### ISSUE TITLE
CronJob pods is not getting clean-up when Job is completed

### ISSUE THREAD

**Issue by sudhir649** [kubernetes/kubernetes#121800]
CronJob pods is not getting clean-up  automatically when Job is completed.

**Comment by sudhir649** [comment]
> I think the documentation is correct. This is either a case where the code isn't behaving as documented, or the code works fine (and you have missed a key step).
> 
> @sudhir649 my _guess_ is you've not set `ttlSecondsAfterFinished`.
> 
> /transfer kubernetes

ttlSecondsAfterFinished is already setup. Many people are getting this issue with CronJob

**Comment by kannon92** [comment]
https://github.com/kubernetes/kubernetes/issues/121502#issue-1960817114

**Comment by sudhir649** [comment]
@kannon92 @sftim 

I can not share the exact yaml file here.
but this is the example, code similar to my yaml

**apiVersion: batch/v1
kind: CronJob
metadata:
  name: testcronjob
spec:
  schedule: "*/2 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 250
      ttlSecondsAfterFinished: 100
      template:
        metadata:
        spec:
          containers:
          - name: test
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: Never**
		  
	






**all pods created by crojob have the status " completed" but are not automatically cleaned up.
it seems like we keep them until they reach a max limit and then PodGC cleans them up?**







kubectl get all -n cronjob
NAME                             READY   STATUS      RESTARTS   AGE
pod/testcronjob-28324442-pzxlw   0/1     Completed   0          16h
pod/testcronjob-28324450-68sv5   0/1     Completed   0          16h
pod/testcronjob-28324456-frtth   0/1     Completed   0          16h
pod/testcronjob-28324476-5mxs9   0/1     Completed   0          16h
pod/testcronjob-28324486-mk8r8   0/1     Completed   0          16h
pod/testcronjob-28324798-tbzln   0/1     Completed   0          10h
pod/testcronjob-28324808-tgfs7   0/1     Completed   0          10h
pod/testcronjob-28324812-f45qt   0/1     Completed   0          10h
pod/testcronjob-28324814-z8994   0/1     Completed   0          10h
pod/testcronjob-28324816-w2drb   0/1     Completed   0          10h
pod/testcronjob-28324820-8wrxv   0/1     Completed   0          10h
pod/testcronjob-28324822-jlx6h   0/1     Completed   0          10h
pod/testcronjob-28324824-gnx2z   0/1     Completed   0          10h
pod/testcronjob-28324826-fpnn8   0/1     Completed   0          10h
pod/testcronjob-28324828-tpm9v   0/1     Completed   0          10h
pod/testcronjob-28324830-cwr7d   0/1     Completed   0          10h
pod/testcronjob-28324832-kgd49   0/1     Completed   0          10h
pod/testcronjob-28324834-mvrs8   0/1     Completed   0          10h
pod/testcronjob-28324838-h886f   0/1     Completed   0          10h
pod/testcronjob-28324842-g5f7t   0/1     Completed   0          10h
pod/testcronjob-28324844-qw72q   0/1     Completed   0          10h
pod/testcronjob-28324846-jd2sf   0/1     Completed   0          10h
pod/testcronjob-28324848-vb9wh   0/1     Completed   0          10h
pod/testcronjob-28324850-dbphh   0/1     Completed   0          9h
pod/testcronjob-28324852-5q5cd   0/1     Completed   0          9h
pod/testcronjob-28324862-46jf2   0/1     Completed   0          9h
pod/testcronjob-28324866-z8rq8   0/1     Completed   0          9h
pod/testcronjob-28325110-7q7fm   0/1     Completed   0          5h39m
pod/testcronjob-28325112-hmn84   0/1     Completed   0          5h37m
pod/testcronjob-28325114-jt4c8   0/1     Completed   0          5h35m
pod/testcronjob-28325160-2c9pb   0/1     Completed   0          4h49m
pod/testcronjob-28325182-b8kjl   0/1     Completed   0          4h27m
pod/testcronjob-28325190-qpbgv   0/1     Completed   0          4h19m
pod/testcronjob-28325196-rm2fx   0/1     Completed   0          4h13m
pod/testcronjob-28325198-rdrmq   0/1     Completed   0          4h11m
pod/testcronjob-28325212-tql7p   0/1     Completed   0          3h57m
pod/testcronjob-28325218-465t5   0/1     Completed   0          3h51m
pod/testcronjob-28325226-mlsrz   0/1     Completed   0          3h43m
pod/testcronjob-28325230-5jxnw   0/1     Completed   0          3h39m
pod/testcronjob-28325232-qs4jr   0/1     Completed   0          3h37m
pod/testcronjob-28325234-9x5j6   0/1     Completed   0          3h35m
pod/testcronjob-28325238-7pddx   0/1     Completed   0          3h31m
pod/testcronjob-28325244-mctzm   0/1     Completed   0          3h25m
pod/testcronjob-28325252-4svzt   0/1     Completed   0          3h17m
pod/testcronjob-28325258-gl77z   0/1     Completed   0          3h11m
pod/testcronjob-28325260-jnxht   0/1     Completed   0          3h9m
pod/testcronjob-28325262-v6fv4   0/1     Completed   0          3h7m
pod/testcronjob-28325272-5zn66   0/1     Completed   0          177m
pod/testcronjob-28325280-n27fl   0/1     Completed   0          169m
pod/testcronjob-28325292-2s866   0/1     Completed   0          157m
pod/testcronjob-28325304-t4rg9   0/1     Completed   0          145m
pod/testcronjob-28325308-cgdsh   0/1     Completed   0          141m
pod/testcronjob-28325310-6r7md   0/1     Completed   0          139m
pod/testcronjob-28325318-gvjrn   0/1     Completed   0          131m
pod/testcronjob-28325326-fbrjj   0/1     Completed   0          123m
pod/testcronjob-28325328-tpxls   0/1     Completed   0          121m
pod/testcronjob-28325330-s4d54   0/1     Completed   0          119m
pod/testcronjob-28325332-l6cwv   0/1     Completed   0          117m
pod/testcronjob-28325338-697np   0/1     Completed   0          111m
pod/testcronjob-28325340-wf6j4   0/1     Completed   0          109m
pod/testcronjob-28325350-qmd94   0/1     Completed   0          99m
pod/testcronjob-28325352-6z2rn   0/1     Completed   0          97m
pod/testcronjob-28325354-9zm67   0/1     Completed   0          95m
pod/testcronjob-28325368-kwpf7   0/1     Completed   0          81m
pod/testcronjob-28325378-gv5ts   0/1     Completed   0          71m
pod/testcronjob-28325380-f55l4   0/1     Completed   0          69m
pod/testcronjob-28325382-74xlq   0/1     Completed   0          67m
pod/testcronjob-28325384-2jv5p   0/1     Completed   0          65m
pod/testcronjob-28325390-rxjv8   0/1     Completed   0          59m
pod/testcronjob-28325392-d8qw8   0/1     Completed   0          57m
pod/testcronjob-28325394-4fb2s   0/1     Completed   0          55m
pod/testcronjob-28325396-m96f7   0/1     Completed   0          53m
pod/testcronjob-28325398-r4wsl   0/1     Completed   0          51m
pod/testcronjob-28325400-bsrs2   0/1     Completed   0          49m
pod/testcronjob-28325408-mr8cf   0/1     Completed   0          41m
pod/testcronjob-28325410-jcfr7   0/1     Completed   0          39m
pod/testcronjob-28325412-qvk9j   0/1     Completed   0          37m
pod/testcronjob-28325418-djghg   0/1     Completed   0          31m
pod/testcronjob-28325430-z7jk8   0/1     Completed   0          18m
pod/testcronjob-28325434-j69ds   0/1     Completed   0          15m
pod/testcronjob-28325436-gk9kl   0/1     Completed   0          13m
pod/testcronjob-28325448-dcsf7   0/1     Completed   0          72s

NAME                        SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/testcronjob   */2 * * * *   False     0        81s             18h

NAME                             COMPLETIONS   DURATION   AGE
job.batch/testcronjob-28325428   0/1           21m        21m
job.batch/testcronjob-28325448   1/1           4s         82s

**Comment by sudhir649** [comment]
> /uncc

not able to understand

**Comment by sudhir649** [comment]
@kannon92 

Want to confirm that .
it seems like we keep them until they reach a max limit and then PodGC cleans them up
right?

**Comment by hmeerlo** [comment]
So we all run into this issue at some time but it is just being ignored as not important?
I now have more than a thousand (!) pods in completed state. And yes I have set all the history limits, and it used to work, but it suddenly stopped.

**Comment by dims** [comment]
@hmeerlo if you are able to dig deeper, that would be great!

**Comment by frankjkelly** [comment]
Just experiencing this ourselves as of last week - yes we are setting
```
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
```
and
```
      ttlSecondsAfterFinished: 300
```
Any advice on where to look to "dig deeper". I'm not an SRE by trade.
