### ISSUE TITLE
Kubernetes 1.26.1: Unexplained Authentication Error, Unexpected Resolution, and Certificate Renewal Quandaries

### ISSUE THREAD

**Issue by devopsInterviews** [kubernetes/kubernetes#121853]
### What happened?

We encountered an issue where kubectl commands were failing with authentication-related errors, specifically mentioning the inability to get the current server API group list and a request for the client to provide credentials

For example:

kubectl get ns

returned:

E1108 17:25:17.087455 1494015 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
E1108 17:25:17.089374 1494015 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
E1108 17:25:17.091456 1494015 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
E1108 17:25:17.093366 1494015 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
E1108 17:25:17.095556 1494015 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
error: You must be logged in to the server (the server has asked for the client to provide credentials)

It happend in multiple clusters that were created at the same day a year ago.
During the troubleshooting process, we executed sudo kubeadm certs check-expiration to inspect the expiration status of certificates in the cluster. The output revealed the expiration dates of various certificates, including those used by the control plane components, and confirmed that the Certificate Authorities (CA) had ample time before expiration.

sudo kubeadm certs check-expiration

returned:

[check-expiration] Reading configuration from the cluster...
[check-expiration] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'

CERTIFICATE                EXPIRES                  RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
admin.conf                 Mar 28, 2024 14:23 UTC   140d            ca                      no
apiserver                  Mar 28, 2024 14:22 UTC   140d            ca                      no
apiserver-etcd-client      Mar 28, 2024 14:22 UTC   140d            etcd-ca                 no
apiserver-kubelet-client   Mar 28, 2024 14:22 UTC   140d            ca                      no
controller-manager.conf    Mar 28, 2024 14:22 UTC   140d            ca                      no
etcd-healthcheck-client    Mar 28, 2024 13:45 UTC   140d            etcd-ca                 no
etcd-peer                  Mar 28, 2024 13:45 UTC   140d            etcd-ca                 no
etcd-server                Mar 28, 2024 13:45 UTC   140d            etcd-ca                 no
front-proxy-client         Mar 28, 2024 14:22 UTC   140d            front-proxy-ca          no
scheduler.conf             Mar 28, 2024 14:23 UTC   140d            ca                      no

CERTIFICATE AUTHORITY   EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGED
ca                      Nov 05, 2032 14:55 UTC   8y              no
etcd-ca                 Nov 05, 2032 14:55 UTC   8y              no
front-proxy-ca          Nov 05, 2032 14:55 UTC   8y              no

But we also found that:

sudo openssl x509 -noout -dates -in /var/lib/kubelet/pki/kubelet.crt

returned:

notBefore=Nov  8 13:56:46 2022 GMT
notAfter=Nov  8 13:56:46 2023 GMT

However, when we manually renewed this certificate the issue persisted, and kubectl commands continued to face authentication errors.

This raised questions about the automatic renewal process, as we expected the kubelet certificate to be renewed automatically by the Kubernetes system. Despite having other certificates successfully renewed through manual intervention, the kubelet certificate renewal, which we understood should occur automatically, did not happen. This discrepancy added complexity to the troubleshooting process, leading us to investigate why the expected automatic renewal of the kubelet certificate did not take place. Clarifying this aspect is crucial for understanding the root cause and ensuring the expected behavior of the Kubernetes certificate management system.

The resolution, though its effectiveness remains unclear, involved executing the command sudo kubeadm certs renew all. This command successfully renewed all non-expired certificates, extending their expiration dates. Notably, it did not alter the /var/lib/kubelet/pki/kubelet.crt, which continued to be expired. Despite the kubelet certificate retaining its expired status, the execution of kubectl commands was restored to normal functionality following this renewal process. The reason behind this unexpected behavior, where the renewal of other certificates impacted kubectl even when the kubelet certificate remained expired, remains a point of inquiry.

We did:

sudo kubeadm certs renew all
sudo kubeadm certs check-expiration

And got:

[check-expiration] Reading configuration from the cluster...
[check-expiration] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'

CERTIFICATE                EXPIRES                  RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
admin.conf                 Nov 08, 2024 13:38 UTC   364d            ca                      no
apiserver                  Nov 08, 2024 13:38 UTC   364d            ca                      no
apiserver-etcd-client      Nov 08, 2024 13:38 UTC   364d            etcd-ca                 no
apiserver-kubelet-client   Nov 08, 2024 13:38 UTC   364d            ca                      no
controller-manager.conf    Nov 08, 2024 13:38 UTC   364d            ca                      no
etcd-healthcheck-client    Nov 08, 2024 13:38 UTC   364d            etcd-ca                 no
etcd-peer                  Nov 08, 2024 13:38 UTC   364d            etcd-ca                 no
etcd-server                Nov 08, 2024 13:38 UTC   364d            etcd-ca                 no
front-proxy-client         Nov 08, 2024 13:38 UTC   364d            front-proxy-ca          no
scheduler.conf             Nov 08, 2024 13:38 UTC   364d            ca                      no

CERTIFICATE AUTHORITY   EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGED
ca                      Nov 05, 2032 14:55 UTC   8y              no
etcd-ca                 Nov 05, 2032 14:55 UTC   8y              no
front-proxy-ca          Nov 05, 2032 14:55 UTC   8y              no

We're left with several questions after this experience. First, why did the initial error happen? Second, why did using sudo kubeadm certs renew all fix the problem, even though the kubelet certificate stayed expired? Third, why did renewing non-expired certificates make a difference? We also want to know the best practices for solving this kind of issue and why the automatic renewal, expected in Kubernetes 1.15 and later, didn't happen. These questions highlight the need for a clearer understanding of what occurred and guidance on managing certificates effectively in Kubernetes clusters.

### What did you expect to happen?

We expected that the Kubernetes cluster, running version 1.26.1, would function seamlessly without authentication errors. Additionally, I assumed that the automatic certificate renewal mechanism, introduced in Kubernetes 1.15 and later versions, would appropriately handle the expiration of certificates, including the kubelet certificate. The expectation was for a reliable and self-maintaining system, where certificate-related issues would be mitigated automatically.

### How can we reproduce it (as minimally and precisely as possible)?

Set up a Kubernetes cluster using version 1.26.1 with a specific configuration, including master nodes, worker nodes, and relevant components.
Introduce a scenario that intentionally triggers the authentication error in kubectl commands. This can be achieved by allowing a critical certificate, such as the kubelet certificate at /var/lib/kubelet/pki/kubelet.crt, to expire.

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

None

### OS version

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Container runtime (CRI) and version (if applicable)

crio
version: 1.26.1

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Cilium
version: 1.13.4

**Comment by neolit123** [comment]
> This raised questions about the automatic renewal process, as we expected the kubelet certificate to be renewed automatically by the Kubernetes system. Despite having other certificates successfully renewed through manual intervention, the kubelet certificate renewal, which we understood should occur automatically, did not happen. 

kubeadm deploys the kubelet with automatic client cert rotation. this works for maybe 90% of users who use the kubeadm stock defaults. the rest of the users use manual rotation and/or external cert signers.

> This discrepancy added complexity to the troubleshooting process, leading us to investigate why the expected automatic renewal of the kubelet certificate did not take place. Clarifying this aspect is crucial for understanding the root cause and ensuring the expected behavior of the Kubernetes certificate management system.

we have seen cases where this happens. likely due to clock drift or other system settings that prevent the kubelet client cert rotation to trigger. sig auth / sig node can maybe provide guidance on what are all the conditions that can prevent the rotation from happening. there isn't much else what we can do here.
https://kubernetes.io/docs/tasks/tls/certificate-rotation/

/sig auth node

> The resolution, though its effectiveness remains unclear, involved executing the command sudo kubeadm certs renew all. This command successfully renewed all non-expired certificates, extending their expiration dates. Notably, it did not alter the /var/lib/kubelet/pki/kubelet.crt, which continued to be expired. De

the process of getting out of an expired kubelet client cert is different. did you see this document?
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubelet-client-cert

> Despite the kubelet certificate retaining its expired status, the execution of kubectl commands was restored to normal functionality following this renewal process. The reason behind this unexpected behavior, where the renewal of other certificates impacted kubectl even when the kubelet certificate remained expired, remains a point of inquiry.

the kubelet client certificate is for the kubelet -> apiserver connection and due to the automatic rotation `kubeadm certs renew` does not renew it. some kubectl commands may work without this certificate.

/kind support documentation

**Comment by devopsInterviews** [comment]
@neolit123 Thanks for the response!

I still find it hard to understand how renewing the rest of the certificates (which were not expired), solved the issue.
Because the kubelet.crt was still expired.

Also, the rest of the certificates also has automatic rotation (beside the kubelet)?

I saw on stackoverflow someone using those flags in the kubeadm configuration file:
--rotate-certificates=true and --rotate-server-certificates=true
Are those necessary for the process?

I don't see any reason for the rotation to not work..
Either way, the main question remains unclear.. How when we renew the rest of the certificates that were ok the kubectl seems to work just fine.

**Comment by neolit123** [comment]
> I still find it hard to understand how renewing the rest of the certificates (which were not expired), solved the issue.
Because the kubelet.crt was still expired.

renewing the rest of the certs is not related to renewal of the kubele client cert.
like i said, kubectl might work for some use cases without a valid kubelet client cert.

> Also, the rest of the certificates also has automatic rotation (beside the kubelet)?

`kubeadm upgrade` will by default rotate all the certs that it needs (except kubelet client cert).
so if you are upgrading your kubeadm cluster you will get new certs, if not the certs must be rotated manually.

> I saw on stackoverflow someone using those flags in the kubeadm configuration file:
--rotate-certificates=true and --rotate-server-certificates=true
Are those necessary for the process?

kubeadm by default only enables the client cert rotation (first option).
https://kubernetes.io/docs/tasks/tls/certificate-rotation/

> I don't see any reason for the rotation to not work..
Either way, the main question remains unclear.. How when we renew the rest of the certificates that were ok the kubectl seems to work just fine?

i don't think that's a related issue.

please mind that we do not use github for providing support:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

after further examination, closing as a support ticket.
/close

if you wish the maintainers to document more aspects in:
https://kubernetes.io/docs/tasks/tls/certificate-rotation/
such as known failure scenarios.
please log a new ticket in kubernetes/website and tag it with `/sig auth node`.

**Comment by devopsInterviews** [comment]
Hi @neolit123 , I didn't understand why you closed the ticket..
I'm unable to proceed working on my Kubernetes clusters without knowing what's going on in there.
This is obviously an issue and I believe the community needs to check it.
Some of my clusters are still down with an issue that hasn't been explained.
I would appreciate if you will reopen the ticket and let other people the option to see that and help me. 
Maybe someone from the /sig auth can take a look at this?
