### ISSUE TITLE
1.29 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by fsmunoz** [kubernetes/kubernetes#121886]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.29 Release Notes. If you know of issues or API changes that are going out in 1.29, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @kubernetes/release-team-release-notes 

/sig release
/milestone v1.29

**Comment by pacoxu** [comment]
> We also want to highlight that Evented PLEG beta feature that is disabled by default have a critical bug: https://github.com/kubernetes/kubernetes/issues/121349#issuecomment-1813029991 that is not resolved yet. We recommend to use extra caution when enabling this feature.

When enabling EventedPLEG feature gate(beta, default false), a static pod with 1 container may have multiple containers up and one running well and the other failed for `port in use` or some other issues.

**Comment by SergeyKanzhelev** [comment]
From SIG Node, originally posted [here](https://github.com/kubernetes/sig-release/discussions/2349#discussioncomment-7581178):

Evented PLEG beta feature that is disabled by default have a critical bug: https://github.com/kubernetes/kubernetes/issues/121349#issuecomment-1813029991 that is not resolved yet. We recommend to use extra caution when enabling this feature.

**Comment by fsmunoz** [comment]
Closing, release date is near.  Please reopen if anything urgent comes up between now and the release.

/close
