### ISSUE TITLE
Image pull from private registry fails because of missing credentials

### ISSUE THREAD

**Issue by danigian** [kubernetes/kubernetes#121827]
### What happened?

When trying to pull a image from a private registry the request is executed without any kind of authorization.

The secret is manually created with
`kubectl create secret generic regcred --from-file=.dockerconfigjson=dc.json --type=kubernetes.io/dockerconfigjson`

`dc.json` is a file like the following:
```json
{
    "auths": {
        "somecontainerregistry.azurecr.io": {
            "auth": "XYZ"
        }
    }
}
```
where XYZ is the base64 encoding of `:refresh_token` (there is no username as I want to dynamically get a token from a OAuth endpoint)

My pod is then specifying the `imagePullSecret` pointing to the `regcred` from above.

When creating the pod, after setting up a mitmproxy, I can see the following requests:
- HEAD to `https://somecontainerregistry.azurecr.io/v2/whateverimage/manifests/latest` which correctly fails with a 401 and returns a `Www-Authenticate` header set to `Bearer realm="https://somecontainerregistry.azurecr.io/oauth2/token",service="somecontainerregistry.azurecr.io",scope="repository:whateverimage:pull"`
- Then the request to the `/oauth2/token` endpoint is executed. The problem here is that it is executed as a GET (opposed to being a POST) and without the expected URLEncoded form including the refresh_token from the imagePullSecret.

Executing a `HTTPS_PROXY="127.0.0.1:8080" crictl pull --auth "XYZ"  somecontainerregistry.azurecr.io/whateverimage` gives me no issues and the image is pulled successfully.

### What did you expect to happen?

I expected the kubelet and the container runtime to properly talk to each other, but I am either doing something wrong or there is a bug 😄 

### How can we reproduce it (as minimally and precisely as possible)?

- Create an Azure Container Registry (or any image registry that is capable of OAuth AuthN)
- Setup a mitmproxy to watch the outgoing requests
- `kubectl create secret generic regcred --from-file=.dockerconfigjson=dc.json --type=kubernetes.io/dockerconfigjson` where `dc.json` is a file like the following:  
  ```json
  {
      "auths": {
          "somecontainerregistry.azurecr.io": {
              "auth": "XYZ"
          }
      }
  }
  ```  
  (and XYZ is the base64 encoding of `:refresh_token`)
- Create a Pod referencing the imagePullSecret from above
- Check in mitmproxy there are 2 requests, one of the two should be a HEAD to `/v2/whateverimage/manifests/latest` and the other should be a POST (not a GET as above)

### Kubernetes version

<details>
Client Version: v1.27.7+k3s2
Kustomize Version: v5.0.1
Server Version: v1.27.7+k3s2
</details>

### Cloud provider

<details>
Should not be relevant, but the tests were executed on an Azure VM (with k3s on it)
</details>

### OS version

<details>
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Linux k3s 6.2.0-1016-azure #16~22.04.1-Ubuntu SMP Tue Oct 10 17:11:51 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Version:  0.1.0  

RuntimeName:  containerd
RuntimeVersion:  v1.7.7-k3s1.27
RuntimeApiVersion:  v1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
@HirazawaUi please talk to the k3s folks first. this repo is for future development of k8s and not for support per se.

/close

**Comment by danigian** [comment]
@dims I am not sure why you are saying this is related to k3s. I am having the exact same issue also with microk8s.
What's the process to understand whether this is a bug in k8s or whether I am doing something wrong? Is there anyone who I can chat with?

**Comment by dims** [comment]
@danigian we test everything in this repository using `kind` / `kubeadm` and few other similar things. We do not know or touch any other deployers or distros. Any bugs will need to be triaged by the distros before being escalated back here if it is truly something that is a fault of code in this repository. Even if you run into trouble with `kind` we would want you to talk to `kind` folks before you come back here. Apologies.

https://github.com/kubernetes/kubernetes/blob/ca5c522080bc62e2e6387516a605c24bb513256b/SUPPORT.md
