### ISSUE TITLE
Pod "xxx" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[* ].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)

### ISSUE THREAD

**Issue by allenhaozi** [kubernetes/kubernetes#121855]
### What happened?

update a pod annotation, got the following errors:
```
Pod "xxxx" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*
].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
```

### What did you expect to happen?

update successful

### How can we reproduce it (as minimally and precisely as possible)?

1. MutatingWebhook update the pod
2. another service patch this pod annotion failed

### Kubernetes version

v1.21.13

### Cloud provider

<details>
private
</details>

### Install tools

<details>
kbuespray
</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
flannel
</details>

**Comment by T-Lakshmi** [comment]
**Page:** https://kubernetes.io/docs/concepts/workloads/pods/#pod-update-and-replacement

**Comment by T-Lakshmi** [comment]
@allenhaozi,
I don't think there is any wired behaviour on it. As per kubernetes documentation, while updating pods there are certain limitations. 

> Pod updates may not change fields other than spec.containers[*].image, spec.initContainers[*].image, spec.activeDeadlineSeconds or spec.tolerations. For spec.tolerations, you can only add new entries.

This is one of the expected behaviour.
