### ISSUE TITLE
How to wait for new pods status to running then kill old pods, when execute rolling-update?

### ISSUE THREAD

**Issue by dereknex** [kubernetes/kubernetes#12183]
Now it seems that if the new pod status is pending the old pod will be killed.

**Comment by smarterclayton** [comment]
This is intended to be fixed by changes to rolling update here https://github.com/GoogleCloudPlatform/kubernetes/pull/11942

**Comment by bgrant0607** [comment]
Dupe of #11484.

The experimental Deployment API will provide this functionality in 1.1.
