### ISSUE TITLE
Support having ExternalIP in node spec.addresses on baremetal

### ISSUE THREAD

**Issue by dm3ch** [kubernetes/kubernetes#121971]
I would like to be able to provide not only InternalIP but also an ExternalIP.

I tried to add address to `spec.addresses` array manually via kubectl edit, but as far as I understood it's overridden immediately (? by kubelet I suppose).

As far as I understood from code and documentation, currently it's not possible to get ExternalIP address if you don't have a Cloud Controller Manager providing this information.

Having an ExternalIP in node spec could be useful for bare-metal cluster holders, to use k8s as a inventory source for k8s nodes.

**Comment by aojea** [comment]
/close

Duplicate of https://github.com/kubernetes/kubernetes/issues/42125

**Comment by dm3ch** [comment]
@aojea missed it, TY

**Comment by aojea** [comment]
> @aojea missed it, TY

no worries, it was not easy to find , it is from 2017 ;) ,
