### ISSUE TITLE
After installing the k8s cluster, the latency of the host will increase

### ISSUE THREAD

**Issue by smallemployees** [kubernetes/kubernetes#121960]
### What happened?

After installing the k8s cluster, the latency of the host will increase

### What did you expect to happen?

How to find the cause of the delay

### How can we reproduce it (as minimally and precisely as possible)?

Install a bare metal K8S cluster and then ping the host IP

### Kubernetes version

<details>

```console
$ kubectl version
v1.23.6
# paste output here
```

</details>

### Cloud provider

<details>
![Uploading 64d09c2182638ff5df44f0b80862e55.png…]()

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/remove-kind bug

a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
