### ISSUE TITLE
scheduling_algorithm_duration_seconds only reported for successful scheduling attempts

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#121969]
### What happened?

schedulingCycle only reports algorithm_duration when it's a successful scheduling attempt:
https://github.com/kubernetes/kubernetes/blob/ec5096fa869b801d6eb1bf019819287ca61edc4d/pkg/scheduler/schedule_one.go#L190

### What did you expect to happen?

Also report scheduling algorithm latency when the pods is unschedulable

### How can we reproduce it (as minimally and precisely as possible)?

Create a Pod that is unschedulable (perhaps node selector for a node that doesn't exist) and observe metrics

### Kubernetes version

<details>

ANY

</details>

### Cloud provider

<details>
ANY
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by olderTaoist** [comment]
let me try
