### ISSUE TITLE
Running conformance test on 1.29.0-alpha.3 cluster with sonobuoy fails 

### ISSUE THREAD

**Issue by tnqn** [kubernetes/kubernetes#121985]
### What happened?

@rtheis reported that conformance testing with the latest version of sonobuoy against a version 1.29.0-alpha.3 cluster fails on the support the 1.17 Sample API Server using the current Aggregator test: https://github.com/kubernetes/kubernetes/pull/121283#issuecomment-1812399851, related to https://github.com/kubernetes/kubernetes/pull/121283.

I found the reason why the test is working fine in Kubernetes CI jobs but fails with sonobuoy is because **the service account used by sonobuoy "sonobuoy-serviceaccount" doesn't have read permission of the non-resource url "/"**, which is used by the test to confirm the removal of group path:
https://github.com/kubernetes/kubernetes/blob/ec5096fa869b801d6eb1bf019819287ca61edc4d/test/e2e/apimachinery/aggregator.go#L744-L746

```
I1121 14:31:40.149085       1 rbac.go:119] RBAC: no rules authorize user "system:serviceaccount:sonobuoy:sonobuoy-serviceaccount" with groups ["system:serviceaccounts" "system:serviceaccounts:son
thenticated"] to "get" nonResourceURL "/" cluster-wide
I1121 14:31:40.149099       1 authorization.go:87] "Forbidden" URI="/" reason=""
I1121 14:31:40.149218       1 httplog.go:132] "HTTP" verb="GET" URI="/" latency="327.429µs" userAgent="e2e.test/v1.29.0 (linux/amd64) kubernetes/1f69e12 -- [sig-api-machinery] Aggregator Should b
 the 1.17 Sample API Server using the current Aggregator [Conformance]" audit-ID="46c27282-7af6-48d1-bf3e-ca439c57bc92" srcIP="172.18.0.4:36878" apf_pl="workload-low" apf_fs="service-accounts" ap
eats=0 apf_additionalLatency="0s" apf_execution_time="105.94µs" resp=403
```

The permission of "sonobuoy-serviceaccount" is as below:
https://github.com/vmware-tanzu/sonobuoy/blob/6f9e27f1795f10475c9f6f5decdff692e1e228da/pkg/client/gen.go#L502-L505
```
cr.Rules = []v1.PolicyRule{
	{
		APIGroups: []string{"*"},
		Resources: []string{"*"},
		Verbs:     []string{"*"},
	},
	{
		NonResourceURLs: []string{"/metrics", "/logs", "/logs/*"},
		Verbs:           []string{"get"},
	},
}
```

There may be two ways to fix it:
1. Update the RBAC rule of sonobuoy to include "get" of "/". However, could other test runners encounter this issue? Is there a doc listing the required permissions for running e2e tests?
2. Update the e2e to skip checking the removal of the group path if the service account doesn't have permission to access the root path.

Which way do we usually prefer? 

### What did you expect to happen?

Running e2e with sonobuoy should succeed.

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy a v1.29.0-alpha.3 cluster.
2. Run `sonobuoy run --e2e-focus "Sample API Server using the current Aggregator"`

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"29+", GitVersion:"v1.29.0-alpha.3", GitCommit:"1f69e121482db6664e4a1c1d21ec4dcf2b36b080", GitTreeState:"clean", BuildDate:"2023-11-02T18:24:31Z", Go
", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tnqn** [comment]
> 2\. Update the e2e to skip checking the removal of the group path if the service account doesn't have permission to access the root path.

https://github.com/kubernetes/kubernetes/pull/121986 implemented this solution.

**Comment by neolit123** [comment]
> > 2. Update the e2e to skip checking the removal of the group path if the service account doesn't have permission to access the root path.
> 
> #121986 implemented this solution.

/sig api-machinery

**Comment by rtheis** [comment]
@tnqn thank you for opening this issue and working on a solution. I'm probably not the right person to decide on which solution is preferred. From my perspective, either solution is fine.

**Comment by BenTheElder** [comment]
Note: Sonobuoy is not owned by any Kubernetes SIG. 
At most it is between SIG Architecture and the CNCF to choose whether to recommend it for running tests.
SIG Testing owns the e2e image that sonobuoy can be used to schedule but not sonobuoy.

IMHO this is a bug in running the tests via a pod, which is not how we develop the tests (they're run outside the cluster, by a cluster admin account typically).

I would say 1) is the correct answer. xref: https://github.com/kubernetes/kubernetes/pull/121986#discussion_r1401231672

/sig architecture
/sig testing
/triage accepted

cc @johnbelamaric @Riaankl

**Comment by tnqn** [comment]
> IMHO this is a bug in running the tests via a pod, which is not how we develop the tests (they're run outside the cluster, by a cluster admin account typically).
> 
> I would say 1) is the correct answer. xref: [#121986 (comment)](https://github.com/kubernetes/kubernetes/pull/121986#discussion_r1401231672)

@BenTheElder thanks for your comment. I guess 1) means non of the existing sonobuoy versions can pass K8s conformance test against a cluster > 1.29.0-alpha3, as the RBAC rule is hardcoded. I will file an issue to sonobuoy first.

**Comment by neolit123** [comment]
question here is what are the set of client permissions required to run the conformance suite?
perhaps a `cluster-admin`  level of access or a more granular recommendation should be documented.

@sttts what is your take on the root path requirement as approver for:
https://github.com/kubernetes/kubernetes/pull/121283/files#diff-d9472590663e3c095a5e1f62d1483eb7cda4f61fc725daebb0934db5f5bccdd8R744-R746

**Comment by BenTheElder** [comment]
> perhaps a cluster-admin level of access or a more granular recommendation should be documented.

I agree, we already require e.g. privileged pods for a long time in conformance tests and we should make it clear that we expect a highly privileged client.

**Comment by sttts** [comment]
@neolit123 +1 for what @BenTheElder is saying, that we should expect that the user running the tests has required permissions. These tests are not built for being run unprivileged.

**Comment by neolit123** [comment]
i wanted to PR the admin note in our conformance docs under sig-arch, but then i saw this:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md

> it is non-privileged (e.g., does not require root on nodes, access to raw network interfaces, or cluster admin permissions)

so https://github.com/kubernetes/kubernetes/pull/121283 broke this guarantee.
sounds like SIG Arch needs to comment.

**Comment by sttts** [comment]
> so https://github.com/kubernetes/kubernetes/pull/121283 broke this guarantee.

This statement surprises me. Root discovery is one of the least-privileged permission you can have on a cluster. For years this was even open for unauthorized users on the internet (if your api endpoint has been exposed).

In other words, just add the `/` permission. While thinking about it, it is surprising that the user in question does not have this access already. Don't we allow that for every authorized user?

**Comment by sttts** [comment]
In contrast, I hope that lots of privileged operations are tested by conformance today. If we don't test things like admission webhooks for example, we have much bigger problems. And admission webhooks are basically equivalent to cluster-admin.

**Comment by aojea** [comment]
> i wanted to PR the admin note in our conformance docs under sig-arch, but then i saw this: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md
> 
> > it is non-privileged (e.g., does not require root on nodes, access to raw network interfaces, or cluster admin permissions)
> 
> so #121283 broke this guarantee. sounds like SIG Arch needs to comment.

that is outdated, we use hostNetwork pods one some of the tests IIRC

**Comment by neolit123** [comment]
> In other words, just add the / permission. While thinking about it, it is surprising that the user in question does not have this access already. Don't we allow that for every authorized user?

looks like we don't.

```bash
$ kubectl get clusterrole cluster-admin -o yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2023-11-24T18:34:38Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cluster-admin
  resourceVersion: "1206"
  uid: 13836a28-6c0d-4008-b566-bb528011e6e0
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - /api # <------------- modified from the default of '*'
  verbs:
  - '*'

$ kubectl get --raw /
Error from server (Forbidden): forbidden: User "kubernetes-admin" cannot get path "/"

$ kubectl get --raw /api
{"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.0.2.15:6443"}]}
```

> In contrast, I hope that lots of privileged operations are tested by conformance today. If we don't test things like admission webhooks for example, we have much bigger problems. And admission webhooks are basically equivalent to cluster-admin.

before this ticket, i was under the impression that the conformance suite already requires admin and that all testers (like Sonobuoy) use admin level credentials.

>> it is non-privileged (e.g., does not require root on nodes, access to raw network interfaces, or cluster admin permissions)

> that is outdated, we use hostNetwork pods one some of the tests IIRC

looks like we may have to change that sentence completely.

**Comment by sttts** [comment]
Would have expected it here:
```yaml
		{
			// a role which provides just enough power to determine if the server is
			// ready and discover API versions for negotiation
			ObjectMeta: metav1.ObjectMeta{Name: "system:discovery"},
			Rules: []rbacv1.PolicyRule{
				rbacv1helpers.NewRule("get").URLs(
					"/livez", "/readyz", "/healthz",
					"/version", "/version/",
					"/openapi", "/openapi/*",
					"/api", "/api/*",
					"/apis", "/apis/*",
				).RuleOrDie(),
			},
		},
```

**Comment by liggitt** [comment]
adding to milestone and making release blocking ... we should not release 1.29 in a state that the most commonly used conformance tool will fail

**Comment by BenTheElder** [comment]
IMO we should clarify the state and go fix the tool, but we should keep the test and we should NOT add skip.

Conformance docs are not a release artifact, and sonobuoy release lifecycle is not a conformance artifact.

If we can't get sonobuoy working in a reasonable time, we already know the tests can be run by scheduling the image (which is ours) directly with kubectl instead and we can document that in the upstream conformance docs.

https://github.com/kubernetes/kubernetes/blob/master/test/conformance/image/conformance-e2e.sh
https://github.com/kubernetes/kubernetes/blob/master/test/conformance/image/conformance-e2e.yaml

We need to fix the for this image: https://testgrid.k8s.io/sig-testing-kind#conformance-image,%20master%20(dev)
And it should probably be added to release-blocking in the future.

**Comment by liggitt** [comment]
I opened https://github.com/kubernetes/kubernetes/pull/122129 to revert the e2e change and move the functional test to an integration test

**Comment by BenTheElder** [comment]
Filed https://github.com/kubernetes/test-infra/pull/31343 to try to get the image job passing again.

**Comment by BenTheElder** [comment]
We probably need another issue to track 1.30 follow-up?

**Comment by tnqn** [comment]
> We probably need another issue to track 1.30 follow-up?

@BenTheElder If no one has done it, I could create another issue and follow up with the items that have been discussed here:
1. Update outdated privilege requirement in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md.
2. Make commonly used conformance tools like sonobuoy aware of the required priviledge to avoid similar situations in the future.
3. Add permission of GET "/" to authorized users via the `system:discovery` role for root discovery.
