### ISSUE TITLE
Add "action" property to NetworkPolicySpec

### ISSUE THREAD

**Issue by SineSwiper** [kubernetes/kubernetes#121945]
### What would you like to be added?

Add an `action` property to NetworkPolicySpec, which is an enum described as such:

* `accept` - Accept the packet
* `drop` - Drop the packet, allowing for a timeout on the other side
* `reject` - Immediately send back an error packet (such as a TCP RST)

For `iptables`, this would closely match the ACCEPT, DROP, REJECT actions, respectively.

This property could be expanded to include other actions, such as `log`, if they are compatible with the underlying sub-systems, either in the new feature, or future feature requests.

### Why is this needed?

The existing [NetworkPolicySpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#networkpolicyspec-v1-networking-k8s-io) has an implied action here described here:

> Outgoing traffic is allowed if there are no NetworkPolicies selecting the pod (and cluster policy otherwise allows the traffic), OR if the traffic matches at least one egress rule across all of the NetworkPolicy objects whose podSelector matches the pod. If this field is empty then this NetworkPolicy limits all outgoing traffic (and serves solely to ensure that the pods it selects are isolated by default).

So, the action taken for a given network policy is not explicitly declared, and could change depending on if the rules are removed or added.

This implied action is confusing, prone to error, and can lead to security mistakes.  Most firewall software, whether it's Layer 4 devices or Layer 7 WAFs, has some sort of explicit action field to communicate exactly what will happen if it matches a rule or ruleset.

Furthermore, there is no option to reject packets, which can be a more useful troubleshooting step, as it does not require waiting for timeouts from the client side, and has a more specific error message.

**Comment by oxxenix** [comment]
@SineSwiper hello! can I work on the issue?

**Comment by BenTheElder** [comment]
@oxxenix the premise hasn't been accepted by maintainers yet.

NetworkPolicy is owned by SIG Network AFAIK, and this would probably require a KEP https://www.kubernetes.dev/resources/keps/
/remove-sig api-machinery

**Comment by kumarankit999** [comment]
Hey @oxxenix, wait till the issue has a label of triage acceptable

**Comment by astoycos** [comment]
Hiya @SineSwiper!! 

Thanks for opening this.  I completely agree with most of your points working above, however the original Network Policy V1 resource is very stable and unlikely to change majorly anytime soon.

There is good news though! We are working on the "next generation of policy related apis" in the [sig-network-policy-api subgroup](https://network-policy-api.sigs.k8s.io/). 

Additionally as part of that we have an active NPEP (Network Policy Enhancement Proposal) dedicated explicitly to the next gen developer oriented version of policy which you can find here -> https://github.com/kubernetes-sigs/network-policy-api/pull/162

Please come get involved and make sure we're covering your use cases in the design process!

**Comment by astoycos** [comment]
Closing this based on the previous comment 👍
