### ISSUE TITLE
[Flaking Test] Conformance-GCE-master-kubetest2 (client rate limiter Wait returned an error)

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#121911]
##### Error text:
```
[FAILED] client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
In [It] at: test/e2e/apimachinery/resource_quota.go:1191 @ 11/09/23 14:53:30.003

```

TestGrid: https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master%20-%20kubetest2

#### Recent failures:
[11/15/2023, 5:50:05 PM ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1724764199302729728)
[11/15/2023, 1:48:47 PM ci-kubernetes-gce-conformance-latest-kubetest2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1724702794104967168)
[11/15/2023, 10:47:10 AM ci-kubernetes-gce-conformance-latest-kubetest2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1724657243439239168)
[11/15/2023, 4:20:04 AM ci-kubernetes-e2e-ubuntu-gce-network-policies](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-network-policies/1724560355511767040)
[11/15/2023, 3:54:04 AM ci-cos-containerd-e2e-cos-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-e2e-cos-gce/1724553810191323136)

/kind flake

/sig api-machinery

**Comment by aojea** [comment]
checking https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1724764199302729728

```
Nov 15 12:30:55.571: INFO: Found resourceQuota "e2e-rq-status-rblx9" in namespace "resourcequota-3464" with hard status: v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:2, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"2", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:2147483648, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"2Gi", Format:"BinarySI"}}
Nov 15 12:35:55.571: INFO: Unexpected error: 
    <*fmt.wrapError | 0xc0053968e0>: 
    client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
    {
        msg: "client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline",
        err: <*errors.errorString | 0xc0052b2f30>{
            s: "rate: Wait(n=1) would exceed context deadline",
        },
    }
E1115 12:35:55.572209   10473 runtime.go:79] Observed a panic: types.GinkgoError{Heading:"Your Test Panicked", Message:"When you, or your assertion library, calls Ginkgo's Fail(),\nGinkgo panics to prevent subsequent assertions from running.\n\nNormally Ginkgo rescues this panic so you shouldn't see it.\n\nHowever, if you make an assertion in a goroutine, Ginkgo can't capture the panic.\nTo circumvent this, you should call\n\n\tdefer GinkgoRecover()\n\nat the top of the goroutine that caused this panic.\n\nAlternatively, you may have made an assertion outside of a Ginkgo\nleaf node (e.g. in a container node or some out-of-band function) - please move your assertion to\nan appropriate Ginkgo node (e.g. a BeforeSuite, BeforeEach, It, etc...).", DocLink:"mental-model-how-ginkgo-handles-failure", CodeLocation:types.CodeLocation{FileName:"test/e2e/apimachinery/resource_quota.go", LineNumber:1191, FullStackTrace:"k8s.io/kubernetes/test/e2e/apimachinery.glob..func22.15.6({0x789e128?, 0xc0003544d0?})\n\ttest/e2e/apimachinery/resource_quota.go:1191 +0x85\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2(0xc00295ea90?, {0x789e128?, 0xc0003544d0?})\n\tvendor/k8s.io/apimachinery/pkg/util/wait/loop.go:87 +0x52\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext({0x789e128, 0xc0003544d0}, {0x7887ec8?, 0xc0010605c0}, 0x1, 0x0, 0xc0000c0800?)\n\tvendor/k8s.io/apimachinery/pkg/util/wait/loop.go:88 +0x247\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollUntilContextTimeout({0x7f9bac644008?, 0xc0023a2b10?}, 0x12a05f200, 0xc0020c9560?, 0x80?, 0xc0054830e0?)\n\tvendor/k8s.io/apimachinery/pkg/util/wait/poll.go:48 +0x98\nk8s.io/kubernetes/test/e2e/apimachinery.glob..func22.15({0x7f9bac644008?, 0xc0023a2b10})\n\ttest/e2e/apimachinery/resource_quota.go:1189 +0x4686", CustomMessage:""}} (�[1m�[38;5;9mYour Test Panicked�[0m
�[38;5;243mtest/e2e/apimachinery/resource_quota.go:1191�[0m
  When you, or your assertion library, calls Ginkgo's Fail(),
  Ginkgo panics to prevent subsequent assertions from running.

  Normally Ginkgo rescues this panic so you shouldn't see it.

  However, if you make an assertion in a goroutine, Ginkgo can't capture the
  panic.
  To circumvent this, you should call

  	defer GinkgoRecover()

  at the top of the goroutine that caused this panic.

  Alternatively, you may have made an assertion outside of a Ginkgo
  leaf node (e.g. in a container node or some out-of-band function) - please
  move your assertion to
  an appropriate Ginkgo node (e.g. a BeforeSuite, BeforeEach, It, etc...).

  �[1mLearn more at:�[0m
  �[38;5;14m�[4mhttp://onsi.github.io/ginkgo/#mental-model-how-ginkgo-handles-failure�[0m
```

there is a ginkgo panic, independently of this issue, @pohly is it normal that we panic on these cases?

https://github.com/kubernetes/kubernetes/blob/8254569d50d6bbe8d60bcdfb16eac337f6e60514/test/e2e/apimachinery/resource_quota.go#L1191

coming back to the issue, the error comes from https://github.com/kubernetes/kubernetes/blob/8254569d50d6bbe8d60bcdfb16eac337f6e60514/staging/src/k8s.io/client-go/rest/request.go#L616

I couldn't spend much time, but we need to understand why the ratelimiter errors

**Comment by pacoxu** [comment]
https://storage.googleapis.com/k8s-triage/index.html?date=2023-10-20&test=ResourceQuota%20should%20apply%20changes%20to%20a%20resourcequota%20status#c538bc0857d4164bb14a

https://github.com/kubernetes/kubernetes/pull/121365/files#diff-e1a46008c4ddbb9f83858cb22ce56ca0f820b78142a1e8abbbb11aa59127a09bR1188

Before it, we use PollImmediateWithContext will not return context err.
After it, we use PollUntilContextTimeout and it may fail for context deadline exceeded .

**Comment by aojea** [comment]
There is something odd  here, why they will exceed the deadline , it is just the second try 

https://github.com/kubernetes/kubernetes/blob/8254569d50d6bbe8d60bcdfb16eac337f6e60514/test/e2e/apimachinery/resource_quota.go#L1189-L1191

I noticed previous loops use a different timeout 

https://github.com/kubernetes/kubernetes/blob/8254569d50d6bbe8d60bcdfb16eac337f6e60514/test/e2e/apimachinery/resource_quota.go#L1171-L1173

@pohly is it possible that we are using the wrong context here? if that is the case, why it cancel the request in flight?

**Comment by pohly** [comment]
@aojea: Using assertions inside a `wait.Poll` callback as in https://github.com/kubernetes/kubernetes/blob/8254569d50d6bbe8d60bcdfb16eac337f6e60514/test/e2e/apimachinery/resource_quota.go#L1189-L1191 is wrong. An error should be returned instead. Or better yet, don't use `wait.Poll`...

An assertion inside a `gomega.Eventually` is not idea either, but I think `gomega.Eventually` would handle it better than `wait.Poll` .

**Comment by pohly** [comment]
> is it possible that we are using the wrong context here?

The context is the one from
https://github.com/kubernetes/kubernetes/blob/8254569d50d6bbe8d60bcdfb16eac337f6e60514/test/e2e/apimachinery/resource_quota.go#L1015

That looks right to me. In https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-learner-mode-latest/1715168333977882624, there is a "normal" `context deadline exceeded`, but given the lack of information in the log output it is impossible to tell how long it has been polling.

> it is just the second try

`Wait returned an error: rate: Wait(n=1) would exceed context deadline` seems normal to me, too, if `Get` is called shortly before the 5 min timeout. The `n=1` then isn't the number of times that `PollUntilContextTimeout` polled, it's the number of times that the rate limiter retried the `Get`.

Where did you

**Comment by pacoxu** [comment]
> An assertion inside a `gomega.Eventually` is not idea either

@carlory mentioned that as well and https://github.com/kubernetes/kubernetes/pull/121861#discussion_r1392089576

This may finally be changed to something like below:

>   gomega.Eventually(ctx, func(ctx context.Context) (book Book, err error) {
>       // Retrieve book from API server and return it.
>       ...
>    }).WithPolling(5 * time.Second).WithTimeout(30 * time.Second).
>    Should(gomega.HaveField("Author.DOB.Year()", BeNumerically("<", 1900)))

**Comment by aojea** [comment]
> but given the lack of information in the log output it is impossible to tell how long it has been polling.

```
Oct 20 01:09:40.654: INFO: Found resourceQuota "e2e-rq-status-jsqhh" in namespace "resourcequota-8" with hard status: v1.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:2, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"2", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:2147483648, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"2Gi", Format:"BinarySI"}}
Oct 20 01:14:40.655: INFO: Unexpected error: 
    <context.deadlineExceededError>: 
    context deadline exceeded
```

ok, so it really times out, there is a 5 mins gap, between the error  and the previous log

**Comment by aojea** [comment]
> That looks right to me. In https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-learner-mode-latest/1715168333977882624, t

don't use these jobs to debug this problem, those create a multi master cluster and there is a loadbalancer in between that makes it hard to debug,

**Comment by carlory** [comment]
@pacoxu `Consistently` + `framework.HandleRetry` should work together to fix this issue.

FYI: https://github.com/kubernetes/kubernetes/pull/121916/files#diff-562f7c9728486282388de5492716c4141fa0823720206e125b3d89593968ca28R493

**Comment by pohly** [comment]
Reporting the timeout will become better, but it doesn't help when the expected state really isn't reached.

**Comment by pohly** [comment]
Given that there is additional checking in https://github.com/kubernetes/kubernetes/blob/8254569d50d6bbe8d60bcdfb16eac337f6e60514/test/e2e/apimachinery/resource_quota.go#L1194-L1195 it might be best to use a custom matcher that is specific to this particular test.

**Comment by pohly** [comment]
Another idea that I keep coming back to, but haven't turned into an issue or some actual code: if some failure occurs, then we need to know about the state of the cluster and events that may have been relevant for the test.

https://github.com/kubernetes/kubernetes/blob/8254569d50d6bbe8d60bcdfb16eac337f6e60514/test/e2e/apimachinery/resource_quota.go#L1171-L1186
was written to gather such information. I think it would be nicer if this was part of a report after a failure. That report then can also be more detailed than log messages that get written regardless of whether the test passes or not.

One way to do that would be to gather events in that watcher in memory instead of logging them and when generating the failure message in the custom matcher, include that information. That would be limited to this test. Ideally, the framework should make that easier or even do it automatically - not sure yet how... perhaps by manipulating the Gingko failure handler while a framework instance is active.

There's one potential downside of not dumping information during a successful run: it becomes impossible to compare a "good" run with a "bad" run. But that's already true today for the CI logs because we discard the log output from "good" runs. For running tests locally, a flag could enable dumping this information also for passing tests. It could even be on by default and only get turned off in the CI? Or perhaps always be enabled?

**Comment by aojea** [comment]
that is already dumped today, isn't it?

**Comment by neolit123** [comment]
> Using assertions inside a wait.Poll callback as in ... is wrong.

yeah, that's broken. it will panic on the first GET call from the RQ client if it fails.
first thing to fix here is to remove all the assertions from the PollUntilContextTimeout handler function.
there could be log messages and/or state can be stored, then once the poll is done state can be asserted outside of the handler.

**Comment by pohly** [comment]
> that is already dumped today, isn't it?

Something is dumped. But I am not sure how complete it is. I think it also only dumps events that still exist. If some were garbage-collected, then they won't show up. Not sure whether that is a problem. Anyway, definitely needs to be looked into.

**Comment by aojea** [comment]
@jpbetz @deads2k I don't know the owner of the resource quota controller, can someone check why the resource quota controller takes more than 5 minutes and fails the test?

**Comment by jpbetz** [comment]
/assign
Having a look

**Comment by neolit123** [comment]
the flake is caused by a metrics-server addon deployment failure?

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1724657243439239168/artifacts/cluster-logs/kt2-9de71057-9277-master/kube-apiserver.log

```
E1115 05:44:21.517932       9 controller.go:146] Error updating APIService "v1beta1.metrics.k8s.io" with err: failed to download v1beta1.metrics.k8s.io: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
```

there is also this:
```
E1115 05:44:20.761279       9 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]"}: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]
I1115 05:44:20.762062       9 httplog.go:132] "HTTP" verb="POST" URI="/api/v1/namespaces/kube-system/pods" latency="11.066026ms" userAgent="kube-controller-manager/v1.29.0 (linux/amd64) kubernetes/7b1c378/system:serviceaccount:kube-system:replicaset-controller" audit-ID="14df6f9f-a3cf-4167-ab5d-6f5ebad34ed5" srcIP="[::1]:53846" apf_pl="workload-high" apf_fs="kube-system-service-accounts" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_execution_time="8.457805ms" resp=500 statusStack=<
	
	goroutine 14264 [running]:
	k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc0052469a0, 0xc00aaad740?)
		vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:319 +0xfa
	k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc0052469a0, 0xc006074b00?)
		vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:299 +0x1d
```

**Comment by jpbetz** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1725201997688213504 is an example of a passing test where the metrics server discovery is failing.

We should probably still figure out why the metrics server is not starting (cc @logicalhan), but it MIGHT be a red herring here.

**Comment by jpbetz** [comment]
I filtered and then diffed the kube-controller-manager logs between a passing test and a failing test, looking for any difference in behavior in the RQ controller, I was not able to observe any difference in behavior from the logs..

**Comment by aojea** [comment]
/assign

Found the race, tricky one

**Comment by aojea** [comment]
ok, my bad, I didn't follow the code right, the resync period for the resource quota controller is an option in

https://github.com/kubernetes/kubernetes/blob/94f15bbbcbe952762b7f5e6e3f77d86ecec7d7c2/cmd/kube-controller-manager/app/core.go#L552

and the default is 5 minutes

https://github.com/kubernetes/kubernetes/blob/94f15bbbcbe952762b7f5e6e3f77d86ecec7d7c2/pkg/controller/resourcequota/config/v1alpha1/defaults.go#L40-L42

that matches with the observation on the failed test , everything adds up now
