### ISSUE TITLE
Kube-proxy not creating iptables rules on 1.28

### ISSUE THREAD

**Issue by jasonaliyetti** [kubernetes/kubernetes#121988]
### What happened?

We created an EKS cluster on 1.28 using kube-proxy in iptables mode, and a majority of nodes fail to become ready.  Kube-proxy is running and not restarting.  On inspection we noticed that kube-proxy logs do not contain errors but looking at iptables (`iptables -t nat -L`) there appear to be no KUBE-SVC chains created.  Some nodes start fine and we see lots of iptables rules configured as expected.

### What did you expect to happen?

KUBE-SVC rules to be created so that networking is functional.

### How can we reproduce it (as minimally and precisely as possible)?

We consistently see this when creating a cluster and adding nodes.

### Anything else we need to know?

iptables output on NotReady node:
```
$ sudo iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
KUBE-POSTROUTING  all  --  anywhere             anywhere             /* kubernetes postrouting rules */

Chain KUBE-KUBELET-CANARY (0 references)
target     prot opt source               destination

Chain KUBE-LOAD-BALANCER (0 references)
target     prot opt source               destination

Chain KUBE-MARK-MASQ (0 references)
target     prot opt source               destination

Chain KUBE-NODE-PORT (0 references)
target     prot opt source               destination

Chain KUBE-POSTROUTING (1 references)
target     prot opt source               destination

Chain KUBE-PROXY-CANARY (0 references)
target     prot opt source               destination

Chain KUBE-SERVICES (2 references)
target     prot opt source               destination
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.3-eks-4f4795d", GitCommit:"e77944ea667aee90c84c48a74a2a0da7a23e0508", GitTreeState:"clean", BuildDate:"2023-10-20T23:21:39Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
$ uname -a
Linux ip-10-34-38-30.ec2.internal 5.15.137-91.144.amzn2.aarch64 #1 SMP Wed Oct 25 18:42:55 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.19
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
kube-proxy v1.28.1-minimal-eksbuild.1

note: we see the same behavior on v1.28.3-minimal-eksbuild.1 as well
</details>

**Comment by aojea** [comment]
> . kube-proxy v1.28.1-minimal-eksbuild.1
note: we see the same behavior on v1.28.3-minimal-eksbuild.1 as well

@dims someone more familiar with the EKS environment?

**Comment by dims** [comment]
@jasonaliyetti please open an AWS service request. There are a lot of moving parts and you are using the managed service!

/close
