### ISSUE TITLE
Access `negotiation.MediaTypeOptions` from `rest.Lister` implementation

### ISSUE THREAD

**Issue by toddtreece** [kubernetes/kubernetes#121966]
### What would you like to be added?

We would like to the ability to access `negotiation.MediaTypeOptions` from within `rest.Lister` implementations.

### Why is this needed?

I am working on a project at Grafana that implements [rest.Lister](https://pkg.go.dev/k8s.io/apiserver@v0.28.2/pkg/registry/rest#Lister) with Grafana's existing SQL backed storage. We are currently using [rest.TableConvertor](https://pkg.go.dev/k8s.io/apiserver@v0.28.2/pkg/registry/rest#TableConvertor) to format the response, but we would like to optimize the SQL query when the user requests the `Table` response format.

For example:
```
kubectl get dashboards
NAME                                   TITLE       CREATED AT
d08ca90a-64c8-459e-b2fc-69d30cb5e01e   example     2023-11-17T19:22:47Z
```

Right now the query would look like:

```sql
SELECT * from dashboard;
```

But if we knew it was a request for the `Table` format, it could be limited to:

```sql
SELECT uid, title, created from dashboard;
```

*Note: In this example `uid` from the dashboard query is used as the K8s object's `metadata.name`.*

It appears that [negotiation.NegotiateOutputMediaType](https://pkg.go.dev/k8s.io/apiserver@v0.28.2/pkg/endpoints/handlers/negotiation#NegotiateOutputMediaType) is what is normally used to determine this, but it’s unclear what to use for the `EndpointRestrictions` argument when implementing `List`. It seems like [handlers.RequestScope](https://pkg.go.dev/k8s.io/apiserver/pkg/endpoints/handlers#RequestScope) is used for `EndpointRestrictions` in the apiserver code, but `handlers.RequestScope` is not accessible from within our `rest.Lister` implementation.

**Comment by toddtreece** [comment]
@sttts i was discussing this earlier with @luxas, and he mentioned that it would be good to ping you for this one.

**Comment by sttts** [comment]
I guess this would break the layering. The `rest.Lister` is operating on the storage version, while the media type options operate on the external version. Also there might be the watch cache wrapping the lister, making this awkward or even wrong to leak it down.

**Comment by toddtreece** [comment]
@sttts that makes sense, and thanks for the additional context
