### ISSUE TITLE
Cassandra containers pending state

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#12197]
I have followed the https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/cassandra to bring up containers but it doesn't seem to be working and shows pending state.

$ kubectl get pods
NAME              READY     STATUS    RESTARTS   AGE
cassandra         0/1       Pending   0          11m
cassandra-ds7v0   0/1       Pending   0          5s

$ kubectl get services
NAME         LABELS                                    SELECTOR         IP(S)           PORT(S)
cassandra    name=cassandra                            name=cassandra   192.168.3.157   9042/TCP
kubernetes   component=apiserver,provider=kubernetes   <none>           192.168.3.1     443/TCP

**Comment by adyanthaya17** [comment]
$ ifconfig
 docker0 Link encap:Ethernet HWaddr 56:84:7a:fe:97:99
 inet addr:172.16.57.1 Bcast:0.0.0.0 Mask:255.255.255.0

and the ip the container is receiving ip 192.168.3.37 as in cluster/ubuntu/config-default.sh

export SERVICE_CLUSTER_IP_RANGE=192.168.3.0/24
 export FLANNEL_NET=172.16.0.0/16

**Comment by yujuhong** [comment]
Please follow the troubleshooting guide for [debugging pods](https://github.com/GoogleCloudPlatform/kubernetes/blob/fd7a48f379fd4f6b0779bdc6db1efb625b1a24d8/docs/user-guide/application-troubleshooting.md#debugging-pods). If that doesn't solve your problem, you could update this issue with more information. Thanks!

**Comment by adyanthaya17** [comment]
Seems like it required time. The starting container took some time but now it's running. I replicated the pods and it ran in few seconds. 

I have a problem tho, how do you access the container with it's IP?

root@test:/home/ubuntu/kubernetes# kubectl get services
NAME         LABELS                                    SELECTOR         IP(S)           PORT(S)
cassandra    name=cassandra                            name=cassandra   192.168.3.151   9042/TCP
kubernetes   component=apiserver,provider=kubernetes   <none>           192.168.3.1     443/TCP

root@test:/home/ubuntu/kubernetes# kubectl get endpoints cassandra
NAME        ENDPOINTS
cassandra   172.17.0.1:9042,172.17.0.2:9042,172.17.0.3:9042 + 1 more...

Neither 192.168.3.x or 17.17.0.x is my external or internal IP of my machine. Is there a way I can access it?

**Comment by yujuhong** [comment]
> Seems like it took a lot of time around an hour for it to get into running state. I replicated the pods and it ran in few seconds.

The only possible explanation I can come up with is that image pulling is slow. Have you tested pulling a similar size of image from gcr.io in your cluster?



> Neither 192.168.3.x or 17.17.0.x is my external or internal IP of my machine. Is there a way I can access it?

Kubernetes uses the IP-per-pod model. Each of your pod will be assigned an IP address routable within your cluster. Please see the [networking doc](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/networking.md) for more details. 

In most cases, you don't need to access the pod IP directly. If you want to execute a command in a pod, you can use kubectl. e.g.,  `kubectl exec -ti <pod_name> -- <cmd>`
You can also access the service, which will be routed to one of the endpoints (pods).
