### ISSUE TITLE
Add status field for ResourceClaimTemplate

### ISSUE THREAD

**Issue by asm582** [kubernetes/kubernetes#121987]
### What would you like to be added?

When claims are made available on the target accelerators the status should be updated on the ResourceClaim object. please find below the suggestion:

```
// ResourceClaimTemplate is used to produce ResourceClaim objects.
type ResourceClaimTemplate struct {
	metav1.TypeMeta
	// Standard object metadata
	// +optional
	metav1.ObjectMeta

	// Describes the ResourceClaim that is to be generated.
	//
	// This field is immutable. A ResourceClaim will get created by the
	// control plane for a Pod when needed and then not get updated
	// anymore.
	Spec ResourceClaimTemplateSpec
       
       //Add status object when the claim is made available on target hardware
       Status ClaimStatus `json:"status,omitempty"`

}
```

### Why is this needed?

DRA performs GPU partitions in two modes: 
- Wait for the first consumer and
- Immediate
In immediate mode, pods may not exist but we have a use case where we want claims to be present apriori. Hence we think the status is key for exercising dra functionality in Immediate mode.

**Comment by ningziwen** [comment]
Are you asking the status of claim or claim template?

If claim, resource claim has it [here](https://github.com/kubernetes/kubernetes/blob/a07b1aaa5b39b351ec8586de800baa5715304a3f/api/openapi-spec/v3/apis__resource.k8s.io__v1alpha2_openapi.json#L286).

Claim template is just a stateless template to be reuse multiple times, like class in programming languages. Claim is the actual object which should have status.
