### ISSUE TITLE
[flaking test][sig-node] NodeProblemDetector should run without error

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#121973]
### Failure cluster [f0cef9ada6202025601f](https://go.k8s.io/triage#f0cef9ada6202025601f)
https://storage.googleapis.com/k8s-triage/index.html?test=NodeProblemDetector%20should%20run%20without%20error

##### Error text:
```
[FAILED] an error on the server ("Internal Error: failed to list pod stats: failed to list all container stats: rpc error: code = NotFound desc = failed to convert to cri containerd stats format: failed to decode container metrics for \"34e999f718280d188dc98de552ec36df97d2ee7649424427cb02dad2be6bd459\": failed to obtain cpu stats: failed to get usage nano cores, containerID: 34e999f718280d188dc98de552ec36df97d2ee7649424427cb02dad2be6bd459: failed to get container ID: 34e999f718280d188dc98de552ec36df97d2ee7649424427cb02dad2be6bd459: not found") has prevented the request from succeeding (get nodes bootstrap-e2e-minion-group-2qzf:10250)
In [It] at: test/e2e/node/node_problem_detector.go:379 @ 11/12/23 04:28:06.191

 Nov 19 22:21:12.806: INFO: Unexpected error: 
      <*errors.StatusError | 0xc00358c280>: 
      an error on the server ("Internal Error: failed to list pod stats: failed to list all container stats: rpc error: code = NotFound desc = failed to convert to cri containerd stats format: failed to decode container metrics for \"bb5ad9e5466f818f2a6e3b3d61e3841af1e65ea2a58abe9e0e68f26395d04acc\": failed to obtain cpu stats: failed to get usage nano cores, containerID: bb5ad9e5466f818f2a6e3b3d61e3841af1e65ea2a58abe9e0e68f26395d04acc: failed to get container ID: bb5ad9e5466f818f2a6e3b3d61e3841af1e65ea2a58abe9e0e68f26395d04acc: not found") has prevented the request from succeeding (get nodes bootstrap-e2e-minion-group-4fz9:10250)
      {
          ErrStatus: 
              code: 500
              details:
                causes:
                - message: 'Internal Error: failed to list pod stats: failed to list all container
                    stats: rpc error: code = NotFound desc = failed to convert to cri containerd
                    stats format: failed to decode container metrics for "bb5ad9e5466f818f2a6e3b3d61e3841af1e65ea2a58abe9e0e68f26395d04acc":
                    failed to obtain cpu stats: failed to get usage nano cores, containerID: bb5ad9e5466f818f2a6e3b3d61e3841af1e65ea2a58abe9e0e68f26395d04acc:
                    failed to get container ID: bb5ad9e5466f818f2a6e3b3d61e3841af1e65ea2a58abe9e0e68f26395d04acc:
                    not found'
                  reason: UnexpectedServerResponse
                kind: nodes
                name: bootstrap-e2e-minion-group-4fz9:10250
              message: 'an error on the server ("Internal Error: failed to list pod stats: failed
                to list all container stats: rpc error: code = NotFound desc = failed to convert
                to cri containerd stats format: failed to decode container metrics for \"bb5ad9e5466f818f2a6e3b3d61e3841af1e65ea2a58abe9e0e68f26395d04acc\":
                failed to obtain cpu stats: failed to get usage nano cores, containerID: bb5ad9e5466f818f2a6e3b3d61e3841af1e65ea2a58abe9e0e68f26395d04acc:
                failed to get container ID: bb5ad9e5466f818f2a6e3b3d61e3841af1e65ea2a58abe9e0e68f26395d04acc:
                not found") has prevented the request from succeeding (get nodes bootstrap-e2e-minion-group-4fz9:10250)'
              metadata: {}
              reason: InternalError
              status: Failure,
      }
  [FAILED] in [It] - test/e2e/node/node_problem_detector.go:379 @ 11/19/23 22:21:12.806

```
#### Recent failures:
[2023/11/20 18:55:47 ci-kubernetes-e2e-gci-gce-kube-dns](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-kube-dns/1726554925984387072)
[2023/11/20 18:41:47 ci-kubernetes-e2e-prow-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-prow-canary/1726551402437677056)
[2023/11/20 16:55:47 ci-kubernetes-e2e-gci-gce-proto](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-proto/1726524726387412992)
[2023/11/20 13:52:47 ci-kubernetes-e2e-gci-gce-network-proxy-grpc](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-grpc/1726478672820441088)
[2023/11/20 13:10:47 ci-kubernetes-e2e-gci-gce-ipvs](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1726468102910119936)

/kind flake
/sig node

This flake in the master blocking board recently:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1726360140367532032
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1725971072433524736

**Comment by pacoxu** [comment]
> "failed to list pod stats: failed to list all container stats: rpc error: code = Unavailable desc = error reading from server: EOF" request="/stats/summary"

I found some similar logs in https://github.com/kubernetes/kubernetes/issues/115192.

/cc @SergeyKanzhelev @harche 
for more attentions from sig-node, as this may be a case that the flaking indicts a bug of kubelet.

**Comment by pacoxu** [comment]
According to @Vyom-Yadav 's investigation, this issue is really old, this started flaking recently
https://storage.googleapis.com/k8s-triage/index.html?date=2023-10-30&test=NodeProblemDetector%20should%20run%20without%20error#1adbf9900df472bd8059

It started to flake from 10-24, on which day we bump the npd version in https://github.com/kubernetes/kubernetes/pull/121382.

I think we should revert it before we find the root cause.

**Comment by aojea** [comment]
> /area test

@SergeyKanzhelev this node problem detect need to be tagged so it is not picked by default, jobs that want to exercise these npd tests should be explicitily opt in for it

**Comment by aojea** [comment]
> It started to flake from 10-24, on which day we bump the npd version in #121382.

the problem here is that when is a daemonset, it accounts for scheduling and sometimes the instances are too small that the pods are not able to be scheduled and the e2e timesout 

https://github.com/kubernetes/test-infra/pull/31312
https://github.com/kubernetes/test-infra/pull/31315

NPD should not run by default, and the tests should be opt-in

**Comment by pacoxu** [comment]
https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.15 is released.

**Comment by pacoxu** [comment]
This will be fixed by https://github.com/kubernetes/kubernetes/pull/123114

**Comment by pacoxu** [comment]
This only flake in https://testgrid.k8s.io/sig-release-1.29-blocking#gce-cos-k8sbeta-default.

I need watch after we upgrade to v0.8.16.  https://github.com/kubernetes/kubernetes/pull/123114

**Comment by pacoxu** [comment]
Flake in https://testgrid.k8s.io/sig-release-1.29-blocking#gce-cos-k8sstable1-default but the CI is blocked by https://github.com/kubernetes/kubernetes/issues/124438.
