### ISSUE TITLE
CPU resourcequota doesn't recycle

### ISSUE THREAD

**Issue by seaurching** [kubernetes/kubernetes#122031]
### What happened?

I create an resourcequota on namespace with hard limit CPU 4000C and Memory 1.6Ti. But the Used CPU is 3997, the real usage is 134C .Why? 
![image](https://github.com/kubernetes/kubernetes/assets/7349963/ce876da5-dac9-410d-9d51-7503eec4f480)

### What did you expect to happen?

I expect the resource used of cpu is `kubectl top`'s value

### How can we reproduce it (as minimally and precisely as possible)?

Create an resourcequota, then create alot of pod to use the full resource.
Then recycle it. The used isn't currently value

### Kubernetes version

<details>

```console
root@tjv1~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
ksyun
</details>

### OS version

<details>

```console
[root@tjv1 ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@tjv1 ~]# uname -a
Linux tjv1 5.4.54-1.0.0.std7c.el7.2.x86_64 #1 SMP Mon Nov 16 10:02:20 CST 2020 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
v1.21 is no longer supported, can you test with the version that is still supported?
ref: https://kubernetes.io/releases/version-skew-policy/

/triage needs-information
