### ISSUE TITLE
Kubelet logs filling up with error: PodExistsInVolume failed to find expandable plugin

### ISSUE THREAD

**Issue by eroji** [kubernetes/kubernetes#122037]
### What happened?

Kubelet logs filling up with this error message
{"log":"I1125 01:34:33.264582   52079 actual_state_of_world.go:821] \"PodExistsInVolume failed to find expandable plugin\" volume=kubernetes.io/nfs/b53a3e3e-2b43-41e8-9386-ccad310db97d-namespace.volume volumeSpecName=\"namespace.volume\"\n","stream":"stderr","time":"2023-11-25T01:34:33.264805238Z"}

### What did you expect to happen?

For this error to stop

### How can we reproduce it (as minimally and precisely as possible)?

It's not clear to me what's causing this error to occur

### Kubernetes version

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.16", GitCommit:"51e33fadff13065ae5518db94e84598293965939", GitTreeState:"clean", BuildDate:"2023-07-19T12:19:24Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

Local Rancher deployment

### OS version

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Linux hostname.example.com 3.10.0-1160.102.1.el7.x86_64 #1 SMP Tue Oct 17 15:42:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:11:35 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:10:36 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by carlory** [comment]
The intree plugin nfs does not support volume expand. do you changes the pvc's requet storage in spec? If changed, you will see above error.

**Comment by carlory** [comment]
If you want to stop the error, you can simulate the controller behavior to update pvc status matched with its spec.
