### ISSUE TITLE
Using backpressure to determine rates limits vs. hard-coded values.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#12208]
Update and query semantics have far too many magic numbers which are fairly arbitrary.
e.g. rate limits such as qps and max-requests-inflight, as well as update intervals 

Ideally clients should be able to use back-pressure to determine their update rate within some bounds and back-off where necessary.

Use case in point, when we load balance API-servers we eliminate many of the performance bottlenecks and it clearly shows that the api-server, not etcd, is the gating component. 

cc @rrati @jayunit100 
cc @davidopp @wojtek-t @fgrzadkowski

**Comment by wojtek-t** [comment]
I agree it makes sense to do it for things like: rate-limits and max-requests-inflights.
However, update intervals is a different thing to me.

Anyway - I agree that such mechanism would be useful and we can decide it for which things we can use it later (there will be at least few of those).

**Comment by jayunit100** [comment]
Update on this.   We've noticed that the  `type Client struct {   *RESTClient }`, by definition has a RESTClient.  The RESTClient itself uses a `throttle`.   I'm digging into adding push metrics to the RESTClient metrics, so that *all* metrics can be gathered rather than just those from apiserver and controllermanager clients.

**Comment by timothysc** [comment]
I'd like to bring this up for 1.3 planning, once 1.2 is out. 

/cc @kubernetes/sig-scalability

**Comment by jayunit100** [comment]
We need to do #18892 to as well

**Comment by spiffxp** [comment]
Dupe of #14955 (or vice-versa)

**Comment by timothysc** [comment]
prior to back-offs I'm targeting http2 as it makes it easier given there is a single choke-point 

xref: #23709

**Comment by bgrant0607** [comment]
I'd like to see:

1. Differentiated treatment: prioritization, fairness, quota, QoS
   * Not all clients are equal. Some are critical system components. Even those components act on behalf of multiple users / service accounts / namespaces / workloads. A namespace with quota to run 1 pod shouldn't be able to get as much resources as one with quota to run 100k pods. And admins need to be able to access the API to mitigate problems.

2. More sophisticated automatic mitigations: flow control (pausing), load shedding (dropping), dynamic backoff (not just fixed limits)

**Comment by wojtek-t** [comment]
We are going to look into that with @lavalamp this quarter.

**Comment by liggitt** [comment]
moved to https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190228-priority-and-fairness.md#queuing / https://github.com/kubernetes/enhancements/issues/1040

/close
