### ISSUE TITLE
Failed to dial apiserver "10.96.0.1:443": dial tcp 10.96.0.1:443: i/o timeout When install kube-ovn-cni

### ISSUE THREAD

**Issue by WindHenry** [kubernetes/kubernetes#122007]
I have a cluster that contains 3 nodes (1 master, 2 workers). I want to install kube-ovn-cni into this cluster. 
Below is information of 3 nodes and pods in cluster
![image](https://github.com/kubernetes/kubernetes/assets/96536348/0e89c7cb-7e14-4c6f-a2f7-f31685b8e6bb)
![image](https://github.com/kubernetes/kubernetes/assets/96536348/9b2c103e-c67e-4f9d-ac0e-6f045bb85534)
You can see, kube-ovn-cni just has running status in Master node and crashed in 2 worker node. 
Below is infomation in kube-api-server pod 
![image](https://github.com/kubernetes/kubernetes/assets/96536348/00c3d5aa-f064-4dad-bdda-7fb50727d4df)
Kubernetes Service 
![image](https://github.com/kubernetes/kubernetes/assets/96536348/35e41f1c-705f-4e51-aa4b-5b734af8234d)
Describe of kube-ovn-cni pod
![image](https://github.com/kubernetes/kubernetes/assets/96536348/088a578e-c6ce-4682-8a4b-eccbba764e30)
And kube-ovn-cni.log in each nodes
![image](https://github.com/kubernetes/kubernetes/assets/96536348/d8faf8bf-fb94-4bc1-8667-a66f5814e985)
I want to ask whether the connection from a node to the kube-apiserver is related to CNI or not?

**Comment by neolit123** [comment]
> You can see, kube-ovn-cni just has running status in Master node and crashed in 2 worker node.

kube-ovn-cni is not part of the kubernetes project. better ask them for feedback first.

> I want to ask whether the connection from a node to the kube-apiserver is related to CNI or not?

please see
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
