### ISSUE TITLE
Higher CPU usage when pods are placed in a single namespace

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#122006]
### What happened?

When @afcollins was testing with [benchmarking](https://github.com/cloud-bulldozer/kube-burner/blob/master/cmd/kube-burner/ocp-config/node-density-heavy/node-density-heavy.yml) runs, it was observed that we if place the pods in a single namespace the reported CPU usage is much higher than if we just distribute those pods across multiple namespaces. 

e.g. When all 6006 pods are created in the same namespace, the kubepods.slice exceeds 12 cores.
However, when dividing the same 6006 pods across 4 namespaces (capping each namespace to 2000 pods), the node's CPU maxes out at 5 cores.

![image](https://github.com/kubernetes/kubernetes/assets/12152047/b4bffcb2-7ea5-4b89-bc20-30a66fe26dd3)

Corresponding prometheus query - `prom query:
sum by (id) (( rate(container_cpu_usage_seconds_total{ job=~".*", id =~"/system.slice|/system.slice/kubelet.service|/system.slice/ovs-vswitchd.service|/system.slice/crio.service|/system.slice/systemd-journald.service|/system.slice/ovsdb-server.service|/system.slice/systemd-udevd.service|/kubepods.slice"}[$interval])) * 100 * on (node) group_left kube_node_role{ role = "worker" } )
`

This becomes an issue on smaller cloud nodes with 8vCPU, where the excessive CPU use causes the nodes to thrash, skip metrics collection, and presents as a poorly-performing workload. Changing the config to break iterations into namespaces allows the workload to run on the smaller cloud nodes.

The goal here is to understand why the CPU usage compounds when pods are focused in a single namespace and if that points to any performance improvements we can make.

![image](https://github.com/kubernetes/kubernetes/assets/12152047/1856bfa0-8a5c-41c0-95ae-61e3e584f4ae)

Prometheus query - `sum( rate( (node_cpu_seconds_total{ mode != "idle" } * on (instance) group_left label_replace( kube_node_role{ role = "worker"} , "instance" , "$1" , "node" ,"(.*)") )[$interval:] ) ) by (instance) * 100
`

Memory, network, and memory demands on the node stay mostly constant. The only increase we see is CPU.

The observed higher CPU usage comes from the worker nodes, so none of the control plane components like API server, etcd are at play here. 

 

### What did you expect to happen?

CPU consumption should remain same whether we run the pods in single namespace or distribute them across multiple namespaces.

### How can we reproduce it (as minimally and precisely as possible)?

1. Get the kube-burner suite - https://github.com/cloud-bulldozer/kube-burner/tree/master
2. To run the pods in single namespace - `kube-burner ocp node-density-heavy --pods-per-node 150`
3. To run the pods in multiple namespaces - `kube-burner ocp node-density-heavy --pods-per-node 150 --iterations-per-namespace=10`

### Anything else we need to know?

Another run showed similar results, 

`kube-burner ocp node-density-heavy --pods-per-node 150` (single namespace)
vs.
`kube-burner ocp node-density-heavy --pods-per-node 150 --iterations-per-namespace=10` (multiple namespaces)

Results from 4 worker nodes. All CPU is coming from /kubepods.slice. (695 - 559 = 136 ) seconds less CPU  just by distributing into more namespaces -

Single namespace - 
`sum ( container_cpu_usage_seconds_total { id =~ "/system.slice|/system.slice/kubelet.service|/system.slice/ovs-vswitchd.service|/system.slice/crio.service|/kubepods.slice" } and on (node) kube_node_role{ role = "worker" } ) by ( id )`

```
/kubepods.slice: 36173 - 35478 = 695
/system.slice: 41456 - 41119 = 337
```

`sum ( node_cpu_seconds_total { } ) by ( mode )`
```
user: 265317 - 263848 = 1469
system: 66657 - 66229 = 428
irq: 25040 - 24951 = 89
softirq: 16627 - 16567 = 60
```
Multiple namespaces - 
`sum ( container_cpu_usage_seconds_total { id =~ "/system.slice|/system.slice/kubelet.service|/system.slice/ovs-vswitchd.service|/system.slice/crio.service|/kubepods.slice" } and on (node) kube_node_role{ role = "worker" } ) by ( id )`

```
/kubepods.slice: 37084 - 36525 = 559
/system.slice: 42439 - 42099 = 340
```

`sum ( node_cpu_seconds_total { } ) by ( mode )`
```
user: 269176 - 267809 = 1367
system: 67785 - 67360 = 425
irq: 25369 - 25277 = 92
softirq: 16848 - 16785 = 63
```

### Kubernetes version

master

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ndixita** [comment]
/triage accepted

/sig instrumentation 
Could you please help us understand the issue here while we triage node side of things? Can this just be an issue on how metrics are reported?

**Comment by dgrisonnet** [comment]
/cc @dashpole 
for instrumentation support

**Comment by dashpole** [comment]
> Could you please help us understand the issue here while we triage node side of things? Can this just be an issue on how metrics are reported?

This shouldn't be an issue with how the metrics are reported.  The metric in question is the CPU usage of the kubepods cgroup (kubepods.slice).  The cgroup's CPU usage is measured directly by cAdvisor, so there shouldn't be any aggregation issues.

It also seems incredibly unlikely to me that splitting into multiple namespaces would impact pod CPU usage at all.

@harche can you try and break down the kubepods cgroup usage into usage by individual pods?  Can you verify that there are the same number of total pods/containers reported via metrics?  If there are the same number, are there outliers in terms of CPU usage compared with other runs?

**Comment by pacoxu** [comment]
Is this related benchmark running script?  Can you briefly introduce about how it runs? Or how to reproduce it in a simple way?

**Comment by harche** [comment]
After looking deeper into the logs from the runs, it seems it more related to multus-cni than k8s. 

/close
