### ISSUE TITLE
When PreFilter's PreFilterResult filter out some Nodes, unschedulable plugin isn't registered for those plugins

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#122018]
### What happened?

from: https://github.com/kubernetes/kubernetes/issues/118369#issuecomment-1581610018

When PreFilter's PreFilterResult filters out some Nodes, unschedulable plugin isn't registered for those plugins. 

1. PreFilterA filters out all Nodes but NodeA via PreFilterResult.
2. FilterA filters out NodeA.
3. Currently, only FilterA is registered in unsched plugins.

In this case, some changes in the cluster may change the result from PreFilterA and may make this Pod schedulable. 

### What did you expect to happen?

1. PreFilterA filters out all Nodes but NodeA via PreFilterResult.
2. FilterA filters out NodeA.
3. PreFilterA and FilterA are registered in unsched plugins.

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Kubernetes version

master

### Cloud provider

<details>
n/a
</details>
 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by olderTaoist** [comment]
can let me try？

**Comment by sanposhiho** [comment]
Yes.

/unassign
/assign @olderTaoist

**Comment by sanposhiho** [comment]
/remove-lifecycle stale

on going: https://github.com/kubernetes/kubernetes/pull/122251

**Comment by alculquicondor** [comment]
@sanposhiho does this affect in-tree plugins?
