### ISSUE TITLE
Keeping important pods on same Node during high resource utilization on Node

### ISSUE THREAD

**Issue by ajayrudresh** [kubernetes/kubernetes#122055]
Hi There,

We have DB pod running in our K8s cluster. That DB pod was used by many application services. If CPU or Memory or Disk Utilization is high on the Node where DB pod is running, the DB and other Pods will get restarted and moved to another node. During this time, application services are getting impacted.

Is it possible to keep the Important Pod(i.e. DB-Pod) on the same node and release the other low-priority pods to another node in Kubernetes? If Yes, Kindly share the references for the same.

Thanks
Ajay

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
