### ISSUE TITLE
while creating kubernetes cluster over IPv6 using kubeam api-server is not coming up 

### ISSUE THREAD

**Issue by kishoremakkena** [kubernetes/kubernetes#122042]
### What happened?

api server is not able to connect to etcd over ipv6

root@i-00ca34d43fb89ec68:/home/ubuntu# nerdctl -n k8s.io logs 3ddf54bf4dd4
I1126 02:35:56.364282       1 options.go:220] external host was not specified, using 2600:1f14:3129:9701:700e:603e:c944:5228
I1126 02:35:56.365658       1 server.go:148] Version: v1.28.4
I1126 02:35:56.365691       1 server.go:150] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
W1126 02:35:56.894912       1 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:35:56.896601       1 logging.go:59] [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
I1126 02:35:56.896827       1 shared_informer.go:311] Waiting for caches to sync for node_authorizer
I1126 02:35:56.904274       1 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I1126 02:35:56.904303       1 plugins.go:161] Loaded 13 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurity,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,ClusterTrustBundleAttest,CertificateSubjectRestriction,ValidatingAdmissionPolicy,ValidatingAdmissionWebhook,ResourceQuota.
I1126 02:35:56.904607       1 instance.go:298] Using reconciler: lease
W1126 02:35:56.905755       1 logging.go:59] [core] [Channel #5 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:35:57.895639       1 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:35:57.897914       1 logging.go:59] [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:35:57.906486       1 logging.go:59] [core] [Channel #5 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:35:59.265847       1 logging.go:59] [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:35:59.352513       1 logging.go:59] [core] [Channel #5 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:35:59.585034       1 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:36:01.624501       1 logging.go:59] [core] [Channel #5 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:36:02.188257       1 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:36:02.294118       1 logging.go:59] [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:36:06.006179       1 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:36:06.206118       1 logging.go:59] [core] [Channel #5 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:36:06.211599       1 logging.go:59] [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:36:13.175524       1 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:36:13.524491       1 logging.go:59] [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
W1126 02:36:13.557968       1 logging.go:59] [core] [Channel #5 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:2379", ServerName: "::1", }. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused"
F1126 02:36:16.906342       1 instance.go:291] Error creating leases: error creating storage factory: context deadline exceeded

### What did you expect to happen?

It needs to connect to etcd over IPv6 and start running the container

### How can we reproduce it (as minimally and precisely as possible)?

I am able to reproduce it if required.

### Kubernetes version

Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

### Cloud provider

aws

### OS version

PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

containerd

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> I am able to reproduce it if required.

we have a variety of e2e tests where a full ipv6 setup works fine with kubeadm. try asking on the support channels for help.

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/sig cluster-lifecycle network
/triage support
/close
