### ISSUE TITLE
Enabling InPlacePodVerticalScaling feature gate causes restart of containers within the cluster

### ISSUE THREAD

**Issue by elias-dbx** [kubernetes/kubernetes#122028]
### What happened?

We recently enabled the InPlacePodVerticalScaling feature gate which caused the container spec of our containers to change which in turn triggered container restart logic on the kubelet. All the containers in our cluster we restarted at the same time.

### What did you expect to happen?

Containers shouldn't restart when the InPlacePodVerticalScaling feature gate is enabled

### How can we reproduce it (as minimally and precisely as possible)?

Enable InPlacePodVerticalScaling feature gate, observe k8s events for pods after restarting apiserver:
```
1h39m  Normal   Killing    Container XXX definition changed, will be restarted
```

### Anything else we need to know?

This issue is caused since enabling the feature gate causes the apiserver to update the container spec with a default policy here: https://github.com/kubernetes/kubernetes/blob/d61cbac69aae97db1839bd2e0e86d68f26b353a7/pkg/apis/core/v1/defaults.go#L181

That causes the logic here to restart the container since the container spec changed: https://github.com/kubernetes/kubernetes/blob/d61cbac69aae97db1839bd2e0e86d68f26b353a7/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L991

You can also easily verify that the container spec changed using kubectl:
```
# before apiserver restart with InPlacePodVerticalScaling feature gate 
$ kubectl get pod XXX -n NNN -o json | grep resize

# after apiserver restart with InPlacePodVerticalScaling feature gate 
$ kubectl get pod XXX -n NNN -o json | grep resize
                "resizePolicy": [
```

### Kubernetes version

<details>

```console
v1.27.5
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd version 1.7.9
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
This looks like a specific instance of https://github.com/kubernetes/kubernetes/issues/63814 and means the defaulting around this field is breaking 

the tests in https://github.com/kubernetes/kubernetes/pull/78914 should have caught and prevented this but they may not be exercising all feature gate states correctly

**Comment by HirazawaUi** [comment]
> but they may not be exercising all feature gate states correctly

During my testing I found that the `TestPodDefaults` had correctly exercised the enable state of the `InPlacePodVerticalScaling` feature gate. 

But when the pod.Spec.Containers.Resources.Requests field is not empty, it changes the default value of resizePolicy.
ref:  https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/pkg/apis/core/v1/defaults.go#L181-L195

So I think what we should really need to change is [HashContainerWithoutResources](https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/pkg/kubelet/container/helpers.go#L121-L135), so that the kubelet omits the ResizePolicy field when performing compute hash (same as omitting the Resources field).

Do you think this is the right thing to do?

**Comment by liggitt** [comment]
> So I think what we should really need to change is [HashContainerWithoutResources](https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/pkg/kubelet/container/helpers.go#L121-L135)

I'm open to improving kubelet code (https://github.com/kubernetes/kubernetes/issues/63814 suggests radically altering how the kubelet decides to restart by *only* considering fields it knows should trigger restarts), but a kubelet-only fix in 1.30+ won't unbreak older kubelets if the apiserver starts populating this field suddenly when the feature gate is turned on. kube-apiserver *cannot* populate default values inside container specs on upgrade or feature enable in ways supported skewed kubelets will interpret as requiring a container restart.

**Comment by HirazawaUi** [comment]
> then that's a bug we have to fix in the apiserver

I checked https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources and realized that we seem to be missing this scene.

And I looked at the code that sets the `ContainerResizePolicy` context, and if we want to fix this on apiserver, we can only set the `ContainerResizePolicy` to the default value on [creation](https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/pkg/api/pod/util.go#L554-L566), not nil.

This would allow clusters that don't have the `InPlacePodVerticalScaling` feature gate enabled to also see this field in the podSpec, can we accept this change?

@vinaykul Do you have some additional thoughts on it? (as the owenr of this feature)

**Comment by liggitt** [comment]
> And I looked at the code that sets the ContainerResizePolicy context, and if we want to fix this on apiserver, we can only set the ContainerResizePolicy to the default value on [creation](https://github.com/kubernetes/kubernetes/blob/55f2bc10435160619d1ece8de49a1c0f8fcdf276/pkg/api/pod/util.go#L554-L566), not nil.

On creation is definitely safer. It means the kubelet will have to handle that field being absent and understand what that should mean.

> This would allow clusters that don't have the InPlacePodVerticalScaling feature gate enabled to also see this field in the podSpec, can we accept this change?

No, the logic should only populate the field if the feature gate is enabled as well.

**Comment by HirazawaUi** [comment]
> No, the logic should only populate the field if the feature gate is enabled as well.

If we can't tolerate this noise (for clusters of unenabled InPlacePodVerticalScaling feature gates), then we may just have to make changes to it in the kubelet for now!

Until we make the changes to the kubelet as suggested in #63814 (I'd be happy to move this forward if I can)

Or do you have a better suggestion?

**Comment by liggitt** [comment]
> > No, the logic should only populate the field if the feature gate is enabled as well.
> 
> If we can't tolerate this noise (for clusters of unenabled InPlacePodVerticalScaling feature gates), then we may just have to make changes to it in the kubelet for now!

Why? We can populate the field conditionally in PrepareForCreate by checking if the feature gate is enabled.

**Comment by HirazawaUi** [comment]
> Why? We can populate the field conditionally in PrepareForCreate by checking if the feature gate is enabled.

This way we maybe can't seem to avoid creating a pod on an apiserver that have the `InPlacePodVerticalScaling` feature gate is disabled, and then enable the `InPlacePodVerticalScaling` feature gate on the apiserver later causes the pod to restart

`PrepareForCreate` will be called when a pod is created, and will have no effect on existing pods.

Please correct me if I'm wrong.

**Comment by liggitt** [comment]
I'm saying that modifying containers ResizePolicy in SetDefaults_Pod breaks existing kubelets (by instantly modifying and triggering container restarts for all existing pods when the feature gate is enabled) and we have either have to:
1. stop doing that and move the defaulting logic to happen *only* at pod create time and *only* when the feature gate is enabled
2. fix the kubelet issue with miscalculating whether containers should restart and block the feature graduation to beta until the fix reaches the oldest supported kubelets

**Comment by elias-dbx** [comment]
> stop doing that and move the defaulting logic to happen only at pod create time and only when the feature gate is enabled

that is the preferable solution in my opinion. fixing on the kubelet side basically means that this feature is unusable until all the kubelets can be upgraded, the fact that all containers in the cluster restart at the same time is a VERY large footgun. There should also probably be some warnings in the docs around this flag because restarting all containers in the cluster is probably something people should know about.

**Comment by HirazawaUi** [comment]
> * stop doing that and move the defaulting logic to happen _only_ at pod create time and _only_ when the feature gate is enabled
> * fix the kubelet issue with miscalculating whether containers should restart and block the feature graduation to beta until the fix reaches the oldest supported kubelets

I got it, thank you for your patient explanation.

**Comment by vinaykul** [comment]
Sorry for this bug. We made some late stage changes to defaulting logic and I missed this test case. I would take the ugliness of clusters with `InPlacePodVerticalScaling` disabled seeing the default resize policy over all containers restarting at once. If we fixed it in kubelet as well and backported the fix to 1.27x dot releases, we can mitigate the issue. Let me take a stab at a fix this weekend.

**Comment by liggitt** [comment]
> If we fixed it in kubelet as well and backported the fix to 1.27.x+ dot releases, we can mitigate the issue.

I'm -1 on changing kubelet container restart logic in backports for a new feature... that's a pretty fragile area of the kubelet, and I think the burden is on the new feature to not break older kubelets. We also cannot assume someone has all their kubelets on the latest patch releases of all supported skewed minor version kubelets before they upgrade the control plane to whatever version turns VPA on

**Comment by anirudhjayakumar** [comment]
Any update on this?

**Comment by HirazawaUi** [comment]
> Any update on this?

After the #122255 merger, we can solve this issue.

**Comment by anirudhjayakumar** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/122255 has been on hold for more than 2 months.
