### ISSUE TITLE
HA Cluster initialization issues

### ISSUE THREAD

**Issue by raphael10-collab** [kubernetes/kubernetes#122094]
### What happened?

During the initialization of the very first control-plane-nodes (3 control-plane-nodes + 3 worker-nodes) I'm getting these errors : 

    root@k8s-eu-1-control-plane-node-1:~# sudo kubeadm init --control-plane-endpoint k82-eu-1-load-balancer-dns-1:53 --upload-certs --v=8 --ignore-preflight-errors=Port-6443

    
    Unfortunately, an error has occurred:
	    timed out waiting for the condition
    
    This error is likely caused by:
	    - The kubelet is not running
	    - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
    
    If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	    - 'systemctl status kubelet'
	    - 'journalctl -xeu kubelet'
    
    Additionally, a control plane component may have crashed or exited when started by the container runtime.
    To troubleshoot, list all containers using your preferred container runtimes CLI.
    Here is one example how you may list all running Kubernetes containers by using crictl:
	    - 'crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
	    Once you have found the failing container, you can inspect its logs with:
	    - 'crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock logs CONTAINERID'

This is the complete output of the failed initialization :

https://drive.google.com/file/d/1iEnu34unu7xnsh556eTbY5EAJ-2zBrkr/view?usp=sharing

Output of `journalctl -xeu kubelet` : https://drive.google.com/file/d/1d_Z6ic2xjyXu1QIpdba655yS4bvcfhkl/view?usp=drive_link 

    root@k8s-eu-1-control-plane-node-1:~# crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock ps -a | grep kube | grep -v pause
    579c2b9e5d17a       7fe0e6f37db33       41 seconds ago      Exited              kube-apiserver            50                  7d52f351045d2       kube-apiserver-k8s-eu-1-control-plane-node-1
    9db9a2fe179e3       e3db313c6dbc0       16 minutes ago      Running             kube-scheduler            25                  d55a5e9d9be56       kube-scheduler-k8s-eu-1-control-plane-node-1
    d3887c919854f       d058aa5ab969c       16 minutes ago      Running             kube-controller-manager   18                  e61c1eb6a8700       kube-controller-manager-k8s-eu-1-control-plane-node-1
    root@k8s-eu-1-control-plane-node-1:~# 
    root@k8s-eu-1-control-plane-node-1:~# crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock logs 579c2b9e5d17a
    I1128 16:58:28.080267       1 options.go:220] external host was not specified, using 38.242.249.60
    I1128 16:58:28.081342       1 server.go:148] Version: v1.28.4
    I1128 16:58:28.081365       1 server.go:150] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
    E1128 16:58:28.081652       1 run.go:74] "command failed" err="failed to create listener: failed to listen on 0.0.0.0:6443: listen tcp 0.0.0.0:6443: bind: address already in use"

    root@k8s-eu-1-control-plane-node-1:~# ps xa | grep 6443
      33348 pts/0    R+     0:00 grep --color=auto 6443

If I do `kubeadm init --pod-network-cidr=192.168.0.0/16` the initialization process goes fine

### What did you expect to happen?

Initialization process OK

### How can we reproduce it (as minimally and precisely as possible)?

Based on what is described here: https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#keepalived-configuration

I defined:

 `/etc/haproxy/haproxy.cfg` : 
    
    # https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#haproxy-configuration
    
    # /etc/haproxy/haproxy.cfg
    #---------------------------------------------------------------------
    # Global settings
    #---------------------------------------------------------------------
    global
        log /dev/log local0
        log /dev/log local1 notice
        daemon
    
    #---------------------------------------------------------------------
    # common defaults that all the 'listen' and 'backend' sections will
    # use if not designated in their block
    #---------------------------------------------------------------------
    defaults
        mode                    http
        log                     global
        option                  httplog
        option                  dontlognull
        option http-server-close
        option forwardfor       except 127.0.0.0/8
        option                  redispatch
        retries                 1
        timeout http-request    10s
        timeout queue           20s
        timeout connect         5s
        timeout client          20s
        timeout server          20s
        timeout http-keep-alive 10s
        timeout check           10s
    
    #---------------------------------------------------------------------
    # apiserver frontend which proxys to the control plane nodes
    #---------------------------------------------------------------------
    frontend apiserver
        bind *:6445
        mode tcp
        option tcplog
        default_backend apiserverbackend
    
    #---------------------------------------------------------------------
    # round robin balancing for apiserver
    #---------------------------------------------------------------------
    # https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#bootstrap-the-cluster
    
    backend apiserverbackend
        #option httpchk GET /healthz
        option httpchk GET /livez
        http-check expect status 200
        mode tcp
        option ssl-hello-chk
        balance     roundrobin
            server k82-eu-1-load-balancer-dns-1 ppp.pp.ppp.pp:53
            server k82-eu-1-load-balancer-dns-2 yyy.yy.yyy.yy:53

`/etc/keepalived/keepalived.conf` : 

    # https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#keepalived-configuration
    # https://www.server-world.info/en/note?os=Ubuntu_22.04&p=keepalived&f=1
    
    ! /etc/keepalived/keepalived.conf
    ! Configuration File for keepalived
    global_defs {
        router_id LVS_DEVEL
        enable_script_security
    }
    vrrp_script check_apiserver {
      script "/etc/keepalived/check_apiserver.sh"
      interval 3
      weight -2
      fall 10
      rise 2
    }
    
    vrrp_instance VI_1 {
        state MASTER
        interface eth0
        virtual_router_id 51
        priority 101
        authentication {
            auth_type PASS
            auth_pass 42
        }
        virtual_ipaddress {
            10.0.0.30
        }
        track_script {
            check_apiserver
        }
    }

`/etc/keepalived/check_apiserver.sh` : 

    # https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#keepalived-configuration
    # https://www.server-world.info/en/note?os=Ubuntu_22.04&p=keepalived&f=1
    
    #!/bin/sh
    
    errorExit() {
        echo "*** $*" 1>&2
        exit 1
    }
    
    APISERVER_DEST_PORT=6445
    APISERVER_VIP=10.0.0.30
    
    curl --silent --max-time 2 --insecure https://localhost:${APISERVER_DEST_PORT}/ -o /dev/null || errorExit "Error GET https://localhost:${APISERVER_DEST_PORT}/"
    if ip addr | grep -q ${APISERVER_VIP}; then
        curl --silent --max-time 2 --insecure https://${APISERVER_VIP}:${APISERVER_DEST_PORT}/ -o /dev/null || errorExit "Error GET https://${APISERVER_VIP}:${APISERVER_DEST_PORT}/"
    fi

`/etc/kubernetes/manifests/haproxy.yaml` : 

    # https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#option-2-run-the-services-as-static-pods
    
    apiVersion: v1
    kind: Pod
    metadata:
      name: haproxy
      namespace: kube-system
    spec:
      containers:
      - image: haproxy:2.1.4
        name: haproxy
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: localhost
            path: /healthz
            port: 6445
            scheme: HTTPS
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: haproxyconf
          readOnly: true
      hostNetwork: true
      volumes:
      - hostPath:
          path: /etc/haproxy/haproxy.cfg
          type: FileOrCreate
        name: haproxyconf
    status: {}

`/etc/kubernetes/manifests/keepalived.yaml` : 

    # https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#option-2-run-the-services-as-static-pods
    
    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      name: keepalived
      namespace: kube-system
    spec:
      containers:
      - image: osixia/keepalived:2.0.17
        name: keepalived
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_BROADCAST
            - NET_RAW
        volumeMounts:
        - mountPath: /usr/local/etc/keepalived/keepalived.conf
          name: config
        - mountPath: /etc/keepalived/check_apiserver.sh
          name: check
      hostNetwork: true
      volumes:
      - hostPath:
          path: /etc/keepalived/keepalived.conf
        name: config
      - hostPath:
          path: /etc/keepalived/check_apiserver.sh
        name: check
    status: {}

### Kubernetes version

    root@k8s-eu-1-control-plane-node-1:~# kubectl version
    Client Version: v1.28.2
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    The connection to the server localhost:8080 was refused - did you specify the right host or port?

### Cloud provider

Contabo

### OS version

    root@k8s-eu-1-control-plane-node-1:~# cat /etc/os-release
    PRETTY_NAME="Ubuntu 22.04.3 LTS"
    NAME="Ubuntu"
    VERSION_ID="22.04"
    VERSION="22.04.3 LTS (Jammy Jellyfish)"
    VERSION_CODENAME=jammy
    ID=ubuntu
    ID_LIKE=debian
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    UBUNTU_CODENAME=jammy
    root@k8s-eu-1-control-plane-node-1:~# 
    root@k8s-eu-1-control-plane-node-1:~# 
    root@k8s-eu-1-control-plane-node-1:~# uname -a
    Linux k8s-eu-1-control-plane-node-1 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Install tools

I followed these indications: https://www.linuxtechi.com/install-kubernetes-on-ubuntu-22-04/

### Container runtime (CRI) and version (if applicable)

    root@k8s-eu-1-control-plane-node-1:~# sudo systemctl status containerd
    ● containerd.service - containerd container runtime
         Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
         Active: active (running) since Tue 2023-11-28 19:04:50 CET; 1min 49s ago
           Docs: https://containerd.io
       Main PID: 2936 (containerd)
          Tasks: 15
         Memory: 17.4M
            CPU: 430ms
         CGroup: /system.slice/containerd.service
                 └─2936 /usr/bin/containerd
    
    Nov 28 19:04:50 k8s-eu-1-control-plane-node-1 containerd[2936]: time="2023-11-28T19:04:50.215299387+01:00" level=info msg="Start subscribing containerd event"
    Nov 28 19:04:50 k8s-eu-1-control-plane-node-1 containerd[2936]: time="2023-11-28T19:04:50.215405211+01:00" level=info msg="Start recovering state"
    Nov 28 19:04:50 k8s-eu-1-control-plane-node-1 containerd[2936]: time="2023-11-28T19:04:50.215555105+01:00" level=info msg=serving... address=/run/containerd/containerd.sock.ttrpc
    Nov 28 19:04:50 k8s-eu-1-control-plane-node-1 containerd[2936]: time="2023-11-28T19:04:50.215604457+01:00" level=info msg=serving... address=/run/containerd/containerd.sock
    Nov 28 19:04:50 k8s-eu-1-control-plane-node-1 containerd[2936]: time="2023-11-28T19:04:50.260351587+01:00" level=info msg="Start event monitor"
    Nov 28 19:04:50 k8s-eu-1-control-plane-node-1 containerd[2936]: time="2023-11-28T19:04:50.260440830+01:00" level=info msg="Start snapshots syncer"
    Nov 28 19:04:50 k8s-eu-1-control-plane-node-1 containerd[2936]: time="2023-11-28T19:04:50.260471551+01:00" level=info msg="Start cni network conf syncer for default"
    Nov 28 19:04:50 k8s-eu-1-control-plane-node-1 containerd[2936]: time="2023-11-28T19:04:50.260487122+01:00" level=info msg="Start streaming server"
    Nov 28 19:04:50 k8s-eu-1-control-plane-node-1 containerd[2936]: time="2023-11-28T19:04:50.260597685+01:00" level=info msg="containerd successfully booted in 0.076156s"
    Nov 28 19:04:50 k8s-eu-1-control-plane-node-1 systemd[1]: Started containerd container runtime.
    root@k8s-eu-1-control-plane-node-1:~# 
    root@k8s-eu-1-control-plane-node-1:~# sudo systemctl status docker
    ● docker.service - Docker Application Container Engine
         Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
         Active: active (running) since Tue 2023-11-28 19:05:43 CET; 1min 6s ago
    TriggeredBy: ● docker.socket
           Docs: https://docs.docker.com
       Main PID: 3179 (dockerd)
          Tasks: 16
         Memory: 25.4M
            CPU: 300ms
         CGroup: /system.slice/docker.service
                 └─3179 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
    
    Nov 28 19:05:42 k8s-eu-1-control-plane-node-1 dockerd[3179]: time="2023-11-28T19:05:42.765125882+01:00" level=info msg="Starting up"
    Nov 28 19:05:42 k8s-eu-1-control-plane-node-1 dockerd[3179]: time="2023-11-28T19:05:42.766274889+01:00" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
    Nov 28 19:05:42 k8s-eu-1-control-plane-node-1 dockerd[3179]: time="2023-11-28T19:05:42.777199153+01:00" level=info msg="[graphdriver] trying configured driver: overlay2"
    Nov 28 19:05:42 k8s-eu-1-control-plane-node-1 dockerd[3179]: time="2023-11-28T19:05:42.811255077+01:00" level=info msg="Loading containers: start."
    Nov 28 19:05:43 k8s-eu-1-control-plane-node-1 dockerd[3179]: time="2023-11-28T19:05:43.185761603+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
    Nov 28 19:05:43 k8s-eu-1-control-plane-node-1 dockerd[3179]: time="2023-11-28T19:05:43.267872886+01:00" level=info msg="Loading containers: done."
    Nov 28 19:05:43 k8s-eu-1-control-plane-node-1 dockerd[3179]: time="2023-11-28T19:05:43.278584874+01:00" level=info msg="Docker daemon" commit=311b9ff graphdriver=overlay2 version=24.0.7
    Nov 28 19:05:43 k8s-eu-1-control-plane-node-1 dockerd[3179]: time="2023-11-28T19:05:43.278667556+01:00" level=info msg="Daemon has completed initialization"
    Nov 28 19:05:43 k8s-eu-1-control-plane-node-1 dockerd[3179]: time="2023-11-28T19:05:43.308728512+01:00" level=info msg="API listen on /run/docker.sock"
    Nov 28 19:05:43 k8s-eu-1-control-plane-node-1 systemd[1]: Started Docker Application Container Engine.

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
@raphael10-collab as i mentioned on slack try discuss.k8s.io or other forums.
github is not the right place to ask, as per our rules:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
