### ISSUE TITLE
How to build kubernetes base controller which will support different env's

### ISSUE THREAD

**Issue by obul465** [kubernetes/kubernetes#122054]
### What would you like to be added?

we would like to build one base k8s controller on top of it needs to pass different configuration values based on env specific so that we will have single image and we will avoid the maintenance work of different env's 

### Why is this needed?

we have requirement of building k8s controller with help of kube builder but not able to build different api version under one kind so building different controller with different api version(dev,int,qa,stage)

**Comment by neolit123** [comment]
by base controller, perhaps you mean the kube-controller manager.
kube builder is not used for building any of the core k8s components.

to understand how to build new contollers you can ask the kube builder maintainers.

for general help questions please use the community channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
