### ISSUE TITLE
--oidc-ca-file Updating the contents doesn't take effect properly, only a new file name seems to work.

### ISSUE THREAD

**Issue by mikementzmaersk** [kubernetes/kubernetes#122091]
### What happened?

Added a CA to the file referenced by --oidc-ca-file=custom-cas.pem
This didn't take effect, so restarted kube-api-server pod
Still the new CA was not taking effect with x509 unknown certificate authority warnings in the apiserver logs..

Confused (and after much CA validations), we copied the custom-cas.pem file as custom-cas.pem2 and updated the kube-apiserver static manifest - this worked.!

### What did you expect to happen?

We expected that simply altering the content of the already referenced oidc ca file would work, or at least, would work after a apiserver pod restart at worse...

Certainly we weren't expecting that the only way to get the new CA to work was to create a whole new file..

### How can we reproduce it (as minimally and precisely as possible)?

use a custom oidc ca file with a bad certificate so you get the usual x509 errors when trying to validate oidc ca
correct the oidc ca file

keep getting the errors
restart apiserver pod

keep getting the errors
rename the custom oidc ca file
reference the new filename in static manifest

x509 errors gone

### Kubernetes version

1.25.11

### Cloud provider

Bare Metal

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> We expected that simply altering the content of the already referenced oidc ca file would work, or at least, would work after a apiserver pod restart at worse...

there was an issue somewhere to dynamically reload cert files on change.

/sig auth
/feature

**Comment by liggitt** [comment]
Restarting the server process would certainly reread the content, are you sure you modified the file the server was reading?

**Comment by mikementzmaersk** [comment]
Yes - we're sure.  Did some more testing and some interesting observations.  

In one test, we didn't update the name of the oidc-ca-file and just loaded the apiserver static manifest in vi and saved it again with no content changes. In this case, kubelet reloaded apiserver and it picked up the new CA. 

This got us wondering whether restarting apiserver via kubectl vs kubelet noticing a difference is what is at play here - something around the mirror pod and actual container engine. 

We will do a test tomorrow where we add the new CA and restart from container engine not kubectl to make sure.

**Comment by aramase** [comment]
> We will do a test tomorrow where we add the new CA and restart from container engine not kubectl to make sure.

@mikementzmaersk Did you get a chance to test it?

**Comment by ibihim** [comment]
Hey,

reviewed during sig-auth triage meeting:

there was no response for over a month on it, we assume that the issue has gone. If not, feel free to reopen the issue.

/close
