### ISSUE TITLE
How to customize scheduling strategies for k8s

### ISSUE THREAD

**Issue by smallemployees** [kubernetes/kubernetes#122165]
### What happened?

How to customize scheduling strategies for k8s

### What did you expect to happen?

How to achieve the connection between our scheduling department and some of our own conditions

### How can we reproduce it (as minimally and precisely as possible)?

How to achieve the connection between our scheduling department and some of our own conditions

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.23
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
How to achieve the connection between our scheduling department and some of our own conditions
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
If you have a feature suggestion for the docs &ndash; **not** a request for advice, but an explanation of some way the docs could be better &ndash; then you can make that @smallemployees.

https://github.com/kubernetes/website/issues/new/choose

**Comment by kerthcet** [comment]
> for reference please see [Scheduler Configuration](https://kubernetes.io/docs/reference/scheduling/config/)

Yes, we have the scheduling configuration for default-scheduler, or if you want to use a second scheduler, see https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/.

/close 

Feel free to reopen if you have a special reason or issue. Thanks a lot.
