### ISSUE TITLE
New feature to allocate specific devices using DRA - usecase and design proposal

### ISSUE THREAD

**Issue by tmishina** [kubernetes/kubernetes#122198]
### What would you like to be added?

Feature to allocate a specific device to a Pod using webhook to generate appropriate DRA resources from user's intention in Pod manifest.

![design drawio](https://github.com/kubernetes/kubernetes/assets/7124738/9b3ece40-7424-4335-b25a-33c50ec9d708)

- Steps
  1. User appends node name and device ID (PCI address) to `.metadata.annotation` to Pod manifest
  2. Webhook converts the designation in `.metadata.annotation` into a set of resource claim and resource claim template
  3. DRA resource controller schedules the Pod to the designated node
  4. DRA driver allocates the designated device to the container(s) of the Pod

### Why is this needed?

Allocating a specific device to a Pod is meaningful in the following usecases.

1. **Efficient device allocation:** allocate an AI device which is located near a NIC on a PCI-Express bus to accelerate RDMA (e.g., `AI Device 2` is better for apps running both on `Node1` and `Node 2` in the picture below) - this can also be used by some automated tool to schedule Pods to the best location with certain cards w.r.t. co-working Pods
2. **Debugging:** allocate an unhealthy AI device to a debug-purpose Pod

![device-location drawio](https://github.com/kubernetes/kubernetes/assets/7124738/afe55114-e36d-458b-9b2b-c6c9ca82b515)

In the current Kubernetes architecture, several challenges exist for the usecases.

1. With classic device plugin, no parameters like device ID can be specified in Pod manifest
2. With DRA, parameters can be defined in device class parameters and claim parameters, and therefore we need some additional mechanism if user wants to specify per-Pod parameters

**Comment by pohly** [comment]
I think this is similar to the use cases for which @klueska extended the `AllocationResult`: what is needed is a DRA driver controller which understand both "AI Device" and "NIC Device" and can choose instances that are close together, then let the kubelet DRA plugin of each handle the setup on the node.

Or are you suggesting that the user should provide additional information to pre-select hardware? What would an API for that look like? Hardware would have to have user-visible IDs. A DRA driver can support this in their custom CRD (publish IDs) and and in their custom parameters (select by ID). But then there's no real scheduling because the user has to choose upfront where to run the pod.

**Comment by klueska** [comment]
As Patrick mentioned, the alignment use-case is covered by using a custom controller that knows how to do the desired alignment.

Please see the following:
* Video: https://www.youtube.com/watch?v=_fi9asserLE&t=1629
* Slides (84): https://docs.google.com/presentation/d/1NiGmZPLGgpCey80Yy6jwpbp0C9QVXMQw/edit#slide=id.g22c7a4ceec3_2_1340

Picking a specific device can be accomplished using the existing DRA driver for GPUs (with a small addition). We already support selecting by UUID or Index, we would just need to add PCIeBusID in here:
* https://github.com/NVIDIA/k8s-dra-driver/blob/main/api/nvidia.com/resource/gpu/v1alpha1/gpuselector.go#L63

**Comment by tmishina** [comment]
@neolit123 sorry for bothering. I know the KEP process, but I'd like to start a discussion in SIG with a short document, and I had thought that creating a document as an issue in this repo might be convenience for the SIG members. I'd appreciate it if there is better way/location to store and share a proposal document for SIG-level discussion. Thank you so much.
> @tmishina note, k8s has a KEP process for proposals: https://github.com/kubernetes/enhancements/blob/master/keps/README.md
> 
> /sig node

**Comment by pohly** [comment]
> Could you give your thoughts about weather this kind of automation (the webhook described in the third bullet above) can be a part of DRA architecture itself?

My gut reaction is that this is a custom extension built on top of DRA and certain DRA drivers, i.e. not part of the core DRA architecture. If it needs to be part of the core DRA, then a good explanation of why can't or shouldn't be done as such an extension would be needed.

**Comment by tmishina** [comment]
@pohly Thank you so much, I got it. I will implement the proposed features as a custom DRA controller + driver.
