### ISSUE TITLE
Move kubernetes to github.com/kubernetes/kubernetes

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#12211]
We need to transfer the kubernetes repo out of the GoogleCloudPlatform org to its own org in order to facilitate managing project teams, additional repos, etc.

Filing an issue to sort through what needs to be done.

- [x] Try moving a smaller project first, like Heapster or cAdvisor?
- [x] Change all imports to vanity domain/path to abstract away from specific github location
- [x] Update redirects that target github
- [x] Reconfigure automated testing: Travis, Shippable, Jenkins e2e, ...
- [x] Figure out what to do with the CLA bot

Add more items to this list.

cc @thockin @ixdy @zmerlynn @brendandburns @smarterclayton @vishh @vmarmol

**Comment by smarterclayton** [comment]
@ncdc

On Tue, Aug 4, 2015 at 1:37 PM, Brian Grant <notifications@github.com>
wrote:

> We need to transfer the kubernetes repo out of the GoogleCloudPlatform org
> to its own org in order to facilitate managing project teams, additional
> repos, etc.
>
> Filing an issue to sort through what needs to be done.
>
> [ ] Try moving a smaller project first, like Heapster or cAdvisor?
> [ ] Change all imports to vanity domain/path to abstract away from
> specific github location
> [ ] Update redirects that target github
> [ ] Reconfigure automated testing: Travis, Shippable, Jenkins e2e, ...
> [ ] Figure out what to do with the CLA bot
>
> Add more items to this list.
>
> cc @thockin <https://github.com/thockin> @ixdy <https://github.com/ixdy>
> @zmerlynn <https://github.com/zmerlynn> @brendandburns
> <https://github.com/brendandburns> @smarterclayton
> <https://github.com/smarterclayton> @vishh <https://github.com/vishh>
> @vmarmol <https://github.com/vmarmol>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/12211>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by pmorie** [comment]
> Change all imports to vanity domain/path to abstract away from specific github location

![](http://acme.com/licensemaker/licenses/license_20150804114735_11194.jpg)

**Comment by smarterclayton** [comment]
Is the vanity path worth it?  Will it make any of our tooling harder?

**Comment by mikedanese** [comment]
Vanity path can also useful for seeing godoc at specific versions/branches with godoc.org.

**Comment by bgrant0607** [comment]
We at least need to change all the imports to the new path. @thockin is investigating the vanity path.

**Comment by bgrant0607** [comment]
I think this is done.
