### ISSUE TITLE
Pod Cleanup Can Sometimes Delete Content from Persistnet Volumes

### ISSUE THREAD

**Issue by swagiaal** [kubernetes/kubernetes#12210]
While trying to reproduce #11231 I ran into a similar issue where content from the mounted volume was getting deleted. It turns out that the rapid creation/deletion of the pod exposes a race condition when results in the volume content getting deleted here https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1315

To fix this we should of course fix the race condition but I also thing it is worthwhile creating a special Remove/RemoveAll which checks to see if the file is under a mount point and/or check for a special lock file which protects content form kube cleanup and prints a warning to the logs. The reason is that while the bug rare and easy to fix the loss of user data is a high cost.

**Comment by yujuhong** [comment]
I have a PR which prevents the pod directory from being deleted if there is still running container in the pod: #10651. Maybe it'd help in this situation as well.

**Comment by saad-ali** [comment]
@swagiaal Did #13293 end up fixing this?

**Comment by swagiaal** [comment]
@saad-ali looks like it. I have not been able to reproduce it.
