### ISSUE TITLE
Ports with duplicate names should not be allowed to exist in the pod.

### ISSUE THREAD

**Issue by yanfeng1992** [kubernetes/kubernetes#122150]
### What happened?

The same port name exists in the pod, but it is not allowed in the document.

https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#ports

![image](https://github.com/kubernetes/kubernetes/assets/89568107/a12f4f70-ff90-4960-a5b7-2f8d64ae7ffb)

![image](https://github.com/kubernetes/kubernetes/assets/89568107/15576707-f22d-4dfe-bc96-1ca50f6d7d8b)

### What did you expect to happen?

Each named port in a pod must have a unique name.

### How can we reproduce it (as minimally and precisely as possible)?

I think it can't be repaired and there will be problems with upgrading.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

v1.25.8

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
I can reproduce this issue in the latest version.

If a pod has multiple containers with the same port name, the pod will be allowed to be created, we should reject this behavior during the validation.

/sig apps

**Comment by yanfeng1992** [comment]
In addition to changing the API and website documentation, can we add a warning if there are duplicate named ports in a pod?

@liggitt @HirazawaUi

**Comment by SergeyKanzhelev** [comment]
/remove-sig node

since it is handled by sig apps

**Comment by aojea** [comment]
@HirazawaUi it seems we are waiting for the author to finish https://github.com/kubernetes/kubernetes/pull/122170 , should this be taken by other person?

**Comment by HirazawaUi** [comment]
If @yanfeng1992 is no longer active, I'll move forward to complete it. Let's wait a few more days.

**Comment by thockin** [comment]
Recap:
- duplicate port names within a single container are NOT allowed
- duplicate port names within a pod but in different containers IS allowed, without any warning, but should not be
- duplicate port names within a pod but in containers and initContainers IS allowed, without any warning, but should not be

https://github.com/kubernetes/kubernetes/pull/122170 adds warnings for both cases.
