### ISSUE TITLE
loki helm upgrade failed from helm version 2.11.1 to 3.3.3 on eks 1.24 version

### ISSUE THREAD

**Issue by pvilasra** [kubernetes/kubernetes#122110]
### What happened?

Hi Team I will be updating eks version 1.25 for that need to upgrade loki helm chart as pod security policy is getting depricated. but getting me below error. We have ovverrided some of the values.yaml configuration as well

Error: execution error at (loki/templates/validate.yaml:2:4): Top level 'config' is not allowed. Most common configuration sections are exposed under the loki section. If you need to override the whole config, provide the configuration as a string that can contain template expressions under loki.config. Alternatively, you can provide the configuration as an external secret.
│
│ with module.service.helm_release.loki,
│ on ........\modules\loki\helm.tf line 1, in resource "helm_release" "loki":
│ 1: resource "helm_release" "loki" {

### What did you expect to happen?

I want to upgrade the loki helm chart as pod security policy is getting depricated on EKS version 1.25

### How can we reproduce it (as minimally and precisely as possible)?

installed loki helm chart on EKS version 1.24 currently 

### Anything else we need to know?

overridedn yaml files: loki_config.yaml

config:
auth_enabled: false
ingester:
chunk_idle_period: 3m
chunk_block_size: 262144
chunk_retain_period: 1m
max_transfer_retries: 0
lifecycler:
ring:
kvstore:
store: inmemory
replication_factor: 1
limits_config:
enforce_metric_name: false
reject_old_samples: true
reject_old_samples_max_age: 168h
schema_config:
configs:
- from: 2020-10-24
store: boltdb-shipper
object_store: aws
schema: v11
index:
prefix: loki_index_
period: 24h
server:
http_listen_port: 3100
grpc_server_max_recv_msg_size: 8388608
grpc_server_max_send_msg_size: 8388608
storage_config:
aws:
s3: s3://${aws_region}
bucketnames: ${aws_s3_bucket}
boltdb_shipper:
active_index_directory: /data/loki/boltdb-shipper-active
shared_store: aws
cache_location: /data/loki/boltdb-shipper-cache
chunk_store_config:
max_look_back_period: 4320h
table_manager:
retention_deletes_enabled: true
retention_period: 4320h
compactor:
working_directory: /data/loki/boltdb-shipper-compactor
shared_store: aws
ruler:
storage:
type: local
local:
directory: /rules
rule_path: /tmp/scratch
alertmanager_url: ${alertmanager_url}
ring:
kvstore:
store: inmemory
enable_api: true

loki.yaml

nodeSelector:
node-role: ${node_selector}

podLabels:
service: loki
deployment: ${deployment}
environment: ${environment}

priorityClassName: "system-cluster-critical"

replicas: 1

resources:
limits:
cpu: ${loki_resources.limits.cpu}
memory: ${loki_resources.limits.memory}
requests:
cpu: ${loki_resources.requests.cpu}
memory: ${loki_resources.requests.memory}

serviceAccount:
create: true
annotations:
"eks.amazonaws.com/role-arn": "${sa_role_arn}"

rbac.pspEnabled: false

serviceMonitor:
enabled: true
interval: "30s"
additionalLabels:
release: monitoring
service: loki
environment: ${environment}
deployment: ${deployment}

extraArgs:
log.level: debug
readinessProbe:
initialDelaySeconds: 60

livenessProbe:
initialDelaySeconds: 60

### Kubernetes version

[cloudshell-user@ip-10-6-65-93 ~]$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-8ccc7ba", GitCommit:"892db4a4e439987d7addade5f9595cadfa06db2e", GitTreeState:"clean", BuildDate:"2023-08-15T16:06:56Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.17-eks-4f4795d", GitCommit:"af19e454a15b5eb16d9f29d4d2361b3050ac78a6", GitTreeState:"clean", BuildDate:"2023-10-20T23:22:36Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

Bottlerocker OS
</details>

### Install tools

<details>
loki , alertmanager, promtail
</details>

### Container runtime (CRI) and version (if applicable)

<details>
NA
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
available
</details>

**Comment by troy0820** [comment]
This seems to be a similar issue https://github.com/grafana/helm-charts/issues/2040

**Comment by neolit123** [comment]
> /kind support
> 
> This doesn't seem like a Kubernetes issue

indeed. also please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
