### ISSUE TITLE
Add container_network_tcp/udp metrics from CRI

### ISSUE THREAD

**Issue by vsxen** [kubernetes/kubernetes#122179]
### What would you like to be added?

I would like to request a new feature for Kubernetes regarding container-level TCP/UDP monitoring within the Container Runtime Interface (CRI). Similar to the functionality provided by cAdvisor.

### Why is this needed?

container_network_advance_tcp_stats_total | Gauge | advanced tcp connections statistic for container |   | advtcp
-- | -- | -- | -- | --
container_network_tcp6_usage_total | Gauge | tcp6 connection usage statistic for container |   | tcp |  
container_network_tcp_usage_total | Gauge | tcp connection usage statistic for container |   | tcp
container_network_udp6_usage_total | Gauge | udp6 connection usage statistic for container |   | udp |  
container_network_udp_usage_total | Gauge | udp connection usage statistic for container |   | udp
container_network_udp6_usage_total | Gauge | udp6 connection usage statistic for container |   | udp |  
container_network_udp_usage_total | Gauge | udp connection usage statistic for container |   | udp

https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md

https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2371-cri-pod-container-stats/README.md

/sig node

**Comment by saschagrunert** [comment]
Hey @vsxen, thank you for the request. I think this would fit better in the [actual KEP for discussion](https://github.com/kubernetes/enhancements/issues/2371) rather than the k/k repository. 

cc @sohankunkerkar @haircommander

**Comment by haircommander** [comment]
yeah we can extend the desired metrics in the KEP, though note: currently this is up to the CRI implementation to support so you may have to contact your favorite CRI impl to get support
