### ISSUE TITLE
Upgrade NodeProblemDetector to v0.8.14+

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#122118]
During bumping NPD version, we met problems below

- After upgrading NPD to v0.8.13, we find a NPD flake in https://github.com/kubernetes/kubernetes/issues/121973.
- The NPD v0.8.14 image seems bad, the arm64 version has an x86_64 node-problem-detector binary and its failing all arm64 tests. https://storage.googleapis.com/k8s-triage/index.html?sig=node&job=ec2&xjob=windows#9f7f7053b14ff9d31a67 (https://github.com/kubernetes/kubernetes/pull/120441)

/sig node
/kind bug

We need to know why NPD upgrade causes the flake #121973 before next bump.

**Comment by kumarankit999** [comment]
Who is working on this issue currently!!!???

**Comment by pacoxu** [comment]
> Who is working on this issue currently!!!???

Feel free to assign to yourself if you want to work on it. The related issue https://github.com/kubernetes/kubernetes/issues/121973 is also not assigned.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.15
I still do not try it yet.

**Comment by liangyuanpeng** [comment]
https://github.com/kubernetes/kubernetes/pull/123740 is working for npd to 0.8.17

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/125128 upgrade npd to v0.8.19

/close
