### ISSUE TITLE
ExternalName to resolve  a custom domain in Bare metal K8s

### ISSUE THREAD

**Issue by abelkbil** [kubernetes/kubernetes#122199]
### What happened?

![qeqw](https://github.com/kubernetes/kubernetes/assets/1478274/6a8421ac-be83-423d-a754-72c3eca3ccd4)

Hi everyone, As in above image , I have a managed k8s v 1.28 running on a Ubuntu PC. I have some web api available in another machine. This is a intranet network. Typicaly i modify /etc/hosts file and api are able to connect to IIS via custom domain.

In this senario, I created below external service

```
apiVersion: v1
kind: Service
metadata:
  name: external-api
  namespace: demo
spec:
  type: ExternalName
  externalName: 10.12.0.1
```

I also created a ConfigMap, Now i removed this

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-dns-config
  namespace: demo
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        hosts {
            nodea.dev 10.12.0.1
            fallthrough
        }
    }
```

still when in do `kubectl exec -it poda -- nslookup nodea.dev` It is not able to resolve. Since this is a managed K8s, do i need to modify coredns directly, but how can i automate later ?

This is how it used in code
```
  "auth":{
        "clientId":"WebClient",
        "authority":"https://external-api/auth-server",
        "authenticationServerUrl":"https://external-api/auth-server",
        "signInType":"redirect",
        }
```
I expect ```https://nodea.dev``` should be resolved inside pod

Since external IP and domain name are dynamic depends on env, I want to convert this total solution to a helm chart eventualy and read the external ip and custom domain from values.yaml file.

Thank you for time and consideration. Any comments are helpfull. Thank you

### What did you expect to happen?

I expect ```https://nodea.dev``` should be resolved inside pod. But Pod logs error, saying could not resolve domain. 

### How can we reproduce it (as minimally and precisely as possible)?

All pods in my name space should able to communicate a api avilable in intranet , due to https certificcate using a custim domain. There is no DNS to resolve IP, 

### Anything else we need to know?

I am looking for a solution which i can convert to eventualy to a helm chart, so it should be configrable. 

### Kubernetes version

<details>

```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

</details>

### Cloud provider

<details>
Bare Metal Ubuntu PC
</details>

### OS version

Bare Metal Ubuntu PC
<details>
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

```
</details>

### Install tools

<details>
kubeadm init
</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O with Proxy
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
```

**Comment by aojea** [comment]
/remove kind-bug
/kind support

This is a configuration problem, if you want to use coreDNS and modify its configuration, you have first to understand how it is configured, commonly it uses a configmap, but then you have to modify THAT configmap https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options

If you want to use an ExternalName, that returns a cname, so you have to configure somewhere that DNS that you are pointing to https://kubernetes.io/docs/concepts/services-networking/service/#externalname , the fact that an IP address is a valid value does not mean that is going to return an A record to that address.

Github issues are for bugs, so I will close this and I encourage you to try to find another solution in other forums, the coreDNS seems a good option IMHO, you should try to get that working

/close
