### ISSUE TITLE
subPath 挂载 卷 的二级目录为空，无法挂载

### ISSUE THREAD

**Issue by DokiDoki1103** [kubernetes/kubernetes#122155]
### What happened?

<img width="551" alt="图片" src="https://github.com/kubernetes/kubernetes/assets/62740231/2b8485c7-a6f8-4e3d-984a-d206bd7519a0">
<img width="568" alt="图片" src="https://github.com/kubernetes/kubernetes/assets/62740231/8ed7337c-bff9-4b8e-9edf-5da9fc3e028b">

<img width="948" alt="图片" src="https://github.com/kubernetes/kubernetes/assets/62740231/fef4a139-19a6-4449-b80c-ebe349fa6f57">

**Comment by HirazawaUi** [comment]
Can you report bugs in English? We usually use English to collaborate.

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by neolit123** [comment]
> 挂载 卷 的二级目录为空，无法挂载 

as the above link says support tickets must not be logged here.
but if you think there is a bug or missing feature please re-open this ticket and translate it in english with all required details in the issue template.
