### ISSUE TITLE
Unable to run make lint

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#122190]
### What happened?

If I try to run `make lint` in my dev environment, I get a security error saying the checksum mismatches.

```
kehannon@kehannon-thinkpadp1gen4i:~/Work/kubernetes$ make lint
installing golangci-lint and logcheck plugin from hack/tools into /home/kehannon/Work/kubernetes/_output/local/bin
go: downloading github.com/Abirdcfly/dupword v0.0.13
go: downloading github.com/Antonboom/testifylint v0.2.3
go: downloading github.com/butuzov/ireturn v0.2.1
go: downloading github.com/catenacyber/perfsprint v0.2.0
go: downloading github.com/daixiang0/gci v0.11.2
go: downloading github.com/golangci/gofmt v0.0.0-20231018234816-f50ced29576e
go: downloading github.com/jgautheron/goconst v1.6.0
go: downloading github.com/macabu/inamedparam v0.1.2
go: downloading github.com/mgechev/revive v1.3.4
go: downloading github.com/nunnatsa/ginkgolinter v0.14.0
go: downloading github.com/polyfloyd/go-errorlint v1.4.5
verifying github.com/butuzov/ireturn@v0.2.1: checksum mismatch
        downloaded: h1:QXLHriOCzRI8VN9JPhfDcaaxg3TMFD46n1Pq6Wf5zEw=
        go.sum:     h1:w5Ks4tnfeFDZskGJ2x1GAkx5gaQV+kdU3NKNr3NEBzY=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
make: *** [Makefile:350: lint] Error 1
```

### What did you expect to happen?

I should be able to run the linter.

### How can we reproduce it (as minimally and precisely as possible)?

Run `make lint` on master.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
master
</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
k/k's go version is at this:
https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml#L121

make sure your local version matches.
but this is a peculiar problem.

> SECURITY ERROR
> This download does NOT match an earlier download recorded in go.sum.

/sig testing security

**Comment by kannon92** [comment]
> k/k's go version is at this: https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml#L121
> 
> make sure your local version matches. but this is a peculiar problem.
> 
> > SECURITY ERROR
> > This download does NOT match an earlier download recorded in go.sum.
> 
> /sig testing security

Yep, it matches exactly.

**Comment by kannon92** [comment]
/cc @pohly

I wonder if this is just a local dev issue as we don’t have this issue in the CI. Do we use the code for make lint in CI?

**Comment by pohly** [comment]
> make sure your local version matches.

That hasn't been necessary for a while. The build rules check the installed Go version and installs exactly the right one if needed.

**Comment by neolit123** [comment]
it's probably not an actual security problem but rather just a cache problem, see:
https://stackoverflow.com/questions/54133789/go-modules-checksum-mismatch

and tell us if clearing the cache fixes it for you.

**Comment by kannon92** [comment]
I'll delete the cache and redownload everything and see if that fixes this.

**Comment by kannon92** [comment]
I still have this issue after doing `go clean -modcache && go mod tidy`.

**Comment by kannon92** [comment]
> Do you have a GOPROXY set? Which proxy are you using? It might be useful to compare with fellow developers who are in the same environment.

I am using GOPROXY=direct. I am using fedora 39.

**Comment by pohly** [comment]
I can reproduce it with `go clean -modcache && env GOPROXY=direct make lint`:
```
verifying github.com/butuzov/ireturn@v0.2.1: checksum mismatch
	downloaded: h1:QXLHriOCzRI8VN9JPhfDcaaxg3TMFD46n1Pq6Wf5zEw=
	go.sum:     h1:w5Ks4tnfeFDZskGJ2x1GAkx5gaQV+kdU3NKNr3NEBzY=
```

**Comment by pohly** [comment]
It works without `GOPROXY=direct`.

Found it: https://github.com/butuzov/ireturn/issues/69
