### ISSUE TITLE
PodScheduled lastTransitionTime null after scheduling gate removal

### ISSUE THREAD

**Issue by ahaysx** [kubernetes/kubernetes#122164]
### What happened?

When a scheduling gated pod is ungated, the `PodScheduled` condition's `lastTransitionTime` is consistently null until the pod is scheduled:

```
"conditions": [
    {
        "lastProbeTime": null,
        "lastTransitionTime": null,
        "message": "0/5 nodes <elided>",
        "reason": "Unschedulable",
        "status": "False",
        "type": "PodScheduled"
    }
]
```

### What did you expect to happen?

Pods without a scheduling gate have the same `PodScheduled` condition but  `lastTransitionTime` is populated:

```
"conditions": [
    {
        "lastProbeTime": null,
        "lastTransitionTime": "2023-12-04T01:48:32Z",
        "message": "0/4 nodes <elided>",
        "reason": "Unschedulable",
        "status": "False",
        "type": "PodScheduled"
    }
]
```

### How can we reproduce it (as minimally and precisely as possible)?

Submit a pod with a scheduling gate. Observe that after removal of the gate, the `PodScheduled` pod condition.

### Anything else we need to know?

I uncovered this while using Kueue and the ProvisioningRequest feature. Since this is reproducible with just the scheduling gate, I think k/k is the right project for the issue.

### Kubernetes version

<details>

```console
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.3-gke.1203000", GitCommit:"28396c07d85d0131e4f94369f78a7dee01ca1e0c", GitTreeState:"clean", BuildDate:"2023-10-26T09:28:34Z", GoVersion:"go1.20.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ahaysx** [comment]
The gated pod has just this condition. The transition time is also null, but is that expected since it is the first condition?

```
"conditions": [
    {
        "lastProbeTime": null,
        "lastTransitionTime": null,
        "message": "Scheduling is blocked due to non-empty scheduling gates",
        "reason": "SchedulingGated",
        "status": "False",
        "type": "PodScheduled"
    }
]
```

**Comment by kerthcet** [comment]
Are you still on this, we meet the same problem.

**Comment by alculquicondor** [comment]
I just noticed a related issue:
When the Pod no longer has schedulingGates, the SchedulingGated condition is correctly transitioned to False, but it has the message `Scheduling is blocked due to non-empty scheduling gates`, which can be confusing.

**Comment by lianghao208** [comment]
@ahaysx It's been over a month, I assume you might no longer work on this? We encounter the same bug and hope this bug can be fixed as soon as possible(hopefully next release). Since there is no further update on this issue, I am proposing a protential fix on #122636 now, can you assign this issue to me and review the code once you are available? Thanks.

**Comment by ahaysx** [comment]
Sorry I have been on vacation until today. Thanks for the fix @lianghao208!

**Comment by alculquicondor** [comment]
@lianghao208, are you still working on this?

**Comment by lianghao208** [comment]
> @lianghao208, are you still working on this?

@alculquicondor I’ve submitted the PR, but it seems lack of reviewer moving this forward.
