### ISSUE TITLE
postContainer - something to run after container success exit

### ISSUE THREAD

**Issue by sls1j** [kubernetes/kubernetes#122242]
### What would you like to be added?

We have the ability of an initContainer for pods.  It would be nice to have postConatiner that would run after the pod has exited successfully.  

```apiVersion: batch/v1
kind: Job
metadata:
  name: big-job
spec:
  template:
    spec:
      initContainers:
      - image: 192.168.4.120:5000/s3-pull:v1.000
        command:
        - "dotnet"
        - "s3Pull.dll"
        - "http://192.168.4.120:4566"
        - "/data/input"
        name: s3-pull
        volumeMounts:
        - name: shared-dir
          mountPath: /data
      containers:
      - name: big-job
        image: 192.168.4.120:5000/job-test:v1.001
        command: ["dotnet",  "jobTest.dll"]
        volumeMounts:
        - name: shared-dir
          mountPath: /data
      postContainers:
      - image: 192.168.4.120:5000/s3-push:v1.000
        command:
        - "dotnet"
        - "s3Push.dll"
        - "http://192.168.4.120:4566"
        - "/data/output"
        name: s3-push
        volumeMounts:
        - name: shared-dir
          mountPath: /data
      volumes:
      - name: shared-dir
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 4
```

### Why is this needed?

I have a situation where I'm receiving containers from a 3rd party.  I can use an initContainer to load files from s3 into the pod's directory so that the 3rd party doesn't have to worry about s3, key distribution etc.  The contain then executes and places the results in a specific location.  However, currently I have to put those in persistent volume claim and have a separate process monitoring it to push the data into s3.  It would be very nice to have a postContainer that runs after the job has completed and has access to the job's directory that could push the files to s3.

**Comment by aojea** [comment]
You can achieve the same adding a container that captures the SIGTERM signal on termination and implement that logic

**Comment by sls1j** [comment]
Hmmm, I think I see what you are saying.  Add another container within the specs that should have access to the internal volume and be able to monitor for a SIGTERM within itself since the sigterm is part of the pod and should be sent to every container within the pod...  That is brilliant.  I think I can see how to do that.  Thanks!

**Comment by thockin** [comment]
The new sidecar support should help, too - they will terminate AFTER the main app container.
