### ISSUE TITLE
NodeAffinity/NodeUnschedulable QueueingHint may miss Node related events that make Pod schedulable

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#122284]
### What happened?

/kind bug
/triage accepted
/priority urgent
/sig scheduling
/assign

NodeAffinity QueueingHint may miss Node related events that make Pod schedulable because of preCheck.
It's similar to: https://github.com/kubernetes/kubernetes/pull/119177#issuecomment-1820091877

So:
1. Node is added. But, it's filtered out by preCheck (due to node's unready or whatever) and the scheduling queue doesn't receive NodeAdded. (noderesourcefit cannot receive NodeAdded.)
2. Node is updated and ready now. But, this event is NodeUpdated.

In such scenarios, NodeAffinity may return `QueueSkip` to the event due to (2).
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/nodeaffinity/node_affinity.go#L94-L131

### What did you expect to happen?

We have to loosen the filtering in `isSchedulableAfterNodeChange` until preCheck is removed.
https://github.com/kubernetes/kubernetes/issues/110175

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Pod with NodeAffinity under the situation where no Node can accommodate the Pod.
2. Create a new Node.

It may cause the above problematic scenario.

### Kubernetes version

master

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sanposhiho** [comment]
/assign @carlory 

I'll have a PR to just revert QHint since the release date is close. But, I'll leave the QHint re-implementation for @carlory.

**Comment by sanposhiho** [comment]
Wait... It's the same for NodeUnschedulable. 

/retitle NodeAffinity/NodeUnschedulable QueueingHint may miss Node related events that make Pod schedulable

**Comment by sanposhiho** [comment]
/assign @wackxu 
For the NodeUnschedulable QueueingHint re-implementation.

**Comment by Vyom-Yadav** [comment]
@sanposhiho The release cut is under progress, are we reverting https://github.com/kubernetes/kubernetes/pull/119396 and https://github.com/kubernetes/kubernetes/pull/119155?

**Comment by sanposhiho** [comment]
Unfortunately, I suppose our leads are not around, they're all in US timezone and it's late night now.

**Comment by sanposhiho** [comment]
@Vyom-Yadav 
Yes, I submitted the PRs.
But, unfortunately, I suppose our leads are not around, they're all in US timezone and it's late night now.

**Comment by kerthcet** [comment]
All node related plugins are influenced.

**Comment by sanposhiho** [comment]
Yes, I just went through all, and seems these two are the only ones that has got QHint in the last release.

- NodePort 🙆‍♂️  https://github.com/sanposhiho/kubernetes/blob/7cba35f6519c6e0cf72848185ef3f9a524601467/pkg/scheduler/framework/plugins/nodeports/node_ports.go#L118-L124
- DRA: doesn't have QHint for Node events

**Comment by sanposhiho** [comment]
Wait... I think https://github.com/kubernetes/kubernetes/issues/109437 is silently coming back.
Regardless of whether QHint is implemented or not, we have to make sure all plugins that have Node Add event to have Node Update event. I see some plugins don't follow it. (we must mention it in the doc somewhere.)

**Comment by kerthcet** [comment]
If you mean the newly added plugins like the DRA, I think yes, let me check that in.

**Comment by sanposhiho** [comment]
Yes, I meant that. For newly added plugins like DRA, they have NodeAdd, but not NodeUpdated.

**Comment by sanposhiho** [comment]
We discussed at slack:
https://kubernetes.slack.com/archives/C2C40FMNF/p1702438650646789

And decided we'll make the feature gate for QHint disable by default. (There was a discussion of disablement for this before actually because we observed a memory consumption issue: https://github.com/kubernetes/kubernetes/issues/120622) This issue reinforces that idea. We'll make it enable by default once all issues here + memory consumption issue are addressed.

**Comment by sanposhiho** [comment]
Also, one general problem is that we have few integration (or e2e) tests for requeueing scenario.

**Comment by kerthcet** [comment]
Related problems we faced now: 
1. preCheck has some potential bugs as https://github.com/kubernetes/kubernetes/issues/110175 described, so we're planning to remove preCheck someday(without obvious performance degradation)
2. currently, node related plugins like `nodeUnschedulable` & `nodeAffinity` & `nodeResourceFit` with tight validations in hintFunc is conflict with preCheck as this issue mentioned.
3. Also because of preCheck, node plugins register `nodeAdd` events should also register the `nodeUpdate` event, DRA  is one plugin we missed. (I'll raise a quick fix with the consistent policy we applied now)

To the 2nd question, a feasible approach is only check the newObj (we're now validating the oldObj and newObj both, only the oldObj doesn't match but the newObj does, then we'll return `Queue`), still better than before when we only watch for the event. But the disadvantage is not that efficient, like we have two plugins A & B, also two nodes Node1, Node2. When pod is scheduling, Node1 is failed by pluginA, Node2 is failed by pluginB, so when Node2 updated, pluginA will pass the validation however, pod is still unschedulable.

**Comment by sanposhiho** [comment]
Regarding (3), what do you think about this idea: when plugins add `nodeAdd`, we automatically register `nodeUpdated` (until preCheck is removed) so that we could technically prevent https://github.com/kubernetes/kubernetes/issues/109437 happening again in any plugins.

**Comment by sanposhiho** [comment]
The action items in my mind (correct me if I am mistaken or missed something.)

- [ ] plugins that have `nodeAdd` should have `nodeUpdate` as well. (maybe we'll fix it via https://github.com/kubernetes/kubernetes/pull/122292)
- [ ] revert PRs of NodeAffinity/NodeUnschedulable QHints (https://github.com/kubernetes/kubernetes/pull/122285 and https://github.com/kubernetes/kubernetes/pull/122288) and cherry-pick them.
- [ ] re-implement QHints for NodeAffinity/NodeUnschedulable.
- [ ] have a sufficient number of integration tests for QueueingHint to catch this kind of bugs.
- [ ] have a UT for QHint feature gate disabled. (https://github.com/kubernetes/kubernetes/pull/122289#issuecomment-1853266698)
- [ ] remove preCheck eventually. (tracked in https://github.com/kubernetes/kubernetes/issues/110175)

I'll probably create other issues corresponding to them, not to put a lot of context in this issue later.

**Comment by kerthcet** [comment]
What I hope is we can have a quick fix for No.2 and cherry-picked, then let's work out the whole stuff in the next release, no longer need to patch anything additionally, also longer.

**Comment by alculquicondor** [comment]
> Also, one general problem is that we have few integration (or e2e) tests for requeueing scenario.

Let's make that a requirement for re-enabling the feature again.

**Comment by sanposhiho** [comment]
I created the issues based on the above checklist https://github.com/kubernetes/kubernetes/issues/122284#issuecomment-1853346333

- https://github.com/kubernetes/kubernetes/issues/122304
- https://github.com/kubernetes/kubernetes/issues/122305
- https://github.com/kubernetes/kubernetes/issues/122306

**Comment by carlory** [comment]
@sanposhiho [here](https://github.com/kubernetes/kubernetes/pull/122309)'s the re-implementation of the NodeAffinity plugin, please take a look.

**Comment by sanposhiho** [comment]
Reverting is done and we have issues for other action items, I believe we can close it. 
Feel free to reopen if anyone disagree.

/close

**Comment by Huang-Wei** [comment]
@sanposhiho do you want (or already have) to create an umbrella issue tracking all on-going items to re-enable QueueingHint feature. In particular, we don't really want to re-stomp on issue like #109437.

**Comment by sanposhiho** [comment]
We have all issues individually, but don't have ☔ one. Let me create it for a better tracking.

**Comment by sanposhiho** [comment]
https://github.com/kubernetes/kubernetes/issues/122597
I'll organize the list later.
