### ISSUE TITLE
Guestbook example app port

### ISSUE THREAD

**Issue by coreyperkins** [kubernetes/kubernetes#12224]
I have ran the scripts to generate a cluster on azure. I am using the guestbook example. The cluster is up and running and I can use swagger ui. I've been able to query for services, pods, and nodes. However, I am not sure which port the php application is running on. I have tried 80, 8000, and 31605 but exposing any of those doesn't seem to make it available. I also ran netstat on my kube-01, the results are attached. Thanks!

![screen shot 2015-08-04 at 3 53 32 pm](https://cloud.githubusercontent.com/assets/429696/9072471/fda4ff62-3ac0-11e5-9f82-1529ee2de0ef.png)

**Comment by coreyperkins** [comment]
Thanks for the tags mbforbes, I'm certainly still looking for a solution.

**Comment by errordeveloper** [comment]
Thank you for reporting this and I had fallowing #7826 also. Have you ran the `./expose_guestbook_app_port.sh` script, if so could you provide the output?

**Comment by coreyperkins** [comment]
I couldn't find the expose script because I was working with the 1.0.1 tag. I did find it in master so I pulled that into my local copy, but I got the following upon execution.

<img width="700" alt="screen shot 2015-08-18 at 4 56 15 am" src="https://cloud.githubusercontent.com/assets/429696/9327311/814ee838-4565-11e5-894e-9a468fbf692a.png">

**Comment by errordeveloper** [comment]
@coreyperkins I am afraid there is a lag of what version gets into which tag, which basically means that having checked-out `v1.0.1` tag you then deploy an older version of Kubernetes to Azure. If you checkout `release-1.0` branch, you will get version 1.0.1 as it currently stands.

**Comment by errordeveloper** [comment]
The problem is that the older version of `kubectl` you have deployed doesn't understand the `-L`, it's best if you just destroy and re-provision the cluster.

**Comment by coreyperkins** [comment]
@errordeveloper Using master worked perfectly. I was trying to be safe by checking out a tag I thought was stable and I shot myself in the foot. :) 

Thanks!
