### ISSUE TITLE
Does verify-licenses work?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#122249]
When I run it manually, I get:

```
[ERROR] The following go-packages in the project have unknown or unreachable license URL:
google.golang.org/genproto/googleapis/api                                                            :  Apache-2.0           : https://github.com/googleapis/go-genproto/blob/23370e0ffb3e/googleapis/api/LICENSE
google.golang.org/genproto/googleapis/rpc                                                            :  Apache-2.0           : https://github.com/googleapis/go-genproto/blob/b8732ec3820d/googleapis/rpc/LICENSE
sigs.k8s.io/kustomize/api                                                                            :  Apache-2.0           : https://github.com/kubernetes-sigs/kustomize/blob/6ce0bf390ce3/api/LICENSE
sigs.k8s.io/kustomize/kustomize/v5/commands/build                                                    :  Apache-2.0           : https://github.com/kubernetes-sigs/kustomize/blob/6ce0bf390ce3/kustomize/LICENSE
sigs.k8s.io/kustomize/kyaml                                                                          :  Apache-2.0           : https://github.com/kubernetes-sigs/kustomize/blob/6ce0bf390ce3/kyaml/LICENSE
+++ [1209 10:28:28] [ERROR] Project is using go-packages with unknown or unreachable license URLs. Please refer to the CNCF's approved licence list for further information: https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md
```

Clearly that is wrong, it's just looking in the wrong place.  I also see a reference to https://github.com/google/go-licenses/pull/110 which is still open 2 years later.

Does this script run?  Is it useful?

**Comment by saschagrunert** [comment]
This job runs the script and fails right now as well: https://testgrid.k8s.io/sig-testing-misc#kubernetes-verify-go-licenses-periodical

**Comment by saschagrunert** [comment]
Another note: It runs around 5-6 minutes right now: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/kubernetes-verify-go-licenses-periodical

**Comment by thockin** [comment]
It has a very poorly placed n^2 loop. That can be fixed.

**Comment by saschagrunert** [comment]
It looks like that go-licenses cannot handle multi module repos if the license is only part of the repo root: https://github.com/google/go-licenses/issues/186

The question is: do we want to contribute such a feature or don't we need the license test at all?

**Comment by BenTheElder** [comment]
We should vet licenses in presubmit.

Though I think dep approvers are pretty good at checking this, one less thing to manually vet would be ideal.

If we can't speed it up, we can add a job that only runs on vendor/ changes.
