### ISSUE TITLE
Dynamic selector for PVC

### ISSUE THREAD

**Issue by PaveLGIL** [kubernetes/kubernetes#122275]
### What happened?

I know that it is not a bug, but, I don't know where I should create it. Sorry guys.

### What did you expect to happen?

Is it possible to add possibility to use dynamic selectors in PVC.
For Example:
I have this STS
<details>

```console
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: some-sts
  namespace: some-namespace
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  replicas: 3
  selector:
    matchLabels:
      app: some-app
  serviceName: some-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: some-app
    spec:
      containers:
        - image: ''
          imagePullPolicy: IfNotPresent
          name: app
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: data-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
        selector:
          matchLabels:
            type: dev-some-data
        storageClassName: ''
        volumeMode: Filesystem
      status:
        phase: Pending
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: logs-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        selector:
          matchLabels:
            type: dev-some-logs
        storageClassName: ''
        volumeMode: Filesystem
      status:
        phase: Pending
```

</details>

I want to have possibility to use PV selector depending on STS and Pods names. For example
<details>

```console
        selector:
          matchLabels:
            type: $STS_NAME-$REPLICA_INDEX
```

</details>

It is needed to say pods use their own PV's.
Is it possible?

### How can we reproduce it (as minimally and precisely as possible)?

I understand that it is not correct place for this question, but, please, move it into correct place

### Kubernetes version

<details>

```console
Client Version: v1.28.2
Server Version: v1.27.7-eks-
```

</details>

### Cloud provider

<details>
AWS
</details>

**Comment by pranav-pandey0804** [comment]
remove /kind bug

**Comment by pranav-pandey0804** [comment]
@PaveLGIL 
> Is it possible to add possibility to use dynamic selectors in PVC.

It is not possible, you can either use static provisioning with a specific PV name or a selector or dynamic provisioning with storage class.

**Comment by pranav-pandey0804** [comment]
@PaveLGIL hope it helped you, 
if there is an actual bug please log a new issue and fill the template.

/close

**Comment by pranav-pandey0804** [comment]
@PaveLGIL You can close this issue as I'm unable to do it, Thanks!
