### ISSUE TITLE
When upgrading in rolling upgrade mode (1.25.7 to 1.26.9), some pods are not restarting due to authentication failure 

### ISSUE THREAD

**Issue by lallema** [kubernetes/kubernetes#122392]
I have a cluster in 1.25.7 version and upgrade it to 1.26.9.
When all is finished, some pods are not able to get the images in our private registry (docker) as if the pod lost the secret.
Knowing that other pods are correctly restarted in the same namespace (and secret needed to connect to the private registry are present in this namespace)

in my case:
knative-operator-6649bc5fc7-jlk8q 0/1 ImagePullBackOff 0 14m
operator-webhook-5fd954994f-wp9kv 0/1 ImagePullBackOff 0 14m

last time it was the kube-proxy pod that could not start

**Comment by neolit123** [comment]
/close
dup https://github.com/kubernetes/kubernetes/issues/122390
