### ISSUE TITLE
restart kubelet, the node change its status from ready to notready

### ISSUE THREAD

**Issue by lance5890** [kubernetes/kubernetes#122338]
### What happened?

when node status is already ready, and then restart kubelet manually, and watch the node status, when kubelet starts again, it will record a notready event

```
Dec 15 17:25:41 single1 kubenswrapper[1832249]: I1215 17:25:41.121883 1832249 setters.go:549] "Node became not ready" node="single1" condition={Type:Ready Status:False LastHeartbeatTime:2023-12-15 17:25:41.121753163 +0800 CST m=+0.403692528 LastTransitionTime:2023-12-15 17:25:41.121753163 +0800 CST m=+0.403692528 Reason:KubeletNotReady Message:[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]}
Dec 15 17:25:41 single1 kubenswrapper[1832249]: E1215 17:25:41.137425 1832249 kubelet.go:2129] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
Dec 15 17:25:41 single1 kubenswrapper[1832249]: E1215 17:25:41.262177 1832249 kubelet.go:2129] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Dec 15 17:25:41 single1 kubenswrapper[1832249]: E1215 17:25:41.463838 1832249 kubelet.go:2129] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Dec 15 17:25:41 single1 kubenswrapper[1832249]: E1215 17:25:41.864780 1832249 kubelet.go:2129] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Dec 15 17:25:42 single1 kubenswrapper[1832249]: E1215 17:25:42.665975 1832249 kubelet.go:2129] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
```

### What did you expect to happen?

when node status is ready ,start the kubelet will not record the notready status

### How can we reproduce it (as minimally and precisely as possible)?

watch the node status, and status will change from ready to notready when kubelet restart

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
v1.25.8
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
5.15.67-2.cl9.x86_64
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

sounds like a support ticket, if bug reopen.

/kind support
/close

**Comment by SergeyKanzhelev** [comment]
/triage accepted

this may work as expected and in this case we need to change it to a feature request. 


/assign @rphillips @haircommander

**Comment by SergeyKanzhelev** [comment]
Also, the issue report is on 1.25 which is out of support in Open Source. Can you repro it on later versions?

**Comment by lance5890** [comment]
> Also, the issue report is on 1.25 which is out of support in Open Source. Can you repro it on later versions?

I think there is nothing to do with the cri-o. The cri-o is running normally, what we do is just to restart the kubelet

**Comment by aojea** [comment]
when the kubelet starts can not assume everything is ready, because it does not know for how long it was stopped, and independently, things we'll may have changed during this time, I think this is the correct and expected behavior

**Comment by SergeyKanzhelev** [comment]
/close

please re-open with clear expectations on what should be hapenning and on the supported version of a kubelet. Thank you!
