### ISSUE TITLE
noderesourcefit: change PodUpdate QHint to take a new scenario into consideration 

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#122354]
See: https://github.com/kubernetes/kubernetes/pull/122234#issuecomment-1859021909
/kind feature
/sig scheduling
/assign @carlory 

---

After https://github.com/kubernetes/kubernetes/pull/122234, the scheduler starts to use QueueingHint registered for Pod/Updated event to determine whether unschedulable Pods update make them schedulable. 
We have to change PodUpdate QHint in noderesourcefit to take into consideration that the pod might equal the unscheduled pod.
i.e.,
```go
func (f *Fit) isSchedulableAfterPodChange(logger klog.Logger, pod *v1.Pod, oldObj, newObj interface{}) (framework.QueueingHint, error) {
  // maybe pod == newObj (oldObj)
}
```

**Comment by carlory** [comment]
I'll do it tomorrow.

**Comment by sanposhiho** [comment]
/close

include this to #122234
