### ISSUE TITLE
[Flake] [Conformance] unable to retrieve the complete list of server APIs: wardle.example.com/v1alpha1: stale GroupVersion discovery

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#122333]
### Which jobs are flaking?

e2e conformance jobs, seen in aws, capz-windows, and kind

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1729268578957398016

### Which tests are flaking?

https://storage.googleapis.com/k8s-triage/index.html?text=stale%20GroupVersion%20discovery

### Since when has it been flaking?

seen back to 1.28

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel-1-28/1727260532764839936

https://storage.googleapis.com/k8s-triage/index.html?text=stale%20GroupVersion%20discovery shows flakes going back as far as history exists

### Reason for failure (if possible)

[FAILED] could not find group version resource for dynamic client and wardle/flunders (discovery error: <nil>, discovery results: map[schema.GroupVersionResource]struct {}{schema.GroupVersionResource{Group:"", Version:"v1", Resource:"bindings"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"configmaps"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"endpoints"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"events"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"limitranges"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"persistentvolumeclaims"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"pods"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"podtemplates"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"replicationcontrollers"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"resourcequotas"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"secrets"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"serviceaccounts"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"services"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"controllerrevisions"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"daemonsets"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"deployments"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"replicasets"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"statefulsets"}:struct {}{}, schema.GroupVersionResource{Group:"authorization.k8s.io", Version:"v1", Resource:"localsubjectaccessreviews"}:struct {}{}, schema.GroupVersionResource{Group:"autoscaling", Version:"v2", Resource:"horizontalpodautoscalers"}:struct {}{}, schema.GroupVersionResource{Group:"batch", Version:"v1", Resource:"cronjobs"}:struct {}{}, schema.GroupVersionResource{Group:"batch", Version:"v1", Resource:"jobs"}:struct {}{}, schema.GroupVersionResource{Group:"coordination.k8s.io", Version:"v1", Resource:"leases"}:struct {}{}, schema.GroupVersionResource{Group:"discovery.k8s.io", Version:"v1", Resource:"endpointslices"}:struct {}{}, schema.GroupVersionResource{Group:"events.k8s.io", Version:"v1", Resource:"events"}:struct {}{}, schema.GroupVersionResource{Group:"networking.k8s.io", Version:"v1", Resource:"ingresses"}:struct {}{}, schema.GroupVersionResource{Group:"networking.k8s.io", Version:"v1", Resource:"networkpolicies"}:struct {}{}, schema.GroupVersionResource{Group:"policy", Version:"v1", Resource:"poddisruptionbudgets"}:struct {}{}, schema.GroupVersionResource{Group:"rbac.authorization.k8s.io", Version:"v1", Resource:"rolebindings"}:struct {}{}, schema.GroupVersionResource{Group:"rbac.authorization.k8s.io", Version:"v1", Resource:"roles"}:struct {}{}, schema.GroupVersionResource{Group:"storage.k8s.io", Version:"v1", Resource:"csistoragecapacities"}:struct {}{}, schema.GroupVersionResource{Group:"wardle.example.com", Version:"v1beta1", Resource:"flunders"}:struct {}{}})

- or -

[FAILED] could not find group version resource for dynamic client and wardle/flunders (discovery error: unable to retrieve the complete list of server APIs: wardle.example.com/v1alpha1: stale GroupVersion discovery: wardle.example.com/v1alpha1, discovery results: map[schema.GroupVersionResource]struct {}{schema.GroupVersionResource{Group:"", Version:"v1", Resource:"bindings"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"configmaps"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"endpoints"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"events"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"limitranges"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"persistentvolumeclaims"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"pods"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"podtemplates"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"replicationcontrollers"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"resourcequotas"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"secrets"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"serviceaccounts"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"services"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"controllerrevisions"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"daemonsets"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"deployments"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"replicasets"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"statefulsets"}:struct {}{}, schema.GroupVersionResource{Group:"authorization.k8s.io", Version:"v1", Resource:"localsubjectaccessreviews"}:struct {}{}, schema.GroupVersionResource{Group:"autoscaling", Version:"v2", Resource:"horizontalpodautoscalers"}:struct {}{}, schema.GroupVersionResource{Group:"batch", Version:"v1", Resource:"cronjobs"}:struct {}{}, schema.GroupVersionResource{Group:"batch", Version:"v1", Resource:"jobs"}:struct {}{}, schema.GroupVersionResource{Group:"coordination.k8s.io", Version:"v1", Resource:"leases"}:struct {}{}, schema.GroupVersionResource{Group:"discovery.k8s.io", Version:"v1", Resource:"endpointslices"}:struct {}{}, schema.GroupVersionResource{Group:"events.k8s.io", Version:"v1", Resource:"events"}:struct {}{}, schema.GroupVersionResource{Group:"networking.k8s.io", Version:"v1", Resource:"ingresses"}:struct {}{}, schema.GroupVersionResource{Group:"networking.k8s.io", Version:"v1", Resource:"networkpolicies"}:struct {}{}, schema.GroupVersionResource{Group:"policy", Version:"v1", Resource:"poddisruptionbudgets"}:struct {}{}, schema.GroupVersionResource{Group:"rbac.authorization.k8s.io", Version:"v1", Resource:"rolebindings"}:struct {}{}, schema.GroupVersionResource{Group:"rbac.authorization.k8s.io", Version:"v1", Resource:"roles"}:struct {}{}, schema.GroupVersionResource{Group:"storage.k8s.io", Version:"v1", Resource:"csistoragecapacities"}:struct {}{}})

### Anything else we need to know?

Unclear if the issue is discovery going stale, or the aggregated server not responding, or something else

### Relevant SIG(s)

/sig api-machinery

**Comment by pacoxu** [comment]
It flakes in https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel once recently.

**Comment by Jefftree** [comment]
/assign
Based on https://storage.googleapis.com/k8s-triage/index.html?text=stale%20GroupVersion%20discovery, I don't see it flaking as far as history exists. It seemed to have started flaking around March/April 2023. This also corresponds to when aggregated discovery was enabled by default so it may be related.

Will do some more digging.

**Comment by Neha-dot-Yadav** [comment]
Hey @pacoxu 
Is this issue fixed?
If yes, from which version of  kubernetes will this fix be available from?

**Comment by pacoxu** [comment]
> Hey @pacoxu Is this issue fixed? If yes, from which version of kubernetes will this fix be available from?

https://storage.googleapis.com/k8s-triage/index.html?text=stale%20GroupVersion%20discovery
This still flakes in some CIs.

**Comment by Neha-dot-Yadav** [comment]
> > Hey @pacoxu Is this issue fixed? If yes, from which version of kubernetes will this fix be available from?
> 
> https://storage.googleapis.com/k8s-triage/index.html?text=stale%20GroupVersion%20discovery This still flakes in some CIs.
> 
> The flake rate is very low, but it is a conformance test.

Thanks for the quick response.
I see it is very flaky.
Is there any active work going on to fix this?
If yes, is there any estimated time by which it could be fixed?

**Comment by pacoxu** [comment]
@Jefftree do you have some update on this?

**Comment by fxierh** [comment]
https://github.com/kubernetes/kubernetes/issues/119582#issuecomment-2215054411
