### ISSUE TITLE
Support skip watch Headless Service in server-side.

### ISSUE THREAD

**Issue by Sakuralbj** [kubernetes/kubernetes#122394]
### What would you like to be added?

Support watch service with field-selector spec.clusterIP!=None to skip headless service in kube-apiserver. And kubelet/kube-proxy can skip watch headless-service in the future.
![image](https://github.com/kubernetes/kubernetes/assets/42128207/55a3df12-e70d-4b09-b5a4-a5a6ebff890e)

Now, endpoints will be added labels [service.kubernetes.io/headless](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L518) for headless service  by endpoints-controller,  and kube-proxy will ignore  event for it by label-selector. https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L913. But headless service haven't be added label and kube-proxy  still watch for it.

For kubelet, it watch service to add service-env for pods , but it ignores headless service when  build service-env-map(https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L549). So kubelet don't need to watch headless service either.

### Why is this needed?

In a large-cluster with more then 5000 nodes,  when we run kubeflow task( tfjob:pod:headlessService=1:10:10) with qps 10, it can save huge network bandwidth and cpu for kube-apiserver.

**Comment by aojea** [comment]
> In a large-cluster with more then 5000 nodes, when we run kubeflow task( tfjob:pod:headlessService=1:10:10) with qps 1

how many headless Services does that kubeflow task creates?

**Comment by aojea** [comment]
/sig scalability
this falls into that area too

**Comment by Sakuralbj** [comment]
> > In a large-cluster with more then 5000 nodes, when we run kubeflow task( tfjob:pod:headlessService=1:10:10) with qps 1
> 
> how many headless Services does that kubeflow task creates?

Under steady-state conditions, the cluster maintains 30,000 headless services. During daily new tasks, an additional 10,000 headless services will be created. The number of nodes in the cluster is around 7,000

**Comment by aojea** [comment]
interesting, I can see lately a lot of consumption of headless Services specially in AI/ML workloads,  instead of labelling Services we can add a field selector on the ClusterIP field, WDYT @wojtek-t @thockin ?

/cc @alculquicondor @ahg-g

**Comment by aojea** [comment]
Submitted https://github.com/kubernetes/kubernetes/pull/122541 , we are already having a selector for PodIP https://github.com/kubernetes/kubernetes/pull/50091/ so I think is ok having a field selector for the clusterIP field, that will bring the benefit of being able to build informers that filter headless services by using ` spec.clusterIP!="None"`
/assign

**Comment by Sakuralbj** [comment]
> Submitted #122541 , we are already having a selector for PodIP #50091 so I think is ok having a field selector for the clusterIP field, that will bring the benefit of being able to build informers that filter headless services by using ` spec.clusterIP!="None"` /assign

@aojea 
We firstly consider support the function  by field-selector for clusterIP,  compared to add label to headless service as we discussed in [#122502](https://github.com/kubernetes/kubernetes/pull/122502) , the main disadvantages is:

kube-apiserver needs to support field-selector with clusterIP  firstly, and then kubelet/kube-proxy can be updated. Otherwise, clients performing List-watch operations will receive errors like this,  which is not suitable for updating on existing clusters. 
![image](https://github.com/kubernetes/kubernetes/assets/42128207/c25d9026-d5bd-4f1f-a31a-b70630039c0b)
When using  the way for adding labels for headless-service,  kube-proxy  does not need to be updated (As it always list-watch with label-selector service.kubernetes.io/headless not exists) .

**Comment by Sakuralbj** [comment]
@aojea  If adding a field-selector  for clusterIP is considered to be ok. I think we can add IndexFields for service spec.clusterIP  as well (such as node metadata.name)，it can reduce events-count converted from kube-apiserver common channel to every cacheWatcher，reduce cpu-usage for kube-apiserver.

**Comment by aojea** [comment]
> . I think we can add IndexFields for service spec.clusterIP as well (such as node metadata.name)，it can reduce events-count converted from kube-apiserver common channel to every cacheWatcher，reduce cpu-usage for kube-apiserver.

That is on sig-scalability area and better @wojtek-t to decide in that, I can see how Headless services are more used lately in Kubernetes , special fo AI/ML workloads, so I think is a fair request to implement this field selector and allow to filter server side headless service, but I do not know the tradeoffs of using IndexFields

**Comment by wojtek-t** [comment]
> instead of labelling Services we can add a field selector on the ClusterIP field, WDYT @wojtek-t @thockin ?

+1

I would be ok with adding IndexFields for headless services too [re tradeoff, it adds a bit of memory usage, but it is fairly low - there was a similar thing happening recently in https://github.com/kubernetes/kubernetes/issues/120778 that has a lot of good analysis done]

**Comment by aojea** [comment]
> I would be ok with adding IndexFields for headless services too [re tradeoff, it adds a bit of memory usage, but it is fairly low - there was a similar thing happening recently in https://github.com/[/issues/120778](https://github.com/kubernetes/kubernetes/issues/120778) that has a lot of good analysis done]

I can see that IndexFields implementation is feature gated, I think we can iterate here and go with the fieldselector first and evaluate later the IndexFields addition

**Comment by alculquicondor** [comment]
The documentation currently says that headless services are labeled. Is this not accurate?

https://kubernetes.io/docs/reference/labels-annotations-taints/#servicekubernetesioheadless

**Comment by aojea** [comment]
> The documentation currently says that headless services are labeled. Is this not accurate?
> 
> https://kubernetes.io/docs/reference/labels-annotations-taints/#servicekubernetesioheadless

The control plane adds this label to an **Endpoints object** when the **owning Service** is headless.

**Comment by aojea** [comment]
/reopen

We had to revert the fix https://github.com/kubernetes/kubernetes/pull/123896/files
