### ISSUE TITLE
[Failing Test] gce-cos-master-scalability-100 & ci-kubernetes-e2e-gce-scale-performance

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#122325]
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1735187630884130816

### Which tests are failing?

- [x] e2e.go: ClusterLoaderV2: fixed by https://github.com/kubernetes/test-infra/pull/31470.
- [ ] TestMetrics error  https://storage.googleapis.com/k8s-triage/index.html?text=EtcdMetrics&test=overall#74370439712675f1ba4a 

### Since when has it been failing?

yesterday

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

### Reason for failure (if possible)

- warnings.go:70 unknown field "spec.selector.k8s-app": https://github.com/kubernetes/perf-tests/blob/83cc34c18d8b0a5583d3eec257a0c1bcc3cbd200/clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml#L64-L65

Error 1:
```
E1219 01:42:24.381984 18036 etcd_metrics.go:147] EtcdMetrics: failed to collect etcd database size
I1219 01:42:28.705907 18036 util.go:101] 1/3 targets are ready, example not ready target: {map[container:dns endpoint:metrics instance:10.64.75.4:8080 job:dns namespace:probes pod:dns-7dd54dbc8d-grd68 service:dns] unknown}

[measurement call TestMetrics - TestMetrics error: [action gather failed for EtcdMetrics measurement: unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting SSH client to prow@35.243.182.107:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'"}]]


```

Error 2(Fixed):
```
W1214 06:56:14.749194   18081 warnings.go:70] unknown field "spec.selector.k8s-app"
I1214 06:56:14.749347   18081 prometheus.go:439] Waiting for Prometheus stack to become healthy...
W1214 06:56:14.785669   18081 util.go:72] error while calling prometheus api: the server is currently unable to handle the request (get services http:prometheus-k8s:9090), response: k8s�

v1Status]

���Failure3no endpoints available for service "prometheus-k8s""ServiceUnavailable0��"�
W1214 06:56:44.822018   18081 util.go:72] error while calling prometheus api: the server is currently unable to handle the request (get services http:prometheus-k8s:9090), response: k8s�

v1Status]

Attempt 9 failed to list marker files for successful nodes
Listing marker files (gs://sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability/1735187630884130816/logexported-nodes-registry) for successful nodes...
CommandException: One or more URLs matched no objects.
Attempt 10 failed to list marker files for successful nodes
Final attempt to list marker files failed.. falling back to logdump through SSH
n


ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
External IP address was not found; defaulting to using IAP tunneling.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out

Recommendation: To check for possible causes of SSH connectivity issues and get
recommendations, rerun the ssh command with the --troubleshoot option.

gcloud compute ssh e2e-big-minion-group-3lkf --project=k8s-infra-e2e-boskos-scale-28 --zone=us-east1-b --troubleshoot

Or, to investigate an IAP tunneling issue:

gcloud compute ssh e2e-big-minion-group-3lkf --project=k8s-infra-e2e-boskos-scale-28 --zone=us-east1-b --troubleshoot --tunnel-through-iap

```

### Anything else we need to know?

link | | | result
-- |  -- | -- | --
[1735187630884130816](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1735187630884130816)  | Dec 14 14:41:44Dec 14 2023, 14:41:44 UTC+0800 | 2h11m55s | FAILURE
[1735173034244837376](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1735173034244837376)   | Dec 14 13:43:29Dec 14 2023, 13:43:29 UTC+0800 | 54m29s | SUCCESS

**Comment by pacoxu** [comment]
I check kube merged PR during that time: https://github.com/kubernetes/kubernetes/compare/ad1ea5d4560c56...e7e3eaf06568af. It seems to be not related.

**Comment by pacoxu** [comment]
`unable to handle the request (get services http:prometheus-k8s:9090)` makes me suspect it is related to dns.

**Comment by neolit123** [comment]
it could be DNS yes, but the scale tests have too many moving parts.
they are defined in https://github.com/kubernetes/perf-tests, which merges code even during code freeze.
https://github.com/kubernetes/perf-tests/commits/master/

i'd leave this to sig-scalability to triage.

/sig scalability

**Comment by wojtek-t** [comment]
This is the PR that broke us:
https://github.com/kubernetes/kubernetes/pull/122136

[Ironically approved by me...]

We're referencing this feature-gate in our scalability test configs:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-presets.yaml#L170

All scalability-related failures on master branch are failing due to that.

We need to remove that feature gate from master-branch tests but leave it in older branches.

@mborsz @tosi3k @jprzychodzen

**Comment by wojtek-t** [comment]
Opened https://github.com/kubernetes/test-infra/pull/31470 to fix it

**Comment by pacoxu** [comment]
/reopen 
as https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1736683568601501696 failed

I will watch the next runs to see if this is fixed.

**Comment by pacoxu** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1736920181550092288

> W1219 01:42:18.873560   18036 etcd_metrics.go:201] EtcdMetrics: call on 2382 port (curl http://localhost:2382/metrics) failed due to unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting SSH client to prow@35.243.182.107:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'"}. Falling back to default 2379 port.

> [measurement call TestMetrics - TestMetrics error: [action gather failed for EtcdMetrics measurement: unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting SSH client to prow@35.243.182.107:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'"}]]

The failure is now related to the etcd metrics.

**Comment by pacoxu** [comment]
failed log:

> 1219 01:41:13.984871   18036 ooms_tracker.go:174] ClusterOOMsTracker: starting cluster OOMs tracking measurement...
> I1219 01:41:28.699945   18036 util.go:93] Not enough active targets (0), expected at least (3), waiting for more to become active...
> I1219 01:41:28.913151   18036 util.go:93] Not enough active targets (0), expected at least (6), waiting for more to become active...
> I1219 01:41:43.707886   18036 util.go:93] Not enough active targets (0), expected at least (3), waiting for more to become active...
> I1219 01:41:43.899595   18036 util.go:93] Not enough active targets (0), expected at least (6), waiting for more to become active...
> I1219 01:41:58.709799   18036 util.go:93] Not enough active targets (0), expected at least (3), waiting for more to become active...
> I1219 01:41:58.895980   18036 util.go:93] Not enough active targets (0), expected at least (6), waiting for more to become active...
> I1219 01:42:13.709239   18036 util.go:93] Not enough active targets (0), expected at least (3), waiting for more to become active...
> I1219 01:42:13.890893   18036 util.go:93] Not enough active targets (0), expected at least (6), waiting for more to become active...
> error dialing prow@35.243.182.107:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain', retrying
> W1219 01:42:18.873560   18036 etcd_metrics.go:201] EtcdMetrics: call on 2382 port (curl http://localhost:2382/metrics) failed due to unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting SSH client to prow@35.243.182.107:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'"}. Falling back to default 2379 port.
> W1219 01:42:18.873591   18036 etcd_metrics.go:210] empty etcd cert or key, using http
> error dialing prow@35.243.182.107:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain', retrying
> E1219 01:42:24.381984   18036 etcd_metrics.go:147] EtcdMetrics: failed to collect etcd database size
> I1219 01:42:28.705907   18036 util.go:101] 1/3 targets are ready, example not ready target: {map[container:dns endpoint:metrics instance:10.64.75.4:8080 job:dns namespace:probes pod:dns-7dd54dbc8d-grd68 service:dns] unknown}
> I1219 01:42:28.900125   18036 util.go:101] 3/6 targets are ready, example not ready target: {map[container:ping-server endpoint:metrics instance:10.64.96.4:8080 job:ping-server namespace:probes pod:ping-server-77bbd84c7c-r7kqf service:ping-server] unknown}
> I1219 01:42:43.707596   18036 util.go:101] 2/3 targets are ready, example not ready target: {map[container:dns endpoint:metrics instance:10.64.75.4:8080 job:dns namespace:probes pod:dns-7dd54dbc8d-grd68 service:dns] unknown}
> I1219 01:42:43.902408   18036 util.go:101] 5/6 targets are ready, example not ready target: {map[container:ping-server endpoint:metrics instance:10.64.96.4:8080 job:ping-server namespace:probes pod:ping-server-77bbd84c7c-r7kqf service:ping-server] unknown}
> I1219 01:42:58.704728   18036 util.go:104] All 3 expected targets are ready

**Comment by aojea** [comment]
@wojtek-t I don't know if is related to this issue but this job https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance is failing because it can not ssh into nodes https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1737156242658299904

```
{ Failure :0
[measurement call TestMetrics - TestMetrics error: [action gather failed for EtcdMetrics measurement: unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting SSH client to prow@35.185.68.98:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'"}]]
:0}
```

**Comment by wojtek-t** [comment]
What I fixed was a different issue - this most probably regressed with the recent COS update.
@mborsz has a good understanding of this one - we're trying to find the best fix for it, but that is not a serious issue.

**Comment by upodroid** [comment]
We are merging a potential patch in k/perf-tests

https://github.com/kubernetes/perf-tests/pull/2486

@marseel

**Comment by pacoxu** [comment]
> kubernetes/perf-tests#2486

CI is green now after the merge.

Thanks @upodroid.
