### ISSUE TITLE
The error "No such container" is reported during the health check

### ISSUE THREAD

**Issue by bichengpeng** [kubernetes/kubernetes#122375]
### What happened?

During the health check, an error message is displayed, indicating that the container cannot be found.
The error information is as follows:
165949：I1130 13:10:54.337030 694061 prober.go：114] Readiness probe for "xxxxxx-probe-service-9d3eb26d-864d788bbd-m67zd_kube-system(65b90de7-0342-4101-8690-5ed8bbd91c00):xxxxxxx-service" errored：rpc error：code = Unknown desc = Error：No such container：8a17b9c6-fce5-471b-9a32-b8b4530328b3
165962：I1130 13:10:56.501912 694061 prober.go：114] Liveness probe for "xxxxxx-probe-service-9d3eb26d-864d788bbd-m67zd_kube-system(65b90de7-0342-4101-8690-5ed8bbd91c00):xxxxxxx-service" errored：rpc error：code = Unknown desc = Error：No such container：8a17b9c6-fce5-471b-9a32-b8b4530328b3
![Uploading k8s bug.png…]()

### What did you expect to happen?

I see another issure has this problem, but this issure is closed without explaining the reason.
Now I think someone can help me answer that question.

another issure link is  https://github.com/kubernetes/kubernetes/issues/85338

### How can we reproduce it (as minimally and precisely as possible)?

I don't know the conditions for reproduction. It's the first time I've seen it.

I have see another issure 

### Kubernetes version

<details>

k8s version is 1.19.4
docker version is 18.09.0
</details>

### Cloud provider

<details>
On my machine, kubelet, docker, canal, etc. restarted repeatedly, but this happened several times.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
/sig node
/triage needs-information

v1.19 is no longer supported. Can you test with a version that is still supported to see if the issue can be reproduced?
ref: https://kubernetes.io/releases/

**Comment by bichengpeng** [comment]
I don't know the conditions for reproducing this problem. It's the first time I've seen it. It may not be reproduced in a later version.

**Comment by bichengpeng** [comment]
> /sig node /triage needs-information
> 
> v1.19 is no longer supported. Can you test with a version that is still supported to see if the issue can be reproduced? ref: https://kubernetes.io/releases/

I don't know the conditions for reproducing this problem. It's the first time I've seen it. It may not be reproduced in a later version.

**Comment by HirazawaUi** [comment]
You might need post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes forum](https://discuss.kubernetes.io/). These are better places for support requests than GitHub.
/close
