### ISSUE TITLE
Pods Restarting on Node After a Period of Inactivity in Kubernetes 1.20.11 Cluster with Containerd

### ISSUE THREAD

**Issue by wolgod** [kubernetes/kubernetes#122349]
### What happened?

I am running a Kubernetes cluster with version 1.20.11 and Containerd as the runtime. I am currently experiencing an issue where if a node does not have any pods scheduled on it for a period of time, when a pod is eventually scheduled on that node, all pods on the node are restarted. I can see the restart count increment by 1 and events such as "kubelet stop the container" and "Pod sandbox changed, it will be killed and re-created" are logged.

I am currently unable to identify the cause of this issue. I initially suspected it might be network-related, but I have not been able to find any evidence to support this. 

Any help or suggestions on what might be causing this issue or how to troubleshoot it would be greatly appreciated. Thank you.

### What did you expect to happen?

all pod normal

### How can we reproduce it (as minimally and precisely as possible)?

where if a node does not have any pods scheduled on it for a period of time, when a pod is eventually scheduled on that node, all pods on the node are restarted.

### Kubernetes version

<details>

```console
$ kubectl version
# 1.20.11
```

</details>

### Cloud provider

<details>
  no
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux l82-2-p-ga 5.4.231-1.el7.elrepo.x86_64 #1 SMP Sat Feb 4 13:55:47 EST 2023 x86_64 x86_64 x86_64 GNU/Linux


</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.18
containerd://1.6.21
containerd://1.6.22
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
  ceph-csi
  kube-ovn 1.11.1
 kube-ovn 1.11.10
</details>

**Comment by HirazawaUi** [comment]
/remove-kind bug
/kind support
/sig node
/triage needs-information

v1.20 is no longer supported. Can you test with a version that is still supported to see if the issue can be reproduced?
ref: https://kubernetes.io/releases/
