### ISSUE TITLE
thanks for all the fish @mitchellh! aka `Archiving ~15 of my Go libs`

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#122399]
Tweet: https://x.com/mitchellh/status/1737226562519593207?s=20
Context: https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc

Search results:
https://cs.k8s.io/?q=mitchellh%5C%2F&i=nope&files=go.mod&excludeFiles=vendor%2F&repos=

What do we use?
```
$ cat log.txt  | rg "^[\d]+[\t\s]+github.com/mitchellh" | cut -f 2 | awk '{print $1}' | sort | uniq -c | sort
      1 github.com/mitchellh/colorstring
      1 github.com/mitchellh/hashstructure
      1 github.com/mitchellh/protoc-gen-go-json
      2 github.com/mitchellh/go-testing-interface
      3 github.com/mitchellh/go-ps
      3 github.com/mitchellh/hashstructure/v2
     22 github.com/mitchellh/reflectwalk
     23 github.com/mitchellh/copystructure
     26 github.com/mitchellh/go-wordwrap
     48 github.com/mitchellh/go-homedir
     71 github.com/mitchellh/mapstructure
```

/area code-organization

**Comment by dims** [comment]
Just k/k and k/test-infra:
https://cs.k8s.io/?q=mitchellh%5C%2F&i=nope&files=go.mod&excludeFiles=vendor%2F&repos=kubernetes/kubernetes,kubernetes/test-infra

```
github.com/mitchellh/go-wordwrap
github.com/mitchellh/go-homedir
github.com/mitchellh/mapstructure
```

**Comment by liggitt** [comment]
for reference, go-wordwrap is the only one k/k actually includes in its dependency graph for built binaries

**Comment by dims** [comment]
Added https://github.com/kubernetes/kubernetes/pull/122588 to make sure we don't expand usage of go-wordwrap.

closing this for now. other repositories can open their own issues as needed.

/close
