### ISSUE TITLE
Implement the integration tests for requeueing scenarios

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#122305]
/sig scheduling
/priority important-soon
/kind feature

Part of: https://github.com/kubernetes/kubernetes/issues/122284#issuecomment-1853346333.

We have few tests to check the scheduler's requeueing scenario in the integration test. 
We should have the one so that we can catch a bug like https://github.com/kubernetes/kubernetes/issues/122284, which only happens the scheduling queue is actually working.

---

Here's the list of plugins with QueueingHint.
Basically, I believe we can just pile up the test cases in the existing [TestCoreResourceEnqueue](https://github.com/kubernetes/kubernetes/blob/746f08a8da0a45e8b1a46362822db05cb11ed294/test/integration/scheduler/queue_test.go#L188).
Also, note that we have to cover major scenarios only, don't have to cover minor ones within the integration test.

**Please comment in this issue before starting to work on so that we can avoid many people from working on the same thing!**

- [x] InterPodAffinity @nayihz https://github.com/kubernetes/kubernetes/pull/127090
- [x] Dynamic resource allocation https://github.com/kubernetes/kubernetes/issues/122305#issuecomment-2336618368
- [x] NodeAffinity @tozastation https://github.com/kubernetes/kubernetes/pull/127139
- [x] NodePorts @saku3 https://github.com/kubernetes/kubernetes/pull/127130
- [x] NodeResourceFit @unvavo https://github.com/kubernetes/kubernetes/pull/127354
- [x] NodeUnschedulable @toshikish  https://github.com/kubernetes/kubernetes/pull/127406
- [ ] CSILimits @utam0k https://github.com/kubernetes/kubernetes/pull/127224
- [x] TopologySpread @saku3 https://github.com/kubernetes/kubernetes/pull/127399
- [x] TaintToleration @unvavo  https://github.com/kubernetes/kubernetes/pull/127923
- [ ] VolumeBinding @saku3  https://github.com/kubernetes/kubernetes/pull/127946
- [x] VolumeRestriction @utam0k https://github.com/kubernetes/kubernetes/pull/127892
- [x] VolumeZone @Gekko0114 https://github.com/kubernetes/kubernetes/pull/127353

**Comment by carlory** [comment]
> For example:
> ...

@sanposhiho There's already an existing intergation test. it follows similar steps.

https://github.com/carlory/kubernetes/blob/d36a7089cd9fa2abedd62f0964a42c21f837c53a/test/integration/scheduler/scheduler_test.go#L529

**Comment by sanposhiho** [comment]
We may want to refactor that then to be a more general one. 
What I want to make sure (eventually) is that **_all_** plugins take preCheck into consideration in EventsToRegisrter (+ QHint). That `TestNodeEvents` makes sure only noderesourcefit currently.

**Comment by sanposhiho** [comment]
As part of https://github.com/kubernetes/kubernetes/pull/122292, I implemented the e2e test, which would be a good starting point of this.

**Comment by sanposhiho** [comment]
/remove-lifecycle stale

https://github.com/kubernetes/kubernetes/pull/122292 is implemented, we have to cultivate the test cases there for existing QHints.

**Comment by sanposhiho** [comment]
/remove-lifecycle stale

Still important

**Comment by Gekko0114** [comment]
Hi @sanposhiho 

I can work it. Could you assign any item to me?

**Comment by sanposhiho** [comment]
Yes, name the ones you want.

**Comment by bells17** [comment]
Hi @sanposhiho
May I work on adding tests for VolumeBinding?

**Comment by Gekko0114** [comment]
Can you assign volumezone to me?

**Comment by tozastation** [comment]
Hi @sanposhiho 
Could you assign NodeAffinity to me ?

**Comment by saku3** [comment]
Hi @sanposhiho 
Could you assign NodePorts to me?

**Comment by nayihz** [comment]
I'll pick up the InterPodAffinity
/assign

**Comment by utam0k** [comment]
Hi, I'll give it a try!

**Comment by sanposhiho** [comment]
Oops,

/reopen

**Comment by mipplo** [comment]
Hi @sanposhiho
Has TaintToleration part finished yet？

**Comment by sanposhiho** [comment]
/assign @mipplo 

Not yet, assigned to you.

**Comment by unvavo** [comment]
Hi @satyampsoni 
Could you assign NodeResourceFit to me?

**Comment by satyampsoni** [comment]
Hey @unvavo I guess you mistakenly mentioned me!

**Comment by unvavo** [comment]
@satyampsoni 
I'm so sorry, I mistakenly menshioned you.

**Comment by unvavo** [comment]
@sanposhiho 
Could you assign NodeResourceFit to me?

**Comment by CodeDiego15** [comment]
Hi, good afternoon

**Comment by CodeDiego15** [comment]
how can I take the position of NodeUnschedulable?

**Comment by CodeDiego15** [comment]
@sanposhiho hi, Could you assign me NodeUnschedulable?

**Comment by saku3** [comment]
@sanposhiho hi, Could you assign me TopologySpread?

**Comment by sanposhiho** [comment]
@pohly Can we scope out DRA from this issue? meaning, do we already have some integration tests for requeueing for DRA?

**Comment by CodeDiego15** [comment]
@sanposhiho bro is the "first" time I participate, how can I be a member of kubernetes, I already did the CLA thing I think that's what it's called

**Comment by sanposhiho** [comment]
No, you don't have to be a member. The robot boy is complaining that this issue already has 10 assignees and we cannot assign more. So, just ignore him and proceed creating your PR.

**Comment by CodeDiego15** [comment]
@sanposhiho 
Okk, thank you very much. Thing, what is the file I have to modify? or the files, and excuse me.

**Comment by sanposhiho** [comment]
We're adding the test in -
https://github.com/kubernetes/kubernetes/blob/746f08a8da0a45e8b1a46362822db05cb11ed294/test/integration/scheduler/queue_test.go#L188
Also you can refer to other people's PR.

By the way, this is _not_ a beginner level issue, and is `important-soon` as we're aiming at the beta graduation this release cycle (= we have a clear deadline on this issue). In case you're not yet familiar with the scheduler, I'd recommend looking for other ones with [good first issue](https://github.com/kubernetes/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) or [help wanted](https://github.com/kubernetes/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label.

**Comment by CodeDiego15** [comment]
Okayy, What is the deadline?

**Comment by sanposhiho** [comment]
It's the beginning of Nov.

**Comment by CodeDiego15** [comment]
@sanposhiho Hey bro, I'm sorry it's very difficult, you're right, there are no other easier problems, I'll clarify it now so as not to waste time because I know how important it is.

**Comment by pohly** [comment]
> Can we scope out DRA from this issue? meaning, do we already have some integration tests for requeueing for DRA?

I am using `scheduler_perf` to write integration tests for DRA. It tends to be very good at finding unexpected race conditions or missing code (like the queuing hint for pod changes).

With unit tests and "traditional" integration tests one can verify that certain known corner cases get handled, i.e. one can write regression tests.

**Comment by sanposhiho** [comment]
Okay, then I'll just scope out DRA from this issue.

**Comment by utam0k** [comment]
Can I pick up `NodeResourceFits`?

**Comment by sanposhiho** [comment]
@utam0k NodeResourceFit is already assigned to @unvavo. The only remaining one is VolumeRestriction.

**Comment by utam0k** [comment]
I had missed it. Let me give that one a shot.

**Comment by toshikish** [comment]
@CodeDiego15 Are you already working on NodeUnschedulable?
I wrote test cases for it, so if you are not, may I send a PR instead?

**Comment by sanposhiho** [comment]
@toshikish You can take over. Assigned the one to you.

**Comment by sanposhiho** [comment]
/reopen

mistake

**Comment by sanposhiho** [comment]
/reopen

mistake again!!!! 😓

**Comment by sanposhiho** [comment]
@mipplo @bells17 @utam0k Friendly reminder for unsubmitted PRs.
We have 1 month left until the deadline though, let us know if you may not be able to make it so that someone can take over.

**Comment by sanposhiho** [comment]
@mipplo Are you still planning to work on it? I guess you deleted your comment from the thread here.

**Comment by utam0k** [comment]
> @mipplo @bells17 @utam0k Friendly reminder for unsubmitted PRs. We have 1 month left until the deadline though, let us know if you may not be able to make it so that someone can take over.

Sorry for the late. I'm working on mine.

**Comment by saku3** [comment]
@bells17 Are you still working on volumebinding? I can take it over if you're busy.

**Comment by sanposhiho** [comment]
@saku3 You can take it over. Since the volume binding is one of the biggest plugins, we should start asap.

**Comment by sanposhiho** [comment]
Also, is anyone here interested in taking over the taint toleration plugin?

**Comment by bells17** [comment]
@saku3 cc: @sanposhiho I'm sorry, but it seems I won't have much time available, so it would be very helpful if you could do it for me.

**Comment by unvavo** [comment]
@sanposhiho 
> Also, is anyone here interested in taking over the taint toleration plugin?

I am interested in that. Can I take it over?

**Comment by googs1025** [comment]
> > Can we scope out DRA from this issue? meaning, do we already have some integration tests for requeueing for DRA?
> 
> I am using `scheduler_perf` to write integration tests for DRA. It tends to be very good at finding unexpected race conditions or missing code (like the queuing hint for pod changes).
> 
> With unit tests and "traditional" integration tests one can verify that certain known corner cases get handled, i.e. one can write regression tests.

@sanposhiho @pohly 
I know Patrick is currently implementing dra related integration tests in scheduler_perf.
Do we still need integration tests for dra's re-enqueue scenario? 
I can take this if we still need to.

**Comment by pohly** [comment]
I don't think that such specific integration tests are needed for DRA, but I *do* think that having them won't hurt :smile: So yes, if you have time and want to help, then please do.

**Comment by sanposhiho** [comment]
@utam0k Do you need any help with two that you have?

**Comment by utam0k** [comment]
> @utam0k Do you need any help with two that you have?

VoulumeRestriction has been completed. And the other one is working on it. I'll send out my fix this week.
https://github.com/kubernetes/kubernetes/pull/127892

**Comment by sanposhiho** [comment]
Missed the volume restriction is done already! 
Perfect, thanks.

**Comment by sanposhiho** [comment]
@utam0k @saku3 Do you still think you'll be able to merge the PRs until the code freeze, tge end of this week?

**Comment by utam0k** [comment]
> @utam0k @saku3 Do you still think you'll be able to merge the PRs until the code freeze, tge end of this week?

I've almost done it, but I don't know how to do a few things. Can I get some advice? I'll push my code for now on the PR.
