### ISSUE TITLE
[CSI]DeleteVolumeRequest：A parameter may be added to transfer the PV name of the volume to be deleted

### ISSUE THREAD

**Issue by redriverhong** [kubernetes/kubernetes#122352]
### What would you like to be added?

The pvName parameter needs to be added to the DeleteVolumeRequest interface of the CSI module.
![image](https://github.com/kubernetes/kubernetes/assets/11647782/508137d8-21b6-412c-a7b9-fa2cc635714f)

### Why is this needed?

Currently, the DeleteVolumeRequest is only one parameter VolumeId, which is used to transfer the volume to be deleted. However, this requirement cannot be met in the scenario where PV volumes are preset.

![image](https://github.com/kubernetes/kubernetes/assets/11647782/a66ca47b-027a-4959-baad-67be9e811de9)

for example：
apiVersion: v1
kind: PersistentVolume
metadata:
annotations:
pv.kubernetes.io/provisioned-by: com.localcsi
pv.kubernetes.io/create-by: manual // Identifier Manually Preset
name: pv-test-0
spec:
capacity:
storage: 256Mi
accessModes:

ReadWriteOnce
claimRef:
apiVersion: v1
kind: PersistentVolumeClaim
name: data-test-0
namespace: default
persistentVolumeReclaimPolicy: Retain
volumeMode: Filesystem
storageClassName: local
csi:
driver: com.localcsi
fsType: ext4
volumeHandle: caasvg_lv // volumeId
nodeAffinity:
required:
nodeSelectorTerms:
matchExpressions:
key: kubernetes.io/hostname
operator: In
values:
master1
apiVersion: v1
kind: PersistentVolume
metadata:
annotations:
pv.kubernetes.io/provisioned-by: com.localcsi
pv.kubernetes.io/create-by: manual // Identifier Manually Preset
name: pv-test-1
spec:
capacity:
storage: 256Mi
accessModes:

ReadWriteOnce
claimRef:
apiVersion: v1
kind: PersistentVolumeClaim
name: data-test-1
namespace: default
persistentVolumeReclaimPolicy: Retain
volumeMode: Filesystem
storageClassName: local
csi:
driver: com.localcsi
fsType: ext4
volumeHandle: caasvg_lv // volumeId
nodeAffinity:
required:
nodeSelectorTerms:
matchExpressions:
key: kubernetes.io/hostname
operator: In
values:
master2
For the preceding two PVs, if I want to delete the first PV, only one volumeId is sent to me when I invoke the volume deletion interface. but the volumeId of the two PVs is the same and the volume of the node to be deleted cannot be identified.

So raised this issue to add a parameter pvName in DeleteVolumeRequest.

Describe the solution you'd like in detail
![image](https://github.com/kubernetes/kubernetes/assets/11647782/e87db777-7d04-4a85-958c-5f9ba32c7d15)

**Comment by carlory** [comment]
Can you explain why you need to define two PVs for the same volume? I can't understand the use case. In design, I think we should have only one PV for one volume. If you really need to define more than one PV for one volume, you can follow the steps below:

1. define a main PV for the volume, and its reclaim policy is `Delete`.
2. define other PVs for the volume, and their reclaim policy is `Retain`.

When you delete the main PV, the volume will be deleted. When you delete other PVs, the volume will be retained. Perhaps, you need to implement a webhook/controller to protect the volume from being deleted when there are other PVs for it. 

IMO, it's not common scenario in single cluster. If you still want to add a new field for `DeleteVolumeRequest`, the [container-storage-interface](https://github.com/container-storage-interface/spec) repo and csi channel on slack are the right place to discuss.

**Comment by redriverhong** [comment]
I have three nodes, node1, node2, and node3. 
During VM migration to containerization, there are the following scenarios:
In the virtualization scenario, three ServiceA instances are deployed. Each node has an LV whose name is lv_bigdata.
When the environment is upgraded to the containerized version, ensure that data is not lost. Deploy the ServiceA service pod. Three PV resources are preset. The volumehandle field in the PV resources is set to lv_bigdata.
However, the volume deletion interface shows that only one volume name is transferred when the volume is deleted. In this case, the node to which the volume belongs cannot be identified. If the PV name parameter is added, the node information of the PV can be obtained from the node affinity information of the PV.

**Comment by pranav-pandey0804** [comment]
@redriverhong @carlory's advocacy for adhering to Kubernetes' best practice of one-to-one mapping between PVs and physical volumes is foundational for clear and efficient volume lifecycle management. This principle ensures that the system remains manageable and predictable.

**Comment by pranav-pandey0804** [comment]
Conversely, @redriverhong's depiction of their migration journey from VMs to containerized services brings to light a unique challenge that may not be fully addressed by standard practices alone. The effort to preserve data integrity across such a transition is a poignant reminder of the intricate demands our evolving infrastructures face, and it subtly suggests the necessity for a degree of flexibility in certain specialized scenarios.

**Comment by pranav-pandey0804** [comment]
@redriverhong @carlory 
To bridge the gap between these perspectives, i think considering a custom controller or operator tailored for managing such complex volume mappings. 
This Kubernetes-native solution could encapsulate the requisite logic for handling edge cases like the one described, thereby integrating seamlessly with Kubernetes' existing mechanisms without undermining its design principles.

**Comment by pranav-pandey0804** [comment]
This approach offers a structured pathway to accommodate unique requirements without diluting the system's architectural integrity. It also encourages community collaboration, inviting further enhancements and adaptations to address similar challenges.

I'm keen to hear your thoughts on this proposed solution and any other ideas that might harmonize the principles of standardization with the practicalities of diverse operational contexts.

**Comment by pranav-pandey0804** [comment]
@redriverhong regarding the original issue,
The scenario you've outlined, where PV volumes are preset and share the same `VolumeId` but are distinguished by their `pvName`, highlights a critical gap in the current implementation that could lead to ambiguity and potential errors in volume management operations.

**Comment by pranav-pandey0804** [comment]
@redriverhong 
To build on your proposal, it might be beneficial to also consider how this change would interact with existing CSI drivers and the potential need for backward compatibility. 
Ensuring that existing drivers can handle or gracefully ignore the new parameter without disruption is crucial for smooth adoption.

**Comment by pranav-pandey0804** [comment]
@redriverhong 
Moreover, given the Kubernetes community's emphasis on API stability and versioning, 
it might be worth discussing how this change could be rolled out in a manner that minimizes disruption to current users. Perhaps introducing this as an optional field initially, with clear documentation on its usage and benefits, could facilitate a smoother transition.

I look forward to seeing further discussion on this proposal and am keen to contribute to the development and testing of this feature, should it move forward.

**Comment by redriverhong** [comment]
@carlory @pranav-pandey0804 
First of all, thank you very much for your responses and suggestions. 
The optional parameter PvName is added to the CSI request body, which reduces the impact and does not conflict with the overall design concept. I'm also looking forward to a better way to address this scenario.

**Comment by pranav-pandey0804** [comment]
Moving forward, it could be beneficial to engage with CSI driver maintainers and the Kubernetes storage SIG to ensure the change aligns with broader community needs. I'm here to help with testing, documentation, or community discussions as needed.

Excited to see how this enhancement evolves!
