### ISSUE TITLE
[Flaking test] [sig-apps] Deployment should not disrupt a cloud load-balancer's connectivity during rollout 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#122377]
### Which jobs are failing?

- [failing] ci-aws-kops-eks-pod-identity-sandbox
- [flaking] [gce-master-scale-correctness](https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness)

### Which tests are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-aws-kops-eks-pod-identity-sandbox/1736863130182488064

Kubernetes e2e suite: [It] [sig-apps] Deployment should not disrupt a cloud load-balancer's connectivity during rollout

### Since when has it been failing?

After this job is created https://github.com/kubernetes/test-infra/pull/31373 the job keeps failing.

After  Dec 16 02:06:53(Dec 16 2023, 02:06:53 UTC+0800),  https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-aws-kops-eks-pod-identity-sandbox/1735722980912140288 it started to fail with the only failure.

Before that, https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-aws-kops-eks-pod-identity-sandbox/1735714368596742144 failed to kubetest2: Up,

### Testgrid link
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness 
&
https://storage.googleapis.com/k8s-triage/index.html?job=ci-aws-kops-eks-pod-identity-sandbox

### Reason for failure (if possible)

```
{ failed [FAILED] timed out waiting for service "test-rolling-update-with-lb" to have a load balancer: context deadline exceeded
In [It] at: test/e2e/apps/deployment.go:1393 @ 12/18/23 22:07:24.394
}
```

### Relevant SIG(s)

/sig apps network

**Comment by pacoxu** [comment]
flake in https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness as well
/cc @upodroid

**Comment by ameukam** [comment]
Why are we tracking `ci-aws-kops-eks-pod-identity-sandbox` ?
This prowjob is not included in the CI signal and only target kops.

**Comment by aojea** [comment]
https://testgrid.k8s.io/sig-k8s-infra-canaries#ci-aws-kops-eks-pod-identity-sandbox

This test should not be running in this job, is a loadbalancer test, and AWS loadbalancers behave differently as they need annotations for some things

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness I saw a flake here.

And I search in all CI storage index， and find it failed more in that kops ci.

**Comment by aojea** [comment]
last failure are from one month ago, load balancer test at scale are not as reliable as the others, so having one failure per week can be considered ok

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness&include-filter-by-regex=Deployment%20should%20not%20disrupt%20a%20&show-stale-tests=

/close
