### ISSUE TITLE
The actual situation after the accessmode setting of my pvc is inconsistent with the documentation

### ISSUE THREAD

**Issue by AbelHugh** [kubernetes/kubernetes#122353]
### What happened?

The actual situation after the accessmode setting of my pvc is inconsistent with the documentation, https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

### What did you expect to happen?

consistent

### How can we reproduce it (as minimally and precisely as possible)?

As shown 

### Anything else we need to know?

As shown in the picture below, I increased the number of replicas to 4, and the pods were assigned to multiple nodes, but they were all mounted with the same pvc of access mode RWO.

![446173DD-BF78-470b-9342-A86E82124816](https://github.com/kubernetes/kubernetes/assets/71317399/38418880-6820-4c7b-92ac-aa86e68aed48)
![image](https://github.com/kubernetes/kubernetes/assets/71317399/279e2b89-d853-4e25-9ce0-3ca0f83f59ea)
![Dingtalk_20231216164657](https://github.com/kubernetes/kubernetes/assets/71317399/ca9d6695-e20b-47b8-af3f-6937084f1f34)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:08:36Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.21
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
k8s-sigs.io/nfs-subdir-external-provisioner
</details>

**Comment by kerthcet** [comment]
/sig scheduling

Also related to sig scheduling, defer to sig storage for advices.

**Comment by ningziwen** [comment]
I think we can add the check as part of Prefilter() [step](https://github.com/kubernetes/kubernetes/blob/735804dc812ce647f8c130dced45b5ba4079b76e/pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go#L162) in volume_restrictions. 

I could try to make this change if it sounds good.

**Comment by pranav-pandey0804** [comment]
hi @AbelHugh 
The Kubernetes [documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) confirms that a `PVC` with `ReadWriteOnce` access mode can be mounted as `read-write` by a single node, and it's implied that this could allow multiple `pods` on the same `node` to access the `volume`.

**Comment by pranav-pandey0804** [comment]
@AbelHugh 
The confusion may stem from interpreting "a single node" in the RWO access mode as limiting access to only one `pod`. In reality, RWO restricts `volume` mounting to a single `node`, but doesn't inherently limit the number of `pods` on that `node` that can access the `volume`.

**Comment by pranav-pandey0804** [comment]
@AbelHugh upon reading the documentation again, 
i think that the issue you've encountered where multiple `pods` on different nodes can mount a `PVC` with RWO access mode contradicts Kubernetes [documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/). 
This could indicate a potential oversight in the scheduler's enforcement of `PVC` access policies or a documentation update might be needed to reflect actual behavior. 
It's crucial to investigate this further to ensure consistency and reliability in resource allocation and access control within Kubernetes clusters.

**Comment by pranav-pandey0804** [comment]
> I think we can add the check as part of Prefilter() [step](https://github.com/kubernetes/kubernetes/blob/735804dc812ce647f8c130dced45b5ba4079b76e/pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go#L162) in volume_restrictions.

@ningziwen Your suggestion to integrate a check within the `Prefilter()` step of `volume_restrictions` is insightful. Enhancing this validation could significantly improve the scheduler's ability to adhere to `PVC` access mode constraints, addressing the issue at hand effectively. If you proceed with this change, it could provide a robust solution to prevent similar scheduling discrepancies in the future.

**Comment by pranav-pandey0804** [comment]
@ningziwen 
This approach aligns with the function's role in evaluating `pods` against `volume` constraints before scheduling. 
It could provide a robust mechanism to ensure that pods respect `PVC` access mode constraints, especially in complex scheduling scenarios. This addition might involve validating `PVCs` against their declared access modes, enhancing the scheduler's capability to prevent potential misconfiguration. 
It would be beneficial to see this idea explored further in the Kubernetes community !
