### ISSUE TITLE
new API to control kubelet

### ISSUE THREAD

**Issue by PilotPaul** [kubernetes/kubernetes#122430]
I encountered a problem using k8s and need to check the vm machine's environment. Under normal circumstance, I need to build an Agent server to receive my requests to do executing or query operations, but I don't want to develop an additional Agent, kubelet can serve as Agent, right? So,
does k8s's development team have plan to expand such a kube-apiserver API? Through this API, all kubelets managed by it can be ordered to execute scripts or binary programs prepared by users in a certain vm's path in advance, somewhat similar CSI flexvolume.

Looking forward your reply.

/sig Architecture
/sig CLI
/sig K8s Infra
/sig Node

**Comment by neolit123** [comment]
> Through this API, all kubelets managed by it can be ordered to execute scripts or binary programs prepared by users

such an API already exists and that's the Job:
https://stackoverflow.com/questions/41674108/how-to-include-script-and-run-it-into-kubernetes-yaml

> So, does k8s's development team have plan to expand such a kube-apiserver API?

probably not, but let's see what kubelet maintainers think.

/kind feature
/sig node

**Comment by PilotPaul** [comment]
> > Through this API, all kubelets managed by it can be ordered to execute scripts or binary programs prepared by users
> 
> 
> 
> such an API already exists and that's the Job API:
> 
> https://stackoverflow.com/questions/41674108/how-to-include-script-and-run-it-into-kubernetes-yaml
> 
> 
> 
> > So, does k8s's development team have plan to expand such a kube-apiserver API?
> 
> 
> 
> probably not, but let's see what kubelet maintainers think.
> 
> 
> 
> /kind feature
> 
> /sig node
> 
> 
> 
> 

Yep, I've already browse the link you've provided. However what I need is kublet can be ordered to execute scripts on virtual machine rather than in pod/container. Can the job api accomplish this task?

**Comment by charles-chenzz** [comment]
execute scripts on vm seems not like the responsibility that kubelet should take. because kubelet was design to be the agent/manager of  node/pod/container

**Comment by sftim** [comment]
This might be an _extension_ to Kubernetes. For example, the [Cluster API](https://cluster-api.sigs.k8s.io/) could add a NodeManagementJob API (it might not, but that's a _feasible_ approach at least).

**Comment by tallclair** [comment]
Why can't the script be executed in a container? There are lots of container security settings that can be relaxed if higher privileges are needed. In particular, look at:

- privileged
- HostPID
- HostIPC
- HostPath (volume)
- HostNetwork

Some combination of these should be close enough for most use cases. We would need a lot more justification to consider adding this feature.

/triage needs-information

**Comment by thockin** [comment]
There's an exceptionally good tool for this, and it happens to be industry-standard - ssh.
