### ISSUE TITLE
kubelet start hang forever at cadvisor.New while there are nfs volume mountpoints with unresponsive nfs server

### ISSUE THREAD

**Issue by 249043822** [kubernetes/kubernetes#122491]
### What happened?

![222](https://github.com/kubernetes/kubernetes/assets/18046309/38e709ff-b386-4fd9-b8ad-621cfd752a0d)
![333](https://github.com/kubernetes/kubernetes/assets/18046309/d39bf7a6-008d-4427-a15d-c12bb2fe1abe)
![111](https://github.com/kubernetes/kubernetes/assets/18046309/1059482b-1804-406e-9f48-36183ebadc19)

### What did you expect to happen?

kubelet can startup complete
or cadvisor should skip pod volume mountpoints while getGlobalFsInfo
### How can we reproduce it (as minimally and precisely as possible)?

1. create a nfs-server pod
2. create a pod using nfs pv
3. delete the nfs-server pod
4. restart kubelet on the node which the pod at step 2 running

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/blob/f55d18a1cf6cd9b49740819cc08479bd0d362c7b/vendor/github.com/google/cadvisor/fs/fs.go#L433-L435

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by zhifei92** [comment]
There seems to be no issue, and identifying a hung file system early can only be beneficial。In the event of a similar issue, should not restart kubelet; instead, the focus should be on resolving the storage problem

**Comment by SergeyKanzhelev** [comment]
nfs stale mounts are known issue for more than just kubelet. +1 to what @zhifei92 suggests

/kind documentation
/remove-kind bug

Maybe it is a good idea to document this.

**Comment by lojies** [comment]
> nfs stale mounts are known issue for more than just kubelet. +1 to what @zhifei92 suggests
> 
> /kind documentation /remove-kind bug
> 
> Maybe it is a good idea to document this.

I think a robust system should not rely on external systems; it can report errors but must not get stuck.
Now  kubelet may experience exceptions at various stages such as startup, pleg, and volume mounting due to issues with nfs.

**Comment by sreenandan** [comment]
With k8s 1.30, we are also seeing the exact same issue where kubelet is getting stuck, stack trace shows 
cadvisor/fs.getVfsStats making the system call Statfs

goroutine 1 gp=0xc0000061c0 m=7 mp=0xc000600008 [syscall]:
syscall.Syscall(0x89, 0xc00074c360, 0xc000a238a0, 0x0)
        syscall/syscall_linux.go:69 +0x25 fp=0xc000a23838 sp=0xc000a237d8 pc=0x494665
syscall.Statfs({0xc000b62010?, 0xc000a238c0?}, 0xc000a238a0)
        syscall/zsyscall_linux_amd64.go:1376 +0x78 fp=0xc000a23888 sp=0xc000a23838 pc=0x493698
github.com/google/cadvisor/fs.getVfsStats({0xc000b62010?, 0x5?})
        github.com/google/cadvisor@v0.49.0/fs/fs.go:720 +0x5d fp=0xc000a23928 sp=0xc000a23888 pc=0x1c65a3d
github.com/google/cadvisor/fs.(*RealFsInfo).GetFsInfoForPath(0xc000b47b30, 0x0)
        github.com/google/cadvisor@v0.49.0/fs/fs.go:446 +0x76f fp=0xc000a23fe8 sp=0xc000a23928 pc=0x1c6356f
github.com/google/cadvisor/fs.(*RealFsInfo).GetGlobalFsInfo(0x45124e8?)
        github.com/google/cadvisor@v0.49.0/fs/fs.go:573 +0x15 fp=0xc000a24008 sp=0xc000a23fe8 pc=0x1c64795
github.com/google/cadvisor/machine.Info({0x45124e8, 0xc000750920}, {0x44fc2b8, 0xc000b47b30}, 0x0?)
        github.com/google/cadvisor@v0.49.0/machine/info.go:97 +0x1a6 fp=0xc000a24368 sp=0xc000a24008 pc=0x213e766
github.com/google/cadvisor/manager.New(0xc0007767c0, {0x45124e8, 0xc000750920}, {0xc000a24580?, 0xc000752408?}, 0xc00073ce70, 0x638dde0, {0xc000750820, 0x1, 0x1}, ...)
        github.com/google/cadvisor@v0.49.0/manager/manager.go:212 +0x585 fp=0xc000a244e8 sp=0xc000a24368 pc=0x2152725
k8s.io/kubernetes/pkg/kubelet/cadvisor.New({0x44c7518, 0xc000750910}, {0x3f25e13, 0x10}, {0xc000750820, 0x1, 0x1}, 0x0, 0x1)
        k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:105 +0x2dc fp=0xc000a245f0 sp=0xc000a244e8 pc=0x215ed7c
k8s.io/kubernetes/cmd/kubelet/app.run({0x44ecb08, 0xc0004abcc0}, 0xc0002b4008, 0xc00084ad00, {0x7f3a00be70d8, 0xc00071c0a0})
        k8s.io/kubernetes/cmd/kubelet/app/server.go:731 +0x10c7 fp=0xc000a25938 sp=0xc000a245f0 pc=0x31f8787
k8s.io/kubernetes/cmd/kubelet/app.Run({0x44ecb08, 0xc0004abcc0}, 0xc0002b4008, 0xc00084ad00, {0x7f3a00be70d8, 0xc00071c0a0})
        k8s.io/kubernetes/cmd/kubelet/app/server.go:491 +0x333 fp=0xc000a25ab8 sp=0xc000a25938 pc=0x31f6bf3
k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc0003ccf08, {0xc000052080, 0x6, 0x6})
        k8s.io/kubernetes/cmd/kubelet/app/server.go:282 +0xbc9 fp=0xc000a25c58 sp=0xc000a25ab8 pc=0x31f5689
github.com/spf13/cobra.(*Command).execute(0xc0003ccf08, {0xc000052080, 0x6, 0x6})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x882 fp=0xc000a25d78 sp=0xc000a25c58 pc=0x5df402
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003ccf08)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5 fp=0xc000a25e30 sp=0xc000a25d78 pc=0x5dfc45
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
k8s.io/component-base/cli.run(0xc0003ccf08)
        k8s.io/component-base/cli/run.go:146 +0x290 fp=0xc000a25eb8 sp=0xc000a25e30 pc=0xb48d50
k8s.io/component-base/cli.Run(0xc0000061c0?)
        k8s.io/component-base/cli/run.go:46 +0x17 fp=0xc000a25f38 sp=0xc000a25eb8 pc=0xb489f7
main.main()
        k8s.io/kubernetes/cmd/kubelet/kubelet.go:36 +0x18 fp=0xc000a25f50 sp=0xc000a25f38 pc=0x31fe4b8
runtime.main()
        runtime/proc.go:271 +0x29d fp=0xc000a25fe0 sp=0xc000a25f50 pc=0x44313d
runtime.goexit({})
        runtime/asm_amd64.s:1695 +0x1 fp=0xc000a25fe8 sp=0xc000a25fe0 pc=0x47b4a1

**Comment by sreenandan** [comment]
@249043822 when you opened this issue on Dec 23, the fix of using statx instead of stat was not merged to main branch.
k8s 1.30 released on Apr 17 has statx fix. 
With k8s 1.30, kubelet gets stuck only a restart when there is a hung nfs mount as per your repro steps.
In any case, this needs a fix.
