### ISSUE TITLE
Deprecated -t so that we can make it --tty

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#12248]
In the docker cli `-t` is used for shorthand for `--tty`, right now `-t` in kubectl is shorthand for `--template`

We should deprecated the shorthand (and possibly the entire `--template` flag) and repurpose `-t` for `--tty`

**Comment by brendandburns** [comment]
Also remove from examples.

**Comment by bgrant0607** [comment]
Forked from #12220

**Comment by thockin** [comment]
I've been meaning to ask for -o template="template string" or
template:"template string" rather than -t, so +1

**Comment by bgrant0607** [comment]
Well, #12220 changes --template to --golang-template (to make room for --jsonpath-template), which isn't what you want.

**Comment by thockin** [comment]
Yeah, I think we should not be doing coupled pairs of flags - I think it's
better to parse single flags, if we can make it work.

**Comment by bgrant0607** [comment]
cc @smarterclayton had an opinion about this

**Comment by smarterclayton** [comment]
Suggest -T, and also that we create a "reservation system" for new short
flags before we use them all.

On Aug 14, 2015, at 1:28 PM, Brian Grant <notifications@github.com> wrote:

cc @smarterclayton <https://github.com/smarterclayton> had an opinion about
this

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12248#issuecomment-131188275>
.

**Comment by thockin** [comment]
If we are breaking compat, I really want to argue for just saying -o
template="template string" rather than pairs of flags (-o and -t) that need
to coordinate.

If we support that, no need for -t or -T

**Comment by smarterclayton** [comment]
-t is (was) common enough that it was intended to be easy to use.  The
primary use is scripting so making things harder for users is less
impactful.  The goal is to reduce the friction on common actions, but with
-L and the column spec -o, -t is less important now.

On Aug 15, 2015, at 10:29 PM, Tim Hockin <notifications@github.com> wrote:

If we are breaking compat, I really want to argue for just saying -o
template="template string" rather than pairs of flags (-o and -t) that need
to coordinate.

If we support that, no need for -t or -T
On Aug 14, 2015 4:18 PM, "Clayton Coleman" <notifications@github.com> wrote:

> Suggest -T, and also that we create a "reservation system" for new short
> flags before we use them all.
>
> On Aug 14, 2015, at 1:28 PM, Brian Grant <notifications@github.com> wrote:
>
> cc @smarterclayton <https://github.com/smarterclayton> had an opinion
> about
> this
>
> —
> Reply to this email directly or view it on GitHub
> <
>
https://github.com/kubernetes/kubernetes/issues/12248#issuecomment-131188275
> >
> .
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/issues/12248#issuecomment-131265857
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12248#issuecomment-131477321>
.

**Comment by thockin** [comment]
I think output templates are still important, I just don't think it should
be twin flags when one flag + parsing works just as well.

**Comment by smarterclayton** [comment]
Having to parse flags like that is somewhat unusual.  I guess it's no worse
than flag explosion (clutters help), but may inhibit discovery.

On Aug 16, 2015, at 12:49 PM, Tim Hockin <notifications@github.com> wrote:

I think output templates are still important, I just don't think it should
be twin flags when one flag + parsing works just as well.
On Aug 16, 2015 8:49 AM, "Clayton Coleman" <notifications@github.com> wrote:

> -t is (was) common enough that it was intended to be easy to use. The
> primary use is scripting so making things harder for users is less
> impactful. The goal is to reduce the friction on common actions, but with
> -L and the column spec -o, -t is less important now.
>
> On Aug 15, 2015, at 10:29 PM, Tim Hockin <notifications@github.com> wrote:
>
> If we are breaking compat, I really want to argue for just saying -o
> template="template string" rather than pairs of flags (-o and -t) that
need
> to coordinate.
>
> If we support that, no need for -t or -T
> On Aug 14, 2015 4:18 PM, "Clayton Coleman" <notifications@github.com>
> wrote:
>
> > Suggest -T, and also that we create a "reservation system" for new short
> > flags before we use them all.
> >
> > On Aug 14, 2015, at 1:28 PM, Brian Grant <notifications@github.com>
> wrote:
> >
> > cc @smarterclayton <https://github.com/smarterclayton> had an opinion
> > about
> > this
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> >
>
>
https://github.com/kubernetes/kubernetes/issues/12248#issuecomment-131188275
> > >
> > .
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
>
>
https://github.com/kubernetes/kubernetes/issues/12248#issuecomment-131265857
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <
>
https://github.com/kubernetes/kubernetes/issues/12248#issuecomment-131477321
> >
> .
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/issues/12248#issuecomment-131576156
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12248#issuecomment-131580862>
.
