### ISSUE TITLE
Topology Aware Routing: Unable to allocate minimum required endpoints to each zone without exceeding overload threshold 

### ISSUE THREAD

**Issue by a7i** [kubernetes/kubernetes#122437]
### What happened?

Given that we have 3 availability zones and even spread of nodes/CPU across all of those topology domains, we end up with a cpu ratio of `[0.333, 0.333, 0.333]`

Given that the workload has `HorizontalPodAutoscaler`, it can scale up and down with random assignment to zones but never with a skew of more than 1.

The workload had a spread of `[4, 4, 3]` across topology domains (a total of 11 `Pods` / `EndPoints`). This leads to an error of `Unable to allocate minimum required endpoints to each zone without exceeding overload threshold (11 endpoints, 3 zones)`

Given the [code logic here](https://github.com/kubernetes/kubernetes/blob/755b4e2bc493518f916e1b1ba11652a44b9fdc58/staging/src/k8s.io/endpointslice/topologycache/topologycache.go#L315C46-L331):
- `cpuRatiosByZone` of `[0.333, 0.333, 0.333]`
- `numEndpoints` of 11
- => `remainingMinEndpoints` ends up being `-1`
- => removes hints

![image](https://github.com/kubernetes/kubernetes/assets/9448877/f10b8d01-44c6-4b14-b145-f706df94dc3b)

### What did you expect to happen?

Spread of `[4, 4, 3]` is capable of handling same zone traffic so I would expect the hints to not be removed.

### How can we reproduce it (as minimally and precisely as possible)?

- Set up nodes across 3 zones
- Setup a Deployment or StatefulSet with 9 replicas evenly spread across zones (can use `topologySpreadConstraints` of `DoNotSchedule` with `topology.kubernetes.io/zone` key and `maxSkew` of 1)
- Observe a spread of `[3, 3, 3]` across zones
- Observe that hints are created
- Scale to 11 replicas to force a spread of `[4, 4, 3]`
- Observe that hints are removed

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.27.6
```

</details>

### Cloud provider

<details>
aws
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by robscott** [comment]
This is a very unfortunate aspect of the current topology aware hints heuristic. In a cluster with 3 equivalent zones, [hints will not be allocated when a Service has 4, 5, 8, or 11 endpoints](https://docs.google.com/spreadsheets/d/1_4QyfQEcnEWYpcmUc1Q6cjgkLMhMqpTgok2UUpOmUhE/edit?resourcekey=0-k7XjENYqtAyBfm12lDq0KQ#gid=0). Of course zones are not always equivalent, and there are not always 3 zones in a cluster, so there will be many exceptions to this.

@gauravkghildiyal is working on a new heuristic for Topology Aware Hints that would keep all traffic in zone if _any_ healthy endpoints were present (https://github.com/kubernetes/kubernetes/pull/121060). That approach has its own limitations, but is likely preferable in many cases, it all depends on risk tolerance. 

Unfortunately I think this is actually the heuristic working as intended, so I don't think there's a lot we can change here. The overarching idea with the existing heuristic was to have something that kept traffic in the same zone whenever it was reasonably safe, and the overload threshold was a rather rudimentary way to achieve that.

**Comment by a7i** [comment]
That makes sense @robscott , thank you for your detailed response.
