### ISSUE TITLE
unexpected error getting claim reference: selfLink was empty, can't make reference

### ISSUE THREAD

**Issue by tutengdihuang** [kubernetes/kubernetes#122466]
### What happened?

E1224 11:17:00.799148       1 controller.go:1004] provision "default/test-claim" class "nfs-client": unexpected error getting claim reference: selfLink was empty, can't make reference
E1224 11:17:00.799174       1 controller.go:1004] provision "ems/data-mysql-0" class "mysql-nfs-sc": unexpected error getting claim reference: selfLink was empty, can't make reference

### What did you expect to happen?

# kubectl logs -f nfs-client-provisioner-df694fc99-sjbdn -n kube-system
I1224 11:16:43.293732       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/fuseim.pri-ifs...
E1224 11:17:00.695109       1 event.go:259] Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"fuseim.pri-ifs", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"f60746e4-76ec-44f4-89d6-ec395d57a884", ResourceVersion:"390611", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63839005128, loc:(*time.Location)(0x1956800)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"nfs-client-provisioner-df694fc99-sjbdn_eaf160b8-a24d-11ee-8106-be1984dda519\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2023-12-24T11:17:00Z\",\"renewTime\":\"2023-12-24T11:17:00Z\",\"leaderTransitions\":10}"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'nfs-client-provisioner-df694fc99-sjbdn_eaf160b8-a24d-11ee-8106-be1984dda519 became leader'
I1224 11:17:00.695240       1 leaderelection.go:194] successfully acquired lease kube-system/fuseim.pri-ifs
I1224 11:17:00.695307       1 controller.go:631] Starting provisioner controller fuseim.pri/ifs_nfs-client-provisioner-df694fc99-sjbdn_eaf160b8-a24d-11ee-8106-be1984dda519!
I1224 11:17:00.795665       1 controller.go:680] Started provisioner controller fuseim.pri/ifs_nfs-client-provisioner-df694fc99-sjbdn_eaf160b8-a24d-11ee-8106-be1984dda519!
I1224 11:17:00.795791       1 controller.go:987] provision "ems/data-mysql-0" class "mysql-nfs-sc": started
I1224 11:17:00.795846       1 controller.go:987] provision "default/test-claim" class "nfs-client": started
E1224 11:17:00.799148       1 controller.go:1004] provision "default/test-claim" class "nfs-client": unexpected error getting claim reference: selfLink was empty, can't make reference
E1224 11:17:00.799174       1 controller.go:1004] provision "ems/data-mysql-0" class "mysql-nfs-sc": unexpected error getting claim reference: selfLink was empty, can't make reference

### How can we reproduce it (as minimally and precisely as possible)?

version: 1.28.2

### Anything else we need to know?

1. I have add       - --feature-gates=RemoveSelfLink=false to kube-apiserver.yaml and restart the kubelet in all of the node
2. but no works

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
v1.28.2

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
centos 7.9

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tutengdihuang** [comment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 10.0.3.231
            - name: NFS_PATH
              value: /root/nfs/data
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.0.3.231
            path: /root/nfs/data

**Comment by tutengdihuang** [comment]
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: fuseim.pri/ifs # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"

**Comment by tutengdihuang** [comment]
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-client-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
    # replace with namespace where provisioner is deployed
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
    # replace with namespace where provisioner is deployed
    namespace: kube-system
roleRef:
  kind: Role
  name: leader-locking-nfs-client-provisioner
  apiGroup: rbac.authorization.k8s.io

**Comment by tutengdihuang** [comment]
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Mi

**Comment by tutengdihuang** [comment]
```
[root@k8s-node1 第四章控制器controller]# kubectl get pvc -A
NAMESPACE   NAME                     STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
default     data-my-release-etcd-0   Pending                                                     108m
default     test-claim               Pending                                      nfs-client     14m
ems         data-mysql-0             Pending                                      mysql-nfs-sc   22m
[root@k8s-node1 第四章控制器controller]# 
```

**Comment by tutengdihuang** [comment]
```
# kubectl get pvc -A
NAMESPACE   NAME                     STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
default     data-my-release-etcd-0   Pending                                                     108m
default     test-claim               Pending                                      nfs-client     14m
ems         data-mysql-0             Pending                                      mysql-nfs-sc   22m
```

**Comment by carlory** [comment]
/remove-kind bug
/kind document

RemoveSelfLink was GA in 1.24 but the flag was forgot to be removed.

https://github.com/kubernetes/enhancements/issues/1164

**Comment by carlory** [comment]
doc was updated by https://github.com/kubernetes/website/pull/44509, if you have any question, feel free to reopen
/close
