### ISSUE TITLE
[Discussion]`InPlacePodVerticalScaling` may lead to assumed pod with rotten state

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#122406]
### What happened?

With `InPlacePodVerticalScaling` enabled, an assumed pod might be scaled down with its resources, however, we'll return directly here
https://github.com/kubernetes/kubernetes/blob/4111bef430515f6e76213c4be84c0dd1e9722e20/pkg/scheduler/eventhandlers.go#L145-L147

This may lead to the pod cache with rotten state, and moreover, some unschedulable pods which failed by nodeResourceFit might be re-schedulable but now it's unworkable.

However, I think **the intermediate state is acceptable**, it's short and after pod is binded, we'll receive a new pod updated event which will **refresh the cache**, also re-trigger the rescheduling processes, finally **reach the eventual consistence**.

Then what we should do here is  adding more explanations.

/sig scheduling
/assign

### What did you expect to happen?

None

### How can we reproduce it (as minimally and precisely as possible)?

None

### Kubernetes version

None

### Cloud provider

None

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/cc @carlory 
[KEP-1287](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources) focus on allowing a running pod resource change to trigger a restart or not. 
- For pending pod without nodeName (during scheduling stage), the KEP doesn't cover. 

I would +1 to decline a resource update  of pending pod, and fix it as a bug. This will reduce complexity of this feature.

**Comment by carlory** [comment]
> However, I think the intermediate state is acceptable, it's short and after pod is binded, we'll receive a new pod updated event which will refresh the cache, also re-trigger the rescheduling processes, finally reach the eventual consistence.

According to current implementation of the QueueingHintFn in the NodeResourceFit plugin, it will ingore 2 update events and not put previous unschedulable pod into the backoff  queue. So the pod has to wait for the next rescheduling process to be scheduled.

There are 2 ways to solve this problem:

1. the NodeResourceFit plugin also holds a reference to the assume cache. QueueingHintFn checks whether the pod is in the assume cache when it receives an update event and the pod's nodeName is empty. 
2. QueueingHintFn doesn't do fine-grained control. It just checks whether the pod from the update event reduces resource requests whatever the pod is scheduled, assumed or not. It's easy to implement. But it may cause unnecessary rescheduling processes.

**Comment by carlory** [comment]
cc @sanposhiho

**Comment by carlory** [comment]
If a pod is being assumed, the hintFn won't observe update event because the event is filtered by the [updatePodInSchedulingQueue](https://github.com/kubernetes/kubernetes/blob/42ab3b7b40c34e91b63589ae905ed918752a4a36/pkg/scheduler/eventhandlers.go#L132). so we don't consider this [scenario](https://github.com/kubernetes/kubernetes/pull/122360#discussion_r1431547953)

@alculquicondor @kerthcet

**Comment by sanposhiho** [comment]
As @carlory said, assumed Pods' updates are ignored in [updatePodInSchedulingQueue](https://github.com/kubernetes/kubernetes/blob/42ab3b7b40c34e91b63589ae905ed918752a4a36/pkg/scheduler/eventhandlers.go#L132).

And eventually when Pod is bound to some Node, `addPodToCache` is called.
https://github.com/kubernetes/kubernetes/blob/42ab3b7b40c34e91b63589ae905ed918752a4a36/pkg/scheduler/eventhandlers.go#L190-L205

Then, what if this scenario happens?↓

1. Pod is assumed to Node-A.
2. Pod is scaled down before Pod is bound to Node-A. updatePodInSchedulingQueue ignores this event.
3. Pod is bound to Node-A. (addPodToCache)

(2) actually makes a free space, but the scheduler ignores it, doesn't it? Could this scenario happen? Is this something prohibited by the in-place Pod resizing feature?

**Comment by ningziwen** [comment]
> /cc @carlory @vinaykul @thockin [KEP-1287](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources) focus on allowing a running pod resource change to trigger a restart or not.
> 
> * For pending pod without nodeName (during scheduling stage), the KEP doesn't cover.
> 
> I would +1 to decline a resource update of pending pod, and fix it as a bug. This will reduce complexity of this feature.
> 
> BTW, if a pod is not running yet, recreating it with an new resource limit/request is a very low cost operation, the aim of In-Place Update of pod resource to solve running pod resource optimization. We'd better not support pod resource update before scheduled until we have a clear scanerio.

+1. Resizing in assumed pods does not provide much value to users, and the feature is still in alpha state so we should be good to make the change. 

I could help the change when it reaches alignment.

**Comment by alculquicondor** [comment]
Let's not add unnecessary complexity to in-place updates.

/close
