### ISSUE TITLE
Kubernetes conflicts with AppLocker on Windows PCs

### ISSUE THREAD

**Issue by maottsen** [kubernetes/kubernetes#122417]
Dear Kubernetes Team,
We have a considerable number of users who utilize your software tools such as kube forwarder, k9s, kubectl etc. for a variety of tasks, a number that is consistently growing.
However, we are encountering recurring issues due to conflicts between your software and our security solutions, notably AppLocker, Microsoft's application control feature. 
This primarily stems from the fact that you have opted not to sign your software or situate it within program files. As a result, we are compelled to authorize the software based on its filehash, but this obviously changed at each software update.
This situation is not only causing administrative difficulties for us (Without a doubt other customer as well), but it is also proving problematic for the developers who use your software tools.
I hope you will consider this, as it will make your software way more enterprise friendly.
BR

**Comment by maottsen** [comment]
> triage/accepted

triage/accepted

**Comment by sftim** [comment]
/kind feature
/sig windows release
/retitle Kubernetes conflicts with AppLocker on Windows PCs

**Comment by Najzer0** [comment]
> Dear Kubernetes Team, We have a considerable number of users who utilize your software tools such as kube forwarder, k9s, kubectl etc. for a variety of tasks, a number that is consistently growing. However, we are encountering recurring issues due to conflicts between your software and our security solutions, notably AppLocker, Microsoft's application control feature. This primarily stems from the fact that you have opted not to sign your software or situate it within program files. As a result, we are compelled to authorize the software based on its filehash, but this obviously changed at each software update. This situation is not only causing administrative difficulties for us (Without a doubt other customer as well), but it is also proving problematic for the developers who use your software tools. I hope you will consider this, as it will make your software way more enterprise friendly. BR

As this got auto-closed, care to tell how you whitelisted windows workloads with the hashes in applocker... having the same issue and need to automate whitelisting
