### ISSUE TITLE
etcd

### ISSUE THREAD

**Issue by tommyzhao830** [kubernetes/kubernetes#122482]
### What happened?

etcd exceeds 8G, the cluster is unavailable, is there a way to increase this limit.

### What did you expect to happen?

I hope there can be a solution that can increase the capacity of etcd

### How can we reproduce it (as minimally and precisely as possible)?

You can try filling up the etcd store to reproduce the problem.

### Kubernetes version

v1.24

### Cloud provider

ucloud

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liangyuanpeng** [comment]
I believe that this is a issue of https://github.com/etcd-io/etcd and not kubernetes.

/sig etcd

**Comment by tommyzhao830** [comment]
Ok, I'll give it a try, thanks for the answer.
