### ISSUE TITLE
Modify the metadata.name length verification rule in the source code，which will not take effect after compilation

### ISSUE THREAD

**Issue by neo-hu** [kubernetes/kubernetes#122461]
### What happened?

modify k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go  
`DNS1123SubdomainMaxLength = 1000`

`KUBE_BUILD_PLATFORMS=linux/amd64 KUBE_BUILD_CONFORMANCE=n KUBE_BUILD_HYPERKUBE=n make quick-release 
`

` must be no more than 253 characters`

which will not take effect after compilation?

### What did you expect to happen?

metadata.name length > 253

### How can we reproduce it (as minimally and precisely as possible)?

modify code

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.2-dirty", GitCommit:"89a4ea3e1e4ddd7f7572286090359983e0387b2f", GitTreeState:"dirty", BuildDate:"2023-12-23T14:33:59Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kumarankit999** [comment]
Hey @neo-hu, Thanks for raising this issue. Can you tell me a line or something else that can help me troubleshoot this issue? I would like to work on it.
/assign

**Comment by thockin** [comment]
To api-machiner
