### ISSUE TITLE
QueueingHints(Pod/delete) have to consider that "unassume Pod" is treated as Pod/delete

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#122444]
### What happened?

> Side question: What if the unscheduled Pod was assumed?
https://github.com/kubernetes/kubernetes/pull/122360#discussion_r1431547953

This question made me wonder what if the Pod was unassumed. 

1. Only one Node which can accomodate only one Pod exists. 
2. Pod-a is assumed to the Node. (but not yet actually bound)
3. Pod-b is rejected because the scheduler assumes Pod-a.
4. Pod-a is somehow unassumed. **It's treated as Pod/delete event.**
5. Pod-a goes to the scheduling queue. Now, the Node has a free space though, will Pod-b be retried? Well, it's depending on the implementation of QHints of Pod/delete...

---

These are plugins that have this problem.

- [ ] nodeports
- [ ] noderesource

For example, nodeports:

> // If the deleted pod is unscheduled, it doesn't make the target pod schedulable.
https://github.com/kubernetes/kubernetes/blob/42ab3b7b40c34e91b63589ae905ed918752a4a36/pkg/scheduler/framework/plugins/nodeports/node_ports.go#L136

This is not true, because if the deleted pod is assumed Pod, it makes the target pod schedulable.

### What did you expect to happen?

1. Only one Node which can accomodate only one Pod exists. 
2. Pod-a is assumed to the Node. (but not yet actually bound)
3. Pod-b is rejected because the scheduler assumes Pod-a.
4. Pod-a is somehow unassumed. **It's treated as Pod/delete event.**
5. Pod-a goes to the scheduling queue. **noderesourcefit receives Pod/delete event by (4), and it moves Pod-b to activeQ/backoffQ.**

### How can we reproduce it (as minimally and precisely as possible)?

The above scenario.

### Kubernetes version

<details>

master

</details>

### Cloud provider

<details>
 
n/a
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ningziwen** [comment]
If pod-A anyways goes back to scheduled queue, it does not free up any resources for pod-B. Pod-B will be still unscheduled if we don't consider other changes. Does this "making unassumed" change itself really make it more possible for Pod-B to be scheduled?

**Comment by sanposhiho** [comment]
> If pod-A anyways goes back to scheduled queue, it does not free up any resources for pod-B.

It does. IIUC, the assumed pod is treated like scheduled pod in the scheduler cache. So, from the scheduler cache pov, "unassume pod from node" is the same as delete pod scheduled on node.

**Comment by ningziwen** [comment]
> > If pod-A anyways goes back to scheduled queue, it does not free up any resources for pod-B.
> 
> It does. IIUC, the assumed pod is treated like scheduled pod in the scheduler cache. So, from the scheduler cache pov, "unassume pod from node" is the same as "delete pod that was scheduled on node".

I got what you mean. It frees up more resources only from B's perspective, instead of more resources overall. in the scenario "Only one Node which can accomodate only one Pod exists.", the result will have to be that either A or B are scheduled, instead of both.

Assume you are ahead of another person in a line. You are almost served but the reception wants to pause for a minute. After one minute when it comes back, is it more fair to you to be served immeidately or rebuild the line with another person randomly? I'm not sure which philosophy we prefer generally, but I guess either way should not make difference to the overall efficiency as the overall resources don't change?

**Comment by sanposhiho** [comment]
> Assume you are ahead of another person in a line. You are almost served but the reception wants to pause for a minute. After one minute when it comes back, is it more fair to you to be served immeidately or rebuild the line with another person randomly? I'm not sure which philosophy we prefer generally, but I guess either way should not make difference to the overall efficiency as the overall resources don't change?

If very simple scenario like the above, Yes.
But, this world is actually much more complicated. There's no guarantee if the receptionist can accommodate me after a minute. One step further scenario:
1. Only one Node with 3 cores exists.
2. Pod-a with 3 cores is assumed to the Node. (but not yet actually bound)
3. Pod-b with 1 core is rejected because the scheduler assumes Pod-a to the Node and the Node has no empty resource.
4. Pod-a is somehow unassumed. It's treated as Pod/delete event.
5. Pod-a goes to the scheduling queue. 
6. Pod-c with 2 cores is scheduled to the Node. 
7. Pod-a comes back to the scheduling cycle, but the Node no longer accepts Pod-a. Pod-a is rejected and put back to the scheduling queue again.
8. Pod-a and Pod-b are in the unschedQ for 5 min.

**Comment by alculquicondor** [comment]
> This is not true, because if the deleted pod is assumed Pod, it makes the target pod schedulable.

We can take the simple approach and not ignore this change, which would go back to parity with the behavior before scheduling hints.

In general, the deletion of unscheduled pods should be uncommon.

**Comment by sanposhiho** [comment]
/close

While implementing the fix, I noticed `assume()` sets an assumed node name to `Pod.Spec.NodeName` internally. So, this bug doesn't exist.

- https://github.com/kubernetes/kubernetes/blob/42ab3b7b40c34e91b63589ae905ed918752a4a36/pkg/scheduler/schedule_one.go#L197
- https://github.com/kubernetes/kubernetes/blob/42ab3b7b40c34e91b63589ae905ed918752a4a36/pkg/scheduler/schedule_one.go#L900-L904

**Comment by alculquicondor** [comment]
> While implementing the fix, I noticed assume() sets an assumed node name to Pod.Spec.NodeName internally. So, this bug doesn't exist.

But does that name make it into the scheduling hint function?

**Comment by sanposhiho** [comment]
There're already tests for confirming `ForgetPod()` gets a Pod with `NodeName`.
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/schedule_one_test.go#L646

And, `ForgetPod` and `MoveAllToActiveOrBackoffQueue` for Pod/delete here get the same pod object.
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/schedule_one.go#L337-L354

So, yes, we can say QHint for Pod/delete gets Pods with nodename even if they are un-assumed Pods.
