### ISSUE TITLE
Faster ResourceQutoa Replenishment

### ISSUE THREAD

**Issue by leoyang02** [kubernetes/kubernetes#122483]
### What would you like to be added?

An enhancement to make the resource quota replenishment faster when resources are updated or deleted. 

### Why is this needed?

The resource quota controller does full sync of resource quotas periodically. And the resource update/delete events are put into the same queue which handles the full sync objects. In a cluster with large amount of namespaces and resource quota objects, the queue becomes too long and makes the quota replenishment slow.

**Comment by neolit123** [comment]
> An enhancement to make the resource quota replenishment faster when resources are updated or deleted.

/sig node

> In a cluster with large amount of namespaces and resource quota objects, the queue becomes too long and makes the quota replenishment slow.

/sig scalability
