### ISSUE TITLE
Preprocessing of kube.kubelet.containers.running key

### ISSUE THREAD

**Issue by AnjeiKozhev** [kubernetes/kubernetes#122454]
**I don’t understand how you can get the correct values if the preprocessing is the same for different keys, namely kube.kubelet.containers.running and kube.kubelet.containers.restarts**:

**I want to understand why the same preprocessing is performed for different keys**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by SergeyKanzhelev** [comment]
@AnjeiKozhev can you please elaborate on what the impact and how to reproduce this. 

/triage needs-information
