### ISSUE TITLE
create preemptible nodes in GCP?

### ISSUE THREAD

**Issue by Hokutosei** [kubernetes/kubernetes#12249]
Greetings,

I'm sorry if this has been asked already before, I tried searching around, but I cant find how to create preemptible nodes? I'm using GCE container cluster and there seems to be no options for preemptible nodes?

**Comment by roberthbailey** [comment]
This configuration nob doesn't exist yet in the startup scripts for GCE. You should be able to modify the [node instance template creation](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/util.sh#L403) to make the nodes preemptible without too much trouble. Feel free to send a PR to plumb through an environment variable (defaulting to false) if you get this working.

**Comment by Hokutosei** [comment]
Greetings,

yeah, I'll try hacking on this :D thanks for the tip!

**Comment by roberthbailey** [comment]
Fixed by #12384.
