### ISSUE TITLE
[Failing Test][SLOW] ci-kubernetes-e2e-ec2-eks-al2023 failed for LoadBalancers related test

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#122408]
### Failure cluster [997e83dedcf136c2d9fd](https://go.k8s.io/triage#997e83dedcf136c2d9fd)
https://storage.googleapis.com/k8s-triage/index.html?test=LoadBalancers%20should%20be%20able%20to%20change%20the%20type%20and%20ports%20of%20a%20TCP%20service

Failing job
- https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-slow
- https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-arm64-slow

Failing tests:

- Kubernetes e2e suite: [It] [sig-network] LoadBalancers should be able to change the type and ports of a TCP service [Slow] 
- Kubernetes e2e suite: [It] [sig-network] LoadBalancers should be able to create LoadBalancer Service without NodePort and change it [Slow] 
- Kubernetes e2e suite: [It] [sig-network] LoadBalancers should handle load balancer cleanup finalizer for service [Slow] 
- Kubernetes e2e suite: [It] [sig-network] LoadBalancers should only allow access from service loadbalancer source ranges [Slow] 

Skipped
- ~~Kubernetes e2e suite: [It] [sig-network] LoadBalancers should not have connectivity disruption during rolling update with externalTrafficPolicy=Cluster [Slow]~~
- ~~Kubernetes e2e suite: [It] [sig-network] LoadBalancers should not have connectivity disruption during rolling update with externalTrafficPolicy=Local [Slow]~~

##### Error text:
```
[FAILED] timed out waiting for service "mutability-test" to have a load balancer: context deadline exceeded
In [It] at: test/e2e/network/loadbalancer.go:225 @ 12/10/23 16:15:57.83

```
#### Recent failures:
[2023/12/20 01:32:43 ci-kubernetes-e2e-ec2-eks-al2023-arm64-slow](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-arm64-slow/1737163290548637696)
[2023/12/19 19:31:38 ci-kubernetes-e2e-ec2-eks-al2023-arm64-slow](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-arm64-slow/1737072439478718464)
[2023/12/19 19:30:34 ci-kubernetes-e2e-ec2-eks-al2023-slow](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-slow/1737072185958207488)
[2023/12/19 13:31:34 ci-kubernetes-e2e-ec2-eks-al2023-arm64-slow](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-arm64-slow/1736981837995053056)
[2023/12/19 13:30:33 ci-kubernetes-e2e-ec2-eks-al2023-slow](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-slow/1736981587439915008)

/kind failing-test
/sig network

**Comment by pacoxu** [comment]
/cc @aojea
previous failure in https://github.com/kubernetes/kubernetes/issues/114577

**Comment by aojea** [comment]
Loadbalancers are infrastructure specific, so there is no much kubernetes devs can do if there is no connection with the implementation , the test shows this error

```
(x18 over 15m)  service  Failed build model due to unable to resolve at least one subnet (0 match VPC and tags)\n"
Dec 19 12:08:44.913: INFO: Name:                     test-lb-rolling-update
Namespace:                loadbalancers-4997
Labels:                   name=test-lb-rolling-update
Annotations:              <none>
Selector:                 name=test-lb-rolling-update
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.108.212.88
IPs:                      10.108.212.88
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31051/TCP
Endpoints:                172.31.29.150:80,172.31.31.27:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason            Age                  From     Message
  ----     ------            ----                 ----     -------
  Warning  FailedBuildModel  4m2s (x18 over 15m)  service  Failed build model due to unable to resolve at least one subnet (0 match VPC and tags)
```


I know per example that AWS LB has some tests that are skipped because they require to use annotations, and we are not likely going to implement test that mutate the behavior depending on where they are running as it does not scale.

My recommendation is first to understand what is the problem, is there some wrong assumption on the test?
Do we want to run this tests in AWS @dims ?
if not, just skip them in the regex, @upodroid is working on these jobs , he may have more insights

**Comment by thockin** [comment]
ping @dims

**Comment by dims** [comment]
ACK @thockin haven't had a chance to get to this!

**Comment by dims** [comment]
Still on my TODO

**Comment by aojea** [comment]
I saw PR about this I can not find 🤔

**Comment by dims** [comment]
@aojea disabled for now, leaving this issue open though - https://github.com/kubernetes/test-infra/pull/31888

**Comment by aojea** [comment]
> waiting for next execution today with more verbosity on the controller manager #124616

wrong issue :) 

/unassign @aojea 
/remove-sig network

**Comment by pacoxu** [comment]
/close 
as ci is green now
