### ISSUE TITLE
[Flaking Test] Restart [Disruptive] [KubeUp] should restart all nodes and ensure all nodes and pods recover

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#122407]
### Which jobs are flaking?

ci-kubernetes-e2e-gci-gce-serial

### Which tests are flaking?

[sig-cloud-provider-gcp] Restart [Disruptive] [KubeUp] should restart all nodes and ensure all nodes and pods recover

### Since when has it been flaking?

In the testgrid, the first time is in 12-10.  I may flake long time ago. at least: 2023/8/15

https://storage.googleapis.com/k8s-triage/index.html?date=2023-08-20&test=should%20restart%20all%20nodes%20and%20ensure%20all%20nodes%20and%20pods%20recover

### Testgrid link

 - flake in https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial before(now not flake for weeks)
 - flake in https://storage.googleapis.com/k8s-triage/index.html?date=2024-04-01&test=should%20restart%20all%20nodes%20and%20ensure%20all%20nodes%20and%20pods%20recover multi CI: 
   - ci-kubernetes-e2e-gce-cos-k8sstable[1|2|3]-serial	
   - ci-kubernetes-e2e-gce-cos-k8sbeta-serial	

### Reason for failure (if possible)
```
{ failed [FAILED] At least one pod wasn't running and ready or succeeded at test start.
In [BeforeEach] at: test/e2e/cloud/gcp/restart.go:81 @ 12/19/23 00:34:09.641
}
```

### Anything else we need to know?

N/A

### Relevant SIG(s)

/sig cloud-provider
/area provider/gcp

**Comment by elmiko** [comment]
we are discussing this at the sig cloud provider office hours and while it is a gcp cloud provider issue, we think that we might need involvement from sig node as well.

cc @tallclair

**Comment by bridgetkromhout** [comment]
Although this problem shows up in the CCM, we do need SIG Node to take a look and triage this - SIG Cloud Provider needs Node's input to understand this.

**Comment by moficodes** [comment]
Hello!
Release Signal shadow here.
This issue has not been updated for a long time, so I'd like to check what's the status. The code freeze is starting [02:00 UTC Wednesday 6th March 2024 / 18:00 PDT Tuesday 5th March 2024](https://everytimezone.com/s/5056bace) (less than a month from now), and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As this issue is tagged for 1.30, is it still planned for this release?

**Comment by pacoxu** [comment]
/milestone clear
flake only once in last 2 weeks



> Although this problem shows up in the CCM, we do need SIG Node to take a look and triage this - SIG Cloud Provider needs Node's input to understand this.

/cc @SergeyKanzhelev @bart0sh

**Comment by pacoxu** [comment]
No flake after 03-18.

The priority may be very low for v1.30.

/close

**Comment by pacoxu** [comment]
/reopen 
still flake in other CI

https://storage.googleapis.com/k8s-triage/index.html?date=2024-04-01&test=should%20restart%20all%20nodes%20and%20ensure%20all%20nodes%20and%20pods%20recover

**Comment by pacoxu** [comment]
/close 

The test is not in https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial any more.
