### ISSUE TITLE
Do kubernetes1.0 create a token automatically ?

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#12256]
i saw some docs and one of them(
https://github.com/GoogleCloudPlatform/kubernetes/blob/fd7a48f379fd4f6b0779bdc6db1efb625b1a24d8/docs/user-guide/service-accounts.md#using-the-default-service-account-to-access-the-api-server) 
said that when we start api-server. It will create a serviceaccount named "default".and it will also create a token(or a secret?) for that.
   
but why can't i find the token?

[root@vm-56-65 bin]# kubectl  get serviceaccounts
NAME      SECRETS
default   0

i  tried  to start apiserver with flag --admission_control  but it still not created.

**Comment by dchen1107** [comment]
What is your cloud environment? 

For several cloud providers, such as gce, aws, etc. yes, we create token automatically.

**Comment by fzu-huang** [comment]
@dchen1107    
i know what's  wrong  

when  i start apiserver   i should add flag:
--service_account_key_file=/var/run/kubernetes/apiserver.key --service_account_lookup=false --admission_control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota 

and  then copy a key file to the file location.

all these are done in the shell script "/hack/local-up-cluster.sh".

now  it is  OK .

I think these two flag (service_account_lookup,service_account_key_file) must be motioned in kubernete's doc.....
thank you for your caring~

**Comment by dalanlan** [comment]
hack/local-up-cluster.sh is aimed to start a local one. 
Yet i do believe `--service_account_key_file` & `--service_account_lookup` are optional. k8s would create a token automatically even without cloud provider, ubuntu for example.
