### ISSUE TITLE
kubectl/cmd/util rolling_updater_test.go TestUpdateWithRetries: Use timeout defined in RollingUpdaterConfig

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#12258]
From a shippable build that failed spuriously for #12168
https://app.shippable.com/builds/55c1b5430e93780b00588c5a

```
ok github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/util   1.373s  coverage: 32.3% of statements
--- FAIL: TestUpdateWithRetries (0.61s)
rolling_updater_test.go:958: unexpected error: timed out waiting for the condition
rolling_updater_test.go:963: Remaining updates [0xc20814f320] gets []
FAIL
coverage: 56.3% of statements
FAIL    github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl   2.260s
```

In looking at the rolling updater code, it appears to have a whopping 500ms timeout.  I'm not sure why we'd expect to be able to contact the API server to update an RC, then contact it again to get the new RC, and do it all within 500 ms on an ongoing reliable basis given network links, etcd, etc.  We have evidence that even in unit tests that's not always possible.  @ixdy @jlowdermilk

**Comment by alex-mohr** [comment]
@jlowdermilk writes: This should not be hard coded. RollingUpdaterConfig defines a timeout to use when updating controllers. We should be using that.

**Comment by alex-mohr** [comment]
Leaving this open -- we shouldn't hardcode, but plumb through the config value instead.

**Comment by nikhiljindal** [comment]
Assuming this is regarding pkg/kubectl/rolling_updater_test.go.
cc @ironcladlou who is touching that file in one of his PR

**Comment by ironcladlou** [comment]
Just FYI: this shouldn't conflict with #11942; the update code in question is actually just a helper used exclusively by `UpdateExistingReplicationController` which is part of the CLI command setup for rolling updates. It won't affect the main update loop, but it would affect the setup of a rolling update initiated via the CLI.

**Comment by ironcladlou** [comment]
And thanks @nikhiljindal for the heads up!

**Comment by lavalamp** [comment]
Reducing priority, renaming.

**Comment by ixdy** [comment]
Is this still an issue? Should this be under the flake label?

**Comment by jlowdermilk** [comment]
Shouldn't be under flake. The issue is purely internal cleanup. It would not surprise me if there are other retry timeouts sprinked throughout kubectl that should be standardized.

**Comment by kargakis** [comment]
Shouldn't be an issue anymore
