### ISSUE TITLE
Namespace resource reservation per node

### ISSUE THREAD

**Issue by remiville** [kubernetes/kubernetes#122542]
### What would you like to be added?

An object named NodeReservation :
- with one CPU entry
- if one pod of a namespace wants to be scheduled on a node the latter must have NodeReservation.cpu non requested and free CPU
- if at least one pod of this namespace run on a node, any pod of another namespace cannot consume the CPU reserved
- sum of all pod CPU limits of the namespace concerned by the NodeReservation, per node, cannot be greater than the NodeReservation.cpu
- CPU throttling of these pods happens if they try to consume more CPU than the NodeReservation.cpu
- pods of this namespace are never evicted

### Why is this needed?

Many applications are migrated to kubernetes.
Often these applications avoid to be evicted because they have not been originally designed to relaunch interrupted tasks or the cost to rerun a long task can be considered too high.
Also these applications come from the VM world, where there's no CPU limit per process but a global VM CPU capacity is shared between all processes running inside.
When migrating to kubernetes, finding good pod CPU limits and dealing with CPU throttling can be difficult to address.
It is not obvious to take a global VM CPU capacity an convert it to per pod CPU limits.

Some operators/developers would like their main application pods without CPU limits but also avoid them being evicted.

Is there a way to reserve a CPU capacity per namespace per node ?

Such a feature may not be desirable from a kubernetes point of view, but I am also curious to have hints to how address this issue differently with such applications without rewriting them from scratch or chose an oversized pod request = limit to either avoid eviction and CPU throttling. 

By the way, happy new year !

**Comment by thockin** [comment]
If you just don't set CPU limit on your pod - what is causing eviction?

**Comment by thockin** [comment]
That's not really how it works.

We schedule. Pods to nodes based only on requests, and (unless the node reports the wrong allocatable) whenever a pod needs its request, it can have it.  Pods with limit > request have access to other pods' unused CPU, but no guarantees.

In the worst case, every pod is using 100% of its request, and nobody gets to borrow extra, but that is what you asked for with requests.

My standing guidance for max happiness: almost always set memory limit == request; almost never set cpu limit. 

This proposal sounds hypothetical.  If you have an actual problem happening, we'll be happy to try to help diagnose, of course.

**Comment by remiville** [comment]
Thanks a lot for taking your time to give me those explanations.
I'm confused as my mistake comes from the fact I thought there was a node CPU pressure but it doesn't exist (my bad), I should have read the documentation correctly, it speaks about memory, disk and pid node pressure but nothing about CPU.

Thanks for your hints concerning resources requests and limits.

Optional question: I read somewhere that it is possible for a pod to reserve an integer number of vCPU, thanks to the CPU manager (to avoid context switch, cache miss issues), but the QoS must be guaranteed, does it really imply request=limit for both CPU AND memory ? even if it seems to concern CPU only resource ?

It happens the documentation speaks about QoS even if it seems concerning exclusively CPU or memory resource, but I wonder if the QoS is not just a flag not really used by the kubernetes engine.
Ok I go read the documentation 😉
