### ISSUE TITLE
Projected Service Account Tokens: Ability to specify multiple Audiences

### ISSUE THREAD

**Issue by denniskniep** [kubernetes/kubernetes#122500]
### What would you like to be added?

The Property `Audience` of  `ServiceAccountTokenProjection` is currently a `string`. (see [here]( https://kubernetes.io/docs/concepts/storage/projected-volumes/#serviceaccounttoken) and [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md#api-change))

Would be helpful if this could be an array of type string (`Audiences []string`)
  

### Why is this needed?

1. If the token is passed to a service for authentication and that service uses exactly that token to authenticate on the k8s token review api endpoint, then at least two audiences are necessary. First for the service itself and second the k8s api server audience. (Example Hashicorp Vault K8s Auth Plugin: see [here](https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/6f9c733333c1d5f86166db8db0016eda7bfb21bf/path_login.go#L456) and [here](https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/6f9c733333c1d5f86166db8db0016eda7bfb21bf/token_review.go#L71))

2. To be consistent with the manual `TokenRequest` api, which also allows to create tokens with multiple audiences (see [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md#api-changes))

**Comment by enj** [comment]
> First for the service itself and second the k8s api server audience

For this use case I would expect two tokens to be used (one for the API server and the other for vault).  A token with multiple audiences is saying that all audiences in the list are equivalent, which is not the case here.

**Comment by mikedanese** [comment]
Based on https://github.com/cert-manager/cert-manager/issues/6150#issuecomment-1733934244, it seems like the fundamental issue here is that it's hard to provision credentials for service accounts that run external to the cluster. Multiple audiences support in `ServiceAccountTokenProjection` seems like an incidental "fix" for this issue in this specific instance but does not address the root issue. This does not seem like a valid use of multiple audiences. If you want to do this, you can just configure vault to accept the API servers audience.

**Comment by enj** [comment]
Closing this per Mike's comment

/close

**Comment by denniskniep** [comment]
@mikedanese okay, got your point and I agree, both components (vault-kubernetes-auth and cert-manager) does not play together well in that specific situation. 

But what about my second point?

> To be consistent with the manual TokenRequest api, which also allows to create tokens with multiple audiences (see [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md#api-changes))

Does it make sense to design it equally to the TokenRequest API?

**Comment by enj** [comment]
Notes from today's SIG Auth meeting:

- Multiple audiences rarely needed in steady state
- Migration from one audience to another can be handled with either two audiences accepted at the server or two audiences in the token, we chose to go with the multiple audiences supported at the server (hence token review API supports multiple audiences but the projected volume does not)
- Token request does support multiple audiences, but supporting it in the projected volume would require a concrete use case (the situation described in this issue is not a sufficient reason to make such a change)
