### ISSUE TITLE
"kubectl get <entity>" faulty if the number of entities are more than 10

### ISSUE THREAD

**Issue by Pratham1812** [kubernetes/kubernetes#122546]
### What happened?

I created a `sts` and scaled it to `30` replicas and then used `kubectl get pods` and `kubectl get pvc`
![issue2](https://github.com/kubernetes/kubernetes/assets/32198580/7ce62c91-641e-4c84-ac8f-b8f22171b09c)
![pvc](https://github.com/kubernetes/kubernetes/assets/32198580/01213f52-c410-4f87-9845-f209b11433b1)

### What did you expect to happen?

I expected to get the pods and pvc names to print in order of which they were created that is increasing order of the indexes.

### How can we reproduce it (as minimally and precisely as possible)?

Following this [tutorial](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/). If I scale by more than 10 replicas executing `kubectl scale sts web --replicas=30 ` and then execute `kubectl get pods -l app=nginx`

### Anything else we need to know?

The issue is probably in the following files [customcolumn.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/get/customcolumn.go) and
[sorter.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/get/sorter.go)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Ithrael** [comment]
![image](https://github.com/kubernetes/kubernetes/assets/38208715/d22643da-05b3-4dca-9f1c-e74c683d64d2)

The default sort order for `kubectl get po`. is by name. If you want to sort by creation time, you can use `kubectl get pods --sort-by=.metadata.creationTimestamp`

**Comment by mpuckett159** [comment]
It looks like this support question has been answered, closing but please open if there are more details needed.
/close
