### ISSUE TITLE
Docker IPs are not communicating each other in a kubernetes cluster 

### ISSUE THREAD

**Issue by Naresht-vedams** [kubernetes/kubernetes#12250]
I have two nodes cluster  172.16.2.92 ("ai") (kube02) it is ubuntu vm and 10.0.0.2 ("i") (ubuntu1) it is a devstack instance. Floating IP for devstack node is 172.16.2.10 

``kube02:``
``eth0 - 172.16.2.92
flannel0 - 12.1.27.0
docker0 - 12.1.27.1``

``ubuntu1:``
``eth0 - 10.0.0.2
flannel0 - 12.1.51.0
docker0 -  12.1.51.1``

``config-default.sh:`` 
``export nodes="root@172.16.2.92 root@172.16.2.10"``

In config-default file  I am using floating IP and I changed *listen-peer-urls http:* IP to *10.0.0.2* in   */etc/default/etcd* file in ubuntu1 so two nodes are get ready state 
``ETCD_OPTS="-name infra1   -initial-advertise-peer-urls http://172.16.2.10:2380   -listen-peer-urls http://10.0.0.2:2380   -initial-cluster-token etcd-cluster-1   -initial-cluster infra0=http://172.16.2.64:2380,infra1=http://172.16.2.10:2380   -initial-cluster-state new"``  
docker IPs are unable to ping each other from two vms. To get this work, do I need to change any configuration ?

**Comment by kgrvamsi** [comment]
Is this happening across regions or with the same region?If not then can you show me what etcdtcl ls --recursive gives and what is the output at /etc/subnets.env?

**Comment by Naresht-vedams** [comment]
Is this you are asking @kgrvamsi 

*# cat /run/flannel/subnet.env*
``FLANNEL_SUBNET=12.1.40.1/24``
``FLANNEL_MTU=1472``
``FLANNEL_IPMASQ=false``

*# etcdtcl ls -- recursive*
``etcdtcl: command not found``

**Comment by lleszczu** [comment]
you have a typo, it is etcd**ct**l not etcd**tc**l

**Comment by Naresht-vedams** [comment]
*# etcdctl ls --recursive*
``etcdctl: command not found``

**Comment by kgrvamsi** [comment]
oh u need to get the etcdctl binary and check it whether the keys are stored on to the ETCD because every flanneld daemon check for their settings in their respective keys stored on etcd and based upon that the subnet communication from one node to other node happens.

BTW what is the mode of communication which presently your flanneld is using? vlan or gre?

**Comment by kgrvamsi** [comment]
These are my FlannelD options

    FLANNEL_ETCD_PREFIX="/coreos.com/network/config"
    FLANNEL_NETWORK_CONFIG='{"Network":"10.10.0.0/16","Backend":{"Type":"vxlan"}}'
    FLANNEL_OPTS="--ip-masq --etcd-endpoints=http://0.0.0.0:4001"
    FLANNEL_ETCDCTL_OPTS="-C http://0.0.0.0:4001"

**Comment by Naresht-vedams** [comment]
Is that flannel IPs are pinging for you ?

**Comment by kgrvamsi** [comment]
Yes !!!!

**Comment by kgrvamsi** [comment]
May be this screenshot may help you out!!!!

![flanneld-working](https://cloud.githubusercontent.com/assets/1199031/9085117/9be0a47a-3b97-11e5-863b-8e6540c1a298.png)

**Comment by Naresht-vedams** [comment]
Here in my case docker IPs should ping

**Comment by kgrvamsi** [comment]
Yes they can Ping.... :100: %

![flanneld-working](https://cloud.githubusercontent.com/assets/1199031/9085366/bdb242be-3b99-11e5-891e-ef26a6cbeba3.png)

**Comment by kgrvamsi** [comment]
Lets close this  issue and feel free to reopen it anytime if you have doubts

**Comment by Naresht-vedams** [comment]
Where is docker bridge in your screenshots . That is eth0 bridge.

**Comment by kgrvamsi** [comment]
if you use flannel then docker bridge interface will replace with the flanneld bridge on the host and docker bridge is the underlaying networking for the containers to take over the ip's released from the base machine bridge interface.

**Comment by mbforbes** [comment]
@Naresht-vedams did @kgrvamsi's answer help? I'm going to close this issue assuming so, but please feel free to re-open if not.
