### ISSUE TITLE
Pause image seems make no sense in kubeadm part

### ISSUE THREAD

**Issue by weilaaa** [kubernetes/kubernetes#122577]
### What happened?

I was gonna install k8s cluster through `kubeadm` in an offline environment through pre-prepared images, but pause image is not as my expectations, as a result, the paused image pull failed, and `kubelet` also failed to start.

### What did you expect to happen?

`kubelet` use the pause image which I override in `kubeadm`, and `kubelet` start success.

### How can we reproduce it (as minimally and precisely as possible)?

1. At first, I use `kubeadm config images list` to list all k8s images which I need to prepare in advance, and print bellow:
```
I1229 04:29:13.670682   21144 version.go:256] remote version is much newer: v1.29.0; falling back to: stable-1.28
registry.k8s.io/kube-apiserver:v1.28.4
registry.k8s.io/kube-controller-manager:v1.28.4
registry.k8s.io/kube-scheduler:v1.28.4
registry.k8s.io/kube-proxy:v1.28.4
registry.k8s.io/pause:3.9
registry.k8s.io/etcd:3.5.9-0
registry.k8s.io/coredns/coredns:v1.10.1
```

2. Use the following configuration file to initialize the cluster with kubeadm
```
kind: ClusterConfiguration
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
... # other content
```

3. Inspect the pause image actually used.
```
[root@localhost ~]# ps -ef | grep '/usr/local/bin/kubelet'
root     27248     1  4  2023 ?        07:06:00 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime-endpoint=unix:///var/run/cri-dockerd.sock --pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9
```
```
[root@localhost ~]# docker ps -a | grep pause
a279c1be4c9c        registry.k8s.io/pause:3.6            "/pause"                 6 days ago          Up 6 days                                     k8s_POD_calico-kube-controllers-7fd5bb489f-6pxjx_kube-system_7e9c6ee5-90f7-4484-9de5-9658f5ba430d_1
```

### Anything else we need to know?

I know `--pod-infra-container-image` flag in `kubelet` was deprecated, and we should override pause image at `container runtime` side, It's ok to me, but what about the config in `kubeadm`, It seems make no sense as soon as `--pod-infra-container-image` removed. Pause image in preflight check make no sense either.

By the way, please think about it, do we need to maintain the default version of pause image in k/k, such as in kubelet and e2e test? Can we obtain the pause image information directly through `CRI`?

### Kubernetes version

kubeadm version: &version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.4", GitCommit:"bae2c62678db2b5053817bc97181fcc2e8388103", GitTreeState:"clean", BuildDate:"2023-11-15T16:56:18Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

none

### Install tools

kubeadm v1.28.4

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> I know --pod-infra-container-image flag in kubelet was deprecated, and we should override pause image at container runtime side, It's ok to me, but what about the config in kubeadm, It seems make no sense as soon as --pod-infra-container-image removed. Pause image in preflight check make no sense either.

currently, the kubeadm pause image is the pause image you need for a certain k8s release. it is the source of truth and you must set the same version in your container runtime config.

there were some discussions that kubeadm should not care about pause at all.
but it's still useful in scenarios where the cluster admin wants to pre-pull all required official images with `kubeadm config images pull`.

for kubeadm there is no actionable items here, yet - i.e. there is no plan to remove the pause image from kubeadm.
if you wish you can skip the preflight (image pull) phase.

> By the way, please think about it, do we need to maintain the default version of pause image in k/k, such as in kubelet and e2e test? Can we obtain the pause image information directly through CRI?

if you ask me, the pause image should not even exist. the concept of a "parent container" should be integral to CRI implementers. but for that you can open a separate ticket that does not discuss kubeadm.

**Comment by neolit123** [comment]
/area kubeadm
/kind support
given there is nothing actionable on the kubeadm side

**Comment by neolit123** [comment]
> > I know --pod-infra-container-image flag in kubelet was deprecated, and we should override pause image at container runtime side, It's ok to me, but what about the config in kubeadm, It seems make no sense as soon as --pod-infra-container-image removed. Pause image in preflight check make no sense either.
> 
> currently, the kubeadm pause image is the pause image you need for a certain k8s release. it is the source of truth and you must set the same version in your container runtime config.
> 
> there were some discussions that kubeadm should not care about pause at all. but it's still useful in scenarios where the cluster admin wants to pre-pull all required official images with `kubeadm config images pull`.
> 
> for kubeadm there is no actionable items here, yet - i.e. there is no plan to remove the pause image from kubeadm. if you wish you can skip the preflight (image pull) phase.

here is the old discussion on this topic.
there are no pending changes for kubeadm until kubelet / CRI make a change - e.g. drop pause completely.
https://github.com/kubernetes/kubeadm/issues/2020#issuecomment-844185318

> 
> > By the way, please think about it, do we need to maintain the default version of pause image in k/k, such as in kubelet and e2e test? Can we obtain the pause image information directly through CRI?
> 
> if you ask me, the pause image should not even exist. the concept of a "parent container" should be integral to CRI implementers. but for that you can open a separate ticket that does not discuss kubeadm.

+1, if you want more discussion on this topic you can:
- log a new issue and tag it with `/sig node`
- or try contacting sig node in a different way
https://github.com/kubernetes/community/tree/master/sig-node


/close

**Comment by weilaaa** [comment]
> there are no pending changes for kubeadm until kubelet / CRI make a change - e.g. drop pause completely.
> [kubernetes/kubeadm#2020 (comment)](https://github.com/kubernetes/kubeadm/issues/2020#issuecomment-844185318)

I read all the discussions in this issue, and I agree `there are no pending changes for kubeadm until kubelet / CRI make a change - e.g. drop pause completely.`, thanks for the explanation, I'ill consider log a new issue and tag it with /sig node.
