### ISSUE TITLE
world's first K8S AI agent is here, never write a single kubectl command again.

### ISSUE THREAD

**Issue by incomingflyingbrick** [kubernetes/kubernetes#122526]
### k8s agent is here

    Hi everyone, I've created a Kubernetes agent using GPT-4. It can perform various kinds of tasks for you. You can interact with the agent using natural language, and it will accomplish tasks for you.

Head to this repo to get started!
https://github.com/incomingflyingbrick/agentk8s

A blog about the agent on medium.
[https://medium.com/@vurtnesaerdna/k-gpt-an-autonomous-kubernetes-agent-k8s-agent-3f58c0a4af44](url)

**Comment by neolit123** [comment]
hello, this is a bug/feature tracker.
you can share this on external platforms like reddit, for example.

/close
