### ISSUE TITLE
go-flow-levee is abandoned and semi-broken

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#122592]
Our ./hack/verify-govet-levee.sh calls github.com/google/go-flow-levee which has not been updated in years.

Importantly, it does not support generics (https://github.com/google/go-flow-levee/issues/323) which leads to a spew of warnings:

```
# k8s.io/kubernetes/test/e2e/framework
unexpected type received: *types.TypeParam T; please report this issue
unexpected type received: *types.TypeParam T; please report this issue
unexpected type received: *types.TypeParam T; please report this issue
unexpected type received: *types.TypeParam T; please report this issue
```

Does this tool serve any purpose today, or should we just get rid of it?

**Comment by BenTheElder** [comment]
/sig security
FYI @kubernetes/sig-security
