### ISSUE TITLE
[Flaking Test] [sig-scheduling] UT TestSchedulerWithExtenders

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#122505]
### Which jobs are [flaking](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md)?

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Which tests are flaking?

TestSchedulerWithExtenders

### Since when has it been flaking?

After https://github.com/kubernetes/kubernetes/pull/122435 was merged 

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

```
1/1092 Tests Failed. 

k8s.io/kubernetes/pkg: scheduler expand_less13s{Failed;Failed;  === RUN   TestSchedulerWithExtenders/test_10     node_tree.go:65: I1228 06:39:37.927007] Added node in listed group to NodeTree node="node1" zone=""     node_tree.go:65: I1228 06:39:37.927159] Added node in listed group to NodeTree node="node2" zone="" W1228 06:39:37.927283   50360 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.     framework.go:368: I1228 06:39:37.927793] the scheduler starts to work with those plugins Plugins={"PreEnqueue":{"Enabled":null,"Disabled":null},"QueueSort":{"Enabled":[{"Name":"PrioritySort","Weight":0}],"Disabled":null},"PreFilter":{"Enabled":null,"Disabled":null},"Filter":{"Enabled":[{"Name":"TrueFilter","Weight":0}],"Disabled":null},"PostFilter":{"Enabled":null,"Disabled":null},"PreScore":{"Enabled":null,"Disabled":null},"Score":{"Enabled":null,"Disabled":null},"Reserve":{"Enabled":null,"Disabled":null},"Permit":{"Enabled":null,"Disabled":null},"PreBind":{"Enabled":null,"Disabled":null},"Bind":{"Enabled":[{"Name":"DefaultBinder","Weight":0}],"Disabled":null},"PostBind":{"Enabled":null,"Disabled":null},"MultiPoint":{"Enabled":null,"Disabled":null}}     extender_test.go:345: Unexpected error: 0/2 nodes are available: 1 FakeExtender: node "node2" failed.     --- FAIL: TestSchedulerWithExtenders/test_10 (0.00s) ;=== RUN   TestSchedulerWithExtenders --- FAIL: TestSchedulerWithExtenders (0.03s) ;} | k8s.io/kubernetes/pkg: scheduler expand_less | 13s | {Failed;Failed;  === RUN   TestSchedulerWithExtenders/test_10     node_tree.go:65: I1228 06:39:37.927007] Added node in listed group to NodeTree node="node1" zone=""     node_tree.go:65: I1228 06:39:37.927159] Added node in listed group to NodeTree node="node2" zone="" W1228 06:39:37.927283   50360 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.     framework.go:368: I1228 06:39:37.927793] the scheduler starts to work with those plugins Plugins={"PreEnqueue":{"Enabled":null,"Disabled":null},"QueueSort":{"Enabled":[{"Name":"PrioritySort","Weight":0}],"Disabled":null},"PreFilter":{"Enabled":null,"Disabled":null},"Filter":{"Enabled":[{"Name":"TrueFilter","Weight":0}],"Disabled":null},"PostFilter":{"Enabled":null,"Disabled":null},"PreScore":{"Enabled":null,"Disabled":null},"Score":{"Enabled":null,"Disabled":null},"Reserve":{"Enabled":null,"Disabled":null},"Permit":{"Enabled":null,"Disabled":null},"PreBind":{"Enabled":null,"Disabled":null},"Bind":{"Enabled":[{"Name":"DefaultBinder","Weight":0}],"Disabled":null},"PostBind":{"Enabled":null,"Disabled":null},"MultiPoint":{"Enabled":null,"Disabled":null}}     extender_test.go:345: Unexpected error: 0/2 nodes are available: 1 FakeExtender: node "node2" failed.     --- FAIL: TestSchedulerWithExtenders/test_10 (0.00s) ;=== RUN   TestSchedulerWithExtenders --- FAIL: TestSchedulerWithExtenders (0.03s) ;}
k8s.io/kubernetes/pkg: scheduler expand_less | 13s
{Failed;Failed;  === RUN   TestSchedulerWithExtenders/test_10     node_tree.go:65: I1228 06:39:37.927007] Added node in listed group to NodeTree node="node1" zone=""     node_tree.go:65: I1228 06:39:37.927159] Added node in listed group to NodeTree node="node2" zone="" W1228 06:39:37.927283   50360 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.     framework.go:368: I1228 06:39:37.927793] the scheduler starts to work with those plugins Plugins={"PreEnqueue":{"Enabled":null,"Disabled":null},"QueueSort":{"Enabled":[{"Name":"PrioritySort","Weight":0}],"Disabled":null},"PreFilter":{"Enabled":null,"Disabled":null},"Filter":{"Enabled":[{"Name":"TrueFilter","Weight":0}],"Disabled":null},"PostFilter":{"Enabled":null,"Disabled":null},"PreScore":{"Enabled":null,"Disabled":null},"Score":{"Enabled":null,"Disabled":null},"Reserve":{"Enabled":null,"Disabled":null},"Permit":{"Enabled":null,"Disabled":null},"PreBind":{"Enabled":null,"Disabled":null},"Bind":{"Enabled":[{"Name":"DefaultBinder","Weight":0}],"Disabled":null},"PostBind":{"Enabled":null,"Disabled":null},"MultiPoint":{"Enabled":null,"Disabled":null}}     extender_test.go:345: Unexpected error: 0/2 nodes are available: 1 FakeExtender: node "node2" failed.     --- FAIL: TestSchedulerWithExtenders/test_10 (0.00s) ;=== RUN   TestSchedulerWithExtenders --- FAIL: TestSchedulerWithExtenders (0.03s) ;}


```

### Anything else we need to know?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1739996472507633664

> Resubmit of https://github.com/kubernetes/kubernetes/pull/122058, reverted in https://github.com/kubernetes/kubernetes/pull/122317 due to a flaky test

### Relevant SIG(s)

/sig scheduling
/cc @aleksandra-malinowska

**Comment by srivastav-abhishek** [comment]
This flakiness can be observed on ppc64le arch as well,

```
{Failed;Failed;  === RUN   TestSchedulerWithExtenders/test_10
    node_tree.go:65: I0102 13:22:44.856712] Added node in listed group to NodeTree node="node1" zone=""
    node_tree.go:65: I0102 13:22:44.856867] Added node in listed group to NodeTree node="node2" zone=""
W0102 13:22:44.856989   55133 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
    framework.go:368: I0102 13:22:44.857590] the scheduler starts to work with those plugins Plugins={"PreEnqueue":{"Enabled":null,"Disabled":null},"QueueSort":{"Enabled":[{"Name":"PrioritySort","Weight":0}],"Disabled":null},"PreFilter":{"Enabled":null,"Disabled":null},"Filter":{"Enabled":[{"Name":"TrueFilter","Weight":0}],"Disabled":null},"PostFilter":{"Enabled":null,"Disabled":null},"PreScore":{"Enabled":null,"Disabled":null},"Score":{"Enabled":null,"Disabled":null},"Reserve":{"Enabled":null,"Disabled":null},"Permit":{"Enabled":null,"Disabled":null},"PreBind":{"Enabled":null,"Disabled":null},"Bind":{"Enabled":[{"Name":"DefaultBinder","Weight":0}],"Disabled":null},"PostBind":{"Enabled":null,"Disabled":null},"MultiPoint":{"Enabled":null,"Disabled":null}}
    extender_test.go:345: Unexpected error: 0/2 nodes are available: 1 FakeExtender: node "node2" failed.
    --- FAIL: TestSchedulerWithExtenders/test_10 (0.00s)
;=== RUN   TestSchedulerWithExtenders
--- FAIL: TestSchedulerWithExtenders (0.04s)
;}
```

/cc @Rajalakshmi-Girish  @mkumatag

**Comment by srivastav-abhishek** [comment]
@pacoxu This issue is getting observed frequently on `ppc arch`.

Link to failure : https://prow.k8s.io/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le/1755260242423189504

**Comment by AxeZhan** [comment]
So I dig into it, and I'm sure this is a bug...

In #122435, we introduced this logic in `findNodesThatPassFilters`, and this doesn't consider about extenders
```
	if !sched.hasScoring(fwk) {
		numNodesToFind = 1
	}
```

Say that we have two nodes(node1, node2), some filter plugins but no score plugins.
With this line, we'll return only one node in `findNodesThatPassFilters`, probably `node1` but also probably `node2`(due to we check nodes parallel).

And if we have one extender which rejects node1, we'll fail in `findNodesThatPassExtenders` 
if `findNodesThatPassFilters` returns `node2`, but before  #122435, we'll return both nodes in `findNodesThatPassFilters`, and node2 will pass the extenders.

I'm not sure if this is included in `1.29.1`, but it seems yes, then this is a regression, I think we should just revert it now.
/cc @kubernetes/sig-scheduling-approvers 
/kind bug
/kind regression

**Comment by AxeZhan** [comment]
And as we can't stop checking nodes in `findNodesThatPassFilters`.
I think the only performance we can improve is here in `prioritizeNodes`:
Change `if len(extenders) == 0 && !fwk.HasScorePlugins() ` to something like: ` if len(ScoreExtenders) == 0 && !fwk.HasScorePlugins() `
I doubt this will have a considerable improvement, and I'm not sure if we should implement #122435 again.

**Comment by alculquicondor** [comment]
The default `numNodesToFind` is 100. If it happens to be the case that the extenders reject these 100 nodes, but there is another node that could have fit, we still reach this situation, wouldn't we?

**Comment by AxeZhan** [comment]
> The default numNodesToFind is 100. If it happens to be the case that the extenders reject these 100 nodes, but there is another node that could have fit, we still reach this situation, wouldn't we?

Yes, I think so. But I don't think this behavior is related to https://github.com/kubernetes/kubernetes/pull/122435 . So does this affect #123290 ?

**Comment by aleksandra-malinowska** [comment]
>And as we can't stop checking nodes in findNodesThatPassFilters.

We could also check for `len(extenders) == 0` here. It's less elegant, but seems practical. 

>However, making numNodesToFind = 1 will Increase the probability of this scenario occurring. And it will greatly increase the time required for this pod to return to normal.

Yes, it makes it more likely to hit this.

**Comment by ahg-g** [comment]
> We could also check for len(extenders) == 0 here. It's less elegant, but seems practical.

I think more specifically check that no filters are registered.

> The default numNodesToFind is 100. If it happens to be the case that the extenders reject these 100 nodes, but there is another node that could have fit, we still reach this situation, wouldn't we?

The ultimate fix is to continue to check for another `numNodesToFind` until all nodes are checked if `findNodesThatPassExtenders` filters all nodes.
