### ISSUE TITLE
Cannot setup kubernetes on ubuntu 15.04

### ISSUE THREAD

**Issue by asdfsx** [kubernetes/kubernetes#12266]
Every time I execute 

```shell
KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
``` 

And cannot pass the minion verification.

So I execute "pgrep -f kubelet", it got nothing return.
Then I found the etcd doesn't boot up also. So I try to start the etcd manualy.
First I tried "sudo service etcd start", but it seems etcd doesn't start.
Then I tried "sudo systemctl enable etcd", then got a error 

```
Synchronizing state for etcd.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d etcd defaults
Executing /usr/sbin/update-rc.d etcd enable
update-rc.d: error: etcd Default-Start contains no runlevels, aborting.  
```

Is there any wrong with the etcd init script on ubuntu?

**Comment by kgrvamsi** [comment]
With what user you are trying to run the setup as?

**Comment by dchen1107** [comment]
Are you trying to deploy kubernetes on bare-metal ubuntu machines?

**Comment by mikedanese** [comment]
@WIZARD-CXY

**Comment by dchen1107** [comment]
For etcd issue, I think it might be fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/11559

**Comment by WIZARD-CXY** [comment]
Ubuntu 15.04 do not use upstart jobs.So I recommend you use docker approach, you know, it can run where docker can run, and it is good also.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker-multinode.md

**Comment by asdfsx** [comment]
I want to setup it on bare-metal ubuntu machines!
And thx WIZARD-CXY, I'll try that
