### ISSUE TITLE
E2E test is not setting the EndpointSlices conditions to ready

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#122623]
The test create custome EndpointSlices to validate some behaviors sending traffic, so it is clear that it expects the EndpointSlices to be ready, 

https://github.com/kubernetes/kubernetes/blob/b529e6ff1c7edb3bb1eaca185b9662d8e42ac2d0/test/e2e/network/endpointslice.go#L698-L712

The API doc is vague about this situation and leaves room to interpret the "unknown behavior", quoting @danwinship

> I was going to say that the API docs say that Ready: nil means it is ready, but actually it says "A nil value indicates an unknown state. In most cases consumers should interpret this unknown state as ready". FTR, kube-proxy interprets nil as true for Ready and Serving, and false for Terminating. It's possible we should update the API docs to make that official. Or if not, probably we should change the e2e tests to not rely on undefined values

Since the test expects the EndpointSlices to be Ready we should set them, if we decide to change the API behavior, then we should add an additional e2e test to validate this behavior, but not use the same test to validate two different things

/kind bug
/kind failing-testing
/sig network

Slack thread https://kubernetes.slack.com/archives/C09QYUH5W/p1704500806325289

**Comment by aauren** [comment]
Thanks @aojea! I'll take this one and draft up a PR this weekend. (this comment should hopefully allow the k8s ci robot to assign this to me as well)

**Comment by aojea** [comment]
> Thanks @aojea! I'll take this one and draft up a PR this weekend. (this comment should hopefully allow the k8s ci robot to assign this to me as well)

if you are planning to contribute more often you should apply as org member https://github.com/kubernetes/community/blob/master/community-membership.md
