### ISSUE TITLE
Kubernetes Scheduling Framework, "kubernetes-sigs/scheduler-plugins" [Warnings] for "./hack/update-codegen.sh"

### ISSUE THREAD

**Issue by Hemang70** [kubernetes/kubernetes#122621]
### What happened?

I am trying to create a new plugin for "kubernetes-sigs/scheduler-plugins" using links

https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/develop.md
https://github.com/wangchen615/scheduler-plugins/tree/kubecon22/pkg/scorebylabel
But getting following Warnings for command ./hack/update-codegen.sh

Warnings:
Generating deepcopy funcs
Generating defaulters
Generating conversions
WARNING: generate-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.

WARNING: Specifying "all" as a generator is deprecated.
WARNING: Please list the specific generators needed.
WARNING: "all" is now an alias for "applyconfiguration,client,deepcopy,informer,lister"; new code generators WILL NOT be added to this set

WARNING: generate-internal-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.

Generating deepcopy funcs
Generating apply configuration for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/applyconfiguration
Generating clientset for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/clientset
Generating listers for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/listers
Generating informers for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/informers

How to solve this?

I have added the plugin "ScoreByLabel" by referring https://github.com/wangchen615/scheduler-plugins/tree/kubecon22/pkg/scorebylabel and executed command "./hack/update-codegen.sh"

### What did you expect to happen?

Expectation was to update the generated files with functions as DeepCopy for the added structures.

### How can we reproduce it (as minimally and precisely as possible)?

by: "git clone https://github.com/kubernetes-sigs/scheduler-plugins.git"
and executing command:  "./hack/update-codegen.sh"

Reference document: https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/develop.md

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Not applicable
</details>

### Cloud provider

<details>

</details>
Not applicable

### OS version

<details>
Not applicable
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> by: "git clone https://github.com/kubernetes-sigs/scheduler-plugins.git"
and executing command: "./hack/update-codegen.sh"

this is not a core kubernetes problem.
please log this issue in https://github.com/kubernetes-sigs/scheduler-plugins

/close
/sig scheduling
