### ISSUE TITLE
Why does Kubernetes use Golang more than Java?

### ISSUE THREAD

**Issue by anirudh-hegde** [kubernetes/kubernetes#122695]
![image](https://github.com/kubernetes/kubernetes/assets/105560839/932d71d6-54b4-41d5-991b-a825936c01cd)

Thanks

**Comment by AmarNathChary** [comment]
@anirudh-hegde Kubernetes is primarily implemented in the Go programming language

**Comment by anirudh-hegde** [comment]
> @anirudh-hegde Kubernetes is primarily implemented in the Go programming language

In the future, will Kubernetes use Java as the primary language

**Comment by AmarNathChary** [comment]
> In the future, will Kubernetes use Java as the primary language

Kubernetes core components are primarily written in Go due to its concurrency model, performance, and tooling. While Kubernetes is extensible, allowing developers to use various languages for applications interacting with it, contributing to the core is done in Go.
