### ISSUE TITLE
kubelet.service entered failed state  (code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by gitissuepost** [kubernetes/kubernetes#122609]
### What happened?

I had followed the steps from [install-kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) to install the tools
Enabled kubelet service, started it and checked the status
systemctl status kubelet

### What did you expect to happen?

The service should be active and running. Got below error

```
# systemctl status kubelet

● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Fri 2024-01-05 13:21:38 UTC; 6s ago
     Docs: https://kubernetes.io/docs/
  Process: 7019 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
 Main PID: 7019 (code=exited, status=1/FAILURE)

Jan 05 13:21:38 ip-10-34-114-123 systemd[1]: Unit kubelet.service entered failed state.
Jan 05 13:21:38 ip-10-34-114-123 systemd[1]: kubelet.service failed.
```

### How can we reproduce it (as minimally and precisely as possible)?

Followed the steps from [install-kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) to install the tools
Enable kubelet service, start it and check the status

System Info: Amazon Linux 2 AMI on a t3.medium instance

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"

$ uname -a
Linux ip-xx-xx-xxx-xxx 5.10.201-191.748.amzn2.x86_64 #1 SMP Mon Nov 27 18:28:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm, kubectl, kubelet, containerd, runc
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI - 1.4.0
crictl - 1.29.0
</details>

**Comment by neolit123** [comment]
the kubelet service will fail until kubeadm init/join is called.
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

>> The kubelet is now restarting every few seconds, as it waits in a crashloop for kubeadm to tell it what to do

github is not the right place for support.
please see

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
