### ISSUE TITLE
InPlacePodVerticalScaling can make node requests be over 100 percent

### ISSUE THREAD

**Issue by tonyaw** [kubernetes/kubernetes#122602]
### What happened?

Before I patch pod to enlarge CPU requests:

```
kubectl describe nodes node-x
...
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  --------           --------     ------
  cpu                4350m (13%)  5800m (18%)
  memory             6384Mi (3%)  8532Mi (5%)
  ephemeral-storage  0 (0%)       0 (0%)
  hugepages-1Gi      0 (0%)       0 (0%)
  hugepages-2Mi      0 (0%)       0 (0%)
Events:              <none>
```

Patch the pod to change CPU requests, and it is successful:
```
[root@node-x test]# kubectl patch pod tonyaw-pod2 --patch '{"spec":{"containers":[{"name":"test","resources":{"limits":{"cpu":"31000m"}, "requests":{"cpu":"30000m"}}}]}}'
pod/tonyaw-pod2 patched
[root@node-x test]#
```

node request is over 100%:
```
kubectl describe nodes node-x
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests       Limits
  --------           --------       ------
  # tonyaw: requests is over 100%
  cpu                33850m (105%)  36 (112%)
  memory             6384Mi (3%)    8532Mi (5%)
  ephemeral-storage  0 (0%)         0 (0%)
  hugepages-1Gi      0 (0%)         0 (0%)
  hugepages-2Mi      0 (0%)         0 (0%)
Events:              <none>
```

If I use same CPU request to recreate this pod, it will fail because of lacking of resource:
```
Warning  FailedScheduling  43s   default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```

### What did you expect to happen?

Patch to change resources shall be failed.

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod, and patch its CPU request to over the total request of node.

### Kubernetes version

<details>

```console
kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
```

</details>

### Cloud provider

<details>
local server
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Ithrael** [comment]
I can't reopen this issue.
![image](https://github.com/kubernetes/kubernetes/assets/38208715/8450a5c2-9976-4a34-a5bc-635cc4950492)
Can you modify a pod's resources using patch?

我是minikube 1.29.0
![image](https://github.com/kubernetes/kubernetes/assets/38208715/898ae9f9-d48d-40d4-af7a-e2bfc31d709e)

**Comment by kannon92** [comment]
You probably need the feature toggle turned on.

**Comment by sftim** [comment]
> Patch to change resources shall be failed.

We should define what we expect to happen. There are two outcomes I could imagine:
1. reject the patch
2. accept the patch provided that there is a lower-priority Pod where preempting it would satisfy the new request, and then:
   - find another Pod to preempt
   - preempt that other Pod
   - satisfy the vertical scaling change

I'd actually expect outcome 2. For example, if I have a high-priority static Pod, it's useful to be able to give it more resources. I could talk to the control plane to evict another Pod, but:
 - the scheduler will use the spare capacity as soon as it's available &mdash; that's kind of its role in life
 - what if the API server is degraded and the vertical scaling is an attempt to fix this?

Even if in-place Pod vertical scaling doesn't support static Pods today, we should consider a future where it might, and make sure the design accounts for it.

If folks agree with my thinking here, the bug might not be that node requests can exceed 100%, it's that the kubelet isn't doing the preemption I'd expect as early as I'd hope it to.

**Comment by tonyaw** [comment]
@sftim , if there is no lower-priority pod, I assume one pod with same priority will be preempted randomly. Right?
In my product environment, actually we don't use pod priority feature. It means all the pods have same priority.
If we go to option2, other pod on same node will be preempted unintentionally.

Is it possible to combine both option1 and option2 at same time:
1. First time, go with option1 to reject the patch.
2. Second time, a "--force" option can be set. It means user knows preemption will happen, and go to option2 sounds more reasonable.

**Comment by sftim** [comment]
> If there is no lower-priority pod, I assume one pod with same priority will be preempted randomly. Right?

Let's say the node has 7 pods at priority 123456 (all the same). Node overhead is 1 CPU, each Pod requests 1 vCPU, there are 8 CPUs. You also have plenty of memory.

Now, someone tries to scale one of those Pods, in-place, to request 4 vCPU. You're positing that another same-priority Pod gets preempted.

The options I'd support are:
1. randomly select a same-priority Pod, preempt that selected other Pod, do the vertical scaling
1. reject the vertical scaling request

I don't have a strong opinion about which of those is better.
My soft opinion is to reject the vertical scaling request. There could be an API mechanism to allow forcing the preemption; if we add that support, I expect it wouldn't turn up until late in the beta phase.

**Comment by tonyaw** [comment]
> I don't have a strong opinion about which of those is better. My soft opinion is to reject the vertical scaling request. There could be an API mechanism to allow forcing the preemption; if we add that support, I expect it wouldn't turn up until late in the beta phase.
I vote the following solution as I mentioned in previous message:
1. If user doesn't provide "--force" option, reject the vertical scaling request.
2. If user provides a "--force" option, preempt lower priority pod, or a same priority pod randomly.

**Comment by haircommander** [comment]
/assign @tzneal 
/triage accepted

This may actually be an issue with the client reporting reqeust rather than actual allocated values. @tzneal is going to investigate

**Comment by haircommander** [comment]
probably something to look at for beta https://github.com/kubernetes/enhancements/issues/1287

**Comment by tzneal** [comment]
What does the pod status look like in this case? Specifically interested in the pod.status.resize field.

**Comment by thockin** [comment]
This is what "Deferred" and "Infeasible" are for in `Pod.status.resize` is for - the request itself is valid (structurally and syntactically) and was passed on to kubelet.  Kubelet can decide whether to do an eviction or just wait for some other pods to exit or just say no.

**Comment by thockin** [comment]
This seems like WAI unless status is broken?
