### ISSUE TITLE
 Kube-scheduler High Memory usage

### ISSUE THREAD

**Issue by klllmxx** [kubernetes/kubernetes#122661]
### What happened?

When I was patrolling the kubernetes cluster, I found that the Pod memory usage of the kube scheduler on a node was abnormal. The following are the resource usage and log outputs：
Logs:
[root@lb ~]# kubectl logs -f -n kube-system kube-scheduler-k8s-master-03
I0910 13:47:01.536621       1 serving.go:348] Generated self-signed cert in-memory
W0910 13:47:03.253799       1 requestheader_controller.go:193] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
W0910 13:47:03.253828       1 authentication.go:368] Error looking up in-cluster authentication configuration: configmaps "extension-apiserver-authentication" is forbidden: User "system:kube-scheduler" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
W0910 13:47:03.253841       1 authentication.go:369] Continuing without authentication configuration. This may treat all requests as anonymous.
W0910 13:47:03.253853       1 authentication.go:370] To require authentication configuration lookup to succeed, set --authentication-tolerate-lookup-failure=false
I0910 13:47:03.307574       1 server.go:154] "Starting Kubernetes Scheduler" version="v1.28.1"
I0910 13:47:03.307597       1 server.go:156] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I0910 13:47:03.311804       1 secure_serving.go:210] Serving securely on 127.0.0.1:10259
I0910 13:47:03.313958       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0910 13:47:03.314014       1 configmap_cafile_content.go:202] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I0910 13:47:03.314028       1 shared_informer.go:311] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0910 13:47:03.414494       1 shared_informer.go:318] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0910 13:47:03.414543       1 leaderelection.go:250] attempting to acquire leader lease kube-system/kube-scheduler...
I1221 06:22:01.501294       1 leaderelection.go:260] successfully acquired lease kube-system/kube-scheduler
Resouces:
[root@lb ~]# kubectl top po -n kube-system |grep sch
kube-scheduler-k8s-master-01            1m           31Mi            
kube-scheduler-k8s-master-02            0m           29Mi            
kube-scheduler-k8s-master-03            76m          3450Mi

### What did you expect to happen?

How can I solve my abnormal memory usage situation and seek a solution

### How can we reproduce it (as minimally and precisely as possible)?

![ee91b3fe0610869118c6f6d3010af24](https://github.com/kubernetes/kubernetes/assets/87749576/886ccf51-0b08-4c99-a781-a53de7c00766)
![Uploading 1704816893072.png…]()

### Kubernetes version

Kubernetes: 1.28.1
kubeadm: 1.28.1
kubelet: 1.28.1

### Cloud provider

N/A

### OS version

os:  CentOS Linux release 7.9.2009 (Core)

kernel：3.10.0-1160.76.1.el7.x86_64

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

[root@lb ~]# crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  1.6.22
RuntimeApiVersion:  v1

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ingvagabund** [comment]
We are experiencing a memory usage build up as well. Did some simple pprof check and one of the places where the memory build up is reported is:
```
(pprof) list FieldsV1\).Unmarshal
Total: 867.55MB
ROUTINE ======================== k8s.io/apimachinery/pkg/apis/meta/v1.(*FieldsV1).Unmarshal in vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  140.24MB   140.24MB (flat, cum) 16.17% of Total
         .          .   6447:func (m *FieldsV1) Unmarshal(dAtA []byte) error {
         .          .   6448:	l := len(dAtA)
         .          .   6449:	iNdEx := 0
         .          .   6450:	for iNdEx < l {
...
         .          .   6502:			if postIndex > l {
         .          .   6503:				return io.ErrUnexpectedEOF
         .          .   6504:			}
  140.24MB   140.24MB   6505:			m.Raw = append(m.Raw[:0], dAtA[iNdEx:postIndex]...)
         .          .   6506:			if m.Raw == nil {
         .          .   6507:				m.Raw = []byte{}
         .          .   6508:			}
         .          .   6509:			iNdEx = postIndex
         .          .   6510:		default:
```
After ~ a day after:
```
         .          .   6502:			if postIndex > l {
         .          .   6503:				return io.ErrUnexpectedEOF
         .          .   6504:			}
  968.78MB   968.78MB   6505:			m.Raw = append(m.Raw[:0], dAtA[iNdEx:postIndex]...)
         .          .   6506:			if m.Raw == nil {
         .          .   6507:				m.Raw = []byte{}
         .          .   6508:			}
```
Not that much experienced with memory usage debugging using pprof. Any tips how to figure out whether the append line is the culprit?

**Comment by ingvagabund** [comment]
Checking inuse_objects:
```
k8s.io/apimachinery/pkg/apis/meta/v1.(*FieldsV1).Unmarshal
vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go

  Total:      309611     309611 (flat, cum)  2.62%
   6502            .          .           			if postIndex > l { 
   6503            .          .           				return io.ErrUnexpectedEOF 
   6504            .          .           			} 
   6505       309611     309611           			m.Raw = append(m.Raw[:0], dAtA[iNdEx:postIndex]...) 
   6506            .          .           			if m.Raw == nil { 
   6507            .          .           				m.Raw = []byte{} 
   6508            .          .           			} 
```
After ~a day:
```
k8s.io/apimachinery/pkg/apis/meta/v1.(*FieldsV1).Unmarshal
vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go

  Total:     2069705    2069705 (flat, cum)  2.49%
   6502            .          .           			if postIndex > l { 
   6503            .          .           				return io.ErrUnexpectedEOF 
   6504            .          .           			} 
   6505      2069705    2069705           			m.Raw = append(m.Raw[:0], dAtA[iNdEx:postIndex]...) 
   6506            .          .           			if m.Raw == nil { 
   6507            .          .           				m.Raw = []byte{} 
   6508            .          .           			} 
```

https://go101.org/article/memory-leaking.html provides some tips on how to create a memory leak.

`(*FieldsV1).Unmarshal` code has not changed for the last 5 years. Could the golang version be the culprit here?

**Comment by ingvagabund** [comment]
@kannon92 have you had a chance to dig deeper into the heap profile? I suspect `dAtA` does not get properly deallocated somewhere.

**Comment by ingvagabund** [comment]
@xuqin1019 have you had a chance to dig deeper into the heap profile? I suspect `dAtA` does not get properly deallocated somewhere.

**Comment by kannon92** [comment]
I asked if someone in sig-scheduling slack could look into this issue.

**Comment by sanposhiho** [comment]
This is a known issue, and we changed the caused feature gate back to 'disable by default' already.
Please try out the latest patch release of v1.28 or v1.29.

**Comment by sanposhiho** [comment]
Or you can explicitly disable the feature gate `SchedulerQueueingHints` if you're not able to upgrade the version soon.

**Comment by xuqin1019** [comment]
> @xuqin1019 have you had a chance to dig deeper into the heap profile? I suspect `dAtA` does not get properly deallocated somewhere.

below is my heap profile analysis, the top 2 is (*ObjectMeta).Unmarshal and (*FieldsV1).Unmarshal

(pprof) top 20
```
Showing nodes accounting for 21.63GB, 93.11% of 23.23GB total
Dropped 390 nodes (cum <= 0.12GB)
Showing top 20 nodes out of 62
      flat  flat%   sum%        cum   cum%
    5.46GB 23.48% 23.48%     5.46GB 23.48%  k8s.io/apimachinery/pkg/apis/meta/v1.(*FieldsV1).Unmarshal
    4.54GB 19.53% 43.01%    10.33GB 44.47%  k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).Unmarshal
    2.62GB 11.28% 54.29%     5.68GB 24.45%  k8s.io/api/core/v1.(*Container).Unmarshal
    2.33GB 10.03% 64.31%    10.42GB 44.83%  k8s.io/api/core/v1.(*PodSpec).Unmarshal
    1.10GB  4.75% 69.06%     1.67GB  7.17%  k8s.io/api/core/v1.(*EnvVar).Unmarshal
    0.97GB  4.16% 73.22%     0.98GB  4.22%  k8s.io/api/core/v1.(*ResourceRequirements).Unmarshal
    0.83GB  3.56% 76.78%     0.83GB  3.56%  reflect.New
    0.78GB  3.37% 80.15%     1.06GB  4.57%  k8s.io/api/core/v1.(*PodStatus).Unmarshal
    0.65GB  2.78% 82.93%     0.65GB  2.81%  k8s.io/apimachinery/pkg/apis/meta/v1.(*LabelSelector).Unmarshal
    0.29GB  1.24% 84.17%     0.29GB  1.24%  k8s.io/api/core/v1.(*FlexVolumeSource).Unmarshal
    0.28GB  1.22% 85.39%     0.56GB  2.42%  k8s.io/api/core/v1.(*EnvVarSource).Unmarshal
    0.27GB  1.15% 86.53%     5.72GB 24.63%  k8s.io/apimachinery/pkg/apis/meta/v1.(*ManagedFieldsEntry).Unmarshal
    0.25GB  1.08% 87.61%     0.71GB  3.06%  k8s.io/api/core/v1.(*VolumeSource).Unmarshal
    0.23GB  1.01% 88.62%     0.23GB  1.01%  k8s.io/api/core/v1.(*ObjectFieldSelector).Unmarshal
    0.20GB  0.84% 89.46%     0.20GB  0.84%  k8s.io/api/core/v1.(*VolumeMount).Unmarshal
    0.18GB  0.79% 90.26%     0.18GB  0.79%  k8s.io/api/core/v1.(*NodeSelectorRequirement).Unmarshal
    0.18GB  0.76% 91.02%     0.38GB  1.64%  k8s.io/api/core/v1.(*NodeStatus).Unmarshal
    0.16GB  0.71% 91.72%     0.16GB  0.71%  k8s.io/api/core/v1.(*Toleration).Unmarshal
    0.16GB   0.7% 92.43%     0.35GB  1.50%  k8s.io/api/core/v1.(*NodeSelectorTerm).Unmarshal
    0.16GB  0.69% 93.11%     0.16GB  0.69%  k8s.io/api/core/v1.(*ContainerImage).Unmarshal
```

list FieldsV1\).Unmarshal
```
         .          .   6500:				return ErrInvalidLengthGenerated
         .          .   6501:			}
         .          .   6502:			if postIndex > l {
         .          .   6503:				return io.ErrUnexpectedEOF
         .          .   6504:			}
    5.46GB     5.46GB   6505:			m.Raw = append(m.Raw[:0], dAtA[iNdEx:postIndex]...)
         .          .   6506:			if m.Raw == nil {
         .          .   6507:				m.Raw = []byte{}
         .          .   6508:			}
         .          .   6509:			iNdEx = postIndex
         .          .   6510:		default:
```

list ObjectMeta\).Unmarshal
```
         .          .   9266:				return ErrInvalidLengthGenerated
         .          .   9267:			}
         .          .   9268:			if postIndex > l {
         .          .   9269:				return io.ErrUnexpectedEOF
         .          .   9270:			}
  400.75MB   400.75MB   9271:			m.ManagedFields = append(m.ManagedFields, ManagedFieldsEntry{})
         .     5.72GB   9272:			if err := m.ManagedFields[len(m.ManagedFields)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
         .          .   9273:				return err
         .          .   9274:			}
         .          .   9275:			iNdEx = postIndex
         .          .   9276:		default:
         .          .   9277:			iNdEx = preIndex
```

**Comment by xuqin1019** [comment]
> I think this is a known issue, and we changed the feature gate causing this back to 'disable by default' already. Please try out the latest patch release of v1.28 or v1.29 and check if it resolves the issue.

@sanposhiho, 
thx, where is the known issue being tracked, and could you please specify which commit resolves this known issue?

**Comment by sanposhiho** [comment]
- Issue tracking this particular issue: https://github.com/kubernetes/kubernetes/issues/120622
- PR to change the default value of feature gate: https://github.com/kubernetes/kubernetes/pull/122289
  - General tracking issue to re-enable the feature gate by default again: https://github.com/kubernetes/kubernetes/issues/122597

**Comment by xuqin1019** [comment]
> * Issue tracking this particular issue: [scheduler: handle in-flight Pods with less memory #120622](https://github.com/kubernetes/kubernetes/issues/120622)
> * PR to change the default value of feature gate: [fix: disable SchedulerQueueingHints feature flag by default #122289](https://github.com/kubernetes/kubernetes/pull/122289)
>   
>   * General tracking issue to re-enable the feature gate by default again: [Beta requirement: QueueingHint #122597](https://github.com/kubernetes/kubernetes/issues/122597)

Thanks, we will backport this temporary fix and try out in our clusters to see if it fixes the issue.

**Comment by xuqin1019** [comment]
@sanposhiho 

After backporting the fix to disable the feature gate for QueueingHints, I could see the memory keeps stable now. 

![image](https://github.com/kubernetes/kubernetes/assets/95034/7097fdf7-be3c-429b-9a5d-02efacf88ee7)

**Comment by sanposhiho** [comment]
Perfect, then can we close this issue as we have another issue to track this problem?

**Comment by xuqin1019** [comment]
> Perfect, then can we close this issue as we have another issue to track this problem?

I think so, we need another issue to track why the memory is leak in QueueingHint feature.

**Comment by sanposhiho** [comment]
Yep.

/close

**Comment by ingvagabund** [comment]
Thanks for all the pointers and help!!!

**Comment by klllmxx** [comment]
ok thanks all guys for help me,thank you! but I fixed checked this one by 1 weeks ago cause from apiserver configuration file not good ，problem from etcd……umm actually higher used memory form every modules by kubernetes sometimes ,that’s is problem ,generally good kubernetes🎉🎉🎉



From iPhone 13 Pro


------------------ Original ------------------
From: Jan Chaloupka ***@***.***&gt;
Date: Wed,Jan 17,2024 4:35 PM
To: kubernetes/kubernetes ***@***.***&gt;
Cc: klllmxx ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [kubernetes/kubernetes]  Kube-scheduler High Memory usage (Issue#122661)





 
Thanks for all the pointers and help!!!
