### ISSUE TITLE
Usage of backwards compatibility in Docker API

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#12263]
It turns out that [`dockertools.runContainer()`](https://github.com/GoogleCloudPlatform/kubernetes/blob/28b9ebed47b5ec0524d01e00be3505eab27575c9/pkg/kubelet/dockertools/manager.go#L583-L664) relies on a backwards compatibility feature in Docker API, which essentially allows one to pass `HostConfig` attribute to `/containers/:id/start` endpoint.

**Comment by dchen1107** [comment]
This issue was addressed for 1.2. Closing it.
