### ISSUE TITLE
Custom CIDR for control and data planes

### ISSUE THREAD

**Issue by rgherta** [kubernetes/kubernetes#122746]
Hey guys

I am referencing here this issue
https://github.com/kubernetes/kubeadm/issues/2993

My question is the following: in enteprise environments control plane and data plane nodes need to be on separate subnets and sometimes the interaction with control plane handled via a dns... my question is whether kube-controller-manager can handle 2 cidrs for control planme and data plane...

In environments that are focused around perimeter based security this is a requirement and I noticed some managed cloud services like eks and gke proceed exactly like that.... I would expect kube-controller-manager to support 2 arguments for control plane cidr and data plane cidr......

Thank you in advance.

**Comment by neolit123** [comment]
/kind feature
please include more details in the issue description instead of linking to the other ticket. copy-paste, maybe.

**Comment by rgherta** [comment]
> /kind feature please include more details in the issue description instead of linking to the other ticket. copy-paste, maybe.

updated the issue description

**Comment by rgherta** [comment]
Kube controller manager splits the podcidr into smaller ranges, it makes no assumption about the nodes which should be already provisioned ... Ok, I will close this, I realize it just now...

**Comment by rgherta** [comment]
> @rgherta see if this projects can suit your needs https://github.com/kubernetes-sigs/node-ipam-controller

Hi Antonio, I guess the issue still stands in the sence that you might have pods on the control plane (ie coredns) witing the same cidr as other pods... I will check the ipam controller, thank you!
