### ISSUE TITLE
kube-up.sh with aws and coreos

### ISSUE THREAD

**Issue by erikthorselius** [kubernetes/kubernetes#12273]
Hi, when I'm trying to run kube-up.sh with aws and coreos i get 

```
Attempt 1 to check for SSH to master [ssh to master not working yet]
Attempt 2 to check for SSH to master [ssh to master working]
Attempt 1 to check for salt-master [salt-master not working yet]
Attempt 2 to check for salt-master [salt-master not working yet]
Attempt 3 to check for salt-master [salt-master not working yet]
Attempt 4 to check for salt-master [salt-master not working yet]
Attempt 5 to check for salt-master [salt-master not working yet]
Attempt 6 to check for salt-master [salt-master not working yet]
Attempt 7 to check for salt-master [salt-master not working yet]
Attempt 8 to check for salt-master [salt-master running]
Creating minion configuration
./../cluster/aws/../../cluster/../cluster/aws/coreos/util.sh: line 32: $1: unbound variable
```

And when I'm looking at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/aws/util.sh#L945 it looks like it don't sends any arguments.

I'm on mac os x, the config I use is

``` shell
export KUBE_AWS_ZONE=eu-west-1a
export AWS_S3_REGION=eu-west-1
export AWS_REGION=eu-west-1
export MASTER_SIZE=c4.large
export MINION_SIZE=r3.large
export KUBE_OS_DISTRIBUTION=coreos
export KUBERNETES_PROVIDER=aws
```

**Comment by dchen1107** [comment]
cc/ @justinsb and @bakins

**Comment by sarath** [comment]
surprisingly this is not voted too much? I think this would be considered a blocker/ Is there a workaround?

**Comment by dchen1107** [comment]
cc/ @yifan-gu, @kelseyhightower for coreos on aws. Thanks!

**Comment by joshm1** [comment]
This is a duplicate of #11975 which has a "potential" workaround of just removing the lines, but I'm not sure if that causes other issues. I did this myself but had issues with multi-minion service discovery/DNS not working and none of the kube-system services working from the master public IP nor `kubectl proxy`

**Comment by mbforbes** [comment]
Closing as dupe of #11975 — please yell if this is not the case!

**Comment by sarath** [comment]
Wait a min! this is NOT a duplicate. The generate-minion-user-data function in aws/coreos/util.sh requires an argument. 
in the below commit, the argument was removed from aws/ubuntu/util.sh 
https://github.com/kubernetes/kubernetes/commit/2a5ed2f0869f2bb7e2939cfc897f295983176032

thats what is breaking this.

**Comment by mbforbes** [comment]
ping @justinsb

**Comment by justinsb** [comment]
Looking at this now

**Comment by roberthbailey** [comment]
@justinsb Any updates?

**Comment by drora** [comment]
+1

**Comment by ericfode** [comment]
+1

**Comment by akranga** [comment]
+1

**Comment by theo01** [comment]
+1

**Comment by mward29** [comment]
+1

**Comment by vyshane** [comment]
+1

**Comment by SpencerBrown** [comment]
+1

**Comment by jonbaierCTP** [comment]
+1

**Comment by mettjus** [comment]
+1

**Comment by four43** [comment]
Just ran into this issue still on 1.0.7 "production"

**Comment by jetole** [comment]
Also just ran into this issue still on 1.0.7 "production".

**Comment by dhart-alldigital** [comment]
+1 blocker

**Comment by arkkanoid** [comment]
+1

**Comment by lordkada** [comment]
+1

**Comment by jakubkulhan** [comment]
+1

**Comment by yifan-gu** [comment]
FWIW, kube-up with gce coreos is WIP https://github.com/kubernetes/kubernetes/pull/17243

**Comment by justinsb** [comment]
We're not going to making further changes in kube-up.  Solutions for CoreOS are kube-aws, kubeadm, and likely kops soon (see https://github.com/kubernetes/kops/pull/854).  Closing.
