### ISSUE TITLE
[Failing Test] ci-kubernetes-kubemark-500-gce failed after change the machine type

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#122722]
### Which jobs are flaking?

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce?buildId=1743193497881546752

### Which tests are flaking?

```
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - Setting minimum CPU platform is not supported for the selected machine type e2-standard-16.
Failed to create master instance due to non-retryable error
```

### Since when has it been flaking?

after https://github.com/kubernetes/kubernetes/pull/118626/ was merged
@upodroid 

### Testgrid link

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce?buildId=1743193497881546752

### Reason for failure (if possible)

It seems to be related to the machine type.

### Anything else we need to know?

/cc @dims @ameukam 

### Relevant SIG(s)

/sig scalability k8s-infra

**Comment by upodroid** [comment]
I'll fix this now
