### ISSUE TITLE
kube-scheduler memory leak issue in v1.28.3

### ISSUE THREAD

**Issue by xuqin1019** [kubernetes/kubernetes#122725]
### What happened?

We have identified a memory leak issue in kube-scheduler after upgrading to version v1.28.3. Despite a stable number of pods/nodes, we have noticed a continuous increase in kube-scheduler memory usage over time.

![image](https://github.com/kubernetes/kubernetes/assets/95034/4f363977-720f-468a-860f-833fb4ee4059)

Upon analyzing the pprof dump, it was observed that a significant portion of the memory is consumed by watch.(*StreamWatcher).receive

![image](https://github.com/kubernetes/kubernetes/assets/95034/73508580-5403-4480-832f-c6182f9f0d0a)

![image](https://github.com/kubernetes/kubernetes/assets/95034/7b8ed04d-6253-4d33-8263-303592bf24bc)

[profile.pb.gz](https://github.com/kubernetes/kubernetes/files/13916077/profile.pb.gz)

### What did you expect to happen?

The kube-scheduler(v1.28.3)memory usage is expected to keep stable

### How can we reproduce it (as minimally and precisely as possible)?

Using the script below to scale out/in pods, we should see the memory leak issue

```
for (( ; ; ))
do
    kubectl scale deployment nginx-deployment --replicas=0 
    sleep 60
    kubectl scale deployment nginx-deployment --replicas=30
    sleep 120
done
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-1", GitCommit:"d0509afab1df7f17cc670b6c617b3d747da6e207", GitTreeState:"clean", BuildDate:"2020-11-11T12:27:59Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.3-2-rc2-apiserver-compatiable-all-01", GitCommit:"c2078abccc565d633be3a31da29c9f8d683f8327", GitTreeState:"clean", BuildDate:"2023-12-27T08:36:21Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux VMS48219 4.14.67-2dev917.el7.x86_64 #1 SMP Sun Sep 16 19:46:27 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kannon92** [comment]
duplicated of https://github.com/kubernetes/kubernetes/issues/122661

Same k8s version.

/close
