### ISSUE TITLE
[Flaking Test] [sig-node] gce-cos-master-alpha-features failed for EventedPLEG

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#122721]
### Which jobs are failing?

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features is breaked 
- Flaking rate is higher than 50%.

### Which tests are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1745617205501890560

### Since when has it been failing?

After https://github.com/kubernetes/kubernetes/pull/122697 is merged.

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features

### Reason for failure (if possible)

EventedPLEG has a known issue: https://github.com/kubernetes/kubernetes/issues/121349, and it will cause static pod startup failure(most time)

### Anything else we need to know?

~~https://github.com/kubernetes/kubernetes/pull/122124~~
#122763 is a potienial fix but not complete yet.

### Relevant SIG(s)

/sig node

**Comment by aojea** [comment]
Assigning the feature owners https://github.com/kubernetes/kubernetes/pull/111384

/assign @harche @derekwaynecarr

**Comment by harche** [comment]
Thanks @pacoxu for fixit it https://github.com/kubernetes/kubernetes/pull/122763#issuecomment-1892234737

**Comment by p0lyn0mial** [comment]
@pacoxu is it also going to fix `pull-kubernetes-e2e-gce-cos-alpha-features` ? It also seems to be[ constantly failing](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-cos-alpha-features?buildId=).

**Comment by harche** [comment]
@p0lyn0mial triggered it, https://github.com/kubernetes/kubernetes/pull/122763#issuecomment-1892727660

**Comment by p0lyn0mial** [comment]
@pacoxu @harche it looks like finding and merging a fix might take some time. Have you considered reverting the changes that introduced the issue?

**Comment by pacoxu** [comment]
> @pacoxu @harche it looks like finding and merging a fix might take some time. Have you considered reverting the changes that introduced the issue?

evented pleg is reverted from beta to alpha recently
Do you mean revert the feature which is introduced since 1.27？

**Comment by pacoxu** [comment]
The pr in review can fix this failure, but it needs more review.

**Comment by p0lyn0mial** [comment]
`pull-kubernetes-e2e-gce-cos-alpha-features` [is constantly failing](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-cos-alpha-features?buildId=). In the past it was fine, something broke it around 11th of January. Maybe not everything was reverted ? Is there a way to disable the alpha feature you mentioned from the `*-alpha-features` jobs ? (you could reenable it once you know it works).

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/122697 revert the evented pleg from beta to alpha. This CI only enables all alpha feature gates. Before the 122697, the feature is beta and by default disabled, so the feature did not fail this alpha CI at that time.

After the revert, it is an alpha feature gate and will be enabled in this Alpha CI and it started to fail.

**Comment by p0lyn0mial** [comment]
Since it is failing in alpha, would you consider disabling the feature altogether ? I think it boils down to setting `--env=KUBE_FEATURE_GATES=AllAlpha=true,YOUR_FEATURE=false` in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L400 (and similarly for the other jobs).

**Comment by pacoxu** [comment]
> Since it is failing in alpha, would you consider disabling the feature altogether ? I think it boils down to setting `--env=KUBE_FEATURE_GATES=AllAlpha=true,YOUR_FEATURE=false` in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L400 (and similarly for the other jobs).

This is a solution to fix the CI as well. 

 - Pros to disable it:
   - gce-cos-master-alpha-features is one CI of master blocking board
   - gce-cos-master-alpha-features failed for EventedPLEG only
   - there is still discussion in the PR, and no clear timeline
 - Cons:
   - gce-cos-master-alpha-features flakes and can pass with retry (passing rate is about ~40% according to the testgrid.)
   - PR is almost done and waiting for more reviews and approval
   - we have to revert the test-infra change once EventedPLEG bug is fixed.

@harche @aojea @smarterclayton what's your idea?

**Comment by harche** [comment]
IMHO, considering we do not have a timeline, it may not be a bad idea to omit the Evented PLEG feature from alpha features job temporarily to unblock everyone else.

**Comment by pacoxu** [comment]
I opened https://github.com/kubernetes/test-infra/pull/31647.

In https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-cos-alpha-features,
we can see some PR want to run those alpha features CI, and now failed for the bug.
- https://github.com/kubernetes/kubernetes/pull/122791 
- https://github.com/kubernetes/kubernetes/pull/122701

**Comment by aojea** [comment]
@pacoxu what issue do we want to keep open tro track this?

**Comment by pacoxu** [comment]
> Reference

In https://github.com/kubernetes/test-infra/pull/31647, I only disabled evented pleg for presubmit CI jobs. 

The master blocking board is still failing(flaking in high rate). We still need to fix it in a high priority.

**Comment by harche** [comment]
@pacoxu while we still trying to tweak Generic PLEG to exhibit similar behaviour, if we gate all changes to Evented PLEG only then we can merge the PR as it doesn't alter anything when regular Generic PLEG is in action. 

https://github.com/kubernetes/kubernetes/pull/122778/files#r1459564818

**Comment by harche** [comment]
> @pacoxu while we still trying to tweak Generic PLEG to exhibit similar behaviour, if we gate all changes to Evented PLEG only then we can merge the PR as it doesn't alter anything when regular Generic PLEG is in action.
> 
> https://github.com/kubernetes/kubernetes/pull/122778/files#r1459564818

No luck yet keeping the cluster steady while messing around with Generic PLEG to reproduce the issue. 

cc @sairameshv

**Comment by harche** [comment]
I am trying to see why do we need to restart the container if it is in created state even in case of Generic PLEG? what happens if you make the change in this PR for `ContainerStateCreated` also applicable to the Generic PLEG?

https://github.com/kubernetes/kubernetes/pull/122737/files#diff-cb70f01a3ac982d9bd1fda913788b2ef7d9862cf6392204f6db00f3cb2292813R90

**Comment by harche** [comment]
> I am trying to see why do we need to restart the container if it is in created state even in case of Generic PLEG? what happens if you make the change in this PR for `ContainerStateCreated` also applicable to the Generic PLEG?
> 
> https://github.com/kubernetes/kubernetes/pull/122737/files#diff-cb70f01a3ac982d9bd1fda913788b2ef7d9862cf6392204f6db00f3cb2292813R90

Looks like it was introduced with this PR - 
https://github.com/kubernetes/kubernetes/commit/9fa1ad29fd4df650f451522970908869b8199bf3

But I am not sure if this assumption, https://github.com/kubernetes/kubernetes/commit/9fa1ad29fd4df650f451522970908869b8199bf3#diff-e81aa7518bebe9f4412cb375a9008b3481b19ec3e851d3187b3021ee94148f0dR1214-R1219 is true. 

In the kubelet you can clearly see [create container](https://github.com/kubernetes/kubernetes/blob/c55848a7246a0283be9b78c1b15bbeb922662a17/pkg/kubelet/kuberuntime/kuberuntime_container.go#L254) and [start container](https://github.com/kubernetes/kubernetes/blob/c55848a7246a0283be9b78c1b15bbeb922662a17/pkg/kubelet/kuberuntime/kuberuntime_container.go#L268) are two distinct steps.

**Comment by pacoxu** [comment]
As we disabled it in CI,  the CI is not flaing for this. Let's discuss it in a straightforward issue.

**Comment by pacoxu** [comment]
> As we disabled it in CI, the CI is not flaing for this. Let's discuss it in a straightforward issue.

@harche I add all related context in https://github.com/kubernetes/kubernetes/issues/123087.
