### ISSUE TITLE
Watch-List feature does not work as expected when ResourceVersion is not set.

### ISSUE THREAD

**Issue by qwtsc** [kubernetes/kubernetes#122805]
### What happened?

Kube-apiserver with [Watch-List](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3157-watch-list#design-details) feature enabled does not send back `k8s.io/initial-events-end` BOOKMARK to client when  resourceVersion is not set.

```bash
curl 'http://localhost:8001/api/v1/namespaces/default/pods?allowWatchBookmarks=true&resourceVersionMatch=NotOlderThan&sendInitialEvents=true&timeoutSeconds=565&watch=true' -v 8
* About to connect() to localhost port 8001 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8001 (#0)
> GET /api/v1/namespaces/default/pods?allowWatchBookmarks=true&resourceVersionMatch=NotOlderThan&sendInitialEvents=true&timeoutSeconds=565&watch=true HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8001
> Accept: */*
> 
< HTTP/1.1 200 OK
< Audit-Id: 7234c88c-a068-4479-8c4e-7780d252ba66
< Cache-Control: no-cache, private
< Content-Type: application/json
< Date: Tue, 16 Jan 2024 08:25:17 GMT
< X-Kubernetes-Pf-Flowschema-Uid: c164aa1f-bd17-4fd7-8b8e-ca061207c6dc
< X-Kubernetes-Pf-Prioritylevel-Uid: 71b16c3c-cc3a-4485-adce-76c22bb29aad
< Transfer-Encoding: chunked
< 
```

and when resourceVersion is randomly set as seen in the following, the response from kube-apiserver does have the designed BOOKMARK.

```bash
curl 'http://localhost:8001/api/v1/namespaces/default/pods?allowWatchBookmarks=true&resourceVersionMatch=NotOlderThan&sendInitialEvents=true&timeoutSeconds=565&watch=true&resourceVersion=1000' -v 8
* About to connect() to localhost port 8001 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8001 (#0)
> GET /api/v1/namespaces/default/pods?allowWatchBookmarks=true&resourceVersionMatch=NotOlderThan&sendInitialEvents=true&timeoutSeconds=565&watch=true&resourceVersion=1000 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8001
> Accept: */*
> 
< HTTP/1.1 200 OK
< Audit-Id: eaf9a084-642c-444c-882f-dd2d5d4ced3d
< Cache-Control: no-cache, private
< Content-Type: application/json
< Date: Tue, 16 Jan 2024 08:25:27 GMT
< X-Kubernetes-Pf-Flowschema-Uid: c164aa1f-bd17-4fd7-8b8e-ca061207c6dc
< X-Kubernetes-Pf-Prioritylevel-Uid: 71b16c3c-cc3a-4485-adce-76c22bb29aad
< Transfer-Encoding: chunked
< 
{"type":"BOOKMARK","object":{"kind":"Pod","apiVersion":"v1","metadata":{"resourceVersion":"3089","creationTimestamp":null,"annotations":{"k8s.io/initial-events-end":"true"}},"spec":{"containers":null},"status":{}}}
```

Is this phenomenon a bug to this alpha phase [feature](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3157-watch-list#design-details) or just by design?

### What did you expect to happen?

send back  `k8s.io/initial-events-end` BOOKMARK to client as well when resource version is not set in request parameter.

### How can we reproduce it (as minimally and precisely as possible)?

use kubectl proxy to connect apiserver
```bash
kubectl proxy &
```
and then curl
```
curl 'http://localhost:8001/api/v1/namespaces/default/pods?allowWatchBookmarks=true&resourceVersionMatch=NotOlderThan&sendInitialEvents=true&timeoutSeconds=565&watch=true' -v 8
```

### Anything else we need to know?

etcd version is 3.5.11

### Kubernetes version

<details>

```console
$ kubectl version
I have tried k&k with tag of v1.28.4, v1.29.0 and master branch.
```

</details>

### Cloud provider

<details>
bare-metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by brandond** [comment]
This sounds a lot like https://github.com/kubernetes/kubernetes/issues/121688#issuecomment-1789857228 - see https://github.com/kubernetes/kubernetes/pull/115096.

Can you test with a v1.26 release and see if that has the behavior you were expecting?

**Comment by qwtsc** [comment]
Watch-List feature was introduced in v1.27, so it's meaningless to test with v1.26 release.

**Comment by qwtsc** [comment]
cc @wojtek-t @liggitt
/sig api-machinery

**Comment by brandond** [comment]
When testing this, I see that a bookmark event is sent as soon as there is any change to pods, but this does not seem like what was intended here.

For example, I see that my CURL request gets no response until I delete a pod in any namespace. As soon as I do that, I get an `initial-events-end` progress report, followed by progress reports at regular intervals after that.

```
*   Trying 127.0.0.1:8001...
* Connected to localhost (127.0.0.1) port 8001 (#0)
> GET /api/v1/namespaces/default/pods?allowWatchBookmarks=true&resourceVersionMatch=NotOlderThan&sendInitialEvents=true&timeoutSeconds=565&watch=true&resourceVersion= HTTP/1.1
> Host: localhost:8001
> User-Agent: curl/7.86.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Audit-Id: 2b5742a1-3944-40c0-b44c-088d483a1299
< Cache-Control: no-cache, private
< Content-Type: application/json
< Date: Wed, 17 Jan 2024 00:23:18 GMT
< X-Kubernetes-Pf-Flowschema-Uid: ee776534-8b4f-4046-9577-3bedfa5a391f
< X-Kubernetes-Pf-Prioritylevel-Uid: 55aef8e4-0a45-45c3-a58d-ad8d89cce662
< Transfer-Encoding: chunked
<


{"type":"BOOKMARK","object":{"kind":"Pod","apiVersion":"v1","metadata":{"resourceVersion":"2285","creationTimestamp":null,"annotations":{"k8s.io/initial-events-end":"true"}},"spec":{"containers":null},"status":{}}}
{"type":"BOOKMARK","object":{"kind":"Pod","apiVersion":"v1","metadata":{"resourceVersion":"2285","creationTimestamp":null},"spec":{"containers":null},"status":{}}}
{"type":"BOOKMARK","object":{"kind":"Pod","apiVersion":"v1","metadata":{"resourceVersion":"2285","creationTimestamp":null},"spec":{"containers":null},"status":{}}}
```

**Comment by likakuli** [comment]
I tested this in my kind env with v1.29.0. bookmark returned successfully but the bookmark has noticeable latency even there is no normal data to return. more than 1~1.25s latency. 
i have opened issue before and not sure if this cost should be reduced before beta https://github.com/kubernetes/kubernetes/issues/122277

**Comment by p0lyn0mial** [comment]
> I see that a bookmark event is sent as soon as there is any change to pods

@brandond @qwtsc could you ensure that the `etcd` binary has `experimental-watch-progress-notify-interval` flag set? 

I know that the flag name is unfortunate but IIRC the flag was promoted to `GA` in etcd `3.5`.
In addition to that the flag is also required for https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1904-efficient-watch-resumption/README.md#proposal

All GCE test set the flag to `5s` - https://github.com/kubernetes/kubernetes/blob/b1ab18ade24473630499568f6fbb73c13c93175d/cluster/gce/config-test.sh#L573

**Comment by p0lyn0mial** [comment]
> I tested this in my kind env with v1.29.0. bookmark returned successfully but the bookmark has noticeable latency even there is no normal data to return. more than 1~1.25s latency.
i have opened issue before and not sure if this cost should be reduced before beta https://github.com/kubernetes/kubernetes/issues/122277

For beta, we were planning to enable the feature only for controllers. We think that higher latency won't have a big impact on them. In general we were planing to utilise the `WatchProgressRequester` feature to decrease latency (~100ms) (https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3157-watch-list#ga)

**Comment by likakuli** [comment]
seems WatchProgressRequester is only effective for List request in current logic.

**Comment by likakuli** [comment]
> more than 1~1.25s latency.

sorry. i have confirmed the latency in my env is related to this parameter. `--experimental-watch-progress-notify-interval` which set to 5s.

**Comment by p0lyn0mial** [comment]
We were planning to advertise the feature and details in a blog post. I will check with @wojtek-t  to see if there might be a better place (i.e. KEP). Thanks for the feedback!

**Comment by wojtek-t** [comment]
We will integrate it also with "manual progress notify", but that still requires a bit of work to make it safe.
That's why the feature remains in alpha for now....

**Comment by samj1912** [comment]
Note, the blog post went out but the above frequency was not noted. Is it possible to amend the blogger post to note the etcd flag?

**Comment by p0lyn0mial** [comment]
> Note, the blog post went out (https://kubernetes.io/blog/2024/08/15/consistent-read-from-cache-beta/) but the above frequency was not noted. Is it possible to amend the blogger post to note the etcd flag?

We no longer require any specific frequency or additional flags to be set on etcd. The only requirement is that etcd is running in a supported version, as noted in the blog post. If the requirement for the etcd version is not met, the feature will be automatically turned off, and clients should fall back to a backup mechanism.

**Comment by brandond** [comment]
@p0lyn0mial can you provide a reference to the change that made the shorter interval no longer necessary? Does Kubernetes actually test with the default 10m interval? As noted above, the tests were all running with a 5s interval, and improper behavior was observed when using longer intervals.
