### ISSUE TITLE
We Should Use `PollUntilContextTimeout` Replacing Deprecated `PolImmediate` Method

### ISSUE THREAD

**Issue by daniel-hutao** [kubernetes/kubernetes#122800]
### What would you like to be added?

As described in this pr: #122708, we need to replace `PolImmediate` with `PollUntilContextTimeout`. There is also a discussion about this on [Slack](https://kubernetes.slack.com/archives/CHGFYJVAN/p1705335454294119).

However, this modification is too extensive, so we need to break it down. The purpose of this issue is to track these dispersed PRs. Once the individual PRs are merged, I will close PR #122708.

### Why is this needed?

PollUntilContextTimeout was decided to actually remove the old functions at some point.

/assign @daniel-hutao

**Comment by liangyuanpeng** [comment]
Please check https://github.com/kubernetes/kubernetes/pull/107826

We already have a few PRs working on this, and each PR only changes part of it.

@daniel-hutao

**Comment by neolit123** [comment]
see how PollUntilContextTimeout can introduce flakes under certain conditions:
- polls an API call with a propagated context
- expect a specific type of error from the poll, but instead gets unexpected "context timeout" errors

https://github.com/kubernetes/kubeadm/issues/2998
