### ISSUE TITLE
k8s workers stuck although there's no high work load or high utilization of resources 

### ISSUE THREAD

**Issue by rogaina** [kubernetes/kubernetes#122831]
there's issue in our kubernetes cluster that consists of 20 workers and many times some of these workers stuck although there's no high workload or high utilization of compute resources

this is the following info about kubernetes cluster

> kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:34:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:27:46Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

> os release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

**Comment by liangyuanpeng** [comment]
Could you reproduce this in a supported version of Kubernetes? I notice that you are using 1.23 which is no longer supported.

**Comment by rogaina** [comment]
yes , kubernetes version is 1.23.17

**Comment by Ritikaa96** [comment]
Hi @rogaina  does this issue exist in latest version as well?

**Comment by Ritikaa96** [comment]
Also,  the support channels would be better places to ask support queries. please see:
https://git.k8s.io/kubernetes/SUPPORT.md
