### ISSUE TITLE
Readiness probes are called even when pod is in terminating state

### ISSUE THREAD

**Issue by reenakabra** [kubernetes/kubernetes#122824]
### What happened?

When i deleted a pod using readiness probe saw below events

Events:
  Type     Reason     Age                 From     Message
  ----     ------     ----                ----     -------
  Normal   Killing    3m3s                kubelet  Stopping container xxxxxxx
  Warning  Unhealthy  35s (x10 over 14d)  kubelet  Readiness probe failed:

### What did you expect to happen?

Based on the issue https://github.com/kubernetes/kubernetes/issues/52817 and PR https://github.com/kubernetes/kubernetes/pull/98571 I expected readiness probe should not be called for a terminating pod similar to startup and liveness probe. Any specific reason we did not include readiness probe in this check.

	// Graceful shutdown of the pod.
	if w.pod.ObjectMeta.DeletionTimestamp != nil && (w.probeType == liveness || w.probeType == startup) {
		klog.V(3).Infof("Pod deletion requested, setting %v probe result to success: %v - %v",
			w.probeType.String(), format.Pod(w.pod), w.container.Name)
		if w.probeType == startup {
			klog.Warningf("Pod deletion requested before container has fully started: %v - %v",
				format.Pod(w.pod), w.container.Name)
		}
		// Set a last result to ensure quiet shutdown.
		w.resultsManager.Set(w.containerID, results.Success, w.pod)

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod using readiness probe and a preStop hook so that deletion takes time. Delete the pod. You can still see readiness probe getting called for this pod.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here

NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"


$ uname -a
# paste output here

Linux infdevlnx001 4.18.0-372.32.1.el8_6.x86_64 #1 SMP Fri Oct 7 12:35:10 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
If we expect readiness probes to be called for pods that are terminating, let's make that clear in the docs (to avoid future bug reports).

**Comment by kannon92** [comment]
cc @matthyx

Tagging out as you worked on the PR linked and was curious if you had any insight into this bug report.

**Comment by kannon92** [comment]
Could you reproduce this in a supported version of Kubernetes? I notice that you are using 1.25 which is no longer supported.

**Comment by matthyx** [comment]
> If we expect readiness probes to be called for pods that are terminating, let's make that clear in the docs (to avoid future bug reports).

Probes are not supposed to run during termination... except (in the future) with sidecar containers.

**Comment by reenakabra** [comment]
Reproduced the issue with 1.26.13

Events:
  Type     Reason       Age    From     Message
  ----     ------       ----   ----     -------
  Normal   Killing      79s    kubelet  Stopping container xxx
  Warning  Unhealthy    12s    kubelet  Readiness probe failed:

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.13", GitCommit:"7ba444e261616cb572b2c9e3aa6ee8876140f46a", GitTreeState:"clean", BuildDate:"2024-01-17T13:45:13Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.13", GitCommit:"7ba444e261616cb572b2c9e3aa6ee8876140f46a", GitTreeState:"clean", BuildDate:"2024-01-17T13:37:06Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}

Simple steps:
Delete the pod that has readiness probe and terminationGracePeriod and preStop hook set. Readiness probe failure message is seen after deletion.

**Comment by HirazawaUi** [comment]
> Probes are not supposed to run during termination... except (in the future) with sidecar containers.

Based https://github.com/kubernetes/kubernetes/pull/98571#issuecomment-771459905, only stop liveness and startup probe seems to be in line with expectations.

**Comment by rphillips** [comment]
Readiness probes during termination are expected. Readiness probes during termination allow for statuses to be propagated to allow for Services to be cleanly removed from Endpoints. 

https://github.com/kubernetes/kubernetes/pull/110191

/close
