### ISSUE TITLE
Allow creation of floating IPs for Load Balancer VIPs (OpenStack)

### ISSUE THREAD

**Issue by jgriffiths1993** [kubernetes/kubernetes#12284]
It would be very, VERY, **VERY** useful if OpenStack external load balancers could be assigned a floating IP address.

This involve adding `floating-network-id` as a configuration option to the cloud-config file and assigning an IP from here to the VIP.

It can then add this IP address to the `LoadBalancer Ingress` IP addresses.

**Comment by jgriffiths1993** [comment]
Also worth mentioning that the behaviour should not change unless `floating-network-id` is set

**Comment by thockin** [comment]
@artfulcoder as discussed last week
