### ISSUE TITLE
kubernetes/default service (api server) fails when changing --service-cluster-ip-range argument

### ISSUE THREAD

**Issue by jbkc85** [kubernetes/kubernetes#12289]
I ran into an issue earlier in which I started the API Server on a service-cluster-ip-range, and then went back and changed that ip-range (went from 10.51/16 to 10.52/16).  After changing this I started receiving errors in the journalctl logs of the kube-apiserver.service:

```
kube-apiserver[1723]: E0805 17:16:38.150204    1723 repair.go:122] the cluster IP 10.51.0.1 for service kubernetes/default is not within the service CIDR 10.52.0.0/16; please recreate
```

Thanks to thockin on IRC, I was able to delete the service and have it re-create itself:

```
# kubectl get services --all-namespaces
NAMESPACE   NAME         LABELS                                    SELECTOR   IP(S)       PORT(S)
default     kubernetes   component=apiserver,provider=kubernetes   <none>     10.51.0.1   443/TCP
# kubectl delete services/kubernetes
services/kubernetes
# kubectl get services --all-namespaces
NAMESPACE   NAME         LABELS                                    SELECTOR   IP(S)       PORT(S)
default     kubernetes   component=apiserver,provider=kubernetes   <none>     10.52.0.1   443/TCP
```

However, without thocken's help I would be unaware on what to do in this situation (being a newbie to K8s).  He asked me to open an issue, and thus the issue is open!

Additional Information:
- OS: CoreOS
- Using Fleet for kube-apiserver.service

**Comment by dchen1107** [comment]
Based on log posted above, we already detected the issue, shouldn't it be possible to automate this delete/recreate procedure. Or at least document it for now.

**Comment by thockin** [comment]
We don't, in general support changes to the `--service-cluster-ip-range` except expansions (e.g. 10.0.0.0/18 -> /16).  Service IPs are supposed to be reliably stable.  Now, if you have totally drained the cluster, MAYBE we could justify the master service itself handling this, but I think it's pretty fringe so this should be a doc, not a code change.

**Comment by marcmillien** [comment]
You shouldn't have to do this, but:
```
etcdctl rm /registry/services/specs/default/kubernetes
```

**Comment by RandyAbernethy** [comment]
If this is true:
"We don't, in general support changes to the --service-cluster-ip-range"
then it should be possible to run kube-apiserver without the switch. Presently if you leave it off the process errors and complains (which sort of makes you think you can set it to the range you like).

Perhaps the switch should be made optional and default to 10.0.0.0/16.

**Comment by thockin** [comment]
You can set it to any range you like, you just can't CHANGE it very easily.  You can change it, but ONLY if all Services have been removed, so none of them are determined to be in conflict.  This was decided to be safer than automatically re-allocating all Service IPs in the case of an accidental change.  If you are down to JUST the master Service, you can change the flag and delete the master Service, which the master will helpfully recreate for you.

It's probably debatable whether the master should do this step..
