### ISSUE TITLE
Order persistence with declared POD environment variables

### ISSUE THREAD

**Issue by MSJisable** [kubernetes/kubernetes#122950]
Describe scenario
When using HTTP Proxy, the MutatingWebhookConfiguration aks-webhook-admission-controller is reordering my environment variables. This leads to non-deterministic ordering of the environment variables which breaks interdependent environment variables: https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/

For example, I have a container spec as follows:
env:
- name: K8S_POD_NAME
valueFrom:
fieldRef:
fieldPath: metadata.name
- name: SERVER_NAME
value: 'FOO_$(K8S_POD_NAME)_eastus'

ASK: It is possible to force and keep the order persistence when POD Environment Variables have been declared?

**Comment by tamilselvan1102** [comment]
The order of precedence for environment variables is as follows:
1. Keys in env field
2. Keys in envFrom field
3. Keys defined in the container image

In you case case SERVER_NAME will be higher precedence than K8S_POD_NAME. so K8S_POD_NAME will be set as null.

**Comment by aojea** [comment]
> the MutatingWebhookConfiguration aks-webhook-admission-controller is reordering my environment variables

should not this being a request for that admission controller to not modify the order of the environment variables?

**Comment by AlftioH** [comment]
@aojea @tamilselvan1102 
Effectively the order is honored. A set of Environment Variables are injected from env at pod level and others are injected from a config map by a mutating admission webhook.

Exist the possibility to force the Admission Controller - MutatingAdmissionWebhook to keep a specific order for the Enviroment Variables?

**Comment by AlftioH** [comment]
@aojea @tamilselvan1102  Thanks for checking.

We are aware of the order precedence. The technical aspect is tha there are 2 separated elements generating Enviroment variables at the same time.

1. Pod yaml - env field
2- HTTP Proxy configMap - envFrom field

The defined Environment variable values are injected, intercepted and modified by mutating admission webhook.
As results the response after the mutating admission webhook is not maintaining the env order for the POD/Statefultset/Deployment.


Direct question is if exist a possibility to force, keep or reorganize the mutated response to keep the expected order ?
https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/ 

Reference:
https://github.com/Azure/AKS/issues/4071

**Comment by thockin** [comment]
Kubernetes should never re-order env variables.  If this is happening, it's got to be in the specific webhook
