### ISSUE TITLE
Scheduler:  Share `frameworkImpl.waitingPods` among profiles

### ISSUE THREAD

**Issue by NoicFank** [kubernetes/kubernetes#122945]
### What would you like to be added?

I hope to share the `waitingPods` among multiple profiles, instead of creating a new `waitingPods` in each profiles with the current implementation.

In other words, `waitingPods` is only instantiated once in a scheduler app.

https://github.com/kubernetes/kubernetes/blob/a1ffdedf782edf1472102b0b99c1467d4ed39753/pkg/scheduler/framework/runtime/framework.go#L253-L258

@Huang-Wei @ahg-g  PTAL, Is there any negative impact of this change that I didn't consider, thanks.

### Why is this needed?

In some scenarios, I need to traverse `all pods` waiting in the permit stage within the current scheduler app, rather than the pods that using the current profile for scheduling and waiting in the permit stage.

For example, we want use [coscheduling](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/coscheduling/README.md) to achieve `all-or-nothing`. And we have abstracted the concept of a `Cluster`, where there are two deployments under each cluster. Each deployments use different scheduler profile, and one cluster corresponds to one podGroup, as following:
![image](https://github.com/kubernetes/kubernetes/assets/18323315/256ffd20-6adc-4dc5-b249-d6ffcafed303)

Then, we want pods in one cluster (podA1, podA2, podB1) to be scheduled succeed/failed together. 

We assume that all pods can pass through the filter plugins, and `podA2` is the last to be scheduled. At this point, `podA1` and `podB1` are both waiting in the permit stage. Afterwards, we traverse the `waitingPods` to complete the permit waiting for `podA1` and `podB1`. However, from an implementation perspective, now we can only see `podA1` in `waitingPods`, `podB1` cannot be seen, because`podA2` & `podB1` use different scheduling profiles. Which will cause `podB1` timeout during the permit phase, even if all pods within the podGroup are successfully scheduled.

**Comment by kerthcet** [comment]
So the `Cluster`  is cross-k8s-clusters object, and these two different deployments under different k8s-cluster, right?

**Comment by NoicFank** [comment]
> So the `Cluster` is cross-k8s-clusters object, and these two different deployments under different k8s-cluster, right?

Not really, these two deployments are located in the same k8s-cluster

It can be understood that the `Cluster` in the example above is roughly equivalent to an namespace, where these two deployments are located in the same ns, and we hope that all pods managed by the two deployments under this ns can be scheduled successfully or fail simultaneously.

**Comment by kerthcet** [comment]
Can you elaborate more? Why these deployments should be scheduled together, I'm curious about this. Thanks.

**Comment by NoicFank** [comment]
> Can you elaborate more? Why these deployments should be scheduled together, I can image this might be useful, just curious about the user story. Thanks.

Of course, our specific usage scenario is for stateful service (DB). For a DB instance (which is a `Cluster` mentioned above), there will be many pods under each DB instance. We will divide those pods into different components according to their functions (mainly different images), and for each component, we will use a workload(sts/deploy/...) to manage it. Overall, there will be multiple workloads under each DB instance, and each workload will manage its own pods.
For scheduling, we need to consider successfully scheduling all pods under the same instance to ensure service availability, because if some pods under an instance are successfully scheduled, the DB service is still unavailable (even if all pods managed by the next workload of the DB instance are successfully scheduled)

**Comment by NoicFank** [comment]
> Can you elaborate more? Why these deployments should be scheduled together, I can image this might be useful, just curious about the user story. Thanks.

Following is an open-source project to manage databases on K8s that you may be interested in.
https://github.com/apecloud/kubeblocks
