### ISSUE TITLE
[KEP 3488] Promote ValidatingAdmissionPolicy to GA

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#122936]
### What would you like to be added?

This is the tracking issue of promoting Validating Admission Policy to GA: https://github.com/kubernetes/enhancements/issues/3488

Listed the blocking issues/features below:

- [x] https://github.com/kubernetes/kubernetes/issues/122935
- [x] https://github.com/kubernetes/kubernetes/issues/122918
- [x] https://github.com/kubernetes/kubernetes/issues/122658
- [x] https://github.com/kubernetes/kubernetes/issues/120239
- [x] https://github.com/kubernetes/kubernetes/issues/120491

- [ ] https://github.com/kubernetes/kubernetes/issues/122205

Issues be aware of but should not be a GA blocker
- [x] https://github.com/kubernetes/kubernetes/issues/122052
- [ ] https://github.com/kubernetes/kubernetes/issues/115920
- [ ] https://github.com/kubernetes/kubernetes/issues/118230

### Why is this needed?

/sig api-machinery
/triage accepted

**Comment by cici37** [comment]
FYI @jpbetz @alexzielenski @jiahuif

**Comment by sftim** [comment]
/retitle [KEP 3488] Promote ValidatingAdmissionPolicy to GA

We do like to write API kinds without inner whitespace

**Comment by jpbetz** [comment]
xref https://github.com/kubernetes/enhancements/issues/3488 which being used by the release team to track this enhancement
