### ISSUE TITLE
Scalability evaluation for validatingadmissionpolicy

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#122918]
### What would you like to be added?

[Validating Admission Policy](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/) was graduated to beta in 1.28. Since the feature is expected to be stable, the scalability evaluation is expected including the performance impact of each operation related to the ValidatingAdmissionPolicy feature and the limitations to which the cluster degrades to be nonfunctional. 

### Why is this needed?

To provide a better idea on scalability of the feature.

**Comment by jiahuif** [comment]
Results published publicly at https://docs.google.com/document/d/1RkVI_RIc-ZxaW0ew-NaBgrqejcxPuO1jCTHRr83ewoQ/edit?usp=sharing&resourcekey=0-uAlqxV8HT-ZeORalxIRtYg

Any comments will be greatly appreciated. Note that you need to be in `dev@kubernetes.io` google group to comment.

**Comment by cici37** [comment]
Please feel free to reopen the issue if needed. Thanks!
