### ISSUE TITLE
Topology spreading can become imbalanced during pod eviction

### ISSUE THREAD

**Issue by jmao-dd** [kubernetes/kubernetes#122909]
### What happened?

We saw topology spreading constraints violated when a pod was evicted from a node and rescheduled on another node. In our deployment we want the 3 pods to be distributed in 3 availability zones but we saw 0/1/2 distributions multiple times. 

When a node is drained it evicts all pods on it and k8s schedules new pods on other nodes to satisfy deployment's replicas spec. In our environment, when this event happens the newly scheduled pod is always created at least 10 seconds before the corresponding old pod is terminated. When scheduling the new pod k8s sees evenly distributed pods without knowing a pod will be terminated soon, so it schedules pod to an arbitrary domain which is sometimes different from the domain in which the old pod is running. 

This is similar to https://github.com/kubernetes/kubernetes/issues/105661 but it happens during node draining so the new and old pods are in the same replica, which means we can't use the `MatchLabelKeys` to distinguish the old an new pods. 

### What did you expect to happen?

I am not sure this is a bug or limitation of topology spreading constraints. If it is a limitation please document this limitation.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a 3 replica service to a k8s cluster running in 3 AZ region with the following topologySpreadConstraints

```
topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.k8s.io/zone
        whenUnsatisfiable: DoNotSchedule
```

Drain the node in one zone and check the pods distribution after

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.6-dd.1
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by AxeZhan** [comment]
> I am not sure this is a bug or limitation of topology spreading constraints.

I think this is a limitation, it's because scheduler also considers terminating pod when calculating the topology spreading constraints.
Some rescheduler like `Descheduler` may helps.
