### ISSUE TITLE
Kubelet - failed to initialize top level QOS containers: root container [kubepods] doesn't exist

### ISSUE THREAD

**Issue by sj98ta** [kubernetes/kubernetes#122955]
### What happened?

Starting the kubelet the first time after a system reboot,  the kubelet fails with:
`E0125 00:20:56.003890    2172 kubelet.go:1466] "Failed to start ContainerManager" err="failed to initialize top level QOS containers: root container [kubepods] doesn't exist"`

Which, sort of is a lie.   The root cause is actually that `cpuset` does not exist in `/sys/fs/cgroup/cgroup.subtree_control` 

After the kubelet exits, systemd restarts in,  and then all is fine after that,  until the next time the OS is restarted.  

I tried to track it down,  create.go does add the cpuset to `cgroup.subtree_control`,  and it remains there until `common.go:setUnitProperties()` is executed,  at which time `cpuset` appears to be disabled and disappears.  The other controllers are unaffected.   On the subsequent kubelet restart, `cpuset` does get added again,  and remains after the call to setUnitProperties().   

### What did you expect to happen?

I would expect the kubelet to start and not exit on all starts of the kubelet. 

### How can we reproduce it (as minimally and precisely as possible)?

The OS I am using is RHEL 9 on s390x.   
1) Boot the OS
2) Start the kubelet (I start with `kubeadm init` or `kubeadm join`.
3) Observer the kubelet starts,  fails, and then restarts.   Subsequent restarts of the kubelet are successful until the OS rebooted. (Likely due to after a reboot, the /sys/fs/cgroups is fresh,  unlike subsequent restarts of the kubelet)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:32:41Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/s390x"}
Kustomize Version: v4.5.7
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

RHEL 9 kernel 5.14.0-162.22.2.el9.s390x
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O 1.26.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by T-Lakshmi** [comment]
@sj98ta,

See the issues #122681[(comment)](https://github.com/kubernetes/kubernetes/issues/122681#issuecomment-1885625941) and #95488 which were reported with same kind of error.

I hope it may helpful for you.

**Comment by sj98ta** [comment]
@T-Lakshmi 
> See the issues #122681[(comment)](https://github.com/kubernetes/kubernetes/issues/122681#issuecomment-1885625941) and #95488 which were reported with same kind of error.
> 
> I hope it may helpful for you.

Thanks.  I have seen both of these before,  and neither seems applicable in my case.  :-(  

FWIW,  the cgroup driver in my case is systemd for both cri-o  and kubelet.   
This only seems to fail the first time the kubelet is started after the OS has finished a fresh boot.  After the failure, systemd restarts the kubelet, and all is good.  Subsequent restarts of the kubelet also start clean.   If the OS is started,  then again kubelet fails, restarts, then all is fine again.    Somehow, `vendor/github/opencontainers/runc/libcontainer/cgroups/common.go:setUnitProperties()`  is disabling the `cpuset` controller, but only on the initial start of kubelet after reboot of the OS.

**Comment by kannon92** [comment]
/remove-kind support

This doesn't seem to be a support case.

**Comment by harche** [comment]
We observed this issue on `x86_64` as well.

**Comment by harche** [comment]
@sj98ta are you using cgroup v1 or v2?

**Comment by sj98ta** [comment]
@harche This is cgroup v2

**Comment by kolyshkin** [comment]
Would be nice to see what parameters are passed on to SetUnitProperties (what unit, list of properties and their values).

What the function does is simply sends a dbus message to systemd to set some properties for a unit (similar to what `UNIT PROPERTY=VALUE...` would do). So, it must be systemd that changes `/sys/fs/cgroup/cgroup.subtree_control` file.

**Comment by harche** [comment]
> Would be nice to see what parameters are passed on to `SetUnitProperties` (what unit, list of properties and their values).
> 
> What the function does is simply sends a dbus message to systemd to set some properties for a unit (similar to what `UNIT PROPERTY=VALUE...` would do). So, it must be systemd that changes `/sys/fs/cgroup/cgroup.subtree_control` file.

```
Feb 28 18:54:45 ip-10-0-0-59 systemd[1]: Created slice libcontainer container kubepods.slice.
Feb 28 18:54:45 ip-10-0-0-59 kubenswrapper[2123]: I0228 18:54:45.859828    2123 common.go:448] "setUnitProperties Params" name="kubepods.slice" properties=[{"Name":"MemoryMax","Value":{}},{"Name":"CPUWeight","Value":{}},{"Name":"TasksMax","Value":{}}]
Feb 28 18:54:45 ip-10-0-0-59 kubenswrapper[2123]: E0228 18:54:45.870378    2123 kubelet.go:1559] "Failed to start ContainerManager" err="failed to initialize top level QOS containers: root container [kubepods] doesn't exist"
Feb 28 18:54:45 ip-10-0-0-59 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Feb 28 18:54:45 ip-10-0-0-59 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Feb 28 18:54:47 ip-10-0-0-59 chronyd[977]: Selected source 169.254.169.123
Feb 28 18:54:51 ip-10-0-0-59 /usr/sbin/irqbalance[890]: Cannot change IRQ 31 affinity: Input/output error
Feb 28 18:54:51 ip-10-0-0-59 /usr/sbin/irqbalance[890]: IRQ 31 affinity is now unmanaged
Feb 28 18:54:51 ip-10-0-0-59 /usr/sbin/irqbalance[890]: Cannot change IRQ 30 affinity: Input/output error
Feb 28 18:54:51 ip-10-0-0-59 /usr/sbin/irqbalance[890]: IRQ 30 affinity is now unmanaged
Feb 28 18:54:51 ip-10-0-0-59 ovs-vswitchd[1073]: ovs|00064|memory|INFO|180028 kB peak resident set size after 10.1 seconds
Feb 28 18:54:51 ip-10-0-0-59 ovs-vswitchd[1073]: ovs|00065|memory|INFO|handlers:4 idl-cells-Open_vSwitch:635 ports:10 revalidators:2 rules:9 udpif keys:15
Feb 28 18:54:54 ip-10-0-0-59 systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
Feb 28 18:54:55 ip-10-0-0-59 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 1.
Feb 28 18:54:55 ip-10-0-0-59 systemd[1]: Stopped Kubernetes Kubelet.
Feb 28 18:54:55 ip-10-0-0-59 systemd[1]: Starting Kubernetes Kubelet...
```

I printed the args of [SetUnitPropertiesContext](https://github.com/kubernetes/kubernetes/blob/e21a2f5d4f010e49cea1b954bd9b31d94e712c5b/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/common.go#L447C12-L447C36)

PS: This change in the kubelet's systemd service file seem to fix the issue - https://github.com/openshift/machine-config-operator/pull/4217/files, but we aren't sure yet if that's the right approach. 

/cc @haircommander

**Comment by harche** [comment]
> Would be nice to see what parameters are passed on to `SetUnitProperties` (what unit, list of properties and their values).
> 
> What the function does is simply sends a dbus message to systemd to set some properties for a unit (similar to what `UNIT PROPERTY=VALUE...` would do). So, it must be systemd that changes `/sys/fs/cgroup/cgroup.subtree_control` file.

```
Feb 28 16:08:51 ip-10-0-2-97 kubenswrapper[2115]: I0228 16:08:51.122290 2115 common.go:448] "setUnitProperties Params" name="kubepods.slice" properties=[{"Name":"MemoryMax","Value":{}},{"Name":"CPUWeight","Value":{}},{"Name":"TasksMax","Value":{}}]
Feb 28 16:08:51 ip-10-0-2-97 kubenswrapper[2115]: E0228 16:08:51.131925 2115 kubelet.go:1559] "Failed to start ContainerManager" err="failed to initialize top level QOS containers: root container [kubepods] doesn't exist"
```

**Comment by AnishShah** [comment]
How does setting `Delegate=yes` in systems service help resolve this issue?

**Comment by haircommander** [comment]
basically: we've figured out that this issue happens because libcontainer doesn't initialize the cpuset cgroup for the kubepods slice when the kubelet initially calls into it to do so. This happens because there isn't a cpuset defined on the top level of the cgroup. however, we fail to validate all of the cgroup controllers we need are present. It's possible this is a limitation in the dbus API: how do you ask systemd to create a cgroup that is effectively empty?

if we delegate: we are telling systemd to leave our cgroups alone, and not remove the "unneeded" cpuset cgroup.
