### ISSUE TITLE
pkg/client separation from godep, or using godep save -r ./..., or ?

### ISSUE THREAD

**Issue by peter-edge** [kubernetes/kubernetes#12290]
I ran into this issue today re: https://github.com/GoogleCloudPlatform/kubernetes/issues/12272

Kubernetes has a ton of uses just through the client library, which is primarily in pkg/client, but the typical way to use golang libraries is to just do a simple import. Vendoring is obviously golang's big gripe right now, and it's definitely getting better with 1.5, but many tools (including godep) default to a state where the vendoring only works for final applications, not for libraries that can be used elsewhere.

Requiring external code to conform with kubernetes' specific usage of godep means the following things:
1. Other libraries need to do special godep restores just for kubernetes code
2. These dependencies may conflict with other libraries' dependencies
3. GOPATH manipulation, special casing, etc

Just a general pain :)

Potential solutions:
1. `godep save -r`: this rewrites the import paths within kubernetes code, so no more `GOPATH` manipulation needed
2. Use the party tool https://github.com/mjibson/party: we've been using this for a bit over at https://github.com/fsouza/go-dockerclient and it works just fine.
3. I don't know, I really only had 1 and 2, but I'm sure there's a thousand other solutions.

This would seem like a relatively big change, but it's not terrible, some of the development docs would need to be updated. This obviously needs a lot of discussion though. Thoughts?

One other note: I forget which of godep and party have issues with getting dependencies across all values of `GOOS/GOARCH`, I think both of them do actually, but generally I just do `GOOS=linux GOARCH=amd64` for linux-only apps when doing dependencies, and I think this is effectively what has been doine with godep right now but it should be noted somewhere for those who are developing on mac and then doing all local testing within docker containers.

**Comment by dchen1107** [comment]
cc/ @lavalamp @JanetKuo

**Comment by lavalamp** [comment]
Yeah, it's a pain to import our client right now.

We have work in progress to reduce the number of imports needed. We'll also definitely be investigating 1.5's new vendoring system.

We definitely can't do rewriting in our main repo, various downstream consumers have this as a requirement (including red hat and google). (Although if you want to make local clones that rewrite before you import into your project, nothing is stopping you.)

**Comment by bgrant0607** [comment]
See also #7584 and the issues it references
