### ISSUE TITLE
e2e_node help message about "--kubeconfig" flag is not correct 

### ISSUE THREAD

**Issue by YuikoTakada** [kubernetes/kubernetes#123013]
### What happened?

When I try to do e2e test on my local environment which is built using `kind`, `unknown flag` error occusr though this flag is explained in help message.

### What did you expect to happen?

the explanation about flag will be fixed

### How can we reproduce it (as minimally and precisely as possible)?

Reproduction steps:
```
$ cd $GOPATH/src/k8s.io/kubernetes
$ make WHAT="test/e2e_node/e2e_node.test" 
$ ./_output/bin/e2e_node.test --kubeconfig ~/.kube/config
```

When I do above steps, error message `unknown flag: --kubeconfig` is shown.
But When I execute `./_output/bin/e2e_node.test --help` , below message is shown:
```
--host string      The host, or apiserver, to connect to. Will default to https://127.0.0.1:6443 if this argument and --kubeconfig are not set.
```

Can I use `--kubeconfig` flag or not?

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"29+", GitVersion:"v1.29.0-alpha.0.594+efb8fe8ba90c01", GitCommit:"efb8fe8ba90c01c488fd980f6fff494ae7edff36", GitTreeState:"clean", BuildDate:"2024-01-16T08:23:24Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
local cluster built using `kind`
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tuibeovince** [comment]
Just to add:

The --host flag is classified under Common Flags. Therefore this description will common to e2e_node and e2e_kubeadm
https://github.com/kubernetes/kubernetes/blob/eb0fcf9e216f83e200e1c04e24d0484394da6b86/test/e2e/framework/test_context.go#L365

However

--kubeconfig argument is classified under the Cluster Flags
https://github.com/kubernetes/kubernetes/blob/eb0fcf9e216f83e200e1c04e24d0484394da6b86/test/e2e/framework/test_context.go#L411

both e2e and e2e_kubeadm use the Cluster Flags, but e2e_node does not.

I hope someone can share the intended output for e2e_node

**Comment by kannon92** [comment]
This is a better question for slack rather than as a k8s issue. 

short story is that you are using the wrong `make` command for node-e2e tests.

You could try `make test-e2e-node`. I recommend trying it with `REMOTE=false`.

```
make test-e2e-node REMOTE=false CLEANUP=false RUNTIME=remote  FOCUS="YOUR_TEST_NAME" SKIP="" 
```

Just an example.

**Comment by YuikoTakada** [comment]
@kannon92 Thank you for your kindness. Unfortunately, I tryed what you teached me, but it failed because of auth error with `Unable to find in-cluster config, using default host : https://127.0.0.1:6443/` message.
I'll post to #sig-node channel in slack, thanks.
