### ISSUE TITLE
Releases v1.26.12 - Kubernetes ConfigMap Values Not Resolving after Upgrade

### ISSUE THREAD

**Issue by SL20523** [kubernetes/kubernetes#123025]
After upgrading Kubernetes from version 1.25.x to v1.26.12, we have encountered an issue where values in the ConfigMap are not resolving as expected. Specifically, the value for the property MY_PROPERTY_NOT_WORKING is set to "null," and Null objects are not being recognized or resolved from within the pod.

Example ConfigMap:
```
apiVersion: v1
data:
  MY_PROPERTY_NOT_WORKING: "null"
  MY_PROPERTY_WORKING: "true"
kind: ConfigMap
metadata:
  annotations:
  creationTimestamp: "2023-07-04T13:50:49Z"
  name: test-env
  namespace: test
  resourceVersion: "123"
  uid: <UID>
```

We will continue to investigate and provide updates as we work towards resolving this incident. If you have any additional information or insights, please feel free to contribute to the investigation.

**Comment by sftim** [comment]
@SL20523: GitHub is not the right place for support requests.

If you're really looking for help with your specific cluster, you could try asking on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by neolit123** [comment]
/sig api-machinery
close if not a bug or FR.

**Comment by SL20523** [comment]
Why is it not a Bug? All our Pods have since the update the issue that they can not find a env Variable which has a "null" as value.

**Comment by sftim** [comment]
> Where can I ask for help in Kubernetes Slack?

Visit https://slack.k8s.io/ for an invitation, log in, and then ask in #kubernetes-users

You can create a bug report here in GitHub, but: this needs to explain how to reproduce the bug, and to outline what the symptoms look like. It can't just be a request for help with troubleshooting.
