### ISSUE TITLE
@alandsidel this is not fruitful. locking this conversation now.

### ISSUE THREAD

**Issue by alandsidel** [kubernetes/kubernetes#123028]
@alandsidel this is not fruitful. locking this conversation now.

_Originally posted by @dims in https://github.com/kubernetes/kubernetes/issues/82381#issuecomment-1402611379_
            
It's.. insulting.. to have @thockin continue to post in a "locked" issue.  This sort of ivory tower behavior is, bluntly, another reason why so many of us simply don't engage with projects like this -- which leads your project to mistakenly conclude that you have a reasonably representative sample of your userbase to base decisions on.

Seriously.  Unlock the issue, or stop posting in it.

Or just lock this one and continue on, reinforcing my point.

**Comment by neolit123** [comment]
move this discussion on slack - e.g. #sig-network channel.

/sig network
/close
