### ISSUE TITLE
Difference in observed pod status in regular vs static pod

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#123057]
### What happened?

I was looking create a reproducer to test https://github.com/kubernetes/kubernetes/pull/122778, when I stumbled upon something that didn't make sense to me. Maybe I am mistaken, please feel free to close this issue if it isn't a real bug. 

I was trying to force the pod to stay in `ContainerCreating` state for debugging https://github.com/kubernetes/kubernetes/issues/122721 when using standard `Generic PLEG`.  So I modified `Generic PLEG` in my local setup to ignore `PodLifeCycle ContainerStarted` event for a specific pod under test using this patch, 

<details>
  <summary>pleg diff</summary>

```diff
diff --git a/pkg/kubelet/pleg/generic.go b/pkg/kubelet/pleg/generic.go
index 80da5bb059c..3ec180ec0a6 100644
--- a/pkg/kubelet/pleg/generic.go
+++ b/pkg/kubelet/pleg/generic.go
@@ -19,6 +19,7 @@ package pleg
 import (
        "context"
        "fmt"
+       "strings"
        "sync"
        "sync/atomic"
        "time"
@@ -176,7 +177,7 @@ func (g *GenericPLEG) Healthy() (bool, error) {
        return true, nil
 }
 
-func generateEvents(podID types.UID, cid string, oldState, newState plegContainerState) []*PodLifecycleEvent {
+func generateEvents(podID types.UID, cid string, oldState, newState plegContainerState, pod *kubecontainer.Pod) []*PodLifecycleEvent {
        if newState == oldState {
                return nil
        }
@@ -184,6 +185,9 @@ func generateEvents(podID types.UID, cid string, oldState, newState plegContaine
        klog.V(4).InfoS("GenericPLEG", "podUID", podID, "containerID", cid, "oldState", oldState, "newState", newState)
        switch newState {
        case plegContainerRunning:
+               if strings.Contains(pod.Name, "nginx") {
+                       return []*PodLifecycleEvent{{ID: podID, Type: ContainerChanged, Data: cid}}
+               }
                return []*PodLifecycleEvent{{ID: podID, Type: ContainerStarted, Data: cid}}
        case plegContainerExited:
                return []*PodLifecycleEvent{{ID: podID, Type: ContainerDied, Data: cid}}
@@ -388,14 +392,17 @@ func getContainersFromPods(pods ...*kubecontainer.Pod) []*kubecontainer.Containe
 
 func computeEvents(oldPod, newPod *kubecontainer.Pod, cid *kubecontainer.ContainerID) []*PodLifecycleEvent {
        var pid types.UID
+       var pod *kubecontainer.Pod
        if oldPod != nil {
                pid = oldPod.ID
+               pod = oldPod
        } else if newPod != nil {
                pid = newPod.ID
+               pod = newPod
        }
        oldState := getContainerState(oldPod, cid)
        newState := getContainerState(newPod, cid)
-       return generateEvents(pid, cid.ID, oldState, newState)
+       return generateEvents(pid, cid.ID, oldState, newState, pod)
 }

 
 func (g *GenericPLEG) cacheEnabled() bool { 
```
</details>

While this works well for regular pod (which end up getting stuck, as expected, in `ContainerCreating` state), 

```bash
 kubectl get pods 
NAME    READY   STATUS              RESTARTS   AGE
nginx   0/1     ContainerCreating   0          2s
```
but if I deploy the same pod as a static pod it ends up running even though Generic PLEG is clearly not sending any `ContainerStarted` PodLifeCycle event. 

```bash
$ kubectl get pods 
NAME              READY   STATUS    RESTARTS   AGE
nginx-127.0.0.1   1/1     Running   0          2s
```

I always thought the pod status should be similar for regular and static pod, but not sure why do they differ here though. 

<details>
<summary> pod yaml </summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
```
</details>

### What did you expect to happen?

Pod statuses should remain same for regular as well as static pods. 

### How can we reproduce it (as minimally and precisely as possible)?

You will have to apply the patch given in the description. 

### Kubernetes version

master 

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by harche** [comment]
Please note that this is not really a `bug` per say, that a regular user will encounter. I am deliberating modifying `Generic PLEG` for understanding a few things. Having said that, I was surprised to see a difference in behaviour between regular and static pods under similar modified circumstances.

**Comment by thockin** [comment]
@tallclair

**Comment by ndixita** [comment]
cc: @SergeyKanzhelev

**Comment by yujuhong** [comment]
I tried reproducing this with the patch but couldn't. Both the regular and the static pods in my cluster ended up in the running state after a while. 

My interpretation is that even though the events weren't sent to trigger an immediate sync for the pod, the pod status are still updated internally in PLEG. And also the fallback sync internal will eventually triggers a full sync of the pod and send the status update to the apiserver. 

Could you try reproducing again and watch the pod status for, say, 5 minutes, to see if you still observe the same problem?

**Comment by harche** [comment]
@yujuhong I had update the patch in the description to be able to apply to the current master branch. 

<details>
<summary> updated diff </summary>

```diff
diff --git a/pkg/kubelet/pleg/generic.go b/pkg/kubelet/pleg/generic.go
index 80da5bb059c..3ec180ec0a6 100644
--- a/pkg/kubelet/pleg/generic.go
+++ b/pkg/kubelet/pleg/generic.go
@@ -19,6 +19,7 @@ package pleg
 import (
        "context"
        "fmt"
+       "strings"
        "sync"
        "sync/atomic"
        "time"
@@ -176,7 +177,7 @@ func (g *GenericPLEG) Healthy() (bool, error) {
        return true, nil
 }
 
-func generateEvents(podID types.UID, cid string, oldState, newState plegContainerState) []*PodLifecycleEvent {
+func generateEvents(podID types.UID, cid string, oldState, newState plegContainerState, pod *kubecontainer.Pod) []*PodLifecycleEvent {
        if newState == oldState {
                return nil
        }
@@ -184,6 +185,9 @@ func generateEvents(podID types.UID, cid string, oldState, newState plegContaine
        klog.V(4).InfoS("GenericPLEG", "podUID", podID, "containerID", cid, "oldState", oldState, "newState", newState)
        switch newState {
        case plegContainerRunning:
+               if strings.Contains(pod.Name, "nginx") {
+                       return []*PodLifecycleEvent{{ID: podID, Type: ContainerChanged, Data: cid}}
+               }
                return []*PodLifecycleEvent{{ID: podID, Type: ContainerStarted, Data: cid}}
        case plegContainerExited:
                return []*PodLifecycleEvent{{ID: podID, Type: ContainerDied, Data: cid}}
@@ -388,14 +392,17 @@ func getContainersFromPods(pods ...*kubecontainer.Pod) []*kubecontainer.Containe
 
 func computeEvents(oldPod, newPod *kubecontainer.Pod, cid *kubecontainer.ContainerID) []*PodLifecycleEvent {
        var pid types.UID
+       var pod *kubecontainer.Pod
        if oldPod != nil {
                pid = oldPod.ID
+               pod = oldPod
        } else if newPod != nil {
                pid = newPod.ID
+               pod = newPod
        }
        oldState := getContainerState(oldPod, cid)
        newState := getContainerState(newPod, cid)
-       return generateEvents(pid, cid.ID, oldState, newState)
+       return generateEvents(pid, cid.ID, oldState, newState, pod)
 }

 
 func (g *GenericPLEG) cacheEnabled() bool { 
```

</details>

I observed that the regular pod stays in `ContainerCreating` state for a long time before moving into `Running` state,

```bash
[harshal@fedora kubernetes]$ kubectl get pods 
NAME    READY   STATUS              RESTARTS   AGE
nginx   0/1     ContainerCreating   0          50s
[harshal@fedora kubernetes]$ kubectl get pods 
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          5m41s
```
but the same pod if deployed as a static pod immediately moves to `Running` state, 

```
[harshal@fedora kubernetes]$ sudo cp /tmp/pod.yaml /var/run/kubernetes/static-pods/. 
[sudo] password for harshal: 
[harshal@fedora kubernetes]$ kubectl get pods 
NAME              READY   STATUS    RESTARTS   AGE
nginx-127.0.0.1   1/1     Running   0          2s
```

**Comment by yujuhong** [comment]
@harche thanks for the update. 

With the information, I think we can all agree that this is not a bug. And even with the change, eventually all pods became running (which is good).

As to why it takes longer for a regular pod in this situation, I have a theory after scanning the log further. 

Logs handling a static pod:
```
kubelet[26439]: I0222 18:20:10.727900   26439 kubelet.go:2408] "SyncLoop ADD" source="file" pods=["default/nginx-gke-otter-default-pool-7dffbbd1-99cz"]
kubelet[26439]: I0222 18:20:10.840722   26439 kubelet.go:2408] "SyncLoop ADD" source="api" pods=["default/nginx-gke-otter-default-pool-7dffbbd1-99cz"]
kubelet[26439]: I0222 18:20:11.774599   26439 kubelet.go:2421] "SyncLoop RECONCILE" source="api" pods=["default/nginx-gke-otter-default-pool-7dffbbd1-99cz"]
kubelet[26439]: I0222 18:21:12.802814   26439 kubelet.go:2459] "SyncLoop (SYNC) pods" total=1 pods=["default/nginx-gke-otter-default-pool-7dffbbd1-99cz"]
```

The first sync happened when kubelet detected the static pod (source=file). At the end of this sync, a mirror pod was created at the apiserver. 
The second sync happened when kubelet detected the mirror pod from the apiserver, this triggered a sync right away which resulted in a status update. This is the extra sync that the regular pods don't have. 

I think you should be able to verify the behavior by changing and/or injecting some log messages.

**Comment by harche** [comment]
Thanks @yujuhong 

/close
