### ISSUE TITLE
messages with sensitive information should not be printed to the log file because of information security?

### ISSUE THREAD

**Issue by chaunceyctx97** [kubernetes/kubernetes#123029]
### What happened?

we found some sensitive information in log file:

1. in Audit.log
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"RequestResponse"，"auditID":"","stage":"ResponseComplete","requestURI":"/apis/certificates.k8s.io/v1/certificatesigningrequests","verb":"create","user":{"username":"kubelet-bootstrap","uid":"10001","groups":
["system:bootstrappers","system:authenticated"J}，"sourceiPs":["192.108.18.135 ⌋，"usergent :Kubelet/（Linux/amd64)kubernetes/77d727f"，"objectRef":{"resource":"certificatesigningrequests","apiGroup":"certificates.k8s.io","apiVersion":"v1"},"responseStatus":{"metadata":{}，"code":201},"requestObject": {"kind":"CertificateSigningRequest","apiVersion":"certificates.k8s.io/v1","metadata":
{"generateName":"csr-","creationTimestamp":null},"spec":{"request":"LSetLS1CRUd38880 XXXXXXXXX U2NxaGtqT1B.  

```
spec.request  `"LSetLS1CRUd38880 XXXXXXXXX U2NxaGtqT1B.  ` looks like a private key

2. in kubelet.log
```
E0116 19:35:32.748517 4920 kuberuntime_manager.go:1007] container&Container{Name:installer,Image:engine-hub-x86 64:23.99.1,Comand:[],Args:[],WorkingDir:,Ports[]ContainerPort{ContainerPort{Name:daemon,HostPort:0,ContainerPort:9902,Protocol:TCP,HostIP:,},},Env: []EnvVar{EnVar{Name:INSTALL_APP,Value:engine-hub,ValueFrom:nil,},EnvVar{Name:INSTALL_SET_image_repository,Value:engine-hub-B6,ValueFrom:nil,},EnvVar{Name:INSTALL_SET_Cluster_replicas,Value:3,ValueFrom:nil,},EnvVar{Name:INSTALL_SET_cluster_secret,Value:00000xxxxxxxxxx, ValueFrom:nil}

```
kubelet will print pod information including container environment variable when startContainer failed.
if pod uses some secrets as environment variable, kubelet will print this secret content just like above-mentioned
`EnvVar{Name:INSTALL_SET_cluster_secret,Value:00000xxxxxxxxxx, ValueFrom:nil}` 

so will this content in log file result in information leakage?  and do we have a better log print policy?

### What did you expect to happen?

no sensitive information in log file

### How can we reproduce it (as minimally and precisely as possible)?

all k8s version

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
what is your k8s version?

/sig auth node

**Comment by neolit123** [comment]
> EnvVar{Name:INSTALL_SET_cluster_secret,Value:00000xxxxxxxxxx,

that's just an env var, and it's the responsibility of the user.
there could be a standardized suffix / prefix to hide certain env vars with suffix / prefix.
that;s not a bug but a FR.

/sig instrumentation

**Comment by neolit123** [comment]
> "spec":{"request":"LSetLS1CRUd38880 XXXXXXXXX U2NxaGtqT1B.  

what verbosity level is this in the logs --v=x ?

**Comment by kannon92** [comment]
This is not a support. It seems like a valid ask that could impact all users so removing support label. 
/remove-kind support

**Comment by chaunceyctx97** [comment]
> what is your k8s version?
> 
> /sig auth node

sorry for late reply. use k8s 1.27

**Comment by chaunceyctx97** [comment]
> > "spec":{"request":"LSetLS1CRUd38880 XXXXXXXXX U2NxaGtqT1B.
> 
> what verbosity level is this in the logs --v=x ?

@neolit123  
may be this method prints these message
https://github.com/kubernetes/kubernetes/blob/a923537a15ab68c7cf547f9cb0e434d7a04927b6/staging/src/k8s.io/apiserver/plugin/pkg/audit/log/backend.go#L87

**Comment by dgrisonnet** [comment]
SIG Instrumentation doesn't own the content of the logs, please reach out to SIG node.

/remove-sig instrumentation

**Comment by thockin** [comment]
@pohly sine he thinks about logs a lot

**Comment by pohly** [comment]
There is a whole KEP about log sanitization: https://github.com/kubernetes/enhancements/tree/master/keps/sig-security/1933-secret-logging-static-analysis

It used to be under SIG Instrumentation and got transferred to SIG Security. I have never been involved with it and only ran into it a few times because it also had hooks for live filtering of log messages while writing them (not used anymore).

As @dgrisonnet said, SIG Instrumentation is not responsible for the content of log messages.

**Comment by ndixita** [comment]
cc: @ndixita

**Comment by AnishShah** [comment]
Regarding part 1, I think audit logs containing sensitive information might be WAI? In case of security intrusion, this can help understand what changes a bad actor made.

`kube-apiserver` takes the `--audit-policy-file` flag to control how much you want to log. You can use the following policy to avoid logging the full request header.

```
- level: Metadata
  resources:
  - group: "" 
    resources: ["secrets", "serviceaccounts/token"]
  - group: authentication.k8s.io
    resources: ["tokenreviews"]
  omitStages:
  - "RequestReceived"
  ```

**Comment by tallclair** [comment]
The flagged audit log is reporting the CertificateSigningRequest's `request` field, which should be a public certificate. Do you have evidence suggesting that a private key was included in the request?

For the environment variable, secret data should be stored in a secret, and use the `valueFrom` with a secret ref, instead of embedding the secret data directly. There is lots of special handling for secrets, but we cannot tell if the data is secret for a raw envvar.

I think we can close this as working-as-intended.

/close
