### ISSUE TITLE
Kubernetes Node Resources may not have provider ID populated when using external cloud provider 

### ISSUE THREAD

**Issue by swetharepakula** [kubernetes/kubernetes#123024]
### What happened?

When using an external/out of band cloud providers, the responsibility of adding the provider ID to a Node resource moves from kubelet to the node controller. However because of this change, kubelet will create a node without the provider ID specified and may mark the node as ready. This has become an issue in GKE where workloads are scheduled on the node, but external networking (Ingress and Gateway) cannot proceed because the providerID is missing leading to possible downtimes every time a new node is created.

Another consequence is that if populating the [provider ID fails for any reason](https://github.com/kubernetes/kubernetes/blob/ae185414f4e94e969399c40b23995af6f85fa37f/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L434-L437), the Node object is never updated which means information such as the zone topology and provider ID don't exist. EPS Controller uses the zone topology to populate the EPS.

### What did you expect to happen?

When using an external cloud provider, I would expect that the provider ID should gate whether the Node is considered ready or not. This would ensure that workloads are not scheduled on to a Node, until it has all relevant information populated.

### How can we reproduce it (as minimally and precisely as possible)?

On any cluster that uses an external cloud provider, there will be two API calls made when a new node is created. A create call from kubelet where provider ID isn't populated and an update by the node controller.

### Kubernetes version

<details>

Relevant code seems quite old and should be the same in all supported Kubernetes Versions.

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by swetharepakula** [comment]
cc/ @bobbypage

**Comment by aryasoni98** [comment]
This issue is still active ? @swetharepakula

**Comment by swetharepakula** [comment]
Yes this issue is still active. We are seeing in GKE 1.26+ clusters where the external cloud provider is used. However, looking at the code, any cloud provider can run into this issue and it is not specific to GKE.

**Comment by aojea** [comment]
Are we not tainting the node?

https://github.com/kubernetes/kubernetes/blob/ae185414f4e94e969399c40b23995af6f85fa37f/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L424-L437

The controller should reconcile

**Comment by bowei** [comment]
@dchen1107

**Comment by aojea** [comment]
/close

https://github.com/kubernetes/kubernetes/pull/123331
