### ISSUE TITLE
How can I compile Kubernetes with gollvm and generate IR?

### ISSUE THREAD

**Issue by younaman** [kubernetes/kubernetes#123018]
### What happened?

Hello everyone, I am nanzi yang. I want to compile Kubernetes source code to LLVM IR. So, I just install gollvm. My installation is fine and I can use commands such as go build/go-doc to compile a simple go program to IR (such as Hello world.go). But when I try to compile the Kubernetes source code. I have some issues:
1. When I try to use go build, there are no main.go under Kubernetes main directory, so it is failed.
2. I tried to use go build under each separate directory. It still failed.
3. After 1 and 2, I try to modify the Makefile of LLVM and make it use my specific gollvm compiler, not the default go compiler. But I am not familiar with the Makefile of LLVM and I can't find the location where I can specify the go compiler.

### What did you expect to happen?

Does anyone can give me some comments about compiling Kubernetes source code to LLVM IR?

### How can we reproduce it (as minimally and precisely as possible)?

You can try to install gollvm following its official documents [here](https://go.googlesource.com/gollvm/#building). However, please notice that the gollvm is not compatible with the latest LLVM main branch. It takes me about one week and now I follow the commit [here](https://groups.google.com/g/golang-nuts/c/EzY7FFlDINM). These commits work on my local ubuntu 22.04 LTS. I will be very glad if anyone can help me to fix these "terrible" problem.

### Kubernetes version

<details>

```console
$ kubectl version
the master branch now
# paste output here
```

</details>

### Cloud provider

<details>

</details>
no provider

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/kind support
/sig release
(? please close if no owner)

@younaman 
your best bet is to ask on support channels and not on github.
maybe stackoverflow.
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by younaman** [comment]
@saschagrunert Thanks for your reply! I am sorry for the delay because I have been a little bit busy recently.
For the go command. I have tried the go build ./cmd/kubelet, but it returns:

``go build k8s.io/kubernetes/cmd/kubelet: no Go files in /home/younaman/workarea-specific-commit/install/src/kubernetes/cmd/kubelet``
After that, I tried to run build in the ./cmd/kubelet, and run:
``go build kubelet.go``

It seems like no error returns, but where can I find the built binary file?

**Comment by younaman** [comment]
@saschagrunert Thanks a lot! According to your comment about golang.sh, I tried to change the official go install command to my specific go build command, and it works!:)
But it exists another problem. When I added another ``go version`` command before the official go install command as you described. I find that the Kubernetes use its own go compiler because the ``go version`` returns ``the version of go compiler is: go version go1.22.0 linux/amd64
``
BUT my local gollvm version is ``go version go1.18 gollvm LLVM 15.0.0git 20240129 (experimental) linux/amd64``. So it looks like Kubernetes doesn't use my local go compiler, and use its own go compiler from _output directory. How can I make the Kubernetes use my local go compiler? Looking forward to your reply!


Regards,
Nanzi Yang

**Comment by saschagrunert** [comment]
@younaman how do you build Kubernetes? If you run something like plain `go build …` then it should use your local toolchain, right?

**Comment by younaman** [comment]
Thanks for your reply! After a few days, I found that the Kubernetes will first download the compiler if the local environment doesn't meet the minimum go version requirement, after that, it will compile the source code via the compiler.
After that, I found that Kubernetes version 1.23.17 met my requirement, and I tried to compile it with my local gollvm compiler (go version go1.18) with FORCE_HOST_GO env. But the compile can't pass with this error ( shown in the figure). However, when I tried to build the Kubernetes with native go compiler go 1.18. It returns no error. So, it seems the gollvm compiler itself has a problem which can not meet my requirements.:(

Now, I am trying to follow the go native SSA and build my own go static analyzer with the analyzer package of Golang itself. It's a big undertaking for me. If you have any comments, please feel free to let me know.
