### ISSUE TITLE
Duplicate OwnerReferences Can Deny Service To SSA Clients

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/kubernetes#123053]
### What happened?

When some actor manages to add duplicate `OwnerReferences` to an object, any other client attempting to use server-side apply to mutate the object will fail client-side.

Consider some `Service`:

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-10T22:57:31Z"
  name: service-name
  namespace: service-namespace
  ownerReferences:
  - apiVersion: group.whatever.com/v1
    blockOwnerDeletion: false
    controller: false
    kind: SomeKind
    name: someName
    uid: 1ea7605c-001a-11ea-9a90-027feb72be7e
  - apiVersion: group.whatever.com/v1
    blockOwnerDeletion: false
    controller: false
    kind: SomeKind
    name: someName
    uid: 1ea7605c-001a-11ea-9a90-027feb72be7e
  resourceVersion: "304470743"
  uid: 8cf44d74-d698-450f-abb6-b52f3511a85b
spec:
  clusterIP: 172.30.249.81
  clusterIPs:
  - 172.30.249.81
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 5443
  selector:
    app: whatever
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

When a client attempts to send a server-side apply PATCH, client-side validation fails:

```
E0131 12:33:54.677801       1 queueinformer_operator.go:319] sync {"update" "service-namespace/service-name"} failed: failed to create manager for existing fields: failed to convert new object (service-namespace/service-name; /v1, Kind=Service) to smd typed: errors:
  .metadata.ownerReferences: duplicate entries for key [uid="1ea7605c-001a-11ea-9a90-027feb72be7e"]
  .metadata.ownerReferences: duplicate entries for key [uid="1ea7605c-001a-11ea-9a90-027feb72be7e"]
```

### What did you expect to happen?

If unique `OwnerReferences` is an invariant required of objects, perhaps we can add some ratcheting validation for objects in `etcd` that enforces it. I can't see a good reason any client would want duplicate entries, but we must have uniqueness for SSA to function here.

### How can we reproduce it (as minimally and precisely as possible)?

Create a resource with a duplicate `OwnerReference` - don't use `kubectl edit` as that client will helpfully dedupe things for you. Then try using SSA.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.0
WARNING: version difference between client (1.29) and server (1.24) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
not important
```

</details>

### Install tools

<details>
none
</details>

### Container runtime (CRI) and version (if applicable)

<details>
n/a
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
n/a
</details>

**Comment by jpbetz** [comment]
Does a  the problem still happen if a client uses`--force-conflicts`?

**Comment by stevekuznetsov** [comment]
@jpbetz while trying to find a trivial reproducer to answer your question, I found this error message while trying to create such an object:

```
Warning: .metadata.ownerReferences contains duplicate entries; API server dedups owner references in 1.20+, and may reject such requests as early as 1.24; please fix your requests; duplicate UID(s) observed: 1ea7605c-001a-11ea-9a90-027feb72be7e
```

The cluster in question has been upgraded past 1.24 for years. Just to confirm - when that ratcheting validation was added, would we have expected it to also re-read and update data in `etcd`? I believe the object that tripped me up in this bug is pretty ancient. Wondering if it would have been expected that data int `etcd` would no longer be valid.

**Comment by deads2k** [comment]
>Wondering if it would have been expected that data int etcd would no longer be valid.

We don't fix already broken data. The interaction with apply is not-great, but if ratcheting validation is already present I don't think we'll do much with this.

**Comment by stevekuznetsov** [comment]
Yeah, makes perfect sense.
