### ISSUE TITLE
Migrate remaining `k/k` jobs

### ISSUE THREAD

**Issue by rjsadow** [kubernetes/kubernetes#123079]
The following jobs still run on the default google owned cluster and need to be migrated to a community cluster

**kubernetes**
- [x] pull-kubernetes-e2e-gci-gce-ingress | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gci-gce-ingress) |
- [x] pull-kubernetes-e2e-ubuntu-gce-network-policies | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-ubuntu-gce-network-policies) |
- [x] pull-kubernetes-e2e-gci-gce-ipvs | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gci-gce-ipvs) |
- [x] pull-kubernetes-e2e-containerd-gce-main | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-containerd-gce) |
- [x] pull-kubernetes-node-arm64-ubuntu-serial-gce-main | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-arm64-ubuntu-serial-gce) |
- [x] pull-kubernetes-node-e2e-containerd-kubetest2 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-e2e-containerd-kubetest2) |
- [x] pull-kubernetes-node-kubelet-serial-containerd | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-kubelet-serial-containerd) |
- [x] pull-kubernetes-node-kubelet-serial-containerd-alpha-features | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-kubelet-serial-containerd-alpha-features) |
- [x] pull-kubernetes-node-kubelet-serial-containerd-sidecar-container | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-kubelet-serial-containerd-sidecar-container) |
- [x] pull-kubernetes-node-kubelet-serial-containerd-kubetest2 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-kubelet-serial-containerd-kubetest2) |
- [x] pull-kubernetes-kind-dra | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-kind-dra) |
- [x] pull-kubernetes-e2e-inplace-pod-resize-containerd-main-v2 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-inplace-pod-resize-containerd-main-v2) |
- [x] pull-kubernetes-e2e-gce-device-plugin-gpu-1.26 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gce-device-plugin-gpu) |
- [x] pull-kubernetes-e2e-containerd-gce-1.26 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-containerd-gce) |
- [x] pull-kubernetes-node-e2e-containerd-kubetest2 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-e2e-containerd-kubetest2) |
- [x] pull-kubernetes-e2e-gce-device-plugin-gpu-1.27 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gce-device-plugin-gpu) |
- [x] pull-kubernetes-e2e-containerd-gce-1.27 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-containerd-gce) |
- [x] pull-kubernetes-node-e2e-containerd-kubetest2 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-e2e-containerd-kubetest2) |
- [x] pull-kubernetes-e2e-gce-device-plugin-gpu-1.28 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gce-device-plugin-gpu) |
- [x] pull-kubernetes-e2e-containerd-gce-1.28 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-containerd-gce) |
- [x] pull-kubernetes-node-arm64-ubuntu-serial-gce-1.28 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-arm64-ubuntu-serial-gce) |
- [x] pull-kubernetes-node-e2e-containerd-kubetest2 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-e2e-containerd-kubetest2) |
- [x] pull-kubernetes-e2e-containerd-gce-1.29 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-containerd-gce) |
- [x] pull-kubernetes-node-arm64-ubuntu-serial-gce-1.29 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-arm64-ubuntu-serial-gce) |
- [x] pull-kubernetes-node-e2e-containerd-kubetest2 | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-node-e2e-containerd-kubetest2) |
~~[ ] pull-kubernetes-e2e-gce-big-performance | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gce-big-performance) |~~
~~[ ] pull-kubernetes-e2e-gce-scale-performance-manual | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gce-scale-performance-manual) |~~
- [x] pull-kubernetes-e2e-gce-storage-slow | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gce-storage-slow) |
- [x] pull-kubernetes-e2e-gce-storage-snapshot | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gce-storage-snapshot) |
- [x] pull-kubernetes-e2e-gce-csi-serial | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gce-csi-serial) |
- [x] pull-kubernetes-e2e-gce-storage-disruptive | [Search Results](https://cs.k8s.io/?q=pull-kubernetes-e2e-gce-storage-disruptive) |

/sig testing
/sig k8s-infra

**Comment by sandipanpanda** [comment]
Hi! I would like to take this opportunity to contribute to K8s.

/assign

**Comment by ameukam** [comment]
> Hi! I would like to take this opportunity to contribute to K8s.
> 
> /assign

@sandipanpanda Please pick one repo at the time and tag me in the PR for review.
Multiple attempts to migrate are completely OK. we are not expecting people to be successful on the first try.

**Comment by alessandrocapanna** [comment]
I am working on pull-cadvisor-e2e-kubernetes job!

**Comment by jongwooo** [comment]
I am working on `pull-kubernetes-node-kubelet-serial-containerd` job.

/assign

**Comment by Devaansh-Kumar** [comment]
Hello guys, I would like to work on `pull-kubernetes-node-kubelet-serial-containerd-kubetest2` job
/assign

**Comment by Devaansh-Kumar** [comment]
I will now work on `pull-kubernetes-node-kubelet-serial-containerd-sidecar-container` and `pull-kubernetes-node-kubelet-serial-containerd-alpha-features` jobs

**Comment by jongwooo** [comment]
I would like to work on `pull-kubernetes-kind-dra` job.

**Comment by jongwooo** [comment]
I would like to work on `pull-kubernetes-e2e-gce-big-performance` and `pull-kubernetes-e2e-gce-scale-performance-manual` jobs.

**Comment by jongwooo** [comment]
I would like to work on `pull-kubernetes-e2e-gce-storage-slow`, `pull-kubernetes-e2e-gce-storage-snapshot`, `pull-kubernetes-e2e-gce-csi-serial`,  `pull-kubernetes-e2e-gce-storage-disruptive` jobs. (all included in `sig-storage-gce-config.yaml`)

**Comment by jongwooo** [comment]
I'd like to work on `pull-kubernetes-node-arm64-ubuntu-serial-gce` job.

**Comment by jongwooo** [comment]
I'd like to work on `pull-kubernetes-e2e-inplace-pod-resize-containerd-main-v2` job.

**Comment by Devaansh-Kumar** [comment]
I would like to work on all three `pull-kubernetes-e2e-gce-device-plugin-gpu` jobs

**Comment by ameukam** [comment]
@rjsadow `pull-kubernetes-e2e-containerd-gce` is referenced multiple times. Can you reference the release version instead and toggle them under the same checkbox?

**Comment by rjsadow** [comment]
@ameukam Updated `pull-kubernetes-e2e-containerd-gce` and `pull-kubernetes-e2e-gce-device-plugin-gpu` for clarity

**Comment by ameukam** [comment]
@rjsadow Let's exclude
pull-kubernetes-e2e-gce-big-performance
pull-kubernetes-e2e-gce-scale-performance-manual

Let's take care of the scalability tests at the end.

**Comment by alessandrocapanna** [comment]
@rjsadow we have already migrated: 

- pull-kubernetes-e2e-gce-device-plugin-gpu-1.26
- pull-kubernetes-e2e-gce-device-plugin-gpu-1.27
- pull-kubernetes-e2e-gce-device-plugin-gpu-1.28
- pull-kubernetes-node-arm64-ubuntu-serial-gce-1.28

(all remaining jobs for this story) 

So I think we can close it?
