### ISSUE TITLE
APIServer cache dose not work

### ISSUE THREAD

**Issue by xianlubird** [kubernetes/kubernetes#123012]
### What happened?

I enabled consistent reading interfaces in k8s 1.28, but I found that they could not speed up my list. Has anyone else tested why?

### What did you expect to happen?

speed up my list.

### How can we reproduce it (as minimally and precisely as possible)?

enabled consistent reading interfaces in k8s 1.28

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
1.28

### Cloud provider

<details>
no
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
What's `consistent reading interfaces` exactly?

**Comment by MadhavJivrajani** [comment]
I'm assuming this is what is being spoken about: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2340-Consistent-reads-from-cache

cc @serathius

**Comment by MadhavJivrajani** [comment]
@xianlubird can you provide more information about your setup, how you've run the test, what your request looked like, what your response looked like etc?
