### ISSUE TITLE
Is Graceful Node Shutdown enabled by default on a K8S cluster?

### ISSUE THREAD

**Issue by nashtapu-tibco** [kubernetes/kubernetes#123132]
### What happened?

As checked on the K8S documentation, the GracefulNodeShutdown was enabled by default in K8S 1.21 as beta: https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/

But there is no update on this yet. I don't think this is GA yet.

### What did you expect to happen?

For a fresh EKS cluster created 1.25 (sufficiently after 1.21), I was expecting that it should have the GracefulNodeShutdown enabled. Hence, the systemd-inhibit --list should show kubelet.

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster and check the systemd-inhibit --list  on the nodes.

### Kubernetes version

<details>
1.25
</details>

### Cloud provider

<details>
Amazon EKS
</details>

### OS version

<details>

```console
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tamilselvan1102** [comment]
Kubernetes v1.21 onward, it is enabled by default

To enable the GracefulNodeShutdown, you need edit master/worker configmap. Along with the feature gate, there is a requirement to set value of ShutdownGracePeriod (by default it is set to zero).

**Comment by nashtapu-tibco** [comment]
@tamilselvan1102 the documentation says
`Graceful node shutdown is controlled with the GracefulNodeShutdown [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates) and is enabled by default in Kubernetes 1.21.`

Does that mean the feature is available to use but to use one needs to configure?
Because from the documentation, it looks like is "enabled" be default.

**Comment by tamilselvan1102** [comment]
@nashtapu-tibco 
please refer here, you can get an idea https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown
