### ISSUE TITLE
[Failing Test][sig-node] ci-cos-containerd-node-e2e and required presubmit CI pull-kubernetes-node-e2e-containerd

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#123127]
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e/1753883638342094848

### Which tests are failing?

- e2e.go: Node Tests expand_more	42m46s
- E2eNode Suite: [It] [sig-node] Pod SIGKILL [LinuxOnly] [NodeConformance] The containers terminated forcefully by Sigkill should have the correct exit code(137) and reason (Error) expand_more	10m3s
- E2eNode Suite: [It] [sig-node] Probing container should be restarted with an exec liveness probe with timeout [MinimumKubeletVersion:1.20] [NodeConformance] expand_more	4m2s
- E2eNode Suite: [It] [sig-network] Networking Granular Checks: Pods should function for intra-pod communication: http [NodeConformance] [Conformance] expand_more	14s
- E2eNode Suite: [It] [sig-network] Networking Granular Checks: Pods should function for node-pod communication: http [LinuxOnly] [NodeConformance] [Conformance] expand_more	1m16s
- E2eNode Suite: [It] [sig-node] Ephemeral Containers [NodeConformance] should update the ephemeral containers in an existing pod [Conformance] expand_more	4s
- E2eNode Suite: [It] [sig-node] Ephemeral Containers [NodeConformance] will start an ephemeral container in an existing pod [Conformance] expand_more	4s
- E2eNode Suite: [It] [sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart exec hook properly [NodeConformance] [Conformance] expand_more	5m2s
- E2eNode Suite: [It] [sig-node] [NodeConformance] Containers Lifecycle should call the container's preStop hook and terminate it if its liveness probe fails expand_more	1m44s
- E2eNode Suite: [It] [sig-node] [NodeConformance] Containers Lifecycle should not launch second container before PostStart of the first container completed expand_more	4s
- E2eNode Suite: [It] [sig-node] PrivilegedPod [NodeConformance] should enable privileged commands [LinuxOnly] expand_more	2s
- E2eNode Suite: [It] [sig-node] Probing container should override timeoutGracePeriodSeconds when StartupProbe field is set [NodeConformance] expand_more	4m43s
- E2eNode Suite: [It] [sig-node] [NodeConformance] Containers Lifecycle should run Init container to completion before call to PostStart of regular container expand_more	6s
- E2eNode Suite: [It] [sig-node] Probing container should be restarted with a exec "cat /tmp/health" liveness probe [NodeConformance] [Conformance] expand_more	4m2s
- E2eNode Suite: [It] [sig-network] Networking Granular Checks: Pods should function for intra-pod communication: udp [NodeConformance] [Conformance] expand_more	16s
- E2eNode Suite: [It] [sig-node] Swap [NodeConformance] [LinuxOnly] with configuration QOS Guaranteed expand_more	2s
- E2eNode Suite: [It] [sig-node] Pods should support remote command execution over websockets [NodeConformance] [Conformance] expand_more	2s
- E2eNode Suite: [It] [sig-node] [NodeConformance] Containers Lifecycle should call the container's preStop hook and terminate it if its startup probe fails expand_more	1m42s
- E2eNode Suite: [It] [sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance] expand_more	36s
- E2eNode Suite: [It] [sig-node] Security Context [NodeConformance] [LinuxOnly] Container PID namespace sharing containers in pods using isolated PID namespaces should all receive PID 1 expand_more	2s
- E2eNode Suite: [It] [sig-node] Swap [NodeConformance] [LinuxOnly] with configuration QOS Burstable expand_more	2s
- E2eNode Suite: [It] [sig-node] Security Context [NodeConformance] [LinuxOnly] Container PID namespace sharing processes in containers sharing a pod namespace should be able to see each other expand_more	4s
- E2eNode Suite: [It] [sig-node] KubeletManagedEtcHosts should test kubelet managed /etc/hosts file [LinuxOnly] [NodeConformance] [Conformance] expand_more	4s
- E2eNode Suite: [It] [sig-node] Swap [NodeConformance] [LinuxOnly] with configuration QOS Best-effort expand_more	2s
- E2eNode Suite: [It] [sig-network] Networking Granular Checks: Pods should function for node-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance] expand_more	1m16s
- E2eNode Suite: [It] [sig-node] Swap [NodeConformance] [LinuxOnly] with configuration QOS Burstable with memory request equals to limit expand_more

### Since when has it been failing?

02-04 
first failure https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e/1753883638342094848

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#image-validation-node-e2e

### Reason for failure (if possible)

> { failed [FAILED] Failed to await Pod (sigkill-test-6542/sigkill-pod-e1d4c8ed-fd7a-46fe-a56f-b3da64dc2e5e) become 
> ready after registering signal handler: Timed out after 300.000s.
> The matcher passed to Eventually returned the following error:
>     <*errors.errorString | 0xc000c003a0>: 
>     pod 'sigkill-pod-e1d4c8ed-fd7a-46fe-a56f-b3da64dc2e5e' on 'tmp-node-e2e-01675d27-ubuntu-gke-2204-1-25-v20240203' didn't have condition {Ready True}; conditions: [{PodReadyToStartContainers True 0001-01-01 00:00:00 +0000 UTC 2024-02-03 21:05:54 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-02-03 21:05:53 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2024-02-03 21:05:53 +0000 UTC ContainersNotReady containers with unready status: [sigkill-target-container]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2024-02-03 21:05:53 +0000 UTC ContainersNotReady containers with unready status: [sigkill-target-container]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-02-03 21:05:53 +0000 UTC  }]

some potential reason log

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e/1753883638342094848/artifacts/tmp-node-e2e-01675d27-ubuntu-gke-2204-1-25-v20240203/cloud-init.log and 
cloud-init.log and serial-1.log

**in the failed CI job**
```
Feb 03 21:02:24 ubuntu dhclient[354]: execve (/bin/true, ...): Permission denied

 [    0.000000] [Firmware Bug]: TSC doesn't count with P0 frequency!
[    0.368418] smpboot: CPU0: AMD EPYC 7B12 (family: 0x17, model: 0x31, stepping: 0x0)
[    0.368418] smpboot: CPU0: AMD EPYC 7B12 (family: 0x17, model: 0x31, stepping: 0x0)
[    0.369959] Performance Events: AMD PMU driver.
[    0.370642] ... version:                0
[    0.371269] ... bit width:              48
[    0.371309] ... generic registers:      4
[    0.371311] ... value mask:             0000ffffffffffff
[    0.372034] ... max period:             00007fffffffffff
[    0.372832] ... fixed-purpose events:   0
[    0.373385] ... event mask:             000000000000000f
[    0.374192] signal: max sigframe size: 1776
[    0.374858] rcu: Hierarchical SRCU implementation.
[    0.375699] smp: Bringing up secondary CPUs ...
[    0.376617] x86: Booting SMP configuration:
[    0.377367] .... node  #0, CPUs:      #1
```

**in the passed CI job**

```
- [    0.080936] Kernel/User page tables isolation: enabled

[    0.512792] smpboot: CPU0: Intel(R) Xeon(R) CPU @ 2.20GHz (family: 0x6, model: 0x4f, stepping: 0x0)
[    0.514936] Performance Events: unsupported p6 CPU model 79 no PMU driver, software events only.
[    0.515582] signal: max sigframe size: 1776
[    0.516667] rcu: Hierarchical SRCU implementation.
[    0.518384] NMI watchdog: Perf NMI watchdog permanently disabled
[    0.519619] smp: Bringing up secondary CPUs ...
[    0.521096] x86: Booting SMP configuration:
[    0.522258] .... node  #0, CPUs:      #1

``` 

### Relevant SIG(s)

/sig node

**Comment by pacoxu** [comment]
It failed on ubuntu01 and passed on cos-stable01. 


`pull-kubernetes-node-e2e-containerd` is a required CI for presubmit. So this blocks PR merge.
/priority critical-urgent

**Comment by pacoxu** [comment]
kubelet log shows
```
E0203 21:03:52.016194    2380 kubelet.go:1449] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
I0203 21:03:52.016225    2380 event.go:376] "Event occurred" object="tmp-node-e2e-01675d27-ubuntu-gke-2204-1-25-v20240203" fieldPath="" kind="Node" apiVersion="" type="Warning" reason="InvalidDiskCapacity" message="invalid capacity 0 on image filesystem"
E0203 21:04:12.509307    2380 remote_runtime.go:496] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = failed to exec in container: failed to start exec \"b510f45b99c156f191e645c62b8e814200bb1979c3202e0955afd426a9551078\": OCI runtime exec failed: exec failed: container_linux.go:390: starting container process caused: setns_init_linux.go:98: eaccess caused:: unknown" containerID="8ee76e1ba2ba72c4775f90571e3fd1da337c402ed64c3e8a158599ba1c0569a1" cmd=["cat","/tmp/health"]
I0203 21:04:12.509394    2380 exec.go:62] Exec probe response: ""
I0203 21:04:12.509418    2380 prober.go:139] "Exec-Probe runProbe" pod="container-probe-8636/busybox-b9a2998c-1631-4d9a-b220-fb83214338a6" containerName="busybox" execCommand=["cat","/tmp/health"]
I0203 21:04:12.535957    2380 kuberuntime_manager.go:1246] "Creating container in pod" containerType="container" container="&Container{Name:busybox-3,Image:registry.k8s.io/e2e-test-images/agnhost:2.45,Command:[],Args:[pause],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:host-etc-hosts,ReadOnly:false,MountPath:/etc/hosts-original,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:host-etc-hosts,ReadOnly:false,MountPath:/etc/hosts,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Never,SecurityContext:&SecurityContext{Capabilities:nil,Privileged:nil,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,}" pod="e2e-kubelet-etc-hosts-546/test-pod"
```

> E0203 21:04:12.509307    2380 remote_runtime.go:496] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = failed to exec in container: failed to start exec \"b510f45b99c156f191e645c62b8e814200bb1979c3202e0955afd426a9551078\": OCI runtime exec failed: exec failed: container_linux.go:390: starting container process caused: setns_init_linux.go:98: eaccess caused:: unknown" containerID="8ee76e1ba2ba72c4775f90571e3fd1da337c402ed64c3e8a158599ba1c0569a1" cmd=["cat","/tmp/health"]

**Comment by carlory** [comment]
Runc code (eaccess):

- https://github.com/opencontainers/runc/blob/v1.1.12/libcontainer/standard_init_linux.go#L202-L209
- https://github.com/opencontainers/runc/blob/v1.1.12/libcontainer/eaccess_stub.go#L1-L10
- https://github.com/opencontainers/runc/blob/v1.1.12/libcontainer/eaccess_go119.go#L1-L17

**Comment by pacoxu** [comment]
https://github.com/containerd/containerd/blob/v1.6.18/script/setup/runc-version
- containerd 1.6.18 is using runc v1.1.4
- runc v1.1.6 fixed a `permission denied` buy in https://github.com/opencontainers/runc/pull/3817
- See https://github.com/golang/go/issues/58624 and https://go-review.googlesource.com/c/go/+/468735 for more details.

It seems to be related with the runc/containerd version on GCE.

Can we specify the runc/containerd version for the job?

**Comment by adisky** [comment]
> Can we specify the runc/containerd version for the job?

**Comment by ameukam** [comment]
> > Can we specify the runc/containerd version for the job?

```bash
Feb 03 21:02:41 tmp-node-e2e-01675d27-ubuntu-gke-2204-1-25-v20240203 containerd[1247]: time="2024-02-03T21:02:41.210610460Z" level=info msg="starting containerd" revision= version="1.6.18-0ubuntu0~22.04.2~gke2"
```

**Comment by pacoxu** [comment]
The latest containerd is `1.6.28` not `1.6.18`.

**Comment by adisky** [comment]
> revision= version="1.6.18-0ubuntu0~22.04.2~gke2"

**Comment by carlory** [comment]
I'm not sure whether the prowJob uses the [script](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure.sh#L480) or not. 

If it does, it will install containerd from Docker repo. And If env UBUNTU_INSTALL_CONTAINERD_VERSION and UBUNTU_INSTALL_RUNC_VERSION are set, it will override to latest versions of containerd and runc.

**Comment by carlory** [comment]
I don't know why container 1.6.18 and runc v1.1.4 are installed on ubuntu. It's not the latest version.

**Comment by dims** [comment]
good run, images used are - [log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e/1753868538629591040/build-log.txt):
```
Initializing e2e tests using image cos-stable/cos-cloud/cos-beta-109-17800-66-78.
Initializing e2e tests using image ubuntu/ubuntu-os-gke-cloud/ubuntu-gke-2204-1-25-v20240125a.
```

bad run, images used are - [log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e/1753883638342094848/build-log.txt):
```
Initializing e2e tests using image cos-stable/cos-cloud/cos-beta-109-17800-66-78.
Initializing e2e tests using image ubuntu/ubuntu-os-gke-cloud/ubuntu-gke-2204-1-25-v20240203.
```

**Comment by dims** [comment]
@pacoxu can we try the pipeline-1-29? ( https://paste.centos.org/view/raw/e1706f86 )

We need to fix the line here - https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/containerd/image-config-systemd.yaml#L3C5-L3C32

**Comment by neolit123** [comment]
the node e2e with GKE and COS semantics seem out of place, especially if not maintained properly. this is currently halting k/k unless someone with authz can skip. we have a plan to phase out cloud providers out of e2e, but i don't think there a similar plan for node e2e.

**Comment by dims** [comment]
slack thread is here: https://kubernetes.slack.com/archives/C0BP8PW9G/p1707110467128319

**Comment by dims** [comment]
@carlory @pacoxu PTAL https://github.com/kubernetes/test-infra/pull/31834

**Comment by dims** [comment]
Few more greens... closing this:

![image](https://github.com/kubernetes/kubernetes/assets/23304/d157de7a-d961-4fd3-9095-841829c58f49)

Feel free to reopen with pointers to fresh logs/failures.

/close
