### ISSUE TITLE
try setting KUBERNETES_MASTER environment variable

### ISSUE THREAD

**Issue by bnmanju** [kubernetes/kubernetes#123147]
### Describe the issue

Implemented sample operator using kubebuilder.
make run is to operator locally, its working fine. Created the docker image using the cmd, 'docker build -t <operator-name> . and while try to run it using the cmd, docker run <operator-name>, getting error like 
unable to get kubeconfig-invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable.
Tried to set KUBE_CONFIG path also.
Tested with both Kind and Minikube cluster.
Any suggestions please ?

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
