### ISSUE TITLE
Change encryption config reload success/failure metrics

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#123175]
Change encryption config controller reload metrics to be consistent with other places (Authn, Authz)
xref: https://github.com/kubernetes/enhancements/pull/4456/files#r1480546416

Combine `apiserver_encryption_config_controller_automatic_reload_failures_total` and `apiserver_encryption_config_controller_automatic_reload_success_total` into a single metric `apiserver_encryption_config_controller_automatic_reloads_total` with `status` with an enum value of `success` and `failure`.

/sig auth
/triage accepted

**Comment by aramase** [comment]
cc @enj

**Comment by enj** [comment]
We probably should keep the existing metrics for some time to allow folks to migrate to the new one.

**Comment by aramase** [comment]
> We probably should keep the existing metrics for some time to allow folks to migrate to the new one.

Ah I was thinking about this as well!

Looking at https://github.com/kubernetes/kubernetes/blob/fae7ec4a37642060bf97dcffb24a7a55b3190485/staging/src/k8s.io/component-base/metrics/opts.go#L77-L79 "may be deleted at any time", I was leaning towards just removing it.

If the common approach is to keep it for a release before removing, we could do that. I believe we can set a `DeprecatedVersion` for the 2 metrics we want to remove.

**Comment by enj** [comment]
I don't have a good sense of metrics stability because they tend to stay alpha forever and folks don't go back to update them.  Since the associated feature set is GA, I think we should be conservative with the changes we make.  Perhaps SIG instrumentation folks can provide some guidance here?

**Comment by aramase** [comment]
> I don't have a good sense of metrics stability because they tend to stay alpha forever and folks don't go back to update them.

As part of the PR, I was going to ask when is the right time to graduate these `ALPHA` metrics 😄 

@logicalhan do you have thoughts on
1. approach to take while deleting an alpha metric
2. when metrics should be graduated from alpha to beta and stable?
