### ISSUE TITLE
Reduce heapster's memory usage/leaks

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#12315]
As experienced while validating #12243, heapster is OOM'ing way too quickly, and using a surprising amount of memory in general. In that particular case, it OOM'ed after 15 minutes on a 5 node cluster with only a handful of pods running. We need to get it under control so that it can run reliably on larger clusters.

You're free to close this if you feel that it should only be tracked in heapster's repo, but it's an issue that affects kubernetes pretty seriously as well.

@vishh

**Comment by vishh** [comment]
I am working on this now.

**Comment by wojtek-t** [comment]
cc @piosz

**Comment by piosz** [comment]
@vishh could you please update what is your plan to reduce mem usage once you'll figured it out?

**Comment by vishh** [comment]
The current plan is as follows:
1. Store recent history (~5 mins) of stats per container in memory. We can consider reducing this cache duration further.
2. We will use a rolling window to make it resource estimation friendly.
3. To calculate percentiles, we will perform some approximations. For every minute, max and mean will be stored. For every hour, only the max and mean of minute samples will be stored. 95th %ile for the hour will be calculated from the per minute maximum values, to be on the safer side, considering the primary use case is resource estimation. When it comes to a day, average will be based on the average of hourly averages, 95%ile will be based on the 95%ile of each hour. 
4. All the derived metrics will be stored in memory to begin with. We should consider moving it to something like levelDB in the future, to provide more reliability. 

@afein is planning on implementing `2` and `3`. `1` is already completed. 
@piosz: If we can get to `4` soon, then we can probably declare to be production ready.

**Comment by piosz** [comment]
cc @mwielgus

**Comment by a-robinson** [comment]
Any update on how improved this will be for k8s 1.1? :)

**Comment by vishh** [comment]
The cache duration has been reduced to 4 minutes.
All the known issues around garbage collection have been fixed.
The internal storage model for the cache has not been updated and so I do not expect significant changes in the base line memory usage of heapster for 1.1.

**Comment by vishh** [comment]
@a-robinson What is the memory and cpu budget for heapster in GKE?

**Comment by a-robinson** [comment]
There's no explicit budget -- we can set it to whatever's appropriate. But given that we currently allot a particular amount of resources (100m, 300Mi), it seems fair to say that any increases in future versions should have to be justified (given that upgrading to a version that uses more resources might make heapster unschedulable in an existing cluster), and any decreases will be very welcome.

Sound reasonable?

**Comment by vishh** [comment]
Yes. That makes sense. Can we setup any automated tests for validating
heapster builds in GKE?

**Comment by a-robinson** [comment]
We should be able to, yeah

**Comment by vishh** [comment]
Given that heapster has undergone extensive refactoring thanks to @mwielgus and @piosz, this issue is now obsolete. Let's re-open if we see any new problems with memory consumption.
