### ISSUE TITLE
Pod looses network connection (connection reset errors) during preStop period

### ISSUE THREAD

**Issue by eternalklaus** [kubernetes/kubernetes#123116]
### What happened?

**Environment:**  
I am running an Spring boot HTTP server and an HTTP client pod, where the client sends requests to the server using the `myserver.svc.cluster.local` address. Both server and client communicate over a keep-alive session. And the server is configured with a `preStop` hook set to 10 seconds during rolling updates
```
 A(pod)---
          | -- myserver(svc) <--[HTTP request with keep-alive]-- myclient(svc) --- C(pod)
 B(pod)---
```
**Issue:**  
When performing a rolling update on the `myserver`, the client experiences a 2 times of a connection reset error. 
Each connection reset error occurs immediately as the each server pod enter the Terminating state. (beginning of preStop session)

<br>

**Detailed condition:**  
Despite the preStop being set to 10 seconds, which should theoretically allow existing keep-alive sessions to continue without accepting new HTTP traffic, the server's IP is immediately removed from the endpoints upon the preStop hook initiation. 
As a result, keep-alive sessions, which should have been maintained with Pod A, are transferred to Pod B. 

**ex)** For example, the client sends an HTTP GET request with a sequence number `61293`, which was associated with a keep-alive session on Pod A. However, as soon as preStop on Pod A initiates, this packet is redirected to Pod B. Pod B, receiving a packet with an unexpected sequence number, sends an RST packet back to the client, resulting in a connection reset error.

### What did you expect to happen?

While I expect that new HTTP traffic will not reach the pod during the preStop period, **I also expect that existing keep-alive sessions should be preserved.** However, this is not happening. Is this a bug, or is it intended behavior?

### How can we reproduce it (as minimally and precisely as possible)?

.

### Kubernetes version

<details>

```console
$ kubectl version
v1.15.11
```

</details>

### Cloud provider

<details>
kubernetes inhouse closed cloud service
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by thockin** [comment]
> Despite the preStop being set to 10 seconds

I don't know what that means - can you please paste some JSON/YAML to show exactly what you are setting?
