### ISSUE TITLE
e2e_node: Rebuild `registry.k8s.io/stress:v1` as Schema2 or OCI

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/kubernetes#123146]
https://github.com/kubernetes/kubernetes/blob/244fbf94fd736e94071a77a8b7c91d81163249d4/test/e2e_node/eviction_test.go#L1080-L1086

The image is built as a legacy Schema 1 image and will not work with most runtimes soon:
```console
$ docker pull registry.k8s.io/stress:v1 
v1: Pulling from stress
[DEPRECATION NOTICE] Docker Image Format v1, and Docker Image manifest version 2, schema 1 support will be removed in an upcoming release. Suggest the author of registry.k8s.io/stress:v1 to upgrade the image to the OCI Format, or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```

ref: 
- https://github.com/containerd/containerd/pull/6884
- https://github.com/containerd/containerd/pull/9765
- https://github.com/moby/moby/pull/42300

**Comment by AkihiroSuda** [comment]
cc @vishh 

You seemed to have built the image from https://github.com/vishh/stress on 2016-06-24T22:29:32 , could you rebuild and push the image?

**Comment by kannon92** [comment]
I actually ran into an issue with this one a few months ago. There was very little in the image for testing and I believe that @BenTheElder pointed me to the new test images they are using. We found that this image was quite old and essentially unmaintained.

**Comment by AkihiroSuda** [comment]
> @BenTheElder pointed me to the new test images they are using

Where is the new image?

**Comment by AkihiroSuda** [comment]
PR to merge stress to agnhost:
- https://github.com/kubernetes/kubernetes/pull/123258

**Comment by AkihiroSuda** [comment]
Next: 
- https://github.com/kubernetes/kubernetes/issues/123266
