### ISSUE TITLE
Eviction Tests Failures - Sorting of active pods is random

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#123247]
### Which jobs are flaking?

eviction tests

### Which tests are flaking?

eviction tests

### Since when has it been flaking?

For a long time.

### Reason for failure (if possible)

The main issue for these failures seems to be the ranking of the pods for eviction is random. Digging into this, I discovered that we are grabbing the stats from `cacheStatsFunc` and sometimes this call is failing. When the call fails, we skip checking by `exceedDiskUsage` and go to priority and usage. priority is the only one we can reliability rely on in e2e tests with the flaking summary calls.

### Relevant SIG(s)

/sig node

**Comment by kannon92** [comment]
https://github.com/kubernetes/kubernetes/pull/121832 is relevant here. I added logs in this PR to confirm that sorting fails and then that causes a mismatch of expected ranking of pods.

**Comment by rphillips** [comment]
I think the issue is EvictionManager is returning too early in waitForPodsCleanup due to it not checking pod_worker to see if the pod is still active.

**Comment by kannon92** [comment]
So there are two issues I discovered.

PidEviction tests are failing because we are not collecting process stats. #115215 

This happens in both crio/containerd eviction tests (so its not related to CRIStats versus CAdvisor stats).

ANd the second issue is that sometimes the stats collection fails and then we evict the pod that we couldn't get stats from.

THis can cause issues with ordering.

Some thoughts are to make the tests less random on stats (use priority classes)

Or we could add a deterministic sort based on QoS in case the pods fail. ie evict BestEffort before Burstable, etc.

**Comment by kannon92** [comment]
moving this to https://github.com/kubernetes/kubernetes/issues/123247
/close
