### ISSUE TITLE
Update api-conventions.md and api_changes.md, and add documentation about how to do API change reviews

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#12322]
I need other people to be able to do API reviews, so I need to improve the API convention documentation.

Placeholder for me to collect doc changes before I have to think about wordsmithing.

Conventions to document:
* Subresources: /binding, /status, ...
* Watch URL query parameter
* Deprecated conventions
  * Phase #7856
  * FooController
  * Minion
* FooTime vs. FooTimestamp
* Durations: FooSeconds
* Reason (CamelCase category) vs. Message (text w/ details)
* ObjectReference, LocalObjectReference, FooName, ...
* Referring to fields
* ObservedGeneration
* Label/Selector defaulting and auto-generated labels
* Experimental API and API groups
* Where maps are permitted (example: Secret)
* How to do discriminated unions
* No O(N) state in a single resource
* Pointers to distinguish unset
* Don't abbreviate
* How to handle overlapping conflicting sets selected by labels

Reviews:
* Backward compatibility gotchas
  * Changing default behavior

See also #7018 and #8190 for ideas.

cc @erictune @thockin

**Comment by pmorie** [comment]
@bgrant0607 Corollary on abbreviation: how to correctly handle things that make sense to refer to by acronyms

**Comment by pmorie** [comment]
And when to use acronyms

**Comment by timothysc** [comment]
cc @rrati - fyi per recent changes.

**Comment by bgrant0607** [comment]
Done enough. Will continue to add more things as we think of them.
