### ISSUE TITLE
Accessing Metrices on Https using Pod IP

### ISSUE THREAD

**Issue by vivek-singh2** [kubernetes/kubernetes#123289]
I am exposing prometheus metrices on port 8088 on HTTPS inside a Pod inside kubernetes cluster.  When some other Pod running in same cluster try to access these metrices, it fails at SSL connection part. It is accessing metrices like https://{pod-ip}:8088/metrices 
What will be needed to get this working on https. It works fine on http. In case of https, I am getting below error-

*   Trying 10.42.2.79:8088...
* Connected to 10.42.2.79 (10.42.2.79) port 8088
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 10.42.2.79:8088
* Closing connection
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 10.42.2.79:8088
pod "curl" deleted

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
