### ISSUE TITLE
Unable to fetch container log stats: failed to get fsstats

### ISSUE THREAD

**Issue by ncugit-sec** [kubernetes/kubernetes#123231]
### What happened?

Kebelet continues to display "Unable to fetch container log stats" errors trying to access missing logs of docker containers.
I'm not sure what is the mechanism here, while it seems that if somehow the container is not recycled by kebelet, the dangling link to the deleted container is not handled, triggering the file not found error.

```
cri_stats_provider.go:694] "Unable to fetch container log stats" err="failed to get fsstats for \"/var/log/pods/kube-system_kube-scheduler-xxx_4xxxe/kube-scheduler/15.log\": no such file or directory" containerName="kube-scheduler"
cri_stats_provider.go:694] "Unable to fetch container log stats" err="failed to get fsstats for \"/var/log/pods/kube-system_kube-apiserver-xxx_xxx/kube-apiserver/29.log\": no such file or directory" containerName="kube-apiserver"
cri_stats_provider.go:694] "Unable to fetch container log stats" err="failed to get fsstats for \"/var/log/pods/kube-system_etcd-xxx_0x9/etcd/18.log\": no such file or directory" containerName="etcd"
```

### What did you expect to happen?

automatically remove missing logs

### How can we reproduce it (as minimally and precisely as possible)?

Started with `kubeadm init --cri-socket unix:///var/run/cri-dockerd.sock`.
Remove any exited container from docker
Then "Unable to fetch container log stats" error will be triggered

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
```

</details>

### Cloud provider

<details>
self hosted
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux xxx 5.4.0-171-generic #189-Ubuntu SMP Fri Jan 5 14:23:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
cri-dockerd_0.3.9.3-0.ubuntu-focal_amd64
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico CNI 
</details>

**Comment by kannon92** [comment]
cc @haircommander @mikebrow 
tagging you all for cri-stats-provider.

**Comment by kannon92** [comment]
TBH I don't really understand if this is supported.

Code is related to CRIStatsProvider.

**Comment by haircommander** [comment]
yeah this sounds like a bug in cri-dockerd, as it's responsible for cleaning up that link AFAIU. If you cannot reproduce with cri-o or containerd, please open an issue in cri-dockerd repo
