### ISSUE TITLE
Kubernetes unit tests are getting failed to execute due to improper Go Version in dependency file

### ISSUE THREAD

**Issue by srivastav-abhishek** [kubernetes/kubernetes#123256]
### Which jobs are failing?

https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le/1756891004578828288

### Which tests are failing?

Tests are not getting executed due to improper go version.

### Since when has it been failing?

It has been failing since past 4 days.

### Relevant SIG(s)

/sig node

**Comment by srivastav-abhishek** [comment]
This seems to be failing due to improper version addition in dependency files where `go1.22` is added instead of `1.22.0 patch version`. I will raise a PR for it.

**Comment by cpanato** [comment]
fixing that
