### ISSUE TITLE
Move EqualPriority to package ./plugin/pkg/scheduler/algorithm/priorities

### ISSUE THREAD

**Issue by HaiyangDING** [kubernetes/kubernetes#12329]
EqualPriority() is one of the many prioritizer functions in Kubernetes scheduler algorithm. It is now located at package ./plugin/pkg/scheduler while all the other priority functions are in package ./plugin/pkg/scheduler/algorithm/priorities.

I think this is a little confusing and maybe we should move it to package priorities. I would be happy to send a relevant PR.

**Comment by dchen1107** [comment]
cc/ @davidopp

**Comment by davidopp** [comment]
Please feel free to send a PR.

**Comment by mbforbes** [comment]
I think GitHub was supposed to close this with #12376
