### ISSUE TITLE
etcd-master pod is deleted

### ISSUE THREAD

**Issue by hieupham259** [kubernetes/kubernetes#123200]
Hi all, i am a newbie. I'm joining cka course from udemy of Srinath Challa. In ETCD lecture, Srinath said: etcd-master pod is "static pod", K8s will create from above etcd.yaml file after run this command: kubectl delete pods etcd-master -n kube-system --grace-period=0 --force. But when i do it, etcd-master pod dont recreate. I waited a long time but this pod doesn't return.
I don't know how to fix this issue. Please help me. Thanks
![image](https://github.com/kubernetes/kubernetes/assets/98680441/26cc8712-03ff-4cdd-b93b-95ee92933810)

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
