### ISSUE TITLE
[kubeadm] Apparently, it's not possible to change the Node CIDR Mask Size

### ISSUE THREAD

**Issue by vicvi1997** [kubernetes/kubernetes#123208]
### What happened?

BACKGROUND
I'm trying to create a small HA kubernetes cluster with 'kubeadm" following the topology "stacked control plane nodes" described here [1]. Considering I want to have 3 worker nodes, my infra looks as the following:
 - 6 nodes in total ( 3 control plane and 3 worker ).
 - All 6 nodes are within a GCP /28 subnet. In GCP, the first 2 and last 2 IPs of a subnet are unusable for the user. Meaning my cluster can run up to 12 nodes (16 - 2 - 2).
 - I'm also running an internal TCP Load Balancer with an internal IP within the same /28 subnet to distribute the traffic within the 3 control plane nodes, that leaves a total space of 11 nodes for the cluster.
 - Moving on, I decided to have a maximum number of pods per node of 64. For that, I have created a /20 secondary IPv4 range in the subnet, that I can divide into up to 16 /26 alias IP ranges for each node of my cluster.
 - I follow the same strategy for the services CIDR, I want a max of 64 per node, therefore I create a /20 secondary IPv4 range that I can later divide 16 times for each node as /26 alias Ip ranges.

ISSUE
When installing the cluster on the 1st control plane node, when I get to the step of running the command:
 $ sudo kubeadm init --control-plane-endpoint "192.168.0.7:6443" --upload-certs --pod-network-cidr "172.16.0.0/26" --service-cidr "172.16.4.0/26"
I get the error:
 networking.podSubnet: Invalid value: "172.16.0.0/26": the size of pod subnet with mask 26 is smaller than the size of node subnet with mask 24

The thing is, the node subnet mask is not 24, but 28 ( see 2 bulletpoint in background ). I've tried several ways to change this value without success:
 - Via a now deprecated `kubeadm init` flag: --node-cidr-mask-size 28
 - Via providing a kubeadm configuration file [2] via the flag: --config
___
[1]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/#stacked-etcd-topology
[2]
https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/

### What did you expect to happen?

I would expect to be able to configure the Node CIDR Mask Size ( value other than 24 ) during the `kubeadm init` command step. Apparently, this was possible in the past with the flag `--node-cidr-mask-size`, see [3].
___
[3]
https://github.com/kubernetes/kubernetes/issues/111425#issuecomment-1195076050

### How can we reproduce it (as minimally and precisely as possible)?

Trying to mimic a topology like the one described in background:
 - Up to 16 nodes in the cluster ( /28 ).
 - Up to 64 pods per node ( subnet secondary range of /20, that gives enough space for 16 /26 alias ip ranges for all possible 16nodes in the cluster ).
 - Same topology for the services CIDR.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux k8s-control-plane-1.europe-southwest1-a.c.vicvi-k8s.internal 6.1.0-17-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm

kubeadm version: &version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.0", GitCommit:"3f7a50f38688eb332e2a1b013678c6435d539ae6", GitTreeState:"clean", BuildDate:"2023-12-13T08:50:10Z", GoVersion:"go1.21.5", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Container runtime (CRI) and version (if applicable)

<details>
Containerd

Client:
  Version:  v1.7.13
  Revision: 7c3aca7a610df76212171d200ca3811ff6096eb8
  Go version: go1.20.13

ctr: failed to dial "/run/containerd/containerd.sock": connection error: desc = "transport: error while dialing: dial unix /run/containerd/containerd.sock: connect: permission denied"
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
non-related, since this occurs before initializing the cluster with `kubeadm init`.
</details>

**Comment by tamilselvan1102** [comment]
`node-cidr-mask-size` was deprecated. you can use in this case `node-cidr-mask-size-ipv4`

**Comment by neolit123** [comment]
> networking.podSubnet: Invalid value: "172.16.0.0/26": the size of pod subnet with mask 26 is smaller than the size of node subnet with mask 24

that's a valid problem. it's not possible to do that.

how about passing `node-cidr-mask-size-ipv4` as extra arg to KCM?
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#controllermanager-flags

we have no plans to expose this option in the kubeadm config or CLI flags.

/kind support

**Comment by thockin** [comment]
The service CIDR does not get split up per node and anyway, I think you want the /20 networks specified for these flags?

**Comment by thockin** [comment]
If this is "support" we should close the issue quickly

**Comment by neolit123** [comment]
/close

agreed. @vicvi1997 what you want is supported with flags.
