### ISSUE TITLE
Move validation functions of Templates into staging

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#123265]
### What would you like to be added?

It would be ideal to have the validation logic in staging so users of JobTemplate could check for validation errors and log an error.

I think that we would just need a function that returns the fieldErrors and that way we can reuse the same validation logic but also do a bit of validation when using JobTemplates.

### Why is this needed?

In the JobSet project, we are composing the JobTemplate in our JobSet spec. This works fine but we are having trouble validating the JobTemplate. We basically create it and the template can fail. 

We would like to have a way to validate the JobTemplate using the same rules that is in pkg/validation. It would be great if we had a function we could call as part of the API.

See https://github.com/kubernetes-sigs/jobset/issues/422.

**Comment by kannon92** [comment]
The main function we would want to reuse is https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/validation/validation.go#L626.

I am also open to other validation templates being moved to staging if others have usecases for them.

**Comment by alculquicondor** [comment]
It's tricky though. The validation logic uses internal types, which you wouldn't have in the jobset controller.

**Comment by thockin** [comment]
Yeah, unfortunately, the open-coded validation logic is unversioned, which makes it unsuitable.  The right(er) thing to do it try to get everything to declarative validation, so the types carry their own validation information.
