### ISSUE TITLE
Should return an error message when creating a secret consumed by a non-existing SA

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#12327]
I believe it's better to return an error message when one attempts to create a secret consumed by a non-existing SA.

```
$ kubectl get serviceaccount --all-namespaces
NAMESPACE     NAME      SECRETS
default       default   1
kube-system   default   1
$ kubectl create -f build-robot-secret.yaml
secrets/build-robot-secret
```
 No errors for now.

Corresponding `build-robot-secret.yaml`.  Just in case.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: build-robot-secret
  annotations: 
    kubernetes.io/service-account.name: build-robot
type: kubernetes.io/service-account-token
```

**Comment by pmorie** [comment]
Agree, this seems like it should be the appropriate behavior.  @liggitt @deads2k any thoughts?

**Comment by liggitt** [comment]
I don't think so... I don't want object validations that look up other objects. We should either tolerate the annotation or delete the secret in the controller reconciliation (which is what currently happens)

**Comment by dalanlan** [comment]
Any particular reason to avoid cross validation (too much overhead or sth)? 'cause it could be confusing to the user without any error messages.

**Comment by deads2k** [comment]
> Any particular reason to avoid cross validation (too much overhead or sth)? 'cause it could be confusing to the user without any error messages.

I think that validation methods should be static check of an object.  Having individual static methods will allow them to be added to the scheme, allow client side validation,  and eliminates stateful checks.

**Comment by liggitt** [comment]
In general, I'm unhappy with this indirect method of manually creating tokens (create a secret with a magic annotation and wait for "a little while"). I have a WIP pull request to move token generation to an API (https://github.com/GoogleCloudPlatform/kubernetes/pull/8866). The final shape will probably change, but I envision an API to request/create a service account token which would fail if the service account did not exist.

**Comment by davidopp** [comment]
@liggitt Can you update this issue with the current status or close it?

**Comment by liggitt** [comment]
As long as the tokens are generated asynchronously via a controller, I would expect this behavior (allow secret in, clean up invalid secrets in the controller check). I don't want to introduce cross-object validation. I agree it is somewhat confusing, but I think the right fix is to allow more direct request/creation of tokens.
