### ISSUE TITLE
The pod remains in the terminating state for an extended period of time

### ISSUE THREAD

**Issue by Eisenhower** [kubernetes/kubernetes#123365]
### What happened?

When Kubernetes starts a pod, if the pod is deleted while it is still pulling the image, the pod will remain in the terminating state until the image pull is completed before it gets deleted. If the image is large, the waiting time can be particularly long.

### What did you expect to happen?

When deleting a pod, delete it directly without waiting for the image download to complete.

### How can we reproduce it (as minimally and precisely as possible)?

Prepare a relatively large image and ensure it has not been loaded on the Kubernetes node. Start a pod with this image, and delete the pod while it is in the process of pulling the image.

### Kubernetes version

<details>

```console
$ v1.23.6
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by T-Lakshmi** [comment]
Hi @Eisenhower,

You can avoid the extended period of time by forceful deletion of pod using the following command:
**kubectl delete pod --all --force --grace-period=0**

**Comment by kannon92** [comment]
https://github.com/kubernetes/kubernetes/issues/122905

**Comment by Eisenhower** [comment]
> Hi @Eisenhower,
> 
> You can avoid the extended period of time by forceful deletion of pod using the following command: kubectl delete pod **_name of the pod_** --force --grace-period=0
Hi @T-Lakshmi
Hello, the logic for deleting pods is executed by the program. In rare cases, pulling images may cause the delete operation to be blocked, but in most cases, it terminates normally. My concern is whether using force to delete might cause processes within the container to not exit properly. Therefore, I still hope to find a solution at the configuration or framework level.

**Comment by T-Lakshmi** [comment]
Hi @Eisenhower,
Yes, i understand your concern here, thanks for reporting the issue.

In fact this issue is already registered as a new feature under #122905.
As its open source, things will take time to implement.
Please refer #122905 for more details.

**Comment by Eisenhower** [comment]
> Hi @Eisenhower, Yes, i understand your concern here, thanks for reporting the issue.
> 
> In fact this issue is already registered as a new feature under #122905. As its open source, things will take time to implement. Please refer #122905 for more details.

@T-Lakshmi 
OK，thanks

**Comment by kannon92** [comment]
/close

duplicate
