### ISSUE TITLE
kubernetes 1.16 to 1.20

### ISSUE THREAD

**Issue by BingYanlx** [kubernetes/kubernetes#123395]
### What happened?

After upgrading kubelet from version 1.16 to 1.20, I found that 'journal -u kubelet' is unable to query the subsequent logs of kubelet, only the logs from its startup, while 'journal -t kubelet' can retrieve the logs.

### What did you expect to happen?

![image](https://github.com/kubernetes/kubernetes/assets/31502232/87d90fd3-d929-4e65-a3db-1ff3d6532ee7)

### How can we reproduce it (as minimally and precisely as possible)?

1.18 to 1.20 centos7.6

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.20
</details>

### Cloud provider

<details>
..
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liangyuanpeng** [comment]
Both 1.16 and 1.20 are no longer supported versions  (:

/kind support

**Comment by harshanarayana** [comment]
IMHO, this is probably nothing to do with kubelet/k8s for that matter. You should check the journaling config on the system to see what might be leading to this issue

**Comment by VannTen** [comment]
Check if kubelet has a different `kubeletCgroup` than it's default, this can cause the kubelet to "jump" out of his cgroup service on startup and be lost by systemd for the purpose of journald.

**Comment by BingYanlx** [comment]
> Check if kubelet has a different `kubeletCgroup` than it's default, this can cause the kubelet to "jump" out of his cgroup service on startup and be lost by systemd for the purpose of journald.
How can I check the kubeletGroup of the kubelet?

**Comment by BingYanlx** [comment]
My kubelet.service configuration file is as follows:![image](https://github.com/kubernetes/kubernetes/assets/31502232/c65f0e8a-ce3c-473e-9970-2857de80b5e2)
and /apps/conf/kubernetes/kubelet.env is as follows:
![image](https://github.com/kubernetes/kubernetes/assets/31502232/193be03c-0c91-417c-883e-8d37d37f90a6)


> Check if kubelet has a different `kubeletCgroup` than it's default, this can cause the kubelet to "jump" out of his cgroup service on startup and be lost by systemd for the purpose of journald.

**Comment by BingYanlx** [comment]
When I use journalctl -o verbose -u kubelet -f to view the results, the output is as follows:
![image](https://github.com/kubernetes/kubernetes/assets/31502232/19b1fc41-fa66-4e95-b400-fd964a6f398b)

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
