### ISSUE TITLE
Need fencing in HA recovery process

### ISSUE THREAD

**Issue by accelazh** [kubernetes/kubernetes#12338]
Some apps, usually those need access to shared data or legacy apps, need to make sure that there are at least one (HA) and only one (fencing) instance running. Otherwise, if one instance is detected to be down, but still accessing data (e.g. network issue or responsiveless); the second instance is boot up, accessing data too. Data will be corrupted.

The fencing, in above case, need to make sure the first instance is "fully dead" or totally isolated from any access to data. Fencing is commonly used in active-passive HA such as Pacemaker.

One walkaround is to implement leader selection for the app, using etcd/zookeeper. However, it may happen that: instance1 acquires leader => instance1 keep writing but responsiveless => heartbeat timeout and instance2 acquires leader => instance1 still writing => instance2 writes => data corruption. Besides, in may use case, modifying existing apps is not feasible.

Another walkaround is to implement a distributed lock using shared FS (file lock) or etcd/zookeeper. Beside the added overhead of locking every write operation, it has the similar problem: instance1 acquires lock => instance1 becomes responsiveless but still writing => lock timeout => instance2 acquires lock => instance1 still writing => instance2 writes => data corruption.

The code of the app would look like

```
# Enter the app
distributed_lock.lock()

do_things1()
do_things2()
...
do_thingsK()    # lock is acquired by instance2 at this time
do_thingsK+1()    # I'm still writing, so data corrupts
...
do_thingsN()

# Exit the app
distributed_lock.unlock()
```

However, if the app keeps checking lock too frequently, say every heartbeat, the overhead would be unfeasible, yet hard to write the correct code.

So, my point is that the best place to implement fencing is the underlying cluster manager, i.e. k8s.

Related discussion: https://groups.google.com/forum/#!topic/coreos-dev/ZCAywIDVyys

**Comment by dchen1107** [comment]
cc/ @thockin

**Comment by thockin** [comment]
This is the phantom jobs problem.  It's real and it's tricky.  In Borg we
could tell people to link a library to voluntarily self-terminate when they
detected they were a phantom, but that's not tenable in OSS.

I'm not an expert in all the solutions here, though

**Comment by sgotti** [comment]
@accelazh thanks for starting this. My proposal in the related discussion started from the idea to avoid self fencing (an app trying to isolate itself by killing, or by locking) as it's not the most reliable way and can fail for multiple reason. Instead I tried to learn from cluster managers like pacemaker that does node fencing.

The simple idea/proposal that I have in mind is:
Assuming that kubernetes is the unique cluster manager for the cluster nodes, when it detects that a kubelet isn't responding, before scheduling the pods on another node, it should fence the node. The fencing will depend on the underlying infrastructure (cloud provider, bare metal etc...) so it should talk (if possible) with it asking to fence that node and waiting for the fencing completion (here fencing will be just to kill a node, or to remove it's access to the network, storage and so on).

@thockin Do you think that this makes sense in k8s and will be accepted as a PR or are there better ideas?

When instead there are multiple cluster manager on the same nodes, this becomes tricky as they can have different cluster views (due to different ways to detect node health) so they should coordinate with each other. For this reason usually only one cluster manager should be elected as the "real" one, and the other should get the cluster view from it.

I also saw #10563 (rbd mount fencing), this is useful to avoid data corruption but probably just covers a little piece of the puzzle and cannot do automatic recovery (the node owning the lock must come back to remove it, or someone has to manually do it ensuring that the node is really dead)

P.S. some months ago, thinking about a similar idea, I started writing a go library for node fencing (https://github.com/sgotti/go-fence)

**Comment by accelazh** [comment]
If I didn't got it wrong, k8s use etcd to do its leader selection, locking and consensus staff for itself. Does the phantom jobs problem also exists in k8s itself?

If so, when k8s is doing the fencing for us, would there be phantom fencings too, urmm ...?

**Comment by philips** [comment]
@sgotti Instead of relying on killing the host running the kublet could we deny/kill service connections coming from the "dead kubelet" to other services through the service proxy?

**Comment by thockin** [comment]
There's more at stake than the service proxy.  Storage, in particular.
Killing a node is probably the most certain way to go about this, but it
does impose some difficult requirements on bare-metal installations.

**Comment by smarterclayton** [comment]
@timstclair

**Comment by sgotti** [comment]
@philips @thockin yeah. Data corruption is the main concern.

About baremetal, the RedHat cluster fencing agents supports a big number of fencing devices. Some of these are very specialized (for example SCSI fencing with SCSI persistent reservation) and also requires node cooperation to do the unfencing. But just using the ones that do node fencing with on board server management consoles or power switches will be a good start (you can test them with https://github.com/sgotti/go-fence). About cloud providers, new fence providers could be written. Assuming that the fencing is initiated by the k8s master, it needs to be able to talk with the cloud provider to get node status and ask node shutdown/reboot (I'm not sure if this will be always possible).

**Comment by timstclair** [comment]
@smarterclayton I think you meant @timothysc

**Comment by smarterclayton** [comment]
I did, my apologies.

**Comment by timothysc** [comment]
We already enable fencing using RHEL-HA on our end using pacemaker (ref: https://access.redhat.com/articles/1528853) 

In our upstream proposal we sited the long term need indirectly in our design discussions: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/proposals/high-availability.md

**Comment by sgotti** [comment]
@timothysc Sorry if I missed something, but doesn't this just covers different ways to achieve master components HA?

The issue/my proposal is instead related on enforcing some types of app/pod (for example apps accessing shared data) to run "at most once" to avoid data corruption. 

Actually, when the master thinks that a kubelet is dead it will schedule the pods on another node. In different scenarios like network partitions, slow node, hung kubelet etc... this can bring to have multiple apps running and causing data corruption.

The idea was to use node fencing before rescheduling pods.

Additionally a similar problem can also be extended to different cases not involving the app but also the kubelet (for example the kubelet mounts the storage volumes, and those of block device type with ext4 or other non global fs on top shouldn't be mounted by more than one node).

@thockin @timothysc I'll be happy to put down a draft proposal detailing these scenario if you think that the idea is feasible. If you already thought about this and had better ideas just let me know. Thanks!

**Comment by timothysc** [comment]
The proposal provides an api such that introspective applications can also do their own lock/leasing, but there currently doesn't exist an internal construct to ensure that there is at most only one under * conditions.  

However, with some of the api changes + containerized pacemaker we could create the construct, but I would almost consider it an anti-pattern to how kubernetes operates.

**Comment by bgrant0607** [comment]
This can't be solved in general without something like [three-phase commit](https://en.wikipedia.org/wiki/Three-phase_commit_protocol), in which the application participates.

In general, if a node is unreachable it can't be killed, kind of by definition.

**Comment by kfox1111** [comment]
@bgrant0607 not quite true. many systems have back channels, so if the node is unresponsive and bare metal, you can use ipmi to power cycle it, if a vm, ask the cloud to power cycle it. If you can control the network switches, cut off all its network ports. etc. There are a lot of existing fencing tools that do this.

**Comment by timothysc** [comment]
@kfox1111 that's what pacemaker does as mentioned above.

**Comment by smarterclayton** [comment]
Fencing is a multi layer solution that can involve:

1. The application
2. The daemon running the application
3. Another heartbeating daemon on the application
4. The kernel / hardware module on the machine
5. The IPMI firmware
6. The rack firmware
7. The top of rack switch
8. The data plane routers
9. Other participants like the storage servers
10. The network of the storage servers

etc to infinity.

I think fencing has a place in Kube.  But I think it would be best if
fencing was *reactive* (level driven) based on the kube state, which I
think is a massive win over the current fencing approach.  Volume fencers
are abstracted by the GCE/AWS/Cinder APIs.  Hardware fencers can also be
participants in the process.  Network fencers can be observers.  As long as
they are subordinate to the central "lock" (the apiserver) we can make this
controllable and predictable.


On Fri, Sep 2, 2016 at 12:44 PM, Timothy St. Clair <notifications@github.com

**Comment by smarterclayton** [comment]
Now covered by proposal https://github.com/kubernetes/kubernetes/pull/34160

**Comment by kargakis** [comment]
@smarterclayton can we close this issue now that https://github.com/kubernetes/community/pull/124 is merged?

**Comment by smarterclayton** [comment]
Not really, because any storage volume that isn't a cloud provider or ceph isn't fenced and would horribly blow up in a couple of cases today.

**Comment by kargakis** [comment]
@kubernetes/sig-storage-misc

**Comment by kvaps** [comment]
Hi, I wrote and currently testing my own implementation of fencing. It uses classic fence-agents from clusterlabs, but it can use something else, if you interested in it, please take a look:
https://github.com/kvaps/kube-fencing
