### ISSUE TITLE
Due forceful deletion of Statefulset pod, new instace of the pod stuck in Pending state.. 

### ISSUE THREAD

**Issue by Samiksha29** [kubernetes/kubernetes#123338]
### What happened?

After deleting Statefulset forcefully, new instance generated for that stuck in Pending state, new instance is not able to Attach to volume because volume is still showing Attached to old instance. our CSI driver haven't received unmount request for the volume because of that volume detach failed.

### What did you expect to happen?

Even after forceful deletion of Statefulset pod, CSI driver should received unmount request from Kuberenetes.

### How can we reproduce it (as minimally and precisely as possible)?

1] Create Statefulset pod with 10 replica's
2] Delete all pod replica's forcefully using command - kubectl delete pod --all  --force --grace-period=0
3] Watch on new instance started and volume state.
4] New instance pod will stuck in Pending state and volume still showing attach to old pod.

volume list - 
pvc-2bc36143-a3a0-4dd7-9197-a1178b92a220   107.39GB   [node-1]   abc.com/pod-name=default/fio-sts-local-5   -         Attached    node-1    /dev/nvme2n2             0d:1h:0m
pvc-8c2a0071-14fb-4b9c-aabf-b65d681bb6d5   107.39GB   [node-2]   abc.com/pod-name=default/fio-sts-local-4   -         Attached    node-2     /dev/nvme2n2             0d:1h:0m
pvc-ce11e344-f69b-499e-8bdf-12fa032e7519   107.39GB   [node-1]   abc.com/pod-name=default/fio-sts-local-0   -         Attached    node-1     /dev/nvme1n1             0d:19h:57m

pod list - 
fio-sts-local-0   0/1     Pending   0          7m33s   <none>   <none>   <none>           <none>

Note that, this issue is intermediate.

### Kubernetes version

<details>

```console
$ kubectl version - 
# $ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2


</details>


### Cloud provider

<details>

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

$ uname -a
Linux appserv17 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig apps
for triage
