### ISSUE TITLE
TestMakeUserNsManagerFailsPodRecord from pkg/kubelet/userns/userns_manager_test.go is failing 

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#123378]
### Which jobs are failing?

Observed this on our internal CI Job https://prow.k8s.io/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le

### Which tests are failing?

`TestMakeUserNsManagerFailsPodRecord` from pkg/kubelet/userns/userns_manager_test.go 

### Since when has it been failing?

After addition of test with commit  https://github.com/kubernetes/kubernetes/pull/122877 on 17th February Saturday (IST)

### Testgrid link

https://testgrid.k8s.io/ibm-unit-tests-ppc64le#Periodic%20unit%20test%20suite%20on%20ppc64le

### Reason for failure (if possible)

```
[root@maxwells1 kubernetes]# go test ./pkg/kubelet/userns/
--- FAIL: TestMakeUserNsManagerFailsPodRecord (0.00s)
    userns_manager_test.go:396:
                Error Trace:    /root/kubernetes/pkg/kubelet/userns/userns_manager_test.go:396
                Error:          An error is expected but got nil.
                Test:           TestMakeUserNsManagerFailsPodRecord
    userns_manager_test.go:397:
                Error Trace:    /root/kubernetes/pkg/kubelet/userns/userns_manager_test.go:397
                Error:          An error is expected but got nil.
                Test:           TestMakeUserNsManagerFailsPodRecord
FAIL
FAIL    k8s.io/kubernetes/pkg/kubelet/userns    0.121s
FAIL
[root@maxwells1 kubernetes]#
```

### Anything else we need to know?

Though the internal CI job runs on `ppc64le` architecture, we have also observed this on `x86_64` architecture.

### Relevant SIG(s)

/sig testing

**Comment by Rajalakshmi-Girish** [comment]
@rata ^^

**Comment by dims** [comment]
don't see anything on linux for sure (4 hits on windows): https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestMakeUserNsManagerFailsPodRecord

**Comment by saschagrunert** [comment]
I’m wondering how to reproduce this locally. 🤔

**Comment by Rajalakshmi-Girish** [comment]
> I’m wondering how to reproduce this locally. 🤔

Steps to reproduce:
1. git clone https://github.com/kubernetes/kubernetes
2. cd kubernetes
3.  go test ./pkg/kubelet/userns/ -race

**Comment by bart0sh** [comment]
@Rajalakshmi-Girish where did you run it?

Works just fine for me on Ubuntu x86_64:
```
$ go test ./pkg/kubelet/userns/ -race
ok  	k8s.io/kubernetes/pkg/kubelet/userns	1.241s
```

**Comment by rata** [comment]
I can't repro locally, I don't think there is any arch specific issue either. Based on @dims comment and link I guess for some reason this test is running on Windows and os.Chmod there works differently.

This feature is linux-only, so I'll rename the test the include '_linux' and that should solve this issue.

**Comment by rata** [comment]
Isn't there any other way to avoid windows picking this up? Because lot of things are linux only, it would reduce the noise considerably if windows was opt-in.

**Comment by bart0sh** [comment]
I don't see any signs of windows here: https://storage.googleapis.com/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le/1759608942486360064/build-log.txt
It's not a x86_64 Linux, but not a windows for sure.

**Comment by rata** [comment]
@bart0sh the link @dims shared points to windows failures.

**Comment by rata** [comment]
Let's see if this fixes it, otherwise we can remove that test too: https://github.com/kubernetes/kubernetes/pull/123388

**Comment by Rajalakshmi-Girish** [comment]
> @Rajalakshmi-Girish where did you run it?

I ran it in one of our local VMs with centos.
```
cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
[root@maxwells1 kubernetes]#
```

**Comment by bart0sh** [comment]
@rata 
> Let's see if this fixes it, otherwise we can remove that test too: https://github.com/kubernetes/kubernetes/pull/123388

How this suppose to fix a failure on PPC linux? and on x86_64 linux (I guess) mentioned by @Rajalakshmi-Girish above?

**Comment by bart0sh** [comment]
@Rajalakshmi-Girish 
> I ran it in one of our local VMs with centos.

which hw architecture do you run it on? Can you show the output of the `arch` on that machine?

**Comment by rata** [comment]
Ohh, I got it! The CI is running the "go test" as root, with all the capabilities. So all test that rely on not having permissions to write somewhere, fail, as they have capabilities to bypass that.

It seems **completely** weird that this didn't fail before. This smells like:
 * Not all of our CI runs on open PRs
 * The CI was changed to run as root now

Both things can cause lot of noise and failures. If it wasn't any of those, I don't know what could have caused it.

**Comment by Rajalakshmi-Girish** [comment]
> @Rajalakshmi-Girish
> 
> > I ran it in one of our local VMs with centos.
> 
> which hw architecture do you run it on? Can you show the output of the `arch` on that machine?
```
[root@maxwells1 kubernetes]# uname -a
Linux maxwells1.fyre.ibm.com 4.18.0-500.el8.x86_64 #1 SMP Wed Jun 28 00:07:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@maxwells1 kubernetes]#
```

**Comment by rata** [comment]
@bart0sh @Rajalakshmi-Girish 

 it is not arch nor distro, it is that just _some_ are running as root. IMHO, if not all are running as root or unprivileged, it is a bug in our CI configuration.

**Comment by rata** [comment]
I have opened PR #123388  to fix the issue, but the root cause seems to be a bug in our CI.

How can we report that we started running tests on _some_ architectures as root, with all the capabilities, and therefore tests that exercise a permission check failure can't never work in those setups?

**Comment by bart0sh** [comment]
@rata you're right, the test fails when running as root. I'd suggest to fix the test then. In shouldn't fail even if it runs with root privileges.

**Comment by bart0sh** [comment]
@rata I think @dims should know more, but suspect that it was not done recently.

**Comment by rata** [comment]
If it wasn't done recently, those workers running as root didn't run when the PR was open. So _something_ change recently, otherwise the test would have failed (it is not flaky, it always passes as unprivileged and it always fails as root).

**Comment by kannon92** [comment]
> Ohh, I got it! The CI is running the "go test" as root, with all the capabilities. So all test that rely on not having permissions to write somewhere, fail, as they have capabilities to bypass that.
> 
> It seems **completely** weird that this didn't fail before. This smells like:
> 
> * Not all of our CI runs on open PRs
> * The CI was changed to run as root now
> 
> Both things can cause lot of noise and failures. If it wasn't any of those, I don't know what could have caused it.

Yes, the majority of the node related tests are not run on open PRs. We usually delegate feature testing to the author of the PR by triggering presubmits. The node tests are much longer than the required jobs on the PR and they usually filter out alpha jobs.
