### ISSUE TITLE
jwt: min valid payload

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#123318]
- [x] Add a unit test that asserts the min valid payload https://github.com/kubernetes/kubernetes/pull/123458
- [x] Add an integration test that asserts the min valid payload with both RSA/EC based signing https://github.com/kubernetes/kubernetes/pull/123458
- [x] Update the go struct docs on the relevant APIs in k/k with the min valid payload https://github.com/kubernetes/kubernetes/pull/123458
- [x] Update the website docs with this info https://github.com/kubernetes/website/issues/45140 https://github.com/kubernetes/website/pull/45108
- [x] Update the KEP with this info https://github.com/kubernetes/enhancements/pull/4562

/assign @aramase
/sig auth
/triage accepted

**Comment by sftim** [comment]
/kind documentation
as well

**Comment by enj** [comment]
@aramase what all is left from the list above to complete this issue?

**Comment by aramase** [comment]
> @aramase what all is left from the list above to complete this issue?

KEP update was the last pending item for this issue. First 3 items in the list were covered in https://github.com/kubernetes/kubernetes/pull/123458.
