### ISSUE TITLE
Installing the k8s server using kubeadm and restarting it resulted in the master node being unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by flamboyantBox** [kubernetes/kubernetes#123368]
### What happened?

When I rebooted my Linux server and checked the command kubectl get nodes, I encountered an error: unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority

### What did you expect to happen?

can not use

### How can we reproduce it (as minimally and precisely as possible)?

After installing k8s with kubeadmin, after the master node init is completed, the reboot server can view the node information to reproduce it

### Kubernetes version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.8", GitCommit:"395f0a2fdc940aeb9ab88849e8fa4321decbf6e1", GitTreeState:"clean", BuildDate:"2023-08-24T00:50:44Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority

### Cloud provider

person

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chenk008** [comment]
Please compare your kubeconfig in `~/.kube/config`  with `/etc/kubernetes/admin.conf`, they should be the same

**Comment by liangyuanpeng** [comment]
Has your machine’s IP changed after restarting?

**Comment by flamboyantBox** [comment]
> 重启后你的机器IP有变化吗？

It looks unchanged

**Comment by flamboyantBox** [comment]
> 请比较你的 kubeconfig 和`~/.kube/config` ，`/etc/kubernetes/admin.conf`它们应该是相同的

Yes, it's the same

**Comment by flamboyantBox** [comment]
[root@k8s-master ~]# docker logs -f c9deffe8a0a7
I0219 10:00:33.046026       1 server.go:557] external host was not specified, using 192.168.0.25
I0219 10:00:33.046996       1 server.go:164] Version: v1.26.14
I0219 10:00:33.047031       1 server.go:166] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
E0219 10:00:33.047372       1 run.go:74] "command failed" err="failed to create listener: failed to listen on 0.0.0.0:6443: listen tcp 0.0.0.0:6443: bind: address already in use"

This is the log of apiserver which caused the container to not get up

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
