### ISSUE TITLE
Allow users to set KUBECTX

### ISSUE THREAD

**Issue by ORESoftware** [kubernetes/kubernetes#123455]
### What happened?

```bash
export KUBECONFIG=xyz
```

is a thing

but when we call:

```bash
kubectl config use-context abc
```

it is global - it writes to the file and therefore not safe against multiples sessions or processes. This is not just a missing feature - this is a bug waiting to happen.

Please allow users to:

```bash
export KUBECTX=abc
```

and of course if abc doesn't exist in xyz (the current config) -it should throw an error

### What did you expect to happen?

expect env var for context/ctx

### How can we reproduce it (as minimally and precisely as possible)?

easy to understand/repro

### Anything else we need to know?

nope

### Kubernetes version

<details>

Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig cli
for feedback

**Comment by mpuckett159** [comment]
/triage accepted
/remove-kind bug
/kind feature
Agreed and this is something that is intended to be worked on in the general overhaul of the kubeconfig that is being attempted.

**Comment by BenTheElder** [comment]
A change like this should probably go through a [KEP](https://github.com/kubernetes/enhancements) before being implemented?

**Comment by soltysh** [comment]
This topic has been actually covered in https://github.com/kubernetes/kubectl/issues/1154, which talks about `--namespace` and `--context` flags being exposed through env vars. For now we've decided not to pursuit this kind of change due to potential impact on the entire ecosystem. For quickly switching between contexts I'd advice users to look into https://github.com/ahmetb/kubectx which is one of the many kubectl plugins. 

/close
