### ISSUE TITLE
In a time leap scenario, it may render the service account token unavailable.

### ISSUE THREAD

**Issue by hwzengzy** [kubernetes/kubernetes#123415]
### What happened?

Starting from Kubernetes version 1.21, Service Account Tokens are obtained through the TokenRequest API to acquire a JWT token with a specific expiration time. If the token's validity exceeds 24 hours or 80% of ExpirationSeconds, kubelet will proactively refresh the token.

In a time leap scenario, if the system time is adjusted to a time beyond the token's expiration, kubelet will refresh the token automatically, ensuring no issues arise. However, if the system time is set to a time before the token's validity period, kubelet will not automatically update the token, leading to a 401 error when containers attempt to access the API server.

### What did you expect to happen?

If the system time is adjusted to a time before or after the token's validity period, kubelet will proactively refresh the token for the pod.

### How can we reproduce it (as minimally and precisely as possible)?

1. View service account token details:
    `cat /var/lib/kubelet/pods/{pod uid}/volumes/kubernetes.io~projected/kube-api-access-xxxx/token`
2. Parse the JWT token, check the "iat" field, and then adjust the system time to be earlier than that time.

3. Subsequently, you will notice a large number of client 401 errors in the kube-apiserver logs:

    E0220 00:01:07.525160       1 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, service account token is not valid yet]"
    I0220 00:01:07.525322       1 httplog.go:131] "HTTP" verb="GET" URI="/api" latency="856.07µs" userAgent="test/v0.0.0 (linux/arm64) kubernetes/$Format/test" audit--
    ID="f8a8a29a-6f95-427d-b467-e4997d29aa25" srcIP="172.16.0.133:47038" resp=401

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.3-h0.dsiv.test.r3-dirty", GitCommit:"308d9d6535243cebbce78461f486b6f42b6d24d9", GitTreeState:"dirty", BuildDate:"2024-02-06T02:23:07Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.3-h0.dsiv.test.r3-dirty", GitCommit:"308d9d6535243cebbce78461f486b6f42b6d24d9", GitTreeState:"dirty", BuildDate:"2024-02-06T02:21:30Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/arm64"}
</details>

### OS version

$ cat /etc/os-release
NAME="EulerOS"
VERSION="2.0 (SP12)"
ID="euleros"
VERSION_ID="2.0"
PRETTY_NAME="EulerOS 2.0 (SP12)"
ANSI_COLOR="0;31"

$ uname -a
Linux Storage 5.10.0-136.12.0.86.h1398.eulerosv2r12.aarch64 #1 SMP Tue Dec 12 04:12:20 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Install tools
kubeadm

**Comment by neolit123** [comment]
> In a time leap scenario, if the system time is adjusted to a time beyond the token's expiration, kubelet will refresh the token automatically, ensuring no issues arise. However, if the system time is set to a time before the token's validity period, kubelet will not automatically update the token, leading to a 401 error when containers attempt to access the API server.

this seems like something that can be improved.
SIG auth can provide feedback.

but FWIW, time leap can break a lot of things and is generally not advisable.
the kubelet automatic client cert rotation comes to mind. we (at kubeadm) continue to occasionally get reports where the kubelet client cert did not renew "on time".

**Comment by hwzengzy** [comment]
I submitted a PR.
When the kubelet determines that the token is later than the system time, it will be refreshed, as if the token is about to expire.

**Comment by enj** [comment]
/close

Per https://github.com/kubernetes/kubernetes/pull/123432#discussion_r1516373259

**Comment by kolserdav** [comment]
/open

Because of this, I have to re-initialize the cluster on the local machine every day! The next day, the tokens disappear and the pods stop working, and after rebooting, `k8s` does not respond at all, only 
```sh
kubeadm reset
kubeadm init
```
 helps.

Any ideas?
