### ISSUE TITLE
Cleanup to commonize utility function for CronJob and Job

### ISSUE THREAD

**Issue by mimowo** [kubernetes/kubernetes#123445]
This is a follow up to the discussion https://github.com/kubernetes/kubernetes/pull/123380#discussion_r1494914346

Both controllers currently use the same `IsJobFinished` function, semantically [CronJob](https://github.com/kubernetes/kubernetes/blob/47737eca1e5daf486d6a2ef4c642655531e776d9/pkg/controller/cronjob/utils.go#L290), and [Job](https://github.com/kubernetes/kubernetes/blob/47737eca1e5daf486d6a2ef4c642655531e776d9/pkg/controller/job/utils.go#L26).

The proposed idea is to place them under `pkg/controller/job/util`. Potentially more functions might be moved there, but the one catches attention already.

**Comment by anishbista60** [comment]
@mimowo 
i have good knowledge of golang and beginner to writing k8s controller. Currently working on issue of kubevirt. Could you please assigned me with beginner friendly task ?

**Comment by kushalShukla-web** [comment]
is this issue still open wanted to work on it

**Comment by kaisoz** [comment]
Hey @hrishikeshdkakkad @kushalShukla-web!

This issue has been fixed in #123537 and is ready for approval. It didn't happen yet because approvers are busy with the code freeze and Kubecon.

@anishbista60 I suggest you to have a look at the open issues with the `good-first-issue` label which are still free :). The [Getting started](https://www.kubernetes.dev/docs/guide/) guide will surely help

**Comment by anishbista60** [comment]
@kaisoz Every issue has assignee working on

**Comment by kaisoz** [comment]
@anishbista60 I know it can be challenging to find a issue to work on. However, I recommend to have a look at those stalled and politely ask to take over. There are some (specially the older ones) which are not being worked on despite of having and asignee

**Comment by theabhinavdas** [comment]
It's surprising to see people trying to get an issue assigned to them when there's clearly a linked pull request that's under review 🤦
