### ISSUE TITLE
`util.NextPod` leaks goroutine

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#123480]
/sig scheduling
/kind cleanup

Ref: https://github.com/kubernetes/kubernetes/pull/122627#discussion_r1451648811

A test helper function `util.NextPod` creates a goroutine to pop a Pod from the scheduling queue. This goroutine never stops until the scheduling queue is `Close()`ed or `testCtx.Scheduler.NextPod(logger)` is somehow stopped for waiting for a new Pod. Ideally, when reaching timeout, we should somehow stop `testCtx.Scheduler.NextPod(logger)` from waiting for Pod to be enqueued to activeQ.
https://github.com/kubernetes/kubernetes/blob/master/test/integration/util/util.go#L1163

**Comment by AxeZhan** [comment]
We can replace this `timeout` function with `PollUntilContextTimeout` and it should be enough? 
I think we no longer need to maintain this function.
https://github.com/kubernetes/kubernetes/blob/781da7595167f872662db3bb62290d1b0522f666/test/integration/util/util.go#L1127

**Comment by sanposhiho** [comment]
No, the core of this problem is that we cannot cancel once we start `Scheduler.NextPod`.
Even if we change `timeout` function to whatever, we will hit this problem.

**Comment by sanposhiho** [comment]
Or, alternatively and much more easily, maybe we can just replace all `NextPod` with `NextPodOrDie` and remove `NextPod`. `NextPodOrDie` kills the entire test if reaching timeout and we could care less about leaked goroutine then.

**Comment by AxeZhan** [comment]
> Or, alternatively and much more easily, maybe we can just replace all NextPod with NextPodOrDie and remove NextPod. NextPodOrDie kills the entire test if reaching timeout and we could care less about leaked goroutine then.

I don't think we can do this.

From the test case:
```
	// Pod2 and Pod3 are not expected to be popped out.
	// - Although the failure reason has been lifted, Pod2 still won't be moved to active due to
	//   the node event's preCheckForNode().
	// - Regarding Pod3, the NodeTaintChange event is irrelevant with its scheduling failure.
	podInfo = testutils.NextPod(t, testCtx)
	if podInfo != nil {
		t.Fatalf("Unexpected pod %v get popped out", podInfo.Pod.Name)
	}
```
The expected behavior of this case is that we revecive a timeout to make sure no pods are added to `activeQ`.
So, reaching timeout is acutally a success.

So, I think:
option 1: using sth like this in `p.Pop()`:
```
done := make(chan struct{})
go func() {
 	for p.activeQ.Len() == 0 {
		p.cond.Wait()
	}
  close(done)
}()
select {
case <-time.After(timeout):
  // timed out
case <-done:
  // Wait returned
```

option2: do sth in the test code

This part is where it confused me.
The current code is fine as we closed schdulerQueue after called `NextPod`, and after#122627 I think there is no test case using this this function anymore(seeems that you refactored the test), so are we trying to solve a potential problem?

**Comment by sanposhiho** [comment]
/close

https://github.com/kubernetes/kubernetes/pull/125433
