### ISSUE TITLE
Why is the service type of nodeport downgraded from ipvs to iptables

### ISSUE THREAD

**Issue by smallemployees** [kubernetes/kubernetes#123404]
### What happened?

Why is the service type of nodeport downgraded from ipvs to iptables

### What did you expect to happen?

Can't load balancing type complete forwarding? Why is it downgraded to iptables

### How can we reproduce it (as minimally and precisely as possible)?

Want to understand the reason

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.23
</details>

### Cloud provider

<details>
no
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/sig  network
/close

**Comment by neolit123** [comment]
if the support forums cannot help you and you suspect a bug try reopening this ticket but add full details and logs.
