### ISSUE TITLE
Service is not deleting endpoint and endpointslice when i do the update without the selector

### ISSUE THREAD

**Issue by yurivenancio30** [kubernetes/kubernetes#123471]
### What happened?

I applied the service with the selector to match a pod in the cluster, but when i do the update in the same service removing the selector, the endpoint and the endpointslices are not deleted from the cluster. On the contrary, when update the service removing the selector, other endpointslice is created pointing to the same pod from when i had the selector existing in the service, , staying with 2 endpointslices and 1 endpoint. The service still points to the same pod even without any selector.

### What did you expect to happen?

I expected that when the service was updated the endpoint and the endpointslice were deleted from the cluster, like when i add a service with any selector. The service shouldn't point to the pod, because now the service is without any selector, but keeps pointing to the same pod, even without any selector.

### How can we reproduce it (as minimally and precisely as possible)?

First, apply the pod and the service with the selector. After, apply the service removing the selector and run `kubectl get endpointslices` to see the 2 endpointslices.
```apiVersion: v1
kind: Pod
metadata:
  name: endpoint-pod
  namespace: default
  labels:
    environment: endpoint
spec:
  containers:
    - args: [sleep, infinity]
      image: busybox
      imagePullPolicy: Always
      name: teste-service
      resources:
        limits:
          cpu: 1200m
          memory: 1400Mi
        requests:
          cpu: '1'
          memory: 1400Mi
      ports:
        - containerPort: 8080
  ```
```apiVersion: v1
kind: Service
metadata:
  name: endpoint-service
  namespace: default
spec:
  selector:
    environment: endpoint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3-gke.1203001
```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=77d913a39ed76e488be139379dffe44e172527f9
GOOGLE_CRASH_ID=Lakitu
VERSION=109
VERSION_ID=109
BUILD_ID=17800.66.19
# paste output here
$ uname -a
Linux gke-private-cluster-pool-3-9c7b6894-pg85 6.1.58+ #1 SMP PREEMPT_DYNAMIC Sat Nov  4 14:14:29 UTC 2023 x86_64 Intel(R) Xeon(R) CPU @ 2.80GHz GenuineIntel GNU/Linux
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.7.7
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yurivenancio30** [comment]
sig network
sig apps

**Comment by aojea** [comment]
@yurivenancio30 dup of this https://github.com/kubernetes/kubernetes/issues/118376, no?

**Comment by thockin** [comment]
Close as dup!
