### ISSUE TITLE
[Flaking Test] [sig-apps][sig-architecture] sig-release-master-informing (Conformance - EC2 - master)

### ISSUE THREAD

**Issue by SubhasmitaSw** [kubernetes/kubernetes#123462]
### Which jobs are flaking?

https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20EC2%20-%20master&show-stale-tests=

### Which tests are flaking?

1. [sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]
2. [sig-architecture] Conformance Tests should have at least two untainted nodes [Conformance]

### Since when has it been flaking?

These tests flake regularly in almost 2-3 days intervals. `Might cause a NO/GO to upcoming RCs! `

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20EC2%20-%20master&show-stale-tests=

### Relevant SIG(s)

**Comment by SubhasmitaSw** [comment]
/ sig apps architecture

**Comment by pacoxu** [comment]
/cc @alculquicondor @soltysh @janetkuo 
- some related issue before: https://github.com/kubernetes/kubernetes/issues/118928 and https://github.com/kubernetes/kubernetes/issues/69601

**Comment by pacoxu** [comment]
The tests failed [FAILED] as Conformance test suite needs a cluster with at least 2 nodes. 
/cc @ameukam 
- This may be an infra problem according to the failing reason. 

Or can we skip if the infra is flaky? 

/sig k8s-infra

**Comment by ameukam** [comment]
@pacoxu There were 3 instances created and deleted:

```bash
I0304 04:46:53.400815    3239 deployer.go:155] deleted instance id: i-0b5893d63f85b60bc
I0304 04:46:53.718314    3239 deployer.go:155] deleted instance id: i-098bba2873b0ff3df
I0304 04:46:54.032940    3239 deployer.go:155] deleted instance id: i-097b5ecb2c80639c4
```
I think this meet Conformance node requirement. What the failing error that suggests it's an infrastructure problem ?

**Comment by ameukam** [comment]
@dims is currently working a lot on this.

**Comment by pacoxu** [comment]
```

Kubernetes e2e suite: [It] [sig-architecture] Conformance Tests should have at least two untainted nodes [Conformance]

{ failed [FAILED] 
Conformance requires at least two nodes In [It] at: 
Expected
    <int>: 1
to be >
    <int>: 1
k8s.io/kubernetes/test/e2e/architecture/conformance.go:45 @ 03/03/24 17:38:46.024 }


I0303 17:39:59.427966 61877 daemon_set.go:140] pods: {"kind":"PodList","apiVersion":"v1","metadata":{"resourceVersion":"15763"},"items":null}

< Exit [AfterEach] [sig-apps] Daemon set [Serial] - k8s.io/kubernetes/test/e2e/apps/daemon_set.go:122 @ 03/03/24 17:39:59.45 (55ms)
> Enter [DeferCleanup (Each)] [sig-apps] Daemon set [Serial] - k8s.io/kubernetes/test/e2e/framework/node/init/init.go:34 @ 03/03/24 17:39:59.45
I0303 17:39:59.450363 61877 helper.go:121] Waiting up to 7m0s for all (but 0) nodes to be ready
< Exit [DeferCleanup (Each)] [sig-apps] Daemon set [Serial] - k8s.io/kubernetes/test/e2e/framework/node/init/init.go:34 @ 03/03/24 17:39:59.461 (11ms)
> Enter [DeferCleanup (Each)] [sig-apps] Daemon set [Serial] - k8s.io/kubernetes/test/e2e/framework/metrics/init/init.go:35 @ 03/03/24 17:39:59.461
< Exit [DeferCleanup (Each)] [sig-apps] Daemon set [Serial] - k8s.io/kubernetes/test/e2e/framework/metrics/init/init.go:35 @ 03/03/24 17:39:59.461 (0s)
> Enter [DeferCleanup (Each)] [sig-apps] Daemon set [Serial] - dump namespaces | framework.go:218 @ 03/03/24 17:39:59.461
STEP: dump namespace information after failure - k8s.io/kubernetes/test/e2e/framework/framework.go:297 @ 03/03/24 17:39:59.461
STEP: Collecting events from namespace "daemonsets-3276". - k8s.io/kubernetes/test/e2e/framework/debug/dump.go:42 @ 03/03/24 17:39:59.461
STEP: Found 0 events. - k8s.io/kubernetes/test/e2e/framework/debug/dump.go:46 @ 03/03/24 17:39:59.472

```

> What the failing error that suggests it's an infrastructure problem ?

Both test cases are failed for `Conformance requires at least two nodes`.

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-ec2-conformance-latest/1764326435192836096


```

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
+ [[ false == true ]]
Cloud-init v. 23.4.4-0ubuntu0~22.04.1 finished at Sun, 03 Mar 2024 16:40:23 +0000. Datasource DataSourceEc2Local.  Up 69.42 seconds
```
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-ec2-conformance-latest/1764326435192836096/artifacts/logs/i-026cc699a8ec50dbe/cloud-init-output.log Error in  cloud-init-output.log
 seems to be the root cause.

**Comment by BenTheElder** [comment]
/remove-sig k8s-infra

the infra provided by sig k8s infra is working fine, the problem here is the EC2 e2e cluster bringup which is going to be one of cluster-lifecycle, cloud-provider / AWS, or sig testing.

**Comment by pacoxu** [comment]
It flakes in EC2: both arm and amd.

- https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20EC2%20-%20arm64%20-%20master
- https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20EC2%20-%20master

**Comment by SubhasmitaSw** [comment]
@pacoxu The arm EC2 has passed since 04-01 https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20EC2%20-%20arm64%20-%20master 

However, the amd one is flaking regularly. @dims do we have any updates on this, can we help support you in any way to get this closed out?

**Comment by dims** [comment]
@SubhasmitaSw not for 1.30, don't want to touch it as it may break other things. it's failing in the creation of the cluster itself from what i saw, so it's not a test failure per se. So let's give it a pass - as it is still `informing`

**Comment by wendy-ha18** [comment]
Hey @dims 
Just want to let you know these 2 tests `[sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]` and `[sig-architecture] Conformance Tests should have at least two untainted nodes [Conformance]` are currently continue flaking on master-informing [Conformance - EC2 - master](https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20EC2%20-%20master), and failed quite frequent.
- Prow: [link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-ec2-conformance-latest/1804223225975017472).
- Triage: [Link](https://storage.googleapis.com/k8s-triage/index.html?date=2024-06-23&test=should%20rollback%20without%20unnecessary%20restarts) and [link](https://storage.googleapis.com/k8s-triage/index.html?date=2024-06-23&test=Conformance%20Tests%20should%20have%20at%20least%20two%20untainted%20nodes).

Do you have plan to solve this issue in 1.31 release @dims ?

**Comment by Vyom-Yadav** [comment]
From: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-ec2-conformance-latest/1804223225975017472/artifacts/logs/i-0a2c27ef0d3d27b09/cloud-init-output.log

```
server-linux-amd64.tar.gz
+ tar -xvzf kubernetes-server-linux-amd64.tar.gz
kubernetes/
kubernetes/server/
kubernetes/server/bin/
kubernetes/server/bin/kube-apiserver
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
+ [[ false == true ]]
Cloud-init v. 24.1.3-0ubuntu1~22.04.5 finished at Fri, 21 Jun 2024 18:57:06 +0000. Datasource DataSourceEc2Local.  Up 62.99 seconds
```

**Comment by dims** [comment]
@wendy-ha18 let's open fresh issue with the specific test failure. this is an old stale issue.

@Vyom-Yadav looks intermittent right? let's track it separately please.

/close
