### ISSUE TITLE
Problem with local-up-cluster.sh

### ISSUE THREAD

**Issue by hakuna-matatah** [kubernetes/kubernetes#123452]
### What happened?

When you start a local cluster it doesn't setup bridge networking for `containerd containers` at `/etc/cni/net.d/10-containerd-net.conflist ` when it finds `/opt/cni/bin/loopback` locally and ends up with following output i.e Worker Node would never join the cluster because there is no networking setup for the node and kubelet sees it as `CNI networking not setup for node`

```
WARNING : The kubelet is configured to not fail even if swap is enabled; production deployments should disable swap unless testing NodeSwap feature.
2024/02/22 20:37:04 [INFO] generate received request
2024/02/22 20:37:04 [INFO] received CSR
2024/02/22 20:37:04 [INFO] generating key: rsa-2048
2024/02/22 20:37:04 [INFO] encoded CSR
2024/02/22 20:37:04 [INFO] signed certificate with serial number 280440300532529762741846552121807144132451209833
kubelet ( 82838 ) is running.
wait kubelet ready
No resources found
No resources found
No resources found
No resources found
127.0.0.1   NotReady   <none>   2s    v1.30.0-alpha.2.158+6049a1bca4551f-dirty
error: timed out waiting for the condition on nodes/127.0.0.1
^CCleaning up...
Cleaning up...


```

Node doesn't become ready because and kubelet logs shows that CNI  isn't ready and node doesn't become ready no matter how long we wait.

```
2024/02/22 20:37:04 [INFO] signed certificate with serial number 280440300532529762741846552121807144132451209833
kubelet ( 82838 ) is running.
wait kubelet ready
No resources found
No resources found
No resources found
No resources found
127.0.0.1   NotReady   <none>   2s 
```

### What did you expect to happen?

Expect worker node to become ready when `local-up-cluster.sh` seamlessly with networking setup for worker node, so it leads to following output where it will successfully bring up the cluster.

```
To start using your cluster, you can open up another terminal/tab and run:

  export KUBECONFIG=/var/run/kubernetes/admin.kubeconfig
  cluster/kubectl.sh

Alternatively, you can write to the default kubeconfig:

  export KUBERNETES_PROVIDER=local

  cluster/kubectl.sh config set-cluster local --server=https://localhost:6443 --certificate-authority=/var/run/kubernetes/server-ca.crt
  cluster/kubectl.sh config set-credentials myself --client-key=/var/run/kubernetes/client-admin.key --client-certificate=/var/run/kubernetes/client-admin.crt
  cluster/kubectl.sh config set-context local --cluster=local --user=myself
  cluster/kubectl.sh config use-context local
  cluster/kubectl.sh
  ```
 

### How can we reproduce it (as minimally and precisely as possible)?

The way current code works is, when it calls [install_cni_if_needed
](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L1365) it only checks if [/opt/cni/bin/loopback](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L1256C19-L1256C40) is present , and it doesn't check nor configure  if  [`bridge networking config file for containerd containers`](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L1217-L1252) like it sets up when  [install_cni](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L1186) is called.

### Anything else we need to know?

Fix is to check if `/etc/cni/net.d/10-containerd-net.conflist` is also present when calling this [function](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L1254C10-L1257) as its mandatory for successful local_cluster_setup.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

```
dev-dsk-hakuna-2c-0fa5574b % kubectl version                                                                                                 
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0-alpha.2.159+2414f23c341e2b-dirty
```

</details>

### Cloud provider

<details>
local 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
```

```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
```
$ uname -a

```
Linux dev-dsk-hakuna-2c-0fa5574b.us-west-2.amazon.com 5.10.209-175.858.amzn2int.x86_64 #1 SMP Tue Feb 13 18:51:15 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>


### Install tools

<details>
Follow steps [here](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md)
</details>


### Container runtime (CRI) and version (if applicable)

<details>
```
dev-dsk-hakuna-2c-0fa5574b % containerd --version
containerd github.com/containerd/containerd v1.7.13 7c3aca7a610df76212171d200ca3811ff6096eb8
```
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Plugins [here](dev-dsk-hakuna-2c-0fa5574b % containerd --version
containerd github.com/containerd/containerd v1.7.13 7c3aca7a610df76212171d200ca3811ff6096eb8) 
</details>

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
@dims @pohly WDYT?

**Comment by BenTheElder** [comment]
/triage accepted
(tentatively ...)

**Comment by BenTheElder** [comment]
nudged PR review, I think we'll decide on the PR

**Comment by BenTheElder** [comment]
closing based on https://github.com/kubernetes/kubernetes/pull/123453#discussion_r1655682064

please re-open and elaborate if I've gotten this wrong. sorry for the lengthy cycle here.
