### ISSUE TITLE
[Flaking Test] UT TestRoundTripTypes 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#123497]
### Which jobs are flaking?

ci-kubernetes-unit

### Which tests are flaking?

k8s.io/kubernetes/pkg/api: testing 
Failed;  === RUN   TestRoundTripTypes

### Since when has it been flaking?

since 02-25
https://storage.googleapis.com/k8s-triage/index.html?text=TestRoundTripTypes&job=ci-kubernetes-unit

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1761875559492620288
```
    roundtrip.go:360: ServiceList: diff:   &core.ServiceList{
          	TypeMeta: {},
          	ListMeta: {SelfLink: "關衬榦腠ȅ傃", ResourceVersion: "15634087042978939296"},
          	Items: []core.Service{
          		{
          			TypeMeta:   {},
          			ObjectMeta: {Name: "Ǔ|r!飸ɋ6芌ɰw褂堭W葇鑈wwK`", GenerateName: ")ĸmǡJVȀ香Ħã沦ʧ賿4啍8", Namespace: "瀝?郣H", SelfLink: "尶XɊ璫", ...},
          			Spec:       {Type: "LoadBalancer", Ports: {{Protocol: "TCP", AppProtocol: &"ǐ9ʑ氺緿阶ɔ z辔#哭U(柭灥拎憬", Port: -174794998, TargetPort: {IntVal: -52227}, ...}}, ClusterIP: "vɼɕŧ琸嶫F6?ù", IPFamilyPolicy: &"耋d矾翚kÇʈÛ浂龮s]噲急卍ŋ09", ...},
          			Status: core.ServiceStatus{
          				LoadBalancer: core.LoadBalancerStatus{
          					Ingress: []core.LoadBalancerIngress{
          						{
          							IP:       "Ƶva蔗饔v$i",
          							Hostname: "dȄ蜭LƌƘ2d迮豕",
        - 							IPMode:   nil,
        + 							IPMode:   &"VIP",
          							Ports:    nil,
          						},
          					},
          				},
          				Conditions: nil,
          			},
          		},
          	},
          }
```

### Relevant SIG(s)

/sig api-machinery network

**Comment by pacoxu** [comment]
It started to flake after https://github.com/kubernetes/kubernetes/pull/123418

**Comment by Rajalakshmi-Girish** [comment]
It is also flaking in our internal CI on `ppc64le` https://testgrid.k8s.io/ibm-unit-tests-ppc64le#Periodic%20unit%20test%20suite%20on%20ppc64le

https://prow.k8s.io/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le
