### ISSUE TITLE
Disable limit checking for scheduler

### ISSUE THREAD

**Issue by DmitriyLyalyuev** [kubernetes/kubernetes#12345]
Hi.

I have some troubles with resource limitations for pods in namespace.
I want to limit minimum and maximum of CPU and memory usage for each pod in my namespace.
But I do not want the scheduler to check how many resources are already used on the node.

How I can resolve this?

**Comment by pmorie** [comment]
@derekwaynecarr

**Comment by erictune** [comment]
@wojtek-t @gmarek you both are closer to the OP's time zone and know a bit about the scheduler.  Can one of you help him?  As a short term fix, maybe suggest a way to disable the PodFitsResources check.  Also figure out exactly what the user needs (overcommitment?)

**Comment by erictune** [comment]
randomly assigning to @gmarek but feel free to move.

**Comment by DmitriyLyalyuev** [comment]
Yes, I need overcommitment to each nodes.

**Comment by derekwaynecarr** [comment]
There is work underway to support basic overcommit of cpu and memory.

The plan is to do the following:

A container can specify a request for cpu / memory and a limit for cpu and memory.  The scheduler will schedule on the requesting value, but of course the container will be allowed to burst to their limit if the request != limit.

I think this basic support should be in the code base soon, it's a near term priority, just need to work out coordinating delivery.

See the following:

Qos Proposal: https://github.com/GoogleCloudPlatform/kubernetes/pull/11713
Schedule on requests: https://github.com/GoogleCloudPlatform/kubernetes/pull/12035
Limits with QoS: https://github.com/GoogleCloudPlatform/kubernetes/pull/12216
Quota with QoS: https://github.com/GoogleCloudPlatform/kubernetes/pull/12291

**Comment by gmarek** [comment]
@derekwaynecarr wrote pretty much everything I wanted to:) If you need this right now @erictune is right - you can build your own Kubernetes binary with disabled PodFitsResources check. It's not that easy though, as you'll need to disable it both in scheduler and in Kubelet. When the check is disabled everything else (like spreading) should work correctly.

If you need it quickly please let me know - I'll write more precise instructions on what to disable, but with waiting for QoS implementation is probably a better idea, if you're OK with it.
