### ISSUE TITLE
[Bug] framework.Event not working when Node was added

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes/kubernetes#123509]
### What happened?

T1: My pod failed scheduling because of InterPodAffinity:
```
I0226 17:55:16.511750       1 schedule_one.go:188] "Status after running PostFilter plugins for pod" pod="default/nginx-anti-affinity-766965866-fpxqx" status="preemption: 0/2 nodes are available: 1 No victims found on node cn-shenzhen.10.0.3.86 for preemptor pod nginx-anti-affinity-766965866-fpxqx, 1 No victims found on node cn-shenzhen.10.0.5.157 for preemptor pod nginx-anti-affinity-766965866-fpxqx., "
```

T2: One node was added to cluster by ClusterAutoscaler, and there is a taint {"key":"node.kubernetes.io/not-ready","effect":"NoSchedule"} on node so the pod didn't pass the func preCheckForNode(nodeInfo). This is reasonable:
```
I0226 17:55:31.361891       1 eventhandlers.go:76] "Add event for node" node="cn-shenzhen.10.0.4.9"
```

T3: KCM removed the taints from node, I found the pod was not scheduled:
```
I0226 17:55:50.341010       1 scheduling_queue.go:1104] "Event is not making pod schedulable" pod="default/nginx-anti-affinity-766965866-fpxqx" event="NodeTaintChange"
```
This is the log in my audit:
```
objectRef: {"resource":"nodes","name":"cn-shenzhen.10.0.4.9","apiVersion":"v1"}
requestObject: {"metadata":{"resourceVersion":"33524979"},"spec":{"taints":null}}
requestReceivedTimestamp: 2024-02-26T09:55:50.331949Z
```

Then I found the reason:
We only record the first failed plugin in Filter, so we will miss some event. For example, my pod failed in InterPodAffinity, so TaintToleration was not be executed. InterPodAffinity only return Queue for `{Event: framework.ClusterEvent{Resource: framework.Node, ActionType: framework.Add | framework.UpdateNodeLabel}}`, so my pod did not be scheduled until it was refreshed from unschedulable queue after 5 minutes.

### What did you expect to happen?

Pod which failed scheduling due to InterPodAffinity should be rescheduled when a new node was added to cluster.

### How can we reproduce it (as minimally and precisely as possible)?

Just see what happend section.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.28.3
And I think there is the same problem because the code is not changed.
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by KunWuLuan** [comment]
I think just change `{Event: framework.ClusterEvent{Resource: framework.Node, ActionType: framework.Add | framework.UpdateNodeLabel}} to {Event: framework.ClusterEvent{Resource: framework.Node, ActionType: framework.Add | framework.Update}}` will help. HDYT?

**Comment by AxeZhan** [comment]
I think this is tracked before, I'm not sure which pr it is. Maybe https://github.com/kubernetes/kubernetes/pull/122292.
/cc @sanposhiho Can you confirm?

**Comment by sanposhiho** [comment]
Yes, we acked this issue and it'll be fixed at the PR @AxeZhan shows.

**Comment by KunWuLuan** [comment]
Great, Thanks!
