### ISSUE TITLE
Docs: When the `--bind-address` parameter of kube-proxy is configured as ipv6, the ip address of metrics listens to 127.0.0.1 by default, instead of::1

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#123544]
### What happened?

The `--bind-address` parameter of kube-proxy is configured as ipv6
```
--bind-address=aaaa:bbbb::2e8

```
The metrics port of kube-proxy listens to the ipv4 address
​```
netstat -nlap|grep 10249
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      5412/kube-proxy     
```

### What did you expect to happen?

When the `--bind-address` parameter of kube-proxy is configured as ipv6, the ip address of metrics listens to ::1 by default

### How can we reproduce it (as minimally and precisely as possible)?

The `--bind-address` parameter of kube-proxy is configured as ipv6

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by khenidak** [comment]
Thank you for this. 

Please use `--metrics-bind-address` flag to change metric listening address, docs are here: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/

as for the `--bind-address`, the docs are a bit confusing wrt to this field.

**Comment by songxiao-wang87** [comment]
--metrics-bind-address          ipport     Default: 127.0.0.1:10249
  | The IP address and port for the metrics server to serve on, defaulting to "127.0.0.1:10249" (if --bind-address is unset or IPv4), or "[::1]:10249" (if --bind-address is IPv6).

Set metrics-bind-address to ::1, the effect is as follows：
tcp6       0      0 ::1:10249               :::*                    LISTEN      30567/kube-proxy 

So the document can also be updated. --bind-address may not useful.
