### ISSUE TITLE
Local Travis

### ISSUE THREAD

**Issue by AnanyaKumar** [kubernetes/kubernetes#12353]
Is there a way to run the continuous-integration tests locally? If not, we should create "hack/continuous-integration.sh" and run all the scripts that Travis does! :)

The last couple of days, I've submitted a few PRs that fail on some of the continuous integration checks, so I think having a meta-script that does this would be useful.

**Comment by mbforbes** [comment]
local Jenkins would also be incredibly useful

**Comment by ihmccreery** [comment]
@AnanyaKumar Can you elaborate on what tests have failed?  I would expect that [running e2es](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#end-to-end-tests) would be a good first step; has that not suited your needs?

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by spiffxp** [comment]
/close
see https://github.com/kubernetes/test-infra#automated-testing
