### ISSUE TITLE
Patching metadata.labels field of volumeclaimtemplate in a statefulset is forbidden

### ISSUE THREAD

**Issue by navilg** [kubernetes/kubernetes#123551]
### What happened?

When I try to patch STS's volumeClaimTemplate metadata.labels, It fails to patch it with error message "Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template' ...."

### What did you expect to happen?

It should allow to patch the fields in volumeclaimtemplate which are allowed to be patched in PVC

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a statefulset with volumeclaimtemplate in it. It will create statefulset pods and PVC using volumeclaimtemplate
2. Try to edit labels inside volumeclaimtemplate of statefulset
3. It fails with above mentioned error

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.0
Kustomize version: v5.0.4-0.20230601165947-6ce0bf390ce3 
Server Version: v1.28.3-gke.1286000
```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Containerd 1.7.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
I think this is a feature request rather than a bug. Not sure.

**Comment by neolit123** [comment]
> When I try to patch STS's volumeClaimTemplate metadata.labels, It fails to patch it with error message "Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template' ...."

/sig apps

**Comment by navilg** [comment]
I think its currently a bug as it doesnot allow to mutate the values which it actually should allow (pvc labels) and can be fixed by a new feature

**Comment by liggitt** [comment]
This is a feature request, not a bug. 

It's essentially the same as https://github.com/kubernetes/kubernetes/issues/121178, but for labels, so deduplicating against that one
