### ISSUE TITLE
Duplicated shortname "vs"

### ISSUE THREAD

**Issue by ericitaquera** [kubernetes/kubernetes#123514]
### What happened?

Hello.

I just noticed that "vs" shortname is set for both "virtualservices" and "volumesnapshots".

`$ for i in $(k api-resources); do if [ "$(echo $i | awk '{print NF}')" == "5" ]; then echo $i; fi; done | sort -k2 | grep vs
volumesnapshotclasses               vsclass,vsclasses        snapshot.storage.k8s.io            false        VolumeSnapshotClass
volumesnapshotcontents              vsc,vscs                 snapshot.storage.k8s.io            false        VolumeSnapshotContent
virtualservices                     vs                       networking.istio.io                true         VirtualService
volumesnapshots                     vs                       snapshot.storage.k8s.io            true         VolumeSnapshot
`

### What did you expect to happen?

By the above, it looks like my system...
`]$ kubectl version
W0226 11:09:40.682098 1183782 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.10-gke.1101000", GitCommit:"375ed214cfa092ed25d2472c1709db5d7dcda078", GitTreeState:"clean", BuildDate:"2023-11-06T09:23:17Z", GoVersion:"go1.20.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
`
...considers "vs" as the shortname for "volumesnapshots" since "kubectl get vs -A" returns no virtualservices even I having thousands of them in the cluster. =)

### How can we reproduce it (as minimally and precisely as possible)?

I noticed this behavior on 1.26 and 1.27 clusters (Google's  GKE). 

I think the below would helps to reproduce in bash.
`export IFS=$'\n'
for i in $(k api-resources); do if [ "$(echo $i | awk '{print NF}')" == "5" ]; then echo $i; fi; done | sort -k2 | grep vs`

It should show both virtualservices and volumesnapshots with "vs" shortname.

### Kubernetes version

<details>

```console
$ kubectl version
W0226 11:09:40.682098 1183782 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.10-gke.1101000", GitCommit:"375ed214cfa092ed25d2472c1709db5d7dcda078", GitTreeState:"clean", BuildDate:"2023-11-06T09:23:17Z", GoVersion:"go1.20.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
$ uname -a
Linux gcp-anthos01 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
both "vs" objects are custom resources. while Istio is not a k8s subproject, "volumesnapshots" originated by the K8S group SIG Storage, so that's closer to core k8s:
https://github.com/kubernetes/enhancements/blob/cf6ee34e37f00d838872d368ec66d7a0b40ee4e6/keps/sig-storage/177-volume-snapshot/README.md?plain=1#L457

either way, kubectl likely just decides to pick one of them.

> It should show both virtualservices and volumesnapshots with "vs" shortname.

that's a SIG CLI request
/sig cli

**Comment by ardaguclu** [comment]
Best we can do with respect to this topic is to add a warning about this ambiguity and that was added by https://github.com/kubernetes/kubernetes/pull/117668

**Comment by ericitaquera** [comment]
> Best we can do with respect to this topic is to add a warning about this ambiguity and that was added by #117668

Besides this warning, it´d be kind if major k8s projects would observe some agreement on not to overlap each other´s shortnames. =)

Istio is not a minor peripheral project and, AFAIK, they "reserved" 'vs' first.

Many thousands of people around the globe may be using vs shortname in their scripts which broke when the new vs arose. 

Regards!

**Comment by ardaguclu** [comment]
Thanks for dropping your thoughts @ericitaquera. As kubectl maintainers, we always recommend to use fully qualified resource names to prevent such short name collisions

**Comment by sftim** [comment]
/remove-kind bug

I don't see any fault here.

**Comment by ardaguclu** [comment]
Unfortunately, there is no guarantee with respect to priorities (even maybe it is alphanumerical sorting). But as I mentioned above, fully qualified usage is recommended.

/close
