### ISSUE TITLE
--feature-gates=AllAlpha=true  make error

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#123665]
### What happened?

```
I0304 16:55:26.081185  109523 healthz.go:261] informer-sync,poststarthook/start-service-ip>
[-]informer-sync failed: 2 informers not started yet: [*v1alpha1.IPAddress *v1alpha1.Servi>
[-]poststarthook/start-service-ip-repair-controllers failed: not finished
[-]poststarthook/rbac/bootstrap-roles failed: not finished
[-]poststarthook/start-kubernetes-service-cidr-controller failed: not finished
[-]poststarthook/built-in-resources-storage-version-updater failed: not finished
```

make --feature-gates=AllAlpha=true

root@29-a:~# kubectl patch -n k8s pod mypod --type='json' -p='[{"op": "replace", "path": "/spec/containers/0/resources/requests/cpu", "value": "300m"}]'
Error from server (ServiceUnavailable): wait for storage version registration to complete for resource: pods, last seen error: <nil>

### What did you expect to happen?

--feature-gates=AllAlpha=true
everything is good

### How can we reproduce it (as minimally and precisely as possible)?

kube-apiserver,kube-controller-manager,kube-schedule,kubelet config
--feature-gates=AllAlpha=true

### Kubernetes version

<details>
root@29-a:~# kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0

</details>

### Cloud provider

<details>
vmware
</details>

### OS version

<details>

```console
root@29-a:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> root@29-a:~# kubectl patch -n k8s pod mypod --type='json' -p='[{"op": "replace", "path": "/spec/containers/0/resources/requests/cpu", "value": "300m"}]'
Error from server (ServiceUnavailable): wait for storage version registration to complete for resource: pods, last seen error:

how is this related to the alpha feature gate?

/sig architecture
/triage needs-information

**Comment by 13567436138** [comment]
In-Place Pod Vertical Scaling
modify resources requests or limits cpu memory

**Comment by kannon92** [comment]
I am very confused on what you are trying to do.

Starting Kubernetes using the AllAlpha feature gate is not really supported. You should try enabling the feature you want in that config.

We use the AllAlpha feature gate as shorthand in the CI but I don't think that is supported for.

If you are builing locally, you could try FEATURE_GATES=... hack/local-up-cluster.

I don't really expect make to work with those feature gates as most of our features are not build time dependent.
