### ISSUE TITLE
goland not recognizing staging  modules with new go workspaces

### ISSUE THREAD

**Issue by aroradaman** [kubernetes/kubernetes#123653]
I'm not sure if this is an actual issue or an issue with my Goland configuration. 
Opening this for confirmation, feel free to close it 🙂

**Comment by aroradaman** [comment]
maybe linked with https://github.com/kubernetes/kubernetes/pull/123529

**Comment by aojea** [comment]
> maybe linked with #123529

it seems is supported in goland https://www.jetbrains.com/help/go/go-workspaces.html

**Comment by dims** [comment]
@aojea yea, it's not working with staging repos as our root go.mod still has v0.0.0

**Comment by aroradaman** [comment]
screenshot for reference. 

<img width="1728" alt="Screenshot 2024-03-03 at 9 11 56 PM" src="https://github.com/kubernetes/kubernetes/assets/6954627/51128770-fde9-4c20-afbf-d2ffd5b5c25a">

**Comment by aojea** [comment]
do we know why it works in vscode and gopls but not in goland?
can we open in parallel a support case with jetbrains to understand better what is the difference?

**Comment by thockin** [comment]
I don't use goland, but given that Go itself works and gopls, and (anecdotally) vscode, this sounds like a goland issue, doesn't it?

**Comment by aroradaman** [comment]
> I don't use goland, but given that Go itself works and gopls, and (anecdotally) vscode, this sounds like a goland issue, doesn't it?

yeah, just wanted to see if other folks are facing the same issue with Goland. Will close this issue in a day or two.

**Comment by dims** [comment]
@thockin i requested @aroradaman to open this one. yes, it feels like a goland issue for sure. Wanted a spot for folks to trade info on workarounds.

**Comment by akhilerm** [comment]
![Screenshot from 2024-03-04 08-39-27](https://github.com/kubernetes/kubernetes/assets/7610845/4f4bdf5b-c045-4799-9484-e6cb5f5a2485)

You can disable vendoring support in goland settings, then invalidate the caches and restart.  This will resolve the imports directly to the staging directory instead of via the vendor directory.

**Comment by aroradaman** [comment]
thanks @akhilerm this works!

**Comment by Karthik-K-N** [comment]
Using VSCode and the editor is failing to resolve to definition or usages of any struct membeers for K8s repo, I do have latest VSCode and golang version, Is there any configuration needs to be enabled to make it work with go.work?

Where as it works well with other repos which are not having go.work.

**Comment by chaochn47** [comment]
FWIW, removing `go.work` and `go.work.sum` helps in Goland 2022.1 since the vendoring support cannot be disabled in its setting. 

<img width="984" alt="image" src="https://github.com/kubernetes/kubernetes/assets/54131596/2c39833a-4496-4a9f-b93d-90acfff54e38">

**Comment by dims** [comment]
@chaochn47 in that `Environment` box, `GOWORK=off` should work as well
