### ISSUE TITLE
typo error in volume name section of pod json causes default of 'emptyDir' by default - should only accept approved values

### ISSUE THREAD

**Issue by screeley44** [kubernetes/kubernetes#12361]
```json
"volumes": [
  {
    "name": "phpvol1",
    "glusterf": {      <-- accidentally missed the 's' for the volume type and got defaulted to emptyDir
      "endpoints": "glusterfs-cluster",
      "path": "myVol",
      "readOnly": false
    }
  }
```

if the value specified is not in the list then an error should be thrown back to the user stating that "volume type of XXXXXX is not a valid type"

currently any value is accepted but if not recognized defaults to emptyDir type

**Comment by thockin** [comment]
This should be more obvious now that --validate is on by default.
