### ISSUE TITLE
Ubuntu kubernetes-xenial package repository issue

### ISSUE THREAD

**Issue by jaingaurav001** [kubernetes/kubernetes#123673]
### What happened?

I am trying to deploy kubernetes (kubeadm) on x86_64 based Ubuntu 20.04 virtual machine.
I am getting the follwoing error when deploying kubeadm:

$ sudo cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
$ sudo mkdir -p /etc/apt/keyrings
$ curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
$ echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
$ sudo apt-get update
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Get:2 https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/amd64  InRelease [1484 B]
Hit:3 https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/amd64  InRelease
Hit:4 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal InRelease
Get:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Ign:5 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Err:8 https://packages.cloud.google.com/apt kubernetes-xenial Release
  404  Not Found [IP: 142.250.71.110 443]
Hit:9 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:10 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1170 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal-security/main amd64 Packages [2752 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages [944 kB]
Reading package lists... Done
E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Please help.

### What did you expect to happen?

I am expecting kubernetes-xenial repo to be added successfully for kubernetes package download.

### How can we reproduce it (as minimally and precisely as possible)?

$ sudo mkdir -p /etc/apt/keyrings
$ curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
$ echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
$ sudo apt-get update

### Anything else we need to know?

Please note i was able to add the repo and download the kubernetes till recently (i.e. last tired successfully on 24 Feb 2024).

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On prim
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux na-controller 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
/kind support
/remove-kind bug

See https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

**Comment by jaingaurav001** [comment]
/sig release

It seems like 1.22 is not available via Community-Owned Package Repositories:
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.22/deb/Release.key
curl: (22) The requested URL returned error: 403

Does that mean 1.22 is no longer available? Is there a way to install kubernetes version 1.22 using Community-Owned Package Repositories?

**Comment by xmudrii** [comment]
Please also see https://github.com/kubernetes/release/issues/3485 and https://k8s.io/linuxrepos

> Does that mean 1.22 is no longer available? Is there a way to install kubernetes version 1.22 using Community-Owned Package Repositories?

That's correct, 1.22 is not available in the package repositories any longer. Only versions starting from v1.24 are available in the Kubernetes community-owned package repositories. We're working on some docs on how this can be mitigated, you can follow https://github.com/kubernetes/release/issues/3485 for the latest updates

**Comment by dmashal** [comment]
@xmudrii  How to install kubernetes 1.20.15 in March 2024 now?

**Comment by neolit123** [comment]
a better place to have this discussion is on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by Zetanova** [comment]
@xmudrii  Any change to get the old packages for apt & rpm to upgrade from 1.20 to >1.24. 
Because of the deprecation of the docker-shim and `In-tree Storage Plugin` I postponed the upgrade

**Comment by Zetanova** [comment]
I managed to install kubelet 1.20.15 on ubuntu 22.04.4 over snap and joined it with kubeadm

But it was not easy, required to install missing bin's including cri-tools and cni plugins pack
and add config of kubelet.service to systemd

**Comment by boxoky** [comment]
(Perdonen por no escribir en ingles mi comentario y sea mas universal, pero con google translate pueda ser sencilla la interpretación)

Hola! ... Mismo error con Ubuntu 22.04 LTS.

Definitivamente es por la referencia al repo, podrías eliminar el archivo /etc/apt/sources.list.d/kubernetes.list (con permisos de sudo), las referencias a los repos de kubertenes (si los hay) en el archivo /etc/apt/sources.list.d/sources.list (permisos sudo), y de haber  algún archivo referente a knertenes en /etc/apt/trusted.gpg.d. 

Intentar con los repos y llaves en la referencia actual de kubernetes: https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/ .  Ahí tendrás una buena referencia del porque se hizo el cambio, y podrás saber si en algún momento cambia para futuras instalaciones.

Pero en resumen con esto debería funcionar 

`$ echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list`

`$ curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg`

`$ sudo apt update`

`$ sudo apt install -y kubelet kubeadm kubectl`

Espero funcione con tu caso, igual podrías intentarlo en una versión mas nueva de ubuntu o debian, igual en la referencia hay para mas distros.

**Comment by boxoky** [comment]
@xmudrii  I got it!. In that time just wanted to write in my native language. I understand that the use of English makes the maintenance work easier (unification).  For this reason:

try using the new Kubernetes repositories. You will find the well reasons why the repos references had changed. It may  change in the future, I recommend that you bear this in mind.

$ echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

$ curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

$ sudo apt update

$ sudo apt install -y kubelet kubeadm kubectl

i hope this help you. Happy. happy orquestation <3

**Comment by cyford** [comment]
> I solved this issue. I deleted "/etc/apt/sources.list.d/docker.list" and "/etc/apt/sources.list.d/kubernetes.list" with
> 
> ```
> sudo rm /etc/apt/sources.list.d/docker.list /etc/apt/sources.list.d/kubernetes.list
> ```
> 
> and reinstalled docker & k8s with official document ([debian](https://docs.docker.com/engine/install/debian/)), ([ubuntu](https://docs.docker.com/engine/install/ubuntu/))

you say k8   but i only see docker in these links

**Comment by nonus25** [comment]
for anyone who would get same issue https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate

**Comment by lukamarkac-hibob** [comment]
> @xmudrii I got it!. In that time just wanted to write in my native language. I understand that the use of English makes the maintenance work easier (unification). For this reason:
> 
> try using the new Kubernetes repositories. You will find the well reasons why the repos references had changed. It may change in the future, I recommend that you bear this in mind.
> 
> Please try this:
> 
> Definitely the reason is the repository reference, try to removing (if it exists) the /etc/apt/sources.list.d/kubernetes.list file (with sudo permissions), the kubernetes repository reference (if it exist) in the /etc/apt/sources.list.d/sources.list file (with sudo permissions, with some text editor like vim), finally, (if it exists) any if there is any kubernetes reference file in the /etc/apt/trusted.gpg.d directory.
> 
> Add the correct repositories:
> 
> $ echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
> 
> $ curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
> 
> Install kubectl, kubeadmin and kublet:
> 
> $ sudo apt update
> 
> $ sudo apt install -y kubelet kubeadm kubectl
> 
> i hope this help you. Happy orquestation <3
> 
> References: https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/
> 
> 頑張って ^u^

That worked. THANK YOU!

**Comment by SumairaS** [comment]
> (Perdonen por no escribir en ingles mi comentario y sea mas universal, pero con google translate espero sea sencilla la interpretación)
> 
> Hola! ... Mismo error con Ubuntu 22.04 LTS.
> 
> Definitivamente es por la referencia al repo, podrías eliminar el archivo /etc/apt/sources.list.d/kubernetes.list (con permisos de sudo), las referencias a los repos de kubertenes (si los hay) en el archivo /etc/apt/sources.list.d/sources.list (permisos sudo), y de haber algún archivo referente a knertenes en /etc/apt/trusted.gpg.d.
> 
> Intentar con los repos y llaves en la referencia actual de kubernetes: https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/ . Ahí tendrás una buena referencia del porque se hizo el cambio, y podrás saber si en algún momento cambia para futuras instalaciones.
> 
> Pero en resumen con esto debería funcionar
> 
> `$ echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list`
> 
> `$ curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg`
> 
> `$ sudo apt update`
> 
> `$ sudo apt install -y kubelet kubeadm kubectl`
> 
> Espero funcione con tu caso, igual podrías intentarlo en una versión mas nueva de ubuntu o debian, igual en la referencia hay para mas distros.

This works! thanks @boxoky God bless you

**Comment by boxoky** [comment]
@SumairaS Me alegra oír eso, un placer  c:
