### ISSUE TITLE
☂️Slow Unit Test 🌂 1.30/1.31

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#123685]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-1-27 takes ~35min
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-unit taks ~40min

There are some adding UT. **New** below is comparing with v1.27. (The test or package may be old, but it takes more than 1m in UT in master, and not take more than 1m in v1.27.)

- [x] **New** k8s.io/apiserver/pkg/admission/plugin/policy: validating 1m24s https://github.com/kubernetes/kubernetes/pull/124036
- [ ] k8s.io/apiserver/pkg: server https://github.com/kubernetes/kubernetes/pull/124037
- [ ] k8s.io/apiserver/pkg/server: filters
- [ ] k8s.io/apiserver/pkg/server: options https://github.com/kubernetes/kubernetes/pull/124082 https://github.com/kubernetes/kubernetes/pull/124087
- [ ] **New**  k8s.io/apiserver/pkg/server/options: encryptionconfig
- [x] k8s.io/apiserver/pkg/storage: cacher **~3m**. still one of the slowest package
  - [x] Timeout is fixed:  we have a 3 minute timeout https://github.com/kubernetes/kubernetes/issues/123850.
- [ ] k8s.io/apiserver/pkg/storage: etcd3
- [ ] k8s.io/apiserver/pkg/util: flowcontrol 
- [ ] **New** k8s.io/apiserver/pkg/util: peerproxy
- [x] **New** k8s.io/kubectl/pkg/cmd: apply https://github.com/kubernetes/kubernetes/pull/124494
- [ ] k8s.io/kubernetes/pkg/controller: endpoint
- [ ] k8s.io/kubernetes/pkg/controller: endpointslice
- [ ] k8s.io/kubernetes/pkg/controller: nodeipam
- [ ] k8s.io/kubernetes/pkg/controller: statefulset
- [x] **New** k8s.io/kubernetes/pkg/kubelet/cm: dra **~3m** ⚠️ we have a 3 minute timeout https://github.com/kubernetes/kubernetes/pull/123720
- [ ] k8s.io/kubernetes/pkg/kubelet/volumemanager: reconciler
- [ ] k8s.io/kubernetes/pkg/registry/core/pod: storage
- [ ] k8s.io/kubernetes/pkg/registry/core/service: ipallocator
- [ ] k8s.io/kubernetes/pkg/registry/core/service: storage
- [ ] k8s.io/kubernetes/pkg/scheduler/framework/plugins: volumebinding
- [ ] k8s.io/kubernetes/pkg/volume: csi

/sig node api-machinery cli 
for new ones.

https://github.com/kubernetes/kubernetes/issues/98486 we did a similar check in 2021 before.

---

https://github.com/kubernetes/kubernetes/issues/123850#issuecomment-1988422238  We have a 3 minute timeout for a package.  
https://github.com/kubernetes/kubernetes/blob/ebc1a7b7fb52f30021b7e66f77070dac8e6b839b/hack/make-rules/test.sh#L60-L64

**Comment by HirazawaUi** [comment]
k8s.io/kubernetes/pkg/kubelet/cm/dra  https://github.com/kubernetes/kubernetes/pull/123720

time required before modification: 
```
go test ./... -cover -count=1
ok  	k8s.io/kubernetes/pkg/kubelet/cm/dra	94.097s	coverage: 83.8% of statements
```
time required after modification
```
go test ./... -cover -count=1
ok  	k8s.io/kubernetes/pkg/kubelet/cm/dra	1.356s	coverage: 83.8% of statements
```

**Comment by p0lyn0mial** [comment]
I will try to decrease the running time of the `apiserver/pkg/storage/cacher` pkg.

**Comment by SergeyKanzhelev** [comment]
/assign @bart0sh 

for k8s.io/kubernetes/pkg/kubelet/cm: dra

**Comment by HirazawaUi** [comment]
> /assign @bart0sh
> 
> for k8s.io/kubernetes/pkg/kubelet/cm: dra

Fixed in https://github.com/kubernetes/kubernetes/pull/123720

**Comment by brianpursley** [comment]
This one has been fixed by https://github.com/kubernetes/kubernetes/pull/124494
> [ ] **New** k8s.io/kubectl/pkg/cmd: apply

**Comment by pacoxu** [comment]
/close

since slowest UTs were improved.
