### ISSUE TITLE
[Failing Test] gce-master-scale-performance

### ISSUE THREAD

**Issue by SubhasmitaSw** [kubernetes/kubernetes#123672]
### Which jobs are failing?

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

### Which tests are failing?

ci-kubernetes-e2e-gce-scale-performance.Overall
kubetest.ClusterLoaderV2

### Since when has it been failing?

02-25-24 to 02-27-24

latest since 03-03-24

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

### Reason for failure (if possible)

```
I0303 17:17:36.980573   17996 prometheus.go:439] Waiting for Prometheus stack to become healthy...
W0303 17:17:37.019005   17996 util.go:72] error while calling prometheus api: the server is currently unable to handle the request (get services http:prometheus-k8s:9090), response: k8s�

v1Status]

���Failure3no endpoints available for service "prometheus-k8s""ServiceUnavailable0��"�

      "involvedObject": {
        "kind": "StatefulSet",
        "namespace": "monitoring",
        "name": "prometheus-k8s",
        "uid": "9d65236a-7d47-4c6d-882d-807df0b57eed",
        "apiVersion": "apps/v1",
        "resourceVersion": "520714"
      },
      "reason": "FailedCreate",
      "message": "create Pod prometheus-k8s-0 in StatefulSet prometheus-k8s failed error: pods \"prometheus-k8s-0\" is forbidden: error looking up service account monitoring/prometheus-k8s: serviceaccount \"prometheus-k8s\" not found",
      "source": {
        "component": "statefulset-controller"
      },
      "firstTimestamp": "2024-03-03T17:17:32Z",
      "lastTimestamp": "2024-03-03T17:17:32Z",
      "count": 5,
      "type": "Warning",
      "eventTime": null,
      "reportingComponent": "statefulset-controller",
      "reportingInstance": ""
    }
    
    ```

### Relevant SIG(s)

/sig scalability

**Comment by pacoxu** [comment]
last run passed. We will watch this to see if the failure are fixed.

**Comment by MaryamTavakkoli** [comment]
This one has failed again, please take a look https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

**Comment by aojea** [comment]
@wojtek-t it seems it times out waiting for the prometheus stack to be ready

> F0309 17:32:22.412466   17806 clusterloader.go:326] Error while setting up prometheus stack: timed out waiting for the condition

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1766509724091551744

**Comment by SubhasmitaSw** [comment]
🟢 Not a release blocker for v1.30 release cut. Confirmed by @wojtek-t

**Comment by wojtek-t** [comment]
> @wojtek-t it seems it times out waiting for the prometheus stack to be ready

This flaked before for the same reason before. We need to debug it, but it definitely seems like test issue.

**Comment by pacoxu** [comment]
Can we close this or observe another week?
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance passed 5 times in a row.

**Comment by Vyom-Yadav** [comment]
@aojea @wojtek-t Any updates on this? Still flakes. Can we add `triage/accepted` label or maybe assign this issue to someone?

**Comment by pacoxu** [comment]
> "message": "create Pod prometheus-k8s-0 in StatefulSet prometheus-k8s failed error: pods \"prometheus-k8s-0\" is forbidden: error looking up service account monitoring/prometheus-k8s: serviceaccount \"prometheus-k8s\" not found",

Not sure if we can add some redo logic for prometheus pod or a larger timeout  (currently it is large.)

Why the sa is missing? It is a problem.

**Comment by marseel** [comment]
I took a quick look and the reason for the failure is that not all targets in prometheus for scraping are ready, the other error is probably just a red herring with the old timestamp `2024-04-09T17:16:27Z`
```
I0409 17:18:01.929248   15853 util.go:101] 1221/1321 targets are ready, example not ready target: {map[container:coredns endpoint:metrics instance:10.73.255.3:9153 job:kube-dns namespace:kube-system pod:coredns-69df6df6c8-ks2mx service:kube-dns] down}
...
I0409 17:31:32.691361   15853 util.go:101] 1315/1321 targets are ready, example not ready target: {map[container:coredns endpoint:metrics instance:10.71.113.4:9153 job:kube-dns namespace:kube-system pod:coredns-69df6df6c8-x6bvd service:kube-dns] down}
...
F0409 17:31:32.724374   15853 clusterloader.go:326] Error while setting up prometheus stack: timed out waiting for the condition
```

**Comment by marseel** [comment]
Seems like kubelet was failing to pull coredns image for > 20 minutes:
```
./kubelet.log:428:E0409 17:11:57.828980    1880 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"coredns\" with ErrImagePull: \"failed to pull and unpack image \\\"registry.k8s.io/coredns/coredns:v1.11.1\\\": failed to resolve reference \\\"registry.k8s.io/coredns/coredns:v1.11.1\\\": unexpected status from HEAD request to https://registry.k8s.io/v2/coredns/coredns/manifests/v1.11.1: 429 Too Many Requests\"" pod="kube-system/coredns-69df6df6c8-x6bvd" podUID="3c125e4a-20b7-4038-a168-0b0b6eb056b7"
./kubelet.log:430:E0409 17:12:09.174659    1880 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"coredns\" with ImagePullBackOff: \"Back-off pulling image \\\"registry.k8s.io/coredns/coredns:v1.11.1\\\"\"" pod="kube-system/coredns-69df6df6c8-x6bvd" podUID="3c125e4a-20b7-4038-a168-0b0b6eb056b7"
...
happened many times in-between
...
./kubelet.log:730:E0409 17:31:22.174653    1880 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"coredns\" with ImagePullBackOff: \"Back-off pulling image \\\"registry.k8s.io/coredns/coredns:v1.11.1\\\"\"" pod="kube-system/coredns-69df6df6c8-x6bvd" podUID="3c125e4a-20b7-4038-a168-0b0b6eb056b7"
```

**Comment by pacoxu** [comment]
Is there any failure of pulling the image in containerd or kubelet?
- I cannot get the kubelet/containerd log from the CI.

**Comment by wojtek-t** [comment]
Discussed briefly on slack - it seems to be rate-limitting at the registry level.
It seems something might have changed that we're not more aggressively rate-limited

**Comment by serathius** [comment]
Update on flakes: We have 70% failure rate in last 10 tests due to the issue.

![image](https://github.com/kubernetes/kubernetes/assets/5873433/ddc28100-5c7b-4d6d-8f19-fc915c349b58)

**Comment by mborsz** [comment]
One interesting data point would be to check who is throttling us: is it registry.k8s.io redirect service or gcr.io it redirects to?

**Comment by aojea** [comment]
> One interesting data point would be to check who is throttling us: is it registry.k8s.io redirect service or gcr.io it redirects to?

let's ask sig-infra people. @ameukam @BenTheElder  can you help us here?

**Comment by ameukam** [comment]
> One interesting data point would be to check who is throttling us: is it registry.k8s.io redirect service or gcr.io it redirects to?

registry.k8s.io currently redirect to to AR. as Marek pointed, our rate limiting didn't affect previous versions and currently matching k8s.gcr.io default rate limit quota.

**Comment by BenTheElder** [comment]
Right, we have throttling as near to the GCR limits as we could setup, and it has been in place for a long time now, we have not made infrastructure changes anywhere near the timeline that this started failing.

My guesses:
- We changed the way traffic flows out of the scale clusters to be more heavily NAT-ed?
- Scale clusters started pulling more images from registry.k8s.io? (E.G. some change to kube-up.sh, or enabling kubelet parallel pulls or ...)

Mitigation suggestions:
- Use an in-cluster pull-through cache or ensure pulls are spread to different IPs and not a single NAT or similar.

**Comment by serathius** [comment]
Log with  containerd config from one of the nodes in scalability tests:
```
time="2024-04-05T17:11:03.545068034Z" level=info msg="Start cri plugin with config {PluginConfig:{ContainerdConfig:{Snapshotter:overlayfs DefaultRuntimeName:runc DefaultRuntime:{Type: Path: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:map[] PrivilegedWithoutHostDevices:false PrivilegedWithoutHostDevicesAllDevicesAllowed:false BaseRuntimeSpec: NetworkPluginConfDir: NetworkPluginMaxConfNum:0 Snapshotter: SandboxMode:} UntrustedWorkloadRuntime:{Type: Path: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:map[] PrivilegedWithoutHostDevices:false PrivilegedWithoutHostDevicesAllDevicesAllowed:false BaseRuntimeSpec: NetworkPluginConfDir: NetworkPluginMaxConfNum:0 Snapshotter: SandboxMode:} Runtimes:map[runc:{Type:io.containerd.runc.v2 Path: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:map[SystemdCgroup:true] PrivilegedWithoutHostDevices:false PrivilegedWithoutHostDevicesAllDevicesAllowed:false BaseRuntimeSpec: NetworkPluginConfDir: NetworkPluginMaxConfNum:0 Snapshotter: SandboxMode:podsandbox} test-handler:{Type:io.containerd.runc.v2 Path: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:map[] PrivilegedWithoutHostDevices:false PrivilegedWithoutHostDevicesAllDevicesAllowed:false BaseRuntimeSpec: NetworkPluginConfDir: NetworkPluginMaxConfNum:0 Snapshotter: SandboxMode:podsandbox}] NoPivot:false DisableSnapshotAnnotations:true DiscardUnpackedLayers:false IgnoreBlockIONotEnabledErrors:false IgnoreRdtNotEnabledErrors:false} CniConfig:{NetworkPluginBinDir:/home/kubernetes/bin NetworkPluginConfDir:/etc/cni/net.d NetworkPluginMaxConfNum:1 NetworkPluginSetupSerially:false NetworkPluginConfTemplate:/home/kubernetes/cni.template IPPreference:} Registry:{ConfigPath: Mirrors:map[docker.io:{Endpoints:[https://mirror.gcr.io https://registry-1.docker.io]} k8s.gcr.io:{Endpoints:[https://registry.k8s.io https://k8s.gcr.io]}] Configs:map[] Auths:map[] Headers:map[]} ImageDecryption:{KeyModel:node} DisableTCPService:true StreamServerAddress:127.0.0.1 StreamServerPort:0 StreamIdleTimeout:4h0m0s EnableSelinux:false SelinuxCategoryRange:1024 SandboxImage:registry.k8s.io/pause:3.9 StatsCollectPeriod:10 SystemdCgroup:false EnableTLSStreaming:false X509KeyPairStreaming:{TLSCertFile: TLSKeyFile:} MaxContainerLogLineSize:262144 DisableCgroup:false DisableApparmor:false RestrictOOMScoreAdj:false MaxConcurrentDownloads:3 DisableProcMount:false UnsetSeccompProfile: TolerateMissingHugetlbController:true DisableHugetlbController:true DeviceOwnershipFromSecurityContext:false IgnoreImageDefinedVolumes:false NetNSMountsUnderStateDir:false EnableUnprivilegedPorts:false EnableUnprivilegedICMP:false EnableCDI:false CDISpecDirs:[/etc/cdi /var/run/cdi] ImagePullProgressTimeout:5m0s DrainExecSyncIOTimeout:0s} ContainerdRootDir:/var/lib/containerd ContainerdEndpoint:/run/containerd/containerd.sock RootDir:/var/lib/containerd/io.containerd.grpc.v1.cri StateDir:/run/containerd/io.containerd.grpc.v1.cri}"
```

**Comment by serathius** [comment]
This config comes from 
https://github.com/kubernetes/kubernetes/blob/c016b0b9a8ca63dbec1fade0910c2a06017cc4ab/cluster/gce/gci/configure-helper.sh#L3277-L3282

**Comment by serathius** [comment]
/assign

Sent a fix https://github.com/kubernetes/kubernetes/pull/124366

**Comment by BenTheElder** [comment]
the "mirror" for k8s.gcr.io is actually just to encourage traffic to switch sooner, we should actually delete that one.

> We changed the way traffic flows out of the scale clusters to be more heavily NAT-ed?
>
>Scale clusters started pulling more images from registry.k8s.io? (E.G. some change to kube-up.sh, or enabling kubelet parallel pulls or ...)

do we know if either of these is true? something must have changed, so reverting may also be an option

**Comment by serathius** [comment]
Let me try configuring Cloud Nat in the GCP project.

**Comment by BenTheElder** [comment]
two green runs since but probably still need to keep an eye on this a big longer ...

**Comment by pacoxu** [comment]
Thanks.
3 success in a row.
