### ISSUE TITLE
DRA: beta: CEL validation

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#123687]
### What would you like to be added?

At the moment, `staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile.go` uses 1.0 as version for everything in its CEL environment to grant the alpha API CEL expressions access to things defined in the 1.30 release. We need to change that to the real version before promotion to beta.

### Why is this needed?

New expression must not use CEL expressions which become invalid on a downgrade, so only features already available in the previous release are valid.

**Comment by jpbetz** [comment]
Once https://github.com/kubernetes/kubernetes/issues/123687 and https://github.com/kubernetes/kubernetes/pull/123516 are merged to the same branch, a [RemovedVersion](https://github.com/kubernetes/kubernetes/blob/46f017a90b54b5abfc0a66a6ecf19e304aa7da95/staging/src/k8s.io/apiserver/pkg/cel/environment/environment.go#L177) can be added to the DRA specific implementation to prevent future versions from enabling both copies of the library.

**Comment by tico88612** [comment]
Hello @pohly @jpbetz 
I would like to send a gentle remind. The code freeze is starting 02:00 UTC Friday November 8th 2024 (about 3 weeks from now), and while there is still time, we want to ensure that each PR has a chance to be merged on time.
As the PR is tagged for 1.32, is it still planned for this release?
Thank you!
