### ISSUE TITLE
how to connect specific Pods of Api and asp.net core MVC in Kubernetes?

### ISSUE THREAD

**Issue by Ommkwn2001** [kubernetes/kubernetes#123616]
### What happened?

I have Two projects asp .net core Api and asp .net core MVC. In the asp .net core Api have a Two Replicas(instance) and asp .net core MVC have a three Replicas(instances).

So i want connect one pod of Api to one pod of MVC and than connect second pod of Api to second pod of MVC and than connect third pod of MVC to both pod of Api.

So i want when i Run the one pod of Api and MVC connected the Api data get and show in the MVC project.

So i want Pod's url for get data from Api.

### What did you expect to happen?

I want to use with specific pod connection of Api and MVC to Get data through Api and show in MVC.

### How can we reproduce it (as minimally and precisely as possible)?

I trying to pass pod url (Base Url) like this below image but this url is not working in MVC

I want to use with specific pod connection of Api and MVC to Get data through Api and show in MVC.

### Kubernetes version

![kub](https://github.com/kubernetes/kubernetes/assets/102901250/c3eb0ed0-72c0-46e2-8dd6-7c3b58193b86)

### Cloud provider

   `[HttpGet]
    public async Task<ActionResult> GetMySqlData()
    {
        string Baseurl = "http://webapiservice-0.webapiservice.default.pod.cluster.local:8081/";
        
        List<Customer> EmpInfo = new List<Customer>();

        using (var client = new HttpClient())
        {
            //Passing service base url  
            client.BaseAddress = new Uri(Baseurl);

            //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
            HttpResponseMessage Res = await client.GetAsync("home/MySqlData");

            //Checking the response is successful or not which is sent using HttpClient  
            if (Res.IsSuccessStatusCode)
            {
                //Storing the response details recieved from web api   
                var EmpResponse = Res.Content.ReadAsStringAsync().Result;

                //Deserializing the response recieved from web api and storing into the Employee list  
                EmpInfo = JsonConvert.DeserializeObject<List<Customer>>(EmpResponse);

            }
            //returning the employee list to view  
            return View(EmpInfo);

        }
    }`

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by Ommkwn2001** [comment]
I am try to access specific pod like this

string Baseurl = "http://webapiservice2-0.webapiservice2.default.pod.cluster.local:8081/";

![Screenshot1png](https://github.com/kubernetes/kubernetes/assets/102901250/35a71937-33fd-4760-9188-d3bf5b2ead54)
