### ISSUE TITLE
DRA: scheduler: refactor AssumeCache + event handler

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#123698]
### What would you like to be added?

The assume cache is now shared between volumbinding and dynamicresources plugin. It should be moved into the scheduler framework.

Events that make pods scheduleable currently are triggered by the informer cache, not the assume cache. For "claim was deallocated", this leads to a small, unlikely race if a pod gets scheduled and stopped so quickly that the informer cache doesn't ever see the "claim is allocated" state. The event handler should react to changes in the assume cache because that cache is guaranteed to receive the "claim is allocated" state which cause some pod to not get scheduled, because by definition the cache must have listed some other claim as using resources needed for that pod.

### Why is this needed?

Code ownership, race condition.

/sig node
/triage accepted
/priority important-longterm
/lifecycle frozen
/assign

**Comment by alculquicondor** [comment]
cc @Huang-Wei since you asked the same question I did

**Comment by pohly** [comment]
Implemented in https://github.com/pohly/kubernetes/tree/dra-scheduler-assume-cache-eventhandlers, will create PR once https://github.com/kubernetes/kubernetes/pull/124102 is merged.

**Comment by pohly** [comment]
Done in https://github.com/kubernetes/kubernetes/pull/124595
