### ISSUE TITLE
Document `email_verified` check when CEL expression is used in authentication configuration

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#123675]
When the `email` claim is used directly, we perform a custom check against the `email_verified` claim if it is present:

https://github.com/kubernetes/kubernetes/blob/9043ce05c125091c0cb5519206fd90d311abd8c8/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L779-L793

I do not think this type of check makes sense via the CEL based config, but we should document how to perform a similar validation since that check is lost if moving a config to use CEL expressions and the admin is unaware of the implicit `email_verified` check.

cc @aramase @liggitt

**Comment by liggitt** [comment]
> I do not think this type of check makes sense via the CEL based config, but we should document how to perform a similar validation since that check is lost if moving a config to use CEL expressions and the admin is unaware of the implicit `email_verified` check.

I think I agree. Should we go so far as to warn or forbid a cel username expression that contains `claims.email` and doesn't contain `claims.email_verified`?

Also, our doc looks misleading up here:
```
	//   Nested claims can be accessed using dot notation, e.g. 'claims.email.verified'.
```

I would never expect an `email` claim to be a nested structured claim... probably better to put a different field in the example.

**Comment by enj** [comment]
> Should we go so far as to warn or forbid a cel username expression that contains `claims.email` and doesn't contain `claims.email_verified`?

As in, if your `AuthenticationConfiguration.jwt[N].claimMappings.username.expression` contains the substring `claims.email`, we would require that at least one `AuthenticationConfiguration.jwt[N].userValidationRules[...].expression` contains the substring `claims.email_verified`?  I am not sure if warning is worth the effort (I do not think anyone would actually see it).  Forbidding it seems okay since the CEL validation check is not hard to write and we already require that exact behavior in the existing non-CEL code path?  I guess that question remains: does someone using CEL actually want to perform such a check?

> Also, our doc looks misleading up here

Yeah, will fix.

**Comment by liggitt** [comment]
> I am not sure if warning is worth the effort (I do not think anyone would actually see it). Forbidding it seems okay since the CEL validation check is not hard to write and we already require that exact behavior in the existing non-CEL code path? I guess that question remains: does someone using CEL actually want to perform such a check?

if we start with forbidding .email without doing *something* with .email_verified in some check, that seems safer / nicer / probably correct
