### ISSUE TITLE
When the node is in the NotReady state for 5 minutes, the DamonSet Pod on the node is still in the Running state.

### ISSUE THREAD

**Issue by luomengY** [kubernetes/kubernetes#123612]
### What happened?

When the kubelet on the node server2 stopped for 5 minutes, it was found that the Pod of DamonSet on the server2 node was still in the Running state. as follows:
![9bb35de7f03cfaf2a9a16225b7e3c4b](https://github.com/kubernetes/kubernetes/assets/110345347/7b8c6a8e-7ac0-4cfc-b8b9-ecce896408d3)

### What did you expect to happen?

When the node is in the NotReady state for 5 minutes, the Pod of the DamonSet on the node should be in the NodeLost state.

### How can we reproduce it (as minimally and precisely as possible)?

1. In a k8s cluster, stop the kubelet on one of the nodes.
2. After 5 minutes, observe the running status of the DamonSet Pod on this node.

### Kubernetes version

<details>

```console
$ kubectl version v1.28.2
# paste output here
```

</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O v1.28.2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico 
</details>

**Comment by AnishShah** [comment]
This might be WAI. Did you check the tolerations in the pod spec?

/triage needs-information
/priority backlog

**Comment by luomengY** [comment]
> This issue is currently awaiting triage.
> 
> If a SIG or subproject determines this is a relevant issue, they will accept it by applying the `triage/accepted` label and provide further guidance.
> 
> The `triage/accepted` label can be added by org members by writing `/triage accepted` in a comment.

All DeamonSets remain in Running status after the kubelet crash, and Pod has not added a tolerance.

**Comment by luomengY** [comment]
> This might be WAI. Did you check the tolerations in the pod spec?
> 
> /triage needs-information /priority backlog

All DeamonSets remain in Running status after the kubelet crash, and Pod has not added a tolerance.

**Comment by luomengY** [comment]
Does anyone understand this issue? Sometimes, the container of my DamonSet is already hanging on the node, but the pod still shows the Running status.

**Comment by haircommander** [comment]
> All DeamonSets remain in Running status after the kubelet crash, and Pod has not added a tolerance.

Maybe we could have been a bit clearer: default tolerations are added as well, can you check that there are no tolerations on the resulting pod. you can use `kubectl describe pod $podname` and it should show

**Comment by luomengY** [comment]
> Maybe we could have been a bit clearer: default tolerations are added as well, can you check that there are no tolerations on the resulting pod. you can use `kubectl describe pod $podname` and it should show

This is deamonset's pod tolerations：
![image](https://github.com/user-attachments/assets/61f261ef-1330-4c92-95a4-5f4c7ba757b9)

**Comment by luomengY** [comment]
@haircommander

**Comment by AnishShah** [comment]
sig-node triage meeting:

- This is working as intended since the Daemonset pod has toleration for `NodeNotReady` condition

/close

**Comment by luomengY** [comment]
> * This is working as intended since the Daemonset pod has toleration for `NodeNotReady` condition

DamonSet has been added with intolerance for not ready, but after the node is not ready, the pod's status remains Running.
![image](https://github.com/user-attachments/assets/0a68bb8d-cd2d-4184-adaf-49238061d3a3)
