### ISSUE TITLE
SetFeatureGateDuringTest doesn't work if test is run in pararell. 

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#123677]
### What happened?

`defer featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.ConsistentListFromCache, true)()` should change the feature flag to true, however feature flag is a global state, so if somewhere in the test we call `t.Parallel()` there is a risk that some other test changes the flag state in the mean time.

Found this when we launched broken ConsistentListFromCache to Alpha and only noticed issues in Beta as the test didn't really test anything. https://github.com/kubernetes/kubernetes/pull/123674/files#r1511492942.

### What did you expect to happen?

We should protect against usage of `featuregatetesting.SetFeatureGateDuringTest` and `t.Parallel` in a single test. 

### How can we reproduce it (as minimally and precisely as possible)?

```
func TestFeatureGateOn(t *testing.T) {
	defer featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.ConsistentListFromCache, true)()
	runFeatureGateTest(t, true)
}

func TestFeatureGateOff(t *testing.T) {
	defer featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.ConsistentListFromCache, false)()
	runFeatureGateTest(t, false)
}

func runFeatureGateTest(t *testing.T, expectEnabled bool) {
	t.Parallel()
	time.Sleep(time.Second)
	gotEnabled := utilfeature.DefaultFeatureGate.Enabled(features.ConsistentListFromCache)
	if gotEnabled != expectEnabled {
		t.Errorf("unexpected feature gate state, got: %v, want: %v", gotEnabled, expectEnabled)
	}
}
```

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by serathius** [comment]
Looks like issue doesn't appear when running on single CPU with `--cpu 1` flag.

**Comment by serathius** [comment]
In the watch cache tests we want to keep them running in parallel. The only way to prevent global state pollution is to move tests to separate files.

**Comment by neolit123** [comment]
> featuregatetesting.SetFeatureGateDuringTest

tagging as sig arch

/sig architecture

**Comment by serathius** [comment]
Tried one approach that didn't work. Wanted to prevent parallel calls to `SetFeatureGateDuringTest` by making the second caller wait until the first caller finishes. Unfortunately this doesn't work as it doesn't agree with how golang tests are parallelized. We don't have a guarantee (also cannot check that) that the caller is also parallelized and if it's not it will cause infinite block.

**Comment by serathius** [comment]
Looks like the best, but ugly way would be to separate tests setting the feature flag into different modules. Attempt: github.com/kubernetes/kubernetes/pull/123701

**Comment by p0lyn0mial** [comment]
> Looks like the best, but ugly way would be to separate tests setting the feature flag into different modules. Attempt:
https://github.com/kubernetes/kubernetes/pull/123701

yes, I did something similar in the past when i wanted to make sure no other test will modify the global state - https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/features/testing/features_init_test.go#L29

the alternative would be to get rid of the global state but that seems unfeasible as we would have to pass a feature gate implementation to every method that wants to use it.

**Comment by serathius** [comment]
Wrote a fix, PTAL
