### ISSUE TITLE
Document master <-> node communication

### ISSUE THREAD

**Issue by lucmult** [kubernetes/kubernetes#12375]
Document what ports and protocols are needed to have master <-> node communication fully working.

The scenario is:
- User wants to harden the node and master network configuration by having the minimal network ports exposed to public.
- Specially having master and node running with public/external IPs on cloud providers

I personally would expect this documentation on "Cluster Administration" section:
http://kubernetes.io/v1.0/docs/admin/index.html

**Comment by jimmycuadra** [comment]
I'm also looking for this information. There should be a single obvious document that lists ports and protocols (and which binaries use which). Right now it's very unclear which of the Kubernetes components require incoming network connections.

Here's what I was able to find by scrounging around in the docs:

* kube-apiserver: 6443/tcp, possibly 443/tcp if a reverse proxy is sitting in front of it (https://github.com/kubernetes/kubernetes/blob/v1.0.3/docs/admin/accessing-the-api.md)
* kube-scheduler: Offers a --port option, suggesting it acts as a server, but there are no details about what the default port is, what it's used for, or what other components must be able to reach it (https://github.com/kubernetes/kubernetes/blob/v1.0.3/docs/admin/kube-scheduler.md)
* kube-controller-manager: Same as kube-scheduler (https://github.com/kubernetes/kubernetes/blob/v1.0.3/docs/admin/kube-controller-manager.md)
* kubelet: Offers a --port option but appears not to require functioning as a server in the default case (https://github.com/kubernetes/kubernetes/blob/v1.0.3/docs/admin/kubelet.md)
* kube-proxy: Offers a few port related options, seems to pick a random range of ports to proxy by default (https://github.com/kubernetes/kubernetes/blob/v1.0.3/docs/admin/kube-proxy.md)

**Comment by vishh** [comment]
@dchen1107 @roberthbailey: Can we prioritize this issue? I see quite a few support questions related to this.

**Comment by davidopp** [comment]
ping?

**Comment by davidopp** [comment]
Sorry, I guess there isn't really anyone to ping. I'll try to find an owner.

**Comment by roberthbailey** [comment]
@davidopp if you haven't found an owner I can probably write something up in the next week or two.

**Comment by davidopp** [comment]
Sure, that would be great. Assigning to you.
