### ISSUE TITLE
Search domain generation verification

### ISSUE THREAD

**Issue by lunhuijie** [kubernetes/kubernetes#123747]
### What happened?

The text of the search domain generated by kubelet is inconsistent with the behavior verification of the search domain in the dnsConfig configured on the pod.

I configured the clusterDomain in kubelet to be capitalized XXXX, created a pod, and generated the search domain in the /etc/resolv.conf file to contain capitalized XXXX;
However, the same search domain configured directly in the podConfig on the pod will fail to verify.
as follows：
spec.dnsConfig.searches[0]: Invalid value: "XXXX": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

### What did you expect to happen?

I google it:
Although the RFC 1123 specification defines naming rules for domain names, in actual DNS configuration, search domains are not required to strictly follow these specifications. In Kubernetes, the search domain generated by kubelet is dynamically generated based on the configuration information of the cluster, and usually does not require users to manually set or pay attention to its restrictions in compliance with RFC 1123 specifications.
But:
I think kubelet should also follow principles when generating search domains, so that the configuration rules for search domains in k8s code are consistent;
Instead: 
source code generation can and does not follow the rules, but user configuration needs to follow the rules.

### How can we reproduce it (as minimally and precisely as possible)?

NONE

### Kubernetes version

<details>

```console
$ kubectl version
v1.22.3
# paste output here
```

</details>

### Cloud provider

<details>
NONE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig node

> The text of the search domain generated by kubelet is inconsistent with the behavior verification of the search domain in the dnsConfig configured on the pod.

**Comment by HirazawaUi** [comment]
There is some discussion in #71140 about why we restrict the use of lowercase dns.

We can modify the documentation to explain this problem (clusterDomain and dnsConfig have different validation rules). If we restrict clusterDomain to have the same validation rules as dnsConfig, then upgrad an already running cluster would be broke.

**Comment by lunhuijie** [comment]
> There is some discussion in #71140 about why we restrict the use of lowercase dns.
> 
> We can modify the documentation to explain this problem (clusterDomain and dnsConfig have different validation rules). If we restrict clusterDomain to have the same validation rules as dnsConfig, then upgrad an already running cluster would be broke.

ok, I see. thanks
