### ISSUE TITLE
 conn.go:254] Error on socket receive: read tcp 127.0.0.1:33421->127.0.0.1:54136: use of closed network connection

### ISSUE THREAD

**Issue by gaolc** [kubernetes/kubernetes#123787]
### What happened?

I used the jenkins k8s plugin to dynamically schedule the pod .This error occurred when the pod was connected to execute the command after successful scheduling

### What did you expect to happen?

Why is socket closed before to connecting? 

### How can we reproduce it (as minimally and precisely as possible)?

Jenkins ERROR: 
[2024-03-06T13:20:56.162Z]  java.net.SocketTimeoutException: connect timed out

K8s node  /var/log/message  ERROR:
Mar  6 21:18:56 k8s-node-11 kubelet: E0306 21:18:56.398023  214481 conn.go:254] Error on socket receive: read tcp 127.0.0.1:33421->127.0.0.1:54136: use of closed network connection：

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-1+db95af67a8a660", GitCommit:"db95af67a8a660dc53ac09b8475161de2f5c711e", GitTreeState:"clean", BuildDate:"2021-01-22T07:54:01Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-1+db95af67a8a660", GitCommit:"db95af67a8a660dc53ac09b8475161de2f5c711e", GitTreeState:"clean", BuildDate:"2021-01-22T07:24:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
# paste output here
$ uname -a
# paste output here
Linux cambricon-test-ai74 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadmin
</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker  Version: 20.10.12
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico v3.8.4
</details>

**Comment by pacoxu** [comment]
/sig node
it looks like https://github.com/kubernetes/kubernetes/issues/87615 which is fixed in https://github.com/kubernetes/kubernetes/issues/87615#issuecomment-743342319 v1.20 and cherry-picked to 1.19. 

https://github.com/kubernetes/kubernetes/releases/tag/v1.19.6 should include this fix : https://github.com/kubernetes/kubernetes/pull/96778.

BTW, 1.19 is end of life in kubernetes community. See https://kubernetes.io/releases/patch-releases/#non-active-branch-history. Please upgrade to community supported version.

/kind support

**Comment by dims** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
