### ISSUE TITLE
[Flaking Test] UT k8s.io/apiserver/pkg/storage cacher

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#123850]
### Which jobs are flaking?

ci-kubernetes-unit
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1766951890710433792 for Test_newReady
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1766693183548297216 for TestConditionalProgressRequester
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1766435231256023040 for Test_newReadyCancelPending

### Which tests are flaking?

k8s.io/apiserver/pkg/storage: cacher
{Failed;  === RUN   Test_newReady
{Failed;  === RUN   TestConditionalProgressRequester
Test_newReadyCancelPending

### Since when has it been flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1766951890710433792

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

```
{Failed;  === RUN   Test_newReady
W0310 22:58:09.559627   74191 logging.go:59] [core] [Channel #555 SubChannel #557] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:32823", ServerName: "localhost:32823", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:32823: connect: connection refused"
W0310 22:58:09.735598   74191 logging.go:59] [core] [Channel #543 SubChannel #545] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:42315", ServerName: "localhost:42315", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42315: connect: connection refused"
panic: test timed out after 3m0s
running tests:
	Test_newReady (0s)

goroutine 39481 [running]:
testing.(*M).startAlarm.func1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/testing/testing.go:2366 +0x265
created by time.goFunc
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/time/sleep.go:177 +0x45

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0005244e0, {0x2e50346, 0xd}, 0x2f70cb0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/testing/testing.go:1750 +0x851
testing.runTests.func1(0xc0005244e0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/testing/testing.go:2161 +0x86
testing.tRunner(0xc0005244e0, 0xc00068fb10)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/testing/testing.go:1689 +0x21f
testing.runTests(0xc0000134a0, {0x43a3620, 0x73, 0x73}, {0xc00068fbb8?, 0xc00068fc00?, 0x43b71a0?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/testing/testing.go:2159 +0x8bf
testing.(*M).Run(0xc0000df720)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/testing/testing.go:2027 +0xf18
main.main()
	_testmain.go:279 +0x2be
```

### Anything else we need to know?

similar flake before: https://github.com/kubernetes/kubernetes/issues/116225 

### Relevant SIG(s)

/sig api-machinery

**Comment by p0lyn0mial** [comment]
I looked at `Test_newReady` from [this](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1766951890710433792) run and it looks like all 10 go routines waited on `ready_test.go:33`/`ready.go:73` while the main test go routine was blocked on` ready_test.go:36`.
That means that the test didn’t call `ready.set(true)`/`ready_test.go:41` to unblocked the go routines. The main test thread waited on:
```
select {
 case <-time.After(1 * time.Second):
 case <-errCh:
  t.Errorf("ready should be blocking")
}
```
which suggests potential CPU contention.

**Comment by p0lyn0mial** [comment]
`Test_newReadyCancelPending` from [this](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1766435231256023040) run is similar to `Test_newReady`. All 10 go routines were blocked on `ready_test.go:181`/`ready.go:73`, while the main test go routine was blocked on `ready_test.go:184`. This indicates that the test did not invoke `cancel()`/`ready_test.go:189` to unblock the go routines. The main test thread was waiting on:
```
select {
 case <-time.After(1 * time.Second):
 case <-errCh:
  t.Errorf("ready should be blocking")
}
```

which again suggests potential CPU contention.

**Comment by p0lyn0mial** [comment]
/cc @serathius 

for `TestConditionalProgressRequester`

**Comment by aojea** [comment]
> ```
> select {
>  case <-time.After(1 * time.Second):
>  case <-errCh:
>   t.Errorf("ready should be blocking")
> }
> ```
> 
> which again suggests potential CPU contention.

That is super weird, that should unblock the test in 1 second,

**Comment by p0lyn0mial** [comment]
> That is super weird, that should unblock the test in 1 second,

yeah, which is why i think this could be potential CPU contention or a weird bug in golang.

**Comment by liggitt** [comment]
I'm not sure Test_newReady is the one blocking ... I think the package may be timing out while Test_newReady *happens* to be the currently running test.

Looking at successful runs, this package is *really* close to the 3 minute timeout:

> ✓  k8s.io/apiserver/pkg/storage/cacher (2m56.832s)

There's lots of goroutines in the dumped trace related to grpc, which Test_newReady doesn't even make use of:

```
goroutine 2278 [select, 2 minutes]:
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0xc0005233a0, {0x32da9e0, 0xc00037a7d0})
	/home/prow/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go:83 +0x1f1
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 2256
	/home/prow/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go:55 +0x245
```

looks like this flake was first seen on master on 3/7 - https://storage.googleapis.com/k8s-triage/index.html?text=test%20timed%20out%20after%203m0s&job=ci-kubernetes-unit%24&test=cacher

https://github.com/kubernetes/kubernetes/pull/123532 merged on 3/4... I suspect the added unit tests pushed us just slightly over the 3 minute timeout

**Comment by aojea** [comment]
ok, this easy to see in testgrid 
![image](https://github.com/kubernetes/kubernetes/assets/6450081/1d0bac8d-1869-4cc2-b1f9-50df11c69399)

cc @pohly as dra is around 3 mins now and may hit this problem if further development add more tests

**Comment by pacoxu** [comment]
> cc @pohly as dra is around 3 mins now and may hit this problem if further development add more tests

All slow(>1m) UT are listed in https://github.com/kubernetes/kubernetes/issues/123685.

**Comment by pohly** [comment]
Thanks @aojea for the heads up and @pacoxu for the PR link. Definitely something to keep an eye on.

**Comment by p0lyn0mial** [comment]
Oh, ok, I didn't realize that kube [has a custom timeout](https://github.com/kubernetes/kubernetes/blob/a0215badb8ddbdb21775a9a16fcce5af003c8b9d/hack/make-rules/test.sh#L63) of 3m for unit tests. It looks like the `apiserver/pkg/storage/cacher` after merging https://github.com/kubernetes/kubernetes/pull/123732 is still running close to the threshold. I will have a look and will try to decrease the running time of that package. Thanks.

**Comment by serathius** [comment]
Also reduced the running time of TestWatchStreamSeparation, however the change is not as impressive as @p0lyn0mial, I only saved 6 seconds :(

**Comment by p0lyn0mial** [comment]
I had a type in the PR, the decrease in running time is around `17%.` - 30s.
I will keep on improving the tests, but that PR gives us some headroom.

**Comment by p0lyn0mial** [comment]
We should save an additional 6 seconds of running time with https://github.com/kubernetes/kubernetes/pull/123891

**Comment by p0lyn0mial** [comment]
I have one more potential improvement - an additional 6 seconds of running time with https://github.com/kubernetes/kubernetes/pull/123897

**Comment by p0lyn0mial** [comment]
> Tests in k8s.io/apiserver/pkg/storage/cacher ordered by their duration:

> TestWatch 87.949s
>  ...


I think this is incorrect because `go go help testflag` says:
```
-run regexp
    Run only those tests, examples, and fuzz tests matching the regular
    expression.
 ```

and `go test -v -race -count 1 -run ^TestWatch$` says:
```
=== RUN   TestWatch
W0313 13:03:27.818896   63947 reflector.go:547] storage/cacher.go:/pods: failed to list *example.Pod: injected error
E0313 13:03:27.819078   63947 cacher.go:475] cacher (pods): unexpected ListAndWatch error: failed to list *example.Pod: injected error; reinitializing...
=== RUN   TestWatch/create_a_key
=== RUN   TestWatch/key_updated_to_match_predicate
=== RUN   TestWatch/update
=== RUN   TestWatch/delete_because_of_being_filtered
=== RUN   TestWatch/filtering
W0313 13:03:28.866632   63947 logging.go:59] [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59442", ServerName: "localhost:59442", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59442: connect: connection refused"
--- PASS: TestWatch (1.50s)
    --- PASS: TestWatch/create_a_key (0.91s)
    --- PASS: TestWatch/key_updated_to_match_predicate (0.01s)
    --- PASS: TestWatch/update (0.01s)
    --- PASS: TestWatch/delete_because_of_being_filtered (0.01s)
    --- PASS: TestWatch/filtering (0.01s)
PASS
W0313 13:03:29.874149   63947 logging.go:59] [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59442", ServerName: "localhost:59442", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59442: connect: connection refused"
ok  	k8s.io/apiserver/pkg/storage/cacher	3.260s
```

**Comment by serathius** [comment]
Ups, sorry didn't notice this.

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit still flakes a lot.
- TestGetListNonRecursiveWithConsistentListFromCache failed the most time

For instance: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1768002636163846144. 

- [ ] https://github.com/kubernetes/kubernetes/pull/123888 is the only PR in-review for this timeout
- [x] https://github.com/kubernetes/kubernetes/pull/123887
- [x] https://github.com/kubernetes/kubernetes/pull/123891
- [x] https://github.com/kubernetes/kubernetes/pull/123897

**Comment by Rajalakshmi-Girish** [comment]
> https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit still flakes a lot.
> 
>     * TestGetListNonRecursiveWithConsistentListFromCache failed the most time

We are also seeing this in our CI on `ppc64le`
https://testgrid.k8s.io/ibm-k8s-unit-tests-ppc64le#periodic-k8s-unit-tests-ppc64le

**Comment by p0lyn0mial** [comment]
https://github.com/kubernetes/kubernetes/pull/123926 should deflake `TestGetListNonRecursiveWithConsistentListFromCache` - @serathius PTAL.

**Comment by serathius** [comment]
Think we need to disable it, hope was that we could mitigate the issue on etcd side by allowing time for watch to be created, looks like it still flakes because of that. Will try to send a PR.

**Comment by pacoxu** [comment]
No flake in https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit after https://github.com/kubernetes/kubernetes/pull/123926 was merged. 

/close 

There seems to be some other works to track around this like https://github.com/kubernetes/kubernetes/pull/123927.

**Comment by Vyom-Yadav** [comment]
Still Flaking (Failed thrice in a row)
![image](https://github.com/kubernetes/kubernetes/assets/73882557/4301328a-0653-4db5-9ff4-ad31362d8b61)

/reopen

cc @pacoxu @serathius

**Comment by p0lyn0mial** [comment]
I'll try to rework some of the tests so that they can be moved to a new package.

**Comment by wojtek-t** [comment]
> TestWatch 87.949s

This seems wrong - this test is fairly fast on my laptop - O(3s). It seems that this is actually a sum of all `TestWatch*` tests.

**Comment by pacoxu** [comment]
fixed after https://github.com/kubernetes/kubernetes/pull/123994 was merged.
