### ISSUE TITLE
DRA: CDI: maximum annotation length

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#123889]
### What would you like to be added?

This code checks that "plugin name" (= DRA driver name) + "CDI device ID" with "_" as separator is at most `maxNameLen` = 63:

https://github.com/kubernetes/kubernetes/blob/3ec6a387955b1240ad6d795663513f1ee12ceaec/pkg/kubelet/cm/util/cdi/cdi.go#L104-L108

Can that happen for valid driver and CDI device IDs? Do CDI driver authors have to avoid this? If yes, we need to document it.

/cc @klueska @bart0sh 
/sig node

### Why is this needed?

Avoid surprises...

**Comment by ffromani** [comment]
/triage accepted
/priority important-longterm

not sure between important-soon or important-longterm, taking a conservative approach for starters

**Comment by varunrsekar** [comment]
@pohly Could `maxNameLen` atleast be 127/128 chars? If `deviceID` is a `uuid`, then it already takes up 36 chars.

Example that will break: `foobar.resource.example.com_dd84eb13-3eca-4caf-9042-4f556c8f6d48`

We use UUIDs when working with vGPUs and mediated devices. So having atleast 127 chars will help satisfy that.

**Comment by pohly** [comment]
I'm not sure where the `maxNameLen = 63` limit comes from. @bart0sh, can you clarify?

/assign @bart0sh

**Comment by varunrsekar** [comment]
Just found that k8s has some limits on the annotation key size: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set

```
Annotations are key/value pairs. Valid annotation keys have two segments: an optional prefix and name, separated by a slash (/). The name segment is required and must be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between. The prefix is optional. If specified, the prefix must be a DNS subdomain: a series of DNS labels separated by dots (.), not longer than 253 characters in total, followed by a slash (/).
```
But in the annotation key (`<prefix>`/`<name>`), only the name segment needs to be 63 characters or less where as the prefix can be upto 253 chars.

In our case, we have `<prefix>=cdi.k8s.io, <name>=pluginID+deviceID` which maybe it can just be `<prefix>=<pluginID>, <name>=deviceID`

**Comment by bart0sh** [comment]
I'm not sure either, but it's probably related to these 2 places:
- https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set
- https://github.com/cncf-tags/container-device-interface/blob/main/pkg/cdi/annotations.go#L91

@elezar @kad Any other ideas?

**Comment by pohly** [comment]
/priority important-soon

We are finalizing the DRA API and this has implications for it.

**Comment by elezar** [comment]
As @bart0sh points out, the 63 character limit is due to the use of the `name` section of the annotation key. Note that the `cdi.k8s.io` prefix is assumed by downstream consumers (containerd and cri-o) to determine whether CDI devices are requested if the dedicated CRI fields are not available.

Note that the `name` serves no practical purpose other than preventing colissions in keys. Furthermore, it is unrelated to the fully-qualified CDI device names which are passed as a comma-separated list in the corresponding annotation *value*.

The original thinking behind allowing a user to specify the plugin name is to allow some human-readability as to the source of the annotations, but maybe this flexibility is not required. We could also replace `getAnnotations(string, string) (string, error)` with an implementation that unconditionally returns a uuid instead.

@varunrsekar when you mention vGPUs and mediated devices, where are the UUIDs used? In the CDI device name, or in the annotation keys that are generated?

**Comment by elezar** [comment]
> We are finalizing the DRA API and this has implications for it.

@pohly which implications does this have? If we remove the logic for cleaning and prepending the driver name, we can construct the `name` section ourselves and leave it opague to the user. This may make some things more difficult to debug, but the annotation creation is opague to a DRA driver implementer in any case.

**Comment by pohly** [comment]
This may limit the length of strings exchanged between Kubernetes and DRA drivers (device ID) and/or of the driver name.

We currently have a limit on the driver name as part of the Kubernetes API (DNS subdomain, max 63 characters), but not for the device ID:
https://github.com/kubernetes/kubernetes/blob/529896474f2fad03156b78e097717dab1649a934/staging/src/k8s.io/kubelet/pkg/apis/dra/v1alpha3/api.proto#L70-L74

**Comment by elezar** [comment]
In the context of DRA the claim ID is used at present. My question was how we wish to expose this to driver authors? We could make this an implementation detail on the kubelet side and always generate a uuid.

**Comment by bart0sh** [comment]
Passing CDI devices as annotations should be deprecated soon and removed from the Kubelet. To my understanding it should happen after EOL of the Kubernetes 1.28.

Kubernetes 1.29 supports passing CDIDevices with CRI field and has Device plugin CDI support enabled by default.

**Comment by pohly** [comment]
Do we have a tracking issue for this? If not, can you create one?

**Comment by varunrsekar** [comment]
> @varunrsekar: I suppose the claim UID is what you saw in your failure case, not the UID you use in your driver. Is that correct?

@pohly Sorry for the confusion! What I saw in the CDI annotations was indeed the claim UID.

**Comment by bart0sh** [comment]
Created an issue as requested: https://github.com/kubernetes/kubernetes/issues/125210

**Comment by bart0sh** [comment]
This issue can be closed as DRA stopped setting CDI annotations in Kubernetes 1.31.
@pohly Can you close it?
