### ISSUE TITLE
StructuredAuthenticationConfiguration does not support ES256 algorithm

### ISSUE THREAD

**Issue by HamzaZo** [kubernetes/kubernetes#123840]
### What happened?

I'm using [Pinniped](https://pinniped.dev/docs/background/architecture/) as an OIDC provider to authenticate users. following the Pinniped documentation we need to add the following flags to the api-server to trust supervisor as OICD provider
```
# Make this exactly match the spec.issuer of your Supervisor's FederationDomain.
# Note: It seems like the kube-apiserver pod cannot resolve `cluster.local`
# DNS names, so don't use one of those DNS names as the issuer.
--oidc-issuer-url="https://my-supervisor.example.com/my-issuer"

# This is only required if the kube-apiserver pod is not going to trust your
# Supervisor's FederationDomain's TLS certificates, e.g. if you used a
# self-signed CA. Make this match where you mounted the CA PEM file into
# your control plane node's filesystem, which must be under a directory
# that the kube-apiserver container is going to volume mount.
--oidc-ca-file="/etc/ca-certificates/supervisor/root-ca.pem"

# Choose a unique value for each cluster here. By making this unique, the
# Supervisor will be able to issue ID tokens for this cluster that cannot
# be used on any other cluster, which improves security. Do not use the
# special value "pinniped-cli" or any value that contains the substring
# ".pinniped.dev", because these special values are reserved for other
# purposes.
--oidc-client-id="my-cluster-342klb7h"

# Use these exact values. These are based on how the Supervisor issues ID
# tokens. Do not change these values.
--oidc-signing-algs="ES256"
--oidc-username-claim="username"
--oidc-groups-claim="groups"
```
which works fine. However when I tried to implement the same thing using the new featureGates `StructuredAuthenticationConfiguration ` in the apiserver as follow
```
- --feature-gates=StructuredAuthenticationConfiguration=true
- --authentication-config=/etc/kubernetes/auth-config.yaml
```

The output of `auth-config.yaml`
```
apiVersion: apiserver.config.k8s.io/v1alpha1
kind: AuthenticationConfiguration
jwt:
  - issuer:
      url: https://my-supervisor.example.com/my-issuer
      audiences:
        - my-cluster-342klb7h
       certificateAuthority: |
         xxxxxxxx
    claimMappings:
      username:
        expression: 'claims.email'
      groups:
        expression: 'claims.groups'
```

I'm getting ```Unable to authenticate the request err=[invalid bearer token, oidc; verify token: oidc: id token signed with unsupported algortithm, expected [\"RSA256\"] got \"ES256\"]"```

According to the quote from the KEP, all asymmetric algorithms are allowed, which is not the case
```
Goals:
Easy migration from existing OIDC flags
Note: we intend to drop the --oidc-signing-algs flag because this configuration provides no benefit (we will always allow all asymmetric algorithms)
```
https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3331-structured-authentication-configuration#goals

cc @cfryanr  to follow 

Any help, please? 

### What did you expect to happen?

ES256 is an asymmetric algorithm so it should be allowed

### How can we reproduce it (as minimally and precisely as possible)?

Allow all asymmetric algorithm 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
1.29.1

### Cloud provider

<details>

</details>
On premise

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
Ubuntu 22

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>
Containerd

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
@HamzaZo looks like then intention is there `"oidc-signing-algs"` but the flag has NOT been deprecated yet. wanna try to specify that too?

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubeapiserver/options/authentication.go#L351-L354

**Comment by HamzaZo** [comment]
@dims You mean that I need to add `- --oidc-signing-algs="ES256"` in the apiserver ?
```
- --feature-gates=StructuredAuthenticationConfiguration=true
- --authentication-config=/etc/kubernetes/auth-config.yaml
- --oidc-signing-algs="ES256"
```

**Comment by dims** [comment]
yes, please try that to see what happens.

**Comment by nevivurn** [comment]
We were running into the same problem, and we tried the `--oidc-signing-algs="ES256"` workaround.
Unfortunately the apiserver complains that `oidc-*` flags (including `oidc-signing-algs`)  are mutually exclusive with `authentication-config`.

Relevant code is here, I think. https://github.com/kubernetes/kubernetes/blob/v1.29.2/pkg/kubeapiserver/options/authentication.go#L680

**Comment by aramase** [comment]
There is a bug present in version v1.29, which has been resolved through the patch provided in https://github.com/kubernetes/kubernetes/pull/123282. This fix will be included in the upcoming v1.30 release.

FYI `StructuredAuthenticationConfiguration` will be beta in `v1.30` and enabled by default.

**Comment by HamzaZo** [comment]
@aramase my use case is to define two `oidc-client-id` using `StructuredAuthenticationConfiguration` (currently, using multiple --oidc-client-id flags is not supported in the api-server) Is there any workaround to implement without waiting for v1.30 ?

**Comment by aramase** [comment]
Multiple audience support in Authentication Configuration was only added in v1.30: https://github.com/kubernetes/kubernetes/pull/123165. There is no way to define more than one audience in authentication configuration in v1.29 or using the `oidc-*` flags. 

The recommendation would be to use the feature in `v1.30` that supports configuring multiple audiences, multiple JWT authenticators and contains the signing algs [fix](https://github.com/kubernetes/kubernetes/pull/123282).

Closing the issue with the above comment. Please try out the feature in `v1.30` and let us know your feedback.

/triage accepted
/close
