### ISSUE TITLE
Failure cluster [331a0ece...] [sig-api-machinery] ValidatingAdmissionPolicy [Privileged:ClusterAdmin] should type check a CRD [Conformance]

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#123829]
<img width="1015" alt="image" src="https://github.com/kubernetes/kubernetes/assets/23304/1be6048d-3ae1-4b39-94f8-38494461bbcd">

##### Error text:
```
[FAILED] Expected
    <[]v1.ExpressionWarning | len:0, cap:0>: nil
to have length 2
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/validatingadmissionpolicy.go:365 @ 03/08/24 10:00:06.477

```
#### Recent failures:
[3/8/2024, 4:40:41 PM ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-29-on-latest](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-29-on-latest/1766217293441798144)
[3/8/2024, 4:12:52 PM ci-kubernetes-e2e-kubeadm-kinder-rootless-latest](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-rootless-latest/1766210246927192064)
[3/8/2024, 4:12:48 PM ci-kubernetes-e2e-kubeadm-kinder-learner-mode-latest](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-learner-mode-latest/1766210246868471808)
[3/8/2024, 4:01:43 PM ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-27-on-latest](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-27-on-latest/1766207478464253952)
[3/8/2024, 3:45:39 PM ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-29-latest](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-29-latest/1766203452079214592)

/kind failing-test

/sig api-machinery

**Comment by dims** [comment]
/priority critical-urgent

xref : https://github.com/kubernetes/kubernetes/pull/123774

/assign @cici37 @jpbetz @liggitt

**Comment by liggitt** [comment]
hrmm, looks super solid in https://testgrid.k8s.io/sig-testing-kind#kind-master-parallel&width=20&include-filter-by-regex=ValidatingAdmissionPolicy

**Comment by dims** [comment]
yea something screwy going on with the kubeadm jobs :(

**Comment by dims** [comment]
my main concern what that this was a `Conformance` test ..

**Comment by neolit123** [comment]
kinder or kind jobs have been mostly solid across the board for a few years. if something is failing in kind / kinder then likely it would also fail in resource constraint scenarios. sorry but my 2c are that this is worth investigating by owning sigs

**Comment by neolit123** [comment]
i don't know what could be the cause here. kubeadm is crd agnostic.

**Comment by liggitt** [comment]
> if something is failing in kind / kinder then likely it would also fail in resource constraint scenarios. sorry but my 2c are that this is worth investigating by owning sigs

completely agree this needs resolution, I'm just confused since https://testgrid.k8s.io/sig-testing-kind#kind-master-parallel&width=20&include-filter-by-regex=ValidatingAdmissionPolicy is a really similar setup and looks completely solid

The test waits until the status is set, so even a resource-constrained env should just wait a little longer ... 

> i don't know what else could be the cause here. kubeadm is crd agnostic.

I'm also pretty confused

**Comment by neolit123** [comment]
the diff between the two jobs reveals that the kind job has much higher resource limits/requests

https://prow.k8s.io/prowjob?prowjob=01d30d7a-d551-4d7d-8e97-0f22c9a8f368
https://prow.k8s.io/prowjob?prowjob=9fa64315-f831-4764-b1b2-a3a6a324d846

```diff
         limits:
-          cpu: "7"
-          memory: 9Gi
+          cpu: "2"
+          memory: 9000Mi
         requests:
-          cpu: "7"
-          memory: 9Gi
+          cpu: "2"
+          memory: 9000Mi
```

full diff:

<details>

```diff
--- prowjob?prowjob=01d30d7a-d551-4d7d-8e97-0f22c9a8f368        2024-03-10 09:27:41.444783563 +0200
+++ prowjob?prowjob=9fa64315-f831-4764-b1b2-a3a6a324d846        2024-03-10 09:27:22.014720698 +0200
@@ -1,33 +1,34 @@
 metadata:
   annotations:
-    description: Uses kubetest to run e2e tests against a latest kubernetes master
-      cluster created with sigs.k8s.io/kind
-    fork-per-release: "true"
-    fork-per-release-periodic-interval: 1h 2h 6h 24h
+    description: 'OWNER: sig-cluster-lifecycle (kinder); Uses kubeadm/kinder to create
+      a cluster with rootless control-plane and run kubeadm-e2e and the conformance
+      suite'
     prow.k8s.io/context: ""
-    prow.k8s.io/job: ci-kubernetes-kind-e2e-parallel
-    testgrid-alert-email: bentheelder@google.com,antonio.ojea.garcia@gmail.com,release-team@kubernetes.io
-    testgrid-dashboards: sig-release-master-blocking, sig-testing-kind
-    testgrid-num-columns-recent: "6"
-    testgrid-tab-name: kind-master-parallel
-  creationTimestamp: "2024-03-10T06:02:53Z"
-  generation: 7
+    prow.k8s.io/job: ci-kubernetes-e2e-kubeadm-kinder-rootless-latest
+    testgrid-alert-email: sig-cluster-lifecycle-kubeadm-alerts@kubernetes.io
+    testgrid-alert-stale-results-hours: "16"
+    testgrid-dashboards: sig-cluster-lifecycle-kubeadm
+    testgrid-num-columns-recent: "20"
+    testgrid-num-failures-to-alert: "8"
+    testgrid-tab-name: kubeadm-kinder-rootless-latest
+  creationTimestamp: "2024-03-08T21:11:52Z"
+  generation: 8
   labels:
     created-by-prow: "true"
     preset-dind-enabled: "true"
     preset-kind-volume-mounts: "true"
-    prow.k8s.io/build-id: "1766706269772582912"
+    prow.k8s.io/build-id: "1766210246927192064"
     prow.k8s.io/context: ""
-    prow.k8s.io/id: 01d30d7a-d551-4d7d-8e97-0f22c9a8f368
-    prow.k8s.io/job: ci-kubernetes-kind-e2e-parallel
+    prow.k8s.io/id: 9fa64315-f831-4764-b1b2-a3a6a324d846
+    prow.k8s.io/job: ci-kubernetes-e2e-kubeadm-kinder-rootless-latest
     prow.k8s.io/refs.base_ref: master
     prow.k8s.io/refs.org: kubernetes
     prow.k8s.io/refs.repo: kubernetes
     prow.k8s.io/type: periodic
-  name: 01d30d7a-d551-4d7d-8e97-0f22c9a8f368
+  name: 9fa64315-f831-4764-b1b2-a3a6a324d846
   namespace: default
-  resourceVersion: "1720711518"
-  uid: a5e4d148-8ca9-437c-b815-9145fd66838f
+  resourceVersion: "1719272944"
+  uid: daaedc6a-b8bf-4fe1-bedd-b96f32fa9e10
 spec:
   agent: kubernetes
   cluster: k8s-infra-prow-build
@@ -65,23 +66,21 @@
     org: kubernetes
     path_alias: k8s.io/kubernetes
     repo: kubernetes
-  job: ci-kubernetes-kind-e2e-parallel
+  - base_ref: main
+    blobless_fetch: true
+    org: kubernetes
+    path_alias: k8s.io/kubeadm
+    repo: kubeadm
+  job: ci-kubernetes-e2e-kubeadm-kinder-rootless-latest
   namespace: test-pods
   pod_spec:
     containers:
-    - command:
-      - wrapper.sh
-      - bash
-      - -c
-      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz -
-        -C "${PATH%%:*}/" && e2e-k8s.sh
+    - args:
+      - rootless-latest
+      command:
+      - runner.sh
+      - ../kubeadm/kinder/ci/kinder-run.sh
       env:
-      - name: FOCUS
-        value: .
-      - name: SKIP
-        value: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|In-tree.Volumes.\[Driver:.nfs\]|PersistentVolumes.NFS|Network.should.set.TCP.CLOSE_WAIT.timeout|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|should.provide.basic.identity
-      - name: PARALLEL
-        value: "true"
       - name: DOCKER_IN_DOCKER_ENABLED
         value: "true"
       - name: GOPROXY
@@ -90,15 +89,15 @@
         valueFrom:
           fieldRef:
             fieldPath: metadata.name
-      image: gcr.io/k8s-staging-test-infra/krte:v20240222-d3b49dd525-master
+      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240223-1ded72f317-master
       name: ""
       resources:
         limits:
-          cpu: "7"
-          memory: 9Gi
+          cpu: "2"
+          memory: 9000Mi
         requests:
-          cpu: "7"
-          memory: 9Gi
+          cpu: "2"
+          memory: 9000Mi
       securityContext:
         privileged: true
       volumeMounts:
@@ -129,14 +128,15 @@
   report: true
   type: periodic
 status:
-  build_id: "1766706269772582912"
-  completionTime: "2024-03-10T06:30:00Z"
-  description: Job succeeded.
-  pendingTime: "2024-03-10T06:02:53Z"
-  pod_name: 01d30d7a-d551-4d7d-8e97-0f22c9a8f368
+  build_id: "1766210246927192064"
+  completionTime: "2024-03-08T21:57:38Z"
+  description: Job failed.
+  pendingTime: "2024-03-08T21:11:52Z"
+  pod_name: 9fa64315-f831-4764-b1b2-a3a6a324d846
   prev_report_states:
-    gcsk8sreporter: success
-    gcsreporter: success
-  startTime: "2024-03-10T06:02:53Z"
-  state: success
-  url: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1766706269772582912
+    gcsk8sreporter: failure
+    gcsreporter: failure
+    slackreporter: failure
+  startTime: "2024-03-08T21:11:52Z"
+  state: failure
+  url: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-rootless-latest/1766210246927192064
```

</details>

**Comment by neolit123** [comment]
> The test waits until the status is set, so even a resource-constrained env should just wait a little longer ... the failures I see are bailing out of that loop after only one wait (105ms), so something is turning that field non-nil without populating the expected results

i'm not familiar with this area of the code. it does appear to be waiting for the TypeChecking struct to be populated, but not for the Warnings slice to be populated.

logically (without trying to find the code):
- if TypeChecking is expected to be populated with Warnings _during_ a Get call _after_ the Create call, we are catching a bug.
- if the Warnings in the TypeChecking are populated async of the TypeChecking then we are catching a flake and the test must be updated to wait for the Warnings too.

https://github.com/kubernetes/kubernetes/blob/8f80e0146726c42edefdfaeda6123872a5ec0981/test/e2e/apimachinery/validatingadmissionpolicy.go#L184-L198
```go
		ginkgo.By("waiting for the type check to finish with warnings", func() {
			err := wait.PollUntilContextCancel(ctx, 100*time.Millisecond, true, func(ctx context.Context) (done bool, err error) {
				policy, err = client.AdmissionregistrationV1().ValidatingAdmissionPolicies().Get(ctx, policy.Name, metav1.GetOptions{})
				if err != nil {
					return false, err
				}
				if policy.Status.TypeChecking != nil { // non-nil TypeChecking indicates its completion
					return true, nil
				}
				return false, nil
			})
			framework.ExpectNoError(err, "wait for type checking")

			// assert it to contain 2 warnings, first for expression and second for messageExpression
			gomega.Expect(policy.Status.TypeChecking.ExpressionWarnings).To(gomega.HaveLen(2))
```

it polls the get on the priviously created

**Comment by neolit123** [comment]
> logically (without trying to find the code):

well, the code is here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/validatingadmissionpolicystatus/controller.go#L148
it appears that the only way for this to happen is if the Check() call returns nil warnings under "some conditions".
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/policy/validating/typechecking.go#L108

the problem is not reproducible in the unit test here if the interval is set to a lower value <= 100ms and tested with the `stress` tool.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/validatingadmissionpolicystatus/controller_test.go#L118
but that's with a fake client.

this extra err check seems redundant:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/validatingadmissionpolicystatus/controller_test.go#L137-L139

it might be worth temporary adding a print of the crd and policy before this line:
https://github.com/kubernetes/kubernetes/blob/8f80e0146726c42edefdfaeda6123872a5ec0981/test/e2e/apimachinery/validatingadmissionpolicy.go#L364

**Comment by cici37** [comment]
Thanks for raising the issue and thanks for the investigation! 
I don't know exactly why the solid test in kind would be flaky in kubeadm by a quick scan but agree it needs attention.(The tests look less flaky though..)
/assign @jiahuif  the type checking code owner. Would you mind adding a printout as suggested above and see if we could get more info? Thanks!

**Comment by neolit123** [comment]
> I don't know exactly why the solid test in kind would be flaky in kubeadm 

note, both kind and kinder (from the compared jobs) use kubeadm.

**Comment by neolit123** [comment]
> but that's with a fake client.

and

> it might be worth temporary adding a print of the crd and policy

i wonder if this is an informer cache issue.

**Comment by pacoxu** [comment]
https://storage.googleapis.com/k8s-triage/index.html?test=should%20type%20check%20a%20CRD
shows that the test failed for a different reason.
```
[FAILED] wait for type checking: Get "https://34.229.149.1:6443/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies/validating-admission-policy-1003.correct-crd-policy.example.com": http2: client connection lost
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/validatingadmissionpolicy.go:314 @ 03/04/24 07:13:51.264

There were additional failures detected after the initial failure. These are visible in the timeline
```
failure in ci-kubernetes-e2e-ec2-alpha-enabled-default: from 03/04 to 03/06.

**Comment by liggitt** [comment]
> /assign @jiahuif the type checking code owner

@jiahuif, the API field doc indicates a non-nil value means type checking is complete:

```
	// The results of type checking for each expression.
	// Presence of this field indicates the completion of the type checking.
	// +optional
	TypeChecking *TypeChecking `json:"typeChecking,omitempty" protobuf:"bytes,2,opt,name=typeChecking"`
```

It doesn't look like the type checker has any way to signal that it was lacking some information needed to complete type checking, and will record an empty set of warnings if it is:

https://github.com/kubernetes/kubernetes/blob/b3926d137cd2964cd3a04088ded30845910547b1/pkg/controller/validatingadmissionpolicystatus/controller.go#L148-L160

are there any scenarios where a laggy REST mapper or informer can make the controller think it completed type checking but be missing some info that makes it produce an empty list of warnings?

I think our options are:
1. change the test to wait for non-empty warnings in the status (not just non-nil typeChecking)
2. change the controller to not write an empty typeChecking stanza if it fails to type check in some way

option 2 seems better for observers, but I don't know how invasive that is

**Comment by dims** [comment]
@liggitt 2 feels like we are creating a hole? (folks will see warnings sometimes and sometimes they don't?)

**Comment by cici37** [comment]
Option 2 might cause confusion especially when deleting existing warnings from typechecking field.(We will remove the typechecking warning if observed the fix in schema)

**Comment by liggitt** [comment]
> Option 2 might cause confusion especially when deleting existing warnings from typechecking field.(We will remove the typechecking warning if observed the fix in schema)

I'm not suggesting deleting existing warnings, but it appears we are currently reporting an empty typeChecking stanza when we have not actually finished type checking... that doesn't match the API docs

**Comment by jiahuif** [comment]
Ignoring errors while finishing the type checking is intended behavior defined by the original KEP. Can we go back to change the tests to do a retry loop until the CRD appears in the RESTMapper? The root problem of laggy RESTMapper seems out of the scope of this test case.

**Comment by neolit123** [comment]
if https://github.com/kubernetes/kubernetes/pull/123870 is fixing the test then it's masking a state not guaranteed by the field comment:
> // Presence of this field indicates the completion of the type checking.

**Comment by jiahuif** [comment]
> if #123870 is fixing the test then it's masking a state not guaranteed by the field comment:
> 
> > // Presence of this field indicates the completion of the type checking.
> 
> i guess @liggitt already explained that above.

The type checking is completed with this field set to non-nil. The problem is that the type checking finishes with error, and it cause some of the referred types to be ignored.

**Comment by neolit123** [comment]
> 
> The type checking is completed with this field set to non-nil. The problem is that the type checking finishes with error, and it cause some of the referred types to be ignored.

should this error be surfaced to the user and does that need an e2e test?

**Comment by jiahuif** [comment]
> > The type checking is completed with this field set to non-nil. The problem is that the type checking finishes with error, and it cause some of the referred types to be ignored.
> 
> should this error be surfaced to the user and does that need an e2e test?

No. The KEP defines that errors will be ignored. However, there is a next step https://github.com/kubernetes/kubernetes/pull/123350 to make the type checker reacts on CRD changes, which handles the case when the CRD schema is late for the type checking.

**Comment by neolit123** [comment]
i think users might be confused by this behavior (the same way people on this thread are) even if it's documented in a KEP, so a field comment update feels worth it, at minimum.

**Comment by cici37** [comment]
The current type checking is informational and only works on ValidatingAdmissionPolicy. If the CRD is created after type checking or CRD created but not showing in schema watcher yet, the error would be ignored. And it will not retry as long as ValidatingAdmissionPolicy remains unchanged. We have a PR for adding retry with schema resolver raised in https://github.com/kubernetes/kubernetes/pull/123350 which will solve the issue entirely. In current case, the guess would be schema watcher is slow so it didn't have crd info yet when performing typechecking.

The temporary fix in https://github.com/kubernetes/kubernetes/pull/123873 will resolve the test flaky by adding manually retry.

The field comment of `// Presence of this field indicates the completion of the type checking.` makes sense to me since it indicates the completion of the type checking but not handling the case where the CRD has not been created or created but not showing in schema watcher yet. FYI The [documentation](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#type-checking) says `Type Checking does not apply to CRDs, including matched CRD types and reference of paramKind. The support for CRDs will come in future release.`

I agree it might not fit in conformance test. Not sure about the conformance test criteria.

**Comment by fedebongio** [comment]
cc
