### ISSUE TITLE
Default ipFamilyPolicy value

### ISSUE THREAD

**Issue by maxpain** [kubernetes/kubernetes#123810]
### What would you like to be added?

Make the default Service `ipFamilyPolicy` value configurable in `apiserver` or set it as `PreferDualStack` by default.

### Why is this needed?

Almost all public Helm charts don't provide a value to configure Service `ipFamilyPolicy`, so I would like to set it to `PreferDualStack` by default, especially for `kubernetes` default service.

**Comment by aojea** [comment]
> Almost all public Helm charts don't provide a value to configure Service `ipFamilyPolicy`, so I would like to set it to `PreferDualStack` by default, 

I don't think Kubernetes should compensate for that problem, have you tried to open issues to the corresponding charts to set that value? or maybe a webhook?

> especially for `kubernetes` default service.

The kubernetes default service is more involved than that , long history here https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2438-dual-stack-apiserver

**Comment by uablrek** [comment]
Um, when does it matter? Really?

**Comment by thockin** [comment]
Ignoring the kubernetes.default service, which is a different can of worms, Something like a webhook (or upcoming MutatingAdmissionPolicy) is the right-now fix for this. 

I don't know that we want to add a cluster-configuration option for this beyond that, and certainly not as a flag to apiserver.
