### ISSUE TITLE
[Flaking] [kind-e2e-parallel] [sig-apps] ReplicaSet should surface a failure condition on a common issue like exceeded quota

### ISSUE THREAD

**Issue by Namanl2001** [kubernetes/kubernetes#123806]
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1764798590191931392

### Which tests are flaking?

Kubernetes e2e suite.[It] [sig-apps] ReplicaSet should surface a failure condition on a common issue like exceeded quota

### Since when has it been flaking?

[https://storage.googleapis.com/k8s-triage/index.html?test=should%20surface%20a%20failure[…]ition%20on%20a%20common%20issue%20like%20exceeded%20quota](https://storage.googleapis.com/k8s-triage/index.html?test=should%20surface%20a%20failure%20condition%20on%20a%20common%20issue%20like%20exceeded%20quota) shows it flakes several times. The flake rate is not high though

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel

### Reason for failure (if possible)

```
   I0305 00:05:23.622506 67387 replica_set.go:286] Unexpected error: 
      <*errors.errorString | 0xc000bc93c0>: 
      rs controller never added the failure condition for replica set "condition-test": []v1.ReplicaSetCondition(nil)
      {
          s: "rs controller never added the failure condition for replica set \"condition-test\": []v1.ReplicaSetCondition(nil)",
      } 
```

### Relevant SIG(s)

/sig apps

**Comment by carlory** [comment]
The quota hard is 2, but created pod is 3. 
There's conflict in kube-apiserver. 

```
Operation cannot be fulfilled on resourcequotas \"condition-test\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"condition-test","kind":"resourcequotas"},"code":409}
```

**Comment by pacoxu** [comment]
> The quota hard is 2, but created pod number is 3.
> There's conflict in kube-apiserver.

Is this a bug?

**Comment by flavianmissi** [comment]
Hi folks,
I'm interested in working on this. Can anyone assign me? 
Thanks.

**Comment by flavianmissi** [comment]
I started looking into this today, here's a short update of the little progress I made thus far:
* spent some time understanding the test which is the source of the failure: https://github.com/openshift/kubernetes/blob/master/test/e2e/apps/replica_set.go?plain=1#L284
* built and run the tests locally (here I struggled a little with ginkgo, but I think I got it now)
* trying (and failing) to reproduce the failure by running the test repeatedly in isolation using `GINKGO_UNTIL_IT_FAILS=true` (left it running for over an hour without any luck)
* changed approach to run everything under `test/e2e/apps` in parallel instead, still using `GINKGO_UNTIL_IT_FAILS=true`
The flake is probably caused by a race condition, but more investigation is required.
I'll keep working :)

**Comment by flavianmissi** [comment]
Small update that I won't be working on this during this week - will be back at it normally starting next Monday.
In the meanwhile, this is what I ended up with from last week, as shared with my coworkers internally.

I've combed through kube-apiserver as well as kube-controller-manager logs and put what I found to be relevant on this gist: https://gist.github.com/flavianmissi/48e74926cbd48ff60736d933c7527ec0. The full logs can be found here: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-cos-containerd-e2e-ubuntu-gce/1760837621589741568/artifacts/bootstrap-e2e-master/.
I'm not sure if my interpretation of the kas logs is correct, but from what I see it looks like the LIST call to list resource quotas happens before (at 01:38:56.783880) the actual resource quota is created by the test (at 01:38:57.075670). Am I reading this right?

**Comment by flavianmissi** [comment]
FTR - I have continued to work on this issue this week, but the only progress I made was to build and compare a timeline of kube-apiserver audit logs between a failed test cluster and a success one. Unfortunately I didn't find anything relevant there.
I have asked for help from one of my colleagues and we'll look at this together next week 🤞🏼

**Comment by pacoxu** [comment]
No flake in https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel last weeks.

Still flake in other CIs https://storage.googleapis.com/k8s-triage/index.html?date=2024-03-23&test=ReplicaSet%20should%20surface%20a%20failure%20condition%20on%20a%20common%20issue%20like%20exceeded%20quota and flake rate is low.

**Comment by carlory** [comment]
@Namanl2001 @pacoxu after https://github.com/kubernetes/kubernetes/pull/124163 is merged, no new flaky test occurs. I think we can close this issue now.

- https://storage.googleapis.com/k8s-triage/index.html?date=2024-04-03&test=ReplicaSet%20should%20surface%20a%20failure%20condition%20on%20a%20common%20issue%20like%20exceeded%20quota
- https://storage.googleapis.com/k8s-triage/index.html?date=2024-05-27&test=ReplicaSet%20should%20surface%20a%20failure%20condition%20on%20a%20common%20issue%20like%20exceeded%20quota

**Comment by Namanl2001** [comment]
yes @carlory thanks for the reminder, closing this now 👍

**Comment by pacoxu** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce/1854796473967841280 flake recently, but until now the flake rate is very low. I will open an issue if the flake rate is higher later.
