### ISSUE TITLE
unable to pull old version of Kubernetes|1.23.15-00

### ISSUE THREAD

**Issue by musigma-admin** [kubernetes/kubernetes#123830]
### What happened?

The user encountered difficulty adding a new node to the Kubernetes cluster due to the inability to locate the necessary packages on the repository.

### What did you expect to happen?

I expected to successfully locate and access package version 1.23.15 on the repository when adding the new node to the Kubernetes cluster.

### How can we reproduce it (as minimally and precisely as possible)?

    Attempt to add a new node to the Kubernetes cluster.
    During the node addition process, specify the use of package version 1.23.15.
    Observe that the package cannot be located on the repository, resulting in a failure to add the new node to the cluster.

### Anything else we need to know?

The operating system running on the node where the issue occurred is Ubuntu 22.04.3 LTS.
 Versions of Kubernetes are 1.23.15.
My Production server is still running on 1.23.15 and wont be able to upgrade it to the newer versions soon.

Its critical that the new machine is added to the cluster.

In case there is no way access the old packages .Kindly help us how we can bring this node and add them.

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:49:13Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:42:57Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>

</details>

### OS version

Ubuntu 22.04

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
/close

https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

**Comment by musigma-admin** [comment]
I have added the sig as you have asked. Also to answering to @dims  

I cannot just go back to the new one. The Kubernetes new release migration is a time-consuming process and might require multiple servers to be down which we cannot afford now. It would require a separate plan but as of now we would like to stick to the current one.

Kindly emphasize the current situation to help us with a solution.
