### ISSUE TITLE
pod preemptionPolicy can not set

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#123882]
### What happened?

root@29-b:~/k8s-core-teaching/pod# kubectl apply -f preemptionPolicy-priority-Never-without-priority.yaml  -n k8s
Error from server (Forbidden): error when creating "preemptionPolicy-priority-Never-without-priority.yaml": pods "nginx-pod" is forbidden: the string value of PreemptionPolicy (Never) must not be provided in pod spec; priority admission controller computed PreemptLowerPriority from the given PriorityClass name

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: container
    image: nginx
  preemptionPolicy: Never
```

### What did you expect to happen?

apply ok

### How can we reproduce it (as minimally and precisely as possible)?

apply the yaml

### Kubernetes version

<details>
root@29-b:~/k8s-core-teaching/pod# kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
</details>

### Cloud provider

<details>
wmare
</details>

### OS version

<details>
root@29-b:~/k8s-core-teaching/pod# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
wmare
</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by T-Lakshmi** [comment]
@13567436138,
It seems you have followed the correct approach,
First you need to create a **PriorityClass** object and then you should apply that PriorityClass inside your pod manifest file.

**Comment by T-Lakshmi** [comment]
Follow the steps mentioned in the [official k8s document](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#non-preempting-priority-class) _Pod Priority and Preemption_ and let us know if you still facing the issue.

**Comment by neolit123** [comment]
^ yes, also a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
