### ISSUE TITLE
make failed static build CGO_ENABLED=0  cannot find package

### ISSUE THREAD

**Issue by WhiteStart** [kubernetes/kubernetes#123802]
static build CGO_ENABLED=0: k8s.io/kubernetes/cmd/kube-apiserver k8s.io/kubernetes/cmd/kube-controller-manager k8s.io/kubernetes/cmd/kube-scheduler k8s.io/kubernetes/cmd/kube-proxy
pkg/scheduler/framework/plugins/podcapacityofnode/podcapacityofnode.go:6:2: cannot find package "github.com/shirou/gopsutil/v3/cpu" in any of:
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/shirou/gopsutil/v3/cpu (vendor tree)
        /usr/local/go/src/github.com/shirou/gopsutil/v3/cpu (from $GOROOT)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/shirou/gopsutil/v3/cpu (from $GOPATH)
pkg/scheduler/framework/plugins/podcapacityofnode/podcapacityofnode.go:7:2: cannot find package "github.com/shirou/gopsutil/v3/disk" in any of:
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/shirou/gopsutil/v3/disk (vendor tree)
        /usr/local/go/src/github.com/shirou/gopsutil/v3/disk (from $GOROOT)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/shirou/gopsutil/v3/disk (from $GOPATH)
pkg/scheduler/framework/plugins/podcapacityofnode/podcapacityofnode.go:8:2: cannot find package "github.com/shirou/gopsutil/v3/mem" in any of:
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/shirou/gopsutil/v3/mem (vendor tree)
        /usr/local/go/src/github.com/shirou/gopsutil/v3/mem (from $GOROOT)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/shirou/gopsutil/v3/mem (from $GOPATH)
pkg/scheduler/framework/plugins/podcapacityofnode/podcapacityofnode.go:9:2: cannot find package "github.com/shirou/gopsutil/v3/net" in any of:
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/shirou/gopsutil/v3/net (vendor tree)
        /usr/local/go/src/github.com/shirou/gopsutil/v3/net (from $GOROOT)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/github.com/shirou/gopsutil/v3/net (from $GOPATH)
!!! [0308 01:21:05] Call tree:
!!! [0308 01:21:05]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:722 kube::golang::build_some_binaries(...)
!!! [0308 01:21:05]  2: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:878 kube::golang::build_binaries_for_platform(...)
!!! [0308 01:21:05]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0308 01:21:05] Call tree:
!!! [0308 01:21:05]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0308 01:21:05] Call tree:
!!! [0308 01:21:05]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make: *** [Makefile:92: all] Error 1
!!! [0308 01:21:05] Call tree:
!!! [0308 01:21:05]  1: build/../build/common.sh:480 kube::build::run_build_command_ex(...)
!!! [0308 01:21:05]  2: build/release-images.sh:40 kube::build::run_build_command(...)
Makefile:450: recipe for target 'quick-release-images' failed
make: *** [quick-release-images] Error 1

below is my go env:
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/GOPATH/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/GOPATH"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.10"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/kubernetes-1.23.6/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4169701844=/tmp/go-build -gno-record-gcc-switches"

**Comment by neolit123** [comment]
> pkg/scheduler/framework/plugins/podcapacityofnode/podcapacityofnode.go:6:2: cannot find package "github.com/shirou/gopsutil/v3/cpu" in any of:

looks like github.com/shirou/gopsutil is used in a scheduler plugin.

/sig scheduling

@WhiteStart 
does it help if you set GOROOT too?

**Comment by WhiteStart** [comment]
> > pkg/scheduler/framework/plugins/podcapacityofnode/podcapacityofnode.go:6:2: cannot find package "github.com/shirou/gopsutil/v3/cpu" in any of:
> 
> looks like github.com/shirou/gopsutil is used in a scheduler plugin.
> 
> /sig scheduling
> 
> @WhiteStart does it help if you set GOROOT too?
I customized a scheduler，and import "github.com/shirou/gopsutil/v3/cpu". what does /sig scheduling mean? sorry i do not get it
