### ISSUE TITLE
DRA: structured parameters: handling of claim without claim parameters

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#123858]
### What would you like to be added?

Without claim parameters, it is unclear which structured model is meant to be used. If even it was clear, parameters for it might be useful.

We should add a default parameter reference to the ResourceClass. Then if a ResourceClaim has no parameter reference, that default gets used. If both are unset, the claim cannot get allocated.

### Why is this needed?

A claim without parameters may make sense depending on the hardware when users have no special needs.

**Comment by pohly** [comment]
/sig node
/triage accepted
/priority important-soon

https://github.com/kubernetes/kubernetes/pull/123828 is a stop-gap solution for this which hard-codes the default for "named resources" in the code. We should take that out again soon, in 1.31.

**Comment by ravisantoshgudimetla** [comment]
> We should add a default parameter reference to the ResourceClass.

To be clear, when we are adding a reference, we should also ensure that the referenced object exists, should we have a admission controller which creates the referenced resourceclassParameters object on the fly?

**Comment by pohly** [comment]
No. Referencing a default object which doesn't exist is the same as referencing parameters that don't exist: it's a problem when the object is needed, not when the ResourceClass gets created or updated.

**Comment by ravisantoshgudimetla** [comment]
> We should add a default parameter reference to the ResourceClass. Then if a ResourceClaim has no parameter reference, that default gets used. If both are unset, the claim cannot get allocated.

Sorry, I am a bit confused with the above statement and 

>  What we probably want is a field in the ResourceClass which
points to a default ResourceClaimPrameters object that should be used if one
is not supplied as part of the claim.

which was mentioned in https://github.com/kubernetes/kubernetes/pull/123828#issue-2176927920,

Do we want to add new field called ResourceClaimParams which has a default value or do we want to fill in `ParametersRef` when it is nil with a ParameterRef which needs a object to created.

**Comment by pohly** [comment]
We want a new field `DefaultClaimParametersRef` in `ResourceClass`. If `ResourceClaim.ParametersRef` is nil, then `ResourceClass.DefaultClaimParametersRef` gets used instead. If that is also nil, then the claim cannot be allocated.

**Comment by ravisantoshgudimetla** [comment]
> then ResourceClass.DefaultClaimParametersRef gets used instead. 

Who is going to create that? Cluster admin?

**Comment by pohly** [comment]
Cluster admin together with the `ResourceClass`.

**Comment by pohly** [comment]
The new API in 1.31 no longer needs this.

/close
