### ISSUE TITLE
Remember to create kube-system namespace

### ISSUE THREAD

**Issue by jmferrer** [kubernetes/kubernetes#12395]
In ubuntu getting started guide remember to create kube-system namespace before install addons:
https://github.com/GoogleCloudPlatform/kubernetes/compare/master...jmferrer:master

**Comment by dalanlan** [comment]
Done [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/ubuntu/deployAddons.sh#L29) automatically and could save your trouble.

**Comment by jmferrer** [comment]
Automatically tested with: https://github.com/jmferrer/ansible-kubernetes-ubuntu

Nice job.

Thank you.
