### ISSUE TITLE
Cluster all cranky after load testing 

### ISSUE THREAD

**Issue by azr** [kubernetes/kubernetes#12391]
Hello kubiez !

I have a golang written web service runing on kubes+gce and I blitzed it completely with blitz.io .

The app went over machine's memory which caused lots of harm. Here I believe I should have set a mem limit for the pod.

First, the cluster was unavailable for ~30 minutes ( could not kubectl anything, and nothing was restarting)

Then it started working again but weirdly, the logs were unavailable and the  service would not start.

At some point I destroyed the instances, and gce created them back.

After that the cluster started my app again.

But the logging is unavailable now. And it has been like that for a while now (4 days).

```bash
$ kubectl cluster-info
Kubernetes master is running at https://IP
KubeDNS is running at https://IP/api/v1/proxy/namespaces/kube-system/services/kube-dns
KubeUI is running at https://IP/api/v1/proxy/namespaces/kube-system/services/kube-ui
Heapster is running at https://IP/api/v1/proxy/namespaces/kube-system/services/monitoring-heapster
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                     READY     STATUS    RESTARTS   AGE
default       hb-05ac32802b424d022b80156ddc137f80750a0a85-vumuw        1/1       Running   0          20h
kube-system   fluentd-cloud-logging-gke-hb-1fcf8d0b-node-wyrs          1/1       Running   0          1d
kube-system   kube-dns-v6-d50jr                                        0/3       Pending   0          26m
kube-system   kube-ui-v1-0d97b                                         1/1       Running   0          26m
kube-system   monitoring-heapster-v5-3twnx                             0/1       Pending   0          26m
$ kubectl logs hb-05ac32802b424d022b80156ddc137f80750a0a85-vumuw
Error from server: Get https://gke-hb-1fcf8d0b-node-wyrs:10250/containerLogs/default/hb-05ac32802b424d022b80156ddc137f80750a0a85-vumuw/hb-kubernetes: use of closed network connection
```

How does the logging system works, and how do I make it work again ?
Is the cluster manager or logging not running in one of my nodes ?

Thanks ! :)

**Comment by satnam6502** [comment]
@a-robinson

**Comment by a-robinson** [comment]
The logging system works by proxying your request to the node that the pod is running on. @cjcullen, think that this sort of load testing might mess with the SSH tunnel used to reach the nodes from the master?

**Comment by cjcullen** [comment]
Hmmm. That is definitely an error in the SSH tunneling. I think we have seen problems with the proxy tunnels with pegged instances before. The tunnels should eventually heal. @azr is logging still broken?

**Comment by azr** [comment]
Hey @cjcullen, yes, it is still broken.

**Comment by azr** [comment]
Hello again, just to say the problem is still running.
May be the cluster re-create by google-cloud did not set ssh settings right ?

**Comment by azr** [comment]
Hello there ! 

Just to tell this morning I can read my logs again ! Wohoo !

No need to ssh in the node to get logs ! :)

I'll close the issue for yah, you seem to have plenty to handle.

**Comment by cjcullen** [comment]
Sorry this fell off my radar, but glad to hear it is working again!!
