### ISSUE TITLE
[KEP-2400] Add ability to get node's swap capacity with `kubectl describe node`

### ISSUE THREAD

**Issue by iholder101** [kubernetes/kubernetes#123962]
### What would you like to be added?

Add ability to get node's swap capacity with `kubectl describe node`

### Why is this needed?

KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap

**Comment by ffromani** [comment]
@iholder101 considering the direction taken into https://github.com/kubernetes/kubernetes/pull/125278 please consider renaming and rewording this issue

**Comment by pacoxu** [comment]
> @iholder101 considering the direction taken into #125278 please consider renaming and rewording this issue

https://github.com/kubernetes/kubernetes/pull/125278 is closed.


https://github.com/kubernetes/enhancements/pull/4701/files#diff-32d9cbd2b6817965ecee751dfe43b0d91269aee738a5799c9c9a68d04a329ec6R1138-R1139 is still WIP
- The current statement is to use the metric: `/metrics/resource` endpoint
  - Nodes with swap enabled -> `node.swap.swapAvailableBytes` should be non-zero.
  - Nodes with memory pressure -> `node.swap.swapUsageBytes` should be non-zero.

**Comment by iholder101** [comment]
We've decided to defer this to follow-up KEPs, so I think I'll close this for now.
See https://github.com/kubernetes/kubernetes/pull/125278#issuecomment-2301332049 for more details.

/close
