### ISSUE TITLE
GKE schedules pods that prevent scale down

### ISSUE THREAD

**Issue by matti** [kubernetes/kubernetes#123989]
### What happened?

Original issue was closed for no reason: #69696 

GKE still schedules all kinds of pods that prevent scaledown

### What did you expect to happen?

Pods not to prevent scaledown

### How can we reproduce it (as minimally and precisely as possible)?

Run a cluster and try to scaledown after scaleup

### Kubernetes version

since 2018 until today

### Cloud provider

Google

**Comment by andrewsykim** [comment]
cc @SergeyKanzhelev

**Comment by BenTheElder** [comment]
This should be a ticket with cloud support, the Kubernetes project is not responsible for GKE and this issue tracker is not the right place for GKE support requests.

**Comment by elmiko** [comment]
we are reviewing this during the sig cloud provider office hours, do we know if this is GKE specific or does it occur on all cloud providers?

if it's only GKE, then we are inclined to follow @BenTheElder 's advice and close this in favor of a ticket with cloud support.

**Comment by bridgetkromhout** [comment]
@matti We believe this is specific to GKE; please go ahead and open a ticket with GKE support. If GKE support doesn't help, SIG Autoscaling would be the next place to check.

/sig autoscaling

**Comment by elmiko** [comment]
this is a cloud support issue not a sig cloud-provider issue. the pods that are referenced here (eg fluent related) are not kubernetes specific. we still think this needs to be brought up  with gke support.

/remove-sig cloud-provider

**Comment by elmiko** [comment]
marking this as stale to accelerate the process

/lifecycle stale

**Comment by BenTheElder** [comment]
Let's just close it, there's no indication that this is an upstream issue and no follow up.

This issue tracker does not offer product support, only the open source project.

Please follow up with product support if you're still having issues with this, or reopen this issue after commenting with more information about how this is related to the open source project.
