### ISSUE TITLE
SecretProviderClass should be versioned similar to configmaps

### ISSUE THREAD

**Issue by fishy** [kubernetes/kubernetes#123955]
### What happened?

Let's say we have a service A, which currently depends on 2 secrets, B & C, provided by a `SecretProviderClass`.

Then, a new version of A removed the usage of secret C, so it now only need one secret B.

When deploying the new version, 2 things will happen:

1. The `SecretProviderClass` being updated to remove C and only provide B
2. The pods for A being _gradually_ replaced by the new version that no longer needs C

But since 1 is almost immediate while 2 is always a gradual rollout, after 1 is replaced the old pods still requiring both B and C will likely start to fail because the update of `SecretProviderClass` that removed C that they still require.

Even if we tweak the order to only do 1 after 2 is fully done, it can still cause the reverse problem (a new version that requires a new secret).

Currently, to avoid this issue we need to be extra careful and do 2-step deploys, first deploy a superset of `SecretProviderClass` that contains the secrets for both new and old version of code with the new code, and after that's fully done, do another deploy to shrink `SecretProviderClass` to only the ones needed by the new version.

But I think to fully address this problem, we should make `SecretProviderClass` versioned (similar to how configmaps are versioned), so every pod can use their matching version of `SecretProviderClass` to provide the secrets they need.

### What did you expect to happen?

See above.

### How can we reproduce it (as minimally and precisely as possible)?

See above.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
1.27.10

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aramase** [comment]
For questions related to the Secrets Store CSI Driver project, please open issues [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues) and/or reach out to us on [slack](https://github.com/kubernetes-sigs/secrets-store-csi-driver?tab=readme-ov-file#want-to-help).

/close
