### ISSUE TITLE
Troubleshooting kubeadm (docker has enough images but k8s init still pulls the image)

### ISSUE THREAD

**Issue by linkhacker** [kubernetes/kubernetes#123901]
docker has enough images but k8s init still pulls the image

[root@master-node-01 k8s]# kubeadm init --pod-network-cidr=192.168.10.0/16 --control-plane-endpoint "10.0.241.70:6443"  --kubernetes-version v1.29.2 --v=5
I0312 17:13:01.744084   41512 initconfiguration.go:122] detected and using CRI socket: unix:///var/run/containerd/containerd.sock
I0312 17:13:01.744239   41512 interface.go:432] Looking for default routes with IPv4 addresses
I0312 17:13:01.744249   41512 interface.go:437] Default route transits interface "eth0"
I0312 17:13:01.744348   41512 interface.go:209] Interface eth0 is up
I0312 17:13:01.744387   41512 interface.go:257] Interface "eth0" has 2 addresses :[10.0.241.70/24 fe80::250:56ff:fe80:9466/64].
I0312 17:13:01.744399   41512 interface.go:224] Checking addr  10.0.241.70/24.
I0312 17:13:01.744407   41512 interface.go:231] IP found 10.0.241.70
I0312 17:13:01.744418   41512 interface.go:263] Found valid IPv4 address 10.0.241.70 for interface "eth0".
I0312 17:13:01.744425   41512 interface.go:443] Found active IP 10.0.241.70
I0312 17:13:01.744440   41512 kubelet.go:196] the value of KubeletConfiguration.cgroupDriver is empty; setting it to "systemd"
[init] Using Kubernetes version: v1.29.2
[preflight] Running pre-flight checks
I0312 17:13:01.752502   41512 checks.go:563] validating Kubernetes and kubeadm version
I0312 17:13:01.752524   41512 checks.go:168] validating if the firewall is enabled and active
I0312 17:13:01.770964   41512 checks.go:203] validating availability of port 6443
I0312 17:13:01.771387   41512 checks.go:203] validating availability of port 10259
I0312 17:13:01.771494   41512 checks.go:203] validating availability of port 10257
I0312 17:13:01.771608   41512 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0312 17:13:01.771770   41512 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0312 17:13:01.771812   41512 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0312 17:13:01.771932   41512 checks.go:280] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0312 17:13:01.772050   41512 checks.go:430] validating if the connectivity type is via proxy or direct
I0312 17:13:01.772156   41512 checks.go:469] validating http connectivity to first IP address in the CIDR
I0312 17:13:01.772237   41512 checks.go:469] validating http connectivity to first IP address in the CIDR
I0312 17:13:01.772278   41512 checks.go:104] validating the container runtime
I0312 17:13:01.795557   41512 checks.go:639] validating whether swap is enabled or not
I0312 17:13:01.795701   41512 checks.go:370] validating the presence of executable crictl
I0312 17:13:01.795830   41512 checks.go:370] validating the presence of executable conntrack
I0312 17:13:01.795950   41512 checks.go:370] validating the presence of executable ip
I0312 17:13:01.796111   41512 checks.go:370] validating the presence of executable iptables
I0312 17:13:01.796220   41512 checks.go:370] validating the presence of executable mount
I0312 17:13:01.796311   41512 checks.go:370] validating the presence of executable nsenter
I0312 17:13:01.796420   41512 checks.go:370] validating the presence of executable ebtables
I0312 17:13:01.796499   41512 checks.go:370] validating the presence of executable ethtool
I0312 17:13:01.796583   41512 checks.go:370] validating the presence of executable socat
I0312 17:13:01.796664   41512 checks.go:370] validating the presence of executable tc
I0312 17:13:01.796732   41512 checks.go:370] validating the presence of executable touch
I0312 17:13:01.796835   41512 checks.go:516] running all checks
I0312 17:13:01.810847   41512 checks.go:401] checking whether the given node name is valid and reachable using net.LookupHost
I0312 17:13:01.811025   41512 checks.go:605] validating kubelet version
I0312 17:13:01.858612   41512 checks.go:130] validating if the "kubelet" service is enabled and active
I0312 17:13:01.875420   41512 checks.go:203] validating availability of port 10250
I0312 17:13:01.875603   41512 checks.go:329] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0312 17:13:01.875728   41512 checks.go:329] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0312 17:13:01.875802   41512 checks.go:203] validating availability of port 2379
I0312 17:13:01.875885   41512 checks.go:203] validating availability of port 2380
I0312 17:13:01.875996   41512 checks.go:243] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I0312 17:13:01.876342   41512 checks.go:828] using image pull policy: IfNotPresent
I0312 17:13:01.898194   41512 checks.go:854] pulling: registry.k8s.io/kube-apiserver:v1.29.2
I0312 17:13:02.009771   41512 checks.go:854] pulling: registry.k8s.io/kube-controller-manager:v1.29.2
I0312 17:13:02.155468   41512 checks.go:854] pulling: registry.k8s.io/kube-scheduler:v1.29.2
I0312 17:13:02.294060   41512 checks.go:854] pulling: registry.k8s.io/kube-proxy:v1.29.2
I0312 17:13:02.410021   41512 checks.go:854] pulling: registry.k8s.io/coredns/coredns:v1.11.1
I0312 17:13:02.548362   41512 checks.go:854] pulling: registry.k8s.io/pause:3.9
I0312 17:13:02.645862   41512 checks.go:854] pulling: registry.k8s.io/etcd:3.5.10-0
[preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.29.2: output: E0312 17:13:01.989013   41570 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.29.2\": failed to resolve reference \"registry.k8s.io/kube-apiserver:v1.29.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-apiserver/manifests/v1.29.2\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:46078->[::1]:53: read: connection refused" image="registry.k8s.io/kube-apiserver:v1.29.2"
time="2024-03-12T17:13:01+07:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.29.2\": failed to resolve reference \"registry.k8s.io/kube-apiserver:v1.29.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-apiserver/manifests/v1.29.2\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:46078->[::1]:53: read: connection refused"
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-controller-manager:v1.29.2: output: E0312 17:13:02.130442   41607 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.29.2\": failed to resolve reference \"registry.k8s.io/kube-controller-manager:v1.29.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-controller-manager/manifests/v1.29.2\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:12819->[::1]:53: read: connection refused" image="registry.k8s.io/kube-controller-manager:v1.29.2"
time="2024-03-12T17:13:02+07:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.29.2\": failed to resolve reference \"registry.k8s.io/kube-controller-manager:v1.29.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-controller-manager/manifests/v1.29.2\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:12819->[::1]:53: read: connection refused"
, error: exit status 1
[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-scheduler:v1.29.2: output: E0312 17:13:02.273298   41645 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.29.2\": failed to resolve reference \"registry.k8s.io/kube-scheduler:v1.29.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-scheduler/manifests/v1.29.2\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:20709->[::1]:53: read: connection refused" image="registry.k8s.io/kube-scheduler:v1.29.2"
time="2024-03-12T17:13:02+07:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.29.2\": failed to resolve reference \"registry.k8s.io/kube-scheduler:v1.29.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-scheduler/manifests/v1.29.2\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:20709->[::1]:53: read: connection refused"
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-proxy:v1.29.2: output: E0312 17:13:02.389160   41681 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-proxy:v1.29.2\": failed to resolve reference \"registry.k8s.io/kube-proxy:v1.29.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-proxy/manifests/v1.29.2\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:63698->[::1]:53: read: connection refused" image="registry.k8s.io/kube-proxy:v1.29.2"
time="2024-03-12T17:13:02+07:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/kube-proxy:v1.29.2\": failed to resolve reference \"registry.k8s.io/kube-proxy:v1.29.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-proxy/manifests/v1.29.2\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:63698->[::1]:53: read: connection refused"
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/coredns/coredns:v1.11.1: output: E0312 17:13:02.516062   41718 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/coredns/coredns:v1.11.1\": failed to resolve reference \"registry.k8s.io/coredns/coredns:v1.11.1\": failed to do request: Head \"https://registry.k8s.io/v2/coredns/coredns/manifests/v1.11.1\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:11226->[::1]:53: read: connection refused" image="registry.k8s.io/coredns/coredns:v1.11.1"
time="2024-03-12T17:13:02+07:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/coredns/coredns:v1.11.1\": failed to resolve reference \"registry.k8s.io/coredns/coredns:v1.11.1\": failed to do request: Head \"https://registry.k8s.io/v2/coredns/coredns/manifests/v1.11.1\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:11226->[::1]:53: read: connection refused"
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/pause:3.9: output: E0312 17:13:02.629398   41760 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/pause:3.9\": failed to resolve reference \"registry.k8s.io/pause:3.9\": failed to do request: Head \"https://registry.k8s.io/v2/pause/manifests/3.9\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:57673->[::1]:53: read: connection refused" image="registry.k8s.io/pause:3.9"
time="2024-03-12T17:13:02+07:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/pause:3.9\": failed to resolve reference \"registry.k8s.io/pause:3.9\": failed to do request: Head \"https://registry.k8s.io/v2/pause/manifests/3.9\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:57673->[::1]:53: read: connection refused"
, error: exit status 1
[ERROR ImagePull]: failed to pull image registry.k8s.io/etcd:3.5.10-0: output: E0312 17:13:02.724575   41796 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/etcd:3.5.10-0\": failed to resolve reference \"registry.k8s.io/etcd:3.5.10-0\": failed to do request: Head \"https://registry.k8s.io/v2/etcd/manifests/3.5.10-0\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:12166->[::1]:53: read: connection refused" image="registry.k8s.io/etcd:3.5.10-0"
time="2024-03-12T17:13:02+07:00" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/etcd:3.5.10-0\": failed to resolve reference \"registry.k8s.io/etcd:3.5.10-0\": failed to do request: Head \"https://registry.k8s.io/v2/etcd/manifests/3.5.10-0\": dial tcp: lookup registry.k8s.io on [::1]:53: read udp [::1]:12166->[::1]:53: read: connection refused"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with --ignore-preflight-errors=...
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:260
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:446
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:232
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        cmd/kubeadm/app/cmd/init.go:124
github.com/spf13/cobra.(*Command).execute
        vendor/github.com/spf13/cobra/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
        vendor/github.com/spf13/cobra/command.go:1068
github.com/spf13/cobra.(*Command).Execute
        vendor/github.com/spf13/cobra/command.go:992
k8s.io/kubernetes/cmd/kubeadm/app.Run
        cmd/kubeadm/app/kubeadm.go:50
main.main
        cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:267
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1650

[root@master-node-01 k8s]# docker images
REPOSITORY                                TAG        IMAGE ID       CREATED         SIZE
flannel/flannel                           v0.24.3    f6f0ee58f497   5 days ago      78.6MB
registry.k8s.io/kube-apiserver            v1.29.2    8a9000f98a52   3 weeks ago     127MB
registry.k8s.io/kube-controller-manager   v1.29.2    138fb5a3a2e3   3 weeks ago     122MB
registry.k8s.io/kube-proxy                v1.29.2    9344fce2372f   3 weeks ago     82.3MB
registry.k8s.io/kube-scheduler            v1.29.2    6fc5e6b7218c   3 weeks ago     59.5MB
registry.k8s.io/etcd                      3.5.10-0   a0eed15eed44   4 months ago    148MB
registry.k8s.io/coredns/coredns           v1.11.1    cbb01a7bd410   6 months ago    59.8MB
registry.k8s.io/pause                     3.9        e6f181688397   17 months ago   744kB
k8s.gcr.io/ingress-nginx/controller       v0.41.0    28baf567207f   3 years ago     279MB
jettech/kube-webhook-certgen              v1.5.0     344297e197b6   3 years ago     44.7MB

**Comment by harshanarayana** [comment]
@linkhacker You should take a look at https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-NodeRegistrationOptions

There is an option to set the `ImagePullPolicy` that gets used during the preflight check using that kubeadm's `InitConfiguration`.

**Comment by neolit123** [comment]
https://kubernetes.io/docs/setup/production-environment/container-runtimes/

> Kubernetes releases before v1.24 included a direct integration with Docker Engine, using a component named dockershim. That special direct integration is no longer part of Kubernetes 

probably you have cri-o or containerd installed and kubeadm is pulling using those. if you have multiple CRs you have to configure kubeadm's criSocket option.
https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/

for more Qs please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
