### ISSUE TITLE
Node maintenance documentation out of date 

### ISSUE THREAD

**Issue by perljedi** [kubernetes/kubernetes#12398]
The documentation for in docs/admin/cluster-management.md suggest using: 

```
kubectl replace nodes $NODENAME --patch='{"apiVersion": "v1", "spec": {"unschedulable": true}}'
```

Before bringing down a node, however kubectl says that `--patch` is not a supported option.  

Is there a way at this point to mark a node as unschedulable?

BTW:
```
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.2", GitCommit:"e310e619fc1ac4f3238bf5ebe9e7033bf5d47ee2", GitTreeState:"clean"}
```

**Comment by mbforbes** [comment]
@brendandburns

**Comment by jmccarty3** [comment]
kubectl patch nodes $NODENAME -p '{"spec": {"unschedulable": true}}'

Works for me to mark the node as unschedulable.

**Comment by perljedi** [comment]
That works for me also... though the documentation at
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/node.md#manual-node-administration
should probably be updated to reflect that syntax.
