### ISSUE TITLE
1.30 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by rashansmith** [kubernetes/kubernetes#124046]
### What happened?

This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.30 Release Notes. If you know of issues or API changes that are going out in 1.30, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @kubernetes/release-team-release-notes

/sig release
/milestone v1.30

**Comment by npolshakova** [comment]
https://github.com/kubernetes/release/issues/3516

**Comment by neolit123** [comment]
we have two regressions in kubeadm for 1.30.0.
please adjust the language or format as see fit.

-------------

Kubeadm 1.30.0 includes two regressions related to the `kubeadm upgrade apply` command. The kubeadm maintainers recommend that you skip 1.30.0 and upgrade to 1.30.1 instead, or alternatively apply the mitigations explained below.

- `kubeadm upgrade apply` fails with a `CreateJob` preflight error if the cluster has a single node that is a control plane node.
https://github.com/kubernetes/kubeadm/issues/3049
To mitigate the problem, you can pass the flag `--ignore-preflight-errors=CreateJob`

- `kubeadm upgrade apply` does not download the `KubeletConfiguration` stored in the cluster in the `kube-system/kubelet-config` ConfigMap and instead writes a file with defaults in `/var/lib/kubelet/config.yaml`.
https://github.com/kubernetes/kubeadm/issues/3050
To mitigate the problem, you have to manually get the ConfigMap contents with `kubectl get cm -n kube-system kubelet-config -o "jsonpath={.data['kubelet']}"`, write them to `/var/lib/kubelet/config.yaml` and manually apply any node-specific customizations if you are using `--patches` with a `kubeletconfiguration` target.

**Comment by carlory** [comment]
@neolit123 links are incorrect.

**Comment by neolit123** [comment]
> @neolit123 links are incorrect.

fixed

**Comment by pmalek** [comment]
- https://github.com/kubernetes/kubernetes/issues/124540 users including [ImagePullSecrets](https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/apis/core/types.go#L3289-L3292) or in their CRDs will not be able to apply them using kubernetes packages from 1.30.0 tag
  - fix backported to release-1.30 branch in https://github.com/kubernetes/kubernetes/pull/124694.

**Comment by pacoxu** [comment]
/close
as 1.30 was released months ago.
