### ISSUE TITLE
podLogsDir validation of default value breaks on windows

### ISSUE THREAD

**Issue by HuShaoRu** [kubernetes/kubernetes#124076]
### What happened?

> Kubelet: a custom root directory for pod logs (instead of default /var/log/pods) can be specified using the podLogsDir key in kubelet configuration. (https://github.com/kubernetes/kubernetes/pull/112957, [@mxpv](https://github.com/mxpv)) [SIG API Machinery, Node, Scalability and Testing]

`podLogsDir` is not added in `cmd/kubelet/app/options/options.go` so I can't use this flag when running kubelet v1.30.0-beta.0.

also, when I ran it in windows (it's fine when I ran it in linux), I got `invalid configuration: pod logs path \"/var/log/pods\" must be absolute path, invalid configuration: pod logs path \"/var/log/pods\" must be normalized`. Notice there are unexpected \ before quotes.

### What did you expect to happen?

I should be able to run `kubelet` with `--pod-logs-dir`. If I don't use this flag, it should correctly use default value.

### How can we reproduce it (as minimally and precisely as possible)?

run newest kubelet on windows node with some necessary parameters
```sh
./kubelet --version
> Kubernetes v1.30.0-beta.0
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
/remove-sig api-machinery
/sig node

This option is only added to the kubelet config file, so can only be used via that mechanism. It is intentional that not all new options are added as flags, the direction of kubelet configuration is to add new options to the configuration file.

**Comment by liggitt** [comment]
The windows validation error looks legitimate. The \ before the quotes doesn't matter, the issue is behavior of filepath.Clean on windows replacing / with \ in the path itself.

/sig windows
/milestone v1.30
/kind regression

**Comment by liggitt** [comment]
/assign @mxpv

the default for the newly configurable field appears to break windows kubelets

**Comment by liggitt** [comment]
cc @kubernetes/sig-windows-bugs

**Comment by kannon92** [comment]
Is there a way to include some windows tests by default?

**Comment by kannon92** [comment]
You can reproduce this with a presubmit.

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-ci-kubernetes-unit-windows/1772979141621059584

Run /test pull-ci-kubernetes-unit-windows and it will show the validation failures.

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/pull/112957/files#diff-b0fe5718080ac03df1496042447e4468534f1c4648522af21b064efdeee181b0R296-R298

```
	if !filepath.IsAbs(kc.PodLogsDir) {
		allErrors = append(allErrors, fmt.Errorf("invalid configuration: pod logs path %q must be absolute path", kc.PodLogsDir))
	}
```

a Unix path default that is validated with isAbs on Windows will just fail because there is no drive letter prefix e.g. `C:\`
isAbs in the validator is not portable as is.

**Comment by aravindhp** [comment]
Should we consider running the Windows unit test by default for all PRs?

**Comment by neolit123** [comment]
> Should we consider running the Windows unit test by default for all PRs?

+1

**Comment by aravindhp** [comment]
Turns out there are some failing and flaky tests in the Windows unit tests. I am hoping we can disable them for now and keep enabling them as they are fixed, so that we can run the passing tests by default.

**Comment by neolit123** [comment]
> Turns out there are some failing and flaky tests in the Windows unit tests. I am hoping we can disable them for now and keep enabling them as they are fixed, so that we can run the passing tests by default.

there are some WIPs
https://github.com/kubernetes/kubernetes/pull/119436
https://github.com/kubernetes/kubernetes/pull/122072

**Comment by kannon92** [comment]
/priority important-soon

I can't find a critical label..

**Comment by aravindhp** [comment]
> > Turns out there are some failing and flaky tests in the Windows unit tests. I am hoping we can disable them for now and keep enabling them as they are fixed, so that we can run the passing tests by default.
> 
> there are some WIPs #119436 #122072

@neolit123 these were the ones I was talking about. SIG-windows has just been struggling to get them merged 😞

**Comment by SergeyKanzhelev** [comment]
Slack thread: https://kubernetes.slack.com/archives/C0SJ4AFB7/p1711553979064829

**Comment by aravindhp** [comment]
@mxpv is [looking into it](https://kubernetes.slack.com/archives/C0SJ4AFB7/p1711563837273169?thread_ts=1711553979.064829&cid=C0SJ4AFB7)

**Comment by neolit123** [comment]
> /priority important-soon
> 
> I can't find a critical label..

/remove-priority important-soon
/priority critical-urgent

**Comment by neolit123** [comment]
> > > Turns out there are some failing and flaky tests in the Windows unit tests. I am hoping we can disable them for now and keep enabling them as they are fixed, so that we can run the passing tests by default.
> > 
> > 
> > there are some WIPs #119436 #122072
> 
> @neolit123 these were the ones I was talking about. SIG-windows has just been struggling to get them merged 😞

https://github.com/kubernetes/kubernetes/pull/119436 was on sig scheduling.
https://github.com/kubernetes/kubernetes/pull/122072/files touches too many separate SIG OWNER files.

**Comment by jsturtevant** [comment]
I was trying this out and I am not getting the same behavior.  Using the following minimal config that works with Windows:

```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupsPerQOS: false
enforceNodeAllocatable: []
authentication: 
  webhook:
    enabled: false
authorization:
  mode: AlwaysAllow
containerRuntimeEndpoint: "npipe:////./pipe/containerd-containerd"
```

kubelet is starting:

```
.\kubelet.exe --version
Kubernetes v1.31.0-alpha.0.7+f4e246bc93ffb6-dirty

.\kubelet.exe --config .\config.yaml
I0328 11:55:26.927635   23820 server_windows.go:40] "Kubelet is running as" login  dispaly name="James Sturtevant"
I0328 11:55:26.929710   23820 server.go:484] "Kubelet version" kubeletVersion="v1.31.0-alpha.0.7+f4e246bc93ffb6-dirty"
I0328 11:55:26.929710   23820 server.go:486] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I0328 11:55:26.930269   23820 init_windows.go:82] "Creating a Windows job object and adding kubelet process to it" windowsPriorityClass="NORMAL_PRIORITY_CLASS"
I0328 11:55:26.930806   23820 server.go:647] "Standalone mode, no API client"
I0328 11:55:27.337961   23820 server.go:535] "No api server defined - no events will be sent to API server"
I0328 11:55:27.609506   23820 fake_topology_manager.go:33] "NewFakeManager"
I0328 11:55:27.609506   23820 container_manager_windows.go:120] "Creating device plugin manager"
I0328 11:55:27.609506   23820 fake_topology_manager.go:68] "AddHintProvider" hintProvider={}
I0328 11:55:27.610023   23820 server.go:871] "Failed to ApplyOOMScoreAdj" err="setting OOM scores is unsupported in this build"
I0328 11:55:27.610023   23820 kubelet.go:406] "Kubelet is running in standalone mode, will skip API server sync"
I0328 11:55:27.728636   23820 state_mem.go:36] "Initialized new in-memory state store"
I0328 11:55:27.729146   23820 state_mem.go:35] "Initializing new in-memory state store"
I0328 11:55:27.729146   23820 fake_topology_manager.go:33] "NewFakeManager"
I0328 11:55:27.730248   23820 kuberuntime_manager.go:261] "Container runtime initialized" containerRuntime="containerd" version="2.0.0-rc.0+unknown" apiVersion="v1"
I0328 11:55:28.289240   23820 kubelet.go:815] "Not starting ClusterTrustBundle informer because we are in static kubelet mode"
I0328 11:55:28.290444   23820 volume_host.go:77] "KubeClient is nil. Skip initialization of CSIDriverLister"
W0328 11:55:28.290979   23820 csi_plugin.go:202] kubernetes.io/csi: kubeclient not set, assuming standalone kubelet
W0328 11:55:28.290979   23820 csi_plugin.go:279] Skipping CSINode initialization, kubelet running in standalone mode
E0328 11:55:28.291509   23820 server.go:1253] "Failed to set rlimit on max file handles" err="SetRLimit unsupported in this platform"
I0328 11:55:28.291509   23820 server.go:1264] "Started kubelet"
I0328 11:55:28.291509   23820 kubelet.go:1615] "No API server defined - no node status update will be sent"
I0328 11:55:28.291509   23820 ratelimit.go:55] "Setting rate limiting for endpoint" service="podresources" qps=100 burstTokens=10
I0328 11:55:28.292600   23820 server.go:227] "Starting to serve the podresources API" endpoint="npipe://\\\\.\\pipe\\kubelet-pod-resources"
I0328 11:55:28.291509   23820 server.go:163] "Starting to listen" address="0.0.0.0" port=10250
I0328 11:55:28.295328   23820 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
I0328 11:55:28.296408   23820 status_manager.go:213] "Kubernetes client is nil, not starting status manager"
I0328 11:55:28.296408   23820 volume_manager.go:291] "Starting Kubelet Volume Manager"
I0328 11:55:28.296408   23820 desired_state_of_world_populator.go:149] "Desired state populator starts to run"
I0328 11:55:28.295901   23820 server.go:455] "Adding debug handlers to kubelet server"
I0328 11:55:28.296934   23820 kubelet.go:2337] "Starting kubelet main sync loop"
```


Something else seems not right with the path when I added some logging: `config path: C:\temp\var\log\pods`

@HuShaoRu could you share a config file that produces the `invalid configuration: pod logs path \"/var/log/pods\" must be absolute path, invalid configuration: pod logs path \"/var/log/pods\" must be normalized` error?

**Comment by jsturtevant** [comment]
> Something else seems not right with the path when I added some logging: `config path: C:\temp\var\log\pods`

This depends on where the file is loaded based on this path being parsed. I had it stored in a folder called `c:\temp`
 https://github.com/kubernetes/kubernetes/blob/f4e246bc93ffb68b33ed67c7896c379efa4207e7/pkg/kubelet/kubeletconfig/configfiles/configfiles.go#L103-L105

Even after putting this in `c:\config.toml` then I am not able to get the error called out by @HuShaoRu it ends up being resovled to `C:\var\log\pods`

**Comment by HuShaoRu** [comment]
I don't use --config but directly use command line arguments.
I can get the error even when no arguments are provided:
```cmd
>. \kubelet.exe
E0401 04:44:23.548113 7376 run.go:74] "command failed" err="failed to validate kubelet configuration, error: [invalid configuration: Cgroups PerQOS (--cgroups-per- qos) true is not supported on Windows, invalid configurat ion: EnforceNodeAllocatable (--enforce-node-allocatable) [pods] is not supported on Windows, invalid configurat ion: pod logs path \"/var/log/pods\" must be absolute path, invalid configuration: pod logs path \"/var/log/pod s\" must be normalized], path: &TypeMeta{Kind:,APIVersion:,}"
```

**Comment by sanchita-07** [comment]
cc @pacoxu @Vyom-Yadav

**Comment by jsturtevant** [comment]
Based on the following, Windows kubelet has never been able to start without passing a `config`. or overriding some values. 

https://github.com/kubernetes/kubernetes/blob/f4e246bc93ffb68b33ed67c7896c379efa4207e7/pkg/kubelet/apis/config/validation/validation_windows.go#L30

Is this how you typically start a Windows kubelet?  What parameters do you usually use?  If you pass the config it will be resolved in this code path: https://github.com/kubernetes/kubernetes/blob/f4e246bc93ffb68b33ed67c7896c379efa4207e7/pkg/kubelet/kubeletconfig/configfiles/configfiles.go#L99-L107. 

There does seem to be a bug here, in that the pod log path, now goes through the `resolveRelativePaths` code path and `filepath.IsAbs(*path)` which it is treating it like a relative path which could end up putting the path somewhere not expected.

**Comment by neolit123** [comment]
> validateKubeletOSConfiguration


this is related to my open PR here:
https://github.com/kubernetes/kubernetes/pull/123137

the kubelet on Windows should not throw errors with the defaults (which are Linux defaults).

**Comment by HuShaoRu** [comment]
`We always validate the local configuration (command line + config file)` https://github.com/kubernetes/kubernetes/blob/e3bb757129ceb24625ca9c55639471dec64ec1dc/cmd/kubelet/app/server.go#L243

We didn't use config files in windows kubelet before and it worked well. I don't see any special codes for windows which disallow command line configurations. Is it a new feature in 1.30?

**Comment by jsturtevant** [comment]
@HuShaoRu It is intentional that it is an option only added to the config file (https://github.com/kubernetes/kubernetes/issues/124076#issuecomment-2022722888).  

But those details helped, I am now able to reproduce your scenario.  It would be helpful if you shared the command line you do run (minus any sensitive info).

with 1.30, Running with the bare minimal kubelet command line args we get: 

```
.\kubelet.exe --cgroups-per-qos=false --enforce-node-allocatable=""
Flag --cgroups-per-qos has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --enforce-node-allocatable has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
config path: /var/log/pods
invalid configuration: pod logs path /var/log/pods must be absolute path
```

with 1.29, It starts up:

```
Flag --cgroups-per-qos has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --enforce-node-allocatable has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
I0402 08:32:30.934592   35592 server_windows.go:40] "Kubelet is running as" login name="" dispaly name="James Sturtevant"
E0402 08:32:30.937452   35592 server.go:268] "kubelet running with insufficient permissions" err="kubelet needs to run with elevated permissions!"
I0402 08:32:30.938048   35592 server.go:468] "Kubelet version" kubeletVersion="v1.29.0-alpha.1.121+00c6d9329ecfbd"
I0402 08:32:30.938597   35592 server.go:470] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I0402 08:32:30.938827   35592 init_windows.go:82] "Creating a Windows job object and adding kubelet process to it" windowsPriorityClass="NORMAL_PRIORITY_CLASS"
```

So there are two issues:

1. when there is no config file present it is not possible start kubelet with command line options any more
2. when using the config, the pod log path, now goes through the `resolveRelativePaths` code path and `filepath.IsAbs(*path)` which it is treating it like a relative path which could end up putting the path somewhere not expected.

For 1) I can see it going either way. In this case the default provided should be respected, but at some future release we might need to say that the config is required.
