### ISSUE TITLE
node should not be ready when klog flush deamon in kubelet is block in fsync

### ISSUE THREAD

**Issue by divanodestiny** [kubernetes/kubernetes#124016]
### What happened?

1. some issues cause a part of  fsync syscalls to persist in blocking
2. klog flush deamon hold the lock, call `flushAll` and block in fsync syscall 

https://github.com/kubernetes/kubernetes/blob/a309fadbac3339bc8db9ae0a928a33b8e81ef10f/vendor/k8s.io/klog/v2/klog.go#L1223-L1228

4. other goroutines in kubelet will be block when print log
https://github.com/kubernetes/kubernetes/blob/a309fadbac3339bc8db9ae0a928a33b8e81ef10f/vendor/k8s.io/klog/v2/klog.go#L885-L894

5. kubelet can renew node lease normally because this goroutine do not print log
6. node controller think this node is ready

### What did you expect to happen?

node should be not ready

### How can we reproduce it (as minimally and precisely as possible)?

maybe use ptrace to block fsync?

### Kubernetes version

1.26.0
<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

none
<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yuzhiquan** [comment]
I think this related to this [issue](https://github.com/kubernetes/klog/issues/403),  maybe we can wait for the solution on klog side.

/close
