### ISSUE TITLE
K8s workers NotReady, Kubelet stopped posting node status, kubelet service log "Error getting node" err="node \"workernode\" not found" "failed to ensure lease exists"

### ISSUE THREAD

**Issue by Nameyc99** [kubernetes/kubernetes#124054]
### What happened?

All of our cluster's worker has gone NotReady status. 
![image](https://github.com/kubernetes/kubernetes/assets/81574913/e25eb4c1-0197-425d-bfc9-472370c8dc26)
![image](https://github.com/kubernetes/kubernetes/assets/81574913/4b68edb2-befd-43c7-b64b-2205f64d73f0)

Inspecting one of the workers kubelet log shows below 

![image](https://github.com/kubernetes/kubernetes/assets/81574913/87ea659f-5f95-49d9-832d-9a41996e2678)

### What did you expect to happen?

Workers to be working fine as usual.

### How can we reproduce it (as minimally and precisely as possible)?

Not sure.

### Anything else we need to know?

A week ago we got an error X509: Certificate Has Expired Or Is Not Yet Valid, we updated the certificate using kubeadm certs renew all and it is working fine

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:59:18Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:53:39Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On premises machine
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
- Containerd v1.5.9-0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
### ackage Info
- kubernetes v1.22.12
- keepalived v2.2.4
- haproxy v

### Kubernetes Services Version

- Calico v3.21
- Kubeflow v1.6
</details>

**Comment by xuzhenglun** [comment]
/kind support

It seems like kubelet can not access to kube-apiserver.  I think that you can curl kube-apiserver in prombemic node to test network connectivity.

```
curl -k https://192.168.1.50:8443/healthz
```

**Comment by Nameyc99** [comment]
`$ curl -k https://192.168.1.50:8443/healthz
curl: (7) Failed to connect to 192.168.1.50 port 8443 after 0 ms: Connection refused`

**Comment by Nameyc99** [comment]
Below are both of the pods log
Master 1
![image](https://github.com/kubernetes/kubernetes/assets/81574913/8fa42a50-fd2c-4da3-8e16-c31053522688)
Master 2
![image](https://github.com/kubernetes/kubernetes/assets/81574913/46bb5dd2-552c-4d80-a8db-83ab7ef29ea2)

**Comment by neolit123** [comment]
looks like expired certificates.
you should try to resolve with help from the support forums.
we don't provide support on github.

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
