### ISSUE TITLE
Performance tracking/improvements across Kubernetes release 

### ISSUE THREAD

**Issue by faszhang** [kubernetes/kubernetes#124020]
Hi Team,

I did some search the Kubernetes performance documentation. https://kubernetes.io/blog/2015/09/kubernetes-performance-measurements-and/

Do we have a tracking of the Kubernetes performance across releases?

**Comment by faszhang** [comment]
> /sig release scalability

@neolit123  can you add me to this slack **https://kubernetes.slack.com/messages/sig-scale**

**Comment by neolit123** [comment]
> > /sig release scalability
> 
> @neolit123 can you add me to this slack **https://kubernetes.slack.com/messages/sig-scale**

i cannot.
you should join the k8s slack and open the channel.
