### ISSUE TITLE
Even if the container has failed, the DaemonSet pod's phase still shows running

### ISSUE THREAD

**Issue by bigfan6** [kubernetes/kubernetes#124095]
### What happened?

In a single container pod, the container has encountered an error, but the pod status is still running, resulting in not being pulled up in a timely manner

### What did you expect to happen?

When encountering an error in the container, the DaemonSet pod should be refreshed to failed

### Kubernetes version

<details>

```console
$ kubectl version
v1.28.1
</details>


### Cloud provider

<details>
na
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Linux master1 5.10.0-136.12.0.86.h1616.eulerosv2r12.x86_64 #1 SMP Thu Mar 14 04:12:23 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
