### ISSUE TITLE
nfs pv storage capacity doesn't seem to work

### ISSUE THREAD

**Issue by zzuchen** [kubernetes/kubernetes#124159]
### What happened?

I creat a nfs pv, the capacity was set 10Mi, and then I create a pvc, the resourcerequest was also set 10Mi. But when I mount the pvc to the pod, I write 11Mi of data to the mounted nfs volume and can write successfully, the capacity limit of pv and pvc does not seem to work. Also, when I use the df -h command in pod, the size of the mounted volume displayed is the same as the size of nfs itself, which is 25Gi instead of 10Mi.What might be the cause of the error？

### What did you expect to happen?

1.An error occurred writing 11 MB data to the mounted volume.
2.when I use the df -h command in pod, the size of the mounted volume should be 10Mi.

### How can we reproduce it (as minimally and precisely as possible)?

1. create a nfs pv of 10Mi.
2. create a pvc of 10Mi.
3. moute the pvc to the pod.
4. write 11Mi of data to the mounted nfs volume.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Selvamraju007** [comment]
Here are some potential causes and troubleshooting steps:

Misconfigured NFS Server: Ensure that the NFS server is properly configured to enforce storage limits. Check the NFS server's configuration and permissions to ensure it restricts access based on the configured storage limits.

Misconfigured PV/PVC: Double-check the configuration of your PV and PVC to ensure that the capacity settings are correctly applied. Make sure that the PV's capacity is set to 10Mi and that the PVC requests exactly 10Mi.

Storage Quotas: If you're using Kubernetes on a cloud provider, there might be storage quotas or limitations imposed at the cloud provider level. Check if there are any quotas or limitations that could be affecting your storage usage.

Debugging: You can use tools like kubectl describe pv and kubectl describe pvc to inspect the PV and PVC configurations for any discrepancies. Additionally, check the logs of your NFS server and Kubernetes components (such as kube-controller-manager, kube-scheduler, etc.) for any errors or warnings related to storage provisioning and usage.

**Comment by carlory** [comment]
It's not a bug. It requires your nfs backend to support this limitation when you create a volume.

**Comment by zzuchen** [comment]
> It requires your nfs backend to support this limitation when you create a volume.

May I ask what settings need to be enabled for NFS backend to support this limitation?

**Comment by carlory** [comment]
It depends on your storage vendor and the corresponding driver you are using. The NFS server does not support the limit of volume size. However, some storage vendors may provide NFS protocol and the underlying storage system can limit the volume size.

**Comment by xing-yang** [comment]
This works as expected.

**Comment by carlory** [comment]
/close

As @xing-yang said, it's not a bug.
