### ISSUE TITLE
release blocking job ci-kubernetes-e2e-gci-gce-scalability-1-30 needs branch in perf-tests

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#124119]
### What happened?

Standing up a new job for k8s 1.30 release needs a new branch `release-1.30` in https://github.com/kubernetes/perf-tests.git repo

```
$ PWD=/home/prow/go/src/k8s.io/perf-tests  git fetch --filter=blob:none https://github.com/kubernetes/perf-tests.git release-1.30 (runtime: 1m5.58005565s)
fatal: couldn't find remote ref release-1.30
# Error: exit status 128
```

### What did you expect to happen?

CI job to be green

### How can we reproduce it (as minimally and precisely as possible)?

We already have a CI job - https://testgrid.k8s.io/sig-release-1.30-blocking#gce-cos-1.30-scalability-100&width=20

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
cc @kubernetes/release-engineering

**Comment by dims** [comment]
secondary issue ... we probably need to cleanup / add more folks to maintain perf-tests 

https://github.com/kubernetes/org/blob/e546cb7a6040e413c10c9c132ca67d651f4be272/config/kubernetes/org.yaml#L1612-L1629

**Comment by shyamjvs** [comment]
Just created the branch from tip of master - https://github.com/kubernetes/perf-tests/tree/release-1.30.

@dims is that good enough or do we need to update any dependencies etc?

**Comment by dims** [comment]
kicked off a run - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-1-30/1774837914048401408

**Comment by dims** [comment]
We are green!! https://testgrid.k8s.io/sig-release-1.30-blocking#gce-cos-1.30-scalability-100&width=20

/close
