### ISSUE TITLE
Read flags from environment variables

### ISSUE THREAD

**Issue by bcwaldon** [kubernetes/kubernetes#12418]
In order to simplify configuration of the Kubernetes components, each component should parse its own flags from the constructed environment, setting its flags based on the variables it finds. This will simplify configuration of Kubernetes components under complex init systems such as systemd, where it is a common pattern to overlay several files on one another to allow both the operating system vendors, the packagers and the end-users to jointly override the configuration options for a given service.

github.com/coreos/pkg/flagutil#SetFlagsFromEnv [0] provides an example of the code needed to achieve this, and the corresponding tests demonstrate its usage [1]. The code walks through each flag in a given flagset and parses a corresponding value from the environment prefixed with a configurable string.

As for a practical example, the kubelet could be vendored into an operating system like this, setting the default bind address to 127.0.0.1:

```
# /usr/lib64/systemd/system/kubelet.service
[Service]
Environment= KUBELET_ADDRESS=127.0.0.1
ExecStart= /usr/bin/kubelet
```

Then an end-user deploying a cluster could override the value to make the kubelet routable:

```
#/etc/systemd/system/kubelet.service.d/20-address.conf
[Service]
Environment= KUBELET_ADDRESS=0.0.0.0
```

One alternative here would be to initialize a KUBELET_OPTS env var, but that pushes more complexity onto the user and doesn't allow a clean way to selectively override a single flag. Another option would be to maintain a custom set of environment variables, but that pushes a lot of complexity onto the OS vendor and packager, forcing them to chance new flags exposed by the Kubernetes components over time.

[0] https://github.com/coreos/pkg/blob/master/flagutil/env.go#L16
[1] https://github.com/coreos/pkg/blob/master/flagutil/env_test.go#L9

**Comment by ecnahc515** [comment]
This would really be as easy as using one of the following options in spf13/cobra:

https://github.com/spf13/viper#working-with-environment-variables

**Comment by bgrant0607** [comment]
We're moving away from flags for configuration: #12245

**Comment by roberthbailey** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/12245
