### ISSUE TITLE
The setting "internalTrafficPolicy: Local" leads to an additional 1 second delay

### ISSUE THREAD

**Issue by jimsoft1000** [kubernetes/kubernetes#124166]
### What happened?

In Kubernetes version 1.26.4, modifying the service parameter "internalTrafficPolicy: Local" results in a 1-second delay when accessing pod applications through the service.However, in Kubernetes version 1.25.5, it functions normally.

Kubernetes 1.26.4
![1712136070710](https://github.com/kubernetes/kubernetes/assets/74498996/fd7f0d69-cf00-4728-9e98-83aeea1f7009)

Kubernetes 1.25.5
![1712136118708](https://github.com/kubernetes/kubernetes/assets/74498996/a9219bae-c289-4d9f-a7a7-cf2f29d4b3af)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

### Kubernetes version

<details>

```console
$ kubectl version
Kubernetes 1.26.4
Kubernetes 1.25.5
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig network


> In Kubernetes version 1.26.4, modifying the service parameter "internalTrafficPolicy: Local" results in a 1-second delay when accessing pod applications through the service.However, in Kubernetes version 1.25.5, it functions normally.

1.25 and 1.26 are out of support and cannot be patched any more.
is the problem also happening in 1.27 and newer?

**Comment by danwinship** [comment]
Are you using kube-proxy? iptables mode?
What network plugin?
Where are you running `ab` from? (pod, node, outside the cluster?)

**Comment by thockin** [comment]
@jimsoft1000 any answers to the open questions?

**Comment by aojea** [comment]
/close

no answer for one month
