### ISSUE TITLE
[Flaking Test] Integration transformation.transformation timeout 10m

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#124106]
### Which jobs are flaking?

- ci-kubernetes-integration-master

### Which tests are flaking?

- TestKMSv2Healthz https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1773469857552011264
- TestSecretsShouldBeTransformed https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1773515912264028160

### Since when has it been flaking?

since 03-28

https://storage.googleapis.com/k8s-triage/index.html?test=transformation found no failure.

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

```
panic: test timed out after 10m0s
running tests:
	TestKMSv2Healthz (2m42s)
```

```
panic: test timed out after 10m0s
running tests:
	TestSecretsShouldBeTransformed (6s)
```

### Anything else we need to know?

k8s.io/kubernetes/test/integration/controlplane/transformation.TestKMSv2Healthz(0xc003b464e0)
	/home/prow/go/src/k8s.io/kubernetes/test/integration/controlplane/transformation/kmsv2_transformation_test.go:893 +0x2f3

### Relevant SIG(s)

/sig testing auth
/cc @ritazh @aramase

**Comment by aramase** [comment]
This is not a failure with `TestKMSv2Healthz` or `TestSecretsShouldBeTransformed` but rather an overall timeout.

Looking at the history for integration job, `test/integration/controlplane/transformation` runs for ~ 9m. In these 2 instances, it took a little longer and timed out after the 10m timeout.

I'm going to see if we can speed up the tests, so we aren't close to the test job timeout.

**Comment by enj** [comment]
/unassign enj kushalShukla-web
/assign aramase

Anish is already working on this.

**Comment by neoaggelos** [comment]
Hi @aramase, I'm here representing the Release Signal team for Kubernetes 1.30. This is marked as in progress but I do not see any activity for the past week, is this on your radar?

**Comment by aramase** [comment]
> Hi @aramase, I'm here representing the Release Signal team for Kubernetes 1.30. This is marked as in progress but I do not see any activity for the past week, is this on your radar?

@neoaggelos Yes, I'm working on it now! Given this is flake because of test timeout, do you consider this a blocker for 1.30?

**Comment by neoaggelos** [comment]
Thanks! No, I would not consider it a blocker, but would be great to have some sort of fix before 1.30.0

**Comment by enj** [comment]
/reopen

Per https://github.com/kubernetes/kubernetes/pull/124492#issue-2259745129

**Comment by wendy-ha18** [comment]
Hey @aramase , just want to let you know the `k8s.io/kubernetes/test/integration/controlplane/transformation.transformation` test currently failed again on master-blocking with the same error messages as above.
- Triage [link](https://storage.googleapis.com/k8s-triage/index.html?test=transformation.transformation)
- Testgrid: https://testgrid.k8s.io/sig-release-master-blocking#integration-master
- Prow: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1805633433561468928

**Comment by drewhagen** [comment]
The release cycle for 1.32 starts today. Since this is still open, I will carry it over to the latest milestone.

I'm curious if we can reduce the amount of flakes we are tracking.
@enj Is there anything we can do to move #126398 forward?
Thanks!
