### ISSUE TITLE
PriorityClass

### ISSUE THREAD

**Issue by noor-muradi** [kubernetes/kubernetes#124183]
### What happened?

I am trying to create a custom high priority class for my critical apps, there are two existing system PCs with values above 2000000000, as I want to create PC with priority lower than system critical and higher than default, I need to give it value higher than existing PCs if I am not wrong, but the K8s does not allow me to create PC with value higher than existing system critical PCs.  

```
$ k get pc
NAME                      VALUE        GLOBAL-DEFAULT   AGE
system-cluster-critical   2000000000   false            134d
system-node-critical      2000001000   false            134d
$ k apply -f priorityclass.yaml
The PriorityClass "custom-high-priority" is invalid: value: Forbidden: maximum allowed value of a user defined priority is 1000000000
```

### What did you expect to happen?

Create custom pc lower than system critical

### How can we reproduce it (as minimally and precisely as possible)?

kubectl apply -f - <<EOF
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: custom-high-priority
preemptionPolicy: PreemptLowerPriority
value: 2000002000
EOF

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass

>> A PriorityClass object can have any 32-bit integer value smaller than or equal to 1 billion. This means that the range of values for a PriorityClass object is from -2147483648 to 1000000000 inclusive. Larger numbers are reserved for built-in PriorityClasses that represent critical system Pods. A cluster admin should create one PriorityClass object for each such mapping that they want.

> value: 2000002000

max value is 1000000000

> I want to create PC with priority lower than system critical and higher than default

that's not possible.
you can use one of the system- classes or create one with value <= 1000000000

/kind support
/remove-kind bug
/sig scheduling

**Comment by neolit123** [comment]
sig-scheduling please close if there is no actionable feature request here.
