### ISSUE TITLE
[Flaking Test] [sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator capz-windows-1.30

### ISSUE THREAD

**Issue by zelenushechka** [kubernetes/kubernetes#124138]
### Which jobs are flaking?

https://testgrid.k8s.io/sig-release-1.30-informing#capz-windows-1.30

### Which tests are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows-1-30/1774690917182083072

### Since when has it been flaking?

30.03

### Reason for failure (if possible)

could not find group version resource for dynamic client and wardle/flunders (discovery error: unable to retrieve the complete list of server APIs)
  [FAIL] [sig-api-machinery] Aggregator [It] Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance] [sig-api-machinery, Conformance]

### Relevant SIG(s)

/sig api machinery

**Comment by pacoxu** [comment]
dup with https://github.com/kubernetes/kubernetes/issues/119582 ?

**Comment by alexzielenski** [comment]
/cc @alexzielenski @Jefftree 
Possibly a race condition waiting for discovery
/triage accepted

**Comment by neolit123** [comment]
> dup with #119582 ?

yes, let's keep https://github.com/kubernetes/kubernetes/issues/119582
@alexzielenski please comment there if you haven't already.

/close
