### ISSUE TITLE
Import cycle while generating configuration with applyconfig-gen

### ISSUE THREAD

**Issue by mtrqq** [kubernetes/kubernetes#124192]
### What happened?

`applyconfig-gen` code generator creates import cycle in case of multi-token group names (e.g. resource.io).

### What did you expect to happen?

It should generate configuration files with valid go syntax.

### How can we reproduce it (as minimally and precisely as possible)?

Checkout https://github.com/mtrqq/applygen-cycle-repro/tree/main for detailed reproduction. 

Generally the scenario should look like this - create a custom resource API with 1 resource referencing another one and name which includes as least 1 dot (like resource.io). Run `applyconfig-gen` on this configuration, as the result - we are getting import cycle in one of the configuration files

### Kubernetes version

https://github.com/kubernetes/kubernetes/commit/d9c54f69d4bb7ae1bb655e1a2a50297d615025b5

OR

https://github.com/kubernetes/code-generator/commit/670586590c4574bdb99793d8373d8e4431ee30db

### Cloud provider

NONE

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alexzielenski** [comment]
/cc @jpbetz 
since you have context, does #124193 solve this, or more work is needed?
/triage accepted

**Comment by mtrqq** [comment]
@alexzielenski https://github.com/kubernetes/kubernetes/pull/124193 solves the issue I've, tested inside reproduction repo, we may close this one

**Comment by alexzielenski** [comment]
thanks @mtrqq 
/close
