### ISSUE TITLE
Make maxAllowableNUMANodes in the kubelet's TopologyManager configurable

### ISSUE THREAD

**Issue by klueska** [kubernetes/kubernetes#124144]
### What would you like to be added?

Add a config option to the `kubelet` that allows us to configure the value of `maxAllowableNUMANodes` in the TopologyManager:
https://github.com/kubernetes/kubernetes/blob/79c61d5f0305c566b642be978b1e4837870db257/pkg/kubelet/cm/topologymanager/topology_manager.go#L40

### Why is this needed?

The current hard-coded value of 8 was added as a stop-gap 4 years ago, with a plan to improve the topology manager to remove the state explosion that occurs when trying to enumerate the possible NUMA affinities and generating their hints (which unfortunately never happened).

The long term solution should be to refactor this code to avoid the state explosion altogether. In the meantime, a configurable option should be sufficient to allow users to increase the limit when appropriate.

**Comment by ffromani** [comment]
/triage accepted
/priority important-longterm

Note: adding kubelet options/flags will require API review

**Comment by cyclinder** [comment]
I want to work on this, I will be assigning this to myself, let me know if you have any questions.

/assign
