### ISSUE TITLE
update-go-workspace.sh doesn't support for MacOS

### ISSUE THREAD

**Issue by cyclinder** [kubernetes/kubernetes#124162]
### What happened?

```
make update
Running in silent mode, run with SILENT=false if you want to see script logs.
Running in short-circuit mode; run with FORCE_ALL=true to force all scripts to run.
Running update-go-workspace
dirname: illegal option -- z
usage: dirname path
```

### What did you expect to happen?

`make update` can run on MacOS

### How can we reproduce it (as minimally and precisely as possible)?

Run `make-update` on the MacOS

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
master

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
@cyclinder are you able to send PR fix?

**Comment by liggitt** [comment]
hmm... I'm running it on macos and it works fine... macos is missing a fair number of standard utilities so it's pretty normal to have to install them with something like `brew install coreutils`

**Comment by BenTheElder** [comment]
> so it's pretty normal to have to install them with something like [brew install coreutils](https://formulae.brew.sh/formula/coreutils)

we usually have an explicit check and warn though, e.g. some scripts require gnu-sed and detect for that and instruct installing it

/assign

**Comment by codinja1188** [comment]
> > so it's pretty normal to have to install them with something like [brew install coreutils](https://formulae.brew.sh/formula/coreutils)
> 
> we usually have an explicit check and warn though, e.g. some scripts require gnu-sed and detect for that and instruct installing it
> 
> /assign

Can I assign it ?

**Comment by BenTheElder** [comment]
> followed the below steps
>
> $brew install coreutils.

right, the issue is not handling when the user does not have coreutils.

I think this was already fixed? https://github.com/kubernetes/kubernetes/commit/56da06b6dd93208915177dd904da231178a39aea

@cyclinder what version are you testing?

**Comment by cyclinder** [comment]
> I think this was already fixed?

yes, I just noticed that this has been fixed, I forgot to update from the upstearm master to my local branch. sorry :(

Now let me close it.  thanks all!

/close
