### ISSUE TITLE
Comments in kubectl examples should use bash comments, not Go comments

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#12426]
For example:
```
 // Partially update a node using strategic merge patch
 kubectl patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}'
```

It should be:
```
 # Partially update a node using strategic merge patch
 kubectl patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}'
```

**Comment by apeeyush** [comment]
Hi! I would love to work on this one and send a PR as I am still working on getting familiar with the codebase (and hoping to make more meaningful contribution later).

Other than `pkg/kubectl`, the bash comments are also present in docs (`docs/user-guide/kubectl` and `docs/man/man1`). I was wondering if we need to change the comment style from `//` to `#` at all 3 locations or if we are using some automated doc generator that would pick the changes from `pkg/kubectl` directly?

**Comment by bgrant0607** [comment]
Thanks, @apeeyush. If you modify pkg/kubectl and then run hack/run-gendocs.sh, that should update the documentation appropriately.
