### ISSUE TITLE
invalid bearer token, service account token has been invalidated

### ISSUE THREAD

**Issue by tutorguai** [kubernetes/kubernetes#124204]
### What happened?

My K8s cluster kube apiserver has a large number of invalid bearer tokens, and the service account token has been invalidated
Phenomenon:
1. All are concentrated on one kube apiserver node
2. I did not find any functional damage in the cluster, including related business Pods
![image](https://github.com/kubernetes/kubernetes/assets/20591674/791b6289-8fec-4c19-a9d8-55794ff19dc2)

### What did you expect to happen?

How do I know where this part of the request comes from and how do I handle it

### How can we reproduce it (as minimally and precisely as possible)?

no

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:26Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
Linux 5.4.86-1.el7.elrepo.x86_64 #1 SMP Tue Dec 29 10:39:46 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
</details>

### Install tools

<details>
kubeasz
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd github.com/containerd/containerd v1.6.19
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by stlaz** [comment]
This does not appear to be an issue in Kubernetes.
Please try asking on the support channels

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

Also, please note that kube 1.25 is no longer supported.

/kind support
/close
