### ISSUE TITLE
Minor:  # TODO: Remove this package completely and from this list

### ISSUE THREAD

**Issue by see-quick** [kubernetes/kubernetes#124295]
### What would you like to be added?

I have found out that in the `verify-api-groups.sh` there is  a `TODO` i.e.,
```bash
packages_without_install=(
	"k8s.io/kubernetes/pkg/apis/abac"
	"k8s.io/kubernetes/pkg/apis/admission"
	"k8s.io/kubernetes/pkg/apis/apidiscovery"
	"k8s.io/kubernetes/pkg/apis/componentconfig" # TODO: Remove this package completely and from this list
)
```

It seems like a good first issue.  WDYT?

### Why is this needed?

To remove a `TODO` in `verify-api-groups.sh`.
```[tasklist]
### Tasks
```

**Comment by kushalShukla-web** [comment]
Hey @see-quick I would like to solve this issue ,looks beginner friendly!!

**Comment by kushalShukla-web** [comment]
https://github.com/kubernetes/kubernetes/pull/124299

**Comment by BenTheElder** [comment]
context: https://github.com/kubernetes/kubernetes/pull/67090/files#r208702776
/triage accepted

**Comment by see-quick** [comment]
As this PR [1] has been merged there, we can close this.

[1] - https://github.com/kubernetes/kubernetes/pull/124299
