### ISSUE TITLE
Potential conflict of apiserver_storage_size_bytes label (cluster) with Prometheus HA pair dedup logic

### ISSUE THREAD

**Issue by jeromeinsf** [kubernetes/kubernetes#124277]
Hi,

I stumbled upon https://kubernetes.io/docs/reference/instrumentation/metrics/#list-of-alpha-kubernetes-metrics

> **apiserver_storage_size_bytes**
> Size of the storage database file physically allocated in bytes.
> **Stability Level**:ALPHA
> **Type**: Custom
> **Labels**:cluster
> 

Using `cluster` as label sounds intuitive and valid , but ... I believe this has the potential for unexpected consequences for k8s users using Prometheus HA pair deduplication logic in remote storage, for which the default labels are `cluster` and `__replica__`, where `cluster` does not necessarily refers to the k8 cluster.  See:
https://cortexmetrics.io/docs/guides/ha-pair-handling/
https://grafana.com/docs/mimir/latest/configure/configure-high-availability-deduplication/#how-to-configure-prometheus
https://grafana.com/docs/grafana-cloud/send-data/metrics/metrics-prometheus/#sending-data-from-multiple-high-availability-prometheus-instances
https://docs.aws.amazon.com/prometheus/latest/userguide/Send-high-availability-data.html
https://github.com/timescale/promscale/blob/master/docs/high-availability/prometheus-HA.md

Could a different label be considered before marking this metric [stable](https://github.com/kubernetes/kubernetes/pull/123342)?

**Comment by dims** [comment]
@logicalhan @rexagod @dashpole @dgrisonnet Looks like we went from ALPHA to STABLE directly as well ... in https://github.com/kubernetes/kubernetes/pull/123342

**Comment by jeromeinsf** [comment]
I see other metrics use these labels ` apiserver_id_hash` , `endpoint`
Could they be used instead?
Alternatively, proposing `cluster_name` or `clusterName` (seems like both convention exist)

**Comment by dgrisonnet** [comment]
This `cluster` is referring to etcd and not the apiserver, so the meaning is a bit different than the other metrics.

I see that @logicalhan suggested using `etcd_cluster_name` instead of `cluster` on the initial PR (https://github.com/kubernetes/kubernetes/pull/119437#issuecomment-1642190961), but I don't know why the change wasn't made.

cc @serathius since he chose the new semantic

**Comment by dims** [comment]
i like the `etcd_cluster_name` :)

**Comment by serathius** [comment]
Name `etcd_cluster_name` will not work due to two reasons:
* name of the implies "storage" not "etcd".
* Values are not names of cluster.

Values are as follow, default cluster is called "etcd-0". Resource overrides will increment the number "etcd-1" for the first override, "etcd-2" to the second.

**Comment by jeromeinsf** [comment]
Is this some kind of `etcd_id` then?

**Comment by dims** [comment]
or `storage_cluster_id`?

**Comment by dims** [comment]
slack link: https://kubernetes.slack.com/archives/C20HH14P7/p1712857525115589
