### ISSUE TITLE
Optional image validation in kubectl

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#12428]
Users find out late if they specify an invalid image, which contributes to a poor experience and is expensive for the system. #4121

We could add an option to kubectl to verify the image exists. It won't necessarily work for all images (e.g., private images).

Podex has some code to get image metadata, but it targets the old registry API:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/podex/podex.go

**Comment by surajssd** [comment]
@bgrant0607 @kargakis is anyone working on this? If no-one is working can I take up this one?

**Comment by bgrant0607** [comment]
@surajssd I don't think anyone is working on this, but there are some tricky issues to sort out, like where to get credentials for private registries, and there are higher-priority issues to tackle, such as bug fixing, testing, etc. Reach out to the kubernetes-sig-cli googlegroup if you're looking for areas to contribute to in kubectl

**Comment by surajssd** [comment]
@bgrant0607 oh ok, thanks for the info.

**Comment by bgrant0607** [comment]
This is not feasible
