### ISSUE TITLE
rename mergo module in clientcmd

### ISSUE THREAD

**Issue by tessapham** [kubernetes/kubernetes#124279]
### What would you like to be added?

Module `github.com/imdario/mergo` has been renamed as `dario.cat/mergo` and should be updated in `kubernetes/client-go/clientcmd`.

### Why is this needed?

It's causing warnings when we run `go mod tidy` in repos that call `client-go/clientcmd`.

**Comment by neolit123** [comment]
> Module github.com/imdario/mergo has been renamed as dario.cat/mergo and should be updated in kubernetes/client-go/clientcmd.

/sig api-machinery

**Comment by dims** [comment]
xref: https://github.com/kubernetes-sigs/kustomize/pull/5044

**Comment by dims** [comment]
some stuff already discussed like:
https://github.com/kubernetes/kubernetes/issues/107499#issuecomment-1938831712

**Comment by dims** [comment]
we dealt with this in https://github.com/kubernetes/kubernetes/pull/126764

/close
