### ISSUE TITLE
StartError (exit code 128) when pod tries to mount configmap that is being changed at same time

### ISSUE THREAD

**Issue by utkarsh079** [kubernetes/kubernetes#124308]
### What happened?

This is happening when deploying a pod with argo workflow and there is another job running which is editing the configmap
The workflow failed with following error 
`
StartError (exit code 128): failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/f22aa0b7-afdc-497c-beb3-ccb394e8428d/volume-subpaths/config/wait/9" to rootfs at "/mainctrfs/my.py": mount /var/lib/kubelet/pods/f22aa0b7-afdc-497c-beb3-ccb394e8428d/volume-subpaths/my-py/wait/9:/mainctrfs/my.py (via /proc/self/fd/6), flags: 0x5001, data: context="system_u:object_r:data_t:s0:c923,c1020": no such file or directory: unknown
`

### What did you expect to happen?

I expected the pod to come up successfully with whatever version of configmap is available 

### How can we reproduce it (as minimally and precisely as possible)?

This is little hard to reproduce, but to reproduce:
1. Run a script or job to replace/overwrite a configmap
2. at the same time try to create a pod which is mounting data from configmap with subpath

### Kubernetes version

client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.8-gke.1067004

### Cloud provider

<details>
GKE
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

Related Issues:
https://github.com/argoproj/argo-workflows/issues/11983

**Comment by dims** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by tooptoop4** [comment]
🐞
