### ISSUE TITLE
Set container logs to an "admin" GID other than root to make life easier for users and logging/o11y implementers

### ISSUE THREAD

**Issue by matthewmodestino** [kubernetes/kubernetes#124349]
Still have customers adopting Kubernetes and having the discussion about why logging daemonsets need user 0.

By now, is there no adopted way to do what we'd do in nix days, and add the logging agents to a admin group that can access Kubelet logs on disk - `/var/log/pods`

Has this been documented and solved in the last few years? Would make a lot of folks lives easier!

Even a documented security profile that explains to k8s admins, devs and compliance departments, why theres all these tools trying to "run as root". Would definitely help ISVs as well! 

Specifically talking about node level logging architectures: 
https://kubernetes.io/docs/concepts/cluster-administration/logging/

**Comment by kannon92** [comment]
https://github.com/kubernetes/kubernetes/issues/124228

Related issue.

**Comment by yong-jie-gong** [comment]
> Still have customers adopting Kubernetes and having the discussion about why logging daemonsets need user 0.
> 
> By now, is there no adopted way to do what we'd do in nix days, and add the logging agents to a admin group that can access Kubelet logs on disk - `/var/log/pods`
> 
> Has this been documented and solved in the last few years? Would make a lot of folks lives easier!
> 
> Even a documented security profile that explains to k8s admins, devs and compliance departments, why theres all these tools trying to "run as root". Would definitely help ISVs as well!
> 
> Specifically talking about node level logging architectures: https://kubernetes.io/docs/concepts/cluster-administration/logging/

currently, raw logs(*.log) under /var/logs/pods is generated by container runtime instead of kubelet. there is nothing kubelet can do.  archive logs (*.gz) is genrated by kubelet but is world-wide visible considerd as security issue.    which logs do you refer to,?

# ls -rlt /var/log/pods/*/**/*
-rw-r-----. 1 root root /var/log/pods/kube-system_apiserver-demo1.test.com_712b37831be464ccc2fb1553ef89aa91/apiserver/66.log
-rw-r--r--. 1 root root /var/log/pods/kube-system_coredns-cfngt_8a5bacf2-063b-4ffc-b86a-237b94a07246/coredns/18.log.20240329-044703.gz

**Comment by matthewmodestino** [comment]
I am referring to `/var/log/pods`. I am not personally concerned about the world readable archives.

Most logging vendor agents only read the live raw log, and yes, I understand the container engine generates them, but in service of the kubelet. Kubelet already exposes settings like rotation size (which are also super low defaults in production environments k8s runs in). 

The only issue we have is they are owned as root. Some setting should set it to root:adm or something, then us logging vendors dont need to go thru security friction every single time a new user adopts k8s and runs a logging daemonset.

Its way better than the hacky ways im seeing it done now. We as logging vendors shouldnt have to step on these perms out of band.

**Comment by ffatghub** [comment]
and... in 2025 still lot of discussions about why logging daemonsets need group 0... c'mon k8s leadership drives this thing!

I'd be VERY happy to be proved wrong in case I missed some new containerd/kubelet uid:gid parameters...

ciao
