### ISSUE TITLE
When Topology Aware Hints are disabled, kube-proxy shouldn't spam the logs

### ISSUE THREAD

**Issue by diranged** [kubernetes/kubernetes#124341]
### What happened?

We have a mix of smaller and larger clusters - and for our larger clusters it is critical that the [Topology Aware Routing](https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/) is used on some of our high volume services. it works great, and it's fallback mode is reasonable.

The problem is this line: https://github.com/kubernetes/kubernetes/blob/v1.28.9/pkg/proxy/topology.go#L168-L171

With this line in place, on a reasonably sized cluster, we emit **hundreds of millions** of these log messages daily:

```
I0416 21:50:58.359353       1 topology.go:169] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0416 21:50:58.360686       1 topology.go:169] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0416 21:50:58.360944       1 topology.go:169] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0416 21:50:58.503272       1 topology.go:169] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0416 21:50:58.504681       1 topology.go:169] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0416 21:50:58.505831       1 topology.go:169] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
```

A LogQL query shows that on one cluster, we had over **1.2 billion log events** from this message:
![image](https://github.com/kubernetes/kubernetes/assets/768067/489c9ce6-223d-44ca-b649-69d57c639f92)

Here's an hour of the data:
![image](https://github.com/kubernetes/kubernetes/assets/768067/621fa43b-f7c6-4b0a-a8cd-6a6e11b6bba6)

### What did you expect to happen?

I understand that its useful to tell people that the zone aware routing isn't working - but doing it in log messages seems less than useful. I don't know anyone who operates clusters and monitors these log messages for errors, but rather would use metrics to alert on such a behavior.

I expect that the Kubernetes Service will report that Topology Aware Routing is or is not working (which it does) via the `kubectl describe` command - and that's it. Other than that, I expect `kube-proxy` to consider this as some kind of a debug message and not emit it as an `info` level message.

### How can we reproduce it (as minimally and precisely as possible)?

Create a service with `service.kubernetes.io/topology-mode: auto` in the annotations, and only put up one or two pods.. then start sending traffic to the service. Check logs.

### Anything else we need to know?

We're going to drop these messages with Promtail filtering ... but we really don't want them at all because it honestly takes time up on the hosts to write the messages to local disk, it also makes the `kubectl logs kube-proxy-...` command nearly useless, and it's just overall a waste of space I think.

### Kubernetes version

<details>

```console
% kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7-eks-b9c9ed7
```

</details>

### Cloud provider

<details>
AWS EKS 1.28
</details>

### OS version

AWS [Bottlerocket 1.19.2](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.19.2)

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mengjiao-liu** [comment]
/sig network

Someone has encountered the same problem and increased the log level to 2 in PR https://github.com/kubernetes/kubernetes/pull/123322. This change will be included in 1.30. You can avoid this by waiting 2 days for the 1.30 version to be updated to 1.30 after it is released. Then as long as the log level is less than 2 this problem can be avoided.

**Comment by diranged** [comment]
> /sig network
> 
> Someone has encountered the same problem and increased the log verbosity to 2 in PR #123322. This change will be included in Kubernetes version 1.30. You can wait 1 day for [the 1.30 version to be released](https://www.kubernetes.dev/resources/release/). After version 1.30 is released, you can upgrade the cluster to version 1.30, then as long as the log verbosity is less than 2 this problem can be avoided.

Any chance we can see this back-ported to 1.28 and 1.29? It seems like a relatively safe thing to do, and 1.30 is going to take a while to get upgraded to (especially because we use EKS, which of course is a little bit delayed on the release cycle).

**Comment by aojea** [comment]
> Any chance we can see this back-ported to 1.28 and 1.2

anyone willing to take on this ? 

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

/help
/triage accepted

**Comment by aojea** [comment]
/close

cherry picks were merged

**Comment by diranged** [comment]
Thanks everyone!

**Comment by dims** [comment]
I am stilling seeing this in our CI jobs also given `ServiceTrafficDistribution` is on by default it is gonna show up in all 1.31 clusters 

Take a look at this 2.17 GB monster from ec2/aws kops based CI job for scalability:
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1819265519883128832/artifacts/i-0028429514249e2f8/

Another example in a smaller job:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1819407205200302080/artifacts/bootstrap-e2e-minion-group-q92b/kube-proxy.log

**Comment by dims** [comment]
cc @aojea @danwinship

**Comment by gauravkghildiyal** [comment]
@dims Can we close this given https://github.com/kubernetes/kubernetes/pull/126519 merged?

**Comment by dims** [comment]
/close

yes, thanks @gauravkghildiyal
