### ISSUE TITLE
Add mtime to ObjectMeta

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#12430]
`ObjectMeta` already stores the creation and deletion timestamps; it should store last modified time as well.  Splitting off from #12324.

**Comment by pmorie** [comment]
@ncdc @derekwaynecarr

**Comment by smarterclayton** [comment]
What defines last modification time?  spec?  status?  If you set modification time you'll need to handle ensuring the content on GuaranteedUpdate and other CAS operations either updates the body to match the time or not check based on contents for CAS which is a weaker guarantee (in the event the db is rolled back you can accidentally overwrite others changes).

We should ask whether etcd could set this for us in the raft log

**Comment by pmorie** [comment]
@smarterclayton I would expect modification time to be the last modification time of the spec.  I would definitely prefer to have the underlying datastore give us this than have to maintain it in the code.

**Comment by karlkfi** [comment]
In the case on #12324 we need the last modified time of the status. So I added it as a field of Status. But I could see wanting to know the last time the spec was changed too. However, I would expect that to be under Spec. For a LastUpdatedTime in the ObjectMeta I assume it would mean the last object write, regardless of what changed.

**Comment by bgrant0607** [comment]
In the next-gen APIs (#8190), we should consider splitting spec and status into entirely separate resources.

However, as for modification time of the spec: Using actual time is usually the wrong approach. See generation/observedGeneration as implemented for ReplicationController.

**Comment by smarterclayton** [comment]
If we introduce something like this, we have to handle "writes that change nothing" correctly.  As mentioned above that's not easy without support from etcd.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-feature-requests

**Comment by chenk008** [comment]
I need this feature too.It's useful for administer.

**Comment by lavalamp** [comment]
Serverside apply will effectively be adding this.

**Comment by pmorie** [comment]
I suspect a lot of use cases people have for this are solved by objectmeta generation, and am tempted to close this issue.

**Comment by lavalamp** [comment]
Serverside apply beta 2 has landed (in v1.18), it's on universally. Every change includes a timestamp in metadata now. I think this is fixed either way :)
