### ISSUE TITLE
Mandatorliy specify how the application handle disruptions in the pod spec.

### ISSUE THREAD

**Issue by sjindal94** [kubernetes/kubernetes#124390]
### What would you like to be added?

We can have the `associatedPdb` as a required property in the pod spec with value like `ignore` or existing pdb name.

### Why is this needed?

PDBs are important for high availability. But there's a tendency to ignore them. How many teams actually create PDBs? 
It feels like it is important to be aware of disruptions and disruptions handling everytime we create a pod.

**Comment by neolit123** [comment]
/remove-sig scheduling
/sig apps
(for PDB)
