### ISSUE TITLE
After restart Kubelet, node will become notReady in first kubelet update period.

### ISSUE THREAD

**Issue by AllenXu93** [kubernetes/kubernetes#124397]
### What happened?

After restart Kubelet, node will become notReady in first kubelet update period.

node condition is :
```
  - lastHeartbeatTime: "2024-04-19T06:40:55Z"
    lastTransitionTime: "2024-04-19T06:40:55Z"
    message: container runtime status check may not have completed yet
    reason: KubeletNotReady
    status: "False"
    type: Ready
```

in kubelet's logs:
```
I0419 14:40:55.510166 1902465 setters.go:577] "Node became not ready" node="mjq-k8stestarsenalwork-1" condition={Type:Ready Status:False LastHeartbeatTime:2024-04-19 14:40:55.510127183 +0800 CST m=+5.226928586 LastTransitionTime:2024-04-19 14:40:55.510127183 +0800 CST m=+5.226928586 Reason:KubeletNotReady Message:container runtime status check may not have completed yet}
```

when go in to next period (default 10s), node status resume to Ready.

### What did you expect to happen?

Restart Kubelet should not make node status change to notReady.

### How can we reproduce it (as minimally and precisely as possible)?

Restart Kubelet, and watch node status for second
```
watch -n 1 'kubectl get no <node-name>'
```

### Anything else we need to know?

The root case maybe here:
When kubelet start, it will start two go routine, one detect runtime status, one check node status and update to APIServer;
detect runtime status:

in `updateRuntimeUp` it will update `lastBaseRuntimeSync`:
https://github.com/kubernetes/kubernetes/blob/bf07ef3950d80256cb366b035712b6d60b8a3f4c/pkg/kubelet/kubelet.go#L2909

in `kl.runtimeState.runtimeErrors` it will check runtimeStatus include `lastBaseRuntimeSync`:

https://github.com/kubernetes/kubernetes/blob/bf07ef3950d80256cb366b035712b6d60b8a3f4c/pkg/kubelet/runtime.go#L108

`kl.runtimeState.runtimeErrors` is one of the notReady setter func:
https://github.com/kubernetes/kubernetes/blob/bf07ef3950d80256cb366b035712b6d60b8a3f4c/pkg/kubelet/kubelet_node_status.go#L748

So if nodestatus execute before `updateRuntimeUp`, kubelet will update a node status with notReady condition:
https://github.com/kubernetes/kubernetes/blob/bf07ef3950d80256cb366b035712b6d60b8a3f4c/pkg/kubelet/kubelet.go#L1635-L1641
In kubelet starting,  both `syncNodeStatus` go routine and `fastStatusUpdateOnce` will be called before `updateRuntimeUp`,  so the first node status is notReady.

### Kubernetes version

In our cluster is v1.22.17, but I belive it can reproduce in latest version.

<details>

```console
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:47:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:42:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console

# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
I can reproduce this issue in v1.30

When the container runtime is healthy, the kubelet should not report `KubeletNotReady` with the reason `runtime status check may not have completed yet`

We called `kl.updateRuntimeUp()` in the `fastStatusUpdateOnce` function to update the status of the container runtime, but we did not do this in `syncNodeStatus`, 
https://github.com/kubernetes/kubernetes/blob/37ca0377d542d9eb5b6a7ebac2093b8ec6fc9942/pkg/kubelet/kubelet_node_status.go#L467-L469

We only need to execute `kl.updateRuntimeUp()` function once before `fastStatusUpdateOnce` and `syncNodeStatus`, just like we did in the `fastStatusUpdateOnce` function, than this problem can be avoided.

But in https://github.com/kubernetes/kubernetes/issues/122338#issuecomment-1912243387, @aojea seems to have some different opinions...

**Comment by AllenXu93** [comment]
> I can reproduce this issue in v1.30
> 
> When the container runtime is healthy, the kubelet should not report `KubeletNotReady` with the reason `runtime status check may not have completed yet`
> 
> We called `kl.updateRuntimeUp()` in the `fastStatusUpdateOnce` function to update the status of the container runtime, but we did not do this in `syncNodeStatus`,
> 
> https://github.com/kubernetes/kubernetes/blob/37ca0377d542d9eb5b6a7ebac2093b8ec6fc9942/pkg/kubelet/kubelet_node_status.go#L467-L469
> 
> We only need to execute `kl.updateRuntimeUp()` function once before `fastStatusUpdateOnce` and `syncNodeStatus`, just like we did in the `fastStatusUpdateOnce` function, than this problem can be avoided.
> 
> But in [#122338 (comment)](https://github.com/kubernetes/kubernetes/issues/122338#issuecomment-1912243387), @aojea seems to have some different opinions...

yes, in my env, I modify kubelet code let it execute kl.updateRuntimeUp once before `syncNodeStatus ` the same way as you said and it worked. I can submit a PR later.

**Comment by aojea** [comment]
I may be missing something but what happens if something has changed that caused the kubelet to not be ready ... imagine, the Network plugin is not working ... during the initial period until the check changes the state pods will be scheduled on the node and will fail ....

I think that we are operating the assumption that this is a restart and during that time nothing changed, but is this a safe assumption or can we guarantee somehow that nothing has changed that could impact the node readiness state?

**Comment by AllenXu93** [comment]
> I may be missing something but what happens if something has changed that caused the kubelet to not be ready ... imagine, the Network plugin is not working ... during the initial period until the check changes the state pods will be scheduled on the node and will fail ....
> 
> I think that we are operating the assumption that this is a restart and during that time nothing changed, but is this a safe assumption or can we guarantee somehow that nothing has changed that could impact the node readiness state?


In this issue, what I found is that nothing has changed, every time I restart kubelet, node will become notReady only in first sync period, in next period it will be ready;   It's not an assumption.
`Network plugin not working` or other problem would not cause `container runtime status check may not have completed yet` error message, have not relationship with my case;

**Comment by aojea** [comment]
> But in [#122338 (comment)](https://github.com/kubernetes/kubernetes/issues/122338#issuecomment-1912243387), @aojea seems to have some different opinions...

ok, I misread this issue sorry, so it is not to blindly set the node to ready, is just to perform the runtime check before the other checks ... I think you both are right ... actually it seems that if `fastStatusUpdateOnce` wins the race then there is no problem, righ @HirazawaUi ?

**Comment by HirazawaUi** [comment]
> actually it seems that if `fastStatusUpdateOnce` wins the race then there is no problem, righ @HirazawaUi ?

Yes, but `fastStatusUpdateOnce` and `syncNodeStatus` run in different goroutines, so we cannot guarantee that `fastStatusUpdateOnce` will complete faster.

So it seems like a good choice to execute `updateRuntimeUp` before running `syncNodeStatus`, or do you have better suggestions?

**Comment by aojea** [comment]
```diff
diff --git a/pkg/kubelet/kubelet.go b/pkg/kubelet/kubelet.go
index af74a095628..cd8acc7fbf0 100644
--- a/pkg/kubelet/kubelet.go
+++ b/pkg/kubelet/kubelet.go
@@ -1626,23 +1626,27 @@ func (kl *Kubelet) Run(updates <-chan kubetypes.PodUpdate) {
        // Start volume manager
        go kl.volumeManager.Run(kl.sourcesReady, wait.NeverStop)
 
+       // Check the container runtime status.
+       // This has to run before kl.syncNodeStatus (https://issues.k8s.io/124397)
+       go wait.Until(kl.updateRuntimeUp, 5*time.Second, wait.NeverStop)
+
        if kl.kubeClient != nil {
                // Start two go-routines to update the status.
                //
-               // The first will report to the apiserver every nodeStatusUpdateFrequency and is aimed to provide regular status intervals,
-               // while the second is used to provide a more timely status update during initialization and runs an one-shot update to the apiserver
+               // The first will is used to provide a more timely status update during initialization and runs an one-shot update to the apiserver
                // once the node becomes ready, then exits afterwards.
+               go kl.fastStatusUpdateOnce()
+
+               // The second will report to the apiserver every nodeStatusUpdateFrequency and is aimed to provide regular status intervals,
                //
                // Introduce some small jittering to ensure that over time the requests won't start
                // accumulating at approximately the same time from the set of nodes due to priority and
                // fairness effect.
                go wait.JitterUntil(kl.syncNodeStatus, kl.nodeStatusUpdateFrequency, 0.04, true, wait.NeverStop)
-               go kl.fastStatusUpdateOnce()
 
                // start syncing lease
                go kl.nodeLeaseController.Run(context.Background())
        }
-       go wait.Until(kl.updateRuntimeUp, 5*time.Second, wait.NeverStop)
 
        // Set up iptables util rules
        if kl.makeIPTablesUtilChains {
```

**Comment by AllenXu93** [comment]
> > But in [#122338 (comment)](https://github.com/kubernetes/kubernetes/issues/122338#issuecomment-1912243387), @aojea seems to have some different opinions...
> 
> ok, I misread this issue sorry, so it is not to blindly set the node to ready, is just to perform the runtime check before the other checks ... I think you both are right ... actually it seems that if `fastStatusUpdateOnce` wins the race then there is no problem, righ @HirazawaUi ?

Yes, if `fastStatusUpdateOnce` execute very fast, may there is no problem, because in `fastStatusUpdateOnce` it will execute `updateRuntimeUp `. 
I have test in v1.28 (which code in fastStatusUpdateOnce almost same as 1.30 ) , it will not always reproduce, but still occurr some times.
In 1.22,  `fastStatusUpdateOnce` will sleep for about 100ms before everything,  it can be reproduced everytimes.

**Comment by aojea** [comment]
> Arranging the goroutines in order can solve our problems in most cases

it will execute first https://go.dev/play/p/752NWud709S

**Comment by HirazawaUi** [comment]
> moving `go wait.Until(kl.updateRuntimeUp, 5*time.Second, wait.NeverStop)` will execute first https://go.dev/play/p/752NWud709S

I think I must not have expressed clearly.
What I'm worried about is that under special circumstances, `updateRuntimeUp` calls the API of the container runtime and cannot return immediately (not sure if this situation really exists). Even if the `updateRuntimeUp` method is executed first, it will still complete later than `syncNodeStatus` :)

**Comment by AllenXu93** [comment]
> > Arranging the goroutines in order can solve our problems in most cases
> 
> moving `go wait.Until(kl.updateRuntimeUp, 5*time.Second, wait.NeverStop)` will execute first https://go.dev/play/p/752NWud709S

Add some detail:
in `updateRuntimeUp ` it call runtime api to check runtime status, then set `lastBaseRuntimeSync` variable .
https://github.com/kubernetes/kubernetes/blob/92270014e251674c799b9745ca7c8800be7979da/pkg/kubelet/kubelet.go#L2913

in `syncNodeStatus` , it will check `lastBaseRuntimeSync` variable, if `lastBaseRuntimeSync` is nil, this issue's problem will occurr.
https://github.com/kubernetes/kubernetes/blob/bf07ef3950d80256cb366b035712b6d60b8a3f4c/pkg/kubelet/kubelet_node_status.go#L748
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/runtime.go#L108

Even if `updateRuntimeUp ` goroutine call firstly, call container runtime check will still need some time, it can't guarantee that when `syncNodeStatus` firstly call, `lastBaseRuntimeSync` is setted.

**Comment by aojea** [comment]
are you suggesting to lock syncNodeStatus on updateRuntimeUp? 

I'm afraid of some corner cases we can hit ... if the container runtime does not return do we block forever?

**Comment by AllenXu93** [comment]
> are you suggesting to lock syncNodeStatus on updateRuntimeUp?
> 
> I'm afraid of some corner cases we can hit ... if the container runtime does not return do we block forever?

Container runtime API call have timeout.
https://github.com/kubernetes/kubernetes/blob/695a984f569bec2835bcb3ac8474cebefd020994/pkg/kubelet/cri/remote/remote_runtime.go#L621

**Comment by AnishShah** [comment]
Can you try this on a newer version? 1.22 is out of support and we have made changes to node readiness since.

/triage needs-information

**Comment by AllenXu93** [comment]
> Can you try this on a newer version? 1.22 is out of support and we have made changes to node readiness since.
> 
> /triage needs-information

I have tried in 1.28, it can reproduce,  @HirazawaUi  can reproduce in 1.30.
