### ISSUE TITLE
errors running update-codegen.sh

### ISSUE THREAD

**Issue by tessapham** [kubernetes/kubernetes#124391]
### What happened?
Initially, running `hack/update-codegen.sh` returned:
```
hack/verify-codegen.sh
+++ [0418 21:16:48] Generating protobufs for 69 targets
go: -mod may only be set to readonly or vendor when in workspace mode, but it is set to "mod"
	Remove the -mod flag to use the default readonly value,
	or set GOWORK=off to disable workspace mode.
```
so I set `export GOWORK=off` in [`kube::golang::setup_env()`](https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L590), which effectively disabled go workspace.

This fixed the error above, but led to a list of errors from `deepcopy-gen` even though my `kubernetes` repo is already under `$GOPATH/src/k8s.io`:
```
hack/verify-codegen.sh
+++ [0418 17:39:21] Generating protobufs for 69 targets
+++ [0418 17:40:04] Generating deepcopy code for 252 targets
F0418 17:40:09.204730   86904 main.go:107] Error: failed making a parser: error(s) in "./staging/src/k8s.io/api/admission/v1":
-: main module (k8s.io/kubernetes) does not contain package k8s.io/kubernetes/staging/src/k8s.io/api/admission/v1
error(s) in "./staging/src/k8s.io/api/admission/v1beta1":
-: main module (k8s.io/kubernetes) does not contain package k8s.io/kubernetes/staging/src/k8s.io/api/admission/v1beta1
error(s) in "./staging/src/k8s.io/api/admissionregistration/v1":
-: main module (k8s.io/kubernetes) does not contain package k8s.io/kubernetes/staging/src/k8s.io/api/admissionregistration/v1
error(s) in "./staging/src/k8s.io/api/admissionregistration/v1alpha1":
-: main module (k8s.io/kubernetes) does not contain package k8s.io/kubernetes/staging/src/k8s.io/api/admissionregistration/v1alpha1
...
```

### What did you expect to happen?

`hack/update-codegen.sh` should work.

### How can we reproduce it (as minimally and precisely as possible)?

* Change [this line](https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L590) to `export GOWORK=off` and temporarily commit it (or else script will complain dirty working dir).
* Run `hack/update-codegen.sh`.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.13
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tessapham** [comment]
I tried the other option which is to set `-mod` flag to `readonly` and update-codegen.sh worked. Submitted a PR to set this flag in the script.

**Comment by thockin** [comment]
Hi @tessapham - can you help me to reproduce this?  

What I see is:

```
$ git rev-parse HEAD
790d65b28d8058537e5b83428cf81f8be9c75e6c

$ make clean
+++ [0521 17:03:20] Verifying Prerequisites....

$ ./hack/verify-codegen.sh protobuf
go: downloading go1.22.3 (linux/amd64)
+++ [0521 17:04:25] Generating protobufs for 69 targets
+++ [0521 17:04:26] protoc 23.4 not found (can install with hack/install-protoc.sh); generating containerized...
+++ [0521 17:04:26] Verifying Prerequisites....
+++ [0521 17:04:29] Building Docker image kube-build:build-c02211e9dd-5-v1.31.0-go1.22.3-bullseye.0
```

Which is already farther than you seem to get.

Turning GOWORK=off is not going to end in happiness, we pretty much depend on it.  Something is different about your environment than mine - help me pin it down.  Can you sync to the same SHA, make clean and try `./hack/verify-codegen.sh protobuf`?

**Comment by wenjianhn** [comment]
> Are you setting -mod=mod, in particular?

I fixed the issue by deleting `GOFLAGS=-mod=mod` of ~/.config/go/env.
