### ISSUE TITLE
[Code Generator] Issue generating v1alpha2 APIs

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#124302]
I was trying to generate jobset CRD (and we have our API listed as v1alpha2).

I clone the jobset repo and run `make generate manifests`. 

I get a failure in `make openapi-gen` and I think its related to v1alpha2 name.

If I change the API to be v1alpha1 or v1beta1 I have no issue with generating the APIs.

Error I get:

```
kehannon@kehannon-thinkpadp1gen4i:~/Work/jobset$ make openapi-gen
/home/kehannon/Work/jobset/bin/openapi-gen --go-header-file hack/boilerplate.go.txt -i sigs.k8s.io/jobset/api/jobset/v1alpha2 -p sigs.k8s.io/jobset/api/jobset/v1alpha2 --alsologtostderr
2024/04/13 12:36:20 OpenAPI code generation error: Failed making a parser: unable to add directory "sigs.k8s.io/jobset/api/jobset/v1alpha2": No files for pkg "sigs.k8s.io/jobset/api/jobset/v1alpha2"
make: *** [Makefile:244: openapi-gen] Error 1
k
```

Now this may be an environment issue as I seem to be the only able to reproduce this but I am at a loss of debugging this.

I also realize that we should probably drop openapi-gen (as it is dropped in 1.30) but if I remove this command and add openapi-gen into the update-codegen script. I still get a similar issue.

**Comment by kannon92** [comment]
cc @thockin

**Comment by kannon92** [comment]
ref: https://github.com/kubernetes-sigs/jobset/issues/508

**Comment by pohly** [comment]
Do you have a branch which exhibits this problem?

**Comment by kannon92** [comment]
@pohly that was my attempt to get it working with v1alpha1 or v1beta1 (which works). I am actually failing on main of jobset.

**Comment by kannon92** [comment]
Not really sure what went wrong. I decided to give up on my golang environment (deleted cache, go environment) and redownloaded everything.

Once I did that I was back in action..
