### ISSUE TITLE
DeltaFIFO TransformFunc can result in a data race on re-sync

### ISSUE THREAD

**Issue by tpantelis** [kubernetes/kubernetes#124337]
We use a `TransformFunc` to nil out the `ManagedFields`:

```
func(obj interface{}) (interface{}, error) {
    resourceUtil.MustToMeta(obj).SetManagedFields(nil)
    return obj, nil
})
```

However on a re-sync, this results in a data race that was observed when running unit tests:

```
WARNING: DATA RACE
Write at 0x00c0006accc0 by goroutine 81:
  runtime.mapdelete_faststr()
      /usr/lib/golang/src/runtime/map_faststr.go:301 +0x0
  k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.RemoveNestedField()
      /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/apis/meta/v1/unstructured/helpers.go:274 +0x1e6
  k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).SetManagedFields()
      /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/apis/meta/v1/unstructured/unstructured.go:476 +0x87
  github.com/submariner-io/admiral/pkg/syncer.NewResourceSyncer.func3()
      /go/pkg/mod/github.com/submariner-io/admiral@v0.18.0-m2.0.20240415195632-6c525b3cb5e9/pkg/syncer/resource_syncer.go:260 +0x4c
  k8s.io/client-go/tools/cache.(*DeltaFIFO).queueActionLocked()
      /go/pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/delta_fifo.go:456 +0x101
  k8s.io/client-go/tools/cache.(*DeltaFIFO).syncKeyLocked()
      /go/pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/delta_fifo.go:746 +0x154
  k8s.io/client-go/tools/cache.(*DeltaFIFO).Resync()
      /go/pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/delta_fifo.go:717 +0x1b6
  k8s.io/client-go/tools/cache.(*Reflector).startResync()
      /go/pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:378 +0x351
  k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func2()
      /go/pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:356 +0x5d

Previous read at 0x00c0006accc0 by goroutine 82:
  runtime.mapaccess2_faststr()
      /usr/lib/golang/src/runtime/map_faststr.go:108 +0x0
  k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedFieldNoCopy()
      /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/apis/meta/v1/unstructured/helpers.go:61 +0x10f
  k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.nestedMapNoCopy()
      /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/apis/meta/v1/unstructured/helpers.go:195 +0x66
  k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedStringMap()
      /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/apis/meta/v1/unstructured/helpers.go:167 +0x6e
  k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetLabels()
      /go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/apis/meta/v1/unstructured/unstructured.go:400 +0x94
  github.com/submariner-io/admiral/pkg/syncer.getClusterIDLabel()
      /go/pkg/mod/github.com/submariner-io/admiral@v0.18.0-m2.0.20240415195632-6c525b3cb5e9/pkg/syncer/resource_syncer.go:681 +0x65
  github.com/submariner-io/admiral/pkg/syncer.(*resourceSyncer).shouldSync()
      /go/pkg/mod/github.com/submariner-io/admiral@v0.18.0-m2.0.20240415195632-6c525b3cb5e9/pkg/syncer/resource_syncer.go:647 +0x4d
  github.com/submariner-io/admiral/pkg/syncer.(*resourceSyncer).processNextWorkItem()
      /go/pkg/mod/github.com/submariner-io/admiral@v0.18.0-m2.0.20240415195632-6c525b3cb5e9/pkg/syncer/resource_syncer.go:448 +0x3ad
  github.com/submariner-io/admiral/pkg/syncer.(*resourceSyncer).processNextWorkItem-fm()
      <autogenerated>:1 +0x89
  github.com/submariner-io/admiral/pkg/workqueue.(*queueType).processNextWorkItem.func1()
      /go/pkg/mod/github.com/submariner-io/admiral@v0.18.0-m2.0.20240415195632-6c525b3cb5e9/pkg/workqueue/queue.go:103 +0x59
```

The read had occurred previously during a `ResourceEventHandler` callback.

On re-sync, the `DeltaFIFO` retrieves every object from the `knownObjects` cache,  invokes the transform function, and re-queues them.  However, the object instances are the same as those stored in the cache so mutating them outside the cache without lock protection is unsafe. It is documented that the "_TransformFunc sees the object before any other actor, and it is now safe to mutate the object in place instead of making a copy_" however this is not the case on a re-sync. The `DeltaFIFO` should make a copy of the objects retrieved from the cache store on a re-sync or perhaps elide the `TransformFunc` on a re-sync since the objects would already have been transformed.

As a workaround, I changed our `TransformFunc` to only nil the `ManagedFields` if not already nil but this is a latent bug that others will likely run into.

**Comment by liggitt** [comment]
> We use a TransformFunc to nil out the ManagedFields

kube-controller-manager and kube-scheduler do the same in 1.29+ and likely have the same issue

**Comment by linxiulei** [comment]
Looking into this. I may take time to come up with a proper fix. But would like to evaluate the risk for the current situation. Not entirely sure how delete and replace would be triggered in normal settings, but resync is fortunately low frequency as the default setting for resync period is between 12h and 24h for `kube-controller-manager` (--min-resync-period duration     Default: 12h0m0s, see [help](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/)) . As for `kube-scheduler` the resync function is [disabled](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/options/options.go#L304)

Just think out aloud, I read a thread discussion somewhere that resync was a mechanism in the past to prevent data inconsistency due to bugs but client-go has been mature these days, resync is no-longer needed in theory but for a safe guard. So maybe disabling resync is a reasonable fix if delete/replace can be fixed.

**Comment by wojtek-t** [comment]
You're mixing resync with relist - I believe relist is no longer needed.
Resync is actually used.

FWIW - I opened an initial version of the fix: https://github.com/kubernetes/kubernetes/pull/124344

**Comment by linxiulei** [comment]
I think it's resync. The thread I mentioned is https://groups.google.com/g/kubernetes-sig-api-machinery/c/PbSCXdLDno0
