### ISSUE TITLE
update load balancer e2e tests for legacy CloudProvider removal

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#124338]
Spun off from #122828.

Generic notes:
1. The "ESIPP" tests should be renamed to say "externalTrafficPolicy: Local" or something (AFAICT ESIPP stands for "External Source IP Preservation" but we don't use that acronym anywhere else),
2. Should revisit the use of `[Slow]`, which may not make sense for some of these. In particular, all of the jobs where we are intentionally, explicitly running LB tests (eg, all the ones with cloud-provider-kind) should probably run all of these tests.

----

These tests are GCE-specific and can be deleted:
- `Firewall rule control plane should not expose well-known ports`
  This makes various assertions about what ports in a cluster are accessible from outside the cluster. The specific details here are GCE-specific and this test has nothing to do with sig-network anyway. (Even if we wanted a non-GCE-specific version of this, it would belong to sig-security, not sig-network.)
- `Firewall rule [Slow] [Serial] should create valid firewall rules for LoadBalancer type service`
  Tests GCE-specific details of how cloud LBs are configured
- `Loadbalancing: L7 GCE [Slow] [Feature:NEG] .*`
  Tests GCE-specific "Network Endpoint Group" feature
- `LoadBalancers should be able to create an internal type load balancer [Slow]`
  Tests GCE-specific "internal load balancers"
- `Services GCE [Slow] should be able to create and tear down a standard-tier load balancer [Slow]`
  Tests GCE-specific network tiers feature

----

These tests are currently scheduled to be deleted because they have rules like `SkipUnlessProviderIs("gce", "aws", "azure")`, etc, but they need to be fixed to be "skip unless there is a cloud provider with LoadBalancer support" (cf #123714). (I guess we can probably just do "`[Feature:LoadBalancers]`"?) Although we will run them under cloud-provider-kind in our CI, the tests should also be runnable in other environments, so they should not make any provider-specific assumptions.

- `LoadBalancers should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on the same nodes`
- `LoadBalancers should not have connectivity disruption during rolling update with externalTrafficPolicy=Cluster [Slow]`
- `LoadBalancers should not have connectivity disruption during rolling update with externalTrafficPolicy=Local [Slow]`
- `LoadBalancers should be able to change the type and ports of a TCP service [Slow]`
  (includes a "bonus" GCE-specific test that can just be removed)
- `LoadBalancers should be able to change the type and ports of a UDP service [Slow]`
  (includes GCE-specific functionality but I think as with the TCP test that is a "bonus" test that can just be removed)
- `LoadBalancers should only allow access from service loadbalancer source ranges [Slow]`
- `LoadBalancers should be able to create LoadBalancer Service without NodePort and change it [Slow]`
- `LoadBalancers should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on different nodes`
- `LoadBalancers ESIPP [Slow] should work for type=LoadBalancer`
- `LoadBalancers ESIPP [Slow] should work for type=NodePort`
- `LoadBalancers ESIPP [Slow] should only target nodes with endpoints`
- `LoadBalancers ESIPP [Slow] should work from pods`
- `LoadBalancers ESIPP [Slow] should handle updates to ExternalTrafficPolicy field`
- `LoadBalancers should have session affinity work for LoadBalancer service with ESIPP on [Slow] [LinuxOnly]`
- `LoadBalancers should be able to switch session affinity for LoadBalancer service with ESIPP on [Slow] [LinuxOnly]`
- `LoadBalancers should have session affinity work for LoadBalancer service with ESIPP off [Slow] [LinuxOnly]`
- `LoadBalancers should be able to switch session affinity for LoadBalancer service with ESIPP off [Slow] [LinuxOnly]`

---

I'm not sure about these tests:

- `LoadBalancers should handle load balancer cleanup finalizer for service [Slow]`
  Not clear if the use of the `service.kubernetes.io/load-balancer-cleanup` finalizer on LB-type services is actually _required_ (as this test asserts) or merely expected
- `Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should conform to Ingress spec`
  Tests GCE-specific Ingress provider. This is our only test of "ingress actually works". (There is a separate non-provider-specific "the ingress _API_ works" test.) In theory we could write a cloud-provider-kind-specific ingress test, but do we want to? Does SIG Network need to provide anything to allow ingress providers to test for conformance? If so, what? Is Ingress testing something that the Gateway WG is better positioned to handle?

/sig network
/cc @aojea

**Comment by danwinship** [comment]
(If anyone disagrees with the judgements above let's argue it out.)

**Comment by aojea** [comment]
+1 to your assessment 

> * `LoadBalancers should handle load balancer cleanup finalizer for service [Slow]`
>   Not clear if the use of the `service.kubernetes.io/load-balancer-cleanup` finalizer on LB-type services is actually _required_ (as this test asserts) or merely expected

it tests the cloud-provider service controller logic

https://github.com/kubernetes/kubernetes/blob/0e39ca84dc0224edf6b399772d6f4072b4fe8b9b/staging/src/k8s.io/cloud-provider/service/helpers/helper.go#L44


> This is our only test of "ingress actually works". (There is a separate non-provider-specific "the ingress API works" test.) In theory we could write a cloud-provider-kind-specific ingress test, but do we want to? Does SIG Network need to provide anything to allow ingress providers to test for conformance? If so, what? Is Ingress testing something that the Gateway WG is better positioned to handle?

there were nginx-ingress tests that were removed https://github.com/kubernetes/kubernetes/pull/108598  and moved to its own repo  https://testgrid.k8s.io/sig-network-ingress-nginx , gateway API has its own conformance and nginx-ingress too

**Comment by BenTheElder** [comment]
This generally sounds reasonable to me.

Re: tests planned to be removed because they're not suitable for making generic and will stay GCP specific, I'd like to keep track of those outcomes so we can potentially move some of them out of tree versus not running anywhere.

https://github.com/kubernetes/kubernetes/issues/122828#issuecomment-2065367804

> Tests GCE-and-AWS-specific "internal load balancers"

cc @dims, when we have a test that is N+1 cloud providers subject to removal ... we should discuss options

**Comment by danwinship** [comment]
> > * `LoadBalancers should handle load balancer cleanup finalizer for service [Slow]`
> >   Not clear if the use of the `service.kubernetes.io/load-balancer-cleanup` finalizer on LB-type services is actually _required_ (as this test asserts) or merely expected
> 
> it tests the cloud-provider service controller logic

Right, the question is: are cloud providers _required_ to use `k8s.io/cloud-provider/controllers/service` and/or is the finalizer a mandatory element of the CloudProvider API even if they don't use `k8s.io/cloud-provider`?

**Comment by tosi3k** [comment]
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness fails consistently on some of the tests that are mentioned here since Apr 20th and alerts the [scalability oncall](https://go.k8s.io/oncall).

I see https://github.com/kubernetes/kubernetes/pull/124420 is opened but didn't receive much love for a week already.

Is more discussion needed here about what tests we want to remove?

We could also simply filter those tests out in a CI job config in the meantime.

CC @wojtek-t

**Comment by danwinship** [comment]
> I see #124420 is opened but didn't receive much love for a week already.

It's marked `hold` because we want thost tests to get moved somewhere gce-specific so we don't regress in coverage. Though, I guess, if they're already failing with the current state of k/k there's no real reason to keep them...

Looking at the testgrid output though, it doesn't really look like "some tests fail consistently since 4/20", it looks like "multiple tests have been failing at increasing rates for a while, several of which happen to have failed in every run since 4/20".
