### ISSUE TITLE
[Failing Test] `ci-kubernetes-e2e-gce-cos-k8sstable[23]-alphafeatures`

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#124331]
### Which jobs are failing?

- [ci-kubernetes-e2e-gce-cos-k8sstable2-alphafeatures](https://testgrid.k8s.io/sig-release-1.28-blocking#gce-cos-k8sstable2-alphafeatures&width=30)
- [ci-kubernetes-e2e-gce-cos-k8sstable3-alphafeatures](https://testgrid.k8s.io/sig-release-1.27-blocking#gce-cos-k8sstable3-alphafeatures&width=30)

### Which tests are failing?

The suite setup:

```
{  error during ./hack/e2e-internal/e2e-up.sh: exit status 2}
```

### Since when has it been failing?

For the full job history

### Anything else we need to know?

Refers to:
- https://github.com/kubernetes/sig-release/issues/2484
- https://github.com/kubernetes/sig-release/issues/2483

cc @releasemana

### Relevant SIG(s)

/sig testing
/sig release

**Comment by aojea** [comment]
Both jobs fails because of

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable2-alphafeatures/1796233893716692992/artifacts/test-a8a0b221b9-master/kubelet.log

> May 30 17:46:57.439479 test-a8a0b221b9-master kubelet[3061]: E0530 17:46:57.439472    3061 run.go:74] "command failed" err="failed to run Kubelet: failed to create kubelet: cloud provider \"gce\" was specified, but built-in cloud providers are disabled. Please set --cloud-provider=external and migrate to an external cloud provider"

Who owns these jobs, @BenTheElder do you know?

**Comment by BenTheElder** [comment]
I don't think any particular group is handling these :/

They benefit the project at large because they test the alpha features.

**Comment by BenTheElder** [comment]
cc @dims 
/sig cloud-provider

This seems like sig-cloud-provider changes breaking the CI, maybe we can get some help there.

Glancing at the config I don't know why this wouldn't be using the out of tree cloud provider for kube-up, but I haven't been as close to those changes as @aojea or @dims yet.

**Comment by aojea** [comment]
hmm, this is generated from here https://github.com/kubernetes/test-infra/blob/master/releng/test_config.yaml , I could not find where is the template used to generate those tests, but it seems hardcoded to provider=gce and has to change to be external

/sig release 
?

**Comment by BenTheElder** [comment]
From a run you can see the actual prow config used:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable3-alphafeatures/1796145055983996928 => [Prow Job Yaml](https://prow.k8s.io/prowjob?prowjob=0209e898-f39f-4b97-9f2a-e6dae6db1ba5)

**Comment by aojea** [comment]
> From a run you can see the actual prow config used: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable3-alphafeatures/1796145055983996928 => [Prow Job Yaml](https://prow.k8s.io/prowjob?prowjob=0209e898-f39f-4b97-9f2a-e6dae6db1ba5)

yeah, but those are generated from the releng scripts, we need to change the base templates to create those jobs with cloud provider external and regenerate the jobs

**Comment by dims** [comment]
cc @xmudrii

**Comment by saschagrunert** [comment]
@kubernetes/release-managers do we have to change https://github.com/kubernetes/test-infra/blob/a4f43f0f14feb4ec582db4c8b4c64ac6ca767b5d/releng/test_config.yaml#L215-L220 and then run something like `make -C releng prepare-release-branch`?

**Comment by xmudrii** [comment]
@saschagrunert I'll take a look and report back

**Comment by xmudrii** [comment]
Created https://github.com/kubernetes/test-infra/pull/32690 as a potential fix for this issue

**Comment by dims** [comment]
thanks Marko!! @xmudrii

**Comment by aojea** [comment]
> thanks Marko!! @xmudrii

+1
