### ISSUE TITLE
[flaky test] k8s.io/kubernetes/pkg/scheduler/framework/plugins: dynamicresources 

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#124379]
### Which jobs are flaking?

pull-kubernetes-unit
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124375/pull-kubernetes-unit/1780943837938585600

### Which tests are flaking?

k8s.io/kubernetes/pkg/scheduler/framework/plugins: dynamicresources 
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124375/pull-kubernetes-unit/1780943837938585600

### Since when has it been flaking?

unknown

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124375/pull-kubernetes-unit/1780943837938585600

### Reason for failure (if possible)

multiple failures in tests as seen in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124375/pull-kubernetes-unit/1780943837938585600

### Anything else we need to know?

n/a

### Relevant SIG(s)

/sig scheduling

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124383/pull-kubernetes-unit/1781099920288124928

**Comment by BenTheElder** [comment]
probably https://github.com/kubernetes/kubernetes/pull/123938?
cc @pohly

**Comment by pohly** [comment]
DeepCopy missing here:
```
k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources.stripObjects()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:1207 +0xb3
```
