### ISSUE TITLE
Some kube-proxy metrics must be labeled per IP family

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#124305]
kube-proxy has two loops, one per ip family, we need to be able to differentiate the metrics that depend on the IP family to avoid mixing results https://gist.github.com/aojea/f9ca1a51e2afd03621744c95bfdab5b8, as one IP family can take 10s and the other 0 (since there is no rule),

This is just going through the existing metrics and move to `metrics.NewHistogramVec(` with a label `family`, and then inside of the kube-proxy logic record the corresponding family

https://github.com/kubernetes/kubernetes/blob/cae35dba5a3060711a2a3f958537003bc74a59c0/pkg/proxy/metrics/metrics.go#L30-L40

/sig network
/help

**Comment by Devaansh-Kumar** [comment]
I would like to work on this issue
/assign

**Comment by aroradaman** [comment]
@aojea dup/child of https://github.com/kubernetes/kubernetes/issues/116486?

**Comment by aojea** [comment]
> @aojea dup/child of #116486?

/close

as dup 

Thanks Arora
