### ISSUE TITLE
Avoid breaking changes in public interfaces: use apidiff as presubmit for client-go staging repo

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#124380]
>          This change breaks the upgrade to 1.30 for every controller built on top of controller-runtime e.g. Flux https://github.com/fluxcd/pkg/pull/763. Hopefully the controller-runtime maintainers will do a release soon that deals with this breaking change.

> _Originally posted by @stefanprodan in https://github.com/kubernetes/kubernetes/pull/122069#discussion_r1570560522_
            

Ideally we should have a linter or some presubmit that detects this breakages and block the PR waiting for API review, it just have to add the label `kind/api-change`

/cc @liggitt

**Comment by dims** [comment]
@aojea already in progress xref: https://github.com/kubernetes/kubernetes/pull/124372

**Comment by dims** [comment]
@aojea Ack. we have `apidiff` in various repositories for example:
https://cs.k8s.io/?q=apidiff&i=nope&files=.*%5C.sh&excludeFiles=&repos=

**Comment by aojea** [comment]
> Reference

didn't know that event existed :) , so we just need to make it available, at least in the client-go repo , we can start with informative to see how it goes, WDYT?

**Comment by dims** [comment]
> WDYT?

yep!

**Comment by liggitt** [comment]
go APIs have always been out of scope for API review, we don't have the capacity to route everything that apidiff would flag as a go API change through that process

I guess I don't object to running it as informative, but I think *many* more PRs than you expect change a public signature, and will turn the job red, to the point where it will just be ignored

**Comment by pohly** [comment]
FWIW, I had a [PR for enabling apidiff](https://github.com/kubernetes/kubernetes/pull/122971) with the intention to add it as an optional, on-demand job.  Jordan raised the same concerns there, so I closed it.

**Comment by pohly** [comment]
"Optional, on-demand" might have worked in https://github.com/kubernetes/kubernetes/pull/122069#discussion_r1563097713 if the folks involved had known and remembered to run it.

The API break was caught during review, the scope of it was just underestimated. Perhaps seeing the apidiff output would have helped? :shrug:

**Comment by aojea** [comment]
> f the folks involved had known and remembered to run it.

can you reopen so we can make it "Optional, on-demand" , at least I will selfishly use it :)

**Comment by fedebongio** [comment]
Is there any pending action on this one or can we close it?
