### ISSUE TITLE
Multiple PTR records being returned for a Pod backed by multiple Services

### ISSUE THREAD

**Issue by adrianmoisey** [kubernetes/kubernetes#124418]
### What happened?

In the scenario where a Pod has multiple Services pointing at it, multiple PTR records are also created.

### What did you expect to happen?

A single PTR record to be created.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Deployment with at least 1 replica in it
2. Create a service that matches the labels of that Deployment
3. Create a second service that matches the labels of that Deployment
4. Query the PTR record for the pod's IP address

### Anything else we need to know?

This was discovered in trying to understand the behaviour in https://github.com/kubernetes/kubernetes/issues/124207
There is more context here: https://kubernetes.slack.com/archives/C09QYUH5W/p1713551070931899?thread_ts=1713088975.540039&cid=C09QYUH5W

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2```

</details>


### Cloud provider

<details>
Discovered using kind
Reproduced on GKE
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by adrianmoisey** [comment]
Depends on https://github.com/coredns/coredns/pull/6623

**Comment by thockin** [comment]
For bookkeeping I am going to close this, and let https://github.com/coredns/coredns/pull/6623 be the final word.  OK with that?

**Comment by adrianmoisey** [comment]
Works for me!
