### ISSUE TITLE
--hostname-override flag on kubelet is no longer used for Addresses.Hostname value in Kubernetes 1.29

### ISSUE THREAD

**Issue by bradbehle** [kubernetes/kubernetes#124453]
### What happened?

It looks like there was a change that first appeared in Kubernetes 1.29, where in 1.29 the `--hostname-override` flag on kubelet is no longer being used to populate the Node's Addresses.Hostname value.  Here is the relevant output from a `kubectl describe node` for a 1.28 cluster with `hostname-override=10.X.X.X`:

```
Addresses:
  InternalIP:  10.X.X.X
  ExternalIP:  52.X.X.X
  Hostname:    10.X.X.X
```

And here's the output from a 1.29 cluster with the same configuration:

```
Addresses:
  InternalIP:  10.X.X.X
  ExternalIP:  52.X.X.X
```

Here is the full `kubelet` list of parameters in case that is helpful:

`/usr/local/bin/kubelet --config=/etc/kubernetes/kubelet-config.yaml --root-dir=/var/data/kubelet --node-labels=privateVLAN=XXXXXXX,publicVLAN=XXXXXXX --cloud-provider=external --v=2 --kubeconfig=/etc/kubernetes/kubelet-kubeconfig --hostname-override=10.X.X.X --enable-controller-attach-detach=false --version=v1.28.9+IKS --runtime-cgroups=/podruntime/runtime`

This is from an IBM Cloud Kubernetes Service 1.28 and 1.29 cluster.  We do not think there was any cloud-configuration-manager or any other related change that would cause this difference.  Is it possible it is a side effect of https://github.com/kubernetes/kubernetes/pull/121028 ?

### What did you expect to happen?

I expected the behavior to be consistent between Kubernetes releases, since I didn't find any reference to this change in https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md

### How can we reproduce it (as minimally and precisely as possible)?

Create an IBM Cloud Kubernetes Service cluster at 1.28 and 1.29 and see the difference

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4+IKS
$ 
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
root@test-coiu89n20065io30q4n0-bpvg1713759-default-00000251:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@test-coiu89n20065io30q4n0-bpvg1713759-default-00000251:/# uname -a
Linux test-coiu89n20065io30q4n0-bpvg1713759-default-00000251 5.4.0-176-generic #196-Ubuntu SMP Fri Mar 22 16:46:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
root@test-coiu89n20065io30q4n0-bpvg1713759-default-00000251:/# 

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/assign @danwinship 
/unassign 

Thanks

**Comment by bridgetkromhout** [comment]
@danwinship Do the sig cloud provider folks need to help here? We did make external cloud providers the default as of 1.29, which may have uncovered this. Let us know!

**Comment by danwinship** [comment]
No, it's just a dumb kubelet startup bug. Well, not dumb, but easy to fix.

**Comment by aojea** [comment]
It seems the problem is that once kubelet sets the hostname the cloud controller manager does not override it


https://github.com/kubernetes/kubernetes/blob/da479a82ebb6d4117b69f2c78364c81a513ad511/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L373-L388

so maybe the right behavior is only override it if is actually overridden ?

**Comment by aojea** [comment]
@bradbehle we are discussing if the fix should be backported or not https://github.com/kubernetes/kubernetes/pull/124554

It seems you are relaying on the node.status.address with type Hostname and this not clearly documented

https://github.com/kubernetes/kubernetes/pull/126099#discussion_r1677991212

We also find out recently that the behavior of this address will be overriden if the external cloud provider configures it https://github.com/kubernetes/kubernetes/pull/125809

@liggitt @danwinship if the ` IBM Cloud Kubernetes` external cloud provider returns the hostname , then this problem will be solved without need to backport

**Comment by danwinship** [comment]
> It seems you are relaying on the node.status.address with type Hostname and this not clearly documented
> 
> [#126099 (comment)](https://github.com/kubernetes/kubernetes/pull/126099#discussion_r1677991212)

(Well, to clarify my comments there: it's not well-defined _between clouds and node linux distros_. If you know what cloud and distro you are on, then the behavior might be consistent and usable, but that still makes for a lousy kubernetes API.)

Anyway, the question here is: was this actually breaking anything major, or did you just happen to notice this and think "that's weird"?

(Also, if anyone else was broken by this bug, feel free to chime in; trying to figure out what to do about backporting this, because the original fix for this bug ended up introducing another bug, and the fix for _that_ bug is maybe not backport-able...)

**Comment by bradbehle** [comment]
So far I have only heard from a single customer (who was using IBM Cloud Kubernetes Service) who had something in their cluster relying on cluster node's Address.Hostname value, and so when they updated to 1.29 they were broken.  I believe they just modified their code to get this "Hostname" value (which was really the node IP) from somewhere else.

So, to answer the question, it is somewhere between the "I noticed it and thought 'that's weird'" option and the "it broke something major" option.   We have this documented in our 1.29 release notes for IBM Cloud Kubernetes Service, so other customers will have fair warning before updating.  So at this point I don't consider fixing this in 1.29 as essential.
