### ISSUE TITLE
Remove `MinDomainsInPodTopologySpread` feature gate

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#124460]
ref: https://github.com/kubernetes/enhancements/issues/3022

This feature is already GA, but we haven't removed the feature gate yet on purpose.
We can remove this feature gate after a few releases, probably 1.32 -ish.

> Yes, we do keep the feature gate for a couple of releases, so that someone that a manifest that has MyFeature=true continues to run. But we ignore the feature gate in code.
It is common that we forget to remove the gate.
https://github.com/kubernetes/enhancements/pull/4407#issuecomment-1927256512

/kind cleanup
/assign
/sig scheduling

**Comment by googs1025** [comment]
@sanposhiho 
Will you handle this issue? If not, I will take it.
But this issue should be handled after v1.31 is released?

**Comment by sanposhiho** [comment]
@googs1025 It should be handled after v1.31.

**Comment by sanposhiho** [comment]
/close

https://github.com/kubernetes/kubernetes/pull/126863
