### ISSUE TITLE
K8s error message: unexpected error getting claim reference: selfLink was empty, can't make reference

### ISSUE THREAD

**Issue by smallemployees** [kubernetes/kubernetes#124495]
### What happened?

I installed nfs provisioner and reported an error

### What did you expect to happen?

How can I solve this problem

### How can we reproduce it (as minimally and precisely as possible)?

k8s v1.28.2
nfs-client-provisioner:latest

### Kubernetes version

<details>
v1.28.2
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
nfs-client-provisioner:latest
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> I installed nfs provisioner and reported an error

nfs-client-provisioner is not maintained by kubernetes.
maybe that's where the issue should be logged.
https://github.com/vbouchaud/nfs-client-provisioner

also we don't provide support on github.
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
