### ISSUE TITLE
namespace creation is broken or not documented correctly

### ISSUE THREAD

**Issue by abonas** [kubernetes/kubernetes#12446]
I've tried to create a namespace on the latest master.
Used the example from the below link as is:
https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/design/namespaces.md

I get :
"status": "Failure",
  "message": "the object provided is unrecognized (must be of type Namespace): couldn't get version/kind; json parse error: invalid character '}' looking for beginning of object key string",
  "reason": "BadRequest",
  "code": 400

Looking also at  swagger, there is no clear way of understanding what input is requested in the request body for creation:
http://kubernetes.io/third_party/swagger-ui/#!/api%2Fv1/createNamespacedNamespace
all fields are marked as optional, some fields clearly don't belong in creation flow such as deletion timestamp, resource version, etc.

**Comment by nikhiljindal** [comment]
I cant seem to find this in our documentation but does passing yaml instead of json help?
I think API server only support yaml input.

**Comment by thockin** [comment]
I think we ts the opposite.  We support jsonyaml is converted to jso
client-side

**Comment by nikhiljindal** [comment]
aah yes you are right.
APIServer supports json. It does not support yaml: https://github.com/GoogleCloudPlatform/kubernetes/issues/1004

**Comment by abonas** [comment]
@nikhiljindal @thockin this is using json and passing it to the REST api via http (or https)
REST api typically (and here as well) doesn't accept yaml afaik.

**Comment by timothysc** [comment]
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
@abonas - can you paste what you are passing to create so I know which part of the design document you are trying to use?  I suspect the design doc is out of synch because its using hanging commas in the JSON, so I can take a pass to fix that.

Either way, you should look to follow the examples here:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/admin/namespaces

**Comment by nikhiljindal** [comment]
I just tried creating a namespace using the json in that guide (https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/design/namespaces.md#example-openshift-origin-managing-a-kubernetes-namespace) and it worked fine after removing the hanging commas.

Here is my json:
```
 {
   "apiVersion":"v1",
   "kind": "Namespace",
   "metadata": {
     "name": "development"
   },
   "spec": {
     "finalizers": ["openshift.com/origin", "kubernetes"]
   },
   "status": {                                                                                                                                                                                                   
     "phase": "Active"
   },
   "labels": {
     "name": "development"
   }
 }
```
And this is the command I ran:
```
curl -X POST -d @/tmp/ns.json http://localhost:8080/api/v1/namespaces/
```

**Comment by derekwaynecarr** [comment]
Will update doc tomorrow.  Thanks

**Comment by abonas** [comment]
thanks guys! sorry for missing some of your questions, timezone difference...

**Comment by bgrant0607** [comment]
Labels are in the wrong place.
