### ISSUE TITLE
Service DNS not working across pods from different minions on AWS from kube-up install

### ISSUE THREAD

**Issue by joshm1** [kubernetes/kubernetes#12449]
Simply using the following environment variables I'm able to get a master and 2 minions up and running on AWS. The problem is that service DNS only resolves if a pod is on the same minion as kube-dns.

To demonstrate, I launch the cluster from release 1.0.1 using the following command, which creates the VPC, subnet, master instance, ec2 launch group, scaling group, etc.

```
export KUBE_OS_DISTRIBUTION=vivid
export KUBE_AWS_ZONE=us-east-1e
export NUM_MINIONS=2
export MINION_SIZE=m3.large
export AWS_S3_REGION=us-east-1
export AWS_S3_BUCKET=mycompany-kubernetes
export INSTANCE_PREFIX=k8s
export AWS_SSH_KEY=~/.ssh/id_rsa
export KUBERNETES_PROVIDER=aws
./cluster/kube-up.sh
```

Here we see dns works for `kubernetes` when pod and kube-dns are on the same node, but not if on different pods:

```
$ kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                                 READY     STATUS    RESTARTS   AGE       NODE
default       busybox-1mwjm                                        1/1       Running   0          18m       ip-172-20-0-181.ec2.internal
default       busybox-crlux                                        1/1       Running   0          3m        ip-172-20-0-61.ec2.internal
kube-system   kube-dns-v8-cf8ka                                    4/4       Running   0          14m       ip-172-20-0-181.ec2.internal

$ kubectl exec busybox-1mwjm -- nslookup kubernetes
Server:    10.0.0.10
Address 1: 10.0.0.10 ip-10-0-0-10.ec2.internal

Name:      kubernetes

Address 1: 10.0.0.1 ip-10-0-0-1.ec2.internal

$ kubectl exec busybox-crlux -- nslookup kubernetes
Server:    10.0.0.10
Address 1: 10.0.0.10 ip-10-0-0-10.ec2.internal

nslookup: can't resolve 'kubernetes'
error: Error executing remote command: Error executing command in container: Error executing in Docker Container: 1
```

I deleted the kube-dns pod to get it to relaunches on the other minion.  Now we see that it works on the pod that previous failed and fails on the pod that previously worked.

```
$ kubectl delete pod kube-dns-v8-cf8ka --namespace=kube-system
pods/kube-dns-v8-cf8ka

$ kubectl exec busybox-crlux -- nslookup kubernetes
Server:    10.0.0.10
Address 1: 10.0.0.10 ip-10-0-0-10.ec2.internal

Name:      kubernetes
Address 1: 10.0.0.1 ip-10-0-0-1.ec2.internal

$ kubectl exec busybox-1mwjm -- nslookup kubernetes
nslookup: can't resolve 'kubernetes'
Server:    10.0.0.10
Address 1: 10.0.0.10 ip-10-0-0-10.ec2.internal

error: Error executing remote command: Error executing command in container: Error executing in Docker Container: 1
```

Below are details for the kube-dns service:

```
$ kubectl describe service kube-dns --namespace=kube-system
Name:			kube-dns
Namespace:		kube-system
Labels:			k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS
Selector:		k8s-app=kube-dns
Type:			ClusterIP
IP:			10.0.0.10
Port:			dns	53/UDP
Endpoints:		10.244.1.5:53
Port:			dns-tcp	53/TCP
Endpoints:		10.244.1.5:53
Session Affinity:	None
No events.
```

I'm not sure if it's related, but also, none of the cluster-info services load when I try to load them in the browser through the master IP. They all return both when loading https://MASTER_IP/api/v1/proxy/namespaces/kube-system/services/kube-ui/ and on http://localhost:8001 when using `kubectl proxy`

```
Error: 'dial tcp 10.244.0.10:8080: i/o timeout'
Trying to reach: 'http://10.244.0.10:8080/'
```

**Comment by a-robinson** [comment]
It looks like something's wrong with service routing in your cluster in general. @justinsb, have you seen anything like this before?

**Comment by justinsb** [comment]
I have seen this, I believe this happens when we fail to set up routes in the routing table.  This is done on the master now, I believe by kube-controller-manager.

@joshm1 can you please check the logs on the master, in particular /var/log/kube-controller-manager.log (I think that is the right log).

And also ideally check your routing table in the AWS console: the routing table for the cluster VPC should have your instances in it, with each of the instances mapped with a /24 CIDR.

**Comment by joshm1** [comment]
Thanks @a-robinson @justinsb! Looks like routing tables were the issue. There were 2 routing tables for my VPC, which was throwing the error "found multiple matching AWS route tables for AWS cluster". https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/aws/aws_routes.go#L43

![image](https://cloud.githubusercontent.com/assets/182629/9171648/67d9e0d6-3f3b-11e5-81f2-225559476b3d.png)

I set the 2nd one to main and deleted the first.  That didn't do anything. The issue wasn't actually fixed until I looked at all of my route tables from all VPCs and I actually had one in a former VPC with the KubernetesCluster tag :angry: 

To see if I could reproduce the error with a new cluster I tried to teardown the old one via kube-down.sh and re-ran `kube-up`.  The problem didn't reproduce so I think it was the Route Table from a previous VPC. 

It's embarrassing how long I spent on this. Thanks for pointing me in the right direction so quickly!

**Comment by joshm1** [comment]
@a-robinson @justinsb

So even though I got this working with Ubuntu Vivid minions, I created a cluster with coreos minions and I'm getting the same problem. Except this time the Route Table was updated, but loading the UI in my browser responds:

```
Error: 'dial tcp 172.17.0.7:8080: no route to host'
Trying to reach: 'http://172.17.0.7:8080/'
```

This is different, because before it was trying to read `10.244.0.10` which was added to the route table. I don't see any reference to 172.17.0.0/24 as the CIDR in my Route Table or subnet.  CoreOS is really the OS I prefer to use, I had only tried Vivid because of previous CoreOS issues (which is probably what I'm reporting now).

Service DNS also isn't working as described above.

**Comment by thockin** [comment]
172 addresses typically indicate that Docker is using node-private IPs
rather than the subnets we want assigned to each node (though some installs
do use 172, most do not).

**Comment by moosilauke18** [comment]
I seem to have the same issue with Coreos.  I'm not using the 172 addresses, rather addresses in the `10` range.  Usually what I end up doing is terminating the problem node and hoping it fixes the problem, which it sometimes does.

**Comment by givia** [comment]
I had same problem in my bare metal coreos cluster. Sometimes docker main service (not early-docker) starts before flanneld and docker can't use flannel network. I solved the problem by adding this code in my cloud-config:
```
    - name: docker.service
      command: start
      drop-ins:
        - name: 50-flanneld.conf
          content: |
            [Unit]
            After=flanneld.service
            Requires=flanneld.service
```
