### ISSUE TITLE
Make `maxUnavailable` more useful for StatefulSets with `OrderedReady` Pod management

### ISSUE THREAD

**Issue by tzachshabtay** [kubernetes/kubernetes#124408]
### What would you like to be added?

We're using `maxUnavailable` in a stateful set with an `OrderedReady` policy. A few issues/enhancements we would like:
- It's terminating the pods in parallel but the whole initialization process (`ContainerCreating`/`Init`/`PodInitializing`) is still happening one by one, can that be done in parallel too?
- When scaling down (and up) `maxUnavailable` is completely ignored, the pods are still terminated (and initialized) one by one, can that happen on parallel too?

### Why is this needed?

We have a stateful set with 32 replicas, deploying and scaling takes a long time, by using `maxUnavailable` we have been able to improve performance by a lot (from over 30 minutes to under 5 minutes), we believe that if the initialization will also be made in parallel we could bring it down to under 1 minute.
As for scaling down, because it's currently one by one, it still takes us ~30 minutes, and we would like to make it as fast as deploying.

**Comment by Sheikh-Abubaker** [comment]
@tzachshabtay I would like to work on this.

**Comment by nayihz** [comment]
> * the whole initialization process (`ContainerCreating`/`Init`/`PodInitializing`) is still happening one by one, can that be done in parallel too?

Maybe `spec.podManagementPolicy = Parallel` could do that.

**Comment by sftim** [comment]
/retitle Make `maxUnavailable` more useful for StatefulSets with `OrderedReady` Pod management

**Comment by tzachshabtay** [comment]
@nayihz ah thanks, so with "parallel" this works as expected. I guess it's unclear to me now what's the use-case for having "OrderedReady" terminating in parallel but still initializing one by one? Or in the broader sense, before we had `maxUnavailable`, I kind of saw "OrderedReady" as `maxUnavailable=1` and "Parallel" as `maxUnavailable=all replicas`, is there a reason (other than compatibility) to still have the pod management policy field at all and not just use `maxUnavailable`?
