### ISSUE TITLE
[Failing Test] multi jobs failing in sig-release-1.29/1.28-blocking

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#124438]
### Which jobs are failing?

kube.Up

### Which tests are failing?

- gce-cos-k8sstable1-alphafeatures: FAILING
- gce-cos-k8sstable1-default: FAILING
- gce-cos-k8sstable1-ingress: FAILING
- gce-cos-k8sstable1-reboot: FAILING
- gce-device-plugin-gpu-1.29: FAILING
- gce-cos-1.29-scalability-100: FAILING

### Since when has it been failing?

04-15

### Testgrid link

https://testgrid.k8s.io/sig-release-1.29-blocking#gce-cos-k8sstable1-default
https://testgrid.k8s.io/sig-release-1.28-blocking#gce-cos-k8sstable1-default

### Reason for failure (if possible)

```

{  error during ./hack/e2e-internal/e2e-up.sh: exit status 1}
```

> specifically, section 10.2.3 (“Information Requirements”).
> Creating firewall...
> ERROR: (gcloud.compute.instances.create) Must specify either [--image] or [--image-family] when specifying [--image-project] flag.
> 

### Anything else we need to know?

NA

### Relevant SIG(s)

/sig release k8s-infra

**Comment by aojea** [comment]
They fail with this message

```
Creating firewall...
ERROR: (gcloud.compute.instances.create) Must specify either [--image] or [--image-family] when specifying [--image-project] flag.
Failed to create master instance due to non-retryable error
..Created [https://www.googleapis.com/compute/v1/projects/k8s-infra-e2e-boskos-047/global/firewalls/test-359c739436-minion-all].
done.
NAME                        NETWORK          DIRECTION  PRIORITY  ALLOW                     DENY  DISABLED
test-359c739436-minion-all  test-359c739436  INGRESS    1000      tcp,udp,icmp,esp,ah,sctp        False
[0;31mFailed to create firewall rule.[0m
```

was there any change on kubetest or kubekins that could cause this failure?

cc: @BenTheElder @ameukam

**Comment by aojea** [comment]
The errors seems to be coming from https://github.com/kubernetes/kubernetes/blob/9c9a0e3ba57cb103d651e77f1b9283673c4d0cd7/cluster/gce/gci/master-helper.sh#L174-L188

**Comment by saschagrunert** [comment]
cc @kubernetes/release-managers

**Comment by BenTheElder** [comment]
most recent PRs: https://github.com/kubernetes/test-infra/pull/32425, https://github.com/kubernetes/test-infra/pull/32450

**Comment by aojea** [comment]
> most recent PRs: [kubernetes/test-infra#32425](https://github.com/kubernetes/test-infra/pull/32425), [kubernetes/test-infra#32450](https://github.com/kubernetes/test-infra/pull/32450)

it seems to affect only 1.29 branch

**Comment by tosi3k** [comment]
> it seems to affect only 1.29 branch

1.28 is also affected by this problem: https://testgrid.k8s.io/sig-release-1.28-blocking.

> maybe a gcloud update just from image rebuilds?

I don't think so - for `ci-kubernetes-e2e-gci-gce-scalability-1-29`, the [first failing CI job run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-1-29/1780204707642347520) and [the last green CI job run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-1-29/1780023344880422912) used the same `kubekins-e2e` image (tag: `v20240409-13cd3acf7e-1.29`).

**Comment by saschagrunert** [comment]
Can we add more verbosity around this section?
https://github.com/kubernetes/kubernetes/blob/9c9a0e3ba57cb103d651e77f1b9283673c4d0cd7/cluster/gce/gci/master-helper.sh#L174-L188

If the error is
```
Must specify either [--image] or [--image-family] when specifying [--image-project] flag.
```
Then it would be great to understand what the field values are compared 1.30 to the failing 1.29 job. Can we test this in the CI env?

**Comment by dims** [comment]
@pacoxu @saschagrunert https://github.com/kubernetes/kubernetes/issues/124478#issuecomment-2072317348

**Comment by SergeyKanzhelev** [comment]
> Ideally we want this mapping https://github.com/kubernetes/test-infra/tree/master/jobs/e2e_node/containerd/k8s-release-branches to match the mapping in cluster/gce. So the same family of COS is used for testing of a released version
> 
> @mauriciopoppe can you please send PRs similar to @dims's but different version per release branch?

Sorry, I didn't realize we bumper all releases to 109. This is not what I remembered and not very ideal as we want to keep the gke to OS mapping for longer time to minimize change for customers on what is tested upstream. Anyway, keeping it in mind, bumping to 109 looks good

**Comment by pacoxu** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/124485 and https://github.com/kubernetes/kubernetes/pull/124486.

CI looks greener today. 
/close
