### ISSUE TITLE
Proposal: Make pod log endpoint more useful

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#12447]
The Pod log endpoint on the apiserver and Kubelet was implemented as a simple wrapper around Docker logs.  It's intended to provide easy access for users and administrators to the logs of the currently running execution of a container in a pod.  If there is no running execution, it will show the last execution.  There are two flags supported:

* `?follow=true/false` instructs docker to leave the connection open and stream new changes until the container exits or the log connection is closed by the consumer
* `?previous=true/false` uses the previous execution of the container to display logs

When not following logs, the default Docker behavior of returning the entire log file is preserved (Docker `tail=all`).  We currently suppress the timestamp shown by Docker (because the logs may already contain timestamps).

## Problems today:

* A container may generate many megabytes of logs which must be transferred to the client every time the user runs 'logs'
* A container running for several days may generate periodic logs, but a user is only interested in the last few hours
* A user may wish to see when a log statement was generated, but not have added timestamps to their logs themselves

Types of containers and typical uses:

1. Run-once containers are typically used to run jobs - for most users, seeing the entire log of a completed job is useful, or watching the logs until their fail
2. Run-forever containers are usually used to run services - users typically:
  1. want to debug something that has happened recently, or watch for something that has already happened
  2. want to analyze their logs across a larger band of time by searching / scanning for particular behaviors

Finally, for existing systems there may be log aggregators that provide access to historical logs for a pod/container across multiple attempts or deep history.  It would be desirable in the future to be able to abstract access to deep logging in a way that clients can remain oblivious.

## Consuming use cases

* OpenShift is looking to expose log retrieval / scanning via its web console
* OpenShift is looking to integrate ElasticSearch so that it can be used for multi-tenant historical log retrieval, with a simple integration (via the existing log APIs) and then for all other queries via a secured proxy that imposes query restrictions to the elastic search api.

## Suggested changes

To better support clients that want to handle limiting the amount of bulk data they receive, target logging to specific areas of user interest, or more accurately represent the time a log line happened, we should expose a limited subset of the features Docker already supports for log retrieval to allow windowing of requests, without limiting the future ability of the system to be backed by an external log solution.

Minimize the impact to existing runtimes by choosing simple operations that can translate to systemd, Docker, or other local container log systems.

Non goals: 
* Do not build a full log query system
* Do not return structured logs

Consider exposing the following from the Kubelet and the pod logs api:

* `since=<relative or absolute timestamp>` - allow a client to indicate the range of time within which to retrieve logs.  Serves as a useful bound when retrieving historical logs (or, in combination with another flag, to retrieve ranges of logs)
* `tail=<limit>` - starting from the end of the log, return only the X most recent entries. Is valuable for reducing the impact of trying to fetch the logs. Leave default "all" as per Docker
* `timestampn=true/false` - whether to prepend each log entry (line?) with a timestamp
* (potential) `limit=<bytes or lines>` - only return log entries (lines?) until this many bytes or lines have been received, then terminate the connection

**Comment by smarterclayton** [comment]
@jwforres @jcantril @sosiouxme as per discussions, @satnam6502 fyi

**Comment by sosiouxme** [comment]
+1 captures what was discussed.

**Comment by erictune** [comment]
fyi @mr-salty

**Comment by satnam6502** [comment]
@a-robinson @jimmidyson

**Comment by jimmidyson** [comment]
There are 2 problems with streaming with this setup, both related to Elasticsearch.

1. Persisting logs will have to be batched (bulk API) for performance.
2. Elasticsearch does not support streaming results so will have to be implemented with polling.

Both of these will give a bit of a clunky UX. Streaming will be jerky at best. I don't consider streaming from Elasticsearch storage to be a good option for these requirements, although it is an excellent option for structured logs (a non-goal).

If we're not considering structured logs in this then perhaps we need to revisit storage options, although I do think that would be missing a trick for other benefits, like being able to extract data from your logs for continuous improvement, over & above just troubleshooting why something went wrong.

**Comment by smarterclayton** [comment]
> Persisting logs will have to be batched (bulk API) for performance.

I do not intend pod logs to be a log accepting endpoint - only an interface
improves streaming log detail from an end user for better experience

> Elasticsearch does not support streaming results so will have to be
implemented with polling.

Ultimately, that's a limitation with elastic search, not with the intended
UX.  But I don't think in the short term we would attempt to stream from
elastic search - it is a much better design in the short term to continue
to use the nodes to serve low latency logs and fall back to elastic search
transparently for older historical logs.  I don't think it's unreasonable
to limit the scope of the API such that streaming historical logs defaults
to "off" in the short term (you can't follow=true in all cases, i.e. those
that fall back to ES).  If we need to better identify the distinction
between historical and realtime for users we should.  Non realtime use
cases are just bulk retrieval of logs.

Structured logs are interesting, but they are not the default experience to
a consumer of the platform.  I'm not opposed to exposing them in some form,
but for now ElasticSearch does a good job of that.

The issue is mostly concerned with increasing the surface area of the pod
logs API to make it useful for UI tools along the directions docker already
supports (itself using experience from several past iterations and prior
art). Fallback can be a second tier concern as long as we don't believe
it's impossible.


On Thu, Aug 13, 2015 at 12:22 PM, Jimmi Dyson <notifications@github.com>
wrote:

> There are 2 problems with streaming with this setup, both related to
> Elasticsearch.
>
>    1. Persisting logs will have to be batched (bulk API) for performance.
>    2. Elasticsearch does not support streaming results so will have to be
>    implemented with polling.
>
> Both of these will give a bit of a clunky UX. Streaming will be jerky at
> best. I don't consider streaming from Elasticsearch storage to be a good
> option for these requirements, although it is an excellent option for
> structured logs (a non-goal).
>
> If we're not considering structured logs in this then perhaps we need to
> revisit storage options, although I do think that would be missing a trick
> for other benefits, like being able to extract data from your logs for
> continuous improvement, over & above just troubleshooting why something
> went wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/12447#issuecomment-130749445>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by benjaminapetersen** [comment]
From the perspective of a web UI it would be ideal to get streaming logs via WebSockets.  Angular's $http doesn't support chunked http requests, neither does jQuery.ajax.  The browser will compile the chunks behind the scenes, waiting until all data is received then return it.  A raw XMLHttpRequest and an ArrayBuffer can be used to hack around this, but its not the most pleasant of workarounds.  WebSockets would allow us to render as data is received.

**Comment by smarterclayton** [comment]
We also may want to support web sockets for exec (so that web consoles can
run commands) as well.

On Mon, Aug 17, 2015 at 2:45 PM, Ben Petersen <notifications@github.com>
wrote:

> From the perspective of a web UI it would be ideal to get streaming logs
> via WebSockets. Angular's $http doesn't support chunked http requests,
> neither does jQuery.ajax. The browser will compile the chunks behind the
> scenes, waiting until all data is received then return it. A raw
> XMLHttpRequest and an ArrayBuffer can be used to hack around this, but its
> not the most pleasant of workarounds. WebSockets would allow us to render
> as data is received.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/12447#issuecomment-131922504>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by a-robinson** [comment]
Sounds good to me. I'd propose `timestamps` instead of `timestamp`, to match docker's CLI. I'm not convinced `limit` would see much use, but I suppose it makes sense given the `since` option and it'd be easy to implement no matter what the backend.

The only mild disclaimer worth bringing up is what @jimmidyson alluded to -- adding more dependencies on the presence of local log files makes it tougher for us to ever use a docker logging driver instead of having docker write out log files for fluentd to tail. I'm not convinced it'll be worth it for us to try making this swap anytime soon, though, for reasons like this.

**Comment by jimmidyson** [comment]
We also have to consider docker container log rotation as this should (must?) be implemented on nodes to prevent out of disk errors. This will put a limit on the `--since` & `--tail`, but I assume we can point at archived logs for older entries. Most use cases for live logs will be to look at recent logs (last day?) so log rotation shouldn't impact, but needs to be noted.

As detailed [here](https://github.com/docker/docker/blob/d136f5e027e30ac1f92938c7e5ea72b00f49dfc0/docs/reference/logging/overview.md#the-json-file-options):

> If `max-size` and `max-file` are set, docker logs only returns the log lines from the newest log file.

Is this desired behaviour? Should we recommend running with these options if we're sticking with the `json-log` logging driver? I say we do to protect integrity of nodes, but important that we think about how we handle containers that spew masses of logs.

**Comment by smarterclayton** [comment]
On Aug 18, 2015, at 4:15 AM, Jimmi Dyson <notifications@github.com> wrote:

We also have to consider docker container log rotation as this should
(must?) be implemented on nodes to prevent out of disk errors. This will
put a limit on the --since & --tail, but I assume we can point at archived
logs for older entries. Most use cases for live logs will be to look at
recent logs (last day?) so log rotation shouldn't impact, but needs to be
noted.


I think we have to assume rotation is on and work through the limits.  Not
rotating is not really an option.

As detailed here
<https://github.com/docker/docker/blob/d136f5e027e30ac1f92938c7e5ea72b00f49dfc0/docs/reference/logging/overview.md#the-json-file-options>
:

If max-size and max-file are set, docker logs only returns the log lines
from the newest log file.

Is this desired behaviour? Should we recommend running with these options
if we're sticking with the json-log logging driver? I say we do to protect
integrity of nodes, but important that we think about how we handle
containers that spew masses of logs.



Containers that are badly behaved with logs are their own enemies - there
are mechanisms they can use to send their logs elsewhere if they need
stronger guarantees than we can provide today.

Journal docker-log integration is in our roadmap, and that gives us the
best of both worlds.


—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12447#issuecomment-132115883>
.

**Comment by sosiouxme** [comment]
>
>
> Containers that are badly behaved with logs are their own enemies


I don't think sysadmins will see it that way when aggregating the logs from
one spin-locked container delays or halts getting the logs from all
containers. I think they will see it as a platform problem.

**Comment by smarterclayton** [comment]
That's not what I was saying - I'm saying that our goal is not to deliver
perfect log fidelity to a badly behaving container.  Our goal is to protect
the rest of the system from the container.  Restricting the log guarantees
a container gets when badly behaving is not as important as defending the
system from badly behaving containers.

On Tue, Aug 18, 2015 at 9:30 AM, Luke Meyer <notifications@github.com>
wrote:

> >
> >
> > Containers that are badly behaved with logs are their own enemies
>
>
> I don't think sysadmins will see it that way when aggregating the logs from
> one spin-locked container delays or halts getting the logs from all
> containers. I think they will see it as a platform problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/12447#issuecomment-132205682>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by sosiouxme** [comment]
+1

I guess you were saying, if the container is spewing logs so fast they get rotated before an aggregator can follow them (or just chooses to drop them), that's the container's problem.

**Comment by smarterclayton** [comment]
Right, should have been clearer.

On Tue, Aug 18, 2015 at 9:40 AM, Luke Meyer <notifications@github.com>
wrote:

> +1
>
> I guess you were saying, if the container is spewing logs so fast they get
> rotated before an aggregator can follow them (or just chooses to drop
> them), that's the container's problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/12447#issuecomment-132209698>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by a-robinson** [comment]
Agreed, we shouldn't make guarantees about not losing rotated logs from misbehaving containers. There's a point at which it's simply not worth the extra work to support the corner cases perfectly.

**Comment by satnam6502** [comment]
I really wish you could +1 comments on GitHub. +1 ^^^^^

**Comment by lavalamp** [comment]
@smarterclayton Did you have someone in mind to implement this? I have no arguments with the proposal.

**Comment by smarterclayton** [comment]
Not yet, but it might be me shortly, or someone else related to logs.

On Aug 26, 2015, at 7:51 PM, Daniel Smith <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> Did you have someone in
mind to implement this? I have no arguments with the proposal.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12447#issuecomment-135199191>
.
