### ISSUE TITLE
Some high-quality literature reading is required

### ISSUE THREAD

**Issue by Schwarao** [kubernetes/kubernetes#124523]
My topic is to implement a certain computing function in a container environment, which may involve dynamic scaling and resource scheduling. Now my supervisor wants me to read some papers, please recommend some papers to me.

**Comment by neolit123** [comment]
best to try asking on https;//discuss.k8s.io, or reddit/kubernetes.
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
