### ISSUE TITLE
Now I'm not receiving anything. No text or messages 

### ISSUE THREAD

**Issue by Boyplease24** [kubernetes/kubernetes#124579]
Can you please fix. I'm respectfully just trying to fix my device

**Comment by Boyplease24** [comment]
Can I factory reset? There's not a issue. Other than my messages and text not coming straight to my device. Why would info be held in cloud? I want my text to hit my phone

**Comment by Boyplease24** [comment]
I have no idea how to do this? 

/wg <group-name>

**Comment by thisisharrsh** [comment]
Could you please explain the issue that you are facing in detail?
