### ISSUE TITLE
PersistentVolumeLabel admission plugin provides wrong Azure region

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#124525]
### What happened?

On Kubernetes 1.29 with PersistentVolumeLabel admission plugin enabled and no in-tree cloud provider configured in the kube-apiserver, the admission plugins adds label `topology.kubernetes.io/region: ""` to in-tree Azure Disk PVs.

The label is completely wrong - the Azure cloud provider is not initialized and [this](https://github.com/kubernetes/kubernetes/blob/d9d45306df052aa5824fd8b2dab4e61f5ecc481c/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go#L368) just provides empty string. This makes any pod that uses these PVs unschedulable.

As result, all in-tree PVs dynamically provisioned using CSI migration are not usable, because they have a wrong region.

### What did you expect to happen?

When there is no cloud config provided, PersistentVolumeLabel does not add any labels to PVs. PVs created by the CSI driver + CSI migration already have correct `nodeAffinity`, the labels are useless.

### How can we reproduce it (as minimally and precisely as possible)?

1. Enable PersistentVolumeLabel admission in your cluster and disable any cloud providers. It does not need access to Azure, you can run it anywhere.

    Example for `local-up-cluster.sh`:

    ```
    ENABLE_ADMISSION_PLUGINS="NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,Priority,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,PersistentVolumeLabel"
    hack/local-up-cluster.sh
    ```

2. Create in-tree Azure Disk PV. Again, we're testing just the admission, we're not going to use the PV in a pod, so no access to Azure is needed. UUIDs were sanitized ;-)

    ```
    $ kubectl create -f <<EOF
    
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: myvol
    spec:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 5Gi
      azureDisk:
          cachingMode: ReadWrite
          diskName: pvc-ade30d58-5a51-4a62-a83a-142267b74f9e
          diskURI: /subscriptions/4347f140-6c74-4199-b4fc-1938eb6c16c0/resourceGroups/jsafrane-h-jsafrane-h-kxvpr/providers/Microsoft.Compute/disks/pvc-ade30d58-5a51-4a62-a83a-142267b74f9e
          fsType: ext4
          kind: Managed
          readOnly: false
    
    EOF
    ```

Actual result: wrong region label on the PV:

```
$ kubectl get pv --show-labels
LABELS
topology.kubernetes.io/region=
```

Expected result: no labels on the PV.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.29.3
```

</details>

### Cloud provider

<details>
None
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jsafrane** [comment]
@andyzhangx it would be great if Azure cloud provider did not provide any labels when it's actually not configured (i.e. the external one is used). Is there an easy way to detect that in the admission plugin in the API server?

`GetCloudProvider` [here](https://github.com/kubernetes/kubernetes/blob/d9d45306df052aa5824fd8b2dab4e61f5ecc481c/plugin/pkg/admission/storage/persistentvolume/label/admission.go#L285-L285) _could_ return some error + the admission _would_ ignore it (i.e. add no labels to PVs, but admit it; now the admission is denied on error)

Or `GetAzureDiskLabels` [deep inside the cloud provider](https://github.com/kubernetes/kubernetes/blob/d9d45306df052aa5824fd8b2dab4e61f5ecc481c/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go#L368-L368) would see it's not initialized and return no labels, say
```
if c.Location == "" {
    // Cloud provider is not initialized.
    return nil, nil
}
```

Note that it affects 1.29 and older that still have the cloud provider. I am fixing 1.30 differently in https://github.com/kubernetes/kubernetes/pull/124505

**Comment by jsafrane** [comment]
/priority important-soon

The PersistentVolumeLabel admission plugin + CSI migration on azure are basically unusable when used together. I guess it affects a small nr. of clusters, but there is no workaround.

**Comment by andyzhangx** [comment]
@jsafrane the pv lable issue only exists on in-tree disk pv, right? since in-tree disk volume is already deprecated long time ago, I think we could live with that issue.

**Comment by jsafrane** [comment]
In-tree PVs are deprecated, but still supported. If someone upgrades a fully working cluster to a version that has the external cloud provider instead of the in-tree one, they cannot use their StorageClass that was working for many releases.
CSI migration was supposed to provide guarantee that in-tree PVs and SCs keep working.

**Comment by andyzhangx** [comment]
> I filed #124528 to fix it as simply as possible, PTAL. Can there be a real Azure VM with `topology.kubernetes.io/region: ""` ?

this empty value won't make sense, it should always be `topology.kubernetes.io/region=location`

**Comment by jsafrane** [comment]
1.27-1.29 got fixed by https://github.com/kubernetes/kubernetes/pull/124528 and its cherry-picks
1.30 got fixed by https://github.com/kubernetes/kubernetes/pull/124794
1.31 / master got "fixed" by https://github.com/kubernetes/kubernetes/pull/124505
/close
