### ISSUE TITLE
The APIServer health check failed. As a result, the APIServer automatically exits and APIServer unavailable.

### ISSUE THREAD

**Issue by wwthw** [kubernetes/kubernetes#124502]
### What happened?

Most services access the APIServer through the service of the ClusterIP type. The relationship between the service and the endpoints is created by the APIServer , and then the iptables routing rule maintained by kube-proxy. When the APIServer is restarted, the routing rule cannot be updated quickly. A large amount of service traffic is received. CPU resources are limited and the CPU usage is high. As a result, the APIServer health check timeout and then the APIServer exits automatically. As a result, the service is unavailable.

### What did you expect to happen?

Before the APIServer is started successfully, a filter is added to the ingress to control the incoming traffic, ensuring that the APIServer can be started successfully and enhancing the APIServer reliability.

### How can we reproduce it (as minimally and precisely as possible)?

When the APIServer is started, a large number of requests are sent to the APIServer. As a result, the CPU is overloaded and the APIServer health check times out.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

```[tasklist]
### Tasks
```

**Comment by wwthw** [comment]
您好，我是王文涛，您的邮件我已收到，我会尽快给予回复的，谢谢~~~~~

**Comment by aojea** [comment]
> When the APIServer is started, a large number of requests are sent to the APIServer. As a result, the CPU is overloaded and the APIServer health check times out.

We should not use the network to workaround the root cause, the apiserver has to be dimensioned accordingly to deal with the load of the cluster, and use the existing mechanism to protect it from situations like the ones your are describing

APF just went GA in 1.29 https://kubernetes.io/docs/concepts/cluster-administration/flow-control/ and IIUIC  is  designed around the use case you are presenting

> Controlling the behavior of the Kubernetes API server in an overload situation is a key task for cluster administrators. The [kube-apiserver](https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver) has some controls available (i.e. the --max-requests-inflight and --max-mutating-requests-inflight command-line flags) to limit the amount of outstanding work that will be accepted, preventing a flood of inbound requests from overloading and potentially crashing the API server, but these flags are not enough to ensure that the most important requests get through in a period of high traffic.

/close

**Comment by wwthw** [comment]
您好，我是王文涛，您的邮件我已收到，我会尽快给予回复的，谢谢~~~~~
