### ISSUE TITLE
vagrant salt provisioning time improvement

### ISSUE THREAD

**Issue by shanemikel** [kubernetes/kubernetes#12457]
I'm wondering if there's a way to get around the salt provisioning taking a long time (sometimes forever).  If I'm using vagrant to spin up kubernetes cluster, It's a generally viable assumption that I'm running locally for test purposes.

Assuming I'm right in that the problem with salt provisioning is the generation of random data (I haven't checked that assumption), would it be possible to provide an option to use /dev/urandom instead of /dev/random for non-blocking data generation?

**Comment by roberthbailey** [comment]
@derekwaynecarr - this issue hasn't been updated in almost two years, so unless you think it's worth addressing at this point, I'd suggest that we close it.
