### ISSUE TITLE
kubelet and containerd in endless loop for CreateContainer with unexpected media type octet-stream

### ISSUE THREAD

**Issue by thomasmey** [kubernetes/kubernetes#124515]
### What happened?

I think the private container registry had some intermittent errors and did return wrong data for some layers.

The problem I think is that kubelet or containerd is in a state were it assumes that a given OCI image is already downloaded locally, but then some parsing of this layer fails and the loop starts again.

### What did you expect to happen?

kubelet and or containerd should detect the wrong layer/manifest state and delete the incomplete/erroneous download and pull again from container registry.

### How can we reproduce it (as minimally and precisely as possible)?

Not sure, probably container registry needs to return media type octet-stream for some layer/manifest instead of correct media type.

### Kubernetes version

<details>
Kubelet 1.28.7-gke.1026000
Containerd 1.7.10
Linux 6.1.58+
</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Will provide 
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by thomasmey** [comment]
The error message I see in the logs are probably come from here:
https://github.com/containerd/containerd/blob/v1.7.15/images/image.go#L238
Not sure about exact containerd version but I think it's 1.7.x

**Comment by thomasmey** [comment]
The containerd fails probably here:
https://github.com/containerd/containerd/blob/v1.7.10/images/image.go#L238

Looks like something with the local manifest bookkeeping is not correct, which hinders container creation.

Maybe containerd can detect that image layer/manifest is read from local cache and remove erroneous cached local image layers

**Comment by saschagrunert** [comment]
> kubelet and or containerd should detect the wrong layer/manifest state and delete the incomplete/erroneous download and pull again from container registry.

containerd should identiffy the corrupt layer and remove it, that's nothing the kubelet should do. The kubelet only tells the runtime to pull images when they're not present on disk.

Do you mind moving that issue to the containerd repo?
