### ISSUE TITLE
Error for Update-demo example

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#12465]
Hi this is my pods:

$ curl http://master:8080/api/v1/proxy/namespaces/default/pods/update-demo-nautilus-z7x57/data.json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "pods \"update-demo-nautilus-z7x57\" not found",
  "reason": "NotFound",
  "details": {
    "name": "update-demo-nautilus-z7x57",
    "kind": "pods"
  },
  "code": 404

My /etc/hosts reads:
127.0.0.1 localhost
10.211.x.x master

$ kubectl get pods
NAME                         READY     STATUS    RESTARTS   AGE
update-demo-nautilus-7znvi   1/1       Running   0          3m
update-demo-nautilus-km9zc   1/1       Running   0          3m

$ kubectl get services
NAME         LABELS                                    SELECTOR   IP(S)         PORT(S)
kubernetes   component=apiserver,provider=kubernetes   <none>     192.168.3.1   443/TCP

**Comment by timothysc** [comment]
side note - Our update-demo e2e's are running fine on our cluster.

**Comment by a-robinson** [comment]
So what behavior are you expecting here that you're not seeing? It looks like two nautilus pods are running just fine, they just happen to have different names than the one you looked for.

**Comment by adyanthaya17** [comment]
@a-robinson When I ran the first command i.e. curl the status reads as failure and reason being not found. Can someone tell as to which IP's are to be specified in the ubuntu/config-default.sh in the fields for:

export SERVICE_CLUSTER_IP_RANGE=${SERVICE_CLUSTER_IP_RANGE:-x.x.x.x}

export FLANNEL_NET=${FLANNEL_NET:-x.x.x.x}

I'm not sure if the private network or the public network of the node has to be used.

**Comment by a-robinson** [comment]
It looks like the IP address is working just fine for you. You got a valid response, it was just one telling you that the particular pod you were looking for doesn't exist. Kubectl worked just fine, which means your cluster is working fine.

What exactly are you trying to do?

**Comment by adyanthaya17** [comment]
I'm unable to get the GUI for the images on the web page, therefore I'm not sure if I used the right IP's in the configuration file. 

How do I assign the containers with external IP so that it's accessible in the GUI?

**Comment by a-robinson** [comment]
What happens when you run the commands actually shown in the [update-demo README](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/user-guide/update-demo)?

Also note that there are some stale paths in that doc that I've just sent out #12570 to fix.

**Comment by adyanthaya17** [comment]
This is what I've done:
$kubectl proxy --www=examples/update-demo/local/ &
Starting to serve on localhost:8001

I'm able to run all the commands successfully except that I'm unable to  use the IP assigned to it in the browser as it's a clustered environment IP:
http://localhost:8001/static

My /etc/hosts:
root@master:/home/ubuntu/kubernetes# cat /etc/hosts
127.0.0.1 localhost
10.x.x.x master

and the config-default.sh:
export SERVICE_CLUSTER_IP_RANGE=${SERVICE_CLUSTER_IP_RANGE:-20.x.x.0/24}

export FLANNEL_NET=${FLANNEL_NET:-172.x.x.0/16}

**Comment by a-robinson** [comment]
I'm sorry, can you be more precise about what you're doing and what you're seeing? I'm having difficulty parsing exactly what your problem is.

However, you should definitely be using `kubectl proxy --www=docs/user-guide/update-demo/local/ &` instead of the one that you listed, as I mentioned in my previous comment.

Also, you should be using `kubectl proxy` from your local machine rather than from one of the VMs in the cluster if you want to be able to visit the web page on your local machine.

**Comment by adyanthaya17** [comment]
I'll start from the beginning. I have a kubernetes cluster running successfully. I have 3 nodes and I've deployed my minion services on all the three nodes. 

$/etc/hosts
127.0.0.1 localhost
20.10.0.x master-minion

$ kubectl get pods
NAME         LABELS                              STATUS
20.10.0.x   kubernetes.io/hostname=20.10.0.x   Ready
20.10.0.y  kubernetes.io/hostname=20.10.0.y   Ready
20.10.0.z   kubernetes.io/hostname=20.10.0.z  Ready

I deplopyed the adds-on after adding the line---ENABLE_CLUSTER_UI="${KUBE_ENABLE_CLUSTER_UI:-true}" in the config-default.sh file.

$  KUBERNETES_PROVIDER=ubuntu ./deployAddons.sh
Deploying DNS on kubernetes
replicationcontrollers/kube-dns-v8
services/kube-dns

When I go to the /user-guide/update-demo document and run:
$ kubectl proxy --www=docs/user-guide/update-demo/local/ &
$ Starting to serve on localhost:8001   //This gets prompted in the next line.

After this, I'm able to create the pods and replicate it. But when I try to access the IP
http://localhost:8001/static

I get 'Internet Explorer cannot display the webpage'. 

The kubectl get service doesn't provide any IP or port for this particualar application while I tried the cassandra application it gave me the virtual IP which I'm unable to access through the browser. I'm not able to ping the conatiner IP either.

**Comment by adyanthaya17** [comment]
I ran the below command and the output is as seen:

$ curl http://master:8080/api/v1/proxy/namespaces/default/pods/update-demo-nautilus-6lyv4/data.json
 {
 "image": "nautilus.jpg"
 }

If I use the URL in the browser: http://10.x.x.x:8080/api/v1/proxy/namespaces/default/pods/update-demo-nautilus-6lyv4/data.json
 I get:
 {
 "image": "nautilus.jpg"
 }

But when I go to the IP as specified in the document --http://localhost:8001/static/index.html
 I get 'Internet explorer cannot find the page'.

How do I get the images on the browser that are being replicated so that I can view them than the code?

**Comment by adyanthaya17** [comment]
@roberthbailey I did run the kubectl proxy on my node that has both master and minion, that looks like this:

$kubectl proxy --www=examples/update-demo/local/ &
Starting to serve on localhost:8001

**Comment by roberthbailey** [comment]
The proxy functionality will only accept connections from localhost (see https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/proxy_server.go#L183). 

That means that you need to a) run your web browser on the same machine as the proxy, b) create an ssh tunnel to forward packets from your machine to the machine running the proxy, or c) run the proxy on the same machine as your web browser.

**Comment by adyanthaya17** [comment]
I am running the kubectl proxy in the machine as my web browser.

The document said to access-http://localhost:8001/static but for example I have two kubernetes cluster created and if the application running. How will it identify the exact node of application I want to view?

**Comment by roberthbailey** [comment]
You need to use `kubectl config set-context` to select the cluster to which kubectl (including kubectl proxy) connects to. See http://kubernetes.io/v1.0/docs/user-guide/kubectl/kubectl_config_set-context.html.
