### ISSUE TITLE
What Is the Meaning of "Updating CRD OpenAPI spec because xxx changed" in the apiserver Log? 

### ISSUE THREAD

**Issue by kangzhiqin** [kubernetes/kubernetes#124611]
### What would you like to be added?

The apiserver prints a crd update log every 5 minutes. What does this mean? What is the triggering process?

### Why is this needed?

https://github.com/kubernetes/kubernetes/blob/bac1a0ce1b284aff8db1aeeb571d97fa130078a6/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/controller.go#L228

**Comment by kangzhiqin** [comment]
The principle has been figured out. After the CRD is created, the APIServer updates the cached log records after the change.

**Comment by danijam** [comment]
@kangzhiqin We are also seeing this also but still don't understand why... The CRDs haven't changed? Or at least not to my knowledge so confused why we see hundreds of log lines every 5 mins that strikes me as kube-apiserver doing lots of work with the OpenAPI Spec that it doesn't need too?

**Comment by kangzhiqin** [comment]
> @kangzhiqin We are also seeing this also but still don't understand why... The CRDs haven't changed? Or at least not to my knowledge so confused why we see hundreds of log lines every 5 mins that strikes me as kube-apiserver doing lots of work with the OpenAPI Spec that it doesn't need too?

When the CRD informer is created, the full synchronization mechanism is set to be performed every 5 minutes. The log is the evidence of full synchronization. I want you to focus on line 175 here.

https://github.com/kubernetes/kubernetes/blob/5bf1e95541d90e37f6c6637b5b45d8783e7907aa/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go#L162-L185
