### ISSUE TITLE
Kubelet will only get machine info when it is started.

### ISSUE THREAD

**Issue by zhangguanzhang** [kubernetes/kubernetes#124650]
### What would you like to be added?

Hot increase cpu/memory/storage so that kubelet can recognize it without restarting

### Why is this needed?

When the node machine is expanded to these three configuration types, the calculation value source of kubelet based on eviction pod still uses old data.

I would like to add this functionality in a subsequent version, first from a feature gate as a switch

**Comment by ffromani** [comment]
hi, thanks for filing this issue. This is indeed something to improve in the kubelet. We are already discussing in https://github.com/kubernetes/enhancements/issues/3953
