### ISSUE TITLE
The Version Skew Policy does not mention aggregated apiservers

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#124655]
### What happened?

Someone opened #124533 saying

> I expected 1.29 libraries to still be compatible with Kubernetes 1.28 based on the kube-apiserver version skew.

I think that is not what the version skew policy (https://kubernetes.io/releases/version-skew-policy/) is trying to say. I think that the guiding principle is that you must first upgrade the servers that store objects of a given API group and resource/kind, then upgrade the clients of those servers.

In particular, the existing version skew policy document explicitly discusses several kinds of components, but does not mention aggregated apiservers. I think that these should be explicitly mentioned.

### What did you expect to happen?

Everybody agrees on what to expect.

### How can we reproduce it (as minimally and precisely as possible)?

Read the cited doc and Issue.

### Anything else we need to know?

Nope

### Kubernetes version

<details>

All of them.

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

N/A

</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by sftim** [comment]
@MikeSpreitzer if you agree, I suggest you transfer this to [k/website](https://github.com/kubernetes/website). The Prow command for that is `/transfer website`.

**Comment by sftim** [comment]
AIUI Kubernetes release versioning doesn't apply to any aggregated API servers, although some of the components you might run use library code that we release.

You can implement an API server in any language and you don't need to have any Kubernetes code in your implementation. However, your aggregated API server should ideally to be compatible with every API server in your control plane at any point during an upgrade. We can still document more about compatibility than we do right now.

**Comment by dims** [comment]
wasn't this talked about recently @MikeSpreitzer ? https://github.com/kubernetes/kubernetes/issues/124533#issuecomment-2088524797

**Comment by seans3** [comment]
I think the other issue #124533 has been transitioned to a docs issue. I will close this one in favor of the other one. Please re-open if I am mistaken.

/close
