### ISSUE TITLE
Build and e2e failures caused by AWS S3 issues.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#12467]
It turns out that we depend on AWS to build and run e2e tests (which I find rather amusing).

I saw two problems:
When building a binary we do
```
Step 9 : RUN mkdir -p /usr/local/src/etcd &&    cd /usr/local/src/etcd &&    curl -L -O -s https://github.com/coreos/etcd/releases/download/v2.0.0/etcd-v2.0.0-linux-amd64.tar.gz &&    tar xzf etcd-v2.0.0-linux-amd64.tar.gz &&    ln -s ../src/etcd/etcd-v2.0.0-linux-amd64/etcd /usr/local/bin/
```
which ended up with
```
tar (child): etcd-v2.0.0-linux-amd64.tar.gz: Cannot open: No such file or directory
```
It's rather bad that we don't emit more helpful messages, but
```
wget https://github.com/coreos/etcd/releases/download/v2.0.0/etcd-v2.0.0-linux-amd64.tar.gz
```
does print:
```
...
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.8.8
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.8.8|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2015-08-10 10:04:01 ERROR 503: Service Unavailable.
```

Workaround is to download the tar by hand from somewhere and put it into workdir.

Smaller one is the fact that our `kubectl` and `examples` e2e tests fail, without any helpful messages:
```
• Failure [312.402 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:578
  Simple pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:207
    should support port-forward [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:206

    Failed to parse kubectl port-forward output: F0810 12:14:45.825942     596 portforward.go:102] Unable to execute command because pod is not running. Current status=Pending
```

Running get/describe Pod while the test is running gives:
```
Get https://registry-1.docker.io/v1/repositories/library/nginx/tags: read tcp 54.152.161.54:443: i/o timeout
```
which is yet another Amazon address that's not working.

For e2e test we probably can have some failover "old" images stored somewhere (e.g. GCR), but I don't know what to do with the first issue (or do we actually care enough to have some failover for it)

cc @brendanburns @thockin

**Comment by gmarek** [comment]
cc @fgrzadkowski

**Comment by timothysc** [comment]
@gmarek @fgrzadkowski - FWIW we build and run e2e's against the tip of all of the stack to vet & catch earlier where possible.  

Currently we are running tip of: 
etcd, k8's, flannel on latest Atomic, nightly.

**Comment by gmarek** [comment]
@timothysc - the main issue here is that, surprisingly, when S3 is down it's impossible to build Kubernetes. Which I find slightly ironic. We can say that's OK, but we certainly should print out more helpful message.

**Comment by timothysc** [comment]
@gmarek we bypass those steps and run everything raw, so we're unaffected.. for once ;-)
