### ISSUE TITLE
kube-ui does not work properly

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#12468]
####Steps to reproduce
- create a rc & svc as in cluster/addons/kube-ui
- visit the web page( by which i mean 10.10.102.98:37974), click the buttons (to list resources) and get nothing

When clicking the button "Nodes" in the "Views" list, the corresponding request sent was like
 ```
Request URL:http://10.10.102.98:37974/api/v1/nodes
```
whose response was 404 not found. ( normal response without doubt, 'cause the request url is the trouble maker AFAIK)
Any ideas?

####ENV
I guess it's not platform-sensitive, yet list ENV here just in case.
ubuntu 14.04
docker version: 1.7.1
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0", GitCommit:"cd821444dcf3e1e237b5f3579721440624c9c4fa", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-424-gd95ca69400c68d-dirty", GitCommit:"d95ca69400c68d9e7619096d504548c7a4835680", GitTreeState:"dirty"}
```

**Comment by dalanlan** [comment]
10.10.102.98 is the node ip that kube-ui pod is scheduled.
```
$ sudo iptables -t nat -L
DNAT       tcp  --  anywhere             192.168.3.184        /* kube-system/kube-ui: */ tcp dpt:http to:10.10.102.98:37974
```

**Comment by dalanlan** [comment]
Not accessible via https://10.10.102.97:6443/ui (where 10.10.102.97 is the master ip) - - Unauthorized.

/cc @timstclair

**Comment by bkeroackdsc** [comment]
+1 kube-ui assumes that base URL is also the k8s API endpoint, which may not be the case

**Comment by decker502** [comment]
+1

**Comment by lvlv** [comment]
+1
btw, can you try http://apiserver:8080/ui? Works from my env.

**Comment by dalanlan** [comment]
I'll bet you mean http://<master-ip>:8080/ui?
8080 is binded to 127.0.0.1 in my case, so I (and basically no one else too) can access that via url ;-)

**Comment by bq-xiao** [comment]
I think you should launch kube-ui manually with:
>kubectl create -f cluster/addons/kube-ui/kube-ui-rc.yaml
>kubectl create -f cluster/addons/kube-ui/kube-ui-svc.yaml

Seeing the same problem here https://github.com/GoogleCloudPlatform/kubernetes/issues/10697

**Comment by dalanlan** [comment]
I did that already, and the pod works properly.

**Comment by timstclair** [comment]
To summarize (is this correct?):
- kube-ui is accessible and works through the <master-ip>/ui endpoint (which redirects to the service proxy <master-ip>/api/v1/proxy/namespaces/kube-system/services/kube-ui/)
- kube-ui is accessible but not functional via the pod IP directly since it attempts to access the API through the base IP (10.10.102.98:37974 in your case)

What is the use case for accessing the UI through the pod directly?

**Comment by preillyme** [comment]
It's working well in my testing with the proper /ui endpoint. Do you NOT have the service proxy working correctly?

**Comment by dalanlan** [comment]
@timstclair 
Exactly. Since I have used https certificates, it's unavailable for me to access it via 8080 without extra work. I was wondering if i can save myself the trouble to configure the certs/key/ca in my web brower, that sort of stuff through the base IP. (Since i'm not familiar with that part and never dig that deep)
It's kinda odd, i'll admit :-) 



@preillyme  The proxy is all right. Thank you for your concern.

**Comment by timstclair** [comment]
Correct me if I'm wrong, but since the UI needs access to the API it sounds like it's working as intended for an unauthenticated UI connection to be denied access to the authenticated API (for security).

**Comment by dalanlan** [comment]
![111](https://cloud.githubusercontent.com/assets/5979704/9240879/6c2ca92e-419e-11e5-8346-86d929ae7fe9.png)

Yet it leads me here via http://10.10.102.98:37974/
And when you click the button, it does send a http request, only a wrong one.
Is this intended?

**Comment by bgrant0607** [comment]
@timothysc is correct.

Eventually we'll have auth policy in the apiserver.

**Comment by bgrant0607** [comment]
cc @kubernetes/kube-ui-maintainers
