### ISSUE TITLE
Compatibility between `k8s.io/component-base` and latest `go.opentelemetry.io/otel/exporters/prometheus`.

### ISSUE THREAD

**Issue by angelokurtis** [kubernetes/kubernetes#124687]
### What would you like to be added?

I would like `k8s.io/component-base` to be compatible with the latest version of `go.opentelemetry.io/otel/exporters/prometheus`.

### Why is this needed?

In version `0.48.0` of the `github.com/prometheus/common` library, the `expfmt.FmtText` constant [was made private](https://github.com/prometheus/common/commit/05d7387306aee31a5a9776899b1baf2267667e81#diff-60c3dc651d46ce2018a3e3c97b4bcddd42d132f134c1e592efa28aa4f589090aL45). This directly impacts its compatibility with `k8s.io/component-base`, which uses this constant, leading to issues with the latest Prometheus libraries, such as `go.opentelemetry.io/otel/exporters/prometheus`.

**Comment by neolit123** [comment]
you can try contacting https://github.com/kubernetes/community/tree/master/sig-instrumentation

**Comment by rexagod** [comment]
@angelokurtis Could you link to where this is being used in `component-base`? I did a [search](https://github.com/search?q=repo%3Akubernetes%2Fkubernetes+path%3A%2F%5Estaging%5C%2Fsrc%5C%2Fk8s%5C.io%5C%2Fcomponent-base%5C%2F%2F+FmtText&type=code) but it came up empty.

**Comment by angelokurtis** [comment]
It appears that the issue was resolved in #124346 and will be included in v1.31

**Comment by rexagod** [comment]
/close

Sounds good, closing this then.
