### ISSUE TITLE
kubectl describe uses Endpoints instead of EndpointSlices

### ISSUE THREAD

**Issue by aroradaman** [kubernetes/kubernetes#124651]
### What would you like to be added?

kubectl describe should use **discoveryv1.EndpointSlice** instead of **v1.Endpoints**.

### Why is this needed?

Almost everything in Kubernetes uses endpoint slices instead of endpoints.
This discussion started from https://github.com/kubernetes/kubernetes/issues/123954.

**Comment by brianpursley** [comment]
Related issue:
https://github.com/kubernetes/kubectl/issues/1533

**Comment by aroradaman** [comment]
/close 
dup of https://github.com/kubernetes/kubectl/issues/1533
