### ISSUE TITLE
Throughput degradation scheduling daemonset pods

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#124709]
### What happened?

https://github.com/kubernetes/kubernetes/pull/119779 added some map queries and creations that add non-negligible latency.

The pprof reveals the following lines inside `findNodesThatFitPod` as too expensive:
- 22.2% https://github.com/kubernetes/kubernetes/blob/44bd04c0cbddde69aaeb7a90d3bd3de4e417f27f/pkg/scheduler/schedule_one.go#L492
- 21.7% https://github.com/kubernetes/kubernetes/blob/44bd04c0cbddde69aaeb7a90d3bd3de4e417f27f/pkg/scheduler/schedule_one.go#L489

![image](https://github.com/kubernetes/kubernetes/assets/1299064/d82a658e-ae01-4bcd-9e0d-6ab892bee6c2)

### What did you expect to happen?

Scheduler to keep a throughput of 300 pods/s

### How can we reproduce it (as minimally and precisely as possible)?

Schedule 5k daemonset pods giving 300 qps to the scheduler

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.30
</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
Before #119779, there was this line:
https://github.com/sanposhiho/kubernetes/blob/5ab23179473b621e911511b03693234b60a38033/pkg/scheduler/schedule_one.go#L489

which also had a map access. So we can quite confidently say that the culprit is just the map insert of https://github.com/kubernetes/kubernetes/blob/44bd04c0cbddde69aaeb7a90d3bd3de4e417f27f/pkg/scheduler/schedule_one.go#L492

**Comment by alculquicondor** [comment]
@sanposhiho, @AxeZhan  I have two alternatives:

1. The obvious one is to do a preallocation for the size of the map. I suspect this might be enough, but still somewhat wasteful.
2. Change the preemption logic to assume that if a Node is not in the status map, it's `UnschedulableAndUnresolvable`. https://github.com/kubernetes/kubernetes/blob/44bd04c0cbddde69aaeb7a90d3bd3de4e417f27f/pkg/scheduler/framework/preemption/preemption.go#L422

Option 2 also solves #124705. However, external PostFilter plugins need to be aware of the change. But I'm not aware of any in the wild that implements a behavior similar to preemption. We can leave an ACTION REQUIRED. But was this path working in 1.28 and older?

Regardless of the decision, I think we should accompany the fix with an integration test for preemption by daemonset pods.

**Comment by sanposhiho** [comment]
Can we try (1) first, ask Google for a scalability test again, and then consider (2) if (1) doesn't improve the throughput enough?

(2) could break existing PostFilter plugins. Given PostFilter is not only for preemption, in the world, there may be custom PostFilter plugins which have to rely on the status map with UnschedulableAndUnresolvable nodes. So, it'd be best if we could avoid this breaking.

**Comment by AxeZhan** [comment]
Since (1) is a really small fix, I'm also thinking if we can run tests after #124714 , and then consider (2) base on the test results.

> Regardless of the decision, I think we should accompany the fix with an integration test for preemption by daemonset pods.

Are these "integration test" for performance or correctness?

**Comment by alculquicondor** [comment]
I was asking for a correctness test

**Comment by chengjoey** [comment]
I wrote a benchmark test called `Benchmark_findNodesThatFitPod`

The performance without case(1) is: 
```
4927125125 ~ 5118241875 ns/op
```

The performance of case (1) is: 
```
3865283834 ~ 3972690125 ns/op
```

(1) may improve throughput

**Comment by alculquicondor** [comment]
I guess we can have a different tracking issue for an integration benchmark.

This issue itself is fixed.

/close

**Comment by gabesaba** [comment]
/reopen
/assign

Still observing poor performance in large clusters post #124714. I'm investigating further improvements.

**Comment by sanposhiho** [comment]
@gabesaba @chengjoey 

As I asked [here](https://github.com/kubernetes/kubernetes/pull/124728#issuecomment-2100051619), can we add a test case to scheduler_perf to reproduce this degradation?

Also, more generally, would it be possible to copy Google’s internal scalability tests to k/k somehow? (already talked to Aldo before) There’ve been multiple times that Google found a scalability issue with their internal tests.
Integrating them into scheduler_perf would be the best; we may need to improve scheduler_perf if its capability isn't enough to incorporate, though.

**Comment by chengjoey** [comment]
> @gabesaba @chengjoey
> 
> As I asked [here](https://github.com/kubernetes/kubernetes/pull/124728#issuecomment-2100051619), can we add a test case to scheduler_perf to reproduce this degradation?
> 
> Also, more generally, would it be possible to copy Google’s internal scalability tests to k/k somehow? (already talked to Aldo before) There’ve been multiple times that Google found a scalability issue with their internal tests. Integrating them into scheduler_perf would be the best; we may need to improve scheduler_perf if its capability isn't enough to incorporate, though.

Currently, scheduler_perf does not seem to be able to reproduce the current scenario. Should we first improve scheduler_perf to make it similar to daemonset, such as labeling each node with a specific label or specifying a dedicated node for the pod to achieve the k/k effect?

**Comment by alculquicondor** [comment]
> As I asked https://github.com/kubernetes/kubernetes/pull/124728#issuecomment-2100051619, can we add a test case to scheduler_perf to reproduce this degradation?

We plan to do it an follow up. For now, we have the urgent need to get this back to baseline.

**Comment by sanposhiho** [comment]
Yep, I didn't mean to block the patch PR for scheduler_perf improvement. Doing this as a follow up is totally fine.

> Currently, scheduler_perf does not seem to be able to reproduce the current scenario. Should we first improve scheduler_perf to make it similar to daemonset, such as labeling each node with a specific label or specifying a dedicated node for the pod to achieve the k/k effect?

We can improve scheduler_perf if needed. But, I'm wondering if we could reproduce the degradation just with a simple test case in which creating 5k Pods that have NodeAffinity matching with only one Node among many Nodes (<- @alculquicondor how many Nodes did you have in the scalable test?). I believe the current scheduler_perf is expressive enough to define such test case.

**Comment by alculquicondor** [comment]
We had 15k nodes with 6 Daemonsets, so 90k Pods.

**Comment by sanposhiho** [comment]
I could reproduce the degradation with a new test case (15k nodes / 30k pods) in scheduler_perf https://github.com/kubernetes/kubernetes/pull/125293 (WIP) and confirm #125197 solves the degradation.
 
---

Master

```json
    {
      "data": {
        "Average": 120.80130209885886,
        "Perc50": 128.88163639395216,
        "Perc90": 155.10790546767575,
        "Perc95": 161.00505378763333,
        "Perc99": 169.00350513269643
      },
      "unit": "pods/s",
      "labels": {
        "Metric": "SchedulingThroughput",
        "Name": "SchedulingNodeAffinity/15000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
```

After #125197 

```json
    {
      "data": {
        "Average": 552.6016212924262,
        "Perc50": 474.34585036045274,
        "Perc90": 877.1160813824991,
        "Perc95": 1121.327881099065,
        "Perc99": 1457.5364518479603
      },
      "unit": "pods/s",
      "labels": {
        "Metric": "SchedulingThroughput",
        "Name": "SchedulingNodeAffinity/15000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
```

**Comment by AxeZhan** [comment]
/reopen

I think we still need to implement [option2](https://github.com/kubernetes/kubernetes/issues/124709#issuecomment-2096605264) and some [follow-ups](https://github.com/kubernetes/kubernetes/pull/125197#discussion_r1623144924)of #125197.

@gabesaba Will you continue working on this?

**Comment by alculquicondor** [comment]
https://github.com/kubernetes/kubernetes/pull/125197 is option 2

But yes, there are some follow ups.

**Comment by sanposhiho** [comment]
Can we close it? Any remaining task here?

**Comment by AxeZhan** [comment]
Followup is tracked in https://github.com/kubernetes/kubernetes/issues/125345, so I think it's fine to close it.
/close
