### ISSUE TITLE
[FailingTest] [sig-node] [NodeFeature:SidecarContainers] Containers Lifecycle should terminate sidecars simultaneously if prestop doesn't exit

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#124743]
### Which jobs are failing?

Multiple, for example:
- [ci-crio-cgroupv1-node-e2e-features](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features)
- [ci-crio-cgroupv2-node-e2e-features](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv2-node-e2e-features)

### Which tests are failing?

`E2eNode Suite: [It] [sig-node] [NodeFeature:SidecarContainers] Containers Lifecycle should terminate sidecars simultaneously if prestop doesn't exit`

### Since when has it been failing?

Since e798b9c26

### Testgrid link

See above

### Reason for failure (if possible)

The test tolerations are now to strict:

```
Expected
    <int64>: 29372
to be within 1000 of ~
    <int>: 32000
In [It] at: k8s.io/kubernetes/test/e2e_node/container_lifecycle_test.go:2876 @ 05/08/24 05:42:29.367
}
```

### Relevant SIG(s)

/sig node

**Comment by saschagrunert** [comment]
cc @kubernetes/sig-node-cri-o-test-maintainers

**Comment by haircommander** [comment]
I think it's from https://github.com/kubernetes/test-infra/pull/32576 
if you check the cri-o versions the succeessful one was efff37a2900e5039e5af554c3196633df25890dc and the failing was d519447937c4711db9ad3e783ab2b8121b39b996

**Comment by saschagrunert** [comment]
Working on a fix in https://github.com/cri-o/cri-o/pull/8162

**Comment by gjkim42** [comment]
cc

**Comment by haircommander** [comment]
/reopen

need to bump in kube as well to fully get the fix
