### ISSUE TITLE
[FailingTest] [gce-master-scale-correctness] Multiple test failures, mostly networking

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/kubernetes#124744]
### Which jobs are failing?

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

### Which tests are failing?

Network related tests:
* Kubernetes e2e suite.[It] [sig-network] Services GCE [Slow] should be able to create and tear down a standard-tier load balancer [Slow]
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers should be able to change the type and ports of a UDP service [Slow]
* Kubernetes e2e suite.[It] [sig-apps] Deployment should not disrupt a cloud load-balancer's connectivity during rollout
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers ESIPP [Slow] should work from pods
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers should be able to switch session affinity for LoadBalancer service with ESIPP on [Slow] [LinuxOnly]
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers ESIPP [Slow] should only target nodes with endpoints
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers should be able to create an internal type load balancer [Slow]
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers should have session affinity work for LoadBalancer service with ESIPP on [Slow] [LinuxOnly]
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers should have session affinity work for LoadBalancer service with ESIPP off [Slow] [LinuxOnly]
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers should handle load balancer cleanup finalizer for service [Slow]
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers should be able to create LoadBalancer Service without NodePort and change it [Slow]
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on the same nodes
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers should only allow access from service loadbalancer source ranges [Slow]
* Kubernetes e2e suite.[It] [sig-storage] CSI Mock volume expansion CSI online volume expansion should expand volume without restarting pod if attach=off, nodeExpansion=on
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers ESIPP [Slow] should work for type=LoadBalancer
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on different nodes
* Kubernetes e2e suite.[It] [sig-network] LoadBalancers ESIPP [Slow] should handle updates to ExternalTrafficPolicy field

Storage related test:
* Kubernetes e2e suite.[It] [sig-storage] CSI Mock volume storage capacity storage capacity unlimited

### Since when has it been failing?

Since 04-12 each of those tests had at least one failure

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

### Relevant SIG(s)

/sig network storage

**Comment by jprzychodzen** [comment]
Do you know if this is related to recent changes in CCM pipeline?

/cc @aojea

**Comment by jprzychodzen** [comment]
Ref. #122286 - networking issues are tracked there.

**Comment by aojea** [comment]
> Ref. #122286 - networking issues are tracked there.

This is a dup of #122286 

/close

Besides that, all cloudprovider code has been removed and we had to make the test cloud provider agnostic https://github.com/kubernetes/kubernetes/pull/124660 , so we need to keep an eye on this job, I've had to change the regex https://github.com/kubernetes/test-infra/pull/32585 but I still didn't verify we didn't miss coverage (@jprzychodzen please check that we have downstream jobs picking this changes if you don't mind)

**Comment by jprzychodzen** [comment]
@aojea https://github.com/aojea/test-infra/blob/c72cf043f571c4954c2a8c3d73bf7a0a6d64eaac/config/jobs/kubernetes/sig-scalability/sig-scalability-release-blocking-jobs.yaml#L47 doesn't really makes what I'm expecting. I don't see `[Feature:LoadBalancer]` tests in https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness . Is there any follow up happening?

**Comment by aojea** [comment]
it runs every two days, and PR recovering the loadbalancer tests merged today, we have to wait to the next run
