### ISSUE TITLE
集群升级kubelet版本高于kube-apiserver版本

### ISSUE THREAD

**Issue by Xiaolei1091058519** [kubernetes/kubernetes#124720]
### What happened?

集群版本是1.22.5-00版本，我这边将节点kubelet版本升级到1.23.17-00版本，按照官方文档中的说明，kubelet版本不能高与kube-apiserver版本（1.22.5-00），可是我的节点还是正常可以创建pod资源。节点kubelet日志无异常。目前不确定这样问题出在哪儿，哪位大神可以帮我解答一下。
![image](https://github.com/kubernetes/kubernetes/assets/169143772/d75f4a14-a408-4468-afd0-650cdbae0974)
官方文档地址：https://kubernetes.io/zh-cn/releases/version-skew-policy/

### What did you expect to happen?

kubelet版本高于kube-apiserver版本，会出现节点notready或者是创建pod资源失败的情况。

### How can we reproduce it (as minimally and precisely as possible)?

集群是1.22.5-00版本，其中一个node节点kubelet升级到1.23.17-00版本。

### Kubernetes version

<details>

```console
$ kubectl version
#Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
#NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
#Linux sz-exa-cpu-2 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker 24.0.5
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by T-Lakshmi** [comment]
@Xiaolei1091058519 
Can you please describe the issue in primary language(English)?

**Comment by Xiaolei1091058519** [comment]
The cluster version is version 1.22.5-00. Upgrade the kubelet version of one of the nodes to version 1.23.17-00. According to the instructions in the official documentation, the kubelet version cannot be higher than the kube-apiserver version (1.22.5-00). But currently my node can create pod resources normally. There are no exceptions in the node kubelet logs.

**Comment by Xiaolei1091058519** [comment]
The cluster version is version 1.22.5-00. Upgrade the kubelet version of one of the nodes to version 1.23.17-00. According to the instructions in the official documentation, the kubelet version cannot be higher than the kube-apiserver version (1.22.5-00). But currently my node can create pod resources normally. There are no exceptions in the node kubelet logs.

**Comment by HirazawaUi** [comment]
github issue is not the right place for support requests.

You can post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close
