### ISSUE TITLE
Unable to deploy 1.20.0

### ISSUE THREAD

**Issue by prawen** [kubernetes/kubernetes#124727]
### What happened?

On RHEL, tried to deploy 1.20.0
But unable to fetch packages
`failed to download metadata for repo 'kubernetes': cannot download repomd.xml: cannot download repodata/repomd.xml: all mirrors were tried`

### What did you expect to happen?

I expected the packages to be deployed. Later I read https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/ and understand that legacy packages are removed and I can install only from version 1.24

But I'm in need to install 1.20

Please let me know the possible options. I always used 1.20 and deployed using kubeadm on Ubuntu and RHEL

### How can we reproduce it (as minimally and precisely as possible)?

Install 1.20

### Kubernetes version

1.20

### Cloud provider

Self managed

### OS version

RHEL 8

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pranav-pandey0804** [comment]
Support channels are generally preferred for these kind of issues .
Please refer to - https://git.k8s.io/kubernetes/SUPPORT.md

**Comment by HirazawaUi** [comment]
github issue is not the right place for support requests.

You can post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close
