### ISSUE TITLE
Archive legacy-cloud-providers when 1.30 goes out of support

### ISSUE THREAD

**Issue by carlory** [kubernetes/kubernetes#124771]
After https://github.com/kubernetes/kubernetes/pull/124519 and https://github.com/kubernetes/kubernetes/pull/124767 were merged, this repo won't get any update once release 1.30 becomes unsupported.

Related file: https://github.com/kubernetes/kubernetes/blob/master/staging/publishing/rules.yaml#L2291

/assign @dims @carlory 

End of Life:  https://kubernetes.io/releases/patch-releases/#support-period
```[tasklist]
### Tasks
- [x] Redo "remove legacycloudproviders from staging" when https://github.com/kubernetes/publishing-bot/issues/433 is resolved
- [ ] Remove legacycloudproviders staging rule from https://github.com/kubernetes/test-infra/blob/ae2d6ba397a883a3e968aa2a816618607b673c29/config/prow/config.yaml#L431-L435
```

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/124767

**Comment by dims** [comment]
/close

already taken care of!
