### ISSUE TITLE
[Failing Test] [sig-cloud-provider-gcp] Provider does not support InstanceGroups

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#124748]
### Which jobs are failing?

master-informing:
- [gce-cos-master-serial](https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial)

### Which tests are failing?

- Kubernetes e2e suite.[It] [sig-autoscaling] DNS horizontal autoscaling [Serial] [Slow] [KubeUp] kube-dns-autoscaler should scale kube-dns pods when cluster size changed
- Kubernetes e2e suite.[It] [sig-cloud-provider-gcp] Nodes [Disruptive] Resize [Slow] should be able to add nodes
- Kubernetes e2e suite.[It] [sig-cloud-provider-gcp] Nodes [Disruptive] Resize [Slow] should be able to delete nodes
- Kubernetes e2e suite.[It] [sig-cloud-provider-gcp] [Disruptive] NodeLease NodeLease deletion node lease should be deleted when corresponding node is deleted

### Since when has it been failing?

After https://github.com/kubernetes/kubernetes/pull/124519

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

### Reason for failure (if possible)

```
provider does not support InstanceGroups
```

### Anything else we need to know?

Support for gce instance groups was removed, so these tests need to be either updated (To test some other functionality) or removed. 

### Relevant SIG(s)

/sig cloud-provider-gcp

**Comment by pacoxu** [comment]
> After #124519

@dims @carlory

**Comment by aojea** [comment]
These tests has to be refactored or migrated

**Comment by Vyom-Yadav** [comment]
@kubernetes/sig-cloud-provider Can someone ptal and assign this issue to someone. Thanks!

**Comment by elmiko** [comment]
hey folks, just ack'ing that i've seen this issue. i will start to investigate but could probably use assistance from @andrewsykim

**Comment by elmiko** [comment]
discussing at the sig cloud provider meeting today, we'd like to investigate the scope fuirther.

/assign @cheftako

**Comment by cartermckinnon** [comment]
FWIW, we removed the InstanceGroups impl from cloud-provider-aws as well -- +1 for removing these tests or breaking them out.

**Comment by pacoxu** [comment]
After https://github.com/kubernetes/kubernetes/pull/125153 was merged, `Kubernetes e2e suite.[It] [sig-autoscaling] DNS horizontal autoscaling [Serial] [Slow] [KubeUp] kube-dns-autoscaler should scale kube-dns pods when cluster size changed` is not triggered in this test.


For other 3 test: In https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1812584966039539712, all are skipped now.

- Kubernetes e2e suite: [It] [sig-cloud-provider-gcp] [Disruptive] NodeLease NodeLease deletion node lease should be deleted when corresponding node is deleted
- -  Reason: skipped
- Kubernetes e2e suite: [It] [sig-cloud-provider-gcp] Nodes [Disruptive] Resize [Slow] should be able to delete nodes
- -  Reason: skipped
- Kubernetes e2e suite: [It] [sig-cloud-provider-gcp] Nodes [Disruptive] Resize [Slow] should be able to add nodes
- -  Reason: skipped

I suppose that we can close this now.

**Comment by aojea** [comment]
/close

yep, this is green https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial
