### ISSUE TITLE
kubectl cp a file from a Windows Pod to Windows 11 localhost failed

### ISSUE THREAD

**Issue by GoingMyWay** [kubernetes/kubernetes#124781]
### What happened?

I was trying to cp a from a Windows Pod to the Windows localhost. But it failed.

```
kubectl.exe cp --kubeconfig .\kubconfig -n namespace-win pod-20240509-120334-779546rrfsc:C:\\data\\0509-1065.log 0509-1065.log
```

It showed

```
tar: Removing leading drive letter from member names
error: tar contents corrupted
```

### What did you expect to happen?

I want to copy the file to the localhost.

### How can we reproduce it (as minimally and precisely as possible)?

Windows 11 localhost
Windows Pod.

### Kubernetes version

<details>

```console
$(powershell) kubectl version
# paste output here

Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Unable to connect to the server: dial tcp 127.0.0.1:6443: connectex: No connection could be made because the target machine actively refused it.
```
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here

BuildNumber  Caption                      OSArchitecture  Version
22621        Microsoft Windows 11 Professional  64-bit          10.0.22621
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tamilselvan1102** [comment]
Try this way
kubectl.exe cp --kubeconfig .\kubconfig -n namespace-win pod-20240509-120334-779546rrfsc:C:\\data\\0509-1065.log 
./0509-1065.log

**Comment by GoingMyWay** [comment]
> Try this way kubectl.exe cp --kubeconfig .\kubconfig -n namespace-win pod-20240509-120334-779546rrfsc:C:/data/0509-1065.log ./0509-1065.log

It failed. It shows
```
tar: Removing leading drive letter from member names
error: tar contents corrupted
```

**Comment by brianpursley** [comment]
I think you might be running into this:
https://github.com/kubernetes/kubernetes/blob/6e0ece85c49462c40221cb4e322197dbbcdc8fd4/staging/src/k8s.io/kubectl/pkg/cmd/cp/cp.go#L497-L504

This is probably the cause:
```
tar: Removing leading drive letter from member names
```

Is there a way you can do this without referencing the drive letter, like maybe this way?
See comments here for some ideas:
https://github.com/kubernetes/kubectl/issues/1225#issuecomment-1193374558
https://github.com/kubernetes/kubectl/issues/1225#issuecomment-1156576538

I wonder if something like this would work...
```
kubectl.exe cp --kubeconfig .\kubconfig -n namespace-win pod-20240509-120334-779546rrfsc:\\.\c\\data\0509-1065.log 0509-1065.log
```

**Comment by GoingMyWay** [comment]
> I think you might be running into this:
> 
> https://github.com/kubernetes/kubernetes/blob/6e0ece85c49462c40221cb4e322197dbbcdc8fd4/staging/src/k8s.io/kubectl/pkg/cmd/cp/cp.go#L497-L504
> 
> This is probably the cause:
> 
> ```
> tar: Removing leading drive letter from member names
> ```
> 
> Is there a way you can do this without referencing the drive letter, like maybe this way? See comments here for some ideas: [kubernetes/kubectl#1225 (comment)](https://github.com/kubernetes/kubectl/issues/1225#issuecomment-1193374558) [kubernetes/kubectl#1225 (comment)](https://github.com/kubernetes/kubectl/issues/1225#issuecomment-1156576538)
> 
> I wonder if something like this would work...
> 
> ```
> kubectl.exe cp --kubeconfig .\kubconfig -n namespace-win pod-20240509-120334-779546rrfsc:\\.\c\\data\0509-1065.log 0509-1065.log
> ```

@brianpursley 

I tried it and it showed the following error:

```
tar: : Couldn't visit directory: No such file or directory
tar: Error exit delayed from previous errors.
```
or 
```
tar: 6.0.1: Couldn't visit directory: No such file or directory
tar: Error exit delayed from previous errors.
```

**Comment by brianpursley** [comment]
Gotta get the slashes right.  Your original path had double-backslashes and I think I skipped removing one of them.  The `\\` before the `.` is supposed to be double though (Windows :man_shrugging:)

Try this:
```
kubectl.exe cp --kubeconfig .\kubconfig -n namespace-win pod-20240509-120334-779546rrfsc:\\.\c\data\0509-1065.log 0509-1065.log
```

Otherwise, I'm out of ideas.

**Comment by GoingMyWay** [comment]
> Gotta get the slashes right. Your original path had double-backslashes and I think I skipped removing one of them. The `\\` before the `.` is supposed to be double though (Windows 🤷‍♂️)
> 
> Try this:
> 
> ```
> kubectl.exe cp --kubeconfig .\kubconfig -n namespace-win pod-20240509-120334-779546rrfsc:\\.\c\data\0509-1065.log 0509-1065.log
> ```
> 
> Otherwise, I'm out of ideas.

@brianpursley Still the same error. Thanks. It is not easy to use k8s on Windows.

**Comment by jsturtevant** [comment]
Can you try:

```
kubectl.exe cp --kubeconfig .\kubconfig -n namespace-win pod-20240509-120334-779546rrfsc:/data/0509-1065.log 0509-1065.log
```

Agree that this is more difficult than it should be

**Comment by fabiohaertel** [comment]
Did you find a solution? I'm kind of facing a similar issue.

If I do it like this:

`kubectl -n ns cp ns/my-service-agent-22g6w:\app\app2.txt b.txt`

The file is copied from c:/app/app2.txt (source pod) to b.txt

But if I try to pass a drive letter:

`kubectl -n ns cp ns/my-service-agent-22g6w:c:\app\app2.txt b.txt`

It doesnt work. I've tried a lot of different ways but it seems like there's no way to pass a drive letter.
Thanks

**Comment by GoingMyWay** [comment]
> Did you find a solution? I'm kind of facing a similar issue.
> 
> If I do it like this:
> 
> `kubectl -n ns cp ns/my-service-agent-22g6w:\app\app2.txt b.txt`
> 
> The file is copied from c:/app/app2.txt (source pod) to b.txt
> 
> But if I try to pass a drive letter:
> 
> `kubectl -n ns cp ns/my-service-agent-22g6w:c:\app\app2.txt b.txt`
> 
> It doesnt work. I've tried a lot of different ways but it seems like there's no way to pass a drive letter. Thanks

@fabiohaertel  Hi, I have not found a solution.

**Comment by catmanjan** [comment]
Will this reopen if I comment?
