### ISSUE TITLE
Change EvaluatedNodes to count Nodes that reach Filter phase only

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#124705]
Currently, `EvaluatedNodes` contains the number of nodes that filtered out by PreFilterResult and Filter plugins.
But, before #119779, actually it only contains Nodes reach Filter plugins, which is actually more useful than the current state.

This issue aims to bring back the previous `EvaluatedNodes`.

ref: https://github.com/kubernetes/kubernetes/pull/119779#discussion_r1589213337
/cc @alculquicondor 
/sig scheduling
/kind feature

**Comment by AxeZhan** [comment]
/assign
I'll take a look recently

**Comment by alculquicondor** [comment]
FYI #124709
