### ISSUE TITLE
disable events?

### ISSUE THREAD

**Issue by tooptoop4** [kubernetes/kubernetes#124836]
### What would you like to be added?

looking at kubectl events I see things like "message": "Started container bla" with "userAgent": "kubelet" and "involvedObject" "kind": "Pod"

is there any config option to prevent these events being sent?

### Why is this needed?

etcd can fill up

**Comment by pacoxu** [comment]
kube-apiserver default event ttl is 1h. So etcd will not be filled up by events unless the recent 1 hour events is with a too large amount.
```
`--event-ttl` duration     Default: 1h0m0s
 Amount of time to retain events.
```
Another solution is to use separated etcd for events. https://openai.com/index/scaling-kubernetes-to-2500-nodes/ openai blog also include the `etcd-servers-overrides` flag usage. With this solution, events are saved separately.

```
--etcd-servers-overrides strings

  | Per-resource etcd servers overrides, comma separated. The individual override format: group/resource#servers, where servers are URLs, semicolon separated. Note that this applies only to resources compiled into this server binary.
```

**Comment by tooptoop4** [comment]
@pacoxu can i put ttl as 0? really not interested in the events

**Comment by pacoxu** [comment]
You may set it to a quite small duration IIUC.

> Zero means no TTL, not expire immediately.

https://github.com/kubernetes/kubernetes/blob/48dbcf641e34e05a5bc6ef0dcb6558b2303fd168/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L1435-L1438

**Comment by neolit123** [comment]
/kind support
/close

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
