### ISSUE TITLE
scheduler_perf: Allow each test case to specify its timeout

### ISSUE THREAD

**Issue by utam0k** [kubernetes/kubernetes#124827]
/kind feature
/sig scheduling

# what

Allow each test case to specify its timeout. Now, it is specified 30 minutes as hard coding.
https://github.com/kubernetes/kubernetes/blob/99a8a6fe258a456d51dddd3dec16d168d94e4eb1/test/integration/scheduler_perf/scheduler_perf.go#L759-L760

# why

I admit that 30 minutes is enough for the default scheduler with the in-tree scheduler plugins, but scheduler_perf is also helpful for other schedulers with outside scheduler plugins. In that case, more than 30 minutes might be required to complete a test case.

**Comment by utam0k** [comment]
@kubernetes/sig-scheduling-approvers I'd be happy to contribute to this issue if it is acceptable.

**Comment by kerthcet** [comment]
User case is first, do you have any real case here.

**Comment by sanposhiho** [comment]
Agree with @kerthcet. 
Even if there's a usecase (let's say using ~1 hour) actually, could we just extend the global timeout to 1 hour? I don't see any necessity of per-test timeout.

**Comment by utam0k** [comment]
> User case is first, do you have any real case here.

It's very important. Let me share my experience. Unfortunately, I know of a scheduler with fairly poor throughput. That is like an order of magnitude slower throughput. For example, a co-scheduling plugin would be something that could significantly reduce throughput. However, we would like to verify throughput and deadlock on a large number of nodes (possibly an endurance test). In this case, I think scheduler-perf is currently appropriate. However, it will take more than 30 minutes. If preemption is also included, there is an extra possibility of this.

> Additionally to say, even if there's a usecase (let's say using ~1 hour) actually, could we just extend the global timeout to 1 hour? I don't see any necessity of per-test timeout.

Certainly, this could be the case. However, in the case of `fast` label, for example, it is expected to fail quickly. In this case, it seems a bit wasteful to wait an hour for a deadlock or something

@kerthcet @sanposhiho Given your extensive experience, I would appreciate hearing your perspective. Could you please share your thoughts? 🙏

**Comment by sanposhiho** [comment]
Even if the scheduler is 10 times slower (= 30 pods/s throughput), 
the scheduler can handle 54000 scheduling cycles within 30 min theoretically.
Did your test really **_actually_** hit this 30 min timeout? It sounds like too slow though (as long as you used an appropriate sized test case), even if your test involves preemption.

**Comment by utam0k** [comment]
> Did your test actually get failed by this 30 min timeout?

No, I didn't. It's fair to reopen this when I get actually this situation. Thanks for your input.
