### ISSUE TITLE
 Linux 6.6 EEVDF scheduler on Kubernetes: openat2 /sys/fs/cgroup/kubepods.slice/cpu.weight: no such file or directory

### ISSUE THREAD

**Issue by chenk008** [kubernetes/kubernetes#124879]
### What happened?

Linux 6.6 comes with a new job scheduler called EEVDF (Earliest Eligible Virtual Deadline First), replacing the old CFS.

The kubelet/containerd failed to create cgroup

### What did you expect to happen?

Kubelet/containerd is compatible with linux EEVDF scheduler

### How can we reproduce it (as minimally and precisely as possible)?

Run kubernetes on Ubuntu 24.04 LTS

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: v1.28.3-aliyun.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-aliyun.1
```

</details>

### Cloud provider

<details>
Aliyun
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chenk008** [comment]
Mixed use cgroupv1 and cgroupv2

**Comment by therealak12** [comment]
@chenk008 What do you mean by mixed use of cgroupv1 and cgroupv2? How can they be mixed use?
