### ISSUE TITLE
[Failing Test] UserNamespacesSupport feature gate kernel version requirements should not apply generally

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#124834]
This is breaking the kind job that monitors the state of a cluster with alpha features enabled 

https://testgrid.k8s.io/sig-testing-kind#kind-master-alpha-beta

The kubelet fails to start https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kind-alpha-beta-features/1789720580090499072/artifacts/kind-control-plane/kubelet.log

> May 12 18:23:54 kind-control-plane kubelet[299]: E0512 18:23:54.927628     299 run.go:72] "command failed" err="failed to run Kubelet: failed to create kubelet: the kernel version (5.15.0) is incompatible with the UserNamespacesSupport feature gate, which needs 6.3 as a minimum kernel version"

If I understand the feature correctly, the enablement of the feature gate does not necessary means that kernel version is required.
It seems the feature gate is being used as a flag that is incorrect, as if this graduates it will be always enabled, and we can not require `UserNamespacesSupportKernelVersion` for ALL the cluster

@dims @AkihiroSuda can you please relax this validation to check the kernel version supported ONLY when the feature is actually used? or emit a warning, I'm not familiar enough with the feature

/cc @liggitt

_Originally posted by @aojea in https://github.com/kubernetes/kubernetes/pull/124731#discussion_r1597725753_

**Comment by dims** [comment]
I am supportive @aojea
