### ISSUE TITLE
[Failing Test] multi ci gce-cos-k8sbeta-*

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#124861]
### Which jobs are failing?

https://testgrid.k8s.io/sig-release-1.30-blocking#gce-cos-k8sbeta-alphafeatures
https://testgrid.k8s.io/sig-release-1.30-blocking#gce-cos-k8sbeta-default
https://testgrid.k8s.io/sig-release-1.30-blocking#gce-cos-k8sbeta-ingress
https://testgrid.k8s.io/sig-release-1.30-blocking#gce-cos-k8sbeta-reboot

### Which tests are failing?

kubetest.IsUp

### Since when has it been failing?

05-06

### Testgrid link

https://testgrid.k8s.io/sig-release-1.30-blocking#gce-cos-k8sbeta-reboot

### Reason for failure (if possible)

```
Specify --start=72893 in the next get-serial-port-output invocation to get only the new output starting from here.
/usr/bin/scp: /var/log/cluster-autoscaler.log*: No such file or directory
/usr/bin/scp: /var/log/fluentd.log*: No such file or directory
/usr/bin/scp: /var/log/kubelet.cov*: No such file or directory
/usr/bin/scp: /var/log/startupscript.log*: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Dumping logs from nodes locally to '/logs/artifacts'
```
{  error during ./hack/e2e-internal/e2e-status.sh: exit status 1}

**Comment by pacoxu** [comment]
Is it related to https://github.com/kubernetes/kubernetes/pull/124519?

**Comment by aojea** [comment]
it is passing now
