### ISSUE TITLE
Kubectl auth can-i doesn't know about the `approve` verb

### ISSUE THREAD

**Issue by raesene** [kubernetes/kubernetes#124880]
**What happened**:

If you use `kubectl auth can-i` to test whether a user can approve certificate signing requests, you get a response indicating that `approve` is not a valid verb

```bash
kubectl auth can-i approve certificatesigningrequests.certificates.k8s.io
Warning: resource 'certificatesigningrequests' is not namespace scoped in group 'certificates.k8s.io'

Warning: verb 'approve' is not a known verb
```

An example of the `approve` verb being used can be seen [here](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#approval-rejection-kubectl)

**What you expected to happen**:

`approve` should be recognized as a valid verb on `certificatesigningrequest` objects.

**How to reproduce it (as minimally and precisely as possible)**:
Run

```bash
kubectl auth can-i approve certificatesigningrequests.certificates.k8s.io
```

**Anything else we need to know?**:

I think that `approve` needs to be added to the kubectl auth can-i code [here](https://github.com/kubernetes/kubectl/blob/514f46729f82412dd9cc41f206058bc4ae9b62b0/pkg/cmd/auth/cani.go#L106)

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by ah8ad3** [comment]
This will work even without adding verb there, adding verb just removes the warning. Submitted a PR to add that.
/assign
