### ISSUE TITLE
[Failing Test] ec2-master-scale-performance (kubetest2.Down)

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#124951]
### Which jobs are failing?

master-informing:
- ec2-master-scale-performance

### Which tests are failing?

kubetest2.Down

### Since when has it been failing?

05/07

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#ec2-master-scale-performance

### Reason for failure (if possible)

```
E0519 09:00:49.058855   57018 simple_test_executor.go:396] Resource cleanup error: [timed out waiting for the condition
...
instance:i-02443c4c5d2c921fa	error deleting resources, will retry: error terminating instances: operation error EC2: TerminateInstances, exceeded maximum number of attempts, 3, https response error StatusCode: 429, RequestID: 85e73038-e02b-4864-8086-4e99b4102d6a, api error RequestLimitExceeded: Request limit exceeded.
...
Error: wait time exceeded during resources deletion
```

### Anything else we need to know?

Error Terminating EC2 instances

### Relevant SIG(s)

/sig k8s-infra

**Comment by Vyom-Yadav** [comment]
cc @BenTheElder @ameukam @dims

**Comment by dims** [comment]
last thing we tried on kops was this: https://github.com/kubernetes/kops/pull/16580

**Comment by hakman** [comment]
Looks like ^^^ worked. 😄
Today's test passed, but let's wait a few more days to be sure.

**Comment by Vyom-Yadav** [comment]
The test is green. Thanks!

/close
