### ISSUE TITLE
EC2 + GCE GPU CI Jobs not running any test cases

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#124950]
### Which jobs are failing?

master-blocking
- gce-device-plugin-gpu-master

### Which tests are failing?

kubetest.Up

### Since when has it been failing?

05/17

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

### Reason for failure (if possible)

```
ERROR: (gcloud.compute.instance-groups.managed.create) Could not fetch resource:
 - The resource 'projects/220512457637/zones/us-west1-b/acceleratorTypes/nvidia-tesla-k80' was not found
ERROR: (gcloud.compute.instance-groups.managed.wait-until) Some requests did not succeed:
 - The resource 'projects/k8s-infra-e2e-boskos-gpu-01/zones/us-west1-b/instanceGroupManagers/bootstrap-e2e-minion-group' was not found
```
```
Waiting for 2 ready nodes. 1 ready nodes, 1 registered. Retrying.
Using image: cos-109-17800-218-26 from project: cos-cloud as master image
Using image: cos-109-17800-147-22 from project: cos-cloud as node image
Detected 1 ready nodes, found 1 nodes out of expected 2. Your cluster may not be fully functional.
```

### Relevant SIG(s)

/sig k8s-infra

**Comment by Vyom-Yadav** [comment]
cc @BenTheElder @dims @ameukam

**Comment by BenTheElder** [comment]
Note that while the job is "green" after https://github.com/kubernetes/test-infra/pull/32635 we are not running `[Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests` anymore and the Windows test is skipped so ... no real tests are run.

https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master&show-stale-tests=&width=5

This issue is a sub-variant of https://github.com/kubernetes/test-infra/issues/32242

**Comment by aojea** [comment]
It seems fixed https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

**Comment by BenTheElder** [comment]
> It seems fixed https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

It's not, see above https://github.com/kubernetes/kubernetes/issues/124950#issuecomment-2121211252

The `[Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests` is no longer even in stale tests because it hasn't run in so long now, but it was yesterday as a stale test, we're running no actual GPU tests currently.

**Comment by BenTheElder** [comment]
I don't even seen `[Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests` in the skipped results


The only matching test is for windows ... asking if something changed with the test cases in SIG Node slack
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1795477868910743552/artifacts/junit_01.xml

**Comment by BenTheElder** [comment]
The test cases were all deleted ... https://github.com/kubernetes/kubernetes/commit/bf268f02a3567c1af29199c27a7cf61cca494b2d#diff-7629c065680da0396ef2e8d190ce7cdd1dbf2c336f99c22ec543a4be61d74ccd

**Comment by BenTheElder** [comment]
**NOTE: This also impacts the EC2 Job which is no longer running any test cases.**

The GCE job is running and "passing" same as the ec2 job now ... neither of which run any tests.

/retitle EC2 + GCE GPU CI Jobs not running any test cases



See an old run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-device-plugin-gpu/1781225142752382976

(ran: `Kubernetes e2e suite: [It] [sig-scheduling] [Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests`, 8 tests passed, the other "tests" are just cluster bringup / test runner etc)

Current:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-device-plugin-gpu/1795464027577520128

(7 "tests" passed, none of which are actual e2e tests)

**Comment by aojea** [comment]
😅

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-release-1.30-blocking#gce-device-plugin-gpu-1.30
keeps failing

**Comment by BenTheElder** [comment]
Yes, I think the job is coming up but not the driver install or device plugin. We need to add more log dump there, I've been discussing a bit with dims what we should do about the test removal in #sig-node: https://kubernetes.slack.com/archives/C0BP8PW9G/p1716914276819719?thread_ts=1716913485.823089&cid=C0BP8PW9G

**Comment by BenTheElder** [comment]
Talked to @elfinhe this morning about the driver install.

**Comment by dims** [comment]
FYI https://github.com/kubernetes/kubernetes/issues/122828 documents that `[Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests` is getting dropped!

**Comment by BenTheElder** [comment]
Going to revisit test cases once we figure out the driver install issue on 1.30 with existing test cases on that branch. There are WIP PRs for this and I'm in contact with the team supporting us on the driver problems, providing upstream CI pointers. https://github.com/kubernetes/kubernetes/pull/125208 / https://github.com/kubernetes/kubernetes/pull/125206

**Comment by AnishShah** [comment]
Notes from sig-node CI meeting:

- This is not release blocking

**Comment by BenTheElder** [comment]
For the GPU tests, we have a driver install fix for 1.30 branch now at https://github.com/kubernetes/kubernetes/pull/125208
We will need to backport to other branches, forward port to master, and then re-introduce device plugin GPU tests to master.

**Comment by BenTheElder** [comment]
I intend to follow up more here soon, well ahead of 1.31 freeze.

**Comment by BenTheElder** [comment]
Update: CI is actually passing on 1.28 and 1.27 (???)

https://testgrid.k8s.io/google-gce#gce-device-plugin-gpu-1.27
https://testgrid.k8s.io/google-gce#gce-device-plugin-gpu-1.28

But not on 1.29:

https://testgrid.k8s.io/google-gce#gce-device-plugin-gpu-1.29

It is passing on 1.30:

https://testgrid.k8s.io/google-gce#gce-device-plugin-gpu-1.30

We only updated the driver install for 1.31+, and we only have the AWS job for 1.31+ I think??

For 1.31+ we're still not really running any tests on AWS or GCE, but we appear to be as expected on 1.30 and earlier.

... it's strange that only 1.29 is broken, aside from the lack of tests in 1.31+

**Comment by BenTheElder** [comment]
Presubmit passes on 1.29 but does not appear to run any test cases, implying it "passes" but skips the test because the driver didn't come up.

Future tests probably shouldn't self-skip and should instead rely only on the feature tag/label.

**Comment by BenTheElder** [comment]
Confirmed that we need the driver update for 1.29 to get tests actually running and passing and should do it for 1.28 as well.

https://github.com/kubernetes/kubernetes/pull/126275 and https://github.com/kubernetes/kubernetes/pull/126179 to cherry pick to remaining active branches

After that still leaves tests for 1.31+

**Comment by BenTheElder** [comment]
/help
/unassign

We have the driver install working for all supported branches but we need some test cases for master/ 1.31+

Ideally as a starting point they should run a simple relatively portable workload that just proves that we can use device-plugin to attach a functioning GPU to a pod.

You can look at the tests removed in https://github.com/kubernetes/kubernetes/pull/124519 / copied in https://github.com/kubernetes/cloud-provider-gcp/pull/706 as a starting point, but those tests are not suitable as-is, we cannot call into cloud-provider-gcp and shouldn't be attempting things like node reboot, not to get basic coverage back.

This is NOT a good-first issue, however it would be good for an experienced SIG Node contributor.

**Comment by kannon92** [comment]
Looking at this issue, how does one test with a GPU? Do we have a image config that can use a GPU from GCP?

**Comment by dims** [comment]
@kannon92 you can check the 3 CI job definitions that use nvidia today - you end up specifying the node image and then the test harness installs the nvidia drivers using a daemonset

- https://cs.k8s.io/?q=nvidia-driver-installer&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra 
- https://cs.k8s.io/?q=GPUDevicePlugin&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes

The combination of the node image + driver version is very finicky which is what this issue was all about ...

**Comment by BenTheElder** [comment]
If you look at the PRs referenced for the GPU test cases they have container images / pods that use the attached GPU. Those test cases also did a number of things we don't need for minimal coverage and can't do from this repo anymore like rebooting GCE nodes to test that behavior.

**Comment by ameukam** [comment]
@kannon92 GPUs are provided for any GCP project. You should be able to check with your account. 

```bash
gcloud compute accelerator-types list
```

**Comment by drewhagen** [comment]
The release cycle for 1.32 starts today. Since this is still open, I will carry it over to the latest milestone.

I'm curious if we can reduce the amount of flakes we are tracking.
@BenTheElder I see that you've mentioned this issue in a PR that was merged. Will that PR fix this issue? Do we want to keep observing?
Thanks!

**Comment by BenTheElder** [comment]
> Will that PR fix this issue? Do we want to keep observing?

We fixed being able to bring up clusters on GCE with the driver working.

However in the meantime all of the GPU test cases were dropped during cloud provider removal, so both the GCE and EC2 GPU CI jobs run no meaningful test cases, someone would need to develop new test cases that do not call into the cloud provider SDKs.

I think we need to track this, at the very least we should shut down these jobs at some point, cc @dims.

**Comment by dims** [comment]
AWS ci job now has some sanity tests to exercise the nvidia GPU

<img width="703" alt="image" src="https://github.com/user-attachments/assets/48d394a3-d42c-4000-be06-7ee3e287c1e7">

**Comment by dims** [comment]
cherry pick for 1.31 has landed - https://github.com/kubernetes/kubernetes/pull/127462

/close

**Comment by BenTheElder** [comment]
It looks like GCE as well now? https://github.com/kubernetes/kubernetes/pull/127456#issuecomment-2359683644

So we're back to having multi-vendor coverage for device plugin, particularly nvidia. Thanks @dims!
