### ISSUE TITLE
Ephemeral volume scheduling problems

### ISSUE THREAD

**Issue by kangzhiqin** [kubernetes/kubernetes#124907]
### What would you like to be added?

I have two ephemeral  volumes, one that requires 100M of memory and one that requires 43G of memory.
![image](https://github.com/kubernetes/kubernetes/assets/143382668/048d69d4-6b03-4038-80b7-e73fefa57d82)

After the 100 MB volume is successfully scheduled, only 42 GB memory is available on the node. As a result, the second volume fails to be created, and the pod fails to be scheduled.
![image](https://github.com/kubernetes/kubernetes/assets/143382668/b17d5771-33ab-480d-b5db-8b66511c69eb)

However, other nodes in the cluster have sufficient space.

### Why is this needed?

Is there a good way to solve this problem?

**Comment by xing-yang** [comment]
@kangzhiqin as a workaround, can you combine the two volumes and use subpath for different mounts?
Does localcsi driver support storage capacity tracking?  If it relies on that feature, enhancement is still needed as it currently only supports one PVC per Pod.

**Comment by kangzhiqin** [comment]
> @kangzhiqin as a workaround, can you combine the two volumes and use subpath for different mounts? Does localcsi driver support storage capacity tracking? If it relies on that feature, enhancement is still needed as it currently only supports one PVC per Pod.

Thank you for your reply. I'll think about this solution.

**Comment by kangzhiqin** [comment]
> @kangzhiqin as a workaround, can you combine the two volumes and use subpath for different mounts? Does localcsi driver support storage capacity tracking? If it relies on that feature, enhancement is still needed as it currently only supports one PVC per Pod.

**Comment by kangzhiqin** [comment]
Will volumes be created in order of size? For example, creating 43 GB volumes first and then 100 MB volumes can avoid this problem.

**Comment by kangzhiqin** [comment]
The code should be on line 235
https://github.com/kubernetes/kubernetes/blob/e67f889edc4ab278028f6cffd2501bc90a0defcf/pkg/controller/volume/ephemeral/controller.go#L213-L243
