### ISSUE TITLE
last applied annotations are not getting updated

### ISSUE THREAD

**Issue by jainpratik163** [kubernetes/kubernetes#124940]
### What happened?

i was trying to update configmap and after editing successfully configmap annotation didn't update with the last values. still, it holds 1st-time data only.
basically, I am trying to write one code to capture if someone changes anything in CM and we can identify it.

and also in some configmap I am not able to find last-applied annotation.

### What did you expect to happen?

annotation should update

### How can we reproduce it (as minimally and precisely as possible)?

create cm with below 
`apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config-env-file
data:
  allowed: '"true"'
  enemies: aliens
  lives: "31"`

and now edit this cm game-config-env-file and let say change any values last-applied annotation is not getting chnaged

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: v1.28.8-eks-ae9a62a
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8-eks-adc7111
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
try opening a thread at the support channels like discuss.k8s.io first.
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by jainpratik163** [comment]
dont this issue as last applied annotation is not getting updated whenever configmaps are been updated.
