### ISSUE TITLE
Enabling `publishNotReadyAddresses` causes proxy to direct traffic to NotReady pods.

### ISSUE THREAD

**Issue by the-redshift** [kubernetes/kubernetes#124914]
### What happened?

Documentation states that enabling `publishNotReadyAddresses` will cause DNS records to appear for pods, even if `NotReady`. Documentation does not state that enabling this flag will cause incoming traffic to be directed to pods that are `NotReady`.

### What did you expect to happen?

I expected DNS records to be created, nothing beyond that.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create HTTP Server deployment with initContainer -> `sleep 30`
2. Create service for that deployment with `publishNotReadyAddresses` set to `true`
3. Continiously call HTTP Server
4. Scale HTTP Server to 10 Replicas
5. Observe incoming errors

### Anything else we need to know?

It can be easily fixed by changing condition for building topology from `isReady` to `isServing && !isTerminating`.

### Kubernetes version

<details>

```console
$ kubectl version
v1.29.1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> Documentation does not state that enabling this flag will cause incoming traffic to be directed to pods that are `NotReady`.

https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#ready

maybe is not clear, but is the way it works 

/remove-kind bug
/kind documentation

**Comment by the-redshift** [comment]
@aojea - could you elaborate _why_ does it work the way it does? What's the benefit of routing traffic to a Pod that doesn't even has its containers up?

**Comment by aojea** [comment]
> What's the benefit of routing traffic to a Pod that doesn't even has its containers up?

and the DNS? :) 


You are focusing on the behaviors and is important to understand the internals, Services provide discovery via DNS and ClusterIP (L4 load balancers).

Services depend on the EndpointSlices, that represent the set of pods that belong to that Service and their *state*

These Services/EndpointSlices objects have a 1to1 relation and are used by the DNS implementation (commonly CoreDNS) and the Services implementations (commonly kube-proxy) , so both the DNS records and and proxy will do whatever the EndpointSlice says, if it says is ready then it will trust the object.

If we go to the API you have the explanation of this field

https://github.com/kubernetes/kubernetes/blob/5ceb99dc6bae8a3013192439bdbee942d14de190/pkg/apis/core/types.go#L4507-L4516

This is an opt-in feature to deal with very specific behaviors that has side effects as the one you are describing, so the user that wants to use it need to understand this (put a side we could have done differently, this is an v1 API and we need to respect it)... in your description you describe a scenario that will fail as WAI, why any user will choose to do that?

**Comment by the-redshift** [comment]
Hi @aojea,
I appreciate you for taking the time to provide more context in that regard.
I can now see how changing that field would break things.

That comment you've quoted indeed states things clear as day - couldn't find that within the docs though.

Thanks again!
