### ISSUE TITLE
One Node all pods got crashloopbackoff

### ISSUE THREAD

**Issue by Asakaigg** [kubernetes/kubernetes#124903]
### What happened?

Hello 
I  have installed three nodes on my k8s 
one is master node and two nodes are slave node
but one slave node pods works normally but one slave node pods got crashloopback error continously

### What did you expect to happen?

I want to run all pods norml

### How can we reproduce it (as minimally and precisely as possible)?

I have installed self kubernetes on my ubuntu servers. if I add new server to it, it doesn't work 

### Anything else we need to know?

this is just the log from master node 
![image](https://github.com/kubernetes/kubernetes/assets/165806253/2812f5d5-d27c-4462-a522-104d1ab718f9)
this is kubelet log from error node 
![image](https://github.com/kubernetes/kubernetes/assets/165806253/ba1ff7ce-df5f-4219-a526-d8b3da86c717)
this is containerd log from error node
![image](https://github.com/kubernetes/kubernetes/assets/165806253/b4936d4b-e155-405b-9b7c-c009adc1b14b)

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.28.9



### Cloud provider

self hosting

### OS version

ubuntu 22.0.4


### Install tools

docker 
container
kubectl 
helm 


### Container runtime (CRI) and version (if applicable)

containerd

### Related plugins (CNI, CSI, ...) and versions (if applicable)

flannel
![image](https://github.com/kubernetes/kubernetes/assets/165806253/db458c22-8200-4093-8a0d-f94d206d78c2)

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
