### ISSUE TITLE
kubernetes-sigs / scheduler-plugins  go.mod Error 

### ISSUE THREAD

**Issue by Hemang70** [kubernetes/kubernetes#125098]
### What happened?

Trying to create scheduler plugin by referring link: https://github.com/kubernetes-sigs/scheduler-plugins.git 
Getting error while executing "go mod tidy"

go: finding module for package sigs.k8s.io/scheduler-plugins/pkg/generated/applyconfiguration/scheduling/v1alpha1
go: finding module for package sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned/typed/scheduling/v1alpha1
go: finding module for package sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned
go: finding module for package sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/fake
go: finding module for package sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned/scheme
go: finding module for package sigs.k8s.io/scheduler-plugins/pkg/generated/informers/externalversions/internalinterfaces
go: finding module for package sigs.k8s.io/scheduler-plugins/pkg/generated/informers/externalversions/scheduling
go: finding module for package sigs.k8s.io/scheduler-plugins/pkg/generated/informers/externalversions/scheduling/v1alpha1
go: finding module for package sigs.k8s.io/scheduler-plugins/pkg/generated/listers/scheduling/v1alpha1
go: sigs.k8s.io/scheduler-plugins/sigs.k8s.io/scheduler-plugins/pkg/generated/applyconfiguration imports
        sigs.k8s.io/scheduler-plugins/pkg/generated/applyconfiguration/scheduling/v1alpha1: no matching versions for query "latest"
go: sigs.k8s.io/scheduler-plugins/sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned imports
        sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned/typed/scheduling/v1alpha1: no matching versions for query "latest"
go: sigs.k8s.io/scheduler-plugins/sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned/fake imports
        sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned: no matching versions for query "latest"
go: sigs.k8s.io/scheduler-plugins/sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned/fake imports
        sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/fake: no matching versions for query "latest"
go: sigs.k8s.io/scheduler-plugins/sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned/typed/scheduling/v1alpha1 imports
        sigs.k8s.io/scheduler-plugins/pkg/generated/clientset/versioned/scheme: no matching versions for query "latest"
go: sigs.k8s.io/scheduler-plugins/sigs.k8s.io/scheduler-plugins/pkg/generated/informers/externalversions imports
        sigs.k8s.io/scheduler-plugins/pkg/generated/informers/externalversions/internalinterfaces: no matching versions for query "latest"
go: sigs.k8s.io/scheduler-plugins/sigs.k8s.io/scheduler-plugins/pkg/generated/informers/externalversions imports
        sigs.k8s.io/scheduler-plugins/pkg/generated/informers/externalversions/scheduling: no matching versions for query "latest"
go: sigs.k8s.io/scheduler-plugins/sigs.k8s.io/scheduler-plugins/pkg/generated/informers/externalversions/scheduling imports
        sigs.k8s.io/scheduler-plugins/pkg/generated/informers/externalversions/scheduling/v1alpha1: no matching versions for query "latest"
go: sigs.k8s.io/scheduler-plugins/sigs.k8s.io/scheduler-plugins/pkg/generated/informers/externalversions/scheduling/v1alpha1 imports
        sigs.k8s.io/scheduler-plugins/pkg/generated/listers/scheduling/v1alpha1: no matching versions for query "latest"
  

### What did you expect to happen?

no error

### How can we reproduce it (as minimally and precisely as possible)?

How to update mod.go

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
not applicable

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
Not applicable

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
This is the wrong repo, please file issues with https://github.com/kubernetes-sigs/scheduler-plugins for problems with that project.
