### ISSUE TITLE
post-kubernetes-push-image-pause failed to publish version 3.10

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#125099]
pause image was updated in:
https://github.com/kubernetes/kubernetes/pull/125067

but the build failed with:
```
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/wincat-windows-amd64 windows/wincat/wincat.go
reading go.work: /workspace/go.work:3: invalid go version '1.22.0': must match format 1.23
make[1]: *** [Makefile:121: bin/wincat-windows-amd64] Error 1
make[1]: Leaving directory '/workspace/build/pause'
make: *** [Makefile:107: sub-container-registry-windows-amd64-1809] Error 2
```

Please see logs here:
https://storage.googleapis.com/kubernetes-jenkins/logs/post-kubernetes-push-image-pause/1793662199902769152/build-log.txt

**Comment by dims** [comment]
cc @jsturtevant @marosset 

/sig windows

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/125067

**Comment by neolit123** [comment]
> CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/wincat-windows-amd64 windows/wincat/wincat.go

i can't repro locally with go 1.22.
it seems workspace related.

**Comment by dims** [comment]
@neolit123 possibly https://github.com/kubernetes/test-infra/pull/32647 ?

**Comment by BenTheElder** [comment]
/triage accepted

> CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/wincat-windows-amd64 windows/wincat/wincat.go

This probably means we're building without setting up the go environment, which makes sense because our scripts support linux primarily.

We should teach the windows builds to respect toolchain / .go-version / make sure they're using a go version new enough to bootstrap that.

**Comment by dims** [comment]
@BenTheElder Ack, took the opportunity to fix it anyway even if it was not the real culprit.... i am trying `make OUTPUT_TYPE=registry OS=windows ARCH=amd64 OSVERSION=1809 container` which seems to work fine locally as well (gets past the stage where wincat failed to build)

**Comment by BenTheElder** [comment]
The strange part is we should already be running this step inside kube-cross with the expected version, so ...

We can even see in the logs:
```
docker run --rm -u $(id -u):$(id -g) -v $(pwd):/build \
	registry.k8s.io/build-image/kube-cross:v1.31.0-go1.22.3-bullseye.0 \
	/bin/bash -c "\
		cd /build && \
		x86_64-w64-mingw32-gcc -Os -Wall -Werror -static -DVERSION=v3.10- -o bin/pause-windows-amd64 windows/pause.c && \
		x86_64-w64-mingw32-strip  bin/pause-windows-amd64.exe"
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/wincat-windows-amd64 windows/wincat/wincat.go
reading go.work: /workspace/go.work:3: invalid go version '1.22.0': must match format 1.23
```

**Comment by BenTheElder** [comment]
Oh, I see, we're not containerizing all of it.

**Comment by dims** [comment]
@BenTheElder if you start `docker run -it --entrypoint bash gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20230623-56e06d7c18` and git clone k8s, you can see the problem 

```
23a99242e41f:/workspace/kubernetes/build/pause# CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/wincat-windows-amd64 windows/wincat/wincat.go
reading go.work: /workspace/kubernetes/go.work:3: invalid go version '1.22.0': must match format 1.23
```

unfortunately the newest version `gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20240210-bcb4e42f96` also does not work and fails with a slightly different reason (better reason!)
```
721fc0a9976c:/workspace/kubernetes/build/pause# CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/wincat-windows-amd64 windows/wincat/wincat.go
go: ../../go.work requires go >= 1.22.0 (running go 1.21.6; GOTOOLCHAIN=local)
```

**Comment by dims** [comment]
@BenTheElder https://github.com/kubernetes/test-infra/pull/32652 PTAL

**Comment by BenTheElder** [comment]
filed https://github.com/kubernetes/kubernetes/pull/125105 PTAL, this should avoid us depending on the GCB image specifics

**Comment by BenTheElder** [comment]
This is fixed. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-pause/1793743356572995584

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/125108 will also go ahead and pickup the current gcb-gcloud-docker while we're at it
