### ISSUE TITLE
The old pod log file is not deleted from the /var/log/pods/ directory

### ISSUE THREAD

**Issue by Black-max12138** [kubernetes/kubernetes#125079]
### What happened?

In the /var/log/pods/ directory, many old log files are not deleted in a timely manner. As a result, the disk space is used up.
![1709001460262](https://github.com/kubernetes/kubernetes/assets/54977497/e541ec52-d6c4-4b7a-bcb6-f7bc88969d24)

### What did you expect to happen?

I think there should be only 1 old log file in this path.

### How can we reproduce it (as minimally and precisely as possible)?

I don't know how this happened.

### Kubernetes version

<details>

```console
$ kubectl version
# 1.28
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pranav-pandey0804** [comment]
hi @Black-max12138 , thanks for reporting the issue,
could you verify if the `containerLogMaxSize` and `containerLogMaxFiles` settings are correctly configured or not?

**Comment by pranav-pandey0804** [comment]
If these settings are not configured correctly then kubelet may not delete the old log files efficiently because these setting dictate the maximum size each log file can reach before being rotated and the max log files that can be retained !

**Comment by pranav-pandey0804** [comment]
you can also refer to [this](https://kubernetes.io/docs/concepts/cluster-administration/logging/) page for more details !

**Comment by Black-max12138** [comment]
> hi @Black-max12138 , thanks for reporting the issue, could you verify if the `containerLogMaxSize` and `containerLogMaxFiles` settings are correctly configured or not?

`containerLogMaxSize` and `containerLogMaxFiles` are using default values

**Comment by Black-max12138** [comment]
> If these settings are not configured correctly then kubelet may not delete the old log files efficiently because these setting dictate the maximum size each log file can reach before being rotated and the max log files that can be retained !

So what is the possibility of this happening if the parameters are set correctly?

**Comment by tamilselvan1102** [comment]
Generally once the POD is terminated & a new instance is started, the log files associated with the old pod get deleted.

**Comment by jsafrane** [comment]
AFAIK container logs are managed by sig-node, not by sig-storage
/sig node
/remove-sig node

**Comment by tamilselvan1102** [comment]
> hi @Black-max12138 , thanks for reporting the issue, could you verify if the `containerLogMaxSize` and `containerLogMaxFiles` settings are correctly configured or not?

By default, Kubernetes truncates the pod’s container log if it reaches 10 MB. 
if you want to change the file size, you can set through containerLogMaxSize parameter in the kubelet configuration.
These parameters are not related to delete/persist the log file.

**Comment by AnishShah** [comment]
This seems to be WAI since it is set to default value. Please reopen if there are additional questions.

/close
