### ISSUE TITLE
test/e2e/rc.go fails to pull the image when running with Docker v1.8.0rc3

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#12506]
The failed test: "ReplicationController should serve a basic image on each replica with a private image"

```
Failed to pull image "gcr.io/_b_k8s_authenticated_test/serve_hostname:1.1": API error (500): repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
```

Seems like docker does not accept any component starting with an underscore (```_b_k8s_```...).

**Comment by yujuhong** [comment]
I am not sure who maintains our gcr.io buckets, and how to get a new one with a compatible name to replace this.  Add @thockin for suggestions (since he touched the Dockerfile).

**Comment by thockin** [comment]
spoke with Dawn today - I touched it but did not add that weird name.

**Comment by yujuhong** [comment]
@thockin, do you know who has the permission to rename the bucket?

**Comment by dchen1107** [comment]
We want to test docker 1.8.1 for 1.1 release. Let me quickly fix this.

**Comment by dchen1107** [comment]
pr #13747 was merged, closed this issue.
