### ISSUE TITLE
`GOTOOLCHAIN=go1.22.1 make verify WHAT=codegen` fails with error deleting tempdir

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#125010]
### What happened?

While debugging https://github.com/kubernetes/kubernetes/issues/124932 I discovered that setting `GOTOOLCHAIN` causes `make verify WHAT=codegen` @ 765e7ef0d21 (recent master branch commit) to fail on cleanup at the end.

This doesn't happen if you don't set `GOTOOLCHAIN`. It's not immediately apparent why those are related.

### What did you expect to happen?

This make target should not fail on a clean branch with no diff.

### How can we reproduce it (as minimally and precisely as possible)?

set GOTOOLCHAIN to some valid go version and then run `make verify WHAT=codegen`

### Anything else we need to know?

/sig testing release
/triage accepted

### Kubernetes version

765e7ef0d21

### Cloud provider

n/a

### OS version

Linux. ~Debian. But this is happening inside our build container.

### Install tools

n/a

### Container runtime (CRI) and version (if applicable)

docker 20.10.21

### Related plugins (CNI, CSI, ...) and versions (if applicable)

n/a

**Comment by BenTheElder** [comment]
I would guess: we wind up downloading go underneath the tempdir we setup for the script and then there's some non-writeable go toolchain download cache there, or something like that.

**Comment by mauri870** [comment]
That is indeed the case.

Go toolchains are downloaded into `$GOPATH/cache/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64` and the folder is write protected. I will send in a fix.

/assign
