### ISSUE TITLE
Kubernets service not distributing traffic in equally , seeing imbalance in traffic  .   

### ISSUE THREAD

**Issue by uttam-phygitalz** [kubernetes/kubernetes#125013]
### What happened?

We are seeing traffic is not in balancing among  ingress controller replicas when replica count gets higher . 
We have set HPA like 40 as Maximum replicas and when the load test  happen the HPA get triggered and spawn new replicas but the load is not evenly distributed even though resources are available .  . PFB the screenshot . 

<img width="1521" alt="image" src="https://github.com/kubernetes/kubernetes/assets/142709637/a8ab770d-2b0d-4315-a611-08fbf50827c0">

It is deployed in AWS NLB . There is not long-lived connection preset , all are new connections being hit . 

description of ingress 

`│ Labels:                   app=ingress-nginx-external-nlb                                                                                                                                            │
│                           app.kubernetes.io/managed-by=Helm                                                                                                                                             
│ Annotations:              helm.sh/resource-policy: keep                                                                                                                                                 │
                                                                                                                            │
│                           service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags:                                                                                                        │
                  │
│                           service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp                                                                                                            │
│                           service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: true                                                                                                │
│                           service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: 60                                                                                                  │
│                           service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 300                                                                                                     │
│                           service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true                                                                                          │
│                           service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-0116assa519f2f2aa1fe8c                                                                                      │
│                           service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip                                                                                                              │
│                           service.beta.kubernetes.io/aws-load-balancer-type: nlb                                                                                                                        │
│ Selector:                 app=ingress-nginx-external                                                                                                                                                │
│ Type:                     LoadBalancer                                                                                                                                                                  │
│ IP Family Policy:         SingleStack                                                                                                                                                                   │
│ IP Families:              IPv4                                                                                                                                                                          │
│ IP:                       172.20.189.13                                                                                                                                                                 │
│ IPs:                      172.20.189.13                                                                                                                                                                 │
│ LoadBalancer Ingress:     a47c0fada1425caa057592-76e4445441da70fa.elb.us-west-2.amazonaws.com                                                                                                 │
│ Port:                     https  443/TCP                                                                                                                                                                │
│ TargetPort:               443/TCP                                                                                                                                                                       │
│ NodePort:                 https  31411/TCP                                                                                                                                                              │
│ Endpoints:                100.64.165.237:443,100.65.173.35:443,100.64.244.118:443                                                                                                                       │
│ Session Affinity:         None                                                                                                                                                                          │
│ External Traffic Policy:  Local                                                                                                                                                                         │
│ HealthCheck NodePort:     31286                                                                                                                                                                         │
│ Events:                                                                                                                                                                                                 │
│   Type    Reason               Age                    From                Message                                                                                                                       │
│   ----    ------               ----                   ----                -------                                                                                                                       │
│   Normal  UpdatedLoadBalancer  16m (x163 over 2d17h)  service-controller  Updated load balancer with new hosts`

### What did you expect to happen?

The traffic should distributed among all replicas evenly or somewhere near to that .Not like totally imbalanced way . 

### How can we reproduce it (as minimally and precisely as possible)?

Deploy Ingress controllers 
set the HPA for ingress controller ,like min 3 and max 40 . 
perform the load test . 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8-eks-adc7111

### Cloud provider

<details>

</details>

AWS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

Rocky linux / alpine 

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by adrianmoisey** [comment]
Are your pods equally spread across your nodes?

We noticed a similar problem, and our issue was that some nodes had more ingress-nginx pods than others, so each node would distribute the traffic it received amongst the pods hosted on itself.

**Comment by uttam-phygitalz** [comment]
Hi @adrianmoisey  , Yeah could see its spread over different nodes . each node has one replica pod running .

**Comment by adrianmoisey** [comment]
> Hi @adrianmoisey , Yeah could see its spread over different nodes . each node has one replica pod running .

And just to confirm, when you are scaled up (to 40 pods), you have and equal spread of pods to nodes?

**Comment by uttam-phygitalz** [comment]
> > Hi @adrianmoisey , Yeah could see its spread over different nodes . each node has one replica pod running .
> 
> And just to confirm, when you are scaled up (to 40 pods), you have and equal spread of pods to nodes?

Yes correct .. Its being equal spread to nodes .. Each node has one replica running ..

**Comment by aojea** [comment]
You need to test from inside the cluster and from outside, to investigate if is a loadbalancer problem or a kubernetes problem

**Comment by adrianmoisey** [comment]
What does the Service look like? Can you paste a YAML representation of it here?

**Comment by uttam-phygitalz** [comment]
> What does the Service look like? Can you paste a YAML representation of it here?

Service looks okay .. 

`apiVersion: v1
kind: Service
metadata:
  annotations:
    helm.sh/resource-policy: keep
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-0165192f2aa1fe8cc
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  creationTimestamp: "2024-02-18T19:10:42Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: ingress-nginx-external-nlb
    app.kubernetes.io/managed-by: Helm
    bu: cloud
  name: ingress-nginx-external-nlb
  namespace: qa
  resourceVersion: "4809557489"
  uid: 985e1e4e-cb41-4afa-896a-012e40d826dc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.196.247
  clusterIPs:
  - 172.20.196.247
  externalTrafficPolicy: Local
  healthCheckNodePort: 32161
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    nodePort: 31172
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-nginx-external
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a985e1eecbbbt414afa896a012e40d826d-7b200cd7fdc4afef.elb.us-west-2.amazonaws.com`

**Comment by adrianmoisey** [comment]
> externalTrafficPolicy: Local
> internalTrafficPolicy: Cluster

Given that `internalTrafficPolicy` is set to Cluster, I'd assume that Kubernetes would distribute the traffic evenly.

Since `externalTrafficPolicy` is set to Local, it may be the NLB that is causing this behaviour.

I agree with @aojea's suggestion of doing a test inside the cluster. That we it will help eliminate either the cluster to the load balancer.

**Comment by aroradaman** [comment]
/remove-kind bug
(until we are sure etp: local and NLB is not the culprit)

**Comment by shaneutt** [comment]
We discussed this one in the SIG Network meeting today, and it seems we have several open questions. I've assigned myself this just to try and help shepherd it forward, but @uttam-phygitalz it does seem there are some open questions about this above including a desire to see if this is something that might be happening _outside_ the cluster? Please let us know?

/triage needs-information

**Comment by shaneutt** [comment]
Seems like this is getting stale.

/lifecycle stale

Let us know your thoughts on some of the above questions @uttam-phygitalz, or if you need any help or support in this?

**Comment by elmiko** [comment]
we talked about this again at sig cloud--provider today, deferring an acceptance on triage while we wait for more information.

**Comment by aojea** [comment]
/close

last comment from the reporter from May, it can always be reopened if there is more information
