### ISSUE TITLE
Regarding the issue of certificate expiration when accessing links with Https in kubernetes through pod access

### ISSUE THREAD

**Issue by 1569099266** [kubernetes/kubernetes#125130]
### What happened?

![image](https://github.com/kubernetes/kubernetes/assets/46311200/5f7f6d63-c825-47ca-80a0-7784a370f86d)
I curl any link with HTTPS in the ingress nginx controller pod in Kubernetes, and the HTTPS certificate will expire at the same time. However, I have no problem curling on the node, and I have no problem starting an nginx container curl using Docker

### What did you expect to happen?

I curl any link with HTTPS in the ingress nginx controller pod in Kubernetes, and the HTTPS certificate will expire at the same time. However, I have no problem curling on the node, and I have no problem starting an nginx container curl using Docker

### How can we reproduce it (as minimally and precisely as possible)?

Use Proxmox Virtual Environment and start running a kubernetes cluster, then run an nginx container curl https link

### Kubernetes version

[root@Rocky ~]#  kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.0
WARNING: version difference between client (1.29) and server (1.24) exceeds the supported minor version skew of +/-1

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
![image](https://github.com/kubernetes/kubernetes/assets/46311200/6023ab68-775f-487a-a3fb-c84c0c068bc0)
![image](https://github.com/kubernetes/kubernetes/assets/46311200/6c9a2fd8-30f1-4421-9660-7657dcd66ddb)

### Install tools

<details>
Kind  kubeadm
</details>
I have installed both Kind and Kubeadm and encountered the same problem

### Container runtime (CRI) and version (if applicable)

<details>
![image](https://github.com/kubernetes/kubernetes/assets/46311200/0b862854-970d-4e82-9eb7-a555187731a8)

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 1569099266** [comment]
Can you please teach me how to add tags

**Comment by adrianmoisey** [comment]
> I curl any link with HTTPS in the ingress nginx controller pod in Kubernetes, and the HTTPS certificate will expire at the same time.

In the image you attached, the image expires 4 months after the issuing date.

**Comment by shaneutt** [comment]
@1569099266 I may be a bit confused here, so please bear with me!

I was looking this over, and the screenshot you shared shows a certificate that expired last year in 2023... isn't the certificate being marked as expired accurate there?
