### ISSUE TITLE
apiserver_admission_webhook_request_total metric still emit after webhook is deleted. Is this expected?

### ISSUE THREAD

**Issue by pbxqdown** [kubernetes/kubernetes#125199]
### What happened?

We would like to have a metric that helps us determine whether a webhook exists or not. 

The metric apiserver_admission_webhook_request_total seems still emit after a webhook is deleted. So we can not use it to check whether webhook exists.
I think it is more convincing that metric stops emitting when corresponding webhook no longer exists.
  
Wondering whether there are some webhook_exists  metric that helps in this case.

### What did you expect to happen?

apiserver_admission_webhook_request_total metric should stop emit after webhook is deleted. 

### How can we reproduce it (as minimally and precisely as possible)?

create a webhook then delete it.  apiserver_admission_webhook_request_total will still emit after webhook has been deleted.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:22Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by likakuli** [comment]
It's not a bug. if you want some metrics to show whether some webhook exist, you can try to use kube_state_metrics to find them.

**Comment by pbxqdown** [comment]
Yes kube_state_metrics indeed has mutating webhook metric. But they are marked as [experimental](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/extend/mutatingwebhookconfiguration-metrics.md), maybe nice if api server can provide native support.

Regarding the webhook_request_total metric, I think idiomatically it should stop emit if webhook is deleted(because the object no more exists). But understandable if in practice it is useful for some case(e.g. keep accumulative request count when a webhook is deleted accidentally).

**Comment by logicalhan** [comment]
Yes, metrics are not wiped even if the webhook is deleted. How would the metric even know that the webhook was deleted? It's indistinguishable from the webhook not being called for a while. 

You cannot use metrics to determine that a webhook was deleted. 

/close
