### ISSUE TITLE
Deleting ns is stuck on terminating

### ISSUE THREAD

**Issue by yinfuqian** [kubernetes/kubernetes#125143]
### What happened?

I started to execute kubectl delete ns xxx without clearing the resources under the namespace, and found that the namespace was stuck in the terminating state. 
![image](https://github.com/kubernetes/kubernetes/assets/43942747/974d6255-5927-4a80-986c-c57156d85737)
[root@k8s-master-node1 lstio]# kubectl get ns pal -ojson 
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "annotations": {
            "cattle.io/status": "{\"Conditions\":[{\"Type\":\"ResourceQuotaInit\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2024-01-22T06:13:19Z\"},{\"Type\":\"InitialRolesPopulated\",\"Status\":\"True\",\"Message\":\"\",\"LastUpdateTime\":\"2024-01-22T06:13:19Z\"}]}",
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{\"cattle.io/status\":\"{\\\"Conditions\\\":[{\\\"Type\\\":\\\"ResourceQuotaInit\\\",\\\"Status\\\":\\\"True\\\",\\\"Message\\\":\\\"\\\",\\\"LastUpdateTime\\\":\\\"2024-01-22T06:13:19Z\\\"},{\\\"Type\\\":\\\"InitialRolesPopulated\\\",\\\"Status\\\":\\\"True\\\",\\\"Message\\\":\\\"\\\",\\\"LastUpdateTime\\\":\\\"2024-01-22T06:13:19Z\\\"}]}\",\"lifecycle.cattle.io/create.namespace-auth\":\"true\"},\"creationTimestamp\":\"2024-01-22T06:13:18Z\",\"finalizers\":[\"controller.cattle.io/namespace-auth\"],\"managedFields\":[{\"apiVersion\":\"v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:status\":{\"f:phase\":{}}},\"manager\":\"kubectl-create\",\"operation\":\"Update\",\"time\":\"2024-01-22T06:13:18Z\"},{\"apiVersion\":\"v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:cattle.io/status\":{},\"f:lifecycle.cattle.io/create.namespace-auth\":{}},\"f:finalizers\":{\".\":{},\"v:\\\"controller.cattle.io/namespace-auth\\\"\":{}}}},\"manager\":\"rancher\",\"operation\":\"Update\",\"time\":\"2024-01-22T06:13:18Z\"}],\"name\":\"pal\",\"resourceVersion\":\"24742810\",\"uid\":\"8ab8b99b-8eab-4657-9902-87af861f6fba\"},\"status\":{\"phase\":\"Active\"}}\n",
            "lifecycle.cattle.io/create.namespace-auth": "true"
        },
        "creationTimestamp": "2024-02-28T02:20:50Z",
        "deletionGracePeriodSeconds": 0,
        "deletionTimestamp": "2024-05-24T06:01:07Z",
        "finalizers": [
            "controller.cattle.io/namespace-auth"
        ],
        "managedFields": [
            {
                "apiVersion": "v1",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:metadata": {
                        "f:annotations": {
                            ".": {},
                            "f:cattle.io/status": {},
                            "f:kubectl.kubernetes.io/last-applied-configuration": {},
                            "f:lifecycle.cattle.io/create.namespace-auth": {}
                        },
                        "f:finalizers": {
                            ".": {},
                            "v:\"controller.cattle.io/namespace-auth\"": {}
                        }
                    }
                },
                "manager": "kubectl-client-side-apply",
                "operation": "Update",
                "time": "2024-02-28T02:20:50Z"
            },
            {
                "apiVersion": "v1",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:status": {
                        "f:phase": {}
                    }
                },
                "manager": "kube-controller-manager",
                "operation": "Update",
                "time": "2024-05-24T06:01:12Z"
            }
        ],
        "name": "pal",
        "resourceVersion": "10993707",
        "uid": "e8dae028-edcf-461d-97c6-5b71ef4621ff"
    },
    "spec": {},
    "status": {
        "conditions": [
            {
                "lastTransitionTime": "2024-05-24T06:01:12Z",
                "message": "All resources successfully discovered",
                "reason": "ResourcesDiscovered",
                "status": "False",
                "type": "NamespaceDeletionDiscoveryFailure"
            },
            {
                "lastTransitionTime": "2024-05-24T06:01:12Z",
                "message": "All legacy kube types successfully parsed",
                "reason": "ParsedGroupVersions",
                "status": "False",
                "type": "NamespaceDeletionGroupVersionParsingFailure"
            },
            {
                "lastTransitionTime": "2024-05-24T06:01:12Z",
                "message": "All content successfully deleted, may be waiting on finalization",
                "reason": "ContentDeleted",
                "status": "False",
                "type": "NamespaceDeletionContentFailure"
            },
            {
                "lastTransitionTime": "2024-05-24T06:01:12Z",
                "message": "All content successfully removed",
                "reason": "ContentRemoved",
                "status": "False",
                "type": "NamespaceContentRemaining"
            },
            {
                "lastTransitionTime": "2024-05-24T06:01:12Z",
                "message": "All content-preserving finalizers finished",
                "reason": "ContentHasNoFinalizers",
                "status": "False",
                "type": "NamespaceFinalizersRemaining"
            }
        ],
        "phase": "Terminating"
    }
}

I tried to modify the spec.finalizers using kube-proxy, but the spec field is empty.

### What did you expect to happen?

namespace  was deleted

### How can we reproduce it (as minimally and precisely as possible)?

kubectl delete ns xxxx 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:23:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
[root@k8s-master-node1 lstio]# uname  -a
Linux k8s-master-node1 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@k8s-master-node1 lstio]# 
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
helm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
runc
[root@k8s-master-node1 lstio]# runc --version
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d1
spec: 1.0.2-dev
go: go1.17.10
libseccomp: 2.5.4
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
flannel
</details>

**Comment by kundan2707** [comment]
@yinfuqian can you share what kind of resourse this ns had?
i tried same but namespace got deleted successfully.

**Comment by aojea** [comment]
> lifecycle.cattle.io/create.namespace-auth":{}},"f:finalizers":{".":{},"v:\"controller.cattle.io/namespace-auth\"":{}}}},"manager":"rancher","operation":"Update","time":"2024-01-22T06:13:18Z"}],"name":"pal","resourceVersion":"24742810","uid":"8ab8b99b-8eab-4657-9902-87af861f6fba"},"status":{"phase":"Active"}}\n",
"lifecycle.cattle.io/create.namespace-auth": "true

it seems to be handled by rancher controller, it is better you open the issue in the Rancher project

/close

**Comment by yinfuqian** [comment]
I haven't used rancher

**Comment by yinfuqian** [comment]
I haven't used rancher

**Comment by aojea** [comment]
> finalizers":["controller.cattle.io/namespace-auth"],"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:phase":{}}},"manager":"kubectl-create","operation":"Update","time":"2024-01-22T06:13:18Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:cattle.io/status":{},"f:lifecycle.cattle.io/create.namespace-auth":{}},"f:finalizers":{".":{},"v:\"controller.cattle.io/namespace-auth\"":{}}}},"manager":"rancher","operation":"Update","time":"2024-01-22T06:13:18Z"}],"name":"pal","resourceVersion":"24742810","uid":"8ab8b99b-8eab-4657-9902-87af861f6fba"},"status":{"phase":"Active"}}\n",
"lifecycle.cattle.io/create.namespace-auth": "true"

@yinfuqian if you see the object you can see that something is adding finalizers to the namespaces, finalizers block the deletion until that controller removes the finalizer, see

> }},"f:finalizers":{".":{},"v:\"controller.cattle.io/namespace-auth\"":{}}}},"manager":"rancher","operation":"Update","time":"2024-01-

**Comment by yinfuqian** [comment]
You mean I should manually add finalizers to the spec and then use kube proxy to delete it again?

**Comment by aojea** [comment]
No, I mean some controller that seems to come from rancher is adding a finalizer `controller.cattle.io` and not removing it, so this leaves the namespce stuck

**Comment by yinfuqian** [comment]
Ok, thanks.i understand,now how can i fix it ?

**Comment by aojea** [comment]
https://github.com/rancher/rancher/issues/14715

**Comment by yinfuqian** [comment]
OK  thanks
