### ISSUE TITLE
Some doubts about the iptables mode of kube-proxy

### ISSUE THREAD

**Issue by luzejia** [kubernetes/kubernetes#125169]
### What happened?

I have recently been modifying kube-proxy to support our internal business, and I have doubts about two places.

* Why nodeport rules need to be inserted last after other rules？
* Why does local access to lb service require masq?

### What did you expect to happen?

I didn’t find any special reason for doing the above two questions.

### How can we reproduce it (as minimally and precisely as possible)?

Two problems are in the kube-proxy(v1.24.11-iptables mode)source code:

Why nodeport rules need to be inserted last after other rules？
https://github.com/kubernetes/kubernetes/blob/0f75679e3346160939924550fd3591462a4afec6/pkg/proxy/iptables/proxier.go#L1395

Why does local access to lb service require masq?
https://github.com/kubernetes/kubernetes/blob/0f75679e3346160939924550fd3591462a4afec6/pkg/proxy/iptables/proxier.go#L1134

### Anything else we need to know?

kube-proxy
v1.24.11
iptables mode

### Kubernetes version

v1.24.11

### Cloud provider

nothing

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by T-Lakshmi** [comment]
@luzejia
github issue is not the right place for support queries.

Please post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by danwinship** [comment]
> @danwinship you have documented this somewhere, right?

not really...

(but yes, Slack is better for these questions than github)

> * Why nodeport rules need to be inserted last after other rules？

If you don't set `--nodeport-addresses`, then the nodeport rules match connections to "all local IPs". In some cases, external IPs or LB IPs may be "local IPs". So, like, if you have a Service "foo" of type LoadBalancer service with LB IP 1.2.3.4 and port 32999, and you have an unrelated NodePort Service "bar" with NodePort 32999, we want to make sure that a connection to "1.2.3.4:32999" goes to "foo", not "bar". So the NodePort match has to happen last.

> * Why does local access to lb service require masq?

It doesn't _require_ it, it just happens for consistency; LB connections to Cluster traffic policy services always get masqueraded.
