### ISSUE TITLE
problem when calling the API interface to create or delete  PVC resources

### ISSUE THREAD

**Issue by zzuchen** [kubernetes/kubernetes#125155]
### What happened?

When calling the API interface to create PVC resources, PVC is not yet in a bound state (still in a pending state), The API interface call has returned. When calling the API interface to delete PVC resources, PVC is still in the terminating state and has not been completely removed, but the API interface has returned success

### What did you expect to happen?

When calling the API interface to create PVC resources, when PVC is in a bound state, The API interface call returned. When calling the API interface to delete PVC resources, PVC  has been completely removed, the API interface call returned success.

### How can we reproduce it (as minimally and precisely as possible)?

calling the API interface to create or delete  PVC resources

### Kubernetes version

v1.23

### Cloud provider

none

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mert2m** [comment]
these are the expected behaviors in the K8s PVC lifecycle.

**Comment by mauri870** [comment]
Since this is expected behavior, shall we close this issue?

**Comment by mert2m** [comment]
yes, I think u can close this issue.

**Comment by mauri870** [comment]
Closing as this is expected behavior from the PVC lifecycle.

/close

**Comment by mauri870** [comment]
@zzuchen mind closing this? Otherwise I'll have to wait for someone that can issue a close command. Thanks.
