### ISSUE TITLE
kubectl logs shows host not found in upstream "xxxxx" in /etc/nginx/conf.d/nginx.80.conf:11

### ISSUE THREAD

**Issue by Watle-fan** [kubernetes/kubernetes#125160]
### What happened?

 kubectl get pod -A -owide | grep e3edge shows error.
<img width="770" alt="df12cb33745afebfd222e9214fcd450" src="https://github.com/kubernetes/kubernetes/assets/78351235/065f6454-2bb2-4f13-8d65-7cf7eb9b9fb3">

<img width="745" alt="0c67e5c4ca0c5471b179c984b15aa0e" src="https://github.com/kubernetes/kubernetes/assets/78351235/52cad096-feab-4cc9-b3da-767a8e91ba2a">

kubectl logs shows host not found in upstream "xxxxx" in /etc/nginx/conf.d/nginx.80.conf:11

<img width="721" alt="3182aea145ec40ec658bccd7f308a07" src="https://github.com/kubernetes/kubernetes/assets/78351235/475d06fd-1111-4ed3-b75e-1a028fef9c2b">

### What did you expect to happen?

 kubectl get pod -A -owide | grep e3edge shows running.

### How can we reproduce it (as minimally and precisely as possible)?

I installed kubeedge and deployed my own application e3edge.

My current node status is all ready. After installing the flannel plug-in, it will fail when deploying the official example nginx. Now I am not using flannel. The official example nginx can be deployed successfully, but there is a problem when I deploy the e3edge mentioned above.

### Anything else we need to know?

When I deploy my e3edge application, there is an error in the container, the corresponding log is as shown in the figure(host not found in upstream "svc-user-center-v3" in /etc/nginx/conf.d/nginx.80.conf:11
), for this error, I tried to add "svc-user-center-v3" to the /etc/hosts file, but the error is still reported, is there any solution？

The nginx.80.conf file reads as follows:
`server {
    listen       80;

    location / {
        root   /usr/share/nginx/html;
        index  landing.html index.html index.htm;
        expires  1d;
    }

    location /uc-api/ {
        proxy_pass http://svc-user-center-v3:8080/;
        proxy_http_version 1.1;
        proxy_pass_header Authorization;
        gzip on;
        expires -1;
    }

    error_page   404 500 502 503 504  /404.html;
    location /50x.html {
        root   /usr/share/nginx/html;
    }

    location /404.html {
        root   /usr/share/nginx/html;
    }
}`

### Kubernetes version

Kubernetes version：v1.24

### Cloud provider

none

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

cni:v1.0.0

**Comment by mengjiao-liu** [comment]
/kind support
/remove-kind bug

The best method is to ask on support channels and not on github.
maybe stackoverflow.
Please see https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md.
