### ISSUE TITLE
Moving InPlacePodVerticalScaling into Beta

### ISSUE THREAD

**Issue by roshandashsprinklraccount** [kubernetes/kubernetes#125149]
### What would you like to be added?

InPlacePodVerticalScaling should be moved to Beta. It's already been more than a year since 1.27 when it was released in alpha. Would love to see it being released in 1.31 as Beta.

### Why is this needed?

InPlacePodVerticalScaling is a very useful feature which I want to use in my production workloads in GKE and EKS. Since its still in alpha I cannot enable it in my existing production cluster. It’s been almost more than a year since 1.27, so do we have any plans of making it a beta feature in the upcoming 1.31 release. Or could you please shed some light on which release are we planning to push it into beta. 
Thank you.

**Comment by roshandashsprinklraccount** [comment]
I have found the release plan here 
https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1287-in-place-update-pod-resources/kep.yaml . But it keeps getting shifted. So would love to see it prioritised to push to beta

**Comment by dims** [comment]
/close

duplicate https://github.com/kubernetes/enhancements/issues/1287

@roshandashsprinklraccount if you or your team is willing to help, please step up by joining the sig-node channel/meeting and volunteering. that would really help. opening duplicate issue here will not help.

https://github.com/kubernetes/community/blob/master/sig-node/README.md

thanks!

**Comment by sumeet-zuora** [comment]
Do we know if this feature is in beta or not? And will be released with eks 1.31
