### ISSUE TITLE
Jenkins build failure in any suite should send an email to the current oncall.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#12524]
E.g. #12522 was ignored for over a week.

@roberthbailey @ixdy @quinton-hoole

**Comment by ixdy** [comment]
*Every* suite? We have quite a lot of Jenkins builds these days, with a lot of them being fairly flaky.

In any case, this should probably be a Google-internal bug.

**Comment by gmarek** [comment]
Maybe, but if build is failing (note that by build here I mean compilation, not Jenkins "build" which means tests) something's wrong.

**Comment by ixdy** [comment]
The oncall is now emailed for failures on all "critical" builds, btw.
