### ISSUE TITLE
Persistent 'Terminating' State for Old Pod after Migration to New Node

### ISSUE THREAD

**Issue by wp695533082** [kubernetes/kubernetes#125217]
### What happened?

After a node is shut down, the pod on it migrates to another node and a new pod is established. However, the old pod remains in the Terminating state, continuously displayed, and has not been deleted promptly.

The screenshot is as follows：

![原来节点被关闭后，pod迁移到节点后，旧的节点信息一直显示，没有被及时删除](https://github.com/kubernetes/kubernetes/assets/168079959/7660b781-0fa8-4784-a615-d6ef8bde0694)

### What did you expect to happen?

Can the terminating pod be  deleted promptly ? 

### How can we reproduce it (as minimally and precisely as possible)?

no idea

### Kubernetes version

<details>

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2

</details>

### Cloud provider

<details>
no 
</details>

### OS version

<details>

NAME="CentOS Linux"
VERSION="8"

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tamilselvan1102** [comment]
There are various reasons pod could stuck in 'Terminating' state. 
Check the running information of POD by using the command [kubectl describe POD <YOUR_POD_NAME>]

**Comment by saschagrunert** [comment]
Has the container runtime removed the old pod?

**Comment by brianpursley** [comment]
Your screenshot is pixelated, so difficult to read. Could you paste the terminal output it in a `code` block?

But here is what I think might be happening...

kubectl will show "Terminating" if the pod has [finalizers](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/#how-finalizers-work) that have not been cleared.

You can use `-f` to force delete it, but that's not a good solution for everyday use. It's probably best to see if there are any finalizers and determine why they aren't being cleared (perhaps a missing controller).

**Comment by chengjoey** [comment]
mayby should graceful shut down node

**Comment by wp695533082** [comment]
> There are various reasons pod could stuck in 'Terminating' state. Check the running information of POD by using the command [kubectl describe POD <YOUR_POD_NAME>]

ok, I have reproduced the issue again and executed command [kubectl describe], and the result is as follows:

![describe pod 处于terminating](https://github.com/kubernetes/kubernetes/assets/168079959/3c5373ea-698d-4a48-a0dc-a49149ffe94c)

There were no particular findings. The pod was in the Terminating state because the node was in an unready state, but the problem is that the old pod was not cleaned up in time.
@tamilselvan1102

**Comment by wp695533082** [comment]
> Has the container runtime removed the old pod?

How should I troubleshoot the issue based on your suggestions? Could you provide me with a few commands to try? I've executed command [systemctl status kubelet] and command [systemctl status containerd], but there were no specific error messages.

**Comment by wp695533082** [comment]
> Your screenshot is pixelated, so difficult to read. Could you paste the terminal output it in a `code` block?
> 
> But here is what I think might be happening...
> 
> kubectl will show "Terminating" if the pod has [finalizers](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/#how-finalizers-work) that have not been cleared.
> 
> You can use `-f` to force delete it, but that's not a good solution for everyday use. It's probably best to see if there are any finalizers and determine why they aren't being cleared (perhaps a missing controller).

@brianpursley  ok，the problem is:
```code
Events:
  Type     Reason        Age   From               Message
  ----     ------        ----  ----               -------
  Normal   Scheduled     42m   default-scheduler  Successfully assigned default/test-nginx-wp-2-595dff4799-hz9xr to wp-5.novalocal
  Normal   Pulled        42m   kubelet            Container image "nginx:1.24.0" already present on machine
  Normal   Created       42m   kubelet            Created container nginx
  Normal   Started       42m   kubelet            Started container nginx
  Warning  NodeNotReady  39m   node-controller    Node is not ready
[root@wp-1 k8s]# 
[root@wp-1 k8s]# kubectl get nodes
NAME             STATUS     ROLES           AGE   VERSION
wp-1.novalocal   Ready      control-plane   9d    v1.28.2
wp-2.novalocal   Ready      control-plane   9d    v1.28.2
wp-3.novalocal   Ready      control-plane   9d    v1.28.2
wp-4.novalocal   Ready      <none>          47h   v1.28.2
wp-5.novalocal   NotReady   <none>          9d    v1.28.2
[root@wp-1 k8s]# 
[root@wp-1 k8s]# kubectl get pods -o wide
NAME                               READY   STATUS        RESTARTS   AGE   IP           NODE             NOMINATED NODE   READINESS GATES
test-nginx-wp-2-595dff4799-hz9xr   1/1     Terminating   0          43m   10.0.4.6     wp-5.novalocal   <none>           <none>
test-nginx-wp-2-595dff4799-z5lfs   1/1     Running       0          35m   10.0.3.198   wp-4.novalocal   <none>           <none>
test-nginx-wp-57f8b68b7d-2wg4l     1/1     Running       0          17h   172.16.2.4   wp-4.novalocal   <none>           <none>
[root@wp-1 k8s]# 
[root@wp-1 k8s]# 
[root@wp-1 k8s]# 

```
this is all pods:
```code
[root@wp-1 k8s]# kubectl get pods -A -o wide
NAMESPACE     NAME                                     READY   STATUS        RESTARTS        AGE   IP           NODE             NOMINATED NODE   READINESS GATES
default       test-nginx-wp-2-595dff4799-hz9xr         1/1     Terminating   0               45m   10.0.4.6     wp-5.novalocal   <none>           <none>
default       test-nginx-wp-2-595dff4799-z5lfs         1/1     Running       0               37m   10.0.3.198   wp-4.novalocal   <none>           <none>
default       test-nginx-wp-57f8b68b7d-2wg4l           1/1     Running       0               17h   172.16.2.4   wp-4.novalocal   <none>           <none>
kube-system   cilium-4d5nk                             1/1     Running       0               9d    172.16.2.1   wp-1.novalocal   <none>           <none>
kube-system   cilium-bxtw4                             1/1     Running       0               9d    172.16.2.2   wp-2.novalocal   <none>           <none>
kube-system   cilium-crblz                             1/1     Running       2 (54m ago)     9d    172.16.2.5   wp-5.novalocal   <none>           <none>
kube-system   cilium-gpm9w                             1/1     Running       0               9d    172.16.2.3   wp-3.novalocal   <none>           <none>
kube-system   cilium-operator-f5b449989-9ds29          1/1     Running       41 (58m ago)    9d    172.16.2.1   wp-1.novalocal   <none>           <none>
kube-system   cilium-wvp8s                             1/1     Running       0               47h   172.16.2.4   wp-4.novalocal   <none>           <none>
kube-system   coredns-6486885b75-kkdmx                 1/1     Running       0               9d    10.0.0.235   wp-1.novalocal   <none>           <none>
kube-system   coredns-6486885b75-mkcpd                 1/1     Running       0               9d    10.0.0.18    wp-1.novalocal   <none>           <none>
kube-system   etcd-wp-1.novalocal                      1/1     Running       1               9d    172.16.2.1   wp-1.novalocal   <none>           <none>
kube-system   etcd-wp-2.novalocal                      1/1     Running       0               9d    172.16.2.2   wp-2.novalocal   <none>           <none>
kube-system   etcd-wp-3.novalocal                      1/1     Running       0               9d    172.16.2.3   wp-3.novalocal   <none>           <none>
kube-system   haproxy-wp-1.novalocal                   1/1     Running       1               9d    172.16.2.1   wp-1.novalocal   <none>           <none>
kube-system   haproxy-wp-2.novalocal                   1/1     Running       0               9d    172.16.2.2   wp-2.novalocal   <none>           <none>
kube-system   haproxy-wp-3.novalocal                   1/1     Running       0               9d    172.16.2.3   wp-3.novalocal   <none>           <none>
kube-system   keepalived-wp-1.novalocal                1/1     Running       1               9d    172.16.2.1   wp-1.novalocal   <none>           <none>
kube-system   keepalived-wp-2.novalocal                1/1     Running       0               9d    172.16.2.2   wp-2.novalocal   <none>           <none>
kube-system   keepalived-wp-3.novalocal                1/1     Running       0               9d    172.16.2.3   wp-3.novalocal   <none>           <none>
kube-system   kube-apiserver-wp-1.novalocal            1/1     Running       1               9d    172.16.2.1   wp-1.novalocal   <none>           <none>
kube-system   kube-apiserver-wp-2.novalocal            1/1     Running       2 (9d ago)      9d    172.16.2.2   wp-2.novalocal   <none>           <none>
kube-system   kube-apiserver-wp-3.novalocal            1/1     Running       0               9d    172.16.2.3   wp-3.novalocal   <none>           <none>
kube-system   kube-controller-manager-wp-1.novalocal   1/1     Running       9 (41h ago)     9d    172.16.2.1   wp-1.novalocal   <none>           <none>
kube-system   kube-controller-manager-wp-2.novalocal   1/1     Running       6 (3d ago)      9d    172.16.2.2   wp-2.novalocal   <none>           <none>
kube-system   kube-controller-manager-wp-3.novalocal   1/1     Running       5 (2d19h ago)   9d    172.16.2.3   wp-3.novalocal   <none>           <none>
kube-system   kube-proxy-92t59                         1/1     Running       0               9d    172.16.2.2   wp-2.novalocal   <none>           <none>
kube-system   kube-proxy-d2tpc                         1/1     Running       0               47h   172.16.2.4   wp-4.novalocal   <none>           <none>
kube-system   kube-proxy-mftmd                         1/1     Running       0               9d    172.16.2.1   wp-1.novalocal   <none>           <none>
kube-system   kube-proxy-qckhh                         1/1     Running       0               9d    172.16.2.3   wp-3.novalocal   <none>           <none>
kube-system   kube-proxy-z9q9c                         1/1     Running       2 (54m ago)     9d    172.16.2.5   wp-5.novalocal   <none>           <none>
kube-system   kube-scheduler-wp-1.novalocal            1/1     Running       11 (24h ago)    9d    172.16.2.1   wp-1.novalocal   <none>           <none>
kube-system   kube-scheduler-wp-2.novalocal            1/1     Running       6 (2d19h ago)   9d    172.16.2.2   wp-2.novalocal   <none>           <none>
kube-system   kube-scheduler-wp-3.novalocal            1/1     Running       5 (18h ago)     9d    172.16.2.3   wp-3.novalocal   <none>           <none>

```

Can you give me more suggestions? thanks

**Comment by wp695533082** [comment]
> mayby should graceful shut down node

Thank you for your advice, but I didn't  understand. Could you elaborate on it?
@chengjoey

**Comment by tamilselvan1102** [comment]
The common reasons for node not ready error include lack of resources on the node, a problem with the kubelet or an error related to kube-proxy
you can diagnosis the error by following command

> kubectl describe node [name]

Check all the conditions/flags settings in the conditions section

**Comment by wp695533082** [comment]
> The common reasons for node not ready error include lack of resources on the node, a problem with the kubelet or an error related to kube-proxy you can diagnosis the error by following command
> 
> > kubectl describe node [name]
> 
> Check all the conditions/flags settings in the conditions section

The  reason for node not ready is that I manually shut down the node for testing purposes. The issue I'd like to inquire about is that the old pod that should have been deleted is not being cleared in time, but instead remains in an terminating state after migration to new node.

**Comment by likakuli** [comment]
> The reason for node not ready is that I manually shut down the node for testing purposes.

this is the reason why this pod can't be deleted. you have shut down your node, so no agent can response to the pod delete event thus pod will stuck in terminating state.

**Comment by wp695533082** [comment]
> > The reason for node not ready is that I manually shut down the node for testing purposes.
> 
> this is the reason why this pod can't be deleted. you have shut down your node, so no agent can response to the pod delete event thus pod will stuck in terminating state.

Isn't it the responsibility of k8s or the container orchestrator to delete the pods that should be removed? Do we really need to bring the dead node back to life just to response to the pod delete event?

**Comment by likakuli** [comment]
<< Isn't it the responsibility of k8s or the container orchestrator to delete the pods that should be removed?
you can try to find some document about `node(lifecycle) controller`, may be this is what you want. it provide some parameters to control when to delete pod after node notready or node deleted from cluster.

**Comment by wp695533082** [comment]
> << Isn't it the responsibility of k8s or the container orchestrator to delete the pods that should be removed? you can try to find some document about `node(lifecycle) controller`, may be this is what you want. it provide some parameters to control when to delete pod after node notready or node deleted from cluster.

Thank you, I will try to find some of the documents you recommended to read. Could you send me some related online documents?  @likakuli

**Comment by likakuli** [comment]
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

can search by "eviction" keyword

**Comment by wp695533082** [comment]
> https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
> 
> can search by "eviction" keyword

Thank you for your advice. I found the possible reason on the k8s official website, which is: " https://kubernetes.io/zh-cn/docs/concepts/architecture/nodes/#rate-limits-on-eviction". However, I still have two questions: 1. I can't resolve this issue by modifying the parameter "large-cluster-size-threshold". It seems that this parameter is not provided when k8s creates the cluster; 2. I'm not sure if modifying "large-cluster-size-threshold" can solve the problem, and this phenomenon seems unreasonable: the pod has already been transferred to another node, but the original record still exists.
