### ISSUE TITLE
runtime: failed to create new OS thread

### ISSUE THREAD

**Issue by Kry1702** [kubernetes/kubernetes#125242]
### What happened?

[root@m01 log]# kubectl   get  pod  -A
runtime: failed to create new OS thread (have 3 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

runtime stack:
runtime.throw(0x1c1d651, 0x9)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.newosproc(0xc0000b6400)
        /usr/local/go/src/runtime/os_linux.go:161 +0x1c5
runtime.newm1(0xc0000b6400)
        /usr/local/go/src/runtime/proc.go:1843 +0xdd
runtime.newm(0x1d07a08, 0xc00004a800, 0x2)
        /usr/local/go/src/runtime/proc.go:1822 +0x9b
runtime.startm(0x0, 0xc000048001)
        /usr/local/go/src/runtime/proc.go:1979 +0xc9
runtime.wakep()
        /usr/local/go/src/runtime/proc.go:2067 +0x66
runtime.newproc.func1()
        /usr/local/go/src/runtime/proc.go:3561 +0x97
runtime.systemstack(0x46c414)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1116

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0000b26f0 sp=0xc0000b26e8 pc=0x46c540
runtime.newproc(0x0, 0x1d078c8)
        /usr/local/go/src/runtime/proc.go:3554 +0x6e fp=0xc0000b2738 sp=0xc0000b26f0 pc=0x44214e
runtime.init.6()
        /usr/local/go/src/runtime/proc.go:243 +0x35 fp=0xc0000b2758 sp=0xc0000b2738 pc=0x439e35
runtime.doInit(0x2b17e80)
        /usr/local/go/src/runtime/proc.go:5652 +0x8a fp=0xc0000b2788 sp=0xc0000b2758 pc=0x446fca
runtime.main()
        /usr/local/go/src/runtime/proc.go:151 +0xd9 fp=0xc0000b27e0 sp=0xc0000b2788 pc=0x439b59
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000b27e8 sp=0xc0000b27e0 pc=0x46e181

### What did you expect to happen?

Output Pod information.

### How can we reproduce it (as minimally and precisely as possible)?

I don't know how to repeat the problem.

### Anything else we need to know?

$ ulimit -u
655350
$ ulimit -n
655350

systemctl edit kubelet.service
[Service]
LimitNOFILE=infinity
LimitNPROC=infinity

### Kubernetes version

<details>

```console
$ kubectl version
v 1.19.16
```

</details>

### Cloud provider

<details>
Physical server
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
CentOS Linux 7 (Core)

$ uname -a
linux m01 4.20.3-1.el7.elrepo.x86_64  x86_64  GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
Docker v24.0.6

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Kry1702** [comment]
> 此问题没有签名标签。请使用以下命令之一添加适当的标签：
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> 请参阅[小组列表](https://git.k8s.io/community/sig-list.md)以获取可用的 SIG、工作组和委员会的列表。
> 
> 使用 PR 评论与我互动的说明可[在此处获得。如果您对我的行为有疑问或建议，请针对](https://git.k8s.io/community/contributors/guide/pull-requests.md)[kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:)存储库提交问题。

> * `/sig  apps`
> * `/wg serving`
> * `/committee steering`

**Comment by neolit123** [comment]
/kind support 
/sig cli

>  kubectl version
> v 1.19.16

this is a very old version. try 1.30.

**Comment by Kry1702** [comment]
> /kind support /sig cli
> 
> > kubectl version
> > v 1.19.16
> 
> this is a very old version. try 1.30.

The version is too new,v1.19.16 This version has been running stably for 200 days.
The problem popped up twice this week, and the solution was to restart Docker.
