### ISSUE TITLE
Add net.ipv4.tcp_rmem and net.ipv4.tcp_wmem into safe sysctl list

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/kubernetes#125234]
### What would you like to be added?

`net.ipv4.tcp_rmem` and `net.ipv4.tcp_wmem` have been namespaced since https://github.com/torvalds/linux/commit/356d1833b638bd465672aefeb71def3ab93fc17d (Linux Kernal Version >= 4.15)

It would be helpful to allow config these sysctls for each Pod(Application).

### Why is this needed?

The good performance of some applications depends on these sysctls, for example https://docs.datastax.com/en/cassandra-oss/3.x/cassandra/install/installRecommendSettings.html#TCPsettings.

To handle thousands of concurrent connections used by Cassandra, DataStax recommends these settings to optimize the Linux network stack. We should config these sysctls as the following:
```sh
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
```
It would be helpful to be able to configure this for applications without needing to modify the kubelet args.

**Comment by nikzayn** [comment]
Hey @SataQiu, I would like to take this up after triage-accepted label. Thanks

/assign

**Comment by mauri870** [comment]
@nikzayn I had started working on this yesterday, but I'm fine passing the ball to you. Please take a look at my changes, perhaps some of them are worth porting over to your PR. Thanks.

https://github.com/kubernetes/kubernetes/compare/master...mauri870:kubernetes:feature/sysctl-tcp-rmem-wmem?expand=1

**Comment by mauri870** [comment]
Related work for `net.ipv4.tcp_keepalive_time` at https://github.com/kubernetes/kubernetes/pull/118846 can be used as inspiration as well.

**Comment by nikzayn** [comment]
Thanks a lot @mauri870 my bad I didn't know you were working. I should have to wait for someone to assign from next time. Thanks for passing the ball. Definitely, I will take a look and after a successful build pass will push the respective changes.

**Comment by mauri870** [comment]
> Thanks a lot @mauri870 my bad I didn't know you were working. I should have to wait for someone to assign from next time. Thanks for passing the ball. Definitely, I will take a look and after a successful build pass will push the respective changes.

No worries, it's my fault for not assigning the issue to myself earlier. I'm glad you were able to work on it.

**Comment by nikzayn** [comment]
> > Thanks a lot @mauri870 my bad I didn't know you were working. I should have to wait for someone to assign from next time. Thanks for passing the ball. Definitely, I will take a look and after a successful build pass will push the respective changes.
> 
> No worries, it's my fault for not assigning the issue to myself earlier. I'm glad you were able to work on it.

Thanks, I have made the changes. You can check that out. Do checkout of If I am missing anything. Thanks!!

**Comment by wenjianhn** [comment]
What is the typical TCP RTT between those Cassandra nodes?

`BDP (bits) = bandwidth (bits/second) * RTT (seconds)`
`sudo sysctl -w net.ipv4.tcp_rmem="4096 87380 $MaxExpectedPathBDP"`
See https://cloud.google.com/compute/docs/networking/tcp-optimization-for-network-performance-in-gcp-and-hybrid

TCP memory is not that safe per https://lpc.events/event/16/contributions/1212/

> Potentially a low priority job can hog all the available TCP memory and starve the high priority jobs collocated with it. Indeed we have seen production incidences of low priority jobs negatively impacting the network performance of collocated high priority jobs.
