### ISSUE TITLE
Named ports in initContainer sidecars do not work with NetworkPolicies

### ISSUE THREAD

**Issue by george-angel** [kubernetes/kubernetes#125285]
### What happened?

We have recently migrated our traditional sidecar definitions to the new recommended initContainer sidecars.

We are running a CockroachDB StatefulSet that has a Vault sidecar, such that members 0 and 1 have a "legacy" sidecar container:

```console
$ kubectl --context prod-aws -n partner-registration get -o json pod cockroachdb-0 | jq -r '.spec.containers[] | select(.name == "vault-credentials-agent") | .ports'
[
  {
    "containerPort": 8099,
    "name": "metrics",
    "protocol": "TCP"
  }
]

$ kubectl --context prod-aws -n partner-registration get -o json pod cockroachdb-1 | jq -r '.spec.containers[] | select(.name == "vault-credentials-agent") | .ports'
[
  {
    "containerPort": 8099,
    "name": "metrics",
    "protocol": "TCP"
  }
]
```

And member 2 has a new initContainer style sidecar:

```console
$ kubectl --context prod-aws -n partner-registration get -o json pod cockroachdb-2 | jq -r '.spec.initContainers[] | select(.name == "vault-credentials-agent") | .ports[]'
{
  "containerPort": 8099,
  "name": "metrics",
  "protocol": "TCP"
}
```

They all expose a named port `metrics`.

We also have a NetworkPolicy in this namespace such that:

```console
$ kubectl --context prod-aws -n partner-registration get netpol private-ingress-sys-prom -o yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"private-ingress-sys-prom","namespace":"partner-registration"},"spec":{"ingress":[{"from":[{"namespaceSelector":{"matchLabels":{"name":"sys-prom"}}}],"ports":[{"port":"metrics"}]}],"podSelector":{},"policyTypes":["Ingress"]}}
  creationTimestamp: "2021-03-26T10:52:05Z"
  generation: 3
  name: private-ingress-sys-prom
  namespace: partner-registration
  resourceVersion: "3454111968"
  uid: 26a53b37-53e3-4a8d-92dd-8e17836b087d
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: sys-prom
    ports:
    - port: metrics
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
```

Testing the connection from Prometheus I observe the following results for member 0 and 1:

```console
$ kubectl --context prod-aws -n sys-prom exec -ti prometheus-system-0 -c prometheus -- wget -T2 -O - http://10.2.142.58:8099/__/metrics | head -4
Connecting to 10.2.142.58:8099 (10.2.142.58:8099)
writing to stdout
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary

$ kubectl --context prod-aws -n sys-prom exec -ti prometheus-system-0 -c prometheus -- wget -T2 -O - http://10.2.13.56:8099/__/metrics | head -4
Connecting to 10.2.13.56:8099 (10.2.13.56:8099)
writing to stdout
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
```

And a timeout for member 2 (running initContainer sidecar):

```console
$ kubectl --context prod-aws -n sys-prom exec -ti prometheus-system-0 -c prometheus -- wget -T2 -O - http://10.2.2.53:8099/__/metrics | head -4
Connecting to 10.2.2.53:8099 (10.2.2.53:8099)
wget: download timed out
command terminated with exit code 1
```

If I apply the following patch:

```patch
diff --git a/prod-aws/partner-registration/02-network-policies.yaml b/prod-aws/partner-registration/02-network-policies.yaml
index 9d3ea45d86..c685cc8667 100644
--- a/prod-aws/partner-registration/02-network-policies.yaml
+++ b/prod-aws/partner-registration/02-network-policies.yaml
@@ -43,7 +43,7 @@ spec:
             matchLabels:
               name: sys-prom
       ports:
-        - port: metrics
+        - port: 8099
 ---
 #  Allow private Ingress
 ---
```

Then I'm able to establish a connection with cockroachdb-2:

```console
$ kubectl --context prod-aws -n sys-prom exec -ti prometheus-system-0 -c prometheus -- wget -T2 -O - http://10.2.2.53:8099/__/metrics | head -4
Connecting to 10.2.2.53:8099 (10.2.2.53:8099)
writing to stdout
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
```

This is the Kyverno config that injects our sidecars the describes the whole config of the injected initContainer sidecar: https://github.com/utilitywarehouse/system-manifests/blob/master/kyverno/policies/pods/injectSidecar.yaml#L40-L88

### What did you expect to happen?

named port in the initContainer spec allows the traffic if it matches config of the NetworkPolicy.

### How can we reproduce it (as minimally and precisely as possible)?

Create a StatefulSet with an initContainer sidecar that specifies a named port. Create a NetworkPolicy allowing access to the named port. You should observe timeouts trying to reach that port.

### Kubernetes version

<details>

```console
$ kubectl --context prod-aws version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
```

</details>

### Cloud provider

<details>
AWS EC2 running our own control plane.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3815.2.0
VERSION_ID=3815.2.0
BUILD_ID=2024-02-12-2039
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3815.2.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3815.2.0:*:*:*:*:*:*:*"

$ uname -a
Linux ip-10-44-18-96 6.1.77-flatcar #1 SMP PREEMPT_DYNAMIC Mon Feb 12 19:37:08 -00 2024 x86_64 AMD EPYC 7571 AuthenticAMD GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Terraform / Ignition.
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI: Calico v3.27.3
</details>

**Comment by aojea** [comment]
> CNI: Calico v3.27.3

Assuming Calico is your implementation of network policies you should open the bug in that project, as Kubernetes only defines the APIs ... 

however, it will be helpful to add an e2e test to get coverage so the implementations can validate this behavior

/help
/sig network

**Comment by george-angel** [comment]
Created an issue with Calico: https://github.com/projectcalico/calico/issues/8881

**Comment by mauri870** [comment]
> Created an issue with Calico: [projectcalico/calico#8881](https://github.com/projectcalico/calico/issues/8881)

Thanks! I'll give it a try implementing it in Calico and will follow up with the e2e test here.

**Comment by thockin** [comment]
Do we know if Cilium and others handle this?  It's a fun aspect that probably was not broadcasted well.

**Comment by rouke-broersma** [comment]
Not sure if related but I'm seeing strange results with kubectl port-forward and named ports for native sidecar containers as well.

Example:

```
kubectl port-forward svc/adguard-metrics metrics (named port on service)
error: Pod 'adguard-primary-7cc5d498f4-67zs4' does not have a named port 'metrics'

kubectl port-forward adguard-primary-7cc5d498f4-67zs4 metrics (named port on native sidecar)
error: Pod 'adguard-primary-7cc5d498f4-67zs4' does not have a named port 'metrics'
```

Prometheus also does not seem to be able to discover the endpoints for the native sidecar so metric scraping is also not working for me in this case.

Probes on this pod are able to use the named container port.

Reference:
- https://github.com/broersma-forslund/homelab/blob/7f2062102b8821106da64d425a83458113ac1ef7/apps/adguard/templates/primary/deployment.yaml#L39-L54
- https://github.com/broersma-forslund/homelab/blob/7f2062102b8821106da64d425a83458113ac1ef7/apps/adguard/templates/primary/metrics-service.yaml#L13-L15

**Comment by aojea** [comment]
> Not sure if related but I'm seeing strange results with kubectl port-forward and named ports for native sidecar containers as well.
> 
> Example:
> 
> ```
> kubectl port-forward svc/adguard-metrics metrics (named port on service)
> error: Pod 'adguard-primary-7cc5d498f4-67zs4' does not have a named port 'metrics'
> 
> kubectl port-forward adguard-primary-7cc5d498f4-67zs4 metrics (named port on native sidecar)
> error: Pod 'adguard-primary-7cc5d498f4-67zs4' does not have a named port 'metrics'
> ```
> 
> Prometheus also does not seem to be able to discover the endpoints for the native sidecar so metric scraping is also not working for me in this case.
> 
> Probes on this pod are able to use the named container port.
> 
> Reference:
> 
> * https://github.com/broersma-forslund/homelab/blob/7f2062102b8821106da64d425a83458113ac1ef7/apps/adguard/templates/primary/deployment.yaml#L39-L54
> * https://github.com/broersma-forslund/homelab/blob/7f2062102b8821106da64d425a83458113ac1ef7/apps/adguard/templates/primary/metrics-service.yaml#L13-L15

@rouke-broersma please open a new issue, port-forward is a different subsystem that depend on sig-cli, please tag me there as well

**Comment by mauri870** [comment]
Unfortunately I cannot work on this in the foreseeable future so unassigning.

/unassign

**Comment by george-angel** [comment]
PR fix for Calico: https://github.com/projectcalico/calico/pull/8885

**Comment by shaneutt** [comment]
We discussed this in the SIG Network meeting today, we need to:

1. document a decision on how this should work
2. create some E2E tests to help implementations follow that

/assign @thockin

**Comment by aojea** [comment]
This will be fixed by https://github.com/kubernetes/kubernetes/pull/127976

**Comment by SergeyKanzhelev** [comment]
> This will be fixed by https://github.com/kubernetes/kubernetes/pull/127976

/close

please reopen if this didn't do it. Also if we need an e2e test here (not sure if we need though)

**Comment by thockin** [comment]
I don't think this is "fixed".  NetworkPolicy is implemented out-of-tree (the API is part of Kubernetes, but the implementations are not), so this is REALLY a bug report against the NetworkPolicy implementation (Calico in this case, @caseydavenport FYI).

We have fixed it for Kubernetes Services, but NetworkPolicy implementations need to make a similar fix.

**Comment by thockin** [comment]
We don't need this open - it's not a Kubernetes bug.
