### ISSUE TITLE
ETCD Authentication model in Kubernetes

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#12520]
Does Kubernetes support the Authentication model of ETCD to Connect the Components .

ETCD authentication module
https://github.com/coreos/etcd/blob/master/Documentation/authentication.md

**Comment by erictune** [comment]
It does not support this model.

**Comment by codeb2cc** [comment]
Any future plan for this?

**Comment by erictune** [comment]
#20347 is going to allow for calling out to a webhook to make an authorization decision.   @ericchiang can you say anything about your plans for that code yet?

**Comment by ericchiang** [comment]
Our plans mainly leverages [dex](https://github.com/coreos/dex) and the groups proposal in that repo (coreos/dex#175) to define a webhook service.

dex runs inside kubernetes and the API server queries it using the webhook plugin. Users will be assigned to dex groups, groups will be mapped to k8s resources, and dex will use this information to make authz decisions. Administrators will go through dex to change user group membership (and in turn access to k8s).

We're still working out the exact interfaces but there's a fairly detailed document [here](https://docs.google.com/document/d/1OCKW-8rBCngBFWMMrSGokKqWt-a8lg3WvfrejcETBMA/edit#heading=h.9kkruegwavaf).

The groups model in dex is fairly different from the etcd document cited above.

@codeb2cc please do take a look at #20347. The authz interface is fairly small and should support a wide flavors of authz that you can define yourself.

**Comment by yuvipanda** [comment]
I'm slightly confused by this - I want to just tell the kubernetes apiserver to use a particular username and password to authenticate to etcd, not entirely sure how that's related to dex?

Quoting

> Access to the central data store (etcd) in Kubernetes allows an attacker to run arbitrary containers on hosts, to gain access to any protected information stored in either volumes or in pods (such as access tokens or shared secrets provided as environment variables), to intercept and redirect traffic from running services by inserting middlemen, or to simply delete the entire history of the cluster.

So I basically want to restrict access of the etcd cluster to just the k8s master, which I'm currently doing via fierwall rules. Allowing k8s-apiserver to act as a particular user with a password seems like an easy way to allow this...

**Comment by erictune** [comment]
This issue was about a different question: whether kubernetes would have a role-based auth model.  We are adding that: http://kubernetes.io/docs/admin/authorization/#rbac-mode

To answer your question: no, there is no support for using password auth to talk to etcd.  Just certs, via these options:

       --etcd-cafile="": SSL Certificate Authority file used to secure etcd communication
      --etcd-certfile="": SSL certification file used to secure etcd communication
      --etcd-keyfile="": SSL key file used to secure etcd communication

I suspect we'd take a patch to add flags to handle a password.

**Comment by lchi** [comment]
>I suspect we'd take a patch to add flags to handle a password.

Still looking for a patch? I can create a new ticket to track it as well

**Comment by erictune** [comment]
Go ahead!

**Comment by qiujian16** [comment]
@lchi @erictune Is there a ticket to cover the etcd password auth?

**Comment by ericchiang** [comment]
@qiujian16 this? https://github.com/kubernetes/kubernetes/issues/35565

**Comment by qiujian16** [comment]
@erictune thanks, so the decision is do not user etcd password as a part of kubernetes flag, and use CN name of cert for access control in etcd?

**Comment by ericchiang** [comment]
@qiujian16 it doesn't look like there was a decision reached, but it seems like we don't want to encourage multi-tenant etcd setups. If you can use CN to get around this for now, do you need anything else?

**Comment by qiujian16** [comment]
@erictune our use case is to let kubernetes and some other services share the same etcd cluster, but I think CN should be enough for now. Thanks again :)
