### ISSUE TITLE
DRA: verification that kubelet uses node name filter

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#125355]
### What would you like to be added?

https://github.com/kubernetes/kubernetes/pull/125163 enables kubelet to do a deletecollection of ResourceSlices. At the moment, the code in `plugin/pkg/auth/authorizer/node/node_authorizer.go` has to trust that kubelet uses the node name as filter for list and watch. For deletecollection, an admission check ensures that the right objects get deleted.

Once https://github.com/kubernetes/kubernetes/pull/125163 is implemented, that code should enforce the usage of the node filter and the admission check can be removed.

/sig node

### Why is this needed?

Enhance security.

**Comment by carlory** [comment]
I'd like to do it, can I pick it up? @pohly

**Comment by pohly** [comment]
We need to wait for https://github.com/kubernetes/kubernetes/pull/125163 before anything can be done here.

**Comment by pohly** [comment]
This got resolved in https://github.com/kubernetes/kubernetes/pull/125571

/close
