### ISSUE TITLE
Remove Kubelet soft-admission

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#125393]
Kubelet soft admission handlers were created as a way for the Kubelet to block pods that cannot be run for reasons that can be resolved. In practice, this mechanism was only ever used by AppArmor ([here](https://github.com/kubernetes/kubernetes/blob/eef6c6082d4e34fc4a0675a36ec5cc575cd13696/pkg/kubelet/kubelet.go#L912)).

Problems with soft-admission rejection:
1. This is only used by AppArmor, and only for situations that cannot realistically be resolved (host or build does not support apparmor)
2. Pods held in the blocked state must be manually cleaned up. While there they hold reserved capacity from the scheduler and continually retry syncpod.
3. No other features work this way - usually Kubelet hard rejects pods that it knows it cannot run, or the runtime fails to start the pod/container.

This was originally added to prevent controllers from continuously recreating pods that cannot run, but that is a separate problem that should be approached globally, rather than with this 1-off AppArmor solution.

I propose we remove Kubelet soft admission entirely, and move the AppArmor admission handler to the hard-admission list.

/sig node
/milestone v1.31
/kind bug

**Comment by sftim** [comment]
> No other features work this way - usually Kubelet hard rejects pods that it knows it cannot run, or the runtime fails to start the pod/container.

We have a _different_, alpha mechanism: [PodSchedulingContext](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-scheduling-context-v1alpha2/). We could change AppArmor, seccomp and other mechanisms to work either with PodSchedulingContext or its eventual replacement.

IMO we only need to sketch out an approach and see that it looks viable; we don't have to block graduation for AppArmor support on a fleshed-out design.

**Comment by ffromani** [comment]
From my admittedly limited PoV I'm not against removing soft admission, and I got no opinions about AppArmor specifically. However this seems to connected to the recent conversation we're having in WG serving and SIG-node about retriable vs unretriable errors so I think we would need some coordination
cc @smarterclayton @SergeyKanzhelev

**Comment by dchen1107** [comment]
+1

**Comment by SergeyKanzhelev** [comment]
My understanding is that after this PR: https://github.com/kubernetes/kubernetes/pull/97968/files soft admission just doesn't make sense any longer.

**Comment by Vyom-Yadav** [comment]
Hello @tallclair ! Just a reminder, the code freeze is starting `02:00 UTC Wednesday 10th July 2024` (about `4 weeks` from now), and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the issue is tagged for `1.31`, is it still planned for this release?

**Comment by tallclair** [comment]
Discussed in sig-node, decided to move forward with this (move AppArmor admission to the hard admission set, remove soft-admission code)

**Comment by vinayakankugoyal** [comment]
@tallclair - do you want me to incorporate this change into https://github.com/kubernetes/kubernetes/pull/125257?
