### ISSUE TITLE
[scheduler] Improve Handling of Node Status

### ISSUE THREAD

**Issue by gabesaba** [kubernetes/kubernetes#125345]
### What would you like to be added?

This issue is to track follow-ups from #125197, which addressed a performance issue related to the NodeToStatusMap. There are latent issues which we would like to address to prevent future regressions. We can either improve NodeToStatusMap to support some of the below operations more efficiently, or come up with different way to propagate these statuses through the scheduler.

current problems:
- we loop through all nodes to set the [same status](https://github.com/kubernetes/kubernetes/blob/dae37c21645c0fc04bbb0202ad1eba6ba4438d23/pkg/scheduler/schedule_one.go#L458-L462)
  - w/ current implementation, only need to set Unschedulable status - see [comment](https://github.com/kubernetes/kubernetes/pull/125197#discussion_r1621723775)
- we [loop through all nodes](https://github.com/kubernetes/kubernetes/blob/dae37c21645c0fc04bbb0202ad1eba6ba4438d23/pkg/scheduler/framework/preemption/preemption.go#L419-L430) when determining preemption candidates, so that we can create an [error message](https://github.com/kubernetes/kubernetes/blob/dae37c21645c0fc04bbb0202ad1eba6ba4438d23/pkg/scheduler/framework/types.go#L392-L397) based on the UnschedulableAndUnresolvable status. this error message can be generated more efficiently. also see [comment](https://github.com/kubernetes/kubernetes/pull/125197/files#r1621778045)

other considerations:
- when operating over many nodes, hashing node name string is hotspot when doing hashmap gets/sets. consider creating a lightweight `NodeKey` type, which, for a scheduling cycle, references an existing node. This type should be cheap to hash  (+allow lookup in [flat data structure](https://github.com/kubernetes/kubernetes/blob/a2911e06a7cd393f7cce088b8399f889527b517f/pkg/scheduler/internal/cache/snapshot.go#L33)), and is safer than string node name, as it is guaranteed to reference a valid node.
- consider updating scheduler to not call postfilter plugins when all nodes are `UnschedulableAndUnresolvable`. at least, we should  reconcile the documented behavior [here](https://github.com/kubernetes/kubernetes/blob/a2911e06a7cd393f7cce088b8399f889527b517f/pkg/scheduler/framework/interface.go#L454-L456) and [here](https://github.com/kubernetes/kubernetes/blob/a2911e06a7cd393f7cce088b8399f889527b517f/pkg/scheduler/framework/interface.go#L90) and [here](https://github.com/kubernetes/kubernetes/blob/a2911e06a7cd393f7cce088b8399f889527b517f/pkg/scheduler/framework/interface.go#L97-L98)
- consider changing [Status](https://github.com/kubernetes/kubernetes/blob/a2911e06a7cd393f7cce088b8399f889527b517f/pkg/scheduler/framework/interface.go#L181) to an immutable type, so it can be safely shared.

/sig scheduling

### Why is this needed?

The current implementation includes some operations which may cause future performance regression. Additionally, there is some room for simplification.

**Comment by gabesaba** [comment]
cc @AxeZhan @sanposhiho @alculquicondor

**Comment by sanposhiho** [comment]
> consider updating scheduler to not call postfilter plugins when all nodes are UnschedulableAndUnresolvable.

We cannot take this way, UnschedulableAndUnresolvable has the meaning only to plugin(s) that do preemption-ish stuff. 
But, there are some other usecases in PostFilter, such as record something, clean up something, etc when each scheduling fails.

**Comment by AxeZhan** [comment]
> We cannot take this way, UnschedulableAndUnresolvable has the meaning only to plugin(s) that do preemption-ish stuff.
But, there are some other usecases in PostFilter, such as record something, clean up something, etc when each scheduling fails.

Ah right. We have already changed current behaviour to not set `UnschedulableAndUnresolvable` for allNodes if preFilter fails, not sure if this will break some custom postFilter plugins.
Then I think instead of `not call postfilter`, passing an empty NodeToStatus map may be enough. However, we'll need a new field in NodeToStatus map  to indicate that all nodes are `UnschedulableAndUnresolvable` for plugins.

**Comment by alculquicondor** [comment]
> We cannot take this way, UnschedulableAndUnresolvable has the meaning only to plugin(s) that do preemption-ish stuff.

Still, the preemption plugin could exit early if can tell that all nodes where UnschedulableAndUnresolvable

**Comment by alculquicondor** [comment]
@YamasouA this is not a task that is friendly to newcomers. Do you have experience writing code for the scheduler?

**Comment by sanposhiho** [comment]
No worries Aldo, I'm with him.

**Comment by macsko** [comment]
I have been experimenting with these improvements over the past two weeks (#125954). Unfortunately, I forgot to assign myself to the issue, my bad. Nevertheless, the PR addresses only the "current problems" part of the improvements. I think the lightweight `NodeKey` and immutable `Status` types are still worth exploring, but in my opinion both would require changes in plugins' interface.
