### ISSUE TITLE
kubeadm leaves backup files after a successful upgrade

### ISSUE THREAD

**Issue by davidwtf** [kubernetes/kubernetes#125357]
### What happened?

When I successfully upgraded the cluster using kubeadm, I found the /etc/kubernetes/tmp, which contains the backup files, was left.
```
~]# du -h /etc/kubernetes/tmp/
20K	/etc/kubernetes/tmp/kubeadm-backup-manifests-2024-06-06-18-02-44
32M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-02-44/etcd/member/snap
123M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-02-44/etcd/member/wal
155M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-02-44/etcd/member
155M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-02-44/etcd
155M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-02-44
16K	/etc/kubernetes/tmp/kubeadm-backup-manifests-2024-06-06-18-13-10
32M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-13-10/etcd/member/snap
123M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-13-10/etcd/member/wal
155M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-13-10/etcd/member
155M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-13-10/etcd
155M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-13-10
4.0K	/etc/kubernetes/tmp/kubeadm-kubelet-config3316271885
16K	/etc/kubernetes/tmp/kubeadm-backup-manifests-2024-06-06-18-22-34
32M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-22-34/etcd/member/snap
123M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-22-34/etcd/member/wal
155M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-22-34/etcd/member
155M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-22-34/etcd
155M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-06-06-18-22-34
4.0K	/etc/kubernetes/tmp/kubeadm-kubelet-config3278283034
463M	/etc/kubernetes/tmp/
```

### What did you expect to happen?

I would like to know if this is intended or if it's a bug.
Maybe the document https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ should make it clear that the user needs to remove the backup files manually.

### How can we reproduce it (as minimally and precisely as possible)?

Upgrade the cluster with kubeadm.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8
```
upgraded from v1.25.16 to v1.26.15 to 1.27.12 to 1.27.8

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> I would like to know if this is intended or if it's a bug.

it's by design. we never discussed the option to cleanup as users can easily do that.

> Maybe the document https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ should make it clear that the user needs to remove the backup files manually.

please log a ticket in kubernetes/website, also PRs to adjust the docs are welcome.
the exact place to note this is here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#recovering-from-a-failure-state

/close
