### ISSUE TITLE
False "v1 Binding is deprecated in v1.6+" warning for pods/bindings sub-resource

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#125312]
### What happened?

https://github.com/kubernetes/kubernetes/commit/8d45bbea2b464e856ddcfe3f6ee410ddea0cee32 (new for 1.31.0 alpha 1) added this:
https://github.com/kubernetes/kubernetes/blob/ae5543e4c8f99cb1555102a8ebc310aed3c82596/staging/src/k8s.io/api/core/v1/zz_generated.prerelease-lifecycle.go#L30-L34

For some reason, this code ends up checking the `Binding` type when registering the action for the `"namespaces/{namespace}/pods/{name}/binding"` sub-resource:
https://github.com/kubernetes/kubernetes/blob/ae5543e4c8f99cb1555102a8ebc310aed3c82596/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L767-L776

cc @liggitt as the author of that code

As a result, the Kubernetes scheduler gets a warning from the apiserver when it calls `err := b.handle.ClientSet().CoreV1().Pods(binding.Namespace).Bind(ctx, binding, metav1.CreateOptions{})`:

```
W0604 11:50:04.854792  276440 warnings.go:70] v1 Binding is deprecated in v1.6+
```

### What did you expect to happen?

No warning because the sub-resource is not deprecated.

### How can we reproduce it (as minimally and precisely as possible)?

```console
$ dlv test ./test/integration/scheduler_perf/ -- -test.run=TestScheduling/SchedulingWithResourceClaimTemplateStructured/fast
...

b installer.go:745
cond 1 action.Path == "namespaces/{namespace}/pods/{name}/binding"
```

### Anything else we need to know?

Did not happen in 1.30.0.

### Kubernetes version

master, shortly before v1.31.0 alpha 1.

### Cloud provider

n/a

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
I presume also
/sig node

**Comment by haircommander** [comment]
I'm not sure if this is sig node, it looks largely like apiserver code

**Comment by liggitt** [comment]
/assign @alexzielenski 

https://github.com/kubernetes/kubernetes/pull/124898/files#r1629998898
