### ISSUE TITLE
Kubelet stop watching Pods from API-Server

### ISSUE THREAD

**Issue by shihaohems** [kubernetes/kubernetes#125380]
### What happened?

We have encountered several instances where certain AKS nodes fail to respond to pod updates. This issue includes:

- Terminating pods not receiving SIGTERM notifications.
- New pods not being started as scheduled.

After reviewing the API requests to the API server during one of these incidents, we noticed that the kubelet on the affected node stopped watching pods (`/api/v1/pods?allowWatchBookmarks=true&watch=true`) before the issue happened. Despite this, the kubelet continued to report themselves as healthy via heartbeat.

Kubelet cannot recover from this non-responding state by itself.
The issue can be mitigated by restarting the kubelet on the affected node.

### What did you expect to happen?

Kubelet should not stop responding to pods while reporting healthy.

### How can we reproduce it (as minimally and precisely as possible)?

We have not found a stable way to reproduce this issue.

### Kubernetes version

1.27.13

### Cloud provider

Azure

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Common Base Linux Mariner"
VERSION="2.0.20240425"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"

$ uname -a
# not same node, only for reference
Linux aks-agentpoolm-26294222-vmss000067 5.15.153.1-2.cm2 #1 SMP Thu Apr 25 16:39:35 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

**Comment by AnishShah** [comment]
sig-node triage meeting:

/kind support
/close 

- This might be better to ask AKS support? We cannot debug without much information like kubelet/container logs.

**Comment by nmour77** [comment]
@shihaohems did you get chance to investigate this issue and find the root cause? We have been facing a similar issue.

**Comment by shihaohems** [comment]
> [@shihaohems](https://github.com/shihaohems) did you get chance to investigate this issue and find the root cause? We have been facing a similar issue.

Unfortunately, no.
