### ISSUE TITLE
Kubelet admission failures metric

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#125375]
There are not any metrics tracking admission failures in the Kubelet. I propose adding the following to track this:

`kubelet_admission_rejections_total` - Counter of the number of pods rejected during admission.
- Labels:
  - `reason` - The reason given for the admission rejection.

This would be useful for identifying regressions leading to more pods being rejected in admission (e.g. https://github.com/kubernetes/kubernetes/issues/105523).

/kind feature
/milestone v1.31
/sig node instrumentation

**Comment by drewhagen** [comment]
Hello @tallclair @lowang-bh!

This issue hasn't been updated in a while. What's the current status?

Reminder: Code freeze starts `02:00 UTC Wednesday 24th July 2024 / 19:00 PDT Tuesday 23rd July 2024` (less than **1 week** from now). Please make sure the linked PR https://github.com/kubernetes/kubernetes/pull/125385 has both `lgtm` and `approved` labels before the code freeze.

Thanks!

**Comment by Vyom-Yadav** [comment]
/milestone clear
We are way past the code freeze.
