### ISSUE TITLE
High kubepods cgroup cpu.weight/shares starves kernel threads on many core systems

### ISSUE THREAD

**Issue by StephanDollberg** [kubernetes/kubernetes#125409]
### What happened?

Hi team,

originally this issue manifested as poor performance being observed in Redpanda but for the ease of reproducing I will only talk about [fio](https://github.com/axboe/fio) below.

Running fio on large servers "inside" of kubernetes results in less IOPS (2x in the example below) than running it  "outside" of kubernetes natively on the host.

This is caused by the cgroup settings as created by k8s effectively starving important kernel threads handling interrupts/direct-io handling.

k8s creates a cgroup hierarchy in which the pods are going to run. At the root it creates the `kubepods` cgroup. The cgroup cpu.shares/weight (v1/v2) parameter will be set to N*DEFAULT (1024 for v1/100 for v2) where N is the number of cores on the system (I think potentially `systemReserved` is being substracted from this?).

As a consequence anything running in k8s pod will get a lot higher priority than kernel threads which by default run in the `/` cgroup with a default weight (1024/100). On large many-core servers this could potentially be a very big difference - originally we discovered this on 72 core server.

Note that this problem doesn't necessarily require all cores being busy or having "allocated" all quota. Processes are being weighted against each other at their hierarchy so even if a process has been assigned just one core (1000 millicpus) and that's all it uses it will still compete with the full kubepods cgroup weight (N*DEFAULT) against kernel threads. 

Further the problem with some kernel threads is that they run on the same core as the application thread related to the work (IO etc.).

### What did you expect to happen?

We shouldn't lose IOPS.

It's unclear to me whether the root kubepods group needs to have a non-default cpu.weight/shares. As mentioned above this shouldn't be needed for scheduling in regards to k8s pods against each other.

### How can we reproduce it (as minimally and precisely as possible)?

The issue can be easily reproduced outside of kubernetes by just creating the needed cgroups manually:

Create a cgroup (note this is v2 so default is 100):

```
cgcreate -g cpu:/kubepods
cgset -r cpu.weight=1000 kubepods
```

Run outside of the cgroup:

```
taskset -c 11 fio --name=write_iops --directory=/mnt/xfs --size=10G
--time_based --runtime=1m --ramp_time=10s \
  --ioengine=libaio --direct=1 --verify=0 --bs=4K --iodepth=128
--rw=randwrite --group_reporting=1  --iodepth_batch_submit=128
--iodepth_batch_complete_max=128
...
   iops        : min=200338, max=200944, avg=200570.37, stdev=60.93, samples=120
...
```

Now run inside the cgroup:

```
cgexec -g cpu:kubepods -- taskset -c 11 fio --name=write_iops
--directory=/mnt/xfs --size=10G --time_based --runtime=1m \
  --ramp_time=10s --ioengine=libaio --direct=1 --verify=0 --bs=4K
--iodepth=128 --rw=randwrite --group_reporting=1
--iodepth_batch_submit=128  --iodepth_batch_complete_max=128
...
   iops        : min=113589, max=120554, avg=116073.72, stdev=1334.46,
samples=120
...
```

We see that we almost lost 50% of our IOPS (potentially worse if the disks could actually go faster).

This is on:

 - Amazon Linux 2023 / 6.1 Linux
 - i3en.3xlarge instance / 200k IOPS@4K write
 - XFS filesystem

### Anything else we need to know?

We can also further debug of why this is happening at the kernel level (also posted [here](https://lore.kernel.org/linux-fsdevel/CAM9ScsHJ1zQ4j+0J+jQ1fUyRvxTMCF9OKC9kcvD5uyQZKxN1Pg@mail.gmail.com/T/#u)):

Comparing cpu time and context switches we see that in the bad case we are context switching a lot more. Overall the core is running at 100% in the bad case while only at something like 50% in the good case.

no-cgroup: task clock of fio:

```
perf stat -e task-clock -p 27393 -- sleep 1

 Performance counter stats for process id '27393':

            442.62 msec task-clock                       #    0.442
CPUs utilized

       1.002110208 seconds time elapsed
```

no cgroup: context switches on that core:

```
perf stat -e context-switches -C 11  -- sleep 1

 Performance counter stats for 'CPU(s) 11':

            103001      context-switches

       1.001048841 seconds time elapsed
```

Using the cgroup: task clock of fio:

```
perf stat -e task-clock -p 27456 -- sleep 1

 Performance counter stats for process id '27456':

            695.30 msec task-clock                       #    0.695
CPUs utilized

       1.001112431 seconds time elapsed
```

Using the cgroup: context switches on that core:

```
perf stat -e context-switches -C 11  -- sleep 1

 Performance counter stats for 'CPU(s) 11':

            243755      context-switches

       1.001096517 seconds time elapsed
```

So we are doing about 2.5x more context switches in the bad case. Doing the math at about ~120k IOPS we see that for every IOP we are doing two interrupts (in and out).

Finally we can also look at some perf sched traces to get an idea for what is happening (sched_stat_runtime calls omitted):

The general pattern in the good case seems to be:

```
fio 28143 [011]  2038.648954:       sched:sched_waking:
comm=kworker/11:68 pid=27489 prio=120 target_cpu=011
        ffffffff9f0d7ba3 try_to_wake_up+0x2b3 ([kernel.kallsyms])
        ffffffff9f0d7ba3 try_to_wake_up+0x2b3 ([kernel.kallsyms])
        ffffffff9f0b91d5 __queue_work+0x1d5 ([kernel.kallsyms])
        ffffffff9f0b93a4 queue_work_on+0x24 ([kernel.kallsyms])
        ffffffff9f3bb04c iomap_dio_bio_end_io+0x8c ([kernel.kallsyms])
        ffffffff9f53749d blk_mq_end_request_batch+0xfd ([kernel.kallsyms])
        ffffffff9f7198df nvme_irq+0x7f ([kernel.kallsyms])
        ffffffff9f113956 __handle_irq_event_percpu+0x46 ([kernel.kallsyms])
        ffffffff9f113b14 handle_irq_event+0x34 ([kernel.kallsyms])
        ffffffff9f118257 handle_edge_irq+0x87 ([kernel.kallsyms])
        ffffffff9f033eee __common_interrupt+0x3e ([kernel.kallsyms])
        ffffffff9fa023ab common_interrupt+0x7b ([kernel.kallsyms])
        ffffffff9fc00da2 asm_common_interrupt+0x22 ([kernel.kallsyms])
        ffffffff9f297a4b internal_get_user_pages_fast+0x10b ([kernel.kallsyms])
        ffffffff9f591bdb __iov_iter_get_pages_alloc+0xdb ([kernel.kallsyms])
        ffffffff9f591ef9 iov_iter_get_pages2+0x19 ([kernel.kallsyms])
        ffffffff9f5269af __bio_iov_iter_get_pages+0x5f ([kernel.kallsyms])
        ffffffff9f526d6d bio_iov_iter_get_pages+0x1d ([kernel.kallsyms])
        ffffffff9f3ba578 iomap_dio_bio_iter+0x288 ([kernel.kallsyms])
        ffffffff9f3bab72 __iomap_dio_rw+0x3e2 ([kernel.kallsyms])
        ffffffff9f3baf8e iomap_dio_rw+0xe ([kernel.kallsyms])
        ffffffff9f45ff58 xfs_file_dio_write_aligned+0x98 ([kernel.kallsyms])
        ffffffff9f460644 xfs_file_write_iter+0xc4 ([kernel.kallsyms])
        ffffffff9f39c876 aio_write+0x116 ([kernel.kallsyms])
        ffffffff9f3a034e io_submit_one+0xde ([kernel.kallsyms])
        ffffffff9f3a0960 __x64_sys_io_submit+0x80 ([kernel.kallsyms])
        ffffffff9fa01135 do_syscall_64+0x35 ([kernel.kallsyms])
        ffffffff9fc00126 entry_SYSCALL_64_after_hwframe+0x6e ([kernel.kallsyms])
                   3ee5d syscall+0x1d (/usr/lib64/libc.so.6)
              2500000025 [unknown] ([unknown])

fio 28143 [011]  2038.648974:       sched:sched_switch: prev_comm=fio
prev_pid=28143 prev_prio=120 prev_state=R ==> next_comm=kworker/11:68
next_pid=27489 next_prio=120
        ffffffff9fa0d002 __schedule+0x282 ([kernel.kallsyms])
        ffffffff9fa0d002 __schedule+0x282 ([kernel.kallsyms])
        ffffffff9fa0d3aa schedule+0x5a ([kernel.kallsyms])
        ffffffff9f135a36 exit_to_user_mode_prepare+0xa6 ([kernel.kallsyms])
        ffffffff9fa050fd syscall_exit_to_user_mode+0x1d ([kernel.kallsyms])
        ffffffff9fa01142 do_syscall_64+0x42 ([kernel.kallsyms])
        ffffffff9fc00126 entry_SYSCALL_64_after_hwframe+0x6e ([kernel.kallsyms])
                   3ee5d syscall+0x1d (/usr/lib64/libc.so.6)
              2500000025 [unknown] ([unknown])

kworker/11:68-d 27489 [011]  2038.648984:       sched:sched_switch:
prev_comm=kworker/11:68 prev_pid=27489 prev_prio=120 prev_state=I ==>
next_comm=fio next_pid=28143 next_prio=120
        ffffffff9fa0d002 __schedule+0x282 ([kernel.kallsyms])
        ffffffff9fa0d002 __schedule+0x282 ([kernel.kallsyms])
        ffffffff9fa0d3aa schedule+0x5a ([kernel.kallsyms])
        ffffffff9f0ba249 worker_thread+0xb9 ([kernel.kallsyms])
        ffffffff9f0c1559 kthread+0xd9 ([kernel.kallsyms])
        ffffffff9f001e02 ret_from_fork+0x22 ([kernel.kallsyms])
```

fio is busy submitting aio events and gets interrupted from the nvme interrupts at which point control is yielded to the dio thread which handles the completion and yields back to fio.

Looking at the bad case there now seems to be some form of ping pong:

```
fio 28517 [011]  2702.018634:       sched:sched_switch: prev_comm=fio
prev_pid=28517 prev_prio=120 prev_state=S ==> next_comm=kworker/11:68
next_pid=27489 next_prio=120
        ffffffff9fa0d002 __schedule+0x282 ([kernel.kallsyms])
        ffffffff9fa0d002 __schedule+0x282 ([kernel.kallsyms])
        ffffffff9fa0d3aa schedule+0x5a ([kernel.kallsyms])
        ffffffff9f39de89 read_events+0x119 ([kernel.kallsyms])
        ffffffff9f39e042 do_io_getevents+0x72 ([kernel.kallsyms])
        ffffffff9f39e689 __x64_sys_io_getevents+0x59 ([kernel.kallsyms])
        ffffffff9fa01135 do_syscall_64+0x35 ([kernel.kallsyms])
        ffffffff9fc00126 entry_SYSCALL_64_after_hwframe+0x6e ([kernel.kallsyms])
                   3ee5d syscall+0x1d (/usr/lib64/libc.so.6)
             11300000113 [unknown] ([unknown])

kworker/11:68+d 27489 [011]  2702.018639:       sched:sched_waking:
comm=fio pid=28517 prio=120 target_cpu=011
        ffffffff9f0d7ba3 try_to_wake_up+0x2b3 ([kernel.kallsyms])
        ffffffff9f0d7ba3 try_to_wake_up+0x2b3 ([kernel.kallsyms])
        ffffffff9f0fa9d1 autoremove_wake_function+0x11 ([kernel.kallsyms])
        ffffffff9f0fbb90 __wake_up_common+0x80 ([kernel.kallsyms])
        ffffffff9f0fbd23 __wake_up_common_lock+0x83 ([kernel.kallsyms])
        ffffffff9f39f9df aio_complete_rw+0xef ([kernel.kallsyms])
        ffffffff9f0b9c35 process_one_work+0x1e5 ([kernel.kallsyms])
        ffffffff9f0ba1e0 worker_thread+0x50 ([kernel.kallsyms])
        ffffffff9f0c1559 kthread+0xd9 ([kernel.kallsyms])
        ffffffff9f001e02 ret_from_fork+0x22 ([kernel.kallsyms])

kworker/11:68+d 27489 [011]  2702.018642:       sched:sched_switch:
prev_comm=kworker/11:68 prev_pid=27489 prev_prio=120 prev_state=R+ ==>
next_comm=fio next_pid=28517 next_prio=120
        ffffffff9fa0d002 __schedule+0x282 ([kernel.kallsyms])
        ffffffff9fa0d002 __schedule+0x282 ([kernel.kallsyms])
        ffffffff9fa0d4cb preempt_schedule_common+0x1b ([kernel.kallsyms])
        ffffffff9fa0d51c __cond_resched+0x1c ([kernel.kallsyms])
        ffffffff9f0b9c56 process_one_work+0x206 ([kernel.kallsyms])
        ffffffff9f0ba1e0 worker_thread+0x50 ([kernel.kallsyms])
        ffffffff9f0c1559 kthread+0xd9 ([kernel.kallsyms])
        ffffffff9f001e02 ret_from_fork+0x22 ([kernel.kallsyms])
```

fio is sleeping in io_getevents waiting for all events to complete. The dio worker thread gets scheduled in handling aio completions one by one. This allows fio to wake as there are some amount of completions ready for it to process. Now because of the high weight of the fio process the kernel worker only gets a short amount of runtime and gets preempted by the scheduler yielding back to fio (notice the stack and R+ in the above trace). However because fio is waiting for all aios to complete it wakes up and goes straight back to sleep again. This ping pong continues.

### Kubernetes version

1.25

### Cloud provider

All / AWS EKS

### Container runtime (CRI) and version (if applicable)

containerd

**Comment by dims** [comment]
cc @cartermckinnon @mmerkes

**Comment by AnishShah** [comment]
sig-node triage meeting:

@harche will look into it.

/triage accept
/priority important-longterm

**Comment by harche** [comment]
@StephanDollberg, thanks for filing this issue. It seems you have already [reached out to the kernel community](https://lore.kernel.org/linux-fsdevel/CAM9ScsHJ1zQ4j+0J+jQ1fUyRvxTMCF9OKC9kcvD5uyQZKxN1Pg@mail.gmail.com/T/#u).

If performance degradation is observed while running a task within a cgroup (which, in the case of Kubernetes, would typically be kubepods.slice), it needs to be addressed at the kernel level. Unfortunately, since containers are central to running workloads on Kubernetes hosts, there is no way for Kubernetes to run a process (container) outside of a cgroup.

Since there is nothing that needs to be changed in Kubernetes to fix this issue, I would like to close it. 

/close

**Comment by StephanDollberg** [comment]
> If performance degradation is observed while running a task within a cgroup (which, in the case of Kubernetes, would typically be kubepods.slice), it needs to be addressed at the kernel level. Unfortunately, since containers are central to running workloads on Kubernetes hosts, there is no way for Kubernetes to run a process (container) outside of a cgroup.

The suggestion was not to run outside of a cgroup. As described in the ticket the degradation happens because Kubernetes sets the cpu weight of the kubepods slice extremely high. So this isn't just a kernel issue. At the end of the day the scheduler just does what it's told to do.

**Comment by harche** [comment]
This is being discussed in this issue - https://github.com/kubernetes/kubernetes/issues/72881

specifically this comments highlights how setting higher kubepods slice cpu.weight (or cpu.share for v1) and not updating system slice hurts - https://github.com/kubernetes/kubernetes/issues/72881#issuecomment-821224980 

This was recently brought up in a sig-node meeting, and it was decided to isolate compressible resources like cpu and set the appropriate values on system slice. Work in progress PR - https://github.com/kubernetes/kubernetes/pull/125982

**Comment by StephanDollberg** [comment]
Thanks yeah that looks related. I will keep watching those.

One thing to note here, I don't actually think adjusting the `/system.slice` would help in this case as all the kernel threads don't run in the `/system.slice` but rather as children of the `/` slice.

**Comment by harche** [comment]
```bash
[root@ip-10-0-46-60 cgroup]# cat system.slice/cpu.weight
100
[root@ip-10-0-46-60 cgroup]# cat kubepods.slice/cpu.weight
137
[root@ip-10-0-46-60 cgroup]# cat cpu.weight 
cat: cpu.weight: No such file or directory
[root@ip-10-0-46-60 cgroup]# 
```
How would you set the cpu.weight for the children of `/`?

**Comment by StephanDollberg** [comment]
You can't I think, they default to 100/1024 from my (limited) understanding.

This is really part of the problem as that would for example be an easy workaround that we could apply.

**Comment by wenjianhn** [comment]
I don't think it's cgroup cpu.shares that starves kernel threads ,
since the kernels threads are under the root cgroup.

**Comment by StephanDollberg** [comment]
Please the reproducer above. The root cgroup has the default weight.

**Comment by travisdowns** [comment]
Please consider re-opening this. It seems it was closed in error or based on a misunderstanding of the original report.
