### ISSUE TITLE
When a deployment selects a node with the kubelet service not running as the nodeName, the Pods will remain in the pending state, then move to Terminating, and new Pods will be continuously created in a loop, resulting in a large number of Terminating Pods that cannot be terminated.

### ISSUE THREAD

**Issue by 905049079** [kubernetes/kubernetes#125427]
### What happened?

When a deployment selects a node with the kubelet service not running as the nodeName, the Pods will remain in the pending state, then move to Terminating, and new Pods will be continuously created in a loop, resulting in a large number of Terminating Pods that cannot be terminated.

### What did you expect to happen?

Waiting for the node to be ready, the Pods remain in the pending state.

### How can we reproduce it (as minimally and precisely as possible)?

1：create app
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
      nodeName: host3.example.com

2： disable kubelet
systemctl disable kubelet

3：host3.example.com 
reboot

### Kubernetes version

[root@host1 ~]#  kubectl version --output=yaml
clientVersion:
  buildDate: "2023-10-18T11:44:31Z"
  compiler: gc
  gitCommit: b8609d4dd75c5d6fba4a5eaa63a5507cb39a6e99
  gitTreeState: clean
  gitVersion: v1.26.10
  goVersion: go1.20.10
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-10-18T11:33:36Z"
  compiler: gc
  gitCommit: b8609d4dd75c5d6fba4a5eaa63a5507cb39a6e99
  gitTreeState: clean
  gitVersion: v1.26.10
  goVersion: go1.20.10
  major: "1"
  minor: "26"
  platform: linux/amd64

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chengjoey** [comment]
Specifying `nodeName` is not a good option. The scheduler will skip the selection and will not determine the node status. It will directly schedule the pod to the corresponding node. You should use affinity or selector

**Comment by AnishShah** [comment]
sig-node triage meeting:

/close

This is WAI
