### ISSUE TITLE
Can k8s restrict kubelet from using kmem through configuration

### ISSUE THREAD

**Issue by smallemployees** [kubernetes/kubernetes#125476]
### What happened?

Can k8s restrict kubelet from using kmem through configuration

### What did you expect to happen?

Which specific version is supported

### How can we reproduce it (as minimally and precisely as possible)?

Which specific version is supported

### Kubernetes version

<details>
1.19
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mauri870** [comment]
I'm not sure if this is a question or a bug report, so tentatively marking it as support.

/kind support

**Comment by ffromani** [comment]
Hi, could you please elaborate a bit more the scenario? e.g. what's `kmem` in this context, and how woule you like the kubelet to act?
