### ISSUE TITLE
Scheduler algorithm rename breaks backwards compatibility

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#12542]
1.0.0 shipped with `ServiceSpreadingPriority` (https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go#L70). The rename at https://github.com/GoogleCloudPlatform/kubernetes/pull/10667/files#r36776577 breaks backwards compatibility with serialized scheduler config files.

We should:
1. Add a test for backwards compatibility with the serialized version of the priorities/algorithms
2. Alias or revert the rename to that priority algorithm

**Comment by liggitt** [comment]
Looks like it was more than just a rename, but a change in function as well...

**Comment by liggitt** [comment]
cc @abhgupta

**Comment by abhgupta** [comment]
Pasting my comment from https://github.com/openshift/origin/issues/4112#issuecomment-129996433

The previous priority function (ServiceSpreadingPriority) ONLY considered services and the new priority function (SelectorSpreadPriority) considers both services and replication controllers for spreading.

Do we need to ensure backward compatibility in functionality as well? As in, do we create a ServiceSpreadingPriority that uses the new priority function but ignores the replication controllers (perhaps by passing an empty lister for RCs)?

**Comment by bgrant0607** [comment]
cc @davidopp

**Comment by liggitt** [comment]
Opened #12544 with deserialize test and empty ControllerLister implementation, per @abhgupta's suggestion

**Comment by davidopp** [comment]
Sorry for the trouble.

Yeah, the reason we changed the name was because we changed the behavior.

My proposal wold be that we take what we have now and add back ServiceSpreadingPriority with the same behavior as the old ServiceSpreadingPriority. (That is, SelectorSpreadPriority would be strictly an addition.)

WDYT?

**Comment by liggitt** [comment]
works for me. I think that's what my PR does, eyes welcome
