### ISSUE TITLE
1.31 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by npolshakova** [kubernetes/kubernetes#125569]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.31 Release Notes. If you know of issues or API changes that are going out in 1.31, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/sig release
/milestone v1.31

**Comment by npolshakova** [comment]
https://github.com/kubernetes/kubernetes/pull/126287#issuecomment-2251943946

**Comment by npolshakova** [comment]
With 1.31 you can't re-apply the same CRD YAMLs that worked before anymore (without dropping the invalid caBundle field). Slack context: https://kubernetes.slack.com/archives/C0EG7JC6T/p1722441161968339

Before Kubernetes 1.31 rc.0 we were able to apply CRDs with the following multiple times:
```
      clientConfig:
        caBundle: Cg==
````

After https://github.com/kubernetes/kubernetes/pull/124061, the 2nd apply fails with
`CustomResourceDefinition.apiextensions.k8s.io "clusterclasses.cluster.x-k8s.io" is invalid: spec.conversion.webhookClientConfig.caBundle: Invalid value: []byte{0xa}: unable to load root certificates: unable to parse bytes as PEM block`.

With < 1.31 you could apply the CRD YAMLs with caBundle: Cg== multiple times. While the caBundle was invalid, cert-manager-cainjector fixed them up immediately.

**Comment by npolshakova** [comment]
Addressed in https://github.com/kubernetes/sig-release/pull/2579

**Comment by carlory** [comment]
All containers restart after kubelet upgrade to v1.31: https://github.com/kubernetes/kubernetes/issues/129385#issuecomment-2561367173
