### ISSUE TITLE
The cluster kube-scheduler scheduling is unbalanced, causing the pod to hang and fail to run, even though there are currently idle nodes

### ISSUE THREAD

**Issue by Giant-goose** [kubernetes/kubernetes#125503]
### What happened?

I have 10 nodes in my cluster, and I keep the default cluster scheduling mechanism without configuring the manual scheduling mechanism for tasks (including node taints, label scheduling affinity, etc., and the configuration of pod limit request), but I found that one of my pods will use up 50% of the node's memory after running for a period of time, and the total memory occupied by other nodes of this node is more than 90%. But when I restarted this pod, I found the first problem, it was still scheduled to this node, although there were other nodes with only 30% memory usage, and the second problem was that I found that the pod seemed to like this node very much, and other newly started pods would also be assigned to this 90% load machine, resulting in these pod tasks can only be suspended, can not run, resulting in business stagnation. Why is this?

Off topic: I understand that you can use artificial scheduling mechanism to solve this problem, but the default scheduling I found from the official website's documentation explanation is to score nodes, and there is no additional mechanism to affect other I am very curious about this problem, and I found that many people in the k8s community have encountered this problem.

### What did you expect to happen?

I want to know two questions about the above:
1. Regarding the node score, even though the load of this node is 90%, why is its score still higher than other nodes or is it scheduled to this machine for other reasons?
2. Why do subsequent pods like to run on this node so much, when there are other nodes and their models and configurations are exactly the same? Is there any data affinity (pod will look for the node where the data was stored last time to reduce the cluster's response time and performance consumption)?

### How can we reproduce it (as minimally and precisely as possible)?

This is a long-term practical problem

### Anything else we need to know?

![187d5c530b74963a020687139c0cc24](https://github.com/kubernetes/kubernetes/assets/66284983/7d3996d3-3523-47d2-b58f-a04529838206)
![8612d5413d9fd36f5052b6b1ea96936](https://github.com/kubernetes/kubernetes/assets/66284983/cbd2348e-aaac-41ab-8f34-f0dfec06f59f)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
v1.26.1

### Cloud provider

<details>

</details>
aws and tencent k8s cluster

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
centos7

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>
kubeadm

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
1.26 is no longer in support. also better to ask on support channels.

please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
