### ISSUE TITLE
Pods gated by custom PreEnqueue plugins don't go through backoffQ even in case they ought to

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#125538]
### What happened?

With the current implementation, all gated Pods are always regarded as **not** backing off.

https://github.com/kubernetes/kubernetes/blob/ef9965ebc66dafda37800bb04f5e284535bbba10/pkg/scheduler/internal/queue/scheduling_queue.go#L658-L661

That is correct for a vanilla scheduler because all Pods gated by SchedulingGates are not backing off for sure,
but, not correct for a custom scheduler with out-of-tree PreEnqueue plugins,
which could gate Pods that already have gone through scheduling cycles (and got unschedulable).

### What did you expect to happen?

Pods which have gone through scheduling cycles, but now gated should be put into backoffQ. (or activeQ, if it's in the unschedQ for enough time already)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Pod that cannot be scheduled.
2. After a Pod got unschedulable, custom PreEnqueue plugin gates the Pod.
3. Trigger a cluster event which could make the Pod schedulable, and with this event, remove a gate.
4. The Pod directly goes to activeQ, not going through backoffQ, while it's once gone through a scheduling cycle.

### Kubernetes version

master

### Cloud provider

<details>
n/a
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
I don't consider this a bug, as PreEnqueue was not initially designed for Pods that went through the scheduling cycle already.

/remove-kind bug
/kind feature

In any case, I'm happy to review a reasonable proposal.

**Comment by kerthcet** [comment]
Current design is reasonable to me, so again ping @Huang-Wei

**Comment by sanposhiho** [comment]
@kerthcet moving the discussion here:

To reply to your last comment
> I don't know if we have such case, but if a pod is gated again, it means it's not ready, maybe it should restart the scheduling lifecycle.. my two cents. Let's track this under your issue then.
https://github.com/kubernetes/kubernetes/pull/125527#discussion_r1645373474

At least, we have a usecsae here -
https://github.com/pfnet/scheduler-plugins/tree/master/plugins/gang
(wow hello again 😅 I've brought it into several discussion)

What it does with PreEnqueue is-
> We also use PreEnqueue in https://github.com/pfnet/scheduler-plugins/tree/master/plugins/gang (gang scheduling); PreEnqueue allows Pods to enter scheduling cycles iff all Pods in the group are now ready to retry scheduling.
e.g., When gangA-pod1 is rejected by plugin-1 and when gangA-pod2 is rejected by plugin-2, we want to requeue all gangA Pods iff the scheduling queue observes some cluster events that could change the scheduling results of gangA-pod1 and gangA-pod2. (i.e., when QHints of plugin-1 and plugin-2 returns Queue for those Pods)
https://github.com/kubernetes/kubernetes/issues/125223#issuecomment-2174787844

So, Pods once got un-gated could get gated again.

To clarify, from less-subjective view, we have two options here:
- Add `once PreEnqueue allows a Pod to enter a scheduling cycle, PreEnqueue shouldn't gate the Pod again` to PreEnqueue specification.
- Fix the behaviour like the issue description at the top argues in `What did you expect to happen?`.

And, (as you know) I'm tend to the second option. I don't see any big reason that we have to limit the usage of PreEnqueue like the first one said.

**Comment by kerthcet** [comment]
I can break this into two parts:
- A single Pod
- A group of Pods

I mostly pointed to the single Pod, I feel a re-gated Pod should restart the whole lifecycle of scheduling, backoffQ is designed for not blocking the queue however gated Pods will not enter into the queue.

For a group of Pods, it's much more complex, like if a Pod failed in scheduling, it should be marked as unschedulable or gated again, maybe unschedulable, then it's already under backoff. And they should be re-scheduled first next time because they're the main reason blocking the whole group. When scheduling timeout, how to handle these Pods, assumedPods should be gated again maybe, unscheduledPod should still be unscheduledPods, backoffing in the background?

So the total workflow is still unclear to me, but that's what I'm working for right now. Always open to new ideas :)

**Comment by sanposhiho** [comment]
Okay, so the first thing not a direct answer to your last comment (sorry), but let me confirm one thing as I feel like we're not on the same base page.

So, this issue does not depend on which kind of Pods they are. The point that I cannot justify the current behaviour is more general.

Reviewing the concept of backoff just in case, backoff time is a [penalty](https://github.com/kubernetes/kubernetes/blob/09472b673d9e34b866fbd41c544887ba60d7ca7b/pkg/scheduler/framework/interface.go#L93-L95) that we impose on Pods when they consume a scheduling cycle, but they didn't get scheduled and came back to the queue.
So, regardless of whether a Pod is gated or not, they are supposed to get a penalty if they waste some scheduling cycles. It's the law in the scheduler; it's their obligation that they must meet before retrying a schedule again.
 
However, the current situation this issue highlights is, if they gated again, they somehow get immune from this penalty.
Let's say Pods have failed at scheduling 1k times before, but if they were being gated in the queue even during a moment, they bypass backoff, which is illegal. That's my point that I want to clarify with this PR.

---

Then, answering your questions,
> I feel a re-gated Pod should restart the whole lifecycle of scheduling, backoffQ is designed for not blocking the queue however gated Pods will not enter into the queue.

Why is it better to restart a whole lifecycle of scheduling? 

My point is, again -
> Let's say Pods have failed at scheduling 1k times before, but if they were being gated in the queue even during a moment, they bypass backoff, which is illegal.

So, Pod should not restart a whole lifecycle, but the scheduling queue should remember this guy has failed at scheduling 1k times, and then impose a backoff penalty on them.

Usecase-wise, DRA's PreEnqueue, which is not a plugin schedules a group of Pods, could gate a Pod once it allows. (e.g., when a claim for Pod-A is deleted somehow after Pod-A's scheduling failure)

> For a group of Pods

Sorry, I don't quite understand what you have in your mind. 

But, let me elaborate our gang plugin's behaviour around retrying:

1. Let's say Pod1, Pod2 and Pod3 are in the same group and they're just created, going to scheduling cycles.
2. Pod1 and Pod2 goes thru Filter phase, and waiting for Pod3 (waitOnPermit).
3. Pod3, unfortunately, is rejected by noderesourcefit. 
4. Pod3 goes back to unschedQ.
5. Also, we bring back Pod1 and Pod2 to unschedQ too, without waiting for timeout they have. The reason is for "waiting Pods reserve too large space in a cluster https://github.com/kubernetes/enhancements/issues/4671#issuecomment-2141307013"
6. Now, Pod1 and Pod2 have `unschedPlugin: gang` and Pod3 has `unschedPlugin: noderesourcefit`. 
7. This group won't be schedulable until Pod3's failure is resolved. So, Pod1 and Pod2 will be gated until Pod3's failure is solved.
8. And, when the scheduler receives an event that is registered in noderesourcefit ([if QHint enabled] + when QHint returns `Queue` to the event ), Pod3 is moved from unschedQ to activeQ or backoffQ because Pod3 _may_ be schedulable now. 
9. Then, move Pod1 and Pod2 to activeQ/backoffQ too so that all Pods in this group are again proceeding to scheduling cycles.
10. Then, if you're lucky, all Pods are scheduled successfully. If you're not, some of them might be unschedulable, and we're doing the same process of requeueing again.
