### ISSUE TITLE
StatusCause "field" should not contain multiple field names

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#12552]
https://github.com/GoogleCloudPlatform/kubernetes/pull/9594/files#diff-e77d382a51b51741c1c2b9803fb68fa2R159 introduced the ability to let a single field contain multiple names separated by a literal " or ".

Any client or UI that uses the name of a field in a returned error to correlate errors with inputs will be unable to parse that.

If the data structure is insufficient to express a type of error, we should change the structure, but we can't cram a sentence into a field intended to be parsed programmatically

**Comment by liggitt** [comment]
cc @bgrant0607 for API compatibility

**Comment by liggitt** [comment]
cc @deads2k

**Comment by bgrant0607** [comment]
cc @manansaraf @ghodss

**Comment by bgrant0607** [comment]
So this depends on whether we feel this field should be directed at humans, programs, or both. A more structured form is more convenient for programs, but less convenient for humans.

Until we figure out a better approach, I'm fine with reverting that PR.

**Comment by bgrant0607** [comment]
BTW, how did you catch this?

**Comment by liggitt** [comment]
we have unit tests to make sure all OpenShift API objects pass through sufficiently strict validators on the way to storage. The latest rebase changed the field on the error returned when missing a name from "name" to "name or generateName", which raised eyebrows

**Comment by ghodss** [comment]
Yeah, we didn't like the idea of cramming a sentence into the field but after a thorough overview the conclusion was that any other solution would require a tremendous amount of refactoring (likely at least one or two weeks) because of how many places the struct was used directly. No problem if it gets reverted, though we'd lose the usability win we have in the current implementation.

**Comment by liggitt** [comment]
As far as I can tell, the only place using it currently is the "name or generateName" validation. I think it would make more sense to keep the required field limited to "name", and populate the detail message with info about alternately providing the generateName field
