### ISSUE TITLE
Add Limit and Continue to ListRestrictions on client-go

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes/kubernetes#125554]
### What would you like to be added?

As mentioned on the title, add Limit and Continue to ListRestrictions on client-go.

### Why is this needed?

We need to test logic with `Limit` and `Continue` options. But fake SimpleClientset don't allow to do it. We already discussed it [here](https://github.com/kubernetes/client-go/issues/793#issuecomment-620763574). I agree with this point, but we can also add `Limit` and `Continue` options to `ListRestrictions` [here](https://github.com/kubernetes/client-go/blob/master/testing/actions.go#L354). It will allow us to manually filtering list using `Reactor`.

**Comment by neolit123** [comment]
> We need to test logic with Limit and Continue options. But fake SimpleClientset don't allow to do it. We already discussed it https://github.com/kubernetes/client-go/issues/793#issuecomment-620763574. I agree with this point, but we can also add Limit and Continue options to ListRestrictions [here](https://github.com/kubernetes/client-go/blob/master/testing/actions.go#L354). It will allow us to manually filtering list using Reactor.

/sig api-machinery

**Comment by seans3** [comment]
/assign @liggitt 

Can you have a look at this, since you also responded to: https://github.com/kubernetes/client-go/issues/793#issuecomment-620763574

/triage accepted

**Comment by mbobrovskyi** [comment]
Close because options support already added on #125560

/close
