### ISSUE TITLE
Collect logfiles inside the container

### ISSUE THREAD

**Issue by wulonghui** [kubernetes/kubernetes#12567]
## Logs to stdout/stderr
Currently, it's ok to collect container's logs which are printed to `stdout/stderr`.
According to [kubernetes/fluentd-eslasticsearch](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/pkg/volume) addon, kubelet links the docker containers' log to  `/var/log/containers`,
```
/var/log/containers/<pod_full_name>_<container_name>-<container_id>.log -> /var/lib/docker/containers/<container_id>/<container_id>-json.log
```
then fluentd tails the logfiles in `/var/log/containers`, and add the tag `<pod_full_name>_<container_name>-<container_id> `to log record by parsing the path.

## Logs in files
Now want to collect the logfiles inside the container. 
Firstly, should use volume mount the logdir , 

### HostPath Volume
Mount the logdir(/log) by HostPath Volume, like:
```
/var/log/pods/<pod_name> => /log
```
Use `/var/log/pods/<pod_name>` to persist the logs, it's configured manually, so fluentd can distinguish the logs file also.
But all the pod's instances will use the same HostPath(/var/log/pods/<pod_name>), this can cause conflict.

## EmptyDIr Volume
Mount the logdir(/log) by EmptyDIr Volume, like:
```
/var/lib/kubelet/pods/<pod_id>/volumes/kubernetes.io~empty-dir/log-storage => /log
```
fluentd can tail the logfiles in `/var/lib/kubelet/pods/<pod_id>/volumes/kubernetes.io~empty-dir/log-storage `,  but the path only include `pod_id`,   pod_id changes when pod migrates, so I don't think it's ok to be the tag.

Any better solution?

**Comment by goltermann** [comment]
Closing this support issue, I believe everything is covered in the linked proposal at #13010
