### ISSUE TITLE
kube-apiserver logs watch requests before they end in 1.30

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#125614]
### What happened?

In 1.30, WATCH request is logged immediately when a watch is opened, with very low latency. There appears to be no trace of when the watch ends. This significantly impacts debugging capability for issues with establishing watches. 

Example for consecutive watches on pods opened by kube-scheduler - each appears to be lasting 8-9 minutes, everything works in the cluster, but the latency doesn't match watch length, the request is logged immediately, and with `resp=0`:

```
I0620 12:33:17.389016      11 httplog.go:132] "HTTP" verb="WATCH" URI="/api/v1/pods?allowWatchBookmarks=true&fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&resourceVersion=97186&timeout=9m12s&timeoutSeconds=552&watch=true" latency="470.891µs" userAgent="kube-scheduler/v1.30.2 (linux/amd64) kubernetes/85fad5b/scheduler" audit-ID="2cf3b6d8-8c04-4065-8bb8-ccd209f24063" srcIP="[::1]:60566" apf_pl="workload-high" apf_fs="kube-scheduler" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_init_latency="252.569µs" apf_execution_time="253.277µs" resp=0
...
I0620 12:42:29.390797      11 get.go:261] "Starting watch" path="/api/v1/pods" resourceVersion="135790" labels="" fields="status.phase!=Failed,status.phase!=Succeeded" timeout="6m10s"
I0620 12:42:29.391006      11 httplog.go:132] "HTTP" verb="WATCH" URI="/api/v1/pods?allowWatchBookmarks=true&fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&resourceVersion=135790&timeout=6m10s&timeoutSeconds=370&watch=true" latency="629.842µs" userAgent="kube-scheduler/v1.30.2 (linux/amd64) kubernetes/85fad5b/scheduler" audit-ID="619843d2-3f2a-4c2e-960a-17eecc71695b" srcIP="[::1]:60566" apf_pl="workload-high" apf_fs="kube-scheduler" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_init_latency="299.938µs" apf_execution_time="300.55µs" resp=0
```

### What did you expect to happen?

Watches are usually long (~minutes). In 1.29 and earlier log looks like this:

```
I0620 12:30:26.940451      11 get.go:260] "Starting watch" path="/api/v1/pods" resourceVersion="93431" labels="" fields="status.phase!=Failed,status.phase!=Succeeded" timeout="8m18s"
...
I0620 12:38:44.940817      11 httplog.go:132] "HTTP" verb="WATCH" URI="/api/v1/pods?allowWatchBookmarks=true&fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&resourceVersion=93431&timeout=8m18s&timeoutSeconds=498&watch=true" latency="8m18.00060226s" userAgent="kube-scheduler/v1.29.6 (linux/amd64) kubernetes/43a444e/scheduler" audit-ID="c39f0303-10ad-4b51-baf4-87c592fcb85e" srcIP="[::1]:39438" apf_pl="workload-high" apf_fs="kube-scheduler" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_init_latency="280.462µs" apf_execution_time="281.612µs" resp=200
```

### How can we reproduce it (as minimally and precisely as possible)?

Compare kube-apiserver log in 1.29 and 1.30.

### Anything else we need to know?

Log line examples are taken from passing runs of gce-scalabiltiy-100 tests: 
- https://testgrid.k8s.io/sig-scalability-gce#gce-cos-1.29-scalability-100 : https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-1-29/1803759918289784832
- https://testgrid.k8s.io/sig-scalability-gce#gce-cos-1.30-scalability-100 : https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-1-30/1803759918403031040

### Kubernetes version

Observed in 1.30.2 and 1.30.1. To be verified if present in 1.30.0..

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by mborsz** [comment]
It looks like https://github.com/kubernetes/kubernetes/pull/120902 has moved watch to a defered goroutine. IIUC this can lead to effects like this. The problem is that it changes a behavior of httplog and removes us a way to track a length of watch calls which turned out to be useful in many debugging sessions in the past.

We either should fix httplog or provide some other log with equivalent information instead (i.e. when the watch ends).

**Comment by aojea** [comment]
fortunately we were cautious and this is behind a feature gate https://github.com/kubernetes/kubernetes/pull/120902#discussion_r1430722839

```
grep -r APIServingWithRoutine {pkg,staging}
pkg/features/kube_features.go:  genericfeatures.APIServingWithRoutine: {Default: true, PreRelease: featuregate.Beta},
staging/src/k8s.io/apiserver/pkg/server/config.go:      if utilfeature.DefaultFeatureGate.Enabled(genericfeatures.APIServingWithRoutine) {
staging/src/k8s.io/apiserver/pkg/features/kube_features.go:     APIServingWithRoutine featuregate.Feature = "APIServingWithRoutine"
staging/src/k8s.io/apiserver/pkg/features/kube_features.go:     APIServingWithRoutine: {Default: true, PreRelease: featuregate.Beta},
```

**Comment by linxiulei** [comment]
> but also want to add an additional information so that we can see the latencies for both watch initialization (which allowed me to find https://github.com/kubernetes/kubernetes/pull/124692) and duration

Correction: actually there is `apf_execution_time` in the httplog, which is a proxy to initiation latency
