### ISSUE TITLE
Gracefully transition traffic when change selector of loadbalancer service

### ISSUE THREAD

**Issue by hua82556281** [kubernetes/kubernetes#125697]
### What would you like to be added?

We hope when change selector of Loadbalancer service to transition traffic from one backend to another, the status of pool member in Loadbalancer on cloud provider side can be automatically updated.

I assume the process is like below. 'blue' and 'green' stands for two backend pod labels.
After changing the selector from 'green' to 'blue', Kubernetes would first modify the endpoints to point to both nodes simultaneously. Then, the Kubernetes OpenStack Cloud Provider plugin modifies the load balancer pool status, disabling 'green'. This way, there won't be any new traffic being routed from the load balancer to 'green'. Then, Kubernetes proceeds to modify the endpoints to 'blue', completing the graceful switch from 'green' to 'blue'.

### Why is this needed?

Because when I change the selector of a Loadbalancer service I found there is always a break (less than 15sec) to establish a new connection via the loadbalancer ip address. I suppose this issue is caused by the health monitoring from loadbalancer is later than the health check of kube-proxy. So the status of pool member cannot be updated in time. The Loadbalancer still distribute the traffic to the old backend although it has been already unhealthy. So that the break occurs. If changing selector can be graceful this issue would be avoided.

**Comment by aojea** [comment]
/sig cloud-provider

> Then, the Kubernetes OpenStack Cloud Provider plugin modifies the load balancer pool status, disabling 'green'.

You should ask in the specific project https://github.com/kubernetes/cloud-provider-openstack

/sig network

> Then, Kubernetes proceeds to modify the endpoints to 'blue', completing the graceful switch from 'green' to 'blue'.

So basically you are asking to implement a mechanism to expose Services and implement blue/green deployment with zero disruptuon, @robscott @shaneutt  is this not something Gateway API community is working on?

**Comment by sftim** [comment]
Fronting two Services (`green` and `blue` perhaps) with one Gateway sounds like the way we want to go. The Services would not be `type: LoadBalancer`.

**Comment by shaneutt** [comment]
> So basically you are asking to implement a mechanism to expose Services and implement blue/green deployment with zero disruption, @robscott @shaneutt is this not something Gateway API community is working on?

Users of `HTTPRoute` today can add additional [backendRefs](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.BackendRef) which their `Gateway` implementation can then start sending traffic to in addition to the existing one:

* these are `Services` by default (but the specification allows custom types)
* these can have [weights](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.BackendRef)

So you can add a new backendRef (`Service`), test and monitor the traffic results, and then drop the old backendRef when ready. 

> **Warning**: Different [implementations](https://gateway-api.sigs.k8s.io/implementations/) may handle the transition differently, you'll want to test.

> **Note**: You also might consider using a service mesh, as these kinds of things are one of the common reason people employ them on their clusters.

So I recognize that this is not _exactly_ what you were asking for @hua82556281, but if that sounds like something that could help that all exists today in [Gateway API](https://gateway-api.sigs.k8s.io) and you could ask some questions in our [GitHub Discussions Forum](https://github.com/kubernetes-sigs/gateway-api/discussions) and we also have the `#sig-network-gateway-api` channel on [Kubernetes Slack](https://kubernetes.slack.com).

**Comment by hua82556281** [comment]
Thanks all very much. I will look into gateway api and check if it can meet.
