### ISSUE TITLE
[FG:InPlacePodVerticalScaling] resources in pod status are never updated if EventedPLEG is enabled

### ISSUE THREAD

**Issue by hshiina** [kubernetes/kubernetes#125624]
### What happened?

If eventedPLEG is enabled, resources in a pod status are never updated after the pod is resized.

### What did you expect to happen?

Resources in a pod status are updated after the pod is resized.

### How can we reproduce it (as minimally and precisely as possible)?

1. Enable `EventedPLEG` and `InPlacePodVerticalScaling`.
2. Create a pod and update resources in the pod following the [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/#updating-the-pod-s-resources).

```
$ kubectl -n qos-example patch pod qos-demo-5 --patch '{"spec":{"containers":[{"name":"qos-demo-ctr-5", "resources":{"requests":{"cpu":"800m"}, "limits":{"cpu":"800m"}}}]}}'
$ # Wait for more than 10 minutes...
$ kubectl -n qos-example get pod qos-demo-5 -o json | jq '.status.containerStatuses[0].resources'
{
  "limits": {
    "cpu": "700m",
    "memory": "200Mi"
  },
  "requests": {
    "cpu": "700m",
    "memory": "200Mi"
  }
}
```

### Anything else we need to know?

The root cause of this issue is the same problem mentioned in #124297. Evented PLEG passes a timestamp wrongly to a cache:
https://github.com/kubernetes/kubernetes/blob/5ec31e84d6c525c173906b1497ee6f075c1926e9/pkg/kubelet/pleg/evented.go#L269

EventedPLEG does not emit any event or update a cache because a runtime raises no event at resizing a container without restart. Though GenericPLEG is expected to back up in such a case, this does not work. Generic PLEG relists pods every 5 minutes. It also updates the cache when pod resizing is in progress:
https://github.com/kubernetes/kubernetes/blob/5ec31e84d6c525c173906b1497ee6f075c1926e9/pkg/kubelet/kubelet.go#L2008-L2011

However, an update from GenericPLEG is rejected because the new timestamp looks older than the existing timestamp that EventedPLEG sets at starting the pod because of the bug mentioned above:
https://github.com/kubernetes/kubernetes/blob/5ec31e84d6c525c173906b1497ee6f075c1926e9/pkg/kubelet/container/cache.go#L106-L112

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: v1.29.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
</details>

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by AnishShah** [comment]
sig-node triage meeting:

/triage accepted

**Comment by AnishShah** [comment]
sig-node triage meeting:

/priority important-longterm

**Comment by hshiina** [comment]
Only fixing #124297 will not solve this issue. If the CRI runtime doesn't set a timestamp to `PodSandboxStatusResponse` for `PodSandboxStatus()`, the generic PLEG uses `0` as a timestamp to update the cache.

As of today, containerd does not look to set the timestamp while CRI-O does:
- containerd: https://github.com/containerd/containerd/blob/2ddd3db9524b14000208862e2e578e567b391a06/internal/cri/server/sandbox_status.go#L85-L88
- CRI-O: https://github.com/cri-o/cri-o/blob/74d54cd3071c51225055df91121ebf77618e86a8/server/sandbox_status.go#L52-L65

If the timestamp is not set by the runtime, the runtime manager in kubelet does not set the timestamp in `PodStatus`:
https://github.com/kubernetes/kubernetes/blob/a2106b5f73fe9352f7bc0520788855d57fc301e1/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1565-L1612

The generic PLEG uses `0` in the `PodStatus` to update the cache:
https://github.com/kubernetes/kubernetes/blob/a2106b5f73fe9352f7bc0520788855d57fc301e1/pkg/kubelet/pleg/generic.go#L478-L482

We also need to fix this problem.

**Comment by hshiina** [comment]
I noticed this issue will not been solved even if the timestamp issues are fixed. Generic PLEG updates a pod status only when container statuses in the pod changed. A pod is resized while containers are running.

Only when a pod is resized soon after it was created, Generic PLEG can update resource information because Generic PLEG relists pods every five minutes. This happens only in testing.

**Comment by hshiina** [comment]
Alternatively, #125635 may fix this issue as a side-effect.

**Comment by hshiina** [comment]
> I noticed this issue will not been solved even if the timestamp issues are fixed. Generic PLEG updates a pod status only when container statuses in the pod changed. A pod is resized while containers are running.
> 
> Only when a pod is resized soon after it was created, Generic PLEG can update resource information because Generic PLEG relists pods every five minutes. This happens only in testing.

I misunderstood. Generic PLEG updates the cache here when a pod is being resized:
https://github.com/kubernetes/kubernetes/blob/ee74baec6e05afde972f1a8705d4f8efe066f120/pkg/kubelet/kubelet.go#L1980
So, this issue will be solved by the timestamp fix.

**Comment by hshiina** [comment]
Because of #127195, a timestamp is set to `PodStatus` even if containerd does not set the timestamp. So, this issue has been fixed.

note: containerd will set the timestamp in the future release due to containerd/containerd#10740.
