### ISSUE TITLE
[Flaking Test] UT apiserver/pkg/storage: cacher for 3m timeout

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#125688]
### Which jobs are flaking?

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit&graph-metrics=test-duration-minutes

### Which tests are flaking?

k8s.io/apiserver/pkg/storage: cacher expand_less
{Failed;Failed;  === RUN   TestWatchStreamSeparation

### Since when has it been flaking?

06-25

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

ut package timeout is 180s/3m.
- this was tracked https://github.com/kubernetes/kubernetes/issues/123850 and we may add some new test recently?

### Anything else we need to know?

some tries: https://github.com/kubernetes/kubernetes/pull/123888 

**Edited(Add some investigation process about the flake)**
- At first, I thought https://github.com/kubernetes/kubernetes/pull/125405 caused the timeout as it added a new test in the package and it is the only change in the package.
- @serathius find the root cause is  https://github.com/kubernetes/kubernetes/pull/125575 according to https://github.com/kubernetes/kubernetes/issues/125688#issuecomment-2191286621

### Relevant SIG(s)

/sig api-machinery

**Comment by p0lyn0mial** [comment]
maybe we should revisit https://github.com/kubernetes/kubernetes/pull/123990 ?

**Comment by wojtek-t** [comment]
Can we generate up-to-date version of this comment: https://github.com/kubernetes/kubernetes/issues/123850#issuecomment-1991057218

**Comment by p0lyn0mial** [comment]
Here is the list of the 60 slowest tests in the package. I've decided to run the most time-consuming [tests in parallel](https://github.com/kubernetes/kubernetes/pull/125696) to reduce the overall time quickly. On my local laptop, the execution time decreased from 150s to 130s.

```
❯ gotestsum tool slowest --num 60 --jsonfile tmp.json.log
k8s.io/apiserver/pkg/storage/cacher TestWatchStreamSeparation 12.56s
k8s.io/apiserver/pkg/storage/cacher TestWatchSemantics 11.27s
k8s.io/apiserver/pkg/storage/cacher TestWatchDispatchBookmarkEvents 5.73s
k8s.io/apiserver/pkg/storage/cacher TestCacherNoLeakWithMultipleWatchers 5.07s
k8s.io/apiserver/pkg/storage/cacher TestWatchBookmarksWithCorrectResourceVersion 4.99s
k8s.io/apiserver/pkg/storage/cacher TestCreateWithTTL 4.09s
k8s.io/apiserver/pkg/storage/cacher TestGuaranteedUpdateWithTTL 3.58s
k8s.io/apiserver/pkg/storage/cacher TestWatchStreamSeparation/separate_RPC_&_watch_cache_context_>_only_watch_cache_gets_bookmarks 3.57s
k8s.io/apiserver/pkg/storage/cacher TestWatchStreamSeparation/separate_RPC_>_only_etcd_gets_bookmarks 3.2s
k8s.io/apiserver/pkg/storage/cacher TestWatchStreamSeparation/common_RPC_&_watch_cache_context_>_both_get_bookmarks 3.09s
k8s.io/apiserver/pkg/storage/cacher TestCacherSendBookmarkEvents 3.01s
k8s.io/apiserver/pkg/storage/cacher TestWaitUntilWatchCacheFreshAndForceAllEvents/legacy:_allowWatchBookmarks=false,_sendInitialEvents=true,_RV=unset 3s
k8s.io/apiserver/pkg/storage/cacher TestGetListNonRecursiveWithConsistentListFromCache/existing_key,_resourceVersion=too_high 3s
k8s.io/apiserver/pkg/storage/cacher TestWaitUntilWatchCacheFreshAndForceAllEvents/allowWatchBookmarks=true,_sendInitialEvents=true,_RV=105 3s
k8s.io/apiserver/pkg/storage/cacher TestWatchDispatchBookmarkEvents/allowWatchBookmarks=false 3s
k8s.io/apiserver/pkg/storage/cacher TestWaitUntilWatchCacheFreshAndForceAllEvents/allowWatchBookmarks=true,_sendInitialEvents=true,_RV=unset 3s
k8s.io/apiserver/pkg/storage/cacher TestGetListNonRecursive/existing_key,_resourceVersion=too_high 3s
k8s.io/apiserver/pkg/storage/cacher TestListWithConsistentListFromCache/rejects_resource_version_set_too_high 3s
k8s.io/apiserver/pkg/storage/cacher TestGet/too_high_resource_version 3s
k8s.io/apiserver/pkg/storage/cacher TestList/rejects_resource_version_set_too_high 3s
k8s.io/apiserver/pkg/storage/cacher TestWatchSemanticInitialEventsExtended 2.84s
k8s.io/apiserver/pkg/storage/cacher TestWatchStreamSeparation/common_RPC_>_both_get_bookmarks 2.69s
k8s.io/apiserver/pkg/storage/cacher TestEmptyWatchEventCache 2.6s
k8s.io/apiserver/pkg/storage/cacher TestBookmarksOnResourceVersionUpdates 2.29s
k8s.io/apiserver/pkg/storage/cacher TestConsistentListWithConsistentListFromCache 2.21s
k8s.io/apiserver/pkg/storage/cacher TestCacherSendsMultipleWatchBookmarks 2.16s
k8s.io/apiserver/pkg/storage/cacher TestDeleteWithSuggestionOfDeletedObject 2.11s
k8s.io/apiserver/pkg/storage/cacher TestList 2.09s
k8s.io/apiserver/pkg/storage/cacher TestValidateDeletionWithSuggestion 2.09s
k8s.io/apiserver/pkg/storage/cacher TestGuaranteedUpdateWithSuggestionAndConflict 2.09s
k8s.io/apiserver/pkg/storage/cacher TestListPaginationRareObject 2.009s
k8s.io/apiserver/pkg/storage/cacher TestDispatchEventWillNotBeBlockedByTimedOutWatcher 2s
k8s.io/apiserver/pkg/storage/cacher TestConditionalDelete 1.98s
k8s.io/apiserver/pkg/storage/cacher TestWatch 1.91s
k8s.io/apiserver/pkg/storage/cacher TestDeleteWithSuggestionAndConflict 1.9s
k8s.io/apiserver/pkg/storage/cacher TestCreateWithKeyExist 1.9s
k8s.io/apiserver/pkg/storage/cacher TestSendInitialEventsBackwardCompatibility 1.89s
k8s.io/apiserver/pkg/storage/cacher TestWatchDeleteEventObjectHaveLatestRV 1.88s
k8s.io/apiserver/pkg/storage/cacher TestDelayedWatchDelivery 1.81s
k8s.io/apiserver/pkg/storage/cacher TestConsistentList 1.79s
k8s.io/apiserver/pkg/storage/cacher TestClusterScopedWatch 1.71s
k8s.io/apiserver/pkg/storage/cacher TestListWithConsistentListFromCache 1.71s
k8s.io/apiserver/pkg/storage/cacher TestListInconsistentContinuation 1.7s
k8s.io/apiserver/pkg/storage/cacher TestUnconditionalDelete 1.69s
k8s.io/apiserver/pkg/storage/cacher TestPreconditionalDeleteWithSuggestion 1.68s
k8s.io/apiserver/pkg/storage/cacher TestDeleteTriggerWatch 1.62s
k8s.io/apiserver/pkg/storage/cacher TestGetListNonRecursiveWithConsistentListFromCache 1.61s
k8s.io/apiserver/pkg/storage/cacher TestListContinuation 1.6s
k8s.io/apiserver/pkg/storage/cacher TestWatchFromZero 1.6s
k8s.io/apiserver/pkg/storage/cacher TestWatchDispatchBookmarkEvents/allowWatchBookmarks=true 1.56s
k8s.io/apiserver/pkg/storage/cacher TestWatcherTimeout 1.5s
k8s.io/apiserver/pkg/storage/cacher TestGet 1.49s
k8s.io/apiserver/pkg/storage/cacher TestWatchInitializationSignal 1.49s
k8s.io/apiserver/pkg/storage/cacher TestPreconditionalDeleteWithSuggestionPass 1.48s
k8s.io/apiserver/pkg/storage/cacher TestGuaranteedUpdateWithConflict 1.48s
k8s.io/apiserver/pkg/storage/cacher TestDeleteWithSuggestion 1.48s
k8s.io/apiserver/pkg/storage/cacher TestNamespaceScopedWatch 1.43s
k8s.io/apiserver/pkg/storage/cacher TestCreate 1.41s
k8s.io/apiserver/pkg/storage/cacher TestWatchSemantics/allowWatchBookmarks=true,_sendInitialEvents=true,_RV=unset 1.37s
k8s.io/apiserver/pkg/storage/cacher TestWatchSemantics/allowWatchBookmarks=true,_sendInitialEvents=true,_RV=1 1.37s
```

**Comment by pacoxu** [comment]
It flakes a lot. Can we revert https://github.com/kubernetes/kubernetes/pull/125405 as it blocked some PR merge today?

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/125713 was merged for the unit CI flakes.

- for the CI merging flakes, `pull-kubernetes-integration` seems to be another one: I opened [Flaking Test] integration-master flakes for test-cmd.run_wait_tests  #125718 to track it.

**Comment by serathius** [comment]
Prepared https://github.com/kubernetes/kubernetes/pull/125722 to improve runtime of TestWatchStreamSeparation, however I found it has 30-40% flakiness on master. Confirmed that at point of introduction the test didn't flake. https://github.com/kubernetes/kubernetes/pull/123532

**Comment by serathius** [comment]
Bisection pointed to https://github.com/kubernetes/kubernetes/pull/125575 as culprit.

**Comment by pacoxu** [comment]
> Prepared #125722 to improve runtime of TestWatchStreamSeparation, however I found it has 30-40% flakiness on master. Confirmed that at point of introduction the test didn't flake. #123532



> Bisection pointed to #125575 as culprit.

Thanks for investigation. 
- In the CI run of https://github.com/kubernetes/kubernetes/pull/125713#issuecomment-2190952861, it failed with the revert. 

Sorry @p0lyn0mial would you re-submit the PR again?

**Comment by p0lyn0mial** [comment]
> Sorry @p0lyn0mial would you re-submit the PR again?

np, and yes I will re-open the PR again.

**Comment by serathius** [comment]
A educated guess for root cause for flakes of `TestWatchStreamSeparation` it's https://github.com/grpc/grpc-go/pull/7137

It added released in v1.64.0, and made `String()` method for metadata non-deterministic. It basically broke etcd stream selection logic. cc @ahrtr 

https://github.com/grpc/grpc-go/blob/98e5deebae600b6cd50d2f41bcb5155f8471d53f/metadata/metadata.go#L93-L106

**Comment by serathius** [comment]
@dims have confirmed the issue by re-implementing `String()` to be deterministic and issue being no longer present!
Thanks!

**Comment by dims** [comment]
patch is here for grpc-go - https://github.com/grpc/grpc-go/pull/7137#issuecomment-2192410001

**Comment by ahrtr** [comment]
> A educated guess for root cause for flakes of `TestWatchStreamSeparation` it's [grpc/grpc-go#7137](https://github.com/grpc/grpc-go/pull/7137)

Only etcd main branch depends on grpc-go v1.64.0. But Kubernetes should be depending on etcd 3.5.x, which depends on [v1.59.0](https://github.com/etcd-io/etcd/blob/f7ab198fb6c87d6e59f717af92a132d558712c35/server/go.mod#L45). So the flaky has nothing to do with grpc-go's change?

**Comment by dims** [comment]
@ahrtr in kubernetes go.mod we have v1.64.0 which has the bug, sometimes we go ahead of etcd dependencies, this was needed for OTEL

**Comment by dims** [comment]
opened PR in grpc - https://github.com/grpc/grpc-go/pull/7355

**Comment by ahrtr** [comment]
> @ahrtr in kubernetes go.mod we have v1.64.0 which has the bug, sometimes we go ahead of etcd dependencies, this was needed for OTEL

Makes sense. Based on https://go.dev/ref/mod#minimal-version-selection, v1.64.0 is used.

**Comment by serathius** [comment]
Talked with @easwars, he is ok with making `String()` deterministic but recommends to not depend on it. We should consider implementing our own deterministic metadata traversal.

**Comment by ahrtr** [comment]
> We should consider implementing our own deterministic metadata traversal.

Agreed.

**Comment by p0lyn0mial** [comment]
This is not the first time that a flaky test has been introduced and only caught after being run multiple times. 

Why not create a new CI job/jobs that would run the test multiple times? I think this could be applied to unit/integration tests and maybe even to e2e tests. I would rather wait a bit longer for input from the CI than introduce a costly flake. What do you think?

**Comment by aojea** [comment]
> Why not create a new CI job/jobs that would run the test multiple times? I think this could be applied to unit/integration tests and maybe even to e2e tests. I would rather wait a bit longer for input from the CI than introduce a costly flake. What do you think?

1. running as a presubmit will take more than one hour to run, we want to keep CI jobs on that timeframe
2. how many people checks a failure vs how many people just retry until it pass? I would say is 1 to 1000000, that will end being ignored most of the time
3. we had one as periodic for unit test https://github.com/kubernetes/test-infra/pull/28869 that run multiple times, some tests are not prepared to run multiple times as have global variables, specially the ones about metrics, I spent a considerable time fixing some of them ... until I gave up, nobody else helped

Current method work, we have people monitoring flakes and we have testgrid that make it easy to correlate, is just a matter of paying attention to our ci-signal folks when the raise the alarm

**Comment by dims** [comment]
> Current method work, we have people monitoring flakes and we have testgrid that make it easy to correlate, is just a matter of paying attention to our ci-signal folks when the raise the alarm

Agree with @aojea here.

**Comment by serathius** [comment]
If the issue is early detection of flakes, maybe you should take solution from etcd community? We are working on a automatic flake detection.

https://github.com/etcd-io/etcd/issues/17773#issuecomment-2084928796
/cc @siyuanfoundation

**Comment by BenTheElder** [comment]
https://go.k8s.io/triage and testgrid can both identify flaky tests.

We've found that it's already _really_ resource intensive to run all of the "unit" tests, so things like stress testing them and race detector become impractical for presubmit.

> we had one as periodic for unit test https://github.com/kubernetes/test-infra/pull/28869 that run multiple times, some tests are not prepared to run multiple times as have global variables, specially the ones about metrics, I spent a considerable time fixing some of them ... until I gave up, nobody else helped

this, sig testing has maintained a job to run unit tests repeatedly but it was hard to get anyone to work on the issues

**Comment by BenTheElder** [comment]
If there's sufficient interest we can reintroduce the periodic, but people have to be following up on these or else it's useless, we already have a TON of CI that nobody really monitors (I'm trying to cut down on this but it's really hard! we need testgrid analytics or something ... cc @michelle192837)

**Comment by p0lyn0mial** [comment]
Thanks for your input, I really appreciate it. 
It looks like the proposed path was explored in the past and didn't bring the desired outcome. 
I'm okay with the current approach.

**Comment by p0lyn0mial** [comment]
I'm closing this issue since the tests in the `k8s.io/apiserver/pkg/storage/cacher` package [have stabilised](https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit&graph-metrics=test-duration-minutes). Many thanks for your help.

/close

**Comment by aojea** [comment]
to be clear, is a hard problem to solve in general across the entire software industry and it requires time and effort, if someone want to work on it and dedicate time and experiment is more than welcome, but what we should not do is to do a new additional job that nobody monitors or act on it, as Ben is said, we already have a lot of jobs that are red

**Comment by BenTheElder** [comment]
This is a tangent, but just FYI

> I'm trying to cut down on this but it's really hard! we need testgrid analytics or something ... cc @michelle192837

We talked more about this and Michelle created a query on the testgrid internal side to identify tabs with low view counts, we'll look more at this.

**Comment by michelle192837** [comment]
I do have something rough for TestGrid analytics, but I need to do some cleanup and run through it again before publishing. I think I should have something next week. ^^

**Comment by pacoxu** [comment]
> I do have something rough for TestGrid analytics, but I need to do some cleanup and run through it again before publishing. I think I should have something next week. ^^

Great. Thanks.
