### ISSUE TITLE
FailedSync events of infra container when starting a pod

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#12563]
Recently every time i tried to start a new pod, there exists a failedsync events of infra pod, which complains `Error syncing pod, skipping: DNS ResolvConfPath specified but does not exist. It could not be updated: /var/lib/docker/containers/a5e2efe6a35a00ff07094cf34a9c8dcf8bbdfe5808f0cb0bdef7137b0f038549/resolv.conf`.

The pod is properly running eventually, and I was wondering whether it's a timing thing or not. Does it even hurt?
```
$ kubectl describe pods/busybox-busybox
Name:				busybox-busybox
Namespace:			default
Image(s):			busybox,busybox
Node:				10.10.102.99/10.10.102.99
Labels:				<none>
Status:				Running
Reason:				
Message:			
IP:				10.1.9.20
Replication Controllers:	<none>
Containers:
  busybox1:
    Image:		busybox
    State:		Running
      Started:		Wed, 12 Aug 2015 10:03:00 +0800
    Ready:		True
    Restart Count:	0
  busybox2:
    Image:		busybox
    State:		Running
      Started:		Wed, 12 Aug 2015 10:03:00 +0800
    Ready:		True
    Restart Count:	0
Conditions:
  Type		Status
  Ready 	True 
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath				Reason		Message
  Wed, 12 Aug 2015 10:02:50 +0800	Wed, 12 Aug 2015 10:02:50 +0800	1	{scheduler }							scheduled	Successfully assigned busybox-busybox to 10.10.102.99
  Wed, 12 Aug 2015 10:02:50 +0800	Wed, 12 Aug 2015 10:02:50 +0800	1	{kubelet 10.10.102.99}	implicitly required container POD	pulled		Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  Wed, 12 Aug 2015 10:02:50 +0800	Wed, 12 Aug 2015 10:02:50 +0800	1	{kubelet 10.10.102.99}	implicitly required container POD	created		Created with docker id a5e2efe6a35a
  Wed, 12 Aug 2015 10:02:50 +0800	Wed, 12 Aug 2015 10:02:50 +0800	1	{kubelet 10.10.102.99}	implicitly required container POD	started		Started with docker id a5e2efe6a35a
  Wed, 12 Aug 2015 10:02:50 +0800	Wed, 12 Aug 2015 10:02:50 +0800	1	{kubelet 10.10.102.99}						failedSync	Error syncing pod, skipping: DNS ResolvConfPath specified but does not exist. It could not be updated: /var/lib/docker/containers/a5e2efe6a35a00ff07094cf34a9c8dcf8bbdfe5808f0cb0bdef7137b0f038549/resolv.conf
  Wed, 12 Aug 2015 10:03:00 +0800	Wed, 12 Aug 2015 10:03:00 +0800	1	{kubelet 10.10.102.99}	spec.containers{busybox1}		created		Created with docker id 48fd6edbc6ec
  Wed, 12 Aug 2015 10:03:00 +0800	Wed, 12 Aug 2015 10:03:00 +0800	1	{kubelet 10.10.102.99}	spec.containers{busybox1}		started		Started with docker id 48fd6edbc6ec
  Wed, 12 Aug 2015 10:03:00 +0800	Wed, 12 Aug 2015 10:03:00 +0800	1	{kubelet 10.10.102.99}	spec.containers{busybox2}		created		Created with docker id 25adeddb4b63
  Wed, 12 Aug 2015 10:03:00 +0800	Wed, 12 Aug 2015 10:03:00 +0800	1	{kubelet 10.10.102.99}	spec.containers{busybox2}		started		Started with docker id 25adeddb4b63

```

Corresponding pod manifest. Just in case. ( I'm fully aware that we'd better use a rc and it's just a simple test case)
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox-busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "100"
    name: busybox1
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox2
  restartPolicy: Always
```

**Comment by dalanlan** [comment]
Or is it about the read-write permission of `/var/lib/docker`? 
```
$ ls -l /var/lib/docker
total 84
drwxr-xr-x   5 root root  4096 Jul 21 17:04 aufs
drwx------  51 root root  4096 Aug 12 10:15 containers
drwx------ 161 root root 20480 Aug 10 15:56 graph
drwx------   2 root root  4096 Aug  4 14:15 init
-rw-r--r--   1 root root 29696 Aug 12 10:15 linkgraph.db
-rw-------   1 root root  1756 Aug 12 09:53 repositories-aufs
drwx------   2 root root  4096 Aug 10 15:56 tmp
drwx------   2 root root  4096 Jul 25 10:55 trust
drwx------   2 root root  4096 Jul 21 17:04 volumes

```

**Comment by dalanlan** [comment]
Hmm.. make some progress here. It would break domain name resolution.  
Yet this didnt happen before when i set up dns. 
And the settings for docker are never changed.

**Comment by lvlv** [comment]
Yes, kubelet tries to modify /var/lib/docker/.../resolv.conf to change the
dns settings of the pod.
Are u using containerized version of k8s deployment? I met the same issue
that time. My issue was resolved by using "slave" mount option in kubelet
container.

**Comment by dalanlan** [comment]
Yep, a containerized kubelet. What confused me most is that it didnt happen before and shows up untraceably.
What's a "slave" mount option of kubelet, if i may ask? Sorry but i didnt quite catch you:-)

**Comment by lvlv** [comment]
That's a vfs mount flag.
For details see https://lwn.net/Articles/159077/
Also a docker PR: https://github.com/docker/docker/pull/14097

I patched that PR in 1.7.1 and made /var shared before mounting that (with
--rootmount=slave) into kubelet container.

**Comment by dalanlan** [comment]
Ic. Maybe i'll try later. 
Yet I used `--privileged` flag for kubelet, and it's kinda odd for kubelet what happened here.

**Comment by dalanlan** [comment]
Solved the dns pb already. Turns out it suffers due to missing params, which is my own fault.

Yet i assume it's a *bug*, 'cause kubelet should *not* attempt to update the resolv.conf of infra container.

**Comment by dalanlan** [comment]
Closing it in favor of a newer one.

**Comment by LenutaToderean** [comment]
@dalanlan Hi!
I receive the same error(Error syncing pod, skipping: DNS ResolvConfPath specified but does not exist.). Did you fixed this? Really ned some help with that. Thanks!
