### ISSUE TITLE
[FG:InPlacePodVerticalScaling] e2e test does not verify resource update in pod status

### ISSUE THREAD

**Issue by hshiina** [kubernetes/kubernetes#125609]
### What happened?

e2e tests for pod resizing does not verify if resources in a pod status is updated to the same values in a pod spec after resizing is actuated. This is caused because the result of the runtime support check is reversed:

https://github.com/kubernetes/kubernetes/blob/1519f802816f6a6b9bd4cfb259c93644fe950e0e/test/e2e/node/pod_resize.go#L501-L513

### What did you expect to happen?

Resources in pod status are verified.

### How can we reproduce it (as minimally and precisely as possible)?

Run e2e test with enabling InPlacePodVerticalScaling.

### Anything else we need to know?

I'm not sure if we should fix it immediately. If this issue is fixed, it will take much longer to finish the tests because there are some issues that it takes much time (60-90s) till resources in a pod status is updated after resizing is actuated such as #123940 and #125559. In addition, pod resize e2e tests are being migrated to e2e node tests in PR #124296.

### Kubernetes version

master branch

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by hshiina** [comment]
FWIW, if this issue is fixed and the tests are run with enabling EventedPLEG, I guess most tests will fail with timeout because resources in a pod status are never updated (issue #125624).

**Comment by dshebib** [comment]
It might also be worth it to check that the resizeStatus itself is properly updated to prevent unexpected behavior later on

**Comment by AnishShah** [comment]
sig-node meeting notes:

/assign @esotsal to update this test in pod resize e2e tests.

/area test
/priority important-longterm

**Comment by tallclair** [comment]
/assign
Will be fixed by https://github.com/kubernetes/kubernetes/pull/128377
