### ISSUE TITLE
`kubernetes.io/legacy-token-last-used` label being added to long lived service token secrets

### ISSUE THREAD

**Issue by sidewinder12s** [kubernetes/kubernetes#125633]
### What happened?

We've gone through migrating some of our static service account tokens to follow the new instructions for creating long lived service account tokens documented here: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#create-token

Is it intended that the legacy token controller would still label these secrets with the `kubernetes.io/legacy-token-last-used` label?

I am assuming the token cleanup controller won't delete my credentials either:

1. They are in use
2. The secret and service account do not bi-directionally reference each other

But wanted to check on that as the label still being in place is unexpected/not entirely correct as I don't perceive it as a legacy token that the controller was built to deal with.

### What did you expect to happen?

Expected the new static token secrets to not be labeled with the legacy-token-last-used label.

### How can we reproduce it (as minimally and precisely as possible)?

Follow https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#create-token and then use the credential.

### Kubernetes version

<details>

```console
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```

</details>

### Cloud provider

<details>
AWS
</details>

**Comment by stlaz** [comment]
@liggitt Are the _manually_ created tokens also part of the automatic token cleanup?

**Comment by liggitt** [comment]
The last-used labeling and metrics apply to all secret-based tokens.

The automatic clean up *only* applies to token secrets referenced from the ServiceAccount secrets list
