### ISSUE TITLE
data race in spdystream dependency

### ISSUE THREAD

**Issue by puertomontt** [kubernetes/kubernetes#125707]
This data race in spdystream https://github.com/moby/spdystream/pull/91 effects the code in https://github.com/kubernetes/client-go/blob/master/transport/spdy/spdy.go

**Comment by dims** [comment]
Looks like we need a new tag for moby/spdystream: https://github.com/moby/spdystream/compare/v0.2.0...HEAD

**Comment by dims** [comment]
We now have a v0.3.0 for spdystream - https://github.com/moby/spdystream/releases/tag/v0.3.0

**Comment by dims** [comment]
@ritster Do you want to cut a PR for updating this dependency?
