### ISSUE TITLE
kube-apiserver: Removed rules from code-base are not removed from the existing bootstrap ClusterRoles/Roles

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#125727]
### What happened?

https://github.com/kubernetes/kubernetes/pull/117140 and https://github.com/kubernetes/kubernetes/pull/117414 removed stale leader election related endpoints RBAC rules from the `system:kube-scheduler` and `system:kube-controller-manager` ClusterRoles.
However, for existing clusters these RBAC rules are not removed and still exists.

On a new K8s cluster the rules removed with the above PRs are not present.

It looks like in https://github.com/kubernetes/kubernetes/blob/00b9ead02c37921011ebe5293558cea5277cd295/pkg/registry/rbac/rest/storage_rbac.go#L209-L213 we don't specify `RemoveExtraPermissions: true`. https://github.com/kubernetes/kubernetes/blob/a5920f7edb48654edaf649e28680d324ea1cdcb9/staging/src/k8s.io/component-helpers/auth/rbac/reconciliation/reconcile_role.go#L66-L67

### What did you expect to happen?

The rules removed in https://github.com/kubernetes/kubernetes/pull/117140 and https://github.com/kubernetes/kubernetes/pull/117414 to be removed from the existing ClusterRoles.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a K8s 1.27 cluster
2. Make sure that the rules from https://github.com/kubernetes/kubernetes/pull/117140 and https://github.com/kubernetes/kubernetes/pull/117414 are present there
3. Upgrade the K8s cluster to 1.28
4. Make sure that the rules removed in rules from https://github.com/kubernetes/kubernetes/pull/117140 and https://github.com/kubernetes/kubernetes/pull/117414 are still present in the `system:kube-scheduler` and `system:kube-controller-manager` ClusterRoles. 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Gardener
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by cici37** [comment]
Hi we are at the sig api-machinery bug triage meeting and decided to review this issue next time to leave time for sig auth to take a look :)

**Comment by cici37** [comment]
This is working as expected where the rules will not exist in the new cluster while creation. 
/remove-kind bug
/kind support
/close
