### ISSUE TITLE
Volume with storage medium "memory" must be title case with unhelpful error message

### ISSUE THREAD

**Issue by tbmetcalfe** [kubernetes/kubernetes#125734]
### What happened?

When you create a deployment with volume that has a medium of `memory` (note here that it is not title case), it fails with an error message of `unknown storage medium "memory"` and the pod gets stuck in the `ContainerCreating` state. As this is a `beta` feature (enabled with the `SizeMemoryBackedVolumes` feature gate), we originally thought that this feature gate was disabled and was the cause of this error message. It turns out that is was simply because it was `memory` and not `Memory`.

### What did you expect to happen?

Either accept `memory` as a value or there would be a more meaningful error message with something along the lines of `unknown storage medium 'memory' - only the following are accepted: 'Memory', [...]`.

In addition, it was misleading that this value was accepted when applying. I would have expected the apply to fail when attempting to apply an invalid value for this field. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a deployment with the following volume definition:
```yaml
volumes:
- emptyDir:
     medium: memory # note the lower case.
     sizeLimit: 32Mi
```

### Kubernetes version

<details>

```console
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

</details>

### Cloud provider

<details>
This originally occurred on EKS, but we were also able to replicate this on a `kind` cluster.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by thisisharrsh** [comment]
I have tried to reproduce this issue and created a deployment (memory-dep1) using `memory` as the parameter; in this case, I have found the pods to be stuck in the `ContainerCreating` stage. 

![image](https://github.com/kubernetes/kubernetes/assets/88570905/c6956bfa-d567-46d7-af42-6b9269606f4f)

**Comment by thisisharrsh** [comment]
And I have also created another deployment (memory-dep2) using `Memory` as a parameter. I have observed that the pod is now in the `running` state. 

![image](https://github.com/kubernetes/kubernetes/assets/88570905/56b8f22d-4942-48e3-95e2-5905266b97ed)

**Comment by thisisharrsh** [comment]
Since the issue is valid, we can have two workarounds for it. Either accept `memory` as a valid medium or provide a clearer `error` message.

**Comment by thisisharrsh** [comment]
If we use `memory` as a valid medium this would require changes in the codebase to handle memory-backed volumes. It would streamline the process for users who intend to use this feature.

**Comment by thisisharrsh** [comment]
If we choose to provide a clearer error message that would involve modifying the error message to explicitly state that `memory` is not a currently supported medium and list the available options.
