### ISSUE TITLE
kubectl kubectl: command not found

### ISSUE THREAD

**Issue by eivantsov** [kubernetes/kubernetes#12573]
Just followed the tutorial on settng up master and worker nodes on Ubuntu 15.04 with Docker 1.8

However, I keep getting the following:

Master done!
root@master:~/kubernetes/docs/getting-started-guides/docker-multinode# kubectl
kubectl: command not found

**Comment by dalanlan** [comment]
You should at least scp the kubectl binary to the master node manually and make it available via PATH ENV.

**Comment by bq-xiao** [comment]
You can download the kubectl binary from https://storage.googleapis.com/kubernetes-release/release/v1.0.1/bin/linux/amd64/kubectl (linux), or download from https://storage.googleapis.com/kubernetes-release/release/v1.0.1/bin/darwin/amd64/kubectl (OS X) and make it available in your machine PATH ENV.
