### ISSUE TITLE
Expose GPU specific requests and limits via Downward API

### ISSUE THREAD

**Issue by frittentheke** [kubernetes/kubernetes#125764]
### What would you like to be added?

Currently the DownwardAPI allows to expose various resource requests and limits to pods (https://kubernetes.io/docs/concepts/workloads/pods/downward-api/#downwardapi-resourceFieldRef) which is commonly used to fine-tune applications accordingly.
Unfortunately this is not the case for GPUs yet, even though GPU scheduling is now stable: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

Adding this functionality was proposed before (https://github.com/kubernetes/kubernetes/issues/44552) but at that time GPU support in Kubernetes was still in alpha, so the APIs were as well.

The difference making GPUs a little more complex to other resources is that there is somewhat of a whole namespace of possible keys to expose ...

GPU resources are addressed via `gpu-vendor.example/example-gpu`. 

So there could be the "classic" count of GPUs via: 
`nvidia.com/gpu: 1`

but a certain amount of special GPU-flavors the likes of 
`nvidia.com/mig-3g.20gb:  2`
(See e.g. NVIDIA MIG: https://docs.nvidia.com/datacenter/cloud-native/kubernetes/latest/index.html#testing-with-different-strategies)

### Why is this needed?

There are applications that can make use of multiple GPUs, which in turn require corresponding settings. See vLLM as an example: https://docs.vllm.ai/en/latest/serving/distributed_serving.html#distributed-inference-and-serving

so having the GPU count (or GPU flavor) available makes this as easy as referencing an environment variable.

**Comment by kannon92** [comment]
cc @pohly 

I can see usefulness in this but not sure how this would work with DRA.

**Comment by pohly** [comment]
This proposal is very much about device plugins. I'm not sure whether it's worth putting more effort into supporting that better.

Access to multiple devices works differently with DRA. A DRA driver can set whatever env variables it wants. What we don't have at the moment is admin- or user-controlled re-mapping of those env variables. We haven't heard of a good use case for it yet, we only noted that gap.

**Comment by sftim** [comment]
An alternative might be possible: at admission time, use a mutating webhook that sets an annotation on a Pod based on the resource requests (DRA or otherwise) and the resources that the Pod guarantees are available.

Then, use a ValidatingAdmissionPolicy to restrict changing that annotation for a bound Pod. Now, the downward API can work to copy that annotation into somewhere a container can see it.

We could try this out-of-tree approach and see if we like it before making in-tree changes.

**Comment by sftim** [comment]
Bear in mind that the downward API also lets you set values as the contents of a file. I don't think DRA has a way to do that, so the downward API mechanism may yet be useful in a DRA context.

**Comment by sftim** [comment]
I wonder if we'd like to reopen https://github.com/kubernetes/kubernetes/issues/125764 (and maybe close this one). The original issue seems to have been closed pending device plugins becoming stable; they now are.

**Comment by frittentheke** [comment]
> I wonder if we'd like to reopen #125764 (and maybe close this one). The original issue seems to have been closed pending device plugins becoming stable; they now are.

You meant to link to https://github.com/kubernetes/kubernetes/issues/44552 I suppose?
If you re-open the other one I gladly start to comment there. Whatever works.

**Comment by sftim** [comment]
Ah yep.
/close not-planned

Closing in favor of https://github.com/kubernetes/kubernetes/issues/44552

**Comment by frittentheke** [comment]
> Ah yep.
> /close not-planned
> 
> Closing in favor of https://github.com/kubernetes/kubernetes/issues/44552

Is "not planned" really the correct reason? "Duplicate" maybe? If there is that kind of metadata being generated, may as well make it worth a dime.

**Comment by sftim** [comment]
In the GitHub API, the opposite of not-planned closure is “completed”, indicating that the issue was resolved / fixed. Out of the two, not-planned is a better fit.

**Comment by frittentheke** [comment]
@sftim just for the sake of spreading the word on this feature: https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate
