### ISSUE TITLE
Service cluster IP range

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#12579]
Hi,

I've been follwoing the document https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

I have a question when it comes to the ubuntu/config-default.sh file in the field:

export SERVICE_CLUSTER_IP_RANGE=192.168.3.0/24
export FLANNEL_NET=172.16.0.0/16

Do we need to specify the machine's internal private IP here or is a virtual network that is created for the clustered environment?

**Comment by adyanthaya17** [comment]
The 192.168.3.x is neither my external or internal IP range. To make use of the UI feature doesn't the node require it?

**Comment by cjcullen** [comment]
SERVICE_CLUSTER_IP_RANGE is the virtual IP range that will be used by Kubernetes services, which is managed by kube-proxy on each of your nodes.
FLANNEL_NET is the virtual IP range used for pods/containers. It is managed by flanneld.

As long as neither of those conflict with the IP range that your nodes are using, I think you should be good.

**Comment by adyanthaya17** [comment]
Alright, SERVICE_CLUSTER_IP_RANGE and FLANNEL_NET makes use of virtual IP range, I have a question here.

If my master and minion node has private and public IP of it's own, and if I make use the internal IP to deploy the cluster environment successfully. Will I be able to access the containers in the web browser?

**Comment by kgrvamsi** [comment]
if this setup is something ur doing it on a cloud provider then internal ip on the brwoser is something which you cannot do but if you are trying to create the cluster on a local network based nodes and if you can ping to those machines then we can get it on the browser if and only if you make the kube-api server running on 0.0.0.0 then u should be getting that request running on a public or private ip.

**Comment by adyanthaya17** [comment]
I did deploy my cluster on a cloud provider with an internal IP and I'm able to get the webpage for a single container using the public IP as in:
http://10.x.x.x:8080/api/v1/proxy/namespaces/default/pods/update-demo-nautilus-6lyv4/data.json

I have two nodes-one set as master and minion while another set as a second minion node. The minion nodes run kubectl proxy. 

For one of the application example I ran:
$kubectl proxy --www=examples/update-demo/local/ &
Starting to serve on localhost:8001

but when I go to web page: http://localhost:8001/static/index.html
I get 'Internet explorer cannot find the page'.

**Comment by kgrvamsi** [comment]
```
but when I go to web page: http://localhost:8001/static/index.html
I get 'Internet explorer cannot find the page'
````
Can you check with netstat -vpln whether there is any port running on 8001 and can you send me the output from the server which you ran that command using curl

````
curl http://localhost:8001
````

If the Port is running globally then you may need to open it on the web browser with the Public Ip but not with the locahost.

**Comment by adyanthaya17** [comment]
When I execute the command:
$ curl http://localhost:8001
404 page not found

**Comment by adyanthaya17** [comment]
$ kubectl proxy --www=docs/user-guide/update-demo/local/ &
[1] 4353
root@master:/home/ubuntu/kubernetes# Starting to serve on localhost:8001F0817 03:57:38.633486    4353 proxy.go:110] listen tcp :8001: bind: address already in use

I did the netstata -vpln and found it running on tcp6
tcp6       0      0 :::8001                 :::*                    LISTEN      10088/kubectl

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
