### ISSUE TITLE
Use request instead of limit in prioritizer function LeastRequestedPriority()

### ISSUE THREAD

**Issue by HaiyangDING** [kubernetes/kubernetes#12574]
In https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/proposals/resource-qos.md, we have defined the QoS of CPU/Memory resources. Based on the description, I think it would make more sense to use requested resource instead of resource limit when prioritizing the node with respect to free resources. That is, free resource on a node should be measured by `capacity - sum_of_requested_resource`.

Besides, limits are replaced by requests in the corresponding predicate function `CheckPodsExceedingFreeResources()`, so I think it is necessary that we make similar changes in prioritizer function. 

What do you think? I would be happy to implement this if you think it is OK.

@davidopp @AnanyaKumar 

> update 2015.08.14:

In fact, as mentioned by @AnanyaKumar in the comments, we should use request instead of limit when scheduling. So, basically we need to change almost every limit in all priority functions. I will handle them carefully and send PR sooner. We can have further discussion based on the PR.

Regards

**Comment by AnanyaKumar** [comment]
@HaiyangDING I agree. Requests represent the amount of resources that a container needs/wants, so the scheduler should primarily deal with requests. Limits are simply a hard cap, and are not necessarily representative of the work load requirements.

In general, limits should be enforced by the Kubelet, but shouldn't be used for much else. You should probably wait for @davidopp to give the green light before implementing this change though.

Thanks for opening this issue!
