### ISSUE TITLE
kube-scheduler split-brain occurs after the time is changed

### ISSUE THREAD

**Issue by kangzhiqin** [kubernetes/kubernetes#125761]
### What would you like to be added?

After the system time is changed to one hour later, master election is triggered again on the kube-schduler node because the lease expires. The standby node is promoted to the master node. However, the original master node is promoted to the standby node 2 seconds later. Therefore, split-brain occurs for at least two seconds. If two active nodes work at the same time, some service problems may occur.

The code is in the following position:
https://github.com/kubernetes/kubernetes/blob/29defc15aa435d9531258d2c2346ab06ece834c8/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L266-L293

### Why is this needed?

Does the community have a good solution to fix this problem?

**Comment by neolit123** [comment]
> After the system time is changed to one hour later, 

note, a lot of thing can go wrong with k8s if the system time is changed.
leaving this ticket for sig scheduling to comment.

/sig scheduling

**Comment by sftim** [comment]
(not speaking for SIG Scheduling)
I suppose the scheduler could watch its Lease to defend against losing it; even so, the watch is not transactional and the scheduler may not notice fast enough. However, I don't see a big risk in momentarily having two processes both believing they can bind Pods to nodes. Kubernetes can self-heal if this happens.

Best advice does seem to be: don't skew the system clock for nodes hosting control plane components.

**Comment by kangzhiqin** [comment]
> (not speaking for SIG Scheduling) I suppose the scheduler could watch its Lease to defend against losing it; even so, the watch is not transactional and the scheduler may not notice fast enough. However, I don't see a big risk in momentarily having two processes both believing they can bind Pods to nodes. Kubernetes can self-heal if this happens.
> 
> Best advice does seem to be: don't skew the system clock for nodes hosting control plane components.

No. Split-brain may cause problems. For example, two pods with strong anti-affinity are scheduled to the same node by two kube-schedulers, and one pod is destined to fail to be started. Then, the process is irreversible, and Kubernetes does not automatically tune back.

**Comment by sftim** [comment]
> Kubernetes does not automatically tune back.

Partially. We have the Descheduler out-of-tree. See https://github.com/kubernetes-sigs/descheduler?tab=readme-ov-file#removepodsviolatinginterpodantiaffinity

**Comment by sftim** [comment]
I doubt it. We could add a document about how to fix incorrect time on a control plane node (eg: stop the kubelet and its static pods first).

**Comment by BenTheElder** [comment]
It could get quite complex to detect this edge case with any real reliability and best practice is to maintain synchronized clocks and not change them.

A lot of things, Kubernetes or otherwise, are not going to handle time jumps well, leading to solutions like https://developers.google.com/time/smear

**Comment by alculquicondor** [comment]
Thanks @BenTheElder for the insight

I'm clearing the backlog, so:
/close
