### ISSUE TITLE
Linux network namespaces created by serivce in Pod  become "RTNETLINK answers: Invalid argument"

### ISSUE THREAD

**Issue by gotostack** [kubernetes/kubernetes#125888]
Simply, the openstack neutron-l3-agent service running on k8s has started a batch of network namespaces, but in unknown circumstances, these namespaces cannot be accessed.

There is a long story about docker:
https://github.com/moby/moby/issues/27277

And long disscussion on:
https://bugs.launchpad.net/kolla/+bug/1616268

and:
https://bugs.launchpad.net/kolla-ansible/+bug/1864856

# ip netns exec qrouter-42ecd889-9aba-41b1-bb95-4a546539e2b8 ip a
setting the network namespace "qrouter-42ecd889-9aba-41b1-bb95-4a546539e2b8" failed: Invalid argument

# ls -lah /run/netns
----------  1 root root    0 Jun 28 00:18 qdhcp-f1c65cd3-24e2-40a5-bbfd-a4757bb9721f
----------  1 root root    0 Jun 28 00:18 qdhcp-f6eb2c25-bf59-451b-af6b-0d1750032b10
----------  1 root root    0 Jun 28 00:22 qrouter-095f5916-8235-44e3-8fb8-dbd494a605bf
----------  1 root root    0 Jun 28 00:20 qrouter-1228752a-a2d3-4bc6-81ff-0ece5e9410b5
----------  1 root root    0 Jun 28 00:22 qrouter-177318e8-f775-4491-8d41-abfb96722e64
----------  1 root root    0 Jun 28 00:22 qrouter-1826d198-427f-438f-9ea3-81e5de716d0

In those disscussion, the result solution is to mount /run:/run:shared or /run/netns:/run/netns:shared to the container.
But for the k8s the mount point is:
      {
        "containerPath": "/run/netns",
        "hostPath": "/run/netns",
        "propagation": "PROPAGATION_BIDIRECTIONAL",
        "readonly": false,
        "selinuxRelabel": false
      },

So, is there similar issue in the community had encountered? Is there any clue or informations can solve this issue?
If you need any more information, I will added here as soon as possible.

# crictl --version
crictl version v1.19.0

# kubelet --version
Kubernetes v1.19.15

# crictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                     ATTEMPT             POD ID
aa950e02ad3fe       fee6482a19404       6 days ago          Running             neutron-l3-agent         1                   d2b21b9cc30a5

Container details:
# crictl inspect aa950e02ad3fe
https://paste.opendev.org/show/bEciGQyK2zmjnarA0lJ0/

**Comment by saschagrunert** [comment]
Just like to note that 1.19 is EOL, can you reproduce the issue with a recent Kubernetes version?

**Comment by aojea** [comment]
> Simply, the openstack neutron-l3-agent service running on k8s has started a batch of network namespaces, but in unknown circumstances, these namespaces cannot be accessed.

/close

This seems related to Openstack not to Kubernetes, better to open the issue on the corresponding project

**Comment by gotostack** [comment]
Please do not close this, since the issue is no so much related to openstack service itself. We have many deployments which run openstack service directly on the hosts, no such issue happened. But, for those deployments run the openstack service on the k8s Pod containers, many have such issue. And because of the docker rekated https://github.com/moby/moby/issues/27277, I assume that the k8s related container service may have same problem.

**Comment by aojea** [comment]
> And because of the docker rekated [moby/moby#27277](https://github.com/moby/moby/issues/27277), I assume that the k8s related container service may have same problem.

Kubernetes deprecated docker in 1.20 https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/ and removed it entirely in 1.24 https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/#:~:text=Dockershim%20was%20removed%20from%20Kubernetes,to%20obtain%20Docker%20Engine%20support.

Last supported release is 1.28 https://kubernetes.io/releases/ 

> So, is there similar issue in the community had encountered? Is there any clue or informations can solve this issue?
> Please do not close this, since the issue is no so much related to openstack service itself. We have many deployments which run openstack service directly on the hosts, no such issue happened.

It is not clear what  Kubernetes can do here, if you have a more clear description on the problem and a way to reproduce we will reopen , but with the existing information there is no actionable action
