### ISSUE TITLE
yaml parser fails with "bufio.Scanner: token too long"

### ISSUE THREAD

**Issue by onorua** [kubernetes/kubernetes#12582]
While creating secrets, I've got an error: 
```
bufio.Scanner: token too long
```
while when I created json from the same data my secret created without any issues. So far I've changed "default" format to use json instead of yaml. But as far as I can see, yaml parser is the only module using bufio.Scanner while package docs states:
```
Programs that need more control over error handling or large tokens, or must run sequential scans on a reader, should use bufio.Reader instead.
```
bufio filed on the folder with following files encoded:
```
notification-service $ wc * 
     4      5    240 application.properties
   552   4490 100578 cacerts.jks
     9     13    160 forwards.conf
    22     43    791 logback.xml
    39     70   1185 push-server.conf
   626   4621 102954 total
```

**Comment by stensonb** [comment]
Can confirm...reference files are here: https://gist.github.com/stensonb/b75193458fff424054d54208524d915a

<code>toobig.json</code> works via <code>kubectl create -f toobig.json</code>, but <code>toobig.yaml</code> fails via <code>kubectl create -f toobig.yaml</code> with the following error:

```
$ kubectl create -f toobig.yaml
bufio.Scanner: token too long
```

Here's my toolset versions:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3+882d296", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}
```

**Comment by onorua** [comment]
There is a fix in https://github.com/kubernetes/kubernetes/pull/23265 coming
