### ISSUE TITLE
pull-kubernetes-typecheck doesn't notice compile errors in staging test files

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#125807]
_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/125571#issuecomment-2198419708_

/sig testing
/area test
/kind bug

`pull-kubernetes-typecheck — Job succeeded.`
yet:
```
ERROR: staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile.go:1: : # k8s.io/dynamic-resource-allocation/structured/namedresources/cel [k8s.io/dynamic-resource-allocation/structured/namedresources/cel.test]
ERROR: staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile_test.go:127:14: undefined: Compiler (typecheck)
```

(I fixed this in that PR, but it should be reproducible by reintroducing a compile error in a test file like that)

**Comment by BenTheElder** [comment]
@dims noticed that this only impacts staging modules, which makes sense, we were only walking the main module currently

https://github.com/kubernetes/kubernetes/pull/125850 patches in covering staging/src/k8s.io/...

**Comment by BenTheElder** [comment]
Not sure if we've always had this gap or something in the mix of migrating to modules/workspaces, but we're closing it now.

Turned up some other minor build issues.
