### ISSUE TITLE
Deploy addons

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#12580]
I'm facing the below error when I look for the --namespace

root@master:/home/ubuntu/kubernetes/cluster/ubuntu# 
KUBERNETES_PROVIDER=ubuntu ./deployAddons.sh
Deploying DNS on kubernetes
replicationcontrollers/kube-dns-v8
services/kube-dns

root@master:/home/ubuntu/kubernetes/cluster/ubuntu# kubectl get pods --namespace=kube-system
NAME                READY     STATUS    RESTARTS   AGE
kube-dns-v8-ko1oz   0/4       image pull failed for gcr.io/google_containers/etcd:2.0.9, this may be because there are no credentials on this request.  details: (API error (500): Get https://gcr.io/v1/_ping: read tcp 74.125.200.82:443: i/o timeout
)                   0         3m

**Comment by kgrvamsi** [comment]
Give it a Try again, seems like a problem with the connectivity.
