### ISSUE TITLE
client-go: global transport cache grows unbounded when requesting configs with non-nil `Dial` functions

### ISSUE THREAD

**Issue by moio** [kubernetes/kubernetes#125818]
### What happened?

client-go 1.26+ changed the semantics of `kubernetes.NewForConfig(restConfig)` by caching TLS transport objects in some cases which were not cached in earlier versions (notably, configurations with non-nil `Dial` functions).

Unfortunately the cache does not have any expire or pruning mechanism, leading in worst case to unbounded growth of memory usage (see for example kubernetes/kubernetes#117250).

The change is: kubernetes/kubernetes#112450

This issue is for a program using client-go (Rancher) requesting clientsets with non-nil Dial functions over time.

### What did you expect to happen?

TLS transport objects not to be internally cached by client-go, like in 1.25 and earlier versions.

### How can we reproduce it (as minimally and precisely as possible)?

`	clientset, err := kubernetes.NewForConfig(config)`

with `config.Dial` being non-nil.

I will be submitting a PR that unit-test covers this.

### Kubernetes version

1.26 and over

### Cloud provider

any

### OS version

any

### Install tools

any

### Container runtime (CRI) and version (if applicable)

n/a

### Related plugins (CNI, CSI, ...) and versions (if applicable)

n/a

**Comment by cici37** [comment]
Thanks Ben :)
/triage accepted

**Comment by BenTheElder** [comment]
I think the question is: Do we want to support a blunt "no more caching" knob for users (@moio has a PR proposed for this in https://github.com/kubernetes/kubernetes/pull/125819) which does pretty conclusively handle that use case, or do we want to try to further mitigate the issue by default instead? (which may also solve some other issue that are cropping up, without adding another config field)

cc @liggit @aojea @enj @dims

**Comment by BenTheElder** [comment]
cc @liggitt ... dropped a t there ...

**Comment by dims** [comment]
@BenTheElder i am not opposed to what @moio has in there. I would love to have a fix for everyone more.

**Comment by aojea** [comment]
> with `config.Dial` being non-nil.

with config.Dial non-nil you have to use something like https://github.com/kubernetes/kubernetes/pull/117258, is that not working?

**Comment by moio** [comment]
No, it is not solving the problem.

My understanding is:

 - client-go < 1.26 did **not** cache TLS transport objects if `config.Dial` is non-nil, but such caching is necessary in Kubernetes, so it was implemented inside `AvailableConditionController`.

 - client-go >= 1.26 changed that, and TLS transport objects **are** now cached by client-go. Therefore https://github.com/kubernetes/kubernetes/pull/117258 was merged in order to avoid caching in both places, and in fact it drops the cache in `AvailableConditionController`:

https://github.com/kubernetes/kubernetes/pull/117258/files#diff-f768db209f4057d77a95bb4dc5cf166b8dde189398590809600f96417735e9edL169


In my case (Rancher), I have the "dual" problem: I do not want any caching to happen, because the `config.Dial` functions are many and change frequently.

 - client-go < 1.26 did **not** cache TLS transport and my code was fine
 - client-go >= 1.26 **does**, and I see no way to prevent that

Hence this PR to add an optional, disabled-by-default flag to restore the previous behavior if necessary (and give users a way to implement a different caching mechanism if they so want).

Does that make sense?

**Comment by moio** [comment]
> do you have some links to the specific code you are referring so I can get some context?

Yes, but that is a bit buried, I hope I'll do a decent job explaining the situation.

First of all Rancher is an application to manage multiple Kubernetes clusters, therefore it keeps track of clusters "registered" to it.

There is a [ToRESTConfig](https://github.com/rancher/rancher/blob/3c1c5730afc57546b362b2010744efdc7b77212b/pkg/clustermanager/manager.go#L259-L342) function to generate a `rest.Config` given Rancher-specific `v3.Cluster` object, which represents a registered cluster. The resulting `rest.Config` is of course used to manage the cluster.

Among other things, `ToRESTConfig` calls a [ClusterDialer](https://github.com/rancher/rancher/blob/3c1c5730afc57546b362b2010744efdc7b77212b/pkg/clustermanager/manager.go#L291) method, which returns a dialing function for the specific `Cluster`.

That dialing function is crucial for Rancher, because different clusters are accessed in different ways depending on network topology and other factors. Importantly, most clusters are accessed via a Rancher-specific tunneling mechanism called [remotedialer](https://github.com/rancher/remotedialer): `ClusterDialer` takes care of that, and therefore we almost universally have a `Dialer` in our `rest.Config`.

> Are you mutating the same config with different dialers every time?

No, we are generating new configs every time. Because managed clusters can be many, they are divided among Rancher replicas to implement load balancing. When "rebalancing" events happen, replicas get to connect to a different set of clusters than before.

After rebalancing a replica they might get new clusters, in that case `rest.Config`s are simply generated from scratch.

Or it could lose some, and in that case any stale `rest.Config`s are discarded. But the TLS Transport remains cached inside of client-go, therefore causing a leak.

I hope this helps

**Comment by moio** [comment]
@aojea are there any news about this one?

**Comment by aojea** [comment]
sorry @moio lot of things , thanks for the reminder

Looking at the code I'm not sure the problem are the dialers (this code is complex and with similar names for variables and types and is easy to get confused)

This is the config you are generating, you are not setting the Dial field, instead the code is using a wrapper over the transport to override the dialer

```

	// adding suffix to make tlsConfig hashkey unique
	suffix := []byte("\n" + cluster.Name)
	rc := &rest.Config{
		Host:        u.String(),
		BearerToken: string(secret.Data[secretmigrator.SecretKey]),
		TLSClientConfig: rest.TLSClientConfig{
			CAData:     append(caBytes, suffix...),
			NextProtos: []string{"http/1.1"},
		},
		Timeout:     45 * time.Second,
		RateLimiter: ratelimit.None,
		UserAgent:   rest.DefaultKubernetesUserAgent() + " cluster " + cluster.Name,
		WrapTransport: func(rt http.RoundTripper) http.RoundTripper {
			if ht, ok := rt.(*http.Transport); ok {
				if tlsDialer == nil {
					ht.DialContext = clusterDialer
				} else {
					ht.DialContext = nil
					ht.DialTLS = tlsDialer
				}
			}
			if cluster.Status.Driver == "googleKubernetesEngine" && cluster.Spec.GenericEngineConfig != nil {
				cred, _ := (*cluster.Spec.GenericEngineConfig)["credential"].(string)
				rt, err = gke.Oauth2Transport(context.RunContext, rt, cred)
				if err != nil {
					logrus.Errorf("unable to retrieve token source for GKE oauth2: %v", err)
				}
			}
			return rt
		},
	}

	return rc, nil
```

When you create a new RESTClient

https://github.com/kubernetes/kubernetes/blob/7436ca32bc766ff202109a7541d2e7bb41ee7d13/staging/src/k8s.io/client-go/rest/config.go#L309-L330

The transport is created in

https://github.com/kubernetes/kubernetes/blob/7436ca32bc766ff202109a7541d2e7bb41ee7d13/staging/src/k8s.io/client-go/rest/transport.go#L32-L48

that calls 
https://github.com/kubernetes/kubernetes/blob/7436ca32bc766ff202109a7541d2e7bb41ee7d13/staging/src/k8s.io/client-go/rest/transport.go#L63-L69


that wraps the transports here

https://github.com/kubernetes/kubernetes/blob/7436ca32bc766ff202109a7541d2e7bb41ee7d13/staging/src/k8s.io/client-go/rest/transport.go#L144-L155


Then it builds the Transport based on the config

https://github.com/kubernetes/kubernetes/blob/7436ca32bc766ff202109a7541d2e7bb41ee7d13/staging/src/k8s.io/client-go/transport/transport.go#L36-L61

and then adds the wrappers.

I think it grows because of this

> 	// adding suffix to make tlsConfig hashkey unique

**Comment by moio** [comment]
@aojea thanks for the deep dive, I think I now understand your line of reasoning. 

I will admit I am not particularly happy about copying over that much code from [transport/cache.go](https://github.com/kubernetes/kubernetes/blob/7436ca32bc766ff202109a7541d2e7bb41ee7d13/staging/src/k8s.io/client-go/transport/cache.go#L96-L137) as it may diverge in future client-go versions, although it's probably a viable workaround.

My final question now is: do you consider https://github.com/kubernetes/kubernetes/pull/125819 not acceptable because such workaround is possible?

Thanks

**Comment by BenTheElder** [comment]
[seems we lack consensus to go forward with this, https://github.com/kubernetes/kubernetes/issues/125818#issuecomment-2315167931 sounds pretty reasonable to me]
