### ISSUE TITLE
How to Process Pod Eviction and Rebuilding Caused by Node NotReady in a More Refined Manner

### ISSUE THREAD

**Issue by maxin93** [kubernetes/kubernetes#125824]
### What happened?

My cluster has multiple network planes. The network between the worker node and control node is interrupted for more than 5 minutes. When the network is restored, all pods on the worker node are evicted and rebuilt. As a result, my service is interrupted for a period of time.[](url)[](url)

### What did you expect to happen?

I know that this is the mechanism for handling node failures. In scenarios where only some nodes fail, it is necessary to evict and rebuild the pod. However, when all the worker nodes fail to report the node status, the pods are still up. So, I want to do something in this extreme failure scenario and then not evict and rebuild all the pods.

### How can we reproduce it (as minimally and precisely as possible)?

We can stop the network switch between the worker node and the control node to close the network connection between them. Or even stop the kubelet on the worker node.

### Kubernetes version

kubernetes V1.28.1

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by maxin93** [comment]
I have an idea that kube-controller-manager checks whether there is a normal worker node before evicting the pod when determining that the node is NotReady. If there is no normal worker node, the eviction operation is not performed. Of course, the number of active nodes can be configured, and the node type can also be set, for example, including nodes with specified labels.

**Comment by AnishShah** [comment]
sig-node meeting triage:

- This does not seem to be related to sig/node. We have a support forum - http://discuss.kubernetes.io where you can ask this question. You can explore service mesh to mitigate such issues.

/remove-sig node

**Comment by AnishShah** [comment]
sig-node triage:

/remove-kind bug
/kind support
/close
