### ISSUE TITLE
Add Container Optimized OS version to release notes for gke releases.

### ISSUE THREAD

**Issue by ndlanier** [kubernetes/kubernetes#125844]
### What would you like to be added?

The build number of the cos attached to releases of gke verions needs to be added to changelogs, release documentation, etc.

Examples, would be nice to have it here: https://cloud.google.com/kubernetes-engine/docs/release-notes-nochannel

Somewhere it's seen, and so one doesn't have to dig for the information, or doesn't have to upgrade and hope they're on a version of cos that they need to target.

### Why is this needed?

Vulnerability issue tracking from companies like Wiz identify issues and vulnerabilities with cos. One must upgrade cos to address some vulnerabilities. Without the knowledge of what cos version is attached to a gke version, it is a guess and check approach that takes way too much time.

**Comment by neolit123** [comment]
> ### What would you like to be added?
> The build number of the cos attached to releases of gke verions needs to be added to changelogs, release documentation, etc.
> 
> Examples, would be nice to have it here: https://cloud.google.com/kubernetes-engine/docs/release-notes-nochannel
> 
> Somewhere it's seen, and so one doesn't have to dig for the information, or doesn't have to upgrade and hope they're on a version of cos that they need to target.
> 
> ### Why is this needed?
> Vulnerability issue tracking from companies like Wiz identify issues and vulnerabilities with cos. One must upgrade cos to address some vulnerabilities. Without the knowledge of what cos version is attached to a gke version, it is a guess and check approach that takes way too much time.

please log this issue with GKE support.
open source k8s does not manage COS images or GKE specifics.

/kind support
/close
