### ISSUE TITLE
Provide OpenStack instructions on the CoreOS cluster configuration

### ISSUE THREAD

**Issue by vallard** [kubernetes/kubernetes#12587]
The file: https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/getting-started-guides/coreos/coreos_multinode_cluster.md has instructions for AWS, GCE, and VMware.  I'd like to see documentation for OpenStack as well.  
I'd be happy to do the work for this as I don't think it would take too much time.  I'll add some instructions to this issue if its something that people think would be helpful.

**Comment by rastapopulous** [comment]
I would greatly appreciate any work you can do with this. I've been trying, unsuccessfully, to get the OpenStack integration working.

**Comment by vallard** [comment]
Ok, I created instructions in this gist: https://gist.github.com/vallard/9583d9e20a3a338dc139  If it looks good to you I'll create a pull request and merge changes in the document after the GCE section (as it appears we're going in Alphabetical order? )

**Comment by erictune** [comment]
Sending a PR sounds good.
