### ISSUE TITLE
No resources found

### ISSUE THREAD

**Issue by trojanul2008** [kubernetes/kubernetes#125840]
### What happened?

I created a namespace "lab-pods", I switched from default namespace to "lab-pods" namespace. I created 4 pods in namespace "lab-pods", I deleted the namespace "lab-pods". I received the message that the "lab-pods" namespace was deleted but when I asked to see the pods in the "lab-pods" namespace I received the message "No resources found in lab-pods namespace." 

### What did you expect to happen?

It should have said that the namespace/resource requested does not exist.

### How can we reproduce it (as minimally and precisely as possible)?

1
`$ kubectl create namespace lab-pods
namespace/lab-pods created
`

2
`$ kubectl get ns
NAME              STATUS   AGE
default           Active   43h
ingress-nginx     Active   43h
kube-node-lease   Active   43h
kube-public       Active   43h
kube-system       Active   43h
lab-pods          Active   13s
`

3
`$ kns  lab-pods
Context "kubernetes-admin@kubernetes" modified.`

4
`$ kubectl apply -f phippy-db.yaml
pod/phippy-db created
`

5
`$ kubectl apply -f phippy-api.yaml
pod/phippy-api created
`

6
`$ kubectl apply -f toolbox.yaml
pod/toolbox created
`
7
`$ kubectl apply -f phippy-ui.yaml
pod/phippy-ui created
`

8
`$ kubectl get pods -o wide
NAME         READY   STATUS    RESTARTS   AGE     IP             NODE                 NOMINATED NODE   READINESS GATES
phippy-api   1/1     Running   0          7m28s   10.x.x.x    ip-192-168-x-x   <none>           <none>
phippy-db    1/1     Running   0          8m42s   10.x.x.x   ip-192-168-x-x   <none>           <none>
phippy-ui    1/1     Running   0          3m45s   10.x.x.x   ip-192-168-x-x   <none>           <none>
toolbox      1/1     Running   0          5m10s   10.x.x.x   ip-192-168-x-x   <none>           <none>
`

9
`$ kubectl delete namespace lab-pods
namespace "lab-pods" deleted
`

10
`$ kubectl get pods -o wide
**No resources found in lab-pods namespace**.
`

11
`$ kubectl get ns
NAME              STATUS   AGE
default           Active   44h
ingress-nginx     Active   44h
kube-node-lease   Active   44h
kube-public       Active   44h
kube-system       Active   44h
`

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
`WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.11", GitCommit:"f25b321b9ae42cb1bfaa00b3eec9a12566a15d91", GitTreeState:"clean", BuildDate:"2024-06-11T20:11:29Z", GoVersion:"go1.21.11", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.28) exceeds the supported minor version skew of +/-1
`
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> It should have said that the namespace/resource requested does not exist.

it by design like that, but leaving this ticket open as maybe SIG CLI can comment.

/sig cli

**Comment by tamilselvan1102** [comment]
if you delete the namespace the resources belong to that will be deleted. it is the general behavior

**Comment by trojanul2008** [comment]
I agree that the resources that belong to that namespace will be deleted that is obvious, I do not agree to the message returned which states that "No resources found in lab-pods namespace" instead of saying for example "The namespace lab-pods does not exist" or "The resource that you requested does not exist" when I try to request any type of resource from a namespace that was deleted...  :)

**Comment by trojanul2008** [comment]
> This version is no longer supported. For more details check this link:https://kubernetes.io/releases/ I suggest you to try this with a supported version.

I have update the version and the message returned is the same.

`
$ kubectl version --client --output=yaml
clientVersion:
  buildDate: "2022-06-15T14:22:29Z"
  compiler: gc
  gitCommit: f66044f4361b9f1f96f0053dd46cb7dce5e990a8
  gitTreeState: clean
  gitVersion: v1.24.2
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: windows/amd64
kustomizeVersion: v4.5.4
`

$ k delete ns lab-pods
namespace "lab-pods" deleted

$ k get pods
No resources found in lab-pods namespace.

**Comment by ardaguclu** [comment]
This comment https://github.com/kubernetes/kubectl/issues/1290#issuecomment-1276468256 explains why this was designed in that way and as it's duplicate of multiple issues, I'd prefer closing it;

/close
