### ISSUE TITLE
do we have NormalizeScorePlugin plugin for scheduler

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#125937]
### What happened?

```
package plugin

import (
    "context"
    "fmt"
    "k8s.io/kubernetes/pkg/scheduler/framework"
     "k8s.io/apimachinery/pkg/runtime"
)

// NormalizeScorePlugin is a normalize score plugin.
type MyNormalizeScorePlugin struct {
    handle framework.Handle
}

// Name returns the name of the plugin.
func (p *MyNormalizeScorePlugin) Name() string {
    return "MyNormalizeScorePlugin"
}

// NormalizeScore normalizes the scores to a range of 0 to 100.
func (p *MyNormalizeScorePlugin) NormalizeScore(ctx context.Context, state *framework.CycleState, pod *framework.PodInfo, scores framework.NodeScoreList) *framework.Status {
    fmt.Printf("before NormalizeScore score %s \n", scores)
    var maxScore, minScore int64 = -1, -1
    for _, score := range scores {
        if maxScore == -1 || score.Score > maxScore {
            maxScore = score.Score
        }
        if minScore == -1 || score.Score < minScore {
            minScore = score.Score
        }
    }

    if maxScore == minScore {
        for i := range scores {
            scores[i].Score = 100
        }
    } else {
        for i := range scores {
            scores[i].Score = 100 * (scores[i].Score - minScore) / (maxScore - minScore)
        }
    }
    fmt.Printf("after NormalizeScore score %s \n", scores)
    return framework.NewStatus(framework.Success, "")
}

// New initializes a new plugin and returns it.
func New(_ runtime.Object, handle framework.Handle) (framework.Plugin, error) {
    return &MyNormalizeScorePlugin{
        handle: handle,
    }, nil
}

var _ framework.NormalizeScorePlugin = &MyNormalizeScorePlugin{}
```

plugin/plugin.go:53:17: undefined: framework.NormalizeScorePlugin

### What did you expect to happen?

compile no error

### How can we reproduce it (as minimally and precisely as possible)?

compile the code

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.27.1
</details>

### Cloud provider

<details>
vmware
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 13567436138** [comment]
root@mark-VMware-Virtual-Platform:~/myUnreservePlugin# go build -o my-scheduler main.go
# myUnreservePlugin/plugin
plugin/plugin.go:32:17: undefined: framework.UnreservePlugin

the same problem,do we have UnreservePlugin for scheduler

**Comment by googs1025** [comment]
Currently, the scheduler framework should have the interface method you need. https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/interface.go#L523
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/interface.go#L490

What is your k8s version? Or is there an error in your compilation process? Maybe you need to provide more information

**Comment by AxeZhan** [comment]
Nope, we don't have a `NormalizeScorePlugin` type, you need to implement NormalizeScore under a score plugin.
