### ISSUE TITLE
DRA: rename pkg/cm/dra/plugin files

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#125924]
### What would you like to be added?

https://github.com/kubernetes/kubernetes/pull/125163#discussion_r1665552886:
- plugin.go -> registration.go
- client.go -> plugin.go

The PR above moved everything related to `Plugin` into `client.go` because that was where most of the code already was, but didn't renamed the files to avoid a larger diff and merge conflicts.

Once https://github.com/kubernetes/kubernetes/pull/125488 is merged, we can do the renaming.

### Why is this needed?

Code clarity.

/sig node

**Comment by carlory** [comment]
will do
