### ISSUE TITLE
[Flaking Test][sig-windows]pull-kubernetes-e2e-capz-windows-master

### ISSUE THREAD

**Issue by mengjiao-liu** [kubernetes/kubernetes#125903]
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124439/pull-kubernetes-e2e-capz-windows-master/1808394643918819328

### Which tests are flaking?

pull-kubernetes-e2e-capz-windows-master
```
Release "calico" does not exist. Installing it now.
Error: failed to install CRD crds/calico/crd.projectcalico.org_felixconfigurations.yaml: 1 error occurred:
	* Post "https://capz-conf-enp638-c72af9c3.canadacentral.cloudapp.azure.com:6443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?fieldManager=helm": unexpected EOF

```

### Since when has it been flaking?

6-27 20:00 CST

### Testgrid link

https://testgrid.k8s.io/sig-windows-presubmit#pull-kubernetes-e2e-capz-windows

### Relevant SIG(s)

/sig windows

**Comment by jsturtevant** [comment]
This should be passing now after https://github.com/kubernetes-sigs/windows-testing/pull/445
