### ISSUE TITLE
kube-proxy: userspace proxier should clean up iptables proxier's mess

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#12596]
If you switch from iptables back to userspace, all the rules are left behind.

@BenTheElder

**Comment by BenTheElder** [comment]
Should be a pretty easy fix though we may have to copy over the chain
parsing or add that back to the iptables package. Thoughts?

**Comment by BenTheElder** [comment]
Add it back to the util/iptables package*

**Comment by thockin** [comment]
Maybe we can get away with just unlinking KUBE-SERVICES from OUTPUT and PREROUTING ?  This is an experimental thing, you can leave a TODO if we keep it long term...

**Comment by BenTheElder** [comment]
Ok, sounds good. I'll put out a PR shortly.
