### ISSUE TITLE
OOMKiller test consistently failing in EC2 cgroupv1 serial jobs

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/kubernetes#126009]
### Which jobs are failing?

* ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks
* ci-cgroupv1-containerd-node-e2e-serial-ec2-eks

### Which tests are failing?

```
E2eNode Suite.[It] [sig-node] OOMKiller for pod using more memory than node allocatable [LinuxOnly] [Serial] single process container without resource limits The containers terminated by OOM killer should have the reason set to OOMKilled
```

### Since when has it been failing?

It has been failing consistently for a long time.

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv1-containerd-node-e2e-serial-ec2-eks
https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks

### Reason for failure (if possible)

```
{ failed [FAILED] Failed waiting for pod to terminate, nodeallocatable-oomkiller-test-2000/oomkill-nodeallocatable-pod: Timed out after 300.001s.
The matcher passed to Eventually returned the following error:
    <*errors.errorString | 0xc0016b6a30>: 
    Expected pod "oomkill-nodeallocatable-pod" in namespace "nodeallocatable-oomkiller-test-2000" to be terminated with reason "", got reason: "Evicted"
    {
        s: "Expected pod \"oomkill-nodeallocatable-pod\" in namespace \"nodeallocatable-oomkiller-test-2000\" to be terminated with reason \"\", got reason: \"Evicted\"",
    }
In [It] at: k8s.io/kubernetes/test/e2e_node/oomkiller_linux_test.go:123 @ 07/10/24 12:18:42.111
}
```

### Relevant SIG(s)

/sig node

**Comment by AnishShah** [comment]
There's another bug #120646 that was filed a long time ago. But there's no update on it and the same test in gce jobs seem to be green now.

**Comment by dims** [comment]
cc @tzneal
