### ISSUE TITLE
E2E: E2eNode Suite.[It] [sig-node] PodPidsLimit [Serial] With config updated with pids limits should set pids.max for Pod

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/kubernetes#126007]
### Which jobs are failing?

kubelet-gce-e2e-swap-fedora-serial

### Which tests are failing?

This test is failing consistently:

```
E2E: E2eNode Suite.[It] [sig-node] PodPidsLimit [Serial] With config updated with pids limits should set pids.max for Pod
```

### Since when has it been failing?

Last 3 runs of this test consistently failed at the time of filing this bug.

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora-serial

### Reason for failure (if possible)

The pod is not getting deleted within the timeout period of 2 mins:

```
{ failed [FAILED] wait for pod "pod122cee7b-faae-4868-84ab-ff42fbd6eabc" to disappear: expected pod to not be found: Timed out after 120.000s.
```

### Relevant SIG(s)

/sig node

**Comment by AnishShah** [comment]
From kubelet logs, I see that kubelet delays pod deletion.

```
I0712 16:54:31.505198   32297 status_manager.go:939] "Delaying pod deletion as the phase is non-terminal" phase="Pending" localPhase="Pending" pod="pids-limit-test-3343/podd26eb2cc-b5b4-464a-a071-0d79778a296c" podUID="7cdb4474-3d42-4637-90eb-0298473b9bfb"
```

**Comment by haircommander** [comment]
Looks like this has been fixed!

/close
