### ISSUE TITLE
why  build visitor NewFlattenListVisitor  func executed twice repeatedly

### ISSUE THREAD

**Issue by Jerry-yz** [kubernetes/kubernetes#126042]
### What happened?

cli-runtime builder.Do func execute two times NewFlattenListVisitor func for build visitor

builder.Do() func execute once
[first](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/resource/builder.go#L1177)

builder.visitByPaths execute once
[two](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/resource/builder.go#L1142)

### What did you expect to happen?

visitByPaths func is in Do func logic,  If the outer layer has been executed, whether the inner layer does not require redundant execution.

### How can we reproduce it (as minimally and precisely as possible)?

none

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by googs1025** [comment]
Maybe these methods are used elsewhere? You can try testing it in the unit test file

**Comment by Jerry-yz** [comment]
> Maybe these methods are used elsewhere? You can try testing it in the unit test file

the method is used no other where

**Comment by googs1025** [comment]
As far as I understand, there is no problem with this code. If `len(b.paths) == 0`, there is no problem of duplicate settings.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/resource/builder.go#L868
