### ISSUE TITLE
Remove long deprecated gitrepo volume plugin from code base

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#126041]
### What happened?

In SIG Storage Meeting today, @bswartz pointed out that `gitrepo` in-tree volume was deprecated a long time ago (see https://github.com/kubernetes/kubernetes/issues/60999) but the code is still around and may have vulnerabilities.

We should consider removing it.

### What did you expect to happen?

It looks like completely removing the API/code would have been considered a backwards incompatible change which k8s avoids, and so only a deprecation notice was created and the code was left as is see https://github.com/kubernetes/kubernetes/pull/63445#issuecomment-387438109

We have been able to get rid of other in-tree plugins by keeping the API and implementing "CSI migration" which enables the implementation to be removed and redirect to new CSI drivers. In this case there is no "CSI" migration -- instead the recommendation is to use emptyDir + initContainers.

To remove risk from the unmaintained code -- I suggest that we keep the API, but remove the implementation. (We did exactly this with Flocker, for example, see https://github.com/kubernetes/kubernetes/pull/111618)/)

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Kubernetes version

1.30

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by saad-ali** [comment]
/assign @noctarius
Chris indicated on Slack he's interested in driving this.

**Comment by saschagrunert** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/125983
