### ISSUE TITLE
Accessing etcd container from another container

### ISSUE THREAD

**Issue by wwhurley** [kubernetes/kubernetes#12606]
I'm able to access etcd from the k8s master on port 4001 but I'm struggling to connect to it from another container using confd. I've tried localhost, the IP address for the k8s master and even the IP addresses listed in the Dns config for docker without any luck. Any suggestions or direction would be appreciated.

**Comment by cjcullen** [comment]
By default, etcd on the master binds to 127.0.0.1:4001, and is configured to use the host's network namespace, so you can reach it at localhost if you are running in the host's network namespace.

From inside a container running in bridge mode (not --net=host), localhost resolves to the namespace of the container, and you can't reach anything listening on the host machine's localhost.

You might be able to use the --listen-client-urls flag to tell etcd to bind to more addresses, but this isn't really an intended use (I don't think). Why do you want direct access to the apiserver's etcd?

**Comment by wwhurley** [comment]
Trying to set up a confd nginx proxy to route external requests to the appropriate service. I figured confd would be the easiest solution to get annotations and build out the proxy, since only GKE has a supported external load balancer at the moment.

**Comment by erictune** [comment]
GKE and many of the Getting-started-guides treat etcd as private to apiserver.  There are a couple of reasons for this:
1.  To allow control over which etcd version is used with apiserver. (the one we performance and correctness tested)
1. Secrets are currently kept in plaintext in etcd, so you need to limit etcd access to trusted parties. This is awkward when etcd is shared by several uses. (This could be solved by encrypting the secrets before storing in etcd; discussed in #11937)
1. data format of apiserver state in etcdis not versioned nor intended to be used by others.

So, I'd suggest running a separate etcd instance for your confd.
