### ISSUE TITLE
kubelet-gce-e2e-swap-ubuntu-serial jobs are timing out

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/kubernetes#126008]
### Which jobs are failing?

kubelet-gce-e2e-swap-ubuntu-serial

### Which tests are failing?

Random tests are failing due to test suite timeout

### Since when has it been failing?

It has been failing for a long time.

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu-serial

### Reason for failure (if possible)

It is failing due to test suite timeout.

```
timedout [TIMEDOUT] A suite timeout occurred
```

Increasing the test suite timeout should help.

### Relevant SIG(s)

/sig node

**Comment by dims** [comment]
@AnishShah dup of https://github.com/kubernetes/kubernetes/issues/126001 i think

**Comment by kannon92** [comment]
Yea I think increasing timeout to be similar to fedora swap would be a good thing to try.
