### ISSUE TITLE
Can we implement `kubectl get pod -o gron` ?

### ISSUE THREAD

**Issue by rmetzler** [kubernetes/kubernetes#126097]
### What would you like to be added?

I do a lot of debugging and scripting with kubectl. A common pattern I use is something like:

```
kubectl get pod -n prometheus -o json | gron | grep image
```

gron is a tool which transforms JSON in line-based JavaScript notation, which makes it greppable and easy to manipulate. It's written in Go and Licensed under MIT.  (I'm not a lawyer, I don't know if this is a compatible license.)

https://github.com/tomnomnom/gron

My question would be, if it makes sense and would be beneficial to be able to do something like:

```
kubectl get pod -n prometheus -o gron | grep image
```

### Why is this needed?

It's not really needed, but might be convenient.

**Comment by ardaguclu** [comment]
Unfortunately, we can't support every output option and we always strongly recommend to implement a kubectl plugin for such cases.

**Comment by Ritikaa96** [comment]
HI @rmetzler, JFYI ,If you have a repetitive command you working with you can also use kubectl [alias](https://kubernetes.io/docs/reference/kubectl/quick-reference/#kubectl-context-and-configuration) .

**Comment by BenTheElder** [comment]
This should probably stay a post-processing step, json and other output formats we support are widely used and supported standards. As mentioned above you can create an alias to avoid typing it. Something like this in your bashrc: `kgron(){ kubectl get -o json $@ | gron}`
