### ISSUE TITLE
Issue: NFS Server Not Mounting on Agent Pod

### ISSUE THREAD

**Issue by rakesh0022** [kubernetes/kubernetes#126028]
@jingxu97  @saad-ali 
### What happened?

I am using google cloud , on that i have created gke cluster and install the nfs server on to it and created a PV for nfs server
and then created pv and pvc which is using nfs server ip for connection and lastly we are using a clinet-deployment.yaml file which is used to connect with nfs server mount point and use the /data volume
We are experiencing an issue where the NFS server is running correctly, but the client pod defined in client-deployment.yaml is failing to start. Below are the details of each configuration file and the error logs, and i have attached the logs for nfs server
![mount-error](https://github.com/kubernetes/kubernetes/assets/92107358/a3502250-e36e-40cd-8f40-8bcf7a33cb51)

### What did you expect to happen?

the client pod should be mounted with /data mount point with nfs server

### How can we reproduce it (as minimally and precisely as possible)?

please find below code for you reference

Configuration Files
nfs-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: nfs4-web
spec:
replicas: 1
selector:
matchLabels:
app: nfs-server
template:
metadata:
labels:
app: nfs-server
spec:
initContainers:
- name: init-modules
image: busybox
command: ["/bin/sh", "-c", "modprobe nfs && modprobe nfsd && modprobe rpcsec_gss_krb5"]
securityContext:
privileged: true
volumeMounts:
- name: modules
mountPath: /lib/modules
readOnly: true
volumes:
- name: data
gcePersistentDisk:
pdName: gce-nfs-disk
fsType: ext4
- name: modules
hostPath:
path: /lib/modules
containers:
- name: server
image: erichough/nfs-server
imagePullPolicy: IfNotPresent
securityContext:
privileged: true
volumeMounts:
- mountPath: /data
name: data
- mountPath: /lib/modules
name: modules
env:
- name: NFS_DISABLE_VERSION_3
value: "yes"
- name: NFS_LOG_LEVEL
value: DEBUG
- name: NFS_SERVER_THREAD_COUNT
value: "6"
- name: NFS_EXPORT_0
value: /data *(rw,sync,fsid=0,crossmnt,no_subtree_check,no_root_squash)

nfs-pv.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
name: nfs-pv
spec:
capacity:
storage: 10Gi
accessModes:
- ReadWriteMany
nfs:
server: 34.118.233.16
path: /data
persistentVolumeReclaimPolicy: Retain
storageClassName: nfs-storage-class

nfs-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: my-pvc
spec:
accessModes:
- ReadWriteMany
resources:
requests:
storage: 2Gi
storageClassName: nfs-storage-class
volumeName: nfs-pv

client-deployment.yaml

apiVersion: v1
kind: Pod
metadata:
name: nfs-test-pod
spec:
containers:

name: nfs-test-container
image: busybox
command: ["sleep", "3600"]
volumeMounts:
mountPath: /mnt/nfs
name: nfs-volume
volumes:
name: nfs-volume
nfs:
server: 34.118.226.147 # Replace with the IP address of your NFS server
path: /data
readOnly: false

### Anything else we need to know?

nfs server logs 
[downloaded-logs-20240708-205018.json](https://github.com/user-attachments/files/16175254/downloaded-logs-20240708-205018.json)

### Kubernetes version

we are using the latest version of gke
i think 1.29.xx 

### Cloud provider

I am using google cloud , on that i have created gke cluster and install the nfs server on to it and created a PV for nfs server 
and then created pv and pvc which is using nfs server ip for connection and lastly we are using a clinet-deployment.yaml file which is used to connect with nfs server mount point and use the /data volume

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

student-00-c41c08d6d3ad@gke-cluster-1-default-pool-43144b86-cvbz ~ $ cat /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=1a8b1dfd94df6f28729aca0565343c0a9f6906ee
GOOGLE_CRASH_ID=Lakitu
VERSION=109
VERSION_ID=109
BUILD_ID=17800.218.69

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
a better place to ask would be on the support channels or google support themselves. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
