### ISSUE TITLE
Failure cluster [5cf7d618...] `[sig-network] Services should preserve source pod IP for traffic thru service cluster IP`

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#126089]
I expect this to be something related to the EC2/Kubeadm based cluster setup. https://github.com/kubernetes-sigs/provider-aws-test-infra

##### Error text:
```
[FAILED] Expected
    <string>: 172.31.94.67
to equal
    <string>: 172.31.84.110
In [It] at: k8s.io/kubernetes/test/e2e/network/service.go:1058 @ 06/30/24 04:01:35.438

```
#### Recent failures:
[7/14/2024, 3:31:32 PM ci-kubernetes-e2e-ubuntu-ec2-arm64-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-ec2-arm64-containerd/1812570369752567808)
[7/14/2024, 3:04:25 PM pr:pull-kubernetes-e2e-ec2](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/126088/pull-kubernetes-e2e-ec2/1812563536254078976)
[7/14/2024, 2:28:47 PM pr:pull-kubernetes-e2e-ec2](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121968/pull-kubernetes-e2e-ec2/1812554550926643200)
[7/14/2024, 12:15:36 PM ci-kubernetes-e2e-ec2-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-alpha-enabled-default/1812521044456509440)
[7/14/2024, 10:07:31 AM pr:pull-kubernetes-e2e-ec2](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/126086/pull-kubernetes-e2e-ec2/1812488817991487488)

/kind failing-test

/sig network

**Comment by dims** [comment]
cc @aojea

**Comment by chengjoey** [comment]
![image](https://github.com/user-attachments/assets/a78e11fd-1a12-49d0-9b07-f2c35c332718)

![image](https://github.com/user-attachments/assets/8ed665a2-d691-4fe1-bec9-8dd0458ba735)

It seems that the clientip returned by these e2e tests has become the node host ip instead of the source pod ip.

**Comment by aojea** [comment]
yeah, you need to avoid masquerading the internal Pod traffic, see how we do with kindnet

https://github.com/kubernetes-sigs/kind/blob/79ffb67882fb77f0c8286ea89af66293bed76e1e/images/kindnetd/cmd/kindnetd/main.go#L149-L151

an alternative is to use the ipmasq agent https://github.com/kubernetes-sigs/ip-masq-agent or kindnet directly https://github.com/aojea/kindnet

**Comment by dims** [comment]
@chengjoey @aojea thanks for the tips. Should we add some notes in the test itself that it needs to avoid masquerading internal pod traffic?

**Comment by aojea** [comment]
> @chengjoey @aojea thanks for the tips. Should we add some notes in the test itself that the cluster should NOT masquerade internal pod traffic?

nope, that is a [fundamental requirement of the kubernetes networking model ](https://kubernetes.io/docs/concepts/services-networking/)

> pods can communicate with all other pods on any other [node](https://kubernetes.io/docs/concepts/architecture/nodes/) without NAT

and this tests is just validating the cluster is conformance with the networking model of kubernetes

**Comment by aojea** [comment]
on the contrary, I just think this should be conformance

**Comment by dims** [comment]
> on the contrary, I just think this should be conformance

@aojea Let's do that then! And when we do, make sure the error messages/logs indicate better what to look for when things go wrong.

**Comment by aojea** [comment]
is it working now?

**Comment by chengjoey** [comment]
/assign

add some notes for this test

**Comment by dims** [comment]
> is it working now?

not yet

**Comment by danwinship** [comment]
Discussed in the SIG meeting; this test is actually wrong; K8s requires that _direct_ pod-to-pod traffic does not get masqueraded, but does not require that for pod-to-ClusterIP-to-pod traffic (and, in particular, the old userspace proxy did not work that way, and iptables/nftables kube-proxy can be configured to `--masquerade-all` if you are using a network plugin that requires that behavior).

**Comment by danwinship** [comment]
(This was probably added to validate the "new" iptables behavior when that backend was added, and then when the userspace proxy went away, it got switched from "iptables and ipvs only" to "backend agnostic", even though it's not really. At any rate, the iptables and nftables backends validate their masquerading behavior for all types of services in their `TestInternalExternalMasquerade` unit tests.)

**Comment by dims** [comment]
@danwinship thanks! looking forward to an update to test that fails. i still have CI jobs that "fail" so that will be useful to see if the updates to the test fixed those failures

**Comment by aojea** [comment]
To clarify, the test is not wrong, what is wrong is to apply the test generally, so it may be modified to use a tag to indicate that the test can only be used on services proxy implementation that does not masquerade the ClusterIP traffic

**Comment by aojea** [comment]
an important note, all the clusters that masquerade the traffic on Services ClusterIP will have more problems to implement network policies to the traffic that goes through the Services

**Comment by danwinship** [comment]
OK, so:
- Pod-to-service-to-pod non-masquerading is not a requirement.
- The iptables and nftables kube-proxy unit tests validate that their own pod-to-service-to-pod rules do not masquerade.
- Direct pod-to-pod non-masquerading IS a hard requirement, but we currently only have a `Slow`, feature-tagged test for it (`test/e2e/network/no_snat.go`).

So I propose that:
1. We remove `Services should preserve source pod IP for traffic thru service cluster IP`.
2. We split out a new smaller version of `Should be able to send traffic between Pods without SNAT` that only tests connectivity between a reasonable number of nodes, rather than testing _every_ node (and make it non-`Slow` and not tagged).
3. We promote that new test to conformance.

**Comment by aojea** [comment]
> We remove Services should preserve source pod IP for traffic thru service cluster IP.

This test is opt-in, so I prefer to keep it, despite is not required a cluster that masquerade IP traffic will break a lot of Services demanded features, as mTLS per example ... and it has been running this way for years without any complain so it should not be a problem

> Direct pod-to-pod non-masquerading IS a hard requirement, but we currently only have a Slow, feature-tagged test for it (test/e2e/network/no_snat.go).

it is simpler to cap that test so it always run with a max number of nodes, we already do that with , currently it takes less than 20 seconds to run https://testgrid.k8s.io/sig-network-kind#sig-network-kind,%20master&include-filter-by-regex=NAT&graph-metrics=test-duration-minutes

```
grep -r GetBoundedReadySchedulableNodes test/
test/e2e/storage/persistent_volumes-local.go:           nodes, err := e2enode.GetBoundedReadySchedulableNodes(ctx, f.ClientSet, maxNodes)
test/e2e/storage/local_volume_resize.go:                        nodes, err := e2enode.GetBoundedReadySchedulableNodes(ctx, f.ClientSet, maxNodes)
test/e2e/framework/network/utils.go:    nodeList, err := e2enode.GetBoundedReadySchedulableNodes(ctx, config.f.ClientSet, maxNetProxyPodsCount)
test/e2e/framework/node/resource.go:// GetBoundedReadySchedulableNodes is like GetReadySchedulableNodes except that it returns
test/e2e/framework/node/resource.go:func GetBoundedReadySchedulableNodes(ctx context.Context, c clientset.Interface, maxNodes int) (nodes *v1.NodeList, err error) {
test/e2e/framework/node/resource.go:    nodes, err := GetBoundedReadySchedulableNodes(ctx, c, maxCount)
test/e2e/framework/node/node_killer.go: nodes, err = GetBoundedReadySchedulableNodes(ctx, k.client, numNodes)
test/e2e/framework/service/jig.go:      nodes, err := e2enode.GetBoundedReadySchedulableNodes(ctx, j.Client, 2)
test/e2e/network/conntrack.go:          nodes, err := e2enode.GetBoundedReadySchedulableNodes(ctx, cs, 2)
test/e2e/network/hostport.go:           nodes, err := e2enode.GetBoundedReadySchedulableNodes(ctx, cs, 1)
test/e2e/network/dual_stack.go:         nodeList, err := e2enode.GetBoundedReadySchedulableNodes(ctx, cs, 3)
test/e2e/network/service.go:            nodes, err := e2enode.GetBoundedReadySchedulableNodes(ctx, cs, 2)
test/e2e/network/service.go:            nodes, err := e2enode.GetBoundedReadySchedulableNodes(ctx, cs, 2)
```

for conformance is better to wait at least one release to avoid surprises :) https://github.com/kubernetes/kubernetes/pull/126294

**Comment by danwinship** [comment]
> This test is opt-in

In what way? It doesn't have any feature tags. That makes it part of the "default" test suite doesn't it?

**Comment by aojea** [comment]
>  the "default" test suite doesn't it?

default for kubernetes/kubernetes,  the e2e test is an internal suite, we only expose `Conformance` to the end users, external projects already use regex for filtering the test they want to run

**Comment by danwinship** [comment]
I don't think that's how people think about the e2e tests. If there is nothing in the test that _explicitly_ indicates that it is not universal, then people assume it's supposed to pass everywhere, even if it's not strictly required for conformance. (In particular, this bug was filed because @dims was assuming that the test was supposed to pass in e2e-ec2, and that the failure to pass indicated a problem with the test or with kube-proxy.)
