### ISSUE TITLE
Enhance PodCondition by adding LastTransitionTime, Reason, Message

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#12615]
Filing this issue to track implementing this TODO: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L829.

We need PodCondition.LastTransitionTime to support AvailableThresholdSeconds (minimum seconds for which the pod should be "ready", before it can be considered "truly ready") as discussed in https://github.com/kubernetes/kubernetes/pull/12236#discussion_r36823378

cc @bgrant0607

**Comment by bgrant0607** [comment]
Detail: We need to restart the clock for AvailableThresholdSeconds whenever containers restart.
