### ISSUE TITLE
[failing-test] ProcMount Specific SecurityContext set fails

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#126180]
After https://github.com/kubernetes/kubernetes/pull/125259 merged we are seeing the new test added in https://github.com/kubernetes/kubernetes/pull/123303/files fail since it was turned on be default now (it passed in the PR linked because it didn't have the alpha feature enabled).

```
Kubernetes e2e suite: [It] [sig-windows] [Feature:Windows] SecurityContext should ignore ProcMount Specific SecurityContext if 
```

<br class="Apple-interchange-newline">
</body>
</html>

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1813661088579850240

```
{ failed [FAILED] Pod "pod-77ced19a-4786-47e3-a166-cbffe9cb367c" is invalid: spec.containers[0].securityContext.procMount: Invalid value: "Unmasked": `hostUsers` must be false to use `Unmasked`
In [It] at: k8s.io/kubernetes/test/e2e/windows/security_context.go:181 @ 07/17/24 20:16:10.774
```

/sig windows
/sig node

/cc @sohankunkerkar @haircommander

**Comment by mrunalp** [comment]
@sohankunkerkar @haircommander ptal
