### ISSUE TITLE
Gracefull and Controlled / Ordered Cluster Shutdown and Controlled / Ordered Startup

### ISSUE THREAD

**Issue by Martin-Weiss** [kubernetes/kubernetes#126103]
### What would you like to be added?

Could we get some sort of technology to get an organized and controller "complete cluster shutdown" and "controlled startup" into Kubernetes?

**Background - Shutdown:** 
From time to time we need to poweroff a data-center i.e. for maintenance purposes. In case we have a single cluster in a single data-center with some workload on top of it - we need to controll the shutdown of the workload (scale to replicas = 0) before we can drain and shutdown all the workers and control plane in a given kubernetes cluster.

We do not want to delete the whole cluster during this exercise as re-deploment of cluster and workload would be a lot of traffic and load.

**Background - Startup:**
When we start up the cluster and its nodes - the workload needs to be re-scheduled (scale to replicas >0) once a specific number of workers is back alive in the cluster and ideally to the same number of replicas as "before" the shutdown. So we need some sort of control on how long the "scale up" should wait before the workload gets started to avoid imbalance - and re-balance needs during power-on / startup.

I understand that we basically never want to shutdown a whole cluster - but sometimes / due to physical maintenace or maintenance on the platform - it might still be required.. also physical re-locations need this as well.

Idea would be some sort of automation / controller based process that would scale down everything to 0 while remembering the scale "before shutdown" - and during power-on - scale back to what we had before but in relation to wait for a set of workers and / or wait for some sort of timeout.

### Why is this needed?

Physical maintenance needs - maintenance needs that require a full rack ... full data-center to be powered off.

**Comment by neolit123** [comment]
> I understand that we basically never want to shutdown a whole cluster - but sometimes / due to physical maintenace or maintenance on the platform - it might still be required.. also physical re-locations need this as well.

yes, because that's the opposite of what users want - i.e. they don't want to introduce workload downtime.
the feature you are requesting doesn't seem suitable for core k8s and i don't thinks it's technically possible either. 

instead, i suggest you close this ticket and start looking at project like kOps, kubespray and cluster-api that can maybe accept the idea / feature request of such a orchestrated shutdown.

/sig architecture
