### ISSUE TITLE
[Flaking Test]  [sig-node] [NodeFeature:NodeProblemDetector] should run without error 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#126192]
### Which jobs are failing?

NodeProblemDetector [NodeFeature:NodeProblemDetector] should run without error 

### Which tests are failing?

ci-kubernetes-e2e-gci-gce-alpha-enabled-default

### Since when has it been failing?

for a long time

### Testgrid link

https://testgrid.k8s.io/google-gce#gci-gce-alpha-enabled-default

### Reason for failure (if possible)

failed [FAILED] an error on the server ("Internal Error: failed to list pod stats: rpc error: code = Unknown desc = 1 error occurred:\n\t* failed to decode sandbox container metrics for sandbox \"2dda500c81c49c73488ad52cb6a19563ac33ccd365b01ea328a1d6381c226398\": ttrpc: closed: unknown") has prevented the request from succeeding (get nodes bootstrap-e2e-minion-group-vgh1:10250)
In [It] at: k8s.io/kubernetes/test/e2e/node/node_problem_detector.go:381 @ 07/16/24 21:09:33.122
}
```
STEP: Gather node-problem-detector cpu and memory stats - k8s.io/kubernetes/test/e2e/node/node_problem_detector.go:164 @ 07/16/24 21:06:26.828
I0716 21:09:33.122599 10712 node_problem_detector.go:381] Unexpected error: 
    <*errors.StatusError | 0xc0003c1e00>: 
    an error on the server ("Internal Error: failed to list pod stats: rpc error: code = Unknown desc = 1 error occurred:\n\t* failed to decode sandbox container metrics for sandbox \"2dda500c81c49c73488ad52cb6a19563ac33ccd365b01ea328a1d6381c226398\": ttrpc: closed: unknown") has prevented the request from succeeding (get nodes bootstrap-e2e-minion-group-vgh1:10250)
    {
        ErrStatus: 
            code: 500
            details:
              causes:
              - message: "Internal Error: failed to list pod stats: rpc error: code = Unknown
                  desc = 1 error occurred:\n\t* failed to decode sandbox container metrics for
                  sandbox \"2dda500c81c49c73488ad52cb6a19563ac33ccd365b01ea328a1d6381c226398\":
                  ttrpc: closed: unknown"
                reason: UnexpectedServerResponse
              kind: nodes
              name: bootstrap-e2e-minion-group-vgh1:10250
            message: 'an error on the server ("Internal Error: failed to list pod stats: rpc error:
              code = Unknown desc = 1 error occurred:\n\t* failed to decode sandbox container
              metrics for sandbox \"2dda500c81c49c73488ad52cb6a19563ac33ccd365b01ea328a1d6381c226398\":
              ttrpc: closed: unknown") has prevented the request from succeeding (get nodes bootstrap-e2e-minion-group-vgh1:10250)'
            metadata: {}
            reason: InternalError
            status: Failure,
    }
[FAILED] an error on the server ("Internal Error: failed to list pod stats: rpc error: code = Unknown desc = 1 error occurred:\n\t* failed to decode sandbox container metrics for sandbox \"2dda500c81c49c73488ad52cb6a19563ac33ccd365b01ea328a1d6381c226398\": ttrpc: closed: unknown") has prevented the request from succeeding (get nodes bootstrap-e2e-minion-group-vgh1:10250)
In [It] at: k8s.io/kubernetes/test/e2e/node/node_problem_detector.go:381 @ 07/16/24 21:09:33.122
< Exit [It] should run without error - k8s.io/kubernetes/test/e2e/node/node_problem_detector.go:63 @ 07/16/24 21:09:33.122 (3m10.139s)

```

### Anything else we need to know?

similar issue https://github.com/kubernetes/kubernetes/issues/122118

### Relevant SIG(s)

/sig node

**Comment by wangzhen127** [comment]
The NPD specific CI tests are running fine: https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-kubernetes-gce-gci, which runs NPD as system daemon.

Is the [gci-gce-alpha-enabled-default](https://testgrid.k8s.io/google-gce#gci-gce-alpha-enabled-default) test running NPD as daemonset? @hakman can you help take a look?

/cc @AnishShah @digitalveer

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/bee5e03707bcd66b92d453278816707eac387d4a/cluster/addons/node-problem-detector/npd.yaml#L26-L48

It seems to be a DS.

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/125874

**Comment by kannon92** [comment]
/triage accepted
/priority important-soon

Can someone from NPD take a look at this?

**Comment by AnishShah** [comment]
/cc @hakman 

can you take a look?
