### ISSUE TITLE
No explanation of error returned from SharedInformer.AddEventHandler

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#126106]
The comments do not explain why the AddEventHandler method of SharedInformer can return an error. No mention of what errors can appear, what such an appearance would mean. The caller gets no clue about how to react to an error.

**Comment by Ritikaa96** [comment]
Hi @MikeSpreitzer , it will be helpful if you add some context and log the issue as per the issue format.

**Comment by MikeSpreitzer** [comment]
See #126235 instead.
