### ISSUE TITLE
Error during pulling of v.1.30.3 images

### ISSUE THREAD

**Issue by nicofnt** [kubernetes/kubernetes#126170]
### What happened?

I was trying to create a new k8s cluster and there was now way to pull images for v1.30.3.
_kubeadm init_ command gives the same results.

`[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.30.3: output: E0717 17:53:46.785794   43580 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.30.3\": failed to resolve reference \"registry.k8s.io/kube-apiserver:v1.30.3\": registry.k8s.io/kube-apiserver:v1.30.3: not found" image="registry.k8s.io/kube-apiserver:v1.30.3"
time="2024-07-17T17:53:46+02:00" level=fatal msg="pulling image: rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.30.3\": failed to resolve reference \"registry.k8s.io/kube-apiserver:v1.30.3\": registry.k8s.io/kube-apiserver:v1.30.3: not found"
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-controller-manager:v1.30.3: output: E0717 17:53:48.966539   43682 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.30.3\": failed to resolve reference \"registry.k8s.io/kube-controller-manager:v1.30.3\": registry.k8s.io/kube-controller-manager:v1.30.3: not found" image="registry.k8s.io/kube-controller-manager:v1.30.3"
time="2024-07-17T17:53:48+02:00" level=fatal msg="pulling image: rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.30.3\": failed to resolve reference \"registry.k8s.io/kube-controller-manager:v1.30.3\": registry.k8s.io/kube-controller-manager:v1.30.3: not found"
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-scheduler:v1.30.3: output: E0717 17:53:51.057338   43761 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.30.3\": failed to resolve reference \"registry.k8s.io/kube-scheduler:v1.30.3\": registry.k8s.io/kube-scheduler:v1.30.3: not found" image="registry.k8s.io/kube-scheduler:v1.30.3"
time="2024-07-17T17:53:51+02:00" level=fatal msg="pulling image: rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.30.3\": failed to resolve reference \"registry.k8s.io/kube-scheduler:v1.30.3\": registry.k8s.io/kube-scheduler:v1.30.3: not found"
, error: exit status 1`

### What did you expect to happen?

I was expecting images to be correctly pulled from registry.k8s.io

### How can we reproduce it (as minimally and precisely as possible)?

Try to upgrade current kubernetes cluster to version 1.30.3 using 

`killall -s SIGTERM kube-apiserver && sleep 30 && kubeadm upgrade apply v1.30.3`

or simply use `kubeadm config images pull` to pull latest kubernetes images

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
$ uname -a
#5.14.0-427.24.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jul 8 17:47:19 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: v1.30.3
#Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
#Server Version: v1.30.2
```

</details>

### Cloud provider

On Prem.

/sig cli

**Comment by neolit123** [comment]
> [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.30.3: output: E0717 17:53:46.785794   43580 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.30.3\": failed to resolve reference \"registry.k8s.io/kube-

seems like a networking error.
you must prepull images on a machine that can do it and then have the images ready on a machine that cannot pull.
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#without-internet-connection

for more support questions please use the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support

**Comment by nicofnt** [comment]
I had no problems pulling images using kubeadm config images pull --kubernetes-version=v1.30.2 though. And tried from different machines and clean environment.

**Comment by aphick** [comment]
I can replicate this issue:

```
time="2024-07-17T10:16:08-07:00" level=fatal msg="pulling image: rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.30.3\": failed to resolve reference \"registry.k8s.io/kube-controller-manager:v1.30.3\": registry.k8s.io/kube-controller-manager:v1.30.3: not found"
```

**Comment by nicofnt** [comment]
> Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`

@k8s-ci-robot

> I am experiencing this issue as well:
> 
> `time="2024-07-17T10:16:08-07:00" level=fatal msg="pulling image: rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.30.3\": failed to resolve reference \"registry.k8s.io/kube-controller-manager:v1.30.3\": registry.k8s.io/kube-controller-manager:v1.30.3: not found"`

@neolit123 Can we re-open this issue?

**Comment by CoreFloDev** [comment]
same issue for me as well

**Comment by neolit123** [comment]
sorry about that,
the images do not exist!

i will ping the release team on slack about this.

/sig release
/priority critical-urgent

**Comment by neolit123** [comment]
> I had no problems pulling images using kubeadm config images pull --kubernetes-version=v1.30.2 though. And tried from different machines and clean environment.

we get a lot of tickets from users in restricted network setups and that's why i though "this is support ticket...".
1.30.3 was released today and looks like the images are not there...

**Comment by neolit123** [comment]
images are available but looks like there is a networking issue with the registry:
https://explore.ggcr.dev/?image=registry.k8s.io%2Fkube-apiserver:v1.30.3

**Comment by neolit123** [comment]
try debugging your connectivity:
https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md

for me i have DNS resolution and connectivity but can't get the specific images.

**Comment by BenTheElder** [comment]
/triage accepted
being discussed in https://kubernetes.slack.com/archives/CJH2GBF7Y/p1721239285050569, appears to be a sync issues with the regional backends and the image promotion process.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/promo-tools/issues/1271

**Comment by BenTheElder** [comment]
We've manually restarted the sync process again, it's running.

**Comment by BenTheElder** [comment]
I think this is fixed after an additional re-run of the sync process (the one above was the second rerun)

Can you confirm that this is resolved now? Thanks!

**Comment by neolit123** [comment]
thanks @BenTheElder 

pulling works for me now:
```
$ docker pull registry.k8s.io/kube-apiserver:v1.30.3
v1.30.3: Pulling from kube-apiserver
...
```

how bout you @nicofnt and @CoreFloDev ?

**Comment by CoreFloDev** [comment]
@neolit123 Yes working fine now, thanks!

**Comment by pacoxu** [comment]
It works for me now and I tested from multi region.
/close 
Feel free to reopen if you still can not pull these images.
