### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Minimum CPU request is displayed when only memory request is configured

### ISSUE THREAD

**Issue by hshiina** [kubernetes/kubernetes#126195]
### What happened?

If `InPlacePodVerticalScaling` is enabled and only a memory resource request is configured in a pod, the minimum CPU request set internally is displayed in the pod status:
```
$ kubectl get pod testpod -o jsonpath='spec: {.spec.containers[0].resources}{"\nallocatedResources: "}{.status.containerStatuses[0].allocatedResources}{"\nstatus: "}{.status.containerStatuses[0].resources}{"\n"}'
spec: {"requests":{"memory":"200Mi"}}
allocatedResources: {"memory":"200Mi"}
status: {"requests":{"cpu":"2m","memory":"200Mi"}}
```

### What did you expect to happen?

The minimum CPU request is not displayed in the pod status.

### How can we reproduce it (as minimally and precisely as possible)?

1. Enables the `InPlacePodVerticalScaling` feature.
2. Create a pod where only memory request is configured:
   <Details>

   ```
   apiVersion: v1
   kind: Pod
   metadata:
     labels:
       run: testpod
     name: testpod
   spec:
     containers:
     - image: nginx
       name: testpod
       resources:
         requests:
           memory: 200Mi
     restartPolicy: Always
   ```

   </Details>
3. See its resources in the pod status:
   ```
   $ kubectl get pod testpod -o jsonpath='spec: {.spec.containers[0].resources}{"\nallocatedResources: "}{.status.containerStatuses[0].allocatedResources}{"\nstatus: "}{.status.containerStatuses[0].resources}{"\n"}'
   spec: {"requests":{"memory":"200Mi"}}
   allocatedResources: {"memory":"200Mi"}
   status: {"requests":{"cpu":"2m","memory":"200Mi"}}
   ```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

</details>

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Octopusjust** [comment]
If `InPlacePodVerticalScaling` is disabled, will the internally set minimum CPU request be displayed in the Pod status?

**Comment by hshiina** [comment]
No, container resources are not displayed in a pod status unless `InPlacePodVerticalScaling` is enabled.

**Comment by hshiina** [comment]
This minimum CPU request in runtime status causes another error internally in kubelet. The following messages are logged in `kubelet.log` at every pod resync:
```
Jul 30 09:14:47 kind-control-plane kubelet[702]: I0730 09:14:47.436195     702 kuberuntime_manager.go:1051] "computePodActions got for pod" podActions="KillPod: false, CreateSandbox: false, UpdatePodResources: false, Attempt: 0, InitContainersToStart: [], ContainersToStart: [], EphemeralContainersToStart: [],ContainersToUpdate: map[cpu:[{0 {containerd 34bd8427f9d86a8795ba5d56ddc5f51d7b3dd9722686c62d30c1e672d6910ca9} {314572800 209715200 0 0} 0xc0014c7e00}]], ContainersToKill: map[]" pod="default/resize-pod"
Jul 30 09:14:47 kind-control-plane kubelet[702]: E0730 09:14:47.436340     702 kuberuntime_manager.go:750] "podResources.CPUQuota or podResources.CPUShares is nil" pod="resize-pod"
```

Because the unset CPU request in the pod spec is treated as zero and the CPU request in the runtime status is the minimum value, a resize action is computed due to the gap:
https://github.com/kubernetes/kubernetes/blob/0fc167103189a4d462c3cc7a17b360c3d998f4bf/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L573
https://github.com/kubernetes/kubernetes/blob/0fc167103189a4d462c3cc7a17b360c3d998f4bf/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L586

This is the situation described in #126388 where the CPU request is resized when the CPU limit is not configured. Then, it hits the following error:
https://github.com/kubernetes/kubernetes/blob/0fc167103189a4d462c3cc7a17b360c3d998f4bf/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L754-L758

**Comment by hshiina** [comment]
I have added a fix for the problem(https://github.com/kubernetes/kubernetes/issues/126195#issuecomment-2257922410) to the PR #126196 because this problem will occur more possibly especially if #126480 is merged. With #126480, this problem will occur in every `BestEffort` Qos pod.

**Comment by kannon92** [comment]
@esotsal Could you help triage this?

**Comment by esotsal** [comment]
@hshiina i followed steps in description using v1.32.0-alpha.0.191+1e45c3acd639c6 output is as you describe, interestingly 
testing it with https://github.com/kubernetes/kubernetes/pull/123319 (v1.32.0-alpha.0.189+c897550e76e691), output is below.
```
kubectl get pod testpod -o jsonpath='spec: {.spec.containers[0].resources}{"\nallocatedResources: "}{.status.containerStatuses[0].allocatedResources}{"\nstatus: "}{.status.containerStatuses[0].resources}{"\n"}'
spec: {"requests":{"memory":"200Mi"}}
allocatedResources: 
status: 
```
+1 to accept this for triage, @kannon92 I added it today's SIG Node to decide triage this

**Comment by tallclair** [comment]
It's not clear to me that this is undesirable. The resources in the container status represent the "actual resources" that the container is currently configured with. If the Kubelet is setting a default CPU request, wouldn't this be a good place to surface it?

**Comment by hshiina** [comment]
I'm afraid I misunderstood this problem.
`MilliCPUToShares()` returns `2` if `0`  is passed:
https://github.com/kubernetes/kubernetes/blob/1a16c2d57815b013f11011897043dfa3ad463d76/pkg/kubelet/cm/helpers_linux.go#L84-L90
However, `sharesToMilliCPU()` returns `2` if `2` is passed:
https://github.com/kubernetes/kubernetes/blob/1a16c2d57815b013f11011897043dfa3ad463d76/pkg/kubelet/kuberuntime/helpers_linux.go#L65-L69

`sharesToMilliCPU()` should convert `2 CPUshares` to `0 milliCPU` request.
