### ISSUE TITLE
dra nvidia k8s-dra-driver helm chart install with error

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#126285]
### What happened?

W0723 09:36:00.907949       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.cudaDriverVersion"
W0723 09:36:00.907986       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.driverVersion"
I0723 09:36:00.922111       1 device_state.go:146] using devRoot=/driver-root
W0723 09:36:00.924825       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.cudaDriverVersion"
W0723 09:36:00.924835       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.driverVersion"
W0723 09:36:00.928266       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.cudaDriverVersion"
W0723 09:36:00.928278       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.driverVersion"

### What did you expect to happen?

no error

### How can we reproduce it (as minimally and precisely as possible)?

 kubectl logs -n nvidia-dra nvidia-dra-k8s-dra-driver-kubelet-plugin-zqrbw  

### Kubernetes version

<details>
root@k8s-master01:~/k8s-dra-driver#  kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
</details>

### Cloud provider

<details>
pve 8
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
please log the issue in the repository where the helm chart comes from.
/close
/kind support
/sig node

**Comment by 13567436138** [comment]
https://gitlab.com/nvidia/cloud-native/k8s-dra-driver

**Comment by 13567436138** [comment]
https://github.com/NVIDIA/k8s-dra-driver
