### ISSUE TITLE
please support new dockercfg format for private registries support

### ISSUE THREAD

**Issue by onorua** [kubernetes/kubernetes#12626]
I do not know whether you noticed already, but docker changed default format and location for the dockercfg. 
Previously it was `$HOME/.dockercfg` right now it's  `$HOME/.docker/config.json` and they slightly changed format:
#### previously
```
{
        "registryaddress": {
                "auth": "auth string",
                "email": "email@domain.com"
        }
}
```
#### current format
```
{
        "auths": {
                "registryaddress": {
                        "auth": "auth string",
                        "email": "email@domain.com"
                }
        }
}
```
and kubernetes requires to have "https://" prefix in order to work for old format, while docker doesn't require it, as a result, documentation at [http://kubernetes.io/v1.0/docs/]
(http://kubernetes.io/v1.0/docs/user-guide/images.html#configuring-nodes-to-authenticate-to-a-private-repository) it outdated and that's why you have so much "private registry" issues opened. 
So we either need to update documentation or to support new format, I personally think new format support is preferable, but it's up to you.

**Comment by erictune** [comment]
Thanks for the clear explanation.  Would you be interested in sending a patch?

It looks like config file locations are searched in pkg/credentialprovider/config.go in function ReadDockerConfigFile().

Looks like parsing also happens in that file.

And there are tests of json parsing in pkg/credentialprovider/config_test.go.

**Comment by onorua** [comment]
I would love to, but have 0 go language experience :( any way, it seems not that difficult, will try my best

**Comment by ngbinh** [comment]
This issue took me a day to figure out what's wrong. :( Will try to send a PR this weekend

**Comment by liggitt** [comment]
cc @deads2k
