### ISSUE TITLE
Release a go mod version (with no replace)

### ISSUE THREAD

**Issue by hunshcn** [kubernetes/kubernetes#126261]
### What would you like to be added?

The go.mod content of k8s.io/kubernetes contains the replace directive, which makes it cumbersome to import it (requires replace k8s.io/*).

When we release a new version, is it possible to release a version for go mod k/k, e.g. v1.29.7-mod.

Since it's already been released, it would be possible to have k8s.io/* use the corresponding version instead of `replace`, like in v1.29.7, use
```
require k8s.io/api v0.29.7
```

I tried it and it works fine https://github.com/hunshcn/kubernetes/commit/72b15e5969cc6c02b1b1a88f732ac8c403716b2
(current usage is `replace k8s.io/kubernetes => github.com/hunshcn/kubernetes v1.29.7-mod`)

I know that k/api's v0.29.7 was created according to k/k's v1.29.7, so I propose to create a new v1.29.7-mod to use v0.29.7.

This seems like something that should be done by test-infra, but since it's related to the main repository, it's posted here

### Why is this needed?

This can be helpful in certain scenarios where you need to import k/k, such as [scheduling-framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/624-scheduling-framework/README.md#custom-scheduler-plugins-out-of-tree).

**OR make scheduling-framework out of k/k ?**

**Comment by saschagrunert** [comment]
Hey @hunshcn, I'd say k/k should not be imported directly, that's what the staging repos (like k8s.io/api) are for.

**Comment by hunshcn** [comment]
> Hey @hunshcn, I'd say k/k should not be imported directly, that's what the staging repos (like [k8s.io/api](https://github.com/kubernetes/api)) are for.


But building [Custom Scheduler Plugins](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/624-scheduling-framework/README.md#custom-scheduler-plugins-out-of-tree) need import k/k.

**Comment by hunshcn** [comment]
k/k's import problem with scheduler has been mentioned 3 years age https://github.com/kubernetes/kubernetes/issues/107263.

The current common practice is to do replace, such as [sigs.k8s.io/kube-scheduler-simulator/simulator](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/simulator/go.mod), which doesn't make much sense.

If k/k doesn't want to be imported, we may need to move the scheduler to k8s.io/scheduler?

If the scheduler remains in k/k, then this issue makes sense.

**Comment by hunshcn** [comment]
may be related

/sig scheduler

**Comment by BenTheElder** [comment]
re: replace statements, see the dependency scripts under hack/, these are used intentionally to pin deps, we also actually build from vendor, and we have go.work now.


> If k/k doesn't want to be imported, [..]

It has been the general stance that this is not considered supported (though even some other subprojects do it, we're just not taking features/bugs related to it), and I'm pretty sure I raised this on the discussion for scheduler plugins.


> [...] we may need to move the scheduler to k8s.io/scheduler?

That's not super realistic and doesn't really change that anyone building a plugin needs to match the go packages and go version exactly.

I personally don't think go plugins are a great approach and it would be better to revisit that part, or else accept that scheduler extensions will have to deal with this.

I've also previously raised this but ... Go's official docs for plugins mostly consist of warnings about drawbacks to using them: https://pkg.go.dev/plugin#hdr-Warnings

> Runtime crashes are likely to occur unless all parts of the program (the application and all its plugins) are compiled using exactly the same version of the toolchain, the same build tags, and the same values of certain flags and environment variables.

This goes _way_ past how we manage go.mod

**Comment by hunshcn** [comment]
> I personally don't think go plugins are a great approach and it would be better to revisit that part, or else accept that scheduler extensions will have to deal with this.
> I've also previously raised this but ... Go's official docs for plugins mostly consist of warnings about drawbacks to using them: https://pkg.go.dev/plugin#hdr-Warnings

I just want to clarify that "Custom scheduler plugin" is not a "go plugin". It needs to be programmed by importing "k8s.io/kubernetes/cmd/kube-scheduler/app" and compiled by the maintainer itself, so it faces the problem discussed now.

**Comment by BenTheElder** [comment]
> I just want to clarify that "Custom scheduler plugin" is not a "go plugin". It needs to be programmed by importing "k8s.io/kubernetes/cmd/kube-scheduler/app" and compiled by the maintainer itself, so it faces the problem discussed now.

Into a binary that replaces kube-scheduler, or runs alongside?

Because if the former, we could just tell people to maintain a fork of the repo that adds importing their plugin in a `custom_plugins.go` patch (no rebase diff) that registers the plugin, and allows them to leverage all of the machinery we have to do builds and use go.work/go.mod

Officially telling people to depend on importing k/k is probably not something I would've expected SIG-arch to approve.

**Comment by hunshcn** [comment]
> Into a binary that replaces kube-scheduler, or runs alongside?

Yes. replace as default scheduler or an another scheduler and specify pod's schedulerName to use.

**Comment by hunshcn** [comment]
So it seems that it is an expected behavior for me to modify go.mod myself?

**Comment by dims** [comment]
@hunshcn happy to accept any updates to hack/* scripts to make things better. But it's not going to be sustainable keeping it working always. your specific example may work, but other things may not and over time things will change as well. So sure, please do what you need for your use case.

**Comment by liggitt** [comment]
> Officially telling people to depend on importing k/k is probably not something I would've expected SIG-arch to approve.

Agreed. In fact, we've repeatedly warned against this. The replace directives in the root go.mod file are not *for* this purpose, but the fact that they make it more difficult to consume k8s.io/kubernetes as a go library is not a bad thing, in my opinion. It is explicitly not meant for that purpose.

**Comment by hunshcn** [comment]
Get. Thanks a lot.
