### ISSUE TITLE
kindnetd + coredns issues in ec2 test harness

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#126255]
Either kindnetd fails or that succeeds and then coredns fails :( 

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-alpha-features/1814933513313456128
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023/1814933511295995904
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-arm64-serial/1814933515003760640
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-disruptive/1814933515834232832
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-eks-al2023-serial/1814933514160705536
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-ec2-containerd/1814933761914048512
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-ec2-conformance-latest/1814933761670778880
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-ec2-eks-al2023-arm64-conformance-latest/1814933761851133952
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-ec2-eks-conformance-latest/1814933761729499136

cc @aojea

**Comment by dims** [comment]
@aojea each run should have pod logs under the instance directory. (all logs including kubeproxy, coredns, kindnetd etc)

**Comment by pacoxu** [comment]
/retitle kindnetd + coredns issues in ec2 test harness

**Comment by dims** [comment]
xref: https://github.com/aojea/kindnet/issues/47

**Comment by aojea** [comment]
can we close this already?
