### ISSUE TITLE
Scheduling queue lock improvements follow-ups

### ISSUE THREAD

**Issue by macsko** [kubernetes/kubernetes#126219]
### What would you like to be added?

This issue is to track follow-ups from #125692 and #125820. Those PRs introduced two new locks to scheduling queue and still require some smaller changes to be made:

- [x] Move `activeQ` and other related fields that needs to be locked with new `activeQLock` to a dedicated unexported struct to make it less coupled with the general `lock` ([comment](https://github.com/kubernetes/kubernetes/pull/125692#discussion_r1667112611))
#126680
- [x] Try to get `activeQLock` once while activating the pod ([comment](https://github.com/kubernetes/kubernetes/pull/125692#discussion_r1667133225))
#126222
- [x] Move `NominatedPodsForNode` to scheduling queue directly ([comment](https://github.com/kubernetes/kubernetes/pull/125820#discussion_r1664408410))
#126197
- [x] Improve get operations on the queues by casting the `Pod`/`PodRef` to `ObjectName` directly ([comment](https://github.com/kubernetes/kubernetes/pull/125820#discussion_r1677507672), [comment2](https://github.com/kubernetes/kubernetes/pull/125820#discussion_r1677203190))
#126158

### Why is this needed?

These changes are required to make scheduling queue more manageable in the future and to reduce introducing possible locking issues.

**Comment by macsko** [comment]
> [#125820 (comment)](https://github.com/kubernetes/kubernetes/pull/125820#discussion_r1677203190) here is another one.

It is in "Improve get operations on the queues by casting the Pod/PodRef to ObjectName directly", but added a ref to this comment as well.

**Comment by nayihz** [comment]
It's better to link the related PR to each follow-up.

**Comment by macsko** [comment]
All improvements have been made in the linked commits, so I'm closing the issue.
