### ISSUE TITLE
Promote Go version to either 1.23.0 or revert to 1.22.x before K8s 1.31

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/kubernetes#126299]
sgtm, add an issue labeled as release-blocking and in the milestone to either promote to 1.23.0 or revert this to 1.22.x before our 1.31 release

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/126047#issuecomment-2245648031_

Kubernetes is being built and tested with go1.23rc2 at HEAD (https://github.com/kubernetes/kubernetes/pull/126047) to let it bake in the CI and help iron out issues, if any, with this version of Go.

However, for the 1.31 release, the version of Go should be a non-rc, released version. The release timeline of go1.23.0 is ~same as the release timeline of K8s 1.31.0 (see https://github.com/kubernetes/kubernetes/pull/126047#issuecomment-2235706834). If go1.23.0 is not out by then, we should revert to go1.22.x before cutting K8s 1.31.0.

/sig release architecture
/area code-organization
/cc @liggitt @dims @cpanato

**Comment by wendy-ha18** [comment]
cc @kubernetes/release-team-release-signal

**Comment by MadhavJivrajani** [comment]
xposting relevant slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1721804964443209

**Comment by BenTheElder** [comment]
Also unlike in the past, missing shipping 1.23.0 in 1.31.0 is not a big deal, we have much more room to switch to 1.23.0 in a patch release after all the compat changes with the go team. So we should not fear reverting if the timelines don't line up.

**Comment by liggitt** [comment]
(though go1.23 adds the thing that makes it workable to default to old go version compat settings, so we'll have to eke out another 5 months on 1.21/1.22 for https://github.com/kubernetes/kubernetes/issues/123744 until we can adopt 1.23 on release branches in ~Jan if we miss 1.31, but that's how it looks like it will have to happen)
