### ISSUE TITLE
Make Kubeadm client to call API of it.

### ISSUE THREAD

**Issue by sivchari** [kubernetes/kubernetes#126218]
### What would you like to be added?

I want to add the APIs of Kubeadm to deal with the response easily. 

### Why is this needed?

Currently, we can use kubeadm command and check the result as the output of os.Stdout.
Thus, if we want to handle the output of kubeadm command, we should write the code like following.

```go
package main

import (
    "fmt"
    "os/exec"
)

func runKubeadmCheckExpiration() {
    cmd := exec.Command("kubeadm", "certs", "check-expiration")
    output, err := cmd.Output()
    if err != nil {
        panic(err)
    }
    // convert to struct or something
    // handle the response.
}

func main() {
    runKubeadmCheckExpiration()
}
```

In my case, I want to renew the certification automatically using kubeadm. But, since we don't have the way to call Kubeadm API, I must convert the result to struct myself and if the Kubeadm's API will be expanded in the future, I must upgrade the defined struct of my code, too.
It sounds hard for me (maybe for us) and I want to deal with the response of kubeadm as easily as client-go.
Thus, I propose to expose the API about kubeadm command. If this proposal will be accepted, we can use the information about Kubeadm more easily than now.

**Comment by neolit123** [comment]
> It sounds hard for me (maybe for us) and I want to deal with the response of kubeadm as easily as client-go.
Thus, I propose to expose the API about kubeadm command. If this proposal will be accepted, we can use the information about Kubeadm more easily than now.

sorry but there are no plans for adding such a feature to kubeadm anytime soon.
it requires a lot of planning and design to start exposing parts of kubeadm as a library.

https://github.com/kubernetes/kubeadm/issues/2316

also kubernetes/kubenetes should not be imported as a library so it means kubeadm must first move outside of this repo..

https://github.com/kubernetes/kubeadm/issues/1949

/close

**Comment by neolit123** [comment]
newer versions of kubeadm (i think 1.30) support the --experimental-output / --output = json flag which can give you structured output of the kubeadm certs check-certs expiration command.

**Comment by sivchari** [comment]
@neolit123 
Thank you for providing good information. I might understand the points to archive this hope.
I'll check the issues you wrote.

Has the plan to move kubeadm from k/k to outside progresses, yet ? If so, I want to help it as much as possible. If not, I want to digcuss about separating   kubeadm from k/k. Thanks.

The problem I wrote at first would solve using --output flag. Thank you so much, too.
