### ISSUE TITLE
Topology aware endpoint filtering logs too much.

### ISSUE THREAD

**Issue by npinaeva** [kubernetes/kubernetes#126271]
### What happened?

Since `ServiceTrafficDistribution` was promoted to beta and enabled by default https://github.com/kubernetes/kubernetes/pull/125838, v2 logs in kube-proxy are getting too aggressive logging the same message (see timestamps, this cluster has 10K services)
```
I0722 11:01:53.493532       1 topology.go:165] "Skipping topology aware endpoint filtering since node is missing label" label="topology.kubernetes.io/zone"
I0722 11:01:53.493604       1 topology.go:165] "Skipping topology aware endpoint filtering since node is missing label" label="topology.kubernetes.io/zone"
I0722 11:01:53.493677       1 topology.go:165] "Skipping topology aware endpoint filtering since node is missing label" label="topology.kubernetes.io/zone"
I0722 11:01:53.493744       1 topology.go:165] "Skipping topology aware endpoint filtering since node is missing label" label="topology.kubernetes.io/zone"
I0722 11:01:53.493808       1 topology.go:165] "Skipping topology aware endpoint filtering since node is missing label" label="topology.kubernetes.io/zone"
I0722 11:01:53.493886       1 topology.go:165] "Skipping topology aware endpoint filtering since node is missing label" label="topology.kubernetes.io/zone"
```

### What did you expect to happen?

The amount of generated logs seems a but too much for v2 log level, and generally not quite helpful with the same message.

### How can we reproduce it (as minimally and precisely as possible)?

Create kind cluster from master, watch kube-proxy logs.

### Anything else we need to know?

There was an attempt to fix this https://github.com/kubernetes/kubernetes/pull/123322, and I think @danwinship was right https://github.com/kubernetes/kubernetes/pull/123322#issuecomment-1946606361.

### Kubernetes version

master

### Cloud provider

NONE

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
with V < 2 does not log, does it?

**Comment by pohly** [comment]
No, there is no "sampling" support in our logging infrastructure. zap has it, but I think it's just randomly picking which log entries to write across all log entries being produced, not per call site. We don't have options to configure that in Kubernetes.

What Kubernetes does instead is to ensure that log levels are used consistently. If this particular log entry is considered too noisy at -v2, then it should use V(3) or higher.

**Comment by robscott** [comment]
If I understand this particular log message correctly, it should only trigger in the following situation:

1. Someone has configured a Service to use topology aware routing
2. The node kube-proxy is running on does not have a Zone, thus meaning that we can't implement 1

This is not a happy state, and I don't think moving the logs down to a lower verbosity level is helpful here until we have some other way to signal this. Is there something wrong with the cluster that's logging this?

It would be great to find a way to make these log messages less frequent, but I think we need at least something at this log level to surface the problem.

**Comment by dims** [comment]
@robscott we are generating a 2.1 GB log file in the ec2/aws kops based CI job for scalability that runs for 4 hours. So i don't think we can ship with these log messages at `V(2)`

**Comment by danwinship** [comment]
did #126519 fix this?

**Comment by robscott** [comment]
> did #126519 fix this?

I believe so, yes. Closing this one out, feel free to reopen if this problem shows up again.

/close
