### ISSUE TITLE
can you please backport emptyDir 0777 to some 1.0.x release?

### ISSUE THREAD

**Issue by onorua** [kubernetes/kubernetes#12627]
I can see in [blame] (https://github.com/kubernetes/kubernetes/blame/871ca7a05f3aeb0f2324b1d424ae67ada8425486/pkg/volume/empty_dir/empty_dir.go) that July 8 @pmorie did a change to empty dir rights. 
I can see history of the tag:
```
git show v1.0.3
tag v1.0.3
Tagger: Brendan Burns <bburns@google.com>
Date:   Thu Aug 6 21:57:40 2015 -0700

Kubernetes version v1.0.3

commit 61c6ac5f350253a4dc002aee97b7db7ff01ee4ca
Author: Brendan Burns <bburns@google.com>
Date:   Thu Aug 6 21:56:59 2015 -0700

    Kubernetes version v1.0.3
```
that it was in August 6. 
I can check that latest change in tag v1.0.3 is:
```
git log  pkg/volume/empty_dir/empty_dir.go  | head
commit fd22f48f5bba3523c7d5ed1bc2ff102cb656ca9d
Author: Tim Hockin <thockin@google.com>
Date:   Mon May 18 13:26:09 2015 -0700

    rename StorageType StorageMedium

commit cd359ffa73dce63c7318c9ce56396458ee4b0008
Author: Paul Morie <pmorie@redhat.com>
Date:   Sun May 10 20:12:57 2015 -0400
```
apparently you do not release 1.0.x from master but from 1.0 branch. When can we expect that emptydir to be released, is it possible to backport the change to 1.0 meantime?

**Comment by thockin** [comment]
I'm ok with cherry-picking this into 1.0.x

@zmerlynn arguments?

**Comment by zmerlynn** [comment]
#9384? It would defiantly be a behavioral change for a patch release, so I think it's past the bar.

**Comment by thockin** [comment]
It looks like a big change but it's semantically simple.  That said, v1.1
is just a couple months out.  I think we can wait.

**Comment by pmorie** [comment]
I am hoping that by then we will have sorted out volumes and non-root permissions.
