### ISSUE TITLE
Add repobeats to the readme

### ISSUE THREAD

**Issue by kenm47** [kubernetes/kubernetes#126212]
### What would you like to be added?

Add https://repobeats.axiom.co/ to readme to show off the development of the project

### Why is this needed?

Kubernetes is the most significant project on github ever. Adding repobeats to show off the incredible support this project gets would be of benefit to the community.

**Comment by neolit123** [comment]
/sig contributor-experience

#sig-contribex on k8s slack might have feedback on that.
