### ISSUE TITLE
See extra disks in container other than the one mounted inside the pod using lsblk command

### ISSUE THREAD

**Issue by adarsh-dell** [kubernetes/kubernetes#126262]
### What happened?

Here's the scenario I tested on k8 cluster:

Created two pods, each consuming its own PVC/PV (mounting only one volume for each pod), and both got scheduled on the same worker node.
Both pods are in a running state and volumes are mounted.
Observations:

Running the `lsblk` command on the worker node shows both blocks and their mounting paths. Please see below screenshot.

![image](https://github.com/user-attachments/assets/278fffef-2ded-47f7-a359-6c5c5ad225b0)

Running the same `lsblk` command from inside one of the app pods (using `exec -it bash`) lists both blocks but shows only one volume as mounted with its mount path. While In the manifest file of this pod I have only mounted one volume, why we are seeing other devices ?

-------------------------------------------------
 I tried to create a very simple and basic pod using below yaml file.

Note: Not using any PVC or dynamic provisioning and this pod also got scheduled to the same worker nodes where other 2 pods are already running and are consuming CSI vols. Even inside this container, if I am running lsblk command I can see sda, sdb.sdc , scnia, scnib etc. Even I haven't mounted anything inside pod.

```
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80 
```
![image](https://github.com/user-attachments/assets/bf3f8a59-c7f7-48d0-a64d-72400f59d777)

Question is that what are we seeing all these devices even without mounting it explicitly inside the pod.

There is no impact and issue in reading or writing the data and issue in functionality wise.

### What did you expect to happen?

Not seeing any extra device other than the one that is mounted inside the pod explicitly.
If this is expected then why?

### How can we reproduce it (as minimally and precisely as possible)?

Steps are mentioned in the description.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3
```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
$ uname -a
Linux master-1-XouLFUVP8VwOg 5.14.21-150500.55.68-default #1 SMP PREEMPT_DYNAMIC Wed Jun 5 21:39:05 UTC 2024 (40e256a) x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jsafrane** [comment]
You runt the first `lsblk` on the host. Kubernetes (kubelet) mounts all volumes of all Pods to the host first and then ask container runtime to bind-mount only Pod's volumes to a given Pod containers. So it is expected that you see all volumes mounted on the host.

You run the second `lsblk` on in a container. You should see only Pod's volumes mounted. lsblk does not show any mounts, that part is OK. I am not sure why it shows also sdb and sdc block devices from the host. What container runtime do you use? And do you have sdb/sdc mounted on the host?

/triage needs-information

**Comment by adarsh-dell** [comment]
Hi @jsafrane Thanks for looking into this issue:

<img width="799" alt="image" src="https://github.com/user-attachments/assets/ba69f0be-2c16-4371-ba91-f84dffc16bbc">

Thanks

**Comment by fanf4** [comment]
Hi @jsafrane ,

please see below for more detail.
1. we created a pod with one pvc mounted (provisioning by DELL powerflex CSI driver)
2.  login to the container "task pv container"  and use "lsblk", found it listed all disks of HOST. but this container only required disk scinie. other disks are mounted by other pods on HOST worker2
![image](https://github.com/user-attachments/assets/32c918fd-0353-4b87-a9bb-c4aaaf3a9348)
3. output of "lsblk" on HOST

[core@worker2 ~]$ lsblk
NAME     MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
loop0      7:0    0    32G  0 loop
sda        8:0    0   200G  0 disk
|-sda1     8:1    0     1M  0 part
|-sda2     8:2    0   127M  0 part
|-sda3     8:3    0   384M  0 part  /boot
`-sda4     8:4    0 199.5G  0 part  /sysroot
sdc        8:32   0     1G  0 disk
`-mpathc 253:2    0     1G  0 mpath /var/lib/kubelet/pods/bd428673-3ea0-403b-ae48-03cde2d7933e/volumes/kubernetes.io~csi/ocpcsivol-91c07d1446/mount
sdd        8:48   0     1G  0 disk
`-mpathd 253:1    0     1G  0 mpath /var/lib/kubelet/pods/eb135fc0-7266-4f20-bb5b-84938c628012/volumes/kubernetes.io~csi/ocpcsivol-78b818c6e2/mount
sde        8:64   0     1G  0 disk
`-mpathe 253:3    0     1G  0 mpath /var/lib/kubelet/pods/44e76f9e-be29-45bc-bf7a-8b123ac259f0/volumes/kubernetes.io~csi/ocpcsivol-430c585c89/mount
sdg        8:96   0     1G  0 disk
`-mpathc 253:2    0     1G  0 mpath /var/lib/kubelet/pods/bd428673-3ea0-403b-ae48-03cde2d7933e/volumes/kubernetes.io~csi/ocpcsivol-91c07d1446/mount
sdh        8:112  0     1G  0 disk
`-mpathd 253:1    0     1G  0 mpath /var/lib/kubelet/pods/eb135fc0-7266-4f20-bb5b-84938c628012/volumes/kubernetes.io~csi/ocpcsivol-78b818c6e2/mount
sdi        8:128  0     1G  0 disk
`-mpathe 253:3    0     1G  0 mpath /var/lib/kubelet/pods/44e76f9e-be29-45bc-bf7a-8b123ac259f0/volumes/kubernetes.io~csi/ocpcsivol-430c585c89/mount
sdk        8:160  0     1G  0 disk
`-mpathc 253:2    0     1G  0 mpath /var/lib/kubelet/pods/bd428673-3ea0-403b-ae48-03cde2d7933e/volumes/kubernetes.io~csi/ocpcsivol-91c07d1446/mount
sdl        8:176  0     1G  0 disk
`-mpathd 253:1    0     1G  0 mpath /var/lib/kubelet/pods/eb135fc0-7266-4f20-bb5b-84938c628012/volumes/kubernetes.io~csi/ocpcsivol-78b818c6e2/mount
sdm        8:192  0     1G  0 disk
`-mpathe 253:3    0     1G  0 mpath /var/lib/kubelet/pods/44e76f9e-be29-45bc-bf7a-8b123ac259f0/volumes/kubernetes.io~csi/ocpcsivol-430c585c89/mount
sdo        8:224  0     1G  0 disk
`-mpathc 253:2    0     1G  0 mpath /var/lib/kubelet/pods/bd428673-3ea0-403b-ae48-03cde2d7933e/volumes/kubernetes.io~csi/ocpcsivol-91c07d1446/mount
sdp        8:240  0     1G  0 disk
`-mpathd 253:1    0     1G  0 mpath /var/lib/kubelet/pods/eb135fc0-7266-4f20-bb5b-84938c628012/volumes/kubernetes.io~csi/ocpcsivol-78b818c6e2/mount
sr0       11:0    1   1.1G  0 rom
sdq       65:0    0     1G  0 disk
`-mpathe 253:3    0     1G  0 mpath /var/lib/kubelet/pods/44e76f9e-be29-45bc-bf7a-8b123ac259f0/volumes/kubernetes.io~csi/ocpcsivol-430c585c89/mount
scinia   252:0    0    32G  0 disk  /var/lib/kubelet/pods/2e1a569c-d025-4913-88ba-5b42acd82f59/volumes/kubernetes.io~csi/k8s-5326050b2c/mount
scinib   252:16   0    40G  0 disk  /var/lib/kubelet/pods/7d76b5db-fc7a-4708-b33a-240535784771/volumes/kubernetes.io~csi/k8s-7326b95dce/mount
scinic   252:32   0    32G  0 disk
scinid   252:48   0    32G  0 disk  /var/lib/kubelet/pods/bf421fc4-8f47-40de-9eb8-3393ef6da4d5/volumes/kubernetes.io~csi/k8s-e8304edf8c/mount
scinie   252:64   0    96G  0 disk  /var/lib/kubelet/pods/6a18b873-5d9a-497d-bf4f-bdeb5160f872/volumes/kubernetes.io~csi/k8s-d5ef8f6832/mount
scinif   252:80   0    96G  0 disk  /var/lib/kubelet/pods/d111ff42-4908-4059-a8d0-b354128b9903/volumes/kubernetes.io~csi/k8s-5107235ef7/mount
scinig   252:96   0    80G  0 disk  /var/lib/kubelet/pods/fc1246d7-7b83-4fe0-be85-59b0a192dc39/volumes/kubernetes.io~csi/k8s-5943f0efde/mount
scinih   252:112  0    80G  0 disk  /var/lib/kubelet/pods/8cc0f29e-fc42-41ae-a644-411bfc5c6e3b/volumes/kubernetes.io~csi/k8s-b20fc647ce/mount
scinii   252:128  0    80G  0 disk  /var/lib/kubelet/pods/bde3fd50-6cf8-4a4c-89cc-d5b8438a7ad2/volumes/kubernetes.io~csi/k8s-5a49ddbd8f/mount


4. we create a pod without PVC . login to the container and run lsblk and see all disks of the HOST as well.
![image](https://github.com/user-attachments/assets/f2c5c470-ed0a-48ad-a06f-c37818660952)

Above tests are in openshift Env.

5. we also tested in K8S env. created pod without pvc.
the container can list all disks of host woker2.  disk scina and scinab are mounted by other pods on worker2.

![image](https://github.com/user-attachments/assets/3d8a8453-b66c-4888-8bd6-5ee8ab23cd71)

**Comment by jsafrane** [comment]
It looks like an issue (or feature?) in containerd, please open an issue there. Kubernetes does not tell the container runtime to show all host devices and some other runtimes explicitly block them. e.g. CRI-O since https://github.com/cri-o/cri-o/pull/4072.

Note that while lsblk can list the host devices, because it uses information from /sys, the devices are not actually not visible in the container - `ls /dev` should not show `sda` or `scini*`.

/close
