### ISSUE TITLE
Investigate improving Job integration test runtime by reusing the api server

### ISSUE THREAD

**Issue by mimowo** [kubernetes/kubernetes#126225]
This is a spin off from https://github.com/kubernetes/kubernetes/issues/126202 as there are still some tests which spawn api server per test case (which takes around 2s). Example https://github.com/kubernetes/kubernetes/blob/dda657b5982e8f9102b8df5931344262b0793163/test/integration/job/job_test.go#L431-L432

The idea is to spawn a single API server, and to avoid Job / pod name collisions use a unique suffix per test case (say test case index).

/sig apps

**Comment by kaisoz** [comment]
I could take care of this if that's ok for you guys? @mimowo @alculquicondor @dejanzele ?

**Comment by dejanzele** [comment]
Feel free to take it @kaisoz, you can assign me for initial review

**Comment by kaisoz** [comment]
/assign

Thanks!
