### ISSUE TITLE
About the possibility of adding remaining field in node status

### ISSUE THREAD

**Issue by googs1025** [kubernetes/kubernetes#126372]
Currently, I am working on cluster capacity management. However, I noticed that the node field only has capacity and allocatable fields. There is no field indicating the remaining capacity of the node. Is there a way for us to record the remaining capacity of the node itself without relying on monitoring systems like Prometheus? For example, could we add a new field called remaining?
I want to get the remaining node information directly from node status without going through the monitoring system

I'm not sure if I might have missed any other methods. Alternatively, implementing this functionality might not be straightforward. This is because we need to consider pods that do not have the requests and limits fields set.

```go
root@VM-0-5-ubuntu:/home/ubuntu# kubectl describe node cluster1-worker2
Name:               cluster1-worker2
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=cluster1-worker2
                    kubernetes.io/os=linux
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: unix:///run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 20 Jul 2024 22:23:07 +0800
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  cluster1-worker2
  AcquireTime:     <unset>
  RenewTime:       Fri, 26 Jul 2024 13:01:57 +0800
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Fri, 26 Jul 2024 12:58:33 +0800   Sat, 20 Jul 2024 22:23:07 +0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Fri, 26 Jul 2024 12:58:33 +0800   Sat, 20 Jul 2024 22:23:07 +0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Fri, 26 Jul 2024 12:58:33 +0800   Sat, 20 Jul 2024 22:23:07 +0800   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Fri, 26 Jul 2024 12:58:33 +0800   Sat, 20 Jul 2024 22:23:12 +0800   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  172.18.0.2
  Hostname:    cluster1-worker2
Capacity:
  cpu:                4
  ephemeral-storage:  20529768Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7474636Ki
  pods:               110
Allocatable:
  cpu:                4
  ephemeral-storage:  20529768Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7474636Ki
  pods:               110
System Info:
  Machine ID:                 cc8f0687a3da484c8f69425b37c637e7
  System UUID:                ec373bdb-af92-4d4f-88d3-5095aa43805f
  Boot ID:                    1e5b572a-9618-43b1-a80a-de385753cf39
  Kernel Version:             5.15.0-113-generic
  OS Image:                   Debian GNU/Linux 12 (bookworm)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.7.13
  Kubelet Version:            v1.29.2
  Kube-Proxy Version:         v1.29.2
```

```go
// NodeStatus is information about the current status of a node.
type NodeStatus struct {
	// Capacity represents the total resources of a node.
	// More info: https://kubernetes.io/docs/reference/node/node-status/#capacity
	// +optional
	Capacity ResourceList `json:"capacity,omitempty" protobuf:"bytes,1,rep,name=capacity,casttype=ResourceList,castkey=ResourceName"`
	// Allocatable represents the resources of a node that are available for scheduling.
	// Defaults to Capacity.
	// +optional
	Allocatable ResourceList `json:"allocatable,omitempty" protobuf:"bytes,2,rep,name=allocatable,casttype=ResourceList,castkey=ResourceName"`
	// NodePhase is the recently observed lifecycle phase of the node.
	// More info: https://kubernetes.io/docs/concepts/nodes/node/#phase
	// The field is never populated, and now is deprecated.
	// +optional

```

**Comment by googs1025** [comment]
<img width="987" alt="image" src="https://github.com/user-attachments/assets/3200bbc3-f8d4-4fbc-a274-c5595d756ddb">

use `kubectl describe node cluster1-worker2`
I see the Allocated resources field, but I don't know where it is defined.

**Comment by Adarsh-verma-14** [comment]
so you can see here may be it is helpful for you https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L4192

**Comment by googs1025** [comment]
> so you can see here may be it is helpful for you https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L4192

Thanks, I found

**Comment by googs1025** [comment]
Another thing I'd like to know is: how does node consider the capacity of a pod that doesn't have requests limits set?

**Comment by Adarsh-verma-14** [comment]
Now I got it you want to know about the possibility of adding remaining field in node status and also how to handle the pod that doesn't have requests limits set ?

**Comment by ffromani** [comment]
The observers (point in case, the scheduler) are expected to do their accounting AFAIK. The kubelet don't update their remaining capacity, one of the reason being the fact node objects are heavyweight and requiring frequent update would tax the apiserver too much.

There are exception though. The node-local kubelet podresources interface does report available quantities with NUMA-level granularity. This is because it's the only way to enable NUMA-aware scheduling.

At this point in time, getting the available capacity is done using 3rd parties (prometheus, daemons consuming the podresources API and exposing it somehow), this is the preferred direction.

**Comment by ffromani** [comment]
> Another thing I'd like to know is: how does node consider the capacity of a pod that doesn't have requests limits set?

we don't. CPU is considered compressible, so these pods (best-effort QoS, because they don't have request set) will "eventually" run somehow. This however has unintended consequences in extreme cases (https://github.com/kubernetes/enhancements/pull/4541#issuecomment-2175001925 )
