### ISSUE TITLE
[Flaking Test] TestUpdateAllocatedResourcesStatus

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#126357]
### Which jobs are flaking?

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Which tests are flaking?

TestUpdateAllocatedResourcesStatus

### Since when has it been flaking?

Few days ago

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Relevant SIG(s)

/sig node

**Comment by kannon92** [comment]
I could reproduce this with `make test GOFLAGS=-count=1 WHAT=pkg/kubelet/cm/devicemanager` in maybe 1/10 times.

**Comment by kannon92** [comment]
cc @ffromani 

```
I0725 16:04:21.570321  958866 manager.go:510] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
I0725 16:04:21.606742  958866 fake_topology_manager.go:33] "NewFakeManager"
--- FAIL: TestUpdateAllocatedResourcesStatus (0.00s)
    manager_test.go:1931: UpdateAllocatedResourcesStatus failed, expected: [{test-container {nil nil nil} {nil nil nil} false 0    <nil> map[] nil [] nil [{test-resource [{dev1 Healthy} {dev2 Unhealthy}]}]}], got: [{test-container {nil nil nil} {nil nil nil} false 0    <nil> map[] nil [] nil [{test-resource [{dev2 Unhealthy} {dev1 Healthy}]}]}]
```

I am unfamilar with this code so wanted to see if you have any ideas on this.

**Comment by ffromani** [comment]
> cc @ffromani
> 
> ```
> I0725 16:04:21.570321  958866 manager.go:510] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
> I0725 16:04:21.606742  958866 fake_topology_manager.go:33] "NewFakeManager"
> --- FAIL: TestUpdateAllocatedResourcesStatus (0.00s)
>     manager_test.go:1931: UpdateAllocatedResourcesStatus failed, expected: [{test-container {nil nil nil} {nil nil nil} false 0    <nil> map[] nil [] nil [{test-resource [{dev1 Healthy} {dev2 Unhealthy}]}]}], got: [{test-container {nil nil nil} {nil nil nil} false 0    <nil> map[] nil [] nil [{test-resource [{dev2 Unhealthy} {dev1 Healthy}]}]}]
> ```
> 
> I am unfamilar with this code so wanted to see if you have any ideas on this.

yes, I'll have a look ASAP

**Comment by pacoxu** [comment]
```
	expectedStatus := v1.ResourceStatus{
		Name: v1.ResourceName(resourceName),
		Resources: []v1.ResourceHealth{
			{
				ResourceID: "dev1",
				Health:     pluginapi.Healthy,
			},
			{
				ResourceID: "dev2",
				Health:     pluginapi.Unhealthy,
			},
		},
	}
	expectedContainerStatuses := []v1.ContainerStatus{
		{
			Name:                     containerName,
			AllocatedResourcesStatus: []v1.ResourceStatus{expectedStatus},
		},
	}
	if !reflect.DeepEqual(status.ContainerStatuses, expectedContainerStatuses) {
		t.Errorf("UpdateAllocatedResourcesStatus failed, expected: %v, got: %v", expectedContainerStatuses, status.ContainerStatuses)
	}
```

In the flake, the ResourceHealth array is with a different order.

If this is acceptable, we should tune the test.

**Comment by ffromani** [comment]
nice catch @pacoxu !

I think the best fix is ensure the ordering of statuses either in the production code or in the test code before to check
Note: if we do this in the production code then we should go full throttle and offer a full API guarantee (docs, explicit tests) because users will depend on this

**Comment by pacoxu** [comment]
A quick fix is like https://github.com/kubernetes/kubernetes/pull/126427
