### ISSUE TITLE
Security Vulnerability: Go Package: gopkg.in/square/go-jose.v2 2.x - End of Life Notification (EOL)

### ISSUE THREAD

**Issue by anjaniprayaga** [kubernetes/kubernetes#126380]
Is your feature request related to a problem? Please describe.
We are currently using the rancher/hardened-kubernetes container image for our project, which was downloaded as part of the RKE2 tarball. This image internally uses version v2.6.0 of square/go-jose. Recently, we received a notification that go-jose.v2 version 2.6.0 has reached its end of life and has been deprecated. Please refer to the notification [here](https://github.com/square/go-jose/blob/master/README.md).

Describe the solution you'd like
We would like to request an upgrade to the supported version v3 of go-jose.

Additional Context:
I would like to reiterate the importance of updating the EOL packages, if a version reaches End Of Life, there won't be any security fixes done for these versions and also the vulnerabilities are not reported for these versions. This sounds like a security risk. I hope this request Is taken on priority.

**Comment by dims** [comment]
please contact rancher and encourage them to work with upstream kubernetes for your needs.

/close

**Comment by dims** [comment]
FYI https://github.com/kubernetes/kubernetes/issues/123252
