### ISSUE TITLE
ci-kubernetes-e2e-capz-master-windows should skip DRA feature e2e

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#126321]
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1815980600901767168

### Which tests are failing?

Kubernetes e2e suite: [It] [sig-api-machinery] ResourceQuota should create a ResourceQuota and capture the life of a ResourceClaim [Feature:DynamicResourceAllocation] expand_less 

### Since when has it been failing?

Today

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master

### Reason for failure (if possible)

{ failed [FAILED] context deadline exceeded In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:518 @ 07/24/24 05:49:04.337  There were additional failures detected after the initial failure. These are visible in the timeline }

### Anything else we need to know?
> That test shouldn't run in that job because the test has the [Feature:DynamicResourceAllocation] label.

See https://github.com/kubernetes/kubernetes/pull/120611#issuecomment-2247056565

> --ginkgo.focus=.... \[sig-api-machinery\].ResourceQuota|...  that's probably it.

### Relevant SIG(s)

/sig windows

**Comment by pohly** [comment]
Converting to `--label-filter` will probably make your focus/skip combination more readable and simpler.

**Comment by jsturtevant** [comment]
> Converting to `--label-filter` will probably make your focus/skip combination more readable and simpler.

Is there documentation on using this?  I've opened https://github.com/kubernetes-sigs/windows-testing/issues/458 to track this update

**Comment by pohly** [comment]
@jsturtevant: see https://groups.google.com/a/kubernetes.io/g/dev/c/uBP23XSbypo and the resources linked in it.

https://github.com/kubernetes-sigs/windows-testing/pull/457 fixes the immediate problem, but as you are not skipping all unknown features, that problem can resurface with some other feature.
