### ISSUE TITLE
Print "LABELS" field for resources after "kubectl label" is executed.

### ISSUE THREAD

**Issue by hurf** [kubernetes/kubernetes#12638]
After using `kubectl label` command, it will print the resources whose label has been modified, in the form of output of 'get' command. eg:

    $ kubectl label no 127.0.0.1 test=abc --overwrite
    NAME        LABELS                                      STATUS    AGE
    127.0.0.1   kubernetes.io/hostname=127.0.0.1,test=abc   Ready     1h

I think the intension is to show users the label change result. But for some resource like `rc` and `pod`, this form doesn't contain `LABELS` field now. eg: 

    $ kubectl label rc --all test=abc --overwrite
    CONTROLLER   CONTAINER(S)   IMAGE(S)   SELECTOR    REPLICAS   AGE
    nginx        nginx          nginx      run=nginx   1          5s
    CONTROLLER         CONTAINER(S)   IMAGE(S)   SELECTOR    REPLICAS   AGE
    nginx-controller   nginx          nginx      app=nginx   2          10s

I'm thinking to show `LABELS` field in this condition. There're three approches in my mind:

1.Customize the output format in `label` command. eg:

    TYPE    NAME     LABELS
    pod     nginx    app=nginx,test=abc  

2.Use the output of `describe` command. eg:

    Name:		nginx-controller
    Namespace:	default
    Image(s):	nginx
    Selector:	app=nginx
    Labels:		app=nginx,test=abc
    Replicas:	2 current / 2 desired
    Pods Status:	2 Running / 0 Waiting / 0 Succeeded / 0 Failed
    Events:

3.Modify functions in `resource_printer`, allow functions accept customized columns and values as optional parameters. Then we can print same resource in the format of `get` command, but with extra columns. eg:

    CONTROLLER   CONTAINER(S)   IMAGE(S)   SELECTOR    REPLICAS   AGE  LABELS
    nginx        nginx          nginx      run=nginx   1          5s   app=nginx,test=abc

Which one looks better?

**Comment by bgrant0607** [comment]
My opinion is that we should not be printing resource details after these kinds of commands. We should just print a short message similar to other mutations.

**Comment by bgrant0607** [comment]
See my comment here: https://github.com/kubernetes/kubernetes/issues/5906#issuecomment-117832140

**Comment by hurf** [comment]
OK, I'll read the related issue and work on it.

**Comment by hurf** [comment]
Closing since it's fixed
