### ISSUE TITLE
[Flaking Tests] Device Manager, TestUpdateAllocatedResourcesStatus

### ISSUE THREAD

**Issue by drewhagen** [kubernetes/kubernetes#126392]
### Which jobs are flaking?

sig-release-master-blocking
* [ci-kubernetes-unit](https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit)

### Which tests are flaking?

* k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.devicemanager (TestUpdateAllocatedResourcesStatus)

### Since when has it been flaking?

7/25

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Anything else we need to know?

K8s Triage link:
https://storage.googleapis.com/k8s-triage/index.html?text=TestUpdateAllocatedResourcesStatus

### Relevant SIG(s)

Unsure yet

**Comment by kannon92** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/126357

**Comment by drewhagen** [comment]
Closing as duplicate
