### ISSUE TITLE
authentication to kubernetes apiserver (vagrant setup)?

### ISSUE THREAD

**Issue by snrism** [kubernetes/kubernetes#12630]
I have a vagrant based kubernetes setup (https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/vagrant.md)

With this, I am able to spin-up/lookup pods, services, rc via kubectl or using ./cluster/kubectl.sh. 

Now, I am trying to reach the apiserver in the master node via API calls. As an example, when I use the --insecure option, I can retrieve existing pods/services etc.
"curl --insecure https://vagrant:vagrant@10.245.1.2/api/v1/pods"

However, if I try to create new pods using the insecure option say:
"curl --user vagrant:vagrant --insecure https://10.245.1.2/api/v1/pods -XPOST -d redis-master.json"

I get the following error:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server does not allow this method on the requested resource",
  "reason": "MethodNotAllowed",
  "details": {},
  "code": 405
}

Setup details:
Vagrant version: 1.7.4 on MacOS X version 10.9.5
I also noticed that the ~/.kubernetes_vagrant_auth only contains the following:
{
  "User": "vagrant",
  "Password": "vagrant"
}

and does not contain the CAFile, CertFile, KeyFile. 

Where can I find the crt, key files for the setup and by which methodology can I authenticate to the APIServer. Any pointers will be helpful. Thanks in advance.

**Comment by kgrvamsi** [comment]
Can you post the output or try doing a Get request of nodes with curl ?

**Comment by snrism** [comment]
@kgrvamsi :With the --insecure option (curl --user vagrant:vagrant --insecure https://10.245.1.2/api/v1/nodes), I get the minion-1 node's full info:
{
  "kind": "NodeList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/nodes",
    "resourceVersion": "15018"
  },
  "items": [
    {
      "metadata": {
        "name": "10.245.1.3",
        "selfLink": "/api/v1/nodes/10.245.1.3",
        "uid": "f7778291-4120-11e5-af7e-0800279dd272",
        "resourceVersion": "15018",
        "creationTimestamp": "2015-08-12T18:35:55Z",
        "labels": {
          "kubernetes.io/hostname": "10.245.1.3"
        }
      },
      "spec": {
        "externalID": "10.245.1.3",
        "providerID": "vagrant://10.245.1.3"
      },
      "status": {
        "capacity": {
          "cpu": "2",
          "memory": "1017552Ki",
          "pods": "40"
        },
        "conditions": [
          {
            "type": "Ready",
            "status": "True",
            "lastHeartbeatTime": "2015-08-13T17:11:39Z",
            "lastTransitionTime": "2015-08-13T16:51:07Z",
            "reason": "kubelet is posting ready status"
          }
        ],
        "addresses": [
          {
            "type": "LegacyHostIP",
            "address": "10.245.1.3"
          }
        ],
        "nodeInfo": {
          "machineID": "6c30ad3b41fa4d1e89745cef6f22c4de",
          "systemUUID": "F5C35957-F2A6-4D75-B853-7D70BC6FDB54",
          "bootID": "c5e853ce-76e1-45d5-82aa-94a050be93fd",
          "kernelVersion": "3.17.4-301.fc21.x86_64",
          "osImage": "Fedora 21 (Twenty One)",
          "containerRuntimeVersion": "docker://1.6.2.fc21",
          "kubeletVersion": "v1.0.0.1162+2e68002f3132a7",
          "kubeProxyVersion": "v1.0.0.1162+2e68002f3132a7"
        }
      }
    }
  ]
}

But without the --insecure option, the local issuer certificate is not picked up:

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option. 

My local machine does not have the crt and key values in ~/.kubernetes_vagrant_auth file. However, I do see the crt data, client cert and key info in the ~/.kube/config file.

The output from my kubernetes master node shows:
ls -la /var/run/kubernetes/*
-rw-r--r--. 1 root root 1139 Aug 12 18:34 /var/run/kubernetes/kubelet.crt
-rw-------. 1 root root 1679 Aug 12 18:34 /var/run/kubernetes/kubelet.key

Thanks for your help.

**Comment by derekwaynecarr** [comment]
You are calling the wrong endpoint to do create.

When you call

get /api/v1/pods

You are getting pods across all namespaces.

To create a pod, you must specify the namespace:

Post /api/v1/namespaces/default/pods

So in this case you are creating a pod in the default namespace.

**Comment by derekwaynecarr** [comment]
Closing issue since calling invalid endpoint and prior reply should unblock.

You can see what API calls kubectl makes by setting a log level which may help as well.

**Comment by snrism** [comment]
@derekwaynecarr thanks for the pointer. that works..
