### ISSUE TITLE
Invalid k8s service account token

### ISSUE THREAD

**Issue by fhalde** [kubernetes/kubernetes#126381]
### What happened?

The file `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` contained a malformed token of the form
```
<token> 11:11:49.782386   40364 v3.go:79] EOF
```

### What did you expect to happen?

The token should not have been malformed

### How can we reproduce it (as minimally and precisely as possible)?

Not reproducible

### Anything else we need to know?

Since the token was malformed, and since we use EKS IRSA, the AWS STS call was failing

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.0
Server Version: v1.29.4-eks-036c24b
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.4 (Plow)"
$ uname -a
Linux 5.10.219-208.866.amzn2.x86_64 #1 SMP Tue Jun 18 14:00:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by fhalde** [comment]
apologies in advance if this is not k8s related and instead has to do with https://github.com/aws/amazon-eks-pod-identity-webhook

**Comment by sftim** [comment]
/kind support

/remove-kind bug

I think `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` is specific to EKS, which this project doesn't maintain.

For help with the specifics of EKS, you could start with https://www.google.com/search?q=hwo+to+get+help+with+EKS+on+AWS

**Comment by fhalde** [comment]
thanks, i'll indeed move this to one of their channels then
