### ISSUE TITLE
Kube-addon-manager fail to execute in kubernetes v1.28.7

### ISSUE THREAD

**Issue by udhayd** [kubernetes/kubernetes#126371]
### What happened?

[kube-addons_logs.txt](https://github.com/user-attachments/files/16386497/kube-addons_logs.txt)

Hi Team , 

**Issue summary :**

kube-addon-manager doesnt work as expected in kubernetes v1.28 , though job is running in background . Its unable to perform reconcile tasks for addons when add & replace a new manifest in "/etc/kubernetes/addons" location.

I noticed , Job fails with API version compatibility issue for CronJob API version "**batch/v1beta1**" referred in the script , however actual API version of CronJob in kubernetes v1.28 cluster is "**batch/v1**" 

**Suggestion :** 

Can we first retrieve the API version of objects from existing Cluster & store those in variable and then get those called in reconcile function , this would avoid API compatibility version Issues in future.

**Error :**

```shell
+ /usr/local/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /etc/kubernetes/addons -l 'kubernetes.io/cluster-service!=true,addonman
core/v1/ConfigMap --prune-whitelist core/v1/Endpoints --prune-whitelist core/v1/Namespace --prune-whitelist core/v1/PersistentVolumeClaim --prune
--prune-whitelist core/v1/ReplicationController --prune-whitelist core/v1/Secret --prune-whitelist core/v1/Service --prune-whitelist batch/v1/Job
/DaemonSet --prune-whitelist apps/v1/Deployment --prune-whitelist apps/v1/ReplicaSet --prune-whitelist apps/v1/StatefulSet --prune-whitelist netw
+ grep -v configured
error: no matches for kind "CronJob" in version "batch/v1beta1"
``` 

### What did you expect to happen?

Reconcile Job has to perform below mentioned tasks , which doesnt perform below tasks due to Cronjob API Version error.

- Any changes made through the API will automatically revert to the configuration in /etc/kubernetes/addons/.

- If an extension is deleted via the API, it will be automatically recreated from the configuration in /etc/kubernetes/addons/.

- Removing configuration from /etc/kubernetes/addons/ will also delete the corresponding Kubernetes resources.

- Essentially, modifications can only be made by adjusting the configuration in /etc/kubernetes/addons/.

### How can we reproduce it (as minimally and precisely as possible)?

To test Kube-addons-manager in Kubernetes v1.28.7 with "addons" components Creation/Modification/Removal.

### Anything else we need to know?

NA

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.7", GitCommit:"c8dcb00be9961ec36d141d2e4103f85f92bcf291", GitTreeState:"clean", BuildDate:"2024-02-14T10:32:14Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd - 1.6.28
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico 3.38.0
</details>

**Comment by neolit123** [comment]
everything under https://github.com/kubernetes/kubernetes/tree/master/cluster/addons is legacy and unsupported. you should possibly migrate to using a different tool for addon management.

you coukd also check this, but i don't know the latest state there:
https://github.com/kubernetes-sigs/cluster-addons

/kind support
/close
