### ISSUE TITLE
View all the containers on one web page

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#12639]
I ran the below command and the output is as seen:

$ curl http://master:8080/api/v1/proxy/namespaces/default/pods/update-demo-nautilus-6lyv4/data.json
 {
 "image": "nautilus.jpg"
 }

If I use the URL in the browser: http://10.x.x.x:8080/api/v1/proxy/namespaces/default/pods/update-demo-nautilus-6lyv4/data.json
 I get:
{
 "image": "nautilus.jpg"
 }

But when I go to the IP as specified in the document --http://localhost:8001/static/index.html
I get 'Internet explorer cannot find the page'.

I have the containers running on different minion nodes. How do I get all the images on the browser that are being replicated so that I can view them than the code?

**Comment by brendandburns** [comment]
you need to run `kubectl proxy ...` that will start a local webserver that proxies all machines.

**Comment by adyanthaya17** [comment]
I did run the kubectl proxy on my node that has both master and minion, that looks like this:
$kubectl proxy --www=examples/update-demo/local/ &
Starting to serve on localhost:8001
