### ISSUE TITLE
CSP node can not add additional labels, regex is in wrong format

### ISSUE THREAD

**Issue by wangshu3000** [kubernetes/kubernetes#126453]
### What happened?

For cloud provider nodes, there are some k8s label names are reserved. Like *kubernetes.io/* and *k8s.io/*
The current regex is: `(kubernetes|k8s).io/`
This will match the dot . as any single character.
This block adding a label name like: app.k8snio/name
The regex format is incorrect, we should escape the dot in regex so that it can match the dot as a string.

### What did you expect to happen?

Can add additional label with name like: app.k8snio/name

### How can we reproduce it (as minimally and precisely as possible)?

Configure AdditionalLabels in the instanceMeta to add additional label name with app.k8snio/name. 

### Kubernetes version

<details>

Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
Which Kubernetes component has the bug @wangshu3000 ? (eg: kubelet)

Can you explain how to reproduce the problem?

**Comment by BenTheElder** [comment]
It's the node controller in the k8s.io/cloud-provider/controllers shared library

https://github.com/kubernetes/kubernetes/blob/974f3d3d8ff6bfb33a375f7207c34c69b3e8b932/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L553

Though I really don't think cloud providers should be setting node labels like "`app.k8snio/name`", this is technically incorrect. This restriction is only applied to labels the cloud provider controller binary running this controller would attempt to add itself.

**Comment by elmiko** [comment]
just noticed this after our SIG meeting today, cc @bridgetkromhout

**Comment by elmiko** [comment]
@wangshu3000 please go ahead and raise a PR, thanks for reporting this =)

**Comment by sftim** [comment]
When fixing this, consider if there are any labels that cloud provider integration might legitimately set.

For example: [`node.kubernetes.io/instance-type`](https://kubernetes.io/docs/reference/labels-annotations-taints/#nodekubernetesioinstance-type) (usually set by the kubelet) or [`topology.kubernetes.io/zone`](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesioregion) (documented as being set by cloud provider integration code).

Some labels are OK to set; we could allowlist `topology.kubernetes.io/zone` and ``topology.kubernetes.io/region` explicitly. When rejecting some others, maybe setting a Condition on the Node (`ConfigurationInvalid` perhaps) would help surface what's not right. Not sure.

---

Making the simple fix is also fine by me.
