### ISSUE TITLE
update year-old coreDNS images

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#126443]
/kind cleanup
/sig cluster-lifecycle testing

kubeadm and kube-up.sh are still using coreDNS v1.11.1, which means most of our CI is as well
https://github.com/kubernetes/kubernetes/blob/e8588e6493222ab623f794ca4aeb5261f86ef3d3/build/dependencies.yaml#L44

coreDNS has had some release struggles (e.g. https://github.com/coredns/coredns/issues/6661), but there is a more recent release tag available, we should get this into registry.k8s.io (unclear how we've been doing this? asking in slack ...), and then update the references in this repo.

It's a bit late in the 1.31 cycle unfortunately, but I'm concerned about the missing CVE and bug fixes after one year.

**Comment by BenTheElder** [comment]
Filed https://github.com/kubernetes/kubernetes/pull/126449 but I'm not sure if we need https://github.com/coredns/corefile-migration/issues/81 first.

**Comment by BenTheElder** [comment]
Yes, we need https://github.com/coredns/corefile-migration/pull/82 first

**Comment by BenTheElder** [comment]
/lifecycle active

The plan for now is to merge this when 1.32 merges open up / when 1.31 is released I'll file a cherry pick to 1.31 targeting 1.31.1

With some luck we'll have this released by 1.31.1 in September ... 🤞

**Comment by BenTheElder** [comment]
We should probably actually backport this to all supported branches? I've been focused on trying to get it into the next release, and then to backporting to 1.31.1 since we just missed 1.31.0, but this should be a fixes-only patch upgrade without deprecations.

Kubernetes 1.28 is on coreDNS 1.10.1 though, and that probably needs more investigation
https://github.com/kubernetes/kubernetes/blob/8ee77cb2c7cf575b3ccb6dc55b41b49ecf1ae8e3/build/dependencies.yaml#L41-L42

Kubernetes 1.29 forward are on coreDNS 1.11.1 and should definitely receive 1.11.3 backport IMHO, I'll plan to file the cherry pick to 1.29, 1.30, 1.31 at least.
https://github.com/kubernetes/kubernetes/blob/138e2d568af302b593b771f8fe076d2868464707/build/dependencies.yaml#L43-L44

**Comment by dims** [comment]
@BenTheElder yes we should backport ... +1 to after we land it once master reopens for sure.

**Comment by BenTheElder** [comment]
Do we typically backport minor version bumps though? (Re: v1.28 is on 1.10.x still)

**Comment by neolit123** [comment]
> Do we typically backport minor version bumps though? (Re: v1.28 is on 1.10.x still)

i don't think there is a written policy but normally we don't for etcd. if there are plugin changes in coredns 1.11 we shouldn't break the user in a k8s patch.

**Comment by pacoxu** [comment]
https://github.com/coredns/coredns/releases/tag/v1.11.0

> This release introduces the following backward incompatible changes:
> 
> - In the kubernetes plugin, we have dropped support for watching Endpoint and Endpointslice v1beta, since all supported K8s versions now use Endpointslice.
> - The bufsize plugin changed its default size limit value to 1232
> - Some changes to forward plugin metrics.

A quick look of the v1.11 release notes, the upgrade will not break users.

cc @chrisohaver @yongtang https://github.com/coredns/coredns/issues/6102

**Comment by BenTheElder** [comment]
This is merged and will be in 1.32.0

Cherry picks are going out now: 
- 1.31.1 (hopefully): https://github.com/kubernetes/kubernetes/pull/126796
- 1.30.5 (hopefully): Working on it, vendor changes not picking cleanly
- 1.29.9 (hopefully): TODO
- 1.28.13 (hopefully): TODO

**Comment by BenTheElder** [comment]
Since 1.30 didn't cherry-pick cleanly, looking for review before doing the same to 1.29 and 1.28.

1.31.1 cherry-picked cleanly.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/126797#issuecomment-2299070457 we need to decide how to handle the other libraries being transitively upddated before backporting it further.

**Comment by BenTheElder** [comment]
We wound up having some more changes made to minimize dependency issues, 1.30 is done now but 1.29 and 1.28 remain.
