### ISSUE TITLE
Bad cluster initialization on AWS when using IAM roles 

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#12649]
When Kubernetes is not given with a AWS_S3_BUCKET it calculates its value with a hash on the aws access key and the user on the system.

When using IAM roles to allow the machine to raise the Kubernetes cluster, the access key is blank.
So Kubernetes actually makes a hash on blank and the user name which is probably ubuntu or ec2-user.
The problem with this is that aws s3 bucket names have to be unique across all aws and that means that all people using IAM roles for permissions on the machine which is creating the cluster will get the same bucket name, which is not allowed to be created by AWS.

I had this problem and took some time to figure it out.
1. Is my analysis correct? 
2. If so, maybe adding a random factor to the hash like current epoch time could help creating unique bucket names.

I am willing to make the PR if you see this is necessary.

**Comment by brendandburns** [comment]
Seems possible.  The goal in having the hash was to make the bucket consistent across different cluster turn-ups, so that each user would create N different buckets for each cluster they turned up.

But I'd be happy to see a PR that tested for empty string, and then fell back to just using basic randomness.

Thanks!
--brendan

**Comment by justinsb** [comment]
@erez-rabih That does indeed sound correct.  Thanks for finding this.

Randomness is a reasonable fallback.  Another option might be to fall-back to `aws iam get-user`.  Based on http://stackoverflow.com/questions/10197784/how-can-i-deduce-the-aws-account-id-from-available-basicawscredentials, I think this bash command gives you the AWS account id: 
`aws iam get-user --output text --query User.Arn | awk -F: '/arn:aws:/{print $5}'`

I think we should keep the existing behaviour as primary, even though arguably something based on iam get-user would be better.

**Comment by erez-rabih** [comment]
@justinsb That snippet for getting the account ID is not working for me I'm getting:
```
A client error (ValidationError) occurred when calling the GetUser operation: Must specify userName when calling with non-User credentials
```
Also I made a short lookup and couldn't find any official API returning the account ID

I agree that we better have some consistency between cluster creations, maybe we can find a safer way to achieve that.

**Comment by justinsb** [comment]
We're not going to be making further changes to kube-up, and I don't believe this is a problem in kops (which is the tool I recommend to use instead).  Closing.
