### ISSUE TITLE
scheduler: Add ctx param to PodEligibleToPreemptOthers

### ISSUE THREAD

**Issue by googs1025** [kubernetes/kubernetes#126464]
### What would you like to be added?

In the scheduling framework we provide preemption.Interface for third-party implementations.

When I was working on this [issue](https://github.com/kubernetes-sigs/scheduler-plugins/issues/743), I found that this method `PodEligibleToPreemptOthers` needs to add context param.

```go
// methods might have different behavior compared with the default preemption.
type Interface interface {
	...
	// PodEligibleToPreemptOthers returns one bool and one string. The bool indicates whether this pod should be considered for
	// preempting other pods or not. The string includes the reason if this pod isn't eligible.
	PodEligibleToPreemptOthers(pod *v1.Pod, nominatedNodeStatus *framework.Status) (bool, string)
        ...	
}

```
example: 
https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/capacityscheduling/capacity_scheduling.go#L402
https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/preemptiontoleration/preemption_toleration.go#L326

### context parameter

The primary motivation is to be able to use contextual values, such as https://github.com/kubernetes/kubernetes/pull/116884 and https://github.com/kubernetes/kubernetes/pull/126113

**Comment by googs1025** [comment]
If agree to this proposal, I will take this :)

**Comment by googs1025** [comment]
When this `PodEligibleToPreemptOthers` method is to be implemented by a third party, context information may be required. We should pass it in

**Comment by sanposhiho** [comment]
> When I was working on this https://github.com/kubernetes-sigs/scheduler-plugins/issues/743, I found that this method PodEligibleToPreemptOthers needs to add context param.

We don't log anything in `PodEligibleToPreemptOthers`, right? Why do we need ctx?
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L239-L264

**Comment by googs1025** [comment]
The scheduler-plugins project has implementation. 

example:
https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/capacityscheduling/capacity_scheduling.go#L402
https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/preemptiontoleration/preemption_toleration.go#L326

**Comment by googs1025** [comment]
> > When I was working on this [kubernetes-sigs/scheduler-plugins#743](https://github.com/kubernetes-sigs/scheduler-plugins/issues/743), I found that this method PodEligibleToPreemptOthers needs to add context param.
> 
> We don't log anything in `PodEligibleToPreemptOthers`, right? Why do we need ctx? https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L239-L264

When a third party implements the PodEligibleToPreemptOthers method, it is likely to require a log or ctx, so I think it is reasonable to pass it in. Because the logic of PodEligibleToPreemptOthers may be much more complicated than the default one.

**Comment by sanposhiho** [comment]
Okay, I overlooked this issue https://github.com/kubernetes-sigs/scheduler-plugins/issues/743 you mentioned is the one on sched-plugin repo.
I don't have any concern adding `ctx` in `PodEligibleToPreemptOthers`.

**Comment by googs1025** [comment]
This PR https://github.com/kubernetes/kubernetes/pull/126465 has been completed and the issue is closed. If having any questions, feel free to open one. 
/close
