### ISSUE TITLE
kubelet would happily schedule a pod with `spec.hostUsers: false` even if `UserNamespacesSupport` is not set for kubelet

### ISSUE THREAD

**Issue by frezbo** [kubernetes/kubernetes#126484]
### What happened?

As per https://github.com/kubernetes/kubernetes/pull/123216/files#diff-ed935ef85e4cd93302c07762fbc4314164759fb618bd661a3ac17ca782dde836R397 I would have expected kubelet to disallow a pod that has `spec.hostUsers: false` set when the `UserNamespacesSupport` is not enabled for the kubelet.

From testing kubelet and api server would happily accept a pod having the spec and gives the user a false sense of security.

From my further testing if the `UserNamespacesSupport` feature gate is set for api server and not set for kubelet the pod fails to be scheduled.

### What did you expect to happen?

Expected to see the error message below:

```text
Failed to create pod sandbox: the feature gate "UserNamespacesSupport" is disabled: can't set spec.HostUsers
```

when `UserNamespacesSupport` is not enabled at all for any component of kubernetes

### How can we reproduce it (as minimally and precisely as possible)?

Schedule a pod on a standard k8s cluster that has the `UserNamespacesSupport` feature gate not set for both kubelet and kube-apiserver

Sample pod spec used:

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  hostUsers: false
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

```

### Kubernetes version

<details>

```console
$ kubectl version
❯ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0-beta.0
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Talos"
ID=talos
VERSION_ID=v1.8.0-alpha.1-40-g96492c097
PRETTY_NAME="Talos (v1.8.0-alpha.1-40-g96492c097)"
HOME_URL="https://www.talos.dev/"
BUG_REPORT_URL="https://github.com/siderolabs/talos/issues"
VENDOR_NAME="Sidero Labs"
VENDOR_URL="https://www.siderolabs.com/"
$ uname -a
Linux version 6.6.43-talos (@buildkitsandbox) (gcc (GCC) 13.3.0, GNU ld (GNU Binutils) 2.42) #1 SMP Mon Jul 29 17:04:08 UTC 2024
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
```
# runc --version
runc version v1.2.0-rc.2
commit: f2d2ee5e45af3c9b38dfd639ac92f43c3055ce4e
spec: 1.2.0
go: go1.22.5
libseccomp: 2.5.5
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by kannon92** [comment]
@frezbo Thank you for reporting this.

cc @haircommander

**Comment by haircommander** [comment]
It was my understanding we should expect homogeneous feature gates among KAS and kubelet for a cluster. Obviously we're not doing anything to enforce this, but is this expectation wrong? cc @deads2k and @liggitt whom i've chatted about this with

**Comment by kannon92** [comment]
> Schedule a pod on a standard k8s cluster that has the UserNamespacesSupport feature gate not set for both kubelet and kube-apiserver

The bug is if the feature gate is not set, we don't block using that field I think.

**Comment by frezbo** [comment]
> > Schedule a pod on a standard k8s cluster that has the UserNamespacesSupport feature gate not set for both kubelet and kube-apiserver
> 
> The bug is if the feature gate is not set, we don't block using that field I think.

Correct, this would otherwise might give a false sense of security to an end user

**Comment by kannon92** [comment]
@frezbo do you want to try your hand at a fix?

**Comment by kannon92** [comment]
Looks like we are probably hitting this case:

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/pod/util.go#L632

**Comment by frezbo** [comment]
> Looks like we are probably hitting this case:
> 
> https://github.com/kubernetes/kubernetes/blob/master/pkg/api/pod/util.go#L632

is `hostUsers` a field of `securityContext` , the docs here shows it as under `spec` https://kubernetes.io/docs/tasks/configure-pod-container/user-namespaces/#create-pod

**Comment by frezbo** [comment]
> > Looks like we are probably hitting this case:
> > https://github.com/kubernetes/kubernetes/blob/master/pkg/api/pod/util.go#L632
> 
> is `hostUsers` a field of `securityContext` , the docs here shows it as under `spec` https://kubernetes.io/docs/tasks/configure-pod-container/user-namespaces/#create-pod

never mind, read the code wrong

**Comment by frezbo** [comment]
> @frezbo do you want to try your hand at a fix?

I'm lost trying to follow the code

**Comment by haircommander** [comment]
I opened https://github.com/kubernetes/kubernetes/pull/126560, let's see how folks think about it

**Comment by haircommander** [comment]
I think we probably can't do this https://github.com/kubernetes/kubernetes/pull/126560#discussion_r1705793252
this is in part why the UserNamespacesPodSecurityStandards exists: the KAS cannot be sure older versions of the kubelet support the feature gate and won't fail to create a user namespace if asked. When relying on user namespaces for security isolation, a cluster admin should ensure kubelets are new enough and can support the field

/close

**Comment by frezbo** [comment]
> I think we probably can't do this [#126560 (comment)](https://github.com/kubernetes/kubernetes/pull/126560#discussion_r1705793252) this is in part why the UserNamespacesPodSecurityStandards exists: the KAS cannot be sure older versions of the kubelet support the feature gate and won't fail to create a user namespace if asked. When relying on user namespaces for security isolation, a cluster admin should ensure kubelets are new enough and can support the field
> 
> /close

i understand the code path, but the issue is that if just kubelet has the feature gate set, the pod gets scheduled, the validation is only done if both kubelet and apiserver has the feature flag set (since api server does the vlaition and drops the field), which is very easy to miss

**Comment by haircommander** [comment]
/reopen

potentially we could do https://github.com/kubernetes/kubernetes/pull/126874 instead

**Comment by haircommander** [comment]
after some testing, I see what you're talking about: your problem is when KAS has it disabled, the pod is accepted and hostUsers is filtered out. that's true and apparently needs to be the case (see https://github.com/kubernetes/kubernetes/pull/126560#discussion_r1705793252) I was worried the situation you were describing was kubelet had it off, but KAS had it on and kubelet created the pod. that's not true, we do in fact hit https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/userns/userns_manager.go#L402 

/close
