### ISSUE TITLE
In-tree storage plugin removal still alpha (?)

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#126406]
**Problem:**
According to the [docs](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/),

- `InTreePluginAWSUnregister` (alpha)
- `InTreePluginAzureDiskUnregister` (alpha)
- `InTreePluginAzureFileUnregister` (alpha)
- `InTreePluginGCEUnregister` (alpha)
- `InTreePluginOpenStackUnregister` (alpha)
- `InTreePluginPortworxUnregister` (alpha)
- `InTreePluginvSphereUnregister` (alpha)

are alpha features. Is that right? Given we've blogged about completing the cloud provider migration I'd expect these to at least be beta, if not GA.

**Proposed Solution:**
- Find out what's wrong: stale docs? Missed work updating feature gates? Something else?
- Fix those things.

/sig storage

See https://kubernetes.slack.com/archives/C718BPBQ8/p1702577018709349 for more context.
I opened a related issue, https://github.com/kubernetes/kubernetes/issues/126434

**Comment by carlory** [comment]
https://github.com/kubernetes/website/pull/47241 marked those feature gates as removed in 1.31. I don't know why the feature-gate page has not been updated yet. What's wrong with my changes?

The above feature gates don't take effect in earlier versions. In csi implementation meeting, we agreed to remove them instead of deprecating or promoting them. 

- https://github.com/kubernetes/kubernetes/pull/124815
- https://github.com/kubernetes/kubernetes/pull/124023
- https://docs.google.com/document/d/1_hvq3nleqQEYatH9V_Gfep39jMzaFJRSN2ioA0PFq-Q/edit#heading=h.k3x483vz909y

cc @msau42 @sftim

**Comment by carlory** [comment]
InTreePluginPortworxUnregister is still in alpha (is it expected? @msau42 @jsafrane should promote it to beta after its migration is GA?). the Portworx is the last one that needs to complete csi migration. In 1.31, we turn on its migration feature-gate. https://github.com/kubernetes/kubernetes/pull/125016

**Comment by jsafrane** [comment]
IIRC `InTreePluginXYZUnregister` should be disabled for at least 3 releases after XYZ CSI migration is GA, to make sure the volume plugin is still registered in KCM, so it can attach/detach in-tree volumes for nodes that are 3 versions older than KCM (the max. allowed version skew).

Having said that, Portworx volumes are not attachable and A/D controller in KCM ignores them. There is a good chance that we can graduate InTreePluginPortworxUnregister together with the CSI migration itself. Please triple check the code where the feature gate is used.

**Comment by sftim** [comment]
Can we at least promote these feature gates from alpha to beta?

**Comment by sftim** [comment]
> [kubernetes/website#47241](https://github.com/kubernetes/website/pull/47241) marked those feature gates as removed in 1.31. I don't know why the feature-gate page has not been updated yet. What's wrong with my changes?

We haven't yet released Kubernetes v1.31

It's unusual to remove alpha feature gates. We should instead graduate them to stable and lock them to default, then remove them in a later release. I'll file a bug.

**Comment by sftim** [comment]
/retitle In-tree storage plugin removal still alpha (?)

**Comment by jsafrane** [comment]
> It's unusual to remove alpha feature gates move a feature gate from alpha, enabled by default directly to components don't even recognize this as a feature gate. 

They're not enabled by default in 1.30, they're disabled there.

I think [the deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecation) allows us to drop alpha feature gates without deprecation / warnings:

> Rule #9: Feature gates must be deprecated when the corresponding feature they control transitions a lifecycle stage as follows. Feature gates must function for no less than:
> * Alpha feature to EOL: 0 releases

**Comment by sftim** [comment]
OK, so, next question: is the behaviour behind those gates now off-by-default (implying,  they really alpha?)

If Kubernetes v1.30 does _not_ enable the _behavior_ implied by `InTreePluginPortworxUnregister`, `InTreePluginAWSUnregister` etc - we're all good. If the behavior was enabled and we're now yanking it, it's probably allowed but we need really good comms.

When I ask about behavior, this is not asking about whether the boolean value for `InTreePluginAWSUnregister` was reported as true. It's about whether, for each feature gate, the in-tree plugin _was_ registered and active by default  in v1.30 - and how we'll handle the transition to a release where they are not.

- Maybe the problem was that we stopped registering the plugins, but didn't graduate the feature gate to beta or enable it by default (in which case, I presume that setting the feature gate explicitly to false was broken but nobody reported it?)
- Maybe the problem was that the code did change but the SIG missed updating the docs?

If it's more one of those scenarios, see https://github.com/kubernetes/kubernetes/issues/126434

This issue was about my suspicion that we had some features that had become enabled by default and were removing them without the process. I still think that's true, but there are philosophical questions as well. Philosophy? Well, if we've removed the code for an in-tree plugin, what does “not registering” it mean? That kind of semantic quibbling.

**Comment by jsafrane** [comment]
The feature gates (except for InTreePluginPortworxUnregister) made KCM+kubelet not to register in-tree volume plugins. But the in-tree volume plugins were removed, so there is nothing to register...

We should have removed the feature gates when removing the in-tree volume plugins, but we forgot to do so. Now we have gates that for most part do not change Kubernetes behavior when flipping them on/off. In my personal opinion, removing them without graduation is fine.

**Comment by sftim** [comment]
Let's do good comms about why this unusual removal is OK.

**Comment by jsafrane** [comment]
Would a release note be enough?

**Comment by sftim** [comment]
I would also make sure to mention this in the release announcement blog article. Failure to pay attention here could break your cluster (only if you don't test your changes, but we should be nice to users rather than assuming they cover for our mini shortcoming).

**Comment by sftim** [comment]
If we have capacity, also make a PR against _main_ that explains how these gates have no effect in v1.30 (assuming that's right).

**Comment by jsafrane** [comment]
Adding a note to release blog: https://github.com/kubernetes/website/pull/47281/files#r1703832864

**Comment by sftim** [comment]
Maybe we can close this issue now?

**Comment by jsafrane** [comment]
ack
/close
