### ISSUE TITLE
Kubernetes Cert rotation

### ISSUE THREAD

**Issue by debankurchatterjee** [kubernetes/kubernetes#126430]
### What happened?

Does the Kubernetes-managed CA also get renewed during Kubernetes Certs rotation or on Kubernetes upgrade?

### What did you expect to happen?

If we are using the same VM for 10 years and keep patching the Kubernetes version then the Kubernetes managed CA should also get renewed.

but as per the Kubernetes code base  
https://github.com/kubernetes/kubernetes/blob/a2106b5f73fe9352f7bc0520788855d57fc301e1/cmd/kubeadm/app/phases/certs/renewal/manager.go#L114
it says renewal of CA is not managed.

In such case how we will renew the CA ?

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Anything else we need to know?

NA

### Kubernetes version

1.27.2

### Cloud provider

NA

### OS version

Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
the CA is not renewed. you must renew it manually. the process of auto-renewing the CA is out of scope for kubeadm and there are no plans for this feature.

https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/

/close
/kind feature
/sig cluster-lifecycle

**Comment by debankurchatterjee** [comment]
Is there any documented process to renew the Kubernetes-provided CA manually? if we intend to use the Cluster for 10+ years

**Comment by neolit123** [comment]
> Is there any documented process to renew the Kubernetes-provided CA manually? if we intend to use the Cluster for 10+ years

i posted the link. check above.
