### ISSUE TITLE
Allow custom EXTRA_DOCKER_OPTS with KUBE_ENABLE_INSECURE_REGISTRY

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#12647]
I'm working with kubernetes 1.0.1 on AWS.

Currently, the way to specify custom docker options for the docker daemon on the minion machine is to set the EXTRA_DOCKER_OPTS environment variable when raising the cluster.
The problem is that if I also set the KUBE_ENABLE_INSECURE_REGISTRY environment variable it overrides the EXTRA_DOCKER_OPTS here:
https://github.com/kubernetes/kubernetes/blob/v1.0.1/cluster/aws/config-default.sh#L70

I need the custom options in order to set `--default-ulimit nofile` on the docker daemon.

Does it make sense to only append to EXTRA_DOCKER_OPTS when KUBE_ENABLE_INSECURE_REGISTRY is set instead of override? This way users will be able to set whatever custom docker options they would like in conjunction with KUBE_ENABLE_INSECURE_REGISTRY.

**Comment by brendandburns** [comment]
That seems like a bug, we should append, not overwrite.  Send a PR?

**Comment by erez-rabih** [comment]
Just noticed that we're overriding the options in another place which has nothing with KUBE_ENABLE_INSECURE_REGISTRY:
https://github.com/kubernetes/kubernetes/blob/v1.0.1/cluster/vagrant/config-default.sh#L74

I think about adding `EXTRA_DOCKER_OPTS="${EXTRA_DOCKER_OPTS:-}"` to all of the default configurations (gce, aws, vagrant) and then append as needed.

**Comment by justinsb** [comment]
@erez-rabih that is indeed a bug, thanks for spotting.  Can you send a PR?  If not I can put one together.

**Comment by roberthbailey** [comment]
Tagging 1.2 since there is an outstanding PR that will fix this. Leaving at P2 since that PR won't block cutting a release.
