### ISSUE TITLE
Request for release timeline of "Resize CPU and Memory Resources assigned to Containers".

### ISSUE THREAD

**Issue by beggginner** [kubernetes/kubernetes#126433]
We are currently exploring the resizePolicy feature for use in our production environment. As noted in the [official documentation](https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/), this feature is currently available in Kubernetes 1.27 alpha version.

Could you provide an estimated timeline for when the resizePolicy feature will be included in a stable major release of Kubernetes? This information would greatly assist us in our planning and deployment strategies.

**Comment by neolit123** [comment]
you can ask on #sig-node at k8s slack for any feature releated questions.
