### ISSUE TITLE
How to dynamically add machine into a kubernetes cluster

### ISSUE THREAD

**Issue by shenshouer** [kubernetes/kubernetes#12642]
How to dynamically add machine into a kubernetes cluster when the cluster has started?

**Comment by roberthbailey** [comment]
Any kubelet that has the correct flags will join the cluster. The kubelet needs to know where the apiserver is and have valid client credentials to register itself into the cluster. In general, you can accomplish this by cloning an existing machine's configuration. 

On GCE / GKE, you can increase the size of the managed instance group that backs the cluster and the new VMs will be automatically added to the cluster.

**Comment by shenshouer** [comment]
thanks! I will try it!

**Comment by mbforbes** [comment]
@shenshouer I'm going to assume @roberthbailey's comment answered your question and close this issue. But please feel free to re-open or open a more specific issue if you run into problems!
