### ISSUE TITLE
Failure cluster [47ae877c...] e2e-ci-kubernetes-e2e-al2023-aws-serial-canary issues

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#126505]
##### Error text:
```
[FAILED] Key "attachdetach_controller_forced_detaches" not found in A/D Controller metrics
In [It] at: k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:436 @ 07/18/24 00:34:39.158

There were additional failures detected after the initial failure. These are visible in the timeline

```
#### Recent failures:
[7/31/2024, 8:06:51 PM e2e-ci-kubernetes-e2e-al2023-aws-serial-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-al2023-aws-serial-canary/1818800431434829824)
[7/31/2024, 2:06:51 PM e2e-ci-kubernetes-e2e-al2023-aws-serial-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-al2023-aws-serial-canary/1818709833696677888)
[7/31/2024, 10:39:42 AM e2e-ci-kubernetes-e2e-al2023-aws-serial-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-al2023-aws-serial-canary/1818657698065944576)
[7/23/2024, 2:07:11 AM e2e-ci-kubernetes-e2e-al2023-aws-serial-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-al2023-aws-serial-canary/1815629619794022400)
[7/22/2024, 8:07:10 PM e2e-ci-kubernetes-e2e-al2023-aws-serial-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-al2023-aws-serial-canary/1815539020898242560)

/kind failing-test

/sig storage

**Comment by dims** [comment]
3 tests seem to be failing related to sig-storage: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-al2023-aws-serial-canary/1818891029567246336

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/aa9ee93a-b943-46df-8596-10df7d704eb7">

**Comment by dims** [comment]
Also see https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-al2023-aws-disruptive-canary/1818903864221372416 there are a few there as well

**Comment by AndrewSirenko** [comment]
x-ref  #126345

Looks like the only jobs running volume metrics tests are e2e-ci-kubernetes-e2e-cos-gce-serial-canary &e2e-ci-kubernetes-e2e-al2023-aws-serial-canary... In that PR we are trying to make those tests run in for kind clusters and gce-serial. 

Therefore [sig-storage] [Serial] Volume metrics PVC should create metrics for total number of volumes in A/D Controller has likely been broken for a while.

Looks like any metric for `attachdetach_controller_forced_detaches` isn't being emitted in that test at all? I dumped the metrics and only saw `attachdetach_controller_total_volumes` 😅

May take some time to get it working.

**Comment by torredil** [comment]
@AndrewSirenko Thanks for dumping the metrics, good call.

Could we be dealing with a logical error in the test? I would expect that the only requirement for passing a `should create metrics for total number of volumes` test to be that the `attachdetach_controller_total_volumes` metric is emitted (which it is, as per the dump)

It's odd to also expect `attachdetach_controller_forced_detaches` in `should create metrics for total number of volumes`.

Ideally, this validation:

https://github.com/kubernetes/kubernetes/blob/f8d5b2074c9b3a1629ef085b9e17a5370f393732/test/e2e/storage/volume_metrics.go#L434-L440

should be part of a separate `should create metrics for forced detaches` test.

**Comment by dims** [comment]
cc @xing-yang

**Comment by AndrewSirenko** [comment]
> It's odd to also expect attachdetach_controller_forced_detaches in should create metrics for total number of volumes.

I don't disagree with you, but I think the short-term question we should be trying to solve next is why the forced detach metric is not present in this test, and if that was a regression. 

If I were consuming these metrics, I would expect that there is an `attachdetach_controller_forced_detaches` metric emitted, even if the value is 0, if any volumes were attached/detached for a particular driver. Right? (Perhaps metric only emitted on first detach?) 

Perhaps an extra serial test is worth putting that check in a separate test.
