### ISSUE TITLE
Unable to access control plane after Kubernetes worker node reboot

### ISSUE THREAD

**Issue by uaysk** [kubernetes/kubernetes#126598]
### What happened?

After running the kubectl drain master-1 --ignore-daemonsets command, I rebooted the node. (The node's name is master-1, but it's actually a worker node.) After rebooting, I ran kubectl describe node master-1 and was able to confirm the following.

```
NetworkUnavailable False Thu, 08 Aug 2024 13:03:33 +0900 Thu, 08 Aug 2024 13:03:33 +0900 CalicoIsUp Calico is running on this node
MemoryPressure Unknown Fri, 09 Aug 2024 00:24:51 +0900 Fri, 09 Aug 2024 00:28:34 +0900 NodeStatusUnknown Kubelet stopped posting node status. DiskPressure Unknown Fri, 09 Aug 2024 00:24:51 +0900 Fri, 09 Aug 2024 00:28:34 +0900 NodeStatusUnknown Kubelet stopped posting node status.
 PIDPressure Unknown Fri, 09 Aug 2024 00:24:51 +0900 Fri, 09 Aug 2024 00:28:34 +0900 NodeStatusUnknown Kubelet stopped posting node status.
 Ready Unknown Fri, 09 Aug 2024 00:24:51 +0900 Fri, 09 Aug 2024 00:28:34 +0900 NodeStatusUnknown Kubelet stopped posting node status.

```
After that, I tried sudo service kubelet restart, but the status above did not change, so I ran journalctl -xeu kubelet and was able to see the following log.

`Aug 09 00:53:43 master-1 kubelet[4037]: E0809 00:53:43.977693 4037 event.go:368] "Unable to write event (may retry after sleeping)" err="Post \"https://172.30.1.25:6443/api/v1/namespaces/default/events\": dial tc p 172.30.1.25:6443: connect: connection refused" event="&Event{ObjectMeta:{master-1.17e9cb4b4ae2670b default 0 0001-01-01 00:00:00 +0000 UTC <> Aug 09 00:53:44 master-1 kubelet[4037]: W0809 00:53:44.689016 4037 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Get "https://172.30.1.25:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.30.1.2 5:6443: connect: connection refused Aug 09 00:53:44 master-1 kubelet[4037]: E0809 00:53:44.689188 4037 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://172.30.1.25:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.30.1.25:6443: connect: connection refused Aug 09 00:53:46 master-1 kubelet[4037]: E0809 00:53:46.719516 4037 eviction_manager.go:282] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"master-1\" not found" Aug 09 00:53:49 master-1 kubelet[4037]: E0809 00:53:49.431097 4037 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://172.30.1.25:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/master-1?timeout=10s\": dial tcp 172.30.1.25:6443: connect: connection refused" interval="7s" Aug 09 00:53:49 master- 1 kubelet[4037]: I0809 00:53:49.796996 4037 kubelet_node_status.go:73] "Attempting to register node" node="master-1" Aug 09 00:53:49 master-1 kubelet[4037]: E0809 00:53:49.800718 4037 kubelet_node_status.go:96] "Unable to register node with API server" err="Post \"https://172.30.1.25:6443/api/v1/nodes\": dial tcp 172.30.1.25:6443: connect: connection refused" node="master-1"
`
The strange thing is that when I ran curl https://172.30.1.25:6443 --insecure on other worker nodes and the master node, I got a 403 error, but when I ran the above command on the node that had been rebooted, I got the following output.

`curl: (7) Failed to connect to 172.30.1.25 port 6443 after 0 ms: Couldn't connect to server`

The actual master node ip is 172.30.1.4, and 172.30.1.25 is an address exposed through HAProxy and Keepalived on a separate load balancer node. Could this be the issue?
Or did I do something wrong during the node reboot process?

### What did you expect to happen?

When this happened previously, the solution was to reset the entire cluster.

### How can we reproduce it (as minimally and precisely as possible)?

sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --upload-certs --control-plane-endpoint=172.30.1.25:6443
After running the above command, add the worker node using the kubeadm join command. After installing calico and metallb, the above-described thing happened.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
```

</details>

### Cloud provider

<details>
self hosted ubuntu 24 server
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
$ uname -a
Linux master-1 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd containerd.io 1.7.19
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico v3.28.1
</details>

**Comment by neolit123** [comment]
> The strange thing is that when I ran curl https://172.30.1.25:6443/ --insecure on other worker nodes and the master node, I got a 403 error, but when I ran the above command on the node that had been rebooted, I got the following output.

marking as support. please try asking on the support forums.
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
