### ISSUE TITLE
Protect from Unauthorized access of Volume

### ISSUE THREAD

**Issue by kislaynigam** [kubernetes/kubernetes#126591]
Can an n authorized user has access rights to perform update or patch operations on VolumeSnapshotContents, which is a cluster-level resource? If Yes then Who can provide these rights only to trusted users or applications, like backup vendors. Users apart from such authorized ones will never be allowed to modify the volume mode of a PVC when it is being created from a VolumeSnapshot.
To convert the volume Mode what an authorized user must do ?
What are the steps that must be followed by the user.?

All of these are very required for me in context of my project requirement. Anyone who wants any details are welcomed but must be helpful and relevant to the discussion.
/sig storage

**Comment by niranjandarshann** [comment]
@kislaynigam  Thank you for your contribution.  I must say 
Yes an authorized user can access right to perform update or patch operation on VolumeSnapshot Content  Which is the cluster level resources.

**Comment by niranjandarshann** [comment]
ClusterAdministrator is responsible to provide these rights to the trusted and backup vendors.

**Comment by kislaynigam** [comment]
@niranjandarshann  Thank you for your response Can you help me out for implementing it and letting me know more about it? As i am eager to get the response positively in Yes that i get . So can you elaborate more about it?

**Comment by niranjandarshann** [comment]
@kislaynigam  sure i will try to give my best  so that you may get the response on it.

**Comment by kislaynigam** [comment]
@niranjandarshann  But in above comment you stated  that its is possible. I am eager to know How authorized user can modify the volume mode? How it is possible?
Help me for that too @niranjandarshann

**Comment by niranjandarshann** [comment]
Sure @kislaynigam You should follow the folling steps to convert the volume Mode so as an authorized user must do:
. Identify the VolumeSnapshot that is to be used as the data source for a newly created PVC in namespace that you were given.
. Identify the VolumeSnapshotContent bound it to the  above VolumeSnapshot

The command that will help you to describe volumesnapshot with namespace are

`kubectl describe volumesnapshot -n <namespace> <name>`

**Comment by niranjandarshann** [comment]
we must add annotation snapshot.storage.kubernetes.io/allow-volume-mode-change:"true" to the above volumesnapshotcontent.

**Comment by niranjandarshann** [comment]
Like as 
```
kind:VolumeSnapshotContent
metadata:
    annotations:
       -snapshot.storage.kubernetes.io/allow-volume-mode-change:"true"
....
```

**Comment by kislaynigam** [comment]
@niranjandarshann   Thank you for your response but for me i have predefined volumesnapshot i thing you given solution for new volumeasnapshot.

**Comment by niranjandarshann** [comment]
@kislaynigam it was not mentioned above in the description of the problem that is is pre provisoned thats why i responded for the new one.

**Comment by niranjandarshann** [comment]
@kislaynigam  no need to worries we have to follow all the above mentioned 3 steps and one more steps. add  `sourceVolumeMode` inside `spec` field  of `volumesnapshotcontent` yaml file. either you may add `Filesystem` or `Block` the mode of the volume from which the snapshot is taken.

**Comment by kislaynigam** [comment]
@niranjandarshann  let me to try this first.

**Comment by kislaynigam** [comment]
@niranjandarshann  Thanks for your help It worked for me. Your Contribution and response helped me alot. 
Seen your dedication helped me alot. thanks again. Means alot for me.

**Comment by niranjandarshann** [comment]
Thank you @kislaynigam for ack. Its my pleasure to help you out and in OSS we work in collaborative manner for each one. Feel free to raise any other concern if you feel to be addressed , the bug the feature request.

**Comment by niranjandarshann** [comment]
You may close the issue marking as completed. 
Thank you and keep Contributing.
