### ISSUE TITLE
Using runtime scheme.Convert for Validating Admission Policy version conversion results in error

### ISSUE THREAD

**Issue by JaydipGabani** [kubernetes/kubernetes#126582]
### What happened?

Converting `v1beta1.ValidatingAdmissionPolicy` to `v1.ValidatingAdmissionPolicy` and `v1beta1.ValidatingAdmissionPolicyBinding` to `v1.ValidatingAdmissionPolicyBinding` using [runtime#Scheme.Convert](https://pkg.go.dev/k8s.io/apimachinery@v0.30.3/pkg/runtime#Scheme.Convert), results below errors - 

- `converting (v1beta1.ValidatingAdmissionPolicy) to (v1.ValidatingAdmissionPolicy): unknown conversion`

- `converting (v1beta1.ValidatingAdmissionPolicyBinding) to (v1.ValidatingAdmissionPolicyBinding): unknown conversion`

### What did you expect to happen?

`scheme.Convert` should convert the validating admission policy and validating admission policy binding resource to respective `v1` versions.

### How can we reproduce it (as minimally and precisely as possible)?

- Construct a `v1beta1` versioned ValidatingAdmissionPolicy or ValidatingAdmissionPolicyBinding object through go-client.
- Use `runtime#Scheme.Convert()` to convert the object to `v1` versioned Validating Admission Policy.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
# paste output here
Linux <user-name> 5.15.0-1068-azure #77~20.04.1-Ubuntu SMP Fri Jun 21 22:05:38 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
Conversion is only defined to the internal "hub" API type, not directly from one external version to another, and is only done by the api server, not by clients.

/close
