### ISSUE TITLE
Make volume.CanSupport return (bool, error)

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#12650]
Many volumes have dependencies on a binary being on the node, such as ISCSI, RBD, Gluster, and even GitRepo.   If the binary is not present, CanSupport returns False and gives the user a "No plugins found" error.

A user has a reasonable expectation for, say, RBD to be supported and it requires debugging to understand the binary isn't present.  A better error message would be something like "RBD binary not installed".  CanSupport should return (bool, error) to support that.

@smarterclayton @thockin @kubernetes/rh-storage  Thoughts on this UX improvement?

**Comment by markturansky** [comment]
We've run into this problem with NFS where "nfs-util" is not installed on the machine.  Debugging to learn of a missed install is not fun.

**Comment by brendandburns** [comment]
@markturansky can you add labels and priority?

**Comment by markturansky** [comment]
@brendandburns I don't think so or I just don't know where those options are in the UI.

**Comment by rootfs** [comment]
@markturansky probably you need write permission

**Comment by markturansky** [comment]
from #15668 

> It was missing nfs utils on the minions!

Another kind of thing to surface to the user, if possible.

**Comment by erictune** [comment]
@markturansky @thockin what is the plan here?
With a cluster built ca. v1.1, a GCE VM, and docs at head, the example fails.

**Comment by erictune** [comment]
example = examples/nfs

**Comment by thockin** [comment]
I thought we had already implemented this, but it seems not.  Aside from
that, there's a different issue with recycling (controller manager runs in
a container ergo no mount utils).  Solution is being discussed.

**Comment by erictune** [comment]
As far as I can see, there is no example for setting up multi-writer storage that does not require installing extra software on nodes.

**Comment by markturansky** [comment]
https://github.com/kubernetes/kubernetes/issues/16727 has the conversation around a solution.

I'm kind of glad this issue wasn't implemented yet because the bug in #16727 wouldn't have been solved.  With the solution discussed in that issue, we can return better errors, which is what this issue was intended to provide.

**Comment by thockin** [comment]
@pmorie @childsb @jsafrane @rootfs @saad-ali 

Hey all,  I am clearing out old PRs and issues and realized this is still open.  I propose one of 2 solutions.

1) We leave this as-is.  If you ask for NFS on a system that doesn't have NFS tools available, Mount() will fail, hopefully with a decent error message.  The volume plugin is correct, the system is wrong.

2) We add a "CanMount()" interface to the API and callers who want to SetUp() should call that first.  We could go further and make FindMountableVolumePlugin call CanMount, but then it would indicate that no plugin was found, when clearly one was.

So I think #1 is the right choice.  Plugins should just produce good errors.  Given that, I am closing this.  Argue with me...

**Comment by saad-ali** [comment]
I'm ok with 1
