### ISSUE TITLE
Scheduler allows more volumes than a CSI driver limit to be attached

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#126502]
### What happened?

When a pod that uses an attachable volume is deleted, it can take some time for its volumes to get detached, but the scheduler does not care about it and treats Pod volumes as detached immediately after Pod is deleted from the API server.

The scheduler should count not only Pods, but also existing VolumeAttachment objects to get accurate nr. of volumes attached to the node.

### What did you expect to happen?

Scheduler respects the attachment limit and never puts more Pods with volumes when a CSI driver is still detaching a volume for a deleted pod.

### How can we reproduce it (as minimally and precisely as possible)?

1. Get a CSI driver that reports an attach limit. Using AWS EBS, it reports 26 max. attachments in its CSINode:
    ```yaml
    spec:
      drivers:
      - allocatable:
          count: 26
        name: ebs.csi.aws.com
    ```
2. Create many pods targeting the same node using a `nodeSelector`, each of them using its own AWS EBS PV.
3. See scheduler tries to schedule just 26 Pods on the node, the rest is Pending.
4. Delete one Running Pod. Once the Pod is deleted, the scheduler puts a new Pod to the node immediately. But the volume of the deleted Pod is still attached!
5. Observe that nr. of VolumeAttachments is >26 for a short time. Depending on the driver and its current load and nr. of deleted pods it may not be that short time and it may grow significantly over 26.

Most CSI drivers recover from this, however, e.g. AWS EBS driver throws really weird errors and the recovery takes some time and I don't blame the driver.

### Anything else we need to know?

All attachable in-tree volumes are now migrated to CSI and have VolumeAttachments, so the calculation will be accurate even for them.

### Kubernetes version

v1.30.2

### Cloud provider

<details>
AWS EC2
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
> But the volume of the deleted Pod is still attached!

Which signal from the API can we use to know when the volume is no longer attached?

**Comment by jsafrane** [comment]
> Which signal from the API can we use to know when the volume is no longer attached?

VolumeAttachment for that volume - node pair does not exist. All in-tree attachable volumes are now migrated to CSI, so the object accurately represents volume attachment.

**Comment by alculquicondor** [comment]
cc @dom4ha
