### ISSUE TITLE
duplicate init kube-apiserver gorestful.container.ServeMux

### ISSUE THREAD

**Issue by Jerry-yz** [kubernetes/kubernetes#126547]
### What happened?

https://github.com/kubernetes/kubernetes/blob/00236ae0d73d2455a2470469ed1005674f8ed61f/staging/src/k8s.io/apiserver/pkg/server/handler.go#L80
https://github.com/emicklei/go-restful/blob/33de94869dbe48c2ad3bba44083546d0672fc359/container.go#L39

### What did you expect to happen?

whether should init gorestful.container.ServeMux once

### How can we reproduce it (as minimally and precisely as possible)?

none

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Adarsh-verma-14** [comment]
Hi @Jerry-yz , as for my understanding, func 'NewAPIServerHandler' initialize gorestfulContainer.ServeMux each time due to  gorestfulContainer.ServeMux = http.NewServeMux() when the function is called ,am i right ?

**Comment by Jefftree** [comment]
Looks like it is duplicated and we should be able to remove the call. Feel free to assign if anyone would like to send a PR for this.

**Comment by Adarsh-verma-14** [comment]
I want to work on this but need to some guidance

**Comment by Jefftree** [comment]
> Hi @Jerry-yz , as for my understanding, func 'NewAPIServerHandler' initialize gorestfulContainer.ServeMux each time due to gorestfulContainer.ServeMux = http.NewServeMux() when the function is called ,am i right ?

Yes, and it should already have been initialized when calling `restful.NewContainer()`

**Comment by Adarsh-verma-14** [comment]
yes @Jefftree got it , so we can remove call gorestfulContainer.ServeMux = http.NewServeMux() ?

**Comment by Jefftree** [comment]
yes

**Comment by Adarsh-verma-14** [comment]
/assign @Adarsh-verma-14 
I will raised PR.

**Comment by Adarsh-verma-14** [comment]
Hi @Jefftree, I have raised PR could you check ?
