### ISSUE TITLE
Inconsistency between the code and the doc on how `matchFields` works

### ISSUE THREAD

**Issue by scheduler-tester** [kubernetes/kubernetes#126531]
### What happened?

The `pod.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchFields` is introduced in PR [#62202](https://github.com/kubernetes/kubernetes/pull/62002) and used to bind a pod directly to nodes via `metadata.name`. However, we find that there are some hidden constraints on how to use this field that are not documented well.

More concretely, the current API documentation says that
```
> kubectl explain pod.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchFields
    KIND:       Pod
    VERSION:    v1

    FIELD: matchFields <[]NodeSelectorRequirement>


    DESCRIPTION:
        A list of node selector requirements by node's fields.
        A node selector requirement is a selector that contains values, a key, and
        an operator that relates the key and values.
    
    FIELDS:
      key   <string> -required-
        The label key that the selector applies to.
    
      operator      <string> -required-
      enum: DoesNotExist, Exists, Gt, In, ....
        Represents a key's relationship to a set of values. Valid operators are In,
        NotIn, Exists, DoesNotExist. Gt, and Lt.
    
        Possible enum values:
         - `"DoesNotExist"`
         - `"Exists"`
         - `"Gt"`
         - `"In"`
         - `"Lt"`
         - `"NotIn"`
    
      values        <[]string>
        An array of string values. If the operator is In or NotIn, the values array
        must be non-empty. If the operator is Exists or DoesNotExist, the values
        array must be empty. If the operator is Gt or Lt, the values array must have
        a single element, which will be interpreted as an integer. This array is
        replaced during a strategic merge patch.
```
And the doc does not mention that its key must be `metadata.name`, it's operator must be in `In/NotIn`, and the number of its value<s>s</s> must be equal to 1 (thought the term itself can be defined multiple times in `nodeSelectorTerms`).

This issue has also caused confusion in [#115980](https://github.com/kubernetes/kubernetes/issues/115980), [#81725](https://github.com/kubernetes/kubernetes/issues/81725), [#78238](https://github.com/kubernetes/kubernetes/issues/78238) and a reddit [thread](https://stackoverflow.com/questions/67018171/kubernetes-what-are-valid-node-fields)

### What did you expect to happen?

The hidden constraints should be explicitly documented if they reflect the developers' real intent. For example, we can mention this field in kubernetes.io docs, and clarify in the API doc on the constraints.

Besides improving the doc, we are thinking about how to prevent misconfiguration in this field (e.g., someone specifies things other than node name in `matchFields`) in the first place. One direction is to make the API more restrictive rather than take in any valid strings.

### How can we reproduce it (as minimally and precisely as possible)?

Read the documentation and the code.

### Anything else we need to know?

/sig scheduling docs

### Kubernetes version

<details>

Since 1.11, exists in 1.30

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by utkarsh-singh1** [comment]
Quite different from matchExpression -> where node labels are considered to filter out the node.

**Comment by utkarsh-singh1** [comment]
![Screenshot_20240807_100026](https://github.com/user-attachments/assets/70716c1c-65f5-47df-8180-0a1451469251)

**Comment by utkarsh-singh1** [comment]
Also, current description for nodeAffinity example does not have case for matchFields yet.

**Comment by utkarsh-singh1** [comment]
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity

**Comment by alculquicondor** [comment]
Open documentation issues against kubernetes/website

/close
