### ISSUE TITLE
kube-scheduler updates pod status mistakenly during preemption

### ISSUE THREAD

**Issue by xiazhan** [kubernetes/kubernetes#126643]
### What happened?

When a pod with "BestEffort" of qosClass is preempted by a higher priority pod whose qolClass is "Burstable", the victim pod's qosClass will be updated to "Burstable" because [the scheduler will update the victim's status with the content from higher priority pod before deleting the victim pod](https://github.com/kubernetes/kubernetes/blob/34e620d18c036acf035cb42c6f445dd568f60303/pkg/scheduler/framework/preemption/preemption.go#L375). The pod then will be stuck in terminating state after deleting because of this [check](https://github.com/kubernetes/kubernetes/blob/bbe8ca8b2ab14992389bc67e3bcfa209adcb13d4/pkg/apis/core/validation/validation.go#L4996). Supposedly, kubelet will reconcile the status back very soon. However, the deletion request stops kubelet from doing that.

### What did you expect to happen?

The victim pod's qosClass shouldn't be changed and the pod should be deleted successfully. 

### How can we reproduce it (as minimally and precisely as possible)?

 reproduced it on 1.29.4

Reproduce steps:
Scale the node number to 1
- Create victim pod (here I use a cronjob to create a pod with empty resources)
- Create a higher priority class(p1) with "Preempt" policy.
- Create extra pods(using a deployment) with priorityClassName as "p1" to make the pod number beyond the maxim pod number of the node. The pods also have cpu/memory requests set.
- The victim pod will be preempted, then stuck in "terminating" state
[cronjob.txt](https://github.com/user-attachments/files/16592258/cronjob.txt)
[deployment.txt](https://github.com/user-attachments/files/16592259/deployment.txt)
[pc.txt](https://github.com/user-attachments/files/16592260/pc.txt)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Huang-Wei** [comment]
@xiazhan I can confirm it's a regression.

Just curious: how did this issue popped up in your env? As a BestEfforts pod is considered reserving nil resources, and hence won't be considered a preemption victim. Is it because you have a custom scheduler that also looks into BestEfforts Pod upon preemption?

**Comment by xiazhan** [comment]
Thank @Huang-Wei for quick response!

**Comment by Huang-Wei** [comment]
> Just curious: how did this issue popped up in your env? As a BestEfforts pod is considered reserving nil resources, and hence won't be considered a preemption victim. Is it because you have a custom scheduler that also looks into BestEfforts Pod upon preemption?

Talked with @Fei-Guo offline. Best-efforts pod is also feasible to be preempted when the total pods number reaches the limit.

**Comment by alculquicondor** [comment]
>  The pod then will be stuck in terminating state after deleting

uhm... how come? Wouldn't the patch itself fail the validation logic?

**Comment by xiazhan** [comment]
> > The pod then will be stuck in terminating state after deleting
> 
> uhm... how come? Wouldn't the patch itself fail the validation logic?

Filed another issue for the patch. https://github.com/kubernetes/kubernetes/issues/126662#issuecomment-2287166555

**Comment by xiazhan** [comment]
> @xiazhan I can confirm it's a regression.
> 
> Just curious: how did this issue popped up in your env? As a BestEfforts pod is considered reserving nil resources, and hence won't be considered a preemption victim. Is it because you have a custom scheduler that also looks into BestEfforts Pod upon preemption?

Sorry, missed your question in the first reply. Yes, as you already got from Fei, it's preempted by max pods number of a node.

**Comment by alculquicondor** [comment]
Thanks for the follow up issue.

Then we can close this one, given that #126644 and its cherry-picks already merged
