### ISSUE TITLE
automatically configuring HAProxy

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#12665]
@jjfiguep wrote in another issue : 
----
Hi,

First of all, this is my first comment in GitHub and sorry if this is not the correct place.

In previous comments it is discussed the possibility to use Kubernetes and HAProxy. Also it is commented the option to periodically detect new services and update haproxy config file. 
This is just my problem, I´m using NodePort to expose the services to internet but I would like replace the assigned port number to access to the service by something more user friendly and my idea is to use haproxy to do the same (when /foo is requested in the url, haproxy should redirect the traffic to the corresponding port). The problem is that my implementation of Kubernetes is continuously creating and destroying services and the process to update haproxy configuration should be automatic. My doubts below:
1.- Am I focusing the problem from the correct side?
2.- If not, how I can resolve my problem? If yes, there is some project or something to do this? or could someone help me with this?

Thanks a lot!!

**Comment by erictune** [comment]
@jjfiguep

**Comment by erictune** [comment]
@bprashanth this user wants to use haproxy as a "bare metal load balancer", if I understand correctly.   
Is https://github.com/kubernetes/kubernetes/pull/11679/files the right thing?

**Comment by erictune** [comment]
@jjfiguep take a look at https://github.com/kubernetes/kubernetes/blob/master/contrib/service-loadbalancer/README.md and see if that answers some of your questions.

**Comment by bprashanth** [comment]
@jjfiguep did you deploy the haproxy pod in the example? let me know how it went when you have a minute

**Comment by jjfiguep** [comment]
Hello @bprashanth, sorry for my late response.

I have had some unexpected events and I could not to deploy the haproxy pod yet, but I have done a quick read and maybe it can help me.
I can´t check it soon but it is good to know that there are a possible solution. From my side we can close this issue and reopen it if I need more help in the future.

Thanks a lot for your help, I am very grateful.
