### ISSUE TITLE
Flag retrieval causes system exit

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#12668]
Helper methods for flag retrieval are now causing system exits.  This prevents any reasonable error handling for missing flag conditions.  See here for an example: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/helpers.go#L211

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by mengqiy** [comment]
Has this been fixed or not?

**Comment by deads2k** [comment]
> Has this been fixed or not?

It hasn't been fixed: https://github.com/kubernetes/kubernetes/blob/0613ae5077b280eabbff593bc2dc34fe2d03538d/pkg/kubectl/cmd/util/helpers.go#L369

**Comment by Lion-Wei** [comment]
@mengqiy Sorry I'm not understand, what is this issue talking about, : ( 
Can we fix it?

**Comment by soltysh** [comment]
> @mengqiy Sorry I'm not understand, what is this issue talking about, : (
> Can we fix it?

The problem is that when we can't read flag value we use `glog.Fatalf` which will eventually `os.Exit` process, which is what this issue is about. Have a look at this https://github.com/kubernetes/kubernetes/blob/0613ae5077b280eabbff593bc2dc34fe2d03538d/pkg/kubectl/cmd/util/helpers.go#L369
