### ISSUE TITLE
Get "invalid configuration: unable to read certificate-authority " error with clientcmd.RESTConfigFromKubeConfig function

### ISSUE THREAD

**Issue by guoqi1990** [kubernetes/kubernetes#126647]
### What happened?

I want to use this k8s.io/client-go/tools/clientcmd.RESTConfigFromKubeConfig([]byte(kubeConfig)) function to build a Kube config of IKS cluster , I provided kube config string which get from `ibmcloud ks cluster config --cluster CLUSTER_NAME`  command, but got following error

```
invalid configuration: unable to read certificate-authority /home/gqibj/.bluemix/plugins/container-service/clusters/oss-dev-dal10-btoplnjd0bgq7h9nbh80/ca-aaa00-oss-dev-dal10.pem for oss-dev-dal10/btoplnjd0bgq7h9nbh80 due to open /home/gqibj/.bluemix/plugins/container-service/clusters/oss-dev-dal10-btoplnjd0bgq7h9nbh80/ca-aaa00-oss-dev-dal10.pem: no such file or directory
```

### What did you expect to happen?

Build kube config file successfully.

### How can we reproduce it (as minimally and precisely as possible)?

ibmcloud login --sso
ibmcloud ks cluster config --cluster CLUSTER_NAME
Pass the content of ~/.kube/config to RESTConfigFromKubeConfig

### Kubernetes version

<details>

```console
$ kubectl version
# 1.29.7_1553
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xuzhenglun** [comment]
It looks like the path of certificate defined in the kubeconfig doesn't exist in your machine. you may check the content of the kubeconfig and find out.

/kind support
/remove-kind bug

additional, for support question please use the support channels. 
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
