### ISSUE TITLE
QosClass of pod status shouldn't be changeable

### ISSUE THREAD

**Issue by xiazhan** [kubernetes/kubernetes#126662]
### What happened?

According to this [code](https://github.com/kubernetes/kubernetes/blob/bbe8ca8b2ab14992389bc67e3bcfa209adcb13d4/pkg/apis/core/validation/validation.go#L4996), the QosClass of pod status is immutable. 

This [function ](https://github.com/kubernetes/kubernetes/blob/40b604e374144351eac463e7077fdb1903f5a033/pkg/apis/core/helper/qos/qos.go#L48
)also shows that QosClass is computed from the resources instead of being provided by users. 

However, we can use rest api or "kubectl edit pod <podName> --subresource='status'" to change it. 

### What did you expect to happen?

The request to change QoSClass of pod status should receive a validation error to indicate it's immutable. 

### How can we reproduce it (as minimally and precisely as possible)?

Use "kubectl edit pod <podName> --subresource='status'" to change the qosClass to a different value. It will succeed. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chengjoey** [comment]
In fact, this value cannot be changed. It directly obtains the qos of the old pod and compares it with the calculated value of the new pod. It does not matter what value is changed, and the change will not succeed.

`edit` succeed, but get pod still the old status qos

**Comment by xiazhan** [comment]
> In fact, this value cannot be changed. It directly obtains the qos of the old pod and compares it with the calculated value of the new pod. It does not matter what value is changed, and the change will not succeed.
> 
> `edit` succeed, but get pod still the old status qos

Not exactly. If you use "--subresource=status" in "kube edit po", it can change the qosClass. I verified that on 1.29.4.

**Comment by kannon92** [comment]
/unassign

I did not look into this.

**Comment by SergeyKanzhelev** [comment]
/assign @kubernetes/api-reviewers 

My understanding is that this is a breaking change and is not backward compatible. So it will be hard to enforce this even if it is semantically correct. Perhaps some warning may be useful in this case.
