### ISSUE TITLE
Status cannot be changed via pod patching

### ISSUE THREAD

**Issue by xiazhan** [kubernetes/kubernetes#126646]
### What happened?

When I tried to reproduce a [scheduler bug](https://github.com/kubernetes/kubernetes/issues/126643), I found some interesting behavior of pod/status patching. 
When I use "kubectl edit pod xxx" to change the qosClass of status of a pod,  kubectl sends out the request and gets the 200 response code, but the responseObject still has the old qosClass value. 

Instead , if I use below go code to patch the status as sub resource, the patching succeeds.
`newPod, err := cs.CoreV1().Pods(old.Namespace).Patch(ctx, old.Name, types.StrategicMergePatchType, patchBytes, metav1.PatchOptions{}, "status")
`
I checked the kube audit log and found the differences of two requests.  One patch happened on pod and the other patch happened on the subresource "status". 

![image](https://github.com/user-attachments/assets/6d398327-3e28-4bc9-8cea-894072b9f0da)

### What did you expect to happen?

I would expect their behaviors are consistent. Both of them can change the qosClass of the status. If the request kubectl sent really shouldn't change the value for some reason, I would expect it returns some meaningful error. 

### How can we reproduce it (as minimally and precisely as possible)?

Use "kubectl edit pod xxx" to change the qosClass of status of pod. There is no failure, but the value won't be changed. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xuzhenglun** [comment]
for editing subresource via `kubectl`, you need to append `--subresource` flag to do so. 
see more: https://kubernetes.io/docs/reference/kubectl/conventions/#subresources

> I would expect their behaviors are consistent. Both of them can change the qosClass of the status. 
actually, the behavior between `client-go` and `kubectl` are consistent. In `client-go`, you also need to specify the "status" parameter when calling `Patch`. In the hood, there are two different APIs between `resource` and `subresource`, see more: https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-uris

/kind support
/remove-kind bug
/close
