### ISSUE TITLE
`kubectl wait --for=jsonpath='{.status.readyReplicas}'=1` fails in 1.31.0-rc.1

### ISSUE THREAD

**Issue by neoaggelos** [kubernetes/kubernetes#126637]
### What happened?

https://kubernetes.slack.com/archives/C0EG7JC6T/p1723471158762629

In v1.31.0-rc.1 `kubectl wait --for=jsonpath='{.status.readyReplicas}'=1` commands hang, see relevant thread for details.

### What did you expect to happen?

Second command should work, as it does with kubectl v1.30.3

### How can we reproduce it (as minimally and precisely as possible)?

Reproducer against a 1.30.3 server:

```
(
	curl https://dl.k8s.io/v1.31.0-rc.1/kubernetes-client-linux-amd64.tar.gz -L -o v1.31.0-rc.1.tar.gz
	tar xvzf v1.31.0-rc.1.tar.gz -C v1.31.0-rc.1
)


./v1.31.0-rc.1/kubernetes/client/bin/kubectl create deploy nginx --image nginx --replicas 1
./v1.31.0-rc.1/kubernetes/client/bin/kubectl wait deploy nginx --for=condition=available                # works
./v1.31.0-rc.1/kubernetes/client/bin/kubectl wait deploy nginx --for=jsonpath='{.status.readyReplicas}'=1    # does not work
```

### Kubernetes version

<details>

```console
$ ./v1.31.0-rc.1/kubernetes/client/bin/kubectl version
Client Version: v1.31.0-rc.1
Kustomize Version: v5.4.2
Server Version: v1.30.3

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neoaggelos** [comment]
cc @soltysh @liggitt

**Comment by liggitt** [comment]
looks like a regression introduced in https://github.com/kubernetes/kubernetes/pull/125868/files#r1713843179

/assign @soltysh

**Comment by liggitt** [comment]
thanks so much for the very detailed and timely report, great to catch this before the .0 release 🎉
