### ISSUE TITLE
contrib/podex: update to kubernetes v1 and registry v2

### ISSUE THREAD

**Issue by proppy** [kubernetes/kubernetes#12663]
See https://github.com/kubernetes/kubernetes/pull/11693#issuecomment-128889120

**Comment by 3cky** [comment]
Working on this issue, have some questions about correct format for "container" manifest type for kubernetes v1. Currently I implemented it like this:
```bash
$ ./podex -type="container" google/nodejs-hello
apiVersion: v1
kind: ContainerList
metadata: {}
containers:
- name: nodejs-hello
  image: google/nodejs-hello
  ports:
  - name: nodejs-hello-tcp-8080
    containerPort: 8080
```
Not sure about `kind` value and `metadata` content.

**Comment by 3cky** [comment]
Done in kubernetes/contrib#53

cc @proppy

**Comment by brendandburns** [comment]
Fixed by https://github.com/kubernetes/contrib/pull/53
