### ISSUE TITLE
Container network metrics missing with kubelet 1.30 and crio-1.30

### ISSUE THREAD

**Issue by rkojedzinszky** [kubernetes/kubernetes#126682]
### What happened?

Upgraded kubernetes cluster from 1.29 to 1.30, and container network metrics disappeared.

### What did you expect to happen?

Expected metrics to be available as before.

### How can we reproduce it (as minimally and precisely as possible)?

Run crio-1.30 with default config, deploy kubernetes 1.30, deploy a pod, and collect cadvisor metrics. `container_network_receive_bytes_total` and other metrics are not reported for pod.

### Anything else we need to know?

Seems that crio dropping infra containers and a change in cadvisor results in this misbehavior. https://github.com/google/cadvisor/issues/3577

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2
WARNING: version difference between client (1.28) and server (1.30) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
Bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux k8s-node01 5.15.162 #2 SMP Tue Jul 9 08:02:50 UTC 2024 aarch64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
cri-o 1.30
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
kube-router v2.1.3
</details>

**Comment by kannon92** [comment]
cc @saschagrunert @haircommander

**Comment by kannon92** [comment]
Is there a reason to have this here and in cadvisor?

**Comment by rkojedzinszky** [comment]
> Is there a reason to have this here and in cadvisor?

Only that this the user-facing misbehavior, howewer, the real issue is in a component kubernetes depends on.

**Comment by saschagrunert** [comment]
@rkojedzinszky can we keep the conversation in https://github.com/google/cadvisor/issues/3577 to streamline the bugfix and close out this one instead?

**Comment by rkojedzinszky** [comment]
> @rkojedzinszky can we keep the conversation in [google/cadvisor#3577](https://github.com/google/cadvisor/issues/3577) to streamline the bugfix and close out this one instead?

Sure, sorry for spamming here.
