### ISSUE TITLE
ResourceSliceList object has `listMeta` field instead of `metadata` field

### ISSUE THREAD

**Issue by Arnavion** [kubernetes/kubernetes#126659]
### What happened?

Listing `v1alpha3.ResourceSlice`s on v1.31.0 returns an object with a `listMeta` field instead of the standard `metadata` field for (list) objects:

```sh
$ curl -kL --cert client.pem --key client.key.pem 'https://127.0.0.1:39987/apis/resource.k8s.io/v1alpha3/resourceslices'

{
  "kind": "ResourceSliceList",
  "apiVersion": "resource.k8s.io/v1alpha3",
  "listMeta": {
    "resourceVersion": "522"
  },
  "items": []
}
```

Listing `v1alpha2.ResourceSlice`s on v1.30.3 behaves correctly:

```sh
$ curl -kL --cert client.pem --key client.key.pem 'https://127.0.0.1:34519/apis/resource.k8s.io/v1alpha2/resourceslices'

{
  "kind": "ResourceSliceList",
  "apiVersion": "resource.k8s.io/v1alpha2",
  "metadata": {
    "resourceVersion": "422"
  },
  "items": []
}
```

This is also propagated to the Swagger spec (which is how I noticed it, since I maintain the Rust bindings for the client API). v1.31.0:

```json
    "io.k8s.api.resource.v1alpha3.ResourceSliceList": {
        "listMeta": {
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta",
          "description": "Standard list metadata"
        }
```

v1.30.3:

```json
    "io.k8s.api.resource.v1alpha2.ResourceSliceList": {
        "metadata": {
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta",
          "description": "Standard list metadata"
        }
```

### What did you expect to happen?

As explained above.

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy v1.31.0 with `DynamicResourceAllocation` feature gate enabled and runtime config `resource.k8s.io/v1alpha3=true`. With kind, this is:

    ```yaml
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    featureGates:
      DynamicResourceAllocation: true
    runtimeConfig:
      'resource.k8s.io/v1alpha3': 'true'
    ```

2. Perform the API server request as in the above curl command in any way you like as long as it lets you see the raw JSON response.

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0
```

</details>

### Cloud provider

<details>
kind 0.23.0
</details>

### OS version

<details>

```console
N/A
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pranav-pandey0804** [comment]
It seems there may be a discrepancy in the API response format between v1.30.3 and v1.31.0. The `ResourceSliceList` object is expected to follow standard Kubernetes API conventions, which typically use the `metadata` field for list objects.

**Comment by pranav-pandey0804** [comment]
This deviation might cause compatibility issues for API clients that rely on this structure.

**Comment by pranav-pandey0804** [comment]
If this deviation from the expected API structure wasn't intentional, it should be aligned with the standard conventions.

**Comment by pranav-pandey0804** [comment]
The presence of `listMeta` instead of `metadata` could disrupt client integrations, as you've encountered with the Swagger spec and Rust bindings.

**Comment by BenTheElder** [comment]
cc @kubernetes/api-reviewers

**Comment by liggitt** [comment]
this must be fixed to `metav1.ListMeta `json:"metadata" protobuf:"bytes,1,opt,name=metadata"``

the `listMeta` serialization will not work with standard clients

**Comment by thockin** [comment]
Shoot, that's clearly a mistake.
