### ISSUE TITLE
The secrets user guide uses the word automatic too freely

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/kubernetes#12664]
Based on this thread

https://groups.google.com/d/msg/google-containers/VTc3EQLv9R0/6MPmOtlgAQAJ

the secrets user guide may use the word 'automatic' too freely.  Not all secrets in a namespace are automatically mounted in a same-namespace pod, and the user-guide should make this clear, or at least avoid implying it.

**Comment by brendandburns** [comment]
@erictune can you take a look at that doc and see about making sure it is correct wrt 'automatic'

Thanks!
