### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Change in version-skewed behavior in v1.31

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#126616]
For features that span nodes & control planes, they must support the case where the feature is enabled in the control plane but not on nodes, in order to support version skew after the feature is promoted to a default-on state.

Previously, the node/control-plane skewed behavior of `InPlacePodVerticalScaling` was to sort of support the resize by restarting the resized container. The API is eventually consistent with the running container.

1. Someone / something updates pod resources on a running pod
2. apiserver has the feature gate enabled, so it accepts the request and sets the resize status to pending
3. Kubelet sees a change in the hash and restarts the container, with the new resource amount
4. Kubelet patches the status, but doesn't set the resize status (and doesn't copy it from the old status), thus clearing it

In v1.31 the hashing logic was changed to avoid accidental container restarts: https://github.com/kubernetes/kubernetes/pull/124220. However, this also prevents the Kubelet from seeing the changed resources in step 3, so the container is not restarted with the new resource value. If the container is restarted for any other reason, it will be restarted with the new resource value. There is no way to tell from the API which value the container is using.

The previous behavior is consistent with the skew handling described in the KEP, except this part was never implemented:
> kubelet: When feature-gate is disabled, if kubelet sees a Proposed resize, it rejects the resize as Infeasible.

This is a regression, but shouldn't be release blocking as it is only triggered when the alpha feature is enabled.

/kind bug
/kind regression
/milestone v1.31
/sig node
/priority important-longterm

**Comment by tallclair** [comment]
**Proposal:**

The `Resources` field in container status is set by the Kubelet if and only if IPPVS is enabled. It's a hack, but the apiserver can use this information to determine whether the node the pod is running on supports IPPVS. In other words, in validation, only allow a resize if the resources field is present on the container status (or if the pod is still pending):

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L5166

**Comment by HirazawaUi** [comment]
> In v1.31 the hashing logic was changed to avoid accidental container restarts: #124220. However, this also prevents the Kubelet from seeing the changed resources in step 3, so the container is not restarted with the new resource value. If the container is restarted for any other reason, it will be restarted with the new resource value.

I believe the current behavior is reasonable. We shouldn't restart the pod just because a user updates pod resources when the InPlacePodVerticalScaling feature gate is enabled on the ApiServer (this is still unexpected for users).



> in validation, only allow a resize if the resources field is present on the container status (or if the pod is still pending):

Should we modify the ApiServer's validation logic based on Kubelet's behavior? Would it be better to warn users that this behavior will cause the actual running pod's resources to be inconsistent with their updates until the pod is restarted?

**Comment by HirazawaUi** [comment]
> kubelet: When feature-gate is disabled, if kubelet sees a Proposed resize, it rejects the resize as Infeasible.

I believe the current actions are still in line with this goal, aren't they?

**Comment by tallclair** [comment]
>> in validation, only allow a resize if the resources field is present on the container status (or if the pod is still pending):
>
> Should we modify the ApiServer's validation logic based on Kubelet's behavior? Would it be better to warn users that this behavior will cause the actual running pod's resources to be inconsistent with their updates until the pod is restarted?

I agree it's weird, but I think it's our best option here. We can remove it in a future release once we're not worried about the version skew.

I wanted to capture this issue so we don't forget about it, but I think the next step is to update the KEP (I'm working on a KEP update).

/cc @thockin

**Comment by tallclair** [comment]
>> kubelet: When feature-gate is disabled, if kubelet sees a Proposed resize, it rejects the resize as Infeasible.
>
> I believe the current actions are still in line with this goal, aren't they?

I'm not sure I understand what you're saying here. The Kubelet doesn't currently reject a proposed resize if the feature gate is disabled. If we wanted this to be the version skew behavior, we'd need to push that change in v1.32, and then wait all the way until v1.35 to promote to beta.

**Comment by HirazawaUi** [comment]
> I'm not sure I understand what you're saying here. The Kubelet doesn't currently reject a proposed resize if the feature gate is disabled. If we wanted this to be the version skew behavior, we'd need to push that change in v1.32, and then wait all the way until v1.35 to promote to beta.

Soory,  my previous response wasn't accurate; the current behavior doesn't align with the deviation logic outlined in the KEP.



> I agree it's weird, but I think it's our best option here. We can remove it in a future release once we're not worried about the version skew.

If it was our consensus in previous discussions(in KEP's PR) that we should reject resource updates to running pods when the `InPlacePodVerticalScaling` feature gate is enabled on the ApiServer but not on the kubelet, then I support that approach (or if we have a smarter way to detect whether the kubelet has `InPlacePodVerticalScaling` enabled).

**Comment by HirazawaUi** [comment]
If we consider the issue as "no way to tell from the API which value the container is using," the original KEP seems to have the same problem.

When the ApiServer receives the user's update to the pod resource, and the kubelet rejects the resizing, the resources in the running pod remain old, while the pod resources in the ApiServer are updated. From this perspective, the current behavior seems consistent with the original KEP.

The only difference is that the kubelet does not explicitly reject the resource update.

**Comment by Vyom-Yadav** [comment]
Hey Folks, why is this in the 1.31 milestone? (We are shipping 1.31.0 tomorrow)

**Comment by liggitt** [comment]
agreed, I don't think this is actionable for the 1.31 milestone

/milestone clear

**Comment by tallclair** [comment]
Yeah, sorry, I originally tagged v1.31 because the change in behavior is in v1.31, and I thought we might want to try and backport a fix, but I don't think that will be needed (and certainly isn't needed for v1.31.0)

**Comment by thockin** [comment]
> Should we modify the ApiServer's validation logic based on Kubelet's behavior?

Any feature which has updates control-plane and node components has this issue, more or less - right?

I don't think we want to gate the APi based on kubelets - Is it "some" kubelets?  All kubelets?  What if one is updated and rolled back after API admission.

**Comment by HirazawaUi** [comment]
> Any feature which has updates control-plane and node components has this issue, more or less - right?
> 
> I don't think we want to gate the APi based on kubelets - Is it "some" kubelets? All kubelets? What if one is updated and rolled back after API admission.

Yes, this approach (gating the API based on the kubelet) cannot cover scenarios where the kubelet is rolled back. This proposal by @tallclair is more of a remedial action because our current behavior has disrupted the version skew policy outlined in the original KEP(even though we haven't actually implemented this).

However, I would prefer to discuss the rationality of the version skew policy in the original KEP. If we require the kubelet to explicitly reject updates to pod resources when the InPlacePodVerticalScaling feature gate is not enabled, then to ensure our component version skew policy is maintained, the feature gate would need at least three versions to reach beta(even though we've already gone through four versions in the alpha stage).

I believe a more common version skew policy would be to have the kubelet ignore the pod resource updates when the feature gate is not enabled (like we added a new field to podSpec, but the old version of kubelet will ignore it). This approach does not impact running workloads. The downside, however, is that the actual running resources of a pod may not match what is observed through the API until the pod is restarted (The version skew policy in the original KEP seems to have the same problem).

**Comment by HirazawaUi** [comment]
Regarding the InPlacePodVerticalScaling feature gate, if the Apiserver is enabled but the kubelet has it disabled, the behavior is as follows:

Original KEP: If the kubelet detects a Proposed resize, it rejects the resize as Infeasible.

Before #124220: If the kubelet detects a Proposed resize, it would restart the pod with the updated resources and clear the resize field in the status.

After #124220: If the kubelet detects a Proposed resize, it does not restart the pod and clear the resize field in the status.

I prefer the current approach, WDYT？

**Comment by tallclair** [comment]
>> Should we modify the ApiServer's validation logic based on Kubelet's behavior?
> 
> Any feature which has updates control-plane and node components has this issue, more or less - right?

Yes, more or less. We should probably solve this in a generic way, but I'd prefer not to block in-place pod resize on it. This is also an unusual case since it's not adding a new field (or value), just making an existing one mutable.

> I don't think we want to gate the APi based on kubelets - Is it "some" kubelets? All kubelets? What if one is updated and rolled back after API admission.

I'll propose a KEP update with the details, but here's a rough summary:

- This logic is only applied on update, and the gating only happens if the pod is already bound to a node (there's some details to work out around whether the pod is pending)
- The gating I proposed above is based on whether the Kubelet is setting a specific status field, so if there are mixed node versions, it would be blocked for nodes with the feature disabled, but allowed for enabled nodes
- Rollback isn't an issue, since this is only evaluated on update by comparing to the old value. Once the value is updated, this validation logic doesn't kick in, independent of whether the feature is enabled or disabled.

> After https://github.com/kubernetes/kubernetes/pull/124220: If the kubelet detects a Proposed resize, it does not restart the pod and clear the resize field in the status.
> 
> I prefer the current approach, WDYT？

I don't like that there is no way to tell what resources the container is configured for in the current approach, and when it uses the updated resources is non-deterministic. I could also imagine this causing problems with any controllers that try to use in-place update (e.g. VPA).

If we go with either of the current approaches, IMO we should backport a change to make the behavior consistent.

**Comment by liggitt** [comment]
> I don't like that there is no way to tell what resources the container is configured for in the current approach, and when it uses the updated resources is non-deterministic.

I thought the status was supposed to give visibility for when the node had accepted the increased resources. Does it not?

> If we go with either of the current approaches, IMO we should backport a change to make the behavior consistent.

I don't think we'd backport changes for alpha features, we'd wait until the oldest supported skewed node had the behavior we expected before enabling by default, right?

**Comment by tallclair** [comment]
>> I don't like that there is no way to tell what resources the container is configured for in the current approach, and when it uses the updated resources is non-deterministic.
> 
> I thought the status was supposed to give visibility for when the node had accepted the increased resources. Does it not?

Only once the feature is enabled. The discussion here is specifically for the skewed case where it's enabled in the apiserver, so the resources can be mutated, but the Kubelet doesn't have in-place updates enabled. As of v1.31 the behavior is that the resources are updated, but the Kubelet ignores them until the container is restarted for any other reason.

> I don't think we'd backport changes for alpha features, we'd wait until the oldest supported skewed node had the behavior we expected before enabling by default, right?

Yeah, probably. Hence wanting to address it at the control plane :)

**Comment by HirazawaUi** [comment]
@thockin @SergeyKanzhelev  Do you have any additional thoughts on this? If not, I will go ahead and implement it according to @tallclair's suggestion.

**Comment by tallclair** [comment]
This is fixed with the new version skew handling described in the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1287-in-place-update-pod-resources/README.md#version-skew-strategy). https://github.com/kubernetes/kubernetes/issues/117767 tracks the version skew strategy implementation, so I'll close this.

@HirazawaUi feel free to pick up https://github.com/kubernetes/kubernetes/issues/117767
