### ISSUE TITLE
kubectl >= 1.30.0 triggers leak of goroutines in containerd on `kubectl exec`

### ISSUE THREAD

**Issue by alfredkrohmer** [kubernetes/kubernetes#126608]
### What happened?

Some of our developers were running a workload that regularly does `kubectl exec` into pods running in an EKS cluster with a command that collects some metrics, then exits.

We noticed an increase of memory usage by the containerd process on the host running the pod into which the `kubectl exec` connected. Turning on the debug socket of containerd and comparing the output of the `ctr pprof goroutines` command executed multiple times over the span of several minutes showed that goroutines were leaking inside containerd. All leaked goroutines had a stack trace like this:

```
goroutine 82060 [chan receive]:
k8s.io/apiserver/pkg/util/wsstream.(*Conn).Open(0xc006ba0af0, {0x55fe91acc880?, 0xc0055d8ee0}, 0xc00a1bcb00)
	/builddir/build/BUILD/containerd-1.6.19-1.amzn2.0.1/src/github.com/containerd/containerd/vendor/k8s.io/apiserver/pkg/util/wsstream/conn.go:185 +0xc5
github.com/containerd/containerd/pkg/cri/streaming/remotecommand.createWebSocketStreams(0xc00a1bcb00?, {0x55fe91acc880, 0xc0055d8ee0}, 0xc0085c17f4, 0xd18c2e28000)
	/builddir/build/BUILD/containerd-1.6.19-1.amzn2.0.1/src/github.com/containerd/containerd/pkg/cri/streaming/remotecommand/websocket.go:114 +0x32c
github.com/containerd/containerd/pkg/cri/streaming/remotecommand.createStreams(0xc00a1bcb00, {0x55fe91acc880, 0xc0055d8ee0}, 0xc0085c1690?, {0x55fe926be380, 0x4, 0x4}, 0x203001?, 0xc006d8bb00?)
	/builddir/build/BUILD/containerd-1.6.19-1.amzn2.0.1/src/github.com/containerd/containerd/pkg/cri/streaming/remotecommand/httpstream.go:126 +0x9b
github.com/containerd/containerd/pkg/cri/streaming/remotecommand.ServeExec({0x55fe91acc880?, 0xc0055d8ee0?}, 0x6?, {0x55fe91ab5af8, 0xc0006b0ed0}, {0x0, 0x0}, {0x0, 0x0}, {0xc006b918c0, ...}, ...)
	/builddir/build/BUILD/containerd-1.6.19-1.amzn2.0.1/src/github.com/containerd/containerd/pkg/cri/streaming/remotecommand/exec.go:61 +0xc5
github.com/containerd/containerd/pkg/cri/streaming.(*server).serveExec(0xc00040a090, 0xc004cfa630, 0xc006be77a0)
	/builddir/build/BUILD/containerd-1.6.19-1.amzn2.0.1/src/github.com/containerd/containerd/pkg/cri/streaming/server.go:302 +0x19e
github.com/emicklei/go-restful.(*Container).dispatch(0xc00040a1b0, {0x55fe91acc880, 0xc0055d8ee0}, 0xc00a1bcb00)
	/builddir/build/BUILD/containerd-1.6.19-1.amzn2.0.1/src/github.com/containerd/containerd/vendor/github.com/emicklei/go-restful/container.go:288 +0x8c8
net/http.HandlerFunc.ServeHTTP(0x0?, {0x55fe91acc880?, 0xc0055d8ee0?}, 0x0?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x72?, {0x55fe91acc880, 0xc0055d8ee0}, 0xc00a1bcb00)
	/usr/lib/golang/src/net/http/server.go:2462 +0x149
github.com/emicklei/go-restful.(*Container).ServeHTTP(0x0?, {0x55fe91acc880?, 0xc0055d8ee0?}, 0xc0074c0000?)
	/builddir/build/BUILD/containerd-1.6.19-1.amzn2.0.1/src/github.com/containerd/containerd/vendor/github.com/emicklei/go-restful/container.go:303 +0x27
net/http.serverHandler.ServeHTTP({0xc004cfa510?}, {0x55fe91acc880, 0xc0055d8ee0}, 0xc00a1bcb00)
	/usr/lib/golang/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0054b1a40, {0x55fe91acdbd8, 0xc003dc2420})
	/usr/lib/golang/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:3071 +0x4db
```

The number of leaked goroutines can be checked with:
```console
$ ctr pprof goroutines | grep createWebSocketStreams | wc -l
```

This looks like the websocket connection from kubelet to containerd is somehow stuck, however the `kubectl exec` command works just fine.

The version of kubectl used by the workload is `v1.30.2`, while the cluster itself is running AWS EKS `v1.26.15-eks-db838b0` (kubelet: `v1.26.4-eks-0a21954`) and we could reproduce this as well on a cluster running `v1.28.11-eks-db838b0` (kubelet: `v1.28.11-eks-1552ad0`).
After checking some versions, it looks like this behavior started with kubectl `v1.30.0` and was not present in `v1.29.4` yet.
We are aware that this is an unsupported version discrepancy, but it shouldn't be possible for a normal user of the Kubernetes API to trigger a memory leak in the container runtime by simply running `kubectl exec` repeatedly against a pod with an incompatible version of kubectl.

### What did you expect to happen?

Neither kubectl nor any other Kubernetes API client should be able to cause a memory leak in the container runtime of the host running the affected pod.

### How can we reproduce it (as minimally and precisely as possible)?

1. Start an EKS cluster v1.26 or v1.28 (probably 1.27 or earlier versions and plain Kubernetes clusters are affected as well, but we couldn't check this) and ensure some nodes are up and running and some pods are running as well.
2. SSH into a node and enable the containerd debug socket by appending the following to `/etc/containerd/config.toml`:
    ```toml
    [debug]
      address = "/run/containerd/debug.sock"
    ```
    Then restart containerd with `systemctl restart containerd`, then run:
    ```console
    $ watch "ctr pprof goroutines | grep createWebSocketStreams | wc -l"
    ```
4. In a second terminal, run `kubectl exec <pod name> -- true` or similar repeatedly against any pod running on the node on which you SSH'd.
5. Notice the number reported by the `watch` command increase for every execution of `kubectl`.

### Anything else we need to know?

We were unsure where the right place to report this issue would be. We believe containerd should have timeout on this goroutine to abort it if something gets stuck. On the other hand, this can only be triggered with a newer certain version of kubectl, which also hints a bug in the Kubernetes API server or in kubelet.

### Kubernetes version

<details>

1.26 cluster:
```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.15-eks-db838b0
WARNING: version difference between client (1.30) and server (1.26) exceeds the supported minor version skew of +/-1
```

1.28 cluster:
```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.11-eks-db838b0
WARNING: version difference between client (1.30) and server (1.28) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

1.26 cluster:
```console
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
$ uname -a
Linux ip-a-b-c-d.us-east-2.compute.internal 5.10.179-168.710.amzn2.x86_64 #1 SMP Mon May 22 23:10:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

1.28 cluster:
```console
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"

$ uname -a
Linux ip-a-b-c-d.us-east-1.compute.internal 5.10.220-209.869.amzn2.x86_64 #1 SMP Wed Jul 17 15:10:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Verified on containerd `1.6.19` and `1.7.11`
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xuzhenglun** [comment]
Can you please dump the kubelet goroutine by `kubectl get --raw '/api/v1/nodes/<node-name>/proxy/debug/pprof/goroutine?debug=2'` to check if there is some goroutine leaking in `kubelet`?

/sig node

**Comment by alfredkrohmer** [comment]
After doing 10 `kubectl exec` calls, I can only see 1 additional goroutine spawned in kubelet:
```
goroutine 47737 [IO wait]:
internal/poll.runtime_pollWait(0x7f6e04306c58, 0x72)
	runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc000cba400?, 0xc000fd4700?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000cba400, {0xc000fd4700, 0x700, 0x700})
	internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc000cba400, {0xc000fd4700?, 0xc000bc35f0?, 0x8?})
	net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc000520cc8, {0xc000fd4700?, 0xc002005860?, 0x1d?})
	net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc001cf7470, {0xc000fd4700?, 0xc001cf7470?, 0x0?})
	crypto/tls/conn.go:805 +0x3b
bytes.(*Buffer).ReadFrom(0xc000d050a8, {0x4af67e0, 0xc001cf7470})
	bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000d04e00, {0x4af6860?, 0xc000520cc8}, 0xc000bc3788?)
	crypto/tls/conn.go:827 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc000d04e00, 0x0)
	crypto/tls/conn.go:625 +0x250
crypto/tls.(*Conn).readRecord(...)
	crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc000d04e00, {0xc0010eb000, 0x1000, 0x6d13080?})
	crypto/tls/conn.go:1369 +0x158
net/http.(*connReader).Read(0xc0012e4d80, {0xc0010eb000, 0x1000, 0x1000})
	net/http/server.go:791 +0x14b
bufio.(*Reader).fill(0xc000876720)
	bufio/bufio.go:113 +0x103
bufio.(*Reader).Peek(0xc000876720, 0x4)
	bufio/bufio.go:151 +0x53
net/http.(*conn).serve(0xc00121a2d0, {0x4b273d0, 0xc000b0b470})
	net/http/server.go:2044 +0x75c
created by net/http.(*Server).Serve in goroutine 206
	net/http/server.go:3086 +0x5cb
```
that might be unrelated.

**Comment by xuzhenglun** [comment]
> additional

yeah, maybe you can try to reproduce this by execute `crictl exec`? If the goroutine is still leaking without kubelet, so maybe it's related with `containerd` only.

**Comment by alfredkrohmer** [comment]
`crictl exec` does not leak goroutines in containerd.

**Comment by xuzhenglun** [comment]
will restarting kubelet release goroutine in containerd?On Aug 9, 2024, at 18:33, Alfred Krohmer ***@***.***> wrote:﻿
crictl exec does not leak goroutines in containerd.

**Comment by alfredkrohmer** [comment]
No, after `systemctl restart kubelet`, `ctr pprof goroutines | grep createWebSocketStreams | wc -l` still reports the same number as before.

**Comment by xuzhenglun** [comment]
So this goroutine leaking doest not like caused by connection leaking. I will do some research later.

**Comment by alfredkrohmer** [comment]
Just learned that `Exec` can work with Spdy or with WebSocket in the CRI. Just tried `crictl` `v1.31.0` like so:
```
$ ./crictl exec --transport websocket d23e90b9151b3 true
WARN[0000] runtime connect using default endpoints: [unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead. 
FATA[0000] execing command in container: unable to upgrade streaming request: websocket: bad handshake (403 Forbidden)
```
and this **did** cause a leaked goroutine in containerd.

**Comment by alfredkrohmer** [comment]
Just checked:
* starting `kubectl exec` >= `v1.30.0` with the environment variable `KUBECTL_REMOTE_COMMAND_WEBSOCKETS=false` does **not** cause the leaked goroutines
* starting `kubectl exec` on `v1.29.4` with `KUBECTL_REMOTE_COMMAND_WEBSOCKETS=true` **does** cause the leaked goroutines

It looks like the feature flag is enabled is enabled by default starting 1.30 and it looks that if it is enabled, kubectl will try the WebSocket connection first and fallback to Spdy if this doesn't work, which I think is what is happening here:
https://github.com/kubernetes/kubectl/blob/321896d352dc90d2ccc68c8e3b2ed46a0bc314a0/pkg/cmd/exec/exec.go#L145-L153

So it looks like this is purely a bug in containerd that is triggered if it refuses an `Exec` connection through WebSocket.

**Comment by mikebrow** [comment]
@liggitt @aojea @SergeyKanzhelev @saschagrunert We appear to be moving from default is spdy to default is unimplemented websocket?  Note here: https://github.com/kubernetes-sigs/cri-tools/pull/1305#issuecomment-1858867649. I thought the default would remain the tested/working one, surprised by the change.

**Comment by liggitt** [comment]
The websocket exec by kubectl is handled by kube-apiserver and translated into a spdy exec request to the node / kubelet / containerd. There's no change on the kubelet side yet.

**Comment by liggitt** [comment]
cc @seans3

**Comment by alfredkrohmer** [comment]
@liggitt As you can see from the stack trace of the leaked goroutine above, a `kubectl exec` with WebSocket is _somehow_ translated to a WebSocket exec against containerd.

**Comment by liggitt** [comment]
The websocket exec protocol requested by kubectl 1.30 is unknown to kube-apiserver prior to 1.29 and is just proxied through to nodes. It is *also* unknown to kubelets prior to 1.29 (and any websocket negotiation code copied out from kubernetes to containerd prior to 1.29). During development, @seans3 verified kubectl websocket exec requests to old servers / nodes returned a negotiation error, which makes kubectl to fall back to spdy.

It's... surprising to see an old node / containerd version apparently accepting a websocket subprotocol it shouldn't know about... need to figure out why this differs from the negotiation error @seans3 verified for this scenario.

**Comment by alfredkrohmer** [comment]
> During development, @seans3 verified kubectl websocket exec requests to old servers / nodes returned a negotiation error, which makes kubectl to fall back to spdy.

This is actually what's happening here.

> It's... surprising to see an old node / containerd version apparently accepting a websocket subprotocol it shouldn't know about... need to figure out why this differs from the negotiation error @seans3 verified for this scenario.

containerd isn't accepting the connection, it's actually returning a 403 and kubelet falls back to Spdy. However, this failed connection attempt leads to a leaked goroutine in containerd apparently.

**Comment by xuzhenglun** [comment]
it seems like [conn.ready](https://github.com/containerd/containerd/blob/963625d7bcee468ced2f868a9de6dbb2c7506514/vendor/k8s.io/apiserver/pkg/util/wsstream/conn.go#L185) never have chance to be closed, since the ws connection was never be initialized.

containerd 1.6.19 vendor's `k8s.io/apiserver` was too old, this issue seems like was fixed in https://github.com/kubernetes/kubernetes/commit/168998e87bfd49a1b0bc6402761fafd5ace3bb3b#diff-c2c40fc1bed998a21132175e1db4d83c0514fe9963b09373bd4823fa553cd866R220

**Comment by xuzhenglun** [comment]
cc @liggitt @seans3 

Perhaps we should update the documentation to warn users that there is a known issue here.

/triage accepted

**Comment by SergeyKanzhelev** [comment]
So this seems to be the containerd issue. I don't think there is anything kubelet can do differently.

This sounds critical enough to warrant the cherry-pick to 1.x branch.

@samuelkarp @mikebrow wdyt?

**Comment by mikebrow** [comment]
@SergeyKanzhelev bit of a tricky problem here.  We should probably not be going back to 1.6/1.7(and out of service 1.5) and swapping out the streaming implementation, the one we had forked from k8s way back when to resolve k8s's recursive imports problems, to the new implementation and then testing the new implementation from the server side (containerd all shims) against the now out of service Kubernetes releases that were also based entirely on spdy.. and the new k8s releases.  

We should consider a patch of some kind in the 1.x containerd releases to resolve the leak, but that won't resolve the new 403 error that occurs as a way of probing to see if the new preferred protocol is available.  

I have a vague memory of the streaming proxy code in kubelet, would have to look it over again to see if there is an easy way to avoid asking older cri integrations to support new types of streaming connection protocols replacing spdy, but again that won't fix the problem of kubectl asking for an unsupported protocol "first."  Fixing in kubelet would just reduce the surface area impact of the changes by returning the 403 faster.

Wondering if there is any validation code / migration code for the config/defaults where we could by default set  KUBECTL_REMOTE_COMMAND_WEBSOCKETS=false esp. if the version of the container runtime is known to 403 this..

**Comment by SergeyKanzhelev** [comment]
yes, I meant the fix for leak, not the whole feature.

Is there a problem with 403? My understanding it will be retried with other protocol? Changing the default will hide the problem, but it still seems like a severe problem. Are you saying that the priority for it will be lowered if the defaults will be changed?

**Comment by alfredkrohmer** [comment]
I think there is no problem with the 403, kubectl silently ignores that and proceeds with Spdy.

**Comment by mikebrow** [comment]
Yes, connection attempt using the unsupported protocol will fail and the runtime will log that as an **error** every time. https://github.com/containerd/containerd/blob/main/internal/cri/instrument/instrumented_service.go#L288 
Then on the subsequent request, unless in debug log level, silently work just fine as kubectl hunts for it's next best protocol. This will be a new error not seen before and is highly likely to raise issues / queries trigger alarms etc. with admin scripts/tools execing into infra containers.

**Comment by dims** [comment]
cc @henry118 @cartermckinnon @mmerkes @tzneal

**Comment by mikebrow** [comment]
digging deeper there was code for web sockets in containerd 1.x but that code got out of sync with the k8s version..

**Comment by samuelkarp** [comment]
Would it be a problem if we dropped websocket support in containerd 1.6/1.7 entirely, since crictl and Kubelet should both fall-back to spdy?

**Comment by mikebrow** [comment]
but the plan is removing spdy ... panic() :-)

**Comment by SergeyKanzhelev** [comment]
> Would it be a problem if we dropped websocket support in containerd 1.6/1.7 entirely, since crictl and Kubelet should both fall-back to spdy?

Another deprecation or change of functionality notice in 2.0? Ideally 1.7 should have the same logic as 2.0 so people can test to prepare to 2.0. Having this difference in 2.0 is yet another thing to block adoption.

**Comment by henry118** [comment]
Looking at the current websocket implementation, the goroutine leak seems to be solvable with the `serveHTTPComplete` chan (below).

https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/staging/src/k8s.io/apimachinery/pkg/util/httpstream/wsstream/conn.go#L219-L246

But that's vendor code in containerd.

**Comment by mikebrow** [comment]
> Looking at the current websocket implementation, the goroutine leak seems to be solvable with the `serveHTTPComplete` chan (below).
> 
> https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/staging/src/k8s.io/apimachinery/pkg/util/httpstream/wsstream/conn.go#L219-L246
> 
> But that's vendor code in containerd.

nod that seems to be a part of it (why I said panic() above :-) It is vendor in containerd main... but was a fork copy of the k8s implementation in 1.6/1.7 where it is not out of sync..

**Comment by henry118** [comment]
Is it possible to backport that part of the logic?

**Comment by mikebrow** [comment]
> Is it possible to backport that part of the logic?

possibly

**Comment by dims** [comment]
@mikebrow @henry118 see https://github.com/containerd/containerd/issues/10568#issuecomment-2282345839

**Comment by aojea** [comment]
> Would it be a problem if we dropped websocket support in containerd 1.6/1.7 entirely, since crictl and Kubelet should both fall-back to spdy?

websockets are supported and Conformance for a long time, remove that support is a breaking change

https://github.com/kubernetes/kubernetes/blob/b2799bbda7f381c004b7b6827e66ed37cc83de42/test/conformance/testdata/conformance.yaml#L2364-L2371

The thing here is that kubectl exec/attach/port-forward were using spdy by default and , with the spdy deprecation, there were some flaws identified by @seans3 on the existing websocket protocol, hence the new version of the protocol

**Comment by mikebrow** [comment]
> > Would it be a problem if we dropped websocket support in containerd 1.6/1.7 entirely, since crictl and Kubelet should both fall-back to spdy?
> 
> websockets are supported and Conformance for a long time, remove that support is a breaking change
> 
> https://github.com/kubernetes/kubernetes/blob/b2799bbda7f381c004b7b6827e66ed37cc83de42/test/conformance/testdata/conformance.yaml#L2364-L2371
> 
> The thing here is that kubectl exec/attach/port-forward were using spdy by default and , with the spdy deprecation, there were some flaws identified by @seans3 on the existing websocket protocol, hence the new version of the protocol

nod.. @dims has fixed it, bringing the streaming code back in sync.  is merged now in test.. and with the next 1.6/1.7 patches.  Thank you @dims ..

**Comment by kannon92** [comment]
Should we close this issue? Given that https://github.com/containerd/containerd/issues/10568#issuecomment-2282345839 exists?
