### ISSUE TITLE
InPlacePodVerticalScaling feature duplicate feature definition

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#126793]
The InPlacePodVerticalScaling feature is duplicated in both https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L922-L928 and https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/features/kube_features.go#L287-L292.

Traditionally pkg/features should inherit from apiserver features as defined here: https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L1245-L1256 to prevent duplication and drift.

/cc @vinaykul @jpbetz

**Comment by Adarsh-verma-14** [comment]
Hi @Jefftree, it would be great approach I want to work on that if triage accepted.

**Comment by Adarsh-verma-14** [comment]
@Jefftree , I have worked on it but I am  facing some issue

**Comment by Adarsh-verma-14** [comment]
when I remove  the feature flag definition from `pkg/features/kube_features.go` causes errors in the source code because many parts of the code are still using it

**Comment by Adarsh-verma-14** [comment]
if i only replace this line `InPlacePodVerticalScaling: {Default: false, PreRelease: featuregate.Alpha}`, with `genericfeatures.InPlacePodVerticalScaling: {Default: false, PreRelease: featuregate.Alpha},` in pkg/features/kube_features.go then is there duplication removed or not ?

**Comment by Jefftree** [comment]
Yes it is removed. You can also remove the definition in `pkg/features/kube_features.go`. If anything else in the code references the `InPlacePodVerticalScaling` variable from `pkg/features/kube_features.go` instead of the one from genericfeatures, they will also need to be updated.

**Comment by Adarsh-verma-14** [comment]
you mean like for example this snippet code https://github.com/kubernetes/kubernetes/blob/master/pkg/api/pod/util.go#L657 using 
`InPlacePodVerticalScaling` variable from pkg/features/kube_features.go then I need to replace with `genericfeatures.InPlacePodVerticalScaling` instead of `features.InPlacePodVerticalScaling`.

**Comment by Adarsh-verma-14** [comment]
@Jefftree , I have made some changes in this PR:https://github.com/kubernetes/kubernetes/pull/126882 PTAL!!

**Comment by Adarsh-verma-14** [comment]
first one is I removed feature flag definition  from `pkg/features/kube_feature.go` for InPlacePodVerticalScaling and inherit pkg/feature traditionally as suggested

**Comment by Adarsh-verma-14** [comment]
second one is which part of source code references the `InPlacePodVerticalScaling` variable from `pkg/features/kube_features.go` is also updated using inherit from apiserver.

**Comment by tallclair** [comment]
This was fixed by https://github.com/kubernetes/kubernetes/pull/127161

/close
