### ISSUE TITLE
Wrong path to Kubernetes binaries provided to user after successful cluster turnup

### ISSUE THREAD

**Issue by adamjcook** [kubernetes/kubernetes#12674]
The following message is shown after running `export KUBERNETES_PROVIDER=aws; curl -sS https://get.k8s.io | bash` to turnup a cluster on AWS:

```
...
Kubernetes binaries at /Users/myname/kubernetes/kubernetes/cluster/
You may want to add this directory to your PATH in $HOME/.profile
Installation successful!
```

However, there is no directory `/Users/myname/kubernetes/kubernetes/cluster/` created by the script. I think that what is meant is just `/Users/myname/kubernetes/cluster/`.

I am just getting started with looking at Kubernetes, but I can certainly provide a PR if this issue is accepted.

**Comment by brendandburns** [comment]
Yeah, that looks like a bug in the script, would happily take a PR.

Thanks!
-brendan

**Comment by justinsb** [comment]
We're not going to making further changes to kube-up, and I don't believe kops has this problem (and I recommend kops as the natural replacement for users looking for kube-up like ease of use on AWS - without many of the shortcomings of kube-up!)  Closing.
