### ISSUE TITLE
Inconsistency between the code and the doc when toleration has an empty key

### ISSUE THREAD

**Issue by scheduler-tester** [kubernetes/kubernetes#126790]
### What happened?

According to the [concept documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#concepts)
> **An empty key** with operator Exists matches all keys, values and effects which means this **will tolerate everything**.

This means when a toleration's `key` is empty, it can match any taints no matter what value the `effect` is.

But this is inconsistent with the [API documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#concepts):

> **If the key is empty**, operator must be Exists; this combination **means to match all values and all keys.**

This means even if a toleration's `key` is empty, the `effect` should also be the same to match a taint.

And **the code** implementation is following **the API documentation**, thus contradicting **the concept documentation**.

### What did you expect to happen?

The concept documentation, the API documentation and the code should be consistent.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a node with a taint
```bash
kubectl apply -f - <<EOF
apiVersion: v1
kind: Node
metadata:
  name: node-1
spec:
  taints:
    - key: simple-key
      value: simple-value
      effect: NoSchedule
EOF
```

2. Create a pod with a toleration whose key is empty, it should be able to land on `node-1` according to the concept documentation
```bash
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: container-1
      image: nginx
  tolerations:
    - key: ''
      operator: Exists
      effect: NoExecute
EOF
```

3. Check the pod's scheduling result, it failed to be scheduled to `node-1`
```bash
$ kubectl describe pods pod-1
 Warning  FailedScheduling  0/1 nodes are available: 1 node(s) had untolerated taint {simple-key: simple-value}. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

### Anything else we need to know?

/sig docs scheduling

### Kubernetes version

1.30.2

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
Please open documentation issues against kubernetes/website

/close
