### ISSUE TITLE
Typo in cassandra example?

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes#12673]
Here: 
https://github.com/kubernetes/kubernetes/blob/master/examples/cassandra/README.md#simple-single-pod-cassandra-node
and here:
https://github.com/kubernetes/kubernetes/blob/master/examples/cassandra/cassandra-controller.yaml
the cpu info in the rc spec: 'cpu: 0.1'
doesn't match with the text: 'Finally, we tell the cluster manager that we need 0.5 cpu (0.5 core).'

**Comment by brendandburns** [comment]
yep, want to fix it ;)

Thanks!
--brendan
