### ISSUE TITLE
the patch operation of the node lifecycle controller may miss the taints that need to be processed

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#126755]
### What happened?

when node lifecycle controller and other clients patch taints on  the same node simultaneously, which may cause the taints to be overwritten

### What did you expect to happen?

when node lifecycle controller and other clients patch taints on  the same node simultaneously, which the taints not to be overwritten

### How can we reproduce it (as minimally and precisely as possible)?

when node lifecycle controller and other clients patch taints on  the same node simultaneously, there is a small probability that this issue will occur

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Linux kind-control-plane 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
/sig node

Is there a way to reproduce it without adding a sleep? I assume you encountered this issue in a production or test environment. Could you describe your use case?

**Comment by yangjunmyfm192085** [comment]
> /sig node
> 
> Is there a way to reproduce it without adding a sleep? I assume you encountered this issue in a production or test environment. Could you describe your use case?

Yes. If there are multiple kube-apiserver instances in the cluster, there will be problems in the following scenarios:
When the node status changes from not ready to ready, the two goroutines of kube-controller-manager that remove the unreachable noschedule taint and noexecute taint update the taint information at the same time, which may cause overwriting. When the noschedule taint is deleted and overwritten again, when processing subsequent node change messages, the node-controller will load balance to a random apiserver to obtain the latest node information, but may access a node that has only updated the removal of the noschedule taint, causing the node-controller to think that the noschedule taint has been removed and no longer process it.
The result is that when the node status changes to ready, the noschedule taint is still retained.

**Comment by HirazawaUi** [comment]
Technically, this makes sense, but the interval at which `monitorNodeHealth` runs is determined by the `--node-monitor-period` parameter of the `kube-controller-manager`. By default, it runs every 5 seconds, which I believe is sufficient to balance the Apiserver cache and etcd. 
ref: https://github.com/kubernetes/kubernetes/blob/0f095cf0ba5156a972b446a5f65c963fe2a7919c/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L508-L513

If you encountered this issue, you might need to provide more detailed information about your environment configuration when the issue occurred :)

**Comment by yangjunmyfm192085** [comment]
> Technically, this makes sense, but the interval at which `monitorNodeHealth` runs is determined by the `--node-monitor-period` parameter of the `kube-controller-manager`. By default, it runs every 5 seconds, which I believe is sufficient to balance the Apiserver cache and etcd. ref:
> 
> https://github.com/kubernetes/kubernetes/blob/0f095cf0ba5156a972b446a5f65c963fe2a7919c/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L508-L513
> 
> If you encountered this issue, you might need to provide more detailed information about your environment configuration when the issue occurred :)

This has nothing to do with the interval at which monitorNodeHealth runs. The main problem is that the processing of the taint no execute and no schedule is handled by two goroutines. In addition, the TaintManager processes node events triggered by watch, not controlled by the --node-monitor-period parameter.

**Comment by yangjunmyfm192085** [comment]
The cause analysis is wrong. The current patch taints operation should not cause overwriting. I will continue to study it.
/close

**Comment by yangjunmyfm192085** [comment]
@HirazawaUi As commented in https://github.com/kubernetes/kubernetes/pull/126756#issuecomment-2295241702. I think this modification is necessary

**Comment by yangjunmyfm192085** [comment]
/remove-kind bug
/kind support
More analysis needed

**Comment by yangjunmyfm192085** [comment]
I will close this PR first.
Continue to analyze it clearly

/close
