### ISSUE TITLE
kube-proxy fails with CreateContainerConfigError when joining a 1.30.0 node to 1.30.4 cluster

### ISSUE THREAD

**Issue by sj98ta** [kubernetes/kubernetes#126746]
### What happened?

I have a cluster which is 1.30.4 and I am trying to join a node to the cluster that is 1.31.0, and the kube-proxy fails to start, and the status is `CreateContainerConfigError` . 

`kubectl describe pod` events show:
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  65s                default-scheduler  Successfully assigned kube-system/kube-proxy-gc7zf to server2
  Normal   Pulled     11s (x6 over 63s)  kubelet            Container image "registry.k8s.io/kube-proxy:v1.30.4" already present on machine
  Warning  Failed     11s (x6 over 63s)  kubelet            Error: services have not yet been read at least once, cannot construct envvars
```
The kubelet logs shows:
`GET https://<apiserverip of cluster>:6443/api/v1/services?fieldSelector=spec.clusterIP%21%3DNone&limit=500&resourceVersion=0 400 Bad Request in 7 milliseconds`

And the response is 
`failed to list *v1.Service: "spec.clusterIP" is not a known field selector: only "metadata.name", "metadata.namespace"`

All-Beta=False feature-gate is coded for all components. 
Enabling the `CustomResourceFieldSelectors` on the downlevel node seemed to have no effect.

The problem seems to be that even though the joining node downloaded the correct images and start the pods, the kubelet of course is still at 1.31.0.   I suspect installing a downlevel kubelet will allow it to work.

Is this even a supported thing to do?  i.e.  join a downlevel cluster with an uplevel node? 

### What did you expect to happen?

I would have expected with AllBeta=False, that the request would not be sent with `spec.clusterIP`  
I also would have also expected that enabling the `CustomResourceFieldSelectors` on the downlevel node would have allowed the spec.clusterIP field selector.

### How can we reproduce it (as minimally and precisely as possible)?

Bring up an 1.30.4 node with `kubeadm init`
Attempt to join a 1.31.0 node to the cluster.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4

```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux server1 5.4.0-186-generic #206-Ubuntu SMP Fri Apr 26 12:31:10 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
1.30.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xuzhenglun** [comment]
This is expected and not a bug, as the [version skew policy](https://kubernetes.io/releases/version-skew-policy/#kubelet) saild:

> kubelet must not be newer than kube-apiserver.

`spec.clusterIP` fieldSelector of service is added in 1.31, so apiserver in 1.30 doesn't support this param. addional, kubelet also use this param in 1.31, so when 1.31 kubelet connect to 1.30 apiserver, an error occurd.

/support
/close
