### ISSUE TITLE
kube-controller-manager takes 100% cpu on master

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#126704]
### What happened?

When starting K8s on master the kube-controller-manager 100% cpu all the time in an idle system. I have 2 cores on my VM's so kube-controller-manager hogs 1 core.

### What did you expect to happen?

kube-controller-manager should take ~0% cpu in an idle system

### How can we reproduce it (as minimally and precisely as possible)?

Start K8s on master and run "top"

### Anything else we need to know?

I made a bisect, and the problem appear in commit eb16aa1d4a5d36482bd58da6737364ef81759002.

I start kube-controller-manager from init scripts, so no POD.

### Kubernetes version

master (v1.32.0-alpha.0.22+f6a11da279877b)

### Cloud provider

none

### OS version

Linux 6.10.0

### Install tools

none

### Container runtime (CRI) and version (if applicable)

crio version 1.29.2

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Probably all CNI-plugins. Tested:

1. flannel:v0.24.2
2. calico/cni:v3.27.0
3. cilium:v1.15.4
4. antrea-ubuntu:v1.14.1

**Comment by uablrek** [comment]
I start kube-controller-manager from init scripts, so no POD.

**Comment by xuzhenglun** [comment]
Could you please dump pprof `goroutine` and `profile` to help locate where the CPU is consumed. 
```bash
kubectl create clusterrole "foo" --verb=get --non-resource-url='/debug/*'
kubectl create clusterrolebinding foo  --clusterrole=foo --group=system:unauthenticated

curl -k https://127.0.0.1:10257/debug/pprof/profile > profile.bin
curl -k https://127.0.0.1:10257/debug/pprof/goroutine?debug=2 > goroutine.txt
```

**Comment by uablrek** [comment]
@xuzhenglun 

goroutine.txt:
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/debug/pprof/goroutine\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```
same with profile.bin.

This is a virtual test cluster. I can restart with any params to kube-controller-manager in <30s. I am root and can do anything without any risk of messing up. So, can I use some other tool? I will check the go profiler, but I haven't used it, so it may take a while

What I usually can't do is using tools with a lot of dependencies, since this is a small system without any Linux distro.

**Comment by uablrek** [comment]
BTW, the log looks fine. No repeated error logs. After start it is quiet. Last entries:
```
I0815 10:35:42.552461     327 shared_informer.go:320] Caches are synced for garbage collector
I0815 10:35:42.552496     327 shared_informer.go:320] Caches are synced for garbage collector
I0815 10:35:42.552502     327 garbagecollector.go:157] "All resource monitors have synced. Proceeding to collect garbage" logger="garbage-collector-controller"
I0815 10:35:50.585234     327 range_allocator.go:241] "Successfully synced" logger="node-ipam-controller" key="vm-001"
I0815 10:35:50.632973     327 range_allocator.go:241] "Successfully synced" logger="node-ipam-controller" key="vm-003"
I0815 10:35:50.752938     327 range_allocator.go:241] "Successfully synced" logger="node-ipam-controller" key="vm-002"
I0815 10:35:50.776898     327 range_allocator.go:241] "Successfully synced" logger="node-ipam-controller" key="vm-004"
```

**Comment by uablrek** [comment]
> I will check the go profiler, but I haven't used it

Oh, I just did :smile: The "kubectl create" commands work. But I am using token authentication to the api-server, must I use the token in some way to get profiling data?

**Comment by uablrek** [comment]
Tried to set
```
--authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics,/debug
```
to `kube-controller-manager`, but access to /debug is still rejected. /metrics works though

**Comment by xuzhenglun** [comment]
> tl create" commands work. But I am using token authentication to the api-server, must I use the token in some way to get profiling d

After ClusterRole and ClusterRoleBinding are created, you should be able to connect to the 10257 port which `kube-controller-manager` listen. 

> Tried to set --authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics,/debug

try `--authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics,/debug/*`, It should works too.

**Comment by uablrek** [comment]
That worked. The files are in [pprof.tar.gz](https://github.com/user-attachments/files/16625334/pprof.tar.gz).

**Comment by xuzhenglun** [comment]
It looks like there is a dead loop here. `queue.Len()` return `0` and make `processNextWorkItem()` return immediately. 
https://github.com/kubernetes/kubernetes/blob/eb16aa1d4a5d36482bd58da6737364ef81759002/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L183-L187
https://github.com/kubernetes/kubernetes/blob/eb16aa1d4a5d36482bd58da6737364ef81759002/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L195-L208

/triage accepted
/sig storage
/kind bug
/kind regression
/priority important-soon

cc @hungnguyen243

**Comment by xuzhenglun** [comment]
the pprof profile can also proof this:
![pprof001](https://github.com/user-attachments/assets/536179b1-675d-401b-9051-25d4aa90ba44)

**Comment by xuzhenglun** [comment]
I just submit a quick fix https://github.com/kubernetes/kubernetes/pull/126719, PTAL @hungnguyen243 @pwschuurman

**Comment by xuzhenglun** [comment]
The promblemic commit has been decided to revert in https://github.com/kubernetes/kubernetes/pull/126723, and the follow-up PR is at https://github.com/kubernetes/kubernetes/pull/126725

**Comment by uablrek** [comment]
The problem is gone after the reverted PR. Closing
