### ISSUE TITLE
kubectl exec to pods causes unexpected exit 0 in concurrence with jobs running

### ISSUE THREAD

**Issue by abhijit-2024** [kubernetes/kubernetes#126778]
### What happened?

We are having our EKS cluster and Node Groups working fine in our environment however whenever we are logged into a pod of our cluster then we are getting logged out after an hour automatically - this is happening when we are running batch using some scripts :-
Screen Shots -
EKS Version - 1.28
![image](https://github.com/user-attachments/assets/ddace079-ef8e-498a-80ff-954d63bdcf9f)

EKS Cluster
![image](https://github.com/user-attachments/assets/96265b59-9926-4ee2-8c9c-4c3c10921a23)
When we are logged in to a pod
![image](https://github.com/user-attachments/assets/e532bf77-abad-4d8c-b518-b4bac6c6f96b)

Kubectl Version [Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-0a21954", GitCommit:"cd5c12c51b0899612375453f7a7c2e7b6563f5e9", GitTreeState:"clean", BuildDate:"2023-04-15T00:35:51Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.11-eks-db838b0", GitCommit:"5ec1757cec753faac1ea8374cf6bfee9a8b35c2a", GitTreeState:"clean", BuildDate:"2024-06-27T19:09:54Z", GoVersion:"go1.21.11", Compiler:"gc", Platform:"linux/amd64"}]
![image](https://github.com/user-attachments/assets/d549880d-b912-4721-9ae3-864d6cd9d386)

Docker version
[root@ip-10-152-145-146 bin]# docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:22:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false
![image](https://github.com/user-attachments/assets/df8210aa-8f77-43bc-a3ff-3406b8ca690b)

 

### What did you expect to happen?

We do not want the automated signing out from EKS pods

### How can we reproduce it (as minimally and precisely as possible)?

We are having our EKS cluster and Node Groups working fine in our environment however whenever we are logged into a pod of our cluster then we are getting logged out after an hour automatically - this is happening when we are running batch using some scripts

### Kubernetes version

Kubernetes Version is 1.28
![image](https://github.com/user-attachments/assets/63344523-3209-452b-b8a2-8a54456d2527)
Public Cloud Platform is AWS

Kubectl Version [Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-0a21954", GitCommit:"cd5c12c51b0899612375453f7a7c2e7b6563f5e9", GitTreeState:"clean", BuildDate:"2023-04-15T00:35:51Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.11-eks-db838b0", GitCommit:"5ec1757cec753faac1ea8374cf6bfee9a8b35c2a", GitTreeState:"clean", BuildDate:"2024-06-27T19:09:54Z", GoVersion:"go1.21.11", Compiler:"gc", Platform:"linux/amd64"}]
![image](https://github.com/user-attachments/assets/d549880d-b912-4721-9ae3-864d6cd9d386)

Docker version
[root@ip-10-152-145-146 bin]# docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:22:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false
![image](https://github.com/user-attachments/assets/df8210aa-8f77-43bc-a3ff-3406b8ca690b)

### Cloud provider

AWS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
$ uname -a
Linux ip-10-51-155-146.eu-west-1.compute.internal 5.10.214-202.855.amzn2.x86_64 #1 SMP Tue Apr 9 06:57:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
ping @dims to see if we can triage this , as it is not clear to me this is a kubernetes problem and seems more about the specific implementation

**Comment by dims** [comment]
please reach out to EKS/AWS support. this should not be open in community repository.

/kind support
/close
