### ISSUE TITLE
Fix service e2e test on ubuntu node by using initctl

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#12689]
pr #12506 introduces run kubernetes node on GCE with Ubuntu. e2e service test failed because test code uses init.d restart kube-proxy, instead of initctl. 

cc/ @andyzheng0831

**Comment by andyzheng0831** [comment]
I think it is not fixed yet

**Comment by ixdy** [comment]
Ah, now I see. [`restart-kube-proxy` in cluster/gce/util.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L1217-L1223) has a correct implementation, but [`restartKubeProxy` in test/e2e/util.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/util.go#L2156-L2166) does not.

**Comment by andyzheng0831** [comment]
It is true. I made the change in the util.sh script, because it is easy to
determine the os distribution. But I am not sure how to do it in the test
golang code, so the problem in test/e2e/util.go has not been fixed.

**Comment by ixdy** [comment]
Right, I just wanted to document what was missing so that future-me would understand what still needs to be done.

**Comment by andyzheng0831** [comment]
While I was working on pr #20463, I noticed that test cases in test/e2e/addon_update.go also uses "init.d" to restart kube-addon service. This does not work for distros using upstart as init system, such as ubuntu trusty.

**Comment by ixdy** [comment]
We should fix this - I think this test is still disabled in some places due to this issue. cc @wonderfly

**Comment by andyzheng0831** [comment]
This issue can be closed now. Since 1.2.0, kube-proxy is moved into a pod and the test code simply kill the kube-proxy process to force restart it. This way works in ContainerVM, Trusty, and CoreOS.

**Comment by wonderfly** [comment]
Where was the fix? Was it ever cherry-picked to `release-1.1`?
