### ISSUE TITLE
Split L3 Cache Topology Awareness in CPU Manager

### ISSUE THREAD

**Issue by ajcaldelas** [kubernetes/kubernetes#126890]
### What would you like to be added?

Introduction to a new CPU Manager static policy option that groups CPUs resources by last level cache where possible. 

### Why is this needed?

The enhancement is to reduce noisy neighbor scenarios that occur on systems with split L3 cache, which is available on both x86 and ARM architecture.

**Comment by ffromani** [comment]
/triage accepted
/sig node
/priority important-longterm

we have a KEP which is tentatively added to the 1.32 cycle, so I guess a trackin issue is helpful

**Comment by thisisharrsh** [comment]
Please take a [look](https://github.com/kubernetes/enhancements/issues/4800).

**Comment by pacoxu** [comment]
/close 
in favor of https://github.com/kubernetes/enhancements/issues/4800
