### ISSUE TITLE
DRA: ResourceSlice controller enhancements

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#126837]
### What would you like to be added?

https://github.com/kubernetes/kubernetes/blob/v1.31.0/staging/src/k8s.io/dynamic-resource-allocation/resourceslice/resourceslicecontroller.go was "good enough" for alpha, but still needs further work:
- [ ] support publishing larger numbers of devices in multiple ResourceSlice objects
- [ ] unit tests

### Why is this needed?

More complex DRA drivers might need this. Lack of unit tests is a blocker for beta.

/sig node
/priority important-soon

**Comment by googs1025** [comment]
I'm not sure if we need to lock the operation here. I think we should try to use locks to protect variables in this operation (provided that it does not affect performance). If necessary, I will submit a new PR to modify it.
@pohly @bart0sh 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/dynamic-resource-allocation/structured/allocator.go#L475
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/dynamic-resource-allocation/structured/allocator.go#L464
```go
type matchAttributeConstraint struct {
	logger        klog.Logger // Includes name and attribute name, so no need to repeat in log messages.
	requestNames  sets.Set[string]
	attributeName resourceapi.FullyQualifiedName

	attribute  *resourceapi.DeviceAttribute
	numDevices int
}

func (m *matchAttributeConstraint) add(requestName string, device *resourceapi.BasicDevice, deviceID DeviceID) bool {
	if m.requestNames.Len() > 0 && !m.requestNames.Has(requestName) {
		// Device not affected by constraint.
		m.logger.V(7).Info("Constraint does not apply to request", "request", requestName)
		return true
	}

	attribute := lookupAttribute(device, deviceID, m.attributeName)
	if attribute == nil {
		// Doesn't have the attribute.
		m.logger.V(7).Info("Constraint not satisfied, attribute not set")
		return false
	}

	if m.numDevices == 0 {
		// The first device can always get picked.
		m.attribute = attribute
		m.numDevices = 1
		m.logger.V(7).Info("First in set")
		return true
	}

	switch {
	case attribute.StringValue != nil:
		if m.attribute.StringValue == nil || *attribute.StringValue != *m.attribute.StringValue {
			m.logger.V(7).Info("String values different")
			return false
		}
	case attribute.IntValue != nil:
		if m.attribute.IntValue == nil || *attribute.IntValue != *m.attribute.IntValue {
			m.logger.V(7).Info("Int values different")
			return false
		}
	case attribute.BoolValue != nil:
		if m.attribute.BoolValue == nil || *attribute.BoolValue != *m.attribute.BoolValue {
			m.logger.V(7).Info("Bool values different")
			return false
		}
	case attribute.VersionValue != nil:
		// semver 2.0.0 requires that version strings are in their
		// minimal form (in particular, no leading zeros). Therefore a
		// strict "exact equal" check can do a string comparison.
		if m.attribute.VersionValue == nil || *attribute.VersionValue != *m.attribute.VersionValue {
			m.logger.V(7).Info("Version values different")
			return false
		}
	default:
		// Unknown value type, cannot match.
		m.logger.V(7).Info("Match attribute type unknown")
		return false
	}

	m.numDevices++
	m.logger.V(7).Info("Constraint satisfied by device", "device", deviceID, "numDevices", m.numDevices)
	return true
}

func (m *matchAttributeConstraint) remove(requestName string, device *resourceapi.BasicDevice, deviceID DeviceID) {
	if m.requestNames.Len() > 0 && !m.requestNames.Has(requestName) {
		// Device not affected by constraint.
		return
	}

	m.numDevices--
	m.logger.V(7).Info("Device removed from constraint set", "device", deviceID, "numDevices", m.numDevices)
}
```

**Comment by pohly** [comment]
Let's discuss on Slack, it's unrelated to this PR. I am currently working on performance optimizations of that code and will ask for reviewers soon.

**Comment by googs1025** [comment]
I think the unit test part is done. Also, how do we support publishing larger numbers of devices in multiple ResourceSlice objects? If need my help, please let me know. Or will you be responsible for this part? :)

**Comment by pohly** [comment]
@googs1025: thanks for asking. Yes, it would be great if you could continue with publishing via multiple ResourceSlice objects.

The algorithm that I envision would work like this:
- Get list of current slices objects.
- Remove all devices which no longer exist in the desired state.
- Add new devices in the desired state to existing slice, trying one after the other. The limiting factor is the number of devices per slice (https://github.com/kubernetes/kubernetes/blob/3ab0c84bacd059a5b5995d72706c63b46ed24c0b/staging/src/k8s.io/api/resource/v1alpha3/types.go#L185C7-L185C30).
- Create new slices if necessary.
- If there are changes in a pool, re-publish *all* slices of that pool with an increased pool.generation, including slices which were not modified otherwise. They would become obsolete if left with the original generation.

Because you will deal with objects that contain many devices, consider writing a helper function which produces a set of `Device` instances.

A unit test will use the fake client-go, which doesn't do the same check as a real apiserver.

Therefore a related activity is to write an E2E test which creates such "large" slices, ideally with everything at its maximum size. That serves as check that our size limits are accurate and a "valid" slice really can be stored.

**Comment by googs1025** [comment]
Thanks for the detailed response! Just a couple things I want to confirm:

- So most of the logic should be contained within the syncPool method, right?
- Also, our requirement stems from the fact that resourceslice has a maximum length limit, but the Devices in the Pool could potentially exceed a length of 128, hence the need for multiple resourceslices to manage them. Am I correct in understanding this?

**Comment by pohly** [comment]
Both is correct.
