### ISSUE TITLE
Failure cluster [9aa4f04d...] swap tests failing for ubuntu

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#126857]
##### Error text:
```
[FAILED] Timed out after 300.000s.
expected pod to be running and ready, got instead:
    <*v1.Pod | 0xc00085db08>: 
        metadata:
          annotations:
            owner.test: k8s.io/kubernetes/test/e2e_node/swap_test.go:379
          creationTimestamp: "2024-08-19T20:48:38Z"
          managedFields:
          - apiVersion: v1
            fieldsType: FieldsV1
            fieldsV1:
              f:metadata:
                f:annotations:
                  .: {}
                  f:owner.test: {}
              f:spec:
                f:containers:
                  k:{"name":"busybox-container"}:
                    .: {}
                    f:command: {}
                    f:image: {}
                    f:imagePullPolicy: {}
                    f:name: {}
                    f:resources: {}
                    f:terminationMessagePath: {}
                    f:terminationMessagePolicy: {}
                f:dnsPolicy: {}
                f:enableServiceLinks: {}
                f:nodeName: {}
                f:restartPolicy: {}
                f:schedulerName: {}
                f:securityContext: {}
                f:terminationGracePeriodSeconds: {}
            manager: e2e_node.test
            operation: Update
            time: "2024-08-19T20:48:38Z"
          - apiVersion: v1
            fieldsType: FieldsV1
            fieldsV1:
              f:status:
                f:conditions:
                  .: {}
                  k:{"type":"ContainersReady"}:
           
```
#### Recent failures:
[8/21/2024, 7:58:11 AM ci-kubernetes-node-swap-conformance-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-conformance-ubuntu-serial/1826227077003612160)
[8/21/2024, 7:05:16 AM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu-serial/1826213487563509760)
[8/21/2024, 5:54:16 AM ci-kubernetes-node-swap-ubuntu](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu/1826195871293771776)
[8/21/2024, 3:57:12 AM ci-kubernetes-node-swap-conformance-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-conformance-ubuntu-serial/1826166427053199360)
[8/21/2024, 3:03:09 AM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu-serial/1826152837101391872)

/kind failing-test

/sig node

**Comment by kannon92** [comment]
@iholder101 Can you look into this and see what has happened?

**Comment by iholder101** [comment]
Hey @kannon92! Thanks for tagging me here!

At a first glance, I see this error in some different logs [[1](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-swap-conformance-ubuntu-serial/1826227077003612160/artifacts/n1-standard-2-ubuntu-gke-2204-1-29-v20240820-be01fea2/containerd.log)][[2](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-swap-conformance-ubuntu-serial/1826227077003612160/artifacts/n1-standard-2-ubuntu-gke-2204-1-29-v20240820-be01fea2/kubelet.log)] (I've trimmed the messages a bit for readablity):
> failed to setup network for sandbox \"f43989d6afd90389090d9b3ea8fd4b156c8d391d5090cf3f463625e823fa2f9d\": plugin type=\"ptp\" failed (add): failed to find plugin \"ptp\" in path [/home/containerd/]"

>pod_workers.go:1301] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"sleeping-test-pod-swap-...\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"sleeping-test-pod-swap-9c44p_swap-qos\\\": rpc error: code = Unknown desc = failed to setup network for sandbox: plugin type=\\\"ptp\\\" failed (add): failed to find plugin \\\"ptp\\\" in path [/home/containerd/]\"" pod="swap-qos-2620/sleeping-test-pod-swap-9c44p"

Not sure what this `ptp` network plugin means TBH, I'll continue investigating.

In addition, I wanted to raise attention to the `We're migrating Prow on Aug 21! Expect CI disruption and avoid releases that week` message. I wonder if this migration could have affected these failures. On the other hand, it seems that the fedora lane remains green for some reason..

**Comment by kannon92** [comment]
/priority important-soon

We want to GA swap in 1.32 and this is a blocker for GA.

**Comment by MikeZappa87** [comment]
What is installing the community CNI plugin? The ptp plugin is nothing but a veth netdev with one side in the root netns and the other side in the pod netns. What changed? The path is also odd they usually would be in /opt/cni/bin.

**Comment by kannon92** [comment]
https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/swap/ubuntu-swap-1G-allocation.yaml.

I'm not sure what the config.toml is.

**Comment by kannon92** [comment]
I am not sure what these jobs are using whatever is in the GCP storage bucket.

But I think this is also related to why our ubuntu huge pages is failing (https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-hugepages).

Both have this weirdness in their cloud-init script:

huge pages:

```
runcmd:
  - echo 1 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
  - mount /tmp /tmp -o remount,exec,suid
  - mkdir -p /home/containerd
  - mount --bind /home/containerd /home/containerd
  - mount -o remount,exec /home/containerd
  - mkdir -p /etc/containerd
  - 'curl --fail --retry 5 --retry-delay 3 --silent --show-error -H "X-Google-Metadata-Request: True" -o /home/containerd/cni.template http://metadata.google.internal/computeMetadata/v1/instance/attributes/cni-template'
  - 'curl --fail --retry 5 --retry-delay 3 --silent --show-error -H "X-Google-Metadata-Request: True" -o /etc/containerd/config.toml http://metadata.google.internal/computeMetadata/v1/instance/attributes/containerd-config'
  - 'curl --fail --retry 5 --retry-delay 3 --silent --show-error -o /home/containerd/cni.tgz -L https://dl.k8s.io/network-plugins/cni-plugins-amd64-v0.7.5.tgz'
  - tar xzf /home/containerd/cni.tgz -C /home/containerd --overwrite
  - systemctl restart containerd
```

```
runcmd:
  - mount /tmp /tmp -o remount,exec,suid
  - mkdir -p /home/containerd
  - mount --bind /home/containerd /home/containerd
  - mount -o remount,exec /home/containerd
  - mkdir -p /etc/containerd
  - 'curl --fail --retry 5 --retry-delay 3 --silent --show-error -H "X-Google-Metadata-Request: True" -o /home/containerd/cni.template http://metadata.google.internal/computeMetadata/v1/instance/attributes/cni-template'
  - 'curl --fail --retry 5 --retry-delay 3 --silent --show-error -H "X-Google-Metadata-Request: True" -o /etc/containerd/config.toml http://metadata.google.internal/computeMetadata/v1/instance/attributes/containerd-config'
  - 'curl --fail --retry 5 --retry-delay 3 --silent --show-error -o /home/containerd/cni.tgz -L https://dl.k8s.io/network-plugins/cni-plugins-amd64-v0.7.5.tgz'
  - tar xzf /home/containerd/cni.tgz -C /home/containerd --overwrite
  - systemctl restart containerd
  - 'echo current swappiness: $(sysctl vm.swappiness)'
  - 'echo create swap file'
  - 'fallocate -l 1G /swapfile || true'
  - 'chmod 600 /swapfile'
  - 'mkswap /swapfile'
  - 'swapon /swapfile'
  - 'echo "/swapfile swap swap defaults 0 0" | tee -a /etc/fstab'
  - 'echo swap files'
  - 'swapon --show'
  - 'free -h'
  - 'sudo sed -i "s:console=ttyS0:console=ttyS0 cgroup_enable=memory swapaccount=1:g" /etc/default/grub.d/50-cloudimg-settings.cfg' 
  - 'sudo update-grub'
  - 'sudo reboot' 
```

**Comment by MikeZappa87** [comment]
Those are internal urls so I can't inspect the containerd config.toml. Also those CNI plugins are super old as well.

**Comment by kannon92** [comment]
@mmiranda96 maybe you can look at this? I don't really know why we are using the internal URLs in a cloud init script.

**Comment by kannon92** [comment]
Looking at this, I think I have a fix.

https://github.com/kubernetes/test-infra/pull/33358

**Comment by kannon92** [comment]
That fixed merged and worked!

/close
