### ISSUE TITLE
[Flaking Test] UT Test_InFlightPods

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#126801]
##### Error text:
```
    scheduling_queue_test.go:756: Unexpected diff of backoffQ pod names (-want, +got):
          []string{
        - 	"targetpod",
        + 	"targetpod2",
        - 	"targetpod2",
        + 	"targetpod",
          }
    --- FAIL: Test_InFlightPods/All_Pods_registered_in_inFlightPods_are_enqueued_back_to_activeQ (0.11s)

```

It looks like an order flake.

#### Recent failures:
[2024/8/20 05:00:07 ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1825638697689681920)

/kind flake

**Comment by googs1025** [comment]
Maybe we need to determine the order before comparing
```go
sortOpt := cmpopts.SortSlices(func(a, b string) bool { return a < b })
if diff := cmp.Diff(test.wantBackoffQPodNames, podNames, sortOpt); diff != "" {
	t.Fatalf("Unexpected diff of backoffQ pod names (-want, +got):\n%s", diff)
}
```

**Comment by Rajalakshmi-Girish** [comment]
Also seeing it in our CI https://testgrid.k8s.io/ibm-k8s-unit-tests-ppc64le#periodic-k8s-unit-tests-ppc64le

**Comment by googs1025** [comment]
close this issue, because the PR https://github.com/kubernetes/kubernetes/pull/126802  has been merged. If we still have questions, feel free to open 
/close
