### ISSUE TITLE
Using docker run --group-add to track container disk usage through disk quota

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#12686]
Docker 1.8 introduces a new option --group-add to run command: https://docs.docker.com/reference/commandline/run/

We could use this to add another supplementary gid to the processes of a container, so that we can track the disk usage of a container easily through disk quota. 

cc/ @vishh @bgrant0607

**Comment by erictune** [comment]
In order for this to work, the container has to write all of its files with the supplementary GID as the file's GID.  I don't think we can make it do that (as opposed to using another GID).  Also, even if it could, it would probably not be what people expect when accessing networked storage.  If there were some way to make it use the supplementary GID while in the emptyDir, but the primary GID when using other volume types, it might work.

**Comment by vishh** [comment]
FYI: I'm working on a proposal for disk accounting and eventually disk
scheduling.

**Comment by dchen1107** [comment]
cc/ @adityakali

**Comment by smarterclayton** [comment]
Now that we have FSGroup this in theory is already handled.  We rely on this in openshift to do XFS emptydir quota.
