### ISSUE TITLE
Projected access token CEL mutation support

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#126876]
### What would you like to be added?

I'd like to be able to set some CEL manipulation rules to be applied to projected access tokens after they are generated, but before they are signed.

### Why is this needed?

Some services expect particular properties to be in tokens sent to them. This would allow custom rules to be loaded into the cluster by the cluster-admins to handle these properties.

**Comment by enj** [comment]
The Kube SA token payload is an API that is expected to be stable and consistent across different Kube environments - we cannot introduce a point of fragmentation.  The Kube API server must also be able to validate all the claims set in the token payload, which it cannot do for claims that it does not understand the meaning of.  New claims can be added as long as they meet the criteria above.

/close
