### ISSUE TITLE
Test pure iptables proxy vs userspace proxy.

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#12682]
I/we need to test the new iptables proxy's performance vs the old userspace one.
Previous discussion: https://github.com/kubernetes/kubernetes/pull/9210#issuecomment-130154261 and https://github.com/kubernetes/kubernetes/issues/3760#issuecomment-130493058.

I've been working on a PR for this, so I'm just opening the issue as a seperate space to discuss it.

/cc @thockin @Symmetric

**Comment by BenTheElder** [comment]
@Symmetric I've been playing around with your netserver image, and netperf doesn't seem to be in the path?

**Comment by BenTheElder** [comment]
Hmm, I think I've gotten something wrong in my kubectl call. That really doesn't make sense.
Sorry for the noise @Symmetric, I'll report back here when I figure it out.

**Comment by BenTheElder** [comment]
Figured it out, I didn't have my args split up properly. Should have something working soon.

**Comment by BenTheElder** [comment]
@thockin mostly-automated netperf tests are working now, just need to parse the results and tidy things up. Will open a PR and post data in a bit, heading out for dinner.

**Comment by BenTheElder** [comment]
Here's a sample of plotting (in libre-office) some of the csv export data from my netperf test tool running with the userspace proxy on a vagrant cluster on my laptop.
![test_graph](https://cloud.githubusercontent.com/assets/917931/9267429/ee96acc4-421c-11e5-9ded-73c2b600387b.png)
It still needs work, but it's gotten very late on me and I have to get up and move in tomorrow. 
I'll push my current code and link it here first though.
So far it's pretty automated if a bit hacky, you just need to do:
```shell
NUM_MINIONS=2 cluster/kube-up.sh
contrib/for-tests/netperf-tester/run.sh --number=100 --debug=false --output=$HOME/test.csv
```

**Comment by BenTheElder** [comment]
Code is here: https://github.com/BenTheElder/kubernetes/tree/kube-proxy_test

**Comment by thockin** [comment]
What are the axes and units?  First rule of graphs!!

Do you have an equivalent for iptables proxier?

**Comment by BenTheElder** [comment]
Sorry, units for Y are on the labels, X is the test number (repeatedly runs
a netperf test for a burst of TCP request/response), just a quick example
output, I plan to histogram it later, raw data is in csv.

For the iptables proxier same thing but set up your cluster to be using it.

I'll post real results when I get a chance, I just wanted to show that the
data export was working etc. The final graphs will probably won't look like
that at all. I can either transform the raw results to histogram in the
script or in libreoffice/excel etc.

That was just meant to be a quick update, finished version and results
still to come. Should be back up and running on this tonight and through
the weekend.

**Comment by thockin** [comment]
Great.

From my end:

I have a recipe that has nodeports working in all modes (localhost, VMIP,
external IP, load-balancers, etc).  All external traffic has to be
MASQUERADED, but internal traffic retains source IP.

It also handles DNAT to self.

I am testing UDP now, but that looks good, too (except external traffic
which we don't really support yet).

I have a battery of tests that we can turn into e2e.

I have to figure out the optimal layout of these new rules and then code
them up.

**Comment by BenTheElder** [comment]
Ok. Sounds good :)

Putting my new room and desk etc back together here. Should have a place to
work in a bit. I'm hoping to have some more useful results tonight up
tonight. I want to experiment more with the test settings before I generate
the comparison results though.

**Comment by BenTheElder** [comment]
Still experimenting with the test settings. I'll post the results when I've sorted this out a bit more.

**Comment by BenTheElder** [comment]
Cluster is failing to spin up to complete tests. Will continue in the morning. 
I ran into an issue where the netperf images were run on the same node as well; is there a way to force them to be on different nodes? I haven't found a way to ensure that yet, so far just having 2 workers and nothing else running had taken care of that.

**Comment by thockin** [comment]
If you give your pod a HostPort (any port, doesn't matter) then the
scheduler CAN'T put them on the same node.

**Comment by BenTheElder** [comment]
Thanks, I'll add that.

Cluster is failing when installing pre-requisites on the minions, seems to
be a fedora repo flake, trying one more time then heading to bed to try
again in the morning.

**Comment by thockin** [comment]
I'm gonna see if I can add you to a GCE project I own.  If not, spin up
your own GCE project and I'll personally reimburse you for this work.
Can't be more that $100 bucks, I'd reckon.

**Comment by BenTheElder** [comment]
Ok. Local cluster is coming up smoothly now, will use that for the moment.
Gotta head off soon though, classes start tomorrow(!)
Looks like i should have more than enough time to get this tidied up and
out though, shouldn't be a problem.

**Comment by thockin** [comment]
email me your gmail address and I'll try to add you to a GCE project.
Sorry, I should have done that sooner.

**Comment by BenTheElder** [comment]
sent

**Comment by BenTheElder** [comment]
Quick export of local test results, data is pretty noisy.
Tests with 100 req/rep mode:
![userspace](https://cloud.githubusercontent.com/assets/917931/9299522/b2b5519a-448a-11e5-8f14-afd5ef47b507.png)
![iptables](https://cloud.githubusercontent.com/assets/917931/9299523/b2b574cc-448a-11e5-9cf1-b61c3b3da8d1.png)
Test with 1 second mode:
![userspace-1s](https://cloud.githubusercontent.com/assets/917931/9299621/d4011388-448b-11e5-942d-94af62eefb77.png)
![iptables-1s](https://cloud.githubusercontent.com/assets/917931/9299620/d400f394-448b-11e5-8bfb-3ec61c279c83.png)

I suspect that the results are mostly noisy from running in vagrant on my laptop. Will try GCE next, if that's still too noisy, will look into alternate testing. The test itself should be in pretty good shape though, it's running netperf's TCP_RR.

From [the netperf manual](http://www.netperf.org/netperf/training/Netperf.html):
>Request/response performance is the second area that can be investigated with netperf. Generally speaking, netperf request/response performance is quoted as "transactions/s" for a given request and response size. A transaction is defined as the exchange of a single request and a single response. From a transaction rate, one can infer one way and round-trip average latency.

May need to adjust the test size, those above used `-l -100` (100 req/rep) and `-l 1` (one second) respectively.

**Comment by BenTheElder** [comment]
Getting a lot of connection refused on GCE, been trying to debug. Otherwise have it configured and ready to go, just having commands fail like:
```
kubectl get pods --all-namespaces
error: couldn't read version from server: Get https://<ip address>/api: dial tcp <ip address>:443: connection refused
```

**Comment by BenTheElder** [comment]
Looks like it might be related to https://github.com/kubernetes/kubernetes/issues/12776.

**Comment by BenTheElder** [comment]
Running the test snippet from there, i see the same issues, apiserver and docker are going down for a while then coming back up briefly.

**Comment by BenTheElder** [comment]
Fix works. Noted upstream in #12776. I'll continue testing now.

**Comment by thockin** [comment]
OK.  let me know what I can do

**Comment by BenTheElder** [comment]
Everything is going well. Should have some fresh results and a PR out tonight. Had to do a few things here but back at it now.

**Comment by BenTheElder** [comment]
Posting raw data as it's ready to this gist: https://gist.github.com/BenTheElder/8ad343913fbe876e219a
I'm working on exporting it to friendlier results now, then if it looks good I'll go ahead and tidy up and open that PR with the tool.

**Comment by BenTheElder** [comment]
![gce-netperf-histogram](https://cloud.githubusercontent.com/assets/917931/9320276/09f80c90-4526-11e5-82ec-6fff252c5131.png)

**Comment by Symmetric** [comment]
Are those axes the right way round? I'm reading this as saying that
iptables has a higher mean latency... hopefully the x axis is latency and y
is count (as is normal for a histogram)...

**Comment by BenTheElder** [comment]
those axes are indeed backwards!

**Comment by BenTheElder** [comment]
Updated

**Comment by thockin** [comment]
Is microseconds right?  I expected a much longer tail..

**Comment by BenTheElder** [comment]
*According to netperf: yes. Example output:Throughput Throughput Mean
  Minimum      Maximum      50th         90th         99th         Stddev
    Local  *

*Units                 Latency      Latency      Latency      Percentile
Percentile   Percentile   Latency      CPU    *

*                      Microseconds Microseconds Microseconds Latency
Latency      Latency      Microseconds Util   *

*                                                             Microseconds
Microseconds Microseconds              %      *

*Trans/s    7210.84    138.37       89           4690         123
174          376          116.20       12.24  *

**Comment by BenTheElder** [comment]
hmm emailing ate that:
```
Throughput Throughput Mean         Minimum      Maximum      50th         90th         99th         Stddev       Local  
Units                 Latency      Latency      Latency      Percentile   Percentile   Percentile   Latency      CPU    
                      Microseconds Microseconds Microseconds Latency      Latency      Latency      Microseconds Util   
                                                             Microseconds Microseconds Microseconds              %      
Trans/s    7210.84    138.37       89           4690         123          174          376          116.20       12.24  ```

**Comment by BenTheElder** [comment]
Moved to https://github.com/kubernetes/contrib/pull/10
