### ISSUE TITLE
ValidatingAdmissionPolicy's Validate func returns decision with Evaluation="" when Action is ActionDeny

### ISSUE THREAD

**Issue by piny940** [kubernetes/kubernetes#126866]
### What happened?

This issue is about the `Validate` function in `staging/src/k8s.io/apiserver/pkg/admission/plugin/policy/validating/validator.go`.

In this function, `ValidatingAdmissionPolicy`'s `spec.validations.expression` is evaluated in this line:

```
evalResults, remainingBudget, err := v.validationFilter.ForInput(ctx, versionedAttr, admissionRequest, optionalVars, ns, runtimeCELCostBudget)
```

and if `evalResult` is not `true`, `PolicyDecision`'s `Action` is set to `ActionDeny`:

```
} else if evalResult.EvalResult != celtypes.True {
	decision.Action = ActionDeny
...
```

But `decision.Evaluation` remains empty string.

### What did you expect to happen?

`decision.Evaluation` should be set to `EvalDeny`.

### Kubernetes version

I imported public library

<details>

<summary>go.mod</summary>

```
module k8s-bug-report

go 1.22.5

require (
	k8s.io/api v0.31.0
	k8s.io/apimachinery v0.31.0
	k8s.io/apiserver v0.31.0
)

require (
	github.com/antlr4-go/antlr/v4 v4.13.0 // indirect
	github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a // indirect
	github.com/beorn7/perks v1.0.1 // indirect
	github.com/blang/semver/v4 v4.0.0 // indirect
	github.com/cenkalti/backoff/v4 v4.3.0 // indirect
	github.com/cespare/xxhash/v2 v2.3.0 // indirect
	github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc // indirect
	github.com/emicklei/go-restful/v3 v3.11.0 // indirect
	github.com/felixge/httpsnoop v1.0.4 // indirect
	github.com/fxamacker/cbor/v2 v2.7.0 // indirect
	github.com/go-logr/logr v1.4.2 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/go-openapi/jsonpointer v0.19.6 // indirect
	github.com/go-openapi/jsonreference v0.20.2 // indirect
	github.com/go-openapi/swag v0.22.4 // indirect
	github.com/gogo/protobuf v1.3.2 // indirect
	github.com/golang/protobuf v1.5.4 // indirect
	github.com/google/cel-go v0.20.1 // indirect
	github.com/google/gnostic-models v0.6.8 // indirect
	github.com/google/go-cmp v0.6.0 // indirect
	github.com/google/gofuzz v1.2.0 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/grpc-ecosystem/grpc-gateway/v2 v2.20.0 // indirect
	github.com/imdario/mergo v0.3.6 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/josharian/intern v1.0.0 // indirect
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/mailru/easyjson v0.7.7 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.2 // indirect
	github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/prometheus/client_golang v1.19.1 // indirect
	github.com/prometheus/client_model v0.6.1 // indirect
	github.com/prometheus/common v0.55.0 // indirect
	github.com/prometheus/procfs v0.15.1 // indirect
	github.com/spf13/cobra v1.8.1 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/stoewer/go-strcase v1.2.0 // indirect
	github.com/x448/float16 v0.8.4 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.53.0 // indirect
	go.opentelemetry.io/otel v1.28.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.28.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.27.0 // indirect
	go.opentelemetry.io/otel/metric v1.28.0 // indirect
	go.opentelemetry.io/otel/sdk v1.28.0 // indirect
	go.opentelemetry.io/otel/trace v1.28.0 // indirect
	go.opentelemetry.io/proto/otlp v1.3.1 // indirect
	golang.org/x/exp v0.0.0-20230515195305-f3d0a9c9a5cc // indirect
	golang.org/x/net v0.26.0 // indirect
	golang.org/x/oauth2 v0.21.0 // indirect
	golang.org/x/sync v0.7.0 // indirect
	golang.org/x/sys v0.21.0 // indirect
	golang.org/x/term v0.21.0 // indirect
	golang.org/x/text v0.16.0 // indirect
	golang.org/x/time v0.3.0 // indirect
	google.golang.org/genproto/googleapis/api v0.0.0-20240528184218-531527333157 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240701130421-f6361c86f094 // indirect
	google.golang.org/grpc v1.65.0 // indirect
	google.golang.org/protobuf v1.34.2 // indirect
	gopkg.in/evanphx/json-patch.v4 v4.12.0 // indirect
	gopkg.in/inf.v0 v0.9.1 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
	k8s.io/client-go v0.31.0 // indirect
	k8s.io/component-base v0.31.0 // indirect
	k8s.io/klog/v2 v2.130.1 // indirect
	k8s.io/kube-openapi v0.0.0-20240228011516-70dd3763d340 // indirect
	k8s.io/utils v0.0.0-20240711033017-18e509b52bc8 // indirect
	sigs.k8s.io/apiserver-network-proxy/konnectivity-client v0.30.3 // indirect
	sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd // indirect
	sigs.k8s.io/structured-merge-diff/v4 v4.4.1 // indirect
	sigs.k8s.io/yaml v1.4.0 // indirect
)

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Divyansh200102** [comment]
> ### What happened?
> 
> This issue is about the `Validate` function in `staging/src/k8s.io/apiserver/pkg/admission/plugin/policy/validating/validator.go`.
> 
> In this function, `ValidatingAdmissionPolicy`'s `spec.validations.expression` is evaluated in this line:
> 
> ```
> evalResults, remainingBudget, err := v.validationFilter.ForInput(ctx, versionedAttr, admissionRequest, optionalVars, ns, runtimeCELCostBudget)
> ```
> 
> and if `evalResult` is not `true`, `PolicyDecision`'s `Action` is set to `ActionDeny`:
> 
> ```
> } else if evalResult.EvalResult != celtypes.True {
> 	decision.Action = ActionDeny
> ...
> ```
> 
> But `decision.Evaluation` remains empty string.
> 
> 
> ### What did you expect to happen?
> 
> `decision.Evaluation` should be set to `EvalDeny`.
> 
> ### How can we reproduce it (as minimally and precisely as possible)?
> 
> 
> ### Anything else we need to know?
> 
> _No response_
> 
> ### Kubernetes version
> 
> I imported public library
> 
> <details>
> 
> <summary>go.mod</summary>
> 
> ```
> module k8s-bug-report
> 
> go 1.22.5
> 
> require (
> 	k8s.io/api v0.31.0
> 	k8s.io/apimachinery v0.31.0
> 	k8s.io/apiserver v0.31.0
> )
> 
> require (
> 	github.com/antlr4-go/antlr/v4 v4.13.0 // indirect
> 	github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a // indirect
> 	github.com/beorn7/perks v1.0.1 // indirect
> 	github.com/blang/semver/v4 v4.0.0 // indirect
> 	github.com/cenkalti/backoff/v4 v4.3.0 // indirect
> 	github.com/cespare/xxhash/v2 v2.3.0 // indirect
> 	github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc // indirect
> 	github.com/emicklei/go-restful/v3 v3.11.0 // indirect
> 	github.com/felixge/httpsnoop v1.0.4 // indirect
> 	github.com/fxamacker/cbor/v2 v2.7.0 // indirect
> 	github.com/go-logr/logr v1.4.2 // indirect
> 	github.com/go-logr/stdr v1.2.2 // indirect
> 	github.com/go-openapi/jsonpointer v0.19.6 // indirect
> 	github.com/go-openapi/jsonreference v0.20.2 // indirect
> 	github.com/go-openapi/swag v0.22.4 // indirect
> 	github.com/gogo/protobuf v1.3.2 // indirect
> 	github.com/golang/protobuf v1.5.4 // indirect
> 	github.com/google/cel-go v0.20.1 // indirect
> 	github.com/google/gnostic-models v0.6.8 // indirect
> 	github.com/google/go-cmp v0.6.0 // indirect
> 	github.com/google/gofuzz v1.2.0 // indirect
> 	github.com/google/uuid v1.6.0 // indirect
> 	github.com/grpc-ecosystem/grpc-gateway/v2 v2.20.0 // indirect
> 	github.com/imdario/mergo v0.3.6 // indirect
> 	github.com/inconshreveable/mousetrap v1.1.0 // indirect
> 	github.com/josharian/intern v1.0.0 // indirect
> 	github.com/json-iterator/go v1.1.12 // indirect
> 	github.com/mailru/easyjson v0.7.7 // indirect
> 	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
> 	github.com/modern-go/reflect2 v1.0.2 // indirect
> 	github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822 // indirect
> 	github.com/pkg/errors v0.9.1 // indirect
> 	github.com/prometheus/client_golang v1.19.1 // indirect
> 	github.com/prometheus/client_model v0.6.1 // indirect
> 	github.com/prometheus/common v0.55.0 // indirect
> 	github.com/prometheus/procfs v0.15.1 // indirect
> 	github.com/spf13/cobra v1.8.1 // indirect
> 	github.com/spf13/pflag v1.0.5 // indirect
> 	github.com/stoewer/go-strcase v1.2.0 // indirect
> 	github.com/x448/float16 v0.8.4 // indirect
> 	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.53.0 // indirect
> 	go.opentelemetry.io/otel v1.28.0 // indirect
> 	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.28.0 // indirect
> 	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.27.0 // indirect
> 	go.opentelemetry.io/otel/metric v1.28.0 // indirect
> 	go.opentelemetry.io/otel/sdk v1.28.0 // indirect
> 	go.opentelemetry.io/otel/trace v1.28.0 // indirect
> 	go.opentelemetry.io/proto/otlp v1.3.1 // indirect
> 	golang.org/x/exp v0.0.0-20230515195305-f3d0a9c9a5cc // indirect
> 	golang.org/x/net v0.26.0 // indirect
> 	golang.org/x/oauth2 v0.21.0 // indirect
> 	golang.org/x/sync v0.7.0 // indirect
> 	golang.org/x/sys v0.21.0 // indirect
> 	golang.org/x/term v0.21.0 // indirect
> 	golang.org/x/text v0.16.0 // indirect
> 	golang.org/x/time v0.3.0 // indirect
> 	google.golang.org/genproto/googleapis/api v0.0.0-20240528184218-531527333157 // indirect
> 	google.golang.org/genproto/googleapis/rpc v0.0.0-20240701130421-f6361c86f094 // indirect
> 	google.golang.org/grpc v1.65.0 // indirect
> 	google.golang.org/protobuf v1.34.2 // indirect
> 	gopkg.in/evanphx/json-patch.v4 v4.12.0 // indirect
> 	gopkg.in/inf.v0 v0.9.1 // indirect
> 	gopkg.in/yaml.v2 v2.4.0 // indirect
> 	gopkg.in/yaml.v3 v3.0.1 // indirect
> 	k8s.io/client-go v0.31.0 // indirect
> 	k8s.io/component-base v0.31.0 // indirect
> 	k8s.io/klog/v2 v2.130.1 // indirect
> 	k8s.io/kube-openapi v0.0.0-20240228011516-70dd3763d340 // indirect
> 	k8s.io/utils v0.0.0-20240711033017-18e509b52bc8 // indirect
> 	sigs.k8s.io/apiserver-network-proxy/konnectivity-client v0.30.3 // indirect
> 	sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd // indirect
> 	sigs.k8s.io/structured-merge-diff/v4 v4.4.1 // indirect
> 	sigs.k8s.io/yaml v1.4.0 // indirect
> )
> 
> ```
> 
> </details>
> 
> 
> ### Cloud provider
> 
> <details>
> 
> </details>
> 
> 
> ### OS version
> 
> <details>
> 
> ```console
> # On Linux:
> $ cat /etc/os-release
> # paste output here
> $ uname -a
> # paste output here
> 
> # On Windows:
> C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
> # paste output here
> ```
> 
> </details>
> 
> 
> ### Install tools
> 
> <details>
> 
> </details>
> 
> 
> ### Container runtime (CRI) and version (if applicable)
> 
> <details>
> 
> </details>
> 
> 
> ### Related plugins (CNI, CSI, ...) and versions (if applicable)
> 
> <details>
> 
> </details>
> 

Hi,
I am new to contributing to this repo can you please tell me what all things I should be familiar with to start contributing in kubernetes specifically this issue.
