### ISSUE TITLE
Document removal of KMSv2 and KMSv2KDF feature gates

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#126859]
Is there a related PR to update [k/website](https://github.com/kubernetes/website/) (_dev-1.32_ branch)?

_Originally posted by @sftim in https://github.com/kubernetes/kubernetes/issues/126698#issuecomment-2303017500_

**Comment by Divyansh200102** [comment]
>               Is there a related PR to update [k/website](https://github.com/kubernetes/website/) (_dev-1.32_ branch)?
> 
> _Originally posted by @sftim in https://github.com/kubernetes/kubernetes/issues/126698#issuecomment-2303017500_
>             

Hi,
I am new to contributing to this repository can you please tell me what all things I should be familiar with to start contributing in this repository.

**Comment by sftim** [comment]
> Hi, I am new to contributing to this repository can you please tell me what all things I should be familiar with to start contributing in this repository.

Actually, you need to update a _different_ repository. Visit https://kubernetes.io/docs/contribute/docs/ to learn more.

**Comment by enj** [comment]
> > ```
> >           Is there a related PR to update [k/website](https://github.com/kubernetes/website/) (_dev-1.32_ branch)?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _Originally posted by @sftim in [#126698 (comment)](https://github.com/kubernetes/kubernetes/pull/126698#issuecomment-2303017500)_
> 
> Hi, I am new to contributing to this repository can you please tell me what all things I should be familiar with to start contributing in this repository.

There is already a PR open to fix this: https://github.com/kubernetes/website/pull/47621

/assign aramase

**Comment by aramase** [comment]
Closed with https://github.com/kubernetes/website/pull/47621

/close
