### ISSUE TITLE
describe service endpoints shows endpoints that are not ready

### ISSUE THREAD

**Issue by maciejkra** [kubernetes/kubernetes#126922]
### What happened?

After upgrading from 1.29 to 1.30.2 `kubectl describe service` in the endpoints section shows all endpoints even if pods are not ready and `kubectl get endpoints` is not showing the endpoint.
Before upgrading, all pods that are not ready were not shown in the endpoints section.

### What did you expect to happen?

IP of pods that are not ready should not be shown in `kubectl describe service` Endpoints section.

### How can we reproduce it (as minimally and precisely as possible)?

Make pod readyness probe will fail:
```kubectl get pods pkad-health -o wide
NAME          READY   STATUS    RESTARTS      AGE    IP          NODE             NOMINATED NODE   READINESS GATES
pkad-health   0/1     Running   2 (94m ago)   119m   10.1.0.19   docker-desktop   <none>           <none>
```

In the service describe Endpoints section it should not be visable
```
kubectl describe svc pkad
Name:                     pkad
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 szkolenie=k8s
Type:                     ClusterIP
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.106.116.19
IPs:                      10.106.116.19
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
Endpoints:                10.1.0.19:8080
Session Affinity:         None
Internal Traffic Policy:  Cluster
Events:                   <none>


kubectl get endpoints pkad
NAME   ENDPOINTS   AGE
pkad               121m

```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.2
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

tested on docker desktop and DigitalOcean Kuberentes service.

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by maciejkra** [comment]
I did some additional checks, and I have some doubts about Kubectl in version 1.31 is not to blame here. I have checked it on the older version of Kubectl, and the behavior is as expected.

**Comment by zhifei92** [comment]
> I did some additional checks, and I have some doubts about Kubectl in version 1.31 is not to blame here. I have checked it on the older version of Kubectl, and the behavior is as expected.

I reproduced this issue on the kubectl compiled from the master branch. I'm interested in trying to fix it.

**Comment by chengjoey** [comment]
#124598, `ServiceDescriber` been changed since this pr

cc @aroradaman

**Comment by chengjoey** [comment]
@maciejkra , the different is `kubectl get endpoints ${name}` and `kubectl get endpointslices -l kubernetes. io/ service-name=${name}`

**Comment by zhifei92** [comment]
> #124598, `ServiceDescriber` been changed since this pr
> 
> cc @aroradaman

Is this the expected behavior?

**Comment by chengjoey** [comment]
> Is this the expected behavior?

seems expected behavior , because it has user-facing change:
```
kubectl describe service and ingress will now use endpointslices instead of endpoints
```

**Comment by zhifei92** [comment]
> kubectl describe service and ingress will now use endpointslices instead of endpoints

"I think even though we're using endpointslices, we still need to describe ready endpoints."

**Comment by qingwave** [comment]
I also think it's make sense show the ready endpoints address in the result rather than all, it should keep the same behavior with `describe endpoints`.

We can check the `endpointslices` [ready condition](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#ready) in the describe command.

**Comment by zhifei92** [comment]
> I also think it's make sense show the ready endpoints address in the result rather than all, it should keep the same behavior with `describe endpoints`.
> 
> We can check the `endpointslices` [ready condition](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#ready) in the describe command.

Agree. I'll submit a PR to fix it. If displaying all eps is the expected behavior, I think we need more descriptive documentation to explain this behavior.
