### ISSUE TITLE
Get call to a non-existent namespace returns not-nil object when using the fake client

### ISSUE THREAD

**Issue by aruneshpa** [kubernetes/kubernetes#126906]
### What happened?

When using client-go fake client to Get a resource (in this case, a namespace) that does not exist, the Get call is returning a non nil object along with the not found error.

### What did you expect to happen?

If the resource does not exist, I would expect the returned object to be nil.

### How can we reproduce it (as minimally and precisely as possible)?

```	
	client := fake.NewSimpleClientset()
	ns, err := client.CoreV1().Namespaces().Get(context.Background(), "some-namespace", metav1.GetOptions{})
	if err != nil {
		fmt.Println(err)
	}

	if ns != nil {
		fmt.Println("should not have happened")
	}
	fmt.Println(ns)
```

- When run with v0.31.0:
```
namespaces "some-namespace" not found
should not have happened
&Namespace{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:NamespaceSpec{Finalizers:[],},Status:NamespaceStatus{Phase:,Conditions:[]NamespaceCondition{},},}
```

- When run with v0.30.3:
```
namespaces "some-namespace" not found
nil
```

### Anything else we need to know?

This seems to be an issue specific to client-go version v0.31.0.  The exact same snippet pasted above, when run with v0.30.3 behaves as expected.

### Kubernetes version

<details>
The kubectl version is not really relevant.  The issue is specific to v0.31.0.  The issue is *not* observed in v0.30.3.
</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
$ uname -a
Darwin MW6YR2N7X4 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chengjoey** [comment]
#122892

user-facing change:
```
The "fake" clients generated by `client-gen` now have the same semantics on
error as the real clients; in particular, a failed Get(), Create(), etc, no longer
returns `nil`. (It now returns a pointer to a zero-valued object, like the real
clients do.) This will break some downstream unit tests that were testing
`result == nil` rather than `err != nil`, and in some cases may expose bugs
in the underlying code that were hidden by the incorrect unit tests.
```

**Comment by aruneshpa** [comment]
Thanks so much @chengjoey!  Resolving this issue.
