### ISSUE TITLE
APIServerTracing causing huge memory consumption/memory leak

### ISSUE THREAD

**Issue by lynx-coding** [kubernetes/kubernetes#126918]
### What happened?

Since updating from Kubernetes 1.26.* to 1.29.* we experiences OOM-Kills on control plane nodes.
After some investigation we found that adding `--feature-gates=APIServerTracing=false` to the `kube-apiserver` fixed the issue.
(Found this via pprof/heap of one apiserver: heap dump could be added if needed)

Before the update to 1.29.* the control planes were running with 4GB of memory with the same worklow in the cluster without issues. After the workarround using the feature gate the memory consumption of the whole control plane is not at ~2GB.

### What did you expect to happen?

In case there is an issue with other components, memory consumption of the apiserver should not be that excessive.

### How can we reproduce it (as minimally and precisely as possible)?

We just had the K8s cluster running and saw a permant increase in memory usage of the control plane nodes. And after some time (can not give a specific duration) the OS of the control plane node started to OOM kill processes.

### Anything else we need to know?

Let us know if you need additional information.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
```

</details>

### Cloud provider

on-premise; control-planes are running with 4 CPU cores, 8GB of memory and and NVME discs

### OS version

<details>

```console
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux kube-master01-003 5.10.0-32-cloud-amd64 #1 SMP Debian 5.10.223-1 (2024-08-10) x86_64 GNU/Linux

```

</details>

### Install tools

<details>

```console
$ kubeadm version -o yaml
clientVersion:
  buildDate: "2024-04-16T15:05:51Z"
  compiler: gc
  gitCommit: 55019c83b0fd51ef4ced8c29eec2c4847f896e74
  gitTreeState: clean
  gitVersion: v1.29.4
  goVersion: go1.21.9
  major: "1"
  minor: "29"
  platform: linux/amd64
```

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
$ crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  1.6.31
RuntimeApiVersion:  v1
```

</details>

**Comment by zhifei92** [comment]
> (Found this via pprof/heap of one apiserver: heap dump could be added if needed)
Please provide the pprof, and what is the size of your cluster.

**Comment by lynx-coding** [comment]
As we were not sure if sharing the pprof is secure, we decided to only share screenshots first:

![profile002](https://github.com/user-attachments/assets/7ab015a2-4dd4-4889-b072-ededbacd6fc5)
![flamegraph_screenshot](https://github.com/user-attachments/assets/65d38f79-70a1-4575-96a5-ba888ce78c34)

From this information we found the this [line of code](https://github.com/kubernetes/apiserver/blob/v0.31.0/pkg/storage/storagebackend/factory/etcd3.go#L318) which pointed us to the mentioned feature flag.

We sometimes see etcd connection timeouts in the apiserver logs, maybe this could be related but should not cause this behaviour.

> size of your cluster
- 5 control planes
- ~100 worker nodes
- ~1700 Pods

**Comment by chengjoey** [comment]
Can you provide the pprof without `APIServerTracing`, so could compare the two?

**Comment by lynx-coding** [comment]
Sure, the current pprof with `--feature-gates=APIServerTracing=false` set:
![profile004](https://github.com/user-attachments/assets/77e33f56-32a5-4aea-9ece-4fe2b0cf0269)
![flamegraph_new_screenshot](https://github.com/user-attachments/assets/f456f18c-cdf6-47b5-87d1-870840443c65)

**Comment by dims** [comment]
cc @dashpole

**Comment by dashpole** [comment]
I believe this is https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4226.  Sounds like we may need to backport some of the dependency bumps

**Comment by dashpole** [comment]
We need to apply the workaround in https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5190.  It should be simple, but needs to be backported to 1.27

**Comment by dims** [comment]
> but needs to be backported to 1.27

all versions starting 1.27 right @dashpole ?

**Comment by lynx-coding** [comment]
Thanks for taking care of this so quickly

**Comment by dashpole** [comment]
@dims yes.  All versions starting 1.27.

**Comment by dashpole** [comment]
Actually, this only needs to be backported to v1.29. At 1.28, we were using v0.35.0 of otelgrpc, which did not include metrics at the time.

**Comment by dashpole** [comment]
Cherry-picks:

* https://github.com/kubernetes/kubernetes/pull/126983
* https://github.com/kubernetes/kubernetes/pull/126984
* https://github.com/kubernetes/kubernetes/pull/126985

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/129220
