### ISSUE TITLE
Bump DefaultKubeBinaryVersion to 1.32

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#126946]
Bump DefaultKubeBinaryVersion to 1.32.

ref: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/version/base.go#L69

This is blocking feature promotions in 1.32 and we should look to resolve ASAP

Tracking PR: https://github.com/kubernetes/kubernetes/pull/126977

8 tests are breaking, 5 in integration, 3 in unit.

It would also be great to think of alternatives so we do not need to manually update this on every release.

/sig api-machinery
/triage accepted

**Comment by BenTheElder** [comment]
we have https://github.com/kubernetes/kubernetes/pull/126604 and https://github.com/kubernetes/kubernetes/pull/126977 but both seem blocked

cc @jpbetz @liggitt

**Comment by Jefftree** [comment]
> we have #126604 and #126977 but both seem blocked
> 
> cc @jpbetz @liggitt

Yep, #126977 builds on top of #126604 so the first one can be closed.

**Comment by BenTheElder** [comment]
longterm: https://github.com/kubernetes/kubernetes/issues/126686
