### ISSUE TITLE
--exclude-webhook-validation-ns kube-api option

### ISSUE THREAD

**Issue by francislance** [kubernetes/kubernetes#126944]
### What would you like to be added?

`--exclude-webhook-validation-ns=kube-system,...` or any similar exclusion as an option in API static Pod

### Why is this needed?

It would be more productive that in case we wanted to configure `--enable-admission-plugins` `--admission-control-config-file` we have the option to add `--exclude-webhook-validation-ns=kube-system,...` which straight away exempts kube-system and other namespaces we desired to be exempted. This is to help simplify especially when we are in early stage of constructing Image Validation Webhook configurations and the application. 

The feature would also ensure that when we change the API static Pod, there is no impact that could lead into it not able to put up because of any mistake in the configurations or validation logics.

Having a global flag like `--exclude-webhook-validation-ns` would simplify the process of ensuring that critical namespaces are exempt from webhook policies. Currently, we must implement namespace-based filtering within each webhook or rely on custom labels/selectors, which can be error-prone and inconsistent across different webhooks.

**Comment by cici37** [comment]
/close
I am not convinced on if it makes sense to have a separate option for this kind of use case. If you don't want your webhook to be applied on certain namespace, adding `matchCondition` in your webhook will do so. If you wanna conditional apply your webhook, using [Validation Admission Policy](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/). Thank you :)

**Comment by francislance** [comment]
Thanks @cici37 for the quick response. Yeap what you said make sense and would definitely work. 

What I am looking at is an explicit exclusion regardless of what inside any admission policies. This is to ensure that those critical pods such as those inside kube-system are not checked against any policy that could break it because of typo or any human mistakes.
