### ISSUE TITLE
Probe can not visit  port by name

### ISSUE THREAD

**Issue by hurf** [kubernetes/kubernetes#12698]
When using probe, define the port by number, it works. But if the port is defined by name like below, it doesn't work.

    containers:
      - name: nginx
        image: nginx
        ports:
          - name: testport
            containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: testport

it seems [findPortByName](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/prober/prober.go#L258) should return `ContainerPort` other than `HostPort`.

**Comment by brendandburns** [comment]
Closed by #12699
