### ISSUE TITLE
`"failed to initialize nfacct client" err="nfacct sub-system not available"` logged when `k8s.io/kubernetes/pkg/proxy/metrics` module is initialized as non-root user

### ISSUE THREAD

**Issue by brandond** [kubernetes/kubernetes#126951]
### What happened?

The `k8s.io/kubernetes/pkg/proxy/metrics` module now logs two errors during module initialization. Simply loading the module will cause two errors to be printed to stderr if the code is not run as root, or is run on a node without nfacct support. 

This is due to `newNFAcctMetricCollector` being used when creating Prometheus metrics during module variable initialization, which calls `klog.Errors()` if the nfacct client cannot be initialized.

This regression was introduced by:
* https://github.com/kubernetes/kubernetes/pull/125866

K3s ships all the various Kubernetes components bundled in a single multicall binary, which means that our `kubectl` now logs these errors when it is run as a non-root user.

### What did you expect to happen?

No error logs on module init

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/brandond/kube-proxy-repro

```golang
import (
	"k8s.io/kubernetes/cmd/kube-proxy/app"
)

func main() {
	_ = app.NewProxyCommand()
}
```

### Anything else we need to know?

cc @aroradaman @danwinship

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.0+k3s1
Kustomize Version: v5.4.2
Server Version: v1.31.0+k3s1
```

</details>

### Cloud provider

n/a

### OS version

n/a

### Install tools

n/a

### Container runtime (CRI) and version (if applicable)

n/a

### Related plugins (CNI, CSI, ...) and versions (if applicable)

n/a

area/proxy
sig/network

**Comment by brandond** [comment]
area/proxy

sig/network

**Comment by aroradaman** [comment]
I was about to fix this, this initialization happens even in the unit tests as well 😔.

**Comment by brandond** [comment]
@aroradaman thanks for the quick response! Do you think you'll have a patch that we could use temporarily for k3s? We were considering just removing the `klog.Errors()` call for our initial 1.31 release, unless you have a better suggestion.

**Comment by aojea** [comment]
@brandond  can you confirm https://github.com/kubernetes/kubernetes/pull/126952 is fine?
