### ISSUE TITLE
kubelet should only trigger relevant pod workers for pod spec changes

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#12691]
Currently, kubelet receive a set of desired pods through the update channel, and blindly triggers all pod workers to sync as well as performing global cleanup. This is inefficient because a single pod change would engage N workers (goroutines), assuming there are N desired pods. Each worker performs a series inspection which swamps Docker, slowing down the reaction to the actual pod change. I did a simple experiment which showed that there was at least ~30% less SyncPod calls when only the relevant pod workers were called.

Kubelet should react to different type of pod changes according and dispatch the work to relevant pod worker:

```
ADD -->  pod admission -->  pod worker dispatcher
UPDATE --> update validation  -->  pod worker dispatcher
REMOVE --> kill pod worker/cleanup
```
The cleanup work includes removing orphaned pod directories/volumes etc.

In today's kubelet, all the work is done in SyncPods (pod admission/validation/dispatcher and global cleanup). I recently broke down the code in `SyncPods` into functions to isolate the different utilities (#12560) as the precursor for eliminating `SyncPods`. If we separate the each component, there is no need for the `SyncPods` function to exist.

In addition, kubelet needs to know what kind of spec change it receives (ADD/UPDATE/REMOVE). In fact, the [kubelet/config] module (which watches various sources) supports all different update types, however, for reason unknown to me, kubelet is restricted to only receive the SET operation with all pods included in one update. Due to the lost of information, kubelet is forced to [derive the sync type](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/pod_manager.go#L125) later in the code (reverse-engineering!). One way to solve this is to restore the operation types and use them properly.

Known caveats: 
 - Handle kubelet restarts
 - Handle mirror pods

Marking this p1 because this is a relative low-hanging fruit with potential to improve kubelet's performance significantly.

**Comment by yujuhong** [comment]
/cc @vishh 

FYI, we are merging graceful termination #9165 soon, which will shift the responsibility of killing containers a bit.

Difference: 

Graceful deletion:
   1. receives a pod spec change (UPDATE), delegate to the corresponding pod worker
   2. pod worker kills the pod/containers

Non-graceful deletion:
   1. receives a REMOVE change
   2. let the cleanup routine kill the pod/containers

**Comment by yujuhong** [comment]
This is part of #12540

**Comment by smarterclayton** [comment]
One thing to check on non-graceful deletion - it will still be possible for a pod to get deleted without a corresponding update to metadata.terminationGracePeriodSeconds.  We will record spec.terminationGracePeriodSeconds into the container metadata, but we should be sure we still go through the graceful path even if we get a pure etcd delete (no graceful from the server).  We should only  kill containers with period 0 if the user explicitly requests it via an API call.

**Comment by yujuhong** [comment]
#13003 has been merged. To sum up, it does two things:
 1. Use incremental update, handle ADD/UPDATE/REMOVE operation differently, and trigger each pod worker individually (`SyncPods` function has been removed completely).
 2. Create a separate goroutine to "kill" containers, so that it no longer blocks the sync loop. Note that this has gotten worse after the graceful termination period was introduced, and was exacerbated by not handling REMOVE in a batch by (1), so I had to fix in the PR. In general, we should move all long, blocking calls out of the loop.

After this change, kubelet should react to pod creations/updates faster because we don't blindly sync all pods anymore. This is especially true when the number of pods on the node is high, causing unnecessary resource contention. My pod creation test shows 20% pod creation latency improvement for creating 40 pods on the node. If we raise the apiserver client QPS limit, the difference could be higher.

Also, it should be easier to trace pod changes grepping SyncLoop in kubelet.log . E.g.,
```
I0827 18:56:21.891783    3601 kubelet.go:1771] SyncLoop (ADD): "monitoring-heapster-v8-ybvk4_kube-system"
I0827 18:56:22.047398    3601 kubelet.go:1771] SyncLoop (ADD): "monitoring-influx-grafana-v1-je4aq_kube-system"
I0827 18:56:32.047547    3601 kubelet.go:1785] SyncLoop (periodic sync)
```

I've been watching jenkins to make sure the PR doesn't break anything. @kubernetes/goog-node, if you find any bug or performance issue, let me know. Thanks.
