### ISSUE TITLE
kubernetes v1.31.0: TypedNewDelayingQueue should be renamed to NewTypedDelayingQueue

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#126908]
### What happened?

TypedNewDelayingQueue in k8s.io/client-go/util/workqueue does not follow the naming convention in the same package.

### What did you expect to happen?

The naming pattern observed in k8s.io/client-go/util/workqueue suggests that TypedNewDelayingQueue should be renamed to NewTypedDelayingQueue.
Because we have NewTypedDelayingQueueWithConfig, and other functions are named in such rules, I think this is an obvious conversion tooling error and/or cut and paste error.

### How can we reproduce it (as minimally and precisely as possible)?

There is no reproduction steps.

### Kubernetes version

<details>

kubernetes v1.31.0

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
Added in https://github.com/kubernetes/kubernetes/pull/124263.
/cc @alvaroaleman @sttts

**Comment by alvaroaleman** [comment]
I can change this but then that of course breaks everyone who uses the current name. Is that something we want to do?

**Comment by tatsuhiro-t** [comment]
Adding NewTypedDelayingQueue and deprecating TypedNewDelayingQueue keep backward compatibility if that is a way to go.
