### ISSUE TITLE
[KEP-4639] Specify SELinux behavior for image volumes

### ISSUE THREAD

**Issue by carlory** [kubernetes/kubernetes#126956]
Related to https://github.com/kubernetes/website/pull/47588 and https://github.com/kubernetes/kubernetes/pull/126806

SIG storage meeting notes: https://docs.google.com/document/d/1-8KEG8AjAgKznS9NFm3qWqkGyCHmvU6HVl0sk5hwoAE/edit#heading=h.9rsna5zrjwc

From me:

https://github.com/kubernetes/website/pull/47588#discussion_r1727171579 It is related to image volume plugin and selinux. Is it a known limitation of all the volume plugins when using selinux? I have a different opinion. If two pods don't share the same mountpoint (hostpath), they can run the same node when the selinux is enabled. the current implementation of  cri-o is sharing the same hostpath when two pods use the same image volume. More details about my idea: https://github.com/kubernetes/kubernetes/pull/126806#discussion_r1724826814 

From @jsafrane:

Sharing each volume between namespaces is kind of natural. Sharing PVs not possible but sharing image quite common.

From @gnufied: 

Although for most volume plugins it is true that, they can't be mounted with 2 different selinux context on same node, we want to understand why is this not possible for Imagevolume source. For a traditional storage persistent storage plugins - this limitation is underlying limitation of storage backend/Linux kernel etc.

For ImageVolume source, it seems like a simple solution which unpacks image to two different hostpath would work and not run into this limitation. @haircommander can you specify, why this limitation exists for ImageVolume plugins?

From @haircommander:

we choose to keep it simple and follow the lead of other volume types. supporting multiple selinux types would mean making more complicated the way we mount the image into the container AFAIR. But agreed we can chat about this elsewhere, in the meantime for the purposes of this PR: this is consistent with behavior of other volume plugins and is expected behavior.

Let's discuss the SELinux behavior for image volumes in this issue.

cc @gnufied @jsafrane @saschagrunert @haircommander

/sig node
/sig storage

**Comment by carlory** [comment]
@haircommander I moved this issue into kubernetes repo.

**Comment by haircommander** [comment]
thanks!

**Comment by carlory** [comment]
Copid from kep:

```
SELinux
Traditionally, the container runtime is responsible of applying SELinux labels to volume mounts, which are inherited from the securityContext of the pod or container on container creation. The same will apply to OCI volume mounts.
```

As https://github.com/cri-o/cri-o/pull/8521 merged, do we need to change the KEPs to reflect the new behavior? @saschagrunert
