### ISSUE TITLE
Deprecated  package is used and the secret file error message is unformated 

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/kubernetes#126986]
### What happened?

package ioutil is deprecated from Go 1.16 onward and is used in our code . Some of the finding i got is in `pkg/volume/secret/secret_test.go`. We should update it by removing the deprecated one with the most suitable for it without harming the code.

file `pkg/volume/secret/secret.go` is having error message under GetVolumeName Function Which is Capitalize Where as fmt.Errorf doesnot allow capitalization of any error message.

### What did you expect to happen?

Update the deprecated package with the updated package 
Updating Error message in correct form

### How can we reproduce it (as minimally and precisely as possible)?

Try to update the package with the recent and updated package in place of ioutils in GO . and check whether code is working fine
change the capitalization of message  to lower case

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
None
</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
Previously: https://github.com/kubernetes/kubernetes/issues/100367

/area code-organization

https://github.com/kubernetes/kubernetes/issues/100367#issuecomment-1405382516

cc @liggitt @dims

**Comment by dims** [comment]
please feel free to file a PR and work with the sig on specific things like this issue calls out. we just won't start accepting bulk updates as @liggitt mentions in his comment that @BenTheElder points to.
