### ISSUE TITLE
Update the versionize-docs.sh script to process the types_swagger_doc.go file

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#12690]
The [versionize-docs.sh script](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fkubernetes%2Fkubernetes%2Fblob%2Fmaster%2Fbuild%2Fversionize-docs.sh&sa=D&sntz=1&usg=AFQjCNFvneV33AbecKPiXdysx8otECI04g) needs to be updated so that it processes this new doc before it gets moved/published to gh-pages so that urls that point to HEAD get redirected so that they instead to point to the corresponding version of the docs on k8s.io (gh-pages), for example, links to ```http://releases.k8s.io/HEAD/docs/```*specificdochere.md*

#10933

**Comment by thockin** [comment]
@caesarxuchao @krousey anyone have bandwidth for this change this week?  I am buried.

**Comment by krousey** [comment]
@thockin Probably not. I'm trying to finish up a few things before I take time off to move.

**Comment by caesarxuchao** [comment]
I can do this later this week.

**Comment by caesarxuchao** [comment]
@RichieEscarez, are we going to expose types_swagger_doc.go in gh-pages?

**Comment by caesarxuchao** [comment]
@RichieEscarez, I've sent #12965 to fix the links in the definitions.html directly. Do you think we still need fix types_swagger_doc.go?

**Comment by RichieEscarez** [comment]
@caesarxuchao, its not yet clear to me how or what the process is for generating the API output for gh-pages using the types_swagger_doc.go file but if types_swagger_doc.go is the source thats used to  generate the HTML output for the definitions.html file, then it sounds like we are covered here.

@nikhiljindal, can you help clarify?

**Comment by caesarxuchao** [comment]
Hey @RichieEscarez, we use types.go to generate types_swagger_doc.go, then use types_swagger_doc.go to generate swagger spec (api/swagger-spec), then use the swagger spec to generate the definitions.html and operations.html.

Currently the versionize-docs.sh only touches the md files in docs/ and examples/. I don't think it's necessary to versionize the links in a go file. @nikhiljindal, what do you think?

**Comment by nikhiljindal** [comment]
Yes. We do not surface api/swagger-spec as part of versionized docs on gh-pages. If we were, then it would make sense to versionize types_swagger_doc.go.

As things are right now, we only surface definitions.html on gh-pages so just versioning that should be enough.

**Comment by caesarxuchao** [comment]
This is fixed. I'm going to close it.

@RichieEscarez feel free to reopen it if you think otherwise :)

**Comment by RichieEscarez** [comment]
Thanks @caesarxuchao! Nope, nothing more from me. Sorry I didnt follow up and ensure this was closed on #12965 merge.
