### ISSUE TITLE
kube-proxy hope listen all zero addresses in dual-stack env without health check error

### ISSUE THREAD

**Issue by shuoyans** [kubernetes/kubernetes#126960]
### What happened?

I have deployed a latest 1.31 Kubernetes dual-stack cluster, and cube-proxy is running in IPVS mode
Also created a dual-stack service with `externalTrafficPolicy: Local`:
```
  ...
  externalTrafficPolicy: Local
  healthCheckNodePort: 30256
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  ...
```
In kube-proxy’s configuration, —nodeport-addresses is unset. (we know this strongly is recommended in 1.31, but we don’t expect to just listen on certain specific ip, just want to listen on all interface)

And the error in kube-proxy's log:
```
 "Opening healthcheck" service="default/service-1" port=30256
 "Opening healthcheck" service="default/service-1" port=30256
 "Failed to start healthcheck" err="listen tcp 0.0.0.0:30256: bind: address already in use" node="xxxxxxx" service="default/service-1" port=30256
```

And the cause of this problem is the way how kube-proxy handles health check nodePortAddresses in dual-stack.

There are some previous discussions about this issue:
https://github.com/kubernetes/kubernetes/issues/114702
https://github.com/kubernetes/kubernetes/issues/122899
But still can't solve our problem or meet our needs.

### What did you expect to happen?

In [#123105](https://github.com/kubernetes/kubernetes/pull/123105), setting `—nodeport-addresses` to the value `"primary"`, which means only listening for NodePort connections on the node's primary IPv4 and/or IPv6 address, may solve the address problem. 

But in some scenarios (some users do have this kind of needs), we still hope to listen on all interfaces, and this is the current default behavior in IPVS mode, and when you create a dual-service, there is always the problem mentioned above.

It’s a quite long-standing question for kube-proxy, but still unsolved, since ipv6 "::" also includes ipv4 on Linux https://github.com/kubernetes/kubernetes/issues/122899, and then the “address already bind” error seems to be inevitable, and in this situation, `—nodeport-addresses` is still helpless.

One possible solution I could figure out is:
When a dual-satck service change comes, if nodePortAddress have all zero addresses in IPv6 ip family, only open the healthcheck in IPv6's proxier.

But this may require a large change to the code: the IPv4 proxier also need to watch the change in IPv6, and pass relative parameters to its healthcheck server.

### How can we reproduce it (as minimally and precisely as possible)?

In a dual-stack cluster environment, `--nodeport-addresses` is not configured.
Additionally, a dual-stack LoadBalancer Service with healthCheckNodePort is created.

### Kubernetes version

<details>

```console
$ kubectl version
# 1.31.0
```

</details>

### Cloud provider

<details>
nil
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by danwinship** [comment]
> There are some previous discussions about this issue:
> #114702
> #122899
> But still can't solve our problem or meet our needs.

Yes, that is why #114702 is still open; because the bug is not fixed yet.
Closing this one as a duplicate.
/close
