### ISSUE TITLE
Race condition of kubelet/kubeproxy may cause short ingress broken when lost connection to kubeapi

### ISSUE THREAD

**Issue by syy6** [kubernetes/kubernetes#127065]
### What would you like to be added?

We are running K8s to host some network connection sensitive workload, in our workload, we have dedicated Node to host HAProxy. In front of these HAProxy Node, we have IaaS Load Balance, it would dispatch the traffic from external to them and detects the health status via health check. And our kubeapi is some other place, like in other VPC behind the LB.
In some rare case, we see our HAProxy Node may lost the connection to kubeapi, such connection lost would not cause issue, but if it’s over the node-monitor-grace-period(default as 40 sec) in kube-controller-manager, then the Node status in kubeapi would become unhealthy. But since the Node to kubeapi connection is broken, then it’s also fine.
But when the Node resumes the connection to kubeapi, since kubelet and kubeproxy has its own re-try interval for the connection, then we see a race condition here. 
If kubelet first resumes the connection to kubeapi and report healthy Node status, then kubeproxy gets the update and everything is fine.
But if kubeproxy first resumes the connection to kubeapi, then it would get the unhealthy node status. In this case, it would remove the Endpoint Slice for HAProxy. And likely, then kubelet would updates the Node status back to healthy and then kubeproxy would receives this status in the next update. We see, if this case happens, normally it would be ~7 sec, the Endpoint Slice would be removed and added back. Since the LB in front of the HAProxy node can’t detect such short change via health check, it would dispatch the traffic to this Node, but it would fail.
We suggest for this case, if kubeproxy can wait for some interval to get the Node update the status to avoid such race condition problem.

### Why is this needed?

It can help K8s to host network very sensitive connection application, even in case Kubelet/kubeproxy lost connection to kubeapi, then a impact to ingress can be avoided.

**Comment by aojea** [comment]
> In some rare case, we see our HAProxy Node may lost the connection to kubeapi,

does this mean that ALL the communication from the node, including the pods running on the node,  to the apiserver is lost?

If you have a lost of connectivity from the node for more than 50 seconds that seems a big problem compared to the 7 second gap

> node-monitor-grace-period(default as 40 sec)

this default has been changed recently to 50 sec https://github.com/kubernetes/kubernetes/pull/126287 , check if you are having some symptom consequence of the problem described on the issue related

**Comment by syy6** [comment]
Thanks @aojea, we changed the  node-monitor-grace-period to 50 sec, as we met with #121793, the time is not matched with  HTTP2_PING_TIMEOUT_SECONDS+HTTP2_READ_IDLE_TIMEOUT_SECONDS
And yes, it means all the connection from the Node including Pod on the Node lost connection to apiserver, like in our case, the Node->NAT Gateway->some network->LB->kubeapi, there is some issue happens on the LB of the kubeapi, then the connection is blocked.
Such 50+ sec connection lost, would be problem, but during this time, the external connection to the LB and then to the HAProxy Node still can work. We see it as tolerance, but problem occur when connection to kubeapi back, that's somehow tricky, resume the connection to kubeapi would cause some unnecessary issue.

**Comment by thockin** [comment]
While I agree with @aojea ("having a control plane disconnected frequently for such amount of time is the main problem") I also see how this behavior is not pleasant.

First thought was to use `externalTrafficPolicy: Local` but that's not right.  It will fall-back on ready+terminating endpoints if no ready+nonterminating are available, but it will not fall back on nonready+nonterminating (which sadly, we discussed and decided not to implement, damn).

You can maybe set `service.spec.publishNotReadyAddresses`, which will ignore pod readiness for these endpoints?  Can you look into that @syy6 ?  (credit where due: this was suggested at sig-net call, not my idea but I like it :)

**Comment by syy6** [comment]
Thanks @aojea & @thockin , thanks for the suggestion, but to be honest, I think we can't use service.spec.publishNotReadyAddresses, since it means if the Pod(HAProxy) is in issue with some reason, it still would be exposed to the Load Balancer, it may cause some issue here, thanks!

**Comment by aojea** [comment]
@syy6 do you have only one haproxy pod in node as ingress?

**Comment by aojea** [comment]
> Hi @aojea , yes, we keep the node with one dedicated HAProxy Pod

but then you have an HA problem , you should have at least 2 replicas and the LB implement the failover

**Comment by syy6** [comment]
Hi @aojea, yes, I mean in the one Node, we only deploy one HAProxy Pod, but we have several Node with HAProxy Node.  We are using K8s on openstack, the LB's health check is based on kubeproxy's health endpoint(healthz), so my understanding is if I set service.spec.publishNotReadyAddresses to true, the LB would always got a health status even the HAProxy's Pod is down.

**Comment by aojea** [comment]
> but we have several Node with HAProxy No

😅  sorry, I misunderstood the scenario

> if I set service.spec.publishNotReadyAddresses to true, the LB would always got a health status even the HAProxy's Pod is down.

yes

I was thinking you can use the pod HostPort feature in this case, and open a health endpoint in your Pod for your LB to probe, this way you shorcut services and keep exposing the haproxy pod ... HostPort will also guarantee two Pods don't land in the same node

**Comment by thockin** [comment]
Is there anything to be done with this one?  I am not sure what a reasonable path would be.
