### ISSUE TITLE
Deprecated package in use

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/kubernetes#127080]
What happened?
package 	"github.com/golang/protobuf/proto" is deprecated and is used in our code . Some of the finding i got is at 21 files such as roundtrip.go, any.go and many. We should update it by removing the deprecated one with the most suitable for it without harming the code.

What did you expect to happen?
Update the deprecated package with the updated package 

How can we reproduce it (as minimally and precisely as possible)?
Try to update the package with the recent and updated package in place of github.com/golang/protobuf/proto in GO . and check whether code is working fine

**Comment by niranjandarshann** [comment]
I would like to work on this issue. May I assign it?

**Comment by neolit123** [comment]
> I would like to work on this issue. May I assign it?

i believe this package is deprecated but should not be removed.

/sig api-machinery

/sig architecture
(code org)

**Comment by dims** [comment]
/close

please see https://github.com/kubernetes/kubernetes/issues/96564
