### ISSUE TITLE
No copyright owner information in repository licensing

### ISSUE THREAD

**Issue by Falcion** [kubernetes/kubernetes#127077]
This may not be a problem at all, but I was confused by the fact that the licenses (both `LICENSE` and `LICENSES/LICENSE`) do not indicate the copyright date and the name of the owner of this copyright.

https://github.com/kubernetes/kubernetes/blob/534003da8a5df5d90f1e0c9daaf3bce03a50fecc/LICENSE#L190
https://github.com/kubernetes/kubernetes/blob/534003da8a5df5d90f1e0c9daaf3bce03a50fecc/LICENSES/LICENSE#L193

In the second file (link attached above), you indicate at the beginning that "Kubernetes licensed under".

At the same time, your program code actively indicates copyrights and links to the license:

https://github.com/kubernetes/kubernetes/blob/534003da8a5df5d90f1e0c9daaf3bce03a50fecc/staging/src/k8s.io/metrics/hack/tools.go#L4-L20

And at the same time, next to this code there is another LICENSE file in which they are not indicated data:

https://github.com/kubernetes/kubernetes/blob/534003da8a5df5d90f1e0c9daaf3bce03a50fecc/staging/src/k8s.io/metrics/LICENSE#L189

If this is standard practice for this project, then I apologize and can close this topic.

**Comment by neolit123** [comment]
> This may not be a problem at all, but I was confused by the fact that the licenses (both LICENSE and LICENSES/LICENSE) do not indicate the copyright date and the name of the owner of this copyright.

this is the official APACHE 2.0 statement that indicates how a LICENSE header should be placed in files.

it's under:

https://github.com/kubernetes/kubernetes/blob/534003da8a5df5d90f1e0c9daaf3bce03a50fecc/LICENSE#L179

> At the same time, your program code actively indicates copyrights and links to the license:

which is valid use of the COPYRIGHT headers.

> And at the same time, next to this code there is another LICENSE file in which they are not indicated data:

this is also a valid LICENSE file with an appendix on how to apply the license to individual files.

---

to summarize, there is no issue.

LICENSE files are the source-of-truth documents that contain the actual OSS LICENSE which may or may not include an APPENDIX on how to apply a COPYRIGHT header to individual source code files.

you can google more on this topic.

/close
