### ISSUE TITLE
Document graceful deletion

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#12701]
With #9165 merging the docs need to be updated to reflect the impact.

**Comment by bgrant0607** [comment]
From #12747:

Should mention preStop hooks and link to https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/container-environment.md from pods.md

Should update the relevant section of https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/production-pods.md

**Comment by smarterclayton** [comment]
Added a commit to that pull with both of these

On Sep 17, 2015, at 2:22 PM, Brian Grant <notifications@github.com> wrote:

From #12747 <https://github.com/kubernetes/kubernetes/pull/12747>:

Should mention preStop hooks and link to
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/container-environment.md
from pods.md

Should update the relevant section of
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/production-pods.md

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12701#issuecomment-141174163>
.

**Comment by smarterclayton** [comment]
This was fixed in the merged pull.
