### ISSUE TITLE
CEL unit tests - `TestFilter` (`filter_test.go`) + `AuthorizeWithSelector` Subtests Incorrectly Passing @ master due to CEL environment caching

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/kubernetes#127174]
### What happened?

In attempting to bump the `DefaultKubeBinaryVersion` semver version [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/version/base.go#L69) as part of a necessary PR for v1.32 - https://github.com/kubernetes/kubernetes/pull/126977 we are seeing an issue where changing this version seems to cause the `TestFilter` unit test in [staging/src/k8s.io/apiserver/pkg/admission/plugin/cel/filter_test.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/cel/filter_test.go#L134) to fail with the following test cases failing:
- test_authorizer_error_using_fieldSelector_with_1.30_compatibility 
- test_authorizer_allow_resource_check_with_all_fields 
- test_authorizer_allow_resource_check_with_parse_failures
- test_authorizer_allow_resource_check_with_all_fields,_without_gate

**EDIT: See https://github.com/kubernetes/kubernetes/issues/127174#issuecomment-2338722300 for updated root cause understanding**

~~In root causing the issue, it seems that currently CEL has some environment logic that can allow CEL features to be used (eg: `authorizer`) even when the feature gate required for that CEL feature is not enabled. In `v1.31` this was not an issue but in bumping the `DefaultKubeBinaryVersion` to v1.32 this comparison now has the issue where CEL will allow/rely-on a feature (the specific feature causing the test breaking being `AuthorizeWithSelector`) but the feature gate supporting that feature is not enabled. See code below for the logic that does this:~~

~~https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/cel/environment/environment.go#L261-L265~~

~~Currently the above logic uses `||` in `allowedByFeatureGate || allowedByVersion` which means that in cases where a feature gate is not enabled the associated CEL feature/library is still usable. This is causing an issue in `TestFilter` where tests that test the `authorizers` feature/library are failing now as CEL attempt to use `AuthorizeWithSelector` but the feature is actually not enabled.~~

~~[staging/src/k8s.io/apiserver/pkg/cel/environment/base.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/cel/environment/base.go#L152-L171)~~

~~This CEL logic for the `authorizer` lib // AuthorizeWithSelectors feature gate support was added in https://github.com/kubernetes/kubernetes/pull/125571. Specifically the changes to:~~
- ~~staging/src/k8s.io/apiserver/pkg/cel/environment/base.go~~
- ~~staging/src/k8s.io/apiserver/pkg/cel/environment/environment.go~~
- ~~staging/src/k8s.io/apiserver/pkg/admission/plugin/cel/filter_test.go~~

~~We have two options IIUC:~~ 
- ~~CEL can support all libraries/features but fail when attempting to run the feature in the case the feature gate is not enabled~~
- ~~CEL can deny using libraries/features when attempting to run a feature gate that is not enabled.~~

~~I was hoping to get some feedback from the authors/owners of the original PR as well as `AuthorizeWithSelectors` to understand what the intention was for the `if allowedByFeatureGate || allowedByVersion` comparison and CEL library support. I believe the correct folks to followup here with would be @liggitt and @deads2k to understand the best path forward here (or to iron out any issues with the current understanding). I'm happy to make the necessary changes, wanted to understand what the preferred logic is here. Thanks!~~

### What did you expect to happen?

I expected to be able to bump `DefaultKubeBinaryVersion` s/v1.31/v1.32 without any unit test failures.

### How can we reproduce it (as minimally and precisely as possible)?

Modify the code [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/version/base.go#L69) to bump `DefaultKubeBinaryVersion` and then run the tests at `staging/src/k8s.io/apiserver/pkg/admission/plugin/cel/filter_test.go`

**Comment by aaron-prindle** [comment]
Related:
https://github.com/kubernetes/kubernetes/pull/126977#issuecomment-2332601137

> the TestFilter/test_authorizer_error_using_fieldSelector_with_1.30_compatibility failure means that the compatibility version passed explicitly into MustBaseEnvSet in that test isn't actually being honored as expected (if the test result is breaking when the default compatibility version changes from 1.31 to 1.32)

Likely the root cause identified is incorrect in the initial description.

**Comment by aaron-prindle** [comment]
I was able to root cause the TestFilter issues, TLDR the test is broken/incorrect @ master but CEL env caching is masking the failure. I will put a gist here, still in the process of compiling a more comprehensive set of trace/debug information (w/ debugger screenshots, etc.).

unit test issues - TestFilter: 
TestFilter is currently broken @ master as well as compat-132 (the PR) BUT it is hidden by CEL's env catching. @ master, 1.30 is the default compatibility version. When the first test in the TestFilter test suit runs (`valid syntax for object`), it runs w/ compatVersion 1.30 and that first test runs creates an env with the AuthorizeWithSelector feature disabled which is then used env IS CACHED for the all future tests using compatVersion=1.30, notably - `test authorizer error using fieldSelector with 1.30 compatibility`. In practice this means that the enable call set in the test: ```             enableSelectors: true, # <--- this             compatibilityVersion: v130, ``` is ignored. This means in the call here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/cel/environment/environment.go#L261-L265 `allowedByFeatureGate` is incorrectly false when it should be true. If you run the test standalone/hermetically: eg
```
if tc.name != "test authorizer error using fieldSelector with 1.30 compatibility" {                 t.SkipNow()             }
```
you get the same error you get in the compat-132 branch.  This also occurs if you set `test authorizer error using fieldSelector with 1.30 compatibility` to use 1.29 instead of 1.30.  This shouldn’t affect what the test is supposed to be testing (enabled: true, AuthorizeWithSelector same feature gate status in 1.29 and 1.30) but you get into the test failure code path as the env isn’t cached for 1.29 from previous tests as it isn’t the default compatibilityVersion (1.30 is for `master` branch). 


Still outlining the proper fix, currently the issues as I see them are: 
- at least in tests, the CEL env catching causes tests relying on toggling a feature enabled to at times (if already cached) not have that set in practice. Not sure how high priority this is or if such cache invalidation is actually possible in normal k8s usage. Perhaps a way to clear the cache between test could be an option. 
- As a # of TestFilter tests @ master are currently incorrectly passing at master IIUC due to the CEL env caching hiding the failures, likely the correct fix is that the CEL environment.go logic below should be adjusted: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/cel/environment/environment.go#L261-L265
```
if allowedByFeatureGate || allowedByVersion { 
```
 The test @ master explicitly sets feature enabled true and the compatVersion s.t. this case will succeed but it expects it not to succeed

**Comment by liggitt** [comment]
Thanks for digging... that's... a tangle 🤦 

> if allowedByFeatureGate || allowedByVersion {  // should be likely changed to &&

We definitely do not want to change that. The entire point of allowing by feature gate is to opt in via feature setting to something that is not yet auto-enabled by version.

**Comment by liggitt** [comment]
I think the more correct fix is to address the env caching and init ordering in CEL construction.

**Comment by aaron-prindle** [comment]
PR with fix: https://github.com/kubernetes/kubernetes/pull/127254

**Comment by aaron-prindle** [comment]
Fixed with: https://github.com/kubernetes/kubernetes/pull/127254

Closing
