### ISSUE TITLE
Scheduler tests: use testing loggers

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#127124]
### What would you like to be added?

Use `NewLogger` or `NewTestContext` from `k8s.io/klog/ktesting` in pkg/scheduler tests.

### Why is this needed?

In most tests, we are using `context.Background()`. Using a testing logger allows us to associate the scheduler logs to a specific test.

**Comment by alculquicondor** [comment]
/sig scheduling
/triage accepted
@dom4ha can help with this

**Comment by satyampsoni** [comment]
I have some time next week to contribute on it, if this is not important. I can work on this. wdys @alculquicondor

**Comment by dom4ha** [comment]
Hi @satyampsoni , I'm actually already on it. thanks

**Comment by alculquicondor** [comment]
We should also check `test/integration/scheduler` and `test/integration/scheduler_perf`.
