### ISSUE TITLE
Add a constants.go to podresources

### ISSUE THREAD

**Issue by lengrongfu** [kubernetes/kubernetes#127189]
### What would you like to be added?

Current when i use `PodResourcesLister` API, we need handwriting a unixSocketPath `"/var/lib/kubelet/pod-resources/kubelet.sock"`.

### Why is this needed?

 We hope add a constants.go to provide this content, like `deviceplugin/v1beta1/constants.go`.

**Comment by ffromani** [comment]
Thanks for filing this issue. I agree the current state is not the user friendlier.

the problem here is the path is constructed from the kubelet option `--root-dir`, and this prevents us to add a meaningful constant.
