### ISSUE TITLE
Audit feature gates with multiple definitions

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#127160]
Certain feature gates like `RetryGenerateName` are defined in multiple places https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L267 and https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/features/kube_features.go#L193 but if we search for the feature it is only used in apiserver https://github.com/search?q=repo%3Akubernetes/kubernetes%20RetryGenerateName&type=code.

This kind of feature can be just defined in apiserver/pkg/features/kube_features.go and pkg/features/kube_features.go can just have a reference to it like https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L990.

We should do a sweep for all of them and deduplicate if possible

- [x] https://github.com/kubernetes/kubernetes/pull/127161
- [x] https://github.com/kubernetes/kubernetes/pull/127186
/sig architecture

**Comment by CodeDiego15** [comment]
It's true.

**Comment by omerap12** [comment]
Hey @Jefftree , may I help with that?

**Comment by omerap12** [comment]
Hey @Jefftree , may I help with that?
/assign

**Comment by Adarsh-verma-14** [comment]
@Jefftree , now I will raised PR only for `RetryGenerateName` and will be looking for this type of feature for removing duplication.

**Comment by Jefftree** [comment]
/close

Fixed by two PRs:

- [x] https://github.com/kubernetes/kubernetes/pull/127161
- [x] https://github.com/kubernetes/kubernetes/pull/127186
