### ISSUE TITLE
support set default dns ndots in kubelet

### ISSUE THREAD

**Issue by yangyefei90** [kubernetes/kubernetes#127137]
# What would you like to be added?
support set default dns ndots in kubelet
such as --dns-default-ndtos=2

# Why is this needed?
For ultra-large-scale clusters, there are hundreds of thousands of nodes and millions of pods. At the same time, a centralized DNS architecture is adopted. All DNS requests will be sent to the central DNS service cluster. At this time, each pod will be resolved once more or less, which will have a great impact on the pressure of the DNS server. The ndots configuration can determine whether to resolve the original domain name first and then splice it, or to splice it first and then resolve it, which will effectively affect the number of DNS resolutions for each pod. For this scenario, we prefer a unified default configuration instead of requiring users to configure DNS ndots in the pod, so that users do not need to understand the logic here, and it will not cause greater pressure on the DNS server.

**Comment by yangyefei90** [comment]
Resubmit later

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/1dbf0830c59038822f37eaf5a1d4f7583f1a1081/pkg/kubelet/network/dns/dns.go#L412-L413

The default dns options for kubelet is hardcoded. 

It will be override by pod dns option, and you have to use some admission controllers like https://kyverno.io/policies/other/add-ndots/add-ndots/ to change its default.

/cc @aojea

**Comment by aojea** [comment]
@yangyefei90 you can achieve the same not configuring the `clusterDNS` option

The defaultDNS options only apply if you defined that 

https://github.com/kubernetes/kubernetes/blob/2108e54f5249c6b3b0c9f824314cb5f33c01e3f4/pkg/kubelet/network/dns/dns.go#L400-L420

if not it will fall through and it will use the resolv.conf you passed as parameters or the one in the host

I think that is better for these power admins that need this customization to handle their own resolv.conf with all the options , than use  kubelet config as a resolv.conf templater

**Comment by pacoxu** [comment]
As @aojea said, we can config `clusterDNS` to be empty list and edit local `/etc/resolv.conf` to use your local DNS options like `options ndots:3`.

For this workaround, you have to add the cluster dns to local if you want to use it. I am not sure if it has some side effects.
```
[root@node ~]# cat /etc/resolv.conf
nameserver 192.168.1.29
nameserver 10.96.0.10
options ndots:3
```

**Comment by thockin** [comment]
In the past we have discussed a per-clustrer ot per-namespace DNS default config, but we decided not to since we have per-pod config and webhooks.  I know everyone hates webhooks, but we have MutatingAdmissionPolicy coming which should make it much nicer too.

As to the question on sig-net about providing a custom resolv.conf, I am not convinced.  `GetPodDNS` calls `getHostDNSConfig` which reads a file - that might be the host's /etc/resolv.conf or some other file - it doesn't care.  Then we force set the options (`dnsConfig.Options = defaultDNSOptions` where `defaultDNSOptions = []string{"ndots:5"}`), so the only real config we have is per-pod.  

So our options are:
1) use a webhook (or MAP when it is ready) to set dnsConfig per pod
2) add a whole new API for this which basically does a subset of MAP
3) add node-level config for this, which leads to pods getting a different experience on different nodes (and I doubt sig-node would be happy with, @SergeyKanzhelev )

> For ultra-large-scale clusters, there are hundreds of thousands of nodes

I'd love to hear more about this.  I have heard of some in the 10s of thousands, but not 100s of thousands.

**Comment by SergeyKanzhelev** [comment]
> add node-level config for this, which leads to pods getting a different experience on different nodes (and I doubt sig-node would be happy with, @SergeyKanzhelev )

indeed, more we can do per-pod the better. Operator and vendors wouldn't typically know what is the best default config.

**Comment by zengyuxing007** [comment]
In my opinion, using webhook is an incorrect choice, as webhooks can't guarantee the execution order and compatibility between multiple webhooks, and it also reduces the overall stability. Opening default configuration options is the best choice, rather than the current hard coding. DNS Server and DNS configurations should only be known to system / kubernetes administrators, and the personnel in charge of deploying business Pod are not concerned about these.

**Comment by aojea** [comment]
@zengyuxing007 there are multiple options, webhooks is just one option, Validation Mutation will be another option without the problems of webhooks, alpha in 1.31
There is also another option that you can pass a custom resolv.conf to the kubelet to use as template for your Pods

**Comment by zengyuxing007** [comment]
> Validation Mutation ??

Validation or mutatingwebhookconfigurations ? 


> There is also another option that you can pass a custom resolv.conf to the kubelet to use as template for your Pods
It's a good idea, but the template now just for "default" dnsPolicy, and the  default dnsPolicy (if you not defined it) is "ClusterFirst",  it is a bit strange that the dnsPolicy: "default" needs to be explicitly specified when defining a pod.

**Comment by aojea** [comment]
> About "Validation Mutation will be another option ", I'm not sure which one you are referring to.
> validating and mutating admission webhook ? Isn't it still a webhook?

https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3962-mutating-admission-policies

> If there are multiple webhooks, the final pod yaml may become unpredictable.

that applies independently of this, no? if there is something changing the dnsconfig it does not matter if you have a functionality that `support set default dns ndots in kubelet` if it will be overriden by the webhook

> It's a good idea, but the template now just for "default" dnsPolicy, and the default dnsPolicy (if you not defined it) is "ClusterFirst", it is a bit strange that the dnsPolicy: "default" still needs to be explicitly specified when defining a pod.

sorry but I don't fully follow what you mean here

**Comment by zengyuxing007** [comment]
> > About "Validation Mutation will be another option ", I'm not sure which one you are referring to.
> > validating and mutating admission webhook ? Isn't it still a webhook?
> 
> https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3962-mutating-admission-policies
> 
> > If there are multiple webhooks, the final pod yaml may become unpredictable.
> 
> that applies independently of this, no? if there is something changing the dnsconfig it does not matter if you have a functionality that `support set default dns ndots in kubelet` if it will be overriden by the webhook
> 
> > It's a good idea, but the template now just for "default" dnsPolicy, and the default dnsPolicy (if you not defined it) is "ClusterFirst", it is a bit strange that the dnsPolicy: "default" still needs to be explicitly specified when defining a pod.
> 
> sorry but I don't fully follow what you mean here

if your pod's dnsPolicy using "ClusterFirst", the resolv.conf your supply for kubelet which not effect for this pod.

**Comment by aojea** [comment]
I understand what you want, but you need to come with a solution that works with existing workloads, if you have some suggestion feel free to open a KEP or a shared doc or an email thread in the sig network mailing list to discuss the approach and the technical details of your proposal

**Comment by thockin** [comment]
I'm not going to say don't open a KEP, but I don't think we're interested in a per node solution like a kubelet config, and we have webhooks, and gatekeeper, andvalidating admission policy now, and mutating admission policy soon, so anything more bespoke than that is questionable.

**Comment by dghubble** [comment]
I think everyone asking just wants a way to set `ndots: 1` across a cluster, to avoid the performance issues of 5. Per-workload dnsConfig then becomes a mechanism for rare workloads want 5 ndots.

If you're at an organization that already mandates apps use FQDNs for cluster local DNS resolution and setting ndots to 1 in every workload (various enforcement mechanisms), the next logical step is some mechanism for it to be the cluster-wide default.

Per-node isn't anyone's goal as far as I can tell. It's just one possible means of addressing a hardcoded default that's undesired by many.

**Comment by thockin** [comment]
Our options are:

1) change the default, which inevitably will break people
2) allow enlightened clusters to opt-in
3) define core/v2 API and change the default 

Given that (1) is not happening and (3) is an enormous effort, how best to do (2)?  We have a slew of mechanisms that already exist, defining a new mechanism seems unfounded.

**Comment by dghubble** [comment]
To allow enlightened clusters to opt-in, a distro could ship a Kubelet image with the default patched out, and let users pick btw them? Non-ideal and conformance probably disapproves unless ageement is reached. Having a flag or config in `KubeletConfiguration` seems the conventional choice to be adjust a hardcoded default. Does that imply the work of 3?

I get the concern that nodes might configure it differently and that could be confusing, but that argument applies to all the  kubelet configurables (e.g. I can configure node shutdown grace periods or resolveconf's differently). But as an operator, we tend to not do that. Moreover, it doesn't seem like enough to settle the matter and keep it hardcoded.

**Comment by thockin** [comment]
Distributions can do anything they want, but it's already possible to force a value via the mutating admission systems (and getting easier with MAP).  That's my main point.  Adding another way of defaulting is MORE confusing than using the existing ones.

Or, and it's always possible, I am missing some important aspect of this discussion?

**Comment by dghubble** [comment]
I spent a while with the `MutatingAdmissionPolicy` alpha and I see your point. If this will soon be configuable via a higher-level policy, its relieves the pressure for Kubelet to offer a way to configure its behavior. The policy is more complex than a toggle it would have been, but I agree its nice to be able to make this global.

To save others the trouble and provide a working solution:

```yaml
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: default-dns-ndots
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments", "statefulsets", "daemonsets"]
        operations:  ["CREATE", "UPDATE"]
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        resources: ["jobs", "cronjobs"]
        operations:  ["CREATE", "UPDATE"]
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: "JSONPatch"
      jsonPatch:
        expression: >
          [
            JSONPatch{
              op: "add",
              path: "/spec/template/spec/dnsConfig",
              value: {
                "options": [
                  {
                    "name": "ndots",
                    "value": "1"
                  }
                ]
               }
            }
          ]
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: default-dns-ndots
spec:
  policyName: default-dns-ndots
  matchResources:
```

Workloads that set a custom value still use their custom value. Requires alpha feature gates in v1.32, so it'll be a while before this makes it to AKS, GKE, EKS and the like. But hopefully it graduates.

**Comment by thockin** [comment]
Thanks for that!
