### ISSUE TITLE
Status of APIServingWithRoutine gate

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes#127181]
### What happened?

The code says this (staging/src/k8s.io/apiserver/pkg/features/kube_features.go):

```go
	APIServingWithRoutine: {Default: false, PreRelease: featuregate.Alpha},
```

While the comment says this (staging/src/k8s.io/apiserver/pkg/features/kube_features.go):

```go
	// owner: @linxiulei
	// beta: v1.30
	//
	// Enables serving watch requests in separate goroutines.
	APIServingWithRoutine featuregate.Feature = "APIServingWithRoutine"
```

So..., what happened? The feature is still Alpha or it is a Beta?

### What did you expect to happen?

Be consistent about the features we add or change.

### How can we reproduce it (as minimally and precisely as possible)?

Read the code.

### Kubernetes version

1.30.0

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tengqm** [comment]
According to the changelog:

```
Disabled a previously on-by-default optimization for the API server where each **watch** response
used a dedicated goroutine. The `APIServingWithRoutine` feature gate has been demoted from beta to alpha,
and is now off by default. ([#126470](https://github.com/kubernetes/kubernetes/pull/126470), [@benluddy](https://github.com/benluddy)) [SIG API Machinery and Scalability]
```

This feature has been demoted from Beta to Alpha. That is fine. We need to revise the code comment then.

**Comment by neolit123** [comment]
/sig api-machinery
(not sure  who owns it per se)

**Comment by liangyuanpeng** [comment]
not worry, i think this can be resolved with https://github.com/kubernetes/kubernetes/issues/127181

**Comment by Adarsh-verma-14** [comment]
> According to the changelog:
> 
> ```
> Disabled a previously on-by-default optimization for the API server where each **watch** response
> used a dedicated goroutine. The `APIServingWithRoutine` feature gate has been demoted from beta to alpha,
> and is now off by default. ([#126470](https://github.com/kubernetes/kubernetes/pull/126470),
> [@benluddy](https://github.com/benluddy)) [SIG API Machinery and Scalability]
> ```
> 
> This feature has been demoted from Beta to Alpha. That is fine. We need to revise the code comment then.

I found same like this inconsistency between the comment and the actual feature gate definition for APIServingWithRoutine in kube_features.go due to this PR:https://github.com/kubernetes/kubernetes/pull/126481

**Comment by Adarsh-verma-14** [comment]
I want to work on that if triage accepted.

**Comment by Jefftree** [comment]
Looks like this comment should be updated to alpha based on #126481. Thanks for catching. 

@Adarsh-verma-14 if you'd like to raise a PR to fix the comment that'd be great!

**Comment by Adarsh-verma-14** [comment]
> Looks like this comment should be updated to alpha based on #126481. Thanks for catching.
> 
> @Adarsh-verma-14 if you'd like to raise a PR to fix the comment that'd be great!

sure
