### ISSUE TITLE
Port apiserver, apiextensions-apiserver & kcm features to versioned

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#127159]
As part of https://github.com/kubernetes/kubernetes/issues/126926, we need to port all kubernetes features from unversioned to versioned. 

https://github.com/kubernetes/kubernetes/pull/126791 ports over all `pkg/kube_features.go` features but we have other features defined in apiserver, apiextensions-apiserver, and kube-controller-manager

We have quite a few features defined in apiserver that need to be ported (https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L987-L1048).

https://github.com/kubernetes/kubernetes/pull/127009 is an example of a feature port and promotion. 

/triage accepted
/sig api-machinery
/help

**Comment by omerap12** [comment]
@Jefftree is it ok that I take it on?
/assign

**Comment by Jefftree** [comment]
@omerap12 Of course! Feel free to reply here or ping me on slack if you need help.

**Comment by liangyuanpeng** [comment]
@omerap12   I want to working for apiextensions-apiserver if you don't mind, thanks you!
/assign

**Comment by liangyuanpeng** [comment]
@omerap12  hi, this issue need to work for three component: apiserver, apiextensions-apiserver, and kube-controller-manager, and i'm working for  the ` apiextensions-apiserver` (also can working for all components)

so you can work for `apiserver` and `kube-controller-manager`.

**Comment by omerap12** [comment]
Oh ok @liangyuanpeng  ,  thank you!  :) 
/assign

**Comment by Jefftree** [comment]
This is fixed. Thanks all!

/close
