### ISSUE TITLE
error: unable to upgrade connection: error dialing backend: dial tcp 127.0.0.1:25241: connect: connection refusedssh

### ISSUE THREAD

**Issue by hubcomsix** [kubernetes/kubernetes#127106]
### What happened?

# CurrentBehavior 
connect: connection refusedssh 

### What did you expect to happen?

# ExpectedBehavior 
kubectl works fine 

### How can we reproduce it (as minimally and precisely as possible)?

ALL VERSION

### Kubernetes version

ALL

### Cloud provider

ALL

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by thisisharrsh** [comment]
Hi @hubcomsix, could you please provide some more details on the issue that you are facing.

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
