### ISSUE TITLE
 [Failing Test] Strange ci-benchmark-scheduler-perf-master behavior

### ISSUE THREAD

**Issue by macsko** [kubernetes/kubernetes#127245]
### Which jobs are failing?

ci-benchmark-scheduler-perf-master

### Which tests are failing?

Interestingly, we get benchmark results for all of the test cases, but the job is somehow failing (see [testgrid](https://testgrid.k8s.io/sig-scalability-benchmarks#scheduler-perf)). 

### Since when has it been failing?

6th September. No changes in scheduler_perf since 26th August.

### Testgrid link

https://testgrid.k8s.io/sig-scalability-benchmarks#scheduler-perf

### Reason for failure (if possible)

I have no idea what's going on with the test. Tests give the correct results and populate the [perf-dash](https://perf-dash.k8s.io/#/?jobname=scheduler-perf-benchmark&metriccategoryname=Scheduler&metricname=BenchmarkPerfResults&Metric=SchedulingThroughput&Name=Unschedulable%2F5000Nodes%2F200InitPods%2F10000Pods%2Fnamespace-2&extension_point=not%20applicable&plugin=not%20applicable&result=not%20applicable) dashboard. 

### Relevant SIG(s)

/sig scheduling

**Comment by pohly** [comment]
/assign

The first failed test case is:
```
=== FAIL: test/integration/scheduler_perf BenchmarkPerfScheduling/SchedulingCSIPVs/5000Nodes_5000Pods (unknown)
```

That should have caused the per-test log output to be preserved, which might have had more information, but it's not under the artifacts.

Something isn't quite right with output handling - will check.

**Comment by pohly** [comment]
SchedulingCSIPVs/5000Nodes_5000Pods has 48 as threshold. In https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1833184953530060800/build-log.txt, it has:
```
name                                                  SchedulingThroughput/Average
PerfScheduling/SchedulingBasic/5000Nodes_10000Pods-6                                                 351 ± 0%

name                                                  SchedulingThroughput/Perc50
PerfScheduling/SchedulingBasic/5000Nodes_10000Pods-6                                                 383 ± 0%

name                                                  SchedulingThroughput/Perc90
PerfScheduling/SchedulingBasic/5000Nodes_10000Pods-6                                                 509 ± 0%

name                                                  SchedulingThroughput/Perc95
PerfScheduling/SchedulingBasic/5000Nodes_10000Pods-6                                                 515 ± 0%

name                                                  SchedulingThroughput/Perc99
PerfScheduling/SchedulingBasic/5000Nodes_10000Pods-6                                                 518 ± 0%

name                                                  runtime_seconds
PerfScheduling/SchedulingBasic/5000Nodes_10000Pods-6                                                44.1 ± 0%

```

Why is the threshold so low?

**Comment by pohly** [comment]
https://github.com/kubernetes/kubernetes/pull/125534 changed how `go test` output is processed. The difference between 0e4cf67e9..204936037 (working/not working) includes that.

I think we now hit https://github.com/gotestyourself/gotestsum/issues/413#issuecomment-2169193288.

**Comment by pohly** [comment]
@macsko : how much longer are you willing to wait before we revert?

There have been some discussions around how to fix this in gotestsum, but no conclusion yet.

**Comment by macsko** [comment]
It's not that urgent until something bad happen with scheduling performance and we don't get an alert.

**Comment by sanposhiho** [comment]
Welcome back, green lights! :)

<img width="931" alt="Screenshot 2024-11-22 at 10 55 15" src="https://github.com/user-attachments/assets/a2d7f326-69ae-4cf9-8271-3d7feb3b5300">
