### ISSUE TITLE
We should have a default k8s version for multinode docker cluster

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#12725]
Currently user has to manually specify it. In most cases it will be our most current major release.

@brendandburns

**Comment by resouer** [comment]
The release of gcr.io/google_containers:hyperkube is a bit slower than k8s release. So maybe the last one of latest release?

**Comment by resouer** [comment]
I'm also wondering if there's any way to update default version automatically? (seems e2e test will be need in this case)
