### ISSUE TITLE
Cleanup Job e2e helper functions (fail fast wait functions and don't use deprecated functions)

### ISSUE THREAD

**Issue by mimowo** [kubernetes/kubernetes#127295]
I would like to cleanup / improve the code in `test/e2e/framework/job/wait.go`. In particular:
1. `WaitForJobComplete` and `WaitForJobFailed` can fail fast - e.g. we wait for JobComplete condition, if we observe JobFailed we can fail immediately, the Job is not expected to do that. It is wasteful, especially when running the tests locally, to wait 15min if the Job fails after a couple of seconds.

2. `wait.PollImmediate` used in `WaitForJobFailed` is now deprecated, use `PollUntilContextTimeout`

I think these could be two PRs, but I combine them in a single issue as closely related in a theme.

**Comment by kaisoz** [comment]
/assign 

I'll take this one if it's ok for you guys :blush:

**Comment by carlory** [comment]
Hi @kaisoz @mimowo please use `Eventually` or `Consistently` due to https://github.com/kubernetes/kubernetes/issues/115164
