### ISSUE TITLE
Headless service end point update problem

### ISSUE THREAD

**Issue by yvzsrt** [kubernetes/kubernetes#127234]
### What happened?

I have a problem about headless service.

I have a statefulset redis app on my 3 node cluster, as you see I shutdown node1, now redis-node-1 is in terminating state
```
kubectl get pods -A -o wide | grep redis
mynamespace   redis-node-0                                    3/3     Running            0                    18m     10.244.248.4     ha3-node2
mynamespace   redis-node-1                                    3/3     Terminating        0                    68m     10.244.230.119  ha3-node1
mynamespace   redis-node-2                                    3/3     Running            0                    67m     10.244.192.208   ha3-node3
```
I have two services, redis and redis-headless
In redis-headless 10.244.230.119 is still in endpoints
```
kubectl describe endpoints  -n mynamespace redis-headless
Name:         redis-headless
Namespace:    mynamespace
Subsets:
  Addresses:          10.244.192.208,10.244.230.119,10.244.248.4
```
For redis service (clusterIP) endpoints are OK. Is this behaviour normal, how to solve for headless?
k8s version: v1.27.15 (edited) 

### What did you expect to happen?

headless service end point should be updated as the node goes down.

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce it you can install redis cluster on kubernetes. 

### Anything else we need to know?

I've tested same scenario with nginx but headless ep updated immediately as expected.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.15", GitCommit:"fb63712e1d017142977e88a23644b8e48b775665", GitTreeState:"clean", BuildDate:"2024-06-11T20:04:38Z", GoVersion:"go1.21.11", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.15", GitCommit:"fb63712e1d017142977e88a23644b8e48b775665", GitTreeState:"clean", BuildDate:"2024-06-11T19:56:02Z", GoVersion:"go1.21.11", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux ha2-node1 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by niranjandarshann** [comment]
@yvzsrt  this indicates the problem may be related to how Redis or the StatefulSet configuration handles pod termination, specifically in combination with Redis. Can you check the pod yaml file.

**Comment by chengjoey** [comment]
Does the spec of the headless service you created contain  `selector`?

**Comment by niranjandarshann** [comment]
@yvzsrt What i have noticed
 under spec
  ```
  **terminationGracePeriodSeconds: 30**
```

The teminationgraceperiod is 30  seconds and if you want immediately then i think it should be 0. Then i think it should work.

**Comment by yvzsrt** [comment]
Thank for replies.
here are the selectors:

```
redis-headless
  selector:
    app.kubernetes.io/instance: bb-suite-edge-voltha
    app.kubernetes.io/name: redis
```

```
redis
  selector:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: bb-suite-edge-voltha
    app.kubernetes.io/name: redis
```

**Comment by yvzsrt** [comment]
@chengjoey  when all nodes are UP (so all redis instances), all endpoints are seen healthy so there is no problem about label matching. 

Here is a test from other version of kubernetes: v1.23.17

All cluster nodes are UP and in Ready status:

```
NAME       STATUS   ROLES                  AGE    VERSION
ha-node1   Ready    control-plane,master   234d   v1.23.17
ha-node2   Ready    control-plane,master   234d   v1.23.17
ha-node3   Ready    control-plane,master   234d   v1.23.17
```
All end points are OK
```
sepon@ha-node1:~$ kubectl -n voltha-1 describe ep redis-1-headless redis-1 | grep Address
  Addresses:          172.16.109.214,172.16.14.228,172.16.44.217
  NotReadyAddresses:  <none>
  Addresses:          172.16.109.214,172.16.14.228,172.16.44.217
  NotReadyAddresses:  <none>
```

When one node becomes NotReady:

```
NAME       STATUS     ROLES                  AGE    VERSION
ha-node1   Ready      control-plane,master   234d   v1.23.17
ha-node2   NotReady   control-plane,master   234d   v1.23.17
ha-node3   Ready      control-plane,master   234d   v1.23.17
```

Endpoints of Redis servis is OK but end points of redis-headless is not updated:
```
sepon@ha-node1:~$ kubectl -n voltha-1 describe ep redis-1-headless redis-1 | grep Address; kubectl get nodes
  Addresses:          172.16.109.214,172.16.14.228,172.16.44.217
  NotReadyAddresses:  <none>
  Addresses:          172.16.14.228,172.16.44.217
  NotReadyAddresses:  172.16.109.214
```
As you see pod 172.16.109.214 is in NotReady status but it is still in headless end point list

**Comment by yvzsrt** [comment]
Output:
```
sepon@ha-node1:~$ kubectl get svc -n voltha-1 redis-1-headless -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: redis-1
    meta.helm.sh/release-namespace: voltha-1
  creationTimestamp: "2024-08-13T15:57:14Z"
  labels:
    app.kubernetes.io/instance: redis-1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-15.5.3
  name: redis-1-headless
  namespace: voltha-1
  resourceVersion: "29753158"
  uid: 128396b4-4917-4d87-8136-8117c637895c
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: tcp-sentinel
    port: 26379
    protocol: TCP
    targetPort: redis-sentinel
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: redis-1
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
I noticed the "  publishNotReadyAddresses: true" parameter? Could it be related with that? This parameter doesn't exist in redis service.

**Comment by aojea** [comment]
>   publishNotReadyAddresses: true

hehe, is exactly that, statefulset use to use that option, that indicates that , no matter what, that endpoint will be considered as ready (despite is not)

**Comment by yvzsrt** [comment]
Hmm, then this is not a bug, i will try without this parameter.
Thanks for your help.
In bitnami's redis yaml this parameter exists. I'm not sure why they use this.
I'll post that repository.

**Comment by aojea** [comment]
> In bitnami's redis yaml this parameter exists. I'm not sure why they use this.

most common use case is to bootsrap the clusters, as there may depend on some leader and there is a chicken an egg problem you can not select a leader if you don't know the members of the cluster ... don't know if is this case though
