### ISSUE TITLE
Strange Behavior when creating pods and RC v1.0.1

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#12723]
Configuration

Version

    core@ip-10-20-30-35 / $ kube-apiserver --version
    Kubernetes v1.0.1

Components Health

    core@ip-10-20-30-35 ~ $ kubectl get cs
    NAME                 STATUS    MESSAGE              ERROR
    controller-manager   Healthy   ok                   nil
    scheduler            Healthy   ok                   nil
    etcd-0               Healthy   {"health": "true"}   nil

Environment Variables

    KUBE_APISERVER_OPTS="--bind-address=0.0.0.0 \
     --address=0.0.0.0 \
     --etcd_servers=http://10.20.30.35:4001 \
     --service-cluster-ip-range=10.200.0.0/16 \
     --etcd-prefix="/cluster1/username/registry" \
     --logtostderr=true \
      --profiling=true \
      --insecure-port=8080 \
      --v=2"
     
    KUBE_CONTROLLER_MANAGER_OPTS="--logtostderr=true \
     --master=http://0.0.0.0:8080 \
     --v=2"

    KUBE_SCHEDULER_OPTS="--logtostderr=true \
    --master=http://0.0.0.0:8080 \
    --v=2"

ETCD Output

    core@ip-10-20-30-35 ~ $ etcdctl -C=http://10.20.30.35:4001 ls --recursive
    /cluster1
    /cluster1/username
    /cluster1/username/registry
    /cluster1/username/registry/namespaces
    /cluster1/username/registry/namespaces/default
    /cluster1/username/registry/ranges
    /cluster1/username/registry/ranges/servicenodeports
    /cluster1/username/registry/ranges/serviceips
    /cluster1/username/registry/services
    /cluster1/username/registry/services/endpoints
    /cluster1/username/registry/services/endpoints/default
    /cluster1/username/registry/services/endpoints/default/kubernetes
    /cluster1/username/registry/services/specs
    /cluster1/username/registry/services/specs/default
    /cluster1/username/registry/services/specs/default/kubernetes
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/events
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/events/default
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/minions
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/minions/ip-10-20-30-34.ec2.internal
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/minions/ip-10-20-30-36.ec2.internal
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/minions/ip-10-20-30-37.ec2.internal
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/namespaces
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/namespaces/default
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/ranges
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/ranges/serviceips
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/ranges/servicenodeports
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/services
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/services/endpoints
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/services/endpoints/default
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/services/endpoints/default/kubernetes
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/services/specs
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/services/specs/default
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/services/specs/default/kubernetes
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/controllers
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/controllers/default
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/controllers/default/nginx
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/pods
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/pods/default
    /cluster1/username/registry++--logtostderr=true++--profiling=true++--insecure-port=8080++--v=2/pods/default/testing
    /coreos.com
    /coreos.com/network
    /coreos.com/network/config
    /coreos.com/network/subnets
    /coreos.com/network/subnets/10.10.34.0-24
    /coreos.com/network/subnets/10.10.86.0-24
    /coreos.com/network/subnets/10.10.87.0-24
    /coreos.com/network/subnets/10.10.19.0-24
    /coreos.com/updateengine
    /coreos.com/updateengine/rebootlock
    /coreos.com/updateengine/rebootlock/semaphore

Kubectl Output

    core@ip-10-20-30-35 ~ $ kubectl get rc
    CONTROLLER   CONTAINER(S)   IMAGE(S)       SELECTOR     REPLICAS
    nginx        nginx          nginx:latest   name=nginx   3

    core@ip-10-20-30-35 ~ $ kubectl get pods
    NAME      READY     STATUS    RESTARTS   AGE
    testing   0/1       Pending   0          30m

    core@ip-10-20-30-35 ~ $ kubectl describe rc nginx
    Name:           nginx
    Namespace:      default
    Image(s):       nginx:latest
    Selector:       name=nginx
    Labels:         name=nginx
    Replicas:       0 current / 3 desired
    Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
    No events.

    core@ip-10-20-30-35 ~ $ kubectl describe pod testing
    Name:                           testing
    Namespace:                      default
    Image(s):                       ubuntu:14.04
    Node:                           /
    Labels:                         <none>
    Status:                         Pending
    Reason:
    Message:
    IP:
    Replication Controllers:        <none>
    Containers:
    messager:
        Image:              ubuntu:14.04
        State:              Waiting
        Ready:              False
        Restart Count:      0
    No events.

Replication Controller Template 

    apiVersion: v1
    kind: ReplicationController
    metadata:
      labels:
        name: nginx
     name: nginx
    spec:
       replicas: 3
    selector:
     name: nginx
    template:
      metadata:
        labels:
          name: nginx
      spec:
        containers:
          - name: nginx
          image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
              name: nginx-webserver

Pod Template

    apiVersion: v1
    kind: Pod
    metadata:
      name: testing
    spec:
      containers:
      - name: messager
        image: "ubuntu:14.04"

Logs -- Kube-Api Server

    Aug 14 11:41:47 ip-10-20-30-35.ec2.internal systemd[1]: Starting Kubernetes API Server...
    Aug 14 11:41:47 ip-10-20-30-35.ec2.internal kube-apiserver[1066]: I0814 11:41:47.401703    1066 plugins.go:69] No cloud provider specified.
    Aug 14 11:41:47 ip-10-20-30-35.ec2.internal kube-apiserver[1066]: I0814 11:41:47.403225    1066 master.go:273] Node port range unspecified. Defaulting to 30000-32767.
    Aug 14 11:41:47 ip-10-20-30-35.ec2.internal kube-apiserver[1066]: I0814 11:41:47.404034    1066 master.go:295] Will report 10.20.30.35 as public IP address.
    Aug 14 11:41:47 ip-10-20-30-35.ec2.internal kube-apiserver[1066]: [restful] 2015/08/14 11:41:47 log.go:30: [restful/swagger] listing is available at https://10.20.30.35:6443/swaggerapi/
    Aug 14 11:41:47 ip-10-20-30-35.ec2.internal kube-apiserver[1066]: [restful] 2015/08/14 11:41:47 log.go:30: [restful/swagger] https://10.20.30.35:6443/swaggerui/ is mapped to folder /swagger-ui/
    Aug 14 11:41:47 ip-10-20-30-35.ec2.internal kube-apiserver[1066]: I0814 11:41:47.442892    1066 server.go:441] Serving securely on 0.0.0.0:6443
    Aug 14 11:41:47 ip-10-20-30-35.ec2.internal kube-apiserver[1066]: I0814 11:41:47.443088    1066 server.go:483] Serving insecurely on 0.0.0.0:8080
    Aug 14 11:41:47 ip-10-20-30-35.ec2.internal kube-apiserver[1066]: I0814 11:41:47.619194    1066 server.go:456] Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)

Logs -- Kube-Controller-Manager

     Aug 14 12:36:27 ip-10-20-30-35.ec2.internal kube-controller-manager[1077]: E0814 12:36:27.984061    1077 nodecontroller.go:255] Error monitoring node status: the server could not find the requested resource
    Aug 14 12:36:28 ip-10-20-30-35.ec2.internal kube-controller-manager[1077]: E0814 12:36:28.336139    1077 reflector.go:130] Failed to list *api.Service: the server could not find the requested resource
     Aug 14 12:36:28 ip-10-20-30-35.ec2.internal kube-controller-manager[1077]: E0814 12:36:28.337197    1077 reflector.go:130] Failed to list *api.Pod: the server could not find the requested resource
    Aug 14 12:36:28 ip-10-20-30-35.ec2.internal kube-controller-manager[1077]: E0814 12:36:28.337851    1077 reflector.go:130] Failed to list *api.Pod: the server could not find the requested resource
    Aug 14 12:36:28 ip-10-20-30-35.ec2.internal kube-controller-manager[1077]: E0814 12:36:28.338497    1077 reflector.go:130] Failed to list *api.ReplicationController: the server could not find the requested resource
     Aug 14 12:36:28 ip-10-20-30-35.ec2.internal kube-controller-manager[1077]: E0814 12:36:28.339116    1077 reflector.go:130] Failed to list *api.Namespace: the server could not find the requested resource

Log-- Kube-scheduller

    Aug 14 12:37:21 ip-10-20-30-35.ec2.internal kube-scheduler[1080]: E0814 12:37:21.392015    1080 reflector.go:130] Failed to list *api.Pod: the server could not find the requested resource
    Aug 14 12:37:21 ip-10-20-30-35.ec2.internal kube-scheduler[1080]: E0814 12:37:21.396356    1080 reflector.go:130] Failed to list *api.Node: the server could not find the requested resource
    Aug 14 12:37:22 ip-10-20-30-35.ec2.internal kube-scheduler[1080]: E0814 12:37:22.391626    1080 reflector.go:130] Failed to list *api.Service: the server could not find the requested resource
    Aug 14 12:37:22 ip-10-20-30-35.ec2.internal kube-scheduler[1080]: E0814 12:37:22.392266    1080 reflector.go:130] Failed to list *api.Pod: the server could not find the requested resource
    Aug 14 12:37:22 ip-10-20-30-35.ec2.internal kube-scheduler[1080]: E0814 12:37:22.392793    1080 reflector.go:130] Failed to list *api.Pod: the server could not find the requested resource
    Aug 14 12:37:22 ip-10-20-30-35.ec2.internal kube-scheduler[1080]: E0814 12:37:22.396670    1080 reflector.go:130] Failed to list *api.Node: the server could not find the requested resource

I have stopped all the minions connecting to the Api Server but still the output shows the minions are in ready state

    core@ip-10-20-30-35 ~ $ kubectl get nodes
    NAME                          LABELS                                               STATUS
    ip-10-20-30-34.ec2.internal   kubernetes.io/hostname=ip-10-20-30-34.ec2.internal   Ready
    ip-10-20-30-36.ec2.internal   kubernetes.io/hostname=ip-10-20-30-36.ec2.internal   Ready
    ip-10-20-30-37.ec2.internal   kubernetes.io/hostname=ip-10-20-30-37.ec2.internal   Ready

**Comment by brendandburns** [comment]
controller manager and scheduler should be pointed at `127.0.0.1:8080`, `0.0.0.0:8080` is an invalid address.

**Comment by kgrvamsi** [comment]
But this sort of settings are being working on my other cluster of 4 nodes and i have no issues with it and infact when i changed my version of kubernetes to 1.0.3 then i can run the RC and Pods with no problem.

**Comment by kgrvamsi** [comment]
Today there was a new issue in one of the cluster with 1.0.1 version and all the minions went down and docker daemon went down.This issue i have raised it earlier #12269 and now will be replying with the information of the logs we have with the present state of the cluster @brendandburns  if you still feel the problem is because of the 0.0.0.0:8080 url then i dont see a point why the minons got stopped with this inreturn docker daemon also stopped as well.
