### ISSUE TITLE
Silently ignoring duplicate creates

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubernetes#12720]
Whenever I create a RC or service that already exists, I rightfully get back an error:

> Error from server: error when creating "foo.yaml": replicationControllers "foo" already exists

But is there any way currently to have this error silently ignored? I have a systemd unit file that relies on starting this service, so if I get back the above error the entire thing is registered as a failure. I'd rather have attempts to create duplicate services refused, but silently.

If there is no functionality that allows this, would you be open to adding a new flag perhaps? Ideas could be `-s` for suppress, `-i` for ignore or `-q` for quiet.

**Comment by erictune** [comment]
Do you want to ignore it?  What if the existing pod is not the same as the one you are trying to create, such as if pod.yaml changed?

Maybe:
```
# Create if does not exist, or replace if exists.
if kubectl get pods mypod; then
  kubectl replace --force -f mypod.yaml || exit 1
else
  kubectl create -f mypod.yaml || exit 1
fi 
```

**Comment by brendandburns** [comment]
Closing this as I think it is essentially a request for `kubectl reconcile ...` https://github.com/kubernetes/kubernetes/issues/1702

**Comment by brendandburns** [comment]
To be clear, closing this because I think it's a dupe, not that it is an invalid request.  We should definitely implement `reconcile`

**Comment by jamiehannaford** [comment]
@erictune @brendandburns :+1: Fine with me. Thanks!
