### ISSUE TITLE
scheduler: Pods aren't retried at all with cluster events to unschedulable Pod

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#127290]
It's initially raised at https://github.com/kubernetes/kubernetes/issues/110175#issuecomment-1140397251. Just create a separate issue so that we don't forget.

So, currently, we don't trigger requeueing with cluster events to unschedulable Pods. It's OK for in-tree plugins, but not OK for out-of-tree plugins that could change the scheduling results with unsched Pods state.

/sig scheduling
/kind bug
/cc @macsko 
/assign

**Comment by sanposhiho** [comment]
/unassign
/assign @macsko 

Would you like? @macsko 
If you're packed, i can take over.

**Comment by AxeZhan** [comment]
Do you mean to try requeue all pods in backoff/unschedulable queue if any unscheduled pod update/add/delete event happens?
If so, would this significantly increase the scheduler's burden? As we would run every plugin's requeue check(isSchedulableAfterPodChange) for all pods?
We might need to came up a special event for this, and let the current in-tree plugins only care about the updated pod but not all pods?

**Comment by sanposhiho** [comment]
> Do you mean to try requeue all pods in backoff/unschedulable queue if any unscheduled pod update/add/delete event happens?

Yes. Like what we do with all the other events, we should trigger QHints with events to unschedulable Pods.

> If so, would this significantly increase the scheduler's burden? As we would run every plugin's requeue check(isSchedulableAfterPodChange) for all pods?

Sorry, I didn't put all the context here though, 
at https://github.com/kubernetes/kubernetes/pull/127268#discussion_r1753558756, we talked about creating a new `GVK` for `AssignedPod` and `UnschedulablePod` and then we can change all plugins to subscribe to `AssignedPod` events only, which allows us not to impact the vanilla scheduler at all, while we can allow out-of-tree plugins to use `UnschedulablePod` events.

**Comment by AxeZhan** [comment]
OK I get it. 

I think I can try this if both of you are packed :)

**Comment by macsko** [comment]
I'm packed, so feel free to take it

**Comment by sanposhiho** [comment]
@AxeZhan Thanks, please take it and poke me and @macsko for reviews.

/unassign @macsko 
/assign @AxeZhan

**Comment by sanposhiho** [comment]
See the discussion at https://github.com/kubernetes/kubernetes/pull/127387. We intentionally don't support unsched Pod events. 

@AxeZhan would you mind creating another PR to document ^?

**Comment by sanposhiho** [comment]
Wait, sorry. Let me do it myself, along with other changes.
/unassign @AxeZhan 
/assign @sanposhiho
