### ISSUE TITLE
Keys/certificates generation for services

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#12732]
It is normal for services within a cluster to require TLS & hence keys/certificates are required. Managing this is normally manual & time-consuming. I'd like to be able to generate keys/certificates on (authenticated) request & provide these to the relevant pods via secrets. This a common problem in a microservice architecture - great blog post on it [here](https://blog.cloudflare.com/how-to-build-your-own-public-key-infrastructure/).

I have a working prototype building on top of [cfssl](https://github.com/cloudflare/cfssl). The basic idea is to watch secrets as they are added & if annotated correctly to update the sceret with generated keys & signed certificates via a cfssl pod (cfssl is bound to localhost so no external connectivity). These are then mounted inside pods that require them in the normal way.

Obviously this is very insecure at the moment as there is no idea of authorization, or of revocation, or of ... well anything other than simply usability. I am not advocating the approach I currently have, just explaining what I've done so far to start discussion.

This is related to some other issues around secret/token generation such as #11070 & #8866, but separate IMO, perhaps just a special case, but one that justifies it's own discussion.

/cc @liggitt @erictune

**Comment by brendandburns** [comment]
It would be awesome to add a key generation service, we should probably make it pluggable so that users can supply their own implementations as well.

**Comment by jimmidyson** [comment]
So could we add this as another type of secret, ala service token, seeing as it's so commonly required & add pluggable generators? Right now generation of anything is in-process, but this seems to be something that should be requested externally rather than trying to embed a full CA inside kube master. This could in time plug in with letsencrypt.org when it's available, but also having a private implementation using [cfssl](https://github.com/cloudflare/cfssl) or [boulder](https://github.com/letsencrypt/boulder). Can perhaps make the key/CSR generation static & just have a pluggable piece to send the request off?

**Comment by bgrant0607** [comment]
cc @kubernetes/goog-cluster

**Comment by bprashanth** [comment]
Can we get this to reach out to letsencrypt CA (https://letsencrypt.org/howitworks/technology/) and produce real certs for domains that we get through cloudprovider dns? haven't thought this through, just putting it out there

**Comment by thockin** [comment]
+1 to the idea - need it for docker registry SSL,

**Comment by jimmidyson** [comment]
@bprashanth Absolutely, although that will only work for services hosted on an owned domain obviously. I'm thinking we need this for internal services which would require an internal CA. Thinking of [cfssl](https://github.com/cloudflare/cfssl) for this, even better that it's the base of letsencrypt.

I would like to try to implement this, but would really like some pointers on how to implement. My first thought was adding a controller, ala the old service account token generator, but that would leave empty secrets until they are generated. As there is no lifecycle for secrets this would lead to pod failures when they can't find the secrets they're expecting.

My next thought is to provide a service to do this generation using the third party types API. Watch specified resources, generate & create corresponding secrets. I can start hacking on that right away, unless someone thinks this would be better as a feature of kubernetes itself? The only way I can think of adding this in (remembering I don't know kubernetes) would be to add a lifecycle to secrets. This would have the added benefit of feeding into secret rotation, but would be more invasive into kubernetes code & probably less pluggable & extensible.

So far I have had to generate secrets for server keys/certificates, client keys/certificates, ssh key pairs (& being able to reference public keys from generated pairs as a separate secret), gpg keys & secure passphrases.

All comments appreciated!

**Comment by roberthbailey** [comment]
@jimmidyson - While designing the system to generate signed certs for services we should also consider that at some point the master components will need to handle CSRs from nodes wanting to join the cluster (in [dynamic clustering](https://github.com/kubernetes/kubernetes/blob/master/docs/design/clustering.md#dynamic-clustering)). It would be useful to work towards a solution that will support both requirements.

**Comment by jimmidyson** [comment]
@roberthbailey Thanks for pointing that out. I can see cfssl helping hugely with that, handling multiple CAs to separate cluster CA trust chain from service CA trust chain, potentially even multiple service CAs in action. And it's handily written in go... Is this dynamic clustering going to be part of core binary or an add-on?

**Comment by roberthbailey** [comment]
The plan is for the core system to support both static and dynamic clustering. Dynamic clustering would be the default for the "kick the tires" use case because it would require minimal initial work to get the cluster set up. Static cluster might still be preferred for deployments where you wanted to have tighter control over the certificates used in the cluster.

**Comment by bprashanth** [comment]
> Absolutely, although that will only work for services hosted on an owned domain obviously. 

What I really want is to just create a single Ingress that sets everything up for a website. This involves:
1. public dns
2. certs
3. loadbalancing to backend services

Setting up the backends is upto the developer (i.e the gmail or maps team is responsible for their backends, but don't worry about how traffic reaches the backend).

**Comment by bprashanth** [comment]
@jimmidyson took a look at your WIP. It seems useful but why put it in the master? That makes anything other than exec-ing a local binary hard to achieve (eg: waiting for a CA to sign a CSR). 

I think it would be more useful to define a claim-like resource that individual controllers can watch and fulfill. That way I can write a CA controller that generates 3 types of CA requests (eg: clusterlocal - signed by cluster CA, self, external). The secret created shows up in the status of the claim. Rough sketch:
```
// need a better name
request:
 crt:
  // some domain id (eg: google), 
  // kubernetes.io:nodename for kubelet?
  domain: foo.bar.com 
status:
 secret: fooSecret
```
That controller would generate the private key and csr, and block tilll signed, then create the secret. Similarly, SSHRequest:
```
request:
 ssh:
  type: rsa
  keyLength: 2048
status:
 secret: fooSecret
```
And so on.

**Comment by bprashanth** [comment]
Thinking about it a little more, you can still do this through a secret/request subreqource endpoint on the master, it's just not satisfied by the master but by an external controller.

**Comment by liggitt** [comment]
submission of a request for a secret to be generated, followed by waiting for the thing to actually be generated before using it sounds good on paper, but needs some sort of "initialization" support to be usable...

service account tokens are currently asynchronously generated into secrets of a given type, and we've found that to be painful to request and use. Pods that require those secrets currently get rejected in admission until they are ready. That works in cases where a replication controller is repeatedly trying to create the pod, and will retry until it succeeds, but it's painful for run-once pods, whose submitter then has to handle retrying.

The more external a cert/key generation is, the more delay could be expected, and the more a request/fulfillment model makes sense, I'm just aware of the challenges of using such a system.

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/pull/8866 as an example of what I started to pull service account token generation back into the master, and why

**Comment by bprashanth** [comment]
fair enough, perhaps its easiest to keep the cluster CA a cluster CA and figure out a more generic model for external resource acquisition that ends up creating the right type of secret using an intermediate claim object

**Comment by jimmidyson** [comment]
I've found the same problems as @liggitt describes above when going for the controller approach (similar to the original approach I tried actually). I want to be able to request a secret be generated & it be generated before I move on to the next request, to create a pod, etc. so that it is ready to be used. Otherwise, as @liggitt says, continual rejection by admission controller until secret is generated.

I expect secret generation to be quick as is the case right now for the 2 supplied generators. I expect cert generation to be quick too, using any of letsencrypt/boulder/cfssl which I'd like to see used for the cluster CA as well to get certs-as-a-service with renewal, etc. I don't expect execing a binary to be required & this doesn't prevent a manual approach for secrets that take too long to generate of course. In fact that would be my recommendation for secrets that take long time to generate, or require human workflow (e.g. manual signing of CSR).

**Comment by bprashanth** [comment]
>  I don't expect execing a binary to be required & this doesn't prevent a manual approach for secrets that take too long to generate of course. 

Oh, I thought you'd have some fallback option that self signed the cert using openssl -x509.

> this doesn't prevent a manual approach for secrets that take too long to generate of course. In fact that would be my recommendation for secrets that take long time to generate, or require human workflow (e.g. manual signing of CSR).

Yeah I'm trying to figure out a non-manual cert generation strategy for "real" domain names that one would acquire via cloud dns, say.

**Comment by jimmidyson** [comment]
I'm probably going to add a self-signed cert generator but programatically rather than execing openssl.

**Comment by kargakis** [comment]
Discussed about this today, we want this feature in order to automate securing our internal registry

cc: @pweil- @deads2k

**Comment by bgrant0607** [comment]
There's also discussion of secret generation in #18215

**Comment by smarterclayton** [comment]
@deads2k can you link in the prototype PR to Origin you have here?

**Comment by deads2k** [comment]
> @deads2k can you link in the prototype PR to Origin you have here?

Sure.  I put together https://github.com/openshift/origin/pull/7728 to allow a cluster-admin to configure an optional controller to automatically mint and sign serving certificates for a service's internal DNS name.  Its triggered by annotation on the service (not a secret) so that things like RCs that depend on the secret won't have any pods start until the key and its signed cert are available to be mounted.

**Comment by mikedanese** [comment]
cc @gtank

**Comment by smarterclayton** [comment]
This is about to merge to origin.  Will update once we get more practical use (I plan on trying it with pet sets for automatic peer signing)

**Comment by erictune** [comment]
Is OpenShift just doing this for servers, or for clients as well?  The latter seems very useful too, but a little trickier.    Servers are discovered by their DNS name, so that is sufficient.  But clients may have multiple attributes that servers want to know about when authorizing them (pod name/namespace, controller it is part of, service account, labels, etc).

Related: @jbeda's [spiffe.io].

**Comment by smarterclayton** [comment]
Just generating serving certs and propagating a CA into service account
secrets right now.

**Comment by smarterclayton** [comment]
We are considering extending this to allow users to request secret generation of two secrets - one a CA.crt with private key, and one a client cert against that key.  That would allow some common two party client auth setups to happen automatically.  This turned out to be a requirement for things like elastic search and fluentd, where we want fluentd to have a client cert that is distinct from the server certs used by ES.

**Comment by hobti01** [comment]
@smarterclayton Could you explain your considerations in more detail?  Here's my interpretation of what you've mentioned and I'm getting stuck on "automatically" :)

- Existing service cert functionality via annotations remains as-is
  - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  - /my/secret/tls.crt and /my/secret/tls.key
- "user" generates new-ca.crt and new-ca.key, client.crt and client.key (signed by new-ca)

Given a Kubernetes Service and a separate "client" Pod:
- The client can "trust" the service via the typical process of comparing the signing cert to a known signer, which means comparing to /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
- How does the Service trust the client?
  - Is new-ca.crt auto-added to /var/run/secrets/kubernetes.io/serviceaccount/new-ca.crt?
  - How is new-ca.crt integrated into the distro-specific ca-certificates, or server specific configurations/directories/keystores?
- Are all client CAs trusted by all Services or is the list of trusted CAs annotated on or linked to the Service?

**Comment by deads2k** [comment]
> How does the Service trust the client?
> Is new-ca.crt auto-added to /var/run/secrets/kubernetes.io/serviceaccount/new-ca.crt?
> How is new-ca.crt integrated into the distro-specific ca-certificates, or server specific configurations/directories/keystores?

The `new-ca.crt` wouldn't be auto-added to the container.  Instead a the pod would have to mount the secret (or configmap depending on how smart we make this) which contains the ca.crt that will verify the client secret that the platform signed with the CA it made.

Basically, we'd just be taking the manual "create signing key/cert pair, create client key/cert pair, and sign client key/cert pair" out of the equation.  To rotate, you'd simply delete the original signer and things (ought) to cascade.

The secret creation, annotation, and mounting order problems remain.  If we assume that pods can crash loop on missing secret content, I think it ought to work.

**Comment by hobti01** [comment]
Thanks for that information.

Do you mean that the "server" pod crash loops, automatically adding `new-ca.crt` via a Secret?

From a UX perspective:
1. Deploy a server with annotations to get a cert "automatically"
2. Deploy a client with annotations to get a cert "automatically"
  - Get the name of the Secret containing the new-ca?
3. Modify the server Pod to mount the new-ca Secret
  - Manually, because automatically would be a security risk?
4. Deploy the server again

Repeat 2-4 for each client?  I think that if all clients use the same CA and only repeat step 2 then that allows rogue clients.

**Comment by deads2k** [comment]
Off the cuff, I think something like this works.  It lets the server come up and separately bring up clients.  The server doesn't have to restart on new clients, no modification is needed after creation, and the system eventually settles.

```yaml
kind: Secret
metadata:
    name: client-ca
    annotations:
        create-client-ca-signer: "true"
kind: Secret
metadata:
    name: client-cert
    annotations:
        create-client-cert-from-signer: client-ca
kind: Pod
metadata:
    name: server
volume:
    # pod crash loops if this the content is empty
    secretMount: client-ca
kind: Pod
metadata:
    name: client
volume:
    # pod crash loops if this the content is empty
    secretMount: client-cert
```

**Comment by mikedanese** [comment]
Also checkout https://github.com/kelseyhightower/certificate-init-container

**Comment by thockin** [comment]
I've been looking at this problem from the Service side.  It seems useful for kube to optionally generate a CA and serving cert for a Service, so clients can trust that the Service they are talking to is the service they expect.

**Comment by smarterclayton** [comment]
Yeah, had planned to fold this into the container / service identity working group discussion, that email will go out in the next day or two.

**Comment by smarterclayton** [comment]
This is fully implemented in openshift and is going to move into GA as soon as we figure out what the istio / SPIFFEE alignment will be (spiffee has an analogue, as does istio)

**Comment by dnascimento** [comment]
@smarterclayton @deads2k Any predictions about merging this in Kubernetes?
https://github.com/openshift/origin/pull/7728

**Comment by hobti01** [comment]
@thockin are you influencing an alignment of this request with https://github.com/PalmStoneGames/kube-cert-manager or https://github.com/jetstack-experimental/cert-manager?

Each effort sees the value of certs for services with various approaches.

@munnerz are you accommodating the current state of the OpenShift approach with your incubator proposal? https://github.com/jetstack-experimental/cert-manager/pull/50

It's a genuine challenge at the moment to choose a stable and maintained implementation.
