### ISSUE TITLE
DRA API: consumable capacity in v1beta1.

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#127386]
### What would you like to be added?

One of the long-term goals is to support "consumable capacity": a single device that can be allocated in different claims such that each claim "consumes" some capacity provided by the device.

For v1beta1 we need to decide whether the current v1alpha3 BasicDevice can support this or whether we need to make changes to it. This issue is about that, not about implementing consumable capacity.

The problem in v1alpha3 is that:
- Not all capacities are necessarily something that should be consumable.
- There is no place in the API to describe additional constraints for a capacity, like the size of chunks that can be consumed.

See https://github.com/kubernetes/enhancements/pull/4808#discussion_r1736000692 for a longer discussion around this.

/sig node
/wg device-management

### Why is this needed?

Future-proofing the DRA API.

**Comment by pohly** [comment]
One option is to turn `BasicDevice.Capacity` from `map[QualifiedName]resource.Quantity` into `map[QualifiedName]DeviceCapacity` with
```
type DeviceCapacity struct {
    Quantity resource.Quantity
    <future fields to be added here for consumable capacity>
}
```

That won't round-trip easily into v1alpha3 where Capacity is a `map[QualifiedName]resource.Quantity`. But let's not let ourselves be constrained by that. The priority has to be to have a sane v1beta1 API. Whether we want to and can continue to support v1alpha3 in 1.32 is less important.

/cc @thockin @johnbelamaric @klueska

**Comment by pohly** [comment]
Another option is to remove `Capacity` from `BasicDevice` and make `Quantity` an attribute type. Then when we define the API for consumable devices, we create `ConsumableDevice` with whatever fields are needed for "consuming capacity".

**Comment by pohly** [comment]
I prefer the `DeviceCapacity` approach. It's okay if old clients ignore the "future fields" there as long as the *request* for consuming capacity is defined such that they recognize it as a future extension.

**Comment by klueska** [comment]
Here is a link to the discussion about this in the implementation PR for 1.31:
https://github.com/kubernetes/kubernetes/pull/125488#discussion_r1669193884

This was the latest from @thockin and @johnbelamaric after I made the comment above:
https://github.com/kubernetes/kubernetes/pull/125488/files#r1676476375

**Comment by johnbelamaric** [comment]
Good points Patrick. I also agree with you that it should be up to the driver whether a capacity is considered consumable or not.

**Comment by knabben** [comment]
Hello @pohly @johnbelamaric 
The code freeze is starting 02:00 UTC Friday November 8th 2024 (about 2 weeks from now), and while there is still time, we want to ensure that each PR has a chance to be merged on time.
As the issue is tagged for 1.32, is it still planned for this release?
Thank you!

**Comment by knabben** [comment]
Hey @pohly @johnbelamaric
⚠️ Do we still intend to merge this for v1.32? Just a reminder that the code freeze is starting 02:00 UTC Friday November 8th 2024 (a little less than 1 week from now). Please make sure the PR has both lgtm and approved labels before the code freeze. Thanks!
