### ISSUE TITLE
is:issue is:open embed:rejected connection from #106.0.18.66:35592"(error"remoteerror :t1s:certificateembed:servername""

### ISSUE THREAD

**Issue by yinfuqian** [kubernetes/kubernetes#127334]
### What happened?

Due to an accidental operation, the etcd certificates were replaced, causing the Kubernetes cluster to become corrupted and the kubectl command to become unusable. I attempted to regenerate the cluster certificates using kubeadm init phase certs all --config /etc/kubernetes/kubeadm-config.yaml and copied the entire /etc/kubernetes/pki directory to other nodes. After restarting all cluster components, the following error occurs:

### What did you expect to happen?

my cluster recover

### How can we reproduce it (as minimally and precisely as possible)?

Severely affects production use.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
[zhuiyi@k8s-master-node1 ~]$  kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:23:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
[zhuiyi@k8s-master-node1 ~]$ 

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
[zhuiyi@k8s-master-node1 ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[zhuiyi@k8s-master-node1 ~]$ 
$ uname -a
[zhuiyi@k8s-master-node1 ~]$ uname -a
Linux k8s-master-node1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[zhuiyi@k8s-master-node1 ~]$ 


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
