### ISSUE TITLE
/proxy/metics/cadvisor metrics data not updating metrics frequently

### ISSUE THREAD

**Issue by ArunprakashD** [kubernetes/kubernetes#127390]
### What happened?

HI,
we have a single server cluster and the container metrics are not updating frequently in /proxy/metrics/cadvisor, because of this prometheus is showing same values over period of time and range give 0 output.
`kubectl get --raw /api/v1/nodes/mynode/proxy/metrics/cadvisor | grep container_cpu_usage_seconds_total | grep mypod`

Kubernetes: **v1.30.1**

kubelet ps output:
`ps -ef | grep kubelet
root       11396       1 76 Sep13 ?        2-08:19:14 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime-endpoint=unix:///run/containerd/containerd.sock --pod-infra-container-image=registry.myzone.local:5000/pause:3.9 --cert-dir=/var/lib/kubelet/pki --cpu-manager-policy=static --housekeeping-interval=3600s --node-ip=172.16.0.18 --node-labels=node.uuid=39343550-3036-5a43-3233-343530425a33,node.uuid_source=mycluster,mycluster/version=2.29.1,node-pool=ucc,my.cluster.com/node-images-version=v3,infra.my.cluster.com/cluster=aaaa,infra.my.cluster.com/pool=ucc,infra.my.cluster.com/singleserver=,nic-type-sriov=true,isolation-interrupts=true,type=high-throughput --register-with-taints=infra.my.cluster.com/taskset=:NoSchedule --reserved-cpus=0,1,2,3,4,5,64,65,66,67,68,69 --runtime-cgroups=/myzone.slice/containerd.service --system-reserved=cpu=100m
`

```
>>> kubectl get --raw /api/v1/nodes/mynode/proxy/metrics/cadvisor | grep container_cpu_usage_seconds_total | grep mypod
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod711e104c_a951_4a1a_b123_a3169121bed7.slice",image="",name="",namespace="kube-system",pod="mypod"} 160.314258 1726485335746
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod711e104c_a951_4a1a_b123_a3169121bed7.slice/cri-containerd-60cb609ce98a2c5ce7c55892150af456850ffe11b59085e5e3a21f85362e6ea1.scope",image="registry.myzone.local:5000/pause:3.9",name="60cb609ce98a2c5ce7c55892150af456850ffe11b59085e5e3a21f85362e6ea1",namespace="kube-system",pod="mypod"} 0.208044 1726486650276
container_cpu_usage_seconds_total{container="mypod-consumer",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod711e104c_a951_4a1a_b123_a3169121bed7.slice/cri-containerd-47af50324ccf418da19327b140f5e9d4329ea893d62f9ba6290151949401a22b.scope",image="registry.myzone.local:5000/mypod:1.5-86-3ef3cd5d",name="47af50324ccf418da19327b140f5e9d4329ea893d62f9ba6290151949401a22b",namespace="kube-system",pod="mypod"} 158.987157 1726483476487
```

`curl -s http://$VM_SELECT:8481/select/0/prometheus/api/v1/query --data-urlencode 'query=(container_cpu_usage_seconds_total{job="kubernetes-nodes-cadvisor",pod="mypod",container="mypod-consumer"}[5m])' | jq
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "container_cpu_usage_seconds_total",
          "namespace": "kube-system",
          "job": "kubernetes-nodes-cadvisor",
          "type": "high-throughput",
          "pod": "mypod",
          "name": "47af50324ccf418da19327b140f5e9d4329ea893d62f9ba6290151949401a22b",
          "beta_kubernetes_io_arch": "amd64",
          "beta_kubernetes_io_os": "linux",
          "container": "my-consumer",
          "cpu": "total",
          "id": "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod711e104c_a951_4a1a_b123_a3169121bed7.slice/cri-containerd-47af50324ccf418da19327b140f5e9d4329ea893d62f9ba6290151949401a22b.scope",
          "image": "registry.myzone.local:5000/mypod:1.5-86-3ef3cd5d",
          "isolation_interrupts": "true",
          "kubernetes_io_arch": "amd64",
          "kubernetes_io_os": "linux",
          "nic_type_sriov": "true",
          "node_pool": "ucc",
          "node_uuid": "39343550-3036-5a43-3233-343530425a33",
          "topology_topolvm_cybozu_com_node": "ucc-mycluster"
        },
        "values": [
          [
            1726488133.816,
            "158.987157"
          ],
          [
            1726488163.816,
            "158.987157"
          ],
          [
            1726488193.816,
            "161.795579"
          ],
          [
            1726488223.816,
            "161.795579"
          ],
          [
            1726488253.816,
            "161.795579"
          ],
          [
            1726488283.816,
            "161.795579"
          ],
          [
            1726488313.816,
            "161.795579"
          ],
          [
            1726488343.816,
            "161.795579"
          ],
          [
            1726488373.816,
            "161.795579"
          ],
          [
            1726488403.816,
            "161.795579"
          ]
        ]
      }
    ]
  }
}
`
When we enable verbosity for kubelet, we see these logs being printed but not sure if its related.
Aug 13 09:39:46 ucc-kubelet[10909]: I0813 09:39:46.185047   10909 cri_stats_provider.go:220] "
Unable to find cadvisor stats for container"
containerID="8cf4faf5f7a800b0430b7e081d362ca29fa24903df4f9253aa30b4d1163836c8"

### What did you expect to happen?

cadvisor metrics should be updated frequently, one thing observered is /proxy/metrics/resources is keep updating the data.

### How can we reproduce it (as minimally and precisely as possible)?

Observed in our local cluster

### Kubernetes version

<details>

```console
 kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp5"
DOCUMENTATION_URL="https://documentation.suse.com/"

$ uname -a
Linux ucc-myzone 5.14.21-150500.55.65.1.28147.1.PTF.1222893-default #1 SMP PREEMPT_DYNAMIC Tue May 28 12:11:24 UTC 2024 (e6fa633) x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ArunprakashD** [comment]
Can we get a support here or how to debug this issue?

**Comment by AnishShah** [comment]
sig-node triage meeting:

@ArunprakashD , can we get kubelet logs with increased verbosity for further debugging?

**Comment by ArunprakashD** [comment]
[kubelet.zip](https://github.com/user-attachments/files/17184245/kubelet.zip)

Hi, @AnishShah  attached the kubelet logs with verbosity 8

**Comment by SergeyKanzhelev** [comment]
@ArunprakashD can you please give more information about the environment:

1. Does this oissue happen all the time?
2. How many pods are running on the node? Are containers failing/restarting often?
3. How long Pods typically alive?
4. Anything specific about containers? Are they sleep a lot for instance?

**Comment by SergeyKanzhelev** [comment]
As a debug steps you can try to perform is to check which container stats cadvisor cannot collect by observing cgroups manually.

**Comment by ArunprakashD** [comment]
Could you please let me know what should be checked here.. 

`As a debug steps you can try to perform is to check which container stats cadvisor cannot collect by observing cgroups manually.
`

**Comment by peppi-lotta** [comment]
@SergeyKanzhelev 

I'm working with @ArunprakashD on this. Here is some information on the cgroups. Please let us know if there is something more we can inspect on these!

In the kubepods-burstable-pod cgroups all these metrics are present and files are constantly changing: 
```
/sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb67b31a2_9311_49ab_8909_5e7708df5d11.slice> ll
total 0
-r--r--r-- 1 root root 0 Oct 16 10:36 cgroup.controllers
-r--r--r-- 1 root root 0 Sep 25 13:23 cgroup.events
-rw-r--r-- 1 root root 0 Oct 16 10:56 cgroup.freeze
--w------- 1 root root 0 Oct 16 10:56 cgroup.kill
-rw-r--r-- 1 root root 0 Oct 16 10:56 cgroup.max.depth
-rw-r--r-- 1 root root 0 Oct 16 10:56 cgroup.max.descendants
-rw-r--r-- 1 root root 0 Oct 16 10:56 cgroup.procs
-r--r--r-- 1 root root 0 Oct 16 10:56 cgroup.stat
-rw-r--r-- 1 root root 0 Sep 25 13:23 cgroup.subtree_control
-rw-r--r-- 1 root root 0 Oct 16 10:56 cgroup.threads
-rw-r--r-- 1 root root 0 Oct 16 10:56 cgroup.type
-rw-r--r-- 1 root root 0 Oct 16 10:56 cpu.idle
-rw-r--r-- 1 root root 0 Oct 16 10:35 cpu.max
-rw-r--r-- 1 root root 0 Oct 16 10:56 cpu.max.burst
-rw-r--r-- 1 root root 0 Oct 16 10:56 cpu.pressure
-rw-r--r-- 1 root root 0 Oct 16 10:56 cpuset.cpus
-r--r--r-- 1 root root 0 Oct 16 10:35 cpuset.cpus.effective
-rw-r--r-- 1 root root 0 Oct 16 10:56 cpuset.cpus.partition
-rw-r--r-- 1 root root 0 Oct 16 10:56 cpuset.mems
-r--r--r-- 1 root root 0 Oct 16 10:56 cpuset.mems.effective
-r--r--r-- 1 root root 0 Oct 16 10:56 cpu.stat
-rw-r--r-- 1 root root 0 Oct 16 10:35 cpu.weight
-rw-r--r-- 1 root root 0 Oct 16 10:56 cpu.weight.nice
drwxr-xr-x 2 root root 0 Sep 25 13:23 cri-containerd-4b1f25b75c891b8377a9e6a03e64252a4812e58fc293164579c2ad2966325c0c.scope
drwxr-xr-x 2 root root 0 Sep 25 13:23 cri-containerd-db8b6607bb0a7e95592e5a3b5e246c2af388b50d10ce77ec98f312e63dfc7993.scope
-r--r--r-- 1 root root 0 Oct 16 10:56 hugetlb.1GB.current
-r--r--r-- 1 root root 0 Oct 16 10:56 hugetlb.1GB.events
-r--r--r-- 1 root root 0 Oct 16 10:56 hugetlb.1GB.events.local
-rw-r--r-- 1 root root 0 Oct 16 10:56 hugetlb.1GB.max
-r--r--r-- 1 root root 0 Oct 16 10:56 hugetlb.1GB.rsvd.current
-rw-r--r-- 1 root root 0 Oct 16 10:56 hugetlb.1GB.rsvd.max
-r--r--r-- 1 root root 0 Oct 16 10:56 hugetlb.2MB.current
-r--r--r-- 1 root root 0 Oct 16 10:56 hugetlb.2MB.events
-r--r--r-- 1 root root 0 Oct 16 10:56 hugetlb.2MB.events.local
-rw-r--r-- 1 root root 0 Oct 16 10:56 hugetlb.2MB.max
-r--r--r-- 1 root root 0 Oct 16 10:56 hugetlb.2MB.rsvd.current
-rw-r--r-- 1 root root 0 Oct 16 10:56 hugetlb.2MB.rsvd.max
-rw-r--r-- 1 root root 0 Oct 16 10:56 io.bfq.weight
-rw-r--r-- 1 root root 0 Oct 16 10:56 io.latency
-rw-r--r-- 1 root root 0 Oct 16 10:56 io.max
-rw-r--r-- 1 root root 0 Oct 16 10:56 io.pressure
-rw-r--r-- 1 root root 0 Oct 16 10:56 io.prio.class
-r--r--r-- 1 root root 0 Oct 16 10:56 io.stat
-rw-r--r-- 1 root root 0 Oct 16 10:56 io.weight
-r--r--r-- 1 root root 0 Oct 16 10:56 memory.current
-r--r--r-- 1 root root 0 Oct 16 10:56 memory.events
-r--r--r-- 1 root root 0 Oct 16 10:56 memory.events.local
-rw-r--r-- 1 root root 0 Oct 16 10:56 memory.high
-rw-r--r-- 1 root root 0 Oct 16 10:56 memory.low
-rw-r--r-- 1 root root 0 Oct 16 10:35 memory.max
-rw-r--r-- 1 root root 0 Oct 16 10:35 memory.min
-r--r--r-- 1 root root 0 Oct 16 10:56 memory.numa_stat
-rw-r--r-- 1 root root 0 Oct 16 10:56 memory.oom.group
-rw-r--r-- 1 root root 0 Oct 16 10:56 memory.pressure
--w------- 1 root root 0 Oct 16 10:56 memory.reclaim
-r--r--r-- 1 root root 0 Oct 16 10:56 memory.stat
-r--r--r-- 1 root root 0 Oct 16 10:56 memory.swap.current
-r--r--r-- 1 root root 0 Oct 16 10:56 memory.swap.events
-rw-r--r-- 1 root root 0 Oct 16 10:56 memory.swap.high
-rw-r--r-- 1 root root 0 Oct 16 10:35 memory.swap.max
-r--r--r-- 1 root root 0 Oct 16 10:56 misc.current
-rw-r--r-- 1 root root 0 Oct 16 10:56 misc.max
-r--r--r-- 1 root root 0 Oct 16 10:56 pids.current
-r--r--r-- 1 root root 0 Oct 16 10:56 pids.events
-rw-r--r-- 1 root root 0 Oct 16 10:35 pids.max
-r--r--r-- 1 root root 0 Oct 16 10:56 rdma.current
-rw-r--r-- 1 root root 0 Oct 16 10:56 rdma.max
```

In the cri-containerd cgroups files are not constantly changing:
```
/sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb67b31a2_9311_49ab_8909_5e7708df5d11.slice/cri-containerd-db8b6607bb0a7e95592e5a3b5e246c2af388b50d10ce77ec98f312e63dfc7993.scope> ls -lhrt
total 0
-r--r--r-- 1 root root 0 Sep 25 13:23 memory.events
-rw-r--r-- 1 root root 0 Sep 25 13:23 cgroup.subtree_control
-r--r--r-- 1 root root 0 Sep 25 13:23 cgroup.events
-rw-r--r-- 1 root root 0 Oct 16 10:35 pids.max
-rw-r--r-- 1 root root 0 Oct 16 10:35 memory.swap.max
-rw-r--r-- 1 root root 0 Oct 16 10:35 memory.min
-rw-r--r-- 1 root root 0 Oct 16 10:35 memory.max
-rw-r--r-- 1 root root 0 Oct 16 10:35 cpu.weight
-r--r--r-- 1 root root 0 Oct 16 10:35 cpuset.cpus.effective
-rw-r--r-- 1 root root 0 Oct 16 10:35 cpu.max
-rw-r--r-- 1 root root 0 Oct 16 11:06 rdma.max
-r--r--r-- 1 root root 0 Oct 16 11:06 rdma.current
-r--r--r-- 1 root root 0 Oct 16 11:06 pids.events
-r--r--r-- 1 root root 0 Oct 16 11:06 pids.current
-rw-r--r-- 1 root root 0 Oct 16 11:06 misc.max
-r--r--r-- 1 root root 0 Oct 16 11:06 misc.current
-rw-r--r-- 1 root root 0 Oct 16 11:06 memory.swap.high
-r--r--r-- 1 root root 0 Oct 16 11:06 memory.swap.events
-r--r--r-- 1 root root 0 Oct 16 11:06 memory.swap.current
-r--r--r-- 1 root root 0 Oct 16 11:06 memory.stat
--w------- 1 root root 0 Oct 16 11:06 memory.reclaim
-rw-r--r-- 1 root root 0 Oct 16 11:06 memory.pressure
-rw-r--r-- 1 root root 0 Oct 16 11:06 memory.oom.group
-r--r--r-- 1 root root 0 Oct 16 11:06 memory.numa_stat
-rw-r--r-- 1 root root 0 Oct 16 11:06 memory.low
-rw-r--r-- 1 root root 0 Oct 16 11:06 memory.high
-r--r--r-- 1 root root 0 Oct 16 11:06 memory.events.local
-r--r--r-- 1 root root 0 Oct 16 11:06 memory.current
-rw-r--r-- 1 root root 0 Oct 16 11:06 io.weight
-r--r--r-- 1 root root 0 Oct 16 11:06 io.stat
-rw-r--r-- 1 root root 0 Oct 16 11:06 io.prio.class
-rw-r--r-- 1 root root 0 Oct 16 11:06 io.pressure
-rw-r--r-- 1 root root 0 Oct 16 11:06 io.max
-rw-r--r-- 1 root root 0 Oct 16 11:06 io.latency
-rw-r--r-- 1 root root 0 Oct 16 11:06 io.bfq.weight
-rw-r--r-- 1 root root 0 Oct 16 11:06 hugetlb.2MB.rsvd.max
-r--r--r-- 1 root root 0 Oct 16 11:06 hugetlb.2MB.rsvd.current
-rw-r--r-- 1 root root 0 Oct 16 11:06 hugetlb.2MB.max
-r--r--r-- 1 root root 0 Oct 16 11:06 hugetlb.2MB.events.local
-r--r--r-- 1 root root 0 Oct 16 11:06 hugetlb.2MB.events
-r--r--r-- 1 root root 0 Oct 16 11:06 hugetlb.2MB.current
-rw-r--r-- 1 root root 0 Oct 16 11:06 hugetlb.1GB.rsvd.max
-r--r--r-- 1 root root 0 Oct 16 11:06 hugetlb.1GB.rsvd.current
-rw-r--r-- 1 root root 0 Oct 16 11:06 hugetlb.1GB.max
-r--r--r-- 1 root root 0 Oct 16 11:06 hugetlb.1GB.events.local
-r--r--r-- 1 root root 0 Oct 16 11:06 hugetlb.1GB.events
-r--r--r-- 1 root root 0 Oct 16 11:06 hugetlb.1GB.current
-rw-r--r-- 1 root root 0 Oct 16 11:06 cpu.weight.nice
-r--r--r-- 1 root root 0 Oct 16 11:06 cpu.stat
-r--r--r-- 1 root root 0 Oct 16 11:06 cpuset.mems.effective
-rw-r--r-- 1 root root 0 Oct 16 11:06 cpuset.mems
-rw-r--r-- 1 root root 0 Oct 16 11:06 cpuset.cpus.partition
-rw-r--r-- 1 root root 0 Oct 16 11:06 cpuset.cpus
-rw-r--r-- 1 root root 0 Oct 16 11:06 cpu.pressure
-rw-r--r-- 1 root root 0 Oct 16 11:06 cpu.max.burst
-rw-r--r-- 1 root root 0 Oct 16 11:06 cpu.idle
-rw-r--r-- 1 root root 0 Oct 16 11:06 cgroup.type
-rw-r--r-- 1 root root 0 Oct 16 11:06 cgroup.threads
-r--r--r-- 1 root root 0 Oct 16 11:06 cgroup.stat
-rw-r--r-- 1 root root 0 Oct 16 11:06 cgroup.procs
-rw-r--r-- 1 root root 0 Oct 16 11:06 cgroup.max.descendants
-rw-r--r-- 1 root root 0 Oct 16 11:06 cgroup.max.depth
--w------- 1 root root 0 Oct 16 11:06 cgroup.kill
-rw-r--r-- 1 root root 0 Oct 16 11:06 cgroup.freeze
-r--r--r-- 1 root root 0 Oct 16 11:06 cgroup.controllers
```

cadvisor/metrics endpoint does not have updated stats in the frequency that is expected. This relates to all CPU and memory stats.

Other thing  we've checked so far is that kubelet and containerd have the same cgroupDriver (cgroupDriver: systemd)

**Comment by kashifest** [comment]
@SergeyKanzhelev @AnishShah can you please check the logs and findings and suggest a way forward in this issue ?

**Comment by lentzi90** [comment]
I have been helping @peppi-lotta with the debugging. We have now found that the issue is really a mistake in the configuration. Specifically this: `--housekeeping-interval=3600s`. It makes cadvisor collect container metrics only once per hour. The default value is 10s.
This is good to close.
/close
