### ISSUE TITLE
Incorrect error message when a namespace is omitted from POST request

### ISSUE THREAD

**Issue by vaikas** [kubernetes/kubernetes#12737]
https://github.com/kubernetes/kubernetes/blob/master/examples/cassandra/cassandra-controller.yaml

Converting that to JSON and trying to post to master without namespace in the URL results in 403, which seems incorrect.
 curl -X POST -k -H 'Authorization: Basic XXX' https://aaa.bbb.ccc.ddd/api/v1/replicationcontrollers --data @k8s.new.json 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "ReplicationController \"cassandra\" is forbidden: Namespace  does not exist",
  "reason": "Forbidden",
  "details": {
    "name": "cassandra",
    "kind": "ReplicationController"
  },
  "code": 403
}

**Comment by bgrant0607** [comment]
cc @nikhiljindal

**Comment by lavalamp** [comment]
@vaikas What code did you expect? 404 doesn't seem right, since you're allowed to read from that URL, just not write to it.

**Comment by brendandburns** [comment]
405 (method not allowed) seems to be the correct error in this case.  I'll send a PR.

**Comment by lavalamp** [comment]
Yeah, 405 seems like the right code.

**Comment by brendandburns** [comment]
This was fixed @ HEAD by https://github.com/kubernetes/kubernetes/pull/11252.

I'm going to cherry-pick it into 1.0.X
