### ISSUE TITLE
One node(s) had taints that the pod didn't tolerate in kubernetes cluster

### ISSUE THREAD

**Issue by lauradavidd** [kubernetes/kubernetes#127380]
Today my kubernetes cluster  give me this error: 1 node(s) had taints that the pod didn't tolerate and the pods could not start.

It tells me one nodes have taints and I check the node status and works fine, how to know it exactly have taints?

I am searching from internet and all tells me that master node could not allocate for pods running by default. But now my kubernetes pods is not running a master node.

What may cause my node have taints(for example this node have not enough resource)?
What should I do to find out the taints of the node and fix it?

**Comment by niranjandarshann** [comment]
@lauradavidd  You can use kubectl describe node <nodename> to check taints.

The node controller automatically taints a Node when certain conditions are true.

**Comment by lauradavidd** [comment]
checked the description of the node can you guide  me next. @niranjandarshann

**Comment by niranjandarshann** [comment]
Hey @lauradavidd  
If you want to keep the taint on node as it is and still you want to schedule particular pod on that node then include this in your pod/deployment.yaml file.

```
tolerations:
- key: "key"
  operator: "Exists"
  effect: "NoSchedule"

```

**Comment by niranjandarshann** [comment]
`kubectl taint node master node-role.kubernetes.io/master:NoSchedule-
`Use this command if you want to remove  taint from node.

**Comment by lauradavidd** [comment]
@niranjandarshann   tells me that master node could not allocate for pods running by default. But now my kubernetes pods is not running a master node. I am looking for it?

**Comment by lauradavidd** [comment]
`kubectl taint node master node-role.kubernetes.io/master:NoSchedule
`
This command is not working  for me

**Comment by niranjandarshann** [comment]
> `kubectl taint node master node-role.kubernetes.io/master:NoSchedule ` This command is not working for me

@lauradavidd  dont forget to use the `-` after NoSchedule.

**Comment by niranjandarshann** [comment]
`kubectl taint node master node-role.kubernetes.io/master:NoSchedule- `  use the command same by changing your master node name

**Comment by niranjandarshann** [comment]
@lauradavidd  Let me know if it work for you ?

**Comment by niranjandarshann** [comment]
> @niranjandarshann tells me that master node could not allocate for pods running by default. But now my kubernetes pods is not running a master node. I am looking for it?

By default master node is tainted (means no pod or workload will be scheduled on master node. and this is best practices because master node meant to run cluster component like ETCD, kubeapi-server etc. and all other application related pods should go onto worker nodes ) so that's why by default taint applied on master node. Taints and toleration work together to ensure that pods are not scheduled onto inappropriate nodes. One or more taints are applied to a node.

**Comment by niranjandarshann** [comment]
@lauradavidd  I think it give you best explanation about your question.

**Comment by lauradavidd** [comment]
> @lauradavidd Let me know if it work for you ?

yes it worked for me

**Comment by lauradavidd** [comment]
> @lauradavidd I think it give you best explanation about your question.

good explanation impressed .

**Comment by lauradavidd** [comment]
You helped me to resolve the issue . @niranjandarshann  Thank you for your kindness, patience and help.

**Comment by niranjandarshann** [comment]
@lauradavidd  for support question you may ask this in kubernetes slack  channel as well or in discussion forum.

**Comment by niranjandarshann** [comment]
If issue is resolved then you may closethe issue.
If you need to discuss further then you may reopen it or you may raise in discussion forum or slack or in fresh issue.

**Comment by niranjandarshann** [comment]
Without your confirmation we cannot close the issue else you may close it. reopened it for your response/ action.

**Comment by lauradavidd** [comment]
@niranjandarshann  Not an issue this  is successfully resolved  so you may close this issue.
