### ISSUE TITLE
Failure cluster [acfaf590...] `[sig-node] Restart [Serial] [Slow] [Disruptive] Kubelet should evict running pods that do not meet the affinity after the kubelet restart`

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#127374]
##### Error text:
```
[FAILED] Timed out after 300.001s.
Pod affinity-pod5ecfc1b1-95d3-4c1c-81f6-ec3a7a533436 not terminated: 
In [It] at: k8s.io/kubernetes/test/e2e_node/restart_test.go:551 @ 09/14/24 10:33:13.346

```
#### Recent failures:
[9/15/2024, 6:16:30 AM ci-cgroupv1-containerd-node-e2e-serial-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-e2e-serial-ec2-eks/1835260903365283840)
[9/15/2024, 5:17:22 AM ci-kubernetes-node-kubelet-cgroupv1-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-cgroupv1-serial-cri-o/1835246307090894848)
[9/15/2024, 3:32:29 AM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1835219882820505600)
[9/15/2024, 1:56:45 AM ci-cgroupv2-containerd-node-arm64-e2e-serial-ec2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv2-containerd-node-arm64-e2e-serial-ec2/1835195723293921280)
[9/15/2024, 12:16:03 AM ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks/1835170305685852160)

/kind failing-test

/sig node

**Comment by dims** [comment]
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/89b95c3e-cf7e-460e-8720-4d05c623768d">

**Comment by kannon92** [comment]
@chengjoey This looks like a test you added a few days ago: https://github.com/kubernetes/kubernetes/pull/124445

/assign @chengjoey 

Can you look into these failures?

**Comment by chengjoey** [comment]
https://github.com/kubernetes/kubernetes/pull/124445#discussion_r1759138289
https://github.com/kubernetes/kubernetes/pull/124445#discussion_r1759653994

As mentioned in the previous comments, there should be only one expected state in the end. From the logs of these failed tests, after stopping the container, the phase changes to Failed. I think this does not meet expectations.

```
I0915 10:44:56.637361 6170 dump.go:53] At 2024-09-15 10:39:53 +0000 UTC - event for affinity-pod1086d1b6-21f6-439d-8702-196ed94e77fd: {kubelet i-099e08745cf2dac00} Started: Started container affinity-pod1086d1b6-21f6-439d-8702-196ed94e77fd
I0915 10:44:56.637370 6170 dump.go:53] At 2024-09-15 10:39:55 +0000 UTC - event for affinity-pod1086d1b6-21f6-439d-8702-196ed94e77fd: {kubelet i-099e08745cf2dac00} NodeAffinity: Predicate NodeAffinity failed: node(s) didn't match Pod's node affinity/selector
I0915 10:44:56.637378 6170 dump.go:53] At 2024-09-15 10:39:56 +0000 UTC - event for affinity-pod1086d1b6-21f6-439d-8702-196ed94e77fd: {kubelet i-099e08745cf2dac00} Killing: Stopping container affinity-pod1086d1b6-21f6-439d-8702-196ed94e77fd
I0915 10:44:56.639096 6170 resource.go:168] POD                                               NODE                 PHASE   GRACE  CONDITIONS
I0915 10:44:56.639146 6170 resource.go:175] affinity-pod1086d1b6-21f6-439d-8702-196ed94e77fd  i-099e08745cf2dac00  Failed         [{PodReadyToStartContainers False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC PodFailed } {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC PodFailed } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  }]
I0915 10:44:56.639163 6170 resource.go:178] 
I0915 10:44:56.646064 6170 dump.go:109] 
Logging node info for node i-099e08745cf2dac00
```

**Comment by chengjoey** [comment]
Thanks to @kannon92 for revert my previous PR. I think the pod final state should always be in one state. From the current e2e test results, the final state may be Succeed or Failed. I think this seems to be wrong. I will study whether the node status (sufficient memory) and other factors interfere with the final state. Thanks again to @kannon92 for his help.

**Comment by chengjoey** [comment]
Add the log with phase "Succeed":

```
`canAdmitPod`:
07:12:40.999114 1932567 kubelet.go:2306] "Pod admission denied" podUID="eea5fa4a-6ea5-43c4-926a-fc95b6925ed8" pod="default/app" reason="NodeAffinity" message="Predicate NodeAffinity failed: node(s) didn't match Pod's node affinity/selector"

1.update pod status
`updateStatus` this status conditions are empty:
07:12:41.075186 1932567 status_manager.go:872] "Patch status for pod" pod="default/app" podUID="eea5fa4a-6ea5-43c4-926a-fc95b6925ed8" patch="{\"metadata\":{\"uid\":\"eea5fa4a-6ea5-43c4-926a-fc95b6925ed8\"},\"status\":{\"conditions\":null,\"containerStatuses\":null,\"hostIP\":null,\"hostIPs\":null,\"podIP\":null,\"podIPs\":null,\"qosClass\":null}}"

2. update pod status
killing container, update status, this status update pod phase as `PodFailed`:
07:12:42.228610 1932567 status_manager.go:872] "Patch status for pod" pod="default/app" podUID="eea5fa4a-6ea5-43c4-926a-fc95b6925ed8" patch="{\"metadata\":{\"uid\":\"eea5fa4a-6ea5-43c4-926a-fc95b6925ed8\"},\"status\":{\"conditions\":[{\"lastProbeTime\":null,\"lastTransitionTime\":\"2024-09-16T07:12:42Z\",\"status\":\"False\",\"type\":\"PodReadyToStartContainers\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2024-09-16T07:12:42Z\",\"status\":\"True\",\"type\":\"Initialized\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2024-09-16T07:12:42Z\",\"reason\":\"PodFailed\",\"status\":\"False\",\"type\":\"Ready\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2024-09-16T07:12:42Z\",\"reason\":\"PodFailed\",\"status\":\"False\",\"type\":\"ContainersReady\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2024-09-16T07:12:42Z\",\"status\":\"True\",\"type\":\"PodScheduled\"}],\"containerStatuses\":[{\"containerID\":\"docker://89ab3e747f2dc1c9e21e17e5978f6108e151f9aea3c116fc15dc3d1bdff90fb4\",\"image\":\"registry.k8s.io/pause:3.10\",\"imageID\":\"docker-pullable://registry.k8s.io/pause@sha256:ee6521f290b2168b6e0935a181d4cff9be1ac3f505666ef0e3c98fae8199917a\",\"lastState\":{},\"name\":\"web-server\",\"ready\":false,\"restartCount\":0,\"started\":false,\"state\":{\"terminated\":{\"containerID\":\"docker://89ab3e747f2dc1c9e21e17e5978f6108e151f9aea3c116fc15dc3d1bdff90fb4\",\"exitCode\":0,\"finishedAt\":\"2024-09-16T07:12:42Z\",\"reason\":\"Completed\",\"startedAt\":\"2024-09-16T07:12:12Z\"}}}],\"hostIP\":\"192.168.49.2\",\"hostIPs\":[{\"ip\":\"192.168.49.2\"}],\"podIP\":\"10.244.0.29\",\"podIPs\":[{\"ip\":\"10.244.0.29\"}],\"qosClass\":\"BestEffort\"}}"

3. update pod status, all pod container terminated, because kill container status with exitCode 0, update pod phase as `PodSucceed` from `PodFailed` again:
07:12:43.251602 1932567 status_manager.go:872] "Patch status for pod" pod="default/app" podUID="eea5fa4a-6ea5-43c4-926a-fc95b6925ed8" patch="{\"metadata\":{\"uid\":\"eea5fa4a-6ea5-43c4-926a-fc95b6925ed8\"},\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"PodReadyToStartContainers\"},{\"type\":\"Initialized\"},{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[{\"reason\":\"PodCompleted\",\"type\":\"Initialized\"},{\"reason\":\"PodCompleted\",\"type\":\"Ready\"},{\"reason\":\"PodCompleted\",\"type\":\"ContainersReady\"}],\"phase\":\"Succeeded\"}}"

4.  update pod status after pod worker stopped
07:12:44.246239 1932567 pod_workers.go:951] "Pod worker has stopped" podUID="eea5fa4a-6ea5-43c4-926a-fc95b6925ed8"
07:12:44.269592 1932567 status_manager.go:872] "Patch status for pod" pod="default/app" podUID="eea5fa4a-6ea5-43c4-926a-fc95b6925ed8" patch="{\"metadata\":{\"uid\":\"eea5fa4a-6ea5-43c4-926a-fc95b6925ed8\"}}"
```

The normal update status steps are 1->2->3->4, but the result of failure tests is that step 2 is executed last, which seems a bit strange. Because phase is empty
> [FAILED] Timed out after 300.001s.
> Pod affinity-pod5ecfc1b1-95d3-4c1c-81f6-ec3a7a533436 not terminated:

**Comment by kannon92** [comment]
@chengjoey feel free to reopen the PR. But let's make sure to run the tests that this reported as failing before we merge.

Thank you for your help on improving test coverage!

**Comment by toVersus** [comment]
> From the current e2e test results, the final state may be Succeed or Failed, seems pod.Status.Phase is empty.

@chengjoey 
The links to the failed E2E tests in the overview of this issue all show the Pod phase as `Failed`, but is there a link available somewhere for cases where it's empty string?

```console
  I0915 10:44:56.639096 6170 resource.go:168] POD                                               NODE                 PHASE   GRACE  CONDITIONS
  I0915 10:44:56.639146 6170 resource.go:175] affinity-pod1086d1b6-21f6-439d-8702-196ed94e77fd  i-099e08745cf2dac00  Failed         [{PodReadyToStartContainers False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC PodFailed } {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC PodFailed } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  }]
```

**Comment by chengjoey** [comment]
> > From the current e2e test results, the final state may be Succeed or Failed, seems pod.Status.Phase is empty.
> 
> @chengjoey The links to the failed E2E tests in the overview of this issue all show the Pod phase as `Failed`, but is there a link available somewhere for cases where it's empty string?
> 
> ```
>   I0915 10:44:56.639096 6170 resource.go:168] POD                                               NODE                 PHASE   GRACE  CONDITIONS
>   I0915 10:44:56.639146 6170 resource.go:175] affinity-pod1086d1b6-21f6-439d-8702-196ed94e77fd  i-099e08745cf2dac00  Failed         [{PodReadyToStartContainers False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC PodFailed } {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC PodFailed } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  }]
> ```

In fact, these failed tests are all empty strings, because not terminated: should be followed by phase


> [FAILED] Timed out after 300.001s.
> Pod affinity-pod5ecfc1b1-95d3-4c1c-81f6-ec3a7a533436 not terminated: 
> In [It] at: k8s.io/kubernetes/test/e2e_node/restart_test.go:551 @ 09/14/24 10:33:13.346

Because my original test was written like this
```
gomega.BeTrueBecause("Pod %s not terminated: %s", pod.Name, pod.Status.Phase)
```

**Comment by toVersus** [comment]
The Pod's final state is shown as `Failed` in the dumped result immediately after the test fails.

```console
  [FAILED] in [It] - k8s.io/kubernetes/test/e2e_node/restart_test.go:551 @ 09/15/24 10:44:56.628
  I0915 10:44:56.639096 6170 resource.go:168] POD                                               NODE                 PHASE   GRACE  CONDITIONS
  I0915 10:44:56.639146 6170 resource.go:175] affinity-pod1086d1b6-21f6-439d-8702-196ed94e77fd  i-099e08745cf2dac00  Failed         [{PodReadyToStartContainers False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC PodFailed } {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC PodFailed } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-09-15 10:39:57 +0000 UTC  }]
```

The `pod.Status.Phase` referenced inside `gomega.BeTrueBecause` - is that coming from the Pod information fetched within `gomega.Eventually`? Could it be that it's showing up as an empty string because it's not able to access the value externally?

```go
			gomega.Eventually(ctx, func() bool {
				pod, err = e2epod.NewPodClient(f).Get(ctx, podName, metav1.GetOptions{})
				framework.ExpectNoError(err)
				return pod.Status.Phase == v1.PodSucceeded
			}, recoverTimeout, f.Timeouts.Poll).Should(gomega.BeTrueBecause("Pod %s not terminated: %s", pod.Name, pod.Status.Phase))
```

**Comment by chengjoey** [comment]
@toVersus In the tests submitted previously, and in my local(minnikube) tests, the pod status will change from `Failed` to `Succeed` again

see this log step 3


> 07:12:43.251602 1932567 status_manager.go:872] "Patch status for pod" pod="default/app" podUID="eea5fa4a-6ea5-43c4-926a-fc95b6925ed8" patch="{\"metadata\":{\"uid\":\"eea5fa4a-6ea5-43c4-926a-fc95b6925ed8\"},\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"PodReadyToStartContainers\"},{\"type\":\"Initialized\"},{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[{\"reason\":\"PodCompleted\",\"type\":\"Initialized\"},{\"reason\":\"PodCompleted\",\"type\":\"Ready\"},{\"reason\":\"PodCompleted\",\"type\":\"ContainersReady\"}],\"phase\":\"Succeeded\"}}"

So I think the order of state changes affects the final result, and this is not very stable

**Comment by toVersus** [comment]
I think this is a separate issue, so as I mentioned in https://github.com/kubernetes/kubernetes/pull/124445#discussion_r1733825015, I thought it might be fine to wait for either the `Failed` or `Succeeded` phase. However, after looking at [Sergey's comment](https://github.com/kubernetes/kubernetes/pull/124445#discussion_r1759138289), it seems that we may need to resolve this unstable final result first.

@SergeyKanzhelev WDYT?

**Comment by SergeyKanzhelev** [comment]
> I think this is a separate issue, so as I mentioned in [#124445 (comment)](https://github.com/kubernetes/kubernetes/pull/124445#discussion_r1733825015), I thought it might be fine to wait for either the `Failed` or `Succeeded` phase. However, after looking at [Sergey's comment](https://github.com/kubernetes/kubernetes/pull/124445#discussion_r1759138289), it seems that we may need to resolve this unstable final result first.
> 
> @SergeyKanzhelev WDYT?

If we can explain different results, it is fine. I don't want unexplained check for either condition in our tests
