### ISSUE TITLE
kubeadm config images list does not provide the correct version of the images

### ISSUE THREAD

**Issue by icebluey** [kubernetes/kubernetes#127350]
### What happened?

The command `kubeadm config images list` does not provide the correct version of the image
```
[root@localhost]# ./kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.1", GitCommit:"948afe5ca072329a73c8e79ed5938717a5cb3d21", GitTreeState:"clean", BuildDate:"2024-09-11T21:26:49Z", GoVersion:"go1.22.6", Compiler:"gc", Platform:"linux/amd64"}
[root@localhost]#
[root@localhost]# ./kubeadm config images list
registry.k8s.io/kube-apiserver:v1.31.0
registry.k8s.io/kube-controller-manager:v1.31.0
registry.k8s.io/kube-scheduler:v1.31.0
registry.k8s.io/kube-proxy:v1.31.0
registry.k8s.io/coredns/coredns:v1.11.3
registry.k8s.io/pause:3.10
registry.k8s.io/etcd:3.5.15-0
[root@localhost]# 
```

```
[root@localhost]# ./kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.5", GitCommit:"74e84a90c725047b1328ff3d589fedb1cb7a120e", GitTreeState:"clean", BuildDate:"2024-09-12T00:17:07Z", GoVersion:"go1.22.6", Compiler:"gc", Platform:"linux/amd64"}
[root@localhost]#
[root@localhost]# ./kubeadm config images list
I0913 15:27:16.104557    1624 version.go:256] remote version is much newer: v1.31.0; falling back to: stable-1.30
registry.k8s.io/kube-apiserver:v1.30.4
registry.k8s.io/kube-controller-manager:v1.30.4
registry.k8s.io/kube-scheduler:v1.30.4
registry.k8s.io/kube-proxy:v1.30.4
registry.k8s.io/coredns/coredns:v1.11.3
registry.k8s.io/pause:3.9
registry.k8s.io/etcd:3.5.15-0
[root@localhost]# 

```

### What did you expect to happen?

To provide the correct version of the images.

### How can we reproduce it (as minimally and precisely as possible)?

```
wget https://dl.k8s.io/release/v1.31.1/bin/linux/amd64/kubeadm
chmod 0755 kubeadm
./kubeadm version
./kubeadm config images list
```

```
wget https://dl.k8s.io/release/v1.30.5/bin/linux/amd64/kubeadm
chmod 0755 kubeadm
./kubeadm version
./kubeadm config images list
```

### Kubernetes version

kubeadm v1.31.1 and v1.30.5

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by carlory** [comment]
![image](https://github.com/user-attachments/assets/0245f523-a3e6-4ff5-81c7-066dbec42b18)

**Comment by mbleichner** [comment]
```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.1", GitCommit:"948afe5ca072329a73c8e79ed5938717a5cb3d21", GitTreeState:"clean", BuildDate:"2024-09-11T21:26:49Z", GoVersion:"go1.22.6", Compiler:"gc", Platform:"linux/amd64"}
```

```
# kubeadm upgrade plan
[preflight] Running pre-flight checks.
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: 1.31.0
[upgrade/versions] kubeadm version: v1.31.1
[upgrade/versions] Target version: v1.31.0
[upgrade/versions] Latest version in the v1.31 series: v1.31.0
```

**Comment by saschagrunert** [comment]
Hm, we changed to the production bucket with the latest series of patches. [Looking at the v1.30.5 release logs](https://console.cloud.google.com/cloud-build/builds/4e87b2c9-8cb0-4b4d-b47b-82294dda2f2f?project=kubernetes-release-test), it seems to look correct:

```
Step #4: INFO[2024-09-12T02:54:40Z] Publishing version                           
Step #4: INFO[2024-09-12T02:54:40Z] Version marker path is gs://767373bbdcb8270361b96548387bf2a9ad0d48758c35/release 
Step #4: INFO[2024-09-12T02:54:40Z] Release path is gs://767373bbdcb8270361b96548387bf2a9ad0d48758c35/release/v1.30.5 
Step #4: INFO[2024-09-12T02:54:42Z] Publish version markers: [stable stable-1 stable-1.30] 
Step #4: INFO[2024-09-12T02:54:42Z] Publish official pointer text files to gs://767373bbdcb8270361b96548387bf2a9ad0d48758c35/release 
Step #4: INFO[2024-09-12T02:54:42Z] Testing v1.30.5 > stable.txt (published)     
Step #4: INFO[2024-09-12T02:54:43Z] Not updating version, because v1.30.5 <= v1.31.0 
Step #4: INFO[2024-09-12T02:54:43Z] Skipping stable.txt for v1.30.5 because it does not need to be updated 
Step #4: INFO[2024-09-12T02:54:43Z] Testing v1.30.5 > stable-1.txt (published)   
Step #4: INFO[2024-09-12T02:54:44Z] Not updating version, because v1.30.5 <= v1.31.0 
Step #4: INFO[2024-09-12T02:54:44Z] Skipping stable-1.txt for v1.30.5 because it does not need to be updated 
Step #4: INFO[2024-09-12T02:54:44Z] Testing v1.30.5 > stable-1.30.txt (published) 
Step #4: INFO[2024-09-12T02:54:46Z] Updating version, because v1.30.5 > v1.30.4  
Step #4: INFO[2024-09-12T02:54:46Z] Using marker path: gs://767373bbdcb8270361b96548387bf2a9ad0d48758c35/release 
Step #4: INFO[2024-09-12T02:54:46Z] Using public link: https://dl.k8s.io/release/stable-1.30.txt 
Step #4: INFO[2024-09-12T02:54:48Z] Validating uploaded version file at https://dl.k8s.io/release/stable-1.30.txt 
Step #4: INFO[2024-09-12T02:54:48Z] Version equals response   
```

But it clearly isn't:
```
> curl -L https://dl.k8s.io/release/stable-1.30.txt
v1.30.4
```

**Comment by saschagrunert** [comment]
@aarnaud can you inspect `gs://767373bbdcb8270361b96548387bf2a9ad0d48758c35/release/stable-1.30.txt`, so that we can verify that this command succeeded?

https://github.com/kubernetes/release/blob/2fe57c3c3106ead997312f40b209055e86edd2c5/pkg/release/publish.go#L363-L372

We may also made a mistake wrt the `publishFileDst` variable. :thinking:

**Comment by ameukam** [comment]
@saschagrunert Did you want to tag me ? :D

I double-checked and the issue is accurate. The issue is affecting all the version markers for the patch releases of last week.

```bash
gcloud storage cat gs://767373bbdcb8270361b96548387bf2a9ad0d48758c35/release/stable-1.28.txt --project k8s-infra-releases-prod
v1.28.13
```

**Comment by saschagrunert** [comment]
> @saschagrunert Did you want to tag me ? :D
Oops sorry fixed that.

> I double-checked and the issue is accurate. The issue is affecting all the version markers for the patch releases of last week.
> 
> ```shell
> gcloud storage cat gs://767373bbdcb8270361b96548387bf2a9ad0d48758c35/release/stable-1.28.txt --project k8s-infra-releases-prod
> v1.28.13
> ```

Then we do not upload the markers correctly :thinking:

**Comment by saschagrunert** [comment]
Trying to dig into this and found an issue (https://github.com/kubernetes/release/pull/3763/files), but that's not the root cause for this one.

@ameukam by the time, can we manually update the markers for 1.28-1.31 for now? I tried but don't have the permissions as it seems.

**Comment by saschagrunert** [comment]
Ah @ameukam I think there is something wrong with the bucket:

```
gsutil cat gs://767373bbdcb8270361b96548387bf2a9ad0d48758c35/release/stable-1.30.txt
v1.30.4
```

But looking online: https://console.cloud.google.com/storage/browser/_details/767373bbdcb8270361b96548387bf2a9ad0d48758c35/release/stable-1.30.txt;tab=version_history

![screenshot](https://github.com/user-attachments/assets/a786c133-5be3-4722-a357-1e319330ecb6)

The version from Sep 12 contains the right release version. :thinking:

**Comment by ameukam** [comment]
@saschagrunert We use object versioning. I think something went wrong during the release process. The version markers should expose the right version.

**Comment by BenTheElder** [comment]
Did we forget to turn down the bucket sync? If not, then these got overwritten by the old bucket I'd guess. That's an easy fix at least 😅

**Comment by ameukam** [comment]
> Did we forget to turn down the bucket sync? If not, then these got overwritten by sync from the old bucket I'd guess. That's an easy fix at least 😅

Great idea! I disabled the sync job. 
I think we need to wait Oct 24 to validate this and we should probably track this in a separate issue.

**Comment by saschagrunert** [comment]
> Did we forget to turn down the bucket sync? If not, then these got overwritten by sync from the old bucket I'd guess. That's an easy fix at least 😅

Awesome, that makes so much sense now.

**Comment by pacoxu** [comment]
- https://cdn.dl.k8s.io/release/stable-1.31.txt is correct now: v1.31.1
- https://cdn.dl.k8s.io/release/stable-1.txt is still v1.31.0

**Comment by BenTheElder** [comment]
I thought we fixed this weeks ago? I had a chat with marko and he said arnaud corrected the file.

I guess we missed stable-1?

This shouldn't keep happening, now that the sync job is disabled.
It should get naturally corrected when 1.31.2 releases, in the worst case. October's patch releases are coming in a few days https://kubernetes.io/releases/patch-releases/

NOTE: I don't actually have access to write to this bucket. We could escalate access for someone else, but currently I think it's just arnaud (for the purposes of handling the migration) + the automation (for publishing releases securely going forward).

**Comment by saschagrunert** [comment]
@ameukam are you able to correct the stable-1 marker?

We can track this issue after the next weeks patches and skim through the logs to see if the file gets updated correctly.

**Comment by ameukam** [comment]
I'll take care of this before EoW. I'm a little away from OSS work currently.

**Comment by ameukam** [comment]
@saschagrunert I think we can close this ?
