### ISSUE TITLE
windows node join to linux master kubelet failed

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#127311]
### What happened?

![image](https://github.com/user-attachments/assets/68a7e2d1-5670-41c8-862e-8526374c529e)

### What did you expect to happen?

join success

### How can we reproduce it (as minimally and precisely as possible)?

**安装git**

https://git-scm.com/download/win

**安装containerd**

```
.\Install-Containerd.ps1
```

**加入集群**

```
# 自动初始化Windows 下 kubernetes 的脚本
https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/Install-Containerd.ps1
https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/PrepareNode.ps1

https://dl.k8s.io/v1.31.0/kubernetes-node-windows-amd64.tar.gz

unzip kubernetes-node-windows-amd64.tar.gz
mv bin files to k directory

https://k8stestinfrabinaries.blob.core.windows.net/nssm-mirror/nssm-2.24.zip

https://github.com/Microsoft/SDN/raw/master/Kubernetes/windows/hns.psm1

https://github.com/rancher/wins/releases/download/v0.0.4/wins.exe

PrepareNode.ps1注释下面内容，自己下载
<#
DownloadFile $kubeletBinPath https://dl.k8s.io/$KubernetesVersion/bin/windows/amd64/kubelet.exe
DownloadFile "$global:KubernetesPath\kubeadm.exe" https://dl.k8s.io/$KubernetesVersion/bin/windows/amd64/kubeadm.exe
DownloadFile "$global:KubernetesPath\wins.exe" https://github.com/rancher/wins/releases/download/v0.0.4/wins.exe
#>

mkdir c:\k

upload file to c:\k

.\PrepareNode.ps1 -KubernetesVersion v1.31.0 -ContainerRuntime  containerD

kubeadm token create --print-join-command

.\kubeadm token create --print-join-command
kubeadm join 192.168.229.180:6443 --token mcpuze.9xgaztfwhbwoz62p --discovery-token-ca-cert-hash sha256:ce6b446b6fca5e82fdf104d82cc8a786789d1a4fc1168afb2373f049ecc77bf5 
```

### Kubernetes version

<details>

1.31.0

</details>

### Cloud provider

<details>
wmware workstation
</details>

### OS version

<details>

`windows server 2022 data center

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Ritikaa96** [comment]
/kind support
This might occur either when kubelet is not successfully accessible or running on said node .
Please check the kubelet service status  on the node and retry.

**Comment by Ritikaa96** [comment]
You can check the kubelet status using command
```bash
service status kubelet
```

**Comment by 13567436138** [comment]
windows node

**Comment by 13567436138** [comment]
kubelet is running

**Comment by 13567436138** [comment]
Windows do not support cgroup ,should i remove cgroupDriver config from kubelet config

**Comment by neolit123** [comment]
this repo is not for support requests. please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

you can use this:
https://github.com/kubernetes-sigs/sig-windows-tools/issues/375

/close
/sig windows
