### ISSUE TITLE
Links in API are broken and point to HEAD

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#12738]
The links in the API point to missing directories and you get a 404. The location of files have moved (see #11239). Also, these links should be version specific and point to the corresponding set of documents on k8s.io (and not point to the development version in the master branch).

Example:
Out in k8s.io, the links in this section of the API result in 404: http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_awselasticblockstorevolumesource

Here is one of the links that's broken:
http://releases.k8s.io/HEAD/docs/volumes.md#awselasticblockstore
     - The correct location in Master is:
     http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#awselasticblockstore

**For all of the links in the API pages out on k8s.io:**
The correct link for the example above is:
http://kubernetes.io/v1.0/docs/user-guide/volumes.html#awselasticblockstore

And any other link in the page http://kubernetes.io/v1.0/docs/api-reference/definitions.html should be updated (and fixed if it points to a file that have moved):

From: "http://releases.k8s.io/HEAD/docs/*" 

To: "http://kubernetes.io/v1.0/docs/*"

**Comment by RichieEscarez** [comment]
I have also found that sections are missing from the TOC, for example v1.Container is not listed at the top of the page:

http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_container

**Comment by caesarxuchao** [comment]
>I have also found that sections are missing from the TOC, for example v1.Container is not listed at the top of the page:
http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_container

That's because we only list top level API Objects in the TOC, i.e., the objects that are not a field of other objects.

**Comment by caesarxuchao** [comment]
@RichieEscarez  I've sent #12761 to fix. Thank you for taking care of the pages.

We will need to generate these html files again after #10933 got merged.

**Comment by caesarxuchao** [comment]
Fixed by #12761. Closing.
