### ISSUE TITLE
Setting externalIPs to the same IP as one node, renders the node unaccessible

### ISSUE THREAD

**Issue by lboclboc** [kubernetes/kubernetes#127410]
### What happened?

We switched to use ipvs-mode for kube-proxy and by mistake we had a number of services defining the field "externalIPs" to the IP-address of one of the nodes.
This resulted in that this node became unavailable from a number of other nodes, not even by ping. As far as I could see the nodes affected where nodes running pods for those bad services.
What happened was that kube-proxy created a route entry in the table "local" for the unavailable node on each of the nodes running the affected pods. (A local route will then not forward traffic but just make the traffic go to current node)

### What did you expect to happen?

kube-proxy should not have allowed this externalIPs address, or at least not created the route entry in the local table

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod and corresponding service where the service externalIPs is set to one of the worker nodes real IP. Make sure to set kube-proxy to run in ipvs-mode.

### Anything else we need to know?

We are using two IP-addresses on our nodes for more IP-range. I don't think this would affect this situation but just for info.

### Kubernetes version

<details>

```console
Client Version: v1.30.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5
```

</details>

### Cloud provider

<details>
Locally bare-metal cluster.
</details>

### OS version

<details>

```console
Linux px2csw20 5.15.0-121-generic #131-Ubuntu SMP Fri Aug 9 08:29:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Manual install but maintenance with puppet 
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
flannel, rook-ceph
</details>

**Comment by aojea** [comment]
/area ipvs

It is a "fat-fingers" kind of mistake that because of the implementation details of ipvs turned into a problematic result ... @uablrek do you know if there are some guardrails that can be implemented to prevent this kind of scenarios?

I think the main problem is that the local route takes over the entire IP, if it just took only the IP:Port:protocol , will that help?

**Comment by uablrek** [comment]
Similar issues have been raised before, e.g
* https://github.com/kubernetes/kubernetes/issues/123992
* https://github.com/kubernetes/kubernetes/pull/115019
* https://github.com/kubernetes/kubernetes/issues/114815

Check also the "strictARP" setting. If not set, _all_ nodes will respond ARPs for the externalIP's, which happens to be _one_ nodes real IP. So where the packet ends up is unpredictable

**Comment by lboclboc** [comment]
> /area ipvs
> 
> It is a "fat-fingers" kind of mistake that because of the implementation details of ipvs turned into a problematic result ... @uablrek do you know if there are some guardrails that can be implemented to prevent this kind of scenarios?
> 
> I think the main problem is that the local route takes over the entire IP, if it just took only the IP:Port:protocol , will that help?

Just taking over the port would be no problem. As it is now anyone that can create a svc, in any namespace can basically krash the cluster

**Comment by uablrek** [comment]
> I think the main problem is that the local route takes over the entire IP, if it just took only the IP:Port:protocol , will that help?

Ipvs doesn't work that way. To route packets to ipvs you must use, well... a route. And that is L3.

**Comment by uablrek** [comment]
If the "probablility-ladder" (my word) in proxy-mode=iptables is the problem, please switch to proxy-mode=nftables instead (it uses a hash). IMO proxy-mode=ipvs is a dead end, and a big reason is the route requirement. A `-j IPVS` target for iptables would be better.

**Comment by lboclboc** [comment]
Thanks, we will switch to nftables instead then.

**Comment by uablrek** [comment]
Can we close this issue? I think nobody will try to make externalIP==nodeIP work anyway for ipvs, and the answer is really: "Don't do that".
