### ISSUE TITLE
controller package names don't match the folders

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#12741]
During the controller refactoring, the package names weren't made to match the folder names.  This is annoying an unexpected.

See https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/namespace/namespace_controller.go as an example.

**Comment by zhengguoyong** [comment]
hi deads2k,
Do you need some help?  i would happy to do some work for this.
@deads2k

**Comment by deads2k** [comment]
> hi deads2k,
> Do you need some help? i would happy to do some work for this.
> @deads2k

@zhengguoyong 

That would be great.  Can you sweep the direct subpackages from `pkg/controller` (`daemon`, `deployment`, etc)?  Most are probably ok, but some are not.

To limit the scope of the change, I'd suggest making the package names match the existing folders, but when you see them imported, you can alias them.

For example, the `pkg/controller/service` package should be `service`, but when the package is imported (like here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L52), you could make it 
```go
`servicecontroller "k8s.io/kubernetes/pkg/controller/service"
```
That way you don't have to update every line, but we don't end up weird package name collisions in code anymore.

Be sure to tag me on the pull and thanks for jumping in.

**Comment by zhengguoyong** [comment]
ok, i will send PR sooner, and then tag you for review. :)
