### ISSUE TITLE
Move scheduler fit predicates into a library

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#12744]
They are used (or will be used) by
- scheduler
- kubelet
- rescheduler (#12140)
- vertical autoscaler (#8157)
- updater (#8157)

@dchen1107 @gmarek @fgrzadkowski

**Comment by gmarek** [comment]
I'd bump the priority, as it'll be useful pretty soon.

**Comment by HaiyangDING** [comment]
Anyone has started working on this yet? I am going to start doing it.

**Comment by davidopp** [comment]
Nobody has started on it.

**Comment by HaiyangDING** [comment]
@davidopp 

Hi, would you say a little more about what we want to achieve in this issue?

Is it about moving some of the predicate functions in the scheduler to another package or what?

Big thanks in advance  :)

**Comment by gmarek** [comment]
I can give you my view on this. Currently we have a function which scheduler uses to check if Pod will fit on a given machine: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L148. But we're doing pretty similar thing in Kubelet: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1605

The implementation of this method is likely to be used in other components, like rescheduler or autoscaler, so it'd be extremely nice to have an abstraction layer on top of this logic (i.e. some interface) which we'd inject into every component that needs this.

**Comment by davidopp** [comment]
What I'd like is for us to literally invoke the same code everywhere that we apply scheduler predicate functions (like the places @gmarek  mentioned above).

I'm not enough of a Go guru to know the right way to do this -- either put it in its own new package that is imported by scheduler and kubelet (and later rescheduler etc.), or just put it in the existing scheduler or kubelet package and export it for use in the other place(s).

**Comment by HaiyangDING** [comment]
@gmarek @davidopp 

Thank you all for the explanation. I think I have got the idea, hope to send a PR sooner!

**Comment by bgrant0607** [comment]
It might be useful for replication controller manager to reuse the prioritization logic, also. #4301

**Comment by bgrant0607** [comment]
We may need to omit external extensions: #11470

**Comment by HaiyangDING** [comment]
I did not have time to do this PR in the past few days and will start working on this right away. @HaiyangDING

**Comment by davidopp** [comment]
OK. Be aware of #13580 which may conflict a bit.

**Comment by davidopp** [comment]
We should also use this when scheduling DaemonSet, to prevent the problem reported in #16967

**Comment by davidopp** [comment]
@HaiyangDING @hurf

**Comment by HaiyangDING** [comment]
Noted.

**Comment by davidopp** [comment]
Since we want this to work in a system with multiple schedulers and a rescheduler, the right factoring is probably
* a library containing the kubelet predicates; it is used by all schedulers and rescheduler
* for each scheduler S, a library containing S's additional predicates; it is used by S and the rescheduler

**Comment by HaiyangDING** [comment]
This has been delayed for a while, and the blame is on me. I will start working right away.

As for:

> Since we want this to work in a system with multiple schedulers and a rescheduler, the right factoring is probably

> - a library containing the kubelet predicates; it is used by all schedulers and rescheduler

Noted. 

> - for each scheduler S, a library containing S's additional predicates; it is used by S and the rescheduler

Does this mean we should make a library for each of schedulers in Kubernetes? For default scheduler, it is easy to do since the predicates used by default scheduler are known.

But what if for user-provided scheduler whose predicates we can not know ahead of compiling the rescheduler?

**Comment by davidopp** [comment]
> But what if for user-provided scheduler whose predicates we can not know ahead of compiling the rescheduler?

Yeah, I haven't thought much about how to structure this library and how it should interact with the components that use it. For now, I guess we will have to recompile the rescheduler whenever we introduce a new scheduler into the system. (That is, when someone implements a new scheduler, they will also need to update the rescheduler code.)

To handle the case where someone has introduced a new scheduler but has not updated the rescheduler, we could say (1) if there is a pending pod for that scheduler, rescheduler will ignore it (not try to get it to schedule); and (2) when rescheduler is considering evicting a pod, if the pod belongs to a scheduler whose predicate rules are not known to the rescheduler, rescheduler will only apply the kubelet predicate rules in computing whether the pod will be able to reschedule (thus it may evict the pod and it can't reschedule--tough luck). This provides a good incentive for people to update the rescheduler when they create a new scheduler, but doesn't break anything if they don't.

**Comment by davidopp** [comment]
[Comment below is NOT a suggestion for something to implement as part of this issue. But it seemed better to put it here than to create a new issue.]

Related to this, we should also standardize the selection criteria that are applied before a node is even considered by the predicate functions (for example, avoiding nodes with NodeReady==ConditionFalse and nodes marked unschedulable). This doesn't belong in the scheduler fit predicates, instead probably in pkg/client/cache/listers.go

**Comment by davidopp** [comment]
[@davidopp]
> Since we want this to work in a system with multiple schedulers and a rescheduler, the right factoring is probably
>
> a library containing the kubelet predicates; it is used by all schedulers and rescheduler
> for each scheduler S, a library containing S's additional predicates; it is used by S and the rescheduler

[@haiyangding]
> Does this mean we should make a library for each of schedulers in Kubernetes? For default scheduler, it is easy to do since the predicates used by default scheduler are known.
>
> But what if for user-provided scheduler whose predicates we can not know ahead of compiling the rescheduler?

Last paragraph of
https://github.com/kubernetes/kubernetes/issues/12140#issuecomment-162416243
is relevant.

**Comment by HaiyangDING** [comment]
Noted. I am working on this right now, the PR can be expected sooner.

**Comment by davidopp** [comment]
One more twist: When we implement #18261, #18265, and #18263, we'll be adding code to Kubelet that asynchronously evicts pods that no longer meet their constraints, hard anti-affinity, etc. However, not all feasibility rules should trigger eviction when they are violated; for example, if node capacity shrinks, causing machine free resources to go negative, we probably shouldn't evict any pods (if machine OOMs, then lowest-QoS pod will get killed, but there's no reason to kill proactively if it might not be necessary). So the library should probably be split into
1. predicates that cause eviction when they become violated
2. predicates that do not cause eviction when they become violated

The code in Kubelet that performs the evictions would use (1), while the code in Kubelet that checks pod feasibility when the pod arrives (before Kubelet starts the pod) would use (1) and (2). Likewise the scheduler would use (1) and (2) as well as any scheduler-specific rules.

**Comment by HaiyangDING** [comment]
> One more twist: When we implement #18261, #18265, and #18263, we'll be adding code to Kubelet that asynchronously evicts pods that no longer meet their constraints, hard anti-affinity, etc. However, not all feasibility rules should trigger eviction when they are violated; for example, if node capacity shrinks, causing machine free resources to go negative, we probably shouldn't evict any pods (if machine OOMs, then lowest-QoS pod will get killed, but there's no reason to kill proactively if it might not be necessary). So the library should probably be split into
1. predicates that cause eviction when they become violated
2. predicates that do not cause eviction when they become violated

> The code in Kubelet that performs the evictions would use (1), while the code in Kubelet that checks pod feasibility when the pod arrives (before Kubelet starts the pod) would use (1) and (2). Likewise the scheduler would use (1) and (2) as well as any scheduler-specific rules.

That sounds reasonable, then I will have a reconsideration about the implementation and fulfill the requirements here. But I have 2 questions here: 

1. Currently, where does Kubelet **proactively** iterate over its pods and decide whether some of them need to be evicted?
2. Which predicates should be considered trigger eviction and which should not be? I think predicates related to label-selecting/ports/host-name/max-pod-number should trigger eviction while those related to resource should not. Moreover, MaxPodNumber is currently verified in resource checking, we may want to separate this from memory and cpu checking given the requirement you have proposed.

**Comment by davidopp** [comment]
@jdef

**Comment by davidopp** [comment]
@HaiyangDING sorry I missed this earlier

> Currently, where does Kubelet proactively iterate over its pods and decide whether some of them need to be evicted?

AFAIK it doesn't. You'd have to add this. We can talk to @dchen1107 and @yujuhong to get suggestions about where to put it.

> Which predicates should be considered trigger eviction and which should not be? I think predicates related to label-selecting/ports/host-name/max-pod-number should trigger eviction while those related to resource should not. Moreover, MaxPodNumber is currently verified in resource checking, we may want to separate this from memory and cpu checking given the requirement you have proposed.

I think what you described sounds roughly right. We can refine it as you get closer to working on it.

**Comment by yujuhong** [comment]
@derekwaynecarr has a pod eviction proposal #18724

**Comment by davidopp** [comment]
AFAICT #18724 is just talking about eviction for OOR.

**Comment by derekwaynecarr** [comment]
Correc, #18724 is about OOR and not rescheduling.

**Comment by mikedanese** [comment]
I'm moving this into v1.2 milestone since we need it to graduate daemonset?

**Comment by davidopp** [comment]
> I'm moving this into v1.2 milestone since we need it to graduate daemonset.

@HaiyangDING said it will be done by the end of the week but can you explain why you think it's needed for 1.2? We can always continue to (figuratively) copy-paste code between the scheduler and Kubelet, as we're doing today. This issue is just a way to make this less hacky/error-prone by factoring it into a library.

**Comment by timothysc** [comment]
For * middle-ground things we've been labeling as 1.2-candidate.

**Comment by mikedanese** [comment]
In https://github.com/kubernetes/kubernetes/issues/15310#issuecomment-160033364 @davidopp said:

> We need to fix #16967 (via #12744) before graduation.

We have 3 options:

* This is either v1.2
* we need to find another way to revert #17318 safely
* we can demote this and daemonset to v1.2-candidate.

**Comment by davidopp** [comment]
Copy-paste option is still only the table and might be best approach. @mikedanese  pointed out it's not much code since Kubelet only checks resources; in particular we don't need to configure to use the same policies as the scheduler(s), just the same policy as kubelet.

**Comment by mikedanese** [comment]
The can fit predicate needs to check:
  * pod fits resource
  * pod fits ports
  * node has sufficient disk

I'll demote this to v1.2 candidate and try to the copy paste for now.

**Comment by davidopp** [comment]
@mikedanese did you do the copy paste yet? If not I can probably do it. Let me know.

**Comment by mikedanese** [comment]
@davidopp I did this last week but still need to performance test and write tests. Just sent out a WIP pr #20061

**Comment by mikedanese** [comment]
Can this be closed?

**Comment by davidopp** [comment]
I think there are still a couple of things to do (though lower-priority / not for 1.3)
https://github.com/kubernetes/kubernetes/issues/12744#issuecomment-156877624
https://github.com/kubernetes/kubernetes/issues/12744#issuecomment-164372008

**Comment by HaiyangDING** [comment]
> 

[Comment below is NOT a suggestion for something to implement as part of this issue. But it seemed better to put it here than to create a new issue.]

Related to this, we should also standardize the selection criteria that are applied before a node is even considered by the predicate functions (for example, avoiding nodes with NodeReady==ConditionFalse and nodes marked unschedulable). This doesn't belong in the scheduler fit predicates, instead probably in pkg/client/cache/listers.go


I think this is addressed (or at least partially addressed) [here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L229). No?

We could add Node.Spec.Unschedulable to the selection criteria.

**Comment by HaiyangDING** [comment]
@davidopp 

I will work on splitting the library into eviction/non-eviction categories.

**Comment by davidopp** [comment]
> I will work on splitting the library into eviction/non-eviction categories.

This is not important right now since we don't do evictions yet. It would be better if you can help @jiangyaoguo with /evict subresource, as that is higher-priority and probably will require iteration on the implementation that could take some time.

**Comment by HaiyangDING** [comment]
> This is not important right now since we don't do evictions yet. It would be better if you can help @jiangyaoguo with /evict subresource, as that is higher-priority and probably will require iteration on the implementation that could take some time.

OK.

**Comment by lukaszo** [comment]
@davidopp I think it's finished in #20204. Can it be closed or is there something more to be done?

**Comment by timothysc** [comment]
closing, please reopen if needed.
