### ISSUE TITLE
Document how to specify hostname / IP for livenessProbe

### ISSUE THREAD

**Issue by devurandom** [kubernetes/kubernetes#12740]
I am trying to setup Kubernetes v1.0.3 using the hyperkube images. I noticed that for kube-controller-manager, the livenessProbe tries to GET `http://192.168.10.24:10251/healthz`, but the controller-manager actually listens on localhost:
```
$ sudo netstat -nptul | grep 10252
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      15568/hyperkube
```

Thus I need to modify the livenessProbe to connect to localhost instead. How do I do that?

**Comment by devurandom** [comment]
`"host": "127.0.0.1"` does the trick, but seems to be nowhere documented. Especially not in the `scratch.md` guide, which does not work without this.

**Comment by aveshagarwal** [comment]
I am wiling to help with this.

**Comment by devurandom** [comment]
Maybe together we can improve the `scratch.md` guide? It seems to be the most central piece to understand how kubernetes is supposed to work.

I still have to write about the authentication part (#11000). Maybe you could have a look at the pod descriptions?

**Comment by aveshagarwal** [comment]
https://github.com/kubernetes/kubernetes/pull/13220 to address this issue.
