### ISSUE TITLE
Need emulation version guidance on how to perserve disabled feature gate tests for LockToDefault features 

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#127477]
After promoting `RetryGenerateName` to GA and setting `LockToDefault: true` for the feature, I got failing tests such as:

```
store_test.go:450: error setting RetryGenerateName=false: cannot set feature gate RetryGenerateName to false, feature is locked to true
```

Before emulation versioning, this failure made a lot of sense. There was no way to disable the feature, so tests for feature disablement serve no purpose and should be removed.

But with the presence of emulation version, should I remove these tests?  The system can be put into a state where the feature is disabled. So it seems like the test should be preserved.

One option would be to add something like this to the test:

```
featuregatetesting.SetFeatureGateEmulationVersionDuringTest(t, utilfeature.DefaultFeatureGate, version.MustParse("1.31"))
```

Another would be to change how `SetFeatureGateDuringTest` to allow features to be disabled even if LockedToDefault on the current version.

**Comment by jpbetz** [comment]
/sig api-machinery

cc @Jefftree @aaron-prindle

**Comment by Jefftree** [comment]
> But with the presence of emulation version, should I remove these tests? The system can be put into a state where the feature is disabled. So it seems like the test should be preserved.

hmm this is an interesting case. Normally things like e2e tests are versioned so we'd be able to do something like run the n-1 version's e2e tests against version n at emulation version n-1. Unit tests don't make as much sense to run in this manner. Explicitly passing the emulation version when setting the feature gate could work, but I'm wondering if we'd be making too many assumptions about other things like available apis, storage versions, etc that are hard to control via unit test.

**Comment by jpbetz** [comment]
If the purpose of the test is to show that some aspect of the system works when a feature is disabled, and it's possible for the feature to be somehow disabled, is the test useful?

I started to think about if we should change `SetFeatureGateDuringTest` to to disable a `LockedToDefault` feature.  The only objection I had to that was that it can put the system into a state that can't actually happen (RetryGenerateName disabled, emulation version: 1.32). So I instead set emulation version to a version where the feature can be disabled.  This has the advantage of putting the system into a valid state, but the disadvantage of requiring additional changes when promoting a feature to GA than would be required if the tests "just worked".

**Comment by Jefftree** [comment]
Yeah the downsides I see are additional work when feature goes to GA and also additional work when the feature is removed. Eventually, 1.31 will go out of n-3 and disabling will be impossible so the test will need to be removed. If this is only required for beta -> GA transitions I would imagine it's not too much work to add the emulation version explicitly for disablement tests. 

I do agree that the test is definitely useful since the disabled state is valid under the current binary version (with a <=n-1 emulation version). For conformance tests we are required to include the version introduced information in the comments, I wonder if there's benefit in programmatically including version information in feature tests.

**Comment by jpbetz** [comment]
Sounds good. I'll leave this open for a few days to allow others to voice opinions, and if there are no objections I'll close it with the conclusion that we should add `SetFeatureGateEmulationVersionDuringTest` to this sort of test when promoting to GA.

**Comment by sftim** [comment]
BTW, do we have a KEP for version emulation?

**Comment by aojea** [comment]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/4330-compatibility-versions/README.md

**Comment by Jefftree** [comment]
Fixed by https://github.com/kubernetes/community/pull/8087
