### ISSUE TITLE
CRI proxy for e2e_node tests

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#127459]
In order to simulate failures and delays in CRI API, we may need to introduce the CRI API proxy in our e2e_node tests.

The proxy will be instantiated inside the test framework and if no failures or delays were injected, simply proxies all the calls to the container runtime. If we see it is reliable enough, we can configure it for all e2e_node tests to minimize the configuration required. If we cannot make it reliable enough, than it should be enabled by test configuration, or even configured by test itself by overwriting kubelet config and restarting the kubelet. I think preferred approach would be enabling by test configuration similar how we enable standalone mode: https://github.com/kubernetes/kubernetes/blob/283ff763b3fd82c831f1f45efa87fb2aa518d184/test/e2e_node/e2e_node_suite_test.go#L111

The example of failure injection tests in e2e_node may be found here: test/e2e_node/testdeviceplugin/device-plugin.go 

As the first set of tests, I suggest we implement a better set of tests than those: https://github.com/kubernetes/kubernetes/pull/121604. This will allow to GA the KEP: https://github.com/kubernetes/enhancements/issues/3673

/sig node
/area test
/kind cleanup
/help

**Comment by zhifei92** [comment]
I want to try to do this

/assign

**Comment by SergeyKanzhelev** [comment]
> > I think preferred approach would be enabling by test configuration similar how we enable standalone mode
> 
> @SergeyKanzhelev Do you mean that all CRI API calls will inject errors or delays based on the configuration? Will existing test cases be affected?

No, I mean the CRI API proxy will be configured when some argument is passed to the test binary. Each test will be able to inject errors by itself

**Comment by SergeyKanzhelev** [comment]
Some clarification of an ask here:

1. Test framework will start a CRI proxy service. Same way as it serves a rudimentary API server or how device plugin is being created here: test/e2e_node/testdeviceplugin/device-plugin.go
2. Test framework will edit kubelet configuration - it will configure kubelet to use those proxies as a runtime.
3. Test will configure the failure injection.
4. Test will do some operations like schedule a Pod. Since kubelet is connected via proxy, those operation will call the proxy and some of these calls will fail due to the failure injection.
5. Test will validate that kubelet behaved as expected when experienced this failure from the runtime (cri proxy).
