### ISSUE TITLE
integrate kubelet with the systemd watchdog

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#127460]
Implement the [systemd watchdog](https://0pointer.de/blog/projects/watchdog.html) in kubelet. Similar to https://github.com/containerd/containerd/issues/10329, we want to have a lightweight way to health check kubelet instead of requiring to run the health check process `curl`-ing the `/healthz` endpoint.

Implementation will require integrating with watchdog API, hooking those with the same checks that `/healthz` performs, and implement some e2e_node tests demonstrating this behavior. Documentation should be updated once implemented as well.

/sig node
/area kubelet
/kind feature

/good-first-issue
/help

**Comment by RocooHash** [comment]
I can give this a shot 

/assign

**Comment by yunzck8s** [comment]
I want to try it too

/assign

**Comment by ajit97singh** [comment]
I want to try it too

/assign

**Comment by zhifei92** [comment]
I would like to work on this, but if anyone has already started working on it, I can stop.

/assign

**Comment by Shresth72** [comment]
I want to give this a try too

/assign

**Comment by SergeyKanzhelev** [comment]
For everybody who signed up to try it, this PR is going to the right direction: https://github.com/kubernetes/kubernetes/pull/127566 but has some shortcomings. I commented on PR, listing here:

1. There should be no change of behavior when watchdog is not enabled (it is OK for 1 info message that it is not enabled, but NOT ok to report an error)
2. There should be no change of behavior on Windows. Do not even report that it is not enabled
3. When watchdog is enabled, but we failed to configure kubelet - kubelet should not start (e.g. time is not configured correctly)
4. The loop checks must be as lightweight as you can make them. Minimum allocations and no locks
5. Try to avoid false positives as much as possible.

PR should include code and unit tests. If you have a good idea on how to test e2e by emulating `daemon.Foo` behavior - it is an extra bonus.

**Comment by pravin-rgb** [comment]
Hi @SergeyKanzhelev 
I am new to the community.
I am new contributor I want to try it .If its fixed that's fine.
If their are still some beginner friendly or good-first issues for me to try and explore .That's appreciable.
Let me know.
Thank you.
/assign

**Comment by zhifei92** [comment]
> I am a new contributor I want to try it .If its fixed that's fine.

Thank you for your interest in this issue. I am working on this PR：https://github.com/kubernetes/kubernetes/pull/127566#issuecomment-2416311736

**Comment by SergeyKanzhelev** [comment]
/remove-help
/remove-good-first-issue

since @zhifei92 is working on it already

**Comment by pravin-rgb** [comment]
@zhifei92 Thanks for notifying me. Have a great day
