### ISSUE TITLE
TLS Error with Karpenter Liveness and Readiness Probes: remote error: tls: unrecognized name

### ISSUE THREAD

**Issue by oluranticode** [kubernetes/kubernetes#127419]
### What happened?

I am deploying Karpenter on my EKS cluster via ArgoCD, and I am encountering TLS errors on the liveness and readiness probes. The errors are as follows:

Readiness probe failed: Get "https://10.0.x.x:8443/": remote error: tls: unrecognized name
Liveness probe failed: Get "https://10.0.x.x:8443/": remote error: tls: unrecognized name

I have set up a wildcard DNS for *.mydom.com, and Karpenter is using a TLS certificate with karpenter.mydom.com as the common name (CN). Despite my configuration, the probes keep failing due to a TLS handshake issue.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: karpenter
namespace: argocd
spec:
project: system
source:
repoURL: 'https://charts.karpenter.sh/'
chart: karpenter
targetRevision: {{ index .Values "targetRevision" "karpenter" }}
helm:
values: |
clusterName: "cliniify-cluster"
clusterEndpoint: "[https://A1B2C3D4E$%RF6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0.us-west-2.eks.amazonaws.com](https://a1b2c3d4e$%25rf6g7h8i9j0k1l2m3n4o5p6q7r8s9t0.us-west-2.eks.amazonaws.com/)"
defaultInstanceProfile: "KarpenterInstanceProfile"
controller:
livenessProbe:
httpGet:
scheme: HTTPS
host: karpenter.kube-system.svc.cluster.local # Service DNS
port: 8443
httpHeaders:
- name: Host
value: karpenter.mydomain.com
readinessProbe:
httpGet:
scheme: HTTPS
host: karpenter.kube-system.svc.cluster.local
port: 8443
httpHeaders:
- name: Host
value: karpenter.mydomain.com
tls:
secretName: karpenter-tls
serviceName: karpenter # Service name
namespace: kube-system # Namespace of the secret
keyFile: tls.key
certFile: tls.crt
destination:
server: 'https://kubernetes.default.svc/'
namespace: kube-system
syncPolicy:
automated:
prune: true # Optional: Automatically delete resources that are no longer defined in the source
selfHeal: true # Optional: Automatically correct any deviations from the desired state
syncOptions:
- ApplyOutOfSyncOnly=true

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
name: karpenter-cert
namespace: kube-system
spec:
secretName: karpenter-tls
duration: 24h
renewBefore: 12h
commonName: karpenter.mydomain.com
dnsNames:
- karpenter.mydomain.com
- karpenter.kube-system.svc.cluster.local
issuerRef:
name: letsencrypt-prod
kind: ClusterIssuer
privateKey:
algorithm: RSA
size: 2048

### What did you expect to happen?

The probes should pass successfully without TLS errors, and the liveness and readiness checks should not fail due to mismatched certificate names.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy Karpenter using Helm via ArgoCD.
Configure TLS with a cert-manager Certificate for karpenter.mydom.com.
Apply readiness and liveness probes using the service IP (10.0.x.x).
Observe the repeated TLS errors in the pod logs.

### Anything else we need to know?

What I’ve Tried:

Created a Certificate using cert-manager with the CN set to karpenter.mydomain.com.
Configured a wildcard DNS record (*.mydomain.com) pointing to the Kubernetes LoadBalancer.
Updated the liveness and readiness probes to use both the service DNS (karpenter.kube-system.svc.cluster.local) and the service IP (10.0.x.x).
Disabled the liveness probe as a temporary workaround.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Kustomize Version: v4.5.7

</details>


### Cloud provider

<details>
AWS
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
This seems like an issue that should be filed with the karpenter project?

https://github.com/kubernetes-sigs/karpenter/issues

cert-manager, karpenter, and argoCD are not part of this repo.
