### ISSUE TITLE
elasticsearch/elasticsearch_discovery.go is failing to discover

### ISSUE THREAD

**Issue by ryfow** [kubernetes/kubernetes#12749]
I get this when trying to start the elasticsearch example.

```
I0814 20:01:33.272686       7 elasticsearch_discovery.go:42] Elasticsearch discovery
I0814 20:01:33.272788       7 elasticsearch_discovery.go:52] Server: https://10.100.0.1:443
I0814 20:01:33.272861       7 elasticsearch_discovery.go:53] Namespace: "default"
I0814 20:01:33.272886       7 elasticsearch_discovery.go:54] selector: "name=elasticsearch"
F0814 20:01:33.304261       7 elasticsearch_discovery.go:73] Failed to list pods: the server could not find the requested resource
```

If I'm debugging this right, it looks like `/elasticsearch_discovery` in `kubernetes/elasticsearch:1.0` is trying to hit `v1beta3` which doesn't exist anymore.

**Comment by jimmidyson** [comment]
@ryfow You're better off using the Elasticsearch Kubernetes discovery plugin from https://github.com/fabric8io/elasticsearch-cloud-kubernetes. @pires has an example of it's use at https://github.com/pires/kubernetes-elasticsearch-cluster.

**Comment by ryfow** [comment]
Thanks @jimmidyson. That looks like it'll meet my needs.

I'd suggest that the elasticsearch example in this repository should either work or be deleted.

**Comment by jimmidyson** [comment]
@pires Fancy contributing your excellent elasticsearch work to replace the broken elasticsearch example in this repo?

**Comment by pires** [comment]
@jimmidyson thanks for your kind words!
I'm always happy to contribute.  I'll try and have it by monday.

**Comment by pires** [comment]
Oh, https://github.com/kubernetes/kubernetes/pull/12621 seems to fix it.

**Comment by jimmidyson** [comment]
Well personally I think the Elasticsearch plugin approach is cleaner, but I guess as long as it works...

**Comment by pires** [comment]
@jimmidyson I agree and have tried to push my work before, but the current _official_ way was preferred.

**Comment by jimmidyson** [comment]
@satnam6502 Still don't want to go down the Elasticsearch discovery plugin route rather than the custom go binary?

**Comment by satnam6502** [comment]
Plugin would be great.

**Comment by pires** [comment]
Working on that then.

**Comment by pires** [comment]
@satnam6502 would you be willing to joint effort for this? I already have it working but want to minimize changes to what you have already provided.

**Comment by satnam6502** [comment]
I am happy to help in any way -- esp. if we can do it ssonish since I only have two weeks left at Google.

**Comment by pires** [comment]
@satnam6502 what's your timezone? Can we try tomorrow on IRC?

**Comment by satnam6502** [comment]
Pacific, I work at Google HQ in Mountain View.
I get very little in the way of sleep so I am very open to very early or
very late meetings.

**Comment by pires** [comment]
10am EST is doable?

**Comment by satnam6502** [comment]
(switching to email to continue discussion)

**Comment by satnam6502** [comment]
If you look at #12644 you will see that at least for GCE things seem to be working. I think it would be better to open a new issue about updating/merging the Elasticsearch examples -- as discussed over VC today.
