### ISSUE TITLE
rbd plugin two mountpoints

### ISSUE THREAD

**Issue by bliss** [kubernetes/kubernetes#12746]
Good day!
Could anyone please shed some light why rbd plugin mounts ceph **rbd** device twice?
this is mount command output
`
/dev/rbd0 on /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/rbd-image-nginxy-nginx-drive__SEP__bliss type ext4 (rw,relatime,seclabel,stripe=1024,data=ordered)
`
`
/dev/rbd0 on /var/lib/kubelet/pods/b0ba3df0-42b1-11e5-8717-52540051caca/volumes/kubernetes.io~rbd/usr-share-nginx-html3648334128 type ext4 (rw,relatime,seclabel,stripe=1024,data=ordered)
`
this is rbd showmapped output
`
0  rbd  nginxy-nginx-drive__SEP__bliss -    /dev/rbd0
`
Thank you!

**Comment by thockin** [comment]
@rootfs for help

**Comment by rootfs** [comment]
The first mount is the kubelet volume plugin space. A unique rbd is mounted only once under `var/lib/kubelet/plugin`.

Second mount is in the Pod's volume storage space, it is a bind mount to the kubelet's volume.

**Comment by bliss** [comment]
Thank you very much!

**Comment by bliss** [comment]
Good day. Container on rbd persistent volume fails because of selinux:
```
SELinux is preventing /usr/sbin/mysqld from write access on the directory /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/rbd-image-wp-disk__SEP__bliss
If you want to allow mysqld to have write access on the rbd-image-wp-disk__SEP__bliss directory
...
Do
# semanage fcontext -a -t FILE_TYPE '/var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/rbd-image-wp-disk__SEP__bliss'
where FILE_TYPE ...: cgroup_t, docker_var_lib_t, svirt_home_t, svirt_sandbox_file_t, virt_home_t.
```
docker logs for mariadb container:
```
chown: cannot read directory '/var/lib/mysql/': Permission denied
```
mount output:
```
/dev/rbd0 on /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/rbd-image-maria-drive__SEP__bliss type ext4 (rw,relatime,seclabel,stripe=1024,data=ordered)
/dev/rbd0 on /var/lib/kubelet/pods/4d3a347e-57c0-11e5-922c-52540051caca/volumes/kubernetes.io~rbd/var-lib-mysql8732482847 type ext4 (rw,relatime,seclabel,stripe=1024,data=ordered)
```
docker inspect command output related to paths:
```
    "Volumes": {
    ...
        "/var/lib/mysql": "/var/lib/kubelet/pods/4d3a347e-57c0-11e5-922c-52540051caca/volumes/kubernetes.io~rbd/var-lib-mysql8732482847"
    },

```
Are there any workarounds?
Thank you!

**Comment by rootfs** [comment]
@bliss what if you make your pod privileged?

**Comment by bliss** [comment]
@rootfs thank you for quick reply.
This is config fed to kubernetes
```JavaScript
{
    "apiVersion": "v1",
    "kind": "ReplicationController",
    "metadata": {
        "labels": {
            "kuberdock-pod-uid": "0a657616-7ace-4af1-a4e7-0f70bbaa3ed3"
        },
        "name": "47d3b6bf-ca81-4fde-ba18-ddb739342fbd",
        "namespace": "0a657616-7ace-4af1-a4e7-0f70bbaa3ed3",
        "uid": "0a657616-7ace-4af1-a4e7-0f70bbaa3ed3"
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "kuberdock-pod-uid": "0a657616-7ace-4af1-a4e7-0f70bbaa3ed3"
        },
        "template": {
            "metadata": {
                "labels": {
                    "kuberdock-pod-uid": "0a657616-7ace-4af1-a4e7-0f70bbaa3ed3"
                }
            },
            "spec": {
                "containers": [
                    {
                        "args": [
                            "mysqld"
                        ],
                        "containerID": "mariadb86175731410",
                        "env": [
                            {
                                "name": "MARIADB_VERSION",
                                "value": "10.0.21+maria-1~jessie"
                            },
                            {
                                "name": "MARIADB_MAJOR",
                                "value": "10.0"
                            },
                            {
                                "name": "MYSQL_ROOT_PASSWORD",
                                "value": "Iwb4gDo"
                            },
                            {
                                "name": "MYSQL_DATABASE",
                                "value": "blissie"
                            }
                        ],
                        "image": "mariadb",
                        "imageID": "mariadb",
                        "lastState": {},
                        "limits": {
                            "cp": "0.04 Cores",
                            "memory": "256 MB"
                        },
                        "name": "mariadb86175731410",
                        "ports": [
                            {
                                "containerPort": 3306,
                                "isPublic": false,
                                "protocol": "TCP"
                            }
                        ],
                        "ready": false,
                        "resources": {
                            "limits": {
                                "cp": "0.04",
                                "memory": 268435456
                            },
                            "requires": {
                                "cp": "0.04",
                                "memory": 268435456
                            }
                        },
                        "restartCount": 0,
                        "securityContext": {
                            "privileged": true
                        },
                        "startedAt": null,
                        "state": "stopped",
                        "terminationMessagePath": null,
                        "volumeMounts": [
                            {
                                "mountPath": "/var/lib/mysql",
                                "name": "var-lib-mysql75210922476",
                                "readOnly": false
                            }
                        ],
                        "workingDir": ""
                    }
                ],
                "nodeSelector": {
                    "kube-type": "type_0"
                },
                "volumes": [
                    {
                        "name": "var-lib-mysql75210922476",
                        "rbd": {
                            "fsType": "ext4",
                            "image": "privma-disk__SEP__bliss",
                            "keyring": "/etc/ceph/ceph.client.admin.keyring",
                            "monitors": [
                                "192.168.168.9"
                            ],
                            "pool": "rbd",
                            "size": 2,
                            "user": "admin"
                        }
                    }
                ]
            }
        }
    }
}
```
This is kubernetes feedback
```JavaScript
{
    "apiVersion": "v1",
    "code": 422,
    "details": {
        "causes": [
            {
                "field": "spec.template.spec.containers[0].securityContext.privileged",
                "message": "forbidden \"<*>(0xc20890e08c)true\"",
                "reason": "FieldValueForbidden"
            }
        ],
        "kind": "ReplicationController",
        "name": "47d3b6bf-ca81-4fde-ba18-ddb739342fbd"
    },
    "kind": "Status",
    "message": "ReplicationController \"47d3b6bf-ca81-4fde-ba18-ddb739342fbd\" is invalid: spec.template.spec.containers[0].securityContext.privileged: forbidden \"<*>(0xc20890e08c)true\"",
    "metadata": {},
    "reason": "Invalid",
    "status": "Failure"
}
```
```
kube-apiserver --version
Kubernetes 1.0.3-0.1.git61c6ac5
```

**Comment by rootfs** [comment]
If you are admin, see [this instruction](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/fedora/fedora_manual_config.md) but set

```
# Should this cluster be allowed to run privileged docker containers
KUBE_ALLOW_PRIV="--allow-privileged=true"
```

**Comment by bliss** [comment]
@rootfs Thank you very much!
Indeed, after setting --allow-privileged=true both on master and nodes pod started in privileged mode and mariadb from container got write access to RBD volume.
Could you please say: is it really no other way to make rbd volume work without elevating privileges? I personally consider privileged mode less secure.

**Comment by rootfs** [comment]
@bliss i am working on this, will keep you updated

**Comment by bliss** [comment]
@rootfs Thank you!

**Comment by rootfs** [comment]
@pmorie @childsb

**Comment by swagiaal** [comment]
> is it really no other way to make rbd volume work without elevating privileges? I personally consider privileged mode less secure.

Are you able to relabel the RBD volume ? If so try this:
sudo chcon -R -t svirt_sandbox_file_t /var/lib/kubelet/plugins/kubernetes.io/path/to/RBD/volume
That should allow containers to access it.

**Comment by bliss** [comment]
@swagiaal: When should I relabel it? Though technically that no problem at all, the mountpoint is created by kubelet and I has no control on it. I just pre-create RBD volume, mkfs and that's all.

**Comment by rootfs** [comment]
@bliss @swagiaal i'll get that done

**Comment by bliss** [comment]
@rootfs There's one more issue. When I use RBD Persistent Storage, that rbd volume gets mapped to all of my nodes, though mounted to only one, which runs the pod itself. Does it correct?

**Comment by pmorie** [comment]
@rootfs 

> @bliss @swagiaal i'll get that done

What?

**Comment by rootfs** [comment]
@bliss that's odd, the rbd image should be unmapped (though with some delay) after pod is deleted. 

There is a rbd image locking, so there is only one node that can mounts the image.

**Comment by rootfs** [comment]
@pmorie we need to check chchon also works for rbd (i think it should).

**Comment by bliss** [comment]
@rootfs: oddly but I can no more reproduce the issue with rbd volume being mapped to all nodes. Now it's being mapped to a node of the pod.
>There is a rbd image locking, so there is only one node that can mounts the image.
Do we say of 'mount' or 'map' ? The volume was mapped to all nodes while mounted to the node of the pod. Moreover as far as I know CEPH doesn't care how many clients map its RBD volumes.
Thank you!

**Comment by rootfs** [comment]
rbd is mounted on just one node. i used `rbd lock`, each time rbd image is to be mounted, the node checks if an exclusive lock can be held. The node exit without mounting rbd image if it fails to hold the lock. The lock is released during pod deletion.

**Comment by pmorie** [comment]
@rootfs I expect that it will -- can you do a simple manual test to verify?

**Comment by rootfs** [comment]
I believe chcon should work, my rbd volume is already labeled `system_u:object_r:svirt_sandbox_file_t:s0`, that is what @swagiaal suggested. I am able to read and create files on rbd volume inside container.

@bliss can you get the output of `mount |grep rbd|awk '{printf "%s/../\n", $3}' |xargs ls -Zd` on your k8s node, after you create pod with rbd volume?

**Comment by bliss** [comment]
@rootfs: I can confirm: I made a fresh kubernetes install and while there was a replica with one pod on one node rbd volume is mounted to all nodes. After replica deleted the rbd volume gets removed from the node it has been but stays mapped to all other nodes. Sad but true.
kubernetes 1.0.3

**Comment by rootfs** [comment]
@bliss very likely the following fixed your problem. You have to get at least 1.2.0-alpha.2 though

https://github.com/kubernetes/kubernetes/commit/8dbbcefdec541308616cface9c9ee4212d84bc9c#diff-36f18e327f36d95eb1333c4a18781184R266

**Comment by bliss** [comment]
@rootfs Thank you very much. I'll try to update.

**Comment by bliss** [comment]
@rootfs: good day! BTW, is privileged mode still required for ceph rbd plugin ?

**Comment by rootfs** [comment]
@bliss you don't need have to be privileged mode. You can set `securityContext`  to match the dest selinux label

**Comment by thockin** [comment]
@rootfs did we triage this?
