### ISSUE TITLE
Getting Unknown Field error for "podLogsDir"

### ISSUE THREAD

**Issue by dipaksawle** [kubernetes/kubernetes#127502]
### What happened?

I want to change the default pod logs directory path from  "/var/log/pods" to ""/storage/kubelet/pods""

Below is the kubelet configuration in /etc/kubernetes/kube-cluster.conf
**apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
podLogsDir: "/storage/kubelet/pods"**
staticPodPath: "/etc/kubernetes/manifests"
tlsCertFile: "/etc/kubernetes/pki/kubelet.crt"

[root@kubemaster device-plugins]# /usr/local/bin/kubeadm init phase kubelet-start --config /etc/kubernetes/kube-cluster.conf
W0920 11:02:21.615655 1875303 initconfiguration.go:307] **error unmarshaling configuration schema.GroupVersionKind{Group:"kubelet.config.k8s.io", Version:"v1beta1", Kind:"KubeletConfiguration"}: strict decoding error: unknown field "podLogsDir"**
W0920 11:02:21.616537 1875303 configset.go:177] error unmarshaling configuration schema.GroupVersionKind{Group:"kubelet.config.k8s.io", Version:"v1beta1", Kind:"KubeletConfiguration"}: strict decoding error: unknown field "podLogsDir"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[root@kubemaster device-plugins]#

### What did you expect to happen?

POD should start sending logs to "/storage/kubelet/pods" directory

### How can we reproduce it (as minimally and precisely as possible)?

Add below line in KubeletConfiuration 
podLogsDir: "/storage/kubelet/pods"

Run below command 
kubeadm init phase kubeconfig kubelet --config <config-file-path>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.9
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9

```

</details>

### Cloud provider

NA. Using self managed K8s cluster in Vcenter

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.10"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.10"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:10:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.10
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.10

$ uname -a
Linux kubemaster 5.4.17-2136.333.5.1.el8uek.x86_64 #3 SMP Fri Jul 12 12:38:51 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
[ root@kubemaster kubernetes]# crio version
INFO[2024-09-20 09:49:14.931951423Z] Starting CRI-O, version: 1.28.4, git: unknown(clean)
Version:        1.28.4
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2024-04-10T21:13:08Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
  rpm_crashtraceback
  exclude_graphdriver_btrfs
  btrfs_noversion
  exclude_graphdriver_devicemapper
  libdm_no_deferred_remove
  seccomp
  containers_image_openpgp
LDFlags:          -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath= -X  github.com/cri-o/cri-o/internal/version.buildDate=2024-04-10T21:13:08Z -X  github.com/cri-o/cri-o/internal/version.gitCommit=c5fc2a463053cf988db2aebe9b762700484922e5 -X  github.com/cri-o/cri-o/internal/version.version=1.28.4 -X  github.com/cri-o/cri-o/internal/version.gitTreeState=clean  -B 0x604967098e3ed4e008efb0700b88f0add5131ca3 -extldflags '-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' -compressdwarf=false
SeccompEnabled:   true
AppArmorEnabled:  false

[ root@kubemaster kubernetes]#

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xyz-li** [comment]
The filed podLogsDir was added in this commit https://github.com/kubernetes/kubernetes/commit/d9e2487d0c3f1d62e9702af98c3a9acc5b1dde32.

So v1.28.9 not support this field. So this is not a bug.
@dipaksawle

**Comment by kannon92** [comment]
@xyz-li is correct. It went in for 1.30.

/close

Feel free to reopen if you discover a bug with this in 1.30 or above.
