### ISSUE TITLE
/sig <API Machinery> The kubeadm init can't start a healthy API server

### ISSUE THREAD

**Issue by lengcangche-gituhub** [kubernetes/kubernetes#127530]
***Description:
When I user kubeadm init, the API server is not healthy.

***Steps to reproduce the behavior:
1. Open the terminal
2. su
3. kubeadm init --pod-network-cidr=192.169.0.0/16 --image-repository=registry.aliyuncs.com/google_containers --apiserver-advertise-address=192.168.1.133

***Details:
1. "kubeadm init" print:
I0922 08:58:19.911014   14859 version.go:256] remote version is much newer: v1.31.0; falling back to: stable-1.30
[init] Using Kubernetes version: v1.30.5
[preflight] Running pre-flight checks
	[WARNING SystemVerification]: missing optional cgroups: hugetlb
	[WARNING Hostname]: hostname "ubuntu" could not be reached
	[WARNING Hostname]: hostname "ubuntu": lookup ubuntu on 8.8.8.8:53: no such host
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
................
[kubelet-check] Waiting for a healthy kubelet. This can take up to 4m0s
[kubelet-check] The kubelet is healthy after 2.502889623s
[api-check] Waiting for a healthy API server. This can take up to 4m0s
[api-check] The API server is not healthy after 4m0.003332021s

Unfortunately, an error has occurred:
	context deadline exceeded

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
	- 'crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock logs CONTAINERID'
error execution phase wait-control-plane: could not initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

2. "systemctl status kubelet" print:

kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: active (running) since Sun 2024-09-22 08:58:32 CST; 54min ago
       Docs: https://kubernetes.io/docs/
   Main PID: 15117 (kubelet)
      Tasks: 16 (limit: 9410)
     Memory: 38.6M
     CGroup: /system.slice/kubelet.service
             └─15117 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime-en>

9月 22 09:52:53 ubuntu kubelet[15117]: E0922 09:52:53.625880   15117 kubelet_node_status.go:96] "Unable to register node with API server" err="Post \"https://192.168.1.133:6443/api/v1/nodes\": dial tcp >
9月 22 09:52:55 ubuntu kubelet[15117]: E0922 09:52:55.813788   15117 eviction_manager.go:282] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"ubuntu\" not found"
9月 22 09:52:56 ubuntu kubelet[15117]: E0922 09:52:56.472098   15117 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate sandbox c>
9月 22 09:52:56 ubuntu kubelet[15117]: E0922 09:52:56.472179   15117 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to generate sandbox contai>
9月 22 09:52:56 ubuntu kubelet[15117]: E0922 09:52:56.472211   15117 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to generate sandbox conta>
9月 22 09:52:56 ubuntu kubelet[15117]: E0922 09:52:56.472273   15117 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-apiserver-ubuntu_kube-system(f9b2fd>
9月 22 09:52:56 ubuntu kubelet[15117]: E0922 09:52:56.570173   15117 event.go:368] "Unable to write event (may retry after sleeping)" err="Patch \"https://192.168.1.133:6443/api/v1/namespaces/default/ev>
9月 22 09:52:56 ubuntu kubelet[15117]: E0922 09:52:56.570353   15117 event.go:307] "Unable to write event (retry limit exceeded!)" event="&Event{ObjectMeta:{ubuntu.17f76b13e52cbfb2  default    0 0001-01>
9月 22 09:52:56 ubuntu kubelet[15117]: E0922 09:52:56.570963   15117 event.go:368] "Unable to write event (may retry after sleeping)" err="Patch \"https://192.168.1.133:6443/api/v1/namespaces/default/ev>
9月 22 09:52:56 ubuntu kubelet[15117]: E0922 09:52:56.734160   15117 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.133:6443/apis/coordination.k8s.io/v1/name>

3. The "journalctl -xeu kubelet" print:

9月 22 09:54:28 ubuntu kubelet[15117]: E0922 09:54:28.449318   15117 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate sandbox c>
9月 22 09:54:28 ubuntu kubelet[15117]: E0922 09:54:28.449410   15117 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to generate sandbox contai>
9月 22 09:54:28 ubuntu kubelet[15117]: E0922 09:54:28.449442   15117 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to generate sandbox conta>
9月 22 09:54:28 ubuntu kubelet[15117]: E0922 09:54:28.449500   15117 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-scheduler-ubuntu_kube-system(241bec>
9月 22 09:54:30 ubuntu kubelet[15117]: E0922 09:54:30.450850   15117 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate sandbox c>
9月 22 09:54:30 ubuntu kubelet[15117]: E0922 09:54:30.450953   15117 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to generate sandbox contai>
9月 22 09:54:30 ubuntu kubelet[15117]: E0922 09:54:30.450991   15117 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to generate sandbox conta>
9月 22 09:54:30 ubuntu kubelet[15117]: E0922 09:54:30.451055   15117 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"etcd-ubuntu_kube-system(bd1251c0a684a8fa>
9月 22 09:54:33 ubuntu kubelet[15117]: E0922 09:54:33.171015   15117 certificate_manager.go:562] kubernetes.io/kube-apiserver-client-kubelet: Failed while requesting a signed certificate from the contro>
9月 22 09:54:34 ubuntu kubelet[15117]: I0922 09:54:34.404898   15117 kubelet_node_status.go:73] "Attempting to register node" node="ubuntu"
9月 22 09:54:34 ubuntu kubelet[15117]: E0922 09:54:34.405353   15117 kubelet_node_status.go:96] "Unable to register node with API server" err="Post \"https://192.168.1.133:6443/api/v1/nodes\": dial tcp >
9月 22 09:54:34 ubuntu kubelet[15117]: E0922 09:54:34.406382   15117 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate sandbox c>
9月 22 09:54:34 ubuntu kubelet[15117]: E0922 09:54:34.406480   15117 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to generate sandbox contai>
9月 22 09:54:34 ubuntu kubelet[15117]: E0922 09:54:34.406513   15117 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to generate sandbox conta>
9月 22 09:54:34 ubuntu kubelet[15117]: E0922 09:54:34.406587   15117 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-controller-manager-ubuntu_kube-syst>
9月 22 09:54:34 ubuntu kubelet[15117]: E0922 09:54:34.790203   15117 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.133:6443/apis/coordination.k8s.io/v1/name>
9月 22 09:54:35 ubuntu kubelet[15117]: E0922 09:54:35.853861   15117 eviction_manager.go:282] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"ubuntu\" not found"
9月 22 09:54:36 ubuntu kubelet[15117]: W0922 09:54:36.986307   15117 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://192.168.1.133:6443/api/v1/nodes?fi>
9月 22 09:54:36 ubuntu kubelet[15117]: E0922 09:54:36.987038   15117 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://192.168.>
9月 22 09:54:37 ubuntu kubelet[15117]: E0922 09:54:37.210211   15117 event.go:368] "Unable to write event (may retry after sleeping)" err="Patch \"https://192.168.1.133:6443/api/v1/namespaces/default/ev>
9月 22 09:54:37 ubuntu kubelet[15117]: E0922 09:54:37.210385   15117 event.go:307] "Unable to write event (retry limit exceeded!)" event="&Event{ObjectMeta:{ubuntu.17f76b13e52ce07e  default    0 0001-01>
9月 22 09:54:37 ubuntu kubelet[15117]: E0922 09:54:37.211019   15117 event.go:368] "Unable to write event (may retry after sleeping)" err="Patch \"https://192.168.1.133:6443/api/v1/namespaces/default/ev>
9月 22 09:54:38 ubuntu kubelet[15117]: W0922 09:54:38.262184   15117 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.RuntimeClass: Get "https://192.168.1.133:6443/apis/no>
9月 22 09:54:38 ubuntu kubelet[15117]: E0922 09:54:38.262301   15117 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get ">
9月 22 09:54:40 ubuntu kubelet[15117]: E0922 09:54:40.474307   15117 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate sandbox c>
9月 22 09:54:40 ubuntu kubelet[15117]: E0922 09:54:40.474372   15117 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to generate sandbox contai>
9月 22 09:54:40 ubuntu kubelet[15117]: E0922 09:54:40.474402   15117 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to generate sandbox conta>
9月 22 09:54:40 ubuntu kubelet[15117]: E0922 09:54:40.474459   15117 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-apiserver-ubuntu_kube-system(f9b2fd>
9月 22 09:54:40 ubuntu kubelet[15117]: E0922 09:54:40.474531   15117 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate sandbox c>
9月 22 09:54:40 ubuntu kubelet[15117]: E0922 09:54:40.474567   15117 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to generate sandbox contai>
9月 22 09:54:40 ubuntu kubelet[15117]: E0922 09:54:40.474592   15117 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to generate sandbox conta>
9月 22 09:54:40 ubuntu kubelet[15117]: E0922 09:54:40.474632   15117 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-scheduler-ubuntu_kube-system(241bec>
9月 22 09:54:40 ubuntu kubelet[15117]: E0922 09:54:40.994151   15117 event.go:368] "Unable to write event (may retry after sleeping)" err="Patch \"https://192.168.1.133:6443/api/v1/namespaces/default/ev>
9月 22 09:54:41 ubuntu kubelet[15117]: I0922 09:54:41.623548   15117 kubelet_node_status.go:73] "Attempting to register node" node="ubuntu"
9月 22 09:54:41 ubuntu kubelet[15117]: E0922 09:54:41.624037   15117 kubelet_node_status.go:96] "Unable to register node with API server" err="Post \"https://192.168.1.133:6443/api/v1/nodes\": dial tcp >
9月 22 09:54:41 ubuntu kubelet[15117]: E0922 09:54:41.794226   15117 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.133:6443/apis/coordination.k8s.io/v1/name>
9月 22 09:54:42 ubuntu kubelet[15117]: E0922 09:54:42.493364   15117 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate sandbox c>
9月 22 09:54:42 ubuntu kubelet[15117]: E0922 09:54:42.493441   15117 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to generate sandbox contai>
9月 22 09:54:42 ubuntu kubelet[15117]: E0922 09:54:42.493471   15117 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to generate sandbox conta>
9月 22 09:54:42 ubuntu kubelet[15117]: E0922 09:54:42.493525   15117 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"etcd-ubuntu_kube-system(bd1251c0a684a8fa>
9月 22 09:54:45 ubuntu kubelet[15117]: E0922 09:54:45.468300   15117 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate sandbox c>
9月 22 09:54:45 ubuntu kubelet[15117]: E0922 09:54:45.468368   15117 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to generate sandbox contai>
9月 22 09:54:45 ubuntu kubelet[15117]: E0922 09:54:45.468398   15117 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to generate sandbox conta>
9月 22 09:54:45 ubuntu kubelet[15117]: E0922 09:54:45.468457   15117 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-controller-manager-ubuntu_kube-syst>
9月 22 09:54:45 ubuntu kubelet[15117]: E0922 09:54:45.857769   15117 eviction_manager.go:282] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"ubuntu\" not found"
9月 22 09:54:48 ubuntu kubelet[15117]: E0922 09:54:48.798177   15117 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://192.168.1.133:6443/apis/coordination.k8s.io/v1/name>
9月 22 09:54:48 ubuntu kubelet[15117]: I0922 09:54:48.842869   15117 kubelet_node_status.go:73] "Attempting to register node" node="ubuntu"
9月 22 09:54:48 ubuntu kubelet[15117]: E0922 09:54:48.843330   15117 kubelet_node_status.go:96] "Unable to register node with API server" err="Post \"https://192.168.1.133:6443/api/v1/nodes\": dial tcp >
9月 22 09:54:50 ubuntu kubelet[15117]: W0922 09:54:50.698308   15117 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Get "https://192.168.1.133:6443/api/v1/servi>
9月 22 09:54:50 ubuntu kubelet[15117]: E0922 09:54:50.698428   15117 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://19>
9月 22 09:54:50 ubuntu kubelet[15117]: E0922 09:54:50.998153   15117 event.go:368] "Unable to write event (may retry after sleeping)" err="Patch \"https://192.168.1.133:6443/api/v1/namespaces/default/ev>
9月 22 09:54:53 ubuntu kubelet[15117]: E0922 09:54:53.474536   15117 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to generate sandbox c>
9月 22 09:54:53 ubuntu kubelet[15117]: E0922 09:54:53.474639   15117 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to generate sandbox contai>
9月 22 09:54:53 ubuntu kubelet[15117]: E0922 09:54:53.474674   15117 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to generate sandbox conta>
9月 22 09:54:53 ubuntu kubelet[15117]: E0922 09:54:53.474747   15117 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-apiserver-ubuntu_kube-system(f9b2fd>

***Versions:
1. OS：
Linux ubuntu 4.19.15 #3 SMP Fri Sep 20 10:00:52 CST 2024 aarch64 aarch64 aarch64 GNU/Linux
2. swap is already off

***Additional context:
1. "systemctl status containerd" prints:
containerd.service - containerd container runtime
     Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2024-09-22 08:57:55 CST; 1h 2min ago
       Docs: https://containerd.io
   Main PID: 14716 (containerd)
      Tasks: 15
     Memory: 23.4M
     CGroup: /system.slice/containerd.service
             └─14716 /usr/bin/containerd

9月 22 10:00:04 ubuntu containerd[14716]: time="2024-09-22T10:00:04.477574403+08:00" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:etcd-ubuntu,Uid:bd1251c0a684a8fafa193c821b7bc675,Namespace>
9月 22 10:00:04 ubuntu containerd[14716]: time="2024-09-22T10:00:04.477895569+08:00" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:etcd-ubuntu,Uid:bd1251c0a684a8fafa193c821b7bc675,Namespac>
9月 22 10:00:08 ubuntu containerd[14716]: time="2024-09-22T10:00:08.474284816+08:00" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-apiserver-ubuntu,Uid:f9b2fd204a3d5696876616b708b145d5>
9月 22 10:00:08 ubuntu containerd[14716]: time="2024-09-22T10:00:08.474617357+08:00" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-apiserver-ubuntu,Uid:f9b2fd204a3d5696876616b708b145d>
9月 22 10:00:09 ubuntu containerd[14716]: time="2024-09-22T10:00:09.359618502+08:00" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-scheduler-ubuntu,Uid:241beccb9fb940d1c1fa208efed30d3b>
9月 22 10:00:09 ubuntu containerd[14716]: time="2024-09-22T10:00:09.359933711+08:00" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-scheduler-ubuntu,Uid:241beccb9fb940d1c1fa208efed30d3>
9月 22 10:00:16 ubuntu containerd[14716]: time="2024-09-22T10:00:16.490874266+08:00" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-controller-manager-ubuntu,Uid:a9aaf8b052090d3b3e1bf07>
9月 22 10:00:16 ubuntu containerd[14716]: time="2024-09-22T10:00:16.491201454+08:00" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-controller-manager-ubuntu,Uid:a9aaf8b052090d3b3e1bf0>
9月 22 10:00:16 ubuntu containerd[14716]: time="2024-09-22T10:00:16.491366766+08:00" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:etcd-ubuntu,Uid:bd1251c0a684a8fafa193c821b7bc675,Namespace>
9月 22 10:00:16 ubuntu containerd[14716]: time="2024-09-22T10:00:16.491524787+08:00" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:etcd-ubuntu,Uid:bd1251c0a684a8fafa193c821b7bc675,Namespac>
lines 1-20/20 (END)

2. "iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X" prints:
iptables v1.8.4 (legacy): can't initialize iptables table `mangle': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

3. "ipvsadm -C" prints:
modprobe: FATAL: Module ip_vs not found in directory /lib/modules/4.19.15
Can't initialize ipvs: Protocol not available
Are you sure that IP Virtual Server is built in the kernel or as module?

**Comment by lengcangche-gituhub** [comment]
Hello, everyone!
This issue is already solved.
I updated the linux kernel and added the ipvs module.
Boom~~~Success.
So I guess the ApiServer itself needs ipvs module.

**Comment by pacoxu** [comment]
> This issue is already solved.

/close
/kind support
