### ISSUE TITLE
missing release from https://storage.googleapis.com/kubernetes-release

### ISSUE THREAD

**Issue by camaeel** [kubernetes/kubernetes#127595]
### What happened?

In https://storage.googleapis.com/kubernetes-release release 1.29.9 is missing. Latest one for 1.29 line is 1.29.8. 

https://console.cloud.google.com/storage/browser/kubernetes-release/release/v1.29.8?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))

### What did you expect to happen?

Release 1.29.9 should be available as well.

### How can we reproduce it (as minimally and precisely as possible)?

Try downloading this file: https://storage.googleapis.com/kubernetes-release/release/v1.29.9/bin/linux/amd64/kubelet

### Kubernetes version

<details>

```console
1.29.9
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by carlory** [comment]
It is duplicated with https://github.com/kubernetes/kubernetes/issues/127350 @camaeel

**Comment by camaeel** [comment]
Thanks @carlory
