### ISSUE TITLE
Coveralls.io badge points to stale GoogleComputePlatform/kubernetes results

### ISSUE THREAD

**Issue by senorflor** [kubernetes/kubernetes#12758]
First issue, woo!

The code coverage % badge currently points to a stale coverage check on the old repo under the [Google Cloud Platform org](https://github.com/GoogleCloudPlatform/).

TODO:
- [ ] Update Coveralls account to run on new repo
- [ ] Update README.md to point to new coveralls.io page

**Comment by mbforbes** [comment]
@senorflor do you want to take this? :-)

**Comment by kargakis** [comment]
Has been removed ever since
