### ISSUE TITLE
Duplicate webhook messages from Admission Controller during exec operation with kubectl v1.30+ (but not in v1.27)

### ISSUE THREAD

**Issue by danilovid** [kubernetes/kubernetes#127564]
### What happened?
When executing an exec operation via the Admission Controller, two webhook messages are returned instead of one. This issue is reproducible with kubectl version 1.30 and later but does not occur when using kubectl version 1.27. The cluster version in both cases is 1.27.

Example of one of the duplicated messages:

    **request:**
    
    "args": {
        "uid":  "*****-*****-*****-*****",
        "kind": {
            "group": "",
            "version": "v1",
            "kind": "PodExecOptions"
        },
        "resource": {
            "group": "",
            "version": "v1",
            "resource": "pods"
        },
        "subResource": "exec",
        "requestKind": {
            "group": "",
            "version": "v1",
            "kind": "PodExecOptions"
        },
        "requestResource": {
            "group": "",
            "version": "v1",
            "resource": "pods"
        },
        "requestSubResource": "exec",
        "name": "test-runtime",
        "namespace": "default",
        "operation": "CONNECT",
        "userInfo": {
            "username": "*****",
            "uid": ""*****",
            "groups": [
                "yc:admin",
                "system:authenticated"
            ]
        },
        "object": {
            "kind": "PodExecOptions",
            "apiVersion": "v1",
            "stdin": true,
            "stdout": true,
            "tty": true,
            "container": "t",
            "command": [
                "ls"
            ]
        },
        "oldObject": null,
        "dryRun": false,
        "options": null
    },
    
    **responce:**
   
    "result": {
        "uid": "*****-*****-*****-*****",
        "allowed": true,
        "status": {
            "metadata": {}
        }
    },

### What did you expect to happen?

Only one webhook message should be returned when executing an exec operation.

### How can we reproduce it (as minimally and precisely as possible)?

1) Run a Kubernetes cluster with version 1.27.
2) Use kubectl version 1.30 or later.
3) Perform an exec operation that triggers the Admission Controller webhook.
4) Observe that two webhook messages are generated instead of one.

### Anything else we need to know?

- The issue does not occur when using kubectl v1.27 with the same Kubernetes cluster (v1.27).
- It appears to be related to newer kubectl versions.

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: v1.30+
# Server Version: v1.27
```

</details>

### Cloud provider

<details>
Yandex Cloud

https://yandex.cloud/
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xuzhenglun** [comment]
This maybe caused by Websocket is not supported in APIServer and then request fallback to SPDY.

Can this reproduced if set environment `KUBECTL_REMOTE_COMMAND_WEBSOCKETS=false` ?

**Comment by danilovid** [comment]
Thank you! You are right, it works correctly with the flag.

**Comment by danilovid** [comment]
When executing the kubectl exec command with the KUBECTL_REMOTE_COMMAND_WEBSOCKETS=false flag enabled, only one message is received on the webhook. However, if the flag is missing, two messages continue to be sent. This might not be entirely the correct behavior.

**Comment by xuzhenglun** [comment]
This is expected as [design doc](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/4006-transition-spdy-to-websockets#version-skew-strategy) said. 

kubectl has it's version skew policy. 1.30 kubectl should work with 1.29 1.30 1.31 apiserver. see more, https://kubernetes.io/releases/version-skew-policy/#kubectl

But in fact, even if the version difference is met, this issue would happen with v1.29 apiserver and 1.30 kubectl. But I still don't think this additional API request hehavior is invalid, as kubectl as a user functionality was not affected.

**Comment by liggitt** [comment]
cc @seans3 for visibility (no action required)
