### ISSUE TITLE
/sig Network The kube-flannel pod on the worker node stays in CrashLoopBackOff status.

### ISSUE THREAD

**Issue by lengcangche-gituhub** [kubernetes/kubernetes#127676]
### What happened?

I use kubeadm join to add a worker node. However, the flannel pod on the worker node stays in CrashLoopBackOff status.

### What did you expect to happen?

The flannel pod becomes Running

### How can we reproduce it (as minimally and precisely as possible)?

1. On the master node
```console
root@NPU-Atlas-2:/home/lincom# kubeadm init --pod-network-cidr=100.100.0.0/16 --image-repository=registry.aliyuncs.com/google_containers --apiserver-advertise-address=192.168.1.122
root@NPU-Atlas-2:/home/lincom# mkdir -p $HOME/.kube
root@NPU-Atlas-2:/home/lincom# sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
root@NPU-Atlas-2:/home/lincom# sudo chown $(id -u):$(id -g) $HOME/.kube/config
root@NPU-Atlas-2:/home/lincom# kubectl apply -f kube-flannel.yml
```
2. On the worker node
```console
kubeadm join 192.168.1.122:6443 --token 2ydxw7.y64x3rl3d2g4fsxh \
> --discovery-token-ca-cert-hash sha256:9e3a2259e1c0d2a3bf0abcd6e344c5f65c7324cb58900d251f2305d4d16e7273
```
3. On the master node
```console
root@NPU-Atlas-2:/home/lincom# kubectl get pods --all-namespaces
NAMESPACE      NAME                                   READY   STATUS              RESTARTS        AGE
default        kubernetes-bootcamp-666cf565fc-97sbb   0/1     ContainerCreating   0               4m39s
kube-flannel   kube-flannel-ds-2tszk                  0/1     CrashLoopBackOff    5 (2m44s ago)   5m46s
kube-flannel   kube-flannel-ds-mkhst                  1/1     Running             0               9m54s
...................
root@NPU-Atlas-2:/home/lincom# kubectl describe pods/kube-flannel-ds-2tszk -n kube-flannel
.............................
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Warning  BackOff  32m (x416 over 122m)   kubelet  Back-off restarting failed container kube-flannel in pod kube-flannel-ds-2tszk_kube-flannel(b97155bd-b848-4272-88d4-0e5fa2f89706)
  Normal   Pulled   28m                    kubelet  Container image "swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/flannel/flannel-cni-plugin:v1.4.1-flannel1-linuxarm64" already present on machine
  Normal   Created  28m                    kubelet  Created container install-cni-plugin
  Normal   Started  28m                    kubelet  Started container install-cni-plugin
  Normal   Pulled   28m                    kubelet  Container image "swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/flannel/flannel:v0.25.1-linuxarm64" already present on machine
  Normal   Created  28m                    kubelet  Created container install-cni
  Normal   Started  28m                    kubelet  Started container install-cni
  Normal   Pulled   27m (x4 over 28m)      kubelet  Container image "swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/flannel/flannel:v0.25.1-linuxarm64" already present on machine
  Normal   Created  27m (x4 over 28m)      kubelet  Created container kube-flannel
  Normal   Started  27m (x4 over 28m)      kubelet  Started container kube-flannel
  Warning  BackOff  3m31s (x115 over 28m)  kubelet  Back-off restarting failed container kube-flannel in pod kube-flannel-ds-2tszk_kube-flannel(b97155bd-b848-4272-88d4-0e5fa2f89706)
root@NPU-Atlas-2:/home/lincom# kubectl -n kube-flannel logs kube-flannel-ds-2tszk
Defaulted container "kube-flannel" out of: kube-flannel, install-cni-plugin (init), install-cni (init)
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.14
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.14
```

</details>

### Cloud provider

<details>
No
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux FT-D2000-2-1 4.19.15 #5 SMP Tue Sep 24 09:29:10 CST 2024 aarch64 aarch64 aarch64 GNU/Linux


```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd containerd.io 1.7.22
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
flannel:v0.25.1-linuxarm64
flannel-cni-plugin:v1.4.1-flannel1-linuxarm64
</details>

**Comment by xyz-li** [comment]
Could you provide the log of the crashed pod?

**Comment by neolit123** [comment]
best to report this the flannel repository instead of hear.

/sig network
/kind support

**Comment by lengcangche-gituhub** [comment]
> Could you provide the log of the crashed pod?

root@NPU-Atlas-2:/home/lincom# kubectl -n kube-flannel logs kube-flannel-ds-2tszk
Defaulted container "kube-flannel" out of: kube-flannel, install-cni-plugin (init), install-cni (init)

**Comment by uablrek** [comment]
Try `kubectl -n kube-flannel logs kube-flannel-ds-2tszk -c install-cni-plugin` (or/and -c install-cni)

**Comment by lengcangche-gituhub** [comment]
> Try `kubectl -n kube-flannel logs kube-flannel-ds-2tszk -c install-cni-plugin` (or/and -c install-cni)


root@NPU-Atlas-2:/home/lincom# kubectl -n kube-flannel logs kube-flannel-ds-89jgt -c install-cni-plugin
Error from server: Get "https://**192.168.0.133**:10250/containerLogs/kube-flannel/kube-flannel-ds-89jgt/install-cni-plugin": dial tcp 192.168.0.133:10250: connect: no route to host
root@NPU-Atlas-2:/home/lincom# kubectl -n kube-flannel logs kube-flannel-ds-89jgt -c install-cni
Error from server: Get "https://**192.168.0.133**:10250/containerLogs/kube-flannel/kube-flannel-ds-89jgt/install-cni": dial tcp 192.168.0.133:10250: connect: no route to host

Supplementary information: 
1. The master node is called NPU-Atlas-2. The **problematic** worker node is called FT-D2000-2-1. Another worker node is called GPU-Nvidia-2.
2. 192.168.0.133 is the IP address of an interface (on the problematic worker node FT-D2000-2-1) that is **not** used by the networking between the worker node and the master node. When I "kubectl describe" the problematic worker node FT-D2000-2-1, the InternelIP is 192.168.0.133. This is very strange. 
3. When I "kubectl describe" the worker node gpu-nvidia-2, the InternelIP is the IP address of an interface that **is** used by the networking between the worker node and the master node. 
4. However, the route of the problematic worker node FT-D2000-2-1 is right.
root@FT-D2000-2-1:/home/user# ip route show:
.....................
192.168.1.0/24 dev enp17s0f0 proto kernel scope link src **192.168.1.133** metric 100

**Comment by aojea** [comment]
If you have nodes with multiple addresses, and the one you are using to communicate with the apiserver is not the address of the interface with teh default route, you need to set the ip address of the node passing the `--node-ip` option to the kubelet

**Comment by lengcangche-gituhub** [comment]
> If you have nodes with multiple addresses, and the one you are using to communicate with the apiserver is not the address of the interface with teh default route, you need to set the ip address of the node passing the `--node-ip` option to the kubelet

Thank you, I'll try
