### ISSUE TITLE
Support Defaulting in CRD with CEL expression

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#127601]
### What would you like to be added?

Currently CRD defaulting only supports [specify default values in the OpenAPI v3 validation schema](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting). However, for more complex use case like Defaulting based on other fields condition or defaulting while updating is not supported hence webhook would still be needed. We would like to have more complex defaulting be supported in CRD and later in declarative validation as well.

### Why is this needed?

Make CRD more declarative as well as reduce the complexity of having webhook setup for simple use cases.

**Comment by liggitt** [comment]
> Defaulting based on other fields condition

that is not recommended, and has caused problems when we've done it in the past

> defaulting while updating is not supported

defaulting while updating is definitely supported... defaults are applied to incoming objects on update requests as well

**Comment by liggitt** [comment]
I'm not sure I see a case for the things CEL defaulting would allow

**Comment by cici37** [comment]
Thanks for the input!
By `defaulting while updating` I mean only applying defaulting on certain operation(I feel it might not be the use case we wanna support..). 
For cross field defaulting, cel gives us the power to access "previous value". Would it help for a safer cross field defaulting? User could specify if they wanna the field value to be updated based on certain condition of other field or even the existing value of current field. 

Do you happen to know some existing use cases or if there is valuable use cases require cross-field defaulting? 
Thank you :)

**Comment by liggitt** [comment]
> I mean only applying defaulting on certain operation

Hmm... that doesn't sound like API-level defaulting... that sounds like admission

> For cross field defaulting, cel gives us the power to access "previous value". Would it help for a safer cross field defaulting? User could specify if they wanna the field value to be updated based on certain condition of other field or even the existing value of current field.

I don't think I'd want to make it easy to do defaulting in a way we've found unhelpful and recommended against in the past. I'd probably lean on mutating admission for anything cross-field people wanted to do

**Comment by cici37** [comment]
/close
Using MutatingAdmissionPolicy sounds a better way to handle this! Thanks
