### ISSUE TITLE
e2e flake: Monitoring - should verify monitoring pods and all cluster nodes are available on influxdb using heapster. 

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#12765]
```
[Fail] Monitoring [It] should verify monitoring pods and all cluster nodes are available on influxdb using heapster. 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:233
```

Reported in #12214 ([Heapster Logs](https://gist.github.com/yujuhong/f233d8c9b6dd18d1608b)) & #12324 ([Build Log](https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/28296f8296ca323cc75aad11afd099bb2e25ac45/kubernetes-pull-build-test-e2e-gce/5265/build-log.txt))

**Comment by vishh** [comment]
@piosz can you help debug this issue?

**Comment by piosz** [comment]
Yes, sure.

**Comment by wojtek-t** [comment]
Another failure:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9727/

@piosz - can you prioritize looking into it?

**Comment by zmerlynn** [comment]
@wojtek-t beat me to it.

**Comment by wojtek-t** [comment]
Ane one more:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9730/

**Comment by wojtek-t** [comment]
One more:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/19350/#

**Comment by piosz** [comment]
The test fails with:
```
23:31:10 Dec  6 23:31:09.982: INFO: failed to find all expected Pods.
23:31:10 Expected: [03c0e016-9cb3-11e5-a0c0-42010af00002 03fa9162-9cb3-11e5-a0c0-42010af00002]
23:31:10 Actual: map[642bb4cd-9cb3-11e5-a0c0-42010af00002:false 1649be93-9cb3-11e5-a0c0-42010af00002:false ...
```
Heapster logs:
```
I1207 07:22:18.827367       1 heapster.go:55] /heapster --source=kubernetes:'' --sink=influxdb:http://monitoring-influxdb:8086 --stats_resolution=30s --sink_frequency=1m
I1207 07:22:18.827624       1 heapster.go:56] Heapster version 0.18.2
I1207 07:22:18.828419       1 kube_factory.go:169] Using Kubernetes client with master "https://10.0.0.1:443" and version "v1"
I1207 07:22:18.845379       1 kube_factory.go:170] Using kubelet port 10255
E1207 07:22:48.830159       1 reflector.go:136] Failed to list *api.Node: Get https://10.0.0.1:443/api/v1/nodes: dial tcp 10.0.0.1:443: i/o timeout
E1207 07:22:48.852365       1 reflector.go:136] Failed to list *api.Pod: Get https://10.0.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: dial tcp 10.0.0.1:443: i/o timeout
E1207 07:22:48.852570       1 kube_events.go:123] Failed to load events: Get https://10.0.0.1:443/api/v1/events: dial tcp 10.0.0.1:443: i/o timeout
E1207 07:22:48.852649       1 reflector.go:136] Failed to list *api.Namespace: Get https://10.0.0.1:443/api/v1/namespaces: dial tcp 10.0.0.1:443: i/o timeout
E1207 07:22:53.998991       1 driver.go:326] Database creation failed: Post http://monitoring-influxdb:8086/db?u=root&p=root: dial tcp: lookup monitoring-influxdb: no such host. Retrying after 30 seconds
I1207 07:23:24.127430       1 driver.go:301] Created database "k8s" on influxdb
I1207 07:23:24.127560       1 driver.go:376] created influxdb sink with options: {root root monitoring-influxdb:8086 k8s false}
I1207 07:23:24.132416       1 heapster.go:66] Starting heapster on port 8082
```

**Comment by piosz** [comment]
I investigated the recent failure http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/9762. InfluxDB pod has been killed -> db schema was lost -> Heapster doesn't handle this situation.

I'll create the fix thought it may take some time until it will land in Kubernetes.

**Comment by piosz** [comment]
The problem was fixed in Heapster by @vishh in https://github.com/kubernetes/heapster/pull/548. The only missing thing here is to bump Heapster version in Kubernetes.

@mwielgus

**Comment by piosz** [comment]
Reassign to @mwielgus who will make a new Heapster release.

**Comment by wojtek-t** [comment]
Another failure:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9803/

@mwielgus - can we prioritize making heapster release so that we will not be blocking merging on it?

**Comment by saad-ali** [comment]
More failures:
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9895/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9881/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9865/

**Comment by wojtek-t** [comment]
@mwielgus - is there a new heapster release? Can we upgrade Kubernetes to use it?

**Comment by wojtek-t** [comment]
Can we really prioritize it - it happened 5+ times over the weekend.

**Comment by spxtr** [comment]
Not sure if it's helpful to link these anymore, but this is failing nearly one out of every four runs.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9984/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9979/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9976/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9970/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9966/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9959/

**Comment by gmarek** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10110/

**Comment by goltermann** [comment]
Is this still failing?  It's listed as P0.

**Comment by piosz** [comment]
The test hasn't failed for last 30 runs, although there is still an issue. Decreasing the priority.

**Comment by freehan** [comment]
I run salt manually on the master and it cannot manage the heapster rc yaml file due to the following error. Looks like a salt script problem.  Not sure why it is NOT failing consistently. 

----------
          ID: /etc/kubernetes/addons/cluster-monitoring/influxdb
    Function: file.recurse
      Result: False
     Comment: #### /etc/kubernetes/addons/cluster-monitoring/influxdb/heapster-controller.yaml ####
              Unable to manage file: Jinja syntax error: no test named 'None'; line 2
              
              ---
              {% set heapster_memory = "300Mi" -%}
              {% if pillar['num_nodes'] is defined and pillar['num_nodes'] is not None -%}    <======================
                {% set heapster_memory = (200 + pillar['num_nodes'] * 12)|string + "Mi" -%}
              {% endif -%}
              
              apiVersion: v1
              kind: ReplicationController
              [...]
              ---

**Comment by zmerlynn** [comment]
@freehan: That looks like an unrelated issue (and one we're not seeing on GCE).

**Comment by zmerlynn** [comment]
@freehan: Actually, I'm wrong, that just got merged and may be disrupting things actively.

**Comment by freehan** [comment]
@zmerlynn This test is failing a lot in flaky suite due to this. It is introduced by a recent change: https://github.com/kubernetes/kubernetes/commit/9c843495d79b7db8e95dc71af7d003700a39deb9#diff-c04177fe557c0bb69636f233b0c7487a 

After fixing this, it should get back to the previous state...

**Comment by zmerlynn** [comment]
@freehan: Yeah, I saw that #19535 just landed.

**Comment by mwielgus** [comment]
The test has been marked flaky in #19168. Should not cause any issues in non-flaky suites. The issue will be fixed with the new Heapster.

**Comment by davidopp** [comment]
Thanks @mwielgus. Closing this issue.
