### ISSUE TITLE
OSX build scripts should support docker-machine (not just boot2docker)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#12768]
The docker team is now favoring docker-machine over boot2docker.  Docker-machine is also better, in that it supports options other than VirtualBox (though sadly not yet xhyve).

We should probably consider adding support for docker-machine therefore.

**Comment by thockin** [comment]
Would this replace or augment our vagrant mode?

**Comment by justinsb** [comment]
I may be unaware of a new way to build, but I'm just talking about e.g. `make clean release` on OSX.

Our build scripts directly refer to boot2docker, but docker-machine will likely be more prevalent going forwards:
https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L133-L150

Changing title to try to better capture my intent.

**Comment by kelcecil** [comment]
Does the work done in #13095 capture what you were looking for? I can add whatever else you might be looking for if you can provide some direction.

**Comment by erik-farmer** [comment]
Additionally [Docker deprecated boot2docker][1] in it's recent release.
This unfortunately puts the [kubernetes local docker documentation][2] out of date
[1]:https://docs.docker.com/installation/mac/
[2]:http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html

**Comment by bgrant0607** [comment]
Done.
