### ISSUE TITLE
The `update-vendor.sh` is broken with `GOPROXY=direct`

### ISSUE THREAD

**Issue by stlaz** [kubernetes/kubernetes#127623]
### What happened?

https://github.com/kubernetes/kubernetes/pull/126799 seems to have broken the vendor by adding a transitive dependency at a version that no longer exists

### What did you expect to happen?

`./hack/update-vendor.sh` should not fail

### How can we reproduce it (as minimally and precisely as possible)?

Run `./hack/update-vendor.sh` with an emtpy `_output/` dir

### Anything else we need to know?

https://github.com/microsoft/hcsshim/blob/main/go.mod seems to be fixing the dependency but does not appear to be in any released version of `microsoft/hcsshim`

Snip from `./hack/update-vendor.sh` logs:
```
+ errs=()
+ kube::util::read-array errs
+ [[ -z errs ]]
++ declare -p errs
++ go list -e -tags=tools -json all
++ jq -r '.Error.Err | select( . != null )'
++ grep -v 'is a program, not an importable package'
+ [[ -n declare -a errs=() ]]
+ declare -p errs
+ grep -q '^declare -a'
+ local __read_array_i=0
+ IFS=
+ read -r 'errs[__read_array_i++]'
+++ kube::log::errexit
+++ local 'err=0 0 1'
+++ set +o
+++ grep -qe '-o errexit'
+++ set +o xtrace
+ eval '[[ ${errs[--__read_array_i]} ]]'
++ [[ -n '' ]]
+ unset 'errs[__read_array_i]'
+ ((  0 != 0  ))
+ go list -m -f '{{if not .Main}}{{.Path}}{{end}}' all
go: github.com/veraison/go-cose@v1.2.0: invalid version: unknown revision v1.2.0
++ kube::log::errexit
++ local err=1
++ set +o
++ grep -qe '-o errexit'
++ set +o xtrace
++ kube::log::errexit
++ local err=1
++ grep -qe '-o errexit'
++ set +o
++ set +o xtrace
(END)
```

### Kubernetes version

master

### Cloud provider

irrelevant

### OS version

Arch Linux 6.10.10-arch1-1

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
`v1.2.0` is still in go eco system:
- https://pkg.go.dev/github.com/veraison/go-cose?tab=versions
- https://pkg.go.dev/github.com/veraison/go-cose@v1.2.0

Though it looks like it was retracted:
- https://github.com/veraison/go-cose/blame/4162f36a08c7104c4c218eeb74f89c70281ce5c7/go.mod#L11
- https://github.com/veraison/go-cose/pull/153

cc @kiashok @princepereira

Can you please open an issue in [https://github.com/microsoft/hcsshim](https://github.com/microsoft/hcsshim/blob/main/go.mod)? and ping the MSFT folks i cc'ed above to get a new release of hcsshim out?

( Looks like you are trying to build with a strict `GOPROXY` `GOSUMDB` etc and caught this! )

**Comment by stlaz** [comment]
I added a comment to https://github.com/microsoft/hcsshim/issues/2162#issuecomment-2374345844, I'll try to see if I can fetch these two :)

**Comment by liggitt** [comment]
Adding to the milestone as a blocker to make sure we don't release before resolving this

**Comment by dims** [comment]
good call @liggitt thanks

**Comment by drewhagen** [comment]
Double checking, is this meant to be on the 1.32 milestone or 1.31?

**Comment by liggitt** [comment]
Oops, 1.32

**Comment by liggitt** [comment]
Isn't this fixed by https://github.com/kubernetes/kubernetes/pull/127824 ?

**Comment by dims** [comment]
> Isn't this fixed by https://github.com/kubernetes/kubernetes/pull/127824 ?

@liggitt yep. should be fixed now.

/close
