### ISSUE TITLE
cancel function could be nil in CLE leader election path

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#127665]
https://github.com/kubernetes/kubernetes/pull/124012#discussion_r1777340551

Per https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L210, we could call OnStoppedLeading before OnStartedLeading gets called leading to a nil cancel function. We should check the function before calling it.

/sig api-machinery
/triage accepted

**Comment by pacoxu** [comment]
Flakes a lot in both
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&width=90 
and 
https://testgrid.k8s.io/sig-release-master-blocking#integration-master.

/cc @kubernetes/release-team-release-signal

**Comment by aojea** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/127834

/close
