### ISSUE TITLE
The controller-manager monitors customized resources.

### ISSUE THREAD

**Issue by Black-max12138** [kubernetes/kubernetes#127617]
### What happened?

According to the APIServer audit, the controller-manager sends watch requests to custom resources. Why? What functions are used? Can I not monitor them?

### What did you expect to happen?

Can the controller-manager not send watch requests to custom resources if it is not required?

### How can we reproduce it (as minimally and precisely as possible)?

Viewing APIServer Audit Logs

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.28
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
/remove-kind bug
/kind support
/close

there are two generic controllers that watch even custom resources: garbage collection controller (so metadata.ownerReferences are honored) and resource quota (so object count quota is honored)
