### ISSUE TITLE
[help] when use kruise client, go mod dep issue

### ISSUE THREAD

**Issue by gotosre** [kubernetes/kubernetes#127648]
go: github.com/openkruise/kruise-api@v1.7.0 (matching github.com/openkruise/kruise-api/client/clientset/versioned@upgrade) indirectly requires k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0

how to resolve?

**Comment by AmarNathChary** [comment]
The package indirectly depends on a version of k8s.io/api that doesn't exist. also, check that you are using the latest versions of your dependencies,
