### ISSUE TITLE
Control-plane node failure after transfer pods from one control-plane to another

### ISSUE THREAD

**Issue by WillDeploy1984** [kubernetes/kubernetes#127755]
### What happened?

After updating kubernetes components from 1.20 to 1.30 there is a bug where if several pods (5-10) go from node1 to node2 (both control-plane), node2 starts to fail. This failure consist in a incremental delay response from the server until I am unable to login through ssh nor directly into the machine. It looks like a memory leak and note that after working with k8s 1.20 during 4 years in this cluster I have never faced this issue. Also the software that runs in the pods was not modified during the whole process so everything points into a k8s problem. I am able to recover the affected node by a manual restart.

In this cluster I have 3 control-plane nodes and this problem occur in all of them. After the first node fails the pods are loaded in another control-plan node which eventually fails following the same error, this problem continues until all control-plan nodes fail causing a total cluster failure.

I performed an analysis in the performance of the nodes and it only reaches about 20% of total available RAM when it fails but it might be not representative of the current problem.

### What did you expect to happen?

No problem in the node after transferring pods from one control-plan to another.

### How can we reproduce it (as minimally and precisely as possible)?

I have 9 nodes, 3 control-plan and 6 workers.
After updating kubeadm, kubelet, kubectl, cri-tools from 1.20 to 1.30(containerd and kubernetes-cni were also updated)

### Kubernetes version

<details>

```console
$ kubectl version
1.30.0
```

</details>

### Cloud provider

<details>
Bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.5"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.5
$ uname -a
Linux mcs1 5.4.17-2136.302.7.2.2.el8uek.x86_64 #2 SMP Fri Jan 28 20:03:52 PST 2022 x86_64 x86_64 x86_64 GNU/Linux
(machine is running in 2020 so ingore date)

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
Containerd 1.6.9
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Kubernetes-cni 1.4.0
</details>

**Comment by sftim** [comment]
Hi

You did an upgrade from v1.20 to v1.30? That's not a supported transition, so this wouldn't be a bug per se if if fails.

/triage needs-information
/priority awaiting-more-evidence

**Comment by neolit123** [comment]
yes, directly 20 -> 30 is not supported.


a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by sftim** [comment]
Sorry about the noise. We are closing it though.
/reopen

**Comment by WillDeploy1984** [comment]
But how is this posible? The way forward to upgrade it was to uninstall all components of kubernetes, the ones I mentioned above, and then install them with the new version, so it's almost like install from cero all k8s
