### ISSUE TITLE
Optimize the delivery of TracerProvider in kubelet

### ISSUE THREAD

**Issue by lengrongfu** [kubernetes/kubernetes#127705]
### What would you like to be added?

Current in the kubelet new a trace provider,  this is a global provider, but we need to pass it to each module that uses it, this is cumbersome. for example, the following code:

https://github.com/kubernetes/kubernetes/blob/3d6c5b2e98afaaae1d17107e2d3d709c726be49d/cmd/kubelet/app/server.go#L489

https://github.com/kubernetes/kubernetes/blob/3d6c5b2e98afaaae1d17107e2d3d709c726be49d/cmd/kubelet/app/server.go#L502

https://github.com/kubernetes/kubernetes/blob/3d6c5b2e98afaaae1d17107e2d3d709c726be49d/pkg/kubelet/kubelet.go#L329-L331

We hope in `newTracerProvider` method add `otel.SetTracerProvider(tp)`, to set global trace provider, where used call `otel.GetTracerProvider()` to get this provider.

```go
--- a/cmd/kubelet/app/server.go
+++ b/cmd/kubelet/app/server.go
@@ -1391,13 +1391,14 @@ func parseResourceList(m map[string]string) (v1.ResourceList, error) {
        return rl, nil
 }
 
-func newTracerProvider(s *options.KubeletServer) (oteltrace.TracerProvider, error) {
+func newTracerProvider(s *options.KubeletServer) error {
        if s.KubeletConfiguration.Tracing == nil {
-               return noopoteltrace.NewTracerProvider(), nil
+               otel.SetTracerProvider(noopoteltrace.NewTracerProvider())
+               return nil
        }
        hostname, err := nodeutil.GetHostname(s.HostnameOverride)
        if err != nil {
-               return nil, fmt.Errorf("could not determine hostname for tracer provider: %w", err)
+               return fmt.Errorf("could not determine hostname for tracer provider: %w", err)
        }
        resourceOpts := []otelsdkresource.Option{
                otelsdkresource.WithAttributes(
@@ -1407,9 +1408,10 @@ func newTracerProvider(s *options.KubeletServer) (oteltrace.TracerProvider, erro
        }
        tp, err := tracing.NewProvider(context.Background(), s.KubeletConfiguration.Tracing, []otlptracegrpc.Option{}, resourceOpts)
        if err != nil {
-               return nil, fmt.Errorf("could not configure tracer provider: %w", err)
+               return fmt.Errorf("could not configure tracer provider: %w", err)
        }
-       return tp, nil
+       otel.SetTracerProvider(tp)
+       return nil
 }

```

### Why is this needed?

When trace provider is needed in more places, `TracerProvider` can be avoided from being passed between methods.

**Comment by lengrongfu** [comment]
@sallyom What are your thoughts on this optimization?  thanks~

**Comment by dgrisonnet** [comment]
cc @dashpole

**Comment by dashpole** [comment]
We should avoid using globals.  It makes it more difficult to write tests, and makes it more likely that we will collect telemetry that isn't expected.  We moved away from using the global prometheus registry for this reason
