### ISSUE TITLE
Remove alpha/beta/ga comments in kube_features.go

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#127782]
We already have detailed version transition information in https://github.com/kubernetes/kubernetes/blob/master/pkg/features/versioned_kube_features.go and the comments in [kube_features.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go) are unnecessary and could drift from the ones documented in code. The versions in `versioned_kube_features.go` are programmatically verified thanks to a utility by @liggitt: https://github.com/kubernetes/kubernetes/pull/127200#discussion_r1768722135 and should be used as the source of truth compared to the comments.

Eg: The alpha and beta lines should be removed.

```
	// owner: @bswartz
	// alpha: v1.18
	// beta: v1.24
	//
	// Enables usage of any object for volume data source in PVCs
	AnyVolumeDataSource featuregate.Feature = "AnyVolumeDataSource"
```

cc @jpbetz @liggitt @aaron-prindle 
/sig architecture

**Comment by Adarsh-verma-14** [comment]
could I work on it @Jefftree ?

**Comment by Jefftree** [comment]
Of course, thank you!

**Comment by AmarNathChary** [comment]
/assign 
I will make the changes that are needed.
