### ISSUE TITLE
Add a confirmation parameter to all k8s API that delete collections.

### ISSUE THREAD

**Issue by zhifei92** [kubernetes/kubernetes#127746]
### What would you like to be added?

Add a confirmation parameter to all k8s API that delete collections.

Like the following:
```
DELETE api/v1/namespaces/{namespace}/pods?confirm=true
DELETE api/v1/namespaces/{namespace}/secrets?confirm=true
DELETE api/v1/nodes?confirm=true
```

### The current design of the k8s API for deleting collections is unreasonable. 

For instance, `DELETE api/v1/namespaces/{namespace}/pods` deletes all pods under a specific namespace, while `DELETE api/v1/namespaces/{namespace}/pods/{name}` deletes a specific pod under a specific namespace. This may seem normal at first glance, but it's not a good design. 

Take this scenario as an example: if a user wants to delete pod1 under ns1, their URI should be `api/v1/namespaces/ns1/pods/pod1`, however, due to negligence or a bug in their program, the pod name might be left empty, which would change their URI to `api/v1/namespaces/ns1/pods/`. What would happen then? It would result in the deletion of all pods under ns1, which could be disastrous. The issues would be more severe with `DELETE api/v1/nodes`.

##### This issue can occur with the Python client, for example, with the following code:
in https://raw.githubusercontent.com/kubernetes-client/python/refs/heads/master/kubernetes/client/api/core_v1_api.py
```
    def delete_namespaced_pod_with_http_info(self, name, namespace, **kwargs):  # noqa: E501
        """delete_namespaced_pod  # noqa: E501

        delete a Pod  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_namespaced_pod_with_http_info(name, namespace, async_req=True)
        >>> result = thread.get()
......

        return self.api_client.call_api(
            '/api/v1/namespaces/{namespace}/pods/{name}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='V1Pod',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
```
### How can such issues be avoided currently?
1. Role-Based Access Control (RBAC) can be used to manage permissions, ensuring that only users with sufficient privileges can perform the DELETE api/v1/namespaces/{namespace}/pods operation
2. Security admission can be enforced using tools like `Gatekeeper` and `Kyverno`.

##### The issues with the current solution are:
1. Deleting a collection is a real need and is reasonable in itself. However, security must be taken into account, and both permission controls and confirmation mechanisms should be required.
2. Currently, the confirmation mechanism is missing.
```[tasklist]
### Tasks
```

**Comment by zhifei92** [comment]
> This issue seems interesting! I would love to contribute or discuss further. 👍

Thank you very much for your interest in this. If this is accepted, I would like to work on this. Happy to discuss this matter with you

**Comment by zhifei92** [comment]
cc @david-mcmahon @fedebongio

**Comment by sftim** [comment]
This could be implemented client-side.

I don't see the benefit in adding optional server-side confirmation, and we can't change the semantics of the existing API (we guarantee that stable APIs don't change in breaking ways - see https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api)

/priority awaiting-more-evidence

**Comment by zhifei92** [comment]
> This could be implemented client-side.
> 
> I don't see the benefit in adding optional server-side confirmation, and we can't change the semantics of the existing API (we guarantee that stable APIs don't change in breaking ways - see https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api)
> 
> /priority awaiting-more-evidence

Thank you for your reply. Everything you mentioned is correct. However, the issue I raised above is also indeed possible, and once it occurs, it can be quite serious. This has happened in clusters with thousands of nodes, causing significant negative impacts.

Client-side optimizations cannot 100% prevent disasters from happening.

**Comment by aojea** [comment]
> Client-side optimizations cannot 100% prevent disasters from happening.

I wish there was something that can guarantee 100% reliability 😄  . 

Appending an extra string to an url will make it more difficult to happen as you say, but does not stop the system of be broken by subtle bugs like the one that you mention. This specific bug seems it should have be caught with an unit test to validate you can not pass an empty value, or just restricting the capabilities of the clients with policies, ... that is why is important to follow the best practices with staging environments, safe rollouts in waves, canaries, testing , code reviews, rbac policies ...

As Tim says, we don't break compatibility, so in this case , independently of adding or not adding the feature, the systems has to keep working as before, so it will not be possible to solve the problem you are raising, because the old format has to keep working

Hope you accept this explanation , but I'm going to close this bug as work as intended

Thanks for your feedback

/close

**Comment by zhifei92** [comment]
> but does not stop the system of be broken by subtle bugs like the one that you mention

Thank you for your reply. This is not a simple issue of a minor bug, nor is it about best practices. Suppose you are maintaining a k8s cluster with many users who have full permissions to their own namespaces, including pods. If a user simply wants to delete a pod, but due to some reason—whether it's a bug in their program or just a mistake in deleting a pod—the result is that all pods in the namespace are deleted. This leads to a catastrophic outcome. You might argue that the user didn't do proper testing, but the user will complain that the API you provided is faulty, and there is indeed a problem. You will find it hard to defend yourself because your API is not secure, and this is not a good design.

**Comment by zhifei92** [comment]
>  we don't break compatibility, so in this case , independently of adding or not adding the feature, the systems has to keep working as before

I accept this. However, I really hope that this issue will be addressed in the future. It is definitely not a minor problem. I believe others will surely encounter this issue as well.

**Comment by sftim** [comment]
We could change the _client libraries_ to include a `really_delete` parameter. Making a breaking a change to all the client libraries is disruptive, but **way** less disruptive than changing all Kubernetes' APIs representing things you can have in collections (of which, I think, all of them support item deletion).

**Comment by jpbetz** [comment]
> We could change the _client libraries_ to include a `really_delete` parameter. Making a breaking a change to all the client libraries is disruptive, but **way** less disruptive than changing all Kubernetes' APIs representing things you can have in collections (of which, I think, all of them support item deletion).

After rereading the description.  Another thing to consider doing, specifically for client delete pod operations, is make sure the client returns an error early if the pod name is an empty string, preventing the client from calling delete collection when the client is accidentally called to delete a single pod but somehow the name field accidentally got provided as an empty string.

Which clients is this currently a problem for?

**Comment by aojea** [comment]
the example in the description is with the python one @jpbetz https://raw.githubusercontent.com/kubernetes-client/python/refs/heads/master/kubernetes/client/api/core_v1_api.py
