### ISSUE TITLE
/sig Network The InternalIP of the master node is abnormal

### ISSUE THREAD

**Issue by lengcangche-gituhub** [kubernetes/kubernetes#127729]
### What happened?

When I "kubectl describe" the master node, the InternalIP field is 192.168.0.133. This is another network interface's IP, **not** the specified IP address 192.168.1.133 during "kubeadm init". By the way, 192.168.1.133 is the IP address of one of network interfaces on the master node. 

### What did you expect to happen?

The InternalIP becomes the specified IP address.

### How can we reproduce it (as minimally and precisely as possible)?

1. kubeadm init --pod-network-cidr=133.133.0.0/16 --image-repository=registry.aliyuncs.com/google_containers --apiserver-advertise-address=192.168.1.133 (where 192.168.1.133 is the address of one of the network interfaces on the master node)
2. mkdir -p $HOME/.kube
3. sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
4. sudo chown $(id -u):$(id -g) $HOME/.kube/config
5. kubectl apply -f kube-flannel.yml
6. kubectl describe nodes/ft-d2000-2-1 (where ft-d2000-2-1 is the node name of the master node)

### Anything else we need to know?

1. Part of the file kube-flannel.yml:
apiVersion: v1
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "133.133.0.0/16",
      "EnableNFTables": false,
      "Backend": {
        "Type": "vxlan"
      }
    }

2. Part of the output of "ifconfig":
enaftgm1i0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.133  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::8689:88ff:fe10:ffc  prefixlen 64  scopeid 0x20<link>
        ether 84:89:88:10:0f:fc  txqueuelen 1000  (Ethernet)
        RX packets 111  bytes 12995 (12.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 60  bytes 6868 (6.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 9  base 0x2000  

enp17s0f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.133  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::4e74:a7ff:fe40:a404  prefixlen 64  scopeid 0x20<link>
        ether 4c:74:a7:40:a4:04  txqueuelen 1000  (Ethernet)
        RX packets 4224  bytes 315667 (315.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 190  bytes 24877 (24.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

3. The content of the file /etc/network/interfaces:
source-directory /etc/network/interfaces.d
auto enaftgm1i0
iface enaftgm1i0 inet dhcp
nameservers 8.8.8.8

iface enp17s0f0 inet static
gateway 192.168.1.1

4. The content of the file /etc/NetworkManager/NetworkManager.conf:
[main]
plugins=ifupdown,keyfile

[ifupdown]
managed=true

[device]
wifi.scan-rand-mac-address=no
5. The output of "ip route show":
default via 192.168.1.133 dev enp17s0f0 scope link 
169.254.0.0/16 dev enp17s0f0 scope link metric 1000 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.0.0/24 dev enaftgm1i0 proto kernel scope link src 192.168.0.133 
192.168.1.0/24 dev enp17s0f0 proto kernel scope link src 192.168.1.133 metric 100 

6. The output of "route -n":
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.133   0.0.0.0         UG    0      0        0 enp17s0f0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 enp17s0f0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.0.0     0.0.0.0         255.255.255.0   U     0      0        0 enaftgm1i0
192.168.1.0     0.0.0.0         255.255.255.0   U     100    0        0 enp17s0f0

7. The content of /etc/rc.local:
#!/bin/bash
insmod /root/test/rnp-0.3.6-rc8-33b3b45/src/rnp.ko
sleep 1
cd /root/test/uart
/root/test/uart/uart_pant &

modprobe iptable_nat
modprobe overlay
modprobe ip_vs
modprobe ip_vs_sh
modprobe ip_vs_rr
modprobe ip_vs_wrr
modprobe nf_conntrack
modprobe vxlan

sleep 1

sudo ifconfig enaftgm1i0 192.168.0.133 up
sudo ifconfig enp17s0f0 192.168.1.133 up

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.14
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.14

```

</details>

### Cloud provider

<details>
No
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux FT-D2000-2-1 4.19.15 #6 SMP Fri Sep 27 10:12:55 CST 2024 aarch64 aarch64 aarch64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd containerd.io 1.7.22 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
flannel:v0.25.1-linuxarm64
flannel-cni-plugin:v1.2.0-linuxarm64
</details>

**Comment by neolit123** [comment]
that's because the kubelet does it's own ip detection unless you pass --node-ip to it.

/kind support
/sig network node cluster-lifecycle

**Comment by neolit123** [comment]
a better place to talk about this would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

also see:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#network-setup

/close
