### ISSUE TITLE
sorry this is a support,what is below cluster config in ExecCredential used to? can you give me an example?

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#127770]
### What would you like to be added?

```
{
  "apiVersion": "client.authentication.k8s.io/v1",
  "kind": "ExecCredential",
  "spec": {
    "cluster": {
      "server": "https://172.17.4.100:6443",
      "certificate-authority-data": "LS0t...",
      "config": {
        "arbitrary": "config",
        "this": "可以在设置 provideClusterInfo 时通过 KUBERNETES_EXEC_INFO 环境变量提供",
        "you": ["can", "put", "anything", "here"]
      }
    },
    "interactive": true
  }
}
```

### Why is this needed?

sorry this is a support,what is below cluster config in ExecCredential used to? can you give me an example?

**Comment by sftim** [comment]
/remove-kind feature
/kind support



/close not-planned

Thanks for the question, but GitHub is not the right place for support requests. You could ask on [Stack Exchange](https://stackexchange.com/), post your question on the [Kubernetes Slack](http://slack.k8s.io/), or try the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
