### ISSUE TITLE
Run scheduler_perf benchmark with queueing hints both enabled and disabled

### ISSUE THREAD

**Issue by macsko** [kubernetes/kubernetes#127750]
### What would you like to be added?

Run the scheduler_perf test cases twice: with the queuing hints feature enabled and disabled. Adding a new field to the benchmark results specifying the enablement of the feature may be enough for perf-dash to handle it. We need to consider at which level to enable/disable this feature - in the scheduler_perf code itself or at the test level. 

/sig scheduling

### Why is this needed?

For a better coverage, especially before enabling queuing hints by default we need to make sure the performance tests won't get worse and all test cases are passing consistently.

**Comment by macsko** [comment]
/cc @pohly 
I think you talked about some solutions some time ago.

**Comment by macsko** [comment]
> One approach is to copy all test cases in `performance_config.yaml` and add variants where queuing hints are enabled. The duplication is annoying, but it has the advantage that those copies can have their own performance thresholds - ideally those should be better than without queuing hints!

I think we could even improve this approach - allow specifying feature gates on a workload level. Then one test case could have duplicated similar workloads, but with hints enabled and disabled, so we could define different thresholds for them. In this way, the backbone of the test case will be shared, so we won't lose any consistency.

**Comment by pohly** [comment]
Good idea.

**Comment by alculquicondor** [comment]
> Alternatively, we could define a second directory for running the tests with queuing hints.

I think this is a good idea, with the caveat that this forces us to duplicate the configuration files in two places.

Another option could be to split the configuration file into multiple folders but by topic. For example, topics could be "affinity", "events", "dra"

**Comment by pohly** [comment]
> I think this is a good idea, with the caveat that this forces us to duplicate the configuration files in two places.

I think that could be addressed by making the path where the configuration is expected configurable through the `scheduler_perf` API.

**Comment by macsko** [comment]
> Another option could be to split the configuration file into multiple folders but by topic. For example, topics could be "affinity", "events", "dra"

I like this approach, especially because the number of test cases is constantly growing, so separating it by hints enabled/disabled might not be enough. Could we just create multiple directories for each topic with configuration file inside? Then, we could have sth_test.go file in each directory which will call scheduler_perf tests with the specific config (like 10 lines of code).

**Comment by pohly** [comment]
The downside is that it makes the benchmark job more complex. Instead of one invocation, we will need several different ones.

**Comment by macsko** [comment]
Or we could run benchmarks with one invocation (as it is for now, but with multiple configs) and only apply the strategy above to integration tests where we have timeout limitations.

**Comment by pohly** [comment]
A single invocation with multiple configs from different directories sounds complex, in particular when one such config then reference other artifacts like the dra/*.yaml files.

**Comment by alculquicondor** [comment]
> The downside is that it makes the benchmark job more complex. Instead of one invocation, we will need several different ones.

How so, it can just do something like `test/integration/scheduler_perf/...`?

**Comment by pohly** [comment]
Does writing several different benchmark result files work? They must not use the same name and the consumer must be able to merge them. But you are right, `/...` would be okay.

**Comment by alculquicondor** [comment]
Oh right, that's a good point. If they run serially, perhaps they could all be written to the same file?
I don't know for sure, but it could be worth prototyping.

**Comment by pohly** [comment]
We already have two files:
- [BenchmarkPerfScheduling_benchmark_2024-10-02T04:46:36Z.json](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1841315763823054848/artifacts/BenchmarkPerfScheduling_benchmark_2024-10-02T04:46:36Z.json)
- [BenchmarkResults_benchmark_2024-10-02T03:15:31Z.json](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1841315763823054848/artifacts/BenchmarkResults_benchmark_2024-10-02T03:15:31Z.json)

I remember vaguely that there was some configuration for perf-dash which tells it to read those two. Let's see whether I can find that again....

https://github.com/kubernetes/perf-tests/blob/7adcea6823fe9966e87302640d5888044bc93e70/perfdash/deployment.yaml#L26-L28 points perf-dash towards the current Prow job definitions.

https://github.com/kubernetes/test-infra/blob/b7443a710be4592e19a5cd1536974e66cc9c8a2d/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L725-L727 sets some options for perf-dash, but nothing related to files.

There are other examples with multiple .json files (https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-benchmark-kube-dns-master/1841349738016804864/artifacts/), so I suppose it just works.

**Comment by macsko** [comment]
/assign

It seems we should be able to split directories and merge them in perf-dash by setting [FetchMetricNameFromArtifact](https://github.com/kubernetes/perf-tests/blob/e0f8f40c7233c2bfea625d51f1fecdbe321f559d/perfdash/config.go#L40) to true there.
