### ISSUE TITLE
Failing SIG-Node presubmit jobs

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/kubernetes#127831]
### Which jobs are failing?

- [ ] [pull-crio-cgroupv1-node-e2e-eviction](https://testgrid.k8s.io/sig-node-cri-o#pr-crio-cgroupv1-node-e2e-eviction)
- [ ] [pull-kubernetes-cos-cgroupv2-containerd-node-e2e-eviction](https://testgrid.k8s.io/sig-node-presubmits#pr-cos-cgroupv2-containerd-node-e2e-eviction)
- [ ] [pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial](https://testgrid.k8s.io/sig-node-presubmits#pr-cos-cgroupv2-containerd-node-e2e-serial)
- [ ] pull-kubernetes-e2e-gce
- [ ] [pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e](https://testgrid.k8s.io/sig-node-presubmits#pr-crio-cgrpv1-evented-pleg-gce-e2e) issue: https://github.com/kubernetes/kubernetes/issues/127312
- [ ] [pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e-kubetest2](https://testgrid.k8s.io/sig-node-presubmits#pr-crio-cgrpv1-evented-pleg-gce-e2e-kubetest2)
- [ ] [pull-kubernetes-node-e2e-containerd-alpha-features](https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-containerd-alpha-features)
- [ ] [pull-kubernetes-node-kubelet-containerd-flaky](https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-containerd-flaky)                 

### Which tests are failing?

- E2eNode Suite: [It] [sig-node] PriorityPidEvictionOrdering [Slow] [Serial] [Disruptive] [NodeFeature:Eviction] when we run containers with PodAndContainerStatsFromCRI=false that should cause PIDPressure should eventually evict all of the correct pods
- E2eNode Suite: [It] [sig-node] PriorityPidEvictionOrdering [Slow] [Serial] [Disruptive] [NodeFeature:Eviction] when we run containers with PodAndContainerStatsFromCRI=true that should cause PIDPressure should eventually evict all of the correct pods 
- E2eNode Suite: [It] [sig-node] [NodeFeature:SidecarContainers] Containers Lifecycle when A pod with restartable init containers is terminating when Restartable init containers are terminated during initialization should not hang in termination if terminated during initialization 
- E2eNode Suite: [It] [sig-node] Device Plugin [NodeFeature:DevicePlugin] [Serial] DevicePlugin [Serial] [Disruptive] Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration) [Flaky] 

### Since when has it been failing?

I believe that most of the jobs were not triggered for a long time, so it's hard to say for how long they're failing.

### Testgrid links

https://testgrid.k8s.io/sig-node-presubmits
https://testgrid.k8s.io/sig-node-ec2

### Reason for failure (if possible)

I've triggered all SIG-Node pull* jobs for [my test PR](https://github.com/kubernetes/kubernetes/pull/120459) (the codebase is the same as the latest master branch). Here is how the list of jobs was generated:
```
test-infra (master) $  git grep 'name: pull-' config/jobs/kubernetes/sig-node/*-presubmit.yaml | cut -f3 -d: | while read job ; do echo "/test $job"; done | sort -u

/test pull-crio-cgroupv1-node-e2e-eviction
/test pull-crio-cgroupv1-node-e2e-eviction-kubetest2
/test pull-crio-cgroupv1-node-e2e-features
/test pull-crio-cgroupv1-node-e2e-features-kubetest2
/test pull-crio-cgroupv1-node-e2e-hugepages
/test pull-crio-cgroupv1-node-e2e-hugepages-kubetest2
/test pull-crio-cgroupv1-node-e2e-resource-managers
/test pull-crio-cgroupv1-node-e2e-resource-managers-kubetest2
/test pull-crio-cgroupv2-imagefs-separatedisktest
/test pull-crio-cgroupv2-imagefs-separatedisktest-kubetest2
/test pull-crio-cgroupv2-node-e2e-eviction
/test pull-crio-cgroupv2-node-e2e-eviction-kubetest2
/test pull-crio-cgroupv2-node-e2e-hugepages
/test pull-crio-cgroupv2-node-e2e-hugepages-kubetest2
/test pull-crio-cgroupv2-node-e2e-resource-managers
/test pull-crio-cgroupv2-node-e2e-resource-managers-kubetest2
/test pull-crio-cgroupv2-splitfs-separate-disk
/test pull-crio-cgroupv2-splitfs-separate-disk-kubetest2
/test pull-kubernetes-cos-cgroupv1-containerd-node-e2e
/test pull-kubernetes-cos-cgroupv1-containerd-node-e2e-features
/test pull-kubernetes-cos-cgroupv2-containerd-node-e2e
/test pull-kubernetes-cos-cgroupv2-containerd-node-e2e-eviction
/test pull-kubernetes-cos-cgroupv2-containerd-node-e2e-features
/test pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial
/test pull-kubernetes-crio-node-memoryqos-cgrpv2
/test pull-kubernetes-crio-node-memoryqos-cgrpv2-kubetest2
/test pull-kubernetes-e2e-containerd-gce
/test pull-kubernetes-e2e-gce-kubelet-credential-provider
/test pull-kubernetes-e2e-inplace-pod-resize-containerd-main-v2
/test pull-kubernetes-e2e-relaxed-environment-variable-validation
/test pull-kubernetes-kind-dra
/test pull-kubernetes-kind-dra-all
/test pull-kubernetes-node-arm64-e2e-containerd-ec2
/test pull-kubernetes-node-arm64-e2e-containerd-ec2-canary
/test pull-kubernetes-node-arm64-e2e-containerd-serial-ec2
/test pull-kubernetes-node-arm64-e2e-containerd-serial-ec2-canary
/test pull-kubernetes-node-arm64-ubuntu-serial-gce
/test pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e
/test pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e-kubetest2
/test pull-kubernetes-node-crio-cgrpv2-e2e
/test pull-kubernetes-node-crio-cgrpv2-e2e-kubetest2
/test pull-kubernetes-node-crio-cgrpv2-imagefs-e2e
/test pull-kubernetes-node-crio-cgrpv2-imagefs-e2e-kubetest2
/test pull-kubernetes-node-crio-cgrpv2-imagevolume-e2e
/test pull-kubernetes-node-crio-cgrpv2-imagevolume-e2e-kubetest2
/test pull-kubernetes-node-crio-cgrpv2-splitfs-e2e
/test pull-kubernetes-node-crio-cgrpv2-splitfs-e2e-kubetest2
/test pull-kubernetes-node-crio-cgrpv2-userns-e2e-serial
/test pull-kubernetes-node-crio-cgrpv2-userns-e2e-serial-kubetest2
/test pull-kubernetes-node-crio-e2e
/test pull-kubernetes-node-crio-e2e-kubetest2
/test pull-kubernetes-node-e2e-alpha-ec2
/test pull-kubernetes-node-e2e-containerd
/test pull-kubernetes-node-e2e-containerd-1-7-dra
/test pull-kubernetes-node-e2e-containerd-alpha-features
/test pull-kubernetes-node-e2e-containerd-ec2
/test pull-kubernetes-node-e2e-containerd-ec2-canary
/test pull-kubernetes-node-e2e-containerd-ec2-eks-canary
/test pull-kubernetes-node-e2e-containerd-features
/test pull-kubernetes-node-e2e-containerd-features-kubetest2
/test pull-kubernetes-node-e2e-containerd-kubetest2
/test pull-kubernetes-node-e2e-containerd-serial-ec2
/test pull-kubernetes-node-e2e-containerd-serial-ec2-canary
/test pull-kubernetes-node-e2e-containerd-serial-ec2-eks
/test pull-kubernetes-node-e2e-containerd-serial-ec2-eks-canary
/test pull-kubernetes-node-e2e-containerd-standalone-mode
/test pull-kubernetes-node-e2e-containerd-standalone-mode-all-alpha
/test pull-kubernetes-node-e2e-cri-proxy-serial
/test pull-kubernetes-node-e2e-crio-cgrpv1-dra
/test pull-kubernetes-node-e2e-crio-cgrpv1-dra-kubetest2 # experimental alternative to pull-kubernetes-node-e2e-crio-cgrpv1-dra
/test pull-kubernetes-node-e2e-crio-cgrpv2-dra
/test pull-kubernetes-node-e2e-crio-cgrpv2-dra-kubetest2 # experimental alternative to pull-kubernetes-node-e2e-crio-cgrpv2-dra
/test pull-kubernetes-node-e2e-resource-health-status
/test pull-kubernetes-node-kubelet-containerd-flaky
/test pull-kubernetes-node-kubelet-credential-provider
/test pull-kubernetes-node-kubelet-podresize
/test pull-kubernetes-node-kubelet-serial-containerd
/test pull-kubernetes-node-kubelet-serial-containerd-alpha-features
/test pull-kubernetes-node-kubelet-serial-containerd-kubetest2
/test pull-kubernetes-node-kubelet-serial-containerd-sidecar-containers
/test pull-kubernetes-node-kubelet-serial-cpu-manager
/test pull-kubernetes-node-kubelet-serial-cpu-manager-kubetest2
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv1
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv1-kubetest2
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv2
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv2-kubetest2
/test pull-kubernetes-node-kubelet-serial-hugepages
/test pull-kubernetes-node-kubelet-serial-memory-manager
/test pull-kubernetes-node-kubelet-serial-podresources
/test pull-kubernetes-node-kubelet-serial-topology-manager
/test pull-kubernetes-node-kubelet-serial-topology-manager-kubetest2
/test pull-kubernetes-node-swap-conformance-fedora-serial
/test pull-kubernetes-node-swap-conformance-ubuntu-serial
/test pull-kubernetes-node-swap-fedora
/test pull-kubernetes-node-swap-fedora-serial
/test pull-kubernetes-node-swap-ubuntu-serial
```

### Relevant SIG(s)

/sig node

**Comment by krzyzacy** [comment]
> I believe that most of the jobs were not triggered for a long time, so it's hard to say for how long they're failing.

we'd at least ensure all the blocking presubmit are healthy, and we can probably clean up the older ones if nobody cares about them

**Comment by pacoxu** [comment]
> pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e

This is tracked in https://github.com/kubernetes/kubernetes/issues/127312. for `ci-crio-cgroupv1-evented-pleg`.
- https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-evented-pleg

> pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e-kubetest2 

```
Will use ginkgo flags as: -timeout=24h -nodes=8  -focus="\[NodeConformance\]|\[NodeFeature:.+\]|\[NodeFeature\]"  -skip="\[Flaky\]|\[Slow\]|\[Serial\]"  --no-color -vF1010 14:37:46.322342   10028 gce_runner.go:112] While preparing GCE images: Could not read image config file provided: open --image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/crio/latest/image-config-cgroupv1-evented-pleg.yaml: no such file or directory
```

**Comment by pacoxu** [comment]
> > pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e
> 
> This is tracked in https://github.com/kubernetes/kubernetes/issues/127312. for ci-crio-cgroupv1-evented-pleg.

After https://github.com/kubernetes/test-infra/pull/33633, `pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e-kubetest2` failed for https://github.com/kubernetes/kubernetes/issues/127312 as well.

**Comment by pacoxu** [comment]
> * [ ]  pull-kubernetes-node-arm64-e2e-containerd-ec2-canary
> * [ ]  pull-kubernetes-node-kubelet-containerd-flaky

flaky(known flaking) and canary tests are with lower priority. 

> * [ ]  pull-kubernetes-node-e2e-cri-proxy-serial

This should be fixed by https://github.com/kubernetes/kubernetes/pull/127495.

> * [ ]  pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e

See https://github.com/kubernetes/kubernetes/issues/127312.

> * [ ] pull-crio-cgroupv2-node-e2e-eviction

See https://github.com/kubernetes/kubernetes/issues/127996.

> * [ ]  pull-kubernetes-node-arm64-e2e-containerd-ec2

@bart0sh your fix https://github.com/kubernetes/test-infra/pull/33640 was merged today. It looks green now.

> * [ ]  pull-kubernetes-node-arm64-ubuntu-serial-gce

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-arm64-ubuntu-serial looks green.
- pull-kubernetes-node-arm64-ubuntu-serial-gce flakes a lot. 

Add to my todo list. (will update here once do a diff)

> * [ ]  pull-kubernetes-node-crio-cgrpv2-userns-e2e-serial

Added recently. See https://github.com/kubernetes/kubernetes/pull/127484.

I plan to open an issue to track it.

> * [ ]  pull-kubernetes-node-e2e-containerd-alpha-features
> * [ ]  pull-kubernetes-node-e2e-containerd-standalone-mode-all-alpha

I prefer to think they are related to the Evented PLEG issue. I need to verify.

**Comment by bart0sh** [comment]
@pacoxu Thank you for the detailed overview and the links to the issues! I'll try to continue investigating (and hopefully fixing) pr jobs and running them in the test PR.

**Comment by pacoxu** [comment]
> @pacoxu I excluded -kubetest2 jobs from the scope of this issue as they seem to be a work in progress.

Do you mean the migration process https://github.com/kubernetes/test-infra/issues/32567?

**Comment by bart0sh** [comment]
Yes. I decided to concentrate on more stable jobs. I'm hoping that at the end of this road the -kubetest2 suffix will be removed and my test PR will trigger them automatically. They're still too buggy to pay attention to them right now in my opinion.

**Comment by kannon92** [comment]
/triage accepted
/priority important-longterm

TY for looking into this!

**Comment by kannon92** [comment]
@bart0sh should you be assigned to this?

**Comment by bart0sh** [comment]
@kannon92 thanks for the reminder!
/assign

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/issues/128251
- this also can be seen in presubmit CI: 

```
/test pull-kubernetes-node-e2e-containerd-serial-ec2
/test pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial
```

**Comment by pacoxu** [comment]
Just see https://testgrid.k8s.io/presubmits-kubernetes-blocking this is a blocking board for presubmits CIs.
- We may take them as the top priority and update the board if needed.

**Comment by bart0sh** [comment]
@pacoxu @kannon92 @haircommander I'm going to close this issue as almost all pr jobs failures have been fixed. There are only 4 failing jobs (see [my test pr](https://github.com/kubernetes/kubernetes/pull/120459)) currently:

- [pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/120459/pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial/1869192794141102080) times out because of the new DRA issue. I'm not sure, but it seems to be caused by the [recent changes in this area](https://github.com/kubernetes/test-infra/pull/33969).
- [pull-kubernetes-node-kubelet-containerd-flaky](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/120459/pull-kubernetes-node-kubelet-containerd-flaky/1869192794078187520) should be fixed by [this pr](https://github.com/kubernetes/kubernetes/pull/129010) pending approval.
- 2 evented pleg jobs, which are permanently failing and hopefully have their own issues: [pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/120459/pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e/1869063406347096064) and [pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e-kubetest2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/120459/pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e-kubetest2/1869056601718001664)

Any thoughts/objections/suggestions?

**Comment by bart0sh** [comment]
Thank you! Closing.

**Comment by pacoxu** [comment]
Great job. Thanks @bart0sh.

**Comment by bart0sh** [comment]
Thank you it's been a great run! 

The next step would be to develop a setup which makes sure that no pr jobs is forgotten. Otherwise we'll end up with the same situation after some time. I'd propose to make sure *every* pr job is mapped to the ci job with the same name, e.g. `pull-crio-cgroupv2-splitfs-separate-disk` -> `ci-crio-cgroupv2-splitfs-separate-disk` and develop automatic checks that ensure this mapping. [Generating job configs from easy to maintain configuration file[s]](https://github.com/kubernetes/test-infra/pull/33993#discussion_r1891237103) would also help to maintain this mapping.

Any other ideas?
