### ISSUE TITLE
kubelet GetBootTime() could drift backward for 1s

### ISSUE THREAD

**Issue by leonzz** [kubernetes/kubernetes#127841]
### What happened?

There are a few places in kubelet that calls `pkg/kubelet/util`.`GetBootTime()`. One such place is the kubelet `/stats/summary` endpoint where it's getting the node startTime: [ref](https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/kubelet/server/stats/summary.go#L56)

And there's an issue in the [Linux implementation of `GetBootTime`](https://github.com/kubernetes/kubernetes/blob/v1.31.0/pkg/kubelet/util/boottime_util_linux.go#L30) that the result is not consistent: sometimes it could drift backwards for 1s. This caused problem in certain monitoring systems where the time series database expect timestamps to be monotonically increasing.****

### What did you expect to happen?

`GetBootTime()` to return consistent result everytime it runs, more specifically the kubelet `/stats/summary` endpoint returns a consistent node startTime when kubelet restarts.

### How can we reproduce it (as minimally and precisely as possible)?

do the following steps multiple times:

- restart kubelet
- do a http get on kubelet /stats/summary endpoint
- observe the `node`.`startTime` field in the response

you will see the node startTime could shift backwards for 1s in some cases.

You can also reproduce the issue by simply running the same `GetBootTime` logic multiple times:

```
cat get-boot-time.go 
package main

import (
	"fmt"
	"time"
	"golang.org/x/sys/unix"
)

func main() {
	// This is the same logic as `pkg/kubelet/util/boottime_util_linux.go`
	currentTime := time.Now()
	var info unix.Sysinfo_t
	if err := unix.Sysinfo(&info); err != nil {
		fmt.Errorf("error getting system uptime: %s", err)
		return
	}
	bootTime := currentTime.Add(-time.Duration(info.Uptime) * time.Second).Truncate(time.Second)
	fmt.Printf("bootTime: %s\n", bootTime)
	return
}

$ for i in {1..100} ; do go run get-boot-time.go ; done
bootTime: 2024-09-09 01:04:18 +0000 UTC
bootTime: 2024-09-09 01:04:18 +0000 UTC
bootTime: 2024-09-09 01:04:17 +0000 UTC    <--------- 1s backward drift
bootTime: 2024-09-09 01:04:18 +0000 UTC
 bootTime: 2024-09-09 01:04:18 +0000 UTC
bootTime: 2024-09-09 01:04:18 +0000 UTC
bootTime: 2024-09-09 01:04:18 +0000 UTC
```

### Anything else we need to know?

I think the cause is a combination of multiple factors:

(a) `currentTime := time.Now()` is represented in a sub-second unit
(b) `unix.Sysinfo.Uptime` has a unit in second
(c) GetBootTime() subtracts uptime from current time and then round to the earlier second with the `time`.`Truncate()` method

so the following situation could happen:

1. system actually starts at 0,
2. when kubelet calls GetBootTime(), currentTIme returns 10s 999ms 999us 999ns
3. then 1us later, sysInfo reports Uptime 11s
4. at the end GetBootTime would round (10.999999 - 11) and return -1s instead of the actual 0s

### One possible solution:

The drift always happen when Sysinfo.upTime increased by one second, so we could avoid it by: call the same GetBootTime() logic 3 times in a row, assuming each call finishes < 1s, then there will be for sure at least 2 times where Sysinfo.upTime agrees with each other. Then out of the 2 times, we use the GetBootTime() result from first one.

### Kubernetes version

all existing kubernetes versions

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> One possible solution:

or you just calculate once and cache that value

@thockin you may find this interesting

**Comment by leonzz** [comment]
> One possible solution: The drift always happen when Sysinfo.upTime increased by one second, ...

actually after second thought this is not accurate, the drift can happen when currentTime jumps to the next second as well. Consider this case:

actual bootTime at 0.2 s, then upTime jumps at 1.2s, 2.2s, 3.2s, ...
when currentTime = 4.6s, uptime = 4s,  GetBootTime retuens  bootTime =  0s
but when currentTIme=5.1s, uptime still = 4s,  GetBootTime retuens bootTime = 1s

To get consistent behavior we need a result when both currentTime and uptime haven't incremented

> or you just calculate once and cache that value

Yeah that works too.

It looks like the `uptime -s` command returns pretty consistent result (at least during the few minutes I tried), we could also just run that command.

**Comment by aojea** [comment]
@leonzz 

do you want to submit something like this?
```diff
iff --git a/pkg/kubelet/util/boottime_util_linux.go b/pkg/kubelet/util/boottime_util_linux.go
index b48ef392eeb..02776846326 100644
--- a/pkg/kubelet/util/boottime_util_linux.go
+++ b/pkg/kubelet/util/boottime_util_linux.go
@@ -26,12 +26,19 @@ import (
        "golang.org/x/sys/unix"
 )
 
+var bootTime time.Time
+
 // GetBootTime returns the time at which the machine was started, truncated to the nearest second
 func GetBootTime() (time.Time, error) {
-       currentTime := time.Now()
-       var info unix.Sysinfo_t
-       if err := unix.Sysinfo(&info); err != nil {
-               return time.Time{}, fmt.Errorf("error getting system uptime: %s", err)
+       // cache the boottime value to avoid skew problems
+       if bootTime.IsZero() {
+               currentTime := time.Now()
+               var info unix.Sysinfo_t
+               if err := unix.Sysinfo(&info); err != nil {
+                       return time.Time{}, fmt.Errorf("error getting system uptime: %s", err)
+               }
+               bootTime = currentTime.Add(-time.Duration(info.Uptime) * time.Second).Truncate(time.Second)
        }
-       return currentTime.Add(-time.Duration(info.Uptime) * time.Second).Truncate(time.Second), nil
+
+       return bootTime, nil
 }
diff --git a/pkg/kubelet/util/boottime_util_linux_test.go b/pkg/kubelet/util/boottime_util_linux_test.go
index 4fce0acdeb3..5f2051e21f8 100644
--- a/pkg/kubelet/util/boottime_util_linux_test.go
+++ b/pkg/kubelet/util/boottime_util_linux_test.go
@@ -35,3 +35,21 @@ func TestGetBootTime(t *testing.T) {
                t.Errorf("Invalid system uptime")
        }
 }
+
+func TestGetBootTimeImmutable(t *testing.T) {
+       bootTime, err := GetBootTime()
+       if err != nil {
+               t.Fatal("Unable to get system uptime")
+       }
+
+       for i := 0; i < 1000; i++ {
+               newBootTime, err := GetBootTime()
+               if err != nil {
+                       t.Fatal("Unable to get system uptime")
+               }
+               if !newBootTime.Equal(bootTime) {
+                       t.Errorf("Different system uptime")
+
+               }
+       }
+}
```

**Comment by leonzz** [comment]
@aojea we want the boot time to be consistent across kubelet restarts, so I think an in memory cache won't be enough.  But caching via a file on disk also seems an overkill because we need to worry about clearing that file after system reboot etc. 

do you think it's reasonable to run a `uptime -s` from the GetBootTime() method (assuming the systems kubelet runs on always have the uptime command)?

**Comment by dims** [comment]
@leonzz if i strace the `uptime -s`, it seems to be reading from `/proc/uptime` ... do we want to use that? https://linux.die.net/man/5/proc

[uptime-dash-s.log](https://github.com/user-attachments/files/17284747/uptime-dash-s.log)

**Comment by leonzz** [comment]
> @leonzz if i strace the `uptime -s`, it seems to be reading from `/proc/uptime` ... do we want to use that? https://linux.die.net/man/5/proc
> 
> [uptime-dash-s.log](https://github.com/user-attachments/files/17284747/uptime-dash-s.log)

Thanks! that sounds good to me. Compared to `golang.org/x/sys/unix`.`Sysinfo`,  at least [/proc/uptime has a sub-second part](https://github.com/torvalds/linux/blob/v6.11/fs/proc/uptime.c#L33) that allows us to calculate a more accurate boot time in second.

I can prepare a PR

**Comment by googs1025** [comment]
My intuitive thought when seeing this question is: Can we solve this problem using a method similar to unit conversion?
