### ISSUE TITLE
x509 clients missing User.Uid info for authorization and admission

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#127860]
### What happened?

For all other authenticator types, the authenticator supplies a UID for the user. When an authorizer or admission validator evaluates a request, the uid for x509 users is an empty string.

### What did you expect to happen?

I expected a UID to be populated by the x509 authenticator if set in the certificate. I'd also expect `kubeadm` to have a flag in the `kubeadm kubeconfig user` subcommand to support setting it like `--client-name` and `--org` populate username and groups respectively, so something like `--client-uid`. 

For Kubernetes-created node client certs should probably have the node object's `uid`. Other client x509 certs such as Kube-apiserver client cert for node proxy or client certs from the CSR  API, its not clear if/what Kubernetes should set. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a [kind](https://kind.sigs.k8s.io/) cluster
2. Run `kubectl auth whoami`. No UID is returned as it is for other auth formats

```
kubectl auth whoami
ATTRIBUTE   VALUE
Username    kubernetes-admin
Groups      [kubeadm:cluster-admins system:authenticated]
```

### Anything else we need to know?

As [discussed in #sig-auth](https://kubernetes.slack.com/archives/C0EN96KUY/p1727984474325949), x509 has an optional field for UID. Go's `crypto/x509` doesn't have a named field for it, but it can be set or accessed. 

### Kubernetes version

All versions

### Cloud provider

N/A

### OS version

N/A

**Comment by enj** [comment]
> For all other authenticator types, the authenticator supplies a UID for the user

This is not true.  JWT, token webhook, etc have no requirement to set this field.  In fact, every field can be left unset by the authenticator and it will still get passed down the stack as a user with empty string as their username.
