### ISSUE TITLE
Per instance pods

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#12786]
Hi,

I don't know if this is the right place to post this so please bear with me :)

I am using Kubernetes on AWS and I want to be able to run a pod per instance. This pod will be responsible for instance health checks and log collection/delivery to a centralized place. 
I want that every instance that joins the cluster will automatically boot with this pod.

1. What is the best practice to do it using Kubernetes?
2. If pod per instance is not possible or recommended, then what is the best way to handle instance health checks / centralized logging? I know that kubernetes ships with some of these, but what if I want to integrate my custom components?

Thanks in advance.

**Comment by bgrant0607** [comment]
Hi, @erez-rabih. 

Currently the recommended way is to create a file on each node that the Kubelet reads, described #10093.

Work is underway to add a "daemon controller" (#1518) that would do this more automatically.

Another possible workaround is to create a ReplicationController with a pod template using a hostPort, with as many replicas as nodes.

**Comment by thockin** [comment]
There are two ways to do this.  The first is to drop a config file onto
each node (/etc/kubernetes/manifests by default) which will launch a Pod.
The more modern approach is to use the Daemon feature, which was added
recently in the 1.1 (alpha) channel.  If you're building kubernetes from
HEAD and willing to be at the bleeding edge, you should take a look at
Daemon.

http://code.k8s.io/pkg/api/types.go#L1084

**Comment by bgrant0607** [comment]
Let us know if you have further questions.
