### ISSUE TITLE
1.30.5 binary : 404

### ISSUE THREAD

**Issue by shcherbak** [kubernetes/kubernetes#127837]
### What happened?

404 https://storage.googleapis.com/kubernetes-release/release/v1.30.5/bin/linux/amd64/kubectl

### What did you expect to happen?

200 ok

### How can we reproduce it (as minimally and precisely as possible)?

wget https://storage.googleapis.com/kubernetes-release/release/v1.30.5/bin/linux/amd64/kubectl

### Kubernetes version

1.30.5

### Cloud provider

no

### OS version

all

### Install tools

kubectl

### Container runtime (CRI) and version (if applicable)

all

### Related plugins (CNI, CSI, ...) and versions (if applicable)

all

**Comment by BenTheElder** [comment]
Binaries are hosted at dl.k8s.io, please see the release notes.

**Comment by BenTheElder** [comment]
(https://dl.k8s.io/release/v1.30.5/bin/linux/amd64/kubectl)

**Comment by BenTheElder** [comment]
I wrote a more detailed response here: https://github.com/kubernetes/kubernetes/issues/127796#issuecomment-2392019607

**Comment by shcherbak** [comment]
thx
sorry for disturbing

**Comment by BenTheElder** [comment]
No worries!
