### ISSUE TITLE
kube2sky not able to connect to the kubernetes api-server

### ISSUE THREAD

**Issue by biswars** [kubernetes/kubernetes#12784]
Kubernetes version: 1.0.3
Set up: Using the local set up with coreos cluster (not using GCE).
Note: I am not using any secrets explicitly and the same was working for the earlier version of kubernetes (have tried with kubernetes version 0.16 earlier)

The cluster set up is working fine locally with 1 master and 1 node. Able to list the nodes using "kubectl get no" command.

However dns pod is not working fine and while inspecting, kube2sky logs the following:

I0817 06:36:26.364315       1 kube2sky.go:383] [Attempt: 1] Attempting access to etcd after 5 second sleep
I0817 06:36:31.409058       1 kube2sky.go:389] Etcd server found: http://127.0.0.1:4001
I0817 06:36:32.424772       1 kube2sky.go:455] Using http://localhost:8080 for kubernetes master
I0817 06:36:32.426385       1 kube2sky.go:456] Using kubernetes API
E0817 06:36:32.432580       1 reflector.go:136] Failed to list *api.Service: Get http://localhost:8080/api/v1/services: dial tcp 127.0.0.1:8080: connection refused
E0817 06:36:32.434000       1 reflector.go:136] Failed to list *api.Endpoints: Get http://localhost:8080/api/v1/endpoints: dial tcp 127.0.0.1:8080: connection refused
E0817 06:36:33.436988       1 reflector.go:136] Failed to list *api.Endpoints: Get http://localhost:8080/api/v1/endpoints: dial tcp 127.0.0.1:8080: connection refused
E0817 06:36:33.437375       1 reflector.go:136] Failed to list *api.Service: Get http://localhost:8080/api/v1/services: dial tcp 127.0.0.1:8080: connection refused
E0817 06:36:34.480639       1 reflector.go:136] Failed to list *api.Service: Get http://localhost:8080/api/v1/services: dial tcp 127.0.0.1:8080: connection refused
E0817 06:36:34.481006       1 reflector.go:136] Failed to list *api.Endpoints: Get http://localhost:8080/api/v1/endpoints: dial tcp 127.0.0.1:8080: connection refused

But when I curl http://localhost:8080/api/v1/endpoints (or 127.0.0.1), I get the output with details of the endpoints.

Note: This is a fresh set up so not sure what more needs to be done to make this work. The exact set up works with kubernetes version 0.16 in a separate cluster.

Here is the yaml file submitted via kubectl for the dns set up:

apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns
  namespace: default
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        command:
        - /usr/local/bin/etcd
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.11
        args:
        # command = "/kube2sky"
      - -domain=kubernetes.local
        volumeMounts:
        - mountPath: /etc/dns_token
          name: dns-token
          readOnly: true
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-03-11-001
        args:
        # command = "/skydns"
        - -machines=http://localhost:4001
        - -addr=0.0.0.0:53
        - -domain=kubernetes.local
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      dnsPolicy: Default  # Don't use cluster DNS.

The only difference here compared to the working version earlier is the image version of kube2sky in the yaml, which was gcr.io/google_containers/google_containers-kube2sky:1.7

Any suggestion on how to make this work ?

**Comment by thockin** [comment]
Please see if #10265 applies.

**Comment by biswars** [comment]
Thank @thockin for the reference and it got resolved in it. However, it can be seen very often the kube-proxy logging the following. Not sure if this can be treated as norm as the cluster behaves properly even with this log. At this point I can't warrant the steps done to see this log though.

Aug 21 12:35:15 core-02 kube-proxy[1217]: E0821 12:35:15.360591    1217 proxysocket.go:161] I/O error: read tcp 10.100.41.5:33207: connection reset by peer
Aug 21 12:36:14 core-02 kube-proxy[1217]: E0821 12:36:14.646707    1217 proxysocket.go:161] I/O error: write tcp 10.100.41.5:33213: broken pipe

**Comment by andrewmichaelsmith** [comment]
Anyone hitting this issue - I resolved it by adding (among others, but I believe this to be the important one) ServiceAccount to my `--admission-control=` flag to the kube-apiserver.
