### ISSUE TITLE
DEREF_OF_NULL in common_token_factory.go

### ISSUE THREAD

**Issue by ellena13** [kubernetes/kubernetes#127871]
Dear colleagues!

**Using nil constant** at common_token_factory.go:52

https://github.com/kubernetes/kubernetes/blob/3ceaf84982e40c490c975067ddf202c8b0be09ef/vendor/github.com/antlr/antlr4/runtime/Go/antlr/v4/common_token_factory.go#L51-L52

it is passed as 1st parameter in call to function 'antlr.NewCommonToken'

https://github.com/kubernetes/kubernetes/blob/3ceaf84982e40c490c975067ddf202c8b0be09ef/vendor/github.com/antlr/antlr4/runtime/Go/antlr/v4/token.go#L124-L130

https://github.com/kubernetes/kubernetes/blob/3ceaf84982e40c490c975067ddf202c8b0be09ef/vendor/github.com/antlr/antlr4/runtime/Go/antlr/v4/token.go#L136

where it **is dereferenced** at token.go:136.

***It seems that the nil-check*** for`t.source` ***should be here*** :D

Found by Linux Verification Center (portal.linuxtesting.ru) with SVACE.

Author E. Bykhanova ([e.bykhanova@fobos-nt.ru](mailto:e.bykhanova@fobos-nt.ru)).

**Comment by niranjandarshann** [comment]
I already raised PR  #127879
 for this issue.

**Comment by neolit123** [comment]
you can't PR code under vendor. instead the dependency under vendor must be updated, or in case of indirect dependencies they must be updated to use the fixed version.

this antlr depedency seems unwanted and indirect:
https://github.com/search?q=repo%3Akubernetes%2Fkubernetes+antlr&type=code

/sig architecture
/area code-organization

**Comment by dims** [comment]
/close

please open an issue in antlr and we can update this repository once a fix lands there and a release tag is cut
