### ISSUE TITLE
[Flaky Test] integration-master k8s.io/kubernetes/test/integration/apiserver/peerproxy

### ISSUE THREAD

**Issue by drewhagen** [kubernetes/kubernetes#127858]
### Which jobs are flaking?

* release-master-blocking
** integration-master

### Which tests are flaking?

TestPeerProxiedRequestToThirdServerAfterFirstDies

### Since when has it been flaking?

[10/3/2024, 10:14:04 PM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1842040154072551424)	ci-kubernetes-integration-master	k8s.io/kubernetes/test/integration/apiserver/peerproxy peerproxy
[10/3/2024, 6:17:12 AM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1841799315102633984)	ci-kubernetes-integration-master	k8s.io/kubernetes/test/integration/apiserver/peerproxy peerproxy

Triage: https://storage.googleapis.com/k8s-triage/index.html?text=TestPeerProxiedRequestToThirdServerAfterFirstDies

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

```
{Failed;  === RUN   TestPeerProxiedRequestToThirdServerAfterFirstDies
I1004 10:04:02.830309  113327 feature_gate.go:387] feature gates: {map[APIServerIdentity:true]}
I1004 10:04:02.830412  113327 feature_gate.go:387] feature gates: {map[APIServerIdentity:true StorageVersionAPI:true]}
I1004 10:04:02.830493  113327 feature_gate.go:387] feature gates: {map[APIServerIdentity:true StorageVersionAPI:true UnknownVersionInteroperabilityProxy:true]}
I1004 10:04:03.174302  113327 plugins.go:83] "Registered admission plugin" plugin="NamespaceLifecycle"
I1004 10:04:03.174340  113327 plugins.go:83] "Registered admission plugin" plugin="ValidatingAdmissionWebhook"
I1004 10:04:03.174350  113327 plugins.go:83] "Registered admission plugin" plugin="MutatingAdmissionWebhook"
I1004 10:04:03.174358  113327 plugins.go:83] "Registered admission plugin" plugin="ValidatingAdmissionPolicy"
I1004 10:04:03.174367  113327 plugins.go:83] "Registered admission plugin" plugin="AlwaysAdmit"
I1004 10:04:03.174376  113327 plugins.go:83] "Registered admission plugin" plugin="AlwaysPullImages"
I1004 10:04:03.174385  113327 plugins.go:83] "Registered admission plugin" plugin="LimitPodHardAntiAffinityTopology"
I1004 10:04:03.174393  113327 plugins.go:83] "Registered admission plugin" plugin="DefaultTolerationSeconds"
I1004 10:04:03.174400  113327 plugins.go:83] "Registered admission plugin" plugin="DefaultIngressClass"
I1004 10:04:03.174410  113327 plugins.go:83] "Registered admission plugin" plugin="DenyServiceExternalIPs"
I1004 10:04:03.174418  113327 plugins.go:83] "Registered admission plugin" plugin="AlwaysDeny"
I1004 10:04:03.174426  113327 plugins.go:83] "Registered admission plugin" plugin="EventRateLimit"|
...
```
Please look into the build links above for a longer log.

### Relevant SIG(s)

/sig testing
cc: @release-signal

**Comment by googs1025** [comment]
seem to be same issue: https://github.com/kubernetes/kubernetes/issues/127830

**Comment by aojea** [comment]
yes, please consolidate the information in one, this seems to have more detail @googs1025 

/remove-sig testing
/sig api-machinery

**Comment by googs1025** [comment]
more details to track: https://github.com/kubernetes/kubernetes/issues/127830#issuecomment-2394478224
/cc @richabanker

**Comment by aojea** [comment]
for more visibility, @richabanker comment is

> I did some refactor changes in https://github.com/kubernetes/kubernetes/pull/127718 & https://github.com/kubernetes/kubernetes/pull/122957 (that modified peerproxy_handler) that were merged recently. Will take a look at whats causing the flakiness.

**Comment by jpbetz** [comment]
From failing tests:

```
E1008 23:28:24.399511  113873 peerproxy_handler.go:157] "error finding serviceable-by apiservers for the requested resource" err="missing port in address" gvr="coordination.k8s.io/v1, Resource=leases"
```

xref: https://github.com/kubernetes/kubernetes/pull/122957/files#diff-7bcd0a60c323058ec64ca92eaad9b056ab18c0178f8056fee19d9302974748b9R157

**Comment by jpbetz** [comment]
I don't know if this fully fixes the flake, but locally, when I context cancel the informers for serverA when it is shutdown, it seems to help.  See https://github.com/kubernetes/kubernetes/pull/127945

**Comment by pohly** [comment]
When the apiserver has active clients like watches then it takes longer to shutdown the apiserver. So canceling informers may indeed help.

**Comment by pohly** [comment]
https://github.com/kubernetes/kubernetes/pull/127945 seems to have helped, all the recent runs are green.

**Comment by aojea** [comment]
was not this https://github.com/kubernetes/kubernetes/pull/127909 ?

**Comment by richabanker** [comment]
https://github.com/kubernetes/kubernetes/pull/127909 fixed a bug that was causing the test to fail sometimes with the error `peerproxy_handler.go:157] "error finding serviceable-by apiservers for the requested resource" err="missing port in address" gvr="[coordination.k8s.io/v1](http://coordination.k8s.io/v1), Resource=leases"` and https://github.com/kubernetes/kubernetes/pull/127945 made the test fast, so I think it was both :)

**Comment by aojea** [comment]
perfect
