### ISSUE TITLE
CoreDNS not filter incorrect settings in /etc/resolv.conf

### ISSUE THREAD

**Issue by yuanyuefeng** [kubernetes/kubernetes#127991]
### What happened?

Recently , eanbled dns cache on host itself where update /etc/resolv.conf files as below :
search xxx.yyy.com  zzz.com
nameserver 127.0.0.1
nameserver A.A.A.A 
nameserver B.B.B.B
options ends0 timeout:3 

Once core dns pod running it will copy records from host . And nameserver 127.0.0.1 copied as first nameserver where trigger issue happen. Other pods who query dns from core dns pod will stuck and not get correct ip from dns name. I tested on pure docker env as well. it can auto filter not correct setting in /etc/resolv.conf other than just copy it all. Docker can ignore nameserver 127.0.0.1 or nameserver 0.0.0.0 setting there. 

### What did you expect to happen?

Read content and filter not correct settings in /etc/resolv.conf just as mechanism of docker  

### How can we reproduce it (as minimally and precisely as possible)?

Just enable copy above /etc/resolv.conf and re-deployment core-dns 

### Kubernetes version

kubernetes version: v1.24.10

### Cloud provider

<details>
not sure what should input here
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.10"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.10"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:10:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.10
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.10
$ uname -a
Linux  5.4.17-2136.333.5.el8uek.x86_64 #3 SMP Thu Jun 20 01:03:41 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux



</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by zengyuxing007** [comment]
i think you should use kubelet configuration to provide the specified correct resolv.conf file.

**Comment by yuanyuefeng** [comment]
> i think you should use kubelet configuration to provide the specified correct resolv.conf file.

Thanks for your response. Would u pls share example about how to config it there ?

**Comment by zengyuxing007** [comment]
> > i think you should use kubelet configuration to provide the specified correct resolv.conf file.我认为您应该使用 kubelet 配置来提供指定的正确 resolv.conf 文件。
> 
> Thanks for your response. Would u pls share example about how to config it there ?感谢您的回复。您能否分享有关如何在那里配置它的示例？

```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
- 192.168.0.10
clusterDomain: cluster.local
resolvConf: "/etc/resolv-pod.conf"
...
```
something like this, you can found the spec details fllow this link:  https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
