### ISSUE TITLE
How to Freeze a Kubernetes Namespace to Prevent Deployments?

### ISSUE THREAD

**Issue by zameer712** [kubernetes/kubernetes#127925]
Hello Kubernetes Community,

I am looking for guidance on how to effectively freeze a namespace in a Kubernetes cluster. My goal is to ensure that no new deployments or modifications are allowed within that namespace until I explicitly unfreeze it.

Context:

I am managing multiple namespaces in my cluster and need to temporarily halt all deployments for maintenance purposes.
I want to enforce this restriction at the namespace level without relying on individual deployments or resources to be specified.
Questions:

What are the best practices to achieve a namespace freeze in Kubernetes?
Are there specific configurations or annotations I can use to block deployments?
Is there a built-in feature or tool that can help with this requirement?

**Comment by AmarNathChary** [comment]
the best approach to freeze a namespace will depend on your specific requirements and existing cluster configurations.

- Using Admission Controllers is one of the most effective ways to enforce a namespace freeze and also Validating Admission Webhook  use a combination of an annotation (ex: `freeze=true`)

**Comment by dims** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/127924

/close
