### ISSUE TITLE
Multiple e2e tests failing in parallel with "namespace was not deleted within limit"

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#12799]
e.g. kubernetes-e2e-gce-parallel/6104

Identified problems

Kubectl client Kubectl describe should check if kubectl describe prints relevant information for rc and pods

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:84
Aug 17 06:25:54.496: Couldn't delete ns namespace e2e-tests-kubectl-p4kw2 was not deleted within limit: timed out waiting for the condition, some pods were not marked with a deletion timestamp, pods remaining: [redis-master-rv7ck]

Probing container with readiness probe that fails should never be ready and never restart

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:41
Aug 17 06:25:42.792: Couldn't delete ns "e2e-tests-container-probe-4gdwb": namespace e2e-tests-container-probe-4gdwb was not deleted within limit: timed out waiting for the condition, some pods were not marked with a deletion timestamp, pods remaining: [test-webserver-f58ba3f2-44e2-11e5-8632-42010af01555]

Probing container with readiness probe should not be ready before initial delay and never restart

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:41
Aug 17 06:25:50.459: Couldn't delete ns "e2e-tests-container-probe-shpmy": namespace e2e-tests-container-probe-shpmy was not deleted within limit: timed out waiting for the condition, some pods were not marked with a deletion timestamp, pods remaining: [test-webserver-17eb3ce0-44e3-11e5-be57-42010af01555]

Services should serve multiport endpoints from pods

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:51
Aug 17 06:25:42.506: Couldn't delete ns "e2e-tests-services-ifvtp": namespace e2e-tests-services-ifvtp was not deleted within limit: timed out waiting for the condition, pods remaining: []

Kubectl client Update Demo should do a rolling update of a replication controller

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:84
Aug 17 06:25:45.709: Couldn't delete ns namespace e2e-tests-kubectl-fmhwi was not deleted within limit: timed out waiting for the condition, some pods were not marked with a deletion timestamp, pods remaining: [update-demo-kitten-2nu97 update-demo-kitten-kmw7p]

Pods should *not* be restarted with a docker exec "cat /tmp/health" liveness probe

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:51
Aug 17 06:25:32.823: Couldn't delete ns "e2e-tests-pods-oz3wx": namespace e2e-tests-pods-oz3wx was not deleted within limit: timed out waiting for the condition, pods remaining: []

Services should serve a basic endpoint from pods

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:51
Aug 17 06:25:44.459: Couldn't delete ns "e2e-tests-services-t8z6a": namespace e2e-tests-services-t8z6a was not deleted within limit: timed out waiting for the condition, pods remaining: []

Services should be able to up and down services

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:51
Aug 17 06:26:02.730: Couldn't delete ns "e2e-tests-services-lxupr": namespace e2e-tests-services-lxupr was not deleted within limit: timed out waiting for the condition, pods remaining: []

**Comment by quinton-hoole** [comment]
@smarterclayton fixed this

**Comment by smarterclayton** [comment]
Was this from while graceful was in master (I think the timing is right)?  It's entirely possible that this was due to cluster rate limits on deletion during the e2e tests - I didn't see a lot of these *prior* to my changes going in, but haven't seen these after as well.
