### ISSUE TITLE
pyroscope-server always restarts and cannot be started successfully

### ISSUE THREAD

**Issue by ly0511** [kubernetes/kubernetes#127957]
### What happened?

pyroscope-server always restarts and cannot be started successfully, reporting probe 503 error, version is 1.4.0,There was no operation, it just happened suddenly, I don't know why

### What did you expect to happen?

Started successfully and no longer restarted frequently

### How can we reproduce it (as minimally and precisely as possible)?

The error log information is as follows：
![image](https://github.com/user-attachments/assets/bc17667b-417a-40a4-bf25-75249a9b6621)

the version is pyroscope:1.4.0

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chengjoey** [comment]
This is not a k8s. The obvious reason is that the health check failed (503). You should check the pyroscope-server logs or submit an issue to [pyroscope](https://github.com/grafana/pyroscope)
