### ISSUE TITLE
Named ports specified in sidecar container pod spec are not available to services

### ISSUE THREAD

**Issue by sklirg** [kubernetes/kubernetes#127958]
### What happened?

When migrating a sidecar container to a native sidecar container (initContainer with restartPolicy=Always), traffic going via the Kubernetes Service did not reach the application container/sidecar container.

### What did you expect to happen?

The traffic should have reached the sidecar container like before the migration.

### How can we reproduce it (as minimally and precisely as possible)?

Create a Pod with a native sidecar container (initContainer) with a named port, as well as a Kubernetes Service using that named port as its targetPort. This port is not listed in the Endpoint.

Apply the following:

```
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-ports
  labels:
    app: sidecar-ports
spec:
  containers:
  - image: bloomberg/goldpinger:3.10.1
    name: goldpinger
    ports:
    - containerPort: 8000
      name: http
      protocol: TCP
  initContainers:
  # note: no envoy configuration is provided, the steps to reproduce involve reading other Kubernetes manifests (Endpoints)
  - image: envoyproxy/envoy:v1.73.7
    name: tls-terminator
    ports:
    - containerPort: 9443
      name: https
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar-ports
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: sidecar-ports
  type: ClusterIP
```

The Endpoint backing the created Service "sidecar-ports" should contain two ports; "http" and "https", but it only contains "http":
```
k describe endpoints sidecar-ports
Name:         sidecar-ports
Namespace:    default
Subsets:
  Ports:
    Name  Port  Protocol
    ----  ----  --------
    http  8000  TCP

Events:  <none>
```

### Anything else we need to know?

The feature gate is enabled:

```
kubectl get --raw /metrics | grep kubernetes_feature_enabled | grep SidecarContainers
kubernetes_feature_enabled{name="SidecarContainers",stage="BETA"} 1
```

I was suggested to create this issue in [this Slack thread](https://kubernetes.slack.com/archives/C06JCTLFPFX/p1728475764781559)

Workarounds:

1) 

If we update the Service to contain numeric ports instead of named ports, they show up in the endpoint:
```diff
k diff -f reproduce.yaml
diff -u -N /tmp/LIVE-529307225/v1.Service.default.sidecar-ports /tmp/MERGED-1321372933/v1.Service.default.sidecar-ports
--- /tmp/LIVE-529307225/v1.Service.default.sidecar-ports 2024-10-09 14:40:30.518739432 +0200
+++ /tmp/MERGED-1321372933/v1.Service.default.sidecar-ports      2024-10-09 14:40:30.518739432 +0200
@@ -25,7 +25,7 @@
   - name: https
     port: 443
     protocol: TCP
-    targetPort: https
+    targetPort: 9443
   selector:
     app: sidecar-ports
   sessionAffinity: None
```

```
Name:         sidecar-ports
Namespace:    default
Subsets:
  Ports:
    Name   Port  Protocol
    ----   ----  --------
    https  9443  TCP
    http   8000  TCP

Events:  <none>
```

2)

If we specify the named port in the "main" container instead of in the initContainer, the port shows up in the endpoint:

```diff
spec:
  containers:
  - image: bloomberg/goldpinger:3.10.1
    name: goldpinger
    ports:
    - containerPort: 8000
      name: http
      protocol: TCP
+    - containerPort: 9443
+      name: https
+      protocol: TCP
  initContainers:
  # note: no envoy configuration is provided, the steps to reproduce involve reading other Kubernetes manifests (Endpoints)
  - image: envoyproxy/envoy:v1.73.7
    name: tls-terminator
-    ports:
-    - containerPort: 9443
-      name: https
-      protocol: TCP
```

```
Name:         sidecar-ports
Namespace:    default
Subsets:
  Ports:
    Name   Port  Protocol
    ----   ----  --------
    https  9443  TCP
    http   8000  TCP

Events:  <none>
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.9
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8
```

</details>

### Cloud provider

<details>
Self-hosted, kubeadm-driven.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
I'll say Ubuntu.
$ uname -a
I can provide this if strictly relevant.

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
```
$ containerd --version
containerd containerd.io 1.7.20 8fc6bcff51318944179630522a095cc9dbf9f353
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/sig network
/sig node

Not sure which one is the best sig here

**Comment by uablrek** [comment]
I have interpreted "sidecar container" as a container that is _not_ part of the application, and optional, e.g. a service mesh. Implementing the suggested feature makes it possible to create an application (pods+service) that _can't be loaded_ without sidecar containers. I think that opens possible issues where an application can't be loaded, and the fix would be something like: "Oh, you have to install feature Y first, which will add required sidecar containers using a web-hook".

In the example, if the named port is _required_ (as part of the application) it should be defined in a normal (non-sidecar) container (work-around 1). To use numeric ports (work-around 2) allows the application to be loaded with or without sidecar containers.

**Comment by uablrek** [comment]
And BTW I brought this up on the sig/network meeting today, and it seemed I was the only one having problems with it.

**Comment by matthyx** [comment]
so should we close this?

**Comment by SergeyKanzhelev** [comment]
@aojea wdyt?

**Comment by SergeyKanzhelev** [comment]
The fix seems to be straightforward: https://github.com/kubernetes/kubernetes/pull/127976

**Comment by aojea** [comment]
> officially supported on API, I would think we need to fix this as a bug

I think we need to fix it, agree we should not make distinction on the type of container from the networking point of view on the cluster and be consistent
It is also the expectations of users, see https://github.com/kubernetes/kubernetes/issues/125285 that is also reporting the same problem
