### ISSUE TITLE
Unable to migrate to kms v2

### ISSUE THREAD

**Issue by krishnan206** [kubernetes/kubernetes#127950]
### What happened?

We tried to migrate kms plugin from v1 to v2 as kms v1 is deprecated with Micork8s version v1.26 onwards.
During the migration, we were unable to create secrets using kms plugin and we are getting below errors:
```
failed to create: Internal error occurred: got unexpected nil transformer
```

### What did you expect to happen?

The secrets should be created successfully

### How can we reproduce it (as minimally and precisely as possible)?

1. Upgrade the kubernetes to v1.30.3
2. Migrate the KMS plugin to v2
3. Create a new secret with command:
```
kubectl create secret generic kmssecret -n default --from-literal=mykey="This a test data to encrypt"
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
```

</details>

### Cloud provider

<details>
Microk8s On-Premise
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux kms-test 6.6.16generic #1 SMP PREEMPT_DYNAMIC Sat Jun  8 12:36:32 UTC 2024 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
Microk8s
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
a better place to ask would be on the support channels or Microk8s community. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
