### ISSUE TITLE
kubernetes-e2e-gke-ci-reboot e2e test is perma-broken with "Kubelet stopped posting node status" after reboot

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#12804]
e.g.
kubernetes-e2e-gke-ci-reboot/2633/

Root cause seems to be multiple cases of nodes not becoming ready within 5 minutes after a reboot, e.g.

Aug 17 06:16:54.677: INFO: Node gke-jenkins-gke-e2e-ci-reboot-a503d07f-node-m0el condition 1/1: type: Ready, status: Unknown, reason: "Kubelet stopped posting node status.", message: "", last transition time: 2015-08-17 06:11:55 -0700 PDT
Aug 17 06:16:59.574: INFO: Node gke-jenkins-gke-e2e-ci-reboot-a503d07f-node-hejo didn't reach desired readiness (true) within 5m0s

• Failure [355.792 seconds]

@roberthbailey is anyone on your team looking into this?

**Comment by quinton-hoole** [comment]
Possibly related to #12800

**Comment by jlowdermilk** [comment]
Right now it's failing for the same reason as e2e-gke-ci. #13001 should fix that, at which point I can see what the original failure was.

**Comment by quinton-hoole** [comment]
Fixed by #12824
