### ISSUE TITLE
[Failing Test] [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#128047]
### Which jobs are failing?

pull-kubernetes-node-e2e-containerd-alpha-features

### Which tests are failing?

E2eNode Suite.[It] [sig-node] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api

### Since when has it been failing?

NA
- some old failing issue https://github.com/kubernetes/kubernetes/issues/120079 and https://github.com/kubernetes/kubernetes/issues/119400. @tzneal @harche 

### Testgrid link

https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-containerd-alpha-features

### Reason for failure (if possible)

```

E2eNode Suite: [It] [sig-node] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api expand_less  

{ failed [FAILED] Timed out after 60.001s. Expected     <metrics.KubeletMetrics \

- node_cpu_usage_seconds_total:

...

to have key
    <string>: container_cpu_usage_seconds_total
In [It] at: k8s.io/kubernetes/test/e2e_node/resource_metrics_test.go:120 @ 10/14/24 04:25:20.818
```

### Anything else we need to know?

container_cpu_usage_seconds_total seems to be the root cause here. 

### Relevant SIG(s)

/sig node instrumentation

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/issues/119853#issuecomment-1852953216 may indict that this may be a bug, but still need more information.

**Comment by haircommander** [comment]
cc @akhilerm @bart0sh
