### ISSUE TITLE
KEP-4832(alpha): Increase the test coverage of `/pkg/scheduler/framework/preemption/preemption.go`

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#128018]
This is for KEP-4832.

https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/4832-async-preemption/README.md#unit-tests

Given the coverage for preemption.go is pretty low, we have to improve the testing there.

Note that it should be done as soon as possible ideally before making a core change for KEP, at the latest by the code freeze `02:00 UTC Friday 8th November 2024 / 19:00 PDT Thursday 7th November 2024: Week 9` ([ref](https://www.kubernetes.dev/resources/release/)).

**Comment by googs1025** [comment]
It seems that some work has been done on this PR. https://github.com/kubernetes/kubernetes/pull/126933

**Comment by googs1025** [comment]
I will continue to improve the coverage of other parts

**Comment by sanposhiho** [comment]
Thanks, @googs1025 !

**Comment by googs1025** [comment]
thanks for @alculquicondor Sure, I'll try to add this test case. 
I understand this perspective, but there is a small issue: directly verifying all possible state changes through public methods can be difficult, and testing private variables can help ensure the consistency and correctness of the internal state.

**Comment by googs1025** [comment]
Completed. Close this issue
/close
