### ISSUE TITLE
[Failing Test]  TestNestedNumberAsFloat64/found_int64_not_representable_as_float64 is failing on arm64, ppc64le

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#128094]
### Which jobs are failing?

https://prow.k8s.io/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le

### Which tests are failing?

```

=== FAIL: k8s.io/apimachinery/pkg/apis/meta/v1/unstructured TestNestedNumberAsFloat64/found_int64_not_representable_as_float64 (0.00s)
    helpers_test.go:283: got 9.223372036854776e+18, wanted 0
    helpers_test.go:286: got true, wanted false
    helpers_test.go:290: got nil error, wanted .value accessor error: int64 value 9223372036854775807 cannot be losslessly converted to float64

=== FAIL: k8s.io/apimachinery/pkg/apis/meta/v1/unstructured TestNestedNumberAsFloat64 (0.00s)
```

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers_test.go#L272

### Since when has it been failing?

Since the testcase addition in change https://github.com/kubernetes/kubernetes/pull/127838

### Testgrid link

https://testgrid.k8s.io/ibm-k8s-unit-tests-ppc64le#periodic-k8s-unit-tests-ppc64le

### Reason for failure (if possible)

The value of MaxInt64 from math package's file [const.go](https://github.com/golang/go/blob/master/src/math/const.go#L50) varies across architectures as mentioned at the top of file.

`// This package does not guarantee bit-identical results across architectures.`

We need to avoid values which trigger implementation defined behavior.

### Anything else we need to know?

We could confirm this failure on `arm64` and `ppc64le` architectures.

### Relevant SIG(s)

/sig testing

**Comment by benluddy** [comment]
Looking... I don't think we depend a particular bit representation of the int64 fixture, but double-checking the Go spec, the result of the int64-to-float64 conversion is implementation-defined. I'll figure out how to do this in a portable way.

**Comment by liggitt** [comment]
> The value of MaxInt64 from math package's file [const.go](https://github.com/golang/go/blob/master/src/math/const.go#L50) varies across architectures as mentioned at the top of file.

I don't think that's accurate... MaxInt64 does not vary across architectures... though the float might

**Comment by mkumatag** [comment]
This failure introduced almost a week back and happening on arm64 platform as well, wondering why it is unnoticed so far? where can we see all the UT test runs for the arm64 architecture?

**Comment by mkumatag** [comment]
Similar behaviour fixed in the past, see if this helps - https://github.com/kubernetes/kubernetes/pull/120097

**Comment by benluddy** [comment]
> https://testgrid.k8s.io/ibm-k8s-unit-tests-ppc64le#periodic-k8s-unit-tests-ppc64le

I checked testgrid this morning. There have been several runs since the intended fix merged yesterday and the test is passing consistently. Thanks for noticing and reporting this issue.

**Comment by mkumatag** [comment]
> > https://testgrid.k8s.io/ibm-k8s-unit-tests-ppc64le#periodic-k8s-unit-tests-ppc64le
> 
> I checked testgrid this morning. There have been several runs since the intended fix merged yesterday and the test is passing consistently. Thanks for noticing and reporting this issue.

Thanks @benluddy for quick triage and fix :rocket:
