### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Disable in-place resize for guaranteed pods on nodes with a static topology policy

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#128068]
See https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1287-in-place-update-pod-resources/README.md#static-cpu--memory-policy

We probably want to introduce a new feature gate to allow resize in this case to unblock development on https://github.com/kubernetes/kubernetes/issues/127262.

/sig node
/kind feature
/priority important-longterm

**Comment by tallclair** [comment]
@esotsal any interest in picking this up?

**Comment by olderTaoist** [comment]
@tallclair let me try？
/assign

**Comment by olderTaoist** [comment]
> > [@tallclair](https://github.com/tallclair) let me try？ /assign
> 
> Do you working this issue? @olderTaoist

i already read  the [InPlacePodVerticalScaling](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1287-in-place-update-pod-resources/README.md). but i notice @esotsal previous [implementation](https://github.com/kubernetes/kubernetes/pull/123319),  if @esotsal don't mind, i perfer want to work this issue.

**Comment by esotsal** [comment]
> > > [@tallclair](https://github.com/tallclair) let me try？ /assign
> > 
> > 
> > Do you working this issue? @olderTaoist
> 
> i already read the [InPlacePodVerticalScaling](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1287-in-place-update-pod-resources/README.md). but i notice @esotsal previous [implementation](https://github.com/kubernetes/kubernetes/pull/123319), if @esotsal don't mind, i perfer want to work this issue.

It links with the ongoing PR  I am working with, it is not same Thanks for volunteering @olderTaoist and @lengrongfu but prefer to work on this as initially asked by Tim

**Comment by drewhagen** [comment]
Hello @esotsal @olderTaoist @lengrongfu @tallclair 

Really appreciate all the activity here! If there's anything we can do, please let us know.

Friendly reminder that code freeze is starting `02:00 UTC Friday November 8th 2024` (**about 3 weeks from now**), and while there is still time, we want to ensure that each PR has a chance to be merged on time.

Is this issue still planned for release `1.32`? Thanks!

**Comment by esotsal** [comment]
> Hello @esotsal @olderTaoist @lengrongfu @tallclair
> 
> Really appreciate all the activity here! If there's anything we can do, please let us know.
> 
> Friendly reminder that code freeze is starting `02:00 UTC Friday November 8th 2024` (about **3 weeks from now**), and while there is still time, we want to ensure that each PR has a chance to be merged on time.
> 
> Given this timeline, do we feel this will be able to release for `1.32`? Thanks!

Yes, that’s the goal.

**Comment by drewhagen** [comment]
Hello again 👋 @esotsal @olderTaoist @lengrongfu @tallclair 
Following up on the goal for this to go out with the `v1.32` release. I see this issue is active - awesome work!

Friendly reminder that the code freeze is starting `02:00 UTC Friday November 8th 2024` (a little less than **1 week from now**). Please make sure the linked PRs have both `lgtm` and `approved` labels before the code freeze. Thanks! 🚀

**Comment by drewhagen** [comment]
👋 Hello  @esotsal @olderTaoist @lengrongfu @tallclair
Is the plan still to resolve this issue for v1.32?

If so, a gentle reminder that the code freeze has started `02:00 UTC Friday November 8th 2024`. Please make sure any PRs have both `lgtm` and `approved` labels ASAP, and file an [Exception](https://github.com/kubernetes/sig-release/blob/master/releases/EXCEPTIONS.md).
Thanks!
