### ISSUE TITLE
KEP-4832(alpha): Implement new metrics `goroutines_duration_seconds` and `goroutines_execution_total` 

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#128019]
We want to add new metrics goroutines_duration_seconds and goroutines_execution_total for the observability for KEP-4832.

https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/4832-async-preemption/README.md#are-there-any-missing-metrics-that-would-be-useful-to-have-to-improve-observability-of-this-feature

Note that it should be done by the code freeze, `02:00 UTC Friday 8th November 2024 / 19:00 PDT Thursday 7th November 2024: Week 9` ([ref](https://www.kubernetes.dev/resources/release/)).

**Comment by Gekko0114** [comment]
Hi @sanposhiho 
Which function's execution time do these metrics measure?

I thought that these metrics will be measured similar to `StorageOperationMetric` or other metrics.
Do I understand correctly?
https://github.com/kubernetes/kubernetes/blob/4812ea8aa5a49384ca8db7770da299fea6a48015/pkg/volume/util/metrics.go#L46C5-L46C27

**Comment by sanposhiho** [comment]
It's like the existing `goroutine` metric, measuring the duration and the count of goroutine, triggered by the parallelizer.

https://github.com/kubernetes/kubernetes/blob/master/pkg%2Fscheduler%2Fframework%2Fparallelize%2Fparallelism.go#L57-L57

**Comment by Gekko0114** [comment]
I got it, then I will create a PR.

**Comment by Gekko0114** [comment]
Hi @sanposhiho 
I've created a PR, could you have a look?
https://github.com/kubernetes/kubernetes/pull/128023
