### ISSUE TITLE
kube-api proxy does not proxy to kubelet running on `127.0.0.1`

### ISSUE THREAD

**Issue by SimonBaeumer** [kubernetes/kubernetes#128001]
### What happened?

While running Kubernetes locally, using `./hack/local-cluster-up.sh`, I wanted to send requests to the kubelet `proxy` endpoint in the api-server, like this:

```
curl -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"   https://localhost:6443/api/v1/nodes/127.0.0.1/proxy/healthz
```

The response returned a `400` HTTP status code and the message was `address not allowed`.

### What did you expect to happen?

I've expected that the request is able to proxy to IP address `127.0.0.1` successfully because it is the node's IP address.

### How can we reproduce it (as minimally and precisely as possible)?

Run kubernetes with `hack/local-up-cluster.sh` scripts locally (or kubelet running on 127.0.0.1).

Assign the `system:kubelet-api-admin` role to Pod's service account, mount the Service Account token and run the following curl command:

curl -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"   https://localhost:6443/api/v1/nodes/127.0.0.1/proxy/healthz

### Anything else we need to know?

The following check for a Global Unicast address causes the error message: https://github.com/kubernetes/kubernetes/blob/1dc05009fe7f4e1d139b0c8394683edb54f8d082/pkg/registry/core/node/strategy.go#L248-L250

I think there should a special case to handle when kubelet runs on 127.0.0.1 and is accessible.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.0", GitCommit:"7c48c2bd72b9bf5c44d21d7338cc7bea77d0ad2a", GitTreeState:"clean", BuildDate:"2024-05-13T22:00:36Z", GoVersion:"go1.22.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
localhost 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Workstation Edition"
VARIANT_ID=workstation

$ uname -a
Linux XXXXXXXX 6.10.10-100.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 16:02:41 UTC 2024 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pranav-pandey0804** [comment]
It looks like the issue is related to how the API server blocks proxying requests to `127.0.0.1` because it checks for a Global Unicast address.

**Comment by pranav-pandey0804** [comment]
This makes sense for security in standard Kubernetes setups, 
but for local development, especially when using something like `hack/local-up-cluster.sh`, it would be super helpful to allow exceptions for `127.0.0.1`.

**Comment by pranav-pandey0804** [comment]
A workaround could be adding a special rule to the proxy validation that permits requests to loopback addresses like `127.0.0.1`.

**Comment by pranav-pandey0804** [comment]
This would be great for developers testing locally, without affecting production clusters. Maybe it’s also worth updating the documentation to mention this behavior when using `hack/local-up-cluster.sh`, just so others are aware of the current limitations for conformance tests.

**Comment by aojea** [comment]
This opens a security risk, since it can be used in production to connect to the host where apiserver is running

https://github.com/kubernetes/kubernetes/pull/71980

> This would be great for developers testing locally, 

developer testing locally don't need to proxy , they can reach all the endpoints directly

Thanks

/close

**Comment by sftim** [comment]
/reopen
momentarily
