### ISSUE TITLE
release-1.0 Shippable broken after rename

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#12805]
Please propose cherry-pick any changes after the great rename into the release branch.

See e.g. #12559

**Comment by mikedanese** [comment]
There are two ways to fix this:

1. I can PR a one line commit to fix shippable.yml, but the change will not be in master
2. I cherry-pick the "rewrite all import paths to k8s.io/" commit.

Do you have a preference?

**Comment by zmerlynn** [comment]
The latter would improve cherry-pickability of anything else, wouldn't it?

**Comment by mikedanese** [comment]
Sure, I will prepare that.
