### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Implement updated AllocatedResources logic

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#128065]
The logic for handling allocated resources with in-place pod resize is changing for beta, as described here: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1287-in-place-update-pod-resources/README.md#allocated-resources

In summary, the following changes are needed:
- [ ] Most references to `status...AllocatedResources` outside the Kubelet should move to `status...Resources`
    - [ ] https://github.com/kubernetes/kubernetes/issues/117765
- [ ] Move handling of the `AllocatedResources` field behind the new `InPlacePodVerticalScalingAllocatedStatus` feature gate
- [ ] Kubelet references to `AllocatedResources` should move to read from the status manager directly
- [ ] `status...Resources` should be set to the allocated resources if the pod is not running

/kind feature
/sig node
/milestone v1.32
/priority important-longterm
/area kubelet

**Comment by bouaouda-achraf** [comment]
Is anyone currently working on the following tasks?

- Kubelet references to AllocatedResources should move to read from the status manager directly
- status...Resources should be set to the allocated resources if the pod is not running

If these tasks are not assigned, I’d be happy to take on one of them .

**Comment by knabben** [comment]
Hello @tallclair @hshiina 
This issue has not been updated for a long time, so I'd like to check what's the status. It seems #127773 fixes this issue.
The code freeze is starting 02:00 UTC Friday November 8th 2024 (about 3 weeks from now), and while there is still time, we want to ensure that each PR has a chance to be merged on time.
As the issue/PR is tagged for 1.32, is it still planned for this release?

**Comment by knabben** [comment]
Hey @tallclair @hshiina
⚠️ Do we still intend to merge this for v1.32? Just a reminder that the code freeze is starting 02:00 UTC Friday November 8th 2024 (a little less than 1 week from now). Please make sure the PR has both lgtm and approved labels before the code freeze. Thanks!
