### ISSUE TITLE
[Flaking Test] [sig-node] [NodeFeature:SidecarContainers] Containers Lifecycle when using a restartable init container in a Pod with restartPolicy=Always 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#128015]
### Which jobs are flaking?

 - ci-cri-containerd-node-e2e-features
 - ci-cos-containerd-node-e2e-features
 - ci-crio-cgroupv2-node-e2e-features
 - ci-crio-cgroupv1-node-e2e-features
 - pull-kubernetes-node-crio-cgrpv2-e2e

### Which tests are flaking?

- when a restartable init container runs continuously should not restart a restartable init container

https://storage.googleapis.com/k8s-triage/index.html?test=%20when%20a%20restartable%20init%20container%20runs%20continuously%20should%20not%20restart%20a%20restartable%20init%20container

### Since when has it been flaking?

long time ago

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#node-e2e-features one of them

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cri-containerd-node-e2e-features/1842930891668590592
```
{ failed [FAILED] expected restartable-init-1 to not start after regular-1, got
0) 2024-10-06 14:26:09.114 +0000 UTC restartable-init-1 Starting
1) 2024-10-06 14:26:09.114 +0000 UTC regular-1 Starting
2) 2024-10-06 14:26:09.15 +0000 UTC restartable-init-1 Started
3) 2024-10-06 14:26:09.157 +0000 UTC regular-1 Started
4) 2024-10-06 14:26:09.172 +0000 UTC restartable-init-1 Delaying
5) 2024-10-06 14:26:09.174 +0000 UTC regular-1 Delaying
6) 2024-10-06 14:26:10.197 +0000 UTC regular-1 Exiting
7) 2024-10-06 14:26:11.399 +0000 UTC regular-1 Starting
8) 2024-10-06 14:26:11.423 +0000 UTC regular-1 Started
9) 2024-10-06 14:26:11.438 +0000 UTC regular-1 Delaying
10) 2024-10-06 14:26:12.459 +0000 UTC regular-1 Exiting
11) 2024-10-06 14:26:26.731 +0000 UTC regular-1 Starting
12) 2024-10-06 14:26:26.746 +0000 UTC regular-1 Started
13) 2024-10-06 14:26:26.755 +0000 UTC regular-1 Delaying
14) 2024-10-06 14:26:27.767 +0000 UTC regular-1 Exiting
In [It] at: k8s.io/kubernetes/test/e2e_node/container_lifecycle_test.go:2412 @ 10/06/24 14:26:29.999
}
```

### Anything else we need to know?

Other failed example https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/120459/pull-kubernetes-node-crio-cgrpv2-e2e/1841786523335266304

https://github.com/kubernetes/kubernetes/blob/4812ea8aa5a49384ca8db7770da299fea6a48015/test/e2e_node/container_lifecycle_test.go#L2403-L2463

### Relevant SIG(s)

/sig node

**Comment by pacoxu** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/120459/pull-kubernetes-cos-cgroupv1-containerd-node-e2e-features/1844846418351624192 
- `E2eNode Suite: [It] [sig-node] [NodeFeature:SidecarContainers] Containers Lifecycle when A pod with restartable init containers is terminating when the restartable init containers have multiple PreStop hooks should call sidecar container PreStop hook simultaneously` is similar.

**Comment by pacoxu** [comment]
@SergeyKanzhelev 

### `a Pod with restartPolicy=Always` 
https://github.com/kubernetes/kubernetes/blame/3ec1f3df5fe9e265a3272610a8ace63010bb09d6/test/e2e_node/container_lifecycle_test.go#L2456-L2462 

For a regular container and a sidecar container,
```
0) 2024-07-27 03:02:39.952 +0000 UTC restartable-init-1 Starting
1) 2024-07-27 03:02:39.952 +0000 UTC regular-1 Starting
2) 2024-07-27 03:02:39.969 +0000 UTC regular-1 Started
3) 2024-07-27 03:02:39.97 +0000 UTC restartable-init-1 Started
```

The regular container will not wait until the restartable-init-1 is started. 

In most case, first starting, and first started. But sometimes not.


https://github.com/kubernetes/kubernetes/blob/3ec1f3df5fe9e265a3272610a8ace63010bb09d6/test/e2e_node/container_lifecycle_pod_construction.go#L182-L198

I think this is the root cause.

**Comment by toVersus** [comment]
> The regular container will not wait until the restartable-init-1 is started.

Yeah, this seems like expected behavior for Sidecar Containers without startup probes. The startup sequence starts with `restartable-init-1`, followed by the `regular-1`, but there's no guarantee they'll finish starting up in that order. Looks like we might need to tweak how the test is written. I'll take a look at it.

/assign
