### ISSUE TITLE
kubelet generates ~6MB/min of logs

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#12816]
This seems wrong?

~$ ls --full-time -sh /var/log/kubelet.log
85M 2015-08-17 19:32:16.488672699
$ ls --full-time -sh /var/log/kubelet.log
91M 2015-08-17 19:33:16.652642208

Here are the main culprits on the node I'm currently looking at:

$ cat /var/log/kubelet.log | awk '{print $4}' | sort | uniq -c | sort -nr
  46863 manager.go:293]
  23000 kubelet.go:2315]
  11845 volumes.go:95]
  11730 volumes.go:193]
  11730 volumes.go:156]
  11728 manager.go:1488]
  11728 manager.go:1457]
  11500 manager.go:1537]
  11500 manager.go:1434]
  11500 manager.go:1421]
  11500 manager.go:1410]
  11498 prober.go:180]
  11465 status_manager.go:129]
   5253 container.go:383]
   1150 prober.go:216]
    460 http.go:71]
    445 server.go:676]
    236 server.go:634]
    230 prober.go:169]
    115 kubelet.go:1796]
    115 kubelet.go:1429]
    115 gce_pd.go:176]
     76 config.go:253]
     69 file.go:135]
     17 manager.go:312]
     10 reflector.go:302]
      6 reflector.go:224]
      4 handler.go:322]
      3 status_manager.go:169]
      2 manager.go:837]
      2 manager.go:782]
      2 manager.go:641]
      2 manager.go:1587]
      2 manager.go:1449]
      2 factory.go:78]
      2 container.go:368]

Examples of the top few:

*  46863 manager.go:293] Container inspect result: {ID:f0b3903e459d25d557793ca461fdf703f35abee78fde8d0fda1f531c2cfc511d Created:2015-08-17 18:25:12.457518663 +0000 UTC Path:/pause Args:[] Config:0xc20b2a8180 State:{Running:true Paused:false Restarting:false OOMKilled:false Pid:14383 ExitCode:0 Error:
 StartedAt:2015-08-17 18:25:18.783167855 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC} Image:6c4579af347b649857e915521132f15a06186d73faa62145e3eeeb6be0e97c27 Node:<nil> NetworkSettings:0xc20a875200 SysInitPath: ResolvConfPath:/var/lib/docker/containers/8da35ee3ba957ed5df527bb9cc118e7fee06c0c002bc2f6e3e157fa6a326393
7/resolv.conf HostnamePath:/var/lib/docker/containers/8da35ee3ba957ed5df527bb9cc118e7fee06c0c002bc2f6e3e157fa6a3263937/hostname HostsPath:/var/lib/docker/containers/8da35ee3ba957ed5df527bb9cc118e7fee06c0c002bc2f6e3e157fa6a3263937/hosts LogPath:/var/lib/docker/containers/f0b3903e459d25d557793ca461fdf703f35abee78fde8d0fda1
f531c2cfc511d/f0b3903e459d25d557793ca461fdf703f35abee78fde8d0fda1f531c2cfc511d-json.log Name:/k8s_cleanup30-fe85342b-448b-11e5-839c-42010af01555.cd063718_cleanup30-fe85342b-448b-11e5-839c-42010af01555-z63t1_e2e-tests-kubelet-hbdlk_fe9628cb-448b-11e5-b08d-42010af027db_ada2439b Driver:aufs Volumes:map[/var/run/secrets/kube
rnetes.io/serviceaccount:/var/lib/kubelet/pods/fe9628cb-448b-11e5-b08d-42010af027db/volumes/kubernetes.io~secret/default-token-6kp3j /dev/termination-log:/var/lib/kubelet/pods/fe9628cb-448b-11e5-b08d-42010af027db/containers/cleanup30-fe85342b-448b-11e5-839c-42010af01555/f0b3903e459d25d557793ca461fdf703f35abee78fde8d0fda1
f531c2cfc511d] VolumesRW:map[/dev/termination-log:true /var/run/secrets/kubernetes.io/serviceaccount:false] HostConfig:0xc20d2906c0 ExecIDs:[] RestartCount:0 AppArmorProfile:}
* 23000 kubelet.go:2315] Generating status for "proxy-service-08iel-4105c_e2e-tests-proxy-oimgf"
* 11845 volumes.go:95] Used volume plugin "kubernetes.io/host-path" for varlog

**Comment by roberthbailey** [comment]
How many containers are you running on the node? Presumably the amount of output would scale with the number of containers (since we print out the inspect result). 

Also note that we run the kubelet at `v=2` by default. Maybe we should consider running at a lower verbosity -- or change the verbosity of some of the larger / more frequent log lines.

**Comment by yujuhong** [comment]
Clarification:  The inspect logging line is at v=3, so this is only a problem for a testing cluster ([v=4](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L58)).

**Comment by quinton-hoole** [comment]
Aah - given @yujuhong's explanation, I'm happy to close this as working as intended.  

It's probably worth checking that our scalability testing clusters are not running at such high log verbosity, as I'm pretty sure that this level of logging will skew scalability and performance.  @wojtek-t you might want to check that.

**Comment by wojtek-t** [comment]
@quinton-hoole - good point (although I'm not sure if the effect of that is significant).
It seems there is --v=4 set for all components in scalability tests too. I will fix that later today.
