### ISSUE TITLE
Enable /proc/sys/kernel/panic_on_oops on nodes so that they don't go AWOL

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#12818]
#12809 refers

Currently our nodes don't panic on oops, which causes them to simply go AWOL.

$ cat /proc/sys/kernel/panic
10
$ cat /proc/sys/kernel/panic_on_oops 
0

On Monday, August 17, 2015 at 12:46:00 PM UTC-7, Eric Northup wrote:
> Although it won't catch _all_ guest kernel problems, two mechanisms
> get you most of the way there: 1) reboot on guest kernel panic, and
> oops=panic.
> 
> To test for the first, examine /proc/sys/kernel/panic and make sure
> it's not zero.  Also, enabling "oops=panic" might be worth doing (if
> that's not enabled, then the guest kernel "oops" encountered in the
> bug will not trigger anything, while it might have left a usermode
> thread unable to make forward progress).
> 
> See /proc/sys/kernel/panic_on_oops to enable the second (background:
> https://www.kernel.org/pub/linux/kernel/people/akpm/patches/2.5/2.5.66/2.5.66-mm3/broken-out/panic-on-oops.patch
> )
>

**Comment by roberthbailey** [comment]
@dchen1107 @zmerlynn

**Comment by dchen1107** [comment]
We can enable this and we believe this could resolve docker process stucking at zombie state. But there is a concern we observed before: after kernel crash, the node is not reboot, instead, GCE mark the CPU usage of such node as 100% forever. There is no node liveness detection. NodeController can only know Kubelet doesn't post NodeStatus for a while.

**Comment by bgrant0607** [comment]
If this is for 1.1, it needs to be P0 at this point. Should it be?

**Comment by dchen1107** [comment]
No, move it to 1.2

**Comment by derekwaynecarr** [comment]
Cc @derekwaynecarr for tracking

**Comment by brendandburns** [comment]
This was closed by #17202
