### ISSUE TITLE
Pod status not getting updated to Failed when pod is hard-evicted by Kubelet

### ISSUE THREAD

**Issue by asobti** [kubernetes/kubernetes#128103]
### What happened?

We have some pods that have a termination grace period of 3600sec. When such a pod gets evicted by the kubelet due to ephemeral storage shortage, the sequence of steps that we expect would happen is:

1. kubelet updates pod status to `Failed`
2. kubelet instructs container runtime to terminate containers without any grace period
3. a `DELETE` for that pod is issued to the apiserver

However, we don't see (1) happen. The pod status remains `Running` until step (3). This issue is further exacerbated by the fact that our version of kube is afflicted by #115819 wherein the termination grace-period of containers is respected, even though it isn't supposed to be.

As a result of this, what ends up happening is:
1. The pod's containers get `SIGTERM` (pod status remains `Running`)
2. Containers take 3600s to shutdown
3. Pod gets deleted from apiserver

This means there is a 1hr window where the pod is available as an 'endpoint' even though the containers have received SIGTERM (and are no longer accepting new connections) until the pod is deleted from the apiserver.

---

Events from the pod when it gets evicted:
```
 Warning  Evicted              3m24s                  kubelet               The node was low on resource: ephemeral-storage. Threshold quantity: 15405210648, available: 14857028Ki. Container appconfd was using 1224Ki, request is 0, has larger consumption of ephemeral-storage. Container istio-proxy was using 104Ki, request is 0, has larger consumption of ephemeral-storage. Container otel-agent was using 1200Ki, request is 0, has larger consumption of ephemeral-storage. Container vector-agent was using 16768Ki, request is 0, has larger consumption of ephemeral-storage. Container vault-refresh was using 1192Ki, request is 0, has larger consumption of ephemeral-storage. Container ses was using 3524Ki, request is 0, has larger consumption of ephemeral-storage. Container logrotate was using 1232Ki, request is 0, has larger consumption of ephemeral-storage. Container vaultpkid-refresh was using 1224Ki, request is 0, has larger consumption of ephemeral-storage.
  Warning  ExceededGracePeriod  3m14s (x9 over 9m18s)  kubelet               Container runtime did not kill the pod within specified grace period.
```

Pod's status is still 'Running':
```
$ k get pod ses-8576fbb5f-2z4jj -o json | jq .status.phase
"Running"
```

### What did you expect to happen?

In case of a kubelet-initiated eviction, pod status should be updated to `Failed` before containers are terminated.

### How can we reproduce it (as minimally and precisely as possible)?

1. Configure and run a pod with terminationGracePeriod of 3600s
2. Exec into another pod on the node and write a lot of data to an `emptyDir` until the node runs out of ephemeral storage and evicts pod from step (1)
3. Observe that the status of the pod still displays 'Running' and the pod's IP address is still listed in endpoints.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.15", GitCommit:"2c67202dc0bb96a7a837cbfb8d72e1f34dfc2808", GitTreeState:"clean", BuildDate:"2023-06-14T09:56:11Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.16-gke.1148000", GitCommit:"0bb6bb602fbe44baf68389e21f6e11859d08ee2d", GitTreeState:"clean", BuildDate:"2024-08-07T09:16:13Z", GoVersion:"go1.22.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>
```
$ cat /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
KERNEL_COMMIT_ID=2890fc8995cd68013377c0adcc1f6e985ee6e11e
GOOGLE_CRASH_ID=Lakitu
GOOGLE_METRICS_PRODUCT_ID=26
VERSION=105
VERSION_ID=105
BUILD_ID=17412.370.78
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Containerd v1.7.19
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kannon92** [comment]
1.27 is out of support (https://kubernetes.io/releases/).

Please see if you can reproduce on a supported version of kubernetes. (1.31, 1.30, 1.29). 1.28 will be out of support in a few weeks.

**Comment by kannon92** [comment]
/close

Please reopen if you are able to reproduce the problem on a supported version of Kubernetes.
