### ISSUE TITLE
Docker k8s cluster - private repo

### ISSUE THREAD

**Issue by stevesloka** [kubernetes/kubernetes#12814]
I'm using the docker setup which bootstraps a cluster by just running three docker commands. I'm looking  to pull images from my private internal repo. Is there a way to volume in my .dockercfg? 

Ideally I could just volume my files into /var/lib/kubelet but then I would need that on my host.

As a brute force, is there a public docker file for the images that are used that I could hack to add my creds to (locally)?

**Comment by bprashanth** [comment]
We have image pull secrets http://kubernetes.io/v1.0/docs/user-guide/production-pods.html#authenticating-with-a-private-image-registry
