### ISSUE TITLE
K1.31.0 - Very Unstable, Not Usable - kube-apiserver, kube-controller-manager, kube-proxy, kube-scheduler, etcd

### ISSUE THREAD

**Issue by msbrod** [kubernetes/kubernetes#128161]
### What happened?

Installed K1.31.0 several weeks ago and it worked great.  Then reinstalled on 10/13/2024 and found that all critical containers that come with the installation of kubeadm are very unstable, restart frequently, and eventually becomes unusable because the api-server stops listening on its port (6443).  Kube-proxy and kube-scheduler were both in CrashLoopBackOff.

OS:  Ubuntu 22.04.3 LTS
Kernel: 5.15.0-73-generic. 5.19.0-50-generic, and 6.2.0-32-generic
Containerd: 1.6.28

### What did you expect to happen?

Expected K1.31 to be stable and usable.

### How can we reproduce it (as minimally and precisely as possible)?

Install OS
Install Containerd
Install and Init Kubernetes as described on its website.

### Anything else we need to know?

It worked several weeks ago.  Noticed that coredns changed from 1.11.1 to 1.11.3 to 1.11.1, but still have instability.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
Baremetal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
~$  uname -a
Linux master-cmm12-1 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Containerd: 1.6.28
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pranav-pandey0804** [comment]
hi @msbrod, thanks for reporting this.
You mentioned that coredns changed between versions. It might be helpful to check if other dependencies or related configurations also updated in the background between your installations.

**Comment by pranav-pandey0804** [comment]
If possible, trying the previous working setup or testing different versions of core components might help isolate what changed. 
Sometimes even a small change in configuration files or system dependencies could lead to such instabilities.

**Comment by msbrod** [comment]
Thank you for your response, I really appreciate it.  I will collect more information and share it soon.

**Comment by msbrod** [comment]
Hi Pranav - The issue was fixed in the master node by adding "SystemdCgroup = true" to the config.toml, but in the worker nodes, removing that same configuration.  Please let me know if you have thoughts on why the config needs to be different on master vs worker nodes.  Otherwise, please go ahead and close this issue.  Thank you for your support.

**Comment by neolit123** [comment]
a better place to ask for support would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by neolit123** [comment]
> Hi Pranav - The issue was fixed in the master node by adding "SystemdCgroup = true" to the config.toml, but in the worker nodes, removing that same configuration. Note that if the master node's config.toml was missing "SystemdCgroup = true", then the Kubernetes containers were not stable. Please let me know if you have thoughts on why the config needs to be different on master vs worker nodes. Otherwise, please go ahead and close this issue. Thank you for your support.

all nodes should have this setting if you are using a kubelet that is managed by systedm.
that is already documented at k8s.io
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers
