### ISSUE TITLE
Control-plane unexpected node to "Not Ready"

### ISSUE THREAD

**Issue by WillDeploy1984** [kubernetes/kubernetes#128151]
### What happened?

Server running fine and seems unexpected lost of connection, I have attached the main logs of messages, and I will explain my analysis:
Sep 26 07:11:39 kubelet started to show "Error updating node status"

At 07:12:00 Lost connection with the pods running in qos1

Sep 26 07:12:03 kubelet shows that update node exceeds retry count.

The logs repeat again and again.

Sep 26 07:16:25 qos1 sssd_be[1077]: Backend is offline

And almost 6 hours later  qos server got reconnected and I can access the server.

One thing that catches my attention is  the following log:
Sep 26 13:11:10 qos1 Keepalived_vrrp[1512]: Interface cali9f8d8b57766 deleted

Nominally there is always a previous log indicating that the inteface cali****** has been added but for cali9f8d8b57766 interface it does not show.

Keepalived has been working perfectly and it does not show any restart or shutdown.

[logs.txt](https://github.com/user-attachments/files/17409957/logs.txt)

### What did you expect to happen?

It should not occur and or at least not lose connection with the server.  The node was not ready and recovered itself after almost 6 hours.

### How can we reproduce it (as minimally and precisely as possible)?

I have 9 nodes, 3 control-plane, master and 6 workers.
qos1 is one of the 3 control-plane, master

### Anything else we need to know?

This is the second time this occurs, first time the node was ready instantly but this time the node was "Not Ready" for almost 6 hours. 
The other 2 nodes [control-plane, master] have not shown this behavior. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
(machine is running in 2020 so ignore date)
```
</details>

### Cloud provider

<details>
Bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.5"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.5
$ uname -a
Linux qos2 5.4.17-2011.7.4.el8uek.x86_64 #2 SMP Fri Oct 2 14:39:04 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
(machine is running in 2020 so ignore date)
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Aaina26** [comment]
Hi! The k8s version that you are using is no longer supported. Could you please try recreating this issue with more recent versions(1.28+)?

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
