### ISSUE TITLE
/sig CLI The manifest for "cAdvisor Kubernetes Daemonset" cannot be found

### ISSUE THREAD

**Issue by lengcangche-gituhub** [kubernetes/kubernetes#128176]
### What happened?

When I tried to deploy cAdvisor, I used the following command as "https://github.com/google/cadvisor/tree/master/deploy/kubernetes":

```console
$ VERSION=v0.42.0
$ kustomize build "https://github.com/google/cadvisor/deploy/kubernetes/base?ref=${VERSION}" | kubectl apply -f -
Error: no 'git' program on path: exec: "git": executable file not found in $PATH
error: no objects passed to apply

``` 

Moreover, when I use chrome to open the link https://github.com/google/cadvisor/deploy/kubernetes/base?ref=v0.42.0 ,   the page not found (404)

### What did you expect to happen?

The cAdvisor should be deployed.

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/google/cadvisor/tree/master/deploy/kubernetes

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.14
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.14
```

</details>

### Cloud provider

<details>
No
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by adrianmoisey** [comment]
This works for me.
These is an error on your output:
> Error: no 'git' program on path: exec: "git": executable file not found in $PATH

Have you got git installed?

**Comment by lengcangche-gituhub** [comment]
> This works for me. These is an error on your output:
> 
> > Error: no 'git' program on path: exec: "git": executable file not found in $PATH
> 
> Have you got git installed?

Thank you very much. I haven't intalled git.

**Comment by pacoxu** [comment]
Probably this is not k/k issue. 

/kind support

**Comment by dims** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
