### ISSUE TITLE
Fix typo / missleading `kubeadm` output

### ISSUE THREAD

**Issue by amaddio** [kubernetes/kubernetes#128117]
When running `kubeadm init` the produced output is confusing:

> "You can now join any number of the control-plane node running the following command on each as root:"

I suggests that you can join the initializied control-plane node to somewhere. It is the other way round. You can create another control plane node and let it join. So the change would be:

> "You can now join any number of control-plane nodes running the following command on each as root:"

This must have been forgotten. As the exact phrase is seen in file `cmd/kubeadm/app/cmd/phases/init/showjoincommand.go` in line `59`. See PR.

**Comment by amaddio** [comment]
Unfortunately I am unable to use a slash command to update the label of this issue. I reckon the appropriate group for `kubeadm` would be [cluster-lifecycle](https://github.com/kubernetes/kubernetes/labels/sig%2Fcluster-lifecycle). `/sig cluster-lifecycle`

**Comment by saschagrunert** [comment]
> See PR.

Hey @amaddio, to which PR are you referring to?

**Comment by amaddio** [comment]
Sorry, my contribution request is still pending. Just finished it now: https://github.com/kubernetes-sigs/contributor-playground/pull/1480. I'll be able to contribute hopefully soon. Sorry for making the second step before the first

**Comment by amaddio** [comment]
PR is here: https://github.com/kubernetes/kubernetes/pull/128118
