### ISSUE TITLE
RBD volume on CoreOS require udev rules.

### ISSUE THREAD

**Issue by lleszczu** [kubernetes/kubernetes#12815]
RBD driver requires rbd device path in format ```/dev/rbd/<pool name>/<image name>``` while latest kernels places it under ```/dev/rbd{number}```. Driver should check dev name by executing "rbd showmapped" command.

**Comment by roberthbailey** [comment]
@thockin Do you know who the maintainer for the RBD volume code is?

**Comment by thockin** [comment]
@rootfs

**Comment by rootfs** [comment]
@lleszczu  `/dev/rbd{number}` is a symlink to `/dev/rbd/pool/image`, created by udev helper `ceph-rbdnamer(8)`

**Comment by rootfs** [comment]
@lleszczu what's your ceph package and kernel version?

**Comment by lleszczu** [comment]
@rootfs I am using CoreOS with kernel 4.1.5 and as a client docker image ceph/rbd which includes ceph 0.94.2.
After you mentioned udev, I have found https://github.com/ceph/ceph-docker/tree/master/examples/coreos/rbdmap that creates correct mapping. Thanks for help.
