### ISSUE TITLE
kube-apiserver receives a large number of requests created by kubelet every hour.

### ISSUE THREAD

**Issue by lojies** [kubernetes/kubernetes#128146]
### What happened?

In a cluster with over 1000 nodes and 100,000 pods, metrics and kube-apiserver logs reveal a large number of requests from kubelets creating tokens. Is this behavior reasonable, and has the impact on large-scale clusters been considered when reducing the token expiration time from 1 year to 3600 seconds?
···
I1016 18:47:01.093648      11 trace.go:243] Trace[8739521]: "Create" accept:application/vnd.kubernetes.protobuf,application/json,audit-id:231913e0-d53d-4450-aee3-8030b2808dcb,client:1234:55:33:10::e9,protocol:HTTP/2.0,resource:serviceaccounts,scope:resource,url:/api/v1/namespaces/kube-system/serviceaccounts/default/token,user-agent:kubelet/v1.28.3 (linux/amd64) kubernetes/a8a1abc,verb:POST (16-Oct-2024 18:46:59.279) (total time: 1814ms):
Trace[8739521]: ---"Write to database call succeeded" len:194 1814ms (18:47:01.093)
Trace[8739521]: [1.814509389s] [1.814509389s] END
···

### What did you expect to happen?

Reduce unnecessary requests to alleviate resource pressure on the cluster.

### How can we reproduce it (as minimally and precisely as possible)?

view kube-apiserver's log can find this

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.28.3
</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig node
for primary triage

**Comment by dims** [comment]
Are you talking about https://github.com/kubernetes/enhancements/tree/e1d4725d07a07c40da7ded6e1dd44c0f9aaeaeb9/keps/sig-auth/1205-bound-service-account-tokens which was GA in 1.22?

**Comment by xyz-li** [comment]
I think this is because the default value of `ExpirationSeconds` is one hour.

https://github.com/kubernetes/kubernetes/blob/06a15c5cf96131faaf44f93f1be228a013ae5c0d/pkg/apis/core/v1/defaults.go#L294-L299

**Comment by enj** [comment]
This is working as expected (and is used in large clusters across all providers).  A mutating admission webhook could be used to set a higher default expiration seconds, if desired.

**Comment by kannon92** [comment]
From what enj says, https://github.com/kubernetes/kubernetes/issues/128146#issuecomment-2420329966, I think we can close this.

/close
