### ISSUE TITLE
[Failing Test][sig-node][Serial] oom-score-adj should be -998 and best effort container's should be 1000

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#128251]
### Which jobs are failing?

- ci-cos-cgroupv1-containerd-node-e2e-serial
- https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cos-cgroupv2-containerd-node-e2e-serial/1846928355077656576
- ci-cgroupv2-containerd-node-e2e-serial-ec2

### Which tests are failing?

E2eNode Suite.[It] [sig-node] Container Manager Misc [Serial] Validate OOM score adjustments [NodeFeature:OOMScoreAdj] once the node is setup with test pods pod infra containers oom-score-adj should be -998 and best effort container's should be 1000

### Since when has it been failing?

10-16

### Testgrid link

 https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial, https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial, https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv2-containerd-node-e2e-serial-ec2

### Reason for failure (if possible)

```
{ failed [FAILED] Timed out after 120.000s.
Expected
    <*errors.errorString | 0xc0020ce560>: 
    expected pid 59090's oom_score_adj to be 1000; found -998
    {
        s: "expected pid 59090's oom_score_adj to be 1000; found -998",
    }
to be nil
In [It] at: k8s.io/kubernetes/test/e2e_node/container_manager_test.go:194 @ 10/17/24 04:30:16.775
}
```

### Relevant SIG(s)

/sig node

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv2-containerd-node-e2e-serial-ec2 shows that it started failing after https://github.com/kubernetes/kubernetes/pull/124227 was merged. 

- https://github.com/kubernetes/kubernetes/pull/128252 is a revert PR to test using the presubmit CI: pull-kubernetes-node-e2e-containerd-serial-ec2
and pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial

**Comment by esotsal** [comment]
Checking the shared failed run, i notice from [containerd.log](https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-cos-cgroupv2-containerd-node-e2e-serial/1846928355077656576/artifacts/n1-standard-2-cos-beta-117-18613-0-79-66cd92e1/containerd.log) pid:18341 is related 

>Oct 17 16:10:11 n1-standard-2-cos-beta-117-18613-0-79-66cd92e1 containerd[10226]: time="2024-10-17T16:10:11.616760589Z" level=info msg="received exit event container_id:\"8b0c46d33f98429f27094fc8d0cc5b2378c10f6fe6e391fe78f725c763b4921f\" id:\"8b0c46d33f98429f27094fc8d0cc5b2378c10f6fe6e391fe78f725c763b4921f\" pid:18341 exit_status:2 exited_at:{seconds:1729181411 nanos:616146447}"

with container agnhost executing the agnhost pause command

>Oct 17 16:08:11 n1-standard-2-cos-beta-117-18613-0-79-66cd92e1 containerd[10226]: time="2024-10-17T16:08:11.785722567Z" level=debug msg="Container \"8b0c46d33f98429f27094fc8d0cc5b2378c10f6fe6e391fe78f725c763b4921f\" spec: (*specs.Spec)(0xc000c18ab0){Version:(string)1.2.0 Process:(*specs.Process)(0xc0009d3e00){Terminal:(bool)false ConsoleSize:(*specs.Box)<nil> User:(specs.User){UID:(uint32)0 GID:(uint32)0 Umask:(*uint32)<nil> AdditionalGids:([]uint32)<nil> Username:(string)} Args:([]string)[/agnhost pause] CommandLine:(string) Env:([]strin

pause.go  seems it is  a direct syscall call according to [pause.go](https://github.com/kubernetes/kubernetes/blob/v1.31.1/test/images/agnhost/pause/pause.go#L37) . 

Want to test my theory if this is the root cause, so i started the container this time adding an args parameter to overcome getting the pause command. Ths CI of #128270 should test this theory.

**Comment by esotsal** [comment]
Some more datapoints

a) Containerd version is different latest successful uses  2.0.0-rc.5-47-g8b41368e7  while first failed 2.0.0-rc.5-61-g3a6e5fcb1

```
 diff containerd-installation_working.log containerd-installation_not_working.log  | grep version=2.0.0-rc.5
< Oct 16 15:08:32 n1-standard-2-cos-beta-117-18613-0-79-63fbf3e3 configure.sh[1069]: + version=2.0.0-rc.5-47-g8b41368e7
 > Oct 17 03:07:46 n1-standard-2-cos-beta-117-18613-0-79-4a486c93 configure.sh[1064]: + version=2.0.0-rc.5-61-g3a6e5fcb1
```

b) Checking kubelet.logs and containerd.logs seems K8s correctly through CRI asks for OOMAdjScr 1000 

![image](https://github.com/user-attachments/assets/c6714ab3-265b-4e6c-8448-5ff812cd6a04)

**Comment by pacoxu** [comment]
> Containerd version is different latest successful uses 2.0.0-rc.5-47-g8b41368e7 while first failed 2.0.0-rc.5-61-g3a6e5fcb1

Does this related to containerd 2.0?

**Comment by SergeyKanzhelev** [comment]
@samuelkarp are you aware of any recent changes in containerd 2.0?

**Comment by haircommander** [comment]
/triage accepted
/priority important-soon

it's possible this would be better as a containerd issue, but we can triage here for now

**Comment by samuelkarp** [comment]
https://github.com/containerd/containerd/compare/8b41368e7...3a6e5fcb1 this is the diff between the two versions (the commit sha is the last few characters of that generated version number, since these are both untagged builds).

**Comment by samuelkarp** [comment]
https://github.com/containerd/nri/pull/94 this commit is included in the diff and looks suspect (just based on it adjusting oom_score_adj).

**Comment by samuelkarp** [comment]
It looks like that commit did create a bug.  Here's a simple unit test demonstrating that the NRI library is incorrectly clearing existing OOMScoreAdj: https://github.com/containerd/nri/pull/116

**Comment by samuelkarp** [comment]
https://github.com/containerd/nri/issues/117 bug on NRI side to track

**Comment by samuelkarp** [comment]
https://github.com/containerd/containerd/pull/10884 this should now be fixed.

**Comment by pacoxu** [comment]
> [containerd/containerd#10884](https://github.com/containerd/containerd/pull/10884) this should now be fixed.

Great. Thanks @samuelkarp for the quick fix.

I will close this once the CI bumped the containerd.

**Comment by pacoxu** [comment]
IIUC the containerd will be built in https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/post-containerd-build.

I suppose the next run of https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv2-containerd-node-e2e-serial-ec2 will pass.

**Comment by pacoxu** [comment]
/close

https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv2-containerd-node-e2e-serial-ec2 is green now.
