### ISSUE TITLE
pull-kubernetes-e2e-kind-alpha-features

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#128227]
### Which jobs are failing?

https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/pr-logs/directory/pull-kubernetes-e2e-kind-alpha-features

### Which tests are failing?

Initialization phase.

### Since when has it been failing?

Jul 18th

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kind-alpha-features

### Reason for failure (if possible)

Something during starting kind fails.

### Relevant SIG(s)

/sig testing

**Comment by aojea** [comment]
it seems it was failing for a lot of time, the apiserver fails to start

 I'm puzzled why the periodic jobs does not fail 🤔 https://testgrid.k8s.io/sig-testing-kind#kind-master-alpha

**Comment by sanposhiho** [comment]
Thanks for this!

**Comment by aojea** [comment]
> Thanks for this!

thanks for reporting it, we should not have jobs that are permanent failing, or we fix them or we remove them, but leaving them in bad state causes confusion as this demonstrates
