### ISSUE TITLE
[FG:InPlacePodVerticalScaling] kubectl subcommand to resize pod resources

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/kubernetes#128278]
### What would you like to be added?

In #128266, we are introducing a new /resize subresource to request pod resource resizing. It would be good add support for this in kubectl. 

Few options:

1. A new `resize` subcommand: 

```
kubectl resize pods <pod-name> -c <container> --cpu <cpu> --memory <memory>
```

2. support for `resize` subresource in existing commands like `kubectl patch` and `kubectl edit`:

```
kubectl patch pod pause \
     -p '{"spec":{"containers":[{"name":"pause", "resources": {"requests": {"cpu": "200m"}}}]}}' \
    --subresource=resize
```

```
kubectl edit pod pause --subresource=resize
```

### Why is this needed?

This will help us manually test this feature as well as making it user friendly to use the new subresource.

**Comment by ardaguclu** [comment]
I don't think we'd need a new command for this. I think, minor changes would required to support this in kubectl apply, patch and edit.

**Comment by fanhaouu** [comment]
This explanation is so far-fetched. `kubectl` supports `exec` and `log`, so shouldn't it also support `resize`? It would make it easier for users to know how to resize pod resources. @ardaguclu
