### ISSUE TITLE
Support setting env vars in kubectl run

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#12828]
Something like `kubectl run --env="VAR=value" image`. Multiple --env flags should be accepted. Comma-separate values would get into an escape rathole, so I'd like to avoid that.

**Comment by bgrant0607** [comment]
@feihujiang Would you be interested in this issue?

**Comment by feihujiang** [comment]
@bgrant0607 Yes, I'd like to work on this.
