### ISSUE TITLE
Restructure SyncPod in kubelet

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#12826]
This is forked from #12540.

Proposal #12802 adds a pod lifecycle event generator. This requires pod workers in kubelet to know what events to expect in from the actions of `SyncPod`.

**Background**: [`SyncPod`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/runtime.go#L56) is the all-encompassing function defined in the container runtime interface to drive pod states to match the spec. `SyncPod` can perform millions of tasks, but all of them are hidden from kubelet. The reason behind the abstraction level is that the container runtimes (docker and rkt) are so different, and it is simpler to push all the implementation details down to individual runtimes. The downside, however, is that the code is hard to profile and reason about. 

Here are a few options that we can do.

**Option 1: Keep SyncPod as a black box**
Kubelet remains unaware of what's going on in `SyncPod`, but `SyncPod` would return a list of expected events to for pod worker to wait on.
Pros [+] and cons [-]:
- [+] No change to the container runtime interface or the main kubelet code. Individual runtimes can divert naturally.
- [-] Still need to restructure the code in docker/rkt packages.
- [-] `SyncPod` remains a monolithic function.

**Option 2: Define clear control flow and expectations in kubelet**
Break `SyncPod` into a couple of functions in the container runtime interface and define expected events for each of them. E.g.,

``` go
func SyncPods(....) {
    if !runtime.NetworkIsUp() {
        runtime.SetupNetwork()
        // Record the NetworkSetupCompleted event in expectations
    }
    if ! runtime.containerIsRunning() {
        runtime.StartContainer()
        // Record the ContainerStarted event in expectations
    }
    ...
}
```

Pros [+] and cons [-]:
- [+] The overall control flow is clear in kubelet.
- [-] It's hard to come up with a control flow that would work both for rkt and docker (e.g., docker would need to kill all containers if POD infra container needs to be restarted).

**Option 3: Define a generic execution plan at the runtime-level abstraction**

This is a compromise between option 1 and 2. Instead of forcing a control flow in kubelet, we'd ask each runtime what the execution plan is, and calls individual functions to complete this plan. E.g.,

``` go
type ExecutionPlan struct {
        TearDownNetwork   bool
        SetupNetwork      bool
        ContainersToKill  []string
        ContainersToStart []string
}

func GetExecutionPlan(api.Pod, kubecontainer.Pod) (*ExecutionPlan, error)
...
```

Based on the plan, we can augment the container Runtime interface to include new actions.

| Plan | Action | Expected events |
| --- | --- | --- |
| TearDownNetwork | SetupNetwork() | NetworkSetupCompleted |
| ContainersToKill | KillContainersInPod() | ContainerTerminated |
| ContainersToStart | CreateContainersInPod() | ContainerCreated |

Pros [+] and cons [-]:
- [+] The overall execution plan is clear in kubelet.
- [-] Need to come up with a generic ExecutionPlan understood by both runtimes.

---

I am leaning towards option 3 at the moment. The example I use is still more docker-centric, and needs to be worked on more for rkt.
@yifan-gu, what do you think about this?

**Comment by yifan-gu** [comment]
@yujuhong Thanks for the write up, it's very clean :) I like the 3rd option. I am looking into codes to see whether we can live with `ContainersToKill` and `ContainersToStart` with both runtime.

**Comment by yifan-gu** [comment]
Or we can just add `PodToKill`, `PodToStart` to make our life easier during reconstructing this.

**Comment by pmorie** [comment]
Very interesting.  One thing that is a little confusing is the first row in the plan/action/expected events tables.  Should the plan column be `SetupNetwork`, rather than `TeardownNetwork` ?

**Comment by yujuhong** [comment]
Still relevant, but we don't plan to work on this until rktnetes is removed (to reduce the scope and complexity of the refactoring).
