### ISSUE TITLE
node_lifecycle_controller accidentally removes newly tainted node taints when trying to remove some old taints

### ISSUE THREAD

**Issue by ImNotAFrog** [kubernetes/kubernetes#128304]
### What happened?

In my case, our program will try to taint a newly joined master node with our customed taint "node-role.kubernetes.io/master:NoSchedule"
But the taint wasn't there in one of our test case.
After looking into the logs, we found that kube-controller-manager was the most suspicious component.
Kube-controller-manager would update node taint when node gets ready, and it just happened when we tainted the node with kubectl
![image](https://github.com/user-attachments/assets/af5ff6a3-145c-45d4-a738-536430dc47bc)
![image](https://github.com/user-attachments/assets/b594dd1d-ed5d-4bde-821d-97a5af4b16d2)
Then we looked into the code, and found the problem in pkg/controller/controller_utils.go
https://github.com/kubernetes/kubernetes/blob/aa8f2878a588d80b0dc7960c0b82af1882011115/pkg/controller/controller_utils.go#L1115
When it tries to remove a taint, it uses Patch, which would lost the taints tainted by others during Get to Patch

### What did you expect to happen?

The taint should not be lost

### How can we reproduce it (as minimally and precisely as possible)?

Modify the code, make some Pause between Get and Patch (sleep() .etc) in function RemoveTaintOffNode
Stop the kubelet on one node, to create not-ready condition
Start the kubelet after not-ready stats has been updated
Use kubectl to create some new taint when the Pause is triggered
Check if the taint is still there after the node was ready

### Anything else we need to know?

We should probably use Update instead of Patch.
Besides, I don't like it to get node from apiserver cache at first try, because cache data does not guarantee data effectiveness, this could cause inconsistency of node's taints when taints were updated concurrently. This actually happened in another test we ran before, but I didn't keep the logs.

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.3", GitCommit:"d35bc1202891fc160168410ef38cb06782f9c1db", GitTreeState:"dirty", BuildDate:"2024-10-23T16:47:38Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.3", GitCommit:"d35bc1202891fc160168410ef38cb06782f9c1db", GitTreeState:"dirty", BuildDate:"2024-10-23T16:46:14Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by zhifei92** [comment]
> Modify the code, make some Pause between Get and Patch (sleep() .etc) in function RemoveTaintOffNode

Hi, have you reproduced the issue using this method yet?

**Comment by ImNotAFrog** [comment]
> > Modify the code, make some Pause between Get and Patch (sleep() .etc) in function RemoveTaintOffNode
> 
> Hi, have you reproduced the issue using this method yet?

Yes. 
![image](https://github.com/user-attachments/assets/803138b4-18c8-4d42-857b-3e531aa80798)

**Comment by carlory** [comment]
@ImNotAFrog  https://github.com/kubernetes/kubernetes/pull/113330 fixed this issue, please try to upgrade your cluster.

**Comment by ImNotAFrog** [comment]
> @ImNotAFrog #113330 fixed this issue, please try to upgrade your cluster.

Indeed, thank you.
