### ISSUE TITLE
kubectl drain --ignore-daemonsets=false error

### ISSUE THREAD

**Issue by gordonwwang** [kubernetes/kubernetes#128312]
### What happened?

On node4, which includes Pods managed by DaemonSet, when we execute `kubectl drain node4 --ignore-daemonsets=false` , an error occurs and 1 is returned.
At this point I looked at node4, and the Daemonset managed pods still seemed to exist.
I have two questions:
1. Are Daemonset Pods evicted and then pulled back up by Daemonset? Why would you exit 1? Is that a problem?
2. The Daemonset pod was never expelled, which means that --ignore-daemonsets=false did not take effect. That should be the problem, right?
![image](https://github.com/user-attachments/assets/da84ff71-606a-4b57-affd-00c5fd261a29)

### What did you expect to happen?

When --ignore-daemonsets are executed, there should be no exit 1

### How can we reproduce it (as minimally and precisely as possible)?

At a node with a Daemonset, execute
```
kubectl drain node_name --ignore-daemonsets=false
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"archive", BuildDate:"2024-03-25T09:56:57Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Tencent
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Linux kube-master 6.6.30-4.oc9.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May 13 19:20:48 CST 2024 x86_64 GNU/Linux

```

</details>

**Comment by Shuimo03** [comment]
I replicated your questions, first of all the first question Pods created by DaemonSet are not evicted in the pullback, you can check the events and logs
A return of 1 indicates that the kubectl drain command failed to execute because it was unable to remove the Pod managed by DaemonSet, resulting in a non-zero exit status code.

The second issue, --ignore-daemonsets=false didn't take effect, but wasn't the problem, it was that DaemonSet didn't allow it.

**Comment by Aaina26** [comment]
`kubectl drain node_name --ignore-daemonsets` is the command that ignores pods managed by Daemonsets. I get the following result when I use the above command:
`$ kubectl drain node01 --ignore-daemonsets
node/node01 already cordoned
Warning: ignoring DaemonSet-managed Pods: default/example-daemonset-gwdkc, kube-system/canal-5vpcx, kube-system/kube-proxy-txwtn
node/node01 drained`

So if the focus is to ignore daemon sets then the value should not be set to false.

**Comment by Aaina26** [comment]
Interestingly, on running `kubectl drain -h`, the description mentions the following:
`--ignore-daemonsets=false:
        Ignore DaemonSet-managed pods.`
So, maybe this is the bug? Maybe removing '=false' from the description might resolve this issue. If so I would like to work on this.

**Comment by Aaina26** [comment]
There is a [feature request](https://github.com/kubernetes/kubernetes/issues/75482) as well that asks for a flag to allow removal of daemonset managed pods with kubectl drain. That issue is still in progress which means that kubectl drain does not allow eviction of daemonset managed pods yet.

**Comment by Aaina26** [comment]
> ### What happened?
> On node4, which includes Pods managed by DaemonSet, when we execute `kubectl drain node4 --ignore-daemonsets=false` , an error occurs and 1 is returned. At this point I looked at node4, and the Daemonset managed pods still seemed to exist. I have two questions:
> 
> 1. Are Daemonset Pods evicted and then pulled back up by Daemonset? Why would you exit 1? Is that a problem?
> 2. The Daemonset pod was never expelled, which means that --ignore-daemonsets=false did not take effect. That should be the problem, right?
>    ![image](https://private-user-images.githubusercontent.com/53458548/379664198-da84ff71-606a-4b57-affd-00c5fd261a29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzg4NjgsIm5iZiI6MTczMTIzODU2OCwicGF0aCI6Ii81MzQ1ODU0OC8zNzk2NjQxOTgtZGE4NGZmNzEtNjA2YS00YjU3LWFmZmQtMDBjNWZkMjYxYTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDExMzYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhODFiMzk1YTAwNjNkMzdlNzU2ZjlkNjk4Mjc1NjFmNGVjNWNjMWY3MzZjMzVkYzZlMzVmMjk1OTE5YWI3YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MUcWzE9ZyR3SPqm8jL6qsPQws-9LhlI2W6UkEd38v-U)
> 
> ### What did you expect to happen?
> When --ignore-daemonsets are executed, there should be no exit 1
> 
> ### How can we reproduce it (as minimally and precisely as possible)?
> At a node with a Daemonset, execute
> 
> ```
> kubectl drain node_name --ignore-daemonsets=false
> ```
> 
> ### Anything else we need to know?
> _No response_
> 
> ### Kubernetes version
> ```
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"archive", BuildDate:"2024-03-25T09:56:57Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
> Kustomize Version: v5.0.1
> Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> ### Cloud provider
> ### OS version
> ```
> # On Linux:
> $ cat /etc/os-release
> # paste output here
> $ uname -a
> Linux kube-master 6.6.30-4.oc9.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May 13 19:20:48 CST 2024 x86_64 GNU/Linux
> ```
> 
> ### Install tools
> _No response_
> 
> ### Container runtime (CRI) and version (if applicable)
> _No response_
> 
> ### Related plugins (CNI, CSI, ...) and versions (if applicable)
> _No response_

Hi! You used the flag wrong. You are not supposed to set the --ignore-daemonsets flag '=false'. You just need to use '--ignore-daemonsets' like this. Kubectl drain -h describes the flags and their default value which in case of this flag is 'false'. Same is true for other flags as well..on running 'kubectl drain -h' you will see the flags that you can use and their default value. In this flag, if you don't use it, then its default value is taken as false. But if you specify it like this `kubectl drain --ignore-daemonsets` then the value of flag becomes true and daemonsets are ignored while draining the node. Therefore, the correct command to run here is `kubectl drain --ignore-daemonsets`. I hope you find this helpful

**Comment by Aaina26** [comment]
This not a bug.
/kind support

**Comment by Aaina26** [comment]
This is not a bug. I am not sure if I can remove the label. I am not a member yet

**Comment by gordonwwang** [comment]
Thank you @Aaina26  for your answer
