### ISSUE TITLE
client-go README.md is not mirrored from staging directory

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#128341]
The client-go README.md file does not exist in the staging directory: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go and we have PRs going directly to the repo to update it: https://github.com/kubernetes/client-go/blob/master/README.md. 

Is this a bug? Should the file exist in the staging repo instead? Other staging repos follow the convention like https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-apiserver/README.md and https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/README.md

/sig api-machinery

**Comment by sttts** [comment]
It was intentional at the time because we could easily update the README out of band in k/client-go directly. I guess the reason was that the client-go "release" happened after the kube release. Note that we didn't have automatic tagging for long time. Everything beyond cherry-picking commits was manual, including branch creation.

**Comment by sttts** [comment]
I think we can move the README into kube by deleting it first in a commit in client-go, and then adding it in k/k. And after that carefully watch the bot doing the right thing.

**Comment by Jefftree** [comment]
@sttts Opened https://github.com/kubernetes/client-go/pull/1394 and https://github.com/kubernetes/kubernetes/pull/129212.

The README also seems quite outdated as the last mentions are for v1.28

**Comment by sttts** [comment]
Who could watch the publishing bot @dims ? Not sure I know where it is running these days.

**Comment by dims** [comment]
@sttts @akhilerm or i can watch the bot @sttts - first sign of failure will show up in the issue anyway (with the log snippet)

**Comment by sttts** [comment]
Looks like we have a prow misconfiguration in client-go: `pull-client-go-build Expected — Waiting for status to be reported`.

**Comment by sttts** [comment]
Looks like it worked just fine: https://github.com/kubernetes/client-go/blob/master/README.md

**Comment by dims** [comment]
@sttts Nice! feels nice when things work as expected :)

**Comment by BenTheElder** [comment]
We could probably start automatically redirecting people to file PRs upstream and closing incoming PRs?

We could do this with the robot commenter (search for PRs in this repo periodically and file a comment explaining/closing ... slow), a blockade (see prow plugin docs, reacts based on paths touched in the push), or some other mechanism ...
