### ISSUE TITLE
Master-Node Doesn't server service exposed port

### ISSUE THREAD

**Issue by Garrybac** [kubernetes/kubernetes#128328]
### What happened?

Exposed port doesn't serve on Master-Node.

### What did you expect to happen?

Normally as we expose the port, we can both access the port via master-node and worker-node.

### How can we reproduce it (as minimally and precisely as possible)?

Seems like master nodes can't serve any services port.

### Anything else we need to know?

we already expose port in service as below:
Type: NodePort
External Traffic Policy: Cluster

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
```

</details>

### Cloud provider

<details>
No cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.4 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.4 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://issues.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
# paste output here
$ uname -a
Linux rhel50 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
INFO[2024-10-25 11:56:25.432610169+07:00] Starting CRI-O, version: 1.30.3, git: 8750e76e814ab80c40061f07402187d6b33ab72e(clean)
Version:        1.30.3
GitCommit:      8750e76e814ab80c40061f07402187d6b33ab72e
GitCommitDate:  2024-07-01T07:09:15Z
GitTreeState:   clean
BuildDate:      1970-01-01T00:00:00Z
GoVersion:      go1.22.0
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico v3.28.1
</details>

**Comment by zhifei92** [comment]
Do master nodes have kube-proxy?

**Comment by Garrybac** [comment]
Yes, It does.
I have only 1 master and 2 workers.

**Comment by aojea** [comment]
> Yes, It does. I have only 1 master and 2 workers.

then it has to be some problem in your environment, you need to add more data on the steps you are doing and what are the errors your are getting and how you are Validating ports are not exported 

/kind support

**Comment by Garrybac** [comment]
Hello,
There is no error I found in the log.
but when I curl to the port I got like this:
curl -Iv worker-node:31884 (connected)
curl -Iv master-node:31884 (timeout)
/Thanks

**Comment by aojea** [comment]
you need to check your firewalls rules, if kube-proxy is running in the master node that port will be forwarded

**Comment by neolit123** [comment]
a better place to ask for help would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

you can continue the discussion but this ticket will be closed.

/kind support
/close
