### ISSUE TITLE
fix changelog 1.31 documentation: kubeamd to kubeadm

### ISSUE THREAD

**Issue by obriensystems** [kubernetes/kubernetes#128460]
### What happened?

Going through the release notes - I noticed a veryminor code documentation error "kubeamd join"
Some context - Very nice work here.  I have been using Kubernetes since 1.7 in 2018

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.31.md#bug-or-regression

### What did you expect to happen?

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.31.md#bug-or-regression
-Kubeadm: when adding new control plane nodes with "kubeamd join", ensure that the etcd member addition is performed only if a given member URL does not already exist in the list of members
+Kubead,: when adding new control plane nodes with "kubeadm join", ensure that the etcd member addition is performed only if a given member URL does not already exist in the list of members

### How can we reproduce it (as minimally and precisely as possible)?

Yes, a one line docs change - not code changes

### Kubernetes version

<details>

```console
michaelobrien@mbp7 modules % kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4-eks-a737599
```

</details>

### Cloud provider

<details>
agnostic - but I am running EKS and K8S in Docker Desktop
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
@mbp7 modules % uname -a
Darwin mbp7.ht.home 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000 arm64

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by obriensystems** [comment]
patching - eta 10 min.... 128460-1.31-rel-notes-kubeadm

**Comment by obriensystems** [comment]
PR https://github.com/kubernetes/kubernetes/pull/128461/files

**Comment by neolit123** [comment]
there is already a PR for this repository
- https://github.com/kubernetes/kubernetes/pull/128293

**Comment by neolit123** [comment]
no need for a tracking issue in this repo. this should be merged:
- https://github.com/kubernetes/kubernetes/pull/128293

/close
