### ISSUE TITLE
kube-proxy: iptables implementation: allow a fallback flag to MASQUERADE pod source IPs

### ISSUE THREAD

**Issue by MikaelCluseau** [kubernetes/kubernetes#12843]
Related to #3760 .

As a safety mesure, it could be very useful to actually include a flag to proxy to MASQUERADE everything (acting very close to a userspace proxy). I think it's not very hard to do and a very good way to diagnose or even fallback in case of problem (I'm thinking about vxlan cases).

Something like "--snat-clients" or "--snat-pods" could be appropriate.

**Comment by BenTheElder** [comment]
@MikaelCluseau 
Looking at the current code:  https://github.com/kubernetes/kubernetes/blob/6f34be30a3ee4cf57bdadf262e4949e190163b6f/pkg/proxy/iptables/proxier.go#L497

It looks like we SNAT almost everything already now? Would adding a set-mark rule (behind the flag of course) at line 548 be sufficient? Deprecated Public IPs, Loadbalancer IPs, and NodePorts all appear to be marked for SNAT already (also endpoint loopback traffic).

**Comment by thockin** [comment]
I think that is the flag, yeah.

**Comment by BenTheElder** [comment]
Ok, I'll push out a PR for that in a moment. I should be able to take care
of that and the cleanup flag (PR out but needs some more work) today.
