### ISSUE TITLE
[Failing test][sig-cluster-lifecycle] failed to exec action kubeadm-upgrade

### ISSUE THREAD

**Issue by wendy-ha18** [kubernetes/kubernetes#128485]
### Which jobs are failing?

master-informing
- kubeadm-kinder-upgrade-1-31-latest

### Which tests are failing?

- kubeadm-kinder-upgrade-1-31-latest
- task-06-upgrade

### Since when has it been failing?

2024-10-31 16:52:10 +0000 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-1-31-latest

### Reason for failure (if possible)

failed to exec action kubeadm-upgrade
It may relate to this PR kubeadm: support dryrunning upgrade without a real cluster: https://github.com/kubernetes/kubernetes/pull/128457

### Relevant SIG(s)

/sig cluster-lifecycle
cc @kubernetes/release-team-release-signal

**Comment by neolit123** [comment]
fixed by
- https://github.com/kubernetes/kubernetes/pull/128487

next run should b green:
- https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-31-latest

**Comment by neolit123** [comment]
^ runs are green
/close
