### ISSUE TITLE
Pod in terminating state, Kubernetes EndpointSlice shows pod as running: false, but pod still getting traffic after 120 sec.

### ISSUE THREAD

**Issue by PrasannaJatla1** [kubernetes/kubernetes#128479]
### What happened?

When doing rolling deployment of a spring boot app, with 120sec pre stop. There is another active pod up and running.
EndpointSlice show this terminating pod as running:false and but in EndpointSlice ips we still see this terminating pod. But it has been removed from service endpoint immediately. Why is the pod in terminating state getting traffic when there is another active pod to receive traffic?

We have an alb ingress controller with instance type and Kubernetes service with node-port type.
We are continuously simulating traffic from a postman client during rolling deployment. And we are getting few 502 errors as the pod in terminating state getting traffic all the while when it is running pre-stop and after that as well.
here is snippet from deployment yaml
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 120
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
   terminationGracePeriodSeconds: 150

Below are details from kubectl
Endpoints:
  - Addresses:  10.0.153.241
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/demo-5ccf6cd66c-jpcxh
    NodeName:   ip-10-0-147-87.ec2.internal
    Zone:       us-east-1a
  - Addresses:  10.0.216.8
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/demo-5ccf6cd66c-tvk46
    NodeName:   ip-10-0-204-238.ec2.internal
    Zone:       us-east-1b
  - Addresses:  10.0.247.50
    Conditions:
      Ready:    false
    Hostname:   <unset>
    TargetRef:  Pod/demo-7c8d47c64f-n7vvp
    NodeName:   ip-10-0-219-33.ec2.internal
    Zone:       us-east-1b
Events:         <none>

% kubectl get endpointslice -n demo-jj         
NAME                ADDRESSTYPE   PORTS   ENDPOINTS                             AGE
demo-jj  IPv4          8080    10.0.153.241,10.0.216.8,10.0.247.50   220d

### What did you expect to happen?

Terminating pod should be removed from EndpointSlice when it is running pre-stop.

### How can we reproduce it (as minimally and precisely as possible)?

A spring boot app with above deployment yaml and alb ingress controller should reproduce this while rolling deployment. And simulate traffic through postman performance testing.

### Kubernetes version

<details>v1.29.8-eks-a737599</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
can you please format the code using markdown? 

Can you please paste the entire yaml for the deployment and the Service objects?

**Comment by bowei** [comment]
Do you know if Postman keeps the existing connection to the backend open during your test?

**Comment by PrasannaJatla1** [comment]
@bowei , yes it open a long connection, but it should not matter right, the connection is to ingress alb, from alb it routes to instance/node and kube proxy on that node is responsible to route it to corresponding pod ip, so why is kube proxy still routing to same pod even when endpoint slices got updated with status terminating as true(serving true, ready false). So, can some one through some light on how kube proxy is supposed to work in these situations.  Thanks in advance.

**Comment by aojea** [comment]
kube-proxy doesn't terminate existing connections, so there can be gracefully terminated, this has been a topic of long debate, see more discussion here https://github.com/kubernetes/kubernetes/issues/108523

**Comment by bowei** [comment]
(had this comment in draft): As Antonio said, the connections are kept alive to allow for any in-flight requests/response to have a change to complete from the client. New connections will be mapped to non-terminating Pods.

This is somewhat a "works as intended".

**Comment by adrianmoisey** [comment]
(thanks for handling this Bowei and Antonio, just going to remove my name from here since I didn't do anything)
/unassign

**Comment by thockin** [comment]
@PrasannaJatla1 The end-of-life of a pod which has long-running connections might not force-close those connections. 

You have a couple options.  You could set up some sort of max-lifetime at the ALB, so it doesn't keep backend-connections open indefinitely.  You could have the pod backend close the connection at some point (e.g. once you receive SIGTERM, you can still accept connections and serve them, but then close the connection).

There's not much that kube-proxy can realistically do here.

**Comment by PrasannaJatla1** [comment]
@thockin ,Thank you for the response. But, why long running connection from postman to alb matter here? in Instance type alb, alb routes to kube-proxy on any node, so how does the connection from postman to alb matter here?

**Comment by thockin** [comment]
ISTR that AWS ALB has different modes - routing to the nod-port or the pod IP directly.  Which is in use?

It must be the case that either ALB is keeping the connection open to a terminating pod, or else it is (wrongly) choosing to route to terminating pods.  If you route to a node-port (or cluster IP), kube-proxy will not use terminating endpoints (unless all others are dead).

**Comment by thockin** [comment]
Or perhaps it is routing to a node which only has that one pod and you are using `externalTrafficPolicy=Local`, and the ALB is not using a smart enough health-check?

**Comment by PrasannaJatla1** [comment]
Thanks again for quick reply. we are using node-port and externalTrafficPolicy = cluster , and there are 2 pods running and one terminating. In this case kube-proxy should route to running pods and not terminating pod. So, I don't understand why is terminating pod still getting traffic(We are running on EKS).

**Comment by adrianmoisey** [comment]
> That suggests that the traffic is coming across an already-established connection, which we don't want to hard-break (we don't have enough information to do that smartly).

Just to add to this, and keep me honest here Tim, this means that it's the responsibility of the serving Pod (the one terminating) to terminate the TCP connection, forcing the ALB and Postman to disconnect and then reconnect.

**Comment by thockin** [comment]
> Just to add to this, and keep me honest here Tim, this means that it's the responsibility of the serving Pod (the one terminating) to terminate the TCP connection, forcing the ALB and Postman to disconnect and then reconnect.

More or less - if you know that your upstreams tend to use long-lived connections, you can either configure them to bound that (e.g. 90s max) or you can enlighten your pod, such that once it receives SIGTERM it closes connections itself.

This is one of the biggest downsides of node-port based LBs -- they are lacking information about the actual backend, so they can't be smart enough to handle this case.
