### ISSUE TITLE
compatibility version: should allow using v1beta1 instead of older alpha version

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#128448]
### What would you like to be added?

https://github.com/kubernetes/kubernetes/blame/d001d5684e69b08e120dc328917925318c5f324c/staging/src/k8s.io/apiserver/pkg/server/storage/resource_encoding_config.go#L170-L179
skips over a beta version of an API group if that version gets introduced in the current release. An older alpha gets used instead.

Seen with https://github.com/kubernetes/kubernetes/pull/127511 (v1alpha3 -> v1beta1, with `scheme.SetVersionPriority(v1beta1.SchemeGroupVersion, v1alpha3.SchemeGroupVersion))` being ignored).

That code shouldn't override the explicit choice by the developer to prefer the beta encoding.

### Why is this needed?

In this particular case, it was a conscious choice to not support downgrades in favor of using v1beta1 as long-term storage version because:
- it enables removing v1alpha3
- future changes might make round-tripping to v1alpha3 harder

cc @jpbetz @logicalhan @siyuanfoundation

**Comment by jpbetz** [comment]
Opened https://github.com/pohly/kubernetes/pull/53 to fix

**Comment by neolit123** [comment]
please tag the `/sig ...` always.

/sig api-machinery
