### ISSUE TITLE
use kubectl delete static pod, pod can't recreate

### ISSUE THREAD

**Issue by lengrongfu** [kubernetes/kubernetes#128524]
### What happened?

I having a kube-scheduler static pod, configuration a kubescheduler-config.yaml to pod, i change this file in node, then exec `kubectl -n kube-system delete pods {scheduler-pod}`, then the pod is restarted. but i found kube-scheduler pod not using the latest configuration file.

### What did you expect to happen?

I hope exec  `kubectl -n kube-system delete pods {scheduler-pod}` after, can create a new static pod. use latest configuration file.

### How can we reproduce it (as minimally and precisely as possible)?

1. change `KubeSchedulerConfiguration` this config.
2. exec `kubectl -n kube-system delete pods {scheduler-pod}`.
3. found kube-scheduler pod use old config file.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by thisisharrsh** [comment]
It could help us to reproduce and understand the issue better

**Comment by xyz-li** [comment]
If you don't change the config of the static pod. kubelet won't restart the port. You can rename  the pod spec in  static pod dir or mv that pod to another dir and mv it back.

https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/
`If you try to use kubectl to delete the mirror Pod from the API server, the kubelet doesn't remove the static Pod:`

**Comment by xyz-li** [comment]
I think this work as design.

**Comment by kannon92** [comment]
Static pods are not part of the APIServer.
