### ISSUE TITLE
Unit tests support testing the passed path and its sub paths

### ISSUE THREAD

**Issue by zhifei92** [kubernetes/kubernetes#128536]
### What happened?

The current unit tests support running all test cases with `make test`; and `make check WHAT=./pkg/kubelet GOFLAGS=-v`, which will execute all test cases under the path `./pkg/kubelet` but not include those in its subdirectories. If you modify the code in multiple subdirectories of `pkg/kubelet`, and if you want to run unit tests, you need to explicitly import each subdirectory. This can be inconvenient and may lead to overlooking some test cases.

### What did you expect to happen?

Therefore, we need something like a switch to allow running all test cases from the desired directory and its subdirectories, for example: `make test WHAT="pkg/kubelet" GOFLAGS=-v KUBE_SUBDIR=y`. If `KUBE_SUBDIR` is set to y or Y, all tests within `pkg/kubelet` and its subdirectories will be executed; otherwise, only the test cases within `pkg/kubelet` will be run.

### How can we reproduce it (as minimally and precisely as possible)?

```
make check WHAT=./pkg/kubelet GOFLAGS=-v
```

### Kubernetes version

<details>

```console

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
Yes, and `./pkg/kubelet/...` is standard go behavior.

I don't think we should further deviate from `go test` input behaviors.

**Comment by BenTheElder** [comment]
https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns

> An import path is a pattern if it includes one or more "..." wildcards, each of which can match any string, including the empty string and strings containing slashes. Such a pattern expands to all package directories found in the GOPATH trees with names matching the patterns.

`make test`, is a wrapper around `go test` that ensures some additional things are setup correctly (like the right `.go-version`) but is ultimately ~go test compatible.
