### ISSUE TITLE
No older versions of k8s.io/cri-client available in CRI client repo

### ISSUE THREAD

**Issue by yuxiang-he** [kubernetes/kubernetes#128549]
### What happened?

The repo https://github.com/kubernetes/cri-client only has v0.31 versions available. Older versions are no longer accessible. E.g. https://github.com/kubernetes/cri-client/tree/v0.29.9 directs to a 404 page, but https://github.com/kubernetes/cri-client/tree/v0.31.0 shows the repo at tag v0.31.0

### What did you expect to happen?

Older versions should be available in the repo

### How can we reproduce it (as minimally and precisely as possible)?

Go to https://github.com/kubernetes/cri-client/tree/v0.29.9, and Github shows a 404 page.

No tags are available for v0.30 and older when searching for such tags in the repo

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
- 1.29 did not have `cri-client` ( https://github.com/kubernetes/kubernetes/tree/release-1.29/staging/src/k8s.io )
- 1.30 did not have `cri-client` ( https://github.com/kubernetes/kubernetes/tree/release-1.30/staging/src/k8s.io )
- 1.31 did have `client` ( https://github.com/kubernetes/kubernetes/tree/release-1.31/staging/src/k8s.io )

So you would only see the tags corresponding to 1.31 in the repo.

/close
