### ISSUE TITLE
The request times out in dozens of milliseconds.

### ISSUE THREAD

**Issue by Black-max12138** [kubernetes/kubernetes#128509]
### What happened?

I find that when the number of requests in the cluster is large, the return code 504 is returned for some requests, but the request takes only dozens of milliseconds. Why?
Some APIServer logs are as follows:

E1031 10:16:37.163017      11 writers.go:122] apiserver was unable to write a JSON response: http: Handler timeout
E1031 10:16:37.163055      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1031 10:16:37.166591      11 writers.go:135] apiserver was unable to write a fallback JSON response: http: Handler timeout
E1031 10:16:37.167083      11 timeout.go:142] post-timeout activity - time-elapsed: 4.003161ms, GET "/api/v1/nodes/work233" result: <nil>
I1031 10:16:37.173768      11 node_authorizer.go:205] "NODE DENY" err="node 'work115' cannot get configmap manager/cloudsop.beidou.hostlog, no relationship to this object was found in the node authorizer graph"
{"level":"warn","ts":"2024-10-31T10:16:37.179181Z","logger":"etcd-client","caller":"v3@v3.5.9/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc002799500/192.167.14.53:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
E1031 10:16:37.179302      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}: context canceled
E1031 10:16:37.179404      11 writers.go:122] apiserver was unable to write a JSON response: http: Handler timeout
E1031 10:16:37.184405      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1031 10:16:37.184759      11 writers.go:135] apiserver was unable to write a fallback JSON response: http: Handler timeout
I1031 10:16:37.189411      11 node_authorizer.go:205] "NODE DENY" err="node 'work115' cannot get configmap manager/caas, no relationship to this object was found in the node authorizer graph"
{"level":"warn","ts":"2024-10-31T10:16:37.191638Z","logger":"etcd-client","caller":"v3@v3.5.9/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc002799500/192.167.14.53:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
E1031 10:16:37.191736      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}: context canceled
E1031 10:16:37.191810      11 writers.go:122] apiserver was unable to write a JSON response: http: Handler timeout
E1031 10:16:37.192091      11 writers.go:122] apiserver was unable to write a JSON response: http: Handler timeout
E1031 10:16:37.192558      11 timeout.go:142] post-timeout activity - time-elapsed: 12.911662ms, GET "/api/v1/nodes/work233" result: <nil>
E1031 10:16:37.192682      11 writers.go:122] apiserver was unable to write a JSON response: http: Handler timeout
E1031 10:16:37.192798      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1031 10:16:37.193019      11 writers.go:122] apiserver was unable to write a JSON response: http: Handler timeout
E1031 10:16:37.193034      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
{"level":"warn","ts":"2024-10-31T10:16:37.195287Z","logger":"etcd-client","caller":"v3@v3.5.9/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0038c9c00/192.167.14.53:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
E1031 10:16:37.195425      11 writers.go:135] apiserver was unable to write a fallback JSON response: http: Handler timeout
E1031 10:16:37.195562      11 timeout.go:142] post-timeout activity - time-elapsed: 10.78091ms, PUT "/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/work233" result: <nil>
{"level":"warn","ts":"2024-10-31T10:16:37.198821Z","logger":"etcd-client","caller":"v3@v3.5.9/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0038c9c00/192.167.14.53:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
{"level":"warn","ts":"2024-10-31T10:16:37.202745Z","logger":"etcd-client","caller":"v3@v3.5.9/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0038c9c00/192.167.14.53:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
E1031 10:16:37.203114      11 finisher.go:175] FinishRequest: post-timeout activity - time-elapsed: 270.763µs, panicked: false, err: context canceled, panic-reason: <nil>
E1031 10:16:37.203153      11 finisher.go:175] FinishRequest: post-timeout activity - time-elapsed: 11.033912ms, panicked: false, err: context canceled, panic-reason: <nil>
E1031 10:16:37.203177      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1031 10:16:37.203218      11 writers.go:135] apiserver was unable to write a fallback JSON response: http: Handler timeout
E1031 10:16:37.203244      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1031 10:16:37.203260      11 finisher.go:175] FinishRequest: post-timeout activity - time-elapsed: 10.568058ms, panicked: false, err: context canceled, panic-reason: <nil>
E1031 10:16:37.210072      11 writers.go:122] apiserver was unable to write a JSON response: http: Handler timeout
E1031 10:16:37.210110      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1031 10:16:37.220130      11 writers.go:122] apiserver was unable to write a JSON response: http: Handler timeout
E1031 10:16:37.220167      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1031 10:16:37.220237      11 writers.go:135] apiserver was unable to write a fallback JSON response: http: Handler timeout
E1031 10:16:37.223611      11 writers.go:122] apiserver was unable to write a JSON response: http: Handler timeout
E1031 10:16:37.223646      11 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1031 10:16:37.228423      11 writers.go:135] apiserver was unable to write a fallback JSON response: http: Handler timeout
E1031 10:16:37.228617      11 timeout.go:142] post-timeout activity - time-elapsed: 53.474833ms, PUT "/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/work200" result: <nil>

The preceding log shows that the /apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/work233 request times out in 10 ms.

### What did you expect to happen?

The request is returned normally.

### How can we reproduce it (as minimally and precisely as possible)?

Check the APIServer audit logs when the number of requests is large.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.28
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

1.28 is out of support - https://endoflife.date/kubernetes

/kind support
/close
