### ISSUE TITLE
kubectl get cs only show one etcd

### ISSUE THREAD

**Issue by NatureLR** [kubernetes/kubernetes#128594]
### What happened?

```shell
kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS    MESSAGE   ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-0               Healthy   ok
```

### What did you expect to happen?

show three etcd

```shell
kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS    MESSAGE   ERROR
etcd-0               Healthy   ok
scheduler            Healthy   ok
controller-manager   Healthy   ok
etcd-2               Healthy   ok
etcd-1               Healthy   ok
```

### How can we reproduce it (as minimally and precisely as possible)?

k8s version 1.28.12 

### Kubernetes version

<details>

```console
Client Version: v1.28.15
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.15
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by NatureLR** [comment]
It should be the problem here  <https://github.com/kubernetes/kubernetes/pull/119039/files#diff-c545ad1ec99b614befff65e76f40dc215d2ce38f29cdf52c19590532cd721ea7L426>

**Comment by thisisharrsh** [comment]
`for ix, cfg := range s.storageFactory.Configs() :` This iteration would ensure each Config is mapped to a unique identifier. However, it assumes that each Config directly corresponds to a single etcd instance, which may not always capture all nodes.

**Comment by thisisharrsh** [comment]
`for _, cfg := range s.storageFactory.Configs()` and nested iteration on `ServerList .` By iterating over each ServerList within each Config, this approach would allow us to validate every etcd node explicitly.

**Comment by pacoxu** [comment]
Two workarounds:
- https://github.com/kubernetes/kubernetes/issues/92371#issuecomment-647710109 etcdctl
- https://github.com/kubernetes/kubernetes/issues/66810#issuecomment-409113836 apiserver `--etcd-servers`

**Comment by NatureLR** [comment]
> 两种解决方法：
> 
> * [componentstatuses 输出中仅可见 1 个 etcd - HA k8s 集群处于堆叠 etcd 模式 #92371 (评论)](https://github.com/kubernetes/kubernetes/issues/92371#issuecomment-647710109) etcdctl
> * [kubectl get componentstatus 显示额外的 etcd 实例 #66810 (评论)](https://github.com/kubernetes/kubernetes/issues/66810#issuecomment-409113836) apiserver`--etcd-servers`

So  not planning to fix this problem ?

**Comment by pacoxu** [comment]
> So not planning to fix this problem ?

IMO, yes, as the feature was deprecated in https://github.com/kubernetes/enhancements/issues/553 since v1.19.
- This is not removed as it is a GA API. https://github.com/kubernetes/kubernetes/pull/110886#issuecomment-1189802916.

**Comment by NatureLR** [comment]
> > So not planning to fix this problem ?
> 
> IMO, yes, as the feature was deprecated in [kubernetes/enhancements#553](https://github.com/kubernetes/enhancements/issues/553) and #93570 since v1.19.
> 
> * This is not removed as it is a GA API. [remove componentstatus support in v1.25 #110886 (comment)](https://github.com/kubernetes/kubernetes/pull/110886#issuecomment-1189802916).

ok i known tks
