### ISSUE TITLE
Disable compression of container logs after rotation

### ISSUE THREAD

**Issue by ashish-kumar-glean** [kubernetes/kubernetes#128587]
Environment:
Amazon EKS.
kubelet version: v1.30.4-eks-a737599
container runtime: containerd://1.7.22

Rotation of logs written to console from container is managed by kubelet. Kubelet compresses the rotated logs with gzip by default, and this is causing issues.

We use fluentbit as our logs processor, fluentbit is able to detect log rotation, but it can't detect and process when log file gets compressed, because of this, logs of a file are not being processed after rotation as the file gets compressed. This is causing loss of logs.

The same behavior is across different log aggregators like fluentbit. I searched around and couldn't find any way to disable log compression.

Other people posting for the same thing: https://serverfault.com/questions/1162412/how-to-prevent-kubernetes-log-rotation-from-compressing-files
https://www.reddit.com/r/kubernetes/comments/1e45njx/does_anyone_know_how_logrotate_is_configured/

Is there a way to disable compression? this is currently causing loss of logs for us.

**Comment by dims** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
