### ISSUE TITLE
kubelet /metrics/slis endpoint gives 404 not found 

### ISSUE THREAD

**Issue by leonzz** [kubernetes/kubernetes#128545]
### What happened?

A http get on kubelet `/metrics/slis` endpoint returns `404 page not found`

### What did you expect to happen?

the `/metrics/slis` endpoint on kubelet (both the secure port 10250 and insecure port 10255) should return health check metrics, e.g.

```
# curl -k --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key /etc/kubernetes/pki/apiserver-kubelet-client.key https://localhost:10250/metrics/slis
# HELP kubernetes_healthcheck [STABLE] This metric records the result of a single healthcheck.
# TYPE kubernetes_healthcheck gauge
kubernetes_healthcheck{name="log",type="healthz"} 1
kubernetes_healthcheck{name="ping",type="healthz"} 1
kubernetes_healthcheck{name="syncloop",type="healthz"} 1
# HELP kubernetes_healthchecks_total [STABLE] This metric records the results of all healthcheck.
# TYPE kubernetes_healthchecks_total counter
kubernetes_healthchecks_total{name="log",status="success",type="healthz"} 1
kubernetes_healthchecks_total{name="ping",status="success",type="healthz"} 1
kubernetes_healthchecks_total{name="syncloop",status="success",type="healthz"} 1
# HELP process_start_time_seconds [ALPHA] Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.73015473685e+09
```

### How can we reproduce it (as minimally and precisely as possible)?

have kubelet listen on both secure and insecure ports.

- restart kubelet and curl kubelet/metrics/slis on either one of the ports

Repeat multiple times and you'll see after some of the restarts, the endpoint returns 404 not found.

### Anything else we need to know?

Root Cause: 

- the http server handler registration is wrapped so only runs [once](https://github.com/kubernetes/component-base/blob/v0.30.0/metrics/prometheus/slis/routes.go#L49)
- the [ListenAndServeKubeletServer](https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/kubelet/server/server.go#L153) and [ListenAndServeKubeletReadOnlyServer](https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/kubelet/server/server.go#L190) both calls the `NewServer` and then [slis.SLIMetricsWithReset{}.Install(s.restfulCont)](https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/kubelet/server/server.go#L374) but only one of the 2 calls would run, resulting just one of the 2 ports handling the `/metrics/slis` endpoint
- depend on the start sequence of kubelet, there's a random-ness in which one would get the handler. So if you restart kubelet multiple times, you could see `/metrics/slis` available sometimes on https 10250 or sometimes on http 10255, but not both.

### Kubernetes version

All past versions where /metrics/slis endpoint is available on kubelet

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by richabanker** [comment]
/close 
since https://github.com/kubernetes/kubernetes/pull/128430 got merged
