### ISSUE TITLE
[Flaking Test] unit TestPrepareCandidate

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#128689]
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit/1854630377990131712

### Which tests are flaking?

- https://k8s.io/kubernetes/pkg/scheduler/framework: preemption TestPrepareCandidate

### Since when has it been flaking?

11-08

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

```
{Failed;Failed;  === RUN   TestPrepareCandidate/two_victims_without_condition,_one_passes_successfully_and_the_second_fails_(Async_preemption_enabled:_false)
    preemption_test.go:749: expected deleted pods [victim2], got []
--- FAIL: TestPrepareCandidate/two_victims_without_condition,_one_passes_successfully_and_the_second_fails_(Async_preemption_enabled:_false) (30.11s)
;=== RUN   TestPrepareCandidate
--- FAIL: TestPrepareCandidate (34.78s)
```

### Anything else we need to know?

recent change: https://github.com/kubernetes/kubernetes/pull/128170 
- /cc @sanposhiho 

### Relevant SIG(s)

/sig scheduling

**Comment by sanposhiho** [comment]
/assign 

Will take a look within today asap.
