### ISSUE TITLE
[Failing Test] master-blocking integration-master k8s.io/kubernetes/test/integration/scheduler.scheduler

### ISSUE THREAD

**Issue by tico88612** [kubernetes/kubernetes#128660]
### Which jobs are failing?

- master-blocking
  - integration-master

### Which tests are failing?

- k8s.io/kubernetes/test/integration/scheduler.scheduler

### Since when has it been failing?

11/06 23:49 PST

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

```
{Failed;  === RUN   TestSchedulerInformers
;}
```

```
{Failed;Failed;  panic: test timed out after 10m0s
	running tests:
		TestMultipleSchedulers (10s)

goroutine 494192 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2373 +0x385
created by time.goFunc
	/usr/local/go/src/time/sleep.go:215 +0x2d

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000616ea0, {0x3973fbc?, 0x0?}, 0x3b4e788)
	/usr/local/go/src/testing/testing.go:1751 +0x3ab
testing.runTests.func1(0xc000616ea0)
	/usr/local/go/src/testing/testing.go:2168 +0x37
testing.tRunner(0xc000616ea0, 0xc000bc1b60)
	/usr/local/go/src/testing/testing.go:1690 +0xf4
testing.runTests(0xc000a10be8, {0x612af80, 0xc, 0xc}, {0x38af520?, 0xc000bc1be0?, 0x6166720?})
	/usr/local/go/src/testing/testing.go:2166 +0x43d
testing.(*M).Run(0xc000bd0500)
	/usr/local/go/src/testing/testing.go:2034 +0x64a
k8s.io/kubernetes/test/integration/framework.EtcdMain(0xc000bc1f30)
	/home/prow/go/src/k8s.io/kubernetes/test/integration/framework/etcd.go:231 +0x392
k8s.io/kubernetes/test/integration/scheduler.TestMain(...)
	/home/prow/go/src/k8s.io/kubernetes/test/integration/scheduler/main_test.go:26
main.main()
	_testmain.go:69 +0xc8
```

### Anything else we need to know?

Probably related #128639

### Relevant SIG(s)

/sig api-machinery

**Comment by aojea** [comment]
![image](https://github.com/user-attachments/assets/f1d576b3-e0b8-4c9e-a497-4a0f5446a2a2)


> {Failed;  === RUN   TestSchedulerInformers


https://screenshot.googleplex.com/AauKshcJgZJY2Hw

**Comment by sanposhiho** [comment]
Taking a look, but https://github.com/kubernetes/kubernetes/pull/127946 is unrelated to `TestSchedulerInformers`. So, for now, I'm not yet sure if #127946 is related or not

**Comment by sanposhiho** [comment]
> {Failed;Failed;  panic: test timed out after 10m0s

Ah, Okay timeout...

**Comment by sanposhiho** [comment]
We've been adding a lot of tests in `/test/integration/scheduler/` lately.
Is this timeout per package timeout...? then it makes sense to start failing after adding a new test at https://github.com/kubernetes/kubernetes/pull/127946.

**Comment by aojea** [comment]
@sanposhiho yes, the test build a test binary per package, one solution is to split in different packages https://github.com/kubernetes/kubernetes/pull/109048/files

**Comment by sanposhiho** [comment]
Okay, thanks for a quick info. I'll quickly submit a PR to split tests.
