### ISSUE TITLE
[Failing-Test]: capz-windows-master is unable to start

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#128632]
### Which jobs are failing?

capz-windows-master

### Which tests are failing?

The entire job won't start and its difficult to understand why.

### Since when has it been failing?

As of 12:49 EST on November 6th.

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master

### Anything else we need to know?

This is in the sig-release informing dashboard so eyes will be on this failure.

### Relevant SIG(s)

/sig windows

**Comment by dims** [comment]
cc @jsturtevant @marosset

**Comment by jsturtevant** [comment]
There was an update to some scripts that help maintain the Azure subscription used for the tests.  This caused during some testing and we've reverted back.  The tests should begin to recover and I will continue to monitor.

**Comment by jsturtevant** [comment]
/close
We reverted the change and the tests are passing again https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-capz-master-windows/1854510851105492992
