### ISSUE TITLE
[Flaking Test] TestRequeueByBindFailure  in ci-kubernetes-integration-master 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#128688]
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1854663093817184256

### Which tests are flaking?

https://k8s.io/kubernetes/test/integration/scheduler queueing

### Since when has it been flaking?

11-08

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

```
<testsuite tests="93" failures="1" time="597.056000" name="k8s.io/kubernetes/test/integration/scheduler/queueing" timestamp="2024-11-07T23:27:30Z">
<properties>
<property name="go.version" value="go1.23.2 linux/amd64"/>
</properties>
<testcase classname="k8s.io/kubernetes/test/integration/scheduler" name="queueing" time="597.056000">
<failure message="Failed;" type="">=== RUN TestRequeueByBindFailure ;</failure>
</testcase>
</testsuite>
```

### Relevant SIG(s)

/sig scheduling

**Comment by haosdent** [comment]
Could not reproduce in my end
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
        <testsuite tests="1" failures="0" time="5.981000" name="k8s.io/kubernetes/test/integration/scheduler/queueing" timestamp="2024-11-11T22:16:21Z">
                <properties>
                        <property name="go.version" value="go1.23.2 linux/amd64"></property>
                </properties>
                <testcase classname="k8s.io/kubernetes/test/integration/scheduler" name="queueing" time="5.981000"></testcase>
        </testsuite>
</testsuites>
```

It is weird that this test took "597.056000" seconds in the job, compared to my local test is "5.981000" seconds.

**Comment by aojea** [comment]
> It is weird that this test took "597.056000" seconds in the job, compared to my local test is "5.981000" seconds.

how are you running the test? the integration test run all the package tests not only one, you can see in testgrid we need to split the test in this package since they are close to the 10 mins timeout

![image](https://github.com/user-attachments/assets/632a21a3-9765-449e-8588-d94629d42935)


/priority important-soon

@sanposhiho already split some test https://github.com/kubernetes/kubernetes/pull/128661 , can we do the same to avoid being so close to the limit?

/cc @alculquicondor

**Comment by alculquicondor** [comment]
cc @macsko

**Comment by haosdent** [comment]
@aojea 
> how are you running the test? the integration test run all the package tests not only one, you can see in testgrid we need to split the test in this package since they are close to the 10 mins timeout

I see, I run the specific test only so it looks faster.

I try to run via 
```
stress ./queueing.test -test.run TestRequeueByBindFailure
```
in the beginning, but keep encounter 
```
"EtcdMain goroutine check" err=<
        found unexpected goroutines:
        [Goroutine 355 in state select, with k8s.io/client-go/util/workqueue.(*delayingType[...]).waitingLoop on top of the stack:
        k8s.io/client-go/util/workqueue.(*delayingType[...]).waitingLoop(0x630ada0)
                /home/toc/SME/kubernetes/staging/src/k8s.io/client-go/util/workqueue/delaying_queue.go:311 +0x599
```
I guess it is an unrelated issue.

So I try to run via 

```
make test-integration WHAT=./test/integration/scheduler/queueing ETCD_LOGLEVEL=warn KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-run=TestRequeueByBindFailure"
```
