### ISSUE TITLE
pull-kubernetes-e2e-gce-cos-alpha-features: [sig-auth] [Feature:ClusterTrustBundle] [Feature:ClusterTrustBundleProjection] 

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#128656]
### Which jobs are failing?

pull-kubernetes-e2e-gce-cos-alpha-features

### Which tests are failing?

[sig-auth] [Feature:ClusterTrustBundle] [Feature:ClusterTrustBundleProjection] *

See https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/128170/pull-kubernetes-e2e-gce-cos-alpha-features/1854429746889232384

### Since when has it been failing?

The oldest failing is Nov 06 16:08:00, no successful afterwards.

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/128374/pull-kubernetes-e2e-gce-cos-alpha-features/1854057730449346560

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-cos-alpha-features

### Relevant SIG(s)

/sig

**Comment by sanposhiho** [comment]
/priority critical-urgent

Unable to test any alpha feature tests.

**Comment by sanposhiho** [comment]
cc @kubernetes/sig-auth-leads

**Comment by sanposhiho** [comment]
cc @stlaz 
https://github.com/kubernetes/kubernetes/pull/128581

**Comment by aojea** [comment]
/reopen

this seems to be more accurate
