### ISSUE TITLE
Exposing services with load balancers should allow either existing load balancer names, existing static IPs for load balancers or assignment of DNS records to load balancers

### ISSUE THREAD

**Issue by hach-que** [kubernetes/kubernetes#12867]
Currently when you an expose a service, there's no way to guarantee that the service is exposed on a certain IP address.  It looks as if the `publicIPs` setting is now ignored (it does nothing when specified), and when you use `--create-external-load-balancer=true` it will result in the creation of a new load balancer for the same named service if the cluster has been destroyed and recreated (e.g. when upgrading the VM size on Google Cloud Compute).

To ensure that automated deployments come back up with the same configuration, one (or more) of the following should be supported:

* Allowing the specification of an existing load balancer with an IP address already assigned (via `--attach-external-load-balancer=name`).
* Allow specifying the IP address the newly created load balancer should use (via `--external-load-balancer-ip-address`).  This option should also take into account reassigning the IP address if it's currently in use by another load balancer (since in this case we often want to replace it).
* Allow specifying a DNS record which is set up or configured in Google Cloud DNS to point to the Ephemeral IP address assigned to the load balancer.

**Comment by bprashanth** [comment]
I think this is more of an autosizing question, changing the instance size shouldn't required teardown of loadbalancers. if we allowed somone to specify loadbalancer ip in the spec, and left everything as it was (forwarding rules etc), getting kubeproxy to come back up and write the correct iptable rules for that ip should be straightforward, i think. The service controller would blindly take the spec ip and put it into the status.

**Comment by thockin** [comment]
Dup of #10323
