### ISSUE TITLE
Pod log error message "must select container name" should print valid container names

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#12863]
```
$ kubectl logs master-1-e6bup
error: POD master-1-e6bup has more than one container; please specify the container to print logs for
```

Should try harder to be useful to the user:

```
error: Pod master-1-e6bup has the following containers: api, controllers; please specify the container to print logs for with -c`
```

Also, `POD` capitalized is bad

**Comment by feihujiang** [comment]
@smarterclayton Is there anybody to work on this? If not, I'd like to volunteer myself.

**Comment by smarterclayton** [comment]
No one has worked on this yet, so please.

On Sun, Aug 30, 2015 at 10:13 PM, feihujiang <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> Is there anybody to
> work on this? If not, I'd like to volunteer myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/12863#issuecomment-136227332>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by chiefy** [comment]
:+1: n00b here and yeah, this would be super useful. Thanks.
