### ISSUE TITLE
[Failing Test] some containerd e2e depends on cri-containerd-2.0.0-linux-arm64.tar.gz

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#128605]
https://testgrid.k8s.io/sig-node-containerd#ci-kubernetes-node-arm64-e2e-containerd-ec2
- https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-arm64-e2e-containerd-ec2/1853916679520653312 
- https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-kubernetes-node-arm64-e2e-containerd-ec2/1853916679520653312/artifacts/i-082785d3277a505bb/containerd-installation.log 

> Nov 05 21:55:32 ip-172-31-64-16.ec2.internal configure.sh[4410]: + curl -f --ipv4 -Lo containerd.tar.gz --connect-timeout 20 --max-time 300 --retry 6 --retry-delay 10 https://github.com/containerd/containerd/releases/download/v2.0.0/cri-containerd-2.0.0-linux-arm64.tar.gz

See more in https://github.com/containerd/containerd/pull/9096

/sig node

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/128612
