### ISSUE TITLE
Kubernetes as Cloud Development Environment

### ISSUE THREAD

**Issue by enlgsh** [kubernetes/kubernetes#128760]
### What would you like to be added?

There are numerous technologies/projects under CNCF which developed around or exclusively for k8s. Eg: Kata containers, i see introducing kata into kubernetes changed the perspective of looking k8s as the tech that can only run production workloads. Gitpod flex(https://www.gitpod.io/blog/introducing-gitpod-flex) claims to be more relevant with CDE. 

Despite kata, kubevirt are being popular there is no document in k8s official claiming these are production grade. How do k8s community see cloud development verticals?

### Why is this needed?

Cloud Development Environment is a case where compute,workload type and other params cannot be predicted. Whereas in case of workloads such as appserver, serverless functions, jobs can be predicted and acted upon. So, there is a clear distinction between making CDE with k8s and managing appserver like workloads.

**Comment by aojea** [comment]
> Despite kata, kubevirt are being popular there is no document in k8s official claiming these are production grade. How do k8s community see cloud development verticals?. 

kata-containers https://github.com/kata-containers and kubevirt https://github.com/kubevirt are not kubernetes projects and belong to different organizations so I don't feel kubernetes as a project should do any claim about projects that are not under the kubernetes umbrella

Thanks

/close

**Comment by enlgsh** [comment]
@aojea : make sense but the OG question is unlike cri complaint runtimes, do k8s supports vm as runtimes?

**Comment by aojea** [comment]
> @aojea : make sense but the OG question is unlike cri complaint runtimes, do k8s supports vm as runtimes?

can you be a bit more specific on what is the exact statement you are looking for? 

Kubernetes defines an interface to talk with the runtimes https://kubernetes.io/docs/concepts/architecture/cri/, the examples you provide with kata and kubevirt are not quite the same and solve different problems.

kata, gvisor , ... https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/run-kata-with-k8s.md use the existing runtimes to run the kubernetes pods inside isolated environments, IIUIC they don't implement any behavior user facing, just the Pods run in more isolated environment

kubevirt IIRC run vms inside the pod, it implements an user facing behavior to use Kubernetes as a VM orchestrator,
