### ISSUE TITLE
[Failing test] UT TestWriteKubeletConfigFiles of cmd/kubeadm/app/phases/upgrade fails when run as root user

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#128762]
### Which jobs are failing?

k8s UT TestWriteKubeletConfigFiles at https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/postupgrade_test.go#L116 fails when run as root user.

### Which tests are failing?

TestWriteKubeletConfigFiles
```
[root@raji-x86-workspace1 kubernetes]#  make test WHAT=./cmd/kubeadm/app/phases/upgrade
+++ [1112 04:14:13] Set GOMAXPROCS automatically to 16
+++ [1112 04:14:13] Normalizing Go targets
+++ [1112 04:14:13] Running tests without code coverage and with -race
FAIL
FAIL    k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade        6.593s

=== Failed
=== FAIL: cmd/kubeadm/app/phases/upgrade TestWriteKubeletConfigFiles (0.00s)
W1112 04:14:21.309454  577063 postupgrade.go:112] Using temporary directory /etc/kubernetes/tmp/kubeadm-kubelet-config2862491829 for kubelet config. To override it set the environment variable KUBEADM_UPGRADE_DRYRUN_DIR
[dryrun] Would back up kubelet config file to /etc/kubernetes/tmp/kubeadm-kubelet-config2862491829/config.yaml
[kubelet-start] Writing kubelet configuration to file "/etc/kubernetes/tmp/kubeadm-upgrade-dryrun3857010355/config.yaml"
[dryrun] Would write file "/var/lib/kubelet/config.yaml" with content:
W1112 04:14:21.309747  577063 postupgrade.go:112] Using temporary directory /etc/kubernetes/tmp/kubeadm-kubelet-config278798797 for kubelet config. To override it set the environment variable KUBEADM_UPGRADE_DRYRUN_DIR
[dryrun] Would back up kubelet config file to /etc/kubernetes/tmp/kubeadm-kubelet-config278798797/config.yaml
    postupgrade_test.go:169: Expected error contains "no kubelet component config found.*no such file or directory", got error writing kubelet configuration to file: no kubelet component config found

DONE 114 tests, 1 failure in 14.460s
make: *** [Makefile:192: test] Error 1
[root@raji-x86-workspace1 kubernetes]#
```

### Since when has it been failing?

After the commit [https://github.com/kubernetes/kubernetes/pull/128031/commits/c47eaa88b1d96ae8e7d0ed08cc7a3781bf883ffb#diff-7bb5f1d4cb628a78[…]ed12478eb74d356f8809bf](https://github.com/kubernetes/kubernetes/pull/128031/commits/c47eaa88b1d96ae8e7d0ed08cc7a3781bf883ffb#diff-7bb5f1d4cb628a783d6b247da73a9ef0b93f793b62ed12478eb74d356f8809bf)
### Relevant SIG(s)

/sig testing

**Comment by aojea** [comment]
we should not run unit test as root by the way

**Comment by Rajalakshmi-Girish** [comment]
> TestWriteKubeletConfigFiles

The lines [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/postupgrade_test.go#L116:#L118) state:
```
// exit early if the user doesn't have root permission as the test needs to create /etc/kubernetes directory
// while the permission should be granted to the user.
```
this seemed, the test needs to be run as root user and would be skipped if run as non-root.

**Comment by BenTheElder** [comment]
We don't run unit tests as root by design because we had many tests depending on being root which doesn't work for local development and highly suggests an os level integration test rather than a unit test.

We should be overriding the base path so we can test in a tempdir and not try to write to the actual global path.

**Comment by pacoxu** [comment]
cc @neolit123 @SataQiu

**Comment by neolit123** [comment]
> cc @neolit123 @SataQiu

commented in the PR

**Comment by neolit123** [comment]
seems like IBM are running the k8s OSS UT internally as root, which they should stop doing. +1 to apply a fix for .32, but my comments on the PR suggest the preferred way.

**Comment by mkumatag** [comment]
> seems like IBM are running the k8s OSS UT internally as root, which they should stop doing. +1 to apply a fix for .32, but my comments on the PR suggest the preferred way.

Suggestion noted, we will look into avoiding running as the root user. That said, unit tests should behave the same way regardless of the user, in my opinion and hope PR will fix them.

**Comment by BenTheElder** [comment]
> seems like IBM are running the k8s OSS UT internally as root, which they should stop doing. 

sure, but the bug here is having a "unit test" that
A) only runs as root
B) doesn't work

Which we might not have caught as quickly without down streams running as root, but it's still a bug.
It took me a long time to get the upstream tests out of running as root because of bugs like this.

We should also be checking on PR review that new tests actually ran. We should not check in tests that do not run.

**Comment by neolit123** [comment]
> sure, but the bug here is having a "unit test" that

the unit test is certainly horrendous.

> We should also be checking on PR review that new tests actually ran. We should not check in tests that do not run.

another annoyance is the Windows unit test that we constantly break as they don't block merge.
i don't think SIG Windows created a job that runs quickly just to verify that.
cc @claudiubelu

**Comment by liggitt** [comment]
There are still a couple other preexisting unit tests in kubeadm that check privileged and skips if not, that should be cleaned up in a follow up:

https://grep.app/search?q=isPrivileged.Check

**Comment by neolit123** [comment]
> There are still a couple other preexisting unit tests in kubeadm that check privileged and skips if not, that should be cleaned up in a follow up:
> 
> https://grep.app/search?q=isPrivileged.Check

i logged at ticket:
- https://github.com/kubernetes/kubeadm/issues/3124

**Comment by srivastav-abhishek** [comment]
> > There are still a couple other preexisting unit tests in kubeadm that check privileged and skips if not, that should be cleaned up in a follow up:
> > https://grep.app/search?q=isPrivileged.Check
> 
> i logged a ticket:
> 
> * [don't skip unit tests in preflight/checks_test.go when not running as root kubeadm#3124](https://github.com/kubernetes/kubeadm/issues/3124)
> 
> @srivastav-abhishek take this one as well if you'd like. cc @mkumatag

Sure, I have assigned.
