### ISSUE TITLE
etcdserver: data corruption detected, unable to start etcd member

### ISSUE THREAD

**Issue by rockswe** [kubernetes/kubernetes#128735]
### What happened?

After a sudden power outage in our on-premises data center, our Kubernetes cluster failed to recover upon reboot. The etcd server could not start and logged the following error:
`etcdserver: data corruption detected, unable to start etcd member`
So the Kubernetes API server was unavailable, and the entire cluster became non-operational.

### What did you expect to happen?

I expected etcd to handle the abrupt shutdown gracefully and recover its data upon restart which allows the k8s control plane to become available again.

### How can we reproduce it (as minimally and precisely as possible)?

While this issue is rare and difficult to reproduce, the following steps simulate a similar scenario:
Set up a single-node Kubernetes cluster using kubeadm, deploy some resources to populate etcd, simulate an abrupt power loss, attempt to restart etcd, check the etcd logs for the data corruption error

### Kubernetes version

$ kubectl version --short
Client Version: v1.26.3
Server Version: v1.26.3

### Cloud provider

On-premises (bare-metal servers)

### OS version

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
ID=ubuntu
ID_LIKE=debian
VERSION_ID="22.04"

### Install tools

kubeadm version: v1.26.3 
etcd version: v3.5.6

### Container runtime (CRI) and version (if applicable)

Container Runtime: containerd 
containerd version: v1.6.15

### Related plugins (CNI, CSI, ...) and versions (if applicable)

CNI Plugin: Calico v3.25.0 
CSI Plugin: N/A

**Comment by dims** [comment]
please open an issue in https://github.com/etcd-io/etcd

/close
