### ISSUE TITLE
Error when run `build/run.sh make test-cmd` in containerized build environment

### ISSUE THREAD

**Issue by scaventz** [kubernetes/kubernetes#128717]
### What happened?

According to "https://github.com/kubernetes/kubernetes/tree/master/build", I use `build/run.sh make test-cmd` to run CLI tests, in my WSL2 environment, and get error: `got error: fork/exec /go/src/k8s.io/kubernetes/_output/local/go/bin/kubeadm: no such file or directory`.

Please see detailed logs in this attachment:
[error-log.txt](https://github.com/user-attachments/files/17686344/error-log.txt)

I've made some investigation, and it looks like the issue is caused by `KUBEADM_PATH ` exported in `hack/make-rules/test-cmd.sh`
https://github.com/kubernetes/kubernetes/blob/feb3f92bc42f006874f68c476c2d7a6f2ac5ab16/hack/make-rules/test-cmd.sh#L177

If I change this line with: 
`export KUBEADM_PATH="${KUBEADM_PATH:=$(kube::realpath "${KUBE_ROOT}")/_output/dockerized/go/bin/kubeadm}"`, the error is gone.

### What did you expect to happen?

Command `build/run.sh make test-cmd` runs without error: "no such file or directory"

### How can we reproduce it (as minimally and precisely as possible)?

With Docker Desktop, run command `build/run.sh make test-cmd` in WSL2 backend.

### Kubernetes version

branch master 33c64b380a1

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
BuildNumber  Caption                    OSArchitecture  Version
22000        Microsoft Windows 11 Home  64-bit          10.0.22000
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
seems to be kubeadm specific so also
/sig cluster-lifecycle

The problem with this is assuming either path, this should be straightforward to fix.
/triage accepted
/assign

**Comment by BenTheElder** [comment]
Please try with https://github.com/kubernetes/kubernetes/pull/128992

**Comment by scaventz** [comment]
> Please try with #128992

It works, the error is gone. But the task `make test-cmd` seems have some other problems, I'll take a closer look later. Thanks!
