### ISSUE TITLE
Additional access check for exec into a Pod using WebSocket

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#128743]
### What would you like to be added?

This is in support of https://github.com/kubernetes/enhancements/issues/3737

I'd like a way to require additional permissions (not just **get**) before someone can exec into a Pod.

/sig security

### Why is this needed?

Prompted by https://github.com/kubernetes/kubernetes/issues/78741 and https://raesene.github.io/blog/2024/11/11/When-Is-Read-Only-Not-Read-Only/

I think we could - in hindsight - have done a double access check for exec; for example, ensuring that the caller can **get** _and_ **invoke** it.

Maybe that's still feasible as an opt-in behavior. Not sure we'd be able to make it the default.

**Comment by sftim** [comment]
Also
/sig auth

**Comment by dims** [comment]
/sig cli

cc @liggitt @seans3

**Comment by liggitt** [comment]
The pods/exec resource is the key thing being granted access to… any request to that is invoking the exec (get or create)

if you want to add extra checks beyond authorization, admission on the CONNECT operation on the pods/exec resource can be registered to intercept all exec requests (whether made via a get or post request)
