### ISSUE TITLE
[Failing-Tests] DRA CRIO Features tests are failing

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#128716]
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-dynamic-resource-allocation#ci-node-e2e-crio-cgrpv1-dra-features and https://testgrid.k8s.io/sig-node-dynamic-resource-allocation#ci-node-e2e-crio-cgrpv2-dra-features

### Which tests are failing?

The entire suite is failing.

### Since when has it been failing?

November 8th

### Testgrid link

https://testgrid.k8s.io/sig-node-dynamic-resource-allocation#ci-node-e2e-crio-cgrpv2-dra-features

### Reason for failure (if possible)

E1110 17:45:56.162727    3470 run.go:72] "command failed" err="failed to validate kubelet configuration, error: invalid configuration: FeatureGate KubeletCrashLoopBackOffMax not enabled, CrashLoopBackOff.MaxContainerRestartPeriod must not be set, path: &TypeMeta{Kind:,APIVersion:,}"

### Relevant SIG(s)

/sig node
/wg device-management

**Comment by kannon92** [comment]
cc @bart0sh @pohly

**Comment by aojea** [comment]
> { failed [FAILED] DeleteOptions.meta.k8s.io "" is invalid: ignoreStoreReadErrorWithClusterBreakingPotential: Invalid value: true: is not allowed with DELETECOLLECTION, try again after removing the option

@pohly @bart0sh it looks like

https://github.com/kubernetes/kubernetes/blob/feb3f92bc42f006874f68c476c2d7a6f2ac5ab16/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go#L126-L128

https://github.com/kubernetes/kubernetes/pull/127513#discussion_r1835235231

I will say this is a dupe of https://github.com/kubernetes/kubernetes/issues/128704#issuecomment-2466004961

**Comment by pohly** [comment]
https://github.com/kubernetes/kubernetes/pull/127513 introduced this `ignoreStoreReadErrorWithClusterBreakingPotential` that the error is complaining about. Got merged yesterday in that range of commits.

Why is it complaining about `Invalid value: true: is not allowed with DELETECOLLECTION`? The new option is not set.

**Comment by aojea** [comment]
See my previous comment, there is a release blocker for that, I will aggregate this information into https://github.com/kubernetes/kubernetes/issues/128704#issuecomment-2466004961 and close this

**Comment by pohly** [comment]
I agree with Jordan's analysis, the `ptr.Deref` is wrong. Agreed, let's close this one here.

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/128704

**Comment by kannon92** [comment]
Sorry for the noise!

**Comment by dims** [comment]
> Sorry for the noise!

Not at all, checks and balances! we need more people looking at stuff

**Comment by aojea** [comment]
> Sorry for the noise!

Absolutely the opposite, thanks for reporting it, keep doing it

**Comment by kannon92** [comment]
/reopen

It seems that there are still failure for these tests. They of course now seem to be different.

**Comment by aojea** [comment]
checking this job https://testgrid.k8s.io/sig-node-dynamic-resource-allocation#ci-node-e2e-crio-cgrpv1-dra-features

it fails to start, kubelet logs 

https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-node-e2e-crio-cgrpv1-dra-features/1855316153497292800/artifacts/n1-standard-4-fedora-coreos-40-20241019-3-0-gcp-x86-64-42c9e336/kubelet.log


> I1109 18:54:52.769361    4728 flags.go:64] FLAG: --volume-stats-agg-period="1m0s"
I1109 18:54:52.769504    4728 feature_gate.go:387] feature gates: {map[DynamicResourceAllocation:true]}
E1109 18:54:52.769618    4728 run.go:72] "command failed" err="failed to validate kubelet configuration, error: invalid configuration: FeatureGate KubeletCrashLoopBackOffMax not enabled, CrashLoopBackOff.MaxContainerRestartPeriod must not be set, path: &TypeMeta{Kind:,APIVersion:,}"

@lauralorenz @thockin didn't you already fixed this one?

**Comment by aojea** [comment]
this jobs also set the faeture gate in the flags

> I1109 18:54:52.768942    4728 flags.go:64] FLAG: --feature-gates="DynamicResourceAllocation=true"


can this flag vs config being the different and why the error is triggered in this job and not in the others that enable the KubeletCrashLoopBackOffMax  feature gate?

**Comment by aojea** [comment]
I can not repro, I can't understand why the feature flags fail in these jobs, 

@kannon92 is the kubelet build from HEAD?

@kannon92 if you want to reuse the issue you should update the description, or is misleading

**Comment by kannon92** [comment]
Yea we dont do any special builds here.

I can try tomorrow

**Comment by kannon92** [comment]
I am able to reproduce.

```
export SSH_USER=core && make test-e2e-node INSTANCE_PREFIX=kehannon REMOTE=true IMAGE_CONFIG_FILE="/home/kehannon/Downloads/TestInfra/image-config-cgroupv2.yaml" CLEANUP=false RUNTIME=remote CONTAINER_RUNTIME_ENDPOINT="unix:///var/run/crio/crio.sock" FOCUS="DynamicResourceAllocation" SKIP="" TEST_ARGS='--feature-gates="DynamicResourceAllocation=true" --service-feature-gates="AllAlpha=true,AllBeta=true" --runtime-config=api/alpha=true,api/beta=true --kubelet-flags="--feature-gates=DynamicResourceAllocation=true --cgroup-driver=systemd --fail-swap-on=false --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
```

Kubelet fails to start due to the logs error mentioned.

```
E1110 17:45:56.162727    3470 run.go:72] "command failed" err="failed to validate kubelet configuration, error: invalid configuration: FeatureGate KubeletCrashLoopBackOffMax not enabled, CrashLoopBackOff.MaxContainerRestartPeriod must not be set, path: &TypeMeta{Kind:,APIVersion:,}"
```

**Comment by kannon92** [comment]
Looking at https://testgrid.k8s.io/sig-node-dynamic-resource-allocation#ci-node-e2e-cgrpv2-crio-dra versus these jobs, I think the reason this is failing is because we enable the other alpha/beta jobs via `--service-feature-gates`.

**Comment by kannon92** [comment]
Opened up https://github.com/kubernetes/test-infra/pull/33783 to fix this.

I was able to confirm that this works in my repo case.

**Comment by kannon92** [comment]
/priority important-soon

From my analysis this is not a release blocker or a bug in any feature. It would be good to get this for this release but it is not a release blocker.

**Comment by aojea** [comment]
What are 'service-feature-gates'?

**Comment by kannon92** [comment]
They are feature gates for services (apiserver, scheduler). We have separate flags for kubelet and all other services.
