### ISSUE TITLE
Allow proxied access to metric endpoints in Kubernetes API

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kubernetes#128781]
### What would you like to be added?

As a user I would like to have the kubernetes API provide endpoints that allow querying metrics from kube-scheduler, kube-controller-manager and etcd, so I don't have to open up the network access for these components wider than necessary.

Ideally these metrics get presented on an instance level (either /etcd/metrics and then the metrics themselves get enriched by an instance={"foo"} label or a single endpoint per instance: "/etcd/${instance}/metrics").

### Why is this needed?

Kube-Scheduler, Kube-Controller-Manager and ETCD run outside the cluster but on the same node or in the same network as the Kubernetes APIServer.

If your monitoring system runs within the cluster, it is difficult to monitor these systems from within the cluster as it requires you either to open up access to the external components (--bind-address=0.0.0.0) or apply some workaround that punches through the network boundaries. 

The Kubernetes APIServer by its nature can already connect to these components securely, therefore it can also scrape their metric endpoints, which would allow a simplified architecture.

There's a risk on losing visibility if the APIServer is unavailable but that's likely a risk to the whole cluster anyway and the scheduler and controller-manager are unable to function without a working apiserver.

The APIServer could also accidentally present stale data, this can be prevented by not caching it (e.g. the request is forwarded) or adding timestamp information to the metrics (similar to pushgateway's push_time_seconds).

**Comment by BenTheElder** [comment]
> The Kubernetes APIServer by its nature can already connect to these components securely, therefore it can also scrape their metric endpoints, which would allow a simplified architecture.

apiserver doesn't open connections to kcm or kube-scheduler ..?

This feature is also potentially a security issue if you didn't intend to allow external access to those metrics.

**Comment by liggitt** [comment]
If these run as pods the apiserver has access to, you can already access metrics via pod proxy endpoints. If they don't, I don't think it is a good idea for kube-apiserver to expose endpoints via proxy to those… there is no guarantee it has network visibility to those components.
