### ISSUE TITLE
add updateTimestamp in ConfigMap status

### ISSUE THREAD

**Issue by j4ckstraw** [kubernetes/kubernetes#128794]
### What would you like to be added?

add a new field `updateTimestamp` in ConfigMap status

### Why is this needed?

We can use this field to check whether the ConfigMap has been updated or not, and when it was updated.

**Comment by googs1025** [comment]
IIUC, k8s was originally designed without the concept of updatedTime. The controller does not care about the number of updates, but only cares whether the actual state meets the expected state. 🤔 
Maybe you can use `last-applied-configuration` or resourceVersion to solve this problem.

**Comment by zhifei92** [comment]
K8s does not require an `UpdateTimestamp` in its design (which also has certain side effects), while `CreationTimestamp`and `DeletionTimestamp` have practical value. For example, `DeletionTimestamp` is valuable during pod cleanup.

**Comment by zhifei92** [comment]
> We can use this field to check whether the ConfigMap has been updated or not, and when it was updated.

Audit logs can provide assistance.

**Comment by j4ckstraw** [comment]
1. `last-applied-configuration` does not help us. Helm is a widely used tool for managing Kubernetes applications. When update app with helm, `last-applied-configuration` is not patched. 
2. `resourceVersion`is not friendly to deployers
3. also not everyone can read the audit log

Is there any other way?

**Comment by googs1025** [comment]
I think one point: Why do we need to know whether it is updated? Is there a practical scenario that requires it? Because whether it is updated is not what we should care about. What we should care about is whether the actual state meets the expected state.

**Comment by j4ckstraw** [comment]
Thank you for your reply.  I understand the design philosophy of kubernetes. I will find other solutions.
