### ISSUE TITLE
cos-cgroupv1-containerd-node-e2e and cos-cgroupv2-containerd-node-e2e are unable to run ginkgo

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#128706]
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e and https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-features are getting an error when trying to run ginkgo.

### Which tests are failing?

The job is not running

### Since when has it been failing?

Today

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e

### Reason for failure (if possible)

timeout: failed to run command ‘./ginkgo’: Permission denied

### Relevant SIG(s)

/sig node testing

**Comment by kannon92** [comment]
cc @dims

**Comment by dims** [comment]
https://prow.k8s.io/?job=ci-cgroup-systemd-containerd-node-e2e we have a ✅ run
https://prow.k8s.io/?job=ci-cos-cgroupv2-containerd-node-e2e-features has a  ✅  run
https://prow.k8s.io/?job=ci-cos-cgroupv1-containerd-node-e2e is recovering 💛 
https://prow.k8s.io/?job=ci-containerd-e2e-ubuntu-gce is recovering 💛

**Comment by dims** [comment]
we have been stabilizing the runs for containerd tar.gz builds. Let's keep a watch on them for sure.

**Comment by dims** [comment]
/close

All of the 4 CI jobs are back on their feet.
