### ISSUE TITLE
[Failing test][sig-node] `ci-crio-cgroupv1-node-e2e-conformance`

### ISSUE THREAD

**Issue by wendy-haa** [kubernetes/kubernetes#128774]
### Which jobs are failing?

master-blocking:
- ci-crio-cgroupv1-node-e2e-conformance

### Which tests are failing?

kubetest.Node Tests

### Since when has it been failing?

2024-11-12 13:15:49 +0000 UTC
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv1-node-e2e-conformance/1856466494783754240

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-crio-cgroupv1-node-e2e-conformance&exclude-non-failed-tests=

### Reason for failure (if possible)

`{  error during go run /home/prow/go/src/k8s.io/kubernetes/test/e2e_node/runner/remote/run_remote.go --cleanup -vmodule=*=4 --ssh-env=gce --results-dir=/logs/artifacts --project=k8s-infra-e2e-boskos-090 --zone=us-west1-b --ssh-user=core --ssh-key=/workspace/.ssh/google_compute_engine --ginkgo-flags=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]" --test_args=--container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}" --test-timeout=3h0m0s --image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/crio/latest/image-config-cgroupv1.yaml: exit status 1}`

### Anything else we need to know?

NA

### Relevant SIG(s)

/sig node

**Comment by wendy-haa** [comment]
cc @kubernetes/release-team-release-signal

**Comment by pacoxu** [comment]
```
E1112 13:29:29.270871    9955 ssh.go:149] failed to run SSH command: out: ssh: connect to host 34.169.137.149 port 22: Connection timed out
```
/sig k8s-infra

**Comment by BenTheElder** [comment]
/remove-sig k8s-infra
creating disposable test VMs to e2e and run node tests is under sig node, k8s infra provides the underlying cloud resources

**Comment by BenTheElder** [comment]
See also: https://github.com/kubernetes/node-problem-detector/issues/970

**Comment by BenTheElder** [comment]
this job is using fedora/fedora-coreos-cloud/fedora-coreos-41-20241027-3-0-gcp-x86-64

**Comment by saschagrunert** [comment]
Closing the loop: https://kubernetes.slack.com/archives/C0BP8PW9G/p1731464990778519
```
Refusing to run under cgroup v1, SY… specified on kernel command line.
```

We switched from fedora-coreos-40-20241019-3-0-gcp-x86-64 to fedora-coreos-41-20241027-3-0-gcp-x86-64 which causes the issue.

**Comment by saschagrunert** [comment]
cc @kubernetes/sig-node-cri-o-test-maintainers

**Comment by kannon92** [comment]
SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1

41 now will not boot on a v1 node. Systemd has an override you can set at the kernel level.

**Comment by kannon92** [comment]
We are green!

PR merged to set the environment variable above.

/close
