### ISSUE TITLE
UDP conntrack not cleared when upgrading destination node 

### ISSUE THREAD

**Issue by adrianmoisey** [kubernetes/kubernetes#128830]
### What happened?

In GKE on Kubernetes `1.30.5-gke.1014001`, when having  UDP stream flow from a Pod on one node to a Pod on another node, if the destination node is upgraded (using GKE's normal node pool upgrade process), then sometimes (about 1 in every 3 tests I've performed), the conntrack entry is not cleared, and the UDP stream continues to be sent towards a now dead Pod.

Note: The Service iTP must be set to Cluster.

### What did you expect to happen?

That the conntrack entry is cleared.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a DaemonSet (on every node) that can receive UDP traffic on every
2. Configured a Service fronting this DaemonSet, with iTP of Cluster
3. Create a "client" pod that sends UDP (non-stop) to one of the destination Pods
4. Figure out which node is receiving the traffic, and perform a GKE upgrade on it
5. Watch traffic to see if it moves to a new node

Repeat steps 3-5 a few times until the problem happens.

### Anything else we need to know?

So far I can only reproduce on `1.30.5-gke.1014001`, and only when performing a node-pool upgrade (I don't understand this)

I had assumed that https://github.com/kubernetes/kubernetes/pull/127780 would fix it, which landed in 1.30.5, but it didn't seem to help.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.5-gke.1443001
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_CRASH_ID=Lakitu
KERNEL_COMMIT_ID=46944808c635edfd2bc86fd90d924a6def1e28ac
GOOGLE_METRICS_PRODUCT_ID=26
VERSION=113
VERSION_ID=113
BUILD_ID=18244.151.88
$ uname -a
Linux gke-k8s-gcp-qa1-nodes-frontend-us-cen-52fd96a8-ac7u 6.1.100+ #1 SMP PREEMPT_DYNAMIC Sun Sep 29 16:26:42 UTC 2024 x86_64 Intel(R) Xeon(R) CPU @ 2.80GHz GenuineIntel GNU/Linux
```

</details>

### Install tools

<details>
GKE's 
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

/sig network
cc @aojea

**Comment by adrianmoisey** [comment]
/sig network

(Apparently I can't edit that string into the description after I made the issue)

**Comment by aojea** [comment]
@adrianmoisey the backport is not in 1.30.5

```
 git tag --contains 3a295d45ad05e7ea54e70ad0bebd824c27456d46
v1.30.6
```
 
it is present in 1.30.6, that AFAIK today is only in the rapid channel https://cloud.google.com/kubernetes-engine/docs/release-notes#rapid-channel

/assign @aojea 

Please let me know

**Comment by adrianmoisey** [comment]
🤦 🤦 🤦 

When I read the changelog, I saw "Changes **since** 1.30.5" and my brain read it as "Changed **in** 1.30.5"
Sigh.

Ok, I'll close this for now, get us up to 1.30.6 and test again. If it's still present in 1.30.6, then I'll re-open it.
Sorry for wasting your time!

/close
