### ISSUE TITLE
First argument in kubernetes yaml is not correctly passed to bash script

### ISSUE THREAD

**Issue by renepupil** [kubernetes/kubernetes#128843]
### What happened?

First argument is not `$*` and `$?` of the executed bash command.

### What did you expect to happen?

For `$*` and `$?` to contain the first argument.

### How can we reproduce it (as minimally and precisely as possible)?

`kubectl apply -f job.yaml`:

```
# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: some.job
spec:
  ttlSecondsAfterFinished: 10000
  activeDeadlineSeconds: 86400
  backoffLimit: 1
  suspend: false
  template:
    spec:
      containers:
      - args: ["exit", "4"]
        command: 
        - bash
        - -cx
        - |
          echo "$*";
          echo "$0";
          echo "$1";
          echo "$@";
          ("$@"); 
          
          php_exit=$?; 
          if [ $php_exit != 0 ] && [ $php_exit != 2 ]; then
            exit $php_exit; # Practically ignore exit code 2.
          fi;
        image: docker.io/library/bash:5
        imagePullPolicy: Always
        name: bash
      restartPolicy: Never
```
Then check the logs of the created pod with `kubectl logs <pod>`:

```
+ echo 4
+ echo exit
+ echo 4
+ echo 4
4
exit
4
4
+ 4
exit: line 5: 4: command not found
+ php_exit=127
+ '[' 127 '!=' 0 ']'
+ '[' 127 '!=' 2 ']'
+ exit 127
```

### Anything else we need to know?

If a mounted script is used, it works accordingly:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: manipulate-exit-code-script-config
data:
    manipulate_exit_code.bash: |
      #!/bin/bash

      ("$@"); 
      php_exit=$?; 
      if [ $php_exit != 0 ] && [ $php_exit != 2 ]; then
        exit $php_exit; 
      fi;
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.15+rke2r1
```

</details>

### Cloud provider

<details>
Nine Internet Solutions AG
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
$ uname -a
Linux <pc-name> 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
From the docs:
>  If the -c option is present, then commands are read from
>               the first non-option argument command_string.  If there
>               are arguments after the command_string, the first argument
>               is assigned to $0 and any remaining arguments are assigned
>               to the positional parameters.  The assignment to $0 sets
>               the name of the shell, which is used in warning and error
>               messages.

https://www.man7.org/linux/man-pages/man1/bash.1.html

This is expected behavior in bash.
