### ISSUE TITLE
[Flaking Test] integration TestExternalJWTSigningAndAuth

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#128871]
### Which jobs are flaking?

https://storage.googleapis.com/k8s-triage/index.html?text=TestExternalJWTSigningAndAuth

- https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1858425874718658560

### Which tests are flaking?

  TestExternalJWTSigningAndAuth/change_of_supported_keys_picked_up_after_periodic_sync

### Since when has it been flaking?

11/09-10

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

```
-]poststarthook/priority-and-fairness-config-producer failed: not finished
  	Type:               "Dangling",
- 	Status:             "",
+ 	Status:             "False",
- 	LastTransitionTime: v1.Time{},
+ 	LastTransitionTime: v1.Time{Time: s"2024-11-18 09:28:53.78921237 +0000 UTC m=+5.328431288"},
- 	Reason:             "",
+ 	Reason:             "Found",
- 	Message:            "",
+ 	Message:            `This FlowSchema references the PriorityLevelConfiguration object named "system" and it exists`,
  }
  	Type:               "Dangling",
- 	Status:             "",
+ 	Status:             "False",
- 	LastTransitionTime: v1.Time{},
+ 	LastTransitionTime: v1.Time{Time: s"2024-11-18 09:28:53.796115633 +0000 UTC m=+5.335334551"},
- 	Reason:             "",
+ 	Reason:             "Found",
- 	Message:            "",
+ 	Message:            `This FlowSchema references the PriorityLevelConfiguration object named "node-high" and it exists`,
  }
```

### Relevant SIG(s)

/sig auth api-machinery

**Comment by liggitt** [comment]
cc @HarshalNeelkamal

I don't think the priority and fairness logs have anything to do with the failure, those show up in other test runs as well

**Comment by liggitt** [comment]
Flake is:
```
TestExternalJWTSigningAndAuth/change_of_supported_keys_picked_up_after_periodic_sync
    external_jwt_signer_test.go:230: Expected Authentication to succeed, got [invalid bearer token, square/go-jose: error in cryptographic primitive]
```

**Comment by liggitt** [comment]
fix in https://github.com/kubernetes/kubernetes/pull/128966
