### ISSUE TITLE
Cast Environment Variable Values As String

### ISSUE THREAD

**Issue by pnovotnak** [kubernetes/kubernetes#12889]
Occasionally I forget to wrap numeric environment variables in quotes and am briefly puzzled by the resulting error.

    error: could not read an encoded object from <controller>.yaml: unable to load "<controller>.yaml": json: cannot unmarshal number into Go value of type string
    error: no objects passed to create

**Comment by thockin** [comment]
Unfortunately this is done in the yaml/json decoder before we ever see it.

We could back env values with IntOrString instead of string, and then
handle the case of int by converting to string.  Better UX maybe, but very
"special case".

**Comment by pnovotnak** [comment]
Roger, seems like rolling our own parser for Kubernetes is a fool's errand. Closing ticket.
