### ISSUE TITLE
Migrate test infrastructure to new gcloud commands for MIGs

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#12881]
In the per-PR e2e tester, I see a bunch of lines like this:

```
WARNING: This preview command will be removed soon.
WARNING: These managed infrastructure preview commands have been migrated to "gcloud compute intance-groups managed" command group.
WARNING: See https://cloud.google.com/sdk/gcloud/reference/ for more details.
WARNING: Please use instead [gcloud compute instance-groups managed list].
```

which means that our per-PR builder is going to break abruptly in the next few weeks after a gcloud release. 

https://github.com/kubernetes/kubernetes/pull/11692 switched us over to the new API but it appears that there are some places where we are still using the preview commands.

**Comment by wojtek-t** [comment]
I will fix that.

**Comment by ixdy** [comment]
thanks!

**Comment by wojtek-t** [comment]
This is really misleading - it was caused by autoscaling:

    wojtekt@wojtekt-work:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ gcloud preview autoscaler --zone "us-central1-b" list
    WARNING: This preview command will be removed soon.
    WARNING: These managed infrastructure preview commands have been migrated to "gcloud compute intance-groups managed" command group.
    WARNING: See https://cloud.google.com/sdk/gcloud/reference/ for more details.
    WARNING: Please use instead [gcloud compute instance-groups managed list].
    NAME  DESCRIPTION  STATE  STATE_DETAILS
    Listed 0 items.

**Comment by wojtek-t** [comment]
cc @piosz 
I will fix that too
