### ISSUE TITLE
Set pod hostname to node name if --net=host

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#12893]
Forked from #4825 - there seems to be no disagreement.  If a pod uses host networking, the host's UTS should be used, too (or at least hostname and domainname fields in the docker API).

This seems like a pretty easy change that just about anyone could make (hint hint)

**Comment by bgrant0607** [comment]
cc @senorflor

**Comment by bgrant0607** [comment]
cc @ghodss

**Comment by bgrant0607** [comment]
cc @kubernetes/goog-node

**Comment by senorflor** [comment]
Awesome; on it at next spare moment.

**Comment by bgrant0607** [comment]
PR in progress already: #12980

**Comment by senorflor** [comment]
ack

**Comment by bgrant0607** [comment]
Closed by #12895
