### ISSUE TITLE
Backport #11804 to release branch

### ISSUE THREAD

**Issue by rubenv** [kubernetes/kubernetes#12899]
Would it be possible to cherry-pick #11804 into the release branch?

This was fixed 26 days ago but hasn't made its way into 1.0.3, which means that kube-proxy is broken out of the box on libvirt-coreos.

**Comment by roberthbailey** [comment]
@rubenv -- yes. Feel free to run `./hack/cherry_pick_pull.sh` to propose this (or future) cherry pick in PR form yourself as well.

**Comment by rubenv** [comment]
@roberthbailey giving it a try!

**Comment by roberthbailey** [comment]
Excellent. Feel free to assign the PR to me.

**Comment by rubenv** [comment]
@roberthbailey I don't think I can assign issues in this project. The PR is #12924, where the CLA bot is going slightly crazy.

Closing this one.
