### ISSUE TITLE
Ensure emulation-version works with feature gates that progress to false

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#128918]
I think emulation version assumes gate state in prior releases is `false`, and progresses to `true` in later releases.

Some gates reverse that (especially ones that are disabling deprecated old behavior).

I'm wondering if we need to explicitly indicate the effective state of that behavior in old releases, like this:

```
diff --git a/pkg/features/versioned_kube_features.go b/pkg/features/versioned_kube_features.go
index 9b8bbc6958f..f269076fcad 100644
--- a/pkg/features/versioned_kube_features.go
+++ b/pkg/features/versioned_kube_features.go
@@ -37,18 +37,22 @@ import (
 // Entries are alphabetized.
 var defaultVersionedKubernetesFeatureGates = map[featuregate.Feature]featuregate.VersionedSpecs{
 	AllowDNSOnlyNodeCSR: {
+		{Version: version.MustParse("1.0"), Default: true, PreRelease: featuregate.GA},
 		{Version: version.MustParse("1.31"), Default: false, PreRelease: featuregate.Deprecated},
 	},
 
 	AllowInsecureKubeletCertificateSigningRequests: {
+		{Version: version.MustParse("1.0"), Default: true, PreRelease: featuregate.GA},
 		{Version: version.MustParse("1.31"), Default: false, PreRelease: featuregate.Deprecated},
 	},
 
 	AllowOverwriteTerminationGracePeriodSeconds: {
+		{Version: version.MustParse("1.0"), Default: true, PreRelease: featuregate.GA},
 		{Version: version.MustParse("1.32"), Default: false, PreRelease: featuregate.Deprecated},
 	},
 
 	AllowServiceLBStatusOnNonLB: {
+		{Version: version.MustParse("1.0"), Default: true, PreRelease: featuregate.GA},
 		{Version: version.MustParse("1.29"), Default: false, PreRelease: featuregate.Deprecated},
 		{Version: version.MustParse("1.32"), Default: false, PreRelease: featuregate.Deprecated, LockToDefault: true}, // remove in 1.35
 	},
```

/sig api-machinery
/assign @jpbetz

**Comment by sftim** [comment]
IIRC we have seen feature gates go from off-by-default to on-by-default to _oops, we've done it again_ back to off-by-default and eventually end up stable (feature implicitly on). It's rare but we need to support this kind of transition.

/sig architecture
too

**Comment by jpbetz** [comment]
cc @siyuanfoundation @Jefftree @aaron-prindle

**Comment by liggitt** [comment]
> go from off-by-default to on-by-default to oops, we've done it again back to off-by-default

in all the cases like that I know of, we realized in a later release a beta feature regressed something badly enough the safest fix was to demote back to disabled by default, and we backported the disablement to the previous release branch. In that case, the enablement state at HEAD of master should represent the enablement state at HEAD of the minor release branches, including any post 1.x.0 enablement changes.

Emulation version only has minor granularity and should represent our present-day understanding of the latest state of the feature gate in each previous minor.

**Comment by Jefftree** [comment]
> Emulation version only has minor granularity and should represent our present-day understanding of the latest state of the feature gate in each previous minor.

Yeah this case seems fine since the state at HEAD is the most accurate representation and changes would be backported. 

> I think emulation version assumes gate state in prior releases is false, and progresses to true in later releases.

This is definitely a problem. When the emulated version is set to prior to a feature's introduction, we assume the feature is in "[pre-alpha](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/featuregate/feature_gate.go#L607-L611)" state which has the feature set to off. Instead having to remember to set that deprecated features should be in a on state before the deprecation, I think it will be better to special case deprecated features that if the emulation version is prior to the introduction of the deprecation AND has no other transitions, the feature default state is on. 

Obviously we could still have some cases like 

```
{Version: version.MustParse("1.32"), Default: false, PreRelease: featuregate.Alpha},
{Version: version.MustParse("1.33"), Default: true, PreRelease: featuregate.Beta},
{Version: version.MustParse("1.34"), Default: false, PreRelease: featuregate.Deprecated}
```

that should still respect that pre 1.32 should default to false. 

I don't see explicitly that all [deprecation transitions](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecation) from true -> false, but it seems to be implicit from the documentation and I don't see any exceptions currently. (though haven't looked at historical cases)

- alpha -> deprecated: technically could just immediately remove feature but pre-alpha behavior should remain false
- beta -> deprecated: Betas are not guaranteed on by default so either true -> false or false -> false. pre-beta behavior should still be false
- n/a -> deprecated introduced: goes from true to false

**Comment by liggitt** [comment]
> Instead having to remember to set that deprecated features should be in a on state before the deprecation, I think it will be better to special case deprecated features that if the emulation version is prior to the introduction of the deprecation AND has no other transitions, the feature default state is on.

We're inconsistent enough with polarity that I'm skeptical we can derive a default value prior to the gate introduction for gates that show up as deprecated.

**Comment by siyuanfoundation** [comment]
I agree with Jordan that the polarity of deprecated feature could be inconsistent, e.g.
```
        AllowDNSOnlyNodeCSR: {
 		{Version: version.MustParse("1.31"), Default: false, PreRelease: featuregate.Deprecated},
 	},
```
could be 
```
        DisallowDNSOnlyNodeCSR: {
 		{Version: version.MustParse("1.31"), Default: true, PreRelease: featuregate.Deprecated},
 	},
```
We need to treat it case by case for individual features. Explicitly indicating the effective state of that behavior in old releases seems to be a simple and good solution.

**Comment by liggitt** [comment]
we *can* (and probably should) write a unit test that catches gates that show up in new minors as deprecated from the start and guides people to create a "1.0" entry with a default that matches to pre-gated state

**Comment by jpbetz** [comment]
@siyuanfoundation what linters and/or unit tests do we already have that check for invalid versioned feature gates?   We should start listing out all the things that "should never happen" and start putting up protections to prevent those.

Some that are actively being discussed or have come up in the past:

- Should not be able to have two entries for the same version
- Should not be able to accidentally transition backward in stability levels? At least not without a good reason and without some sort of "ACK, this is what I really want to do".
-  Should not be able to deprecate a GA feature? (or at least, not accientally)
- ???

**Comment by liggitt** [comment]
I was playing around with linting and requiring initial state indication for deprecated gates with something like https://github.com/kubernetes/kubernetes/pull/128947

**Comment by sftim** [comment]
> We're inconsistent enough with polarity, and with whether the behavior change happens in the very first release a deprecation gate is introduced, that I'm skeptical we can reliably derive a correct default value prior to the gate introduction for gates that show up as deprecated.

SIG Docs came to the same conclusion when changing https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ to be rendered based on data.

**Comment by BenTheElder** [comment]
> I was playing around with linting and requiring initial state indication for deprecated gates with something like https://github.com/kubernetes/kubernetes/pull/128947

xref: https://github.com/kubernetes/kubernetes/issues/126893 (which was supposed to be tracked while allowing the current thing to merge late in the release as-is to prevent delaying the functionality, we would really like to avoid a proliferation of DIY static analysis framework(s) if possible)

**Comment by siyuanfoundation** [comment]
> @siyuanfoundation what linters and/or unit tests do we already have that check for invalid versioned feature gates? We should start listing out all the things that "should never happen" and start putting up protections to prevent those.
> 
> Some that are actively being discussed or have come up in the past:
> 
> * Should not be able to have two entries for the same version
> * Should not be able to accidentally transition backward in stability levels? At least not without a good reason and without some sort of "ACK, this is what I really want to do".
> * Should not be able to deprecate a GA feature? (or at least, not accientally)
> * ???

The linter is only for checking all new features adopt the new versioned format. Now that all the features have been migrated, we actually do not need the linter anymore. 
Long term, I think https://github.com/kubernetes/kubernetes/pull/128947 is a better approach than linter/unit test, because it is ensuring all features follow the same rules, not just limited to k/k.

**Comment by siyuanfoundation** [comment]
> > The linter is only for checking all new features adopt the new versioned format. Now that all the features have been migrated, we actually do not need the linter anymore.
> 
> I agree from a linting perspective, though #128241 is an alternative where we can generate a static fixture so that the feature gates in the kubernetes website can be automatically generated rather than having manual PRs that can have drift with the k/k feature set. Obviously its purpose isn't for linting, but the artifact would loosely follow `versioned_feature_list.yaml`

that's a good point, #128241 is useful for doc generation, but we should consider renaming it to reflect the repurpose.
