### ISSUE TITLE
node authorizer may have a delay in updating the graph

### ISSUE THREAD

**Issue by cccccc0226** [kubernetes/kubernetes#128910]
### What happened?

In k8s 1.29 cluster, I created 100 pods, each of which mounted 50 secrets. Then I deleted all the pods and created 100 pods again, repeating this process. I noticed that there were `warning` events about `failed to sync secret cache: timed out waiting for the condition`. After checking the apiserver logs, I found that the response code of corresponding request was 403 meaning unauthorized. Maybe the node authorizer may have a delay in updating the graph?

```
I1008 09:55:48.683488	13 httplog.go:131] "HTTP" verb="GET" URI="/api/v1/namespaces/default/secrets?fieldSelector=metadata.name%3Dsecret-kms-2&limit=500&resourceVersion=0" latency="1.324644ms" userAgent="kubelet/v1.29.2 (Linux/amd64) kubernetes/3ffab2c" audit-ID="d73de627-ff5b-3412-4416-97bada04664c" srcIP="192.168.121.154:44700" apf_pl="system" apf_fs="system-nodes" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf execution time="139.57us" resp=403
```

/sig auth

### What did you expect to happen?

no warning events appear

### How can we reproduce it (as minimally and precisely as possible)?

In k8s 1.29 cluster
1. created 100 pods, each of which mounted 50 secrets. 
2. deleted all the pods 

repeating above process

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SuQiucheng** [comment]
plugin/pkg/auth/authorizer/node/graph_populator.go

**Comment by liggitt** [comment]
Did you force delete the original pods (grace period of 0)? 

Were the forbidden messages seen between when the old pods were deleted and the new ones created, or after the new ones were created? If after, how long after they were scheduled to the node?

Did the forbidden error resolve itself, or block the pods from starting?

**Comment by SuQiucheng** [comment]
A large number of pods will be created, and the pods will be successfully created. However, during the creation, kubelet may fail to obtain secrets and configmaps. Then, kubelet backoff to obtain secrets and configmaps until they are successfully obtained. As a result, pod creation is slow

**Comment by SuQiucheng** [comment]
/reopen I recreated the problem.
`kube-apiserver.log:
[root kubernetes]# cat kube-apiserver.log | grep ecret-kms-18
I1224 15:09:04.107593       7 node_authorizer.go:209] "NODE DENY" err="node '192.168.83.220' cannot get unknown secret default/secret-kms-18"
I1224 15:09:04.108144       7 httplog.go:132] "HTTP" verb="WATCH" URI="/api/v1/namespaces/default/secrets?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dsecret-kms-18&resourceVersionMatch=NotOlderThan&sendInitialEvents=true&timeout=8m41s&timeoutSeconds=521&watch=true" latency="701.072µs" userAgent="kubelet/v1.28.15 (linux/amd64) kubernetes/65af8ed" audit-ID="c7473ad4-fd7f-48b7-9824-cefbffce01f1" srcIP="192.168.56.46:47960" apf_pl="system" apf_fs="system-nodes" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_init_latency="167.884µs" apf_execution_time="168.683µs" resp=403
I1224 15:09:05.453152       7 get.go:260] "Starting watch" path="/api/v1/namespaces/default/secrets" resourceVersion="" labels="" fields="metadata.name=secret-kms-18" timeout="5m1s"
I1224 15:09:24.492558       7 httplog.go:132] "HTTP" verb="WATCH" URI="/api/v1/namespaces/default/secrets?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dsecret-kms-18&resourceVersionMatch=NotOlderThan&sendInitialEvents=true&timeout=5m1s&timeoutSeconds=301&watch=true" latency="19.039802842s" userAgent="kubelet/v1.28.15 (linux/amd64) kubernetes/65af8ed" audit-ID="460d7bc3-c351-41b8-8ce9-4362c8d5199a" srcIP="192.168.56.46:47960" apf_pl="system" apf_fs="system-nodes" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_init_latency="1.238848ms" apf_execution_time="1.240065ms" resp=200
I1224 15:10:04.219626       7 get.go:260] "Starting watch" path="/api/v1/namespaces/default/secrets" resourceVersion="" labels="" fields="metadata.name=secret-kms-18" timeout="7m9s"
I1224 15:10:24.573924       7 httplog.go:132] "HTTP" verb="WATCH" URI="/api/v1/namespaces/default/secrets?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dsecret-kms-18&resourceVersionMatch=NotOlderThan&sendInitialEvents=true&timeout=7m9s&timeoutSeconds=429&watch=true" latency="20.35452207s" userAgent="kubelet/v1.28.15 (linux/amd64) kubernetes/65af8ed" audit-ID="3894b113-b431-479e-9e47-04a7cd67168c" srcIP="192.168.56.46:47960" apf_pl="system" apf_fs="system-nodes" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_init_latency="5.582409ms" apf_execution_time="5.582846ms" resp=200

`
I create a pod with 20 secret, and create 50 pods at a time. The pod and secret are deleted after each creation, and then the pod and secret are created again.
