### ISSUE TITLE
[discuss] Guides are not tight to release tags in the main repo

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#12907]
It's probably a good idea to move community integration guides into a separate repo, as they will never get in sync with release tags. It is actually technically almost impossible for community to test an integration with release binaries until a tag is published, and bothering to find magic ways of doing it would probably be a very unnecessary overhead as many of the guides have their own ways of deploying those binaries, whether is wrapping up cloud-config or CloudFormation or other platform-specific stuff, there will probably always be guides that do not adhere to common provisioning tools (which are currently salt+bash). Unless one wishes to have a policy around what tools a given guide is using, I can see no good reason of keeping guides in the main repository.

**Comment by errordeveloper** [comment]
Here is a good example of [user confusion](https://github.com/kubernetes/kubernetes/issues/12224#issuecomment-132198414).

**Comment by roberthbailey** [comment]
We have https://github.com/kubernetes/contrib so it would be reasonable to move them there or create a new top level repository. Do you have a preference?

@mikedanese

**Comment by mikedanese** [comment]
@bgrant0607 suggested that we breakout examples but not documentation. @erictune has a [TODO](https://github.com/kubernetes/kubernetes/blob/0f27307f82b015ee41327a3d15005bafe6252bae/hack/conformance-test.sh#L59-L64) which might also solve this issue if completed satisfactorily. Maybe we should prune the getting-started-guides that don't pass conformance tests and for the ones that do pass, clearly document the latest version to pass.

**Comment by errordeveloper** [comment]
> We have https://github.com/kubernetes/contrib so it would be reasonable to move them there or create a new top level repository. Do you have a preference?

I think it's a good idea.

> @bgrant0607 suggested that we breakout examples but not documentation.

Yes, that's what I meant.

>  @erictune has a TODO which might also solve this issue if completed satisfactorily

True, although seems a bit complicated and may be not so much necessary, however I am not familiar with conformance test suite...

**Comment by bgrant0607** [comment]
I agree we should do something to more clearly differentiate how actively supported each port/configuration is, though it's not clear what/how/when exactly.

A number of these guides also correspond to code in /cluster and/or /cloudprovider. I wouldn't want to move the (poorly named) "getting-started guide" and not the corresponding code.

**Comment by errordeveloper** [comment]
We have decided to move Weave/CoreOS/Azure guide into our own repo, as that's more convenient for a number of internal reasons. Also, CoreOS now has completely separate repository for their guides.

**Comment by errordeveloper** [comment]
I think the decision here will depend on the outcome of #5472 and other similar discussions.

**Comment by mikedanese** [comment]
@errordeveloper I think that makes sens. If it keeps the documentation/deploy scripts more up to date then we are all for it.

**Comment by errordeveloper** [comment]
I'm closing this because docs are in a different repo now.
