### ISSUE TITLE
Rename `UpdatePodTolerations` to `UpdatePodToleration` for code style consistency

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#129015]
### What would you like to be added?

Checked the scheduler `ActionTypes`, finding a non-consistent error about `UpdatePodTolerations` which we usually name it with singular, like `UpdatePodLabel`, `UpdateNodeTaint`.

However, this may lead to backward incompatibility, but the framework is not versioned, so I think it's ok, just need to add a `action required` for reminding.

cc @kubernetes/sig-scheduling-misc 

/kind cleanup
/remove-kind feature

### Why is this needed?

code style consistency.

**Comment by alculquicondor** [comment]
WDYT @sanposhiho?

**Comment by sanposhiho** [comment]
I agree with the renaming.

**Comment by sanposhiho** [comment]
and @zhifei92, feel free to tackle it.

**Comment by kerthcet** [comment]
> @kerthcet Hello, can I pick this up?

Just go ahead
