### ISSUE TITLE
1.32.0-rc.0 kubelet fails to mount volumes from windows GCEPD CSI driver

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#129080]
A downstream e2e test creating / attaching / mounting / writing to a GCE PD CSI volume is working on latest 1.31 releases and failing with a 1.32.0-rc.0 kubelet. Nothing else changed between the passing and failing run (same OS level, same versions of all other components including CSI driver,  etc).

Bisected to https://github.com/kubernetes/kubernetes/pull/127076, when kubelet started being built with go 1.23.

[Many things changed in go 1.23 around filesystem handing](https://tip.golang.org/doc/go1.23#ospkgos), and it doesn't look like kubelet volume code reacted to those.

Building the kubelet with `winsymlink=0` resolved the issue.

> On Windows, the mode bits reported by [Lstat](https://tip.golang.org/pkg/os#Lstat) and [Stat](https://tip.golang.org/pkg/os#Stat) for reparse points changed. Mount points no longer have [ModeSymlink](https://tip.golang.org/pkg/os#ModeSymlink) set, and reparse points that are not symlinks, Unix sockets, or dedup files now always have [ModeIrregular](https://tip.golang.org/pkg/os#ModeIrregular) set. This behavior is controlled by the winsymlink setting. For Go 1.23, it defaults to winsymlink=1. Previous versions default to winsymlink=0.

> On Windows, [EvalSymlinks](https://tip.golang.org/pkg/path/filepath#EvalSymlinks) no longer evaluates mount points, which was a source of many inconsistencies and bugs. This behavior is controlled by the winsymlink setting. For Go 1.23, it defaults to winsymlink=1. Previous versions default to winsymlink=0.

There are other stdlib windows fs behavior changes as well:

> On Windows, Readlink no longer tries to normalize volumes to drive letters, which was not always even possible. This behavior is controlled by the winreadlinkvolume setting. For Go 1.23, it defaults to winreadlinkvolume=1. Previous versions default to winreadlinkvolume=0.

> On Windows, EvalSymlinks no longer tries to normalize volumes to drive letters, which was not always even possible. This behavior is controlled by the winreadlinkvolume setting. For Go 1.23, it defaults to winreadlinkvolume=1. Previous versions default to winreadlinkvolume=0.

There is still code throughout kubelet like this (as well as many uses of stat / lstat), which may not be correct in go 1.23 on windows any more:

https://github.com/kubernetes/kubernetes/blob/04ac01e9b64ca7006be0f88f0937122226723028/pkg/util/filesystem/util_windows.go#L45-L91

https://github.com/kubernetes/kubernetes/blob/2b472fe4690c83a2b343995f88050b2a3e9ff0fa/staging/src/k8s.io/mount-utils/mount.go#L258-L270

We're still trying to narrow down what code in the Kubelet needs to be adjusted and was failing with default go 1.23 behavior, but wanted to raise this now for visibility to the 1.32 release.

/cc @msau42 @BenTheElder @aojea 
/cc @kubernetes/release-team 
/milestone v1.32

**Comment by liggitt** [comment]
my first thought would be to use the compatibility mode escape hatches for the go windows filesystem changes in go 1.23 we haven't reacted to yet, and set this in our go.mod to get back to go 1.22 behavior until sig-storage / sig-windows sweeps and adapts to the new behavior

```
godebug (
  default=go1.23
  winreadlinkvolume=0
  winsymlink=0
)
```

will test with those in place and see if that resolves the failures we're seeing

**Comment by dims** [comment]
and cc @marosset

**Comment by liggitt** [comment]
(as a follow up, a windows CI job for https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver might have caught this during the dev cycle)

**Comment by liggitt** [comment]
Building the kubelet with the `winsymlink=0` escape hatch was enough to fix the failures we saw downstream with kubelet failing on GCE PD CSI volumes on Windows.

That said, since we have not swept / updated code using Readlink / EvalSymlinks, I think we should also set winreadlinkvolume=0 for the 1.32 release and prioritise sweeping / fixing the kubelet code so we can stop setting both of those early in 1.33.

**Comment by mauriciopoppe** [comment]
> (as a follow up, a windows CI job for [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) might have caught this during the dev cycle)

Agreed, [there's a Windows CI job already in place that periodically runs the k/k master storage test suite against the PD CSI Driver](https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#ci-windows-2019-provider-gcp-compute-persistent-disk-csi-driver) but it was very painful to maintain because of changes in kubetest2, docker, among others. I see that the job's been failing for a long time already cc @mattcary.

- https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/880
- https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/982
- https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/892

**Comment by liggitt** [comment]
Ok, I think https://github.com/kubernetes/kubernetes/pull/129083 is ready for review. I'd like explicit acks from storage and windows leads on the resolution, and feedback from both on all the tests we should throw at that PR before merge.

Sweeping / recovering from this temporary behavior revert also needs to be prioritized early in 1.33 (as well as improving the windows test signal around this in general)

**Comment by marosset** [comment]
Yes for 1.32 lets revert to old behavior

**Comment by andyzhangx** [comment]
I just tried, golang 1.23.1 building with `godebug winreadlinkvolume=0` actually breaks the disk CSI driver on Windows node, golang 1.23.1 building with `godebug winreadlinkvolume=1`  keeps the original behavior (`os.ReadLink` should return `\\?\Volume{99cc61ac-6fec-11ef-bbb1-cd4785e79c6b}\` instead of a driver letter)

 - golang 1.23.1 building with `godebug winreadlinkvolume=0` 
```
C:\>dir C:\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\72bb2b07b6028371cea50fb631344dc9113f0846681814572edb765f698195da
 Volume in drive C is Windows
 Volume Serial Number is 663A-A45B

 Directory of C:\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\72bb2b07b6028371cea50fb631344dc9113f0846681814572edb765f698195da

09/11/2024  03:33 AM    <DIR>          .
12/05/2024  08:21 AM    <DIR>          ..
09/11/2024  03:33 AM    <JUNCTION>     globalmount [\??\Volume{99cc61ac-6fec-11ef-bbb1-cd4785e79c6b}\]
09/11/2024  03:34 AM               230 vol_data.json
               1 File(s)            230 bytes
               3 Dir(s)  80,665,006,080 bytes free

C:\>osreadlink.exe C:\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\72bb2b07b6028371cea50fb631344dc9113f0846681814572edb765f698195da\globalmount
Symlink target: F:\
```

 - golang 1.23.1 building with `godebug winreadlinkvolume=1`  keeps the original behavior (`os.ReadLink` should return `\\?\Volume{99cc61ac-6fec-11ef-bbb1-cd4785e79c6b}\`)
```
C:\>dir C:\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\72bb2b07b6028371cea50fb631344dc9113f0846681814572edb765f698195da\
 Volume in drive C is Windows
 Volume Serial Number is 663A-A45B

 Directory of C:\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\72bb2b07b6028371cea50fb631344dc9113f0846681814572edb765f698195da

09/11/2024  03:33 AM    <DIR>          .
12/05/2024  08:21 AM    <DIR>          ..
09/11/2024  03:33 AM    <JUNCTION>     globalmount [\??\Volume{99cc61ac-6fec-11ef-bbb1-cd4785e79c6b}\]
09/11/2024  03:34 AM               230 vol_data.json
               1 File(s)            230 bytes
               3 Dir(s)  80,661,196,800 bytes free

C:\>osreadlink.exe C:\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\72bb2b07b6028371cea50fb631344dc9113f0846681814572edb765f698195da\globalmount
Symlink target: \\?\Volume{99cc61ac-6fec-11ef-bbb1-cd4785e79c6b}\
```

**Comment by liggitt** [comment]
> I just tried, golang 1.23.1 building with godebug winreadlinkvolume=0 actually breaks the disk CSI driver on Windows node

What was the default behavior building that test with Go 1.22? Did you make changes when building with Go 1.23?

**Comment by andyzhangx** [comment]
@liggitt here are my steps: https://github.com/andyzhangx/demo/blob/master/debug/windows-debug.md
set as `godebug winreadlinkvolume=1` or remove this godebug symbol when building with golang 1.23.1 would resolve as `\\?\Volume{99cc61ac-6fec-11ef-bbb1-cd4785e79c6b}\`, and this is the correct and expected behavior in csi-proxy in golang 1.22.

Anyway, the default `winreadlinkvolume=1` in go1.23 is ok, we don't want to normalize volumes to drive letter in CSI driver since the volume may not always be linked to a drive letter, we should do the same as in k/k go.mod?

**Comment by liggitt** [comment]
Setting `winsymlink=0` resolved the issue we were seeing with the kubelet failing to mount successfully, so that was the only setting I _knew_ we needed for Kubernetes 1.23. The other was _intended_ to be preventative based on the Go 1.23 documentation.

The only use of the `winreadlinkvolume` switch in Go is in https://github.com/golang/go/blob/release-branch.go1.23/src/os/file_windows.go#L393-L395, and the only change from Go 1.22 → Go 1.23 is that by default, Go 1.23 short-circuits an attempt to resolve to a drive name.

`winreadlinkvolume=0` avoids the short-circuit and continues to the exact code present in Go 1.22:

```diff
+var winreadlinkvolume = godebug.New("winreadlinkvolume")
+
 // normaliseLinkPath converts absolute paths returned by
 // DeviceIoControl(h, FSCTL_GET_REPARSE_POINT, ...)
 // into paths acceptable by all Windows APIs.
@@ -360,7 +374,7 @@ func openSymlink(path string) (syscall.Handle, error) {
 //
 //     \??\C:\foo\bar into C:\foo\bar
 //     \??\UNC\foo\bar into \\foo\bar
-//     \??\Volume{abc}\ into C:\
+//     \??\Volume{abc}\ into \\?\Volume{abc}\
 func normaliseLinkPath(path string) (string, error) {
        if len(path) < 4 || path[:4] != `\??\` {
                // unexpected path, return it as is
@@ -375,7 +389,11 @@ func normaliseLinkPath(path string) (string, error) {
                return `\\` + s[4:], nil
        }
 
-       // handle paths, like \??\Volume{abc}\...
+       // \??\Volume{abc}\
+       if winreadlinkvolume.Value() != "0" {
+               return `\\?\` + path[4:], nil
+       }
+       winreadlinkvolume.IncNonDefault()
 
        h, err := openSymlink(path)
        if err != nil {
```

It *looks* like go 1.22 would have attempted to resolve to a drive letter by default. If the resolution fails, maybe it would still return a then it would still return `\\?\Volume{abc}\`?

Can you repeat your test, building your demo binary with go 1.22, and see what it does on the exact same machine with the exact same path?

**Comment by andyzhangx** [comment]
@liggitt you are right, in go1.22 `os.ReadLink` would return drive letter (as we tried in 4/9/2024), and later on when we move on to go 1.23, finally we could use `os.ReadLink` to replace powershell cmdlet `Get-Item` since the **default** behavior of `os.ReadLink` is what we want today. back to the original question in k/k, I think we could remove `godebug winreadlinkvolume=0` since we when want to parse a symlink on Windows node, we don't want to get a drive letter (usually it's wrong or not useful), return `\??\Volume{99cc61ac-6fec-11ef-bbb1-cd4785e79c6b}\` is what we want today in CSI driver. And GCEPD CSI driver fails due to not using `godebug winsymlink=0`, not related to `winreadlinkvolume`

```
I0409 13:38:51.650865   20420 volume.go:239] Readlink: c:\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\95d764218d14515cced832a6fa730d0cd34db9315b93e1fb89d8d9eaf7e7903a\globalmount
I0409 13:38:51.651481   20420 volume.go:239] Readlink: G:\
E0409 13:38:51.656304   20420 utils.go:110] GRPC error: GetVolumeIDFromMount(c:\var\lib\kubelet\pods\1e8d0def-30cd-4571-bb7d-2d366a186b0d\volumes\kubernetes.io~csi\pvc-62b91cd8-17c7-4bbe-a819-0461d396bc6c\mount) failed with error: readlink G:\: The file or directory is not a reparse point.

# this is what we want by using powershell command Get-Item
(Get-Item -Path C:\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\95d764218d14515cced832a6fa730d0cd34db9315b93e1fb89d8d9eaf7e7903a\globalmount).Target
Volume{5119f826-d03c-4d16-9fd1-5e9c1c29c939}\
```

**Comment by liggitt** [comment]
I can buy that the go 1.22 behavior of `winreadlinkvolume` ("_sometimes_ resolve to drive names") was inconsistent and unreliable, and the default go 1.23 behavior is more desirable.

All of the CSI / volume tests I know of passed with just the `winsymlink` option in place, so I don't have any specific concerns about dropping out the `winreadlinkvolume` option. I opened https://github.com/kubernetes/kubernetes/pull/129103 to drop that, leaving just the `winsymlink` compatibility switch in place, and will defer to storage / windows / release leads on whether to merge that.
