### ISSUE TITLE
CoreDNS service is running but IPs are not assigned

### ISSUE THREAD

**Issue by berkankadioglu** [kubernetes/kubernetes#129104]
/sig Network
### What happened?

I started a new cluster with 1 control plane node and 1 worker node. None of the default pods are getting IPs and it seems like there is no associated node with core dns pods. Some logs are as below:

$ kubectl get services -A
NAMESPACE     NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  9m21s
kube-system   kube-dns     ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   8m48s

$ kubectl get pods -o wide -A
NAMESPACE     NAME                                                       READY   STATUS    RESTARTS   AGE     IP       NODE                               NOMINATED NODE   READINESS GATES
kube-system   coredns-55cb58b774-h4vbk                                   0/1     Pending   0          3m59s   <none>   <none>                             <none>           <none>
kube-system   coredns-55cb58b774-zfxmn                                   0/1     Pending   0          3m59s   <none>   <none>                             <none>           <none>
kube-system   etcd-bsocialtoday-control-plane-s7n99                      1/1     Running   0          3m58s   <none>   bsocialtoday-control-plane-s7n99   <none>           <none>
kube-system   kube-apiserver-bsocialtoday-control-plane-s7n99            1/1     Running   0          3m58s   <none>   bsocialtoday-control-plane-s7n99   <none>           <none>
kube-system   kube-controller-manager-bsocialtoday-control-plane-s7n99   1/1     Running   0          3m58s   <none>   bsocialtoday-control-plane-s7n99   <none>           <none>
kube-system   kube-proxy-64tgt                                           1/1     Running   0          81s     <none>   bsocialtoday-md-0-dwwnv-8r6sj      <none>           <none>
kube-system   kube-proxy-q7l7s                                           1/1     Running   0          3m59s   <none>   bsocialtoday-control-plane-s7n99   <none>           <none>
kube-system   kube-scheduler-bsocialtoday-control-plane-s7n99            1/1     Running   0          3m58s   <none>   bsocialtoday-control-plane-s7n99   <none>           <none>

### What did you expect to happen?

I expected core dns to work fine with default instructions as followed in [here](https://syself.com/docs/caph/getting-started/quickstart/creating-a-workload-cluster).

### How can we reproduce it (as minimally and precisely as possible)?

Follow instructions [here](https://syself.com/docs/caph/getting-started/quickstart/creating-a-workload-cluster).

### Kubernetes version

<details>

```console
$ kubectl version
1.30.7
```

</details>

### Cloud provider

<details>
Hetzner
</details>

### OS version

Ubuntu 22.04

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by carlory** [comment]
@berkankadioglu do you install a network plugin, i.e. cilium? After cilium is installed, the coredns pod will become running.

**Comment by berkankadioglu** [comment]
@carlory I tried that too: [here](https://github.com/cilium/cilium/issues/36413) The issue persisted.

In that case, I believe cilium failed because pods etc did not receive an ip address because core dns is not working. Feels chicken and egg problem now. Not sure whats going on. I will debug core dns a bit more.
