### ISSUE TITLE
feature-gate not listing MutatingAdmissionPolicy in v1.32.0 Alpha1

### ISSUE THREAD

**Issue by sybadm** [kubernetes/kubernetes#129167]
### What happened?

kubeadm init --help

      --feature-gates string                 A set of key=value pairs that describe feature gates for various features. Options are:
                                             ControlPlaneKubeletLocalMode=true|false (ALPHA - default=false)
                                             EtcdLearnerMode=true|false (default=true)
                                             NodeLocalCRISocket=true|false (ALPHA - default=false)
                                             PublicKeysECDSA=true|false (DEPRECATED - default=false)
                                             RootlessControlPlane=true|false (ALPHA - default=false)
                                             WaitForAllControlPlaneComponents=true|false (ALPHA - default=false)

### What did you expect to happen?

Expect to see release 1.32.0 kubeadm to have enabled MutatingAdmissionPolicy feature-gate

### How can we reproduce it (as minimally and precisely as possible)?

kubeadm init --help

### Kubernetes version

<details>

```console
$ kubeadm version
# paste output here
```
# ./kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"32", GitVersion:"v1.32.0", GitCommit:"70d3cc986aa8221cd1dfb1121852688902d3bf53", GitTreeState:"clean", BuildDate:"2024-12-11T18:04:20Z", GoVersion:"go1.23.3", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sybadm** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.32.md

Introduced v1alpha1 API for mutating admission policies, enabling extensible # admission control via CEL expressions (KEP 3962: Mutating Admission Policies). # To use, enable the MutatingAdmissionPolicy feature gate and the admissionregistration.k8s.io/v1alpha1 # API via --runtime-config. (https://github.com/kubernetes/kubernetes/pull/127134, [@jpbetz](https://github.com/jpbetz)) [SIG API Machinery, Auth, Etcd and Testing]

**Comment by sybadm** [comment]
It is good to see that the feature itself is enabled.

`# kubectl explain mutatingadmissionpolicy --api-version=admissionregistration.k8s.io/v1alpha1
GROUP:      admissionregistration.k8s.io
KIND:       MutatingAdmissionPolicy
VERSION:    v1alpha1

DESCRIPTION:
    MutatingAdmissionPolicy describes the definition of an admission mutation
    policy that mutates the object coming into admission chain.
    
FIELDS:
  apiVersion	<string>
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values. More info:
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

  kind	<string>
    Kind is a string value representing the REST resource this object
    represents. Servers may infer this from the endpoint the client submits
    requests to. Cannot be updated. In CamelCase. More info:
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

  metadata	<ObjectMeta>
    Standard object metadata; More info:
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata.

  spec	<MutatingAdmissionPolicySpec>
    Specification of the desired behavior of the MutatingAdmissionPolicy.
`

**Comment by BenTheElder** [comment]
The values for `kubeadm init --feature-gate` are `kubeadm`'s **own** featuregates, while MutatingAdmissionPolicy is a kube-apiserver feature gate

**Comment by BenTheElder** [comment]
> It is good to see that the feature itself is enabled.

That's the API type, not the feature.

To set `--runtime-config` on kube-apiserver, see https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/ and set an apiserver extraArgs with `runtime-config`

**Comment by k8sautom8** [comment]
Thank you

**Comment by sftim** [comment]
I'm also thinking: /close not-planned?
