### ISSUE TITLE
`1.31` requires `privileged` to create a tun device, `1.30` only required `NET_ADMIN`

### ISSUE THREAD

**Issue by maggie44** [kubernetes/kubernetes#129157]
### What happened?

Upgraded to `1.31.3` (k3s) and all of my pods failed to start with `permission denied` errors. On start up of the pod, it creates a tun device at `/dev/net/tun`. On version 1.30, this worked fine with the `NET_ADMIN` permissions. Now I have updated to `1.31` and the pods won't start unless I add `privileged` permission to the pods. 

### What did you expect to happen?

v1.30 to be the same as v1.31 in terms of the permissions required to create tun devices.

### How can we reproduce it (as minimally and precisely as possible)?

I am creating the tun device in go using the following:

```
err = unix.Mknod("/dev/net/tun", unix.S_IFCHR|0600, int(unix.Mkdev(10, 200)))
if err != nil {
	return nil, fmt.Errorf("failed to create /dev/net/tun: %w", err)
}

fd, err = unix.Open("/dev/net/tun", os.O_RDWR, 0)
if err != nil {
	return nil, fmt.Errorf("created /dev/net/tun, but still failed: %w", err) // <-- failing here
}
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.4
Kustomize Version: v5.4.2
Server Version: v1.31.3+k3s1
```

</details>

### Cloud provider

<details>
Self hosted
</details>

**Comment by sftim** [comment]
/triage needs-information

Please fill in the issue details @maggie44 including OS, container runtime and network plugin.

**Comment by aojea** [comment]
/close

seems to be handled in the rancher project https://github.com/k3s-io/k3s/issues/11429#issuecomment-2535495783

feel free to reopen if it turns out is something in kube

**Comment by maggie44** [comment]
> /triage needs-information
> 
> Please fill in the issue details @maggie44 including OS, container runtime and network plugin.

containerd for k3s, and flannel. openSUSE microOS. Updated above.

**Comment by maggie44** [comment]
Traced back to runc, an intended break. Unfortunately means granting privileged now for creating tun devices, and during the transition containers will fail to start: https://github.com/tailscale/tailscale/pull/14262#issue-2713214388

**Comment by maggie44** [comment]
Cross linking here to the conversation on whether this change should be reverted, or whether upstream users like Kubernetes could add the ability to mount TUN devices without privileged: https://github.com/opencontainers/runc/pull/3468#issuecomment-2543171272
