### ISSUE TITLE
draplugin.PublishResources() only supports enumerating resources in a single slice

### ISSUE THREAD

**Issue by klueska** [kubernetes/kubernetes#129122]
### What happened?

I wanted to publish multiple resource slices within the same pool, but there was no easy way to do this with the recommended helper library.

### What did you expect to happen?

I expected the API to `draplugin.PublishResources()` to take a list of ResourceSlices, similar to the call to `resourceslice.Update()` that it wraps. 

### How can we reproduce it (as minimally and precisely as possible)?

Examine the code here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/dynamic-resource-allocation/kubeletplugin/draplugin.go#L427-L459
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/dynamic-resource-allocation/kubeletplugin/draplugin.go#L410

### Anything else we need to know?

/wg device-management

### Kubernetes version

`v1.32.0`

### Cloud provider

None

### OS version

Irrelevant

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pohly** [comment]
/triage accepted

This is an oversight. Ideally we should fix this quickly and backport to v1.32.1 for DRA drivers targeting 1.32.

**Comment by googs1025** [comment]
Should we modify the original API interface or add a new one? 🤔 
like this: 
`PublishMultipleResources(ctx context.Context, resourcesList []Resources) error`

**Comment by googs1025** [comment]
Got it, I'd like to try this.
/assign

**Comment by pohly** [comment]
/reopen

Backport still pending: https://github.com/kubernetes/kubernetes/pull/129328

**Comment by aojea** [comment]
> We can just change the existing Go API. It means that DRA drivers need to be updated when bumping their dependencies from v1.32.0 to v1.32.1, but that's okay: the k8s.io/dynamic-resource-allocation module has version v0.32.0 resp. v0.32.1, i.e. no API stability guarantee.

then why is it in staging if there is no guarantee between minors?

**Comment by pohly** [comment]
Between 0.32.0 and 0.33.0? It's normal Go practice that there there is no API stability for 0.x releases. While we strive for more stability in staging repos, we also have always reserved the right to change APIs if needed. This one falls into that category.

Actually, it's even [documented explicitly already](https://github.com/kubernetes/dynamic-resource-allocation?tab=readme-ov-file#compatibility)! :smile:

**Comment by aojea** [comment]
> There are NO compatibility guarantees for this repository, yet. It is in direct support of Kubernetes, so branches will track Kubernetes and be compatible with that repo.

Kubernetes compatibility rules are much stricter as you can see in the backport rules, https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

**Comment by pohly** [comment]
I don't see anything in that document about "don't break APIs".

I fully understand that this would be surprising and that it might not be important enough for a backport, but in this case forgetting to update that API in 1.32.0 is the bug that we want to fix.

**Comment by pohly** [comment]
Okay, let's not backport.

DRA driver authors who need this can pin their dependency to https://github.com/kubernetes/dynamic-resource-allocation/commit/4361fe437fbafcf2e9cec648d590de43135b3b02.
