### ISSUE TITLE
Automated bare-metal deployment on CentOS

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubernetes/kubernetes#12914]
I'm recently working on kubernetes deployement on CentOS7. The [Manual Config Guide on CentOS](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/centos/centos_manual_config.md) is helpful to get an running environment, but not enough:
- User cannot easily deploy a multi-node cluster with too many manual configuration steps.
- Becides, it is not always easy to find a repo that provides the latest k8s rpm package.

I'd like to provide some scripts as well as guides to support the bare-metal deployment on CentOS, which are more automated and helpful for users to customize their own deployments.

**Comment by kevin-wangzefeng** [comment]
To review the scripts, please refer to the PR #12915.

**Comment by kevin-wangzefeng** [comment]
To review the guide, please refer to the PR #14119.

**Comment by roberthbailey** [comment]
#12915 merged. Marking as fixed.
