### ISSUE TITLE
Empty annotation removes all existing and valid annotations

### ISSUE THREAD

**Issue by bruecktech** [kubernetes/kubernetes#129176]
### What happened?

When creating a resource (e.g. a Service) with annotations the annotations are all removed when one of them has an empty value. The same happens on update.
It happens in our production environment as well as locally on minikube so I don't expect anything we deployed there to interfere with it.

### What did you expect to happen?

Applying the resource should fail on empty values

### How can we reproduce it (as minimally and precisely as possible)?

Create a Service (notice the empty `baz` annotation)

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    foo: bar
    baz:
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
```

Apply it

```
kubectl apply -f my-service.yaml
```

Retrieve it
```
kubectl get service my-service -o yaml
```

The service also lacks the `foo` annotation
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"my-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":9376}],"selector":{"app.kubernetes.io/name":"MyApp"}}}
  creationTimestamp: "2024-12-12T12:16:24Z"
  name: my-service
  namespace: default
  resourceVersion: "1776057"
  uid: a947a42c-a922-4f67-8103-c88dbb814004
spec:
  clusterIP: 169.254.131.120
  clusterIPs:
  - 169.254.131.120
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    app.kubernetes.io/name: MyApp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
  

### Anything else we need to know?

This happens with `kubectl apply` but also with `helm install` 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.5
WARNING: version difference between client (1.28) and server (1.25) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

MacOs 15.1.1

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by brianpursley** [comment]
I also am able to reproduce it.

It certainly is a surprising result.

A few things I notice when trying to reproduce it:

1. The `-v9` output shows that kubectl doesn't send either annotation in the request.

2. Server side apply seems to not have the problem:
```
~/projects/ktest/k-129176 $ kubectl apply -f svc.yaml --server-side
service/my-service serverside-applied
~/projects/ktest/k-129176 $ kubectl get svc my-service -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    baz: ""
    foo: bar
  creationTimestamp: "2024-12-16T23:37:48Z"
  name: my-service
  namespace: default
  resourceVersion: "162716"
  uid: 0857690a-2da1-43ad-b5db-8437946e79ff
spec:
  clusterIP: 10.96.9.210
  clusterIPs:
  - 10.96.9.210
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    app.kubernetes.io/name: MyApp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

/triage accepted
/sig cli

**Comment by ardaguclu** [comment]
Annotations are string maps and both of key and value must be string. [GetModifiedConfiguration](https://github.com/kubernetes/kubernetes/blob/3ec97a445f036a38bfec6291dee661954138bac9/staging/src/k8s.io/kubectl/pkg/util/apply.go#L78) function calls `NestedStringMap` and this function fails when there is a non-string value in [here](https://github.com/kubernetes/kubernetes/blob/3ec97a445f036a38bfec6291dee661954138bac9/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go#L197-L201). Consequently, all the annotations in the object are cleared up, since we couldn't extract the annotations in the object.

It would be better to propagate this error to the user for better experience. However, GetAnnotations functions interface is `GetAnnotations() map[string]string` which does not contain error.

I tried `bar: ""` instead of nil and it worked.

I think, always using `--server-side` in lieu of `client-side` in apply is still the best recommended path.

**Comment by ali-hamza-noor** [comment]
@brianpursley @ardaguclu Can I work on this issue? Would it better to propagate the error to the users in this case?

**Comment by ardaguclu** [comment]
@ali-hamza-noor This requires significant changes in the code base and it is not possible that we can change the signature of function to return the error.

**Comment by liggitt** [comment]
One possibility is to do additional validation specifically within kubectl to make sure labels and annotations are well-formed and don't specify `null` - https://github.com/kubernetes/kubernetes/pull/129255 is an example of that

The issue with that approach is that it will break commands like `kubectl create`, `kubectl replace`, and `kubectl apply --server-side` which currently turn `null` label and annotation values into empty strings:

`more nullannotation.yaml`
> ```yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: test
>   annotations:
>     foo: "x"
>     bar:
> data:
>   key: value
> ```

`kubectl create -f nullannotation.yaml -o yaml`:
> ```yaml
> apiVersion: v1
> data:
>   key: value
> kind: ConfigMap
> metadata:
>   annotations:
>     bar: ""
>     foo: x
>   creationTimestamp: "2024-12-17T15:32:05Z"
>   name: test
>   namespace: default
>   resourceVersion: "288"
>   uid: a6ccf114-7a6f-442f-b36e-f240c81376c0
> ```

`kubectl replace -f nullannotation.yaml -o yaml`:
> ```yaml
> apiVersion: v1
> data:
>   key: value
> kind: ConfigMap
> metadata:
>   annotations:
>     bar: ""
>     foo: x
>   creationTimestamp: "2024-12-17T15:36:10Z"
>   name: test
>   namespace: default
>   resourceVersion: "353"
>   uid: f8669ddf-900c-4ea5-ac74-5e6726b69357
> ```

`kubectl apply --server-side -f nullannotation.yaml -o yaml`:
> ```yaml
> apiVersion: v1
> data:
>   key: value
> kind: ConfigMap
> metadata:
>   annotations:
>     bar: ""
>     foo: x
>   creationTimestamp: "2024-12-17T15:32:28Z"
>   name: test
>   namespace: default
>   resourceVersion: "295"
>   uid: de32754a-44bb-44e0-97ef-2382396e422c
> ```

Only client-side apply (or things which try to set client-side apply annotations with `--set-config`) have this issue where they drop all other annotations:
`kubectl apply -f nullannotation.yaml -o yaml`:
> ```yaml
> apiVersion: v1
> data:
>   key: value
> kind: ConfigMap
> metadata:
>   annotations:
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"apiVersion":"v1","data":{"key":"value"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test","namespace":"default"}}
>   creationTimestamp: "2024-12-17T15:32:51Z"
>   name: test
>   namespace: default
>   resourceVersion: "302"
>   uid: 5b73bc45-5a09-4969-b5d4-9d295cd81a8d
> ```


Another possibility is to coerce null values to empty strings, to match what create / replace / server-side-apply do. https://github.com/kubernetes/kubernetes/pull/129257 does that.
