### ISSUE TITLE
The connection to the redis-clusterf service deployed by Kubernetes fails

### ISSUE THREAD

**Issue by 1280019840** [kubernetes/kubernetes#129171]
Redis-cluster is deployed in k8s, and the program built as a mirror is also deployed to k8s. The ClusterIP provided by redis service can normally connect to the redis service in k8s. If the redis service name cannot connect to the redis service in k8s, why is this
![image](https://github.com/user-attachments/assets/67a17ca5-edc4-4147-930d-8a5ec2b6672f)
![image](https://github.com/user-attachments/assets/05125fa6-bfe7-49a8-8b16-1e655f55abc2)

**Comment by BenTheElder** [comment]
You might try #kubernetes-users in https://slack.k8s.io or the forum at https://discuss.k8s.io

There's not enough info here to respond, and the project has far too many issues to handle user support in the issue tracker. This doesn't appear to be a Kubernetes bug, failing / flaking test, or feature request.
