### ISSUE TITLE
 add a non-existent owner reference to a resource can cause it to be silently deleted

### ISSUE THREAD

**Issue by caozhuozi** [kubernetes/kubernetes#129260]
### What happened?

 if we add a non-existent owner reference to a resource, the API **does not return an error when doing the modification**. However, the resource is deleted **silently** in the background.

### What did you expect to happen?

1. Do we need to return an error when the owner dose not exist ?
2. I am aware of an issue that one can delete a resource only with update permissions by hacking a non-existent owner reference to it. This should be regarded as an authorization issue.

### How can we reproduce it (as minimally and precisely as possible)?

1. create an arbitary resource
2. `kubectl edit` the resource, add a non-existent owner reference to a resource.
3. `kubectl get` the resource. the resource will be not found.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.5-gke.1443001", GitCommit:"d16b6cc50798c61dc2740487abdaa656af180538", GitTreeState:"clean", BuildDate:"2024-10-07T04:15:31Z", GoVersion:"go1.22.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux 5.15.0-1062-gcp #70~20.04.1-Ubuntu SMP Fri May 24 20:12:18 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pohly** [comment]
Kubernetes is state driven. Therefore an object with a reference to another object that no longer exists is identical to an object with a reference to another object that never has existed. Both objects get deleted. This is by design.

There is no logic either in the apiserver that checks for existence at creation time. The referenced object must have existed at the time when the client prepared the new object (because how else would the client get a UID for it?!) and could have been deleted in the meantime. There's no need to prevent the creation because eventually the resulting state will be the same (object deleted again).

**Comment by liggitt** [comment]
> I am aware of an issue that one can delete a resource only with update permissions by hacking a non-existent owner reference to it. This should be regarded as an authorization issue.

https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement is the admission plugin that can be enabled in clusters where this is a concern (it is not on by default)

**Comment by liggitt** [comment]
> Do we need to return an error when the owner does not exist?

No, that scenario is indistinguishable from the following valid scenario:

1. create object A
2. create object B
3. delete object B and update object A to have an ownerReference to B in parallel

That is not an error, and is the condition that properly leads to deletion of A.
