### ISSUE TITLE
Running Kubernetes with Vagrant (and VirtualBox) fails

### ISSUE THREAD

**Issue by noz-oro** [kubernetes/kubernetes#12921]
When performing common instalation of kube cluster via Vagrant (according to [Getting started with Vagrant](http://kubernetes.io/v1.0/docs/getting-started-guides/vagrant.html)) 

```bash
export KUBERNETES_PROVIDER=vagrant
export KUBERNETES_OS=ubuntu
export KUBERNETES_BOX_NAME=ubuntu/trusty64
curl -sS https://get.k8s.io | bash
```

it fails:

```bash
==> minion-1: Running provisioner: shell...
    minion-1: Running: /tmp/vagrant-shell20150819-15899-1hue163.sh
==> minion-1: stdin: is not a tty
==> minion-1: grep: 
==> minion-1: /etc/sysconfig/network-scripts/ifcfg-eth1
==> minion-1: : No such file or directory
==> minion-1: /tmp/vagrant-shell: line 149: /etc/sysconfig/network-scripts/ifcfg-eth1: No such file or directory
```

It seem to be that vagrant provisioning is hard-coded to be used with fedora and did not respects the `KUBERNETES_OS` nor `KUBERNETES_BOX_NAME` envars.

**Comment by roberthbailey** [comment]
@noz-oro Most of the automated install scripts target a specific OS distribution on a specific cloud provider. In this case, where the cloud provider is Vagrant, both Fedora and CoreOS are listed in the table of getting started guides: https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/README.md#table-of-solutions

If you'd like to contribute PRs to add support for Ubuntu, that would be awesome!

**Comment by derekwaynecarr** [comment]
As noted above, we do not support arbitrary box and OS distros.  

The fields used here were more intended to let specific vagrant box files to be pulled down that were required for a specific virtualization provider (i.e. libvirt, vbox, etc.).  It was not intended to be an entire different OS distribution.

If its important to you, feel free to add support for Ubuntu, or follow one of the Ubuntu getting started guides.
