### ISSUE TITLE
kubernetes dependency failure in CentOS 7.1

### ISSUE THREAD

**Issue by JackChen255** [kubernetes/kubernetes#12925]
I try to setup kubernetes master and 3 minions in four CentOS 7.1 VM. But in minions, I can't start kube service due to dependency failure. Can anyone one help on it? Thanks.

Installed Packages
Name : kubernetes
Arch : x86_64
Version : 1.0.0
Release : 0.8.gitb2dafda.el7
[root@localhost ~]# for SERVICES in kube-proxy kubelet docker flanneld; do systemctl restart $SERVICES; systemctl enable $SERVICES; systemctl status $SERVICES; done
kube-proxy.service - Kubernetes Kube-Proxy Server
Loaded: loaded (/usr/lib/systemd/system/kube-proxy.service; enabled)
Active: active (running) since Tue 2015-08-18 14:35:11 EDT; 280ms ago
Docs: https://github.com/GoogleCloudPlatform/kubernetes
Main PID: 2041 (kube-proxy)
CGroup: /system.slice/kube-proxy.service
└─2041 /usr/bin/kube-proxy --logtostderr=true --v=0 --master=http://172.24.18.120:4001

Aug 18 14:35:11 localhost.localdomain systemd[1]: Started Kubernetes Kube-Proxy Server.
Aug 18 14:35:12 localhost.localdomain kube-proxy[2041]: E0818 14:35:12.133962 2041 api.go:108] Unable to load services: the server could not find the requested resource (get services)
Aug 18 14:35:12 localhost.localdomain kube-proxy[2041]: E0818 14:35:12.134749 2041 api.go:180] Unable to load endpoints: the server could not find the requested resource (get endpoints)
A dependency job for kubelet.service failed. See 'journalctl -xn' for details.
kubelet.service - Kubernetes Kubelet Server
Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled)
Active: failed (Result: exit-code) since Tue 2015-08-18 14:29:05 EDT; 7min ago
Docs: https://github.com/GoogleCloudPlatform/kubernetes
Main PID: 4134 (code=exited, status=2)

Aug 18 14:29:04 localhost.localdomain kubelet[4134]: E0818 14:29:04.583542 4134 reflector.go:136] Failed to list *api.Service: the server could not find the requested resource (get services)
Aug 18 14:29:04 localhost.localdomain kubelet[4134]: E0818 14:29:04.583927 4134 reflector.go:136] Failed to list *api.Node: the server could not find the requested resource (get nodes)
Aug 18 14:29:04 localhost.localdomain kubelet[4134]: E0818 14:29:04.587238 4134 reflector.go:136] Failed to list *api.Pod: the server could not find the requested resource (get pods)
Aug 18 14:29:05 localhost.localdomain systemd[1]: Stopping Kubernetes Kubelet Server...
Aug 18 14:29:05 localhost.localdomain systemd[1]: kubelet.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 18 14:29:05 localhost.localdomain systemd[1]: Unit kubelet.service entered failed state.
Aug 18 14:30:35 localhost.localdomain systemd[1]: Dependency failed for Kubernetes Kubelet Server.
Aug 18 14:36:42 localhost.localdomain systemd[1]: Dependency failed for Kubernetes Kubelet Server.
A dependency job for docker.service failed. See 'journalctl -xn' for details.
docker.service - Docker Application Container Engine
Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
Drop-In: /usr/lib/systemd/system/docker.service.d
└─flannel.conf
Active: inactive (dead) since Tue 2015-08-18 14:29:05 EDT; 9min ago
Docs: http://docs.docker.com
Main PID: 4085 (code=exited, status=0/SUCCESS)
CGroup: /system.slice/docker.service

Aug 18 14:29:00 localhost.localdomain docker[4085]: time="2015-08-18T14:29:00.179186922-04:00" level=info msg="GET /containers/json"
Aug 18 14:29:00 localhost.localdomain docker[4085]: time="2015-08-18T14:29:00.977857973-04:00" level=info msg="GET /version"
Aug 18 14:29:05 localhost.localdomain systemd[1]: Stopping Docker Application Container Engine...
Aug 18 14:29:05 localhost.localdomain docker[4085]: time="2015-08-18T14:29:05.588557680-04:00" level=info msg="Processing signal 'terminated'"
Aug 18 14:30:35 localhost.localdomain systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 18 14:36:42 localhost.localdomain systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 18 14:38:12 localhost.localdomain systemd[1]: Dependency failed for Docker Application Container Engine.
Job for flanneld.service failed. See 'systemctl status flanneld.service' and 'journalctl -xn' for details.
flanneld.service - Flanneld overlay address etcd agent
Loaded: loaded (/usr/lib/systemd/system/flanneld.service; enabled)
Active: failed (Result: timeout) since Tue 2015-08-18 14:39:42 EDT; 199ms ago
Main PID: 2736

Aug 18 14:39:36 localhost.localdomain flanneld[2736]: E0818 14:39:36.074872 02736 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [35]
Aug 18 14:39:37 localhost.localdomain flanneld[2736]: E0818 14:39:37.077739 02736 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [35]
Aug 18 14:39:38 localhost.localdomain flanneld[2736]: E0818 14:39:38.080662 02736 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [35]
Aug 18 14:39:39 localhost.localdomain flanneld[2736]: E0818 14:39:39.083196 02736 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [35]
Aug 18 14:39:40 localhost.localdomain flanneld[2736]: E0818 14:39:40.085591 02736 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [35]
Aug 18 14:39:41 localhost.localdomain flanneld[2736]: E0818 14:39:41.087974 02736 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [35]
Aug 18 14:39:42 localhost.localdomain flanneld[2736]: E0818 14:39:42.090438 02736 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [35]
Aug 18 14:39:42 localhost.localdomain systemd[1]: flanneld.service operation timed out. Terminating.
Aug 18 14:39:42 localhost.localdomain systemd[1]: Failed to start Flanneld overlay address etcd agent.
Aug 18 14:39:42 localhost.localdomain systemd[1]: Unit flanneld.service entered failed state.
[root@localhost ~]# for SERVICES in kube-proxy kubelet docker flanneld; do systemctl restart $SERVICES; systemctl enable $SERVICES; systemctl status $SERVICES; done
kube-proxy.service - Kubernetes Kube-Proxy Server
Loaded: loaded (/usr/lib/systemd/system/kube-proxy.service; enabled)
Active: active (running) since Tue 2015-08-18 14:55:32 EDT; 547ms ago
Docs: https://github.com/GoogleCloudPlatform/kubernetes
Main PID: 5499 (kube-proxy)
CGroup: /system.slice/kube-proxy.service
└─5499 /usr/bin/kube-proxy --logtostderr=true --v=0 --master=http://172.24.18.120:4001

Aug 18 14:55:32 localhost.localdomain systemd[1]: Started Kubernetes Kube-Proxy Server.
Aug 18 14:55:32 localhost.localdomain kube-proxy[5499]: E0818 14:55:32.269131 5499 api.go:108] Unable to load services: the server could not find the requested resource (get services)
Aug 18 14:55:32 localhost.localdomain kube-proxy[5499]: E0818 14:55:32.270175 5499 api.go:180] Unable to load endpoints: the server could not find the requested resource (get endpoints)
A dependency job for kubelet.service failed. See 'journalctl -xn' for details.
kubelet.service - Kubernetes Kubelet Server
Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled)
Active: failed (Result: exit-code) since Tue 2015-08-18 14:29:05 EDT; 27min ago
Docs: https://github.com/GoogleCloudPlatform/kubernetes
Main PID: 4134 (code=exited, status=2)

Aug 18 14:30:35 localhost.localdomain systemd[1]: Dependency failed for Kubernetes Kubelet Server.
Aug 18 14:36:42 localhost.localdomain systemd[1]: Dependency failed for Kubernetes Kubelet Server.
Aug 18 14:38:12 localhost.localdomain systemd[1]: Dependency failed for Kubernetes Kubelet Server.
Aug 18 14:39:42 localhost.localdomain systemd[1]: Dependency failed for Kubernetes Kubelet Server.
Aug 18 14:57:02 localhost.localdomain systemd[1]: Dependency failed for Kubernetes Kubelet Server.
A dependency job for docker.service failed. See 'journalctl -xn' for details.
docker.service - Docker Application Container Engine
Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
Drop-In: /usr/lib/systemd/system/docker.service.d
└─flannel.conf
Active: inactive (dead) since Tue 2015-08-18 14:29:05 EDT; 29min ago
Docs: http://docs.docker.com
Main PID: 4085 (code=exited, status=0/SUCCESS)
CGroup: /system.slice/docker.service

Aug 18 14:36:42 localhost.localdomain systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 18 14:38:12 localhost.localdomain systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 18 14:39:42 localhost.localdomain systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 18 14:57:02 localhost.localdomain systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 18 14:58:33 localhost.localdomain systemd[1]: Dependency failed for Docker Application Container Engine.
Job for flanneld.service failed. See 'systemctl status flanneld.service' and 'journalctl -xn' for details.
flanneld.service - Flanneld overlay address etcd agent
Loaded: loaded (/usr/lib/systemd/system/flanneld.service; enabled)
Active: failed (Result: timeout) since Tue 2015-08-18 15:00:03 EDT; 248ms ago
Main PID: 6131

Aug 18 14:59:56 localhost.localdomain flanneld[6131]: E0818 14:59:56.531987 06131 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [52]
Aug 18 14:59:57 localhost.localdomain flanneld[6131]: E0818 14:59:57.534650 06131 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [52]
Aug 18 14:59:58 localhost.localdomain flanneld[6131]: E0818 14:59:58.537597 06131 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [52]
Aug 18 14:59:59 localhost.localdomain flanneld[6131]: E0818 14:59:59.540381 06131 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [52]
Aug 18 15:00:00 localhost.localdomain flanneld[6131]: E0818 15:00:00.543285 06131 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [52]
Aug 18 15:00:01 localhost.localdomain flanneld[6131]: E0818 15:00:01.545823 06131 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [52]
Aug 18 15:00:02 localhost.localdomain flanneld[6131]: E0818 15:00:02.549499 06131 main.go:151] Failed to create SubnetManager: 100: Key not found (/coreos.com) [52]
Aug 18 15:00:03 localhost.localdomain systemd[1]: flanneld.service operation timed out. Terminating.
Aug 18 15:00:03 localhost.localdomain systemd[1]: Failed to start Flanneld overlay address etcd agent.
Aug 18 15:00:03 localhost.localdomain systemd[1]: Unit flanneld.service entered failed state.

**Comment by hw-qiaolei** [comment]
Hello JackChen255,
I believe your have wrongly configured your system.  For the following reasons:
1, By default etcd usually listens on 4001,  api server listens on 8080;
2, It is clearly see from your log the flannel etcd  key not found. 

So, please check the following configuration(or paste these values here):
1, On master:
    - `/etc/etcd/etcd.conf`: `ETCD_LISTEN_CLIENT_URLS`
    - `/etc/kubernetes/apiserver`: `KUBE_API_ADDRESS`, `KUBE_API_PORT`, `KUBE_ETCD_SERVERS`
    - The output of `etcdctl get /coreos.com/network/config Network`
2, On node:
    - `/etc/sysconfig/flanneld`: `FLANNEL_ETCD`, `FLANNEL_ETCD_KEY`
    - `/etc/kubernetes/config`: `KUBE_MASTER`
    - `/etc/kubernetes/kubelet`: `KUBELET_HOSTNAME`, `KUBELET_API_SERVER`

**Comment by JackChen255** [comment]
Hi @hw-qiaolei,
Thanks for your help. The config files are as below.
[root@localhost ~]# etcdctl get /coreos.com/network/config Network
Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379

/etc/etcd/etcd.conf:
ETCD_NAME=default
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:4001"

/etc/kubernetes/apiserver:
KUBE_API_ADDRESS="--address=0.0.0.0"
# The port on the local server to listen on.
KUBE_API_PORT="--port=8080"
# Port minions listen on
KUBELET_PORT="--kubelet_port=10250"
# Comma separated list of nodes in the etcd cluster
KUBE_ETCD_SERVERS="--etcd_servers=http://127.0.0.1:4001"
# Address range to use for services
KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.254.0.0/16"
# default admission control policies
#KUBE_ADMISSION_CONTROL="--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"
KUBE_ADMISSION_CONTROL="--admission_control=NamespaceAutoProvision,LimitRanger,ResourceQuota"
# Add your own!
KUBE_API_ARGS=""


Minion nodes:
/etc/sysconfig/flanneld:
FLANNEL_ETCD="http://172.24.18.120:4001"
FLANNEL_ETCD_KEY="/coreos.com/network"

/etc/kubernetes/config:
KUBE_LOGTOSTDERR="--logtostderr=true"
KUBE_LOG_LEVEL="--v=0"
KUBE_ALLOW_PRIV="--allow_privileged=false"
KUBE_MASTER="--master=http://172.24.18.120:8080"

/etc/kubernetes/kubelet:
KUBELET_ADDRESS="--address=127.0.0.1"
KUBELET_PORT="--port=10250"
KUBELET_HOSTNAME="--hostname_override=172.24.18.124"
KUBELET_API_SERVER="--api_servers=http://172.24.18.120:8080"
KUBELET_ARGS=""

**Comment by hw-qiaolei** [comment]
Hello JackChen255,

My suggestions are as following:

On **Master**:
1, Define flannel network configuration in etcd, which will be pulled by flannel service on nodes:
`etcdctl mk /coreos.com/network/config '{"Network":"172.17.0.0/16"}'`

This will eliminate the `Key not found (/coreos.com)` error messages.

2, Configure `/etc/kubernetes/controller-manager`, define the nodes' IP addresses:
`KUBELET_ADDRESSES="--machines=172.24.18.124,172.24.18.X,172.24.18.Y"`

Replace `X`, `Y` with actual values.

On **Node**:
3, Make sure docker are installed and running properly on your nodes:
`rpm -qa | grep docker`
`systemctl status docker.service`

4,  Configure `/etc/kubernetes/kubelet` as the following:
`KUBELET_ADDRESS="--address=0.0.0.0"`

Good luck.

**Comment by roberthbailey** [comment]
Please direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by bsed** [comment]
i have same problem

**Comment by cmlicata** [comment]
I have the same problem as well
