### ISSUE TITLE
AKS connection refused 

### ISSUE THREAD

**Issue by PoornaKumar151997** [kubernetes/kubernetes#129383]
### Which jobs are failing?

Hello everyone,

I have set up an AKS cluster with the following configuration:

Version: 1.29.8
Node Pools: 2
Userpool: AKSAzureLinux-V2gen2-202412.04.0
Agentpool: AKSUbuntu-2204gen2containerd-2024
Our goal is to automate the transfer of files from one server to another. To achieve this, I have configured an Azure Site-to-Site VPN. However, when attempting to transfer files using the cluster, I encounter the following error:

![image (5)](https://github.com/user-attachments/assets/922e4632-b747-4911-a4fe-4c9b23ad27ac)
![image (5)](https://github.com/user-attachments/assets/d908d590-2228-4740-ab3a-4d68e455b46e)

### Which tests are failing?

while transferring files, the connection was not stable. In some scenarios, the connection was refused.

### Since when has it been failing?

I have attached the screen shot of error
![image (5)](https://github.com/user-attachments/assets/050c9334-6b61-4b32-9359-a5dd059f5c01)

### Relevant SIG(s)

/sig

**Comment by sftim** [comment]
/remove-kind failing-test
/kind support

AIUI this is a support query
