### ISSUE TITLE
[proposal]two better resource scheduling and allocation plugins

### ISSUE THREAD

**Issue by LY-today** [kubernetes/kubernetes#129316]
### What would you like to be added?

**What is your proposal**:
The NodeResourcesFit plug-in of native k8s can only adopt a type of strategy for all resources, such as MostRequestedPriority and LeastRequestedPriority. However, in industrial practice, this design does not apply to some scenarios. For example: In AI scenarios, businesses that apply for GPUs prefer to occupy the entire GPU machine first to prevent GPU fragmentation; businesses that apply for CPU & MEM are prioritized and dispersed to non-GPU machines to prevent excessive consumption of CPU & MEM on GPU machines, resulting in real tasks of applying for GPUs. Pending due to insufficient non-GPU resources
. It is therefore hoped that both strategies can be extended to address this business need.

**Why is this needed**:
There are related descriptions above

**Is there a suggested solution, if so, please add it**:
### plugin-one
config：
```
resources: 
  nvidia.com/gpu:
    type: MostAllocated
    weight: 2
  cpu:
    type: LeastAllocated
    weight: 1
  memory:
    type: LeastAllocated
    weight: 1
```
config description：
![image](https://github.com/user-attachments/assets/2427864d-7738-4687-a5a9-d8553dd22e39)

node score:
```
finalScoreNode = [(weight1 * resource1) + (weight2 * resource2) + … + (weightN* resourceN)] /(weight1+weight2+ … +weightN)
```

 ### plugin-two
config：
```
resources: 
- nvidia.com/gpu 
```
config description：
![image](https://github.com/user-attachments/assets/6fe369b6-0bbf-4501-ba97-f86ac662e7a4)

node score:
```
finalScoreNode = (allocatablesResourcesNum - requestsResourcesNum) * framework.MaxNodeScore / allocatablesResourcesNum
```

### Why is this needed?

It’s introduced above

**Comment by sftim** [comment]
Thanks for the feature request. Kubernetes is already written to be extensible.

- do these plugins need to be part of Kubernetes?

**Comment by LY-today** [comment]
@sftim Yes, these two plug-ins have been extended and running in our enterprise for some time and have achieved the expected benefits. So now I want to provide these two ideas to the Kubernetes community. First of all, I want to ask you a question. Do you think these two plugins are valuable, and do you have any intention to merge them?

**Comment by sftim** [comment]
> Yes, these two plug-ins have been extended and running in our enterprise for some time and have achieved the expected benefits. So now I want to provide these two ideas to the Kubernetes community. First of all, I want to ask you a question. Do you think these two plugins are valuable, and do you have any intention to merge them?

If you're willing to, you could propose donating the existing code to the CNCF. Would you like advice on how to do that @LY-today?

**Comment by LY-today** [comment]
@sftim I'm not sure what the difference is between donating to CNCF and merging code into the kubernetes code repository? Can you explain it to me?

**Comment by sftim** [comment]
Sure.

## Donation to CNCF

Example: Karpenter

AWS, the cloud provider, wrote Karpenter and then donated https://github.com/kubernetes-sigs/karpenter to the CNCF. It is now maintained by the Kubernetes organization.

## Merge into k/k

Huang Wei, who currently works for Apple, authored a [PR](https://github.com/kubernetes/kubernetes/pull/92682) to improve the (existing) Preemption plugin. Kubernetes accepted that change and now maintains it as part of core Kubernetes.

**Comment by LY-today** [comment]
@sftim Thank you for your explanation. I have this intention, and I have mentioned this MR variant to the koordinator community. Of course, this is the advancement after preliminary communication with community classmates: https://github.com/koordinator- sh/koordinator/pull/2302

In the future, I will also submit an MR about kubernetes to enhance the scheduling strategy. I look forward to your guidance on this MR in the future.

**Comment by sftim** [comment]
Ah, OK, so you might add these to Koordinator instead? That works.

**Comment by sftim** [comment]
Once nice benefit of contributing these to Koordinator is that we should find it easy to borrow the code for Kubernetes if we ever want to.

**Comment by LY-today** [comment]
@sftim In fact, on the contrary, we prefer to integrate it into kubernetes, so that more open source components can obtain public packages or functional capabilities from kubernetes.

**Comment by LY-today** [comment]
@sftim I have communicated with students in the Koordinator community. They very much agree with the MR proposal, and they suggest that if it can be integrated into kubernetes, many open source workers can reuse the capabilities of kubernetes. After all, kubernetes is the master of the container field.

**Comment by LY-today** [comment]
@sftim koordinator is a community project open sourced from China, so part of the description covers Chinese. The MR just now is more suitable for koordinator, but not suitable for kubernetes, but their principles are consistent and can bring substantial benefits, so these two plugins will be shared with kubernetes, and MR more suitable for kubernetes will be provided in the future.

**Comment by googs1025** [comment]
The scheduling plugin is currently an extensible feature. If we want to add it, we can propose it in here https://github.com/kubernetes-sigs/scheduler-plugins . @LY-today

**Comment by LY-today** [comment]
> The scheduling plugin is currently an extensible feature. If we want to add it, we can propose it in here https://github.com/kubernetes-sigs/scheduler-plugins . @LY-today

receive

**Comment by LY-today** [comment]
@googs1025 Doesn't the Makefile of scheduler-plugins provide a code generation tool like generate to help users generate code for scheme-related files?

**Comment by googs1025** [comment]
Has been moved to scheduler-plugins, close it first, open it freely 
https://github.com/kubernetes-sigs/scheduler-plugins/issues/842
/close
