### ISSUE TITLE
Raise Node events/ status when a node is being drained

### ISSUE THREAD

**Issue by svijaykumar-px** [kubernetes/kubernetes#129318]
I am running an EKS cluster with pods protected by Pod DIsruption Budget. During kubernetes upgrades, EKS cordons all nodes but selects only few nodes randomly to drain at a time . I want to control the order of node upgrades by updating the PodDisruptionBudget (PDB) accordingly.  For this I would need to know the exact nodes that EKS drains . Right now since I am unable to detect node drains via kubernetes events or status or pod eviction failures due to PDB, the upgrades fail.

I would need some help in understanding if there is any way to find when a node is exactly draining? I cannot use external observability tools like prometheus or grafana nor can I used EKS's built in cloud watch. Is there any other native kubernetes way to find out nodes being drained?

Would it also be good to have a small enhancement where we update the node status or raise an event when node is being drained?

**Comment by dims** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by dims** [comment]
Please talk to AWS/EKS support or use the support channels as mentioned above.

**Comment by svijaykumar-px** [comment]
> a better place to ask would be on the support channels. please see: https://git.k8s.io/kubernetes/SUPPORT.md
> 
> /kind support /close

Thank you, however I did ask on the [support channel ](https://discuss.kubernetes.io/t/node-events-status-when-a-node-is-being-drained/30868) as well as slack, but did not get any response. I was hoping to get better visibility on github.

**Comment by svijaykumar-px** [comment]
> Please talk to AWS/EKS support or use the support channels as mentioned above.

Thank you, I did talk to the EKS support team and they have created a feature request, but they have not planned it on their roadmap, so I was looking to see if there are any solutions or workarounds from kubernetes meanwhile.
