### ISSUE TITLE
Support 'dockerfile' deployment

### ISSUE THREAD

**Issue by yaronr** [kubernetes/kubernetes#1294]
Hi

Not sure if this capability exists or not (if it does, then docs have to be updated):
I would like to create a pod / run a docker container on Kube, using a dockerfile (text), as opposed to a docker image on a repository.

**Comment by bgrant0607** [comment]
cc @ethernetdan

**Comment by smarterclayton** [comment]
The challenge with any such scheme is that it isn't deterministic.  I suspect init containers may address part of this use case for simpler setups, but not the more complex ones.

**Comment by bgrant0607** [comment]
This functionality won't be in core Kubernetes.
