### ISSUE TITLE
release-1.0: Node resize tests flaky

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#12946]
Node resize tests are flaky on the release branch, on pretty high order (10%-ish).

**Comment by quinton-hoole** [comment]
@zmerlynn which Jenkins job are you referring to?

**Comment by zmerlynn** [comment]
`kubernetes-e2e-gce-release`

**Comment by quinton-hoole** [comment]
They seem to have stabilized, for reasons as yet unknown.  Zero failures over the past 30 runs:

```
Nodes Resize should be able to add nodes (No known failures. Stability 100 %) No flake or failure
Nodes Resize should be able to delete nodes (No known failures. Stability 100 %) No flake or failure
```

I'll take a closer look at the most recent failures and try to correlate them with a bug fix.

**Comment by quinton-hoole** [comment]
Here are the most recent failures...

**Build #714 (Aug 19, 2015 2:56:09 AM)**

**Nodes Resize should be able to add nodes**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:485
Expected error:
    <*errors.errorString | 0xc208d12ba0>: {
        s: "timeout waiting for cluster size to be 3",
    }
    timeout waiting for cluster size to be 3 not to have occurred

**Build #702 (Aug 18, 2015 10:45:38 AM)**

**Nodes Resize should be able to delete nodes**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:459
Expected error:
    <*errors.errorString | 0xc2081ed870>: {
        s: "failed to wait for pods responding: pod with UID 027bfbbe-45d5-11e5-b512-42010af0c24b is no longer a member of the replica set.  Must have been restarted for some reason.  Current replica set: &{{ } {/api/v1/namespaces/e2e-tests-resize-nodes-koc4w/pods 1568} [{{ } {my-hostname-delete-node-q91y8 my-hostname-delete-node- e2e-tests-resize-nodes-koc4w /api/v1/namespaces/e2e-tests-resize-nodes-koc4w/pods/my-hostname-delete-node-q91y8 2114cacc-45d5-11e5-b512-42010af0c24b 1568 0 2015-08-18 11:15:39 -0700 PDT <nil> map[name:my-hostname-delete-node] map[kubernetes.io/created-by:{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"e2e-tests-resize-nodes-koc4w\",\"name\":\"my-hostname-delete-node\",\"uid\":\"027af05f-45d5-11e5-b512-42010af0c24b\",\"apiVersion\":\"v1\",\"resourceVersion\":\"1548\"}}]} {[{default-token-w986y {<nil> <nil> <nil> <nil> <nil> 0xc2081ed1e0 <nil> <nil> <nil> <nil> <nil>}}] [{my-hostname-delete-node gcr.io/google_containers/serve_hostname:1.1 [] []  [{ 0 9376 TCP }] [] {map[] map[]} [{default-token-w986y true /var/run/secrets/kubernetes.io/serviceaccount}] <nil> <nil> <nil> /dev/termination-log IfNotPresent <nil>}] Always <nil> <nil> ClusterFirst map[] default e2e-gce-minion-npti false []} {Running [{Ready False}]   10.240.132.101 10.245.1.13 2015-08-18 11:15:39 -0700 PDT [{my-hostname-delete-node {<nil> 0xc20822c000 <nil>} {<nil> <nil> <nil>} false 0 gcr.io/google_containers/serve_hostname:1.1 docker://00619279d4083019321e4865829a65a550a23c677d76cbb44274ade0d92ca7a9 docker://2d1ca709c0e1c8d4e2c6d36dc17be1414712f5a5a8620d9f0a887813607fde6c}]}} {{ } {my-hostname-delete-node-rfmw3 my-hostname-delete-node- e2e-tests-resize-nodes-koc4w /api/v1/namespaces/e2e-tests-resize-nodes-koc4w/pods/my-hostname-delete-node-rfmw3 211046ae-45d5-11e5-b512-42010af0c24b 1567 0 2015-08-18 11:15:38 -0700 PDT <nil> map[name:my-hostname-delete-node] map[kubernetes.io/created-by:{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"e2e-tests-resize-nodes-koc4w\",\"name\":\"my-hostname-delete-node\",\"uid\":\"027af05f-45d5-11e5-b512-42010af0c24b\",\"apiVersion\":\"v1\",\"resourceVersion\":\"1510\"}}]} {[{default-token-w986y {<nil> <nil> <nil> <nil> <nil> 0xc2081ed210 <nil> <nil> <nil> <nil> <nil>}}] [{my-hostname-delete-node gcr.io/google_containers/serve_hostname:1.1 [] []  [{ 0 9376 TCP }] [] {map[] map[]} [{default-token-w986y true /var/run/secrets/kubernetes.io/serviceaccount}] <nil> <nil> <nil> /dev/termination-log IfNotPresent <nil>}] Always <nil> <nil> ClusterFirst map[] default e2e-gce-minion-npti false []} {Running [{Ready False}]   10.240.132.101 10.245.1.12 2015-08-18 11:15:39 -0700 PDT [{my-hostname-delete-node {<nil> 0xc20822c300 <nil>} {<nil> <nil> <nil>} false 0 gcr.io/google_containers/serve_hostname:1.1 docker://00619279d4083019321e4865829a65a550a23c677d76cbb44274ade0d92ca7a9 docker://1e3cabe2eb328932b8536a380fb08af60af04bc2c569f00070555b64de147d5e}]}}]}",
    }
    failed to wait for pods responding: pod with UID 027bfbbe-45d5-11e5-b512-42010af0c24b is no longer a member of the replica set.  Must have been restarted for some reason.  Current replica set: &{{ } {/api/v1/namespaces/e2e-tests-resize-nodes-koc4w/pods 1568} [{{ } {my-hostname-delete-node-q91y8 my-hostname-delete-node- e2e-tests-resize-nodes-koc4w /api/v1/namespaces/e2e-tests-resize-nodes-koc4w/pods/my-hostname-delete-node-q91y8 2114cacc-45d5-11e5-b512-42010af0c24b 1568 0 2015-08-18 11:15:39 -0700 PDT <nil> map[name:my-hostname-delete-node] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"e2e-tests-resize-nodes-koc4w","name":"my-hostname-delete-node","uid":"027af05f-45d5-11e5-b512-42010af0c24b","apiVersion":"v1","resourceVersion":"1548"}}]} {[{default-token-w986y {<nil> <nil> <nil> <nil> <nil> 0xc2081ed1e0 <nil> <nil> <nil> <nil> <nil>}}] [{my-hostname-delete-node gcr.io/google_containers/serve_hostname:1.1 [] []  [{ 0 9376 TCP }] [] {map[] map[]} [{default-token-w986y true /var/run/secrets/kubernetes.io/serviceaccount}] <nil> <nil> <nil> /dev/termination-log IfNotPresent <nil>}] Always <nil> <nil> ClusterFirst map[] default e2e-gce-minion-npti false []} {Running [{Ready False}]   10.240.132.101 10.245.1.13 2015-08-18 11:15:39 -0700 PDT [{my-hostname-delete-node {<nil> 0xc20822c000 <nil>} {<nil> <nil> <nil>} false 0 gcr.io/google_containers/serve_hostname:1.1 docker://00619279d4083019321e4865829a65a550a23c677d76cbb44274ade0d92ca7a9 docker://2d1ca709c0e1c8d4e2c6d36dc17be1414712f5a5a8620d9f0a887813607fde6c}]}} {{ } {my-hostname-delete-node-rfmw3 my-hostname-delete-node- e2e-tests-resize-nodes-koc4w /api/v1/namespaces/e2e-tests-resize-nodes-koc4w/pods/my-hostname-delete-node-rfmw3 211046ae-45d5-11e5-b512-42010af0c24b 1567 0 2015-08-18 11:15:38 -0700 PDT <nil> map[name:my-hostname-delete-node] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"e2e-tests-resize-nodes-koc4w","name":"my-hostname-delete-node","uid":"027af05f-45d5-11e5-b512-42010af0c24b","apiVersion":"v1","resourceVersion":"1510"}}]} {[{default-token-w986y {<nil> <nil> <nil> <nil> <nil> 0xc2081ed210 <nil> <nil> <nil> <nil> <nil>}}] [{my-hostname-delete-node gcr.io/google_containers/serve_hostname:1.1 [] []  [{ 0 9376 TCP }] [] {map[] map[]} [{default-token-w986y true /var/run/secrets/kubernetes.io/serviceaccount}] <nil> <nil> <nil> /dev/termination-log IfNotPresent <nil>}] Always <nil> <nil> ClusterFirst map[] default e2e-gce-minion-npti false []} {Running [{Ready False}]   10.240.132.101 10.245.1.12 2015-08-18 11:15:39 -0700 PDT [{my-hostname-delete-node {<nil> 0xc20822c300 <nil>} {<nil> <nil> <nil>} false 0 gcr.io/google_containers/serve_hostname:1.1 docker://00619279d4083019321e4865829a65a550a23c677d76cbb44274ade0d92ca7a9 docker://1e3cabe2eb328932b8536a380fb08af60af04bc2c569f00070555b64de147d5e}]}}]}
not to have occurred

**Build #701 (Aug 18, 2015 9:21:51 AM)**

**Nodes Resize should be able to add nodes**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:410
Not all nodes are ready: Not ready nodes: [{{ } {e2e-gce-minion-4khn   /api/v1/nodes/e2e-gce-minion-4khn 884635db-45c6-11e5-8c5b-42010af0fdd8 2408 0 2015-08-18 09:31:09 -0700 PDT <nil> map[kubernetes.io/hostname:e2e-gce-minion-4khn] map[]} {10.245.0.0/24 14134641876684247957 gce://k8s-jkns-e2e-gce-release/us-central1-f/e2e-gce-minion-4khn false} {map[cpu:{2.000 DecimalSI} memory:{7863918592.000 BinarySI} pods:{40.000 DecimalSI}]  [{Ready Unknown 2015-08-18 09:49:37 -0700 PDT 2015-08-18 09:50:21 -0700 PDT Kubelet stopped posting node status. }] [{InternalIP 10.240.36.246} {ExternalIP 146.148.55.98}] { 56D4FFBC-C579-2317-DC85-9F8354906656 1439f6a8-9452-468b-af1c-8d78fe9915fa 3.16.0-0.bpo.4-amd64 Debian GNU/Linux 7 (wheezy) docker://Unknown v1.0.3.8+5e1da5a5027a8f-dirty v1.0.3.8+5e1da5a5027a8f-dirty}}}]

**Comment by quinton-hoole** [comment]
Closing for now, but I assume that this is going to come back and bite us in the ass soon, in which case I'll re-open.
