### ISSUE TITLE
High severity vulnerability reported in golang.org/x/net

### ISSUE THREAD

**Issue by checkaayush** [kubernetes/kubernetes#129412]
As per GitHub's advisory (https://github.com/advisories/GHSA-w32m-9786-jp63), version for `golang.org/x/net` in dependencies should be upgraded to `v0.33.0`.

**Comment by liggitt** [comment]
This is a false positive, and duplicate of https://github.com/kubernetes/kubernetes/issues/129347

The dependency is updated in master branch for 1.33, but will not be backported to release branches, since this is a false positive and does not actually impact client-go

/close

**Comment by checkaayush** [comment]
https://github.com/kubernetes/kubernetes/blob/v1.33.0-alpha.0/go.mod#L77

**Comment by dims** [comment]
@checkaayush did you read the link from @liggitt ? please do!

**Comment by checkaayush** [comment]
> @checkaayush did you read the link from @liggitt ? please do!

Yes, I did read the link shared and understood that the CVE doesn't impact the project. What I don't see is the dependency upgraded in 1.33 master, hence shared that link.

**Comment by dims** [comment]
@checkaayush a quick search of PRs in progress would have helped.

https://github.com/kubernetes/kubernetes/pull/129349
