### ISSUE TITLE
Alpine linux unable to use version 1.30.5 and higher

### ISSUE THREAD

**Issue by Gerrel** [kubernetes/kubernetes#129436]
**What happened**: Upgrade kubectl version in Alpine container fails.

**What you expected to happen**: Running as usual.

**How to reproduce it (as minimally and precisely as possible)**: 
This Dockerfile KUBE_VERSION fails with error "/usr/local/bin/kubectl: line 1: syntax error: unexpected redirection": 
```
FROM alpine:3.21.0
RUN apk add curl zip unzip && rm -rf /var/cache/apk/*
ARG KUBE_VERSION=1.30.5
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBE_VERSION}/bin/linux/amd64/kubectl
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
RUN kubectl version --client
```

**Anything else we need to know?**:
This Dockerfile KUBE_VERSION succeeds:
```
FROM alpine:3.21.0
RUN apk add curl zip unzip && rm -rf /var/cache/apk/*
ARG KUBE_VERSION=1.30.4
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBE_VERSION}/bin/linux/amd64/kubectl
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
RUN kubectl version --client
```

**Environment**:
- Docker
- Just save above code snippets in file named "Dockerfile"
- Run build command by "docker build ."

**Comment by pacoxu** [comment]
/kind support
Try to follow the latest official website: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux and https://kubernetes.io/blog/2023/06/09/dl-adopt-cdn/.

```
curl -LO https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl
```
