### ISSUE TITLE
Link to Borg in readme is broken

### ISSUE THREAD

**Issue by fatima2003** [kubernetes/kubernetes#129413]
### What happened?

I'm new to the Kubernetes repo and was looking through the docs and discovered a broken link to Borg in the readme file.

![image](https://github.com/user-attachments/assets/6acaa45b-fbd3-40d0-b08a-ee51d3f0cc9b)

### What did you expect to happen?

See the page linked to Borg.

### How can we reproduce it (as minimally and precisely as possible)?

Click on the link to Borg on the readme.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3```

</details>


### Cloud provider

<details>

</details>


### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

**Comment by dims** [comment]
/close

fix will land in https://github.com/kubernetes/kubernetes/pull/129365
