### ISSUE TITLE
local-up-cluster, x509 errors not easily deduced

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#12955]
The error that we fixed in #11285  seemingly  can still occur, it seems.  I've put the details here.  

The core error that we see, is: 

```
[root@fed22-kubernetes-pr11715 fedora]# docker logs 8022e9e85aa1
2015/08/19 19:59:36 Unable to get server version: Get https://10.0.0.1:443/version: x509: certificate signed by unknown authority
```

This is reproduced by running the networking test:

```
 sudo _output/local/bin/linux/amd64/e2e.test --host="http://127.0.0.1:8080" --provider="local" --ginkgo.v=true --ginkgo.focus="Networking" --kubeconfig="$HOME/.kubernetes_auth" --repo-root="/home/fedora/gopath/src/k8s.io/kubernetes/" #--repo-root="/home/fedora/gopath/k8s.io/kubernetes"
```

THOUGHT: I played with some things, and although not sure, I think changing permissions of /var/run/kubernetes/.. permissions to being open seems to fix the issue.

The goal here: We should report/document/reference a docs/.md file explaining how the security x509/crt's are meant to work for users so that when they see such errors there is some kind of diagnostic workflow .

**Comment by jayunit100** [comment]
*Indeed, I found that just deleting /var/run/kubernetes is enough to fix this error*.  

No idea why.  Probably related to the fact that, if you run local-up multiple times on multiple branches or something, those tokens can get their permissions messed up? Or maybe they get out of sync somehow with other things? 

I guess we can add a PR to add this info to a doc page somewhere, and link to it in the hack/local-up-cluster shell script.

@liggitt and I debugged this some today... jordan, now that we've finally gotten to the bottom of it..  any thoughts on the right way to deal with this, now that we know deleting var/run/kubernetes fixes the problem?

**Comment by liggitt** [comment]
not sure... I thought local-up-cluster.sh cleans up and recreates etcd and certs every time. If you see this again, can you check the filesystem permissions on the cert?

**Comment by liggitt** [comment]
@saad-ali can probably lower the priority on this

**Comment by jayunit100** [comment]
Yeah, If your saying local up should be idem potent than if I can reproduce failure by changing perms, it is officially a bug

**Comment by liggitt** [comment]
might just be a cleanup failure in local-up-cluster.sh... I think it cleans up etcd on shutdown, but doesn't ensure a clean slate on startup (etcd, cert files, etc)

**Comment by jayunit100** [comment]
Ok.  So the goal for this issue can be to 

- add cleanup to local-up.
- add some Verification of certificates on startup.

**Comment by euank** [comment]
How certs are managed with local-up-cluster has been totally reworked pretty much (cfssl and all that jazz).

I suspect we can close this issue as stale.

**Comment by roberthbailey** [comment]
Given the last update from @euank, I'm closing this issue as obsolete.
