### ISSUE TITLE
Endpoints are not persistented

### ISSUE THREAD

**Issue by wb14123** [kubernetes/kubernetes#12964]
I create a glusterfs endpoint, but after I restart kube-apiserver, the endpoint is missing. Does Kubernetes persistence endpoints?

**Comment by thockin** [comment]
Do you mean and Endpoints object in the API or something else?

**Comment by wb14123** [comment]
Here is what I do:

```
 > kubectl create -f glusterfs-endpoints.yaml
endpoints/glusterfs-cluster

> cat glusterfs-endpoints.yaml
kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - IP: 192.168.1.1
    ports:
      - port: 1
  - addresses:
      - IP: 192.168.1.2
    ports:
      - port: 1
```

Then use `kubectl get endpoints` I can see this line:

```
glusterfs-cluster          192.168.1.1:1,192.168.1.2:1
```

But after I restart kube-apiserver, this endpoint is lost.

**Comment by thockin** [comment]
Do you have a Service named `glusterfs-cluster` ?

Otherwise it should persist, just the same as any other API object

**Comment by wb14123** [comment]
No. This endpoints is just used for persistent volumes, which is used by other pods. I followed [this doc](http://kubernetes.io/v1.0/examples/glusterfs/README.html). Is it necessary to define a service?

**Comment by thockin** [comment]
@wojtek-t Can one of you guys try to repro?

**Comment by markturansky** [comment]
> But after I restart kube-apiserver, this endpoint is lost.

What does that mean exactly?  What kind of cluster are you running?  Does *anything* persist and endure between restarts of the API server?  When you restart the API server (why?), are you also restarting etcd or other services?

**Comment by wb14123** [comment]
The cluster just have one master. The pods, secrets, controllers and services are recovered after the restart, but the endpoints are not.

About why I restart the API server, well, it may fail (or something else). You cannot expect the api-server runs and never restart. After I restart it, I expect all the things are recovered. In my case, I just restart api-server through /etc/init.d/kube-apiserver (kill the process manually should do the same thing). Etcd is always running and the data in it is not lost.

**Comment by wb14123** [comment]
Any update on this? I cannot use kubernetes in production if this problem is not solved. Or do you have a work around, like define a service with the glusterfs endpoints?

**Comment by jonathan-kosgei** [comment]
I'm running into this too on GKE so I'm not sure if it's the api-server restarting, but just now after a loadtest and intermittently a couple of other times, after my app tries to come back up it failes to mount from gluster due to the gluster endpoints having mysteriously disappeared.

**Comment by thockin** [comment]
Do you mean the whole object disappeared or that it exists but is empty?

**Comment by thockin** [comment]
In the original YAML "IP" should be "ip"

**Comment by jonathan-kosgei** [comment]
`kubectl get endpoints` does not show the resource

**Comment by thockin** [comment]
I am trying to repro, but no luck so far.

**Comment by jonathan-kosgei** [comment]
Just checked.. IP is ip..it does come up, and it works well enough as the
pods are able to mount the gluster volumes, but every once in a while I
find that they're gone.

**Comment by jonathan-kosgei** [comment]
I haven't been able to either, it happens every once in a while. I think
maybe they're deleted before I notice and I only notice because a pod is
fails and on restart it fails to mount it's volume

**Comment by jonathan-kosgei** [comment]
Just checked a cluster I created an hour ago, and yup all the pods that had
been created are running smoothly but the gluster endpoints resource is gone

**Comment by thockin** [comment]
Interesting.

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L466-L487

It appears this is intentional.  If you create a service with `clusterIP:
None` and an empty selector, this will not be activated.  It is trying to
prevent submarine problems, such as creating an Endpoints then later
creating a Service and conflicting.

**Comment by jonathan-kosgei** [comment]
So the fix is to create a corresponding service for the endpoints?

**Comment by thockin** [comment]
Yes.  Endpoints are usually a derived value, and in hindsight they should
probably have been a sub-resource of Service.

**Comment by pcm32** [comment]
I'm getting this exact same behaviour as well. Glusterfs endpoint API object disappears every now and then, producing the error syncing pod mentioned here. Could you explain what do you mean by creating a service for the endpoint? Do you need to have the PV using the EP through the service? How do you link the service to the EP, through the selector of the service and some metadata on the EP? Thanks!

**Comment by pcm32** [comment]
In case you're wondering (like I was) how to attach a service to the EP the [documentation on glusterfs](https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/glusterfs) was updated to include an example service for it.

**Comment by jonathan-kosgei** [comment]
@thockin I'm having this issue again in a very different setup, basically I'm using the Nginx Ingress controller and it uses endpoints and these endpoints keep disappearing intermittently breaking all ingress to the cluster. Opened an issue at the nginx-ingress repo https://github.com/kubernetes/ingress-nginx/issues/1715.

Saving the endpoints with a `get -o yaml` and recreating them when resolution failure occurs fixes it immediately.

**Comment by smallWWhite** [comment]
> 你有一个名为的服务`glusterfs-cluster`吗？
> 
> 否则它应该持久化，就像任何其他API对象一样
> 
> 2015年8月19日星期三下午8:39，Bin Wang [notifications@github.com](mailto:notifications@github.com)写道：
> 
> > 这是我做的：
> > > kubectl create -f glusterfs-endpoints.yaml 
> > > 端点/ glusterfs-cluster
> > > cat glusterfs-endpoints.yaml 
> > > kind：端点
> > > apiVersion：v1 
> > > 元数据：
> > > name：glusterfs-cluster 
> > > subsets：
> > > 
> > > * 地址：
> > >   
> > >   * IP：192.168.1.1 
> > >     端口：
> > >   * 港口：1
> > > * 地址：
> > >   
> > >   * IP：192.168.1.2 
> > >     端口：
> > >   * 港口：1
> > 
> > 
> > 然后使用kubectl获取端点我可以看到这一行：
> > glusterfs-cluster 192.168.1.1:1,192.168.1.2:1
> > 但是在我重新启动kube-apiserver之后，这个端点就丢失了。
> > - 
> > 直接回复此电子邮件或在GitHub上查看
> > [＃12964（评论）](https://github.com/kubernetes/kubernetes/issues/12964#issuecomment-132875230) 
> > 。
this will make kubelet notready


> Do you have a Service named `glusterfs-cluster` ?
> 
> Otherwise it should persist, just the same as any other API object
> 
> On Wed, Aug 19, 2015 at 8:39 PM, Bin Wang [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Here is what I do:
> > > kubectl create -f glusterfs-endpoints.yaml
> > > endpoints/glusterfs-cluster
> > > cat glusterfs-endpoints.yaml
> > > kind: Endpoints
> > > apiVersion: v1
> > > metadata:
> > > name: glusterfs-cluster
> > > subsets:
> > > 
> > > * addresses:
> > >   
> > >   * IP: 192.168.1.1
> > >     ports:
> > >   * port: 1
> > > * addresses:
> > >   
> > >   * IP: 192.168.1.2
> > >     ports:
> > >   * port: 1
> > 
> > 
> > Then use kubectl get endpoints I can see this line:
> > glusterfs-cluster          192.168.1.1:1,192.168.1.2:1
> > But after I restart kube-apiserver, this endpoint is lost.
> > —
> > Reply to this email directly or view it on GitHub
> > [#12964 (comment)](https://github.com/kubernetes/kubernetes/issues/12964#issuecomment-132875230)
> > .

if i create a Service named glusterfs-cluster, after reboot  endpoint is not  lost.  but the kubelet will be notready , something wrong?  hope response    tks.

**Comment by hanqiulun** [comment]
The correct explanation should be When the cluster starts Endpoint-Controller Will check all
 Endpoint list Then put Endpoint name in work_queue, worker get value from work_queue, Found Endpoint no corresponding Service,Just delete Endpoint.

**Comment by realAndyLuo** [comment]
@hanqiulun 
Your explanation is super helpful! Can you please point me to the official doc?

**Comment by xulis** [comment]
I created the Endpoints and  Services,it worked well for a while,But not long after, Endpoints lost subsets:
```yaml
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-qa1
subsets:  
 - addresses:
    - ip: 10.10.1.4
   ports:
    - port: 3306
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-qa1
spec:
  selector:
    name: mysql-qa1
  ports:
  - port: 3306
```
Before things happen
```
kubectl get ep -n qa1 mysql-qa1
NAME        ENDPOINTS        AGE
mysql-qa1   10.10.1.4:3306   4d21h
```
After the incident
```
kubectl get ep -n qa1 mysql-qa1        
NAME        ENDPOINTS   AGE
mysql-qa1   <none>      4d21h
```

why...

**Comment by dongwangdw** [comment]
yes, the manually created EP resource will not be reconciled by the controller. This is the cause.
Usually we do not create EP, this kind of secondary resource directly. It is created for the corresponding service resource.
