### ISSUE TITLE
Skydns container keeps falling over

### ISSUE THREAD

**Issue by esecules** [kubernetes/kubernetes#12984]
I just tried updating to 1.0.3 and switched from consul to skydns 

The container only stays up for about 30 seconds and these are the last few lines in the container log.
``` 
2015/08/20 17:21:08 skydns: failure to forward request "read udp 10.0.0.10:53: i/o timeout"
2015/08/20 17:21:08 skydns: failure to forward request "read udp 10.0.0.10:53: i/o timeout"
2015/08/20 17:21:08 skydns: failure to forward request "read udp 10.0.0.10:53: i/o timeout"
2015/08/20 17:21:08 skydns: failure to forward request "read udp 10.0.0.10:53: i/o timeout"
2015/08/20 17:21:08 skydns: failure to forward request "read udp 10.0.0.10:53: i/o timeout"
2015/08/20 17:21:08 skydns: failure to forward request "read udp 10.0.0.10:53: i/o timeout"
2015/08/20 17:21:08 skydns: failure to forward request "read udp 10.0.0.10:53: i/o timeout"
2015/08/20 17:21:09 skydns: failure to forward request "read udp 10.0.0.10:53: i/o timeout"
2015/08/20 17:21:09 skydns: failure to forward request "read udp 10.0.0.10:53: i/o timeout"
2015/08/20 17:21:09 skydns: failure to forward request "read udp 10.0.0.10:53: i/o timeout"
```

**Comment by thockin** [comment]
Did you set the dnsPolicy flag for the kube-dns pod?  It looks like skydns is trying to talk to itself.

https://github.com/kubernetes/kubernetes/blob/v1.0.1/cluster/addons/dns/skydns-rc.yaml.in

**Comment by esecules** [comment]
I did not, It remains "Default"

**Comment by thockin** [comment]
"Default" is correct.  @artfulcoder

**Comment by esecules** [comment]
I was also seeing ```can not forward, name too short (less than 2 labels):``` Is this skydns enforcing ```service.namespace``` addressing?

**Comment by thockin** [comment]
the "can not forward" is not a big deal.

**Comment by esecules** [comment]
I have since reverted my main cluster back to 0.21.1 and I'm working on setting up a staging cluster for new releases.

Generally how stable is the skydns pod setup? I am coming from using a custom kube2consul program that was written for pre kuberentes v1.0.0. After upgrading I will have to choose whether to bring my kube2consul in line with the current state of the world, or try out the skydns which was still in development when I first started running kubernetes (around v0.17.0) and needed dns.

**Comment by thockin** [comment]
In general our DNS is rock solid - I have seen no problems with it except
weird configs, which is what I have to suspect here, but I don't know what
it might be off th etop of my head

**Comment by ArtfulCoder** [comment]
can you run the following
1. `cat /etc/resolv.conf` on this pod 
2. `cat /etc/resolv.conf` on the host
3. Is the skydns pod running with net=host ?
4. please give the command line args for skydns process.

**Comment by ArtfulCoder** [comment]
5. can you also print the endpoints for kubernetes dns service ?
`kubectl get ep --all-namespaces`

**Comment by ArtfulCoder** [comment]
@esecules let me know if you had a chance to address my previous comment.
If you are not facing this problem anymore, I would like to close this issue./

**Comment by ArtfulCoder** [comment]
Closing this issue.
Please re-open if you are still facing this issue.

**Comment by miry** [comment]
I had similar problem:

```
2015/12/16 17:39:12 skydns: failure to forward request "read udp 10.0.8.2:53: i/o timeout"
```

where `10.0.8.2` is DNS from AWS.

Built cluter with:

```
SERVICE_CLUSTER_IP_RANGE="10.247.0.0/16"
DNS_SERVER_IP="10.247.0.10"
KUBE_SUBNET_CIDR="10.0.8.0/24"
```

I think something wrong with routes in VPC.  So sky dns could not reach it.

**Comment by miry** [comment]
```
$ kubectl exec busybox -- traceroute 10.0.8.2   
traceroute to 10.0.8.2 (10.0.8.2), 30 hops max, 46 byte packets
 1  10.244.0.1 (10.244.0.1)  0.004 ms  0.003 ms  0.002 ms
2  *  *  *
 3  *  *  *
 4  *  *  *
 5  *  *  *
```

**Comment by daikaixian** [comment]
similar problem:

etcdmain: listen tcp: lookup localhost on 202.96.199.133:53: read udp 172.17.0.2:36311->202.96.199.133:53: i/o timeout

anyidea?

**Comment by daikaixian** [comment]
@ArtfulCoder

follow your comment,there is the output:

1.
# Generated by NetworkManager
search localdomain
nameserver 180.168.255.118
nameserver 202.96.199.133

2.
search localdomain
nameserver 180.168.255.118
nameserver 202.96.199.133
options ndots:5

3.  ?

4./skydns -machines=http://127.0.0.1:4001 -addr=0.0.0.0:53 -domain=mycluster.com

5.
NAMESPACE   NAME           ENDPOINTS            AGE
default     dns-svc-test                        13m
default     kubernetes     61.152.115.83:6443   41d


help me. please.

**Comment by stephanlindauer** [comment]
same problem with this setup:
https://github.com/stephanlindauer/terra-aws-core-kube

any news on this? any fixes @daikaixian @miry @esecules ?

**Comment by miry** [comment]
@stephanlindauer you can try https://github.com/kubernetes/kops/blob/master/docs/terraform.md.  I used to create a small test KB cluster via terraform.

**Comment by stephanlindauer** [comment]
hi @miry, thanks for the heads up. i tried that but i'd really like to utilize coreos the operating system, so kops is not really an option. :/

**Comment by luckywarrior** [comment]
skydns version older than 1.3 has the problem.It is because skydns will inherit the host's dns configure from  /etc/resolv.conf.To solved this problem just remove all the nameserver in host's /etc/resolv.conf,and restart skydns,or just update newer version after 1.3

**Comment by msavlani** [comment]
@luckywarrior : i dont think we should remove entry from hosts resolv.conf because that would cause many other problems like name resolution.

 @daikaixian @miry @esecules @stephanlindauer  : If you think IP for which connection issues are coming is your DNS IP and not skydns IP, then try to look at your iptables rules.
There are some issues related to IP routing  e.g : [#11204](https://github.com/kubernetes/kubernetes/issues/11204)

Take back up of your iptables and flush rules "iptables -F" and restart kubelet
