### ISSUE TITLE
Create an AggregatedValidationError type 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#12987]
Follow up https://github.com/kubernetes/kubernetes/pull/12837#issuecomment-133111549

Create an AggregatedValidationError type so that we could plumb the handling for validation errors all the way back to the caller.

**Comment by matthyx** [comment]
@janetkuo I am working on custom errors in OpenShift (https://github.com/openshift/origin/issues/9434) maybe it could be nice to coordinate the work and do this in a unified way?

**Comment by janetkuo** [comment]
@matthyx thanks, that would be very helpful!

**Comment by matthyx** [comment]
OK, I will work on that after Kubecon Berlin, where I will attend your talk!

**Comment by matthyx** [comment]
@janetkuo here is what I have so far... https://github.com/matthyx/kubernetes/tree/issue12987
I have reached out @deads2k for clarification as this custom error is useless if we don't do something with it...

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc
