### ISSUE TITLE
Make it easier to setup and debug cert issues

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#12991]
We need something like the debugging services doc (https://github.com/kubernetes/kubernetes/blob/4244a7cb2fff33d5e0c2081357abcd9324bb25af/docs/user-guide/application-troubleshooting.md) it keeps coming up on irc, email etc. People have a hard time with cert. They don't always use the getting-started scripts, and sometimes the script of that cloudprovider doesn't work. I usually point them at scratch.md, but that only helps 25% of the time.

@liggitt @erictune

**Comment by roberthbailey** [comment]
Have you seen https://github.com/kubernetes/kubernetes/blob/master/docs/admin/authentication.md#creating-certificates (from the recently merged https://github.com/kubernetes/kubernetes/pull/12702)?

We can clean it up if it isn't sufficient but it explains how to create certs if you aren't using a startup script.

**Comment by bprashanth** [comment]
There are 2 problems I think:

1. Setting up the cluster. We do a good job of elaborating on this in both scratch and the guide above.
2. After I've setup the cluster in what I believe is the correct way, the token is missing (https://botbot.me/freenode/google-containers/2015-07-31/?msg=46101611&page=11) or the ca.crt is missing (https://groups.google.com/forum/#!topic/google-containers/dDhlTIWS1pI) or things just don't work with cryptic x509 like messages (https://github.com/kubernetes/kubernetes/issues/11222, https://github.com/kubernetes/kubernetes/issues/12955).

I'm looking for something I can point at to deal with 2. Sometimes the solution is just: man openssl, while other times it's: you need a root-ca flag pointing at a pem.
