### ISSUE TITLE
Kube-ui don't show anything

### ISSUE THREAD

**Issue by liguangbo** [kubernetes/kubernetes#13009]
I have the same problem with the issue https://github.com/kubernetes/kubernetes/issues/12468
![image](https://cloud.githubusercontent.com/assets/13741813/9399774/91eceae0-47eb-11e5-9ffe-e2a57eef55b9.png)
The Kube-ui can send request for information, but can't get respond.
![image](https://cloud.githubusercontent.com/assets/13741813/9399786/c8428a50-47eb-11e5-8226-eb764adea8aa.png)
Is it a problem about auth policy of apiserver? Who can fix it? Thanks

**Comment by dalanlan** [comment]
Sorry about my misleading, if there is any.
Maybe we should not access the pod ip directly, yet via apiserver only.
Can you try something like `http://$master-ip:8080/ui` if possible? 
It should work if you get rid of https authentication.

**Comment by liguangbo** [comment]
Thank you! I can access the pod by `http://$master-ip:8080/ui`
