### ISSUE TITLE
Minion stopped taking the Pods to run

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#13019]
Kube-Api Server Output
 
    core@ip-10-20-30-29 ~/scripts_bh/yaml $ kubectl get nodes
    NAME           LABELS                                                                   STATUS
    10.20.30.191   kubernetes.io/hostname=10.20.30.191,servicegrp=heapster,udpservice=yes   Ready
    10.20.30.192   kubernetes.io/hostname=10.20.30.192,servicegrp=capp,udpservice=yes       Ready
    10.20.30.45    kubernetes.io/hostname=10.20.30.45,servicegrp=capp,stresstool=done       Ready
    
    core@ip-10-20-30-29 ~/scripts_bh/yaml $ kubectl get events
    FIRSTSEEN                         LASTSEEN                          COUNT     NAME                                        KIND      SUBOBJECT   REASON        SOURCE                   MESSAGE
    Fri, 21 Aug 2015 07:23:26 +0000   Fri, 21 Aug 2015 08:33:45 +0000   422       monitoring-heapster-controller13-kj4dv   Pod                   failedMount   {kubelet 10.20.30.191}   Unable to mount volumes for pod "monitoring-heapster-controller13-kj4dv_default": exit status 32
    Fri, 21 Aug 2015 07:23:26 +0000   Fri, 21 Aug 2015 08:33:45 +0000   422       monitoring-heapster-controller13-kj4dv   Pod                   failedSync    {kubelet 10.20.30.191}   Error syncing pod, skipping: exit status 32
    Fri, 21 Aug 2015 08:33:50 +0000   Fri, 21 Aug 2015 08:33:50 +0000   1         10.20.30.191                             Node                  starting      {kubelet 10.20.30.191}   Starting kubelet.
    Fri, 21 Aug 2015 08:33:50 +0000   Fri, 21 Aug 2015 08:33:50 +0000   1         10.20.30.191                             Node                  NodeReady     {kubelet 10.20.30.191}   Node 10.20.30.191 status is now: NodeReady
    Fri, 21 Aug 2015 08:33:51 +0000   Fri, 21 Aug 2015 08:34:01 +0000   2         monitoring-heapster-controller13-kj4dv   Pod                   failedMount   {kubelet 10.20.30.191}   Unable to mount volumes for pod "monitoring-heapster-controller13-kj4dv_default": exit status 32
    Fri, 21 Aug 2015 08:33:51 +0000   Fri, 21 Aug 2015 08:34:01 +0000   2         monitoring-heapster-controller13-kj4dv   Pod                   failedSync    {kubelet 10.20.30.191}   Error syncing pod, skipping: exit status 32

Kubelet Output from 10.20.30.191

    Aug 21 08:36:42 ip-10-20-30-191.ec2.internal kubelet[29515]: Mounting arguments: tmpfs /var/lib/kubelet/pods/836ea4b0-47d5-11e5-87f8-0a05e62dda5b/volumes/kubernetes.io~secret/heapster-token-oawgo tmpfs [rootcontext="unlabeled"]
    Aug 21 08:36:42 ip-10-20-30-191.ec2.internal kubelet[29515]: Output: mount: wrong fs type, bad option, bad superblock on tmpfs,
    Aug 21 08:36:42 ip-10-20-30-191.ec2.internal kubelet[29515]: missing codepage or helper program, or other error
    Aug 21 08:36:42 ip-10-20-30-191.ec2.internal kubelet[29515]: In some cases useful info is found in syslog - try
     Aug 21 08:36:42 ip-10-20-30-191.ec2.internal kubelet[29515]: dmesg | tail or so.
     Aug 21 08:36:42 ip-10-20-30-191.ec2.internal kubelet[29515]: E0821 08:36:42.221032   29515 kubelet.go:1190] Unable to mount volumes for pod "monitoring-heapster-controller13-kj4dv_default": exit status 32; skipping pod
    Aug 21 08:36:42 ip-10-20-30-191.ec2.internal kubelet[29515]: E0821 08:36:42.231368   29515 pod_workers.go:111] Error syncing pod 836ea4b0-47d5-11e5-87f8-0a05e62dda5b, skipping: exit status 32
    Aug 21 08:36:52 ip-10-20-30-191.ec2.internal kubelet[29515]: E0821 08:36:52.241548   29515 mount_linux.go:103] Mount failed: exit status 32
    Aug 21 08:36:52 ip-10-20-30-191.ec2.internal kubelet[29515]: Mounting arguments: tmpfs /var/lib/kubelet/pods/836ea4b0-47d5-11e5-87f8-0a05e62dda5b/volumes/kubernetes.io~secret/heapster-token-oawgo tmpfs [rootcontext="unlabeled"]
    Aug 21 08:36:52 ip-10-20-30-191.ec2.internal kubelet[29515]: Output: mount: wrong fs type, bad option, bad superblock on tmpfs,
     Aug 21 08:36:52 ip-10-20-30-191.ec2.internal kubelet[29515]: missing codepage or helper program, or other error
     Aug 21 08:36:52 ip-10-20-30-191.ec2.internal kubelet[29515]: In some cases useful info is found in syslog - try
     Aug 21 08:36:52 ip-10-20-30-191.ec2.internal kubelet[29515]: dmesg | tail or so.
    Aug 21 08:36:52 ip-10-20-30-191.ec2.internal kubelet[29515]: E0821 08:36:52.243125   29515 kubelet.go:1190] Unable to mount volumes for pod "monitoring-heapster-controller13-kj4dv_default": exit status 32; skipping pod
     Aug 21 08:36:52 ip-10-20-30-191.ec2.internal kubelet[29515]: E0821 08:36:52.252671   29515 pod_workers.go:111] Error syncing pod 836ea4b0-47d5-11e5-87f8-0a05e62dda5b, skipping: exit status 32

**Comment by kgrvamsi** [comment]
@bgrant0607  Can you please help me out on this?we tried getting the cluster up again but now kubelet on every minions stops running with the tmpfs issue

**Comment by nikhiljindal** [comment]
@kgrvamsi What is the cloud provider you are using and what is the script you used to bring up your cluster?

**Comment by kgrvamsi** [comment]
This is a Manual setup on Coreos @nikhiljindal

**Comment by bgrant0607** [comment]
@kgrvamsi Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for users to find answers to frequently asked questions and how to address common use cases. 

Either someone from the community or someone from the Kubernetes team will help you. We scan stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

**Comment by kgrvamsi** [comment]
@bgrant0607  here is the stackoverflow question raised on the same issue

http://stackoverflow.com/questions/32224046/minion-stopped-taking-the-pods-to-run-tmpfs-error

**Comment by bgrant0607** [comment]
@kgrvamsi Thanks for your patience. Trying to find someone to help you.

**Comment by kgrvamsi** [comment]
@bgrant0607 is this issue can be resolved ?so that i can decommission the servers which i kept them aside untill i see any solution to apply on those servers and get the cluster state back.

**Comment by bgrant0607** [comment]
@kgrvamsi There was a reply on stackoverflow a few days ago. Please follow up there if you still need help, or feel free to decommission the servers if you do not.
