### ISSUE TITLE
jsonpath_test.go flaky

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#13024]
After #12202 was merged, json path test became flaky:

jsonpath_test.go:47: in recursive name, expect to get "127.0.0.1 127.0.0.2 myself e2e", got "myself e2e 127.0.0.1 127.0.0.2"
FAIL
FAIL	k8s.io/kubernetes/pkg/util/jsonpath	0.049s

It fails in about 20% of runs.

**Comment by jszczepkowski** [comment]
The problem is with the following case:

 {"recursive name", "{..name}", nodesData, `127.0.0.1 127.0.0.2 myself e2e`},

It seems that operator ".." does not guarantee the order in which values are returned. Sometimes they are returned as "127.0.0.1 127.0.0.2 myself e2e", and sometimes as "myself e2e 127.0.0.1 127.0.0.2".

**Comment by piosz** [comment]
@daizuozhuo could you please take a look?

cc @brendandburns

**Comment by jszczepkowski** [comment]
@daizuozhuo I've commented-out the offending test-case. We still need the proper fix.

**Comment by daizuozhuo** [comment]
Sorry, I think happens because map iteration order is random . I will fix it as soon as possible.

**Comment by brendandburns** [comment]
This was fixed by #13031, closing.
