### ISSUE TITLE
Make it possible to disable collection of kubelet/docker logs

### ISSUE THREAD

**Issue by swalkowski** [kubernetes/kubernetes#13033]
When I run Kubernetes cluster on GKE, it generates a lot of system logs coming from docker and kubelet. Even if my cluster runs just a few pods, I can see dozens or hundreds of log entries per second available in Google Cloud Logging in docker and kubelet logs. This makes the actual logs from my application get lost among them, if I do not set appropriate filter. Also, I am afraid that collecting massive amounts of logs imposes unnecessary workload on fluentd pod in my cluster.

It would be good if I could just disable collection of kubelet/docker logs (and potentially other Kubernetes system logs) assuming that I do not want to have these logs exported.

**Comment by a-robinson** [comment]
@dchen1107: since you tend to have a vested interest in node debug-ability, what's the minimum you'd want to have available here? From GKE's perspective, our users typically have no interest in these logs, so turning them off by default, even without an easy option to re-enable them, makes sense. Any user sophisticated enough to want them shouldn't have problems SSH'ing to the node for them.

Is the story all that different in open-source kubernetes? Does anyone even care to have the kubelet and docker logs collected from the nodes? I've never used cloud logging to debug issues with them, it's always been easier to just SSH to the node. I'd lean towards not collecting them on the nodes in general.

Also cc @satnam6502 in case he has wisdom he'd like to impart

**Comment by satnam6502** [comment]
All I can say is that personally I have never accessed kubelet etc. logs "for real" when debugging -- as Alex says -- it is usually more direct just to SSH in. I would support not collecting these logs to improve cluster stability (but perhaps have a switch / technique to make it easy to collect them if the admin does care about this?).

**Comment by a-robinson** [comment]
One last call for @kubernetes/goog-node to complain, because I'm starting on this now

**Comment by a-robinson** [comment]
Also @jimmidyson

**Comment by vishh** [comment]
We want to avoid storing logs onto local disk in the future. In-order to
achieve that, we need the existing cluster level logging infrastructure to
work.
Can the GKE problem be solved by moving system logs to a separate namespace?

**Comment by a-robinson** [comment]
How far in the future? Unless that's intended to happen soon, collecting the kubelet and docker logs in the meantime offers little value with a nontrivial  resource (cpu+memory+egress) cost.

But yes, we can handle the system logs separately if we'd like. I think the most natural way would be to report them as compute engine logs, which could be done by adding an extra config option into the gcp output plugin.

**Comment by vishh** [comment]
On Thu, Sep 10, 2015 at 4:44 PM, Alex Robinson <notifications@github.com>
wrote:

> How far in the future? Unless that's intended to happen soon, collecting
> the kubelet and docker logs in the meantime offers little value with a
> nontrivial resource (cpu+memory+egress) cost.
>
#13846

> But yes, we can handle the system logs separately if we'd like. I think
> the most natural way would be to report them as compute engine logs, which
> could be done by adding an extra config option into the gcp output plugin.
>
Can we try this approach while we I try to get some consensus on the future?

**Comment by a-robinson** [comment]
@swalkowski -- just to confirm, do you think this fix will be sufficient for you? In GKE, logs from containers will be listed under Container Engine, while logs from Docker and the Kubelet will be listed under Compute Engine, with the logs for each effectively being entirely seperated in the log viewer.

**Comment by swalkowski** [comment]
Yes, this will be sufficient in terms of not polluting Container Engine logs with system logs. I am still concerned about unnecessary load on fluentd caused by exporting Docker and Kubelet logs so ideally it would be great not to export these system logs if a user is not interested in them. But this is of slightly lower priority.

**Comment by bamb00** [comment]
Hi, What's the status from this request?
Is this available in 1.7.x or higher?
Thanks.
