### ISSUE TITLE
kubectl export and clone

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#13038]
Forked from #11368.

Openshift has an "export" command that strips out fields typically set automatically by the system, or at least would be different for different instances of a resource, such as status, nodeName, clusterIP, etc.:
https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/export.go
https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/exporter.go

This would be useful for creating "clean" config files from live state, for cloning resources, and for creating replication controllers from pods (#11490).

I'd prefer to do the resource munging in the apiserver rather than in the client, either by adding subresources or query params.

**Comment by bgrant0607** [comment]
See also discussion in #7576

**Comment by bgrant0607** [comment]
I'm inclined to use a GET query parameter for export. That's what we'd also use for the more general field filtering #1459.

**Comment by pmorie** [comment]
@kubernetes/rh-cluster-infra @kubernetes/rh-ux 

Also, personally, DO WANT>

**Comment by kargakis** [comment]
This is added in https://github.com/kubernetes/kubernetes/pull/18101

**Comment by mikedanese** [comment]
This is closed but there is still no kubectl export. What's happening here?

**Comment by kargakis** [comment]
> This is closed but there is still no kubectl export. What's happening here?

@mikedanese there is `kubectl get --export`

**Comment by mikedanese** [comment]
@kargakis thanks!
