### ISSUE TITLE
hack/cherry_pick_pull fails if upstream push url is set to a safety value

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#13045]
My upstream push url was set to "dont_push_to_upstream", to prevent accidental pushing to upstream.

hack/cherry_pick_pull.sh was failing with

```
+++ Creating a pull request on github
Aborted: the origin remote doesn't point to a GitHub repository.
```

Workaround:

```
git remote set-url --push upstream http://github.com/GoogleCloudPlatform/kubernetes.git
hack/cherry_pick_pull.sh ...
git remote set-url --push upstream dont_push_to_upstream
```

**Comment by mikedanese** [comment]
@zmerlynn this is likely what i ran into.

**Comment by roberthbailey** [comment]
I hit this yesterday as well (see https://github.com/github/hub/issues/876).

**Comment by roberthbailey** [comment]
This is pretty annoying considering that we [tell everyone with write access to do this](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#keeping-your-development-fork-in-sync).

**Comment by justinsb** [comment]
I was planning on just changing the docs to include my workaround.  I could put it into the script, but messing with push urls feels pretty risky...

**Comment by roberthbailey** [comment]
It'd be even better if hub worked properly without the valid push_url. :)

Where in the docs were you going to add it? We could have our script check your upstream push_url and give you a warning if it isn't set.

**Comment by justinsb** [comment]
I was going to add it here: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md

But I think I like the idea of checking the upstream push_url better - much more immediately helpful!

**Comment by mikedanese** [comment]
cc @ihmccreery

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc
