### ISSUE TITLE
storage.Interface leaks error abstractions

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#13057]
`genericetcd` abstracts a key value store, but it does not transform the errors returned (which are needed by callers):

```
    if err := e.Storage.Create(key, obj, out, ttl); err != nil {
        err = etcderr.InterpretCreateError(err, e.EndpointName, name)
        err = rest.CheckGeneratedNameError(e.CreateStrategy, err, obj)
        return nil, err
    }
```

and 

```
    if err := e.Storage.Get(key, obj, false); err != nil {
        return nil, etcderr.InterpretDeleteError(err, e.EndpointName, name)
    }
```

are examples where lower level errors are converted to higher level conditions (because we Get before Deleting to check certain conditions).

Callers still have to handle etcd errors today.
### In general:

Our higher level kv abstraction is really `genericetcd`, so `storage.Interface` is only useful in the context that it provides the primitives `genericetcd` needs.  Having `storage.Interface` support base KV primitives is great, but the granularity of the `storage.Interface` should be matched to `genericetcd` (Or generickv).  An example is guaranteed update - a store that has a built in patch primitive like mongodb or can do JS on the server side would be _better_ at implementing the genericetcd.Update logic than `storage.Interface#GuaranteedUpdate` - so there is no point in having a lowest common denominator storage interface that makes a hypothetical generic KV impl slower than our generic etcd.

/rant

**Comment by lavalamp** [comment]
I agree the errors need to be abstracted away. Absolutely. My goal is that nothing under pkg/registry should care about the backing storage. StorageInterface should abstract away everything.

**Comment by smarterclayton** [comment]
To do that we'll need to change StorageInterface to do more of the things
that genericetcd is doing today.  We should probably clarify what those
parts are (guaranteed update, maybe delete).  Right now, the
StorageInterface is not the most efficient implementation for guaranteed
update of an object stored in a DB row, and it's likely that some of the
flows in genericetcd would be incorrect if a DB had to maintain
transactional state for a watch stream. That's partially why I'm opposed to
these refactorings prior to having a second, non etcd backing store - they
don't solve the etcd problem any better than the current code and cost
developer time in review.

On Tue, Aug 25, 2015 at 4:56 PM, Daniel Smith <notifications@github.com>
wrote:

> I agree the errors need to be abstracted away. Absolutely. My goal is that
> nothing under pkg/registry should care about the backing storage.
> StorageInterface should abstract away everything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13057#issuecomment-134720161>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by lavalamp** [comment]
@timothysc, who is experiencing pain over this merely by changing etcd clients.

**Comment by timothysc** [comment]
@lavalamp could you label area/storage please for tracking.

**Comment by saad-ali** [comment]
Removing sig/storage label since this is an etcd issue, not related to k8s volume plugin system.

**Comment by timothysc** [comment]
closing, this issue is old, and no longer applies post refactorings over the last year, and have other refactors coming post 1.6 release.
