### ISSUE TITLE
elasticsearch-logging pods each consumes ~500MB memory

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#13051]
We don't set memory limit for the elastic search cluster addon pods. They seem to be consume quite a lot of memory by looking at a cluster I just created. 
1. Is the high memory usage normal/expected?
2. Can we set a reasonable memory limit for these addon pods?

/cc @satnam6502, @kubernetes/goog-node

**Comment by satnam6502** [comment]
I looked into Elasticsearch memory consumption earlier and indeed I think that's just how it behaves -- and with the constant ingestion of system logs (as discussed with @dchen1107 and @a-robinson  ) I think the data store is going to be monotonically increasing until something bad happens. As a stop-gap measure we could not could not collect the system logs but we need a story for what to do for a system this is supposed to run for a long time that collects lots of logs.

**Comment by dchen1107** [comment]
Here are the reasons on why not setting memory limit for 1.0 release:
https://github.com/kubernetes/kubernetes/pull/10653#issue-92503401

But now we are working toward 1.1, and should re-examine the decision we made earlier.

**Comment by eduardobaitello** [comment]
Any news about this?

**Comment by crassirostris** [comment]
@eduardobaitello There's a [memory limit of 200MB](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml#L33) set up for fluentd-elasticsearch currently. Unfortunately, huge memory consumption is a known issue of the fluentd. As one of the possible solutions I can recommend taking a look at fluentbit and its [kubernetes installation](https://github.com/fluent/fluent-bit-kubernetes-daemonset)

Another thing is, kubernetes will soon not be responsible for the logging solution integration, I would recommend creating follow-up discussions in the [fluentd repo](http://github.com/fluent/fluentd) or in the [fluentd kubernetes deployments repo](github.com/fluent/fluentd-kubernetes-daemonset).

**Comment by eduardobaitello** [comment]
@crassirostris thanks for the quick feedback.

My question was due to Elastic Search memory usage, which is [unlimited](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/es-controller.yaml#L28) at this time, and using about 2GB RAM in my environment.

There is a recommendation for this setting?

**Comment by crassirostris** [comment]
@eduardobaitello Oh, sorry, I didn't look into the question properly!

We don't have an expertise in Elasticsearch installation, so I don't feel like recommending something. I would suggesting taking a look into existing deployments: https://github.com/fabric8io/elasticsearch-cloud-kubernetes or https://github.com/pires/docker-elasticsearch-kubernetes. Quick glance shows that they don't set Kubernetes limits, but rather limit Java heap size
