### ISSUE TITLE
logging: make namespace and labels fields in kibana

### ISSUE THREAD

**Issue by mcbain** [kubernetes/kubernetes#13066]
To search in kibana for a certain pod the namespace and labels would be very useful. 
Since kibana 4 allows to enter with a configured query all logs of pods of a resourceController could be easily filtered.

**Comment by kargakis** [comment]
@piosz

**Comment by crassirostris** [comment]
/sig instrumentation

@mcbain It should be exported already: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/td-agent.conf#L282

If it's not, please open a separate issue, since it's a bug

/cc @coffeepac
