### ISSUE TITLE
Should doc garbage collection strategy better

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#13065]
The garbage collection strategy has not been well doc (correct me if i'm wrong), which could bother users who have OOD issues badly.

My main concerns about gc comes to
- What would kubelet do with the volumes (hostPath, for instance) of the container precisely when it's gonna to remove a exited container. l'll bet It wont please the users whether kubelet cleans the volumes or not. Greater customization should be allowed here. 
- Should warn the users that an external garbage collection tool is not recommended since it would break kubelet's behavior.
- Since flag like `--maximum-dead-containers-per-container` has been provided to the users, what if we set it to 0? Would kubelet just accept this happily even it could hurt? 
- Is there still race condition (like break the pulling-image-process when gc) existing?

/cc @yujuhong  Seems you had a plan for this, i'm not so sure and just.. ding dong

**Comment by yujuhong** [comment]
@dalanlan, thanks for the suggestions and the PR! 

@pwittrock is working on documenting the GC policies (#8416). I am not sure about his progress, so I'll leave it up to him to either review your PR or work with you to incorporate your suggestions in his own :)
 We should address all your questions in the new documentation. In the meantime, I am closing this issue as a dup of #8416.
