### ISSUE TITLE
Get rid of last remnants of "create-external-load-balancer"

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#13070]
There's still a kubectl flag at least, maybe more.  would be nice to make it deprecated in v1.1 if it isn't already, or nuke it if it was already deprecated.

**Comment by JanetKuo** [comment]
It's only used in `kubectl expose`. Why should we deprecate this flag?

**Comment by thockin** [comment]
the name ties to the old implementation of load-balancers and is totally
obsoleted by --type for `expose`.  We need to do it in a compat-safe way,
so if we didn't think to deperecate it pre 1.0 we probably have to
deprecate it now, keep it for a year, and then kill it.  The longer we
wait, the more annoying it is :)

**Comment by JanetKuo** [comment]
@thockin: got it. I added a PR to deprecate it.
