### ISSUE TITLE
When kube-down the cluster,we need to umount the volume of pods.

### ISSUE THREAD

**Issue by huangyuqi** [kubernetes/kubernetes#13077]
when we run kube-down.sh to move a k8s cluster, we want a clean env to deploy a new cluster next time. https://github.com/kubernetes/kubernetes/pull/12075. we need to move all remains, includes volumes of pod. https://github.com/kubernetes/kubernetes/pull/12704
However, if we can add a command like "kubectl remove all pods", or  let Kubelet clean up volumes. It is better than writing script.
So i want to add a new command to remove all mount volumes, before kube-down a cluster.

**Comment by dalanlan** [comment]
Maybe i'm nuts, yet `kubectl` is, let's say like a "client" binary. 
It would be quite odd to me to call `kubectl remove sth` manually before i tear down the cluster.

**Comment by dalanlan** [comment]
btw, i guess `kubectl delete pods --all` would take care of that if you insist on manual operation.

**Comment by huangyuqi** [comment]
Thanks for your comment. I think that "kubelet" or "kubectl" can not apperceive the action of cluster down,  because it is carried out by script "kube-down.sh". So there are two ways to fix this issue, one is that before tearing down the cluster, delete the volume by the kubelte's api manually ; another is script.
In addition, we just want a clean enviroment for deployment. It is just a issue about deployment. So now i think that it is not necessary to add interface to kubelet or kubectl.

**Comment by resouer** [comment]
@dalanlan have we work out the kube-down in ubuntu cluster? I think add a  `kubectl delete pods --all` in kube-down make sense.

**Comment by dalanlan** [comment]
Fair enough. I'll send a pr tomorrow:)

**Comment by huangyuqi** [comment]
Hi, @dalanlan , with https://github.com/kubernetes/kubernetes/issues/13491 , i met two issues.

1. If the api-server is down of not working, the kube-down.sh script will exit.
1. The function `tear_down_alive_resources` should copy to the master node to execute. Not in the local machine.
```bash
function kube-down {
  source "${KUBE_ROOT}/cluster/ubuntu/${KUBE_CONFIG_FILE-"config-default.sh"}"
  source "${KUBE_ROOT}/cluster/common.sh"
  tear_down_alive_resources
  ii=0
  for i in ${nodes}; do
    {
      echo "Cleaning on node ${i#*@}"
      if [[ "${roles[${ii}]}" == "ai" || "${roles[${ii}]}" == "a" ]]; then
      ....
    }
    ((ii=ii+1))
  done
}
```
In this case, `kubectl.sh` and scripts included should copy to the master.

**Comment by dalanlan** [comment]
1. It's somewhat an odd case. I' ve send a follow-up pr to fix this anyway.
2. Definitely not.
