### ISSUE TITLE
Inconsistency in the API with persistentVolumes and persistentVolumeClaims

### ISSUE THREAD

**Issue by zakiva** [kubernetes/kubernetes#13096]
When I'm accessing persistentVolumes and persistentVolumeClaims, I'm getting nil instead of empty list of items, as happening in other entities when there are no items. 

{
  "kind": "PersistentVolumeList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/persistentvolumes",
    "resourceVersion": "198954"
  }
}

**Comment by nikhiljindal** [comment]
Yes, this seems like a bug.
I see an empty list when I access pods: ```api/v1/namespaces/default/pods/```
```
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/default/pods/",
    "resourceVersion": "233"
  },
  "items": []
}
```
And items is nil when I access persistent volumes: ```api/v1/persistentvolumes```
```
{
  "kind": "PersistentVolumeList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/persistentvolumes",
    "resourceVersion": "229"
  }
}
```

**Comment by bgrant0607-nocc** [comment]
Items shouldn't be tagged with omitempty:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L422
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L422

**Comment by bgrant0607-nocc** [comment]
cc @markturansky

**Comment by bgrant0607-nocc** [comment]
PersistentVolumeList and PersistentVolumeClaimList appear to be the only resource types with this problem.

**Comment by markturansky** [comment]
Please see #13590 for fix.
