### ISSUE TITLE
ReplicationControllers can deterministically assign distinct persistent volumes to pod replicas

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#13108]
This issue attempts to solve only the storage piece of #260.

Current:

* 1:1 binding between PVC:PV
* RC gives all replica pods the same PVC name.  Good for shared storage only.

Proposed:

* 1:N binding between PVC:PV
  * Change pvc.Spec.VolumeName to pvc.Spec.VolumeNames[]
  * Add pvc.Spec.Singleton to denote if a claim can be bound exactly once or many times (shared storage toggle)
  * Alternatively, add pvc.Spec.VolumeNames[] and leave VolumeName for backwards compatibility.  Singleton flag denotes which one to use for the binding.
* ReplicationController assigns annotations to pods
  * Each pod annotated with "rc/$PVC.name" where the value is $PV.Name

This suggested refactoring would leave responsibility with the RC (or other actor) to assign annotations in a manner appropriate with the pod it is creating (with regard to its role in the clustered service - Mongo/Redis/Zookeeper/Whomever).

@smarterclayton @thockin @kubernetes/rh-storage

**Comment by markturansky** [comment]
A little clarification:

* Preserve 1.0 API backwards compatibility
  * Add pvc.Spec.VolumeNames[] to internal & v1 types
  * Add pvc.Spec.Singleton to internal & v1 types
  * Remove pvc.Spec.VolumeName from internal
  * Use conversions to translate between v1 and internal types
  * Use internal pvc.spec.VolumeNames[] for binding

I believe the annotation naming convention "rc/$PVC.Name" -> $PV.Name holds up.  Only the RC managing pods with a specific label selector would assign that key.  Other pods with similar labels but weren't created by the RC would not have the annotation.

Using RCs already comes with the caveat (in the docs) to ensure pod label selectors don't overlap with each other.  The same applies here to prevent conflict on the annotation key.

Someone needs to burn down this strawman.  Otherwise, I think it can work successfully.

**Comment by markturansky** [comment]
@smarterclayton just had a conversation with @thockin and @saad-ali about this PR.  They would like to know if this PR as suggested has value apart from how it might be used in nominal services.  

It was Tim's opinion that solving the hostname issue in nominal services would potentially open a different way of allocating volumes than what this issue describes.   The implementation described in this issue can work, but it would potentially be thrown away later.

Is it useful generally to have RCs reliably give pods distinct volumes independent of how nominal services might be implemented?

**Comment by smarterclayton** [comment]
All the use cases I have today for nominal services overlap to some degree
with PVC.  The *identity* that comes with nominal service seems like it
maps to a single volume.  So similar in concept to what you describe above,
but if the pod identity flows down into the pod I think it would be better
for the pvc volume to be parameterized by identity.  I don't have a
concrete case today where I would use a replication controller where the
pod template stays the same, but gets a different volume (because I want to
reuse the volume with new pods that get created).

On Tue, Aug 25, 2015 at 5:50 PM, Mark Turansky <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> just had a
> conversation with @thockin <https://github.com/thockin> and @saad-ali
> <https://github.com/saad-ali> about this PR. They would like to know if
> this PR as suggested has value apart from how it might be used in nominal
> services.
>
> It was Tim's opinion that solving the hostname issue in nominal services
> would potentially open a different way of allocating volumes than what this
> issue describes. The implementation described in this issue can work, but
> it would potentially be thrown away later.
>
> Is it useful generally to have RCs reliably give pods distinct volumes
> independent of how nominal services might be implemented?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13108#issuecomment-134736588>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by markturansky** [comment]
@smarterclayton thanks.  It'll be interesting to see how the nominal services discussion plays out.  I'll close this issue.

**Comment by thockin** [comment]
FWIW I am not AGAINST this idea (it's similar in form to what I called
storage equivalence pools).  If we have a use-case for this level of
equivalence AND that use-case does not need the identity aspect, THEN maybe
this (or something like it) is useful on its own.
