### ISSUE TITLE
Cluster is unstable with REGISTER_MASTER_KUBELET=true

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#13102]
I created an e2e cluster with `REGISTER_MASTER_KUBELET=true`, and the master node is extremely unstable with docker/kubelet being restarted frequently.
I ended up *fixing* this by removing `/etc/supervisor/conf.d/docker.conf` to prevent docker from being restarted again. The cluster was stable and functioning after the fix.
Here are my questions:
 - Is REGISTER_MASTER_KUBELET=true supposed to work in this case, or was there any other configurations that I needed to change?
 - Do we run any e2e suite with master node registered?

The docker health check performed by supervisord seems defective on the master node in this case, but I am not sure why.

/cc @roberthbailey

**Comment by yujuhong** [comment]
@roberthbailey, this seems like a duplicate of #12776, so feel free to close it if you see fit.

**Comment by roberthbailey** [comment]
We've set REGISTER_MASTER_KUBELET=false to solve this temporarily, but I think we want to move back to a state where you can set it to true and have a functioning cluster (so I don't think it's a dupe of #12776) -- let's use this to diagnose / fix this flag and leave that one as the issue that stopped the bleeding. 

I can't tell if there was something wrong with my initial implementation or if the switch from monit -> supervisord caused the bad interactions that have been reported. I didn't see the apiserver crash looping when it was being monitored by monit.

**Comment by roberthbailey** [comment]
To answer your original questions:

1. Setting REGISTER_MASTER_KUBELET to true should be all that you need to do. 
1. I left it set to false in the e2e suites because not all of the e2e tests were passing with it set to true (not because the apiserver was crash-looping though).

@dchen1107 and @bgrant0607 mentioned elsewhere that we should register the master node but in an unscheduleable state. This will allow us to scrape metrics from the master (and see the mirror pods for the master components) but not schedule user pods on the master VM until we have better resource isolation to give us better assurance that the master components won't be starved for resources.

**Comment by yujuhong** [comment]
> I can't tell if there was something wrong with my initial implementation or if the switch from monit -> supervisord caused the bad interactions that have been reported. I didn't see the apiserver crash looping when it was being monitored by monit.

One major difference I can think of is that supervisord checks more frequently (10s vs. ~2min by monit). If both kubelet and supervisord want to restart docker, they could fight forever?

**Comment by yujuhong** [comment]
> @dchen1107 and @bgrant0607 mentioned elsewhere that we should register the master node but in an unscheduleable state. This will allow us to scrape metrics from the master (and see the mirror pods for the master components) but not schedule user pods on the master VM until we have better resource isolation to give us better assurance that the master components won't be starved for resources.

Agreed. We don't want other pods to schedule on the master for now.

**Comment by roberthbailey** [comment]
> If both kubelet and supervisord want to restart docker, they could fight forever?

It seems like a not-so-good design to have two parts of our system that are trying to start docker.

**Comment by mikedanese** [comment]
I don't think this is entirely a supervisord issue. That was a red herring. I didn't really explain it clearly in the earlier issue. Here is what is happening: 

1. master kubelet starts up with the default cidr specified [here](https://github.com/kubernetes/kubernetes/blob/9f32599beeb6e76bbe9fc38ef3fcfecb8aa843a0/cluster/aws/templates/salt-minion.sh#L29), `10.123.45.1/30`
2. apiserver starts
3. kubelet registers with apiserver and is assigned a different cidr by the api
4. kubelet ensures cbr0 [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container_bridge.go#L62) with the new assigned cidr and as a part of this process restarts docker
5. kubelet fails the docker healthz check since docker is killed and supervisord kills kubelet
6. kubelet comes up and the apiserver is down so it uses the default cidr, `10.123.45.1/30`
7. kubelet sees cbr0 is assigned to the previous apiserver cidr and ensures cbr0 with the default cidr
8. docker is restarted, kubelet fails health check, kubelet is restarted
9. goto step 1

There's a ton of error logs during this. For instance, since the master kubelet is schedulable and the default cidr only has room for 3 pods, There are a ton of "unable to assign ip errors". Also notice that stopping supervisord for a little while to let things reach steady state is enough to break the cycle.

hence the kubelet logs at --v=4:

```
root@kubernetes-master:/home/mikedanese# tailf  -n 1000 /var/log/kubelet.log | grep container_bridge
I0817 23:47:34.097818    3723 container_bridge.go:117] Want cbr0 CIDR: 10.244.0.1/24, have cbr0 CIDR: 10.123.45.1/30
I0817 23:47:34.098006    3723 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.244.0.1/24
I0817 23:47:34.153176    3723 container_bridge.go:58] Recreated cbr0 and restarted docker
I0817 23:48:04.695999    4559 container_bridge.go:117] Want cbr0 CIDR: 10.123.45.1/30, have cbr0 CIDR: 10.244.0.1/24
I0817 23:48:04.696042    4559 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.123.45.1/30
I0817 23:48:04.817674    4559 container_bridge.go:58] Recreated cbr0 and restarted docker
I0817 23:48:34.826903    4559 container_bridge.go:117] Want cbr0 CIDR: 10.123.45.1/30, have cbr0 CIDR: 10.123.45.1/30
I0817 23:49:04.039513    4936 container_bridge.go:117] Want cbr0 CIDR: 10.123.45.1/30, have cbr0 CIDR: 10.123.45.1/30
I0817 23:49:34.042020    4936 container_bridge.go:117] Want cbr0 CIDR: 10.244.0.1/24, have cbr0 CIDR: 10.123.45.1/30
I0817 23:49:34.042068    4936 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.244.0.1/24
I0817 23:49:34.104654    4936 container_bridge.go:58] Recreated cbr0 and restarted docker
I0817 23:50:05.358115    5805 container_bridge.go:117] Want cbr0 CIDR: 10.123.45.1/30, have cbr0 CIDR: 10.244.0.1/24
I0817 23:50:05.358147    5805 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.123.45.1/30
I0817 23:50:05.495230    5805 container_bridge.go:58] Recreated cbr0 and restarted docker
I0817 23:50:35.497820    5805 container_bridge.go:117] Want cbr0 CIDR: 10.244.0.1/24, have cbr0 CIDR: 10.123.45.1/30
I0817 23:50:35.497978    5805 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.244.0.1/24
I0817 23:50:35.553070    5805 container_bridge.go:58] Recreated cbr0 and restarted docker
I0817 23:51:04.515971    6695 container_bridge.go:117] Want cbr0 CIDR: 10.123.45.1/30, have cbr0 CIDR: 10.244.0.1/24
I0817 23:51:04.516018    6695 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.123.45.1/30
I0817 23:51:04.649771    6695 container_bridge.go:58] Recreated cbr0 and restarted docker
I0817 23:51:34.656008    6695 container_bridge.go:117] Want cbr0 CIDR: 10.244.0.1/24, have cbr0 CIDR: 10.123.45.1/30
I0817 23:51:34.656207    6695 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.244.0.1/24
I0817 23:51:34.717479    6695 container_bridge.go:58] Recreated cbr0 and restarted docker
I0817 23:52:04.633458    7320 container_bridge.go:117] Want cbr0 CIDR: 10.123.45.1/30, have cbr0 CIDR: 10.244.0.1/24
I0817 23:52:04.633617    7320 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.123.45.1/30
I0817 23:52:04.796951    7320 container_bridge.go:58] Recreated cbr0 and restarted docker
I0817 23:52:34.799890    7320 container_bridge.go:117] Want cbr0 CIDR: 10.244.0.1/24, have cbr0 CIDR: 10.123.45.1/30
I0817 23:52:34.800040    7320 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.244.0.1/24
I0817 23:52:34.848743    7320 container_bridge.go:58] Recreated cbr0 and restarted docker
I0817 23:53:04.767234    7990 container_bridge.go:117] Want cbr0 CIDR: 10.123.45.1/30, have cbr0 CIDR: 10.244.0.1/24
I0817 23:53:04.767360    7990 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.123.45.1/30
I0817 23:53:04.927161    7990 container_bridge.go:58] Recreated cbr0 and restarted docker
```

**Comment by roberthbailey** [comment]
How long do you need to stop supervisord to reach a steady state?

As mentioned above, monit was only doing a healthcheck every 2.5 minutes. supervisord is doing a healthcheck every 10s. I bet that the 2.5 minute interval was sufficiently long for this change to not create a cycle when I was originally testing it using monit.

**Comment by bgrant0607** [comment]
Kubelet should persist state it fetches from apiserver (aka checkpointing) #489. In this case the assigned cidr should be checkpointed, before reconfiguring Docker. Even tmpfs would survive a kubelet restart.

But, yes, it's suboptimal that we have 2 mechanisms restarting Docker.

And we shouldn't confuse liveness and readiness. Kubelet shouldn't die if Docker is down, assuming I'm interpreting the comments above correctly.

**Comment by roberthbailey** [comment]
> And we shouldn't confuse liveness and readiness.

Do you think the supervisord monitoring should only restart the kubelet if it isn't alive, but not restart it if it is alive but not ready? It seems like we could pretty easily get into a state where the kubelet is alive but never becomes ready.

**Comment by brendandburns** [comment]
For the master, we never need/use the CIDR that the second master assigns.  We should just disable the `--configure-cbr0` flag on the master kubelet.

The kubelet doesn't manage Docker health, it merely bounces it once, after it has configured the bridge.  Yes, it's sub-optimal that supervisord might also kill Docker in the same window, but it doesn't really matter...

--brendan

**Comment by brendandburns** [comment]
@roberthbailey is this fixed?

**Comment by dchen1107** [comment]
Agreed on https://github.com/kubernetes/kubernetes/issues/13102#issuecomment-135640097 made by @brendandburns 

I still hope we can have this fix in 1.1 and enabling master node register which highly improves our introspection.

**Comment by roberthbailey** [comment]
@brendandburns Not that I know of (I haven't had a chance to try and fix it).

**Comment by davidopp** [comment]
1.1 deadline is upon us -- what is the status of this issue?

**Comment by mikedanese** [comment]
This is in progress but will require API changes (see https://github.com/kubernetes/kubernetes/issues/14140#issuecomment-141574219).
