### ISSUE TITLE
Document max-pods

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#13112]
Hit irc at least twice: 
I have a beefy node, how do i test how many pods i can put on it? there seems to be a hard limit. 

Maybe we can append some text about max-pods and limit ranges to our large cluster or production pods docs? (https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/admin/cluster-large.md, http://kubernetes.io/v1.0/docs/user-guide/production-pods.html). Limits already have (https://github.com/kubernetes/kubernetes/blob/e366f2c597df57494c647dd5d0e99305d887b321/docs/admin/limitrange/README.md) but clearly not too findable.

@gmarek

**Comment by gmarek** [comment]
I don't see how this is related to the large cluster doc. I believe information about max pods belongs to docs/user-guide/compute-resources.md.

@bprashanth @bgrant0607 @davidopp WDYT?

**Comment by bgrant0607** [comment]
The LimitRange documentation was moved to docs/admin, but ResourceQuota was mistakenly left in docs/user-guide. We really should have the full documentation about how to create/update such limits in the admin guide, but user-relevant consequences should be described in the user guide. Using docs/user-guide/compute-resources.md as a home for the latter makes sense to me.

**Comment by bgrant0607** [comment]
cc @derekwaynecarr

**Comment by bprashanth** [comment]
Only reason I suggested large clustes doc is because there's a correlation between people setting up large clusters and doing things that break out of our safety-sandbox (i.e wanting to use more than max-pods, violate default limit range, use N cores for etcd etc). As long as we link from docs/admin I think they'd find it.

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
If anyone is still interested in following up this issue, consider opening it against kubernetes/kubernetes.github.io repository (or better, contribute a patch if you have time).
