### ISSUE TITLE
iptables based Kube-proxy should support NodePort

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#13123]
Creating a new issue since I couldn't find one already, but do close and redirect me if one already exists.

#9210 Replaced the userspace kube-proxy (behind a feature flag for now) but still has a bit to go before feature parity with the userspace proxy.  One missing feature is support for NodePort, which we've suggested can be implemented in iptables using a combined SNAT/DNAT rule which looks something like this:

SNAT: extIP -> nodeIP
DNAT: nodeIP:svcPort -> podIP:svcPort

**Comment by caseydavenport** [comment]
@thockin @Symmetric

**Comment by thockin** [comment]
I'm confused.  NodePorts are in and have worked for a week.  #12764

How are you observing that they don't work?

**Comment by caseydavenport** [comment]
Yikes, not sure how I missed #12764.  I'm seeing them not work right now, but it could be that I don't have the right code.

I'll close this for now on the assumption that I'm just not up to date, and re-open if I find a bug.  Thanks!

**Comment by thockin** [comment]
Please holler if you can make a case that doesn't work.
