### ISSUE TITLE
Update the link processing script to redirect the html preview links to kubernetes.io

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#13149]
As part of the file processing (for publishing docs to gh-pages) can you please update the scripts so that it finds and changes the 'HTML preview links' that are used to display the API files from within master (vs showing the html code)? 

For links to the API in the files that we publish to kubernetes.io, we want those links to open the version of the API docs what we've published in the site.

In short, can we please ensure that links like:
https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/v1.0.2/docs/api-reference/definitions.html#_v1_pod

Are changed to:
http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_pod

Example:
The [pods](http://kubernetes.io/v1.0/docs/user-guide/pods.html) topic still contains a link to the HTML preview on GitHub (#12728) but should instead point to 
http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_pod

Related (files that use these types of HTML preview links): #11569

Fixes #15337, #12728, & #11772

**Comment by RichieEscarez** [comment]
@thockin, @nikhiljindal, would either of you be able to help here while krousey is OOO?

**Comment by thockin** [comment]
I'm pretty slammed at the moment, but I'll put it into the hopper.  If
someone gets there first, that would be great.

**Comment by nikhiljindal** [comment]
Making this as P1 as multiple people are reporting this.
Ref https://github.com/kubernetes/kubernetes/issues/11772 and https://github.com/kubernetes/kubernetes/issues/12728

**Comment by krousey** [comment]
Just now noticing that this was assigned to me 12 days ago. Sorry.

**Comment by krousey** [comment]
There are a couple of problems I see with this.

 1. https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/pods.md is broken as it is. That link is already a dead link.

 2. The specific example you point out requires that we need to know that v1.0.2 maps to v1.0 in the resultant URL. Why is this? Would you always want us to drop the revision portion?

**Comment by nikhiljindal** [comment]
Re: 1. That link works fine for me.
Re: 2. I think thats correct. We just have v1.0 docs on kubernetes.io which we use for all v1.0.x versions.

**Comment by RichieEscarez** [comment]
Hi @krousey,

Re: #1. The source files just got moved: #15877 (so the link to the API object in master is now outdated)

Now that we are going to v1.1, anything in v1.0 no longer comes out of master and is now an archived doc set out on kubernetes.io (ie. v1.0 folder in the gh-pages branch).

But for our up coming v1.1, any links to the API docs while in kubernetes.io, should remain out on the site and point to the corresponding API docs published there (not back into the master branch of the github repo).

Re: #2. The only reason i mentioned the tag is because for any version, we should ensure that a doc points to it's corresponding version of the API before a version/tag gets cut. Otherwise it will always point to HEAD and if you are trying to view only that tagged set (ie referencing an archived version), you wont ever get pointed to the right version of the API.

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/15979
