### ISSUE TITLE
Mark node unschedulable before beginning eviction

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#13145]
It would be better if we record on the node the unschedulable nature of the node before we begin eviction (to guarantee no overlap).  This may not be necessary if we implement a garbage collector controller for pods assigned to nodes which don't exist.

**Comment by bgrant0607** [comment]
We should not do this. The unschedulable field is for administrative use. Reporting the node as not ready should be sufficient.

cc @gmarek

**Comment by smarterclayton** [comment]
He was the one who proposed it :)

NotReady would be the equivalent - it's possible we shouldn't try to evict
a node that is not marked as NotReady.  The situation here was guarding
against scheduling during eviction.  While that's no guarantee (and
NotReady should already be set before we begin eviction), we discussed
adding that check as an extra guard.

On Tue, Aug 25, 2015 at 2:32 PM, Brian Grant <notifications@github.com>
wrote:

> We should not do this. The unschedulable field is for administrative use.
> Reporting the node as not ready should be sufficient.
>
> cc @gmarek <https://github.com/gmarek>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13145#issuecomment-134679080>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by davidopp** [comment]
I agree this is not necessary. As @gmarek said when he suggested it:

>  I'm not sure it's currently needed, as eviction only happens when the Node is unhealthy (thus it's unchedulable), but it may be worth to do it now to be future proof.

Let's cross that bridge if we come to it.

**Comment by smarterclayton** [comment]
Ok, superseded by garbage collector and existing code.
