### ISSUE TITLE
Client negotiation is too aggressive, makes disconnected operation hard

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#13153]
Negotiation is only required when the server doesn't support the requested client version.  The requested client version is always known (whether default from code or specified by the user).  We should probably only negotiate in the presence of a failure to access an endpoint that should exist, or during a client action that mimics "establish config to new server".  On high latency connections, this may double the perceived delay for users which is also a usability concern.

Copied from comment on #9762

------------------------------------

I totally missed the implications here when reviewing this change, but this makes it difficult to run kubectl in a disconnected mode.  That's a significant usability issue (I can't run kubectl commands that deal with local files and can output content without contacting the server on a plane, for example).  Once we add export or other temporary working tools this becomes even more irritating.  OpenShift has more generate level commands (above and beyond run) that can work in dry run which now require a running server to work.  

We can work around it in individual commands (defer .Client until later()) but there may be a better way to solve it.

One option is to have negotiation only invoked when negotiation is required.  If the user specifies a version, negotiation isn't required unless the server doesn't support the version.  If the user has recorded a preferred version, negotiation also isn't required unless the server supports the version.  Those could be handled by a fallback pattern on error.  At minimum, we could negotiate lazily on the first connection.  However, we have code that uses the api version prior to connect.  If we wanted to do aggressive negotiation we could do it on a login or config create action.

**Comment by lavalamp** [comment]
Closing in favor of #13794, which has more commentary.

**Comment by liggitt** [comment]
Actually closing
