### ISSUE TITLE
Some Getting Started topics do not map to the navigation menu

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#13157]
Ive found that there are some lower-level getting started pages that are not yet mapped to the navigation menu. For navigational purposes (usability), we need to find and ensure all Getting Started topics are mapped to their corresponding parent containers in the nav menu so that their location gets indicated. To do this, the missing topics need to be listed in the nav_v1.0.html file, under their corresponding parent containers:
See the nested sections for "Local-machine Solutions", "Turn-key Cloud Solutions", or "Custom Solutions" in https://github.com/kubernetes/kubernetes/blob/gh-pages/_includes/nav_v1.0.html#L10.

Example: 
This page does not get mapped to the navigation menu:
"http://kubernetes.io/v1.0/docs/getting-started-guides/coreos/coreos_multinode_cluster.html" 
This page is the "mult-node cluster" link found in the TOC for the "Getting Started on CoreOS" page at http://kubernetes.io/v1.0/docs/getting-started-guides/coreos.html.

**Comment by RichieEscarez** [comment]
I did a quick compare and found several getting started topics that we do not include in the navigation menu. I know these should be reviewed and exposed only if we know they are up to date and working.

/docs/getting-started-guides/aws-coreos.md
/docs/getting-started-guides/aws.md
/docs/getting-started-guides/aws/kubectl.md
/docs/getting-started-guides/azure.md
/docs/getting-started-guides/binary_release.md
/docs/getting-started-guides/coreos/coreos_multinode_cluster.md
/docs/getting-started-guides/coreos/bare_metal_calico.md
/docs/getting-started-guides/docker-multinode/deployDNS.md
/docs/getting-started-guides/docker-multinode/master.md
/docs/getting-started-guides/docker-multinode/testing.md
/docs/getting-started-guides/docker-multinode/worker.md
/docs/getting-started-guides/fedora/fedora-calico.md
/docs/getting-started-guides/logging-elasticsearch.md
/docs/getting-started-guides/mesos.md
/docs/getting-started-guides/mesos-docker.md
/docs/getting-started-guides/rkt/README.md
/docs/getting-started-guides/ubuntu-calico.md

Today, we have one getting started topic that we want all to read/review (versus listing them all out - without guidance): http://localhost:4000/v1.1/docs/getting-started-guides/README.html

Ive created dynamic landing pages that correspond to the document above:
![image](https://cloud.githubusercontent.com/assets/11762685/10651615/74d3b688-7805-11e5-9fea-bbeb61f7386a.png)

For example this custom solutions landing page: http://kubernetes.io/v1.0/gs-custom.html

Each landing page dynamically lists the available options by pulling them from the navigation menu:
![image](https://cloud.githubusercontent.com/assets/11762685/10651648/b29080aa-7805-11e5-9879-4c8d696a5cf7.png)

If any of the GS topics listed above should be exposed and get displayed in these landing page lists, they should be added to the corresponding version's navigation menu (ie. nav_v1.0.html or nav_v1.1.html) [here](https://github.com/kubernetes/kubernetes/tree/gh-pages/_includes).

Topics are also listed here and if any above are exposed, they should be added in this doc too: http://localhost:4000/v1.1/docs/getting-started-guides/README.html

**Comment by bgrant0607** [comment]
This is obsolete.
