### ISSUE TITLE
Enumerating options on Load-balanced apiservers.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#13152]
Over time we've discussed several options regarding how we wish to provide active-active HA on the api-servers.  Currently "we"/Red Hat support this by updating the apiservers to use a common virtual IP(VIP) that is used by both an external load-balancer and is referenced by the kube-proxy and kubelet.  

However, in the past we have discussed other options, including leveraging a discovery service.

The goal of opening this ticket is to enumerate some of the ideas and to determine a common path forwards provided it makes sense. 

@lavalamp, @davidopp, @rrati, @wojtek-t

**Comment by lavalamp** [comment]
IMO, we already provide most of the mechanisms to accomplish this. apiservers populate a "kubernetes" service's endpoints with their IP addresses. We should leverage all the work we've put into making services work.

The remaining piece, as far as I see it, is to make clients (primarily kubelet & kube-proxy) periodically get and locally store this list; they can then use it on a reboot/restart to rejoin the cluster.

**Comment by timothysc** [comment]
@lavalamp The question I always have is: "Should the kubelet and proxy know any details at all, or simply rally through a VIP, or common endpoint?"  if so, why?

**Comment by lavalamp** [comment]
Downsides to VIPs etc:
* Requires either more advanced networking, or more services (load balancer). Seems SPOFy.
* We preach services to our users. If we can't use our own services for the things we need to do, then something is wrong. If we can't eat our own dogfood, we need to fix the dogfood, not make a special variety of dogfood that only we are allowed to eat.

**Comment by davidopp** [comment]
@mikedanese

**Comment by timothysc** [comment]
@lavalamp so what is your answer then for external clients?  Use NodePort and expose the introspective service?

**Comment by lavalamp** [comment]
We should expose apiserver to external clients the same way we expose all other services to external clients: NodePort or ExternalLoadBalancer.

**Comment by timothysc** [comment]
Right now the kubernetes introspective service is kind of a weird hard coded thing and it doesn't actually append additional endpoints from the looks of things.  b/c there is a hardcoded MasterCount=1 in the code which doesn't actually feed out anywhere.  Anyway that can be fixed.. 

So in summary we want to do the following: 
1. Fix to support appending, possibly expose mastercount.
2. Create Instructions on howto update the default endpoint to overwrite and expose using 'kubectl get services kubernetes -o json'  +  'kubectl replace'.  It's possible we may just want to pass this through default command line options on startup, or better yet feed in as a .json|yaml on startup.  
3. Update the proxy + kubelet to grab the endpoint list on startup and periodically update/renew and leverage.  Question here will be should we load-balance this? (A: Probably) but I fear re-creating a square wheel here.

**Comment by lavalamp** [comment]
> 1. Fix to support appending, possibly expose mastercount.

In the current system, every master has to know this count at start up, and agree on its value.

> 2. Create Instructions on howto update the default endpoint to overwrite and expose using 'kubectl get services kubernetes -o json' + 'kubectl replace'. It's possible we may just want to pass this through default command line options on startup, or better yet feed in as a .json|yaml on startup to expose NodePort|ExternalLoadBalancer settings.

The cert that the apiservers present to the world will need to be generated with the externally visible DNS name (or, shudder, IP address).

> 3. Update the proxy + kubelet to grab the endpoint list on startup and periodically update/renew and leverage. Question here will be should we load-balance this? (A: Probably) but I fear re-creating a square wheel here.

One extra detail: probably only kube-proxy needs to do this; kubelet can just remember the kubernetes service IP. Then kube-proxy will load balance for us.

**Comment by smarterclayton** [comment]
I think in all of our existing OpenShift customers will stick a load balancer (or two of them) either in IaaS or their own environments in front of the masters.  Our clients can't handle round robin DNS today on failures - that's an option as well for the future.

@lavalamp can we come up with another algorithm for endpoints that doesn't require a preconfigured # of masters?

**Comment by lavalamp** [comment]
@smarterclayton I'm sure we could hack something together using etcd... like each master creates a key (w/ short TTL) in a directory, and then to figure out how many there are, we count the keys.

**Comment by smarterclayton** [comment]
We don't do force time synchronization today, but each master could report
a time with its endpoints and other masters are free to purge it if it
expires.  It is unfortunate the masters have to write their endpoints
frequently.

On Wed, Aug 26, 2015 at 3:16 PM, Daniel Smith <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> I'm sure we could
> hack something together using etcd... like each master creates a key (w/
> short TTL) in a directory, and then to figure out how many there are, we
> count the keys.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13152#issuecomment-135128603>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by timothysc** [comment]
> We don't do force time synchronization today 
We explicitly listed in our installation steps on atomic host - https://access.redhat.com/articles/1353773

xref - https://github.com/kubernetes/kubernetes/pull/12124

**Comment by timothysc** [comment]
@jayunit100 per our discussions you can probably hit #1 pretty fast.

**Comment by jayunit100** [comment]
For now ignoring proxy part, just focusing on api server append on startup , will see how end points cleanup

**Comment by mikedanese** [comment]
> Fix to support appending, possibly expose mastercount.

If it's possible to rip out mastercount with this refactoring, we should do that.

**Comment by timothysc** [comment]
@mikedanese +1

**Comment by jayunit100** [comment]
true or false?  ripping out mastercount only has one consequence : stale api-server IPs would be floating around. 

thats what im seeing in the code so far, am playing more with it today and diving a little deeper.

**Comment by smarterclayton** [comment]
Yes, and those endpoints would show up in the individual kube-proxies.
Eventually, you could have the kube proxy potentially pointing to someone
else's server that listens on port X that starts getting your master
traffic from nodes.

On Mon, Aug 31, 2015 at 4:04 PM, jay vyas <notifications@github.com> wrote:

> true or false? ripping out mastercount only has one consequence : stale
> api-server IPs would be floating around.
>
> thats what im seeing in the code so far, am playing more with it today and
> diving a little deeper.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13152#issuecomment-136468355>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by lavalamp** [comment]
@jayunit100 if masters think there is 1 master and there are more than one, then they will constantly fight over writing the endpoints. If they think there are more masters than there really are, then you will end up with stale entries.

**Comment by jayunit100** [comment]
@lavalamp currently, yes, but that is only the case so long as we keep the `MasterCount` append statements, right?  The "mastercount" removal of endpoints is a side effect of the current list refresher implementation...  If a TTL based mechansim is used, the whole problem goes away ... right?

**Comment by smarterclayton** [comment]
I'm not sure a ttl mechanism justifies a special mechanism just for master
endpoints.  Our goal is to keep the list relatively pruned within a
window.  Having another component (endpoints controller?) check
reachability of masters might be a better solution.  I don't want to over
design this component before we consider self hosting (mirror pods ->
endpoints) or bootstrapping (where the bootstrapper would write the
endpoints).

Mirror pods might be an approach - if we create mirror pods for nodes that
approximate the masters we could also require them to check in.  We *could*
use a ttl for that, although we are trying not to put ttl in the critical
path for the API.

On Aug 31, 2015, at 9:43 PM, jay vyas <notifications@github.com> wrote:

@lavalamp <https://github.com/lavalamp> currently, yes, but that is only
the case so long as we keep the MasterCount append statements, right? The
"mastercount" removal of endpoints is a side effect of the current list
refresher implementation... If a TTL based mechansim is used, the whole
problem goes away ... right?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13152#issuecomment-136547585>
.

**Comment by jayunit100** [comment]
Regarding the `kubectl ...replace` instructions... Is that the preferred way to expose the loadbalancer NodePort 
 Or should we plumb the nodeport directly through as a command line option?

**Comment by timothysc** [comment]
Baby Steps, try a get and replace the of the object .json.

**Comment by jayunit100** [comment]
```
{
            "kind": "Service",
            "apiVersion": "v1",
            "metadata": {
                "name": "kubernetes2",
                "namespace": "default",
                "selfLink": "/api/v1/namespaces/default/services/kubernetes",
                "uid": "zzcc8d9d3b-517z-11e5-a002-3c970e4b8bbd",
                "resourceVersion": "7",
                "creationTimestamp": "2015-09-02T13:02:00Z",
                "labels": {
                    "component": "apiserver",
                    "provider": "kubernetes"
                }
            },
            "spec": {
                "ports": [{
                        "protocol": "TCP",
                        "port": 443,
                        "nodePort": 30291
                }],
                "type": "NodePort"
            }
}
```

**Comment by jayunit100** [comment]
This patch seems to work to fire up the service endpoint https://github.com/jayunit100/kubernetes/commit/1de3e94b98a8e3c767ef9beb151642a8ff7de79f on a nodeport. Its then curlable from the NodePort.  Seems like, so long as apiservers continue to  `Mapped service "default/kubernetes:" to endpoint 192.168.1.190:6443` .    I'll test some more tomorrow.

**Comment by jayunit100** [comment]
In particular, the error I'm getting is `E0904 10:11:56.307660   13442 event.go:195] Unable to write event: 'Post http://0.0.0.0:30291/api/v1/namespaces/default/events: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"' (may retry after sleeping)` .  I'm assuming this has something to do with the way requests may need to be encoded , not sure .

**Comment by jayunit100** [comment]
ok , progress, by switching from `http` -> `https`, its saying x509 error, so just a certs issue.

**Comment by pmorie** [comment]
:+1:

**Comment by jayunit100** [comment]
Thanks for the help pmorie ... Now just gotta fix x509 and we're all set

**Comment by jayunit100** [comment]
got another hint from tim, going to try to launch kubelet w/ a custom kubeconfig file which authenticates to the services by referencing the auto generated credentials in /var/run/kubernetes.  Im guess my problem is simply that: by default, if accessing w/o service endpoint, auth isn't really needed.

```
 76 users:
 77 - name: blue-user
 78   user:
 79     token: blue-token
 80 - name: green-user
 81   user:
 82     client-certificate: path/to/my/client/cert
 83     client-key: path/to/my/client/key
```

**Comment by jayunit100** [comment]
The following kubeconfig file (/opt/kube-creds2)
```
  1 apiVersion: v1
  2 kind: Config
  3 current-context: mycontext
  4 clusters:
  5 - cluster:
  6     insecure-skip-tls-verify: true
  7     server: https://192.168.1.190:30291
  8   name: myserver
  9 contexts:
 10 - context:
 11     cluster: myserver
 12     user: kubelet
 13   name: mycontext
 14 preferences: {}
 15 users:
 16 - name: kubelet
 17   user:
 18     token: kubelet
 19 - name: myuser
 20   user: {}
```

Along side the following tokens file (/tmp/token)

```
kubelet,kubelet,1
jayunit100,jayunit100,2
tstclair,tstclair,3
rsquared,rsquared,4
```
 
And this patch https://github.com/jayunit100/kubernetes/commit/626f68409500816531409504331bd07e9f7338b5 

Will allow this NodePort functionality to work.  

Should I try plumbing the NodePort functionality as a command line option ?   It appears that because of the immutability issue above, that might be a good way to go. 

Thanks to @pmorie @eparis @liggitt @timothysc for helping me figure this one out.  This certs stuff is tricky !  Im hoping to help maintain the docs around them in the future if i can keep learning more.

Next step: I can offer a pretty clean patch+docs/ update which describes how to setup minimal NodePort based api-server and test in a "real" cluster.

**Comment by timothysc** [comment]
@jayunit100 I debate if whether NodePort exposing, or leveraging @bprashanth ' s edge-proxy makes sense for the introspective service.

**Comment by jayunit100** [comment]
Can you clarify the "edge-proxy" alternative ? I can try that one out as well if needed.

**Comment by timothysc** [comment]
cross-ref https://github.com/kubernetes/contrib/tree/master/service-loadbalancer

**Comment by jayunit100** [comment]
ok folks.  we can close this and move to the above WIP PR.  I've plumbed the nodeport option through and updated `hack/local-up` to demonstrate the way it works.

**Comment by davidopp** [comment]
@jayunit100 can we close this issue?

**Comment by jayunit100** [comment]
Yes this can be closed.  The new option allows for loadbalanced access via nodeport.
In the future if we iterate on using it we can open a new issue .

**Comment by jayunit100** [comment]
@timothysc to confirm .....

**Comment by timothysc** [comment]
yes please close.
