### ISSUE TITLE
Vagrant provisioner fails with "cluster/../cluster/../cluster/vagrant/util.sh: line 267: KUBECONIG: unbound variable"

### ISSUE THREAD

**Issue by Symmetric** [kubernetes/kubernetes#13164]
in commit 43821684, the following typo was introduced:

```
267     echo "The user name and password to use is located in ${KUBECONIG}"
```

Looks to be benign, since that's the last thing the provisioning scripts do, but the user does get a backtrace.

PR incoming to fix this...

**Comment by yujuhong** [comment]
Thanks for reporting. This has just been fixed by #13154
