### ISSUE TITLE
URLs that only point to a GitHub directory do not show in the navigation menu on kubernetes.io

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#13162]
**Problem**

URLs that do not specify the full URL (URLs that point to a directory and exclude the filename README.html), do not display in the navigation menu. 

In the GitHub repo, the corresponding REAME.md file automatically opens. On GitHub Pages where Kubernetes.io is hosted, corresponding index.html files get displayed (someone has added in renamed copies of the README files (index.html) to avoid 404 errors) but those URLs are not listed/found in the navigation menu. We can only define a single URL in the navigation menu, either */README.html or *index.html. 

**Example**

Example of incomplete URL:  
"http://localhost:4000/v1.0/examples/guestbook-go/", which is found in the "go implementation" link at the top of http://localhost:4000/v1.0/examples/k8petstore/README.html

**Solutions**

In order to get the navigation menu to recognize the incomplete URLs, we need to either:

(1) Fix each URL (although we might continue to see these errors since this is a GitHub repo convention):

 * Since the GitHub repo contains the README.md files, we can update each URL in all of the source .md files to include the missing README.md filenames.  

(2) Programmatically detect the URL and find the topic in the nav menu (possibly more effort but will resolve the commonly used GitHub convention if used in the future):

 * Add in some javascript to detect these types of URLs, assume the URL is missing "README.html", and then automatically append "README.html" the URL so it maps to an entry in the nav menu.  
    * This should happen in the [findcurnavitem()](https://github.com/kubernetes/kubernetes/blob/gh-pages/_layouts/docwithnav.html#L18) function so that each time it is called the URL will match entries in the navigation menu (so it gets highlighted and automatically scrolled to).

**Comment by bgrant0607** [comment]
This is obsolete.
