### ISSUE TITLE
Document that CoreOS clusters can be created on GCE using the standard cluster/kube-up.sh

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#13168]
The fact that we have a reasonably well-supported script for setting up a multi-node CoreOS cluster on GCE is either not present in our docs or very hard to find (since I haven't seen it). This leads users to try less well-supported solutions, as occurred in #13073.

There are so many CoreOS-related options in our [getting-started-guides](https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides) that it's kind of crazy. Ctrl+F finds 33 occurrences of CoreOS on that page, and we link to a whole bunch more in https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos.md

We should rationalize these to a less overlapping set of options that are less likely to fall out of date.

@erictune

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
AFAIK, kube-up.sh is no longer a good way to create kubernetes clusters. I vote for closing this issue (and opening similar issues in the future on kubernetes/kubernetes.github.io repo).

**Comment by chenopis** [comment]
IMHO, since all the docs now live in the k8s.io repo, any docs issue pre-2017 should be closed.
