### ISSUE TITLE
kube-start.sh error: "KUBECONIG: unbound variable"

### ISSUE THREAD

**Issue by technosophos** [kubernetes/kubernetes#13166]
At the end of running a vagrant provision on OS X, the kube-start command produces the following error: `./cluster/../cluster/../cluster/vagrant/util.sh: line 263: KUBECONIG: unbound variable`

Looks like it should be `KUBECONFIG`.

**Comment by yujuhong** [comment]
Thanks for reporting. This has just been fixed by #13154
