### ISSUE TITLE
Automated policing of `release-1.0` for non-cherry-pick PRs

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#13167]
We need to keep the release branch free of non-cherry-pick PRs in general, but the GitHub UI doesn't throw it in peoples faces, so things like #12939 slip in (and I've had to close 2-3 others). This is probably a good use for bots.

@brendandburns, up for a little more automation?

**Comment by ihmccreery** [comment]
I maybe makes sense to do this as part of kubernetes/contrib#156, and just have the release merge-bot ignore/warn on non-cherry-pick PRs.

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc
