### ISSUE TITLE
Performance improvement in ProxyLoop by goroutine 

### ISSUE THREAD

**Issue by roackb2** [kubernetes/kubernetes#13176]
I found that running our web on Kubernetes is a little bit slower and seems related to kube-proxy, so I'm trying to improve performance of it. 

Digging into the code, at `/pkg/proxy/userspace/proxysocket.go`, in the `tryConnect` function, there's a TODO:

``` go
// TODO: This could spin up a new goroutine to make the outbound connection,
// and keep accepting inbound traffic.
```

And I think it would be better if we could, in the function `ProxyLoop`, extract the part of tryConnect to a function and run it as goroutine, which enables the loop to accept new inbounds quicker. 

Could I make a pull request for this? Or this would cause some problem? 
I tested this change and run it on our own cluster, and seems working fine.

Though I read the development guide, if I'm doing anything wrong, please let me know, thanks in advance.

**Comment by resouer** [comment]
@roackb2 any PR is welcome, but I think Tim is already doing something to eliminate userspace proxy, which will improve Service performance remarkably, so ping @thockin

**Comment by thockin** [comment]
We will have both the userspace and iptables proxy modes for a while, so performance improvements on kube-proxy are welcome, if they are reasonably simple.

**Comment by roackb2** [comment]
Ok, thanks for your reply.
