### ISSUE TITLE
Auto-create replication cotroller first when using '-f' to expose it.

### ISSUE THREAD

**Issue by hurf** [kubernetes/kubernetes#13173]
When using `kubectl expose -f nginx-controller.yaml --port=80 --target-port=8000` to expose an rc, if the rc is not created yet, it will report `Error from server: replicationControllers "nginx-controller" not found
`.
Can we create the rc first instead of throw this error? Since `-f` implies that resource has been passed to the command and `expose` actually does a `create` work.

@kubernetes/kubectl @feihujiang

**Comment by smarterclayton** [comment]
I don't think we should create an RC in this case.  The user can kubectl
create -f nginx-controller.yaml.  In this case it's clear the user might
want to create that object.  In other contexts (reading a directory) it's
more likely an error.  We should require explicit input to create something
since it's not much harder to run oc create.

On Tue, Aug 25, 2015 at 10:08 PM, Victor HU <notifications@github.com>
wrote:

> When using kubectl expose -f nginx-controller.yaml --port=80
> --target-port=8000 to expose an rc, if the rc is not created yet, it will
> report Error from server: replicationControllers "nginx-controller" not
> found
> .
> Can we create the rc first instead of throw this error? Since -f implies
> that resource has been passed to the command and expose actually does a
> create work.
>
> @kubernetes/kubectl <https://github.com/orgs/kubernetes/teams/kubectl>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13173>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by hurf** [comment]
Whether the input is a file or a directory, `expose` only accepts one single resource, if multi-resources inputted, `expose` will return an error. Acutually `expose` is always dealing one resource, so I think create the rc when reading a directory wouldn't bring an error. 

Indeed it's not hard to use `create` command first, I'm just trying to make it more convinient for users.

**Comment by smarterclayton** [comment]
We generally don't do it anywhere else (scale, label, annotate).  I don't
think it's necessary for adding it to those commands, so we don't want to
introduce an inconsistent (surprising) behavior to just one command.

On Aug 26, 2015, at 3:37 AM, Victor HU <notifications@github.com> wrote:

Whether the input is a file or a directory, expose only accepts one single
resource, if multi-resources inputted, expose will return an error.
Acutually expose is always dealing one resource, so I think create the rc
when reading a directory wouldn't bring an error.

Indeed it's not hard to use create command first, I'm just trying to make
it more convinient for users.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13173#issuecomment-134859076>
.

**Comment by kargakis** [comment]
The resource builder is enough for creating the input object in the client without existing in the server - submitted a fix for this

**Comment by hurf** [comment]
@smarterclayton - I also looked these commands before, only got a feeling that `expose` should do so. The reason may be`expose` is creating something, `scale, label, annotate` are patching.

Anyway it's not a critical issue, and inconsistence is also a problem, so I'm okay not creating it first.
