### ISSUE TITLE
Clarify documentation about `kubectl expose` 

### ISSUE THREAD

**Issue by hurf** [kubernetes/kubernetes#13178]
In the document, `expose` should take rc and service as input. I tried `kubectl expose po nginx --port=80 --target-port=8080` and `kubectl expose -f pod-nginx.yaml ...`, they all worked (when pod has labels).

Another thing is, in `expose` command, service name is duplicated from input resource name(when `--name` is not specified), if service with same name already exsits, it will return an error. Can we give the service a unique name as rc does to the pods it manages.

@kubernetes/kubectl @feihujiang

**Comment by feihujiang** [comment]
@hurf OK, I'd like to fix the first bug.

**Comment by hurf** [comment]
Just noticed in [test-cmd.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/test-cmd.sh#L668), does that mean `pod` is also a acceptable input for `expose`? In this case we should modify the document.

Still we should check the resouce first, though for other resources the command will return an error because they don't have label selector. But we don't need to go that far to get the error.

**Comment by jlowdermilk** [comment]
I believe expose works for any of `pod|service|rc`. We should probably document that in the help text.

**Comment by hurf** [comment]
Closing since it's fixed.
