### ISSUE TITLE
Problem with setting policy config at kube-scheduler

### ISSUE THREAD

**Issue by lzephyr9** [kubernetes/kubernetes#13195]
I'm running k8s cluster on Centos  VMs (1 master and 2 minions). 
If add "--policy-config-file=/var/lib/policy/scheduler-policy.json" to KUBE_SCHEDULER_ARGS in /etc/kubernetes/scheduler file and did systemctl daemon-reload and systemctl restart kube-scheduler
From log I can see creating scheduler with algo provider 'DefaultProvider', creating scheduler with fit predicates 'map[HostName:{} ... and priority functions 'map[LeastRequestedPriority:{} BalancedResourceAllocation:{} ServiceSpreadingPriority:{}]

However if I run the same command (i.e. /usr/bin/kube-scheduler --logtostderr=true --v=4 --master=<master-ip>:8080 --policy-config-file=/var/lib/policy/scheduler-policy.json) on command line 
can see creating scheduler with fit predicates 'map[HostName:{} ... and priority functions 'map[ServiceSpreadingPriority:{} LeastRequestedPriority:{} BalancedResourceAllocation:{} ] instead
In scheduler-policy.json just shifted ServiceSpreadingPriority before LeastRequestedPriority and BalancedResourceAllocation

 If  edit unit file for scheduler n add --policy-config-file=/var/lib/policy/scheduler-policy.json right under /usr/bin/kube-scheduler, did a systemctl daemon-reload and systemctl restart kube-scheduler, it can work correctly

There is difference running scheduler with "sudo -u kube /usr/bin/kube-scheduler %OPTIONS%  --policy-config-file=..." and "sudo -u kube /usr/bin/kube-scheduler --policy-config-file=... %OPTIONS%" 

The 1st one will just display 0.217.x.x:8080 and address already bind and ended
whereas the 2nd one will display 0.217.x.x:8080 and address already bind and continue create scheduler from config, registering predicate and registering priority

Options order shouldn't matter, correct? Pls advise. Thanks

**Comment by timothysc** [comment]
@ConnorDoyle want to triage this please.
