### ISSUE TITLE
AWS & Coreos broken

### ISSUE THREAD

**Issue by xsamurai** [kubernetes/kubernetes#13190]
It seems coreos cluster is not currently deployable with the current configuration.  Reviewing the code in cluster/aws/utils.sh :

 815    grep -v "^#" "${KUBE_ROOT}/cluster/aws/templates/common.sh" 
  816     grep -v "^#" "${KUBE_ROOT}/cluster/aws/templates/format-disks.sh"
 817     grep -v "^#" "${KUBE_ROOT}/cluster/aws/templates/setup-master-pd.sh"
 818     grep -v "^#" "${KUBE_ROOT}/cluster/aws/templates/create-dynamic-salt-files.sh"
 819     grep -v "^#" "${KUBE_ROOT}/cluster/aws/templates/download-release.sh"
 820     grep -v "^#" "${KUBE_ROOT}/cluster/aws/templates/salt-master.sh"

Both common.sh and format-disk have apt-get or dpkg statements that fail on coreos systems, I also noticed that the default user in aws/coreos/util.sh is ubuntu, I've submitted a pull request for that in #13185 .  I'm curious if i'm missing something or a coreos cluster deployment has not been done or is broken.

**Comment by yujuhong** [comment]
cc @pires

**Comment by pires** [comment]
@yujuhong this is not related to the ways I maintain but rather the official way of using `kube-up.sh`.

**Comment by xsamurai** [comment]
Judging from the code in aws/utils.sh it assumes all supported distros are debian based, either templates get divided into templates/debian and templates/coreos or the code gets adjusted to take appropriate actions based on the value of KUBE_OS_DISTRIBUTION.  Also I consider myself a novice with coreos but coreos isnt really made to download packages off the net and install them, it is designed to run everything inside a docker container and that might be the perfect , simpler alternative.  I use a similar method with python and aws binaries by running them in a container and creating bash scripts that runs those containers, for example the file /usr/bin/aws contains the following line of code: 

docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY privaterepo/ops:python-aws-1.0 aws "$@"

Unless I'm missing something and coreos works just fine with the current code base, I don't mind getting my hands dirty and doing the work to get coreos working properly.

**Comment by yujuhong** [comment]
> @yujuhong this is not related to the ways I maintain but rather the official way of using kube-up.sh.

Thanks for the clarification! 

/cc @justinsb

**Comment by xsamurai** [comment]
Any update on this ?

**Comment by vyshane** [comment]
@xsamurai I've had better luck with the [coreos-kubernetes](https://github.com/coreos/coreos-kubernetes) project that the CoreOS team maintains.

**Comment by pires** [comment]
@vyshane that's the official way nowadays - or it's becoming that way. The CoreOS team has been overtaking that effort.

**Comment by justinsb** [comment]
We're not going to making further changes in kube-up.  Solutions for CoreOS are kube-aws, kubeadm, and likely kops soon (see https://github.com/kubernetes/kops/pull/854).  Closing.
