### ISSUE TITLE
Check for Partitions before formatting in SafeFormatAndMount

### ISSUE THREAD

**Issue by swagiaal** [kubernetes/kubernetes#13212]
'diskLooksUnformatted' in 'SafeFormatAndMount' (#8530) should check if disk is partitioned before formatting. So if a user mistakenly enters /dev/sdb instead of /dev/sdb1 we don't format the disk.

**Comment by BugRoger** [comment]
The manual provisioning of volumes is already tedious. Even more so if the volumes need to be partitioned before they can be used. 

Imo this defeats the point of the automatic mounting/formatting. At least I am just using whole devices without partitions to easy my life.

**Comment by swagiaal** [comment]
@BugRoger this is not adding a partitioning requirement. Partitions are already supported and you can use them in your pods. This is just saying that if you specify /dev/sdb and the format function finds that this disk has partitions then assume that the user made a mistake. ie they meant /dev/sdb1 or something. Otherwise we will format the entire drive and lose partitions. Come to think of it 'file' should be able to see that there are partitions on a drive. I'll look into that.

**Comment by kyzh** [comment]
@swagiaal could the behaviour beerroring out instead of making the decision to use /dev/sdb1.
Fixing the root cause will make it safer in the long run.

**Comment by swagiaal** [comment]
@kyzh Yeah that's the idea

**Comment by pmorie** [comment]
@kubernetes/rh-storage

**Comment by rootfs** [comment]
Or we make partition part of the API like [gce pd does](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L434).
