### ISSUE TITLE
What is the K8s project layout methodology?

### ISSUE THREAD

**Issue by jaytaylor** [kubernetes/kubernetes#13217]
How is it decided when a package goes into a  /pkg/<package> directory vs. keeping it flat?

I'd like to understand the rule being followed for the code structure throughout this project.

**Comment by mikedanese** [comment]
See #4851

**Comment by jaytaylor** [comment]
Roger that, thank you @mikedanese !

**Comment by mikedanese** [comment]
Feel free to comment or propose a reorg. It's put together pretty haphazardly at the moment but it's on our radar. Sorry we don't have a better answer!
