### ISSUE TITLE
e2e tests may fail if one of the nodes is unreachable

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#13219]
In this Jenkins run:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/8226/consoleFull
there are 10 failed tests. 
From the logs, it seems that at some point node e2e-gce-minion-gkwy became unreachable. After that, a bunch of tests failed.

I started looking into it and at least some of them may fail if a node is unreachable.
For example all PD tests will fail if first node returned from the LIST nodes operation will be unreachable:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/pd.go#L61
(we don't check whether that node is healthy).

We should also check the other tests is that run.

**Comment by wojtek-t** [comment]
cc @quinton-hoole @kubernetes/goog-testing

**Comment by quinton-hoole** [comment]
We should also figure out why the node is becoming unreachable.  I'm not a big fan of having the tests all pass if one of them causes a node to become forever unreachable.

**Comment by wojtek-t** [comment]
Definitely - this is equally important.

**Comment by wojtek-t** [comment]
Increasing the priority of it to P0.
We had a bunch of tests failing, because some Kubelet "stopped posting its status". This seems to be a very serious regression.

cc @dchen1107 @yujuhong

**Comment by wojtek-t** [comment]
To give more details, another example of node being down:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/8237/

**Comment by yujuhong** [comment]
It seems to me that `should be able to delete nodes` test in resize.go deleted node `e2e-gce-minion-jpxm`, and didn't successfully restore the node to the healthy condition. It failed the after-test check.
