### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JimTravisGoog** [kubernetes/kubernetes#13228]
http://kubernetes.io/v1.0/docs/admin/kubelet.html

"echanisms" instead of "mechanisms".

**Comment by resouer** [comment]
An old typo, docs need to be re-generated

**Comment by bprashanth** [comment]
@JimTravisGoog @resouer please send pr

**Comment by JimTravisGoog** [comment]
No need for a PR, the docs are correct on GitHub. They just need to be
sync'ed up to the docs site.
