### ISSUE TITLE
Issue with livenessProbe

### ISSUE THREAD

**Issue by roman-shuhov** [kubernetes/kubernetes#13226]
Hi, i spot weird issue with livenessProbe. You can see pod description here https://gist.github.com/roman-shuhov/d5d6c230bb3b86b639be .

I tried to create this pod and it kept restarting, and kubectl describe showed the following error:

``
Liveness probe failed: Get http://website-example-a:80/watcher.html: dial tcp: lookup website-example-a: no such host
``

So, looks like if "host" value is specified in livenessProbe (as in the example above), kubernetes is trying to fetch url http://<host>/<path> instead of sending host as a HTTP header. 

You can actually see this logic in the source code - https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/prober/prober.go#L205

The problem is that in this case this request go to the random pod (because it goes through load balancer), so if kubernetes have a bad pod it may kill a healthy one instead.

I think this logic should be changed, because i don't see any reason to make http://<host>/<path> request for the livenessProbe.

**Comment by roman-shuhov** [comment]
Is it really P2? I think this issue may seriously affect running services...

**Comment by thockin** [comment]
I don't think that is what the `host` field was meant to do, but it's an interesting interpretation.  The host field was meant to allow you to proxy health through a different Service or something that had higher-level visibility into the overall health.

**Comment by therc** [comment]
This should at least be better documented. The [guide](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/liveness/README.md) mentions `host` just briefly, with some very contorted syntax. And it also talks about setting it to `127.0.0.1`, which only makes sense for pods with `hostNetwork = true` — right?

If you took away the ability to manually set the Host: header from the internal prober used at a certain search engine company, people would scream bloody murder. :-)

**Comment by thockin** [comment]
Yeah, the semantic of host is "obvious" to non-web people, and surprising
to web people.  I don't think we can change this behavior, but we can add
new behavior.

#14713

**Comment by thockin** [comment]
We could also try to deprecate the existing implementation - it seems very marginally useful...

**Comment by thockin** [comment]
Closing in favor of #14713
