### ISSUE TITLE
generateName / numeric container ID

### ISSUE THREAD

**Issue by streamnsight** [kubernetes/kubernetes#13221]
Is there an easy way to assign a unique numeric ID to a container?

Zookeeper, Kafka, and many other services require a unique ID to identify each other.
Using docker-compose I would assign a hostname with a unique id that I would parse inside the container to get its ID, but with Kubernetes even with the 'generateName' option there is no easy way to get a numeric ID.

Does anyone know of a way to 'automatically' assign a 'unique' numeric ID to a container? 
I resorted to using the IP without the dots, right now, to be sure it is unique and accessible outside but not sure this is foolproof.

**Comment by davidopp** [comment]
This is under active discussion. See #260. You can follow up with any questions there.
