### ISSUE TITLE
e2e: node stuck at recreating cbr0 and became not ready

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#13236]
I've noticed that in some jenkin runs, a node would be stuck at configuring network half way through the e2e suite.
E.g.,
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/8231/consoleFull

```
Aug 26 17:45:43.835: INFO: Node e2e-gce-minion-wlgf condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-26 17:44:20 -0700 PDT
Aug 26 17:45:43.835: INFO: Successfully found node e2e-gce-minion-wlgf readiness to be true
Aug 26 17:45:43.835: INFO: Node e2e-gce-minion-ywcb condition 1/1: type: Ready, status: False, reason: "network not configured correctly", message: "", last transition time: 2015-08-26 17:45:22 -0700 PDT
```

Here are some snippets of the kubelet.log on node e2e-gce-minion-ywcb, showing it try to recreate cbr0 bridge but failed.
```
I0827 00:43:35.702065    3551 kubelet.go:1760] Skipping pod synchronization, network is not configured
```

```
I0827 00:43:20.865910    3551 container_bridge.go:129] MASQUERADE rule doesn't exist, recreate it
I0827 00:43:20.883549    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
E0827 00:43:20.888854    3551 container_bridge.go:76] exit status 1
E0827 00:43:20.888898    3551 kubelet.go:2078] Error configuring cbr0: exit status 1
I0827 00:43:22.349578    3551 kubelet.go:2054] Recording NodeNotReady event message for node e2e-gce-minion-ywcb
```

```
I0827 00:43:20.883549    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:45:20.927077    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:45:50.942765    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:46:20.960209    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:47:50.996761    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:50:51.061544    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:51:21.075445    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:51:51.089490    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:52:21.103941    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:52:51.121908    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:53:21.135363    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:54:51.198902    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:55:51.231347    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:57:21.266844    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:57:51.281313    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 00:58:51.308590    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:00:21.355958    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:01:51.386797    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:05:51.465498    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:06:51.488499    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:08:21.519682    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:08:51.534112    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:09:21.556072    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:09:51.588990    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:11:21.644487    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:11:51.660640    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:18:21.769745    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:24:21.873383    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:25:21.900912    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:26:51.933698    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:31:22.035843    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:38:52.228351    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:40:22.272265    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:44:52.389135    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
I0827 01:46:22.430447    3551 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.1.1/24
```

**Comment by yujuhong** [comment]
I saw this around the MaxPod test, which pushed kubelet's limit by creating 100 pods per node. I also observed the same error by running the MaxPods test on my own e2e cluster.

**Comment by wojtek-t** [comment]
cc @kubernetes/goog-testing @quinton-hoole 

This might be in fact what we wanted to debug as mentioned in https://github.com/kubernetes/kubernetes/issues/13219#issuecomment-135170004

**Comment by quinton-hoole** [comment]
Thanks.  I can take a look.

**Comment by piosz** [comment]
Is this still an issue? #13247 should have fixed that.

**Comment by piosz** [comment]
I'm probably wrong, sorry for the confusion.

**Comment by yujuhong** [comment]
> Is this still an issue? #13247 should have fixed that.

It's quite likely that #13247 has fixed this problem, as this problem is very reproducible by running the MaxPods test. I will run locally to see if it's fixed. 
 #13219 seems to exhibit a different symptom that was caused by the node resize test.

**Comment by yujuhong** [comment]
I ran MaxPods 3 times and could not reproduce this problem anymore. I think the issue has been fixed by the revert(s). Closing this for now.

**Comment by yujuhong** [comment]
The e2e tests are randomly failing because network is not configured on node, starting from build http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/8293

`Aug 31 03:22:18.526: INFO: Node e2e-gce-minion-3bxx condition 1/1: type: Ready, status: False, reason: "network not configured correctly", message: "", last transition time: 2015-08-31 03:22:17 -0700 PDT`

**Comment by lavalamp** [comment]
Merges are basically blocked because of this.

**Comment by yujuhong** [comment]
FWIW, this is what I saw from my e2e cluster:
```
I0901 01:04:40.847141   15233 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.0.1/24
E0901 01:04:40.849254   15233 container_bridge.go:76] exit status 1
E0901 01:08:40.889234   15233 kubelet.go:2159] Error configuring cbr0: exit status 1
```

The relevant line with the failure: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container_bridge.go#L76
Manually running `ip link set dev cbr0 down` has never failed for me.

```console
# ip addr show cbr0
4: cbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP 
    link/ether 4a:70:65:c3:b4:01 brd ff:ff:ff:ff:ff:ff
    inet 10.245.0.1/24 scope global cbr0
       valid_lft forever preferred_lft forever
```

**Comment by piosz** [comment]
cc @gmarek

**Comment by wojtek-t** [comment]
This is especially visible on the gce-scalability suite.
Since exactly the same time - not even a single test passed.

There are 3 PRs that could cause that (looking at what was merged around that time):
https://github.com/kubernetes/kubernetes/pull/13356
https://github.com/kubernetes/kubernetes/pull/13237
https://github.com/kubernetes/kubernetes/pull/13296

i think we should try reverting them and check if that helps...

**Comment by yujuhong** [comment]
I modified the code to capture the stderr, and `ip addr show cbr0` would sometimes return `Device "cbr0" does not exist.` even though cbr0 was always there.

I am leaning towards the cadvisor PR because
 - cadvisor version bump includes a series PR for monitoring network stats
 - Both times when the PR landed, jenkins started becoming unstable. It is the only common PR.

**Comment by wojtek-t** [comment]
I agree that this one seems the most suspicious. Let's try to revert it.

**Comment by wojtek-t** [comment]
I created #13427 to revert the suspicious PR.

**Comment by jimmidyson** [comment]
> I modified the code to capture the stderr, and ip addr show cbr0 would sometimes return Device "cbr0" does not exist. even though cbr0 was always there.

I might be missing something, but how could cadvisor dependency affect that? If `cbr0` bridge is present, `ip addr show cbr0` has nothing to do with cadvisor - it's unrelated system command.

I'm looking through the code now to see if I can work out why/if cadvisor affects creating the bridge interface, but can't explain it at the moment.

**Comment by piosz** [comment]
I don't have idea how. This is not yet confirmed but the second try of merge this PR causes similar problems which looks at least suspicious.

**Comment by jimmidyson** [comment]
OK found a possible cause, working on a fix now. Can someone point out how to run e2e tests myself (preferably just the failing e2e test) so I can test before submitting an updated PR?

**Comment by piosz** [comment]
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#end-to-end-tests

**Comment by jimmidyson** [comment]
I can't see the failing e2e tests (please hurry up with the public jenkins ;) - I know it's coming soon). Could someone please post the failure log here or somewhere accessible so I can take a look?

Specifically looking for one of the following errors:

`Error on adding ip table rules` ([source](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2107))
`ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now` ([source](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2110))
`Error configuring cbr0` ([source](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2114))

These look like the only way that the reported error(`network not configured correctly` [source](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2244)) could manifest that I can see.

**Comment by wojtek-t** [comment]
I'm not sure how useful it is, but here is some snippet of logs:

    43816 I0831 10:24:40.182839    3547 server.go:685] POST /stats/container/: (20.972588ms) 0 [[Go 1.1 package http] 10.245.2.4:46973]
    43817 I0831 10:24:40.275565    3547 container_bridge.go:72] Attempting to recreate cbr0 with address range: 10.245.0.1/24
    43818 E0831 10:24:40.286520    3547 container_bridge.go:76] exit status 1
    43819 E0831 10:24:40.286576    3547 kubelet.go:2114] Error configuring cbr0: exit status 1
    43820 I0831 10:24:43.611439    3547 server.go:685] GET /healthz: (859.195µs) 0 [[curl/7.26.0] 127.0.0.1:54257]
    43821 I0831 10:24:47.697058    3547 kubelet.go:2090] Recording NodeNotReady event message for node e2e-gce-minion-3bxx
    43822 I0831 10:24:47.697133    3547 server.go:642] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"e2e-gce-minion-3bxx", UID:"e2e-gce-minion-3bxx", APIVersion:"", ResourceVersion:"",       FieldPath:""}): reason: 'NodeNotReady' Node e2e-gce-minion-3bxx status is now: NodeNotReady

 Also note, that in our normal e2e tests it's not happening frequently - it is just causing flakes, so you won't be able to reproduce it every time.

**Comment by jimmidyson** [comment]
So this is showing that `cbr0` exists but with an incorrect cidr.

Is e2e run with `--v=5` as most of the debug logs relevant to this error are logged at that level?

> in our normal e2e tests it's not happening frequently

Sounds like a race to me?

**Comment by wojtek-t** [comment]
@yujuhong or @dchen1107 are ones that you need to talk - I'm not very familiar with that parts of the code.

**Comment by piosz** [comment]
@jimmidyson my personal feeling is that your change didn't break anything but since Heapster is talking with cadvisor all the time the broken network configuration is always detected while querying for stats. Do you know how does the way network is used by cadvisor has changed in the new version you've added?

BTW thank you very much with digging into it!

**Comment by jimmidyson** [comment]
@piosz The change is to support Docker >= 1.7, which in previous versions of cadvisor resulted in no network stats (change in how docker networking worked with the introduction of libnetwork).

Digging through the code & looking at the logs, this error is around trying to run the command to recreate `cbr0` ([source](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container_bridge.go#L75-L78)). This is totally unrelated to cadvisor & I'm trying to figure out why this is happening at all. Output of the forked `ip addr` process is swallowed so no help there - how about a PR to log that output on failure as that might help in future?

**Comment by jimmidyson** [comment]
@yujuhong @dchen1107 @piosz @wojtek-t As you've said this is a flaky test, not consistent. Do you have a command (or 2 ;)) I can run that is most likely to cause the failure if I run it repeatedly? What just repeatedly running the following work cause it to fail do you think?

```
go run hack/e2e.go -v --up
go run hack/e2e.go -v -test
go run hack/e2e.go -v --down
```

**Comment by jimmidyson** [comment]
Ah I can just do `go run hack/e2e.go -build -pushup -test -down`

**Comment by jimmidyson** [comment]
So running the e2e tests & getting failures due to:

    exit status 1: Cannot find device "cbr0"

when trying to recreate cbr0.

I really can't understand how this could be related to cadvisor but is more likely to be caused by the create/recreate logic in the kubelet & the up/down in the e2e tests.

**Comment by wojtek-t** [comment]
I don't understand what is the reason, but it seems that reverting this PR helped.
Our scalability tests that were constantly failing since it was merged, now finally passed.
We should probably wait at least one more run, but it seems to be related to your PR.

**Comment by piosz** [comment]
cc @kubernetes/goog-node @vishh @vmarmol @rjnagal

**Comment by jimmidyson** [comment]
>  scalability tests that were constantly failing

Can you point out the constantly failing tests & how to run just those so I can test some fixes I'm making?

**Comment by wojtek-t** [comment]
The test that was failing more than 50% of cases was Density tests starting 30 pods per node:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/density.go#L174

However, the issue is that we are running it on 100-node cluster and the size of the cluster seems to be crucial here.

**Comment by jimmidyson** [comment]
And before this PR this test was successful 100% of the time? Size of cluster being important would again point towards a race of some kind, more nodes == more chance of it happening.

**Comment by wojtek-t** [comment]
Yes - it was constantly passing.

**Comment by yujuhong** [comment]
@jimmidyson, here is what I know:
 
 - kubelet periodically (30s) checks cbr0 to ensure it exists and has the correct CIDR
 - Sometimes, when checking the CIDR, `ip addr show cbr0` would return `exit status 1` (device does not exist). This happens quite regularly (once per minute).
   * Due to the error, kubelet thinks that the CIDR is incorrect, it then tries to bring down cbr0 with `ip link set dev cbr0 down`, which returns the same error (device does not exist).
   * With this error, kubelet reports that the network is not configured.
 - There is no proof that cbr0 was ever down and `/sys/class/net/cbr0` always exists. All pods seem to be functioning correctly. I wrote a one-line command to run `ip addr show cbr0` every two seconds, and the command never failed.

I have no idea why `ip` would sometimes fail to find cbr0.

As for how to test this, it happened quite often in my own e2e cluster, with or without running tests. You can always run a few e2e tests and grep `cbr0` from `kubelet.log`.

**Comment by jimmidyson** [comment]
Thanks @yujuhong.

> it happened quite often in my own e2e cluster

Do you mean post-cadvisor PR merge or before? Has this always been happening in your environment? I've seen it even with master after reverting the cadvisor PR, although perhaps not quite as often.

**Comment by yujuhong** [comment]
> Do you mean post-cadvisor PR merge or before? Has this always been happening in your environment? I've seen it even with master after reverting the cadvisor PR, although perhaps not quite as often.

I was testing my own changes yesterday in my e2e cluster, and this happened often enough that I couldn't finish my e2e test. (the cadvisor PR was still in head yesterday). I reverted the cadvisor PR locally, and the cluster has been up >12 hours without any problem.

Also, I spoke to @vishh, and he said he had some ideas about what may have caused this problem.

**Comment by vishh** [comment]
@jimmidyson: Is it possible that the fact that cAdvisor is entering namespaces of other containers affecting kubelet? IIRC, you did lock the runtime thread, so I would not expect that to happen.
Also, since you are getting rid of the namespace entering logic in cAdvisor, should we re-run e2e against a more recent cadvisor dependency?

**Comment by jimmidyson** [comment]
@vishh That was  only idea too but not sure how that affects cbr0 which isn't related to the actual containers network namespace.

Either way, yes we should be using the latest cadvisor now. Let's close this & get a new pr with updated cadvisor godep?

**Comment by yujuhong** [comment]
SGTM

**Comment by vishh** [comment]
I was suggesting that one of kubelet's goroutines might accidentally end up
in a docker container's network namespace. It cannot find cbr0 in there.
In any case, closing this PR and moving on latest HEAD SGTM.

**Comment by jimmidyson** [comment]
That mystery will remain unsolved. I can live with that ;)

**Comment by dchen1107** [comment]
Sorry for chiming in so late (I were OOO last week).

Do we know what's the root cause here? Reverting cAdvisor pr fixed the bleeding, but we need to bump up cAdvisor version, especially fixing the issue for network stats collection. I failed to find the fix at cAdvisor side.

**Comment by jimmidyson** [comment]
@dchen1107 The cause seemed to be some dodgy network namespace switching code I wrote to collect network stats in cadvisor. I've since rewritten that code in cadvisor completely & network stats now come from /proc fs.

I've personally run through e2e tests a few times & @vishh suggested we run through the e2e for the PR a couple of times to make sure.

New cadvisor upgrade PR is #13454.

**Comment by dchen1107** [comment]
Yeah, I realized that https://github.com/google/cadvisor/pull/870 should be the new code fixing the initial stats collection issue in cAdvisor. Thanks!
