### ISSUE TITLE
Problem with  replacing nodes 

### ISSUE THREAD

**Issue by decker502** [kubernetes/kubernetes#13242]
When I run kubectl replace command follow [here](http://kubernetes.io/v1.0/docs/admin/cluster-management.html), I got the below error

```
kubectl replace nodes 10.162.64.136 --patch='{"apiVersion": "v1", "spec": {"unschedulable": true}}'

Error: unknown flag: --patch
Run 'kubectl help' for usage.
```

**Comment by ivajloip** [comment]
Any development on this. Seems like it still does not work with 1.1.7 

     ./cluster/kubectl.sh version -c                                                                   
     Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}

And I see similar output (the help for `kubectl replace` + *Error: unknown flag: --patch*). Is there another way to mark a node as *unschedulable*?
