### ISSUE TITLE
Cross Availability Zone Cluster on AWS

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#13240]
Hi,

I started using Kubernetes on AWS a few weeks ago and it works great.
We're in the process of developing our product but looking forward we will need features like High Availability / Disaster Recovery and Redundancy.

The common way to have these features on AWS is spreading your instances across different Availability Zones.

I couldn't find any documentation on how to implement this using Kubernetes. By default, it works with a single AZ.

1. Is there a way to achieve multi-AZ spread using Kubernetes?
2. Is there an intention to add such feature in the future?

Thanks for the help.

**Comment by davidopp** [comment]
See #13056
