### ISSUE TITLE
Failed Syncing Pods

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#13245]
I am getting the following error message when trying to create a replication controller:
```
 failedSync         {kubelet ip-172-20-0-211.ec2.internal}   Error syncing pod, skipping: mkdir /mnt/ephemeral/kubernetes/kubelet/pods... no space left on device
```
The instance itself has 25Gigs of HD:
```
ubuntu@ip-172-20-0-211:/mnt$ df -h
Filesystem                            Size  Used Avail Use% Mounted on
udev                                  1.9G     0  1.9G   0% /dev
tmpfs                                 377M   39M  338M  11% /run
/dev/xvda1                             25G  1.8G   22G   8% /
tmpfs                                 1.9G  376K  1.9G   1% /dev/shm
tmpfs                                 5.0M     0  5.0M   0% /run/lock
tmpfs                                 1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/mapper/vg--ephemeral-docker      3.9G  2.5G  1.2G  68% /mnt/ephemeral/docker
/dev/mapper/vg--ephemeral-kubernetes  190M  186M     0 100% /mnt/ephemeral/kubernetes
tmpfs                                 377M     0  377M   0% /run/user/1000
```

Why is Kubernetes trying to download the images into that small 190M mounted volume and not use the main one?

**Comment by bprashanth** [comment]
@kubernetes/goog-node showing disk in describe node would help with clarity

**Comment by yujuhong** [comment]
This https://github.com/kubernetes/kubernetes/issues/12074#issuecomment-126713515 seems relevant. Why type of instance do you use?

**Comment by erez-rabih** [comment]
When I had the problem I used m3.medium instance type.
I changed to m4.large which is EBS backed only instance and the problem seems to be resolved.

I guess the problem exists in instances which have instance store disk.

**Comment by justinsb** [comment]
Thanks for the bug report & sorry for the problem.

I would like to track this under #13508, as that's where I've started thinking about it (although I think you reported it first!).  I'm going to close this one, but if you don't think #13508 will cover it then please do reopen.
