### ISSUE TITLE
Vagrant Cluster Provider uses deprecated -t option for kubectl get operation

### ISSUE THREAD

**Issue by cameronbrunner** [kubernetes/kubernetes#13267]
When running the Vagrant Cluster Provider with `kube-up.sh` the following deprecated message is displayed (with some context):

    Validating minion-1
    .........
    Waiting for each minion to be registered with cloud provider
    Flag shorthand -t has been deprecated, please use --template instead

Proposed Fix:  Simple, change -t to --template in cluster/vagrant/util.sh b/cluster/vagrant/util.sh at line 240.

**Comment by derekwaynecarr** [comment]
Closing issue as fix was merged.
