### ISSUE TITLE
port clash between kube-controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#13264]
Beginning in the v1.1.0-alphas, when attempting to run `kube-controller-manager` and `kube-scheduler` together on a CoreOS machine, the two will port clash.

    Aug 27 15:29:15 master systemd[1]: Started Kubernetes Scheduler.
    Aug 27 15:29:15 master kube-scheduler[1928]: F0827 15:29:15.805946    1928 server.go:120] listen tcp 127.0.0.1:10251: bind: address already in use
    Aug 27 15:29:15 master systemd[1]: kube-scheduler.service: Main process exited, code=exited, status=255/n/a
    Aug 27 15:29:15 master systemd[1]: kube-scheduler.service: Unit entered failed state.
    Aug 27 15:29:15 master systemd[1]: kube-scheduler.service: Failed with result 'exit-code'.
    Aug 27 15:29:25 master systemd[1]: kube-scheduler.service: Service hold-off time over, scheduling restart.
    Aug 27 15:29:25 master systemd[1]: Starting Kubernetes Scheduler...
    Aug 27 15:29:25 master curl[1937]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Aug 27 15:29:25 master curl[1937]: Dload  Upload   Total   Spent    Left  Speed
    Aug 27 15:29:26 master curl[1937]: [234B blob data]
    Aug 27 15:29:26 master systemd[1]: Started Kubernetes Scheduler.
    Aug 27 15:29:26 master kube-scheduler[1939]: F0827 15:29:26.072575    1939 server.go:120] listen tcp 127.0.0.1:10251: bind: address already in use
    Aug 27 15:29:26 master systemd[1]: kube-scheduler.service: Main process exited, code=exited, status=255/n/a
    Aug 27 15:29:26 master systemd[1]: kube-scheduler.service: Unit entered failed state.
    Aug 27 15:29:26 master systemd[1]: kube-scheduler.service: Failed with result 'exit-code'.

If I stop `kube-controller-manager` and then start the scheduler, the scheduler will start successfully. However, if I then try to start the controller, it will now fail due to the port conflict.

**Comment by bprashanth** [comment]
hmm, controller manager should be using 10252

**Comment by jcderr** [comment]
There must've been gremlins in my servers earlier. I started looking at this again this afternoon and have been unable to reproduce.
