### ISSUE TITLE
Default regular expression for long running requests does not match .../pods/.../log

### ISSUE THREAD

**Issue by mmilata** [kubernetes/kubernetes#13266]
Followup for #9013 #9180 #10656

The default regular expression for long running requests defined here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L60 does not match paths such as `/api/v1/namespaces/myns/pods/mypod/log` - though it matches `.../logs` which is incorrect as the singular form seems to be used.

CC @csrwng

**Comment by liggitt** [comment]
Usage of singular "log" subresource:
https://github.com/kubernetes/kubernetes/blob/ead7b376162e34f3a75436ef9ee631a1f953089c/pkg/kubectl/cmd/log.go#L149

In general, using a regex for that purpose is not great...

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/38119
