### ISSUE TITLE
Web UI/Dashboard does not allow viewing in other than the default namespace (?)

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes#13276]
Perhaps I'm missing something.  It seems like the k8s web UI doesn't expose any controls for viewing a namespace other than the default.

**Comment by bprashanth** [comment]
@preillyme

**Comment by scrisenbery** [comment]
@amygdala I believe this was changed in version 3 of the UI which is now in the master branch, but has not been included in any recent release as far as I can tell.
