### ISSUE TITLE
kube-proxy eats too much cpu

### ISSUE THREAD

**Issue by colorzhang** [kubernetes/kubernetes#13270]
Hello kubernauts,

I am running java/mysql application on single kubernetes node.
Kube-proxy eats too much cpu as shown in the snapshot.
any suggestion or idea to debug? 

Thanks.
Winston

kubernetes 1.0.3
go1.4.2
Docker 1.8.1
Gentoo Linux latest

<img width="634" alt="screen shot 2015-08-28 at 00 38 00" src="https://cloud.githubusercontent.com/assets/919606/9526677/3ea3b8a0-4d1d-11e5-8106-c20208bdde58.png">

**Comment by bprashanth** [comment]
Thanks for the report. Please provide:
1. kube proxy logs (probably /var/log/kube-proxy.log)
2. iptables -t nat -L, kubectl get svc --all-namespaces, kubectl get ep --all-namespaces
3. kubectl describe svc <your mysql/java service>, describe pods

@kubernetes/goog-cluster

**Comment by colorzhang** [comment]
1.
gentoo kube # more kube-proxy.log 
E0827 23:28:19.044748    7694 event.go:195] Unable to write event: 'Post http://localhost:8080/api/v1/namespaces/default/events: dial tcp [::1]:8080: getsockopt: connection refused' (may retry after sle
eping)
E0827 23:28:19.278290    7694 proxier.go:211] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or director
y

Try `iptables -h' or 'iptables --help' for more information.
E0827 23:28:19.293442    7694 proxier.go:215] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or director
y

Try `iptables -h' or 'iptables --help' for more information.
E0828 01:07:05.877257    7694 proxysocket.go:165] I/O error: read tcp 10.0.2.15:43044->10.0.2.2:52113: read tcp 172.17.42.1:56731->172.17.0.6:9001: read: connection reset by peer
E0828 01:37:43.171756    7694 proxier.go:477] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/solr-service:solr", args:[-m comment --comment default/solr-service:solr -p tcp 
-m tcp --dport 8983 -d 10.0.72.20/32 -j REDIRECT --to-ports 42643]
E0828 01:37:43.203448    7694 proxier.go:235] Failed to ensure portal for "default/solr-service:solr": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you 
want to use the -w option?
E0828 01:37:43.371544    7694 proxier.go:477] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/zk-service:zookeeper", args:[-m comment --comment default/zk-service:zookeeper -
p tcp -m tcp --dport 2181 -d 10.0.108.253/32 -j REDIRECT --to-ports 37098]
E0828 01:37:43.371593    7694 proxier.go:235] Failed to ensure portal for "default/zk-service:zookeeper": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps y
ou want to use the -w option?
E0828 01:37:44.532157    7694 proxier.go:220] Failed to ensure iptables: error creating chain "KUBE-PORTALS-CONTAINER": exit status 4: Another app is currently holding the xtables lock. Perhaps you want
 to use the -w option?
E0828 01:37:44.850939    7694 proxier.go:477] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/zk-service:zookeeper", args:[-m comment --comment default/zk-service:zookeeper -
p tcp -m tcp --dport 2181 -d 10.0.108.253/32 -j REDIRECT --to-ports 37098]
E0828 01:37:44.851010    7694 proxier.go:235] Failed to ensure portal for "default/zk-service:zookeeper": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps y
ou want to use the -w option?
E0828 01:37:45.002247    7694 proxier.go:477] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "kube-system/kube-ui:", args:[-m comment --comment kube-system/kube-ui: -p tcp -m tcp --d
port 80 -d 10.0.59.82/32 -j REDIRECT --to-ports 47674]
E0828 01:37:45.002294    7694 proxier.go:235] Failed to ensure portal for "kube-system/kube-ui:": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want 
to use the -w option?
E0828 01:37:45.118226    7694 proxier.go:477] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/hybris56-service:http", args:[-m comment --comment default/hybris56-service:http
 -p tcp -m tcp --dport 9001 -d 10.0.159.218/32 -j REDIRECT --to-ports 43044]
E0828 01:37:45.136265    7694 proxier.go:235] Failed to ensure portal for "default/hybris56-service:http": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps 
you want to use the -w option?
E0828 01:37:45.473590    7694 proxier.go:477] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/hybris56-service:https", args:[-m comment --comment default/hybris56-service:htt
ps -p tcp -m tcp --dport 9002 -d 10.0.159.218/32 -j REDIRECT --to-ports 50074]
E0828 01:37:45.473644    7694 proxier.go:235] Failed to ensure portal for "default/hybris56-service:https": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps
 you want to use the -w option?
E0828 01:37:45.682198    7694 proxier.go:477] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/hybris56-service:debug", args:[-m comment --comment default/hybris56-service:deb
ug -p tcp -m tcp --dport 8000 -d 10.0.159.218/32 -j REDIRECT --to-ports 60799]
E0828 01:37:45.682257    7694 proxier.go:235] Failed to ensure portal for "default/hybris56-service:debug": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps
 you want to use the -w option?
E0828 01:37:45.869681    7694 proxier.go:477] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/kubernetes:", args:[-m comment --comment default/kubernetes: -p tcp -m tcp --dpo
rt 443 -d 10.0.0.1/32 -j REDIRECT --to-ports 39516]
E0828 01:37:45.872049    7694 proxier.go:235] Failed to ensure portal for "default/kubernetes:": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want t
o use the -w option?
E0828 01:37:46.050272    7694 proxier.go:477] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/mysql-service:mysql", args:[-m comment --comment default/mysql-service:mysql -p 
tcp -m tcp --dport 3306 -d 10.0.178.40/32 -j REDIRECT --to-ports 56148]
E0828 01:37:46.050340    7694 proxier.go:235] Failed to ensure portal for "default/mysql-service:mysql": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps yo
u want to use the -w option?
E0828 01:37:46.135114    7694 proxier.go:477] Failed to install iptables KUBE-PORTALS-CONTAINER rule for service "default/solr-service:solr", args:[-m comment --comment default/solr-service:solr -p tcp 
-m tcp --dport 8983 -d 10.0.72.20/32 -j REDIRECT --to-ports 42643]
E0828 01:37:46.135385    7694 proxier.go:235] Failed to ensure portal for "default/solr-service:solr": error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you 
want to use the -w option?

2.
gentoo ~ # iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
KUBE-PORTALS-CONTAINER  all  --  anywhere             anywhere             /* handle ClusterIPs; NOTE: this must be before the NodePort rules */
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
KUBE-NODEPORT-CONTAINER  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL /* handle service NodePorts; NOTE: this must be the last rule in the chain */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-PORTALS-HOST  all  --  anywhere             anywhere             /* handle ClusterIPs; NOTE: this must be before the NodePort rules */
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL
KUBE-NODEPORT-HOST  all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL /* handle service NodePorts; NOTE: this must be the last rule in the chain */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         

Chain KUBE-NODEPORT-CONTAINER (1 references)
target     prot opt source               destination         

Chain KUBE-NODEPORT-HOST (1 references)
target     prot opt source               destination         

Chain KUBE-PORTALS-CONTAINER (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             10.0.108.253         /* default/zk-service:zookeeper */ tcp dpt:2181 redir ports 37098
REDIRECT   tcp  --  anywhere             10.0.59.82           /* kube-system/kube-ui: */ tcp dpt:http redir ports 47674
REDIRECT   tcp  --  anywhere             10.0.159.218         /* default/hybris56-service:http */ tcp dpt:9001 redir ports 43044
REDIRECT   tcp  --  anywhere             10.0.159.218         /* default/hybris56-service:https */ tcp dpt:9002 redir ports 50074
REDIRECT   tcp  --  anywhere             10.0.159.218         /* default/hybris56-service:debug */ tcp dpt:8000 redir ports 60799
REDIRECT   tcp  --  anywhere             10.0.0.1             /* default/kubernetes: */ tcp dpt:https redir ports 39516
REDIRECT   tcp  --  anywhere             10.0.178.40          /* default/mysql-service:mysql */ tcp dpt:mysql redir ports 56148
REDIRECT   tcp  --  anywhere             10.0.72.20           /* default/solr-service:solr */ tcp dpt:8983 redir ports 42643

Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             10.0.108.253         /* default/zk-service:zookeeper */ tcp dpt:2181 to:10.0.2.15:37098
DNAT       tcp  --  anywhere             10.0.59.82           /* kube-system/kube-ui: */ tcp dpt:http to:10.0.2.15:47674
DNAT       tcp  --  anywhere             10.0.159.218         /* default/hybris56-service:http */ tcp dpt:9001 to:10.0.2.15:43044
DNAT       tcp  --  anywhere             10.0.159.218         /* default/hybris56-service:https */ tcp dpt:9002 to:10.0.2.15:50074
DNAT       tcp  --  anywhere             10.0.159.218         /* default/hybris56-service:debug */ tcp dpt:8000 to:10.0.2.15:60799
DNAT       tcp  --  anywhere             10.0.0.1             /* default/kubernetes: */ tcp dpt:https to:10.0.2.15:39516
DNAT       tcp  --  anywhere             10.0.178.40          /* default/mysql-service:mysql */ tcp dpt:mysql to:10.0.2.15:56148
DNAT       tcp  --  anywhere             10.0.72.20           /* default/solr-service:solr */ tcp dpt:8983 to:10.0.2.15:42643
gentoo ~ # 

gentoo ~ # kubectl get svc --all-namespaces
NAMESPACE     NAME               CLUSTER_IP     EXTERNAL_IP   PORT(S)                      SELECTOR          AGE
default       hybris56-service   10.0.159.218   <none>        9001/TCP,9002/TCP,8000/TCP   app=hybris56      20d
default       kubernetes         10.0.0.1       <none>        443/TCP                      <none>            26d
default       mysql-service      10.0.178.40    <none>        3306/TCP                     app=mysql         20d
default       solr-service       10.0.72.20     <none>        8983/TCP                     app=solrcloud     20d
default       zk-service         10.0.108.253   <none>        2181/TCP                     app=zookeeper     18d
kube-system   kube-ui            10.0.59.82     <none>        80/TCP                       k8s-app=kube-ui   26d

gentoo ~ # kubectl get ep --all-namespaces
NAMESPACE     NAME               ENDPOINTS                                         AGE
default       hybris56-service   172.17.0.6:9002,172.17.0.6:9001,172.17.0.6:8000   20d
default       kubernetes         10.0.2.15:6443                                    26d
default       mysql-service      172.17.0.2:3306                                   20d
default       solr-service       172.17.0.4:8983,172.17.0.5:8983                   20d
default       zk-service         172.17.0.3:2181                                   18d
kube-system   kube-ui            172.17.0.1:8080                                   26d


3.
gentoo ~ # kubectl describe svc
Name:			hybris56-service
Namespace:		default
Labels:			app=hybris56-service
Selector:		app=hybris56
Type:			ClusterIP
IP:			10.0.159.218
Port:			http	9001/TCP
Endpoints:		172.17.0.6:9001
Port:			https	9002/TCP
Endpoints:		172.17.0.6:9002
Port:			debug	8000/TCP
Endpoints:		172.17.0.6:8000
Session Affinity:	None
No events.

Name:			kubernetes
Namespace:		default
Labels:			component=apiserver,provider=kubernetes
Selector:		<none>
Type:			ClusterIP
IP:			10.0.0.1
Port:			<unnamed>	443/TCP
Endpoints:		10.0.2.15:6443
Session Affinity:	None
No events.

Name:			mysql-service
Namespace:		default
Labels:			app=mysql-service
Selector:		app=mysql
Type:			ClusterIP
IP:			10.0.178.40
Port:			mysql	3306/TCP
Endpoints:		172.17.0.2:3306
Session Affinity:	None
No events.

Name:			solr-service
Namespace:		default
Labels:			app=solr-service
Selector:		app=solrcloud
Type:			ClusterIP
IP:			10.0.72.20
Port:			solr	8983/TCP
Endpoints:		172.17.0.4:8983,172.17.0.5:8983
Session Affinity:	None
No events.

Name:			zk-service
Namespace:		default
Labels:			app=zk-service
Selector:		app=zookeeper
Type:			ClusterIP
IP:			10.0.108.253
Port:			zookeeper	2181/TCP
Endpoints:		172.17.0.3:2181
Session Affinity:	None
No events.

gentoo ~ # kubectl describe pods
Name:				hybris56-controller-wad0c
Namespace:			default
Image(s):			winston/hybris:5.6
Node:				gentoo/127.0.0.1
Labels:				app=hybris56
Status:				Running
Reason:				
Message:			
IP:				172.17.0.6
Replication Controllers:	hybris56-controller (1/1 replicas created)
Containers:
  hybris56:
    Image:	winston/hybris:5.6
    Limits:
      cpu:		4
      memory:		4Gi
    State:		Running
      Started:		Thu, 27 Aug 2015 23:42:00 +0800
    Ready:		True
    Restart Count:	0
    Variables:
Conditions:
  Type		Status
  Ready 	True 
No volumes.
No events.

Name:				mysql-controller-apusf
Namespace:			default
Image(s):			mysql:5.6
Node:				gentoo/127.0.0.1
Labels:				app=mysql
Status:				Running
Reason:				
Message:			
IP:				172.17.0.2
Replication Controllers:	mysql-controller (1/1 replicas created)
Containers:
  mysql:
    Image:			mysql:5.6
    State:			Running
      Started:			Thu, 27 Aug 2015 21:45:38 +0800
    Last Termination State:	Terminated
      Exit Code:		0
      Started:			Mon, 17 Aug 2015 15:49:47 +0800
      Finished:			Mon, 17 Aug 2015 20:16:48 +0800
    Ready:			True
    Restart Count:		1341
    Variables:
      MYSQL_ROOT_PASSWORD:	hybris
      MYSQL_DATABASE:		hybris
      MYSQL_USER:		hybris
      MYSQL_PASSWORD:		hybris
Conditions:
  Type		Status
  Ready 	True 
Volumes:
  mysql-data:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
No events.

Name:				solrcloud-controller-h5kyc
Namespace:			default
Image(s):			winston/solr:5.2.1
Node:				gentoo/127.0.0.1
Labels:				app=solrcloud
Status:				Running
Reason:				
Message:			
IP:				172.17.0.4
Replication Controllers:	solrcloud-controller (2/2 replicas created)
Containers:
  solrcloud:
    Image:			winston/solr:5.2.1
    State:			Running
      Started:			Thu, 27 Aug 2015 21:45:39 +0800
    Last Termination State:	Terminated
      Exit Code:		143
      Started:			Mon, 17 Aug 2015 15:49:48 +0800
      Finished:			Mon, 17 Aug 2015 20:16:54 +0800
    Ready:			True
    Restart Count:		1341
    Variables:
      ZKHOST:	10.0.108.253:2181
Conditions:
  Type		Status
  Ready 	True 
Volumes:
  solr-data:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
No events.

Name:				solrcloud-controller-kz8lx
Namespace:			default
Image(s):			winston/solr:5.2.1
Node:				gentoo/127.0.0.1
Labels:				app=solrcloud
Status:				Running
Reason:				
Message:			
IP:				172.17.0.5
Replication Controllers:	solrcloud-controller (2/2 replicas created)
Containers:
  solrcloud:
    Image:		winston/solr:5.2.1
    State:		Running
      Started:		Thu, 27 Aug 2015 23:28:31 +0800
    Ready:		True
    Restart Count:	0
    Variables:
      ZKHOST:	10.0.108.253:2181
Conditions:
  Type		Status
  Ready 	True 
Volumes:
  solr-data:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
No events.

Name:				zk-controller-g3yv5
Namespace:			default
Image(s):			apache/zookeeper
Node:				gentoo/127.0.0.1
Labels:				app=zookeeper
Status:				Running
Reason:				
Message:			
IP:				172.17.0.3
Replication Controllers:	zk-controller (1/1 replicas created)
Containers:
  zookeeper:
    Image:			apache/zookeeper
    State:			Running
      Started:			Thu, 27 Aug 2015 21:45:38 +0800
    Last Termination State:	Terminated
      Exit Code:		143
      Started:			Mon, 17 Aug 2015 15:49:48 +0800
      Finished:			Mon, 17 Aug 2015 20:16:46 +0800
    Ready:			True
    Restart Count:		1341
    Variables:
Conditions:
  Type		Status
  Ready 	True 
Volumes:
  zk-data:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
No events.

**Comment by thockin** [comment]
This is not unexpected under heavy heavy load.  The new (hopefully kube
v1.1) proxier uses iptables directly to avoid the userspace copies.  What
sort of load are you running through this?

**Comment by colorzhang** [comment]
I load hundreds of thousands items into mysql database through java/jdbc. (do hybris initialization )
I also tested against kube git master. It was even worse with higher cpu.

Usually it takes 40m to finish. now it takes more than 6h to finish with kubernetes.

java web(hybris) service==>java web(hybris) rc==>mysql service ==>mysql rc
                                                                       |
                                                                       |   ==>solr service ==> solr rc

gentoo kube # kubectl version
Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.2405+997dd12c2cc7fb", GitCommit:"997dd12c2cc7fb05de0e6191ab041119e54e4a4e", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.2405+997dd12c2cc7fb", GitCommit:"997dd12c2cc7fb05de0e6191ab041119e54e4a4e", GitTreeState:"clean"}

**Comment by colorzhang** [comment]
Thank you @thockin for hint
I switched to iptables proxy with --legacy-userspace-proxy=false. everything is ok now.

Thanks,
Winston

**Comment by bprashanth** [comment]
Nice, so can we close this? you have decent cpu and good perf?

**Comment by colorzhang** [comment]
Yes, please. kube-proxy userspace perf has been covered by other threads already. Thanks.
