### ISSUE TITLE
Aggressively GC dead containers

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#13287]
We currently keep dead containers around for several reasons:
1. To keep container logs and other data around
2. To keep a record of the container state
  * _It is possible for the container to be GCed before we no longer need this state_

We could address these in other ways by:
1. Storing records for dead containers elsewhere (perhaps the api server?)
2. Rotating log data to a permanent location (fluentd?)

This would allow us to immediately GC containers once their state and logs had been exported.  It would also ensure that we did not lose state or log data due to premature garbage collection.

**Comment by dalanlan** [comment]
Just to mention, the logs stored elsewhere could be safely removed some time (those logs of a container corpse within a *deleted* pod, for example). The logs could take up space after all.

**Comment by yujuhong** [comment]
Closing this in favor of #26923
