### ISSUE TITLE
Remove V(5) logging

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#13282]
According to https://github.com/kubernetes/kubernetes/blob/master/docs/devel/logging.md, logging only goes up to level 4. However there are many log lines that log at level 5:

```
MBPr:kubernetes sam$ grep -R "\.V(5)" pkg
pkg/api/v1beta3/defaults.go:            glog.V(5).Infof("creating security context for container %s", container.Name)
pkg/apiserver/proxy.go:         glog.V(5).Infof("[%x: %v] making a dial-only transport...", proxyHandlerTraceID, req.URL)
pkg/apiserver/proxy.go:         glog.V(5).Infof("[%x: %v] using transport %T...", proxyHandlerTraceID, req.URL, roundTripper)
pkg/apiserver/proxy.go:         glog.V(5).Infof("[%x] Not making a reriting transport for proxy %s...", proxyHandlerTraceID, req.URL)
pkg/apiserver/proxy.go:         glog.V(5).Infof("[%x] making a transport for proxy %s...", proxyHandlerTraceID, req.URL)
pkg/apiserver/watch.go:                 glog.V(5).Infof("Failed to set self link for object %v: %v", reflect.TypeOf(obj), err)
pkg/client/record/event.go:                     glog.V(5).Infof("Server rejected event '%#v': '%v' (will not retry!)", event, err)
...
MBPr:kubernetes sam$ grep -R "\.V(5)" pkg | wc -l
      65
```

These should be mass search-and-replaced to V(4).

**Comment by ghodss** [comment]
Another nice thing to do here would be to add a comment to the kubectl --v flag indicating that the highest level is "4".

**Comment by bprashanth** [comment]
@lavalamp generally has opinions and also https://github.com/kubernetes/kubernetes/pull/9274

**Comment by ghodss** [comment]
Ah. If there's a distinction as to what a user should ever see vs. what a developer might want to see while they're debugging, that might be okay, but the documentation at least should make note of that. Especially if we're making discontinuous leaps (like V(10)).

**Comment by lavalamp** [comment]
Yeah, we're somewhat inconsistent here. But I think V(big number) is useful for details that are definitely not wanted in logs when everything is working correctly.

**Comment by liggitt** [comment]
for example, there are debugging transports that dump network traces at levels 6, 7, and 8

**Comment by liggitt** [comment]
> Especially if we're making discontinuous leaps (like V(10)).

As long as it goes to 11

**Comment by smarterclayton** [comment]
We should update the docs.  6-9 have definite value, 5 was really the "be verbose" debug.

**Comment by liggitt** [comment]
I always thought of V(4) as debug-level, and V(5) as trace-level

**Comment by fabianofranz** [comment]
There are logs present across the codebase that go from 0 up to 10. 

I'd suggest we formally embrace **0-4 as debug-level** logs, and **5-10 as trace-level** ones. Then I'd do 3 things:

1) Update the flag description to something like the one below. 

```
-v, --v=0: Set the level of log output to debug-level (0~4) or trace-level (5~10) 
```

Also, short and long forms are equal today (`-v` and `--v`), we could in addition consider a longer long form like `--loglevel`, although there might be back compat issues.

2) Review and replace across the codebase to make sure logs are compliant with the debug/trace levels.

3) Update user/contrib docs.

What do you think?

**Comment by ghodss** [comment]
SGTM. I think you can omit the short flag version since all flags are automatically converted internally to long-flag and that's where we want to end up anyways.

I think you still want some more docs and/or guidelines (especially for developers) that give people a little more guidance on what log level to pick within that range, both for when you're debugging and for when you're developing.

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/community/issues/558
