### ISSUE TITLE
Mesos TestExecutorStaticPods flaky 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#13284]
https://app.shippable.com/builds/55df5cc04c1f700b00bad724

93 195 246 0 0 0 162 1 0 0 10 0 0 0 0 0 0 0 0 0 0 0 0 0 44 1 0 0 115 112 111 100 50 46 106 115 111 110 80 75 1 2 20 0 20 0 8 0 8 0 0 0 0 0 135 16 169 50 246 0 0 0 162 1 0 0 13 0 0 0 0 0 0 0 0 0 0 0 0 0 90 2 0 0 100 105 114 47 115 112 111 100 46 106 115 111 110 80 75 5 6 0 0 0 0 3 0 3 0 170 0 0 0 139 3 0 0 0 0],XXX_unrecognized:[],} of framework nil registered with slave nil
E0827 19:00:42.000928    7284 file.go:53] Unable to read config path "/tmp/executor-k8sm-archive297949158": path does not exist, ignoring
--- FAIL: TestExecutorStaticPods (2.35s)
	executor_test.go:530: Executor should send pod updates for 2 pods, only saw 0

@davidopp for triage

**Comment by davidopp** [comment]
If this is still flaking, please disable the test until a fix is available.

**Comment by jdef** [comment]
update: we're cleaning this up #13943

**Comment by wojtek-t** [comment]
Is this still an issue? Can we close it?

**Comment by sttts** [comment]
The code has completely changed. I would close this one and reopen another ticket if something is broken again.

**Comment by wojtek-t** [comment]
SGTM - thanks!
