### ISSUE TITLE
Inconsistent docker root causing fluentd failures

### ISSUE THREAD

**Issue by iterion** [kubernetes/kubernetes#13313]
It seems that there are potentially two separate issues here:
- The inconsistent docker root due to a potential race between kubelet and docker.
- The misconfiguration (on AWS) of fluentd to mount /var/lib/docker instead of /mnt/ephemeral/docker.

For the first issue, perhaps the kubelet should fail if it is not able to retrieve the docker root from docker info?

An alternative solution would be to mount our volume for AWS to /var/lib/docker instead of /mnt/ephemeral/docker. This would solve both issues. But, it seems that the kubelet is providing the ability to dynamically locate the docker root for some reason.
##### Details:

I'm having intermittent issues with fluentd pushing logs to elasticsearch. It seems that fluentd is unable to see the log files, even though it is able list the containers directory. This is happening on an AWS cluster.

From inside the fluentd I see the following:

``` bash
 root@fluentd-elasticsearch-ip-172-20-0-194:/# cat /varlog/containers/vapor-web-v1-x894w_vapor-alpha_nginx-521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491.log
 cat: /varlog/containers/vapor-web-v1-x894w_vapor-alpha_nginx-521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491.log: No such file or directory
```

On AWS the log file symlinks look like this:

``` bash
 root@fluentd-elasticsearch-ip-172-20-0-194:/# ls -al /varlog/containers/vapor-web-v1-x894w_*
 lrwxrwxrwx 1 root root 171 Aug 27 18:03 /varlog/containers/vapor-web-v1-x894w_vapor-alpha_POD-99cd13b12f2b45275f5a3bcb7537d08ce722c48d66e3e21b57ad0563d5f2d8c0.log -> /mnt/ephemeral/docker/containers/99cd13b12f2b45275f5a3bcb7537d08ce722c48d66e3e21b57ad0563d5f2d8c0/99cd13b12f2b45275f5a3bcb7537d08ce722c48d66e3e21b57ad0563d5f2d8c0-json.log
 lrwxrwxrwx 1 root root 171 Aug 27 18:03 /varlog/containers/vapor-web-v1-x894w_vapor-alpha_nginx-521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491.log -> /mnt/ephemeral/docker/containers/521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491/521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491-json.log
 lrwxrwxrwx 1 root root 171 Aug 27 18:03 /varlog/containers/vapor-web-v1-x894w_vapor-alpha_vapor-unicorn-1e5233b3d6d2e8c92c8534dd61d46b4aadc7766d54423eb17425682d678bad9a.log -> /mnt/ephemeral/docker/containers/1e5233b3d6d2e8c92c8534dd61d46b4aadc7766d54423eb17425682d678bad9a/1e5233b3d6d2e8c92c8534dd61d46b4aadc7766d54423eb17425682d678bad9a-json.log
```

Fluentd seems to expect that the symlinks will point to /var/lib/docker/containers but on AWS we use /mnt/ephemeral/docker/containers.

From the node I see:

``` bash
root@ip-172-20-0-194:/home/ubuntu# ls -al /var/log/containers/vapor-web-v1-x894w_vapor-alpha_*
lrwxrwxrwx 1 root root 171 Aug 27 18:03 /var/log/containers/vapor-web-v1-x894w_vapor-alpha_nginx-521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491.log -> /mnt/ephemeral/docker/containers/521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491/521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491-json.log
lrwxrwxrwx 1 root root 171 Aug 27 18:03 /var/log/containers/vapor-web-v1-x894w_vapor-alpha_POD-99cd13b12f2b45275f5a3bcb7537d08ce722c48d66e3e21b57ad0563d5f2d8c0.log -> /mnt/ephemeral/docker/containers/99cd13b12f2b45275f5a3bcb7537d08ce722c48d66e3e21b57ad0563d5f2d8c0/99cd13b12f2b45275f5a3bcb7537d08ce722c48d66e3e21b57ad0563d5f2d8c0-json.log
lrwxrwxrwx 1 root root 171 Aug 27 18:03 /var/log/containers/vapor-web-v1-x894w_vapor-alpha_vapor-unicorn-1e5233b3d6d2e8c92c8534dd61d46b4aadc7766d54423eb17425682d678bad9a.log -> /mnt/ephemeral/docker/containers/1e5233b3d6d2e8c92c8534dd61d46b4aadc7766d54423eb17425682d678bad9a/1e5233b3d6d2e8c92c8534dd61d46b4aadc7766d54423eb17425682d678bad9a-json.log
```

``` bash
 root@ip-172-20-0-194:/home/ubuntu# cat /mnt/ephemeral/docker/containers/521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491/521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491-json.log | tail -n 5
 {"log":"172.20.0.70 - - [28/Aug/2015:17:29:26 +0000] \"GET / HTTP/1.1\" 302 116 \"-\" \"Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)\"\n","stream":"stdout","time":"2015-08-28T17:29:26.242591558Z"}
 {"log":"172.20.0.70 - - [28/Aug/2015:17:29:26 +0000] \"GET /users/sign_in HTTP/1.1\" 200 1954 \"-\" \"Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)\"\n","stream":"stdout","time":"2015-08-28T17:29:26.265429648Z"}
 {"log":"2015/08/28 17:29:26 [info] 5#5: *58423 client 172.20.0.70 closed keepalive connection\n","stream":"stdout","time":"2015-08-28T17:29:26.271201715Z"}
 {"log":"2015/08/28 17:29:38 [info] 5#5: *58426 client closed connection while waiting for request, client: 172.20.0.171, server: 0.0.0.0:80\n","stream":"stdout","time":"2015-08-28T17:29:38.549273837Z"}
 {"log":"2015/08/28 17:29:46 [info] 5#5: *58427 client closed connection while waiting for request, client: 172.20.0.33, server: 0.0.0.0:80\n","stream":"stdout","time":"2015-08-28T17:29:46.549263618Z"}
```

**Comment by iterion** [comment]
I updated the fluentd pod to look like the following which seems like it has resolved the issue on that node.

```yaml

apiVersion: v1
kind: Pod
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
spec:
  containers:
  - name: fluentd-elasticsearch
    image: gcr.io/google_containers/fluentd-elasticsearch:1.9
    resources:
      limits:
        cpu: 100m
    env:
    - name: "FLUENTD_ARGS"
      value: "-qq"
    volumeMounts:
    - name: varlog
      mountPath: /varlog
    - name: containers
      mountPath: /mnt/ephemeral/docker/containers
  terminationGracePeriodSeconds: 30
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: containers
    hostPath:
      path: /mnt/ephemeral/docker/containers
```

@justinsb based on the above, it definitely seems like this could be an AWS specific problem. I'm not sure what the best approach for a fix would be.

It's also strange that the logging seems to work sometimes, but many times it fails for this reason. I'm investigating what's happening for the cases where it does work now.

From the node I can also access the logs from /var/lib/docker.
```bash
 cat /var/lib/docker/containers/521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491/521e74369e30312a32806b018e62ef81d6a606dd87c0772aaacc2461ae84e491-json.log | tail -n 2
 {"log":"2015/08/28 17:54:53 [info] 5#5: *59483 client closed connection while waiting for request, client: 172.20.0.71, server: 0.0.0.0:80\n","stream":"stdout","time":"2015-08-28T17:54:53.103264167Z"}
 {"log":"2015/08/28 17:54:53 [info] 5#5: *59484 client closed connection while waiting for request, client: 172.20.0.75, server: 0.0.0.0:80\n","stream":"stdout","time":"2015-08-28T17:54:53.103594112Z"}
```

**Comment by iterion** [comment]
Further investigation:

On my cluster on AWS docker info gives:
```bash
root@ip-172-20-0-194:/home/ubuntu# docker info
Containers: 123
Images: 291
Storage Driver: aufs
 Root Dir: /mnt/ephemeral/docker/aufs
  Backing Filesystem: extfs
  Dirs: 537
  Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.19.0-20-generic
Operating System: Ubuntu 15.04 (containerized)
CPUs: 8
Total Memory: 31.42 GiB
Name: ip-172-20-0-194
ID: N264:XBMH:KUCS:A3ZU:5X4P:LL6L:FCET:A4EP:5C75:VCTU:XOHQ:24AO
WARNING: No swap limit support
```

Docker info seems to be used by the kubelet to set `dockerRoot` which is then used to create symlinks to the docker logs.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L162

**Comment by iterion** [comment]
The inconsistency seems to be tied to nodes that defaulted to /var/lib/docker as their docker root.

```bash
ubuntu@ip-172-20-0-171:~$ ls -al /var/log/containers/ | tail -n 5
lrwxrwxrwx  1 root root     165 Aug 21 21:37 worker-cleaner-rbpw0_vapor-alpha_worker-cleaner-72ec7b56758d5f35d9deda061a010f0c3c46af1c19247e132d1cb1ec456c8023.log -> /var/lib/docker/containers/72ec7b56758d5f35d9deda061a010f0c3c46af1c19247e132d1cb1ec456c8023/72ec7b56758d5f35d9deda061a010f0c3c46af1c19247e132d1cb1ec456c8023-json.log
lrwxrwxrwx  1 root root     165 Aug 21 21:48 worker-cleaner-sjvbk_vapor-alpha_POD-a8f48c3fee3dfaf89db00900435b4803d7709d84fa565503039c6553825eeb2d.log -> /var/lib/docker/containers/a8f48c3fee3dfaf89db00900435b4803d7709d84fa565503039c6553825eeb2d/a8f48c3fee3dfaf89db00900435b4803d7709d84fa565503039c6553825eeb2d-json.log
lrwxrwxrwx  1 root root     165 Aug 21 21:48 worker-cleaner-sjvbk_vapor-alpha_worker-cleaner-6208af9f07a5642db5bbc5804dce9aa0172211cb2b1c4c5d535730dc0ef1c15f.log -> /var/lib/docker/containers/6208af9f07a5642db5bbc5804dce9aa0172211cb2b1c4c5d535730dc0ef1c15f/6208af9f07a5642db5bbc5804dce9aa0172211cb2b1c4c5d535730dc0ef1c15f-json.log
```

Interestingly, on that node docker info still reports docker root as /mnt/ephemeral/docker
```bash
ubuntu@ip-172-20-0-171:~$ sudo docker info
Containers: 61
Images: 178
Storage Driver: aufs
 Root Dir: /mnt/ephemeral/docker/aufs
 Backing Filesystem: extfs
 Dirs: 300
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.19.0-20-generic
Operating System: Ubuntu 15.04 (containerized)
CPUs: 8
Total Memory: 31.42 GiB
Name: ip-172-20-0-171
ID: 5ARV:N526:VXCL:K7IC:V4SW:LI4X:P6CO:6LEU:DSTN:SF47:HKGF:E5EN
WARNING: No swap limit support
```

**Comment by iterion** [comment]
It seems that there are potentially two separate issues here:

1. The inconsistent docker root due to a potential race between kubelet and docker.
2. The misconfiguration (on AWS) of fluentd to mount /var/lib/docker instead of /mnt/ephemeral/docker.

For the first issue, perhaps the kubelet should fail if it is not able to retrieve the docker root from docker info?

An alternative solution would be to mount our volume for AWS to /var/lib/docker instead of /mnt/ephemeral/docker. This would solve both issues. But, it seems that the kubelet is providing the ability to dynamically locate the docker root for some reason.

**Comment by iterion** [comment]
@a-robinson @jimmidyson Any thoughts on what the preferred approach for fluentd on AWS? I'm happy to work on a PR, I'm just not sure what the best path is.

**Comment by a-robinson** [comment]
As you mention, there appear to be two issues here -- one between the kubelet and docker, and one with fluentd. However, if I'm understanding correctly, the fluentd issue is purely a symptom of the kubelet/docker issue.

Unless you're using a very old version (which you don't appear to be), fluentd shouldn't actually be using the /var/lib/docker path at all. I'll send a PR to remove it from the pod manifest yaml files.

For containers' logs, fluentd relies only the symlinks in /var/log/containers (see the config [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/td-agent.conf)), which are created by the kubelet. If the kubelet is using the wrong docker root, then the symlinks will either not exist or have no data, which will cause fluentd to not collect the logs.

**Comment by a-robinson** [comment]
cc @kubernetes/goog-node for the docker root race

**Comment by jimmidyson** [comment]
@a-robinson That's not quite right. The kubelet creates symlinks to the container logs in the docker root - see the code at https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1405-L1410.

**Comment by jimmidyson** [comment]
So both the docker root & `/var/log/containers` need to be mounted inside the fluentd container - right now the fluentd pod has `/var/lib/docker` hard coded as a mounted host dir IIRC.

**Comment by a-robinson** [comment]
So basically I'm dumb and don't understand how symlinks work -- mounting /var/log/containers/ doesn't help unless the files being symlinked to are also mounted?

**Comment by jimmidyson** [comment]
That's right. Symlinks are just like pointers to the real location. If that location is unreadable the symlink can't be followed.

**Comment by jimmidyson** [comment]
I'm not sure of a good solution to this TBH. With the `json-log` driver for Docker (which Kubernetes relies on for `kubectl logs`) logs to docker root which is configurable on the host. We need to know that dir to mount for log symlinks to work.

**Comment by iterion** [comment]
@jimmidyson @a-robinson the necessity of mounting both the symlinks and the dir they're linked to seems to fit with the problem I'm seeing.

For AWS, would it be easiest to have salt create a different template with the correct log path for the fluentd pod?

**Comment by jimmidyson** [comment]
@iterion Good idea - that would be easiest for those using salt for deployments. I'd like to think of a more generic solution though if possible.

**Comment by dchen1107** [comment]
@a-robinson I am assigning this to you since you are looking into it already. Feel free to unassign it.

**Comment by MartinSoto** [comment]
Being hit by this right now. Any suggestions for a workaround. Is fixing the fluentd containers manually a solution at all? What happens when new nodes are added to the cluster?

**Comment by vishh** [comment]
#25712 attempts to address the docker log path issue.

**Comment by 1gnition** [comment]
@iterion 

How did you change the Fluentd pod configuration? This is a managed add-on pod and any changes to it are overridden automatically by the master node (https://github.com/kubernetes/kubernetes/tree/release-1.3/cluster/addons).

The instructions say that you need to edit the yaml on the master node's filesystem (`/etc/kubernetes/addons`). Unfortunately, the Fluentd yaml is not there. I'm trying to apply the workaround but it's impossible.

Any ideas?

**Comment by so0k** [comment]
I'm also hitting this issue, on Kubernetes 1.3 - just used the `kube-up.sh` to create  cluster on AWS with `KUBE_ENABLE_NODE_LOGGING=true` and `KUBE_LOGGING_DESTINATION=elasticsearch`

@1gnition - currently `kube-up.sh` deploys fluentd agent on each node [by dropping the yaml definition under `/etc/kubernetes/manifests/`](https://github.com/kubernetes/kubernetes/tree/v1.3.2/cluster/saltbase/salt/fluentd-es)...
so, that would be the location to edit the file - but it would not work when you scale up/down your nodes as you'd have to manually patch them each time...

Ideally fluentd is deployed as a Daemonset, similar to the [node-problem-detector](https://github.com/kubernetes/kubernetes/blob/v1.3.2/cluster/addons/node-problem-detector/node-problem-detector.yaml) definition

**Comment by 1gnition** [comment]
@so0k 

Thanks for the info. I did not find the yamls at `/etc/kubernetes/manifests/...`. In the end we just created a new cluster with `KUBE_ENABLE_NODE_LOGGING=false` and created out own Fluentd yamls as a daemon set, and added a volume mount for `/mnt/ephemeral/docker` ourselves.

This issue is really nasty, I hope a fix will arrive soon

**Comment by so0k** [comment]
agreed, better not to enable node_logging and manually deploy the logging as daemon sets - `kube-up` is being deprecated, but the alternatives (kops?) don't seem to be there yet..

**Comment by vishh** [comment]
cc @matchstick

**Comment by so0k** [comment]
For anyone coming here - the PR to deploy the logging add-on as a DaemonSet instead of a drop-in manifest on the nodes is linked here: https://github.com/kubernetes/kubernetes/issues/15324

The reason it's not in 1.3 seems to be a missing feature to handle upgrades... (the DaemonSet needs NodeSelector to ensure a single fluentd agent per node by filtering on the kubelet version running on the node)

**Comment by so0k** [comment]
Overall, future of Logging is best summarised in https://github.com/kubernetes/kubernetes/issues/24677 - will most likely move away from streaming everything to stderr / stdout to ease tagging of logging source.

**Comment by aneeshd16** [comment]
Just hit this after setting up a cluster on AWS using 1.3.2. I understand that some solid fixes are underway, but are there any recommended hacks/workarounds for this? k8s newbie here, will this issue happen everytime i set up a cluster?

**Comment by jimmidyson** [comment]
I wonder if for now we can just mount some host paths that are defined in a lot of deployments? Mounting `/mnt/ephemeral/docker/containers` & `/mnt/sda1/var/lib/docker/containers` (for minikube) even if the dirs don't exist on the host should be fine & allow symlinks from `/var/log/containers` to be followed again on more platforms. Thoughts @a-robinson?

**Comment by matchstick** [comment]
@saad-ali Does 1.3.4 address this?

**Comment by saad-ali** [comment]
> @saad-ali Does 1.3.4 address this?

@matchstick No this is unrelated to the volume stack. It is about docker container mounting. @kubernetes/sig-node should be able to provide more insight.

**Comment by jimmidyson** [comment]
I've been running with my suggestion above of multiple mounts, even if target dir doesn't exist on the host, & it's working fine. I know this doesn't handle arbitrary docker roots, but it would allow us to handle a number of known locations, such as the aws one detailed in this thread.

**Comment by rca** [comment]
Going by @iterion's comment above, I ran the following on each system and after some minutes logs started appearing:

```
sudo systemctl restart kubelet
```

The lag possibly due to  kubelet sorting out symlinks in `/var/log/containers` ?

**Comment by bgrant0607** [comment]
This has got to be obsolete
