### ISSUE TITLE
Include SSH host fingerprint with node registration

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#13328]
Follow on to #13326. When the node registers with the master, it should probably tell the master its host fingerprint as well. Then when we try to tunnel back, if anything hinky happens like #13326, it's easy to detect.

cc @cjcullen

**Comment by roberthbailey** [comment]
@gmarek is modifying what information is stored about a kubelet in https://github.com/kubernetes/kubernetes/pull/12655.
