### ISSUE TITLE
local-up-cluster.sh should give an error if openssl fails

### ISSUE THREAD

**Issue by copejon** [kubernetes/kubernetes#13321]
Running hack/local-up-cluster.sh without OpenSLL installed causes the apiserver to timeout.  The error is masked in the script in `function set_service_accounts`.

**Comment by copejon** [comment]
@jayunit100

**Comment by jayunit100** [comment]
Yup, just need to check that the command exits 0

**Comment by pavelbucek** [comment]
this is not just about OpenSSL. I had very same issue with missing "sudo" command.

see around line 225:
```    sudo -E "${GO_OUT}/kube-apiserver" ${priv_arg} ${runtime_config}\
      --v=${LOG_LEVEL} \
      --cert-dir="${CERT_DIR}" \
      --service-account-key-file="${SERVICE_ACCOUNT_KEY}" \
      --service-account-lookup="${SERVICE_ACCOUNT_LOOKUP}" \
      --admission-control="${ADMISSION_CONTROL}" \
      --insecure-bind-address="${API_HOST}" \
      --insecure-port="${API_PORT}" \
      --etcd-servers="http://127.0.0.1:4001" \
      --service-cluster-ip-range="10.0.0.0/24" \
      --cors-allowed-origins="${API_CORS_ALLOWED_ORIGINS}" >"${APISERVER_LOG}" 2>&1 &```

**Comment by dims** [comment]
openssl failure has been addressed here:
https://github.com/dims/kubernetes/commit/e9045bea222823d12449fd98ac305225e21ab87b

So we should close this issue

**Comment by dims** [comment]
@copejon @bprashanth Can we please close this issue?
