### ISSUE TITLE
Can we simplify cloud PersistentVolume creation?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#13338]
As I understand it, at the moment persistent volume creation is a two-step process:
1. I call the underlying cloud provider to create the volume (e.g. `aws ec2 create-volume`)
2. I edit a template pv.json document to insert the ID of the volume I created, and I then call `kubectl create -f ...`

I propose that the pv.json document tolerate a missing volumeID (or perhaps recognize a magic value), and create the volume should be created automatically.

A few questions:
1. I know we have some more ambitious ideas about automatically maintaining a pool, but I can't find those efforts.
2. Does this particular idea sounds like a good one?
3. Is it OK to write the volume ID back into the spec?  An alternative could be to use tags (at least on EC2) to do this without needing a volumeID at all (e.g. I could write the PV UUID as a tag)
4. Any thoughts on missing-field vs a "magic value" like `auto`

cc @markturansky as I believe you are the guru here

**Comment by iterion** [comment]
@justinsb I found this https://github.com/kubernetes/kubernetes/pull/10580/files for PVC which is maybe part of changes to enable this or the pool functionality?

I would really like to see this. I was a bit confused when I first used persistent volumes. To me it felt as if the default should be to create a volume on the cloud provider.

**Comment by markturansky** [comment]
We've proposed one way to maintain pools of storage.  https://github.com/kubernetes/kubernetes/pull/6773

When controllers are more pluggable, I think it should be easy to swap out one controller (that binds claims to pools) with another (that creates PVs on demand to the spec in the claim).  Both would watch  PVCs.  The object model doesn't have to change.

Creation on demand has been asked for internally at Red Hat, too.  I think swapping out a controller is the easiest way to customize this behavior.

**Comment by markturansky** [comment]
@kubernetes/rh-storage

**Comment by wattsteve** [comment]
@justinsb As Mark mentioned in https://github.com/kubernetes/kubernetes/pull/6773 Dynamic Provisioning will allow for storage assets to be automatically created and registered as Persistent Volumes. This is the "cattle storage" model. A Kube Admin can declaratively submit a request to create x amount of persistent volumes for storage type y and Kube will make it happen. The issue is that not all storage runtimes/vendors support a RESTful interface for provisioning and management, there's not too much the Kube project can do about that.

**Comment by justinsb** [comment]
I'm going to close as we have dynamic provisioning now.
