### ISSUE TITLE
EnsureTCPLoadBalancer always tears down forwarding rule & target pool

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#13333]
See: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L363

This means that any controller-manager restart or other sync will cause all external services to get new IPs. I don't think that is good.

**Comment by cjcullen** [comment]
Looks like the refactor in #8366 introduced this, so it isn't on the 1.0 branch.

**Comment by cjcullen** [comment]
@a-robinson

**Comment by cjcullen** [comment]
@lavalamp

**Comment by lavalamp** [comment]
> all external services to get new IPs

I agree we should probably avoid that if possible.

**Comment by a-robinson** [comment]
This will be fixed by #13335

**Comment by davidopp** [comment]
@brendandburns after discussion with @a-robinson and others we decided to make this a v1.1 blocker. This is currently assigned to you -- do you have time to work on it, or should we reassign?

**Comment by davidopp** [comment]
Oh, and @a-robinson clarified that the comment above about this being fixed is not correct (or at least, not complete): "#13335 (and its successors) fixed the fact that #13333 would cause service's external IPs to change when the bug triggers, but not that it causes all the resources to be deleted and recreated, leading to some amount of downtime."

**Comment by a-robinson** [comment]
I've confirmed @brendandburns hasn't done anything for this, so I'll work on a fix.
