### ISSUE TITLE
Type of object in WatchEvent is incorrect in swagger json schema

### ISSUE THREAD

**Issue by cjellick** [kubernetes/kubernetes#13337]
The type of the object property on the WatchEvent in the json schema is reported as a string but in reality it can be the object being watch, a status object, or (I think) a string in case of delete ([basing that assumption off of this bit of documentation](https://github.com/kubernetes/kubernetes/blob/64e5e1a2ddd5b30de6a5139876d41e0a90ecd3ac/pkg/watch/json/types.go#L37))

**Comment by lavalamp** [comment]
WatchEvent.Type should always be a string-- if that's not the case, please let us know what you're doing and we'll fix it. The comment you linked to applies to WatchEvent.Object, not .Type. Please reopen if this doesn't match what you see.
