### ISSUE TITLE
Alpha release mechanics issues

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#13339]
This is a tracking bug for all the stuff that's needed to push new 1.1.0-alpha.x releases. I did this mostly manually for alpha.1.

* [ ] We need to fix `mark-new-version.sh` to handle the tag. This isn't a big deal. After you choose a build, you can just tag it on `master` and push the tag and things will just magically work.
* [ ] `build-official-release` isn't accepting the right regex. I hacked it to make it work.
* [x] `push-official-release` isn't accepting the prerelease regex. I hacked it to make it work. Actually, this is wrong anyways. It shouldn't be an official release, because otherwise it'll bonk `latest.txt`, so I pushed it as a CI build for now until we figure out where it belongs in GCS. (Actually, even `push-ci-build` is wrong because it bonks the CI `latest.txt`, so we just need something else here. Bleh.)
* [x] Release notes: The tool for `master` was broken because we hadn't run it after The Great Rename and Shuffle: #13343.

Other than that, it seems like we're in somewhat sane shape.

**Comment by ihmccreery** [comment]
- I can work on `mark-new-version.sh`.
- `build-official-release` and `push-official-release

**Comment by ihmccreery** [comment]
Alternatively, we could add other scripts, `build/push-pre-release.sh`, which pushes to `prerelease/`.  I'm not sure what we'd gain from that, but zml@ said he didn't want to pollute the `release/` directory.  I think pushing to `release/` would make testing easier, (no need to change configurations when moving from prerelease validation to official release validation).

(cc @quinton-hoole)

**Comment by ihmccreery** [comment]
We also need to update https://github.com/kubernetes/kubernetes/blob/master/docs/devel/releasing.md.

@zmerlynn Are we expecting to do `beta` releases too?  If not, should we be calling this `rc`, not `alpha`?

**Comment by ihmccreery** [comment]
I've renamed this issue and am going to own trying to get release versioning into a state that is usable for release validation.  Already merged #15340, which is a start at describing where we're headed.

**Comment by ihmccreery** [comment]
I've added this to v1.1, because we need to fix the way we cut releases so that the release branch gets properly tagged with beta tags, (i.e. when we cut `v1.1.1`, we need to tag the same commit as `v1.1.2-beta`).

**Comment by ihmccreery** [comment]
Status update: with #14959 and #15422, we can now use `push-ci-build.sh` to push an alpha prerelease version, e.g. `v1.2.0-alpha.2`.  It will properly overwrite `latest-1.2.txt`, `latest-1.txt`, and `latest.txt` but won't clobber `latest-1.1.txt`.

No progress has been made on any other fronts, as far as I'm aware.

**Comment by ihmccreery** [comment]
> We need to fix `mark-new-version.sh` to handle the tag. This isn't a big deal. After you choose a build, you can just tag it on master and push the tag and things will just magically work.

In the long run, we should split tooling for marking a new beta version, official version, and alpha version, but that hasn't yet been done.

**Comment by ihmccreery** [comment]
With #16102 in, I'm closing in favor of #16773.
