### ISSUE TITLE
Fix make-release-notes.sh (in kubernetes/contrib)

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#13343]
The shuffle to contrib means the wrapper script is no longer usable, so relnotes for `1.1.0-alpha.1` are currently lame.

**Comment by zmerlynn** [comment]
(https://github.com/kubernetes/kubernetes/releases/tag/v1.1.0-alpha.1 needs to be filled in, and I'm OoO next week.)

**Comment by ihmccreery** [comment]
Additionally, the script never took into account the possibility that a PR might be updated after it was merged.  It sorts on last updated, then when it hits the oldest PR it's looking for, it assumes all others are older, even though they might have been merged after the oldest PR, but before that PR was commented on.

**Comment by ihmccreery** [comment]
`make-release-notes.sh` should also filter on the `release-note` [tag](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Arelease-note+).
