### ISSUE TITLE
We should remove NotReady nodes from a load balancer

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#13346]
Currently, we add all known nodes, regardless of their status to a load balancer.   We should probably not add `NotReady` nodes, since they aren't health checking.

@a-robinson @thockin

**Comment by resouer** [comment]
but, I found knowing which Node is NotReady help me to understand what's going on in the cluster. (I can't remember which node I ever added)

**Comment by resouer** [comment]
So, I think we should delete the Node after a "slack time"? @brendandburns

**Comment by resouer** [comment]
ignore my original comments, since i did not notice the load balancer. then this issue seems more like a bug now. and when node come back, proxy should be able to build the iptables rules. #dibs anyway.

**Comment by davidopp** [comment]
IIUC this is talking about a GCE load balancer, not the endpoints of a service?

**Comment by resouer** [comment]
@davidopp my bad, I already deleted my original comments, in case of misleading other people ...

**Comment by lavalamp** [comment]
Better yet, why not configure a health check for the load balancer, then we won't have a 5 minute delay where the loadbalancer is sending traffic to a down node?

**Comment by a-robinson** [comment]
Agreed that health checks make more sense. It's not as general of a solution though since the openstack and AWS cloud providers will need to have health checks added as well, and upgrading to a new version of k8s won't update existing load balancers to have health checks.

The other downside is that GCE health checks require an HTTP endpoint to hit. We can use the kube-proxy's /healthz, but that's relying on the kube-proxy to be running on the expected port, which I don't believe is actually a requirement, is it?

**Comment by thockin** [comment]
There's no guarantee that kube-proxy will be up in general.  In Borg we
health-check for a third-party daemon that we know is very very reliable.
We could do the same here.

**Comment by brendandburns** [comment]
If kube-proxy isn't up, we really shouldn't send traffic to that node (since who knows what will happen once it gets there)

I think it's legit to health check on the kubelet /healthz path.

**Comment by smarterclayton** [comment]
We should check both things (load balancers have to have health checks integrated in order to catch restarting pods becoming ready).  not sure what the best way to deliver that health check info to the LB is...

**Comment by thockin** [comment]
I think the 0th thing we can do here is to put a health-check on the cloud load-balancer.  #14661

The more difficult thing to convince ourselves of is whether the kubelet->pod healthcheck is good enough and propagates fast enough (kubelet -> apiserver -> other kube-proxies) or whether we need another lebvel of health-check.  The userspace kube-proxy will retry failed connections, but the iptables implementation is less flexible #14399

**Comment by brendandburns** [comment]
I realized that to do this, we need to expose the service to the public internet.  We can lock it down with firewalls, but it will still need to listen on the external IP for the machine.

I'd really prefer to use kube-proxy instead of a dummy daemon as the health check interface, but I don't know how I feel about exposing kube-proxy to the wilds of the internet...

I suppose we could just use a simple nginx proxy that only proxies the health check across, I worry a little about resource usage there, but it's probably not too bad.

**Comment by thockin** [comment]
A dummy daemon can be VERY lightweight, but it is yet another thing to
manage...

**Comment by rvrignaud** [comment]
@brendandburns Does https://github.com/kubernetes/kubernetes/pull/16443 remove nodes from load balancers if they become NodeNotReady after service creation ?

**Comment by brendandburns** [comment]
Yes.  Leaving open to consider adding explict health checks too...

**Comment by thockin** [comment]
@freehan

**Comment by davidopp** [comment]
@brendandburns Are you planning to work on this? If not, please bump it to P2.

**Comment by bgrant0607** [comment]
Related: #8673, #14661

**Comment by thockin** [comment]
@MrHohn please take anything useful and de-dup this with the other one for healtchecks.

**Comment by MrHohn** [comment]
The original issue "remove NotReady nodes from a load balancer" is fixed by #16443. The remaining purpose "adding explicit health checks" is being track by #14661. I'm closing this one to not have multiple issues tracking the same thing.

/assign
