### ISSUE TITLE
Difference between the kubectrl docs and  the getting started guide

### ISSUE THREAD

**Issue by bobef** [kubernetes/kubernetes#13359]
Here http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html it says

```sh
kubectl -s http://localhost:8080 run-container nginx --image=nginx --port=80
```

but here http://kubernetes.io/v1.0/docs/user-guide/kubectl/kubectl.html or when you run kubectl there is no `run-container`, only `run`.

**Comment by bgrant0607** [comment]
cc @brendandburns

**Comment by bgrant0607** [comment]
Fixed.
