### ISSUE TITLE
The secret data is not allowed to be more than 253 characters?

### ISSUE THREAD

**Issue by ntquyen** [kubernetes/kubernetes#13357]
May be it is the new constraint for creating secret. If so, how do I attach private key for git cloning?

```
...
data:
  id_rsa: "encoded_base64_private_key_definitely_greater_than_253_characters..."
...
```

error:
```
The Secret "bitbucket-secret" is invalid:data[id_rsa]: invalid value 'id_rsa': must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
```

**Comment by thockin** [comment]
@pmorie

**Comment by lavalamp** [comment]
As you can see here, that message is about the key, not the data:

https://github.com/kubernetes/kubernetes/blob/e5ac41331119bb8c67004b8efaa0c3d942b31d3a/pkg/api/validation/validation.go#L1493

So I suspect that your yaml/json is doing something you don't expect. Can you paste it here?

**Comment by liggitt** [comment]
underscore isn't an allowed character in secret data keys yet, so id_rsa doesn't match the regex

**Comment by ntquyen** [comment]
Oh, sorry I though the error is about the value!!! Thanks @liggitt @lavalamp
