### ISSUE TITLE
should 'gitRepo' volumes have 755 permissions instead of 750?

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes#13361]
As part of a pod, I'm creating a shared volume from a github repo, used by multiple pod containers.
(This is a workaround, as I really would like to use something like 'volumes-from' instead, as discussed in #831).

One of them is an nginx container.  If I run it like this, directly via docker, the volume mount works fine:

    docker run --name frontend -v <frontend_dir>:/usr/share/nginx/html:ro -d -p ${PORT}:80 nginx

But in the pod, done as in the snippet below, I get permissions issues.  The `/usr/share/nginx/html` directory has 750 permissions.  If I exec into the running container and do a chmod 755 on the `html` dir, all is well.  Should volumes from repos have 755 permissions by default? (Or am I missing a config option?)

This is for an example, so for simplicity I'd prefer not to wrap the nginx image in another layer just to do the chmod.

    ..
      image: nginx
      volumeMounts:
      - name: frontend
        mountPath: /usr/share/nginx/html
    ...
    volumes:
    - name: frontend
      gitRepo:
       repository: https://github.com/<frontend_repo>.git

**Comment by brendandburns** [comment]
We just do a straight git clone.  Is this a difference in the git repo?  I don't think we want to manipulate permissions on top of git...

**Comment by amygdala** [comment]
Hmm. If I do a 'git clone' of the same repo locally, the created directory has 755 permissions, even if the test parent directory has 750 permissions.  I don't know what the difference is, but the direct docker mount of a dir with the same permissions into the same path in the container does end up with 755 permissions.

However, as you say, it doesn't sound like a good idea to mess arbitrarily with the result of the git clone.

Okay to close this you want-- if someone else hits the same thing they can find it and comment.  (don't think it's a 'support' bug per se).

**Comment by thockin** [comment]
umask?

**Comment by pmorie** [comment]
@thockin agree it might be the kubelet running w/ umask set
