### ISSUE TITLE
kubectl port-forward not working on gcloud

### ISSUE THREAD

**Issue by apobbati** [kubernetes/kubernetes#13360]
I am having an issue with the `kubectl port-forward` command when interacting with a container cluster on gcloud.

Here's a the log output:

```
kubectl port-forward -p my-pod 0:8080

I0830 11:38:09.169210   51213 portforward.go:225] Forwarding from 127.0.0.1:60458 -> 8080
I0830 11:38:09.169496   51213 portforward.go:225] Forwarding from [::1]:60458 -> 8080
I0830 11:38:24.586552   51213 portforward.go:251] Handling connection for 60458
I0830 11:38:24.960589   51213 portforward.go:251] Handling connection for 60458
I0830 11:38:24.965366   51213 portforward.go:251] Handling connection for 60458
I0830 11:38:24.970032   51213 portforward.go:251] Handling connection for 60458
I0830 11:38:24.975280   51213 portforward.go:251] Handling connection for 60458
I0830 11:38:24.979826   51213 portforward.go:251] Handling connection for 60458
E0830 11:38:55.341548   51213 portforward.go:310] An error occurred forwarding 60458 -> 8080: Timed out waiting for data stream
E0830 11:38:55.341712   51213 portforward.go:310] An error occurred forwarding 60458 -> 8080: Timed out waiting for data stream
E0830 11:38:55.341782   51213 portforward.go:310] An error occurred forwarding 60458 -> 8080: Timed out waiting for data stream
E0830 11:38:55.341812   51213 portforward.go:310] An error occurred forwarding 60458 -> 8080: Timed out waiting for data stream
```

Is there anything I'm missing here? Can you point me to any troubleshooting guides?
Thanks!

**Comment by apobbati** [comment]
The target pod wasn't listening on all interfaces. Works fine now.

**Comment by apobbati** [comment]
Actually, its not working properly. The request seems to timeout.
I'm running a single RethinkDB container (https://hub.docker.com/_/rethinkdb/). I have started the rethinkdb server with `--bind all` to listen on all interfaces but it still times out.

**Comment by lavalamp** [comment]
I think in GKE this may be limited to a few minutes? @cjcullen probably knows more.

**Comment by cjcullen** [comment]
I don't know exactly how `kubectl port-forward` works, but I'm assuming it uses the `/proxy/` endpoint. On GKE, the proxy works through SSH tunnels that are refreshed (closed and replaced) every 5 minutes. I have another issue open tracking the problems with this: https://github.com/kubernetes/kubernetes/issues/12179

It sounds like that may be causing this issue as well?

**Comment by lavalamp** [comment]
Yes, this is a dup of #12179. I will bump that priority and close this.
