### ISSUE TITLE
Pod-to-self networking require hairpin mode

### ISSUE THREAD

**Issue by MikaelCluseau** [kubernetes/kubernetes#13375]
Linked to #3760, when using the iptables proxy instead of userspace, a pod can connect to a service IP it serves, looping back to itself. In this case, the Linux bridge implementation stops the packet from being processed because it then has the same input and output interfaces. 

The solution to this problem is to enable the hairpin of each port of the virtual bridge where the pods are connected. It should be equivalent to the following shell script:

```
# To get traffic from a pod to itself via a service:
for intf in $(ip link list | grep veth | cut -f2 -d:); do brctl hairpin cbr0 $intf on; done
```

/cc @thockin

**Comment by thockin** [comment]
Better heuristic:

for intf in /sys/devices/virtual/net/cbr0/brif/*; do echo 1 > $intf/hairpin_mode; done

The only tricky part is knowing the name "cbr0"

**Comment by MikaelCluseau** [comment]
I don't know yet the internals, but I was going to look for the interface holding the pod's IP to set up hairpin on deploy, right after the "pause" container is created.

**Comment by thockin** [comment]
No matter what we do this is going to be a bit hacky - we need to move all
the networking stuff out into a plugin, but we need to solidify the plugin
interface first.

**Comment by MikaelCluseau** [comment]
I'll keep that in mind :-) The main point is that I see this code run in the kubelet, I hope I'm not wrong.

**Comment by thockin** [comment]
that's correct :)

**Comment by evanphx** [comment]
@thockin @MikaelCluseau I took a crack at implementing this. It's a bit of a hack but it covers the requirements and also nicely performs some anti-entropy on the interfaces in case something is missed.

**Comment by thockin** [comment]
fixed

**Comment by shettyg** [comment]
I connect my pod interface to a Open vSwitch bridge. Since this code does not find a peer interface on a linux bridge, it just enabled hairpin mode in every linux bridge on my host. This completely breaks my host where I do not want hair pin mode enabled. It took me a good 2 days to figure out why things break in my setup. This feels like a very bad way to solve problems.

**Comment by MikaelCluseau** [comment]
@shettyg Thank for the feedback. This fallback is considered the safest, since it logs the switch to fallback mode at the info level, but this can change. The simplest "fix" is probably to provide an option.

@thockin Should we (1) include an option to disable the fallback, (2) another one to disable hairpin mode completely? (3) Try to detect if the container's interface is a veth? I think (1) is enough to quickly fix the issue, then I'd go for (3). I also see that with the libcontainer's version bump of 15 oct., it now includes this:

```
libcontainer/configs/network.go:50:     HairpinMode bool `json:"hairpin_mode"`
```

But I suppose this is not going to be widely deployed anytime soon.

**Comment by thockin** [comment]
@shettyg I lost track of this because it is buried in a closed issue.  I assume this is still an issue?  Might be worth opening a new bug.

Can you find the "Unable to find pair interface, setting up all interfaces" log line in kubelet and tell me what the remainder of the error is?

**Comment by thockin** [comment]
I'll open an issue.

**Comment by MikaelCluseau** [comment]
The line with the log:
https://github.com/kubernetes/kubernetes/blob/916ddbca654a429868321e3e583982a01bb8d55c/pkg/kubelet/network/hairpin/hairpin.go#L49

It should be easy to add a command-line flag.

**Comment by AdoHe** [comment]
@MikaelCluseau what do you think about this pr #19490 and also I add some comments on this issue #19766, what do you think about this?

**Comment by MikaelCluseau** [comment]
@AdoHe Thank for letting me know, I put my thoughts where they apply :-)

**Comment by AdoHe** [comment]
@MikaelCluseau Ok, I will take a look and try to find a better solution.
