### ISSUE TITLE
Provide proxy option when gcr.io is banned

### ISSUE THREAD

**Issue by ulucaydin** [kubernetes/kubernetes#13396]
For enterprises, it's very likely that gcr.io is restricted/banned hence a created Kuberentes cluster on a local environment fails to proceed since it cannot pull images such as gcr.io/google_containers/pause, which are currently hard-coded into the code.

**Comment by lavalamp** [comment]
Proxying to gcr.io is probably a bad idea in such environments, as it'd be circumventing security rules. Instead, you'll need to preload the necessary containers on your nodes.
