### ISSUE TITLE
Gracefully handle cloud provider api downtime

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#13398]
Kubelet doesn't update node status if it can't access the cloud provider api: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2127 which leads to the whole node NotReady chain reaction nodecontroller side. Feels like the kubelet can just continue using node.Status.Addresses to update status till the partition recovers. Can this lead to split brain? 

@roberthbailey

**Comment by jfoy** [comment]
I have an internal patch doing exactly this; I'll send a PR when it's ready.

**Comment by gmarek** [comment]
assigning @yujuhong as she's reviewing corresponding PR.

**Comment by brendandburns** [comment]
Closing this since it was addressed by 313417
