### ISSUE TITLE
`echo foo | kubectl exec -i <pod> cat` hangs instead of cleanly exiting

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#13394]
If you run the following

    echo foo | kubectl exec -i <pod> cat

it will print out foo and hang instead of returning control to the user in the shell. This is due to various changes to how go-dockerclient handles attach and exec.

I am working on a fix and will have a PR soon.

**Comment by lavalamp** [comment]
dup of #13395?

**Comment by ncdc** [comment]
Not a dupe - they have different root causes.

**Comment by liggitt** [comment]
one is non-interactive terminating stdin, the other is interacting non-terminating stdin

**Comment by lavalamp** [comment]
Gotcha, thanks for clarification.
