### ISSUE TITLE
Enable testing fields based on util.Time

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#13399]
Based on discussion https://github.com/kubernetes/kubernetes/pull/12894#discussion_r38253051

There is no way right now to control the behavior of util.Time for tests. Hence, timestamp fields set based on that cant be tested properly.
We need a way to test that.
@bgrant0607 suggested using a simulated clock. util.Now should take a clock interface. We can pass a standard clock in our code, but pass a simulated code in tests.

cc @lavalamp

**Comment by lavalamp** [comment]
We already have (or had) a fake clock in util package. Code that needs to be tested that uses a clock should accept a clock at creation time. Let's avoid making a global fake clock if we possibly can.

**Comment by davidopp** [comment]
Is the behavior you want in tests "a clock that returns a value I can specify" or "a clock that ticks at a rate I control"? I assume it's the former?

**Comment by nikhiljindal** [comment]
Yes. My test just needs the former.
The scenario I want to test is:
When I call a function the first time, it should set a field as per time.Now().
Every time, I call the function again, based on some conditions, it should reset the field to time.Now() or continue using the old value.

I can test it using the later as well, tough.
