### ISSUE TITLE
Type of object in WatchEvent is incorrect in swagger json schema

### ISSUE THREAD

**Issue by cjellick** [kubernetes/kubernetes#13400]
@lavalamp You asked me to re-open #13337 if I still had an issue. I can't re-open that issue, so I'm creating a new one.

I was referring to WatchEvent.Object as it is described in the swagger API here:
https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L11287
It is being defined as a string in the API schema.

I'm currently attempting to attempting to generate structs based off of the schema definition and this one is inaccurate.

**Comment by lavalamp** [comment]
Ah, I'm sorry, I see you are right.

@nikhiljindal What should the swagger be for this field?

**Comment by nikhiljindal** [comment]
I guess it should refer to RawExtension model as defined here:  https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/types.go#L101 (which actually just contains a RawJson string field).
@bgrant0607 is it fine to expose RawExtension as part of our API models?

**Comment by lavalamp** [comment]
@nikhiljindal How would RawExtension's fields get exposed? Is there a way to just express "a json object"?

**Comment by nikhiljindal** [comment]
As per https://github.com/kubernetes/kubernetes/issues/4700#issuecomment-194725971, we can use `"type": "object"` to represent a JSON object.

**Comment by nikhiljindal** [comment]
We now have `"type": "*versioned.Event"` instead of `"type:"string"`. It should actually be `"type": "versioned.Event"` (without the pointer), which is tracked by https://github.com/kubernetes/kubernetes/issues/24240.
cc @smarterclayton 

Closing this one.
