### ISSUE TITLE
kube-up.sh should detect an 'out of cores' quota issue and exit

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes#13407]
Seems that kube-up.sh does not react gracefully to not having enough cores to bring up the whole set of nodes.  It should detect and exit.

Instead, it just keeps retrying, apparently indefinitely, e.g.

```
Waiting for group to become stable, current operations: creating: 2
Waiting for group to become stable, current operations: creating: 2
Waiting for group to become stable, current operations: creating: 2
Waiting for group to become stable, current operations: creating: 2
Waiting for group to become stable, current operations: creating: 2
Waiting for group to become stable, current operations: creating: 2
...
```

**Comment by quinton-hoole** [comment]
Yes, we should report this in a better way.

I ran into this today, and the problem was some leaked network forwarding rules from a previous test run.  I deleted those and all was good.  I'm still trying to diagnose how those rules are being leaked.

**Comment by quinton-hoole** [comment]
@amygdala FYI ^^

**Comment by amygdala** [comment]
In my case, I believe it was just a cores limit, and not due to a leakage.  For some reason the project I was using had only an 8 cores quota, which I didn't realize, and some were already in use.

(Though - I have seen leaked forwarding rules myself in earlier days.  I'm trying to remember the context.  It might have been some version mismatch with the cluster and the local installation causing issues running the kube-down script.  I don't think I've seen this recently).
