### ISSUE TITLE
Vagrant: Broken EXTRA_DOCKER_OPTS

### ISSUE THREAD

**Issue by technosophos** [kubernetes/kubernetes#13401]
During setup of a Vagrant cluster, it is not possible for `$EXTRA_DOCKER_OPTS` to ever get to a master or a minion. A bug in `cluster/vagrant/util.sh` is preventing the `$DOCKER_OPTS` environment from ever being overwritten.

The errant code appears in two places:
https://github.com/kubernetes/kubernetes/blob/master/cluster/vagrant/util.sh#L151
https://github.com/kubernetes/kubernetes/blob/master/cluster/vagrant/util.sh#L176

In both cases, there should be a colon (`:`) between `EXTRA_DOCKER_OPTS` and the trailing `-`.

**Comment by technosophos** [comment]
FWIW, I am waiting for a Corp CLA to go through before I contribute a patch. If it goes through in time, I'll submit a PR.

**Comment by lavalamp** [comment]
Yes, that looks like a clear bug. Will look forward to a patch, thank you!
