### ISSUE TITLE
We should handle flaky cloud provider APIs more gracefully

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#13412]
From: jonathanbweeks@gmail.com
... we experienced a catastrophic failure this morning when our in-house OpenStack cloud team went to upgrade from Juno to Kilo, and the OpenStack API went away for a period. (We are running Kubernetes on top of Openstack for our internal private cloud.)

We are still trying to completely grok the sequence of events, but from logs and source code inspection (we are on K8s 1.0.1):

1. The kubelets on each node periodically poll the cloud provider API to get network/IP interface information. When the API went away, this update starting failing, causing them to be marked as "Not Ready" by the controller-manager. This would be bad, as it would lead to the scheduler obviously not being able to schedule pods on the affected nodes (eventually all nodes)

However, it is exacerbated by:

2. The controller-manager eventually then ends up evicting (AKA killing) all pods on every "NotReady" node after a timeout (which is quickly all nodes in the K8s cluster)

This means that the entire cluster basically offs itself in a misguided violent purge. (But no one ever expects the Spanish Inquisition).

This issue was at least partially captured today in the IRC, and a related issue logged here: https://github.com/kubernetes/kubernetes/issues/13398

Now clearly, Openstack should have an HA API and allow seamless rolling upgrades, but cloud providers will likely have occasional unplanned API downtime, and kubernetes needs to be more tolerant and robust in the face of that (at the very least, not kill all running pods :)

We looked at various timeout config settings, but there seemed to be non-trivial side-effects to setting them to "high" values (we continue to investigate this). As a workaround, we are patching our kubelet to keep posting status even if the cloud provider is unavailable and will submit a pull request.

**Comment by brendandburns** [comment]
One option would be to introduce a Node `LameDuck` status/state which basically marked the node as unschedulable for future pods, but otherwise left it in the cluster.

**Comment by brendandburns** [comment]
@bgrant0607 @thockin @davidopp @lavalamp @smarterclayton

**Comment by brendandburns** [comment]
@davidopp said:

First, let me say I'm really sorry about the problem you had.

We are supposed to be rate limiting pod eviction (implemented by podEvictor in controllermanager.go). If this works properly and you do adequate monitoring, it should be possible to catch this kind of problem before it causes a catastrophe. In other words, (2) should eventually happen but it should take a long time.

It sounds like the rate limiting isn't working properly and/or we need to tune the parameters better. I'll take a look. I think this is the proper solution to this general class of problems.

This should as a side-effect provide the behavior Brendan is talking about, in the sense that such a node will be marked NotReady (hence no new work will be scheduled to it) but the evictions will not be executed yet.

**Comment by bgrant0607** [comment]
What happened exactly? Nodes shouldn't be dependent on a cluster-level control plane. 

Additionally, it would be reasonable for Kubelet to cache the information (even persistently -- #489) and not consider the lack of the ability to receive updates to be a problem, at least not for a longer period of time.

As for what type of conditions to add, they should reflect the status of the node, not the decision about what to do in response: Ready, Reachable, ...

**Comment by lavalamp** [comment]
I think the assumption that "cloud provider doesn't respond == node has been ejected" is just plain wrong, and if we model this uncertainty we can respond better in this situation. (If the node has been ejected, the cloud provider should answer the request and be angry at us--not silent.)

I think that probably looks like setting a flag and letting node controller decide if the problem is local to a single node or is with the cloud provider API.

I don't think marking `LameDuck` and not scheduling is a good solution, because it'll happen to all nodes in the cluster at once, so nothing will be schedulable anywhere. I think we should focus on not making the mistake at all before we talk about mitigating its harm.

**Comment by brendandburns** [comment]
fwiw, not scheduling anywhere is a lot better than deleted everywhere.

Let's take a scan at the podController rate limit code and make sure that it's actually working (and that we have an e2e for it ;)

**Comment by brendandburns** [comment]
also, @lavalamp the problem isn't that the node has been ejected, it could simply be that it's IP address has changed, in which case pro-actively asking the cloud provider is the only way you could know that.

**Comment by lavalamp** [comment]
@brendandburns If the node's IP has changed, then the cloud provider should actually return an error, in which case NotReady is a perfectly good thing to do. If the cloud provider is down, then the connection should not go through or you should get a low-level socket error or something, not a high-level cloud provider error. We should be able to tell the difference.

**Comment by jfoy** [comment]
I've submitted #13417 for the original issue, though it's a much more naive implementation than what is discussed here.

**Comment by jbweeks** [comment]
Agreed with @lavalamp above regarding potential handling of the scenario. Perhaps a policy configuration setting to decide between preferring scheduling availability with potentially stale IP address information versus potentially disabling all scheduling? It is a bit of a CAP-type decision -- availability vs potential inconsistency. For our operations, we would prefer to keep scheduling in this case (global cloud provider API unavailability), knowing that we might have potential stale IP information, but others might have different priorities.
