### ISSUE TITLE
kube2sky ignores insecure-skip-verify in kubeconfig

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes/kubernetes#13411]
Trying to set insecure-skip-verify:true in a kubeconfig for use by kube2sky.  However, the setting seems to be ignored (API requests fail with "certificate signed by unknown authority").

However, if a server is also specified in the kubeconfig, the insecure-skip-verify flag will be respected, and kube2sky can communicate with apiserver.

**Comment by thockin** [comment]
@jeffml @mikedanese - what is expected behavior here?

**Comment by lavalamp** [comment]
I think what is happening is that putting the server location in the kubeconfig file makes it not ignore the file.

**Comment by thockin** [comment]
Is that "correct"?

**Comment by aaronlevy** [comment]
Closing this as it's a year old, and I was probably being lazy at the time by not generating proper certs.
