### ISSUE TITLE
Generate 2.0 swagger spec

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#13414]
Our swagger spec is as per v1.2.
We need to move to v2.0.

We use https://github.com/emicklei/go-restful to generate our swagger spec, which generates 1.2 spec.
https://github.com/emicklei/go-restful/issues/157 tracks updating it to generate 2.0 spec.

cc @bgrant0607

**Comment by lavalamp** [comment]
What is the motivation for the upgrade?

**Comment by paralin** [comment]
@lavalamp compat with dynamic clients and codegen for one.

**Comment by paralin** [comment]
Another case for this is that swagger-1.0 doesn't support key value responses. The type "any" on labels on ObjectMeta is currently making the labels field not parseable from code generated by swagger-codegen.

**Comment by paralin** [comment]
Also any reason to not use this?

https://github.com/go-swagger/go-swagger

**Comment by nikhiljindal** [comment]
Thanks for suggesting that @paralin 
Are you suggesting that as a replacement for go-restful?

At a quick glance it looks like its a CLI that supports generating server, client code from spec, but am not sure how can I use that to generate spec from our code.
Any pointers?

cc @casualjim who suggested the same https://github.com/emicklei/go-restful/issues/157#issuecomment-155246694

**Comment by paralin** [comment]
@nikhiljindal Tricky. I think it probably only supports spec -> code. Might have to just focus on updating go-restful unless there's some other solution here

**Comment by casualjim** [comment]
@nikhiljindal it has a free-style doc comment parsing API, it should be able to work with anything.
these 2 applications should show you some possible use cases. https://github.com/go-swagger/go-swagger/tree/master/fixtures/goparsing

Documentation is a bit of a WIP atm.

**Comment by casualjim** [comment]
I've created some docs for generating a spec from go code. I'm sure there are still gaps in there, but it's a start. http://go-swagger.github.io/generate/spec/

**Comment by bgrant0607** [comment]
@smarterclayton had some recent thoughts on Swagger 2.0 and go-restful.

**Comment by nikhiljindal** [comment]
cc @campoy

**Comment by smarterclayton** [comment]
go code to spec is interesting - that's essentially the protobuf path we are on (idl that generates equivalent go structs using gogoprotobuf).  We don't need a complex web framework because we handle most everything already as wrappers.  Also, eventually we'll need to tune something in that stack, and I'd prefer a simpler stack over a full featured one (we have 100 lines of API registration, ease of input is not our primary goal).

**Comment by smarterclayton** [comment]
The lib linked above looks a lot a lot like the go code to idl work, which is encouraging.

**Comment by casualjim** [comment]
I also found a protoc-gen-swagger which takes protobufs and generates a swagger spec for it. There is a bit of a mismatch between the 2 toolsets though in terms of what they support.
For go-swagger I do have this: https://github.com/go-swagger/go-swagger/issues/143

Which is something I think is entirely possible to get protobuf as a wireformat, but still use swagger to describe the full contract of the API, including validations and documentation.

**Comment by smarterclayton** [comment]
Don't get me wrong - proto idl is insufficient to get full fidelity
round trip from go -> idl -> go, so a specific client that takes go as
input is the right approach I think

**Comment by mward29** [comment]
Hey folks, Any progress or workarounds on this? Before knowing of this issue, we attempted to create a python library with codegen and ran into the same issue.

**Comment by casualjim** [comment]
This issue links a valid swagger 2.0 spec for kubernetes, I think it was generated with lucy.

https://github.com/go-swagger/go-swagger/issues/239

**Comment by smarterclayton** [comment]
Good to see that this is progressing - I'd like to see how it was done as well as I was poking around with generate on go-swagger last night to get a feel for the current remaining steps.

**Comment by casualjim** [comment]
The reporter of that bug shared this:

> To build a swagger kube client use make swagger. The client files will be located at pkg/kuber/{client, models}.

> spec 1.2 to 2.0 issues

> go-swagger only supports spec 2.0. You need to convert the kube 1.2 spec.

Converter tool: https://github.com/lucybot/api-spec-converter

```shell
api-spec-converter kube1.2.json --from=swagger_1 --to=swagger_2 > kube.json
replace: "$ref": "#/definitions/integer"VS."type": "integer"`

%s/"$ref": "#\/definitions\/integer"/"type": "integer"/g
```

v1.HTTPGet - Port types etc have the wrong type.

> kube has a type that is both string and int32.. pina.
> convert to interface{}
> HTTPGetAction#port
> TCPSocketAction#port
> ServicePort#targetPort #

**Comment by smarterclayton** [comment]
Oh, ok, so that's not what we need - we want to generate new kube 2.0 specs
directly from the codebase.  I thought this was from reading the source
code directly.

**Comment by smarterclayton** [comment]
* we want to generate kube 2.0 specs directly from the code base
eventually.  In the short term running the converter is a good bridge
solution.

**Comment by nikhiljindal** [comment]
@mward29 re: type "any". We are switching to using type "object" instead of type "any" which should fix your problem without having to wait for us to switch to swagger 2.0.
Ref https://github.com/kubernetes/kubernetes/pull/22897

**Comment by nikhiljindal** [comment]
cc @whitlockjc

**Comment by whitlockjc** [comment]
I would love to help with this.  Is there a suggested venue to get plugged in with the developers already involved in this?

**Comment by nikhiljindal** [comment]
You can join the [API machinery SIG](https://groups.google.com/forum/#!forum/kubernetes-sig-api-machinery) and add it to the agenda for our next hangouts: https://goo.gl/0lbiM9.
We also have a slack channel: https://kubernetes.slack.com/messages/sig-api-machinery/

**Comment by jayunit100** [comment]
cc @elmiko , re openshift updating to 2x swagger

**Comment by nikhiljindal** [comment]
With https://github.com/kubernetes/kubernetes/pull/30233, v1.4 apiserver will now publish swagger spec 2.0 at /swagger.json.
Thanks to @mbohlool

**Comment by smarterclayton** [comment]
Yeah, much thanks.

**Comment by mbohlool** [comment]
Swagger 2.0/OpenAPI spec feature is completed. There are always small improvements that I will do as part of other tasks.
