### ISSUE TITLE
Investigate whether we should spawn off a dedicated goroutine for global cleanup tasks

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#13418]
kubelet does a series of housekeeping/cleanup tasks, including removing pod directories, unmounting volumes, etc. The housekeeping tasks are currently intertwined with kubelet's main sync loop, and the frequency of housekeeping is uncertain.

We should investigate whether we should decouple housekeeping and individual pod operations by spawning a dedicated goroutine for it, and if we do, what the caveats are.

Related issue: #13311

/cc @vishh @pwittrock

**Comment by gmarek** [comment]
@yujuhong please mark as help-wanted or reassign.

**Comment by yujuhong** [comment]
@gmarek, my understanding is that I shouldn't assign the issue to myself if I don't plan to work on it anytime soon. Is it a new requirement to add help-wanted to every issue? :)

**Comment by gmarek** [comment]
I'm just seeing a lot of inactive 'investigate/consider/discuss' issues laying dormant. I think we should do something with this.

**Comment by yujuhong** [comment]
One issue will be that if the periodic cleanup routine relies heavily on the list of desired `api.Pod`s to decide what volumes/directories are not wanted. Basically, it grabs a snapshot of the desired pods, and a snapshot of currently visible volumes/directories and compare. 

If we spawn a dedicated goroutine for cleanup tasks, the main syncloop may be updating the list of desired pods in the meantime. The snapshot of the desired pods will be outdated, so the cleanup routine needs to get the latest snapshot of desired pods from the pod manager right before each cleanup task.

I am closing this issue.

**Comment by jingxu97** [comment]
I think we might at least use a seperate gorountine to cleanupOrphanedPodDirs() function. My understanding is if a pod becomes Orphaned, it will not comes back. So even during cleanup, the desired pods are changing, it should not be a problem. Reopen this issue for further discussion. 
cc @yujuhong
