### ISSUE TITLE
Write e2e test for eviction when node is NotReady (with and without grace period)

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#13429]
ref/ #13412 

@gmarek

**Comment by gmarek** [comment]
The test itself should be a simple modification of `e2e/reboot.go`, but we need to consider the cluster as well. Currently there's no way to change the value of flags controlling eviction/grace periods in runtime. If we don't want to wait for a few minutes doing nothing, we'd need to change the behavior of the whole e2e cluster, or spin up a new one for this test only. Both solutions have disadvantages.

Better solution would be to use config objects, that are planned for some future. Does anyone know what's the status of that effort? @bgrant0607 @lavalamp

**Comment by bgrant0607** [comment]
@tmrts is updating the proposal in #6477.

**Comment by gmarek** [comment]
Does it need to be an e2e test, or unit test will suffice?

**Comment by davidopp** [comment]
Can you do integration test?

**Comment by gmarek** [comment]
I guess I can, but I'm starting to need more priorities than p1 and occasional p0...

**Comment by davidopp** [comment]
This is really p1.5 IMO. We really need something between P1 and P2 (there are 281 open P2 issues, so we need something that means "more important than P2" but not P1...)

**Comment by gmarek** [comment]
My point exactly.

**Comment by davidopp** [comment]
Oh, I should have mentioned that's 281 open P2 *control-plane* issues. There are more than 1000 open P2 issues total.

**Comment by gmarek** [comment]
I'm missing 'depends on' option... I'd like to fix the eviction logic in NodeController before writing a test.

**Comment by davidopp** [comment]
ping -- this seems important (see #24200)

**Comment by gmarek** [comment]
P1 - if it's a P0, please explicitly mark it so:)

**Comment by gmarek** [comment]
It is actually done for quite some time, as a part of 'network-partition' e2e test.
