### ISSUE TITLE
Question on ResourceQuota

### ISSUE THREAD

**Issue by HaiyangDING** [kubernetes/kubernetes#13431]
I come up with this question when doing https://github.com/kubernetes/kubernetes/issues/13074

As we know ResourceQuota sets a limitation on the amount of resources that are allowed to be used by the Pods in the same namespace. Meanwhile, we also use resource *request* (not *limit*) to ensure each Pod (Container) to be able to use a certain amount of resource when needed, that is, the amount of "reserved" resources is specified by resource *request*, not *limit*. 

To this end, does it make more sense if we check ResourceQuota by using sum of resources *request* instead of *limit* (currently, ResourceQuota is verified by looking at the total resource limits of Pods in the namespace)

**Comment by gmarek** [comment]
This is a good point. @bgrant0607 @smarterclayton @davidopp

**Comment by bgrant0607** [comment]
See #12600
