### ISSUE TITLE
Log spam: <autogenerated>:29: Trying to convert 'conversion.ExternalTestType2' to 'conversion.TestType2'

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#13463]
This fills up Shippable tests, making them very hard to read.

**Comment by lavalamp** [comment]
@wojtek-t Do you know why this is printed so much?

**Comment by wojtek-t** [comment]
I have no idea...

**Comment by lavalamp** [comment]
This seems to be fixed now. Presumably something @ixdy tweaked?

**Comment by ixdy** [comment]
Yeah, #14298 probably fixed this.
