### ISSUE TITLE
No documentation on how to use kubelet API

### ISSUE THREAD

**Issue by apeeyush** [kubernetes/kubernetes#13470]
Hi,

I would like to use the kubelet API from `pkg/kubelet/server.go`. However, I could not find any documentation around it. Could someone pls. point me to the right place? Thanks :)

**Comment by coocla** [comment]
Here:  http://kubernetes.io/third_party/swagger-ui/

If you have your own kubernetes cluster, you can also find it from  http://apiserver:apiport/swagger-ui

**Comment by gmarek** [comment]
@apeeyush - did that answered your question?
@bgrant0607, @davidopp - do we plan on having some "real" doc about it?

**Comment by apeeyush** [comment]
@gmarek: No, it did not. The `swagger-ui` does not contain documentation for kublet API (for example `/attach`, `/pods`, `runningpods` etc.) and how to access them.

**Comment by bgrant0607** [comment]
No immediate plans, no. 

If I understand correctly, this is about the internal implementation rather than external APIs (which is covered by #1963 and #2098). 

If so, yes, we should document our code better. I don't know when we'll get to it, though.

What are you specifically trying to do?

cc @kubernetes/goog-node

**Comment by apeeyush** [comment]
Yup, it's about the internal implementation. Sorry I didn't see #1963 and #2098 before creating the issue!

I am planning to modify the scheduler and replication controller to add rescheduling and auto-scaling capabilities. It would be great if someone could point out a few (1-2, preferably in scheduler or replication controller) examples of API usage in code and I can try to understand the rest of it myself.

**Comment by pmorie** [comment]
@kubernetes/rh-cluster-infra

**Comment by yujuhong** [comment]
> I am planning to modify the scheduler and replication controller to add rescheduling and auto-scaling capabilities. It would be great if someone could point out a few (1-2, preferably in scheduler or replication controller) examples of API usage in code and I can try to understand the rest of it myself.

@apeeyush, the endpoints in `pkg/kubelet/server.go` are mostly for debugging, stats, and for one-off container operations such as `kubectl logs` or `kubectl exec`. None of the components you mentioned talks to kubelet directly, so they don't understand the kubelet API at all. Kubelet simply watches the pods via the apiserver, looking for pods that are assigned to itself. It then runs the pods if possible. You may want to read up on the scheduler code and/or issues related to the topics you are interested in, e.g., rescheduler design #12140

**Comment by apeeyush** [comment]
Thanks @yujuhong for the explanation :). I'll close this issue for now since it is anyways a duplicate.
