### ISSUE TITLE
Monitoring and managing the quota size of containers and local volumes

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#13479]
Today no process on the node manages the amount of storage in use for:
- Container CoW layers (the container's writable directory)
- Empty dir volumes
- Docker volumes created implicitly on startup of the container

Since neither Docker nor the host operating system can totally manage this, I think it should be possible to have a management loop in / around the kubelet to control the total usage of these elements.  Today, it's possible to write to the empty dir until you fill the filesystem, at which point all pods fail.  You _could_ set quotas (if the uids of the processes are different), but that requires all your pods to be running unique uids (or set quota to a multiple of the count of the pods with the same UID which doesn't protect against bad actors).

I would propose the following
- Add something to cAdvisor to track top layer CoW usage where possible for the filesystems that can provide it 
  - Docker today does not expose this - we could potentially add an abstraction endpoint there, or do the checks directly against devmapper / overlay
- In the Kubelet, honor a resource limit for usage of emptyDir (per mount / pod?) as well as the cow filesystem with a simple check loop.
  - In situations where the container CoW layer has exceeded the maximum, restart the container gracefully (this is hard to do outside of the kubelet today)
  - In situations where the emptyDir has exceeded size... do something??
- Report the volume and cow metrics up through cAdvisor
- Support read only containers through docker as a pod setting and allow it to be controlled via pod policy or similar (user cannot set non-readonly containers)
- Be able to deny emptyDir volumes via pod policy or forcibly limit them to a specific size.

**Comment by smarterclayton** [comment]
@twiest @kubernetes/rh-storage @kubernetes/goog-node

**Comment by vishh** [comment]
* cAdvisor tracks filesystem usage for containers if AUFS driver is enabled. Relevant code [here](https://github.com/google/cadvisor/blob/master/container/docker/handler.go#L262).
* cAdvisor ignores other volumes mounted into a container since it does not understand volume sharing semantics. 
* The existing logic can be used for tracking usage of emptyDir volumes.
* One thing to consider is that tracking filesystem usage without quota can be pretty expensive, especially when dealing with deep directories. 
* I really like the read-only filesystem option, but @bgrant0607 had reservations against that. Ideally, I want that to be the default policy. 

How about using quota with supplemental Gids? I was planning on posting a proposal for disk management by end of this week. Would it be ok to discuss disk management using that proposal?

**Comment by smarterclayton** [comment]
Sure - this was a discussion today where we looked at the various policy
escape hatches and wanted them closed.

Since aufs isn't a supported FS for us we're looking at devicemapper and
overlay.  We'd be happy to pitch in to gather that data (where possible).

Agree quota may be the best option with supplemental groups - we do expect
to set a number of them downward and would be ok if the kubelet reserved a
range for per pod checking.

On Sep 1, 2015, at 8:27 PM, Vish Kannan <notifications@github.com> wrote:


   - cAdvisor tracks filesystem usage for containers if AUFS driver is
   enabled. Relevant code here
   <https://github.com/google/cadvisor/blob/master/container/docker/handler.go#L262>
   .
   - cAdvisor ignores other volumes mounted into a container since it does
   not understand volume sharing semantics.
   - The existing logic can be used for tracking usage of emptyDir volumes.
   - One thing to consider is that tracking filesystem usage without quota
   can be pretty expensive, especially when dealing with deep directories.
   - I really like the read-only filesystem option, but @bgrant0607
   <https://github.com/bgrant0607> had reservations against that. Ideally,
   I want that to be the default policy.

How about using quota with supplemental Gids? I was planning on posting a
proposal for disk management by end of this week. Would it be ok to discuss
disk management using that proposal?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13479#issuecomment-136901809>
.

**Comment by bgrant0607** [comment]
Resources on EmptyDir volumes: SGTM. Use ResourceRequirements (requests and limits), exactly like PersistentVolumeClaimSpec:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L453
but actually support limits as well as requests.

I've heard that not all union filesystem implementations support quota and/or have problems with the implementations. Would love to collapse filesystem layers into readonly image plus CoW layer, though that wasn't on your list.

Storage resources on containers would apply to container-related disk usage: writable layer and (ideally) logs.

I don't object to optionally readonly filesystems. It should be handled exactly like SecurityContext.

We've planned to use supplemental gids to track local storage usage for a long time now.

**Comment by jsafrane** [comment]
Just an idea: what about a new volume plugin, which would create a (sparse) file of a given size on the host, create a filesystem on it and use it instead of emptyDir? That would enforce the quota in pretty hard way, with very little overhead in the OS and without periodical `du -s` polling. In addition, the container would get nice ENOSPC errors when the inner or the outer filesystems gets full, no special actions would be needed from Kubernetes side.

As downside, when the volume is heavily used and data is being deleted from the volume, they would still consume data in the host (outer) filesystem. Periodic fstrim could help here.

And of course, this does not solve container CoW layer quota.

**Comment by dchen1107** [comment]
Using supplemental gids to track local storage usage is tracked by #12686

@jsafrane Shouldn't there is a performance penalty by using sparse file since every read goes through extra VFS layer, and every write requires extra sparse file allocation call?

**Comment by smarterclayton** [comment]
Note that disk is like memory and is incompressible - if we overcommit, and we approach the real limit, we have to OOD kill someone.  The OODkill is a restart (container filesystem deleted) and needs to be recorded.

**Comment by jsafrane** [comment]
> Shouldn't there is a performance penalty by using sparse file since every read goes through extra VFS layer

There is a performance penalty, but IMO it's not _that_ bad. Perhaps 1-5%? Of course, it depends on the filesystem.

**Comment by rootfs** [comment]
@dchen1107 @jsafrane sparse file penalty is not a huge issue if cache works right. I have [some test results](https://huaminchen.wordpress.com/2015/09/17/a-very-rough-performance-comparison-file-vs-tcm-loop-vs-loopback/) on this topic. loopback incurs double page cache and gets most penalty. tcm_loop is not subject to this problem and performs closely to filesystem.

**Comment by rootfs** [comment]
@smarterclayton @jsafrane Is `fallocate(1)` able to avoid OOD problem?

**Comment by jkemp101** [comment]
Has there been any progress on this request?  I need to provide 100 Gigs tmp space to a bunch of pods.  Using emptyDirs looks to risk the entire node to 1 pod having a run away export.  Is there still no way to protect the node from this threat?  Just being able to specify the location of the emptyDirs would be very useful.  I could put them all on a single dedicated local volume to protect the node's root volume from getting consumed.

**Comment by smarterclayton** [comment]
No - OpenShift implemented a barebones XFS quota system for empty dir (
https://github.com/openshift/origin/blob/master/pkg/volume/emptydir/quota.go
and master_node_configuration.html
<https://docs.openshift.org/latest/install_config/master_node_configuration.html#node-configuration-files>)
that is based on the FSGroup id assigned to the container, but it hasn't
been implemented in Kube because we're trying to sort out the disk eviction
work.

You *should* be able to set the Kube volume directory to its own device
with --root-dir and setting up mounts, although I haven't tried it in a
while.

**Comment by vishh** [comment]
> but it hasn't
been implemented in Kube because we're trying to sort out the disk eviction
work.

I don't think we should use gid based quota in Kube. Kindly refer to the existing [disk accounting](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/disk-accounting.md) doc.
The plan is to use project quota. Support for project quota in ext4 is currently being stabilized upstream.

We already track usage of volumes that use local disk. In theory, it should be straight forward to place resource limits on these volumes and have the kubelet evict pods that exceed limits. This approach will not be robust and so we should avoid over-commitment if at all possible for disk.

**Comment by jkemp101** [comment]
Thanks for updates.  I think I have another workaround using a hostpath instead of emptydir.  I can point hostpath to a dedicated shared tmp volume.  I will create a subdirectory with world writeable permissions so all pods/processes can use it even if they aren't running as root.

**Comment by smarterclayton** [comment]
We can move this to that issue, but disk quota without over commitment
isn't useful for us (and I suspect, not useful for many practical
users of quota).

**Comment by smarterclayton** [comment]
Also, I was not implying gid was the solution, I was pointing out the
execution path discussed in that doc depended on eviction being prior
to enforcement.

**Comment by erinboyd** [comment]
Seems we would need something more granular than project quota, as a
project could entail multiple storage sources. GID seems to git more inline
with a true filesystem, though you could also have the scenario where
multiple users across different projects with the same GID are consuming
the same resource.

Seems like we have to have a combination of the two.

**Comment by smarterclayton** [comment]
I would assume project quota in this context was specific to the pod -
having a concept that spans pods is probably something we want to avoid
(even though the openshift XFS implementation does span pods) because
schedulers and other parts of the system can't reason about it.  Per pod
quota for emptydir seems most correct.

**Comment by vishh** [comment]
Per pod is what I'm thinking too. Project quota across local-disk volumes,
root filesystem, logging directories, etc., per-pod will be very useful to
begin with.

**Comment by liubog2008** [comment]
Has there been any progress on this request? I want to limit emptyDir's storage to avoid node's OutOfDisk problem. Now we want to use lvm or loop device to solve this problem(I found it that you don't list this solution in disk-accounting doc. Is there any problem I don't know?). Could you give me some suggestions?

**Comment by vishh** [comment]
No progress yet on limiting usage. We do have an optional feature which
will evict pods based on disk usage whenever the disk availability is low.

**Comment by liubog2008** [comment]
Thanks for your reply. I also need the feature that pod would be evicted by kubelet if OOD. By the way, could you tell me why LVM is not considered in doc disk-accounting.md? I think lvm is a more general solution.

> No progress yet on limiting usage. We do have an optional feature which
will evict pods based on disk usage whenever the disk availability is low.

**Comment by krmayankk** [comment]
i think limiting and managing the quota for local disk is required for supporting any kind of local disk persistent volumes support. Is this being tracked as part of emptyDir sticky proposal or something else ?

**Comment by rkouj** [comment]
This makes an effort to improve local storage
https://github.com/kubernetes/community/pull/306
