### ISSUE TITLE
e2e-scalability test suite is broken

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#13499]
It is constantly failing since run #2312

Suspects (merged around that time):
https://github.com/kubernetes/kubernetes/pull/12963
https://github.com/kubernetes/kubernetes/pull/13227 [probably not]
https://github.com/kubernetes/kubernetes/pull/13345
https://github.com/kubernetes/kubernetes/pull/13426 [probably not]
https://github.com/kubernetes/kubernetes/pull/13386

We should fix this problem before merging anything else.

@mwielgus @fgrzadkowski 
@brendandburns @lavalamp - who were merging after those failures started (please do NOT do it again)

@kubernetes/goog-testing @quinton-hoole 
@k8s-oncall

**Comment by wojtek-t** [comment]
cc @smarterclayton @derekwaynecarr 

I'm almost sure that #12963 is the reason of this regression. To give a bit more context, all tests are failing with errors like this:

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:92
deleting rc load-test-small-rc-10
Expected error:
    <*errors.errorString | 0xc20802b070>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred

which basically confirms that the problem is with a deletion.

**Comment by wojtek-t** [comment]
I would like to avoid reverting this PR and I think we can tweak some values in the test itself to fix that. I did a bit deeper debugging and it seems that what is failing is the function:
waitForRCPodsGone: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/util.go#L1498

I will try to play a little bit with the timeout there - it seems to me that increasing it should help.

**Comment by wojtek-t** [comment]
It seems that #13505 fixed the problem thus I'm closing it.
Feel free to reopen in case it appears again.

**Comment by smarterclayton** [comment]
Thanks - glad this was just a timing tweak.

**Comment by lavalamp** [comment]
@wojtek-t Run 2312 took two hours to finish, so it would have been 3:27 MTV time before we knew it was broken. PRs merged when it was known broken:

#11942 mergebot - @brendandburns why did merge bot merge this if scalability was broken?
#13229 It's not clear to me why @a-robinson merged this
#13480 this was me, I was arguably confident enough that this was safe
#13340 docs
#13442 also docs

I think only two of these merges were actually problematic. Please keep in mind how long the test takes to run. It's not reasonable for us to merge only one thing every two hours, so scalability is going to break more often than the other tests, since it takes so long to run.

**Comment by ironcladlou** [comment]
#13519 contains a fix for a test compilation error.

**Comment by a-robinson** [comment]
Sorry about #13229 -- it had been in merge queue hell for nearly a week and only contained a few trivial, known-safe config changes. I hadn't checked the scalability suite.

**Comment by wojtek-t** [comment]
>
I think only two of these merges were actually problematic. Please keep in mind how long the test takes to run. It's not reasonable for us to merge only one thing every two hours, so scalability is going to break more often than the other tests, since it takes so long to run.

As discussed offline,  I didn't mean that we should merge one thing per hour. 
I just meant that we probably shouldn't merge more after it appeared that scalability is broken (and obviously docs, etcd are fine, I just meant no other big PRs).

**Comment by wojtek-t** [comment]
@a-robinson 
>
Sorry about #13229 -- it had been in merge queue hell for nearly a week and only contained a few trivial, known-safe config changes. I hadn't checked the scalability suite.

This didn't break scalability suite - it was only merged after it appeared that scalability suite is broken.
