### ISSUE TITLE
E2e test schedulers reaction to osciallating nodes

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#13492]
Observed on @yujuhong s cluster, flipping a node in and out of Unknown (will happen if the kubelet doesn't report node status in ~40s) resulted in the scheduler ignoring the node forever. The scheduler watches nodes filtered on unschedulable, with a relist period of 0, and kubectl describe node showed the right node conditions. Restarting the scheduler fixed it because of the relist. 

2 plausible explanations: NodeReady update was dropped, we clobbered the kubelet ready update from node controller.

**Comment by bprashanth** [comment]
@gmarek fyi, since you're at the intersection of nodecontroller, scheduler and kubelet.

**Comment by gmarek** [comment]
A reliable repro is needed, or we'll end up on a wild-goose chase.

**Comment by bprashanth** [comment]
I came to the same conclusion, which is why the bug is about writing a test. Feel free to P3 if you don't think it's attention worthy. Just documenting that this did happen at least once, and most usual signs (describe node, scheduler logs etc) point at a somewhat serious bug.

**Comment by gmarek** [comment]
Yeah, I'd like to have time to debug this:/
