### ISSUE TITLE
Change the mechanism of transport packets to kube-proxy

### ISSUE THREAD

**Issue by tsjsdbd** [kubernetes/kubernetes#13500]
# Background
As mentioned in the Kubernetes user guide documentation that every node in a Kubernetes cluster runs a kube-proxy. Essentially, Kube-proxy on each node watches the Kubernetes master for any addition and removal of Service. When a proxy sees a new Service, it opens a new random port on the local node, establishes an IPTable redirect from the VIP to this new port, and starts accepting connections on it. When a client connects to the VIP, the IPTables rule kicks in and redirects the packets to the Service proxy's own (random) port. The Service proxy chooses the appropriate backend Pod and starts proxying traffic from the client to the backend Pod.

# Shortcomming
The official documentation also says that using IPTable and userspace proxies for VIPs will work at small to medium scale but may not scale to very large clusters with thousands of Services in the cluster. This is predominantly because of the performance implications due to large number of IPTable rules.  As the number services grow, the average path for one packet to travel from Client to kube-proxy becomes very long. As a result, the overall performance degrades.
![image](https://cloud.githubusercontent.com/assets/7219402/9625089/a36abc7c-5185-11e5-8cb9-a2ed21554ba5.png)

# Range
So my proposal is change the mechanism of useing iptables, the range of change is show below:
![image](https://cloud.githubusercontent.com/assets/7219402/9624887/972acf12-5183-11e5-9044-6570a66a4dc0.png)
The key point is: how can sent a packet with a virtual destination address to reach to kube-proxy (if not use iptables).So I think a different approach as illustrated in the subsequent section below.

# Key Idea
We know that in Linux system, a single network interface can have many ip addresses. so we can  leverage this Linux system concept .

Think about that the Node(Host VM) have an additional virtual internal interface, this interface have many ip address, each ip is the service ip(Cluster IP), and the kube-proxy application listen on these ips. Note that Docker0 is such an interface (though it is a Bridge). So once a packet reachs to the Node's network namespace (sent out from any Pod, it will reach to interface Docker0, which is belong to Host's network namespace), the Linux system protocol stack says: the destination address of this packet is myself, no need forward action, then it throw the packet to application lay, which kube-proxy is listening on, so the packet will be received by kube-proxy.
![image](https://cloud.githubusercontent.com/assets/7219402/9625409/79ec9f48-5188-11e5-82ea-3071cfd86cb2.png)

# The changes
1.	Internal interface of each Node in the Kubernetes cluster will have as many IP addresses as the number of services (`not sure if one interface assigned thousands of IP address will cause side effect`)
2.	Kube-proxy will not listen on the random port on the node any more. Instead, it listens on the exact Service IP.
3.	Other than these two, there are no other changes required as per our proposal.

# Example
```
ip addr
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
```
Then I add a new IP 1.2.3.4 to Docker0 interface:
```
ip addr add 1.2.3.4/16 dev docker0
ip addr
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet 1.2.3.4/16 scope global docker0
```
Then I write an App running on Node which listen on 1.2.3.4
```
func main() {
    http.HandleFunc("/hello", helloHandler)

    err := http.ListenAndServe("1.2.3.4:9090", nil)
    if err != nil {
        log.Fatal("ListenAndServe: ", err.Error())
    }
}
```
Then in a Pod, I can access this Application:
```
curl http://1.2.3.4:9090/hello   
Hello, [curl/7.35.0]! you are from 172.17.0.7:44319
```

# The Last
So what about this Idea? :-)

**Comment by thockin** [comment]
Thanks so much for a very well thought out and detailed proposal.

What you describe sounds viable to me - I thought of something similar but only after implementing the existing model, and I was lazy :)  However, there are a few things to discuss.

First, in practical terms, the number of iptables rules doesn't matter much until you hit thousands of rules.  At that point, you could probably work up a binary tree in iptables and convert a linear search into log(n), making every packet have a very bounded worst case.

The real performance hit is coming from hitting userspace at all.  We will have a pure-iptables proxy in kubernetes v1.1 (hopefully on by default but worst case it is just flagged off by default).  This seems to make the scaling much better.  We have not implemented the above-describe binary tree, but that should be a relatively easy change.

Given that, I hope the userspace proxier has a lifetime measured in months, and I don't think that heavy rework will bring be useful, unless it can be show to be dramatically better (in which case we could consider a patch to the v1.0 release).  I'm inclined to close this as "not worth doing", but I would like to leave it open for a bit of discussion if you (or others) disagree.

**Comment by tsjsdbd** [comment]
Thanks for kindly reply.

It is just an idea when I see the shortcomming section in the Service Readme, not sure if it worth further more step, because one of my colleague told me that iptables is very poor performance, and also it may have some security group on the Node. But I'm not sure about the performance result between pure-iptables and pure-ips.

Seems that pure-iptables can works but with less flexible, like how to choose the backend with policy?

**Comment by thockin** [comment]
On Sun, Sep 6, 2015 at 8:08 PM, 唐盛军 <notifications@github.com> wrote:
>
> Thanks for kindly reply.
>
> It is just an idea when I see the shortcomming section in the Service Readme, not sure if it worth further more step, because one of my colleague told me that iptables is very poor performance, and also it may have some security group on the Node. But I'm not sure about the performance result between pure-iptables and pure-ips.

I'm eager to see the new solution stress tested - Our benchmarks and
initial measurements look very promising.

> Seems that pure-iptables can works but with less flexible, like how to choose the backend with policy?

That's true.  There are things you can do in userspace that there just
are not iptables rules to express.  This is a conscious tradeoff.  We
did not intend for kube-proxy to become a competitor to haproxy or
ngingx - it's a relatively simple implementation of VIP, which can be
replaced by other implementations, including "real" load balancers ].

Tim
