### ISSUE TITLE
libvirt-coreos kube-up failed

### ISSUE THREAD

**Issue by linzichang** [kubernetes/kubernetes#13507]
on master commit d23d083439d4b936ceaa82d562fc9880906412c4

I use libvirt-coreos to run k8s cluster and got an error when kube-up.sh：
rmdir: failed to remove ‘/root/workspace/kubernetes/cluster/libvirt-coreos/libvirt_storage_pool/kubernetes/kubernetes’: Directory not empty

I found that `kubernetes-server-linux-amd64.tar.gz` contain a `addons` dir which is added recently. 
And `upload-server-tars` in `cluster/libvirt-coreos/util.sh` don't remove this when upload the release binary.

I think this need a fix. Maybe I can make a PR.

**Comment by linzichang** [comment]
This issue can close now. Fix was merged.

**Comment by linzichang** [comment]
@quinton-hoole

**Comment by quinton-hoole** [comment]
@fixed by #13544
