### ISSUE TITLE
printEvent Source to much more cleaner

### ISSUE THREAD

**Issue by Hokutosei** [kubernetes/kubernetes#13501]
Greetings,

currently, when doing `kubectl describe node node-name` then in `From` column, the ui result is 

```
{kubelet gke-cluster-1-micro-a0f27b19-node-vn5m}
```

maybe can do something like this instead? remove `{}` then join it with `,`

```
kubelet, gke-cluster-1-micro-a0f27b19-node-vn5m
```

**Comment by JanetKuo** [comment]
How about something like `kubelet on gke-cluster-1-micro-a0f27b19-node-vn5m`?

**Comment by Hokutosei** [comment]
Greetings,

thanks for the interest, I thought I may throw hacking on it. btw, how about for `{scheduler }` ?

**Comment by JanetKuo** [comment]
For `{scheduler }` we can just print `scheduler` since it's master's component.

**Comment by matthyx** [comment]
Hi @janetkuo looks like there is the same issue reported on the OpenShift Origin github:
https://github.com/openshift/origin/issues/6586
It would make more sense to solve that upstream.
Should we do something together to solve it?

**Comment by matthyx** [comment]
There is a pull request for that:
https://github.com/kubernetes/kubernetes/pull/40073
