### ISSUE TITLE
define Docker labels for containers

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#13513]
Is it possible to define Docker labels for the containers in a POD? I want to set custom labels for the containers so I can see them when I do "docker inspect" on those containers.

**Comment by resouer** [comment]
Just out of curiosity, does the pod labels not enough for you? Why do you want labels when doing `docker inspect`?

**Comment by philk** [comment]
A good example would be tools that use docker labels but aren't aware of k8s labels yet (or may never).

One specific example:
https://sysdig.com/sysdig-cloud-adds-support-for-docker-labels/

**Comment by philk** [comment]
This issue could be considered a dupe of #3764 and/or #12451

**Comment by davidopp** [comment]
Yeah, definitely a dupe of #3764. Please follow up there.
