### ISSUE TITLE
displayed number of restarts for a pod is often inaccurate.

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes#13517]
I've noticed this to be the case for quite a while now (months).  The displayed number of restarts for a pod always ratchets down to display as '2' after a short while.  e.g.:
https://www.dropbox.com/s/vlzg2f6m1sx8jib/Screenshot%202015-09-02%2010.34.37.png?dl=0
Note the timestamps.

So, it seems that '2' in the pods list should always be interpreted as '>=2'. :)

**Comment by yujuhong** [comment]
@amygdala, we recently fixed the restart count in HEAD, but it hasn't be included in any releases yet. We plan to backport this to v1.0 soon.

**Comment by dchen1107** [comment]
I believe this is fixed in HEAD by #13320. Please reopen it otherwise. Thanks!
