### ISSUE TITLE
Reusable client/server infrastructure

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#13541]
Forked from #8190, #8132, #6363, #2742, #2098, and probably other issues.

We need to choose/build a reusable client/server infrastructure, either based on apiserver or something new, such as grpc. While many components will slave off the core apiserver, some won't, and we also want to support federated apiservers.

cc @kubernetes/goog-csi

**Comment by pires** [comment]
Any updates on this? Would be great to have the API exposed as a gRPC service.
