### ISSUE TITLE
Fix writing secrets in containerized kubelet

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#13557]
Currently when kubelet is running in a container writing secretes doesn't work. The problematic workflow is:
1. Kubelet mounts ```tmpfs``` as a secret volume using ```nsenter_mounter``` in host's namespace
2. Kubelet reads secretes from API server
3. Kubelet tries to write secretes to the newly created volume, but as it resides in host's namespace it fails.

This will be solved with https://github.com/docker/docker/pull/15648, but before it happens we will need some temporary solution. One workaround is to use ```nsenter``` to write data similarly to how we have mounted it.

This is a blocker to run kubelet and other k8s components as docker containers, which should greatly simplify UX for new setups.

@dchen1107 @smarterclayton @brendandburns

**Comment by smarterclayton** [comment]
You can always switch to redhat os'es... :)

On Sep 3, 2015, at 11:52 AM, Filip Grzadkowski <notifications@github.com>
wrote:

Currently when kubelet is running in a container writing secretes doesn't
work. The problematic workflow is:
1. Kubelet mounts tmpfs as a secret volume using nsenter_mounter in host's
namespace
2. Kubelet reads secretes from API server
3. Kubelet tries to write secretes to the newly created volume, but as it
resides in host's namespace it fails.

This will be solved with docker/docker#15648
<https://github.com/docker/docker/pull/15648>, but before it happens we
will need some temporary solution. One workaround is to use nsenter to
write data similarly to how we have mounted it.

This is a blocker to run kubelet and other k8s components as docker
containers, which should greatly simplify UX for new setups.

@dchen1107 <https://github.com/dchen1107> @smarterclayton
<https://github.com/smarterclayton> @brendandburns
<https://github.com/brendandburns>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13557>.

**Comment by dalanlan** [comment]
The param `--containerized` seems to do with this. Hadn't dived deep though @pmorie

**Comment by fgrzadkowski** [comment]
@dalanlan ```--containerized``` will indeed help with mounting, but will _not_ help with writing secrets. I have WIP PR that should fix it.

**Comment by smarterclayton** [comment]
When we do the fix, we should be careful to preserve both modes - with Docker with Slave and without so we can continue working when in centos/fedora.

**Comment by tony24681379** [comment]
It still has bug in v1.5.1, something becomes wrong.
