### ISSUE TITLE
Indirect dependency on golang test code introduced unintended CLI flags in Kubernetes binaries

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#13565]
From @eparis's comment in the Cinder PR: https://github.com/kubernetes/kubernetes/pull/13367#issuecomment-137254241

PR #13367, Cinder Volume Plugin introduced a dependency on 

* [`github.com/rackspace/gophercloud/openstack/blockstorage/v1/volumes`](https://github.com/rackspace/gophercloud/blob/master/openstack/blockstorage/v1/volumes/fixtures.go#L6)
* [`github.com/rackspace/gophercloud/openstack/compute/v2/extensions/volumeattach`](https://github.com/rackspace/gophercloud/blob/master/openstack/compute/v2/extensions/volumeattach/fixtures.go#L8)

which in turn has a dependency on [`github.com/golang/go/src/testing`](https://github.com/golang/go/blob/master/src/testing/testing.go#L187)

which declares a bunch of command line args (see https://github.com/golang/go/blob/master/src/testing/testing.go#L187).

Which means that kubernetes binaries, like `kubelet` now have flags for golang test code like `--test.memprofilerate`, `--chatty`, etc.

**Comment by saad-ali** [comment]
@spothanis is taking a look

**Comment by saad-ali** [comment]
Status: @spothanis submitted PR https://github.com/rackspace/gophercloud/pull/476

**Comment by spothanis** [comment]
The PR was merged in gopher cloud. I updated the godeps
https://github.com/spothanis/kubernetes/commit/9f3e02d12cd2da940d03bbcfb71b4d40cf847223, it looks like the test flags are now gone. However I still have some functionality testing (here is where I am missing e2e tests for openstack dearly :), cause godep update touched 88 files)

**Comment by saad-ali** [comment]
@spothanis any update?

**Comment by spothanis** [comment]
@saad-ali Sorry for the delay, I tested the cinder and instance operations after the update, however I was not able to test LB side of things, cause our internal OpenStack deployment and the way we use it with Kube is significantly different from generic implementations.

**Comment by saad-ali** [comment]
#14364 merged
