### ISSUE TITLE
kubectl apply conflict detection

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#13576]
Forked from #1702 and #13007 .

We're not initially doing conflict detection in kubectl apply -- the user's config will always win. Eventually we should provide that (optionally). See the (lengthy) discussions in the issues/PRs mentioned above.

cc @smarterclayton @ghodss @jackgr

**Comment by bgrant0607** [comment]
Field-based preconditions on PATCH (in addition to a resourceVersion precondition) could push some of the detection onto the server, which is generally desirable #12143.

**Comment by ymqytw** [comment]
Has this issue been solved by #16980? Should we close it?
