### ISSUE TITLE
User confusion on namespace field for non-namespaced objects (swagger)

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#13579]
http://stackoverflow.com/questions/32316178/does-kubernetes-pv-recognize-namespace-when-created-queried-with-kubectl/32337310?noredirect=1#comment52557906_32337310

We should make sure the swagger does not list namespace as a valid field

**Comment by gmarek** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
As discussed in email, we can either fork the struct definition or add a tag and strip out the field where it's not needed.

**Comment by gmarek** [comment]
Can we make a decision on what to do, and rename this issue to indicate what needs to be done, so that anyone looking for things to work on can grab it?

**Comment by bgrant0607** [comment]
See also #5286

**Comment by smarterclayton** [comment]
Or our preferred option, which was to do nothing.  I don't see folks clamoring for this, and the impact is not severe.  Server should error if it's not empty.
