### ISSUE TITLE
In "Getting Started Guide", cannot SSH with generated key

### ISSUE THREAD

**Issue by bbirand** [kubernetes/kubernetes#13588]
I'm trying to follow the CoreOS/Azure startup guide:
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/azure/README.md

I can pull up the VMs, but when I try to ssh to the the root kubernetes node, I get asked for a passphrase for the SSH key:

```
$ ssh -F output/kube_49a47311e556f3_ssh_conf kube-00
Permission denied (publickey).
```

I'm not sure what the passphrase is supposed to be, and I asked this question on SO as well:
http://stackoverflow.com/questions/32395099/default-ssh-passphrase-as-generated-by-openssl-req

**Comment by gmarek** [comment]
@yifan-gu - as it's CoreOS stuff, can you help with this?

**Comment by yifan-gu** [comment]
subscribe

**Comment by yifan-gu** [comment]
cc @crawford @kelseyhightower who are more familiar with azure/coreos

**Comment by crawford** [comment]
CoreOS does not have a password for the core or root account by default. When you create the Azure instance, you must provide the API with a password or SSH key.

**Comment by errordeveloper** [comment]
There had been a few updates since this issue had been filed, could you please test once #16129 is merged?

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
This document has been changed many times and in fact does not exist anymore. We should close.

**Comment by chenopis** [comment]
agreed
