### ISSUE TITLE
[kubectl] terminal dimensions not exported with 'exec' command

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#13585]
When using `kubectl exec` the terminal dimensions are always set to 80x24 instead of matching the client's layout.

Of course it is possible to insert "env COLUMNS=$COLUMNS LINES=$LINES" before every command, but this is not very usable.

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by rvrignaud** [comment]
+1 for this issue. This is really annoying.

**Comment by joltup** [comment]
+1

**Comment by tslater** [comment]
+1

**Comment by thuey** [comment]
+1

**Comment by piersy** [comment]
+1

**Comment by maclof** [comment]
I'd love to see this fixed soon. It seems that the terminal window size isn't monitored by kubectl and sent to kubelet to resize.

We should probably be doing something like docker does here: https://github.com/docker/docker/blob/master/api/client/utils.go#L99

I noticed back in may @ncdc was working on a commit for this here: https://github.com/ncdc/origin/commit/13220dbb5208df5659568e282bc8483079463d2c so perhaps we could work from this?

I'll see if I can work on a PR

**Comment by ncdc** [comment]
I'm still planning on working on it but it's lower priority than some other
things on my plate. If you want to pick it up, that would be fine. It just
needs to continue to be backwards compatible with older clients and servers
that don't have this feature.

**Comment by maclof** [comment]
@ncdc regarding backwards compatibility, I assume this would to be implemented as streamingProtocolV3? similarly to how it's already been done? https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/remotecommand/v2.go

**Comment by bgrant0607** [comment]
cc @ethernetdan

**Comment by gy8** [comment]
+1

**Comment by harai** [comment]
+1

**Comment by kpatryk** [comment]
+1

**Comment by ncdc** [comment]
@maclof we might be able to get away without a new v3 protocol version. If the client tries to create a stream type the server doesn't support, the client will receive an error back from the server for that stream. It would probably be sufficient to check for absence/presence of an error and proceed accordingly.

I do wonder about the websocket version of this, though. It may require a new subprotocol version. We'll need to see.

Are you still intending to work on this?

**Comment by ghodss** [comment]
As a simpler intermediate solution I'm sure it would be helpful to have the columns and lines at least set when kubectl exec starts, and as a subsequent enhancement have it always stay up to date as your terminal resizes.

**Comment by ncdc** [comment]
@ghodss that still requires all the plumbing to be able to have the client inform the server of the terminal size

**Comment by ncdc** [comment]
I have a prototype from months ago that implemented this. It's just a matter of finding some time to see it through to completion.

**Comment by maclof** [comment]
@ncdc I was going to work on this on top of what you had implemented, but I haven't had the time. I am planning to work on it if nobody gets to it sooner.

**Comment by ncdc** [comment]
It might be worth waiting until the 1.2 branch is created. Once that's done, I'll rebase #16451 and hopefully get that in, and then you could come on top of that.

**Comment by maclof** [comment]
Sounds good to me. I'll keep an eye on that issue.

**Comment by gy8** [comment]
thanks guys!

**Comment by vaijab** [comment]
Meanwhile:
```
stty rows 50 cols 150
```

**Comment by timbunce** [comment]
I see @ncdc's #16451 has been merged. I'm hoping @maclof can get to this soon. Just getting the initial size right would be a big help.

**Comment by ncdc** [comment]
I've actually started working on SIGWINCH support. I hope to have something submitted for review later this week.

**Comment by ncdc** [comment]
Here's my WIP: https://github.com/ncdc/kubernetes/pull/7

**Comment by hubt** [comment]
This script doesn't understand SIGWINCH, but it will set terminal size correctly at startup on most systems.
```
#!/bin/sh
if [ "$1" = "" ]; then
  echo "Usage: kshell <pod>"
  exit 1
fi
COLUMNS=`tput cols`
LINES=`tput lines`
TERM=xterm
kubectl exec -i -t $1 env COLUMNS=$COLUMNS LINES=$LINES TERM=$TERM bash
```

**Comment by ncdc** [comment]
I've been busy with other items, but I do hope to submit the winch pull
next week. It's 100% functional and just needs some polishing up before
it's ready.

**Comment by timbunce** [comment]
Thanks @ncdc. Looking forward to it.

**Comment by ncdc** [comment]
PR is #25273

**Comment by yasseur1007** [comment]
@ncdc +1 !!

**Comment by numidiasoft** [comment]
:+1

**Comment by Yugloocamai** [comment]
+1

**Comment by fx-dx** [comment]
It would be great to export terminal dimensions with 'exec' command

**Comment by ncdc** [comment]
@fx-dx this has been implemented. Are you having some issues?

**Comment by variousred** [comment]
I'm on 1.5.4 and i'm still seeing the remote bash thinking my console is at 80 columns ...

**Comment by ncdc** [comment]
@variousred would you mind sharing how you tested?

**Comment by variousred** [comment]
`kubectl exec -it some-app-name-randomnumber-abcdefg /bin/bash`
`echo $COLUMNS` -> 80

**Comment by variousred** [comment]
Its probably the server side version

**Comment by ncdc** [comment]
What is the server version?

**Comment by variousred** [comment]
Yeah, my bad, on this cluster the server version is 1.2.2

**Comment by tslater** [comment]
I still seem to have this problem on
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T23:29:08Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-04-07T20:46:46Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ncdc** [comment]
@tslater could you please be more specific with what you're doing? What command(s) are you running? What are you experiencing? Thanks!

**Comment by snstanton** [comment]
I'm seeing similar behavior in 1.6.4:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:24Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-30T22:03:41Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

$ echo $COLUMNS
144

<having previously deployed ubuntu:16.04 with kubectl run>

$ kubectl exec -ti bash-699984357-m99g8 bash
root@bash-699984357-m99g8:/# echo $COLUMNS
145
root@bash-699984357-m99g8:/# exit

$ kubectl exec -ti bash-699984357-m99g8 bash
root@bash-699984357-m99g8:/# echo $COLUMNS
80

```

As you can see, back-to-back runs of the command lead to different results.  Sometimes it picks up the right value, sometimes not.  It looks like there is some sort of initialization race condition because it always gets it right if I resize the window.

**Comment by rajasaur** [comment]
Yeah, been seeing the same with 

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-05-09T23:22:45Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

````


As @snstanton  mentioned, if I resize the terminal it picks up the right values, but if not, it defaults $COLUMNS to 80

**Comment by ncdc** [comment]
I have looked into this, and it appears that the kubelet is sending the resize request to the docker daemon too early:

```
Jun 23 15:38:43 f25 dockerd-current[10894]: time="2017-06-23T15:38:43.042817005-04:00" level=debug msg="Calling POST /v1.24/exec/d8be9c9787a5a11e7f428e13be6e145d484481812002947f8248bf50f582fa11/resize?h=28&w=119"
Jun 23 15:38:43 f25 dockerd-current[10894]: time="2017-06-23T15:38:43.042891870-04:00" level=info msg="{Action=resize, Username=vagrant, LoginUID=1000, PID=11704}"
Jun 23 15:38:43 f25 dockerd-current[10894]: time="2017-06-23T15:38:43.043449375-04:00" level=error msg="Handler for POST /v1.24/exec/d8be9c9787a5a11e7f428e13be6e145d484481812002947f8248bf50f582fa11/resize returned error: rpc error: code = 2 desc = containerd: process not found for container"
```

I performed a similar test with `docker exec` and it behaves correctly.

I think I can fix this. I'll report back in a bit.

**Comment by ncdc** [comment]
I have been able to fix this locally. However, I am going to open a new issue. Please move discussion there - #47990.
