### ISSUE TITLE
Timeout option for containers before they receive SIGKILL

### ISSUE THREAD

**Issue by bobef** [kubernetes/kubernetes#13583]
Here http://kubernetes.io/v1.0/docs/user-guide/production-pods.html#liveness-and-readiness-probes-aka-health-checks it says 

> Kubernetes will send SIGTERM to applications, which can be handled in order to effect graceful termination. SIGKILL is sent 10 seconds later if the application does not terminate sooner.

These 10 seconds **MUST** be customizable like `docker stop` can. Real world scenario from our company: you are making a hotel booking or flight booking. The services that provide these bookings are sometimes slow as hell. You can't stop the container in the middle of a booking request, this costs money.

**Comment by gmarek** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
This was implemented as part of graceful deletion.  Docs are still in progress https://github.com/kubernetes/kubernetes/pull/12747

Set pod `spec.terminationGracePeriodSeconds`
