### ISSUE TITLE
kubectl plugins

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#13606]
This was discussed way back when designing kubectl. 

Although we want to move more functionality server-side (#12143, #5280), there are going to be some things that are better / more easily done in the client (e.g., processing of local inputs, such as #4822). For the latter category, it would be useful to support some kind of plugins/extensions in kubectl.

**Comment by andrewstuart** [comment]
I think this would also be hugely useful for secret encryption as well. The ability to hook in, selectively grab secrets, and encrypt them transparently with local credentials or via some remote provider would really add to the UX.

To that end, I think it would also be really helpful to be able to prompt for user interaction, if for example a new public key is found that the user needs to validate is trusted (I'm thinking use cases like you'd see with ~/.ssh/known_hosts).

**Comment by bgrant0607** [comment]
Proposal: https://github.com/kubernetes/community/pull/122

**Comment by bgrant0607** [comment]
For posterity, plugins exist: https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/
