### ISSUE TITLE
Fix 1.0-1.1 GKE upgrade tests, and get them into release critical builds

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#13602]

**Comment by ihmccreery** [comment]
Looks like the LB reachability is flaking:

```
Skipped
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:334
  Cluster upgrade
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:333
    upgrade-cluster
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:332
      should maintain a functioning cluster [It]
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:331

      Error waiting for the url http://104.154.51.255:80 to be reachable
      Expected error:
          <*errors.errorString | 0xc208029fa0>: {
              s: "timed out waiting for the condition",
          }
          timed out waiting for the condition
      not to have occurred

      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1329
```

**Comment by ihmccreery** [comment]
@davidopp since I saw your comments on other bugs, what's left:
@davidopp This is a work-in-progress, and #15717 and others are work toward getting results, but hasn't stabilized yet, so we haven't ported it over to GCE.

- [x] fix the build infrastructure on the `release-1.1` branch (@ixdy looks to have succeeded on this)
- [ ] stabilize 1.0-1.1 upgrades on GKE (#15717)
- [ ] diagnose failures and address them, by fixing unexpected failures and disabling expected failures, (or something)

**Comment by ihmccreery** [comment]
The biggest problem seems to be not being able to delete pods: #15123.

**Comment by ihmccreery** [comment]
Status update: these tests are running, but aren't stable.  They need to be stabilized, then this issue can be closed.  #15123 is the biggest issue, but there may be others, (e.g. #15806).

**Comment by ihmccreery** [comment]
Update: there is one outstanding issue: 1.0 Kubectl e2e's leave pods in Error state lying around (against a 1.1 head & 1.1 nodes) #16447.

Then, there are a few test fixes (see #15116).

**Comment by davidopp** [comment]
@ihmccreery Is there anything left to fix here (other than the one remaining GCE upgrade test issue)?

**Comment by ihmccreery** [comment]
Just watch the tests go green (with #16533) and put them in critical builds.

**Comment by ihmccreery** [comment]
Thanks to everyone for their hard work on this.  GKE upgrade tests for 1.0 to 1.1 are now in the 1.1 CI builds.
