### ISSUE TITLE
kubectl describe <kind> needs to hide terminated pods

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#13621]
kubectl get <kind> default hide terminated pods, use --show-all (-a ) to show all resources. Does kubectl describe <kind> need to be consistent with kubectl get <kind> ?

**Comment by feihujiang** [comment]
@bgrant0607 What's you point about this issue?

**Comment by feihujiang** [comment]
But "kubectl get pods -o yaml/json" show all pods, not hide terminated pods. So I'm confused whether "kubectl describe pods" needs to hide terminated pods.

**Comment by feihujiang** [comment]
According to the docs, "kubectl get pods -o yaml/json" should  hide terminated pods too.

**Comment by jlowdermilk** [comment]
@kubernetes/kubectl

**Comment by smarterclayton** [comment]
Isn't it likely as a user I would describe terminated pods and want to see
their status?  We're putting in a lot of code to try and hide pods that
still exist, I'm a bit worried we should be spending that effort on making
those pods go away instead.

On Sep 6, 2015, at 1:57 PM, Jeff Lowdermilk <notifications@github.com>
wrote:

@kubernetes/kubectl <https://github.com/orgs/kubernetes/teams/kubectl>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13621#issuecomment-138104288>
.

**Comment by feihujiang** [comment]
I means: 
1. There is a conflict, "kubectl get pods" hides terminated pods, but "kubectl get pods -o yaml/json" doesn't hide terminated pods. Should we change to keep them consistent? 
2. Does "kubectl describe <kind> " need to hide terminated pods and using --show-all (-a ) flag to show all pods? 

Most of time, users don't want to see the terminated pods. but if users want to see the terminated pods' status, we should give the method. 

To make those pods go away instead, maybe we could offer a creating flag to create a pod that would be deleted automatically when it is terminated,  and also offer a method to let users delete terminated pods all.

**Comment by smarterclayton** [comment]
I tend to think kubectl describe does not need the --show-all flag, if only
because --show-all is specific to the "list" function which we have defined
as being "kubectl get".  kubectl get pods not filtering the output is
inconsistent, although I don't really want to move the logic we currently
have in the printer out to the higher level (out of the pod specific scope).

On Tue, Sep 8, 2015 at 1:50 AM, Flying Tiger <notifications@github.com>
wrote:

> I means:
> 1. There is a conflict, "kubectl get pods" hides terminated pods, but
> "kubectl get pods -o yaml/json" doesn't hide terminated pods. Should we
> change to keep them consistent?
> 2. Does "kubectl describe " need to hide terminated pods and using
> --show-all (-a ) flag to show all pods?
>
> Most of time, users don't want to see the terminated pods. but if users
> want to see the terminated pods' status, we should give the method.
>
> To make those pods go away instead, maybe we could offer a creating flag
> to create a pod that would be deleted automatically when it is terminated,
> and also offer a method to let users delete terminated pods all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13621#issuecomment-138442241>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
If `kubectl describe` does list all resources (which we've discussed doing in the past), it makes sense to me to be consistent with `kubectl get`.

**Comment by smarterclayton** [comment]
It's certainly consistent.  I just don't know whether I think it's
important to emphasize show-all as anything other than an option to get.
In what scenario would I want to call kubectl get -o yaml or kubectl
describe pods?  Probably when I want to capture a lot of output and grep it
or transform it.  --show-all seems much more targeted towards the
assumption that a user needs to filter the list down to the most relevant
items (and --show-all should really be a field selector on the API, not a
client side thing).  Copying this special abstraction around seems vague.

Would jobs have --show-all (for only running jobs)?  Should we define a
common condition that could be selected on, or define a condition selector
that happens to be bound to --show-all?

On Tue, Sep 8, 2015 at 2:00 PM, Brian Grant <notifications@github.com>
wrote:

> If kubectl describe does list all resources (which we've discussed doing
> in the past), it makes sense to me to be consistent with kubectl get.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13621#issuecomment-138649751>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by feihujiang** [comment]
Now I know the show-all option is just only used by "kubectl get pods --show-all" to show all the pods including the terminated pods, not used by other resources.  Maybe we should remove it, and let "kubectl get pods" show all the pods including the terminated pods. But I don't know the history of the show-all option, so your point is important.

**Comment by JanetKuo** [comment]
The reason terminated pods are hidden by default is for #7660 (GC terminated pods). 

We didn't use field selector because the users can get multiple resources at once (such as `kubectl get po,svc,ns`) but we don't have an universal way to apply fieldSelector to different resources. If any of the resources doesn't have the field we specified, it'll fail.

**Comment by osterman** [comment]
@janetkuo: We always see the terminated pods despite not passing `--show-all`

![image](https://cloud.githubusercontent.com/assets/52489/16430996/3dfdc6dc-3d33-11e6-8a7b-b304d9c8387a.png)

IMO `desired` = `current` = `0` = `terminated` :)

Am I misunderstanding what it means to be "terminated" or is this a bug? . I can file an issue in that case.

**Comment by janetkuo** [comment]
@osterman `--show-all` is only relevant to pods (i.e. either hides/displays terminated pods). If you want those "terminated" RSes (we call them old RSes) be gone (garbage collected), and I assume they're created by a "supernova" Deployment, you can set the Deployment's [`.spec.revisionHistoryLimit`](http://kubernetes.io/docs/user-guide/deployments/#revision-history-limit) to determine how many old RSes you want to keep in the system. Note that those old RSes are used to rollback, so once deleted you can't rollback to it.

**Comment by janetkuo** [comment]
> `--show-all` is only relevant to pods (i.e. either hides/displays terminated pods).

I should say, it's only relevant to pods for now. https://github.com/kubernetes/kubernetes/pull/27510 is planning to hide 0 replica RSes by default.

**Comment by osterman** [comment]
@janetkuo thanks! Didn't know about `.spec.revisionHistoryLimit `. That was something else we wanted
