### ISSUE TITLE
patching service' port renders ip routing unusable

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#13630]
I was messing around with some `kubectl` commands, to see what was possible, and ran into this situation:

```bash
$ jq -c '{spec: {ports: .spec.ports}} | .spec.ports[0].port |= 90' service.json \
    | xargs -0 kubectl patch service app -p
# => app
```

```bash
$ kubectl get service app -o json | jq '.spec.ports[0].port'
# => 90
```

after repeating above steps to change it back to port 80, I noticed the `loadBalancer` IP had changed. However, I was no longer able to reach the service using this IP:

```bash
$ curl 130.211.xx.yy
# => curl: (56) Recv failure: Connection reset by peer
```

the pods where still up, and I could still curl their internal IPs (from inside one of the pods, using `kubectl exec`).

Even after re-creating the service (using `kubectl delete` and `kubectl create`) I am still unable to reach the pods.

**Comment by thockin** [comment]
The fact that the load-balancer IP changed is a bug and is fixed for v1.1.

Can you clarify what the 130.211.x.y is ?  The old load-balancer IP?  The
new load-balancer IP?

There's not quite enough info here to repro the problem.

**Comment by JeanMertz** [comment]
It was the new LB ip. After recreating the Service I got that IP again (I guess GCE hangs on to it?) and the curl request still didn't work.

I'll try to reproduce tomorrow and see if I can get some more information.

**Comment by thockin** [comment]
Yeah, if you can boil it down to a simple repro case, we can dig in.
Thanks!

**Comment by JeanMertz** [comment]
I haven't tried to reproduce this, and won't be in a position to do so in the foreseeable future. If this hasn't been fixed already in some of the recent releases, I'm sure someone else will run into this and create a new issue.

Closing this.
