### ISSUE TITLE
mesos: Use IPs to connect to masters

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubernetes#13647]
A mesos master host's hostname doesn't necessarily resolve to the IP mesos is listening on. Since we have the IP mesos registers itself in ZK with, we should use that instead.

Basically, we just need to remove 135 and 136:
https://github.com/kubernetes/kubernetes/blob/HEAD/pkg/cloudprovider/providers/mesos/client.go#L135

**Comment by gmarek** [comment]
@discordianfish can you write this PR?
