### ISSUE TITLE
Rkt driver: lifecycle hook doesn't work.

### ISSUE THREAD

**Issue by PiotrProkop** [kubernetes/kubernetes#13645]
Lifecycle hook doesn't work ( command specifed in pod.yaml is not being executed) when `container_runtime=rkt` flag is specified in `kubelet`. In `kubelet` logs there is no information about failing of postStart action, even with `--v=10` flag. 

```
rkt version 0.8.0
appc version 0.6.1
```

```
$# kubelet --version=true
Kubernetes v1.1.0-alpha.1.304+cbce3a1ab8779a-dirty
```

```
$# cat /etc/lsb-release
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=794.0.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 794.0.0"
```

**Comment by jlowdermilk** [comment]
@kubernetes/rh-cluster-infra

**Comment by lleszczu** [comment]
@yifan-gu

**Comment by yifan-gu** [comment]
@PiotrProkop Thanks for reporting. This is because the hooks are not implemented yet (as well as network plugin). Added to the [todo list](https://github.com/kubernetes/kubernetes/issues/8262) to track this. But this should be simple to implement, feel free to patch it if you want :)
