### ISSUE TITLE
Improve eviction of pods from unhealthy and vanished nodes

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1366]
A user reported that crashing a minion didn't cause replicationController to create replacement pods: #1346. A partial fix was implemented in #1347, and another change is being discussed in #1356.

Currently, https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/minion/healthy_registry.go simply omits minions that don't respond to health checks, which are performed on demand when List() is called, and pods scheduled on unhealthy nodes are reported as terminated just while the nodes are unresponsive, but may revert to running.

In #1347, I proposed: Something needs to health-check the minions and decide when the pods should be marked terminated (which I currently means they need to be deleted). We can start with a fixed timeout. At the same time, the minion needs to be made ineligible for scheduling. (There are various ways in which we may want to make this more sophisticated in the future, but we can start simple.)

If a minion went AWOL and then returned, it should see that all of its pods are supposed to be gone, and kill anything running.

This would make pod lifecycle more predictable across reboots and network partitions. 

/cc @lavalamp @thockin @brendandburns @dchen1107 @erictune

**Comment by bgrant0607** [comment]
Proposal: Record time of last probe and time of last good probe for each node in node Status. When the delta becomes greater than some value (say, 10 minutes -- could be a flag), delete the pods. When syncing with the cloud provider, if the node disappears, it should delete the pods immediately (assuming we can tell the difference between object doesn't exist and other API failures).

**Comment by ddysher** [comment]
I planned to make node lifecycle work before fixing this, but for rudimentary solution, we can start with node status.  All the probe will be NodeReady for now.

One problem with @bgrant0607's proposal is that we have to keep an extra field "last probe time", which node controller will update periodically to api server.  It occurs to me this will put a lot burden on api server.

We can degrade a little bit to use last transition time as our last good probe time.  So if current probe fails, we check our last transition time, which is the first bad probe.  The gap between the 'first bad probe' and 'last good probe' is the sync peroid. This is actually a problem of how we judge the interval (sync time) between two probes, does it count to good condition or bad condition?

If we do create a new field for this, we'll make it a little more general, i.e. to also cover "LastBadProbTime".  This can be useful for future use, say if we want to revive a node only after some time, then we need to know last bad prob time.

**Comment by erictune** [comment]
Alternate proposal:

Node controller does not touch pods.  Apiserver terminates pods that have
not seen an update from kubelet in more than N seconds.  Kubelet
periodically tells apiserver that its pods are okay.

Advantages:

Keeps pod concept out of node controller.

If kubelet is multithreaded or even multiprocess, a blockage in one pod
handling thread only needs to terminate that pod not all.

Node controller not as critical for availability.  Fewer things critical
for availability is better.

Lost pod handled via same mechanism as lost node.

Possible objection:
"Apiserver should not have specialized logic to handle this."

Response to that objection:
This is just an instance of a more general case that the apiserver should
handle.  That pattern is work unit leasing.  Here's the general pattern.

  1. add a lease special verb
  2. An object can only be under one lease at a time.
  3.  A lease ends after a set time (expiration) or earlier if the client
releases early.
  4. Other clients can wait and see when a lease ends
  5. Business logic specifies a modification to the object for the
apiserver to make if the lease expires without release.
  6. A client can release and modify atomically
  7. A client can renew a lease prior to expiry
  8. A lease does not prevent object modification by other clients.   The
lessee still needs to watch for changes to the object.  It just blocks
other lease respecting clients from acquiring the lease.

Use cases:

Scheduler leases a pod when it starts scheduling pass.  If it crashes or is
slow then the lease expires and another scheduler instance can pick it up.

Kubelet leases a pod it plans to run.  It keeps renewing the lease as long
as the pod is healthy.  If the lease expires then the pod is moved to
terminated state.

During bootstrap, or in simplified system, where there is no centralized
scheduler, kubelets can vie for pods.

General pattern for redundancy and overlapping sharding work for finalizers.

Lease renewal and expiry events are useful for debugging.

**Comment by derekwaynecarr** [comment]
This sounds interesting.

How is the holder of a lease represented on the object?  Is it a service account?  

Does retaining a lease come with a state flag to describe why the lease is being held?

Is there a controller expiring leases and changing the lease status?

**Comment by bgrant0607** [comment]
I'm trying to make the apiserver a generic, dumb, reactive CRUD server. SOME controller will need to do this. I'm not 100% set on the node controller, but it seems like the best place at the moment.

The main problem I'm trying to solve here is doing something reliably when a node dies. I'm less concerned with Kubelet timeouts unless/until they show up as a problem. In that case, we may switch to a different signal (e.g., machine ping) to trigger pod killing.

I understand and like the fine-grained lock model. It may be useful when we replicate/shard components. However, it seems to me that Kubelet leasing pods is isomorphic to the proposed solution -- if the "lease manager" doesn't hear from the Kubelet for longer than the lease period, it deletes the pods. If you want to keep the timestamps in each pod rather than just in the node, I agree that might make sense once the Kubelet is made highly concurrent. (Tangent: we should add a last modified time to ObjectMeta.)

If what you're suggesting is simply a centralized queue that the Kubelets take from, that's been discussed before. With that approach, it's possible to still apply fit predicates, but any kind of prioritization across hosts is difficult. How could the pods of a service be spread across hosts, for instance? It's also somewhat dubious from a security perspective. In any case, I don't see a strong motivation to try to move to that model.

**Comment by thockin** [comment]
I don't find the simple form (node controller does it) to be too
objectionable, but I find the proposal appealing as a more principled
approach.  I'm not sure what the implications of it would be for
implementation timeline - we have an oozing wound here right now.  I'd
really like to get it bandaged up...

**Comment by bgrant0607** [comment]
#4048 is adding Pod Conditions, readiness in particular. That would be a logical place to add a node heartbeat to Pod. The logical controller, then, to take action would be ReplicationController. Pods not supervised by any controller are out of luck in the case of node failure, anyway; maybe staying on a possibly dead node indefinitely is ok in that case.

**Comment by bgrant0607** [comment]
#4241 made the node controller delete pods. Reducing priority of the fancier solution.

**Comment by YanXiaoping** [comment]
I did some test on kubernetes v0.18.0-157-g5520386b180d3d.
Eviction of pods from unresponsive noe is quite slow (4:20 minutes = pod-eviction-timeout - node-monitor-grace-period).
As those pods were running (from kubectl get pods), I think they are not removed from backend list of service.
Isn't it a problem to keep an unresponsive pod in service backend list for so long time?

PS: How can I check service's backend list from kube-proxy?

**Comment by YanXiaoping** [comment]
just noticed answer for 
>>PS: How can I check service's backend list from kube-proxy?
kubectl get endpoints ${SERVICE_NAME}

Still expect comment to "Isn't it a problem to keep an unresponsive pod in service backend list for so long time?" :)

**Comment by mikedanese** [comment]
@YanXiaoping the kube-proxy will retry failed connections with the next backend. Even if 1 out of 3 backends are failing tcp connections (e.g. no longer listening), a client using the kube-proxy should see no impact.

**Comment by thockin** [comment]
kube-proxy probably should keep track of failed backends and preferentially
not use them.  Boy that is going to make the kube-proxy rewrite tricky :)

**Comment by philk** [comment]
Just ran into an issue like this. If you shut down a node, then delete the node in the API before they reach the `--pod-eviction-timeout` from the controller manager the pods never get rescheduled. We had a ton of bad pods laying around.

**Comment by lavalamp** [comment]
@philk Thanks for pointing that out, I made an issue to track that separately.

**Comment by bgrant0607** [comment]
This is obsolete.
