### ISSUE TITLE
Port forwarding stream creation logic is racy

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#13673]
When a new connection is established to a local port that is forwarded to a pod, the current logic in the Kubelet assumes that an error stream will be created first, followed by a data stream (these are distinguished via a header when creating the stream, and linked together via another header containing the forwarded port). However, because the streaming library, spdystream, processes "new stream" frames in nondeterministic order, it is possible for the Kubelet to receive the data stream first, instead of the error stream.

The error presents itself with various stream creation timeouts and occurs most often when multiple connections to the same forwarded port occur at the same time.

1 solution I've come up with is to have the client add a new connectionID header when the streams are created. When the Kubelet receives a stream, it would make sure it gets both the error and data streams for a given connectionID, where order doesn't matter. The problem with this solution is that it breaks backwards compatibility when using an old kubectl client against a new server. I so far haven't come up with any alternatives. Would this kind of change be acceptable?

@smarterclayton @liggitt

**Comment by liggitt** [comment]
Rather than client-assigned stream ids, I would rather do the following:
* Update the client to allocate the error and data streams in a serial, threadsafe way (to guarantee that a particular connection's data and error streams are set up together before another connection's)
* Update the server to accept data/error streams in either order

Client-assigned stream ids seem odd to me, and it would break backward compatibility

**Comment by smarterclayton** [comment]
Jordan's suggestion makes sense.

On Tue, Sep 8, 2015 at 10:34 AM, Jordan Liggitt <notifications@github.com>
wrote:

> Rather than client-assigned stream ids, I would rather do the following:
>
>    - Update the client to allocate the error and data streams in a
>    serial, threadsafe way (to guarantee that a particular connection's data
>    and error streams are set up together before another connection's)
>    - Update the server to accept data/error streams in either order
>
> Client-assigned stream ids seem odd to me, and it would break backward
> compatibility
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13673#issuecomment-138584048>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by ncdc** [comment]
@liggitt we could guarantee the the client creates the pair of streams for a single connection together, but there's no guarantee the server won't still process streams from multiple connections out of order, given the frame worker has 5 workers in the pool.

**Comment by ncdc** [comment]
More info: when you run `kubectl port-forward`, it creates 1 long-running SPDY connection to the apiserver. With each new connection to the local port, 2 new streams are created by the client. The reason I went with a unique identifier to tie together the 2 streams is because if you have multiple connections to the local port at the same time, it will rapidly create many streams, and there's no way to force the server to process them in a specific order.

**Comment by liggitt** [comment]
I'm coming around to the client-generated connectionID idea, but we can preserve backwards compatibility by generating an id for streams that are missing it, using the StreamId.

GenerateConnectionID(errorStream) == errorStream.StreamId
GenerateConnectionID(dataStream) == dataStream.StreamId-2

**Comment by ncdc** [comment]
You still might have the server get this (or any variation):

- dataStream for conn1, streamId=1
- dataStream for conn2, streamId=3
- errorStream for conn2, streamId=7
- errorStream for conn1, streamId=9

**Comment by liggitt** [comment]
sure, new clients set a connectionID, which guarantees correct pairing

old clients still have problems with concurrency, but at least we don't break compatibility for single or spaced-out connections

**Comment by liggitt** [comment]
Also, if the server calculated a connectionID and found that connectionID already had a stream of that type, it would know there was a concurrency issue and could fail that connection, instead of just hanging

**Comment by caesarxuchao** [comment]
Please change the label if the one I applied is not appropriate. Thanks.

**Comment by gmarek** [comment]
cc @dchen1107 @yujuhong

**Comment by liggitt** [comment]
Any other opinions on the client-issued connectionID header approach to correlating data/error stream pairs over a single portforward connection (with fallback to StreamID checking to support current clients)? If not, @ncdc is your branch far enough along to open a WIP PR?

**Comment by ncdc** [comment]
My current branch has some lingering debugging print statements that ultimately need to be removed, I don't have the StreamID fallback coded yet, and I'm sure the unit tests need updating. I have something else that's a higher priority at the moment, so I can either hand my branch off to someone else or come back to it once I've finished the other thing I'm currently working on.
