### ISSUE TITLE
MySQL Galera 3-Node Synchronous example provided

### ISSUE THREAD

**Issue by CaptTofu** [kubernetes/kubernetes#13677]
At Percona Live in Santa Clare in April, I did a talk on running a 3-node Galera cluster on Kubernetes. I recently updated this work for v1 and have a pull request I could immediately make. I work for HP and we have a corporate CLA. I would love to provide this example in the example directory and have other contributions I could make. The example includes pod, rc, service files as well as source for the image that works with Kubernetes.

**Comment by gmarek** [comment]
By all means, please do send us a PR.
