### ISSUE TITLE
Allow user to specify alternative MASTER_IP and MINION_IP_BASE

### ISSUE THREAD

**Issue by bmbroom** [kubernetes/kubernetes#13676]
When creating a vagrant based cluster, the MASTER_IP and MINION_IP_BASE appear to be hardwired to 10.245.1.2 and 10.245.1., respectively, in kubernetes/cluster/vagrant/config-default.sh.  This breaks an environment in which the 10.245.1 subnet has already been assigned (and can't easily be changed).

Please provide a simple mechanism to override these default values.  One approach would be to accept the values of existing environment variables MASTER_IP and MINION_IP_BASE.

**Comment by gmarek** [comment]
cc @a-robinson

**Comment by derekwaynecarr** [comment]
Seems reasonable.

**Comment by roberthbailey** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/10602
