### ISSUE TITLE
Handshaking being the most significant part of the cpu profile

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#13671]
When profiling apiserver on 100-node clusters, the most significant part of the profile is now handshaking. To be more precise:
crypto/tls.(*Conn).Handshake
method can take 25-30 % of CPU.

I'm not sure what we can do with it - maybe trying to reuse tcp connections (although by default we have MaxIdleConnsPerHost set to 2, which I think should be enough).
Any thoughts?

@timothysc @jbeda

**Comment by wojtek-t** [comment]
cc @kubernetes/goog-csi

**Comment by jbeda** [comment]
This looks like it might be a big stumbling block.  Some quick googling suggests that TLS is significantly underoptimized in the go standard libraries.

https://groups.google.com/forum/#!topic/golang-nuts/u22Up7qN7WM
http://grokbase.com/t/gg/golang-nuts/149j833t8c/go-nuts-tls-termination-reverse-proxy-and-performance-issues
https://blog.cloudflare.com/go-crypto-bridging-the-performance-gap/

The CloudFlare link is probably the most interesting.

Some questions that I think we need to answer here:
* Is the bottleneck on the handshake or during data transfer.  Some of the issues above seem to be about optimizing post-handshake.
* What cypher suite are we using?
* Are we doing TLS session resumption?  It looks like there are things that can make that fail and we should check in to it.
* What part of the handshake is actually slow?  Is it the `math/big` stuff as suggested by the first link?  More context on the profile would help.
* Are we really reusing TCP connections?  Ideally we should be able to have a single TCP connection with each kubelet/component and call it a day.  Handshake would be amortized then.

**Comment by timothysc** [comment]
@jbeda from everything I've read thus far it appears to be in the hand-shake.  

I do notice a bunch of updates in 1.5 (https://golang.org/doc/go1.5) regarding tls, but no explicit call-outs to the handshake speed. 

@wojtek-t what version of golang are you checking?

**Comment by wojtek-t** [comment]
@timothysc I was compiling it locally and locally I have 1.5 version (so if there were any improvements, there are already there).

**Comment by wojtek-t** [comment]
@timothysc - my appologies (it seems that I didn't understand out build process). I was running it with 1.4 Go version (at that point). I can try to look into it with 1.5.1 Go version this week.

**Comment by liggitt** [comment]
In openshift, we saw performance issues with the handshake with the ECDHE ciphers as well... related issue (https://github.com/openshift/origin/issues/4417) and temporary workaround (https://github.com/openshift/origin/pull/4414)

**Comment by jeremyeder** [comment]
The exact fingerprint of this issue is in https://github.com/openshift/origin/issues/5106

**Comment by wojtek-t** [comment]
@jeremyeder - yup - I think we figured it out from #15664

**Comment by wojtek-t** [comment]
OK - I'm going to close this issue in favor of #15664
