### ISSUE TITLE
Add a plug point to extended secret type validation

### ISSUE THREAD

**Issue by jhadvig** [kubernetes/kubernetes#13687]
Would be helpful to have a plugin point to extend SecretType, in order to have a new valid secret of that type.

**Comment by deads2k** [comment]
The current structure allows downstream components to add new secret types similar to: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L2083, but it does not allow for extending the secret validation to ensure that the new secret types are well-formed.  See https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L1568. 

@liggitt @bparees fyi

**Comment by davidopp** [comment]
@erictune

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc
