### ISSUE TITLE
Move as many e2e tests into PARALLEL track as possible

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#13694]
Per the closure of #3132, we should move as many e2e tests into the PARALLEL track as possible.

We should move from a PARALLEL whitelist to a SERIAL blacklist, then audit the blacklist and drain it as much as possible.

**Comment by gmarek** [comment]
cc @quinton-hoole

**Comment by quinton-hoole** [comment]
We already use a blacklist, not a whitelist.  Look in e2e.sh for GCE_PARALLEL_FLAKY etc.

**Comment by ihmccreery** [comment]
Woops, could have sworn I saw a whitelist yesterday.  Well, I leave it to you, @quinton-hoole, to say whether this needs to happen.  I opened this per my comment & a :+1: in #3132.

**Comment by quinton-hoole** [comment]
Yup, it's a whitelist.
https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L117
https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L130
https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L245

As for auditing the backlist, that's something that I, and a few others, do periodically.  I don't think that we need an explicit ongoing issue for that.
