### ISSUE TITLE
kube-addons are all guaranteed qos tier, seems like they could be burstable

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#13695]
I want to revisit the resource requirements for kube-addons now that we have qos.

All of the `kube-addons` that are added to the cluster are guaranteed qos for the cpu and memory enumerated resources.  I would like to reduce the amount of resource required by the `kube-addons` if possible so I can spin up a smaller sized cluster and still deploy some basic things without needing multiple nodes. 

Questions:
- Can we update to use requests instead of explicit limits?  
- Can we set requests to half the limits?  

At minimum, it seems like we should be using requests for cpu since that is what most closely aligns to `cpu-shares` unless you enable the kubelet flag to enforce limits via cfs quota.

Thoughts?

@kubernetes/goog-cluster

**Comment by a-robinson** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/13048, intelligent sizing of addons based on cluster size.

**Comment by spiffxp** [comment]
/remove-sig node
/sig cluster-lifecycle
I'm assuming sig-cluster-lifecycle owns addon management
