### ISSUE TITLE
soak test failure: Downward API fails to provide pod IP as an env variable after a while

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#13690]
In our soak test CI environment, the test below starts to fail consistently after a few hours/runs.

Possibly related:
#13052 
#12595

```
Downward API should provide pod IP as an env var

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/downward_api.go:90
"POD_IP=(?:\\d+)\\.(?:\\d+)\\.(?:\\d+)\\.(?:\\d+)" in container output
Expected
    <string>: POD_IP=
    KUBERNETES_PORT=tcp://10.0.0.1:443
    KUBERNETES_SERVICE_PORT=443
    HOSTNAME=downward-api-ba4e2059-5656-11e5-91ed-42010af01555
    SHLVL=1
    HOME=/root
    KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    KUBERNETES_PORT_443_TCP_PORT=443
    KUBERNETES_PORT_443_TCP_PROTO=tcp
    KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443
    PWD=/
    KUBERNETES_SERVICE_HOST=10.0.0.1
    
to match regular expression
    <string>: POD_IP=(?:\d+)\.(?:\d+)\.(?:\d+)\.(?:\d+)
```

Example successful runs (immediately after a cluster build:

* job/kubernetes-soak-continuous-e2e-gce/3045/
* job/kubernetes-soak-continuous-e2e-gce/3046/

... whereafter that test (and only that test) fails continuously:

* job/kubernetes-soak-continuous-e2e-gce/3047/
* job/kubernetes-soak-continuous-e2e-gce/3048/
* job/kubernetes-soak-continuous-e2e-gce/3049/
* job/kubernetes-soak-continuous-e2e-gce/3050/
* job/kubernetes-soak-continuous-e2e-gce/3051/

@smarterclayton @pmorie FYI

**Comment by smarterclayton** [comment]
Is it possible that the pod doesn't get an IP right away?  That docker is
returning an empty string for the pod IP that only later becomes available?

On Tue, Sep 8, 2015 at 3:40 PM, Quinton Hoole <notifications@github.com>
wrote:

> In our soak test CI environment, the test below starts to fail
> consistently after a few hours/runs.
>
> Possibly related:
> #13052 <https://github.com/kubernetes/kubernetes/pull/13052>
> #12595 <https://github.com/kubernetes/kubernetes/pull/12595>
>
> Downward API should provide pod IP as an env var
>
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/downward_api.go:90
> "POD_IP=(?:\\d+)\\.(?:\\d+)\\.(?:\\d+)\\.(?:\\d+)" in container output
> Expected
>     <string>: POD_IP=
>     KUBERNETES_PORT=tcp://10.0.0.1:443
>     KUBERNETES_SERVICE_PORT=443
>     HOSTNAME=downward-api-ba4e2059-5656-11e5-91ed-42010af01555
>     SHLVL=1
>     HOME=/root
>     KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
>     KUBERNETES_PORT_443_TCP_PORT=443
>     KUBERNETES_PORT_443_TCP_PROTO=tcp
>     KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443
>     PWD=/
>     KUBERNETES_SERVICE_HOST=10.0.0.1
>
> to match regular expression
>     <string>: POD_IP=(?:\d+)\.(?:\d+)\.(?:\d+)\.(?:\d+)
>
> Example successful runs (immediately after a cluster build:
>
>    - job/kubernetes-soak-continuous-e2e-gce/3045/
>    - job/kubernetes-soak-continuous-e2e-gce/3046/
>
> ... whereafter that test (and only that test) fails continuously:
>
>    - job/kubernetes-soak-continuous-e2e-gce/3047/
>    - job/kubernetes-soak-continuous-e2e-gce/3048/
>    - job/kubernetes-soak-continuous-e2e-gce/3049/
>    - job/kubernetes-soak-continuous-e2e-gce/3050/
>    - job/kubernetes-soak-continuous-e2e-gce/3051/
>
> @smarterclayton <https://github.com/smarterclayton> @pmorie
> <https://github.com/pmorie> FYI
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13690>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by quinton-hoole** [comment]
Yes, that's entirely possible.  The interesting point is that this test succeeds consistently in our one-off test runs (where we build a cluster and run each test once).  It only fails when we run the test multiple times against the same cluster.

Also relevant is that #13656 actually reverts that test, so it's no longer running in our standard tests, only in our soak test cluster, which predates the above PR.

**Comment by smarterclayton** [comment]
Could we be breaking docker IP allocation?

On Tue, Sep 8, 2015 at 3:51 PM, Quinton Hoole <notifications@github.com>
wrote:

> Yes, that's entirely possible. The interesting point is that this test
> succeeds consistently in our one-off test runs (where we build a cluster
> and run each test once). It only fails when we run the test multiple times
> against the same cluster.
>
> Also relevant is that #13656
> <https://github.com/kubernetes/kubernetes/pull/13656> actually reverts
> that test, so it's no longer running in our standard tests, only in our
> soak test cluster, which predates the above PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13690#issuecomment-138681598>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by pmorie** [comment]
@quinton-hoole I will take a look at the individual runs and see if we can tie the beginning of the failures to some other problem in the system once I have a patch that deals with the pod start latency issues that have been reported

**Comment by davidopp** [comment]
@pmorie Did you have a chance to look into this?

**Comment by lavalamp** [comment]
@pmorie status?

**Comment by pmorie** [comment]
Going to try to reproduce this today.

**Comment by dchen1107** [comment]
@pmorie Do you have any updates on this one?

**Comment by pmorie** [comment]
@dchen1107 No progress to report, I'm looking at it now, though.

**Comment by timothysc** [comment]
@pmorie latest results can be viewed here: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-soak-continuous-e2e-gce/  - you would probably want to grok the last 10 to gleen meaningful info.

**Comment by pmorie** [comment]
@dchen1107 I wasn't able to reproduce this in my own GCE cluster and it doesn't look like it's failed in the last 10 runs -- do you have a suggestion for what the decision plane should be before we close this?  15 runs? 20 runs?

**Comment by quinton-hoole** [comment]
There are no failures in our CI history, which goes back only 50 runs, unfortunately.
So it's definitely much, much better than when this issue was reported.  
I'm happy closing this.
