### ISSUE TITLE
Reducing dependency tree of pkg/labels

### ISSUE THREAD

**Issue by tummychow** [kubernetes/kubernetes#13698]
Hey all, I'm writing some code that imports the `labels` package and running into issues with its [large dependency tree](http://godoc.org/k8s.io/kubernetes/pkg/labels?import-graph&hide=2). Specifically `glog`, which declares flags at init time, is causing panics because its flags collide with other flags that we've already defined. In addition, the `util` package sets `logtostderr` to true [at init time](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/logs.go#L32) which interferes with the logging behavior of our code.

To that end, I propose some changes to prune the dependencies of `labels` significantly, and thereby remove the dependency on `glog` to get rid of its side effects. The `labels` package depends on `util.StringSet` and `fielderrors.NewFieldInvalid`. All its other dependencies are from the standard library. My suggestions are:

- refactor `util.StringSet` into its own package, `k8s.io/kubernetes/pkg/util/stringset`, so that `labels` does not depend on the entirety of `util`. Essentially this would be moving [`set.go`](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/set.go) into another folder. Most of this can be implemented with `gofmt -r`.
- remove [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/fielderrors/fielderrors.go#L164) from `fielderrors` to eliminate the dependency on `glog` from that package. I don't have any strong opinions on what it would be replaced with. Assertion or panic? `fmt.Printf`? This is up to the maintainers, but pulling in the `glog` dependency for this one line makes the use of this entire dependency tree untenable for us.

I would be glad to hear your thoughts on these changes. With the release of Go 1.5, it is possible to move this package under `internal` if you do not want to share it with other clients. However, if it is public, then I think these changes are reasonable to make it more friendly to other importers.

**Comment by mikedanese** [comment]
PRs are welcome. For visibility, I suggest moving this proposal into a comment in #4851 or at least linking it from there since that umbrella issue about package reorg.

**Comment by tummychow** [comment]
Thanks for accepting all 3 of my PRs! This is done.
