### ISSUE TITLE
Downward API volume plugin fail in the docker kubernetes cluster

### ISSUE THREAD

**Issue by zhengguoyong** [kubernetes/kubernetes#13703]
i run the downwardAPI volume example in docker kubernetes cluster.  after i create the pod, i  saw the pod is running , the i check the pod/container output, in the pod's /etc directory i not found the file created by the plugin. 
root@ubuntu:~# kubectl get pods
NAME                                    READY     STATUS    RESTARTS   AGE
k8s-master-127.0.0.1                    3/3       Running   6          18h
kubernetes-downwardapi-volume-example   1/1       Running   0          18h
root@ubuntu:~# kubectl describe pods/kubernetes-downwardapi-volume-example
Name:                           kubernetes-downwardapi-volume-example
Namespace:                      default
Image(s):                       gcr.io/google_containers/busybox
Node:                           127.0.0.1/127.0.0.1
Labels:                         cluster=test-cluster1,rack=rack-22,zone=us-est-coast
Status:                         Running
Reason:
Message:
IP:                             172.17.0.1
Replication Controllers:        <none>
Containers:
  client-container:
    Image:              gcr.io/google_containers/busybox
    State:              Running
      Started:          Wed, 09 Sep 2015 00:30:35 +0800
    Ready:              True
    Restart Count:      0
Conditions:
  Type          Status
  Ready         True 
No events.

root@ubuntu:~# kubectl exec kubernetes-downwardapi-volume-example -i -t -- sh
/ # ls -laR /etc
/etc:
total 20
drwxr-x---    2 0        0             4096 Sep  8 16:30 .
drwxr-xr-x   23 0        0             4096 Sep  8 16:31 ..
-rw-r--r--    1 0        0               38 Sep  8 16:30 hostname
-rw-r--r--    1 0        0              199 Sep  8 16:30 hosts
-rw-r--r--    1 0        0              176 Sep  8 16:30 resolv.conf

**Comment by sdminonne** [comment]
@eulerzgy  I'm trying to reproduce the issue on the HEAD. Let you know asap.

**Comment by pmorie** [comment]
@zhengguoyong can this be closed?

**Comment by yujuhong** [comment]
@zhengguoyong please file a new issue if the problem is reproducible.
