### ISSUE TITLE
Consistent syntax in commented examples

### ISSUE THREAD

**Issue by rhcarvalho** [kubernetes/kubernetes#13719]
About a month ago #12593 was merged. In the issue (#12426) that it was meant to solve, we had an example like this:
```
 // Partially update a node using strategic merge patch
 kubectl patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}'
```

Becoming:
```
 # Partially update a node using strategic merge patch
 kubectl patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}'
```

I can imagine copy-pasting that as is into a terminal, or into a file to run it as a bash script later.
However, I think except for [one file](https://github.com/kubernetes/kubernetes/pull/12593/files#diff-c59558fac792ecdd67a419318d11ae92), all the examples that were changed followed this pattern:

```diff
-// List all pods in ps output format.
+# List all pods in ps output format.
 $ kubectl get pods
```

In this context, $ normally prefixes lines that are meant to be executed as normal user, while # lines are to be executed as root.

I'd propose to have examples as either:
```
$ # comment
$ command
```

Or, with the advantage of being easy to copy-paste, and the disadvantage of being unable to distinguish root vs. non-privileged user:
```
# comment
command
```

Opinions?

**Comment by gmarek** [comment]
cc @bgrant0607

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by bgrant0607** [comment]
@AdoHe Is this something you could work on?

**Comment by AdoHe** [comment]
@bgrant0607 ok I will work on this.

**Comment by ghodss** [comment]
I like:

```
# comment
command
```

**Comment by bgrant0607** [comment]
What @ghodss proposes facilitates cut&paste.

C++-style comments are blatantly wrong.

Prompts ('$') aren't needed, because we don't show output.

**Comment by kargakis** [comment]
This is fixed now in kubectl. @rhcarvalho can you do the same for oc?

**Comment by rhcarvalho** [comment]
@kargakis will do.
