### ISSUE TITLE
kubelet options : if missing --tls-Private-key-file while providing --tls-cert-file leads to ambiguous error message

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#13713]
if we don't provide the `--tls-private-key-file=` option along `--tls-cert-file="/var/run/kubernetes/xyz.crt"`, we get a cryptic error message in the kubelet logs:

```
I0909 04:06:43.217854   32380 server.go:63] Starting to listen on 127.0.0.1:10250
F0909 04:06:43.219260   32380 server.go:72] open : no such file or directory
```

Probably we can clean this up in the flags somehow.   I stumbled into this in trying to better understand certs, so I'm probably not the best person to fix it :)...  But maybe i can give it a shot

**Comment by gmarek** [comment]
cc @thockin

**Comment by thockin** [comment]
shotgun BANG
@mikedanese @liggitt @erictune

**Comment by liggitt** [comment]
Should make sure a non-empty cert and key were both provided prior to starting the server at these two locations, and log a clearer error:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L519
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server.go#L72
