### ISSUE TITLE
Implement kubemark

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#13731]
As proposed in #12530 we want to implement kubemark - a tool to run performance/scalability tests without using physical machines (details in the #12530). This issue is am umbrella bug to track what needs to be done.
- [x] Initial implementation - simple kubelet (similar to the one from integration tests) runs as pod in kubernetes cluster; master runs on a separate VM
- [x] Provide scripts that will allow to easily setup the whole kubemark environment
- [x] Mock remaining parts of kubelet (e.g. disk manager, image manager)
- [x] Configure master to use SSL in kubemark
- [x] Run kube-proxy next to each kubelet
- [ ] Run master as a pod in kubernetes cluster

(sorted from highest to lowest priority)

@wojtek-t @gmarek @davidopp

**Comment by davidopp** [comment]
@gmarek Can we close this?

**Comment by wojtek-t** [comment]
Can we check that we have issues for things like implement support for addons before closing?
@gmarek - are we missing anything significant appart from addons support?

**Comment by davidopp** [comment]
Good point, I forgot about addons.

**Comment by gmarek** [comment]
We lack a mechanism that will assure that Node team will keep SimpleKubelet implementation up to date with the 'real' thing. It's important not only for Kubemark but also for integration tests (cc @kubernetes/goog-node) - but I guess it's out of scope for this issue.

Except for that we miss addons and adding a Kubelet to oversee master components on master node:
- #20804
- #20805

**Comment by gmarek** [comment]
I think we can say that with addition of Secrets plugin to HollowNode and supervisor monitoring api server components we can say it's done.
