### ISSUE TITLE
Future docker upgrade for different OS distros/versions

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#13749]
I believe AWS, GCE, bare-metal and vagrant rely on our [salt file](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/docker/init.sls) to ensure docker installation. Non-RedHat distribution downloads and install a [deb package](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/docker/init.sls#L102). The deb package used to (<=1.7.1) contain a static docker binary. Docker announced two months back that all distributions'd get dynamic binaries.
https://blog.docker.com/2015/07/new-apt-and-yum-repos

Now that we don't have a deb file with a static binary anymore, we need to augment this salt file significantly for each distros/version for docker upgrade. Some initial concerns are:
 - It is not very clear what distros/versions we need to support
 - The salt file is hard to read as it is, and this would only make it worse.

We should figure out what we want to support, what level of control we want (i.e., a specific version or just the existence of docker) and how to continue doing it.

cc @justinsb for AWS setup/support

cc @dchen1107

**Comment by dchen1107** [comment]
Can we upgrade it to docker 1.8.2? Here are two fixes I am caring about:

1) Fix goroutine leak pulling images from registry V2.
2) Fixed an incorrect network namespace switch issue.

The second one already bite us, and we have to patch cadvisor for that. I also noticed several reports related to 1) too.

**Comment by yujuhong** [comment]
I will update my PR to upgrade to docker 1.8.2 (it was not ready that time). There are more registry V2 issues which were not fixed in 1.8.2. @justinsb reported one yesterday and the fix was not included in any release yet (#13804).

**Comment by dchen1107** [comment]
Sorry, my above comment is really for your pr #13752, not the issue here.

**Comment by dchen1107** [comment]
I have a pending PR to resolve this issue, but blocked by https://github.com/docker/docker/issues/16293

**Comment by davidopp** [comment]
@dchen1107 @yujuhong this is marked as team/control-plane (as well as team/node) -- do you need anything from control plane team for this issue?

**Comment by davidopp** [comment]
Removing control-plane label having received no response.

**Comment by bgrant0607** [comment]
If this is for 1.1, it needs to be P0 at this point. Should it be?

**Comment by dchen1107** [comment]
No we decide to leave other provider to 1.7.1 and only bump GCE / GKE to 1.8.3 by default. Also we are dropping support for docker version under 1.6.2 (API version: 1.18)

**Comment by dchen1107** [comment]
I am closing this one since we handle this issue now explicitly through each cloud provider. For example, #21632 is merged for all os distros on aws.
