### ISSUE TITLE
Can't watch or list objects with a given name across all namespaces

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#13743]
`generic/etcd` assumes MatchesSingle is that "metadata.name" is set, but if namespace is not set, matches single should be false.  It should be possible to call `GET /api/v1/pods?fields=metadata%2Dname`

One possible fix is to assume that an error in List and Watch in generic/etcd on KeyFunc means that we should not continue down the match single path.

@wojtek-t @lavalamp

**Comment by smarterclayton** [comment]
Fixing...

**Comment by wojtek-t** [comment]
Good catch and thanks for fixing it.
