### ISSUE TITLE
Document how to write a new volume plugin

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#13753]
Add documentation showing how to write a new volume plugin. Document should how to create a sample plugin, and capture gotchas to watch out for.

**Comment by wyc** [comment]
Hi,

I'd also like to see more technical documentation on how to implement a new volume driver in [pkg/volume](https://github.com/kubernetes/kubernetes/tree/master/pkg/volume). Right now, the [interface](https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/pkg/volume/volume.go) is pretty un-explanatory and the [doc.go file](https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/pkg/volume/doc.go) doesn't contain any relevant writing. I'm willing to spend some time to write a summary and guide on how to implement a new volume-based cloud provider and the particulars of how it interacts with the rest of the system.

The intended target audience would be:
- Cloud providers looking to implement persistent volume support for k8s
- New developers interested in an overview of how volumes interact with the rest of the system
- System administrators who need to understand the code-level coupling of nodes and volumes

I'd like to cover:
- When and how other pieces of the codebase interact with the volume interface implementations
- The characteristics of a typical volume driver
- An implementation of an example volume driver or detailed walkthrough of simpler existing ones such as GlusterFS or NFS

Resources I need to do this:
- Reasonable access to someone familiar with the volume storage system who is willing to check my work for correctness and provide direction

**Comment by saad-ali** [comment]
@wyc Awesome, thanks for helping out with this.

> Resources I need to do this: Reasonable access to someone familiar with the volume storage system who is willing to check my work for correctness and provide direction

@rootfs @jsafrane and I should be able to help out with this.

Looks like somewhere in https://github.com/kubernetes/community/tree/master/contributors/devel/ would be the best home for this doc.

**Comment by saad-ali** [comment]
CC @kubernetes/sig-storage-misc

**Comment by wyc** [comment]
This is my WIP:

https://github.com/wyc/k8s-community/blob/volume-guide/contributors/devel/developer-guides/volume-overview.md

Is this the right tone/scope/style?

**Comment by wyc** [comment]
Hey, I'm writing the FAQ section based on things that were confusing during writing the previous sections. I'm working on a question titled "How do cloud provider volume plugins figure out what mount device (e.g., /dev/sdc) a newly-attached volume will appear as?"

It seems that most of them query their respective APIs and are able to come up with some kind of block device mapping either directly or by something like LUN. What's the use of predicting the next available device?

https://github.com/kubernetes/kubernetes/blob/17e745631aa3af979628841d37bd42f27de3d2e8/pkg/cloudprovider/providers/aws/aws.go#L1223

https://github.com/kubernetes/kubernetes/blob/bf984aa328f3d3e5f8956f7d8e65c13c52102426/pkg/cloudprovider/providers/azure/azure_storage.go#L166

**Comment by wyc** [comment]
Okay a new look tells me that it's prevented here:

https://github.com/kubernetes/kubernetes/blob/17e745631aa3af979628841d37bd42f27de3d2e8/pkg/cloudprovider/providers/aws/aws.go#L1199

This will make it to the implementor's guide.

**Comment by davidz627** [comment]
New plugins no longer being added/written. Please add new storage backends to Kubernetes through CSI: https://kubernetes-csi.github.io/docs/developing.html
/close
