### ISSUE TITLE
please support InfluxDB v0.9

### ISSUE THREAD

**Issue by onlyjob** [kubernetes/kubernetes#13769]
Please support current release of InfluxDB. [InfluxDB promises to be good](https://github.com/influxdb/influxdb#an-open-source-distributed-time-series-database):

>Going forward, the 0.9.x series of releases will not make breaking API changes or breaking changes to the underlying data storage.

**Comment by mikedanese** [comment]
@onlyjob kubernetes does not directly depend on influxdb. influxdb is a downstream dependency of heapster so this issue would be better posed there, but I see there is already an open issue for it. kubernetes/heapster#302

**Comment by onlyjob** [comment]
Thank you.

**Comment by onlyjob** [comment]
Hold on, Kubernetes v1.0.5 have references to InfluxDB in `test/e2e/monitoring.go`. Also I can't find heapster bundled anywhere in Kubernetes...

**Comment by mikedanese** [comment]
@onlyjob the monitoring.go test runs heapster in a pod which writes data to an influxdb backend, then the test checks to make sure data is written properly. When heapster upgrades it's influxdb version, that change will trickle down to kubernetes when kubernetes upgrades heapster.

cc @vishh

**Comment by mikedanese** [comment]
> I can't find heapster bundled anywhere in Kubernetes

we don't bundle heapster per say, we just run it as a pod. The autoscaler calls out to heapster to get resource utilization metrics of pods so we do depend on some heapster api types. See https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/autoscaler/metrics/metrics_client.go#L33
