### ISSUE TITLE
ETCD Prefix should not default to "/"

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#13763]
The prefix should probably default to the empty string or something like "k8s.io". 

When running `go test` in the `pkg/master`, third party objects are stored to `//ThirdPartyResourceData/company.com/foos/default/test` but the double slash is eaten on the HTTP Get:

```console
	fake_etcd_client.go:201: creating //ThirdPartyResourceData/company.com/foos/default/test, index 0 (ttl: 0)
	fake_etcd_client.go:142: data for /ThirdPartyResourceData/company.com/foos/default/test was not defined prior to invoking Get
	master_test.go:234: unexpected status: &{404 Not Found 404 HTTP/1.1 1 1 map[Content-Type:[application/json] Date:[Wed, 09 Sep 2015 20:41:40 GMT] Content-Length:[259]] 0xc8202b1380 259 [] false map[] 0xc8202dc0e0 <nil>}
```

**Comment by lavalamp** [comment]
"registry" would also be a sane default.

**Comment by krousey** [comment]
Possibly even validate the the specified prefix doesn't end in a slash too.

**Comment by caesarxuchao** [comment]
+1, I encountered this problem last night.
