### ISSUE TITLE
pkg/probe/http fails with Go 1.5 or 1.4

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#13764]
```console
hack/test-go.sh pkg/probe/http
Running tests for APIVersion: v1 with etcdPrefix: registry
+++ [0909 14:18:36] Running tests without code coverage
--- FAIL: TestHTTPProbeChecker (1.00s)
	http_test.go:78: Expected use of closed network connection, got Get http://127.0.0.1:39766: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
FAIL
FAIL	k8s.io/kubernetes/pkg/probe/http	1.034s
```

**Comment by krousey** [comment]
Looks maybe like a fragile test relying on certain error messages.

**Comment by mikedanese** [comment]
Hopefully #13058 will fix this

**Comment by brendandburns** [comment]
fwiw, this just flaked in Shippable + go 1.4:

```
http_test.go:103: Expected success, got failure
http_test.go:106: Expected one of []string{"ok body"}, got Get http://127.0.0.1:60629: net/http: request canceled while waiting for connection
```

https://app.shippable.com/builds/560c2ab1354b7c0c00ca4e86

**Comment by mikedanese** [comment]
The error is a timeout waiting for the local test server. This may have been a shippable environment issue but i was not able to reproduce locally. We can either not use "net/http/httptest" anywhere or we can see reopen if this still happens now that we don't run on shippable anymore.

**Comment by gajju26** [comment]
Hi All,
This test is failing in my environment system-z architecture and go1.4 with different error message "http_test.go:106: Expected one of []string{"use of closed network connection", "request canceled (Client.Timeout exceeded while awaiting headers)"}, got Get http://127.0.0.1:56654: net/http: transport closed before response was received (Client.Timeout exceeded while awaiting headers)." 
Can anyone tell me this error message is expected or not?
