### ISSUE TITLE
Kubelet supports dropping in network plugins at runtime.

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#13760]
Currently, if a network plugin is declared using the `--network-plugin=` flag, and the plugin is not installed, the Kubelet will fail to start.

This makes bootstrapping a node via the Kubelet somewhat trickier, since the network plugin needs to be installed before the Kubelet is started.

One way you might want to deploy a network plugin is to use a per-node manifest file which installs the plugin (and in the Calico case runs the per-node agent).  This currently can't be done, since the Kubelet won't run and thus won't load the manifest unless the network plugin is already installed.

I'm interested in getting other people to chime in and provide thoughts on if this is useful, or if this is crazy and no one should be trying to deploy network-plugins in this manner.

**Comment by philips** [comment]
The use case that Casey and I talked about for this: a pod launched by a kubelet via an on-disk manifest can place a network plugin on disk and then have the kubelet use that network plugin going forward. It is a bit of a bootstrap loop.

**Comment by dchen1107** [comment]
cc/ @kubernetes/goog-cluster

**Comment by thockin** [comment]
having a container use a hostPath to "install" a plugin is a bit clunky,
but I am not against the idea of only looking for network plugins when they
are needed and logging an error and event at that time.

This means that all plugin containers would need to run with host
networking, or we would have to do the equiv of docker's --net=none.

@dchen1107

**Comment by AdoHe** [comment]
@thockin I think we should provide an option to configure the net mode. Actually I prefer `--net=none`, since I want to my network plugin to control the network of containers, and I don't want to use `veth` and `docker0`.

**Comment by thockin** [comment]
That's what CNI plugins give you.

**Comment by AdoHe** [comment]
@thockin yeah I will use the CNI network plugin. Thanks very much.

**Comment by philips** [comment]
cc @aaronlevy @mikedanese @pb0 @derekparker

**Comment by thockin** [comment]
For teh sake of our busting-at-the-seams issue list, I'm going to close this.  If anyone feels it needs more discussion, please object. :)
