### ISSUE TITLE
API Package structure

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#13772]
`pkg/expapi/v1` needs to be renamed to `experimental/v1`. But where to put it?
- pkg/api/experimental/v1
- pkg/api/groups/experimental/v1
- pkg/apigroups/experimental/v1

Some of these might imply moving our current api types.

I don't think it's a good idea to put our api groups loose under pkg/.

**Comment by lavalamp** [comment]
@bgrant0607 @caesarxuchao

**Comment by bgrant0607** [comment]
pkg/apis/experimental/v1alpha1
pkg/apis/api/

**Comment by bgrant0607** [comment]
and for "internal"
pkg/apis/experimental/unserialized
pkg/apis/api/unserialized

sadly, we can't use "internal"

**Comment by lavalamp** [comment]
OK, that sounds good to me.

**Comment by lavalamp** [comment]
We'll leave global types where they are. (i.e., pkg/api/resource, pkg/api/unversioned etc.)

**Comment by bgrant0607** [comment]
Yes, that stuff can move later, when we clean up apiserver-related packages: #https://github.com/kubernetes/kubernetes/issues/4851#issuecomment-132052036, #2742

**Comment by thockin** [comment]
uggh, api and apis ?  That's going to be hell on tab-complete and visual
ident.

Can we do this, expunge everything from pkg/api, and then reclaim that name?

**Comment by caesarxuchao** [comment]
@thockin, we won't have pkg/api/, we will move it to pkg/apis/api (see https://github.com/kubernetes/kubernetes/issues/13772#issuecomment-139063633), is that bad? That shouldn't affect tab-complete.

**Comment by thockin** [comment]
The redundancy makes me sad, but I don't have a better answer.

**Comment by tmrts** [comment]
What about something like `pkg/api/release/v1`  or `pkg/api/stable/v1` and `pkg/api/experimental/v1alpha1`?

I imagine `pkg/apis/experimental` and `pkg/apis/api` will be confusing to people.

**Comment by lavalamp** [comment]
@thockin Yeah, my goal is to move things out of pkg/api until there's nothing there. I'm waiting for #13823 to land, and then I'll do another big move.

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/kubernetes/issues/4851#issuecomment-132052036, which discusses the machinery half of pkg/api (as opposed to the API schema-definition half).

**Comment by bgrant0607** [comment]
Done as much as it's going to be for 1.1.

**Comment by lavalamp** [comment]
See also: #16062

For finalizing this cleanup, how would people feel about moving the "core" api types from `pkg/api/` into `pkg/apis/core/`? That would get types.go, v1/, registration and conversion code out of the current `pkg/api`, and make it totally regular with the rest of our groups--with the exception of its name.

Alternatives: `pkg/apis/api`, `pkg/apis/legacy`

**Comment by caesarxuchao** [comment]
Do we need to reserve the name `core` for a future group? If so, I'll vote for `pkg/apis/legacy`, otherwise `pkg/apis/core`.

**Comment by lavalamp** [comment]
`pkg/apis/core` sounds good to me. Doesn't look like we'll get to this for 1.2, though.

**Comment by smarterclayton** [comment]
The move to external APIs will cover this.  Closing because it's already tracked there.
