### ISSUE TITLE
please support AWS-SDK v0.9

### ISSUE THREAD

**Issue by onlyjob** [kubernetes/kubernetes#13770]
Current version of [AWS-SDK](https://github.com/aws/aws-sdk-go/releases) is v.0.9.5 while Kubernetes supports only v0.6. Please update to current version of AWS-SDK.

**Comment by mikedanese** [comment]
@onlyjob any reason why we need to bump the version? Is something broken? 

cc @justinsb @iterion

**Comment by onlyjob** [comment]
No urgent reasons but it is nice to stay up to date and AWS SDK is [packaged](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798297) for [Debian](http://debian.org) hence it would be great if Kubernetes on Debian could take advantage of properly compartmentalised AWS SDK library. Thanks.

**Comment by justinsb** [comment]
So I have code that does this, which I have just proposed as a PR #13805.  I am uncertain whether we should merge it though.  I agree that we should be on the latest code, except that it only just last week moved out of RC, and this version includes some fairly large breaking changes to naming.  In particular, they changed the capitalization from go-style (VPC) to match AWS (Vpc) in a number of places.

I don't know if this change it going to stick or if the aws-sdk-go library will change their mind; I couldn't find any discussion of the motivation behind the change (but nor did I find any backlash!)

I'll mark the PR as WIP for now, but happy to have the discussion to figure out whether we should follow the library here.

**Comment by justinsb** [comment]
We are now using 0.9.9.  Thanks for the reminder @onlyjob !
