### ISSUE TITLE
Make generic: Conversion & Deep copy generators

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#13775]
It's currently impossible to use the generators on arbitrary go packages, even if the packages are arranged correctly. This makes it really difficult to generically deal with different api groups.

**Comment by lavalamp** [comment]
FYI @wojtek-t

**Comment by lavalamp** [comment]
BTW-- the swagger doc generator does this correctly. \o/

**Comment by wojtek-t** [comment]
As discussed offline, we should rewrite those tools to parse "types.go" files instead of using the compiled version. We should use the existing infrastructure: go/parser go/ast for it.

**Comment by thockin** [comment]
The sketchy code-gen I did to argue for methods in API machinery uses the
reflect approach but generates to a new pkg, so the destination does not
need to compile in order to be regenerated.  I think this is a decent
attack.  That said, if we switch to AST and we have a common way of
slurping in the whole deps tree from an API file, I could follow that path
instead.

**Comment by lavalamp** [comment]
IIRC golang.org/x/types does type checking (type name resolution), which will be useful for this.

We definitely want to switch to using an AST method instead of reflection.

**Comment by thockin** [comment]
I can't find any such pkg...

**Comment by uluyol** [comment]
go/types for Go 1.5+ (stdlib), golang.org/x/tools/go/types for <1.5. The APIs are [not identical](https://golang.org/doc/go1.5#go_types).

**Comment by lavalamp** [comment]
A start is in #14665.

**Comment by wojtek-t** [comment]
Deep-copy generator is already migrated (I've just finished it).

I will do the conversion next.

**Comment by wojtek-t** [comment]
I already migrated to conversion-generator to the framework.
Closing as fixed.
