### ISSUE TITLE
Add a kubectl cp ... command

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#13776]
Containers are supposed to be immutable, I know, but sometimes copy is useful...

Syntax:

``` sh
# copy from a container to local
kubectl cp container:/path/to/file /path/to/local/file

# copy from local to container
kubectl cp /path/to/local/file container:/path/to/file

#copy from container to container
kubectl cp container1:/path/to/file container2:/path/to/other/file
```

@smarterclayton @bgrant0607 @kubernetes/kubectl

**Comment by smarterclayton** [comment]
Is that pod to pod copy without an intermediate, or passing back to the client?  We'd need to identify pod -> container specificity

**Comment by bgrant0607** [comment]
I agree this would be useful for debugging.

Please ensure pod/container syntax is consistent with exec, log, etc.

As @smarterclayton pointed out, you need to identify the pod.

How do you imagine implementing this?

cc @ncdc @vishh

**Comment by bgrant0607** [comment]
And we should ensure it handles volumes properly. Not sure if docker's cp does yet. Almost certainly it won't work for terminated containers.

**Comment by smarterclayton** [comment]
I should note we're going to do a client side command for rsync that does
increments transfer over exec, and rely on the client local rsync for bulk
transfers.  This is a good general purpose tool to have just because you
don't need anything in the remote container (although eventually I'd like
to be able to inject a shell into any container via a busybox like http one
off server proc)

On Sep 9, 2015, at 8:28 PM, Brian Grant <notifications@github.com> wrote:

I agree this would be useful for debugging.

Please ensure pod/container syntax is consistent with exec, log, etc.

As @smarterclayton <https://github.com/smarterclayton> pointed out, you
need to identify the pod.

How do you imagine implementing this?

cc @ncdc <https://github.com/ncdc> @vishh <https://github.com/vishh>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13776#issuecomment-139079693>
.

**Comment by brendandburns** [comment]
Yes, will def. make it match `exec/attach/logs/...`

@bgrant0607 I was thinking of implementing it in terms of exec, e.g.

`kubectl cp $local-file $remote-file` just looks like:

`cat $local-file | kubectl exec bash -c "cat > $remote-file"`

And

`kubectl cp $remote-file $local-file` is
`kubectl exec cat $remote-file > $local-file`

Possibly mix in some `kubectl ls $remote-file` to try to do maintain permissions / uid

And I envisioned the remote to remote transiting at least through the master, and likely through the client in the first pass (it's just easier, though I understand why you wouldn't want to do that)

@smarterclayton can you add more detail to what you are thinking wrt rsync, I had a little trouble parsing your description in particular ("that does increments transfer over exec")

Thanks
--brendan

**Comment by resouer** [comment]
@bgrant0607 FYI, `docker cp` is implemented by directly copy files from host's file system, we'll do a fake `Mount` to generate real paths of container on the host, including volume dir. In a word, quite a `docker specific` way.

One of the concern is: I can see dockerd is so vulnerable that even larger amount log stdout may crash it. Not sure if `cp` big file or a lot of files will be too much burden for it?

**Comment by smarterclayton** [comment]
The rsync path was exactly the same as what you described, `rsync -av -e
'kubectl exec -i ...'` localdir remotehost:/remotedir.  We have to make one
change to allow it though, because when you run rsync like this it adds the
argument of the destination host first, then the command second.  I haven't
looked at exec in the last few weeks but we probably need to have a way to
enforce that for exec to work.

The docker cp path is another option, and the best part is it doesn't
require anything specific in a container.  However, right now (because I
got overruled by certain @thockin for the default path *cough*) exec *also*
goes through the dockerd.  We have alterative solutions but they haven't
been prioritized yet.  So docker cp is no worse than exec.

On Thu, Sep 10, 2015 at 9:13 AM, Harry Zhang <notifications@github.com>
wrote:

> @bgrant0607 <https://github.com/bgrant0607> FYI, docker cp is implemented
> by directly copy files from host's file system, we'll do a fake Mount to
> generate real paths of container on the host, including volume dir. In a
> word, quite a docker specific way.
>
> One of the concern is: I can see dockerd is so vulnerable that even larger
> amount log stdout may crash it. Not sure if cp big file or a lot of files
> will be too much burden for it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13776#issuecomment-139230662>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by brendandburns** [comment]
@smarterclayton the rsync version requires the rsync daemon be present in the container, which is kind of an unnecessary requirement, don't you think?  I don't really want to use `docker cp` since it requires plumbing a whole additional API call through the kubelet, apiserver etc.

I think I will just stick with cat.

**Comment by smarterclayton** [comment]
Might be unnecessary, but present in the vast majority of containers.
We're doing it mostly to enable rapid dev scenarios on Windows - it's not
trivial to get an rsync on a windows system, but it's still a better
experience than pretty much any other story for dealing with O(1K) files
that need to be synced.

**Comment by xied75** [comment]
:100: Since kubectl aligns subcommands with docker, a 'cp' is definitely needed for everyday life, so that DevOps can still have some hair left. With 'cp' ability lots of problems can be solved with it, e.g. a gitrepo volume mount is no longer needed as many people use it to just get hold of some conf file, also the genius usage of k8s Secret for the same purpose.

Given we can do "kubectl exec <container> <whatever cmd>" and this goes via TLS channel, can we do something similar to ssh/sshd that we can open a reverse proxy port somehow? If that's possible then in order to get a file into the running container I can do this:
"kubectl exec <container> -- scp -P 22000 me@localhost:/home/me/k8s/nginx/default.conf /etc/nginx/conf.d/default.conf"

**Comment by johanhaleby** [comment]
I would also be interested in this. My use case is that I've created/edited a file locally I and want to copy it to a pod that has a Google Persistent Disk attached to it.

**Comment by bittrance** [comment]
@xied75 I have a python script in container that allows this:

tar cf - . | kubectl exec shinken -i -- catcher /configdir

See https://github.com/bittrance/docker-shinken/blob/master/catcher.py

**Comment by xied75** [comment]
Interesting enough I found similar solution yesterday, looks like "cp" can be done like this:

```
kubectl exec -i mypod -- /bin/bash -c 'cat > /the/path/to/your/pod/file.txt' < /path/to/your/local/file.txt
```

**Comment by joeatwork** [comment]
Some containers don't have equipment like bash or scp (or even cat) installed - one example of a container like this is gcr.io/google_containers/etcd:2.0.9, which is a pretty common beast in most Kubernetes clusters.

**Comment by xoss** [comment]
Thanks to @bittrance and @xied75, we found an even shorter solution which also includes entire directories:
```
tar cz . | kubectl exec -i POD -- tar xz .
```

Now, we have a `node-dev` (quay.io/amadeusmuc/node-dev) running in the developer's namespace and sync the entire folder to that plain vanilla node container. It is a rough solution, but it does work. 
However, a decent implementation would help a lot.

**Comment by jhoblitt** [comment]
1 for built in `cp` support.  This would be invaluable for debugging.

**Comment by xiaomengyi** [comment]
Support this feature, it would be helpful.

**Comment by dbbernstein** [comment]
+1 for working in a container without remote editing

**Comment by expz** [comment]
The Openshift Origin "distributon" of Kubernetes has already implemented an `rsync` subcommand of their `oc` command (in Go, of course). Perhaps it can be used without much modification:

> https://github.com/openshift/origin/tree/388478c40e751c4295dcb9a44dd69e5ac65d0e3b/pkg/cmd/cli/cmd/rsync

**Comment by whereisaaron** [comment]
While some form of runtime container file transfer would be handy, the 'docker cp' command features [obscure semantics with a range of overloaded behaviors triggers by judicious placement of slashes and dots](https://docs.docker.com/engine/reference/commandline/cp/). I'd prefer to see 'docker cp' semantics left behind in favor of one or two cleaner kubectl commands.

**Comment by joshperry** [comment]
This is an interesting req that I found after trying to do a volume mount, out of habit, with `kubectl exec`. I would definitely make use of this occasionally, but perhaps a volume mount feature more often.

When I need to copy things to containers it's usually to do some kind of debugging or hotfix, and I need some tools to facilitate my task. It would be nice to be able to attach a volume with tools or files along with the exec and then just use cp on the container system to copy from the volume if needed.

Mounting `~/.ssh` for example would be particularly helpful.

**Comment by sijnc** [comment]
This would be very helpful, would love to be able to mount a pod/container and be able to live edit files for debugging and hotfix as suggested by @joshperry. We have a very large deployment that cannot run on a local dev machine so we have to develop in the kubernetes cluster.

The ability to mount via something like SSHFS would be great!

**Comment by brendandburns** [comment]
I just realized that we could even use this to write a FUSE driver...  Mount your pod's file system into the local filesystem.

What could possibly go wrong :)

**Comment by feniix** [comment]
You mean something similar to this?  https://github.com/opencredo/kubefuse

**Comment by mqliang** [comment]
```
kubectl exec POD -c Container -i 
apt-get insatll lrzsz
rz #receive file
sz FILE #send file
```
works for terms supporting zmodem/ymodem/xmodem , such as xshell, and iterm2(with zmodem integrating, see https://github.com/aurora/iterm2-zmodem). If we want send/receive file    using web term, it does't work, since web term does not support zmodem/ymodem/xmodem

**Comment by mark9white** [comment]
@feniix that app gives you the kubernetes resources on the filesystem, not the pod filesystem.

Here's a little script I've got to mount the pod filesystem on OS X into ~/Downloads/fuse with $2 being the pod name:

    kill $(ps aux  | grep "5100:22" | grep kubectl |  awk '{print $2}')
    umount -f ~/Downloads/fuse

    kubectl exec -i $2 -- /bin/bash -c 'cat > /sshfsci' < ~/bin/sshfsci
    kubectl exec $2 -- /bin/bash  -c "chmod +x /sshfsci; /sshfsci"

    kubectl port-forward $2 5100:22 &
    sleep 2

    mkdir -p ~/Downloads/fuse
    sshfs root@localhost:/ ~/Downloads/fuse -p 5100 -o reconnect,ServerAliveInterval=5,ServerAliveCountMax=3
    cd ~/Downloads/fuse

and the ~/bin/sshfsci script contains (replace *** with the key):

    if [ $(dpkg-query -W -f='${Status}' openssh-server 2>/dev/null | grep -c "ok installed") -eq 0 ];
    then
      apt-get update && apt-get install -y --no-install-recommends openssh-server;
    fi
    mkdir /var/run/sshd
    sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
    if [ "$HOME" = "/" ]
    then
      SSH_HOME=/root/.ssh
    else
      SSH_HOME=$HOME/.ssh
    fi
    echo $SSH_HOME
    mkdir -p $SSH_HOME
    echo ssh-rsa ****** > $SSH_HOME/authorized_keys
    chmod 600 $SSH_HOME/authorized_keys
    service ssh start

**Comment by arterrey** [comment]
here is an rsync solution... super hacky but seems to work, assumes you have rsync in the container

```
rsync -av -e 'kubectl exec POD -i -- env ' --rsync-path= rsync:/var/www/html ./html
```

**Comment by smarterclayton** [comment]
Yeah, that's what we use in openshift (for linux platforms).  Works pretty
well when both client and server match up, can be more difficult on windows.

**Comment by timgivois** [comment]
+1

**Comment by brendandburns** [comment]
This was added.  I used `tar`, that is all.

**Comment by anguslees** [comment]
Just because I didn't see it explicitly spelled out above, the rsync version is as easy as ensuring the rsync binary exists in the container and setting `RSYNC_RSH` env var to point to the location of this script:

```sh
#!/bin/sh
name="$1"; shift
exec kubectl exec $name --stdin -- "$@"
```

Then you can just do `rsync /local/path $name_of_container:/remote/path` and all the other rsync argument variations as usual.

**Comment by mrmcmuffinz** [comment]
I know I'm kinda late to the game here and this item was closed but what was the exact solution be able to copy a remote file over from my host to the pod? I'm on linux/unix so no windows issues here.

**Comment by ax-nathan** [comment]
@mrmcmuffinz 
```
$ kubectl cp --help
Copy files and directories to and from containers.

Examples:
  # !!!Important Note!!!
  # Requires that the 'tar' binary is present in your container
  # image.  If 'tar' is not present, 'kubectl cp' will fail.
  
  # Copy /tmp/foo_dir local directory to /tmp/bar_dir in a remote pod in the default namespace
  kubectl cp /tmp/foo_dir <some-pod>:/tmp/bar_dir
  
  # Copy /tmp/foo local file to /tmp/bar in a remote pod in a specific container
  kubectl cp /tmp/foo <some-pod>:/tmp/bar -c <specific-container>
  
  # Copy /tmp/foo local file to /tmp/bar in a remote pod in namespace <some-namespace>
  kubectl cp /tmp/foo <some-namespace>/<some-pod>:/tmp/bar
  
  # Copy /tmp/foo from a remote pod to /tmp/bar locally
  kubectl cp <some-namespace>/<some-pod>:/tmp/foo /tmp/bar

Options:
  -c, --container='': Container name. If omitted, the first container in the pod will be chosen

Usage:
  kubectl cp <file-spec-src> <file-spec-dest> [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

**Comment by hex0cter** [comment]
+1!

**Comment by fncmedia** [comment]
Should it be possible to copy files of an completed pod? I failed on trying. Docker cp makes it possible when using on kubernetes node but this does not solve our issue.

**Comment by voyalab** [comment]
+1

**Comment by AnthonyWC** [comment]
@fncmedia Did you check if tar is installed in the container?

**Comment by NiraliSupe** [comment]
Hello,
I need to take volume backup. I am trying to rsync pod volume folder to backup folder.
```rsync -avv -e 'kubectl exec postgres-5554f4fdd4-nhs48 -n default -i -- env ' --rsync-path=/var/lib/postgresql/data/  ~/pod```

but it is giving output
```➜  ~ rsync -avv -e 'kubectl exec postgres-5554f4fdd4-nhs48 -n default -i -- env ' --rsync-path=/var/lib/postgresql/data/  ~/pod
building file list ...
done
drwxr-xr-x          64 2018/04/21 13:50:10 podd
delta-transmission disabled for local transfer or --whole-file
total: matches=0  hash_hits=0  false_alarms=0 data=0

sent 98 bytes  received 20 bytes  236.00 bytes/sec
total size is 0  speedup is 0.00
```
and pod folder is empty

can someone please help with this?

**Comment by mckingho** [comment]
Is this command working on `remote pod -> remote pod`? I tried with `kubectl cp podA:/app/a.tar.gz podB:/app/` and got `error: open /app: permission denied`. 
Is it unsupported or permission issue that i set unproperly? I can cp from podA to local and then cp from local to podB inconveniently.

**Comment by back-2-95** [comment]
Just wanted to let you know what started to work for me:

```
rsync -aurP --exclude='*.json' --exclude=css --exclude=js --exclude=languages --exclude=php --exclude=styles --exclude=translations --blocking-io --rsync-path=/var/www/html/public/sites/default/files/ -e '/usr/local/bin/kubectl exec -i -n NAMESPACE --container CONTAINER_NAME POD_NAME -- env ' \
		rsync: ./public/sites/default/files/
```

Weirdest was that when I had:

`rsync:/var/www/html/public/sites/default/files/ ./public/sites/default/files/`

It synced everything from working dir and did not respect that path.

And that was needed to change to flag `--rsync-path=/var/www/html/public/sites/default/files/` and having src & dest as `rsync: ./public/sites/default/files/`

**Comment by Gerst20051** [comment]
I got it to work copying a local file to the pod like this:

[$]> `kubectl exec -i $pod -- /bin/bash -c 'cat > /app/file.txt' < ~/file.txt`

Has anyone figured out the reverse of this to get `/app/file.txt` on the **remote** to `~/file.txt` on **local**?

**Comment by glensc** [comment]
untested, but should work:

to read a file:
```
kubectl exec $pod -- cat /path/to/remote/file.txt
```

to write a file:
```
kubectl exec $pod -- tee /path/to/remote/file.txt < /path/to/local/file.txt
```

**Comment by mind-mind** [comment]
There is anyone know how can I get the throughput of `kubectl cp `

Thank you.

**Comment by mrmcmuffinz** [comment]
@brendandburns @smarterclayton @bgrant0607 @kubernetes/kubectl Can we lock this issue? I feel like this issue is just being compounded with support request and don't contribute anything meaningful to the discussion. If individuals have problems they should open up a new issue or try to reach out for help on slack.
