### ISSUE TITLE
server.key and server.crt was not generated from the ansible installing.

### ISSUE THREAD

**Issue by tech2free** [kubernetes/kubernetes#13795]
https://storage.googleapis.com/kubernetes-release/easy-rsa/easy-rsa.tar.gz doesn't contain server.crt and server.key which has an impact on ansible installing the Kubernetes.

**Comment by tech2free** [comment]
I got code list below: 

```
cp -p pki/ca.crt "${cert_dir}/ca.crt"
cp -p "pki/issued/${master_name}.crt" "${cert_dir}/server.crt"  > /dev/null 2>&1
cp -p "pki/private/${master_name}.key" "${cert_dir}/server.key" > /dev/null 2>&1
cp -p pki/issued/kubecfg.crt "${cert_dir}/kubecfg.crt"
cp -p pki/private/kubecfg.key "${cert_dir}/kubecfg.key"
cp -p pki/issued/kubelet.crt "${cert_dir}/kubelet.crt"
cp -p pki/private/kubelet.key "${cert_dir}/kubelet.key"

CERTS=("ca.crt" "server.key" "server.crt" "kubelet.key" "kubelet.crt" "kubecfg.key" "kubecfg.crt")
for cert in "${CERTS[@]}"; do
  chgrp "${cert_group}" "${cert_dir}/${cert}"
  chmod 660 "${cert_dir}/${cert}"
done
                         
```
from 
```
cp -p "pki/issued/${master_name}.crt" "${cert_dir}/server.crt"  > /dev/null 2>&1
cp -p "pki/private/${master_name}.key" "${cert_dir}/server.key" > /dev/null 2>&1

```
above, it seems that we may don't need the server.key and server.crt, but the code below we need them.    
What's on the earth for this?

**Comment by tech2free** [comment]
I found code below to generate server.key and server.crt 
```
 ./easyrsa --subject-alt-name="${sans}" build-server-full "${master_name}" nopass 
```
Something must be wrong that cause the loss of server.key and server.crt

**Comment by mikedanese** [comment]
@tech2free would this be better filed in https://github.com/kubernetes/contrib where ansible deploy stuff lives? cc @eparis

**Comment by eparis** [comment]
it does belong there, not here.  I don't understand the problem...  Can you please restate what your remaining problem is in an issue there?

**Comment by tech2free** [comment]
Thanks for this reply. In the end I resolve by modify next code, because I have multiple NICs on this machine which cause the cert generation process failed.
```
 # The IP(s) for which the certificate will be valid
-kube_cert_ip: "{{ hostvars[inventory_hostname]['ansible_all_ipv4_addresses'] | join (',IP:') }}"
+# kube_cert_ip: "{{ hostvars[inventory_hostname]['ansible_all_ipv4_addresses'] | join (',IP:') }}"
+kube_cert_ip: "{{ hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address'] }}"
```
