### ISSUE TITLE
NegotiateVersion happens too often

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#13794]
Whenever a client is requested from the client cache, it negotiates a version with the API server (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/clientcache.go#L63).  For longer latency connections, this adds noticeable delays to every `kubectl` command to gather information that doesn't change very often.  If we don't change our approach, this problem will be exacerbated by API groups and discovery.

Instead of requesting the information every call, we could cache the api-version information locally.  Based on that cache, the client could choose a preferred version and simply force the `RESTClient` to that particular version.  If we update the API server to add additional headers to the 404 returned when an invalid version is specified, the client could unambiguously know that the api-version is no longer valid.  At that point we could clear the cache, give a good error message, and re-populate it on next `kubectl` command.

I like the idea of a separate cache instead of re-using something like a kubeconfig file, because there's no real reason for user intervention.  I'd like to allow our tooling to mutate the local cache at will and kubeconfig files aren't the right place to make those kinds of modifications.

@smarterclayton @jlowdermilk @liggitt @kubernetes/kube-api @kubernetes/kubectl

**Comment by liggitt** [comment]
Based on the comment at https://github.com/kubernetes/kubernetes/pull/13667#issuecomment-139113600, it sounds like kubectl is also requesting swagger spec docs during create/replace calls if --validate=true (which is the default). That's another large request we don't want to repeat for every call... if that could use a similar caching strategy, that would be ideal

**Comment by smarterclayton** [comment]
The pattern of Apis identifying which versions are valid as part of a header response is well established.  The vast majority of this information is going to change infrequently at best, which makes a cache practical.  As long as invalidation is easy and predictable for users, that's not a significant issue.

The swagger doc validation is all work that could be done in other ways - I'm not sure it currently reflects the long term goals of the interaction pattern, and is something only one client is doing today.

**Comment by smarterclayton** [comment]
It should be possible to run without a cache for whatever reason, but for
OpenShift and production use cases I don't want to take the negotiate
latency hit, so even if we are less comfortable with using the cache in
Kube I'd like to get the machinery in so we can bypass it in OS.

On Thu, Sep 10, 2015 at 8:49 AM, Jordan Liggitt <notifications@github.com>
wrote:

> Based on the comment at #13667 (comment)
> <https://github.com/kubernetes/kubernetes/pull/13667#issuecomment-139113600>,
> it sounds like kubectl is also requesting swagger spec docs during
> create/replace calls if --validate=true (which is the default). That's
> another large request we don't want to repeat for every call... if that
> could use a similar caching strategy, that would be ideal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/13794#issuecomment-139226435>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by lavalamp** [comment]
@caesarxuchao - we discussed this earlier today. We should do one negotiation request per invocation of kubectl.

(in the future, we could reduce that to 0 if we started caching the server's response, although I don't know if that's really a huge performance win.)

**Comment by smarterclayton** [comment]
It's a big latency hit for every single Cli command everyone makes.  David
has a todo to come back with a better approach.  We've already had
complaints from people working remotely that it pushes the cli from seeming
fast to seeming slow

On Sep 24, 2015, at 7:03 PM, Daniel Smith <notifications@github.com> wrote:

@caesarxuchao <https://github.com/caesarxuchao> - we discussed this earlier
today. We should do one negotiation request per invocation of kubectl.

(in the future, we could reduce that to 0 if we started caching the
server's response, although I don't know if that's really a huge
performance win.)

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13794#issuecomment-143072152>
.

**Comment by lavalamp** [comment]
Actually, maybe there's a way to reduce this to ~0 calls per invocation. The idea is that kubectl locally caches the server's version output, and predicates its HTTP calls on that output not having changed, with one of the ETag type headers, like If-Unmodified-Since. http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by lavalamp** [comment]
@krousey Something to consider as we improve the client.

**Comment by smarterclayton** [comment]
We will get a 404 if the API version doesn't exist.

On Oct 2, 2015, at 2:15 PM, Daniel Smith <notifications@github.com> wrote:

Actually, maybe there's a way to reduce this to ~0 calls per invocation.
The idea is that kubectl locally caches the server's version output, and
predicates its HTTP calls on that output not having changed, with one of
the ETag type headers, like If-Unmodified-Since.
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13794#issuecomment-145112643>
.

**Comment by lavalamp** [comment]
Joining #13153 with this issue.

**Comment by lavalamp** [comment]
xref #14895

**Comment by liggitt** [comment]
This has gotten worse with the API group discovery... there are multiple version negotiation calls run now with every invocation

**Comment by kargakis** [comment]
I see three :)
```
I0512 17:21:54.002655   26956 round_trippers.go:296] GET http://127.0.0.1:8080/api
I0512 17:21:54.002665   26956 round_trippers.go:303] Request Headers:
I0512 17:21:54.002671   26956 round_trippers.go:306]     Accept: application/json, */*
I0512 17:21:54.002674   26956 round_trippers.go:306]     User-Agent: kubectl/v1.3.0 (linux/amd64) kubernetes/644fa22
I0512 17:21:54.003429   26956 round_trippers.go:321] Response Status: 200 OK in 0 milliseconds
I0512 17:21:54.003442   26956 round_trippers.go:324] Response Headers:
I0512 17:21:54.003452   26956 round_trippers.go:327]     Content-Type: application/json
I0512 17:21:54.003458   26956 round_trippers.go:327]     Date: Thu, 12 May 2016 15:21:54 GMT
I0512 17:21:54.003462   26956 round_trippers.go:327]     Content-Length: 131
I0512 17:21:54.003509   26956 request.go:882] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]}
I0512 17:21:54.003702   26956 round_trippers.go:296] GET http://127.0.0.1:8080/apis
I0512 17:21:54.003711   26956 round_trippers.go:303] Request Headers:
I0512 17:21:54.003715   26956 round_trippers.go:306]     User-Agent: kubectl/v1.3.0 (linux/amd64) kubernetes/644fa22
I0512 17:21:54.003720   26956 round_trippers.go:306]     Accept: application/json, */*
I0512 17:21:54.004052   26956 round_trippers.go:321] Response Status: 200 OK in 0 milliseconds
I0512 17:21:54.004062   26956 round_trippers.go:324] Response Headers:
I0512 17:21:54.004068   26956 round_trippers.go:327]     Date: Thu, 12 May 2016 15:21:54 GMT
I0512 17:21:54.004072   26956 round_trippers.go:327]     Content-Length: 1064
I0512 17:21:54.004077   26956 round_trippers.go:327]     Content-Type: application/json
I0512 17:21:54.004104   26956 request.go:882] Response Body: {"kind":"APIGroupList","groups":[{"name":"apps","versions":[{"groupVersion":"apps/v1alpha1","version":"v1alpha1"}],"preferredVersion":{"groupVersion":"apps/v1alpha1","version":"v1alpha1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]},{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]}]}
I0512 17:21:54.004624   26956 round_trippers.go:296] GET http://127.0.0.1:8080/api
I0512 17:21:54.004636   26956 round_trippers.go:303] Request Headers:
I0512 17:21:54.004643   26956 round_trippers.go:306]     Accept: application/json, */*
I0512 17:21:54.004650   26956 round_trippers.go:306]     User-Agent: kubectl/v1.3.0 (linux/amd64) kubernetes/644fa22
I0512 17:21:54.005021   26956 round_trippers.go:321] Response Status: 200 OK in 0 milliseconds
I0512 17:21:54.005031   26956 round_trippers.go:324] Response Headers:
I0512 17:21:54.005036   26956 round_trippers.go:327]     Content-Length: 131
I0512 17:21:54.005041   26956 round_trippers.go:327]     Content-Type: application/json
I0512 17:21:54.005049   26956 round_trippers.go:327]     Date: Thu, 12 May 2016 15:21:54 GMT
I0512 17:21:54.005074   26956 request.go:882] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]}
I0512 17:21:54.005210   26956 round_trippers.go:296] GET http://127.0.0.1:8080/apis
I0512 17:21:54.005221   26956 round_trippers.go:303] Request Headers:
I0512 17:21:54.005227   26956 round_trippers.go:306]     Accept: application/json, */*
I0512 17:21:54.005234   26956 round_trippers.go:306]     User-Agent: kubectl/v1.3.0 (linux/amd64) kubernetes/644fa22
I0512 17:21:54.005581   26956 round_trippers.go:321] Response Status: 200 OK in 0 milliseconds
I0512 17:21:54.005590   26956 round_trippers.go:324] Response Headers:
I0512 17:21:54.005595   26956 round_trippers.go:327]     Content-Type: application/json
I0512 17:21:54.005599   26956 round_trippers.go:327]     Date: Thu, 12 May 2016 15:21:54 GMT
I0512 17:21:54.005604   26956 round_trippers.go:327]     Content-Length: 1064
I0512 17:21:54.005638   26956 request.go:882] Response Body: {"kind":"APIGroupList","groups":[{"name":"apps","versions":[{"groupVersion":"apps/v1alpha1","version":"v1alpha1"}],"preferredVersion":{"groupVersion":"apps/v1alpha1","version":"v1alpha1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]},{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]}]}
I0512 17:21:54.005993   26956 round_trippers.go:296] GET http://127.0.0.1:8080/api
I0512 17:21:54.006004   26956 round_trippers.go:303] Request Headers:
I0512 17:21:54.006008   26956 round_trippers.go:306]     Accept: application/json, */*
I0512 17:21:54.006012   26956 round_trippers.go:306]     User-Agent: kubectl/v1.3.0 (linux/amd64) kubernetes/644fa22
I0512 17:21:54.006287   26956 round_trippers.go:321] Response Status: 200 OK in 0 milliseconds
I0512 17:21:54.006300   26956 round_trippers.go:324] Response Headers:
I0512 17:21:54.006305   26956 round_trippers.go:327]     Content-Type: application/json
I0512 17:21:54.006329   26956 round_trippers.go:327]     Date: Thu, 12 May 2016 15:21:54 GMT
I0512 17:21:54.006333   26956 round_trippers.go:327]     Content-Length: 131
I0512 17:21:54.006362   26956 request.go:882] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"127.0.0.1:443"}]}
I0512 17:21:54.006462   26956 round_trippers.go:296] GET http://127.0.0.1:8080/apis
I0512 17:21:54.006469   26956 round_trippers.go:303] Request Headers:
I0512 17:21:54.006473   26956 round_trippers.go:306]     Accept: application/json, */*
I0512 17:21:54.006477   26956 round_trippers.go:306]     User-Agent: kubectl/v1.3.0 (linux/amd64) kubernetes/644fa22
I0512 17:21:54.006787   26956 round_trippers.go:321] Response Status: 200 OK in 0 milliseconds
I0512 17:21:54.006796   26956 round_trippers.go:324] Response Headers:
I0512 17:21:54.006800   26956 round_trippers.go:327]     Content-Type: application/json
I0512 17:21:54.006804   26956 round_trippers.go:327]     Date: Thu, 12 May 2016 15:21:54 GMT
I0512 17:21:54.006808   26956 round_trippers.go:327]     Content-Length: 1064
```

**Comment by caesarxuchao** [comment]
I'll unassign myself so that people can pick it. Sorry for sitting on this for a long time..

**Comment by smarterclayton** [comment]
We squashed this recently.
