### ISSUE TITLE
MaxLimitRequestRange validation error in admission control

### ISSUE THREAD

**Issue by hurf** [kubernetes/kubernetes#13799]
We should use float number to calculate observed ratio. Division by integer will lose accuracy.

In https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/limitranger/admission.go#L252 , `observedValue` usually has a different unit with `enforcedValue`. They can't be compared.

**Comment by derekwaynecarr** [comment]
See https://github.com/kubernetes/kubernetes/pull/13680

**Comment by hurf** [comment]
Closing since it's fixed.
