### ISSUE TITLE
pod with glusterfs volume fails to be restarted after kubelet restart

### ISSUE THREAD

**Issue by Rio** [kubernetes/kubernetes#13797]
I've found that if there is a container running that use gluster as a volume mount type and you restart the kubelet it fails to come back up again. This is what I can tell caused by the kubelet mounting the volume using glusterfs and that program is also stopped on restart without cleanly unmounting which gives us errors like this:
```
kubelet.go:1503] Failed cleaning up orphaned pod directories: lstat /var/lib/kubelet/pods/8de73732-56e3-11e5-bdb1-52540072e8ed/volumes/kubernetes.io~glusterfs/static-storage: transport endpoint is not connected
kubelet.go:1793] Couldn't sync containers: lstat /var/lib/kubelet/pods/8de73732-56e3-11e5-bdb1-52540072e8ed/volumes/kubernetes.io~glusterfs/static-storage: transport endpoint is not connected
volumes.go:152] Could not read directory /var/lib/kubelet/pods/8de73732-56e3-11e5-bdb1-52540072e8ed/volumes/kubernetes.io~glusterfs: lstat /var/lib/kubelet/pods/8de73732-56e3-11e5-bdb1-52540072e8ed/volumes/kubernetes.io~glusterfs/static-storage: transport endpoint is not connected
kubelet.go:1503] Failed cleaning up orphaned pod directories: lstat /var/lib/kubelet/pods/8de73732-56e3-11e5-bdb1-52540072e8ed/volumes/kubernetes.io~glusterfs/static-storage: transport endpoint is not connected
kubelet.go:1793] Couldn't sync containers: lstat /var/lib/kubelet/pods/8de73732-56e3-11e5-bdb1-52540072e8ed/volumes/kubernetes.io~glusterfs/static-storage: transport endpoint is not connected
```
Only by manually stopping the pod and unmounting the volume will kubelet clean the volume.

**Comment by Rio** [comment]
version: Kubernetes v1.1.0-alpha.0.1588+e44c8e6661c931

**Comment by pmorie** [comment]
@kubernetes/rh-storage

**Comment by rootfs** [comment]
Something happened to glusterfs fuse mount. 
@Rio  What is your glusterfs version? Is your gluster daemon running on the same host as kubelet? Do you run any flannel or similar? Can you share your glusterfs log located at /var/log/glusterfs ?

**Comment by Rio** [comment]
@rootfs, sorry for some reason logs were lost. I've been trying to recreate the situation on a test node for a while now but I can't manage it. Just to give you a picture we have a 4 node replicated distributed gluster setup with client versions ```3.6.4-1.fc22``` on the kubernetes nodes running fedora server 22.

We're migrating from our old nfs storage to the nodes so usage should increase and maybe it'll happen again. Our kubernetes nodes are quite volatile, we tend to update them often and sometimes just remove them and rebuild them completely.

You can close this issue if you'd like.

**Comment by rootfs** [comment]
@Rio thanks, looking forward to your update. 
i cannot close it, only you can :)
