### ISSUE TITLE
Docker issue: problems with V2 registry

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#13804]
This is not technically a k8s issue, but I think because we ship a fixed version of Docker we will hit it.  When using a V2 registry, I observed disk space filling up very fast with GetV2ImageBlob files in /var/lib/docker/tmp, I believe due to https://github.com/docker/docker/issues/14506

The pods in question fail to launch with an error message like "image not found" - I thought I had typod the name of the image.

I think this only happens when using a V2 registry, when pushing with a newer version of Docker: pushing with Docker 1.5 does not seem to cause a problem, pushing with Docker 1.7 seems to mean that the docker pull will fail.  I think this is because 1.5 is actually not using the V2 registry API (?).

I am not sure if this is known or if there is a known workaround, but I expect other users are likely to hit it and we'll have to figure it out.

**Comment by yujuhong** [comment]
@justinsb, is the "image not found" error from docker or kubelet? It'd be good to have some clarity if user reports.

/cc @kubernetes/goog-node

**Comment by justinsb** [comment]
I actually haven't been able to reproduce this, despite pushing from different docker versions, so I haven't been able to confirm the message.  I was also encountering some disk full errors, so perhaps these were actually the root cause.  If I do reproduce this I will reopen (and get the exact error messages as logged by both docker, kubelet & events).  I will close, but it will remain searchable.  Sorry for the noise!
