### ISSUE TITLE
Regression: kubectl logs --follow is broken

### ISSUE THREAD

**Issue by stefwalter** [kubernetes/kubernetes#13811]
This command is broken on git master:

```
kubectl logs --follow <pod>
```

It just hangs forever rather than producing any output. It used to work in kubernetes 1.0

**Comment by stefwalter** [comment]
Reproduce like so:

```
$ wget -O test.json 'https://bugzilla.redhat.com/attachment.cgi?id=1072268'
$ kubectl create -f test.json
$ kubectl get pods # get name and wait until running
$ kubectl logs --follow mock-ffctj
^C
```

The above just hangs. It should instead produce output:

```
$ kubectl logs --follow mock-tpo3j
HelloMessage.
HelloMessage.
HelloMessage.
HelloMessage.
HelloMessage.
HelloMessage.
HelloMessage.
HelloMessage.
...
```

```docker logs --follow``` on the same machine works:

```
[root@falcon kubernetes]# docker logs --follow 248896a80890
HelloMessage.
HelloMessage.
HelloMessage.
HelloMessage.
HelloMessage.
...
```

**Comment by stefwalter** [comment]
@eparis @ingvagabund @liggitt CC

**Comment by roberthbailey** [comment]
@jlowdermilk CC as well

**Comment by roberthbailey** [comment]
It sounds like we don't have any regression tests for this feature; we should add one as we fix it.

**Comment by stefwalter** [comment]
The Cockpit integration tests caught this bug. So yes, testing upstream would be great.

**Comment by mikedanese** [comment]
@kubernetes/kubectl

**Comment by smarterclayton** [comment]
Do we know what the problem is?

**Comment by liggitt** [comment]
Did https://github.com/kubernetes/kubernetes/issues/13864 not resolve it?

**Comment by feiskyer** [comment]
#13864 has fixed `kubectl logs --follow` broken problem.

**Comment by liggitt** [comment]
@stefwalter closing as fixed in master
