### ISSUE TITLE
flaky/broken e2e: Services should be able to change the type and nodeport settings of a service

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#13818]
Test is failing pretty regularly at the same [point](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/service.go#L608); after updating service nodeport, it expects the loadbalancer ingress to be the same as before, but this is not the case:
```
• Failure [262.469 seconds]
Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:967
  should be able to change the type and nodeport settings of a service [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:650

  Expected
      <api.LoadBalancerIngress>: {IP: "104.154.44.93", Hostname: ""}
  to equal
      <api.LoadBalancerIngress>: {IP: "104.197.22.89", Hostname: ""}

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:608
```
Not familiar with loadbalancer creation code, so not sure whether test or service controller is broken. If we expect the loadbalancer ingress ip to be the same after updating the nodeport, this would indicate a bug in the service controller.

cc @justinsb @ArtfulCoder

**Comment by ixdy** [comment]
This test is no longer flaky; it's failing 100% on `kubernetes-e2e-gce-flaky`:

```
• Failure [1215.675 seconds]
Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:861
  should be able to change the type and nodeport settings of a service [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:584

  Expected error:
      <*errors.errorString | 0xc20836ede0>: {
          s: "service mutability-service-test in namespace e2e-tests-services-kylfa doesn't have a LoadBalancer ingress point after 1200.00 seconds",
      }
      service mutability-service-test in namespace e2e-tests-services-kylfa doesn't have a LoadBalancer ingress point after 1200.00 seconds
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:478
```

**Comment by thockin** [comment]
@ixdy #15854 - I have a half dozen passes on it - what am I doing differently from you?

**Comment by ixdy** [comment]
@thockin http://goto.google.com/k8s-test/job/kubernetes-e2e-gce-flaky/lastCompletedBuild/testReport/(root)/Kubernetes%20e2e%20suite/Services_should_be_able_to_change_the_type_and_nodeport_settings_of_a_service/ says "Failing for the past 324 builds (Since [build #]5766)"

**Comment by ixdy** [comment]
oh, I think we exhausted our quota of forwarding rules and static IP addresses in the project this build is using. some tests are still leaking...

**Comment by ixdy** [comment]
OK, this started working again when I cleaned up the resources. Never mind.

**Comment by thockin** [comment]
Great cuz I want to move all Services tests off the flaky list :)

**Comment by lavalamp** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9595/

**Comment by thockin** [comment]
@bprashanth have time to help on a flaky test?

**Comment by wojtek-t** [comment]
friendly ping - can someone look into it?

**Comment by lavalamp** [comment]
@ArtfulCoder this is assigned to you and is P0-- can you find an owner if you're not working on it?

**Comment by thockin** [comment]
Flaky trumps almost everything.  PTAL

**Comment by ArtfulCoder** [comment]
https://status.cloud.google.com/incident/compute/15065
Hard to investigate with the ongoing GCE L3 issue.

what I found so far:
The flakiness occurs because we are unable to create a L3 LB using ephemeral IP.
We can increase the timeout, and ensure that L3 LBs can deleted when the namespace is deleted.

But, beyond that, there is not much we can do here. GCE LB service needs to improve for ephemeral IPs

I am not sure what the quota is for ephemeral IPs (I am guessing it is a high number)

1. This flaky test uses ephemeral IP: should be able to change the type and nodeport settings of a service [It]

2. Another test in the same suite that uses static IP, "should serve identically named services in different namespaces on different load-balancers" does not seem to be flaky.

**Comment by wojtek-t** [comment]
There is another failure that just happened:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9893/

@thockin - FYI

**Comment by wojtek-t** [comment]
And one more:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9823/

Can someone please take a look?

**Comment by thockin** [comment]
PR #18532 is another shot at this.

**Comment by wojtek-t** [comment]
I've manually merged #18532 - we will see if that helps... (thanks @thockin !)

**Comment by thockin** [comment]
any news on this?

**Comment by wojtek-t** [comment]
I haven't seen such failures over the weekend.
I'm closing this for now - will reopen if we observe this again.

Thanks @thockin !
