### ISSUE TITLE
Regression: kubectl create with List no longer works

### ISSUE THREAD

**Issue by stefwalter** [kubernetes/kubernetes#13812]
Using kubectl create with a list no longer works. We get the output:

```
$ _output/local/bin/linux/amd64/kubectl create -f /tmp/test.json
error validating "/tmp/test.json": error validating data: couldn't find type: v1.List; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by stefwalter** [comment]
In kubernetes 1.0 ```kubectl create -f ``` with a List would create all items in the List.

```
[root@falcon kubernetes]# _output/local/bin/linux/amd64/kubectl create -f test.json
replicationcontroller "mock" created
service "mock" created
```

**Comment by stefwalter** [comment]
Test data to duplicate the problem: https://bugzilla.redhat.com/attachment.cgi?id=1071695

**Comment by stefwalter** [comment]
@eparis @ingvagabund @liggit CC

**Comment by stefwalter** [comment]
@sub-mod FYI in case you run into this.

**Comment by roberthbailey** [comment]
@jlowdermilk 

Another feature that needs a test.

**Comment by liggitt** [comment]
the swagger spec may only include object definitions that are registered as API request/response types... since `v1.List` isn't actually submitted to the server (that I know of), that's probably why it didn't get included. Enabling validation by default (https://github.com/kubernetes/kubernetes/pull/12837) probably exposed the bug with a List not being able to validate

**Comment by mikedanese** [comment]
@kubernetes/kubectl

**Comment by bgrant0607** [comment]
We need to make validation on List work. We should test multiple resources w/o List as well.

**Comment by pmorie** [comment]
@kubernetes/rh-ux

**Comment by bgrant0607** [comment]
Naive question: Could we just call Schema() after Flatten() but before Do()?

**Comment by bgrant0607** [comment]
Hmm. No, validation isn't actually called there.

**Comment by bgrant0607** [comment]
Each input-source visitor (URLVisitor, FileVisitor, StreamVisitor) has its own call to ValidateSchema.

We need to validate before decoding, but we don't unpack the list until after decoding.

**Comment by bgrant0607** [comment]
We could do something similar to FlattenListVisitor in ValidateSchema:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/visitor.go#L338
https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/helper.go#L62

But that's pretty ugly.

**Comment by bgrant0607** [comment]
@jlowdermilk Do you have time to take a look at what the most straightforward solution/workaround is for this?

Longer-term we should maybe push this into the json decoder, as proposed here: https://github.com/kubernetes/kubernetes/issues/13806#issuecomment-139306570

**Comment by liggitt** [comment]
The simplest thing might be to add List to the swaggerapi models list… I was looking into that yesterday and got sidetracked

**Comment by bgrant0607** [comment]
@liggitt I thought about adding List, but it didn't look like the validator would recurse into the individual resource models, hence the need to special-case List.

**Comment by bgrant0607** [comment]
@linzichang Nobody is working on this at the moment, if you'd like to take a look.

**Comment by linzichang** [comment]
@bgrant0607 OK, I will take a look.

**Comment by linzichang** [comment]
@bgrant0607 @liggitt If add List to the swaggerapi, it need to add a new api v1.List. I think it might be a little strange. Please correct me.

**Comment by bgrant0607** [comment]
I recommended not adding List to the swagger. I don't think it would help. I think we need to detect the case of a List and extract the resources within, similar to FlattenListVisitor.

**Comment by linzichang** [comment]
@bgrant0607 I agree.  I think doing something similar to FlattenListVisitor in ValidateSchema maybe a little ugly. But it's straightforward.
