### ISSUE TITLE
Clear Pod Spec in Strategy not Validation?

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#13814]
In pkg/api/validation/validation.go in function ValidatePodUpdate, it says: 

```
        newPod.Status = oldPod.Status
```

But this is also done in pkg/registry/pod/rest.go in function PrepareForUpdate.

I would not expect a Validate routine to modify it's input.  Probably a holdover from before we added strategy.  Should be safe to delete, but needs more thought/testing than I could give at this moment.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important (we may have fixed this).
