### ISSUE TITLE
Kubectl flag for specifying custom user-agent

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#13829]
The kube-addon-update.sh script that runs on the master periodically uses kubectl to talk to the apiserver. This is fine, but muddies up the kube-apiserver logs with requests from kubectl that aren't actually user-initiated. It's not a big deal, but would be nice if they had a more appropriate user-agent string.

**Comment by a-robinson** [comment]
@jlowdermilk @goltermann

**Comment by mikedanese** [comment]
@kubernetes/kubectl

**Comment by smarterclayton** [comment]
This is one place where an env var would make sense

**Comment by dims** [comment]
agree with @smarterclayton env var is great for this use case. sent a PR

**Comment by erictune** [comment]
Are we moving from apiserver logs to audit logs?  https://github.com/kubernetes/kubernetes/pull/27087

I don't recall those having a user agent.

A separate account for the addon controller, or a "reason" field in the audit log are alternatives to user-agent.
