### ISSUE TITLE
Multiple e2e tests fail with "Namespace x is active"

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#13828]
Our CI "soak" testing runs e2e tests repeatedly against a cluster.  After a few runs we start seeing lots of the following sort of thing:

```
**SchedulerPredicates validates resource limits of pods that are allowed to run.**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:162
Expected error:
    <*errors.errorString | 0xc2082bd290>: {
        s: "Namespace e2e-tests-container-probe-jdj8w is active",
    }


    ** Namespace e2e-tests-container-probe-jdj8w is active **  
not to have occurred


**SchedulerPredicates validates that NodeSelector is respected.**


/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:162
Expected error:
    <*errors.errorString | 0xc208b92480>: {
        s: "Namespace e2e-tests-container-probe-jdj8w is active",
    }

    ** Namespace e2e-tests-container-probe-jdj8w is active **
not to have occurred

** SchedulerPredicates validates MaxPods limit number of pods that are allowed to run. **

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:162
Expected error:
    <*errors.errorString | 0xc208567be0>: {
        s: "Namespace e2e-tests-container-probe-jdj8w is active",
    }

    ** Namespace e2e-tests-container-probe-jdj8w is active **
not to have occurred


** Nodes Resize should be able to delete nodes ** 

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:410
Sep 10 11:02:28.129: ** Couldn't delete testing namespaces 'e2e-tests-resize-nodes-w8oer', Namespace e2e-tests-container-probe-jdj8w is active **


** Nodes Resize should be able to add nodes **
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:410
Sep 10 11:35:56.521: **Couldn't delete testing namespaces 'e2e-tests-resize-nodes-48944', Namespace e2e-tests-container-probe-jdj8w is active **
```

This appears to be related to:
#10175 ( @wojtek-t )
and/or #12408 ( @smarterclayton  )

@derekwaynecarr any suggestions?  These and other related namespace deletion problems seem to be plaguing e2e reliability.  Any help much appreciated.

**Comment by derekwaynecarr** [comment]
This went in recently, but its not clear to me why that would have caused the bug either:
https://github.com/kubernetes/kubernetes/pull/13553

**Comment by quinton-hoole** [comment]
@derekwaynecarr Thanks but our soak test cluster was built before #13553 merged, so that can't be the cause.  I'll dig out some stats as to when the errors started to occur. 1 minute please... :-)

**Comment by quinton-hoole** [comment]
I can trace the problem back to at least Sep 3, 2015 3:41:03 PM. That's as far back as our history on our soak test cluster extends. The problem probably predates that substantially.

**Comment by quinton-hoole** [comment]
@derekwaynecarr I would imagine that this would be pretty simple to reproduce on a local test cluster. Just build one, and run the e2e suite against it a few times. What we're seeing is typically two successful e2e runs, followed by consistent failures of the above tests for the reasons stated.

**Comment by derekwaynecarr** [comment]
@smarterclayton - could it be related to graceful pod delete?

@quinton-hoole <https://github.com/quinton-hoole> - is it possible to dump
the contents of the namespace and the namespace itself when this is
encountered?  Would help us understand if anything is in process of being
deleted.  Also wondering if it's a stale etcd catch result.

**Comment by smarterclayton** [comment]
We definitely had the races that were fixed (where pods can be deleted
after the node becomes healthy).  However, it's possible there is a similar
race during namespace deletion, where we requeue the deletion for the next
interval but the namespace is deleted and recreated.  Are we reusing
namespace names during soaking?

E2e has a helper for dumping all pods across all namespaces and their
termination state, that may be reusable.

On Sep 10, 2015, at 7:14 PM, Derek Carr <notifications@github.com> wrote:

@smarterclayton - could it be related to graceful pod delete?

@quinton-hoole <https://github.com/quinton-hoole> - is it possible to dump
the contents of the namespace and the namespace itself when this is
encountered? Would help us understand if anything is in process of being
deleted. Also wondering if it's a stale etcd catch result.

On Thursday, September 10, 2015, Quinton Hoole <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> @derekwaynecarr <https://github.com/derekwaynecarr> I would imagine that
> this would be pretty simple to reproduce on a local test cluster. Just
> build one, and run the e2e suite against it a few times. What we're seeing
> is typically two successful e2e runs, followed by consistent failures of
> the above tests for the reasons stated.
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/issues/13828#issuecomment-139385681
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/13828#issuecomment-139408656>
.

**Comment by quinton-hoole** [comment]
@derekwaynecarr sure, you should be able to add some logging around 
test/e2e/scheduler_predicates.go:162

Q

**Comment by timothysc** [comment]
imho a part of this is an issue inside of the tests as well.  

There are checks on deleting namespaces, which we've found to be full of #fail on large clusters such that we segregate the tests, and do explicit deletes.  

Part of this issue goes waaaay back.

**Comment by jayunit100** [comment]
Is the staleness caused after several namespaces are deleted/created, sounds like it.  

- like Clayton said; are these namespaces being reused? That's a possible cause I might guess.
- One test which can be done : have the soak cluster run the namespace soak several times before it starts, does that reproduce it?
 - if not, does simply running density several times reproduce it? 

The answer to those questions will answer if it's just namespaces, or pods in namespaces, which are causing the slow deletion.

Finally this is one reason that I some time stamps info encoded in random namespace names could really be useful.

**Comment by wojtek-t** [comment]
@quinton-hoole - regarding #10175 - this changed only scalability tests (which are not runing in soak tests). Also, I didn't touch e.g. predicates tests so this is unrelated.

**Comment by derekwaynecarr** [comment]
I am investigating this more today, I think we have may have some issues dealing with stale resources in the namespace_controller that I am debugging today to see if its the cause.

**Comment by derekwaynecarr** [comment]
See related discussion: https://github.com/openshift/origin/issues/4731

**Comment by derekwaynecarr** [comment]
@quinton-hoole - can you confirm that you see this error when not running concurrent tests?  The tests in question all make use of https://github.com/kubernetes/kubernetes/blob/master/test/e2e/util.go#L495 so its inherent in that environment that their will be active namespaces.

**Comment by quinton-hoole** [comment]
@derekwaynecarr Our soak test cluster (the one originally reported above) runs tests in serial, not parallel.

**Comment by derekwaynecarr** [comment]
@quinton-hoole - i think the tests in question have a bug.  they call ```deleteTestingNs``` but you can see that that method never actually does a delete.  What is the expected behavior?  I see other tests that call ```deleteNs``` then ```deleteTestingNs``` in the AfterEach clause which makes more sense.  Should ```deleteTestingNs``` actually update to try and delete?

I am in the process of making ```namespace_controller``` more fault tolerant, but want to make sure I understand the expected behavior for ```deleteTestingNs```

**Comment by quinton-hoole** [comment]
@derekwaynecarr you may well be right.  Fortunately https://github.com/kubernetes/kubernetes/pull/14055#discussion_r39684912  
should merge today to sort out the naming abomination upon which we all seem to agree.
But it still seems completely wrong that it checks that all testing namespaces are deleted, rather than the namespace specific to the current test.

@gmarek want to take a hack at fixing that?

**Comment by quinton-hoole** [comment]
Actually @gmarek has just headed out.  I'll try to do this today.

**Comment by quinton-hoole** [comment]
Oh, I see that github munged my link above.  To be clear, this is what I was referring to:

quinton-hoole added a note 5 days ago
I really really really don't like this function, for the following reasons:

1. It's called deleteTestingNS, but it doesn't actually delete anything. All it does is do some checks.
2. It takes a namespace as a parameter, and given the name of the function, callers could reasonably expect that to be the namespace upon which it operates, but it's in fact the opposite of that.

Could you not rename it to something like checkTestingNSDeletedExcept(). I know it's slightly verbose, but at least it's true :-)

**Comment by derekwaynecarr** [comment]
@quinton-hoole - thanks for the update, in the interim, i am also trying to make improvements to namespace controller to better handle resource conflicts, so between the 2 efforts we should knock this out.

**Comment by fgrzadkowski** [comment]
I was just debugging #14695 and one of the failures was:
```
Sep 29 18:00:37.181: Couldn't delete testing namespaces 'e2e-tests-resize-nodes-yd40e', Namespace e2e-tests-daemonsets-fecw4 is active
```
The test that created namespace ```e2e-tests-daemonsets-fecw4``` failed in ```BeforeEach``` step. AFAIU this means that ```AfterEach``` is never deleted. If that's the case namespace is not deleted. Is it possible that we see the same problem in other cases?

**Comment by timothysc** [comment]
@fgrzadkowski yes.

**Comment by quinton-hoole** [comment]
I've searched through the CI logs, and haven't seen this occur as far back as our logs go (only Nov 17, unfortunately). Closing for now, and will re-open if we see it again.
