### ISSUE TITLE
AWS coreos util file unbound variable

### ISSUE THREAD

**Issue by nhumrich** [kubernetes/kubernetes#13839]
```
$ pwd
~/kubernetes/cluster
$ export KUBERNETES_PROVIDER=aws
$ export KUBE_OS_DISTRIBUTION=coreos
$ ./kube-up.sh
```

... stuff going good ...
then:

```
Attempt 9 to check for salt-master [salt-master not working yet]
Attempt 10 to check for salt-master [salt-master running]
Creating minion configuration
./../cluster/aws/../../cluster/../cluster/aws/coreos/util.sh: line 32: $1: unbound variable
```

Note sure what this script is expecting. `aws/util.sh` calls `aws/coreos/util.sh` directly without passing in variables. But it looks like the `coreos/util.sh` file is looking for some type of ip?

```
function generate-minion-user-data() {
  i=$1
  # TODO(bakins): Is this actually used?
  MINION_PRIVATE_IP=$INTERNAL_IP_BASE.1${i}
```

**Comment by mikedanese** [comment]
cc @bakins

**Comment by bakins** [comment]
Looks like this changed in https://github.com/kubernetes/kubernetes/commit/2a5ed2f0869f2bb7e2939cfc897f295983176032 

I think just removing lines 32-34 in coreos/util.sh would fix.

**Comment by nhumrich** [comment]
removing line 32-34 as well as line 47 fixed the issue. It looks like `MINION_IP` isnt even being used in the node.yaml file.

**Comment by justinsb** [comment]
We're not going to making further changes in kube-up.  Solutions for CoreOS are kube-aws, kubeadm, and likely kops soon (see https://github.com/kubernetes/kops/pull/854).  Closing.
