### ISSUE TITLE
Request for feature:  provide mechanism for one of many containers to cause a pod to exit

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/kubernetes#13847]
I was encouraged to file an issue here based on a Slack exchange with @mikedanese.

I have a pod with, say, two containers.  The first pod is my "app".  The second container exists to support the first.  When the first pod exits normally or not normally, I would like the remaining support containers to be terminated, which leaves the pod ready for GC.

As it stands, I'll have to monitor the pod for signs my app has exited, and kill the pod via the API.

It would be nice to have a supported pod spec parameter whereby when one 'sentinel' container exits, the other containers are taken down with no further cleanup from the user required.

Thoughts?

Thanks.

**Comment by mikedanese** [comment]
@kubernetes/goog-control-plane

**Comment by resouer** [comment]
+1 for this. But I propose to set certain containers as `sentinel` instead of one, they will decide the state of the Pod together following [state doc](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/pod-states.md); 

and for the `non-sentinel` containers, they doesn't matter at all.

@mikedanese @ae6rt What do you guys think? I can make a PR for this

**Comment by ae6rt** [comment]
Having more than one sentinel is fine with me.

**Comment by ae6rt** [comment]
That being said, my use case is not so much having sentinels vote on whether the pod should be destroyed, but more like if a container(s) exits, then destroy the pod.  There is a difference.  In the former case, containers have to be responsive.  In the latter, they do not.

**Comment by gmarek** [comment]
cc @dchen1107 @yujuhong

**Comment by fgrzadkowski** [comment]
@ae6rt If k8s restarts your app container, can it continue to run? Why do you need to recreate the whole pod?

**Comment by ae6rt** [comment]
@fgrzadkowski I have intentionally set restart policy to 'never', so while in theory the exited container could be restarted, I don't want that to happen.

These pods in my use case are created to execute a one-time task.  My "app", as I use the term in my opening comment, is the task-runner.  The other containers in the pod assist the task while the task is running.  When the task is finished, I need to destroy the pod.  I know I can DELETE the pod programmatically.  I was asking for this feature to free me of such a manual deletion.

**Comment by fgrzadkowski** [comment]
@ae6rt Would it work if you "companion container" watches the main one and dies if it fails health check? I know it wouldn't be too clean, but I think it'd serve the purpose.

**Comment by gmarek** [comment]
We do something like @ae6rt asks for for POD infra containers. I think it shouldn't be too much work to generalize it slightly, if we decide to (and agree on API)

**Comment by ae6rt** [comment]
@fabianofranz I'm pretty easy to please on this, and defer to you and your architects on how to implement this, knowing that perfection is the enemy of good enough.

My only concern is that my "app" container not be asked complicated health questions.  I'd rather it not be expected to be that smart.  In my case, the "app" container entrypoint is a shell script that does some important (of course) stuff.  When the stuff is done, I desired the entire pod that encloses it be destroyed.  

If this app container has to be made smarter, to me that means it needs to respond to health checks that make the script, or whatever runnable command obtains, more complicated - perhaps the script has to spin up an http server to service the health check.  That sounds brittle to me, and well beyond the scope of what I want that container capable doing.  I hope this makes sense.  Maybe I'm missing something - some super easy health check such a dumb container can implement that you can wire into for destroy-pod purposes.  But I think "if app container has exited" should be at least one flavor of health check.

**Comment by mikedanese** [comment]
This is pretty much GoogleCloudPlatform/container-agent#9

**Comment by mikedanese** [comment]
We should consider in the context of batch tasks as well as service tasks. @erictune

**Comment by ae6rt** [comment]
I want to make another observation, one not made yet, but surely I'm not the only one to think it:  the destroy-pod instruction should probably come from outside the pod based on an observable of some sort.  Contrast this with my adding an (N+1)^th container to monitor whether my "app" container has exited, then have that monitoring-container destroy its very own pod.  Having a pod destroyed by one of its containers seems like a bad idea to me - race conditions, how can I be sure the pod is really gone if I'm gone, too, etc.

**Comment by brendandburns** [comment]
This seems reasonable, and seems like a restart policy of `TerminateOnFailure` or `TerminateOnExit`

Though of course, in this concrete case, this is achievable right now with a `RestartNever` and health checks for the support pods.

The first pod exits, doesn't get restarted, the health checks fail for the other support pods, the kubelet kills them, and then since restart policy is restart never, they don't get restarted.

**Comment by ae6rt** [comment]
@brendandburns The second sentence seems to say that if my support pods can return not-healthy, then the pod can be torn down.  And not-healthy in my use case means the "app" container has exited.  But I don't want these support pods to have to know the "app" container even exists.  My use case support pods are things like stock mysql, or stock redis.  They are unaware the app has exited, and don't and shouldn't care that it has.

**Comment by brendandburns** [comment]
the health checks are kubernetes Pod concepts, not app level concepts, so your support containers know nothing about them.

**Comment by cristicbz** [comment]
Our use-case here is two containers C1 and C2. C1 computes a long-running expensive computation in a loop saving the results in a volume and C2 serves those results as an HTTP server.

When C1 finishes the computation the first time (thus ensuring the data on the volume is up to date enough), it notifies C2 that it can start serving (i.e. start responding with OK to its readiness probe).

If C2 is restarted without also restarting C1, the new instance of C2 never gets notified and therefore never starts responding with OK to its readiness probe.
