### ISSUE TITLE
SessionAffinity not working

### ISSUE THREAD

**Issue by jonbaierCTP** [kubernetes/kubernetes#13865]
I have an issue with SessionAffinity set to ClientIP. If I do multiple refreshes in a browser (using the service LB IP), I eventually get a different pod. It takes 10 or so refreshes, but switches and then usually switches again in the next one or two refreshes. Checked both the service description and the GCE console and affinity is set to Client IP.

Here is the service YAML:
apiVersion: v1
kind: Service
metadata:
  name: node-js-scale-ab
  labels:
    service: node-js-scale-ab
spec:
  type: LoadBalancer
  ports:
  - port: 80
  sessionAffinity: ClientIP
  selector:
    service: node-js-scale-ab

and the first controller:
apiVersion: v1
kind: ReplicationController
metadata:
  name: node-js-scale-a
  labels:
    name: node-js-scale-a
    version: "0.2"
    service: node-js-scale-ab
spec:
  replicas: 2
  selector:
    name: node-js-scale-a
    version: "0.2"
    service: node-js-scale-ab
  template:
    metadata:
      labels:
        name: node-js-scale-a
        version: "0.2"
        service: node-js-scale-ab
    spec:
      containers:
      - name: node-js-scale
        image: jonbaier/pod-scaling:0.2
        ports:
        - containerPort: 80
        livenessProbe:
          # An HTTP health check 
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5

Second Controller:
apiVersion: v1
kind: ReplicationController
metadata:
  name: node-js-scale-b
  labels:
    name: node-js-scale-b
    version: "0.3"
    service: node-js-scale-ab
spec:
  replicas: 2
  selector:
    name: node-js-scale-b
    version: "0.3"
    service: node-js-scale-ab
  template:
    metadata:
      labels:
        name: node-js-scale-b
        version: "0.3"
        service: node-js-scale-ab
    spec:
      containers:
      - name: node-js-scale
        image: jonbaier/pod-scaling:0.3
        ports:
        - containerPort: 80
        livenessProbe:
          # An HTTP health check 
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5

**Comment by thockin** [comment]
I can not repro this.  can you try these steps to boil it down:


kubectl run hostnames --image=gcr.io/google_containers/serve_hostname
--replicas=4

kubectl expose rc hostnames --port 80 --target-port 9376
--type=LoadBalancer --session-affinity=ClientIP

#get the service IP:
get svc hostnames -o template --template '{{.spec.clusterIP}}{{"\n"}}'

#ssh to a node
for i in `seq 1 100`; do curl -s $SVCIP; done | sort | uniq -c
#expect 1 line with 100 hits

#get the LB IP:
get svc hostnames -o template --template '{{(index
.status.loadBalancer.ingress 0).ip}}{{"\n"}}'

#from outside the cluster
for i in `seq 1 100`; do curl -s $LBIP; done | sort | uniq -c
#expect 1 line with 100 hits

**Comment by jonbaierCTP** [comment]
I'm getting an error on the session-affinity flag.

unknown flag: --session-affinity

This is the command I used:

kubectl expose rc hostnames --port=80 --target-port=9376 --type=LoadBalancer --session-affinity=ClientIP

**Comment by thockin** [comment]
Maybe that was added after 1.0.  Try without it, and then run

kubectl get svc hostnames -o yaml | sed 's/Affinity: None/Affinity:
ClientIP/' | kubectl replace -f -

I am on mobile, so hopefully that is right

**Comment by jonbaierCTP** [comment]
Sorry for leaving this open, it's been an intense 2 weeks for my day job.

I tried your example and also went back to my app and I am successfully get affinity working. I did upgrade and redeploy my cluster, so I'm guessing maybe it was an old bug?? In any case, it's working great now. Thanks so much for helping me troubleshoot!
