### ISSUE TITLE
unexpected pod killing & creating w/ `--hostname-override` reconfigure for kubelet

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#13860]
#### How to reproduce
- Start a cluster via docker (all components containerized). Use `--hostname-override=10.10.102.36` as the param for kubelet. 
- Create a pod name busybox. Hence we have 2 pods for now ( `k8s-master-10.10.102.36` and `busybox`). 
- Kill the docker container of kubelet via `docker rm`, while other master components stay as they were. Confirm the pod info w/ `kubectl get pods`. Both pods are ok. Also `kubectl get nodes`, `10.10.102.36` was labeled as a *Ready* node.
- Restart a docker container for kubelet with param `--hostname-override=10.10.102.28`. Then we have
(1) pod `busybox` was killed immediately, including the busybox container and infra container, which could be traced by kubelet log ("Killing unwanted pod..."). 
(2) pod `k8s-master-10.10.102.36` just vanished nowhere (no trace log), yet the included containers remain as they were. 
(3) pod `k8s-master-10.10.102.28` was created, yet never make it to a *running* status. (No events also) 
(4) Could create a pod (like busybox, whatever) successfully. (5) Confirm node info, `10.10.102.36` as a *NotReady* node and `10.10.102.28` as a *Ready* one. 

#### My concerns
- What turns busybox to an unwanted pod and killed by kubelet?
- How does `k8s-master-10.10.102.36` pod vanish without being deleted explicitly? It should be a mirror pod in this case.
- Seems odd for pod `k8s-master-10.10.102.28` as well.

#### ENV
k8s: v1.1.0-alpha
platform: ubuntu 14.04
docker: 1.7.1

**Comment by lvlv** [comment]
I think this is expected, the value specified by hostname-override is the
identity of a node, two nodes with different identities should never share
the same docker daemon.

**Comment by dalanlan** [comment]
Considering it's kinda an improper configuration, we should be responsible for what we got, is that what  you referred to?  
/cc @lvlv

**Comment by lvlv** [comment]
In currently implementation, yes. What's your expectation for this configuration? If you want to change this behavior, may I know more about your use case?

**Comment by dalanlan** [comment]
I just found it interesting, and that's all.
