### ISSUE TITLE
User reports problem deleting and re-creating Pod with GCE PD mounted

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#13871]
Not sure if this is a support issue or a bug.

http://stackoverflow.com/questions/32528039/gce-persistent-disk-kubernetes-and-data-persistence/32530650#32530650

User mounted a GCE PD in a Pod that is controlled by a one-Pod RC, wrote some data, scaled the RC down to 0, then scaled it back up to 1. 

(1) user says the data has disappeared from GCE PD when the pod is re-created at scale-up time
(2) user says that when scaling up it "hangs on the command line and loops forever when I view the kublet's logs"

**Comment by davidopp** [comment]
@saad-ali any thoughts on this, or someone else to consult?

**Comment by davidopp** [comment]
(2) is filed as a separate issue, #13869, so this is just about (1)

**Comment by saad-ali** [comment]
Regarding #1, that shouldn't happen. What Kubernetes version was he using?

Changing an RC from 1 to 0 back to 1, should behave the same as deleting a pod with a GCE PD volume and recreate it (meaning the data should remain intact). We had a few bugs around this with v1.0 but these were fixed as of v1.03 (see #11561).

If he's still having issues as of v1.03, then I'd like to see if I can get a repro.

**Comment by brendandburns** [comment]
Long ago we had a bug like this, where we failed the unmount, and then we blindly `rm`'d the directory.  That bug was fixed, but it's possible there's a different codepath with similar behavior.

**Comment by trenton42** [comment]
I'm not sure if anything has happened with this, but I experienced the same issue today on version 1.4.5.

I created a simple setup with a single pod RC that has a gcePersistentDisk mounted. Deleting the pod or changing the RC to 0 then back to 1 causes all of the data in the persistent disk to be deleted.

**Comment by msau42** [comment]
This bug is quite old, and we haven't heard any recent reports of this.  Please open a new issue if you still see the problem.
/assign

**Comment by trenton42** [comment]
@msau42 We haven't experienced this again since my comment above. My suspicion is that it was something to do with our configuration and not a bug in k8s.
