### ISSUE TITLE
Support Hawkular in Initial Resources

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#13873]
To integrate Initial Resources with Hawkular metrics backend we have to provide Hawkular specific implementation of dataSource interface. More details in [data_source.go](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/initialresources/data_source.go).

part of #13589

**Comment by piosz** [comment]
@derekwaynecarr @smarterclayton could you assign the issue to appropriate person? I'm happy to help with it.

**Comment by smarterclayton** [comment]
@mwringe

**Comment by mwringe** [comment]
Is this a task that Hawkular needs to work on ourselves? Or is this something in which we just need to collaborate with someone to make sure they can get the right values out of Hawkular?

**Comment by piosz** [comment]
@mwringe I'm not familiar with Hawkular at all so I'd prefer you to do it, however I'm happy to help you.

**Comment by mwringe** [comment]
Ok

**Comment by piosz** [comment]
Any progress? On Monday we should be feature complete for 1.1.

**Comment by mwringe** [comment]
I have not had any time to even look at this yet

**Comment by piosz** [comment]
cc @burmanm

**Comment by burmanm** [comment]
For progress report, I'm waiting for HWKMETRICS-263 / HWKMETRICS-264 to be merged on Hawkular-Metrics side to send a PR (as they reduce the IR resource requirements a lot on Kubernetes side). I'll know more this evening when the timezone is more suitable for the US guys.

**Comment by davidopp** [comment]
This is listed as being for 1.1 -- is it actually gong to get in?

**Comment by burmanm** [comment]
No idea, the PR #15476 hasn't seen any comments from @piosz yet

**Comment by piosz** [comment]
I don't think so. Removing 1.1 milestone

**Comment by davidopp** [comment]
Assigning to @mwringe since I can't assign to @burmanm

**Comment by mwringe** [comment]
What exactly is the reason this can't be assigned to @burmanm ? Is there something that needs to be changed with his account?

**Comment by davidopp** [comment]
If I don't hear anything about this in the next 24 hours I'm going to move it to the next-candidate milestone.

**Comment by smarterclayton** [comment]
That's fine

**Comment by burmanm** [comment]
The PR got "LGTM" from Derek, then got passed from CI and then failed CI without changes (something related to GCE issues that look like intermittent test-setup failures - I can't see what I could do about them).
