### ISSUE TITLE
Reorganize getting started with building kubernetes

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#13876]
On this page - https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md - the flow appears like it should be:
- Fork the tree
- Download and setup that tree
- Run tests
- Code
- Commit
- Submit PR

However, right now, between steps 2 and 3, there's a large section on godeps, which, I suspect, a reasonably large set of people will never need to do (and it smashes their existing $GOPATH).

I propose moving it into its own file, and linking off to it.

**Comment by mikebrow** [comment]
FWIW If you're new and try to follow the steps they don't all work. I put together a blog that covers most of what's needed to get started with building kube.  https://developer.ibm.com/opentech/2016/06/15/kubernetes-developer-guide-part-1/

I was planning on submitting some PRs to fill in the holes in development.md. Though not sure how this document should fit with #22923 "guide for new contributors"

**Comment by mikebrow** [comment]
dibs .. I'll give this one a shot

**Comment by spzala** [comment]
@aronchick hi, seems like your suggestion for moving godeps is addressed under https://github.com/kubernetes/kubernetes/pull/29945 and so I am closing it. Hope makes sense. Thanks!

**Comment by spzala** [comment]
hmm.. seems like can't assign myself so may not able to close by going to try regardless :)

**Comment by spzala** [comment]
Well I need to work on org membership privilege :)  @aronchick if you can please verify the provided solution and close this issue that would be great. Thanks!!

**Comment by nikhita** [comment]
> However, right now, between steps 2 and 3, there's a large section on godeps, which, I suspect, a reasonably large set of people will never need to do (and it smashes their existing $GOPATH).

https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md doesn't have this anymore.

Closing.
/close
