### ISSUE TITLE
Generate experimental API group docs

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#13883]
We don't appear to generate static docs for the experimental API groups.  Certainly we aren't validating that the generated static docs are up to date.

Also, should check that other api groups besides experimental work.

**Comment by lavalamp** [comment]
@nikhiljindal is this documentation something you can do? It's just pointing the existing scripts at new locations, right? If you're crushed for time, then maybe @caesarxuchao can take this up.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/issues/14069 tracks adding a test to verify that our static api-reference docs are updated.

Once we start generating the spec in https://github.com/kubernetes/kubernetes/pull/15046, we can update https://github.com/kubernetes/kubernetes/blob/master/hack/gen-swagger-doc/run-gen-swagger-docs.sh to generate our docs from it.

**Comment by nikhiljindal** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/15757 to update the static docs to include extension resources.

**Comment by nikhiljindal** [comment]
As per discussion on #15757 @caesarxuchao is going to take this.

**Comment by erictune** [comment]
These appear to be generated now at https://raw.githubusercontent.com/kubernetes/kubernetes/master/docs/api-reference/extensions/v1beta1/definitions.html

Closing.

@caesarxuchao confirm this was okay to close.

**Comment by caesarxuchao** [comment]
Yes, that's fixed and cherry-picked. Thanks.
