### ISSUE TITLE
Make kubelet support  .docker/config

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#13881]
@yujuhong reports an issue from IRC:

nhumrich[2:31 PM]but docker doesnt use dockercfg anymore, it now stores a slightly different format in .docker/config
nhumrich[2:32 PM]so for those of us using docker after 1.7, how do we do private images?

We need to support both dockercfg and .docker/config

**Comment by dchen1107** [comment]
cc/ @mattmoor I am assigning this to you. Thanks!

**Comment by mattmoor** [comment]
Related to this: https://github.com/kubernetes/kubernetes/issues/10807

I'm looking at the credentialprovider part of this, but not pull secrets.

**Comment by bgrant0607** [comment]
Also related: #12717

**Comment by erictune** [comment]
#12717 should close this issue.

**Comment by dchen1107** [comment]
Yes, #12717 should close this issue, and @mattmoor and @erictune are reviewing it for us. Thanks!

**Comment by dchen1107** [comment]
This one should be fixed.
