### ISSUE TITLE
kubernetes-e2e-gce-parallel is occasionally timing out after 2 hours

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#13891]
For example
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/7733/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/7726/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/7722/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/7721/

@quinton-hoole @ixdy

**Comment by ixdy** [comment]
Dupe of #13485.
