### ISSUE TITLE
Kubernetes Service Type to be defined per Service Port

### ISSUE THREAD

**Issue by imesh** [kubernetes/kubernetes#13903]
In Kubernetes services we can define their service types [1]; ClusterIP, NodePort & LoadBalancer. In a given Kubernetes service we can define multiple service ports. 

This functionality is used in Apache Stratos [2] to generate Kubernetes services for exposing transports to external networks and internal communication. In this scenario a given product cluster may have multiple transports with different service types, some may need to be defined as NodePort to be accessed by external applications and others might need to be defined as ClusterIP.

Currently the service type can only be configured for a Kubernetes service, it is not possible to defined this for each service port. Therefore we need to create separate Kubernetes services for each port mapping depending on their service type. I think it would be better if we can allow this configuration to be defined per service port. WDYT?

[1] https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md#publishing-services---service-types
[2] https://github.com/apache/stratos

**Comment by thockin** [comment]
The normal answer to this is to define different Services.  While it is
appealing to decompose this into per-port control, the semantics start to
get a bit complicated, and I am not sure this is a common enough problem ti
warrant it.

Can you explain why creating multiple services is not workable for you?

**Comment by imesh** [comment]
Thanks Tim for your quick response! Appreciate it!

Currently we are creating a kubernetes service for each port mapping. We still do not have any problems with that. However IMO in a large deployment there could be hundreds of product clusters running on a single kubernetes cluster with thousands of port mappings. Then the number of kubernetes services we create can be very large. It would be much easier to maintain if we can group them together and define a single kubernetes service for each cluster and have all the port mappings inside.

**Comment by thockin** [comment]
Don't think of a Service as a set of backends.  Think of it as a set of
functionality with common rules.   I don't think we have enough outcry to
justify this change at this point.  Certainly if this is a real pain point
for lots of people, I want to know.
