### ISSUE TITLE
service using Nodeport really slow 

### ISSUE THREAD

**Issue by nancykyo** [kubernetes/kubernetes#13913]
the service definition
```
$kubectl get -o yaml service/packetix-112
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2015-09-09T10:07:34Z
  labels:
    name: packetix-112
  name: packetix-112
  namespace: default
  resourceVersion: "3925035"
  selfLink: /api/v1/namespaces/default/services/packetix-112
  uid: 970a03ec-56da-11e5-9633-fa163e6d9c98
spec:
  clusterIP: 172.18.48.118
  ports:
  - nodePort: 30503
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    name: packetix-112
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
iptables rule from one of the nodes
```
iptables-save|grep 30503
-A KUBE-NODEPORT-CONTAINER -p tcp -m comment --comment "default/packetix-112:" -m tcp --dport 30503 -j REDIRECT --to-ports 43913
-A KUBE-NODEPORT-HOST -p tcp -m comment --comment "default/packetix-112:" -m tcp --dport 30503 -j DNAT --to-destination 192.168.59.150:43913
```
iptables one the node where the container really runs.
```
# iptables-save |grep packetix-112
-A KUBE-NODEPORT-CONTAINER -p tcp -m comment --comment "default/packetix-112:" -m tcp --dport 30503 -j REDIRECT --to-ports 53976
-A KUBE-NODEPORT-HOST -p tcp -m comment --comment "default/packetix-112:" -m tcp --dport 30503 -j DNAT --to-destination 192.168.59.151:53976
-A KUBE-PORTALS-CONTAINER -d 172.18.48.118/32 -p tcp -m comment --comment "default/packetix-112:" -m tcp --dport 8001 -j REDIRECT --to-ports 53976
-A KUBE-PORTALS-HOST -d 172.18.48.118/32 -p tcp -m comment --comment "default/packetix-112:" -m tcp --dport 8001 -j DNAT --to-destination 192.168.59.151:53976
```
using 192.168.59.151:53976 is fast.
here is the time of execution from outside of the cluster.
```
for i in {1..30}; do time curl -x 192.168.59.151:30503 ip.cn; done

real  0m0.264s

real  0m51.782s

real  0m1.004s

real  1m0.425s
```
here is the time of execution from outside of the container.
```
root@packetix-112-p53dd q]# for i in {1..30}; do time curl -x 0.0.0.0:8001 ip.cn; done
real  0m0.249s

real  0m0.963s

real  0m1.268s
```

**Comment by wojtek-t** [comment]
cc @thockin

**Comment by jayunit100** [comment]
Possibly in e2es we could update networking e2e to confirm nodeports consistently return pings in under a second ?

**Comment by imesh** [comment]
Was this identified as an issue? If so would you mind explaining the problem and how we addressed it?
Thanks

**Comment by thockin** [comment]
Can you look at the kube-proxy logs?  There's obviously something REALLY wrong.

How many backends are under this service?  I've seen problems of a single backend being really stuck, causing things like this...

**Comment by nancykyo** [comment]
here is my proxy setting
```
kube-proxy --master=http://kubermaster.corp.qunar.com --iptables-sync-period=1m --masquerade-all=true
```
i'm trying to setting this to using pure iptables.
```
--legacy-userspace-proxy=false
```
but it seems doesn't work 
```
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0           /* default/packetix-297: */ tcp dpt:31126 redir ports 54170

DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0           /* default/packetix-297: */ tcp dpt:31126 to:192.168.51.89:54170
```
```
netstat -ltpn | grep 54170
tcp        0      0 :::54170                    :::*                        LISTEN      2426/kube-proxy
```

there are 360+ pods and all pods works as a proxy, it provide a http proxy for a service out of this cluster.
it generate 1414 iptables rules on each node.

**Comment by thockin** [comment]
> here is my proxy setting
>
> kube-proxy --master=http://kubermaster.corp.qunar.com --iptables-sync-period=1m --masquerade-all=true

You should not need the masquerade-all flag - it's really just an
escape hatch for emergencies.

> i'm trying to setting this to using pure iptables.
>
> --legacy-userspace-proxy=false
>
> but it seems doesn't work

What exactly doesn't work?

> REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0           /* default/packetix-297: */ tcp dpt:31126 redir ports 54170
>
> DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0           /* default/packetix-297: */ tcp dpt:31126 to:192.168.51.89:54170
>
> netstat -ltpn | grep 54170
> tcp        0      0 :::54170                    :::*                        LISTEN      2426/kube-proxy

What am I looking at?

> there are 360+ pods and all pods works as a proxy, it provide a http proxy for a service out of this cluster.
> it generate 1414 iptables rules on each node.

That sounds about right.  We do generate a handlful of iptables rules
per Service-endpoint, but most packets will only traverse a small
number of rules: O(num_services_in_cluster).

**Comment by nancykyo** [comment]
I thought using this setting, the flow can skip the kube-proxy process, but completely forwarded via iptables.
--legacy-userspace-proxy=false
so I stop the kube-proxy process, I wish to see the networking still working, but it's down immediately. Maybe I'm misunderstanding the concept?

**Comment by thockin** [comment]
masquerade-all obscures source IPs in th eiptable proxier, nothing more.

If you set -legacy-userspace-proxy=false you should be able to kill the
proxy and still serve traffic - is that not the case?

There are a lot of variables in play here - can we settle on one set of
parameters, characterize the problem, and see what we can discover about it?

I'm not clear on the problem anymore.

**Comment by nancykyo** [comment]
ok, now narrow down the problem. just the parameter: -legacy-userspace-proxy
> If you set -legacy-userspace-proxy=false you should be able to kill the
> proxy and still serve traffic - is that not the case?

no, the connection will be down immediately. 
when i was trying the following command.
```
for i in {1..30}; do time curl -x 192.168.51.89:31126 ip.cn; done
```
I stopped the proxy at the same time.
```
real	0m9.876s

real	0m1.989s

real	0m1.001s

real	0m1.027s
curl: (52) Empty reply from server

real	0m0.332s
curl: (7) couldn't connect to host

real	0m0.022s
curl: (7) couldn't connect to host
```

![image](https://cloud.githubusercontent.com/assets/1332885/9869728/e6a6415e-5bb8-11e5-933f-b089d05b615f.png)

**Comment by nancykyo** [comment]
and the iptables rules are not cleared.
![image](https://cloud.githubusercontent.com/assets/1332885/9869866/f49a4930-5bb9-11e5-9cfb-930c46f5dd9d.png)

**Comment by nancykyo** [comment]
hmm.... strange things. I went through the log.
setting the --legacy-userspace-proxy=false but log said Using userspace Proxier.

```
[root@l-kubecluster9.ops.cn8 ~]# grep 'Using userspace Proxier' /home/q/log/kube-proxy
I0915 15:14:24.417420   25979 server.go:192] Using userspace Proxier.
I0915 15:18:21.739832   13518 server.go:192] Using userspace Proxier.
I0915 15:19:12.081839   19694 server.go:192] Using userspace Proxier.
[root@l-kubecluster9.ops.cn8 ~]# ps aux|grep kube-proxy
root     19694 42.7  0.3 450744 24852 pts/0    Sl   15:19   0:07 kube-proxy --master=http://kubermaster.corp.qunar.com --iptables-sync-period=1m --legacy-userspace-proxy=false --v=2
```

**Comment by thockin** [comment]
Is your iptables new enough?  Try turning the --v to 4

**Comment by nancykyo** [comment]
I modify the code to set 
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L178
```
shouldUseIptables = true
```
now it works fine
```
 grep 'Using iptables Proxier' /home/q/log/kube-proxy
I0915 15:47:44.029870   22243 server.go:180] Using iptables Proxier.
```
so the command line setting doesn't work?

**Comment by nancykyo** [comment]
I know why now..
const iptablesMinVersion = utiliptables.MinCheckVersion
![image](https://cloud.githubusercontent.com/assets/1332885/9871294/3b54b8d2-5bc5-11e5-8a11-aeb0f6bad1e7.png)

we are using iptables v1.4.7

**Comment by jayunit100** [comment]
So , i didn't entirely follow this, but I guess we should fail loudly if someone sets kube proxy off while iptables is below a certain version?

**Comment by resouer** [comment]
@jayunit100 I think we have see [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/iptables/iptables.go#L130) 

Need to change log level if ` --legacy-userspace-proxy=false`?

**Comment by jayunit100** [comment]
Thanks for the link.  It appears it's just warning and moving forward...?
by "fail" I mean maybe it should die.....rather than warn.

**Comment by resouer** [comment]
@jayunit100 Actually, the existing version check only determines whether we can set `-C` and `-w`, so it's not clear `how new` the iptables should be to support  `-legacy-userspace-proxy=false`. Hopes @thockin can lead out ...

**Comment by thockin** [comment]
The iptables proxy relies on a bunch of kernel features that are relatively
new (not that new but newer than CentOS 6 :) so we just attached to the
iptables version.  I forget if that also guarded some of the iptables flags
we used.

What distro and kernel are you on that has iptables 1.4.7?  If you say
CentOS 6 I'm going to tell you that you get to stay on the userspace
proxier.  That iptables version was release LITERALLY 5 years ago.  The
version we need is 4.5 years old.

**Comment by thockin** [comment]
@nancykyo any updates here?  Can we close this?

**Comment by nancykyo** [comment]
yes, we can close this. using pure iptables is acceptable, but kube-proxy seem have some performance problem.

**Comment by thockin** [comment]
We're investigating some other reports of slowness, too.
