### ISSUE TITLE
Is it possible to keep original files in volume path of container?

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#13914]
So, here's the problem:

Both `emptyDir` and `hostDir` Volumes are actually host volume for Docker, thus will hide the original files of the volume path inside the container.

Is there possible way to keep those files?  For example, `docker run -v /data`, daemon will copy the contents in `/data` to host before bind mounting, so users can consume those files after container starts up.

Can we support this in kubelet?

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/issues/12526
https://github.com/kubernetes/kubernetes/issues/831

Supporting the idea of a container that pre-populates a volume is covered by one or both of the above, but this is something that can be managed manually (if a bit awkwardly) today.
