### ISSUE TITLE
Add API group concept to kubectl

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#13929]
E.g.:

* kubectl delete group/resource name
* kubectl get group/resource name
* kubectl get resource/name
* kubectl get resource name

Need to make reasonable assumption about the group when it's not provided?

**Comment by lavalamp** [comment]
@caesarxuchao @JanetKuo

**Comment by JanetKuo** [comment]
Do we support these?
- kubectl operation group/resource
- kubectl operation group/resource/name
- kubectl operation group resource
- kubectl operation group resource name

When the group isn't provided, we assume it's empty or find the first match?

**Comment by lavalamp** [comment]
I think if group is not provided, then we should see what groups the resource could possibly be inside; if there's only 1, great. If there's more than one, we should error out.

Likewise it shouldn't be ambiguous whether `kubectl get a b` is group/resource or resource/name, because presumably we won't have groups named e.g. "pods" or resources named e.g. "experimental"; but if we do have those cases, we should force the user to be explicit rather than do something surprising.

I don't have opinions on whether '/', ' ', or both should be allowed as separators.

**Comment by lavalamp** [comment]
So to do that, kubectl would need to get (or maintain) a map of resource -> (group, resource). We should get that from apiserver, not by looking at the resources compiled into kubelet.

**Comment by JanetKuo** [comment]
TODOs:
- [ ] Make setting group/version in unversioned.Request possible 
- [ ] Store group/version information in resource.Helper
- [ ] `kubectl --api-version` flag should work if we set it to v1 (legacy behavior) and when we specify group/version

**Comment by caesarxuchao** [comment]
@JanetKuo, just in case you don't know this already, as stated in the [proposal](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/api-group.md):
"When kubectl is used with a single resource type, the --api-version and --output-version flag of kubectl should accept values in the form of group/version, and they should work as they do today. For multi-resource operations, we will disable these two flags initially."

**Comment by liggitt** [comment]
as we think about this, we should also consider whether subresources (which kubectl doesn't support today) should be addressable, and how

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by AdoHe** [comment]
It seems some TODOs still not finished, will pick one.

**Comment by nikhiljindal** [comment]
We now support resource.version.group for kubectl commands: https://github.com/kubernetes/kubernetes/pull/22853

https://github.com/kubernetes/kubernetes/issues/22454 tracks what we should do about --api-version and --output-version.

I guess we can close this issue?

**Comment by deads2k** [comment]
> I guess we can close this issue?

I think we'll still have problems specifying api-versions for names retrieved from files and for commands that don't take resource strings like `cordon` as a for instance.  We don't use those often downstream, have you guys already figured out what to do about those?

**Comment by kargakis** [comment]
I think `cordon` can handle resource strings.

**Comment by kargakis** [comment]
Is this still an issue?

**Comment by bgrant0607** [comment]
Please file more specific issues for any remaining problems.
