### ISSUE TITLE
RFE: Review Workflow Diagram

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#13935]
Use Case: 

Developer has some cool new feature that they wish to add to kubernetes. This diagram walks them through the process that the developer will follow to have their PR-reviewed in a timely fashion.  It will also set the expectations for all parties involved in order to remove ambiguity. 

@bgrant0607 
/cc @childsb  @kubernetes/rh-cluster-infra

**Comment by bgrant0607** [comment]
An example:
https://docs.docker.com/project/make-a-contribution/

**Comment by bgrant0607** [comment]
Current documentation is text in docs/devel:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/faster_reviews.md
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md
and probably others

**Comment by bgrant0607** [comment]
cc @kelseyhightower

**Comment by timothysc** [comment]
Even better, some update to their PR which shows where they are are in the lifecycle.

**Comment by pmorie** [comment]
Corollary: we should probably have some guidance on when your PR has an intrinsic risk of not being mergeable however high the quality of code, like when it affects something consensus / discussion is needed around.

**Comment by ixdy** [comment]
@jlowdermilk I think you're working on this?
