### ISSUE TITLE
Kubelet: Add timeouts for Docker API calls

### ISSUE THREAD

**Issue by csrwng** [kubernetes/kubernetes#13934]
In certain cases, the Docker daemon can become unresponsive to certain API calls. Instead of returning an error, a call can hang indefinitely. The kubelet should guard against this by allowing a configurable timeout on calls to the Docker daemon.

**Comment by csrwng** [comment]
@smarterclayton

**Comment by timothysc** [comment]
cc @derekwaynecarr

**Comment by smarterclayton** [comment]
And the failure of one of these calls against the daemon should probably trigger some sort of status update to pods.

**Comment by bprashanth** [comment]
@kubernetes/goog-node  https://github.com/kubernetes/kubernetes/issues/9896

**Comment by gmarek** [comment]
cc @yujuhong

**Comment by dchen1107** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/9896
