### ISSUE TITLE
Improve resource_usage e2e test.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#13931]
As @yujuhong noted it'd be useful to reduce variance of measurements. Additionally we may want to include fluentd pod in the measurements.

**Comment by yujuhong** [comment]
@gmarek, FYI, I am adding a long (~1hr) resource monitoring test in #14453. It's mainly to track kubelet/docker resource usage in the soak cluster for v1.1. We want some numbers to gauge whether kubelet consumes unreasonable amount of resources even in a relatively stable cluster.

**Comment by gmarek** [comment]
Framework can now gather data about kube-system pod resource usage, it's turned on by the flag: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e_test.go#L91

This test is currently constantly failing because of #17774, so it needs to stay in the flaky suite until we decide what to do with it.

**Comment by wojtek-t** [comment]
@gmarek Is this a duplicate of https://github.com/kubernetes/kubernetes/issues/12429 ? (it seems similar). If so, can we close one of those?

**Comment by gmarek** [comment]
Yeah, in a sense it is. Closing in favor of #12429
