### ISSUE TITLE
Provide an option for creating PDFs from our docs

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#13940]
Users are requesting a PDF version of our docs. One request is here: http://stackoverflow.com/questions/32538276/how-to-get-a-pdf-print-version-of-kubernetes-docs

Due to the costs and overhead of creating, maintaining, and providing PDFs, the current thinking is to provide a single concatenated HTML file that users could easily covert to PDF (for example, Chrome's "print to PDF" option). @timstclair proposed that a script be created to perform the concatenation.

Other options were searched for (without luck) and GitBook was investigated. Unfortunately, GitBook has an involved process, making it an unreasonable for us to ask our users to perform [lots of setup (ie you need an account and cloning docs from the repo is required) and an .md file that specifies the content structure is needed (we would need to copy and convert our navigation tree (nav_v1.0.html) file, including making all URLs absolute)].

**Comment by bgrant0607** [comment]
@chrislovecnm mentioned that he wanted a pdf of kubectl documentation

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
@kubernetes/sig-release-misc

**Comment by ahmetb** [comment]
Please close this and open this issue at https://github.com/kubernetes/kubernetes.github.io/issues/new if you think it's still relevant. I haven't heard any requests about this lately.

Maybe someone from the community can take a look at GitBook again now that we have a separate Jekyll based website repo.
