### ISSUE TITLE
Change Watch behavior for resourceVersion=0 in v2 API

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#13969]
Currently, Watch request with resourceVersion=0 results in:
- returning a single "watch event" for every object existing "now"
- starts watching from that point

This is pretty misleading (e.g. it's different that what we have in etcd, where there is no first step from above).
In the v2 api, we should probably eliminate the first stop (or even disallow watch requests with resourceVersion = 0).

**Comment by thockin** [comment]
What do you mean by v2 API?  Are we ever going to have a v2 of the machiery and semantics?

**Comment by wojtek-t** [comment]
In 2015 I thought it's not ridiculous. I'm not sure I believe in it now.

Moreover, with https://github.com/kubernetes/enhancements/pull/3142 we will actually be taking benefits of semantic like this, so we should close this.
