### ISSUE TITLE
Fix downward API in containerised kubelet

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#13987]
Currently when kubelet is running in a container downward API doesn't work. The problematic workflow is:
1. Kubelet mounts tmpfs as a downward API volume using `nsenter_mounter` in host's namespace
2. Kubelet reads data from API server
3. Kubelet tries to write data to the newly created volume, but as it resides in host's namespace it fails.

This will be solved with docker/docker#15648, but before it happens we will need some temporary solution. One workaround is to use nsenter to write data similarly to how we have mounted it.

This is important to run kubelet and other k8s components as docker containers, which should greatly simplify UX for new setups.

@dchen1107 @smarterclayton @brendandburns @pmorie

**Comment by dims** [comment]
https://github.com/docker/docker/pull/15648 points to https://github.com/docker/docker/pull/16773 which points to https://github.com/docker/docker/pull/17034 which has already been merged.

I have a PR against docs:
https://github.com/kubernetes/kubernetes.github.io/pull/493 on using 
`--volume=/var/lib/kubelet/:/var/lib/kubelet:rw,shared`

Guess we can close this issue now.
