### ISSUE TITLE
DaemonRestart test is not run in the kubernetes-e2e-gce-flaky builds

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#13996]
DaemonRestart tests are marked as flaky, but they are not run in the kubernetes-e2e-gce-flaky builds

E.g., In http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-flaky/5060/consoleFull, the args passed to ginkgo is
```
 '--ginkgo.skip=Autoscaling\sSuite|Skipped|Reboot|Restart|Example|Reboot' '--ginkgo.focus=DaemonRestart|ResourceUsage|monotonically\sincreasing\srestart\scount|should\sbe\sable\sto\schange\sthe\stype\sand\snodeport\ssettings\sof\sa\sservice|allows\sscheduling\sof\spods\son\sa\sminion\safter\sit\srejoin
```

Could it be that "DaemonRestart" also matches "Restart" in `--ginkgo.skip` and gets skipped always? 

/cc @quinton-hoole

**Comment by quinton-hoole** [comment]
Yes, thanks for spotting that - it's a bug.  I'll send you a PR to fix it shortly...
