### ISSUE TITLE
Help Wanted on setting external load balancers

### ISSUE THREAD

**Issue by suyogbarve** [kubernetes/kubernetes#14003]
Looking for help/documentation/tutorial to setup a baremetal cluster which support external load balancers.
I have created a 4 node cluster as follows
Master: RHEL 7 with docker, flannel, k8s, etcd
Node1,Node2,Node3 with docker flannel, k8s,etcd

I desire to use LoadBalancer feature of Kubernetes Services.

Regards
Suyog

**Comment by bprashanth** [comment]
https://github.com/kubernetes/contrib/tree/master/service-loadbalancer
In the future you might want to ask on slack/irc/mailing list for help. Github issues are reserved for actual *issues*.
