### ISSUE TITLE
[RFC] DeploymentAPI: Change surge and unavailable % to be based on desired replicas

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#14008]
MaxSurge and MaxUnavailable %s should be percentage of desired replicas (Deployment.Spec.Replicas) instead of current replicas (number of old pods when deployment is created). That way the deployment intent is self-contained in the deployment object and it is same no matter when the deployment is created. When the % is based on current replicas, then the intent changes depending on number of replicas when deployment is created.

What do you guys think?

@bgrant0607 @ghodss @ironcladlou @smarterclayton

**Comment by bgrant0607** [comment]
MaxIncrement? You mean MaxUnavailable?

Otherwise, SGTM

**Comment by nikhiljindal** [comment]
yea sorry I meant MaxUnavailable

**Comment by smarterclayton** [comment]
Is there any scenario when maxunavailable new is bad?  I thought we had
one, but now can't think of it...

On Sep 15, 2015, at 8:19 PM, Nikhil Jindal <notifications@github.com> wrote:

yea sorry I meant MaxUnavailable

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14008#issuecomment-140585943>
.

**Comment by ironcladlou** [comment]
Consider asymmetrical updates. Given old=10 and new=20, with maxUnavailability=50% and maxSurge=0% based on new, it's possible you'll effectively incur 100% downtime immediately.

**Comment by nikhiljindal** [comment]
Yes thats a good example. There wont be any downtime tough.
We will be stuck eternally, since we wont be able to scale up nor scale down.

The process will timeout eventually and user will have to do it again with different parameters.

**Comment by bgrant0607** [comment]
See also #14062

**Comment by bgrant0607** [comment]
Old = 10, new = 20.
maxUnavailable = 50%, maxSurge = 0%

Immediately the new RC can be scaled up to 10. The original RC can then be scaled down when new replicas become available. I don't see a problem. 50% * 20 = 10.

**Comment by bgrant0607** [comment]
Imagine what would happen if the user performed the scaling operation first.

If the user wants a different outcome, just done change the replicas count at the same time.

**Comment by smarterclayton** [comment]
As long as we have no gaps that was the only reason we (dan and I) based it
on the old value.

On Sep 16, 2015, at 7:36 PM, Brian Grant <notifications@github.com> wrote:

Old = 10, new = 20.
maxUnavailable = 50%, maxSurge = 0%

Immediately the new RC can be scaled up to 10. The original RC can then be
scaled down when new replicas become available. I don't see a problem. 50%
* 20 = 10.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14008#issuecomment-140926108>
.

**Comment by nikhiljindal** [comment]
aah you are right @bgrant0607 
That example will work fine.

**Comment by ironcladlou** [comment]
Hmm, agree with @bgrant0607. I wasn't considering how the scale up would be attempted first.

**Comment by nikhiljindal** [comment]
This is fixed in both deployments and rollingUpdate. Closing the issue.
