### ISSUE TITLE
Help Wanted: Creating a CAAS using Kubernetes/Docker/Flannel/etcd

### ISSUE THREAD

**Issue by suyogbarve** [kubernetes/kubernetes#14006]
I would like to request some expert opinion from SMEs on:

1) What would it take to build a CAAS using physical/bare-metal servers.
a. Suggested options to implement concerns like : Resource Monitoring, Utilization etc
b. Any suggested approaches to make a robust, scalable, resilient underlying infrastructure which marries well kubernetes/docker/etcd/flannel based CAAS layer 

![kubecluster](https://cloud.githubusercontent.com/assets/1817914/9891822/edf37ec0-5bce-11e5-8cc7-12023ae06df6.png)

2) Kubernetes as a solution likes to leverage underlying "Cloud Provider" ; any suggestion to create it from scratch? (of course I am not looking at elaborate solutions like OpenStack, since the idea is to create a lean/low-cost/light-weight solution) The solution I am looking for is to create an IAAS out of lets say 10 prod servers. Not looking for Data Center type of solutions.

Regards
Suyog

**Comment by thockin** [comment]
Hi there,

As interesting as this topic is - this is not the right forum for it.  Perhaps the google-containers mailing list (https://groups.google.com/forum/#!forum/google-containers) is a better place.

In the mean time, have you looked at RedHat's OpenShift system?

**Comment by suyogbarve** [comment]
I kind of knew that, but was unable to resist the temptation.
 I did not get much details on open shift, I will try to post this in their forum

Thanks for your reply

Regards
Suyog
