### ISSUE TITLE
Upgrade to InfluxDB v0.9

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#14009]
The new version of InfluxDB provides a lot of features that will help improve the scalability and performance of the monitoring stack. Specifically InfluxDB v0.9+ supports labels, clustering and improved tail write latencies. More information [here](https://influxdb.com/blog/2015/08/26/InfluxDB-0_9_3-released-with-compression-and-improved-write-throughput.html) and [here](https://influxdb.com/blog/2014/12/08/clustering_tags_and_enhancements_in_0_9_0.html).

cc @dchen1107

**Comment by vishh** [comment]
xref https://github.com/kubernetes/heapster/issues/302

**Comment by dchen1107** [comment]
Discussed offline, here is the latest updates:

1) For 1.1, we upgrade influxdb to v0.8.9, which still have memory leakage issue, but have new interfaces / endpoints and new data format. 
2) post 1.1, we upgrade influxdb to v0.9 to enable the new data format and interface. 

I move this one out of 1.1 scope.

**Comment by vishh** [comment]
To clarify, InfluxDB does not support upgrading from v0.8 to v0.9
off-the-box. It requires upgrading to v0.8.9, then manually exporting all
the metrics, upgrading to v0.9.4, and then importing the old metrics.
In Kubernetes v1.1, we will upgrade InfluxDB to v0.8.9.
We can try upgrading to InfluxDB v0.9.4 in a patch release of Kubernetes
v1.1.

**Comment by KyleAMathews** [comment]
0.10 is out https://influxdata.com/blog/announcing-influxdb-v0-10-100000s-writes-per-second-better-compression/

**Comment by vishh** [comment]
InfluxDB has been upgraded to v0.9.6. @KyleAMathews: A patch to update to 0.10 will be much appreciated!
