### ISSUE TITLE
Get replicationcontroller list by fieldSelector error: Namespace parameter required

### ISSUE THREAD

**Issue by ttllyy** [kubernetes/kubernetes#14014]
kubernetes version:1.02

Get /api/v1/replicationcontrollers?fieldSelector=metadata.name%3Dmyapp
Http response:400
error:Namespace parameter required

swagger ui:
Get /api/v1/replicationcontrollers
Parameters:
pretty                                  (query)
labelSelector                      (query)
fieldSelector                       (query)
watch                                 (query)
resourceVersion                 (query)

No  parameter about namespace?

Thanks!

**Comment by lavalamp** [comment]
The error message is wrong, it's now an entry in the path.

**Comment by lavalamp** [comment]
Oh, sorry. This is confusing. You accessed the "all namespaces" endpoint, for which it doesn't make sense to pass a name. The swagger ui for that should not show the label & field query parameters, which really only make sense if you provide a namespace. Likewise the error message should probably call that out specifically.

**Comment by feihujiang** [comment]
I checked the current version:
~~~
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.1.1068+726844ec8a164f-dirty", GitCommit:"726844ec8a164fe48638282dd6e204ba7a721852", GitTreeState:"dirty"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.1.947+7ccae98af076e2-dirty", GitCommit:"7ccae98af076e2f24a34df196ad8835bfc7f7d4f", GitTreeState:"dirty"}
~~~
and found it is supported now, 
```Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=metadata.name=counter```
The result is: 
~~~
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/pods",
    "resourceVersion": "10628"
  },
  "items": [
    {
      "metadata": {
        "name": "counter",
        "namespace": "default",
   ......
}
~~~

I also checked the replicationcontrollers, also support.
@lavalamp Do we need to do anything about this issue?

**Comment by lavalamp** [comment]
@feihujiang that's a bug-- you need to specify a namespace before name makes sense. @smarterclayton I thought you fixed that? Am I misremembering?

**Comment by smarterclayton** [comment]
I actually fixed it to allow name without namespace.  Previously, the special case for metadata.name assumed it could call keyfunc which checked for namespace and errors out.  Fast path there didn't need a list.  However, we now detect that you tried the fast path, but it wasn't valid, so we process the non fast path (list), rejecting any entries that don't match the selector.

So there was a bug, but it was in the special case code, not the general path.  Name across all namespaces works

**Comment by lavalamp** [comment]
@smarterclayton I'm saying the behavior semantically is nonsensical-- the system is doing the operation that was requested but that operation makes no sense. IMO we should error out, not give you a list of every pod named "foo" in any namespace. Or is there some valid use case for this behavior?

**Comment by smarterclayton** [comment]
I want a list of all services called "dns" across all namespaces, or all
quotas called "custom" across all namespaces, or all service accounts
called "builder" across all namespaces.  Name is no different than any
other field we'd filter on.

On Oct 19, 2015, at 1:15 PM, Daniel Smith <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> I'm saying the behavior
semantically is nonsensical-- the system is doing the operation that was
requested but that operation makes no sense. IMO we should error out, not
give you a list of every pod named "foo" in any namespace. Or is there some
valid use case for this behavior?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14014#issuecomment-149285474>
.

**Comment by lavalamp** [comment]
Alright, I buy that enough to not write something to specifically prevent it. :)

**Comment by smarterclayton** [comment]
Whew :)
