### ISSUE TITLE
https-nginx example requires a development environment to be setup

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#14017]
but does not mention how to do that or that it's even a prerequisite. Someone ran into this on slack so reporting here.

https://github.com/kubernetes/kubernetes/tree/master/examples/https-nginx

The command:

```
make keys secret KEY=/tmp/nginx.key CERT=/tmp/nginx.crt SECRET=/tmp/secret.json
```

depends on building some k8s.io/kubernetes packages.

@bprashanth

**Comment by bprashanth** [comment]
Yeah, I'll add that in the docs. The thing that spits out the secret as json requires k8s api.

**Comment by derekmahar** [comment]
@bprashanth How does one build the k8s api?

**Comment by bprashanth** [comment]
just run make, as long as you have the go imports worked out it should succeed

**Comment by bprashanth** [comment]
i.e it's just a normal go program that imports `pkg/api` https://github.com/kubernetes/kubernetes/blob/master/examples/https-nginx/make_secret.go#L29

**Comment by derekmahar** [comment]
The Go imports are the problem.  I'm not a Go programmer, so I need to setup and learn this from scratch.

**Comment by bprashanth** [comment]
oh yeah, there's an easier solution now. Just create the secret using openssl eg:
```
$ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout $(KEY) -out $(CERT) -subj "/CN=nginxsvc/O=nginxsvc"
```

then use kubectl to shove that into a kubernetes seceret:
```
$ kubectl create secret tls nginxsecret --key /tmp/nginx.key --cert /tmp/nginx.crt
```

Where nginxsecret is the same name used in the yaml.

**Comment by derekmahar** [comment]
For example, here is what I see when I run the make command:

```
derek@derek-HP-EliteOne-800-G1-AiO:~/Projects/kubernetes/examples/https-nginx$ make keys secret KEY=/tmp/nginx.key CERT=/tmp/nginx.crt SECRET=/tmp/secret.json
# The CName used here is specific to the service specified in nginx-app.yaml.
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/nginx.key -out /tmp/nginx.crt -subj "/CN=nginxsvc/O=nginxsvc"
Generating a 2048 bit RSA private key
...............+++
...................+++
writing new private key to '/tmp/nginx.key'
-----
go run make_secret.go -crt /tmp/nginx.crt -key /tmp/nginx.key > /tmp/secret.json
make_secret.go:29:2: cannot find package "k8s.io/kubernetes/pkg/api" in any of:
	/usr/lib/go-1.6/src/k8s.io/kubernetes/pkg/api (from $GOROOT)
	/home/derek/Projects/kubernetes/src/k8s.io/kubernetes/pkg/api (from $GOPATH)
make_secret.go:34:2: cannot find package "k8s.io/kubernetes/pkg/api/install" in any of:
	/usr/lib/go-1.6/src/k8s.io/kubernetes/pkg/api/install (from $GOROOT)
	/home/derek/Projects/kubernetes/src/k8s.io/kubernetes/pkg/api/install (from $GOPATH)
make_secret.go:30:2: cannot find package "k8s.io/kubernetes/pkg/apimachinery/registered" in any of:
	/usr/lib/go-1.6/src/k8s.io/kubernetes/pkg/apimachinery/registered (from $GOROOT)
	/home/derek/Projects/kubernetes/src/k8s.io/kubernetes/pkg/apimachinery/registered (from $GOPATH)
make_secret.go:31:2: cannot find package "k8s.io/kubernetes/pkg/runtime" in any of:
	/usr/lib/go-1.6/src/k8s.io/kubernetes/pkg/runtime (from $GOROOT)
	/home/derek/Projects/kubernetes/src/k8s.io/kubernetes/pkg/runtime (from $GOPATH)
Makefile:28: recipe for target 'secret' failed
make: *** [secret] Error 1
```

I'm pretty sure my GOPATH is not set correctly.

**Comment by bprashanth** [comment]
let me know if the steps in previous example don't work, you need a kube version >= 1.3. If they do work, and you have the time, please send a pr :)

**Comment by derekmahar** [comment]
In order to fix this issue, I followed the steps in [Go development environment](https://github.com/derekmahar/kubernetes/blob/master/docs/devel/development.md#go-development-environment).  Then I built Kubernetes and successfully rebuilt https-nginx.

**Comment by luntzel** [comment]
`go get k8s.io/kubernetes/pkg/api`

seemed to work for me.

**Comment by cove** [comment]
AFter a go get, it almost worked for me, but maybe something changed?

`go run make_secret.go -crt /tmp/nginx.crt -key /tmp/nginx.key > /tmp/secret.json
# command-line-arguments
./make_secret.go:63: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
./make_secret.go:69: cannot use api.Codecs.LegacyCodec(api.Registry.EnabledVersions()...) (type "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Codec) as type "k8s.io/apimachinery/pkg/runtime".Encoder in argument to "k8s.io/apimachinery/pkg/runtime".EncodeOrDie:
        "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Codec does not implement "k8s.io/apimachinery/pkg/runtime".Encoder (wrong type for Encode method)
                have Encode("k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Object, io.Writer) error
                want Encode("k8s.io/apimachinery/pkg/runtime".Object, io.Writer) error
make: *** [secret] Error 2
`

**Comment by bprashanth** [comment]
This is a better example of how to create certs: https://github.com/kubernetes/ingress/blob/master/examples/PREREQUISITES.md#tls-certificates

Will update the https-nginx example soon.

**Comment by cove** [comment]
@bprashanth thanks, that worked for me.

**Comment by nickleefly** [comment]
I use the following to create cert
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/nginx.key -out /tmp/nginx.crt -subj "/CN=nginxsvc/O=nginxsvc"
kubectl create secret tls nginxsecret --key /tmp/nginx.key --cert /tmp/nginx.crt
```

when run `kubectl describe secret nginxsecret`
```
Name:		nginxsecret
Namespace:	default
Labels:		<none>
Annotations:	<none>

Type:	kubernetes.io/tls

Data
====
tls.crt:	1220 bytes
tls.key:	1675 bytes
```

I have to change [default.conf](https://github.com/kubernetes/kubernetes/blob/master/examples/https-nginx/default.conf)
to use `tls.crt` and `tls.key`

Then it worked as [the doc](https://github.com/kubernetes/kubernetes/tree/master/examples/https-nginx) describes

**Comment by mikedanese** [comment]
This issue appears to be defunct.

**Comment by daplho** [comment]
Actually, it does come up still. Not quite sure what the definite cause is but it seemed to go away after a build of `kubernetes` and

```
go get k8s.io/kubernetes/pkg/api
go get k8s.io/apimachinery/pkg/apis/meta/v1
```

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
```
make keys secret KEY=/tmp/nginx.key CERT=/tmp/nginx.crt SECRET=/tmp/secret.json
```

The Above one line make me so hard.
To walk through [this document](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/), It would be nice to provide example `secret.json` file.

**Comment by joyolkreg** [comment]
This is still a issue. The document is still unfixed.

**Comment by afausti** [comment]
I have run in to the same issue with the nginx https example.

**Comment by leejian0612** [comment]
@nickleefly no need to modify the default.conf, you can specify the file name by using generic secret
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/nginx.key -out /tmp/nginx.crt -subj "/CN=nginxsvc/O=nginxsvc"
kubectl create secret generic nginxsecret --from-file=nginx.key=/tmp/nginx.key --from-file=nginx.crt=/tmp/nginx.crt
```

**Comment by tim-jones-001** [comment]
As others have said previously this is still an issue - the documentation does not explain how to successfully create the secret.json file as the make_secret.go does not run without the API installed

**Comment by argiris-mat** [comment]
I got the packages mentioned above but there is another error

`# The CName used here is specific to the service specified in nginx-app.yaml.
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/nginx.key -out /tmp/nginx.crt -subj "/CN=nginxsvc/O=nginxsvc"
Generating a 2048 bit RSA private key
.................................+++
..........................+++
writing new private key to '/tmp/nginx.key'
-----
go run make_secret.go -crt /tmp/nginx.crt -key /tmp/nginx.key > /tmp/secret.json
# command-line-arguments
./make_secret.go:62:13: cannot use "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
./make_secret.go:70:64: cannot use legacyscheme.Codecs.LegacyCodec(legacyscheme.Registry.EnabledVersions()...) (type "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Codec) as type "k8s.io/apimachinery/pkg/runtime".Encoder in argument to "k8s.io/apimachinery/pkg/runtime".EncodeOrDie:
	"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Codec does not implement "k8s.io/apimachinery/pkg/runtime".Encoder (wrong type for Encode method)
		have Encode("k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Object, io.Writer) error
		want Encode("k8s.io/apimachinery/pkg/runtime".Object, io.Writer) error
./make_secret.go:70:64: cannot use secret (type *core.Secret) as type "k8s.io/apimachinery/pkg/runtime".Object in argument to "k8s.io/apimachinery/pkg/runtime".EncodeOrDie:
	*core.Secret does not implement "k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "k8s.io/apimachinery/pkg/runtime".Object
make: *** [secret] Error 2`
