### ISSUE TITLE
collecting log using fluentd, run kubelet with --docker-root=XX not working

### ISSUE THREAD

**Issue by nancykyo** [kubernetes/kubernetes#14029]
using centos6, docker 1.6...
collecting log using fluentd, and trying to use this feature from 
`kubernetes/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd.conf`

> watch changes to Docker log files that live in the directory /var/lib/docker/containers/ and are symbolically linked to from the /varlog directory using names that capture the pod name and container name.

but from code, it seems that the manager get "docker root" from docker info.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L163

```
docker info
Containers: 143
Images: 255
Storage Driver: devicemapper
 Pool Name: docker-252:7-2140163-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.545 GB
 Data Space Total: 107.4 GB
 Data Space Available: 52.02 GB
 Metadata Space Used: 20.59 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.127 GB
 Udev Sync Supported: false
 Data loop file: /home/q/docker/devicemapper/devicemapper/data
 Metadata loop file: /home/q/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.18.17-1.el6.x86_64
Operating System: <unknown>
CPUs: 4
Total Memory: 3.866 GiB
Name: l-kubecluster1.ops.cn8
ID: JKN2:X7IR:THCS:CNNU:WAQV:UFRQ:PEYC:4272:TWGK:4FTC:VMO5:STX3
WARNING: No swap limit support
```

```
docker -D info
Containers: 143
Images: 255
Storage Driver: devicemapper
 Pool Name: docker-252:7-2140163-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.545 GB
 Data Space Total: 107.4 GB
 Data Space Available: 52.02 GB
 Metadata Space Used: 20.59 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.127 GB
 Udev Sync Supported: false
 Data loop file: /home/q/docker/devicemapper/devicemapper/data
 Metadata loop file: /home/q/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.18.17-1.el6.x86_64
Operating System: <unknown>
CPUs: 4
Total Memory: 3.866 GiB
Name: l-kubecluster1.ops.cn8
ID: JKN2:X7IR:THCS:CNNU:WAQV:UFRQ:PEYC:4272:TWGK:4FTC:VMO5:STX3
Debug mode (server): false
Debug mode (client): true
Fds: 85
Goroutines: 180
System Time: Wed Sep 16 15:44:26 CST 2015
EventsListeners: 1
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/bin/docker
Docker Root Dir: /home/q/docker
WARNING: No swap limit support
```

**Comment by nancykyo** [comment]
so maybe we should use to identify the docker root.
``` docker -D info ```
instead of 
``` docker info ```

**Comment by resouer** [comment]
@nancykyo See [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L179), we are looking for `Root Dir`

In my docker 1.6.2:
```
vcap@ubuntu:~$ docker info
Containers: 8
Images: 99
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 115
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 3.861 GiB
Name: ubuntu
```
So, maybe your docker daemon is too old ...

**Comment by nancykyo** [comment]
this is my docker version 
```
docker -v
Docker version 1.6.2, build 7c8fca2
```
yes, I have test it on ubuntu, it can show the ```Root Dir```.
But on centos it can't...I mean using ```docker -D info```  instead of ```docker info``` can fix this problem

**Comment by resouer** [comment]
that make sense, I think you can send a PR to fix this :smile:

**Comment by yujuhong** [comment]
The docker remote API `/info` endpoint returns everything. It is the cli client that masks out certain info in non-debugging mode. 

kubelet uses go-dockerclient which [doesn't have the debug option](https://github.com/fsouza/go-dockerclient/blob/c9ad0ce23f68428421adfc6ced9e6123f54788a5/misc.go#L30) at all, and should print out all information including the docker root. I doubt this is the problem...

**Comment by resouer** [comment]
@yujuhong  Thanks! I opened a issue to track this: https://github.com/fsouza/go-dockerclient/issues/381
