### ISSUE TITLE
Where is the kubectl binary location? the document not said where to find it

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubernetes#14028]
I am new to kubernets. i know there be a very important binary command called kubectl.
but i am not sure where i can find it.

the document not said more about it.

actually, after build an local kubernetes, it should be location at 

```
huzhifeng@s76054 ~/vbox/k8/kubernetes (master*) $ ll _output/dockerized/bin/linux/amd64          
total 404M
-rwxr-xr-x 1 root root  29M Sep 16 02:58 e2e.test
-rwxr-xr-x 1 root root  20M Sep 16 02:57 genbashcomp
-rwxr-xr-x 1 root root  15M Sep 16 02:57 genconversion
-rwxr-xr-x 1 root root  15M Sep 16 02:57 gendeepcopy
-rwxr-xr-x 1 root root  20M Sep 16 02:57 gendocs
-rwxr-xr-x 1 root root  21M Sep 16 02:57 genman
-rwxr-xr-x 1 root root 4.7M Sep 16 02:57 genswaggertypedocs
-rwxr-xr-x 1 root root 9.1M Sep 16 02:57 ginkgo
-rwxr-xr-x 1 root root  50M Sep 16 02:57 hyperkube
-rwxr-xr-x 1 root root  49M Sep 16 02:58 integration
-rwxr-xr-x 1 root root  40M Sep 16 02:57 kube-apiserver
-rwxr-xr-x 1 root root  33M Sep 16 02:57 kube-controller-manager
-rwxr-xr-x 1 root root  20M Sep 16 02:57 kubectl
-rwxr-xr-x 1 root root  35M Sep 16 02:56 kubelet
-rwxr-xr-x 1 root root  18M Sep 16 02:56 kube-proxy
-rwxr-xr-x 1 root root  17M Sep 16 02:57 kube-scheduler
-rwxr-xr-x 1 root root 3.3M Sep 16 02:56 linkcheck
-rwxr-xr-x 1 root root 3.5M Sep 16 02:57 mungedocs
-rwxr-xr-x 1 root root 6.7M Sep 16 02:57 web-server

```

May we put this location into the guide? so we can easily put them into our PATH

cp them to /usr/bin or  ln -s path/to/kubectl /usr/bin/kubectl or  just add /path/to/kubectl to $PATH

**Comment by netroby** [comment]
You can find it in the release tar bundle, under platforms//; or if you build from source, kubectl should be either under _output/local/bin// or _output/dockerized/bin//.

The document is a bit out of date

http://kubernetes.io/v1.0/docs/user-guide/prereqs.html

The path would be  _output/dockerized/bin/linux/amd64/bin

and  ll _output/local/bin/linux/amd64/ 

The _output/local/bin/linux/amd64 directory not have kubectl

```
huzhifeng@s76054 ~/vbox/k8/kubernetes (master*) $ ll ll _output/local/bin/linux/amd64/    
ls: cannot access ll: No such file or directory
_output/local/bin/linux/amd64/:
total 145M
-rwxr-xr-x 1 huzhifeng huzhifeng 41M Sep 16 02:52 kube-apiserver
-rwxr-xr-x 1 huzhifeng huzhifeng 33M Sep 16 02:51 kube-controller-manager
-rwxr-xr-x 1 huzhifeng huzhifeng 36M Sep 16 02:51 kubelet
-rwxr-xr-x 1 huzhifeng huzhifeng 19M Sep 16 02:51 kube-proxy
-rwxr-xr-x 1 huzhifeng huzhifeng 18M Sep 16 02:51 kube-scheduler

```

**Comment by feihujiang** [comment]
You can use ./hack/local-up-cluster to build a local kubernetes cluster, and use ./hack/kubectl.sh as the CLI.

**Comment by alex-mohr** [comment]
We updated the docs at head: https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/prereqs.md
