### ISSUE TITLE
ResourceQuota somethings not working due to Quantity type mismatch

### ISSUE THREAD

**Issue by hurf** [kubernetes/kubernetes#14021]
I created a resourceQuota with the config below:

    apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: quota
    spec:
      hard:
        cpu: "2"
        memory: 4Gi
        persistentvolumeclaims: "10"
        pods: "10"
        replicationcontrollers: "20"
        resourcequotas: "1"
        secrets: "10"
        services: "5"

Then created a pod like this:

    kind: Pod
    apiVersion: v1
    spec:
        hostNetwork: false
        containers:
          - name: apache1
            image: test/apache:1
            resources:
              limits: 
                cpu: 500m
                memory: 5Gi 
    metadata:
      labels:
        tier: webserver
        type: apache2
      name: testpod5 

The pod is obviously exceeding the memory limit, but created successfully.

I looked into the code, found in [newUsage.Add(*delta)](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/resourcequota/admission.go#L242), usage is initialized with type DecimalSI, but 5Gi is recognized as BinarySI. So this time `Add` will fail and the validation will skip this 5Gi. But after the pod is created, usage will be synchronized and type changed to BinarySI, so if next time another 5Gi comes in the validation will work, but if next time a 5.1Gi comes in which will be recognized as DecimalSI the validation will be skipped again.

Giving a sequence '5Gi, 5.1Gi, 5Gi, 5.1Gi...', it will always escape from validation:-(

By adding

     if resourceName == api.ResourceMemory {
        newUsage.Format = (*delta).Format
       }

before call of `Add` can temporarily fix is problem.I'm not sure whether this is a good idea, maybe we should make some change in Quantity. But I didn't look very deep into Quantity, so @lavalamp do you have any ideas?

**Comment by hurf** [comment]
related issue #13631

**Comment by hurf** [comment]
@kubernetes/goog-control-plane

**Comment by lavalamp** [comment]
@hurf I suggest fixing resource.Quantity.Add. I'm not sure why it's so picky about the format.
