### ISSUE TITLE
[Kubernetes on CoreOs] Update documentation

### ISSUE THREAD

**Issue by ltagliamonte** [kubernetes/kubernetes#14032]
Can someone update the documentation:
```
https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/getting-started-guides/coreos/coreos_multinode_cluster.md
```
using the latest kubernets version v1.0.5 and explain how to get working the kube-ui?
I red that now is it running in a separate container i created the rc and service as explained in this issue:
```
https://github.com/kubernetes/kubernetes/issues/10697
``` 
but i was not able to expose the ui using the api-proxy-server.
Thanks for the support.

**Comment by mikedanese** [comment]
@bakins

**Comment by bakins** [comment]
@pires and/or @kelseyhightower would probably be better equipped to handle this -- or at least point you to the right person.  My knowledge is pretty dated.

**Comment by pires** [comment]
Current CoreOS documentation doesn't provide DNS or UI integration. It's in the pipe but not ready for me to put up a PR. @ltagliamonte feel free to open a PR and tag me so I can review.

**Comment by pires** [comment]
Also, see https://github.com/kubernetes/kubernetes/issues/9178

**Comment by pires** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/14387.
