### ISSUE TITLE
local-up-cluster.sh just only build few binary

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#14030]
When I updated kubernetes today, and used ./hack/local-up-cluster.sh, I found it only build cmd/kube-proxy, cmd/kube-apiserver, cmd/kube-controller-manager, cmd/kubelet, plugin/cmd/kube-scheduler. and befor it build more than those, such as, cmd/kubectl, cmd/integration, cmd/gendocs, ... etc. What's wrong with it?

**Comment by nikhiljindal** [comment]
@sghods changed it I think to speed up local-up-cluster.

**Comment by feihujiang** [comment]
If I want to other binaries  (kubectl ... etc), How can I do, which script should  I execute?

**Comment by nikhiljindal** [comment]
You can run ```/hack/build-go.sh``` to build all your binaries

**Comment by feihujiang** [comment]
@nikhiljindal  I got it, thanks.
