### ISSUE TITLE
Swagger doc for getting pod log looks wrong

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/kubernetes#14048]
The Swagger doc for /api/v1/namespaces/{namespace}/pods/{name}/log looks wrong to me.  There is no mention of how to specify for which container you want logs for.

**Comment by nikhiljindal** [comment]
There is a query param for it: https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L6044
But I see now that the spec is not updated on gh-pages and hence we do not show that param on kubernetes.io/third_party/swagger-ui
Sending a PR now to fix that.

Thanks a lot @ae6rt for pointing that out!

**Comment by nikhiljindal** [comment]
Being fixed by https://github.com/kubernetes/kubernetes/pull/14057

**Comment by ae6rt** [comment]
@nikhiljindal Thanks.  Just curious: why is the responseModel v1.Pod?  The actual response is, well, just plain text.

**Comment by nikhiljindal** [comment]
Yea sorry that seems like a bug. Filed https://github.com/kubernetes/kubernetes/issues/14071

Also, I am wondering what do you mean by "The Swagger doc". We have a few of them, wondering which one are you looking at.

**Comment by ae6rt** [comment]
I was casually referring to this:  http://kubernetes.io/third_party/swagger-ui/

I should have been more specific - sorry.

**Comment by nikhiljindal** [comment]
No problem. Thanks!

We also have https://htmlpreview.github.io/?https://github.com/GoogleCloudPlatform/kubernetes/HEAD/docs/api-reference/operations.html and https://htmlpreview.github.io/?https://github.com/GoogleCloudPlatform/kubernetes/HEAD/docs/api-reference/definitions.html which you might find useful.
