### ISSUE TITLE
Slow GCE tests are not running anywhere

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#14042]
In #13225 some tests where removed from gce suite because of being too long. There were move to a separate config:
"kubernetes-e2e-gce-slow"

However, after more than a week, the "kubernetes-e2e-gce-slow" still doesn't exist (which means we are not running those tests at all).

cc @quinton-hoole @kubernetes/goog-testing

**Comment by quinton-hoole** [comment]
Yes, my apologies - I'll complete this today.

**Comment by quinton-hoole** [comment]
Many thanks to @ixdy for getting there before me.

job/kubernetes-e2e-gce-slow/
