### ISSUE TITLE
resolv.conf ndots:5 is causing throttling issues with cloud provider DNS

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#14051]
As stated above, the choice of having ndots:5 is causing our cloud provider (Azure) to throttle our DNS requests.  It's also causing for skydns to perform pretty poorly taking seconds to respond to a query.

Below are some excerpts of what we're seeing.  To give some background, we run about a 30 nodes cluster, with most traffic generated by our backend processing which talks to various backends and stores information in elastic search.  

Queries with less than 5 dots are being tried for all search domains available and that in turn goes to our VM Cloud provider DNS service.

So a request to "api.google.com" or "api.facebook.com" or "api.twitter.com" would be tried for all search domains.

Here are some logs:

Skydns endless errors:
```
015/09/16 16:04:13 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:04:17 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:04:21 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:04:25 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:04:33 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:04:37 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:04:41 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:04:45 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:04:53 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:04:57 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:01 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:05 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:15 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:19 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:23 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:27 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:35 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:39 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:43 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:47 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:55 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:05:59 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:06:03 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
2015/09/16 16:06:13 skydns: failure to forward request "read udp 168.63.129.16:53: i/o timeout"
... Goes on forever
```

A sample of what a node with skydns pod running on it sees for traffic for port 53.  (the names themselves have been changed)

```
16:55:18.162782 IP (tos 0x0, ttl 64, id 52844, offset 0, flags [DF], proto UDP (17), length 75)
    10.244.45.0.37515 > 10.244.43.7.domain: [udp sum ok] 43591+ A? 5-4-6-app.agent.datadoghq.com. (47)
16:55:18.331576 IP (tos 0x0, ttl 64, id 24485, offset 0, flags [DF], proto UDP (17), length 108)
    10.244.23.0.36337 > 10.244.43.7.domain: [udp sum ok] 40421+ A? 5-4-6-app.agent.datadoghq.com.myazure.c5.internal.cloudapp.net. (80)
16:55:18.354145 IP (tos 0x0, ttl 64, id 22021, offset 0, flags [DF], proto UDP (17), length 83)
    10.244.26.0.57285 > 10.244.43.7.domain: [udp sum ok] 1472+ A? datadog.default.svc.ourkube.int.ourkube.int. (55)
16:55:19.878938 IP (tos 0x0, ttl 64, id 28586, offset 0, flags [DF], proto UDP (17), length 109)
    10.244.114.0.48049 > 10.244.43.7.domain: [udp sum ok] 57371+ A? apiserver.default.svc.ourkube.int.myazure.c5.internal.cloudapp.net. (81)
16:55:19.878942 IP (tos 0x0, ttl 64, id 28587, offset 0, flags [DF], proto UDP (17), length 109)
    10.244.114.0.48049 > 10.244.43.7.domain: [udp sum ok] 57495+ AAAA? apiserver.default.svc.ourkube.int.myazure.c5.internal.cloudapp.net. (81)
16:55:20.016634 IP (tos 0x0, ttl 64, id 28600, offset 0, flags [DF], proto UDP (17), length 83)
    10.244.114.0.49564 > 10.244.43.7.domain: [udp sum ok] 29917+ A? datadog.default.svc.ourkube.int.ourkube.int. (55)
16:55:20.023147 IP (tos 0x0, ttl 64, id 28601, offset 0, flags [DF], proto UDP (17), length 74)
    10.244.114.0.52224 > 10.244.43.7.domain: [udp sum ok] 11918+ A? datadog.default.svc.ourkube.int. (46)
16:55:21.654148 IP (tos 0x0, ttl 64, id 22698, offset 0, flags [DF], proto UDP (17), length 109)
    10.244.26.0.36346 > 10.244.43.7.domain: [udp sum ok] 5080+ A? apiserver.default.svc.ourkube.int.myazure.c5.internal.cloudapp.net. (81)
16:55:21.654152 IP (tos 0x0, ttl 64, id 22699, offset 0, flags [DF], proto UDP (17), length 109)
    10.244.26.0.36346 > 10.244.43.7.domain: [udp sum ok] 1692+ AAAA? apiserver.default.svc.ourkube.int.myazure.c5.internal.cloudapp.net. (81)
16:55:21.847426 IP (tos 0x0, ttl 64, id 22727, offset 0, flags [DF], proto UDP (17), length 83)
    10.244.26.0.53297 > 10.244.43.7.domain: [udp sum ok] 16393+ A? datadog.default.svc.ourkube.int.ourkube.int. (55)
16:55:21.856136 IP (tos 0x0, ttl 64, id 22731, offset 0, flags [DF], proto UDP (17), length 74)
    10.244.26.0.52944 > 10.244.43.7.domain: [udp sum ok] 27081+ A? datadog.default.svc.ourkube.int. (46)
16:55:22.452798 IP (tos 0x0, ttl 64, id 29352, offset 0, flags [DF], proto UDP (17), length 96)
    10.244.107.0.41608 > 10.244.43.7.domain: [udp sum ok] 16022+ A? 5-4-6-app.agent.datadoghq.com.default.svc.ourkube.int. (68)
16:55:22.822912 IP (tos 0x0, ttl 64, id 36307, offset 0, flags [DF], proto UDP (17), length 88)
    10.244.18.0.40918 > 10.244.43.7.domain: [udp sum ok] 8323+ A? 5-4-6-app.agent.datadoghq.com.svc.ourkube.int. (60)
16:55:23.112077 IP (tos 0x0, ttl 64, id 61406, offset 0, flags [DF], proto UDP (17), length 87)
    10.244.47.0.39810 > 10.244.43.7.domain: [udp sum ok] 32524+ A? datadog.default.svc.ourkube.int.svc.ourkube.int. (59)
16:55:24.946267 IP (tos 0x0, ttl 64, id 31290, offset 0, flags [DF], proto UDP (17), length 87)
    10.244.114.0.55361 > 10.244.43.7.domain: [udp sum ok] 22311+ A? datadog.default.svc.ourkube.int.svc.ourkube.int. (59)
16:55:24.956096 IP (tos 0x0, ttl 64, id 31291, offset 0, flags [DF], proto UDP (17), length 74)
    10.244.114.0.53977 > 10.244.43.7.domain: [udp sum ok] 35452+ A? datadog.default.svc.ourkube.int. (46)
16:55:26.066449 IP (tos 0x0, ttl 64, id 62659, offset 0, flags [DF], proto UDP (17), length 88)
    10.244.81.0.37676 > 10.244.43.7.domain: [udp sum ok] 12887+ A? 5-4-6-app.agent.datadoghq.com.svc.ourkube.int. (60)
16:55:26.608937 IP (tos 0x0, ttl 64, id 45002, offset 0, flags [DF], proto UDP (17), length 84)
    10.244.70.0.53080 > 10.244.43.7.domain: [udp sum ok] 65421+ A? 5-4-6-app.agent.datadoghq.com.ourkube.int. (56)
16:55:28.203876 IP (tos 0x0, ttl 64, id 61165, offset 0, flags [DF], proto UDP (17), length 75)
    10.244.45.0.56283 > 10.244.43.7.domain: [udp sum ok] 40909+ A? 5-4-6-app.agent.datadoghq.com. (47)
16:55:28.206431 IP (tos 0x0, ttl 64, id 3278, offset 0, flags [DF], proto UDP (17), length 108)
    10.244.34.0.42125 > 10.244.43.7.domain: [udp sum ok] 40009+ A? 5-4-6-app.agent.datadoghq.com.myazure.c5.internal.cloudapp.net. (80)
16:55:28.357157 IP (tos 0x0, ttl 64, id 24571, offset 0, flags [DF], proto UDP (17), length 107)
    10.244.26.0.52899 > 10.244.43.7.domain: [udp sum ok] 43750+ A? datadog.default.svc.ourkube.int.myazure.c5.internal.cloudapp.net. (79)
16:55:29.586411 IP (tos 0x0, ttl 64, id 61580, offset 0, flags [DF], proto UDP (17), length 97)
    10.244.47.0.33902 > 10.244.43.7.domain: [udp sum ok] 40246+ A? apiserver.default.svc.ourkube.int.default.svc.ourkube.int. (69)
16:55:29.586420 IP (tos 0x0, ttl 64, id 61581, offset 0, flags [DF], proto UDP (17), length 97)
    10.244.47.0.33902 > 10.244.43.7.domain: [udp sum ok] 40847+ AAAA? apiserver.default.svc.ourkube.int.default.svc.ourkube.int. (69)
16:55:29.786832 IP (tos 0x0, ttl 64, id 61689, offset 0, flags [DF], proto UDP (17), length 87)
    10.244.47.0.39698 > 10.244.43.7.domain: [udp sum ok] 1501+ A? datadog.default.svc.ourkube.int.svc.ourkube.int. (59)
16:55:29.796062 IP (tos 0x0, ttl 64, id 61696, offset 0, flags [DF], proto UDP (17), length 107)
    10.244.47.0.59447 > 10.244.43.7.domain: [udp sum ok] 23881+ A? datadog.default.svc.ourkube.int.myazure.c5.internal.cloudapp.net. (79)
16:55:31.315798 IP (tos 0x0, ttl 64, id 35741, offset 0, flags [DF], proto UDP (17), length 108)
    10.244.37.0.43926 > 10.244.43.7.domain: [udp sum ok] 61264+ A? 5-4-6-app.agent.datadoghq.com.myazure.c5.internal.cloudapp.net. (80)
16:55:31.527971 IP (tos 0x0, ttl 64, id 62868, offset 0, flags [DF], proto UDP (17), length 87)
    10.244.47.0.46904 > 10.244.43.7.domain: [udp sum ok] 8012+ A? datadog.default.svc.ourkube.int.svc.ourkube.int. (59)
16:55:31.872298 IP (tos 0x0, ttl 64, id 34751, offset 0, flags [DF], proto UDP (17), length 109)
    10.244.114.0.48180 > 10.244.43.7.domain: [udp sum ok] 13732+ A? apiserver.default.svc.ourkube.int.myazure.c5.internal.cloudapp.net. (81)
16:55:31.872307 IP (tos 0x0, ttl 64, id 34752, offset 0, flags [DF], proto UDP (17), length 109)
    10.244.114.0.48180 > 10.244.43.7.domain: [udp sum ok] 48767+ AAAA? apiserver.default.svc.ourkube.int.myazure.c5.internal.cloudapp.net. (81)
16:55:32.034165 IP (tos 0x0, ttl 64, id 34246, offset 0, flags [DF], proto UDP (17), length 108)
    10.244.23.0.48722 > 10.244.43.7.domain: [udp sum ok] 58177+ A? 5-4-6-app.agent.datadoghq.com.myazure.c5.internal.cloudapp.net. (80)
16:55:32.479747 IP (tos 0x0, ttl 64, id 32259, offset 0, flags [DF], proto UDP (17), length 96)
    10.244.107.0.33647 > 10.244.43.7.domain: [udp sum ok] 45114+ A? 5-4-6-app.agent.datadoghq.com.default.svc.ourkube.int. (68)
16:55:32.729386 IP (tos 0x0, ttl 64, id 37304, offset 0, flags [DF], proto UDP (17), length 84)
    10.244.55.0.50637 > 10.244.43.7.domain: [udp sum ok] 20134+ A? 5-4-6-app.agent.datadoghq.com.ourkube.int. (56)
16:55:32.852405 IP (tos 0x0, ttl 64, id 45484, offset 0, flags [DF], proto UDP (17), length 88)
    10.244.18.0.50767 > 10.244.43.7.domain: [udp sum ok] 64673+ A? 5-4-6-app.agent.datadoghq.com.svc.ourkube.int. (60)
16:55:32.883353 IP (tos 0x0, ttl 64, id 35316, offset 0, flags [DF], proto UDP (17), length 95)
    10.244.114.0.44580 > 10.244.43.7.domain: [udp sum ok] 36252+ A? datadog.default.svc.ourkube.int.default.svc.ourkube.int. (67)
16:55:32.894769 IP (tos 0x0, ttl 64, id 35322, offset 0, flags [DF], proto UDP (17), length 74)
    10.244.114.0.54927 > 10.244.43.7.domain: [udp sum ok] 47316+ A? datadog.default.svc.ourkube.int. (46)
16:55:33.110903 IP (tos 0x0, ttl 64, id 64246, offset 0, flags [DF], proto UDP (17), length 95)
    10.244.47.0.58649 > 10.244.43.7.domain: [udp sum ok] 24843+ A? datadog.default.svc.ourkube.int.default.svc.ourkube.int. (67)
16:55:33.118818 IP (tos 0x0, ttl 64, id 64253, offset 0, flags [DF], proto UDP (17), length 107)
    10.244.47.0.35066 > 10.244.43.7.domain: [udp sum ok] 36011+ A? datadog.default.svc.ourkube.int.myazure.c5.internal.cloudapp.net. (79)
```

and finally and attempt at rating our QPS (per @thockin):
```
# tcpdump -i any -n udp dst port 53 | grep "packets received" & sleep 10; kill %1
...
95 packets captured
99 packets received by filter
0 packets dropped by kernel
```

Which seems pretty low for any issue to happen...

cc @thockin

**Comment by thockin** [comment]
Thanks for bringing it here from IRC.  So many questions.

Background for the record:

Without ndots >= 2, DNS lookups like 'mysvc.myns' can't work (e.g.
kubernetes.default)

Without ndots >= 3, DNS lookups like 'mysvc.myns.svc' can't work (important
once pod DNS lands).

Once you set ndots to 2 (or higher) all queries like 'google.com' become
eligible for search-path expansion - cause several times more DNS queries
than  without.

That said, 99 over 10 seconds is nothing.  It's a pittance.  I have thrown
thousands of QPS at skyDNS and still have latency < 200ms.  Something else
is up.

Are you sure that the i/o timeout  is throttling related?  Are there docs
on what Azure supports for DNS rate?  You could try a simple load-test

```
DNS=10.0.0.10;
for i in `seq 1 10`; do
    QPS=$((i*10));
    echo "sending approx $QPS QPS to $DNS";
    GOT=$(
        for i in `seq 1 $QPS`; do
            dig +noall +short +answer +time=1 +retry=0 @$DNS google.com |
head -1;
        done | wc -l);
    echo got $GOT responses;
    sleep 1;
done
```

We've seen some issues with kube-proxy memory consumption impacting DNS -
you might try restarting kube-proxy (as a data point, not a solution).

If we actually find DNS to be an issue we have a couple mitigations we
might take.

First, we're looking at moving DNS onto each node, so load would be shared
and cached close-to-consumers.  Between now and then, one could run dnsmasq
on your nodes and point kubelet at that DNS server.

But I don't think your problem is actually about load, because 10 QPS is
not load - it's noise :)

On Wed, Sep 16, 2015 at 10:02 AM, Daniel Schonfeld <notifications@github.com

**Comment by thockin** [comment]
@artfulcoder

**Comment by danielschonfeld** [comment]
Update which might "exonerate" the ndots option.

Removing the health probe check utilizing healthz stops the timeout errors reported by skydns trying to connect to the upstream DNS server.

So now i'm not entirely sure what to say next...

**Comment by thockin** [comment]
...but you still see long latency, right?

On Wed, Sep 16, 2015 at 10:32 AM, Daniel Schonfeld <notifications@github.com

**Comment by danielschonfeld** [comment]
@thockin when I say i see skydns taking long to response, I mean that to my eyes when i run
```
$ kubectl --namespace=kube-system exec -i -t kube-dns-v9sr1-5l1uu -c skydns -- nslookup datadog.default.svc.mykube.int localhost
```

It takes about 10 seconds to response which is outrageous.

I should note however, that none of my services which are 'enjoying' skydns are complaining.  And I should note that i've just figured out that those timeout issue occur, whenever I run that nslookup command manually, which happens to be the same thing the health probe did.

So this is def related to the way nslookup does things.  And the recurrence was obviously from the health probe continuously running that command.

**Comment by danielschonfeld** [comment]
When I run nslookup on a system that does not have the ndots set tho, it responds in a fraction of a second utilizing that skydns service as my DNS querying server.

In other words, the presence of ndots:5 option inside the healthz/skydns/etcd and every other pod, could still be the reason for this slow response when utilizing nslookup

**Comment by thockin** [comment]
On Wed, Sep 16, 2015 at 10:39 AM, Daniel Schonfeld
<notifications@github.com> wrote:
>
> @thockin when I say i see skydns taking long to response, I mean that to my eyes when i run
>
> $ kubectl --namespace=kube-system exec -i -t kube-dns-v9sr1-5l1uu -c skydns -- nslookup datadog.default.svc.mykube.int localhost
>
> It takes about 10 seconds to response which is outrageous.

agree outrageous.

Sanity check: what is the dnsPolicy setting on your kube-dns pod?

also, what is v9sr1 - some pathes on top of the standard DNS (which is
currently v9)?

> I should note however, that none of my services which are 'enjoying' skydns are complaining. And I should note that i've just figured out that those timeout issue occur, whenever I run that nslookup command manually, which happens to be the same thing the health probe did.
>
> So this is def related to the way nslookup does things. And the recurrence was obviously from the health probe continuously running that command.

from my GCE cluster:

```
$ kubectl --namespace=kube-system exec -i -t kube-dns-v9-xv0lm -c
skydns -- time nslookup kubernetes.default.svc.cluster.local localhost
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      kubernetes.default.svc.cluster.local
Address 1: 10.0.0.1
real 0m 0.00s
user 0m 0.00s
sys 0m 0.00s
```

**Comment by danielschonfeld** [comment]
@thockin:

dnsPolicy is default and to verify:
```
$ kubectl --namespace=kube-system get rc -o yaml                                                             
apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    creationTimestamp: 2015-09-16T17:42:40Z
    generation: 11
    labels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      version: v9sr
    name: kube-dns-v9sr
    namespace: kube-system
    resourceVersion: "1452930"
    selfLink: /api/v1/namespaces/kube-system/replicationcontrollers/kube-dns-v9sr
    uid: 53f31298-5c9a-11e5-9617-000d3a00d50c
  spec:
    replicas: 10
    selector:
      k8s-app: kube-dns
      version: v9sr
    template:
      metadata:
        creationTimestamp: null
        labels:
          k8s-app: kube-dns
          kubernetes.io/cluster-service: "true"
          version: v9sr
      spec:
        containers:
        - command:
          - /usr/local/bin/etcd
          - -data-dir
          - /var/etcd/data
          - -listen-client-urls
          - http://127.0.0.1:2379,http://127.0.0.1:4001
          - -advertise-client-urls
          - http://127.0.0.1:2379,http://127.0.0.1:4001
          - -initial-cluster-token
          - skydns-etcd
          image: gcr.io/google_containers/etcd:2.0.9
          imagePullPolicy: IfNotPresent
          name: etcd
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/etcd/data
            name: etcd-storage
        - args:
          - -domain=mykube.int
          image: gcr.io/google_containers/kube2sky:1.11
          imagePullPolicy: IfNotPresent
          name: kube2sky
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
        - args:
          - -machines=http://localhost:4001
          - -addr=0.0.0.0:53
          - -domain=mykube.int.
          - -rcache=10000
          image: gcr.io/google_containers/skydns:2015-03-11-001
          imagePullPolicy: IfNotPresent
          name: skydns
          ports:
          - containerPort: 53
            name: dns
            protocol: UDP
          - containerPort: 53
            name: dns-tcp
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: Default
        restartPolicy: Always
        volumes:
        - emptyDir: {}
          name: etcd-storage
  status:
    observedGeneration: 11
    replicas: 10
kind: List
metadata: {}
```

the additional characters on top of v9 is for my own benefit since i had to do a rolling-update today to try various things as this is a live in use cluster and i didn't want to stay for a second without DNS resolving for my pods.

and finally, from my azure cluster:
```
$ kubectl --namespace=kube-system exec -i -t kube-dns-v9sr-8e8q0 -c skydns -- time nslookup kubernetes.default.svc.mykube.int localhost
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      kubernetes.default.svc.mykube.int
Address 1: 10.101.0.1
real	0m 20.00s
user	0m 0.00s
sys	0m 0.00s
```

**Comment by danielschonfeld** [comment]
And just to add one more note... all of these pods including the one i just quoted with the exec command, have been restarted today and showed the same time taking for nslookup to complete from the first 5 seconds they were started.

**Comment by thockin** [comment]
Weird.  There's CLEARLY a 20 second timeout on something.  Sadly there are
not many debug tools available in busybox.  If you're willing to dig
further (since I can not repro it), add a new container to this pod with
image "debian:wheezy" and command bash -c "while true; do sleep 1000000;
done", and update to this.

Then you can kubectl exec into that and run 'strace nslookup...` and see
what the heck is going on, or even tcpdump...

On Wed, Sep 16, 2015 at 12:58 PM, Daniel Schonfeld <notifications@github.com

**Comment by danielschonfeld** [comment]
I'm confused now... i just set up a 'testbox' with ubuntu on it.  Installed strace and nslookup and nslookup alone takes like a fraction of a second.

Yet when I continue executing thru skydns it takes 20 seconds...

**Comment by danielschonfeld** [comment]
Another interesting thing to note is that we run a zookeeper 3 POD cluster on our kubernetes cluster.  When I use zkCli to connect and subsequently `ls /` it takes a good 5-10 seconds to respond when utilizing the service DNS name as the argument given to `-server`... so `zkCli -server zookeeper-1`

When using the `Service` IP tho, it connects in a fraction of a second and so does `ls /`

**Comment by danielschonfeld** [comment]
I think i have pinpointed something.  Whenever i run `nslookup` on a busy box based image (i.e. skydns,busy box itself etc) it takes 20 seconds.  Whenever I run `nslookup` inside a pod on an ubuntu based image, it takes a fraction of a second.  Exactly like the results you get on your GCE cluster.

cc @thockin

**Comment by danielschonfeld** [comment]
cc @thockin - I apologize for bombarding but we are continuing to investigate here and we got some more insights that pretty much pin down all the different notes we've taken throughout the day.

1) zookeeper issues: are not really related to skydns, or kubernetes.  - when using hostname to connect to zookeeper, it does a reverse DNS lookup on the name.  Since kube2sky doesn't register arpa.in-addr in etcd for the entries it makes, zookeeper therefore fails.  This is probably something you'd want to change, in fact i'm probably gonna make a pull request shortly after submitting this comment.  The lack of reverse DNS entries not only affects zookeeper when using it in zkCli, but also when using the java libs like curator to connect to zookeeper.

2) As I said above, the `nslookup` taking 20 seconds and upwards to resolve seems to be a busy box based images only.  At least as compared to ubuntu vs busy box.

**Comment by thockin** [comment]
About reverse DNS - what is it reverse DNS'ing?  The IP of a client that
connected to it, or the IP of the Service?  I don't see what reversing the
IP of the Service would tell you, but I guess I would have no problem doing
PTR records for that.  We will soon have forward records for pods, but not
reverse.  There was a reson we chose not to do reverse for pods, but it
escapes me just now.

As for busybox, I ... uhh... I have no idea what to say.  Obviously it
doesn't repro here.

What if you run an ubuntu or debian container, exec into that and then run
'busybox sh' and try?

**Comment by danielschonfeld** [comment]
@thockin I haven't delved into the ZK code deep enough but there are several bugs about it, here's an example of one (don't be fooled by it showing closed, or the version.... there's already a dupe in an up and current version) https://issues.apache.org/jira/browse/ZOOKEEPER-1652

As for busy box within ubuntu.... it works flawlessly.  And so does the busy box in which skydns is in now :8ball:  

I guess we can closet his bug as this was probably something in my own cluster and network tho the reverse DNS entries should probably be thought about.

The way it worked for me with zookeeper is doing
`etcdctl set /skydns/arpa/in-addr/10/101/1/1 '{"host":"zookeeper-1.default.svc.mykube.int"}'`

**Comment by thockin** [comment]
About reverse DNS:

I am trying to figure out what zk is going to DO with the information.  In other words, if I connect to it from 1.2.3.4 and it does a PTR lookup and gets back "1-2-3-4.ns.pod.cluster.local", what is it going to use "1-2-3-4.ns.pod.cluster.local" for?  Is it going to connect back to that?  Is it going to look it up in a list of allowed clients?  Is it going to regex it?

We could add PTR lookups for pod DNS, but we didn't want to for a couple reasons:

1) Eventually we'll have "nominal sets" which, if your pod is part of one, will change the reverse lookup (instead of 1-2-3-4.ns.pod.cluster.local you might get "replica3.myset.nom.cluster.local").  Changing this might be considered a breaking change if we already did PTR.

2) We don't really know what people are expecting from reverse lookups, and we don't want to add features we don't understand

If you can help us understand it, we might be one step closer to doing it :)

I'll close this for now (unsatisfied, but can not repro).  Discussion on PTR can go in #13552 or #13759 - @stevesloka FYI
