### ISSUE TITLE
Setting resources.requests in pod template breaks updates of resources.limits

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14050]
Thought of this while hashing out #12823.

Luckily, pod resources are not yet updatable #5774.

However, they are in pod templates.

Scenario: User sets limits in ReplicationController template. Later, user does a get, modifies limits, and then put. They changed limit but not request. Boom.

My proposal is that we don't default request from limit in pod templates and that we just do it in pods. LimitRange also just applies to pods. The fields are not updatable in pods, so not a problem there.

I'm sure what the best way is to handle this in the defaulting pass. We might need to copy the Go struct type for ResourceRequirements.
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/defaults.go#L168

cc @davidopp @derekwaynecarr @vishh

**Comment by derekwaynecarr** [comment]
I will need to try this out to make sure I understand the scenario well enough.

|| Action || Result ||
| User creates RC whose pod template has limits set | pod template limits set, requests default to limits. |
| User modified pod template to change limits | pod template limits no longer matches requests. |

I would expect that if limits is less than requests, we error.

I would not expect for limits to continue to match requests.  

Shouldn't I have the ability to modify my pod template from being a guaranteed qos for that resource to become a burstable qos?

Not sure I get the severity of the issue.

**Comment by bgrant0607** [comment]
In 1.0, users/clients were able to update limits without error. Those updates will now (potentially) break, for instance in the case where the new limits are less than the old limits.

**Comment by bgrant0607** [comment]
And even in the where limits were increased, that wouldn't affect scheduling, if that's what the user intended.

**Comment by bgrant0607** [comment]
@derekwaynecarr Did you have any other questions about this issue? Do you have time to work on it?

**Comment by derekwaynecarr** [comment]
Assign to me and I will take a look Monday.

**Comment by HaiyangDING** [comment]
CC @HaiyangDING

**Comment by derekwaynecarr** [comment]
I had to get an unexpected knee xray today.  Will look tomorrow when I have
more time.

**Comment by derekwaynecarr** [comment]
I think an option to do this is to move the defaulting code logic into a defaulting function for a Pod instead of what we have right now is a defaulting function for a ResourceRequirement.  In this manner, the ReplicationController pod template would not be affected.

I will hack something together to see if it works.

**Comment by bgrant0607** [comment]
Thanks.
