### ISSUE TITLE
Kubeconfig file: Verification needs to be more stringent.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#14065]
I found recently that, when spinning a kubelet up with a kubeconfig file, subtle differences in file format may lead to failed authorization.  

We should probably verify that there aren't empty/incomplete/unprocessed fields in the kubeconfig on startup.

```
-       token:kubelet
+  token: kubelet
```

is enough to break kubelet startup if sending a tokens file for auth.  the error message you get is "server needs credentials from client".

**Comment by jayunit100** [comment]
#13978 <- discovered in the work stream on this pr

**Comment by kargakis** [comment]
@kubernetes/sig-auth-misc who owns kubeconfig?

**Comment by liggitt** [comment]
the kubeconfig format uses API object encoding/decoding owned by @kubernetes/sig-api-machinery-misc
