### ISSUE TITLE
flaky e2e: Kubectl client Kubectl expose should create services for rc

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#14078]
Seems to be failing on ~10% of PRs:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/8733/testReport/junit/%28root%29/Kubernetes%20e2e%20suite/Kubectl_client_Kubectl_expose_should_create_services_for_rc/history/?start=75

Appears to wait < 1 second for the command to succeed, e.g.
06:05:15 STEP: exposing RC
06:05:15 Sep 16 06:03:59.693: INFO: Running '/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.153.46 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config expose rc redis-master --name=rm2 --port=1234 --target-port=6379 --namespace=e2e-tests-kubectl-pwnje'
06:05:15 Sep 16 06:03:59.923: INFO: service "rm2" exposed
06:05:15 
06:05:15 Sep 16 06:04:04.928: INFO: Service rm2 in namespace e2e-tests-kubectl-pwnje found.
06:05:15 Sep 16 06:04:04.930: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:04:09.983: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:04:14.997: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:04:20.000: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:04:25.004: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:04:30.007: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:04:35.017: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:04:40.394: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:04:45.397: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:04:50.400: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:04:55.413: INFO: No endpoint found, retrying
06:05:15 Sep 16 06:05:00.450: INFO: No endpoint found, retrying
06:05:15 [AfterEach] Kubectl client
06:05:15   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:85
06:05:15 STEP: Destroying namespace for this suite e2e-tests-kubectl-pwnje
06:05:15 
06:05:15 
06:05:15 • Failure [102.315 seconds]
06:05:15 Kubectl client
06:05:15 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:663
06:05:15   Kubectl expose
06:05:15   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:424

**Comment by alex-mohr** [comment]
@jlowdermilk Someone on kubectl team to investigate and fix up?

**Comment by jlowdermilk** [comment]
Create timeout(s) probably needs some adjusting. Looking into it.

**Comment by quinton-hoole** [comment]
I'd suggest that we leave this one open to track debugging of the failures.  Declaring it flaky doesn't fix the problem :-)

**Comment by jlowdermilk** [comment]
Fair enough. Note that it's only flaky when run in parallel. The [non-parallel test runs](http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/8511/testReport/(root)/Kubernetes%20e2e%20suite/Kubectl_client_Kubectl_expose_should_create_services_for_rc/history/) are 100% green. Reprioritizing accordingly.

**Comment by jlowdermilk** [comment]
After re-adding to parallel suite, this has been [100% stable](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/9118/testReport/(root)/Kubernetes%20e2e%20suite/Kubectl_client_Kubectl_expose_should_create_services_for_rc/history/)
