### ISSUE TITLE
e2e timed out: unclear reason

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#14073]
Unclear to me why this build timed out based on the logs.  Is the reason obvious to a testing expert, or is there something we can add to logs that would help us figure it out?

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/8789/consoleFull

10:01:23 STEP: Successfully fetched pod logs:[/ep-2 override arguments]
10:01:23 
10:01:23 
10:01:23 [AfterEach] Docker Containers
10:01:23   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/docker_containers.go:45
10:01:23 
10:01:23 
10:01:23 • [SLOW TEST:30.071 seconds]
10:01:23 Docker Containers
10:01:23 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/docker_containers.go:82
10:01:23   should be able to override the image's default command and arguments
10:01:23   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/docker_containers.go:81
10:01:23 ------------------------------
10:26:27 Build timed out (after 45 minutes). Marking the build as aborted.
10:26:27 Build timed out (after 45 minutes). Marking the build as failed.
10:26:27 
10:26:27 Build was aborted

**Comment by soltysh** [comment]
I'm experiencing exactly the same behavior in #13259:
```
• [SLOW TEST:50.104 seconds]
Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1037
  should provide secure master service
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:78
------------------------------
Build timed out (after 45 minutes). Marking the build as aborted.
Build timed out (after 45 minutes). Marking the build as failed.
Build was aborted
Recording test results
```

**Comment by soltysh** [comment]
I think this issue is somehow connected with #13485, or even a dupe.

**Comment by alex-mohr** [comment]
@soltysh thanks, yes, dupe of #13485
