### ISSUE TITLE
flaky e2e: ExitError in Services should be able to create a functioning external load balancer with user-provided load balancer ip 

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#14084]
Only seen one instance in today's triage:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8500/consoleFull
14:12:26 STEP: Destroying namespace "e2e-tests-services-trg37" for this suite.
14:12:31 [AfterEach] Services
14:12:31   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:72
14:12:31 STEP: Destroying namespace e2e-tests-service-0-q7zfj
14:12:36 STEP: Destroying namespace e2e-tests-service-1-ebqfp
14:12:41 
14:12:41 • Failure [67.707 seconds]
14:12:41 Services
14:12:41 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1037
14:12:41   should be able to create a functioning external load balancer with user-provided load balancer ip [It]
14:12:41   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:489
14:12:41 
14:12:41   Expected error:
14:12:41       <*exec.ExitError | 0xc2085c5230>: {
14:12:41           ProcessState: {
14:12:41               pid: 23291,
14:12:41               status: 256,
14:12:41               rusage: {
14:12:41                   Utime: {Sec: 0, Usec: 508000},
14:12:41                   Stime: {Sec: 0, Usec: 88000},
14:12:41                   Maxrss: 45448,
14:12:41                   Ixrss: 0,
14:12:41                   Idrss: 0,
14:12:41                   Isrss: 0,
14:12:41                   Minflt: 22370,
14:12:41                   Majflt: 0,
14:12:41                   Nswap: 0,
14:12:41                   Inblock: 0,
14:12:41                   Oublock: 56,
14:12:41                   Msgsnd: 0,
14:12:41                   Msgrcv: 0,
14:12:41                   Nsignals: 0,
14:12:41                   Nvcsw: 73,
14:12:41                   Nivcsw: 32,
14:12:41               },
14:12:41           },
14:12:41       }
14:12:41       exit status 1
14:12:41   not to have occurred
14:12:41 
14:12:41   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:450

**Comment by caesarxuchao** [comment]
Couldn't reproduce this flake. #14839 add more outputs in hope that we can gather more info if this flake occurs again.
