### ISSUE TITLE
Surface versioned swagger-spec on gh-pages

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#14089]
Right now, we surface the latest spec from HEAD on gh-pages at http://kubernetes.io/swagger-spec/, and the corresponding swagger-ui on http://kubernetes.io/third_party/swagger-ui/.

We should also surface the versioned spec: for ex: http://kubernetes.io/{kube-release-version}/swagger-spec and http://kubernetes.io/{kube-release-version}/swagger-ui.

Based on conversation: https://github.com/kubernetes/kubernetes/pull/14057#issuecomment-140928328

cc @lavalamp @bgrant0607 @brendandburns @caesarxuchao

**Comment by bgrant0607** [comment]
It's not clear the swagger UI is needed since we have the autogenerated docs. Maybe we could eliminate it. WDYT?

Versioning the swagger spec seems useful, though.

**Comment by nikhiljindal** [comment]
Summarized the list of things we need to do before we can eliminate swagger-ui here: https://github.com/kubernetes/kubernetes/issues/15915

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is not covered by other issues.
