### ISSUE TITLE
Use docker's DnsOptions feature

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#14082]
We can get rid of our resolv.conf `ndots` hack with docker 1.9+

@ArtfulCoder

**Comment by bprashanth** [comment]
The node team recently revved to 1.9, but I'm punting this to next-release given that we're all currently working on things

**Comment by thockin** [comment]
I don't think we should do this.  What we have works well enough and is safer (we control the vertical and the horizontal)
