### ISSUE TITLE
iptables multiplying as services growing

### ISSUE THREAD

**Issue by nancykyo** [kubernetes/kubernetes#14099]
this is  not bug, just confused about the design of NodePort & service.

> NodePort: use a cluster IP, but also expose the service on a port on each node of the cluster (the same port on each node)

So the number of iptables rules for all Service Node will be several times the number of services (2 NAT + 2 REDIRECT at least).
However, in actual use, my use case is one of a web server just work as Front End Service for one BackEnd Service out of the cluster.
As a result, the unnecessary iptables and environment variables is kind of wasting resources.

now we have 1152 services, when I check on one machine.

```
[root@l-kubecluster32.ops.cn1 ~]# iptables-save|wc -l
9508
```

sometimes I got the error log in kube-proxy, and have to restart the kube-proxy.

```
E0917 16:18:36.027613   17145 proxier.go:248] Failed to ensure portal for "default/packetix-539:http": error checking rule: fork/exec /sbin/iptables-save: too many open files
```

**Comment by nancykyo** [comment]
@thockin

**Comment by hurf** [comment]
@jiangyaoguo

**Comment by alfred-huangjian** [comment]
We have also considered about the scenario when there are more than thousands of services. But we really did't formerly do real performance test and doesn't build such a large real environment.

#13500 Here is some discussion before.
@tsjsdbd @hw-qiaolei

**Comment by thockin** [comment]
Is this with the userspace proxy or the iptables proxy?

I created 1000 Services and here's what I see:

iptables proxy:
```
root@kubernetes-minion-0n4h:/home/thockin# iptables-save | wc -l
22112

root@kubernetes-minion-0n4h:/home/thockin# ps auxw | head -1
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND

root@kubernetes-minion-0n4h:/home/thockin# ps auxw | grep kube-proxy
root     11948  0.2  1.9 138696 74792 ?        Sl   Sep15   6:07 /usr/local/bin/kube-proxy --master=https://kubernetes-master --kubeconfig=/var/lib/kube-proxy/kubeconfig --v=4 --legacy-userspace-proxy=false

root@kubernetes-minion-0n4h:/home/thockin# ls -l /proc/11948/fd | wc -l
10

root@kubernetes-minion-0n4h:/home/thockin# time nslookup kubernetes.default.svc.cluster.local 10.0.0.10
Server:		10.0.0.10
Address:	10.0.0.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.0.0.1


real	0m0.016s
user	0m0.004s
sys	0m0.000s
```
Memory usage is a little high (74 MB) but not out of line with expectations.

For the userspace proxier I had to set the `--iptables-sync-period` flag to `30s` or else it can not fill the table fast enough (yuck), but i see:

```
root@kubernetes-minion-gn8a:/home/thockin# iptables-save | grep PORTAL.*REDIR | wc -l
1011

root@kubernetes-minion-gn8a:/home/thockin# ps auxw | head -1
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND

root@kubernetes-minion-gn8a:/home/thockin# ps auxw | grep kube-proxy
root       452  5.8  1.7 132124 67964 ?        Sl   16:29   0:16 /usr/local/bin/kube-proxy --master=https://kubernetes-master --kubeconfig=/var/lib/kube-proxy/kubeconfig --v=4 --iptables-sync-period=30s

root@kubernetes-minion-gn8a:/home/thockin# ls -l /proc/452/fd | wc -l
1025

root@kubernetes-minion-gn8a:/home/thockin# time nslookup kubernetes.default.svc.cluster.local 10.0.0.10
Server:		10.0.0.10
Address:	10.0.0.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.0.0.1


real	0m0.640s
user	0m0.004s
sys	0m0.000s
```

**Comment by thockin** [comment]
Also, can you see what ulimits are in your case?  Specifically the number of FDs - cat /proc/(pid)/limits.

**Comment by feiskyer** [comment]
@thockin Could kubernetes add something like "this pod consumed services A and B"? So kube-proxy only needs to create rules of consumed services, not all rules of all services.

**Comment by thockin** [comment]
This is something we have considered for a long time, and it has some nice
properties,and some downsides.  That said, I don't think it optimized the
way you want because it has to be opt-in - anything else would be a
seriously breaking change and would also make valid cases (where we dont
actually know the deps ahead of time) impossible.

**Comment by thockin** [comment]
@nancykyo any updates here?

**Comment by nancykyo** [comment]
@thockin we're going to have 8000 services about 40k containers, seems there gonna be more than 176896 iptables on each node? worried about its performance. maybe I need to divide it into several k8s cluster?

**Comment by thockin** [comment]
Two things come to mind:

First, the largest clusters we've done so far are 1000 nodes with 30 pods
per node, and we weren't quite satisfied with the tail latency on that, so
at 40k you're already in "unsupported land".  That said, tell us how it
goes - we want to know!

Second, yeah, that's a lot of iptables, but the vast majority of those
rules will never be evaluated for each packet.  The longest  segment (by
far) is the first "is this a service IP" which is a linear search.  we had
talked about implementing it as a binary tree but didn't do it yet.

It should be pretty simple to use some heuristic like `if len(sevices) < 64
{ doLinear(services) } else { doBinaryTree(services) }`. This is a place
community could help implement, or you can try it out and wait for us to
get to it.

Tim
