### ISSUE TITLE
Building Kubernetes master fails

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#14104]
Checked out a fresh copy of master and building it gives:

```
# k8s.io/kubernetes/cmd/hyperkube
/usr/src/go/pkg/tool/linux_amd64/6l: running gcc failed: Cannot allocate memory
!!! Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:388
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${goldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:388 kube::golang::build_binaries_for_platform(...)
  2: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:523 kube::golang::build_binaries(...)
  3: hack/build-cross.sh:28 main(...)
Exiting with status 1
```

#11119 discusses this.

If more memory is required then `--virtualbox-memory "2048"` or whatever the required number is, should be used while creating the Docker Machine.

**Comment by alex-mohr** [comment]
Thanks for the report.  

Unfortunately, I don't think it has enough detail to be actionable.  We regularly build fresh copies of the master and it works, so perhaps you can include more details about your particular setup and provide exact repro steps?

See e.g. https://github.com/kubernetes/kubernetes/blob/master/docs/troubleshooting.md and the text ```If filing a bug, please include detailed information about how to reproduce the problem, such as:

Kubernetes version: kubectl version
Cloud provider, OS distro, network configuration, and Docker version
Steps to reproduce the problem```

Feel free to re-open with that info added!
