### ISSUE TITLE
iptables kube-proxy memory usage is high

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#14118]
I see about 74 MB RSS for 1000 services with 5 endpoints each (same 5).  We should try to drive this down quite a bit.

**Comment by pmorie** [comment]
@kubernetes/rh-scalability

**Comment by jijun2** [comment]
@thockin , Can you assigne me do some simple things of proxy/service ? I want to  join k8s development.

**Comment by jayunit100** [comment]
The pending networking service soak is meant to surface this #9052 ... We can try to add regression assertions to that ( for large port numbers) if there is a clear fix in sight

**Comment by thockin** [comment]
@jijun2 sure!  This is an interesting starting point.  Bring up a cluster with the iptables kube-proxy (ask if you need details :), then launch 3 pods (kubectl run hostnames --image=gcr.io/google_containers/serve_hostname --replicas=3), then expose it as a bunch of services (for i in $(seq 1 500); do kubectl expose rc hostnames --port 80 --target-port 9376 --name hostnames-$i; done).

Now look at the memory usage of kube-proxy on a node.  Now run a memory profile against it (google how to do profiling for Go apps - it's good reading :)

Now, see if there is a good explanation for the memory usage or if there are obvious places we can optimize.

**Comment by jijun2** [comment]
@thockin ,Thank you! Let me try.

**Comment by jijun2** [comment]
@thockin ,I have started up  example, and try to use memory profile. I confused how kube-proxy works ? and use a simple case , 
$./kubectl run hostnames --image=gcr.io/google_containers/serve_hostname --replicas=3
$./kubectl expose rc hostnames --port 80 --target-port 9376 --name hostnames-1
$curl http://vip:80
$iptables -t nat -L -n 
I check iptable rules has not changed all the time, 
The iptable rules exactly blank, when use ? how works ?

**Comment by thockin** [comment]
iptables requires that you be root

**Comment by jijun2** [comment]
@thockin , I use root account. Maybe DNAT iptables rules will be dynamic use and delete. 
I encountered a problem , how to do profiling for kube-proxy? 
Where to add  memory profile code in cmd/kube-proxy/proxy.go function main() ?    

       f, err := os.Create(*memprofile)
        if err != nil {
            log.Fatal(err)
        }
        pprof.WriteHeapProfile(f)

**Comment by jijun2** [comment]
@thockin , I have got memory profile. But  cpu profile is error


[root@centos-2 ~]# cd /opt/kubernetes/bin/
[root@centos-2 bin]# go tool pprof kube-proxy /tmp/kube-proxy.prof 
Entering interactive mode (type "help" for commands)
(pprof) top
panic: runtime error: index out of range

goroutine 1 [running]:
cmd/pprof/internal/driver.sampleFormat(0xc2080701c0, 0xc208096300, 0xc2080c4b40, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/cmd/pprof/internal/driver/driver.go:975 +0x21c
cmd/pprof/internal/driver.generate(0xc208070101, 0xc2080701c0, 0x7f2e8f562e18, 0xc20802afe0, 0x7f2e8f562dd0, 0xc208038060, 0xc208096300, 0x0, 0x0)
	/usr/lib/golang/src/cmd/pprof/internal/driver/driver.go:1012 +0x11f
cmd/pprof/internal/driver.generateReport(0xc2080700e0, 0xc2080c4aa0, 0x1, 0x1, 0x7f2e8f562e18, 0xc20802afe0, 0x7f2e8f562dd0, 0xc208038060, 0xc208096000, 0x0, ...)
	/usr/lib/golang/src/cmd/pprof/internal/driver/interactive.go:133 +0x11e
cmd/pprof/internal/driver.interactive(0xc2080700e0, 0x7f2e8f562e18, 0xc20802afe0, 0x7f2e8f562dd0, 0xc208038060, 0xc208096000, 0x0, 0x0)
	/usr/lib/golang/src/cmd/pprof/internal/driver/interactive.go:99 +0x586
cmd/pprof/internal/driver.PProf(0x7f2e8f562e58, 0xae1e60, 0x96b7a8, 0x96bd70, 0x7f2e8f562e18, 0xc20802afe0, 0x7f2e8f562dd0, 0xc208038060, 0x0, 0x0, ...)
	/usr/lib/golang/src/cmd/pprof/internal/driver/driver.go:112 +0xc24
main.main()
	/usr/lib/golang/src/cmd/pprof/pprof.go:28 +0x129

**Comment by thockin** [comment]
You should not need to modify the code at all.  Just expose your kube-proxy
on an accessible port and run `go tool pprof
http://host:port/debug/pprof/heap`.
You probably should use the --healthz-bind-address=0.0.0.0 and
--healthz-port=80 flags

**Comment by jijun2** [comment]
@thockin , Where the "--healthz" flags add to ? Can you have some more details ? thanks.

**Comment by thockin** [comment]
kube-proxy should have those flags  try kube-proxy -? on a node.

**Comment by jijun2** [comment]
@thockin , Great!

**Comment by ArtfulCoder** [comment]
svc count | alloc  | total alloc
--------| ------------ | ---------
1 svc | takes 5 mb |
 500 svc | takes 15 mb | 
 1000 svc | takes 22 mb | 

I see a footprint of 20 kb per service (Based on Alloc, not TotalAlloc)

--------- 1 svc below --------------

 runtime.MemStats
 Alloc = 5,210,368
 TotalAlloc = 72468549768
 Sys = 59623672
 Lookups = 177768
 Mallocs = 898458525
 Frees = 898386359
 HeapAlloc = 5210368
 HeapSys = 53870592
 HeapIdle = 46637056
 HeapInuse = 7233536
 HeapReleased = 44335104
 HeapObjects = 72166
 Stack = 655360 / 655360
 MSpan = 87248 / 262144
 MCache = 2416 / 16384
 BuckHashSys = 2537904
 NextGC = 6458478


----- Stats for 500 services (against 3 endpoints)  --------
# runtime.MemStats
# Alloc = 12,017,176
# TotalAlloc = 136024492560
# Sys = 60147960
# Lookups = 340199
# Mallocs = 1677652447
# Frees = 1677427185
# HeapAlloc = 12017176
# HeapSys = 53936128
# HeapIdle = 38715392
# HeapInuse = 15220736
# HeapReleased = 26673152
# HeapObjects = 225262
# Stack = 589824 / 589824
# MSpan = 175504 / 262144
# MCache = 2416 / 16384
# BuckHashSys = 2872640
# NextGC = 13357281

------ 1000 svc ----------
# runtime.MemStats
# Alloc = 22,719,136
# TotalAlloc = 156797672504
# Sys = 60147960
# Lookups = 384668
# Mallocs = 1940258649
# Frees = 1940043464
# HeapAlloc = 22719136
# HeapSys = 53903360
# HeapIdle = 27484160
# HeapInuse = 26419200
# HeapReleased = 0
# HeapObjects = 215185
# Stack = 622592 / 622592
# MSpan = 201488 / 294912
# MCache = 2416 / 16384
# BuckHashSys = 2927360
# NextGC = 34141770

----------

Top 10 heap users by function call
(pprof) top 10
11889.31kB of 13938.30kB total (85.30%)
Dropped 298 nodes (cum <= 69.69kB)
Showing top 10 nodes out of 108 (cum >= 515.13kB)
      flat  flat%   sum%        cum   cum%
 3281.46kB 23.54% 23.54%  3281.46kB 23.54%  reflect.Value.call
 2219.99kB 15.93% 39.47%  2219.99kB 15.93%  k8s.io/kubernetes/pkg/proxy/iptables.getChainLines
 1584.50kB 11.37% 50.84%  1584.50kB 11.37%  crypto/tls.(*block).reserve
 1024.04kB  7.35% 58.18%  1024.04kB  7.35%  github.com/ugorji/go/codec.(*jsonDecDriver).decString
  847.46kB  6.08% 64.27%   847.46kB  6.08%  bytes.makeSlice
  727.78kB  5.22% 69.49%   727.78kB  5.22%  k8s.io/kubernetes/pkg/proxy/config.newServicesSourceApiFromLW.func1
  650.62kB  4.67% 74.15%   650.62kB  4.67%  k8s.io/kubernetes/pkg/proxy/config.newEndpointsSourceApiFromLW.func1
  522.06kB  3.75% 77.90%  4101.59kB 29.43%  k8s.io/kubernetes/pkg/proxy/iptables.(*Proxier).syncProxyRules
  516.26kB  3.70% 81.60%   516.26kB  3.70%  k8s.io/kubernetes/pkg/conversion.(*Scheme).AddKnownTypes
  515.13kB  3.70% 85.30%   515.13kB  3.70%  k8s.io/kubernetes/pkg/api/meta.(*DefaultRESTMapper).Add

**Comment by ArtfulCoder** [comment]
Top allocated objects are:
(pprof) unit=alloc_objects
(pprof) 
(pprof) 
(pprof) 
(pprof) top 10
64484alloc_objects of 64645alloc_objects total (99.75%)
Dropped 170 nodes (cum <= 323alloc_objects)
Showing top 10 nodes out of 51 (cum >= 16397alloc_objects)
      flat  flat%   sum%        cum   cum%
32768alloc_objects 50.69% 50.69% 32768alloc_objects 50.69%  k8s.io/kubernetes/pkg/api/v1.(*ObjectMeta).codecDecodeSelfFromMap
16384alloc_objects 25.34% 76.03% 16384alloc_objects 25.34%  k8s.io/kubernetes/pkg/proxy/iptables.servicePortEndpointChainName
10925alloc_objects 16.90% 92.93% 10925alloc_objects 16.90%  reflect.Value.call

**Comment by wojtek-t** [comment]
This has been significantly optimized in 2017. Closing.
