### ISSUE TITLE
Update container-environment.md to reflect reality

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14127]
Forked from #12747. 

We need to clean up https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/container-environment.md. It's confusing to users.

* Ensure the description reflects current implementation
* Remove unimplemented features. This isn't a design doc.

cc @smarterclayton

**Comment by luebken** [comment]
The PR https://github.com/kubernetes/kubernetes/pull/15246/ deleted some details about proposed container hooks `PreStart` and `PostRestart` and some reason passed to the handler (delete, health, dependency). Any pointers to a design doc or something similar to followup on this?
