### ISSUE TITLE
Vagrant+libvert error installing Docker

### ISSUE THREAD

**Issue by technosophos** [kubernetes/kubernetes#14128]
Host: Ubuntu 15.04 + Lastest Vagrant +libvert, Kubernetes `master`

Problem:

During `kube-up.sh`, during provisioning of master and minion, there is an error that appears to be a conflict over which version of Docker should be installed.

```
==> master: Running transaction check
==> master: Running transaction test
==> master: 
==> master: 
==> master: Transaction check error:
==> master:   file /usr/bin/docker conflicts between attempted installs of docker-io-1.5.0-1.fc20.x86_64 and docker-1.5-10.fc20.x86_64
==> master: 
==> master: Error Summary
==> master: -------------
==> minion-1: Creating image (snapshot of base box volume).
==> master: An error occurred. The error will be shown after all tasks complete.
```

**Comment by lhuard1A** [comment]
I had exactly the same problem with `Vagrant+libvirt`.
It appears that `Vagrant+libvirt` still uses a Fedora 20 box whereas `Vagrant+VirtualBox` uses a Fedora 21 one.

I tried to convert the Fedora 21 VirtualBox box to libvirt format and it solved that issue.

I opened PR #14490 to re-align the `libvirt` box with the `VirtualBox` one.

@technosophos Could you check that this new box solves your issue?

**Comment by kargakis** [comment]
@kubernetes/sig-contributor-experience-misc
