### ISSUE TITLE
kube-proxy: change default resync period

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#14122]
The default 5 second resync period is too low, especially on the userpsace proxier with lots of services - the mutex is held basically continuously.

Consider changing this to 30s for v1.1 - will probably impact e2e which tests this.

**Comment by bgrant0607** [comment]
Moving from v1.1-candidate to v1.1. @thockin, if this isn't happening, punt it out of 1.1 entirely.

**Comment by thockin** [comment]
This is resolved
