### ISSUE TITLE
Events missing UIDs

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#14126]
Certain events are missing UIDs. After a bit of investigation with @lavalamp and @saad-ali we realized that UIDs are not validated if existing events are updated. The api-server can populate UIDs for events if they are missing based on the Name. 
Fixing the client side event generator may not work everywhere since it requires re-compiling all the clients.

**Comment by lavalamp** [comment]
@saad-ali, do you have time to look at this?

**Comment by lavalamp** [comment]
This is important not because of events, but because it indicates that we're not globally validating things that should be globally validated.

**Comment by liggitt** [comment]
It's because events aren't using generic etcd (at least, they weren't the last time I checked), unlike most other things. That means they need to do more of the validation legwork themselves (ensuring things are set on create and don't mutate on update)

**Comment by caesarxuchao** [comment]
Per the in-person discussion with @lavalamp, some of our proposals:
1. we will not accept #14422, and we will need a PR to fix the client that generate the update request. @jiangyaoguo feel free to pick this if you are interested.
2. on the server side, we will add an update request validation to check if UID (and other fields) is changed. Because this will break the clients, we will make a flag to turn on/off this server behavior for now. We plan to turn on the validation in default and **break the clients** when we release **1.2**.

We'd like to know how people think, especially about "breaking clients in 1.2 release" part. @vishh @saad-ali @liggitt  Thank you.

**Comment by lavalamp** [comment]
@bgrant0607 Comments on giving clients until 1.2 to stop wiping out UIDs? We'd flip the flag in HEAD ~now, so we can find offending clients.

**Comment by liggitt** [comment]
when is removing a UID valid?

**Comment by lavalamp** [comment]
It's never valid. Yeah, that's a good point, we should also ignore removal attempts ASAP.

**Comment by lavalamp** [comment]
Never. #14422 seems like an OK short term patch?

**Comment by caesarxuchao** [comment]
#14422 does what it claims, but do we *need* to merge it? Is there any work that depends on it?

**Comment by lavalamp** [comment]
Well, events are potentially archived by external systems, so this could
potentially bite us at some point in the future. But I'm more worried about
non-event resources.

It's true that UID is not used by the system that much today, which is why
we haven't noticed this until now.

**Comment by caesarxuchao** [comment]
Server is already setting UID if it's empty:
https://github.com/kubernetes/kubernetes/blame/master/pkg/api/validation/validation.go#L276

This code is not exercised when updating event though.

**Comment by bgrant0607** [comment]
We're talking about changing metadata.uid or involvedObject.uid?

Updates should never affect metadata.uid. If we ignore the value specified by the user in the v1 API, then we need to preserve that behavior. We could potentially create a way to additional validation, however. I'd like to see a component read resources from the API and validate them, so that we could deploy the validator onto existing clusters.

**Comment by bgrant0607** [comment]
Validation is the wrong place to be mutating the resource. See also #13814.

**Comment by caesarxuchao** [comment]
> I'd like to see a component read resources from the API and validate them, so that we could deploy the validator onto existing clusters.

For this to work, we will need to a way to specify if a field is mutable in the swagger spec. It seems swagger doesn't support this natively. https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schemaObject

**Comment by caesarxuchao** [comment]
@lavalamp 
> But I'm more worried about non-event resources.

Many resources will go through this line https://github.com/kubernetes/kubernetes/blame/master/pkg/api/validation/validation.go#L276, so they will have an UID during update.

**Comment by bgrant0607** [comment]
@caesarxuchao We should request swagger support for immutable (e.g., see https://github.com/swagger-api/swagger-spec/issues/228), but we don't need to block on that. Starting with ad hoc validation code would be a reasonable start. There are likely many more properties we'd like to check than what can be expressed via swagger.

**Comment by lavalamp** [comment]
@caesarxuchao 

> Server is already setting UID if it's empty

Yes, it should do so only on *creates*.

> ValidateObjectMetaUpdate

Ah, that is basically this same hack that's in #14422. If all objects call that, I'm satisfied. (Events must not?)

@caesarxuchao @bgrant0607 

I am interested in validating the UID not changing in some global place. If that's the best place to also have a global hack to be nice to old broken clients, I can live with that. It should be clearly marked with a TODO.

I'll also be satisfied with a test that does discovery and runs against every supported resource, verifying that the UID cannot be changed.

Actually, given that there *is* function (ValidateObjectMetaUpdate) and it's *not* getting called properly, I think such a test is the *only* thing that will satisfy me now. We can write it as an integration test.

**Comment by caesarxuchao** [comment]
@lavalamp 
> Yes, it should do so only on creates.

It should, but currently it's doing this on update as well. (not when updating Event of course)

> I am interested in validating the UID not changing in some global place

ValidateObjectMetaUpdate is called resource-by-resource. To do it globally, we can do the validation in BeforeUpdate().

> Actually, given that there is function (ValidateObjectMetaUpdate) and it's not getting called properly, I think such a test is the only thing that will satisfy me now. We can write it as an integration test.

I think the right step is: 1. have a PR that does the switchable global validation of UID 2. adding the integration test to verify UID cannot be changed.

**Comment by caesarxuchao** [comment]
For the client-side fix of the Events, we plan to use Patch instead of PUT, so we can avoid wiping out fields that we don't want to change.

**Comment by caesarxuchao** [comment]
@saad-ali, per our discussion this afternoon, I'm implementing the update of events using patch. Then it's critical to generate a patch with *all* modified fields. The new event is generated here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/record/event.go#L217
Could you confirm that only Event.Count and Event.LastTimestamp will be changed? Thanks!

**Comment by caesarxuchao** [comment]
> Could you confirm that only Event.Count and Event.LastTimestamp will be changed? Thanks!

I discussed with dchen1107, the answer is yes. Because update of Event only occurs when we compress the event, so those two are the only fields that would be changed.

**Comment by saad-ali** [comment]
@caesarxuchao SGTM and yes `Count` and `LastTimestamp` are the only fields that should be modified.

**Comment by liggitt** [comment]
Reopening... the merged commit only fixes one client of the Events API... nothing enforces events having UIDs still:

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/events.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/event/strategy.go#L45

**Comment by liggitt** [comment]
Since events aren't using generic etcd, they need to do the following themselves:

1. `PrepareForCreate` should probably call `FillObjectMetaSystemFields`
2. `PrepareForUpdate` should (maybe?) fill UID if unset?
2. ValidateEvent should do as many of the same things `ValidateObjectMeta` does (it can't call it directly, because events can be either namespaced and unnamespaced)
  * Require a valid name
  * Validate labels
  * Validate annotations
  * Validate UID is set
3. There should be a ValidateEventUpdate function that ensures the update doesn't mutate an existing name or UID

**Comment by lavalamp** [comment]
@liggitt, did you miss #15191?

Anyway, I'd rather switch events over to using the generic stuff than fix all that separately.

**Comment by liggitt** [comment]
#15191 doesn't help... events don't call any of the common validation methods, right? Also, we should update the "create event" API *now* to avoid getting more bad events in the system, then figure out what to do on update

**Comment by liggitt** [comment]
> Anyway, I'd rather switch events over to using the generic stuff than fix all that separately.

I'd like to as well, but events not following the namespace rules makes that hard... I don't really want to make the common functions crazy to accomodate the events edge case

**Comment by caesarxuchao** [comment]
@liggitt 

> events don't call any of the common validation methods, right

`events` is using the generic etcd (https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/event/etcd/etcd.go#L37), so it calls the common update validation during an update. Did I miss something?

> we should update the "create event" API now to avoid getting more bad events in the system

I agree. #15191 only validate *update*, not *create*.

**Comment by liggitt** [comment]
Generic etcd doesn't call the common validate. The specified update strategy is responsible for doing that, and event's update strategy just calls ValidateEvent, which doesn't validate much other than a well formed namespace

**Comment by caesarxuchao** [comment]
Generic etcd calls BeforeUpdate:
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/generic/etcd/etcd.go#L280,

and in BeforeUpdate we call validateCommonFields which validates the objectMeta:
https://github.com/kubernetes/kubernetes/blob/8c753c84eb149f6434f37f497df64ebb2c41d387/pkg/api/rest/update.go#L83

**Comment by liggitt** [comment]
hrmm, you're right, my mistake...

**Comment by caesarxuchao** [comment]
@liggitt, I think you are correct about the create part. We don't have a validation function for common fields in the create path.

**Comment by liggitt** [comment]
@caesarxuchao putting together a PR now for that, will tag you and @lavalamp on it

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/15975
