### ISSUE TITLE
Unable to use kubectl get with a fieldSelector

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#14129]
I do not appear to be able to use kubectl to perform a field selector.

In particular, I wanted to select pods that were scheduled to a particular node.

Expected to be able to do:

```
kubectl get pods --all-namespaces -l spec.nodeName=10.245.1.3
```

But that only filters on labelSelectors, and there is no way to pass a fieldSelector.

**Comment by derekwaynecarr** [comment]
@kubernetes/kubectl - its possible I am ignorant of a feature, but it looks like field selectors are not usable from kubectl.

**Comment by smarterclayton** [comment]
They are not

On Sep 17, 2015, at 3:01 PM, Derek Carr <notifications@github.com> wrote:

@kubernetes/kubectl <https://github.com/orgs/kubernetes/teams/kubectl> -
its possible I am ignorant of a feature, but it looks like field selectors
are not usable from kubectl.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14129#issuecomment-141190235>
.

**Comment by derekwaynecarr** [comment]
Then consider this issue a feature request to make it easy for me to filter all pods by a node in kubectl using the current fieldSelector available in the API ```spec.nodeName``` ;-)

**Comment by smarterclayton** [comment]
Agree, there are more uses for it and we now have jsonpath to formalize it

On Sep 17, 2015, at 3:37 PM, Derek Carr <notifications@github.com> wrote:

Then consider this issue a feature request to make it easy for me to filter
all pods by a node in kubectl using the current fieldSelector available in
the API spec.nodeName ;-)

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14129#issuecomment-141203107>
.

**Comment by JanetKuo** [comment]
I tried to support that in an earlier PR, however in current development if you're specifying multiple resources with any fieldSelector that don't exist in all of the specified resources, it'd fail. See https://github.com/kubernetes/kubernetes/pull/12112#issuecomment-128532616

**Comment by derekwaynecarr** [comment]
I think its reasonable to error on a fieldSelector when supplying more than one resource type.

```kubectl get --field-selector=spec.nodeName=xyx pods``` works fine.

```kubectl get --field-selector spec.nodeName=xyz pods,services``` should error

**Comment by derekwaynecarr** [comment]
@smarterclayton - the problem with json path is its client filtered, right?  i want to filter on the server if possible.

**Comment by smarterclayton** [comment]
Today.  No reason it can't be on the server.

On Sep 17, 2015, at 4:20 PM, Derek Carr <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> - the problem with json
path is its client filtered, right? i want to filter on the server if
possible.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14129#issuecomment-141216020>
.

**Comment by bgrant0607** [comment]
Field selector is somewhat deliberately obscure until a more general and efficient implementation exists.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc
