### ISSUE TITLE
Vagrant developer provisioning fails because of broken symlink

### ISSUE THREAD

**Issue by technosophos** [kubernetes/kubernetes#14124]
Environment:

Host OS is Ubuntu 15.04, running latest Vagrant and using the Vagrant libvirt provisioner.

Issue:

When running a fresh `cluster/kube-up.sh`, I get to the point where Vagrant is rsyncing data. The process fails because the `testdata` in one of the dependency Go packages contains an (intentionally) broken symlink. Rsync with `--copy-links` does not handle this case well, and the build ultimately fails:

```
==> minion-1: Configuring and enabling network interfaces...
==> minion-1: Installing rsync to the VM...
==> minion-1: Rsyncing folder: /home/mbutcher/Code/kubernetes/ => /vagrant
==> minion-1: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'master'
machine. Please handle this error then try again:

There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /home/mbutcher/Code/kubernetes/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/home/mbutcher/Code/kubernetes/.vagrant/machines/master/libvirt/private_key' --exclude .vagrant/ /home/mbutcher/Code/kubernetes/ vagrant@192.168.121.61:/vagrant
Error: Warning: Permanently added '192.168.121.61' (RSA) to the list of known hosts.
symlink has no referent: "/home/mbutcher/Code/kubernetes/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/data/symlink"
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]


An error occurred while executing the action on the 'minion-1'
machine. Please handle this error then try again:

There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /home/mbutcher/Code/kubernetes/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/home/mbutcher/Code/kubernetes/.vagrant/machines/minion-1/libvirt/private_key' --exclude .vagrant/ /home/mbutcher/Code/kubernetes/ vagrant@192.168.121.192:/vagrant
Error: Warning: Permanently added '192.168.121.192' (RSA) to the list of known hosts.
symlink has no referent: "/home/mbutcher/Code/kubernetes/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/data/symlink"
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
```

Would the best solution be to simply `--exclude` that directory?

**Comment by technosophos** [comment]
Update: This is actually the result of running Vagrant with libvirt and without NFS.

With the `rsync` agent, we could simply add the `rsync__exclude` directive and ignore the problematic test directory.

**Comment by alex-mohr** [comment]
@derekwaynecarr are you still helping with Vagrant issues?

**Comment by derekwaynecarr** [comment]
I am supporting the Vagrant + VirtualBox combination.

I think @pronix added support for the Vagrant + libvirt combination in
https://github.com/kubernetes/kubernetes/pull/7617

It would be good for him to weigh in if he is still able to support.

**Comment by pronix** [comment]
Hello
can you provide step by step instruction how to repeat error, started on git clone kubernetes ?
also rsync working same way as on virtualbox, and you can use rsync__exclude
thank

**Comment by technosophos** [comment]
All I did was clone the repo and run `hack/dev-build-and-up.sh`. I also tried kube-up.sh directly while I was debugging. 

As you can see, the broken symlink is checked into the repo:
https://github.com/kubernetes/kubernetes/tree/master/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/data

It should be reproducible by simply trying to rsync that file to another location using the relevant flags.

**Comment by kargakis** [comment]
@kubernetes/sig-contributor-experience-misc
