### ISSUE TITLE
pkg/client: api version to be set at high level, not low level.

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14133]
Currently pkg/client has logically distinct low level RESTClient (Get, Put, Post...) and high level typed client (PodsNamespacer etc).

The API version (and implictly, group) is currently baked into the low level RESTClient, but this is wrong. We want to use the same low-level code for all API versions and groups, and supply a different high level client for each version.

The action item here is to remove references to "version" from the RESTClient, and put them in the high level client, adding Group(), Version(), and GroupVersion() calls to the client.Request object.

**Comment by deads2k** [comment]
> /cc @deads2k - might be related to the negotiate rework you looked at

Once all the surrounding code can handle a late-binding `apiVersion`, it ought to make it easier to avoid excessive negotiation.  It won't eliminate the problem of getting the correct codec down to the lower level `RESTClient`, but presumably that would happen at the same time the `apiVersion` is set.

**Comment by lavalamp** [comment]
I filed #14321; the high level client still needs to select the right group/version, but @smarterclayton has convinced me it should do so by choosing a particular rest client.

**Comment by liggitt** [comment]
Hmm, that makes it tough to do lazy/just-in-time version negotiation, which @smarterclayton also wants

**Comment by smarterclayton** [comment]
We agreed we need a higher level client - aka metarestclient to negotiate.
Dan is going to dive into that.

On Sep 21, 2015, at 7:58 PM, Jordan Liggitt <notifications@github.com>
wrote:

Hmm, that makes it tough to do lazy/just-in-time version negotiation, which
@smarterclayton <https://github.com/smarterclayton> also wants

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14133#issuecomment-142141822>
.
