### ISSUE TITLE
There should be a cluster-level SELinux capability

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#14131]
Forking from #12944

Currently, the SELinux support in kubernetes is essentially optional and is driven by whether
SELinux is enabled on any particular node.  It should be possible for cluster operators to enforce
that SELinux is enabled if SELinux integration is expected by the cluster.  If SELinux integration
is expected and SELinux is not enabled on a node, the node should have a `NotReady` status.

There should be a cluster-wide capability that controls whether SELinux integration is enabled in
the cluster.  Cluster operators generally either run SELinux or they don't; we do not know of any
cases where an operator wants to have SELinux enforcing on some nodes in a cluster and not on
others.

@swagiaal and I have been discussing this; he is beginning work on a PR now.

@bgrant0607 @thockin @erictune @smarterclayton 

A new `EnableSELinuxIntegration` capability should be added to the `capabilities.Capabilities`
struct:

```go
// Capabilities defines the set of capabilities available within the system.
// For now these are global.  Eventually they may be per-user
type Capabilities struct {
    // descriptions omitted for brevity
    AllowPrivileged bool
    HostNetworkSources []string
    PerConnectionBandwidthLimitBytesPerSec int64

    // EnableSELinuxIntegration controls whether SELinux integration
    // is expected from Kubernetes
    EnableSELinuxIntegration bool
}
```

There should be validations added to ensure that if SELinux integration is not enabled, pods cannot
be created with SELinux contexts set.  If this capability is set and SELinux is not enabled on the node, the node should report `NotReady` status.

**Comment by roberthbailey** [comment]
@dchen1107

**Comment by smarterclayton** [comment]
I'm not sure that we want to prevent pods that have SELinux contexts set from being copied across clusters.  That seems inherently fragile.  What's the benefit to the end user?  If someone writes an example that sets selinux context to a label that is well known across a set of systems, why would we reject the example on systems that don't have SELinux enabled?  If someone uses a Pod feature that hyper or rocket or **insert new containerized here** doesn't support, do we reject their creation?

**Comment by pmorie** [comment]
Closing out since we decided in #14513 not to do this.
