### ISSUE TITLE
Prodswitch-off Kubelet should reject allocated pods from kube-apiserver (was: Unschedulable Kubelet should reject allocated pods from kube-apiserver) 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#14140]
PR #14054 which registers master kubelet with the kube-apiserver, but mark such kubelet as unschedulable through NodeSpec. Such kubelet should operate the same as other kubelets, except rejecting any allocated pods from kube-apiserver.

cc/ @roberthbailey @mikedanese @bgrant0607 @davidopp

**Comment by dchen1107** [comment]
cc/ @kubernetes/goog-node

**Comment by bgrant0607** [comment]
cc @a-robinson

**Comment by dchen1107** [comment]
Yu-Ju Hong Brian Grant Mike Danese and I discussed earlier. We don't want Kubelet take action upon unschedulable, instead, introducing another node condition (name is TBD). The main reason is we don't want to overload schedulable / unschedulable concept here.

**Comment by bgrant0607** [comment]
I suggest "Accepting" for the condition name. I also considered "Admitting", but that sounds like only an admission-time behavior. However, we also plan to kill pods that are already running if this option is changed. "Accepting" implies continued tolerance in addition to "consent to receive".

**Comment by mikedanese** [comment]
Should node controller evict pods on this condition?

**Comment by yujuhong** [comment]
From the comments above, it sounds like that kubelet is *not* going to reject any pods when it becomes unschedulable. Instead, kubelet would report that a node condition "Accepting" if it sees itself as schedulable. Node controller, after observing a node condition changes to not accepting, will then evict all the pods. 

This effectively disallows pods to be run on an unschedulable node, which I think may be useful sometimes. For example, if I wanted to test if a node is ready, I would mark the node as unschedulable, manually assign some pods to the node to see if they run fine, and then mark the node as scheduable again.

**Comment by vishh** [comment]
I assume as part of this new feature, the scheduler will avoid assigning
pods to a kubelet that is not accepting any pods.

**Comment by dchen1107** [comment]
@yujuhong We plan to leave schedulable / unschedulable as is today. Instead we plan to introduce a new condition whose name is to be defined to our API. Let's assume the name is ProdSwitch. When such condition is off:

1) scheduler should avoid schedule pods to that kubelet
2) kubelet should stop accepting any pods from kube-apiserver
3) node-controller should evict all running pods on that node.

**Comment by yujuhong** [comment]
> I assume as part of this new feature, the scheduler will avoid assigning
> pods to a kubelet that is not accepting any pods.

If you create a pod with PodSpec.NodeName written, scheduler would ignore this pod while the kubelet will run the pod.

**Comment by yujuhong** [comment]
> @yujuhong We plan to leave schedulable / unschedulable as is today. Instead we plan to introduce a new condition whose name is to be defined to our API. Let's assume the name is ProdSwitch. When such condition is off:

I see. This is very different from what the title of this issue suggests. Time to change the title? :)

**Comment by dchen1107** [comment]
I didn't change the title because the new condition is not named. :-)

**Comment by dchen1107** [comment]
But I changed the title anyway by giving prodswitch

**Comment by mikedanese** [comment]
How is this different than standalone? Why not publish "NodeStandalone" mode as a condition and enforce it in the kubelet admission?

**Comment by dchen1107** [comment]
I wished we never have such mode called standalone ...

Ok, today's standalone is for running kubelet without API server, and currently the only use case is ContainerVM instances. Those Kubelets are not part of any cluster.

**Comment by dchen1107** [comment]
I am re-target this one for 1.2 since it is blocked by #14054. Also since we decided to introduce a new Condition, instead of using existing Unschedulable condition, this issue is less critical.

**Comment by erictune** [comment]
Is a flag sufficient, rather than a new condition?

**Comment by mikedanese** [comment]
See https://github.com/kubernetes/kubernetes/pull/14054#issuecomment-144229094

**Comment by yujuhong** [comment]
@dchen1107, is this still targeted for v1.2?

**Comment by yujuhong** [comment]
@dchen1107, I'm not sure what the status of this issue is. I'm going to unassign myself since I'm not working on it. Let me know if you need me to pick it up.

**Comment by discordianfish** [comment]
Is this still relevant? I find it hard to figure out how this related to e.g #22494
