### ISSUE TITLE
Validation about creating additional API tokens for a service account

### ISSUE THREAD

**Issue by huangyuqi** [kubernetes/kubernetes#14150]
When i use  `kubectl create -f ./secret.json` to create additional API tokens for a service account, with the follow json file:(according to [Cluster Admin Guide to Service Accounts](https://github.com/kubernetes/kubernetes/blob/master/docs/admin/service-accounts-admin.md#to-create-additional-api-tokens))
```json
secret.json:
{
    "kind": "Secret",
    "apiVersion": "v1",
    "metadata": {
        "name": "mysecretname",
        "annotations": {
            "kubernetes.io/service-account.name": "Account-a"
        }
    },
    "type": "kubernetes.io/service-account-token"
}
```
Although there is no `Account-a` in the cluster, i can still get the right print `secrets/mysecretname`. : ). 
Does it means that there is no validation of ServiceAccount in creating API tokens?Then i found this codes in https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L1566:

```go
	case api.SecretTypeServiceAccountToken:
		// Only require Annotations[kubernetes.io/service-account.name]
		// Additional fields (like Annotations[kubernetes.io/service-account.uid] and Data[token]) might be contributed later by a controller loop
		if value := secret.Annotations[api.ServiceAccountNameKey]; len(value) == 0 {
			allErrs = append(allErrs, errs.NewFieldRequired(fmt.Sprintf("metadata.annotations[%s]", api.ServiceAccountNameKey)))
		}
```
It just check the  name exist or not. And doesn't ensure the referenced service account exists
Is it necessary to fix this? Like this:
```go
	serviceAccount, err := s.getServiceAccount(a.GetNamespace(), pod.Spec.ServiceAccountName)
	if err != nil {
		return admission.NewForbidden(a, fmt.Errorf("Error looking up service account %s/%s: %v", a.GetNamespace(), pod.Spec.ServiceAccountName, err))
	}
```

**Comment by liggitt** [comment]
In general, validation shouldn't make additional API calls to other objects. The tokens controller cleans up tokens that reference service accounts that don't exist

**Comment by Dingshujie** [comment]
I met the same problem, when i use ``` kubectl create -f ./secret.json```to create tokens, it also get right  print ```secrets/mysecretname```,but when i use ```kubectl get secrets/mysecretname -o yaml```to get detail information of mysecretname, it met an error,it print```Error from server: secrets "mysecretname" not found```.Does it means that lack of  specified service-account lead to mysecretname creation fails?

**Comment by liggitt** [comment]
that likely means the tokens controller observed the creation of the secret, found the service account missing, and cleaned up the invalid token secret

**Comment by huangyuqi** [comment]
Thanks, @liggitt. I got what you mean. But the cleaning up action is background, the user should not get any information of `kubectl create -f ./secret.json`.  Maybe,  some tips need add to doc.

**Comment by davidopp** [comment]
@liggitt can you dispense with this issue as appropriate?

**Comment by liggitt** [comment]
Opened https://github.com/kubernetes/kubernetes.github.io/pull/380/files to note the cleanup of invalid tokens.
