### ISSUE TITLE
godep restore failing on HEAD

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#14159]
The cause is prometheus/client_golang#173. It fails with the following error:
```
pszczesniak@piosz:~/go/src/k8s.io/kubernetes$ godep restore
package github.com/prometheus/client_golang/extraction: cannot find package "github.com/prometheus/client_golang/extraction" in any of:
        /usr/lib/google-golang/src/github.com/prometheus/client_golang/extraction (from $GOROOT)
        /usr/local/google/home/pszczesniak/go/src/github.com/prometheus/client_golang/extraction (from $GOPATH)
godep: restore: exit status 1
package github.com/prometheus/client_golang/model: cannot find package "github.com/prometheus/client_golang/model" in any of:
        /usr/lib/google-golang/src/github.com/prometheus/client_golang/model (from $GOROOT)
        /usr/local/google/home/pszczesniak/go/src/github.com/prometheus/client_golang/model (from $GOPATH)
godep: restore: exit status 1
```

@eparis proposed one of:
1) fix e2e to not use prometheus/golang_client/extraction
2) fix godep to not die in this situation
3) turn of the verification

Follow up of #14113

**Comment by piosz** [comment]
cc @timstclair who introduced the mentioned deps

**Comment by juliusv** [comment]
On the Prometheus side, this functionality has moved to `github.com/prometheus/common/model` and `github.com/prometheus/common/expfmt`, respectively. Let us know if we can help with the conversion.

@fabxc, does the note in the README.md of https://github.com/prometheus/common still apply, or is it fine for external users to use packages from this repo now?

**Comment by piosz** [comment]
@juliusv thank you so much for quick update. This should be sufficient for us.

**Comment by fabxc** [comment]
Removed the notice – this repo is now in use across our repositories. It may still change as as required by our components.

**Comment by piosz** [comment]
@fabxc thanks for the info!

**Comment by piosz** [comment]
@juliusv, @fabxc we are using in out code extraction.Processor004. Where can I find a new version of this once it was removed? See https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubelet_stats.go#L116 for references.

**Comment by eparis** [comment]
I think it is supposed to be NewDecoder() and the decoder is supposed to end up doing text/plain decoding based on the http header.  I haven't a clue how to get the header in there where we need it...

**Comment by fabxc** [comment]
Seems like making `textDecoder` and `protoDecoder` public might be helpful for those purposes. The initial version was kept minimal but we can certainly do this.

**Comment by eparis** [comment]
/me has NO idea what he's doing, but I'm trying something like:
```
    hdr := http.Header{"Content-Type": []string{"text/plain"}}
    decoder, err := expfmt.NewDecoder(strings.NewReader(body), hdr)
```

**Comment by fabxc** [comment]
That will work with the current version.

**Comment by piosz** [comment]
@eparis are somewhat familiarized with prometheus? Would you like to take a look into this issue?

**Comment by eparis** [comment]
god no.  I'm TOTALLY clueless and am just hitting random keys hoping it will compile...

**Comment by fabxc** [comment]
What do you think of a solution like prometheus/common#3?

**Comment by thockin** [comment]
Who is owning this on our side?  The bleeding should have stopped now, but we need a real fix.  I want #14179 neutered ASAP

**Comment by timstclair** [comment]
I can take this since I introduced the original dependency, unless @eparis already has a working fix.

**Comment by eparis** [comment]
I do not have it working.  @fabx sent me https://gist.github.com/fabxc/e95dfccb3e69ff991903  which I was about to play with.

**Comment by timstclair** [comment]
Either way... but I think the client model has changed to the protobuf message "MetricFamily" - I'm not sure what model.Vector is.

**Comment by eparis** [comment]
#14198 is another needed godep fix.  But we will need to fix the Prometheus stuff.
