### ISSUE TITLE
Cover Initial Resources with tests

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#14178]
- [x] unit tests of admission part #13132
- [ ] unit tests for gcm source
- [x] e2e test #15145

**Comment by piosz** [comment]
follow up of #14113

**Comment by piosz** [comment]
Reassigning to @jszczepkowski and @krzysztofgrygiel who will work on the new version of Iniital Resources/Vertical Pod Autoscaler.

**Comment by mwielgus** [comment]
Closing in favor the effort in https://github.com/kubernetes/autoscaler.
