### ISSUE TITLE
Add Conditions alongside Phases.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#14181]
We have PodPhaseSucceeded.  
 #7856 says we should use Conditions in place of phases.
If that is the case, then we should add Conditions which mirror andy existing Phases, such as  PodPhaseSucceeded, and mark the Conditions as preferred to Phases.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by bgrant0607** [comment]
No longer considered a good idea. See #7856.
