### ISSUE TITLE
Remove "Required" and "Optional" from comments in types.go

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#14189]
Forked from #14077 

In the types.go:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L594

And there are other occurances of "Required:" in the comments in types.go, which shouldn't be there.

We will also need to re-run scripts to generate html files after the comments are fixed.

@nikhiljindal

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc
