### ISSUE TITLE
The API  proxy cannot handle encoded slashes

### ISSUE THREAD

**Issue by mwringe** [kubernetes/kubernetes#14193]
When using the proxy, we cannot send URLs which contain an encoded /

This can cause problems when the service behind the proxy is expecting a URL path which does contain an encoded /

Eg a URL like this cannot be used:
https://localhost:8443/api/v1/proxy/namespaces/metrics/services/hawkular-metrics:http-endpoint/hawkular/metrics/gauges/hawkular-metrics%2Fc8ac3234-5659-11e5-8de0-3c970e88a56f%2Fmemory%2Fusage

While if you were to use the endpoint directly on the service itself, everything would work properly.

**Comment by smarterclayton** [comment]
This is go being stupid.  @liggitt @csrwng we need to parse requestURI and then pass on the version by splitting the string ourself.

**Comment by smarterclayton** [comment]
I don't know if this is only in upgradeawareproxy or other places

**Comment by csrwng** [comment]
@smarterclayton related issue: https://github.com/openshift/origin/pull/4697. I'll work on a fix.

**Comment by smarterclayton** [comment]
Status on this?

**Comment by csrwng** [comment]
Still don't have a fix, will make it a priority to submit one today or asap

**Comment by csrwng** [comment]
Just a note on this. We can fix path segments that include encoded slashes with something similar to what openshift/origin#4697 is doing. However, if your path segment includes a ".", the golang ServeMux handler intercepts the request before it makes it to our rest handlers and tries to normalize it and returns a 301 with the decoded path. It will do this even if the "." is encoded as %2E.

**Comment by liggitt** [comment]
Do you mean if you have a path segment consisting of exactly `.` (or `..`, I would assume)? If so, I'm not surprised that stack tries to normalize/redirect that away.

**Comment by csrwng** [comment]
It can be anywhere in the path, for example if you try to use the encoded URL for this issue as a path segment: https%3A%2F%2Fgithub.com%2Fkubernetes%2Fkubernetes%2Fissues%2F14193 
Because it contains a ".", it never makes it to our handler.

**Comment by liggitt** [comment]
In that case, I think the double slash is what's causing the redirect to normalize

**Comment by csrwng** [comment]
@liggitt you are absolutely right. I thought it was the period because periods were getting removed in the redirect path, but it's only when they are the only thing in the path segment. So maybe it's not so bad.

**Comment by liggitt** [comment]
well... there's lots of possibilities that could redirect weirdly:

```
/%2F
%2F/
%2F%2F
/.%2F
/..%2F
etc
```

**Comment by liggitt** [comment]
I don't think we can support encoded slashes in the path in a reasonable way. Too much of the guts of ServeMux, url normalization, and request URL parsing disallow it.
