### ISSUE TITLE
Plan for maintaining CoreOS getting started

### ISSUE THREAD

**Issue by robszumski** [kubernetes/kubernetes#14205]
CoreOS recently released [coreos-kubernetes](https://github.com/coreos/coreos-kubernetes) ([blog post](https://coreos.com/blog/official-kubernetes-on-coreos/)), which is a maintained set of guides and Vagrant examples for running single and multi-node Kubernetes clusters.

I wanted to start a discussion on how we (CoreOS) can best incorporate these guides into upstream Kubernetes. Brainstorming a few options to get the converstation started, from most to least ideal:

1. Within `/docs/getting-started-guides/coreos/`, link to the guides on coreos.com and explain options for platforms, etc.
2. Sync `coreos-kubernetes` guides into Kubernetes as they are updated. This means they get included in the release tarball and will appear on kubernetes.io ([example](http://kubernetes.io/v1.0/docs/getting-started-guides/coreos/coreos_multinode_cluster.html)).
3. Maintain the existing guides as is and additionally mention the new guides
4. Remove CoreOS guides completely from the getting started docs

Any other ideas or preferences?

cc CoreOS folks: @aaronlevy, @bcwaldon
cc past contributors to docs: @pires, @vallard

**Comment by pires** [comment]
I believe it makes sense for you guys to maintain this. After all, you're CoreOS! But, I'm against removing **all** previous stuff, unless you provide equivalent support, namely for AWS, GCE and Azure.

**Comment by pires** [comment]
Refs #9178 #1472

**Comment by davidopp** [comment]
(1) seems quite reasonable to me.

**Comment by robszumski** [comment]
I'll start working on a PR for 1. This should fix everything in #9178 #14032 other than the AWS issues, which I believe are being worked on separately.
