### ISSUE TITLE
"KubeProxy should test kube-proxy" is extremely slow

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#14204]
Recent test results show it taking ~15m to run.

We should remove this from the regular test runs until it can be made faster.

@kubernetes/goog-testing @ArtfulCoder

**Comment by thockin** [comment]
Abhi - do we know why it's 15 minutes?  I though it was 3 or 4..

**Comment by ArtfulCoder** [comment]
I will take a look at the historical runs.

If need be/worst-case, we can move the external load balancer testing into a different test run (other than GCE-e2e)

**Comment by ArtfulCoder** [comment]
I will work this out over the weekend.

**Comment by ihmccreery** [comment]
Is this fixed? Can we close it?

**Comment by bprashanth** [comment]
> Is this fixed? Can we close it?

The kube-proxy test is slow, we punted on it in 1.2. It still takes 15m and it's currently banished to gce-slow. For it to run per pr it needs to take < 5m. 

Currently each time it wants to test something (eg: endpoint reachability) it loops 30 times with a sleep of 1s. At the very least we can bail early if the condition we're testing is satisfied (eg: has seen all endpoints).

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by wojtek-t** [comment]
This issue is 15 months old from the last update. Should we close it?

**Comment by bowei** [comment]
Do we have a generic issue for making tests faster? This item would resurface as part of that work. I would close this for now.

**Comment by thockin** [comment]
We have made it faster in the mean time.  I bet half of the tests that
upgrade/downgrade Service could be unit tests or integration tests.

**Comment by cmluciano** [comment]
> We have made it faster in the mean time.  I bet half of the tests that
> upgrade/downgrade Service could be unit tests or integration tests.
> …
This seems like a great task to target 1.8. I can add this to the SIG-Net spreadsheet.

**Comment by cmluciano** [comment]
@ixdy I think we can keep this open to work on post-freeze.

**Comment by ixdy** [comment]
given that this has no owner, I'm removing it from the milestone.
