### ISSUE TITLE
add hack/local-up-cluster to CI

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#14207]
**Problem**

Local up cluster has tons of permutations now, and not all of them are gauranteed to work.
- DNS?
- Auth strategy?
- Docker version?
- Containerized?
- Selinux?

**Solution**

_Lets run hack/local-up-cluster in the CI !_

**thoughts** 

I don't think it needs to be in the continuous PR builds, but at least in the intermittent ones it should run.  

It will catch certificates errors, network errors, command line option inconsistencies, while also helping us to maintain a stable dev environment for folks to use.  This will help us ramping up folks who can test and evaluate kuberentes efficiently.  

hack/local-up-cluster is a workhorse for many folks.  In this issue I propose we **add it to CI**.  
- I know folks have said it should be replaced with something else, but... 
- I don't know if that will be happening, given how effective a tool it is for development and rapid testing/proptotying.

So, since local-up-cluster.sh
- ensures that there is a simple way to run kubernetes components
- is a self contained, integration test for simple dev environments
- spins up in a matter of seconds, and doesn't introduce any networking, VMs, or other artifacts 
- has tons of permutations (containerized?dns?selinux?)...

**Comment by jayunit100** [comment]
This issue came up in #13978 , where we realized the value of having this continuously preventing bitrot from happening, without having to mess with the cluster/salt deployments.

**Comment by jayunit100** [comment]
As part of this, hack/local-up should be modified to take more command line options, for example, to support the above HA nodeport apiserver patch.

**Comment by rrati** [comment]
+1 to this.  hack/local-up-cluster is the easiest way to test changes at the system level and imo should setup as much as is sensible.

**Comment by pmorie** [comment]
bump

`local-up-cluster.sh` failures have proven to be extremely frustrating to newcomers on the project -- I would really like this to go under test ASAP.

**Comment by pmorie** [comment]
Here's some additional evidence: #40459

**Comment by MHBauer** [comment]
As one of those users. Get the simple no-arg, no-environment-variable config version to always work.

**Comment by alejandroEsc** [comment]
@pmorie is correct, as a dev myself i find failures here incredibly frustrating and time consuming to debug.
Very disheartening when i pull latest from master only to find things other than my changes are broken and i cant test my changes any longer.

**Comment by jmccormick2001** [comment]
+1

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by caesarxuchao** [comment]
Is anyone working on this? Maybe we can pick some e2e tests to do some basic sanity check of local-up-cluster.sh?

**Comment by spiffxp** [comment]
I couldn't find an issue in kubernetes/test-infra, I may have missed it.  @BenTheElder are you aware of anything?

**Comment by BenTheElder** [comment]
I'm not aware of anything. I don't think "hack" was ever meant to have guarantees (?) I think in the future if we want this though we should move the discussion to sig-testing / test-infra.

**Comment by cblecker** [comment]
Created https://github.com/kubernetes/test-infra/issues/6696 in test-infra.

/close
