### ISSUE TITLE
Kubernetes imagePullSecrets not working; getting “image not found”

### ISSUE THREAD

**Issue by leonfs** [kubernetes/kubernetes#14214]
Hi,

Following the discussion from StackOverflow: 
http://stackoverflow.com/questions/32510310/kubernetes-imagepullsecrets-not-working-getting-image-not-found/32662719#32662719

I think the documentation http://kubernetes.io/v1.0/docs/user-guide/images.html#specifying-imagepullsecrets-on-a-pod,  should be updated regarding the encoding of dockercfg secret.

Or there might be a possibility that the test mentioned in one of the answers should be amended. 
https://github.com/kubernetes/kubernetes/blob/6def707f9c8c6ead44d82ac8293f0115f0e47262/pkg/kubelet/dockertools/docker_test.go#L280

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
It's very likely this is already fixed: https://kubernetes.io/docs/concepts/containers/images/#bypassing-kubectl-create-secrets this section shows encoded version of the dockercfg.

**Comment by kargakis** [comment]
Seems like it's done
