### ISSUE TITLE
kubectl logs doesn't work with journalctl logs backend

### ISSUE THREAD

**Issue by hjfreyer** [kubernetes/kubernetes#14212]
CoreOS 808 just changed to use journalctl as their logs backend (for some reason). This means that `docker logs` and `kubectl logs` no longer work. Which is sad.

**Comment by thockin** [comment]
@kelseyhightower FYI

**Comment by reiz** [comment]
Any other way to get the logs out?

**Comment by robszumski** [comment]
The Docker logging driver was reverted back to json in CoreOS 815.0.0: https://coreos.com/releases/#815.0.0

Can you provide more output for the broken `kubectl logs` command? It works on my 1.0.6 cluster. Can you provide into on how your configured your SSL certs?

**Comment by reiz** [comment]
I just opened a new ticket here #17949.

**Comment by reiz** [comment]
Currently running on `CoreOS beta (835.2.0)`.

**Comment by yujuhong** [comment]
Docker supports journald logging driver and kubelet unfortunately still calls `docker logs` to support journald for the time being. If you're still experience the problem, please file a new issue with more information (k8s/docker version, etc).
