### ISSUE TITLE
GCE kube-down script should get zone from cluster context

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes#14230]
I noticed that the kube-down.sh script apparently gets the zone from the config file.  
After launching a cluster I'd changed the zone in cluster/gce/config-default.sh.  This caused the takedown  process to break.  
It would be more robust to get the zone info from the cluster context instead.

**Comment by xiangpengzhao** [comment]
Is this issue still valid? If so, can guys from @sig-cluster-lifecycle-feature-requests take a look at it?

**Comment by xiangpengzhao** [comment]
@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by roberthbailey** [comment]
@amygdala - what cluster context are you referring to?

If you are talking about the context in the kubeconfig file, it doesn't contain the zone for the cluster. The name of the context (if we wanted to try and parse that), is just the [GCP project and instance prefix](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L1554). And nothing else written to the kubeconfig file indicates which zone the cluster is in.
