### ISSUE TITLE
GKE cluster running nginx seems to break nodePort

### ISSUE THREAD

**Issue by kelbongoo** [kubernetes/kubernetes#14237]
Setting up a cluster on GKE via the gcloud cli tool, and then following this tutorial https://cloud.google.com/container-engine/docs/tutorials/http-balancer, I came across two issues - the first is here https://github.com/kubernetes/kubernetes/issues/13073.

In the tutorial we set up the nginx service with a nodePort like so
```
kubectl expose rc my-nginx --target-port=80 --type=NodePort
```
Of all the nodes in the cluster (I tried 3 and 4 node clusters), the only one who responded to
```
curl (node external ip):(node_port)
```
was the node where the nginx container was actually hosted. The other nodes all showed TCP open at the nodePort in nmap but dropped the connection right away and nothing ever got through to nginx.

Not sure if this is expected behaviour ? From the tutorial it seems like all nodes should return nginx responses
```
Next, create a Container Engine service which exposes this nginx Pod on each node in your cluster:
```

**Comment by thockin** [comment]
Is the firewall open for the node port?  It should absolutely work, and we have e2e tests over this...

**Comment by kelbongoo** [comment]
Firewall is totally open (all sources and all targets)

**Comment by thockin** [comment]
on the node port or on the service port?

**Comment by kelbongoo** [comment]
![screen shot 2015-09-20 at 09 03 36](https://cloud.githubusercontent.com/assets/6676305/9979631/924a082c-5f76-11e5-9c7a-83b1cc75615a.png)

**Comment by kelbongoo** [comment]
OK i deleted that entire project and cluster and started with a fresh one, and no longer having the issue. I wonder if it's related to the fact that my project name had a colon in it ? I filed a parallel issue where I was getting error messages like below, where legoutdufrais.com:api-project-728797969216' was the project name
```
The resource 'legoutdufrais.com%3Aapi-project-728797969216' was not found
```
a new project name without colon is now working fine
