### ISSUE TITLE
Refactor to distinguish between volume lifecycle on node and within cluster for persistent volumes

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#14244]
Forking from #13650 

Currently the volume package has a couple different concerns floating around in it:
1.  The `Builder` and `Cleaner` interfaces deal with setting up and tearing down a volume in a _pod_ and are used by the Kubelet when setting up and tearing down pods
2.  The `Recycler`, `Deleter` and `Creator` interfaces deal with the life cycle phases of persistent volumes that are orthogonal to any particular node and are used by the PV controller[s]

Some types handle both concerns:

The `VolumeOptions` struct carries information about the SELinux context of the volumes directory as is used by volume plugins in the (1) case, and also carries information about persistent volumes in the (2) case.

We should:
1.  Distinguish which interfaces are for which concern through naming
2.  Determine whether all interfaces need to extend the `volume.Plugin` interface
3.  Ensure that separate concerns have distinct APIs

Specific suggestions:
1.  Rename `Builder` and `Cleaner` to `PodVolumeMounter` and `PodVolumeUnmounter`
2.  Rename `Creator`, `Recycler`, and `Deleter` to `PersistentVolumeCreator`, `PersistentVolumeRecycler`, and `PersistentVolumeDeleter`
3.  Create a `PersistentVolumePlugin` interface that creator, recycler, and delete are tied together with:
   
   ``` go
   package volumes
   
   type PersistentVolumePlugin interface {
       NewCreator(...) (Creator, error)
       NewRecycler(...) (Recycler, error)
       NewDeleter(...) (Deleter, error)
   }
   ```
4.  Rename `VolumeConfig` to `PersistentVolumeConfig` (it only carries info for `PersistentVolumePlugin`)
5.  Create a separate `PersistentVolumeOptions` for use with the PV API.

@saad-ali @vishh @markturansky @thockin

**Comment by markturansky** [comment]
Overall, I agree and like what you propose, though I think #3 is not needed.  As implemented today, a persistent volume plugin can choose to implement N of Deleter/Recycler/Creater.  Not each PV would need to implement all of them.  Plain NFS, for example, wouldn't have a dynamic provisioner, so it uses a Recycler but doesn't need a Creater.  Adding to the PV interface would force no-op implementations.

As for spelling, here's another "Creater":  https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L69

I wish English were more consistent in this regard.

**Comment by dchen1107** [comment]
cc/ @saad-ali

**Comment by pmorie** [comment]
@markturansky I'm all about renaming the other 'Creater' too.

**Comment by markturansky** [comment]
Damn those latin-derived words!  

I much prefer "Creater", but I can't argue against Merriam-Webster.  English is a quirky language.

**Comment by pmorie** [comment]
@markturansky we should split this into multiple PRs, it's too much to do
at one time.

**Comment by vishh** [comment]
@pmorie: +1 for refactoring.

**Comment by pmorie** [comment]
@saad-ali @vishh @markturansky Should we sketch out a refactor that moves that PV concerns into a separate package here?
