### ISSUE TITLE
Inaccurate Vagrant developer guide

### ISSUE THREAD

**Issue by apeeyush** [kubernetes/kubernetes#14265]
I have been trying to setup the Vagrant dev environment on Ubuntu 14.04 since past few days.

I was using the latest version of Virtual Box as mentioned in the [guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/developer-guides/vagrant.md) and couldn't setup the environment successfuly. However, it worked well after I downgraded Virtual Box to 4.3 .

I think we should hint to it in the developer guide so that people don't end up wasting time.

I'll be happy to send a PR if others feel that is should be mentioned in the guide.

**Comment by dchen1107** [comment]
cc/ @derekwaynecarr 

Thanks for playing Kubernetes with Vagrant, and please send us PR to improve our doc.

**Comment by derekwaynecarr** [comment]
What was the error?

**Comment by apeeyush** [comment]
Hi,

It looks like to error is fixed in virtualbox 5.0.6

The error was that it got stuck in an infinite loop with virtualbox 5.0.4

Closing this issue for now. Feel free to reopen if you this that some work needs to be done here.
