### ISSUE TITLE
how to inprove pods-capacity of a node？

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#14264]
i want to run  a big cluster which has 60 pods(only 1 slaver-node). but it is impossible because one node can only run 40 pods.
we can see that in json file:

"status": {
        "capacity": {
            "cpu": "32",
            "memory": "65681124Ki",
            "pods": "40"
        },
.....
Is there any way to change this limit?

**Comment by dchen1107** [comment]
Here is the flag defining maximum number of pods can run on a Kubelet:
https://github.com/kubernetes/kubernetes/blob/843134885e7e0b360eb5441e85b1410a8b1a7a0c/cmd/kubelet/app/server.go#L269
