### ISSUE TITLE
Issue creating kubernetes cluster in AWS Asia regeoon

### ISSUE THREAD

**Issue by mudrion** [kubernetes/kubernetes#14278]
Case. create kubernetes cluster in Amazon AWS ap-southeast-1

Variable used
export KUBE_AWS_ZONE="ap-southeast-1"
export AWS_S3_REGION="ap-southeast-1"
export KUBE_OS_DISTRIBUTION="vivid"
export KUBERNETES_PROVIDER=aws

Error 1st
*********************************************************************************************************
./kube-up.sh
Starting cluster using provider: aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: vivid
Please specify AWS_IMAGE directly (region not recognized)
*********************************************************************************************************
Note adding AWS_IMAGE
export AWS_IMAGE=ami-66546234

Error 2nd
*********************************************************************************************************
./kube-up.sh
Starting cluster using provider: aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: vivid
Uploading to Amazon S3
Creating kubernetes-staging-7ec2902cbab698915d70af73b0cce8dd
make_bucket: s3://kubernetes-staging-7ec2902cbab698915d70af73b0cce8dd/

Unable to confirm bucket creation.
Please ensure that s3://kubernetes-staging-7ec2902cbab698915d70af73b0cce8dd exists
and run the script again. (sorry!)
*********************************************************************************************************
Note checking in S3 on Bucket creation
aws s3 ls "s3://" | grep kubernetes-staging-7ec2902cbab698915d70af73b0cce8dd
2015-09-19 08:25:36 kubernetes-staging-7ec2902cbab698915d70af73b0cce8dd

Can't manage to create the cluster in ap-southeast-1
Please can anybody take a look

Thx

**Comment by davidopp** [comment]
@justinsb

**Comment by mudrion** [comment]
HI
Is anybody is looking into the issues ?

**Comment by justinsb** [comment]
Ah - sorry I missed this.  I will look into it.

**Comment by MalteJ** [comment]
Same problem here with eu-central-1

**Comment by justinsb** [comment]
@mudrion the first problem is this `export KUBE_AWS_ZONE="ap-southeast-1"` - you need to pick a zone, not a region.  So specify e.g. `export KUBE_AWS_ZONE="ap-southeast-1a"`.  What happens is that we remove the last character to determine the region, so we're trying to match `ap-southeast-`.  I'm going to add the region to the 'region not recognized' error message

@mudrion The second problem could just be that S3 is eventually consistent; I thought we had worked around the worst of these problems by targeting to the correct endpoint, but maybe not...  It might that the script will simply work now (if the bucket has been created) but can you try running this command:

`aws s3 ls --region ap-southeast-1 "s3://kubernetes-staging-7ec2902cbab698915d70af73b0cce8dd"`

(that's the command we actually run: https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/util.sh#L503)

I think I'm also going to increase the timeout here.  5 seconds is needlessly short.

@MalteJ which problem were you hitting?  Was is the AZ/region confusion also?  If so, I'm wondering if we should match against a known list of regions and provide a more direct message.

**Comment by mudrion** [comment]
@justinsb Thank you for tip, after changing to correct region zone fixed the both issues

**Comment by MalteJ** [comment]
hmm, don't know why, but it's working now for me even on eu-central-1.

**Comment by justinsb** [comment]
@MalteJ - glad to hear it!  Do you remember which the error you were hitting?  Hopefully it'll be addressed by one of the patches, but if not I'd like to at least try to fix every problem!

**Comment by MalteJ** [comment]
@justinsb it was something with the staging bucket (like `s3://kubernetes-staging-7ec2902cbab698915d70af73b0cce8dd` but with a different hex code). Can't remember exactly which error it was.

**Comment by justinsb** [comment]
OK thanks @MalteJ, I think that's probably related to #15069.  5 seconds was perhaps an overly optimistic timeout for an eventually consistent system :-)

I'm going to close but feel free to reopen if anything not addressed.
