### ISSUE TITLE
Storage for elasticsearch & influxdb is on ephemeral storage

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#14274]
ElasticSearch and InfluxDB are currently backed by host-volume mounts.  This means that this data is not reliably persisted in case of e.g. machine failure.

This also caused us some problems due to a mistake I made with a very small size of the disk that backs these on AWS, but that is a separate issue (hopefully now fixed & cherry-picked).

(Splitting out some issues out of #13174)

**Comment by justinsb** [comment]
Also presumably as part of this we should figure out how we will stop this data out-growing the backing volume.

**Comment by ngbinh** [comment]
Is there a way for me to point kubernetes to external existing Influxdb and elastic search instead?

**Comment by dchen1107** [comment]
Yes, this is known issue since 1.0 release. We documented somewhere to have persistent storage for both influxDB and ElasticSearch, but I couldn't find them now. 

cc/ @vishh

**Comment by dchen1107** [comment]
cc/ @saad-ali on volume plugin.

**Comment by vishh** [comment]
I'm thinking of not running InfluxDB by default since we can now use
[kubedash](https://github.com/kubernetes/kubedash) for basic cluster
monitoring. Running InfluxDB requires setting up a persistent volume, which
is currently a manual deployment specific operation.

**Comment by vishh** [comment]
It is possible to update the deployment configs to not run elastic search
and influxdb by default. You can simply delete those files from your
branch. After that, you can create a kubernetes service for InfluxDB named
`monitoring-influxdb` in the `kube-system` namespace and add the IP of your
existing InfluxDB deployment as an endpoint in the service. Similarly, you
can create a service for elastic search as well.

**Comment by akomic** [comment]
As one of the solutions to stop data outgrowing the backing volumes influxdb and elasticsearch retention policy could be implemented.

**Comment by vishh** [comment]
@akomic: I like that idea. Will you be able to post a PR?
