### ISSUE TITLE
AWS: Need a better story around ephemeral storage

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#14276]
Instance storage is dependent on the instance type, and this is tricky for users:
- some types include adequate free instance storage (m3.large is 32GB)
- some types include small free instance storage (m3.medium is 4GB)
- some types automatically deploy a backing EBS volume (t2.micro has a 32GB EBS volume)
- some types do not include any instance storage by default (m4 family)

(at least I think that's the case).

We should figure out a sensible approach here that ensures users have sensible storage.  This may turn out to be primarily a docs issue.

**Comment by rca** [comment]
I just ran into this on a week-old cluster.  On `m3.medium` instances, there is plenty of disk on the root partition, however docker's filesystem lives on the tiny 4G partition:

```sh
root@ip-172-20-0-130:~# df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       32G  2.3G   28G   8% /
root@ip-172-20-0-130:~# df -h /mnt/ephemeral/
Filesystem                           Size  Used Avail Use% Mounted on
/dev/mapper/vg--ephemeral-ephemeral  3.9G  3.8G     0 100% /mnt/ephemeral
```

Is there a short-term fix for the time being?

**Comment by rca** [comment]
Answering my own question, I created an EBS volume and manually attached it to the instance as `/dev/xvdz`.  Once the volume was attached I added it to LVM:

```sh
# add the volume to LVM
root@ip-172-20-0-130:~# pvcreate /dev/xvdz
# extend the `vg-ephemeral` volume group
root@ip-172-20-0-130:~# vgextend vg-ephemeral /dev/xvdz
# add all the free space to the full partition
root@ip-172-20-0-130:~# lvextend -r -l +100%FREE /dev/vg-ephemeral/ephemeral
```

**Comment by davidopp** [comment]
ping @justinsb - this is labeled v1.3, should we move it to 1.4 (or next-candidate) ?

**Comment by ericln** [comment]
is `m3.medium` still only have 4G?  is there any workaround for this issue ?

**Comment by justinsb** [comment]
We're not going to be making further changes in kube-up, and kops solves this problem by using an EBS volume always (which then creates a problem/opportunity to make better use of instance storage https://github.com/kubernetes/kops/issues/429 ). Closing.
