### ISSUE TITLE
AWS rebooted spot-instance failed to launch pods because of aufs mount errors

### ISSUE THREAD

**Issue by joshm1** [kubernetes/kubernetes#14285]
I have an auto-scaling group that's a duplicate of the one created by `kube-up` for AWS using Ubuntu 15.04 minions, the only difference being it requests spot instances. When a spot instances is rebooted for whatever reason (they aren't stable), it fails to launch any pods because of an aufs error.  I don't know if this only happens with spot instances, but this was the case for me this time, so it might be relevant. 

This is not the first time I've seen this error.  If I manually terminate the instance, which causes the ASG to request a new spot instance, the new node will launch pods successfully.

```
Error pulling image (prd-beb0010d) from me/project, Driver aufs failed to create image rootfs 08ecf065655b44634e66f45201a7d379d30ba877791b1765322dabf57e993f11: open /mnt/ephemeral/docker/aufs/layers/4a5e6db8c0693a16de88b7559ded7c1cb804018571b137e13abb1713ce6a71cf: no such file or directory
API error (500): error creating aufs mount to /mnt/ephemeral/docker/aufs/mnt/38143c22f7a2644da4bc0cd8782a24a95274eaf255c9468dedbeea2d7c4b2b76-init: invalid argument
```

**Comment by dchen1107** [comment]
Thanks for reporting the issue, and close it as dup of #10959. Please re-open it if you think they are different. Thanks!
