### ISSUE TITLE
Client: golang: Consider auto-retrying failed calls

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14280]
Or offer a setting to do so.

From google-containers:

> I'm building a service that makes much use of the (unversioned) Go client.  I'm concerned about error handling for when connections to the Kubernetes API fail.  Doing a quick scan through the client source, I didn't see any automated retrying of API operations.   Is this the case?   I suppose that I could implement the HTTPClient interface with some retry logic but perhaps there is a better way that I'm just not seeing.  I definitely don't want to have to wrap every client function call in my code with retry logic--there's just too many of them.

I think we do retry if the server specifically says to retry later; perhaps we should consider expanding the set of failure cases that trigger a retry.

@krousey

**Comment by jayunit100** [comment]
cc maybe a tangential relation to your work on the etcd round-robining @timothysc

**Comment by chrissnell** [comment]
Thanks for filing this, @lavalamp.

**Comment by liggitt** [comment]
There are a couple scenarios where retry could make sense:
* rate limiting errors with retry-after header responses (which I don't think are being set right now)... this could be a lower-level retry
* 409 conflict errors - this would probably have to be a higher level retry at the command level where refetching/retrying when a 409 error was encountered would still fulfill the user's intent (e.g. for `kubectl label`, etc)

**Comment by chrissnell** [comment]
For what it's worth, my intent in submitting the original request was to have an automatic way of handling network failures--timeouts, connection refused, etc.--in the rare event that they occur when using the client library.

**Comment by lavalamp** [comment]
409 conflicts need to be explicitly retried by a higher level, the client can't automagically deal with that.

I don't think there's harm in retrying on a network-level error.

**Comment by liggitt** [comment]
> I don't think there's harm in retrying on a network-level error

Depends on the operation... read operations could be retried, idempotent write ones might be able to be

**Comment by lavalamp** [comment]
Yes, all of our writes should be idempotent, and thus definitionally safe
to retry/reexecute.
