### ISSUE TITLE
`rolling-update` requires a unique name when specifying a manifest

### ISSUE THREAD

**Issue by evanphx** [kubernetes/kubernetes#14281]
Per a conversation in slack with @jimmidyson, `rolling-update` should be able to do the same rename dance when a manifest is specified as when `--image` is used.

Right now, it errors out with a message like: `error: pods/catalog.yml cannot have the same name as the existing ReplicationController catalog`

**Comment by bgrant0607** [comment]
Thanks for the suggestion. We're working on a server-side implementation of rolling update instead. It will be possible to enable the experimental API in 1.1:
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/deployment.md

cc @nikhiljindal @ironcladlou
