### ISSUE TITLE
Kubectl describe of pod does not mention job or daemonset

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#14304]
`kubectl describe pods/foo` says, among other things:
`Replication Controllers:	<none>`

There are other types of controllers now, so this should probably be something like:
`Controlled-by: jobs/myjob`
etc..

**Comment by erictune** [comment]
Could wait until jobs/daemonset are out of experimental, or not.

**Comment by erictune** [comment]
Use the `.metadata.annotations` item with key `kubernetes.io/created-by`.

**Comment by mikedanese** [comment]
This is tricky since kubectl has no way of knowing whether experimental is enabled yet. I guess that's not entirely necessary.

**Comment by erictune** [comment]
Yeah, i'd just replace 
```
Replication Controllers: foo
```
with
```
Controllers: ReplicationController/foo
```

The Kind of the controller is evident from the kind in the reference in the created-by field.

**Comment by bgrant0607** [comment]
See also #14961: controllerRef would help
