### ISSUE TITLE
Need Docs for Experimental API use and stability

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#14303]
Put in a doc:

- How to enable experimental (--runtime-config=experimental/v1)
- Whether to expect it to work on GKE
- That we might change the API while it is experimental
- That we might change it when we move out of experimental
- That your clients might break.
- That we might stop supporting the experimental one when it graduates.

Link to that doc from pages that describe experimental features.

**Comment by erictune** [comment]
@bgrant0607

**Comment by bgrant0607** [comment]
See also #14132, #13883

**Comment by lavalamp** [comment]
@erictune Are you planning on sending these docs?

**Comment by davidopp** [comment]
Is there more to do on this beyond #15339?

**Comment by erictune** [comment]
Closed by #15339
