### ISSUE TITLE
Deprecate apiversion field in kubeconfig file

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14318]
https://github.com/kubernetes/kubernetes/blob/80775b44d1187805119bbbbb8c3f3242d1279bb1/pkg/client/unversioned/clientcmd/api/v1/types.go#L58

It doesn't make sense to have this field in the config file. I don't think we even need to replace it with a list of preferred versions, either, I think we should just remove it. (Well, deprecate & stop using it.)

Note that this affects every binary we have except for apiserver, since they all use this file to find the apiserver.

**Comment by lavalamp** [comment]
@JanetKuo This is the field I was talking about.

**Comment by liggitt** [comment]
I'm pretty sure there is defaulting code in place if that field is missing or unspecified, so removing it may have minimal impact on older clients...

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
@lavalamp could you update your first comment:

>  I don't think we even need to replace it with a list of preferred versions, either, I think we should just remove it

because we *are* replacing it with preferred-versions. This is useful because users can specify the preferred version in kubeconfig rather than selecting the version via --api-version every time.

cc @bgrant0607

**Comment by lavalamp** [comment]
I recall being convinced that we had to put in a preferred version list, although I can't remember what convinced me now, and I still wish we didn't have to. But I guess it was a good enough reason to convince past-me.

**Comment by caesarxuchao** [comment]
I think this is what I said last time, "This is useful because users can specify the preferred version in kubeconfig rather than selecting the version via --api-version every time."

Anyway, we need to sync with @bgrant0607, he thinks we shouldn't specify any version in kubeconfig.

**Comment by caesarxuchao** [comment]
According to in-person discussion with @bgrant0607, we are on the same page: we need PreferredVersions field in kubeconfig. What Brian means is that we don't need to go through the deprecation process for the APIVersion field, as we only supported one version.

**Comment by lavalamp** [comment]
Ah, ok. Yes, I buy that.

**Comment by nikhiljindal** [comment]
As per discussion with @lavalamp the updated consensus is to deprecate the apiversion field from kubeconfig (ignore it if its present).
Users will specify the version, if they want as part of the kubectl command. So that commands have the same behavior no matter where and by which user they are run.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/22410 deprecates that field

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/22410
