### ISSUE TITLE
Create daemon set test where a new node is added with a matching label

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#14314]
and verify the daemon is started on it.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by lukaszo** [comment]
@kargakis this issue is two years old. I think this commit https://github.com/kubernetes/kubernetes/commit/5468773b837602b310f2a1b031ac3e495d8bec46 with other tests more or less is doing what's described in the issue.
Do we need more tests?

**Comment by gyliu513** [comment]
I think this can be closed as I already added a new test case for this here https://github.com/kubernetes/kubernetes/pull/46695

And it is already merged https://github.com/kubernetes/kubernetes/blame/master/pkg/controller/daemon/daemoncontroller_test.go#L941-L950

@davidopp @lukaszo @kargakis

**Comment by kargakis** [comment]
Yes, that seems enough, thanks!
