### ISSUE TITLE
Experimental: DaemonSet: describe not implemented.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#14313]
@AnanyaKumar

**Comment by mikedanese** [comment]
bug https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe.go#L72

**Comment by erictune** [comment]
Oh.  that line needs to be under expDescriberMap

**Comment by AnanyaKumar** [comment]
@erictune Thanks! I looked a bit into it, but couldn't figure out the issue - I'm not too familiar with experimental.
