### ISSUE TITLE
Add MetaRESTClient between RESTClient and (high-level) Client

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14321]
The request here is basically to keep a collection of RESTClients around, one for each group/version.

This code should then be replaced; both the experimental-group client and the regular-group client should be gotten from this pool of clients. https://github.com/kubernetes/kubernetes/blob/bdfd469a85f734468525b5ab53e99034e7061e09/pkg/kubectl/cmd/util/factory.go#L141

**Comment by lavalamp** [comment]
@smarterclayton @JanetKuo - Filing this based on our discussions.

**Comment by smarterclayton** [comment]
ClientCache is filling some of this role today - it should be possible to initialize this meta-client via what we call "discovery" or via direct calls to populate it, and then ClientForMapping in kubectl should become a thin wrapper, as well as the Client() call being another thin wrapper.

**Comment by lavalamp** [comment]
Yeah, @caesarxuchao and I discussed this some today. ClientCache should be moved into the client library, it should become a layer between RESTClient & the high-level client, and version negotiation needs to be fixed up a bit.

I think additionally RESTClient should be turned into an interface.

**Comment by smarterclayton** [comment]
This was not high priority :)

Closing due to age, reopen if we have concrete steps here.
