### ISSUE TITLE
Flocker volume plugin

### ISSUE THREAD

**Issue by mattbates** [kubernetes/kubernetes#14327]
[Flocker] [1] is an open-source container data volume manager for Dockerized applications.

This [PR adds a volume plugin for Flocker] [2].
The plugin interfaces the [Flocker Control Service REST API] [3] to request volume creation and attachment.

Each kubelet host should run Flocker agents (Container Agent and Dataset Agent).

The kubelet will also require environment variables that contain the host and port of the Flocker Control Service. (see [Flocker architecture] [4] for more).

- FLOCKER_CONTROL_SERVICE_HOST
- FLOCKER_CONTROL_SERVICE_PORT

The contribution introduces a new 'flocker' volume type to the API with fields:

- datasetName: which indicates the name of the dataset in Flocker added
  to metadata;
- size: a human-readable number that indicates the maximum size of the
  requested dataset.

Full documentation (including getting started guides) and e2e tests to follow.

As the plugin is near code complete, we're hoping to make version 1.1.

[1]: https://clusterhq.com/flocker/introduction/
[2]: https://github.com/kubernetes/kubernetes/pull/14328
[3]: https://docs.clusterhq.com/en/1.3.1/reference/api.html
[4]: https://docs.clusterhq.com/en/1.3.1/concepts/architecture.html

**Comment by gmarek** [comment]
cc @thockin @bgrant0607

**Comment by pmorie** [comment]
#14328

**Comment by bgrant0607** [comment]
Thanks. Yesterday was our 1.1 feature-complete deadline and we're now focused on fixing tests and otherwise stabilizing the release, so it may be a few days before we can take a look.
