### ISSUE TITLE
GKE Release Notes possibly outdated

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#14338]
Looking at this page: https://cloud.google.com/container-engine/release-notes#supported_kubernetes_api_versions

It seems that:

1. GCE is running a Kubernetes master version (`1.0.3`) that was released a month and a half ago
2. the Release Notes itself are almost a month old, while updates where more frequent before

Granted, 1,5 month is not that long, but in Kubernetes-development time that's still three releases behind.

I mainly ask because I am interested in upgrading our client nodes to the latest stable version, but am unsure that this is possible right now at GCE?

**Comment by roberthbailey** [comment]
Sorry @JeanMertz -- those release notes have gotten a bit out of date. We have new release notes that have just been published showing that `1.0.6` is currently the default version for new clusters and also the version to which you can upgrade your nodes.
