### ISSUE TITLE
GKE: Kubernetes semi-manual upgrades

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#14339]
Currently, upgrading involves something like:

```
gcloud container clusters upgrade NAME --cluster-version 1.0.6
```

which will re-create all nodes one by one.

While this is a great feature to have, we are running [Vault](https://vaultproject.io) on top of our cluster, which requires a manual *unseal* of each running Vault instance after it restarts, for enhanced security.

This means that, for truely zero-downtime upgrades, we'd need a way to:

1. mark a node as [unschedulable](https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/admin/cluster-management.md#maintenance-on-a-node)
2. upgrade that single node
3. make sure at least _one_ instance of Vault is running on that node
4. unseal Vault
5. we are now ensured of one unsealed vault being available during the next steps
5. upgrade all other nodes at will

Is this possible? In effect, I am trying to manually reproduce the "Node Upgrades" [documentation](https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/admin/cluster-management.md#node-upgrades):

> Node upgrades for GKE and GCE-OSS again use a Managed Instance Group, each node is sequentially destroyed and then recreated with new software.

*As mentioned elsewhere, running two clusters could solve this problem, but that's a bridge too far right now, in terms of engineering effort and costs*

**Comment by gmarek** [comment]
cc @bgrant0607 @fgrzadkowski

**Comment by bgrant0607** [comment]
Related: #3885

**Comment by roberthbailey** [comment]
Also see https://github.com/kubernetes/kubernetes/issues/6080 and https://github.com/kubernetes/kubernetes/issues/5511.

**Comment by bgrant0607** [comment]
What runs Vault in this case?

It sounds like being able to specify a node readiness probe could solve the problem. We probably want to monitor node availability similar to how we monitor pod availability during rolling update: #11484.

**Comment by erictune** [comment]
@kubernetes/goog-gke 

From the docs (`gcloud container clusters upgrade --help`) it says that during a node upgrade, *all of the cluster's nodes will be deleted and recreated one at a time*.   What condition is waited for to ensure "one at a time" behavior?

**Comment by alex-mohr** [comment]
GKE currently uses the Managed Instance Group Updater service: https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service

It specifies InstanceStartupTimeoutSec: 300 and MaxNumConcurrentInstances: 1.  (https://cloud.google.com/compute/docs/instance-groups/updater/v1beta1/rollingUpdates)

I don't think there's a way atm to specify a particular health check url for node healthiness, but am not familiar with the details.

**Comment by roberthbailey** [comment]
There isn't a way to specify a custom healthcheck for managed instance groups or for the updater service. Nodes are updated one at a time but are assumed healthy (such that the updater continues with the next node) once the instance is running rather than when the kubelet is configured and posting a ready status to the apiserver.

**Comment by JeanMertz** [comment]
Has anything changed regarding my original request since 1.2 shipped?

I found the `kubectl drain` command, and used that to empty a single node. But I'm still left with one problem:

I can _delete_ the node from the GCE interface, but that simply spins up a new instance with the _old_ deploy scripts, and thus it won't result in an upgraded node.

Is there any way to "preload" the new deploy scripts in the instance groups. So that new machines are automatically using the upgraded Kubernetes version? Or can this be accomplished some other way?

**Comment by ihmccreery** [comment]
You should be able to change the instance group template and then make requests to recreate the instances:

1. [Change the instance template for a managed instance group](https://cloud.google.com/compute/docs/instance-groups/#set_group_template)
1. [Recreate instances in the group](https://cloud.google.com/compute/docs/instance-groups/#recreate_instances)

Note that deleting the instance manually will cause the instance group to recreate the instance at the *old* template ([Creating groups of instances](https://cloud.google.com/compute/docs/instance-groups)).

**Comment by JeanMertz** [comment]
@ihmccreery that still feels like a lot of manual labour. More specifically, getting the upgraded GKE instance group template might be problematic.

I can switch out all mentions of `1.2.0` to `1.2.4` in our case, but that doesn't work, as I'm sure other variables/scripts are updated as well by Google folks. I could of course spin up a new cluster, and take the scripts from there, but again, that feels like a lot of workarounds to say "upgrade this single node to the latest version of Kubernetes".

**Comment by roberthbailey** [comment]
@JeanMertz -- Can you use node pools to solve this use case?

1. Create a new node pool at the version you want to upgrade to
1. Sequentially drain each node from the old node pool (this should move a vault instance to a new node)
1. Unseal the vault instance
1. Once all nodes in the old node pool have been drained, delete the old node pool

This will give you very fine grained control over the upgrade process, at the cost of having twice as many nodes running in your cluster for the time of the upgrade. You can also create the new node pool at size 1 and then scale it up one-by-one and delete nodes from the old pool one-by-one if you want to trade off some complexity for reduced costs during the upgrade.

**Comment by JeanMertz** [comment]
@roberthbailey ah yes, great feature!

I've now read https://cloudplatform.googleblog.com/2016/05/introducing-Google-Container-Engine-GKE-node-pools.html, and that totally solves this problem.

I'll be upgrading today, and close this issue if all goes well and this features solves the original problem, but it certainly looks like it will (for future readers: the blog post has this exact upgrade scenario described in detail).

**Comment by JeanMertz** [comment]
Yep, This worked as expected. Thank you.

**Comment by roberthbailey** [comment]
Awesome!
