### ISSUE TITLE
Experimental: DaemonSet: needs Status Update

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#14344]
daemonset is not installing a status endpoint.
It should.
Just copy what was done in #14343 since Job had the exact same issue.

**Comment by erictune** [comment]
The primary daemonset endpoint should disallow updates of status.

**Comment by erictune** [comment]
@AnanyaKumar @mikedanese

**Comment by AnanyaKumar** [comment]
Thanks @mikedanese !

**Comment by derekwaynecarr** [comment]
@mikedanese - I can add this if you are blocked on time.

**Comment by bgrant0607** [comment]
That is, a status subresource

**Comment by mikedanese** [comment]
Feel free to knock it out @derekwaynecarr otherwise I will get to it tonight or tomorrow

**Comment by derekwaynecarr** [comment]
Taking this over.  I am almost done, will submit PR tomorrow.

**Comment by bgrant0607** [comment]
Would be great to do this for ReplicationController, also: #4909
