### ISSUE TITLE
NFS: PVC can get all the PV's accessmode instead of what PVC asked for

### ISSUE THREAD

**Issue by chao007** [kubernetes/kubernetes#14340]
Description:
After PVC is bond to PV, check the pvc info, can get all the pv's accessmode
there is a problem that the pvc can get all the pv's accessmode, not only the ROX, bug also RWO.
this is not security for the PV because users can change the pvc to get more access right.

Steps to Reproduce:
1, create pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1
spec:
  capacity:
    storage: 10Gi
  accessModes:
     - ReadOnlyMany
     - ReadWriteOnce
  nfs:
    path: /chaotest
    server: 10.14.6.144
2.create pvc with accessmode ROX
{
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "metadata": {
        "name": "myclaim-1"
    },
    "spec": {
        "accessModes": [ "ReadOnlyMany" ],
        "resources": {
            "requests": {
                "storage": "5Gi"
            }
        }
    }
}
3. check pv info
[root@dhcp-128-79 kubernetes]# cluster/kubectl.sh get pv
NAME      LABELS    CAPACITY   ACCESSMODES   STATUS    CLAIM               REASON    AGE
nfs1      <none>    10Gi       ROX,RWO       Bound     default/myclaim-1             3m
4.check the pvc info
[root@dhcp-128-79 kubernetes]# cluster/kubectl.sh get pvc
NAME        LABELS    STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
myclaim-1   <none>    Bound     nfs1      10Gi      ROX,RWO       5s
Actual results:
PVC accessmode info is RWO,ROX
Expected results:
PVC accessmode info should only be ROX

**Comment by gmarek** [comment]
cc @thockin

**Comment by markt-gh** [comment]
This is a feature, not a bug.

A PVC can request just RWX but it will get RWO+ROX because NFS, for
example, has all of them.

The user can expect the *minimum* to be what was requested (size & access
modes) but they may get more. This is by design.
