### ISSUE TITLE
Cephfs: "Permission denied" when read or write in dir of the cephfs mounted with selinux is enforced

### ISSUE THREAD

**Issue by chao007** [kubernetes/kubernetes#14349]
when set selinux is Enforce, got "Permission denied" when read or write in the dir ceph volume mounted , after setenforce 0,  could read or write to the dir

Steps to Reproduce:
1.create a pod with cephfs , the pod is running 
[root@dhcp-128-79 kubernetes]# cluster/kubectl.sh get pods -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: 2015-09-22T03:36:58Z
    name: cephfs
    namespace: default
    resourceVersion: "46979"
    selfLink: /api/v1/namespaces/default/pods/cephfs
    uid: 2d9fba37-60db-11e5-89f4-fa163ef53087
  spec:
    containers:
  - image: jhou/hello-openshift
    imagePullPolicy: IfNotPresent
    name: cephfs-rw
    resources: {}
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /mnt/cephfs
      name: cephfs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-bcpqn
      readOnly: true
      dnsPolicy: ClusterFirst
      nodeName: 127.0.0.1
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
  - cephfs:
      monitors:
    - 192.168.0.130:6789
    - 192.168.0.131:6789
    - 192.168.0.132:6789
    - 192.168.0.147:6789
      secretFile: /etc/ceph/admin.secret
      user: admin
      name: cephfs
  - name: default-token-bcpqn
    secret:
      secretName: default-token-bcpqn
    status:
    conditions:
  - status: "True"
    type: Ready
    containerStatuses:
  - containerID: docker://2e0e6d6dfc7686eea6fa8d14c9eac994b371d3a36c79e4c6fb1d7d2d751a54e4
    image: jhou/hello-openshift
    imageID: docker://6598e12f7b1839dfc18575157c45d5b78b25ecba8937e9e0247d1f0cc3af8f6f
    lastState: {}
    name: cephfs-rw
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2015-09-22T03:36:59Z
    hostIP: 127.0.0.1
    phase: Running
    podIP: 172.17.0.15
    startTime: 2015-09-22T03:36:58Z
    kind: List
    metadata: {}

2.check the selinux is Enforce
[root@dhcp-128-79 kubernetes]# getenforce
Enforcing
3.try to read or write some data in the pod
[root@cephfs cephfs]# ls
ls: cannot open directory .: Permission denied
[root@cephfs mnt]# ls -Zd
drwxr-xr-x. root root system_u:object_r:svirt_sandbox_file_t:s0:c186,c618 .
1. set the selinux is Permissive
2. try to read or write some data in the pod
   [root@dhcp-128-79 kubernetes]# cluster/kubectl.sh exec cephfs -ti -- bash
   [root@cephfs /]# cd /mnt/cephfs/
   [root@cephfs cephfs]# ls
   testfile1  testfile2
   [root@cephfs cephfs]# touch hi
   [root@cephfs cephfs]# ls
   hi  testfile1  testfile2

Actual results:
when set selinux is Enforce, got "Permission denied" when read or write in the dir ceph volume mounted 

Expected results:
when set selinux is Enforce, could read or write to the cehp volume when ir rw file system.

**Comment by gmarek** [comment]
cc @thockin

**Comment by erictune** [comment]
@kubernetes/rh-cluster-infra

**Comment by erictune** [comment]
@rootfs

**Comment by pmorie** [comment]
@chao007 could you send the output of:

`sudo ausearch -m AVC -ts recent`

?

**Comment by chao007** [comment]
@pmorie 
----
time->Tue Sep 22 13:15:53 2015
type=SYSCALL msg=audit(1442898953.429:169649): arch=c000003e syscall=2 success=yes exit=3 a0=7ffe95a08e01 a1=941 a2=1b6 a3=7ffe95a07b20 items=0 ppid=31413 pid=31461 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=4294967295 comm="touch" exe="/usr/bin/touch" subj=system_u:system_r:svirt_lxc_net_t:s0:c331,c740 key=(null)
type=AVC msg=audit(1442898953.429:169649): avc:  denied  { write } for  pid=31461 comm="touch" path="/mnt/cephfs/hi" dev="ceph" ino=1099511628782 scontext=system_u:system_r:svirt_lxc_net_t:s0:c331,c740 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
type=AVC msg=audit(1442898953.429:169649): avc:  denied  { create } for  pid=31461 comm="touch" name="hi" scontext=system_u:system_r:svirt_lxc_net_t:s0:c331,c740 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file
type=AVC msg=audit(1442898953.429:169649): avc:  denied  { add_name } for  pid=31461 comm="touch" name="hi" scontext=system_u:system_r:svirt_lxc_net_t:s0:c331,c740 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir
type=AVC msg=audit(1442898953.429:169649): avc:  denied  { write } for  pid=31461 comm="touch" name="/" dev="ceph" ino=1 scontext=system_u:system_r:svirt_lxc_net_t:s0:c331,c740 tcontext=system_u:object_r:unlabeled_t:s0 tclass=dir

**Comment by pmorie** [comment]
@rootfs Is there an selinux boolean for ceph that needs to be enabled?

**Comment by rootfs** [comment]
@pmorie @chao007 looking now

**Comment by rootfs** [comment]
@pmorie @chao007 I opened an issue with ceph
http://tracker.ceph.com/issues/13231

**Comment by ibotty** [comment]
This is still an issue, though arguably not one for kubernetes to fix.
/remove-lifecycle stale

**Comment by mcronce** [comment]
I originally saw this in 1.7.x, confirming it's still an issue in 1.9 (granted 1.9.1, running out of Fedora 27 repos)
