### ISSUE TITLE
Vagrant can't download virtualbox image

### ISSUE THREAD

**Issue by tedstirm** [kubernetes/kubernetes#14361]
I was going through the getting started guide and tried to bring up kubernetes using vagrant. However, it can't seem to find the vagrant images.

http://kubernetes.io/v1.0/docs/getting-started-guides/vagrant.html

$ ./cluster/kube-up.sh                                                                                 
Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Using credentials: vagrant:vagrant
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'minion-1' up with 'virtualbox' provider...
==> master: Box 'kube-fedora21' could not be found. Attempting to find and install...
    master: Box Provider: virtualbox
    master: Box Version: >= 0
==> master: Box file was not detected as metadata. Adding it directly...
==> master: Adding box 'kube-fedora21' (v0) for provider: virtualbox
    master: Downloading: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-21_chef-provisionerless.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 503 Service Unavailable

**Comment by tedstirm** [comment]
I can download image from link, so issue must be on my end.

**Comment by sunsongxp** [comment]
This also happens to me, I can download the link blow, but the script still raise this error

```
➜  kubernetes ./cluster/kube-up.sh
... Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node-1' up with 'virtualbox' provider...
==> master: Box 'kube-fedora23' could not be found. Attempting to find and install...
    master: Box Provider: virtualbox
    master: Box Version: >= 0
==> master: Box file was not detected as metadata. Adding it directly...
==> master: Adding box 'kube-fedora23' (v0) for provider: virtualbox
    master: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-23_chef-provisionerless.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
```

**Comment by sunsongxp** [comment]
it works after I upgraded to latest vagrant.
