### ISSUE TITLE
vsphere provider 'kube-down.sh' deletes .vmdk

### ISSUE THREAD

**Issue by Symmetric** [kubernetes/kubernetes#14368]
When using the vsphere provider, and following the [guide](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/vsphere.md), if I run `cluster/kube-down.sh`, then `cluster/kube-up.sh`, I get the following error:

```
+ govc vm.create -debug -disk=./kube/kube.vmdk -g=debian7_64Guest -link=true -c 1 -m 1024 kubernetes-master
Error: datastore directory does not exist
```

I then have to re-run the step from the guide `govc import.vmdk kube.vmdk ./kube/` to get things working again.

I expect to be able to run `kube-down` and `kube-up` without having to run anything else in between; this is the case for all the other k8s providers that I have used.

**Comment by erictune** [comment]
@pietern

**Comment by javierjeronimo** [comment]
Failed execution of kube-up also removes vmdk!!!
