### ISSUE TITLE
vspere cloud provider fails if multiple ESX networks are present

### ISSUE THREAD

**Issue by Symmetric** [kubernetes/kubernetes#14363]
When attempting to create a Kubernetes cluster using KUBERNETES_PROVIDER=vsphere, I get the following error:

```
$ cluster/kube-up.sh 
... Starting cluster using provider: vsphere
... calling verify-prereqs
... calling kube-up
Starting master VM (this can take a minute)...
Error: default network resolves to multiple instances, please specify
```

Following the thread a bit, this is because the instructions don't mention that you need to set the `GOVC_NETWORK` flag if your vcenter manages multiple networks (similarly, it omits the GOVC_DATACENTER flag which was also necessary in my case to upload the kube.vmdk file).

Setting the `GOVC_NETWORK` env variable (using the output of `govc ls /<datacenter name>/network`) has got me past this issue.

**Comment by erictune** [comment]
@pietern
