### ISSUE TITLE
Build a Endpoints / modification E2E test.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#14371]
I've been hacking around with the `master.go` implementation in #13978 ,  and stumbled on the fact that I think we don't have an E2E test which modifies a service endpoint IP address.

If we can create such a test, i.e., one which runs this in an e2e fashion, continually modifying services and confirming that they continue to stay functional.  We will be putting a good regression of the api behaviour/stability for HA modifications.

So, for this issue, lets:

1) Confirm that e2e tests are missing an endpoint modification test (I could be missing something)!  If we need one, then proceed to ->
2) Create a test which implements the above logic from `controller_test.go` as part of an end 2 end functionality suite .

**Comment by cmluciano** [comment]
Is this still relevant? Should this be tagged with SIG-Apps?
