### ISSUE TITLE
Kubernetes.io website has insufficient visual indication that there's content if the user scrolls down

### ISSUE THREAD

**Issue by mansoorj** [kubernetes/kubernetes#14376]
I myself didn't know for the longest time that there's more content below the fold, and I can bet you many other users would completely miss most of the content on the main page as well. 

I've seen other websites with a similar design (e.g. Google Drive) have a conspicuous down-arrow. Alternately have some of the content that's down below peak a little above the fold. There should be some indication that there's more content down there. 

![screen shot 2015-07-28 at 3 01 43 pm](https://cloud.githubusercontent.com/assets/11891117/10029985/14621bf6-612a-11e5-85ce-b70fddf5dff9.png)

**Comment by bgrant0607** [comment]
cc @RichieEscarez 

I agree this is a problem. I never scroll down.

**Comment by mansoorj** [comment]
What's the process for getting it triaged? Any update?

**Comment by bgrant0607** [comment]
Still a problem.

**Comment by bgrant0607** [comment]
Easiest thing might be to move the content below to a separate page and add a button to get to it.

**Comment by bgrant0607** [comment]
This is resolved by the redesign.
