### ISSUE TITLE
Document how to write good tests

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14370]
* Unit tests (table driven, etc.)
* Integration tests (including dealing with issues like multiple tests running concurrently)
* e2e tests

We have a few testing conventions here:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/coding-conventions.md

We want more tests, but not flaky tests.

cc @quinton-hoole @saad-ali @thockin @lavalamp

**Comment by bgrant0607** [comment]
We mention table-driven testing, but we should also link to good references, such as https://github.com/golang/go/wiki/TableDrivenTests

**Comment by bgrant0607** [comment]
@ihmccreery @goltermann @sarahnovotny

**Comment by ihmccreery** [comment]
@quinton-hoole seems like the clear candidate to take this on.  Assigning to him.

**Comment by quinton-hoole** [comment]
I did the e2e testing doc in #20041.  
I'll leave it to @kubernetes/goog-testing to decide what to do with integration and unit tests,as they've fallen somewhat into disrepair, and, I believe, are under review for a refresh.
