### ISSUE TITLE
_output/ partially owned by root

### ISSUE THREAD

**Issue by mvdan** [kubernetes/kubernetes#14378]
After running `build/release.sh`, the `_output/` directory is partially owned by root:

```
$ git clean -dffx
Removing Godeps/_workspace/pkg/
warning: failed to remove _output/dockerized/bin/linux/amd64/mungedocs
warning: failed to remove _output/dockerized/bin/linux/amd64/genswaggertypedocs
[...]
warning: failed to remove _output/dockerized/bin/windows/amd64/ginkgo.exe
warning: failed to remove _output/dockerized/bin/test_for_remote
Removing _output/images
Removing _output/release-stage
Removing _output/release-tars
Removing _output/local
```

None of the scripts in `build/` seem to use `sudo` for any involved commands, so I'm not sure what could be causing this. Perhaps the resulting binaries obtained from the build in the Go 1.4 container are just copied over, and the container runs the build as root?

For what it's worth, the regular user I'm logged in as can build/remove docker images without superuser permissions.

**Comment by mvdan** [comment]
As a confirmation, since `git clean` doesn't specify that root ownership is the cause:

```
$ find _output/ -type f | xargs ls -la
-rwxr-xr-x 1 root root 27711184 Sep 29 13:54 _output/dockerized/bin/darwin/386/e2e.test
-rwxr-xr-x 1 root root 17545708 Sep 29 13:54 _output/dockerized/bin/darwin/386/genbashcomp
-rwxr-xr-x 1 root root 12707452 Sep 29 13:54 _output/dockerized/bin/darwin/386/genconversion
[...]
```

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by thockin** [comment]
This should be fixed for a while now.
