### ISSUE TITLE
kube-ui does not show components form namespaces other than "default"

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes/kubernetes#14389]
It appears that kube-ui supports only 'default' namespace.
Any pod,rc,service created in namespaces other than 'default' are not shown/accessible via kube-ui.

**Comment by emmanuel** [comment]
Duplicate of https://github.com/kubernetes/kube-ui/issues/5

**Comment by ichekrygin** [comment]
missed the original, thx.
