### ISSUE TITLE
kube-controller-manager is stuck on creating external loadbalancer

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes/kubernetes#14388]
k8s build: 1.0.5
platform: aws-ec2
specifics: provisioning kubernetes cluster onto existing VPC

* create service

steps: create service with external loadbalancer option
expected: ec2 elb is create
actual: ec2 elb is not create and kube-controller is looping (as it appears infinitely) and reports:

```
Tue, 22 Sep 2015 15:46:15 -0700   Tue, 22 Sep 2015 16:05:22 -0700   385       my-service   Service             CreatingLoadBalancer   {service-controller }   creating loadbalancer
Tue, 22 Sep 2015 15:46:15 -0700   Tue, 22 Sep 2015 16:05:22 -0700   385       my-service   Service             CreatingLoadBalancerFailed   {service-controller }   error creating loadbalancer (will retry): failed to create external loadbalancer for service integration/my-service: Unable to find VPC
```

* delete service

steps: delete service (created above)
expected: service removed and kube-controller stops all attempts to create external loadbalancer
actual: service is remove, but kube-controller is continues to loop trying (and failing) to create external loadbalancer for now deleted service.
note: restarting kube-controller-manager seems to work in breaking the loop.

**Comment by thockin** [comment]
@justinsb @a-robinson

**Comment by ichekrygin** [comment]
Update: this is still an issue w/ 1.1.7
```
6h        <invalid>   39301     jenkins   Service             CreatingLoadBalancer   {service-controller }   Creating load balancer
6h        <invalid>   294       jenkins   Service             CreatingLoadBalancerFailed   {service-controller }   Error creating load balancer (will retry): Failed to create load balancer for service default/jenkins: InvalidPermission.Duplicate: the specified rule "peer: 0.0.0.0/0, TCP, from port: 80, to port: 80, ALLOW" already exists
          status code: 400, request id:
6h        <invalid>   39302     jenkins   Service             CreatingLoadBalancer   {service-controller }   Creating load balancer
```

As before, restarting `k8s_kube-controller-manager` fixes this issue

**Comment by thockin** [comment]
Can you retest this against 1.2.5 or 1.3.0 ?  I'm going close it as "old" but if it persists, please re-open!!
