### ISSUE TITLE
Integration test: watches scale to 100's-1000's of watchers without dropping

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14386]
Branched from #14273.

I'm examining logs from http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-scalability/2507/

The specific failure is `gave up waiting for pod 'density-latency-pod-13a751c5-6114-11e5-9c0e-42010af01555-4' to be 'running' after 5m0s`

That pod is on node `e2e-scalability-minion-rrnh`. Here's some logs in the midst of the problematic behavior.

```
I0922 10:36:13.884852       5 handlers.go:143] GET /api/v1/pods?fieldSelector=spec.nodeName%3De2e-scalability-minion-rrnh: (18.485022573s) 200 [[kubelet/v1.1.0 (linux/amd64) kubernetes/09cf38e] 10.240.84.162:39917]
...
I0922 10:36:14.667254       5 handlers.go:143] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3De2e-scalability-minion-rrnh&resourceVersion=338101: (709.10701ms) 0 [[kubelet/v1.1.0 (linux/amd64) kubernetes/09cf38e] 
...
I0922 10:36:27.254781       5 handlers.go:143] GET /api/v1/pods?fieldSelector=spec.nodeName%3De2e-scalability-minion-rrnh: (11.524191846s) 200 [[kubelet/v1.1.0 (linux/amd64) kubernetes/09cf38e] 10.240.84.162:39917]
...
goroutine 1337888 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2b1e7a480, 0x1f4)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f4c2d21b238, 0xc2080f7120, 0x7f4c2d21b9d0, 0xc2e6266a00, 0x7f4c2d069698, 0xc2b1e7a480, 0x1)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:399 +0x2b7
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7f4c2d215f40, 0xc2e3f47d00, 0x7f4c2d21b238, 0xc2080f7120, 0x7f4c2d069698, 0xc2b1e7a480, 0xc2c6ad8760)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:406 +0xab
k8s.io/kubernetes/pkg/apiserver.func·027(0xc211459ad0, 0xc2b1e7a540)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:256 +0xc2a
github.com/emicklei/go-restful.func·009(0xc211459ad0, 0xc2b1e7a540)
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc211459b60, 0xc211459ad0, 0xc2b1e7a540)
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc211459ad0, 0xc2b1e7a540, 0xc211459b60)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:61 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc211459b60, 0xc211459ad0, 0xc2b1e7a540)
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2082a8090, 0x7f4c2d069698, 0xc2b1e7a480, 0xc213644b60)
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246 +0xee3
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f4c2d069698, 0xc2b1e7a480, 0xc213644b60)
    /go/src/k8s.io/kubernetes/Godeps/_workspa [[kubelet/v1.1.0 (linux/amd64) kubernetes/09cf38e] 10.240.252.125:54303]
E0922 10:36:31.057767       5 errors.go:62] apiserver received an error that is not an unversioned.Status: too old resource version: 338159 (341885)
I0922 10:36:31.057953       5 handlers.go:143] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3De2e-scalability-minion-rrnh&resourceVersion=339493: (3.717997659s) 500
```

Note that the stack trace and the error lines don't correspond exactly, because threading and many similar things fail simultaneously.

List/watch behavior is problematic. There's two examples above. In the first, the list took 18 (!) seconds, and the watch ended (unknown reason) after only 700ms. In the second, the list took 11s, and when the watch was attempted only 4 seconds later, it was already too late, the resource version was out of date.

So my request here is an integration (or unit) test that directly tests that watches do not drop under these circumstances. It should be possible to write this test given @wojtek-t's new cacher.

**Comment by lavalamp** [comment]
(And the idea is that in the process of writing this test we would find and fix this bug.)

**Comment by lavalamp** [comment]
Downgrading to P1 because this probably isn't the root cause of #14273

**Comment by lavalamp** [comment]
@wojtek-t maybe you can look at this when you get back from vacation in a few days?

**Comment by wojtek-t** [comment]
>
So my request here is an integration (or unit) test that directly tests that watches do not drop under these circumstances. It should be possible to write this test given @wojtek-t's new cacher.

Can you please clarify a bit? I'm happy to write more advanced unit/integration tests but I don't understand what did you mean by that.

BTW, it seems that those 18s lists were due to some other issues in the system, which should hopefully be fixed now.

**Comment by lavalamp** [comment]
Basically, I'm looking for a test, probably in integration, that:
1. Sets up N watchers
2. Writes X things (pods?), and does Y updates to each of them.
3. Verifies that all of the items were delivered, and that no watches closed unexpectedly.

Then I'd like to see a run with a big value for N, and one with a big value for Y, at the same time if it doesn't make shippable fall over.

Basically, if our watch infrastructure can't handle load, I want to detect that before we break the scalability e2e.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
