### ISSUE TITLE
Investigate Jenkins log file upload

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14382]
This run appears to have uploaded only about 1/3rd of the available logs. http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-scalability/2511/gcsObjects/

I checked another run and it was fine, so I'll do my debugging on that one. But we should figure out what happened to this run.

**Comment by ixdy** [comment]
Closing as obsolete. We've improved our infra since then, too.
