### ISSUE TITLE
kubelet: test steady-state pod status update rate

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14391]
It should do zero updates in steady-state!

Split off from #14273

**Comment by yujuhong** [comment]
Lowered the priority, pending discussion of the pod status update frequency and more in #14393.

**Comment by yujuhong** [comment]
Assigning to @Random-Liu since he has related PRs for checking the pod status updates in the test.

**Comment by ehashman** [comment]
/remove-lifecycle frozen
/close

This is a test failure tracking issue from 2015, I don't think it's still relevant.
