### ISSUE TITLE
Containerized kubelet cannot manage image garbage collection properly

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#14403]
Part of #13627
```
$ log for kubelet
E0906 09:56:50.896731       1 kubelet.go:737] Image garbage collection failed: non-existent label "docker-images"
```

The gc problem of cadvisor is because it cannot check the mount point of /var/lib/docker.
```
$ mount info for kubelet
Filesystem partitions: map[/dev/mapper/ubuntu--vg-root:{mountpoint:/rootfs major:252 minor:0} /dev/sda1:{mountpoint:/rootfs/boot major:8 minor:1}]\n","stream":"stderr","time":"2015-09-06T09:11:50.726997545Z"}
```
Hence it wont add the required label.

Yet we do have this in the containerized kubelet 
```
# cat /proc/self/mountinfo | grep '/var/lib/docker '
275 181 252:0 /var/lib/docker /var/lib/docker ro,relatime - ext4 /dev/mapper/ubuntu--vg-root rw,errors=remount-ro,data=ordered
```
It's deprecated by https://github.com/google/cadvisor/blob/master/fs/fs.go#L88
'cause we have following already
```
# mount -l | grep '/dev/mapper/ubuntu--vg-root' 
/dev/mapper/ubuntu--vg-root on /rootfs type ext4 (ro,relatime,errors=remount-ro,data=ordered)
```
Related to #4869
/cc @fgrzadkowski

**Comment by fgrzadkowski** [comment]
Assigning to myself because I'm working on containerized kubelet. Will reassign if needed.

**Comment by luxas** [comment]
How is it going? 
This patch will be useful.

**Comment by dalanlan** [comment]
Backlogged for quite a while. I'll get into this once i'm available:)

**Comment by dalanlan** [comment]
#16563 explains this at a high level

> Kubelet can manage only one storage partition as of today. 
> Kubelet uses cadvisor to identify and track the overall usage of the partition where docker's storage directory is located. 
> If the docker daemon's storage directory is different from that of the root filesystem, kubelet will not realize this.
> Depending on how the node is setup, kubelet's garbage collection behavior will change.

**Comment by fgrzadkowski** [comment]
This is already fixed for image `v1.2.0-alpha7` and obviously will be working in `v1.2.0`.

**Comment by fgrzadkowski** [comment]
Oops. Wrong issue. Sorry.

**Comment by vpal** [comment]
Can someone please briefly explain what consequences this error has?
Is there any workaround to prevent this from happening?

**Comment by luxas** [comment]
I think this issue is fixed when using shared mounts; it only occurs once (which probably is a race condition), but succeeds after that (it syncs periodically)

What do @kubernetes/sig-node think? Can we close it?

**Comment by vishh** [comment]
upstream does not test containerized kubelet mode AFAIK. So closing it SGTM!

**Comment by cheld** [comment]
Verified that garbage collection works with shared mount volumes
