### ISSUE TITLE
Stop old pods after new pods are successful deployed while do rolling update

### ISSUE THREAD

**Issue by wb14123** [kubernetes/kubernetes#14400]
I'm using rolling update a resource controller with kubernetes. But I find it stops old pods after new pods are scheduled, instead the new pods are successful deployed.

For example, the new pod uses a new image, which need time to pull from registry. But the old pods are stopped before the new image is pulled, though new pods are scheduled.

I'd like to know is this a bug or by design?

**Comment by bgrant0607** [comment]
On 1.0.x, you can specify --update-period to set a time to wait between updates.
http://kubernetes.io/v1.0/docs/user-guide/kubectl/kubectl_rolling-update.html

On 1.1-alpha, rolling update monitors pod readiness, and an additional waiting period.

**Comment by bgrant0607** [comment]
Dupe of #11484
