### ISSUE TITLE
docker-multinode does not work on Ubuntu 15.04

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#14429]
The problem is that docker is managed by systemd and so the configuration files which are written in master.sh and worker.sh are ignored.

I have a change locally that fixes this, but need to polish it.

@resouer @dalanlan @brendandburns

**Comment by dims** [comment]
@fgrzadkowski Should we mark this as closed?

**Comment by roberthbailey** [comment]
Docker multi-node has been removed. Marking as obsolete.
