### ISSUE TITLE
Some service e2e tests are timing out.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#14424]
I marked this test as *skip*, to unbreak the build.

cc @quinton-hoole @thockin @wojtek-t

**Comment by gmarek** [comment]
Actually after removing this test it turned out that other ones also time out. Because the timeout is 20 minutes it causes entire suite to fail. From the recent run:
`should correctly serve identically named services in different namespaces on different external IP addresses`
`should be able to create a functioning external load balancer`
`should be able to create a functioning external load balancer with user-provided load balancer ip`

They all should be moved to skipped until fixed. cc @quinton-hoole @thockin @fgrzadkowski

**Comment by gmarek** [comment]
Jenkins is green again, but those tests need to get back to the GCE suite ASAP.

cc @davidopp

**Comment by gmarek** [comment]
I moved this test to flaky suite, to make GCE test actually run, but we're not 'green' yet. Some needs to investigate this. @thockin @smarterclayton @quinton-hoole

**Comment by smarterclayton** [comment]
Has anyone ever dug into the time it takes these containers to become ready?  I assumed a large part of it was delay due to other tests running at the same time (the containers themselves should start and report ready quickly).  It might be a good idea to set up a watch in one of these tests and report timings for various changes in status of the container (including the time the Kubelet reports) as a parallel worker.

**Comment by gmarek** [comment]
cc @brendandburns

**Comment by quinton-hoole** [comment]
@gmarek, @smarterclayton I can take a look into this today.

**Comment by quinton-hoole** [comment]
@thockin Labelled team/cluster, as this issue applies to testing services, which fall under that team.  Removing label team/test-infra, as per recently agreed labelling regime.

**Comment by thockin** [comment]
I can try to look today, though I am still on-call for jury duty

**Comment by quinton-hoole** [comment]
OK @thockin, assigned to you.  Feel free to assign back to me if you hear the call of duty ;-)

**Comment by thockin** [comment]
I am actually looking at this, cleaning up the whole test as I re-learn it.

**Comment by thockin** [comment]
#14957
