### ISSUE TITLE
"Oom" should be "OOM" or "oom"

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#14434]
We have a number of symbols that use the "Oom" denotation and others that use "OOM".   This is an acronym, not a word, and as per Go style rules should be consistent-case, not first-letter-caps.

e.g.

`type OomAdjuster`, `ApplyOomScoreAdj`, `NewOomAdjuster`

**Comment by liguangbo** [comment]
I think I have time to clean this. Is there anyone has worked on this?
