### ISSUE TITLE
APIGroupVersion smashes discrete fields

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#14433]
https://github.com/kubernetes/kubernetes/pull/13945 made `APIGroupVersion.Root` (https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/apiserver.go#L81) a combined field when called from https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L988.  

This ends up making the field ambiguous, since `APIPrefixes` are allowed to contain slashes (at least my knowledge).  Even if they aren't allowed to contain slashes, it hard to make a case for combining two logically discrete fields into a single field that later requires parsing to distinguish.

We need to refactor this into discrete fields to make it easier to reason about.

Implementation problem of https://github.com/kubernetes/kubernetes/pull/12951

**Comment by bgrant0607** [comment]
cc @kubernetes/goog-csi

**Comment by lavalamp** [comment]
The master.go file has changed significantly since you filed this-- what were you referencing?

(The Root field needs documentation...)

**Comment by deads2k** [comment]
> The master.go file has changed significantly since you filed this-- what were you referencing?

This is now fixed.
