### ISSUE TITLE
Persistent Volume health checks / reconciliation with provider

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#14443]
The introduction of volume.Creater allows new volumes to be created dynamically in the storage provider.  PVs are then created that point to the volume.

Errors can occur in between creation of the resource (say an EBS volume in AWS) and the creation of the PV pointing to that resource.  This leaves the EBS volume orphaned and without a PV.

Each volume created in the infrastructure requires, at a minimum, the namespace/name of the claim for which the volume was created.  The cloud provider API should be able to query for all volumes and retrieve whatever tags are applied.  Those volumes earmarked for the cluster must be reconciled with the existing PVs in the cluster to ensure they match.

GCE PD API allows a text description on a PD.   EBS volumes can have tags applied.  Cinder likely has an equivalent.

@thockin @saad-ali @kubernetes/rh-storage

**Comment by thockin** [comment]
Do you ever plan to keep a free pool of PVs ready for use?  What happens to
those tags?

**Comment by markturansky** [comment]
A pre-provisioned pool of PVs is necessarily known by the admin.  However they script those PVs into Kube, they have to know about all of them.

When the cluster creates a volume, we need some means to let the admin know about it, hence tagging. 

If we require a PersistentVolumeSet (or something similar), we'd need to tag those volumes somehow.  There wouldn't be a PVC available at that time.   We don't have this requirement today, though.

**Comment by thockin** [comment]
I meant that you might have, by policy, no less than 3 and no more than 5
PVs always read for use.  If you have more than 5, de-provision some.  If
you drop below 3 add some.  Those are not on demand for any one claim.

**Comment by markturansky** [comment]
I understand.  That's what we wrote in https://github.com/kubernetes/kubernetes/pull/6773.   There would not be a PVC available at the time of creation, so those volumes would have to be tagged in some other way.

But, unless I'm very mistaken, we're not pursuing that approach at this time.  If we do in the future, I understand that tagging will be a requirement.

**Comment by markturansky** [comment]
The PersistentVolumeSet in #6773 as an API object would have a unique name just as the claim's namespace/name is unique.  PVS.Name would make an equally good tag as PVC.Namespace/Name.

**Comment by thockin** [comment]
We don't need to accomodate everythign now, I just want to make sure we
agree that there's mor ethan just claimed volumes being provisioned.

**Comment by markturansky** [comment]
yep, we're singing from the same hymnal.

**Comment by markturansky** [comment]
@jsafrane pointed out to me that we probably also want cluster ID as part of the tag.   There is a metadata equivalent in Cinder that he'll use for tagging volumes.

**Comment by bprashanth** [comment]
Bumping this to next-candidate since it doesn't look like we need it for 1.2.0, please reply if this is inaccurate.

**Comment by saad-ali** [comment]
@jsafrane
