### ISSUE TITLE
AWS VPC lookup should not use tag filtering

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#14466]
In the AWS cloud provider's VPC lookup - given the vpc_id is being read directly from metadata from the local instance, there's no need to additionally filter on the KubernetesCluster tag.  Not only is this superfluous, but it prevents sharing a single regional VPC with multiple per-AZ Kubernetes clusters (per best practices).

**Comment by mikedanese** [comment]
@justinsb

**Comment by chrisleck** [comment]
https://github.com/kubernetes/kubernetes/pull/14503
