### ISSUE TITLE
deployment for ubuntu fails for unknown admission plugin

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#14474]
api-server fails to start with admission control DenyEscalatingExec on ubuntu 14.04 
```
$ log for kube-apiserver
F0924 15:12:51.526539   25709 plugins.go:106] Unknown admission plugin: DenyEscalatingExec
```
Once I deprecate the plugin DenyEscalatingExec, everything works fine again.

Related to #13447
/cc @pweil- @derekwaynecarr 
/cc @resouer  @WIZARD-CXY

**Comment by dalanlan** [comment]
The main reason is that this pr is not cherry picked into a formal release. The admission control supported for 1.0.6 is 
```
--admission-control="AlwaysAdmit": Ordered list of plug-ins to do admission control of resources into cluster. Comma-delimited list of: ResourceQuota, NamespaceExists, AlwaysAdmit, ServiceAccount, NamespaceLifecycle, NamespaceAutoProvision, LimitRanger, DenyExecOnPrivileged, AlwaysDeny, SecurityContextDeny
```
Hence the change for config-default.sh would break the deployment definitely.
Other platforms may suffer as well if they use a formal release (which i assume is the most cases) other than HEAD.

**Comment by derekwaynecarr** [comment]
I am a little confused.  If you are using a specific release, shouldn't you use a config-default file from that release branch?

**Comment by dalanlan** [comment]
Not really. It starts from the HEAD instead. 
My guess is the main concern could be some important patches are not cherry picked into some formal releases, which could lead to failure and consistency.  (i could be wrong though)

**Comment by pweil-** [comment]
Sorry, I'm still a little confused as to the actual run time environment here

1. if you're running 1.0.6 then your start up scripts should not contain the DenyEscalatingExec admission plugin
1. if you're running 1.0.6 but using a startup config that references the DenyEscalatingExec plugin I would expect it to fail
1. if you're running HEAD you shouldn't have a problem using the new plugin or the old one (if you so choose). If you are having an issue with that then it is a bug.

**Comment by pweil-** [comment]
Ah, found the related PR https://github.com/kubernetes/kubernetes/pull/14478/files

@derekwaynecarr - the build.sh for Ubuntu is looking for 1.0.6.

**Comment by dalanlan** [comment]
If you take a close look at the [deployment doc of ubuntu](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md), you'll figure it out easily.
The step for deployment mainly includes following steps:
1. git clone the repo (from the HEAD)
2. download the binaries needed, which is a specific formal release
3. use the config-default.sh from the HEAD repo instead of a formal release to start a cluster

**Comment by dalanlan** [comment]
I cannot tell the original idea of this consistency for sure, yet we cannot use the config files in some specific release as it did have problems due to late cherry-pick, which i can tell for sure.

**Comment by pweil-** [comment]
> If you take a close look at the deployment doc of ubuntu, you'll figure it out easily.

After seeing your PR it's clear.  Thanks!  Looks like it would've also been an issue for Centos which is using 1.0.4 with HEAD scripts but it was not using the old plugin so it did not show up in my search when I was replacing it.

**Comment by derekwaynecarr** [comment]
Thanks for the clarification, will need to keep this in mind when updating
config scripts.  Seems like its only safe to touch the ansible or salt
based setups for now that work against HEAD instead of formal release
packages.

**Comment by bgrant0607-nocc** [comment]
Using HEAD scripts against a binary release doesn't make sense. Use scripts from a matching release tag.

cc @erictune

**Comment by dalanlan** [comment]
Assuming we use the scripts from a formal release, 
- User: "oh the v1.0.6 suffers unbound variable error again!"
- Dev: "Don't worry dear, you can manually patch #11358 to fix this."
- User: "It's not cool. When would this pr be picked into a formal release?"
- Dev: "I cannot make a guarantee. You'd better pray:-/"
- User: "What about kube-push?"
- Dev: "Forget it. You might need to wait for a whole life w/o manual patching."

Ahh I'm just kidding. Yet with the late cherry-pick existing, I can ensure that you would suffer this all the time. Or maybe you would like to maintain a patch list to tell the users how to get rid of the potential bugs. With the increasing releases published, you could have a really long one, which seems too tedious.
If you're fine with this, i don't mind.
