### ISSUE TITLE
Service catalog and service broker

### ISSUE THREAD

**Issue by samsong8610** [kubernetes/kubernetes#14475]
Today, many cloud provider provide some kind of services, such as RDS in AWS, and they also provide API to create service instances on demand. Also, these services may be more robust (high availability), have  better performance or even have special features than that deployed in some pods.
According to [this document](http://kubernetes.io/v1.0/docs/user-guide/services.html#services-without-selectors), we create a service linking to an external endpoint by ignoring the selector property and creating an endpoint manually. But, the whole process is totally MANUALLY.

The service types vary between different cloud providers, but from the view of k8s, it only need an interface to provision a service instance and get its endpoint, so it is possible to define an consistent API for all kinds of services, such as [The broker api in CloudFoundry](http://docs.cloudfoundry.org/services/api.html).

I want to know if it is possible for k8s to integrate with the cloud provider to create a service instance and configure an endpoint for the service. Are there any BP for similar features?

**Comment by bgrant0607-nocc** [comment]
Related: #13748

**Comment by bgrant0607-nocc** [comment]
No immediate plans for a generic provisioning mechanism, but we have discussed more specialized mechanisms for storage and networking.

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by bgrant0607** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
We've been putting together a proposal for an API extension for this that would take the best parts of CF service broker, add in some Kube specific things that are really powerful, and then also let arbitrary provisioning and logic still fit in.

@ncdc, can you get your current deck turned into a summary proposal (high level, not expected to be implemented in Kube in the short term, but for which we can cover the answers here)?

**Comment by ncdc** [comment]
Will do. Expect it by tomorrow at the latest.

**Comment by ncdc** [comment]
Here's the rough proposal: #17543

**Comment by bgrant0607** [comment]
Vaguely related: #14828, #6908

**Comment by bgrant0607** [comment]
cc @ggogolowicz

**Comment by bgrant0607** [comment]
There is a new SIG discussing this. 

https://github.com/kubernetes/community/blob/master/sig-service-catalog/README.md
