### ISSUE TITLE
Reduce boilerplate by trying to inline ObjectType/TypeMeta/JSONBase as a pointer

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#1450]
... so that we don't have to add IsAnAPIObject

Suggested by Tim - don't have time to try it right now.

**Comment by bgrant0607** [comment]
@smarterclayton @thockin @lavalamp Do we still think this is worth doing?

**Comment by thockin** [comment]
I still find the number of steps to add a new object to be silly, and
IsAnAPIObject is part of that

**Comment by smarterclayton** [comment]
The arguments against I can think of are things like making it hard to accidentally copy that data and better memory collocation of the objects.  I also think pointers cause marginally more annoyance to end users (because of defaulting).  I think normalizing our ObjectMeta access is more important though in the short run, and the decision on how to do that should drive this. I'd like to simplify meta.Interface to be something that is available on all "objects" in a way that you know it's an "object" or a "simple object" clearly.

**Comment by thockin** [comment]
Simply deleting almost all of the definitions of IsAnAPIObject() and adding one for TypeMeta (have to leave ContainerManifest for historical..) makes all tests pass.

Is there a reason not to do that?  Is there any type that embeds TypeMeta that is not actually an API object?

**Comment by smarterclayton** [comment]
We're talking about removing TypeMeta on internal objects.  We could replace it with a meaningless stub if we wanted.

**Comment by smarterclayton** [comment]
Ie something like "type InternalType struct {}".

**Comment by lavalamp** [comment]
I'm OK with this idea, although I think it's not good to start using pointer versions of TypeMeta.

> Ie something like "type InternalType struct {}".

Yeah, something like that.

**Comment by smarterclayton** [comment]
This is done.
