### ISSUE TITLE
AWS plugin should not modify existing, non-Kubernetes created security groups on instances.

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#14504]
When a new ELB is created, the code in aws.go attempts to modify an existing security group on the target instance(s) to include ingress traffic from the ELB's security group, without understanding the purpose of the security group it picks (which just appears to be the first one the API returns).

Instead, we should consider simply creating a new, Kubernetes-owned security group for that service/ELB and add that to the instance.

**Comment by bgrant0607-nocc** [comment]
cc @justinsb

**Comment by justinsb** [comment]
This seems accurate.  Normally there is only a single security group (when created by kube-up), so the decision is indeed arbitrary currently.

I think we should probably do what we do generally - tag the security group with our cluster id, and consider that security group to be "k8s managed".

@chrisleck I take it you aren't using kube-up and/or are adding additional security groups?  Can you describe your use-case?  Would matching the security-group by tag work for you?

**Comment by chrisleck** [comment]
Correct - I'm using a series of CloudFormation configs to bring up my infrastructure, including Kubernetes master & nodes.  Kube-up doesn't work for me, as it doesn't:
* follow AWS security best practices for public/private subnetting
* setup a robust multi-AZ ETCD cluster for storing flanneld routes
* allow me to use my own CA for cert generation

Using a Kubernetes-prefixed series of tags across resources would work for my use case.  I imagine Kubernetes will need more than one tag in the future; it may be worth picking out a namespace sooner rather than later.

**Comment by naphthalene** [comment]
Is there any progress on this issue?
