### ISSUE TITLE
TestControllerSyncJob is flaky

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#14500]
https://app.shippable.com/builds/5603ab81110cc60b00ab0dcb

```
controller_test.go:240: failed pod: unexpected number of creates.  Expected 1, saw 2
```

**Comment by bgrant0607** [comment]
cc @erictune @mikedanese

**Comment by mikedanese** [comment]
cc @soltysh

**Comment by brendandburns** [comment]
I have a fix in flight...  PR shortly.

**Comment by brendandburns** [comment]
Ok, consensus is that my fix isn't correct, I'm assigning back to @soltysh but I'll keep looking.  If I can find something else, I will re-acquire the lock on this issue.

**Comment by bgrant0607** [comment]
Are we fixing this for 1.1? How frequently does it fail?

**Comment by soltysh** [comment]
I wasn't able to repro this recently. I'll try to have another look over the weekend.

**Comment by davidopp** [comment]
@soltysh any update on this?

**Comment by soltysh** [comment]
The only thing that bangs in my head is #15838 to at least nail down the issue. It's similar to what @brendandburns proposed, but on the test setup side, rather.

**Comment by erictune** [comment]
I reviewed the controller code, but I haven't seen a way yet that it would be creating too many pods.

Since this tests are based on the Replication Controller tests, and since the RC tests are not flaky, then the problem must be in either the small amount of code that is different between the RC manager and the job manager, or else it must have to do with the fact that the pods terminate for a job, but not for an RC.

**Comment by erictune** [comment]
I'm working on the e2e flakes, #15389.  It may be related to this unittest flake.

**Comment by davidopp** [comment]
@erictune Could you update this by the end of the day, just so we can get a sense of the status?

**Comment by erictune** [comment]
No progress yet.  Have been working on different P0 (#15389)

**Comment by erictune** [comment]
Started looking at this.  Fails about 1 in 100 runs for me.

**Comment by erictune** [comment]
Looks like sometimes `manager.updateHandler` is not called, and then the test case fails, in a way specific to the test case.

**Comment by erictune** [comment]
will be fixed by #16234

**Comment by davidopp** [comment]
Nice debugging! Thanks!

**Comment by davidopp** [comment]
I guess we need a cherrypick for #16234 and then we can close this issue?

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
Oops, comemnted in wrong issue. :)
