### ISSUE TITLE
RFC: Inert deployments

### ISSUE THREAD

**Issue by ironcladlou** [kubernetes/kubernetes#14516]
The deployment design (#1743) implicitly supports a deployment triggering use case known as "config change triggering" in OpenShift: when a new deployment state is observed, the cluster works to realize the new state as soon as possible. There is one functional gap in this design: users sometimes need to temporarily disable a deployment. This could be accomplished by allowing deployments to be "inert". Some uses for inert deployments:

* Provides a way for the deployment to exist in the system awaiting external human processes/validations
* Provides a safe way to prepare a deployment resource without iterative changes being rolled out
* A safety switch to prevent a deployment which you don't want to happen

Technically these use cases are satisfied by simply deleting the deployment resource and recreating it when ready, but that places a burden on the user to preserve the old state until it's ready to be recreated.

**Comment by ironcladlou** [comment]
cc @smarterclayton @nikhiljindal @ghodss @bgrant0607

**Comment by smarterclayton** [comment]
If a deployment is inert, it would be desirable to do exactly one rev of the controller loop for that deployment - i.e. "PUT /deployments/foo/instantiate".   That covers the use case of "I don't want automatic deployments, I want them automatic when I trigger"

**Comment by pmorie** [comment]
It's not obvious to me what this has to do specifically with config change triggering.

**Comment by ironcladlou** [comment]
>It's not obvious to me what this has to do specifically with config change triggering. 

Inert deployments combined with the inherent design of the deployment controller seem to provide config change trigger functionality without needing to introduce the concept of a "config change trigger" as defined in OpenShift.

**Comment by kargakis** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/7242

**Comment by kargakis** [comment]
A couple of questions:
* Is this work for a separate controller or do we think the main one is enough? If the former, then it's as simple as a condition in the spec (and a 2nd controller:) ). If the latter and we do a reconcilation per "PUT /deployments/foo/instantiate", how should the controller recognize that the deployment it is processing is actually inert and that it shouldn't try to reconcile it again without re-triggering? I am envisioning still a condition - a bool pointer (any proposed names? - nil would mean always reconcile, true: ignore, false: reconcile once). The controller would have to invalidate (set to true) non-nil conditions in the end of the reconcilation process. I think I prefer the latter.
* Where should we have "PUT /deployments/foo/instantiate" under? `kubectl rollout`?

**Comment by kargakis** [comment]
Should "PUT /deployments/foo/instantiate" work only on inert or in every deployment? I would guess the latter.

**Comment by smarterclayton** [comment]
I believe every is correct - It would simply be a no-op if the deployment
was not inert (or if the deployment already fired)

On Fri, Dec 18, 2015 at 11:42 AM, Michail Kargakis <notifications@github.com

**Comment by pmorie** [comment]
@ironcladlou 

>  It's not obvious to me what this has to do specifically with config change triggering.

Now it's obvious.  lol.
