### ISSUE TITLE
Too many daemons created by DaemonSet

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#14528]
I created a DaemonSet a few days ago on my 4 node cluster.  I noticed today that I have 6596 Pending pods, and 4 running pods.

This is not expected.

The running pods are on nodes that have existed for 3 or 4 days.

The pending pods all have unset nodeName.  I would not have expected the DaemonSet controller to ever create a pod with this value unset.  I assume they are pending due to port conflicts with the existing pods, as they use a hostPort.

**Comment by erictune** [comment]
Looking at the creation timestamps of the pods, creation of the pending pods is bursty.
It made 196, about 30 minutes passed, it made 147 of them, then an hour, then another 163 of them.
There will be gaps of several hours with no problem.

**Comment by erictune** [comment]
@AnanyaKumar @mikedanese

**Comment by erictune** [comment]
Also wondering why node controller didn't recognize these pods and clean them up.

**Comment by mikedanese** [comment]
Can you paste a daemonset config yaml?

**Comment by erictune** [comment]
Possible problem in the code, file pkg/controller/daemon/controller.go

```
nodeList, err := dsc.nodeStore.List()
        if err != nil {
                glog.Errorf("Couldn't get list of nodes when syncing daemon set %+v: %v", ds, err)
        }
        for i := range nodeList.Items {
```

note that the code uses nodeList even when there is an error.

**Comment by erictune** [comment]
My spec:
```
kind: DaemonSet
metadata:
  creationTimestamp: 2015-09-21T22:04:17Z
  generation: 1
  labels:
    name: prometheus-node-exporter
  name: prometheus-node-exporter
  namespace: default
  resourceVersion: "2220678"
  selfLink: /apis/experimental/v1/namespaces/default/daemonsets/prometheus-node-exporter
  uid: b3c40dee-60ac-11e5-b9fc-42010af00000
spec:
  selector:
    name: prometheus-node-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: prometheus-node-exporter
      name: prometheus-node-exporter
    spec:
      containers:
      - image: prom/prometheus
        imagePullPolicy: IfNotPresent
        name: c
        ports:
        - containerPort: 9090
          hostPort: 9090
          name: serverport
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
```

**Comment by mikedanese** [comment]
fixed by #14550

**Comment by sttts** [comment]
6596 pending pods??? I thought my setup was unlucky with around 50.

**Comment by bgrant0607** [comment]
Can someone please confirm whether this was fixed or not?

**Comment by mikedanese** [comment]
I confirmed that this is fixed by starting a cluster without kube-scheduler and running a daemonset and seeing that node names are written by daemonset controller and not scheduler.
