### ISSUE TITLE
Experimental: Deployments: needs Status Update

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#14521]
Update and UpdateStatus need to be separated in order to properly secure spec changes from status changes.

Related: https://github.com/kubernetes/kubernetes/issues/14344

Corresponding controller code needs to be updated to call the proper endpoint.

**Comment by derekwaynecarr** [comment]
cc @kubernetes/rh-cluster-infra @kubernetes/rh-platform-management

**Comment by bgrant0607** [comment]
cc @nikhiljindal @ironcladlou @ghodss

**Comment by bgrant0607** [comment]
That is, a status subresource

**Comment by nikhiljindal** [comment]
@bgrant0607 Do you think this required for 1.1 or not?

**Comment by bgrant0607** [comment]
No. It's required before the API graduates from experimental.

**Comment by kargakis** [comment]
@bgrant0607 this is fixed in https://github.com/kubernetes/kubernetes/pull/15809
