### ISSUE TITLE
Experimental: HorizontalPodAutoscaler: needs Status Update

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#14520]
I have been evaluating many of the experimental items in more detail to evaluate for OpenShift and came across this resource not properly separating Update from UpdateStatus which is important for a locked down environment.

https://github.com/kubernetes/kubernetes/issues/14308

The setting of status needs to be handled separately from update.

Corresponding controller code needs to be updated to call the proper endpoint.

cc @piosz @smarterclayton @ncdc

**Comment by derekwaynecarr** [comment]
I will look to submit a PR to address this before end of week.

**Comment by derekwaynecarr** [comment]
cc @kubernetes/rh-cluster-infra @kubernetes/rh-platform-management

**Comment by bgrant0607** [comment]
That is, a status subresource

**Comment by bgrant0607** [comment]
cc @jszczepkowski

**Comment by jszczepkowski** [comment]
cc @mwielgus
