### ISSUE TITLE
docker-multinode does not work on CentOS

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#14539]
- CentOS does not accept `DOCKER_OPTS` for its configuration file 
- typically CentOS does not have built-in `ifconfig` cmd
- `yum` requires `-y` or manual input "yes" to continue installation

i'll send a pr later today to fix this.

/cc @fgrzadkowski @resouer @brendandburns

**Comment by fgrzadkowski** [comment]
Assigning myself, but @dalanlan will be working on this.
