### ISSUE TITLE
Vagrant with NUM_MINIONS=2 doesn't work

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#14534]
I was trying to run kubernetes with the vagrant example and the `NUM_MINIONS=2`. I saw that there was 3 VMs created, `master`, `minion-1` and `minion-2` but not all of them are displayed with `vagrant status` nor I can access the `minion-2` with `vagrant ssh minion-2`:

```bash
$ vagrant status
Current machine states:

master                    running (virtualbox)
minion-1                  running (virtualbox)
$ ls .vagrant/machines/
master  minion-1  minion-2
$ git rev-parse HEAD
2cc9ed6b8d8f605f4139c996751e2f0024cf32c4
```

**Comment by tsl0922** [comment]
You need to run `NUM_MINIONS=2 vagrant status`, or export it before run any vagrant command.

**Comment by derekwaynecarr** [comment]
Thanks for the quick response. This is correct you must export the value in your terminal or specify on each command.  Or edit the config-default.sh file directly in your local stash.

**Comment by aanm** [comment]
@tsl0922 Thanks, I was using 2 terminals and only one of them had `NUM_MINIONS=2`.
