### ISSUE TITLE
Better memory manager at node to guarantee QoS

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#14532]
Forked from https://github.com/kubernetes/kubernetes/issues/14452...

We introduced QoS concept and API to Kubernetes 1.1 release, but lack of the support on node side to ensure QoS. Filed this umbrella issue for memory management for current known issues:
1. At node level, the only improvement was introduced is OOM score based on the resource class. This means we fully rely on Kernel sys OOM to react. This is dangerous, which could put the node to totally unstable mode. Based on my experience dealing with internal system, when sys OOM is triggered, before kernel kills some processes, process kswapd might use 100% CPU on a node to reclaim some pages, which could include disk io too, thus. All user processes are significantly slow down. **You can overcommit on request or limit, but Kernel sys OOM should be prevented**
2. This also means we should introduce a userspace memory manager to detect system overcommit on memory at run time. When memory pressure on the node is pretty high, and kubelet should proactively kill some lower priority containers / pods. We don't have this for today. 
3. Docker doesn't do process tracking at all except root pid. This means if sys OOM kills a non-root process in a container, container itself would be still running. 
4. Without userspace OOM handling support, even kernel kills container's root process, Kubelet might restart one to maintain sys OOM situation. 
5. Today all containers are at root level, instead of using cgroup_parent based on QoS. This means, the root cgroup is easily get oom-ed, instead, only some subcgroup. We plan to use cgroup_parent to improve QoS for 1.1 release, but don't have time to really get on it. 
6. Docker daemon uses tons of memory, even with 1.8.2 release. There is no good way to limit / reduce docker's resource footprint today. Currently it runs in a resource-only cgroup called /docker-daemon, and I limited it to 60% of node memory capacity. 
7. Other infrastructure daemons (kubelet, kube-proxy)' memory usage is scaled by workload. More work, more management overhead. We don't limit / budget them today. For 1.0 release, I put each one of them into a subgroup under root without limitation for monitoring / measurement only. We should have budget for them. 
8. We don't control all nodes. This means there are tons of processes / daemons running as native processes on a given node, including sshd. For measnurement / monitoring purpose, I put them in a resource-only cgroup called /system without any limit. We should have budget for them too. 
9. ...

**Comment by pmorie** [comment]
@kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
@dchen1107 

Is 3 specific to QoS situations, or just a general problem in Docker?  non-root processes could die outside of a OOM and result in the same situation today.

For 5, I assume we want a cgroup per memory qos only.  Do you anticipate that the Kubelet would define the groups for you (besteffort, burstable, guaranteed) as it does for the system cgroup or is it a manual task for administrator to provision?  I would be happy to jump in and help on this area in near term.

**Comment by dchen1107** [comment]
cc/ @timstclair This is the umbrella issue I mentioned to you another day for memory management.

**Comment by dchen1107** [comment]
cc/ @janetkuo @caesarxuchao
