### ISSUE TITLE
kubelet[2680]: failed to create kubelet: cAdvisor is unsupported in this build

### ISSUE THREAD

**Issue by shenshouer** [kubernetes/kubernetes#14549]
I use the latest version of the code which I just updated from master. And I build kubelet from source code for test. Can not start up kubelet service. the err:
<pre>
Sep 25 11:23:30 cc1 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Sep 25 11:23:30 cc1 systemd[1]: Stopped kubelet.service.
Sep 25 11:23:30 cc1 systemd[1]: Starting kubelet.service...
Sep 25 11:23:30 cc1 systemd[1]: Started kubelet.service.
Sep 25 11:23:30 cc1 kubelet[2680]: W0925 11:23:30.631752    2680 server.go:549] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
Sep 25 11:23:30 cc1 kubelet[2680]: W0925 11:23:30.632298    2680 server.go:511] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
Sep 25 11:23:30 cc1 kubelet[2680]: I0925 11:23:30.632616    2680 plugins.go:71] No cloud provider specified.
Sep 25 11:23:30 cc1 kubelet[2680]: W0925 11:23:30.632916    2680 server.go:454] setting OOM scores is unsupported in this build
Sep 25 11:23:30 cc1 kubelet[2680]: I0925 11:23:30.633624    2680 server.go:761] Adding manifest file: /etc/kubernetes/manifests
Sep 25 11:23:30 cc1 kubelet[2680]: I0925 11:23:30.634124    2680 server.go:771] Watching apiserver
Sep 25 11:23:30 cc1 kubelet[2680]: failed to create kubelet: cAdvisor is unsupported in this build
Sep 25 11:23:30 cc1 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Sep 25 11:23:30 cc1 systemd[1]: kubelet.service: Unit entered failed state.
Sep 25 11:23:30 cc1 systemd[1]: kubelet.service: Failed with result 'exit-code'.
</pre>

the way I build as follow:
<pre>
$: cd ~/workspaces/go/src/k8s.io/kubernetes/cmd/kubelet
$: CGO_ENABLED=0 GOOS=linux go build -ldflags "-s" -a -installsuffix cgo
</pre>

Is there some wrong with the build way I did ?

**Comment by vishh** [comment]
cadvisor only works on linux as of now and in-order to build it, CGO needs
to be enabled.

**Comment by dhawal55** [comment]
Vish, I tried enabling CGO but getting compilation error:
KUBE_BUILD_PLATFORMS=linux/amd64 CGO_ENABLED=1 make WHAT=cmd/kubelet

hack/build-go.sh cmd/kubelet
+++ [1026 15:57:04] Building go targets for linux/amd64:
    cmd/kubelet
# runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
!!! Error in /Users/xacj/go/src/github.com/kubernetes/kubernetes/hack/lib/golang.sh:350
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${goldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
Call stack:
  1: /Users/xacj/go/src/github.com/kubernetes/kubernetes/hack/lib/golang.sh:350 kube::golang::build_binaries_for_platform(...)
  2: /Users/xacj/go/src/github.com/kubernetes/kubernetes/hack/lib/golang.sh:527 kube::golang::build_binaries(...)
  3: hack/build-go.sh:26 main(...)
Exiting with status 1
make: *** [all] Error 1
