### ISSUE TITLE
We need some kind of global "constants" file

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#14541]
Example: It's useful to have a single place where we define what it means for a Pod to be in a terminated state (and conversely a non-terminated state). Once we have controllers responsible for GCing their Pods, this is something we want all controllers to have the same definition of, and if for some reason we change/add/delete Phases, we want to only have to change the definition in one place.

There surely will be other use cases, if there aren't already.

This would not be part of the API or user-visible, it's just for convenience of writing things like controllers (and maybe schedulers) and the like.

**Comment by davidopp** [comment]
@mikedanese @bgrant0607

**Comment by bgrant0607** [comment]
We can't ever add Phases. We should eliminate Phase and use a condition. #7856

**Comment by davidopp** [comment]
Regardless, all controllers need a common definition of when a Pod is "terminated" so they know when to do GC. I'm sure there will be other examples.

**Comment by davidopp** [comment]
Another example of where this would be useful: #17865 defines the same constant three times. I don't think there's any clean way to do it fewer. That's just silly.

**Comment by HaiyangDING** [comment]
+1 to this.

**Comment by smarterclayton** [comment]
Generally constants can go in the internal types package, esp for annotations and other primary names.  Helper methods go in helpers.go in the same package.

**Comment by davidopp** [comment]
@smarterclayton OK so you're saying we can create a file pkg/types/constants.go and put constants there (and make it part of package types)?

**Comment by smarterclayton** [comment]
Well, all of our constants today are in pkg/api/types.go, so adding more
constants there specifically used from the API doesn't seem wrong.
Constants are versioned but we manage them during conversion into internal.

Which is another thing that moving to using versioned objects internally
will make more complex.

On Nov 29, 2015, at 3:15 AM, David Oppenheimer <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> OK so you're saying we
can create a file pkg/types/constants.go and put constants there (and make
it part of package types)?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14541#issuecomment-160391000>
.

**Comment by davidopp** [comment]
That seems the right place for constants that are part of the API, but I think there are definitely constants that are not part of the API.

For example, we've said that the Reason and Message fields in Events are not part of the API. But it can be very useful to define these as a constant so we can use the same values in tests that check those fields.

**Comment by smarterclayton** [comment]
Hm... I'd still put them in api, and put a doc on them that says "these
events may be replaced by other events".  Seems very rules-lawyerish to say
they're not in the API - they're really just not guaranteed to be preserved
across API versions, but still in the API.

On Sun, Nov 29, 2015 at 4:09 PM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
But surely there are some constants that we don't want to make part of the API?

Our tests are spread across various packages (integration, factory, e2e, maybe others) in addition to the one where the code and its unit test are implemented. I can't imagine it's the case that every variable we would want to share between an implementation and its tests should be considered part of the API.

**Comment by smarterclayton** [comment]
Absolutely - however, both annotations and event names are things returned
by API that have semantics that approach API (are in the gray area between
formal API and massive duplication.  I think my concern with putting them
anywhere else is that they are already seen by users as a quasi API, so
we're already going to have to couch the language we use to describe them
regardless.  The natural place for users to look for at least some of them
is in the API doc - one spot for public facing things has a slight
advantage over two.

**Comment by lavalamp** [comment]
I believe we have other annotation key names in types.go. If not, I'm not opposed to beginning to do so.

In fact, I think it'd be a very good idea to do so. I can imagine auto-changing an annotation key across versions in conversion functions.

**Comment by smarterclayton** [comment]
We even had examples of that in v1beta3.  Openshift does it in a few places

On Dec 3, 2015, at 5:42 PM, Daniel Smith <notifications@github.com> wrote:

I believe we have other annotation key names in types.go. If not, I'm not
opposed to beginning to do so.

In fact, I think it'd be a very good idea to do so. I can imagine
auto-changing an annotation key across versions in conversion functions.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14541#issuecomment-161812123>
.

**Comment by davidopp** [comment]
Another example: for node drain, it's useful to divide pods into categories like "replicated" and "unreplicated" (or "protected from accidental drain" and "unprotected from accidental drain"). For example "kubectl drain" has a `--force` flag that means "drain the node even if it is running unreplicated pods" (without the flag, it will refuse to drain a node with unreplicated pods). We have so many kinds of pods now (ReplicationController, ReplicaSet, Job, DaemonSet, mirror, ...) that it's good to have a single place to describe their categories (e.g. which pod types are considered "replicated" vs. "unreplicated"), and we want a single place where we can add new pod types as they are created.

This is orthogonal to disruption SLOs.

**Comment by mml** [comment]
+1 to davidopp's last comment.  I think chunking this up into areas would make great starter projects.  Do we have a starter project hotlist?

**Comment by smarterclayton** [comment]
David tackled some of this recently.  We are keeping constants local to the components that use them in general.
