### ISSUE TITLE
API call latency regression

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#14552]
Looking at the scalability tests running on Jenkins we can observer a huge regression in the latency metrics (this happened over a week ago).
In particular (metrics from Density test):

run 2441:

    Sep 16 10:50:28.615: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.691713s}
    Sep 16 10:50:28.615: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.604232s}
    Sep 16 10:50:28.615: INFO: Top latency metric: {Verb:DELETE Resource:pods Quantile:0.99 Latency:149.14ms}
    Sep 16 10:50:28.615: INFO: Top latency metric: {Verb:LIST Resource:endpoints Quantile:0.99 Latency:133.645ms}
    Sep 16 10:50:28.615: INFO: Top latency metric: {Verb:PUT Resource:nodes Quantile:0.99 Latency:119.654ms}

run 2442:

    Sep 16 13:03:38.470: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.343039s}
    Sep 16 13:03:38.471: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.343039s}
    Sep 16 13:03:38.471: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:169.136ms}
    Sep 16 13:03:38.471: INFO: Top latency metric: {Verb:DELETE Resource:pods Quantile:0.99 Latency:163.265ms}
    Sep 16 13:03:38.471: INFO: Top latency metric: {Verb:LIST Resource:nodes Quantile:0.99 Latency:131.781ms}

run 2443:

    Sep 16 13:46:28.158: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.3039s}
    Sep 16 13:46:28.158: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.216827s}
    Sep 16 13:46:28.158: INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:672.557ms}
    Sep 16 13:46:28.158: INFO: Top latency metric: {Verb:LIST Resource:services Quantile:0.99 Latency:574.865ms}
    Sep 16 13:46:28.158: INFO: Top latency metric: {Verb:PUT Resource:nodes Quantile:0.99 Latency:532.134ms}

run 2444:

    Sep 16 16:32:15.498: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:2.354339s}
    Sep 16 16:32:15.498: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.158089s}
    Sep 16 16:32:15.498: INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:802.564ms}
    Sep 16 16:32:15.498: INFO: Top latency metric: {Verb:PUT Resource:nodes Quantile:0.99 Latency:774.876ms}
    Sep 16 16:32:15.498: INFO: Top latency metric: {Verb:LIST Resource:endpoints Quantile:0.99 Latency:652.077ms}

What I am looking at is latencies of calls that are NOT listing pods. There was a huge regreession from  <200ms to >500ms

However, it seems that there were no significant merges around that time that could break.

I looked few runs before and few runs after and the trend is very clear.

cc @davidopp @brendandburns @gmarek @fgrzadkowski @lavalamp 
@kubernetes/goog-csi @kubernetes/goog-testing @kubernetes/sig-scalability

**Comment by wojtek-t** [comment]
hmm - on the other hand, the last scalability runs seem to be ok (only the first green one was bad

run 2527:

    04:12:33 Sep 24 04:12:33.050: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.38289s}
    04:12:33 Sep 24 04:12:33.050: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.317718s}
    04:12:33 Sep 24 04:12:33.050: INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:804.229ms}
    04:12:33 Sep 24 04:12:33.050: INFO: Top latency metric: {Verb:LIST Resource:nodes Quantile:0.99 Latency:755.411ms}
    04:12:33 Sep 24 04:12:33.050: INFO: Top latency metric: {Verb:LIST Resource:endpoints Quantile:0.99 Latency:620.734ms}

run 2528:

    05:20:49 Sep 24 05:20:49.853: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.683224s}
    05:20:49 Sep 24 05:20:49.853: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.587855s}
    05:20:49 Sep 24 05:20:49.853: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:620.229ms}
    05:20:49 Sep 24 05:20:49.853: INFO: Top latency metric: {Verb:DELETE Resource:pods Quantile:0.99 Latency:212.385ms}
    05:20:49 Sep 24 05:20:49.853: INFO: Top latency metric: {Verb:PUT Resource:endpoints Quantile:0.99 Latency:137.204ms}


 And there were NO changes touching any related code in the meantime...

**Comment by wojtek-t** [comment]
... and again 2 significantly worse runs now:

run 2535:

    01:48:36 Sep 25 01:48:36.933: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:2.296337s}
    01:48:36 Sep 25 01:48:36.933: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.931939s}
    01:48:36 Sep 25 01:48:36.933: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:672.805ms}
    01:48:36 Sep 25 01:48:36.933: INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:648.451ms}
    01:48:36 Sep 25 01:48:36.933: INFO: Top latency metric: {Verb:LIST Resource:endpoints Quantile:0.99 Latency:460.826ms}

run 2536:

    04:27:04 Sep 25 04:27:04.921: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.180412s}
    04:27:04 Sep 25 04:27:04.921: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.178395s}
    04:27:04 Sep 25 04:27:04.921: INFO: Top latency metric: {Verb:POST Resource:pods Quantile:0.99 Latency:870.845ms}
    04:27:04 Sep 25 04:27:04.921: INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:807.746ms}
    04:27:04 Sep 25 04:27:04.921: INFO: Top latency metric: {Verb:LIST Resource:services Quantile:0.99 Latency:600.304ms}

**Comment by timothysc** [comment]
@wojtek-t we discussed failing the tests on the histogram data but we felt it would it could be too flakey.  

Perhaps we can use alerts instead.

**Comment by wojtek-t** [comment]
@timothysc I though that it doesn't even have to be histogram - we can e.g. just have two limits: one for listing pods (which is way longer than any other operation) and one for other operations.

But anyway - I would just like to understand what is happening here...

**Comment by lavalamp** [comment]
We figured this out, right? @wojtek-t can you update/link/close this?

**Comment by gmarek** [comment]
I'm not sure we figured it out - from time to time we're still seeing slow API calls. It got much better recently though.

**Comment by wojtek-t** [comment]
@lavalamp - no we didn't figure it out. In fact it doesn't seem like a real regression, because it is fluctuating (i.e. we still have "good runs" and "bad runs").
I'm fine with decresing priority, but I would like to leave it open until I have at least some idea what is causing it.

**Comment by lavalamp** [comment]
OK, sounds good. It can't be P0 because it was open a week with no assignee
and no update. :)

**Comment by wojtek-t** [comment]
@lavalamp - sure (thanks for assigning it to me)
I already spend few hours trying to understand it, but to be honest completely no findings yet...

**Comment by wojtek-t** [comment]
To be honest I don't think it's Kubernetes related - this might be GCE-related.
We may try to run those test in a different (less occupied) zone to see if the results are better....

**Comment by davidopp** [comment]
Any update on this? It's marked 1.1 but not P0, which is a bit of a limbo state...

**Comment by wojtek-t** [comment]
@davidopp - I did some debugging around it and still have no clue what is happening.
I'm moving it to 1.2

**Comment by wojtek-t** [comment]
We still observe some runs with much higher latency metrics from time time (e.g. once per 20 runs) and those are pretty random.

I started thinking if this might be related to the "garbage collection" in Go (we are still using go 1.4, where GC is implemented in the "stop-the-world" style).

That's why I would like to have these 2 PRs merged:
https://github.com/kubernetes/kubernetes/pull/13838
https://github.com/kubernetes/kubernetes/pull/14873

to verify this hypothesis.

**Comment by lavalamp** [comment]
It's been two months-- maybe time to make a new issue if we see it again.
