### ISSUE TITLE
Remove experimentalMode from namespace_controller

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#14562]
From https://github.com/openshift/origin/issues/4799#issuecomment-143233276

>> I think the ```experimentalMode``` should be removed and the controller should discover whether the experimental groups are available. If they are, it should clean up those resources.

I agree.

cc @deads2k @kubernetes/rh-cluster-infra 
cc @kubernetes/goog-control-plane

**Comment by deads2k** [comment]
@derekwaynecarr Yes please.

**Comment by mikedanese** [comment]
@caesarxuchao any recommendation on how to do this?

**Comment by caesarxuchao** [comment]
This [line](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L277) seems wrong: 
```
experimentalMode := s.EnableHorizontalPodAutoscaler || s.EnableDeploymentController
```
It should deduce if experimental group is registered by checking if latest.Group("experimental") returns an error.

I think we should remove experimentalMode, keep s.EnableHorizontalPodAutoscaler and s.EnableDeploymentController, and checks these two flags and latest.Group("experimental") before execute the code related to these two controllers.

**Comment by caesarxuchao** [comment]
@nikhiljindal @lavalamp

**Comment by deads2k** [comment]
> It should deduce if experimental group is registered by checking if latest.Group("experimental") returns an error.

Checking if the group is registered is not the same as knowing whether the resources are being served.  It's possible to have the schemes and codecs present, but not serve the resources to be cleaned up.

**Comment by caesarxuchao** [comment]
By "being served", do you mean if there are endpoints exposed on API server? If so, the controller manager can use the API discovery mechanism introduced in #13955, i.e., it needs to check if these two controllers exist in the APIReourceList returned at /apis/experimental/version

**Comment by deads2k** [comment]
> By "being served", do you mean if there are endpoints exposed on API server? If so, the controller manager can use the API discovery mechanism introduced in #13955, i.e., it needs to check if these two controllers exist in the APIReourceList returned at /apis/experimental/version

I think that would be more appropriate.  Find the exposed, namespaced resources and delete them.  That fulfills the intent.

**Comment by lavalamp** [comment]
namespace controller runs in controller manager, not apiserver, right? (please say yes)

It should deduce whether experimental is on by querying apiserver, not by what is compiled into it.

Future: In fact it should not use the high level client at all. It should use raw RESTClients (like kubectl builder). And it should discover the entire list of namespaced resources by querying apiserver, which @caesarxuchao recently made possible.

(disclaimer: I've never looked at the component, so I don't know how much of that it does already)

**Comment by derekwaynecarr** [comment]
@lavalamp - its in controller manager.

**Comment by derekwaynecarr** [comment]
@caesarxuchao - are there client libraries for dealing with the API discovery mechanism you can direct me towards?

**Comment by lavalamp** [comment]
We are still building them :(

**Comment by derekwaynecarr** [comment]
@lavalamp - is there a PR i can track?

**Comment by lavalamp** [comment]
The issue #14321 is the closest thing I can give you at the moment.

**Comment by derekwaynecarr** [comment]
The change in https://github.com/kubernetes/kubernetes/pull/15427 will remove the experimental flag and work against the discovery API.  

As a result, I am closing this issue.

I will shift focus to https://github.com/kubernetes/kubernetes/issues/14765 to make it delete all resources based on discovery with no manual need for future developers to write code in namespace_controller to take part in deletion lifecycle.
