### ISSUE TITLE
TestProcWithExceededActionQueueDepth is flaky

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#14570]
@jdef @karlkfi @davidopp 

Can we get this fixed ASAP?

Thanks!

```
proc_test.go:288: starting test case nested at 2015-09-25 00:21:13.875176228 +0000 UTC
proc_test.go:304: delegate chain invoked for nested at 2015-09-25 00:21:13.930546473 +0000 UTC
proc_test.go:323: executing deferred action: nested at 2015-09-25 00:21:13.933936289 +0000 UTC
proc_test.go:335: runDelegationTest received executed signal at 2015-09-25 00:21:13.949041708 +0000 UTC
proc_test.go:290: runDelegationTest finished at 2015-09-25 00:21:14.035916116 +0000 UTC
proc_test.go:390: unexpected error: cannot execute action because process has terminated
```

https://app.shippable.com/builds/56048e527291610b002dea79

**Comment by jdef** [comment]
yep, thanks for reporting

**Comment by jdef** [comment]
how reproduceable is this? I have some changes that I think will resolve it but I couldn't reproduce locally even when all my cpu's were pretty tied up and using a high GOMAXPROCS.

**Comment by jdef** [comment]
flakey label process?

**Comment by brendandburns** [comment]
the labelling is due to me failing @ github's label interface.  Bulk editing labels removes them if any of the selected things have the label *sigh*

Thanks for the quick fix.
