### ISSUE TITLE
TestWatchJobs is flaky

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#14589]
```
controller_test.go:474: Expected 1 call but got 0
controller_test.go:494: Expected 0 call but got 1
```

https://app.shippable.com/builds/5605ac2df06a390d0055d8aa

@soltysh @mikedanese

**Comment by mvdan** [comment]
Ran a test executable with `-race` more than 20,000 times and no failures. Any hints as to how to get it to show up? I'm running 100 jobs at a time, so my system is stressed already.

**Comment by krousey** [comment]
I to am unable to reproduce this. I get similar errors if I reduce the timeout at the top of the file. I spent a bit looking at how to rewrite the tests without the timeout, but nothing jumped out at me.

Looking at it though, it's really just a 500ms timeout for the test to complete. I'm just going to remove them. Go has a default timeout of 10 minutes. If it's going to pass, it will pass then. If not, Go will give you a nice traceback where it deadlocked.
