### ISSUE TITLE
Failed for reason PodFitsPorts and possibly others

### ISSUE THREAD

**Issue by emaildanwilson** [kubernetes/kubernetes#14586]
Since there is a separate IP address for each pod why do we need this check? The port at the pod level should be irrelevant to scheduling and able to be run on any node with a free address. If I have a 4 node cluster and try to launch 5 pods on the same port it fails to schedule even though there are 255 ip addresses available on each node.

Am I missing something?

**Comment by feihujiang** [comment]
The Ports in PodFitsPorts function is host ports which is specifed in ContainerPort, and expose on the host.

**Comment by davidopp** [comment]
Right, what @feihujiang said.

**Comment by feihujiang** [comment]
@bgrant0607 @HaiyangDing Maybe we should rename this function to PodFitsHostPorts to avoid confusing.

**Comment by davidopp** [comment]
Yes, that's a valid point.

**Comment by davidopp** [comment]
Feel free to send a PR. :)

**Comment by emaildanwilson** [comment]
Thank you, it all makes sense now. In my mind it was working like "docker run -p $hostPort:$containerPort" which I understand now from reading the spec is not the case. Simply removing hostPort from the yaml would fix this issue for most folks.

Just so I understand, what is the use case for hostPort? Would it be like using nodePort but without a service?

**Comment by davidopp** [comment]
It's for when you need to expose your application on the node's IP rather than the pod's IP.

**Comment by HaiyangDING** [comment]
CC @HaiyangDing, I will send a PR sooner.

**Comment by liggitt** [comment]
Mentioned in the PR, but I'll mention it here as well - renaming predicates is fine, but we need to keep equivalent function registered under the old name for backwards compatibility with existing scheduler.json files. Anyone reviewing scheduler plugin changes needs to be aware of that

**Comment by HaiyangDING** [comment]
@liggitt 

Thanks for mentioning this, I will fix the backwards compatibility issue.

**Comment by knownasilya** [comment]
How do I solve this error? `Failed for reason PodFitsHostPorts and possibly others`?

**Comment by HaiyangDING** [comment]
@knownasilya 

This error means that the `hostPort` specified in the pod template is occupied on the target host. To fix, either free the port on the host or change the `hostPort` in the pod template.

**Comment by emaildanwilson** [comment]
I'm closing this since the label change of this error was completed a while ago.
Thank you!

**Comment by Winbobob** [comment]
I am not sure this is the right place to post. But when I have the error `No nodes are available that match all of the following predicates:: PodFitsHostPorts (1).` on my Minikube, I did not find many related posts. So I just write here for future reference.

> The reason on my MInikube is that I enable ingress addons by `minikube addons enable ingress`. And by default minikube will create a ConfigMap, a Ingress Controller and a default http backend service. See [here](https://github.com/kubernetes/minikube/tree/master/deploy/addons/ingress). If you want to customize Ingress Controller, you had better disable Ingress addons and create your own controller.

**Comment by emaildanwilson** [comment]
@Winbobob This means that there are no available nodes in your kubernetes cluster that have the hostPort free that is being requested. In the example you referenced I see three hostPorts being specified (80, 443 & 18080. You should check to see if something is already using those ports on your node(s).  I'd suspect it would be another pod using hostPort as well.
