### ISSUE TITLE
E2E: KubeProxy should test kube-proxy is flaky

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#14585]
One instance of failure can be found with build kubernetes-e2e-gce/8619

KubeProxy should test kube-proxy

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubeproxy.go:96
Response was:map[errors:[reading from udp connection failed. err:'read udp 104.197.20.71:32081: i/o timeout']]
Expected
    <int>: 0
to be ==
    <int>: 2

cc/ @ArtfulCoder

**Comment by brendandburns** [comment]
@dchen1107 I think this is a dupe of https://github.com/kubernetes/kubernetes/issues/14342?

**Comment by dchen1107** [comment]
Yes, it is dup. Close this one as dup of 14342. Thanks!
