### ISSUE TITLE
GET/LIST subset of object fields

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1459]
Split off of #1178 and #1200.

It would be useful to be able to specify fields to be returned by GET or LIST, such as just ObjectMetadata, DesiredState, or CurrentState.

This could make a number of operations easier and cheaper, such as LISTing pods controlled by a replication controller, as in #1325.

**Comment by bgrant0607** [comment]
For reference: https://blog.apigee.com/detail/restful_api_design_can_your_api_give_developers_just_the_information

**Comment by ghodss** [comment]
What is the rationale for using dot approach and not just the Google+ API method exactly?

**Comment by smarterclayton** [comment]
JavaScript.  Anyone who has to do field validation or jquery or jq will be able to leverage that format.  The others are somewhat ivory tower

**Comment by thockin** [comment]
Is that still true with the simplifying assumptions up-thread?  E.g. no
indexes

**Comment by smarterclayton** [comment]
Sorry, I was responding to Sam, in that the format described by Eric works for me (no indexes) because it looks like what we would use for validation (which needs indexes), which we would probably end up using a lot in JavaScript (which benefits from the dot format).

----- Original Message -----

**Comment by smarterclayton** [comment]
A version of this has been implemented in #40848 - clients can request only object metadata.  Future enhancements will allow alternate schemas to be returned.  The only consumer today is GC.  Closing.
