### ISSUE TITLE
kubectl proxy: --api-prefix flag to allow /apis/

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14598]
Now that we've moved the experimental api to /apis/experimental... it's inaccessible from `kubectl proxy` by default. We should fix that.

@erictune who stepped on this earlier

**Comment by lavalamp** [comment]
@stephenR, security questions for you: this prefix was added apparently in response to a security review quite some time ago.
* I don't understand how this adds much security. Can we just remove it?
* If not, is it acceptable to change the default from "/api/" to "/api", which would match both api locations?

Otherwise we'll have to take a comma-separated list or something...

**Comment by JanetKuo** [comment]
Ref #4279

**Comment by lavalamp** [comment]
Oh, so this is not related to the security requests! And the original use case was just to re-root the URL path so it didn't interfere with static content. Sorry, I got confused because the last time I monkeyed with that, it was in conjunction with the allow/deny list that actually was the security request.

In that case, let's see if we can change the default to "/", if that will break anything.

**Comment by stephenR** [comment]
That change got introduced as part of #8871 to protect against XSRF in kubectl proxy. But I think the more important part of that change was that it disallows POST/PUT/PATCH by default. So as long as there is no state changing action outside of /api/ that can be triggered with a GET it should be safe to remove.
