### ISSUE TITLE
Flake in pkg/controller/framework test under Go 1.5

### ISSUE THREAD

**Issue by mvdan** [kubernetes/kubernetes#14617]
Happens a few times every 100 runs.

```
--- FAIL: TestUpdate (2.00s)
        controller_test.go:328: observed transition "to" -> "from" for a-1-0
        controller_test.go:328: observed transition "to" -> "from" for b-1-1
```

```
--- FAIL: TestUpdate (2.00s)
        controller_test.go:328: observed transition "to" -> "missed the add event" for c-2-2
```

```
--- FAIL: TestUpdate (2.00s)
        controller_test.go:328: observed transition "missed the add event" -> "missed the add event" for c-1-2
```

As you can see, there seems to be some kind of race which results in unwanted transitions.

**Comment by mvdan** [comment]
Could someone with an understanding of this code/test tell me if these transitions are definitely unwanted?

**Comment by lavalamp** [comment]
I don't trust 1.5 at this point, and I'm pretty sure I did put in all the expected transitions. I'll see if I can repro in 1.4, though.

**Comment by mvdan** [comment]
@lavalamp due to the scheduler changes in 1.5, this issue might never occur in 1.4. Which doesn't mean the flake is not our fault.

**Comment by lavalamp** [comment]
I'm pretty sure it's not flaky in 1.4. I guess I'll get 1.5 and try that.

**Comment by mvdan** [comment]
FWIW, I got these via `stress -p 200 ./test -test.run '^TestUpdate$'` after building a test binary with `godep go test -short -run '^$' -o test` (note that `-race` is not necessary).

You probably want to pull #14616 though, so that the waitgroup flake disappears and this one is easier to spot.

**Comment by lavalamp** [comment]
The waitgroup flake is a legit bug, not a test flake, IMO :)

**Comment by lavalamp** [comment]
As expected, once I fixed delta_fifo.go the unexpected transitions went away.

**Comment by mvdan** [comment]
Want me to test that it's also gone on 1.5?

**Comment by lavalamp** [comment]
I am running 1.5.1, but independent confirmation would be great :)

**Comment by mvdan** [comment]
FWIW, confirmed in https://github.com/kubernetes/kubernetes/pull/14881#issuecomment-144581201.
