### ISSUE TITLE
Configure skydns to not forward "cluster.local." (configureable suffix) requests

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#14628]
Skydns should not forward requests that end in "cluster.local." and must consider itself as the ONLY source of truth.
This should be configurable via a command-line flag.

**Comment by ArtfulCoder** [comment]
#14394

**Comment by ArtfulCoder** [comment]
Skydns forwarded a cluster.local request that ultimately time out after 4 seconds.

;; QUESTION SECTION:
;kube-registry.kube-system.svc.cluster.local.808746819879.google.internal.      IN       A

Abhi: ServeDNSForward Request at: 1443366957374328618
Abhi: exchange request at:1443366957374410659
Abhi: ReadMsg err:read udp 10.240.0.1:53: i/o timeout
Abhi: exchange response in:4001276207
Abhi: exchange request at:1443366961375767744
Abhi: exchange response in:5228393
Abhi: ServeDNSForward processed in :4006733305
2015/09/27 15:16:01 Abhi: ServeDNS: Returned Response in: 4006944956
2015/09/27 15:16:01 Abhi: ServeDNS: Received Request at:1443366961385978927, req:;; opcode: QUERY, status: NOERROR, id: 53655
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

**Comment by ArtfulCoder** [comment]
150ms might be too aggressive per this article:
https://technet.microsoft.com/en-us/library/ff807396(v=ws.10).aspx

**Comment by ArtfulCoder** [comment]
#14625

**Comment by thockin** [comment]
@bketelsen @miekg - sorry for double @'ing you, this is finer grained :)

**Comment by ArtfulCoder** [comment]
@thockin 
I was over-enthusiastic in opening this issue.

skydns is doing the right thing.
The client's request already had the suffix added
kube-registry.kube-system.svc.cluster.local.808746819879.google.internal. 

As a result, it gets forwarded.

Still, the timeout happens on forwarded requests, as seen in the log.
This is the source of the problems that we have seen.

I will close this bug, but we might want to consider moving our suffixes into skydns..

**Comment by ArtfulCoder** [comment]
My log above shows the client request had the google.internal. suffix to it already..
