### ISSUE TITLE
Reduce the number of search domains for dns lookups

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#14629]
We have 3 kubernetes-specific search domains.
We should consider just having fewer

**Comment by thockin-cc** [comment]
Why?  The DNS load?  I think all three are very useful.  I could see MAYBE
dropping svc.cluster.local, but it was there for compat and dropping it
will be nigh impossible.  I don't think this is feasible.

**Comment by brendandburns** [comment]
Assigning to @thockin for triage or closing

**Comment by thockin** [comment]
Yeah, I'm closing this as infeasible.  It's part of our UX.  If we want to change this (and I don't know we do) it's a MAJOR change to come with deprecations and major releases.
