### ISSUE TITLE
HTTP 500 errors with some label selectors

### ISSUE THREAD

**Issue by bronger** [kubernetes/kubernetes#14622]
When polling a k8s master with

    https://xx.xx.xx.xx/api/v1/namespaces/default/replicationcontrollers?labelSelector=environment%3D

the response is an HTTP 500.  But even if this selector is invalid, it should return a 4xx code instead.

**Comment by bgrant0607-nocc** [comment]
Do you get 500 without the label selector?

cc @kubernetes/goog-csi

**Comment by bronger** [comment]
No, and not with a value like "environment%3Dfoobar".  But if I remove "foobar" or replace it with an url-encoded space, i.e. "environment%3D%20" or "environment%3D+" I get a 500.

I suspect that the value (after the colon) is stripped of whitespace, and if the result is the empty string, this error happens.

**Comment by brendandburns** [comment]
Bumping priority to P1 since this is definitely a bug and we should fix it.

**Comment by lavalamp** [comment]
@brendandburns you had five days, I'm kicking you off of this & giving to Chao. :)
