### ISSUE TITLE
Support reason parameter on pod delete

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1462]
Forked from #137. /cc @dchen1107 

Client-initiated terminations are triggered by DELETE via the API. As discussed in #137, I'd like clients to be able to pass in arbitrary termination reasons, to facilitate ecosystem management extensions, as well as user-provided reasons.

I suggest a URL parameter on DELETE: ?reason=MYREASON.

The apiserver would record this as the termination reason, regardless what Kubelet reported when the termination actually occurred.

Once we generate termination events, the reason should be visible there.

We plan to pass termination reasons to lifecycle hooks (#1445). This means we'll need a way to pass the reason to Kubelet. I suggest implementing a "deletion dance", which we've also talked about doing in the apiserver: rather than actually deleting objects, we should first put them into a deleting/terminated state, so that clients can observe their final state. The reason could be passed this way. 

Of course, objects eventually need to be deleted, and there's always a chance that some clients may not have observed the final state. We still need to handle that, but we should ensure it doesn't happen often. Think of this as a declarative graceful termination.

See also #1370.

**Comment by bgrant0607** [comment]
@davidopp: This was the issue I mentioned could perhaps be used to accomplish Avoid Parent, though I'd probably want a way to be able to still specify multiple different rescheduling reasons (starvation, defragmentation, etc.).

**Comment by bgrant0607** [comment]
cc @kow3ns

**Comment by davidopp** [comment]
Not sure the reason for the renewed interest in this, but we do have alpha support for PreferAvoidPods, it was implemented in #20699. I doubt anyone was has used it, though, and it's not hooked into kubectl in any way.

**Comment by smarterclayton** [comment]
Same, would like to see more of a discussion before we rush into this.  A proposal or quick sketch at minimum.

**Comment by kow3ns** [comment]
@davidopp The use case I have in mind is for signalling to a stateful application the reason it has been terminated. In particular, if the application instance is being terminated for the purposes of horizontal down scaling, and if its data is not replicated identically across each node, it needs to redistribute its data to avoid leaving the system under replicated. However, if the application instance is being terminated and expects to be promptly rescheduled, we probably just want to leave it temporarily under replicated as the expected TTR is much higher if we redistribute the data. Also, we'd like to avoid the additional network and storage costs.
@smarterclayton I think this touches enough components that a full design proposal is warranted.

**Comment by smarterclayton** [comment]
I'll say this is a very common use case - we have lots of people deploying
stateful ish apps who need *something* that helps distinguish between the
reasons for a pod shutdown.

**Comment by davidopp** [comment]
Yes I agree this is a valid use case.

**Comment by tpetracca** [comment]
Just piling on that I would make good use of having termination reason available to my preStop hook. I'm looking to be able to know whether or not my pod is being killed because the statefulset is being scaled down or not. Specifically for Cassandra I want to make sure that I properly `decommission` the node so its data gets replicated to the rest of the cluster properly if it is never coming back online.

**Comment by bgrant0607** [comment]
/remove-lifecycle rotten

The proposal is still open

**Comment by techtonik** [comment]
Why only delete? Any configuration change can benefit from commit user message.
