### ISSUE TITLE
Access to TLS secured etcd: what does the config file look like?

### ISSUE THREAD

**Issue by streamnsight** [kubernetes/kubernetes#14635]
Talking to the CoreOS people, I'm told etcd doesn't take a config file, only command line flags.

However in setting up the api-server and associated pods for Kubernetes, the only way to pass those components the certificates seems to be to pass a config file.

in the flag list for api-server, there is:
`--etcd-config="": The config file for the etcd client. Mutually exclusive with -etcd-servers.`

but I have not been able to figure out the format of this file. What is it supposed to be? YAML? String? 
What are the key/value options?

i need to pass the CA cert, client cert and key I assume. 

anyone knows what the format should be?

Thanks

**Comment by davidopp** [comment]
There's some discussion of your question in this mailing list thread
https://groups.google.com/d/topic/google-containers/bTfEcRQ3N28/discussion

If that doesn't answer your question, please re-post it on StackOverflow
http://stackoverflow.com/questions/tagged/kubernetes
or reply to that mailing list thread. We're trying not to use Github for general Q&A.

Thanks!

**Comment by streamnsight** [comment]
Thanks: I did post on SO before posting here, but didn't get very far. The google group post should help though. I will try asap. Thanks for your answer.
