### ISSUE TITLE
Headless service still uses service cluster IP address

### ISSUE THREAD

**Issue by activeshadow** [kubernetes/kubernetes#14630]
When defining a service with name `abc` who's `clusterIP` setting is set to `None` (ie. a **headless service**), I expected the environment variable `ABC_SERVICE_HOST` in a container to be set to the container pod's IP address. However, it's still being set to a service cluster IP address. When I get the service details via `kubectl get services`, the IP address listed for the headless service is the same service cluster IP address as the environment variable value in the container.

Am I doing something wrong here?

**Comment by thockin** [comment]
> When defining a service with name abc who's clusterIP setting is set to None (ie. a headless service),
> I expected the environment variable ABC_SERVICE_HOST in a container to be set to the container

Sorry, this is not how it works.  A headless Service has an arbitrary
number of backends and those backends can change over time as pods
come and go.  Environment variables are utterly unsuited for this -
they can not be changed from outside a running process.

> pod's IP address. However, it's still being set to a service cluster IP address. When I get the service
> details via kubectl get services, the IP address listed for the headless service is the same service
> cluster IP address as the environment variable value in the container.

A headless service should not get any IP.  If it got assigned an IP,
it is (by definition) not headless.  I just tried it, and I don't see
this on my cluster.  Can you show your YAML or JSON?

Tim

**Comment by activeshadow** [comment]
Thanks for the info @thockin regarding the fact that it would be impractical for a headless service to utilize environment variables - I hadn't thought about it that way. So is it safe to assume that headless services only work if the cluster is utilizing the DNS add-on?

As for my headless service still getting an IP, here's the relevant information.

**headless-redis-service.yml**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
```

**Output From `kubectl get services`**

```
NAME             LABELS    SELECTOR    IP(S)          PORT(S)
headless-redis   <none>    app=redis   10.100.27.78   6379/TCP
```

**Output From `kubectl get services headless-redis -o yaml`**

```yaml
apiVersion: v1beta3
kind: Service
metadata:
  creationTimestamp: 2015-09-28T01:12:09Z
  name: headless-redis
  namespace: default
  resourceVersion: "12597511"
  selfLink: /api/v1beta3/namespaces/default/services/headless-redis
  uid: f0db8f32-657d-11e5-82a2-42010af058cc
spec:
  portalIP: 10.100.27.78
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
status: {}
```

The Kubernetes docs [here](http://kubernetes.io/v1.0/docs/user-guide/services.html#headless-services) state that headless services can be created by specifying `None` for the cluster IP (`spec.clusterIP`). However, now that I look at the output of `kubectl get services headless-redis`, perhaps it's now `portalIP` instead of `clusterIP`?

Thanks! And sorry it took so long for me to respond...

**Comment by thockin** [comment]
Aha!  portalIP is the old (pre 1.0) name.  You are on a back-rev kubernetes
(also indicated  by api v1beta3 rather than v1).

For now, you can set portalIP instead of (or in addition to clusterIP) but
you should update to v1.0 kubernetes.

On Tue, Sep 29, 2015 at 5:16 AM, Active Shadow LLC <notifications@github.com

**Comment by activeshadow** [comment]
Well dang... I'll have to talk to our infrastructure engineer about that. I'll try the `pilotIP` setting.

Thanks Tim for pointing that out and thanks for the additional information you provided!
