### ISSUE TITLE
Does k8s delete the events at intervals? 

### ISSUE THREAD

**Issue by wangzhezhe** [kubernetes/kubernetes#14640]
Does k8s delete the events info at intervals ? could I set the parameter that how long the events info existing? Thank you!

**Comment by derekwaynecarr** [comment]
@wangzhezhe - each event record is assigned a TTL to auto-expire in etcd.  The default value is 1 hour.  You can change the value by modifying the ```event-ttl``` flag for the ```kube-apiserver``` component.
