### ISSUE TITLE
GCE PD: after RC removal, PD stays attached

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#14647]
I've got five single-pod RCs, each having their own GCE PD attached. If I delete all five pods in one go, sometimes one or more pods don't come back online. The cause is this:

```
failedMount	Unable to mount volumes for pod "consul-4-dw8bd-nxlz5_staging": Could not attach GCE PD "consul-data-staging-4". Timeout waiting for mount paths to be created.
failedSync	Error syncing pod, skipping: Could not attach GCE PD "consul-data-staging-4". Timeout waiting for mount paths to be created.
```

The only way I've been able to solve this is to manually ssh into the machine where the disk is still attached, and manually `umount` it, and the run `gcloud compute instances detach-disk`. 

Possibly related to https://github.com/kubernetes/kubernetes/pull/14526?

**Comment by JeanMertz** [comment]
Note: I can consistently reproduce this when deleting all five rcs at once, and can consistently reproduce the desired behaviour when deleting them one by one.

**Comment by fgrzadkowski** [comment]
@kubernetes/goog-cluster

**Comment by saad-ali** [comment]
Hey @JeanMertz! Thanks for the report. Sorry for the troubles.

Have you been able to repro once #14526 was merged?

**Comment by JeanMertz** [comment]
I'm going to close this issue, I haven't been in a position to re-test this, and won't be in the coming weeks. If it happens again, I'll reopen the issue.

Thank you @saad-ali.
