### ISSUE TITLE
Updating of scale sub-resource for RC not working

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#14656]
After #14156 was merged, updating of scale sub-resource for (experimental) replication controller stopped working. In affect, the whole horizontal pod autoscaler is not working now. The problem seems to be that experimental scale sub-resource is trying to update experimental replication controller (while it should update the stable one).

pkg/registry/experimental/controller/etcd/etcd.go:97 return the following error
(https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/experimental/controller/etcd/etcd.go#L97):
no kind "ReplicationController" is registered for version "experimental/v1alpha1"

This also cause failure of horizontal pod autoscaler e2e tests.

**Comment by jszczepkowski** [comment]
CC @mwielgus @derekwaynecarr

**Comment by derekwaynecarr** [comment]
Thanks for the heads-up, let me know if you need assistance.
