### ISSUE TITLE
Jenkins github integration cleanup: make description consistent and accurate

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#14659]
The Jenkins automatic PR-builder currently runs not only e2e tests, but also unit, integration and validation tests too.  The messaging in github issues needs to reflect this to avoid confusion.

In the per-build message, it's approximately correct:
"Unit, integration and GCE e2e test build/test passed for commit"
But does it perform validation ("validate-all.sh") also?

For the PR status, the following is shown though, and this is not accurate:

"Jenkins GCE e2e — 4484 tests run, 105 skipped, 0 failed."

It should say something like:

"Jenkins unit, integration, validation and e2e (parallel only) -- ...."

**Comment by ixdy** [comment]
Updating the PR status is dependent on kubernetes/contrib#123 being merged and built. Otherwise we will break the munge/merge bots.

**Comment by fejta** [comment]
https://github.com/kubernetes/kubernetes/pull/22606 seems to suggest we separate out e2e and unit/integration tests
