### ISSUE TITLE
Boilerplate verification script fails

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#14662]
In my recent PR I'm seeing the following errors from GCE e2e tests:
```
Verifying ./hack/../hack/verify-boilerplate.sh
Boilerplate header is wrong for: /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@6/_gopath/src/github.com/jstemmer/go-junit-report/go-junit-report.go
...
```

See https://github.com/kubernetes/kubernetes/pull/14653#issuecomment-143804533 for details

There are also some other strange failures for other verification scripts.

@quinton-hoole @thockin

**Comment by quinton-hoole** [comment]
cc @ixdy

**Comment by ixdy** [comment]
Yeah, I'm still tracking down all of the issues with the verification scripts. They should not be failing any builds, however.

**Comment by ixdy** [comment]
I think #14587 will fix this.

**Comment by quinton-hoole** [comment]
@ixdy note that I disabled unit, integration and verification steps in Jenkins e2e last week.  You should have the details in your email.

**Comment by ixdy** [comment]
Yeah, I saw. Slowly working through backlog. The verification checks used `|| true` though, so they never should have caused any failures. (The unit/integration tests could still fail runs through the JUnit reports.)

**Comment by ixdy** [comment]
Closing as obsolete.
