### ISSUE TITLE
RollingUpdate rollback broken for asymetric updates

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#14669]
From https://github.com/kubernetes/kubernetes/pull/11942#issuecomment-136467907
Assymetric update ex: Replace an rc A with 5 replicas with an rc B with 7 replicas (old and new RCs have different replica sizes).
RollingUpdate rollback rolls back to old RC, but scales it up to the number of replicas, the new RC had (for ex it will rollback to rc A but with 7 replicas).

We need to fix that.
With https://github.com/kubernetes/kubernetes/pull/11942, we now add an "original-replicas" annotation to oldRC, which we should use.

cc @ironcladlou @ghodss

**Comment by nikhiljindal** [comment]
@ironcladlou let me know if you dont have cycles and want me to take this up.
We will need to cherrypick the fix in 1.1

**Comment by ironcladlou** [comment]
I think I can pick this up.

**Comment by nikhiljindal** [comment]
@ironcladlou Remember to cherrypick the PR in 1.1

**Comment by ironcladlou** [comment]
@nikhiljindal 1.1 PR: https://github.com/kubernetes/kubernetes/pull/14902
