### ISSUE TITLE
Fix 1.0-1.1 GCE upgrade tests, and get them into release critical builds

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#14674]

**Comment by mikedanese** [comment]
@davidopp @quinton-hoole @brendandburns this is the issue tracking gce upgrade e2e test fix effort. I've worked through some problems today in the upgrade and I'm trying to debug this:
```
Sep 28 20:55:36.334: INFO: Running gcloud [alpha compute rolling-updates --project=mikedanese-k8s --zone=us-central1-b describe 1dba3cb6-84cc-497d-9a6a-003790406aad]
actionType: RECREATE
creationTimestamp: '2015-09-29T03:40:15.596Z'
error:
  errors:
  - code: SERVICE_UNAVAILABLE
    location: ''
id: 1dba3cb6-84cc-497d-9a6a-003790406aad
instanceGroupManager: https://www.googleapis.com/replicapool/v1beta2/projects/mikedanese-k8s/zones/us-central1-b/instanceGroupManagers/e2e-test-mikedanese-minion-group
instanceTemplate: https://www.googleapis.com/compute/v1/projects/mikedanese-k8s/global/instanceTemplates/e2e-test-mikedanese-minion-template-v1-1-0-alpha-1-1427-4645ad3cb0d5c8-dirty
kind: replicapoolupdater#rollingUpdate
oldInstanceTemplate: https://www.googleapis.com/compute/v1/projects/mikedanese-k8s/global/instanceTemplates/e2e-test-mikedanese-minion-template
policy:
  instanceStartupTimeoutSec: 300
  maxNumConcurrentInstances: 1
progress: 0
selfLink: https://www.googleapis.com/replicapoolupdater/v1beta1/projects/mikedanese-k8s/zones/us-central1-b/rollingUpdates/1dba3cb6-84cc-497d-9a6a-003790406aad
status: PAUSED
statusMessage: '0/3 instances updated; Errors: SERVICE_UNAVAILABLE'
user: mikedanese@google.com
Sep 28 20:55:37.824: INFO: Waiting for MIG rolling update: '0/3 instances updated; Errors: SERVICE_UNAVAILABLE' (15m13.398309151s elapsed)
```

**Comment by mikedanese** [comment]
It seems to be passing up through the upgrade with the PRs linked above.

**Comment by ihmccreery** [comment]
Ping @mikedanese how's this going?

**Comment by quinton-hoole** [comment]
@ihmccreery There are several PR's in flight today.  It's work in progress.

**Comment by mikedanese** [comment]
Starting to get some greens.

http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-upgrade-gce/1359/

The last patch that needs to go in is #14928 then we will likely need to tune/deflake

**Comment by ihmccreery** [comment]
Awesome.

@mikedanese Can you have a look at what I've done with the GKE upgrade suite, and consider if we can do something similar for GCE?  It's uncovering a number of issues with GKE version-skewed and 1.1 clusters, and I think we should have similar visibility into GCE.  Check out #14760.

**Comment by a-robinson** [comment]
This has been failing very consistently all weekend. Step 2 ("Skipped Cluster upgrade upgrade-cluster should maintain a functioning cluster") has been timing out a bunch, and when it manages to succeed, the deployment tests fail in step 3.

**Comment by mikedanese** [comment]
@a-robinson step 2 needs to be deflaked. I'm it's on my radar but also trying to balance deflaking of daemonset e2e. I'm tracking deployment test failure in #15038. The deployment controller in the upgrade e2e environment was not enabled when the Deployment e2e test was merged on friday.

**Comment by ihmccreery** [comment]
Ping @mikedanese:

> Can you have a look at what I've done with the GKE upgrade suite, and consider if we can do something similar for GCE? It's uncovering a number of issues with GKE version-skewed and 1.1 clusters, and I think we should have similar visibility into GCE. Check out #14760.

I'm happy to do the test-infra lifting to get it done; does that sound reasonable to you?

**Comment by mikedanese** [comment]
@ihmccreery Sorry about the lag. I'm just getting back to this now and I don't mind doing the test-infra work. I'll try to get to it tonight and also work on deflaking step 2.

Regarding GKE test suite, IIUC you are dividing master-upgrade and cluster-upgrade into different steps and running e2e between them. Is that the only thing you are recommending I set up for GCE?

**Comment by ihmccreery** [comment]
Fantastic, thanks!  Due to #14771 this isn't urgent, so definitely don't worry about it if you can't get to it soon.  I'm happy to do the lift while you're actually debugging things.

The GKE suite does a couple of things: divides up master-upgrade and cluster-upgrade, running **old** e2es between them, then also, after the full upgrade, runs both the **old** and **new** e2es between them.  We're running the old e2es because that's the best we've got as far as a conformance suite goes.  There are some expected failures, and we're figuring out how to deal with those in #15116.

**Comment by davidopp** [comment]
@mikedanese / @ihmccreery can you guys clarify what is left from this issue that is for v1.1? It seems that
http://kubekins.dls.corp.google.com/job/kubernetes-upgrade-gce/
hasn't been passing recently so I assume there is still stuff left. (In which case I will channel Brian and say, we should mark this issue P0).

**Comment by davidopp** [comment]
Oh is
https://github.com/kubernetes/kubernetes/pull/15717#issue-111668850
part of what's left here?

**Comment by ihmccreery** [comment]
@davidopp This is a work-in-progress, and #15717 and others are work toward getting results, but hasn't stabilized yet, so we haven't ported it over to GCE.

In a meeting with @brendandburns, @alex-mohr, @bgrant0607, @quinton-hoole, @roberthbailey a couple of weeks ago we prioritized upgrades on GCE as a P1, (not a hard blocker,) following closely behind upgrades on GKE, which we decided was P0.

What's left:

- [x] fix the build infrastructure on the `release-1.1` branch (@ixdy looks to have succeeded on this)
- [ ] stabilize 1.0-1.1 upgrades on GKE (#15717)
- [ ] port to GCE
- [ ] diagnose failures and address them, by fixing unexpected failures and disabling expected failures, (or something)

**Comment by ihmccreery** [comment]
I'm bumping this to P0, because it seems like we're unwilling to release 1.1 without confidence that GCE upgrades work.

**Comment by ihmccreery** [comment]
Ping @mikedanese on this.

Looks like the tests are all borked due to a `flock` problem, because they're building off of your branch.

@jlowdermilk says you need to update that branch to get the latest version which doesn't use sudo on `flock`, or, if the config for the job is already at HEAD, curl e2e.sh from there.

**Comment by mikedanese** [comment]
Broken regardless until #15960 is fixed. Clusters don't pass validation. I will fixup jenkins upgrade when #15960 is resolved

**Comment by mikedanese** [comment]
#15690 is fixed on head, reenabling jenkins. Local run of step 3:

```

Summarizing 11 Failures:

[Fail] Cluster level logging using Elasticsearch [It] should check that logs from pods on all nodes are ingested into Elasticsearch 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/es_cluster_logging.go:83

[Fail] Restart [It] should restart all nodes and ensure all nodes and pods recover 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/restart.go:83

[Fail] Pods [It] should be submitted and removed 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/pods.go:253

[Fail] ReplicationController [It] should serve a basic image on each replica with a private image 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/rc.go:127

[Fail] Kibana Logging Instances Is Alive [It] should check that the Kibana logging instance is alive 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kibana_logging.go:67

[Fail] Pod Disks [It] should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/pd.go:203

[Fail] Services [It] should check NodePort out-of-range 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/service.go:695

[Fail] Services [It] should prevent NodePort collisions 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/service.go:635

[Fail] Shell [It] should pass tests for services.sh 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/shell.go:44

[Fail] Kubectl client Guestbook application [It] should create and stop a working application 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:259

[Fail] MaxPods [BeforeEach] Validates MaxPods limit number of pods that are allowed to run. 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/max_pods.go:59

Ran 81 of 99 Specs in 5511.152 seconds
FAIL! -- 70 Passed | 11 Failed | 2 Pending | 16 Skipped --- FAIL: TestE2E (5511.15s)
```

**Comment by piosz** [comment]
According to test:
```
[Fail] ReplicationController [It] should serve a basic image on each replica with a private image 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/rc.go:127
```
this is known problem. After applying #13747 the test passed.

**Comment by gmarek** [comment]
Few updates:
- [Fail] Restart [It] should restart all nodes and ensure all nodes and pods recover happens on v1.0 cluster as well, so I doubt it's update related
- The tests we're running on Jenkins do not update cluster from 1.0 to 1.1, but from 1.0 to 1.2.alpha-something (line from Jenkins):
```
16:35:01 Oct 27 16:35:01.043: INFO: Running /jenkins-master-data/jobs/kubernetes-upgrade-gce-step1-deploy/workspace/kubernetes/hack/e2e-internal/e2e-upgrade.sh [-M v1.2.0-alpha.2.421+3f3ca480be77dd]
```
- Running v1.1 tests after upgrade locally is working (everything's green)
- Tests from v1.0 contain e.g. services.sh, which is known to be flaky

**Comment by piosz** [comment]
Regarding to:
```
[Fail] Kubectl client Guestbook application [It] should create and stop a working application 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:259
```
The test is failing because of terminationGracePeriod was introduced. One of possible solution is to wait in [cleanup](https://github.com/kubernetes/kubernetes/blob/release-1.0/test/e2e/util.go#L748) for resources to be terminated.

**Comment by gmarek** [comment]
Both Services errors are caused by the change in logging in tests. I'm writing adapters to allow both versions.

**Comment by fgrzadkowski** [comment]
Regarding to:
```
[Fail] Pods [It] should be submitted and removed 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:253
```
This test is also failing because of terminationGracePeriod. 

[Here](https://github.com/kubernetes/kubernetes/blob/release-1.0/test/e2e/pods.go#L249) we delete the pod and immediately expect it to not exist. It's not obvious how this should be done because in 1.0 it was expected that pod will immediately disappear. In 1.1 we are introducing a breaking semantic change in pod delete operations by introducing graceful termination. I think we should just let those tests fail.

**Comment by piosz** [comment]
@bgrant0607 there are two broken tests by introducing terminationGracePeriod: ```Kubectl client Guestbook application...``` and ```Pods [It] should be submitted and removed``` due to the behavior described by @fgrzadkowski. How should we fix it?

**Comment by piosz** [comment]
Regarding to:
```
[Fail] Cluster level logging using Elasticsearch [It] should check that logs from pods on all nodes are ingested into Elasticsearch 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/es_cluster_logging.go:83
```
and
```
[Fail] Kibana Logging Instances Is Alive [It] should check that the Kibana logging instance is alive 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kibana_logging.go:67
```
those tests require [LOGGING_DESTINATION](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L65) set to ```elasticsearch```.

**Comment by fgrzadkowski** [comment]
Regarding:
```
[Fail] Pod Disks [It] should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/pd.go:203
```
I think (I was not able to reproduce it locally) this is again a flakiness due to graceful termination. [Here](https://github.com/kubernetes/kubernetes/blob/release-1.0/test/e2e/pd.go#L224) in 1.0 release we are deleting pod and recreating it right after it. With graceful termination this will fail. In 1.1 we just set grace period 0 ([here](https://github.com/kubernetes/kubernetes/blob/release-1.1/test/e2e/pd.go#L226))

**Comment by bgrant0607** [comment]
These are 1.0 tests against a 1.1 master? With 1.0 or 1.1 Kubelets? And what version of kubectl?

cc @smarterclayton

**Comment by fgrzadkowski** [comment]
@bgrant0607 We run 1.0 tests against 1.1 master and 1.0 nodes/kubelets.

**Comment by fgrzadkowski** [comment]
kubectl is also in 1.0 version

**Comment by bgrant0607** [comment]
Can we patch the tests in the 1.0 branch? 

1.0 had `deletionTimestamp`. If any resource left has non-empty deletionTimestamp, that should be acceptable, also.

https://github.com/kubernetes/kubernetes/blob/release-1.0/pkg/api/v1/types.go#L142

**Comment by bgrant0607** [comment]
To make deletion and re-create work, yes, we'd need to wait for these resources to disappear.

**Comment by fgrzadkowski** [comment]
During the course of the day we had multiple updates so here is the summary:

Bugs failing due to graceful teramination:
```
[Fail] Pods [It] should be submitted and removed 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/pods.go:253

[Fail] Pod Disks [It] should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/pd.go:203

[Fail] Kubectl client Guestbook application [It] should create and stop a working application 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:259
```
Proposed fix https://github.com/kubernetes/kubernetes/pull/16430

Fails caused not enabling elasticsearch in the cluster:
```
[Fail] Cluster level logging using Elasticsearch [It] should check that logs from pods on all nodes are ingested into Elasticsearch 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/es_cluster_logging.go:83

[Fail] Kibana Logging Instances Is Alive [It] should check that the Kibana logging instance is alive 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kibana_logging.go:67
```
Fixed by setting [LOGGING_DESTINATION](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L65) set to ```elasticsearch```.

This test fails even with tests from 1.0 run against master 1.0:
```
[Fail] Restart [It] should restart all nodes and ensure all nodes and pods recover 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/restart.go:83
```

Test:
```
[Fail] ReplicationController [It] should serve a basic image on each replica with a private image 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/rc.go:127
```
Fix in https://github.com/kubernetes/kubernetes/pull/16427

Tests:
```
[Fail] Services [It] should check NodePort out-of-range 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/service.go:695

[Fail] Services [It] should prevent NodePort collisions 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/service.go:635
```
Fix in #16434

Test:
```
[Fail] MaxPods [BeforeEach] Validates MaxPods limit number of pods that are allowed to run. 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/max_pods.go:59
```
Fix in #16433


Test:
```
[Fail] Shell [It] should pass tests for services.sh 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/shell.go:44
```
We didn't have time to look into it.

**Comment by wojtek-t** [comment]
>
Test:

>
    [Fail] Shell [It] should pass tests for services.sh 
    /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/shell.go:44

>
We didn't have time to look into it.

This test was flaky, so we rewrote it in go - https://github.com/kubernetes/kubernetes/pull/11056
maybe it's the same problem why it was rewritten? Maybe we can just disable it?

**Comment by gmarek** [comment]
I'm all for disabling it and cherry-picking relevant parts of services.go. We had enough problems with this test already.

**Comment by gmarek** [comment]
There's one thing to do left (except deciding what to do with `services.sh`) - we need to fix `cluster_upgrade.go` e2e-test, so that it'll be able to upgrade to v1.1, not only to the head-ish.

**Comment by davidopp** [comment]
Thanks for all the work and the excellent summary!

**Comment by bgrant0607** [comment]
Has anyone looked at why services.sh is failing?

**Comment by davidopp** [comment]
> Has anyone looked at why services.sh is failing?

I wasn't claiming the issue is fixed, just thanking the Warsaw guys for all the work they did overnight.

@mikedanese said he would look into the remaining problems.

**Comment by piosz** [comment]
services.sh seems to be the last problem to fix (+ #16427 is in flight)

**Comment by mikedanese** [comment]
Just ran step step 3 (1.0 e2e with 1.1 master and 1.0 nodes) and got:

```
[Fail] Nodes Resize [It] should be able to delete nodes 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:458

• Failure [506.478 seconds]
Nodes
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:547
  Resize
  /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:486
    should be able to delete nodes [It]
    /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:459

    Expected error:
        <*errors.errorString | 0xc2083a0740>: {
            s: "failed to wait for pods running: [gave up waiting for pod 'my-hostname-delete-node-zaeed' to be 'running' after 5m0s]",
        }
        failed to wait for pods running: [gave up waiting for pod 'my-hostname-delete-node-zaeed' to be 'running' after 5m0s]
    not to have occurred

    /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:458

[Fail] Kibana Logging Instances Is Alive [It] should check that the Kibana logging instance is alive 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kibana_logging.go:67

[Fail] Cluster level logging using Elasticsearch [It] should check that logs from pods on all nodes are ingested into Elasticsearch 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/es_cluster_logging.go:83

[Fail] Kubectl client Guestbook application [It] should create and stop a working application 
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:259

• Failure [647.646 seconds]
Kubectl client
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:241
  Guestbook application
  /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:139
    should create and stop a working application [It]
    /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:138

    Frontend service did not start serving content in 600 seconds.
    /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:259

Ran 73 of 99 Specs in 4937.513 seconds
```

Kibana and Cluster level logging aren't running as addons after the upgrade. The other two are flakes (they've passed before). `service.sh` passed so it's also a flake. I'm going to run step 5 now and report back.

**Comment by piosz** [comment]
I created cluster with master from HEAD, nodes from release-1.0 branch and ran tests from release-1.0 against it.

Kibana and Cluster level logging are enabled by default in HEAD, release-1.1 and release-1.0 in [config-test.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L75) thought the default option in [config-default.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L65) is gcp. I guess you are using config-default.sh. Both tests works for me when I'm using config-test.sh.

Guestbook and guestbook.sh e2e are just flakes - I was able to successfully run them 3 times locally.

Nodes Resize is also flaky. It was flaky so we decided to increase timeout there #12138. I'll cherry-pick the change to 1.0.

It seems that all tests pass :)

**Comment by gmarek** [comment]
Thanks @piosz for checking it!

**Comment by davidopp** [comment]
Update from @mikedanese : He says he doesn't think there's anything remaining to fix here. He said there is still some flakiness but it is probably due to the fact that the stuff we were cherrypicking into 1.0 to fix the upgrade tests' flakiness was actually not being used in the upgrade test. He said @ihmccreery is working on that now.

**Comment by mikedanese** [comment]
The test failures on jenkins are related to not running ci/latest-1.0 so we aren't seeing all the test fixes on jenkins, but there is some independent flakiness. #16521 (just merged) should provide infrastructure to start testing with ci/latest-1.0

**Comment by ihmccreery** [comment]
I'll take this over the finish-line, fixing infra and getting it into critical builds.

**Comment by davidopp** [comment]
@mikedanese said he's comfortable with moving this out of the 1.1 milestone, so I'm going to do that now. Not closing, as it's still pretty flaky.

**Comment by davidopp** [comment]
@mikedanese said he'd take a look at what is the current state of this. He said we need to fix the regressions and then move it into critical builds and make the mergebot block on it.

**Comment by ihmccreery** [comment]
This is in my Q4 docket.  Working on stabilizing GKE, then will move onto GCE.  Unless @mikedanese has cycles to burn, I'm happy to take this on.

**Comment by ihmccreery** [comment]
I'm closing this out, as we're coming up to v1.2 and GKE upgrades are still unstable.
