### ISSUE TITLE
flaky e2e: Scheduler should continue assigning pods to nodes across restart

### ISSUE THREAD

**Issue by goltermann** [kubernetes/kubernetes#14696]
DaemonRestart Scheduler should continue assigning pods to nodes across restart (Failed 2 times in the last 30 runs. Stability: 93 %)

**Comment by brendandburns** [comment]
Assigning to @davidopp for triage.

**Comment by davidopp** [comment]
Working on repro now.

**Comment by davidopp** [comment]
I ran this test 30 times by itself and the entire DaemonRestart suite 30 times and didn't get any failures. I also don't see any recent failures of this particular test (I manually checked the last 25 runs) so I am going to close this until we see it again.

**Comment by goltermann** [comment]
Did you move it out of the flaky test suite and into the regular?
