### ISSUE TITLE
oidc.TestOIDCDiscoverySecureConnection Flaky

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#14691]
```
Regression

oidc.TestOIDCDiscoverySecureConnection (from k8s.io_kubernetes_plugin_pkg_auth_authenticator_token_oidc)

Failing for the past 1 build (Since Unstable#10408 )
Took 6 sec.
Error Message

Failed
Stacktrace

oidc_test.go:273: Cannot load cert/key pair: open /tmp/oidc-cert-1: no such file or directory
```

**Comment by brendandburns** [comment]
@liggitt for triage

**Comment by liggitt** [comment]
@mikedanese trying to recreate... was this on shippable, travis, or somewhere else?

**Comment by mikedanese** [comment]
This was on jenkins.

https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/9e4e30e8e8b571d69ba348de3a759e98906d8257/kubernetes-pull-build-test-e2e-gce/10408/build-log.txt

http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce//10408

https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/9e4e30e8e8b571d69ba348de3a759e98906d8257/kubernetes-pull-build-test-e2e-gce/10408/_artifacts/

**Comment by wojtek-t** [comment]
I didn't see this failure since quite a long time. Is it fixed? Can we close it?

**Comment by mikedanese** [comment]
This flaked again in https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26585/kubernetes-pull-test-unit-integration/29352/artifacts/

```xml
<testcase classname="oidc" name="TestOIDCAuthentication" time="2.370">
  <failure message="Failed" type="">
    oidc_test.go:168: Cannot start server: Cannot load cert/key pair: open /tmp/oidc-cert: no such file or directory
   </failure>
</testcase>
```
