### ISSUE TITLE
flaky e2e: Kubelet should not restart containers across restart

### ISSUE THREAD

**Issue by goltermann** [kubernetes/kubernetes#14694]
DaemonRestart Kubelet should not restart containers across restart (Failed 3 times in the last 30 runs. Stability: 90 %)

**Comment by brendandburns** [comment]
@dchen1107 for triage

**Comment by dchen1107** [comment]
@goltermann I couldn't reproduce the issue. I also checked Jenkin build kubernetes-e2e-gce-flaky, there are several builds (5510, 5511, 5517) which were timeout due to service tests, and this particular test didn't get chance to run; otherwise they were passed. Do you have a link of failing test?

**Comment by goltermann** [comment]
I looked again now, and it does show up as 100% reliable over the past several builds.  If things look clean, just use this bug to track moving it out of the flaky test suite and into the regular one.

**Comment by dchen1107** [comment]
Ok, I will move this out of flaky test suite. Thanks!

**Comment by dchen1107** [comment]
Test: DaemonRestart Kubelet should not restart containers across restart is moved out of flaky test suite. Close thie issue.
