### ISSUE TITLE
Race condition in `kubectl run --attach`

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#14703]
`kubectl run foo --attach` runs foo and then waits for it to be ready or terminated. If the pod is terminated, it prints the log, and if it's not terminated, it attaches the output. However, it does not handle the case that the pod terminates between returning the ready status and attaching, as can be the case in the [kubectl e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubectl.go#L193):

```console
[It] should support inline execution and attach
...
    Sep 28 13:49:15.303: Error running &{/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.180.162 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config --namespace=e2e-tests-kubectl-1bdva run run-test --image=busybox --restart=Never --attach=true echo running in container] []  <nil> Waiting for pod e2e-tests-kubectl-1bdva/run-test to be running, status is Pending, pod ready: false
    Waiting for pod e2e-tests-kubectl-1bdva/run-test to be running, status is Pending, pod ready: false
     error: error executing remote command: Error executing command in container: container not found ("run-test")
     [] <nil> 0xc20829d3a0 exit status 1 <nil> true [0xc2080528e0 0xc208052920 0xc208052968] [0xc2080528e0 0xc208052920 0xc208052968] [0xc208052918 0xc208052940] [0x6aa400 0x6aa400] 0xc208370060}:
    Command stdout:
    Waiting for pod e2e-tests-kubectl-1bdva/run-test to be running, status is Pending, pod ready: false
    Waiting for pod e2e-tests-kubectl-1bdva/run-test to be running, status is Pending, pod ready: false
    
    stderr:
    error: error executing remote command: Error executing command in container: container not found ("run-test")
```

Options to fix this:
- Fix kubectl:
  - If attach fails, fall back to printing the logs
  - If attach fails, check the status again and if it's terminated, print the logs
- Fix the flaky test:
  - Prevent the container from exiting (e.g. `sh -c 'echo running in container && sleep 30')
  - Prevent the container from entering ready state (e.g. `readinessProbe: {initialDelaySeconds: 30}`)

@brendandburns

**Comment by brendandburns** [comment]
@timstclair Thanks for debugging.

I think we should probably do both:
   * If attach fails and the container is now terminated, fall back to printing logs
   * Make the e2e more robust by not exiting for a while to ensure time to attach.

I'm happy to review PRs
