### ISSUE TITLE
Why ReplicationControllerInterface, and DaemonSetInterface have no UpdateStatus method

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#14717]
* Why NodeInterface and JobInterface have  UpdateStatus method, but ReplicationControllerInterface and DaemonSetInterface doesn't ?
* UpdateStatus method seems very useful in ReplicationControllerInterface and DaemonSetInterface.

**Comment by fgrzadkowski** [comment]
@bgrant0607 @kubernetes/goog-csi

**Comment by nikhiljindal** [comment]
I see @derekwaynecarr is fixing ReplicationControllerInterface in https://github.com/kubernetes/kubernetes/pull/14672.
He fixed DaemonSetInterface in https://github.com/kubernetes/kubernetes/pull/14535

**Comment by derekwaynecarr** [comment]
I am going to close this issue as each is already handled by separate issues and open pull requests as referenced.
