### ISSUE TITLE
kube-apiserver tls cert does not work if no client-ca-file specified

### ISSUE THREAD

**Issue by gouyang** [kubernetes/kubernetes#14723]
Only tls cert and key file specified, which means no client cert authentication here, does not work.
It should be work.
```
# kube-apiserver --service-cluster-ip-range=10.254.0.0/16  --etcd-servers=http://127.0.0.1:2379 --tls-cert-file=/etc/ssl/certs/host.crt --tls-private-key-file=/etc/ssl/certs/host.key
I0929 17:22:23.726220   15841 plugins.go:69] No cloud provider specified.
I0929 17:22:24.063938   15841 master.go:273] Node port range unspecified. Defaulting to 30000-32767.
I0929 17:22:24.065227   15841 master.go:295] Will report 172.16.2.5 as public IP address.
[restful] 2015/09/29 17:22:24 log.go:30: [restful/swagger] listing is available at https://10.73.2.5:6443/swaggerapi/
[restful] 2015/09/29 17:22:24 log.go:30: [restful/swagger] https://172.16.2.5:6443/swaggerui/ is mapped to folder /swagger-ui/
I0929 17:22:24.098802   15841 server.go:441] Serving securely on 0.0.0.0:6443
I0929 17:22:24.098820   15841 server.go:483] Serving insecurely on 127.0.0.1:8080

# curl --cacert /etc/ssl/certs/rootCA.crt https://test1.redhat.com:6443
Unauthorized
# kubectl -s https://test1.redhat.com:6443 --certificate-authority=/etc/ssl/certs/rootCA.crt api-versions 
Please enter Username:
```

specified with client-ca-file, works as expected
```
# kube-apiserver --service-cluster-ip-range=10.254.0.0/16  --etcd-servers=http://127.0.0.1:2379 client-ca-file=/etc/ssl/certs/rootCA.crt --tls-cert-file=/etc/ssl/certs/host.crt --tls-private-key-file=/etc/ssl/certs/host.key
I0929 17:33:07.420204   16349 plugins.go:69] No cloud provider specified.
I0929 17:33:07.649465   16349 master.go:273] Node port range unspecified. Defaulting to 30000-32767.
I0929 17:33:07.650717   16349 master.go:295] Will report 10.73.2.5 as public IP address.
[restful] 2015/09/29 17:33:07 log.go:30: [restful/swagger] listing is available at https://10.73.2.5:6443/swaggerapi/
[restful] 2015/09/29 17:33:07 log.go:30: [restful/swagger] https://10.73.2.5:6443/swaggerui/ is mapped to folder /swagger-ui/
I0929 17:33:07.682704   16349 server.go:441] Serving securely on 0.0.0.0:6443
I0929 17:33:07.682738   16349 server.go:483] Serving insecurely on 127.0.0.1:8080


# curl --cacert /etc/ssl/certs/rootCA.crt --cert ^C
# kubectl -s https://test1.redhat.com:6443 --certificate-authority=/etc/ssl/certs/rootCA.crt --client-certificate=/etc/ssl/certs/host.crt --client-key=/etc/ssl/certs/host.key api-versions 
Available Server Api Versions: v1
# curl --cacert /etc/ssl/certs/rootCA.crt --cert /etc/ssl/certs/host.crt --key /etc/ssl/certs/host.key https://test1.redhat.com:6443
{
  "paths": [
    "/api",
    "/api/v1",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/resetMetrics",
    "/swagger-ui/",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]
```

**Comment by fgrzadkowski** [comment]
@kubernetes/goog-csi

**Comment by roberthbailey** [comment]
@gouyang - What are you expecting to work? If you don't pass the `--client-ca-file` flag to the apiserver, then it won't accept client certificates for authentication (https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L197) so you must provide alternate client auth (bearer token or http basic auth, depending on how your apiserver is configured).

/cc @liggitt

**Comment by liggitt** [comment]
tls cert/key just enables https serving, not client cert auth

**Comment by roberthbailey** [comment]
Exactly, which is why I'm curious what @gouyang was expecting to work in his first example.

**Comment by gouyang** [comment]
@roberthbailey I think @liggitt has answered the question, without --client-ca-file flag, it enables https serving, but it seems not working as example 1 shows.

examples from etcd and flannel:
https://github.com/coreos/flannel/blob/master/Documentation/client-server.md#use-of-ssltls-to-secure-clientserver-communication

https://github.com/coreos/etcd/blob/master/Documentation/security.md#example-1-client-to-server-transport-security-with-https

**Comment by liggitt** [comment]
Authentication is always required against the secured port. In your first example, you haven't enabled the client cert auth method. Unauthenticated curl requests should not succeed against the secured port.

**Comment by gouyang** [comment]
I'm confused a bit now, how could I make it work? just like the second example does?

**Comment by liggitt** [comment]
You always need to enable some sort of authentication method for secure serving. Bearer token, client cert, etc. In your first example, you started the API server without specifying any way for someone to authenticate.

**Comment by gouyang** [comment]
Seems I understand the problem now, it looks a design from kubernetes.
Just read doc authentication.md
```
Kubernetes uses client certificates, tokens, or http basic auth to authenticate users for API calls.
```

So it's not like other programs like the etcd and the flannel examples above, it must use one authenticate method to access APIs.

**Comment by roberthbailey** [comment]
In the examples you linked to, https was enabled but there was still no client authentication required to connect. As @liggitt said above, in Kubernetes client authentication is always required on the secure port.

**Comment by gouyang** [comment]
thanks for the patient explaining, understand it now.
