### ISSUE TITLE
GCM: Enable all GCM stuff when using googleinfluxdb heapster config

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#14727]
Or at least stop kube-up when not enabled.

**Comment by piosz** [comment]
related to #13023

**Comment by vishh** [comment]
Can you elaborate on what is required? As far as GCM goes, they do not
recommend using custom metrics for storing large volumes of data.

**Comment by mwielgus** [comment]
Today @gmarek tried to enable cluster autoscaling on a new project. It turned out that you need to go to google dev console and manually enable the api, otherwise Heapster will get caught into a crashloop. Kube-up should try to verify if gcm is enabled (and maybe enable it if not).

**Comment by vishh** [comment]
Thanks for explaining! On that note, we should avoid making heapster
crashloop and instead post a user parsable error message that instructs
users to enable the API.
+! for fixing on the kube-up side as well.
