### ISSUE TITLE
Addon pods on master node are not listed in `get pods --namespace=kube-system`

### ISSUE THREAD

**Issue by paulbellamy** [kubernetes/kubernetes#14738]
Addon pods on minion nodes are listed, but ones on the master node are not. Seems like a bug.

I'm using k8s at commit: 28585bc699e7f3b6d3343aebb507d3ecef8e4e28 with the GCE provider. Happy to provide any more reproducibility info you need.

**Comment by bgrant0607** [comment]
Will be addressed by #14054
