### ISSUE TITLE
Deployment does not scale down

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#14744]
Scaling down doesn't work for Deployments in the following scenario:

1. create a simple deployment with 5 replicas
2. wait for rc/pods to be created and running
3. update deployment, change the number of replicas to 1
result: the rc is never scaled down to 1, its size is 5 all the time.

The problems seems to be in scaleUp method:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller.go#L234
This method should actually **scale down** the new rc, but it seems it doesn't due to condition in:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller.go#L254
(Please not that scaleDown method works only on old rcs, but there are no old rcs in our scenario).

**Comment by jszczepkowski** [comment]
I discovered this issue when I was manually testing horizontal pod autoscaler with deployments. (Please note that scale up works fine with autoscaling).

**Comment by jszczepkowski** [comment]
BTW: this case should be covered by a unittest for deployment controller. (You may follow example of autoscaler tests: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal_test.go)

**Comment by ironcladlou** [comment]
@nikhiljindal so, this is actually an interesting problem. During `scaleUp`, if the new/existing RC is already greater than `replicas + maxSurge`, it bails early since we're in violation of the surge specification (by exceeding it).

Should `scaleUp` actually scale down the new RC if it observes such a violation?

**Comment by nikhiljindal** [comment]
Yes. We will maybe need another function reconcileNewRC, which calls scaleUp or down or maybe just rename that function and it calls scaleRC accordingly.

I plan to work on this right after I have fixed the e2e test: https://github.com/kubernetes/kubernetes/issues/15038

By that time, I might have your unit tests as well, which will be great.

**Comment by ironcladlou** [comment]
I got started on the tests late in the day. I'm taking the approach of making test tables at the `scaleUp` and `scaleDown` function granularity since the guts of this thing are now sufficiently decomposed compared to the kubectl version. Will have something for review tomorrow.

**Comment by ironcladlou** [comment]
If you want to get a feel for what it looks like, check out this branch:

https://github.com/kubernetes/kubernetes/compare/master...ironcladlou:deployment-controller-tests?expand=1

**Comment by nikhiljindal** [comment]
Fixing this in https://github.com/kubernetes/kubernetes/pull/15257
