### ISSUE TITLE
Add new kubectl overview to navigation tree

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#14745]
After the new kubectl overview topic (#14177) is merged, it should be added to the navigation tree.

Please insert the following at line 508 of the nav_v1.0.html file (https://github.com/kubernetes/kubernetes/blob/gh-pages/_includes/nav_v1.0.html#L508):
```
<li class="navSubMenu haschild">
		<a href="{{ site.url }}/v1.0/docs/user-guide/user-guide/kubectl-overview.html" class="nav-link">Overview</a>
</li>
```

The result should look like:
![image](https://cloud.githubusercontent.com/assets/11762685/10168245/d7406b7c-6680-11e5-8453-daec5e2ead7c.png)

Related: #11814

**Comment by alfred-huangjian** [comment]
@hw-qiaolei It seems this is related to your PR.

**Comment by bgrant0607** [comment]
Done: http://kubernetes.io/v1.1/docs/user-guide/kubectl-overview.html
