### ISSUE TITLE
Export resource usage benchmarks to an easily consumable place

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#14754]
@dchen1107

**Comment by dchen1107** [comment]
@yujuhong This is the place holder you and I have been talking about for a while: publishing benchmark of kubernetes daemons' resource usage: without any user workload, with user workload (~40 pods).

**Comment by yujuhong** [comment]
Perhaps we should do something similar to http://perf-dash.k8s.io? @kubernetes/goog-node, thoughts?

**Comment by dchen1107** [comment]
http://perf-dash.k8s.io looks pretty cool except I also want to have version related information.

**Comment by yujuhong** [comment]
We have http://node-perf-dash.k8s.io now.
