### ISSUE TITLE
kubelet stats missing on Ubuntu 15.04

### ISSUE THREAD

**Issue by satheessh** [kubernetes/kubernetes#14762]
Attached the screen shot from grafana.  
we can notice that heapster memory usage is zero.

Environment:
1. Kubernetes version 1.06
2. Amazon webservice  machines. 
    c3.large for master and minions.
3. ami version.  -- ubuntu-vivid-15.04-amd64-server-20150611 (ami-f57b8f9e)
4. see below pics from cadvisor memory and cpu usage is zero

<img width="557" alt="screen shot 2015-09-29 at 12 28 54 pm" src="https://cloud.githubusercontent.com/assets/8891432/10175819/e95113e6-66a5-11e5-96d8-19888c06bb3b.png">
![file-page1](https://cloud.githubusercontent.com/assets/8891432/10180545/f4455aba-66c2-11e5-89e4-683c88930760.jpg)
![file-page2](https://cloud.githubusercontent.com/assets/8891432/10180547/f800b3f2-66c2-11e5-9ead-d3fb0edd1690.jpg)

Thanks for  Vish Kannan to debug this issue.

**Comment by satheessh** [comment]
From Vish Kannan:
It is not detecting stats for containers correctly.
I suspect this is due to the way systemd cgroups are setup

**Comment by vishh** [comment]
To provide more context: cAdvisor is not detecting stats for docker containers running on `Ubuntu 15.04`. I suspect this is a bug in cadvisor systemd integration.

**Comment by vishh** [comment]
@dchen1107: We should validate kubelet on latest Ubuntu 15.04 for v1.1.
cc @jimmidyson

**Comment by jimmidyson** [comment]
What version of cadvisor is this running?

**Comment by jimmidyson** [comment]
Tested cadvisor master outside of the kubelet & works fine.

**Comment by jimmidyson** [comment]
Ah this is on Amazon - is this the problem with Docker container dir that IIRC cadvisor already has an issue filed for?

**Comment by satheessh** [comment]
root@ip-172-20-0-9:~# /usr/local/bin/kubelet --version
Kubernetes v1.0.6

**Comment by dchen1107** [comment]
What is the flag for kubelet service, especially with --cgroup-root?

**Comment by satheessh** [comment]
/usr/local/bin/kubelet $DAEMON_ARGS --enable-debugging-handlers=false --cloud_provider=aws --config=/etc/kubernetes/manifests --allow_privileged=False --v=2 --cluster_dns=10.0.0.10 --cluster_domain=cluster.local --docker_root=/mnt/ephemeral/docker --root_dir=/mnt/ephemeral/kubernetes/kubelet --configure-cbr0=true --cgroup_root=docker --system-container=/system --pod-cidr=10.246.0.0/24

**Comment by jimmidyson** [comment]
@satheessh has let me jump on to one of the nodes & I can see that some stats are reported. e.g.

```
$ curl -s ip-172-20-0-152.ec2.internal:10255/metrics|grep 'container_cpu_system_seconds_total{id="/system.slice/docker-1492f0945c2cf4227c621ce3a5347e922deff8082f81ba4ecc0676f80ee68db5.scope",name="k8s_elasticsearch-logging.73529f68_elasticsearch-logging-v1-edgx1_kube-system_4dd94c2f-66d1-11e5-afce-0eba1e912711_4bd28c96"}'|cut -d' ' -f2
21.03
```

**Comment by jimmidyson** [comment]
Interestingly `docker stats` also reports the same zero stats:

```
$ docker stats <containerId>
CONTAINER CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
<SNIP>    0.00%               0 B/3.675 GiB       0.00%               0 B/0 B
```

Yet for others it reports correctly.

**Comment by jimmidyson** [comment]
Ah this is running docker 1.6.0. Think there have been some improvements to the docker stats stuff since then.

@satheessh Can you upgrade docker? Not sure what the minimum supported version is tbh, but 1.6.0 is pretty old now.

**Comment by jimmidyson** [comment]
In addition this is Docker running with LXC rather than libcontainer. @vishh Is LXC supported for metrics in cadvisor?

**Comment by satheessh** [comment]
I created a new cluster with Ubuntu 14.04 trustry and docker version 1.6. It works.
I will try with  ubuntu 15 vivid and latest docker version  and update here.

**Comment by vishh** [comment]
@jimmidyson: No. cAdvisor cannot associate LXC containers with docker containers as of now.

**Comment by vishh** [comment]
@satheessh: is there a reason for running docker with lxc driver?

**Comment by satheessh** [comment]
@vishh no. Look like it is the default, if  kubernete  cluster is created in amazon web services

**Comment by vishh** [comment]
AFAIK, we do not validate kubernetes with LXC. Is there a reason why you
want to use Ubuntu 15.04?

**Comment by pikeas** [comment]
@vishh Ubuntu 15.04 is the default OS for AWS `kube-up`. I expect k8s to be well tested on this platform, or to switch the default install to a different OS.

Are there any other known issues or reasons not to run k8s on 15.04?

**Comment by jimmidyson** [comment]
I'm a little surprised it's the default. Could you share output from `docker info`?

**Comment by vishh** [comment]
Can you change the execution driver in docker to be `native`?

**Comment by cmluciano** [comment]
Can we close this since 15.04 is EOL https://wiki.ubuntu.com/Releases

**Comment by justinsb** [comment]
Closing for now; if people are still hitting please reopen / comment.
