### ISSUE TITLE
Namespace deletion should not include an open-coded  list of resources

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#14765]
pkg/controller/namespace/namespace_controller.go `func deleteAllContent()` includes this:

```
    err = deleteServiceAccounts(kubeClient, namespace)
    if err != nil {
        return estimate, err
    }
    err = deleteServices(kubeClient, namespace)
    if err != nil {
        return estimate, err
    }
    err = deleteReplicationControllers(kubeClient, namespace)
    if err != nil {
        return estimate, err
    }
    estimate, err = deletePods(kubeClient, namespace, before)
    if err != nil {
        return estimate, err
    }
```

And more.  This is antithetical to maintainable software.  We need to fix this in 1.2

**Comment by bprashanth** [comment]
We should also fix how it handles experimental resources. Currently I can start the apiserver with experimental=true and the controller manager with autoscaler, deployments=false, and the ns controller will leak the other experimental resources. We really shouldn't need a flag per resource.  

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/namespace/namespace_controller.go#L195
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L285

**Comment by mikedanese** [comment]
cc @derekwaynecarr for namespace @caesarxuchao for API discovery

**Comment by derekwaynecarr** [comment]
The experimental issue is discussed and covered here:

https://github.com/kubernetes/kubernetes/issues/14562

We want it fixed because it Impact OpenShift as well.

I think this is blocked pending closure on API groups and discovery.

Self assigning

**Comment by caesarxuchao** [comment]
We can discovery all server-supported namespaced resources in three steps,
1. visit /apis, get a list of all supported groups;
2. call NegotiateVersion() to negotiate the version for each group (#14592 revised NegotiateVersion to work properly with concept of group);
3. visit /apis/group/negotiated_version to get a list of resources and whether they are namespaced, we also need to visit /api/v1 to discovery the legacy v1 resources.

We need to maintain a map between the resource names and the handler functions that delete the resources. In deleteAllContent(), we call them based on the the discovery results.

**Comment by derekwaynecarr** [comment]
I am going to take another sweep of the code to see if everything I need is there to support this feature, and will report back if there are gaps.  The goal as I understand it is for deleteAllContent() we will no look maintain a map between the resource names and the handler functions, and instead, we will be able to dynamically via a client make calls to `DELETE /namespace/foo/{kind}` to remove all items in the collection.

**Comment by thockin** [comment]
Awesome!  Thanks.

**Comment by derekwaynecarr** [comment]
Talked about this at today's kube-machinery-sig, I am waiting to implement this until the generic client implementation is in place, which per @lavalamp is _soon_.

**Comment by derekwaynecarr** [comment]
Also recording here so I don't forget, the namespace controller will cache its view of API server resources from discovery for a configured period of time.  By default, it would be ~1hr.
