### ISSUE TITLE
Integration/e2e tests of kubectl support for multiple resources

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14775]
Forked from #13812.

We advocate that users should specify multiple resources in a single file, yet we don't have adequate testing of that feature, and we broke it when we turned on schema validation by default.

It sounds like a test in test-cmd.sh would be adequate to exercise the default configuration of kubectl.

There are multiple ways to specify multiple resources:
* explicit List
* YAML document separator `---`
* JSON object concatenation(?)

Apparently different input sources are handled differently, at least for alternatives to an explicit List, so we probably need to at least test file and stdin. Not sure about directory and URL.

cc @liggitt @deads2k @feihujiang @smarterclayton @lavalamp

**Comment by JanetKuo** [comment]
`--validate` is only used in kubectl create, replace, and rolling-update. kubecl create is the only one specifying multiple resources. Added test for kubectl create multiple resources (rc + svc).

**Comment by liggitt** [comment]
Are you sure replace can't operate on a list input?

**Comment by smarterclayton** [comment]
Any command operation that uses resource.Builder and iterates the visited
items will work for list input.  I think replace is a singleton, but we
also updated a lot of other commands to iterate the list of returned
resources.

On Sep 30, 2015, at 4:03 AM, Jordan Liggitt <notifications@github.com>
wrote:

Are you sure replace can't operate on a list input?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14775#issuecomment-144258006>
.

**Comment by feihujiang** [comment]
I think we should add  tests for ReplicationControllerList, ServiceList etc. What's your point?

I tested the following example, and if --validate=false, they could be created.

The json example is as follows, which is fetched directly by api, not by kubectl get.

{
  "kind": "ReplicationControllerList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/default/replicationcontrollers",
    "resourceVersion": "322971"
  },
  "items": [
    {
      "metadata": {
        "name": "cassandra",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/replicationcontrollers/cassandra",
        "uid": "4104888f-674b-11e5-92b4-286ed488f788",
        "resourceVersion": "322870",
        "generation": 1,
        "creationTimestamp": "2015-09-30T08:14:21Z",
        "labels": {
          "name": "cassandra"
        }
      },
      "spec": {
        "replicas": 1,
        "selector": {
          "name": "cassandra"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "cassandra"
            }
          },
          "spec": {
            "volumes": [
              {
                "name": "data",
                "emptyDir": {}
              }
            ],
            "containers": [
              {
                "name": "cassandra",
                "image": "gcr.io/google_containers/cassandra:v6",
                "command": [
                  "/run.sh"
                ],
                "ports": [
                  {
                    "name": "cql",
                    "containerPort": 9042,
                    "protocol": "TCP"
                  },
                  {
                    "name": "thrift",
                    "containerPort": 9160,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                  {
                    "name": "MAX_HEAP_SIZE",
                    "value": "512M"
                  },
                  {
                    "name": "HEAP_NEWSIZE",
                    "value": "100M"
                  },
                  {
                    "name": "POD_NAMESPACE",
                    "valueFrom": {
                      "fieldRef": {
                        "apiVersion": "v1",
                        "fieldPath": "metadata.namespace"
                      }
                    }
                  }
                ],
                "resources": {
                  "limits": {
                    "cpu": "100m"
                  },
                  "requests": {
                    "cpu": "100m"
                  }
                },
                "volumeMounts": [
                  {
                    "name": "data",
                    "mountPath": "/cassandra_data"
                  }
                ],
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent"
              }
            ],
            "restartPolicy": "Always",
            "terminationGracePeriodSeconds": 30,
            "dnsPolicy": "ClusterFirst"
          }
        }
      },
      "status": {
        "replicas": 1,
        "observedGeneration": 1
      }
    },
    {
      "metadata": {
        "name": "frontend",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/replicationcontrollers/frontend",
        "uid": "8508283a-674b-11e5-92b4-286ed488f788",
        "resourceVersion": "322943",
        "generation": 1,
        "creationTimestamp": "2015-09-30T08:16:15Z",
        "labels": {
          "name": "frontend"
        }
      },
      "spec": {
        "replicas": 3,
        "selector": {
          "name": "frontend"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "frontend"
            }
          },
          "spec": {
            "containers": [
              {
                "name": "php-redis",
                "image": "gcr.io/google_samples/gb-frontend:v3",
                "ports": [
                  {
                    "containerPort": 80,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                  {
                    "name": "GET_HOSTS_FROM",
                    "value": "dns"
                  }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent"
              }
            ],
            "restartPolicy": "Always",
            "terminationGracePeriodSeconds": 30,
            "dnsPolicy": "ClusterFirst"
          }
        }
      },
      "status": {
        "replicas": 3,
        "observedGeneration": 1
      }
    }
  ]
}

**Comment by JanetKuo** [comment]
@feihujiang per my discussion with @bgrant0607, `ReplicationControllerList` and `ServiceList` are returned by apiserver from get operation, and you can't do write operation with these types. Therefore, users wont' specify these types in their config.

**Comment by lavalamp** [comment]
Plain `List` is definitely more convenient, but there's no reason to
prevent users from specifying the more specific list types.

**Comment by bgrant0607** [comment]
AFAIK, it isn't supported currently and we're not adding that feature now.

**Comment by JanetKuo** [comment]
@liggitt @smarterclayton I'll add tests for all commands that should work for `List` input.
