### ISSUE TITLE
GCE reboot tests flaky

### ISSUE THREAD

**Issue by fabioy** [kubernetes/kubernetes#14772]
A few reboot tests are being flaky, affecting the Jenkins project status, which affects the merge-bot rate. The flaky tests:

(2 fails in last 10 runs)
- Reboot each node by switching off the network interface and ensure they function upon switch on
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:83
Sep 29 10:10:46.304: Node e2e-reboot-minion-5vaz failed reboot test.

(2 fails in last 10 runs)
- Reboot each node by ordering unclean reboot and ensure they function upon restart
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:71
Sep 29 10:12:59.060: Node e2e-reboot-minion-i0rp failed reboot test.

(2 fails in last 10 runs)
-Reboot each node by dropping all outbound packets for a while and ensure they function afterwards
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:99
Sep 29 12:58:18.443: Node e2e-reboot-minion-cm4k failed reboot test.

(1 fail in last 10 runs)
-Reboot each node by triggering kernel panic and ensure they function upon restart
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:77
Sep 29 14:18:47.006: Node e2e-reboot-minion-jx2o failed reboot test.

**Comment by brendandburns** [comment]
@davidopp for triage

**Comment by bgrant0607** [comment]
See also #9349, #12800

**Comment by quinton-hoole** [comment]
Close once we've seen 20 successful test runs after merging #14784, which hopefully addresses the flakyness reported here.

**Comment by quinton-hoole** [comment]
Success!
