### ISSUE TITLE
Create sustainable testing for GKE & GCE upgrades and version skew

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#14771]
#14760 is the first pass at this for GKE, but it will no longer work once we start doing stable releases of 1.1.

**Comment by ihmccreery** [comment]
Since we cut a `1.2.0-alpha`, this is now P0.  We need a good way to upgrade from 1.0 to 1.1 during tests, which we don't have right now, because `latest` is `1.2.0-alpha`.

**Comment by davidopp** [comment]
@ihmccreery can you give an update on the status of this issue?

**Comment by ihmccreery** [comment]
What's left is just to get in and stabilize #15717, and port to GCE.

**Comment by ihmccreery** [comment]
Closing this, since the remainder of the work is covered in #14674 and #13602.
