### ISSUE TITLE
Kubectl describe pod qos tiers is missing BestEffort

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#14786]
Right now, when you describe a pod, it lets you know the qos tier for the pod memory and CPU if it has a specified request or limit.  If you do not have a memory or CPU value enumerated, it appears to say nothing.

For completeness, it should tell the user that it has BestEffort qos for non enumerated resources.

FYI @JanetKuo

**Comment by zhengguoyong** [comment]
hi Derek,
what do you mean by BestEffort qos?
@derekwaynecarr

**Comment by derekwaynecarr** [comment]
@zhengguoyong - for details on QoS, see:
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/resource-qos.md

as for this issue, I would expect this image:
https://cloud.githubusercontent.com/assets/4876867/9777437/528907b6-5719-11e5-8fbc-7c6a1043582e.png

to show 

```
QoS Tier
  cpu: Burstable
  memory: BestEffort
```

Will send a PR today.
