### ISSUE TITLE
Version-skewed testing of kubectl

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14780]
Forked from #3334 and #2953.

We should test older and newer versions of kubectl with the apiserver. Integration tests (test-cmd.sh) might be sufficient, but we should consider e2e tests, also.

**Comment by derekwaynecarr** [comment]
@kubernetes/rh-ux - do we have anything in OpenShift that we can contribute upstream here?

**Comment by ihmccreery** [comment]
Closing in favor of #16040.
