### ISSUE TITLE
Containerize verification checks, unit tests, and integration test

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#14781]
In the pull request Jenkins, we're running up to 8 instances of verification checks, build, unit tests, integration tests, and e2e tests.

Unfortunately, it seems like several of these components were not designed to run simultaneous to other tests on the same machine.

In particular, several unit tests seem to write to static file names in /tmp (or equivalent), which is a fairly easy fix. Some of the verification checks and the integration test start up etcd, however, and the etcd helper checks that only a single etcd binary is running on the host (and uses a static port for it).

For example:
```
Verifying ./hack/../hack/verify-generated-swagger-docs.sh
+++ [0929 12:56:12] Building go targets for linux/amd64:
    cmd/genswaggertypedocs
+++ [0929 12:56:12] Placing binaries
Generating swagger type docs for unversioned
Generating swagger type docs for v1
Generating swagger type docs for experimental/v1alpha1
+++ [0929 12:56:15] Building go targets for linux/amd64:
    cmd/kube-apiserver
+++ [0929 12:56:28] Placing binaries

etcd appears to already be running on this machine (7295 etcd) (or its a zombie and you need to kill its parent).


retry after you resolve this etcd error.

+++ [0929 12:56:29] Clean up complete
!!! Error in /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/update-swagger-spec.sh:31
  '"${KUBE_ROOT}/hack/after-build/update-swagger-spec.sh" "$@"' exited with status 1
Call stack:
  1: /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/update-swagger-spec.sh:31 main(...)
Exiting with status 1
!!! Error in /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/update-generated-swagger-docs.sh:68
  '"${KUBE_ROOT}/hack/update-swagger-spec.sh"' exited with status 1
Call stack:
  1: /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/update-generated-swagger-docs.sh:68 main(...)
Exiting with status 1
!!! Error in /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/after-build/verify-generated-swagger-docs.sh:46
  '"${KUBE_ROOT}/hack/update-generated-swagger-docs.sh"' exited with status 1
Call stack:
  1: /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/after-build/verify-generated-swagger-docs.sh:46 main(...)
Exiting with status 1
!!! Error in ./hack/../hack/verify-generated-swagger-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-swagger-docs.sh" "$@"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-generated-swagger-docs.sh:28 main(...)
Exiting with status 1
FAILED
```

```
+++ [0929 13:03:14] Building go targets for linux/amd64:
    cmd/integration
+++ [0929 13:03:31] Placing binaries

etcd appears to already be running on this machine (7295 etcd) (or its a zombie and you need to kill its parent).


retry after you resolve this etcd error.

+++ [0929 13:03:32] Integration test cleanup complete
```

We might be able to fix the etcd issue separately, or we can just figure out how to containerize all of these tests so they can't possibly interfere with each other.

Note that we're ignoring the exit status of the verification checks and unit/integration tests right now, so these etcd failures are effectively being ignored (though it is causing us to miss test coverage).

@kubernetes/goog-testing

**Comment by quinton-hoole** [comment]
@ixdy What percentage of tests are failing due to being non-hermetic like this?

**Comment by ixdy** [comment]
I'm not sure about unit tests (I've anecdotally seen just a few fail), but the verification checks are failing fairly regularly, and the integration test is also similarly frequently not running due to this.

**Comment by quinton-hoole** [comment]
To be clear, I'm looking for real numbers, to decide whether it's feasible to temporarily disable a small number of tests until we can hermetify them.  Otherwise we need to turn off all unit, integration and verification tests in Jenkins to avoid irritation invalid regression signals.  We need to do one or the other this week.

**Comment by quinton-hoole** [comment]
I'll try to dig through the logs, figure out which ones have failed recently, disable them in Jenkins, and see whether the flakes abate.

**Comment by quinton-hoole** [comment]
I just turned off all unit, integration and verification checks in Jenkins, as a temporary measure to unstall the merge-bot.

**Comment by ixdy** [comment]
As a point of information, I just found approximately 20 tests in `pkg/kubelet/network/exec/exec_test.go` which use a static tmp path `/tmp/fake/plugins/net` with semi-random filenames which are highly likely to collide.

We could keep searching for unit tests that are non-hermetic, but it'd probably be a better investment of time to fix the test infrastructure so test authors don't need to care (and so we don't need to go look at and fix ~2000 test cases).

**Comment by ixdy** [comment]
Another few metrics, using the string "/tmp" as a likely anti-pattern:
```console
github.com/kubernetes/kubernetes $ find pkg -iname *_test.go | xargs grep -l "/tmp/" |  find pkg -iname *_test.go | xargs grep "/tmp" | wc -l
76

github.com/kubernetes/kubernetes $ find pkg -iname *_test.go | xargs grep -l "/tmp/" |  find pkg -iname *_test.go | xargs grep -l "/tmp" | sort 
pkg/cloudprovider/providers/mesos/client_test.go
pkg/controller/persistentvolume/persistentvolume_claim_binder_controller_test.go
pkg/kubelet/kubelet_test.go
pkg/kubelet/network/cni/cni_test.go
pkg/kubelet/network/exec/exec_test.go
pkg/kubelet/runonce_test.go
pkg/master/master_test.go
pkg/util/io/io_test.go
pkg/volume/aws_ebs/aws_ebs_test.go
pkg/volume/cephfs/cephfs_test.go
pkg/volume/cinder/cinder_test.go
pkg/volume/downwardapi/downwardapi_test.go
pkg/volume/empty_dir/empty_dir_test.go
pkg/volume/fc/fc_test.go
pkg/volume/gce_pd/gce_pd_test.go
pkg/volume/git_repo/git_repo_test.go
pkg/volume/glusterfs/glusterfs_test.go
pkg/volume/host_path/host_path_test.go
pkg/volume/iscsi/iscsi_test.go
pkg/volume/nfs/nfs_test.go
pkg/volume/persistent_claim/persistent_claim_test.go
pkg/volume/rbd/rbd_test.go
pkg/volume/secret/secret_test.go
```

We'd need to update each of these 23 files to get them to use `os.TempDir` or `ioutil.TempDir` if they aren't already.

**Comment by ixdy** [comment]
Created #15176 to track cleaning up tempdir usage in unit tests.

**Comment by ixdy** [comment]
cc @jlowdermilk
