### ISSUE TITLE
Configuration generation based on application type inference

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14801]
We should be able to generate configurations (like kubectl run, expose) from application information.

One source could be the container, like podex: https://github.com/kubernetes/contrib/tree/master/podex

Another source could be source files, like otto or build packs:
https://github.com/hashicorp/otto/tree/master/appfile/detect
https://docs.cloudfoundry.org/buildpacks/custom.html

**Comment by bgrant0607** [comment]
cc @brendandburns @kubernetes/goog-ux

**Comment by bgrant0607** [comment]
We could also link to configs or get other default values from image labels:

http://developerblog.redhat.com/2015/04/21/introducing-the-atomic-command/
http://www.projectatomic.io/blog/2015/09/introducing-vendor-labels2/

**Comment by kargakis** [comment]
@kubernetes/sig-apps

**Comment by bgrant0607** [comment]
Looks like packs do this:
https://github.com/Azure/draft/blob/master/docs/packs.md

**Comment by bgrant0607** [comment]
We're not going to do this here.
