### ISSUE TITLE
Write a doc describing our status and plans for hard/soft affinity/anti-affinity (scheduling)

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#14816]
The discussion is currently scattered among a number of issues and PRs. I will write something up.

@bgrant0607 @kevin-wangzefeng @ravigadde

**Comment by davidopp** [comment]
ref/ #14543 
ref/ #14485 
ref/ #14484

**Comment by bgrant0607** [comment]
Also relevant:
#367
#341
https://github.com/kubernetes/kubernetes/issues/4301#issuecomment-74355529

**Comment by bgrant0607** [comment]
Also related is control over what runs where: https://github.com/kubernetes/kubernetes/pull/14054#issuecomment-144229094

**Comment by bgrant0607** [comment]
#14573

**Comment by derekwaynecarr** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by bgrant0607** [comment]
We also need to address the tradeoffs between putting the policy directly in the pod vs. elsewhere.

**Comment by davidopp** [comment]
Can you elaborate what mean by "elsewhere"? I assume you don't mean in the controller spec (since the affinity/anti-affinity request has to be visible to the scheduler). Are you thinking of an annotation?

**Comment by resouer** [comment]
@davidopp Any update here?

**Comment by davidopp** [comment]
Sorry, no. We had a lot of last-minute work for the 1.1 release and then I was out of the office for the lat week and a half. I will get back to this issue soon.
