### ISSUE TITLE
Proposal to add service description information as standard Service Annotations.

### ISSUE THREAD

**Issue by KurtStam** [kubernetes/kubernetes#14828]
Every service consumer need to have access to a bit more then the endpoint host and port name to be able to consume a service. In this proposal (https://kurtstam.github.io/2015/09/22/Proposal-for-Kubernetes-Service-Annotations.html) we advocate for a convention to use of 4 _standard_ kubernetes service annotations:
- servicepath
- protocol
- descriptionpath
- descriptiontype

We hope that these annotations can become part of the Kubernetes Specification. There is no need to modify the Kubernetes API to adopt this convention.

Cheers,

--Kurt

**Comment by rhuss** [comment]
Like it, however for symmetry and consistencies sake I'd recommend

* servicePath
* serviceType
* descriptionPath
* descriptionType

**Comment by thockin** [comment]
I don't understand what this is for, and I am not sure this is the right way to do it anyway.

I don't know that Service is the right place to attach this info - this feels closer to the new Ingress object (@bprashanth)

Multi-dimensional annotations are immediately suspicious.

Tactically: annotations should be namespaced.  `whatever.yourdomain.com/name = value`

**Comment by KurtStam** [comment]
Thanks for the quick response @thockin. 

1. The Service already contains information about the host and port, these annotations add to that with the service Path, protocol/Type, and a link to the definition document of the service. Among other things it allows for automation of consumption of the service by clients. 

2. Where can I read more about the new Ingress object?

3. True, the multi-dimensional part would probably not even used that much, so I'm fine with keeping it one dimensional.

4. So if this would be a convention supported by Kubernetes the namespace would be `kubernetes.io`? I guess I assumed the domain would be omitted in that case.

**Comment by thockin** [comment]
> Among other things it allows for automation of consumption of the service by clients.

As lightweight as a bunch of annotations seems, we need to be very careful in what we endorse as "sanctioned" patterns.  I'm looking for concrete problems that this solves and/or similar proven approaches that have solved real problems.

> Where can I read more about the new Ingress object?

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/experimental/v1alpha1/types.go#L479

> So if this would be a convention supported by Kubernetes the namespace would be kubernetes.io? I
> guess I assumed the domain would be omitted in that case.

The name is required for sanctioned annotations and labels - un-namespaced names are reserved for users.  But before we adopt any pattern I really need to understand WHY we're doing it.  Nothing stops you from doing it outside the kubernetes.io namespace in the meantime, and gathering some momentum behind it.

**Comment by KurtStam** [comment]
@thockin it does 'feel' like the ingress object maybe what I'm looking for. The references on the https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/experimental/v1alpha1/types.go#L479
don't actually link to good documentation on this however. Is this part of the spec still being worked and can I be part of it?

A concrete example of where this is used is in fabric8 where we can import services from fabric8 into our api manager by doing a lookup in kubernetes. We present the user will all services in his namespace. https://kurtstam.github.io/2015/09/22/Protect-a-Fabric8-REST-Service-with-Apiman.html. We use the proposed service annotations to set the endpoint url, type, definition url and type in the api-manager. This is the type of info every service consumer needs. You can take it one step further and generate a generate a client like http://editor.swagger.io/#/ can.

Regarding the namespaced labels, we will start using fabric8.io for now. I do think it makes sense for Kubernetes to sanction some pattern to store information like this even if not using annotations as it is very much solves a generic service consumption problem.

**Comment by bgrant0607** [comment]
I'm pretty sure we've discussed this before somewhere.

Enlightened clients do sometimes need more information about endpoints, such as scheme (for http/https), client configuration info, etc. This would be useful for UIs, as well, to hint that they should create links to endpoint URLs. I could see a case for discovery and probe paths.

Starting with annotations seems fine. It seems too early to standardize.

**Comment by KurtStam** [comment]
Thanks for the support @bgrant0607. I do want to stress that this goes beyond the 'scheme and client config', and really is about discovering where the service lives and where to get the definition/'contract' that describes how to consume the service. In many environments services are consumed by a third party. Particularly these folks need access to this kind of info. These patterns have been used before in for instance UDDI (yes I'm the same guy that ran the Apache jUDDI project for a while), so if you say 'too early to standardize' what does that mean? Is Kubernetes not ready for it? Or is your judgement that the proposed annotation 'standard' is not developed far enough? I don't really understand where the 'ingress' concept is at the moment and I would like to help and push things forward!

**Comment by KurtStam** [comment]
I have updated the proposal and incorporated the feedback, please see https://kurtstam.github.io/2015/10/15/Update-1-Proposal-for-Kubernetes-Service-Annotations.html. Changes are:
- dropped support for multiple endpoints
- added a namespace to the annotation keys of 'apiman.io/'

**Comment by thockin** [comment]
If you want to put it in a different annotation space, be prepared to keep
it there, at least for a while.  I have no problem with that and I think
the namespacing of labels and annotation is designed exactly for this use -
for you to define a standard of your own that is related-to but not part-of
kubernetes.

The biggest problem I have with this is that it sort of assumes HTTP, which
is absolutely not true for every Service.  It would be nice if that was
clearer.

I have smaller gripes with naming and things, but since I can't make line
comments on an HTML page, I will just wait for a PR or something.

**Comment by bgrant0607** [comment]
Proposal still assumes all services are http and overlaps with ingress.

But I do think we'll want to document the scheme/protocol, API discovery paths, client config, client secrets, etc. We'll want to add more introspection probes on pods, also, in addition to readiness.

cc @smarterclayton @liggitt @bryk

**Comment by bgrant0607** [comment]
See also #6908

**Comment by KurtStam** [comment]
@bgrant0607  >Proposal still assumes all services are http and overlaps with ingress.
Although the example shows http, it really is meant to be more generic. Looking some typical URLs:
jdbc:mysql://hostname:port/dbname or http://hostname:port/servicePath then really there are 3 parts. 
1 'scheme' : 'jdbc:mysql', 'http'
2 'host and port name' - management by kubernetes
3 'servicePath' - everything after 'port', i.e. dbname
and the first part ('scheme') is what is missing from the current proposal. Would adding a 'serviceScheme' annotation address your concerns?

@thockin >  have smaller gripes with naming and things, but since I can't make line
comments on an HTML page, I will just wait for a PR or something.
Tim, shall I update with the above enhancement and submit it as a PR?

**Comment by bgrant0607** [comment]
cc @ggogolowicz

**Comment by ncdc** [comment]
@KurtStam please go ahead and submit the proposal as a PR, thanks!

**Comment by KurtStam** [comment]
@thockin @ncdc what is the current status of the proposal? It's currently found here:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network/service-discovery.md

Do we need to resubmit it into the new proposal as part of this process?  https://kubernetes.io/docs/community/keps/ which seems overkill since we are just talking about a naming convention here.

Looking forward hearing from you!

**Comment by ncdc** [comment]
@KurtStam sorry it took a while to reply. I am not sure where to go from here - @timothysc do you have any advice?
