### ISSUE TITLE
Visibility into gce-reboot failures is poor

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#14836]
We often fail because a pod fails to become ready.  In that case we should grab logs and events for easier debugging.

@fgrzadkowski for triage.

**Comment by wojtek-t** [comment]
That's not really "kind/flake" - it's more like 'testing infrastructure".

**Comment by fejta** [comment]
Given that this is a couple quarters old without any progress I think we should close this out for now (possibility revisiting at a later date). However I'm going to unassign and take off the test-infra label in case area/cluster-lifecycle wants to keep it open.
