### ISSUE TITLE
serviceaccounts "default" already exists

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#14830]
Every time I start kube-controller-manager, I see this error-level log entry in kube-controller-manager.ERROR:

```
Log file created at: 2015/09/30 15:17:19
Running on machine: sea5m1kmaster1
Binary: Built with gc go1.4.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0930 15:17:19.016980   29089 controllermanager.go:201] Failed to start service controller: ServiceController should not be run without a cloudprovider.
E0930 15:17:19.439207   29089 serviceaccounts_controller.go:215] serviceaccounts "default" already exists
```

The first error (`should not be run without a cloudprovider`) is a known issue -- issue #12716 -- but the second error (`serviceaccounts "default" already exists`) doesn't appear to be described elsewhere.

Is that a configuration issue, or a kube-controller-manager bug?

These are my kube master processes:

```
/opt/kubernetes/bin/kube-apiserver \
     --v=2 \
     --insecure-bind-address=127.0.0.1 \
     --etcd-servers=http://localhost:4001 \
     --secure_port=6443 \
     --token-auth-file=/kubernetes/known_tokens.csv \
     --insecure-port=8080 \
     --kubelet_port=10250 \
     --admission_control=NamespaceLifecycle,NamespaceExists \
     --portal_net=11.1.1.0/24

/opt/kubernetes/bin/kube-controller-manager \
     --v=2 \
     --master=https://10.1.4.153:6443 \
     --kubeconfig=/kubernetes/config \
     --address=10.1.4.153 \
     --port=10252

/opt/kubernetes/bin/kube-scheduler \
     --v=2 \
     --master=https://10.1.4.153:6443 \
     --kubeconfig=/kubernetes/config \
     --address=10.1.4.153 \
     --port=10251
```

Is there any flag or config adjustments I should make? That is, is kubernetes attempting to add a redundant "default" service account due to a misconfiguration on my part? Or is this a bug in the kube-controller-manager?

**Comment by lavalamp** [comment]
@derekwaynecarr

**Comment by davidopp** [comment]
@kubernetes/kube-iam

**Comment by liggitt** [comment]
it's harmless... that's the controller attempting to ensure a service account exists for every namespace. we should tolerate `AlreadyExists` errors in that case... it just meant the local store didn't think we had a service account, so we tried to create one
