### ISSUE TITLE
Multi-container pod fate sharing issue

### ISSUE THREAD

**Issue by erimatnor** [kubernetes/kubernetes#14848]
I have a pod with an InfluxDB database container and a Kafka consumer container. The Kafka consumer imports data from Kafka into InfluxDB. 

Recently, the Kafka consumer container experienced an error, causing it to crash and preventing it from properly starting up again. However, the InfluxDB container was still running fine.

The issue is that Kubernetes removed the endpoint for the service I created for the pod, which I assume is because it didn't deem the pod healthy or ready. However, this prevented other pods from accessing the InfluxDB database.

I am wondering if this type of fate sharing among containers in a pod is a good design? I assume that had I set "ClusterIP: None" in the service (i.e., no proxy/LB), InfluxDB would still be accessible. Maybe it is better to to create an endpoint as long as at least one container is running in the pod? Or, at least make this configurable.

I think it is a common deployment pattern in Kubernetes that you have a side-car container that performs some simple, but non-critical task (like backups, or configuration updates, etc.). A failure in one of these side-cars shouldn't bring down an otherwise functioning service.

**Comment by thockin** [comment]
I think this is correct as a default policy.  We can't know, absent
explicit info, which containers in a pod are required -- we have to assume
they all are.

We could add config that designates some containers as non-critical, but I
am not convinced we should.  That pod is failing, and this would just paper
over the failure.

**Comment by erimatnor** [comment]
Maybe failing the pod as a default is OK. However, I think in many cases other higher-level services or monitoring systems would determine the health of a pod (by e.g., doing e2e application layer checks). A non-critical side-car container shouldn't bring down a service (I mean if I would run my two containers on the same physical host outside of Kubernetes the service would have continued to work even if the sidecar failed). It is fine if the pod is marked as degraded and an admin can look into it, but in the meantime it would be good if a pod continues to serve requests if it still can. This way it would fail gracefully or just have a degraded state.

**Comment by bgrant0607** [comment]
@erimatnor Did you specify readiness probes for any/all of the containers?

**Comment by erimatnor** [comment]
@bgrant0607 No liveness probes specified.

**Comment by thockin** [comment]
Liveness and readiness probes should not matter because they are on each
container, not the Pod overall.  We could add higher-level readiness and/or
liveness on the Pod, but it seems to me that this is adding significant
complexity for a rather corner case.

If a single container is crashing the pod is marked as Ready:false.  Do we
really need to get more nuanced than that?

**Comment by bgrant0607** [comment]
@thockin We aggregate container readiness into pod readiness already, which is what we use to remove the pod from ready endpoints. I don't remember whether we AND or OR the container readiness, but it's definitely all or nothing.

**Comment by thockin** [comment]
My point was that we COULD add a way for the pod to indicate Ready that was
more customizable than "all containers ready".  But I also said I am not
convinced it's a good spend of complexity.
