### ISSUE TITLE
Docs cleanup: linewrap

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#1488]
Markdown does not seem to care if my editor manually wraps lines or not.  We have some docs that never linewrap manually, some that do, and some that mix it up.

I propose we say that docs should linewrap at 80 columns, unless there is a line (a URL or table or something) for which 80 columns is a problem.  We don't need to be religious about it, but I think it would be good to have consistency over time.

**Comment by mikebrow** [comment]
Agree with convention to linewrap docs at 80cols. (usage, md docs, ...)

**Comment by thockin** [comment]
Closing now.  No point in keeping this open
