### ISSUE TITLE
Local vagrant kube-up fails if the KUBERNETES_VAGRANT_USE_NFS option is set

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#14887]
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'minion-1' up with 'virtualbox' provider...
==> master: Box 'kube-fedora21' could not be found. Attempting to find and install...
    master: Box Provider: virtualbox
    master: Box Version: >= 0
==> master: Box file was not detected as metadata. Adding it directly...
==> master: Adding box 'kube-fedora21' (v0) for provider: virtualbox
    master: Downloading: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-21_chef-provisionerless.box
==> master: Successfully added box 'kube-fedora21' (v0) for 'virtualbox'!
==> master: Importing base box 'kube-fedora21'...
==> master: Matching MAC address for NAT networking...
==> master: Setting the name of the VM: kubernetes_master_1443656877945_24341
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 => 2222 (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2222
    master: SSH username: vagrant
    master: SSH auth method: private key
    master: Warning: Connection timeout. Retrying...
    master: 
    master: Vagrant insecure key detected. Vagrant will automatically replace
    master: this with a newly generated keypair for better security.
    master: 
    master: Inserting generated public key within guest...
    master: Removing insecure key from the guest if it's present...
    master: Key inserted! Disconnecting and reconnecting using new SSH key...
==> master: Machine booted and ready!
==> master: Checking for guest additions in VM...
==> master: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/bin/systemctl restart rpcbind nfs

Stdout from the command:

Stderr from the command:

Job for nfs-server.service failed. See "systemctl status nfs-server.service" and "journalctl -xe" for details.

**Comment by chrisleck** [comment]
Perhaps an instance of https://github.com/mitchellh/vagrant/issues/6114 ?

Why use fedora as the hosting OS for these VMs?  Wouldn't CoreOS be more appropriate?

**Comment by imesh** [comment]
I encountered this issue in Kubernetes 1.1.3. Is this fixed now?

**Comment by liggitt** [comment]
vagrant provider has been removed
/close
