### ISSUE TITLE
Making GroupVersion a type to avoid confusion

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#14886]
After we introduce group, we pass around `group/version` in many places. Many fields/variables/input parameters are still named `Version` while they actually contain `group/version`. 

To let the compiler help us avoid such confusion, we need to create types for Group, Version, and GroupVersion. This requires a lot of refactoring and will be hard to get cherry-picked to v1.1, so we will do that after 1.1 release.

@lavalamp @deads2k @smarterclayton

**Comment by deads2k** [comment]
+1  This would really help with code clarity.

**Comment by lavalamp** [comment]
This is near the top of my list of refactors that need to be done.

**Comment by caesarxuchao** [comment]
#16173 has a better summay. Close this one.
