### ISSUE TITLE
TestMaxInFlight is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#14899]
I've already seen it happening few times:

    E1001 13:18:21.582768    6716 errors.go:62] apiserver received an error that is not an unversioned.Status: test Error
    E1001 13:18:21.758605    6716 apiserver.go:453] Failed to parse "not a timeout": time: invalid duration not a timeout
    E1001 13:18:21.782217    6716 apiserver.go:421] apiserver was unable to write a JSON response: type apiserver.UnregisteredAPIObject is not registered for "version" and it will be impossible to Decode it, therefore Encode will refuse to encode it.
    E1001 13:18:21.782232    6716 errors.go:62] apiserver received an error that is not an unversioned.Status: type apiserver.UnregisteredAPIObject is not registered for "version" and it will be impossible to Decode it, therefore Encode will refuse to encode it.
    --- FAIL: TestMaxInFlight (0.00s)
    	handlers_test.go:49: unexpected response: 429
    FAIL
    FAIL	k8s.io/kubernetes/pkg/apiserver	0.466s

**Comment by wojtek-t** [comment]
I will take a look.

**Comment by fgrzadkowski** [comment]
I got this error again from HEAD:
```
E1007 16:32:45.067753   10744 errors.go:62] apiserver received an error that is not an unversioned.Status: test Error
E1007 16:32:45.341542   10744 apiserver.go:457] Failed to parse "not a timeout": time: invalid duration not a timeout
E1007 16:32:45.406559   10744 apiserver.go:425] apiserver was unable to write a JSON response: type apiserver.UnregisteredAPIObject is not registered for "version" and it will be impossible to Decode it, therefore Encode will refuse to encode it.
E1007 16:32:45.406590   10744 errors.go:62] apiserver received an error that is not an unversioned.Status: type apiserver.UnregisteredAPIObject is not registered for "version" and it will be impossible to Decode it, therefore Encode will refuse to encode it.
--- FAIL: TestMaxInFlight (0.00s)
	handlers_test.go:48: unexpected response: 429
FAIL
```

**Comment by wojtek-t** [comment]
I tried to reproduce it today but failed.
