### ISSUE TITLE
TestPluginTearDownHook is flaky

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#14891]
I've seen it fail several times on Shippable:

https://app.shippable.com/builds/560ba4e7cedf4d0d00472634
https://app.shippable.com/builds/560c2ae450483a0d00232996

But the logs are lousy and I can't actually see the failure... 

@thockin

**Comment by nikhiljindal** [comment]
I have seen it fail many times on Jenkins as well.
