### ISSUE TITLE
NegotiateVersion is not working properly

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#14895]
NegotiateVersion has several problems:
1. NegotiateVersion does not check group/versions exposed at /apis and prints a warning message when using kubectl to create an experimental resource.
2. NegotiateVersion takes the client#Config.Version into consideration, but it's not clear what value should be put in client#Config.Version as we have multiple groups now. We plan to create a config for each group, and calls NegotiateVersion for each group.
#14592 fixes the problem but it needs to be broken into smaller pieces to receive proper review.

In #14893 we temporarily disable the warning message in NegotiateVersion. We need to revert that when we have a proper fix.

@lavalamp @krousey

**Comment by bgrant0607** [comment]
We should ignore the client config version.

**Comment by caesarxuchao** [comment]
@bgrant0607 why should we ignore it? That will make --api-version and the apiVersion in kubeconfig useless.

(FYI, we are replacing api-version with preferred-versions in #14383)

**Comment by bgrant0607** [comment]
The apiVersion in kubeconfig is already useless. We need to think about what we want to do about --api-version.

Now is a good time to deprecate these, since there's only 1 API version in 1.0: v1.

**Comment by caesarxuchao** [comment]
Close due to age.
