### ISSUE TITLE
[Mesos] TestAfterDeath is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#14898]
I1001 13:12:21.553212   31893 task_test.go:104] tt initialized
    I1001 13:12:21.553367   31893 task_test.go:91] tt.Finished: ok true
    E1001 13:12:21.553369   31893 task.go:210] logger for task "bar" crashed: qux
    I1001 13:12:21.553492   31893 task.go:373] task "bar" exited with status 2
    I1001 13:12:21.553519   31893 task.go:373] task "foo" exited with status 1
    I1001 13:12:21.553667   31893 task_test.go:200] each task process has completed one round
    I1001 13:12:21.553704   31893 task_test.go:215] firing quit signal
    I1001 13:12:21.553717   31893 task_test.go:218] waiting for tasks to die
    I1001 13:12:21.553769   31893 task.go:313] killing foo (force=false) : 
    I1001 13:12:21.553836   31893 task.go:313] killing bar (force=false) : 
    I1001 13:12:21.553881   31893 task_test.go:221] waiting for merge to complete
    I1001 13:12:21.553918   31893 task.go:313] killing foo (force=false) : 
    I1001 13:12:21.553956   31893 task.go:313] killing foo (force=true) : 
    I1001 13:12:21.554115   31893 task.go:313] killing foo (force=false) : 
    I1001 13:12:21.554154   31893 task.go:313] killing foo (force=true) : 
    W1001 13:12:21.554167   31893 task.go:316] failed to kill process: "" pid -1: for some reason kill failed
    I1001 13:12:21.554186   31893 task.go:313] killing foo (force=false) : 
    W1001 13:12:21.554197   31893 task.go:316] failed to kill process: "" pid 0: for some reason kill failed
    --- FAIL: TestAfterDeath (0.00s)
            Error Trace:    task_test.go:244
	    Error:		Not equal: 123 (expected)
	    		        != 0 (actual)
		
            Error Trace:    task_test.go:245
    	Error:		No error is expected but got failed to kill process: ""
		
    FAIL
    FAIL	k8s.io/kubernetes/contrib/mesos/pkg/minion/tasks	0.049s

**Comment by davidopp** [comment]
@kubernetes/kube-mesos
