### ISSUE TITLE
JSON output format directive overrides templates

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/kubernetes#14905]
When invoking a command like `kubectl get pods --template='{{...}}'`, the output can often be large swaths of text that are difficult to parse. It would be nice to have some sort of pretty-print option for the output. When I append `-o json` to that, the `--template` directive is ignored and the entire output of `kubectl get` is output as JSON. It is _not_ reasonable to be able to express the output of a template with JSON or YAML, but when either option is present alongside a template there should be an error raised, otherwise it is confusing and looks like the template does not function as expected.

**Comment by pmorie** [comment]
@rh-ux

**Comment by bgrant0607** [comment]
cc @daizuozhuo

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by stevekuznetsov** [comment]
This is less pressing now-days as it's `-o template --template $template` and that is clearly going to clash with `-o json`. Pretty-printing would still be nice, though.
