### ISSUE TITLE
Output for comparison: How is my cluster configured?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14916]
Idea is to have a command that outputs, in a stably-sorted & diffable between different clusters (or the same cluster over time), a list of binaries, flags, settings, etc.

Goal is to take a non-working and working cluster, diff this output, and see the relevant differences.

This is like "Diagnose me" but without the diagnose part.

**Comment by timothysc** [comment]
At some point we need to address the notion of how options are passed through the system.  Ideally we could create a well established pattern and leverage a single serializable set of options from the command line through to daemon invocation.
