### ISSUE TITLE
Determine how namespaces and labels and access control interact.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#1491]
Simple approach: 
- Selectors can only refer to labels in one namespace
- the namespace is the one of the object that the selectors is attached to.
- if a replicationController wants to add a label to a pod, for example, then how does it avoid colliding with other labels
  - put labels on the template (how to support replicationController-provided values)
  - reserve certain label keys (e.g. replController-opaqueInstanceId=xe4h1)
- only access control is "can I see this namespace", which allows or denies seeing the object, their labels, and doing selectors on them.

Complex approach:
- Selectors can refer to labels in other namespaces 
- define format like `<namespace>/<base key>=<value>
- need access controls to prevent someone from setting labels that would cause their pods to join services they shouldn't be in.
- need access controls to prevent users from determining the existence of labels they should not be able to see.

Recommendation:
- Keep is simple for now.  Can always prepend namespace and add access controls later.

**Comment by bgrant0607** [comment]
Selectors only work within namespaces for namespaced targets.
