### ISSUE TITLE
Conformance test documentation

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14913]
We need to ship documentation with the conformance test that it should be run from the conformance test branch, not HEAD or 1.x release branches.

**Comment by sttts** [comment]
There is actually documentation in the hack/conformance-test.sh script itself.

**Comment by erictune** [comment]
In https://github.com/kubernetes/kubernetes/issues/13896#issuecomment-144591846 @karlkfi argues that we should run from head.  I'm fine with that.  In that case, the branch should be deleted and the script updated.

**Comment by jayunit100** [comment]
@kubernetes/sig-testing we are rebooting this issue, i think; we can close the issue once the PR of the new minimal basis set is merged.

**Comment by erictune** [comment]
@jayunit100 is that PR merged?

**Comment by jayunit100** [comment]
For now the conformance tests have been updated I believe ; but I've lost track of this issue....

**Comment by spiffxp** [comment]
PR coming soon for this, I'm trying to confirm the tests pass as documented across at least 2 different providers.  I'd really like to get rid of `conformance-test.sh` if possible

**Comment by spiffxp** [comment]
Per #23353 the docs have been updated on master, and `hack/conformance-test.sh` has been removed.  Do we need to cherry pick these doc changes into previous release branches?

**Comment by spiffxp** [comment]
What do we think about closing this?  docs located at https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#conformance-tests

**Comment by erictune** [comment]
SGTM.
