### ISSUE TITLE
Create special test labels that add test-suites as a gatekeeper for merges.

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#14921]
We have the gce-e2e suite that acts as a gatekeeper for PR merges.

We should have the ability to add additional suite(s) to act as a gatekeeper for a PR merge.
This can be done by leveraging github labels.

Currently, we are in a mode where many tests are kicked out of gce-e2e suite because of slowness etc..

Having a custom label-driven suite gatekeeper, we can have certain PRs that need a specific test suite to be run, act as a gatekeep for the PR merges.  

@quinton-hoole 
@brendandburns 
@ixdy 
@thockin

**Comment by quinton-hoole** [comment]
@ArtfulCoder I think that we already have what you want:

https://github.com/kubernetes/contrib/blob/master/submit-queue/pod.yaml#L16

If so, please close this issue.

**Comment by quinton-hoole** [comment]
Sorry, ignore my comment above.  That's not what you want.  
You want to be able to tag specific PR's with additional suites to run.  Leave this issue open to track that please.  This issue should probably move to the kubernetes/contrib repo, where the merge-bot lives.

**Comment by ArtfulCoder** [comment]
closing this in favor of https://github.com/kubernetes/contrib/issues/137
