### ISSUE TITLE
cni.TestCNIPlugin flake

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#14931]
```
cni.TestCNIPlugin (from k8s.io_kubernetes_pkg_kubelet_network_cni)

Failing for the past 1 build (Since Unstable#10924 )
Took 0.18 sec.
Error Message

Failed
Stacktrace

cni_test.go:194: Mismatch in expected output for setup hook. Expected 'DEL /proc/12345/ns/net podNamespace podName dockerid4545454', got ''
```

**Comment by davidopp** [comment]
Yeah @wojtek-t mentioned he has been seeing this flake also.

Should we disable it for now?

**Comment by bprashanth** [comment]
@dcbw

**Comment by dcbw** [comment]
@mikedanese can you give some more details on the system where you're seeing this issue?  It was incredibly hard to reproduce locally, but happened often in Shippable before I added some workarounds in the testcases.

**Comment by gmarek** [comment]
I saw this on Jenkins.

**Comment by wojtek-t** [comment]
Yes - this is quite frequent (I've seen it 5+ times yesterday).

**Comment by wojtek-t** [comment]
I've just seen another one:

    cni_test.go:185: Mismatch in expected output for setup hook. Expected 'ADD /proc/12345/ns/net podNamespace podName dockerid2345', got ''

**Comment by dcbw** [comment]
I wasn't able to access Jenkins logs in the original PR; I kept getting "Access denied".  Are you able to paste some of the Jenkins logs for me?

**Comment by dcbw** [comment]
Would anyone mind testing a branch for me, since you seem to be able to reproduce the issue? I'll add a bunch of debugging stuff to the CNI test so we can get more info out of it, and then running 'make check' until it fails would be quite helpful.  Thanks!

**Comment by dcbw** [comment]
If you wouldn't mind running 'make check' on https://github.com/dcbw/kubernetes/tree/cni-fixes the output from that failure would be quite helpful.

**Comment by pmorie** [comment]
@kubernetes/rh-networking

**Comment by dcbw** [comment]
@davidopp @mikedanese any chance you can try out the cni-fixes branch I linked to above, so I can get some more debugging info about the issue?  Thanks!

**Comment by dcbw** [comment]
@wojtek-t any chance you can try out the cni-fixes branch I linked to above?

**Comment by a-robinson** [comment]
Jenkins has hit cni_test.go failures 4 times out of the last 30. There doesn't appear to be much of use in the output, though. These are the failures:
cni_test.go:175: Failed to select the desired plugin: Network plugin "cni" not found
cni_test.go:194: Mismatch in expected output for setup hook. Expected 'DEL /proc/12345/ns/net podNamespace podName dockerid4545454', got ''
cni_test.go:175: Failed to select the desired plugin: Network plugin "cni" not found.
cni_test.go:194: Mismatch in expected output for setup hook. Expected 'DEL /proc/12345/ns/net podNamespace podName dockerid4545454', got ''

@dcbw - if you think your change will help debug the flakes, how about we merge it into master so that it'll get run by jenkins?

**Comment by dcbw** [comment]
@a-robinson my cni-fixes branch won't fix anything, but it does emit more log info in the errors.  It really looks like a race condition in the testcases now, but we need the debug logging to narrow it down.

**Comment by a-robinson** [comment]
Adding more useful output to the test sounds good to me :+1:

**Comment by dcbw** [comment]
@a-robinson fixed up that branch and reposted so that it can be merged.

**Comment by dcbw** [comment]
See also https://github.com/kubernetes/kubernetes/pull/14983

**Comment by dcbw** [comment]
Been running 'make check' on a tight loop with https://github.com/kubernetes/kubernetes/pull/14983 for a couple hours and still unable to reproduce to get more debugging info.  If anyone is able to help test out and get that log output, that would be great.

**Comment by wojtek-t** [comment]
Is this still a problem? I didn't see this failing since quite a long time...

**Comment by mikedanese** [comment]
Me neither
