### ISSUE TITLE
Remove unnecessary admission controllers from the default list.

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#14934]
Remove unnecessary admission controllers from the default list of admission controllers that get applied today when a cluster is created.
unnecesary = serving no real purpose when users have workarounds 

@bgrant0607

**Comment by derekwaynecarr** [comment]
Do you have a candidate list?

**Comment by ArtfulCoder** [comment]
Want to definitely remove DenyEscalatingExec
Am open to suggestions.

**Comment by liggitt** [comment]
curious what the workaround for DenyEscalatingExec is

**Comment by derekwaynecarr** [comment]
This seems like an either or scenario.

Curious what scenario drove disabling the flag from being on?

I think we disable running privileged containers by default as well in the salt configuration.

**Comment by ArtfulCoder** [comment]
Privileged containers are now on by default
