### ISSUE TITLE
Container runtime does not check RestartPolicy for unhealthy containers

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#14930]
The container runtimes (both [docker](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1710) and [rkt](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/rkt/rkt.go#L1021)) do not check the pod restart policy when restarting unhealthy containers (they do check it before restarting dead containers).

**Comment by pmorie** [comment]
@kubernetes/rh-cluster-infra

**Comment by ncdc** [comment]
Is this a dupe of https://github.com/kubernetes/kubernetes/issues/14491?

**Comment by timstclair** [comment]
No, I think that is a different issue. This is only referring to containers which failed the health check (livenessProbe).
