### ISSUE TITLE
kube-proxy udp and skydns timeout limits  conflict

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#14939]
the skydns forwarding timeout limit is set to 2 seconds, whereas the kube-proxy udp idle timeout is less than a second (250 ms?).

We should align them in a way that makes sense, otherwise skydns will be wasting its time attempting to answer the query, long after the dnsclient has timed out.

````
/ # nslookup facebook.org 10.0.0.10
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'facebook.org'
/ # nslookup facebook.org 10.244.2.3
Server:    10.244.2.3
Address 1: 10.244.2.3

Name:      facebook.org
Address 1: 2a03:2880:f001:6:face:b00c:0:2 edge-star6-shv-01-sea1.facebook.com
Address 2: 31.13.77.6 edge-star-shv-01-sjc2.facebook.com

````

**Comment by ArtfulCoder** [comment]
#14527
#14625

**Comment by pmorie** [comment]
@kubernetes/rh-networking

**Comment by thockin** [comment]
We could close the FD so we don't have them open for a long time, but given
that this is UDP we should be able to transparently re-establish it.

Or we could get more clever with timeouts and set the initial timeout to 5
seconds, but once data has been received drop timeout to 0.25 seconds (on
the assumption that most UDP is DNS, which is a bit sketchy).

**Comment by thockin** [comment]
Also, this seems to be a non-issue for iptables proxier (just tested it).

**Comment by thockin** [comment]
Can you update this with the changes we made for commandline, and see if we can close this?

**Comment by ArtfulCoder** [comment]
closing issue. is not required with iptables-proxy which is now the default
