### ISSUE TITLE
Hitting ^C on e2e test should trap and cleanup

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#14944]

**Comment by pmorie** [comment]
@thockin What context did you hit this in?  I will double-check but I think this works if you're just running `e2e.test` directly

**Comment by thockin** [comment]
Go run hack/e2e.go.  Am I doing g it wrong?  We have like 5 levels of
indirection.

**Comment by pmorie** [comment]
I might be the one doing it wrong, I usually build e2e.test and run that.

**Comment by pmorie** [comment]
I see what you mean now.  Since i'm interrupting the e2e.test binary
directly I don't see it.  We need to trap sigint in e2e.go and
hack/ginkgo-e2e.sh.

**Comment by pmorie** [comment]
hrm, maybe we can trap in e2e.go and just exec in ginkgo-e2e.go

**Comment by thockin** [comment]
We should also define one true way to run e2e

**Comment by bprashanth** [comment]
.. that works on all platforms. Recently @aledbf ran into some problems with e2e on vagrant (KUBERNETES_PROVIDER was always getting overwritten to gce?), I think he just ended up running it on gce. Kinda like cutting your foot off so the shoe fits :)

**Comment by ixdy** [comment]
Assigning to @thockin given #20771.
