### ISSUE TITLE
kubectl run --expose

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14952]
To do a combined `kubectl run`, `kubectl expose`.

cc @brendandburns

**Comment by linzichang** [comment]
How is this going? Is someone working on this?

**Comment by JanetKuo** [comment]
Isn't this enough? `kubectl run -o yaml | kubectl expose -f -`

**Comment by JanetKuo** [comment]
Fixed by #15921. Closing this.
