### ISSUE TITLE
New kubectl command to list information about nodes in a cluster with options for filtering based on labels

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#14953]
something like:

kubectl list nodes --groupby label=kernel-version

**Comment by JanetKuo** [comment]
We currently have `--sort-by` in kubectl get. If we decide to support this, it should be:
 `kubectl get nodes --group-by=".Status.NodeInfo.KernelVersion"`, similar to --sort-by.

**Comment by hurf** [comment]
I'm interested in filtering outcome of kubectl by fields other than labels. I feel the fieldseletor isn't well used in kubectl.
