### ISSUE TITLE
Kubectl run should produce deployment and job

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#14954]
Forked from #1743.

Kubectl run should produce deployment and job rather than replication controller and raw pods.

Initially using an experimental generator version, which we can make the default once these APIs reach beta+ maturity.

**Comment by aronchick** [comment]
+1!

**Comment by derekwaynecarr** [comment]
The OpenShift run command does this today.

@smarterclayton @ironcladlou @deads2k

**Comment by smarterclayton** [comment]
Yeah, I overrode the generator for default always to create the deployment
equivalent. I did not rev our generator identifier version

On Oct 2, 2015, at 3:07 AM, Derek Carr <notifications@github.com> wrote:

The OpenShift run command does this today.

@smarterclayton @ironcladlou @deads2k

On Thursday, October 1, 2015, David Aronchick <notifications@github.com>
wrote:

> +1!
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/issues/14954#issuecomment-144890986
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14954#issuecomment-144892076>
.

**Comment by bgrant0607** [comment]
While these are still experimental we can't make it the default.

**Comment by bgrant0607** [comment]
Both of these should be at least beta in 1.2.
