### ISSUE TITLE
Use easily pronouncable phonetic names for pods

### ISSUE THREAD

**Issue by sakshamsharma** [kubernetes/kubernetes#14963]
A pod named "abc-qmeza" would be a convenience over  "abc-lr74h". The naming code should perhaps use phonetic vowel based naming.
This link does something similar:
http://tools.arantius.com/password
I can probably work on this if the suggestion is approved.

**Comment by F21** [comment]
How about something like docker's random name generator which generates a names using real words: https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go

**Comment by saksham0808** [comment]
That's a good idea, but that list isn't very large. Also, most of the words are more than 5 alphabets, which isn't desirable I think. We can implement a similar thing here though tailored for the purpose.

**Comment by thockin** [comment]
I might be ok with more phonetic randomness, but the names is not useful in
our context IMO

**Comment by pmorie** [comment]
> I might be ok with more phonetic randomness, but the names is not useful in
our context IMO

+1 re: names

**Comment by thockin** [comment]
And if we went phonetic, I think we need to be sure there's enough
entropy...

**Comment by saksham0808** [comment]
I wish to contribute to kubernetes, this seems like a good issue to start with. It'd be great if its possible. Let me know if its feasible.

**Comment by thockin** [comment]
@smarterclayton - any objections?

**Comment by smarterclayton** [comment]
My concern was succinctness.  The more things we generate, the larger the randomness pool needs to be, but the longer names get, and the less extra characters we have.  Docker doesn't mix phonetic and prefixes like we do either - I'd be worried that phonetic additions actually reduce readability and clarity in things like the pod list when you have lots of common prefixes.

I.e.

redis-8fjeb
redis-jbfir
cassandra-83csk
cassandra-jvken

Vs

redis-wicked-tuna
redis-reverse-mermaid
cassandra-miraculous-seaweed
cassandra-understated-octopus

If we add phonetic suffixes, do we reduce the readability of lists like this?  Mixing prefixes and dictionary suffixes seems like it could have the opposite effect - make distinguishing prefix and suffix harder.

**Comment by smarterclayton** [comment]
But removing numbers seems ok to me.

**Comment by smarterclayton** [comment]
Wed have to consider the impact of selection of things that look like common stub words - redis, slave, pods, serve, https, etc.  Those are all possible today, of course.

**Comment by smarterclayton** [comment]
To add to the stream of consciousness, we could afford a few more characters if we had to, 7 vs 5 is not a huge change.

**Comment by smarterclayton** [comment]
In summary - no objections

**Comment by thockin** [comment]
I figured a move from `my-redis-zg5kf` to `my-redis-dekits` (5suffix to
6suffix) was probably OK, though I'd like to see a quick analysis of the
random pool for the chosen algorithm to decide.

**Comment by bprashanth** [comment]
pets cough cough

**Comment by smarterclayton** [comment]
I'd like to introduce you to my cats "qjkoeu" and "jqkcgi".  They're
Norwegian.

**Comment by bgrant0607** [comment]
I see a place for phonetic names: Generated names for resources created from templates: #10495

**Comment by chrislovecnm** [comment]
PetSet addresses this nicely ... Is there some needs outside of what PetSet provides?

**Comment by sakshamsharma** [comment]
Had totally slipped from my mind. Unless this has already been done, or someone is working on it, I'd love to get this done, and in the process get familiar with the k8s code.
Can someone point me to the place where such a change would fit? I've looked a bit at `pkg/kubectl/cmd/create*.go` files, searching for the part where I could make a tweak; still new to the k8s code base. Any help is welcome :smile:

**Comment by smarterclayton** [comment]
It would be in pkg/api/rest/* - you can see the Generator type and the
various "simple" schemes.

On Nov 26, 2016, at 3:38 PM, Saksham Sharma <notifications@github.com>
wrote:

Had totally slipped from my mind. Unless this has already been done, or
someone is working on it, I'd love to get this done, and in the process get
familiar with the k8s code.
Can someone point me to the place where such a change would fit? I've
looked a bit at pkg/kubectl/cmd/create*.go files, searching for the part
where I could make a tweak; still new to the k8s code base. Any help is
welcome 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/14963#issuecomment-263087459>,
or mute the thread

**Comment by thockin** [comment]
Be aware that this makes it MORE likely to generate bad words...

**Comment by sakshamsharma** [comment]
@thockin Can you clarify what you mean by "bad words" here?
I'm submitting an early PR (there still are things which can be ironed out or changed). Perhaps this discussion can be taken to #37523

**Comment by thockin** [comment]
http://thedailywtf.com/articles/The-Automated-Curse-Generator

We just removed vowels from the random-letter set to reduce the chances of
curse words.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by bgrant0607** [comment]
Not doing this
