### ISSUE TITLE
kubelet starts on master and fails to ever run scheduler

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#14986]
Here is an example.

```
root@kubernetes-master:/etc/kubernetes/manifests# cat /var/log/kubelet.log |grep scheduler

I1002 15:28:29.110981    3500 kubelet.go:1929] SyncLoop (ADD): "etcd-server-events-kubernetes-master_kube-system, etcd-server-kubernetes-master_kube-system, kube-apiserver-kubernetes-master_kube-system, kube-controller-manager-kubernetes-master_kube-system, kube-scheduler-kubernetes-master_kube-system"

I1002 15:28:29.121035    3500 manager.go:1670] Need to restart pod infra container for "kube-scheduler-kubernetes-master_kube-system" because it is not found

W1002 15:28:29.840931    3500 manager.go:1856] Failed to pull image "gcr.io/google_containers/kube-scheduler:66c0cb9c22199224da120ae412a5c49a" from pod "kube-scheduler-kubernetes-master_kube-system" and container "kube-scheduler": Tag 66c0cb9c22199224da120ae412a5c49a not found in repository gcr.io/google_containers/kube-scheduler

I1002 15:28:50.335369    3910 kubelet.go:1929] SyncLoop (ADD): "etcd-server-events-kubernetes-master_kube-system, etcd-server-kubernetes-master_kube-system, fluentd-cloud-logging-kubernetes-master_kube-system, kube-apiserver-kubernetes-master_kube-system, kube-controller-manager-kubernetes-master_kube-system, kube-scheduler-kubernetes-master_kube-system"
```

**Comment by ArtfulCoder** [comment]
@dchen1107

**Comment by ArtfulCoder** [comment]
root@kubernetes-master:/etc/kubernetes/manifests# docker ps -a |grep scheduler
4d1090558c26        gcr.io/google_containers/pause:0.8.0                                                "/pause"                 33 minutes ago      Exited (0) 33 minutes ago                         k8s_POD.7be6d81d_kube-scheduler-kubernetes-master_kube-system_47b8cfd522bf6d0f105ba2670c6d821e_c4413105

**Comment by ArtfulCoder** [comment]
Apparently, there isnt enough CPU for kube-scheduler

I1002 16:37:38.942109    9128 server.go:692] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-scheduler-kubernetes-master", UID:"47b8cfd522bf6d0f105ba2670c6d821e", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): reason: 'InsufficientFreeCPU' cannot start the pod due to insufficient free CPU.

**Comment by ArtfulCoder** [comment]
@bgrant0607 
@brendandburns
 
This PR that adds etcd-events pod caused the CPU usage to tip over 100% 
https://github.com/kubernetes/kubernetes/pull/14766

**Comment by ArtfulCoder** [comment]
We can no longer run kubernetes on a single-core master.
e2e is green because its probably using a dual-core machine for the master.

**Comment by ArtfulCoder** [comment]
root@kubernetes-master:/etc/kubernetes/manifests# grep cpu *
etcd-events.manifest:        "cpu": "200m"
etcd.manifest:        "cpu": "200m"
fluentd-gcp.yaml:        cpu: 100m
kube-apiserver.manifest:        "cpu": "200m"
kube-controller-manager.manifest:        "cpu": "200m"
kube-scheduler.manifest:        "cpu": "200m"

**Comment by ArtfulCoder** [comment]
We need to adjust cpu requirement in our component manifest files.

**Comment by ArtfulCoder** [comment]
Assigning to Brendan.
I would imagine that we would to reduce the cpu core requirement for etcd pods to be 100milli instead of 200 milli.

**Comment by ArtfulCoder** [comment]
I have created a PR.

**Comment by bprashanth** [comment]
hmm, I think reducing the cpu limits will just lead to more confusion like etcd stalling. we already impose restrictions on node size (eg single node single core clusters won't work because all the addons don't fit, g1-small nodes aren't allowed with large clusters because of heapster), perhaps impose master size restriction?

@kubernetes/goog-control-plane

**Comment by ArtfulCoder** [comment]
Addons should be treated as optional, not a requirement.

**Comment by bprashanth** [comment]
Then feature flag the new etcd?

**Comment by ArtfulCoder** [comment]
each etcd pod hopefully does lesser work, after the split.
What we want is that we give more cpu shares on a more souped up machine.
we would need to update the master-component manifest templates accordingly.

**Comment by ArtfulCoder** [comment]
Looping in @wojtek-t since it could impact scalability if we reduce cpu shares for etcd.

**Comment by bprashanth** [comment]
All I'm saying is set it to what we observe. Don't compromise. From the etcd testing I've done it does unpredictable things  when starved (it'll crash, come up, try to load a snapshot, crash again), so the user experience on a single node cluster may be horrible.

**Comment by ArtfulCoder** [comment]
@mikedanese suggested we use QoS (100 requested, 200 limit)
I think that should be acceptable, assuming QoS works for cpu

**Comment by wojtek-t** [comment]
@ArtfulCoder - thanks a lot for debugging and fixing this issue

Regarding the further discussion - I think it's a bit artificial - to run any bigger cluster, we need more than 1-core for the master machine anyway.
So I think that what we should do is:
- leave 100 requested, 200 limit for 1-core master
- introduce some logic that gives higher request/limit for any component when the master machine is bigger
I will take a look into it today.

**Comment by bgrant0607** [comment]
Can this be closed? Has an issue been filed to create an e2e test for the default cluster configuration?

**Comment by wojtek-t** [comment]
@bgrant0607 - I think that what we should do is to change the default configuration to be exactly the same as test configuration instead of adding a test to it
Since we are running all tests in "test configuration" - it is much better tested and thus it should be the default one.
