### ISSUE TITLE
pkg/util/wait Poll(), WaitFor(), etc can leak groutines

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#14995]
poll.WaitFor() is the common func among these all and it can return before draining the channel.   This leaves any goroutines spawned by the WaitFunc are leaked and stuck forever.

https://blog.golang.org/pipelines

**Comment by thockin** [comment]
@lavalamp @smarterclayton @ncdc

**Comment by ncdc** [comment]
@thockin are you going to work on a fix for this or would you like me to take a stab?

**Comment by thockin** [comment]
I was not going to take it in the immediate future - it seems like a simple but tedious fix to pass a done chan to any call-site that uses WaitFor(), and then watch for done.

**Comment by thockin** [comment]
in other words: go for it, and this should be a cherry pick to v1.1
