### ISSUE TITLE
Port forwarding should be through iptables

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#15]
As we've disabled docker managing IP tables we no longer get it setting up explicit port forwarding.  Instead we are falling back on user mode proxying that is built into docker to do this port forwarding.

We should either build our networking mode into Docker proper or have the `kubelet` set up and maintain the IPTables forwarding rules we need.

**Comment by hallucynogenyc** [comment]
@errordeveloper Your link is broken, correct link is https://github.com/zettio/weave/issues/260#issuecomment-65626372

**Comment by bgrant0607** [comment]
If would be great if someone could test whether this works now.

Remove the options here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/c2fa72d6ba3ea26e3bea9e9ee97234311ae587bb/cluster/saltbase/salt/docker/docker-defaults#L5

cc @rsokolowski

**Comment by thockin** [comment]
I played with this some today - enabling the --iptables flag in docker gives us a bunch of iptables rules, most of which we do not want.

Also coming up: https://github.com/docker/docker/pull/12165

**Comment by thockin** [comment]
I revisited this with recent docker and it APPEARS that we can re-enable docker's --iptables flag (or stop disabling it).  It needs more thorough testing to be 100% sure, but it looks pretty good.

**Comment by thockin** [comment]
Context: 

https://github.com/docker/docker/issues/8356
https://github.com/docker/docker/pull/6810

**Comment by ernestoalejo** [comment]
I am playing with this (removing `--iptables=false --ip-masq=false` from `/etc/default/docker`) in order to receive the real client IP in a `hostPort` pod container. By the moment it seems to work ok in GCE, with iptables proxy mode enabled.

There is something I should watch for while I test it?

**Comment by errordeveloper** [comment]
@thockin this is a very old issue, is it still meant to be open?
