### ISSUE TITLE
kubectl log --follow and kubectl exec unstable connections

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#15008]
Using Kubernetes on GKE, both `kubectl log --follow` and `kubectl exec` seem to be highly unstable in their connection.

That is to say, both commands, when running a long-running command, eventually simply "stop", and you are returned to your own shell.

It's not even some sort of "no response" timeout, as it happens regularly during typing in a bash shell opened with `kubectl exec <> -it -- bash`.

This highly unstable nature causes the commands to be unfit for use in long-running automated commands (for example, running an automated test-suite on a Kubernetes cluster using `kubectl exec`).

**Comment by cjcullen** [comment]
Same issue as #12179. Mind if we close this one?

**Comment by JeanMertz** [comment]
As sorry, I searched (both through Google and GH), but couldn't find anything related. Closing and subscribing there :+1:
