### ISSUE TITLE
wait.ErrWaitTimeout produces unfriendly log messages

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15000]
Rather than returning a literal we should return an error type with details: `return fmt.Errorf("%v: %v", ErrWaitTimeout, err)` and fix anyone who tests against `ErrWaitTimeout` for wait.IsTimeoutError(error)

**Comment by thockin** [comment]
@bprashanth @ncdc

**Comment by kargakis** [comment]
Agreed with this one, I have been working around that error in every place I stumble across it.

**Comment by kargakis** [comment]
Maybe /sig api-machinery

**Comment by medzin** [comment]
@thockin I can do this, but I have a few questions:
* if I understand correctly you want to add a custom timeout error type and util function to use in conditions
* can I do this in small PRs, or do you prefer a big one?
* this #10322 issue looks like related

**Comment by medzin** [comment]
Some example code:

```go
package wait

// Error represents a polling or listening error.
type Error interface {
	error
	Condition() bool // Is the error from a condition?
	Timeout() bool   // Is the error a timeout?
}

// other package
package other

if err, ok := err.(wait.Error); ok && err.Timeout() {
	// do stuff here
}

```

**Comment by thockin** [comment]
Honestly, some of the context was lost.  #10322 seems apropos.  Also https://dave.cheney.net/2014/12/24/inspecting-errors was an inspiration.

I am not sure what condition means in your interface, but maybe we don't even want a type?

The few places that return `ErrWaitTimeout` don't have much additional context to add (I guess they could add the timeout value, if they know it, but some don't).  One could argue that the places that are installing timeout-able operations should be catching and detecting the timeout and decorating the error themselves with more usage-specific info.

So `the condition timed out` could become `failed to frobnicate: wizzer did not activate: timed out (30s)`

Error reporting hard, and we're not exactly consistent about it.  I do think we overuse `fmt.Errorf` and we don't giftwrap enough.

I'd love to see some thought put into how to do it better and someone to start chipping away at it.

**Comment by nikhita** [comment]
> I think that due to the size of the Kubernetes codebase, it will not be possible to achieve very noticeable effects in one iteration of changes.

That makes sense. It's also easier to review if PRs are smaller. :)

@medzin if you (or anyone else) is still interested in working on this, small and incremental PRs are fine. :+1:

**Comment by josiahbjorgaard** [comment]
@medzin @nikhita I'd like to work on this. Has there been any progress?

**Comment by thockin** [comment]
Unfortunately this is now part of the public API of k8s.io/apimachinery/pkg/util/wait/
