### ISSUE TITLE
Master creates kubernetes service with port 6443 if no secure port is provided

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#15017]
Currently master creates kubernetes service with port 6443 if no secure port is provided. This means that if don't use secure connection we will not be able to communicate with apiserver from a pod using ```kubernetes``` service.

I'd like to fix this as in a single node docker based cluster there is no SSL and this kind of communication should work. The same applies for a basic multinode setup. 

I have a fix that I'll send on Monday.

**Comment by liggitt** [comment]
why wouldn't there be SSL on a single node cluster? the `kubernetes` service should use TLS

**Comment by fgrzadkowski** [comment]
I'm just saying that there doesn't have to be SSL. I'm working now on simplifying setup and running everything in docker containers. Pushing certificates would make it more complex so I want to avoid it initially.

I think there is no reason why we should require using SSL.

**Comment by liggitt** [comment]
@roberthbailey thoughts on this? I think that TLS with a self signed cert is strictly better than non TLS, and I don't really want split components talking over non-TLS connections if we can possibly help it (even for non production envs)

**Comment by liggitt** [comment]
Allowing insecure access has led to things like https://github.com/kubernetes/kubernetes/issues/13598, which overlooked one method of accessing the API such that is isn't possible to provide secured credentials, and required insecure access be enabled. Requiring TLS flushes those cases out.

**Comment by roberthbailey** [comment]
xref #15016

**Comment by roberthbailey** [comment]
What we did initially for other platforms (like GCE) was to keep SSL and just set the client to ignore cert checks. Why not do that here until we have a way to do proper cert validation? That seems better than reverting to http.

**Comment by fgrzadkowski** [comment]
I think that for a developer/getting started we should a super simple setup. This is not only about client side configuration, but also about server side. Adding SSL is not that easy (especially if you want to do it right).

Regarding non-secure port I think that this is and orthogonal problem. Wouldn't it be more explicit if we either listen only on insecure port or only on secured port? I think that the confusion and source of problems is not the fact that we have mechanism to listen on insecure port, but rather the fact that we have insecure port in secure cluster.

**Comment by liggitt** [comment]
Things like https://github.com/kubernetes/kubernetes/issues/13598 are the only reason we even have an insecure port, in my opinion.

**Comment by lavalamp** [comment]
I agree-- leave SSL on. Exercise same code paths in dev and prod.

**Comment by fgrzadkowski** [comment]
Closing in favor of #15368
