### ISSUE TITLE
Figure out how to pass-through version in multi-phase Jenkins jobs

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#15011]
It would be great if we could check client & version skew in multi-phase Jenkins jobs, but right now we can't because we might see version drift in `latest.txt` in between phases.  There may be a way to pass-through versions, and we should investigate it.

**Comment by ihmccreery** [comment]
Related to #15003.

**Comment by justinsb** [comment]
I do wonder if we could maybe use k8s itself to run our tests; perhaps the new jobs framework in particular.

The biggest barrier to doing this (I believe) is that our build scripts don't run in Docker because they use Docker...

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by spiffxp** [comment]
/close

we no longer use jenkins for upgrade tests
