### ISSUE TITLE
Client library assumes that server is using SSL

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#15016]
In some simpler setups apiserver might not use SSL and still pods should be able to contact it. Currently client library assumes we have SSL. See ```InClusterConfig()``` https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/helper.go#L256)

I already have a fix locally and will send on Monday.

**Comment by fgrzadkowski** [comment]
For more background - I'd like to fix this as for the single node docker based cluster we should allow pod<->apiserver communication and it should not use SSL.

**Comment by liggitt** [comment]
credentials should never be sent over a non-ssl connection...

**Comment by fgrzadkowski** [comment]
@liggitt What credentials do you mean? If we have a simple cluster which is not using SSL than we don't need to send any credentials, right?

Just to make it clear - I'm not saying this is a proper production setup. I'm just trying to simplify simple setup for new users and those who want to port it to other OSes

**Comment by liggitt** [comment]
cc @roberthbailey

**Comment by roberthbailey** [comment]
If you want to hit the apiserver without credentials, then you can already use the insecure port (set to localhost:8080 by default). It uses http and doesn't require any client credentials to be sent. I don't think it makes sense to make it an option to have the secure port ever be non-SSL because that would, by definition, make it insecure. 

But it sounds like what you are trying to do is re-jigger the client side of the connection so that it can connect to the insecure port (non-SSL and no client credentials) in cases where the insecure port is remotely accessible. I'm curious to see what changes to the code this requires (how do nodes know that they are running in an "insecure" cluster?). 

/cc @mikedanese

**Comment by fgrzadkowski** [comment]
@roberthbailey Yes, I'm not trying to say that secure port is not using SSL. I'm trying to connect to insecure port. The change in the client library assumes that if we have ```/var/run/secrets/kubernetes.io/serviceaccount``` then we run in secured cluster, otherwise try using insecure protocols.

**Comment by liggitt** [comment]
is there even an insecure service set up any more? I really hope not

**Comment by fgrzadkowski** [comment]
@liggitt What do you mean? Are you saying that each service (including user provided) should use SSL?

**Comment by mikedanese** [comment]
@liggitt no there is not. @fgrzadkowski the InClusterConfig was designed to use the kubernetes service setup in the default namespace which AFAIK will only ever be setup to point to the apiserver's https port. Are you planning on creating an http kubernetes service when the cluster is setup in insecure mode (i.e. insecure-bind-address is a public interface)?

**Comment by liggitt** [comment]
@fgrzadkowski no, I'm referring only to the kubernetes service

**Comment by mikedanese** [comment]
I guess the alternative to that approach would be to allow InClusterConfig to accept some arbitrary configuration but at that point, why don't you just create a client.Config yourself?

**Comment by fgrzadkowski** [comment]
@liggitt @mikedanese All I'm saying is that if we have a simple setup which does not have SSL configured (for whatever reason - development, other security mechanism, performance measurements) cluster should still work. Currently it doesn't. Obviously by default we should use SSL, but I don't  see why this should be a hard requirement.

I think it'll be easier if we discuss over concrete changes, so please wait for the PR. I'll cc both of you :)

**Comment by mikedanese** [comment]
@fgrzadkowski Sounds good.

**Comment by fgrzadkowski** [comment]
Closing in favor of #15368
