### ISSUE TITLE
Create cookbooks / playbooks / cheatsheets for common use cases and scenarios

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15032]
Deployment, troubleshooting, etc.

**Comment by bgrant0607** [comment]
cc @mansoorj

**Comment by bgrant0607** [comment]
And more analogies/translations from other systems, such as GCE and EC2.

| EC2 | GCE | K8s |
| Instance | Instance | Pod |
| Autoscaling group | Managed instance group | Replication controller |
| Elastic load balancer | Forwarding rule | Service |

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers

**Comment by chenopis** [comment]
IMHO, since all the docs now live in the k8s.io repo, any docs issue pre-2017 should be closed.
