### ISSUE TITLE
We should be running flakey & slow tests in GKE as well as GCE

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#15030]
@ixdy, are you willing to take on creating jobs that run flakey, slow, and maybe other (parallel?) tests in GKE that we currently only run in GCE?

**Comment by ihmccreery** [comment]
E.g. "MaxPods Validates MaxPods limit number of pods that are allowed to run." is failing in GKE upgrade tests, but it's not running on GKE anywhere else because it's a slow test, so I can't tell if it's a GKE issue or an upgrade issue.

**Comment by ihmccreery** [comment]
Related to #13062.

**Comment by fejta** [comment]
Send a PR that adds these jobs to https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e.yaml and they will start running automatically!

@alex-mohr to find an owner for this.

**Comment by ihmccreery** [comment]
This has been fixed for a while; sorry it never got closed.
