### ISSUE TITLE
Ensure there is an easy way to provide container input (and to get output)

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1503]
Simple data-in/data-out restart-until-success (or run-once/restart-never) pods need an easy way to receive input data. Such pods could be used for configuration generation functions, workflow steps, cron actions, etc.

There also needs to be an easy way to retrieve at least simple/small outputs, as discussed in #139, so I'm mostly not going to discuss that here.

Options:

1. Surface [Docker attach to stdin and stdout](https://docs.docker.com/reference/api/docker_remote_api_v1.13/#attach-to-a-container)

2. Another possibility would be to support an input field in the container spec, which would be fed into stdin. That approach would preclude reuse of a pod template for multiple inputs, though. Using a command-line argument would have that same problem. A URL parameter on the creation POST could potentially work.

3. Another approach, appropriate for larger inputs, could be image volumes (#831), though the input image would need to be built and pushed prior to launching the consuming pod.

**Comment by proppy** [comment]
4. allow the pod create API call to take an arbitrary data payload?
(I could see that being useful for `docker run` too, I wonder if that open the door to all sort of crazy issues and abuses).

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by bgrant0607** [comment]
we support `kubectl run -t -i` now
