### ISSUE TITLE
Document how to configure API server to use secure connection to etcd

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#15056]
We seem to get a lot of questions about this and it's not clear to me whether it works at all.

http://stackoverflow.com/questions/32912699/unable-to-setup-kubernetes-against-tls-secured-etcd
https://groups.google.com/d/topic/google-containers/vu2QSc_RXIw/discussion
https://groups.google.com/forum/#!topic/google-containers/bTfEcRQ3N28/discussion

etc.

**Comment by glerchundi** [comment]
@davidopp +1.

I already solved my problem, it's related to the value of the timeout. `go-etcd` is deserialized in nanoseconds. For a value of 1s, 1000000000 must be written.

But It is absolutely necessary to have better documentation about this so that people do not fall back into this problem.

**Comment by lavalamp** [comment]
I can't find it now, but long ago I filed an issue with golang about the way time.Duration marshals in json by default.

**Comment by AdoHe** [comment]
@glerchundi from your solution, I can see you use a `json` file to configure the etcd, but from the latest kubernetes release, it seems that there is no such configuration option. So how to use secure connection to etcd?

**Comment by antoineco** [comment]
This doesn't seem to be valid anymore since this particular commit https://github.com/kubernetes/kubernetes/commit/413d8d18fe6a454b728b911c8adab7163ab90250. Is it even still possible to communicate with etcd over TLS?

**Comment by AdoHe** [comment]
@antoineco I have opened a PR #21535 to do this, and it is on the way.

**Comment by davidopp** [comment]
cc/ @xiang90 @hongchaodeng

**Comment by pires** [comment]
#21535 has been merged and seems to close this issue. See https://github.com/AdoHe/kubernetes/blob/7228b9b9878feffb001614d91a974463a6dbb362/docs/admin/kube-apiserver.md
