### ISSUE TITLE
EBS volumes: volume mounted instead of partition

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#15050]
Environment: CoreOS 815.0.0, k8s 1.1.0 (7d6c8b6)

A pod definition including a volume of type awsElasticBlockStore yields errors on the instance the pod starts on:

```
blkfront: xvdf: barrier or flush: disabled; persistent grants: disabled; indirect descriptors: enabled;
EXT4-fs (xvdf): VFS: Can't find ext4 filesystem
EXT4-fs (xvdf): mounted filesystem with ordered data mode. Opts: (null)
EXT4-fs (xvdf): re-mounted. Opts: (null)
```

It looks like the _kubelet_ tries to mount a volume (/dev/xvdf) and not a partition. Although this eventually succeeds, I'm not sure if this is the expected design.

```
kubelet[22950]: I1003 14:55:47.635600   22950 aws.go:1030] Waiting for volume state: actual=attaching, desired=attached
kubelet[22950]: E1003 14:55:48.764833   22950 mount_linux.go:103] Mount failed: exit status 32
kubelet[22950]: Mounting arguments: /dev/xvdf /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/eu-west-1a/vol-4429a18b ext4 [defaults]
kubelet[22950]: Output: mount: wrong fs type, bad option, bad superblock on /dev/xvdf,
kubelet[22950]: missing codepage or helper program, or other error
kubelet[22950]: In some cases useful info is found in syslog - try
kubelet[22950]: dmesg | tail or so.
kubelet[22950]: I1003 14:56:46.264633   22950 manager.go:1615] Need to restart pod infra container for "artifactory_default" because it is not found
```

**Comment by justinsb** [comment]
I think this is actually the expected output from safe_format_and_mount.  If you want to use a partition, you can specify a partition on the volume (https://github.com/kubernetes/kubernetes/blob/6260759c5130f7f8f7e734c923a17638b79f9009/pkg/api/types.go#L496)

I don't think there's any particular requirement to specify a partition (?).  I agree the message is off-putting, but AFAICT that's the normal safe_format_and_mount message (and maybe we should fix that!)

As an aside, I'm currently tidying up the volume mount code for AWS so that it reuses the GCE infrastructure, so that might be a contributing cause of the slowness.

**Comment by antoineco** [comment]
Extra note, if you run `fdisk` on such a block device you get the following warning:

```
/dev/xvdf: device contains a valid 'ext4' signature; it is strongly recommended to wipe the device with wipefs(8) if this is unexpected, in order to avoid possible collisions

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x7033414d
```

As you just mentioned @justinsb, the workaround is to create the partition(s) manually and set the `partition` attribute of the volume to the actual partition number, which makes sense but doesn't sound so clear in the [current documentation page](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/volumes.md#awselasticblockstore).

**Comment by a-robinson** [comment]
@antoineco - does this justify its own issue, or is it covered by #15077?

**Comment by antoineco** [comment]
The two issues are different and do not happen in the same conditions.

In this case a raw disk is treated as if it already contained a partition.
In the mentioned issue a partitioned disk is not properly mounted.

**Comment by davidopp** [comment]
Moved to P1 to indicate 1.2 blocker, @justinsb please move this (and #21219) to P2 if you think it is not a blocker.

**Comment by thockin** [comment]
I'm not clear on what the actual problem is or what the proposed fix is - can someone catch me up?

**Comment by justinsb** [comment]
I'm pretty sure it is fixed, but we had a bug on AWS where we were trying to mount the whole volume instead of just the partition when a partition was specified for an EBS volume.  We just need to verify that it is indeed fixed.

How can I tag this to say "do not block the release, and do not block cutting the branch, but justin (or anyone else aws) should really just find the time to test this"?

**Comment by antoineco** [comment]
@thockin before a filesystem is created one should create a partition. Currently the filesystem is created directly on the device. First this is not a correct approach, second it contradicts the fact that a `volume` can mount a specific partition.

**Comment by justinsb** [comment]
@antoineco I don't think there's anything wrong with mounting the whole volume if you don't specify a partition - I don't think we're going to fix that (certainly not in 1.2).  What do you believe the problem there to be?

What I believe we have fixed is that originally when a user specified a partition to mount, we ignored it and tried mounting the volume instead.

**Comment by antoineco** [comment]
It is not completely invalid, but if you do so tools like `fdisk` will throw warnings like "Device does not contain a recognized partition table." (see my [previous comment](https://github.com/kubernetes/kubernetes/issues/15050#issuecomment-145536852))

**Comment by justinsb** [comment]
I'm going to downgrade this to P2 as I believe the mounting issue is fixed, just need to find time to validate.

@antoineco if you feel strongly about the lack of a partition table, can you open a new issue for that?  I think we do the same thing on GCE too though: I'll follow on AWS whatever we do on GCE.

**Comment by goltermann** [comment]
Moving out of v1.4 as this is a P2.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @justinsb @antoineco

**Comment by antoineco** [comment]
@dims definitely not a release blocker

**Comment by dims** [comment]
Thanks switched milestones @antoineco

**Comment by liggitt** [comment]
this has been moved through four releases... @justinsb, what is involved in validating this is fixed?

**Comment by justinsb** [comment]
Manual verification, or once GCE adds an e2e test for the equivalent bit of functionality we can adapt the test for AWS.

**Comment by antoineco** [comment]
@k8s-bot /kind bug

**Comment by antoineco** [comment]
@k8s-bot /priority important-longterm

**Comment by antoineco** [comment]
@k8s-merge-robot
/kind bug
/priority important-longterm
