### ISSUE TITLE
Make Kubemark easy to run outside GCE

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#15066]
Currently scrips depend on `cluster/gce/util.sh` to get various environmental variables set. It shouldn't be to hard to decouple it, but it requires some work.

cc @fgrzadkowski @timothysc @quinton-hoole

**Comment by gmarek** [comment]
I think @shyamjvs did this.

**Comment by cy-zheng** [comment]
Any solution with it? I found it so hard to run kubemark.
