### ISSUE TITLE
Calibrate Kubemark/Kubemark test results

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#15064]
We have performance testing infrastructure ready for use in GCE, all scripts are in `test/kubemark`, and the rest of the code is spread around `cluster` directory. Currently there's a performance problem, which causes kubemark to be a lot slower than ordinary cluster. We need to find a root cause for this if we want this tool to be useful.

cc @fgrzadkowski @wojtek-t @lavalamp @quinton-hoole @timothysc

**Comment by gmarek** [comment]
It seems that we do a lot more in etcd in Kubemark runs:
Part of etcd logs from 'normal' run:
```
2015/10/05 12:04:14 etcdserver: start to snapshot (applied: 10001, lastsnap: 0)
2015/10/05 12:04:14 etcdserver: compacted log at index 10001
2015/10/05 12:04:14 wal: segmented wal file /var/etcd/data/member/wal/0000000000000001-0000000000002712.wal is created
2015/10/05 12:04:14 etcdserver: saved snapshot at index 10001
2015/10/05 12:06:42 etcdserver: start to snapshot (applied: 20002, lastsnap: 10001)
2015/10/05 12:06:42 etcdserver: compacted log at index 20002
2015/10/05 12:06:42 wal: segmented wal file /var/etcd/data/member/wal/0000000000000002-0000000000004e23.wal is created
2015/10/05 12:06:42 etcdserver: saved snapshot at index 20002
```

Analogous part from Kubemark run:
```
2015/10/05 12:11:44 etcdserver: start to snapshot (applied: 10004, lastsnap: 0)
2015/10/05 12:11:44 etcdserver: compacted log at index 10004
2015/10/05 12:11:44 wal: segmented wal file /var/etcd/data/member/wal/0000000000000001-0000000000002715.wal is created
2015/10/05 12:11:44 etcdserver: saved snapshot at index 10004
2015/10/05 12:12:43 etcdserver: start to snapshot (applied: 20008, lastsnap: 10004)
2015/10/05 12:12:43 etcdserver: compacted log at index 20008
2015/10/05 12:12:43 wal: segmented wal file /var/etcd/data/member/wal/0000000000000002-0000000000004e29.wal is created
2015/10/05 12:12:43 etcdserver: saved snapshot at index 20008
```

Generating the  same work that was done on normal cluster in 2m30s took only 1m on Kubemark

**Comment by gmarek** [comment]
I found another difference: 
real runs:
```
00:40:05 Oct  5 00:40:05.866: INFO: Terminating RC density3000-0936c4af-6b33-11e5-a023-42010af01555 pods took: 10.012089482s
```
kubemark runs:
```
Oct  5 15:03:58.972: INFO: Terminating RC density3000-fa649c0e-6b5f-11e5-8230-7446a0bae05f pods took: 2m0.913464406s
```

It seems that something is not implemented yet...

**Comment by lavalamp** [comment]
are you running kubemark components with the same size (& occupancy!) VM as we run master components on?

**Comment by gmarek** [comment]
Yes, I am. I forgot to update this issue: #15079 fixes most of the problems. Kubemark becomes slightly too fast, but we can work with that.

**Comment by gmarek** [comment]
It's in. I also had to fix `start-kubemark.sh` script to work better with Jenkins (#15143). We're starting to gather data from Jenkins runs from now on.

**Comment by gmarek** [comment]
On a 100 HollowNode cluster we currently have following results:
```
01:23:18 Oct  7 01:23:18.401: INFO: perc50: 1.347382934s, perc90: 1.768415857s, perc99: 1.822130972s
```
and
```
01:26:21 Oct  7 01:26:21.837: INFO: Top latency metric: {Resource:pods Verb:LIST Latency:{Perc50:25.912ms Perc90:827.989ms Perc99:827.989ms}}
01:26:21 Oct  7 01:26:21.837: INFO: Top latency metric: {Resource:nodes Verb:PUT Latency:{Perc50:31.417ms Perc90:47.229ms Perc99:365.444ms}}
01:26:21 Oct  7 01:26:21.837: INFO: Top latency metric: {Resource:pods Verb:DELETE Latency:{Perc50:45.205ms Perc90:65.399ms Perc99:113.004ms}}
01:26:21 Oct  7 01:26:21.837: INFO: Top latency metric: {Resource:pods Verb:POST Latency:{Perc50:25.888ms Perc90:32.586ms Perc99:102.02ms}}
01:26:21 Oct  7 01:26:21.837: INFO: Top latency metric: {Resource:pods Verb:PUT Latency:{Perc50:30.647ms Perc90:35.582ms Perc99:72.453ms}}
```
While on 'real' cluster we have:
```
23:58:07 Oct  6 23:58:07.310: INFO: perc50: 1.402453193s, perc90: 1.747962644s, perc99: 3.75162346s
```
and
```
00:01:15 Oct  7 00:01:15.714: INFO: Top latency metric: {Resource:pods Verb:LIST Latency:{Perc50:728.908ms Perc90:1.84454s Perc99:2.832253s}}
00:01:15 Oct  7 00:01:15.714: INFO: Top latency metric: {Resource:pods Verb:DELETE Latency:{Perc50:13.856ms Perc90:40.838ms Perc99:174.388ms}}
00:01:15 Oct  7 00:01:15.714: INFO: Top latency metric: {Resource:endpoints Verb:LIST Latency:{Perc50:4.421ms Perc90:30.563ms Perc99:117.45ms}}
00:01:15 Oct  7 00:01:15.714: INFO: Top latency metric: {Resource:services Verb:LIST Latency:{Perc50:4.72ms Perc90:33.631ms Perc99:104.12ms}}
00:01:15 Oct  7 00:01:15.714: INFO: Top latency metric: {Resource:nodes Verb:LIST Latency:{Perc50:20.98ms Perc90:53.744ms Perc99:103.398ms}}
```

@wojtek-t observed is that long Lists are generally reported by Heapster, which isn't running in Kubemark setup. Except that results are pretty similar with Kubemark being slightly faster.

**Comment by gmarek** [comment]
I'll need to run profiler on Kubemark and real masters and see if I can notice any difference. I have a couple of docs to write in this week, so I'll get to it in the next one.

Note that this results are without 'Proxy', as #14639 is not merged yet.

**Comment by quinton-hoole** [comment]
This is awesome.  I'd like to run a 1,000 HollowNode test.  Do you want to do it, or should I?

**Comment by quinton-hoole** [comment]
@gmarek ^^

**Comment by gmarek** [comment]
I already did it. Works fine, but latencies are to high. I'm currently running 1785 node test (I'll buy a beer to first person who'll guess why this number:). I'll post results tomorrow.

**Comment by gmarek** [comment]
I'll paste the results for other tests, but the most important lesson we learned from 1785 node kubemark experiment is that it ends with the following log in etcd on GCE n1-standard-16 master:
```
fatal error: runtime: out of memory
```

I.e. we don't scale to much more than 1000 nodes (or I need to learn how to tell docker that this particular container needs a lot of memory - if Docker sets some constraints by default)

**Comment by wojtek-t** [comment]
@gmarek - your test was run with a single etcd
after my recent changes we have a separate etcd for storing events
we can try running in a configuration with 2 etcd instance and if that doesn't help, we can move something to a separate machine (e.g. the second etcd) or even run every component on a different machine

if that would be still to much for the main etcd - we may consider spinning up yet another etcd for some other resources (e.g. pods) - this should be trivial one - it's just a matter of starting it and setting a flag in apiserver correctly

**Comment by gmarek** [comment]
Yes, I can do that, but currently my cluster is hanging there to let heapster guys play with it.

**Comment by wojtek-t** [comment]
@gmarek sure - it was just suggestion how we can work around it

**Comment by gmarek** [comment]
Some data points from 1000 node run on 16-core master.
Starting 30000 pods takes 1h36m on Kubemark and Scheduler it noticeably slows down in process, for first 15k Scheduler had a throughput of roughly 8-10 pods/sec, from 15k-23k it was 5-6 pods/sec, for 23k--30k it was 3-4 pods/sec. IIUC current scheduling complexity is O(#pods * log(#nodes) + max_node_occupancy * #nodes) and is sequential. It looks quite good to me, so I think the only way to go further is to make parallel scheduling work.

Sadly this 1000 node run also failed eventually:
```
Expected error:
      <*errors.StatusError | 0xc255579800>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {SelfLink: "", ResourceVersion: ""},
              Status: "Failure",
              Message: "the object provided is unrecognized (must be of type Pod): empty input",
              Reason: "BadRequest",
              Details: nil,
              Code: 400,
          },
      }
      the object provided is unrecognized (must be of type Pod): empty input
  not to have occurred
```

But managed to produce e2e startup latency data:
```
Oct  8 13:44:03.210: INFO: perc50: 1.954761443s, perc90: 3.656654957s, perc99: 12.308629437s
```

**Comment by gmarek** [comment]
Results for 500 Node cluster on Kubemark are:
```
Oct  9 12:57:08.413: INFO: perc50: 1.530124643s, perc90: 1.930433388s, perc99: 4.053272278s
```
and
```
Oct  9 13:11:48.794: INFO: Top latency metric: {Resource:pods Verb:LIST Latency:{Perc50:279.877ms Perc90:882.027ms Perc99:2.130864s}}
Oct  9 13:11:48.794: INFO: Top latency metric: {Resource:nodes Verb:LIST Latency:{Perc50:53.439ms Perc90:67.997ms Perc99:172.923ms}}
Oct  9 13:11:48.794: INFO: Top latency metric: {Resource:pods Verb:DELETE Latency:{Perc50:46.522ms Perc90:69.987ms Perc99:128.072ms}}
Oct  9 13:11:48.794: INFO: Top latency metric: {Resource:nodes Verb:PUT Latency:{Perc50:32.12ms Perc90:43.727ms Perc99:88.657ms}}
Oct  9 13:11:48.794: INFO: Top latency metric: {Resource:pods Verb:PUT Latency:{Perc50:31.499ms Perc90:42.066ms Perc99:67.367ms}}
```

**Comment by wojtek-t** [comment]
I think that our priority now should be to run all addons that are running on real clusters in Kubemark. They (especially heapster) may affect the metrics.

**Comment by wojtek-t** [comment]
Also, I've just realized that we are still not running KubeProxy in the setup - this may have significant consequences on the performance. We should submit #14639 asap.

**Comment by gmarek** [comment]
750 Node cluster results:
```
Oct  9 16:53:44.730: INFO: perc50: 1.633524489s, perc90: 2.026667673s, perc99: 2.750469171s
```
and
```
Oct  9 17:15:41.011: INFO: WARNING Top latency metric: {Resource:pods Verb:LIST Latency:{Perc50:2.356232s Perc90:3.167201s Perc99:5.221256s}}
Oct  9 17:15:41.011: INFO: Top latency metric: {Resource:nodes Verb:LIST Latency:{Perc50:101.083ms Perc90:198.534ms Perc99:330.809ms}}
Oct  9 17:15:41.011: INFO: Top latency metric: {Resource:pods Verb:DELETE Latency:{Perc50:53.177ms Perc90:81.121ms Perc99:274.616ms}}
Oct  9 17:15:41.011: INFO: Top latency metric: {Resource:nodes Verb:PUT Latency:{Perc50:31.935ms Perc90:91.065ms Perc99:238.219ms}}
Oct  9 17:15:41.011: INFO: Top latency metric: {Resource:pods Verb:POST Latency:{Perc50:21.623ms Perc90:61.878ms Perc99:195.441ms}}
```

**Comment by gmarek** [comment]
We increased the cluster size and load by 50% but metrics increased 2x.

cc @wojtek-t

**Comment by gmarek** [comment]
I managed to start Kubemark on 1000 Node cluster with a separate machine for Event etcd. It still pipes whole traffic through the master, but it lowers memory consumption on it.

**Comment by wojtek-t** [comment]
>
We increased the cluster size and load by 50% but metrics increased 2x.

Did you run it more than once (both of setups)?

**Comment by gmarek** [comment]
Not yet - it takes too long. I'll run some proper testing when HollowProxy gets merged.

**Comment by gmarek** [comment]
Data points from 1000 Node Kubemark run with two etcd machines:

Running Pods | API server memory usage | master machine etcd | event machine etcd
--------------------|------------------------------------|------------------------------|----------------------------
12.5k | 2.2GB | 1.3GB | 1.54GB
15k | 2.7GB | 1.72GB | 1.65GB
18.5k | 2.9GB | 1.84GB | 2.27GB
21k | 3.5GB | 1.77GB | 2.5GB
23.5k | 3.26GB | 1.7GB | 2.83GB
26.5 | 4.1GB | 1.93GB | 3.06GB
28k | 4.46GB | 2.04GB | 2.9GB
29.5k | 4.96GB | 2.08GB | 2.18GB

What surprised me was how much state API server accumulates.
cc @wojtek-t @timothysc @quinton-hoole @davidopp @lavalamp

**Comment by smarterclayton** [comment]
Have we grabbed a memory profile of the API server space and object allocations?

**Comment by smarterclayton** [comment]
~100K bytes memory per pod sounds off by an order of magnitude - even if you assume we have 5-10 copies of that pod in flight due to conversion at any one time (one in the etcd cache, one etcd watch cache, two or three at any time responding to list / watch and at various points in conversion)

**Comment by gmarek** [comment]
Profiling master on big clusters is still on my TODO list, but it gets continuously kicked out by more important stuff...

**Comment by timothysc** [comment]
@gmarek how many api-servers?

**Comment by gmarek** [comment]
One machine with API server, scheduler, controller-manager and 'main' etcd. Plus one machine for event etcd. 

Have in mind that it's a very "optimistic" setup - there're still no Proxies on Nodes, as #14639 is still not merged. Plus we don't have any real kubelets so we're not running any addons.

**Comment by gmarek** [comment]
Memory profile of the API server around 18k running Pods.

[kubemark.pdf](https://github.com/kubernetes/kubernetes/files/12488/kubemark.pdf)

**Comment by timothysc** [comment]
@gmarek I'd be very interested to see a profile with all of events disabled, just as a comparison to determine if the natural extension of offloading events into their own service makes sense.

**Comment by smarterclayton** [comment]
Surprised to still see so much reflection.  We may need to transform the
conversion function into an interface cast (make sure each method can also
be invoked with (interface{}, interface{}, scope)).  The deep copy New is
also somewhat surprising.

**Comment by smarterclayton** [comment]
What about the controller manager?  That'll show whether we're holding
duplicate copies in our client caches.

**Comment by gmarek** [comment]
Controller manager was using reasonable amounts of memory, so I wasn't paying close attention to it. (I'm also not sure if it exposes debug handlers, but even if it doesn't I can fix this easily enough).

I created an issue to track requested experiments: #15551. I'll run them in my free-ish cycles.

**Comment by smarterclayton** [comment]
Ok that's good that our big hitters in the apiserver are reflection right now.  That's manageable.

**Comment by gmarek** [comment]
Results are pretty close now on everything except listing pods. I'll do a braindump here for the posterity, and for the time I'll have some time to work on it:
- in Kubemark runs we're seeing less `list pods` calls than in the real cluster (90th and 99th percentiles are always equal on Kubemark, and they are never equal on real clusters)
- on real clusters we're seeing list pods from:
  - GC controller (quite regularly)
  - kubelets relist their pods from time to time

**Comment by gmarek** [comment]
I run a 500 Node cluster on Flannel and results of this run and kubemark-500 runs are similar, except the time of ListPods, which can be attributed to the lack of add-on in kubemark setup.

**Comment by xiang90** [comment]
@gmarek @wojtek-t @hongchaodeng 

We (k8s scale team Coreos) ran the 1000 nodes and 30pods/node tests. We got similar results.

Here is a graph of creating rate vs # of created pods.

<img src=https://storage.googleapis.com/kubemark/plot/density-running-rate.svg>

We are investigating the slowness. We already made some improvement. Will report back when we get more details.

**Comment by xiang90** [comment]
@gmarek 

> IIUC current scheduling complexity is O(#pods * log(#nodes) + max_node_occupancy * #nodes) and is sequential.

Based on our current observation (we might be wrong), the scheduling is actually very fast. Here is a plot about creating rate.

<img src=https://storage.googleapis.com/kubemark/plot/density-creating-rate.svg>

**Comment by davidopp** [comment]
I assume "Rate" (y-axis) is pods/sec, and the x-axis is essentially "time" but measured in terms of how many pods have {started running, been schedule} ?

**Comment by xiang90** [comment]
@davidopp Basically, yes. But the graph shows the relationship between rate and # of pods (rather than time).

Here is time graph

<img src=https://storage.googleapis.com/kubemark/plot/1000nodes.svg>

**Comment by gmarek** [comment]
@xiang90 IIUC graphs you pasted, first one is a better proxy for scheduler performance than a second one. By 'create' we mean not scheduled, but 'created by the ReplicationController', i.e. it's more or less an API server write throughput.

Also there's a script to grab profiles from various components, which can help with finding bottlenecks `hack/grab-profiles.sh`

**Comment by xiang90** [comment]
> By 'create' we mean not scheduled, but 'created by the ReplicationController', i.e. it's more or less an API server write throughput.

Good to know. We will try to get the overall scheduling throughput. We were thinking they are the same thing since the scheduling e2e latency is around the same value. :( 

I think there are three main checkpoints: submit by replication controller, scheduled by scheduler, started kubelet. We are tying to find which part contributes to most of the latency.

**Comment by xiang90** [comment]
@gmarek Do you have any suggestions for us to look at? Or anything you want us to explore more?

**Comment by gmarek** [comment]
My best guess would be the scheduler. The 'problem' with this test is that we measure scheduling latency in serial requests (we create single pod and wait for it to be running before creating new one). I think it'd be useful to look what happens when scheduler is scheduling multiple pods in the same time (as it does in the first 'saturation' part of this test). Probably grab some CPU profiles and lock contention during the peak.

@wojtek-t may have some other ideas.

**Comment by xiang90** [comment]
@gmarek I gave the output a closer look. 

https://github.com/kubernetes/kubernetes/blob/6b358e43dd56856536b25d06d5d7f112aaf4dd08/test/e2e/util.go#L1554

So pending means scheduled to a node (since the spec has a node name), but waiting for running.
And waiting means waiting for scheduling (since the spec does not have a node name yet).

Am I correct?

**Comment by davidopp** [comment]
> So pending means scheduled to a node (since the spec has a node name), but waiting for running.
And waiting means waiting for scheduling (since the spec does not have a node name yet).

Yes, that's what those terms mean in that code. I think that's really confusing; we should have a separate phase that means "waiting to be scheduled" and "waiting to be started" but we don't.

**Comment by wojtek-t** [comment]
>
So pending means scheduled to a node (since the spec has a node name), but waiting for running.
And waiting means waiting for scheduling (since the spec does not have a node name yet).

Correct.

>
@wojtek-t may have some other ideas.

We need to look into scheduler. If you look into logs from you can see that:
- all pods from RC are created relatively quickly
- then scheduler is a blocker
- once the pods is scheduler, it relatively quickly goes into running state (the number of pending pods is low all the time).

You may want to look into https://github.com/kubernetes/kubernetes/pull/17838 - I'm exposing more visibly some scheduler metrics there - this should give us better understanding what we should improve in scheduler (or at least is a first step towards it).

**Comment by xiang90** [comment]
@gmarek @wojtek-t @davidopp 

We (@hongchaodeng and I) investigate into it more yesterday. 

First there are a few rate limiting issues. After fixing them, the overall rate is improved from 15 pods/second to 60 pods/second for small clusters (100 nodes and 30 podes/nodes).

Second we measure the schedule algo latency. For small nodes, it is around 5-7ms. As the number of nodes getting larger, the latency can go up to 70ms-150ms. That limits the overall rates. We are going to reproduce the slowdown with micro-benchmark. (Or do you have other opinion?)

Third, for large cluster, the api server introduces additional latency spikes due to GC. But that does not affect the average latency a lot. If we switch to go 1.5, it should be resolved.

**Comment by wojtek-t** [comment]
>
First there are a few rate limiting issues. After fixing them, the overall rate is improved from 15 pods/second to 60 pods/second for small clusters (100 nodes and 30 podes/nodes).

Did you look at the latencies of apicalls after those changes? Those are our main metrics and we can't make then worse

>
Second we measure the schedule algo latency. For small nodes, it is around 5-7ms. As the number of nodes getting larger, the latency can go up to 70ms-150ms. That limits the overall rates. We are going to reproduce the slowdown with micro-benchmark. (Or do you have other opinion?)

Microbenchmark would be super helpful - but we need something realistic.
You can take a look into https://github.com/kubernetes/kubernetes/pull/17415 and comments there/

>
Third, for large cluster, the api server introduces additional latency spikes due to GC. But that does not affect the average latency a lot. If we switch to go 1.5, it should be resolved.

Yeah - we should prioritize it. There was already a lot of work done for it, so we should finish it.

**Comment by xiang90** [comment]
> Did you look at the latencies of apicalls after those changes? Those are our main metrics and we can't make then worse

There is no significant change. I can double check though.
