### ISSUE TITLE
Watch requests from heapster are too short and LIST last too long

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#15078]
When running tests I've seen that watch requests for pods coming from heapster are ending quite fast (i.e. most of them are significantly shorter than 1 minute - I would expect them to last 5+ minutes)

```
I1005 14:07:55.671089       5 handlers.go:130] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%21%3D&resourceVersion=768: (3m32.184678181s) 0 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.6:42100]
I1005 14:09:31.396182       5 handlers.go:130] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%21%3D&resourceVersion=4343: (1m34.758179069s) 0 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.6:43669]
I1005 14:10:13.390656       5 handlers.go:130] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%21%3D&resourceVersion=11994: (24.697363382s) 0 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.6:57245]
I1005 14:11:25.059787       5 handlers.go:130] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%21%3D&resourceVersion=15031: (44.015278283s) 0 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.6:36609]
I1005 14:12:35.725318       5 handlers.go:130] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%21%3D&resourceVersion=19762: (18.96559567s) 0 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.6:50178]
I1005 14:14:48.173726       5 handlers.go:130] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%21%3D&resourceVersion=27389: (15.221716234s) 0 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.6:60321]
```

 This results in too frequent unnecessary relists and higher load an apiserver/etcd.

Moreover, the "LIST pods" coming from heapster are much longer:
- all steps are longer (listing from etcd, processing in apiserver, sending to the client)
- it is NOT that they are processing more data

@kubernetes/sig-scalability @kubernetes/goog-csi @lavalamp

**Comment by wojtek-t** [comment]
To give an example for the second problem:

    I1005 14:47:14.674611       8 handlers.go:130] GET /api/v1/pods?fieldSelector=spec.nodeName%21%3D: (1.908231415s) 200 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.13:33263]
    I1005 14:48:39.520395       8 handlers.go:130] GET /api/v1/pods?fieldSelector=spec.nodeName%21%3D: (2.058450085s) 200 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.13:35838]
    I1005 14:49:50.336120       8 handlers.go:130] GET /api/v1/pods: (1.204393579s) 200 [[kube-controller-manager/v1.2.0 (linux/amd64) kubernetes/369c7be] 127.0.0.1:48219]
    I1005 14:49:50.376844       8 handlers.go:130] GET /api/v1/pods: (1.245190288s) 200 [[kube-controller-manager/v1.2.0 (linux/amd64) kubernetes/369c7be] 127.0.0.1:48220]
    I1005 14:49:50.403924       8 handlers.go:130] GET /api/v1/pods: (1.274297448s) 200 [[kube-controller-manager/v1.2.0 (linux/amd64) kubernetes/369c7be] 127.0.0.1:48217]

In all above requests there were 3000-3100 pods in the system (so the requests from heapster are almost 2x slower...)

**Comment by timothysc** [comment]
yeesh...

**Comment by wojtek-t** [comment]
@timothysc - are you also using heapster (and observe the same)
I looked through logs and didn't see any other suspiciously short watch requests...

**Comment by timothysc** [comment]
We have disabled heapster in our environment.

**Comment by lavalamp** [comment]
Perhaps heapster is requesting many relists?

Can you look at the heapster log? What does it think it is doing?

**Comment by lavalamp** [comment]
@vishh

**Comment by wojtek-t** [comment]
This is obsolete now.
