### ISSUE TITLE
Leverage docker labels to construct container statuses without consulting pod spec 

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#15089]
Kubelet reconciles the difference between the pod status and the desired pod specs. When generating status for a pod (`GetPodStatus`), kubelet relies on several pieces of information from the apiserver:
 - PodSpec:
     * container name
     * termination message path
 - PodStatus:
     * container restart count

(*edit: this list may be incomplete*)

We can eliminate this dependency by writing the information as docker labels onto the container. The benefits of doing so include 1) kubelet can populate and maintain a container/pod status cache, representing what's running on the node, regardless of whether it has access to the pod spec yet or not; 2) this should simplify a lot of logic in pod spec.
(Note that `rkt` doesn't have this dependency as it writes relevant bits in the systemd unit file)  

Alternatively, kubelet can store a checkpoint of pods assigned to itself, and load the checkpoint when kubelet restarts. We may need to do this eventually, but in the meantime, docker labels seem like a good idea.

The original docker label issue: #3764

@kubernetes/goog-node, WDYT?

**Comment by dchen1107** [comment]
cc/ @taotaotheripper 

Lantao, I am assigning this to you.

**Comment by dchen1107** [comment]
cc/ @yifan-gu on RKT support side.

**Comment by yifan-gu** [comment]
sgtm. FWIW, appc has similar concept called [annotations]https://github.com/appc/spec/blob/master/spec/pods.md Once we have apis to read them from rkt, we don't have to store everything in service files.

**Comment by Random-Liu** [comment]
I just put restart count into docker label last week in #15965.
Next step, I'll try to move pod name and namespace into docker label, and use label filter to simplify GetPodStatus().
Just report my progress here, :)

**Comment by vishh** [comment]
@Random-Liu: Thanks for working on this! Looking forward to those patches.

**Comment by Random-Liu** [comment]
@vishh Thank you, I'll keep working! :)

**Comment by Random-Liu** [comment]
I put pod full name into docker label and add label filter in GetPodStatus() in #16414.
Again, just update my progress, :)

**Comment by Random-Liu** [comment]
docker/docker#15496

**Comment by Random-Liu** [comment]
Progress Update:
Current now, we can only add labels to newly created containers, but for containers started already, we can do nothing. So we can't do filter list or naming cleanup etc. which must ensure that all containers' label have been set properly.

At least till now, the best solution is to add labels on running containers, but docker doesn't support that yet. I submitted an issue in docker community docker/docker#17457. And there is also related discussion docker/docker#15496. Hope that docker will add this feature soon.

Anyhow, for the next step, I'll keep on moving all the other related things into docker label. :)

**Comment by Random-Liu** [comment]
To figure out whether docker list with label filter could improve the efficiency, I did a small experiment to test.

**Benchmark**
Call client.ListContainers() of go-dockerclient for 100 Times.
* Total Container Number: 6101
* Container Number (with label "test=1"): 100
* Container Number (with label "single=1": 1

**Result**
* ListContainers()
  * each call time: 260.82 (ms)
  * total cpu time: 6.17 (s)
  * total time: 26.08 (s)
  * [cpu profile](https://raw.githubusercontent.com/Random-Liu/docker_label_filter_benchmark/master/list_containers.gif)
* ListContainers() with filter "test=1"
  * each call time: 179.72 (ms)
  * total cpu time: 0.22 (s)
  * total time: 17.97 (s)
  * [cpu profile](https://raw.githubusercontent.com/Random-Liu/docker_label_filter_benchmark/master/filter_containers.gif)
* ListContainers() with filter "single=1"
  * each call time: 174.09 (ms)
  * total cpu time: 0.02 (s)
  * total time: 17.41 (s)
  * [cpu profile](https://raw.githubusercontent.com/Random-Liu/docker_label_filter_benchmark/master/single_container.gif)

**Related Code in Docker**
[api/server/router/local/local.go](https://github.com/docker/docker/tree/master/api/server/router/local/local.go)=>[api/server/router/local/container.go#getContainerJSON()](https://github.com/docker/docker/tree/master/api/server/router/local/container.go#L47) =>[daemon/list.go#Containers()](https://github.com/docker/docker/tree/master/daemon/list.go#L83)
Just list all the containers, then do filter.

**Conclusion**
* On the docker client side, the main overhead is JSON decoding now. Use filter can reduce some of the cost.
* At least till now, docker haven't done indexing for filtering, just list and filter.

**Comment by vishh** [comment]
> At least till now, docker haven't done indexing for filtering, just list and filter.

I guess this was what we were assuming is true with labels. Is there an issue filed against docker to improve label based queries?

**Comment by Random-Liu** [comment]
In the [original proposal of docker label](https://github.com/docker/docker/pull/9882), they proposed indexing and performance. I just check the code to make sure whether they have done that, haha

**Comment by yujuhong** [comment]
As originally proposed, I think we should write TerminationMessagePath as a docker label, so that we don't need to rely on the pod spec to examine a terminated container.

**Comment by Random-Liu** [comment]
OK. I'll do it. :)

**Comment by Random-Liu** [comment]
**Progress Update**
The issue docker/docker#15496 about mutable container label abstracted some attention these days, and "status/needs-attention" label has been added to it. Hope we'll have mutable container label soon, :)

**Comment by Random-Liu** [comment]
**Progress Update**
Docker has started working on mutable label [see here](https://github.com/rancher/rancher/issues/1399#issuecomment-167268874)
And the original issue docker/docker#15496 has been marked as `status/claimed`.

**Comment by yujuhong** [comment]
I believe we can close this one too. @Random-Liu, thanks for working on it!

**Comment by Random-Liu** [comment]
@yujuhong Yeah. Maybe after https://github.com/docker/docker/pull/18958 is landed, we can do something more. For now, I think we have done most of the things. :)
