### ISSUE TITLE
AWS: kube-down fails to clean up properly if no nodes are running

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#15088]
A user on slack mentioned that he was unable to delete a cluster created using our recommended method (`export KUBERNETES_PROVIDER=aws; curl -sS https://get.k8s.io | bash`) by running `cluster/kube-down.sh`, as we [recommend for tearing such clusters down](http://kubernetes.io/v1.0/docs/getting-started-guides/aws.html#tearing-down-the-cluster).

We don't have much other detail on this, but if someone with an aws account could validate that this hasn't broken, it'd be much appreciated.

@brendandburns

**Comment by hotmeatballsoup** [comment]
The full command I ran was (from inside my local `kubernetes` dir):

    export KUBERNETES_PROVIDER=aws; cluster/kube-down.sh

Console output was:

    Bringing down cluster using provider: aws
    Done

But, back in AWS, all the EC2 instance are still there and running. Auto-scaling groups is still there and running. Everything appears to have been unaffected by running the `kube-down.sh` script.

**Comment by hotmeatballsoup** [comment]
And, for the sake of good measure, I accidentally stopped all EC2 instances prior to running this `kube-down.sh`. The auto-scaling group re-provisioned 4 new minions for me and then I manually restarted the master.

I only mention this in case the `kube-down.sh` script is still expecting the 4 original minion nodes somehow.

**Comment by hotmeatballsoup** [comment]
By stopping and restarting the master I see that it has a new IP address. Perhaps the script is using TLS certs and other configs that are bound to the master that *used* to be living at the old IP.

**Comment by a-robinson** [comment]
Yeah, killing the master was the problem here. I thought AWS might be using a static IP or static DNS name for the master, but apparently not.

**Comment by a-robinson** [comment]
Sorry, didn't mean to close this - killing the master explains why kubectl doesn't work, but shouldn't prevent kube-down from doing it's thing, at least not without spitting out error messages.

**Comment by davidopp** [comment]
@justinsb

**Comment by justinsb** [comment]
There is a bug/edge case is the script where we don't clean up properly if there are no minions running.

My inclination is to fix this as part of fixing kube-up in 1.3.  "fixing" might be in the pet sense here :-)

Going to downgrade to P3 and rename the title

**Comment by kant111** [comment]
I have VPC_ID set as environment variable. the kube-down script looks like it is not taking the existing VPC_ID into account and I fear this will actually delete the existing VPC?

**Comment by justinsb** [comment]
We're not going to be making further changes to kube-up.  I recommend kops as the natural replacement for the ease-of-use of kube-up on AWS without the shortcomings!  Also, kops can delete a cluster it did not create, including this case I believe, by passing the `--external` flag to `kops delete cluster`.  Closing.
