### ISSUE TITLE
Enable easier tracking of leaked resources from e2e tests

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#15084]
(cc @ixdy @quinton-hoole @brendandburns)

We're consistently leaking resources in e2e tests and having to clean them up.

We should consider a test right at the beginning of a run that, if there are any resources that it doesn't expect, lists and deletes them all, and then fails.
#15083 and #13515 may be easier if we can get this done.

**Comment by jayunit100** [comment]
Which resources: cluster or local ?

**Comment by ixdy** [comment]
I was planning of at least writing a dumb script that runs `gcloud list` on a variety of resources before a test run, then compares that against a `gcloud list` run after the test.

We won't be able to run it on all of our Jenkins projects; those that share a GCP project would have constant false positives, including the PR Jenkins. But it'd be better than the nothing we have right now.

**Comment by ihmccreery** [comment]
> We won't be able to run it on all of our Jenkins projects; those that share a GCP project would have constant false positives, including the PR Jenkins. But it'd be better than the nothing we have right now.

Some of the resources will be quarantined in a specific network, (e.g. firewall rules).

For those that aren't, it would be great if we could make them traceable to a cluster, (e.g. not use just a random hash, but instead a reasonable name prefixed with the cluster name,) and then we could just grep on the cluster name, right, as long as cluster names aren't substrings of each other.  @ixdy, maybe you know if there's a bug open for that work?  I couldn't find one.

**Comment by ihmccreery** [comment]
@jayunit100 GCP resources, e.g. firewall rules, addresses, forwarding rules, and target pools

**Comment by ixdy** [comment]
I think I saw somewhere that @fabioy was working on a similar effort, but I don't know the details of that discussion.

**Comment by ixdy** [comment]
#14804 is related to this effort.

**Comment by ihmccreery** [comment]
Alternatively, there's been discussion of just relying on namespace deletion to cleanup after all tests.

**Comment by ixdy** [comment]
It'd be great if namespace deletion actually reliably cleaned up everything, but it'd probably be a good idea to have something out-of-band to check, too. #15189 is hopefully a start at exactly that.

**Comment by ihmccreery** [comment]
Regarding namespace deletion: #7372 is a work-in-progress.  That may be our best bet at a longer-term solution.

**Comment by ihmccreery** [comment]
#18119 is the real solution here, plus detection of leaked resources.

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by spiffxp** [comment]
@fejta @krzyzacy does recent janitor work address this?

**Comment by spxtr** [comment]
I think this is fixed by @ixdy's leak detection stuff a long time ago.
