### ISSUE TITLE
Validation should deserialize using runtime.Unstructured

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#15085]
We created the `runtime.Unstructured` to hold objects containing `TypeMeta` that we should be able to deserialize and inspect for other fields (`ObjectMeta` for instance) using common functions in the `runtime` package.  Using these types in validation (https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/schema.go#L99) would make for cleaner code and better re-use.

@linzichang

**Comment by linzichang** [comment]
Ok, tomorrow I will start to work on this.

**Comment by linzichang** [comment]
@deads2k @smarterclayton 
First add `runtime.IsList` to support `runtime.Unstructured`.
Then add `runtime.ExtractUnstructuredList` to do something similar to `runtime.ExtractList`.
