### ISSUE TITLE
Handle path updates in doc scripts

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#15094]
Docs in this repo get moved around for various reasons. Our docs update script should understand such moves and update all references to that doc with the new path.

**Comment by kargakis** [comment]
/sig docs
@kubernetes/sig-docs-maintainers

**Comment by chenopis** [comment]
IMHO, since all the docs now live in the k8s.io repo, any docs issue pre-2017 should be closed.
/close
