### ISSUE TITLE
ListWatch does not support filtering based on label selectors

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#15093]
https://github.com/kubernetes/kubernetes/blob/f86140f1a444a07cc81e0cd4d165ff990304769d/pkg/client/cache/listwatch.go#L46

Is this intentional?

**Comment by a-robinson** [comment]
@lavalamp

**Comment by lavalamp** [comment]
Don't use that function, it needs to be deprecated; construct a ListerWatcher yourself instead.

Or feel free to add a label selector to it.

**Comment by lavalamp** [comment]
Construct it using the high level client, I mean. If you search, you can find many examples of people constructing ListerWatchers.

**Comment by kargakis** [comment]
Removed by https://github.com/kubernetes/kubernetes/pull/34824
