### ISSUE TITLE
Kubelet should ensure that node does not panic on OOM

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#15091]
Linux can be configured to panic on OOM. This will impact QoS policy on kubelet since users can explicitly overcommit the node and kernel OOM killer is used to evict lower priority containers when the node is under memory pressure.

Specifically, kubelet needs to check the value of `/proc/sys/vm/panic_on_oom` and if it not equal to `0`, either 
1. Warn the user (event & logs) and mark the node `NotReady` (or)
2. disable `panic_on_oom` - `echo 0 > /proc/sys/vm/panic_on_oom`

https://www.kernel.org/doc/Documentation/sysctl/vm.txt

cc @derekwaynecarr @kubernetes/goog-node

**Comment by derekwaynecarr** [comment]
I do not have a clear use case for running Kubernetes where ```panic_on_oom``` should not be ```0```.  Marking the node ```NotReady``` if value is non-zero seems to require more work on the user part for things that I would think Kubernetes should do for me.  I prefer 2.

**Comment by derekwaynecarr** [comment]
Assuming we are all good with 2, I can send a PR.

**Comment by vishh** [comment]
Option `2` is what I prefer too. Thanks for picking this up @derekwaynecarr!

**Comment by derekwaynecarr** [comment]
I am working on this now, will have PR shortly.

**Comment by akloss-terion** [comment]
I am curious about this. We've been running our control plane nodes with `panic_on_oom=1` since 2021. If I understand this section of the kernel docs (and I'm not sure I do):
> If this is set to 1, the kernel panics when out-of-memory happens. However, if a process limits using nodes by mempolicy/cpusets, and those nodes become memory exhaustion status, one process may be killed by oom-killer. No panic occurs in this case. Because other nodes' memory may be free. This means system total status may be not fatal yet.

it seems like this would be safe(ish) to do.
