### ISSUE TITLE
Move the Google CSE search box into the banner (on kubernetes.io)

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#15092]
We can regain some real estate if we stop displaying the full search box across the top of the kubernetes.io site (especially in mobile views).

The current proposal is to instead only show a search icon (magnifying glass icon) that is always showing/available. When the icon is clicked, the search box overlays the content on the screen.

**Comment by timstclair** [comment]
Also, we should switch to using the [compact](http://googlecustomsearch.appspot.com/elementv2/compact_v2.html) layout, which is [recommended](https://developers.google.com/custom-search/docs/ui#layout) for mobile devices. (I think we can use it for desktop and mobile).

**Comment by bgrant0607** [comment]
Obsolete
