### ISSUE TITLE
Update documentation on how to pull from private docker repo

### ISSUE THREAD

**Issue by chiefy** [kubernetes/kubernetes#15103]
I created both a `/root/.dockercfg` and `/root/.docker/config.json` with creds (the json form is used by docker >= 1.8), then created a RC which called to pull the private image. I can ssh into the minion and `sudo docker pull myuser/private:version` just fine. 

```
Mon, 05 Oct 2015 15:20:17 -0400   Mon, 05 Oct 2015 15:20:17 -0400   1         api-ctrl-hryhz      Pod                     spec.containers{api}                Pulling            {kubelet 10.245.1.3}        Pulling image "docker.io/chiefy/private-image:latest"
Mon, 05 Oct 2015 15:20:18 -0400   Mon, 05 Oct 2015 15:20:18 -0400   1         api-ctrl-xub3l      Pod                     spec.containers{api}                Failed             {kubelet 10.245.1.3}        Failed to create docker container with error: no such image
Mon, 05 Oct 2015 15:20:18 -0400   Mon, 05 Oct 2015 15:20:18 -0400   1         api-ctrl-84dlp      Pod                     spec.containers{api}                Failed             {kubelet 10.245.1.3}        Failed to pull image "docker.io/chiefy/private-image:latest": image pull failed for docker.io/chiefy/private-image:latest, this may be because there are no credentials on this request.  details: (Error: image chiefy/private-image:latest not found)
Mon, 05 Oct 2015 15:20:18 -0400   Mon, 05 Oct 2015 15:20:18 -0400   1         api-ctrl-xub3l      Pod                     spec.containers{api}                Pulled             {kubelet 10.245.1.3}        Successfully pulled image "docker.io/chiefy/private-image:latest"
Mon, 05 Oct 2015 15:20:18 -0400   Mon, 05 Oct 2015 15:20:18 -0400   1         api-ctrl-hryhz      Pod                     spec.containers{api}                Pulled             {kubelet 10.245.1.3}        Successfully pulled image "docker.io/chiefy/private-image:latest"
Mon, 05 Oct 2015 15:20:18 -0400   Mon, 05 Oct 2015 15:20:18 -0400   1         api-ctrl-hryhz      Pod                     spec.containers{api}                Failed             {kubelet 10.245.1.3}        Failed to create docker container with error: no such image
```

**Comment by a-robinson** [comment]
Please re-post your question to stackoverflow.

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:

the user guide
the troubleshooting guide
Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by chiefy** [comment]
@a-robinson I posted here not because I need help, but it seems like a bug.

**Comment by a-robinson** [comment]
My apologies @chiefy! I didn't realize that [this is a recommended method for authenticating to a private repo](https://github.com/kubernetes/kubernetes/blob/d98f6daff354b4480545706ab44b51d69edada23/docs/user-guide/images.md#configuring-nodes-to-authenticate-to-a-private-repository).

@erictune @mattmoor - you two last touched that part of the doc, interested in taking a look?

**Comment by mattmoor** [comment]
Yes, this doc needs to be updated.  Docker started doing this in 1.7+ clients.

This was actually fixed in: https://github.com/kubernetes/kubernetes/pull/12717

**Comment by a-robinson** [comment]
@mattmoor - thanks! Would you be willing to update the doc? I have to admit I'm not really sure what the new instructions should be.

**Comment by chiefy** [comment]
@a-robinson @mattmoor [here's what I had to do to get it working](http://stackoverflow.com/a/32972366/255051)

**Comment by sils1297** [comment]
> This needs to be done for each pod that is using a private registry. However, setting of this field can be automated by setting the imagePullSecrets in a serviceAccount resource.

The most automated solution is usually what one wants, right? I'd love it if there was some explicit information in the docs that include that info.

**Comment by sils1297** [comment]
At least a sample configuration for not only a pod but a replication controller would be nice and very straightforward IMO.

**Comment by erictune** [comment]
Docs:
http://kubernetes.io/v1.1/docs/user-guide/service-accounts.html#adding-imagepullsecrets-to-a-service-account

**Comment by sils1297** [comment]
IMO it would be a minor change to the docs (making the example with an RC, not a pod) and it'd be more helpful and straightforward.

**Comment by erictune** [comment]
A PR to change the docs would be welcome.

**Comment by Sha01in** [comment]
+1

**Comment by mateeyow** [comment]
I also think that there is an error when using the latest `config.json` of docker. This is the json format of `config.json`.

```json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "asdfasdfasdcasdfasdmclaskdjfe=",
			"email": "test@mail.com"
		}
	}
}
```
It does not authenticate when using this format. I have to edit the format to this:

```json
"https://index.docker.io/v1/": {
	"auth": "asdfasdfasdcasdfasdmclaskdjfe=",
	"email": "test@mail.com"
}
```

Removing the entire **auths** object.

**Comment by erictune** [comment]
@mateeyow what kubelet version are you running?

**Comment by mateeyow** [comment]
@erictune Running `kubectl version` yields:

```
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
```

**Comment by erictune** [comment]
It is the kubelet version that matters in this case.  That is different from the client (kubectl) version.
@kubernetes/goog-node   is there a recommended way for users to check kubelet version other than sshing to the machine and examining the binary?

**Comment by yujuhong** [comment]
> It is the kubelet version that matters in this case. That is different from the client (kubectl) version.
> @kubernetes/goog-node is there a recommended way for users to check kubelet version other than sshing to the machine and examining the binary?

The versions are included in the Node.Status.NodeInfo and they can be viewed via `kubectl describe node <nodename>`
E.g.,
```
System Info:
 Machine ID:			
 System UUID:			CA3B9601-99B0-031E-4AAD-EC4CEC772BF5
 Boot ID:			33e09e48-d984-40cc-bfe3-45151f11191f
 Kernel Version:		3.16.0-4-amd64
 OS Image:			Debian GNU/Linux 7 (wheezy)
 Container Runtime Version:	docker://1.8.3
 Kubelet Version:		v1.2.0-alpha.6.978+efbe57e75ad88a-dirty
 Kube-Proxy Version:		v1.2.0-alpha.6.978+efbe57e75ad88a-dirty
```

**Comment by dchen1107** [comment]
NodeStatus should include all information, like kubelet version, kernel version, etc.

**Comment by mateeyow** [comment]
@erictune I have this version:

```
System Info:
 Machine ID:			             0b40a1a590f54638be9d4bb0ac9fd4f4
 System UUID:			             0B40A1A5-90F5-4638-BE9D-4BB0AC9FD4F4
 Boot ID:			                     7d308c28-f206-44e3-9dd4-ae111f8d83e8
 Kernel Version:		             4.4.0-coreos-r2
 OS Image:			             CoreOS 942.0.0
 Container Runtime Version:	     docker://1.9.1
 Kubelet Version:		             v1.1.2+3085895
 Kube-Proxy Version:		     v1.1.2+3085895

```

**Comment by erictune** [comment]
Okay, you don't have support for unmodified `.docker/config.json` files.
You'll get that in 1.2.

**Comment by mateeyow** [comment]
@erictune Aaaah. Noted, thanks. May I suggest to have a note on the documentation? Others might get confused as well.

**Comment by thockin** [comment]
nobody is assigned to this - @erictune can you suggest where to go with it?  Docs update (which docs?) or close?

**Comment by chiefy** [comment]
@thockin @erictune I can probably take a stab this weekend.

**Comment by erictune** [comment]
The only thing to do here is to cherry-pick a change to the 1.1 release branch and then to the docs branch to explain how to do this on 1.1.  I didn't do that because it is a pain to deal with the branches, and 1.2 is coming soon.

 The docs at HEAD are correct for the code at HEAD, and when 1.2 releases, then the docs and 1.2 will be in sync.  Unless I'm missing something.

**Comment by erictune** [comment]
I removed the 1.2 milestone.

**Comment by jheiss** [comment]
This issue is still open but seems no longer relevant.
