### ISSUE TITLE
vagrant development cluster not always starting (kube-up)

### ISSUE THREAD

**Issue by davidkbainbridge** [kubernetes/kubernetes#15102]
on latest master branch 5-OCT-2015 @ 12:30pm PT, I am more often or not seeing the following message at the end of kube-up

```
Validating minion-1
.............
Waiting for each minion to be registered with cloud provider
error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: i/o timeout
```

**Comment by a-robinson** [comment]
@derekwaynecarr for sanity check on whether this is broken at head. If not, this should be a stackoverflow question so that it can be more easily discovered by other people in the future.

**Comment by davidkbainbridge** [comment]
Just for more details.

Host OS: MacOS 10.10.5
Virtual Box: 5.0.2 r102096
KUBERNETES_PROVIDER=vagrant
NUM_MINIONS=1

Using k8s built off the master branch.

Something seems wedged around networking when it fails, often a reboot of the host and the next kube-up will work. But it will eventuall freeze again.

**Comment by derekwaynecarr** [comment]
This was not broken on head for me today, but I think this error happens
when vagrant is unable to do host networking properly to speak to the
master.  On Linux, this is usually when some network interface doesn't come
up as expected for me, and just ensuring that the proper vboxnet device is
connected fixes it up.

Possibly do a

$ vagrant destroy
$ rm -rf .vagrant

If a host reboot fixes the issue, it sounds like something similar.  How
are you destroying boxes?  Maybe I can update Kube-down scripts to ensure
it does the removal of the .vagrant location if it's not already.

**Comment by davidkbainbridge** [comment]
to destroy the boxes i do

$ ./cluster/kube-down.sh
$ rm -rf .vagrant $HOME/.kube

I am spending a lot of time rebooting lately and doing creating / destroying VMs. Very time consuming.

**Comment by derekwaynecarr** [comment]
I can sympathize if you are having to reboot, I am just trying to figure
out what to do to diagnose.

For example, when this error happens:

$ vagrant ssh master
$ ifconfig | grep eth1 -C 2
eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.245.1.2  netmask 255.255.255.0  broadcast 10.245.1.255

Do you see 10.245.1.2?

On your host, can you do the equivalent:

$ ifconfig | grep 10.245. -C 2
vboxnet5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.245.1.1  netmask 255.255.255.0  broadcast 10.245.1.255
        inet6 fe80::800:27ff:fe00:5  prefixlen 64  scopeid 0x20<link>
        ether 0a:00:27:00:00:05  txqueuelen 1000  (Ethernet)

To see if your host is actually connected to a bridge that is listening on
10.245.1.1 to direct traffic to your box?

Thanks,
Derek

**Comment by davidkbainbridge** [comment]
i have been having better luck now that I up-ed the memory on the VM to 4GB. It has been much more stable and I haven't had to reboot.

There also does seem to be some inter-play with my VPN (which disallows local network access when activate). So kube-up does fail when I am on the VPN (as does everything k8s related as the cluster is essentially unreachable).

I did notice that my shared volume filled up and that sent things south. Not sure what filled it up and i ended up tearing down and rebuilding the cluster.

**Comment by davidkbainbridge** [comment]
to your specific question about eth1, when i am not on the VPN I am able to ping the IP.

**Comment by markllama** [comment]
Is there a way to adjust the timeout on the minion validation? It failed for me trying to connect to the master, timed out, but when I checked a few sec later the master had come up and the manual curl commands passed.  It appears, at least for me, that the master just took a long time to come up to offer the /api url.

**Comment by derekwaynecarr** [comment]
good to know issue was localized to VPN.  will update documentation troubleshooting to help others.

**Comment by davidkbainbridge** [comment]
So working a bit on this tonight. The minion is freezing on me. Not sure if it is a vagrant thing or something else. Testing out a custom docker image for a component, below is the sequence I have seen twice (after bring up the cluster with 1 minion).

1. (on host) docker save -o test.tgz image-name
2. (on host) vagrant ssh minion-1
3. (on minion) sudo docker load -i /vagrant/test.tgz
4. (on minion) ^D
5. (on host) kubectl create -f rc.yaml (starts a single instance of the image)
6. (on host) component doesn't work, but that is ok i am debugging it
7. (on host) kuvectl delete rc name
8. [everything fine so far]
9. (on host) rebuild new version of image
10. [repeat steps 1 to 7]
11. rc is gone, but pod still exists and if i ssh to the minion again things are frozen
