### ISSUE TITLE
kubelet with "--register-node=false" still tries to find that node

### ISSUE THREAD

**Issue by kayrus** [kubernetes/kubernetes#15108]
Default CoreOS [doc](https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/deploy-master.md#create-the-kubelet-unit) has following service:

```
[Service]
ExecStart=/usr/bin/kubelet \
  --api_servers=http://127.0.0.1:8080 \
  --register-node=false \
  --allow-privileged=true \
  --config=/etc/kubernetes/manifests \
  --hostname-override=${ADVERTISE_IP} \
  --cluster_dns=${DNS_SERVICE_IP} \
  --cluster_domain=cluster.local \
  --cadvisor-port=0
Restart=always
RestartSec=10
[Install]
WantedBy=multi-user.target
```

But even with "--register-node=false" it produces logs like (172.17.4.101 is master node):

```
Oct 05 19:38:59 c1 kubelet[1217]: E1005 19:38:59.780577    1217 kubelet.go:1933] Error updating node status, will retry: error getting node "172.17.4.101": node "172.17.4.101" not found
Oct 05 19:38:59 c1 kubelet[1217]: E1005 19:38:59.781823    1217 kubelet.go:1933] Error updating node status, will retry: error getting node "172.17.4.101": node "172.17.4.101" not found
Oct 05 19:38:59 c1 kubelet[1217]: E1005 19:38:59.784190    1217 kubelet.go:1933] Error updating node status, will retry: error getting node "172.17.4.101": node "172.17.4.101" not found
```
 
/cc @philips @bcwaldon
#12533 - here we see lots of useless logs too

[official doc](http://kubernetes.io/v1.0/docs/admin/node.html#manual-node-administration)

**Comment by yujuhong** [comment]
`--register-node=false` only means that kubelet would not try to register itself. However, it still expects a node object to be created for it. @kayrus, do you want kubelet to not update the node status at all? Currently, the only way to do it is to have a nil kubeClient (i.e., running in standalone mode without the apiserver).

From the doc:
```
If the administrator wishes to create node objects manually, set kubelet flag --register-node=false.
```

**Comment by kayrus** [comment]
@yujuhong is there a way to suppress these logs? Lots of users complain on them.

**Comment by yujuhong** [comment]
kubelet should stop complaining once you manually create the node object for it. If you simply want a standalone kubelet, you do not need to specify the apiserver. @kayrus, maybe you can explain your use case a bit to help us understand.

**Comment by bcwaldon** [comment]
@yujuhong On CoreOS today (github.com/coreos/coreos-kubernetes), we deploy controller nodes (those that run the control plane services) in such a way that they should not have user pods scheduled to them. The best way we have to do this today is simply not to register the controller node. I say this is the "best", because it still allows us to statically deploy the kubelet on the controllers. Having this deployment step be static is important, as we need to minimize the number of after-the-fact actions the user takes.

An even better solution here would be to autoregister the node as unscheduleable, but I don't believe that's possible with today's

**Comment by yujuhong** [comment]
@bcwaldon, we are actually fixing this issue because we want our master node (which runs all control-plane services) to register itself to the apiserver, and not let scheduler assign any pods to it. See #13102 and #14140 for the discussion and progress. I believe that should also work for your controller nodes.

**Comment by bcwaldon** [comment]
@yujuhong That sounds like what I need, too. I would like to do this declaratively, though. I do not want to have to make any API calls after the kubelet starts if I can avoid it.

**Comment by yujuhong** [comment]
@bcwaldon, you shouldn't have to. All you need to do is pass "--register-schedulable=false" to kubelet at startup.

**Comment by bcwaldon** [comment]
@yujuhong perfect, that's exactly what I was hoping :)

**Comment by ntquyen** [comment]
I set `--register-schedulable=false` to the master kubelet and restart but got error `unknown flag: --register-schedulable`. I'm using kubelet version 1.0.1

**Comment by yujuhong** [comment]
@ntquyen, this new flag was added recently in #14054, and probably won't make it in to v1.1 release.

**Comment by patrikbeno** [comment]
Kubernetes v1.2.0-beta.0
`--register-schedulable[=true]: Register the node as schedulable. No-op if register-node is false. [default=true]
`
Using kubelet on master node with --register-node=false
(as per https://coreos.com/kubernetes/docs/latest/deploy-master.html)

Still an issue. 6 error lines per 10 seconds.

**Comment by yujuhong** [comment]
> Still an issue. 6 error lines per 10 seconds.

What errors did you see with `--register-schedulable=false`?

**Comment by patrikbeno** [comment]
5x times
`Error updating node status, will retry: error getting node "master.cloud.local": nodes "master.cloud.local" not found`

followed by 
`Unable to update node status: update node status exceeds retry count`

`--register-schedulable=false` does not have any effect because `--register-node=false`

**Comment by patrikbeno** [comment]
According to https://coreos.com/kubernetes/docs/latest/deploy-master.html:

> On the master node, the kubelet is configured to communicate with the API server, but not register for cluster work, as shown in the `--register-node=false`


Are you saying that the proper way to configure master node is `--register-node=true --register-schedulable=false` ?

**Comment by yujuhong** [comment]
@patrikbeno, yes, we want the master node to register so that users can view the pods running on the node. Setting "--register-schedulable=false" simply prevents other tasks to be scheduled on the master node.

**Comment by yujuhong** [comment]
The docs should be modified to reflect this.

**Comment by nishen** [comment]
Hi there,

New to kubernetes...


What I've done so far is to manually register the node and set the node to unschedulable. Is this a viable workaround currently?
``kubectl create -f node.json``

node.json:
```
{
  "kind": "Node",
  "apiVersion": "v1",
  "metadata": {
    "name": "10.163.224.133",
    "labels": {
      "name": "coreos001-master-node"
    }
  },
  "spec":{
    "unschedulable":true
  }
}
```

**Comment by kayrus** [comment]
Confirmed. With new k8s 1.2.x you have to replace `--register-node=false` option with the `--register-node=true --register-schedulable=false`

**Comment by derekhound** [comment]
Confirmed. With new k8s 1.2.x. After I set option '--register-node=true --register-schedulable=false' on master node. No longer to see 'Error updating node status, will retry: error getting node' messages. Great job.

**Comment by kayrus** [comment]
Could be related: https://github.com/kubernetes/kubernetes/pull/31647

**Comment by YitongFeng** [comment]
Kubelet v1.7.1 set --register-node=false ----api_servers=""  that works for me
