### ISSUE TITLE
Flocker Volume Plugin: TestSetUpAtInternal flaky

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#15118]
@mattmoor reports the following failure after syncing with latest code:

--- FAIL: TestSetUpAtInternal (0.00s)
        Error Trace:    plugin_test.go:208
	Error:		Not equal: "expected-to-be-set-properly" (expected)
			        != "" (actual)
		
FAIL
FAIL	k8s.io/kubernetes/pkg/volume/flocker	0.067s

cc/ @saad-ali

**Comment by saad-ali** [comment]
CC @agonzalezro @mattbates

**Comment by agonzalezro** [comment]
Taking a look.

What do you mean with failed sometimes? Is it a random failure?

**Comment by saad-ali** [comment]
@mattmoor Can you please provide more information. This test seems to be consistently green in our CI runs.

**Comment by agonzalezro** [comment]
The test is failing on this assertion: https://github.com/kubernetes/kubernetes/blob/release-1.1/pkg/volume/flocker/plugin_test.go#L208 but as you can see on the previous line I am checking that there was no error on that call.

So the function is returning `nil` for the error checking but it's not setting `b.flocker.path`. Only place where it can happen is here: https://github.com/kubernetes/kubernetes/blob/release-1.1/pkg/volume/flocker/plugin.go#L163

Is the `meta` not been clean between runs?

**Comment by agonzalezro** [comment]
When I said "the only place where it can happen" it was because the other `err`s are being returned after a `err != nil` check. I think that there is no other way to get there.

**Comment by agonzalezro** [comment]
PS: I run the test suite 100 times and I didn't get any error:

```
# alex at Alexs-MacBook-Pro.local in ~/go/src/k8s.io/kubernetes/pkg/volume/flocker on git:flocker-fix o [23:39:51]
$ for i in `seq 1 100`; do go test ./...;done|grep -v ok
```

(That branch is based on the `release-1.1` branch)

**Comment by jdef** [comment]
@mattmoor can you test to see if the patch in #15158 fixes things for you?

**Comment by karlkfi** [comment]
See #15212 for reproducible test environment and failure logs.

**Comment by karlkfi** [comment]
Based on the solution in #542 it sounds like this test creates files the first time through which causes the tests to fail on the second time through.
