### ISSUE TITLE
Test that a cluster continues to function during upgrade steps, not just between them

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#15131]
(cc @quinton-hoole @roberthbailey)

Right now, our [upgrade tests](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/cluster_upgrade.go) only test that the cluster continues to function in between the steps it takes to do the upgrade, (i.e. before the master upgrade, after the master upgrade, before the node upgrade, after the node upgrade).

We should instead parallelize the test somehow, and make sure that the expected things stay up *during* the steps:

- during master upgrade, resources should still be reachable
- during node upgrade, resources should still be reachable and scheduling should still work.

(This is part of #14778)

**Comment by roberthbailey** [comment]
We've discussed this in other issues, but the gist is that an upgrade test should really be testing that a cluster survives an upgrade. If we want to run e2e conformance style tests on split version clusters that's a good goal, but an upgrade test should ensure that if I created an object in my cluster, it still exists and functions correctly after my cluster is upgraded. 

I was under the impression that at least some of our upgrade testing did this (e.g. create a service with an external load balancer and verify that it works before, during, and after an upgrade), but we almost certainly need to look at expanding our test coverage to more object types. 

@quinton-hoole -- eventually I'd like to see an easy e2e-like framework for upgrade testing and require that new API objects be integrated into it to become part of the stable v1 API. That way we know that we have sufficient test coverage for everything a user could be running in their cluster. Of course, this will only happen if it's super easy to add a new object into the upgrade framework.

**Comment by ihmccreery** [comment]
From @mikedanese:

> We check that an external load balanced service remains reachable during the master upgrade but not during the cluster upgrade. https://github.com/kubernetes/kubernetes/blob/master/test/e2e/cluster_upgrade.go#L342-L367

**Comment by quinton-hoole** [comment]
@roberthbailey there are two decent approaches that I can think of here:

First approach:
1. Refactor a subset of our e2e tests into three pieces each (where each piece fairly is independent of Ginkgo, and re-usable/recomposable across multiple Ginkgo test cases):
  1. setup - creates a set of resources to test (e.g. a set of services, or a set of pods with attached PD's etc)
  2. test - verifies that the set of resources behave as expected (e.g. services are reachable, PD's are read/wriable, etc)
  3. teardown - deletes the set of resources
2. Compose the above into multiple Ginkgo test cases:
  1. One that mirrors our current tests (i.e. runs setup, test, teardown).
  2. One that only does setup.
  3. One that only does test (assuming that setup preceded it).
  4. One that only does teardown (assuming that setup, and perhaps test, has preceded it)
3. Run the above 4 tests in different contexts:
  1. Run 2.1 as we do today.
  2. Run 2.2 and 2.3 before an upgrade, 2.3 (repeatedly) during the upgrade, 2.3 after the upgrade, 2.4 after that.

Once we've done the above refactoring in 2, we could consider auto-generating the tests in 3 (but I think that's a convenience).

First step would be, IMO, choosing a subset of representative tests to refactor, and refactoring them.

**Comment by quinton-hoole** [comment]
Oops - I screwed up my nested bulleted list above.  I'll try to fix that now.

**Comment by ihmccreery** [comment]
(cc @ixdy)

@quinton-hoole I tried to fix your outline above.

The spirit of this proposal seems right to me, and also seems like an important direction to be headed in anyway, (right now, some tests call functions across different files in `e2e/`, but all of the files are in the same package right now, so things are very hard to find, understand, and maintain).  I don't think we need your 2., though.  I'd revise to:

1. Refactor a subset of our e2e tests into three pieces each (where each piece fairly is independent of Ginkgo, and re-usable/recomposable across multiple Ginkgo test cases):
    1. setup - creates a set of resources to test (e.g. a set of services, or a set of pods with attached PD's etc)
    2. test - verifies that the set of resources behave as expected (e.g. services are reachable, PD's are read/wriable, etc)
    3. teardown - deletes the set of resources
1. Run the above 3 pieces in different tests:
    1. Run setup, test, teardown as we do today in "normal" test suites, (CI, etc.)
    2. Run setup and test before an upgrade, test (repeatedly) during the upgrade, test after the upgrade, teardown after that

I guess it depends on the mechanics of how we're doing an upgrade and how we parallelize it with testing.

**Comment by davidopp** [comment]
@quinton-hoole raises a good question: should this be marked as a 1.1 blocker?

**Comment by davidopp** [comment]
Also, can we assign this to @ihmccreery ?

**Comment by ihmccreery** [comment]
I can try to take this on, but I've got a lot on my plate right now with managing other upgrade stuff.

**Comment by ihmccreery** [comment]
@mikedanese You'd be the other candidate for working on this.  Maybe I can drive, but with your support?  Or vice versa?

**Comment by quinton-hoole** [comment]
To be clear, I suggested that this is either both P0 and a v1.1 blocker, or it is neither (I suspect the latter).

**Comment by mikedanese** [comment]
I do not have time to work on this unless it has higher priority than the other stuff assigned to me, in which case that stuff will slip.

**Comment by roberthbailey** [comment]
I think that for v1.1 we can run some manual tests to convince ourselves that upgrades work. This should be a P1 and not blocking 1.1.

**Comment by davidopp** [comment]
Yeah, I agree this should be moved to P1 and removed from 1.1. As Ike said, the upgrade tests do run e2e after the upgrade steps, just not during them. This isn't perfect but it doesn't seem like a blocker.

**Comment by quinton-hoole** [comment]
This is still P1 IMO, but unless we can find someone to work on it soon, it's not going to make it into 1.2.

I would estimate that this is at least a few weeks of dedicated work.

**Comment by ihmccreery** [comment]
This is squarely in the realm of the work I'm doing now, but won't happen before the end of the year.  Once I finish my P0 work, I will reevaluate.

**Comment by davidopp** [comment]
@ihmccreery We're trying to move all of the v1.2-candidate issues to v1.2 or next-candidate. Since the last update on this was Dec 15, I assume we should do the latter? Either way, please move it to one of the other categories. Thanks!

**Comment by ihmccreery** [comment]
#24014 provides what I believe is a basic framework for making progress on this.  `chaosmonkey` allows test writers to either implement an interface or define a function that works with a `chaosmonkey.Semaphore` to define functionality across a disruption (e.g. cluster upgrade).

This is similar to what @quinton-hoole suggested above, but puts the structural and parallel logic in first-class code instead of in test-framework land.

**Comment by ihmccreery** [comment]
#24014 has been merged; anyone who wants to test functionality across a cluster upgrade should be able to do so with relative ease.  I'd like to get more functionality in, but I'm not convinced that I'll be able to before the 1.3 branch.

**Comment by alex-mohr** [comment]
We don't have automated testing for components to keep working if they were created e.g. in 1.2 and upgraded to 1.3.  We need to do that manually for 1.3.

Once we manually verify 1.3, we should build automation for 1.4 and push this issue to that milestone.

**Comment by quinton-hoole** [comment]
cc: @lavalamp FYI.  This is the issue we discussed this morning.

**Comment by quinton-hoole** [comment]
Specifically: https://github.com/kubernetes/kubernetes/issues/15131#issuecomment-145943453

**Comment by erictune** [comment]
in progress, with good outlook for finish tomorrow.

**Comment by goltermann** [comment]
Finished upgrade testing for 1.3.
