### ISSUE TITLE
Standardize 'pause' container

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15140]
#15138 demonstrates that our code has no less than THREE different tags of the pause image.

Some of those say 1.0, but our codebase only has 0.8.0 - can someone explain what is going on?

@vmarmol @vishh ?

Also, can someone remind me why we didn't do this as a C program?

**Comment by davidopp** [comment]
Can we also document it? Some of the snippets in docs/ mention it but it's never explained anywhere.

**Comment by mattmoor** [comment]
FWIW, it isn't the only one.  I see at least two versions of each of `mounttest` and `nettest`.

**Comment by mattmoor** [comment]
Actually, for `pause` there are 4 since at least some references don't specify a tag, which means `latest`...  Others are: `0.8.0`, `1.0`, and `go`.

**Comment by vmarmol** [comment]
The original is `0.8` which is also tagged as `go`. News to me that there is a `1.0` :P I think there are so many references since tests decided to use whatever tag they wanted.

As per the why Go, at the time we tried Go produced the smallest binary and didn't require us to ask people to have yet another dependency.

**Comment by mattmoor** [comment]
Actually, if you look in the GCR UI you'll see that 1.0 == latest == go. :)

**Comment by dchen1107** [comment]
News to me that there is a 1.0 too! 

In production, we are using and only using gcr.io/google_containers/pause:0.8.0, which is built and pushed through Makefile: ./build/pause/Makefile
Such image is also cached in ContainerVM image.

**Comment by vmarmol** [comment]
Sounds like someone made and pushed a 1.0 without updating the one we use in production :)

**Comment by thockin** [comment]
Does anyone have free time to either a) make the whole codebase use 0.8.0
or b) bump it to 2.0, push to beta.gcr, and update the codebase to use 2.0
(and container VM)?

I'm still grumpy about it not being C - I have seen the Go binary die.

**Comment by vmarmol** [comment]
I had an assembly one! but you weren't a fan :D 

On a more serious note, long-term it is probably better that it is in C. The Go runtime wakes up a few times a minute to do nothing. So we do see some CPU usage from `pause` (although minimal).

**Comment by bprashanth** [comment]
Slightly OT, but we can just get rid of pause no? 

The way CNI is currently the runtime is reponsible for setting up the new network namespace (and bind mounting a few things) but the plugin will add containers to it. I can surely see how having a library in kube that is responsible for creating namespaces with or without docker is useful. For netns, this would create and manage a point to point link with the host.

**Comment by dchen1107** [comment]
@bprashanth I really want to get rid of pause. It complicates our container runtime implmentation, and resource management, introduces extra overhead, etc.
But when? cni has a 0.1 release a while back, but haven't heard from that for a while. Even today's rkt implementation is still rely on spawn extra systemd for namespace creation. 

I measured last time, rkt's systemd for each POD uses similar amount of resource: cpu and memory.

**Comment by bprashanth** [comment]
IMHO the win here is not reclaimed resources but the ability to manage our own networking and support the minimal runc model. We'd still need something to create that first net ns that everything else joins like you mentioned. I just like the idea of teaching kube about namespace joining so it can support bare bones container runtimes (this probably goes back to pods vs containers, though).

**Comment by thockin** [comment]
It will be some time before runc is ready for us to use, and we have more
than net namespaces to manage.

**Comment by thockin** [comment]
Assembly is a step too far, but a C program (I just did it) has an RSS of 1
page.  The cost is, as you point out, you need a C compiler to rebuild it.
If you want to make the binary tiny you also need dietlibc.  Is it
worthwhile?

**Comment by bprashanth** [comment]
True. I just don't like being beholden (read: enslaved) to a third party container runtime :)

**Comment by luxas** [comment]
@thockin Could you kindly upload the C code you used to build your new pause image (if you have it now). I guess it wasn't too complicated.

The gcc compiler isn't a problem, we could just build `pause` in the `kube-cross` image.

And just for curiosity, how much are we using pause atm? I guess runc has evolved a bit since 7 Oct when this was discussed. `runc` spec is now `0.4`, but `cni` is stuck at `0.1`

**Comment by davidopp** [comment]
Just to repeat my previous request -- can we please document the "pause" container? People ask about it pretty frequently and it's not documented anywhere (at least not in the docs in the docs repo).

**Comment by mattmoor** [comment]
@davidopp In addition, it would be good to make the container name itself slightly more self-documenting.  `pause` isn't a useful name at all (at least to me).

**Comment by thockin** [comment]
@uluyol there are still a bunch of places in the tree that reference :0.8 or or :1.0 or :2.0 - do you have 15 minutes to finish this cleanup? :D

**Comment by luxas** [comment]
This is fixed now with #23009 and #25972.

The pause image is now at version `3.0` and only in two places in the repo, which means it's easily updateable.

Closing as fixed

**Comment by luxas** [comment]
@uluyol A side note, the memory footprint became roughly `50-60x` smaller (from `1.8mb` to `32kb`), at least on my Raspberry Pi now.

I knew it would be smaller, it was @thockin's main point, but I didn't imagine it would decrease so greatly :)

**Comment by vishh** [comment]
cc @dchen1107 ^^

**Comment by davidopp** [comment]
Another request to document pause container.

**Comment by luxas** [comment]
@davidopp Please see #26863 
If you'd like more content in the pause section, feel free to comment on it
