### ISSUE TITLE
I have node-local services I want to offer to pods, e.g. DataDog, how can I do that?

### ISSUE THREAD

**Issue by gtaylor** [kubernetes/kubernetes#15169]
Posting at the suggestion of @thockin .

We're running on GKE with Kubernetes 1.0.6 (the latest release on there as of the time of this issue's writing). We're already using [Datadog](http://datadoghq.com/) successfully across of the rest of our fleet, and wanted to try to do the same on GKE.

They do have a Docker agent, but it currently has some limitations (no Network or process list metrics) that keep us from wanting to use it.

Since the Datadog agent also serves as a statsd server, the big thing we are running into is this:
- We send a ton of metrics from our various processes. The metrics get tagged based on the host they come from.
- As a consequence, we want each container to send metrics to UDP port 8125 on the host machine it resides within. The container doesn't necessarily need to know this, but we want containers on each machine to ultimately end up sending their metrics to the node's UDP port 8125.

It sounds like the current workaround would involve using the Downward API to query the Metadata API to find the right IP to send metrics to for each container. @thockin also mentioned the possibility of using hostNetwork, but that may not be tenable in GKE.

Open to ideas and other suggestions.

**Comment by alq666** [comment]
@gtaylor we have some k8s-specific monitoring in beta right now. Let me know if you're interested in checking it out

**Comment by gtaylor** [comment]
@alq666 Sure, would love to see what you've got. Been following the dd-docker-agent's kubernetes branch, but if you've got something else, please send it along!

**Comment by alq666** [comment]
@gtaylor that's where the code will come from indeed. Do you need some signal re: stability?

**Comment by thockin** [comment]
to capture some ideas on this:

We could expose a concept of a "local service" for which kube-proxy would
always choose a local pod.  This required DataDog (or whatever) to be a Pod
and it requires the new iptables proxier (or source IP gets obscured).
 "local" doesn't even have to mean node-local - it might mean rack local or
something else.

We could expose a virtual IP, like the GCE metadata server, that represents
the local node.  Simple.

We could expose a virtual IP, like the GCE metadata server, and expose only
select ports from the local node.  Cleaner but less simple.

I am sure more options will come to mind, but I wanted to jot those down.

**Comment by thockin** [comment]
For context for other readers:

we don't just want to add hostname as part of the downward API because a) it's not something you should be coupling to and b) it prevents future opportunities like migration.

**Comment by paralin** [comment]
@thockin Only reason why I was interested in that really was for the newrelic DaemonSet example I'm writing right now. It's more informative to have the hostname in that context be the node hostname, rather than the docker container hostname / pod name.

**Comment by gtaylor** [comment]
I definitely understand the coupling argument, but knowing which host the container is running on is, as @paralin is pointing out, is super helpful. Especially while the k8s scheduler is so basic.

**Comment by paralin** [comment]
Particularly for things like internal health monitoring and redundancy analysis.

**Comment by gtaylor** [comment]
Those are the two things we're currently struggling with.

**Comment by thockin** [comment]
I'm not saying there are not good reasons for knowing the hostname just
that we need to think carefully about the implications of exposing that.
Are you saying the use case is to know the name but not to access it?  The
DataDog example wanted to access the host but doesn't care what the host's
name is.

**Comment by paralin** [comment]
@thockin In my particular case, all I care about is knowing the hostname of the node.

**Comment by paralin** [comment]
@thockin Is there some way to do this with env vars? ex. some fieldRef or fieldPath.

**Comment by gtaylor** [comment]
@thockin Each Datadog metric/event has a hostname value attached. You get this by default based on the hotsname that the Datadog agent is running on. If I run a Datadog agent on Node 1 and send metrics to it from Node 2, said metrics will appear to be from Node 1. Similarly, if I run the agent from a container, all metrics from other containers will appear to come from that container's hostname. Not ideal.

You *can* override the hostname attached to a metric. We just don't currently have a great way to do that, since the hostname is out of reach. This means that all of our alerts that consider which hosts are involved in a metric's values get messed up pretty bad. We also lose out on all of the auto-tagging that Datadog does when it knows that it is being ran on GCE/AWS (regions, project names, zones, instance tags, etc).

Also, the other benefit to running the agent outside of Kubernetes on the host is that we're able to send all kinds of host machine metrics (in addition to the containers being able to send their own time-series metrics).

**Comment by thockin** [comment]
FWIW you don't have to run outside of kubernetes to run on the node's
network.  We have a hostNetwork parameter just for that :)

**Comment by gtaylor** [comment]
The reason I'd want to run outside of Kubernetes is that it ensures that I'm getting all of the system-level metrics. Some aren't available when running the agent under Docker. This could change in future dd-agent releases, though.

**Comment by paralin** [comment]
@thockin Would you keep the same hostname then? hmm

**Comment by paralin** [comment]
That seems to work well @thockin.

However, I noticed this line:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/exec.go#L50

Here you set the container hostname, would it be possible to add an environment argument with something like NODE_HOSTNAME?

Also is there a way to specify --pid=host at the moment? It doesn't look like it to me.

**Comment by thockin** [comment]
in Kubernetes v1.1 you can set pod.spec.hostPID

**Comment by paralin** [comment]
@thockin Great, thanks!

**Comment by therc** [comment]
Which of @thockin's three options is more likely to get accepted if implemented?

**Comment by remh** [comment]
Hey everyone. 

One workaround is to expose the dogstatsd port to the host itself.
And then use mechanisms to retrieve the IP of the host.

It's something that got implemented in the python dogstatsd client:
https://github.com/DataDog/datadogpy/pull/134

It will use the default router which should be the kubernetes host. Let me know if that helps

**Comment by joonas** [comment]
I wanted to chime in here that I've also wanted the ability to do something in this vein before, my use case for it was being able to access the node local daemonsets (in my case, rsyslog).

From discussing this a bit with @brendandburns, @jbeda and @lxpollitt at GlueCon last week, it sounded like @jbeda had another use case in mind for something like this and @lxpollitt was aware of some proposals / discussions in sig-network that might help enable this from a networking perspective.

**Comment by therc** [comment]
I have #28637 out for a solution involving DaemonSets. We currently use run the DataDog node agent as a DaemonSet with `containerPort: 8125` and `hostPort: 8125`. We've been using a hack for the node-local part: pods send traffic to a magic IP address that is translated to the node's IP through a custom iptables rule set up by our installer. With my proposal, the magic IP is replaced by a service IP and the iptables rule is managed by `kube-proxy`. Plus, the service itself can be discovered and inspected with standard `kubectl` commands.

**Comment by kjvalencik** [comment]
@therc What iptables rule are you using as a work around? I'm not able to get something to work within a pod.

**Comment by therc** [comment]
DNAT       udp  --  anywhere             MAGICIP  udp dpt:8125 to:NODEIP

**Comment by kjvalencik** [comment]
I made a similar change to run cluster DNS as a `DaemonSet`.
https://github.com/kubernetes/kubernetes/issues/7470#issuecomment-263695219

**Comment by gjcarneiro** [comment]
For my use case I would require `PreferNodeLocal` (nodes in some datacenters cannot run this type of pod), but it is listed merely as "future work" under the proposal.  What a pity...

**Comment by fabiand** [comment]
I wonder if there is some progress on this issue?

**Comment by alexef** [comment]
@fabiand Now (kubernetes 1.7+), this functionality should be available through DaemonSets + hostPort + spec.hostIP/nodeIP

https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#communicating-with-daemon-pods

**Comment by gtaylor** [comment]
> Clients know the list of node IPs somehow, and know the port by convention.

The somehow part of this is the thing needing improvement. As it stands, I believe you have to query the Kubernetes API to figure out the node's IP.

**Comment by alexef** [comment]
Or you can use the Downward api to get the hostIP :)

**Comment by gtaylor** [comment]
Ah, I didn't see that they added the node IP. This is good enough to solve this issue, I think.
