### ISSUE TITLE
Support better integration with “Stateful" schedulers

### ISSUE THREAD

**Issue by sidharta-s** [kubernetes/kubernetes#1517]
The current scheduler plugin implementation assumes that a scheduler “algorithm” needs to be used only when a pod needs to be scheduled (and not deleted/updated). It would be useful to generalize this with added support for letting the scheduler know about delete/update events as well. One example of where this would be very useful would be to integrate better with external/stateful schedulers/resource managers (e.g YARN). Instead of calling into the scheduler algorithm with a pod definition, maybe a pattern similar to what is used in the kubelet could be used ? ( “PodUpdate”/“PodOperation”  ).  Thoughts?

**Comment by lavalamp** [comment]
The current scheduler uses a watch to see all changes to pods it's interested in, which currently is the set of pods with no host field set. It uses this data as a queue of pods waiting to be scheduled.

I can imagine much more complex schedulers that do things like ask for resources to be allocated. I can also imagine components that free up resources when pods are deleted (but it's not at all clear to me that this should be a responsibility of the scheduler).

I would like to see more detailed use cases before agreeing that our scheduler as it stands needs to have hooks; it's fairly modular and already a plugin, so if you want to more complex things my first thought is that you should just write a different scheduler binary.

**Comment by smarterclayton** [comment]
We should do a quick pass and maybe add an example of a variant scheduler and how to run it (would be a good example for our docs, and would highlight any issues or roadblocks in the tweak code -> build -> running image workflow).

**Comment by jdef** [comment]
kubernetes-mesos builds a different scheduler binary, but extends the base scheduler plugin:
* https://github.com/mesosphere/kubernetes-mesos/blob/master/pkg/scheduler/plugin.go

This scheduler implementation can free up mesos resources by killing tasks. It also has the responsibility of watching for deleted pods and communicating kill messages to the kubelet/executor (we use a customized kubelet too). Under current development in a branch, additional functions for task recovery and reconciliation can also more aggressively manage pods, but that's mostly left up to a higher power: the pod registry is the desired state and the scheduler only steps in when it thinks that the state is flawed.

The scheduling algorithm itself is still fairly naive and does not (yet) incorporate the provider/algorithm design that k8s implements.

**Comment by timothysc** [comment]
This issue is sufficiently vague and old that I'm going to close for now.  If folks would like to reopen, please feel free.
