### ISSUE TITLE
cleanup: use ioutil.TempDir in unit tests

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#15176]
As discussed in https://github.com/kubernetes/kubernetes/issues/14781#issuecomment-145720272, there are a number of unit tests which appear to be using a static temporary directory for test files, which can cause failures if tests are run in parallel on the same machine.

```console
$ find pkg -iname *_test.go | xargs grep -l "/tmp/" |  find pkg -iname *_test.go | xargs grep "/tmp" | grep -v TempDir | wc -l
71

$ find pkg -iname *_test.go | xargs grep -l "/tmp/" |  find pkg -iname *_test.go | xargs grep "/tmp" | grep -v TempDir | cut -d: -f1 | sort | uniq
pkg/cloudprovider/providers/mesos/client_test.go
pkg/controller/persistentvolume/persistentvolume_claim_binder_controller_test.go
pkg/kubelet/network/cni/cni_test.go
pkg/kubelet/network/exec/exec_test.go
pkg/kubelet/runonce_test.go
pkg/master/master_test.go
pkg/util/io/io_test.go
pkg/volume/aws_ebs/aws_ebs_test.go
pkg/volume/cephfs/cephfs_test.go
pkg/volume/cinder/cinder_test.go
pkg/volume/downwardapi/downwardapi_test.go
pkg/volume/empty_dir/empty_dir_test.go
pkg/volume/fc/fc_test.go
pkg/volume/gce_pd/gce_pd_test.go
pkg/volume/glusterfs/glusterfs_test.go
pkg/volume/host_path/host_path_test.go
pkg/volume/iscsi/iscsi_test.go
pkg/volume/nfs/nfs_test.go
pkg/volume/persistent_claim/persistent_claim_test.go
pkg/volume/rbd/rbd_test.go
```

Each of these should be updated to use `ioutil.TempDir` so that a new unique temporary directory is created for each test.

**Comment by linzichang** [comment]
@ixdy Do you need someone to fix this? Since you added the help-wanted tag.

**Comment by ixdy** [comment]
@linzichang it's fairly simple grungy work, but I don't think anyone has volunteered for it yet. It's not necessarily a top priority, but it also should be fairly straightforward.

Basically, someone needs to go through the unit tests (the ones I listed are a good start) to look for those that are using static paths for temporary files, and rework them to instead use `ioutil.TempDir` so that each test invocation gets a unique directory.

This would enable us to run these unit tests in Jenkins in parallel, since right now they can potentially interfere with each other.

**Comment by jijun2** [comment]
@ixdy ,@linzichang  ,If no one is doing this now ,I think I can help to fix this.

**Comment by linzichang** [comment]
OK

**Comment by jijun2** [comment]
,

**Comment by saad-ali** [comment]
@jijun2 can you please combine all these PRs in to one, and close the individual ones. They are all doing essentially the same thing, so comments on one of these PRs is likely to apply to the others. Thanks!

**Comment by saad-ali** [comment]
CC @ashcrow

**Comment by ashcrow** [comment]
:+1: agreed. Pulling them all into one fix for the issue will make more sense for git history.

**Comment by jijun2** [comment]
@ashcrow @saad-ali @ixdy , Ok, I will bombine all PRs.

**Comment by ixdy** [comment]
Looks like a few tests still remain:
```console
$ find pkg -iname *_test.go |  xargs grep "/tmp" | grep -v TempDir | cut -d: -f1 | sort | uniq
pkg/cloudprovider/providers/mesos/client_test.go
pkg/controller/persistentvolume/persistentvolume_claim_binder_controller_test.go
pkg/master/tunneler_test.go
pkg/util/io/io_test.go
pkg/volume/fc/fc_test.go
pkg/volume/glusterfs/glusterfs_test.go
pkg/volume/host_path/host_path_test.go
pkg/volume/iscsi/iscsi_test.go
pkg/volume/nfs/nfs_test.go
pkg/volume/persistent_claim/persistent_claim_test.go
pkg/volume/rbd/rbd_test.go
```

**Comment by jijun2** [comment]
@ixdy , I will complete in this week.

**Comment by ihmccreery** [comment]
Assigning to @saad-ali since he reviewed #16236.  @saad-ali let me know if you want to pass off to me.

**Comment by ihmccreery** [comment]
#16236 is closed.  @saad-ali can you drive this?

**Comment by ihmccreery** [comment]
@fabioy to drive this home.

**Comment by fabioy** [comment]
PR merged, closing this issue.
