### ISSUE TITLE
docker pull can stall, leading to cluster bring up stalling

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#15175]
On one of my deployments this morning, I observed that kubelet was not deploying the master components. On closer look, kubelet's last log entry (besides healthz checks) were pulling the images from gcr.io.

Other users mentioning docker pull hangs near the bottom of this issue: docker/docker#6928

That issue also seems to request a mechanism for determining the status of a pull job, maybe to be able to kill it and restart it if it hangs. Maybe kubelet could somehow have a timeout for `docker pull`s?

**Comment by colemickens** [comment]
Workaround was to kill docker daemon, let monit restart it and then let the kubelet successfully pull the image.

**Comment by dchen1107** [comment]
This is known issue, and should be fixed by #10998 in 1.0 release.

Which version are you running?

**Comment by colemickens** [comment]
I'm running from master (4856c7c033bcda29790d7e7c0a27ce5a794a817b) (fetched and rebased early yesterday) with a few minor, Azure-specific commits of my own on top.

**Comment by dchen1107** [comment]
Ahh, #10998 only fixed docker load from tar file. Here you are referring to docker pull. Ok we should timeout docker pull operations too.

**Comment by dchen1107** [comment]
@colemickens I only observed such issue with concurrent pulling. For 1.1 release, we switch concurrent pulling to sequential pulling by default. Please let me if you still have the same issue with 1.1 release. Thanks!

**Comment by dchen1107** [comment]
@colemickens when you run into such issue next time, could you please run the command: docker version and copy & paste the output here? I replaced monit with supervisord for 1.1 release too, and supervisord run docker version, and check the exit code of command. If docker daemon hung, it should return non-zero here. Then supervisord should restart docker daemon.

**Comment by colemickens** [comment]
@dchen1107 Sure, I can do that. One small question about your last comment - where did you replace monit with supervisord? With the setup I'm using, I let upstart itself manage the docker instances running and am not using monit or supervisord. Just curious, wanted to compare notes.

**Comment by dchen1107** [comment]
Ahh, I just realized that only gce/gke cloud provider is using supervisord, not all cloud providers. I will send pr to fix this shortly, but not sure we plan to include that into 1.1 release.

**Comment by dchen1107** [comment]
Here is the code we switch to supervisord for GCE & GKE: https://github.com/kubernetes/kubernetes/blob/b9cfab87e33ea649bdd13a1bd243c502d76e5d22/cluster/saltbase/salt/top.sls#L32

**Comment by dchen1107** [comment]
@colemickens #16736 was merged and cherry-picked to 1.1 release.

**Comment by dchen1107** [comment]
@colemickens I believe  #16736 should fix your issue here. I am closing the issue. Please re-open it if the problem still occur. Thanks!
