### ISSUE TITLE
Observed errors from hairpin code on kube master node

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15187]
```
I1006 22:29:02.131792    7050 hairpin.go:49] Unable to find pair interface, setting up all interfaces: Unable to query interface eth0 of container 9264: exit status 94
I1006 22:29:02.314735    7050 hairpin.go:49] Unable to find pair interface, setting up all interfaces: Unable to query interface eth0 of container 9292: exit status 94
I1006 22:29:02.524940    7050 hairpin.go:49] Unable to find pair interface, setting up all interfaces: Unable to query interface eth0 of container 9288: exit status 94
I1006 22:29:02.654483    7050 hairpin.go:49] Unable to find pair interface, setting up all interfaces: Unable to query interface eth0 of container 9307: exit status 94
I1006 22:29:02.955118    7050 hairpin.go:49] Unable to find pair interface, setting up all interfaces: Unable to query interface eth0 of container 9309: exit status 94
```

@ArtfulCoder @MikaelCluseau

**Comment by MikaelCluseau** [comment]
Hi, "fix" proposal: include the output of the failing command in the error?

**Comment by thockin** [comment]
Good start :)

**Comment by thockin** [comment]
patched in #15194

I1006 23:38:47.364277   12715 hairpin.go:49] Unable to find pair interface, setting up all interfaces: Unable to query interface eth0 of container 13722: exit status 94: no stats available

It seems to only happen when a pod's infra container dies unexpectedly.

Manually running nsenter into the container and trying ethtool:

```
root@kubernetes-master:/home/thockin# ethtool -S  eth0
no stats available
```

**Comment by thockin** [comment]
aha, these are pods with hostNetwork == true, so ethtool will not give them proper stats.

Can you detect hostNetwork and skip hairpin?

**Comment by MikaelCluseau** [comment]
I certainly can. It's more logic outside the hairpin package though, but probably the quickest fix. I could also try to compare the netns (`/proc/PID/ns/net` symlink) and skip hairpin if the container's netns is the same as the kubelet's one. What do you think is the best?

**Comment by thockin** [comment]
I think it's fine to just check the hostNetwork flag and short-cut if it is
set.

**Comment by MikaelCluseau** [comment]
Okay

**Comment by bgrant0607** [comment]
If this is for 1.1, it needs to be P0 at this point. Should it be?

**Comment by thockin** [comment]
Not worth a cherry pick
