### ISSUE TITLE
kubectl port-forward should allow forwarding to a Service

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15180]

**Comment by bgrant0607** [comment]
Currently only accepts pods:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/portforward.go#L78

We could accept resource/name and "resource name" and assume pods by default.

**Comment by feiskyer** [comment]
There are a little problem on service port-forwarding: service is not binding to a specific node, so it should be scheduled to some node first. But there is no such a scheduler existing now.

**Comment by abourget** [comment]
Couldn't it pick a random node ? They all route to services, don't they ?

**Comment by erictune** [comment]
I want this for Charts.  For example, if you have a chart that has one mysql server in it, and a service to give it a stable name, I don't want to have to keep figuring out the pod name. 

Server side would be resolution of service to pod would be idea, but client side would also be a big improvement.

**Comment by eljefedelrodeodeljefe** [comment]
This would be helpful for (MongoDB) StatefulSets as well. Currently connecting to one of it's pod has odd behaviours.

**Comment by cmoad** [comment]
As a solution in the near-term, we grab the first pod name using a template and pass that into the port-forward command.

Example:
`kubectl --namespace logger port-forward $(kubectl --namespace logger get pod -l service=kibana -o template --template="{{(index .items 0).metadata.name}}") 5601:5601`

**Comment by Analect** [comment]
@cmoad 
I am port-forwarding kibana, as you show above, which was working for me yesterday fine ... I was able to view and interact with developer tools and run various REST API calls.  

However, today ... I get this error on the main kibana screen ... 
`Kibana did not load properly. Check the server output for more information.`

... and the developer tools will no longer render.

![image](https://cloud.githubusercontent.com/assets/4063815/22829568/1f74df28-ef9b-11e6-85a0-73da83d74afa.png)

Are you aware of anything that might limit what gets forwarded via `kubectl foward` and why all assets don't appear to load.  Screenshot above is on a chrome incognito window.

I came across this on the ES forum, but not sure if it's relevant in this case.
https://discuss.elastic.co/t/kibana-did-not-load-properly/64867

Thanks.

**Comment by cmoad** [comment]
@Analect I believe kibana has the option of making Elasticsearch calls on the server running kibana or on your client machine. If it is configured on the client machine, then you need to also have access to the Elasticsearch server from your client. I can't think of any other reason why it wouldn't work. We use kibana exactly as you show and Elasticsearch calls are made from the server running kibana.

**Comment by Analect** [comment]
@cmoad ...thanks .. was able to resolve by removing the `.kibana` index.  Not sure what the problem was.

**Comment by tupy** [comment]
+1

**Comment by PauloPaquielli** [comment]
+1

**Comment by kargakis** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by shahidhk** [comment]
We are looking at this issue as it is a pressing use case for us. Currently we use port-forward to a pod, but when he service restarts, the tunnel breaks. I'm thinking of possible ways to implement a persistent tunnel to a service.

Taking service name as an argument and getting​ corresponding pod based on that to forward the port seems like the easiest one to implement. Restarts and multiple pods have to be handled though.

What about the `kubectl proxy` command? I'm quite confused since this one is more closer to proxying services to the client machine. Would adding port support here makes more sense than extending `port-forward`? Something like `kubectl proxy namespace/postges --port 5432:5432`

Long time k8s user, but new to the codebase. Sorry if I'm missing something out

**Comment by JeanMertz** [comment]
This would definitely be a nice feature to have. We currently have to do things like:

```
kubectl port-forward $(kubectl get pod -o=name -lcomponent=... | awk -F/ '{print $2}' | head -1) PORT
```

to get a single pod. It would be better (and also more resilient, since the above command always takes the first pod, no matter the state) to go through a service instead.

And as @shahidhk stated, obviously having the benefits of keeping a connection alive, even when a pod restarts would be a great feature to have.

**Comment by abourget** [comment]
This is an everyday feature, I use that as often as `get pods` .. any hack would be appreciated !

**Comment by julianvmodesto** [comment]
@deads2k what was the result of your related work in OpenShift mentioned in #36819? Is it still related and likely the best solution for this use case?

**Comment by daggerok** [comment]
yeah, it would be nice to have service port forwarding.. these days with minikube when `minikube service web-app` or `minikube service web-app --url` doesn't work, I'm using  pods port forwarding:

terminal:

```bash
cat web-app-pod.yml
# ...
metadata:
  name: web-app
# ...

export WEBAPP_POD=$(kubectl get pods -n $NAMESPACE | grep web-app | awk '{print $1;}')
kubectl port-forward -n $NAMESPACE $WEBAPP_POD 8080
```

browser / client:

```bash
open http://localhost:8080
```

**Comment by mediafreakch** [comment]
It was never mentioned here but was exactly what I was looking for: https://docs.giantswarm.io/guides/accessing-services-from-the-outside/#api-access

Accessing a random pod through the service via URL.

First, simply use `kubectl proxy --port 8002`.
Then you can access your apps like this: `http://localhost:8002/api/v1/proxy/namespaces/NAMESPACE/services/SERVICE_NAME:SERVICE_PORT/`

**Comment by e1senh0rn** [comment]
@mediafreakch Proxy can do for HTTP services, but it won't work for raw TCP/UDP (postgres, powerdns, etc).

**Comment by shiywang** [comment]
cc @vfreex

**Comment by jbeda** [comment]
Proxy also does deep content inspection to rewrite URLs. This is appropriate for thinks like the UI but will lead to surprises for others use cases: https://github.com/kubernetes/apimachinery/blob/18a564baac720819100827c16fdebcadb05b2d0d/pkg/util/proxy/transport.go#L71

FWIW, I have a side project that is *super* early to implement this client side.  If it proves out I'll release it and we can look to perhaps move it into kubectl.

**Comment by vfreex** [comment]
IMO it is more reasonable to implement this feature in `port-forward` not `proxy`.
The syntax would be like `kubectl -s SERVICE [LOCAL_PORT]:[SERVICE_PORT] [...]`
`-p` option is deprecated for specifying the pod name, probably it should be brought back.

**Comment by phsiao** [comment]
My attempt to support this is in PR #59705, would appreciate comments and reviews.

**Comment by phsiao** [comment]
Want to bring #59733 to the attention of people who are interested in this issue.

**Comment by josdotso** [comment]
@phsiao.  Thanks! Will your solution allow cluster admins to scope port forwarding abilities using RBAC?

**Comment by phsiao** [comment]
@josdotso the implementation did not change how it connects to the api, so the same RBAC rule should continue to work.   The change would require permission to look up pods given a resource name, so that needs to be adjusted as needed.

**Comment by Ascendance** [comment]
would love to have this feature 👍

**Comment by emadolsky** [comment]
I assume a very nice idea in this context (while we are port-forwarding to a service) is to watch on the pod we have chosen to forward to and when it goes down, try to connect to another ready replica.
Now we will choose a pod without checking its readiness and after connecting if it gets terminated, there is no failover.

**Comment by mxxk** [comment]
@phsiao thanks for enabling service-level port forwarding in your PR #59809. However, it seems that `kubectl port-forward svc/my-service` only forwards traffic to one pod, even when the service has multiple endpoints. Is this the intended behavior? It seems a bit confusing, as it is different from how services load-balance between multiple pods.

By contrast, using `kubectl proxy` as described by @mediafreakch it is possible to reach different pods, as expected.

All of this is in Kubernetes v1.9:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by phsiao** [comment]
@mxxk port-forward was originally designed to attach to one pod for debugging and other purpose, the improvement in #59809 was really to help with service discovery so you don't need to lookup the pod name first if you don't care which one you attach to if you have multiple qualifying ones.   port-forward does more than just http connections, so the idea of load balancing does not apply and multiple active endpoints are not supported.   There is a separate feature request for re-attach if the active pod terminates, but there has not been work on it.

**Comment by mxxk** [comment]
Thanks for clarifying @phsiao. Perhaps this point can be further clarified in the help page for the port forward command? The current wording

https://github.com/kubernetes/kubernetes/blob/8a5e9ecf8febdfe5ca72d4d99340ce22cbf55cbb/pkg/kubectl/cmd/portforward.go#L76-L77)

simply says "a pod selected by the service", but it would be great if it explicitly states that _one_ pod selected by the service is chosen and all traffic is forwarded there for the entire lifetime of the port forward command 🙂

**Comment by lostpebble** [comment]
Oh my... I have been smacking my head against the wall for the past few hours wondering why on earth, when I am port-forwarding to a _service_, I am only sending traffic to a single pod.

Dug through all service documentation to see if I had suddenly gone crazy and didn't know how to configure a simple service correctly.

Please, for the sake of all future head smackers, make it way more clear that port-forwarding to a service still actually is using a single pod - and **does not function as one might expect.**

**Comment by kfox1111** [comment]
Yeah. and worse, the port forward is not re-evaluated when the pod dies. so, do a rolling upgrade and the port forward breaks. FYI.

Don't get me wrong, I'm very happy that you no longer have to go hunt for a pod name to do the port forward. :)  but there are some remaining issues with the current implementation.

**Comment by lostpebble** [comment]
Yea, I think the easiest way to prevent the confusion is to actually just output a simple message to the console when starting the `port-forward` command when it includes a service. Something like:

```
port-forward allows the use of services for convenience purposes only. Behind the scenes connects to a single pod directly. Connection will be dropped should this pod die.
```

Would have saved a lot of time 😅

**Comment by darenjacobstellic** [comment]
So, having read this, is there *any* way to get persistence of port-forward through the connected pod dropping?

**Comment by Aldekein** [comment]
There is also a solution to set up port forwarding to a service without selector/pod (e.g. ExternalName service) by deploying a proxy pod inside K8s:

```
    kubectl -n production run mysql-tunnel-$USER -it --image=alpine/socat --tty --rm --expose=true --port=3306 tcp-listen:3306,fork,reuseaddr tcp-connect:your-internal-mysql-server:3306
    kubectl -n production port-forward svc/mysql-tunnel-$USER 3310:3306
```

In the example above the MySQL server at `your-internal-mysql-server:3306` will be available on `localhost:3310` on your machine.

**Comment by pwittrock** [comment]
That is clever

**Comment by thockin** [comment]
https://github.com/kubernetes-retired/contrib/tree/master/for-demos/proxy-to-service

:)

**Comment by victortrac** [comment]
I'll throw in there one more solution: we sometimes set up pritunl as a pod inside of k8s, configured to set the client's DNS server to the kube dns cluster IP, with a default route over the VPN.  When a developer connects to the pritunl VPN, their machine is able to access any service by k8s service name & cluster IP/port, just like any other pod in the cluster.

**Comment by lukasz-madon** [comment]
I use 

```
kubectl port-forward svc/foobar 1234:http
curl http://localhost:1234/api/v1/
```

**Comment by ryuphi** [comment]
> I use for HTTP
> 
> ```
> kubectl port-forward svc/foobar 1234:http
> curl http://localhost:1234/api/v1/
> ```

I use this with TCP! <3 thx

**Comment by kvaps** [comment]
> There is also a solution to set up port forwarding to a service without selector/pod (e.g. ExternalName service) by deploying a proxy pod inside K8s:
> 
> ```
>     kubectl -n production run mysql-tunnel-$USER -it --image=alpine/socat --tty --rm --expose=true --port=3306 tcp-listen:3306,fork,reuseaddr tcp-connect:your-internal-mysql-server:3306
>     kubectl -n production port-forward svc/mysql-tunnel-$USER 3310:3306
> ```
> 
> In the example above the MySQL server at `your-internal-mysql-server:3306` will be available on `localhost:3310` on your machine.

Hi thanks for sharing, I made a kubectl plugin for that:

```
kubectl proxy-port-forward 3306:your-internal-mysql-server:3306
```

does exactly same

https://github.com/kvaps/kubectl-proxy-port-forward
