### ISSUE TITLE
Flaky integration test: replicationControllers "mock" cannot be updated: the object has been modified

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#15181]
shippable flake:

```
Error from server: replicationControllers "mock" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
!!! Error in ./hack/test-cmd.sh:793
```

It seems that this test needs to retry on update failures.  
cc @mikedanese who fixed some other similar test flakes recently and might want to take a swing at this one.

**Comment by JanetKuo** [comment]
cc @caesarxuchao @lavalamp

**Comment by JanetKuo** [comment]
We discussed about it in https://github.com/kubernetes/kubernetes/pull/14888#issuecomment-145713163. Assigning to @caesarxuchao.

**Comment by quinton-hoole** [comment]
Thanks @JanetKuo .  Removing team/control-plane, as team/CSI seem to have this in hand.

**Comment by caesarxuchao** [comment]
Aha, my PR was also hit by this flake just now. I'll try to fix this tmr.

**Comment by caesarxuchao** [comment]
`label` has the same problem. 
```
Error from server: replicationControllers "mock" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
!!! Error in hack/test-cmd.sh:788
  'kubectl label -f $file labeled=true "${kube_flags[@]}"' exited with status 1
```
