### ISSUE TITLE
Update get-kube.sh to not re-download the kubernetes archive if it hasn't changed

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#15197]
Currently, get-kube.sh unconditionally downloads 'kubernetes.tar.gz'.  It would be a nice optimization to skip re-downloading the file if it already exists locally with the same version/timestamp.

This should be possible using ```wget -N``` or ```curl -z```.

**Comment by roberthbailey** [comment]
Seems like a relatively easy fix. Want to send a PR? :)

**Comment by nagarjung** [comment]
@roberthbailey : Hi I would like to work on this issue, could you please this to me.

**Comment by roberthbailey** [comment]
Unfortunately github only allows you to assign issues to members of the kubernetes organization (see https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/). It doesn't seem like anyone is working on this at the moment so go ahead and treat your comment as a hold on the issue and I'll look for a PR.

**Comment by nagarjung** [comment]
Please hold on the issue

**Comment by nagarjung** [comment]
@roberthbailey : I would like to send a pull request for the above issue. I have tried maintaining a kubernetes tar ball on a standard directory and then use wget timestamping option to compare the changes in the local and the remote files. If this solution is fine please suggest me a standard directory where i can maintain tar ball. I have tested with /tmp. We can maintain in /urs/local by providing sudo permissions.  Also please look for a PR.

**Comment by jayunit100** [comment]
or maybe we can just maintain the tarball in ./ ?   That way there is no need to think about  writing to /tmp or /usr/local or whatever
