### ISSUE TITLE
Document how examples should be written and convert existing examples to the desired format

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15193]
Forked from #2841, https://github.com/kubernetes/kubernetes/issues/4926#issuecomment-78006098, #9399, #11361, #5465, and other issues.

We need to decide how we want examples to be written, document that, and make existing examples conform.

Issues:
* Decide objectives: teaching system concepts, demonstrating system features, getting started quickly with a particular application, providing sample configurations that can be extended by the user for real use cases, ...
* If teaching concepts or demonstrating features, which ones? How many examples need to illustrate the same concepts/features?
* What techniques do we want to use to make the examples engaging: interactivity, rewards, etc.?
* Does it need to be a realistic application configuration (e.g., HA)?
* Should the example demonstrate the application being used?
* System best practices
  * https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/config-best-practices.md
    * Show individual files and then combined files?
  * https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/pods.md#durability-of-pods-or-lack-thereof
    * Show singleton pods and then demonstrate why controllers are needed for self-healing?
  * Secret
* Cross references to other documentation (e.g., concept and feature documentation)
* Consistent organization (e.g., should the summary appear at the beginning or the end?)
* Keeping examples up to date with new features and evolving conventions
* Repo locations for text vs. config and code
* Whether/how to show multiple solutions (e.g., kubectl run and yaml)
* Shell command format (e.g., prompt or no prompt)
* kubectl output or not
* Screenshots
* How to make it possible to run examples without cloning the whole repo
* System addons that can be assumed (e.g., DNS)
* Examples that show the cluster being created and destroyed in addition to deploying the application
* Cloud-provider-specific examples vs. portable examples
* Unit and end-to-end testing of the examples

cc @aronchick

**Comment by bgrant0607** [comment]
There is overlap with the quick walkthrough:
https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/walkthrough

And with the detailed walkthrough:
https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide#thorough-walkthrough

**Comment by linzichang** [comment]
+1
This is very meaningful. #11361 can make the examples more clear and usable. But can't unify patten, describe and section very well.

**Comment by bgrant0607** [comment]
@mansoorj @jeffmendoza @RichieEscarez @MikeJeffrey 

Reworking guestbook: #14256

**Comment by bgrant0607** [comment]
cc @amygdala

**Comment by bgrant0607** [comment]
For inspiration: 
https://docs.docker.com/mac/step_three/
https://www.youtube.com/watch?v=zRGRJRUWafY&t=25&authuser=0

**Comment by bgrant0607** [comment]
We've decided to separate tutorials from canned applications -- the latter is covered by #17027.

**Comment by bgrant0607** [comment]
Interactive demos: https://github.com/thockin/kube-demos

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by bgrant0607** [comment]
Quick thoughts:
* Should point to documentation of prerequisites
  * Create a cluster (e.g., single-node docker)
  * Setup kubectl
* Should point to documentation on first mention: pods, kubectl, etc.
* Should have a "this is what you'll learn" section at beginning
* Should have a section suggesting what to look at next at the end
* Should have a section that brings up the app in the fewest number of commands (TL;DR / quickstart), ideally without cloning the repo (kubectl -f http:...)
* Most examples should be cloudprovider-independent (e.g., using PVCs, not PDs)
* We could have other examples with cloudprovider-specific bits somewhere else
* We should distinguish teaching examples, real app setups, tutorials, and demos (e.g., update demo or killing a node to demonstrate controller self-healing)
* Demonstrations of kubernetes features rather than apps belong in the user guide
* We shouldn't duplicate the thorough walkthrough

**Comment by bgrant0607** [comment]
And we should mark which examples are maintained vs not.

cc @kubernetes/examples

**Comment by bgrant0607** [comment]
I would like to see each app example actually show the app working -- output, ascii animations, or screenshots.

**Comment by bgrant0607** [comment]
The Openshift examples README does a decent job of explaining what each example demonstrates:
https://github.com/openshift/origin/tree/master/examples

**Comment by bgrant0607** [comment]
We should specify which release of Kubernetes is required and any other prerequisites, such as DNS, a cloudprovider with PV provisioning, a cloudprovider with external load balancers, etc. My current preference would be to point to general documentation about alternatives for those mechanisms rather than present the alternatives in each example.

**Comment by bgrant0607** [comment]
Guidelines are here:
https://github.com/kubernetes/kubernetes/blob/master/examples/guidelines.md
