### ISSUE TITLE
Display QoS class of pods in kubectl

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#15204]
Our current QoS policy is difficult to understand for an average user. We need to expose the QoS class of each container as part of kubectl to make it easier for users to reason system behavior. 
For example, with the new QoS policy, not setting memory limit (or request) could lead to more frequent deaths for containers if the cluster is overcommitted. 

This was suggested by @davidopp and @derekwaynecarr.

**Comment by bgrant0607** [comment]
Not happening for 1.1 AFAIK.

**Comment by hurf** [comment]
QoS Tier:
      cpu:              BestEffort
      memory:           BestEffort

is included in the outcome of describe pod. Do you mean something like `kubectl desribe qos BestEffort` and give users some detailed infomation about how system will react under 'BestEffort' policy?

**Comment by vishh** [comment]
This issue was opened in light of #14943. Since that has been shelved for the purposes of v1.1, this issue can definitely be punted for now.

**Comment by vishh** [comment]
I'm closing this issue for now. I will re-open if #14943 goes through.
