### ISSUE TITLE
/logs Kubelet endpoint does not work.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#15222]
When going to
```
https://XXX.XXX.XXX.XXX/api/v1/proxy/nodes/kubernetes-minion-cc6s/logs/kubelet.log
```

I'm getting `404: Page Not Found` response. Plain `logs/` correctly prints all *available* log files.

cc @dchen1107 @yujuhong @davidopp

**Comment by gmarek** [comment]
@dchen1107 please triage.

**Comment by lavalamp** [comment]
This worked the last time I tried it. Isn't there an e2e that tests this?

**Comment by yujuhong** [comment]
Not that I know of. #12811 seemed to be the last PR touching the endpoints. cc @vishh

**Comment by davidopp** [comment]
ping?

**Comment by dchen1107** [comment]
I don't think this is an issue at node. I believe kubectl proxy is broken for this.

**Comment by lavalamp** [comment]
@gmarek can you still reproduce this?

**Comment by gmarek** [comment]
Yup - every single time.

**Comment by yujuhong** [comment]
I don't think it's kube proxy that's broken because I got the same 404 error when accessing the endpoint directly on the node...

**Comment by gmarek** [comment]
OK, changing title of the issue - I didn't check kubelet directly.

**Comment by davidopp** [comment]
Does this mean 'kubectl get logs' is also broken?

**Comment by davidopp** [comment]
Sorry I mean 'kubectl logs'

**Comment by liggitt** [comment]
`kubectl log` doesn't hit `/logs/*` on the kubelet, it plumbs to `/containerLogs/...`

**Comment by dchen1107** [comment]
Yes, it only affects daemon's log, not container logs. 

I verified it after syncing to HEAD, and it is indeed broken at Kubelet level. Re-assign it back me.
