### ISSUE TITLE
Make it possible to create a cluster with more than 500 nodes in GCE

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#15226]
According to our documentation, maximal size of MIG is 500:
https://cloud.google.com/compute/docs/instance-groups/

This means, that it's currently impossible to create a cluster with more than 500 nodes in GCE using our scripts.
We should fix that by creating multiple MIGs from the same template in that situation.

cc @brendandburns @roberthbailey @fgrzadkowski

**Comment by wojtek-t** [comment]
BTW - if we add this support, we may consider making all MIGs no bigger than X (e.g. 50 nodes) which will significantly speed up cluster creation (because we will be creating those MIGs independently).

**Comment by roberthbailey** [comment]
Is the maximum size something that can be increased with a quota request?

**Comment by wojtek-t** [comment]
@roberthbailey - no. The limit is hardcoded in MIGs implementation (I've talked to MIG team in Warsaw about it, and it's NOT configurable now).

**Comment by roberthbailey** [comment]
Got it. I guess multiple-MIGs is the way to go.

**Comment by wojtek-t** [comment]
@roberthbailey - yet I think it will be the easiest way to do it (and I already checked that having e.g. 2 MIGs within a single cluster just works). So there should be just few changes in our startup scripts.

**Comment by bgrant0607** [comment]
+1 to multiple MIGs. We need to support heterogeneous clusters, anyway. 

Let's try to keep most of the code entirely oblivious to MIGs.

Somewhat relevant: #16199

**Comment by davidopp** [comment]
@fabioy Is there any update on this?
