### ISSUE TITLE
pkg/kubelet/network/cni/cni_test.go is flaky on shippable

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#15239]

**Comment by yujuhong** [comment]
cc author @dcbw from #14525

**Comment by dcbw** [comment]
This has a couple dupes, and we're trying to track debugging in https://github.com/kubernetes/kubernetes/pull/14983.  I can't reproduce on Shippable or locally with multiple machines, so I need to get some more debugging into the test so that others can get some logs.

**Comment by dcbw** [comment]
See also https://github.com/kubernetes/kubernetes/issues/14931

**Comment by yujuhong** [comment]
Closing as dup of #14931
