### ISSUE TITLE
e2e tests that run after reboot frequently fail with network connectivity problems

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#15243]
Context: kubernetes-e2e-gke-ci-reboot runs a small, stable set of tests along with the reboot tests to verify cluster functionality post-reboot. I've noticed tests that are normally stable, fail frequently when they run immediately after node reboot. examples:
[Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host](http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-ci-reboot/4433/)
[Kubectl client Guestbook application should create and stop a working application](http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-ci-reboot/4432/)
[Kubectl client Simple pod should support port-forward](http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-ci-reboot/4424/)

I think the issue here is that [waitForNodeToBeReady](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/util.go#L1828) is an insufficient signal that master/node connectivity is functional after the reboot. In particular, the ssh tunnel used by the proxy may not have been restored yet.

cc @jszczepkowski

**Comment by jlowdermilk** [comment]
After some investigation, and it turns out the flakiness is due to the delay when refreshing ssh tunnels, not the tests. The flakiness is only observed when running in a cluster that uses ssh tunnels (i.e. GKE). So fixing this is equivalent to making ssh tunnels better handle node reboot.

**Comment by jlowdermilk** [comment]
Unassigning, as I'm not actively working on this now.

**Comment by jlowdermilk** [comment]
Ref #12179. Fixing the 6minute ttl on proxy tunnels should (in theory) resolve this.

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by bowei** [comment]
Should probably close this issue as it is very broad.
