### ISSUE TITLE
Our pod/container-related docs are randomly organized

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15244]
In docs/user-guide/, we have:

pods.md
pod-states.md
containers.md
container-environment.md
environment-guide/
images.md
compute-resources.md
security-context.md
volumes.md
downward-api.md
downward-api/
liveness/
node-selection/
(and probably others I missed)

with a seemingly random distribution and organization of topics among the docs, with many gaps.

The API schema for pods/containers is yet somewhere else.

Environment variable expansion: docs/design/expansion.md

These are reference docs and examples.  

The corresponding walkthrough docs, which are reasonably organized, are:
configuring-containers.md
production-pods.md

We desperately need to organize and plug gaps in the documentation of this core primitive (pods, with containers and volumes).

cc @mansoorj

**Comment by bgrant0607** [comment]
cc @MikeJeffrey

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by bgrant0607** [comment]
Related: #16506

**Comment by bgrant0607** [comment]
Also related: #15741

**Comment by bgrant0607** [comment]
Adding more color, since we have a doc overhaul under way.

The primary doc doesn't say anything about how to actually use pods:
http://kubernetes.io/docs/user-guide/pods/

Try to find out to configure the command line and environment variables for your container. 

You might go back to Guides (Horizontal Nav), then User Guide (Vertical Nav), then Quick Walkthrough (in page), Pods (from TOC). Nope, sorry. Not there.

Ok, 201? Nope.

Ok, Thorough Walkthrough (nevermind the different vs. 201)? Configuring Common Parameters -- yes!
http://kubernetes.io/docs/user-guide/configuring-containers/

Does a search for "command line" on the site find that? Nope. It does find:
http://kubernetes.io/docs/user-guide/pods/single-container/

But no command line or env vars there. (Wait, why isn't this linked from the other pages...)

Is there a site map? Nope.

Ok, now how to do I set privileged mode...

Oh, and how about a diagram or two showing a pod with a container and volume, or multiple containers?

**Comment by bgrant0607** [comment]
Another issue:

Most users should create controllers rather than creating pods directly. We need to make the pod feature documentation discoverable from the controller documentation.

The pod template documentation should be substantially the same as pod documentation, except for update policy (most fields in pods can't be updated but most fields in templates can) and the operations.

Users will interact directly with pods in specific scenarios, though, (e.g., debugging) which we should also document.

**Comment by bgrant0607** [comment]
cc @kubernetes/docs

**Comment by bgrant0607** [comment]
cc @kelseyhightower

**Comment by bgrant0607** [comment]
A good doc on pod statuses (phase, reason, message, conditions, etc.) is clearly needed:

#17460
#18206
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/WVUtiCEgWQw/cQo2zFx9CAAJ

**Comment by bgrant0607** [comment]
Let's please separate spec and status documentation. This page documents probes, restartPolicy, and phase, and mentions conditions and containerStatuses:
http://kubernetes.io/docs/user-guide/pod-states/

**Comment by bgrant0607** [comment]
WIP doc proposal:
https://docs.google.com/document/d/12Nfj2E8tZL-CMnnpkSH9m5k_oqd4qJh4qDwYDxPGJJI/edit?ts=5705b1fc#bookmark=id.eb513gov0hg3

**Comment by bgrant0607** [comment]
Mocks:
https://docs.google.com/presentation/d/14mJwJGlwBJHIpMRGR-nYMSyyNk-kRpabyz74-YYXeTo/edit#slide=id.g12d21f53ed_2_11

**Comment by bgrant0607** [comment]
Copied from #562

Concept doc mocks:
https://docs.google.com/presentation/d/14mJwJGlwBJHIpMRGR-nYMSyyNk-kRpabyz74-YYXeTo/edit#slide=id.g12d21f53ed_0_6

We need an overview doc: what is it, when should it be used, required fields, commonly used fields, useful status, when to use something else (controllers, in this case). Some of this is in http://kubernetes.io/docs/user-guide/configuring-containers/

Pods are complicated enough that details will need to be pushed to other docs. For instance, status is covered by pod-states.

We need a kubectl overview: how to create, get, update, delete pods. Some of this is in:
http://kubernetes.io/docs/user-guide/configuring-containers/
http://kubernetes.io/docs/user-guide/pods/multi-container/

Though the latter needs to be fixed/updated. 

We could punt on command details pages for now.

More importantly, we need the individual feature pages:
* containers
  * images
    * imagePullPolicy
    * imagePullSecrets (and therefore Secrets)
  * command and args
  * env
    * env substitution
    * downward API, secrets, and configmaps
  * ports
  * lifecycle features
    * restartPolicy
    * probes
    * hooks
    * terminationGracePeriodSeconds
    * activeDeadlineSeconds 
    * termination message
* scheduling constraints
  * resource requests, limits, QoS
  * nodeSelector
  * new node and pod affinity / anti-affinity features
* serviceAccountName
* pod and container securityContext, and privileged
* hostNetwork/PID/IPC
* volumes
  * emptyDir and hostDir
  * downward API, secrets, and configmaps
  * persistent volume claims

Design motivations, best practices, and other misc. info could be moved to the deep dive:
https://docs.google.com/presentation/d/14mJwJGlwBJHIpMRGR-nYMSyyNk-kRpabyz74-YYXeTo/edit#slide=id.g12d21f53ed_2_2

We'll also need to be able to link to pod-related content from the controller docs. The main differences are in concrete operations and in update policies (very little is updatable in pods, but almost everything can be updated in pod templates).

Note that some content is still just in design docs, such as:
https://github.com/kubernetes/kubernetes/blob/master/docs/design/expansion.md

**Comment by pwittrock** [comment]
cc @pwittrock

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/kubernetes.github.io/issues/649

**Comment by bgrant0607** [comment]
Related blogs:
http://blog.kubernetes.io/2015/06/the-distributed-system-toolkit-patterns.html
http://blog.kubernetes.io/2016/06/container-design-patterns.html

**Comment by bgrant0607** [comment]
cc @devin-donnelly

**Comment by alexandercampbell** [comment]
Can we close this and reopen in the `community` repository? (or perhaps in kubernetes.io?)

**Comment by alexandercampbell** [comment]
I want this ticket, by the way.

**Comment by dims** [comment]
@alexandercampbell : i'd suggest going ahead with opening an issue in the other repository and let us know here, then one of us can close this out. thanks!

**Comment by alexandercampbell** [comment]
@dims I was looking at opening a new issue for this in `kubernetes.github.io` but there are already a [flood of issues](https://github.com/kubernetes/kubernetes.github.io/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20user-guide%20pod) on this topic, particularly https://github.com/kubernetes/kubernetes.github.io/issues/2621 and https://github.com/kubernetes/kubernetes.github.io/issues/2759.

Do you still think I should create a new issue?

**Comment by dims** [comment]
@alexandercampbell nope. as long the info is there and cross linked with this, we are good
