### ISSUE TITLE
v1.List: should not use []RawExtension

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#15266]
RawExtension is intended for use where you have a two-phase unpacking, or want to pass arbitrary objects around.

v1.List should have _only_ v1 objects in it, and therefore can be unpacked in 1 pass; you don't have to defer the understanding of the object.

We need an object that is similar to RawExtension, but contains an internal runtime.Object, guaranteed to be a v1 object. It should be convertable, so conversions between v1.List and api.List types should work.

**Comment by smarterclayton** [comment]
This is incorrect :)  It needs to deal with things that have never been seen.
