### ISSUE TITLE
The  second-level on-wire precision of unversioned.Time is too low

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#15262]
When marshing unversioned.Time to JSON/YAML, the precision decreases to second-level, which is too low, i.e.,
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/unversioned/time.go#L105
```
json.Marshal(t.UTC().Format(time.RFC3339))
```

We need to use RFC3339Nano instead, which keeps the nanosecond-level precision.

@bgrant0607 @saad-ali

**Comment by lavalamp** [comment]
why is this a problem? I cannot recall now what it was, but there was a reason for the original choice.

**Comment by saad-ali** [comment]
For sorting events that happen in rapid succession

**Comment by bgrant0607** [comment]
Was a concrete problem reported by users? How did we notice this?

**Comment by caesarxuchao** [comment]
No, there's no user reported problems.

I noticed it when modifying event_test.go. The test reports error on `event` having identical FirstTimestamp and  LastTimestamp but Count great than 1. I think such `event` will cause confusion among end users as well.

@saad-ali, will the low accuracy cause more serious problems in real life?

**Comment by saad-ali** [comment]
> @saad-ali, will the low accuracy cause more serious problems in real life?

I can imagine a set of events being generated in rapid succession, and an accuracy of 1 second is not enough for a consumer to properly sort them. Annoying, great if we can fix it, but not the end of the world if we can't.

**Comment by bgrant0607** [comment]
Even with finer granularity timestamps, events couldn't be ordered across hosts and perhaps not even across cpu sockets within a single host.

**Comment by caesarxuchao** [comment]
Close this issue as the timestamp accuracy hasn't caused any problem.
