### ISSUE TITLE
Allow for controlling whether a load balancer's IP address should be deleted

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#15261]
We allow for attaching a specific IP address to a load balancer (#10323), but when that load balancer is deleted, we also delete the IP address. It's likely there are cases out there where the user would like to keep the IP address. Opening this mostly to see if anyone cares about it or if we should just leave things as is.

**Comment by thockin** [comment]
For now that's something they can manage outside of kubernetes.  I want to
be extra wary of things that we know not all providers offer..

**Comment by a-robinson** [comment]
SGTM. Closing for now.
