### ISSUE TITLE
Monitor repository for commits without pull request/review

### ISSUE THREAD

**Issue by stephenR** [kubernetes/kubernetes#15294]
Quoting @roberthbailey:
"We have a policy that code should be reviewed and pushed via pull requests, but there isn't anything that enforces this or enforces that a maintainer can't merge their own pull requests (and this happens sometimes when the build cop is trying to fix the build)."

If we can't enforce this, we should at least have a way to detect such commits. Can we build a monitor that alerts us if someone tries to do this?

**Comment by stephenR** [comment]
cc: @quinton-hoole

**Comment by quinton-hoole** [comment]
Labelled as team/test-infra even though it doesn't really fall under that.  
The new buildcop rotation "team" should take ownership of this, but we don't have that team formalized yet.  Will discuss internally and come up with a plan.

**Comment by ixdy** [comment]
Maybe this is something we can put into the munger? @brendandburns @pmorie

**Comment by quinton-hoole** [comment]
Unassigning myself, and leaving to the @kubernetes/goog-testing to triage.
