### ISSUE TITLE
rbd plugin keeps remounting volumes every 10s and mount hangs there.

### ISSUE THREAD

**Issue by changx** [kubernetes/kubernetes#15291]
mount hangs with `D` state

```
32713 ?        Sl     0:35 /opt/bin/kubelet --address=0.0.0.0 --port=10250 --hostname_override=10.3.1.3 --api_servers=http://10.3.1.5:8080 --cluster_dns=192.168.3.254
 3428 ?        D      0:00  \_ mount -o remount,rw /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/rbd-image-pv100g-1 /var/lib/kubelet/pods/b6c2e9a9-6d8c-11e5-8288-525
 3434 ?        D      0:00  \_ mount -o remount,rw /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/rbd-image-pv100g-6 /var/lib/kubelet/pods/cd697576-6d8c-11e5-8288-525
```

It looks like kubelet remount volumes to make sure the volume mounted correctly ? 

I've to reboot the host if mount hangs there because all I/Os were blocked on that volume.

kubernetes v1.0.1 with ceph 0.94.2

**Comment by thockin** [comment]
@rootfs

**Comment by rootfs** [comment]
kubelet remounts rbd volume to ensure rw/ro is correctly done, as part of the setup process. 
I am not able to run into this situation. Any trace we can look at?  @changx

**Comment by changx** [comment]
I can not reproduce the problem in the past 30 days, this issue could be closed.
