### ISSUE TITLE
6 of the last 12 kubernetes-build jenkins runs have failed

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#15308]
[Marking this as team/test-infra since there isn't a release team yet]

@quinton-hoole @ixdy 

We currently have a 50% success rate building k8s.

**Comment by roberthbailey** [comment]
Relevant log lines from the 6 failed builds:

```
04:15:24 !!! [1008 04:15:24] Expected contents of file to be v1.2.0-alpha.1.644+726f1e17c4ef9c-dirty, but got v1.2.0-alpha.1.640+d9a392790aa453-dirty
04:42:11 !!! [1008 04:42:11] Expected contents of file to be v1.2.0-alpha.1.650+f754f05bd6764b-dirty, but got v1.2.0-alpha.1.631+674e8212f683d3-dirty
06:10:25 !!! [1008 06:10:25] Expected contents of file to be v1.2.0-alpha.1.656+30ad675fa1d04b-dirty, but got v1.2.0-alpha.1.654+0129dadc666c07-dirty
07:17:18 !!! [1008 07:17:18] Expected contents of file to be v1.2.0-alpha.1.660+46441a6657e1e1-dirty, but got v1.2.0-alpha.1.658+23b0cb3d0a635c-dirty
07:48:48 !!! [1008 07:48:48] Expected contents of file to be v1.2.0-alpha.1.662+731a47bc94dc99-dirty, but got v1.2.0-alpha.1.658+23b0cb3d0a635c-dirty
09:19:33 !!! [1008 09:19:33] Expected contents of file to be v1.2.0-alpha.1.664+036fe1684973f3-dirty, but got v1.2.0-alpha.1.662+731a47bc94dc99-dirty
```

It looks like this is a problem with our build script rather than the build itself.

**Comment by roberthbailey** [comment]
The preceding log line (in all cases) is:

```
Validating uploaded version file at https://storage.googleapis.com/kubernetes-release/ci/latest.txt
```

**Comment by ihmccreery** [comment]
This is my fault: #14959 adds logic to validate that an upload of `latest.txt` succeeded, but it seems to be hitting either a consistency problem or a race condition because we're hammering that file so much.  However, [GCS uploads are strongly, globally consistent](https://cloud.google.com/storage/docs/concepts-techniques?hl=en#consistency), including for overwrites, so consistency shouldn't be the issue, unless there's some caching layer we're missing.

Investigating.

**Comment by ihmccreery** [comment]
From the same GCS docs:

> Because we allow you to specify cache control for publicly-readable objects, cached objects that are publicly readable might not exhibit strong consistency. If you cache an object, and the object is in the cache when it is updated or deleted, the cached object will not be updated or deleted until its cache lifetime expires. The cache lifetime is defined by the Cache-Control request header, which you can specify when you upload an object. So ultimately, you can control the degree to which cached objects are consistent.

Investigating further.

**Comment by ihmccreery** [comment]
We're going to add a no-cache metadata to the objects, and that should solve the problem.
