### ISSUE TITLE
Ensure that skydns does not round robin between nameservers

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#15303]
Not all nameservers are equal and we need to ensure that skydns can be prevented from round-robining between the nameservers.

the round-robin is the cause of a large % of dns queries failures on mesos-k8s.

https://github.com/kubernetes/kubernetes/issues/14394#issuecomment-146352431

**Comment by ArtfulCoder** [comment]
https://github.com/skynetservices/skydns/pull/231

**Comment by ArtfulCoder** [comment]
We will need to pick up a new skydns release that addresses all the bug fixes.

**Comment by smarterclayton** [comment]
@ramr @sosiouxme we'll want to allow this to be disabled in Openshift as well via a config flag.

**Comment by ArtfulCoder** [comment]
didnt you use skydns in norec mode ?
you wont hit the bug in norec mode.

**Comment by smarterclayton** [comment]
I think someone asked us recently to allow forwarding via config, just want
to be sure we don't miss this if we do.

On Oct 8, 2015, at 4:49 PM, Abhi Shah <notifications@github.com> wrote:

didnt you use skydns in norec mode ?
you wont hit the bug in norec mode.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15303#issuecomment-146681093>
.

**Comment by karlkfi** [comment]
The flag is set in the kube-dns addon replication controller.
For DCOS we're using sed to process the salt pillar files and deploying them manually.
I don't know how you're deploying them on OpenShift.

**Comment by smarterclayton** [comment]
We run DNS with the master and serve DNS directly from the service rest
API, instead of keeping a separate etcd.  Solly has an open to implement
DNS in the Kube proxy (it uses the same data set as a proxy).

On Oct 8, 2015, at 7:16 PM, Karl Isenberg <notifications@github.com> wrote:

The flag is set in the kube-dns addon replication controller.
For DCOS we're using sed to process the salt pillar files and deploying
them manually.
I don't know how you're deploying them on OpenShift.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15303#issuecomment-146713667>
.

**Comment by karlkfi** [comment]
This change will only affect the cluster addon DNS replication controller template. If you don't use that, then you won't be affected. 

Even if you do use it, this only affects you if your using recursion delegating to multiple other nameservers.

**Comment by ArtfulCoder** [comment]
@miekg asked why we didn't want round robin. https://github.com/skynetservices/skydns/pull/231#discussion_r41601408

It is a valid question 
We should not be specifying more than 1 nameserver if we don't want round robin. It would leads to issues like: SkyDNS goes to the first NS, which fails. Then SkyDNS still go to the second one, causing SkyDNS to propagate NXDOMAIN instead of SERVFAIL or something..

@karlkfi for the mesos-k8s use case, can you have skydns just use 1 nameserver ?

@thockin In Kubernetes, for the ClusterFirst dnsPolicy, should we specify only the skydns nameserver ?
We could run multiple instances of it for availability.

I think we should either use skydns in no-rec mode, or only specify it as the only NS for clients in /etc/resolv.conf

**Comment by sosiouxme** [comment]
I would agree with the two options, and further note that the norec mode is a required ability. We do not want admins to have to deploy open resolvers, or even do so by default. If they know what they're doing then having an option to deploy it as the only, recursing nameserver for clients would be ideal.

**Comment by ArtfulCoder** [comment]
As an added functionality in skydns, we could still have a rotate flag, just the way, /etc/resolv.conf has a rotate flag which specifies whether to  round-robin between servers or not.

It would play out as follows:
 i. skydns in no-rec mode: nothing to be done. client will respect the RES_ROTATE value of /etc/resolv.conf. Responsibility lies on the resolver client. The to-be-added-ROTATE flag in skydns would have no impact.

ii. For skydns in rec mode:  for clients of skydns, skydns would be the only NS. 
Skydns in-turn should respect the RES_ROTATE flag from etc/resolv.conf or respect a to-be-added-ROTATE flag that configures skydns to either round-robin or not between its nameservers. This would thus somewhat preserve the behaviour that clients were used to, before skydns replaced those Nameservers and become the only NS.

**Comment by thockin** [comment]
> we should either use skydns in no-rec mode, or only specify it as the
only NS for clients in /etc/resolv.conf

This seems reasonable to me.  It's a change with a fair amount of impact,
so we should consider it carefully.

**Comment by karlkfi** [comment]
Does `no-rec` mode return NXDOMAIN or some other response that makes the client continue down the list?

**Comment by thockin** [comment]
SERVFAIL

**Comment by sosiouxme** [comment]
DENIED, actually.
