### ISSUE TITLE
Deployment: requirements for graduation to "beta"

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15313]
Before Deployment graduates from experimental:
* It needs to implement a status subresource
* It needs to adopt the more general selector, as discussed in #341. This would be very hard to change later.
* The name needs to be finalized

cc @nikhiljindal @ironcladlou @ghodss

**Comment by erictune** [comment]
IIUC, These are requirements for Deployment to graduate to  default-on, a.k.a "beta".

**Comment by nikhiljindal** [comment]
IIUC. these are requirements for enabling deployments by default on HEAD as well, right?
cc @lavalamp

**Comment by lavalamp** [comment]
@nikhiljindal No-- IMO we can and should turn it on on HEAD as long as it's not destabilizing anything.

**Comment by lavalamp** [comment]
Also the e2e tests need to auto-discover whether the API is on and short-circuit if not, so that there's only one knob to flip.

**Comment by bgrant0607** [comment]
Copying note from https://github.com/kubernetes/kubernetes/pull/19686/files#r51005929

We should change DefaultDeploymentUniqueLabelKey to "pod-template-hash" (all lowercase, no prefix).

**Comment by bgrant0607** [comment]
We should copy all Deployment annotations to the RC of the latest revision in order to capture them in the revision history.

**Comment by bgrant0607** [comment]
Other issues that need to be resolved:
#20290
#19111
#17164
#18078
#16737
#3024
#20087

The API also needs to be enabled by default.

**Comment by bgrant0607** [comment]
In flight:
* ReplicaSet (like ReplicationController, but with the generalized selector)
* Pause and resume #20087
* Rollback/undo #19686, #19835
* Scale subresource #19802
* stop #18077
* revision info #19581
* rollout history #19893, #20035

Not done yet:
* make deployment the default in kubectl run
* Doc updates

Not going to make it in 1.2:
* Perm-fail and kubectl rollout retry
* kubectl set image
* watch rollout status in kubectl
* kubectl set env, commands, args

**Comment by bgrant0607** [comment]
Specifically, the user guide needs to be updated.
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/deployments.md

**Comment by janetkuo** [comment]
From @roberthbailey: We should move it to beta soon so that we can start testing it in the gke e2e tests at head.

**Comment by janetkuo** [comment]
> We should copy all Deployment annotations to the RC of the latest revision in order to capture them in the revision history.

This feature will be added in #20035

**Comment by janetkuo** [comment]
Filed #20517 to enable deployments by default, enable deployments in `kubectl run`, and update related docs/scripts.

**Comment by madhusudancs** [comment]
Remove the defaulting behavior that defaults RC labels and Deployment selector to pod template labels in order to be consistent with Job's defaulting behavior.

cc @bgrant0607 @janetkuo @erictune

**Comment by bgrant0607** [comment]
Note that we're waiting for the API to stabilize before enabling Deployment by default: label selector (change to new selector and ReplicaSet), MinReadySeconds (move to DeploymentSpec), uniqueLabelKey (rename to templateHashLabelKey), and the defaulting behavior (mentioned above) at least need to be in their intended states for v1beta1.

**Comment by bgrant0607** [comment]
We've decided not to change the selector and label defaulting behavior in v1beta1.

We're still waiting on scale, stop, and some replicaset features.

I'd like to enable scaling of paused deployments, but we won't block on that.

**Comment by bgrant0607** [comment]
Just waiting on /scale.
