### ISSUE TITLE
Scale subresource graduation requirements

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15311]
Before Scale graduates from experimental:
* It needs to adopt the more general selector, as discussed in #341. This would be very hard to change later.

Will update this issue after I take a closer look.

cc @fgrzadkowski @jszczepkowski

**Comment by bgrant0607** [comment]
cc @davidopp

**Comment by derekwaynecarr** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by jszczepkowski** [comment]
> It needs to adopt the more general selector, as discussed in #341. This would be very hard to change later.

@bgrant0607 Is it really needed for beta? AFAIU, we are currently using the same selector as replication controller. Introducing more generalized selector will require modifications in stable replication controller API. So, additional modifications in scale sub-resource should not make thinks much worse.

**Comment by bgrant0607** [comment]
At what API path is scale accessed?

We might want to rename the Scale Go types if we're going to create new, incompatible types to be used with the new controllers, such as Deployment.

**Comment by jszczepkowski** [comment]
> At what API path is scale accessed?

Currently, scale is under apis/extensions/v1beta1/replicationcontrollers/scale
and apis/extensions/v1beta1/deployments/scale, replicationcontrollers under extensions are just a dummy, with only scale sub-resource implemented.

**Comment by bgrant0607** [comment]
We should change the selector representation to the string form. See also my comment here: https://github.com/kubernetes/kubernetes/pull/15350#discussion_r41659046

**Comment by bgrant0607** [comment]
And here: https://github.com/kubernetes/kubernetes/issues/3676#issuecomment-147524114

**Comment by bgrant0607** [comment]
Actually, it probably needs to be an array of strings, due to the way Deployment works.

**Comment by bgrant0607** [comment]
The comments on ScaleSpec and ScaleStatus need to be rewritten to be more generic. They were just copied from ReplicationControllerSpec/Status.

**Comment by bgrant0607** [comment]
Other than fixing the comments, I'm ok with leaving scale as is. We should document that we expect it to change significantly in a future API version. The other alternative would be to leave the scale API for ReplicationController as is, and create a totally new type definition for Deployment and for the replacement for ReplicationController. The autoscaler could either support both API schemas, or only support the new controllers, esp. since we expect Deployment to be the primary target.

**Comment by bgrant0607** [comment]
Moved to 1.2.

**Comment by bgrant0607** [comment]
Since we decided not to make major changes for 1.1.

**Comment by davidopp** [comment]
Just curious, what's wrong with the current scale subresource? Just the fact that it uses the old type of selector in the status?

**Comment by jszczepkowski** [comment]
> Moved to 1.2.

I'm bit confused. Horizontal Pod Autoscaler was graduated to beta in 1.1. Scale sub-resource is required for HPA to work, as is a part of HPA API. So, I guess scale sub-resource should be also in beta in 1.1?

**Comment by fgrzadkowski** [comment]
Isn't it that we have fixed remaining issues with scale subresource? (#15706)
