### ISSUE TITLE
Fix imported package names to not use mixedCaps

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#15319]
Forked from #15200

@smarterclayton pointed out that all package names should be lower case, no under_scores or
mixedCaps. The same rule applies to renaming imported packages.
(https://blog.golang.org/package-names)

@timstclair generated a list of mixedCaps package names in our codebase: https://gist.github.com/timstclair/d63aac28d4201cf0c0f0

I will upload a PR later to rename kubeletTypes to kubetypes, and the rest is up for grabs.

**Comment by zhengguoyong** [comment]
sorry i have not saw this issue as i open a similar one(#15594),
do you mind i participate in this issue?  i would happy to do some work for this.
best regards. 
@yujuhong

**Comment by yujuhong** [comment]
@zhengguoyong, of course, fixes are welcome. Thanks for picking up on this!

We'll try to expedite the review and merge process of such PRs to avoid a lot of churns, but chances are that some rebases are needed :)

**Comment by zhengguoyong** [comment]
ok, i will send some fix sonner, and tag you for review.
thanks again.
@yujuhong

**Comment by timstclair** [comment]
Not done: https://gist.github.com/timstclair/575b0fb0071603d632bc
