### ISSUE TITLE
[RFC] improve `kubectl annotate` and `kubectl label` to increase success rate

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#15333]
`kubectl label` and `kubectl annotate` work in this pattern: first issuing a "GET" to the API server to retrieve the latest object, then adding the label/annotation to the object, and finally issuing an "PUT" with the modified object. The request will fail if the object stored in the server has been updated between the "GET" and "PUT", even if the update has no conflict with the label/annotate request. In such cases, instead of returning an error, `kubectl` should retry without disturbing the end user.

There are two ways to implement this:

1. retry in kubectl: simply retry the label/annotate process several times if the server rejected the request because the object has been updated. The only exception is when the `--resource-version` [precondition](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/annotate.go#L52) is set, then kubectl shouldn't retry.

2. use the strategicMergePatch instead of calling Update at client-side. PATCH is more robust because PATCH does the "get, modify, update" in the server-side, so there is less chance to have a conflict, and PATCH will retry at the server-side (see #14758). We need to make some adaptions though:

* kubectl annotate/label has the `--overwrite` [flag](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/annotate.go#L51), when it's false, kubectl should retrieve the latest object to confirm there is no existing annotation/label of the same key, and then proceed with issuing the patch.

* if the `--resource-version` [flag](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/annotate.go#L52) is set, ~~we should fall back to the current behavior, because PATCH doesn't support the resource-version precondition.~~ [UPDATE:] we just need to specify the resourVersion in the patch, then it will be treated as a precondition by the UpdateResource() handler in the API server.

I plan to take the first approach as an immediate fix.

@JanetKuo @bgrant0607 @lavalamp

**Comment by bgrant0607** [comment]
Immediate need is to fix the flaky e2e test AIUI.

**Comment by caesarxuchao** [comment]
e2e? do we have an issue out there?

#15325 is an immediate fix to the flake in test-cmd.sh

**Comment by bgrant0607** [comment]
If this is for 1.1, it needs to be P0 at this point. Should it be?

**Comment by bprashanth** [comment]
Fwiw I use annotations both from cmd line as an admin and from scripts, to experiment with loadbalancer settings. In the case of the former, I've never really had a collision, and in the case of the latter my scripts know how to retry like we retry all other updates.

**Comment by caesarxuchao** [comment]
Thank you @bprashanth. When used in scripts, the annotate and label commands have collisions frequently, e.g. in the test-cmd.sh, see #15181. IMO, we shouldn't require users to retry in their scripts if we know there is a simple way to avoid the collisions.

Anyway, #15597 and #15651 are sent to fix this.
