### ISSUE TITLE
Stop the API pages from overriding the nav menu font and color

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#15343]
**Issue:**
When clicking on either of the API pages ([Operations](http://kubernetes.io/v1.0/docs/api-reference/operations.html) or [Definitions](http://kubernetes.io/v1.0/docs/api-reference/definitions.html)), the font and color of the navigation menu incorrectly change and you cannot visually tell what topic you are in. 

**Possible solution:**
We need to stop those API pages from overriding our site's font and color by removing those lines of CSS from the source .html files.

**Examples:**
Here is our sites font and color (how it should display - the parent topic is selected and highlighted blue):
![image](https://cloud.githubusercontent.com/assets/11762685/10383561/61cb9364-6de5-11e5-9e93-82f3665db045.png)

But when you click [Operations](http://kubernetes.io/v1.0/docs/api-reference/operations.html) or [Definitions](http://kubernetes.io/v1.0/docs/api-reference/definitions.html), the font and color change (here you cannot tell that "Definitions" is selected):
![image](https://cloud.githubusercontent.com/assets/11762685/10383594/ea443bb0-6de5-11e5-89bb-5dd0997922b1.png)

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by chenopis** [comment]
I don't think this is true anymore.
/close
