### ISSUE TITLE
Is the shippable console logs not accessable?

### ISSUE THREAD

**Issue by linzichang** [kubernetes/kubernetes#15347]
When I visit the shippable test details, I got the this error:
`{"id":1005,"message":"Internal API Error : getPermissionByProjectId","methodName":"caller:55dbcdd11895ca44740f803f|buildGroupConsoles|5613cb2748a5950d00b6e7e6chkPermForBuildGroupId|_getPermissionsByProjectId"}`

**Comment by roberthbailey** [comment]
Is this for https://github.com/kubernetes/kubernetes/pull/14256? When I click the link I go to https://app.shippable.com/builds/5616258a40e9120b00c5f8cd which shows the logs. It sounds like you may want to file an issue with the shippable folks.

**Comment by linzichang** [comment]
It's ok now. Maybe shippable had some errors yesterday.
