### ISSUE TITLE
A verify script should check that fields have JSON tags set

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#15345]
Currently in `pkg/api/types.go` the `SecurityContext.RunAsUser` field lacks a JSON tag.  We should have a verify script that checks for this.  Perhaps we can rename the `verify-description.sh` script to `verify-field.sh` and check that both:
1.  Each appropriate field has a JSON tag
2.  Those tags never contain descriptions

**Comment by kargakis** [comment]
@kubernetes/sig-contributor-experience-misc 
@kubernetes/sig-api-machinery-misc 
@kubernetes/sig-testing-misc

**Comment by bgrant0607** [comment]
cc @mbohlool 

/remove-lifecycle stale
/lifecycle froze

**Comment by sttts** [comment]
After we had such a case some days ago for the 1.11 release. What is the current status? Do we have such a script, but only miss to check some files named differently to `types.go`?

**Comment by lavalamp** [comment]
https://github.com/kubernetes/kube-openapi/pull/83

Should fix this

**Comment by lavalamp** [comment]
cc @roycaihw

**Comment by apelisse** [comment]
@roycaihw is this fixed? Can we close it? Thanks
