### ISSUE TITLE
Remove FakeClient and embed etcd for unit-testing.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#15349]
Per discussions in the @kubernetes/sig-scalability we all agreed that it would be better for the code base to run the UT's against an embedded etcd, per recommendation from @lavalamp.

**Comment by jayunit100** [comment]
Good idea, Fake client was pretty confusing to me originally and agree,
especially given the semantic dependencies mentioned before, running etcd directly as part of tests might be very useful.

**Comment by timothysc** [comment]
This will likely be broken up into a series of commits, to migrate the tests off the existing clients, and close once we have removed the fake client entirely.

**Comment by timothysc** [comment]
Per discussion on the sig, fan out on replacement can now take place the main changes are in and others who wish to jump in, it would be helpful.  Care should be taken to only use the storage layer and eliminate any dependencies on 

- [ ] pkg/storage/cacher_test.go
- [ ] pkg/registry/node/etcd/etcd_test.go
- [ ] pkg/registry/namespace/etcd/etcd_test.go
- [ ] pkg/registry/limitrange/etcd/etcd_test.go
- [ ] pkg/registry/daemonset/etcd/etcd_test.go
- [ ] pkg/registry/secret/etcd/etcd_test.go
- [ ] pkg/registry/podtemplate/etcd/etcd_test.go
- [ ] pkg/registry/service/ipallocator/etcd/etcd_test.go
- [ ] pkg/registry/service/etcd/etcd_test.go
- [ ] pkg/registry/service/allocator/etcd/etcd_test.go
- [ ] pkg/registry/endpoint/etcd/etcd_test.go
- [ ] pkg/registry/resourcequota/etcd/etcd_test.go
- [ ] pkg/registry/deployment/etcd/etcd_test.go
- [ ] pkg/registry/thirdpartyresourcedata/etcd/etcd_test.go
- [ ] pkg/registry/persistentvolume/etcd/etcd_test.go
- [ ] pkg/registry/generic/etcd/etcd_test.go
- [ ] pkg/registry/experimental/controller/etcd/etcd_test.go
- [ ] pkg/registry/thirdpartyresource/etcd/etcd_test.go
- [ ] pkg/registry/persistentvolumeclaim/etcd/etcd_test.go
- [ ] pkg/registry/event/etcd/etcd_test.go
- [ ] pkg/registry/pod/etcd/etcd_test.go
- [ ] pkg/registry/job/etcd/etcd_test.go
- [ ] pkg/registry/registrytest/etcd.go
- [ ] pkg/registry/horizontalpodautoscaler/etcd/etcd_test.go
- [ ] pkg/registry/serviceaccount/etcd/etcd_test.go
- [ ] pkg/registry/controller/etcd/etcd_test.go
- [ ] pkg/registry/ingress/etcd/etcd_test.go
- [ ] pkg/kubelet/dockertools/docker_test.go
- [ ] pkg/master/master_test.go
- [ ] pkg/client/unversioned/testclient/testclient.go
- [ ] pkg/client/unversioned/helper_blackbox_test.go
- [ ] pkg/kubectl/cmd/cmd_test.go
- [ ] pkg/kubectl/rolling_updater_test.go
- [ ] pkg/kubectl/resource/builder_test.go
- [ ] pkg/controller/podautoscaler/horizontal_test.go
- [ ] pkg/controller/podautoscaler/metrics/metrics_client_test.go
- [ ] pkg/controller/replication/replication_controller_test.go

/cc @kubernetes/sig-scalability @wojtek-t @quinton-hoole

**Comment by wojtek-t** [comment]
@timothysc : I will look into cacher_test.go (since I wrote this test).

**Comment by wojtek-t** [comment]
A bunch of things on the above list are unrelated (e.g. pkg/controller/replication/replication_controller_test.go is using non-etcd related FakeClient).

When looking into the code now, it seems that there are 3 things to be done:
- [ ] contrib/mesos/pkg/election/etcd_master_test.go
- [ ] pkg/master/master_test.go
- [ ] pkg/registry/*/etcd/etcd_test.go (and all of them are exactly the same thing, which is fixing pkg/registry/registrytest/etcd.go)

@timothysc - are you already working on any of those?

**Comment by timothysc** [comment]
@wojtek-t I'm working on 'pkg/registry/*/etcd/etcd_test.go'

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/17057 is removing the usage from mesos tests.

**Comment by timothysc** [comment]
#17469 is the entire registry.

**Comment by timothysc** [comment]
Upon merge of #15349 we can close this.

**Comment by timothysc** [comment]
Done!
