### ISSUE TITLE
kubernetes service

### ISSUE THREAD

**Issue by taozix** [kubernetes/kubernetes#15358]
A cluster created like this:
[root@docker0 yaml]# kubectl get no
NAME         LABELS                              STATUS
10.0.0.207   kubernetes.io/hostname=10.0.0.207   Ready
10.0.0.208   kubernetes.io/hostname=10.0.0.208   Ready
10.0.0.216   kubernetes.io/hostname=10.0.0.216   Ready

[root@docker0 yaml]# kubectl get po -o wide 
NAME                         READY     STATUS    RESTARTS   AGE       NODE
centosphp-controller-n34zz   1/1       Running   0          3h        10.0.0.208
centosphp-controller-v5x6p   1/1       Running   0          3h        10.0.0.207

[root@docker0 yaml]# kubectl get svc
NAME            LABELS                                    SELECTOR           IP(S)           PORT(S)
cphp-nodeport   <none>                                    name=centosphpok   10.254.35.247   8000/TCP
kubernetes      component=apiserver,provider=kubernetes   <none>             10.254.0.1      443/TCP

[root@docker0 yaml]# kubectl describe svc cphp-nodeport
Name:			cphp-nodeport
Namespace:		default
Labels:			<none>
Selector:		name=centosphpok
Type:			NodePort
IP:			10.254.35.247
Port:			<unnamed>	8000/TCP
NodePort:		<unnamed>	31371/TCP
Endpoints:		172.17.0.1:80
Session Affinity:	None
No events.

Now the problem, try curl 10.254.35.247:8000 in node(10.0.0.207 & 10.0.0.208) is OK, but 10.0.0.216, it seems can not connect. any help?

**Comment by taozix** [comment]
when create the service, it print out:
You have exposed your service on an external port on all nodes in your
cluster.  If you want to expose this service to the external internet, you may
need to set up firewall rules for the service port(s) (tcp:31371) to serve traffic.

**Comment by hw-qiaolei** [comment]
@taozix for `NodePort` service you can access it either by: `<ClusterIP>:<Port>(within the cluster)`, or `<NodeIP>:<NodePort>(outside the cluster)`, so try: `curl 10.0.0.216:31371`

BTW, it is not suggested to ask usage problems here. Please move to [StackOverflow](http://stackoverflow.com/questions/tagged/kubernetes) or Slack. Please check with [troubleshooting](https://github.com/kubernetes/kubernetes/blob/master/docs/troubleshooting.md) for how to get help or ask questions, thanks.

**Comment by taozix** [comment]
thanks.
but curl 10.0.0.216:31371 & curl 10.0.0.207:31371 & curl 10.0.0.208:31371, all are failed.

**Comment by hw-qiaolei** [comment]
Hello,

some suggestions below:

1. make sure all your nodes' network connectivity is ok: `ping 10.0.0.207`, `ping 10.0.0.208`, `ping 10.0.0.216` from where you try to connect your service.
2. check if nodeport `31371` is opened on all nodes: `netstat -an | grep 31317`.
3. or use `telnet <node ip>:31371` to see if the nodeport `31371` on all nodes are accessible.

I have tested this before and it works for me.

**Comment by taozix** [comment]
HI,
telnet nodeIP:Port for all my three node are OK.
the node(curl 10.0.0.216:31371) can not be accessibile, and no pod run on this node.
and if I move one pod to node 10.0.0.216, then 10.0.0.216:31371 is OK.
so any relation with which node is running pod?
 thanks.

**Comment by hw-qiaolei** [comment]
Cross node pod connectivity needs a backend network, like `flannel` or `ovs`.
