### ISSUE TITLE
Consistently support graceful and immediate termination for all objects

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1535]
Issue discussed in #103, #1325, #1445, and other issues/PRs.

Our API isn't consistent on clean/graceful shutdown vs. immediate termination of our objects. We should support both modes, and in a consistent fashion. One mode should be the default, and the other should be available via a URL parameter on DELETE or custom verb (e.g., `/stop`, for graceful shutdown). Graceful shutdown should accept a timeout (as discussed in lifecycle hook PRs) and reason (#1462) as parameters.

Cleanly turning down a replication controller currently requires external orchestration: resizing it to 0 and waiting for pods to be deleted prior to deleting the replication controller itself. 

On the other hand, by default, individual pods are supposed to gracefully terminate, executing their PreStop handlers, SIGTERM handlers, and, in the future, PostStop handlers.

We should define what clean shutdown would mean for a service (wait for all targeted pods to be deleted?).

However, there are definitely occasions when one would not want graceful shutdown (e.g., shutting down a test deployment), and we should support that.

**Comment by derekwaynecarr** [comment]
Assuming we move forward with #3613, I would like to expose a pattern where I can effectively stop a Namespace, mark all of its content for deletion by some background controller, and then ultimately purge the Namespace resource.  Reading through this thread and others, it's not clear we have consensus on the right pattern for this across resources.  Is there a recommended pattern to follow that I can look to prototype?  I feel like I need a separate resource (NamespaceTermination) that I can post to kick off the proper workflow as I tend to agree that a DELETE should remain a true delete.

**Comment by derekwaynecarr** [comment]
The XxxTermination resource could be protected via a separate policy so it's not confused with traditional PUT.  Acceptance of the XxxTermination would toggle a Status field on the resource.  A controller would see the resource marked for termination and perform all required cleanup.  Upon completion, a client with proper Policy rights would send the DELETE to the Namespace resource.  A delete would be accepted iff the resource was in a Terminated status, and the final resource removal would complete.  In the interim, clients could do normal Get operations on the internal resources to track the purge to completion.  This seems like the general flow I would look to prototype this week.

**Comment by bgrant0607** [comment]
@derekwaynecarr My proposed approach was here: https://github.com/GoogleCloudPlatform/kubernetes/issues/1535#issuecomment-67680523. We may need to bikeshed about the names/paths, though. You could think of the "custom verb" as a synthetic control resource, such as XxxTermination.

I'm happy to have "stop" and "delete" be distinct. We can provide the ability to do both in a single operation in kubectl.

**Comment by bgrant0607** [comment]
Not directly related, but of interest may be Aurora's approach to graceful shutdown notification to the actual process:
http://aurora.incubator.apache.org/documentation/latest/user-guide/#user-content-http-health-checking-and-graceful-shutdown

We should document what we do, also (pre-stop hook, then docker stop).

**Comment by smarterclayton** [comment]
I like the idea of the abrt call right before the sigkill.  I wonder how many programs that makes worse (if you're about to get killed, what is the odds your abrt handler makes it worse?

**Comment by bgrant0607** [comment]
We have 2 notifications before kill now:
1. pre-stop hook
2. SIGTERM

The first notification is generally very graceful. For instance, a web frontend should start to fail readiness probes, but, in addition to completing in-flight requests, it should still serve any user requests received, so that load balancers redirect traffic, but users don't receive 500s. It shouldn't really shut down yet.

When the 2nd notification is sent, the server should flush logs, etc., and exit.

Aurora has 3 notifications. I'm not sure how useful that is. However, I will say that all (ex-)Googlers should recognize /quitquitquit and /abortabortabort. :-)

**Comment by smarterclayton** [comment]
I'm thinking of abrt behavior in Go, which is going to dump a stack trace of all the go routines, so you'll at least know where you were stuck when you would have gotten SIGKILL'ed.  I don't think it's necessarily worth the complexity now of course.

1. pre-stop hook
2. SIGTERM
3. wait for grace period to expire
4. SIGABRT ?
5. wait 1s
6. SIGKILL

The only question would be if sigabrt was worse than a straight sigkill in some libraries.

----- Original Message -----

**Comment by bgrant0607** [comment]
@derekwaynecarr

**Comment by smarterclayton** [comment]
Have started implementing this in #5085

**Comment by smarterclayton** [comment]
Ok, here's the rough design I'm going with (with various caveats):

1. Allow a Storage object to implement graceful deletion by implementing a new method `Delete(ctx api.Context, name string, options *api.DeleteOptions)`
2. DeleteOptions is a "simple" resource that has a single *int64 `GracePeriod` that is an optional time to delete the resource.  If GracePeriod is nil, the default value is used (which comes from the resource type and maybe even from the resource, once pods have a graceful shutdown value).  If GracePeriod is 0, termination is immediate (equivalent to current behavior)
3. The Storage object will check whether the object is already in the process of being deleted - a shorter GracePeriod will shorten the deletion timer, but a longer grace period will be ignored
4. If the grace period is > 0 and an existing shorter grace period is not pending, I will set the TTL on the etcd record.  This generates an Etcd watch event
5. The resource exposed by etcd will have a new metadata field set "metadata.deleteAt" or "metadata.deleteTimestamp" or something similar that indicates the time that the resource will be deleted at.
6. The kubelet would see the watch event on the pod and send a SIGTERM to the Docker container with a duration of "metadata.deleteAt - now" - Docker would then SIGKILL automatically
7. The kubelet would not start a pod that has deleteAt set (even if it dies)
8. At metadata.deleteAt the pod will be removed by etcd and the TTL, and a delete watch event is set

There is weirdness about removing the pod from the bindings, until the kubelet stops using bound pods we have an unclean setup.  It can be worked around in a way that isn't visible to end users though.

**Comment by smarterclayton** [comment]
All naming is on the table, this is just a first pass to get a rough code flow down so I know what needs to be fixed still.

**Comment by derekwaynecarr** [comment]
So I think this works for resources within a Namespace, but will not work for the Namespace itself.  I think that still requires a /stop style request to change the phase of a Namespace, a controller to use the support described here to graceful terminate content managed in the namespace, ability for other finalizers to report back they have completed their own clean-up, and then finally purge the Namespace itself.

So @smarterclayton approach sounds good, but I will still need to do something around Namespace lifecycle to ensure extended resources associated with Namespace have chance to delete.

Let's chat tomorrow.

**Comment by bgrant0607** [comment]
We need to finish this for replication controllers, and probably for services with external load balancers.

**Comment by smarterclayton** [comment]
And pods.  Now that the kubelet changes have slowed it should be easier to add that (that's what I held off on before).

**Comment by bgrant0607** [comment]
Another idea, based on #4245, #6393, #5842, Kubelet pod/container reconciliation, and a similar Borg feature:

We could add a general existence dependence -- an ObjectReference (or maybe list of them) which, if deleted, would also cause the object containing the reference to be deleted (level-based, not edge-based).

The ReplicationController could populate the reference by default, so that the pods would be deleted when their controller was deleted. We'd need to distinguish between an unspecified dependence (which would be populated by default) vs. explicitly no dependence(s), so that pods could be orphaned. 

This would make behavior of ReplicationController consistent with Pods and Services by default, without explicitly setting replicas to 0, and while still allowing pods to be orphaned en masse.

**Comment by thockin** [comment]
How do you orphan pods?  Run through and blank their DependentOn fields?

**Comment by bgrant0607** [comment]
If you did not plan from the start to orphan them, yes.

**Comment by thockin** [comment]
So we need another index of back-pointers, or we have another rectifier
loop that scans all pods or all objects for this condition?  It's more
general, but is it really simpler than just having the flag exist in the RC
as "KillChildrenOnDeletion" or something?

**Comment by bgrant0607** [comment]
Internally we use this to kill workers when their master is deleted, for instance.

I was also thinking about how to simplify object lifecycle for run-container (which may also spawn a service), deployment controllers, auto-scalers, separate pod templates, etc. These aren't all direct "children".

Also, if we put the flag/reference on the parent rather than on the children, then we need to ensure the parent stays around until all the children are deleted, as kubectl stop does.

Yes, if we put the reference on the children, then something needs to check it.

**Comment by derekwaynecarr** [comment]
@bgrant0607 interesting proposal.  Do you agree the parent-child relationship inferred by Namespace -> Pod,etc is too complex to follow this strategy?

**Comment by bgrant0607** [comment]
@derekwaynecarr Yes, I wouldn't convert namespaces to use such a strategy.

**Comment by bgrant0607** [comment]
While automation often wants to orphan pods of a replication controller, users seldom do. Another example of this: https://groups.google.com/forum/#!topic/google-containers/kEbZP_y1s3o. So, I think we do need to change the default delete behavior.

**Comment by bgrant0607** [comment]
I'd like to add a delete reason to DeleteOptions and to ObjectMeta: #1462.

**Comment by brendandburns** [comment]
@bgrant0607 says "Everything for 1.0 in this issue is done" so I'm removing from 1.0

**Comment by dchen1107** [comment]
subscribe myself

**Comment by smarterclayton** [comment]
The changes to apply the actual grace period are pretty small (so far).  Are we ok with landing the actual use of TerminationGracePeriodInSeconds for 1.0 if the impact to the RC / kubelet remain small?

**Comment by bgrant0607** [comment]
If the PR would land after tomorrow, then we need to discuss whether this should be in 1.0 at tomorrow's hangout or another one.

**Comment by smarterclayton** [comment]
The actual changes to the code are small and probably only some small debate.  The risk is the client behavior change (delete is immediate for pods now, vs with some delay).  

----- Original Message -----

**Comment by smarterclayton** [comment]
Pull is up at #8641 - appreciate eyes on.

**Comment by bgrant0607** [comment]
More cases where we want to clean up resources robustly:
1. Cloud load balancers after their corresponding services have been deleted: https://github.com/GoogleCloudPlatform/kubernetes/pull/5025#issuecomment-77381160
2. Terminated pods: #7660

**Comment by bgrant0607** [comment]
We need existence dependencies for cascading deletion in the server. Deployments generate ReplicaSets which generate Pods. Doing cleanup in the client will be fragile and unfriendly to non-kubectl clients.

cc @nikhiljindal @janetkuo @ironcladlou @ncdc

**Comment by bgrant0607** [comment]
Closing in favor of #19054, which is being implemented for 1.3.

**Comment by kargakis** [comment]
We have the garbage collector in place now but is there an umbrela issue or separate issues for making it work for all of the resources that need graceful deletion?

**Comment by kargakis** [comment]
> We have the garbage collector in place now but is there an umbrela issue or separate issues for making it work for all of the resources that need graceful deletion?

Maybe https://github.com/kubernetes/kubernetes/issues/26120?
