### ISSUE TITLE
e2e failure: "Deployment deployment should scale up and down in the right order" is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#15369]
I've seen few failure like this today:

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:40
Expected
    <int>: 1
to equal
    <int>: 2

cc @nikhiljindal

**Comment by nikhiljindal** [comment]
Link to an example run where this happened? (Want to see the logs)

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/15224#issuecomment-147021850

**Comment by wojtek-t** [comment]
Few other failures:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/9334/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/9311/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/9301/

**Comment by dchen1107** [comment]
Another failure:

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/12368/consoleFull

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/15508 marked the test as flaky so it should not be blocking PR merges anymore.
https://github.com/kubernetes/kubernetes/pull/15572 attempts to fix the flake.
