### ISSUE TITLE
Client library requires authentication

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#15368]
I think that client libraries does not support use-case where we are using self-signed certificates in apiserver, but we don't want to use client authentication:

1. we expect that we will have a token generated (see [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/helper.go#L260)); this will not be the case in our situation
1. if we don't provide private key for signing service account tokens we will not run token controller (see [code](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L322)) and in particular we will not mount CA certificates (see [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/tokens_controller.go#L324)), which will result in the following error:
```
E1009 12:18:19.919513       1 helper.go:264] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
2015/10/09 12:18:19 Unable to get server version: Get https://10.0.0.1:443/version: x509: failed to load system roots and no roots provided
```

Am I missing something?

@lavalamp @liggitt @roberthbailey

**Comment by liggitt** [comment]
TLS is orthogonal to authentication. If we want to change InClusterConfig to determine whether it is running in a cluster environment from the presence of the KUBERNETES_SERVICE_HOST/KUBERNETES_SERVICE_PORT envvars, that's probably ok.

In that case, we could tolerate a missing token.
Additionally, if no CA was found, I would be ok with enabling InsecureSkipVerify for the in-cluster config

**Comment by liggitt** [comment]
Copied comment from https://github.com/kubernetes/kubernetes/pull/15230#issuecomment-146883701:

I think the following things would make sense:

1. Add an authentication option to the apiserver (e.g. `--anonymous-auth`) to allow anonymous requests to the TLS-enabled endpoint (basically an "AllowAll" authenticator)
2. Update InClusterConfig to:
  a. look for the envvars to determine whether it is running in a cluster environment
  b. tolerate a missing token to just attempt using the API anonymously
  c. tolerate a missing CA and enable InsecureSkipVerify

That would allow people who don't want to set up authentication to start their APIserver with `--anonymous-auth --authorization-mode=AlwaysAllow`, and InClusterConfig could happily use the API

**Comment by fgrzadkowski** [comment]
I've changed my approach to containerized kubelet, so this one is not needed anymore.
