### ISSUE TITLE
Rename "experimental" group

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#15378]
Currently, features in the `experimental` api group are at version `v1alpha1`.
As I describe in #15339, I think that the `alpha` version should be the thing that signals to users that a feature is unstable, not the name of the api group, which, for historical reasons, is `experimental`.   

Also, I don't think anyone expects these Kinds to stay in "experimental" indefinitely.  But I haven't heard a plan about what api group they eventually go into.

So, I think we should rename `experimental` api group to something else which doesn't imply unstable.

Three reasons why I think we need to make this change/distinction.

1. when features in the `experimental` api  group graduate to version `v1beta1`, they will have additional stability ... more than the word *experimental* might imply.
1. we may introduce new `alpha` quality interfaces in a subsequent version (v1.2 or v1.2).  For example, we miay introduce OpenShift authorization objects.  Because there are so many, they should go into their own API group, e.g. `policy` at first.  The meaning of `experimental` is confusing when there are other api groups that are also unstable at first.
1.  Once current features in experimental graduate to `v1beta1`, we don't want to add new things into that group (e.g. we don't want `apiVersion: experimental/v1beta1 kind:job` at the same time as `apiVersion: experimental/v1alpha1 kind: newThing`.)  It is just confusing to have different things at different versions in one api group.

So, I see a couple of options at this point:

1. do not rename "experimental" in v1.1, but plan to move each Kind that is currently in experimental into a new, more appropriate group, in the next minor version.
1. rename "experimental" to something less scary, like "demo" right now.  Plan to move each Kind that is in "demo" into a new, more appropriate group, prior to graduating them to "v1".
1. add multiple API groups now (prior to v1.1) and try to sort Kinds into them now.  

The last option is the most coding to do before v1.1 to support even more api groups, and could stall on bike shedding on deciding what the final group names are.

**Comment by erictune** [comment]
@bgrant0607 @lavalamp @caesarxuchao

**Comment by lavalamp** [comment]
When a feature is ready for v1beta1, IMO that means we find a new group, not named "experimental". Experimental only should ever have the v1alpha1 version.

When API groups is more fully featured, ideally we'll retire experimental completely and start new features in a new group from the beginning.

**Comment by derekwaynecarr** [comment]
@smarterclayton @kubernetes/rh-cluster-infra 

IMO, experimental is where a developer can iterate and prove a feature.  its a development sandbox, not a place to gather end-user feedback.

**Comment by ncdc** [comment]
+1 to sandbox

**Comment by caesarxuchao** [comment]
I agree Experimental should ever have the alpha version. Maybe we can make another group with a less scary name to contain all the features of beta version.

**Comment by erictune** [comment]
My levels are:

- developer branch: use for iterating on your own or with a few other devs
- alpha: partial implementation for a feature has been code reviewed and merged, and the parts that are implemented are tested.  you may not implemented everything and the API may not have had a thorough API review; want other devs and selected expert users to try it.  We don't expect those people to build from your branch and make a cluster just to try your feature.
- beta: all planned implementation is done and the API has had a careful review.  There is some kind of documentation.  Some developer besides the author has used the feature for a few days.  The code is stable, but we might have missed something in the API, which is hard to change later.  So, we want more eyes on the API.   we are committed to finishing the features.
- stable, e.g. `v1`.: API is done, for better or for worse.  there may have been minor bug fixes since beta.
- experimental: we should stop using this word.  @lavalamp  has a proposal to do so.

**Comment by lavalamp** [comment]
__We will rename experimental/v1alpha1 to extensions/v1beta1.__

For 1.1, we'll flag-disable objects that aren't meeting the beta bar; I'll file a separate issue for this.

**Comment by pmorie** [comment]
We should capture this in the API changes document.

**Comment by bgrant0607** [comment]
#15339 is in progress

**Comment by davidopp** [comment]
Is there anything left to do for this issue?

**Comment by lavalamp** [comment]
#15573 cherry-picked #15488, so this is done now. I was waiting for that to merge before closing this.
