### ISSUE TITLE
Add correct handling of 'try again later' responses from API server in scalability tests

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#15372]
Today the run of 1000 node Kubemark cluster we got an error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:151
Expected error:
    <*errors.StatusError | 0xc225df0100>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "the server has received too many requests and has asked us to try again later (get replicationControllers density30000-b45dfbb7-6e78-11e5-b820-42010af01555)",
            Reason: "Timeout",
            Details: {
                Name: "density30000-b45dfbb7-6e78-11e5-b820-42010af01555",
                Kind: "replicationControllers",
                Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "Too many requests, please try again later.",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 1,
            },
            Code: 429,
        },
    }
    the server has received too many requests and has asked us to try again later (get replicationControllers density30000-b45dfbb7-6e78-11e5-b820-42010af01555)
not to have occurred
```

IIUC this means that the server is begin hammered and started throttling requests. It's perfectly valid response from the server and test shouldn't fail because of that.

It's probably worth to add function handling this correctly to the general e2e testing framework, as we increase test parallelism those kinds of errors can start to appear.

cc @quinton-hoole @wojtek-t @fgrzadkowski @brendandburns

**Comment by gmarek** [comment]
@lavalamp @davidopp - do you know who's the best person to work on this?

**Comment by wojtek-t** [comment]
I will look into it tomorrow.

**Comment by wojtek-t** [comment]
To be honest I though that our client is handling 429 error internally and retires - it seems it's not the case...
@lavalamp - so how is currently the 429 error being handled?

**Comment by derekwaynecarr** [comment]
I thought in controllers at least that a 429 would just cause a re-queue.

**Comment by lavalamp** [comment]
I thought client/unversioned/request.go had retry logic. It may be that it
reached the maximum number of retries?

**Comment by gmarek** [comment]
I think it's solved now.
