### ISSUE TITLE
Services should work after restarting apiserver flake

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#15381]
Failed 1 times in the last 30 runs.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8829/testReport/junit/%28root%29/Kubernetes%20e2e%20suite/Services_should_work_after_restarting_apiserver/

**Comment by lavalamp** [comment]
54 days old. Obsolete? Reopen if it reoccurs.
