### ISSUE TITLE
Identify the configuration format

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15387]
Currently kubectl looks for files with extensions .yaml, .yml, and .json, and Kubelet reads .manifest files, at least by convention, for legacy reasons.

None of these extensions indicate that the files are Kubernetes-specific. Ironically, we don't even use the extensions to infer the encoding type -- a .json file could contain YAML, for instance.

As users build preprocessors and/or adopt higher-level orchestration tools (e.g., nulecule, terraform, deployment manager), they'll use config files of multiple formats, consumed by multiple systems. We should choose an extension that makes it clear that the files can be consumed by kubectl.

How about .kube?

Openshift uses the same format and tooling. Would it use .kube files, or choose a different extension, such as .os?  Or should we choose something more neutral, like .sic -- self-identifying config (contains apiVersion and kind)?

@smarterclayton

**Comment by smarterclayton** [comment]
To be honest, we usually try to use extensions that other editors on the
system will recognize, rather than claiming our own.  I think we'd assumed
we could live with .json / .yaml for the most part - since most users on
the CLI are providing paths, the extension hasn't jumped up much.  We
definitely want to ensure kubectl edit is using an extension that matches
the format (but that can be kept separate).

**Comment by kelseyhightower** [comment]
I've been pretty happy with the current setup and I don't see a problem with the .yaml or .json file extensions, but it might be a good idea to validate the proper encoding. One benefit of using the "native" file extensions is better integration with other tools and editors that may be used to generate these configs and possibly consume them in the future.

**Comment by bgrant0607** [comment]
Editor recognition is an interesting point.

Another idea that's popped up (e.g., in #14993) is that it would be useful to encode the content type in the file rather than via the extension, since that would work for stdin, http, packages (e.g., [Helm](https://github.com/deis/helm)), etc.

The Nulecule approach requires a separate manifest:
https://github.com/projectatomic/nulecule/blob/master/examples/guestbook-go/Nulecule

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by alexandercampbell** [comment]
Something like `file.kube.yaml` would be recognized by all existing editors but then editors could also add kubernetes-specific support.
