### ISSUE TITLE
Proposal: Required, permitted, prohibited, and default label keys (and maybe values)

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15390]
LimitRange enables administrators to make resource-related requirements upon pods created by users (including indirectly via controllers).

We could create a similar policy object that would enforce required, permitted, prohibited, and default label keys (and perhaps values) on all/selected resources within whatever scope such policies are enforced -- currently per namespace. In this case, per namespace makes sense because label selection is scoped by namespace.

The motivation: it's useful for cluster and app admins to be able to impose such restrictions in order to simplify management, monitoring, etc. For instance, if they know that every resource has an `environment` label key, then they could easily differentiate dev, staging, and production workloads.

**Comment by bgrant0607** [comment]
Default labels would be one solution to #1698

**Comment by bgrant0607** [comment]
cc @gabrtv

**Comment by bgrant0607** [comment]
Generalization of this idea described here: https://github.com/kubernetes/kubernetes/pull/16250#issuecomment-155677649

**Comment by bgrant0607** [comment]
Related: #2211

**Comment by smarterclayton** [comment]
I wonder if we can get away with just default, forbidden, and override.  The benefit is that all clients "just work". I know we've had requests for rules based labeling (add a label based on image used to facilitate global selection), and most of those use cases are solved by that combination.

Actually, that's what the namespace node selector admission controller does - defaults, overrides, and forbids conflicting labels.

Override has the potential to break user apps.

**Comment by bgrant0607** [comment]
This approach would be useful for annotations, also.

Rather than overriding specified label values, how about just default, required, forbidden?

**Comment by markturansky** [comment]
Does this also apply to selectors?  Would it restrict what I can add to, say, pod's NodeSelector?
