### ISSUE TITLE
kube-apiserver: make --runtime-config more fine-grained

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#15403]
Right now runtime config can turn on or off group/version pairs. I want to extend this to allow turning on a group/version, and turning individual objects in that group/version off.

e.g. --runtime-config="v1,extensions/v1beta1=true,extensions/v1beta1/ingress=false" turns on everything in the extensions group except for ingress.

It should not be possible to turn an object on if its group is off, so this is invalid: --runtime-config="v1,extensions/v1beta1=false,extensions/v1beta1/ingress=true"

**Comment by nikhiljindal** [comment]
How about config="v1,extensions/v1beta1/ingress=true" (we turn on v1beta1 without the explicit extensions/v1beta1=true. All resources in that group except ingress are off).

**Comment by lavalamp** [comment]
@nikhiljindal Sure, that seems fine.

**Comment by nikhiljindal** [comment]
Here are the set of tasks based on various discussions:

- [ ] Update defaults in code to enable extensions/v1beta1 by default. Jobs, ingress and HPA will also be enabled by default. All other extension resources will be disabled.
- [ ] Users will be able to override these default enabling/disabling of resources and whole group versions using runtime-config (We should maybe rename that to runtime-overrides?)
- [ ] We will add env vars for each group version and resources (for ex: ENABLE_DEPLOYMENTS or DISABLE_EXTENSIONS) which will set the appropriate runtime-config in all our scripts.

**Comment by lavalamp** [comment]
Reopening this because there's still e.g. cherrypicks and todo items.

**Comment by lavalamp** [comment]
#15785 is the cherrypick we need.

**Comment by lavalamp** [comment]
#15785 is merged! @nikhiljindal, which of your todo items remain?

**Comment by nikhiljindal** [comment]
The third task: adding env vars to enable and disable individual resources (which will set the appropriate runtime-config value in our cluster bring up scripts) is left. But am not sure of how critical that is.
WDYT?

**Comment by lavalamp** [comment]
@nikhiljindal Can we set the default directly here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L228

So that we don't need to change configuration scripts?

We should default Ingress, Job, and HPAS on, and the rest of extensions off. (In the release branch, anyway.)

**Comment by nikhiljindal** [comment]
Yes we already have Ingress, Job and HPAS on and rest of the extensions off, by default.
What I was talking about was to have an env var, for ex: ENABLE_DEPLOYMENTS which when user sets to true and runs cluster/kube-up.sh brings up a cluster with deployments enabled as well (it will be off by default). User can do this on release code as well.
fwiw, ENABLE_DEPLOYMENTS is already implemented (which is used by tests). I was wondering if we should add similar env vars for other resources that are off by default? Or we can leave that on people working on those resources to add it if they want it?

**Comment by lavalamp** [comment]
Ah, OK. I think that does not need to be done for 1.1, thanks for clarifying.

Going forward, we should let whoever is developing a feature add the var to enable/disable, although I'd prefer just to turn everything on in HEAD and stop using so many env vars. But if you want to be extra nice to people, you could add one for the things that didn't make it into 1.1, I suppose.

**Comment by nikhiljindal** [comment]
Closing.
