### ISSUE TITLE
kube-controller-manager: enable controllers based on discovery

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#15402]
Deprecate the --enable-experimental flag and replace with a discovery based mechanism, building on https://github.com/kubernetes/kubernetes/pull/14941

**Comment by davidopp** [comment]
Is there anything to do for this issue other than merge the cherrypick for #15427 ?

**Comment by lavalamp** [comment]
No-- just waiting for that to merge.

**Comment by lavalamp** [comment]
Cherry pick is merged.
