### ISSUE TITLE
[mesos/docker] Flakey Smoke Test - TLS handshake timeout

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#15412]
```
error: couldn't read version from server: Get https://172.17.0.79:6443/api: net/http: TLS handshake timeout
```

https://teamcity.mesosphere.io/viewLog.html?buildId=56436&buildTypeId=Oss_KubernetesMesos_5SmokeTestsDockerMesos&tab=buildLog&guest=1#_focus=614

First time I've seen this. Documenting for searchability.

**Comment by davidopp** [comment]
Removing kind/flake label since we want to use that label only for tests that are in the Google CB. Please feel free to create a kind/mesos-flake for tracking flakes in the Mesosphere CB if you wish.

**Comment by k82cn** [comment]
/close

old issue, close it directly.
