### ISSUE TITLE
patchResource should not retry patch if resourceVersion is specified in the patch

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#15416]
#14758 introduce the server-side retry for patch if there is an conflict. An exception should be made if user specified the `resourceVersion` in the patch, because that means the user wants to use the `resourceVersion` as a precondition. This is consistent with how we handle a PUT request (see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/generic/etcd/etcd.go#L234))

@deads2k @bgrant0607 @lavalamp

**Comment by caesarxuchao** [comment]
We also need a test to verify that `resourceVersion` is taken as an precondition by Patch. I'm adding it in test-cmd.sh.

**Comment by deads2k** [comment]
Are you about the case where the user's patch actually set `resourceVersion`?  If so, I think that case is already handled because the patch will always conflict and you'll get a conflict error back.

**Comment by caesarxuchao** [comment]
@deads2k, yes, a user will get the conflict error, but after `MaxPatchConflicts` times of retries. We should not do the retries.

**Comment by caesarxuchao** [comment]
@bgrant0607, It requires some effort to parse all three types of patches to check if the patch contains `resourceVersions`. And the current code doesn't do anything wrong except doing some unnecessary reties.  Maybe we can downgrade the priority of this issue?

**Comment by bgrant0607** [comment]
We should at least test that the apiserver correctly detects conflicts.

**Comment by caesarxuchao** [comment]
#15420 add the tests.

**Comment by caesarxuchao** [comment]
#15420 add the tests. Closing this issue.
