### ISSUE TITLE
kube-up.sh with KUBERNETES_PROVIDER=libvirt-coreos fails to start kube2sky

### ISSUE THREAD

**Issue by andreacorbellini** [kubernetes/kubernetes#15436]
I have downloaded Kubernetes 1.0.6 from https://github.com/kubernetes/kubernetes/releases

kube2sky fails to start because of the following error:

```
KUBERNETES_RO_SERVICE_HOST is not defined.
```

Indeed, by inspecting `/proc/.../environ` I can see that none of the `KUBERNETES_RO_*` variables are set. If I manually set `KUBERNETES_RO_SERVICE_HOST=192.168.10.1` and `KUBERNETES_RO_SERVICE_PORT=8080` (the host and port of the insecure api server) in `skydns-rc.yaml`, kube2sky starts, but every request fails with "invalid request".

I could provide more details, but my guess is that the **Docker Hub has an outdated version of kubernetes/kube2sky**, which is no longer compatible with the latest version of Kubernetes. FYI, kube2sky from the Docker Hub does not support `-kube_master_url` option.

**Comment by linzichang** [comment]
The latest kube-dns in https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns. The kube-dns in libvirt-coreos should be updated. So some changes to cluster/libvirt-coreos are needed.
