### ISSUE TITLE
Kubectl describe pods doesn't show Container.Command and Container.Args information etc.

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#15432]
Kubectl describe pods doesn't show Container.Command and Container.Args etc. Of course, you can use Kubectl get pods -o yaml to show these things. But I want to know, is there any rules that information should be shown by kubectl describe? @kubernetes/kubectl

**Comment by smarterclayton** [comment]
It probably should show those items.

The rules are "describe should show information useful to an end user who
needs to know more about the intent and state of an object".  In general,
if we summarize some fields we won't show them, but if the fields are
important for a user to understand what the object is supposed to do, or is
doing, they should be presented.

On Oct 10, 2015, at 3:21 AM, Flying Tiger <notifications@github.com> wrote:

Kubectl describe pods doesn't show Container.Command and Container.Args
etc. Of course, you can use Kubectl get pods -o yaml to show these things.
But I want to know, is there any rules that information should be shown by
kubectl describe? @kubernetes/kubectl
<https://github.com/orgs/kubernetes/teams/kubectl>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15432>.

**Comment by feihujiang** [comment]
I got it. I'll fix this.
