### ISSUE TITLE
test-kub-master-pd EBS volume is not deleted with kube-down.sh

### ISSUE THREAD

**Issue by rroopreddy** [kubernetes/kubernetes#15448]
Kubernetes (1.0.6) /AWS  cluster gets into unrecoverable state. To get around it, we go through "kube-down.sh and kube-up.sh". In this scenario the EBS volume created for master (test-kub-master-pd) is not deleted. However, rest of the AWS volumes created for minions are deleted though with kube-down.sh. 

To clarify, 'kube-up.sh' another volume when new master is created leaving old one as is

Is this a bug or intended?

**Comment by saad-ali** [comment]
The logic to attach/detach volumes from nodes (pkg/volume/...) is independent of the logic to create the master PD (which I believe is done in the salt scripts that setup the master).

CC @justinsb

**Comment by justinsb** [comment]
The kube-down script now deletes the master-pd.  I believe that's what you were asking for @rroopreddy  ; feel free to reopen if not!
