### ISSUE TITLE
Update Dockerfile and dev tooling for K8PetStore

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#15450]
The k8petstore app needs 
- updated golang images.  The google/golang one is deprecated, hence `web-server/Dockerfile` isn't really valid anymore (it might work, but has a deprecated message).
- simplified script to setup the dev environment to add new features (Vagrant seems a little heavy weight for it )
- I think this might apply to guestbook-go as well. not sure.  will check.

I can put a PR for this this wk if nobody beats me to it.

**Comment by kargakis** [comment]
@jayunit100 status of this issue?

**Comment by jayunit100** [comment]
Was hoping this would move over with the other examples,and then we could start pruning the examples down to a small, 'basis-set', which k8petstore may (or may not) be a part of .

**Comment by kargakis** [comment]
@jayunit100 mind moving the issue in the examples repo then?

**Comment by jayunit100** [comment]
yes sir
