### ISSUE TITLE
Replacement of "publicIPs" for service in Kubernetes 1.0.x

### ISSUE THREAD

**Issue by xfye** [kubernetes/kubernetes#15469]
Currently, we are using V0.19.0 and we plan to upgrade to V1.0.6. But we found that “publicIPs” is not supported.
<b>Is there a replacement setting of “publicIPs” for a service in Kubernetes 1.0.x ?</b>

From this link https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/user-guide/services.md, only “NodePort” and “LoadBalancer” are supported for external services. But both of them will allocate the same port number on all nodes for a services, which can not meet our requirement.

We have one K8s cluster on which over two applications are running. In each application, there is a component that need export 80 port for external service. We use “publicIPs” feature of a service to place port 80 on different node for different apps. For example:
App1 exports port 80 on node-1.
App2 exports port 80 on node-2.
App3 exports port 80 on node-3.

**Comment by xfye** [comment]
I thought "deprecatedPublicIPs" has been removed from 1.0.6. But "deprecatedPublicIPs" can still work in 1.0.6. So my problem is resolved.

**Comment by thockin** [comment]
deprecatedPublicIPs was retained, and in v1.1 it "un-deprecated" and called "externalIPs".

That said, there are other answers that are less clumsy (IMHO) - https://github.com/kubernetes/contrib/tree/master/for-demos/proxy-to-service
