### ISSUE TITLE
Implement e2e tests for horizontal pod autoscaling of deployments

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#15474]
We need to write e2e tests which combines horizontal pod autoscaling with deployments (scale sub-resourcer should point to a deployment object).

The tests should be similar to https://github.com/kubernetes/kubernetes/blob/master/test/e2e/horizontal_pod_autoscaling.go. The library from https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling_utils.go should be extended and allow creation of a resource consumer as a deployment (currently it is always replication controller). The new tests should create a deployment resource consumer and pass a scale-sub-resource to the deployment to autoscaler.

**Comment by jszczepkowski** [comment]
part of #14108

**Comment by jayunit100** [comment]
- Yeah that sounds like a good test to run re: scale out to n node
- cc  #10479 also
