### ISSUE TITLE
Remove deprecated shorthand flag in kubectl

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#15471]
I see many of shorthand flags in kubectl are deprecated, we should remove them gradually. 

I think -c shorthand for --client in version is least used, we could remove it firstly.
@kubernetes/kubectl

**Comment by jlowdermilk** [comment]
I don't think we have a general plan to remove all shorthand flags. Some are deprecated for specific reasons, but I'm not aware of a policy/design choice that says we want to remove them all. cc @bgrant0607

**Comment by bgrant0607** [comment]
@jlowdermilk see https://github.com/kubernetes/kubernetes/blob/master/docs/devel/kubectl-conventions.md#flag-conventions

@feihujiang thanks for filing the issue. To be clear, first we need to print a deprecation message for some number of releases before we can consider removing it.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc
