### ISSUE TITLE
Support pulling docker image tarfile from a URL in the PodSpec

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#15484]
This would make distribution of cluster components packaged in docker images much easier. Right now component images are downloaded in tarfile format and unpacked by salt/bash. This should be a concern of cluster deployment but is currently entangled with node deployment. We should support this in the node API.

@bgrant0607 @dchen1107 @roberthbailey

**Comment by roberthbailey** [comment]
Is this because of the way we currently side-load the master component images? Having a release process where the images are pushed to gcr.io and dockerhub seems like a better alternative.

**Comment by bgrant0607** [comment]
Or a private registry.

See also #8702.

**Comment by davidopp** [comment]
ref/ #8686

**Comment by mikedanese** [comment]
cc @zmerlynn

**Comment by zmerlynn** [comment]
I actually really like this approach. A docker image is really not much more than a bag of bits at the end of the day, and being able to just take a `.tgz` URL in a PodSpec would be pretty powerful. Registries have a lot of overhead that this can just avoid. Why not people deploy images in other ways?

**Comment by mikedanese** [comment]
Urls should support remote and local:
```
https://storage.googleapis.com/kubernetes-releases/v1.1.2/kubelet.tar.gz
file:///srv/release/bin/kubelet.tar.gz
```

**Comment by resouer** [comment]
Just out of curiosity, do we really want this? Or it is still in discussing?

**Comment by roberthbailey** [comment]
I'm going to close this in favor of https://github.com/kubernetes/kubernetes/issues/8686

**Comment by byrnedo** [comment]
@roberthbailey I don't get why #8686 relates to this issue, what am I missing?

**Comment by roberthbailey** [comment]
The goal of https://github.com/kubernetes/kubernetes/issues/8686 was to define best practices for packaging cluster components, and this issue is about a specific way that we could improve one aspect of packaging. It seemed like one possible answer to the other issue, but I didn't think it stood alone as a feature, because if this is not a way that fit with the best practices that we want to promote then I'm not convinced that it is worth building.
