### ISSUE TITLE
Ingress is missing a /status subresource

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#15480]
Per discussion, this is missing and is needed to graduate the resource.

@kubernetes/rh-cluster-infra @bgrant0607 @lavalamp

**Comment by derekwaynecarr** [comment]
I will look to get a PR in place for this today.

**Comment by bgrant0607** [comment]
cc @bprashanth

**Comment by bprashanth** [comment]
@derekwaynecarr thanks
