### ISSUE TITLE
kubectl apply should retry stale resource version.

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#15493]
From an e2e test failure:
```
Error from server: error when applying patch:
    {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"ReplicationController\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"redis-master\",\"creationTimestamp\":null,\"labels\":{\"app\":\"redis\",\"kubectl.kubernetes.io/apply-test\":\"ADDED\",\"role\":\"master\"}},\"spec\":{\"replicas\":1,\"selector\":{\"app\":\"redis\",\"kubectl.kubernetes.io/apply-test\":\"ADDED\",\"role\":\"master\"},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"redis\",\"kubectl.kubernetes.io/apply-test\":\"ADDED\",\"role\":\"master\"}},\"spec\":{\"containers\":[{\"name\":\"redis-master\",\"image\":\"redis\",\"ports\":[{\"name\":\"redis-server\",\"containerPort\":6379}],\"resources\":{}}]}}},\"status\":{\"replicas\":0}}"},"creationTimestamp":null,"labels":{"kubectl.kubernetes.io/apply-test":"ADDED"}},"spec":{"selector":{"kubectl.kubernetes.io/apply-test":"ADDED"},"template":{"metadata":{"labels":{"kubectl.kubernetes.io/apply-test":"ADDED"}}}}}
    to:
    &{0xc208226190 0xc2080cbea0 e2e-tests-kubectl-ztbsd redis-master STDIN 0xc208568ff0 0xc2083aa960 1387}
    for: "STDIN": replicationControllers "redis-master" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
```

The command should retry resource version mismatches like scale and rollingupdate.

cc @kubernetes/kubectl

**Comment by jayunit100** [comment]
Isn't the failure intentional (i.e. optimistic mutate) ?  I'm probably missing something.

**Comment by jackgr** [comment]
The desired behavior that we settled on previously is to detect version mismatches at the client and error. User can force replacement using --force. See #16543, #16569 and #17237.

**Comment by bgrant0607** [comment]
@jackgr What is the mismatch here? If it is just resourceVersion, kubectl should retry. It should only bail on a meaningful conflict.

We're working on eliminating flaky tests (and flaky parts of the system).

Also, that log message isn't very useful.

**Comment by jackgr** [comment]
@bgrant0607 per discussion on #16543, we can't determine the correct behavior when the resource version changes without more information, so best to catch version mismatch at the client and bail, and let the user replace the object with --force if they want. We can also make the error message less verbose.

**Comment by bgrant0607** [comment]
@jackgr I don't see any mention of resourceVersion in #16543. It shouldn't be serialized in the annotation, because the user shouldn't specify it in their config. The resourceVersion-based precondition is intended to guard against concurrent read-modify-write operations. kubectl apply should be able retry the entire diff&patch in the case of this type of conflict.

That said, it's not obvious to me from the log message what the actual problem was in this case.

**Comment by jackgr** [comment]
I'm sorry, my mistake. You're right that resourceVersion is not in the annotation, and that we should retry on resourceVersion failure.

I was confusing this with the api version change issue discussed in #16543. This is actually a much simpler issue, in the sense that it's an optimistic lock conflict.

If we encounter a lock conflict, then we should fetch a fresh copy of the object, and try again to apply the new configuration supplied by the user. 
* If we don't get a merge conflict when we resubmit, then all's well.
* If we get a merge conflict because the object has changed out from under the user, then we report it in those terms, and the user can decide what to do (e.g., replace using --force).

Does this fit your expectation  of how it should be handled?

**Comment by bprashanth** [comment]
This is causing test flake:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/20534/kubernetes-pull-build-test-e2e-gce/28891
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/28891/
```
    to:
    &{0xc20827c190 0xc2080cbf80 e2e-tests-kubectl-o39wt redis-master STDIN 0xc208504690 0xc208562780 4508}
    for: "STDIN": replicationControllers "redis-master" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
    
    
not to have occurred
```

**Comment by lavalamp** [comment]
@jackgr yes, your understanding is correct. Do you have time to fix this? We're trying to get all our tests fixed. Additionally this sounds like a legit system bug, not just a flaky test problem.

**Comment by jackgr** [comment]
@lavalamp Maybe. Swamped right now, but can fit it in given enough notice. When is the fix needed?

**Comment by lavalamp** [comment]
@jackgr asap. We'll find someone else.

**Comment by bprashanth** [comment]
This should just be a generic GET/Update retry loop, eg: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller_utils.go#L53

**Comment by jackgr** [comment]
Go for it.

Jack Greenfield | Google

**Comment by lavalamp** [comment]
Chao, do you have cycles to take a look?

**Comment by caesarxuchao** [comment]
I thought Patch is retried in the server. I'll investigate.

**Comment by caesarxuchao** [comment]
Patch is retried at server-side five times before an error is returned: https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L92, so I expect this issue to occur very rarely. In fact, it has passed last ~400 kubernetes-gce-e2e tests.

If we want to make this test less flaky, I'd recommend increase the number of the retries at the server-side. What do you guys think?

**Comment by lavalamp** [comment]
It'll fail if an actual conflicting change was made, though. Do we know
what the nature of the conflict was? Maybe first we need to add some log
messages to figure out what the conflict was next time it occurs.

**Comment by bprashanth** [comment]
> so I expect this issue to occur very rarely. In fact, it has passed last ~400 kubernetes-gce-e2e tests.

This happened last week: https://github.com/kubernetes/kubernetes/issues/15493#issuecomment-185509422

**Comment by caesarxuchao** [comment]
@lavalamp you are right. I thought an actual conflicting change would result in a different error message but it's not. I'll add the logs.

**Comment by caesarxuchao** [comment]
In #21723 I added a log entry if there is a meaningful conflict. That said, I don't think we have a meaningful conflict in this particular e2e test.

After taking a closer look at the implementation of `kubectl apply`, I think the submitted `patch` is precise, so we shouldn't retry at the client side if server reports a meaningful conflict.

**Comment by ncdc** [comment]
@bgrant0607 @thockin does the milestone on this need to be changed to v1.2?

**Comment by bgrant0607** [comment]
How often is the test flaking?

**Comment by caesarxuchao** [comment]
> How often is the test flaking?

Last time I checked, `it has passed last ~400 kubernetes-gce-e2e tests.` I'll check it again.

**Comment by caesarxuchao** [comment]
Last time I checked the results was two days ago, in the past 48 hours, the test has consecutively passed another 124 builds (12080 to 12204).

**Comment by bgrant0607** [comment]
I only see 3 reports of failures since October, so I'm going to say, no, it doesn't need to be fixed in 1.2.

**Comment by AdoHe** [comment]
@bgrant0607 any progress on this now? I returned back to the kubectl apply issues, and hope I can fix all apply related issues before 1.3.0 release.

**Comment by caesarxuchao** [comment]
I'll try to check the flake rate again. IMO if the flake rate is non-negligible, we should increase the retry limits of Patch, or more aggressively, just remove the limit. https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L92

**Comment by smarterclayton** [comment]
Infinite retry still scares me, mostly because we may have failure modes
that could race for a very long time.

**Comment by bgrant0607** [comment]
@AdoHe I don't think anyone has worked on this.

Though the original failing test/logs weren't recorded, it appears to be a failure of "should apply a new configuration to an existing RC":
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubectl.go#L541

@caesarxuchao There is a retry loop in the Patch handler in apiserver, but if resourceVersion is specified, the retry loop will always fail in the case of a conflict. (We should detect that and bail out, but I don't think we do.)

In the case of such a conflict, apply should diff again, create another patch, and try again.

I agree with @smarterclayton that it shouldn't retry forever. We should use the same retry limits we use for other commands.

**Comment by caesarxuchao** [comment]
@smarterclayton we have an infinite loop in GuaranteedUpdate (https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd/etcd_helper.go#L610), maybe we should apply a retry limit there as well?

**Comment by caesarxuchao** [comment]
> There is a retry loop in the Patch handler in apiserver, but if resourceVersion is specified, the retry loop will always fail in the case of a conflict. (We should detect that and bail out, but I don't think we do.)
In the case of such a conflict, apply should diff again, create another patch, and try again.

Agree. Just note that the test flake doesn't specify resourceVersion.

**Comment by pwittrock** [comment]
@AdoHe Since this is causing flakey test failures, it is something we should focus on.  Is this something I should pick up?

**Comment by pwittrock** [comment]
FYI: @AdoHe has a PR out for this under review

**Comment by pwittrock** [comment]
Making this a P3 (no release block) since I looks like we haven't seen many instances since Feb 2016
