### ISSUE TITLE
Initial Resources should set initial resources based on historical data flaky

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#15496]
Jenkins project: kubernetes-e2e-gce-autoscaling failed last couple of runs:

Initial Resources [Skipped][Autoscaling Suite] should set initial resources based on historical data
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/initial_resources.go:45
Expected
    <int64>: 1179928576
to be ~
    <int>: 209715200

**Comment by dchen1107** [comment]
couple failing instances:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-autoscaling/1301/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-autoscaling/1300/

**Comment by brendandburns** [comment]
Re-opening.  This flaked again:

http://kubekins.dls.corp.google.com/view/job/kubernetes-e2e-gce-autoscaling/1324/

**Comment by lavalamp** [comment]
@piosz status?

**Comment by piosz** [comment]
The test is disabled and there is no plan to enable it within next few weeks, so closing the issue and I'll back to it some time in the future.
