### ISSUE TITLE
iSCSI targetPortal's port is not optional

### ISSUE THREAD

**Issue by Calpicow** [kubernetes/kubernetes#15501]
Documentation says that port number for `targetPortal` is optional, but I've found that not to be true. It's due to the way it detects whether the disk is attached or not.

`targetPortal` also must be an IP.

Refer to:
https://github.com/kubernetes/kubernetes/tree/4da423c41d5bdee9605f4ac53805449681746f84/examples/iscsi

https://github.com/kubernetes/kubernetes/blob/4da423c41d5bdee9605f4ac53805449681746f84/pkg/volume/iscsi/iscsi_util.go#L82

**Comment by rootfs** [comment]
@Calpicow `targetPortal` is in form of `ip:port`. `port` can be omitted if portal uses default port number 3260. Did you find any exception?

**Comment by rootfs** [comment]
@Calpicow I see what you meant. Good catch. If you don't have a pr yet, I'll provide a fix to the doc.

**Comment by Calpicow** [comment]
I don't have a CLA in file yet, so I'll leave it up to you. Thanks.

**Comment by rootfs** [comment]
@Calpicow check this out https://github.com/kubernetes/kubernetes/pull/15555
