### ISSUE TITLE
Remove ServerAPIVersions() from VersionInterface

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#15511]
We have a ServerAPIVersions(c *Config) [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/helper.go#L196)

We should remove the `ServerAPIVersions` in `VersionInterface`, https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/client.go#L119, which only get the versions from /api, thus broken.

Currently `kubectl explain`, `kubectl api-versions` and `NegotiateVersion` use the broken `ServerAPIVersions`. We need to refactor them.

**Comment by lavalamp** [comment]
Some sort of cleanup here is P1.

**Comment by caesarxuchao** [comment]
This one is fixed.
