### ISSUE TITLE
kubernetes on mesos: 'kubectl delete' strange behaviour  

### ISSUE THREAD

**Issue by loky9000** [kubernetes/kubernetes#15529]
I have running kubernetes-on-mesos cluster and some times some killed tasks stay 'ACTIVE' state on mesos dashboard(oval selection on screenshot).

<img width="1391" alt="screenshot 2015-10-13 09 21 11" src="https://cloud.githubusercontent.com/assets/6886653/10447596/733add24-718e-11e5-8be4-3acd824537eb.png">

`ubuntu@ip-10-10-199-129:~$ kubectl get pods`

NAME           READY     STATUS        RESTARTS   AGE
mysql-s        0/1       Terminating   3          16h
mysql-serv     0/1       Terminating   0          16h
mysql-server   0/1       Terminating   0          16h
tomcat-3qo9o   1/1       Running       0          14h 

`ubuntu@ip-10-10-199-129:~$ kubectl  get rc`

CONTROLLER   CONTAINER(S)   IMAGE(S)               SELECTOR      REPLICAS   AGE
tomcat       tomcat         qubell/tomcat:latest   name=tomcat   1          14h

And another thing. I have several mysql pods with status 'Terminating' , and 'LOST' state on mesos dashboard(rectangle selection on screenshot). But when i try to add these pods again i get the error  'pods  already exists'. It happens when container failed to run for some reasons.

Is there are some way for flush all terminated entities?
How i can  remove nonexistent 'ACTIVE' tasks from mesos dashboard?

**Comment by jdef** [comment]
thanks for reporting this. we've been battling some problems w/ respect to graceful pod deletion. can you tell me how you're building kubernetes mesos (e.g. from which branch)? If from master ... several PR's have been recently merged to master, some specifically to fix bugs related to graceful pod deletion. Would you be able to check out the latest code and check to see if the the task/pod sync problem has been resolved?

FWIW the scheduler is responsible for killing ACTIVE tasks that should no longer exist. There is no backdoor to force the scheduler to kill a specific task.

Mesos maintains a list of terminal tasks. I'm not aware of any method to "flush" list this from mesos.

**Comment by jdef** [comment]
Have you been able to test with the latest master?

**Comment by loky9000** [comment]
ok i'll try with latest master

**Comment by jdef** [comment]
any updates here?

**Comment by loky9000** [comment]
unable to build kubernetes from latest master

**Comment by jdef** [comment]
master builds just fine. are you able to re-test your failure scenario?
