### ISSUE TITLE
kubelet cpu high

### ISSUE THREAD

**Issue by nancykyo** [kubernetes/kubernetes#15528]
it's on a vm.
![image](https://cloud.githubusercontent.com/assets/1332885/10447410/b9e2f798-71b6-11e5-8dc5-e90357c701b3.png)

100 containers on this node
`strace -c -p 1678`
![image](https://cloud.githubusercontent.com/assets/1332885/10447362/6a594b1e-71b6-11e5-8273-7367edb6a26f.png)

`cat /proc/1678/stack`
![image](https://cloud.githubusercontent.com/assets/1332885/10447397/9f69121c-71b6-11e5-8677-e8338958f546.png)

`/proc/1678/wchan`
![image](https://cloud.githubusercontent.com/assets/1332885/10447378/74909470-71b6-11e5-99ac-97a3fc36497e.png)

**Comment by yujuhong** [comment]
@nancykyo, could you provide more information about your cluster? Thanks!
  - kubernetes version (`kubectl version`)
  - What type of vm you use. 100 containers could be pushing the limit on a smaller VM
  - How many pods are running on the node and whether liveness/readiness checks were defined for them.

You can get a 30-second cpu profile by running kubectl proxy and then
`go tool pprof http://localhost:8001/api/v1/proxy/nodes/<node_name>/debug/pprof/profile`
It'd be great if you can post the graph here.

Other high kubelet cpu reports: #10451

**Comment by feiskyer** [comment]
I have met same problem on k8s hangout meeting (running k8s all-in-one on aws instance), but I can't reproduce it again.

**Comment by yujuhong** [comment]
@feiskyer , it was suggested in #15644 that the clock difference between the master and the node might be the root cause. Do you think it'd be the cause of your problem?

**Comment by feiskyer** [comment]
@yujuhong No, I'm running master and node on same vm

**Comment by yujuhong** [comment]
@feiskyer, @nancykyo  I found one goroutine leak at HEAD (see https://github.com/kubernetes/kubernetes/issues/15805#issuecomment-148963658), but it was introduced pretty recently and was not in any of the release cuts. Just to rule out this goroutine leak, could you provide the version of k8s you run? Thanks!

**Comment by feiskyer** [comment]
@yujuhong It's the master branch, so may be #15805 is the root cause. I will take an eye on it.

**Comment by joshm1** [comment]
high CPU on kubelet as well, except for me it's isolated to 1 of out of the 2 nodes in my cluster.  I was able to get only `kube-system` pods running on 1 node and my internal pods on the other. 

below are the pods running on the node that has consistently high kubelet & docker CPU:

This is running kubernetes 1.0.3 on AWS with Ubuntu 15.04 minions.

```
kube-system   elasticsearch-logging-v1-sbg66                       1/1       Running   0          24d       ip-172-20-0-192.ec2.internal
kube-system   fluentd-elasticsearch-ip-172-20-0-192.ec2.internal   1/1       Running   0          24d       ip-172-20-0-192.ec2.internal
kube-system   kibana-logging-v1-fwusk                              1/1       Running   0          24d       ip-172-20-0-192.ec2.internal
kube-system   kube-dns-v8-38fl2                                    4/4       Running   0          24d       ip-172-20-0-192.ec2.internal
kube-system   kube-dns-v8-qoqb7                                    4/4       Running   1          24d       ip-172-20-0-192.ec2.internal
kube-system   kube-ui-v1-2q77h                                     1/1       Running   0          24d       ip-172-20-0-192.ec2.internal
kube-system   monitoring-heapster-v6-n9aql                         1/1       Running   0          24d       ip-172-20-0-192.ec2.internal
kube-system   monitoring-influx-grafana-v1-6gkx4                   2/2       Running   0          24d       ip-172-20-0-192.ec2.internal
```

![image](https://cloud.githubusercontent.com/assets/182629/10699552/90a206f4-7985-11e5-8077-a1b5579a7b41.png)

I restarted the kubelet and that didn't help:

![image](https://cloud.githubusercontent.com/assets/182629/10699569/9b8d765c-7985-11e5-9fe6-9732f6ef8610.png)

**Comment by yujuhong** [comment]
@joshm1, The docker daemon cpu usage is also abnormally high. I don't think yours is related to memory leakage or any of the possibility we discussed above since restarting doesn't help. This might be an issue specific to your cluster setup.

- What's the machine type of your node?
- Did you see any error messages in `/var/log/kubelet.log`?
- Other than the high cpu usage, does the node function correctly? 

It'd might be good to do cpu profiling just in case.
```
$ kubectl proxy
$ go tool pprof <kubelet_binary_path> http://localhost:8001/api/v1/proxy/nodes/<node_name>/debug/pprof/profile
```

**Comment by onorua** [comment]
#### I have

- Kubernetes v1.1.1
- Ubuntu wily with 4.2.0-18-generic
- systemd ntpdate enabled and working fine
- only 2 containers on the host
- CPU usage is around 100%-150% on Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz

```
Process 26912 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.99   25.451882      519426        49        12 futex
  0.01    0.001790          17       104           read
  0.00    0.000148           3        53         3 open
  0.00    0.000042           1        35           fstat
  0.00    0.000000           0        47           close
  0.00    0.000000           0        19         3 stat
  0.00    0.000000           0        36           sched_yield
  0.00    0.000000           0         7           getpid
  0.00    0.000000           0         4           epoll_wait
------ ----------- ----------- --------- --------- ----------------
100.00   25.453862                   354        18 total
```
On neighboring system with more containers and glusterfs client load for kubelet may be up to 400% and > 1GB or RAM:
```
 26912 root      20   0 7621832 1.175g  23180 S 224.7  0.9  22098:09 kubelet                                                                                                          
```

I will be glad to help to debug it, just tell me what information you might be interested in.

**Comment by vishh** [comment]
Can you post the CPU profile of kubelet? `$ kubectl proxy & go tool pprof
http://localhost:8001/api/v1/proxy/nodes/<node_name>/debug/pprof/profile`.

**Comment by yujuhong** [comment]
@onorua, could you follow https://github.com/kubernetes/kubernetes/issues/15528#issuecomment-150667178 and post the information? Thanks!

**Comment by yujuhong** [comment]
@onorua, I am closing this issue since it's been inactive for more than two months. If you have any new information, feel free to reopen the issue.

**Comment by ichekrygin** [comment]
I think I hit this issue in `v1.7.6`
![profile001](https://user-images.githubusercontent.com/324803/31915360-0995434c-b803-11e7-8b78-de8231702c63.png)

**Comment by ichekrygin** [comment]
It appears restarting `kube-kubelet` or `docker` does not change the CPU usage issue. 
It seems the only way to get it (`kubelet` cpu usage) back under control is to bounce `containerd`:
![profile010](https://user-images.githubusercontent.com/324803/31919304-3a7a0fa2-b816-11e7-82c3-a397a8443452.png)

**Comment by yujuhong** [comment]
@ichekrygin, it'd be better to open an new issue since the original one was >2 years ago, closed, and probably doesn't have the same root cause. 

/cc @dashpole, who's looking at cadvisor resource usage, which seems to be causing the big chunk in the profiles above.
