### ISSUE TITLE
kubernetes on mesos:  AWSElasticBlockStore volumes not working

### ISSUE THREAD

**Issue by loky9000** [kubernetes/kubernetes#15530]
ebs volume already exists on amazon 
Name:				mysql-serv
Namespace:			default
Image(s):			tutum/mysql
Node:				ec2-54-172-211-249.compute-1.amazonaws.com/10.10.238.86
Start Time:			Mon, 12 Oct 2015 14:01:26 +0000
Labels:				name=mysql-serv
Status:				Pending
Reason:
Message:
IP:
Replication Controllers:	<none>
Containers:
  mysql:
    Container ID:
    Image:		tutum/mysql
    Image ID:
    QoS Tier:
      cpu:	Guaranteed
    Limits:
      cpu:	500m
    Requests:
      cpu:		500m
    State:		Waiting
      Reason:		ImageNotReady
    Ready:		False
    Restart Count:	0
    Environment Variables:
      STARTUP_SQL:		/tmp/db.sql /tmp/schema.sql /tmp/data.sql
      MYSQL_ROOT_PASSWORD:	1qaz2wsx
Conditions:
  Type		Status
  Ready 	False
Volumes:
  mysql-vol:
    Type:	AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:	vol-ec3aef00
    FSType:	ext4
    Partition:	0
    ReadOnly:	false
Events:
  FirstSeen	LastSeen	Count	From							SubobjectPath	Reason		Message
  ─────────	────────	─────	────							─────────────	──────		───────
  8s		8s		1	{scheduler }								Scheduled	Successfully assigned mysql-serv to ec2-54-172-211-249.compute-1.amazonaws.com
  8s		8s		1	{kubelet ec2-54-172-211-249.compute-1.amazonaws.com}			FailedMount	Unable to mount volumes for pod "mysql-serv_default": Cloud provider does not support volumes
  8s		8s		1	{kubelet ec2-54-172-211-249.compute-1.amazonaws.com}			FailedSync	Error syncing pod, skipping: Cloud provider does not support volumes`

And another question: If volumes described in image's Dockerfile , do i need to describe these volumes(with any type?) in pod definitions or not?

**Comment by jdef** [comment]
volumes require support by the cloudprovider implementation used by kubernetes. kubernetes-mesos uses a custom "mesos" cloudprovider - it doesn't support any type of cloud volumes.
