### ISSUE TITLE
Support dynamic configuration distribution

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1553]
[A related topic came up on IRC today.](https://botbot.me/freenode/google-containers/2014-10-02/?msg=22758209&page=6)

@pwhiteside pointed out [envconsul](https://github.com/hashicorp/envconsul), which can be used to distribute environment variables (or, in theory, arbitrary key-value config data). Something similar could be supported on top of etcd. As with master election (#1542) and endpoint listing, it would be useful to have a canonical solution available in the Kubernetes ecosystem that wasn't tied to a specific key-value store API. 

Even if we don't provide explicit support, it would be useful to document this pattern for others.

**Comment by pmorie** [comment]
@bgrant0607 @thockin @stp-ip A couple of thoughts:

1.  I think there will be a lot of legacy apps that require env vars
2.  It should be possible to consume parameters in many different ways:
    1.  Env vars
    2.  Files from shared `EmptyDir` volume in sidecar container
    3.  Other volume types
3.  There should definitely be a way for pods to be notified when parameters change, either by having kubernetes restart them (especially in the case of env vars), or a notification file becoming present in a volume (personally I like this a lot less than kubernetes just restarting the pod)

**Comment by stp-ip** [comment]
@pmorie
1. yes
2. yes
3. Totally agreed. Restarting is way more plausible and logical.

**Comment by pmorie** [comment]
One mechanism for notification might be if the kubelet did an http `POST` to an endpoint in the pod that would trigger a configuration reload.

**Comment by davidopp** [comment]
Or have Kubelet send a Unix signal like SIGTERM, which can be caught by apps that are able to re-read their config without restarting, or not caught by apps that want to restart when their config changes.

**Comment by pmorie** [comment]
@davidopp Also a good idea.  Summarizing possible reload mechanisms:

1.  Restart pod
2.  Create file with unique name in known location
3.  Post to an endpoint on the pod
4.  Have kubelet send unix signal to containers in pod

I'm not sure I really love the idea of having the kubelet restart the pod on a config change; it seems like restarts should be part of a higher level mechanism.  That said my context is undoubtedly colored by working on OpenShift.

**Comment by thockin** [comment]
How much of this needs to be done by Kubelet vs a side-car container.  I'm
much happier with the latter model.

**Comment by erictune** [comment]
@thockin you have mentioned side-cars a couple of times.  Is there a general issue talking about whether we should use them?  I'm not sold on them yet, versus more narrowly-tailored mechanisms with more specific error handling, etc.

**Comment by pmorie** [comment]
@thockin I'm interested to hear more about side-cars.  I also think a higher level mechanism than the kubelet (in my context specifically, I'm thinking about OpenShift deployments) could handle injection (whatever method of receiving config info the user selects) in which case the kubelet wouldn't necessarily have to do anything.

**Comment by thockin** [comment]
I don't think there's a design issue open for this, but my general feeling
comes down to a few things:

* Anything you can do without privileges (e.g. git clone) should not be run
by privileged things (e.g. kubelet)

* Anything that consumes resources (e.g. running a process periodically)
should run inside a user's pod

* Composable is good, monolithic is bad

* SPOF is bad

All of those things say "containers" to me.  I think it's open as to
whether the user-facing experience is literally "add these containers to
your pod" or is more abstracted (like volumes).  I'm not AGAINST
abstracting the concepts and implementing them as side-car containers, but
I am worried that the amount of things you end up needing to expose
approaches the full api.Container struct.

What I *am* against is kubelet doing potentially costly things on behalf of
users when it doesn't HAVE to.  Isolation is hard.  Accounting is hard.
Availability is hard.  Visibility is hard.  Customization is hard.
Security is hard.

Discuss...

**Comment by bgrant0607** [comment]
I agree with all of @thockin's bullets. In particular, I agree we shouldn't be invoking git, pulling URLs, etc. Those should be done by containers. Even `docker pull` really should be invoked inside some user's container -- our internal equivalent is.

That said, the reason Kubernetes exists is to make common tasks easier. So, even if it were *possible* for users to do this themselves, we should seriously consider what we could do to make it easier, ideally at least as easy as other systems, if not easier.

I think there are a few areas where we should seriously consider helping:
* We should provide some kind of convenience for setting environment variables.
* We need to provide a way to reflect system information into containers: downward API #386.
* As much as we dislike the volumes-from pattern advocated within the Docker community, we should make it easy to onboard those users somehow.
* I also think we should support #831 in some fashion -- make it easy to use a container to statically and/or dynamically populate a volume.
* We need to make it easy to debug container volume fetch and execution failures and performance problems.
* We should provide some kind of container startup-order orchestration. I think it's reasonable to do something custom for container volumes.
* We should provide lifecycle hooks for notifications of data changes. We don't need another built-in notification mechanism. Containers dynamically updating data, such as git sync-er, should be able to send signals, etc. to other containers within the pod once we have shared PID namespaces and the downward API.

**Comment by bgrant0607** [comment]
We're currently discussing implementing something substantially similar to the new Secret API.

**Comment by davidopp** [comment]
Issue number for that discussion? Or do you just mean "we currently think we will implement this feature using something like the new secret API, but haven't thought about it beyond that"?

**Comment by zvbuhl** [comment]
@thockin, I don't know that environment variables are a hack, but whether they are or not they sure are useful.  They're present on every platform; they require no file IO; they're composable; they require no third-party APIs. Those are non-negligible features.

**Comment by stefwalter** [comment]
Further work on this done here: #10982

**Comment by bgrant0607** [comment]
cc @kelseyhightower

**Comment by bgrant0607** [comment]
Putting a link here so I remember to take a look: https://github.com/kelseyhightower/confd

**Comment by bketelsen** [comment]
@kelseyhightower and I also wrote crypt[1], which might be interesting in that it uses etcd/consul as a backend but allows configurations to be encrypted.

[1] https://github.com/xordataexchange/crypt

**Comment by lavalamp** [comment]
Can someone summarize the action items remaining on this issue?

**Comment by bgrant0607** [comment]
Closing in favor of #18455
