### ISSUE TITLE
Configuring authentication for AWS ELB and multiple Kubernetes masters

### ISSUE THREAD

**Issue by jimmycuadra** [kubernetes/kubernetes#15546]
I'm working on a high availability Kubernetes cluster on AWS. I have two k8s master instances and an Elastic Load Balancer sitting in front of them. The API servers on each master are configured to use client certificate authentication. I believe it may not be possible in this set up to configure the load balancer for health checks and forwarding requests.

ELB health checks must supply a protocol (one of HTTP, HTTPS, TCP, or SSL), a port, and for HTTP(S) health checks, a path. For HTTP(S), it will make a GET request as configured and expect a 200 response.

Similarly, incoming connections can be received via HTTP, HTTPS, TCP, or SSL and are forwarded onto the EC2 instances with a matching protocol. The ELB terminates SSL if not configured to connect to the back end EC2 instances with HTTPS/SSL. To receive external connections, an SSL cert and key must be uploaded. To connect to a back end EC2 instance with SSL, the cert used by the back end must be uploaded as well. I've configured my ELB to connect to the Kubernetes master instances using HTTPS:443/healthz.

The problem is that when run with HTTPS and client certificate authentication enabled, the Kubernetes API server rejects health checks from the ELB because it expects all requests, including /healthz to supply a client certificate, and there isn't a way to configure the ELB to provide one. I'm guessing that if the health check were disabled and I just had the ELB assume the instances were always healthy, it would also not be able to forward an external client's certificate on to the back end for proper authentication with the Kubernetes API. I could also change the health check to use TCP/SSL without HTTP(S), but I think the external client requests would still be an issue. As far as I know, it's not possible to set custom headers, so token auth and basic auth are also out, at least for health checks.

Any suggestions on how to achieve load balanced Kubernetes masters on AWS given these constraints?

**Comment by dhawal55** [comment]
I have a similar setup and I configured the ELB to use HTTP (instead of HTTPS) for health check. On the EC2 instance, I have setup security group to allow HTTP traffic only from the ELB. So it protects against unauthenticated access from anywhere else other then ELB.

For external clients, I have the ELB listener configured as follows:
Load Balancer Protocol = TCP
Load Balancer Port = 443
Instance Protocol = TCP
Instance Port = 443

With the above setting, the SSL termination occurs at the node (EC2 instance) instead of at ELB.

Hope this helps.

**Comment by jimmycuadra** [comment]
Thank you, that was very helpful! Does using TCP instead of HTTPS for the listener means that incoming requests have the ELB's IP address instead of the user's? I'm not sure if this actually matters. I guess the Kubernetes API doesn't care about the X-Forwarded-For HTTP header.

**Comment by philk** [comment]
Yup, when you use an ELB in TCP mode you lose the origin information unless what you're passing to supports the PROXY protocol: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html

**Comment by fabioy** [comment]
Is this issue still active? If not, please close it. 

Thank you.

**Comment by jimmycuadra** [comment]
I haven't confirmed a workaround for this yet, but I think I can get it working. Closing for now!

**Comment by stevesloka** [comment]
Hey @jimmycuadra were you able to get this working? I'm in the same position right now with the same question of how to get my ELB to healthcheck my api servers.

**Comment by jimmycuadra** [comment]
Using HTTP for the health check and as described by dhawal55 gets the job done.

**Comment by stevesloka** [comment]
Thanks @jimmycuadra I finally got it all working!

**Comment by alexraju** [comment]
I had to use ELB "TCP:443" as "ping target" for it to work.

**Comment by jimmycuadra** [comment]
For anyone still finding this issue via Google/GitHub search, you can see the details of how I ended up doing this in the k8s cluster deployment tool I'm building at my company: https://github.com/InQuicker/kaws. The important parts, with regards to this issue, are the definition of the load balancers in `terraform/balancers.tf`, and the security groups assigned to the balancers, k8s masters/nodes in `terraform/security.tf`.

**Comment by sachincab** [comment]
In our case, we have couple of master nodes behind ELB. I tried to use ingress and added TLS apiserver-key.pem and apiserver crt in secrets.

http://kubernetes.io/docs/user-guide/ingress/#TLS
From AWS ELB,  TLS seems to be working fine.
On ELB, I have rule like this:
HTTPS	443	HTTPS	443

However I get 401 Unauthorized error, do I need to pass any client certificate here?
TLS with kubernetes.default.svc.cluster.local hostname works fine by passing client-certificate and client-key. Same client-certificate and client-key does not work for external hostname for apiserver.

Any clue on this one, thanks?
 
```
* 	 subjectAltName: host matched
* 	 SSL certificate verify ok.
> GET /version HTTP/1.1
> Host: host
> User-Agent: curl/7.47.1
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 10 Aug 2016 15:43:01 GMT
< X-Content-Type-Options: nosniff
< Content-Length: 13
< Connection: keep-alive
<
Unauthorized

```
**ingress details:**
Namespace:		default
Address:
Default backend:	kubernetes:443 (172.18.2.4:443,172.18.2.5:443)
TLS:
  testsecret terminates
Rules:
  Host	Path	Backends
  ----	----	--------
  *	* 	kubernetes:443 (172.18.2.4:443,172.18.2.5:443)
Annotations:
No events.

**TLS cert details:**
kubectl describe secrets testsecret
Name:		testsecret
Namespace:	default
Labels:		<none>
Annotations:	<none>

Type:	Opaque

Data
====
tls.crt:	1675 bytes
tls.key:	1679 bytes
