### ISSUE TITLE
Kubectl get in a namespace that doesn't exist gives an unclear error

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#15542]
For example, 
kubectl get pods counter --namespace=notexist 

The output is:
Error from server: pods "counter" not found

And also kubectl delete has the same problem.

**Comment by derekwaynecarr** [comment]
@deads2k - does changing this leak any information when namespace is auth
protected?

**Comment by derekwaynecarr** [comment]
looks like we updated to return a 404 instead of a 403 here:
https://github.com/kubernetes/kubernetes/pull/14012

we could look to make the message better on delete at least.

**Comment by feihujiang** [comment]
Delete resource API return a 404 now, and the message is correct, it is ```namespaces "notexist" not found```. But ```kubectl delete``` use get resource API firstly now, get resource returns the unclear message. As I know, delete handler in APIServer would get the resource firstly. I don't know why ```kubectl delete``` should get the resource firstly. Maybe we should ask @kubernetes/kubectl

**Comment by deads2k** [comment]
> As I know, delete handler in APIServer would get the resource firstly. I don't know why kubectl delete should get the resource firstly. Maybe we should ask @kubernetes/kubectl

The `resource.Builder` is used to get the items.  This is necessary in the general case to support reaping of related objects.  That requires a `get`.  You can use the `--ignore-not-found` option to avoid failing on a 404.

Code could be special cased depending on values of related flags, but I doubt we'd do that.
