### ISSUE TITLE
Fix Prometheus metrics in kubelet to measure meaningful performance metrics

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#15554]
Many metrics defined in [`pkg/kubelet/metrics/metrics.go`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/metrics/metrics.go) are unused or no longer relevant/correct.
We need to fix them to show meaningful numbers.

E.g., we should measure the latency along the critical path of a pod update. 
1. kubelet watcher receives pod (kubelet/config) 
2. kubelet dispatches work (kubelet.go)
3. pod worker picks up the work (pod_worker.go)
4. finished sync
5. update pod status

Note that kubelet may overwrite the pod update for a pod worker when it's busy syncing. To preserve the correct sync type, we need to intelligently merge the sync type when overwriting the previous update. E.g., `SyncPodUpdate` and `SyncPodSync` -> `SyncPodUpdate`.

This is related to #11858, #12483. Today in an e2e test, we scrape the /metrics endpoints of all nodes individually and parse the raw output to get the latencies. Once #11858 is completed, we can launch a prometheus server pod to scrape the data from each node in the test, and then query the pod for data.

**Comment by jimmidyson** [comment]
@yujuhong #15612 fixes #11858 so once merged Prometheus metrics will be labelled with Kubernetes metadata (node, namespace, pod name, container name, image, etc). Latest release of Prometheus also has [autodiscovery](http://prometheus.io/docs/operating/configuration/#kubernetes-sd-configurations-kubernetes_sd_config) of nodes built-in so configuration should be super simple.

**Comment by yujuhong** [comment]
@jimmidyson, thanks for the update! This would make performance measurement much easier. The rest of the work involves fixing the metrics in kubelet (the current issue) and get a long running dashboard up (e.g., http://perf-dash.k8s.io).

**Comment by jimmidyson** [comment]
@yujuhong If you're interested, I could put together some grafana dashboards for the perf stuff quite easily. Prometheus-Grafana integration is in Grafana master now. You may want to build your own dashboarding app of course - but just so you know the choice is there.

**Comment by yujuhong** [comment]
@jimmidyson, that'd be great, thanks. I think we should have a dashboard first, and think about whether we need to build our own app later :-)

**Comment by jimmidyson** [comment]
@yujuhong Here's a first attempt at a perf dashboard similar to what you had but using Grafana (master branch to get Prometheus integration).
![selection_016](https://cloud.githubusercontent.com/assets/464659/10733486/f2d60ee2-7bf6-11e5-8e03-65275a343053.png)

Dashboards available at https://github.com/jimmidyson/prometheus-grafana-dashboards

**Comment by yujuhong** [comment]
@jimmidyson, this looks great, thanks!  

We should consider running a prometheus server pod to scrape the data for e2e tests. We should also find a long-running cluster to host the dashboard.

/cc @dchen1107

**Comment by yujuhong** [comment]
As opposed to do something similar to http://perf-dash.k8s.io, @vishh suggested that we send the data to cloud monitoring(?) and set alerts. 

@kubernetes/goog-node for suggestions.
