### ISSUE TITLE
Kubemark experiments requests and results

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#15551]
Let's have an issue to track experiments as a spin off from #15064. If someone thinks it's worthwhile to run an experiment edit this entry/add a comment so an owner can edit this entry. I'll publish the results here.

cc @wojtek-t @lavalamp @davidopp @quinton-hoole @timothysc @smarterclayton 

- [ ] 1000 node cluster without events, 16 core master, master memory profile (@timothysc)
- [ ] 1000 node cluster, 16 core master, master and controller-manager memory profile (@smarterclayton)
- [ ] 2000 node cluster without events, n1-highmem-32 master, local-ssd, reduced kubelet poll frequency, disabled rate limit on API server. (@quinton-hoole)

**Comment by quinton-hoole** [comment]
- [ ] 2000 node cluster without events, n1-highmem-32 master, local-ssd, reduced kubelet poll frequency, disabled rate limit on API server.

**Comment by wojtek-t** [comment]
@quinton-hoole - I don't think disabling rate-limitting on API server will work. Yesterday I made an experiment just increasing the QPS limit in controller-manager from 20 to 100 and it completely broke our metrics - on 100-node cluster our components were highly cpu-bounded. So I'm afraid that disabling it completely will just break it. But I agree that all other parameters make sense.

**Comment by quinton-hoole** [comment]
@wojtek-t Fair enough - I thought that the rate limit was currently set to 5 QPS, and meant to suggest increasing it (although I accidentally types 'disable' - Freudian slip :-) ).  It sounds like you have this covered at 20 QPS.  It might be worth trying it at 40 QPS.

**Comment by lavalamp** [comment]
We should figure out why our QPS is so pitiful. If we turn off all watches
& lists is it still this bad?

Or-- imagine we do this experiment: we start two apiservers. We direct all
lists/gets/watches to one, and all create/update/deletes to the other.
Which one falls over? I'm guessing it's actually the read one, and that the
write one will be happy with very high QPS. But the experiment is kind of a
pain to set up.

**Comment by wojtek-t** [comment]
I completely agree that experiment would be very useful. And my feeling is also that the read one would be the more busy one. But I don't know how to do it without a lot of changes everywhere...

**Comment by gmarek** [comment]
None of the experiments above yet, but master on freshly created 1785 cluster saturates 8-9 cores.

**Comment by gmarek** [comment]
Bad news - it doesn't look like 1785 will be working, no matter how big master machine we'll have.
What happens is this:
```
E1023 15:50:23.646712   31736 reflector.go:206] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:153: Failed to watch *api.Pod: Internal error occurred: too old resource version: 423766 (424966)
Oct 23 15:50:24.368: INFO: density53550-46818eda-7989-11e5-ab9d-7446a0bae05f Pods: 30595 out of 53550 created, 11626 running, 7 pending, 18962 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Oct 23 15:50:34.567: INFO: density53550-46818eda-7989-11e5-ab9d-7446a0bae05f Pods: 30595 out of 53550 created, 11626 running, 7 pending, 18962 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady
```
and so on. Basically cluster ceases to do anything. API-server is saturated (~30 CPUs) by handling handshakes (see profile), main etcd goes crazy (event etcd behaves correctly). What we observed is that it saturates it's CPU and constantly generates roughly 1GB of data per 5-10 sec (or at least increases its memory usage in this rate). 

controller-manager and scheduler seems to be idle (or starved on CPU by both API-server and etcd).

[master-cpu-profile-20151023155448.pdf](https://github.com/kubernetes/kubernetes/files/19447/master-cpu-profile-20151023155448.pdf)

**Comment by gmarek** [comment]
cc @quinton-hoole @smarterclayton @wojtek-t @fgrzadkowski @davidopp @lavalamp

**Comment by smarterclayton** [comment]
We probably really need the Watch timeout.

**Comment by smarterclayton** [comment]
Also, you can try switching to a different cipher (RSA instead of elliptic)
- RSA is I think two orders of magnitude faster in Go 1.5.

**Comment by gmarek** [comment]
:) That's pretty much exactly what I said to @wojtek-t, with exactly the same examples. For fair comparison we're generally building binaries in 1.4 (plus we didn't knew that RSA is already implemented in go at all). I'll try RSA next week.

**Comment by hongchaodeng** [comment]
Is the number of "nodes" here meaning [NUM_MINIONS](https://github.com/kubernetes/kubernetes/blob/70d89a3541b175f8c2e1db28e9c2e681442e3077/cluster/kubemark/config-default.sh#L25)?

**Comment by gmarek** [comment]
Yes it's exactly what it means. It's unfortunate that word 'minion' still appears somewhere... @bgrant0607 @wojtek-t

**Comment by jeremyeder** [comment]
Hey @gmarek have you retried this after #15682 ?

**Comment by wojtek-t** [comment]
@jeremyeder we are running Kubemark continuously

**Comment by gmarek** [comment]
@jeremyeder it depends what 'this' you mean. We're continuously running 1000 node clusters, and 1785 node experiment was done on Oct 25th, which is after #15682 was merged (Oct 17th).

**Comment by jeremyeder** [comment]
Thanks guys -- any chance the continuous kubemark data is surfaced anywhere?

**Comment by gmarek** [comment]
I doubt it... I can paste results if you're interested in some specific thing (we're running standard density test there).

**Comment by gmarek** [comment]
I didn't have time to get it done. I think it's obsolete now.
