### ISSUE TITLE
Duplicate EnvVars not allowed in ReplicationControllers?

### ISSUE THREAD

**Issue by mynameismevin** [kubernetes/kubernetes#15550]
I'm working on standing up a 3 node Zookeeper instance, and instead of having separate RCs and Services for each individual pod, I'd like one RC with three instances that keeps all three pods alive. The image is based off the `mesoscloud/zookeeper` image, just with the quorum enabled.

zookeeper-rc.json

```json
{
    "apiVersion": "v1",
    "kind": "ReplicationController",
    "metadata": {
        "name": "zookeeper-test"
    },
    "spec": {
        "replicas": 1,
        "template": {
            "metadata": {
                "labels": {
                    "app": "zookeeper"
                }
            },
            "spec": {
                "containers": [
                    {
                        "env": [
                            {
                                "name": "MYID",
                                "value": "3"
                            },
                            {
                                "name": "SERVERS",
                                "value": "zk1,zk2,zk3"
                            }
                        ],
                        "image": "custom/zookeeper:latest",
                        "name": "zk3",
                        "ports": [
                            {
                                "containerPort": 2181
                            },
                            {
                                "containerPort": 2888
                            },
                            {
                                "containerPort": 3888
                            }
                        ]
                    },
                    {
                        "env": [
                            {
                                "name": "MYID",
                                "value": "2"
                            },
                            {
                                "name": "SERVERS",
                                "value": "zk1,zk2,zk3"
                            }
                        ],
                        "image": "custom/zookeeper:latest",
                        "name": "zk2",
                        "ports": [
                            {
                                "containerPort": 2181
                            },
                            {
                                "containerPort": 2888
                            },
                            {
                                "containerPort": 3888
                            }
                        ]
                    },
                    {
                        "env": [
                            {
                                "name": "MYID",
                                "value": "1"
                            },
                            {
                                "name": "SERVERS",
                                "value": "zk1,zk2,zk3"
                            }
                        ],
                        "image": "custom/zookeeper:latest",
                        "name": "zk1",
                        "ports": [
                            {
                                "containerPort": 2181
                            },
                            {
                                "containerPort": 2888
                            },
                            {
                                "containerPort": 3888
                            }
                        ]
                    }
                ]
            }
        }
    }
}
```
I have them working with one container per RC, but then I have one RC for each pod. Right now this is just testing, but when I scale out to 7+ nodes, and occassionally 13 nodes, I don't want 13 RCs for one ZK deployment.

When I try to deploy this:
```bash
mynameismevin$ kubectl create -f zookeeper-rc.json --validate
The ReplicationController "zookeeper-rc" is invalid:
* spec.template.spec.containers[1].name: duplicate value 'server'
* spec.template.spec.containers[2].name: duplicate value 'server'
```

The EnvVars have to have `"name":"server"` for each container, so that can be passed to ZK so it knows what servers are in the cluster.

Is this a limitation of k8s or am I using this incorrectly?

**Comment by thockin** [comment]
On Tue, Oct 13, 2015 at 8:34 AM, Mike Lloyd <notifications@github.com> wrote:
>
> I'm working on standing up a 3 node Zookeeper instance, and instead of having separate RCs and Services for each individual pod, I'd like one RC with three instances that keeps all three pods alive. The image is based off the mesoscloud/zookeeper image, just with the quorum enabled.
>
> zookeeper-rc.json
>
> {
>     "apiVersion": "v1",
>     "kind": "ReplicationController",
>     "metadata": {
>         "name": "zookeeper-test"
>     },
>     "spec": {
>         "replicas": 1,
>         "template": {
>             "metadata": {
>                 "labels": {
>                     "app": "zookeeper"
>                 }
>             },
>             "spec": {
>                 "containers": [
>                     {
>                         "env": [
>                             {
>                                 "name": "MYID",
>                                 "value": "3"
>                             },
>                             {
>                                 "name": "SERVERS",
>                                 "value": "zk1,zk2,zk3"
>                             }
>                         ],
>                         "image": "custom/zookeeper:latest",
>                         "name": "zk3",
>                         "ports": [
>                             {
>                                 "containerPort": 2181
>                             },
>                             {
>                                 "containerPort": 2888
>                             },
>                             {
>                                 "containerPort": 3888
>                             }
>                         ]
>                     },
>                     {
>                         "env": [
>                             {
>                                 "name": "MYID",
>                                 "value": "2"
>                             },
>                             {
>                                 "name": "SERVERS",
>                                 "value": "zk1,zk2,zk3"
>                             }
>                         ],
>                         "image": "custom/zookeeper:latest",
>                         "name": "zk2",
>                         "ports": [
>                             {
>                                 "containerPort": 2181
>                             },
>                             {
>                                 "containerPort": 2888
>                             },
>                             {
>                                 "containerPort": 3888
>                             }
>                         ]
>                     },
>                     {
>                         "env": [
>                             {
>                                 "name": "MYID",
>                                 "value": "1"
>                             },
>                             {
>                                 "name": "SERVERS",
>                                 "value": "zk1,zk2,zk3"
>                             }
>                         ],
>                         "image": "custom/zookeeper:latest",
>                         "name": "zk1",
>                         "ports": [
>                             {
>                                 "containerPort": 2181
>                             },
>                             {
>                                 "containerPort": 2888
>                             },
>                             {
>                                 "containerPort": 3888
>                             }
>                         ]
>                     }
>                 ]
>             }
>         }
>     }
> }

This is going to create you a pod with three containers all running on
the same machine.  I don't think this is what you want.

> When I try to deploy this:
>
> mynameismevin$ kubectl create -f zookeeper-rc.json --validate
> The ReplicationController "zookeeper-rc" is invalid:
> * spec.template.spec.containers[1].name: duplicate value 'server'
> * spec.template.spec.containers[2].name: duplicate value 'server'

Are you sure the JSON you posted is the JSON you're running?  This is
complaining that you have multiple containers each named "server"
(which is not allowed - container names must be unique).  The JSON
here does not even have the string "server" anywhere.

> The EnvVars have to have "name":"server" for each container, so that can be passed to ZK so it knows what servers are in the cluster.

The above errors are not about env vars - they are about the
podTemplate's container names.

**Comment by mynameismevin** [comment]
Gotcha! That helped with the errors, I resolved it! Thanks!
