### ISSUE TITLE
--cert-dir flag can cause existing certs to be clobbered.

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#15558]
The comments imply, to me, that specifying --cert-dir will cause the apiserver to look in --cert-dir for some appopriately named certs and will use those. This is in lieu of the user specifying --tls-cert-file and --tls-private-key manually.

Two problems: one, the flag descriptions don't tell the user what the cert/key need to be named for them to be auto-picked up. Two, the code doesn't actually look for those files in the --cert-dir. It just clobbers them with Kubernetes's own self-signed certificates.

Of course, it's also possible that I'm just misunderstanding the description of --cert-dir. In that case, I think it would be clearer if --cert-dir said "The directory where self-signed TLS certs are placed".

Relevant code: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L621-L622

(note, util.GenerateSelfSignedCert says in a comment that it will replace any existing certs)

**Comment by dims** [comment]
@colemickens looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/19309 can we close this please?

**Comment by colemickens** [comment]
Looks like there's a lot of discussion on [the newer issue](https://github.com/kubernetes/kubernetes/issues/19309), so I'll close this out.
