### ISSUE TITLE
Rewrite our build system in Go

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#15560]
Things are getting a bit out of hand in `build/`.  We should consider a rewrite in Go before too long.  (E.g. #15422).

**Comment by sgoings** [comment]
I'm interested to know what your ideas are here - I'm willing to help as we have had similar problems maintaining the build system around deis/deis#4038 and I think there is a need for some sort of lightweight release management tool here but I don't want to reinvent a wheel that already exists and I'm just unaware of it.

I've spent quite a bit of time in the [Gradle](http://gradle.org/) ecosystem which seems to be the farthest along in supplying a fantastic workflow for maintaining projects, especially once you start to tie in Netflix's work with their [Nebula plugins](https://github.com/nebula-plugins). Justin Ryan does an awesome job giving a flyover of what plugins they built and why in [this video](https://gradle.org/gradle-netflix-nebula/). However, I think it would be difficult to "sell" a JVM based tool to be a dependency for building/maintaining kubernetes.

Are there other projects/tools (specifically 'go' ones) that you are aware of that would be a good fit for this sector?

**Comment by ihmccreery** [comment]
One of the first steps I'm working on is splitting out release tooling from build tooling.  Looks like in deis/deis#4038, you're just talking about release.  I think a shell script is reasonable for that case.  See #16529 for work I'm doing and progress, (not much yet).

**Comment by david-mcmahon** [comment]
I'm in the process of rewriting our release tooling, in bash.
There's nothing wrong with bash for release and build tooling.  Bash is used widely for this purpose.  Writing good bash is hard but should be the goal.  I'm happy to take on more of this over time.
I'm not sure writing all of the build tooling in a lower level language like go is best, though pieces of it in go or another language can be helpful - in the way that bash calls awk, perl, sed, etc.

**Comment by ihmccreery** [comment]
Agree.

**Comment by thockin** [comment]
The problem is that we're trying to use bash like a real programming
language.  Functions, fine. Arrays are a little sketchy.  Abstract
interfaces implemented by cloud providers that take optional arrays of
arguments is a disaster.

Frankly it's the need to protect against undefined variables (including
empty arrays) that makes bash terrible to use.  Please avoid arrays and
similar garbage that exists in bash but doesn't work in any sane way.
