### ISSUE TITLE
Validate docker 1.8.3 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#15563]
https://github.com/docker/docker/releases/tag/v1.8.3

**Comment by dchen1107** [comment]
cc/ @kubernetes/goog-node

**Comment by yujuhong** [comment]
Too bad v1.8.3 doesn't contain the fix for slow `docker rmi` https://github.com/docker/docker/issues/16771 :(

**Comment by dchen1107** [comment]
Summarizing 4 Failures:

>[Panic!] Resource usage of system containers [It] should not exceed expected amount. 
>/usr/src/go/src/runtime/panic.go:387

The failure is caused by kubelet's resource usage, not related to the new version of docker:

```
Resource usage of system containers 
  should not exceed expected amount.
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitor_resources.go:137
[BeforeEach] Resource usage of system containers
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitor_resources.go:94
>>> testContext.KubeConfig: /usr/local/google/home/dawnchen/.kube/config
[It] should not exceed expected amount.
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitor_resources.go:137
STEP: Getting ResourceConsumption on all nodes
Oct 13 14:07:33.540: INFO: /kubelet on e2e-test-dawnchen-minion-gafn usage: &e2e.containerResourceUsage{Name:"", Timestamp:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, CPUUsageInCores:0.12384363968049587, MemoryUsageInBytes:131133440, MemoryWorkingSetInBytes:128908492, CPUInterval:0}
Oct 13 14:07:33.540: INFO: CPU is too high for /kubelet (0.12384363968049587)

•! Panic [16.539 seconds]
Resource usage of system containers
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitor_resources.go:138
  should not exceed expected amount. [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitor_resources.go:137

  Test Panicked
  assignment to entry in nil map
  /usr/src/go/src/runtime/panic.go:387

  Full Stack Trace
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:140 (0x4f6c7e)
  /usr/src/go/src/testing/testing.go:447 (0x460cef)
  /usr/src/go/src/runtime/asm_amd64.s:2232 (0x440851)
```
>[Fail] Cluster level logging using Elasticsearch [It] should check that logs from pods on all nodes are ingested into Elasticsearch 
>/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/es_cluster_logging.go:163

This is flaky test itself.

>[Fail] Examples e2e [Example]ClusterDns [It] should create pod that uses dns [Conformance] 
>/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:1049

This is flaky test itself.

>[Fail] ServiceLoadBalancer [It] should support simple GET on Ingress ips 
>/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/serviceloadbalancers.go:238

This is flaky test itself.

Ran 142 of 190 Specs in 12739.757 seconds
FAIL! -- 138 Passed | 4 Failed | 2 Pending | 46 Skipped --- FAIL: TestE2E (12740.23s)

**Comment by bgrant0607** [comment]
If this is for 1.1, it needs to be P0 at this point. Should it be?

**Comment by dchen1107** [comment]
Ok, bump this to p0

**Comment by andyzheng0831** [comment]
cc/ @andyzheng0831
cc/ @yinghan

**Comment by bgrant0607** [comment]
@thockin and @ArtfulCoder found a serious bug in 1.8:
https://github.com/docker/docker/issues/17190

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/pull/16052 as a workaround for docker/docker#17190. Closing this issue.
