### ISSUE TITLE
Add clarity into container/image garbage collection in kubelet

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#15564]
We've received plenty of user questions asking whether their container or image GC routine functions correctly. There are two most likely causes:
1. Their GC settings are not aggressive enough. I usually point them to our [GC doc](https://github.com/kubernetes/kubernetes/blob/80f2d89a79bee987e6c1553ff7617a7c71b977d9/docs/admin/garbage-collection.md) to check if varying the parameters would help (thanks to @dalanlan, @pwittrock and @vishh for the doc).
2. GC does not run correctly. This is harder to detect.

To provide more clarity for the second case, we can do:
1. Log more. This is the easiest solution, but reading `kubelet.log` may not be the best experience (for users) as it could be noisy. We also don't want to add more to our logs.
2. Similar to sync loop health check, we can ask each GC component to log a timestamp and fail the check if they are not responsive or haven't been able to successfully run recently.
3. Registers stats to Prometheus. We can ask the users to check the /metrics endpoint. We can also add a Prometheus pod to scrape the data in the future (#11858).

I am leaning towards option (3) since it's easier to customize the metrics we collect, and it's more user-friendly too.
Thoughts? @kubernetes/goog-node

**Comment by yujuhong** [comment]
See #15115 for an example where the more clarity would have helped.

**Comment by vishh** [comment]
> GC does not run correctly. This is harder to detect.

What are the possible scenarios under which GC fails? If this is a binary state, one option is to generate an event and mark the node not schedulable.

Metrics are useful for performance analysis. They are that helpful when it comes to cluster stability.

**Comment by yujuhong** [comment]
> What are the possible scenarios under which GC fails? If this is a binary state, one option is to generate an event and mark the node not schedulable.

I agree that in general metrics should be used for performance analysis, but it could be useful in cases where the failure is not fatal or cannot be solved by restarting kubelet.

GC could fail sporadically if docker misbehaves, couldn't it? We don't kill kubelet if a single docker request fails or takes too long. E.g., there are bugs where docker is slow in removing images, e.g., https://github.com/docker/docker/issues/16771, and restarts kubelet doesn't help at all.

**Comment by yujuhong** [comment]
I think this is still relevant, but would like input from @dashpole

**Comment by dashpole** [comment]
My impression is that https://github.com/kubernetes/kubernetes/issues/57006 is the primary issue driving user confusion.  I am not aware of any major bugs with it, but the events can be misleading, since they "fail", even when the system is WAI.  I believe https://github.com/kubernetes/kubernetes/pull/58229, and https://github.com/kubernetes/kubernetes/pull/57020 will solve this.
