### ISSUE TITLE
http://kubernetes.io/swagger-spec/ is served as text/html

### ISSUE THREAD

**Issue by dolmen** [kubernetes/kubernetes#15571]
http://kubernetes.io/swagger-spec/ is served as `text/html` (which is completely invalid for JSON data) instead of `application/json` or more specific media types suggested in swagger-api/swagger-spec#110.

**Comment by bprashanth** [comment]
@nikhiljindal

**Comment by nikhiljindal** [comment]
Thanks @dolmen for pointing that out!

kubernetes.io is backed by gh-pages branch of our git repo.
http://kubernetes.io/swagger-spec/ is serving https://github.com/kubernetes/kubernetes/blob/gh-pages/swagger-spec/index.html

I am not sure how can I change the media type. Maybe changing the file name to index.json will work? I will try that.
Suggestions on how to fix this welcome!

**Comment by eosrei** [comment]
Github pages will serve `.json` files as the correct MIME type, but it doesn't recognize `index.json` as a website index file. I tried renaming the files to `index.json` and Github serves the files as `application/json`, but Swagger cannot access.

MIME types on GitHub Pages: https://help.github.com/articles/mime-types-on-github-pages/ 

Hopefully this is some help as a starting point for a resolution.

**Comment by nikhiljindal** [comment]
With the move to kubernetes.github.io, http://kubernetes.io/swagger-spec/ is not available at all.

Filed https://github.com/kubernetes/kubernetes.github.io/issues/515

**Comment by dims** [comment]
@nikhiljindal since the page/url does not exist, we can just close out this issue? :)

**Comment by mbohlool** [comment]
agree with @dims. We completely removed the support for /swagger-spec/ in favor of new documentation site.
