### ISSUE TITLE
Mounting host /dev can cause issues with /dev/pts

### ISSUE THREAD

**Issue by vsimonian** [kubernetes/kubernetes#15577]
I followed the [local Docker getting started guide](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md) on Ubuntu 15.10, and found myself experiencing a host of issues with /dev/pts, most notably being unable to start any terminal emulator, being greeted with

```
There was an error creating the child process for this terminal
getpt failed: No such file or directory
```

Stopping Kubernetes and rebooting consistently fixed the issue.

It seems the likely culprit is the mounting of the entire /dev path as a volume in the container per the run command given in the instructions. Is this necessary? What is Kubernetes looking for that it needs in the host /dev? Perhaps it could be a more explicit mount?

**Comment by gmarek** [comment]
cc @saad-ali

**Comment by saad-ali** [comment]
Reasons that I am aware of that Kubelet needs access the host's `/dev/`:
  * Access to /dev/disk, /dev/sd* to mount volumes attached to the node to containers
  * Default termination log is written to `/dev/termination-log`
There may be other reasons that I'm not aware of.

I agree that none of these seem critical for Kubernetes running inside docker.

CC @dchen1107 @brendandburns who might be able to provide more guidance.

**Comment by 4ndrej** [comment]
got this problem on fedora 22 and kubes:
kubernetes-master-1.1.0-0.5.gite44c8e6.fc22.x86_64
kubernetes-node-1.1.0-0.5.gite44c8e6.fc22.x86_64
kubernetes-client-1.1.0-0.5.gite44c8e6.fc22.x86_64

is there any way to get rid of this problem without rebooting machine?

**Comment by 4ndrej** [comment]
it seems that removing
--volume=/dev:/dev \
from Step Two: Run the master (hyperkube kubelet) solve this issue.

**Comment by hsaputra** [comment]
This is also happen in Ubuntu 15.10

**Comment by heapifyman** [comment]
And on Arch Linux but instead of
```getpt failed: No such file or directory```
I get
```getpt failed: access denied```.

**Comment by saad-ali** [comment]
#18230 duplicate

**Comment by saad-ali** [comment]
Should be fixed by https://github.com/kubernetes/kubernetes/pull/20795
