### ISSUE TITLE
remove repair-malformed-updates flag from HEAD when clients are fixed

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#15580]
#15191 introduced a flag `repair-malformed-updates`, when turned on, api server will try to repair the malformed update requests when validating them.

This behavior is wrong, we need to fix the clients that generate malformed update requests and remove this flag and related code in HEAD.

@lavalamp

**Comment by liggitt** [comment]
"finding all clients" is going to be hard for a publicly released API... what is the downside to preserving immutable metadata fields during an update in which the client didn't submit the values? `resourceVersion` and `name` are the ones which uniquely identify the resource intended to be updated. If the client specifies conflicting values for immutable fields, we already fail (appropriately).

**Comment by liggitt** [comment]
cc @smarterclayton

**Comment by liggitt** [comment]
to be clear, I'd like to move the preservation out of the validation step (maybe into `BeforeUpdate`, after `PrepareForUpdate` is called?)

**Comment by caesarxuchao** [comment]
@liggitt, I think the caveat is how can we know if the client is trying to delete a field when it's left blank? The client will think it has successfully deleted the field while actually the api server silently fixes the update request.

**Comment by liggitt** [comment]
I'm comfortable with letting clients that think they're deleting name, uid, and creationTimestamp be confused.

**Comment by caesarxuchao** [comment]
Fair enough. I agree we can move the preservation code for uid, creationTimestamp, deletionTimestamp to another place. How about `DeletionGracePeriodSeconds`? It's not that obvious it shouldn't be deleted.

**Comment by smarterclayton** [comment]
It can only be shortened - we have code paths in the strategy that preserve
it, but the update paths should be visible and distinct for sure.  Same for
the termination timestamp.

**Comment by caesarxuchao** [comment]
Shall the api server do the preservation for `DeletionGracePeriodSeconds` or shall it return an error if it's changed to empty?

**Comment by liggitt** [comment]
When was DeletionGracePeriodSeconds added? If it's made it into a release, we should default to preserving existing behavior unless we can demonstrate that is breaking something, right?

**Comment by smarterclayton** [comment]
It is an error to mutate deletion grace period seconds outside of a delete
call

On Oct 20, 2015, at 6:40 PM, Chao Xu <notifications@github.com> wrote:

Shall the api server do the preservation for DeletionGracePeriodSeconds or
shall it return an error if it's changed to empty?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15580#issuecomment-149722983>
.

**Comment by smarterclayton** [comment]
But, old clients won't set it, so for backwards compat we have to ignore
its absence on a mutation

On Oct 20, 2015, at 6:40 PM, Chao Xu <notifications@github.com> wrote:

Shall the api server do the preservation for DeletionGracePeriodSeconds or
shall it return an error if it's changed to empty?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15580#issuecomment-149722983>
.
