### ISSUE TITLE
kubectl output for get pods seems to print row header for each pod output

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#15588]
abshah@abhidesk:~/go/src/k8s.io/kubernetes$ kctl get --all-namespaces pods 
NAMESPACE             NAME                                            READY     STATUS    RESTARTS   AGE
e2e-tests-dns-20zlc   dns-test-dd8b5b51-720d-11e5-99a2-8851fb5da20e   3/3       Running   0          4s
NAMESPACE             NAME                                            READY     STATUS    RESTARTS   AGE
e2e-tests-dns-314r3   dns-test-dba4033d-720d-11e5-ae51-8851fb5da20e   3/3       Running   0          8s
NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE
kube-system   elasticsearch-logging-v1-kw7pi   1/1       Running   0          3h
NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE
kube-system   elasticsearch-logging-v1-q1ylc   1/1       Running   0          3h
NAMESPACE     NAME                                                READY     STATUS    RESTARTS   AGE
kube-system   fluentd-elasticsearch-e2e-test-abshah-minion-3nb5   1/1       Running   0          3h
NAMESPACE     NAME                                                READY     STATUS    RESTARTS   AGE
kube-system   fluentd-elasticsearch-e2e-test-abshah-minion-3ttl   1/1       Running   0          3h
NAMESPACE     NAME                                                READY     STATUS    RESTARTS   AGE
kube-system   fluentd-elasticsearch-e2e-test-abshah-minion-kac4   1/1       Running   0          3h
NAMESPACE     NAME                 READY     STATUS    RESTARTS   AGE
kube-system   heapster-v10-7jz7u   1/1       Running   0          3h
NAMESPACE     NAME                      READY     STATUS    RESTARTS   AGE
kube-system   kibana-logging-v1-d73xg   1/1       Running   0          3h
NAMESPACE     NAME                READY     STATUS    RESTARTS   AGE
kube-system   kube-dns-v9-lpetp   4/4       Running   0          3h
NAMESPACE     NAME               READY     STATUS    RESTARTS   AGE
kube-system   kube-ui-v3-tc46k   1/1       Running   0          3h
NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE
kube-system   monitoring-influxdb-grafana-v2-uw34c   2/2       Running   0          3h

**Comment by JanetKuo** [comment]
dup #15415
