### ISSUE TITLE
Ingress documentation

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#15583]
While it might not be a strict graduation requirement, it would be good to have user docs for Ingress before 1.1 is released.

**Comment by thockin** [comment]
@bprashanth how much of the docs from contrib do we want to replicate here?  Probably not too much.  Still, we should get something in ASAP.

**Comment by bprashanth** [comment]
Yeah, a pr will happen today. I'll distil some high level information about the Ingress and just link to the controllers in contrib (which have a while lot of documentation on their own).

**Comment by erictune** [comment]
How will that work with docs.k8s.io?  http://docs.k8s.io/docs/user-guide/ingress.html will point to https://github.com/kubernetes/contrib/blob/master/Ingress/controllers/gce/README.md

**Comment by erictune** [comment]
fixed by #15899
