### ISSUE TITLE
e2e failure: "deployment should delete old pods and create new ones" is flake

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#15622]
Expected error:
        <*errors.errorString | 0xc2080e2bd0>: {
            s: "total pods available: 1, less than the min required: 2",
        }
        total pods available: 1, less than the min required: 2
    not to have occurred
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:173

Example failure:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/12677/consoleFull

**Comment by wojtek-t** [comment]
cc @kubernetes/goog-testing @quinton-hoole

**Comment by quinton-hoole** [comment]
I think deployments fall under @kubernetes/goog-control-plane .  Labelled as such.

**Comment by nikhiljindal** [comment]
The flakiness hasnt been reported for a long time.
I guess we can close this?

**Comment by wojtek-t** [comment]
@nikhiljindal - is this test part of regular e2e (i.e. not in flaky)? If so, I think we can close it.

**Comment by nikhiljindal** [comment]
aah you are right, Its marked flaky. I didnt realize that.
https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L166

**Comment by wojtek-t** [comment]
@nikhiljindal - so I didn't pay much attention to it. Can you please check in Jenkins flaky suite if it was healthy?

**Comment by nikhiljindal** [comment]
It has passed the last O(100) runs. Removing it from flake
