### ISSUE TITLE
Common environment variables for all rc / pods inside a same namespace

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kubernetes#15627]
Hello,

I have for all my applications some "standardised" environment variables. Today I need to copy them for all my RC definitions inside a specific namespace (integration / staging / production).
I think a way to specify some "common" environment variables for all rc / pods in a same namespace would be really useful.

Thoughts ?

**Comment by derekwaynecarr** [comment]
@bparees - is this something that you struggle with today?

/cc @kubernetes/rh-cluster-infra

**Comment by thockin** [comment]
I think the right answer here is some use of the not-completed config
object and tying it into env vars or a volume.  This moves the values out
but leaves the boilerplate code in each RC.  I could maybe see something
like a namespaced config object being applied to all pods, but it's a bit
"magical" and that's not good.  I would not be against a design doc to
consider the options.

**Comment by bparees** [comment]
Yes, not being able to do this has definitely been a pain point for some of
our users.

**Comment by smarterclayton** [comment]
We've made a fairly strong set of statements that we don't want to magically inject things into pods - pods have to explicitly reference those things.  Once ConfigData lands, I think it'll be a lot clearer how to set this up with either admission controllers or just good code generation.

**Comment by bgrant0607** [comment]
ConfigData proposal: #6477
Config template parameterization: #11492
Env file request: #8800

**Comment by bgrant0607** [comment]
See also #17097

**Comment by bgrant0607** [comment]
This use case is addressed by PodPreset:
https://kubernetes.io/docs/tasks/run-application/podpreset/

cc @pwittrock @pmorie
