### ISSUE TITLE
Simplify validation logic and errors

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15633]
Validation is inconsistently applied and hard to get right.  The prefix logic needs a rethink, and some bits of validation have found themselves in other files.

Filing this for debt paydown

**Comment by thockin** [comment]
From @bgrant0607:

How we specify fields to NewFieldRequired, NewFieldInvalid, etc. is very inconsistent.

In some places, we specify full paths. For example, spec.ports[%d].port.

In others, we specify only the field name, such as name.

In still other places, we specify some not-necessarily-contiguous subset of the path, such as template.labels.

We should convert all of them to specify full paths, such as spec.template.metadata.labels.

**Comment by bgrant0607** [comment]
This is about validation generally? The issue I filed was about a very specific problem.

**Comment by thockin** [comment]
My point is that there are several things that I think are debt around
validation and they can all be fixed-up roughly together.

**Comment by bprashanth** [comment]
> In some places, we specify full paths. For example, spec.ports[%d].port.
In others, we specify only the field name, such as name.

As long as the callers have applied Prefix in a way that produces the right yaml path of a field this might be ok? I mean:
```
foo().Prefix(spec)
func foo() {
  NewInvalidField(bar)
}
```

This is hard to reason about with local conetxt, but you can't encode full paths in shared functions.

**Comment by thockin** [comment]
I think we should be passing down catenated full paths - it's way easier to
think about than the prefix stuff, in practice.  I am sure there will be
places where that is hard.

**Comment by lavalamp** [comment]
Kicking this out of the milestone. @thockin holler if you disagree.
