### ISSUE TITLE
decouple dbus and iptables

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15636]
iptables should receive some interface that dbus happens to implement instead of coupling.

**Comment by minhlongdo** [comment]
@thockin I am new to this project, could I pick this one up or is someone already working on it?

**Comment by nikhita** [comment]
> could I pick this one up or is someone already working on it?

@minhlongdo Noone is working on it. Go for it! :tada:

**Comment by minhlongdo** [comment]
@nikhita ok, I am going to work on it, it will take a bit longer since this is my first time in this code base

**Comment by nikhita** [comment]
> it will take a bit longer since this is my first time in this code base

@minhlongdo take your time, no hurries! :)

Also, if you have questions - the #kubernetes-dev channel on the Kubernetes slack is a good place to ask and get immediate feedback. If you are not already on the slack, you can sign up [here](http://slack.k8s.io/).

**Comment by vllry** [comment]
Someone else should probably confirm, but this looks like it was already done. `pkg/util/dbus/dbus.go` has an `Interface` type, which I see is used in iptables.

**Comment by danwinship** [comment]
> Someone else should probably confirm, but this looks like it was already done. `pkg/util/dbus/dbus.go` has an `Interface` type, which I see is used in iptables.

That was already the case before this bug was filed, so that's apparently not what @thockin meant.

**Comment by dipayan** [comment]
@thockin @freehan @nikhita I would like to pick this up , if its not resolved yet ? This would my first PR I would really appreciate some help & guidance.

**Comment by thockin** [comment]
What I meant there was that the iptables package should not need to spell out "dbus" ever.  iptables.Runner (or something) should provide enough hooks to let the caller pass in things (e.g. function pointers) that can be called at various moments in the iptables lifecycle.

Like, instead of `iptables.New()` taking a `utildbus.Interface` argument, it could take an instance of it's own `ExternalSync` interface.  That interface would have a method get a chan that triggers a reload.  Then the iptables code could do something like call that method and if it returns non-nil, read from the channel and trigger reloads.

Callers into iptables would do something like:

```
d := dbus.New()
syncer := newFirewalldSyncer(d)
ipt = iptables.New(exec, syncer)
```
and
```
type firewalldSyncer {
    dbus dbus.Interface
}

func (f firewalldSyncer) signalHandler() {
  firewalld := bus.Object(firewalldName, firewalldPath)
  for s := range runner.signal {
      // handle signals
  }
}

func newFirewalldSyncer(d dbus.Interface) iptables.ExternalSyncer {
    return dbusSyncer{d}
}
```

I know that is a bit abstract, but I would have to go re-learn the dbus and firewalld mess.  The point being that the iptables package doesn't know about dbus SPECIFICALLY just abstract "external sync" hooks.  The dbus package is generic dbus.  Only the caller knows to link iptables to firewalld via dbus for external sync.

Frankly, I wonder if we still need this at all?   Is firewalld still a thing on k8s nodes?  Red Hat folks would know.

Or maybe we just abandon this ideal - it makes iptables "purer" but shifts burden onto the caller of iptables.

**Comment by danwinship** [comment]
> Frankly, I wonder if we still need this at all? Is firewalld still a thing on k8s nodes? Red Hat folks would know.

Both Fedora-based and Debian-based distros have firewall-managing packages that assume that they are allowed to delete any iptables rules that they didn't create themselves. (I assume SUSE does as well but haven't looked.) Kubernetes has code to poll iptables and try to notice when this has happened; in theory the firewalld-listener code could just be dropped and we could use the polling code always, but the firewalld code is both more efficient and faster to recover than the plain iptables version, assuming firewalld is being used.

Except that currently we always poll even if we're also listening to firewalld. I actually just started working on fixing this.

/assign

**Comment by mrostecki** [comment]
> (I assume SUSE does as well but haven't looked.)

Yes, openSUSE and SUSE use firewalld by default and we are cool with the direction of using firewalld instead of direct iptables calls.
