### ISSUE TITLE
app-specific pkgs should be under cmd/...

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15635]
I don't think things like pkg/kubelet, pkg/proxy, etc are useful outside of their own commands.  This clutters pkg and makes it less useful.

**Comment by smarterclayton** [comment]
Having to guess whether something is in cmd vs pkg is also a cost - seems like you want a place for libraries, and a place for binaries, but well architected binaries usually just call libraries.  I've liked that cmd is lean (we split cmd into tools/ and cmd/ so we knew what was internal and what was external) so far.

**Comment by thockin** [comment]
pkg/proxy is totally specific to kube-proxy.  pkg/master..

yeah, I know some people (you) link those as libs, and that would be fine
in small scale, but pkg/ has grown out of control.  Finding common purpose
in "this is a lib that implements a binary" and "this is a plausibly
multi-binarfy lib" doesn't seem so bad to me.

**Comment by smarterclayton** [comment]
It's not bad.  We've gone the other direction - cmd/ is required to be the
thinnest possible shim around a real interface somewhere else.  Go code
lives in pkg/, cmd and tools are only there so that we can define a build
convention for hack/build-go.  At the end of the day I don't think this
matters much, I just prefer to have one of "place to look at where
implementation code is".  As we build more unified binaries, I think
putting code under cmd/ will make understanding what depends on what less
clear.  Proxy would be code that is included in any shared binary as an
example, so you'd have cmd/hyperkube depending on
cmd/proxy/bunch/of/libraries.

**Comment by thockin** [comment]
We already have this in order to multi-link hyperkube.  It has to get flag
definitions for each subordinate binary.  Certainly you're not saying flag
definitions belong in general-purpose libraries?  That way lies madness.

**Comment by smarterclayton** [comment]
I don't think they belong in general purpose libraries, but I don't think
pkg/ means "general purpose libraries", so having a package
`cmd/kubelet/app/server/options` is no more desirable than
`pkg/kubelet/app/options`.  We define commands in `pkg/`, and those are
both reusable and intended to support flags.  Whether a flag struct
describes the general use case or specific is really a detail of that
implementation, not of a directory structure.  Defining global flags on
global structs is general bad code hygiene anyway - accepting that flag
definition is wrapped in a `func (opts) Bind(...)` construct makes location
arbitrary.

**Comment by thockin** [comment]
I think this is just a philosophical difference, and I won't convince you
and you won't convince me.  And in the end, it's not THAT important. What
is important is that the layout be less random than it is today.

I happen to like the idea that packages that are really part of a command's
unique functionality live in a place that is nearby to that command's
root.  That doesn't mean that people couldn't import those pkgs, just that
they are very clearly and deliberately breaking the seal on a binary.
Conversely, pkgs that are plausibly generic, that don't have intrinsic
properties that are specific to a single binary, should exist apart from
the cmds that might use them.

We have a general rule in Google's massive single codebase - first you
write a pkg it in your private space and only AFTER a handful of other
people want to use it do you move it up into shared space, and even then
you move it up as little as possible.  It works out pretty well, and
prevents a horde of "I wrote another variant of a btree" libraries from
polluting the top-level space.

Even hyperkube doesn't change my view on this - it cross-links other cmds,
but those cmds are all relatively independent.

We should also distinguish the kube-* commands from teh various build and
doc tools.  That's another mess..

**Comment by smarterclayton** [comment]
I'll point out that we are effectively "the handful of other people who
want to use it" :)  I don't care too much, but I do think the extra
attention we provide on "are these interfaces well factored enough for
reuse" does manifest in them being suitable for some reuse, hence more
library like than is obvious from observing the Kube codebase alone.

**Comment by spiffxp** [comment]
/sig api-machinery
/sig cli
/sig release

IMO this would be a sig-architecture thing, but we don't have that yet, so I'm hitting the SIG's that are affected by extracting things for `kubectl`

**Comment by spiffxp** [comment]
/remove-lifecycle stale
Opened kubernetes/test-infra#6095 because it doesn't make sense to me to have 2 lifecycle/ labels applied to the same issue
