### ISSUE TITLE
Simplify persistent volume controllers

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15632]
Filing this for debt paydown, though I know it's in flight under other names

@markturansky @saad-ali

**Comment by markturansky** [comment]
Here's the related PR: https://github.com/kubernetes/kubernetes/pull/14537

Just 1 controller, explicit sequence flows, and unit/integration tests.   If that PR isn't it, I'll need serious design guidance.

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/pull/14537 merged, punting all other cleanup to next-release

**Comment by thockin** [comment]
@jsafrane I am going to throw this at you and you can link it to the PR or close it.
