### ISSUE TITLE
Need consistency in managing containers we push

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15639]
We have no real process for versioning, documenting, and pushing all the myriad containers we use for testing and other things.

**Comment by ihmccreery** [comment]
@thockin @fgrzadkowski Is this covered by #11751/#18893?

**Comment by fgrzadkowski** [comment]
AFAIU the answer is not. This issue is about images for tests. I'm trying to address production images.

**Comment by roberthbailey** [comment]
We should have a similar set of procedures for test images as production images, right? The only difference is that we may be incrementing the version numbers of test images faster as we won't want to wait for releases to push newer versions.

**Comment by thockin** [comment]
agree.

**Comment by ixdy** [comment]
cc @david-mcmahon

**Comment by ixdy** [comment]
cc @david-mcmahon

**Comment by david-mcmahon** [comment]
Is this still an issue?  We version all containers at release time AFAIK.  What am I missing?

**Comment by thockin** [comment]
1) Version number tags are not consistent.  We have at least "1", "v1",
"1.0" tags in existence.

2) We have no embedded documentation standard (e.g. a /README.txt)

3) We have no embedded Dockerfile standard (e.g. /Dockerfile)

4) We have no naming convention for containers.  "foobar", "foo-bar",
"foo_bar" all exist.

5) We have no guidelines on MAINTAINER metadata

6) We have no guidelines on "latest" tags

7) We have no place to publish the available tags (sadly gcr does not do
this for us)

Some of these things we may say "don't want", but we've just never THOUGHT
about them enough.  I'd at least like to see 1-5 addressed.  It's tedious
to go through an re-tag and/or re-name everything with consistent formats,
but it will pay off when I no longer have to remember whether it is "v1.3"
or just "1.3".

**Comment by ixdy** [comment]
I feel like things have probably gotten worse. Additional issues:

8. Far too many containers in one namespace (`gcr.io/google-containers`)
9. Container definitions (`Dockerfile`, build steps, etc) spread across a variety of repos (kubernetes, contrib, test-infra, and a multitude of feature repos)
10. Related to above, it's difficult to determine where an image's source lives (additional metadata e.g. points 2 and 3 would help) 
11. Build process is fairly inconsistent - usually a `Makefile`, but each one is unique
12. Some containers are multiarch, but most aren't
13. No set release cadence for most images; many are wildly out-of-date
14. Pushing a new image to gcr.io requires finding someone with the right ACLs - it's not automated
15. No consistent base image used between containers - we have scratch, debian, alpine, busybox, ubuntu, etc. (cc @timstclair) 
16. No clear policy for retiring/deleting an old image

**Comment by david-mcmahon** [comment]
cc @rvkubiak

**Comment by rvkubiak** [comment]
I am working on a process for promoting add-on images to the google-containers GCR repo.  The same automation can be reused for multiple registries, so it should be flexible enough to handle testing images also.

I'm working on getting this ready for google-containers and expect to have it running by next week.  After that's working I'd be happy to look at getting it running for additional registries.
