### ISSUE TITLE
precommit is too slow

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15630]
There has to be more we can do to make it not SO INCREDIBLY PAINFUL.  It has accumulated a lot of cruft.  Filing this for debt paydown.

**Comment by bgrant0607** [comment]
These should just be tests instead.

**Comment by k82cn** [comment]
I think just code style check is enough, delegate others to test.

**Comment by MHBauer** [comment]
I honestly completely disabled this after the first couple of failures. A pre-commit hook should be super fast. Don't prevent me from saving my work if I can't compile. 
Prevent me from sharing it, maybe.
Make the slow stuff a pre-push if we're worried about pushing broken builds.

**Comment by thockin** [comment]
Agree. PRs welcome

**Comment by xiangpengzhao** [comment]
Since pre-commit is removed in #47673, we can close these pre-commit related stale issues.
/cc @thockin

**Comment by cblecker** [comment]
Closing as fixed.
/close
