### ISSUE TITLE
pkg/util should contain no code

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15634]
we should move everything into sub-pkgs.

**Comment by resouer** [comment]
Then what left for `util`, only doc.go & format.go ?

**Comment by thockin** [comment]
util should be a directory that holds other directories and nothing else.

**Comment by resouer** [comment]
clear, I'll help with this

**Comment by resouer** [comment]
What pkg name should we give to [backoff](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/backoff.go#L30) ?

p.s. now the caller is like `imageBackOff := util.NewBackOff(resyncInterval, MaxContainerBackOff)`

**Comment by resouer** [comment]
Actually, most of the files shares this problem, for example:
```
type BoolFlag struct {
	// If Set has been invoked this value is true
	provided bool
	// The exact value provided on the flag
	value bool
}
```
If we refactor it to `package boolflag`, the caller will do `bootflag.Boolflag`. It's so wired. 

How to give them a proper package name in these cases? @thockin

**Comment by thockin** [comment]
Are there any other rate or flow-control related util packages?
 pkg/util/throttle.go looks like a fit. util.RateLimiter too.   I'm not
super-keen on backoff's API, but it's OK.

Why not lump these all together into pkg/util/flow (or something short like
that).

While in there, move the fakes (e.g. `util.NewFakeRateLimiter()`) to a
testing/ subdir, and make sure comments are good Godoc-style comments and
tests are clear and coverage is close to 100%

**Comment by thockin** [comment]
pkg/util/flag/tristate.go, type Tristate - BoolFlag is a bad name for it.

**Comment by resouer** [comment]
Em .. roughly summarize it here, what do you think? 

```
	renamed:    util/atomic_value.go -> util/atomic/value.go
    renamed:    util/atomic_value.go -> util/atomic/value.go
    renamed:    util/configuration_map.go -> util/config/configuration_map.go
	renamed:    util/resource_container_linux.go -> util/container/resource_container_linux.go
	renamed:    util/resource_container_unsupported.go -> util/container/resource_container_unsupported.go
	renamed:    util/diff.go -> util/diff/diff.go
	renamed:    util/flags.go -> util/flag/flags.go
	renamed:    util/bool_flag.go -> util/flag/tristate.go
	renamed:    util/throttle.go -> util/flow/throttle.go
    renamed:    util/backoff.go -> util/flow/backoff.go
	renamed:    util/runner.go -> util/func/runner.go
	renamed:    util/runner_test.go -> util/func/runner_test.go
	renamed:    util/hash.go -> util/hash/hash.go
	renamed:    util/hash_test.go -> util/hash/hash_test.go
	renamed:    util/http.go -> util/http/http.go
	renamed:    util/line_delimiter.go -> util/io/line_delimiter.go
	renamed:    util/line_delimiter_test.go -> util/io/line_delimiter_test.go
	renamed:    util/logs.go -> util/log/logs.go
	renamed:    util/trace.go -> util/log/trace.go
	renamed:    util/port_range.go -> util/port/port_range.go
	renamed:    util/port_range_test.go -> util/port/port_range_test.go
	renamed:    util/port_split.go -> util/port/port_split.go
	renamed:    util/port_split_test.go -> util/port/port_split_test.go
	renamed:    util/crypto.go -> util/secure/crypto.go
	renamed:    util/ssh.go -> util/ssh/ssh.go
	renamed:    util/ssh_test.go -> util/ssh/ssh_test.go
	renamed:    util/cache.go -> util/storage/cache.go
	renamed:    util/cache_test.go -> util/storage/cache_test.go
	renamed:    util/escape.go -> util/string/escape.go
	renamed:    util/string_flag.go -> util/string/string_flag.go
	renamed:    util/umask.go -> util/systool/umask.go
	renamed:    util/umask_windows.go -> util/systool/umask_windows.go
	renamed:    util/template.go -> util/template/template.go
	renamed:    util/template_test.go -> util/template/template_test.go
	renamed:    util/fake_handler.go -> util/tesing/fake_handler.go
	renamed:    util/fake_handler_test.go -> util/tesing/fake_handler_test.go
	new file:   util/tesing/fake_rate_limiter.go
	renamed:    util/clock.go -> util/timeutil/clock.go
	renamed:    util/clock_test.go -> util/timeutil/clock_test.go
	renamed:    util/uuid.go -> util/uuid/uuid.go

```

**Comment by resouer** [comment]
@thockin Any suggestion about the refactoring above?

**Comment by thockin** [comment]
On Thu, Oct 29, 2015 at 1:00 AM, Harry Zhang <notifications@github.com> wrote:
>
> Em .. roughly summarize it here, what do you think?
>
>     renamed:    util/atomic_value.go -> util/atomic/value.go
>     renamed:    util/atomic_value.go -> util/atomic/value.go

As discussed elsewhere - good :)

>     renamed:    util/configuration_map.go -> util/config/configuration_map.go

This is borderline useless - no comments and no tests.  I shake my
fist at you @smarterclayton!  We should move this to
cmd/kube-apiserver/app where it is used.

>     renamed:    util/resource_container_linux.go -> util/container/resource_container_linux.go
>     renamed:    util/resource_container_unsupported.go -> util/container/resource_container_unsupported.go

We can probably remove the kube-proxy call to this lib, which leaves
just kubelet.  What do you think @vishh?  This can just move to one of
the kubelet dirs.

>     renamed:    util/diff.go -> util/diff/diff.go
>     renamed:    util/flags.go -> util/flag/flags.go

ok

>     renamed:    util/bool_flag.go -> util/flag/tristate.go

I'd just leave it called "bool_flag.go" unless you also want to fix it
at all callsites.

>     renamed:    util/throttle.go -> util/flow/throttle.go
>     renamed:    util/backoff.go -> util/flow/backoff.go

ok


>     renamed:    util/runner.go -> util/func/runner.go
>     renamed:    util/runner_test.go -> util/func/runner_test.go

ok

>     renamed:    util/hash.go -> util/hash/hash.go
>     renamed:    util/hash_test.go -> util/hash/hash_test.go

ok

>     renamed:    util/http.go -> util/http/http.go

ok

>     renamed:    util/line_delimiter.go -> util/io/line_delimiter.go
>     renamed:    util/line_delimiter_test.go -> util/io/line_delimiter_test.go

ugg, I hate this lib.  Fine.

>     renamed:    util/logs.go -> util/log/logs.go
>     renamed:    util/trace.go -> util/log/trace.go
>     renamed:    util/port_range.go -> util/port/port_range.go
>     renamed:    util/port_range_test.go -> util/port/port_range_test.go

ok

>     renamed:    util/port_split.go -> util/port/port_split.go
>     renamed:    util/port_split_test.go -> util/port/port_split_test.go

how about `net` as the pkg for this?

>     renamed:    util/crypto.go -> util/secure/crypto.go
>     renamed:    util/ssh.go -> util/ssh/ssh.go
>     renamed:    util/ssh_test.go -> util/ssh/ssh_test.go
>     renamed:    util/cache.go -> util/storage/cache.go
>     renamed:    util/cache_test.go -> util/storage/cache_test.go

ok

>     renamed:    util/escape.go -> util/string/escape.go

strings

>     renamed:    util/string_flag.go -> util/string/string_flag.go

this should go with flags

>     renamed:    util/umask.go -> util/systool/umask.go
>     renamed:    util/umask_windows.go -> util/systool/umask_windows.go

This should just be moved alongside the only caller of it.

>     renamed:    util/template.go -> util/template/template.go
>     renamed:    util/template_test.go -> util/template/template_test.go

ok

>     renamed:    util/fake_handler.go -> util/tesing/fake_handler.go
>     renamed:    util/fake_handler_test.go -> util/tesing/fake_handler_test.go

testing but yes

>     new file:   util/tesing/fake_rate_limiter.go

should be flow/testing/fake_rate_limiter.go - put test utils under
their "real" packages

>     renamed:    util/clock.go -> util/timeutil/clock.go
>     renamed:    util/clock_test.go -> util/timeutil/clock_test.go

why timeutil and not time ?

There's a Fake here that should be in a testing sub-pkg, too.

>     renamed:    util/uuid.go -> util/uuid/uuid.go

ok

**Comment by resouer** [comment]
Thanks, Tim, I was once planning to post a new design here.

**Comment by smarterclayton** [comment]
I think that was my first Kube commit, so I claim newbish.

**Comment by resouer** [comment]
@thockin Two questions:

1. Are we talking about removing usage of `ResourceContainer` in proxy's config? Why it is useless may I ask?
2. There are still plenty of codes in `util.go` , how should we deal with them? Find a proper directory (maybe not so easy ... )?

**Comment by thockin** [comment]
1) proxy normally runs as a container now

2) one at a time, find better homes.  Not easy, but we can just keep
chipping away at it.

**Comment by xiangpengzhao** [comment]
still not be cleant up completely...
/sig api-machinery
