### ISSUE TITLE
Liveness checks against a pod that supports keep-alive are broken

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#15643]
Scenario:

1. User running a liveness probe against HTTP 8080
2. Default delay 30s, timeout 3s, no interval set
3. Pod is a unicorn server which supports keep-alive, but has a 30s timeout

Symptom: pod is restarted continuously with:

```
Liveness probe failed: Get http://10.1.1.46:8080/: read tcp 10.1.1.46:8080: use of closed network connection (4 times in the last 2 minutes, 31 seconds)
```

We allow keep-alive, which means the TCP connection stays in the golang transport.  After 30s, unicorn closes the connection but we don't see it.  The next liveness check tries to connect to the pod, but because of the golang client library, can't open the connection (because the connection in the pool is closed and stale).  It returns an error which results in the kubelet killing the pod.

2 changes:

1. We probably shouldn't use client-keepalive from the health checker, or, if we do
2. We should check for use of closed network connection errors explicitly and retry (the Go http library clears the connection from the pool so a new connection will be opened on the next request).

This is fairly high severity because liveness checks are broken in real world use cases.

**Comment by smarterclayton** [comment]
I think this should be fixed and back ported to 1.1

**Comment by bprashanth** [comment]
So I think that maps to:
1. just create the transport with DisableKeepAlives
2. defer CloseIdleConnections (since we read the body this should be enough?)

@kubernetes/goog-node

**Comment by dchen1107** [comment]
cc/ @mikedanese @timstclair

**Comment by smarterclayton** [comment]
I think - however, if we're health checking a lot of pods at a rapid clip we could be creating lots of TCP sockets.  Probably not at bad scales, but also a possibility.

**Comment by timstclair** [comment]
> 2. We should check for use of closed network connection errors explicitly and retry (the Go http library clears the connection from the pool so a new connection will be opened on the next request).

The prober currently retries up to 3 times on error or failure. If the connection is cleared after the first failure, why isn't the retry succeeding? (Note that I'm thinking about changing this logic to only retry on error. Discussing [here](https://github.com/kubernetes/kubernetes/issues/12866))

> Pod is a unicorn server which supports keep-alive, but has a 30s timeout

The default probe interval is 10s, why is the timeout being reached? If it is because of the initial 30s delay, why is the connection being opened during the delay?

**Comment by smarterclayton** [comment]
It's possible each probe opens a new connection, and subsequents are
reusing multiple old connections out of the pool.  Hard to say.  We deal
with this all over in the code today (search for "closed network
connection") - it's essentially an io.EOF that isn't really an EOF but most
of the time you want to treat it that way.

**Comment by liggitt** [comment]
> if we're health checking a lot of pods at a rapid clip we could be creating lots of TCP sockets

keep-alive only helps you if you're repeatedly talking to the same remote addr... if you're checking lots of pods with different IPs/ports, keep-alive will do nothing for you

**Comment by bprashanth** [comment]
eitherway a keep-alived liveness probe on the node feels like over optimization

**Comment by smarterclayton** [comment]
Agree

On Oct 14, 2015, at 5:12 PM, Prashanth B <notifications@github.com> wrote:

eitherway a keep-alived liveness probe on the node feels like over
optimization

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15643#issuecomment-148201852>
.

**Comment by bgrant0607** [comment]
If this is for 1.1, it needs to be P0 at this point. Should it be?

**Comment by smarterclayton** [comment]
I know we've had it reported by a fair number of people.  I'm not sure
though whether there is a workaround except "don't use liveness"

**Comment by dchen1107** [comment]
Ok, let's disable keep-alive for liveness probe for 1.1 release. I promote this to p0.

**Comment by brendandburns** [comment]
Assigning to @yujuhong since she authord #15733

**Comment by davidopp** [comment]
Can we move this out of v1.1 milestone now that #15733 has been merged?

**Comment by dchen1107** [comment]
#15733 was merged, I am closing the issue. @yujuhong Please make sure cherry-picking your pr. Thanks!
