### ISSUE TITLE
soak cluster should not run daemon/node restart tests

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#15649]
We should be testing the reliability of a long-running cluster. These tests kill/restart components or nodes in the cluster, defeating the purpose of a soak cluster.

**Comment by yujuhong** [comment]
Example tests:

- Nodes\sResize
- Services.*restarting
- DaemonRestart
- Nodes\sResize
- Reboot
- Etcd failure

@quinton-hoole @ixdy

**Comment by quinton-hoole** [comment]
@yujuhong Agreed.

Some of them already seem to be skipped:

https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L184

GCE_SOAK_CONTINUOUS_SKIP_TESTS=(
    "Density.*30\spods"
    "Elasticsearch"
    "Etcd.*SIGKILL"
    "external\sload\sbalancer"
    "identically\snamed\sservices"
    "network\spartition"
    "Services.*Type\sgoes\sfrom"
    )
Q

**Comment by quinton-hoole** [comment]
@ArtfulCoder FYI

**Comment by yujuhong** [comment]
It'd be hard to prevent regression as more tests are added. It might be better if we explicitly define a set of DISRUPTIVE_TESTS, and include them wherever needed, e.g., GCE_PARALLEL_SKIP_TESTS and GCE_SOAK_CONTINUOUS_SKIP_TESTS. That way, people who are adding tests will be aware of the category. @quinton-hoole, WDYT?

**Comment by quinton-hoole** [comment]
@yujuhong Agreed, that seems like a good idea. Want to send in a PR?  Or at least open an issue?
