### ISSUE TITLE
Autoscaling docs

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15652]
We need up-to-date docs for autoscaling once we finalize the API #15315, #15549.

1. User guide doc that explains the feature
2. Example in docs/user-guide (not in examples)
3. Update, unify, and move the design docs to docs/design:
   1. https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/autoscaling.md
   2. https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/horizontal-pod-autoscaler.md

cc @jszczepkowski @fgrzadkowski @RichieEscarez

**Comment by davidopp** [comment]
> https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/horizontal-pod-autoscaler.md

Personally I would leave this one in proposals and put a big note at the top that the document is superseded by the individual docs on HPA and cluster autoscaling.

**Comment by davidopp** [comment]
> https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/autoscaling.md

Personally I would leave this one in proposals and put a big note at the top that the document is superseded by the individual docs on HPA and cluster autoscaling.

(Ignore previous email, I had the wrong link.)

**Comment by davidopp** [comment]
nit: I don't think we should mark documentation issues as P0, even if they're urgently needed for the next release.

**Comment by jszczepkowski** [comment]
@bgrant0607 
> Example in docs/user-guide (not in examples)

So, our example should be moved from ``examples/extensions/horizontal-pod-autoscaling/`` to ``docs/user-guide/horizontal-pod-autoscaling``?

**Comment by bgrant0607** [comment]
@jszczepkowski /examples is for real apps. Documentation of system features, including examples, belongs in docs/user-guide.

**Comment by davidopp** [comment]
Is #16350 the last PR for this issue, or is there anything else left?

**Comment by davidopp** [comment]
Oh, I guess there's also #16366. Anything else besides those two?

**Comment by jszczepkowski** [comment]
> Oh, I guess there's also #16366. Anything else besides those two?

After merging #16350, #16366 and cherry-picking #16366 to 1.1 this issue should be closed.

**Comment by jszczepkowski** [comment]
HPA documentation is done (all PRs are merged and chery-picked to 1.1).
