### ISSUE TITLE
All fields passed to NewFieldFoo() functions should specify full json paths

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15662]
How we specify fields to NewFieldRequired, NewFieldInvalid, etc. is very inconsistent.

In some places, we specify full paths. For example, `spec.ports[%d].port`.

In others, we specify only the field name, such as `name`.

In still other places, we specify some not-necessarily-contiguous subset of the path, such as `template.labels`.

We should convert all of them to specify full paths, such as `spec.template.metadata.labels`.

**Comment by thockin** [comment]
The biggest problem with this is indices, but I agree.  I filed #15633
today, I'll fold this in.
