### ISSUE TITLE
Change the network plugin's interface

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#15663]
Currently the network plugin's [interface](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/plugins.go#L49) takes a docker container ID as the parameter. AFAICS, the container ID is used to get the PID of the infra container. So will it be feasible to change it to the PID that holds the network namespace? This would make the interface more generic for other runtimes such as rkt :)

Related https://github.com/kubernetes/kubernetes/issues/15638#issuecomment-148194718

/cc @dchen1107 @jonboulle @thockin

**Comment by thockin** [comment]
Yeah, I apologize - it should never have been docker-specific.

**Comment by dchen1107** [comment]
@yifan-gu thanks for tracking down the issue. Mind to send us a fix to change the interface? Thanks!

**Comment by thockin** [comment]
Bear in mind thee are some external users of this interface - @rajatchopra

**Comment by yifan-gu** [comment]
@thockin Yes, this will break the contract with those plugins binaries.
@dchen1107 I'd like to take it, but probably won't send the fix until next week.

**Comment by dchen1107** [comment]
@freehan is going to handle this one.
