### ISSUE TITLE
Convert all clients that set parameters directly to use Request.VersionedParams()

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#15672]
We now have a generalized mechanism to turn any of our versioned API objects (options) into parameters via `pkg/client/request#VersionedParams` so we should start doing so.

**Comment by smarterclayton** [comment]
Example: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/pods.go#L77 should just be `VersionedParams(deleteOptions, api.Scheme)`.  We should try to remove the nil options check as well.

**Comment by smarterclayton** [comment]
@kubernetes/goog-csi

**Comment by lavalamp** [comment]
I plan on doing this for 1.2.

**Comment by wojtek-t** [comment]
Yes - we should do the same with ListOptions which I'm planning to do too.
However, this is blocked on #16376

**Comment by smarterclayton** [comment]
I think this is done now.
