### ISSUE TITLE
create a udp timeout flag for kubeproxy

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#15680]
Create a udp timeout flag for kube-proxy so users can adjust it based on their use case.
Also, if users are facing dns timeouts, this flag could prove to be useful.
We don't want to increase the default udp timeout since we are getting close to 1.1 release

**Comment by bgrant0607** [comment]
If this is for 1.1, it needs to be P0 at this point.

**Comment by ArtfulCoder** [comment]
https://github.com/kubernetes/kubernetes/pull/15797

This gives users the ability to adjust udpIdleTimeout values.
Especially useful, if they experience dns flakiness and think that the adjusting the timeout can help.

**Comment by thockin** [comment]
Status: PR need to pass CI then done

**Comment by thockin** [comment]
Main PR is in.  Abhi is out, I'll do a CP today.
