### ISSUE TITLE
multinode sample on local VM docker-machine

### ISSUE THREAD

**Issue by andrevtg** [kubernetes/kubernetes#15688]
Any specific reason why not to support the multinode sample on a local setup done with docker-machine on VirtualBox?

I could gladly go for it and make a PR if I succeed, unless there is a road block ahead for this built-in Linux distro (lsb_release says "Boot2Docker 1.8.2").

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/community/pull/629
