### ISSUE TITLE
Delete API for autoscaling based on raw resources (CPU/Memory usage)

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#15685]
For 1.1 we plan to scale based on cpu request utilization (see #15684)

Subtasks:
- [ ] Delete API
- [ ] Clean implementation
- [ ] Delete kubectl support to print status
- [ ] Delete e2e tests

@bgrant0607 @derekwaynecarr @jszczepkowski @piosz

**Comment by derekwaynecarr** [comment]
The issue proliferation around graduating this feature is becoming intense!

**Comment by jszczepkowski** [comment]
#15706 is merged. Closing.

**Comment by fgrzadkowski** [comment]
@jszczepkowski This issue covers also e2e tests. Do we have them?

**Comment by fgrzadkowski** [comment]
@jszczepkowski Oh, my bad. Please ignore :) I looked at the wrong PR :)

**Comment by jszczepkowski** [comment]
@fgrzadkowski 
> This issue covers also e2e tests. Do we have them?
Yes: #15770.
