### ISSUE TITLE
Reflector ListWatch should use Jitter to avoid aligning resync

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#15683]
Nodes use ListWatch for pod, service, and endpoint retrieval.  Clusters that undergo a shared restart, or are scaled up at the same time, may end up synchronizing their requests and creating load spikes (we're seeing it as described here https://github.com/openshift/origin/issues/5106#issuecomment-148234658).

We should use `util.Jitter()` that is relative to the resync period (1/20th? 1/50th?) to introduce drift.

**Comment by smarterclayton** [comment]
@kubernetes/goog-csi @kubernetes/rh-platform-management

**Comment by wojtek-t** [comment]
We use randomizing the length of the watch request so this shouldn't happen.

**Comment by liggitt** [comment]
> We use randomizing the length of the watch request so this shouldn't happen.

the reflector will still proactively terminate at exactly the resync period

**Comment by wojtek-t** [comment]
@liggitt - sure I think I wanted to write something completely different, but was thinking about a different issue when writing this :)

What I wanted to write is that, we are already trying to randomize the resync periods. So far I changed some of them in our controllers - see
https://github.com/kubernetes/kubernetes/pull/15153

We can do more of that in our components (controllers, kubelets).

The question is what to do with external clients, but I'm not sure how big problem it is.

**Comment by timothysc** [comment]
@bprashanth more thundering herd issues. 

/cc @kubernetes/sig-scalability

**Comment by smarterclayton** [comment]
I'd like to make resync variant based on the size of the cache as well,
with some well chosen constant factors.  That would be a slightly different
factoring, but could account for both the need to jitter and
scale-invariance.

**Comment by lavalamp** [comment]
@wojtek-t, is there anything left to do on this, or did your changes take care of it?

**Comment by wojtek-t** [comment]
IIUC what Clayton wants is to solve it at the framework level. What is currently done is (in most cases), we just randomize the resync period when passing it as parameter to reflector.
So I would treat this is issue as "technical debt".

**Comment by timothysc** [comment]
I believe we've added jitter on most things now, move to close.
