### ISSUE TITLE
On kubernetes.io "Quick Walkthrough (Basics Tutorials)" is blank

### ISSUE THREAD

**Issue by cristicbz** [kubernetes/kubernetes#15699]
The page on "Documentation > Quick Walkthrough (Basics Tutorials)" contains a "Table of contents:" heading but is otherwise blank.

**Comment by goltermann** [comment]
Looks fixed.  http://kubernetes.io/v1.0/basicstutorials.html had nothing but a TOC, whereas http://kubernetes.io/v1.1/basicstutorials.html has a sentence at the top describing it.  Not sure if we want to add more there or not.
