### ISSUE TITLE
On kubernetes.io AWS link 404-s

### ISSUE THREAD

**Issue by cristicbz** [kubernetes/kubernetes#15698]
Going to "Documentation > Turn-Key Cloud Solutions > AWS" takes you to http://kubernetes.io/v1.0/docs/getting-started-guides/AWS.html which 404s and then redirects back to homepage.

**Comment by jtblin** [comment]
The issue doesn't exist for the current site / `v1.1` anymore. Going to "Documentation > Installing Kubernetes and Creating Clusters > Turn-Key Cloud Solutions > AWS" takes you to the correct page. I suggest to close the issue.

**Comment by justinsb** [comment]
The problem is still visible here though: http://kubernetes.io/v1.0/gs-turnkey.html

**Comment by justinsb** [comment]
I have no idea how that is built though.

**Comment by davidopp** [comment]
Assigning to @bgrant0607 to find someone to fix it.

**Comment by bgrant0607** [comment]
We're doing massive surgery to the website. Don't know if/when we'll get to this.

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by bgrant0607** [comment]
Obsolete
