### ISSUE TITLE
Consider reverse DNS records for services

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15690]
Running a wildcard DNS lookup returns a bunch of IPs, but I can't lookup those IPs into a name.  Also, some DNS tools do reverse lookups of IPs they are given (not sure why).  I don't see any reason NOT to support reverse lookups for services.. Anyone?

**Comment by thockin** [comment]
Fixed!

**Comment by derekwaynecarr** [comment]
@thockin - when was this fixed?  Is there a PR I can track?  I got lost following issue chain.

**Comment by thockin** [comment]
This was fixed as part of the kube-dns rewrite

**Comment by Grillz** [comment]
Is there any documentation related to this fix?
