### ISSUE TITLE
The result of accessed "all namespaces" endpoint with fieldSelector=metadata.namespace=default is wrong

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#15701]
I used: ```Get http://127.0.0.1:8080/api/v1/pods``` 
       or ```Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=metadata.name=counter```
The result is: 
~~~
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/pods",
    "resourceVersion": "10628"
  },
  "items": [
    {
      "metadata": {
        "name": "counter",
        "namespace": "default",
   ......
}
~~~
It works, and we can see there is a pod named counter and the namespace is default

But when I used:
```Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=metadata.namespace=default```

The result is:
~~~
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/pods",
    "resourceVersion": "11761"
  },
  "items": []
}
~~~
The result has no pod, I think this is a bug. @lavalamp

**Comment by lavalamp** [comment]
Yes, this is a bug. There is another way to specify the namespace, though, so I'm marking it p2.
