### ISSUE TITLE
Add protocol versions & negotiation for exec, attach, port forward

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#15726]
As seen in #15702, trying to use kubectl from master (which includes #13322) against GKE (currently Kube 1.0.6, which does not include 13322) results in exec falling to function properly. We need to add protocol versions and negotiation to exec, attach, and port-forward to ensure backwards and forwards compatibility.

@smarterclayton @liggitt @lavalamp @kubernetes/kubectl @kubernetes/rh-ux @kubernetes/rh-cluster-infra

**Comment by lavalamp** [comment]
Do non-13322-clients work against 13322-masters?

**Comment by ncdc** [comment]
I'll have to test that out and report back.

**Comment by lavalamp** [comment]
OK. It looks like it's a bit late to revert #13322. It's unfortunate we forgot to test whether it was backwards compatible or not. :(

**Comment by ncdc** [comment]
Ok, with kubectl 1.0.2 against kubelet master, I am able to both `exec -i` and `exec -it`, however, both of them "hang" when you type `exit` and hit enter. With no tty, you can ctrl-c to get out. With a tty, you have to wait several seconds before you regain control of the terminal.

**Comment by lavalamp** [comment]
@ncdc What sort of timeframe are we looking at for a fix for this? Should we just plan on living with it for the 1.1 release, or is a fix easy?

**Comment by ncdc** [comment]
@lavalamp we need to first come up with a plan for how to do the protocol negotiation. Once we do that, it shouldn't be difficult to restore support for the code as it was in 1.0.x (i.e. no defined protocol), and then continue to evolve with new protocol versions as needed.

The exec/attach/port-forward flows all start with an HTTP request with `Connection: Upgrade` and then an `Upgrade` header for either spdy or websockets. The kubelet handles the request, returns `101 switching protocols`, hijacks the connection, and turns it into a multiplexed stream-based connection.

I think we'll want to add a desired stream-protocol-version header to the HTTP request so the kubelet knows what version the client wants to use. An older kubelet won't recognize and handle that, so the client should downgrade to the 1.0.x protocol. A newer kubelet can handle it and respond with a stream-protocol-version in the response to complete the handshake, or reject the connection and return a header indicating what stream-protocol-versions it does support. And if you have an older client that doesn't send the header, the newer kubelet will assume it's the 1.0.x protocol as well.

Does something along those lines sound decent to you?

**Comment by lavalamp** [comment]
Yes, SGTM

**Comment by liggitt** [comment]
cc @benjaminapetersen @stefwalter as interested parties for websocket clients

**Comment by smarterclayton** [comment]
We should reuse the websocket subprotocol rtc definition - websocket exec
handles protocols today, and the same pattern works for any other upgrade
mechanism:

https://tools.ietf.org/html/rfc6455#section-1.9

On Oct 16, 2015, at 8:13 PM, Andy Goldstein <notifications@github.com>
wrote:

@lavalamp <https://github.com/lavalamp> we need to first come up with a
plan for how to do the protocol negotiation. Once we do that, it shouldn't
be difficult to restore support for the code as it was in 1.0.x (i.e. no
defined protocol), and then continue to evolve with new protocol versions
as needed.

The exec/attach/port-forward flows all start with an HTTP request with
Connection:
Upgrade and then an Upgrade header for either spdy or websockets. The
kubelet handles the request, returns 101 switching protocols, hijacks the
connection, and turns it into a multiplexed stream-based connection.

I think we'll want to add a desired stream-protocol-version header to the
HTTP request so the kubelet knows what version the client wants to use. An
older kubelet won't recognize and handle that, so the client should
downgrade to the 1.0.x protocol. A newer kubelet can handle it and respond
with a stream-protocol-version in the response to complete the handshake,
or reject the connection and return a header indicating what
stream-protocol-versions it does support. And if you have an older client
that doesn't send the header, the newer kubelet will assume it's the 1.0.x
protocol as well.

Does something along those lines sound decent to you?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15726#issuecomment-148868991>
.

**Comment by stefwalter** [comment]
Although browsers would be able to negotiate between various WebSocket subprotocols, browsers cannot use the Upgrade header to negotiate between using a WebSocket or falling back to HTTP long poll streaming (and/or even theoretically HTTP/2).

So if kubernetes 1.0 does not have WebSockets for exec/attach then a Web browser would need to determine that before trying to create a WebSocket connection. Essentially a web browser need some indication of this capability external to the WebSocket endpoint.

More specifically, in Cockpit we are not yet using the WebSocket exec/attach endpoints yet, exactly because of this compatibility issue. We are continuing to use HTTP/2 via spawning a kubectl process and talking to it.

**Comment by ncdc** [comment]
I have an initial implementation working on my laptop. I've restored support for the 1.0.x behavior, so a kubectl client from master will now work against a 1.0 kubelet again. I need to finish fleshing this out, which includes fixing the unit tests due to function signature changes, and adding subprotocol negotiation to port forwarding. I'm going to be traveling this afternoon so hopefully I can have something ready for review tomorrow.

**Comment by lavalamp** [comment]
@ncdc awesome, thanks!

**Comment by lavalamp** [comment]
I looked at the upgrade testing we are starting to do, and the e2e in a version-skewed cluster currently is *not* catching this bug. Can we expand the e2e?

**Comment by ncdc** [comment]
@lavalamp I did add exec e2es in a previous PR that should help catch this sort of thing (see e.g. https://github.com/kubernetes/kubernetes/blob/67d3a9316604a0ef2072e24315c13f22944c4684/test/e2e/kubectl.go#L175-L181). Is the version-skewed testing running a master kubectl against a 1.0 kubelet?

**Comment by lavalamp** [comment]
@ncdc Yes, it does (see #16040), and though the test fails at the moment, the relevant step does not fail. Current output below:

```
07:39:36 Kubectl client Simple pod 
07:39:36   should support exec
07:39:36   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:162
07:39:36 [BeforeEach] Kubectl client
07:39:36   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:70
07:39:36 >>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/.kube/config
07:39:41 INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-kubectl-hhjrz
07:39:41 INFO: Get service account default in ns e2e-tests-kubectl-hhjrz failed, ignoring for 5s: serviceaccounts "default" not found
07:39:46 INFO: Service account default in ns e2e-tests-kubectl-hhjrz with secrets found. (5.004895698s)
07:39:46 [BeforeEach] Simple pod
07:39:46   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:150
07:39:46 STEP: creating the pod
07:39:46 INFO: Running '/jenkins-master-data/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl kubectl --server=https://146.148.34.84 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/kubernetes/docs/user-guide/pod.yaml --namespace=e2e-tests-kubectl-hhjrz'
07:39:46 INFO: pods/nginx
07:39:46 
07:39:46 INFO: Waiting up to 5m0s for the following 1 pods to be running and ready: [nginx]
07:39:46 INFO: Waiting up to 5m0s for pod nginx                                                   status to be running and ready
07:39:46 INFO: Waiting for pod nginx                                                   in namespace 'e2e-tests-kubectl-hhjrz' status to be 'running and ready'(found phase: "Pending", readiness: false) (2.455231ms elapsed)
07:39:51 INFO: Waiting for pod nginx                                                   in namespace 'e2e-tests-kubectl-hhjrz' status to be 'running and ready'(found phase: "Running", readiness: false) (5.005603522s elapsed)
07:39:56 INFO: Waiting for pod nginx                                                   in namespace 'e2e-tests-kubectl-hhjrz' status to be 'running and ready'(found phase: "Running", readiness: false) (10.008784337s elapsed)
07:40:01 INFO: Wanted all 1 pods to be running and ready. Result: true. Pods: [nginx]
07:40:01 [It] should support exec
07:40:01   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:162
07:40:01 STEP: executing a command in the container
07:40:01 INFO: Running '/jenkins-master-data/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl kubectl --server=https://146.148.34.84 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/.kube/config exec --namespace=e2e-tests-kubectl-hhjrz nginx echo running in container'
07:40:02 INFO: running in container
07:40:02 
07:40:02 [AfterEach] Simple pod
07:40:02   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:153
07:40:02 STEP: using stop to clean up resources
07:40:02 INFO: Running '/jenkins-master-data/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl kubectl --server=https://146.148.34.84 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/.kube/config stop -f /jenkins-master-data/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/kubernetes/docs/user-guide/pod.yaml --namespace=e2e-tests-kubectl-hhjrz'
07:40:02 INFO: pods/nginx
07:40:02 
07:40:02 INFO: Running '/jenkins-master-data/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl kubectl --server=https://146.148.34.84 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-1.0-1.1-gke-step1-deploy/workspace/.kube/config get pods,rc,se -l name=nginx --no-headers --namespace=e2e-tests-kubectl-hhjrz'
07:40:03 INFO: nginx     1/1       Running   0         17s
07:40:03 
07:40:03 [AfterEach] Kubectl client
07:40:03   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:77
07:40:03 STEP: Destroying namespace for this suite e2e-tests-kubectl-hhjrz
07:40:03 
07:40:03 • Failure in Spec Teardown (AfterEach) [27.160 seconds]
07:40:03 Kubectl client
07:40:03 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:241
07:40:03   Simple pod
07:40:03   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:203
07:40:03     should support exec [AfterEach]
07:40:03     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:162
07:40:03 
07:40:03     Resources left running after stop:
07:40:03     nginx     1/1       Running   0         17s
07:40:03 
07:40:03     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:759
07:40:03 ------------------------------
```

**Comment by ncdc** [comment]
@lavalamp that looks like it's the 1.0 e2e, which didn't have the additional exec tests. And the failure looks like #15123 / #15895.

**Comment by lavalamp** [comment]
@ncdc OK. So we should be covered going forward, but 1.0 -> 1.1 is not covered because the 1.0 test didn't exercise this case well enough. Is that right?

**Comment by ncdc** [comment]
@lavalamp correct

**Comment by mikedanese** [comment]
Can't cut v1.1 without this fixed so adding milestone and upping priority.

**Comment by lavalamp** [comment]
@ncdc, @ihmccreery ran the 1.1 e2e kubectl test suite against a 1.0 apiserver & kubelet cluster, and the exec test did not fail. :( (see: #16041)

**Comment by lavalamp** [comment]
```
14:43:29 ------------------------------
14:43:29 Kubectl client Simple pod 
14:43:29   should support exec
14:43:29   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:196
14:43:29 [BeforeEach] Kubectl client
14:43:29   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:85
14:43:29 >>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/.kube/config
14:43:34 Oct 21 14:43:34.045: INFO: Waiting up to 2m0s for service account default to be provisioned in ns e2e-tests-kubectl-w9zus
14:43:34 Oct 21 14:43:34.056: INFO: Service account default in ns e2e-tests-kubectl-w9zus had 0 secrets, ignoring for 5s: <nil>
14:43:39 Oct 21 14:43:39.067: INFO: Service account default in ns e2e-tests-kubectl-w9zus with secrets found. (5.021679874s)
14:43:39 [BeforeEach] Simple pod
14:43:39   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:161
14:43:39 STEP: creating the pod
14:43:39 Oct 21 14:43:39.067: INFO: Running '/jenkins-master-data/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.151.241 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/kubernetes/docs/user-guide/pod.yaml --namespace=e2e-tests-kubectl-w9zus'
14:43:39 Oct 21 14:43:39.308: INFO: pod "nginx" created
14:43:39 
14:43:39 Oct 21 14:43:39.308: INFO: Waiting up to 5m0s for the following 1 pods to be running and ready: [nginx]
14:43:39 Oct 21 14:43:39.308: INFO: Waiting up to 5m0s for pod nginx                                                   status to be running and ready
14:43:39 Oct 21 14:43:39.319: INFO: Waiting for pod nginx                                                   in namespace 'e2e-tests-kubectl-w9zus' status to be 'running and ready'(found phase: "Pending", readiness: false) (11.294044ms elapsed)
14:43:44 Oct 21 14:43:44.330: INFO: Waiting for pod nginx                                                   in namespace 'e2e-tests-kubectl-w9zus' status to be 'running and ready'(found phase: "Running", readiness: false) (5.022423635s elapsed)
14:43:49 Oct 21 14:43:49.342: INFO: Waiting for pod nginx                                                   in namespace 'e2e-tests-kubectl-w9zus' status to be 'running and ready'(found phase: "Running", readiness: false) (10.03407321s elapsed)
14:43:54 Oct 21 14:43:54.353: INFO: Wanted all 1 pods to be running and ready. Result: true. Pods: [nginx]
14:43:54 [It] should support exec
14:43:54   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:196
14:43:54 STEP: executing a command in the container
14:43:54 Oct 21 14:43:54.353: INFO: Running '/jenkins-master-data/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.151.241 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/.kube/config exec --namespace=e2e-tests-kubectl-w9zus nginx echo running in container'
14:43:55 Oct 21 14:43:55.051: INFO: running in container
14:43:55 
14:43:55 STEP: executing a command in the container with noninteractive stdin
14:43:55 Oct 21 14:43:55.051: INFO: Running '/jenkins-master-data/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.151.241 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/.kube/config exec --namespace=e2e-tests-kubectl-w9zus -i nginx cat'
14:43:55 Oct 21 14:43:55.513: INFO: abcd1234
14:43:55 STEP: executing a command in the container with pseudo-interactive stdin
14:43:55 Oct 21 14:43:55.513: INFO: Running '/jenkins-master-data/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.151.241 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/.kube/config exec --namespace=e2e-tests-kubectl-w9zus -i nginx bash'
14:43:55 Oct 21 14:43:55.972: INFO: hi
14:43:55 
14:43:55 [AfterEach] Simple pod
14:43:55   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:164
14:43:55 STEP: using delete to clean up resources
14:43:55 Oct 21 14:43:55.972: INFO: Running '/jenkins-master-data/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.151.241 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/.kube/config stop --grace-period=0 -f /jenkins-master-data/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/kubernetes/docs/user-guide/pod.yaml --namespace=e2e-tests-kubectl-w9zus'
14:43:56 Oct 21 14:43:56.184: INFO: pod "nginx" deleted
14:43:56 
14:43:56 Oct 21 14:43:56.184: INFO: Running '/jenkins-master-data/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.151.241 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/.kube/config get rc,svc -l name=nginx --no-headers --namespace=e2e-tests-kubectl-w9zus'
14:43:56 Oct 21 14:43:56.400: INFO: 
14:43:56 Oct 21 14:43:56.400: INFO: Running '/jenkins-master-data/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.197.151.241 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-client-skew-1.0-1.1-gke-step1-deploy/workspace/.kube/config get pods -l name=nginx --namespace=e2e-tests-kubectl-w9zus -o go-template={{ range .items }}{{ if not .metadata.deletionTimestamp }}{{ .metadata.name }}{{ "\n" }}{{ end }}{{ end }}'
14:43:56 Oct 21 14:43:56.619: INFO: 
14:43:56 [AfterEach] Kubectl client
14:43:56   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:92
14:43:56 STEP: Destroying namespace for this suite e2e-tests-kubectl-w9zus
14:44:01 
14:44:01 • [SLOW TEST:32.627 seconds]
14:44:01 Kubectl client
14:44:01 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:730
14:44:01   Simple pod
14:44:01   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:243
14:44:01     should support exec
14:44:01     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:196
14:44:01 ------------------------------
```

```
14:41:36 Oct 21 14:41:36.177: INFO: Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-beta.291+959f0d01c682d7", GitCommit:"959f0d01c682d74b7556e31506c2ffff8285abcd", GitTreeState:"clean"}
14:41:36 Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
```

**Comment by ncdc** [comment]
@lavalamp I'm beat for the night. I will take a look at this e2e scenario tomorrow morning.

**Comment by ncdc** [comment]
@lavalamp I *think* that the reason the pseudo-interactive test passes above is because of a timing issue. It passes for me locally (kubectl from master, cluster from 1.0.6). However, if I make it so there is a delay before the stdin data is actually supplied to the kubectlCommand, the expected output is missing. I don't know of any reasonable way to simulate this behavior other than to put in an artificial sleep, which I want to avoid. I've learned my lesson all too well w.r.t test cases and sleep times...

**Comment by lavalamp** [comment]
Not sure what to tell you... What if you make the test send a lot more data?

**Comment by ncdc** [comment]
I can try that

**Comment by ncdc** [comment]
It still passes, even with 16KB of data.

**Comment by ncdc** [comment]
But now the non interactive stdin test is failing for me locally, which is expected, since my branch restores the behavior pre-13322, which has this issue.

**Comment by lavalamp** [comment]
We can take up the test issue in #16119.

I'm reopening until #15961 is cherrypicked. (we want to CP it, right?)

**Comment by lavalamp** [comment]
Reducing to P1 as we're just waiting for the cherrypick to merge.

**Comment by lavalamp** [comment]
#16406 has merged.
