### ISSUE TITLE
Document the different flavor of updates and when to use them

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#15725]
replace, patch, apply, ...

There used to be an issue, filed as a documentation issue, called something like "explain the different kinds of updates and when to use them" but I can't find it.

@jackgr @bgrant0607

**Comment by bgrant0607** [comment]
I think it was #11157.

That was actually done, but needs to be updated for apply and other new commands.

**Comment by janetkuo** [comment]
I'll document `kubectl edit` too.

**Comment by bgrant0607** [comment]
This should be addressed by the doc overhaul:

https://docs.google.com/document/d/12Nfj2E8tZL-CMnnpkSH9m5k_oqd4qJh4qDwYDxPGJJI/edit?ts=5705b1fc#

**Comment by spzala** [comment]
@davidopp hi David, is this still an issue? wondering if you had a chance to look at the doc link @bgrant0607 provided above? If you think issue is addressed, can we please close it? Thanks!!
