### ISSUE TITLE
Example: Drupal

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1572]
I used Drupal as an example for my OSCON talk:

https://speakerdeck.com/bgrant0607/managing-containerized-applications

It would be nice to actually get a demo working. It could demonstrate a multi-tier application, multi-container pods, durable storage, cardinal services (#260), and memcache.

**Comment by scottrigby** [comment]
@bgrant0607 There's a [Helm Charts Drupal example](https://github.com/kubernetes/charts/tree/master/stable/drupal) now.

**Comment by bgrant0607** [comment]
@scottrigby Thanks!
