### ISSUE TITLE
Issues encountered when trying to use heapster/grafana/influxdb on gce

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#15727]
1. heapster requires both "cloud monitoring" and "cloud logging" api to be enabled for the project in the cloud developer console. Without it, the hepaster container may crash or not actually function correctly. 
E.g., `kubectl logs` heapster container shows
` failed to sync data to sinks - encountered the following errors: request to "https:/v1beta3/projects/<project-name>/logs/kubernetes.io%2Fevents/entries:write" failed with status "403 Forbidden" and response: "{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"Project has not enabled the API. Please use Google Developers Console to activate the API for your project.`
It doesn't say which api is required.

We need to document the requirements clearly and/or make the error message informative.

2. Accessing the service through apiserver proxy returns: 
`{"message":"Invalid API key"}`
However, I was able to access the dashboard by creating an ssh tunnel using gcloud directly.

3. The container tab on the grafana dashboard sometimes show no containers. I encountered this problem intermittently.

/cc @vishh

**Comment by vishh** [comment]
> The container tab on the grafana dashboard sometimes show no containers. I encountered this problem intermittently.

cc @thucatebay.

**Comment by pnovotnak** [comment]
Yeah, this is a PITA. We lost logs from a couple of incidents from this. Wouldn't expect an unmodified GKE cluster to be broken out of the gate :/

**Comment by pnovotnak** [comment]
*having this issue with fluentd, not heapster
