### ISSUE TITLE
kubectl autoscale

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15723]
As mentioned in the proposal.
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/horizontal-pod-autoscaler.md#support-in-kubectl

Implementation similar to kubectl expose (using generator, etc.). Should at least work for RCs, and Deployment, if easy.

cc @fgrzadkowski @jszczepkowski @mwielgus

**Comment by jszczepkowski** [comment]
That's great we are doing this for 1.1!

In addition to ``kubectl autoscale``, there is also a proposal to add new parameters to ``kubectl run``, eg: ``--min`` ``--max`` ``--cpu%``, so that we will start an image together with the autoscaler. Do we also plan to do it?
