### ISSUE TITLE
Kubernetes pods die with default restartPolicy=true and do not restart

### ISSUE THREAD

**Issue by rroopreddy** [kubernetes/kubernetes#15731]
Kubernetes version 1.0.6

This setup involves pods for Cassandra (2-nodes), Spark (master, 3-workers, driver), RabbitMQ(1-node). Some pods that are not under replication controller die after a day and never restarted automatically. I found out that  *influxDB' monitoring was using too much of CPU and the pods dying are from that node. 

Please notice the *restartPolicy: Always* is the default as I have not explicitly specified it. With this I was expecting manually started pods to restart on failure similar to the ones under replication controller

Once the pod died, there was no way to run "kubectl.sh describe pod-is* on it. Could not find any debugging information on the failure. This is very much duplicatable if I switch on the  cluster monitoring (with ENABLE_CLUSTER_MONITORING; true by default)

Related threads with more info/discussion
[Influxdb is using 1 core on 4 core cluster](https://github.com/kubernetes/kubernetes/issues/4455)
[Kubernetes pods (some) die after running for a day](http://stackoverflow.com/questions/33068639/kubernetes-pods-some-die-after-running-for-a-day)

**Comment by hurf** [comment]
Even the pod died, `kubectl describe` should be able to access the pod. Have you used `kubectl get` to see if the pod exsit? `kubectl get ev` can also help to find the reason why the pod dies.

**Comment by rroopreddy** [comment]
Ok, I have this situation now where the commands mentioned did gave any info. Are there any other internal commands I could run to get info for DEBUGGING

1. BEFORE: ./cluster/kubectl.sh get pods -o wide

        NAME                            READY     STATUS    RESTARTS   AGE       NODE
        cassandra                       1/1       Running   0          3d        ip-172-20-0-16.us-west-2.compute.internal
        cassandra-node2                 1/1       Running   0          1d        ip-172-20-0-15.us-west-2.compute.internal
        rabbitmq-controller-f7tg7       1/1       Running   0          3d        ip-172-20-0-17.us-west-2.compute.internal
        spark-driver                    1/1       Running   0          1d        ip-172-20-0-15.us-west-2.compute.internal
        spark-master                    1/1       Running   0          3d        ip-172-20-0-17.us-west-2.compute.internal
        spark-worker-controller-7983o   1/1       Running   0          3d        ip-172-20-0-16.us-west-2.compute.internal
        spark-worker-controller-hpy7f   1/1       Running   0          1d        ip-172-20-0-15.us-west-2.compute.internal
        spark-worker-controller-metzx   1/1       Running   0          3d        ip-172-20-0-17.us-west-2.compute.internal

2. AFTER When two pods died: ./cluster/kubectl.sh get pods -o wide

        cassandra                       1/1       Running   0          3d        ip-172-20-0-16.us-west-2.compute.internal
        rabbitmq-controller-f7tg7       1/1       Running   0          3d        ip-172-20-0-17.us-west-2.compute.internal
        spark-master                    1/1       Running   0          3d        ip-172-20-0-17.us-west-2.compute.internal
        spark-worker-controller-7904c   1/1       Running   0          1h        ip-172-20-0-15.us-west-2.compute.internal
        spark-worker-controller-7983o   1/1       Running   0          3d        ip-172-20-0-16.us-west-2.compute.internal
        spark-worker-controller-metzx   1/1       Running   0          3d        ip-172-20-0-17.us-west-2.compute.internal

3. If you notice 2-pods died - spark-driver, cassandra-node2
4. DEBUG yields empty: ./cluster/kubectl.sh get ev

                FIRSTSEEN   LASTSEEN   COUNT     NAME      KIND      SUBOBJECT   REASON    SOURCE    MESSAGE

5. DEBUG yields empty: ./cluster/kubectl.sh describe pods spark-driver

                 error: pods "spark-driver" not found

**Comment by rroopreddy** [comment]
Please let me know if I can gather any useful information now as it is in that state now. Initially I though pods are dying because the CPU from influxDB. However, in this cluster instance monitoring (influxDB) was disabled and there was only a light load on CPU

**Comment by rroopreddy** [comment]
I started to look into the logs on master, see bunch errors of following kind (/var/log/kube-apiserver.log):

errors.go:62] apiserver received an error that is not an api.Status: 100: Key not found (/registry/events/default/spark-driver.140d31c9b92794b4) [125564]

**Comment by fabioy** [comment]
This may be of help: http://stackoverflow.com/questions/31666135/is-norestart-policy-supported-for-kubernetes-pods

Specifically:

"If you run something as a pod rather than as a replication controller, you can set the restartPolicy field on it. The OnFailure policy is probably what you'd want, meaning that kubernetes will restart a pod that exited with a non-zero exit code, but won't restart a pod that exited zero."

Note that if you need a pod to be running at all times, then you need to configure a replication controller in Kubernetes.

Closing the issue. If you still have problems, please reopen it in StackOverflow, where there's greater visibility and the broader community can help answer questions.

Thank you.

**Comment by rroopreddy** [comment]
I made the restartPolicy changes as per suggestion and pods are still dying.  We are pretty much hosed with this issue in test deployment and can not proceed further without understanding the cause.

I have posed in StackOverflow; apossible explanation is that the node was unresponsive for >5 minutes and hence triggering Eviction. Based on item (3 and 4) below from logs, seems right.  

The question is what is causing this state of **NodeNotReady** after node ran fine for a while. How to find the cause and avoid this state constant pods termination 

Here is additional info:

1. The issue is not related to "restartPolicy: OnFailure". The same machine and pods under this are dying and not starting with this restart  policy.

2. This issue is not related to **influxDB** as originally thought. This happens after disabling the monitoring/influxDB. With these disabled, CPU utilization is fairly minimal

3. On master "kube-controller-manager.log" I see the following for the same time

        I1020 02:29:22.732420       7 nodecontroller.go:382] Adding pods to evict: 2015-10-20 02:29:22.732413049 +0000 UTC is later than 2015-10-20 02:24:17.86557047 +0000 UTC + 5m0s
        I1020 02:29:22.774622       7 podevictor.go:110] PodEvictor is evicting Pods on Node: ip-172-20-0-15.us-west-2.compute.internal
        I1020 02:29:22.774680       7 nodecontroller.go:429] Delete all pods from ip-172-20-0-15.us-west-2.compute.internal
        I1020 02:29:22.786431       7 nodecontroller.go:440] Delete pod cassandra-node2
        I1020 02:29:22.811790       7 nodecontroller.go:440] Delete pod spark-driver
        I1020 02:29:22.835105       7 nodecontroller.go:440] Delete pod spark-worker-controller-3wytq
        I1020 02:29:22.853689       7 nodecontroller.go:440] Delete pod fluentd-elasticsearch-ip-172-20-0-15.us-west-2.compute.internal
        I1020 02:29:22.860065       7 replication_controller.go:316] Too few "default"/"spark-worker-controller" replicas, need 3, creating 1

4. /cluster/kubectl.sh describe nodes ip-172-20-0-15.us-west-2.compute.internal

        Events:
          FirstSeen				LastSeen			Count	From							SubobjectPath	Reason		Message
          Wed, 14 Oct 2015 06:32:44 +0000	Tue, 20 Oct 2015 02:24:13 +0000	7	{kubelet ip-172-20-0-15.us-west-2.compute.internal}			NodeNotReady	Node ip-172-20-0-15.us-west-2.compute.internal status is now: NodeNotReady
          Wed, 14 Oct 2015 06:33:15 +0000	Tue, 20 Oct 2015 02:32:18 +0000	17	{kubelet ip-172-20-0-15.us-west-2.compute.internal}			NodeReady	Node ip-172-20-0-15.us-west-2.compute.internal status is now: NodeReady

4.  All application docker containers killed on this specific one minion; 

        all kubernetes "google_containers/pause" with "Exited(0)" and other application containers with "Exited(137)". This error code seems to mean — the container stopped with SIGKILL (137 = 128 + 9 - kill signal ). How to find why they are getting killed? sudo docker inspect 47b671fe593b gives - "State": { "Error": "", "ExitCode": 137, "OOMKilled": false, }
