### ISSUE TITLE
v1.1 known issues / FAQ accumulator

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#15747]
This issue is intended to accumulate known errata / issues / workarounds so we can produce a useful doc upon release. If you have a known issue that is worth putting in our 1.1 release notes, please add a comment here of the form "NEW: ..." and write a paragraph explaining the issue and the workaround or repercussions or whatever. 

cc/ @thockin @bgrant0607

**Comment by lavalamp** [comment]
I thought we were going to scrape the cherry pick issues for this? Or is this meant for things that are known broken?

**Comment by lavalamp** [comment]
Known broken in 1.1: #15726

NEW:

Stdin redirection (pod exec, attach etc) does not work as expected between kubectl 1.0.x clients and Kubernetes 1.1 apiservers, as well as between kubectl 1.1 and 1.0.x apiservers. Workaround: use a kubectl that corresponds to your apiserver's version.

**Comment by dchen1107** [comment]
@lavalamp This is for known breakage in 1.1 release, not for cherry-picks.

**Comment by vishh** [comment]
#10959 will still be unresolved in v1.1.

**Comment by vishh** [comment]
Grafana automated dashboards for containers are at times not working. 
A reload of the browser has resolved these issues in the past.
We suspect that the issues are related to access via proxy. 
We have documented how to access Grafana directly using an external Service.

**Comment by dchen1107** [comment]
#15960: Mirror pods in a delete create loop in version skewed cluster.

**Comment by dchen1107** [comment]
#15175: docker pull can stall and leading cluster bringup issue. Restarting docker daemon should fix the issue.

**Comment by brendandburns** [comment]
Closing this since 1.1 is released.  @dchen1107 re-open if you need this for some reason.

**Comment by bgrant0607** [comment]
This was never done

**Comment by bgrant0607** [comment]
Didn't see anything here worth documenting at this point. Might have been useful 3 months ago. Closing.
