### ISSUE TITLE
Make API schema docs more discoverable for kubectl users

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15741]
We have kubectl explain, but we should make the online docs more discoverable from kubectl docs, also.

**Comment by bgrant0607** [comment]
cc @mansoorj

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by bgrant0607** [comment]
kubectl explain is good enough for now
