### ISSUE TITLE
kube-ui dashboard got 503 (Service Unavailable)

### ISSUE THREAD

**Issue by ntquyen** [kubernetes/kubernetes#15751]
When I access the kube-ui dashboard via `/api/v1/proxy/namespaces/kube-system/services/kube-ui/#/dashboard/` the page is blank, console errors:

```
...
GET http://10.9.8.20:8080/api/v1/proxy/nodes/10.9.8.21:4194/api/v1.0/machine 503 (Service Unavailable)
GET http://10.9.8.20:8080/api/v1/proxy/nodes/10.9.8.22:4194/api/v1.0/machine 503 (Service Unavailable)
POST http://10.9.8.20:8080/api/v1/proxy/nodes/10.9.8.22:4194/api/v1.0/containers/ 503 (Service Unavailable)
POST http://10.9.8.20:8080/api/v1/proxy/nodes/10.9.8.21:4194/api/v1.0/containers/ 503 (Service Unavailable)
...
```
But other views (explore, pods...) are fine. Looks like the proxies are not working...

**Comment by so0k** [comment]
I had the same issue on the dashboard, in my case it was due to the k8s nodes not having a proper IP. Have you deployed your k8s cluster in Digital Ocean, if so, the network management tool which disovers the node IPs picks the wrong IP (an internal DO IP), I document and correct this issue in the https://github.com/docker-saigon/docker-saigon-k8s repo

**Comment by so0k** [comment]
this is the commit that fixed it, I filter out the internal Digital Ocean Subnet from the interface setup: https://github.com/docker-saigon/docker-saigon-k8s/commit/3dd0e944ab200988c962e5ebba40d2176aedcbca#diff-ec7ef0d861167c50203edf0d8052d3b7

**Comment by ntquyen** [comment]
I setup my cluster in our private cloud, in my case, the master picked up the correct nodes' IP to proxy to. (10.9.8.20 can ping to 10.9.8.x) But the problem is that the port 4194 is not opened in the nodes, no idea why...

**Comment by so0k** [comment]
4194 is the cAdvisor port on the nodes (opened by the kubelet), can you curl that port?

**Comment by jlowdermilk** [comment]
Closing/redirecting this with request to please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate all help/support questions onto stackoverflow to improve searchability and response time. We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Thanks

**Comment by ntquyen** [comment]
@so0k Sorry for being late reply. I hadn't got time to go back to kube-ui until recently. I realized that the cAdvisor port wasn't open yet  (`--cAdvisor-port=0` which should be `cAdvisor-port=4194`) and that caused the issue!
