### ISSUE TITLE
Proposal : add health check for etcd client

### ISSUE THREAD

**Issue by combk8s** [kubernetes/kubernetes#15756]
By now, kubernetes use go-etcd https://github.com/coreos/go-etcd#deprecated as etcd client. However, because go-etcd pins to one endpoint if possible, it will always make requests to one server. In addition it cannot detect whether the member in use is healthy when doing read requests. If the member is isolated from the cluster, go-etcd may retrieve outdated data. BTW, go-etcd has deprecated and does't accept new features. 
Even if we replace go-etcd to offical etcd client https://github.com/coreos/etcd/tree/master/client, which may has a nicer API and better support, this problem still exist. As far as I know,  etcd/client will solve this problem using the experimental `/health` endpoint https://github.com/coreos/etcd/issues/3265. Unfortunately, this experimental `/health` endpoint is just available after version V2.1.XX. If we want support V2.0XX version etcd, we must find some other health check method.

So, I propose to solve this problem in kubernetes. My idea is to encapsulate the go-etcd client, and provide health check functions.

We can put our encapsulated client in `third_party/forked/coreos/go-etcd/etcd/hclient.go`, and replace all the `import "github.com/cores/go-etcd/etcd"` statement to `github.com/k8s.io/kubernetes/third_party/forked/coreos/go-etcd/etcd/hclient.go`. So all we need is just replacing the import statement, without modify any other code. 

The content of `third_party/forked/coreos/go-etcd/etcd/hclient.go` is like this

```
import "github.com/cores/go-etcd/etcd"

HClient {
    client *Client  // go-etcd client
    XXX             // some uxiliary field
}


func NewClient(machines []string) *Client {

    hclient := &HClient {
        client : {
            cluster: NewCluster(machines)
            config : config
        }
        XXX : xxx
    }
    hclient.intiHTTPClient()
    hclient.saveConfig()

    go healthCheck(hclient)

    return hclient.client
}

func healthCheck(hclient *Hclient) {

}
```

I wiil explain how to implement of `healthCheck()` function later.

**Comment by combk8s** [comment]
```
fucn healthyCheck(hclient *Hclient) {
	version := hclient.client.Get("/version") // get the version of etcd
	if version > 2.1 {
		healthy :=  hclient.client.Get("/version") // using the experimental `\health` end point to get healthy information
		if !healthy {
			hclient.client.cluster.failed()
		}
	} else {
		// check period
		time.Sleep(5 * time.Second)

		// do we have a leader?
		cl := client.GetCluster()
		ep, ls0, err := getLeaderStats(client.transport, cl)
		if err != nil {
			logger.Warning(err)	// no valid leader, cluster is unhealthy
			continue
		}

		time.Sleep(time.Second)

		// are all the members makeing progress?
		_, ls1, err := getLeaderStats(client.transport, []string{ep})
		if err != nil {
			logger.Debug(err)
			continue
		}

		var healthyMemberID []string

		healthyMemberID = append(healthyMemberID, ls1.Leader)
		for id, fs0 := range ls0.Followers {
			fs1, ok := ls1.Followers[id]
			if !ok {
				logger.Debug("Cluster configuration changed during health checking, retrying.")
				continue
			}
			if fs1.Counts.Success <= fs0.Counts.Success {	// member doesn't make progress, member is invalid
				fmt.Sprintf("member %s is unhealthy\n", id))
			} else {
				healthyMemberID = append(healthyMemberID, id)
			}
		}

		var urls []string
		for _, id := range healthyMemberID {
			for _, member := range hclient.members {
				if member.ID == id {
					urls = append(urls, member.ClientURLs...)
				}
			}
		}

		hclient.updateHealthyMachines(urls)

		needSwitch := true
		for _, url := range urls {
			if client.cluster.pick() == url {
				needSwitch = false
				break
			}
		}

		if needSwitch {
			logger.Debugf("client pin to a unhealthy machine, switching\n")
			hclient.cluster.failure()
		}
	}
}
```

**Comment by combk8s** [comment]
I  commit this implementation to go-etcd https://github.com/coreos/go-etcd/pull/245, but it doesn't be accepted since go-etcd has been  deprecated and doesn't accept new features. 

Sure, etcd/client will solve this problem using the experimental /health endpoint coreos/etcd#3265, but this experimental /health endpoint is just available after version V2.1.XX. 

So I think solve this this problem in k8s is a better choice, if we want support V2.0XX version etcd.

**Comment by jlowdermilk** [comment]
cc @lavalamp @nikhiljindal

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/issues/11962 tracks replacing go-etcd with the new etcd client.

**Comment by lavalamp** [comment]
@timstclair is working on getting the new client in. I would personally rather bump our etcd version than reimplement health checking.

**Comment by lavalamp** [comment]
Oops, wrong Timothy st Clair, I meant @timothysc
