### ISSUE TITLE
Cleanup and type safety - UID and GID types

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15759]
We have a couple fields in the API for Unix UID and GID.  We should define `type UnixGroupID int64` and `type UnixUserID int64` and use them everywhere.

**Comment by pmorie** [comment]
Is `int64` really correct?  As you pointed out, GID is an unsigned int32, isn't it?

**Comment by pmorie** [comment]
@pweil- @swagiaal @kubernetes/rh-cluster-infra

**Comment by thockin** [comment]
If I recall, POSIX does not actually specify signedness and some Unixes
differ on it.  int64 seems like a safe superset, unless we know of any OS
that uses 64 bit UID/GID ?

**Comment by pmorie** [comment]
I personally don't know of one.  How about you @eparis ?

**Comment by thockin** [comment]
int64 also has the nice property of allowing negative values without
wraparound.  (uid_t)-1 is a thing, sadly, and (uid_t)-2 is apparently a
thing, too.

**Comment by pmorie** [comment]
Okay, you've got me on the fence.

**Comment by pmorie** [comment]
I will change #15352 and @swagiaal will change #14991 when he's back from PTO.

**Comment by pmorie** [comment]
@pweil- We might want to talk through the effects of changing this on the origin policy stuff before we start doing it.

**Comment by pmorie** [comment]
@thockin @swagiaal @pweil- 

Okay, after talking to @pweil- I suggest that we do the following:

1.  Change the types of `pod.Spec.SecurityContext.SupplementalGroups` and `pod.Spec.SecurityContext.FSGroup` to `[]int64` and `*int64` respectively in #15323 and #15352 
2.  Have another commit that makes the following type changes:
  1.  Introduce `UnixGroupID` and `UnixUserID` as @thockin has suggested in this issue
  2.  Changes the types in `PodSecurityContext` and `SecurityContext` in applicable fields

This will be easier for us to consume in our rebase of OpenShift onto Kubernetes than if we modify #15323 and #15352 before going into master.

Any objections?

**Comment by thockin** [comment]
I don'[t object as long as the final goal is correct
