### ISSUE TITLE
Proposal: Add content-type on http-headers

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#15758]
Currently the command `kubectl -s http://192.168.0.15:8080 create -f sample.json` produces a packet similar to this one:
```
POST /api/v1/namespaces/default/pods HTTP/1.1
Host: 192.168.50.5:8080
User-Agent: kubectl/v1.0.6 (linux/amd64) kubernetes/388061f
Content-Length: 421
Accept-Encoding: gzip

{"kind":"Pod","apiVersion":"v1","metadata":{"name":"redis-controller","namespace":"default","creationTimestamp":null,"labels":{"app":"redis-controller"}},"spec":{"containers":[{"name":"redis","image":"redis","ports":[{"containerPort":6379,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","dnsPolicy":"ClusterFirst"},"status":{}}
```

Can someone add, if possible, the `Content-type: json` to the HTTP header of the `kubectl` request?

**Comment by jlowdermilk** [comment]
I'm guessing we never bothered adding the content-type to the HTTP header since kubectl only sends requests to the kubernetes apiserver, and the apiserver only accepts json content. Might be marginally useful for logging. What's the reason behind the request?

**Comment by aanm** [comment]
@jlowdermilk Otherwise this doesn't work properly. https://github.com/ClusterHQ/powerstrip/blob/master/powerstrip/powerstrip.py#L193
Still, doesn't hurt providing the type of content there's in the HTTP request.
