### ISSUE TITLE
ReplicationController pod template ignores generateName (ignores all ObjectMeta in fact)

### ISSUE THREAD

**Issue by mbwalas** [kubernetes/kubernetes#15776]
Default is that for RC named "rc" we get pods named rc-1a2e.. according to generateName policy. We would like to customize that to be able to have pods named ab-1a2e... for RC named "rc".
What we tried, is to put desired prefix (ab-) in generateName field of ObjectMeta of PodTemplateSpec, however this didn't work.

We found that this is actually implemented so that the ObjectMeta from spec is ignored:
https://github.com/kubernetes/kubernetes/blob/95b265390e530eb137beac4288ba28d63c1142da/pkg/controller/controller_utils.go#L292

I wonder if this is a desired state - is that something expected or just an implementation issue?

I think that the use case is valid: default to <rc-name>-1a2e... is of course very sane, but we should be able to customize that if needed. The question is what is the interpretation of objectMeta of PodTemplateSpec: is it expression of intent to have a custom objectMeta for created pods or just a "local" objectMeta for the PodTemplateSpec.

+cc @bgrant0607 @brendandburns

**Comment by bgrant0607** [comment]
One advantage of the current approach is that it ensures uniqueness, at least with high probability. Pods generated by one RC can't generate the same names as pods of another RC. That said, it is possible for a RC to adopt pods with arbitrary names.

I'm not opposed to making it possible to specify another prefix, but we'd need to ensure the controller (and the generateName mechanisms) responded sufficiently gracefully to collisions.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc 
@kubernetes/sig-apps-misc
