### ISSUE TITLE
"kubectl get resource-shortname/foo" backwards compatibility broken

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#15781]
I'm no longer able to request `kubectl get sa/default`.  I get back an error that says: `error: no resource "default" is defined for group ""`.

This seems to be due to a bad parsing that doesn't respect the short names described in the RESTMapper.  I suspect https://github.com/kubernetes/kubernetes/pull/14461, but I haven't definitively tracked it down yet.

@smarterclayton @liggitt @JanetKuo @kubernetes/kubectl

**Comment by liggitt** [comment]
Does rc/replicationcontrollername work? I think we defined the sa short name in origin

**Comment by liggitt** [comment]
Along with a fix, we need to add tests for `shortname/name` to prevent rebreakage

**Comment by deads2k** [comment]
> Does rc/replicationcontrollername work? I think we defined the sa short name in origin

Yes.  Looks like its the new interface method `ResourceIsValid`.  I'll add the tests and refactor to avoid breaking again.

**Comment by deads2k** [comment]
semi-related.  `sa` is a pretty useful one....

**Comment by liggitt** [comment]
I would just add `shortname/name` tests until the discussion around `group.resource/name` (and I suppose `group.shortname/name` settles

**Comment by smarterclayton** [comment]
I am going to try to finish that this weekend
