### ISSUE TITLE
kube-push.sh is broken due to unbound variable KUBE_TAR_URL

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#15794]
I tried to upgrade my cluster through hack/dev-build-and-push.sh, and failed due to endless error messages:

hack/../cluster/../cluster/../cluster/gce/../../cluster/common.sh: line 283: KUBE_TAR_URL: unbound variable
Failure trying to curl release .sha1
hack/../cluster/../cluster/../cluster/gce/../../cluster/common.sh: line 283: KUBE_TAR_URL: unbound variable
Failure trying to curl release .sha1
hack/../cluster/../cluster/../cluster/gce/../../cluster/common.sh: line 283: KUBE_TAR_URL: unbound variable
Failure trying to curl release .sha1

...

**Comment by dchen1107** [comment]
cc/ @ihmccreery @mikedanese I suspect #15519 the culprit here.

**Comment by ihmccreery** [comment]
Closing this as a duplicate of #15738.

**Comment by ihmccreery** [comment]
#15793 is out to fix.
