### ISSUE TITLE
Enable REGISTER_MASTER_KUBELET by default

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#15803]
To enable this feature by default for OSS k8s, we need to fix a bunch of e2e tests. File this issue for place holder.

**Comment by resouer** [comment]
@dalanlan Our original deploy scripts can support both, and you can help with e2e tests here (as you once pointed out that)

**Comment by davidopp** [comment]
@gmarek

**Comment by gmarek** [comment]
I fixed some failures, but now I'm seeing timeouts in #18338, so something hangs somewhere. I was unable to reproduce it locally and I don't have cycles to work on it anymore (we need to prioritize debugging density test failures on bigger clusters). I think it should be either a blocker for v1.2, or we should disable master node registration in 'normal' setup - it's really crazy that we have meaningfully different configuration for test and prod. @aronchick @brendandburns @bgrant0607 

@dchen1107 @davidopp - I'm not certain which team should own this.

**Comment by davidopp** [comment]
@gmarek can you update the status of this? in cluster/gce/config-default.sh it appears to default to true, but false everywhere else (including test).

Should we go ahead and change cluster/gce/config-default.sh to default it to false, given that we've run out of time for 1.2?

**Comment by gmarek** [comment]
IMO we should default to false on config-default. I wasn't able to fix all the tests.

**Comment by dchen1107** [comment]
I did re-ran pr builder e2e tests through @gmarek's pr, and currently two failures (only, comparing to more than 20 before):

Test Result (2 failures / +2)
Kubernetes e2e suite.Services should be able to up and down services
Kubernetes e2e suite.MetricsGrabber should grab all metrics from a Scheduler.

I haven't looked into why. We should make decision asap. Disabling this flag means we lost some debuggability / visibility to master nodes. But the user can enable this through config anyway. 

cc/ @roberthbailey since GKE wants to use this, but I am not sure the current status on this one.

**Comment by davidopp** [comment]
Yeah, I'm fine with disabling it. If Marek had time to look into the test failures early next week then I would say we should delay making a decision, but I know he's busy with the performance stuff.

**Comment by gmarek** [comment]
IIRC GKE didn't want to use this at all... cc @roberthbailey 

I'll look into the failures.

**Comment by roberthbailey** [comment]
GKE isn't going to enable this, but we want the e2e config and the default config for OSS to match.

**Comment by dchen1107** [comment]
Ok, I will punt this one to next release, and make sure e2e config and default config are the same.

**Comment by mikedanese** [comment]
We went to v1.1 with register_master=true with failing e2e tests. looks like there is very little work left. If we can get #18338, passing after #22067, I'd elect to revert #21350 for v1.2

**Comment by mikedanese** [comment]
last step is to enable in gce/config-default.sh #22545

**Comment by davidopp** [comment]
> last step is to enable in gce/config-default.sh #22709

Is that actually the issue you meant to refer to?

**Comment by davidopp** [comment]
Maybe you meant #18338

**Comment by mikedanese** [comment]
#22709 is the pr that does the last step
