### ISSUE TITLE
Don't run DaemonRestart tests in GKE in the release-1.1 branch

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#15804]
There are two tests that are running on GKE in `release-1.1` that shouldn't be:

```
Kubernetes e2e suite.DaemonRestart Kubelet should not restart containers across restart
Kubernetes e2e suite.DaemonRestart Scheduler should continue assigning pods to nodes across restart
```

We should backport the skip of those tests into the `release-1.1` branch.

**Comment by ixdy** [comment]
Just created #15884 which is probably what we should cherry-pick in.
