### ISSUE TITLE
Documentation for kubectl bash completion does not work for those that download the tarball

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#15801]
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/gce.md#enabling-bash-completion-of-the-kubernetes-command-line-tools

Tells people that bash completion is available at `./contrib/completions/bash/kubectl`. If you downloaded the tarball (https://github.com/kubernetes/kubernetes/releases), that directory is not present.

**Comment by jlowdermilk** [comment]
This is resolved for future releases by #13836. Open question whether we want to backport it to 1.0 branch.

**Comment by ihmccreery** [comment]
I'm closing this, since `v1.0.7` was likely the last release for `1.0`, and this didn't make it in.  #13836 is in `1.1`.
