### ISSUE TITLE
Should we build codecgen from godeps?

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#15816]
On a clean build in master I get the following:

```
$ hack/update-all.sh
Running in the silent mode, run with -v if you want to see script logs.
Updating codecgen
codecgen error: error running 'go run codecgen-main-1234.generated.go': exit status 2, console: # k8s.io/kubernetes/pkg/util
../../../../go/src/k8s.io/kubernetes/pkg/util/flags.go:49: pflag.CommandLine.AddGoFlagSet undefined (type *pflag.FlagSet has no field or method AddGoFlagSet)

FAILED
```

**Comment by pmorie** [comment]
It's not broken, actually, but I had to update my system pflag to make it work.  Should we build our own codecgen binary from godeps and use that?

**Comment by mikedanese** [comment]
I'm getting a different error:
```
➜  kubernetes git:(master) ✗ ./hack/update-codecgen.sh                          
./hack/update-codecgen.sh: line 46: codecgen: command not found
```
and
```
➜  kubernetes git:(master) ✗ go get -u github.com/ugorji/go/codec/codecgen
# github.com/ugorji/go/codec/codecgen
../../github.com/ugorji/go/codec/codecgen/gen.go:259: undefined: genCodecPath
```

**Comment by pmorie** [comment]
@mikedanese Seems like another data point in favor of building from godeps.

**Comment by wojtek-t** [comment]
Yes - I agree that makes perfect sense.

**Comment by wojtek-t** [comment]
#15836 sent out for review

**Comment by aveshagarwal** [comment]
I am also running into similar error: 
./hack/update-codecgen.sh 
./hack/update-codecgen.sh: line 46: codecgen: command not found

**Comment by wojtek-t** [comment]
#15836 is already LGTMed - it should be merged soon.

**Comment by wojtek-t** [comment]
Should be fixed now.
I will send another cleanup PR later today and close this bug.
