### ISSUE TITLE
Docker Multinode master not starting

### ISSUE THREAD

**Issue by nVitius** [kubernetes/kubernetes#15818]
I'm using v1.1.0 (1.0.6 didn't have the master.sh script)  
I get this output from the script:  
```
k8s version is set to: 1.1.0
Detecting your OS distro ...
Starting bootstrap docker ...
Starting k8s ...
14ec19aab9e5d01f1e04826bb6bf3221f10bbd1ca1ef49b9d9a251e802ca319c
{ "Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}
Error response from daemon: lstat /var/lib/docker-bootstrap/aufs/mnt/c2b1f8720feb6ebcec3fedc21d0fe0c2151cf6ce837f6f76a7f8f845b06d976b/tmp/flannel/subnet.env: no such file or directory
```

Any help troubleshooting this would be appreciated.

**Comment by nVitius** [comment]
I went with the steps in the MASTER.md and that worked fine. Closing this issue, unless anyone has any questions about it.

**Comment by lukemarsden** [comment]
I'm also seeing this with https://raw.githubusercontent.com/kubernetes/kubernetes/master/docs/getting-started-guides/docker-multinode/master.sh on Ubuntu 14.04.

**Comment by RoelVanNyen** [comment]
When I had this, it was due to using wlan0 vs eth0.

**Comment by cpwais** [comment]
I also had a similar issue and wasn't able to get this working.  Seems that master.sh has the container use eth0 ...

FMI https://groups.google.com/forum/#!topic/google-containers/hdonxxWyTBM

@brendandburns could we please consider re-opening this issue?

**Comment by justvisiting** [comment]
Same Issue. Here is master.sh output

K8S_VERSION is set to: 1.1.3
ETCD_VERSION is set to: 2.2.1
FLANNEL_VERSION is set to: 0.5.5
FLANNEL_IFACE is set to: eth0
MASTER_IP is set to: 127.0.0.1
Detecting your OS distro ...
Starting bootstrap docker ...
Starting k8s ...
8873fcdadab0103d4eefbebc75303b0f8c33e3c9938b7a659a774c6d2718c50f
{ "Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}
Error response from daemon: lstat /var/lib/docker-bootstrap/aufs/mnt/bf6c9f111e87d263c55dbe63435fac054acf70509f4d31073f3071c3a89f3c09/tmp/flannel/subnet.env: no such file or directory

**Comment by lakhindr** [comment]
1. I have seen interfaces change name, e.g. eth0 will become em1, after a reboot of Ubuntu. In that case, perhaps it might be useful to set FLANNEL_IFACE ? I saw this problem for on the node running 'worker.sh'. Default values are 'eth0'.

2. But there could be other reasons too..

**Comment by jsilberm** [comment]
Problem has not gone away ...
K8S_VERSION is set to: 1.2.0-alpha.7
ETCD_VERSION is set to: 2.2.1
FLANNEL_VERSION is set to: 0.5.5
FLANNEL_IFACE is set to: eth0
FLANNEL_IPMASQ is set to: true
MASTER_IP is set to: 172.25.3.67
ARCH is set to: amd64
Detecting your OS distro ...
Starting bootstrap docker ...
Starting k8s ...
a2ef87b80306462f3f402ac3e14cfa5ca8379ea6583cfb270784c7ef364a937a
{ "Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}
Dumping flannel ...
Error: No such image or container: 92645bbb878aa1347b3c2b403789da5af0a2fd63e852253cd3cda5565e03ef64

**Comment by jsilberm** [comment]
Problem has not gone away:
K8S_VERSION is set to: 1.2.0-alpha.7
ETCD_VERSION is set to: 2.2.1
FLANNEL_VERSION is set to: 0.5.5
FLANNEL_IFACE is set to: eth0
FLANNEL_IPMASQ is set to: true
MASTER_IP is set to: 172.25.3.67
ARCH is set to: amd64
Detecting your OS distro ...
Starting bootstrap docker ...
Starting k8s ...
c24e1f96db934b1a73a1ec2480bd6289b997eb0fb56160930310378ca55725ba
{ "Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}
Error response from daemon: lstat /var/lib/docker-bootstrap/devicemapper/mnt/30b00e6c73f0f8348afe4a48003af151d564bf6ce0e7d850c582a2022628b71f/rootfs/tmp/flannel/subnet.env: no such file or directory

**Comment by jsilberm** [comment]
FWIW, RH/CentOS 7 no longer use "eth0".
When I made sure that:
FLANNEL_IFACE is set to: enp1s0f0
good things happened ...

**Comment by themsay** [comment]
I'm new to kubernetes.

Following http://kubernetes.io/docs/getting-started-guides/docker-multinode/ to create multi node cluster both on debian/jessie64 3.16.0-4-amd64.

1. I ran ./master.sh on master node and it worked! 
2. But I trying ./worker.sh on worker node output this error.

K8S_VERSION is set to: 1.2.0-alpha.7
FLANNEL_VERSION is set to: 0.5.5
FLANNEL_IFACE is set to: eth0
FLANNEL_IPMASQ is set to: true
MASTER_IP is set to: 10.100.199.200
ARCH is set to: amd64
Detecting your OS distro ...
Starting bootstrap docker ...
Starting k8s ...
Error response from daemon: lstat /var/lib/docker-bootstrap/aufs/mnt/804d15937c2425ab5974a9880b84984e1a41b99609e44cb54166f6fb24aecf40/tmp/flannel/subnet.env: no such file or directory

I any Idea how to solve this problem?

**Comment by jsilberm** [comment]
Sounds like you're running CENTOS/RH 7?

If so, set FLANNEL_IFACE=enp0s3 in your environment.
'eth0' has been superceded.

Good luck,
  -Jeff

**Comment by yidinghan** [comment]
In my case, remove the `Backend` config can solve

More detail about flannel `Backend` can find from [document](https://github.com/coreos/flannel#backends)

Related code see [here](https://github.com/kubernetes/kubernetes/blob/master/docs%2Fgetting-started-guides%2Fdocker-multinode%2Fmaster.sh#L148)

**Comment by ianwalter** [comment]
I'm using Debian 8 and I get the same error even though I have `eth0`.
