### ISSUE TITLE
Remove use of legacy pods proxy path in client code

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#15829]
The construct:

```
body, err = f.Client.Get().
  Namespace(api.NamespaceSystem).
  Prefix("proxy").
  Resource("pods").
  Name("elasticsearch-logging").
  Suffix("_search").
  ...                  
```

should be replaced everywhere with

```
body, err = f.Client.Get().
  Namespace(api.NamespaceSystem).
  Resource("pods").
  SubResource("proxy").
  Name("elasticsearch-logging").
  Suffix("_search").
  ...                  
```

`pods/proxy` existed from 1.0 onwards.

**Comment by smarterclayton** [comment]
We should also mark proxy/pods deprecated in 1.2

**Comment by lavalamp** [comment]
Yeah, this seems like a good cleanup.

**Comment by feihujiang** [comment]
Is there anybody working on this? If not, I'd like to fix this next week.

**Comment by ihmccreery** [comment]
In order to run tests against old clusters, (i.e. for testing upgrades of old clusters, https://github.com/kubernetes/kubernetes/issues/18581#issuecomment-164535146,) we still need this construct around.  @smarterclayton, are you opposed to including version-guarded logic wherein we use `pods/proxy` for anything above 1.0, and `Prefix("proxy")` for 1.0 and below?

**Comment by ihmccreery** [comment]
This is also blocking #18660.

**Comment by smarterclayton** [comment]
No opposition, same pattern we do in other places.

**Comment by brendandburns** [comment]
@smarterclayton we're not going to mark it deprecated.  Its a breaking change for the v1 api.

We can only do this with a switch to a v2 api.

--brendan

**Comment by smarterclayton** [comment]
No opposition, that's what we said for watch and other proxies.

**Comment by ihmccreery** [comment]
After looking into #18726, and considering we won't deprecate `proxy/pods`, I think I'd prefer just rolling back #17002.  It's quite a bit of code cruft to support the version-guarded new behavior for not much payoff, as far as I can tell.  @smarterclayton, opposition?

**Comment by smarterclayton** [comment]
V2 will remove the proxy/ and watch/ paths and new resources won't use
them.  So rolling it back doesn't help much.

**Comment by smarterclayton** [comment]
They are certainly deprecated for our next major versions.  Clients
should use he new paths.

**Comment by smarterclayton** [comment]
Why would we not mark it deprecated?

**Comment by brendandburns** [comment]
because its not deprecated?  it's pointless to mark it deprecated until we mark the whole v1 API deprecated (which is a long way away).  Up until that point its needless churn/angst for users of the v1 API

**Comment by smarterclayton** [comment]
We want to discourage it's use - because pods/proxy is right and proxy/pods
is wrong.

On Dec 15, 2015, at 10:42 PM, Brendan Burns <notifications@github.com>
wrote:

because its not deprecated? it's pointless to mark it deprecated until we
mark the whole v1 API deprecated (which is a long way away). Up until that
point its needless churn/angst for users of the v1 API

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15829#issuecomment-164980447>
.
