### ISSUE TITLE
Consider writing last O(200 bytes) of container log output to pod status for terminated pods

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#15826]
A significant debugging obstacle to pod failures are easy access to the last snippet of logs.  We could potentially add the last few hundred bytes of stdout/err or the termination log to the status of a terminated container in order to enable better debugging ux.  As that could grow pod json by a significant percentage, we could restrict it to failed pods, or have it be a separate snippet recorded at a different etcd key.  However, it's likely that in most "new user" scenarios failures are frequent and represent a barrier to entry - enough that displaying some segment of logs during a pod describe should be considered

Another option is to add this logging to the event - pod exit is highly correlated with failure, and a pod termination event with log snippet is potentially more useful than a termination.

We believe this would reduce debugging load substantially, and enable better ux around pod status.

**Comment by bgrant0607** [comment]
We already have termination message. I originally imagined that a postStop hook could copy the tail of the log into the termination message file. But we still don't have postStop hooks, sadly.
cc @kubernetes/goog-node

**Comment by aknuds1** [comment]
I have been struggling with not being able to see the reason for pods failing to launch. It would be a big help if the actual reason were logged.

**Comment by vishh** [comment]
@bgrant0607 We can still fetch the last few lines from container logs and expose it as termination message, if the container hasn't populated the termination message files.

**Comment by dchen1107** [comment]
shouldn't kubectl logs --previous already give you the information? Of course, you have to run another command to retrieve the information.

**Comment by smarterclayton** [comment]
You don't even need --previous anymore.

In general I think the use case here is to make client support for this
trivial - if we can keep the total size down per container (maybe only log
failures, maybe only last termination state), this becomes something that
immediately enriches all clients for a large percentage of failures (I
think most crash looping containers I've seen write the relevant error in
<< 1k bytes).

**Comment by smarterclayton** [comment]
Fixed with https://github.com/kubernetes/kubernetes/pull/39341

**Comment by bschwartz757** [comment]
@smarterclayton was this ever implemented? I'm trying to recover logs for some killed pods.

**Comment by smarterclayton** [comment]
Yes, `terminationMessagePolicy` if set to `FallbackToLogsOnError` will capture the last chunk of log output when a container fails.

**Comment by bschwartz757** [comment]
@smarterclayton ok thanks - good to know. But there is no log storage/archive of previous machine's data (like the data a logging application might send to STDOUT), correct? Reason I ask is that we had a service outage that caused our FluentD process to stop working, and in pushing a fix, we caused the previously-running application pods to be killed and respawned. We later realized that we may have been able to recover some data from the container logs, but these are replaced each time a new instance is spun up if I understand correctly. 

Would be curious if there is any way to recover these logs but I think we're out of luck.

**Comment by smarterclayton** [comment]
The logs are on disk, but are rotated.  The previous container logs should
be there but the pod and container garbage collector is likely to have
removed anything older than that (and even the previous run will eventually
get removed)

**Comment by bschwartz757** [comment]
@smarterclayton ok, thanks - I feared as much, but just wanted to double-check. There aren't any directories I'd want to check other than `/var/lib/docker/containers`, are there? All of the other log locations seemed to be symlinked back to the ones there.
