### ISSUE TITLE
GKE Persistent Disk unusable after restart of container (on same host)

### ISSUE THREAD

**Issue by alexcouper** [kubernetes/kubernetes#15820]
I have an issue which has the same resulting symptoms as https://github.com/kubernetes/kubernetes/issues/14642 (that a container can't use the disk) - but that is not caused by the Persistent Disk being on the wrong host.
- Is this the same underlying issue? 
- Am I shutting down containers in a non-friendly way? 
- Is the only known workaround that of recreating the RC?
## Reproducing the error
- On GKE, create an RC which is responsible for a single-instance pod that uses a Persistent Disk.
- Confirm that the PD is working as expected
- Check which host/node the container is running on.
- Stop the container.
- Once the RC has spun up a new container, confirm the container is running on the same host as previously.
- Attempt to use the PD
- See failure.
#### Clearing up after error.

The only way I could clean up was by stopping and recreating the RC.
### Starting point

```
$ kubectl get pods -l db=api-db
NAME              READY     STATUS    RESTARTS   AGE
api-db-rc-y7j11   1/1       Running   0          1m

$ kubectl get pod api-db-rc-y7j11  -o template -t '{{ .spec.nodeName }}'
gke-cluster1-9760fccf-node-s8pn

$ kubectl exec api-db-rc-y7j11 ls /var/lib/postgresql/data
data
lost+found
```
### Perform the breaking step

```
$ kubectl stop pod api-db-rc-y7j11
pods/api-db-rc-y7j11
```
### Confirm we're running on the same host

```
$ kubectl get pods -l app=api-db
NAME              READY     STATUS    RESTARTS   AGE
api-db-rc-bl3ng   0/1       Running   0          8s

$ kubectl get pod api-db-rc-bl3ng  -o template -t '{{ .spec.nodeName }}'
gke-cluster1-9760fccf-node-s8pn
```
### See the error

```
$ kubectl exec api-db-rc-bl3ng ls /var/lib/postgresql/data
ls: reading directory /var/lib/postgresql/data: Input/output error
```
### Recovering from failure

```
$ kubectl stop rc api-db-rc
replicationcontrollers/api-db-rc

$ kubectl create -f kubernetes/pg-rc.json
replicationcontrollers/api-db-rc

$ kubectl get pods -l app=api-db
NAME              READY     STATUS    RESTARTS   AGE
api-db-rc-ao3z9   0/1       Pending   0          14s

$ kubectl get pod api-db-rc-ao3z9  -o template -t '{{ .spec.nodeName }}'
gke-cluster1-9760fccf-node-s8pn

$ kubectl exec api-db-rc-ao3z9 ls /var/lib/postgresql/data
data
lost+found
```

**Comment by mikedanese** [comment]
@saad-ali @thockin

**Comment by kargakis** [comment]
@kubernetes/sig-storage-misc

**Comment by jsafrane** [comment]
This is quite old issue and we've rewritten all attaching and mounting logic in the meantime. Can you still reproduce the bug with 1.5 or 1.6 beta?

**Comment by alexcouper** [comment]
@jsafrane just retried this now and couldn't reproduce. (server is 1.6.4 now) Safe to close
