### ISSUE TITLE
Feel a little confused to use --all-namespaces flag

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#15834]
The  desciption of --all-namespaces is listing the requested object(s) across all namespaces. Namespace in current context is ignored even if specified with --namespace."

But when I used the following command: 
```#./cluster/kubectl.sh get pods counter  --all-namespaces```
error: namespace may not be empty when retrieving a resource by name
```#./cluster/kubectl.sh get -f ./examples/blog-logging/counter-pod.yaml --all-namespaces```
no namespace set on resource pods "counter"

The error messages are unclear, and the second message isn't labeled as an error even.

**Comment by feihujiang** [comment]
And  why ```./cluster/kubectl.sh describe``` couldn't use --all-namespaces flag.

**Comment by thockin** [comment]
You're asking for a specific pod name (counter) in all namespaces, which is a nonsensical query.  The pod name is not a grep-like filter, it's a specific name.  

Yeah, the errors could be better.

Describe could work, but potentially generates a LOT of information and API calls.

**Comment by feihujiang** [comment]
@thockin  But I found the following API is supported now.
Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=metadata.name=counter
The result is:
~~~
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/pods",
    "resourceVersion": "10628"
  },
  "items": [
    {
      "metadata": {
        "name": "counter",
        "namespace": "default",
   ......
}
~~~
#14014 has the more information.

Do we need to support the following kubectl command(using the above API) or just return clear error messages? 
#./cluster/kubectl.sh get pods counter --all-namespaces

**Comment by bgrant0607** [comment]
I'd be ok with this being implemented via the field selector.

**Comment by k82cn** [comment]
The issue is still here; I'd like to contribute this :).

```
kc get pods kube-addon-manager-minikubevm --all-namespaces
error: namespace may not be empty when retrieving a resource by name
```

**Comment by k82cn** [comment]
@bgrant0607 , after check the code, the URL was built by `request.go:request(...)`; do you mean we should update it; or avoid to use `NewBuilder(...)`, instead, build url (http://127.0.0.1:8080/api/v1/pods?fieldSelector=metadata.name=counter) directly.

**Comment by k82cn** [comment]
After checking the code, it's better to add fieldSelector to `Helper`, #33087 is created for fieldSelector. Will submit a PR based on #33087 .

**Comment by liggitt** [comment]
getting an object with a particular name across all namespaces seems like something we shouldn't encourage... it breaks the assumption of namespace independence.

**Comment by k82cn** [comment]
@liggitt , so we'll only update message for this issue? for example: `all namespaces or empty namespace is invalid when retrieving a resource by name`

**Comment by RouR** [comment]
> getting an object with a particular name across all namespaces seems like something we shouldn't encourage... it breaks the assumption of namespace independence.

Disagree.
Need easy way to troubleshouting the problem "why pods is stuck in Pending status".
It's tiring for every pod to find who created it and in which namespace. In the logs there is only the name of the pod.
https://github.com/kubernetes/kubernetes/issues/102214

**Comment by djmcgreal-cc** [comment]
Now, with field selectors we can do `kubectl get pods --all-namespaces --field-selector='metadata.name=counter'`

To further my understanding, I'd ask:- doesn't `--all-namespaces` itself break independence? One can search by label across all namespaces, it feels funny for by name to be special.
