### ISSUE TITLE
No service proxy subresource

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#15830]
We created and added "pods/proxy" subresource to remove the need for the generic top level prefix proxy.  We should add the equivalent for service and convert all code to use it (code that does not have to be backwards compatible with a Kube 1.0 or 1.1 server, such as e2e).  We should mark the "proxy/service" construct deprecated for 1.2.

**Comment by smarterclayton** [comment]
Spawned from #15829, but since service proxy is not in 1.0 we can't change client code.

**Comment by feihujiang** [comment]
Is there anybody working on this now? If not, I'd like to volunteer myself to do this work.

**Comment by feihujiang** [comment]
@lavalamp What does the ```help-wanted``` label mean?

**Comment by lavalamp** [comment]
@feihujiang It means we'd love for you to go do this. :)

**Comment by feihujiang** [comment]
Thanks, I got it. I'd love to do this work.

**Comment by feihujiang** [comment]
@smarterclayton @lavalamp I found ```Node``` resource has the generic top level prefix proxy. Do we need to support node proxy subresource? And mark the "proxy/nodes" construct deprecated for 1.2?

**Comment by smarterclayton** [comment]
Yes and yes.

**Comment by lavalamp** [comment]
What Clayton said.

**Comment by feihujiang** [comment]
OK, I'll open a new issue to describe node proxy subresource.

**Comment by mqliang** [comment]
@smarterclayton @lavalamp @feihujiang 

Is there anyone working on "service/proxy" now? If not, I am glad to do.

**Comment by feihujiang** [comment]
@mqliang I have worked on this and almost finished it. The PR is #17493

**Comment by mqliang** [comment]
Ok. Sorry for not noticing it.

BTW, I have a proposal: add a `pod/dockerCmd` subresource, so that user can run some docker commend on it's container, such as commit the image of his container by running `docker commit`.

**Comment by feihujiang** [comment]
You could open a new issue to discuss this. The first question is  why don't you use exec subresource?

**Comment by mqliang** [comment]
The exec subresource can only run commend ***in*** container,  it can not run doker commend.

**Comment by mqliang** [comment]
I open a issue to discuss this https://github.com/kubernetes/kubernetes/issues/18205
