### ISSUE TITLE
Unable to mount volumes for pod

### ISSUE THREAD

**Issue by lorenzvth7** [kubernetes/kubernetes#15833]
I'm trying to create a openshift-project which uses a database (mysql). This is a persistent database. So the content of it will be retained when the pod dies. So I'm working with OpenShift V3, kubernetes and docker. After searching to the solution, I found out it's a kubernetes issue.

First of all I've installed NFS and did the necessary steps to create persistent volumes (pv's). I'm able to create my persistent volums by executing a .yaml. I know I have to change the name manually but this isn't important at this moment. 10.0.0.104 is the internal IP of my openshift-master.
```
{
  "apiVersion": "v1",
  "kind": "PersistentVolume",
  "metadata": {
    "name": "pv0002"
  },
  "spec": {
    "capacity": {
        "storage": "5Gi"
    },
    "accessModes": [ "ReadWriteOnce" ],
    "nfs": {
        "path": "/tmp",
        "server": "10.0.0.104"
    },
    "persistentVolumeReclaimPolicy": "Recycle"
  }
}
```
So I execute this .yaml and I change the name and so I create some persistent volumes. Now I'm creating a very easy project from a template:
```oc new-project demo
oc new-app https://github.com/openshift/ruby-hello-world```

Now it's time to add a database to the project. Herefor I will use this command (as admin):
```oc process -n openshift mysql-persistent -v DATABASE_SERVICE_NAME=database | oc create -f -```

It will use the mysql-persistent template of my openshift project to create an object. I will connect it with my project:
```oc env dc database --list | oc env dc ruby-hello-world -e -```

The output of oc get pv is the following:
```
NAME      LABELS    CAPACITY     ACCESSMODES   STATUS      CLAIM              REASON    AGE
pv0001    <none>    5368709120   RWO           Bound       demo/database             1h
pv0002    <none>    5368709120   RWO           Available                                17m
```

So I thought the db was connected. But in the web console the following error occured and the state of 
the database remained pulling.

```Unable to mount volumes for pod "database-1-28tle_demo": exit status 32```

Is there someone who knows what I'm doing wrong?

**Comment by thockin** [comment]
@kubernetes/rh-storage

**Comment by childsb** [comment]
@lorenzvth7 what's your base OS? and can you check that the NFS package is installed on each host?

To troubleshoot can you create a NFS export then hand mount it from each host to validate that NFS packages, firewall and SELinux are configured properly.

**Comment by lorenzvth7** [comment]
It's CentOS7 and yes, it's installed/running on the master and the nodes: ```ps aux | grep nfsd```
I don't have a lot experience with NFS. Is a persistent volume such an export?
And how should I mount it? Something similar:
In /etc/fstab: ```(internal ip of master)10.0.0.104/home    /mnt/RBD/pv0001 NFS 0 0?```

**Comment by childsb** [comment]
The volumes in the previous GA release of openshift are all NFS.  Upcoming releases will include other volume types.

To mount an NFS volume you can do:

mount -t nfs host:path /mountpoint 

It would be best to create a simple NFS export on the host to use for validation.  Here's some documentation on setting up NFS export:

https://www.centos.org/docs/5/html/Deployment_Guide-en-US/s1-nfs-server-config-exports.html

**Comment by rootfs** [comment]
`exit status 32` looks a dup of #15668 
@lorenzvth7 are you running nfs server in container too? If so, can you check if the host running nfs server has the same dmesg message?

**Comment by lorenzvth7** [comment]
I used this tutorial: http://keithtenzer.com/2015/08/20/openshift-v3-unlocking-the-power-of-persistent-storage/ . So I did not install NFS in a seperate container.

**Comment by rootfs** [comment]
@lorenzvth7 ok, so are you able to mount your nfs volume manually on your kubernetes host?
`mount -t nfs 10.0.0.104:/tmp /mnt`

**Comment by lorenzvth7** [comment]
I was just trying it, but it gave a connection timeout.

**Comment by rootfs** [comment]
@lorenzvth7 connection timeout gives you exit status 32. Possible causes are your nfs server is not running, or connection is blocked by firewall, or you haven't started rpcbind service on nfs server if you are connecting through nfs v3. 

Can you run the same command on your nfs server?

**Comment by four43** [comment]
Hello, I created #15668, my resulting issue was that the minions did not have the correct NFS kernel bits to actually run nfs. I would try SSH-ing into your minion and try mounting the NFS share manually, as @rootfs mentioned.

**Comment by lorenzvth7** [comment]
```[root@ip-10-0-0-104 RBD]# showmount -e 10.0.0.104
Export list for 10.0.0.104:
/mnt/RBD/pv0010 192.168.122.0/24
/mnt/RBD/pv0009 192.168.122.0/24
/mnt/RBD/pv0008 192.168.122.0/24
/mnt/RBD/pv0007 192.168.122.0/24
/mnt/RBD/pv0006 192.168.122.0/24
/mnt/RBD/pv0005 192.168.122.0/24
/mnt/RBD/pv0004 192.168.122.0/24
/mnt/RBD/pv0003 192.168.122.0/24
/mnt/RBD/pv0002 192.168.122.0/24
/mnt/RBD/pv0001 192.168.122.0/24```

```sudo mount -t nfs hostname:/tmp /mnt/RBD/pv0001
mount.nfs: access denied by server while mounting hostname:/tmp```

**Comment by lorenzvth7** [comment]
When I'm creating a whole new persistent volume, without doing exportfs etc.
And I want to mount it to /tmp, I get the following:
```
mount.nfs: timeout set for Tue Oct 20 12:13:28 2015
mount.nfs: trying text-based options 'vers=4,addr=10.0.0.104,clientaddr=10.0.0.104'
mount.nfs: mount(2): No such file or directory
mount.nfs: trying text-based options 'addr=10.0.0.104'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: trying 10.0.0.104 prog 100003 vers 3 prot TCP port 2049
mount.nfs: prog 100005, trying vers=3, prot=17
mount.nfs: trying 10.0.0.104 prog 100005 vers 3 prot UDP port 20048
mount.nfs: mount(2): Permission denied
mount.nfs: access denied by server while mounting ip-10-0-0-104.eu-west-1.compute.internal:/tmp
```

Now the pv was created by this yaml:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: localhost
    path: /home/data/pv0003
```

**Comment by lorenzvth7** [comment]
Iptables on master

```
# Generated by iptables-save v1.4.21 on Tue Oct 20 11:38:04 2015
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1241:185773]
:DOCKER - [0:0]
:OS_FIREWALL_ALLOW - [0:0]
-A INPUT -p udp -m state --state NEW -m multiport --dports 111,892,2049,32769 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m multiport --dports 111,892,2049,32803 -j ACCEPT
-A INPUT -p udp -m multiport --dports 4789 -m comment --comment "001 vxlan incoming" -j ACCEPT
-A INPUT -i tun0 -m comment --comment "traffic from docker for internet" -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j OS_FIREWALL_ALLOW
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -o lbr0 -j DOCKER
-A FORWARD -o lbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lbr0 ! -o lbr0 -j ACCEPT
-A FORWARD -i lbr0 -o lbr0 -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -s 10.1.0.0/16 -j ACCEPT
-A FORWARD -d 10.1.0.0/16 -j ACCEPT
-A FORWARD -s 10.1.0.0/16 -j ACCEPT
-A FORWARD -d 10.1.0.0/16 -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 4001 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 8443 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 53 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 53 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 24224 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 24224 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 2224 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 5404 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 5405 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 10250 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 10255 -j ACCEPT
-A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 10255 -j ACCEPT
COMMIT

# Completed on Tue Oct 20 11:38:04 2015
# Generated by iptables-save v1.4.21 on Tue Oct 20 11:38:04 2015
*nat
:PREROUTING ACCEPT [847:48437]
:INPUT ACCEPT [845:48357]
:OUTPUT ACCEPT [28689:2104294]
:POSTROUTING ACCEPT [28688:2104210]
:DOCKER - [0:0]
:KUBE-NODEPORT-CONTAINER - [0:0]
:KUBE-NODEPORT-HOST - [0:0]
:KUBE-PORTALS-CONTAINER - [0:0]
:KUBE-PORTALS-HOST - [0:0]
-A PREROUTING -m comment --comment "handle ClusterIPs; NOTE: this must be before the NodePort rules" -j KUBE-PORTALS-CONTAINER
-A PREROUTING -m addrtype --dst-type LOCAL -m comment --comment "handle service NodePorts; NOTE: this must be the last rule in the chain" -j KUBE-NODEPORT-CONTAINER
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m comment --comment "handle ClusterIPs; NOTE: this must be before the NodePort rules" -j KUBE-PORTALS-HOST
-A OUTPUT -m addrtype --dst-type LOCAL -m comment --comment "handle service NodePorts; NOTE: this must be the last rule in the chain" -j KUBE-NODEPORT-HOST
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 10.1.2.0/24 ! -o lbr0 -j MASQUERADE
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 10.1.0.0/16 ! -d 10.1.0.0/16 -j MASQUERADE
-A KUBE-PORTALS-CONTAINER -d 172.30.235.119/32 -p tcp -m comment --comment "test/test:8080-tcp" -m tcp --dport 8080 -j REDIRECT --to-ports 47160
-A KUBE-PORTALS-CONTAINER -d 172.30.7.231/32 -p tcp -m comment --comment "default/docker-registry:5000-tcp" -m tcp --dport 5000 -j REDIRECT --to-ports 45616
-A KUBE-PORTALS-CONTAINER -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:" -m tcp --dport 443 -j REDIRECT --to-ports 36831
-A KUBE-PORTALS-CONTAINER -d 172.30.98.219/32 -p tcp -m comment --comment "default/router:80-tcp" -m tcp --dport 80 -j REDIRECT --to-ports 48023
-A KUBE-PORTALS-HOST -d 172.30.235.119/32 -p tcp -m comment --comment "test/test:8080-tcp" -m tcp --dport 8080 -j DNAT --to-destination 10.0.0.104:47160
-A KUBE-PORTALS-HOST -d 172.30.7.231/32 -p tcp -m comment --comment "default/docker-registry:5000-tcp" -m tcp --dport 5000 -j DNAT --to-destination 10.0.0.104:45616
-A KUBE-PORTALS-HOST -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:" -m tcp --dport 443 -j DNAT --to-destination 10.0.0.104:36831
-A KUBE-PORTALS-HOST -d 172.30.98.219/32 -p tcp -m comment --comment "default/router:80-tcp" -m tcp --dport 80 -j DNAT --to-destination 10.0.0.104:48023
COMMIT
# Completed on Tue Oct 20 11:38:04 2015
```

**Comment by lorenzvth7** [comment]
Manually it's al working so I'm now using tis example: https://github.com/openshift/origin/tree/master/examples/wordpress
```
In pod-mysql.yaml:
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql/data
```
So the storage of /var/lib/mysql/data has to come in my /home/data/pv0001 (and vice versa)?
It's possible with:
```
mount -t nfs -v ip-10-0-0-104.eu-west-1.compute.internal:/home/data/pv0001 /var/lib/mysql/data
mount.nfs: timeout set for Tue Oct 20 13:49:17 2015
mount.nfs: trying text-based options 'vers=4,addr=10.0.0.104,clientaddr=10.0.0.129'
```
So when I'm creating a file in /var/lib/mysql/data (on the node), than I see this file in my /home/data/pv0001 on the master.

**Comment by rootfs** [comment]
@lorenzvth7 so you can mount nfs manually now, can you do the same in the pod?

**Comment by lorenzvth7** [comment]
@rootfs How do you mean? So now I'm creating a pv and do exportfs. Than I create a new project with a claim on that pv. Than I create the service and at lat I create the pod (pending state). So you want me to do that command in a pod? I don't really understand

**Comment by rootfs** [comment]
Your `kubectl get event` still shows trouble, but you can mount nfs manually on kubernetes host, correctly? I am wondering   what could be the problem.

**Comment by lorenzvth7** [comment]
I can do it manually but in that case I'm doing nothing with pods

**Comment by lorenzvth7** [comment]
Do I have to do something special what's not mentioned in https://github.com/openshift/origin/tree/master/examples/wordpress ? Mounting is possible with a manual command, but when OpenShift/Kubernetes has to do it, it gets a timeout (exit status 32)

**Comment by markturansky** [comment]
The Wordpress example is step-by-step, apart from installation and
configuration of NFS/nfs-utils, etc.

Which pod in the example is timing out?  MySQL or Apache?

**Comment by lorenzvth7** [comment]
The pod status is pending for both:
```
[root@ip-10-0-0-104 origin]# kubectl get events
FIRSTSEEN   LASTSEEN   COUNT     NAME        KIND      SUBOBJECT   REASON        SOURCE                                               MESSAGE
9m          9m         1         mysql       Pod                   scheduled     {scheduler }                                         Successfully assigned mysql to hostnamenode1
9m          9m         1         wordpress   Pod                   scheduled     {scheduler }                                         Successfully assigned wordpress to hostnamenode2
9m          5s         57        mysql       Pod                   failedMount   {hostnamenode1}   Unable to mount volumes for pod "mysql_wordpress": exit status 32
9m          5s         57        mysql       Pod                   failedSync    {hostnamenode1}   Error syncing pod, skipping: exit status 32
9m          1s         56        wordpress   Pod                   failedMount   {hostnamenode2}   Unable to mount volumes for pod "wordpress_wordpress": exit status 32
9m          1s         56        wordpress   Pod                   failedSync    {hostnamenode2}   Error syncing pod, skipping: exit status 32
```

**Comment by lorenzvth7** [comment]
I don't know what this is:
```
[root@ip-10-0-0-129 centos]# netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 localhost:ieee-mms-ssl  localhost:nfs           TIME_WAIT  
tcp        0      0 ip-10-0-0-129.eu-:46619 ip-10-0-0-:pcsync-https ESTABLISHED
tcp        0      0 ip-10-0-0-129.:iris-lwz ip-10-0-0-104.eu-we:nfs ESTABLISHED
tcp        0      0 localhost:736           localhost:nfs           TIME_WAIT  
tcp        0      0 localhost:834           localhost:nfs           TIME_WAIT  
tcp        0      0 ip-10-0-0-129.eu-:46618 ip-10-0-0-:pcsync-https ESTABLISHED
tcp        0      0 ip-10-0-0-129.eu-:46453 ip-10-0-0-:pcsync-https ESTABLISHED
tcp        0      0 localhost:1016          localhost:nfs           TIME_WAIT  
tcp        0     36 ip-10-0-0-129.eu-we:ssh d54C5660B.access.:57267 ESTABLISHED
tcp        0      0 ip-10-0-0-129.eu-:46449 ip-10-0-0-:pcsync-https ESTABLISHED
tcp        0      0 localhost:rxe           localhost:nfs           TIME_WAIT  
tcp        0      0 ip-10-0-0-129.eu-:46579 ip-10-0-0-:pcsync-https ESTABLISHED
tcp        0      0 ip-10-0-0-129.eu-:46454 ip-10-0-0-:pcsync-https ESTABLISHED
tcp6       0      0 localhost:867           localhost:nfs           TIME_WAIT  
tcp6       0      0 localhost:965           localhost:nfs           TIME_WAIT  
tcp6       0      0 localhost:797           localhost:nfs           TIME_WAIT  
tcp6       0      0 localhost:1015          localhost:nfs           TIME_WAIT  
tcp6       0      0 localhost:974           localhost:nfs           TIME_WAIT  
```

**Comment by markturansky** [comment]
what is "oc status nfs-utils"?   Do you install dependencies on the host or are you attempting a sidecar to put the tools there?

**Comment by lorenzvth7** [comment]
@markturansky I've edited it, it was just 'oc status' so the status of my openshift-project.

**Comment by markturansky** [comment]
I just ran through the example as-is (no repl controller, no sidecars, not attempting to run NFS server in a pod) and it all worked.

Did you attempt the example as-is or did you attempt to modify it to match your RC, etc?

**Comment by lorenzvth7** [comment]
@markturansky I did really everything like in the example. Without editing any files. First as system-admin to create the volumes. Than as openshift-user. The only thing I did was creating a project. So I made my claims inside that project. Just as the pods

**Comment by markturansky** [comment]
Sorry, exactly like the example or within a project?

**Comment by lorenzvth7** [comment]
I don't know if you're familiar with openshift? But I made the pods inside a openshift-project.
So before I do ```oc create -f examples/wordpress/pvc-wp.yaml```, I've done this command: ```oc new-project wordpress```. So that the pods are in the same project. It would surprise me this would be an issue

**Comment by markturansky** [comment]
I am familiar with OpenShift :) I wrote the example and I use it to test OpenShift and the new features I've added upstream.

On the other hand, I don't use all the features of OpenShift and don't really understand the code that drives it.  I cannot discount the difference between our two environments and how we approached running the example.  I know mine works, as I just tested OpenShift with the new provisioning work I added to Kube.

**Comment by lorenzvth7** [comment]
Ow okay :) But don't you put your example in an openshift-project so you can see it in the webconsole. But it still don't look like a solution for the mount issue. What's you're command to mount manually?

**Comment by markturansky** [comment]
Manual mounting instructions are earlier in the comment thread.

**Comment by lorenzvth7** [comment]
@markturansky yes I know but my command, also above, is a bit different I think.

**Comment by lorenzvth7** [comment]
When I just try to create a volumeclaim without creating a project first, than I get this error:
```
[root@ip-10-0-0-104 origin]# oc edit scc restricted
Edit cancelled, no changes made. #was already changed
[root@ip-10-0-0-104 origin]# oc create -f examples/wordpress/pvc-wp.yaml 
Error from server: error when creating "examples/wordpress/pvc-wp.yaml": PersistentVolumeClaim "claim-wp" is forbidden: Namespace wordpress does not exist
```

**Comment by lorenzvth7** [comment]
Can it be an issue that I'm creating the pv's with my admin-account on my master and when I'm doing ```oc get pv```, that I'm seeing my pv's. But when I'm going to another centos7-instance (my node), than I'm only able to login as a normal user which cannot list the pv's:
```Error from server: User "testuser" cannot list all persistentvolumes in the cluster```. But okay, after doing all the stuff I can see a bound for the claims on the right volumes.

**Comment by lorenzvth7** [comment]
Okay finally. I found it. 
First of all I want to thank @markturansky and @rootfs for their help.

The logs showed:
```
Oct 21 10:44:52 ip-10-0-0-129 docker: time="2015-10-21T10:44:52.795267904Z" level=info msg="GET /containers/json"
Oct 21 10:44:52 ip-10-0-0-129 origin-node: E1021 10:44:52.832179    1148 mount_linux.go:103] Mount failed: exit status 32
Oct 21 10:44:52 ip-10-0-0-129 origin-node: Mounting arguments: localhost:/home/data/pv0002 /var/lib/origin/openshift.local.volumes/pods/2bf19fe9-77ce-11e5-9122-02463424c049/volumes/kubernetes.io~nfs/pv0002 nfs []
Oct 21 10:44:52 ip-10-0-0-129 origin-node: Output: mount.nfs: access denied by server while mounting localhost:/home/data/pv0002
Oct 21 10:44:52 ip-10-0-0-129 origin-node: E1021 10:44:52.832279    1148 kubelet.go:1206] Unable to mount volumes for pod "mysql_wordpress": exit status 32; skipping pod
Oct 21 10:44:52 ip-10-0-0-129 docker: time="2015-10-21T10:44:52.832794476Z" level=info msg="GET /containers/json?all=1"
Oct 21 10:44:52 ip-10-0-0-129 docker: time="2015-10-21T10:44:52.835916304Z" level=info msg="GET /images/openshift/mysql-55-centos7/json"
Oct 21 10:44:52 ip-10-0-0-129 origin-node: E1021 10:44:52.837085    1148 pod_workers.go:111] Error syncing pod 2bf19fe9-77ce-11e5-9122-02463424c049, skipping: exit status 32
```

So it was trying to mount with the following arguments:
```
Mounting arguments: localhost:/home/data/pv0002 /var/lib/origin/openshift.local.volumes/pods/2bf19fe9-77ce-11e5-9122-02463424c049/volumes/kubernetes.io~nfs/
```
But the server isn't localhost but the hostname of my master (were the nfs-server is installed) because my pod was created on another node. 

So I had to change the pv-1.yaml and pv-2.yaml of the example and replace localhost by the hostname of my master. After that it works.
A very stupid mistake but I was searching in wrong directions. The last time I saw the var/logs/messages I did not notice this log.

**Comment by markturansky** [comment]
@lorenzvth7 the master node gets an admin client, so it can access things like PVs (an admin resource).  The client used on nodes isn't master and doesn't require access to PVs.

I'm glad you figured out localhost v. hostname.  I missed somewhere in the thread that you're on multiple nodes.  Also, I thought the original PV you posted had an IP instead of localhost, but regardless, I'm glad it now works for you.

There are too many places where this can fail and not enough visibility into the errors to easily diagnose what happened.
