### ISSUE TITLE
podmaster support for etcd with ssl/tls

### ISSUE THREAD

**Issue by genti-t** [kubernetes/kubernetes#15847]
Is there any options to use podmaster with an external etcd cluster with SSL/TLS ?
I see the actual usage:
```
Usage of /podmaster:
      --dest-file="": The destination file to copy to.
      --etcd-servers="": The comma-seprated list of etcd servers to use
      --key="": The key to use for the lock
      --log_flush_frequency=5s: Maximum number of seconds between log flushes
      --sleep=5s: The length of time to sleep between checking the lock.
      --source-file="": The source file to copy from.
      --ttl-secs=30: The time to live for the lock.
      --whoami="": The name to use for the reservation.  If empty use os.Hostname
```

**Comment by genti-t** [comment]
I did find a workaround. 
On the podmaster pod, i created a nginx container as loadbalancer 
from http://127.0.0.1:2379 to my https://etcd-cluster-backend:2379 using 
```
proxy_ssl_certificate 
proxy_ssl_certificate_key
```
IMO, podmaster need the option to connect on a secured etcd cluster.

**Comment by rwehner** [comment]
There is work in progress toward TLS capable podmaster in https://github.com/kubernetes/contrib/pull/130. Might be worth tracking.

**Comment by genti-t** [comment]
Thank You

**Comment by euprogramador** [comment]
IMPORTANT!

this feature is necessary in cluster implementation with failover, thanks @genti-t for workround. nice.

**Comment by huggsboson** [comment]
I believe podmaster is dead in 1.2: #17117

**Comment by carletes** [comment]
@genti-t: Thanks for the Nginx tip! I just published a [Docker image](https://hub.docker.com/r/carletes/k8s-tls-proxy/) to do just that (Dockerfile available at [carletes/k8s-tls-proxy](https://github.com/carletes/k8s-tls-proxy))

**Comment by bgrant0607** [comment]
cc @mikedanese

**Comment by mikedanese** [comment]
Closing as a duplicate of https://github.com/kubernetes/contrib/issues/133 . Pod master is deprecated in v1.2. Use the --leader-elect flags on controller-manager and scheduler.
