### ISSUE TITLE
How to slove this problem "Unit kube-apiserver.service entered failed state"?

### ISSUE THREAD

**Issue by minxinping0105** [kubernetes/kubernetes#15846]
The error :
kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2015-10-19 10:33:32 EDT; 7ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 19445 ExecStart=/usr/bin/kube-apiserver $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBE_ETCD_SERVERS $KUBE_API_ADDRESS $KUBE_API_PORT $KUBELET_PORT $KUBE_ALLOW_PRIV $KUBE_SERVICE_ADDRESSES $KUBE_ADMISSION_CONTROL $KUBE_API_ARGS (code=exited, status=255)
 Main PID: 19445 (code=exited, status=255)

Oct 19 10:33:32 host-192-168-1-167 systemd[1]: Unit kube-apiserver.service entered failed state.
kube-controller-manager.service - Kubernetes Controller Manager
   Loaded: loaded (/usr/lib/systemd/system/kube-controller-manager.service; enabled)
   Active: active (running) since Mon 2015-10-19 10:33:32 EDT; 56ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 19510 (kube-controller)
   CGroup: /system.slice/kube-controller-manager.service
           └─19510 /usr/bin/kube-controller-manager --logtostderr=false --v=0 --master=http://192.168.1.167:8080

Oct 19 10:33:32 host-192-168-1-167 kube-controller-manager[19510]: E1019 10:33:32.981235   19510 reflector.go:136] Failed to list *api.Pod: Get http://192.168.1.167... refused
Oct 19 10:33:32 host-192-168-1-167 kube-controller-manager[19510]: E1019 10:33:32.982749   19510 reflector.go:136] Failed to list *api.PersistentVolume: Get http://... refused
Oct 19 10:33:32 host-192-168-1-167 kube-controller-manager[19510]: E1019 10:33:32.982902   19510 reflector.go:136] Failed to list *api.Namespace: Get http://192.168... refused
Oct 19 10:33:32 host-192-168-1-167 kube-controller-manager[19510]: E1019 10:33:32.981276   19510 reflector.go:136] Failed to list *api.ReplicationController: Get ht... refused
Oct 19 10:33:32 host-192-168-1-167 kube-controller-manager[19510]: E1019 10:33:32.981524   19510 nodecontroller.go:187] Error monitoring node status: Get http://192... refused
Oct 19 10:33:32 host-192-168-1-167 kube-controller-manager[19510]: E1019 10:33:32.983045   19510 reflector.go:136] Failed to list *api.Namespace: Get http://192.168... refused
Oct 19 10:33:32 host-192-168-1-167 kube-controller-manager[19510]: E1019 10:33:32.983016   19510 resource_quota_controller.go:62] Synchronization error: Get http://...22b80)})
Oct 19 10:33:32 host-192-168-1-167 kube-controller-manager[19510]: E1019 10:33:32.983147   19510 reflector.go:136] Failed to list *api.ServiceAccount: Get http://19... refused
Oct 19 10:33:32 host-192-168-1-167 kube-controller-manager[19510]: E1019 10:33:32.983227   19510 reflector.go:136] Failed to list *api.PersistentVolumeClaim: Get ht... refused
Oct 19 10:33:32 host-192-168-1-167 kube-controller-manager[19510]: E1019 10:33:32.983256   19510 reflector.go:136] Failed to list *api.PersistentVolume: Get http://... refused
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by maklemenz** [comment]
Well, we need the full logs instead of shortened ones.
I guess the kube-apiserver binds its insecure port (8080 is not encrypted) on 127.0.0.1 and the node can't reach it. Try to curl the url from your nodes.

**Comment by minxinping0105** [comment]
the curl result
[root@host-192-168-1-167 centos]# curl http://localhost:8080
curl: (7) Failed connect to localhost:8080; Connection refused
[root@host-192-168-1-167 centos]# curl http://localhost:4001
404 page not found

the full logs following :
etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; enabled)
   Active: active (running) since Mon 2015-10-19 11:21:34 EDT; 57ms ago
 Main PID: 29934 (etcd)
   CGroup: /system.slice/etcd.service
           └─29934 /usr/bin/etcd

Oct 19 11:21:34 host-192-168-1-167 bash[29934]: 2015/10/19 11:21:34 etcdmain: listening for client requests on http://localhost:4001
Oct 19 11:21:34 host-192-168-1-167 bash[29934]: 2015/10/19 11:21:34 etcdserver: recovered store from snapshot at index 10001
Oct 19 11:21:34 host-192-168-1-167 bash[29934]: 2015/10/19 11:21:34 etcdserver: name = default
Oct 19 11:21:34 host-192-168-1-167 bash[29934]: 2015/10/19 11:21:34 etcdserver: data dir = /var/lib/etcd/default.etcd
Oct 19 11:21:34 host-192-168-1-167 bash[29934]: 2015/10/19 11:21:34 etcdserver: member dir = /var/lib/etcd/default.etcd/member
Oct 19 11:21:34 host-192-168-1-167 bash[29934]: 2015/10/19 11:21:34 etcdserver: heartbeat = 100ms
Oct 19 11:21:34 host-192-168-1-167 bash[29934]: 2015/10/19 11:21:34 etcdserver: election = 1000ms
Oct 19 11:21:34 host-192-168-1-167 bash[29934]: 2015/10/19 11:21:34 etcdserver: snapshot count = 10000
Oct 19 11:21:34 host-192-168-1-167 bash[29934]: 2015/10/19 11:21:34 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
Oct 19 11:21:34 host-192-168-1-167 bash[29934]: 2015/10/19 11:21:34 etcdserver: loaded cluster information from store: <nil>
Job for kube-apiserver.service failed. See 'systemctl status kube-apiserver.service' and 'journalctl -xn' for details.
kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2015-10-19 11:21:44 EDT; 10ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 29972 ExecStart=/usr/bin/kube-apiserver $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBE_ETCD_SERVERS $KUBE_API_ADDRESS $KUBE_API_PORT $KUBELET_PORT $KUBE_ALLOW_PRIV $KUBE_SERVICE_ADDRESSES $KUBE_ADMISSION_CONTROL $KUBE_API_ARGS (code=exited, status=255)
 Main PID: 29972 (code=exited, status=255)

Oct 19 11:21:44 host-192-168-1-167 systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Oct 19 11:21:44 host-192-168-1-167 systemd[1]: Failed to start Kubernetes API Server.
Oct 19 11:21:44 host-192-168-1-167 systemd[1]: Unit kube-apiserver.service entered failed state.
kube-controller-manager.service - Kubernetes Controller Manager
   Loaded: loaded (/usr/lib/systemd/system/kube-controller-manager.service; enabled)
   Active: active (running) since Mon 2015-10-19 11:21:44 EDT; 49ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 30044 (kube-controller)
   CGroup: /system.slice/kube-controller-manager.service
           └─30044 /usr/bin/kube-controller-manager --logtostderr=true --v=0 --master=http://192.168.1.167:8080

Oct 19 11:21:44 host-192-168-1-167 kube-controller-manager[30044]: E1019 11:21:44.746329   30044 reflector.go:136] Failed to list *api.ReplicationController: Get http://192.168.1.167:8080/api/v...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-controller-manager[30044]: E1019 11:21:44.746377   30044 reflector.go:136] Failed to list *api.Pod: Get http://192.168.1.167:8080/api/v1/pods: dial tcp 1...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-controller-manager[30044]: E1019 11:21:44.746447   30044 reflector.go:136] Failed to list *api.Namespace: Get http://192.168.1.167:8080/api/v1/namespaces...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-controller-manager[30044]: E1019 11:21:44.746521   30044 resource_quota_controller.go:62] Synchronization error: Get http://192.168.1.167:8080/api/v1/res...2081a0f40)})
Oct 19 11:21:44 host-192-168-1-167 kube-controller-manager[30044]: E1019 11:21:44.746667   30044 nodecontroller.go:187] Error monitoring node status: Get http://192.168.1.167:8080/api/v1/nodes:...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-controller-manager[30044]: E1019 11:21:44.746848   30044 reflector.go:136] Failed to list *api.PersistentVolumeClaim: Get http://192.168.1.167:8080/api/v...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-controller-manager[30044]: E1019 11:21:44.746900   30044 reflector.go:136] Failed to list *api.PersistentVolume: Get http://192.168.1.167:8080/api/v1/per...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-controller-manager[30044]: E1019 11:21:44.746924   30044 reflector.go:136] Failed to list *api.PersistentVolume: Get http://192.168.1.167:8080/api/v1/per...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-controller-manager[30044]: E1019 11:21:44.746977   30044 reflector.go:136] Failed to list *api.ServiceAccount: Get http://192.168.1.167:8080/api/v1/servi...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-controller-manager[30044]: E1019 11:21:44.746996   30044 reflector.go:136] Failed to list *api.Namespace: Get http://192.168.1.167:8080/api/v1/namespaces...tion refused
Hint: Some lines were ellipsized, use -l to show in full.
kube-scheduler.service - Kubernetes Scheduler Plugin
   Loaded: loaded (/usr/lib/systemd/system/kube-scheduler.service; enabled)
   Active: active (running) since Mon 2015-10-19 11:21:44 EDT; 49ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 30078 (kube-scheduler)
   CGroup: /system.slice/kube-scheduler.service
           └─30078 /usr/bin/kube-scheduler --logtostderr=true --v=0 --master=http://192.168.1.167:8080

Oct 19 11:21:44 host-192-168-1-167 systemd[1]: Started Kubernetes Scheduler Plugin.
Oct 19 11:21:44 host-192-168-1-167 kube-scheduler[30078]: E1019 11:21:44.865193   30078 reflector.go:136] Failed to list *api.Pod: Get http://192.168.1.167:8080/api/v1/pods?fieldSelector=spec.n...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-scheduler[30078]: E1019 11:21:44.865248   30078 reflector.go:136] Failed to list *api.Node: Get http://192.168.1.167:8080/api/v1/nodes?fieldSelector=spec...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-scheduler[30078]: E1019 11:21:44.865251   30078 reflector.go:136] Failed to list *api.Pod: Get http://192.168.1.167:8080/api/v1/pods?fieldSelector=spec.n...tion refused
Oct 19 11:21:44 host-192-168-1-167 kube-scheduler[30078]: E1019 11:21:44.865285   30078 reflector.go:136] Failed to list *api.Service: Get http://192.168.1.167:8080/api/v1/services: dial tcp 19...tion refused
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by jlowdermilk** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by yogesh9391** [comment]
Hello,
I also faced the same issue. I solved it as -
$journalctl -xe command gives the full log. There I found that the .pem file was missing. somehow it was removed mistakenly. I created that and restrated the kube-apiserver service. Things are working for me. For creating .pem file and other related conf , I followed http://stackoverflow.com/questions/31891734/not-able-to-create-pod-in-kubernetes

Hope this will solve your issue.

**Comment by Deepak3994** [comment]
Hello,

When I am trying to connect to my web browser i get following error,

I0803 10:31:18.642233   21809 logs.go:41] http: proxy error: dial tcp 127.0.0.1:8080: connect: connection refused

So, I checked for kube-apiserver status,
● kube-apiserver.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

Its's showing the status is dead(inactive). Can anyone help me out here in this issue how to restart the kube-apiserver and get it up and running.

**Comment by rajraulo** [comment]
Try the following commands will restart kube-apiserver
$ systemctl daemon-relaod
$ systemctl restart kube-apiserver
