### ISSUE TITLE
Fix capitalization of acronyms from #15247

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15852]
#15247 introduced a bunch of "incorrect" capitalization (as per Go rules).

Easy fix for someone - globally search/replace 'KubeApiQps' to 'KubeAPIQPS' or 'KubeAPIRateQPS`  and  'KubeApiBurst' to 'KubeAPIBurst'

**Comment by stevesloka** [comment]
This was merged in #15946 and can be closed.
