### ISSUE TITLE
kubectl get in namespace with no objects returns nothing

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#15853]
```
➜  kubernetes git:(master) kubectl get po
➜  kubernetes git:(master) echo $? 
0
```

Before it would return the column headers.

cc @JanetKuo

**Comment by nhlfr** [comment]
Looking at this

**Comment by nhlfr** [comment]
Unfortunately, it seems to be tricky to fix with all the reflection stuff which is used inside resource printer.

The thing is, that in `pkg/kubectl/cmd/get.go` we have a list of `runtime.Object`. And then the single elements of this list are passed here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L2159-L2187

Resource printer is doing reflection on the first single element that is passed to it. When we have an empty list in `get.go`, we don't know what type we requested, so reflection cannot be used here.

I'll try to think how to rewrite the printer to consume information about requested resource from somewhere else (CLI args?).

**Comment by smarterclayton** [comment]
Fixing this.
