### ISSUE TITLE
Cannot format a selector with jsonpath

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#15858]
I can't find a way to format a selector from a json representation of a selector, using our jsonpath output.

There doesn't seem to be an operator that extracts keys and values from a map.

This is possible-ish using `jq`:

``` console
$ sel=$(./kubectl get rc <rc-name> --output=json | jq -j '.spec.selector | to_entries | .[] | "\(.key)=\(.value),"')
$ sel=${sel%?} # Remove trailing comma
```

Is our plan to extend jsonpath, to be further non-standard, as needs like this arise, or to fall-back to more sophisticated processors such as jq for more complex cases like this?

**Comment by erictune** [comment]
xref: #15584

**Comment by erictune** [comment]
xref: #12771

**Comment by thockin** [comment]
+1, I can't really find much in the way of concise docs on jsonpath, and I am wrestling to do with it what I know how to do in go-template, and I don't even know go-template very well.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by nikhita** [comment]
Removing help-wanted as there isn't a clear direction and details on how to fix this for contributors to dive into.

/remove-help

**Comment by liggitt** [comment]
/close

The layer that does jsonpath rendering is intentionally type-agnostic. I don't anticipate adding kube-specific object rendering there.

Resources that support the /scale subresource (replication controllers, replicasets, deployments, statefulsets, some custom resources, etc) return a stringified selector in the `.status.selector` field of the scale subresource:

```
kubectl get --raw /apis/apps/v1/namespaces/default/deployments/my-dep/scale | \
  jq -r .status.selector
```

Something like https://github.com/kubernetes/kubernetes/pull/60902 that would allow `kubectl get|patch` to make requests to subresources would let us do this:
```
kubectl get deployment/my-dep --subresource=scale -o jsonpath="{.status.selector}"
```

xref https://github.com/kubernetes/kubectl/issues/564 for adding subresource support to kubectl which would enable getting string-formatted selectors for scale-supporting resources.
