### ISSUE TITLE
Consistent use of pointers re: optional in internal and versioned client structs

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#15859]
Per #15566 we should use pointers when a field in a go struct is optional, and not use pointers when it is required.

We should clean this up at some point.

Also, since it will affect the in-progress versioned clients, we should think about doing the cleanup before that is released.  Making the pointer-means-optional thing consistent will make the versioned clients easier for client-users to understand.

**Comment by erictune** [comment]
@krousey for versioned client.

**Comment by lavalamp** [comment]
It's a really big change. I wasn't planning on tackling this for 1.2.

**Comment by erictune** [comment]
What about at least making new types follow the rule?
DeploymentSpec and DaemonSetSpec  say:
```
`Template *v1.PodTemplateSpec `json:"template,omitempty"`
``` 
even though it is required.  Only Job does this right.
