### ISSUE TITLE
Cleanup: Audit log and error capitalization

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#15863]
Generally: log-lines start with capital letters; error strings do not (unless it starts with an acronym like IP).  We're not consistent with this.  It should be relatively easy to audit these and fix-up.

**Comment by kargakis** [comment]
Maybe an update/validate script so we can keep this consistent in the future too?

See https://gist.github.com/porjo/b331df0b3d7e33c30920 for example

**Comment by kargakis** [comment]
@kubernetes/sig-contributor-experience-misc

**Comment by spxtr** [comment]
Ideally this could be added to golint or something, although sometimes it does make sense to start it with a capital letter. Running `ag "(errors\.New|fmt\.Errorf)\(\"[A-Z]"` is not happy times.

**Comment by kargakis** [comment]
Due to acronyms or are you thinking of something else?

**Comment by spxtr** [comment]
Say you have some function that needs an environment variable set. It makes sense to see `return errors.New("KUBERNETES_PROVIDER unset")` or something. You could argue that we could try to enforce something like `return errors.New("env variable KUBERNETES_PROVIDER unset")`, but it's not totally clear.

There are other similar cases.

**Comment by spxtr** [comment]
Replacing `fmt.Errorf` with `errors.New` where appropriate: https://github.com/golang/lint/issues/284

**Comment by kargakis** [comment]
@spxtr we could check if the first letter is part of a word that is capitalized and ignore lowercasing it in such a case. Maybe python would be better than sed in that case? Or extend golint? Not sure.

**Comment by spxtr** [comment]
Right but what about if you're checking that a public struct member is set? `return errors.New("PublicStructMember must be set")`.

It might be worth just enforcing the check and rewriting error statements even for cases where it makes sense.

> Maybe python would be better than sed in that case? Or extend golint? Not sure.

Extend golint > add some gometalinter > python > sed.

**Comment by spxtr** [comment]
Ooh, @krousey notes that `golint` already does this, but you have to lower the `min_confidence`. Then you get errors like this: `runners.go:77:25: error strings should not be capitalized and should not end with punctuation`

**Comment by krousey** [comment]
@spxtr That message triggers on errors that end with punctuation with a 0.8 confidence level. It triggers on capitalized messages with a 0.6 confidence level. https://github.com/golang/lint/blob/master/lint.go#L1171

**Comment by stevekuznetsov** [comment]
@kargakis if you're parsing Go source and taking actions from it you should really use [`go/ast`](https://golang.org/pkg/go/ast/) and do it "right"

**Comment by Ch3ck** [comment]
@thockin @stevekuznetsov I'll like to work on this issue. How much work has been done so far?

**Comment by nikhita** [comment]
/remove-priority awaiting-more-evidence

I don't think `priority/awaiting-more-evidence` and `help wanted` labels should be on the same issue. :)

This issue looks like it's got sufficient evidence already.

**Comment by nikhita** [comment]
I'm going to label this as a good first issue because it involves changing the error/log messages.

/good-first-issue

**Comment by RajatVaryani** [comment]
Hello. How can I identify all the places where this change needs to be done?

**Comment by nikhita** [comment]
@RajatVaryani you can use something like https://gist.github.com/porjo/b331df0b3d7e33c30920

**Comment by RajatVaryani** [comment]
@nikhita Thanks.

**Comment by stevekuznetsov** [comment]
@nikhita @RajatVaryani for an approach that will remain relevant to the future, it seems like an edit program using `go/ast` paired with a validation would be more appropriate than a one-off

**Comment by nikhita** [comment]
> So should we consider errors like "PublicStructMember must be set" legal?

Yes, they should be remain as-is and be considered legal.

@sunho Thanks for your PR, that's a big change! :D

**Comment by ShivangGoswami** [comment]
for eg:
c.t.Fatalf("got encryptionConfig:\n%q\n, want encryptionConfig:\n%q", got, want)
needs to be changed to:
c.t.Fatalf("Got encryptionConfig:\n%q\n, want encryptionConfig:\n%q", got, want)
or only strings in error.New() and fmt.Errorf() needs to be changed?

**Comment by nikhita** [comment]
@ShivangGoswami Only Kubernetes GitHub org members can be assigned. Even though you can't be assigned to the issue, please feel free to work on it. :)

**Comment by MatonAnthony** [comment]
Hello, I am interested to work on this.

As far as my understanding goes, there is two issues here:
1. Fixing existing cases
2. Write a script that could be added to CI to ensure compliance with this convention.

While the first issue seems easy enough to approach (but quite long), I don't really know how to approach the second one properly.

Does anyone have an idea about how this should be approached ?

**Comment by vnktram** [comment]
@nikhita I'm willing to pick this up.
