### ISSUE TITLE
No nodes available to schedule pods (using google container engine)

### ISSUE THREAD

**Issue by atrauzzi** [kubernetes/kubernetes#15865]
Apologies if this isn't the correct place to inquire, but I've got an issue with a container not running and I'm currently at a loss as to what my next course of action should be.

Please see the following SO question for details: http://stackoverflow.com/questions/33219383/no-nodes-available-to-schedule-pods-using-google-container-engine

I guess the main issue for me at the moment as it pertains to the kubernetes project is that while it's told me my container isn't running, I have absolutely zero indication as to why.

Hopefully someone here might have the time to help me understand what I'm doing wrong.  But moreover, perhaps this is a situation where more feedback from the tools/environment might be helpful?

**Comment by jlowdermilk** [comment]
Your stackoverflow post appears to have the answer; as `kubectl get nodes` showed, you have (had?) no working nodes in your cluster so the scheduler could not schedule your container. For future reference, we are consolidating/redirecting help/support questions of this sort to stackoverflow to improve our efficiency in responding to issues and make it easier for others to search for and find and reuse solutions. 

Thanks for using kubernetes

**Comment by atrauzzi** [comment]
Yeah, the issue is obviously that I have no working nodes.  But `kubectl` doesn't tell me why.
