### ISSUE TITLE
Flaky: Job should run a job to completion when tasks sometimes fail and are locally restarted

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#15866]
Has failed twice this morning in the release branch and I've seen other failures on pull request buildngin
```
Job should run a job to completion when tasks sometimes fail and are locally restarted

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/job.go:75
Expected error:
    <*errors.errorString | 0xc20807c830>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release-1.1/215/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-release-1.1/217/

@soltysh @erictune

**Comment by brendandburns** [comment]
Dup of #15389
