### ISSUE TITLE
Run versionize-docs in release branch

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#15864]
Lots of links in swagger-spec and hence our static documentation point to ```http://releases.k8s.io/HEAD/docs``` instead of pointing to ```http://releases.k8s.io/v1.1.0/docs```.
My guess is these sneaked in with the cherrypicks we have been doing. We ran versionize-docs only when we were cutting the release branch.

We should run versionize-docs in the release branch when all the cherrypicks have been done and we should really have a test for this.

cc @lavalamp @caesarxuchao @kubernetes/goog-csi

**Comment by lavalamp** [comment]
It would be awesome if somehow we could keep the commit that changes these stacked on top of everything else in the branch, to keep down the merge conflicts. But I can't imagine a way of doing that that would work well with github. I guess it won't be too bad because hopefully we'll soon stop pulling things that change the docs.

**Comment by nikhiljindal** [comment]
We need to fix https://github.com/kubernetes/kubernetes/issues/15905 before we can run run-gen-swagger-docs in release branch.

**Comment by lavalamp** [comment]
@nikhiljindal Just confirming, this is now just a button we need to push right before cutting the release, right?

**Comment by nikhiljindal** [comment]
This is already part of the release cutting process.
But we need to run it once in release-1.1 branch for all the cherrypicks we have done after cutting the branch.

**Comment by ihmccreery** [comment]
We run `versionize-docs` in the release branch when cutting a new official version, so these *should* all get corrected.

As part of #15483 I plan on running versionize-docs on beta releases as well.

**Comment by ihmccreery** [comment]
Run in [mark-new-version](https://github.com/kubernetes/kubernetes/blob/master/build/mark-new-version.sh#L99).

**Comment by lavalamp** [comment]
Anything left to do here?

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/16335 fixed this.
Closing
