### ISSUE TITLE
Document recent insights/decisions about API backward compatibility

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#15879]
While it's still fresh in my mind.

From label selector and pod security context discussions:
https://github.com/kubernetes/kubernetes/issues/341#issuecomment-140809259
https://github.com/kubernetes/kubernetes/pull/14705#issuecomment-149287760

cc @pmorie @smarterclayton @thockin

**Comment by timothysc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by bgrant0607** [comment]
we should also add something about not strengthening validation: #21680

cc @liggitt

**Comment by bgrant0607** [comment]
There's more discussion here: https://github.com/kubernetes/kubernetes/issues/30819#issuecomment-252774539

A single feature cannot be represented using multiple spec fields in the same API version simultaneously. Only one field can be populated in any resource at a time, and the client needs to be able to specify which field they expect to use, on both mutation and read.

**Comment by bgrant0607** [comment]
Documented.
https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#backward-compatibility-gotchas
