### ISSUE TITLE
SELinux and Kubernetes

### ISSUE THREAD

**Issue by mooperd** [kubernetes/kubernetes#15883]
Hallo,

No an issue per se but I am looking for some information about SELinux support for Kubernetes. Does this just work if using fedora hosts?

ta,

Andrew

**Comment by thockin** [comment]
@kubernetes/rh-platform-management 

Any OS that is configured for SELinux should work.

**Comment by mooperd** [comment]
@thockin thanks for the fast response. Do you see benefits of using SELinux with kubernetes?

**Comment by thockin** [comment]
That's a trick question.

I have very limited personal experience with SELinux - mostly it just stops
me from doing the things I know I want to do and then I turn it off.  But
obviously SOME people think it is valuable :)

**Comment by mooperd** [comment]
Thats mandatory access control for ya!

**Comment by pmorie** [comment]
@mooperd EmptyDir volumes should work correctly on Fedora.  We are working on adding support for other volume types in #14192 #14991 

I have done most of the coding on selinux and kube so far, so feel free to ask questions on slack or irc if you have any.

**Comment by mooperd** [comment]
@pmorie Thanks for the response!

We are typically specifying SELinux in places where there is a risk of intrusion. Public facing APIs or services touching more sensitive data. With SELinux we are able to "concrete in" our processes and be sure that a compromised process can only do exactly what we specify which significantly reduces the attack surface.

I've been watching the Redhat effort with Docker with interest. As far as I can understand the Docker SELinux policies are similar to sVirt, the Selinux policy for LibVirt. This policy protects against compromises of the virtualisation layer, ensuring that a virtual machines resources are only accessible by a specific virtual machine. This approach protects the hypervisor and the other virtual machines on the host but does not prevent the attacker from exploring the compromised virtual machines, disk volumes or the network attached to that virtual machine.

With Kubernetes; If a docker container get compromised and an attacker is playing around; trying various attack vectors what kind of activity can we expect to see in the SELinux audit.log? With non docker services this log is very useful to watch and can quickly tell us if someone is testing the fences. How tight is the policy and what kind of activity would be automatically denied / allowed? What booleans are available? Is there integration with Atomic? https://github.com/projectatomic/atomic

Thanks,

Andrew

**Comment by pmorie** [comment]
@mooperd Probably easiest to message me on slack to have a higher-bandwidth discussion.
