### ISSUE TITLE
Pod deletion broken in version skewed (1.1 master, 1.0 node) because of GracefulTermination

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#15895]
```
mikedanese@e2e-test-jenkins-master:~$ cat nginx-pod.yml 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
mikedanese@e2e-test-jenkins-master:~$ k create -f nginx-pod.yml 
pod "nginx" created
mikedanese@e2e-test-jenkins-master:~$ k get po
NAME                  READY     STATUS        RESTARTS   AGE
nginx                 0/1       Running       0          3s
mikedanese@e2e-test-jenkins-master:~$ k delete -f nginx-pod.yml 
pod "nginx" deleted
mikedanese@e2e-test-jenkins-master:~$ k get po
NAME                  READY     STATUS        RESTARTS   AGE
nginx                 1/1       Terminating   0          17s
```

The nginx pod remains Terminating forever. The container process stays running on the node. 1.0 kubelet does not know how to handle graceful termination.

@smarterclayton @davidopp @ihmccreery

**Comment by bgrant0607** [comment]
Looks like #12962 was intended to address this scenario.

**Comment by bgrant0607** [comment]
The relevant code is primarily in terminatePods in pkg/controller/node/nodecontroller.go.

The question is whether pods aren't getting deleted fast enough or whether that just isn't working.

One improvement could be to take the Kubelet version into account and delete pods immediately for 1.0.x Kubelets.

**Comment by ihmccreery** [comment]
This may or may not be the same as, or related to, #15123.

**Comment by bgrant0607** [comment]
Forked from #15123, which appears to have additional problems.

**Comment by smarterclayton** [comment]
The Kubelet owns responsibility for terminating pods.  If it doesn't, we have no component that can manage it barring a general purpose GC controller. We could have a feature flag that disables graceful in the API until all Kubelets are upgraded, or have the node controller manage graceful termination on back level nodes.

**Comment by smarterclayton** [comment]
The latter is probably more effective

**Comment by mikedanese** [comment]
@bgrant0607 looking at  #12962 more closely, terminatePods is only ever called on nodes that are being evicted.

**Comment by bgrant0607** [comment]
Yes, we're effectively violating the policy discussed in #4855 by using a feature by default that doesn't work until Kubelets are updated.

@mikedanese That explains why it doesn't help this case. :-)

@smarterclayton Mike and I discussed GC controller vs. node controller. My conclusion was that node controller would be a better fit. I thought about adding a feature flag, but it seemed like getting the corner cases all correct when flipping it would be hard, it probably would be confusing for users, and we also don't really want to surface such a flag in GKE.

**Comment by smarterclayton** [comment]
I also prefer node controller.  I'll send a patch tomorrow morning.

On Oct 19, 2015, at 8:33 PM, Brian Grant <notifications@github.com> wrote:

Yes, we're effectively violating the policy discussed in #4855
<https://github.com/kubernetes/kubernetes/issues/4855> by using a feature
by default that doesn't work until Kubelets are updated.

@mikedanese <https://github.com/mikedanese> That explains why it doesn't
help this case. :-)

@smarterclayton <https://github.com/smarterclayton> Mike and I discussed GC
controller vs. node controller. My conclusion was that node controller
would be a better fit. I thought about adding a feature flag, but it seemed
like getting the corner cases all correct when flipping it would be hard,
it probably would be confusing for users, and we also don't really want to
surface such a flag in GKE.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15895#issuecomment-149385243>
.

**Comment by mikedanese** [comment]
@smarterclayton I'm already preparing one.

**Comment by bgrant0607** [comment]
Is there a reason why we shouldn't also immediately delete terminated pods, just as we do for not-yet-scheduled pods?
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/pod/strategy.go#L109

**Comment by mikedanese** [comment]
@bgrant0607 add that in PR #15900

**Comment by smarterclayton** [comment]
When?  Unscheduled pods aren't under the control of a Kubelet, scheduled
pods are.  If we delete immediately clients have no feedback to termination.

The node controller managing termination for a node controller is
reasonable - it emulates 1.0 behavior.

On Oct 19, 2015, at 9:18 PM, Brian Grant <notifications@github.com> wrote:

Is there a reason why we shouldn't also immediately delete terminated pods,
just as we do for not-yet-scheduled pods?
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/pod/strategy.go#L109

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/15895#issuecomment-149391616>
.

**Comment by smarterclayton** [comment]
Oh, you meant "run to completion".  Yes, we should.

**Comment by mikedanese** [comment]
WIP in #15930
