### ISSUE TITLE
examples/cassandra: Mention DaemonSets as a method of creating cassandra pods

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#15891]
Right now the cassandra docs use a ReplicationController. I think it would be good to update the doc to mention using daemon sets as a valid way to place a single cassandra node on each of the kubernetes nodes, a more realistic deployment method. 

See #15324

**Comment by jlowdermilk** [comment]
cc @mikedanese

**Comment by mikedanese** [comment]
I disagree that it's a "more realistic" deployment. I would actually recommend against running a cassandra cluster in this way. Why do you think it's better?

**Comment by paralin** [comment]
@mikedanese The point of Cassandra, if I'm not mistaken, is to have a single cassandra node on each piece of hardware / VM instance. That way, data is replicated reliably across instances, so if one dies you'll still be okay. It makes no sense therefore, to run more than one cassandra node on a server / kubernetes node, as you could get a single record stored on the same instance, which gives no reliability in the case of instance failure and defeats the purpose of Cassandra.

So, unless there's some way to force Kubernetes to schedule only one of a pod on each node, and also schedule one on each node to have full cluster spread of data, DaemonSets seems like the best way to do it to me.

**Comment by mikedanese** [comment]
cc @erictune

**Comment by vyshane** [comment]
I think that [Persistent Volumes and Claims](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/persistent-volumes.md#persistent-volumes-and-claims) are the correct abstractions for this use case.

**Comment by paralin** [comment]
@vyshane I don't think so - if you mean instead of DaemonSet. Cassandra nodes are completely fine with using ephemeral storage, as long as there are enough nodes in the cluster to replicate data in the case of sudden-instance-implosion. The key point is you need to be running **one** per machine, not multiple, so DaemonSet makes sense.

Or did I misunderstand what you're suggesting?

**Comment by davidopp** [comment]
I like the idea of augmenting the Cassandra documentation with information about how to run it using DaemonSet, if for no other reason than to give us more examples of DaemonSet. But I would remove the sentence "It's optimal to run a single Cassandra pod per each applicable node in the cluster" because I don't think that's true (and in any event, the meaning of "optimal" is not very well-defined here). I think most people probably run Cassandra on a subset of the cluster, not the whole cluster. 

As an aside, you can limit to one pod per node using Replication Controller and a bit of a hack: you set a hostPort in the pod template (just pick any number you want -- the scheduler won't schedule more than one pod per node because it would cause a port conflict).

@zmerlynn

**Comment by paralin** [comment]
@davidopp No problem, I'll remove that line. Probably too opinionated anyway.

The only downside I see to the nodePort hack is that you cannot set replicas == node_count.

**Comment by erictune** [comment]
Talked with @bgrant0607 and @mikedanese.

We get that you don't want to run two cassandra pods on the same node, and we plan to improve the scheduler to allow preventing that.

But DaemonSet is not just about not wanting duplicates. It is also about wanting a copy on every node.

None of us have much experience with Cassandra. That said, we don't understand why you would want to run Cassandra on every node. I can see doing that for a generic storage layer, like HDFS, Ceph/Rados or Glusterfs. But, with Cassandra providing more of a database layer, I think that you would want to scale the number of Cassandra nodes in proportion to the demand for database storage, as opposed to other types of storage (e.g. block or blob storage).

So, at this point we are hesitant to recommend that approach by presenting an example of it.

**Comment by paralin** [comment]
@erictune It's about redundancy - you want to spread the data storage over the entire cluster not for storage space as much as reliability. I'm taking from [Netflix's best practices](https://netflix.github.io/) and OSS recommendations here. The idea is to expect that instances will die at any time, and with that expectation, to spread the data and replicate it over as many instances as possible, so that if, say, half of them died, you have a very high chance of still maintaining the data through replicated pairs.

So for Cassandra, placing a storage node on every node in the cluster is *exactly* what you want. It's not related to storage space, as it would be with MySQL or Mongo or other storage databases.

I'm by no means an expert or even very experienced with this, but according to everything I've read and my own experience, this makes sens.

**Comment by paralin** [comment]
I updated the PR to add the reasoning behind using a DaemonSet, as per suggestions
