### ISSUE TITLE
nodecontroller deleted all nodes in healthy cluster

### ISSUE THREAD

**Issue by emaildanwilson** [kubernetes/kubernetes#15929]
I modified the VPC that kubernetes was running in to no longer provide DNS hostnames. Then the check for ExternalID in the node controller failed which took down all the nodes in the cluster.

Would it be ok to make this check more intelligent and less stringent on externalid? The cluster was perfectly healthy otherwise. Perhaps there is a better way to check on the ExternalID for AWS? It looks like the current check relies on private-dns-name instead of the instance id. 

This is on 1.2 Alpha 2.

Mon, 19 Oct 2015 21:44:21 -0700   Mon, 19 Oct 2015 21:45:03 -0700   9         ip-10-25-45-106.us-west-2.compute.internal   Node                  DeletingNode        {controllermanager }   Node ip-10-25-45-106.us-west-2.compute.internal event: Deleting Node ip-10-25-45-106.us-west-2.compute.internal because it's not present according to cloud provider

**Comment by davidopp** [comment]
@justinsb

**Comment by davidopp** [comment]
ping @justinsb

**Comment by davidopp** [comment]
@brendandburns

**Comment by dmytroleonenko** [comment]
Seeing it in a brand new cluster. 1.3.7 coreos

**Comment by emaildanwilson** [comment]
Closing this since it's incredibly old and there are completely different setup options now.
