### ISSUE TITLE
Getting compilation error for unused variable "var tokenName string" in file service_accounts.go

### ISSUE THREAD

**Issue by gajju26** [kubernetes/kubernetes#15934]
While Compiling the source code of Kubernetes, I am getting a compilation error saying tokneName var is unused. 
Please find below the link of the file:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/service_accounts.go
If this variable is not needed in future can we remove this from the code.

**Comment by jlowdermilk** [comment]
From the link, that value is definitely used, and that warning does not appear in our ci builder. Try re-syncing to master and building again.
