### ISSUE TITLE
Unclear Documentation: Services, NodePorts, and Custom Load Balancers

### ISSUE THREAD

**Issue by activeshadow** [kubernetes/kubernetes#15940]
I'm needing a load balancer, external to my Kubernetes environment, that facilitates session affinity via means other than **client IP**. In reading the documentation for services, I see where it's mentioned that a service of type `NodePort` "gives developers the freedom to set up their own load balancers". This seems like a good start, but it also mentions that a `NodePort` uses a cluster IP along with a random port on each Kubernetes node that proxies traffic to the Service. This makes sense, but it got me to thinking that any traffic sent to the `NodePorts` is still going to get load balanced against the service's pods by the `kube-proxy`.

So ultimately I'm confused by the documentation... how should a developer go about leveraging `NodePorts` in support of their own load balancer with custom session affinity rules? Am I incorrect in thinking that once the traffic is in the Kubernetes environment it's still going to get proxied to pods via a random selection? Is it possible that #8731 would be useful here?

**Comment by kevinsimper** [comment]
@activeshadow I am also reading up on this and when exposing a replicationController through a service, then it will be load-balanced inside Kubernetes, but you would still need to do things like TLS termination.

**Comment by cmluciano** [comment]
This issue is quite stale. The documentation has underwent a major overhaul. Please take a look at https://kubernetes.io/docs/concepts/services-networking/service/ and re-open this issue if it still does not address the problem.
