### ISSUE TITLE
Unclear how to enable experimental API features

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#15968]
Possibly a documentation issue, possibly a code issue.

How can I enable experimental features, like daemonsets?

I noticed here, that it seems the code ignores the environment variable for runtime config:

https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L1037

and defaults to extensions/v1beta1 only.

**Comment by mikedanese** [comment]
Documented in the api docs. Do those instructions not work?

https://github.com/kubernetes/kubernetes/blob/master/docs/api.md#enabling-the-extensions-group

Implemented in https://github.com/kubernetes/kubernetes/pull/15516

**Comment by paralin** [comment]
When deploying to AWS I enable KUBE_ENABLE_EXPERIMENTAL_API.

This causes:

 - ENABLE_EXPERIMENTAL_API to be set here: https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/config-default.sh#L62
 - This causes this flag to be set in salt: https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/templates/create-dynamic-salt-files.sh#L45
 - This sets enable_experimental_api in https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/pillar/cluster-params.sls I believe? 
 - Sets RUNTIME_CONFIG here: https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/util.sh#L444

However down the line I don't see what RUNTIME_CONFIG actually ends up doing. In the actual cluster the command line doesn't have the argument appended to it, and in the code here:

https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L1037

It really doesn't seem like the flag would work. It's hardcoded to v1beta1.

The only way I can get the new daemonset API enabled, it seems, is with this hack:

https://github.com/paralin/kubernetes/commit/940a731137a5b93ab66bf8cc30262f79b796245f

Any ideas? @mikedanese

**Comment by mikedanese** [comment]
Can you see if this patch fixes ENABLE_EXPERIMENTAL_API?

https://github.com/kubernetes/kubernetes/pull/15984

**Comment by paralin** [comment]
@mikedanese I'm not clear why this would fix it when beta1 is enabled https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L1037 in a hardcoded line anyways?

**Comment by paralin** [comment]
Ah I see, that function isn't called unless experimental is enabled.

```
if !m.apiGroupVersionOverrides["extensions/v1beta1"].Disable
```

However, I didn't pull your PR code and manually added it here:

https://github.com/paralin/kubernetes/commit/940a731137a5b93ab66bf8cc30262f79b796245f

And it worked. So that would indicate that the function IS being called, and those are not activated under beta1.

This makes sense as I believe the daemonsets are classified as alpha right now. But there's no way to enable the alpha sets, as far as I can see.

**Comment by mikedanese** [comment]
Also see https://github.com/kubernetes/kubernetes/pull/15981

**Comment by paralin** [comment]
@mikedanese I see. How does this relate to kube-up? How can I add these flags with the script? is it by setting the environment variable RUNTIME_CONFIG?

**Comment by nikhiljindal** [comment]
1. We can remove ENABLE_EXPERIMENTAL_API. extensions (the new name of experimental APIs) is enabled by default.
2. If we do not have it already, then we should add an ENABLE_DAEMONSET env var, similar to ENABLE_DEPLOYMENTS, which makes it easy to bring up a cluster with daemonset enabled. @mikedanese ?

@paralin setting RUNTIME_CONFIG env var directly should work as well. Please let us know if you try that and it does not work.

**Comment by paralin** [comment]
This works:

```
export KUBE_RUNTIME_CONFIG="extensions/v1beta1=true,extensions/v1beta1/daemonset=true,extensions/v1beta1/deployments=true"
```

I have not tried just enabling all of them (extensions=v1beta1) alone. 

I'm not sure about specific ENABLE_FEATURE vars. Perhaps you could just document the KUBE_RUNTIME_CONFIG env var a bit better? I know it's mentioned a few places but it took me some effort to figure out how it works. Maybe I'm just bad at reading, I don't know.

If you'd like I can spin a PR to remove the old ENABLE_EXPERIMENTAL_API flags.

**Comment by paralin** [comment]
... actually on testing, I get this error:

```
unable to recognize "my-controller.yaml": no kind named "DaemonSet" is registered in versions ["" "v1"]
```

@mikedanese any ideasS?

**Comment by nikhiljindal** [comment]
@paralin Feel free to send a PR to remove ENABLE_EXPERIMENTAL_API. Happy to review!

**Comment by paralin** [comment]
Changes in the PR (will copy there too):

 - `enable_experimental_api` in salt is not used anywhere. Removed.
 - `ENABLE_DEPLOYMENTS` and similar removed in favor of `KUBE_RUNTIME_CONFIG="extensions/v1beta1/deployments=true"`
 - Update e2e scripts

**Comment by paralin** [comment]
This should be OK @nikhiljindal if in HEAD the experimental will be enabled on default. `ENABLE_DEPLOYMENTS` before just enabled `ENABLE_EXPERIMENTAL`. I was going to make a change to have it enable the feature in the RUNTIME_CONFIG vars, but this is unnecessary if it's enabled on default.

**Comment by paralin** [comment]
@nikhiljindal Can this be closed now that the newer doc improvements around this have been merged?

**Comment by paralin** [comment]
I'm pretty sure this is being addressed elsewhere, closing. That said the PR to remove ENABLE_EXPERIMENTAL_API is still pending.
