### ISSUE TITLE
Fine grained control of RC pod allocation

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#15970]
I am not sure what the best way of doing this with kubectl but it would be nice to have more fine grained control of which replicas you want to take out.  IE you have a problem with a pod running on one particular computer and you'd like yo reduce the number of replicas that's RC has... but in the process you want the pod eliminated to be the one on the node you really need it off of.

Yes we can use `unschedule:true` but that would remove all pods from that node.

The use case is for debugging problems with certain nodes running certain loads

**Comment by jlowdermilk** [comment]
You can accomplish this using node labels and a [nodeSelector](http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_podspec) on the pod spec, but if you don't mind, please repost your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes), so both it (and the answer) are easier to find.
