### ISSUE TITLE
Job: need parallel task-queue example

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#15982]
We need a concrete example of how to write a parallel job that uses a task-queue.

One aspect is setting up a task queue.  We could use rabbitmq, e.g from examples/celery-rabbitmq/rabbitmq-controller.yaml.   Or do an example on GKE/GCE that uses [GCP task queue](https://cloud.google.com/appengine/docs/python/taskqueue/rest/).

Another aspect is getting a list of tasks (e.g. files to process, parameters to simulate, images to build, etc) into a task queue.  The task queue should be populated before Job is created, or else there is a race where Pods might see an empty queue and think they should terminate.  

A third aspect of is what Pods do when they are running.
Presumably, a Pod sits in a loop where it:

- tries to lease a task from the task queue
- works on task
- deletes task
- repeat

A fourth aspect is how pods exit and how this affects completion of the job. 
I think pods need to exit when there are no remaining tasks.  If all tasks
are currently leased, the task should not exit with success, but rather sleep and recheck.  Otherwise,
there could be a race as follows:

1. pod1 and pod2 each lease 1 task.
1. pod1 completes its task, deletes it, and exits with success. 
1. Job counts 1 completion is done.
1. pod2 completes its task, but then crashes before deleting it, but with lots of time left on lease.
1. pod3 started by Job to replace pod2.  
1. pod3 sees all tasks still leased (one task still leased to pod2), so exits with success
1. Job counts second completion, and so Job exits with success.
1. A task is not completed, yet the Job is done. Boo.

A fifth aspect is how scaling works.  Couple issues there:
  
If you try to increase parallelism greater than completions, then the controller currently won't start extra pods.  This means you need to set completion to the highest level of parallelism you might need (which is wierd, but should work okay -- you'll just have a bunch of pods that start, see an empty task queue, and then exit with success).  

If you try to decrease parallelism while it is running, pod will be terminated.  This needs to be unsuccessful termination if there are still incomplete tasks in the task queue.

**Comment by erictune** [comment]
@mikedanese @soltysh FYI

**Comment by bgrant0607** [comment]
Sort of related (I think it can execute tasks in parallel):

It might be useful to add Job/K8s support to Luigi, a workflow / batch DAG system:
https://github.com/spotify/luigi/tree/master/luigi/contrib

**Comment by erictune** [comment]
Detecting whether a queue is empty (including unacknowledged items) is not supported by several AMQP libraries I looked at (for example Pika 0.10.0).

So another approach is to put an "EOF" message as the last thing in the queue, and for workers to detect this message and exit with success.  The trick is that there could be any number of workers, and so you don't want them to consume the message, or else you would need an unknown number of EOFs at the end of the queue.  So, the workers will need to not ACK the EOF message.

Working on an example that uses the EOF approach.

**Comment by erictune** [comment]
Out for review: https://github.com/kubernetes/kubernetes/pull/17345

**Comment by yaakov2** [comment]
@erictune : The proposed EOF approach can fail easily:  If the worker that processes the last "real" message fails, then the queue will retry this message **after** the EOF messages.  This means that the cluster will think the work is done, while there is still outstanding work.
