### ISSUE TITLE
Ingress: requirements for graduating to v1

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#15990]
- have a plan of how users would upgrade from a user-started ingress controller to an addons-started ingress controller.  Discuss this with GKE, in terms of their upgrade flow.

**Comment by erictune** [comment]
@thockin @bprashanth we talked about this yesterday

**Comment by bprashanth** [comment]
I plan to circle back when the dust around Tim's current proposal for handling Ingress and other resources like it has settled

**Comment by cmluciano** [comment]
Is this still relevant?

**Comment by cmluciano** [comment]
cc @bowei @nicksardo Do we have other issues that supplant this one?
