### ISSUE TITLE
Add an option to create an autoscaler for kubectl run

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#15991]
As mentioned in Horizontal Pod Autoscaling proposal: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/horizontal-pod-autoscaler.md#support-in-kubectl

Ref https://github.com/kubernetes/kubernetes/issues/15723#issuecomment-148751845

cc @bgrant0607 @fgrzadkowski @jszczepkowski @mwielgus

**Comment by bgrant0607** [comment]
Let's not do this for 1.1.

For 1.2, --expose is more important #14952

**Comment by spzala** [comment]
@janetkuo hi, this issue is more than a year old and we are at 1.6 release now. Can you please verify if can close it and if so can you please close it? thanks!!

**Comment by mwielgus** [comment]
There is kubectl autoscale. I guess there is no need to clutter kubectl run with it.

**Comment by spzala** [comment]
Thanks @mwielgus !!
