### ISSUE TITLE
When increase cpu load HorizontalPodAutoscaler can't auto scale pod

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#16018]
```
Description of problem:
When increase cpu load, the pod can't auto scale, hpa can't works as expect.

Version-Release number of selected component (if applicable):
[root@ip-172-18-12-2 horizontal-pod-autoscaling]# kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.2.90+360d0e0a7e92dc", GitCommit:"360d0e0a7e92dcc4d00b4c555e166a2a71a7e713", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.2.90+360d0e0a7e92dc", GitCommit:"360d0e0a7e92dcc4d00b4c555e166a2a71a7e713", GitTreeState:"clean"}

How reproducible:
Always.

Steps to Reproduce:
1. Enable experimental for kube-apiserver
1). For "kube-apiserver"  add  --runtime-config=extensions/v1beta1=true

2. Run & expose php-apache server
$ kubectl create -f rc-php-apache.yaml
$ kubectl expose rc php-apache --port=80
$ kubectl get pods
$ kubectl get svc
$ curl http://$php-server-ip

3. Create horizontal pod autoscaler
$ kubectl create -f hpa-php-apache.yaml
$ kubectl get hpa

4. Increase cpu load and check rc
$ while true; do curl http://$svcip:port; done
$ kubectl get hpa
$ kubectl get rc
$ kubectl get pod

Actual results:
4. When increase cpu load, the pod can't auto scale.
[root@ip-172-18-12-2 kubernetes]# kubectl get rc
CONTROLLER   CONTAINER(S)   IMAGE(S)                            SELECTOR         REPLICAS   AGE
php-apache   php-apache     horizontal-pod-autoscaling:latest   run=php-apache   1          58m
[root@ip-172-18-12-2 kubernetes]# kubectl get hpa
NAME         REFERENCE                                   TARGET    CURRENT     MINPODS   MAXPODS   AGE
php-apache   ReplicationController/default/php-apache/   1%        <waiting>   1         10        46m
[root@ip-172-18-12-2 kubernetes]# kubectl get pod
NAME               READY     STATUS    RESTARTS   AGE
php-apache-wuwzo   1/1       Running   0          58m

Expected results:
4. When increase cpu load, the pod should auto scale.

Additional info:
1.$ cat hpa-php-apache.yaml
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleRef:
    kind: ReplicationController
    name: php-apache
    namespace: default
  cpuUtilization:
    targetPercentage: 1
2.$ cat rc-php-apache.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: php-apache
  name: php-apache
  namespace: default
spec:
  replicas: 1
  selector:
    run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - image: horizontal-pod-autoscaling:latest
        imagePullPolicy: IfNotPresent
        name: php-apache
        resources:
          requests:
            cpu: 200m
      restartPolicy: Always
3. Image "horizontal-pod-autoscaling:latest" is build from 
https://github.com/kubernetes/kubernetes/tree/master/examples/extensions/horizontal-pod-autoscaling/image
4. The php-apache cpu usage can refer:
 http://fpaste.org/281762/44541276/
```

**Comment by mdshuai** [comment]
@derekwaynecarr

**Comment by gmarek** [comment]
@piosz @jszczepkowski @mwielgus

**Comment by piosz** [comment]
@mdshuai thanks for reporting. I'll take a look

**Comment by piosz** [comment]
@mdshuai could you please paste logs from controller manager (sth like /var/log/kube-controller-manager.log). Also could you please verify that heapster is running correctly by running ```kubectl get pods --namespace=kube-system -l k8s-app=heapster```.

**Comment by jszczepkowski** [comment]
Output of `kubectl get hpa` in step 4 says `CURRET <waiting>`. It means that the metrics from heapster were not collected yet.
@mdshuai who long did you wait before step 4? You should wait about 4 minutes due to https://github.com/kubernetes/heapster/issues/642

**Comment by DirectXMan12** [comment]
@mdshuai I'd also reccomend double checking the controller-manager logs to make sure that the controller-manager is actually able to talk to heapster.

If you want to confirm whether or not there are actually metrics present, you can talk to heapster using cURL.  For example:

```base
$ curl http://$YOUR_HEAPSTER_SERVICE_IP/api/v1/model/namespaces/default/pods/php-apache-wuwzo/metrics/cpu-usage | gunzip
```

**Comment by mdshuai** [comment]
@piosz @jszczepkowski  @DirectXMan12 
```
[root@ip-172-18-13-51 kubernetes]# kubectl get pods --namespace=kube-system -l k8s-app=heapster
NAME                 READY     STATUS    RESTARTS   AGE
heapster-v10-nzia1   1/1       Running   0          24m
[root@ip-172-18-13-51 kubernetes]# kubectl get svc --namespace=kube-system
NAME       CLUSTER_IP   EXTERNAL_IP   PORT(S)   SELECTOR           AGE
heapster   10.0.0.83    <none>        80/TCP    k8s-app=heapster   24m
[root@ip-172-18-13-51 kubernetes]# kubectl get pod
NAME               READY     STATUS    RESTARTS   AGE
php-apache-tmdi6   1/1       Running   0          24m
[root@ip-172-18-13-51 kubernetes]# kubectl get hpa
NAME         REFERENCE                                   TARGET    CURRENT     MINPODS   MAXPODS   AGE
php-apache   ReplicationController/default/php-apache/   1%        <waiting>   1         10        24m
[root@ip-172-18-13-51 kubernetes]# curl http://10.0.0.83:80/api/v1/model/namespaces/default/pods/php-apache-tmdi6/metrics/cpu-usage | gunzip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    69  100    69    0     0   8307      0 --:--:-- --:--:-- --:--:--  9857
the requested entity does not have any metrics yet
```
1. My env is local, the heapster is created from: cluster/addons/cluster-monitoring/standalone/heapster-controller.yaml

2. The hpa CURRENT always <waiting>, I have wait more than 5m. It seem that in kube-controller-manager.log  the metrics is empty and can't get pod cpu usage.

3. kube-controller-manager.log :  http://pastebin.test.redhat.com/321734

**Comment by piosz** [comment]
So the problem is with missing metrics. Which version of the Heapster do you use? 0.18.2? Could you please provide logs from the Heapster?

Did you configured source correctly in Heapster? I'm not sure how to do it in local environment. @vishh any thoughts?

**Comment by mdshuai** [comment]
@piosz  The version is v0.18.2. I don't configure heapster. just using the yaml file directly. https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/standalone/heapster-controller.yaml
How to Heapster configure for local kube env ?
```
[root@ip-172-18-13-51 kubernetes]# docker logs de265d96f908
I1022 08:03:30.201885       1 heapster.go:55] /heapster --source=kubernetes:''
I1022 08:03:30.202009       1 heapster.go:56] Heapster version 0.18.2
I1022 08:03:30.202781       1 kube_factory.go:169] Using Kubernetes client with master "https://10.0.0.1:443" and version "v1"
I1022 08:03:30.202798       1 kube_factory.go:170] Using kubelet port 10255
I1022 08:03:30.210944       1 heapster.go:66] Starting heapster on port 8082
E1022 08:04:19.080921       1 model_handlers.go:647] unable to get pod list metric: the model is not populated yet
E1022 08:04:49.088169       1 model_handlers.go:647] unable to get pod list metric: the model is not populated yet
E1022 08:05:19.095401       1 model_handlers.go:647] unable to get pod list metric: the model is not populated yet
E1022 08:05:49.101959       1 model_handlers.go:647] unable to get pod list metric: the model is not populated yet
```

**Comment by piosz** [comment]
Could you please run Heapster with more verbose logging (see [debugging.md](https://github.com/kubernetes/heapster/blob/master/docs/debugging.md#extra-logging)).

**Comment by vishh** [comment]
@mdshuai: The configs you used should work as-is. Ther errors in the logs are benign. (As a side note, @piosz we should consider suppressing those model update errors)
Can you run heapster with an additional command? Add `- --vmodule=*=4` to the command section. This should make heapster spit out additional debugging logs.

**Comment by mdshuai** [comment]
@piosz @vishh 
Heapster detail log http://pastebin.test.redhat.com/322035

**Comment by DirectXMan12** [comment]
> failed to get stats from kubelet url: http://127.0.0.1:10255/stats/kube-system/heapster-v10-apbhf/fa70b1d6-792b-11e5-b2af-0ec5552c9915/heapster - Get http://127.0.0.1:10255/stats/kube-system/heapster-v10-apbhf/fa70b1d6-792b-11e5-b2af-0ec5552c9915/heapster: dial tcp 127.0.0.1:10255: connection refused

Do you have the read-only port enabled on the kubelet?

**Comment by mdshuai** [comment]
@DirectXMan12 port 10255 should be enabled as default when run hack/local-up-cluster.sh
kubelet listen on local host 127.0.0.1:10255
Heapster run in container, connect to 127.0.0.1:10255 is container inner ip not host ,Is the problem? Thanks

**Comment by DirectXMan12** [comment]
@mdshuai yeah, that could be it.  Try editing the heapster config to actually specify the kube IP instead of just relying on the default.

**Comment by mdshuai** [comment]
Thanks all the help, I have resolve the problem, it can autoscale correctly. But it seem that, the autoscale isn't stable. anyway close this issue.

**Comment by jszczepkowski** [comment]
> Thanks all the help, I have resolve the problem, it can autoscale correctly. But it seem that, the autoscale isn't stable. anyway close this issue.

@mdshuai Can you explain what caused the problem and how it was solved? Someone may encounter it  in future.

**Comment by mdshuai** [comment]
For my env is local all-in-one. I setup the env just run command "hack/local-up-cluster.sh". Then create heapster by json "cluster/addons/cluster-monitoring/standalone/heapster-controller.yaml" and hpa. Because kubelet listen on localhost 127.0.0.1 and heapster in container connect to 127.0.0.1, it will never connect to the master.
At first, I don't know how hpa works with heapster. Honestly after read the code, I know hpa get heapster from "kube-system" namesapce, it's hard code and no doc describe this. So I make this mistake. I resolve this problem by create heapster in correctly namespace, change kube default listen ip,  configure it in heapster yaml with "- --source=kubernetes:'http://$kube-apiserver' ".
