### ISSUE TITLE
High availability issue with rethinkdb cluster in kubernetes

### ISSUE THREAD

**Issue by ntquyen** [kubernetes/kubernetes#16022]
I'm setting up rethinkdb cluster inside kubernetes, but it doesn't work as expected for high availability  requirement. Because when a pod is down, kubernetes will creates another pod, which runs another container of the same image, old mounted data will be erased and the new pod will join the cluster as a brand new instance. I'm running k8s in CoreOS v773.1.0 stable.

Please correct me if i'm wrong, but that way it seems impossible to setup a database cluster inside k8s.

Update: As documented here http://kubernetes.io/v1.0/docs/user-guide/pod-states.html#restartpolicy, if `RestartPolicy: Always` it will restart the container if exits failure. It means by "restart" that it brings up the same container, or create another one? Or maybe because I stop the pod via command `kubectl stop po` so it doesn't restart the same container?

**Comment by jlowdermilk** [comment]
I'm not familiar with rethinkdb's architectural details, but it should be possible to set up a highly available cluster using persistent volumes and persistent volume claims (see [this doc](http://kubernetes.io/v1.0/docs/user-guide/persistent-volumes.html)). The idea is that you have storage objects (persistent volumes) that are long lived, and pods attach to and use them. The pods can then be deleted/recreated without destroying the volume. You'll also need to configure rethinkdb to put its data directory in the volume mounted into the container. @markturansky might be interested in this use case.

**Comment by ntquyen** [comment]
Deleting data in mounted folder may be the way rethinkdb instance does to initialize a clean directory. However, I'm not 100% sure whether the data is deleted or not, I just read from the rethinkdb console log about initilizing metadata and tmp directory as it starts. When the newly instance is up, it has new server name, new server id. So it mean that, whether or not the old data is deleted, it can not be accessed anymore...

**Comment by markturansky** [comment]
> When the new instance is up, it has new server name, new server id. So it mean that, whether or not the old data is deleted, it can not be accessed anymore

Is rethinkdb a "nominal service" per the discussion in #260?

That issue is about identity, naming, etc. in a clustered service.  Some of those problems are not solved yet.

**Comment by ntquyen** [comment]
Yes, The problem on varied hostname might be the problem why we cannot use rethinkdb cluster in kube.

**Comment by ntquyen** [comment]
I found out the cause. I realized that I used the same persistentVolume for every nodes in cluster which is wrong even they are scheduled on different nodes. Is that the behavior of k8s persistent Volume, specifically HostPath? However, I don't think it should be that way.

**Comment by markturansky** [comment]
HostPath is not in any way supported in production as a Persistent Volume.  It was created for development and testing only.  There is no local storage in Kube at this time that is supported.

**Comment by ntquyen** [comment]
The problem of using HostPath is that "There is no guarantee your pod ends up on the correct node where the HostPath resides." according to this docs https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/persistent-volumes
However, I think I can use `label` on specific node to make sure of that, isn't that right?

**Comment by markturansky** [comment]
Couple of things...

1. Are you using a ReplicationController for your pods?  That explains why each has the same PV.
2. NodeSelectors on pods can probably work for approximately local storage using HostPath PV, but that turns your nodes into pets instead of treating them (and the pods) like cattle.

The intent of HostPath as a PV was development and testing only.  So, while what you are doing may work and suit your needs, it is an unsupported use case at this time and that is not likely to change for the foreseeable future.

**Comment by davidopp** [comment]
@kubernetes/sig-big-data

**Comment by zmerlynn** [comment]
@ntquyen: Yeah, unfortunately right now, there's a little bit of a wart around storage here. As @markturansky is suggesting, we'd highly recommend you not use `HostPath` and node selectors to pin the pods - that results in a brittle system and basically ruins the schedulers ability to do anything. There are plans in the works for something like a `PVClaim` pool that is more reasonable to tie to an RC, but right now there's no way to tie a dedicated volume to each pod in the replication controller for replication controllers of greater than size 1. (Please correct me, @markturansky, if I say something dumb here. :))

One way to continue is to make a replication controller for each "thing" that needs an identity, though, with exactly one `replica` and give that a unique volume, i.e. `rc-1` has one pod and gets `volume-1`, `rc-2` has one pod and gets `volume-2`, etc. You can script this relatively easily for `N`. It's not my favorite pattern in the world, but it gets the job done.

**Comment by timothysc** [comment]
@davidopp @zmerlynn at some point we are going to need to support persistent local storage via "forgiveness", but I've seen no "complete" design proposals on the topic.

**Comment by ntquyen** [comment]
@zmerlynn and @markturansky  I know that using `HostPath` and local persistent storage will limit the power of Kubernetes and have considered to switch to other volume plugin. But I also concern about the performance of network storage like ISCSI or GCEPersistentStorage, are they recommended to be used for database engine like rethinkdb, which requires high IOPS?

Besides, I'm using self-hosted CoreOS so I cannot use most of the supported volume plugin. And I don't know how to install one (such as this issue https://github.com/kubernetes/kubernetes/issues/16585#issuecomment-153928223). So for static files storage, I end up using NFS in my CoreOS nodes but outside Kubernetes. From the pods, I keep using `HostPath` but mount to the NFS folder.

**Comment by kargakis** [comment]
@kubernetes/sig-storage-misc

**Comment by msau42** [comment]
This issue is a bit old.  Now, we have StatefulSets, which gives one PVC per instance.

And local storage roadmap and implementation tracker is available at #43640

**Comment by kargakis** [comment]
@msau42 thanks, closing in favor of #43640
