### ISSUE TITLE
kube-up 0 ready nodes

### ISSUE THREAD

**Issue by chipironcin** [kubernetes/kubernetes#16021]
Calling `export KUBERNETES_PROVIDER=gce; wget -q -O - https://get.k8s.io | bash` to setup a cluster in gce, stuck "waiting for nodes" at "validate-cluster". Finish with an error but cluster has been successfully initialized and nodes are ready.

Reproducing issue:

```
bash-4.3$ export KUBERNETES_PROVIDER=gce; wget -q -O - https://get.k8s.io | bash
[...]
... calling kube-up
Project: ************
Zone: us-central1-b
[...]
Group is stable
MINION_NAMES=kubernetes-minion-5y0u kubernetes-minion-jiic kubernetes-minion-n3mn kubernetes-minion-ob68
Using master: kubernetes-master (external IP: ************)
Waiting for cluster initialization.
[...]
Kubernetes cluster created.
[...]
Kubernetes cluster is running.  The master is running at:

  https://************

The user name and password to use is located in /home/ubuntu/.kube/config.

... calling validate-cluster
Waiting for 4 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 4 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 4 ready nodes. 0 ready nodes, 4 registered. Retrying.
Waiting for 4 ready nodes. 0 ready nodes, 4 registered. Retrying.
Waiting for 4 ready nodes. 0 ready nodes, 4 registered. Retrying.
[...]
Detected 0 ready nodes, found 4 nodes out of expected 4. Your cluster may not be working.
     1	NAME                     LABELS                                          STATUS    AGE
     2	kubernetes-minion-5y0u   kubernetes.io/hostname=kubernetes-minion-5y0u   Ready     10m
     3	kubernetes-minion-jiic   kubernetes.io/hostname=kubernetes-minion-jiic   Ready     10m
     4	kubernetes-minion-n3mn   kubernetes.io/hostname=kubernetes-minion-n3mn   Ready     10m
     5	kubernetes-minion-ob68   kubernetes.io/hostname=kubernetes-minion-ob68   Ready     10m
[...]

bash-4.3$ kubectl get nodes

NAME                     LABELS                                          STATUS
kubernetes-minion-5y0u   kubernetes.io/hostname=kubernetes-minion-5y0u   Ready
kubernetes-minion-jiic   kubernetes.io/hostname=kubernetes-minion-jiic   Ready
kubernetes-minion-n3mn   kubernetes.io/hostname=kubernetes-minion-n3mn   Ready
kubernetes-minion-ob68   kubernetes.io/hostname=kubernetes-minion-ob68   Ready


bash-4.3$ kubectl cluster-info

Kubernetes master is running at https://************
KubeDNS is running at https://************/api/v1/proxy/namespaces/kube-system/services/kube-dns
KubeUI is running at https://************/api/v1/proxy/namespaces/kube-system/services/kube-ui
Grafana is running at https://************/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
Heapster is running at https://************/api/v1/proxy/namespaces/kube-system/services/monitoring-heapster
InfluxDB is running at https://************/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

```

**Comment by davidopp** [comment]
Unfortunately it looks like we didn't get to this in time to do anything useful with it. If it recurs or you happen to still have logs from this run, please re-open the issue.

**Comment by chetankmalur** [comment]
I am running into the same issue

curl -sS https://get.k8s.io | bash

Waiting for 4 ready nodes. 1 ready nodes, 1 registered. Retrying.
Waiting for 4 ready nodes. 1 ready nodes, 1 registered. Retrying.
Detected 1 ready nodes, found 1 nodes out of expected 4. Your cluster may not be fully functional.
NAME                STATUS                     AGE
kubernetes-master   Ready,SchedulingDisabled   35m


==== START logs for kube-system/etcd-server-events-kubernetes-master ====                                                          [104/1968]
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log et
cd-server-events-kubernetes-master)","reason":"NotFound","details":{"name":"etcd-server-events-kubernetes-master","kind":"pods/log"},"code":$
04}
==== END logs for kube-system/etcd-server-events-kubernetes-master ====
==== START logs for kube-system/etcd-server-kubernetes-master ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log e$
cd-server-kubernetes-master)","reason":"NotFound","details":{"name":"etcd-server-kubernetes-master","kind":"pods/log"},"code":404}
==== END logs for kube-system/etcd-server-kubernetes-master ====
==== START logs for kube-system/fluentd-cloud-logging-kubernetes-master ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log f$
uentd-cloud-logging-kubernetes-master)","reason":"NotFound","details":{"name":"fluentd-cloud-logging-kubernetes-master","kind":"pods/log"},"$
ode":404}
==== END logs for kube-system/fluentd-cloud-logging-kubernetes-master ====
==== START logs for kube-system/heapster-v1.1.0-1922731500-cgyqm ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod heapster-v1.1.0-19$
2731500-cgyqm, choose one of: [heapster eventer heapster-nanny eventer-nanny]","reason":"BadRequest","code":400}
==== END logs for kube-system/heapster-v1.1.0-1922731500-cgyqm ====
==== START logs for kube-system/kube-addon-manager-kubernetes-master ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log k$
be-addon-manager-kubernetes-master)","reason":"NotFound","details":{"name":"kube-addon-manager-kubernetes-master","kind":"pods/log"},"code":4
04}
==== END logs for kube-system/kube-addon-manager-kubernetes-master ====
==== START logs for kube-system/kube-apiserver-kubernetes-master ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log ku
be-apiserver-kubernetes-master)","reason":"NotFound","details":{"name":"kube-apiserver-kubernetes-master","kind":"pods/log"},"code":404}
==== END logs for kube-system/kube-apiserver-kubernetes-master ====
==== START logs for kube-system/kube-controller-manager-kubernetes-master ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log ku
be-controller-manager-kubernetes-master)","reason":"NotFound","details":{"name":"kube-controller-manager-kubernetes-master","kind":"pods/log"
},"code":404}
==== END logs for kube-system/kube-controller-manager-kubernetes-master ====
==== START logs for kube-system/kube-dns-v17-hgti5 ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod kube-dns-v17-hgti5,
 choose one of: [kubedns dnsmasq healthz]","reason":"BadRequest","code":400}
==== END logs for kube-system/kube-dns-v17-hgti5 ====
==== START logs for kube-system/kube-scheduler-kubernetes-master ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log ku
be-scheduler-kubernetes-master)","reason":"NotFound","details":{"name":"kube-scheduler-kubernetes-master","kind":"pods/log"},"code":404}
==== END logs for kube-system/kube-scheduler-kubernetes-master ====
==== START logs for kube-system/kubernetes-dashboard-v1.1.0-yyuzr ====
==== END logs for kube-system/kubernetes-dashboard-v1.1.0-yyuzr ====
==== START logs for kube-system/l7-default-backend-v1.0-pzegm ====
==== END logs for kube-system/l7-default-backend-v1.0-pzegm ====
==== START logs for kube-system/l7-lb-controller-v0.7.0-kubernetes-master ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log l7
-lb-controller-v0.7.0-kubernetes-master)","reason":"NotFound","details":{"name":"l7-lb-controller-v0.7.0-kubernetes-master","kind":"pods/log"
},"code":404}
==== END logs for kube-system/l7-lb-controller-v0.7.0-kubernetes-master ====
==== START logs for kube-system/monitoring-influxdb-grafana-v3-rq53k ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod monitoring-influxdb
-grafana-v3-rq53k, choose one of: [influxdb grafana]","reason":"BadRequest","code":400}
==== END logs for kube-system/monitoring-influxdb-grafana-v3-rq53k ====
==== START logs for kube-system/node-problem-detector-v0.1-85v45 ====
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log no
de-problem-detector-v0.1-85v45)","reason":"NotFound","details":{"name":"node-problem-detector-v0.1-85v45","kind":"pods/log"},"code":404}
==== END logs for kube-system/node-problem-detector-v0.1-85v45 ====

kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/386"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:19:19Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

kubectl get pods --namespace=kube-system
NAME                                        READY     STATUS    RESTARTS   AGE
etcd-server-events-kubernetes-master        1/1       Running   0          3h
etcd-server-kubernetes-master               1/1       Running   0          3h
fluentd-cloud-logging-kubernetes-master     1/1       Running   0          3h
heapster-v1.1.0-1922731500-cgyqm            0/4       Pending   0          3h
kube-addon-manager-kubernetes-master        1/1       Running   0          3h
kube-apiserver-kubernetes-master            1/1       Running   1          3h
kube-controller-manager-kubernetes-master   1/1       Running   0          3h
kube-dns-v17-hgti5                          0/3       Pending   0          3h
kube-scheduler-kubernetes-master            1/1       Running   0          3h
kubernetes-dashboard-v1.1.0-yyuzr           0/1       Pending   0          3h
l7-default-backend-v1.0-pzegm               0/1       Pending   0          3h
l7-lb-controller-v0.7.0-kubernetes-master   1/1       Running   0          3h
monitoring-influxdb-grafana-v3-rq53k        0/2       Pending   0          3h
node-problem-detector-v0.1-85v45            1/1       Running   0          3h

**Comment by davidopp** [comment]
@mikedanese
