### ISSUE TITLE
Revert kubectl slash syntax 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#16039]
- [x] Revert #14461 in PR #16054
- [x] Revert parts of #15808 in PR #16058

Ref https://github.com/kubernetes/kubernetes/pull/15874#issuecomment-149756822 

Revert the slash syntax since we don't need to require `extensions/` for 1.1, and take our time on introducing new syntax in 1.2.

**Comment by bgrant0607** [comment]
cc @smarterclayton

**Comment by bgrant0607** [comment]
Waiting on cherrypick of #16054

**Comment by liggitt** [comment]
c.f. #13929
