### ISSUE TITLE
"kubectl get" shows deleted entries

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/kubernetes#16046]
I deleted a service account, but "kubectl get" still shows that it exists. Trying to delete again the service account results in an error:

    [root@dns-test-09 ~]# kubectl get serviceAccounts  --all-namespaces
    NAMESPACE   NAME       SECRETS
    default     default    0
    optymyze    default    0
    optymyze    optymyze   0
    [root@dns-test-09 ~]# kubectl delete serviceAccounts/optymyze
    Error from server: serviceaccounts "optymyze" not found

Versions installed:

    # rpm -qa | grep kube | sort
    kubernetes-client-1.0.3-0.1.gitb9a88a7.el7.x86_64
    kubernetes-master-1.0.3-0.1.gitb9a88a7.el7.x86_64
    kubernetes-node-1.0.3-0.1.gitb9a88a7.el7.x86_64

**Comment by jlowdermilk** [comment]
cc @erictune

**Comment by erictune** [comment]
Does this work: `kubectl delete --namespace optymyze serviceAccounts/optymyze`

**Comment by cristifalcas** [comment]
I can't reproduce this anymore :). Magic works.

If I will encounter the error again I will come with more data.

Thank you
