### ISSUE TITLE
Feature Request: Change AWS ELB scheme 

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/kubernetes#16047]
Currently it appears service based ELBs come up as internet facing only.  In many cases internal services shouldn't be exposed externally (internal testing?).  There's clearly a number of ways to do this but making ELBs internal is one simple way we've used previously (unless there's a specific reason this is not present).  

It seems like a pretty simple add (passing a `Scheme:` argument when creating an ELB) but I was curious on what others thought since I know Kubernetes is trying to keep load balancer config very simple across different cloud providers.

Thanks!

**Comment by thockin** [comment]
I think "internal" LB is something we should support but it's more than
just a flag.  I'd like to move the evolution of load-balancing towards the
new Ingress model over the next few releases, so this might be better there
(but it's beta for now).

**Comment by kha0S** [comment]
Any development on this?

**Comment by jorgegilmoreira** [comment]
+1

**Comment by mikesplain** [comment]
If it's any help to others, in the meantime I've setup an ingress controller, put it on a node port, and utilized that for internal load balancing https://github.com/kubernetes/contrib/tree/master/Ingress/controllers.  It's definitely a bit faster than spinning up a whole ELB, which is awesome, but it does require some external config in order to actually setup the internal ELB, and open security group for a node port for the ingress service.

**Comment by nunoh** [comment]
+1 for this too

**Comment by yissachar** [comment]
You can do this with a [beta annotation](https://github.com/kubernetes/kubernetes/issues/17620#issuecomment-212508777):

```
kind: Service
apiVersion: v1
metadata:
    name: someService
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```

**Comment by nicolasbelanger** [comment]
+1

**Comment by dberuben** [comment]
+1 for this

**Comment by katcipis** [comment]
+1

**Comment by Cocotton** [comment]
+1

**Comment by justinsb** [comment]
I believe this is implemented: https://github.com/kubernetes/kubernetes/issues/16047#issuecomment-239551868

Is there anything left to do, or can we close?

**Comment by mikesplain** [comment]
Nope all good now thanks!
