### ISSUE TITLE
Add monitoring and alert thresholds for cluster addon pods to scalability test

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#16050]
Heapster is the most important one, but we should do it for all of them.

@wojtek-t @gmarek 

ref/ #15716

**Comment by gmarek** [comment]
IIUC you mean memory consumption thresholds. Right?

**Comment by davidopp** [comment]
Yes, sorry, that would be the main thing we care about.

**Comment by wojtek-t** [comment]
@davidopp - you meant the threshold for usage, right?

**Comment by davidopp** [comment]
Yes

**Comment by wojtek-t** [comment]
I guess it's still not closed, because we don't have any alerting yet.

**Comment by gmarek** [comment]
It's done by #17942 and tweaked by a number of following PRs. @davidopp - can we close this issue?
