### ISSUE TITLE
kube-proxy never recovers if the nofiles limit is hit

### ISSUE THREAD

**Issue by sethp-jive** [kubernetes/kubernetes#16079]
This issue has been [discussed](13709) [before](5461) and the [current behavior](https://github.com/kubernetes/kubernetes/commit/4b299476521d80c7e071d5551b22555638d6d7f3) is presently [desired](6716), but I am here to offer my experience and present a novel approach for discussion.
#### Our Experience

DNS resolution across our cluster was failing, despite being able to successfully dig the pod IPs directly and both SkyDNS replicas reporting healthy. The kube-proxy was still up and its iptables rules were in place:

```
$ sudo iptables-save | grep 10.0.0.10
-A KUBE-PORTALS-CONTAINER -d 10.0.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp --dport 53 -j REDIRECT --to-ports 52726
-A KUBE-PORTALS-CONTAINER -d 10.0.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp --dport 53 -j REDIRECT --to-ports 60214
-A KUBE-PORTALS-HOST -d 10.0.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp --dport 53 -j DNAT --to-destination 172.20.0.130:52726
-A KUBE-PORTALS-HOST -d 10.0.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp --dport 53 -j DNAT --to-destination 172.20.0.130:60214
```

But lo, there was no reachability:

```
$ dig @localhost -p 52726 foobar
; <<>> DiG 9.10.2-P2 <<>> @localhost -p 52726 foobar
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

and yet, DNS-over-TCP worked fine:

```
$ dig +tcp @localhost -p 60214 foobar
; <<>> DiG 9.10.2-P2 <<>> +tcp @localhost -p 60214 foobar
; (1 server found)
;; global options: +cmd
;; Got answer:
;; >>HEADER<< opcode: QUERY, status: SERVFAIL, id: 21264
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;foobar.    IN  A
;; Query time: 0 msec
;; SERVER: 127.0.0.1#60214(127.0.0.1)
;; WHEN: Mon Oct 12 21:19:31 UTC 2015
;; MSG SIZE rcvd: 24
```

Research in our log aggregator revealed the following message (corresponding with commit 4b2994 linked above):

```
Oct 12 19:23:47 ip-172-20-0-167.us-west-2.compute.internal kube-proxy[3653]: E1012 19:23:47.923261 3653 util.go:69] Recovered from panic: "Dial failed: dial udp 10.244.93.32:53: too many open files" (Dial failed: dial udp 10.244.93.32:53: too many open files)
```

In our case (using the default CoreOS config as of 779.0.0), the nofiles limit is very low (1024), and the issue appeared to be transient in that a restart of the kube-proxy was sufficient to restore service. In my estimation we had a connection burst that had the kube-proxy managing slightly over 1024 concurrent connections, at which point the next unlucky 1025th connection triggered the panic condition and permanently terminated the goproc responsible for proxying traffic on that port.

The issue is exacerbated in that it is difficult to monitor for directly – everything appears to be in place, but there's nothing on the kube-proxy end to pick up the phone. Sending a trace over the cross product of service IPs and nodes seems to be the only way to detect this kind of failure.
#### Possible Solution

It helps a great deal to increase the ulimit ceiling, and I'm happy to see that in v1.1.0 it looks like the kube-proxy [tries to do this for itself](https://github.com/kubernetes/kubernetes/commit/6945cb050caa91dbc16b4fca452061c959b94b11), but the issue of subset of ports ceasing to respond to traffic will still persist (albeit with a much lower incidence rate).

It seems that the panic'ing code was put in place to deal with conditions where the sustained connection load was larger than the number of available filehandles, and the errors from kube-proxy were filling the logs with a degree of noise. Both in our scenario and in sustained high-contention situations, it seems that a better solution would be to offer backpressure to the connecting client by refusing the connection (in the case of TCP) or throttle the rate of upstream datagrams (in the case of UDP). 

The simplest idea I have on hand would be for the kube-proxy to allow the panic of a single proxier goproc to panic the entire process – a failing-and-restarting process is much more visible & easier to debug than a single green thread going quietly missing.

**Comment by mikedanese** [comment]
@kubernetes/goog-cluster

**Comment by thockin** [comment]
It might be possible to delay callers when we can't get backends, but I
think that would be miserable in really low-ulimit situations.  The panic()
is supposed to panic the app - is it not?

The real answer, I hope, is to ditch userspace proxying and instead use the
new iptables proxy mode (beta in kube v1.1, not on by default but easily
enabled).  My plan was to tell anyone who is suffering to try this, and
hopefully get some miles on it.  We've run a lot of tests against it and it
looks solid.

**Comment by sethp-jive** [comment]
> It might be possible to delay callers when we can't get backends, but I
think that would be miserable in really low-ulimit situations.

I don't disagree – to me, there's two issues: the capacity ceiling for the proxy is absurdly low with the default ulimit settings ([which has been addressed](https://github.com/kubernetes/kubernetes/commit/6945cb050caa91dbc16b4fca452061c959b94b11)) and that hitting the ceiling causes a nonobvious failure. A throttle that reports (e.g. by logging) that it's out of filehandles isn't meant to address the underlying capacity issue, merely make the failure more obvious.

> The panic() is supposed to panic the app - is it not?

Indeed not: [there is a util.HandleCrash()](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/userspace/proxier.go#L334) that limits the crash to just the one goproc responsible for that one socket.

> The real answer, I hope, is to ditch userspace proxying and instead use the
new iptables proxy mode (beta in kube v1.1, not on by default but easily
enabled).

Getting out of the userspace proxying game does seem like a good way to not have the entire problem. We're on an ancient version right now (v1.0.1) and we'll definitely give the iptables mode a try when we upgrade, but I would suggest that as long as the userspace proxy is the default this problem might still be worth a (brief) look.

**Comment by thockin** [comment]
On Thu, Oct 22, 2015 at 11:41 AM, sethp-jive <notifications@github.com> wrote:

>> It might be possible to delay callers when we can't get backends, but I
>> think that would be miserable in really low-ulimit situations.
>
> I don't disagree – to me, there's two issues: the capacity ceiling for the proxy is absurdly low with the default ulimit settings (which has been addressed) and that hitting the ceiling causes a nonobvious failure. A throttle that reports (e.g. by logging) that it's out of filehandles isn't meant to address the underlying capacity issue, merely make the failure more obvious.

I also think it would be really hard to implement :)  What if we just
backport the rlimit change to 1.0.x and encourage you to upgrade? :)

> The panic() is supposed to panic the app - is it not?
>
> Indeed not: there is a util.HandleCrash() that limits the crash to just the one goproc responsible for that one socket.

dammit!  How did I miss that.

**Comment by sethp-jive** [comment]
I'm not too worried about us – we don't have a heavily loaded cluster yet, and bumping the ulimit external to the kube-proxy process is fairly straightforward. If that weren't enough, we're anxious to get on v1.1.0 anyway, iptables proxying is just another log on that particular fire.

More the concern is for the hypothetical future user who will find themselves in our spot – propagating the crash to take out the whole kube-proxy process would've definitely helped us track the issue down faster. Is that as simple as just removing the line? I'd be happy to send that PR :)

**Comment by thockin** [comment]
It's more careful than that.  we have general policy of catching panics and
retrying things, but in this case that's totally wrong.  That doesn't mean
it is wrong in every case though, and we can only remove that after careful
consideration...

**Comment by sethp-jive** [comment]
In this case, a "retry" would be very helpful – the issue seems to be that once the socket's goproc pancis, there's nothing that re-associates that listening address with a new receiver (or closes the socket, which would introduce some TCP back-pressure). 

Allowing the whole process to panic would bubble the error up to the level of a potential retrier (systemd configured to Restart Always, in our case), but re-launching the [goproc itself](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/userspace/proxier.go#L335-L340) would be just as useful for us.

**Comment by sethp-jive** [comment]
Ah, just to clarify – when you say "retrying is totally wrong" do you mean that "a retrier is wrong because that would just cause us to keep running up against the filehandle limit"? I think I've been misunderstanding you to say that "a retrier wouldn't be useful at all."

**Comment by thockin** [comment]
That's what I meant, yeah

**Comment by thockin** [comment]
The iptables proxier in kubernetes 1.1 should not have this problem any more.

**Comment by bgrant0607** [comment]
Sounds like this is obsolete.
