### ISSUE TITLE
Node in `NotReady` state forever, (Ubuntu multiple VM)

### ISSUE THREAD

**Issue by wpc009** [kubernetes/kubernetes#16098]
I got the same `NotReady` forever situation. But it seems the reason is different.
First. The `kubelet` fail to listen on port `10250`, after checking the log in `/var/log/upstart/kubelet.log` 

```
Failed to execute Info() call to the Docker client: dial unix /var/run/docker.sock: no such file or directory
```

It seems something wrong with the docker daemon.
`ps aux | grep docker` shows there's no docker daemon running.
Then a `service docker start`, it still can not running.
checking `/var/log/upstart/docker.log`

```
invalid value "" for flag --mtu: strconv.ParseInt: parsing "": invalid syntax
See '/usr/bin/docker daemon --help'.
```

checking `/etc/default/docker`

```
DOCKER_OPTS=" -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock --bip= --mtu="
```

Ok, seems faulty `DOCKER_OPTS`, 
checking  `cluster/ubuntu/reconfDocker.sh#L57` 

```
56   echo DOCKER_OPTS=\"${DOCKER_OPTS} -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock \
57        --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}\" > /etc/default/docker
```

It overrides the `/etc/default/docker` file with a empty `FLANNEL_MTU` variable. 
It seems the `/run/flannel/subnet.env` is not ready.
here is the `/var/log/upstart/flannel.log`

```
E1022 13:47:07.358500 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [40]
E1022 13:47:08.359494 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [41]
E1022 13:47:09.360408 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [41]
E1022 13:47:10.361402 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [41]
E1022 13:47:11.362882 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [41]
E1022 13:47:12.364304 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [41]
E1022 13:47:13.365258 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [41]
E1022 13:47:14.366164 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [42]
E1022 13:47:15.367156 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [43]
E1022 13:47:16.368302 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [43]
E1022 13:47:17.369218 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [43]
E1022 13:47:18.370151 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [44]
E1022 13:47:19.371078 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [44]
E1022 13:47:20.372098 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [44]
E1022 13:47:21.373025 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [44]
E1022 13:47:22.374050 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [44]
E1022 13:47:23.375099 18623 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [44]
```

**Comment by wpc009** [comment]
only the 'ai' node fail to start, the other 'i' nodes are fine.

**Comment by resouer** [comment]
@wpc009 Can you make sure your etcd is running? That's the whole cluster including flannel depends on. cc @dalanlan

**Comment by dalanlan** [comment]
Run `/opt/bin/etcdctl get /coreos.com/network/config` to figure it out whether the key has been set properly (apparently not in this case).

**Comment by dalanlan** [comment]
I dug it up. And there is no obvious reason that current scripts would fail to configure config key for `flannel`, only the potential issue reported about this [`-b`](https://github.com/kubernetes/kubernetes/blob/master/cluster/ubuntu/util.sh#L412). Hope #14912 would work.

**Comment by wpc009** [comment]
The `etcd ` is running. The reason is sometimes this (line)[https://github.com/kubernetes/kubernetes/blob/master/cluster/ubuntu/util.sh#L398]  in provision-masterandnode fail to run on the target host. If I run it manually ,then the `ai` node will up and running.

**Comment by dalanlan** [comment]
Re-run `reconfDocker.sh ai` would work as a plan B.

**Comment by dalanlan** [comment]
@wpc009 Have you recovered from this?

**Comment by wpc009** [comment]
re-run `reconfDocker.sh ai` is a workaround. But still don't know what goes wrong.

**Comment by resouer** [comment]
@wpc009 Since #14912 means to fix re-run reconfDocker.sh things, otherwise, it will be a new bug

**Comment by dalanlan** [comment]
This could be safely closed then. Feel free to reopen it once you hit it again.

**Comment by roberthbailey** [comment]
Closing as per the last comment.
