### ISSUE TITLE
kube-apiserver HTTP proxy removes Content-Length header

### ISSUE THREAD

**Issue by tiran** [kubernetes/kubernetes#16093]
Kubernetes' HTTP proxy removes the headers Content-Length and Transfer-Encoding from proxied requests. This breaks PUT and POST requests that require the Content-Length header and use chunked transfer encoding. I've created a producer for the problem with k8s configuration, Dockerfile and outputs at https://github.com/tiran/k8n-contentlength

In the reproducer example I'm making a curl POST request to a service via the proxy APO endpoint http://localhost:8080/api/v1/proxy/namespaces/default/services/contentlength/. Both curl -v and tcpdump show that curl is sending a Content-Length header. The simple socket server inside the pod gets all data except for the Content-Length header.

**Comment by derekwaynecarr** [comment]
@lavalamp - if i recall, you have a good memory on proxy related problems, is this something that jogs your memory?

**Comment by derekwaynecarr** [comment]
Version information gathered in background discussion:

```
$ rpm -q kubernetes-master
kubernetes-master-1.1.0-0.16.git388061f.fc22.x86_64
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6",
GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6",
GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
```

We would need to test the scenario on head to see if issue is resolved.

**Comment by lavalamp** [comment]
It removes the header because it does rewriting, which changes the length,
but the go response mechanism was supposed to add back a header with the
new length.

The report's a bit unclear, since proxying involves two requests. Which
step of `client -> proxy -> downstream -> proxy -> client` is the header
being removed? I think it should be removed/readded in the last step, but
no other step. OP sounds like it is removed in the `proxy -> downstream`
step, which sounds wrong to me.

...unless the Host field counts towards the length, but then it wouldn't be
*Content*-Length, would it?

**Comment by liggitt** [comment]
it doesn't rewrite content on the way in... I wouldn't expect Content-Length on the request to change

**Comment by tiran** [comment]
The bug occurs on the way in. Both headers are removed in the step proxy -> downstream. The original curl request on the master has both Content-Length and Transfer-Encoding headers. I have verified it with tcpdump on the master. The service (downstream) inside my Kubernetes pod doesn't see the headers.

The problem only occurs when I'm using the apiserver HTTP proxy. With type: NodePort and a port on the node, the PUT request works as expected.

**Comment by tiran** [comment]
I found some code in Go's net/http package that removes Content-Length and Transfer-Encoding.

https://golang.org/src/net/http/request.go#L60
https://golang.org/src/net/http/request.go#L444

 Perhaps you have to copy the fields Request.ContentLength and Request.TransferEncoding from the req to newReq?

https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/proxy.go#L153

**Comment by liggitt** [comment]
we're already copying the entire header map... if go is removing those headers, not sure how we can set them more emphatically than we already are

**Comment by tiran** [comment]
The go request library ignores some fields from the header map. For Content-Length and Transfer-Encoding it sends the value of the request's struct members instead of the fields from the header map. 

https://golang.org/src/net/http/transfer.go#L49
https://golang.org/src/net/http/transfer.go#L170

This small modification to https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/proxy.go#L153 might be enough. I don't have infrastructure to test it now, though:

```
newReq.Header = req.Header
newReq.ContentLength = req.ContentLength
newReq.TransferEncoding = req.TransferEncoding
````

(I'm rather new to Go, so I might be wrong.)

**Comment by lavalamp** [comment]
OK, sounds like a legit bug if we're removing the headers on the way in.

**Comment by lavalamp** [comment]
That fix looks reasonable. @caesarxuchao can you make a PR if you're out of things to do for the 1.1 release?

**Comment by tiran** [comment]
@lavalamp I haven't tested if the fix actually works. It's just a wild guess. :)

**Comment by liggitt** [comment]
we'd need to be super-careful to make sure we were using the same transfer encoding (both gzip or neither gzip) to make sure we don't change the content length

**Comment by liggitt** [comment]
hmm... in fact, we might be broken today if there's a mismatch, since we're copying the request body verbatim without setting transfer encoding

**Comment by lavalamp** [comment]
Yes, I recall this being tricky, I think we might actually re-encode with a
different transfer encoding unless we take steps to defeat the go library.

**Comment by caesarxuchao** [comment]
@tiran, I'm going to test if your proposed fix actually works. Please let me know if you've already done so. Thanks.

**Comment by tiran** [comment]
@caesarxuchao No, I haven't tested it yet. Thanks!

**Comment by caesarxuchao** [comment]
@tiran, I think the patch is valid. I tried the patch on master with your testing image (thanks! it's very easy to use), the output of `kubectl logs contentlength` contains the correct content length.

I'm checking if there is any lurks in the TransferEncoding.

**Comment by liggitt** [comment]
We need to test cases where the client uses transfer encoding of gzip, chunk, and none

**Comment by lavalamp** [comment]
Actually we need to test the cross-product of all those encodings @liggitt
mentioned on the client x same on the downstream server-- it had problems
with this at one point.

**Comment by liggitt** [comment]
> Actually we need to test the cross-product of all those encodings @liggitt
mentioned on the client x same on the downstream server-- it had problems
with this at one point.

+1. If possible, automated tests for those combinations would be best before we do clever things here. It's too easy to break scenarios like that without realizing.

**Comment by caesarxuchao** [comment]
>  I think we might actually re-encode with a different transfer encoding unless we take steps to defeat the go library.

@lavalamp, Is it this line you are talking about? https://golang.org/src/net/http/transport.go?#L1143

**Comment by lavalamp** [comment]
Yes, I think so.

**Comment by lavalamp** [comment]
...Yeah, while talking to @caesarxuchao I realized that the Accept-Encoding is about the downstream server's response, but this issue is about the client's request, so I don't actually think there's a problem here.

But testing the three encodings @liggitt mentioned still sounds like a good idea.
