### ISSUE TITLE
E2e tests fail around "flock" command

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#16096]
Today I've seen multiple e2e failures due to a problem around ```flock``` command in https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh. AFAIU current code will fail (```-n``` flag) if another job is trying to update ```gcloud```. This means that an e2e test will be red until next scheduled run, which can be even 1h later. This blocks submit queue for a long time.

I think we should not use ```-n``` flag.

I'm not sending PR as the comment says only @brendandburns and @jlowdermilk can update this code :/

@wojtek-t @gmarek @davidopp

**Comment by lavalamp** [comment]
Failing is not OK there. It needs to retry. @jlowdermilk @brendandburns please fix!

**Comment by jlowdermilk** [comment]
It uses `-n` to exit because it runs in a subshell. If the command fails it will exit the subshell and skip gcloud update calls, which is the desired result. It was failing last night because the lock file temporarily had the wrong permissions on it, but from e2e history, it looks like all runs are back to green/yellow.

**Comment by jlowdermilk** [comment]
Hmmm. The `-n` in subshell is still triggering failure of parent shell. Whatever magic made it work before is now failing. Working on fix.

**Comment by fgrzadkowski** [comment]
@jlowdermilk The parent script fails because we run with an option that every command should be successful or we exit 1. I think there are two options:
 - don't use ```-n``` flag
 - add ``` || true``` to the subshell command

**Comment by jlowdermilk** [comment]
#16114 removes `-n`, if you want to review. I wanted to make sure it wouldn't cause weird behavior, particularly with local gcloud installs, and I think it's fine.
