### ISSUE TITLE
Improve API documentation of pod subresources

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#16095]
Some API objects about the proxy subresource of pod as follows:
connect DELETE requests to proxy of Pod
`delete /api/v1/namespaces/{namespace}/pods/{name}/proxy/{path:*}`

But I don't know what's the function of the proxy subresource of pod. I tried to search in the doc directory,  but couldn't find them. 
Is there any document about the proxy subresource of pod?

**Comment by bgrant0607** [comment]
Yes, we need better documentation of this part of the API. It's used to implement HTTP proxy functionality, proxying to the specified port on the pod, potentially from outside the network:
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/connecting-to-applications-proxy.md

**Comment by bgrant0607** [comment]
cc @mbohlool

**Comment by spzala** [comment]
@feihujiang hello, can you please verify if this is still an issue? It seems like docs been changed a lot. I see the related doc here, https://kubernetes.io/docs/api-reference/v1.5/#delete-connect-proxy

@bgrant0607 If this is still an issue with doc, I guess we can open it against kubernetes.github.io/issues and close this one? Thanks!!
