### ISSUE TITLE
Allow tagging of nodes by passing labels to kubelet via the command line

### ISSUE THREAD

**Issue by eliaslevy** [kubernetes/kubernetes#16090]
A cluster may be comprised of heterogenous nodes.  To aid targeting of nodes through labels and `nodeSelector` it would be useful if we could pass labels to `kubelet` on the command line that it would apply to the node during self-registration.  Thus, we could tag a node with a instance-type, ami-id, or availability zone.

Alternatively or in addition, the cloud providers should be applying tags to registered notes based on the cloud provider node metadata.

**Comment by roberthbailey** [comment]
We are trying to reduce the amount of command line configuration passed into the kubelet. @mikedanese is working on replacing most of the command line flags with a configuration object instead, so you should connect with him about getting a field added for this.

**Comment by mikedanese** [comment]
Flag based approach proposed in #13524 and we decided it wasn't a good idea. There are plenty of ways to add node labels already. You can do this with a pod during cluster bootstrap (although we should document how).

**Comment by eliaslevy** [comment]
@mikedanese thanks for pointing out the #13524 proposal.  That would fill our needs nicely.  Closing this issue.

**Comment by eliaslevy** [comment]
@mikedanese [This is how](https://github.com/coreos/coreos-kubernetes/pull/125) I ended up implementing it using a [pod](https://github.com/eliaslevy/docker-aws-node-labels).

**Comment by acaire** [comment]
@eliaslevy exactly what I was after, thanks!
