### ISSUE TITLE
e2e.Framework should be private in a separate package to avoid afterEach method not being called

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16094]
Per @ixdy's [comment](https://github.com/kubernetes/kubernetes/pull/16008#issuecomment-149981815) to avoid #16008.

**Comment by ixdy** [comment]
cc @smarterclayton (#16084) and @mfojtik (#12221)

**Comment by smarterclayton** [comment]
Agreed - we're able to reuse most of e2e.Framework but minor things like this trip us up

**Comment by ixdy** [comment]
cc @kubernetes/sig-testing

**Comment by spiffxp** [comment]
what do we think about closing this?  framework has since been moved into its own package, and I no longer see `defer framework.afterEach()` calls littered around

**Comment by smarterclayton** [comment]
Not an issue anymore for me
