### ISSUE TITLE
Make it easier to rebase API changes

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#16108]
Currently, when you rebase API changes, you have to merge or otherwise make compilable the generated schema files, which are impossible for me personally (and I'm guessing just about everyone else) to merge.  There should be a script that you can use to 'blank out' generated files after rebase and reset them to the minimal buildable state so that all regenerations can be applied easily.

@wojtek-t @ncdc @kubernetes/rh-cluster-infra

**Comment by ncdc** [comment]
:+1:

**Comment by wojtek-t** [comment]
If we migrate our generator to use Daniel`s framework - https://github.com/kubernetes/kubernetes/pull/15714 this should be mostly solved.
I'm started working on deep-copy generation, convertions will be the next step.

**Comment by feihujiang** [comment]
:+1: , this is a good idea.

**Comment by bgrant0607** [comment]
We shouldn't check in generated files.

**Comment by spzala** [comment]
@pmorie hi Paul, this issue was opened for over a year now. I am not totally sure but I believe it's not a problem any more and in that can we close this issue? Thanks!!
