### ISSUE TITLE
Add Metrics for RESTClients to kuberentes for all clients to optionally use via standard scrape (WAS: pushgateway but that is overkill)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#16100]
Recently @timothysc has suggested the idea of using backpressure for managing client connect storms through a LB endpoint.  

As a corallary to that end, we've dug in and saw that the RESTClient implementation has a mixture of timed backoff/throttle logic.  

As a way **to quantify requests and backoffs for requests into the apiserver, and also to determine what the real hotspots are, we can use a prometheus pushgateway in the RESTClient.**  This basically allows us to, for a given time frame, collect metrics on how the RESTClient is being used or abused by nodes, clients, applications and so on.    

Of course, this **could** be estimated from apiserver metrics, but only the clients themselves are tracking backoff rates.  

Right now, the RESTClient has some metrics, but they aren't necessarily going to be collected for every connection in a system.

I am doing this experimentally now just for data gathering.  I can open a PR if folks are interested in having it in the upstream.

**Comment by timothysc** [comment]
s/Add pushgateway to kuberentes/Add metrics for RESTClients.

**Comment by jayunit100** [comment]
Ok.  I've added a first pass.  Heres what they look like from client's perspective.  
![screenshot from 2015-10-22 11 31 11](https://cloud.githubusercontent.com/assets/826111/10669828/80f8f54e-78b0-11e5-818a-6b43c0933c82.png)

**Comment by jayunit100** [comment]
Now I'll start bucketing these guys to see what URLs are hit the most/least.  have to think some about the right way to do it

**Comment by jayunit100** [comment]
As per conv. w/ tim, **pushgateway is not needed** for the majority of requests which we're assuming (in a  normal system) will come from servers which host scrapable endpoints...

**Comment by jayunit100** [comment]
Update, as part of this work we've been logging some of the urls, to put them into a hashmap for backoffs.  Separate issue, but in any case, I've pasted the keys acquired below as a sample of how backoff times will be 
mapped.

http://127.0.0.1:8080/api/v1/persistentvolumeclaims
http://127.0.0.1:8080/api/v1/persistentvolumes
http://127.0.0.1:8080/api/v1/persistentvolumes
http://127.0.0.1:8080/api/v1/secrets
http://127.0.0.1:8080/api/v1/serviceaccounts
http://127.0.0.1:8080/api/v1/namespaces
http://127.0.0.1:8080/api/v1/serviceaccounts
http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/serviceaccounts
http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/serviceaccounts/%7Bname%7D
http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/secrets
http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/serviceaccounts/%7Bname%7D
http://127.0.0.1:8080/api/v1/nodes
http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/events
http://127.0.0.1:8080/api/v1/resourcequotas
http://127.0.0.1:8080/api/v1/nodes
http://127.0.0.1:8080/api/v1/persistentvolumes
http://127.0.0.1:8080/api/v1/persistentvolumeclaims
http://127.0.0.1:8080/api/v1/persistentvolumes
http://127.0.0.1:8080/api/v1/nodes
http://127.0.0.1:8080/api/v1/pods
http://127.0.0.1:8080/api/v1/services
http://127.0.0.1:8080/api/v1/nodes
http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/events
http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/events
http://127.0.0.1:8080/api/v1/nodes
http://127.0.0.1:8080/api/v1/nodes/%7Bname%7D
http://127.0.0.1:8080/api/v1/nodes/%7Bname%7D/status
http://127.0.0.1:8080/api/v1/nodes/%7Bname%7D
http://127.0.0.1:8080/api/v1/nodes/%7Bname%7D/status
http://127.0.0.1:8080/api/v1/nodes/%7Bname%7D
http://127.0.0.1:8080/api/v1/services
http://127.0.0.1:8080/api/v1/endpoints
http://127.0.0.1:8080/api/v1/namespaces/%7Bnamespace%7D/events
http://127.0.0.1:8080/api/v1/services
http://127.0.0.1:8080/api/v1/pods
http://127.0.0.1:8080/api/v1/replicationcontrollers
http://127.0.0.1:8080/api/v1/nodes
http://127.0.0.1:8080/api/v1/pods
http://127.0.0.1:8080/api/v1/pods

**Comment by timothysc** [comment]
You only really need to bin on 'http://host:port' for backoff, but I find the breakout informative.

**Comment by jayunit100** [comment]
I was thinking maybe, for example, if `/namespaces/` queries were failing or were slow, maybe those would need more backoff than, say, `/nodes`... after all, won't all queries generally be going into a constant balanced endpoint anyway ?

**Comment by jayunit100** [comment]
Plan from conversation today. 

1. Measure: (What do we want to measure and why?)  [C1] 

    We want to measure kubernetes internal RestClients to a 

    Counts for 'host:port'/ connections 

    label=responseCode(404,200,...)

     label=action(GET,POST,..).

2 Analyze:

    Start graphing against density monitoring both nodes and controllers while purposefully triggering failure conditions. (restarting etcd)

    Monitor metrics

    Run a custom controller during the analyssis, and observe its ability to "do work" given failure conditions.

    Determine the set of failure conditions that occur and which ones to backoff on:

    http://kb.globalscape.com/KnowledgebaseArticle10141.aspx

    Define WHEN to back off based on ^.

3. Improve: [Commit 2-N]

    Create (update existing) method/plumbing to exponentially backoff 'host:port' on failure conditions, determined during analysis (goal: in throttle.go, unless it has to be in restclient.go)

    Determine how we wish backoff. http://dthain.blogspot.com/2009/02/exponential-backoff-in-distributed.html

    Throttle *[host:port] clients

4. Control / Test Cases: [Commit N+1]

    Custom Controller (add desc to unit tests)

    specific logging (backing off for the right reasons ?+ all good - this confirms that exp backoff is happening for right reasons.

    when custom controller (pod deleter) runs, density profiles should be significantly different, even after failure conditions - this confirms that controller comes back online after exp backoff.

    UTs for the throttling - verify backoff f(n) behaves as expected.
