### ISSUE TITLE
NFS volume plugin may need to force unmount if it's stuck

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#16104]
I just had a pod that I tried to `kubectl delete`. It didn't work. I left it overnight and checked the logs and found it full of:

```
I1022 16:14:57.801925    4363 kubelet.go:1976] SyncLoop (ADD, "api"): "nfs-busybox_default, fluentd-cloud-logging-kubernetes-minion-9gzi_kube-system, heapster-v10-5m4qf_kube-system, kube-ui-v3-w9bqb_kube-system"
I1022 16:14:57.804664    4363 manager.go:1413] Killing container "280fed192f3a7cd7128c90243b88b5ed7e7ecde0bab08cbe485bac13381ed053 busybox default/nfs-busybox" with 30 second grace period
```

Looks like the joys of NFS mount stability on Linux have struck again again. I did a `umount -f` on the node and the pod evaporated quickly.

**Comment by spzala** [comment]
@zmerlynn hi, this issue is around for long time and seems like not an a real k8s issue and it can be closed? If needed, we can document it and then close? Thanks! 
/cc @thockin
