### ISSUE TITLE
Worrying memory usage of kube-proxy since cluster upgrade to 1.0.6

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kubernetes#16103]
Hello,

I just upgraded yesterday the nodes of my production cluster from 1.0.3 to 1.0.6 hosted on GKE (master was already in 1.0.6).
I'm seeing a worrying memory usage of some of the kube-proxy. One of the kube-proxy grew up to 520 MB of RAM in 22H and seems to leak memory nearly linearly.
See picture attached.
<img width="1267" alt="screen shot 2015-10-22 at 17 00 46" src="https://cloud.githubusercontent.com/assets/525763/10668868/7e99c340-78de-11e5-8db9-90bd3fcb76fb.png">
The metrics come from heapster pushing to influxdb.

I'm can supply kube-proxy logs if needed.
Any thoughts on how to manage that ?

**Comment by thockin** [comment]
What sort of load is this under?  How willing to participate in the debug
are you?  if we provided instructions, would you capture a memory profile?
Would you be willing to try a new kube-proxy binary?

**Comment by rvrignaud** [comment]
Hello @thockin,
I don't seem to have exotic workload except one of my logstash aggregator that should receive a lot of UDP packets.

I can spend as much time to help debugging this problem as needed. My main concern is that I need to ensure reliability and performance of the node. Is there any way to prevent pods from a specific namespace to be scheduled in this node ? This would allow me to be sure that I don't have any production pod that could be impacted by the debugging process.

If memory profiling is safe (reliability / performances) I would be happy to perform provided instructions.
In the same way I'm willing to test a new kube-proxy binary if I have a reasonable performances / reliability warranty.

Any help appreciated.

**Comment by thockin** [comment]
Grabbing a profile should cause no problems.  Let's try it.

Pick a node on which this is happening.  Let's call that "nodeX" for these
instructions.

1) SSH to nodeX: gcloud compute ssh nodeX

2) become root: sudo bash

3) edit the flags for kube-proxy: vi /etc/default/kube-proxy

4) expose healthz: add "--healthz-port=80 --healthz-bind-address=0.0.0.0"
to the flags

5) save file

6) restart: /etc/init.d/kube-proxy restart

7) get the external IP for nodeX: gcloud compute instances list nodeX

8) get the profile: go tool pprof -pdf http://<nodeIP>:80/debug/pprof/heap
> foo.pdf

Alternatively, you can tell me the IP and I can pull the profile myself.
It gives me no access to your cluster except that I can see that one node's
kube-proxy debug info.  You can email me the IP (don't post it here) if you
want to go this route.

Now, the interesting part here is that you'll restart the proxy, which will
clear the memory buildup.  So you might want to do this, wait 24 hours and
then grab the profile. :)

Once we have a profile, you should be able to un-do all of this.

**Comment by rvrignaud** [comment]
Hello,

I found that I had a misconfiguration in my logstash configuration that provoked a log endless loop. Fixing that ended the memory growing usage and a few hours later, memory seemed to be garbage collected. 

<img width="1274" alt="screen shot 2015-10-23 at 16 27 57" src="https://cloud.githubusercontent.com/assets/525763/10695258/1db6fc94-79a3-11e5-842b-8168a66adc40.png">

Here is the profiling on al0f kube-proxy without restarting the process but after the memory "garbage collecting".

![al0f](https://cloud.githubusercontent.com/assets/525763/10695847/2a40b218-79a6-11e5-9030-b53e2934d08b.png)

I spawned a test cluster in GKE to see if I can reproduce memory leak using udp iperf pods sending a large amount of udp traffic. I have pods with both iperf server and clients. They are sending udp traffic through kube-proxy.

For a unknown reason, it seems that kube-proxy in that test cluster is crashing / restarting in loop when I add "--healthz-port=80 --healthz-bind-address=0.0.0.0" in the command line. I don't get any log except "kube-proxy failed!" in /var/log/supervisor/kube-proxy-stdout.log.

I'm still running the test and I'm making the memory profiling using ssh port forwarding as I can't keep a kube-proxy live longer than a few minutes when it exposes its healthz port on 0.0.0.0. I'll let it run for a few hours and try to post the memory profiling image here.

Let me know if I can do anything else to help debugging this issue.

**Comment by thockin** [comment]
It sounds like the fire is out, and the cause was what I suspected - large
numbers of UDP connections.  We've reduced the idle timeout significantly
in v1.1, and we have another issue to investigate memory on kube-proxy.

If I am understanding correctly, this reduces the urgency of this.  We can
close this issue and use  #14118 to track memory usage

**Comment by rvrignaud** [comment]
Hello, 
Yes there is no more production urgency on my side. 
Closing this one.

**Comment by thockin** [comment]
Thanks for grabbing the profile - it confirmed what I expected.
