### ISSUE TITLE
Remove ContainersNotReady conditions from a terminated Pod?

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#16113]
When a Pod without a readiness probe is running, we show a Condition like `status: "True" type: Ready`.
We document this behavior in `docs/user-guide/introspection-and-debugging.md`.
This seems reasonable.

However when a Pod without a readiness probe terminates in Phase Succeeded, we show it as not Ready.  Showing it as not-ready is confusing and noisy.   It looks like this:
```
  - lastProbeTime: null
    lastTransitionTime: 2015-10-22T17:54:57Z
    message: 'containers with unready status: [foo]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
```

It is confusing because words like "False" and "ContainersNotReady" sound like bad things.  But, they are in fact expected since the Pod has reached a final non-running state.  And because it was ready before.

Also, it is visual clutter when you dump out the complete status of the pod.

Would it make sense to do one of the following:

1. remove the Ready condition entirely from terminated pods (or does it have some historical value?) 
1. not set a Readiness condition at all for Pods which do not have RestartPolicy = Always and do not have an explicit readiness probe, on the assumption they are not going to be part of services, and so don't need Readiness.

**Comment by erictune** [comment]
Option 3:

When pod has succeeded, update Condition to:
```
  - lastProbeTime: null
    lastTransitionTime: 2015-10-22T17:54:57Z
    reason: PodCompleted
    status: "False"
    type: Ready
```

**Comment by zhengguoyong** [comment]
Do you need some help?  
I would happy to do this.
:)
