### ISSUE TITLE
Add integration test with mock kubelet 1.0 backend to verify exec subprotocol fallback

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#16119]
PR #13322 fixed a variety of bugs with exec/attach, but unfortunately introduced some backwards incompatibility when a newer kubectl that included the fixes attempted to exec against a 1.0.x kubelet.

#15961 adds support for subprotocol negotiation for exec, attach, and portfoward, and restores the ability for the latest kubectl to talk to 1.0.x kubelets for exec.

We need a way to test that the restored behavior (new kubectl, 1.0 kubelet) is working.

cc @smarterclayton

**Comment by lavalamp** [comment]
I think we should require this testing be in place before we take any more changes to exec & friends, otherwise it won't get done...

**Comment by ncdc** [comment]
@smarterclayton you mentioned you wanted this as an "integration" test. Do you have an inkling on how to put this together? If all the code in HEAD is the same, how do we mock a 1.0 kubelet?

**Comment by smarterclayton** [comment]
I think we'd benefit from splitting the exec / attach / logs wrappers out
of Kubelet server into their own types.  We can then test the end to end
with the different backends.  Goal being to have test that covers the code
paths in Kubelet server to the client.  We can then emulate a legacy
server, and require new changes to work with that old server.  That'll also
help us test our tolerance to docker exec bugs (or when we introduce
alternate exec backends, ensure our problems are backend specific).

On Oct 26, 2015, at 6:54 PM, Andy Goldstein <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> you mentioned you
wanted this as an "integration" test. Do you have an inkling on how to put
this together? If all the code in HEAD is the same, how do we mock a 1.0
kubelet?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/16119#issuecomment-151307779>
.
