### ISSUE TITLE
Validate docker v1.9.0-rc1 release 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#16110]
.

**Comment by dchen1107** [comment]
@vishh is this your turn?

**Comment by vishh** [comment]
Sure :) I will work on this!

**Comment by vishh** [comment]
Update: I'm testing v1.9.0~rc4. I'm running the following suite of tests (based on `hack/jenkins/e2e.sh`) - ` kubernetes-e2e-gce`, ` kubernetes-e2e-gce-slow`, `kubernetes-e2e-gce-parallel`, ` kubernetes-e2e-gce-parallel`.

**Comment by vishh** [comment]
Update: No tests failed in `kubernetes-e2e-gce` suite. This release has been looking good so far.

**Comment by vishh** [comment]
Update: No tests failed in `kubernetes-e2e-gce-slow` suite. :smiley:

**Comment by vishh** [comment]
Update: `kubernetes-e2e-gce-parallel` tests passed.

**Comment by brendandburns** [comment]
Note, I'm think we want to set the `--dns-opt` flag from @thockin in https://github.com/docker/docker/pull/16031

**Comment by vishh** [comment]
@brendandburns: What dns options have to be set?

**Comment by brendandburns** [comment]
I would ask @thockin but I assume he added the flag for a reason ;)

**Comment by thockin** [comment]
we can use dns-opt when we know we don't have to fall-back on older docker
versions.  We current have a (very clever) hack that works.  We set the
ndots option.

**Comment by feiskyer** [comment]
Docker has just released v1.9, so I think v1.9 should be validated on high priority.

**Comment by brendandburns** [comment]
@feiskyer yep, validation is underway by @vishh.  See above.

**Comment by vishh** [comment]
I have tested against most of the test suites. As of now there are no known issues. I'm planning on running soak tests next.

**Comment by vishh** [comment]
I haven't been able to find any issues. I will update HEAD to use docker v1.9 soon.

**Comment by dchen1107** [comment]
FYI: https://github.com/docker/docker/issues/17720 (Docker 1.9 serious performance issues)

**Comment by karlkfi** [comment]
Are the new /etc/hosts changes going to be an issue?

```
Do not update /etc/hosts for the default bridge network, except for links (#17325)
```
https://github.com/docker/docker/pull/17325

**Comment by vishh** [comment]
@karlkfi: AFAIK, we want docker to **not** touch `/etc/hosts` once the container is created.

**Comment by thockin** [comment]
re:/etc/hosts - we have our workaround which should dodge it entirely.

**Comment by pikeas** [comment]
+1, why is K8S still on docker 1.7.1?

**Comment by karlkfi** [comment]
Docker v1.9.1 was released a few weeks ago.

**Comment by yujuhong** [comment]
> FYI: docker/docker#17720 (Docker 1.9 serious performance issues)

@Random-Liu, it might be useful to run your mircobenchmark for docker v1.9 before we try to upgrade.

**Comment by vishh** [comment]
There are still some performance issues with v1.9.1. As of now I'm updating
HEAD to run docker v1.9.1 for now to help identify other potential issues.

**Comment by yujuhong** [comment]
Can we make sure v1.9.1 can pass e2e tests reliably before upgrading? I am dreading the endless test failures that we'll have to triage at the end of the day. The performance benchmark, e.g., at least can give us some idea about how this is going to affect kubelet.

**Comment by vishh** [comment]
Yes. Of course!

**Comment by Random-Liu** [comment]
@yujuhong I got the result I post before with docker 1.9:
* Go Version: 1.5.1
* Docker Version: 
    * Client Version: 1.9.0, API version: 1.21
    * Server Version:  1.9.0, API version: 1.21

**Comment by karlkfi** [comment]
We are now running docker 1.9.1 on the Mesosphere K8s CI. However, this is a little ambiguous, because the [mesos-slave-dind](https://github.com/mesosphere/mesos-slave-dind) containers that run the kubelets still use docker 1.8.2.

This upgrade did, however, fix a regular problem we were having in our CI scripts on docker 1.7.1 where layer pulls would block and/or stall (without any other concurrent docker use).

**Comment by dchen1107** [comment]
@vishh Besides the performance issue I brought up at https://github.com/kubernetes/kubernetes/issues/16110#issuecomment-154210277, there are a network related issue in docker 1.9.1 should affect k8s: cc/ @thockin @kubernetes/goog-cluster 

https://github.com/docker/docker/issues/18535 & https://github.com/docker/docker/issues/18145

We should wait for 1.9.2 for whatever reason.

**Comment by vishh** [comment]
xref: https://github.com/docker/docker/milestones/1.9.2

**Comment by Random-Liu** [comment]
**Introduction**
I benchmarked `docker ps` and `docker inspect` with the following 3 experiments:

1. Do periodically `docker ps` and `docker inspect`, ***gradually increase the dead container number and alive container number***.
2. Do periodically `docker ps` and `docker inspect`, ***gradually increase the operation interval***.
3. Do periodically `docker ps` and `docker inspect`, ***gradually increase the number of goroutines which doing `docker ps` and `docker inspect`***.

The metrics we measured:
* CPU usage.
* `docker ps` latency.
* `docker inspect` latency.

**Benchmark Environment**
* Cloud Provider: GCE
* VM Instance: n1-standard-2 (2 vCPUs, 7.5 GB memory)
* OS: Debian GNU/Linux 8.3 (jessie)
* Docker version:
```
lantaol@docker-perf-1-8-3:~$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:27:08 UTC 2015
 OS/Arch:      linux/amd64
Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:27:08 UTC 2015
 OS/Arch:      linux/amd64
```
```
lantaol@docker-perf-1-9-1:~$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64
Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64
```

**Experiment 1**
* **Workflow:**
start -> create containers -> periodically `docker ps [all=true]` -> periodically `docker ps[all=false]` -> periodically `docker inspect` -> create containers -> ... -> finish
* **Environment Variable**
 * Operation interval: 200ms
* **Container Number**
![varies_container](https://cloud.githubusercontent.com/assets/5821883/12855520/cf65ca94-cbf4-11e5-97d6-57d152a387d7.png)
* **Latency**
 * Docker 1.8.3
![latency-varies_container](https://cloud.githubusercontent.com/assets/5821883/12855513/c3c3a2a6-cbf4-11e5-8950-91cb9ba7786a.png)
 * Docker 1.9.1
![latency-varies_container](https://cloud.githubusercontent.com/assets/5821883/12855505/bc233386-cbf4-11e5-9a6d-c83749d733f6.png)
* **CPU Usage**
 * Docker 1.8.3
![cpu](https://cloud.githubusercontent.com/assets/5821883/12855469/81db5e06-cbf4-11e5-943c-28f00f432aab.png)
 * Docker 1.9.1
![cpu](https://cloud.githubusercontent.com/assets/5821883/12855479/8a96cd96-cbf4-11e5-8e2e-26526c357ff4.png)

Summary: TODO

**Experiment 2**
* **Workflow:**
start -> periodically `docker ps [all=true]` with increasing interval -> periodically `docker ps [all=false]` with increasing interval -> periodically `docker inspect` with increasing interval -> finish
* **Environment Variable**
 * Dead container number: 600
 * Alive container number: 200
* **`ps` Interval**
![list_alive](https://cloud.githubusercontent.com/assets/5821883/12855588/37accf94-cbf5-11e5-987f-e38f03035e1d.png)
* **`ps` [all=true] Latency**
 * Docker 1.8.3
![latency-list_all](https://cloud.githubusercontent.com/assets/5821883/12855821/7758d114-cbf6-11e5-9ebc-fefa77fb5628.png)
 * Docker 1.9.1
![latency-list_all](https://cloud.githubusercontent.com/assets/5821883/12855829/84f42a76-cbf6-11e5-8864-1b90a89bbaea.png)
* **`ps` [all=false] Latency**
 * Docker 1.8.3
![latency-list_alive](https://cloud.githubusercontent.com/assets/5821883/12855841/98ae3c14-cbf6-11e5-904b-2e8b0c09c95c.png)
 * Docker 1.9.1
![latency-list_alive](https://cloud.githubusercontent.com/assets/5821883/12855835/90d49a38-cbf6-11e5-84e9-62934070f4f2.png)
* **`inspect` Interval**
![inspect](https://cloud.githubusercontent.com/assets/5821883/12855854/b499dadc-cbf6-11e5-81ac-27c5966169dc.png)
* **`inspect` Latency**
 * Docker 1.8.3
![latency-inspect](https://cloud.githubusercontent.com/assets/5821883/12855860/bad9aa58-cbf6-11e5-8faa-06a17f25fab6.png)
 * Docker 1.9.1
![latency-inspect](https://cloud.githubusercontent.com/assets/5821883/12855869/c2b81520-cbf6-11e5-83a9-159f060cbe79.png)
* **CPU Usage**
 * Docker 1.8.3
![cpu](https://cloud.githubusercontent.com/assets/5821883/12855884/d9cd0b1c-cbf6-11e5-9446-e9ffecbb235b.png)
 * Docker 1.9.1
![cpu](https://cloud.githubusercontent.com/assets/5821883/12855878/d34510e6-cbf6-11e5-81a5-0fb83bcd721f.png)

Summary: TODO

**Experiment 3 Result**
* **Workflow:**
start-> periodically `docker ps [all=true]` with increasing groutines number -> periodically `docker inspect` with increasing groutines number -> finish
* **Environment Variable**
 * Dead container number: 600
 * Alive container number: 200
 * `docker ps` interval: 1s
 * `docker inspect` interval: 0.5s
* **Routine Number**
![list_all](https://cloud.githubusercontent.com/assets/5821883/12856097/fe6aa1a4-cbf7-11e5-9f3f-260e3234160f.png)
The change rule of routine number is the same for `docker ps` and `docker inspect`.
* **`ps` [all=true] Latency**
 * Docker 1.8.3
![latency-list_all](https://cloud.githubusercontent.com/assets/5821883/12856116/1985da62-cbf8-11e5-8b28-3dbe546417b3.png)
 * Docker 1.9.1
![latency-list_all](https://cloud.githubusercontent.com/assets/5821883/12856118/203b6ec6-cbf8-11e5-896a-747e16f85669.png)
* **`inspect` Latency**
 * Docker 1.8.3
![latency-inspect](https://cloud.githubusercontent.com/assets/5821883/12856140/3b013b5a-cbf8-11e5-868b-543fc784b774.png)
 * Docker 1.9.1
![latency-inspect](https://cloud.githubusercontent.com/assets/5821883/12856134/36111da4-cbf8-11e5-9fae-990189e2e809.png)
* **CPU Usage**
 * Docker 1.8.3
![cpu](https://cloud.githubusercontent.com/assets/5821883/12856170/5e182860-cbf8-11e5-9055-e79d0abce019.png)
 * Docker 1.9.1
![cpu](https://cloud.githubusercontent.com/assets/5821883/12856172/6374ffd6-cbf8-11e5-9f99-acd8938efd52.png)

Summary: TODO

**Conclusion**
There is no significant performance difference for `docker ps` and `docker inspect` between **docker 1.9.1** and **docker 1.8.3**.
