### ISSUE TITLE
Support enabling all extension resources

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#16117]
Forked from https://github.com/kubernetes/kubernetes/pull/15981

Right now, we need to list all resources that we need to enable, for ex: to enable deployments and daemonsets, I will have to set `--runtime-config=extensions/v1beta1/deployments=true,extensions/v1beta1/daemonsets=true`

from https://github.com/kubernetes/kubernetes/pull/15981#issuecomment-150010027

> We do not have extensions/v1beta1/all=true, but we have talked about adding it.

from https://github.com/kubernetes/kubernetes/pull/15981#issuecomment-150012559

> We should make `extensions/v1beta1=true` turn on everything,
> `extensions/v1beta1=false` turn off everything, and have the absence of
> mention leave all the defaults.

cc @mikedanese @lavalamp @paralin

**Comment by paralin** [comment]
If the plan is to enable all on default we can completely merge my other commit removing the old EXPERIMENTAL vars. If not, I can revise to add ENABLE_* flags to make it easier to build the KUBE_RUNTIME_CONFIG variable. Either way the EXPERIMENTAL flags should be removed.
