### ISSUE TITLE
types.generated.go results in massive diffs

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#16128]
The package and variable allocation used in types.generated.go mean that any regenerate easily touches the whole file, which means conflicts between any commits that result in generated changes. The local name allocations should restart at the beginning of every function to minimize conflicts.

**Comment by liggitt** [comment]
cc @wojtek-t

**Comment by wojtek-t** [comment]
@liggitt - I agree but that's a request for the library maintainers not for us

**Comment by lavalamp** [comment]
This sounds awful :/

@mikedanese - does this explain what you were seeing?

**Comment by mikedanese** [comment]
It explains why it was so big, not why it was happening in the first place. I have a fresh master so I would expect no changes.

**Comment by liggitt** [comment]
resolved
