### ISSUE TITLE
Do not update api-reference docs if last updated timestamp is the only change

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#16121]
Right now, rerunning, update-api-reference-docs, keeps updating the docs with new last updated timestamp.
Similar to other generated docs, we should detect that case and not update the doc.

Note that verify-api-reference-docs works fine. (It ignores last update line change)

cc @caesarxuchao

**Comment by caesarxuchao** [comment]
I'll take a look :)

**Comment by caesarxuchao** [comment]
I'm still having issue with the file permission. I will revisit this later.
