### ISSUE TITLE
documentation: upgrade without downtime

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#16132]
What is the recommended approach for upgrading the kubernetes system without downtime?

For instance, we have two etcd hosts, a kubernetes master host, and N kubernetes node hosts.

When we step through each host and restart the relevant services, we see a lot of noise in the error logs, eg:

**When restarting services on an etcd host:**

```
[kubelet] E1020 19:47:32.929452   17262 reflector.go:183] watch of *api.Node ended with: EOF
[kubelet] E1020 19:47:57.291241    1851 reflector.go:183] watch of *api.Node ended with: EOF
[heapster] E1022 21:30:43.105975   19565 reflector.go:183] watch of *api.Node ended with: EOF
[kube-scheduler] E1022 21:30:43.105612   19483 reflector.go:183] watch of *api.Node ended with: EOF
[kube-scheduler] E1022 21:31:01.455430   19483 reflector.go:183] watch of *api.Service ended with: EOF
[kube-scheduler] E1022 21:31:01.455813   19483 reflector.go:183] watch of *api.Pod ended with: EOF
[kubelet] E1022 21:31:01.454142   28311 reflector.go:183] watch of *api.Pod ended with: EOF
[kubelet] E1022 21:31:01.459182   28311 reflector.go:183] watch of *api.Service ended with: EOF
[kubelet] E1020 19:48:15.638076    1851 reflector.go:183] watch of *api.Pod ended with: EOF
[kubelet] E1020 19:48:15.638528    1851 reflector.go:183] watch of *api.Service ended with: EOF
[kube-apiserver] E1022 21:31:01.453302   19307 reflector.go:183] watch of *api.Namespace ended with: EOF
[kube-apiserver] E1022 21:31:01.458767   19307 reflector.go:183] watch of *api.Namespace ended with: EOF
[kubelet] E1020 19:47:51.275654   17262 reflector.go:183] watch of *api.Pod ended with: EOF
[kubelet] E1020 19:47:51.277665   17262 reflector.go:183] watch of *api.Service ended with: EOF
```

**When restarting services on kubernetes master host:**

```
[kubelet] E1020 19:49:45.781736   22284 reflector.go:183] watch of *api.Node ended with: very short watch
[kubelet] E1020 19:49:45.781936   22284 reflector.go:165] Failed to watch *api.Pod: Get https://10.0.0.2:6443/api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.0.0.3&resourceVersion=2932158: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:49:45.781963   22284 reflector.go:183] watch of *api.Service ended with: very short watch
[kubelet] E1020 19:49:46.786014   22284 reflector.go:136] Failed to list *api.Service: Get https://10.0.0.2:6443/api/v1/services: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:49:46.786156   22284 reflector.go:136] Failed to list *api.Node: Get https://10.0.0.2:6443/api/v1/nodes?fieldSelector=metadata.name%3D10.0.0.3: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:10.142975    4936 reflector.go:183] watch of *api.Service ended with: very short watch
[kubelet] E1020 19:50:10.143154    4936 reflector.go:165] Failed to watch *api.Node: Get https://10.0.0.2:6443/api/v1/watch/nodes?fieldSelector=metadata.name%3D10.0.0.7&resourceVersion=2932162: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:10.143185    4936 reflector.go:183] watch of *api.Pod ended with: very short watch
[kubelet] E1020 19:50:11.144252    4936 reflector.go:165] Failed to watch *api.Node: Get https://10.0.0.2:6443/api/v1/watch/nodes?fieldSelector=metadata.name%3D10.0.0.7&resourceVersion=2932162: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:11.144334    4936 reflector.go:136] Failed to list *api.Service: Get https://10.0.0.2:6443/api/v1/services: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:11.144396    4936 reflector.go:136] Failed to list *api.Pod: Get https://10.0.0.2:6443/api/v1/pods?fieldSelector=spec.nodeName%3D10.0.0.7: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:12.145448    4936 reflector.go:136] Failed to list *api.Pod: Get https://10.0.0.2:6443/api/v1/pods?fieldSelector=spec.nodeName%3D10.0.0.7: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:12.145518    4936 reflector.go:165] Failed to watch *api.Node: Get https://10.0.0.2:6443/api/v1/watch/nodes?fieldSelector=metadata.name%3D10.0.0.7&resourceVersion=2932162: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:12.145549    4936 reflector.go:136] Failed to list *api.Service: Get https://10.0.0.2:6443/api/v1/services: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:13.146826    4936 reflector.go:136] Failed to list *api.Pod: Get https://10.0.0.2:6443/api/v1/pods?fieldSelector=spec.nodeName%3D10.0.0.7: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:13.146902    4936 reflector.go:165] Failed to watch *api.Node: Get https://10.0.0.2:6443/api/v1/watch/nodes?fieldSelector=metadata.name%3D10.0.0.7&resourceVersion=2932162: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:13.146931    4936 reflector.go:136] Failed to list *api.Service: Get https://10.0.0.2:6443/api/v1/services: dial tcp 10.0.0.2:6443: connection refused
[kubelet] E1020 19:50:13.347216    4936 kubelet.go:1933] Error updating node status, will retry: error getting node "10.0.0.7": Get https://10.0.0.2:6443/api/v1/nodes/10.0.0.7: dial tcp 10.0.0.2:6443: connection refused
...
[kubelet] E1020 19:49:53.478463   22284 kubelet.go:839] Unable to update node status: update node status exceeds retry count
```

What's the recommended approach / sequence / etc to upgrade each host in the system without downtime (and with minimal error spew)?

**Comment by davidopp** [comment]
For the minion nodes: Upgrading the nodes should "just work" -- the pods that get killed should be rescheduled to another minion, assuming they are running under a ReplicationController. Of course you need to make sure not to take so many nodes down at the same time that there is not enough resources on other machines for the pods from the down machine to reschedule.

For the master and etcd: I think the proper way to upgrade the masters/etcd without causing master downtime is to run the full HA configuration and update one node at a time. See
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/high-availability.md
This should ensure you always have an API server up, always have an etcd quorum, and always have at least one replica of the scheduler and controller manager up.
(Note that if you were running the standard, non-HA configuration of one master+one etcd on the same machine, it should be fine to take the machine down, do your upgrade, and bring it back up. All the pods will keep running on the minions while the master+etcd are down. Of course the master will be unavailable while it is down.)

AFAIK we haven't really experimented with what you're doing -- running a single master and an etcd cluster that can't keep a qorum when there is a node down, and then taking etcd offline without taking down the master or vice-vera. I would think that taking down the master while leaving etcd up should work fine, though it seems you're getting some weird log messages when you bring the master back up? Taking down etcd while leaving the master up seems a bit more dicey, but in theory we should try to make the master not freak out when this happens.

We should do more investigating of this.

@lavalamp 
@timothysc

**Comment by lavalamp** [comment]
I think those log messages are expected and not a big deal, with the
exception that they're happening too frequently. We should slow down the
retries to 1/second or slower, just to reduce log spam.

**Comment by timothysc** [comment]
Re: HA, this kind of depends on your configuration.  We / Red Hat, do not use podmaster for our HA configuration.  Instead we use either pacemaker | openshift have lock-leasing built in which is similar to what is done in podmaster.

The HA configuration we typically recommend is: 
3-master nodes (apiserver+etcd+controllermanager+scheduler) 
- etcd is configured in a HA qurorum. 
- controllermanager+scheduler are in an active-passive lock leasing setup, such that only one is active at a time 
- apiserver is active-active with a load-balanced (HA-Proxy) virtual ip(VIP) in front of it.  

In this configuration you can take out any master node and it will recover.

**Comment by chrislovecnm** [comment]
@bgrant0607 going to ask an evil question :(   Is this really not documented yet? How has this been open for a year?

**Comment by bgrant0607** [comment]
@chrislovecnm Would be happy to assign this to you.

See also #15244.

**Comment by davidopp** [comment]
cc/ @fgrzadkowski

**Comment by chrislovecnm** [comment]
@bgrant0607 I am currently improving how kops does rolling upgrades. Once that is mature, I could blog on it, and flip that into documentation.  Not an easy task to complete.

Does GKE have a playbook on how they perform upgrades?

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-cluster-lifecycle

**Comment by luxas** [comment]
@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by errordeveloper** [comment]
@luxas I'm not sure if we should keep this open, what do you think?

**Comment by roberthbailey** [comment]
@wojtek-t / @chrislovecnm - do either of you want to take this issue and create some documentation about how to do upgrades without downtime?
