### ISSUE TITLE
Support advertise-port flag in apiserver for use in kubernetes master service endpoint

### ISSUE THREAD

**Issue by ravilr** [kubernetes/kubernetes#16139]
there is already --advertise-address which when set, is used as the public address in default `kubernetes` service endpoint. Can --advertise-port setting also be exposed ?
Currently, the secure port is passed along to master controller as the publicServicePort to be used in `kubernetes` endpoint. this will be helpful in multi apiserver setups using external loadbalancer for both external and internal cluster access, where the external loadbalancer port is different then the loadbalanced apiserver's secure port. 
 
advertise-address was added here https://github.com/kubernetes/kubernetes/pull/8649
@thockin @lavalamp

**Comment by lavalamp** [comment]
Do you want to advertise the external loadbalancer's port? Why?
