### ISSUE TITLE
Scalability: watch out for excessive 409s

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#16133]
In logs from an e2e test run on my own cluster,  over a 1 hour period, about 6% of requests to the apiserver were resulting in 409s.  I have not inspected logs from a scalability test, but it would be worth doing so to see if 409s are a significant waste of time.

I just did something like this:
```console
$ dayhourpattern="1022 04:"
$ total=$(cat /var/log/kube-apiserver.log | grep "$dayhourpattern" | "wc -l)
$ conflicts=$(cat /var/log/kube-apiserver.log | grep "$dayhourpattern" | grep " 409 " | wc -l)
$ echo $(( $conflicts * 100 / $total ))% of requests are conflicts
6% of requests are conflicts
```

**Comment by erictune** [comment]
@wojtek-t

**Comment by paralin** [comment]
+1

**Comment by wojtek-t** [comment]
I took last scalability run and the results are:

    wojtekt@wojtekt-work:~/Downloads$ cat apiserver.txt | grep "handlers.go" | wc -l
    444821
    wojtekt@wojtekt-work:~/Downloads$ cat apiserver.txt | grep "handlers.go" | grep " 409 " | wc -l
    1174

So conflicts are ~0.26% of all requests.
It is visible, but not very dangerous (in my opinion).

I'm closing it now, because we have #16134 open anyway.
