### ISSUE TITLE
Some "Examples" do not map to the navigation menu in k8s.io

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#16130]
I searched and found that the following examples are only found in the master branch and are not exposed out on [kubernetes.io](http://kubernetes.io/).

These file are (or will be for v1.1) most likely copied over into the gh-pages branch but are currently not listed in the navigation menu.

It not clear if these are only drafts and are currently being written or if they are complete and should be surfaced/exposed in the k8s.io navigation tree:

examples/aws_ebs/README.md
examples/blog-logging/diagrams/README.md
examples/cephfs/README.md
examples/elasticsearch/production_cluster/README.md
examples/extensions/horizontal-pod-autoscaling/README.md
examples/fibre_channel/README.md
examples/flocker/README.md
examples/guestbook-go/_src/README.md
examples/javaee/README.md
examples/javaweb-tomcat-sidecar/README.md
examples/k8petstore/bps-data-generator/README.md
examples/kubectl-container/README.md
examples/meteor/dockerbase/README.md
examples/mysql-cinder-pd/README.md
examples/mysql-galera/README.md
examples/nfs/exporter/README.md
examples/nfs/nfs-data/README.md
examples/nodesjs-mongodb/README.md
examples/runtime-constraints/README.md
examples/selenium/README.md
examples/sharing-clusters/README.md
examples/spark/images/driver/README.md
examples/vitess/README.md

If any of the above examples should be added, they belong somewhere in these sections:

![image](https://cloud.githubusercontent.com/assets/11762685/10678670/b6f7ef8e-78c8-11e5-9d0b-1a0fb696d2a3.png)

To add an example, insert an entry into the corresponding version's navigation menu (ie. nav_v1.0.html or nav_v1.1.html) [here](https://github.com/kubernetes/kubernetes/tree/gh-pages/_includes).

@jeffmendoza

**Comment by amygdala** [comment]
I'm not really the right person to be assigned to this, but leaving it for now.

**Comment by bgrant0607** [comment]
Obsolete.
