### ISSUE TITLE
Parallelize kubernetes-e2e-gce-autoscaling

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#16158]
Currently in the suite we run:
- horizontal pod autoscaling tests which can be run in parallel.
- cluster size autoscaling tests which can't be run in parallel

I'd imagine that we will run parallel tests first and then switch to sequential mode. 

@ixdy is it possible to have such hybrid suite in Jenkins?

cc @fgrzadkowski @jszczepkowski @mwielgus

**Comment by jszczepkowski** [comment]
Paralyzing hpa tests is reasonable. Maybe we should just have two suits: one for hpa (parallel) and one for cluster autoscale.

**Comment by ixdy** [comment]
The only way to have a hybrid suite like that is to break up the test into separate specs so we can focus on each, and then run e2e tests twice, once focusing on the parallel test, once focusing on the sequential test.

I'm not sure how much value we'd get from running e2e tests twice in a single run like that (the intent of using parallel mode is to make the tests run quickly), but splitting up the test to increase parallel coverage (if that's not done already) is probably worth doing.

**Comment by ihmccreery** [comment]
Related to #10548.

**Comment by piosz** [comment]
This issue is obsolete. We are fine with the tests running in sequential mode.
