### ISSUE TITLE
service-account-private-key-file seems no need to verify the signature

### ISSUE THREAD

**Issue by gouyang** [kubernetes/kubernetes#16151]
```
./kube-controller-manager --service-account-private-key-file=/tmp/serviceaccount.key --master=http://localhost:8080
```

run controller-manager with a key file which is created temporarily, the service can be running and the service account default will be created successfully. I supposed it should be verified by CA or by `apiserver --service-account-key-file`.

**Comment by spzala** [comment]
@gouyang hello, this issue is opened over a year ago. Is this still an issue? Can it be closed otherwise please? Thanks!

**Comment by spzala** [comment]
Thanks @gouyang !!
