### ISSUE TITLE
Frequent logs about exceeded maxTries

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#16162]
I am seeing frequent kubelet logs like this:

```
E1022 04:12:32.944300    3663 manager.go:1933] Error running pod "rand-local-1ia25_e2e-tests-job-mfyjr" container "c": exceeded maxTries, some processes might not have desired OOM score
E1022 04:13:02.773880    3663 manager.go:1933] Error running pod "rand-local-1ia25_e2e-tests-job-mfyjr" container "c": exceeded maxTries, some processes might not have desired OOM score
```

I am running a cluster built from head on Oct 19th.

I trigger the logs by running this e2e test repeatedly:

``` console
$ e2e.test --host="https://104.197.70.187" --provider="gce" --ginkgo.v=true -ginkgo.dryRun=true --kubeconfig="$HOME/.kube/config" --repo-root="$KUBERNETES_SRC_PATH" -ginkgo.focus='Job.should.run.a.job.to.completion.when.tasks.sometimes.fail.and.are.locally.restarted
```

Then I look at the kubelet logs on my kubelets.

The `exceeded maxTries` string is from `pkg/util/oom/oom_linux.go`.

I think the problem is that the container run by this test exits very quickly, and so by the time we get to run this code, there are no pids in the container.

Would it make sense to detect when there are no pids in the container, and conclude that it has exited and not return an error?  Or would there be a race waiting for it to start?  But doesn't that race already exist?

**Comment by erictune** [comment]
I also see these error messages, which I think may also be related to quickly-exiting containers:
```
I1022 04:12:42.716168    3663 helpers.go:96] Unable to get network stats from pid 5757: couldn't read network stats: failure opening /proc/5757/net/dev: open /proc/5757/net/dev: no such file o

W1022 04:12:42.733841    3663 container.go:326] Failed to create summary reader for "/d5e623b683a37603afa6aea914f7ee3e0779e5ff7d3b05b813f4ff0c711c540d": none of the resources are being tracked
which did happen for other tests, but only happened 21 times.

W1022 04:12:42.733899    3663 manager.go:984] Failed to process watch event: failed to read libcontainer config: open /var/lib/docker/execdriver/native/d5e623b683a37603afa6aea914f7ee3e0779e5ff
```

**Comment by dhawal55** [comment]
I'm seeing similar error for one of my container:
```
Error syncing pod, skipping: failed to "StartContainer" for "alertmanager" with RunContainerError: "failed to apply oom-score-adj to container \"exceeded maxTries, some processes might not have desired OOM score\"- /k8s_alertmanager.1065c779_prometheus-1281092506-59j5e_kube-system_ae904db1-1238-11e6-8fe0-0258323de05f_f2eeb0c0"
```

What is OOM score?

**Comment by AaronTao1990** [comment]
I have got the same problem

	I0520 00:59:57.876139   32133 helpers.go:101] Unable to get network stats from pid 41402: couldn't read network stats: failure opening /rootfs/proc/41402/net/dev: open /rootfs/proc/41402/net/dev: no such file or directory
	I0520 01:00:13.716862   32133 helpers.go:101] Unable to get network stats from pid 41402: couldn't read network stats: failure opening /rootfs/proc/41402/net/dev: open /rootfs/proc/41402/net/dev: no such file or directory
	I0520 01:59:44.209016   32133 kubelet.go:2448] SyncLoop (PLEG): "busybox_default(7cffb642-1d92-11e6-a9d1-1402ec3ed5c0)", event: &pleg.PodLifecycleEvent{ID:"7cffb642-1d92-11e6-a9d1-1402ec3ed5c0", Type:"ContainerDied", Data:"d5e3d8e277c7f059347d16ebc756c00846920d57df202f71c491a3e8441f6736"}
	I0520 01:59:45.279917   32133 kubelet.go:2448] SyncLoop (PLEG): "busybox_default(7cffb642-1d92-11e6-a9d1-1402ec3ed5c0)", event: &pleg.PodLifecycleEvent{ID:"7cffb642-1d92-11e6-a9d1-1402ec3ed5c0", Type:"ContainerStarted", Data:"24e6b03e9c95a731b89c8a0389109a07399fa24beba1735326f7fc36deabba1d"}
	I0520 02:00:03.640006   32133 helpers.go:101] Unable to get network stats from pid 58278: couldn't read network stats: failure opening /rootfs/proc/58278/net/dev: open /rootfs/proc/58278/net/dev: no such file or directory
	I0520 02:00:18.083230   32133 helpers.go:101] Unable to get network stats from pid 58278: couldn't read network stats: failure opening /rootfs/proc/58278/net/dev: open /rootfs/proc/58278/net/dev: no such file or directory
