### ISSUE TITLE
Remove handling of old non-capitalized event reason in scheduler-predicates test

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16165]
This issue should not be pursued until we want to break compatibility with `v1.0` components.

This test behavior was added in #15948 as part of the `1.1` rollout to maintain backwards compatibility with `1.0` (issue #15806).

See [@gmarek's comment](https://github.com/kubernetes/kubernetes/issues/15806#issuecomment-149569269) and below for further explanation.

**Comment by timothysc** [comment]
@balajismaniam care to evaluate this one?
