### ISSUE TITLE
jenkins pr builder needs to lock parallel calls to `gcloud components update`

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#16205]
Parallel runs of `gcloud components update` can blind overwrite the `.last_update_check.json`, making it invalid json. Subsequent calls will crash with
```
All components are up to date.
14:06:04 Traceback (most recent call last):
14:06:04   File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 187, in main
14:06:04     _cli.Execute()
14:06:04   File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 592, in Execute
14:06:04     result = args.cmd_func(cli=self, args=args)
14:06:04   File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1223, in Run
14:06:04     resources = command_instance.Run(args)
14:06:04   File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/surface/components/update.py", line 66, in Run
14:06:04     version=args.version)
14:06:04   File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/updater/update_manager.py", line 759, in Update
14:06:04     with install_state.LastUpdateCheck() as update_check:
14:06:04   File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/updater/local_state.py", line 232, in LastUpdateCheck
14:06:04     return LastUpdateCheck(self)
14:06:04   File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/updater/local_state.py", line 658, in __init__
14:06:04     self._LoadData()
14:06:04   File "/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/updater/local_state.py", line 667, in _LoadData
14:06:04     data = json.loads(fp.read())
14:06:04   File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
14:06:04     return _default_decoder.decode(s)
14:06:04   File "/usr/lib/python2.7/json/decoder.py", line 368, in decode
14:06:04     raise ValueError(errmsg("Extra data", s, end, len(s)))
14:06:04 ValueError: Extra data: line 1 column 102 - line 1 column 103 (char 102 - 103)
14:06:04
```

We get around this with other builds by wrapping the call to components update in a subshell with `flock`, but the pr builder skips that step and runs `kube-up.sh` from the built binaries, so updates occassionally break the job.

cc @ixdy

**Comment by ixdy** [comment]
Is there a reason we should just set `KUBE_SKIP_UPDATE=y` for all builds with or without `KUBE_RUN_FROM_OUTPUT`?

**Comment by jlowdermilk** [comment]
Actually, yeah, that should work.

**Comment by jlowdermilk** [comment]
There's another solution here which from talking with the cloud sdk maintainers is the more recommended approach: have every test fetch gcloud tars from gcs, and install gcloud locally in the workspace. That way different tests can't clobber each other and we avoid any update races. The script [already does this](https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L1464) for test gcloud builds, shouldn't be too hard to adapt to do it for all builds, and just fetch from the public release bucket.

**Comment by ixdy** [comment]
I think this is obsolete, since we just have separate Jenkins jobs to update gcloud on each Jenkins VM. @spxtr can confirm.

**Comment by spxtr** [comment]
That's right. We no longer do gcloud updates within each job, but they are done on each slave daily by a Jenkins job. See #18846.

Jenkins is a wonderful cron frontend :)
