### ISSUE TITLE
Add 1.2 to roadmap

### ISSUE THREAD

**Issue by tristanz** [kubernetes/kubernetes#16218]
Currently the releases are ahead of the roadmap, unless there's a better place to get big picture roadmap from now:

https://github.com/kubernetes/kubernetes/blob/master/docs/roadmap.md

@brendandburns

**Comment by bgrant0607** [comment]
Still under discussion, but see:
https://github.com/kubernetes/kubernetes/milestones
https://github.com/kubernetes/kubernetes/wiki/Release-1.2

**Comment by tristanz** [comment]
Thanks, this looks great.
