### ISSUE TITLE
After master upgrade (v1.0->HEAD) DNS doesn't work because default service doesn't work

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#16225]
Looks like we added a name to the kubernetes service port, but we only update the endpoints with the new port name and not the service. This trips up the kube-proxy because it can't find a svcportname mapping from the service to the endpoints.

cc @davidopp @thockin @ArtfulCoder @ihmccreery

**Comment by mikedanese** [comment]
I think this is caused by  #14871

**Comment by thockin** [comment]
Ahh, great catch.  How is it working from head?

**Comment by mikedanese** [comment]
Because it is creating the endpoints correctly initially. What is happening is when the endpoints are incorrect (e.g. they don't have the port name) the controller is not detecting that it needs to fix the endpoints.

**Comment by thockin** [comment]
Aha!  Excellent find.

**Comment by mikedanese** [comment]
You can reproduce this bad state on HEAD by running
```
echo '{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "kubernetes",
        "namespace": "default",
        "labels": {
            "component": "apiserver",
            "provider": "kubernetes"
        }
    },
    "spec": {
        "ports": [
            {
                "protocol": "TCP",
                "port": 443,
                "targetPort": 443
            }
        ],
        "clusterIP": "10.0.0.1"
    }
}' | kubectl replace -f -
```

The kubernetes service will become unavailable and will not recover. Proposed fix in #16227

**Comment by ravilr** [comment]
@mikedanese https://github.com/kubernetes/kubernetes/pull/14871 is only on master. wondering how could it break v1.1.

**Comment by mikedanese** [comment]
@ravilr hmm you are right. Fixed title.

**Comment by mikedanese** [comment]
Lowering priority and moving out of v1. As @ravilr pointed out, this incompatibility was introduced after v1.1 was cut.

**Comment by mikedanese** [comment]
Need to evalute if #15791 fixes this

**Comment by mikedanese** [comment]
#15791 fixed this.
