### ISSUE TITLE
How to access Kubernetes service from pods started via /etc/kubernetes/manifests?

### ISSUE THREAD

**Issue by eliaslevy** [kubernetes/kubernetes#16230]
It appears that pods started by dropping a pod spec into `/etc/kubernetes/manifests` are not associated with the default service account, and don't have `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` and `/var/run/secrets/kubernetes.io/serviceaccount/token` mounted within their container.  Adding `{spec: {serviceAccount: guest}}` appears to have had no effect on this.

How is a pod started via the manifest directory supposed to authenticate with the kubernetes service?

**Comment by mikedanese** [comment]
May I ask what your usecase is? Will a DaemonSet work?

**Comment by eliaslevy** [comment]
Use case is to execute a command on node registration to update node tags with provider metadata so that nodes in a heterogenous cluster can be targeted.  Specifically, adding AWS metadata to tags.  A pod is only needed until the #13524 proposal is implemented.

I have not dug into DaemonSet as I am using v1.0.6.  Looking it over, DaemonSet could work, if it respects the restart policy (i.e. don't restart), although the guarantees for launch ordering may be too weak (no guarantee that DS pods will start before other pods).  This seems a job for the manifests directory.

I've figured out I can use the kubelet's worker certificate to authenticate to the kubernetes service, so I just need to mount the service's certificate, and the workers cert and key inside the container.  That said, having the SA secret and ca.crt auto mounted would be easier.

**Comment by mikedanese** [comment]
Ya DaemonSet won't work. You can create a RestartOnFailure pod and write the spec.nodeName field to be a node name of a node you want to bootstrap. This will bypass the scheduler and place the pod directly on that node. It would be a normal pod so volumes/service accounts would work. Have it do whatever it needs to do and exit zero. Run that same pod to success on every node in the cluster.

**Comment by eliaslevy** [comment]
I could do that, but it would defeat the purpose of nodes self-registering their metadata labels without requiring some external process that iterates over the nodes.  If that were the only choice, then I might as well run a script that iterates over the node instances, use the AWS CLI to fetch the instance metadata and use kubectl to update the labels, which saves me the trouble of having to define a container image and placing it on a registry.

In any case, I think I can do it by using the kubelet client certificate and mounting it into the container.  I'll test that later today.

**Comment by eliaslevy** [comment]
For the record, dropping a pod into the manifest directory and using kubelet's client cert worked.  Closing.
