### ISSUE TITLE
Tutorial says `kubectl expose` will return assigned IP address of service, but actually doesn't

### ISSUE THREAD

**Issue by abevoelker** [kubernetes/kubernetes#16239]
I'm a noob following [the tutorial](http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html), and when I get to the "Expose it as a service" section, the output of `kubectl expose` doesn't output the IP address like the tutorial says it will.

I figured out how to get the assigned IP address by doing `kubectl get services` afterward, but I'm thinking either the tutorial needs to get updated or the kubectl command (or service it's using) needs to be fixed.

![screenshot from 2015-10-24 13 30 28](https://cloud.githubusercontent.com/assets/153459/10712048/ae4a652e-7a53-11e5-98bf-30a78b22bff6.png)

**Comment by janetkuo** [comment]
Thanks for submitting this issue. It's a known issue (refer to #10836) and the output of `kubectl expose` has been changed by its fix. We'll update the tutorial.
