### ISSUE TITLE
Find out a way to use git-sync sidecar to replace gitRepo 

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#16247]
Related issue:  #15421 related PR: #15533

The original discussion is caused by we want to improve gitRepo to support more options like "git clone src target".  Tim @thockin  believes sidecar mode is more suitable for this case, see https://github.com/kubernetes/kubernetes/pull/15533#issuecomment-150880681. Actually, I agree with him, if we can work out something easier to use.

For now, git-sync sidecar is in contrib repo, as a demo to show how sidecar mode works. My opinion is that is not capable enough to replace gitRepo. So here's some problems we hope to address:
1. should we introduce a new volume type to replace gitrepo by using git-sync sidecar?
2. if not, how the git-sync sidecar should be maintained instead of left in contrib repo without any update for months?
3. can we bring up something more generic?
4. which part is user expected to do? which part is our responsibility?

**Comment by resouer** [comment]
@thockin Could you please put your thoughts here?

**Comment by thockin** [comment]
> should we introduce a new volume type to replace gitrepo by using git-sync
> sidecar?

No new volume.  The git-sync container should simply take some args
that tell it from where to sync, how often to refresh, etc.  It then
goes into a loop doing git syncs.  User sets it up with the args
desired, and an emptyDir volume to write into.  It only has one job.

> if not, how the git-sync sidecar should be maintained instead of left in
> contrib repo without any update for months?

Once it works well enough it should almost never need updates, right?

> can we bring up something more generic?

More generic than git sync?

> which part is user expected to do? which part is our responsibility?

We have to present the simplest, cleanest API we can, and let the user
compose it into their pod.  Things we should expose as params:

- where to sync from
- how often to resync (which has to be done atomically)
- credentials for private repos
- what branch or tag or hash
- depth (how many commits back in time)
- any other git args?

We should use --single-branch to optimize transfers.  I think you can
do fast atomic updates by making a hardlink-copy and then git syncing,
but depending on args used that might not work.  Needs
experimentation.

**Comment by bgrant0607** [comment]
See also #831

**Comment by kargakis** [comment]
@thockin SIG that owns git-sync? 
/sig storage ?

**Comment by thockin** [comment]
good enough

**Comment by thockin** [comment]
git-sync has its own repo now, and is open to feature requests.

https://github.com/kubernetes/git-sync
