### ISSUE TITLE
feature request: read-only containers

### ISSUE THREAD

**Issue by stapelberg** [kubernetes/kubernetes#16240]
Docker 1.5 [introduced read-only containers](https://blog.docker.com/2015/02/docker-1-5-ipv6-support-read-only-containers-stats-named-dockerfiles-and-more/). I’ll quote from their release notes:

> By using this capability in combination with volumes, you can make sure containers only persist data where it can be managed in a known location.

I’d like to have kubernetes start all of my containers using `--read-only`, just so that I know there is no data which is stored in temporary storage and then lost when the container is restarted/rescheduled/…

Based on reading https://cloud.google.com/container-engine/docs/spec-schema, I don’t think kubernetes supports a read-only flag for the entire container, only for storage volumes. Hence, I’d like to suggest introducing a read-only flag for the entire container.

What do you think?

**Comment by thockin** [comment]
This sounds reasonable to me, though we need to make clear - does that
include things like /tmp?

**Comment by stapelberg** [comment]
By default, `--read-only` does make `/tmp` read-only as well, yes:
```
$ docker run --read-only -t -i debian:jessie /bin/bash
root@d6841a63502e:/# mount
/dev/mapper/docker-254:0-22831114-d6841a63502ee4a199a353562f23f4c09f8cf6ab7ec81efa280861c105ab15c5 on / type ext4 (ro,relatime,discard,stripe=16,data=ordered)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
/dev/dm-0 on /etc/resolv.conf type ext4 (rw,relatime,data=ordered)
/dev/dm-0 on /etc/hostname type ext4 (rw,relatime,data=ordered)
/dev/dm-0 on /etc/hosts type ext4 (rw,relatime,data=ordered)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
proc on /proc/asound type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/bus type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/fs type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/irq type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,mode=755)
tmpfs on /proc/timer_stats type tmpfs (rw,nosuid,mode=755)
root@d6841a63502e:/# touch /tmp/foo
touch: cannot touch '/tmp/foo': Read-only file system
root@d6841a63502e:/# exit
```

This is how I run nginx (outside of kubernetes, just with docker):

```
/usr/bin/docker run \
  --name frontend \
  --read-only \
  --volume /var/run \
  --volume /var/cache/nginx \
  --volume /media/persistent/nginx/conf.d:/etc/nginx/conf.d:ro \
  --publish 80:80 \
  --publish 443:443 \
  nginx:1
```

When not specifying a host path, a temporary volume will be created. I.e., if you wanted to have /tmp writeable, you’d need to specify `--volume /tmp`. I’m not 100% sure if Kubernetes’ emptyDir volume type is equivalent to that…?

**Comment by thockin** [comment]
It sounds like a reasonable enough feature.

**Comment by hurf** [comment]
So we need a new field in the template? Should the flag work only for containers of for the pod?

**Comment by thockin** [comment]
This is certainly a per-container option.  Interested to see the f t just
works, or if there are wrinkled...
