### ISSUE TITLE
Container cannot perform dns lookups 

### ISSUE THREAD

**Issue by tleyden** [kubernetes/kubernetes#16244]
## Steps to reproduce

* Install Kubernetes via `KUBERNETES_PROVIDER=vagrant curl -sS https://get.k8s.io | bash`
* ssh into kubernetes minion
* Run `docker run -ti --rm centos:7 bash -c 'ping google.com'`
* Get error `ping: unknown host google.com`

Note: I also tried the above by creating a [pod](https://gist.github.com/tleyden/58281e277e932a27863c), but got the same result.

## Setup

* OSX Yosemite
* VirtualBox 5.0.8
* Vagrant 1.7.4
* Kubernetes version: `Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}`

**Comment by thockin** [comment]
Can the VM itself ping google.com?  What is the VM's /etc/resolv.conf ?  What is the container's /etc/resolv.conf?

**Comment by tleyden** [comment]
> Can the VM itself ping google.com? 

Yep

```
[vagrant@kubernetes-minion-1 ~]$ ping google.com
PING google.com (74.125.239.133) 56(84) bytes of data.
64 bytes from nuq05s02-in-f5.1e100.net (74.125.239.133): icmp_seq=1 ttl=63 time=8.56 ms
```

> What is the VM's /etc/resolv.conf

```
[vagrant@kubernetes-minion-1 ~]$ cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 10.0.2.3
options single-request-reopen
options single-request-reopen
[options single-request-reopen repeated many times]
```

where 10.0.2.3 is pingable from the VM.

> What is the container's /etc/resolv.conf?

```
[root@cba057e8bb58 /]# cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 10.0.2.3
options single-request-reopen
options single-request-reopen
[options single-request-reopen repeated many times]
```

where 10.0.2.3 is *not* pingable from the VM.

**Comment by cloudmode** [comment]
Just tried same thing, only with manual setup:download Kubernetes release and extract the archive

OSX Yosemite
VirtualBox 5.0.8
Vagrant 1.7.4
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}

was able to ping google from inside docker.

however kubectl exec busybox -- dig kubernetes.default SRV (in a busybox pod with dig installed) yields an empty response.

kubectl exec busybox -- dig google.com
yields correct A record
;; ANSWER SECTION:
google.com.		299	IN	A	216.58.219.14

but kubectl exec busybox -- dig srv google.com
again yields an empty response.

**Comment by tleyden** [comment]
@cloudmode thanks, that's useful.  Looks like your client version is on v1.0.6 and mine is on v1.0.1.

**Comment by thockin** [comment]
If you can't ping from within the container, I bet the VM itself does not
have proper ip-masquerades set up.

Run `iptables-save` on the VM ?

or if you want to go big, run `iptables -t nat -A POSTROUTING -j
MASQUERADE` and try it again

**Comment by cloudmode** [comment]
Is this related to #16225? Because the port never shows up on the SRV request.

**Comment by tleyden** [comment]
@cloudmode I just tried it using the binary release instead as you suggested, and couldn't reproduce the problem!

I'll go back and try the original steps and try to reproduce with those again, which I think I can because I tried it twice and got the same result each time.

**Comment by tleyden** [comment]
I'm no longer able to reproduce the issue (using the steps in the original comment, after several tries)  Unfortunately my original broken environment is now lost, so I can't provide any more debugging details.

I'm just going to close the ticket for now, but will re-open if I manage to see it again.
