### ISSUE TITLE
NotReady node keeps getting requests

### ISSUE THREAD

**Issue by chenfisher** [kubernetes/kubernetes#16257]
I've seen this in two, unrelated clusters:
1. Node becomes NotReady (for no apparent reason)
2. Requests to a service (of type LoadBalancer) are still routed to that node

**Cluster 1**
Two nodes, one became NotReady
A service of type LoadBalancer
Every second request to the service times out
Termination of the node resolves the issue

**Custer 2**
7 nodes, one became NotReady
Every 7th request to the service times out
Termination of the node resolves the issue

It seems pods were evicted from the NotReady node

```
kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
```

Using AWS provider

**Comment by lavalamp** [comment]
The service controller makes the load balancers, IIRC. It needs to monitor the nodes and refresh the forwarding rule, similarly to how endpoints controller watches pods for liveness and updates the endpoint list.

**Comment by davidopp** [comment]
@cjcullen Are you planning to look at this? It is assigned to you but hasn't been touched in a couple of months. If not, please unassign.

**Comment by cjcullen** [comment]
Not in the next few weeks. Sorry I missed this. If nobody else gets to it, I'll take a look.

**Comment by quinton-hoole** [comment]
@thockin has opened an issue (number?) to to address the fact that we do not currently configure GCE load balancer health checks.  This is the correct solution to this problem, and is in the domain of the cluster team.  re-assigning.

**Comment by thockin** [comment]
Are these accesses from within the cluster or external?

@freehan has a PR in flight to make pods on a timed-out node disappear
faster.

**Comment by freehan** [comment]
#17741 and #19731 has been merged. Closing this issue...
