### ISSUE TITLE
Kubelet shows error while the pod is run successfully

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#16252]
Hi all,

I am running a single node kubernetes cluster. When I try to run a simple hello-world pod, it is run successfully, I see the status as completed (not exit code:0) and I can using docker command that the container has run successfully. But the kubelet shows error in running pod. Here is the kubelet status:

```
I1026 00:45:51.674454   16863 kubelet.go:914] Node 127.0.0.1 was previously registered
W1026 00:50:04.589761   16863 container.go:326] Failed to create summary reader for "/system.slice/docker-62e3cdcc237e46d72232242f32fd2b5adf0faad2ab798946357d2f2def8f9cc8.scope": none of the resources are being tracked.
W1026 00:50:04.589891   16863 manager.go:984] Failed to process watch event: failed to read libcontainer config: open /var/lib/docker/execdriver/native/62e3cdcc237e46d72232242f32fd2b5adf0faad2ab798946357d2f2def8f9cc8/container.json: no such file or directory
E1026 00:50:04.591135   16863 manager.go:1938] Error running pod "hello-world_default" container "hello": failed to get init PID for Docker container {"docker" "62e3cdcc237e46d72232242f32fd2b5adf0faad2ab798946357d2f2def8f9cc8"}

```

Now, here is the pod status:

```
# ./kubectl create -f ./hello-world.yaml --validate 
pod "hello-world" created
# ./kubectl get pods
NAME          READY     STATUS      RESTARTS   AGE
hello-world   0/1       Completed   0          33s
```

It even shows up in docker logs of the container:

```
# docker logs 62e3cdcc237e

Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/userguide/

```

Any idea why am I getting this error, even when my container is running successfully. And what's the difference between completed and exit code:0? TIA.

**Comment by zhengguoyong** [comment]
completed means pod is running, exit code:0 meas pod terminate success ?
maybe not true.

**Comment by yujuhong** [comment]
@Pensu, the pod has run and terminated successfully as `kubectl get pods` shows.

The errors in the log are misleading and not harmful. Kubelet checks a couple of things after starting the container to make sure the container is running as desired. Because your "hello world" container terminated too quickly, kubelet wasn't able to finish those checks before it died.

**Comment by Pensu** [comment]
@yujuhong Oh, okay, that makes sense. Thank a lot, will close the issue.

**Comment by Pensu** [comment]
Though it would be nice to have kubelet print better messages or logs in these cases.
