### ISSUE TITLE
Cluster size autoscaling doesn't work with master 1.1 and nodes 1.0

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#16268]
In 1.0 nodes don't have specified monitoring scope in GCE. In 1.1 we added cluster size autoscaling feature for GCE which requires utilization/reservation metrics to be exported to GCM by Heapster. Heapster requires monitoring scope to be able to communicate with GCM.

So that cluster size autoscaling feature doesn't work on cluster with master in version 1.1 and nodes in version 1.0.

Ref #16201, #16214

**Comment by piosz** [comment]
cc @aronchick @davidopp @fgrzadkowski @jszczepkowski @mikedanese @mwielgus @vishh

**Comment by fgrzadkowski** [comment]
I think this is a more general problem. There might be some parts of node configuration which are required for system pods to work. Scopes are one examples and especially tricky as they can be created only upon creation. At the same time when we update master we also update all of the add-ons (e.g. heapster). This means that new version of add-ons will work on old nodes.

@bgrant0607

**Comment by fgrzadkowski** [comment]
Some more details:
 - we will not have this problem on GKE as it uses a different mechanism to push metrics to GCM
 - for GCE the question is how do we expect that people will perform cluster upgrades. If the time with different versions is short we might be ok with heapster not exporting metrics to GCM

**Comment by piosz** [comment]
After talk with @fgrzadkowski we ended up with the solution:
* cluster size autoscaling will work only when both master and nodes are in version 1.1
* we will add to the Heapster logic to try to create a sink until it will succeed
* googleinfluxdb monitoring option will remain default (so effectively we will revert #16214)

So in case of update when a master is updated and nodes are not updated yet Heapster will not export autoscaling metrics to GCM and periodically check whether GCM is reachable (nodes have monitoring scope enabled). In this case cluster size autoscaling feature will not work. Then once also nodes are upgraded to 1.1 Heapster will notice that it has access to the GCM and start exporting metrics there.  

WDYT?

**Comment by vishh** [comment]
>cluster size autoscaling will work only when both master and nodes are in version 1.1

I assume this requires upgrading the entire cluster (`kube-push`), which is hopefully not a big issue in GCE.

>we will add to the Heapster logic to try to create a sink until it will succeed

In general, the sink should keep trying to store data without failing hard. AFAIK setting scopes requires creation of new nodes, which will result in heapster being re-started on a new node. From that perspective, this change is not that critical. This will be useful when the monitoring APIs are not turned on though.

> googleinfluxdb monitoring option will remain default

This will break the master only upgrades test that @mikedanese is working on to validate GKE upgrade scenarios.

>So in case of update when a master is updated and nodes are not updated yet Heapster will not export autoscaling metrics to GCM and periodically check whether GCM is reachable (nodes have monitoring scope enabled). In this case cluster size autoscaling feature will not work. Then once also nodes are upgraded to 1.1 Heapster will notice that it has access to the GCM and start exporting metrics there.

FYI: The periodic check will be of no use since scopes cannot be added dynamically.

**Comment by vishh** [comment]
How about this: If a GCE user wants to test cluster auto-scaling, they will have to perform a complete upgrade. 
#16214 already updates the heapster configs (to `googleinfluxdb`) when cluster auto-scaling is turned on. 
I hope kube-push will pick up the config change and update heapster controller appropriately.

**Comment by bgrant0607** [comment]
This feature isn't beta. Can we tell users not to enable cluster autoscaling until after upgrading nodes to 1.1?

**Comment by davidopp** [comment]
+1 to @bgrant0607 's suggestion, I was just about to suggest the same thing.

**Comment by piosz** [comment]
SGTM, closing the issue
