### ISSUE TITLE
Store master and node config in API

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#1627]
Have the master components keep their own configuration in etcd, instead of flags (e.g. ip-per-service introduces a config flag --portal_net)

**Comment by thockin** [comment]
This could also host node config params - renamed to reflect.

**Comment by bgrant0607** [comment]
I'm adamant that we shouldn't do this unless it is also usable by user applications, in which case #1553 and #2068 are relevant.

**Comment by brendandburns** [comment]
I take a more nuanced view on this.  While I agree that in the limit a
general config store is useful, it's a lot more work to build.

There are real, practical things that would make the user's life easier
that we should place into etcd, and allow the kubelet to grab, even in the
absence of a general purpose store.

The prime example of one of these is the .dockercfg for authorization.
It's a pretty bad experience that our recommended approach to auth is:
 "ssh into all the machines and run docker login"

I think we need to balance principle with ease of use and good product
experiences, and especially in the dockercfg case, I think ease of use wins.

--brendan

**Comment by bgrant0607** [comment]
Then just use etcd. Don't create a new API for this.

**Comment by brendandburns** [comment]
No, because we need to make this work via kubectl (and eventually a GUI),
or else its not useful

Brendan

**Comment by thockin** [comment]
And we don't want nodes directly accessing etcd

**Comment by bgrant0607** [comment]
FWIW, there is also etcdctl.

That said, I don't think something generic is a lot more work.

First, create a new API prefix for experimental apis, say `/experimental/v0alpha0`. 

Then, create a Parameters object, which is just contains a map of string to string (using the v1beta3 API conventions).

You can stuff dockercfg and anything else you want into object.

Alternatively, finish the kubelet containerization work, and you'll be able to configure the command line, env vars, and volumes.

**Comment by bgrant0607** [comment]
@thockin It wouldn't have to be the same etcd instance

**Comment by bgrant0607** [comment]
Or call the object RuntimeConfig, similar to https://github.com/smarterclayton/kubernetes/commit/7fd887df61f890e8d39f6f10624074a0b5e8323f

**Comment by bgrant0607** [comment]
Actually, forget the experimental api prefix for this. I'm confident enough that it will be generally useful that I'm willing to put it in v1beta3.

**Comment by davidopp** [comment]
> First, create a new API prefix for experimental apis, say /experimental/v0alpha0.

> Then, create a Parameters object, which is just contains a map of string to string (using the v1beta3 API conventions).

> Actually, forget the experimental api prefix for this.

Is this different from what was implemented in the commit listed earlier (that was never submitted)?

**Comment by bgrant0607** [comment]
Along the lines of our previous discussion, yes:
```
s/MasterFlags/RuntimeConfig/g
s/CmdLineArg/Parameters/g
```
Ideally, we'd also finish the work on generic rest objects in #2594, but we could use your previous PR (#2558) as a starting point -- it looks like we could just reopen it.

**Comment by thockin** [comment]
Is there new urgency to this issue?  We have new people coming on board
soon.

**Comment by bgrant0607** [comment]
I think it's a combination of node-level concerns (rather than master): the dockercfg issue, simplifying cluster bringup, eliminating salt, and dealing with cluster upgrades.

**Comment by davidopp** [comment]
Do we really have a realistic chance of getting rid of Salt any time soon (e.g. next 3 months)? The latest I heard from Joe was that we can reduce it but wouldn't be able to get rid of it in that time frame. (I don't remember the details.) If we have Salt then I think distributing configs (for the regular case and for upgrades) isn't a problem, right?

**Comment by thockin** [comment]
I cry a bit every time I have to touch the salt, but it is a capable enough
system.

**Comment by pmorie** [comment]
I know I'm late to the party here, forgiveness please.  Is this an accurate summary of the concerns / needs for this issue?

1.  There should be a mechanism that allows master components to query the API server for their configuration parameters
2.  The mechanism should be also be usable by users of kubernetes for their own purposes and should not encourage bad behavior from users
3.  The resource for storing parameters should be agnostic of how the data is presented to consumers; consumption use-cases might be:
    1.  Query the API server and consume the parameters in an arbitrary manner in-process
    2.  Kubelet injects env vars for parameters into pods
    3.  Kubelet injects parameters into pods via a sidecar container with an `EmptyDir` volume
    4.  Kubelet injects parameters into pods via some other volume
4.  The mechanism / resource for 'non-secret' parameters should not conflict with that for secrets
5.  There should be a way for consumers of parameters to be notified of changes or (legacy case) restarted on change

**Comment by pmorie** [comment]
@thockin @bgrant0607 @brendanburns

**Comment by smarterclayton** [comment]
I'd probably add 6. The mechanism for storing "config" should demonstrate it adds value or simplicity above and beyond other "config systems", by either solving the simple case more elegantly than another system, or removing the need for users to adapt existing software to use a new "config system".

The desire is that software that has minimal needs for config should be agnostic / unaware of the type of "config system" that is delivering its configuration.

**Comment by pmorie** [comment]
@smarterclayton I think that is a good req.

**Comment by davidopp** [comment]
I'm not sure. Why can't we have a simple, home-grown config store for internal components, while encouraging users to use whatever off-the-shelf stuff they want? I'm not super-excited about growing the set of dependencies for Kubernetes (i.e. to include some other config system that isn't built-in).

**Comment by pmorie** [comment]
@davidopp A simple home-grown config store is what I personally want; I interpretted @smarterclayton as saying that the solution to this problem has to make it simple to use with existing software rather than forcing users to jump through X, Y, and Z to do it 'the kubernetes way'.

**Comment by thockin** [comment]
I think the adapter layer between "your config is stored in kubernetes" and
"we stuffed it into a bunch of config files in a volume" needs to be
hypothetically possible, but is NOT critical to any rollout.

Getting a config system for kubernetes components that is better than flags
does not need to gate on this config system being ready to use by
cloud-ignorant software.

**Comment by pmorie** [comment]
Agree @thockin.  What's been discussed earlier in this issue (new Parameter resource with `map[string]string`) seems like it would be a good start to iterate on.

**Comment by davidopp** [comment]
Are we going to do this before 1.0? Unfortunately people are coming up with ad-hoc solutions for component config (see for example #4674), and it seems that it would easier if we have our long-term component config solution in place before 1.0 rather than having to transition people over to it post-1.0.

**Comment by thockin** [comment]
Uggh.  Now that we have Secrets - how much incremental work is required to
make this happen?  It feels like "not much"

On Thu, Feb 26, 2015 at 3:12 PM, David Oppenheimer <notifications@github.com

**Comment by bgrant0607** [comment]
I'd be in favor of a secret-like solution.

Also, etcd ACL proposal: https://github.com/coreos/etcd/pull/2242

cc @abhgupta @erictune

**Comment by bgrant0607** [comment]
As part of this, we should eliminate all command-line flags from all our components, switch to a versioned config format with strict backward compatibility rules, and standardize on the approach to such config. For instance, we already have kubeconfig and the scheduler config.

**Comment by thockin** [comment]
All flags except the flags that tell kubelet where the master is :)

**Comment by bgrant0607** [comment]
No, that shouldn't be a flag, either. What if the apiserver moves? I don't want to have to push a new script / init file / unit file in that case. We also need to be just as careful about compatibility and just as clear with documentation.

Bootstrapping is another discussion.

**Comment by alex-mohr** [comment]
Pragmatically, if all we had left was a flag to kubelet to tell it where its master is (along with its node cert and ...), we'd be much better off.  Let's not require a perfect solution for the next iteration...

**Comment by smarterclayton** [comment]
We had assumed "connect + authorize" config would stay local but everything
else would get sucked up into the cloud.

On Thu, Jul 23, 2015 at 5:01 PM, Alex Mohr <notifications@github.com> wrote:

> Pragmatically, if all we had left was a flag to kubelet to tell it where
> its master is (along with its node cert and ...), we'd be much better off.
> Let's not require a perfect solution for the next iteration...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/1627#issuecomment-124239057>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
Local vs. remote is a separate issue from yaml vs. flag.

**Comment by smarterclayton** [comment]
Fair - we put everything in yaml today - i prefer versioned config as well
in both modes.

On Thu, Jul 23, 2015 at 5:06 PM, Brian Grant <notifications@github.com>
wrote:

> Local vs. remote is a separate issue from yaml vs. flag.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/1627#issuecomment-124240543>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by zmerlynn** [comment]
I'm pretty happy with whatever, as long as (a) we don't spend too long developing it, and (b) the configuration is somehow loadable somehow at cluster startup - I think that's how to solve the deployment issue as well. Then a cloud provider pod can just pull the desired configuration and reconcile.

**Comment by bgrant0607** [comment]
For reference:
Kubeconfig: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/clientcmd/api/v1/types.go
Scheduler config: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/plugin/pkg/scheduler/api/v1/types.go

**Comment by bgrant0607** [comment]
See other discussion on #6245, #6477, and #10982.

**Comment by derekwaynecarr** [comment]
So I am interested in knowing if the api server just supports a config-source that is writeable via some other API, or if I should be editing the master/node config via the api-server itself.

I would like to be able to do the following (this may be too advanced):

1.  modify admission control flags without restart
2.  register a kind -> []initializers if/when we have that concept (trying to find time to write spec)

**Comment by smarterclayton** [comment]
Although I think requiring a restart to pick up config has good
characteristics (forces you to deal with rolling updates, focuses on the
exact config state, reduces the amount of scenarios to test around config
changes) independent of whether they're stored in the API - enough to not
assume that the point of it being in the API is to do it without restart
(although some people might).

On Wed, Jul 29, 2015 at 3:00 PM, Derek Carr <notifications@github.com>
wrote:

> So I am interested in knowing if the api server just supports a
> config-source that is writeable via some other API, or if I should be
> editing the master/node config via the api-server itself.
>
> I would like to be able to do the following (this may be too advanced):
>
>    1. modify admission control flags without restart
>    2. register a kind -> []initializers if/when we have that concept
>    (trying to find time to write spec)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/1627#issuecomment-126059659>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
#12245 is for converting components to use config files. This remains for using the new config API (#1553) for our components. #2068 is for integrating support for third-party config management tools.

**Comment by bgrant0607** [comment]
For comparison, a Mesos/Marathon configuration example: http://blog.codeship.com/one-command-to-mesos-with-docker-compose/?utm_source=twitter_edgar&utm_medium=tweet&utm_campaign=Docker

**Comment by davidopp** [comment]
I hope we end up with something as simple...

**Comment by karlkfi** [comment]
Using docker-compose to launch kubernetes should already be possible with the existing command-line arguments. We're already doing that with the mesos/docker cluster. The only advantage Mesos has in that area is the ability to specify config as environment variables instead of params. 

I've had on my TODO list to backport our mesos/docker cluster to vanilla k8s. It would be relatively easy, having done all the hard work already. 

There are a few caveats tho:

If you run the kubelet in a container it either needs access to the external docker daemon (docker socket mount) or to run its own docker daemon (privileged mode and [docker-in-docker](https://github.com/jpetazzo/dind)).

Using an external docker daemon is tempting, but presents some complications:

1. Volume mount points are namespaced. They wont be the same inside the container as outside.
2. You're effectively escaping the containerization and wont be able to share a docker daemon with another kubelet (fine for multi-machine deployment, bad for local development).
3. The constraints/measurements placed on the kubelet container wont apply to any containers the kubelet launches.

Using docker-in-docker is a compelling alternative, but has its own complications:

1. AUFS doesn't support mounts within mounts. So you have to use OverlayFS (for both inner and outer docker), provide a volume for the mount root, or create a loop device to mount AUFS mounts on. I've backported my DinD upgrades to support these options (other than using a host volume, which it already supports) with a PR that's not yet merged: https://github.com/jpetazzo/dind/pull/84
2. Your internal docker container IPs wont be accessible on the host unless you allocate space for them on the host docker network. Mesos/Docker does this by [giving each mesos-slave a /24 by default](https://github.com/mesosphere/docker-containers/blob/master/mesos-slave-dind/wrapdocker#L122-L157).

**Comment by davidopp** [comment]
This is marked for 1.1 but IIUC we aren't going to have this in 1.1.

**Comment by bgrant0607** [comment]
Moved to 1.2-candidate.

**Comment by quinton-hoole** [comment]
This idea has been around for 14 months now.  It doesn't seem worthy of a priority 1 label. Dropping priority accordingly.  Please feel free to disagree.

**Comment by smarterclayton** [comment]
I thought we said it was priority for 1.2 to enable bootstrapping but don't have a link

**Comment by thockin** [comment]
This is pretty fundamental - it's enabling for so many issues.

**Comment by mikedanese** [comment]
There are two ongoing efforts scheduled for v1.2 that will allow us to finish this (Component Config and Config Data). Is there any documentation on what the different priorities mean?

**Comment by quinton-hoole** [comment]
Fair enough, back to P1.

**Comment by quinton-hoole** [comment]
@mikedanese No definition of priority's meanings written down anywhere, AFAIK, and I don't think that they're being used consistently across the project.  But they roughly mean the following, in most cases:

P0: Must be actively worked on as someone's top priority right now.  Stuff is burning. If it's not being actively worked on, someone is expected to drop what they're doing immediately to work on it.  TL's of teams responsible for making sure that all P0's in their area are being actively worked on.
P1: Should be staffed and worked on either currently, or very soon, ideally in time for the next release.
P2: Agreed that this would be good to have, but we possibly don't have anyone available to work on it right now or in the immediate future. Hopefully in the future some time we will.  Community contributions would be most welcome in the mean time.
P3:  Probably useful, but not enough support to get it done. Mostly place-holders for potentially good ideas, so that they don't get completely forgotten.

We should probably formalise this into our docs somewhere (this is a P1 :-)

**Comment by thockin** [comment]
Now that we have ConfigMap we need to define schema :)

**Comment by davidopp** [comment]
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/issues.md

**Comment by timothysc** [comment]
Closing this issue in favor of @mikedanese 's longstanding proposal on component config migration.  The kubelet, proxy, and scheduler have been transitioned and other issues have a better scope and history.  @kubernetes/sig-cluster-lifecycle-misc has been tracking the progress of these issues over time.
