### ISSUE TITLE
DNS SRV port lookup fails

### ISSUE THREAD

**Issue by cloudmode** [kubernetes/kubernetes#16284]
The explorer example the DNS look up fails. Even the README.md shows an error:

LookupTXT(elasticsearch-logging):
Result: ([]string)<nil>
Error: &lt;*&gt;lookup elasticsearch-logging: no such host

I've had the same experience in two other installations (one useing Vagrant, the other on DigitalOcean/coreos). In one instance (Vagrant/Mac OSX) the hostname resolved, the port number was always zero in the SRV record.

kubectl exec busybox -- dig kubernetes.default SRV (in a busybox pod with dig installed) yields an empty response. same happens for google, the A record is returned, but no answer section for SRV

kubectl exec busybox -- dig google.com
yields correct A record
;; ANSWER SECTION:
google.com. 299 IN A 216.58.219.14

but kubectl exec busybox -- dig srv google.com
again yields an empty response.

**Comment by w0mbat** [comment]
I also still experience this issue on different cloud providers and it really bugs me because we want to deploy systems like crate as deamonsets and have headless services that serve the SRV records - so far port is always 0.

**Comment by thockin** [comment]
You're kind of using SRV wrong, at least as I understand it.

```
$ dig +noall +answer @10.0.0.10 kubernetes.default.svc.cluster.local SRV
kubernetes.default.svc.cluster.local. 30 IN SRV	10 100 0 c88f1059.kubernetes.default.svc.cluster.local.
```

This demonstrates that there is a record present, but you're right that the port is 0.  This is because any service can have multiple ports.  Which port should be the one that we put here?  Instead, you need to ask for ports by name.

```
$ dig +noall +answer @10.0.0.10 _https._tcp.kubernetes.default.svc.cluster.local SRV
_https._tcp.kubernetes.default.svc.cluster.local. 30 IN	SRV 10 100 443 kubernetes.default.svc.cluster.local.
```

There was some argument that the "first" port should be the one listed in the naked SRV record, but by my reading of RFC, I think that's sketchy usage anyway.

**Comment by thockin** [comment]
@girishkalele FYI

**Comment by w0mbat** [comment]
@thockin Thanks for clearing that up! Of course I understand, that services with multiple ports can´t expose multiple ports in an SRV record.
As my service exports one port, I thought that it would automatically use the one port as default in the SRV.

I also think that choosing the first port once multiple ports are defined feels wrong.

**Comment by thockin** [comment]
The reason I don't want to special-case a single port is this:

- You start with one port
- SRV works
- You build apps around it
- You add a second port
- SRV stops working
- Your app breaks and you blame me (rightly)

Better to say "this is too loose, please be more precise", I think.

**Comment by thockin** [comment]
I'm going to close this for now, please reopen if you think more is needed.

**Comment by roldancer** [comment]
Hi All, From the compatibility perspective, Kubernetes should support all DNS's SVR format, I mean old and new.

**Comment by thockin** [comment]
I'm not clear what you mean.  Can you tell me exactly what you think should
be supported that isn't?
