### ISSUE TITLE
e2e tests fail on coreos/gce

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#16289]
Run the [kubernetes-pull-build-test-e2e-gce](https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L262) against a gce cluster that uses coreos image at node. See several failures.

artifacts here:
https://console.developers.google.com/project/coreos-gce-testing/storage/browser/kubernetes-coreos-jenkin/pr-log/kubernetes-pull-build-test-e2e-gce/73/?pli=1

**Comment by yujuhong** [comment]
@yifan-gu, I don't have permission to view the artifact :\

**Comment by yifan-gu** [comment]
@yujuhong How about this one? 
https://console.developers.google.com/storage/browser/kubernetes-coreos-jenkin/pr-log/kubernetes-pull-build-test-e2e-gce/75/

But seeing more failures now...

**Comment by yujuhong** [comment]
@yifan-gu, I can see the artifacts now but the logs don't match....

The build log shows
```
NAME                     LABELS                                          STATUS    AGE
pull-e2e-0-minion-058k   kubernetes.io/hostname=pull-e2e-0-minion-058k   Ready     40s
pull-e2e-0-minion-c6oz   kubernetes.io/hostname=pull-e2e-0-minion-c6oz   Ready     43s
pull-e2e-0-minion-i6iu   kubernetes.io/hostname=pull-e2e-0-minion-i6iu   Ready     45s
pull-e2e-0-minion-ji3y   kubernetes.io/hostname=pull-e2e-0-minion-ji3y   Ready     36s
pull-e2e-0-minion-sw9c   kubernetes.io/hostname=pull-e2e-0-minion-sw9c   Ready     44s
pull-e2e-0-minion-xzyo   kubernetes.io/hostname=pull-e2e-0-minion-xzyo   Ready     42s
```

Node names from the kubelet.log files:
```
pull-e2e-0-minion-3tbr
pull-e2e-0-minion-svgn
pull-e2e-0-minion-6o5j
pull-e2e-0-minion-nr30
pull-e2e-0-minion-t1x2
pull-e2e-0-minion-qkwl
```

Are they from different builds?

**Comment by yifan-gu** [comment]
It's wired, the artifacts are not updated... Let me check..
