### ISSUE TITLE
API server instrumentation only works for successful responses

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#16282]
API server request instrumentation is right the way down the filter chain. This means that only `200`s are actually reported in metrics.

Need to find the appropriate place to instrument requests to ensure consistent metrics for all requests regardless of response codes or other filters such as authn/authz.

/cc @jayunit100

**Comment by jayunit100** [comment]
Yup as discussed. Will patch this today

**Comment by jimmidyson** [comment]
This isn't as simple as it appears... discussed with @liggitt & has to be carefully thought about due to multiple filter layers both in go-restful container & standard `http.HandlerFunc`s wrapping the requests at different points.

**Comment by jayunit100** [comment]
yup, by patch I really should have said "will take a look" :).
