### ISSUE TITLE
e2e test for GCE "metadata" being resolvable

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#16307]
We need to validate that we can resolve the "metadata" host on GCE/GKE (and possibly AWS?) from inside a container.

**Comment by bgrant0607** [comment]
See also #8867. Eventually we'll need to lock this down. 
cc @thockin

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by spiffxp** [comment]
This sounds like it'd belong to the non-existent sig-cloud.  In the interim, I'm not sure, so I'm tagging with the same sigs as the linked issue.

/remove-sig testing
/sig auth
/sig network
/sig node
/sig service-catalog

/area platform/gce

**Comment by liggitt** [comment]
unclear how this interacts with https://github.com/kubernetes/kubernetes/issues/8867

**Comment by bgrant0607** [comment]
Closing in favor of #8867
