### ISSUE TITLE
Some paths through conversion call defaulting functions twice

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16310]
Not a correctness problem until you start doing unusual things with conversion/defaulting functions.

Compare:

https://github.com/kubernetes/kubernetes/blob/master/pkg/conversion/converter.go#L499

And:

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/conversion_generated.go#L4897

Mostly I think it's just confusing that both the converter and the auto-generated functions call defaulting.

@wojtek-t @yujuhong

**Comment by yujuhong** [comment]
FYI, I removed the defaulting in the converter in #16080.

**Comment by wojtek-t** [comment]
There was some reason why I added defaulting functions to auto-generated stuff, but to be honest I can't remember why (but I think it didn't work without them).

**Comment by yujuhong** [comment]
Update: I decided not to remove the defaulting in #16080 and took a different route.

As @thockin mentioned, eventually we may want to decouple defaulting and conversion. In addition, it's hard to enforce calling defaulting functions in *every* custom conversion function.

**Comment by lavalamp** [comment]
Yeah, I suspect it's doubled because not all paths call it twice, but we should really figure that out.

**Comment by wojtek-t** [comment]
>
Yeah, I suspect it's doubled because not all paths call it twice, but we should really figure that out.

I think that's true. We should pay attention to it when we will be rewriting code-generator of conversions to the new framework.

**Comment by smarterclayton** [comment]
Fixed now.
