### ISSUE TITLE
Adding TypeMeta to top-level unversioned types

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#16321]
Forked from the discussion in #16082.

Currently most top-level types in pkg/api/unversioned/ do not have TypeMeta, we made them so because we don't want the unversioned types to have an `APIVersion` field. However, it would be beneficial to let these types have the `Kind` field, (quoting @liggitt's https://github.com/kubernetes/kubernetes/pull/16082#issuecomment-151233217), because the `Kind` field
1. Identifies the target struct so a codec can deserialize correctly
2. Prevents decoding garbage JSON as an empty struct of a different kind (for example, we wouldn't want `{"foo":"bar"}` to successfully deserialize to a `Status` object)
3. Allows the codec to implement `Decode` (which your `JSONDecoder` cannot, because it has nothing to use to recognize the target kind)

So the proposal is adding a TypeMeta to the top-level unversioned types, and we should populate the `Kind` field but leave the `APIVersion` field empty.

Comments are welcomed.

@liggitt @deads2k @smarterclayton @lavalamp @bgrant0607

**Comment by liggitt** [comment]
The ones that are top level response objects (Status) already have typemeta. Not all the types need them, only the top level ones.

**Comment by liggitt** [comment]
The API should not return untyped responses. Currently, the 1.1 branch is for APIVersion responses. We should add the kind to these asap to prevent clients from having to jump through hoops to handle these responses.

**Comment by caesarxuchao** [comment]
@liggitt thanks, I added the word "top-level" as appropriate. And you are right that Status already has TypeMeta.

**Comment by lavalamp** [comment]
@bgrant0607 

@caesarxuchao if we do this, we want the apiVersion field to be absent, I think (instead of present and set to "", for example). 

@liggitt The whole point of at least some of these types is that they will remain constant across versions, so that old clients & new clients will both work against old and new servers. So I guess I'm not convinced this is really urgent.

**Comment by caesarxuchao** [comment]
One thing that may be annoying is the jsonCodec may have to stay there forever if we don't make the discovery API typed in v1.1. On the other hand, APIVersions is not typed in v1 release, so we need special handling for that anyway.

**Comment by liggitt** [comment]
/apis isn't in a released version yet, right (1.1 will be the first)? If so, it would make the discovery process far cleaner if we could actually use normal client/codec paths to decode that response. `/api` has to handle untyped responses for compatibility with 1.0, but given that foreseeable future versions will be building under /apis, don't we want to shape it like we want it from the beginning?

**Comment by lavalamp** [comment]
Reducing to p1 since the cherry pick has already merged.
