### ISSUE TITLE
Logging Docs Dedup

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#16326]
Merge docs/getting-started-guides/logging.md into other documents.
- We already tell the admin that logging is a cluster component in docs/admin/cluster-components.md
- We tell users how to access logs in docs/user-guide/logging.md
- We tell people who are setting up a cluster from scratch that they should setup logging in docs/getting-started-guides/scratch.md.
- We automatically start logging now in our supported startup scripts.
- We keep the maintained/tested replication-controllers for logging in https://github.com/kubernetes/kubernetes/tree/HEAD/cluster/addons/fluentd-elasticsearch.  (Could do with a readme in that directory).

I think the content in  docs/getting-started-guides/logging.md and https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/logging-elasticsearch.md needs to be merged into those other files mentioned above.
The docs/getting-started-guides/logging.md screenshots on GCP should maybe be replaced with Google maintained pages.

**Comment by erictune** [comment]
The content in
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/logging.md
is out of date since it does not even mention  https://cloud.google.com/logging/docs/, and should.

@MikeJeffrey is there any cloud.google.com documentation for logging which is specific to the GKE use case?

**Comment by bgrant0607** [comment]
See also #16938.

**Comment by bgrant0607** [comment]
There's also:
https://github.com/kubernetes/contrib/tree/master/logging

and #14170

We've had some people request instructions for setting up other third-party solutions, also, such as sysdig, datadog, and newrelic.

https://github.com/kubernetes/kubernetes/tree/master/examples/newrelic

It would be useful to put this all into one guide or set of guides.

**Comment by bgrant0607** [comment]
Sorry, those are monitoring solutions, but the same comment holds for logstash, etc.

**Comment by bgrant0607** [comment]
Should be covered by the doc overhaul.

https://docs.google.com/document/d/12Nfj2E8tZL-CMnnpkSH9m5k_oqd4qJh4qDwYDxPGJJI/edit?ts=5705b1fc#

cc @kubernetes/docs

**Comment by piosz** [comment]
cc @Crassirostris @aleksandra-malinowska

**Comment by Crassirostris** [comment]
Addressed (if not fixed) by https://github.com/kubernetes/kubernetes.github.io/pull/1837

**Comment by piosz** [comment]
All changes to logging documentation are merged now
