### ISSUE TITLE
gh-pages importer gets wrong title when importing from master

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#16334]
Our markdown files have

```markdown
<strong>
The latest 1.0.x release of this document can be found
[here](http://releases.k8s.io/release-1.0/docs/api.md).

Documentation for other releases can be found at
[releases.k8s.io](http://releases.k8s.io).
</strong>
--
```

that is stripped out in release branches. When importing from master, this is still there and -- fools the importer into thing that the first header is `</strong>` and should be the title. The import.sh script in gh-pages strips this after importing them.

This may not be a major issue as we shouldn't really import docs from master.

**Comment by bgrant0607** [comment]
Obsolete.
