### ISSUE TITLE
BUG: Replication Controllers Break when Created With Already Used Template Config

### ISSUE THREAD

**Issue by waprin** [kubernetes/kubernetes#16333]
Created a replication controller.

Then I created another one, using the same "name" and "label" in the spec template metadata. kubectl did not prevent this or warn/error, but the newly created RC does not have its pods come up, and can't be deleted directly (kubectl hangs). In general, the cluster starts behaving badly and breaks.

Easily reproduced.

kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}

First JSON:
```json
{
    "metadata": {
        "name": "test1"
    },
    "apiVersion": "v1",
    "kind": "ReplicationController",
    "spec": {
        "template": {
            "metadata": {
                "name": "jenkins-php-slave",
                "labels": {
                    "role": "slave",
                    "language": "php"
                }
            },
            "spec": {
                "containers":[
                    {
                        "name": "jenkins-php-slave",
                        "image": "waprin/php55-jenkernetes-slave",
                        "imagePullPolicy": "Always"
                    }
                ]
            }
        }
    }
}
```

Second JSON:
```json
{
    "metadata": {
        "name": "test2"
    },
    "apiVersion": "v1",
    "kind": "ReplicationController",
    "spec": {
        "template": {
            "metadata": {
                "name": "jenkins-php-slave",
                "labels": {
                    "role": "slave",
                    "language": "php"
                }
            },
            "spec": {
                "containers":[
                    {
                        "name": "jenkins-php-slave2",
                        "image": "waprin/php55-jenkernetes-slave",
                        "imagePullPolicy": "Always"
                    }
                ]
            }
        }
    }
}
```

@thesandlord

**Comment by thesandlord** [comment]
Additional Info:

The new rc behaves very strangely. It creates successfully, but it can't create pods. If you try to scale it, kubectl hangs but the rc reports that it has that many replicas running (which is not true). If you try to delete it, it scales to zero but just hangs and does not delete.

We were able to workaround by doing a ```kubectl delete rc --all``` to wipe the system and then recreate all the previous controllers, but this is a really bad workaround.

**Comment by mikedanese** [comment]
This is expected behavior and we consider the case of overlapping controllers user error. The first created rc takes precedence. You can delete the second RC by running `kubectl delete rc --cascade=false test2`. What did you expect to happen?

cc @bprashanth @davidopp

**Comment by mikedanese** [comment]
Also see #2210, specifically https://github.com/kubernetes/kubernetes/issues/2210#issuecomment-135588169

**Comment by waprin** [comment]
Yes, I expected client-side validation. The problem is that my whole cluster seems to be in a broken state, given that I am creating RCs that are not correctly spinning up pods, even after I delete and re-create all my RCs. It works in a brand new cluster. Unfortunately I am having trouble reproducing the issue, so I am having trouble tying it to a specific problem. But it started after I made this mistake, and it seemed weird kubectl wouldn't prevent me from doing an operation that broke my cluster. But I haven't gotten to the bottom of the RC issue.

**Comment by mikedanese** [comment]
No overlap validation is #2210, and it's a bit tricky which is why it has not been implemented yet.

**Comment by mikedanese** [comment]
Dup of #2210
