### ISSUE TITLE
Cluster shutdown "events"

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#16337]
I'd like to delete certain external resources (loadbalancers) only when the cluster is being torn down. Not when the user deletes the pod, or the scheduler preempts it. Currently scripts like kube-down aren't kubernetes aware, they just start nuking cluster resources using gcloud, meaning the following happens:

``` console
$ ./cluster/kube-up.sh

$ cat <<EOF | kubectl create -f -
> apiVersion: v1
> kind: Service
> metadata:
>   name: nginxsvc
>   labels:
>     app: nginx
> spec:
>   type: LoadBalancer
>   ports:
>   - port: 8080
>     targetPort: 80
>     protocol: TCP
>     name: http
>   - port: 443
>     protocol: TCP
>     name: https
>   selector:
>     app: nginx
> EOF

$ kubectl get svc
NAME         CLUSTER_IP    EXTERNAL_IP      PORT(S)            SELECTOR    AGE
kubernetes   10.0.0.1      <none>           443/TCP            <none>      2m
nginxsvc     10.0.104.32   104.154.47.133   8080/TCP,443/TCP   app=nginx   1m

$ gcloud compute forwarding-rules list 
NAME                        REGION      IP_ADDRESS      IP_PROTOCOL TARGET
a5653a6897c4311e5bf0242010af0000 us-central1 104.154.47.133  TCP         us-central1/targetPools/a5653a6897c4311e5bf0242010af0000

$ ./cluster/kube-down.sh
Done

$ gcloud compute forwarding-rules list
NAME                        REGION      IP_ADDRESS      IP_PROTOCOL TARGET
a5653a6897c4311e5bf0242010af0000 us-central1 104.154.47.133  TCP         us-central1/targetPools/a5653a6897c4311e5bf0242010af0000
```

Having at least the following guarantees when there's a pending shutdown will make life a little easier:
1. Deny new resource create requests
2. Notify existing services/controllers/pods

@thockin

**Comment by thockin** [comment]
@bgrant0607 @brendandburns @smarterclayton

**Comment by bgrant0607** [comment]
Related #4630

cc @davidopp @fgrzadkowski @roberthbailey @zmerlynn

**Comment by bgrant0607** [comment]
It's the pod (LB plugin?) that creates the forwarding rule?

**Comment by bgrant0607** [comment]
Ideally there would be some Kubernetes resources that represented the underlying infrastructure resources, such that deleting the former would cause the latter to be deleted.

**Comment by bgrant0607** [comment]
See also #13515

**Comment by bprashanth** [comment]
My example was with a HEAD kube cluster, so it's the service controller (that runs as part of kube-controller-manager) that creates the forwarding rule for service Type=LoadBalancer, not the L7 LB plugin pod.

**Comment by zmerlynn** [comment]
Yes, GKE still really wants this. It's a pretty big wart.

**Comment by bprashanth** [comment]
> Ideally there would be some Kubernetes resources that represented the underlying infrastructure resources, such that deleting the former would cause the latter to be deleted.

Just receiving a delete is insufficient, I need to differentiate that SIGTERM from a preemption in the case of a pod controller. A new field as suggested in some of the other issues might help, because I can use the grace period to check it in the apiserver.

**Comment by bprashanth** [comment]
Another possible solution would be to map the "Steps" in the simple cluster setup proposal (https://docs.google.com/document/d/1v68yStV2O6aHuRuT3AlWnbe6vkUCtzyC5I7Elhgik3o/edit?ts=561ee618) to runlevels persisted through the apiserver, and add a shutdown level just like init systems, hence the title.

**Comment by thockin** [comment]
Naively, deleting the Ingress object should trigger the controller Pod to
clean up the backend resources.  But that requires some heuristic like
"pods are deleted last" and even then it has to be across namespaces.

**Comment by bgrant0607** [comment]
Re. pods deleted last: Another use case for finalizers. #3585

**Comment by davidopp** [comment]
Also vaguely related to #7459

**Comment by davidopp** [comment]
@bprashanth I'm marking this P2 but feel free to upgrade to P1 if you think it's higher priority.

**Comment by bgrant0607** [comment]
Also related to #10179

**Comment by bgrant0607** [comment]
Note that new resources cannot be created in namespaces that are being deleted:
https://github.com/kubernetes/kubernetes/blob/e02b73ff67dd2dbaab18d1c959d9b58de21d415a/plugin/pkg/admission/namespace/lifecycle/admission.go#L162

And we already treat the default and kube-system namespaces specially (and openshift-infra in OS):
https://github.com/kubernetes/kubernetes/blob/e02b73ff67dd2dbaab18d1c959d9b58de21d415a/plugin/pkg/admission/namespace/lifecycle/admission.go#L53

**Comment by bgrant0607** [comment]
For my own reference: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-loadbalancing/glbc

**Comment by tonglil** [comment]
Should this issue be consolidated with something else, or kept open for the tear down of GCLB resources?

**Comment by bgrant0607** [comment]
/remove-lifecycle stale
/lifecycle frozen

cc @roberthbailey
