### ISSUE TITLE
kubelet not able to update status

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#16353]
Hi all,

I am trying to run kubernetes cluster with docker. I am building everything from scratch. I built kubernetes and then ran the services one by one. Now, when I run kubelet, it runs properly, I am able to spawn a pod, it goes into running state, but after some time, kubelet dies and pod goes into pending state. I get this from kubelet logs:

```
E1027 04:55:44.789086   24796 kubelet.go:2246] Error updating node status, will retry: node "127.0.0.1" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
I1027 04:55:48.787239   24796 kubelet.go:2255] Recording NodeReady event message for node 127.0.0.1
E1027 04:55:49.968093   24796 kubelet.go:2246] Error updating node status, will retry: node "127.0.0.1" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
I1027 04:57:49.395791   24796 kubelet.go:2255] Recording NodeReady event message for node 127.0.0.1
E1027 05:02:11.258810   24796 kubelet.go:2246] Error updating node status, will retry: node "127.0.0.1" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
```

Now, in this case I restart kubelet and everything goes fine for a while, after which the kubelet dies again. I have to restart it once more. Any idea what could be causing this? Or how can I avoid this? TIA.

**Comment by yujuhong** [comment]
Hi @Pensu, the question has been posted on [stackoverflow](http://stackoverflow.com/questions/33362726/error-running-kubelet-node-not-ready) and are a couple of suggestions in the comments. Please continue the discussion there. Thanks!
