### ISSUE TITLE
Kubelet container bridge creates iptable NAT masq rule with hardcoded IP range

### ISSUE THREAD

**Issue by willmore** [kubernetes/kubernetes#16357]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container_bridge.go#L122-L143
container_bridge.go assumes that the virtual IP of services & pods will be in the `10.` space. 
I propose there is no reason to make this assumption.

As outlined in #15932, cluster admins may need to deploy to hosts in which `10.` is reserved for the nodes. In such a case, Kubelets must support an alternative range.

**Comment by therc** [comment]
I think this is a duplicate of #11204

**Comment by willmore** [comment]
@therc agreed - looks like a dupe. Marking it.
Duplicate of #11204
