### ISSUE TITLE
kubectl logs should permit number of lines to be specified

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#16365]
Tools like `tail` allow one to pass `-n N` to specify that only the last N log lines should be displayed. kubectl logs should support this.

My use case is that I have a very, very long running batch process that has output 10s of millions of lines of logs, but I'm only interested in the last few hundred at any one point in time. However, when I run `kubectl logs ...`, my terminal must spew the full logfile before getting to the end.

**Comment by hurf** [comment]
Which kubectl version are you using? It's already supported now.

# Display only the most recent 20 lines of output in pod nginx
$ kubectl logs --tail=20 nginx

# Show all logs from pod nginx written in the last hour
$ kubectl logs --since=1h nginx

**Comment by jcderr** [comment]
$  kubectl version
    Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
    Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}

**Comment by kargakis** [comment]
kubectl logs supports --tail

@bgrant0607 this is not an issue https://github.com/kubernetes/kubernetes/pull/13780

**Comment by bgrant0607** [comment]
Please update to 1.1.
