### ISSUE TITLE
make a centralized event manager in kubelet

### ISSUE THREAD

**Issue by jiangyaoguo** [kubernetes/kubernetes#16374]
-  Make a centralized event Reason declaration, just as @vishh suggested in #15464. This will be helpful to #14111 and can provide more details about Reason define.
-  Use method like EventManager.Event to replace record.Event in kubelet, which actually calls  record.Event with some hook function, like reason field validation(CamelCase), hide infra container event.
-  Add some component level event through monitoring event stream, like after N PullImageFail or OOMKilled at a time,  record a warn level(#15999) event for kubelet.

It's a original idea.Hope to get some suggestions.

**Comment by ashcrow** [comment]
I'll defer more to @vishh as I'm not that familiar with the event code. However, keep in mind [this caveat](https://github.com/kubernetes/kubernetes/issues/14111#issuecomment-141253380).

**Comment by lavalamp** [comment]
I take the "centralized event reason declaration" to just mean all of the event reasons that *kubelet* exports should be declared in one place. I'm ambivalent about that.

Validating the form of the event reason sounds like an OK thing as long as it's not by looking it up in an explict list; (matching a regexp would be OK, I guess). But no need to limit it to kubelet events.

I'm not really sure about the third suggestion.

**Comment by bgrant0607** [comment]
See also #14541

**Comment by vishh** [comment]
> Make a centralized event Reason declaration, just as @vishh suggested in #15464. This will be helpful to #14111 and can provide more details about Reason define.

This is equivalent to documenting all the existing event reasons to some extent. AS for #14111, I was suggesting aggregating kubelet specific event reasons in a single location. Doesn't require aggregating all the reasons in the kubernetes repo.

> Use method like EventManager.Event to replace record.Event in kubelet, which actually calls record.Event with some hook function, like reason field validation(CamelCase), hide infra container event.

Why hide `infra container` events?

**Comment by jiangyaoguo** [comment]
@vishh See #16091.
