### ISSUE TITLE
Update DNS documentation

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#16371]
In file: docs/admin/dns.md

Reword to say that it is required not optional.

Remove text about issues which are resolved at head.

Mention new record types, if any.

Consider whether user-guide is a better place for this content.

**Comment by thockin** [comment]
@ArtfulCoder small things to clean up

**Comment by spzala** [comment]
@erictune Hi Eric, this seems like a problem of past. I don't see dnd.md file any more. Can you please check if this is still an issue with content that might moved to a diff file? and if it's not an issue any more can we please close it? Thanks!

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by cmluciano** [comment]
Seeing many of these covered now https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
