### ISSUE TITLE
Exec/attach should create all streams before copying data

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#16373]
We create the stdin stream and immediately start copying local stdin to the container. We do the same for stdout and stderr (create stream, start copying immediately). In the kubelet, we wait to receive all the streams before we start the exec and copy between the streams and the container.

The spdy connection frame handling code has 5 frame workers, each with a queue of up to 50 frames. In the event that we try to push more than 50 frames to a single queue before all streams are ready, the 51st attempt to push a frame blocks until there is space available in the queue. But there won't be any space until the server starts reading from the streams, which won't happen until all the streams have been received, so we're stuck at this point.

The fix is to create all the streams first, and only start copying after all the streams have been created and the server is ready to copy between the streams and the container.

Originally reported here: https://github.com/openshift/origin/issues/5377

**Comment by ncdc** [comment]
FYI @lavalamp @liggitt @smarterclayton @csrwng @kubernetes/rh-cluster-infra

**Comment by smarterclayton** [comment]
This seems pretty high priority.

**Comment by ncdc** [comment]
It's an easy fix. @csrwng has already tested the patch for OpenShift and it works. Are we willing to pull it in before #16119 is resolved, as that will take longer to put in place?

**Comment by ncdc** [comment]
Here's the patch, for reference: https://gist.github.com/ncdc/c48645fff8c651ad08d0

**Comment by lavalamp** [comment]
5 * 50 = 250 frames before you get stuck? Or did I misunderstand?

**Comment by lavalamp** [comment]
Oh, I guess all the frames go to the same worker for some reason?

**Comment by lavalamp** [comment]
anyway, I'm fine with taking this and cherry picking it. Order doesn't matter; someone has to rebase either way, right?

**Comment by ncdc** [comment]
@lavalamp frames are assigned to each queue based on stream id, so if you sent > 50 frames to the stdin stream, that queue fills up and the loop that processes incoming frames is blocked until something starts reading from the stream. Working on a PR now.

**Comment by lavalamp** [comment]
Gotcha, thanks.
