### ISSUE TITLE
All PD e2e tests are being skipped in parallel runs.  That's bad.

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#16377]
https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L177

This means that any PR that breaks PD's in any way does not get automatically prevented from merging.  We need to promote at least 1 (ideally more) of the 4 PD e2e tests to run reliably in parallel.

**Comment by quinton-hoole** [comment]
Excluding known, subsequently fixed regressions, the duration and reliability stats for these 4 tests, when run in parallel are as follows:

* Pod Disks should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession: [run time ~5 minutes, Failed 1 of 54 most recent runs](http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-parallel-flaky/7939/testReport/junit/%28root%29/Kubernetes%20e2e%20suite/Pod_Disks_should_schedule_a_pod_w__a_RW_PD_shared_between_multiple_containers__write_to_PD__delete_pod__verify_contents__and_repeat_in_rapid_succession/history/)
* Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host: [run time ~2:30, Failed 0 of 70 most recent runs](http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-parallel-flaky/7939/testReport/(root)/Kubernetes%20e2e%20suite/Pod_Disks_should_schedule_a_pod_w__a_RW_PD__remove_it__then_schedule_it_on_another_host/history/)
* Pod Disks should schedule a pod w/two RW PDs both mounted to one container, write to PD, verify contents, delete pod, recreate pod, verify contents, and repeat in rapid succession [run time ~6 min, Failed 0 of 44 most recent runs](http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-parallel-flaky/7939/testReport/(root)/Kubernetes%20e2e%20suite/Pod_Disks_should_schedule_a_pod_w_two_RW_PDs_both_mounted_to_one_container__write_to_PD__verify_contents__delete_pod__recreate_pod__verify_contents__and_repeat_in_rapid_succession/history/)
* Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both [running time ~2 minutes, Failed 0 of 61 most recent runs](http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-parallel-flaky/7939/testReport/(root)/Kubernetes%20e2e%20suite/Pod_Disks_should_schedule_a_pod_w__a_readonly_PD_on_two_hosts__then_remove_both_/history/)

**Comment by lavalamp** [comment]
@quinton-hoole, this can be closed now, right?

**Comment by quinton-hoole** [comment]
Yup. It should have been auto-closed by my PR, but I must have got the
gihub "fixes" syntax wrong.
