### ISSUE TITLE
Duplicate swagger param name "path"

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#16387]
In the swagger api spec, in the proxy methods:

https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L6670

There are many such entries like this:

```js
       {
        "type": "string",
        "paramType": "query",
        "name": "path",
        "description": "Path is the URL path to use for the current proxy request to pod.",
        "required": false,
        "allowMultiple": false
       },
       {
        "type": "string",
        "paramType": "path",
        "name": "namespace",
        "description": "object name and auth scope, such as for teams and projects",
        "required": true,
        "allowMultiple": false
       },
       {
        "type": "string",
        "paramType": "path",
        "name": "name",
        "description": "name of the Pod",
        "required": true,
        "allowMultiple": false
       },
       {
        "type": "string",
        "paramType": "path",
        "name": "path",
        "description": "path to the resource",
        "required": true,
        "allowMultiple": false
       }
```

As you can see, the name "path" is used twice here. Despite the `paramType` being different, this causes `swagger-codegen` to create invalid code:

```cs
ConnectOptionsNamespacedPodProxy_6 (string _namespace, string name, string path, string path);
```

As the name is there twice, path is a duplicate variable, causing errors.

Although this isn't necessarily a kubernetes issue - duplicate names should be handled properly in swagger-codegen - I think it would be wise to not use the same name twice in these methods.

**Comment by lavalamp** [comment]
@nikhiljindal or maybe @caesarxuchao -- can one of you take this?

**Comment by paralin** [comment]
I think it's more of a bug with codegen than with Kubernetes, but it's a good idea to have a look at making the name fields unique. I'm not too experienced with Swagger but I'm pretty sure they are supposed to be unique.

**Comment by nikhiljindal** [comment]
We recently renamed the path param to `path`.
`swagger-tools validate` does not complain which makes me believe that the spec is correct.

I see that swagger-codegen is being fixed, which seems like the right place to me.

Reducing the priority

**Comment by wing328** [comment]
@paralin @nikhiljindal we've added better logic in Swagger Codegen to handle duplicated parameter names. Please pull the latest and let us know if you're still seeing issue.

**Comment by paralin** [comment]
Works fine for me! @wing328 Thanks.

**Comment by nikhiljindal** [comment]
Actually there was another issue which was masking this issue in swagger-tools validate.
Now that we have fixed the other issue (https://github.com/kubernetes/kubernetes/pull/17990), swagger-tools validate is complaining about the duplicate name.

```
$ swagger-tools validate api/swagger-spec/resourceListing.json api/swagger-spec/api.json api/swagger-spec/v1.json api/swagger-spec/version.json api/swagger-spec/apis.json api/swagger-spec/extensions.json api/swagger-spec/v1beta1.json

  API Declaration (/api/v1) Errors:

    #/apis/60/operations/0/parameters/3/name: Parameter already defined: path
    #/apis/60/operations/1/parameters/3/name: Parameter already defined: path
    #/apis/60/operations/2/parameters/3/name: Parameter already defined: path
    #/apis/60/operations/3/parameters/3/name: Parameter already defined: path
    #/apis/60/operations/4/parameters/3/name: Parameter already defined: path
    #/apis/60/operations/5/parameters/3/name: Parameter already defined: path

6 errors and 0 warnings
```

Filed https://github.com/apigee-127/swagger-tools/issues/307 to discuss the issue with them.
