### ISSUE TITLE
e2e flake: failed to initialize within 300 seconds

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16385]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9151/console

Will raise priority if it happens again. It's very not obvious what went wrong:

```
13:33:13 e2e-gce-minion-group us-central1-f e2e-gce-minion          3           e2e-gce-minion-group e2e-gce-minion-template
13:33:54 Waiting for group to become stable, current operations: creating: 3
13:33:54 Waiting for group to become stable, current operations: creating: 3
13:33:54 Waiting for group to become stable, current operations: creating: 3
13:33:54 Waiting for group to become stable, current operations: creating: 3
13:33:54 Group is stable
13:33:55 MINION_NAMES=e2e-gce-minion-7xe2 e2e-gce-minion-lfwh e2e-gce-minion-pn0v
13:33:56 Using master: e2e-gce-master (external IP: 104.197.149.153)
13:33:56 Waiting up to 300 seconds for cluster initialization.
13:33:56 
13:33:56   This will continually check to see if the API for kubernetes is reachable.
13:33:56   This may time out if there was some uncaught error during start up.
13:33:56 
13:38:58 ......................................................................................................................................................Cluster failed to initialize within 300 seconds.
13:38:58 2015/10/27 13:38:58 e2e.go:309: Error running up: exit status 2
13:38:58 2015/10/27 13:38:58 e2e.go:305: Step 'up' finished in 7m35.927186347s
13:38:58 
2015/10/27 13:38:58 e2e.go:141: Error starting e2e cluster. Aborting.
13:38:58 exit status 1
```

**Comment by alex-mohr** [comment]
I've seen 5+ of various Critical builds failing to due "Cluster failed to initialize within 300 seconds." over the past 2 days.

Found two examples, will add more as I come across them.
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-parallel/10699/
http://kubekins.dls.corp.google.com/job/kubernetes-kubemark-gce/941/

**Comment by davidopp** [comment]
I'm OOO this week, reassigning to @mikedanese

**Comment by alex-mohr** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/727/console

**Comment by mikedanese** [comment]
I'm working on this now. Having some difficulty reproducing on a personal cluster.

**Comment by mikedanese** [comment]
I brought up a cluster many times but was never able to reproduce this.

This is an example of an error that is incredibly hard to debug. kube-up (cluster deploy scripts) run without error to completion but the APIServer never comes up. Jenkins immediatly destroys the cluster. Not a single error is caught and logged. It happens very rarely. kube-dump doesn't run on red bubble builds so no logs from any components.

Optimally, I'd like to get my hands on a cluster in this condition. Second best thing would be better tracing maybe? It'd be nice to get a dump of GCE operations made during the run.

cc @fejta @ihmccreery

**Comment by mikedanese** [comment]
If this happens again please reopen. Seems like it was transient
