### ISSUE TITLE
Unversioned API types should show in swagger

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16395]
...and when we fix this, we should make sure swagger doesn't show an "apiVersion" field for them. See the discussion in #16364.

**Comment by lavalamp** [comment]
@nikhiljindal did we fix this?

**Comment by nikhiljindal** [comment]
Not yet.
cc @caesarxuchao if he can get to this before me.

**Comment by caesarxuchao** [comment]
ref #19018. If we take #19018's approach, then we can let the swagger show the "apiVersion" field.
