### ISSUE TITLE
Seemingly random ordering of JSON properties between the log entry and Cloud Logging

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/kubernetes#16397]
Following along with this example:

https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/getting-started-guides/logging.md

Everything works as expected:

```
0: Tue Oct 27 23:50:22 UTC 2015
1: Tue Oct 27 23:50:23 UTC 2015
2: Tue Oct 27 23:50:24 UTC 2015
3: Tue Oct 27 23:50:25 UTC 2015
4: Tue Oct 27 23:50:26 UTC 2015
5: Tue Oct 27 23:50:27 UTC 2015
6: Tue Oct 27 23:50:28 UTC 2015
7: Tue Oct 27 23:50:29 UTC 2015
```

Until viewing the logs in Cloud Logging. I appreciate that the ordering of JSON properties is not significant but it's curious why the ordering of the properties would vary (seemingly randomly) between entries. In log entry "0", the 'log' property precedes the 'stream' property while in entry "1", stream precedes log. It's minor but curious.

![image](https://cloud.githubusercontent.com/assets/1022400/10776177/5537198e-7ccc-11e5-8560-5b27ac5273e0.png)

My experience seemingly contradicts what I would expect to see which is what's shown in the Cloud Logging screenshots included in the logging document cited above.

**Comment by spiffxp** [comment]
/sig instrumentation

docs have changed since this was filed, I suspect this should be closed

https://github.com/kubernetes/kubernetes.github.io/blob/f4fd9e79edc435b977c9fe37219fe39c67f699b3/docs/concepts/cluster-administration/logging.md

**Comment by crassirostris** [comment]
Yup, it's not valid for a long time already

**Comment by crassirostris** [comment]
@spiffxp Thanks a lot for digging this out!
