### ISSUE TITLE
gh-pages shows red rectangles in code 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#16391]
http://kubernetes.io/v1.1/docs/user-guide/compute-resources.html#resource-requests-and-limits-of-pod-and-container contains weird red rectangles. 

![screenshot from 2015-10-27 15 30 25](https://cloud.githubusercontent.com/assets/4876867/10774636/b1747bcc-7cbf-11e5-870f-4d812328b604.png)

Source code of those red rectangles: `<span class="err">  </span>`

cc @bgrant0607 @RichieEscarez @krousey @caesarxuchao

**Comment by janetkuo** [comment]
In https://github.com/kubernetes/kubernetes/blame/master/docs/user-guide/compute-resources.md those rectangles are generated from `<tab>` (see raw file).

**Comment by bgrant0607** [comment]
That's something else that one of the mungers should do. It's fine to convert tabs to spaces in head, I think.

**Comment by bgrant0607** [comment]
Also see this here:
http://kubernetes.io/v1.1/docs/user-guide/production-pods.html

But actually I don't see it in too many places. It would be good to fix this, but I wouldn't block on it.

**Comment by bgrant0607** [comment]
Not a blocker for 1.1

**Comment by nikhiljindal** [comment]
Since we have found only 2 cases, @janetkuo is going to manually fix the yaml files for now.

**Comment by bgrant0607** [comment]
Tabs in quoted regions:
```
find . -name "*.md" -exec awk 'BEGIN{cr=0;tab=0}/^```/{cr = !cr}/\t/{if (cr) {tab = 1}}END{if (tab) {printf("tab found: ")}}' "{}" \; -print |grep "tab found"
tab found: ./devel/api_changes.md
tab found: ./devel/e2e-tests.md
tab found: ./devel/api-conventions.md
tab found: ./proposals/compute-resource-metrics-api.md
tab found: ./design/security_context.md
tab found: ./design/horizontal-pod-autoscaler.md
tab found: ./design/expansion.md
tab found: ./user-guide/jobs.md
tab found: ./user-guide/horizontal-pod-autoscaling/README.md
tab found: ./user-guide/introspection-and-debugging.md
tab found: ./user-guide/kubectl/kubectl_exec.md
tab found: ./user-guide/compute-resources.md
tab found: ./user-guide/connecting-applications.md
tab found: ./user-guide/production-pods.md
tab found: ./user-guide/images.md
tab found: ./getting-started-guides/fedora/fedora_manual_config.md
tab found: ./getting-started-guides/centos/centos_manual_config.md
tab found: ./admin/resourcequota/README.md
tab found: ./admin/namespaces.md
```

**Comment by bgrant0607** [comment]
Hmm. Most of those don't show red rectangles, though.

**Comment by janetkuo** [comment]
Guess it only happens on ```yaml

**Comment by janetkuo** [comment]
I verified all the files listed above (contain tabs in quoted regions), only the two docs we already pointed out have red rectangles.

**Comment by janetkuo** [comment]
Looks like Jekyll doesn't recognize tabs used in `{% highlight yaml %}`. https://raw.githubusercontent.com/kubernetes/kubernetes/gh-pages/_v1.1/docs/user-guide/compute-resources.md

**Comment by bgrant0607** [comment]
Ok, that does appear to be it. 

```
find . -name "*.md" -exec awk 'BEGIN{cr=0;tab=0}/^```yaml/{cr = 1}/^```$/{cr = 0}/\t/{if (cr) {tab = 1}}END{if (tab) {printf("tab found: ")}}' "{}" \; -print |grep "tab found"
tab found: ./docs/user-guide/compute-resources.md
tab found: ./docs/user-guide/production-pods.md
```

Please file an issue to write a munger to replace the tabs with spaces.

**Comment by janetkuo** [comment]
Filed #16541

**Comment by bgrant0607** [comment]
Fixed.
