### ISSUE TITLE
Download link doesn't display well in gh-pages

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#16393]
For example, in http://kubernetes.io/v1.1/docs/user-guide/simple-yaml.html, if you click on [Download example](http://kubernetes.io/v1.1/docs/user-guide/pod.yaml?raw=true), it opens a blank kubernetes page instead of showing the file content. 

cc @bgrant0607 @RichieEscarez @krousey @caesarxuchao

**Comment by bgrant0607** [comment]
I think we need to do something special with the query parameter.

**Comment by bgrant0607** [comment]
Someone please take this issue. Probably the munger in gh-pages needs to deal with this.

**Comment by RichieEscarez** [comment]
The javascript only looks for .yaml and .json at the end of these downloadable files, i think it needs to be updated to handle trailing attributes (?raw=true): http://kubernetes.io/v1.1/docs/user-guide/pod.yaml?raw=true

**Comment by bgrant0607** [comment]
We should strip the query parameter. It's only meaningful to github.

**Comment by RichieEscarez** [comment]
#15121 is what added the code sample preview changes (shows the javascript).

**Comment by bgrant0607** [comment]
ETA today/tomorrow

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/16475 fixes this

**Comment by janetkuo** [comment]
Closing with the fix #16475
