### ISSUE TITLE
Shouldn't run SSH should SSH to all nodes and run commands e2e in GKE

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#16407]
It doesn't work...

Sending to @roberthbailey for triage

**Comment by roberthbailey** [comment]
For reference, this is failed in kubernetes-e2e-gke-test

**Comment by roberthbailey** [comment]
@ixdy recently moved that job into a new cloud project (for isolation) and I'm guessing we didn't quite finish all of the steps (in particular, adding ssh keys into the new project).

**Comment by roberthbailey** [comment]
This test is also failing consistently on the kubernetes-e2e-gke-ci-reboot job, which was also recently moved into a new project.

**Comment by roberthbailey** [comment]
I've added ssh keys and I'll keep an eye on the next Jenkins run to see if the tests start passing.

**Comment by roberthbailey** [comment]
The SSH-based tests are now passing on both kubernetes-e2e-gke-test and kubernetes-e2e-gke-ci-reboot.
