### ISSUE TITLE
Only bring up events etcd server in "large" clusters, and update docs to mention events etcd server 

### ISSUE THREAD

**Issue by willmore** [kubernetes/kubernetes#16424]
Etcd events were moved to a separate instance with
https://github.com/kubernetes/kubernetes/commit/a4581c7cd56c84df269970ed554bbea1e5dc58d0

I believe the HA docs should be updated to cluster etcd-events too:
https://github.com/kubernetes/kubernetes/blob/b9cfab87e33ea649bdd13a1bd243c502d76e5d22/docs/admin/high-availability.md

**Comment by davidopp** [comment]
Yeah we probably should update *all* of our documentation to reflect this...

@bgrant0607

**Comment by davidopp** [comment]
BTW @lavalamp and I were surprised that this was enabled by default instead of flag-controlled. We might want to make it flag-controlled for 1.2.

@wojtek-t

**Comment by davidopp** [comment]
("this" == second etcd instance, not HA)

**Comment by davidopp** [comment]
@wojtek-t

**Comment by wojtek-t** [comment]
@gmarek 

We would like to enable separate etcd instance only if there are more than X nodes in a cluster (X=100?).

**Comment by wojtek-t** [comment]
This one was actually fixed by #18819
