### ISSUE TITLE
We should publish a kubectl container for every release

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#16437]
being able to `docker run --net=host gcr.io/google_containers/kubectl get pods` would be nice.

**Comment by davidopp** [comment]
Would this also make it easier to run kubectl from a container that's running on k8s?

**Comment by davidopp** [comment]
Also what is the relationship to autoscaling?

**Comment by thockin** [comment]
I did not intend for this to be tagged autoscaling, sorry

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by MHBauer** [comment]
I would definitely be interested in having a kubectl image. Service-catalog uses a self published one for testing.
