### ISSUE TITLE
Master may be added to GCE Target Pools

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#16438]
User reports:

I am running my web service behind an SSL proxy on my Kubernetes cluster as described in this tutorial. It works 90% of the time, but from time to time my browsers (Chrome/Firefox) get SSL errors when accessing my web service. Firefox says this:

api.[mydomain.com] uses an invalid security certificate.

The certificate is not trusted because the issuer certificate is unknown.
The server might not be sending the appropriate intermediate certificates.
An additional root certificate may need to be imported.
The certificate is only valid for the following names:
  [MY-CLUSTER-IP], 10.0.0.1, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, kubernetes-master  

(Error code: sec_error_unknown_issuer)
After a reload, all requests work fine - until the error pops up again after a while. Is this a problem with Kubernetes or am I doing something wrong here?

Since a while ago we added the master to the list of nodes.  I think that we must be adding the master to the GCE target pool resource.  This is clearly the wrong thing to do.  We shouldn't add nodes that aren't schedulable.

@davidopp @wojtek-t

**Comment by brendandburns** [comment]
PR in flight, ETA 10/28

**Comment by lavalamp** [comment]
Is this the same as #16278?

**Comment by lavalamp** [comment]
heh-- I'm 10 seconds behind @davidopp...

**Comment by davidopp** [comment]
Yeah that was hilarious timing.

**Comment by brendandburns** [comment]
Yep, this is a dup.  Closing in favor of #16278
