### ISSUE TITLE
apiserver: CORS only works in insecure mode?

### ISSUE THREAD

**Issue by xinzhangcmu** [kubernetes/kubernetes#16431]
I am writing a client-side AngularJS app that uses XMLHttpRequest trying to talk to the apiserver. The apiserver was brought up with the following flags, especially with `cors-allowed-origins` hoping to allow CORS.

```
--cors-allowed-origins=.* 
--insecure-bind-address=127.0.0.1 
--insecure-port=8080 
--bind-address=0.0.0.0 
--secure-port=443
```

and I configured apiserver to support basic auth with https.

However, the pre-flight OPTIONS request failed with 401. Below is my rationale:

- For CORS to work, the client will always first send a pre-flight OPTIONS request to the api endpoint

- When the apiserver runs in the secure mode (with authn), for each request the master will use ["m.Handler"](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L597) to process the request; whereas an ["m.InsecureHandler"](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L650) will be used if running in insecure mode

- The m.InsecureHandler will handle CORS [correctly](https://github.com/kubernetes/kubernetes/blob/52136bdb68d7ac34a702f9d962e141664a31ec0f/pkg/master/master.go#L720) without performing any auth.

- In comparison, the m.Handler will add authn functionality *before* CORS, as shown [here](https://github.com/kubernetes/kubernetes/blob/52136bdb68d7ac34a702f9d962e141664a31ec0f/pkg/master/master.go#L731), where the [handlers.NewRequestAuthenticator](https://github.com/kubernetes/kubernetes/blob/52136bdb68d7ac34a702f9d962e141664a31ec0f/pkg/master/master.go#L727) will add auth *before* the InsecureHandler that handles CORS. In short, in the secure mode, we *first* authenticate *all* requests (including OPTIONS) *before* detecting if it is an OPTIONS request

- Meanwhile (unfortunately), as the OPTIONS request cannot carry any auth headers (by w3c standards), the OPTIONS requests will *always* fail the authentication.

Is this expected behavior or did I miss anything? If it is expected, then what is the recommended way to allow CORS with authn on? I am thinking of using a proxy in front of the apiserver

**Comment by krousey** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
That seems kinda broken, how can we implement this without leaking
information about whether a resource exists or not?
http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0

BTW, our apiserver is not currently safe against XSS attacks, so we do
intend to make a proxy layer that handles this stuff. See
https://github.com/kubernetes/kubernetes/issues/10351#issuecomment-135200873.
If you write a proxy layer, we'd love to see it!

**Comment by Pendoragon** [comment]
I have come across the same issue. Is it possible to run a nginx proxy in front of apiserver on the master to handle CORS request? it seems that there was a nginx sitting in front of apiserver quite a while ago and all requests will be reverse proxied by nginx. but then it got removed to enable apiserver bearer token auth (nginx does not support bearer token).
kubernetes/kubernetes#4007

**Comment by Pendoragon** [comment]
also since the authn handler will take precedence over CORS handler, the apiserver will reject all of the CORS request on its secure port?

**Comment by Pendoragon** [comment]
@lavalamp any update?

**Comment by lavalamp** [comment]
@Pendoragon No update.

As far as what the problem is, OPTIONS not having auth headers means we can't tell if the requester is allowed to see the thing they're asking about.

But anyway, as apiserver is not currently (and possibly not ever) hardened against XSS attacks, if you need CORS, you probably need to run an api proxy that *is* hardened against XSS attacks.

**Comment by xinzhangcmu** [comment]
> OPTIONS not having auth headers means we can't tell if the requester is allowed to see the thing they're asking about.

@lavalamp could you clarify what information would be leaked if we don't check auth on OPTIONS requests? My understanding is that 

- the client sending OPTIONS requests only intends to see if the server allows the client (or a certain origin) to further talk to the server for CRUD operations
- Hence, the only information that is leaking by not checking auth on OPTIONS requests is what origins are allowed for XmlHttpRequests. Is this your concern?

**Comment by lavalamp** [comment]
I was under the impression that OPTIONS also contains a path, and therefore
the server's response would therefore allow someone to tell if a resource
exists or not? If there's no path in OPTIONS (or there is but it can be
ignored) then I have no objection and we can see if @erictune or @stephenR
agree.

**Comment by Pendoragon** [comment]
AFAIU, OPTIONS does contain a path but the server will just return 204 regardless of whether the path exits or not. The response to OPTIONS only indicates that server is aware of CORS.

**Comment by stephenR** [comment]
I agree with @Pendoragon, it should be fine to ignore the path in the options request.

**Comment by lavalamp** [comment]
Thanks for the clarification! In that case it sounds logical to change the
order, and make sure that OPTIONS response does not depend on the path.
I'll happily take a PR that changes this.

**Comment by Pendoragon** [comment]
Thanks! I will work on a PR for this!
