### ISSUE TITLE
examples_test.go tension with config best practices

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#16444]
[Config best practices](../tree/fe6b15ba/docs/user-guide/config-best-practices.md) is at odds with [how we test examples currently](../tree/fe6b15ba/examples/examples_test.go): the best
practices expresses a desire to put multiple resources in a file, which makes
sense, but `examples_test.go` expects each file to represent a single API type. This has a perverse effect on the examples (see #16320, #14256).

**Comment by zmerlynn** [comment]
cc @bgrant0607 @linzichang

**Comment by linzichang** [comment]
In https://github.com/kubernetes/kubernetes/pull/14256, I have add a TODO. I will try to make `examples_test.go` can validate multiple resources file.

**Comment by smarterclayton** [comment]
Oops - I forgot to back port this from Openshift.

**Comment by kargakis** [comment]
@ahmetb
