### ISSUE TITLE
1.0 Kubectl e2e's leave pods in Error state lying around (against a 1.1 head & 1.1 nodes)

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16447]
Perhaps a re-opening of #15123, (which we thought was a duplicate of #15895,) but also may be a new issue.

Worth noting this is only happening when nodes are at 1.1; when nodes are at 1.0, these tests pass.

See `kubernetes-upgrade-1.0-1.1-gke-step5-e2e-old` Jenkins job:

```
Kubectl client Update Demo should scale a replication controller

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:107
Resources left running after stop:
update-demo-nautilus-dh1ty   0/1       Error     0         27s
update-demo-nautilus-uhtk0   0/1       Error     0         7s

Kubectl client Update Demo should create and stop a replication controller

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:93
Resources left running after stop:
update-demo-nautilus-aaq9h   0/1       Error     0         9s
update-demo-nautilus-obcb9   0/1       Error     0         9s

Kubectl client Guestbook application should create and stop a working application

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:138
Resources left running after stop:
frontend-3a81w   1/1       Running   0         1m
frontend-milh3   1/1       Running   0         1m
frontend-mjcix   1/1       Running   0         1m

Kubectl client Kubectl label should update the label on a resource

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:217
Resources left running after stop:
nginx     0/1       Error     0         17s

Kubectl client Simple pod should support port-forward

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:153
Resources left running after stop:
nginx     0/1       Error     0         16s

Kubectl client Simple pod should support exec

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:153
Resources left running after stop:
nginx     0/1       Error     0         17s
```

cc @mikedanese

**Comment by ihmccreery** [comment]
cc @davidopp @mikedanese @lavalamp

**Comment by ihmccreery** [comment]
Re #16457 is there consensus that this isn't a breaking change, and thus we should just fix the tests?  Sounded like, @mikedanese, you weren't confident that this wasn't a problem worth fixing on 1.1.

**Comment by mikedanese** [comment]
Iffy because kubectl output may or may not be under contract. In 1.1 we started hiding terminal, and terminated pods form output(unless you add `--all` command). A combination of this change and GracefulTermination cause these tests to pass in HEAD but not with 1.0 `kubectl`.

**Comment by lavalamp** [comment]
Sounds like old clients don't understand the graceful deletion state. Just waiting as in #16457 seems reasonable.

**Comment by lavalamp** [comment]
Perhaps one of @davidopp or @bgrant0607 can confirm

**Comment by davidopp** [comment]
Yeah this seems reasonable to me.

**Comment by lavalamp** [comment]
If people have built tooling that this feature breaks, they can fix their tooling by upgrading to a new kubectl OR adding a wait, so I'm not too worried.

**Comment by lavalamp** [comment]
Reducing to P1 since it's just a test problem. Also closing since the fix is merged.
