### ISSUE TITLE
Add SAN to certificate

### ISSUE THREAD

**Issue by jetole** [kubernetes/kubernetes#16446]
I would like to be able to add SAN's to certificate so that I can access the cluster either via a different CNAME / A record or if the master uses a different IP.

**Comment by roberthbailey** [comment]
Where are you deploying your cluster? If you don't mind modifying code and running from head, you can easily customize your SANs. 

For GCE, the SANs are set [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L540) but there isn't a variable in [config-default.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh) that allows you to append your own values. Other cloud providers are set similarly.

**Comment by thockin** [comment]
It seems like adding a variable that gets added to the SAN list might be
reasonable?  as an alternative, what if kube-apiserver could generate its
own cert (with our CA)?  Could we just do `kube-apiserver
--generate-master-cert --cert-sans=...` or something?

**Comment by roberthbailey** [comment]
> It seems like adding a variable that gets added to the SAN list might be reasonable?

Yes, that what I'm suggesting, but since this is done in a different place for each provider to actual help @jetole we'd need to do it for the provider he's actually using.

**Comment by thockin** [comment]
IIRC from IRC this was AWS in particular.

**Comment by roberthbailey** [comment]
AWS using salt / CoreOS / Ansible / something else?

**Comment by thockin** [comment]
CoreOS I think, but now we're at the edge of my ability to remember things.

**Comment by jetole** [comment]
@roberthbailey: I'm running in AWS. I modified aws/util.sh and added the line ```MASTER_EXTRA_SANS+=",DNS:blah.blah,IP:x.x.x.x"```

**Comment by jetole** [comment]
I agree with @thockin that it would be nice to be able to define this in a var. It would also be nice to have a override var or option to say use _this_ cert instead of creating one (#16449). I understand that it's done in a different location per provider but it would be nice to have a front end method that would be pushed to the provider specific functions.

**Comment by roberthbailey** [comment]
Definitely. This is something that we are trying to address as part of [Simpler Cluster Setup](https://docs.google.com/document/d/1v68yStV2O6aHuRuT3AlWnbe6vkUCtzyC5I7Elhgik3o/edit).

**Comment by jetole** [comment]
@roberthbailey the link to simple cluster setup says I need permission to view it.

**Comment by roberthbailey** [comment]
Yeah, there isn't a way for me to make a document that is visible to everyone by default. I shared it with the [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev) mailing list, so if you join that list then you can see it without needing to request access (but I've granted you access as well).

**Comment by jetole** [comment]
@roberthbailey: When click on share, at the top right in Google Docs, there is a button that says "Get shareable link". This will give you a link and it will allow you to set permissions on it such as "Anyone with the link can view", "Anyone with the link can comment" and "Anyone with the link can edit". You can also set it to "Off" which means the link will no longer work after you set it to off. You can test it on a private doc and open that same doc with the link from a incognito window which would be display the document and permissions the same way everyone else will see it.

**Comment by roberthbailey** [comment]
That works from consumer accounts, but not from accounts that are tied to a domain with domain restrictions. Instead I can share it with anyone within the domain that has the link rather than anyone that has the link.

**Comment by jetole** [comment]
@roberthbailey: Sort of. I just checked on my Google Apps docs instead of my personal one and there is and from the choice of who you want to share with, click "More" at the bottom of the drop down. This will allow you to select from "Public to the web", "Anyone with a link", two other options specific to domain members as well as disabling it entirely. Below that you can choose the level of access you are granting such as read-only, can comment or can edit.

I have access now. I believe you granted it to me earlier but for this or anything else you would like to make publically visible, you can do that.

**Comment by roberthbailey** [comment]
From what I understand, domain admins can apply restrictions on what sharing options are available. There aren't "Public to web" or "Anyone with a link" options on my sharing dialog; only the domain specific ones.

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by mikedanese** [comment]
This is stale
