### ISSUE TITLE
Enable security context in clusters by default

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#16456]
We have E2E tests for the new security context features, but the `SCDeny` admission controller is used by default in most cluster types.  We should enable it in GCE in order to get coverage in CI on that stack.

**Comment by pmorie** [comment]
@bgrant0607 @thockin Any issue with this?  Of course, we'll have to continue skipping the SELinux-specific tests.

**Comment by pmorie** [comment]
@kubernetes/rh-cluster-infra

**Comment by bgrant0607** [comment]
I'm fine with this. It's in line with our current direction.

**Comment by bgrant0607** [comment]
cc @ArtfulCoder

**Comment by thockin** [comment]
+1

**Comment by yujuhong** [comment]
@pmorie, are there any jenkin builds in testgrid.k8s.io running SecurityContext tests? I couldn't find them...
I am trying to make sure that the new CRI-docker integration will continue support all existing features, and we rely heavily on the tests results. It'd be good to make sure we have some builder running these tests.

**Comment by feiskyer** [comment]
+1.

@pmorie @kubernetes/sig-node  is there any updates for this?

**Comment by yujuhong** [comment]
@pmorie CRI is enabled by default now, but we don't have security context coverage in our tests. It'd be good if the redhat folks can verify that everything works.

**Comment by yujuhong** [comment]
@pmorie @tallclair is this issue outdated?
