### ISSUE TITLE
version 1 coreos install documentation has old cloudconfig file

### ISSUE THREAD

**Issue by esecules** [kubernetes/kubernetes#16454]
in the version 1 coreos install guide here:
 http://kubernetes.io/v1.0/docs/getting-started-guides/coreos/coreos_multinode_cluster.html 
there are cloudconfig files (master.yaml and node.yaml) that are written to pull the kubernetes 0.19.3 release. Could these be updated to use version 1? I got a cluster set up only to realize at the very end that it was the wrong version and I had wasted all my time.

**Comment by esecules** [comment]
ping?

**Comment by esecules** [comment]
I tried editing the cloud config files manually to pull kubernetes 1.0.7 but Im not sure what I ended up doing. As far as I remember 0.19.3 didnt have support for api version v1 and im pretty sure it had support for v1beta1 and v1beta2. 

```
kubectl -s http://10.128.11.45:8080 api-versions
Available Server Api Versions: v1beta3,v1
```
```
kubectl -s http://10.128.11.45:8080 version
Client Version: version.Info{Major:"0", Minor:"21", GitVersion:"v0.21.0", GitCommit:"39b013a5d5fb09b5bb7236b553dfa189f8884bbd", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"19", GitVersion:"v0.19.3", GitCommit:"3103c8ca0f24514bc39b6e2b7d909bbf46af8d11", GitTreeState:"clean"}
```

**Comment by esecules** [comment]
alright, it seems like all you need to do is change the version number in all the ExecStartPre download steps. but this still should be dealt with.

**Comment by bgrant0607** [comment]
Thanks. They have been updated in head, but need to be updated again. A PR would be welcome.

**Comment by roberthbailey** [comment]
The coreos installation guides have changed a lot in the last year, so I'm going to mark this as obsolete.
