### ISSUE TITLE
Make sure 1.1 API resource discovery tolerates 1.0 and 1.2+ apiservers.

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16462]
@caesarxuchao has a fix in #16082, but we're waiting for a dependency to merge, a squash, and then we need to cherrypick it.

**Comment by lavalamp** [comment]
ETA the 30th

**Comment by caesarxuchao** [comment]
Thanks. I'll do these once #16343 is merged.

**Comment by caesarxuchao** [comment]
#16516 is the CP.

**Comment by lavalamp** [comment]
We're just waiting for merges at this point.

**Comment by caesarxuchao** [comment]
Closed by #16516

**Comment by lavalamp** [comment]
everything merged.
