### ISSUE TITLE
Fix serialization of objects to query params

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#16499]
[queryparams.Convert](https://github.com/kubernetes/kubernetes/blob/809f4e1bc39c795dfbb67fa99e8e1e663d03a0e9/pkg/conversion/queryparams/convert.go#L99) is for serializing versioned objects to parameters but we need this to happen in the request. 

See https://github.com/openshift/origin/pull/5396/files#r43377104

cc: @deads2k

**Comment by krousey** [comment]
Not looking too carefully, but is [`func (r *Request) VersionedParams(obj runtime.Object, convertor runtime.ObjectConvertor) *Request`](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/request.go#L410) what you're looking for?

**Comment by kargakis** [comment]
@krousey, yes that would do the trick! Thanks!
