### ISSUE TITLE
Missing field selector conversions

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#16501]
kubernetes/kubernetes#15766 added field selectors for namespace to several objects, but did not add conversions for those field selectors to api/v1/conversion.go#AddFieldLabelConversionFunc.

I'm pretty sure that means the new selectors aren't usable. Please add those conversions, and add tests for using the selectors.

**Comment by krousey** [comment]
@feihujiang Do you want this one?

**Comment by feihujiang** [comment]
@krousey thanks for reminding me. And @miminar started to work on this, I'll work with him to fix this.
