### ISSUE TITLE
Doc needed: pod command[] vs args[]

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#16506]
It's not easy for people to figure out the difference between the two fields.  We should have a simple article that illustrates the interactions with Docker CMD and ENTRYPOINT.

This raises a question for me  - is this an "example" or do we have a new kind of doc: "article" or should it be buried in a pod-doc somewhere?

**Comment by krousey** [comment]
Any suggestion for a team label?

**Comment by resouer** [comment]
I am thinking about can we generate full `pod.yml rc.yml` example based on `api/types`? Then we can add these things in comments.

**Comment by thockin** [comment]
Generated docs are good references, but we actually need a set of
human-created docs that address the subtle aspects of things like this.

**Comment by resouer** [comment]
Em ...  I once read about [this doc](https://github.com/kubernetes/kubernetes/blob/5c903dbcacb423158e3f363bcbb27eef58f95218/docs/user-guide/containers.md#containers-and-commands), does that help?

Anyway, article idea sounds good for me. And I can write, of course.

**Comment by bgrant0607** [comment]
@resouer Yes, I think that doc is sufficient explanation, but hard to find. I'm closing this in favor of #15244.
