### ISSUE TITLE
Brokwn download link in gh-pages

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#16519]
Similar to #16393, in http://kubernetes.io/v1.1/docs/getting-started-guides/docker-multinode/deployDNS.html, the download links doesn't work:
- [skydns-rc template](http://kubernetes.io/v1.1/docs/getting-started-guides/docker-multinode/skydns-rc.yaml.in)
- [skydns-svc template](http://kubernetes.io/v1.1/docs/getting-started-guides/docker-multinode/skydns-svc.yaml.in)

cc @bgrant0607 @caesarxuchao @nikhiljindal @krousey

**Comment by janetkuo** [comment]
It's because gh-pages doesn't recognize `.yaml.in` file extension. I'll change all the `xxx.yaml.in` files to `xxx-template.yaml` (and change the related docs)

**Comment by bgrant0607** [comment]
How hard would it be to make the download link work for .yaml.in?

**Comment by bgrant0607** [comment]
_layouts/docwithnav.html
```
               function displaycodesample(targethref) {
                        var isCodeSample = false;
                        if ((targethref.indexOf('.yaml') > -1 && targethref.indexOf('.yaml') + 5 == targethref.length) || (targethref.indexOf('.jso
n') > -1 && targethref.indexOf('.json') + 5 ==  targethref.length)) {
                                $('#doccontent').load(location.origin + "/codeblockdisplay.html", function() {// load the code sample template
                                        $('#codeblock').load(targethref, function() { //load the code sample file into the 'code' tags of the templ
ate
                                                $('#codetitle').html(location.pathname); //set the page title
                                                $( "code" ).prepend( "<br />" ); //insert line break to correct unwanted 1st line indentation
                                        });
                                });
                                isCodeSample = true;
                        }
                        return isCodeSample;
                }
```

**Comment by janetkuo** [comment]
That's better. I'll make the download link work for `.yaml.in` instead.

**Comment by bgrant0607** [comment]
It doesn't seem to provide the same pretty view, but at least the yaml displays.
