### ISSUE TITLE
Add a way to distinguish between volumes that are synthesized by the kubelet and 'real' volumes

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#16514]
Currently in the ownership and SELinux label management code, we do not alter volumes whose builder reports `true` from `IsReadOnly()`.  This doesn't give us quite the right decision plane; we need a new method that tells the kubelet where a volume is synthesized by the system or not.  I suggest:

```go
package volume

type Builder interface {
  // other methods omitted
  IsSynthetic() bool
}
```

`secrets` and `downwardApi` would return 'true' from this method.

Then the decision plane for ownership / selinux label management becomes:

```go
if builder.IsReadOnly() && !builder.IsSynthetic() {
  // do stuff
}
```

thoughs @thockin @swagiaal @pweil- @smarterclayton ?

**Comment by pmorie** [comment]
@kubernetes/rh-cluster-infra @kubernetes/rh-storage

**Comment by ncdc** [comment]
The issue at hand is that the only user that can currently access downward api files is root, because the timestamped directory in which they're created is made via ioutil.Tempdir, which creates 0700.

**Comment by swagiaal** [comment]
So the motivation for this is to have secrets and downwardapi be read-only but still chown'ed chcon'ed by the kubelet ? If so then we should revisit the decision of IsReadOnly at the chcon chown point and move it to the individual plugins. It might be more code, but adding another predicate confuses matters IMO

**Comment by markturansky** [comment]
What about typing with an interface?  As some but not all plugins are PersistentVolumes, some but not all are SyntheticVolumes?

That applies even after the new provisioning interfaces are refactored out of the plugin proper.

**Comment by pmorie** [comment]
@markturansky It doesn't warrant that at all, I don't think.  Only a couple of volume types will report true.

**Comment by pmorie** [comment]
@swagiaal I would prefer to add predicates instead of folding things into methods that should be getters for simple predicates, especially since the business logic is generalizable to such a great degree.

**Comment by thockin** [comment]
The distinction here is whether a volume is writeable by the host vs by users, right?  Can we just extend the IsReadOnly() to be an enum?  GetReadWriteMode() -> VolumeWritable, VolumeManaged, VolumeReadOnly.  Something like that?  Rather than having two axes..

**Comment by pmorie** [comment]
@thockin We can do that, yeah.

**Comment by pmorie** [comment]
@thockin I'll start coding up a PR

**Comment by thockin** [comment]
Before you get too deep into it, make sure that the current callers of
IsReadOnly can be satisfied cleanly.  Maybe we want a helper like
volume.IsReadOnlyToHost(builder) and volume.IsReadOnlyToContainerUsers() or
something

**Comment by pmorie** [comment]
Yep, I am going to analyze all the call sites before changing anything since I need to refresh my memory about how the PV code uses this.

**Comment by swagiaal** [comment]
> Can we just extend the IsReadOnly() to be an enum? GetReadWriteMode() -> VolumeWritable, VolumeManaged, VolumeReadOnly.

nice

**Comment by pmorie** [comment]
@thockin @markturansky I think I can keep this completely internal and maintain the existing ReadOnly notions in the API.

**Comment by pmorie** [comment]
@thockin @markturansky @swagiaal How do you like this for the API:

```go
// Mode represents the usage mode for a volume.
type Mode string

const (
	ReadWrite       Mode = Mode("ReadWrite")       // The volume is read-write and can be managed by the kubelet
	ReadOnlyManaged Mode = Mode("ReadOnlyManaged") // The volume is read-only to the pod but can be managed by the Kubelet
	ReadOnly        Mode = Mode("ReadOnly")        // The volume is read-only to the pod and the node
)

// Builder interface provides methods to set up/mount the volume.
type Builder interface {
	// Uses Interface to provide the path for Docker binds.
	Volume
	// SetUp prepares and mounts/unpacks the volume to a self-determined
	// directory path.  This may be called more than once, so
	// implementations must be idempotent.
	SetUp() error
	// SetUpAt prepares and mounts/unpacks the volume to the specified
	// directory path, which may or may not exist yet.  This may be called
	// more than once, so implementations must be idempotent.
	SetUpAt(dir string) error
	// Mode determines whether the volume is read-write, read-only but managed,
	// or read-only.  If the mode is ReadWrite or ReadOnlyManaged, the Kubelet
	// will perform ownership and selinux label management on appropriate volumes.
	Mode() Mode
	// SupportsOwnershipManagement returns whether this builder wants
	// ownership management for the volume.  If this method returns true,
	// the Kubelet will:
	//
	// 1. Make the volume owned by group FSGroup
	// 2. Set the setgid bit is set (new files created in the volume will be owned by FSGroup)
	// 3. Logical OR the permission bits with rw-rw----
	SupportsOwnershipManagement() bool
	// SupportsSELinux reports whether the given builder supports
	// SELinux and would like the kubelet to relabel the volume to
	// match the pod to which it will be attached.
	SupportsSELinux() bool
}
```

**Comment by swagiaal** [comment]
That looks good!
