### ISSUE TITLE
Clock Synchronization with NTP when provisioning

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#1651]
We slowly introduced timestamps everywhere. Soon we are going to have logging, monitoring, and events, etc, all of them only make sense when the entire cluster shares the same accurate time.

**Comment by BenTheElder** [comment]
Where would this be added? To the scripts in /cluster ?

**Comment by bgrant0607** [comment]
@BenTheElder Probably cluster/addons.

**Comment by BenTheElder** [comment]
@bgrant0607 thanks again for all of the info.
This also looks interesting but I've currently decided to post a draft for https://github.com/GoogleCloudPlatform/kubernetes/issues/3760.

**Comment by dchen1107** [comment]
cc/ @davidopp

**Comment by timothysc** [comment]
@smarterclayton ^ FYI.
