### ISSUE TITLE
links in release branch should point to release branch, rather than version tags

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#16522]
For example, in this .md file in the release-1.1 branch, https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/configuring-containers.md, 
the "Pod API object" link links to https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/v1.1.0/docs/api-reference/definitions.html#_v1_pod,
it should rather points to 
https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/release-1.1/docs/api-reference/v1/definitions.html#_v1_pod

I will fix this in versionized-docs.sh.

[edit] it seems the problem is the mark-new-version.sh, https://github.com/kubernetes/kubernetes/blob/master/build/mark-new-version.sh#L143
We need rewrite the links to point to release branch before push the release branch.

cc @nikhiljindal @janetkuo @bgrant0607 

And this issue (https://github.com/kubernetes/kubernetes/pull/16486#discussion_r43350745) will be solved as well.

**Comment by caesarxuchao** [comment]
#16553 needs to be merged and cherry-picked, otherwise the bug will relapse once someone run versionized-docs.sh or mark-new-version.sh again.

**Comment by ihmccreery** [comment]
FYI I have #16102 which will supplant `mark-new-version.sh`.  We should coordinate efforts.  As it stands right now, I have it running `mark-new-version.sh` on a beta release, which will link docs to the `vX.Y.Z-beta` tag, but, that still isn't really right.

**Comment by caesarxuchao** [comment]
@ihmccreery 
Discussed with @nikhiljindal @bgrant0607 @lavalamp etc, we thought link URLs in a tag or link URLs in a release branch should all point to the release branch.

Could you point us to the discussion that leads to "links should point to a tag"? Thanks.

**Comment by ihmccreery** [comment]
Hm.  What you propose means that, if I think I'm looking at docs for `v1.1.1`, I'll actually be looking at docs for `release-1.1`/HEAD.  That basically abandons the idea of versionizing docs.  Is that really what we want?

Ideally, I think, we'd like to have docs on the release branch pointing to the release branch, as @caesarxuchao describes, but we also need to have docs in a release point to the tag.  Please see #16102.  Perhaps we should versionize docs to the branch on a beta release and to the tag on an official release?

**Comment by ihmccreery** [comment]
(I don't have a particular discussion I'm thinking of, but not having a canonical set of `v1.1.1` docs seems weird to me.)

**Comment by bgrant0607** [comment]
Yes, we really want docs to point at release-1.1/HEAD.

**Comment by bgrant0607** [comment]
Where "we" is at least me, @thockin, @lavalamp

**Comment by ihmccreery** [comment]
Haha.  K, you win.  :smile:  Happy to be overruled.

Will update #16102 accordingly.

**Comment by bgrant0607** [comment]
Note that on kubernetes.io we also only have docs per minor version, not per patch version.

**Comment by ihmccreery** [comment]
Cool.  Just so we're all on the same page, this means that we'll no longer rev docs at patch bumps, (e.g. `v1.1.1` -> `v1.1.2`,) just at major cycle bumps, (when we cut the `release-1.2` branch).

**Comment by ihmccreery** [comment]
(So this change doesn't actually need to be cherrypicked; I just need to update #16102.)

**Comment by bgrant0607** [comment]
There's no reason we can't copy docs over to gh-pages from the release branch even more often than patch releases.

**Comment by bgrant0607** [comment]
@ihmccreery We need #16553 merged in O(minutes).
