### ISSUE TITLE
examples/high-availability needs a README.md

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#16538]

**Comment by resouer** [comment]
How's this going? @jayunit100 

I can not vagrant up this example, just need some clues to bring me out.

**Comment by jayunit100** [comment]
Hi! Let me make one. 
Iirc it should work fine as is , possibly paste the error meanwhile?

**Comment by resouer** [comment]
Sorry, the error has been eaten ... But I remember it is because etcd is not started. If we have a readme here, I can debug it easier.

**Comment by jayunit100** [comment]
close this ?

**Comment by spzala** [comment]
@bgrant0607 Hi Brian, just wanted to touch base with you and see if this issue can be closed now? It seems so. Thanks!!

**Comment by spzala** [comment]
@kargakis  Thanks!
