### ISSUE TITLE
Remove E2E_SET_CLUSTER_API_VERSION; it's confusing and unnecessary

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16535]
For a while, we were running tests against GKE at versions we didn't realize, because we weren't properly setting `E2E_SET_CLUSTER_API_VERSION`.  See #16533.

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by spiffxp** [comment]
/close

I can't find it in the kubernetes/kubernetes nor kubernetes/test-infra codebases
