### ISSUE TITLE
Add support for tailLines with follow=true for pods/log

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#16532]
Currently, if follow=true, tailLines is ignored by the kubelet in dockertools

```
	if !logOptions.Follow && logOptions.TailLines != nil {
		opts.Tail = strconv.FormatInt(*logOptions.TailLines, 10)
	}
```

"Show me the last 100 lines of the log and follow" is a very natural thing to want to do. Is there an underlying reason not to support this?

**Comment by smarterclayton** [comment]
I'm thinking back to this... and I really can't remember why we did this *except* in our original "let's not be too aggressive about exposing logging".  However, in practice both Docker and journald (as well as others, likely) support follow and tail at the same time, and it's a very common use case.

I'd like to remove this.

**Comment by smarterclayton** [comment]
@thockin @brendandburns because you were involved in reviewing the original https://github.com/kubernetes/kubernetes/pull/1318

**Comment by thockin** [comment]
Remove what?

**Comment by liggitt** [comment]
> Remove what?

Explicitly disallowing specifying tailLines while following:
```
    if !logOptions.Follow && logOptions.TailLines != nil {
        opts.Tail = strconv.FormatInt(*logOptions.TailLines, 10)
    }
```

**Comment by smarterclayton** [comment]
The if check which prevents tail and follow being specified (which docker
and journalctl allow)

**Comment by liggitt** [comment]
cc @spadgett

**Comment by thockin** [comment]
Oh.  SGTM
