### ISSUE TITLE
Determine how apply annotation should be serialized

### ISSUE THREAD

**Issue by jackgr** [kubernetes/kubernetes#16543]
Forked from #16441, starting at [this comment](https://github.com/kubernetes/kubernetes/pull/16441#issuecomment-151935611).

To summarize, when creating the apply annotation in [pkg/kubectl/cmd/apply.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply.go), we are serializing the object client side using the mapping codec. We are also deserializing it client side in [pkg/kubectl/apply.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/apply.go) to retrieve the previous version for the three way diff. 

The question being discussed is whether or not this code is serializing and deserializing the object in a way that deals correctly with the api version and defaults.

cc @bgrant0607, @liggitt, @janetkuo

**Comment by liggitt** [comment]
@deads2k this is related to what we were discussing today

**Comment by jackgr** [comment]
After discussion with @lavalamp, a key observation is that when the object is pushed to the api server, the server will upgrade the version, if necessary, until such time as the version being pushed is deprecated. When the version being pushed is deprecated, an error will be returned. So, there is no risk of doing any damage by submitting the wrong version.

With this observation in mind:
* If there is no annotation, we use what the caller provided to create the annotation and the patch.
* If there is an annotation,
   * If the version provided by the caller is the same as the version in the annotation, we use what the caller provided to create the annotation and the patch.
   * If the version provided by the caller is newer than the version in the annotation, we use what the caller provided to create the annotation and the patch, effectively upgrading the annotation. The patch will contain the version they provided.
   * If the version provided by the caller is older than the version in the annotation, we return an error.

**Comment by deads2k** [comment]
> If the version provided by the caller is newer than the version in the annotation, we use what the caller provided to create the annotation and the patch, effectively upgrading the annotation. The patch will contain the version they provided.

How will you detect the conflict between old annotation and the new apply?  Won't that require reserializing the existing annotation with the new codec?

**Comment by jackgr** [comment]
No, the type meta provides access to the version, regardless of the codec. We can simply compare the versions between annotation and command line input to determine whether or not there's a conflict.

**Comment by deads2k** [comment]
Sorry, I'm still struggling with how there is sufficient information to do this properly.  Can you walk me through this example?

```go
type Foo struct{
    a, b, c, d, eAndF string
}

type FooV1 struct{
    // c is defaulted to "one"
    aAndB, c, d string
}

type FooV2 struct{
    // a is defaulted to "two"
    a, b, cAndD string
}
```

 1. call apply with `FooV1.aAndB="alfa/bravo"`
 1. call apply with `FooV2.b="charlie"` and `FooV2.c="delta"`

Now, intent-wise, this should produce a conflict because `charlie` will collide with `bravo` in the internal copy, but I don't see any way to properly determine that without explicit conversion.  I can also write examples that require defaulting order to do conversions.

Can you walk me through how you'll detect the conflict?

**Comment by liggitt** [comment]
If I'm following correctly, @jackgr is proposing considering FooV2 as a conflict because of the version difference, without even looking at the fields. Not sure how good an experience it is, but it would sidestep all the conversion/defaulting issues. It would basically mean resetting your apply base any time you bumped versions of the API you were working with, right?

**Comment by liggitt** [comment]
Nope, re-read:

> If the version provided by the caller is newer than the version in the annotation, we use what the caller provided to create the annotation and the patch, effectively upgrading the annotation. The patch will contain the version they provided.

In that particular case, I agree with @deads2k, I think you have to do a conversion of the annotation version, which means defaults and conversions get applied, and user-provided fields become ambiguous

**Comment by jackgr** [comment]
First, I assume the reason you mention `Foo` is that we start there. Without it, we have no baseline against which to compare. However, you didn't mention the values provided for `Foo` to start the scenario, I'm assuming that the user calls `kubectl create`, passing values for all of the properties of `Foo`. The annotation is attached and contains what the user passed. The current state of the object is the values of `a`, `b`, `c`, `d` and `eAndF` supplied by the caller. Let's assume that the passed values are as follows:

```
kind: Foo
version: v0
a: alfa
b: bravo
c: charlie
d: delta
eAndF: echo/foxtrot
```

The current state now looks like this:

```
kind: Foo
version: v0
a: alfa
b: bravo
c: charlie
d: delta
eAndF: echoAndFoxtrot
annotation:
  kind: Foo
  version: v0
  a: alfa
  b: bravo
  c: charlie
  d: delta
  eAndF: echo/foxtrot
```

The user now calls `kubectl apply`, passing `Foo1V1`, with the following values:

```
kind: Foo
version: v1
aAndB: alfa/bravo
```

Since `a`, `b`, `c`, `d` and `eAndF` are not present in what the user supplied, the patch contains tombstones for them.  The patch therefore looks like this:

```
version: v1
a: null
aAndB: alfa/bravo
b: null
c: null
d: null
eAndF: null
annotation:
  version: v1
  aAndB: alfa/bravo
```

After the patch is applied, the current state of the object looks like this:

```
kind: Foo
version: v1
aAndB: alfa/bravo
c: one
annotation:
  version: v1
  aAndB: alfa/bravo
```

The value of `c` defaults to `one`, and `d` is not present in the current state, because it was deleted by the patch, with no default provided.

The user now calls `kubectl apply`, passing `FooV2`, with the following values:

```
kind: Foo
version: v2
b: charlie
c: delta
```

Since `aAndB` is not present in what the user supplied, the patch contains a tombstone for it. The patch therefore looks like this:

```
version: v2
aAndB: null
b: charlie
c: delta
annotation:
  version: v2
  b: charlie
  c: delta
```

Since `FooV2` doesn't contain a property named `c`, `kubectl apply` gets an error from the api server, which it returns to the user. The current state of the object is unchanged.

**Comment by jackgr** [comment]
Also, in the last scenario, note that if the user had provided a value for `a`, which does exist, rather than a value for `c`, which doesn't exist, then there would have been no error from the api server. In that case, here's what the user would provide:

```
kind: Foo
version: v2
a: delta
b: charlie
```

The patch would look like this:

```
version: v2
aAndB: null
a: delta
b: charlie
c: null
annotation:
  kind: Foo
  version: v2
  a: delta
  b: charlie
```

After application of the patch, the current state would look like this:

```
kind: Foo
version: v2
a: delta
b: charlie
annotation:
  kind: Foo
  version: v2
  a: delta
  b: charlie
```

**Comment by deads2k** [comment]
Sorry there was confusion there.  `Foo` is the internal version so you can see what you're encoding/decoding to.  In our scheme's, version=`""` is the internal.  I think that will probably change the scenario you built.  

`Foo` = internal, `FooV1` = first external version of `Foo`, `FooV2` = second external version of `Foo`.

**Comment by deads2k** [comment]
I had no idea that `apply` worked like that, stomping fields it didn't know about and that don't even exist in its version of the scheme.  I'm having trouble reasoning about what I think this command does and it accomplishes it in a predictable way.  I'll come back and try again after the rest of the morning's email.

At first blush, it seems like a very dangerous to command to use near version boundaries.

**Comment by jackgr** [comment]
Clearly, there's miscommunication hear about how apply works. Of course, it
does not delete things it doesn't know about. It only deletes things the
user has asked to delete. Likewise, it only writes properties that the user
has provided values for, and only overwrites when asked to do so with a
–-overwrite flag. It isn't dangerous in any way..

I think the problem here is that I misunderstood your example. That said, I
don't think it was well formed. Let's talk off-line about how to craft a
valid example, and then show how it works.

On Monday, November 16, 2015, David Eads <notifications@github.com> wrote:

> I had no idea that apply worked like that, stomping fields it didn't know
> about and that don't even exist in its version of the scheme. I'm having
> trouble reasoning about what I think this command does and it accomplishes
> it in a predictable way. I'll come back and try again after the rest of the
> morning's email.
>
> At first blush, it seems like a very dangerous to command to use near
> version boundaries.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/16543#issuecomment-157019834>
> .
>


-- 
Jack Greenfield | Google

**Comment by liggitt** [comment]
API versions allow fields to be added or removed or change meaning. It looks like apply isn't regarding API versions when computing patches, right? Let's take a more realistic example:

Let's say in v1, we have a couple attributes in the schema:
```
v1 Foo {
  host string  // defaults to 127.0.0.1
  port string  // defaults to 80
}
```

In V2, we realize we want the user to request host/port using a different field, and we use the old field names to indicate the allocated host/port.
```
v2 Foo {
  requestedHost string  // defaults to 127.0.0.1
  requestedPort string  // defaults to 80
  host string  // populated by a controller when a host is allocated
  port string  // populated by a controller when a port is allocated
}
```

1. A user submits:
```
kind: Foo
apiVersion: v1
host: myhost.com
```

2. Object is persisted as
```
kind: Foo
apiVersion: v1
annotation:
  kind: Foo
  apiVersion: v1
  host: myhost.com
host: myhost.com
port: 80 // from default
```

3. Later, using the v2 API the user tries to request a specific port:
```
kind: Foo
apiVersion: v2
requestedHost: myhost.com
requestedPort: 443
```

If I understand correctly, `apply` would diff directly against the annotation and come up with the following patch:
```
apiVersion: v2
host: null
port: null
requestedHost: myhost.com
requestedPort: 443
```

Because it did not consider different API versions when building the patch, `apply` would submit a patch to the v2 API that clears fields the user never intended to clear.

**Comment by jackgr** [comment]
Thanks, @liggitt. That's a much clearer example. The patches and annotations shown are what apply would generate. Several thoughts in reply:

* When the patch in step 3 is applied, `host` will be deleted. IIUC, it will be set some time later, based on the value the user set in `requestedHost`. What will happen in this case?
*  When #17238 is implemented, `kubectl apply` will pass `false` for the `force` flag argument to CreateStrategicMergePatch. As a result, the change submitted by the user in step 3 will fail with a conflict, since it deletes `host`, which was populated by a controller. The user can force the deletion of `host` using the --overwrite flag, or cause the object to be deleted and recreated from scratch using the --force flag.
* An alternate solution would be to always delete and recreate when the version changes.
* It seems like a bad idea to define new fields, in this case `host` and `port`, maintained by controllers, using now deprecated field names once exposed to users. If instead the new fields were called 'allocatedHost' and `allocatedPort`, the existing behavior would not cause any problems. While it makes sense to implement #17238, and perhaps to always delete and recreate when the version changes as an additional measure of assurance, it would also make sense to avoid overloading properties names, if possible.

**Comment by liggitt** [comment]
> When the patch in step 3 is applied, host will be deleted. IIUC, it will be set some time later, based on the value the user set in requestedHost. Is this an appropriate outcome, or would it cause problems (e.g., scheduling problems due to the removal of a required field)?

It's a hypothetical example, so I'm not sure :) The main point was that `apply` has to be version-aware to correctly determine which fields are user-specified when working across versions.

> When #17238 is implemented, kubectl apply will pass false for the force flag argument to CreateStrategicMergePatch. As a result, the change submitted by the user in step 3 will fail with a conflict, since it deletes host, which was populated by a controller.

How does `apply` know `host` was populated by a controller?

> If the new host and port properties populated by a controller are mandatory in the api server, then any attempt to delete them will fail. IMO, we should prevent the user from deleting properties required for correct function.

Again, hypothetical example, but host/port probably wouldn't be required if Foo could be created without them set and they got populated later by a controller.

> An alternate solution would be to always delete and recreate when the version changes.

If you mean delete/recreate the apply annotation, that's actually what I originally thought was being proposed (see https://github.com/kubernetes/kubernetes/issues/16543#issuecomment-156768784)

> It seems like a bad idea to define new fields maintained by controllers, in this case host and port, using now deprecated field names once exposed to users.

Versioning the API lets us make changes like that safely, using defined conversions. Putting constraints on field name interactions between API versions, to allow other components to ignore API versioning does not seem like a good precedent. In cases where a single field was serving two purposes, and a future API version wants to address those purposes using two distinct fields, using the old field name for one of the purposes seems very reasonable.

> perhaps to always delete and recreate when the version changes as an additional measure of assurance

just to clarify, you're thinking of deleting/recreating the apply annotation, not the whole object, right?

**Comment by jackgr** [comment]
> For argument's sake, let's say that there's a manual review process to allocate a hostname, and clearing the allocated host field results in a multi-day outage :)

:0)

> How does apply know host was populated by a controller?

Because its value has changed between the annotated configuration and the live configuration in a way that differs from the user's input. Of course, this interpretation relies on user input maintaining the annotation, which we've been careful to do.

> If you mean delete/recreate the apply annotation, that's actually what I originally thought was being proposed (see #16543 (comment)).

Yes, that's what I meant. It's worth considering as a simple solution. Not sure it's the best experience we can offer, however, per your comment, since the user would lose their historical context. That said, if we can't find a clean and simple way to use their historical context when the version changes, then maybe it is the best experience we can offer. At this point, I'm tempted to do just that, since this feature is dragging out a long time.

> Versioning the API lets us make changes like that safely, using defined conversions.

Well, another approach would be to up convert the annotation when we see user input from the future, and then use the up converted annotation to generate the patch.

> just to clarify, you're thinking of deleting/recreating the apply annotation, not the whole object, right?

Yes. Sorry, that should have been made more clear.

**Comment by bgrant0607** [comment]
`annotations` is a field in `metadata`, and the apply annotation is represented as a single annotation.

**Comment by bgrant0607** [comment]
This should really be covered by a design doc: #15894.

**Comment by liggitt** [comment]
Yes, sorry. The "annotation" content above would be serialized into a single annotation as a JSON string

**Comment by lavalamp** [comment]
I probably don't need to ask this, but on the off chance-- we don't have
the possible bug here where every time you use apply to update the
annotation doubles in size (due to including itself), right?

**Comment by liggitt** [comment]
yes, recursive annotation inclusion is prevented

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by liggitt** [comment]
server-side apply no longer uses the apply annotation

/close
