### ISSUE TITLE
Need to cherry-pick #16553

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#16555]
#16553 fixes versionize-docs.sh and mark-new-version.sh to rewrite links to release branch rather than to the tag.

**Comment by ihmccreery** [comment]
That's #16553, not #16533, I believe.

**Comment by mikedanese** [comment]
Wrong PR Number

**Comment by caesarxuchao** [comment]
#16564 is the CP.

**Comment by mikedanese** [comment]
Ops never mind.
