### ISSUE TITLE
Broken link api-groups in gh-pages

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#16552]
In http://kubernetes.io/v1.1/docs/api.html#api-groups, the link to **API groups** http://kubernetes.io/v1.1/docs/proposals/api-groups.md is incorrect. Shouldn't it be .html?

cc @bgrant0607 @caesarxuchao @nikhiljindal

**Comment by bgrant0607** [comment]
That file doesn't exist. Should be http://kubernetes.io/v1.1/docs/proposals/api-group.html

**Comment by bgrant0607** [comment]
Link needs to be fixed in master.

**Comment by janetkuo** [comment]
Fixing it

**Comment by bgrant0607** [comment]
But it also demonstrates that some munger is confused.

**Comment by janetkuo** [comment]
Yes, and it'd be useful if munger can verify if the link referenced in .md works

**Comment by bgrant0607** [comment]
There are no .md docs on kubernetes.io, so no such links should exist. The munger should direct to the release branch in the case the doc isn't present in gh-pages, or to HEAD if the doc isn't present in the release branch. Obviously if the doc doesn't exist anywhere, the link isn't going to work, so it would be useful to print a warning in that case.

**Comment by caesarxuchao** [comment]
Our munger should caught this relative link is invalid:
https://github.com/kubernetes/kubernetes/blob/master/cmd/mungedocs/links.go#L120
