### ISSUE TITLE
Test failure information no longer shows in shippable?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16562]
e.g., see: https://app.shippable.com/builds/56324fc9d15e2a0c007008ef

A test fails, but I can't figure out how to see the actual failure messages. @ixdy am I missing something or did this break?

**Comment by ixdy** [comment]
Looks like this test failed:
`FAIL	k8s.io/kubernetes/pkg/storage/etcd	6.373s`

but I have no idea why the test report doesn't show that. On Jenkins it's easier to debug, since we save more of the test output, but it's unfortunately hard to debug this on Shippable.

**Comment by hurf** [comment]
Recently most of the PRs fail on this test, with go 1.3. But I tested it locally with go 1.3 and it works fine. There must be a shippable bug but I just can't figure it out.

**Comment by lavalamp** [comment]
https://app.shippable.com/builds/563c7c07fa4c6c0d002fe407 (#16914)

Hard to repro flakes that only fail on shippable are basically impossible to debug right now because of this. @ixdy could it be the script that you had stripping the verbose output out?

**Comment by ixdy** [comment]
@lavalamp in that most recent one the tests timed out, so the test report generation never occurred.

**Comment by ihmccreery** [comment]
We disabled Shippable, so I'm closing this as obsolete.
