### ISSUE TITLE
Problem statement: Generate clients and rest setup code from... what?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16560]
Background: Client proposal in #15730, api type structure proposal in #16062

At first I was thinking we'd generate based on tags in the comments, e.g. something like:

``` go
// Pod documentation here
// +generate=Create,Update,List,Get,Delete
type Pod struct {
  ...
}
```

And the result would be something like our current PodsNamespacer client. But then I got to thinking that it'd be super nice to have type information in the methods, to handle the case where e.g. the Binding() method takes an *v1.Binding.

``` go
type PodsREST interface {
  Create(*Pod) *Pod
  Update(*Pod) *Pod
  List(???) *PodList
  Binding(*Binding) *Status
}
```

This has some downsides, like how do you represent query parameters, or the fact that you'll either get a *Pod or a *Status (i.e., error) back? Or that that you must POST to Binding?

We could model one layer down.

``` go
type PodsPOST struct {
  Parameters *POSTParams
  ReqBody *Pod
  RespBody *Pod
}

type PodsREST struct {
  POST PodsPOST
  ...
  bindings PodBindingsREST
}

type PodBindingsREST struct {
  POST BindingsPOST
}

type BindingsPOST struct {
  Parameters *POSTParams
  ReqBody *Binding
  RespBody *Status
}
```

This has disadvantages: it's starting to get quite complex and verbose, there's still no good go way to indicate union types.

So we need to explore alternatives.
- Always generate clients from swagger? Then we don't need to solve this until we want to generate the rest setup code. This is probably the most obvious thing to do, which is why I'm filing this as only P2.
- Switch to proto? The RPC/service stuff there isn't super natural for describing REST either, but it can work. This would be very disruptive, though.

**Comment by krousey** [comment]
Just skimming through this as I'm about to get on a shuttle. Is this suggesting that we generate client AND types from some IDL instead of generating an IDL from Go source code? If so, I like that :smile:

**Comment by wojtek-t** [comment]
@lavalamp - I think those non-standard methods are relatively rare (at least now). So it is significantly better than what we have now to even generate only those that are standard.

>
    type PodsREST interface {
      Create(*Pod) *Pod
      Update(*Pod) *Pod
      List(???) *PodList
      Binding(*Binding) *Status
    }

Regarding List (and similar methods), I think that we should unify the signatures, so although this is currently a problem - it shouldn't be.

Also, even for non-standard methods (like UpdateStatus), I think that we can generated them automatically, based on the tag.

**Comment by smarterclayton** [comment]
Out of date.
