### ISSUE TITLE
kubectl apply --force

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#16569]
Similar to kubectl replace --force, we should support kubectl apply --force, but it should only delete and re-create the resource if the patch fails.

cc @jackgr

**Comment by jackgr** [comment]
@bgrant0607 progress on this issue is blocked waiting for #17238, which is blocked waiting for #16980 to merge.

**Comment by ymqytw** [comment]
Anyone working on this issue? I can pick it up, if no one is working on it.
