### ISSUE TITLE
Document doc release process

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#16561]
Forked from #15893 and #16102.

After we publish 1.1 docs, we should document a process that would make sense for 1.2.

cc @nikhiljindal @caesarxuchao @janetkuo @krousey @ihmccreery @thockin @lavalamp

**Comment by resouer** [comment]
@bgrant0607 Really need this, I'm working on #17887 but don't know how :( ... seems #16087 is also related?

**Comment by nikhiljindal** [comment]
I will add a doc

**Comment by nikhiljindal** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/17983.
@resouer Please have a look and let me know if I missed anything.

**Comment by resouer** [comment]
Thanks a lot, I will try this in these days and give you feedback

**Comment by bgrant0607** [comment]
@resouer #16087 is not directly related.
