### ISSUE TITLE
Namespaces not created but visible in kubectl

### ISSUE THREAD

**Issue by plamer** [kubernetes/kubernetes#16588]
Hello,

It seems my namespaces are not being created automatically when some object is created in that namespace. Here is my k8s version:

    {
      "major": "1",
      "minor": "0",
      "gitVersion": "v1.0.6",
      "gitCommit": "388061f00f0d9e4d641f9ed4971c775e1654579d",
      "gitTreeState": "clean"
    }

From the cli:

    kubectl get namespaces
    NAME      LABELS    STATUS
    default   <none>    Active

    kubectl get pods --all-namespaces
    NAMESPACE     NAME                READY     STATUS                                                                            RESTARTS   AGE
    cccc       nodejs              1/1       Running                                                                           0          7d
    aaaa       varna-aohhn         1/1       Running                                                                           0          6d
    aaaa       varna-iqbni         1/1       Running                                                                           0          6d
    aaaa       varna-rflw6         1/1       Running                                                                           0          6d
    bbbb      ghost-kwzu5         1/1       Running                                                                           0          5d

API call to http://master/api/v1/namespaces/aaaa returns code 404.

Can someone tell me if this is a bug or I've misconfigured something?

**Comment by feihujiang** [comment]
Yes，as I know, namespaces are not being created automatically, you should create namespace firstly, then create resource in the namespace you created.

**Comment by feihujiang** [comment]
Now it returns an error message  "Error from server: error when creating "./examples/blog-logging/counter-pod.yaml": namespaces "notexistent" not found". Server Version: version.Info{Major:"1", Minor:"2+", ...}

**Comment by lavalamp** [comment]
Yes, you have to create your namespaces ahead of time. Quite some time ago, you didn't have to. Is it possible you created those pods in a really old k8s version, and then upgraded to 1.0.6?

**Comment by lavalamp** [comment]
(you can fix this by just creating the namespaces)

**Comment by lavalamp** [comment]
Please reopen if still an issue.
