### ISSUE TITLE
[AWS] all nodes marked "unhealthy" while EC2 API down

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#16593]
We had a quite serious case today which caused all our pods to terminate because AWS had trouble with their EC2 service in Ireland (6:00 AM PDT)

Basically after 40s (corresponding to [`node-monitor-grace-period`](https://github.com/kubernetes/kubernetes/blob/master/docs/admin/kube-controller-manager.md)) of API downtime during which kubelet couldn't list EC2 instances, it hit the maximum node status retry count and killed everything:

```
12:44:22 kubelet.go:1933] Error updating node status, will retry: failed to get node address from cloud provider: error listing AWS instances: Unavailable: The service is unavailable. Please try again shortly.
status code: 503, request id: []

...

12:45:04 kubelet.go:839] Unable to update node status: update node status exceeds retry count
12:45:10 kubelet.go:1518] Killing unwanted pod "swagger-extcs"
12:45:10 manager.go:1123] Killing container with id "aa4a55984..."
12:45:10 manager.go:1123] Killing container with id "9bdb1788e..."
12:45:10 kubelet.go:1343] Orphaned volume "5796b5eb..." found, tearing down volume
...
```

I could certainly assume that downtimes at AWS may never last more than `t` minutes and increase the `node-monitor-grace-period` and `pod-eviction-timeout` in my kube-controller-manager accordingly, but there is something dangerous in making such assumptions and relying *only* on the cloud provider to define nodes' health, since a not responding cloud provider doesn't mean a completely unhealthy platform.

We paid that price today and saw our whole prod cluster going down while everything was fine on the instances themselves :see_no_evil:

**Comment by a-robinson** [comment]
Thanks for the report @antoineco - that sounds terrible. Mind specifying which version of kubernetes you're on?

cc @justinsb @davidopp

**Comment by antoineco** [comment]
Both 1.0.6 and 1.1.0-beta.

There are definitely workarounds, especially in this case I'm wondering if the cloud provider based health check is really necessary since all kubelets "ping" the master regularly (maybe it's just me who missed the real benefit of listing actual instances by querying the EC2 API)

**Comment by davidopp** [comment]
@brendandburns

**Comment by davidopp** [comment]
ref/ #13398
ref/ #13412

(Brendan says the second one is a better description of the issue, but they are both basically the same as this one.)

**Comment by davidopp** [comment]
#13417 purported to fix this and was merged before 1.1.0-beta IIUC; needs additional investigation.

**Comment by antoineco** [comment]
Sorry, I missed these ones, my search was too narrowed on EC2 specifically. Feel free to close my issue if it's a duplicate, and thank you very much for the quick answer!

**Comment by davidopp** [comment]
I'll leave it open for now because we still need to investigate why you hit this problem running 1.1.0-beta, since the PR I mentioned was in that release.

**Comment by antoineco** [comment]
On 1.1.0-beta (Kubernetes v1.1.0-beta.266+65656cdbd89e08) the log messages were very similar, but the whole cluster went down in the same manner:

```
12:45:04   kubelet.go:2201] Error updating node status, will retry: failed to get node address from cloud provider: error listing AWS instances: Unavailable: The service is unavailable. Please try again shortly.
status code: 503, request id:
12:45:05   kubelet.go:2201] Error updating node status, will retry: failed to get node address from cloud provider: error listing AWS instances: Unavailable: The service is unavailable. Please try again shortly.
status code: 503, request id:
E1030 12:45:05   kubelet.go:907] Unable to update node status: update node status exceeds retry count
I1030 12:45:15   kubelet.go:1929] SyncLoop (UPDATE): "artifactory-730cx_internal"
I1030 12:45:15   manager.go:1344] Killing container "9ca96e0c167... artifactory-pro internal/artifactory-730cx" with 30 second grace period
```

**Comment by brendandburns** [comment]
I actually don't see that PR in the 1.1 release branch.  That PR covers node_manager.go and that file doesn't exist in the release branch as far as I can tell...

We should fix this in the release branch too (I don't think it will cherry-pick in cleanly)

**Comment by brendandburns** [comment]
I will get a PR out for this sometime this evening.

**Comment by brendandburns** [comment]
https://github.com/kubernetes/kubernetes/pull/16633 has a partial fix that will pick cleanly.

I'll think about if/how we can draw in the other fix as well...

**Comment by brendandburns** [comment]
Ok, the backport of #13417 is here:

https://github.com/kubernetes/kubernetes/pull/16641

**Comment by davidopp** [comment]
We've merged #16641 which I believe makes #16633 unnecessary. Once @brendandburns confirms that, we can close this issue.

**Comment by davidopp** [comment]
And thanks very much @antoineco for reporting this problem.

**Comment by antoineco** [comment]
Thank *you* guys for the quick reaction 👍

**Comment by brendandburns** [comment]
@davidopp Yeah, we can close this one.  I think we should still merge in #16633 as it is a good optimization for AWS users that will dramatically reduce the number of API calls we make from worker nodes, but that's not a blocker for this issue or the 1.1 release.

**Comment by antoineco** [comment]
Just one comment on that. I tried to reproduce the situation on v1.1.1 by blocking outgoing traffic to *eu-west-1.ec2.amazonaws.com* on port 443 on one node in the cluster, and this node was evicted almost right away: 

```
kube-controller-manager[1977]: I1120 20:22:17.113012    1977 nodecontroller.go:627] node ip-10-0-12-110.eu-west-1.compute.internal hasn't been updated for 3m14.481979981s. Last ready condition is: {Type:Ready Status:Unknown LastHeartbeatTime:2015-11-20 20:19:01 +0000 UTC LastTransitionTime:2015-11-20 20:19:42 +0000 UTC Reason:NodeStatusUnknown Message:Kubelet stopped posting node status.}
kube-controller-manager[1977]: I1120 20:22:17.128127    1977 nodecontroller.go:419] Evicting pods on node ip-10-0-12-110.eu-west-1.compute.internal: 2015-11-20 20:22:17.128117334 +0000 UTC is later than 2015-11-20 20:22:17.128116321 +0000 UTC + -10s
```

What if *eu-west-1.ec2.amazonaws.com* becomes unreachable like it seemed to be the case when I created this issue? The whole cluster will go down again although all nodes are sane.

**Comment by antoineco** [comment]
The iptables OUTPUT chain used to reproduce:
```
Chain OUTPUT (policy ACCEPT)
target  prot opt source     destination         
DROP    tcp  --  anywhere   178.236.6.52   tcp dpt:https  <- eu-west-1.ec2.amazonaws.com
DROP    tcp  --  anywhere   178.236.4.54   tcp dpt:https  <- eu-west-1.ec2.amazonaws.com
```

After 1 minute:
```
kube-controller-manager[13855]: I1125 18:45:32.528518   13855 nodecontroller.go:627] node ip-10-0-12-110.eu-west-1.compute.internal hasn't been updated for 1m16.322646668s. Last ready condition is: {Type:Ready Status:Unknown LastHeartbeatTime:2015-11-25 18:44:12 +0000 UTC LastTransitionTime:2015-11-25 18:44:56 +0000 UTC Reason:NodeStatusUnknown Message:Kubelet stopped posting node status.}
kube-controller-manager[13855]: I1125 18:45:32.548591   13855 nodecontroller.go:419] Evicting pods on node ip-10-0-12-110.eu-west-1.compute.internal: 2015-11-25 18:45:32.548580631 +0000 UTC is later than 2015-11-25 18:45:32.548579769 +0000 UTC + -10s
kube-controller-manager[13855]: I1125 18:45:35.428727   13855 nodecontroller.go:249] All pods terminated on ip-10-0-12-110.eu-west-1.compute.internal
```

@brendandburns could you please reopen the issue?
