### ISSUE TITLE
[User-guide] Minor issue with persistent-volumes walkthrough 

### ISSUE THREAD

**Issue by fwalker** [kubernetes/kubernetes#16596]
The [pod description](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/persistent-volumes/simpletest/pod.yaml#L15) of the persistent-volumes walkthrough contains the volume mount ``/var/www/html`` which seems to be outdated for the used nginx conatiner which is by default serving from the ``/usr/share/nginx/html`` folder.

As a result, the data wrtitten in ``/var/www/html`` in the node will not be returned by the ``curl`` at the end of the walkthought.

Proposed change: Update the path

**Comment by a-robinson** [comment]
Thanks for bringing up this issue, @fwalker! Would you be up for sending a pull request with the fix?
