### ISSUE TITLE
Event recorder is too strict in counting cached events, can OOM a server

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#16600]
Example scenario:

1. Create a replication controller A
2. Set A.Replicas to N+diff
3. A attempts to create diff pods, and is failed for each
4. For each failure in diff, A records an event with the failure

Problem:
If the error message across each failure is unique, the number of events produced can unexpectedly induce an OOM on the master by overloading etcd.  Common reasons for error messages varying slightly would include the following:

a) the error message including the name of the pod
b) the error message including a timestamp
c) etc.

In our particular instance, we encountered (a) and it resulted in 175488 events being spawned on a rather small deployment that induced OOM scenarios for etcd and killed the node.

**Proposal**
Event.Message should not be used in the event_cache algorithm.

It's too easy for any controller to go rogue, and it can confuse the heck out of users why seemingly common errors repeat in event output.  In my case, when looking at 77000 of those events in one namespace, it stumped me to figure out the difference ;-)

Instead, I think event keys should be the following:

```
func getEventKey(event *api.Event) string {
	return event.Source.Component +
		event.Source.Host +
		event.InvolvedObject.Kind +
		event.InvolvedObject.Namespace +
		event.InvolvedObject.Name +
		string(event.InvolvedObject.UID) +
		event.InvolvedObject.APIVersion +
		event.Reason
}
```

And event.Message should just update to the latest observed message.

Thoughts?

@lavalamp @erictune @wojtek-t @bgrant0607 @smarterclayton

**Comment by lavalamp** [comment]
Proposal sounds reasonable to me.

How long did it take RC to make that many attempts? Perhaps it should retry slower. @davidopp

**Comment by erictune** [comment]
SGTM as a quick fix if you are seeing this as a serious problem.

That said, I find it useful to be able to look at the log of a job and see what pods were created over the lifetime of the job, and this change would eliminate that.  Similarly, I think I want to see when container restarts happened, if they are infrequent (say I wanted to correlate with things happening in other parts of the system, for example).  I lose both of those with your proposed change.  

Ideally, we would preserve detail for well-behaved cases, and collapse it for poorly behaved ones.

A more nuanced fix would something like this:
```
func (eventCache *historyCache) addOrUpdateEvent(newEvent *api.Event) history {
        coarse_key = getEventKeyWithoutMessage(newEvent)
         key := ""
         message := ""
        // TODO: lock access to numEvents
       numEvents[coarseKey] ++
        if numEvents[coarseKey] > MAX_SIMILIAR_MESSAGE_EVENTS_PER_OBJ {
          // This is a frequent event across all events with similar messages, so let's stop
          // adding new messages
          key = coarse_key
          message = "(events with varying messages combined)" 
        else {
           // This is the normal case where there are not too many events with different messages
           key = getEventKey(newEvent)
           message = newEvent.message
        }
        // Store the message
        eventCache.Lock()
        defer eventCache.Unlock()
        eventCache.cache.Add(
                  key,
                  history{
                          Count:           newEvent.Count,
                          FirstTimestamp:  newEvent.FirstTimestamp,
                          Name:            newEvent.Name,
                          ResourceVersion: newEvent.ResourceVersion,
                          Message: message
                  })
          return eventCache.getEventFromCache(key)
```
Say `MAX_SIMILIAR_MESSAGE_EVENTS_PER_OBJ` is 10.
So, the code above is going to save the first 10 events which differ only in message, and then after that, it is going to lump them all together into one event.  

cc: @saad-ali

**Comment by bprashanth** [comment]
> How long did it take RC to make that many attempts? Perhaps it should retry slower. @davidopp

Maybe we should just get a flavor of workqueue that understands util.backoff?

**Comment by bgrant0607** [comment]
cc @vishh

**Comment by derekwaynecarr** [comment]
The error was related to validation, and the response included the generated pod name, which made it unique.  The data is fixed in our case so the immediate bleeding stopped, but I am concerned that there are other control loops that record events that may produce similar problems if the ```Event.Reason``` is fundamentally the same from the actor (controller tried to create a instance of X), but the ```Event.Message``` varies slightly on the generated value from X.  This is why I proposed the nuclear option above in the near term.

@lavalamp - in this particular case, we were running with higher qps/burst values, but I know at Kubernetes defaults of 20/30, it could still have overwhelmed this particular deployment when an operator did not size their cluster for that amount of keys.  The cluster had been sized on a 3GB node, but etcd memory usage started inducing OOM with a rogue event producer in the 1 hr window.  The rapid production of events required > 7GB of RAM for etcd to function even though the workload was VERY basic.

@bprashanth - In the case of the replication controller, back-off would have helped.  Originally, I thought the issue was due to quota/limits in admission, but those properly increment the ```Event.Count``` because the response error message from admission control does not vary based on pod name.  One thing that would have helped is if the controller framework rather than doing Burst attempts per RC in each iteration remembered if the last iteration failed, and throttled back max(Burst/2, 1) on each subsequent pass per RC.  A simple annotation would probably suffice for that use case.

**Comment by derekwaynecarr** [comment]
The fix discussed here is really only addressing the problem for controllers that use our event recorder interface and do client-side event compaction, we may want to think about doing event compaction on the server.

@erictune - I like your suggestion, and agree you should not lose fidelity in well-behaved scenarios.

**Comment by derekwaynecarr** [comment]
I will submit a code change Monday.

**Comment by vishh** [comment]
IIUC, client side event cache is tied to the processes lifetime? We need server side compaction.

**Comment by davidopp** [comment]
+1 for @erictune 's solution

I agree we also need some kind of server-side protection from this; it's not good if a buggy client can cause the master to OOM.

We also should have some kind of backoff for the rate at which RC tries to re-create failed pods, as @lavalamp alluded to in his first comment.

**Comment by bgrant0607** [comment]
I agree with RC backoff, as proposed here: https://github.com/kubernetes/kubernetes/issues/2529#issuecomment-67278765

**Comment by bgrant0607** [comment]
I also like @erictune's proposal.

**Comment by derekwaynecarr** [comment]
I am coding this up now.  The only enhancement to @erictune proposal is to add a time interval for event correlation to know how long to wait between occurrences before we treat the incoming event as new again.  Defaulting that to 1 hr seems fine on the client side event correlation.

**Comment by saad-ali** [comment]
> I am coding this up now. The only enhancement to @erictune proposal is to add a time interval for event correlation to know how long to wait between occurrences before we treat the incoming event as new again. Defaulting that to 1 hr seems fine on the client side event correlation.

Exactly what I was thinking. This proposal SGTM
