### ISSUE TITLE
Update default etcd version

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#16618]
Right now we have 2.0.12 set in quite a few places.  This is from June.  Probably time to update to something newer.  Now is a good time to do it as we can flush out any issues before v1.2 is released.

**Comment by jbeda** [comment]
I'm happy to get a PR together and do some initial testing.  However, I need someone with write access for gcr.io/google_containers to do the following:

1. `cd cluster/images/etcd`
2. edit the `Dockerfile` to update the tag and version to `2.2.1`
3. Run `make`

As this won't update the current image that lots of folks are using, this should be 100% non-breaking.

**Comment by ixdy** [comment]
Probably should update `cluster/mesos/docker/test/bin/install-etcd.sh` and `docs/devel/development.md` too.
