### ISSUE TITLE
Interaction of multiple clusters

### ISSUE THREAD

**Issue by excpt0** [kubernetes/kubernetes#16644]
Is there a solution/article/tool about interaction of multiple clusters on Kubernetes?

**Comment by mikedanese** [comment]
Check out https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/federation.md
and https://github.com/kubernetes/kubernetes/blob/master/docs/admin/multi-cluster.md

cc @quinton-hoole

**Comment by davidopp** [comment]
Also, please use [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes) for questions like this, so everyone can benefit from the answers.

The Kubernetes team scans stackoverflow on a regular basis, to ensure questions are answered.

Thanks for using Kubernetes!
