### ISSUE TITLE
Autoscaling Kubernetes Nodes

### ISSUE THREAD

**Issue by imesh** [kubernetes/kubernetes#16645]
Horizontal pod autoscaling [1] allows to optimize the resource usage based on the actual resource requirement. It is designed to scale the number of pods required to serve a given workload. However if the number of nodes in the Kubernetes cluster is fixed it will consume some amount of resources even though the number of pods running is minimal.

I would like to suggest to implement a feature to autoscale the Kubernetes nodes by talking to the underlying infrastructure as a service platform. This would allow us to fully optimize the resource usage by removing any unnecessary nodes when the incoming request load is low. If the request load goes high, new nodes can be added to the cluster. Please share your thoughts on this.

[1] https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/autoscaling.md

**Comment by piosz** [comment]
cc @fgrzadkowski @mwielgus

**Comment by piosz** [comment]
proposal #15304
