### ISSUE TITLE
go get k8s.io/kubernetes/pkg/api too many errors

### ISSUE THREAD

**Issue by ngtuna** [kubernetes/kubernetes#16643]
I'm playing with k8s by writing a go client to contact k8s api. However, when doing "go get k8s.io/kubernetes/pkg/api", there are too many errors: 

$ go get k8s.io/kubernetes/pkg/api
# k8s.io/kubernetes/pkg/api
../../../k8s.io/kubernetes/pkg/api/types.generated.go:439: r.EncodeEnd undefined (type codec.encDriver has no field or method EncodeEnd)
../../../k8s.io/kubernetes/pkg/api/types.generated.go:454: r.IsContainerType undefined (type codec.decDriver has no field or method IsContainerType)
../../../k8s.io/kubernetes/pkg/api/types.generated.go:457: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
../../../k8s.io/kubernetes/pkg/api/types.generated.go:461: r.IsContainerType undefined (type codec.decDriver has no field or method IsContainerType)
../../../k8s.io/kubernetes/pkg/api/types.generated.go:464: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
../../../k8s.io/kubernetes/pkg/api/types.generated.go:619: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
../../../k8s.io/kubernetes/pkg/api/types.generated.go:637: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
../../../k8s.io/kubernetes/pkg/api/types.generated.go:652: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
../../../k8s.io/kubernetes/pkg/api/types.generated.go:667: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
../../../k8s.io/kubernetes/pkg/api/types.generated.go:682: r.ReadEnd undefined (type codec.decDriver has no field or method ReadEnd)
../../../k8s.io/kubernetes/pkg/api/types.generated.go:682: too many errors

**Comment by mikedanese** [comment]
You need to check out `github.com/ugorji/go/codec` to the revision listed in https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json . Duplicare of #16361

**Comment by mikedanese** [comment]
Lets move discussion to #16361

**Comment by ngtuna** [comment]
Thanks @mikedanese
