### ISSUE TITLE
Clean up failed docker containers

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#16650]
At the moment, if a particular pod is in a CrashBackOff state, it will create and never delete a very large number of docker containers. If this is left running for any amount of time, I've found it can actually fill up the entire storage volume used for docker. This assumes, of course, that the app has some time to write some data before crashing, causing additional storage space to be used for each of the containers.

Perhaps Kubernetes should delete old docker containers that have failed? Especially in backoff circumstances? It adds a lot of complexity to write scripts that automatically connect to every node in the cluster and delete old broken containers.

Would it be better to make this a chron job of some sort?

**Comment by paralin** [comment]
My solution to this was to write a cleanup DaemonSet:

https://github.com/paralin/KubeCleanup

It's really rough but works. In the repo readme I discuss some ideas on how Kubernetes could address this issue.

**Comment by dalanlan** [comment]
kubelet has its own GC policy already. Ref [GC doc](https://github.com/kubernetes/kubernetes/blob/master/docs/admin/garbage-collection.md)
You might want to track #15564 for more detail

**Comment by paralin** [comment]
@dalanlan Thanks. Appreciated.
