### ISSUE TITLE
Limit retries to schedule new pods, if resources are not available with error " 'failedScheduling' Failed for reason PodFitsResources and possibly others"

### ISSUE THREAD

**Issue by babusatasiya** [kubernetes/kubernetes#16652]
While using trial account on gcloud, I setup 100 pods, 55 were successfully started but 45 could not and were in Pending stats, Kuebernetes scheduler was trying to restart container end-less, It would rather hold in pending state and wait for resources available would be good. Kubernetes should have big picture of cluster and if resources gets available, pods in queue will get started rather trying endless, it should do more efficient and better scheduling.

It would be also good to have proper message to say, resources are no more and these containers wont start and even exposing them to kubectl would be good.  

```
I1102 01:48:05.715173       5 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"my-nginx-y87ld", UID:"61683c8a-80ef-11e5-ae47-42010af00002", APIVersion:"v1", ResourceVersion:"3191", FieldPath:""}): reason: 'failedScheduling' Failed for reason PodFitsResources and possibly others
I1102 01:48:05.817766       5 factory.go:214] About to try and schedule pod my-nginx-ea3p5
I1102 01:48:05.818463       5 scheduler.go:127] Failed to schedule: &{{ } {my-nginx-ea3p5 my-nginx- default /api/v1/namespaces/default/pods/my-nginx-ea3p5 616cdde7-80ef-11e5-ae47-42010af00002 3194 0 2015-11-01 23:22:12 +0000 UTC <nil> map[run:my-nginx] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"default","name":"my-nginx","uid":"6d670475-80ee-11e5-ae47-42010af00002","apiVersion":"v1","resourceVersion":"3037"}}]} {[{default-token-qpr58 {<nil> <nil> <nil> <nil> <nil> 0xc208337e70 <nil> <nil> <nil> <nil> <nil>}}] [{my-nginx nginx [] []  [{ 0 80 TCP }] [] {map[cpu:{0.100 DecimalSI}] map[]} [{default-token-qpr58 true /var/run/secrets/kubernetes.io/serviceaccount}] <nil> <nil> <nil> /dev/termination-log IfNotPresent <nil>}] Always <nil> <nil> ClusterFirst map[] default  false []} {Pending []     <nil> []}}
I1102 01:48:05.818820       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-jypo: PodFitsResources
I1102 01:48:05.818980       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-a5nl: PodFitsResources
I1102 01:48:05.819136       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-9sja: PodFitsResources
I1102 01:48:05.819293       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-07x3: PodFitsResources
I1102 01:48:05.819330       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-ybuu: PodFitsResources
I1102 01:48:05.819479       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-s990: PodFitsResources
I1102 01:48:05.819515       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-ckux: PodFitsResources
I1102 01:48:05.819591       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-jypo:
I1102 01:48:05.819637       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-a5nl: PodFitsResources
I1102 01:48:05.819667       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-9sja: PodFitsResources
I1102 01:48:05.819693       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-07x3: PodFitsResources
I1102 01:48:05.819728       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-ybuu: PodFitsResources
I1102 01:48:05.819755       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-s990: PodFitsResources
I1102 01:48:05.819779       5 generic_scheduler.go:47] failed to find fit for pod my-nginx-ea3p5 on node kubernetes-minion-ckux: PodFitsResources
E1102 01:48:05.819586       5 factory.go:262] Error scheduling default my-nginx-ea3p5: Failed for reason PodFitsResources and possibly others; retrying
I1102 01:48:05.819867       5 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"my-nginx-ea3p5", UID:"616cdde7-80ef-11e5-ae47-42010af00002", APIVersion:"v1", ResourceVersion:"3194", FieldPath:""}): reason: 'failedScheduling' Failed for reason PodFitsResources and possibly others
I1102 01:48:05.913193       5 factory.go:214] About to try and schedule pod my-nginx-abvya
I1102 01:48:05.913951       5 scheduler.go:127] Failed to schedule: &{{ } {my-nginx-abvya my-nginx- default /api/v1/namespaces/default/pods/my-nginx-abvya 6174e1e2-80ef-11e5-ae47-42010af00002 3197 0 2015-11-01 23:22:12 +0000 UTC <nil> map[run:my-nginx] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"default","name":"my-nginx","uid":"6d670475-80ee-11e5-ae47-42010af00002","apiVersion":"v1","resourceVersion":"3037"}}]} {[{default-token-qpr58 {<nil> <nil> <nil> <nil> <nil> 0xc2082a2c90 <nil> <nil> <nil> <nil> <nil>}}] [{my-nginx nginx [] []  [{ 0 80 TCP }] [] {map[cpu:{0.100 DecimalSI}] map[]} [{default-token-qpr58 true /var/run/secrets/kubernetes.io/serviceaccount}] <nil> <nil> <nil> /dev/termination-log IfNotPresent <nil>}] Always <nil> <nil> ClusterFirst map[] default  false []} {Pending []     <nil> []}} 
```

**Comment by davidopp** [comment]
> Kuebernetes scheduler was trying to restart container end-less, It would rather hold in pending state and wait for resources available would be good.

This is what it is doing. The log messages you see aren't the pod starting and restarting, but rather the scheduler continuously trying to find a machine for the Pod to run on.  The Pod should stay in PENDING state the whole time.

> Kubernetes should have big picture of cluster and if resources gets available, pods in queue will get started rather trying endless, it should do more efficient and better scheduling.
> It would be also good to have proper message to say, resources are no more and these containers wont start and even exposing them to kubectl would be good.

There are two things we can do here:
(1) [short-term solution] log less frequently when a Pod stays PENDING (don't log every time we try to schedule it)
(2) [long-term solution] have the scheduler cache the fact that the Pod does not fit anywhere, and only have it retry to schedule on a machine when something changes on a machine that might allow it to schedule (for example, free resources increased due to another Pod terminating, or node labels changed, etc.)

**Comment by babusatasiya** [comment]
Thank you for update. I hear you and looks like good proposal.

1. What about exposing the information to client level when it is in Pending state or even further if there is a X number of pods are in Pending state due to resources, it wont allow kubectl to add more PODs to avoid long Pending queue, In sort, failfast would be best. 

2. Is it possible to allow put global limit to avoid scheduling containers which may not be able to kick-off due to resources?
3. Logging message improvement if Kubernetes is not able to start more containers and has known to scheduler about resource constrains than "Failed for reason PodFitsResources and possibly others", Looks more confusing, due to possibly others, It means end-user won't actually know whats fact?

4. Far down the road, If kubectl can expose the resource constrains would be even much better so of analytic - What is the total resources, what is consumes, go more in depth as project gets more matured due to somewhere all resources are stored and it gets exposed using API.

**Comment by davidopp** [comment]
For (1) what information are you referring to when you say "What about exposing the information to client level when it is in Pending stat"? For the second part of (1), I don't think there's a good general way to do this because a new Pod may have a shape that fits even though there is a large pending queue. What you're really asking for, as you mention in (2), is "reject the pod if there are a lot of Pending pods already and the new Pod wouldn't schedule" but this requires consulting the scheduler so it's difficult to do in the admission control phase. But you should be able to write your own custom admission controller that could do whatever admission tests you want, so feel free to experiment with this idea if you want.

For (3), I agree the "possibly others" thing is a bit unsatisfying, but it's a result of the way our scheduler predicate functions work (they exit as soon as they find the first reason a Pod is infeasible, rather than testing all conditions). We'd like to rewrite the scheduler at some point and would consider addressing this issue then, but probably not sooner, as people don't seem to be complaining about this.

Your comment (4) is related to #15743. Feel free to add suggestions there.

**Comment by babusatasiya** [comment]
Thank you for updates. 
1. I like the idea of admission control, I hear you one can write a wrapper to make a API call and if there is a number of Pending pods, before executing kubectl to add more pods. But that would not be clean solution, scheduler has almost all details in terms of cluster capacity and it can turn RED TRAFFIC LINE. When there is a no room for more POD to be added to the cluster.  The RED TRAFFIC line can be used by all client tools to take actions quicker. 

I think I found the exposing logs to client using ```kubectl describe pod my-nginx```.

**Comment by kargakis** [comment]
@kubernetes/sig-scheduling-misc

**Comment by kargakis** [comment]
@kubernetes/sig-scalability-misc
