### ISSUE TITLE
Creating a rootscoped resource with namespace doesn't return an error or a warning

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#16658]
When I create a PersistentVolume  using the following config file:
~~~
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: default
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.999.999.999
    path: "/"
~~~
We know PersistentVolume is not namespaced. But it doesn't return  an error or a warning. 
Do we need to validate to return an error or a warning?

and the same handler to ``` ./cluster/kubectl.sh get persistentvolume --namespace=default```

**Comment by alex-mohr** [comment]
@kubernetes/rh-storage persistentVolumes of interest?

**Comment by markturansky** [comment]
It would be easy to add this validation, but I don't see any other validation of the sort in pkg/api/validation/validation.go

Is there another rootscoped resource I can look at for comparison?

It looks like Node has very little validation generally.  No namespace validation.

**Comment by thockin** [comment]
this should fail already.  ValidatePersistentVolume()
calls ValidateObjectMeta() and that checks namespace.  And yet it doesn't
fail.

**Comment by thockin** [comment]
It doesn't appear to be validating namespace at all.  an invalid name in
there does not fail either.  Is some logic in the REST for PV clearing that
field?

**Comment by thockin** [comment]
pkg/api/rest/create.go BeforeCreate() says:

56     if strategy.NamespaceScoped() {
57         if !api.ValidNamespace(ctx, objectMeta) {
58             return errors.NewBadRequest("the namespace of the provided
object does not match the namespace sent on the request")
59         }
60     } else {
61         objectMeta.Namespace = api.NamespaceNone
62     }

**Comment by markturansky** [comment]
Ah, yes, I remember now :)

I suppose the next question is which is called first: validation or BeforeCreate?

If BeforeCreate, do I remove line 61 and instead put an error in validation?

**Comment by markturansky** [comment]
or, I should say, let validateObjectMeta fail?  I see where it would fail if the namespace was not stripped from the PV.

**Comment by thockin** [comment]
The question is: Is it an API error to fill in the namespace field on a
non-namespaced object, or should we ignore namespace as we do with other
non-existent fields?

Put another way - ObjectMeta for PV probably should not even have a
namespace field.  we ignore unknown fields, so I think the right fix is to
leave it.  Maybe add a comment in ValidateObjectMeta() that namespace
should already be cleared for objects that are always root-scope, but some
objects (like events) are both.

**Comment by markturansky** [comment]
Easy enough to comment in ValidateObjectMeta that namespace has been removed for these type of objects.  

It doesn't seem like an error if the PV has a namespace.  It is rightly ignored.   I don't know where/how we return warnings in the API.

The docs are already clear that PVs have no namespace.

**Comment by thockin** [comment]
We don't have API warnings (yet?)

**Comment by feihujiang** [comment]
OK, I'll add a comment in ValidateObjectMeta() that namespace
should already be cleared for objects that are always root-scope.

**Comment by markturansky** [comment]
@feihujiang SGTM
