### ISSUE TITLE
kubectl describe quota doesn't always format quantities

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#16654]
```
$ kubectl --namespace=demos describe quota demo-quota
Name:		demo-quota
Namespace:	demos
Resource	Used		Hard
--------	----		----
cpu		100m		4
memory		268435456	4Gi
```

268435456 should be 256 Mi?

**Comment by hurf** [comment]
I'm always confused about the Quantity format conversion. The phenomenon mentioned here must be caused by usedQuantity, for it's in the format of DecimalSI.

**Comment by thockin** [comment]
quantity format really depends on the resource being represented.

**Comment by sdminonne** [comment]
@thockin @hurf since in I'm having a look at quotas: Are you still facing this? I couldn't reproduce.

**Comment by thockin** [comment]
The 256Mi formatting is fixed.  I have a new issue, though.  New bug coming.
