### ISSUE TITLE
mesos kubernetes is not honoring --max-pods parameter

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#16663]
Using head of release-1.1 with default --max-pods=40. I was creating 100 pods on 2 slave nodes, which should have stopped creating once 80 pods were created, but it kept going and all 100 pods were created.

The pod spec I was using is (where container name is varied from 1 to 100)
```
apiVersion: v1
kind: Pod
metadata:
  name: cont100
spec:
  containers:
  - name: cont100
    image: gcr.io/google_containers/pause:0.8.0
    resources:
      limits:
        memory: "8Mi"
        cpu: "1m"
```

`kubectl describe node` correctly stated that max pods is 40

Capacity:
 memory:        8209620Ki
 pods:          40
 cpu:           4

However, a few lines below, it says 50 pods were created.
Non-terminated Pods:            (50 in total)
  Namespace                     Name            CPU Requests    CPU Limits      Memory Requests Memory Limits
  ─────────                     ────            ────────────    ──────────      ─────────────── ─────────────
  default                       cont11          1m (0%)         1m (0%)         8Mi (0%)        8Mi (0%)
  default                       cont13          1m (0%)         1m (0%)         8Mi (0%)        8Mi (0%)
  default                       cont15          1m (0%)         1m (0%)         8Mi (0%)        8Mi (0%)
  default                       cont17          1m (0%)         1m (0%)         8Mi (0%)        8Mi (0%)
  default                       cont19          1m (0%)         1m (0%)         8Mi (0%)        8Mi (0%)
  default                       cont21          1m (0%)         1m (0%)         8Mi (0%)        8Mi (0%)
  default                       cont23          1m (0%)         1m (0%)         8Mi (0%)        8Mi (0%)

**Comment by huang195** [comment]
One other useful information is when running k8s in standalone mode, `--max-pods` is honored

**Comment by huang195** [comment]
cc @jdef

**Comment by jdef** [comment]
@sttts @karlkfi related failing conformance and/or e2e tests?

**Comment by sttts** [comment]
I don't think there is a e2e test for that. It's a cluster setting and e2e tests cannot change them on the fly.

**Comment by karlkfi** [comment]
Yet another case that needs black box deploy/destroy capability to test.

**Comment by huang195** [comment]
Any idea why --max-pods is not honored by kubelet executor? Under the cover it calls kubelet and passes it all the parameters it gets from the commandline

**Comment by sttts** [comment]
@huang195 maybe because we patch the node capacity. Can you check your nodes with `get nodes -o yaml`?

**Comment by sttts** [comment]
as a background: we do that from the scheduler right now because the kubelet does not assume the same values as Mesos at the moment, giving strange effects.

**Comment by huang195** [comment]
@sttts it's showing the same result as `describe nodes`
```
   capacity:
      cpu: "4"
      memory: 8209620Ki
      pods: "40"
```

**Comment by huang195** [comment]
Looks like k8sm scheduler only takes into account of a mesos offer, which includes things such as cpu, memory, network ports, etc., that are common across mesos and k8s, but k8s-specific resources such as `--max-pods` are not considered at all.

**Comment by sttts** [comment]
@huang195: right, the scheduler does not consider that, but should.

Closing this ticket in favor of https://github.com/mesosphere/kubernetes-mesos/issues/613.
