### ISSUE TITLE
Cross-namespace privilege escalation attack allowed by HPA

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#16661]
An HPA request is submitted against namespaceA, but contains a reference to namespaceB (https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L75).  The request is accepted because I have rights to create on in namespaceA, but no checking is done to see if I can scale what I'm asking.

The HPA request has a namespace, but it also duplicated a namespace field instead of using a `LocalObjectReference` extended with `kind` and `subresource` field.  The HPA controller then blindly uses the second namespace field: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L99.

This allowed someone in the dev namespace to accidentally (or intentionally) scale down resources in the production namespace.

@ncdc Can you help me find the right groups to call out?

**Comment by deads2k** [comment]
@liggitt happy monday.

**Comment by liggitt** [comment]
@kubernetes/kube-api @bgrant0607 can you weigh in on this approach to cross-API-group object references:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L70-L82

In my opinion, we should only have `ObjectReference` and `LocalObjectReference`, and make them work correctly with API groups and subresources. This is a third type of object reference thing, which concerns me. I agree with @deads2k that HPA should use a LocalObjectReference. Replication controllers create pods in their namespace, an HPA request should be to scale things in its namespace.

**Comment by deads2k** [comment]
@smarterclayton We'll need a fix on our side for 3.1

**Comment by bgrant0607** [comment]
The number of Go types does not concern me. In the future, we may well need more types in order to provide context-specific documentation, for instance.

I'm fine with eliminating Namespace from SubresourceReference.

cc @kubernetes/autoscaling @brendandburns

**Comment by liggitt** [comment]
Extracted from https://github.com/kubernetes/kubernetes/pull/16668#issuecomment-153078877:
 > `validateHorizontalPodAutoscalerSpec` also needs to ensure kind, name, and subresource are non-traversing. I'm not familiar enough with the client to know how a name of ../../../foo is handled. Even if the client correctly encodes it (..%2f..%2f..%2ffoo), that would not be sufficient to prevent traversal on the API side

**Comment by thockin** [comment]
The value of keeping Namespace in the the various Reference objects is that
the object is sort of incomplete without it.  I discussed this just last
week Daniel regarding Event.

That said, if we got rid of Namespace from all *Reference types except
places where cross-namespace refs are specifically allowed, I'd be happy.
Do we have any such places?

Isn't this a breaking change, though?

**Comment by deads2k** [comment]
> Isn't this a breaking change, though?

This is a "feature" that should never have existed.  It doesn't make sense to have an HPA in namespaceA change resources in namespaceB.  That would be like an RC controlling pods in another namespace.

**Comment by bgrant0607** [comment]
We would like to cut 1.1 tonight. @deads2k or @liggitt: could one of you please create a PR removing namespace from SubresourceReference?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/16668

**Comment by liggitt** [comment]
can cherry pick to 1.1 once that has LGTM

**Comment by brendandburns** [comment]
LGTM'd

**Comment by brendandburns** [comment]
Closing this, it's been merged and cherry-picked.
