### ISSUE TITLE
Kubectl --rm flag (like docker)

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#16672]
I find that I frequently want to run a command in my cluster to test something.  When that command is done, I want the pod to be removed.  Soemthing like:

```
$ kubectl run date -i --tty --rm --restart=Never --image=busybox -- nslookup foobar
```

**Comment by dalanlan** [comment]
Quick comment. 
IIUC, this could raise potential issues in which case the restart policy is not `Never`. Both you and kubelet could be crazy somehow.
If you're going to support this it's better that you validate the UX.

**Comment by dalanlan** [comment]
/cc @dchen1107 who went against this idea.
Copied from [#12856(comment)](https://github.com/kubernetes/kubernetes/issues/12856#issuecomment-132740352)

>But according to use docker feature like docker run --rm, I don't think it is a good idea for Kubernetes which is designed for managing containerized applications across multiple hosts (many eventually). Thinking about the user deploying a pod which has a container, using docker run --rm will immediately remove the terminated container, no matter succeeded or failed. You lost the information related to that container instance. Even we plan to improve kubelet to use lifecycle events for better performance and lower the overheads, but still a lot of information cannot be conveyed through events, for example, container logs, etc.

**Comment by feihujiang** [comment]
Yes,  if just pod to be removed, this could raise potential issues in which case the restart policy is not Never. So in my implementation, removing the job or replication controller created in this command, is it OK?

And one other question, My implementation only support --rm flag when enable interactive mode, is this OK?  Or should we support --rm flag whatever mode is,  like docker --rm?

**Comment by deads2k** [comment]
> Or should we support --rm flag whatever mode is, like docker --rm?

Based on the doc, https://docs.docker.com/engine/reference/run/#detached-d, you can't use `--rm` in combination with `-d` (detached).

**Comment by feihujiang** [comment]
@deads2k, thanks for correcting me. 

Which mode in kubernetes is similar to “detached” mode?

I know we should support the following example:
~~~
$ kubectl run date -i --tty --rm --restart=Never --image=busybox
~~~
But should we support the following example(no -i --tty)?
~~~
$ kubectl run date --rm --restart=Never --image=busybox -- sleep 10
~~~

**Comment by deads2k** [comment]
If `-i` or `--attach` are specified, then `--rm` is allowed.

**Comment by feihujiang** [comment]
So we don't need to support '''$ kubectl run date --rm --restart=Never --image=busybox -- sleep 10'''

But docker could support the following example:
~~~
$ docker run --rm --name nginx-app busybox sleep 10
~~~

**Comment by deads2k** [comment]
`docker run` runs attached by default.  `kubectl run` runs detached by default.

**Comment by feihujiang** [comment]
Thanks, I got it.
