### ISSUE TITLE
APIserver returns inconsistent HTTP response status codes

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#16686]
From kube-apiserver.log, Kube-apiserver returns 200 as Success code upon some requests, otherwise return 0 as Success.  

I1102 20:11:33.640539       5 handlers.go:131] GET /api/v1/nodes/kubernetes-minion-3io1: (2.683448ms) 200 [[kubelet/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 10.240.0.5:60298]
I1102 20:11:33.650298       5 handlers.go:131] PUT /api/v1/nodes/kubernetes-minion-3io1/status: (5.474235ms) 200 [[kubelet/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 10.240.0.5:60298]
I1102 20:11:34.705053       5 handlers.go:131] GET /api/v1/nodes: (2.139174ms) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51473]
I1102 20:11:37.294175       5 handlers.go:131] GET /api/v1/nodes/kubernetes-minion-jmxr: (1.452673ms) 200 [[kubelet/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 10.240.0.3:35008]
I1102 20:11:37.302534       5 handlers.go:131] PUT /api/v1/nodes/kubernetes-minion-jmxr/status: (4.833358ms) 200 [[kubelet/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 10.240.0.3:35008]
I1102 20:11:38.218652       5 handlers.go:131] GET /healthz: (104.272µs) 0 [[Go 1.1 package http] 127.0.0.1:51479]
I1102 20:11:39.099377       5 handlers.go:131] GET /api/v1/watch/persistentvolumes?resourceVersion=1687: (9.998412938s) 0 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51469]
I1102 20:11:39.106081       5 handlers.go:131] GET /api/v1/watch/persistentvolumeclaims?resourceVersion=1687: (10.000876825s) 0 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51470]
I1102 20:11:39.119484       5 handlers.go:131] GET /api/v1/watch/persistentvolumes?resourceVersion=1687: (9.998155747s) 0 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51471]
I1102 20:11:39.202130       5 handlers.go:131] GET /api/v1/watch/namespaces?resourceVersion=1667: (59.977954152s) 0 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.5:34499]
I1102 20:11:39.708804       5 handlers.go:131] GET /api/v1/nodes: (1.471292ms) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51473]
I1102 20:11:40.100355       5 handlers.go:131] GET /api/v1/persistentvolumes: (884.225µs) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51473]
I1102 20:11:40.105488       5 handlers.go:131] GET /api/v1/persistentvolumeclaims: (942.355µs) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51484]
I1102 20:11:40.120856       5 handlers.go:131] GET /api/v1/persistentvolumes: (1.065416ms) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51486]
I1102 20:11:40.219264       5 handlers.go:131] GET /api/v1/namespaces: (1.441822ms) 200 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.5:34528]
I1102 20:11:40.332206       5 handlers.go:131] GET /api/v1/nodes: (1.958739ms) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51489]

**Comment by lavalamp** [comment]
If it were only the watches I would understand, but it's pretty weird for /healthz.

**Comment by krousey** [comment]
Looking into this, this is likely a false alarm due to an error in pkg/httplog. It assumes that everything calls [`WriteHeader`](https://github.com/kubernetes/kubernetes/blob/master/pkg/httplog/log.go#L185) on the `http.ResponseWriter`. It is perfectly valid to only call `Write` on a `http.ResponseWriter` as [healthz](https://github.com/kubernetes/kubernetes/blob/master/pkg%2Fhealthz%2Fhealthz.go#L94) does. In this case, the status is defaulted to 200. From the [doc](https://golang.org/pkg/net/http/#ResponseWriter)

```go
        // Write writes the data to the connection as part of an HTTP reply.
        // If WriteHeader has not yet been called, Write calls WriteHeader(http.StatusOK)
        // before writing the data.  If the Header does not contain a
        // Content-Type line, Write adds a Content-Type set to the result of passing
        // the initial 512 bytes of written data to DetectContentType.
        Write([]byte) (int, error)
```

So when you just write, the httplog package doesn't see the status and assumes it's 0. I'm going to work on reproducing, confirming, then fixing this.

**Comment by krousey** [comment]
I confirmed with curl that this is just a logging error at least for healthz. Status code actually returns was 200. This is also pretty obvious since someone writing a 0 status code would result in a stacktrace in the log.

**Comment by krousey** [comment]
Watches are a different issue than healthz. I think watches are hijacked, and that kinda disables all status recording ability by this package. Do we care to fix that? @lavalamp

**Comment by lavalamp** [comment]
websockets hijack-- I thought watches did ordinary HTTP chunked encoding?

**Comment by krousey** [comment]
Probably, but the way it's currently implemented, hijacking completely bypasses this middle-ware logging layer we have.

**Comment by krousey** [comment]
Maybe we detect hijacking and log that instead of false data? e.g.

```
I1102 20:11:39.119484 5 handlers.go:131] GET /api/v1/watch/persistentvolumes?resourceVersion=1687: (9.998155747s) 0 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51471]
```

would become

```
I1102 20:11:39.119484 5 handlers.go:131] GET /api/v1/watch/persistentvolumes?resourceVersion=1687: (9.998155747s) hijacked [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51471]
```

**Comment by lavalamp** [comment]
works for me!

**Comment by krousey** [comment]
Ok out for review in #16756
