### ISSUE TITLE
e2e: kubernetes-e2e-gce-autoscaling broken 10-20% of the time

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#16685]
kubernetes-e2e-gce-autoscaling is broken 10-20% of the time.  It's in the set of builds that blocks submit queue, so flagging as P0 as there's either numerous product or test bugs here.

"ERROR: (gcloud.compute.instance-groups.managed.set-autoscaling) Some requests did not succeed:
- Internal Error"
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1580/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1534/

"Nov  1 23:30:14.056: timeout waiting 10m0s for pods size to be 3"
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1575/

"Nov  1 17:06:17.736: Number of replicas has changed: expected 3, got 4"
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1572/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1569/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1545/

**Comment by fgrzadkowski** [comment]
Reassigning to @piosz who wrote those tests (or at least understands them :) )

**Comment by piosz** [comment]
Each single test in the suite has stability 100% so closing the issue.
