### ISSUE TITLE
Add support for minions to import and run docker images from tarball

### ISSUE THREAD

**Issue by sflxn** [kubernetes/kubernetes#1668]
The docker private registry is still not fully flushed out and many organizations do not want to upload their images to the global docker hub.  For these scenarios, finding a solution to push down a tarball file and letting the minions import it into their local repository and running it is a more optimal choice.  Can we add this support?

**Comment by roberthbailey** [comment]
Given that there are a number of ways to do this (your own cluster startup scripts, run a daemonset to side load your custom images, create VM images with images pre-loaded, run a cluster-local docker registry), and the fact that there have been no substantial updates in over two years, I'm going to close this as obsolete.

**Comment by metrue** [comment]
I'd like to share my the way (https://github.com/metrue/fx/issues/315) I'm doing in [fx](https://github.com/metrue/fx)
