### ISSUE TITLE
AWS LoadBalancer naming/tagging should reflect the service it is defined in

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/kubernetes#16709]
When a Server of type LoadBalancer is defined on AWS, a new ELB with an incomprehensible name and no tags is created.  It should be trivial to map from an ELB back to the owning service (perhaps by namespace & service name/version?).

**Comment by justinsb** [comment]
The name is "a" followed by the UUID of the service.  We need the "a" prefix as I recall because the name can't start with a number.

I agree that we should tag the ELB with the service information - that is a great suggestion.

**Comment by justinsb** [comment]
ELBs are now tagged with the k8s cluster & service name:

```
> aws elb describe-tags --load-balancer-names a320587ffd19711e5a37606cf4a74574
{
    "TagDescriptions": [
        {
            "Tags": [
                {
                    "Value": "default/guestbook",
                    "Key": "kubernetes.io/service-name"
                },
                {
                    "Value": "kubernetes-e2e-aws",
                    "Key": "KubernetesCluster"
                }
            ],
            "LoadBalancerName": "a320587ffd19711e5a37606cf4a74574"
        }
    ]
}
```
