### ISSUE TITLE
Run master node on ubuntu trusty on GCE

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#16702]
We can run worker nodes on ubuntun trusty on GCE, but not master node today. 

cc/ @andyzheng0831

**Comment by andyzheng0831** [comment]
I am working on this part. Please free feel to assign it to me.

**Comment by andyzheng0831** [comment]
Status update: two PRs https://github.com/kubernetes/kubernetes/pull/16960 and https://github.com/kubernetes/kubernetes/pull/18115 have been merged. More PRs will be out for review

**Comment by andyzheng0831** [comment]
Status update: RP #18485 was merged recently. More changes are under preparation.

**Comment by bgrant0607** [comment]
@andyzheng0831 Are you planning more work for 1.2?

**Comment by andyzheng0831** [comment]
Yes, I am working on this. When it can pass e2e test I will send out for review. What is the code freeze date for 1.2 release?

**Comment by dchen1107** [comment]
Next Friday.

**Comment by andyzheng0831** [comment]
As PR #20463 gets merged, the functionality-wise work is done. But there are still a couple of TODO left to make the whole work better.

**Comment by dchen1107** [comment]
I am closing this one since we finished the work except some refactory and cleanup.
