### ISSUE TITLE
Add -N,--names-only flag to kubectl get

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#16700]
Many admin operations are made easier by fetching a list of the names of things, e.g. into a shell variable.  See below for an example.  Rather than hacking up a template, asking for just the names should be a normal flag.
<pre>% nodes=$(kubectl get nodes -lfoo=bar -otemplate --template='{{range .items}}{{.metadata.name}} {{end}}')
% for node in $nodes; do
for> echo $node
for> done

# Sanity check before beginning work.
% echo $nodes | wc -w
4

% for node in $nodes; do 
for> kubectl drain --force $node
for> maintenance_script $node
for> kubectl undrain $node
for> sleep 900
for> done
</pre>

**Comment by mikedanese** [comment]
You could use jsonpath to make it a little shorter but still not great
```
k get no -o jsonpath="{.items[*].metadata.name}" | xargs -d ' ' -I {} kubectl drain {}
```

**Comment by hurf** [comment]
Try `kubectl get no -o name`

**Comment by thockin** [comment]
you want `-o name`
