### ISSUE TITLE
More flexible way of setting external address

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#16706]
Currently one can set external address of the master either via a specific IP or rely on very opinionated _default interface_ selection mechanism (`util.ChooseHostInterface()`). It would be very handy to override this via exact interface name as well as DNS.

There are currently two flags, `--advertise-address` and `--external-hostname`. It is a little surprising that setting `--external-hostname` still doesn't affect what the external address will be, however may be all that's needed is `--external-interface`...

I am running apiserver in a container on Weave and it's Docker's `eth0` that `util.ChooseHostInterface()` currenly favours, as that's what has the default route, but that's not my cross-host network. Weave adds `ethwe` interface and I'd like to use whatever IP that gets. Right now I have to add a wrapper which gets IP of `ethwe` and passes it to `--advertise-address`,  which is in fact just a call to `hostname -i` (see weaveworks/weave#68). Perhaps, a simple mechanism, like `hostname -i`, is what would work more like other programs out there?

**Comment by thockin** [comment]
We went back-and-forth on `hostname -i` - I forget the exact reason we
didn't try that first.  I'm happy to revisit if we think we have a better
heuristic.  Or we could (sigh) add more flags.

**Comment by errordeveloper** [comment]
I see. Well, I don't think `hostname -i` is ideal either, the whole notion of "default interface" is relative anyway. I think it's best to provide full control in situation where the address itself is not known ahead of time, so a flag setting the specific interface would be the way of providing that level of control.

**Comment by lavalamp** [comment]
Happy to look at a PR for this.

**Comment by resouer** [comment]
@lavalamp  sounds interesting #dibs

**Comment by lavalamp** [comment]
@resouer I can't promise speedy reviews, but you are welcome to take a stab at this.

@errordeveloper is there no way you can run a script to discover the correct address and then pass it in? I'm just trying to think of ways to avoid adding more flags.

**Comment by resouer** [comment]
@lavalamp I am also hesitate to add a more flags. So watch this to see if any work around ...

**Comment by errordeveloper** [comment]
@lavalamp I am using a script already:
```
CMD weave_ip=$(hostname -i) ; \
    /hyperkube apiserver \
      --insecure-bind-address=$weave_ip \
      --advertise-address=$weave_ip \
      --external-hostname=kube-apiserver.weave.local \
      --port=8080 \
      --etcd-servers=$ETCD_CLUSTER \
      --service-cluster-ip-range=10.16.0.0/12 \
      --cloud-provider=$CLOUD_PROVIDER \
      --logtostderr=true
```

**Comment by errordeveloper** [comment]
However, I just thought it'd be much nicer to have one of the these two:

a) Allow passing DNS name instead of IP address:
```
      --insecure-bind-address=kube-apiserver.weave.local \
      --advertise-address=kube-apiserver.weave.local \
      --external-hostname=kube-apiserver.weave.local \
      --port=8080 \
```

b) Allow passing interface name instead of exact IP address:
```
      --insecure-bind-address=eth1 \
      --advertise-address=eth1 \
      --external-hostname=kube-apiserver.weave.local \
      --port=8080 \
```

Although, in both cases I'm not sure why I would have to pass all these flags with the same value an a shortcut would be even much nicer!

**Comment by errordeveloper** [comment]
Of course, I can stick with what I have. I might make a pull-request to add a helper script in the upstream container image, if people think it's appropriate.

**Comment by resouer** [comment]
Personally, I prefer your work around to adding a new flag :)

**Comment by lavalamp** [comment]
Yeah, I prefer your work-around to more flags or more functionality for the existing flags.

**Comment by errordeveloper** [comment]
Closing, as a high-level problem like this should probably be solved in `kubeadm`.
