### ISSUE TITLE
I cannot create wordpress and mysql using this guide 

### ISSUE THREAD

**Issue by kk580kk** [kubernetes/kubernetes#16715]
I cannot create wordpress and mysql using this guide http://kubernetes.io/v1.0/examples/mysql-wordpress-pd/README.html

the logs says;
MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

then I try to edit the wordpress.yaml , and add this WORDPRESS_DB_HOST and my mysql ip 10.254.43.97.
I think this maybe bug or something I have a mistake.

**Comment by bgrant0607** [comment]
cc @jeffmendoza @amygdala

**Comment by jeffmendoza** [comment]
Is the mysql service running? Try `kubectl get services` and check for mysql. Where are you running kubernetes? Do you have DNS running?

**Comment by kk580kk** [comment]
@jeffmendoza I don't have a DNS server running by myself. And I don't know how can a wordpress and a mysql connect each other without a explicit "--link".
I thought my mysql status is ok, and I edited "wordpress-pod.yaml" and add "WORDPRESS_DB_HOST = 10.254.43.97 ", can fix this problem.

Is there a implicit "--link" by the name?

**Comment by amygdala** [comment]
@kk580kk , I'm not sure if this is the only issue you are hitting, but it turns out that you now need to use the docker `mysql:5.6` image for this example, as described here:   
https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-wordpress-pd  
See if that fixes things.

**Comment by jeffmendoza** [comment]
You don't need to run your own DNS, but depending on the environment you are running kubernetes in, or what scripts you used to start it, you may or may not have the kube DNS feature. Where are you running kubernetes?

Docker's "--link" is not used in kubernetes. Pods find each other through kubernetes Services, and Services are accessed through kube DNS or environment variables.

**Comment by kk580kk** [comment]
@jeffmendoza perhaps I don't configure right the Kube DNS feature, I am trying it.
For me, I am running kubernetes on redhat (2 servers )and centos (another 4 servers). I haven't known anything about Kube DNS before. Thank you for helping.

@amygdala I haven't try ```mysql:5.6```, I'll try it later. For now I am a litter confuse about how a Kube clients find each other. Thank you for helping.

**Comment by bgrant0607** [comment]
@kk580kk 

Please take a look at Kubernetes documentation regarding services and DNS:
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/connecting-applications.md
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns

If you have additional questions, please try stackoverflow.com.
