### ISSUE TITLE
On systemd, we should restart kubelet indefinitely

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#16730]
I saw an issue where the kubelet was crashing on boot; eventually systemd marked the service as down and (appeared to) stop restarting it.

We should probably restart it indefinitely as the node is useless without a kubelet.

**Comment by dchen1107** [comment]
@justinsb Shouldn't supervisord / monitd detects the issue and restart kubelet? BTW, https://github.com/kubernetes/kubernetes/pull/16736 was just merged, which enables supervisord, and change the interval of daemons healthchecking interval from 2 mins (default interval of monitd) to 10 seconds. Is this good enough?

**Comment by dchen1107** [comment]
Just realized that you were referring to systemd node here.

**Comment by justinsb** [comment]
We now do this in both kube-up:
https://github.com/kubernetes/kubernetes/blob/869af8f5a162b5dfee6a6f6817499f6dbed8ebd8/cluster/saltbase/salt/kubelet/kubelet.service#L8

And in kops: https://github.com/kubernetes/kops/blob/36df0753d9fb33975a8fe50e61dd27029183e3fc/upup/models/nodeup/kubelet/services/kubelet.service#L8

Closing
