### ISSUE TITLE
HPA type should accept a resource

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#16734]
The HPA type currently has a `kind` field.  While sometime unambiguous, the HPA contract is actually with a `group, resource` tuple.  You can see the expression of this in the Scaler client, where they map the `kind` to a `resource`.  Unfortunately, that construct requires that the kube process be aware of and have registered the `kind` and associated a `resource`.  In the general case, that won't happen.

`kind` should still be an option, but a `resource` (mutually exclusive to kind) should be allowed.

**Comment by deads2k** [comment]
@kubernetes/goog-control-plane @kubernetes/kube-api

**Comment by ncdc** [comment]
cc @piosz

**Comment by mwielgus** [comment]
@deads2k 
So you want something like:
```go
// SubresourceReference contains enough information to let you inspect or modify the referred subresource.
type SubresourceReference struct {
	// Kind of the referent; More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds"
	Kind string `json:"kind,omitempty"`
	// Explicit resource name, used only if kind is not provided.
	Resource string `json:"resource,omitempty"`
	// Name of the referent; More info: http://releases.k8s.io/HEAD/docs/user-guide/identifiers.md#names
	Name string `json:"name,omitempty"`
	// API version of the referent
	APIVersion string `json:"apiVersion,omitempty"`
	// Subresource name of the referent
	Subresource string `json:"subresource,omitempty"`
}
```
Right?

**Comment by deads2k** [comment]
> Right?

Yes, and `Resource` and `Kind` should be mutually exclusive.

**Comment by jszczepkowski** [comment]
@bgrant0607 Can you comment on this proposal?

**Comment by jszczepkowski** [comment]
CC @jszczepkowski

**Comment by bgrant0607** [comment]
cc @lavalamp

**Comment by bgrant0607** [comment]
Why?

Resource or resource type?

What form would resource take? A path? 

Would it also be mutually exclusive with subresource? 

When and how would it differ from Kind?

For the most part, we've used ObjectReference or subsets of it to refer to other resources rather than URL paths so that parts of the reference can be set by default from the context of the reference. And ObjectReference intentionally looks like ObjectMeta. It may not be 100% correct, but the subtle distinction between Kind and Resource would probably be lost on most users.

**Comment by deads2k** [comment]
The fact that there is a distinction, suggests to me that we should make our data correct.  If most users only use Kind, that's fine, but I think we should have the expressive power to handle the generic case properly.

Since resources have associated subresources a Resource and Subresource would not be mutually exclusive.  Resource would have to follow the same rules we have for resources today (I think its a non-pathy string).

**Comment by lavalamp** [comment]
There is no intentional difference between Kind and Resource. If I understand the distinction @deads2k is making, though, I'd say that Kind has absolutely no business being in an api type.

You must take either:
* Group and Resource - if you are version agnostic and will do discovery to figure out possible versions.
* Group, Version, and Resource otherwise.

**Comment by lavalamp** [comment]
(I consider Kind and Resource to be synonyms, ftr)

**Comment by thockin** [comment]
I use Object and Resource interchangeably.  Kind is the "class" of
Object/Resource.

**Comment by deads2k** [comment]
> You must take either:
> 
> Group and Resource - if you are version agnostic and will do discovery to figure out possible versions.
> Group, Version, and Resource otherwise.

I like that.

**Comment by erictune** [comment]
Agree with Tim.  Kind is the type, and Resource is a specific resource.

**Comment by lavalamp** [comment]
My headcanon is that the "job resource" refers to e.g.
"/apis/extensions/v1/namespaces/default/jobcontroller/" and everything
under it, which makes it synonymous with "kind". What do you guys call the
above path?

**Comment by deads2k** [comment]
> My headcanon is that the "job resource" refers to e.g.
> "/apis/extensions/v1/namespaces/default/jobcontroller/" and everything
> under it, which makes it synonymous with "kind". What do you guys call the
> above path?

The URL is where you hit the jobcontrollers resource, but the object you pass to it is a JobController.  The distinction becomes more important as multiple resources and subresources accept the same Kind.   

As an example in the kube API, consider `bindings`, `pods/binding`, and `Binding`.  Two separate resources, both operating on the same Kind.  `status` subresources also deal in the same Kind as the parent resource.  With introduction of a generic `scale` subresource, we want to use the same Kind in multiple locations.

I *think* someone in the `extensions` wanted it for `ReplicationControllers`, though its harder to see exactly what they were trying to do there.  It was probably an inter-group dependency problem.

**Comment by bgrant0607** [comment]
We have agreed on a different approach in #18528.
