### ISSUE TITLE
HPA type needs APIGroup

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#16732]
A resource is no longer an unambiguous concept.  It needs an `apiGroup` to qualify the name and make it unambiguous.  The HPA type doesn't contain enough information to uniquely identify what it wants to scale.

**Comment by deads2k** [comment]
@kubernetes/goog-control-plane @kubernetes/kube-api

**Comment by ncdc** [comment]
cc @piosz

**Comment by mwielgus** [comment]
@deads2k 
So the new SubresourceReference would be:
```go
// SubresourceReference contains enough information to let you inspect or modify the referred subresource.
type SubresourceReference struct {
    // Kind of the referent; More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds"
    Kind string `json:"kind,omitempty"`
    // Explicit resource name, used only if kind is not provided. (Requested by #16734)
    Resource string `json:"resource,omitempty"`
    // Name of the referent; More info: http://releases.k8s.io/HEAD/docs/user-guide/identifiers.md#names
    Name string `json:"name,omitempty"`
    // API version of the referent
    APIVersion string `json:"apiVersion,omitempty"`
    // API group of the referent, default "extensions".
    APIGroup string `json:"apiGroup,omitempty"`
    // Subresource name of the referent
    Subresource string `json:"subresource,omitempty"`
}
```

And BTW, Is there already an elegant way to build RESTClient for a particular apiGroup/apiVersion?.

**Comment by deads2k** [comment]
> So the new SubresourceReference would be:

I would consider dropping `Subresource` and forcing it to always be scale.  Similar in concept to forcing names for interface evaluation in Go.  Also, `Name` is required, so `omitempty` shouldn't apply to that field.


> And BTW, Is there already an elegant way to build RESTClient for a particular apiGroup/apiVersion?.

Not that I know of today.  @lavalamp is looking at refactoring `client` so it may get easier, but I wouldn't want to wait for it.

**Comment by mwielgus** [comment]
I would rather keep the subresource so that some other api object may use this reference in the future.

@bgrant0607  Are you OK with this change?

cc: @jszczepkowski @fgrzadkowski

**Comment by deads2k** [comment]
> I would rather keep the subresource so that some other api object may use this reference in the future.

This type isn't a generic something.  Because of the way the codec's generated conversions are written, its currently impossible to reasonably express embedding a type from one APIGroup into another APIGroup.  This is specifically for your use-case.  If you don't need it, I don't think you should add it until something actually needs it.

This type is essentially a clone of `v1.ObjectReference`, you just can't name it that because of other bugs in the way the internal group,version,kinds are registered in the Scheme.

**Comment by lavalamp** [comment]
Group is packed into apiVersion in TypeMeta. I would prefer to do the same here for consistency.

**Comment by deads2k** [comment]
> Group is packed into apiVersion in TypeMeta. I would prefer to do the same here for consistency.

I'd prefer not to do that for this struct.  I think it was a mistake to combine two distinct fields in the first place and things would get really strange here.  Most of the time, I don't care about version, so I'll be setting an `apiVersion` field equal to just the `apiGroup`.

**Comment by lavalamp** [comment]
Do you still feel that way once
https://github.com/kubernetes/kubernetes/pull/16834 is available for the
type?

I think it's even more confusing to have "apiVersion" in type meta be both
group and version, but apiVersion in HPA be only version.

**Comment by deads2k** [comment]
> Do you still feel that way once
> #16834 is available for the
> type?
> 
> I think it's even more confusing to have "apiVersion" in type meta be both
> group and version, but apiVersion in HPA be only version.

It's problematic in this case. In the `TypeMeta` case, it doesn't make any sense to have `apiVersion` be just a `group` because that is insufficient information to locate the correct codec.

In the case of this reference object, it almost always makes sense to have just `group` so that the `version` can be negotiated to whatever is available.

**Comment by lavalamp** [comment]
Ah, so you'd like to remove apiVersion entirely and have only apiGroup? I'm
totally fine with that.

**Comment by deads2k** [comment]
> Ah, so you'd like to remove apiVersion entirely and have only apiGroup? I'm
> totally fine with that.

I think just `apiGroup` is a reasonable place to start.

**Comment by bgrant0607** [comment]
apiVersion cannot be removed.

**Comment by bgrant0607** [comment]
In particular, kinds can be renamed across api versions (e.g., minion to node), so the version is necessary.

**Comment by lavalamp** [comment]
Argh, good point, Brian. So I'm back to recommending a field called
"apiVersion" of type GroupVersion.

**Comment by bgrant0607** [comment]
SubresourceReference already contains apiVersion, which includes the group.

**Comment by deads2k** [comment]
> SubresourceReference already contains apiVersion, which includes the group.

@bgrant0607 This means that sometimes when a user sees `apiVersion` must be an unambiguous group,version tuple.  Other times, when a user sees `apiVersion` its a bare version for backwards compatibility.  And now, `apiVersion` is also sometimes a bare group.

I think its pretty unreasonable to have a user try to understand three different meanings for the same field.

**Comment by bgrant0607** [comment]
@deads2k apiVersion should always be an unambiguous group/version tuple, except for the legacy monolithic API v1 group. Anything else is a bug.

**Comment by deads2k** [comment]
> @deads2k apiVersion should always be an unambiguous group/version tuple, except for the legacy monolithic API v1 group. Anything else is a bug.

@bgrant0607 That's why I opened this.  Its very uncommon for someone to care which version of a resource is used, but needing to specify a group is very common.  In fact, the very first time this was used in kube, a `group` was needed, but it wasn't specified.  Instead it was hardcoded to `extensions`.  See https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/scale.go#L36
