### ISSUE TITLE
Getting "Unknown output type: yaml"

### ISSUE THREAD

**Issue by mahehss** [kubernetes/kubernetes#16747]
I tried setting up the kubernetes cluster by following the below link. I was able to get the bucket created but after that it started throwing ""Unknown output type: yaml" error.

http://kubernetes.io/v1.0/docs/getting-started-guides/aws.html

Below are the stack when I run kube-up.sh

Starting cluster using provider: aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: vivid
Uploading to Amazon S3
+++ Staging server tars to S3 Storage: nb-dev-kube1/devel

Unknown output type: yaml

Thanks,
Mahesh

**Comment by justinsb** [comment]
I believe if you set `export AWS_DEFAULT_OUTPUT=yaml` (or indeed any value that isn't recognized) this will happen.

I guess we should probably either unset this env var, or always pass an --output argument.  The latter is probably safer.

**Comment by justinsb** [comment]
I have a fix for this, but it has some horrendous merge conflicts with some other PRs of mine that are in flight.  I suggest `unset AWS_DEFAULT_OUTPUT` for now, and it will hopefully be fixed soon!

**Comment by mahehss** [comment]
Hi justinsb,

I just checked. AWS_DEFAULT_OUTPUT is not set. 

Thanks,
Mahesh

**Comment by mahehss** [comment]
Thanks a lot justin. I was able to solve the problem by setting the AWS_DEFAULT_OUTPUT key to "table". Thanks again.
