### ISSUE TITLE
Need CR to get first prompt after kubectl run

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#16742]
When you run an image with kubectl run, it prints a bunch of `Waiting lines like this:

```
./kubectl run -i --tty temp2 --image busybox
Waiting for pod default/temp2-7ob5w to be running, status is Pending, pod ready: false
.. lots more lines ...
Waiting for pod default/temp2-7ob5w to be running, status is Pending, pod ready: false
```

Once it is done waiting, it doesn't print anything else, and it does not show the command prompt.  You have to hit enter to get a command prompt.  Users may not realize this.

Suggest at the end of the `Waiting...` loop, we print a line like `Hit enter for prompt` or else figure out what is wrong with the terminal or shell settings that it isn't happening immediately.

**Comment by thockin** [comment]
+1

**Comment by feihujiang** [comment]
I tried to fix this.

**Comment by erictune** [comment]
This worked well, thanks @feihujiang

**Comment by smarterclayton** [comment]
Why do users have to hit enter to get a prompt?  Is this some gap between bash, attach and execution?  Why don't we have to hit enter for exec?

**Comment by smarterclayton** [comment]
Why can't we send enter to the TTY to trigger this?

**Comment by smarterclayton** [comment]
@ncdc have we seen this that we don't get the original prompt?  Is this a race in attach where the buffer is lost or not detected?

**Comment by ncdc** [comment]
It's because we don't monitor terminal size and resize the tty. Long
standing issue, multiple reports upstream and here.

**Comment by ncdc** [comment]
Reports here... Thought this was an Origin issue :-)

But i did fix a similar issue in docker recently.

It is a pretty easy fix for Kube. Just need time...

**Comment by smarterclayton** [comment]
Can we cross link?

**Comment by smarterclayton** [comment]
Ok, I'm going to open a refactor to clean up the safe TTY handling (because deeply nested functions that eat signals and exit immediately are bad for business).
