### ISSUE TITLE
Kubernetes build has grown bloated.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#16753]
The default 'make' target for a build literally grinds my machine to a crawl.  This is almost antitechtical to one of the central themes of golang, that go builds are lightweight and fast.  

My distcc builds of large c++ projects is faster than k8s. 

For example, there are a bunch of targets that I think should be part of only a 'release' build, which is more of an exception then the norm.

**Comment by paralin** [comment]
When building a release for ./cluster/kube-push.sh it builds all of the cross-compilation targets even though we're only targeting the default on the cluster. Seems a bit inefficient? Is there a faster way to do this / speed it up

**Comment by timothysc** [comment]
yeah it's mildly comical that 8-core 8-GB of RAM machine can be bricked by a k8s build now for a bunch of things I don't really care about.  

Couldn't we just have a make minimal and set that as the default?  

/cc @eparis

**Comment by spzala** [comment]
@timothysc Hello, since it's more than a year of this issue was last discussed, can you please check if it's still an issue? If not, can we please close it? Thanks!

**Comment by timothysc** [comment]
It's worse...

**Comment by justaugustus** [comment]
I feel that the ship has maybe left the port on this one, given when this was opened in 2015.
@timothysc -- If there are some actionable, chunkable bits here you'd like to see, reopen and let us know!

/close

**Comment by paralin** [comment]
FWIW I have a project which imports most of Kubernetes directly and uses only the Go compiler (none of the kubernetes build tooling). It builds quite fast and is very manageable. The long build times and bloat is entirely from the convoluted build scripts.
