### ISSUE TITLE
Dependency tree validation

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16768]
A number of things we need to do in the near-ish future will involve making sure that discrete chunks of the codebase are independently importable.

Basically, we want to tightly control the dependencies of the client, and of apiserver infrastructure, to start out with. As we clean up the dependencies, we want to keep them cleaned up. This means we need something to test the import paths, to ensure that parts of the codebase that _should_ be logically distinct _are_ logically distinct.

Even if we manage to split parts of our codebase off, this test will be useful in the interim while we prepare for the move.

We can potentially use go2idl for part of this, but how to represent allowed/disallowed packages? Whitelist or blacklist?

@thockin @smarterclayton

**Comment by smarterclayton** [comment]
Whitelist!  I am 100% in agreement with this.

**Comment by lavalamp** [comment]
I can imagine a solution where you keep a whitelist in package directories, with the whitelist applying recursively to every child directory that doesn't itself have a whitelist.

I can also imagine a single file somewhere with the allowed dependencies.

I think I'm in favor of the former? Is there any other information we would like to pack into this file? (owners?) Or should we just do a separate file for everything--that sounds easiest.

**Comment by smarterclayton** [comment]
Whatever's easiest probably for now.

**Comment by smarterclayton** [comment]
We did this.
