### ISSUE TITLE
Design/Implement "dynamic" client from #15730

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16764]
From #15730, "The dynamic client lets users consume apis which are not compiled into their binary..."

Rough TODO list is to:
- Get consensus on an interface - examine kubectl's Builder.
- Conscript runtime.Unstructured (or similar type).
- Type needs to allow easy/standardized metadata introspection.
- Make a codec supporting the type.
- Implement the client.
- Wire in to potential users; Namespace controller would be an ideal consumer.
- Replace kubectl's Builder?

**Comment by paralin** [comment]
Maybe upgrade to Swagger v2?

I built a dynamic client for C# using code generation:

https://github.com/paralin/kubenet

Of course you need code generation here since you want type safety - however, under swagger v2, you can actually re-generate all that code with a single command targeted at a live endpoint. With v1.2 this doesn't work.

**Comment by paralin** [comment]
That said here's a working v2.0 swagger API declaration:

https://github.com/paralin/KubeNET/blob/master/Resources/API/kubernetes.swagger

pretty easy to generate, via:

https://github.com/paralin/KubeNET/tree/master/Resources/Scripts/gen-swagger2

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/issues/13414 tracks generating 2.0 swagger spec.

Its cool to see 2.0 spec but since that is generated by converting our 1.2 spec, we still cant use the new features introduced in 2.0, right?

**Comment by paralin** [comment]
@nikhiljindal Probably not, either way, it's a working 2.0 spec. Would be a good starting point for someone to go through and manually upgrade things.

**Comment by lavalamp** [comment]
@paralin generating clients from swagger is good, but a separate issue (see the "typed" clients in the proposal I linked). This issue is concerned with making a single client that can talk to *any* kubernetes resource, existing or future, and at least do metadata operations.

For example, the namespace controller would need to be recompiled for every new resource if it were using a client produced from swagger.

**Comment by paralin** [comment]
@lavalamp Sure - I just generated for type safety. It'd be great to have a dynamic client for human interaction.

**Comment by lavalamp** [comment]
@paralin yeah, we absolutely want to do that, too...

**Comment by lavalamp** [comment]
@krousey Can you give an update?

**Comment by derekwaynecarr** [comment]
Is there a WIP pr that I can track?

**Comment by krousey** [comment]
@lavalamp Sure. I got a first swing at it on #20351. I was pulled off on to a couple of flakes and am now getting back to it. Locally, I've updated the Unstructured objects and codecs to address the comments in the WIP PR. I'm in the middle of switching the actual client over to the new types now. I'm going to try to clean it up and get it to a point where I can update the PR today or tomorrow and get more feedback.

@derekwaynecarr I think I mentioned you on #20351

**Comment by lavalamp** [comment]
@krousey Do you think we'll do more on this for 1.2 or should we kick it to the next release?

**Comment by krousey** [comment]
I think we got a lot of this. There are some remaining items that may have to wait. Specifically:

- [x] Get consensus on an interface - examine kubectl's Builder.
- [x] Conscript runtime.Unstructured (or similar type).
- [x] Make a codec supporting the type.
- [x] Implement the client.

Are done.

- [ ] Type needs to allow easy/standardized metadata introspection.

Version, Kind, and Name are easily accessible. Other data is accessible, but not easily. (lots of bare interface type assertions). This could be improved.

- [ ] Wire in to potential users; Namespace controller would be an ideal consumer.

No current users. Namespace controller is in progress. I'm also trying to put together a testing package for this that makes it easy to test.

- [ ] Replace kubectl's Builder?

Not done. Probably should be kicked.

**Comment by lavalamp** [comment]
OK, I think we made good progress on this. Thanks.

**Comment by smarterclayton** [comment]
Implemented.
