### ISSUE TITLE
Update high availability docs / example configs to use supervisord instead of monit

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#16762]
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/high-availability.md
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/high-availability/monit-kubelet
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/high-availability/monit-docker

/cc @brendandburns

**Comment by spzala** [comment]
@roberthbailey Hello, I believe it's safe to close this issue. It's over a year old and also docs are moved to it's own k8s.github.io repo.Thanks!

**Comment by spzala** [comment]
(I wasn't able to close it and it was expected, but I tried as part of contrib X sig discussion I had.)

**Comment by spzala** [comment]
@roberthbailey Thanks!!
