### ISSUE TITLE
Remove docker references in pod_worker_test.go

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#16772]
We should not be testing docker-specific logic outside of docker package. pod_worker_test.go still imports go-dockerclient directly and uses a fakeDockerClient. They should be replaced with the generic FakeContainerRuntime, etc.

**Comment by Random-Liu** [comment]
Will do! :)

**Comment by Random-Liu** [comment]
Done! It takes me some time to read through the related code, if there is anything wrong, tell me please, :)

**Comment by Random-Liu** [comment]
Close this issue, because it has been done in #16825 :)
