### ISSUE TITLE
Slim down fluentd-es-image.

### ISSUE THREAD

**Issue by eliaslevy** [kubernetes/kubernetes#16775]
The fluentd-es-image add-on is massive, weighing in at 534 MB per Docker Hub.  There is no need for that heft.  May I suggest something like https://github.com/eliaslevy/docker-k8s-es-fluentd, which Docker Hub shows at 10 MB.

It uses Alpine Linux and is preconfigured similarly to the existing image.  It does not use the td-age distribution, as Alpine does not support RPM or DEB packages, but it is configured to use jemalloc.

**Comment by eliaslevy** [comment]
@a-robinson thoughts?

**Comment by a-robinson** [comment]
I agree that we should shrink down the base image that we use for this (I actually have a [TODO in the Dockerfile](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Dockerfile#L4) to do so...). I don't have many cycles available to help right now, but I'd be supportive of switching over our Dockerfile to something on alpine like what you have there.

What's your opinion, @jimmidyson?

**Comment by jimmidyson** [comment]
While I love Alpine, one problem is that Alpine doesn't implement DNS search paths at all ([discussion thread](http://www.openwall.com/lists/musl/2015/10/22/6)) so would have to use FQDNs for hostnames which is a bit of annoying, especially when we probably want to move to using the daemon controller for fluentd pod scheduling to every node & using the short name to address ES which will probably be in the same namespace. We should be able to add glibc, which will make the image slightly bigger of course. How does that sound @eliaslevy?

**Comment by eliaslevy** [comment]
Yes, the lack of DNS resolve.conf domain or search support in must libc is
quite annoying and seems to have been ruled out upstream.  You can
certainly install glibc, I've done so to build a small Oracle Java image
based on Alpine, but I am guessing that will require rebuilding Ruby,
rather than using the Alpine package, as well as making sure that the
binary components of fluentd link to glibc during the image build.

**Comment by eliaslevy** [comment]
It appears that @thockin has [convinced](https://www.marc.info/?l=musl&m=144572949505263&w=4) the musl folks to add `resolve.cof` search support.  So it may be best to wait until musl incorporates the support and Alpine is updated, rather than trying to hack in glibc into an image.

**Comment by therc** [comment]
http://www.openwall.com/lists/musl/2016/02/16/1
http://git.alpinelinux.org/cgit/aports/commit/main/musl?id=8daae2d91da7ea2065b57e71950970efbeba80a2

It just needs an official release now.

**Comment by therc** [comment]
Actually, alpine:edge already has the new musl.

**Comment by therc** [comment]
http://www.alpinelinux.org/posts/Alpine-3.3.2-released.html
I can't tell if it has the new musl or just cherrypicks (sounds like the latter).

**Comment by therc** [comment]
I don't see anything related:
http://git.alpinelinux.org/cgit/aports/commit/main/musl/APKBUILD?h=v3.3.2&id=56101f21b652321e32c4a02139ea042fccf6bebd

**Comment by therc** [comment]
Alpine 3.4  is happening as we speak:
http://git.alpinelinux.org/cgit/aports/patch/?id=00864455a5b1ef971280c32347288d7f6f14e5a1

**Comment by bgrant0607** [comment]
closing in favor of #29782
