### ISSUE TITLE
hack/update-codecgen.sh generating different output than verify-codecgen.sh at HEAD

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#16770]
From https://github.com/kubernetes/kubernetes/pull/16757#issuecomment-153537158 (which includes more details):

The output of the ugorji codecgen is varies depending on whether the dependencies' codecs have been generated. https://github.com/kubernetes/kubernetes/pull/16415 started deleting generating files before regenerating them, but without enforcing a dependency ordering.

My suggested fix is to define a dependency ordering in `hack/update-codecgen.sh` and follow the order when regenerating the files (after first deleting them). `hack/verify-codecgen.sh` will also need to be updated to match the same logic.

cc/ @lavalamp

**Comment by wojtek-t** [comment]
Yes - the problem is that it depends on the order - it produces a different code depending whether the code for depending structures already exists or not.
I agree that generating the code in dependency order will fix the problem and is the desired one.

**Comment by wojtek-t** [comment]
#16788 sent out for review.
