### ISSUE TITLE
How to _not_ create a service account?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#16779]
Is it possible to launch a pod without a service account, or with a null service account?

I've tried creating a serviceAccount and deleting the secret (it is recreated).  I've tried creating a secret without the token line (it is recreated).  Not specifying a serviceAccount means the 'default' serviceAccount is used.

As far as I can tell, every pod created gets full access to the k8s API.  While I know that RBAC are the correct long-term solution here, I think denying a pod all access to the k8s API is a common enough use case that we should be able to support it without telling people to wait for RBAC.

The best I have found is to create the serviceaccount, figure out the randomly named secret, download the secret, modify the token to be 123 (base 64 encoded), and then replace the secret.  But that is very hacky indeed.

**Comment by mikedanese** [comment]
It's not possible to create a pod without a service account, however it is possible to restrict all access to the api to a service account using the ABAC authorizer (AllowAll authorizer is the default). cc @erictune

**Comment by pmorie** [comment]
@mikedanese @justinsb actually, this is possible - you need to remove the `ServiceAccount` admission controller from your cluster.  I don't think there's an easy way to do this selectively, though. @liggitt?

**Comment by liggitt** [comment]
Removing the service account admission controller from the list will keep pods from being automatically given an API token. 

If you remove the service account private key arg when starting the controller manager, no tokens will be created at all.

As you say, enabling authorization is really the right fix. Starting with authorization mode AllowAll is not something a security conscious cluster should do

**Comment by spinus** [comment]
@liggitt , @mikedanese do you guys have any clue how to set ABAC up on GCP with kubernetes 1.1.1?

**Comment by mikedanese** [comment]
GKE does not support ABAC yet. However it is possible to setup ABAC with GCE clusters.

**Comment by spinus** [comment]
wow, that was fast :-) thank you for the answer.
By saying ABAC with GCE clusters do you mean setting up own kubernetes installation, right?
Do you know any way of restricting API access from pods to API server on GKE? The current default policy seems a little bit dangerous, not?

**Comment by erictune** [comment]
I think this is an API bug.  In the pod type, ServiceAccountName should be
type string* not a string.  If the user explicitly set it to the empty
string instead of omitting it, then the admission controller should not do
any service-account-token-mounting logic on the pod.

There is a workaround.  Mount an emptyDir at the default service account
mount path, like this:

$ cat no-sa.yaml
apiVersion: v1
kind: Pod
metadata:
  name: i-have-no-sa
spec:
  serviceAccount: "no-api-access"
  containers:
    - name: c
      image: busybox
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: no-api-access-please
        readOnly: true
  volumes:
  - name: no-api-access-please
    emptyDir: {}

$ ./kubectl create -f no-sa.yaml
pod "i-have-no-sa" created

$ ./kubectl get -f no-sa.yaml -o yaml | grep token

(no results, yay)

**Comment by spinus** [comment]
@erictune thank you for sharing your solution. Looks like working workaround :-)

IMHO service account should by mounted only when explicitly set, not as a default. I'm not sure what's the rule of the thumb in most clusters but I can only guess that most pods don't need this.

**Comment by mikedanese** [comment]
That would be a breaking change.

**Comment by spinus** [comment]
I'm not suggesting to change this immediately or anything like that. Rather, maybe would be worth to discuss this topic in security context and then eventually consider changing that using deprecation policy etc.

**Comment by mikedanese** [comment]
@spinus sounds good, and it very well may be the right approach. Just noting that the change isn't necessarily easy to make.

**Comment by liggitt** [comment]
both image pull secrets and mountable secrets (including the automounted api token secret) are related to service accounts. I think we'd still want to be able to set image pull secrets on the `default` service account and have pods use them, even if they didn't want/need an API token. Is there another way we could prevent automounting of an API token, other than removing the association of a service account with a pod entirely?

cc @deads2k

**Comment by erictune** [comment]
We could add field to serviceAccount called, say `noAutomaticAPICredentials` which tells the service account controller, and any other similar automation, that the user does not want credentials added to the service account.

Then users could create serviceAccount "no-api-access" (or any other name the user choses) in their namespace, with `noAutomaticAPICredentials=true`, then add imagePullSecrets if desired, then create a pod which specifies `.spec.serviceAccount="no-api-access"`.  

This would not be a breaking API change.

**Comment by deads2k** [comment]
I'm still rather partial to the idea of an explicit list of auto-mounted secrets proposed in item 4 here: https://github.com/kubernetes/kubernetes/issues/11070

**Comment by spinus** [comment]
@deads2k so, fingers crossed for RBAC :-) hope it won't allow all service accounts to do anythink by default. Default policy DROP ++ :-)

@erictune: small comment, I'm not sure where but think I've seen this kind op options in kubernetes already, I would vote agains "no" options as they can be misleading. +1 for clear options like "AutomaticAPICredentials=false" rather than "noAutomaticAPICredentials=true" which is kind of "no=yes" or "disableOption=enable" (but it's just personal taste thing I think).

**Comment by erictune** [comment]
@spinus agree that positive flag names are better than negative flag names.  However, it gets complicated because of our backward compatibility rules.   There may also be backward compatibility issues around changing the default to drop.  Will look into it.  For now my first priority is for people to have a clean way to create a pod without api creds.

**Comment by erictune** [comment]
#17445 will fix this issue, in one way.  

Will still look into @liggitt suggestion about allowing imagePullSecrets but no API token, with a different fix.

**Comment by erictune** [comment]
@dead2k 
How do you see the proposed `serviceAccount.AutoMountedSecrets` being used by the Token Controller  in the default case and how would the user specify they do not want an API token?

**Comment by deads2k** [comment]
> @deads2k
> How do you see the proposed serviceAccount.AutoMountedSecrets being used by the Token Controller in the default case and how would the user specify they do not want an API token?

I envision `AutoMountedSecrets` containing the token secret by default.  If the user does not want the token auto-mounted, they would explicitly remove the element.  Behavior for handling a deleted token secret is a little less clear, but I think we could reasonable behavior by waiting to remove an existing token secret ref until we had a replacement.

**Comment by erictune** [comment]
So:

1. create a serviceAccount, 
1. waiting for the serviceAccount controller to notice it,
1. delete the token
1. hope that a controller does not decide to add it back.

Seems racy.  Also makes it inconvenient to create a service account and the pods that use it in a single `kubectl create -f` command.  

How about:
1. create a serviceAccount with `.spec.noApiToken=true`

**Comment by liggitt** [comment]
> Seems racy. Also makes it inconvenient to create a service account and the pods that use it in a single kubectl create -f command. 

Agree, don't want to fight controllers.

> How about:
> 1. create a serviceAccount with .spec.noApiToken=true

Can we target the automount behavior specifically? There are use cases for still creating a token (for use with external systems) or still associating a service account with a pod (for use with image pull secrets), but being able to opt out of API token automount (either for a particular pod, or for a particular service account) is useful.

**Comment by pmorie** [comment]
> Can we target the automount behavior specifically? There are use cases for still creating a token (for use with external systems) or still associating a service account with a pod (for use with image pull secrets), but being able to opt out of API token automount (either for a particular pod, or for a particular service account) is useful.

+1 to this, @liggitt; where do you think that attribute should live?  On the service account?

**Comment by deads2k** [comment]
> +1 to this, @liggitt; where do you think that attribute should live? On the service account?

I would want it in the `PodSpec`, so that I could use a service account for its pull secrets, but not allow the pods to act as the SA.

**Comment by pmorie** [comment]
@deads2k Yeah, that makes more sense.

So, all that said, @justinsb what you would get is the ability for pods to opt-out of token mounting, which is different than limiting access.  However, someone who wanted to limit access could make an admission controller that ensures that this flag is set -- does that give you what you want?

**Comment by erictune** [comment]
I don't want to require putting a special field on the `PodSpec`.  That requires every pod creator to remember to set the field, rather than just the person who sets up the service account.

If we put a `doNotMountApiToken` flag on the service account, that does not need to affect `imagePullSecrets`, right?   

Are you using the api token as an image registry credential in OpenShift?

Also, as long as the api token is not mounted in the chroot of any container of the pod, then I don't think it matters that the kubelet has pulled the secret, right?

**Comment by spinus** [comment]
@erictune to make a pod you have to remember (or just check in the docs) lot of stuff already. Reality is that you always check it with the docs, not only because of field number but also because API is evolving. I don't think this one field change a lot. I'm not against any solution, just saying that probably adding a field doesn't change too much.

I would ask about not doing negative flags again :-)
You can add "mountAPIToken" with default value "true" to have backward compatibility and that probably looks more sane.

**Comment by liggitt** [comment]
Off the top of my head, `automountServiceAccountToken *bool`, defaulting to true, on either the service account or the pod spec seems ok. I do wish we had a clearer idea of how we want to specify automounts in general, to tie this in better

**Comment by roberthbailey** [comment]
@erictune Are you still working on this?

**Comment by erictune** [comment]
yes

**Comment by andrewmichaelsmith** [comment]
@roberthbailey suggested I had my use case here so am doing so.

For my case I am not particularly worried about the security implications of pods accessing the API server. My main concern is the [overhead](http://stackoverflow.com/questions/37272853/many-occurrences-of-unmount-in-kubelet) involved in generating all the mounts. 

Right now I have 1 pod (skydns) that needs access to the API server and 600 that do not. Creating those 599 mounts is unnecessary. 

From my perspective adding the default token off by default and being able to optionally enable it where I need it would be ideal.

**Comment by kfox1111** [comment]
I kind of like the doNotMountApiToken idea at the container level. I'm working on a pod that will allow users to run custom code in it so I don't want them having any access at all to k8s from that container, but the rest of the containers/pods on the system are ok to have access. For now, I'm going to try @erictune's emptyDir mount trick.

**Comment by osixia** [comment]
the workaround seems to not work anymore, someone else can confirm ?

**Comment by erictune** [comment]
Nobody is working on this.

**Comment by erictune** [comment]
But is is important.

**Comment by wernight** [comment]
I don't like magic mounts. We could have a standard mount with new type of Volume.

To avoid it to be a breaking change, may be we could use the `version` and release notes to inform: Upgrading version to X.Y will improve security but some Pods may break, for those simply add ... to their definition.

Is that token actually necessary for most Pods to run? I used the hack of mounting the empty directory as `/var/run/secrets/kubernetes.io/serviceaccount` and it seems that all my services work (except the Nginx Ingress Controller of course).

**Comment by kfox1111** [comment]
+1 to making it default off. I've only got maybe 2 or 3 pods that need service accounts. It is great that service accounts are a thing. One of my big criticisms of OpenStack's current auth implementation is it lacks them. They are critical when needed. But most of the time they aren't needed. So for increased security, they should be able to be enabled only when needed at a container level.

**Comment by mikedanese** [comment]
There are two approaches to nullifying this access:

1. Don't add the namespace default service account to pods.
2. Don't give the namespace default service account authorization to the API.

Is one better than the other?

I'm afraid that we can't do 1 by default until the v2 api and 2 requires that the cluster is using ABAC (or other).

**Comment by deads2k** [comment]
> There are two approaches to nullifying this access:
> 
> Don't add the namespace default service account to pods.
> Don't give the namespace default service account authorization to the API.
> Is one better than the other?

I prefer option 1 because it doesn't rely on the API server having bug free authn/authz layers. A project-editor (someone who can create pods in a namespace) can avoid mounting the API token at all, so that even if their pod gets compromised, the pod doesn't have a valid API token that could be used to execute an attack on the API server and perhaps mutate other resources in the namespace.

**Comment by deads2k** [comment]
I guess I should clarify.  I like being able to not mount an SA token.  I have no issue with still assigning an SA for things like an image pull secret for use by the kubelet.

**Comment by kfox1111** [comment]
I prefer option 1 as well. If we can't default it off in v1, that's ok. we can default it on and make it an option to configure it off. once we get to v2, we can flip it around and make it default off and require you to turn it on.

**Comment by philips** [comment]
Is anyone working on this for v1.5? I like the proposal of having the SA simply not mount by configuration. Would we just add v1.ServiceAccount.Spec.mountPolicy?

**Comment by mikedanese** [comment]
We could also implement better behavior in a new admission controller and deprecate the current.

**Comment by deads2k** [comment]
> Is anyone working on this for v1.5?

This didn't make a priority cut as something we'll be actively working on in 1.5 (https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit#heading=h.ux2u8v8kqtz9 Sept 7, `Call for 1.5 Goals`).  



> I like the proposal of having the SA simply not mount by configuration. Would we just add v1.ServiceAccount.Spec.mountPolicy?

I think this is more per-pod, than per-SA.

**Comment by philips** [comment]
@mikedanese What would better admission controller behavior be to you?

**Comment by kfox1111** [comment]
I can see it going either way. for some pods, I could see you not wanting a token on a non privileged container, and having a side car that has a token to do stuff on its behalf. But most of the time, you probably don't want any container in the pod to have one.

Maybe then a way to set the default mode on the pod, and then be able to override it per container?

**Comment by mikedanese** [comment]
@philips I had not sketched it out :) I just wanted to put it forward as a way of making a change while maintaining backwards compatibility. The current ServiceAccount admission controller adds a service account to all pods. Would a SystemNamespaceServiceAccount that only adds service accounts to pods in NamespaceSystem be useful?

**Comment by deads2k** [comment]
> Would a SystemNamespaceServiceAccount that only adds service accounts to pods in NamespaceSystem be useful?

It makes sense to allow service account tokens to mounted at the discretion of the project-editor (person creating pods and things that stamp out pods).  That person has the rights to see the SA token already, so he already has the power to use it.

Allowing it to be mounted into any pod means that he has the power to create pods that run controller-y things.

**Comment by mikedanese** [comment]
Sure but that's possible today. Just don't enable the ServiceAccount admission controller and call it a day, right? I'm mostly concerned with making sure that the addon configs in cluster/addons still work with a new behavior that doesn't mount the service account into pods by default.

**Comment by liggitt** [comment]
Normal namespace editors don't have control over the cluster wide admission chain. Adjusting the existing admission controller's behavior based on a field on the incoming pod spec would make sense to me.

**Comment by deads2k** [comment]
> Sure but that's possible today. Just don't enable the ServiceAccount admission controller and call it a day, right? I'm mostly concerned with making sure that the addon configs in cluster/addons still work with a new behavior that doesn't mount the service account into pods by default.

The SA admission plugin also adds image pull secrets and limits secret mounting. You can't disable it without losing those abilities.

**Comment by kfox1111** [comment]
Just disabling  the controller seems like too big a hammer.

While default off on pods seems like a good idea, lets leave it default on for now so we dont break things, and switch the default when we have a breaking change. Spec 2.x.

**Comment by erictune** [comment]
My preferred solution is:

- Every Pod has a service account (non-empty string in service account
field).
- Pods without a service account mentioned at creation get the default
service account.  Nothing disables this behavior.  We could move this from
an admission control to a defaulter perhaps.  One use case is a create a
namespace where I can run things with ambient authority without having to
write long pod specs.
- An field on a service account object should control whether or not a
kubernetes API credential is automatically added to that service account.
The default service account has this set to true.  You can flip this flag
and the cred will be removed, and you can make your whole namespace have no
API credentials.
- In the future we might add other types of credentials to service accounts
that are automounted.  One type might be a peer-to-peer identifying
certificate.  Another might be a cloud provider service account.  We might
not want to block these even if we want to block API access.  So no big
hammers.
- Sometimes you will want some containers to have API creds and others not
to.  For example an init container that pokes at the API, the a server
starts and you don't want the cred around anymore.  That should work.  Or a
sidecar.  Someday we should support different service accounts per
container.  For now, we can just have a flag per container to block the
pod's secret automount behavior.
- The Authorization plugin / cluster-admin is responsible for deciding what
permissions a service account users has, including the default for new
service accounts, including namespace default service accounts.

**Comment by kfox1111** [comment]
That sounds like a good plan to me.

**Comment by deads2k** [comment]
> - Every Pod has a service account (non-empty string in service account
> field).
> - Pods without a service account mentioned at creation get the default
> service account.  Nothing disables this behavior.  We could move this from
> an admission control to a defaulter perhaps.  One use case is a create a
> namespace where I can run things with ambient authority without having to
> write long pod specs.

Agree.


> - An field on a service account object should control whether or not a
> kubernetes API credential is automatically added to that service account.
> The default service account has this set to true.  You can flip this flag
> and the cred will be removed, and you can make your whole namespace have no
> API credentials.

This is an interesting idea.  How would you link the secret back to the service account? Use the existing annotations?


> - In the future we might add other types of credentials to service accounts
> that are automounted.  One type might be a peer-to-peer identifying
> certificate.  Another might be a cloud provider service account.  We might
> not want to block these even if we want to block API access.  So no big
> hammers.

If we allow multiple different credentials, how would we indicate which ones would get auto-mounted and which ones wouldn't?


> - Sometimes you will want some containers to have API creds and others not
> to.  For example an init container that pokes at the API, the a server
> starts and you don't want the cred around anymore.  That should work.  Or a
> sidecar.  Someday we should support different service accounts per
> container.  For now, we can just have a flag per container to block the
> pod's secret automount behavior.
> - The Authorization plugin / cluster-admin is responsible for deciding what
> permissions a service account users has, including the default for new
> service accounts, including namespace default service accounts.


Agree.

**Comment by wernight** [comment]
I don't understand practically all what you mean. For example what does "Pods without a service account mentioned at creation get the default service account" mean? Does it mean that a Pod not explicitly asking for service accounts still gets a token that gives it some access?

**Comment by deads2k** [comment]
> I don't understand practically all what you mean. For example what does "Pods without a service account mentioned at creation get the default service account" mean? Does it mean that a Pod not explicitly asking for service accounts still gets a token that gives it some access?

No.  Given a configured authorizer, the SA token does not grant any permissions.  Also, a user could change the "automount SA token" bool to false if they wanted.

**Comment by mikedanese** [comment]
Can we add an annotation to a service account that instructs the token controller to not generate an API token secret for the account. E.g.:
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    service-account.alpha.kubernetes.io/skip-api-token: "true"
  name: no-access
  namespace: default
type: kubernetes.io/service-account-token
```
Then a user can use the no-access service account to create pods without api access.

**Comment by deads2k** [comment]
> Can we add an annotation to a service account that instructs the token controller to not generate an API token secret for the account? E.g.:

I don't think that works as well since SA tokens are good way to long lived, revocable tokens for machine purposes.  I can then use those credentials to power out of band scripts.  I probably won't ever create a pod using that SA, but if I did, I could reasonably want to prevent the secret from automounting.

Also, SAs have two categories of secrets: mountable secrets and image pull secrets.  It's natural to create image pull secrets based on the SA identity itself.  In such a case, I'd still want to have image pull secrets (which would require an SA token), but I wouldn't want those tokens automounted.

I think the marker for "automount SA token" resolves the problem while still allowing these uses to work as expected.

**Comment by wernight** [comment]
I hope the "automount SA token" is off by default so it's not mounted/provided by default. Could be on for upgrades if we can show a nice warning explaining how to turn it off.

**Comment by deads2k** [comment]
> I hope the "automount SA token" is off by default so it's not mounted/provided by default. Could be on for upgrades if we can show a nice warning explaining how to turn it off.

That would be a breaking API change.  We don't break our API intentionally, so automounting would be on by default and you can opt-in to disabling automounting on your serviceaccount.

**Comment by wernight** [comment]
I mean off by default for *new* clusters. Or off if using an old `apiVersion` in the Yaml. So this would not be a breaking change.

**Comment by mikedanese** [comment]
@wernight there are quite a few workflows that involve deploying many clusters per week (or per day). This would be a breaking change for those deployment styles.

We should publish a list of configs that moves a cluster towards secure and have a single flag in our deployment automation to enable all of these. This won't be stable until we fix some (many) outstanding security related cleanups. Eventually we can consider deprecating the old config set for the more secure config set.

**Comment by mikedanese** [comment]
@jcbsmpsn is looking into implementing a fix via the automount=false annotation.

**Comment by wernight** [comment]
As long as the release notes are clear and tutorials update to suggest putting `automount: false`, it looks like a decent solution.

Shouldn't in the long term, users be able to change `apiVersion:` for this kind of changes? It would mean having a backward-compatible API of course, but it would make it easier for users to handle this kind of changes.

**Comment by liggitt** [comment]
I would honor the option on both the pod and the service account… either should be able to opt out of auto mount.

**Comment by philips** [comment]
Yes +1 to automount annotation.

**Comment by deads2k** [comment]
> @jcbsmpsn is looking into implementing a fix via the automount=false annotation.

Why an annotation instead of an API field?  The same backwards compatibility concerns will exist either way and I think a field is more obvious.

**Comment by diclophis** [comment]
Defaulting to `automount: false` seems like a _huge_ win in terms of security

**Comment by roberthbailey** [comment]
@diclophis - we all agree, but also want to keep our backwards compatibility guarantees.

**Comment by liggitt** [comment]
agree it could be an improvement, not sure it's a *huge* win if you have authorization in place, though

either way, opened https://github.com/kubernetes/kubernetes/pull/37953 as a possible implementation

**Comment by dimpavloff** [comment]
> That would be a breaking API change. We don't break our API intentionally, so automounting would be on by default and you can opt-in to disabling automounting on your serviceaccount.

Hi, I'm still a bit new to this part of k8s but wouldn't it be possible to add a CLI flag to the controller manager specifying whether to create service accounts for each namespace or not and have it default to true for backwards compatibility? Or alternatively provide it with a list of the namespaces for which to create SAs / SAs with API access tokens?

**Comment by wernight** [comment]
CLI argument is not easy on GKE.

**Comment by kfox1111** [comment]
Cli will break helm packages and cause a lot of unexpected bug reports that arent real. Better to change a default in v2.

**Comment by shyamjvs** [comment]
+1 for this feature request

**Comment by fotinakis** [comment]
I think this is fixed in 1.6+?

https://github.com/kubernetes/kubernetes/pull/37953 implemented this on a pod:

```
spec:
  automountServiceAccountToken: false
```

Also see: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

**Comment by akostadinov** [comment]
yes, that has been said in https://github.com/kubernetes/kubernetes/issues/16779#issuecomment-264472133
You can either disable on the pod side or you can also set the option on the service account used for the pod (`default` by default).

**Comment by fotinakis** [comment]
Oops sorry I thought the issue was still open, I see now it's closed. 👍  Thanks!

**Comment by alexwrinner** [comment]
```
spec:
  automountServiceAccountToken: false
```
Thanks for url [👍](https://trustanalytica.com/online/top-cheap-essay-writing-services)
