### ISSUE TITLE
Secret key value pairs should have linux filename limitations for key name instead of DNS_SUBDOMAIN restrictions

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#16786]
Secret key names like **id_rsa** and **id_rsa.pub** are illegal (see https://github.com/kubernetes/kubernetes/issues/13357). This makes it impossible to use secrets for loading ssh keys and other files with underscores into your containers.

Can the restrictions be loosened so it maps to linux filename restrictions instead of DNS_SUBDOMAIN?

**Comment by mikedanese** [comment]
@pmorie @liggitt

**Comment by pmorie** [comment]
I'm fine with making this possible and don't see a reason not to, with the exception that arbitrary filenames of keys (ie, specifying subdirectories) has been problematic to get agreement about in the past.  That said, now the downward API allows you to do this, so perhaps we can re-use code / semantics of that.  Thoughts, @liggitt ?

**Comment by liggitt** [comment]
+1 on relaxing... I thought @deads2k had already opened an issue on this. Agree on no subpaths, need to prevent names like `.` or `..`.

**Comment by deads2k** [comment]
https://github.com/kubernetes/kubernetes/issues/6589 and https://github.com/kubernetes/kubernetes/issues/8236 are open now.

**Comment by pmorie** [comment]
I might do this next week at the kubecon hackathon.

**Comment by davidopp** [comment]
> #6589 and #8236 are open now.

Can we try to merge this issue and those two? Having one issue that nobody is working on somehow feels better than having three. :-)

**Comment by pmorie** [comment]
Related: #4789 

IMO the issue is that we can't project keys into specific filenames, not that keys have the wrong format, but my ear is open.

**Comment by pmorie** [comment]
I think we should close this -- it's a dupe of #4789

**Comment by JorritSalverda** [comment]
I agree it's a duplicate of https://github.com/kubernetes/kubernetes/issues/8236 and https://github.com/kubernetes/kubernetes/issues/4789.

Mounting the ssh keys without setting the appropriate file permissions doesn't work anyway, so filename is only part of the puzzle.
