### ISSUE TITLE
hack/verify-godeps doesn't work at head

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#16791]
It seems that hack/verify-godeps.sh script doesn't work at HEAD (which means we have somehow broken head).

You can take a look https://github.com/kubernetes/kubernetes/pull/16788 which doesn't modify any dependencies, but triggers hack/verify-godeps.sh (because the diff contains "Godeps" word), and it simply doesn't work.

This is blocking #16788 and #16725 (at least).

@kubernetes/goog-csi @kubernetes/goog-control-plane @lavalamp @timstclair

**Comment by lavalamp** [comment]
verify-godeps is supposed to only run when godeps changes...

**Comment by lavalamp** [comment]
@eparis, can you take a quick look?

**Comment by eparis** [comment]
poking.

**Comment by eparis** [comment]
quick look tells me that upstream godep binary made a change  :-(

**Comment by eparis** [comment]
(will send a PR to handle it)

**Comment by lavalamp** [comment]
thanks!!

**Comment by wojtek-t** [comment]
It seems that #16788 fixed the problem.
