### ISSUE TITLE
Allow setting http request timeout in kubernetes client

### ISSUE THREAD

**Issue by 2opremio** [kubernetes/kubernetes#16793]
I would like to set an http request timeout in the kubernetes Go client, however:

1. The underlying http client is not exposed.
2. Even if I access the underlying http client through an (admittedly inelegant) cast and set the timeout, requests fail because the Transport does not support the CancelRequest method.

The example below fails with `cannot make request: net/http: Client Transport of type *unversioned.userAgentRoundTripper doesn't support CancelRequest; Timeout not supported`

```go
package main

import (
        "fmt"
        k8sClient "k8s.io/kubernetes/pkg/client/unversioned"
        "net/http"
        "time"
)

func main() {
        client, err := k8sClient.NewInCluster()
        if err != nil {
                fmt.Printf("cannot create client: %s\n", err)
                return
        }
        httpClient, ok := client.RESTClient.Client.(*http.Client)
        if !ok {
                fmt.Println("cannot cast k8s client to http client")
        }
        httpClient.Timeout = time.Millisecond * 500
        if _, err := client.Services("default").Get("foo"); err != nil {
                fmt.Printf("cannot make request: %s\n", err)
        }
}
```

**Comment by 2opremio** [comment]
In addition, [`RESTClient.Timeout`](https://godoc.org/k8s.io/kubernetes/pkg/client/unversioned#RESTClient) is undocumented and thus, misleading. It may seem that it corresponds to the HTTP timeout, but it just sets the timeout query parameter in requests , e.g. `?timeout=foo`, something the user can only figure out by inspecting the kubernetes source code.

**Comment by mikedanese** [comment]
@kubernetes/goog-csi

**Comment by caesarxuchao** [comment]
@lavalamp you can assign this to me if we decide to add a CancelRequest method to our transports.

**Comment by 2opremio** [comment]
@caesarxuchao @lavalamp Apart from implementing `CancelRequest` I think it would be a good idea to:
*  Document [`RESTClient.Timeout`](https://godoc.org/k8s.io/kubernetes/pkg/client/unversioned#RESTClient)
* Expose the underlying http client (not just the [HTTPClient interface](https://godoc.org/k8s.io/kubernetes/pkg/client/unversioned#HTTPClient)) or provide a way to modify its Timeout without ugly casts :)

**Comment by hongchaodeng** [comment]
Just to follow on this issue.
It's confusing to have two timeouts -- `RESTClient.Timeout` and `http.Client.Timeout`. How to differentiate those?

**Comment by lavalamp** [comment]
Yes, the Timeout is not doing what you want.

@krousey, ideas about adding a (real) timeout? I vaguely recall some of us wanting that in a test...

@caesarxuchao, if you would like to update the documentation for the Timeout member variable (actually it should be private, IMO), that would be great.

I have no objections to supporting CancelRequest, but we should build on top of @krousey's transport PR.

**Comment by krousey** [comment]
@lavalamp we added real timeouts on the server side. I'm not sure what you're referring to with the testing situation. If we want to go full bore with this.... [context](https://godoc.org/golang.org/x/net/context)  plumbing? :smile:

**Comment by lavalamp** [comment]
I think @2opremio wants to set connection-level timeouts client side. Server side timeouts don't help.

**Comment by 2opremio** [comment]
@lavalamp Correct

**Comment by krousey** [comment]
@lavalamp I was just trying to gather what you test case you were talking about.

plumbing context through the code would be more of a per request timeout and not connection level timeout.

We could probably pull this off in request.Do somehow.

**Comment by hongchaodeng** [comment]
Just want to help out and share thoughts.

If we keep casting `RESTClient.HTTPClient` into `*http.Client`, it's not very nice abstraction and could incur maintaining problems.

One possible solution is to add a `connTimeout` or `requestTimeout` field in [Config](https://github.com/kubernetes/kubernetes/blob/69932aecb032de4b7e1e140ad0b8ad7e326bb7c5/pkg/client/unversioned/helper.go#L46). Then add CancelRequest to custom Transport.

**Comment by hongchaodeng** [comment]
@krousey 

Yes. We can definitely use context to implement timeout. See [this blog](https://blog.golang.org/context):
```Go
func httpDo(ctx context.Context, req *http.Request, f func(*http.Response, error) error) error {
    // Run the HTTP request in a goroutine and pass the response to f.
    tr := &http.Transport{}
    client := &http.Client{Transport: tr}
    c := make(chan error, 1)
    go func() { c <- f(client.Do(req)) }()
    select {
    case <-ctx.Done():
        tr.CancelRequest(req)
        <-c // Wait for f to return.
        return ctx.Err()
    case err := <-c:
        return err
    }
}
```

It's a little duplicate to Timeout in `http.Client`.

**Comment by lavalamp** [comment]
> If we keep casting RESTClient.HTTPClient into *http.Client, it's not very nice abstraction and could incur maintaining problems.

Yes, I don't want people to do this cast.

> One possible solution is to add a connTimeout or requestTimeout field in Config. Then add CancelRequest to custom Transport.

Yes, this sounds good, but look at @krousey's change to factor out the transport code-- we should add it to the transport config.

I'm a little confused about using context.Context to hold a client-side timeout. We don't currently use it client-side at all?

**Comment by 2opremio** [comment]
> Yes. We can definitely use context to implement timeout.

Please don't. Why use context to do what the http timeout is designed for?

**Comment by hongchaodeng** [comment]
It's legacy issue. The `http.Client` has Timeout field since Go 1.0. Context was a library open up much later.

Let's just use http timeout to keep consistency.

**Comment by hongchaodeng** [comment]
From what I read the code, we can make the abstraction better by the following:

- NewRESTClient() didn't set HTTPClient:
```Go
	client := NewRESTClient(baseURL, config.Version, config.Codec, config.QPS, config.Burst)
	transport, err := TransportFor(config)
	client.Client = &http.Client{Transport: transport}
```
Instead, we should add httpClient field in NewRESTClient() construction.

- RESTClientFor() and UnversionedRESTClientFor() are pretty much the same and we could add a common routine function.

- At the end of TransportFor(), it could possible returns some struct that doesn't supports CancelRequest(). If we just add that method to all structs (userAgentRoundTripper, basicAuthRoundTripper, etc.), that doesn't sound very convenient (again, I'm afraid of maintaining effort).
One proposal I had is that we should make use of `http.Transport ` which supports cancel request, redirects, caching connections, etc. We can then override RoundTrip() method for custom logic.

@2opremio @krousey @lavalamp This sounds we need some effort on it. But that's the correct way IMHO. Let me know you guys' thoughts.

**Comment by hongchaodeng** [comment]
Re. the Transport point,
To be more specific, we change `Config.Transport` to be 
```Go
type Config struct {
  transport *http.Transport
}
```
Then we can embed *http.Transport to necessary structs and override RoundTrip() if needed.

**Comment by lavalamp** [comment]
OK, I'm asking @caesarxuchao to just remove the current Timeout member, as it's confusing and I *think* the server only really uses it for watches.

As far as transport stuff, @hongchaodeng please take a look at #16126. I actually want it to work the other way, you should construct a transport and then pass it into the RESTClient's constructor. Please see: https://github.com/kubernetes/kubernetes/pull/15730/files#diff-db2b1446b41ce62918b3fc288d73dad0R62

**Comment by krousey** [comment]
@lavalamp No we don't currently use context in the client code. But in an ideal world sense, I think it would be the right solution if we were starting fresh.

If you wanted to do this at the transport level, the WrapTransport config parameter would be your best bet. This will allow you to still use our TLS framework.

The quickest and cleanest way to enable this is to just expose the http.Client in RESTClient and not hide it behind an interface. Why is that done anyway?

**Comment by lavalamp** [comment]
I think I'm fine with exposing the http.Client.

**Comment by caesarxuchao** [comment]
@lavalamp FYI `watch` actually uses TimeoutSeconds.

https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L277

**Comment by lavalamp** [comment]
@caesarxuchao Oh, right. Can you look at the server code and see if the timeout parameter is still used at all?

**Comment by caesarxuchao** [comment]
@lavalamp, yes, it's used by Create/Patch/Update/Delete handlers and passed to finishRequest. /https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L708

**Comment by lavalamp** [comment]
@caesarxuchao OK. this "timeout" is a remnant of some old code that doesn't exist anymore and hasn't for like a year. We used to start an "operation" and let the client poll for the response if it took too long. We don't do that any more, so "finishRequest" is now pointlessly starting a goroutine and then waiting for it. I'm 95% sure it's perfectly fine to remove both timeout and finishRequest.
