### ISSUE TITLE
Run kube-proxy in a static pod

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#16799]
This will help move it to daemonset

**Comment by luxas** [comment]
This would be useful, why isn't `kube-proxy` present by default in `master-multi.json`?
BTW, will the deprecation of static pods affect `master-multi.json`, when running containerized kubelet?

**Comment by mikedanese** [comment]
@luxas We are hoping to move kube-proxy into a DaemonSet, and static pods are a good intermediate step. They won't be static pods for long I hope.

**Comment by luxas** [comment]
OK, thanks for the info! 
`DaemonSets` is looking very interesting, hadn't read about that earlier
