### ISSUE TITLE
Container and pod resource limits

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#168]
Before we implement QoS tiers (#147), we need to support basic resource limits for containers and pods. All resource values should be integers.

For inspiration, see lmctfy:
https://github.com/google/lmctfy/blob/master/include/lmctfy.proto

Arguably we should start with pods first, to at least provide isolation between pods. However, that would require the ability to start Docker containers within cgroups. The support we need for individual containers already exists.

We should allow both minimum and maximum resource values to be provided, as lmctfy does. But let's not reuse lmctfy's limit and max_limit terminology. I like "requested" (amount scheduler will use for placement) and "limit" (hard limit beyond which the pod/container is throttled or killed).

Even without limit enforcement, the scheduler could use resource information for placement decisions.

**Comment by bgrant0607** [comment]
I'd really like to get the resource spec into v1beta3.
/cc @vmarmol

**Comment by bgrant0607** [comment]
The remaining thing we're doing in the near term is taking advantage of the proposed Docker parent cgroup feature to permit bounding pod resources.

**Comment by bgrant0607** [comment]
--cgroup_parent is in: https://github.com/docker/docker/pull/11428

**Comment by erictune** [comment]
Docker appear to support a `--cpu-quota` flag now.  Should we set that where it is supported?  This brings the behavior of limit for CPU closer to memory.  https://docs.docker.com/reference/run/#runtime-constraints-on-resources

**Comment by davidopp** [comment]
Would using that mean people couldn't burst over their requested (limit) CPU (at least over non-short timescales)? I'm not sure that's desirable. IMO it is better to distribute up 100% of the CPU in proportion to what people have requested (limit) rather than limit people to what they requested.

**Comment by smarterclayton** [comment]
That matches our experience - and how we run today (fair, but allow
bursting when it's available).

On Jun 30, 2015, at 3:39 PM, David Oppenheimer <notifications@github.com>
wrote:

Would using that mean people couldn't burst over their requested (limit)
CPU (at least over non-short timescales)? I'm not sure that's desirable.
IMO it is better to distribute up 100% of the CPU in proportion to what
people have requested (limit) rather than limit people to what they
requested.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/168#issuecomment-117315919>
.

**Comment by erictune** [comment]
@davidopp It's comforting to see that our positions remain unchanged and opposite after all these years. :wink:

**Comment by davidopp** [comment]
Heh. One thing we could consider is making it a cluster-level or even pod-level configuration option. I don't think this is a question where one answer is obviously wrong, I just think one answer is slightly more useful to people than the other. But I can definitely imagine that some people would want the behavior you like, and it doesn't seem hard to make it an option.

**Comment by derekwaynecarr** [comment]
I am interested in also allowing cluster operators to enable ```--cpu-quota``` to provide a ceiling to the maximum amount of CPU a given container/pod can consume before its actively throttled, so a +1 to @erictune suggestion to use it where its supported.

I also agree that not all operators will want to use that instead of ```--cpu-shares``` so I agree with @davidopp on that point as well.

At minimum, it should be a choice of the cluster operator.  We have some scenarios where its definitely more important to not use relative CPU shares just to provide a more consistent end-user experience, and we have other scenarios where we want to use as much as is available.

I also agree that we have scenarios where we want to expose it as an end-user option so a pod configurable field is also appropriate.  @davidopp when you suggest this, I assume you would still just only have ```Limits``` in the resource model, but it would be a flag to say how those limits are converted?  If so, we would also want some measure of admission control to prohibit a bad flag choice if the cluster operator configured to not support the option.

I think this is a near-term concern for us as part of general overcommit, so I am interested in picking up this discussion and getting others opinions on what we would or would not expose as flag to cluster or in end-user facing API.

**Comment by derekwaynecarr** [comment]
Is there a thought about a ```Burst``` field in addition to ```Limits``` that would allow you to exceed beyond your ```Limit``` if there is excess capacity, but not to 100% of the available node cpu?

**Comment by bgrant0607** [comment]
I don't want to be excessively explicit in this area, because we can gradually improve enforcement over time, by monitoring and throttling excessive usage, monitoring CPI to detect and kill (move) aggressors and/or scale usage, allowing some amount of bursting, etc.

**Comment by davidopp** [comment]
I think it's sufficient to just have a flag that says whether the specified limit is a hard cap or a soft cap.

How multiple pods (or containers or whatever) are arbitrated, e.g. whether one process is allowed to starve another and if so under what circumstances, seems like it falls into the QoS proposal. But I think being able to tell the system to cap you at your limit (or not) cam be considered a separate feature, since it makes sense even when you're the only process on a machine.

**Comment by bgrant0607** [comment]
I do not want to add a knob for hard/soft cap. The hard-cap option would be seldom used and is not intent-oriented, thereby impacting our ability to deliver any performance SLO. Options:
a) Use cpu limit to mean hard cap. Most pods/containers would likely specify only request.
b) Perform no hard capping by default. Gradually improve enforcement and isolation over time. We'd do this even in the case of (a).

**Comment by erictune** [comment]
Regarding (a):
Under the limit/request proposal for QoS in #147, limit > request is a different QoS than limit == request.
How would request set and limit unset be interpreted in that case?  Would we end up with different QoS for cpu vs memory?

**Comment by smarterclayton** [comment]
If we use limit to mean hard cap, we can still vertical autosize / default when a user specifies request.  As Derek notes, we want to offer predictable behavior when pods run on multiple heterogenous workloads for end users and admins (which shares can't guarantee), which negatively impacts utilization in some cases but offers a predictable experience for admins.

Do we have the tools to distinguish qos properly when an autosizer is present?  Should the autosizer know enough about qos to reflect the appropriate use?

**Comment by davidopp** [comment]
@erictune My understanding is that request set (say to value "R") and limit unset would be interpreted the way Borg handles memory limit = R with allow_overlimit_mem, and CPU limit = R.

**Comment by timothysc** [comment]
> a) Use cpu limit to mean hard cap. Most pods/containers would likely specify only request.

agreed, that only hard limits as an option.

> b) Perform no hard capping by default. Gradually improve enforcement and isolation over time. We'd do this even in the case of (a).

disagree, not hard capping will affect SLO. 

I do believe what's missing in this conversation is the notion of history in proper sizing.  Right now there is no job-history service to yield best-guess on actual usage.

**Comment by Iwan-Zotow** [comment]
Gentlemen,

I'm running Monte Carlo on google cloud cluster now, and to emulate batch scheduling I had to set CPU limit to some strange values.

**Comment by vishh** [comment]
FYI: Docker now supports updates to cgroups [#15078](https://github.com/docker/docker/pull/15078/files)

**Comment by andyxning** [comment]
Allowing memory limit over-commiting may cause unpredicatable process killing by triggering kernel OOM killers.

I have run a program which allocate 50GB memory in a pod whose memory limit is 118GB on a node with 64GB. when the program is running for several seconds, it is oom killed and i can get the oom killer log in `/var/log/syslog`.

**Comment by montanaflynn** [comment]
Hard limits for CPU are very important for our video transcoding pods we run on Google Container Engine. We need to have nodes with lots of cores for speed but also don't want a single pod greedily using up all the cores. It would be ideal to set their limit at 3/4 of the total nodes CPU. 

We can currently do this for scheduling with `requests` so we don't put two transcoders on a single node but the lack of hard limits mean that when the pod is running it uses all the cores even with `limits` set. This had led us to having two clusters, one especially for transcoding large media and the other for small media and the rest of our services.

**Comment by thockin** [comment]
I thought we used shares for "request" and quota for "limit" thereby
providing true hard limits.  Did I mis-comprehend?

**Comment by smarterclayton** [comment]
So did I - are you not seeing quota enforced?  What docker version are you on?

**Comment by montanaflynn** [comment]
It seems hard limits came with v1.2 based on the [changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md/#action-required-11). I remember when I first started with kubernetes there was a warning saying that CPU limits were not enforced. Maybe it was that my host OS that didn't support it. Looking at the [compute resources documentation] it looks like kubernetes does support hard limits by default now.

> CPU hardcapping will be enabled by default for containers with CPU limit set, if supported by the kernel. You should either adjust your CPU limit, or set CPU request only, if you want to avoid hardcapping. If the kernel does not support CPU Quota, NodeStatus will contain a warning indicating that CPU Limits cannot be enforced.

**Comment by thockin** [comment]
Note that CPU hardlimits can be surprising.  All it guarantees is that you
can use X core-seconds per wall-second.  Consider a 16 core machine, and a
pod that has an 8 core limit.  If your app is multi-threaded or
multi-process, and the number of executable threads/processes is larger
than 8, you could use up all 8 cores of your limit in less than 1 wall
second.  If you used all 16 cores for 0.5 seconds, you would leave your pod
ineligible to run for 0.5 seconds (that's a long time!), giving you
terrible tail latency.

Now, in reality the time slice is smaller, but it is still in the tens or
hundreds of milliseconds.  If you're not careful, you really could find
yourself with unexpected latency blips of 50 or 100 milliseconds or more.

**Comment by timothysc** [comment]
If it's a hard constraint to not tolerate the blips, then you're likely looking for cpu affinity or cpu-sets.  xref: https://github.com/kubernetes/kubernetes/issues/10570

**Comment by montanaflynn** [comment]
I'm on google cloud's container engine and found the warning I referenced above is still shown while running master and nodes kubernetes version 1.3.5:

The warning is displayed with `kubectl describe nodes` is`WARNING: CPU hardcapping unsupported`.

```
$ kubectl describe nodes
Name:			gke-cluster-1-default-pool-777adf16-an5j
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/instance-type=n1-highcpu-8
			beta.kubernetes.io/os=linux
			cloud.google.com/gke-nodepool=default-pool
			failure-domain.beta.kubernetes.io/region=us-central1
			failure-domain.beta.kubernetes.io/zone=us-central1-b
			kubernetes.io/hostname=gke-cluster-1-default-pool-777adf16-an5j
Taints:			<none>
CreationTimestamp:	Wed, 12 Sep 2016 08:14:45 -0700
Phase:
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  NetworkUnavailable 	False 	Mon, 01 Jan 0001 00:00:00 +0000 	Wed, 07 Sep 2016 18:15:58 -0700 	RouteCreated 			RouteController created a route
  OutOfDisk 		False 	Mon, 12 Sep 2016 14:15:13 -0700 	Wed, 07 Sep 2016 18:14:45 -0700 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Mon, 12 Sep 2016 14:15:13 -0700 	Wed, 07 Sep 2016 18:14:45 -0700 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Mon, 12 Sep 2016 14:15:13 -0700 	Wed, 07 Sep 2016 18:15:21 -0700 	KubeletReady 			kubelet is posting ready status. WARNING: CPU hardcapping unsupported
```

**Comment by vishh** [comment]
@montanaflynn On Google Container Engine can you switch to `GCI` as the image type. You can upgrade your node-pool to GCI by setting `--image-type=gci` or pass that flag while creating a new cluster.
`GCI` is the new version of the existing debian 7 based base image on GKE. CPU limits are supported there.

**Comment by montanaflynn** [comment]
@vishh where / how could I set `--image-type=gci` for an existing cluster?

**Comment by vishh** [comment]
@montanaflynn Assuming you have only the default node-pool, run `gcloud container clusters upgrade <your_cluster_name> --image-type gci --node-pool default-pool`. 
This change is disruptive since it restarts existing nodes. 
Another option is to create a new node pool for your cluster that is using GCI and then slowly turn down the default node pool. - `gcloud container node-pools create --cluster <your_cluster_name> --image-type gci`

**Comment by montanaflynn** [comment]
Thanks! Will container engine be using that image by default in the future?

**Comment by vishh** [comment]
Yes. That *might* happen as early as v1.4 on GKE.

**Comment by timothysc** [comment]
I think we should move to close this issue, the root topic has been addressed but there are multiple side-threads that are on this issue where I believe they would be better served on other issues.  

@vishh thoughts?

**Comment by derekwaynecarr** [comment]
I think this can be closed.

**Comment by maicohjf** [comment]
> Before we implement QoS tiers (#147), we need to support basic resource limits for containers and pods. All resource values should be integers.
> 
> For inspiration, see lmctfy:
> https://github.com/google/lmctfy/blob/master/include/lmctfy.proto
> 
> Arguably we should start with pods first, to at least provide isolation between pods. However, that would require the ability to start Docker containers within cgroups. The support we need for individual containers already exists.
> 
> We should allow both minimum and maximum resource values to be provided, as lmctfy does. But let's not reuse lmctfy's limit and max_limit terminology. I like "requested" (amount scheduler will use for placement) and "limit" (hard limit beyond which the pod/container is throttled or killed).
> 
> Even without limit enforcement, the scheduler could use resource information for placement decisions.

https://github.com/kubernetes/kubernetes/issues/168#issue-36096052

Schedule a Pod as follows:
 Name: nginx-kusc00101
 Image: nginx
 Node selector: disk=ssd



apiVersion: v1
kind: Pod
metadata:
    name: nginx-kusc00101
spec:
    containers:
        - name: nginx-kusc00101
           image: nginx
    nodeSelector:
           disk: ssd

kubectl create -f nginx-kusc00101.yaml
