### ISSUE TITLE
GKE upgrades from 1.0 to 1.1 failing on "expected to find 3 nodes but found only 2"

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16803]
See jobs 132 and onward for `kubernetes-upgrade-1.0-1.1-gke-step4-upgrade-cluster` Jenkins job.

**Comment by ihmccreery** [comment]
I believe this is a test problem, not a GKE problem, but I could be wrong.

I think this has surfaced due to #16804, and something changed/broke in HEAD.  I'm going to fix #16804 first to get those jobs green, and then we can look into this further.

**Comment by alex-mohr** [comment]
@ihmccreery Obsolete?

**Comment by ihmccreery** [comment]
Oops, yes, I fixed this a while ago.
