### ISSUE TITLE
Deprecate `gitMajor` and `gitMinor`

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16815]
Right now our build infrastructure relies on versioning in three (or maybe four?) different ways:

- `gitMajor` and `gitMinor` in `pkg/version/base.go`,
- `gitVersion` and `gitCommit`, also in `pkg/version/base.go`,
- `git describe` version, based off of tags, and
- the possibility to override `KUBE_GIT_COMMIT` and other env variables in `hack/lib/version.sh`.

We should at least deprecate and eventually remove `gitMajor` and `gitMinor`, and maybe think harder about how we want to consolidate the other three versioning methods.

@bgrant0607 for commenting on if and how we can deprecate `gitMajor` and `gitMinor`, since this is output by `kubectl` and other utilities, so may be under API contract.

**Comment by bgrant0607** [comment]
We have deprecated a number of kubectl features, but so far haven't removed any. We need to establish a policy re. backward compatibility, but we don't have an official one yet.

cc @eparis

**Comment by bgrant0607** [comment]
This string is returned by the API?

**Comment by ihmccreery** [comment]
Er, I'm not sure; it's returned by `kubectl version`, e.g.:

```console
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.3.89+f64780d6eb0c16", GitCommit:"f64780d6eb0c163514cba049c867ba16a45424d2", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.3.89+f64780d6eb0c16", GitCommit:"f64780d6eb0c163514cba049c867ba16a45424d2", GitTreeState:"clean"}
```

**Comment by ihmccreery** [comment]
So, yeah, it's a returned by the master, (as well as the client).

**Comment by eparis** [comment]
I see little reason to keep Major/Minor.  Version and commit (or just version since it embeds commit) is enough for me.

My understanding of how all of these things at least used to get filled out...

When building from git we use -X to overwrite the values in base.go based on git describe
When we make a tar ball we use `git archive` which will overwrite stuff in base.go which I think also comes from git describe? maybe? I'd have to look again/....

We at RH only used the ENV var's as our build system takes a tarball. Since we typically grab tarball snapshots from github instead of using git archive that means we had to set major/minor/commit/clean-dirty outselves. We may be able to re-architect our stuff to use a tarball from git archive instead of from github and thus eliminate the env var overrides (assuming it get git commit right)...  @ingvagabund

**Comment by ihmccreery** [comment]
This is probably blocked on at least parts of #16529, because right now our releasing infrastructure expects `gitMajor` and `gitMinor` to be present and updatable.  That should instead be the domain of build, but isn't right now.

**Comment by david-mcmahon** [comment]
djmm-kubernetes (master)$ fgrep -Ir gitMinor *
hack/lib/version.sh:      $(kube::version::ldflag "gitMinor" "${KUBE_GIT_MINOR}")
pkg/version/base.go:	// TODO: Deprecate gitMajor and gitMinor, use only gitVersion
pkg/version/base.go:	gitMinor string = "" // minor version, numeric possibly followed by "+"
pkg/version/version.go:		Minor:        gitMinor,
release/cut-official-release.sh:  $SED -ri -e "s/gitMinor\s+string = \"[^\"]*\"/gitMinor string = \"${version_minor}\"/" "${version_file}"

It looks as it only hack/lib/version.sh has a dependency here.  What's stopping us from regex'ing major/minor out of the version itself and doing away with gitMinor and gitMajor right now?

**Comment by ihmccreery** [comment]
> It looks as it only hack/lib/version.sh has a dependency here. What's stopping us from regex'ing major/minor out of the version itself and doing away with gitMinor and gitMajor right now?

Nothing, as far as I'm concerned.  I'd also like to see it disappear from the version string entirely, though.  That's an API change, I think, so would need approval from @kubernetes/kube-api

**Comment by bgrant0607** [comment]
/version is under API contract and, sadly, that's not a versioned API currently. There would have to be a super-compelling reason to change it.

**Comment by david-mcmahon** [comment]
This looks to have more far reaching effects.  Lowering to P3 for now.  I suspect this can be simply closed now, however.

**Comment by david-mcmahon** [comment]
This doesn't look like it's going to happen.  Closing.
