### ISSUE TITLE
The documentation for labels is wrong/confusing

### ISSUE THREAD

**Issue by alexanderkjeldaas** [kubernetes/kubernetes#16812]
From the kubernetes user guide:

http://kubernetes.io/v1.0/docs/user-guide/labels.html

"Each object can have a set of key/value labels defined. Each _Key_ must be unique for a given object."

Then goes on to list examples:

Example labels:

```
"release" : "stable", "release" : "canary", ...
"environment" : "dev", "environment" : "qa", "environment" : "production"
"tier" : "frontend", "tier" : "backend", "tier" : "middleware"
"partition" : "customerA", "partition" : "customerB", ...
"track" : "daily", "track" : "weekly"
```

If the examples are keys, then they will obviously not be unique per object.  I think the documentation probably should read something like:

"Each Key must have a unique value for a given object."

**Comment by lavalamp** [comment]
I think the idea is to pick one choice from each line, but I agree that's confusing.

**Comment by spzala** [comment]
@alexanderkjeldaas As I read the doc, I agree with @lavalamp that examples are showing some common labels specially commonly used keys. I personally am OK with the doc, but if it can confuse you and @lavalamp also thinks so, I am sure it can be confusing to many. I will try to change it. Thanks!

**Comment by spzala** [comment]
I have created this PR with minimal changes to doc but hope that removes confusion https://github.com/kubernetes/kubernetes.github.io/pull/4020

**Comment by spzala** [comment]
@alexanderkjeldaas @lavalamp hello, this related doc patch is merged kubernetes/kubernetes.github.io#4020 if that looks good, can we close this issue please? Thanks!

**Comment by alexanderkjeldaas** [comment]
Feel free to close.  This was just a microscopic nit.
