### ISSUE TITLE
SyncLoop log spam

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#16820]
It appears in a recent commit (probably 2eb17df) this log message was added:

```
Nov 04 23:12:30 ip-172-20-0-49 kubelet[31285]: I1104 23:12:30.006819   31285 kubelet.go:2161] SyncLoop (SYNC): 0 pods
```

It's printed as type `Info` and is logged every second, which is cluttering up the logs quite a bit. Is this necessary?

**Comment by yujuhong** [comment]
Sorry for the spam. I also saw this in the log and wanted to fix it. PR uploaded.

**Comment by paralin** [comment]
That PR works! Thanks :)
