### ISSUE TITLE
Create a terraform backend for Kubernetes

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#16827]
There doesn't appear to be one.

https://github.com/hashicorp/terraform/tree/master/builtin/providers

**Comment by abevoelker** [comment]
This would be amazing to have. Someone linked me to these Terraform PRs when I mentioned it on Twitter:

https://github.com/hashicorp/terraform/pull/3584
https://github.com/hashicorp/terraform/pull/3453

So unless I'm misunderstanding, I think the work has already been started?

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by mattes** [comment]
https://www.terraform.io/docs/providers/kubernetes/index.html

**Comment by luxas** [comment]
cc @jbeda You had some thoughts/work on Terraform and kubeadm?
I think this issue could use a little more instructions/rationales/work-items in order to be relevant.

_I guess_ this issue is just stale, a lot of things have happened since Nov 2015...

**Comment by luxas** [comment]
Plus the fact @mattes pointed out; there is a Kubernetes provider in Terraform now...

**Comment by roberthbailey** [comment]
I think this issue is obsolete. Please re-open if you disagree.
