### ISSUE TITLE
Evaluate the benefits of adopting docker event stream

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#16831]
In #12540, docker event stream was proposed as part of the pod lifecycle event generator (PLEG) to reduce number of docker operations.

However, even without adopting the docker event stream, we can still implement a PLEG solely by periodically relisting the containers. The generic PLEG in #13571 is an example. 
This would still improve the average resource usage of kubelet and docker because only one goroutine queries docker at a higher frequency (as opposed to all pod workers). The drawback, on the other hand, is that kubelet's reaction time to container events would be equal or greater than the relist period. We should try to understand the limit of pure relisting by running some micro-benchmark using docker, so that we know how much benefits the container event stream can bring us.

Metrics:
- latency
- cpu usage percentiles

Parameters to vary:
- op: list, inspect
- period
- number of containers
- GCE machine size

The next step would be benchmarking the docker event stream.

/cc @kubernetes/goog-node

**Comment by Random-Liu** [comment]
OK, will do! This is indeed necessary for future work. :)

**Comment by vishh** [comment]
+1 for starting with the Generic PLEG.
One thing to consider is the resource overhead of periodic relisting on the
docker daemon.

**Comment by yujuhong** [comment]
Now that we've added both a generic PLEG and a cache. We should re-evaluate the benefit of adopting the docker event stream and whether we should prioritize it.

**Comment by Random-Liu** [comment]
Post some benchmark result for this:
https://docs.google.com/document/d/1_mmIFY6MU8SovilagiAFXXwNSBHzdJTCdSj_8KdgZVg/edit?usp=sharing

**Comment by MHBauer** [comment]
I am familiar with the docker side of events. With a little guidance I can help do the work in the kube code.

**Comment by Random-Liu** [comment]
@MHBauer We are redefining the container runtime interface now https://github.com/kubernetes/kubernetes/issues/22964.
At least now, event is not in our short plan, because not all runtimes support event now, e.g. rkt. And according to our measurement, event stream does improve the performance, but not much.

/cc @yujuhong

**Comment by yujuhong** [comment]
@MHBauer that's great.

As @Random-Liu pointed out, event stream will improve performance and resource usage for kubelet, but since 1) not all runtimes support this and 2) the benefits significant enough, we didn't prioritize switching to the event stream.

The problem is a little bit more complicated than simply interfacing with the docker event stream. If you are interested, here is some background.

Kubelet has a Pod Lifecycle Event Generator, [PLEG](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pleg/generic.go) that is compatible with all runtimes. PLEG does basically two things:
 1. periodically polls docker (via `docker ps -a`) and compare the current container list with the last one. If there is any change, it generates an event.
 2. In addition to generating an event, it also does `docker inspect` calls and updates an in-memory pod status cache.

Kubelet has a per-pod goroutine (aka a pod worker) checking a pod periodically. Every time a worker syncs a pod, it gets the current status from the pod status cache to avoid hitting docker directly. Before the next sync can start, the worker will need to wait until all the side-effects (i.e., events) from the previous sync have been observed by PLEG and the in-memory cache has been updated accordingly. This is important because otherwise the worker may create the same container again! To enforce this rule, PLEG records a timestamp on each relisting, to indicate how fresh the cache is. The worker will block until the cache is newer than its last sync.

If we want to use switch to docker event stream today, we'll need to 
 1. add a docker-specific PLEG.
 2. handle the working syncing problem.

(2) is required because if kubelet doesn't receive any events over a period of time, it'd not know if there are truly no events, or the events are simply delayed. This is not the case for `docker ps -a` with an absolute timestamp to show how fresh the cache is. This issue can be handled by [recording expected events](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/pod-lifecycle-event-generator.md#generate-expected-events), which requires modifying a non-trivial amount of kubelet code.

**Comment by yujuhong** [comment]
This issue can be adapted to evaluate whether we need to support event stream in CRI. It is very low priority right now unless the need can be identified clearly.
