### ISSUE TITLE
Validation workflow need to be updated in ubuntu.md

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#16838]
The current scripts did not print `Cluster validation succeeded`:

```

Kubernetes cluster is running.  The master is running at:

  http://10.10.102.153:8080

Using master 10.10.102.153
It looks as if you don't have a compiled kubectl binary

If you are running from a clone of the git repo, please run
'./build/run.sh hack/build-cross.sh'. Note that this requires having
Docker installed.

If you are running from a binary release tarball, something is wrong. 
Look at http://kubernetes.io/ for information on how to contact the 
development team for help.

```
I guess some validation steps are actually un-needed in ubuntu workflow? maybe we need to remove that line in the doc (at least)? @dalanlan

**Comment by dalanlan** [comment]
Starting a cluster from a clean env should not suffer this. @WIZARD-CXY got this situation once yet I didn't have any luck to reproduce it.
Could you please provide more details to help reproduce this? I'll take a closer look at it. 

Thursday, November 5, 2015, 12:05 +0800 from Harry Zhang  <notifications@github.com>:
>The current scripts can not pass validation (completely) and print Cluster validation succeeded:
>Kubernetes cluster is running.  The master is running at:

  http://10.10.102.153:8080

Using master 10.10.102.153
It looks as if you don't have a compiled kubectl binary

If you are running from a clone of the git repo, please run
'./build/run.sh hack/build-cross.sh'. Note that this requires having
Docker installed.

If you are running from a binary release tarball, something is wrong. 
Look at http://kubernetes.io/ for information on how to contact the 
development team for help.

**Comment by resouer** [comment]
I think I know the reason, here's where `Cluster validation succeeded` occurs:
```
$ grep -rl "Cluster validation succeeded" .
./test/e2e/cluster_upgrade.go
./docs/getting-started-guides/ubuntu.md
./cluster/validate-cluster.sh

$grep -rl validate-cluster.sh .
./docs/getting-started-guides/scratch.md
./cluster/kube-push.sh
./cluster/kube-util.sh
./cluster/gce/upgrade.sh
./cluster/centos/util.sh
./cluster/rackspace/kube-up.sh
```
Thus, `Cluster validation succeeded` should never be print out in `ubuntu` workflow. Any thoughts? If you feel ok, I can send a pr

**Comment by dalanlan** [comment]
What is expected when all the things function properly is like following. 
```
Validating master
Validating vcap@10.10.103.100
Validating vcap@10.10.103.101

Kubernetes cluster is running.  The master is running at:

  http://10.10.103.100:8080

Using master 10.10.103.100
cluster "ubuntu" set.
user "ubuntu" set.
context "ubuntu" set.
switched to context "ubuntu".
Wrote config for ubuntu to /home/emma/.kube/config
... calling validate-cluster
Found 2 node(s).
NAME            LABELS                                 STATUS    AGE
10.10.103.100   kubernetes.io/hostname=10.10.103.100   Ready     5m
10.10.103.101   kubernetes.io/hostname=10.10.103.101   Ready     5m
Validate output:
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   nil
etcd-0               Healthy   {"health": "true"}   nil
controller-manager   Healthy   ok                   nil
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at http://10.10.103.100:8080
```
As you can see, we do have `Cluster validation succeeded`, which is called by https://github.com/kubernetes/kubernetes/blob/master/cluster/kube-up.sh#L45 
To make it more clear, we have double-check in the kube-up workflow, which could be a little confusing.

**Comment by dalanlan** [comment]
That said, what occurred to you earlier, is definitely a bug elsewhere.

**Comment by dalanlan** [comment]
Hmm, caught it.
Looks like you dont have a valid local path for `kubectl` binary. https://github.com/kubernetes/kubernetes/blob/master/cluster/kubectl.sh#L81~#L101
