### ISSUE TITLE
Deleting a node doesn't reschedule pods

### ISSUE THREAD

**Issue by chbatey** [kubernetes/kubernetes#16846]
I had a 6 node K8 cluster. I deleted three nodes using kubectl delete.

I expected the pods running on those containers to be rescheduled, possibly after the PodEvicition timeout as happens when the node is down. 

However the behaviour I observed was that the node is gone from kubectl get nodes but when I get the pods with -o wide they are still assigned to the node that I have removed.

Is this expected behaviour? There was nothing in the controller logs about the node being deleted.

K8 version v1.0 running on Centos 7.

**Comment by dchen1107** [comment]
@chbatey I believe you are hitting the issue: https://github.com/kubernetes/kubernetes/issues/13492 and https://github.com/kubernetes/kubernetes/issues/12041

cc/ @brendandburns @lavalamp @wojtek-t

**Comment by davidopp** [comment]
I believe this was fixed in 1.1. Are you able to reproduce this problem on a 1.1.x cluster?

**Comment by chbatey** [comment]
We will be upgrading in the next couple of weeks so will check

**Comment by chbatey** [comment]
Tested this on a 1.2 cluster. No longer an issue. Thanks!

**Comment by dchen1107** [comment]
@chbatey good to hear this. Close the issue.
