### ISSUE TITLE
github.com/scalingdata/gcfg  -->  gopkg.in/gcfg.v1

### ISSUE THREAD

**Issue by onlyjob** [kubernetes/kubernetes#16844]
Please consider switching from obsolete "[github.com/scalingdata/gcfg](https://github.com/scalingdata/gcfg)" to "[gopkg.in/gcfg.v1](https://gopkg.in/gcfg.v1)".
See #16843. Thanks.

**Comment by spzala** [comment]
Hello, is this still an issue or we can close it? Seems like it's taken care under #16843 Thanks!!

**Comment by spzala** [comment]
I see  "Closes #16844." comment in the https://github.com/kubernetes/kubernetes/pull/22486  So I guess this issue (#16844) is good to close?
