### ISSUE TITLE
Cleanup:  deprecated v1beta1 (deleted on June 1, 2015)

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#16848]
I found our codes refer to deprecated v1beta1(deleted on June 1, 2015) someplace. Sometimes, I confused it with extesions/v1beta1. I think we should cleanup the content of deprecated v1beta1 or note it clear.

**Comment by a-robinson** [comment]
Looks like #16849 fixed this, so marking as done.
