### ISSUE TITLE
[question] Scheduling constraint/policy: Exactly one pod per node

### ISSUE THREAD

**Issue by bertrand-quenin** [kubernetes/kubernetes#16856]
Hi,

I have a question regarding the replication controller (or the element responsible to assign pods to nodes).
Is it possible to define a constraint/policy in the replication controller (or other) in order to have exactly one pod per node ?
It would be interesting for instance for cadvisor containers where you want only one instance running per docker daemon (per host).

I didn't see anything like this in the documentation, can someone help me on that topic ?

Regards,
BQ.

**Comment by dchen1107** [comment]
Is this https://github.com/kubernetes/kubernetes/blob/95b265390e530eb137beac4288ba28d63c1142da/docs/design/daemon.md answered your question?

**Comment by bertrand-quenin** [comment]
Thanks for your answer !
I think it's exactly what I need. I didn't even know about this DaemonSet concept.
I assume it's only available starting with Kubernetes v1.1.0, is that right?

**Comment by dchen1107** [comment]
DaemonSet feature is still under development, and it is not available as beta feature for 1.1 release. But please feel free to play with it and give us the feedback. 

cc/ @erictune @mikedanese

**Comment by raliste** [comment]
Is this something that can be implemented on a StatefulSet ?
