### ISSUE TITLE
Cut a 1.1 conformance test

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#16860]
The 1.0 test should continue to pass against 1.1 clusters. The 1.1 test may or may not pass against 1.0 clusters if we add additional feature tests to it.

**Comment by lavalamp** [comment]
@kubernetes/sig-scalability

**Comment by wojtek-t** [comment]
I think it should currently work.
However, I agree that since we are changing it, it may stop working at some point.

**Comment by ixdy** [comment]
Given #18162, we should probably close this issue too?

**Comment by spiffxp** [comment]
agreed
