### ISSUE TITLE
kube-ui is inaccessible after starting a mesos-docker cluster

### ISSUE THREAD

**Issue by extesy** [kubernetes/kubernetes#16875]
Following https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/mesos-docker.md guide I see from the console that addons are supposed to be started successfully:

    Deploying Addons
    namespace "kube-system" created
    Workspace created: /Users/oanashki/Projects/kubernetes/k8sm-dns-XXXXXX.E5El7gBt
    Deploying DNS Addon
    replicationcontroller "kube-dns-v9" created
    service "kube-dns" created
    Workspace deleted: /Users/oanashki/Projects/kubernetes/k8sm-dns-XXXXXX.E5El7gBt
    Deploying UI Addon
    replicationcontroller "kube-ui-v3" created
    service "kube-ui" created

But attempt to access kube-ui redirects to https://172.17.0.5:6443/api/v1/proxy/namespaces/kube-system/services/kube-ui/#/dashboard/ which returns this error:

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kube-ui\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

I've tried recreating kube-ui addon, but it already exists:

```
./cluster/kubectl.sh create -f cluster/addons/kube-ui/kube-ui-rc.yaml                                                                                      [13:07:35]
Error from server: error when creating "cluster/addons/kube-ui/kube-ui-rc.yaml": replicationControllers "kube-ui-v3" already exists

/cluster/kubectl.sh create -f cluster/addons/kube-ui/kube-ui-svc.yaml                                                                                     [13:08:46]
Error from server: error when creating "cluster/addons/kube-ui/kube-ui-svc.yaml": services "kube-ui" already exists
```
I can also see the status for these addons:
```
./cluster/kubectl.sh get pods --namespace=kube-system                                                                                                      [12:56:53]
NAME                READY     STATUS    RESTARTS   AGE
kube-dns-v9-7nuew   0/4       Pending   0          16m
kube-ui-v3-5dffj    0/1       Pending   0          16m
```
Yet I still can't access them. What am I missing?

**Comment by a-robinson** [comment]
You can't access them because the pods aren't running yet (the status is `PENDING`). This can occur for a number of reasons, some of which are explained here: https://github.com/kubernetes/kubernetes/wiki/Debugging-FAQ#by-symptom

If you have further questions on getting set up, StackOverflow is the place to ask them so that answers to past questions are more discoverable. Please reserve Github issues for bugs and feature requests.
