### ISSUE TITLE
Document deprecation policy

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#16873]
Seeing as the 1.0 milestone was reached ~3 months ago, the following needs updating...

```
 Elimination of resources or fields will require following a deprecation process. The precise deprecation policy for eliminating features is TBD, but once we reach our 1.0 milestone, there will be a specific policy.
```

https://github.com/kubernetes/kubernetes/blob/master/docs/api.md

**Comment by bgrant0607** [comment]
To document:
* whole apiversions, alpha, beta, and GA
* API fields, alpha, beta, and GA
* kubectl commands and flags
* component configuration options

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by thockin** [comment]
I am working on a draft deprecation policy doc, and when that is ready I'll
fix up some or all of this in the same PR.  OK?

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by thockin** [comment]
https://kubernetes.io/docs/reference/deprecation-policy/
