### ISSUE TITLE
e2e failure on aws: KubeletManagedEtcHosts should test kubelet managed /etc/hosts file

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#16872]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_etc_hosts.go:54
Nov  4 12:20:00.142: /etc/hosts file should be kubelet managed, but is not: "10.245.1.102\ttest-pod\n127.0.0.1\tlocalhost\n::1\tlocalhost ip6-localhost ip6-loopback\nfe00::0\tip6-localnet\nff00::0\tip6-mcastprefix\nff02::1\tip6-allnodes\nff02::2\tip6-allrouters\n

**Comment by dchen1107** [comment]
cc/ @brendandburns

**Comment by dchen1107** [comment]
I can reproduce the issue without accessing aws nodes by downgrade my docker version from 1.8.X to 1.7.X. There is no functional breakage, and shouldn't block 1.1 release. I will fix the tests. 

On node with docker 1.8.X
```
$ cluster/kubectl.sh exec --namespace=kube-system heapster-v10-4ipqn -c heapster cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.244.2.3	heapster-v10-4ipqn
```
On node with docker 1.7.X which I believe those aws nodes running with: 
```
$ cluster/kubectl.sh exec --namespace=kube-system heapster-v10-4ipqn -c heapster cat /etc/hosts
10.244.2.3	heapster-v10-4ipqn
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```

**Comment by dchen1107** [comment]
To make my above comment more clear: The feature of kubelet managing container's /etc/hosts file relies on docker/docker#14613, which is only included in docker 1.8.X and above.

**Comment by gmarek** [comment]
It happened just now: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10217/

**Comment by roberthbailey** [comment]
@dchen1107 -- Is this a flake or just plain broken on AWS with docker 1.7?

@justinsb -- Can you verify which version of docker is running on AWS installs?

**Comment by dchen1107** [comment]
This is a plain broken with docker pre-1.8 release due to test itself. I thought @justinsb already updated aws to docker 1.8.X, or at least there is a pending pr for that. That is why I didn't update test by introducing more conditions.

**Comment by justinsb** [comment]
I updated to docker 1.8.3 in #19797, which merged 2 days ago.   (And that patch wasn't entirely correct either: #19869)  And only for Ubuntu Vivid, and we pull from docker's repo instead of the GS bucket.

So lots of caveats, but we should now be on 1.8.3.

AWS is totally broken right now on master until #19354 merges, FYI.

I'd love to get e2e on AWS running automatically again...

**Comment by thockin** [comment]
For those of us barely following along - does that mean that this test is NOT a flake, just a min-bar not being satisfied?

**Comment by roberthbailey** [comment]
@thockin that's what I was trying to ascertain and it sounds like the answer is 'yes' (@dchen1107 can correct me if i'm mis-interpreting).

**Comment by dchen1107** [comment]
The answer is yes, and I have a pending pr to ignore the failure when docker version is pre-1.8.

**Comment by thockin** [comment]
great, closing this
