### ISSUE TITLE
Horizonal pod autoscaler e2e tests not running anywhere?

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#16880]
As far as I can tell the Horizontal pod autoscaling tests aren't actually being run anywhere.

I turned them on for [GKE](http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-1.1-features/), and they do not pass. I ran locally against a gke cluster and the tests just time out waiting for rc to be scaled. While it's waiting the hpa sees current CPU utilization as <not available>.
```
cluster/kubectl.sh describe hpa rc --namespace=e2e-tests-horizontal-pod-autoscaling-4vka2 
Name:				rc
Namespace:			e2e-tests-horizontal-pod-autoscaling-4vka2
Labels:				<none>
CreationTimestamp:		Thu, 05 Nov 2015 14:05:29 -0800
Reference:			replicationController/rc/scale
Target CPU utilization:		20%
Current CPU utilization:	<not available>
Min replicas:			1
Max replicas:			5
ReplicationController pods:	1 current / 1 desired
```

**Comment by jlowdermilk** [comment]
cc @brendandburns

**Comment by jlowdermilk** [comment]
cc @fgrzadkowski

**Comment by bgrant0607** [comment]
cc @vishh

**Comment by brendandburns** [comment]
cc @wojtek-t @gmarek 

filip is out on vacation.

**Comment by jlowdermilk** [comment]
HPA, Job, and Ingress tests are now all running (passed in latest run) on http://kubekins.dls.corp.google.com/view/CI%201.1/job/kubernetes-e2e-gce-disruptive-1.1/
