### ISSUE TITLE
Error using NewInCluster() on 1.1.0-alpha1

### ISSUE THREAD

**Issue by jdoliner** [kubernetes/kubernetes#16909]
So I just upgraded to v1.1.0-alpha.1 and one of my pods that's using `NewInCluster()` to get a Kubernetes client is suddenly throwing this error.

```
open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

**Comment by jdoliner** [comment]
Actually nevermind, just tried redeploying on 1.0.6 and had the same problem.
Does anybody have points on why the token would be missing?

**Comment by mwielgus** [comment]
Can you please give more information about your environment/platform?

**Comment by jdoliner** [comment]
Sorry should have included that.

K8s is deployed on Docker as per: https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md. Only thing I've changed is add `--allow-privileged` to the services.

**Comment by jdoliner** [comment]
Just tried this with 1.1.1 and still no luck. I feel like I'm missing something kind of obvious here. Do I need to specify somewhere in the manifest that I want the kubernetes credentials to be visible to the pod or do they just get injected automatically?

**Comment by sandish2222** [comment]
I got the same issue.

https://github.com/kubernetes/contrib/blob/master/Ingress/controllers/nginx-alpha/controller.go  this program runs well in pods（containers） created by kubernetes， but it went wrong when i run it from linux and i got the same error message.

I think the secret token will be generated when you start pods from kubernetes. So if run `NewInCluster()` in a pod, it will work well.

i will try to remove the option `--admission-control ` in the scripted in kube-up. Maybe it works

**Comment by spzala** [comment]
@jdoliner hi Joe, seems like we can close this issue. Did you have chance to try the doc link provided above? Also minikube is now a recommended way to set up local cluster. For any support/help questions, I would recommend to ask it here, https://stackoverflow.com/questions/tagged/kubernetes
Thanks! 

/cc @thockin

**Comment by jdoliner** [comment]
This seems closable. I haven't encountered this in a while and only kind of remember what the error was.

**Comment by spzala** [comment]
Cool. Thanks Joe @jdoliner !!
