### ISSUE TITLE
Tie endpoints into kubectl describe ingress

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#16927]
From https://github.com/kubernetes/kubernetes/pull/16852#issuecomment-154271752

> It would be cool if we could tie this into `describe Ingress` (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe.go#L1000) such that the ingress showed you a list of healthy endpoints for a given backend service. just throwing it out there in case you want to pick it up ;)

cc @bprashanth @feiskyer

**Comment by bprashanth** [comment]
@janetkuo thanks, @feiskyer feel free to assign this bug to me if you don't have time, and I'll get to it when I do

**Comment by feiskyer** [comment]
@janetkuo @bprashanth #17425

**Comment by bgrant0607** [comment]
Looks like this was fixed.
