### ISSUE TITLE
Review process for releases

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16934]
Right now, there's no good way to do a review for releases.  You can't attach a tag to a PR, so the only way to set the tag is to do just a straight push to upstream.  We also just do a straight push of the versionizing commit (that revs versions in `pkg/version/base.go`).

All of this is implemented in dry-run functionality in `cut-official-release.sh` right now, but there's no good paper trail or way to collaborate on review.

It would be much better if we had some sort of review process.

**Comment by spzala** [comment]
@ihmccreery hi Issac, is this still an issue? or do we have a desired review process available now, and we can close it? If not, we probably need to poke related SIG :-) I am helping closing open issues and since this is a very old issue, thought good idea to touch base with you. Thanks!!

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc
