### ISSUE TITLE
“Copying release artifacts to gs://...“ sometimes hangs

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16936]
The step “Copying release artifacts to gs://...“ in `push-official-release` sometimes hangs, maybe when `gcloud` isn't up-to-date?  Presumably it's similar for `push-ci` and `push-dev`.

This needs further investigation.

**Comment by yujuhong** [comment]
Not sure if it's related, but there are known "gsutil -m" hang problem that has not yet been fixed: b/22930057

**Comment by spzala** [comment]
@david-mcmahon @ihmccreery , is this still an issue or can we close it? Since it's around for long time thought good idea to touch base with you. Thanks!
