### ISSUE TITLE
push-official-release versioning issues

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#16937]
Two recently-uncovered issues with `push-[official|dev|ci]-release`:

- [ ] they don't check for a valid CI version until after publication, when trying to do version comparison; they should fail fast if it's trying to push a version that's not valid, instead of uploading and then complaining.
- [ ] they should exit 1 on failure, so that if we failed to push a build, Jenkins goes red.

**Comment by david-mcmahon** [comment]
https://github.com/kubernetes/release/issues/1
