### ISSUE TITLE
We should use YAML tags to set cluster context

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#16935]
So that people can do `kubectl create -f <file>` without having to use `kubectl config use-context ...`

@bgrant0607 @jlowdermilk @smarterclayton

**Comment by brendandburns** [comment]
@kubernetes/kubectl

**Comment by bgrant0607** [comment]
What's the scenario? 

Also, -f works on directories. What if different files specify different contexts?

An alternative would be to make the files executable, with the first line:
```
#!kubectl --context=foo --namespace=bar create -f -
```
```

**Comment by brendandburns** [comment]
@bgrant0607 the scenario is that I have N clusters and I want my config files to care with them which cluster they are intended to update.

I don't really like the "config file is executable" approach since it seems pretty weird to run a config file.

**Comment by bgrant0607** [comment]
I don't know that YAML tags are the best solution. Among other reasons, kubectl also accepts json.

I'd generalize the title to "declaratively specify cluster context".

A number of CLIs do this with a separate file in the same directory. Another option is a flag or env var. The advantages of those approaches is that they wouldn't couple a purely operational concern (which cluster) to potentially reusable config templates.

**Comment by deads2k** [comment]
> A number of CLIs do this with a separate file in the same directory. Another option is a flag or env var. The advantages of those approaches is that they wouldn't couple a purely operational concern (which cluster) to potentially reusable config templates.

Is this different than `KUBECONFIG` or `--config` or `--context=` (for selecting a context in a kubeconfig file?

**Comment by bgrant0607** [comment]
Not likely to happen in kubectl

**Comment by whipit** [comment]
What is the status of this feature request?   I know it is "closed", but it was also added to sig/multicluster.   Not sure what that means.
