### ISSUE TITLE
Service proxy for cluster IP instead of service name

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#16949]
Spark is a special snowflake and its WebUI follow-on links are pretty heavily based on having the cluster IPs routable from the browser. Attached is a sample screenshot of what I mean. As part of the drive in #16517, I have the first page working just fine as part of `kubectl proxy`, but, of course, the links to the workers and application itself don't work, because those are cluster IPs.

If we had a way to get through the service proxy by endpoint spec and directly proxy rather than just proxying an individual service, it would be then be straightforward to write a separate pod that was just a URL rewriter for nginx for all "cluster-like" URLs (handwaving a bit, but assuming you passed the CIDR in, it seems straightforward).

![image](https://cloud.githubusercontent.com/assets/4942464/11008756/948ccce2-8487-11e5-8c0d-c3aba7dd00a4.png)

cc @brendandburns

**Comment by bgrant0607** [comment]
Related: #3481

**Comment by erikschlegel** [comment]
Was anyone able to get the worker proxying to work? I had no success when using the https://github.com/aseigneurin/spark-ui-proxy image.
