### ISSUE TITLE
kube-ui disk usage inconsistently labels filesystems

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#16946]
When viewing the kube-ui dashboard, the ui shows stats and graphs for 4 filesystems. On each successive update of the UI, the actual filesystem being reported on each line may change.

For instance, my `/var/lib/docker` filesystem is usually reported as `Filesystem # 4`, but will occasionally cause wild swings of the graph because it suddenly gets reported as `Filesystem # 2` for a few updates and then returns to being `Filesystem # 4` again.

**Comment by mikedanese** [comment]
Can you open this issue in the kube-ui repo? https://github.com/kubernetes/kube-ui
