### ISSUE TITLE
gcr.io is outdated and will not be supported in a future versions of docker

### ISSUE THREAD

**Issue by onorua** [kubernetes/kubernetes#16968]
Guys, just to let you know, docker 1.9 released, I has pretty interesting message I've discovered by accident:
```
Status: Image is up to date for gcr.io/google_containers/pause:0.8.0
gcr.io/google_containers/pause: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
```
Which means, gcr.io need to be updated or images must be moved to some other registry, otherwise in a couple of months a lot of test environments will be broken around the world, no to tell some production system too.

**Comment by a-robinson** [comment]
Docker is (very quickly) deprecating its original registry protocol/API and has replaced it with a v2 registry. Google Container Registry also supports the new API, and you can find docs on how to use it [here](https://cloud.google.com/container-registry/#using_the_docker_registry_v2_api).

cc @mattmoor in case he wants to add anything or link to better docs.

**Comment by mattmoor** [comment]
That shouldn't even be needed anymore.  Our usual domains now use v2 by default, a docs update is coming.

That said, images must be repushed via v2 to benefit from it.  `pause:0.8.0` was pushed with v1, so it still pulls via v1.  `pause:2.0` was pushed with v2, so you should see v2 pulls.
