### ISSUE TITLE
Unable to schedule pods in mixed version cluster (scheduler=1.0.7, kubelet=1.1.1-beta.1)

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes/kubernetes#16961]
When testing a mixed-version cluster it seems that pods will not be scheduled due to an issue with how multiple node conditions are evaluated.

In this case kubelet=v1.1.1-beta.1 and scheduler (and all other components) are v1.0.7.

It seems the issue is surfaced by adding a second node condition (and was also resolved) here:  https://github.com/kubernetes/kubernetes/commit/a2570926da1b87856351c783c908c255042a9193#diff-53f28720440ab4b589ef2273346cecfcL139

The v1.0.7 code will always evaluate the status of the last condition in the list (now "OutOfDisk=False"), when it should be checking the "Ready" condition. So now, "Ready" always evaluates to "False".

Then pods fail to schedule with "no nodes available to schedule pods", although `kubectl get nodes` reports nodes as ready.

Not sure if this type of mixed-version use is within the bounds of reasonable, but I'll submit a simple (backported) fix from the above commit in case.

**Comment by zmerlynn** [comment]
cc @ihmccreery

**Comment by ihmccreery** [comment]
[Our upgrades policy](https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md#upgrades) is somewhat ambiguous, but more or less suggests that the master version, (of which the scheduler is a part,) should be ahead of the Kubelet versions at all times.  I'd like to suggest that we make it clearer that masters should always be ahead of Kubelets, and close this issue as unsupported, but I'm willing to hear other arguments.  I just don't think it will be reasonable to attempt to support bidirectional version skew—that sounds like too much to me.

**Comment by ihmccreery** [comment]
cc @quinton-hoole @mikedanese

**Comment by a-robinson** [comment]
Agreed on not supporting bidirectional version skew

**Comment by ihmccreery** [comment]
I'm assigning myself to clarify the documentation that we don't support bidirectional version skew.

**Comment by quinton-hoole** [comment]
@ihmccreery @a-robinson Agree on not supporting bidirectional version skews, unless someone comes up with a legitimate use case for that.  My preference would be to eliminate version skew to the maximum extent possible (e.g. mandate a strict ordering of master upgrade before node upgrade, and restrict version skew in that case to a maximum of one minor version difference, purely to allow asynchronous upgrades).   But there are currently legitimate use cases (e.g. GKE), where we need to support node updates that lag many versions behind master.
  
@bgrant0607, @brendandburns  FYI.

**Comment by aaronlevy** [comment]
CoreOS currently ships the Kubelet as part of the OS image, and the scenario I was testing against is an updated kubelet (1.1) shipping with a new OS version, while the master components remain unchanged.

If this type of use case isn't supported, it means an automated global update of the kubelet in the OS image requires a manual step by all CoreOS/Kubernetes users. For example, all users would need to have updated their masters prior to the OS updating with a newer kubelet (and this is not possible to guarantee). Alternatively, it would mean CoreOS couldn't ship updates to the kubelet as part of the OS image.

**Comment by bgrant0607** [comment]
Alex mentioned this to me at Kubecon. 

Does CoreOS have continuous version-skew testing in this direction (node first, then master)?

**Comment by aaronlevy** [comment]
In this case the version skew testing was done manually, but this is something we would add to test kubelet updates in the OS releases.

**Comment by philips** [comment]
I think a very reasonable use case for version skew is simply being able to roll back a cluster upgrade midstream. Imagine I upgrade to kubernetes 1.1 and then start upgrading my kubelets. Then I find that kubernetes 1.1 control plane has a bug/performance problem/etc and so I rollback to kubernetes 1.0 control plane until I can solve the issue in 1.1.

I agree we should minimize version skew but I think it is fairly practical to allow for rollback and compatibility on both sides of the system.

**Comment by quinton-hoole** [comment]
Thanks @aaronlevy @philips - yes, those are exactly the types of legitimate use cases that I was hoping to illicit.  I think that we need to support this.

**Comment by aaronlevy** [comment]
I'd be happy to try to contribute a fix for this specific issue, but I was unsure if this is something that would be considered upstream.

Given that it would currently require a fix in the kubelet itself -- is this something that might be reasonable? One possibility might be retrieving the master component versions prior to building the node status payload?

**Comment by quinton-hoole** [comment]
@aaronlevy Yes, contributing a fix upstream would be the ideal solution.  What I suggest is that you start with a short problem statement and design proposal document (in the form of a PR).  That way community members will have the opportunity to weigh in on alternative approaches (in the form of PR review comments) before you expend effort on a concrete implementation, that might get shot down for design/approach rather than implementation reasons.

**Comment by ihmccreery** [comment]
Opened #17184 for the more general issue of version-skew between masters and Kubelets.  Assigning this specific issue, (the resolution of the 1.0-1.1 problem,) to @quinton-hoole.

**Comment by bgrant0607** [comment]
What workaround are we planning? Just always put the Ready condition last? I'd prefer that to version-specific behavior.
