### ISSUE TITLE
API server should return Date header?

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#16976]
To allow clients to at least understand the time frame the master operates in.  Also, infrastructure clients pushing updates that include dates should also include a Date header on their writes.  Client clocks (regular users) are often unsynchronized, and it's hard to present meaningful dates when the client diverges by minutes from the server.

**Comment by bgrant0607** [comment]
SGTM

**Comment by sttts** [comment]
Isn't there a date header by default with Golang's `net.http`? I also checked a local kube and GKE. Both return a date header.

**Comment by smarterclayton** [comment]
Yeah, we have the date header.  This is probably fine for now.
