### ISSUE TITLE
io.SavePodToFile does not belong in pkg/util/io

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#16970]
That's a generic package - if we need a utility for "write pod to file" it should be in a sub package of volumes (if it's only used there) or a sub package of api.  It's also the wrong signature - it shouldn't assume anything about the codec its running under.

**Comment by kargakis** [comment]
SavePodToFile is not used anymore but SavePodToFile seems to be used by the volume recycler so @kubernetes/sig-storage-misc

**Comment by kargakis** [comment]
correction: LoadPodFromFile is used
