### ISSUE TITLE
GCE client flakes on oauth

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#16985]
The GCE client flakes on oauth from time to time with:

```
https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins/zones/us-central1-f/instanceGroups?alt=json: oauth2/google: can't get a token from the metadata service; not running on GCE
```

Which is weird, because the client should really refresh the token transparently, and the "Not on GCE" message looks suspicious. The controller creates the client in pretty much the same way the Kubernetes cloudprovider module does (https://github.com/kubernetes/contrib/blob/master/Ingress/controllers/gce/cluster_manager.go#L147), so this looks like a general problem?

**Comment by bprashanth** [comment]
kubernetes-e2e-gce-disruptive-1.1 # 101 L7 test for example failure

**Comment by bprashanth** [comment]
@kubernetes/goog-gke in case anyone knows of a recent fix I should rev the godep in contrib to pick up

**Comment by a-robinson** [comment]
For what it's worth, I believe that's the error message the google api client gives when it can't reach the local metadata server to get an access token.

**Comment by a-robinson** [comment]
So the problem is flakiness hitting the metadata server, either due to the DNS lookup for metadata.google.internal or due to the metadata server itself. Both of which suggest an issue with either GCE itself or with node networking.

**Comment by a-robinson** [comment]
I'm not aware of any recent fixes, but these are the relevant chunks of the client:
https://github.com/golang/oauth2/blob/master/google/google.go#L118
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/compute/metadata/metadata.go#L155

**Comment by bprashanth** [comment]
Hmm, I feel like retrying should fix connectivity flakes (which I believe the controller does, but perhaps I'm dropping it).

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/pull/16979 will help clear confusion around retries

**Comment by bprashanth** [comment]
This should only happen when this test runs right after the reboot test. It's a race of resolving the metadataserver and the loadbalancer pod creating the client. The easiest solution does seems to be a liveness probe that wacks the pod, though really I just want control over the client so I can recerte it at will (I mean, just do this again: https://github.com/kubernetes/kubernetes/pull/14574).
