### ISSUE TITLE
Add docs to setup Couchbase cluster on Kubernetes

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#16989]
This would be a great addition to http://kubernetes.io/v1.0/deploy-clusters.html.

Am happy to take ownership of this bug and will send a PR. Can somebody assign it to me?

**Comment by paralin** [comment]
I'd also be interested in this, if you'd like I can work with you to test / debug / write the example.

**Comment by arun-gupta** [comment]
@paralin excellent, sounds good.

I'm busy at Devoxx this week but will share my outline early next week.

**Comment by paralin** [comment]
What about just integrating this? https://github.com/couchbase/kubernetes

**Comment by arun-gupta** [comment]
@paralin It has too much details and require extensive setup. I'm discussing this with @tleyden on how to simplify this and will send a PR.

**Comment by paralin** [comment]
@arun-gupta @tleyden Any updates on this? We're interested in possibly using Couchbase to scale with Kubernetes for a project.

**Comment by arun-gupta** [comment]
@paralin early work at https://github.com/javaee-samples/docker-java/blob/master/chapters/docker-kubernetes.adoc#couchbase-cluster-and-persistent-volumes will work more scaling cluster this week and then create docs.

**Comment by arun-gupta** [comment]
This is for @kubernetes/sig-docs-maintainers

**Comment by ahmetb** [comment]
@arun-gupta We decided to maintain a minimum set of examples in kubernetes/examples repository. We have a Cassandra example there to highlight the StatefulSet and PersistentVolume features, and we're not planning to add more examples overlapping with this. I assume Couchbase falls in the same category.

I see you [blogged about this](http://blog.kubernetes.io/2016/08/create-couchbase-cluster-using-kubernetes.html) on K8s blog. We are encouraging people to create repositories on GitHub to document deploying 3rd party software (like databases) on Kubernetes. (You can find more about the [examples/ directory proposal here](https://docs.google.com/document/d/15eRNrOtofhl1tFyXgZYw3pV4Z9S4PF1TU1iejGnv1f4/edit#heading=h.zhgesvwrrxvt). 

Would you be willing to close this issue and create a repo under Couchbase’s org (or your own personal account) that describes how to set up a Couchbase cluster? Then you can link to there from the blog.kubernetes.io post as well and that repo would be the to-go place.

**Comment by arun-gupta** [comment]
@ahmetb Happy to close as do not plan to blog further about this topic at this time.
