### ISSUE TITLE
Name+label+selector scoping for configuration composition

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1698]
Let's say one has a configuration comprised of a set of objects (e.g., a simple service, replication controller, and template, as in #1695). Within that configuration, objects may refer to each other by object reference (as with replication controller to template, as of v1beta3) and/or by label selector (as with service and replication controller to pods generated from the pod template).

If one wants to create multiple instances of that configuration, such as for dev and prod deployments (aka horizontal composition) or to embed in composite macro-services (aka hierarchical composition), the names must be uniquified and the label selectors must be scoped to just one instance of the configuration, by adding deployment-specific labels and label selector requirements (e.g., env=dev, macroservice=coolapp). The uniquifiying name suffixes could be deterministically generated by hashing the deployment-specific labels.

This could be done as a transformation pass, as described in #1694. The advantage of that is that the generated objects would be fully explicit. However, note that subsequent introspection and management operations will need to operate on the extended names and label sets. That could work for operations (e.g., updates) driven off of configuration data.

The insertions could also be done in the client library invoked by kubectl, not just for creation but also for update, get, etc., or on the server. The latter would have the flavor of uniquified names, as needed for bulk pod creation (#170). 

My preference is to create a single-purpose transformation pass for this. It would need to be possible to identify all names, references, label sets, and label selectors that must be uniquified/extended. In v1beta3 we hopefully will have enough API uniformity to do that automatically based on field names. If not, we could also use knowledge of the specific types and/or annotations (e.g., YAML directives) to identify them.

In general, I think we'll want to make introspection and management operations more user-friendly by supporting label selectors for all operations.

The alternative to a domain-specific pass like this would be to require users to use a generic templating mechanism, such as [Mustache](http://mustache.github.io/), but the scoping mechanism would need to be reimplemented in every templating language, and it would also make configurations more complex.

**Comment by bgrant0607** [comment]
My proposal in #3233 would be a good starting point:

We should also add command-line flags for a curated set of labels, such as `--app=foo`, `--tier={fe,cache,be,db}`, `--uservice=redis`, `--env={dev,test,prod}`, `--stage={canary,final}`, `--track={hourly,daily,weekly}`, `--release=0.4.3c2`. Exact ones TBD. We could allow arbitrary values -- the keys are important.  The actual label keys would be namespaced with `kubectl.kubernetes.io/`. 

A general `--labels=` command-line flag to kubectl could also apply the specified labels to all of the objects.

The trickiest part is updating selectors in services and replication controllers. At least for now, that probably requires understanding of those objects. We can figure out how to make it work for plugins later.

**Comment by smarterclayton** [comment]
Adding the comment here so I don't forget: one option for setting selectors on services and replication controllers is to have a way to have them default to the labels on the service or RC (exact).  The problem would be indicating you want "all pods" which we don't have a concrete implementation of in the query selector syntax yet, until the advanced selector syntax is part of the api.

**Comment by bgrant0607** [comment]
@smarterclayton I agree. I like that it would remove the need for detailed schema knowledge from the client.

What do you mean by "all pods"?

**Comment by smarterclayton** [comment]
Sorry, *global* selector (service that includes all pods in a namespace).

**Comment by bgrant0607** [comment]
Namespaces seem ideally suited as a scoping mechanism, since they bound the scope of both names and label selectors. I was already thinking that users would create different namespaces for dev, test, staging, and production environments, as well as for different teams. What consequences would there be if users launched every app/tier/microservice into a different namespace?

One consequence would be that users would be even more likely to need to deal with multiple namespaces. At minimum, we'd need to change some of the kubectl tooling to make this easier. Would labels be sufficient to organize groups of namespaces, or would we need to add another level to the hierarchy? What would need to be common amongst multiple namespaces? Service accounts and security policies probably?

The service environment variables wouldn't be of much use, then. DNS would be able to bridge namespaces, but I'm guessing we'd need to create an explicit mechanism for cross-namespace visibility, since a number of people are working on network isolation.

cc @erictune @derekwaynecarr @smarterclayton @ghodss @deads2k @liggitt

**Comment by smarterclayton** [comment]
Today, we encourage deploying units of code into individual namespaces -
sometimes one, maybe multiple, rarely many (except when it's a a single
administrator).

We've been looking at how we can use namespaces in workflow - such that
flow between namespaces would be environmental (in many cases).  We'd like
to use labels to organize and group and identify those namespaces, with
possibly a higher level object or tool to help bring some intelligence
there.  Although ideally the label selectors for namespaces would identify
them correctly.

I think there are advantages to having service accounts per namespace -
with the policy model we went with, we think we can do group based access
control across namespaces as effectively as if we had higher level policies
(cluster scoped resources like policy can be referenced in a namespace,
groups can be ad-hoc).  So in the short term we hadn't yet seen the need to
have policies that cross namespaces necessarily (since different
environments are also likely to have different policy).

We do however believe that some sort of multi-cluster authentication and
policy is relevant for scale out - so want to understand how we would apply
that.

We believe that we need a way to identify cross namespace relationships for
services.  I haven't yet seen the proposal for services from the folks at
Red Hat working on network isolation per namespace, but there either has to
be inbound rules (I expose this service to you, but it doesn't override
your changes) or mutual rules (i expose this service to you and you accept
it).  Lots of good discussion to have here.  We'd like to have DNS across
namespaces work if you aren't isolated, and not work if you are.

@eparis can talk about the services + network isolation I believe.


On Thu, Jul 23, 2015 at 12:51 PM, Brian Grant <notifications@github.com>
wrote:

> Namespaces seem ideally suited as a scoping mechanism, since they bound
> the scope of both names and label selectors. I was already thinking that
> users would create different namespaces for dev, test, staging, and
> production environments, as well as for different teams. What consequences
> would there be if users launched every app/tier/microservice into a
> different namespace?
>
> One consequence would be that users would be even more likely to need to
> deal with multiple namespaces. At minimum, we'd need to change some of the
> kubectl tooling to make this easier. Would labels be sufficient to organize
> groups of namespaces, or would we need to add another level to the
> hierarchy? What would need to be common amongst multiple namespaces?
> Service accounts and security policies probably?
>
> The service environment variables wouldn't be of much use, then. DNS would
> be able to bridge namespaces, but I'm guessing we'd need to create an
> explicit mechanism for cross-namespace visibility, since a number of people
> are working on network isolation.
>
> cc @erictune <https://github.com/erictune> @derekwaynecarr
> <https://github.com/derekwaynecarr> @smarterclayton
> <https://github.com/smarterclayton> @ghodss <https://github.com/ghodss>
> @deads2k <https://github.com/deads2k> @liggitt
> <https://github.com/liggitt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/1698#issuecomment-124165810>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
As expected, resource names and label values are among the most commonly templated fields:
https://github.com/luciddreamz/library/blob/master/official/mysql/mysql-persistent-template.json
https://github.com/kubernetes/charts/blob/master/stable/mariadb/templates/deployment.yaml

**Comment by bgrant0607** [comment]
Identifying embedded selectors, labels in inline pod templates, and object references and names is the most challenging aspect of automatic name/label customization. We could annotate those fields in types.go and in OpenAPI with enough information to determine whether they should be updated in a given scenario. For example, we could specify that PodSpec.ServiceAccountName is a local (i.e., same namespace) reference to a Service Account of that name.

**Comment by bgrant0607** [comment]
Selector and reference info: #3676, #22675

How this fits into the bigger picture: https://goo.gl/T66ZcD

**Comment by bgrant0607** [comment]
@kubernetes/sig-apps-feature-requests @kubernetes/sig-cli-feature-requests

**Comment by bgrant0607** [comment]
Closing this in favor of other issues.
/close
