### ISSUE TITLE
enable automatic generation of service account tokens in hyperkube

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#16987]
Copied from [#16965(comment)](https://github.com/kubernetes/kubernetes/issues/16965#issuecomment-154789717)
>@dalanlan Should we open a new issue for enabling secret functionality by default in hyperkube?

>IMO, secrets and serviceAccounts are quite a big part of k8s, and the k8s-in-docker setup will suffer a lot if these aren't default.

It did bother a lot (ref #13424) w/o secrets being generated automatically. If no one goes against it, i could send a pr for this.
/cc @luxas

**Comment by luxas** [comment]
@dalanlan Yes, I think we should try at least.

>Alternatives:
>  -  Use emptyDir. apiserver self-signs the certs and controller-manager uses them. In-memory.
>  -  Use an empty hostPath. apiserver self-signs the certs and controller-manager uses them. Stored on the master's filesystem.
>  -  Use a prepopulated dir with hostPath (or another volume plugin). Specify apiserver and 'controller-manager` flags which points to already-made certs.

If we do this, we have to discuss which alternative should be default. 
I lean towards `emptyDir` as default and then some instructions how to customize it.
That is the easiest solution and fixes the problem without adding more complexity.

Who knows about which `--admission-control` options should be passed? 
It defaults to `AlwaysAdmit`, so one option is `AlwaysAdmit, ServiceAccount`

A new version of the `hyperkube` image should also be built. 
Before this patch could be merged, a `v1.2.0-alpha.3` hyperkube image must be pushed to `gcr.io`.
Just now `curl -O https://storage.googleapis.com/kubernetes-release/release/v1.2.0-alpha.3/bin/linux/amd64/hyperkube` doesn't exist.
Ref: [Makefile](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/Makefile)

Here is one alternative: https://github.com/luxas/kubernetes/blob/16987-default-serviceaccount-secret-hyperkube/cluster/images/hyperkube/master-multi.json

**Comment by dalanlan** [comment]
Speaking of `admission control', i believe it would be just fine to follow 'local-up-cluster.sh' w/ `--admission-control=NamespaceLifecycle,SecurityContextDeny,LimitRanger,ServiceAccount,ResourceQuota`, (deprecate `NamespaceAutoProvision` in favor of `NamespaceLifecycle` though)

**Comment by dalanlan** [comment]
OTOH, using emptyDir w/ self-signed key file would be an easy solution. Yet there could be race condition in some way. 
Since we cannot guarantee the upstart order of the container within a pod, this could happen: when `controller-manager` loads the required key-file, `api-server` has not well prepared by that time. 
This doesn't happen a lot ('cause in most cases, container[0] would be raised before container[1], which does seem like in order), yet when it does, it's hard to trace.

**Comment by luxas** [comment]
Yes, that race condition is unusual, but unfortunately possible. 
What happens if the certs doesn't exist when `controller-manager` starts? 
Does it fail or does it try again later?

Should I switch the position of `controller-manager` (currently container[0]) and `apiserver`?
I'll update the `--admission-control`

**Comment by pmorie** [comment]
This is really about enabling automatic generation of service account tokens, right?

**Comment by luxas** [comment]
@pmorie Yes. For containerized kubelet.
1. So serviceAccounts that are created gets a `secret` associated with it. Especially `default`
2. So `apiserver` tells `kubelet` to mount the `/var/run/secrets/kubernetes.io` that containers use.

Do you have any thoughs about the race condition?
See the file above.

**Comment by dalanlan** [comment]
> What happens if the certs doesn't exist when controller-manager starts? 
Does it fail or does it try again later?

My guess is that it will fail. Or we won't have #12588 then.

> Should I switch the position of controller-manager (currently container[0]) and apiserver?

That won't make a guarantee unfortunately, since kubelet does not ensure the upstart order of the containers within a pod itself.

**Comment by dalanlan** [comment]
Given a second thought, i bet it won't be easy for this currently. 
We cannot use a `hostPath` in the building process anyway, and `emptyDir` is not a good choice. I'm going to close it, unless you guys think otherwise :-)

**Comment by luxas** [comment]
@dalanlan Can you give it a little more time? This would be really great to have.
I got this while starting the pod.
```
I1109 05:30:32.278745    8821 manager.go:2048] Back-off 10s restarting failed container=controller-manager pod=k8s-master-192.168.1.69_kube-system
```

This sounds like the race condition, but `kubelet` solves this by restarting some secs later. 
Is this true? Will check the source.

**Comment by luxas** [comment]
That event happens twice, 0.2 s between events:
```
I1109 06:04:23.827647   11751 manager.go:2048] Back-off 10s restarting failed container=controller-manager pod=k8s-master-192.168.1.69_kube-system
I1109 06:04:24.007972   11751 manager.go:2048] Back-off 10s restarting failed container=controller-manager pod=k8s-master-192.168.1.69_kube-system
```

However, `controller-manager` works fine after that.

**Comment by dalanlan** [comment]
That could be possible since `kubelet` changes its way to sync pods with time. We'd better be cautious.

@yujuhong Could you kindly clarify this? Say we have a static pod, within which containers A (`controller manager)` is expected to use a file as its upstart flag that is generated by container B(`apiserver`) via `emptyDir`. What would happen when there is a [race condition](https://github.com/kubernetes/kubernetes/issues/16987#issuecomment-154810828)? Does it exit directly or kubelet would try it  again?

**Comment by yujuhong** [comment]
@dalanlan, if a container failed to start, kubelet would set a exponential backoff timer for the specific container. The container would only be restarted again when the backoff period is met (e.g, in this case, it's 10 second). Before the backoff period expires, if kubelet tries to sync the pod, it would discover that the requirement is not met, records an event (as seen in https://github.com/kubernetes/kubernetes/issues/16987#issuecomment-154954939), and does nothing.

**Comment by luxas** [comment]
@yujuhong So, may we use it?
AFAIU Kubelet just waits 10 secs, restarts the container, and it's OK. 
For me at least, it worked fine.

However I didn't really get the last sentence:
> Before the backoff period expires, if kubelet tries to sync the pod, it would discover that the requirement is not met, records an event (as seen in #16987 (comment)), **and does nothing.**

**Comment by dalanlan** [comment]
@yujuhong Thanks:-)
That said, `kubelet` would take care of race condition itself and we won't suffer #12588 theoretically.
If that's the case, `emptyDir` fits this scenario.

**Comment by yujuhong** [comment]
> That said, kubelet would take care of race condition itself and we won't suffer #12588 theoretically.
> If that's the case, emptyDir fits this scenario.

Unfortunately, there is no notion to define container startup ordering in k8s, so kubelet can't really do anything :-(
On the other hand, I am unsure this level of coordination between containers should be handled by kubelet (i.e., handling depenencies). Containers should be able to coordinate on their own, either through shared file or other communication channels.

**Comment by luxas** [comment]
@yujuhong I think it's (for this case) OK for kubelet just to restart the container. 
It will work fine after the restart.

@dalanlan However, if we want to avoid this restart we may do something like this:
```
"/bin/sh",
"-c",
"while [ ! -f /var/run/kubernetes/apiserver.crt ]; do sleep 1; done;"
"exec /hyperkube",
  "controller-manager",
  "--master=127.0.0.1:8080",
  "--service-account-private-key-file=/var/run/kubernetes/apiserver.key",
  "--root-ca-file=/var/run/kubernetes/apiserver.crt",
  "--v=2"
```

Yeah, I know this is very hackish, but a such wait for the file would not result in a restart of the container.

But, this makes `sh` or `bash` a dependency, and even though `hyperkube` is built on `debian` today and is dynamically built, it may change in the future.

**Comment by dalanlan** [comment]
@yujuhong What's bothering me is that I cannot really catch the real reason for this potential race condition, even though I'm fully aware that `kubelet` doesn't either guarantee the upstart order nor handle container dependencies. 
Say `api-server` is up expectedly while `controller-manager` fails 'cause lack of the key files. In this case, `kubelet` would sync pod continuously and even restart `controller-manager` after backoff period. Quite clean, right? 

@luxas Seems that it's a little too much IMO :-/

**Comment by luxas** [comment]
@dalanlan Yes, I just said it might be possible, not proposed as an option for this file :)

**Comment by yujuhong** [comment]
> Say api-server is up expectedly while controller-manager fails 'cause lack of the key files. In this case, kubelet would sync pod continuously and even restart controller-manager container after backoff period. Quite clean, right?

@dalanlan, how is this different from today's behavior? I may have missed something...

**Comment by brendandburns** [comment]
@dalanlan I think your analysis is correct, and also the desired behavior.

In a system with health checks and restart, dying if your preconditions aren't met, is actually the robust, correct behavior.  Trust the kubelet to continue to restart you until your pre-conditions are met.

**Comment by dalanlan** [comment]
@brendandburns theoretically, yes. That said,  #12588 is odd indeed and unexpected. 

Based on this assumption, `emptyDir` is good to go in this case(again). 
Thank you for the clarify.

**Comment by luxas** [comment]
@dalanlan So, should I create the PR of this file then (and of course `master.json`)? https://github.com/luxas/kubernetes/blob/16987-default-serviceaccount-secret-hyperkube/cluster/images/hyperkube/master-multi.json

**Comment by dalanlan** [comment]
Feel free to. You deserve this credit :)

**Comment by dalanlan** [comment]
Also `master.json` please.

**Comment by luxas** [comment]
The PR is here: #17213

**Comment by luxas** [comment]
This is fixed now @dalanlan @pmorie @davidopp, so this can be closed.
