### ISSUE TITLE
Kubernetes using Docker instruction needs to be updated

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#16990]
http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html uses boot2docker and instead should use Docker Machine and Compose. A sample Docker Compose file is available at:

https://github.com/arun-gupta/docker-images/blob/master/kubernetes/docker-compose.yml

**Comment by lachie83** [comment]
I'm working on this at the moment and will take a stab at this.

**Comment by spzala** [comment]
@arun-gupta @lachie83 Hello, is this issue still valid? I don't see docker.html or docker-compose.yml while taking a high level look so wanted to touch base. If it's not a valid issue now and can be closed, then please close it. Thanks!

**Comment by arun-gupta** [comment]
@spzala This is a dated issue and no longer relevant. Closing.

**Comment by spzala** [comment]
@arun-gupta Thanks Arun!!
