### ISSUE TITLE
Clean up copies of individual resources in examples/guestbook

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#16998]
Follow-up #14256. See https://github.com/kubernetes/kubernetes/pull/14256#issuecomment-154583601

cc @linzichang @bgrant0607

**Comment by paralin** [comment]
I can work on this if needed

**Comment by janetkuo** [comment]
@paralin thanks!

**Comment by paralin** [comment]
@janetkuo What needs to be done here, exactly? I've read through all the test code for the guestbooks and it seems to be in order, even with the patch. Are there resources here that need to be removed? Do the old tests for this need to be taken out?

**Comment by janetkuo** [comment]
@paralin since those guestbook example files are still required in tests (xxx_test.go and hack/test-cmd.sh), please move the files required for testing to hack/testdata/ and change the path accordingly. Note that those files may be referenced in .md files and should be fixed too.

**Comment by paralin** [comment]
@janetkuo They're referenced a lot in the readme: https://github.com/kubernetes/kubernetes/blame/master/examples/guestbook/README.md#L253

Should I change those references to all-in-one then?

**Comment by janetkuo** [comment]
- examples/guestbook/all-in-one/ should only have guestbook-all-in-one.yaml
- examples/guestbook/ should have redis-master-controller.yaml, redis-master-service.yaml, redis-slave.yaml, and frontend.yaml (since they're required in examples/guestbook/README.md)
- other files under examples/guestbook/ should be removed or moved to hack/testdata/ if used in tests. 
- .md files, including examples/guestbook/README.md should be modified accordingly

**Comment by paralin** [comment]
@janetkuo A lot of the test commands will add the entire directory using -f. Because of this I think it's best to put all of the old files into test-resources to make sure the tests are using the same files they were before. I'm going to go ahead with this because I've tried a few other options (instead of adding a directory, add the all-in-one and update the expected outputs, and also just add the directory - doesn't work).

**Comment by paralin** [comment]
This line here just doesn't make any sense:

**Comment by janetkuo** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/replace_test.go#L150 uses a fake HTTP client so it doesn't actually reference the files in examples/guestbook. 

-f with a directory creates everything in that directory. If "examples/guestbook" (the whole directory) is referenced in tests, you can either keep it as is (since after you moved the files as I suggested in https://github.com/kubernetes/kubernetes/issues/16998#issuecomment-155548056, the same set of resources are referenced), or move those files to hack/testdata/<new folder>. (I'd prefer the later since test data should be separate from examples imo.)

**Comment by bgrant0607** [comment]
I want the examples test to be able to test the multiple-resource files.

**Comment by paralin** [comment]
That's going to require modifying the example_test.go I think.

**Comment by janetkuo** [comment]
To be more clear, 
- The following single resource files should be removed from `examples/guestbook`:
  - `frontend-controller.yaml`
  - `frontend-service.yaml`
  - `redis-slave-controller.yaml`
  - `redis-slave-service.yaml`
- Some tests (*excluding* example tests), such as `test-cmd.sh` or `apply_test.go`, use the single resource example files that need to be removed from `examples/guestbook`. So we won't delete those single resource files but move them to `hack/testdata/guestbook` instead. 
- Example tests (`examples/examples_test.go`) should test *all* files under `examples/`. 
- Example tests need to be fixed to be able to test example files with multiple resources. 

Already synced up with @bgrant0607.

**Comment by kargakis** [comment]
@ahmetb

**Comment by bgrant0607** [comment]
Examples have been moved out of this repo
