### ISSUE TITLE
Separate the pod template from replicationController

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#170]
We should separate the pod template from replicationController, to make it possible to create pods from template without replicationController (e.g., for cron jobs, for deferred execution using hooks). This would also make updates cleaner.

**Comment by smarterclayton** [comment]
Will start some of this next week.  I anticipate the changes to the RESTStorage interface will be the most impactful (to allow additional data to flow through that API), and I want to have a discussion on how we want RESTStorage to evolve w.r.t. the generic registry and ideal swagger support.

**Comment by smarterclayton** [comment]
In order to make pod templates work in our current context, we need to discuss how references will work between RCs.  In the short term, we can choose as a simplifying assumption that no cross-namespace reference is allowed betweens RCs and PTs.  

Even that limit doesn't ensure that the user who created the RC is allowed to see that PT (if policy is truly flexible within a namespace).  Is there a use case for a client who can create RC's, but not see PT's by name?  Or can we relegate that to "things we don't support"?  

The original proposal called out attaching policy (effectively) to a pod template in terms of who can use that PT.  It hasn't really been reconciled with the evolution of the authz/n proposals (the idea that within a namespace, there could be even more granular policy).  The problem with that policy is that it exists at the top of the API stack, not the bottom, so if the Pod API wishes to enforce "can the user who is invoking this actionr see this pod via policy", they have to go back up to the top of the API stack (authn -> authz -> route -> rest handler) and back down, OR they have to have access to directly invoke the policy (potentially bypassing additional checks in the API stack).

Choice 1:

* Make access to create a pod from a pod template a decision of policy, not the pod template
* Make access to create a pod from a pod template a decision of the pod template, not the policy
* Both??

Ancillary question: is policy an API endpoint that internal API components should be entitled to call in order to check permissions, or should our APIs make calls via a client interface that potentially go out through the stack.

In the short term, we can choose to not impose any access control on checks within the namespace, and not to define any permission behavior on the pod template itself.

**Comment by bgrant0607** [comment]
@smarterclayton Still digesting your comment (found it changed since the email update). Short summary: Yes, for now we should constrain to visibility within the same namespace and punt on finer-grain policies.

**Comment by bgrant0607** [comment]
Vaguely, the policy I'd like to be able to express is: allow the replication controller manager (running as some particular user/namespace) the ability to create pods using the pod templates matching this label selector (perhaps matching all pod templates by default).

**Comment by bgrant0607** [comment]
Creation of the pod template should be handled as a regular REST resource. I think there are 2 options that make sense: 
1. `POST /podtemplates`.
2. `POST /pods`, with a field in the pod indicating that it should not be scheduled (say, `suspend`) -- we want that functionality for other reasons

(2) is appealing as a general pattern. In that case, that suggests to me a special verb on the object: `POST /pods/footemplate/clone&suspend=false`.

This would make pod templates not a special thing, which I like.

**Comment by bgrant0607** [comment]
ACK comment on URL parameters. Another motivation for a general solution to PATCH/PATCH-like behavior.

**Comment by bgrant0607** [comment]
I also want to finalize the form of cross-object references. I'm thinking more and more that we should use partial URLs, not the existing `ObjectReference` type. They're more RESTful, more meta-programmable, more forward-compatible with API changes, and more consistent with other API features/proposals, such as polymorphic verbs like resize (and clone). This is perhaps a little dangerous, since it presupposes that deep introspection of the URL structure is not required.

**Comment by smarterclayton** [comment]
One reason why URLs are more painful is if you want a template to have namespace local references.  With ObjectReference it's:

```
Object {
  Name: "something"
  // no namespace set
}
```

With a URL it's

```
/api/v1beta1/ns/???/type/name
```

URL's don't seem to devolve to local references gracefully.  Can be solved by a namespace rescoper, but the object certainly doesn't look normal (URLs are effectively opaque outside of your codebase).

----- Original Message -----

**Comment by bgrant0607** [comment]
The same applies to version -- I'd assume by default it would make sense to use the same API version. Would URL suffixes work?
```
/api/v1beta3/ns/myns/pods/foo
/ns/myns/pods/foo
/pods/foo
```
This definitely breaks down URL opacity, but maybe that's ok, for at least URLs with recognized structure. We could also do a DNS-like resolution (at least conceptually) where we first try the URL, then prepend namespace, then prepend api verison.

**Comment by bgrant0607** [comment]
I'd be fine with sticking with ObjectReference for now in order to get more experience with it. We could potentially add a Link field to it in the future to experiment with the URL approach, also.

**Comment by smarterclayton** [comment]
I feel like URLs are more often the thing an API returns, vs things a user specifies (for precisely this reason).  APIVersion is interesting because it's going to change, so you don't want to store that internally (so you don't have to migrate your Foo's when all their BarRefs drop support for v1betaX).  Every enterprise system I've seen that stored URLs ended up having to do a URL mapping table to handle server renames as well (not that we would store those URLs).

Maybe we should focus on refs as URIs in effective status to simplify reading (traversing):

```
{
  "kind": "ReplicationController",
  "spec": {
    "templateRef": {
      "name": "foo"
    }
  },
  "status": {
    "templateLink": "https//server.com:9080/api/v1beta1/ns/myns/pods/foo"
  }
}
```

Client can either apply the template ref arguments themselves or follow the templateLink.  That's pretty hateos to me.

----- Original Message -----

**Comment by bgrant0607** [comment]
I like it.

**Comment by bgrant0607** [comment]
Note that the clone approach would make it easy to do 2/3 of what I described here: https://github.com/GoogleCloudPlatform/kubernetes/pull/3233/files#r22573202

Creating objects from other objects: pods from pods, replication controllers from pods.

**Comment by bgrant0607** [comment]
For those not familiar with it: http://en.wikipedia.org/wiki/Prototype-based_programming

**Comment by smarterclayton** [comment]
Regarding 'clone' and https://github.com/GoogleCloudPlatform/kubernetes/issues/170#issuecomment-69817935, if we still wanted to have access control limitations on who can create from a pod templates that would be more difficult (the pod would have to have that field, as opposed to a separate pod template object).  I assume the security consideration is still important, although we have not talked about it in a while.  Having it be a separate resource 'podtemplates' with a distinct verb for instantiate is the easiest to secure in the current model (because you can limit replication controller manager to reading pod templates and using the 'clone' / 'instantiate' verb or separate resource name to limit them).

**Comment by bgrant0607** [comment]
Do we plan to put the access control rules in the objects themselves? I would have thought that would be separate ABAC rules.

**Comment by smarterclayton** [comment]
It was in the original proposal, however I think our discussions have lead us away from it.  It does encourage us to model pod creation via template in a way that can be distinguished clearly from POST /pods.

**Comment by bgrant0607** [comment]
Continuing from https://github.com/GoogleCloudPlatform/kubernetes/issues/2726#issuecomment-73144617:

Using [Content-Location](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) is an interesting idea. Would we need an explicit `clone` resource, then? One could just POST with Content-Location pointed at an existing object. I guess if we want to be able to override any fields (which is tricky security-wise), we'd need somewhere to specify that.

**Comment by smarterclayton** [comment]
Yeah - I think that's interesting.  I like that better than needing a resource in the short term - at worst we come along later and create a resource.  Will have to think about how we apply abac to that.

**Comment by bgrant0607** [comment]
More concretely, I think this would work by allowing creation of inert objects using either a metadata or spec field, which would default to enabled (that is, normal, active objects). This bit would be flippable via the control subresource discussed in #2726. The object would have to set generateName. The replication controller would then create new pods by POSTing to /pods with Content-Location, and would have to then enable the new pods via the control subresource. 

I agree that applying abac to that sounds tricky.

My understanding of the alternative:

POST to a subresource, say `/pods/mypodtemplate/clone`. The response would contain a Location header with the path of the new resource (shouldn't we do that for all creations via POST? -- if so, we should add that to #2031). Making the inert pod to clone would work as above. This approach has some advantages:
1. We have a place to hang field overrides. Initially, we could use that to auto-enable the new pods.
2. It's easier to imagine how to write ABAC rules, since there's a distinct path.

**Comment by smarterclayton** [comment]
----- Original Message -----
> More concretely, I think this would work by allowing creation of inert
> objects using either a metadata or spec field, which would default to
> enabled (that is, normal, active objects). This bit would be flippable via
> the control subresource discussed in #2726. The object would have to set
> generateName. The replication controller would then create new pods by
> POSTing to /pods with Content-Location, and would have to then enable the
> new pods via the control subresource.
> 
> I agree that applying abac to that sounds tricky.

Let me think about the ABAC implications more.  The inert bit makes a lot of sense in general.

> 
> My understanding of the alternative:
> 
> POST to a subresource, say `/pods/mypodtemplate/clone`. The response would
> contain a Location header with the path of the new resource (shouldn't we do
> that for all creations via POST? -- if so, we should add that to #2031).

We should be setting the location header, but we don't necessarily have to do the redirect.  Most people end up returning the result body of the POST because they have the object handy (the round trip to the DB or store usually returns the right state), so it's just a default optimization.

> Making the inert pod to clone would work as above. This approach has some
> advantages:
> 1. We have a place to hang field overrides. Initially, we could use that to
> auto-enable the new pods.

Right - when I said another resource earlier I was imagining posting content-location to /clone, and we wouldn't need (on day one) to have a real resource to post.  On the other hand, creating the real resource gives you a schema that shows up in the API.  We could reserve content-location on the base resource as a shortcut way to do clone.  I think eventually field overrides will become important on clone, so best to plan for that outcome.

**Comment by smarterclayton** [comment]
One problem with using inert pods as templates is that they disappear into the press (if I'm using pods at scale I might have 10k pods and 2 inert pods), and to separate them for consumers you need to select a small subset of the pods (the 2).  I think "what pod templates do I have" is not an uncommon question.

I'm not arguing inert or clone shouldn't exist, but if we do believe the data structure for a pod template may support other options in the future, why not model it that way now, and introduce an action that does a transformation?

Example:

    POST /podtemplates {metadata: {}, spec: {template: {}, overrides: {}}}
    # creates a new template

    POST /podtemplates/foo/instantiate {overrides:{}} -> {/* pod */}
    # instantiates a pod from the template
    GET /podtemplates/foo/instantiate
    # dry run for instantiate, although if you need to see the effect of overrides you'd need to do it on POST and add a param

Clone operates on an existing resource, instantiate converts a template resource into its analogue.  Clone is always an operation on self, but instantiate is an adapter.  I assume the two can coexist.  If we have inert pods, then eventually people *can* use them like templates, but they will never have an alternate schema (can't easily define the set of allowed env overrides, for example).  

So it seems it's abac convenience now (new type) vs not having to create a new resource type.  It's probably slightly easier to create pod templates for 1.0 (don't have to carry inert implications throughout the system), but it assumes pod templates are a fundamental thing distinct from pods.

**Comment by bgrant0607** [comment]
I think that the signal vs. noise problem could be mitigated pretty easily with either field filtering (we'd need to introduce a new PodPhase, such as Inert or Disabled or somesuch) and/or label selection (using a by-convention `template` label).

If we wanted to clearly differentiate cloning and activation, we could create a custom operation to do that regardless of whether the object was a pod or pod template: `POST /pods/footemplate/instantiate` (or maybe `spawn`).

I think inert+clone has a natural synergy with finalization #3585: finalizers could fill in an inert object, after which it would either be activated or cloned.

I also think it enables pretty nice kick-the-tires scenarios, such as launching a pod, then creating a replication controller + template from it, though that could be enabled by client-side transformations, as well.

Admission control would have to run upon activation/clone, but that doesn't seem worse than invoking it on, say, updates to resource quantities.

I'm attracted to the elegance and flexibility of the inert+clone approach (similar to label selection vs. enclosing array of pods), but I'm willing to try one, the other, or both. Either would be better than embedding the template object in every controller, and it's admittedly hard to be certain which approach will be more natural to other people until they have something to play with.

**Comment by smarterclayton** [comment]
Do you see inert as generic to all resources (part of metadata, metadata.inert) or specific to some resources that expose it generically (part of spec, spec.inert)? 

I have a hard time imagining that every resource can be inert, but it certainly seems common to all of the current Kube resources, and also to most of the Openshift resources I can think of (deployments, routes, policies).

Is inert only an initial state?  For pods it seems yes, implying it cannot be toggled (since its part of pod phase which is one way).  If someone wants a toggleable field I think that should be something else.

**Comment by smarterclayton** [comment]
To summarize the set of "copy a resource" use cases:

* copy a resource to the local file system to recreate later
  1. GET
  2. POST (later)
* revert an existing object to its older state
  1. GET
  2. copy resource version in client, overwrite spec
  3. PUT
* copy a resource across namespaces
  1. GET
  2. change namespace field in client
  3. POST
* copy a resource within a namespace
  1. GET
  2. change name field in client
  3. POST
* create a resource that can be copied by other clients
  1. POST with inert and generate name
* copy a previously templated resource
  1. POST /resource/clone
  2. (Resets inert)
* convert a resource into another type via a transformation
  1. POST /resource/(spawn|instantiate) with resource representing transformation input

Agree on inert and finalizers.

**Comment by bgrant0607** [comment]
I do see inert as being generic, common to all objects. It facilitates use of the system as a configuration store and message bus, as well as facilitating finalizers.

I do see it as an initial or indefinite (for templates) state only.

**Comment by bgrant0607** [comment]
The list of "copy" scenarios is useful.

I see the main value of `clone` as having special-case authorization rules, as opposed to an open-ended creation operation. Limited mutations, such as enabling the object, would be for convenience.

As for conversion/typecasting, the primary examples we have are:
1. Replication controller from pod. Useful for kick-the-tires and bootstrapping.
2. Service from replication controller (expose).

If we could easily convert a pod into a template we could do the first one. The second just requires extracting the labels or selector. I'm willing to rely on the client for these 2 cases for now.

**Comment by ghodss** [comment]
I will just add that while I do not have an opinion on whether inert is useful, a PodTemplate is a much easier concept for new users to grasp from a UX perspective. Telling new users "okay, first, create a pod, but it's kind of a fake pod, now create a replication controller that's going to create real pods from your fake pod" is really confusing. "Create a template, create a replication controller and point it at that template to create pods" is WAY easier to understand and is a much better onboarding experience. Also `kubectl get pods` shouldn't return templates but it probably should return "inert" pods that are fulfilling other use cases, but I know less about that.

I also don't mind having the option of pointing a replication controller at a pod to clone it, but I do think it's more confusing and should be an advanced use case if it exists at all.

**Comment by smarterclayton** [comment]
Mirrors my thinking right now.  We can always alter pod templates in the future to point to inert pods via a migration.

**Comment by smarterclayton** [comment]
I started with pod templates as a separate resource.  My reasoning was mostly short term:

* Dividing pod templates into a separate resource right now is much easier to explain to end users (it's a template for a pod) 
* To properly handle inert pods, a good client would ideally present them differently (sorted, separated).  Most clients that want to show a runtime view would filter them.  They tend to disappear from any normal UI if the number of pods grows.
* Templates can allow spec updates with a single set of rules - pods would need different update rules for inert vs not (which means swagger can't easily express it).
* Inert requires slightly more changes to the rest of the codebase, such as replication controllers and services omitting them, scheduler waiting for the pod to not be inert.

I don't think starting with pod templates is incompatible with future introduction of inert pods - RCs should be able to target both pods and pod templates equally (they have to expose a clone/instantiate verb).  In the future, it should be possible to migrate pod templates to inert pods, or expose inert pods as pod templates.  It does seem like we need more handholding and clear delineating right now.

**Comment by bgrant0607** [comment]
I'm fine with pod templates.

**Comment by smarterclayton** [comment]
I'd like templates to be marked as immutable, which allows a client to communicate that a particular template should not be modified at runtime.  The server would reject updates to that template if set.  This would allow (for instance) an automated deployment tool to create an rc that cannot be tweaked, and force other clients to either delete and recreate the template (forcing uid to change) or to create a new template and point the rc at it.

**Comment by smarterclayton** [comment]
"To be able"

**Comment by bgrant0607** [comment]
We have some immutable templates internally. Some considerations:
* As with rolling updates themselves, declarative updates to such templates will require special handling, since the objects will need to be re-created rather than updated. We'll want a way to specify the default update approach declaratively, with some default config in kubectl that maps kinds to update strategies. 
* A new name needs to be generated for each new "version" of the object, but it has to be deterministic rather than random. Hashing the object, or some subset of it, works, but can create new objects in unexpected scenarios, such as when the generator itself changes what it does. Also, after defaulting, the hash of the created object won't match the original hash, fwiw.
* We'll likely also want to prevent "in use" objects from being deleted (e.g., the template currently used by a replication controller can't be deleted).
* Since clients wouldn't be able to delete objects when they want to, we'll need to be able to automatically GC them once they are no longer used. Maybe this could be a 2-stage graceful termination example: put the object into "shutting down" mode, then put on a deletion TTL once it is no longer needed.

**Comment by smarterclayton** [comment]
----- Original Message -----
> We have some immutable templates internally. Some considerations:
> * As with rolling updates themselves, declarative updates to such templates
> will require special handling, since the objects will need to be re-created
> rather than updated. We'll want a way to specify the default update approach
> declaratively, with some default config in kubectl that maps kinds to update
> strategies.
> * A new name needs to be generated for each new "version" of the object, but
> it has to be deterministic rather than random. Hashing the object, or some
> subset of it, works, but can create new objects in unexpected scenarios,
> such as when the generator itself changes what it does. Also, after
> defaulting, the hash of the created object won't match the original hash,
> fwiw.
> * We'll likely also want to prevent "in use" objects from being deleted
> (e.g., the template currently used by a replication controller can't be
> deleted).

Ugh, hadn't thought about that.  Yuck :)

> * Since clients wouldn't be able to delete objects when they want to, we'll
> need to be able to automatically GC them once they are no longer used. Maybe
> this could be a 2-stage graceful termination example: put the object into
> "shutting down" mode, then put on a deletion TTL once it is no longer
> needed.

**Comment by bgrant0607** [comment]
Well, we don't have to prevent in-use deletion, or we could implement a best-effort check. It's similar to preventing replication controller overlap. 

Assuming we don't 100% prevent in-use deletion, replication controller would need to do something reasonable, like report that it's broken in its status somehow.

**Comment by nikhiljindal** [comment]
/sub

Current status  (correct me if I am wrong):
- PodTemplate exist as separate resource.
- APIServer exposes POST, GET, DELETE, etc operations on /podtemplates
- PodTemplateSpec is currently inlined in ReplicationControllerSpec.

Remaining Work:
- Allow ReplicationControllerSpec to include a reference to PodTemplate.
- Add podtemplate support to kubectl

**Comment by JeanMertz** [comment]
@nikhiljindal is your "current status" still correct?

Ie. I'd like to separate the RC template from the Pod template, but am unsure if this is even possible yet? This issue is still open, so I guess there's still *something* left to do?

**Comment by nikhiljindal** [comment]
Yes @JeanMertz the above current status and remaining work are still true.

**Comment by bgrant0607** [comment]
It looks like we're never going to do this. Security concerns will be addressed another way.

Pods created will need to match other policies (e.g., PodSecurityPolicy), but checking whether a pod "matches" a template is hard to do in general.

**Comment by smarterclayton** [comment]
Sad.

**Comment by smarterclayton** [comment]
They aren't supported.  They may be in the future.  The type may be
used for polymorphic objects (get PodTemplate from Deployment)

**Comment by kargakis** [comment]
> so it appears I can create pod templates, but If I cannot use them in pods, what's their use?

DaemonSets and StatefulSets may use PodTemplates as a way of retaining history thus enabling rollbacks

**Comment by smarterclayton** [comment]
You can write automation that uses pod templates across multiple objects
for other reasons.

On Dec 16, 2016, at 10:18 AM, Michail Kargakis <notifications@github.com>
wrote:

so it appears I can create pod templates, but If I cannot use them in pods,
what's their use?

DaemonSets and StatefulSets may use PodTemplates as a way of retaining
history thus enabling rollbacks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/170#issuecomment-267616417>,
or mute the thread

**Comment by bgrant0607** [comment]
An alternative to fully moving the pod template out and replacing it with a reference to an external resource:

Create a pod template subresource for all the controllers (and even for CRDs eventually).

This would address the following use cases:
* Create an API endpoint that could have different permissions
* Create a uniform polymorphic API for pod template mutations, which could be used by `kubectl set` commands, for example
* Facilitate rollouts of new ConfigMaps (#22368) by making it easier to update references from controller pod templates
* Facilitate rollouts upon PodPreset changes, by enabling it to target the pod template subresource rather than pods directly

@pmorie @pwittrock @erictune

**Comment by bgrant0607** [comment]
If we had API support for apply (#17333), PodPreset could mutate the template spec without changing the user's intent.

**Comment by enisoc** [comment]
I'm not sure if admission plugins were already discussed as part of the motivation for potentially making use of the top-level PodTemplate resource, but here is a concrete use case where such a design would have been helpful:

https://github.com/kubernetes/kubernetes/issues/61886#issuecomment-378987100

**Comment by MadhavJivrajani** [comment]
/remove-kind design
/kind feature

`kind/design` will soon be removed from `k/k` in favor of `kind/feature`. Relevant discussion can be found here: https://github.com/kubernetes/community/issues/5641

**Comment by bgrant0607** [comment]
This was the original design (sunit prototype = pod template, replicate = replica set):
https://twitter.com/bgrant0607/status/1121058263959654400

But it can be addressed through a combination of type imports and duck typing. 

I don't think this will happen, so closing.
/close
