### ISSUE TITLE
Running Kubernetes via docker with DNS set up issues.

### ISSUE THREAD

**Issue by justingrayston** [kubernetes/kubernetes#17019]
I am opening this issue off of the back of #12534 and http://stackoverflow.com/questions/33255676/configure-kube-dns-when-running-kubernetes-via-docker

I am trying to get a simple set up via docker for devs to be able to develop locally with kubernetes running in docker. https://github.com/justingrayston/kubernetes-docker-dns

The docker.md got me up and running quite quickly, and I was able to get a local dev set up, loading up my own replication controllers and services for the various components of my app I am testing with. However, one problem was the ephemeral nature of the the service IPs and wanted to use the DNS like on GCE locally so we have a consistent set up, between, local, staging and production instead of using environment variables. Hence I started the above repo. I have faced several issues, mostly of my own making probably, but I can't seem to get this working with DNS.

The main culprit after much debugging/going in circles, is kube2sky not being able to talk to the API. I built from head my own image, and that stopped complaining which made me _think_ it was ok, however from running wget from within the container, it was obvious it was failing.

The problem form #12435 with the JSON parse error, is down to the following response on anything localhost:8080 (127.0.01 or 0.0.0.0) returning:
```
<b> Kubernetes healthz sidecar container </b><br/><br/><a href="/healthz">/healthz: healthz probe. Returns "ok" if the command given thr...
```
So connecting via 0.0.0.0:8080 will get the healthz instance. Which makes sense when I look at the skydns-rc.yaml.

That lead me to accessing the kube master api via the exposed service IP which for me is 10.0.0.1, only via port 443. 

Now I have x509 error. I found various issues (#10265 for example) referencing certificates and dns-tokens, however I don't see any mention of this in the add-ons/dns or docker.md, is their an easy way to provision this locally?

I note that with [local-up-cluster.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh) there is some root-ca provisioning going on, do I need to alter the hyperkube mater(-multi).json files to use different flags for the master pod?

I am pretty sure that I am missing something so obvious or doing something so stupid I can't even see it.

Do I need to create a certificate and token? Can I expose the master over 80 as it is only for a local dev set up.

I could be totally off down the wrong track though.

I also notice that in [skydns-rc.yaml.in](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in#L62) there is a dot after the domain. I have tried with and without, just in case, and it makes no difference at all, is this intended, I don't see it in some of the earlier examples in threads?

Any help would be greatly received!

**Comment by justingrayston** [comment]
Ooo. I note this merge...https://github.com/kubernetes/kubernetes/pull/16440 that the multi-node documentation has the dns set up in it....I was using the single node docker.md instructions...off to try multi node now.

**Comment by justingrayston** [comment]
Fantastic! It is working. 2 changes were made. Changed the Master to use manifest-multi, that then allowed kube2sky to access the master api via the docker machine IP on port 8080. DNS now works!!

Thanks to @thockin for his help in the other threads!

**Comment by bgrant0607** [comment]
I reopened #8413 to make this easier.
