### ISSUE TITLE
cluster/ubuntu/util.sh has dquoted strings with un-escaped internal dquotes

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#17014]
For example, in provision-node, there is a big multi-line string being passed to `ssh` but it has un-escaped internal quotes --- for example, around `${MASTER_IP}`.

**Comment by a-robinson** [comment]
Thanks for reporting the issue, @MikeSpreitzer! Would you be interested in also creating a pull request with a fix?

**Comment by MikeSpreitzer** [comment]
Yes, I have one ready.  But, as far as I know, the corporate CLA has not been signed yet.

**Comment by MikeSpreitzer** [comment]
BTW, I think this issue is only a matter of hygene, particularly after having gone through the fixing and seen the same variables referenced both with and without surrounding quotes.  If any licensed contributor wanted to fix this, it would be very easy.

I am more interested in issue #17013.  I have a fix for that one too.

**Comment by dalanlan** [comment]
I'll take a look then;-)
