### ISSUE TITLE
Create a test for kubectl rolling-update --rollback

### ISSUE THREAD

**Issue by johanhaleby** [kubernetes/kubernetes#17010]
I'm using GKE and Kubernetes 1.0.6 and I read in the [docs](https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/design/simple-rolling-update.md#aborting-a-rollout) that you should be able to rollback a release like this:

``` bash
$ kubectl rolling-update foo [foo-v2] --rollback
```

However I don't get this to work. I'm initializing a rolling-update like this:

``` bash
$ kubectl rolling-update app-v1 -f app-rc-v2.yaml
```

I deliberately abort the update (ctrl+c) when I see that app-v2 is being deployed:

``` bash
app-v1-fstog         1/1       Running   0          12m
app-v1-ye2lu         1/1       Running   0          11m
app-v2-fzlyw         0/1       Running   0          6s
```

Now I want to rollback the update but I'm unable to do this. This is what I've tried:
1. Trying to rollback according to the [documented instructions](https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/design/simple-rolling-update.md#aborting-a-rollout):
   
   ``` bash
   $ kubectl rolling-update app-v1 app-v2 --rollback
   ```
   
   This fails with the following error message:
   
   ``` bash
   error: Must specify --filename or --image for new controller
   see 'kubectl rolling-update -h' for help.
   ```
2. Try to rollback using the previous replication controller yaml file:
   
   ``` bash
   kubectl rolling-update app-v2 -f app-rc-v1.yaml --rollback
   ```
   
   This fails with the following error message:
   
   ``` bash
   error: app-rc-v1.yaml cannot have the same name as the existing ReplicationController app-v1
   see 'kubectl rolling-update -h' for help.
   ```
3. Try to rollback using the new replication control yaml file:
   
   ``` bash
   kubectl rolling-update app-v1 -f app-rc-v2.yaml --rollback
   ```
   
   This fails with the following error message:
   
   ``` bash
   Continuing update with existing controller app-v1.
   error: Missing/unexpected annotations for controller app-v1, expected app-v2: : map[kubectl.kubernetes.io/update-source-id:app-v2:]
   ```

I'm out of ideas on how to perform the rollback. Am I miss-interpreting the documentation or is there something else that is wrong?

**Comment by nikhiljindal** [comment]
```
kubectl rolling-update app-v1 -f app-rc-v2.yaml --rollback
```
is the right usage.
FWIW, that works for me on HEAD.

cc @ironcladlou

**Comment by janetkuo** [comment]
@nikhiljindal file names / image specified when rolling-back will generate error `Don't specify --filename or --image on rollback` on HEAD (but not v1.0.6). 

I'll update the help text of `kubectl rolling-update` for --rollback.

**Comment by nikhiljindal** [comment]
I synced my code to HEAD again and I get that error now.
Thanks @janetkuo

**Comment by bgrant0607** [comment]
Do we have a test for rollback?

**Comment by janetkuo** [comment]
No, I don't see any. We should add tests for rollback.

**Comment by janetkuo** [comment]
FWIW, this is an old issue should already be fixed by #14536. The remaining issue is that we need tests for rolling-update and rolling-back.

**Comment by zefciu** [comment]
Looking...

**Comment by zefciu** [comment]
@janeutko: Do we only need to test arguments' validation or should we also test the output that is sent to API?
