### ISSUE TITLE
cluster/ubuntu/util.sh vs. multiple NICs

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#17013]
Issue #9288 seems to have been addressed, at least for the userspace proxy, in the proxy code.  However, the script for creating a cluster on Ubuntu does not take advantage of this.  I have a cluster where each node has multiple NICs, and the default route is *not* through the NIC that: the flannel network should be constructed upon, the API server should use in its advertised URL, and to which kube-proxy should listen.  In util.sh, various options-setting functions should take an extra argument, which is the IP address to use, and their invocations should pass the IP address being used for the local machine (`$MASTER_IP` or `${1#*@}`).

**Comment by WIZARD-CXY** [comment]
Would you please list the extra argument which you want to add ?

**Comment by MikeSpreitzer** [comment]
The extra argument is an IP address of the node where the command is running.  In the provision-master* functions, that is $MASTER_IP; in the provision-*node functions, it is ${1#*@}.

**Comment by WIZARD-CXY** [comment]
hmm, small change

**Comment by MikeSpreitzer** [comment]
I have a patch for this, and it changes 10 lines.

**Comment by dalanlan** [comment]
> Issue #9288 seems to have been addressed, at least for the userspace proxy, in the proxy code. However, the script for creating a cluster on Ubuntu does not take advantage of this. 

@MikeSpreitzer I failed to follow the thread #6910 (tl; dr). Could you please kindly clarify the real benefit to set `--bind-address` for kube-proxy? It's mainly a performance thing, I guess. 
Since Tim used *subtle*, seems that I should reserve my opinion on this:-)

**Comment by MikeSpreitzer** [comment]
Regarding the kube-proxy's bind-address, remember that the default is the IP address of the NIC in the default route.  When that is not the right address for the kube-proxy to listen at then we need to generalize the util.sh script to make a better choice.  I have a cluster where the default route is NOT through the NIC at which the kube-proxy should listen.  That is why I need a change here.  I don't know if we care to get into all the details of _why_ my cluster looks like it does; other people are reporting similar things.  The short version of my story is that the default route is for access to stuff outside the cluster, not inside the cluster, and the NIC used for external access is not the NIC to use for intra-cluster networking.

**Comment by thockin** [comment]
The default for bind address is 0.0.0.0 - are you asserting that you have interfaces you DON'T want to listen on?  It's plausible, but it has a nasty side-effect - specifying bind-address means you won't listen on localhost.  NOT a huge-deal for kube-proxy (I think - it *is* subtle), but there are some docs out there that talk about connecting on localhost to debug stuff.

**Comment by MikeSpreitzer** [comment]
No, I am *NOT* asserting that I have interfaces on which I do *not* want the kube-proxy listening.  I thought I had a problem with it picking a particular, but wrong for me, IP address.  That was weeks ago now, and I do not recall why I thought that.  With the current code, leaving the bind address unspecified gets a working result --- the user-space proxy binds to \*.

For the API server, on the other hand, I *do* have a problem with the default for a _different_ parameter --- the advertised address.  If left unspecified, that defaults to the address of the interface used in the default route.  That does not work in one of my scenarios.  However, in all my scenarios thus far, the IP address that is being explicitly manipulated by the scripting in cluster/ubuntu/util.sh *does* work when given as the API server's advertised address.

**Comment by thockin** [comment]
So what is the request at this point?  Is it just to parameterize the setup
to choose a different interface to advertise?

**Comment by MikeSpreitzer** [comment]
Right.  The provsion-* functions are manipulating an explicit IP address for the master in question, and that would be a fine IP address to advertise for the API server.

**Comment by thockin** [comment]
I don't think that is a problem.  Is this specific to ubuntu or general?

**Comment by dalanlan** [comment]
It's not ubuntu-specific.

**Comment by MikeSpreitzer** [comment]
@thockin I am not sure how to parse what you said.  In the current cluster/ubuntu/util.sh, the function create-kube-apiserver-opts does not set the API server's advertise address; it also does not set the bind-address.  That means that the default will apply: the advertised address will be the address bound to the network interface that appears in the default route.  That is not working for some people, including some of the scenarios I run.  OTOH, the address known in most of that util.sh as KUBE_MASTER_IP works for all the scenarios I run, and I suspect it will work quite broadly.

Are you saying that there is a way I can make the API server's advertised address be that KUBE_MASTER_IP without any change to code/scripts maintained here?  If so that would be great, please clue me in.  Did I miss something in the documentation?

**Comment by thockin** [comment]
Sorry, I meant that I don't think it's a problem to add code to
parameterize.  But it's not something we need on all platforms.  For
example, it doesn't really apply to GCE :)

**Comment by MikeSpreitzer** [comment]
@thockin: the problem is with some provider-specific scripts, so there's no request here to change anything for GCE.  I have only looked at the two ubuntu scripts myself so far.

**Comment by dalanlan** [comment]
@MikeSpreitzer  Maybe i'm asking for too much, yet do you have any idea what `--advertise-address` of api-server is used for?

**Comment by thockin** [comment]
It's the address that we put in the kubernetes Service.
