### ISSUE TITLE
Build on arm64/aarch64

### ISSUE THREAD

**Issue by yghannam** [kubernetes/kubernetes#17012]
Support building on arm64/aarch64 hosts. The biggest part of this is to update the Godeps to support building on arm64. 

Here is a branch based on v1.2.0-alpha.2, and that builds and passes make check and make test_integration tests. 
https://github.com/yghannam/kubernetes/tree/v1.2.0-alpha.2-arm64

Here is a branch that is tracking kubernetes:master.
https://github.com/yghannam/kubernetes/tree/aarch64_port

Currently, builds targeting this aarch64_port branch fail because of lack of arm64 support in docker/libcontainer/seccomp. This may be resolved if Kubernetes changes from docker/libcontainer to opencontainers/runc, since docker/libcontainer is getting stale. However, this may be a large change.

**Comment by thockin** [comment]
@luxas is this still valid?

**Comment by luxas** [comment]
@thockin Nope, I fixed this already in v1.3 ;)
