### ISSUE TITLE
kubectl patch should accept stdin for -p

### ISSUE THREAD

**Issue by ericandrewlewis** [kubernetes/kubernetes#17028]
kubectl patch requires input via an argument with the `-p` flag.

e.g.

``` bash
kubectl patch secrets some-secret -p '{data:{"name":"new_val"}}'
```

Attempting to do this with stdin will result in various error messages.

``` bash
$ echo '{data:{"name":"new_val"}}' | kubectl patch secrets some-secret
error: Must specify -p to patch
see 'kubectl patch -h' for help
```

``` bash
$ echo '{data:{"name":"new_val"}}' | kubectl patch secrets some-secret -p
Error: flag needs an argument: 'p' in -p
Run 'kubectl help' for usage.
```

**Comment by ericandrewlewis** [comment]
Also

```bash
$ echo '{data:{"name":"new_val"}}' | kubectl patch secrets nytco --namespace=pub -p -
Error from server: invalid character ' ' in numeric literal
```

**Comment by a-robinson** [comment]
cc @jlowdermilk

**Comment by jlowdermilk** [comment]
Where in the docs are you seeing that patch *should* accept input from stdin? The help text for the command indicates `-p` is required.

**Comment by ericandrewlewis** [comment]
@jlowdermilk  Sorry I should've mentioned that!

[In the man page](https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.3/docs/man/man1/kubectl-patch.1#L6)

[In the kubectl user documentation](https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.3/docs/user-guide/kubectl/kubectl.md)

[In the kubectl patch user documentation](https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.3/docs/user-guide/kubectl/kubectl_patch.md)

[In this go file, not sure where this gets output to the user](https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.3/pkg/kubectl/cmd/patch.go#L60)

**Comment by ericandrewlewis** [comment]
Another question/discussion is whether kubectl patch *should* accept stdin.

**Comment by jlowdermilk** [comment]
I'm not convinced it should, but I can at least fix the help text.

**Comment by buth** [comment]
@jlowdermilk There's already precedence for this with the `-f` flag for other commands (including this one). For instance, this works:

```bash
kubectl create -f - < test_secret.json
```

Which then makes it seem strange that this does not:

```bash
kubectl patch secret test -p - < test_secret_patch.json
```

This is a problem in our use-case because we are using `kubectl` over SSH.

**Comment by jlowdermilk** [comment]
Reopened and changed title.

@buth, making `-p` accept stdin is stricky because it also takes a `-f` file that can parse from stdin. It's possible to have `-p` read from stdin and validate that only one or the other does, it's just not a quick fix.

@kubernetes/kubectl if someone wants to pick it up. Also cc @bgrant0607 to prioritize.

**Comment by bgrant0607** [comment]
-p should be deprecated in favor of the longer form of the argument, --patch.

It can't take stdin or a file, since that would be ambiguous. We'd need a new argument, like --patch-file.

The reason we can use `-f` is because that's reserved for expressing the resource to operate on.
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_patch.md

Note that you can also do:
`echo ... | kubectl patch secrets some-secret --patch $(cat -)`

**Comment by kargakis** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by groner** [comment]
Using `-p "$(cat)"` works to load the secret from stdin.

```sh
:; jq '{stringData: .AccessKey}' create-access-key-response.json |
    kubectl patch secret whatever-aws-apikey -p "$(cat)"
secret "whatever-aws-apikey" patched
```

**Comment by foobarbecue** [comment]
/remove-lifecycle rotten
Got here because I was trying to figure out how to load a patch from a file... seems like the -p "(cat mypatch.yaml)" method is the best so far. I really think patch and apply should behave identically, though, with regards to supplying the json or yaml from a file or stdin.

**Comment by jcfj** [comment]
(Obvious warning that `kubectl patch secret foo -p "$(cat)"` is not giving the security benefits that "read secrets from stdin" has.)
My reason for wanting this: what if your patch is bigger than `getconf ARG_MAX`?

**Comment by nobiit** [comment]
For anyone who is having trouble with this. You can try
```
kubectl patch secret foo --type=json --patch-file=/dev/stdin <<-EOF
  [
    {
      "op": "replace",
      "path": "/data/metadata/name",
      "value": "bar"
    }
  ]
EOF
```

**Comment by davidshen84** [comment]
/reopen
/remove-lifecycle rotten

I still experience this issue with kubectl v1.27.4.

```yaml
clientVersion:
  buildDate: "2023-07-28T09:46:04Z"
  compiler: gc
  gitCommit: 36645e7311e9bdbbf2adb79ecd8bd68556bc86f6
  gitTreeState: clean
  gitVersion: v1.27.4+k3s1
  goVersion: go1.20.6
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-07-28T09:46:04Z"
  compiler: gc
  gitCommit: 36645e7311e9bdbbf2adb79ecd8bd68556bc86f6
  gitTreeState: clean
  gitVersion: v1.27.4+k3s1
  goVersion: go1.20.6
  major: "1"
  minor: "27"
  platform: linux/amd64
```

I just tried @nobiit 's suggestion and it works. How come it can read from `/dev/stdin`, but ignore `-`? Using `-` as the standard input is the Linux standard.

`kubectl apply -f -` works just as expected.

**Comment by soakes** [comment]
> For anyone who is having trouble with this. You can try
> 
> ```
> kubectl patch secret foo --type=json --patch-file=/dev/stdin <<-EOF
>   [
>     {
>       "op": "replace",
>       "path": "/data/metadata/name",
>       "value": "bar"
>     }
>   ]
> EOF
> ```

Many thanks for the workaround @nobiit , this works a treat.  I must admit I didnt think about trying this.  Kudos to you sir.

**Comment by SecDWizar** [comment]
yq add a block to list
