### ISSUE TITLE
Internal deployment .spec.replicas is not optional

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#17023]
https://github.com/kubernetes/kubernetes/blob/d65c61f15a633ef682b34a0b768461695410d7fa/pkg/apis/extensions/types.go#L202

aka it's not a pointer as the respective v1beta1 field.

Is this known? Is this an issue at all? @bgrant0607 @nikhiljindal

**Comment by bgrant0607** [comment]
@kargakis

This is no different than for ReplicationController:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1135

The field is optional in the versioned API, but is always initialized in the internal rep by the defaulting pass. 

None of the fields of the internal rep should have json tags, so the omitempty inconsistency isn't important.

cc @nikhiljindal @ironcladlou @janetkuo
