### ISSUE TITLE
Should CreateTwoWayMergePatch return any bytes in case of no diff? 

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#17022]
I was playing around with patching and stumbled upon CreateTwoWayMergePatch always returning a diff. I created a unit test verifying that:
```go
func TestEmptyPatch(t *testing.T) {
	patch, err := CreateTwoWayMergePatch([]byte(`{"float64":1.7976931348623157e+308}`), []byte(`{"float64":1.7976931348623157e+308}`), precisionItem)
	if err != nil {
		t.Errorf("unexpected error %v", err)
	}
	if len(patch) > 0 {
		t.Errorf("unexpected patch returned: %v", patch)
	}
}
```
```
$ make check WHAT=Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/strategicpatch/
TEST_KUBE=1 hack/test-go.sh Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/strategicpatch/  
--- FAIL: TestEmptyPatch (0.00s)
	patch_test.go:1586: unexpected patch returned: [123 125]
FAIL
```
Is this expected? Should CreateTwoWayMergePatch return any bytes in case of no diff between original and modified content?

@jackgr

**Comment by jackgr** [comment]
Yes, it returns an empty patch, which if applied to the original, yields
the same thing. That is the correct and intended behavior. See, for
example, the test cases that expect an empty patch.

On Monday, November 9, 2015, Michail Kargakis <notifications@github.com>
wrote:

> I was playing around with patching and stumbled upon
> CreateTwoWayMergePatch always returning a diff. I created a unit test
> verifying that:
>
> func TestEmptyPatch(t *testing.T) {
>     patch, err := CreateTwoWayMergePatch([]byte(`{"float64":1.7976931348623157e+308}`), []byte(`{"float64":1.7976931348623157e+308}`), precisionItem)
>     if err != nil {
>         t.Errorf("unexpected error %v", err)
>     }
>     if len(patch) > 0 {
>         t.Errorf("unexpected patch returned: %v", patch)
>     }
> }
>
> $ make check WHAT=Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/strategicpatch/
> TEST_KUBE=1 <http://k8s.io/kubernetes/pkg/util/strategicpatch/TEST_KUBE=1> hack/test-go.sh Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/strategicpatch/
> --- FAIL: TestEmptyPatch (0.00s)
>     patch_test.go:1586: unexpected patch returned: [123 125]
> FAIL
>
> Is this expected? Should CreateTwoWayMergePatch return any bytes in case
> of no diff between original and modified content?
>
> @jackgr <https://github.com/jackgr>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/17022>.
>


-- 
Jack Greenfield | Google

**Comment by kargakis** [comment]
> Yes, it returns an empty patch, which if applied to the original, yields the same thing. That is the correct and intended behavior. 

Thanks, closing this.

**Comment by kargakis** [comment]
@jackgr back to this, we are looking for a way to determine that a patch is empty. Since an empty patch will always be a couple of bytes, does it make sense to pin that value to a constant that would denote an empty patch? Actually, what's the best way currently to determine on the client that a patch is empty?

cc: @liggitt @jhadvig

**Comment by jhadvig** [comment]
@kargakis after I print size of the patch I see the size is `2`

**Comment by jackgr** [comment]
Sorry for the slow reply. Traveling.

Rather than compare number of bytes, it would be better to compare the
contents of the patch. You're looking for a []byte that converts to the
string "{}".

Jack Greenfield | Google
