### ISSUE TITLE
Zeppelin doesn't work over application proxy

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#17032]
After PR #17025, if you do a `kubectl create -f example/spark`, this works `kubectl port-forward zeppelin-controller-84p9o 8080:8080`.

If you then connect to [http://localhost:8080](http://localhost:8080), you'll get a "connected" Zeppelin (see the green or red dot in the top right corner). However... `kubectl proxy --port=8001`, then: [http://localhost:8001/api/v1/proxy/namespaces/default/services/zeppelin](http://localhost:8001/api/v1/proxy/namespaces/default/services/zeppelin) doesn't. This suggests the application proxy is broken for this case. (Zeppelin is upgrading to a WebSocket.)

**Comment by timothysc** [comment]
IMHO we should hold off #17025 for a couple of reasons now.

**Comment by zmerlynn** [comment]
@timothysc: I actually think we should proceed with #17025. I included the `port-forward` workaround and a reference to the bug. Having that PR committed will make debugging this easier, and we're at the early side of the 1.2 release cycle, so with any luck will get it fixed before anything is visible.

**Comment by zmerlynn** [comment]
(And with any luck it's something that can be cherry-picked, because I'd really like Spark to work elsewhere.)

**Comment by zmerlynn** [comment]
The issue here is that Zeppelin is using absolute URLs for a couple of things and we're not rewriting properly:

```
I1110 23:08:31.573265       7 handlers.go:130] GET /ws: (293.8µs) 404 [[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.49 Safari/537.36] 74.125.59.6:35761]
I1110 23:08:31.683846       7 handlers.go:130] GET /assets/images/zepLogo.png: (303.435µs) 404 [[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.49 Safari/537.36] 74.125.59.6:35761]
I1110 23:08:32.955520       7 handlers.go:130] GET /ws: (276.387µs) 404 [[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.49 Safari/537.36] 74.125.59.6:35761]
```

@brendandburns and I chatted about this for a bit, and `port-forward` is probably the better solution. Getting all the corner cases of rewrite correct is not going to be easy here.

cc @liggitt @jlowdermilk

**Comment by liggitt** [comment]
agree on port-forward... I think a rewriting proxy is a losing battle

**Comment by liggitt** [comment]
also, trying to understand the particular thing rewrite was missing here... was it not rewriting data coming back over an upgraded connection?

**Comment by zmerlynn** [comment]
@liggitt: I'm not sure. The `/ws` is the WebSocket URL, so I'm guessing it upgraded then tried to establish the socket, but I'm not sure where that URL came from (probably JS on the client).

**Comment by liggitt** [comment]
Ah, JS would make sense as well, since that doesn't get rewritten

**Comment by zmerlynn** [comment]
Could we do something like a sticky URL reverse proxy with some sort of session cookie? It seems like we could do something clever where when you browse to http://localhost:8001/api/v1/proxy/namespaces/default/services/foo, we hijack and add a get a session cookie for "kubernetes service foo", at which point if your browser then asks for `/bar`, we see the cookie and say "oh, you mean service `foo`, `/bar`" (failing the same way as today if cookies are disabled, etc).

Brendan and I just chatted about this, and it sounds maybe viable (if hacky), and could possibly even be implemented directly in `kubectl proxy` without even touching the apiserver (under an option).

cc @brendandburns

**Comment by liggitt** [comment]
Sounds like a reach to make work well. I definitely wouldn't want that in the API server.

**Comment by lavalamp** [comment]
Isn't the problem just that websockets don't go through `kubectl proxy`?

**Comment by zmerlynn** [comment]
@lavalamp: What exactly are you proposing? Cracking the WebSocket stream and then ....?

**Comment by lavalamp** [comment]
Forwarding the websocket in both directions? Presumably it just totally doesn't work right now?

**Comment by liggitt** [comment]
I guess I'm not surprised that a rewriting proxy isn't working well with an advanced use case (JavaScript making web socket connections). If port forward is working, why not recommend that instead? We could look into making sure upgrade connections work, but I think chasing advanced rewrite scenarios is not a good idea.

**Comment by zmerlynn** [comment]
It's honestly additional friction to have to bring up `port-forward` for a single app. I'm already recommending it in the example, but the example *additionally* recommends `proxy` to get at the Spark WebUI. How many ways to proxy does one app stack need?

**Comment by errordeveloper** [comment]
I hostly do not understand how WebSockets can be neglected in 2016, especially given that Kubernetes API itself uses WebSockets.

**Comment by cmluciano** [comment]
Is this still an issue?
