### ISSUE TITLE
Application deployment orchestration/workflow tool

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1704]
Forked from #1007 and follow-on to #1702.

We ultimately want to automate most of the orchestration/workflow involved in deployment, so that most users don't need to write custom workflows or scripts. However, it's fairly complex, and we can't necessarily automate all of it in a domain-independent, use-case-independent manner. 

In general, a full deployment would likely be comprised of multiple files, each containing multiple objects (see #1694). These objects may have inter-dependencies (e.g., right now services must be created before their clients are created), rolling updates require special treatment (#1353), and application-specific rollout logic may be required. Therefore, I recommend we keep this more general deployment workflow separate from the basic primitive mechanism that reconciles a single object (#1702), and ensure that the two are composable.

We should design the deployment orchestration/workflow tool/library to be:
- configurable (e.g., inter-object ordering dependencies, group rate limits attached to label selectors), 
- selectable (just create/update/delete certain things), wrappable (so one could run another workflow around sub-workflows), 
- pluggable (so a workflow could be provided for updating microservices / replication controllers), and 
- hookable (so one could easily attach custom logic to a deployment workflow that largely works but needs to poke the application or something, or to externally control update rate/timing).

Other requirements:
- Support for progressive deployment across multiple clusters (with or without federation)
- Support for external (application or infrastructure) actions that aren't implemented by operators, initContainers, etc.

I haven't looked whether an off-the-shelf solution would largely work -- there certainly many workflow-y tools/systems out there.

**Comment by bgrant0607** [comment]
Typical scenario: Rollout across several clusters.

**Comment by zmerlynn** [comment]
I'm trying to figure out how to change this subject line to properly reflect that it's covering deployment of Kube objects specifically. When I saw the subject I got excited because I thought there may have been discussion on a more robust tool to do cluster deployment and upgrade and replace `kube-up.sh`, which was an issue I was about to go write. These need disambiguation. :)

**Comment by bgrant0607** [comment]
Disambiguated

**Comment by lewismarshall** [comment]
I've written a tool for CI / CD using kubectl to facilitate most of this - be happy to get feedback https://github.com/UKHomeOffice/kb8or

**Comment by eliaslevy** [comment]
Just a note that application deployment is usually the easy part. Client can usually retry until a service is available.  A more difficult problem is application shutdown.  These must usually be carefully orchestrated so as not to lose data.  Data processors must be signaled to flush their data to the storage layer before they are terminate and the storage layer can't be terminated before all it's clients have finished their work.

**Comment by bgrant0607** [comment]
Examples:
https://github.com/Mirantis/k8s-AppController
https://cloud.google.com/deployment-manager/configuration/create-configuration-file

**Comment by ash2k** [comment]
https://github.com/ash2k/smith
Here is a prototype of a similar idea (if I understand this issue correctly). The idea came to me a while ago and then I found this and other similar issues. Hopefully it may be useful to someone for inspiration, etc. Any feedback is appreciated.

**Comment by kargakis** [comment]
Closing as per discussion in https://github.com/kubernetes/kubernetes/issues/25067#issuecomment-310078181
