### ISSUE TITLE
gh-pages 404 redirect not working

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#17040]
The 404 page is redirected to v1.0, though the code is pointing to v1.1 (https://raw.githubusercontent.com/kubernetes/kubernetes/gh-pages/docs/index.md).

I knew a hacky work around that would probably work, but will try to find the root cause.

@janetkuo @bgrant0607 @nikhiljindal

**Comment by janetkuo** [comment]
Looks like it's fixed. Thanks!
