### ISSUE TITLE
1.1.1 Hyperkube image not configured correctly

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#17062]
Not sure the details here; @brendandburns, can you fill in?

This is somewhat related to #11751, which is for including the Hyperkube image in the releasing process.

**Comment by brendandburns** [comment]
I'm working on this now.  eta sometime tomorrow.

**Comment by brendandburns** [comment]
Marking this down to P1, as this works as much as it ever has as far as I can tell.

I'm working on improvements.

**Comment by brendandburns** [comment]
I'm going to close this in favor of the various efforts to improve the single node docker experience.
