### ISSUE TITLE
Please don't vendor unreleased components

### ISSUE THREAD

**Issue by onlyjob** [kubernetes/kubernetes#17077]
Kubernetes v1.1.1 bundles unreleased snapshot of https://github.com/appc/cni:
https://github.com/kubernetes/kubernetes/blob/v1.1.1/Godeps/Godeps.json#L31
which is used in https://github.com/kubernetes/kubernetes/blob/v1.1.1/pkg/kubelet/network/cni/cni.go#L21 (and maybe in other places).

The problem is that appc-cni have a formal release which may be more API stable or better tested than random snapshot of "master" which may or may not be released as is.

Please have some concerns for stability and vendor released versions by tag whenever possible.
Thanks.

**Comment by onlyjob** [comment]
FYI @rajatchopra

**Comment by ihmccreery** [comment]
This was picked into release-1.1 in #14805.  @thockin, can you please weigh in?

**Comment by ihmccreery** [comment]
Regardless of the `cni` specifics, this issue is a good one to consider: should released version of Kubernetes be relying on pre-release versions of other things?  Should master?  If master should and the release shouldn't, we need a procedure for resolving discrepancies.

**Comment by thockin** [comment]
What is the action to take here?  We're using it.  We could re-vendor to
newer tag, if one is available, but I don't think we can go backwards.

Fortunately we're using this in a beta aspect of the system, so impact of
instability should be minimal.

**Comment by thockin** [comment]
All the tooling here is sub-par, to say the least.
