### ISSUE TITLE
Feature request: test dashboard to view results/history for all test runs across jenkins jobs and branches

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#17079]
Right now visibility is the biggest problem we have with e2e tests. We have too many jenkins jobs to keep track of test history for each one manually, and with test filters becoming increasingly targeted, there is no easy way to know what job a particular test is running in. Moreover, because test filters are shared across jobs, changing them can result in a set of tests that _should_ be running on a particular provider/branch/job becoming silently disabled and no one is the wiser, as the test still looks green.

Case in point, filter updates caused reboot tests to be skipped on [gke-ci-reboot](http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-ci-reboot/). So the job is green but it isn't even testing what it's meant to.

In order to avoid this kind of confusion and get proper visibility into what tests are running, it would be immensely helpful to have a single test dashboard that aggregates latest test results across all jobs for every defined e2e test in one big grid. Ideally it would also make results viewable by provider (GCE, GKE) and release name.

**Comment by ixdy** [comment]
related #4871

**Comment by fejta** [comment]
Interesting idea for sure! Want to look into this for 1.4

**Comment by ixdy** [comment]
This is probably not P1...

@kubernetes/sig-testing

**Comment by spiffxp** [comment]
/close

I think testgrid.k8s.io satisfies this
