### ISSUE TITLE
Document requirement for DNS Hostnames in AWS VPC

### ISSUE THREAD

**Issue by beeradb** [kubernetes/kubernetes#17072]
## Issue summary

I recently worked through an installation of kubernetes into an AWS VPC which was created outside of kube installation scripts. I found this difficult on several fronts, but my biggest issue is that the VPC I was trying to install into didn't have "EnableDNSHostnames" enabled.

Attempting the installation without that setting enabled does not cause the kube-up.sh script to output any errors, but does hang indefinitely on the "Waiting for cluster initialization." step. Additionally, if I SSH into the kube master it does not appear to me that kube has bootstrapped correctly.

Using the exact same installation process, if I enable DNS hostnames the kube-up.sh script completes without issue and the cluster bootstraps as expected.
## Proposed solution:

I was only able to figure out the installation of kube into an existing VPC by reading through the installation shell scripts and realizing I could set environment variables for the VPC ID and subnet ID. The page at [aws under the hood](https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md) covers some of the details, but does not mention the DNS hostname part. I would suggest both adding that detail and ensuring that page is linked from the [aws installation guide ](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/aws.md)

Secondarily, if a VPC is supplied the setting could be detected using  [describe-vpc-attribute](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-vpc-attribute.html) and the user could be notified.

I'm happy to put together a pull request for this.

**Comment by bprashanth** [comment]
@justinsb

**Comment by beeradb** [comment]
Just nudging this issue. I realize it's probably low priority, but it's also an easy change which I feel would add clarity to the installation docs.

If I should just take initiative and issue a pull request let me know, but as I understand [contributing.md](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md#contributing-a-patch) I'm supposed to issue a proposal and get a thumbs up first.
