### ISSUE TITLE
Pod on GKE cannot pull image from GoogleContainerRegistry

### ISSUE THREAD

**Issue by michaelukpong** [kubernetes/kubernetes#17086]
I created an image and pushed it to GCR using:
```gcloud docker push gcr.io/{project-id}/{image-name}```.

 I can see the image when I log into GCR so all seems fine.  But however, when I run
 ```kubectl run {pod-name} --image=gcr.io/{project-id}/{image-name}```
```kubectl get pods```

I get the following error:
```image pull failed for gcr.io/td-middleware/tdb, this may be because there are no credentials on this request.  details: (Error: image td-middleware/tdb:latest not found)```

The GKE [images doc](https://github.com/kubernetes/kubernetes/blob/1f952b05d3e56cf233c94f1b2c65f05e6cde5061/docs/images.md#using-a-private-registry) says that the my pods should be able to access my private GCR and that makes perfect sense. But somehow this isn't happening... am I missing something?

**Comment by mattmoor** [comment]
@dchen1107 I see a ton of unauthenticated requests for this project.

**Comment by mattmoor** [comment]
@brendandburns FYI

**Comment by dchen1107** [comment]
An update: @brendandburns figured out the root cause of the issue: Pantheon is creating clusters w/o the storage read scope, and oncall is fixing it.

**Comment by roberthbailey** [comment]
@michaelukpong does your GKE cluster still exist?

**Comment by roberthbailey** [comment]
It looks like you deleted your cluster already. Creating a new cluster should resolve this issue for you. Sorry for the trouble.

**Comment by michaelukpong** [comment]
@roberthbailey Thanks guys, deleted the cluster and setting up a new cluster worked.
