### ISSUE TITLE
Move docs for "GCE Load-Balancer Controller (GLBC) Cluster Addon" into k8s.io

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#17080]
The doc at https://github.com/kubernetes/kubernetes/blob/release-1.1/cluster/addons/cluster-loadbalancing/glbc/README.md doesn't seem to be accessible on k8s.io, presumably because it's a README buried in `cluster/`.  Can we move it out into a place that will be more accessible to users?

**Comment by bprashanth** [comment]
The docs on k8s.io don't seem to contain https://github.com/kubernetes/kubernetes/pull/16959. The plan was to include a link to cluster/addons from there. Presumably that cherry-pick missed some k8s.io doc train, @caesarxuchao do you know what one needs to do to update docs on k8s.io?

**Comment by caesarxuchao** [comment]
See https://github.com/kubernetes/kubernetes/pull/16567#issue-114174773.

After running the script, you can just check in the file you are interested.

Let me know if this doesn't work.

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
@nicksardo do you think we still need to keep this addon here https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-loadbalancing/glbc given we already have a more extensive documentation at https://github.com/kubernetes/ingress/tree/master/controllers/gce

**Comment by nicksardo** [comment]
The GLBC still depends on this defaultBackend addon, so the yamls shouldn't move.

I'm not too worried about this readme being inaccessible from k8s.io. Agreed, the information seems to be a summary of everything in `kubernetes/ingress/controllers/gce`.  If we need to do anything, it's adding links pointing to docs of the various ingress controllers on k8s.io.

**Comment by cmluciano** [comment]
@nicksardo Is this still relevant?

**Comment by ahmetb** [comment]
I'm trying to see if there's a precedent for moving vendor-specific docs to the website (excluding the installation/setup guides). I think the rule of thumb nowadays is to keep the website vendor-neutral. That said, we can split the large README.md s into smaller markdowns, and link to their GitHub pages from the docs website where appropriate.

**Comment by chenopis** [comment]
FYI, we now have a general purpose import script [`/update-import-docs/update-imported-docs.go`](https://github.com/kubernetes/website/tree/master/update-imported-docs) that can import docs from other kubernetes repos into kubernetes.io. If you still want to https://github.com/kubernetes/kubernetes/blob/release-1.1/cluster/addons/cluster-loadbalancing/glbc/README.md on the website, let me know. I can find a place for it.

**Comment by ahmetb** [comment]
Not sure if we should have vendor-specific Ingress docs on the site. We can link to them, but I think they should be outside the official docs.

- There are too many Ingresses even today (gce, nginx, contour), and many more probably being developed since Azure/AWS are now offering hosted k8s too. 
- Ingress is being planned to revamped completely. (a v2, or abandon) That's why any effort to start importing docs to this site probably will be void soon.

**Comment by cmluciano** [comment]
That's a good point. @kubernetes/sig-network-pr-reviews WDYT?
