### ISSUE TITLE
Pods on AWS with native networking can't access Amazon provided DNS

### ISSUE THREAD

**Issue by eliaslevy** [kubernetes/kubernetes#17084]
When using native networking in in AWS (i.e. with options `cloud-provider=aws`, `cluster-name=<cluster_name>`, `allocate-node-cidrs=true`, `cluster-cidr=<pod_network>`, `configure-cbr0=true`, `bridge=cbr0`, `iptables=false`, and `ip-msq=false` as appropriate to `kube-apiserve`r, `kube-controller-manager`, `kubelet`, and `docker`), everything works except that Pods, including kube-dns, can't make DNS queries to the Amazon provided DNS server in the subnet.  That means Pods can't resolve external hostnames.

It appears that the Amazon provided DNS server won't respond to queries with an address other than one within the subnet.  The solution to the problem is to masquerade traffic from the Pod network to the Amazon provided DNS server in the subnet.

`sudo  iptables --table nat -A POSTROUTING -s <pod_cidr> -d <dns_ip>/32 -j MASQUERADE`

Arguably this should be done by `kubelet`when it is passed the `configure-cbr0` option alongside the `cloud-provider=aws` option.

**Comment by bgrant0607-nocc** [comment]
cc @justinsb @brendandburns

**Comment by therc** [comment]
This is where I look for what people are doing to tackle the problem and I find duplicates of #11204 (RDS is also affected; it uses addresses in the 10.* range)

**Comment by eliaslevy** [comment]
@therc you sure you can't just add the pod's CIDR to the RDS security group?

**Comment by therc** [comment]
@eliaslevy I thought the basic issue for most of these AWS problems was that the pod's node was setting up masquerading incorrectly, see  #19389

**Comment by eliaslevy** [comment]
@therc while #19389 is of concern, it is not related to not being able to connect to the Amazon DNS server in the subnet, nor do I think its related to the RDS issue you mentioned.  

Note that the masquerade rule with the hardcoded 10.0.0.0/8 network in kubelet says to masquerade traffic is _not_ destined to 10.0.0.0/8.  As the Amazon DNS and RDS are assigned IPs within the VPC network address, if you use the Kubernetes default of 10.0.0.0/8, then pod traffic to the Amazon DNS or RDS won't be masqueraded.

Where #19389 fixed, then kubelet would be creating the same masquerade rule with whatever network you assigned the Kubernetes VPC, but the Amazon DNS and RDS would be assigned addresses within that network also.  So in this case connections to them from the pods would not trigger the masquerade rule either.  The behavior is the same in both cases.

The problem is not that #19389 has not been fixed, but at least for the Amazon DNS it is that with native network traffic the DNS server will see Pod traffic coming from 10.2.0.0/16 and that the DNS server filters out any traffic not coming from its local network of 10.0.0.0/16. That is why I suggest kubelet need to add a masquerade rule specific to masquerading Pod traffic to the Amazon DNS server.

I suspect the RDS issue you observed is similar, except that in that case you should be able to modify the RDS security group so that it accepts connections from the Pod's CIDR, thus not requiring a masquerade rule.

**Comment by therc** [comment]
@eliaslevy: makes perfect sense now, thanks.

**Comment by thockin** [comment]
I don't think kubelet should add that rule, I think the AWS provisioning should.  In fact, the MASQUERADE rule in question, probably should be, too.  It's just so specific to a particular installation.

**Comment by eliaslevy** [comment]
@thockin it can be done in a provisioning step, which is I do right now.  But one could also argue that it should be within a networking plugin, which is executed by kubelet to initialize the node.  This is only necessary if you are using AWS native networking, so it could be reasonably included in an AWS native networking plugin.

**Comment by thockin** [comment]
If there were an AWS-specific plugin, sure, but that feels like the wrong
granularity for a plugin.

**Comment by bprashanth** [comment]
@eliaslevy can you send a pr with your provision-time fix? Is it something like https://github.com/eliaslevy/coreos-kubernetes/commit/992ca32440f82917a910738610a1d7e9b6baba30 ?

**Comment by eliaslevy** [comment]
@bprashanth Apologies for the late reply.  I've been traveling for a number of weeks.  

You've found the correct commit.  Specifically, the line that sets the masquerade rule is https://github.com/eliaslevy/coreos-kubernetes/blob/992ca32440f82917a910738610a1d7e9b6baba30/multi-node/aws/artifacts/scripts/install-worker.sh#L73.

As you may have noticed, I am not using the `kube-up.sh` provisioning script. Instead, I am using a fork of the Kubernetes on CoreOS repo, which uses CloudFormation and CoreOS's cloud-config. I am not that familiar with the standard provisioning system, but I would image you'd have to change how Salt provisions `kubelet` when AWS native networking has been selected by modifying the files under [kubernetes/kubernetes/tree/master/cluster/saltbase/salt/kubelet](https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt/kubelet).

**Comment by bprashanth** [comment]
I think @justinsb should be able to help with AWS setup scripts, we can try to get this for 1.2.X

**Comment by justinsb** [comment]
@bprashanth you mean 1.2.1 or 1.2.2, right?  (i.e. not 1.2.0...)

**Comment by bprashanth** [comment]
Yep I meant for X > 0, pods not being able to resolve external names sounds cherry-pick worthy to me

**Comment by dstynchula** [comment]
How can I add this rule to the existing set of iptables rules that get applied to an Ubuntu node in an autoscaling group so that it gets applied on launch?

**Comment by bprashanth** [comment]
@justinsb did we end up fixing the provision scripts? if so, we can propose a cherry-pick

**Comment by justinsb** [comment]
Can someone clarify the issue here?

Defaults:
1. VPC CIDR is 172.20.0.0/16,  Amazon DNS is at 172.20.0.2
2. The "k8s network" is 10.0.0.0/8 or 100.64.0.0/10 (this is NON_MASQUERADE_CIDR)

So pod traffic to the DNS servers should be NAT-ted?

The case when this doesn't happen is if VPC CIDR overlaps NON_MASQUERADE_CIDR, but in that case I think this is the least of your problems :-)

Is it the overlapping case that is the concern?  Or am I missing something?
