### ISSUE TITLE
JSON clients have trouble with ints >= 53 bits

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#17095]
There are several fields in the API that use int64 types (uid, gid, etc). Any int >= 53 bits will not be preserved when read using some JSON clients that treat all JSON numbers like float64s (notably, browsers).

That means web clients cannot create items containing ints >= 53 bits (it will serialize them as floats, which will lose precision at best, and break go decoding at worst)

We should investigate converting uid/gid (and other int64 fields) to IntOrStrings, or adding validation to restrict int64 values to (at most) `-9007199254740991 <= x <= 9007199254740991`

References:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by liggitt** [comment]
cc @pmorie @jwforres

**Comment by smarterclayton** [comment]
Also broke my kubecon demo but in an impressive way :)

**Comment by liggitt** [comment]
@smarterclayton, fwiw, 1000000000 worked for me with https://github.com/openshift/origin/pull/5774 / https://github.com/kubernetes/kubernetes/pull/16964 ... only values over 53 bits broke in my tests from the browser

**Comment by bgrant0607** [comment]
We had trouble with this for resource values, also, before we introduced Quantity.
cc @lavalamp

**Comment by lavalamp** [comment]
`resource.Quantity` is encoded as a string, so it should pass through anything. Unfortunately, it's not a natural fit for e.g. gid/uid.

`int64` is a critical part of our api, but this is tricky: if we start serializing as strings, we have to rev the API.

We have been acting as if numeric values in json are integers or floats depending on how they're formatted. Is this in line with the JSON spec? (i.e., are we wrong, or are the clients wrong?) I think we even use our IntorString thingy to marshal as a *string* to store floating point values.

It seems perverse to marshal as a string to force integer behavior :(

**Comment by liggitt** [comment]
From the JSON spec:
> JSON is agnostic about numbers. In any programming language, there can be a variety of number types of various capacities and complements, fixed or floating, binary or decimal. That can make interchange between different programming languages difficult. JSON instead offers only the representation of numbers that humans use: a sequence of digits. All programming languages know how to make sense of digit sequences even if they disagree on internal representations. That is enough to allow interchange.

In practice, most implementations deserialize as float64 (go does by default, Javascript does by spec)

> `int64` is a critical part of our api, but this is tricky: if we start serializing as strings, we have to rev the API.

Don't I know it. Not sure which I dislike more, API breakage or data loss/corruption...

**Comment by pmorie** [comment]
@liggitt 

> Don't I know it. Not sure which I dislike more, API breakage or data loss/corruption...

Put that way it seems like a no-brainer that API breakage is the lesser of two evils to me.

**Comment by thockin** [comment]
This is the biggest piece of brain damage I have ever EVER heard.

We can do tricks with marchal/unmarshal ourselves (i.e. JSON looks like an
int to humans, but managed as string) but we can't mandate client libs to
do that across languages.

We can start accepting IntOrString for all ints > 32 bits, and deprecate
the int representation.  But this means sometimes users say "0" and
sometimes 0.  Puke.

We can start accepting IntOrString for ALL ints, always emit string, and
warn any time we get an int in the danger zone (can we characterize that
precisely).

We can stop using int64 and go with uint32 for uid/gid.  We still have
quantities, but at leas those can already be strings.  Any others?

**Comment by smarterclayton** [comment]
Going through the protobuf stuff, every use of int or uint is broken anyway.  For the non-controversial ones I'll submit a pr to make them int32 (anything with port, uid, gid, etc).

Most IntOrString should probably be int32 anyway - all the ports, at least.  We should have Int32OrString.

**Comment by smarterclayton** [comment]
Also, int32orstring should be in unversioned.

**Comment by lavalamp** [comment]
Yes, there's actually an issue I filed about this ages ago. hmm...
https://github.com/kubernetes/kubernetes/issues/2264 Sounds like we thought
we fixed it at one point.

**Comment by liggitt** [comment]
We "fixed" it by correctly deserializing int64 in our code (at least into typed structs), and by specifying int64 in the API types, but it looks like JSON implementations generally don't handle int64

**Comment by smarterclayton** [comment]
Also, people aren't applying that during API review, so we have 20-30
fields which are int internally which means the server *could* return a
very high number to JavaScript.

On Nov 16, 2015, at 7:41 PM, Jordan Liggitt <notifications@github.com>
wrote:

We "fixed" it by correctly deserializing int64 in our code (at least into
typed structs), and by specifying int64 in the API types, but it looks like
JSON implementations generally don't handle int64

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17095#issuecomment-157221313>
.

**Comment by liggitt** [comment]
+1 for int32/uint32 in API types, and continuing to render them as numbers in API responses, not strings.

Looking through the types.go files, the only current int/int64 API fields I see maaybe actually using values > 2 billion are:
* `Generation`/`ObservedGeneration`: not sure how quickly we use up the value space
* `Replicas`: > 2 billion replicas seems like a stretch, but...
* `PodLogOptions.LimitBytes`: would limit to 2 (or 4) GB of logs... not sure how many people streaming multiple gigabytes of logs still care about a limit
* `PodLogOptions.TailLines`
* `ContainerStatus.RestartCount`, though doc claims it is limited to 5

For uid, gid, port, exitcode, signal, I don't see how values > MAX_UINT32 would even be usable, and for the relative timeout fields, I don't anticipate 60 to 100-year-long timeouts or graceful deletion deadlines.

**Comment by smarterclayton** [comment]
I started fixing this in #17353.  It's a horrible PITA to fix this because
we can't regenerate conversions easily.

I made replicas int32, left generation, left log options, and changed
restart count to int32.  I also made prober 32.

**Comment by bgrant0607** [comment]
How does this relate to #16964?

**Comment by thockin** [comment]
On Mon, Nov 16, 2015 at 7:38 PM, Jordan Liggitt
<notifications@github.com> wrote:

> PodLogOptions.LimitBytes: would limit to 2 (or 4) GB of logs... not sure how many people streaming multiple gigabytes of logs still care about a limit

We could also change this to a quantity, so 1234 means the same thing,
but 1234Gi means what you think it means.

> PodLogOptions.TailLines

ditto


> For uid, gid, port, exitcode, signal, I don't see how values > MAX_UINT32 would even be usable, and for the relative timeout fields, I don't anticipate 60 to 100-year-long timeouts or graceful deletion deadlines.

uid/gid was int64 to allow negative numbers.  I say screw it and go
for uint32 for those.

port should be uint16 or uint32
exitcode and signal should be int32

**Comment by liggitt** [comment]
It's related, but https://github.com/kubernetes/kubernetes/pull/16964 is still needed, since I was seeing the default go JSON marshal/unmarshal handler switch to exponent notation when roundtripping, even under the int32 boundary.

**Comment by pmorie** [comment]
@liggitt 

I think the most problematic ones in practice would be the PodLogOptions ones you mentioned, and I second Tim's suggestions for those.  Generation/ObservedGeneration could also conceivably become a problem in super-long lived RCs, but this same situation existed previously, just with a higher limit, right?  We probably ought to think through the boundary conditions of all such sequences / counters in the system.

> I don't anticipate 60 to 100-year-long timeouts or graceful deletion deadlines.

I literally lol'd at this idea.  I suppose there are use-cases if you're programming the monolith from 2001, but probably not for kubernetes.

**Comment by liggitt** [comment]
Since we ended up with int pointers for uid/gid, etc, we can tell the difference between 0 and unset. Was there any other reason for a negative uid?

**Comment by liggitt** [comment]
> I suppose there are use-cases if you're programming the monolith from 2001, but probably not for kubernetes.

*very* eventually consistent

**Comment by thockin** [comment]
Negative UIDs are a thing, as per most UNIXes.  we were trying to avoid
pain, but screw it.

**Comment by smarterclayton** [comment]
If a container says it wants to runAs -2, we should nuke the cluster from
orbit.

It's the only way to be sure.

On Nov 17, 2015, at 1:28 AM, Tim Hockin <notifications@github.com> wrote:

Negative UIDs are a thing, as per most UNIXes. we were trying to avoid
pain, but screw it.

On Mon, Nov 16, 2015 at 10:24 PM, Jordan Liggitt <notifications@github.com>
wrote:

> Since we ended up with int pointers for uid/gid, etc, we can tell the
> difference between 0 and unset. Was there any other reason for a negative
> uid?
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/issues/17095#issuecomment-157283433
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17095#issuecomment-157283929>
.
