### ISSUE TITLE
Configurable pod defaulting

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#17097]
Two other notes - Brian and I and a few others discussed defaulting and how that's technically the role of LimitRanger in general (to apply a default to a pod resource).  We discussed having LimitRange evolve into PodPolicy which is the more generic complement to PodSecurityPolicy - to apply simple defaults to pods that are created.  Things that could be defaulted / ranged per namespace:
- node selector
- pod labels
- pod annotations
- environment variables onto pods
- specific secrets
- generic security defaults (vs the more sophisticated defaulting in PSP)

Not a truly generic solution _except_ it allows simple proscriptive control like node selector to be applied by a resource a regular user may not have access to change

**Comment by derekwaynecarr** [comment]
I like this.

**Comment by bgrant0607** [comment]
Related: #15390

I think we need at least 2 things:

1. A generic resource policy object -- not just for pods. I'd use this for labels and annotations. #15390
2. A pod-specific policy object, which is the generalization of LimitRange.

Is there a reason why we wouldn't fold pod security policy into the latter?

cc @erictune

**Comment by bgrant0607** [comment]
cc @pweil-

**Comment by pweil-** [comment]
I'm not sure yet that having the PSP inside another policy makes sense unless something in the new policy directly relates to the security policy.  For instance does this imply that validation under a PSP is only acceptable if all conditions of the over arching policy are met?  Or are they really separate pieces?  

If they are tied together I would also be concerned about the number of variations someone might need to make.  The number of combinations possible with the current PSP is pretty high, though it is unlikely that someone will use more than a handful, I would guess.

Need to read up on the current efforts, maybe that will help shed some light.

**Comment by bgrant0607** [comment]
cc @mml

**Comment by bgrant0607** [comment]
#17098 made me think of other examples: 

I'd like to be able to require restart=Never and restart=OnFailure pods to have a max/default ActiveDeadlineSeconds.

I'd like to be able to set a max/default TerminationGracePeriodSeconds.

**Comment by bgrant0607** [comment]
Related: https://github.com/docker/docker/issues/11187

**Comment by bgrant0607** [comment]
Namespace is probably too coarse to apply a number of these policies. We'll likely want to use label and field selectors for targeting.

**Comment by bgrant0607** [comment]
Another example: automatically select a scheduler: #17197

**Comment by thockin** [comment]
I'm skeptical that a declarative object is going to provide enough
expressiveness to cover all these use cases.  It sounds more like code
snippets run at some early point in the lifecycle.

**Comment by smarterclayton** [comment]
For small namespaces (app specific), just the defaulting is probably
enough.  For larger namespaces, I agree.

However, it's not clear how much customization you need.  If you had a
label based approach to limitranger selection you can do a number of things
during namespace setup that could just work when you deploy stuff.  I think
we should map out what more complex scenarios could look like here.


On Nov 13, 2015, at 11:32 PM, Tim Hockin <notifications@github.com> wrote:

I'm skeptical that a declarative object is going to provide enough
expressiveness to cover all these use cases. It sounds more like code
snippets run at some early point in the lifecycle.

On Fri, Nov 13, 2015 at 3:13 PM, Brian Grant <notifications@github.com>
wrote:

> Another example: automatically select a scheduler: #17197
> <https://github.com/kubernetes/kubernetes/pull/17197>
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/issues/17097#issuecomment-156585160
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17097#issuecomment-156626098>
.

**Comment by bgrant0607** [comment]
Another example: credential injection (Secret volume + env var)
https://developers.google.com/identity/protocols/application-default-credentials

**Comment by bgrant0607** [comment]
@thockin I'm trying to avoid client-side config munging via templates written in a Turing-complete DSL where everything in the templates can be overridden. :-)

Having such a runtime defaulting mechanism would facilitate the use of mostly concrete, discretely parameterized templates.

**Comment by thockin** [comment]
I'm just seeing a list of capabilities as long as my arm, and I can easily
imagine it sliding into a master-side turing complete system.

**Comment by smarterclayton** [comment]
We can call it DefinitelyNotTuringCompleteMasterSideTemplatingSystemPolicy.

**Comment by bgrant0607** [comment]
@thockin The idea here is to separate operational concerns from (for lack of a better term) development concerns. How the operational policy and overrides are generated is out of scope. Matching of operational policy/overrides to pods and other resources should support common use cases and otherwise rely on the escape hatch of using namespaces and/or label selectors to select matching resources.

**Comment by bgrant0607** [comment]
Related to the matching problem: #17324

**Comment by bgrant0607** [comment]
@derekwaynecarr mentioned that we should try to separate cluster-admin (global) concerns from project-admin (namespace) concerns.

**Comment by derekwaynecarr** [comment]
@bgrant0607 - thanks for pointer.

For background, right now OpenShift by default restricts the ability to create/edit a LimitRange and a ResourceQuota in a Namespace to a cluster-admin.  The idea was the cluster-admin wants to restrict the min/max constraints or overall shape of a pod as well as control cluster compute usage within the Namespace.

The challenge here is that the namespace-admin wants to modify the default request or default limits that are applied to pods as a means of controlling their usage within the quota boundary.  This makes sense, after all, the cluster admin should only care that the request/limit is within the min/max boundaries defined for the compute resource.

Right now, the two needs are bundled, but the actors are different.  It's rational for a cluster admin to still specify default request and limit, but its also reasonable to allow a local namespace admin to provide an override.

As a result, I think we need to distinguish pod defaulting with that in mind going forward.

**Comment by derekwaynecarr** [comment]
To say another way, we may want to think of LimitRange as the cluster-admin tool of choice for saying what the Namespace is allowed to do.  We can think of PodPolicy as the local namespace-admin tool to control what he can do within those boundaries.

**Comment by bgrant0607** [comment]
Common env vars request: #15627

**Comment by erictune** [comment]
Security policy CRUD operations on objects should be generic.
I think security policy about what values are allowed on specific fields should not be generic.
It should be specific to the objects it authorizes.
I said more about this in https://github.com/kubernetes/kubernetes/issues/17549



I think that some rejections require fairly complex computations that are going to be hard to express in a generic object.  For example:

- node selector: want to check if this is a subset of some other selector (users requested nodes may be subset of users allowed nodes which is subset of all nodes)
- pod annotations: these are tending to include structured data, so simple string comparisons are not going to be enough

Regarding defaulting specific secrets: this is done via ServiceAccount already.

By the way, I want to split the defaulting responsibility and the rejecting responsibility of LimitRanger in two objects.  Call them Defaulter and FieldChecker.

**Comment by davidopp** [comment]
Would be good to combine this with #18262.

**Comment by mml** [comment]
In order to evaluate APIs against each other, it would be useful to keep a canonical list of defaulting/restricting/ranging policies.  Actually two lists:  real requests from users and requests we can reasonably imagine arising.

**Comment by bgrant0607** [comment]
Noting an existing example so I don't forget: Service Accounts automatically inject secrets at a well known path within each container.

http://kubernetes.io/docs/user-guide/service-accounts/
http://kubernetes.io/docs/admin/service-accounts-admin/
http://kubernetes.io/docs/user-guide/kubectl/kubectl_create_serviceaccount/
```
type ServiceAccount struct {
...
	Secrets []ObjectReference `json:"secrets,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,2,rep,name=secrets"`
	ImagePullSecrets []LocalObjectReference `json:"imagePullSecrets,omitempty" protobuf:"bytes,3,rep,name=imagePullSecrets"`
}
```

**Comment by bgrant0607** [comment]
Note that PodPreset went into 1.6:

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/settings/v1alpha1/types.go#L28
