### ISSUE TITLE
Add/improve E2E testing of of persistent volumes claims (PVC)

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#17092]
We should improve E2E testing of persistent volumes claims (PVC).
- The existing test (`test/e2e/persistent_volumes.go`) uses NFS and is disabled for regular test runs.
- We should add a few GCE PD based test so that PVC code is regularly tested as part of Jenkins `kubernetes-e2e-gce` build.

**Comment by copejon** [comment]
#34353 Adds 2 GCE tests (Delete PV || PVC before pod does not cause the pod on subsequent deletion due to umount or detach error) and the framework to expand GCE specific testing of PVs.

**Comment by copejon** [comment]
#40885 Further addresses this by consolidating GCE tests into a single persistent_volumes-gce.go file.

**Comment by msau42** [comment]
There are quite a few PVC e2e tests now.
/assign
