### ISSUE TITLE
HDFS cluster can't work with kubernetes + flannel

### ISSUE THREAD

**Issue by ztao1987** [kubernetes/kubernetes#17094]
Hi,

I deployed kubernetes with flanneld.service enabled in coreos. And then I started hdfs namenode and datanode via kubernetes replication-controller. I also created kubernetes service for namenode. The namenode service ip is 10.100.220.223, while the pod ip of namenode is 10.20.96.4. In my case, one namenode and one datanode happens to be on same host. And namenode pod and datanode pod can ping each other successfully. 
However I encountered the following two problems when trying to start hdfs datanode:
1) If I used namenode service ip 10.100.220.223 as fs.defaultFS in core-site.xml for datanode. When datanode tried to register itself to namenode via rpc request, namenode got the wrong ip address for the datanode. Normally it should get the pod ip of the datanode, but in this case docker0 inet address of datanode host is reported to namenode.
2) in order to workaround this, I used namenode pod ip 10.20.96.4 in core-site.xml for datanode. This time datanode can't be started at all. The error info reports that "k8s_POD-2fdae8b2_namenode-controller-keptk_default_55b8147c-881f-11e5-abad-02d07c9f6649_e41f815f.bridge" is used as namenode host instead of the namenode pod ip.

I tried to search this issue over the network, but nothing helps me. Could you please help me out of this? Thanks.

**Comment by ztao1987** [comment]
I got explanation for case #1 from flannel community, it's mentioned that "Because namenode is accessed as a service, the connection goes through kube-proxy, so all connections are actually coming from it (and its connections bind to docker0 interface). I think it would be best to ask Kubernetes community for best practices for working around this problem.". So I am wondering if there is any workaround for this? Thanks.

**Comment by bgrant0607-nocc** [comment]
cc @zmerlynn

**Comment by bgrant0607-nocc** [comment]
Source IP masking is documented here:
https://github.com/kubernetes/kubernetes/blob/f430dc8ac8011f2584eeb06f0e423b1513042c02/docs/user-guide/services.md#shortcomings

But we should have a documented workaround, if there is one.

@thockin Will this still be a problem with the iptables implementation of kube-proxy?

**Comment by zmerlynn** [comment]
@ztao1987: I believe you are the same user that replied to this thread in google-containers?https://groups.google.com/forum/#!searchin/google-containers/hdfs/google-containers/P4uh7y383oo/9PcP_cGVuJgJ If so, it sounds like `--proxy-mode=iptables` worked for you?

**Comment by ztao1987** [comment]
@zmerlynn yes, it solves my problem

**Comment by zmerlynn** [comment]
Closing for now, thanks! I may follow up later to see how HDFS is going for you, though.
