### ISSUE TITLE
Stable release finder URL still reports v1.0.7

### ISSUE THREAD

**Issue by llarsson** [kubernetes/kubernetes#17105]
https://storage.googleapis.com/kubernetes-release/release/stable.txt

The above link, as of right now, reports v1.0.7 as the stable release, even though v1.1.1 came out two days ago. This caused me to experience #17104. Please fix.

**Comment by bgrant0607-nocc** [comment]
cc @ihmccreery @quinton-hoole

**Comment by quinton-hoole** [comment]
@llarson Mine says 1.1.1.  Web caching?

**Comment by ihmccreery** [comment]
@mikedanese fixed this yesterday.

The root cause was a change in our GKE rollout, (which is where we mark a release as stable,) and an oversight on my part.  The docs have been fixed; this shouldn't be a problem again.
