### ISSUE TITLE
Migration Guide for 1.0.x to 1.1.x ?

### ISSUE THREAD

**Issue by remoe** [kubernetes/kubernetes#17107]
I didn't found any migration guide from 1.0.x to 1.1.x. Is it backward compatible?

**Comment by remoe** [comment]
I've found this:

https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md#upgrades

So it should run?

**Comment by bgrant0607-nocc** [comment]
Yes, it's compatible.
http://kubernetes.io/v1.1/docs/admin/cluster-management.html

**Comment by bgrant0607-nocc** [comment]
In the future, please try stackoverflow:
http://stackoverflow.com/questions/tagged/kubernetes
