### ISSUE TITLE
The v1.1 of Kubernetes Installation for CentOS is point to v0.18

### ISSUE THREAD

**Issue by kevintsai** [kubernetes/kubernetes#17103]
Hi, I follow the document [1] to install the v1.1.1 which Kubernetes released the very nice new features and improvements [2].
The environment that I use is CentOS 7.1.
I found the virt7-testing is pointing to v0.18, and also I tried default repo is v1.0.3, 
 and virt7-docker-common-candidate repo is 1.2.0.alpha1.

I wonder whether CentOS users could have an official way to install the v1.1.1 by the yum?
Thanks.

References:
[1] https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/centos/centos_manual_config.md
[2] http://blog.kubernetes.io/2015/11/Kubernetes-1-1-Performance-upgrades-improved-tooling-and-a-growing-community.html

**Comment by nancykyo** [comment]
seems that the repo file hasn't been updated.

**Comment by bgrant0607-nocc** [comment]
We need to move this to an archive or delete it.

**Comment by bgrant0607-nocc** [comment]
cc @erictune

**Comment by erictune** [comment]
@coolsvap Are you still actively using Kubernetes on CentOS?  If so, what version are you running these days?

**Comment by coolsvap** [comment]
@erictune I can update the documentation

**Comment by erictune** [comment]
Thanks, @coolsvap, please do.

**Comment by erictune** [comment]
Fixed by #17308
