### ISSUE TITLE
RepackSubsets (endpoints) loses invalid subsets

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#17116]
If I submit an Enpoints object that has no addresses or notReadyAddresses (which is invalid and covered by validation), the whole subset gets silently dropped.

We should a) not do that and b) test for that.

**Comment by thockin** [comment]
@smarterclayton This is an interesting case.  We're calling repack to "canonicalize" the representation, but we're calling it from strategy.PrepareForCreate() which is BEFORE strategy.Validate(), but I really want to run it AFTER validation.  Consider that there is an error in validation - I might feed back field paths or indexes that don't match what the user gave us.

What think of a post-validation strategy hook "Canonicalize()" ?

**Comment by smarterclayton** [comment]
Or PostValidation?  Agree for the need, I don't care strongly on the name.

On Nov 11, 2015, at 9:08 AM, Tim Hockin <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> This is an interesting
case. We're calling repack to "canonicalize" the representation, but we're
calling it from strategy.PrepareForCreate() which is BEFORE
strategy.Validate(), but I really want to run it AFTER validation. Consider
that there is an error in validation - I might feed back field paths or
indexes that don't match what the user gave us.

What think of a post-validation strategy hook "Canonicalize()" ?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17116#issuecomment-155848683>
.

**Comment by thockin** [comment]
I think I'd rather not name hooks relative to each other, especially if
things like validation will eventually be versioned, which means it has to
change position anyway.
