### ISSUE TITLE
"kubectl proxy" could rewrite absolute URLs using session cookies

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#17115]
Springboarding off https://github.com/kubernetes/kubernetes/issues/17032#issuecomment-155622936: Right now, `kubectl proxy` (and the apiserver proxy) can't handle applications that do things like request absolute URLs in JavaScript. As more and more modern frameworks do this, this is going to limit the usefulness of the proxy. A proposal for a possibly evil way to handle this in `kubectl proxy`:
- For the API proxy alone (i.e. not the static content proxy): Responses get tagged with a session cookie that identifies the original URL, e.g. `/api/v1/proxy/namespaces/default/services/zeppelin`.
- For all incoming requests, we first check for a cookie and modify the request before it hits the mux, if it has a cookie and _isn't_ prefixed with `/api` (because the apiserver is doing rewrites here too, for good or ill). For the above cookie, we would prepend `/api/v1/proxy/namespaces/default/services/zeppelin` to the request.

I think the biggest wart on the solution is that on the client side it doesn't look it's possible to tell the difference between `/api/v1/proxy/namespaces/default/services/zeppelin` and, say, `/api/v1/proxy/namespaces/default/services/zeppelin/#/`, without hacking to hack the URL namespace (which seems kind of gross). The latter is an actual URL that Zeppelin redirects to almost immediately, so if you whack on your browser bar and end up saving that URL, it's certainly a valid use case.

I'm probably missing something obvious, and it's obviously not perfect, but I bet it solves #17032 and others we haven't seen yet.

cc @brendandburns @liggitt

**Comment by liggitt** [comment]
Hmm, not really a fan of the proxy trying to handle URLs statefully. A simple thing like having two browser tabs open would be enough to break this, and I think the complexity makes behavior harder to reason about.

**Comment by lavalamp** [comment]
Hopefully we will never have to do this.

**Comment by zmerlynn** [comment]
I don't see a way around it for some apps, to be honest. It's the best solution I've seen for Zeppelin so far, though I'm open to negotiating with their upstream.

**Comment by liggitt** [comment]
I think this goes beyond what a proxy should do. If there are headers we should be setting to help the backend app behave better, we could look into that, but making a proxy jump through hoops to support an advanced app that isn't proxy aware is not a good idea.

**Comment by lavalamp** [comment]
Unless we want to run such an app as a component of the cluster (e.g. logging/monitoring/etc), I think users should just make a service with a loadbalancer or whatever. Then there's no problems.

**Comment by zmerlynn** [comment]
@lavalamp: Whether `kubectl` provides it or we provide some sort of proxy add on (possibly not written here), customers are going to want this. Propping a external load balancer comes with a ton of cost, including trying to figure out how to auth the service, whereas right now with the proxy you can just create little walled gardens in your cluster that you can auth to with `kubectl`, which is super convenient, especially for things like "worker node status panels", etc, where you may not want to spend time exposing them.

**Comment by liggitt** [comment]
> ...little walled gardens in your cluster...

if no one else has access to anything in your cluster, that could work, but pod IPs can have visibility to other pods, right?

it sounded like port-forward worked better (actually exposed things at whatever context root they natively expected). I'd rather see work to support port-forward working against a service, than gyrations like this.

**Comment by zmerlynn** [comment]
I've seen numerous cases where people have wanted to either VPN or proxy everything in the cluster. I don't think that customers yet care that pods can interact with each other, though namespace network isolation would be awesome.

**Comment by lavalamp** [comment]
@zmerlynn A little pod that lets you VPN into the cluster's network sounds like a good solution for that, better than kubectl proxy.

**Comment by timothysc** [comment]
> A little pod that lets you VPN into the cluster's network sounds like a good solution for that, better than kubectl proxy.

Also seems generally useful...

**Comment by zmerlynn** [comment]
That's fine, if it can be made to generally work. I suspect VPN is actually much hard to make work in the general case, honestly.

**Comment by cmluciano** [comment]
Is this still relevant? I'm not sure if this is related to SIG-Network anymore.
