### ISSUE TITLE
Podmaster should be integrated into hyperkube

### ISSUE THREAD

**Issue by eliaslevy** [kubernetes/kubernetes#17117]
Podmaster is an integral component of a Kubernetes HA cluster.  It should be released within hyperkube along with other k2s components to ensure compatibility of releases and ease of set up.

**Comment by bgrant0607-nocc** [comment]
cc @mikedanese

**Comment by bgrant0607** [comment]
@mikedanese is working on eliminating podmaster.

**Comment by mikedanese** [comment]
Yup. https://github.com/mikedanese/kubernetes/tree/ha-controller-manager is functioning prototype. #16830 is the first piece.

**Comment by davidopp** [comment]
@mikedanese this is marked as 1.2 milestone. You had a rather long list of things remaining to do https://github.com/kubernetes/kubernetes/pull/16830#issuecomment-163060280 but AFAIK you haven't had a chance to do them yet (?). Should we bounce this issue to the next release?

**Comment by mikedanese** [comment]
This is done. It's integrated into controller manager and scheduler thus its in hyperkube
