### ISSUE TITLE
RegistryPullQPS should have a sane default

### ISSUE THREAD

**Issue by mattmoor** [kubernetes/kubernetes#17118]
We've seen several instances now where folks in a crash loop run afoul of GCR's Denial of Service limits (HTTP status: 429), due to a mix of pull policy (e.g. PullAlways) and no configured registry QPS throttle:
https://github.com/kubernetes/kubernetes/blob/bfc60709b1fe69d1d4509f5ba1c83156b84d5c33/cmd/kubelet/app/server.go#L225

There is the customer issue: The kubelet shouldn't eat through a user's QPS quota quite so readily.
There is the registry provider issue: The kubelet shouldn't (D)DoS registry hosts.

This is less of an issue for say GCR than it is for a user's `docker-registry` or DTR instance, which is significantly less HA.

A corollary to this: Does the kubelet do any backoff currently?

**Comment by mattmoor** [comment]
@dchen1107 @roberthbailey FYI

**Comment by dchen1107** [comment]
Which version of Kubelet? Kubelet 1.1 has image pulling backoff.

**Comment by dchen1107** [comment]
Also with Kubelet 1.1, we disabled concurrent docker pulling by default on kubelet too.

**Comment by roberthbailey** [comment]
This was seen with 1.0.x kubelets.
