### ISSUE TITLE
security improvement on restrictions on pod schema

### ISSUE THREAD

**Issue by jon-shanks** [kubernetes/kubernetes#17112]
Hi, 

As an organisation, we have a requirement to restrict what type of requests we want to handle in relation to the json schema someone will supply i.e. The admissioncontroller is already mitigating some parts of this i.e. resource limits etc. However, we also want to prevent people running containers in privileged mode or adding specific capabilities or perhaps mounting specific OS filesystems underneath. 

Some of this can be mitigated with selinux however, there is then a bigger overhead in managing the policies across clusters and it seems like the wrong place i.e. kubernetes has already accepted scheduling to container for it to then fail. When, we could prevent any scheduling at all by setting admission controls around the requests. We have a plan to mitigate it with a proxy in front currently, however, we are happy to contribute on this, however, if there is a proposal on this it would make sense if we did the work to be inline with your future proposal as oppose just meeting our requirement and it never get merged or accepted.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/7893 might be of interest

**Comment by bgrant0607-nocc** [comment]
Closing in favor of the ongoing discussion in #7893
