### ISSUE TITLE
Clean up code in reflector example

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#17120]
It's a little messy and hard to understand -- @jeffvance @jayunit100 are interested in this, I think.

**Comment by jayunit100** [comment]
yup, i had #15782 but now jeff will take over, goals

-  figure out how to test `Delete`, right now, the delete on the `downstream` source has no tested consequence.
- annotate the variables better in comments.
- conslolidate the asserted channel vals `"a","b","c"`

**Comment by jeffvance** [comment]
In Process this code block can be commented out with no negative impact on the test results:
...
} else {
                                // Update our downstream store.
                                //err := downstream.Delete(newest.Object)
                                //if err != nil {
                                //      return err
                                }
...

**Comment by pmorie** [comment]
@jeffvance Yeah, that block should either be killed or made meaningful in the context of the example.  I'm guessing it exists to present an example of writing logic around the event type.

**Comment by jayunit100** [comment]
I think Jeff is tied up with other stuff Paul. 

If you want to take this over then go for it I can help review ... Sounds ok Jeff?

**Comment by jayunit100** [comment]
And yeah definitely make that block useful or delete

**Comment by jeffvance** [comment]
I may have time to work on this. I'll let you know today or tomorrow.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.
