### ISSUE TITLE
Move Latency metric into retry block

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#17125]
The Latency metrics in request.go are occuring at too high a granularity. 

If they are only meant to measure the total time for request success (ignoring retries), we should comment them as such.

Otherwise, lets move them into the most granular part of the request() function, 

See #16271 for origin of this discussion.

**Comment by jayunit100** [comment]
cc @jeffvance 

Look at the comments in PR https://github.com/kubernetes/kubernetes/pull/16271/files , specifically, lets move Latency metric into the for loop.

**Comment by wojtek-t** [comment]
@jayunit100 - is this still an issue?
