### ISSUE TITLE
kubernetes.io/docs latest version link loses place

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#17129]
The link on the 1.0 documentation "View the latest version here" should point to the 1.1 version of the same page (if it exists). Currently, it just navigates to the root page (http://kubernetes.io/docs).

**Comment by timstclair** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/15893

**Comment by timstclair** [comment]
Closed the wrong issue. Sorry for the spam.

**Comment by janetkuo** [comment]
This is expected behavior, and http://kubernetes.io/docs should always redirect to the latest release (i.e. http://kubernetes.io/v1.1/). Are you not seeing it redirects to v1.1 docs?
cc @caesarxuchao

**Comment by timstclair** [comment]
What I meant is if I'm on (for example) http://kubernetes.io/v1.0/docs/user-guide/downward-api.html and click "View the latest version here" link, it should take me to http://kubernetes.io/v1.1/docs/user-guide/downward-api.html, not http://kubernetes.io/docs

**Comment by timstclair** [comment]
I have a fix, just cleaning it up.

**Comment by janetkuo** [comment]
@timstclair I see. Thanks for the upcoming fix.

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by brendandburns** [comment]
We also need to update the munger so that the github text doesn't refer to the 1.0 branch.

--brendan

**Comment by timstclair** [comment]
@brendandburns I think that's a different issue? Or is that somehow tied to this one? I think this issue is fixed.
