### ISSUE TITLE
Sort out $GOPATH dependencies in hack/* scripts

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#17139]
I notice that we could eliminate a ton of bash building logic if we just required people to set up their GOPATH correctly. That means:

1. Make a new GOPATH for kubernetes.
2. Your kubernetes source code is located at $GOPATH/src/k8s.io/kubernetes
3. You've run `godep restore`. (and re-run as necessary when deps change) (or you're willing to say `godep go build ...` everywhere.)

Anyone using tools for an editing environment has already done this or something equivalent, so this is not a burdensome requirement. I personally keep separate GOPATHs per project I work on and have scripts to switch between them.

In exchange for requiring this of people, we could start using ordinary build commands ("go build cmd/foo" or "cd cmd/foo; go build") instead of our e.g. "hack/build-go.sh cmd/foo".

At the moment, I want this to eliminate a bunch of bash in our hack/verify- and hack/update- scripts.

I'm not talking about changing the release build, which happens in a docker container. (We need to continue to not reuse any GOPATH there, to make sure the right deps are used.)

People that might care about this: @thockin @smarterclayton @wojtek-t

**Comment by wojtek-t** [comment]
I'm all for simplifying the scripts, but I'm not sure if you can get a lot out of the changes you're suggesting. 
Do you have any concrete examples of a script that can be simplified with the change you suggested?

**Comment by MHBauer** [comment]
Does the switch to `vendor/` help? #24242 and friends.

**Comment by thockin** [comment]
I think this is done
