### ISSUE TITLE
CronJob controller should use shared informers

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#17130]
All of these controllers follow the same basic pattern.

Internally, maintain a cache.Store of X.
Watch for changes to Y.
When Y changes to a GetThingThatManagesY

That last function is usually like:
store.GetPodControllers()

which does an O(N) search to find matching rc by namespace and label selector.

All of these controllers should use an IndexerInformer to at least filter first on namespace before O(N) search in that namespace for a match.

This can cause excessive CPU churn when running with large numbers of namespaces.

**Comment by soltysh** [comment]
@derekwaynecarr have you done some tests around it?

**Comment by bprashanth** [comment]
I though about making the Informer more flexible when it came to type of store/index etc but punted pre 1.0 because I didn't actually witness any cpu churn when i rewrote the rcs. Don't deny that it might be time now.

**Comment by derekwaynecarr** [comment]
We have an index informer so it's a simple fix to update the controllers in
question.

When doing updates for quota controller here I just noticed these were
doing O(N) lookups that were unnecessary when an O(1) is possible.  With
20k projects/namespaces in an OpenShift deployment it would be a problem if
all controllers followed the same pattern.

https://github.com/kubernetes/kubernetes/pull/17133

I think it would show up in runs with larger numbers of single
app namespaces which I think we need to test more of since its a common
pattern for OpenShift, it's not a top priority but wanted the issue filed
as technical debt so other controllers do not continue the bad pattern in
copy/paste, and so I don't forget.

I will send some PRs in the next week to address each in turn.

**Comment by mqliang** [comment]
I sent a PR to add namespace index for Replication. Benchmark shows it can improve the look up efficiency about 2 times with 100 namespaces( each with 10 RCs each with 10 pods), and about 20 times with 1000 namespaces( each with 10 RCs each with 10 pods).

If it look good, I am glad to send a PR to add namespace index for Job & DaemonSet

**Comment by kargakis** [comment]
All of these controllers are using shared informers today. Only the cronjob controller is still using clients. @soltysh @janetkuo is there an issue for switching the CJ controller to use shared informers? If not, we can keep track of that change here.

**Comment by soltysh** [comment]
There is none, let's keep thus one in. I have a plan how to switch to
informers, but I doubt I will manage to make it happen for 1.7.

On Apr 25, 2017 7:44 PM, "Michail Kargakis" <notifications@github.com>
wrote:

All of these controllers are using shared informers today. Only the cronjob
controller is still using clients. @soltysh <https://github.com/soltysh>
@janetkuo <https://github.com/janetkuo> is there an issue for switching the
CJ controller to use shared informers? If not, we can keep track of that
change here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17130#issuecomment-297109639>,
or mute the thread

**Comment by kargakis** [comment]
Updated the title of the issue

**Comment by soltysh** [comment]
I'm tentatively adding 1.10 milestone, I'd like to see this being addressed and I'm hoping to start working on this withing this timeframe.

**Comment by wanghaoran1988** [comment]
@soltysh Did you start working on this? I'm glad to help if you don't have time doing this.

**Comment by jberkus** [comment]
@soltysh @wanghaoran1988 there hasn't been any activity in this issue.  Do you expect to get it done in the next 5 days?  If not, please bump it to 1.11.  Thanks!

**Comment by soltysh** [comment]
@jberkus @wanghaoran1988 it's targeted for 1.11.

**Comment by soltysh** [comment]
This won't happen in 1.11 definitely, moving to the next miletone.

**Comment by dims** [comment]
/milestone clear

@soltysh @derekwaynecarr Does this still need to be in v1.12? (does not look like it). Please re-add if needed

**Comment by tongchao199** [comment]
> All of these controllers are using shared informers today. Only the cronjob controller is still using clients. @soltysh @janetkuo is there an issue for switching the CJ controller to use shared informers? If not, we can keep track of that change here.

@soltysh @janetkuo @kargakis I have this problem now.
The cronjob controller queries the jobs in all namespaces through the client, which causes a slow log alarm for the etcd cluster。

* Print etcd cluster slow log alarm
```shell
Jan 20 19:40:09 etcd-ser01 etcd: read-only range request "key:\"/registry/jobs/65-ns/k8s-job-tdc6eu-1576247407339\\000\" range_end:\"/registry/jobs0\" limit:500 revision:1712050719 " took too long (117.960324ms) to execute
 ```

* View etcd connection on kube-apiserver
```shell
root@kube-master-ser01:~$ netstat -antp | grep 20994
tcp        0      0 xx.xx.128.58:20994      xx.xx.76.33:2379        ESTABLISHED 25969/kube-apiserve
```

* Capture packets on the kube-apiserver
```shell
root@kube-master-ser01:~$ tcpdump -v -i any -s 0 -w apiserver.pcap port 8080
 ```

* Capture packets on the etcd
```shell
root@etcd-ser01:~$ tcpdump -v -i eth0 -s 0 -w etcd.pcap port 2379
```

* Analyze packet log url information
```
root@kube-master-ser01:~$ grep limit=500 apiserver.log | cut -d '=' -f2 | cut -d '&' -f1 | while read line; do echo $line | base64 -D | grep k8s-job-tdc6eu-1576247407339 && echo $line; done
{"v":"meta.k8s.io/v1","rv":1712050719,"start":"65-ns/k8s-job-tdc6eu-1576247407339\u0000
eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6MTcxMjA1MDcxOSwic3RhcnQiOiI2NS1ucy9rOHMtam9iLXRkYzZldS0xNTc2MjQ3NDA3MzM5XHUwMDAwIn0
```

* Find cronjob controller invoke
![image](https://user-images.githubusercontent.com/18660867/73121655-5c666180-3fb7-11ea-9332-6c5bc162c631.png)
