### ISSUE TITLE
[ubuntu] kube-down gracefully 

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#17147]
kube-down should be conducted only after all of the resouces being deleted completely. Otherwise we would suffer 
```
$ rm -rf /var/lib/kubelet
rm: cannot remove ‘/var/lib/kubelet/pods/24c42a99-8818-11e5-b321-005056b45392/volumes/kubernetes.io~secret/default-token-t6sw8’: Device or resource busy
```

**Comment by resouer** [comment]
You mean we should `kubectl delete xxx --all` first?

**Comment by dalanlan** [comment]
We have done that, yet it takes time to finish, which we didn't take that into account.
That said, in most cases, especially there exist a large number of pods, things are not handled well.
I have a pr for this.
