### ISSUE TITLE
Upstream project node selector until #17097 is more general

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#17151]
Origin project node selector allows an admin to:

* guarantee non cluster-admin upods can NOT land on a subset of nodes unless the admin wishes it
* ensure a namespace is forced to land pods on a default set of nodes

Until initializers are possible, or LimitRange is more flexible #17097, admins cannot isolate pods away from infra by default.

Add an optional admission controller that uses a cluster default node selector, or looks for a namespace specific annotation, as the base node selector, and appends (or fails when conflicting) the pods selector onto that set.  Allows Origin to run on Kube

Example:

* admin wants to run cluster infra on the cluster.  They set cluster default to infra: false
* all namespaces now append infra: false to any pod node selector, or fail if the user sets infra: true
* admin sets annotation infra: true on default namespace, and creates pods that target infra: true automatically
* regular users still cannot target infra: true

Other examples include dev node labels, prod node labels, etc.

@derekwaynecarr discussed as a tactical path before initializers.

**Comment by derekwaynecarr** [comment]
I was going to do some R&D on initializers, but this seems more pressing.  Self assigning and when send a PR.

**Comment by derekwaynecarr** [comment]
@ncdc - I am going to pick this up as part of the r & d work we discussed today.

**Comment by bgrant0607** [comment]
@davidopp: Dedicated machines proposal.

**Comment by bgrant0607** [comment]
Where would the selector be put? LimitRange?

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by bgrant0607** [comment]
Let's say a particular namespace is forced to land on a set of machines. Do you also want to force all other namespaces to not land on that set of machines? That's a use case we have internally -- mutual exclusion. It's inconvenient (and impossible until more general selectors are implemented) to use nodeSelector for this. This is one use case for what we call *taints*, which have a repulsive effect unless they are explicitly *tolerated*. (I haven't filed a separate issue for that feature yet.)

**Comment by derekwaynecarr** [comment]
@bgrant0607 - the initial thought to get parity with downstream efforts in OpenShift was to do this via an annotation inspected during admission, but I agree that it has limitations around mutual exclusion.  I agree with mutual exclusion as being a desire.  I will have time to put some thoughts together on that later today / early next week.

**Comment by bgrant0607** [comment]
cc @mml

**Comment by smarterclayton** [comment]
We do that in the proposal with the global default - the global default can
force everyone away, and the namespace default can allow someone into a
subset of the reserved space (namespace default overrides global default).
Not the same as taints as I understand it, but instead about up-front
partitioning.

**Comment by bgrant0607** [comment]
See also #17190

cc @davidopp

**Comment by davidopp** [comment]
I'm never one to discourage expediency, but just be aware that
(1) we are planning to replace the current k/v-map based node selector with a more generic one at some point in the medium-term future, and move all current users of the map-based node selector over to it  (https://github.com/kubernetes/kubernetes/issues/341#issuecomment-154663349 ). This is similar to what we are already doing with PodSelector.
(2) we are planning to implement a general "dedicated machines" functionality that I believe would subsume what you described here (#17190, as @bgrant0607 mentioned)

My main concern is if you are proposing an API change that we will have to continue to support once we have the more general mechanisms in place (i.e. (2) above). Then again if we can translate it into the new stuff, it may not be hard to continue supporting it.

It will be easier to evaluate if you write a more detailed proposal of what you are proposing to do.

**Comment by smarterclayton** [comment]
It's not an API change.  It's just an admission controller that looks at
the namespace annotation that applies a defaulting behavior.  As an
admission controller it can be optional, solves real use cases in
production (today), and can be controlled by admins othogonally to future
changes.

There's not much more detail needed besides the description above, but I'll
rephrase the description.


On Nov 15, 2015, at 3:55 AM, David Oppenheimer <notifications@github.com>
wrote:

I'm never one to discourage expediency, but just be aware that
(1) we are planning to replace the current k/v-map based node selector with
a more generic one at some point in the medium-term future, and move all
current users of the map-based node selector over to it (#341 (comment)
<https://github.com/kubernetes/kubernetes/issues/341#issuecomment-154663349>
). This is similar to what we are already doing with PodSelector.
(2) we are planning to implement a general "dedicated machines"
functionality that I believe would subsume what you described here (#17190
<https://github.com/kubernetes/kubernetes/issues/17190>, as @bgrant0607
<https://github.com/bgrant0607> mentioned)

My main concern is if you are proposing an API change that we will have to
continue to support once we have the more general mechanisms in place (i.e.
(2) above). Then again if we can translate it into the new stuff, it may
not be hard to continue supporting it.

It will be easier to evaluate if you write a more detailed proposal of what
you are proposing to do.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17151#issuecomment-156791060>
.

**Comment by davidopp** [comment]
> It's not an API change.  It's just an admission controller that looks at
the namespace annotation that applies a defaulting behavior.  As an
admission controller it can be optional, solves real use cases in
production (today), and can be controlled by admins othogonally to future
changes.

That's clear enough; thanks.

**Comment by davidopp** [comment]
See #18261 and #18263.

**Comment by erictune** [comment]
IMO doing this in an admission controller is reasonable.
Suggest following approach:
- namespace has annotation with maximum permitted NodeSelector for pods in that namespace.
- NamespaceDefaultNodeSelector admission controller sets to the one from the annotation if none is specified.
- NamespaceAllowedNodeSelector admission controller denies admission to pods whose NodeSelector is not a subset of the maximum allowed for that namespace.

**Comment by bgrant0607** [comment]
Is anyone working on this for 1.2?

**Comment by ncdc** [comment]
We started, but priorities shifted. We can wait until after 1.2.

**Comment by davidopp** [comment]
FWIW NodeSelector and node affinity was merged today (#19758)

**Comment by davidopp** [comment]
FYI the Huawei folks are starting work on taints and tolerations now.
https://github.com/kubernetes/kubernetes/blob/master/docs/design/taint-toleration-dedicated.md
