### ISSUE TITLE
API Reference: shows "(VAR_NAME)" instead of "$$(VAR_NAME)"

### ISSUE THREAD

**Issue by orfjackal** [kubernetes/kubernetes#17155]
In <http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html#_v1_container> it reads `The $(VAR_NAME) syntax can be escaped with a double , ie: (VAR_NAME).` but it should read `The $(VAR_NAME) syntax can be escaped with a double $$, i.e. $$(VAR_NAME).`

**Comment by bgrant0607-nocc** [comment]
Needs to be quoted in the comment:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L779
Or we need to add an auto-munger for this.
cc @pmorie

**Comment by thockin** [comment]
of curiosity I tried quoting it in the comments, but it still did not regenerate with the $ characters. 

The `types_swagger_doc_generated.go` is already correct (has all the $ characters) - it's the conversion to HTML that is dropping them, and it is only $$ that are affected.

@caesarxuchao

**Comment by caesarxuchao** [comment]
Thank you @orfjackal for catching this. It turns out `$$` has special meaning in asciidoc (search `Double dollar enclosure asciidoc`). Because we convert our swagger spec to asciidoc and then to html, the `$$` is lost when converted to html. I'm sending patches.
