### ISSUE TITLE
Cannot create rc: no nodes available to schedule pods!

### ISSUE THREAD

**Issue by shenshouer** [kubernetes/kubernetes#17154]
when I exec `kubectl create -f rc-nginx.yaml`,  all the status of pod is `Pending `, and got scheduler event :`no nodes available to schedule pods`
The version is v1.1.1 and coreOS 766.5.0
the status of nodes is:
<pre>
core@core-1-85 ~ $ kubectl get node
NAME         LABELS                              STATUS    AGE
10.12.1.89   kubernetes.io/hostname=10.12.1.89   Ready     16m
10.12.1.90   kubernetes.io/hostname=10.12.1.90   Ready     5h
10.12.1.92   kubernetes.io/hostname=10.12.1.92   Ready     5h
10.12.1.93   kubernetes.io/hostname=10.12.1.93   Ready     5h
10.12.1.94   kubernetes.io/hostname=10.12.1.94   Ready     5h
10.12.1.95   kubernetes.io/hostname=10.12.1.95   Ready     5h
10.12.1.96   kubernetes.io/hostname=10.12.1.96   Ready     5h
10.12.1.97   kubernetes.io/hostname=10.12.1.97   Ready     5h
10.12.1.98   kubernetes.io/hostname=10.12.1.98   Ready     5h
</pre>
the status of pod I create in rc is :
<pre>
core@core-1-85 ~ $ kubectl get po -o wide
NAME             READY     STATUS    RESTARTS   AGE       NODE
my-nginx-0hs1v   0/1       Pending   0          15m
my-nginx-308o1   0/1       Pending   0          15m
my-nginx-42q61   0/1       Pending   0          15m
my-nginx-56868   0/1       Pending   0          15m
my-nginx-bdb3s   0/1       Pending   0          15m
my-nginx-d6ftq   0/1       Pending   0          15m
my-nginx-kdai3   0/1       Pending   0          15m
my-nginx-occe1   0/1       Pending   0          15m
my-nginx-xl9ou   0/1       Pending   0          15m
my-nginx-ztqiq   0/1       Pending   0          15m
</pre>
and I got the events :
<pre>
16m         16m        1         my-nginx         ReplicationController               successfulCreate        {replication-controller }   Created pod: my-nginx-0hs1v
16m         16m        1         my-nginx         ReplicationController               successfulCreate        {replication-controller }   Created pod: my-nginx-bdb3s
16m         16m        1         my-nginx         ReplicationController               successfulCreate        {replication-controller }   Created pod: my-nginx-xl9ou
16m         16m        1         my-nginx         ReplicationController               successfulCreate        {replication-controller }   Created pod: my-nginx-occe1
16m         16m        1         my-nginx         ReplicationController               successfulCreate        {replication-controller }   Created pod: my-nginx-d6ftq
16m         16m        1         my-nginx         ReplicationController               successfulCreate        {replication-controller }   Created pod: my-nginx-56868
16m         16m        1         my-nginx         ReplicationController               successfulCreate        {replication-controller }   Created pod: my-nginx-ztqiq
16m         16m        1         my-nginx         ReplicationController               successfulCreate        {replication-controller }   Created pod: my-nginx-42q61
16m         16m        1         my-nginx         ReplicationController               successfulCreate        {replication-controller }   Created pod: my-nginx-308o1
16m         16m        1         my-nginx         ReplicationController               successfulCreate        {replication-controller }   Created pod: my-nginx-kdai3
16m         39s        56        my-nginx-d6ftq   Pod                                 failedScheduling        {scheduler }                no nodes available to schedule pods
16m         39s        56        my-nginx-ztqiq   Pod                                 failedScheduling        {scheduler }                no nodes available to schedule pods
16m         39s        56        my-nginx-56868   Pod                                 failedScheduling        {scheduler }                no nodes available to schedule pods
16m         38s        56        my-nginx-0hs1v   Pod                                 failedScheduling        {scheduler }                no nodes available to schedule pods
16m         38s        56        my-nginx-bdb3s   Pod                                 failedScheduling        {scheduler }                no nodes available to schedule pods
16m         38s        56        my-nginx-kdai3   Pod                                 failedScheduling        {scheduler }                no nodes available to schedule pods
16m         38s        56        my-nginx-occe1   Pod                                 failedScheduling        {scheduler }                no nodes available to schedule pods
16m         38s        56        my-nginx-308o1   Pod                                 failedScheduling        {scheduler }                no nodes available to schedule pods
16m         38s        56        my-nginx-xl9ou   Pod                                 failedScheduling        {scheduler }                no nodes available to schedule pods
16m         38s        56        my-nginx-42q61   Pod                                 failedScheduling        {scheduler }                no nodes available to schedule pods
</pre>

who can help me?

**Comment by nancykyo** [comment]
I ran into same problem there. check your kube-scheduler process and log

`systemctl status kube-scheduler -l`
`journalctl -u kube-scheduler  -f`

**Comment by shenshouer** [comment]
I use the docker images about the api-server, kube-controller-manager and kube-scheduler which in v1.1.1 release kubernetes.tar.gz. I will check version .

**Comment by shenshouer** [comment]
@nancykyo Thank you very much !
I check the version about the container of kube-apiserver,kube-controller-manager and kube-scheduler and found the version about the image I used which docker load from the file kubernetes-server-linux-amd64.tar.gz in kubernetes.tar.gz is v1.0.7 . It does not match with the release version v1.1.1

So I suggest need explicit hint at here when the version is not right  and correct the docker image files in v1.1.1 release version.

**Comment by bgrant0607-nocc** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
