### ISSUE TITLE
Kubernetes.io shows generic snippet when posting in #Kubernetes-users slack

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#17150]
When pasting this URL into slack "http://kubernetes.io/v1.0/docs/user-guide/volumes.html#hostpath"

The snippet is not very useful. I would expect it to show a thumbnail that's more useful, or suppress the thumbnail. Can we update k8s.io to improve the snippet generation for our slack channel?

**Comment by aronchick** [comment]
@kubernetes/sig-docs-maintainers

**Comment by ahmetb** [comment]
Do you mind opening the issue on kubernetes.github.io repo instead?

**Comment by chenopis** [comment]
Yeah, if you open an Issue in the k8s.io repo and assign it to me, I'll try to fix it in Q3.

**Comment by ahmetb** [comment]
There's some info on how Slack unfurls URLs: https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

I'd say this is not too bad:

> ![image](https://user-images.githubusercontent.com/159209/27553447-b1f5a718-5a5f-11e7-8c01-2df5171e7ea9.png)

Maybe if we remove `<meta property="og:description" content="Production-Grade Container Orchestration" />`, this could help it gather some text from the detected content section of the page. Might be worth giving it a few tries through Netlify staging site.

**Comment by chenopis** [comment]
We should loop @steveperry-53 into this discussion.

**Comment by ahmetb** [comment]
For the record, I asked this at https://github.com/jekyll/jekyll-seo-tag/issues/219 but so far no luck.
