### ISSUE TITLE
Deployment status

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#17164]
Status:
* Number of pods of each version
* Number ready/not ready (should add to RC also)

cc @nikhiljindal @janetkuo @ironcladlou @ncdc

**Comment by bgrant0607** [comment]
And we still need to add a /status subresource.
https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go

**Comment by kargakis** [comment]
> And we still need to add a /status subresource.

There is already one
https://github.com/kubernetes/kubernetes/blob/912e54e4967e09787b5e8495b058d0e0ec50fd3a/pkg/master/master.go#L610
https://github.com/kubernetes/kubernetes/blob/912e54e4967e09787b5e8495b058d0e0ec50fd3a/pkg/registry/deployment/etcd/etcd.go#L104-L116

**Comment by kargakis** [comment]
Why do we need to have the number of each version in the deployment status?

**Comment by bgrant0607** [comment]
@kargakis I agree that the number of pods of the latest revision is good enough, at least for now.

We also have available/unavailable.

We can make changes or add more based on user feedback.

Closing.
