### ISSUE TITLE
Noisy logs with latest github.com/golang/glog

### ISSUE THREAD

**Issue by onlyjob** [kubernetes/kubernetes#17162]
Almost every logged message is prefixed with `ERROR: logging before flag.Parse` if [github.com/golang/glog](http://github.com/golang/glog) is updated to the latest snapshot.
Apparently it is caused by https://github.com/golang/glog/commit/65d674618f712aa808a7d0104131b9206fc3d5ad which requires changes in Kubernetes...

**Comment by thockin** [comment]
I feel like we should move on from glog soon.  I've been looking at
https://godoc.org/gopkg.in/inconshreveable/log15.v2#pkg-index and I like
what I see.

**Comment by justinsb** [comment]
I found a workaround: call `goflag.CommandLine.Parse([]string{})`  This convinces goflags that we have called Parse, and suppresses the warning.

e.g.

```
	pflag.CommandLine.AddGoFlagSet(goflag.CommandLine)
	pflag.Parse()

	goflag.CommandLine.Parse([]string{})
```

**Comment by mfischer-zd** [comment]
@thockin a great reason not to use glog is that it's not rotation safe.  it never checks the inode of the underlying log file to see if it needs to reopen the file.

**Comment by thockin** [comment]
We mostly glog to stderr anyway.

**Comment by thockin** [comment]
to be clear, I DO want to move to a structured logging answer.

**Comment by mfischer-zd** [comment]
Whatever you choose, make sure it's rotation-safe please =)

**Comment by paralin** [comment]
Did you guys ever decide what you wanted to use? :)

**Comment by kargakis** [comment]
@kubernetes/sig-scalability-misc

**Comment by justinsb** [comment]
We should presumably close this issue, which is about the now-fixed problem `ERROR: logging before flag.Parse`.  Alternatively, we could redirect this issue to be about a potential glog replacement.

**Comment by thockin** [comment]
glog replacement should be distinct

**Comment by eparis** [comment]
FYI I just merged https://github.com/spf13/pflag/pull/162 to pflag. Which automatically applies this hack to any golang flag set which was explicitly added to a pflag flagset.

**Comment by thockin** [comment]
Do we just need to revendor that to make this go away?
