### ISSUE TITLE
apiserver and kubelet don't agree on what names to use in TLS verification

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#17174]
The kubelet will generate its own self-signed TLS certificates if none exist, and it uses the public IP of the server as the identifier.

apiserver, however, will attempt connections using hostnames where possible. This can cause a mismatch, such as when using `kubectl exec`, where an error will be thrown in the form of:

```
Nov 12 19:49:42 master kube-apiserver[985]: E1112 19:49:42.117202     985 errors.go:62] apiserver received an error that is not an api.Status: x509: certificate is valid for 10.1.24.65@1446839265, not ip-10-1-24-65.us-west-1.compute.internal
```

The kubelet should probably attempt to determine its hostname via reverse lookup to generate its cert, or the two should know to do identity checks via IP address, so that this doesn't happen.

**Comment by bgrant0607-nocc** [comment]
I think you can use HostnameOverride to overcome this behavior:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L100

Reverse lookup might be useful in some environments.

**Comment by spzala** [comment]
@jcderr hi, it's been more than a year the issue was reported so a touch base. Is the use of HostnameOverride works for you? If it's not an issue anymore, can you please close it? Thanks!

**Comment by liggitt** [comment]
as of 1.5, the kubelet reports dns and ip addresses in node status, and places those in its serving cert as subjectAltNames, and the apiserver can select which node address it wants to use with `--kubelet-preferred-address-types`

**Comment by spzala** [comment]
@liggitt nice, thanks for the update and closing !!
