### ISSUE TITLE
Version API in swagger spec return type is void

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#17176]
https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/version.json#L12

Why is this void? Makes no sense.

**Comment by bprashanth** [comment]
@nikhiljindal

**Comment by paralin** [comment]
Same goes for the other GetAPIVersions calls.

Produced C# code is of type void:

https://github.com/paralin/KubeNET/blob/master/KubeNET/Swagger/Api/VersionApi.cs#L23

**Comment by nikhiljindal** [comment]
Yes. Return type for get code version endpoint is `version.Info`: https://github.com/kubernetes/kubernetes/blob/5c30f983d9c821b14899033241e9105aee15641a/pkg/version/version.go#L29

To fix it, we need to add Writes(version.Info) at: https://github.com/kubernetes/kubernetes/blob/5c30f983d9c821b14899033241e9105aee15641a/pkg/apiserver/apiserver.go#L173 (similar to: https://github.com/kubernetes/kubernetes/blob/5c30f983d9c821b14899033241e9105aee15641a/pkg/apiserver/apiserver.go#L243)

**Comment by Pensu** [comment]
Working on this, will send a PR if not done already.
