### ISSUE TITLE
Examples test should be able to test example files containing multiple resources

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#17179]
Follow up #14256

Examples test should be able to test files containing multiple resources (currently under examples/guestbook/all-in-one/). See https://github.com/kubernetes/kubernetes/blob/master/examples/examples_test.go#L168. 

cc @paralin @linzichang

**Comment by paralin** [comment]
Looking into it

**Comment by janetkuo** [comment]
@paralin Thanks! `ExtractList` might be helpful: https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/helper.go#L62-L89.

**Comment by linzichang** [comment]
Duplicate with https://github.com/kubernetes/kubernetes/issues/16444

**Comment by paralin** [comment]
Agreed on the duplicate

**Comment by janetkuo** [comment]
Thanks! Closing this.
