### ISSUE TITLE
unit flake: exec.TestSelectPlugin is flaky

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#17181]
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/1515/

**Comment by gmarek** [comment]
@brendandburns - does this still happen?

**Comment by thockin** [comment]
The jenkins log is long-since purged.  For future, if this happens again, please include the relevant snippets in the bug? 

I'll augment logs and PR it.

**Comment by thockin** [comment]
New logs are in.  Closing this.  Reopen if/when it reoccurs.

**Comment by goltermann** [comment]
Assuming @thockin meant to actually close this one.
