### ISSUE TITLE
Clarify (and perhaps loosen) our version-skew policy between master and Kubelet

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#17184]
Per #16961, it seems there are needs for running Kubelets at versions ahead of masters.  This is not currently recommended in [our versioning policy](https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md#upgrades).

There are a number of considerations here, (not the least of which is the feasibility of guaranteeing and testing version skews,).  This issue is meant to be a place to discuss community needs around master/Kubelet version skews.

(cc @bgrant0607, @brendandburns, @a-robinson, @zmerlynn)

From #16961, we've already seen:

@quinton-hoole:

> Agree on not supporting bidirectional version skews, unless someone comes up with a legitimate use case for that. My preference would be to eliminate version skew to the maximum extent possible (e.g. mandate a strict ordering of master upgrade before node upgrade, and restrict version skew in that case to a maximum of one minor version difference, purely to allow asynchronous upgrades). But there are currently legitimate use cases (e.g. GKE), where we need to support node updates that lag many versions behind master.

@aaronlevy:

> CoreOS currently ships the Kubelet as part of the OS image, and the scenario I was testing against is an updated kubelet (1.1) shipping with a new OS version, while the master components remain unchanged.
> 
> If this type of use case isn't supported, it means an automated global update of the kubelet in the OS image requires a manual step by all CoreOS/Kubernetes users. For example, all users would need to have updated their masters prior to the OS updating with a newer kubelet (and this is not possible to guarantee). Alternatively, it would mean CoreOS couldn't ship updates to the kubelet as part of the OS image.

@philips:

> I think a very reasonable use case for version skew is simply being able to roll back a cluster upgrade midstream. Imagine I upgrade to kubernetes 1.1 and then start upgrading my kubelets. Then I find that kubernetes 1.1 control plane has a bug/performance problem/etc and so I rollback to kubernetes 1.0 control plane until I can solve the issue in 1.1.
> 
> I agree we should minimize version skew but I think it is fairly practical to allow for rollback and compatibility on both sides of the system.

**Comment by bgrant0607** [comment]
Related: #4855

**Comment by bgrant0607** [comment]
It's unrealistic and somewhat dangerous to assume that Kubelets will never be ahead of the master, since latent bugs, especially workload-specific ones, can be exposed in any component at any time, and rolling back nodes is more disruptive than rolling back the cluster control plane.

**Comment by davidopp** [comment]
Could CoreOS ship with two versions of the Kubelet (let's call them the "old" version and the "new" version) and not activate the new version until the user has updated the master to the new version? The new Kubelet version would just be sitting on disk, waiting to be activated until the master version is upgraded. I assume you want the old and new version on disk anyway so you can do rollbacks.

**Comment by aaronlevy** [comment]
That is a possibility, but generally the roll-back mechanism would be to revert to the previous version of the OS itself. Also, given that this discussion was surfaced by a minor-version update (1.0-->1.1) that might eventually mean carrying 4 versions of the kubelet in the OS (last & current major/minor). More likely CoreOS would switch to making the kubelet available via signed image/container, and not ship it as part of the OS image.

**Comment by davidopp** [comment]
Bumping to next-candidate milestone since we didn't do anything on this for 1.2.
