### ISSUE TITLE
Exposing image information from node

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#17196]
Node should expose installed image information, so that scheduler can use that information to do better scheduling. 

cc/ @bgrant0607 @davidopp @kubernetes/goog-node

**Comment by davidopp** [comment]
ref/ #9044

**Comment by davidopp** [comment]
Can you explain what you mean by "better scheduling"? What rules would you like to see the scheduler apply?

**Comment by yujuhong** [comment]
I imagine scheduler would try to assign a pod to the node where the image already exists, to eliminate the pull time.

I think even today scheduler can get images from all pods assigned to the node, which gives it some information to go on, though not all.

**Comment by vishh** [comment]
@davidopp: Scheduler affinity towards nodes that have the the required images for a pod already pulled.
BTW, cAdvisor already [exposes images](https://github.com/google/cadvisor/blob/master/manager/manager.go#L111)

**Comment by davidopp** [comment]
Oh sorry, I mis-read the issue, I thought you meant docker version number. So nevermind my mentioning #9044.

Yes, I agree this is a good idea. I had also mentioned it here
https://github.com/kubernetes/kubernetes/issues/16466#issuecomment-154656277

**Comment by bgrant0607** [comment]
https://github.com/docker/swarm/tree/master/scheduler/filter#image-affinity

**Comment by davidopp** [comment]
> https://github.com/docker/swarm/tree/master/scheduler/filter#image-affinity

Note that the Docker thing is a hard requirement whereas what I believe is being proposed here is a preference (which I think makes more sense, at least to the extent that if you are only going to have one, the preference is more useful).

**Comment by resouer** [comment]
Will this `imageList` belong to the `nodeStatus` and updated frequently (like, whenever a new image is pulled)?

**Comment by resouer** [comment]
#18248 is in , I will write a priority considering data locality of image

**Comment by resouer** [comment]
@davidopp This is now implemented as a priority, do you think we should add a image locality predicate, like docker swarm did?

**Comment by yujuhong** [comment]
This is done.
