### ISSUE TITLE
[ubuntu] etcd error during upstart process

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#17205]
Since we have bumped etcd version to 2.2.1, there exists a problem with etcd when deploying the cluster [ubuntu]. 
I'm not positive whether it's fatal or not, and file this issue in case some one would love to pick it up. Or i'll follow this thread early next week. 

- Case 1
```
etcd start/running, process 336
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused

Error:  100: Key not found (/coreos.com) [10]
{"Network":"172.19.0.0/16"}
{"Network":"172.19.0.0/16"}
```
- Case 2
```
etcd start/running, process 425
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
Error:  100: Key not found (/coreos.com) [10]
{"Network":"172.16.0.0/16"}

```
For case 2, adding param `--no-sync` for `etcdctl` would fix this.

This may apply to all other platforms.

/cc @resouer  @WIZARD-CXY

**Comment by resouer** [comment]
I will test this in docker cluster, to see if it is ubuntu specific (not likely, to be honest)

**Comment by resouer** [comment]
@dalanlan I test it in etcd 2.2.1 with docker cluster, it works well

**Comment by dalanlan** [comment]
@resouer  The flags of `etcd` in docker-k8s are out dated. You might want to upgrade them. Ref https://github.com/coreos/etcd/blob/master/Documentation/configuration.md

**Comment by SunWeicheng0001** [comment]
I use ubuntu to deploy k8s, which came the same result. I use the script in cluster/ubuntu. All the thing are maintain default, except some configuration in cluster/ubuntu/config-default.sh
my deploy output is as follows
```
[sudo] password to start master: 
etcd start/running, process 21018
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
Error:  100: Key not found (/coreos.com) [17]
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
docker stop/waiting
docker start/running, process 21218
Connection to 192.168.1.46 closed.
Validating master
Validating weicheng@192.168.1.46
Using master 192.168.1.46
cluster "ubuntu" set.
user "ubuntu" set.
context "ubuntu" set.
switched to context "ubuntu".
Wrote config for ubuntu to /home/weicheng/.kube/config
... calling validate-cluster
Found 1 node(s).
./../cluster/../cluster/../cluster/../cluster/../cluster/../cluster/../cluster/ubuntu/util.sh: line 47: roles[${ii}]: unbound variable
```
Anybody know why?

**Comment by dalanlan** [comment]
@SunWeicheng0001  Please pull from HEAD. Stick to the doc.

**Comment by SunWeicheng0001** [comment]
@dalanlan I just pull from the HEAD, but it remains same... Is there any other problems?

**Comment by dalanlan** [comment]
@SunWeicheng0001  It's kinda odd that you suffer `unbound variable` & `non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379)` if you pull from HEAD 'cause i cannot reproduce this.

**Comment by SunWeicheng0001** [comment]
@dalanlan I replace the cluster folder with the one in branch release1.1, using the k8s binaries build by myself from HEAD and the etcd binaries downloaded by the script from HEAD, then the result is correct. 
It there any potential problem in cluster scripts from HEAD?

**Comment by dalanlan** [comment]
Sorry but i cannot quite catch you. It does have an issue(or issues), but obviously not this particular one.

**Comment by lingz** [comment]
I have the same problem @SunWeicheng0001 mentioned with basically identical console output. Any ideas?

**Comment by WIZARD-CXY** [comment]
@lingz I met the same problem today when deploying the 1.1.8 version k8s, but the k8s can still works fine

**Comment by robertBrem** [comment]
I have the same problem like **case 1** if I use Ubuntu 14.04.**3** LTS.  
With Ubuntu 14.04.**1** LTS it is working without any problems.

**Comment by robertBrem** [comment]
OK, the problem was not Ubuntu 14.04.3 LTS i think. :-)

The problem is that my hosting provider (Hetzner) does not include in eth0 in the vm. The vm is bridged. Therefore it is a problem inside the master with it's own public routable ip. This can't be resolved.
Perhaps somebody understands what I want to say :-) Im a dev and not very good in the ops field.

**Comment by mmkonrad** [comment]
@dalanlan In which file the "--no-sync" flag has to be set?

**Comment by dalanlan** [comment]
@mmkonrad `--no-sync` is a flag for `etcdctl` indeed.

**Comment by mmkonrad** [comment]
@dalanlan thx for reply.

Unfortunately this leads to Case 1..
`etcd start/running, process 2252
Error:  dial tcp 127.0.0.1:2379: getsockopt: connection refused
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}`

There is another issue concerning that on github: https://github.com/kubernetes/kubernetes/issues/19235
But all three solutions seem to be intended for Case 2.

Any suggestions?

**Comment by ziliu2020** [comment]
I’m having trouble to bring up Kubernetes cluster on ubuntu VMs.  I noticed you may have had the similar issue before.  Wondering if anyone can tell me how to fix it.  

Here is the message I had when doing kube-up.sh:

etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001).
Error:  client: no endpoints available
Error:  100: Key not found (/coreos.com) [15]

Here is the etcd opts I have in the utils.sh:  ${1} is replaced by my local VM eth2 ip address 10.12.24.247.

function create-etcd-opts() {
  cat <<EOF > ~/kube/default/etcd
ETCD_OPTS="\
 -name infra\
 -listen-client-urls http://127.0.0.1:4001,http://${1}:4001\
 -advertise-client-urls http://${1}:4001"
EOF
}

**Comment by mmkonrad** [comment]
@ziliu2020 do you have that problem on a local machine like e.g. your notebook where usually no restrictions exist or do you have it while using a cloud-provider like amazon ec2?

In the first case I succeeded with 2 ubuntu vms and all default settings except the no-sync flag. For the latter case I also found this function and adjusted the etcd-opts. But I still fail.

But I was able to follow this guide https://xelatex.github.io/2015/10/10/Flannel-for-Docker-Overlay-Network/ (but adjusted the addresses in the otps) and was able to create an etcd-cluster within amazon ec2 ubuntu instances that are located in a subnet in a vpc.

On one machine I was also able to create a flannel overlay network but with different parameters (these in the stated guide). But I haven't yet tested it with two machines....the overlay network has side-effects on lots of stuff including docker...especially when you are behind a proxy.

**Conclusion so far:** with proper parameters, set in the function you stated in your post, I figure that the flannel options are the actual problem here. Since I still fail when using proper settings that work when setting up an etcd-cluster natively...

I will continue to explore this tomorrow...

**Comment by ziliu2020** [comment]
I have two VMs running on two kvm hosts (local) that form a cluster.  It
looks like cluster seems to be up and running now even with the error
messages.   I'm just not sure whether it will cause any potential issues
later on.

Where should I add the no-sync?  It is option with etcdctl but I don't see
a file under kubernetes folder where etcdctl options are set.  I do see
opts for etcd from utils.sh.

Thanks for your response.

**Comment by mmkonrad** [comment]
@ziliu2020 There are two lines within this file: kubernetes/cluster/ubuntu/reconfDocker.sh that contain an etcdctl command. Put `--no-sync` both times directly after the word `etcdcl` and the error messages should disappear. At least they did for me, when setting kubernetes up on two local ubuntu-vms with vmware player.

On the other hand, the setup still fails when setting kubernetes up on ubuntu instances on aws. But as aforementioned I suspect the flannel-opts to be part of the problem.

What did you change to make it work (even with error-messages)?

**Comment by ziliu2020** [comment]
thanks for your info.  I made it work by doing sudo kube-up.sh.  without
non sudoers nodes can not be started.

**Comment by kant111** [comment]
@ziliu2020 can you please tell me how you solved the following error? I also filed a ticket in the link below.

Error:  100: Key not found (/coreos.com) [10]
{"Network":"172.19.0.0/16"}
{"Network":"172.19.0.0/16"}

https://github.com/kubernetes/kubernetes/issues/27240

**Comment by ziliu2020** [comment]
i just reinstalled it as root and everything worked fine then.  no matter
you use --no-sync or not, it's not important.  these warning msgs are not
critical and can be ignored.

**Comment by kant111** [comment]
reinstalled? I just downloaded the kubernetes binary release and changed some stuff in config-default.sh and got pretty far but unable to solve this error. so can give me more pointers?

**Comment by mmkonrad** [comment]
@kant111 What exactly have you changed within `config-default.sh`?

From the error message it might look like you changed some of the flannel configuration.
Afaik Flannel gets its configuration from etcd under the key `/coreos.com/network/config`.

Another reason might be, that etcd has some misconfiguration..

Therefore further details of what you've changed could help to locate the problem...

**Comment by kant111** [comment]
@mmkonrad There you go. I am copying and pasting the values I changed in my config-default.sh.

export nodes="kant@192.168.245.251" #ip of my local ubuntu machine (so one node)

# Define all your nodes role: a(master) or i(minion) or ai(both master and minion),
# Roles must be the same order with the nodes.
#roles=${roles:-"ai i i"}
export roles="ai"

# If it practically impossible to set an array as an environment variable
# from a script, so assume variable is a string then convert it to an array
export roles_array=($roles)

# Define minion numbers
#export NUM_NODES=${NUM_NODES:-3}
export NUM_NODES=1
# define the IP range used for service cluster IPs.
# according to rfc 1918 ref: https://tools.ietf.org/html/rfc1918 choose a private ip range here.
export SERVICE_CLUSTER_IP_RANGE=${SERVICE_CLUSTER_IP_RANGE:-192.168.3.0/24} 
# Flannel networking is used if CNI networking is not.  The following
# variable defines the CIDR block from which cluster addresses are
# drawn.
export FLANNEL_NET=${FLANNEL_NET:-172.16.0.0/16}

# Optionally add other contents to the Flannel configuration JSON
# object normally stored in etcd as /coreos.com/network/config.  Use
# JSON syntax suitable for insertion into a JSON object constructor
# after other field name:value pairs.  For example:
# FLANNEL_OTHER_NET_CONFIG=', "SubnetMin": "172.16.10.0", "SubnetMax": "172.16.90.0"'

export FLANNEL_OTHER_NET_CONFIG
FLANNEL_OTHER_NET_CONFIG=''

**Comment by uschtwill** [comment]
@kant111: If this is still an issue, check what the flanneld log at /var/log/upstart/flanneld.log says. For me, my vps had trouble setting up VXLAN as the backend for flannel, which made it fail continuously. The solution was to switch to a generic kernel.

**Comment by thelastworm** [comment]
Hello, I have the same issue 

in my flannel.log file says 

VXLAN init: operation not supported
Retrying in 1 second...
VXLAN init: operation not supported
Retrying in 1 second...
VXLAN init: operation not supported
Retrying in 1 second...

**Comment by uschtwill** [comment]
@thelastworm: Disclaimer: I am really not an expert at this. But check if you have the VXLAN kernel module set up, and if not, try to install it. If your case is like mine and your hosting provider's VPS use a custom kernel that have problems with handling kernel modules, switching to a generic kernel might be the solution.

Checking for kernel modules: http://www.cyberciti.biz/faq/howto-display-list-of-modules-or-device-drivers-in-the-linux-kernel/
Installing kernel modules: http://www.cyberciti.biz/faq/add-remove-list-linux-kernel-modules/

As for changing the kernel itself, doing `apt-get update; \
apt-get install --install-recommends \
  linux-image-4.4.0-34-generic \` and selecting 'Grub Bootloader' as the boot option in my VPS's web interface plus a reboot were enough.
