### ISSUE TITLE
Write a guide to writing a new scheduler

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#17208]
Once we make it possible for people to write new schedulers (#11793), we should write some guidelines/best practices for things people should do when they write a new scheduler. For example
- update the rescheduler
- back off trying to schedule a pod onto a node if kubelet keeps rejecting the pod from that node
- use our standard client code (like pkg/client/cache)
- use the library of kubelet predicates (#12744)
- https://github.com/kubernetes/kubernetes/pull/17197/files#r44845537
- etc.

We should probably also write a guide to how to write a new controller, which might have some overlap with a guide on how to write a new scheduler. We already have a very thorough guide to adding new API resources
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md

@lavalamp

**Comment by HaiyangDING** [comment]
+1 for this doc.

**Comment by lavalamp** [comment]
Scheduler is an "initializer", in that it sets a field under .spec after an object has been created. Controllers, by contrast, act on other objects, potentially updating the status periodically.

Both share use of watches--possibly over multiple resource types--they're basically the same other than the action(s) they perform.

So I agree that they should probably be covered in the same doc. Our current controllers are possibly slightly more advanced than our scheduler.

**Comment by davidopp** [comment]
@jdef I just remembered this issue; it's related to your suggestion at the scheduling SIG meeting to have something like a conformance test for new schedulers. We should probably just use this issue.

Just for posterity, the three things we discussed at the meeting were
* must use the predicate library that Kubernetes uses (#12744)
* must use standard set of non-predicate criteria https://github.com/kubernetes/kubernetes/issues/12744#issuecomment-156877624
(e.g. only consider pods with empty nodeName, don't consider pods marked unschedulable, etc.)
* must respect scheduler name annotation

**Comment by jdef** [comment]
Thanks for passing this along, David, as well as for summarizing the
discussion points from the SIG meeting.

**Comment by timstclair** [comment]
@timothysc

**Comment by timothysc** [comment]
I'm guessing we're going to want to write an sdk library + documentation.  Writing docs against the api itself for a scheduler will be error prone due to the constant subtle shifts in semantics.

**Comment by timothysc** [comment]
@davidopp are there work items we can complete as part of the 1.6 docs effort?

**Comment by davidopp** [comment]
I think our time would be better spent documenting how the default scheduler works. People who want to write their own scheduler will probably just copy the default scheduler and replace whatever parts they want to replace. So what they need is to understand how the default scheduler is structured, moreso than a "guide" to writing a new one.

**Comment by Yancey1989** [comment]
@davidopp +1

**Comment by spzala** [comment]
@davidopp hi David, since this seems a pure doc issue, should we close it here and open one against kubernetes.github.io to make it better visible to Doc team? - just a thought. Thanks!

**Comment by timothysc** [comment]
@spzala I'm ok with it.  Could you open and issue and cross link to this one please.

**Comment by spzala** [comment]
@timothysc very sorry, totally missed your comment earlier, and yes absolutely. Thanks!!

**Comment by davidopp** [comment]
sure

**Comment by spzala** [comment]
@davidopp @timothysc Hi, I have created this doc issue https://github.com/kubernetes/kubernetes.github.io/issues/4517 - hope it makes sense? Thanks!

**Comment by spzala** [comment]
@davidopp Thanks !!
