### ISSUE TITLE
Vagrant provider fails with 404 on fedoraproject.org/coprs

### ISSUE THREAD

**Issue by opyate** [kubernetes/kubernetes#17211]
Hello,

I'm trying the [vagrant provider](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/vagrant.md) walk-through, and start getting red output here:

```
==> master: --2015-11-13 10:52:41--  https://copr.fedoraproject.org/coprs/sgallagh/cockpit-preview/repo/fedora-21/sgallagh-cockpit-preview-fedora-21.repo
==> master: Resolving copr.fedoraproject.org (copr.fedoraproject.org)...
==> master: 209.132.184.54
==> master: Connecting to copr.fedoraproject.org (copr.fedoraproject.org)|209.132.184.54|:443...
==> master: connected.
==> master: HTTP request sent, awaiting response...
==> master: 301 Moved Permanently
==> master: Location: https://copr.fedoraproject.org/coprs/g/cockpit/cockpit-preview/repo/fedora-21/sgallagh-cockpit-preview-fedora-21.repo [following]
==> master: --2015-11-13 10:52:42--  https://copr.fedoraproject.org/coprs/g/cockpit/cockpit-preview/repo/fedora-21/sgallagh-cockpit-preview-fedora-21.repo
==> master: Connecting to copr.fedoraproject.org (copr.fedoraproject.org)|209.132.184.54|:443...
==> master: connected.
==> master: HTTP request sent, awaiting response...
==> master: 404 NOT FOUND
==> master: 2015-11-13 10:52:43 ERROR 404: NOT FOUND.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

The fedoraproject.org links are 404, so I'm wondering if I can hack in an alternative (and if so, which?), or if it's just a case of trying again later.

**Comment by enricomingardo** [comment]
Could this issue be related  to https://github.com/saltstack/salt/issues/28142 ?

**Comment by opyate** [comment]
I dug around on Fedora COPRS, and found [an alternative cockpit preview](https://copr.fedoraproject.org/coprs/g/cockpit/cockpit-preview/repo/fedora-21/msuchy-cockpit-preview-fedora-21.repo), then modified `kubernetes/cluster/vagrant/provision-master.sh` to point to it.

It seems to work, so if the `msuchy` preview is verified, I'm happy to send a PR.

**Comment by opyate** [comment]
@enricomingardo I've worked around the immediate 404 problem, but might be going down the wrong path. My 2 VMs came up with no k8s services started, so it might be part of the larger problem which you alluded to.

**Comment by enricomingardo** [comment]
The alternative repo has a wrong char in header: @
I'm trying this workaround:

```
# Enable Fedora Cockpit on host to support Kubernetes administration
# Access it by going to <master-ip>:9090 and login as vagrant/vagrant
if ! which /usr/libexec/cockpit-ws &>/dev/null; then

  pushd /etc/yum.repos.d
    # wget https://copr.fedoraproject.org/coprs/sgallagh/cockpit-preview/repo/fedora-21/sgallagh-cockpit-preview-fedora-21.repo
    wget https://copr.fedoraproject.org/coprs/g/cockpit/cockpit-preview/repo/fedora-21/msuchy-cockpit-preview-fedora-21.repo
    sed -i'' 's/\[\@/\[/' msuchy-cockpit-preview-fedora-21.repo
  popd

  yum install -y yum-utils socat
  yum clean all
  yum install -y cockpit
  rpm -Uvh --nodeps `repoquery --location cockpit-kubernetes`

  # yum install -y cockpit cockpit-kubernetes

  systemctl enable cockpit.socket
  systemctl start cockpit.socket
fi
```

**Comment by enricomingardo** [comment]
It doesn't works, but Why do you have closed this issue?

**Comment by opyate** [comment]
Re-opened. I thought I found a work-around by pointing to another COPR, but presumably the original was baked specifically for this demo.

**Comment by enricomingardo** [comment]
@opyate the original repo seems now running:
https://copr.fedoraproject.org/coprs/sgallagh/cockpit-preview/repo/fedora-21/sgallagh-cockpit-preview-fedora-21.repo

**Comment by jlowdermilk** [comment]
cc @derekwaynecarr

**Comment by davidopp** [comment]
Is this still not working?

**Comment by enricomingardo** [comment]
now i've this problem:
<img width="1047" alt="kubernetes-master google chrome oggi at 09 44 36" src="https://cloud.githubusercontent.com/assets/912728/11437448/1a932e96-94ee-11e5-9042-e003a8667d84.png">

**Comment by tedstirm** [comment]
@enricomingardo  I was seeing that before as well. Check to see if Fedora Cockpit is trying to access /api/v1beta3/watch. If it is then the issue you are seeing is probably related to https://github.com/kubernetes/kubernetes/issues/17598
