### ISSUE TITLE
Figure out the purpose/necessity of APIGroupVersion.ServerGroupVersion

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#17218]
See https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/apiserver.go#L96.  (It was `APIGroupVersion.ServerVersion` before).  It seems like those values should always be unversioned.

Spawned from: https://github.com/kubernetes/kubernetes/pull/17175/files#r44783763

@liggitt @caesarxuchao

**Comment by smarterclayton** [comment]
I have it to control meta server API versioning.
