### ISSUE TITLE
There should be a SecurityContext component of PodStatus

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#17223]
There should be a `SecurityContext` component of `PodStatus` that communicates the effective SELinux context of a pod / container.  

@pweil- @bgrant0607 @smarterclayton @swagiaal

**Comment by smarterclayton** [comment]
Can't it change over the lifetime of the process?

**Comment by pmorie** [comment]
@smarterclayton The one way it could change, I suppose, is if you let the container runtime allocate an MCS label -- you might get a different label across restarts.

**Comment by smarterclayton** [comment]
What if the container process itself changes uids?  Or labels?

On Nov 14, 2015, at 2:31 PM, Paul Morie <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> The one way it could
change, I suppose, is if you let the container runtime allocate an MCS
label -- you might get a different label across restarts.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17223#issuecomment-156738682>
.

**Comment by pmorie** [comment]
My bad, I've had tunnel vision on selinux.

**Comment by kargakis** [comment]
@pmorie @smarterclayton is there a SIG where SC falls under? node? auth?

**Comment by spzala** [comment]
@pmorie Hi Paul, a gentle touch base, the issue is last discussed an year ago and based on your last comment in the issue I wonder if this is still a valid issue or should we close it? Thanks!
