### ISSUE TITLE
Zeppelin image is huge

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#17231]
The `gcr.io/google_containers/zeppelin` image added by #17025 is over a gig. Investigate how to trim this down. (Cut out interpretters? Make them more modular somehow, possibly composing them once we have some solution like #831?) It's not even clear there's upstream support for making this more modular, though.

**Comment by zmerlynn** [comment]
cc @timothysc @kubernetes/sig-big-data

**Comment by timothysc** [comment]
remove mvn tooling and all the extra steps.

**Comment by zmerlynn** [comment]
@timothysc: I can look at that, but I think I can actually just strip the image of the dev tooling right now. Right now I think the Zeppelin deps themselves are a ridiculous portion of this, though. (I'll poke at it.)

**Comment by mattf** [comment]
```
$ docker history gcr.io/google_containers/zeppelin                 
IMAGE               CREATED             CREATED BY                                      SIZE                 COMMENT
...
1) 9e219a5f3ea9        3 days ago          /bin/sh -c cd /opt/zeppelin &&   mvn clean pa   1.164 GB             
...
2) 25cc5963c671        3 days ago          /bin/sh -c apt-get update   && apt-get instal   202.1 MB             
...
3) d63502d4fbd8        3 weeks ago         /bin/sh -c apt-get update && apt-get install    122.2 MB             
...
```
(3) is an install of [bzr git mercurial openssh-client subversion] in the base java image, which seems wasteful to me. you'll have to switch base images to get rid of this.
(2) is your install of [curl net-tools build-essential git wget unzip python python-setuptools python-dev python-numpy libfontconfig]. i expect curl is at least redundant, as is git if your using the java image. you should merge this layer w/ (1) and do an uninstall of [python-setuptools python-dev etc] & deps at the end.
of course, those are less significant than (1), which is the mvn build. the long term solution here is to use the upstream binaries, when they exist. in the meantime, you should clone zeppelin into tmp, copy out the resulting build artifact and delete the clone. that should at least cut the size of this layer in half, as all the intermediate build artifacts are likely still present and in the final tarball/jar.

**Comment by zmerlynn** [comment]
I can trim it down some by cutting out the build machinery (and I'll put up a PR shortly), but here's what the `.tgz` looks like:

```
-rw-r--r-- 1 zml eng 480M Nov 14 15:24 zeppelin.tgz
```

And expanded:
```
987e5d0d85925015721bc7103   7 minutes ago       /bin/sh -c #(nop) ADD file:8a1f8f82da0d9b00e0fe1f26594973e922335fb0afcf91882a6376c0a9f77a70 in /opt/           
                                                                                                                                                               
                                                                                                                       560.6 MB
```

(Instead of just deleting, it's actually easy to build, copy out, compose, too.)

**Comment by drocsid** [comment]
Is it me or are all the containers rather large. For example, does spark itself need to be a gig?
gcr.io/google_containers/spark            1.5.1_v3             c5b3aa1efb63        6 weeks ago         989.7 MB

There's some spark binary package that's 73M uncompressed: 
http://d3kbcqa49mib13.cloudfront.net/spark-1.6.1.tgz

**Comment by timothysc** [comment]
Java runtime + baseimage + transitive closer is what is causing most of the bloat.  But as we have discussed on other tickets, these images need to move out of the main repository.

**Comment by drocsid** [comment]
@timothysc I'm afraid I don't understand "transitive closer". For example I see my JDK is around 280M, and the Spark binary is 73M. Then that leaves another 636M for base + whatever. I guess I'll have to look at the imagelayers if I'm really curious.

**Comment by mattf** [comment]
@drocsid he means all the dependencies and their dependencies. if you'd like to tackle shrinking the spark image, please open an issue for it. we've done some work on this and you can use the example investigation above to help improve image sizes.
