### ISSUE TITLE
Be able to specify Job's deadline

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#17242]
This was came out from discussion between @pmorie and @sdminonne and was mentioned in https://github.com/kubernetes/kubernetes/issues/14186#issuecomment-155614590. I've been discussing this with @erictune later today and he agreed about bringing back the original idea from https://github.com/kubernetes/kubernetes/pull/11746 of having Job's deadline:
```
// Optional duration in seconds relative to the StartTime that the job may be active
// before the system actively tries to terminate it; value must be positive integer
ActiveDeadlineSeconds *int64
```
Additionally @bgrant0607 mentioned combining it with backoff [here](https://github.com/kubernetes/kubernetes/issues/14186#issuecomment-155686655).

Opinions?

@sdminonne if you're not working on it, I'm willing to take ownership over it.

**Comment by soltysh** [comment]
One thing I didn't mention is, after reaching the deadline, the job would be marked as failed.

**Comment by bgrant0607** [comment]
Note: If we eventually add a way to keep the Job inactive (e.g., initializers #3585), then the clock should only start once the Job becomes active.

**Comment by sdminonne** [comment]
@soltysh no problem :) enjoy

**Comment by bgrant0607** [comment]
Re. backoff: Restart/replacement backoff + a deadline was suggested as an alternative to terminating a job after a specific number of failures. Failures tend to be bursty and it's very difficult to reliably distinguish races and infrastructure failures from user error and broken applications, so assigning a fixed failure limit doesn't work well in practice. OTOH, jobs of bounded duration frequently do have a useful shelf life. Simply gracefully slowing down restarts of failing pods and allowing the deadline to kill the job leaves plenty of room for users to build their own arbitrary complex termination logic in higher-level workflow tools/systems if they want the jobs killed sooner.

**Comment by resouer** [comment]
cc @resouer

**Comment by soltysh** [comment]
@bgrant0607 ok I'll work on adding the back of as next step once the deadline PR is in. But this will be only applicable to RestartPolicyNever, which is the only tracking failures, others unfortunately don't. There's one other question, what should happen if backoff is specified without deadline? Or it's not expected and should fail validation? There's one other thought in my head regarding specifying the backoff as a percentage value, with this we could allow a job to recover. Eg. after reaching level x (I'm thinking about percentage value of failures vs successful), we'll start limiting the number of running instances, if a job recovers during that period and starts working stable, which will be indicated by increasing level of successful completions we could stop further backoff. Does this make sense, or it's too fancy and not needed at this point?

**Comment by bgrant0607** [comment]
@soltysh Backoff shouldn't be exposed in the API. It's an implementation detail. I wouldn't add it yet.

**Comment by soltysh** [comment]
OK, I'll wait with implementation until the right time comes ;)
