### ISSUE TITLE
RFE: ability to define special exit code to terminate existing job

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#17244]
This came out during my discussion with @erictune later today. Our current implementation of jobs assures we always restart pods to fulfill `JobSpec.Completions`. What if, at a certain point in time, we know the job won't be able to finish successfully ever. We should be able to mark the job for termination without actually removing it from the system, because we want to keep old data.
This might be very useful with ScheduledJobs (#11980). 

@pmorie @sdminonne wdyt?

**Comment by soltysh** [comment]
Such job would be marked as failed, in that case.

**Comment by bgrant0607** [comment]
Borg uses exit code 42. It's pretty confusing to silently do this. At minimum, I'd want the user to be able to specify what exit code to use.

Another option would be to use the termination message.

**Comment by bgrant0607** [comment]
Or to create a new "upward API" path just for this purpose.

**Comment by bgrant0607** [comment]
Kubelet would need to not restart OnFailure containers that used whatever mechanism was chosen.

**Comment by pmorie** [comment]
@bgrant0607 

> Another option would be to use the termination message.
>
> Or to create a new "upward API" path just for this purpose.

Did you have any ideas about what upward API would like?  Termination message seems like a natural channel to me, as well as exit code.  Termination message is probably more flexible and can carry any number of signals.

Thinking a little bit more about termination message, what if the termination message could contain a json/yaml object like so:

```yaml
apiVersion: v1alpha1
kind: UpwardAPIRequest
spec:
  terminateExistingJob: true
```

**Comment by bgrant0607** [comment]
Something like that. Maybe not the same file. I want it to be able to pass up a Reason and Message also

**Comment by bgrant0607** [comment]
Vaguely related: #1462

**Comment by erictune** [comment]
We could add a field  `.spec.container[].abortOnExitCode`, which is an integer in the 1-127 range.
When a container that specifies this field exits with this exit code, then the entire pod terminates abnormally regardless of the restart policy.

Communicating a reason/message upward is orthogonal: you might want to communicate a message any time a container exits, with or without this special exit code.

**Comment by soltysh** [comment]
That sounds reasonable, but this applies rather to kubelet interpreting return codes from running containers. Which not necessarily will address the original issue here. For your solution to work, you'd have to make sure the job knows what code to return to be terminated on demand and the pod to be terminated abnormally. I'd rather see an option to poke kubelet to terminate a running pod and terminate it with specified code/reason. @erictune does that sounds reasonable? Such option would also be perfect in the deadline PR I've submitted.

**Comment by pacoxu** [comment]
/sig apps
/triage accepted

I get back to this issue during bug scrub of sig-nod. @soltysh  Do we still need to think about this feature?

**Comment by gaocegege** [comment]
@pacoxu Hi Paco, I think we still need this feature. I am trying to use jobs to run distributed deep learning training jobs. In such a use case, we need to know if the failure can be fixed by retrying.

**Comment by alculquicondor** [comment]
@gaocegege, I'm revisiting this feature request again.

How do you determine which exit codes are acceptable to retry? Are these "retryable" exit-codes coming from the tensorflow framework?

We have a customer that would like to abort on any container error, which they consider "user error". But if the pod was killed due to Eviction or Shutdown, they would like retries. This is visible in the pod.status.reason. So the request is more about the "reason" than exit codes.

Can you clarify your expectations so we can find a solution that works for both requests?

**Comment by alculquicondor** [comment]
@soltysh, what was the usefulness of this below?

> I'd rather see an option to poke kubelet to terminate a running pod and terminate it with specified code/reason

Note that in 1.23+, we can issue a pod deletion from the job controller and the failure count won't be lost. So we have options today :)

I'm thinking that, even if the Pod has a restart policy `OnFailure`, the job controller can still inspect the exit codes and issue a pod deletion and terminate the job.

**Comment by gaocegege** [comment]
> How do you determine which exit codes are acceptable to retry? Are these "retryable" exit-codes coming from the tensorflow framework?

https://tldp.org/LDP/abs/html/exitcodes.html is referred.

**Comment by soltysh** [comment]
@alculquicondor honestly I don't recall that much into the past :wink: I think that the option to react to user-specified codes such that a single run or entire job would be considered a failed seems reasonable. 

All in all, I'm definitely :+1: if you're interested in working on in the near future.

**Comment by alculquicondor** [comment]
Here is my current thinking about this problem:

The requirement is to be able to declare a Job as failed on user errors (unknown command, crashes), but still be able to recreate pods if there is an infrastructure failure (VM preemption, OOM kill, kubelet eviction, kube-scheduler preemption).
When the current backoffLimit is reached, the controller terminates a job if such a number of failures is reached, regardless of the reason for the failure (user or infrastructure).
Open questions:
- Should the definition of infrastructure failure be internal to the job controller or should it be customizable by the API?
- Which information should be used to categorize an error: [.status.containerStatuses.state.terminated.exitCode](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#:~:text=containerStatuses.state.terminated.exitCode) or [.status.reason](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#:~:text=in%20this%20condition.-,reason%20(string),-A%20brief%20CamelCase)?
- How to interpret the Pod [restartPolicy](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#:~:text=restartPolicy%20(string))?
- How to interpret the backoffLimit? There are two possibly alternate interpretations:
  - Don’t count infrastructure failures towards the backoffLimit.
  - Certain failures mark a Job as failed, regardless of the backoff Limit.

**Comment by alculquicondor** [comment]
As usual, the devil is in the details. @mimowa and I will upload a proposal soon for kubernetes/enhancements#3329

**Comment by 0x2b3bfa0** [comment]
Vaguely related: [`jobs.<job_id>.strategy.fail-fast`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) on GitHub Actions.

**Comment by jensentanlo** [comment]
Hi @mimowo, I've been playing with the PodFailurePolicy and it's great, thanks for all of your hard work.

I've noticed an edge case when trying out the PodFailurePolicy example from Story 3 of the KEP. When a pod is marked as a DisruptionTarget but then completes successful, it retries anyways. I wasn't able to add some sort of Ignore rule to exclude the 0 case.

Here's a job that reproduces the issue 99% of the time

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      activeDeadlineSeconds: 60
      containers:
        - name: busybox
          image: busybox
          command: ["sleep", "1m"]
      restartPolicy: Never
  backoffLimit: 3
  podFailurePolicy:
    rules:
      - action: Count
        onPodConditions:
          - type: DisruptionTarget
      - action: FailJob
        onExitCodes:
          operator: NotIn
          values: [0]
```

**Comment by alculquicondor** [comment]
/close
With the feature already being beta, we can mark this issue as closed.

@jensentanlo could you create a new issue for what you hit?

My suspicion would be that the controller immediately creates a replacement pod when a pod has a deletion timestamp. But, once the pod actually finishes as succeeded, the controller would mark the job as succeeded and delete the extra pod.
