### ISSUE TITLE
Per-PR jenkins hits STATIC_ADDRESSES quota

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#17257]
The per-PR jenkins is hitting the resource quota quite frequently:

```
15:11:29 NAME                 ZONE          SIZE_GB TYPE   STATUS
15:11:29 pull-e2e-2-master-pd us-central1-f 20      pd-ssd READY
15:11:34 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
15:11:34  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
15:11:34 
15:11:34 Attempt 1 failed to create static ip pull-e2e-2-master-ip. Retrying.
15:11:43 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
15:11:43  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
15:11:43 
15:11:43 Attempt 2 failed to create static ip pull-e2e-2-master-ip. Retrying.
15:11:44 Created [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/global/firewalls/pull-e2e-2-master-https].
15:11:44 NAME                    NETWORK             SRC_RANGES RULES   SRC_TAGS TARGET_TAGS
15:11:44 pull-e2e-2-master-https pull-e2e-parallel-2 0.0.0.0/0  tcp:443          pull-e2e-2-master
15:11:57 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
15:11:57  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
15:11:57 
15:11:57 Attempt 3 failed to create static ip pull-e2e-2-master-ip. Retrying.
15:12:16 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
15:12:16  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
15:12:16 
15:12:17 Attempt 4 failed to create static ip pull-e2e-2-master-ip. Retrying.
15:12:41 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
15:12:41  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
15:12:41 
15:12:41 Attempt 5 failed to create static ip pull-e2e-2-master-ip. Retrying.
15:13:10 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
15:13:10  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
15:13:10 
```

**Comment by saad-ali** [comment]
Lots of recent PRs have run into this, examples:
* kubernetes-pull-build-test-e2e-gce/16373
* kubernetes-pull-build-test-e2e-gce/16372
* kubernetes-pull-build-test-e2e-gce/16370
* kubernetes-pull-build-test-e2e-gce/16368
* kubernetes-pull-build-test-e2e-gce/16367
* kubernetes-pull-build-test-e2e-gce/16366
* kubernetes-pull-build-test-e2e-gce/16365
* kubernetes-pull-build-test-e2e-gce/16364
* kubernetes-pull-build-test-e2e-gce/16362
* kubernetes-pull-build-test-e2e-gce/16361
* kubernetes-pull-build-test-e2e-gce/16360

Setting priority to P1

**Comment by saad-ali** [comment]
I ran `cluster/gce/delete-stranded-load-balancers.sh` against `kubernetes-jenkins-pull`.

It deleted stranded resources and freed up some quota.

The "kubernetes-jenkins-pull" project quota limits before:
* Firewall rules: 100 (97% used)
* Forwarding rules: 30 (100% used)
* Static IP addresses us-central1: 25 (100% used)
* Target pools: 50 (100% used)

The "kubernetes-jenkins-pull" project quota limits after:
* Firewall rules: 100 (88% used)
* Forwarding rules: 30 (87% used)
* Static IP addresses us-central1: 25 (72% used)
* Target pools: 50 (72% used)

That should help but until the source of the leak is identified, we'll likely hit the limits again. We can consider increasing the limits to match the `kubernetes-jenkins` project.

**Comment by nikhiljindal** [comment]
This is happening again: http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/20750/#

cc @k8s-oncall

**Comment by ixdy** [comment]
Closing as obsolete.
