### ISSUE TITLE
Flaky Service test in per-PR jenkins

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#17256]
Many recent per-PR builds failed with
Kubernetes e2e suite.Services should be able to change the type and nodeport settings of a service

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:600
Expected error:
    <*errors.errorString | 0xc208372080>: {
        s: "service mutability-service-test in namespace e2e-tests-services-e7rlf doesn't have a LoadBalancer ingress point after 1200.00 seconds",
    }
    service mutability-service-test in namespace e2e-tests-services-e7rlf doesn't have a LoadBalancer ingress point after 1200.00 seconds
not to have occurred
```

E.g., all the yellow builds between kubernetes-pull-build-test-e2e-gce16325 to 16335
Note that the timeout is really high (20 minutes), so the failed tests slows down the processing of jenkins queue.

**Comment by sttts** [comment]
Found some more PRs blocked by this: #16034 #16256

**Comment by sttts** [comment]
Something infrastructure related it seems. Even old PRs fail (which were green before).

**Comment by lavalamp** [comment]
I will take no further updates to mean it was indeed resolved by fixing leakage?
