### ISSUE TITLE
Abstract ExtractParams in kubectl/run for generators to share common parameter parsing

### ISSUE THREAD

**Issue by WeixuZhuang** [kubernetes/kubernetes#17258]
kubectl/run.go has a TODO in line 292, 133 which wants to 
'abstract this logic so that multiple generators can handle env in the same way. Same for parse envs.'

This changeset creates a common ExtractParams which shares the common parameter parsing logic for env and args.

It ensures none of the unit tests or system tests would be broken by this change.

**Comment by WeixuZhuang** [comment]
Can this code piece be assigned to me. I have the patchset prepared. Thanks.

**Comment by bgrant0607** [comment]
@WeixuZhuang Are you still working on this?

**Comment by zwxzwx18** [comment]
I have already finished the code and it has been merged. Any question?

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc
