### ISSUE TITLE
[v1.1.1] kube-up could fail potentially on ubuntu 

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#17271]
It's a known issue 'cause by #17109, and fixed from HEAD by #17110.
`controller manager` fails to start in all of my own experiments.
Since v1.1.1 has been officially cut, we should clarify this, at least in the document.

This could apply to other platforms, in which cases `controller manager` and `api-server` are raised w/o  order.

**Comment by dalanlan** [comment]
Or we could change the workflow of deployment to fit v.1.1.1 in (sounds odd to me though).
WDYT?
/cc @resouer  @WIZARD-CXY

**Comment by WIZARD-CXY** [comment]
odd to me,too

**Comment by resouer** [comment]
Here's my thoughts:
1. Change the issue of this title, if it affects all providers.
2. Ask a owner to cherry pick #17110
3. Clarify this issue in the doc is enough

**Comment by dalanlan** [comment]
> 1. Change the issue of this title, if it affects all providers.

It could use extra work to figure out, 'cause it only affects those providers that do not take upstart order of `api-server` and `controller manager` into consideration.

>2. Ask a owner to cherry pick #17110

It's not that useful since v1.1.1 is officially released as i pointed out before. This one would suffer anyway.

**Comment by jlowdermilk** [comment]
Actually a cherry pick would be useful, as we still do patch releases for bugfixes every ~2wks or so. Proposed in #17322.
