### ISSUE TITLE
Ownership management of volumes should be idempotent

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#17281]
Currently the ownership management facility for volumes is not idempotent.  This presents problems for users that need specific permissions that are outside those we give to files in managed volumes.  This is actually a gap that we should work into the design document for ownership management.  The rules should be formalized as:

1.  Unless otherwise noted on a plugin-by-plugin basis, ownership management happens once
2.  Because of (1) if a user needs specific permissions, they can chmod/chown files however they like, within they capabilities they have to do so to allow thing such as:
  1.  Using specific permissions in volumes of pods that use `FSGroup` that are not the standard managed-ownership permissions
  2.  Removing the setgid bit from an ownership-managed volume
3.  Some volume types can opt out of these semantics; they will provide guidance on a plugin basis when they do so.  

The way this should work is:

1.  We should use a marker file similar to the 'ready' file we use for other volumes as a guard against doing repeat work.
2.  The marker file should live in the plugin's 'meta' directory (where we keep the 'ready' marker files)
3.  Volume plugins should be able to clear the marker file for management in their `Setup` method -- for volumes like downward API and config resource that will need to have management reapplied when the data they project into a volume changes

I think this dictates a design as follows:

```go
package volume

type Builder interface {
  // other methods omitted

  // GetMetaPath returns the path to the meta directory for this builder
  GetMetaPath() string
}
```

Builders must expose the path to the metadir so that the ownership management code can use it.  Both the ownership management and plugins can use the following utility methods to work with the marker files:

```go
package util

func SetManagedMarker(dir string) error {
  // similar to SetReady
}

func IsMarkedManaged(dir string) (bool, error) {
  // similar to IsReady
}

func ClearManagedMarker(dir string) error {
  // use your imagination
}
```

@thockin @vishh @saad-ali cc @kubernetes/rh-storage @kubernetes/rh-cluster-infra

**Comment by pmorie** [comment]
@swagiaal Also, AWS, GCE, etc, can have this meta directory regardless of what's in the volume.  Whatever the type of volume, the meta directory is on the node's storage, not the volume itself.

**Comment by pmorie** [comment]
@swagiaal 

> Secondly I would suggest that the interface of util be more generic so that we don't need functions for {Set,Get}{Managed,SELinuxLabeled,Ready}Marker

We can have private functions that the public ones call underneath, but I am wary of exposing this to volumes to use for a free for all.  I think we want to track any proliferation of these mechanisms in a way that calls out what they're being used for.

**Comment by thockin** [comment]
I don't like how informal this proposal is.  I don't want assumptions made
about files existing or not existing.  The plugin meta dir is the plugin's.

Don't we already assert idempotence in plugins by way of SetUp() returning
early?  Why not make SetUp() return a code that indicates "complete" vs
"idempotence short circuit" ?  Something like that.

**Comment by pmorie** [comment]
@thockin The volume plugins do this correctly, but the ownership management exists outside of any plugin.  I am happy to capture this in an update to the proposal so we can debate the merits that way -- I had planned to do that in the PR with the fix for this issue.

**Comment by swagiaal** [comment]
> If it lives on the node then a volume which has been chown'ed will get re-chown'ed when it attaches to a different node.

@pmorie what about the above ?

**Comment by pmorie** [comment]
Going to make a PR with additions to the proposal today.

**Comment by pmorie** [comment]
@swagiaal 

> If it lives on the node then a volume which has been chown'ed will get re-chown'ed when it attaches to a different node.

In that case, it's the exact same as if a new pod is scheduled onto the node, and the exact same as it would be today.

**Comment by thockin** [comment]
I'm re-reading and I still don't like this.

My point was that the volume itself knows if it is actually doing work or short-cutting for idempotence.  mountExternalVolumes() calls builder.SetUp() and then calls kl.manageVolumeOwnership().  Could we do something like:

```
        status, err = builder.SetUp()
        if err != nil {
            return nil, err
        }
        // If status was not PerformedSetUp, that means the volume short-circuited for idempotence.
        // In that case, we will skip ownership manageemnt.
        if status == volume.PerformedSetUp {
            if hasFSGroup &&
                builder.GetAttributes().Managed &&
                builder.GetAttributes().SupportsOwnershipManagement {
                err := kl.manageVolumeOwnership(pod, internal, builder, fsGroup)
```

**Comment by pmorie** [comment]
@thockin and I talked today and discussed externalizing idempotency checks and marker setting into `mountExternalVolumes`.  I need to continue thinking about the best factoring, but I think I'm onto something that will ring the bell.

**Comment by pmorie** [comment]
We designed out of this approach, see #18521
