### ISSUE TITLE
kubectl does not create new rcs, pods and services with Vagrant user

### ISSUE THREAD

**Issue by noralife** [kubernetes/kubernetes#17289]
I am running Kubernetes on VirtualBox.
In release 1.1.1, vagrant user cannot execute `kubectl create` command because of a permission problem.

Here is the execution log.

```
[vagrant@kubernetes-master guestbook]$ kubectl create -f redis-master-controller.yaml
error validating "redis-master-controller.yaml": error validating data: open /tmp/kubectl.schema/v1.1.1/api/v1/schema.json: permission denied; if you choose to ignore these errors, turn validation off with --validate=false
```

The file permission after installing Kubernetes 1.1.1 using `./cluster/kube-up.sh` is like

```
[vagrant@kubernetes-master kubernetes]$ ls -al /tmp/kubectl.schema/v1.1.1/api/v1/schema.json
-rw-------. 2 root root 446222 Nov 14 13:43 /tmp/kubectl.schema/v1.1.1/api/v1/schema.json
```

So current workaround is here but needs to be fixed in the future release.
```
[vagrant@kubernetes-master guestbook]$ sudo chmod 644 /tmp/kubectl.schema/v1.1.1/api/v1/schema.json
```

**Comment by jlowdermilk** [comment]
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
@noralife - I assume that if you interact with the vagrant cluster from your host directly you have no problem?

**Comment by noralife** [comment]
@derekwaynecarr 

I tested commands from my host directly and there is no permission error.
My usage of `kubectl` seems to be wrong.
Thank you for teaching me.

I don't know whether this ticket should be open or not.
Please kindly decide it.

**Comment by sdminonne** [comment]
@derekwaynecarr https://github.com/kubernetes/kubernetes/issues/17340 may be related

**Comment by derekwaynecarr** [comment]
Closing this issue, thanks!

**Comment by mikem** [comment]
Interacting with the cluster from my host directly doesn't appear to be an option if my cluster is on Azure. I can no longer follow the steps in [the `coreos/azure` getting started guide](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/azure/README.md) -- the `kubectl create -f ~/guestbook-example` step at the top of the [Deploying the workload](https://github.com/kubernetes/kubernetes/blob/229f40e69f99fe969a2900ec4a804da516631f33/docs/getting-started-guides/coreos/azure/README.md#deploying-the-workload) section fails.

What's the proper way to interact with my Kubernetes cluster deployed to Azure?
