### ISSUE TITLE
kube-foundry (kubernetes + cloud foundry)?

### ISSUE THREAD

**Issue by donghwicha** [kubernetes/kubernetes#17280]
I've been recently testing a fork of Cloud foundry, Stackato  but.. it is really similar to Kubernetes. 

Is there any movement to integrate kubernetes to cloud foundry? 
like a fork of cloud foundry which is based on kubernetes and all of the components is rewritten with go.

It would be great if cloud foundry can get advantages from Kubernetes for cluster management.

Anybody thinking about this?

**Comment by jlowdermilk** [comment]
To my knowledge there is no effort to fork cloud foundry on top of kubernetes; I'm not sure what the underlying framework is for Stackato, so not sure how much sense that makes. In any case, this is a discussion for which the [slack channel](https://kubernetes.slack.com/messages/kubernetes-dev/) would be better suited.

**Comment by donghwicha** [comment]
@jlowdermilk cool! I'll join it
