### ISSUE TITLE
[Proposal] Simply populate env from files in Pod

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#17293]
Copied from https://github.com/kubernetes/kubernetes/issues/4710#issuecomment-156758189
There's many requests in that thread asking for  publishing Pod env from [update] volume [/update] file/path

**Note**: this proposal does not mean to fix #4710 , 4710 is more complex.

If we do not want to make this non docker specific, we can simply add a pkg/util to load env from file, instead of using `docker --env-file`.

No sure if anyone against this, open for discussion.

**Comment by pmorie** [comment]
@resouer Do you imagine this being used with a file in a volume?

**Comment by resouer** [comment]
@pmorie Either in the volume, or in the docker image. I think.

**Comment by pmorie** [comment]
@resouer I don't think docker supports an env file that comes from the container's filesystem.  Correct me if I'm wrong.

**Comment by resouer** [comment]
@pmorie My bad. Just limit this to populate ENVs from a volume path. updated.

**Comment by thockin** [comment]
So you want to read a file from a volume and use that to populate envs for
a container?  Is that really what people are asking for?  It feels so
convoluted...

**Comment by resouer** [comment]
Close this, sorry for the noise. Focus on the original issue.
