### ISSUE TITLE
DaemonSets not available in api extensions/v1beta1 in Kubernetes v1.1.1

### ISSUE THREAD

**Issue by apatil** [kubernetes/kubernetes#17295]
Hi everyone, I'm running kube-apiserver v1.1.1, with argument `--runtime-config=extensions/v1beta1`. It looks like daemonsets should be API objects in extensions/v1beta1: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/types.go . However, the API server doesn't report them:

```bash
curl 127.0.0.1:8080/apis/extensions/v1beta1/
{
  "kind": "APIResourceList",
  "groupVersion": "extensions/v1beta1",
  "resources": [
    {
      "name": "horizontalpodautoscalers",
      "namespaced": true
    },
    {
      "name": "horizontalpodautoscalers/status",
      "namespaced": true
    },
    {
      "name": "ingresses",
      "namespaced": true
    },
    {
      "name": "ingresses/status",
      "namespaced": true
    },
    {
      "name": "jobs",
      "namespaced": true
    },
    {
      "name": "jobs/status",
      "namespaced": true
    },
    {
      "name": "replicationcontrollers",
      "namespaced": true
    },
    {
      "name": "replicationcontrollers/scale",
      "namespaced": true
    }
  ]
}
```

Also, I have some code written against the unversioned client that works with daemonsets, which worked with version 535246f3645de42a0adee9d532b422f9e6ce1a75 but doesn't work with v1.1.1.

Thanks!

**Comment by kevinliuzhong** [comment]
I met the same problem. @thockin

**Comment by nikhiljindal** [comment]
As per https://github.com/kubernetes/kubernetes/blob/master/docs/admin/daemons.md#caveats, you need to set ```--runtime-config=extensions/v1beta1/daemonsets=true``` to enable daemonsets.

**Comment by apatil** [comment]
Confirmed that that worked. Thanks for the help!
