### ISSUE TITLE
DaemonSet should not/currently cannot schedule pods on SchedulingDisabled nodes

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#17297]
Similar to #16105

In the GCloud deploy script the master appears as a SchedulingDisabled node. DaemonSet is attempting to schedule on this node, and spews out a ton of errors in the event log like so:

```
Error syncing pod, skipping: API error (500): Cannot start container 4fabe3c5a71f1d36972ab4a47da3748f92ef4812c54dc0d17b65ce6f860fa5de: no available ip addresses on network
```

This looks like a fairly critical bug to me.

**Comment by paralin** [comment]
cc @mikedanese @erictune @davidopp @bgrant0607

**Comment by mikedanese** [comment]
yup, makes sense. See https://github.com/kubernetes/kubernetes/pull/14054#issuecomment-144229094. @davidopp this has to do with the node configuration matrix we discussed last meeting.

**Comment by paralin** [comment]
Looks like a very good but complex solution to the problem. Maybe until that's ironed out we could prevent scheduling on SchedulingDisabled pods within DaemonSet as a temporary fix?

**Comment by mikedanese** [comment]
I see two ways we can quickly fix this:

1. Don't place DaemonSet pods on scheduling disabled nodes. What are the behavioral compatibility implications with this approach?
2. Give master container bridge a larger cidr ([here](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/configure-vm.sh#L579)) which fixes the ipallocation problem, but the master configuration is still unsuitable to run actual workload e.g. pod ips are not routable. This is not to say that running certain daemonset pods (like log shipping, monitoring) on the master would not be useful or valid.

**Comment by paralin** [comment]
I vote #1 for compat with existing clusters.

**Comment by davidopp** [comment]
I didn't look at the Kubelet code, but why is it giving that error message? SchedulingDisabled isn't something the Kubelet even knows about, IIRC.

BTW what pod is DaemonSet trying to schedule onto the master? I thought we weren't using DaemonSet for anything yet.

**Comment by paralin** [comment]
It's nothing internal, just the newrelic example I contributed a week ago that uses daemonsets.

**Comment by mikedanese** [comment]
@davidopp It's giving an error because we only allocate a /30 cidr (4 ips) on the master's container bridge. We could allocate more IPs and the problem error would go away.

**Comment by davidopp** [comment]
> It's giving an error because we only allocate a /30 cidr (4 ips) on the master's container bridge. We could allocate more IPs to the master kubelet's cidr and the ip allocation error would go away.

Oh right, that's what you were talking about with (2).

As you allude to, we just need something that's "good enough" until we implement the more flexible policies you mentioned ( https://github.com/kubernetes/kubernetes/issues/17297#issuecomment-156857375 ). On the assumption that we'll implement those policies before we have a burning need to run daemons on the master node, I think (1) is OK.
