### ISSUE TITLE
remove podmaster, vagrant-podmaster examples/

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#17301]
depends on  #16830 being merged and completed... 

Podmaster was a good start on how to do introspective HA, but looks like now  @mikedanese is working on an temporary Leader elector #16830 , that is native to kube daemons, and based  service endpoints + annotations, we will no longer need podmaster stuff.

cc @brendandburns @mikedanese 

Once 16830 is in, we can thus remove brendan's podmaster (i think in contrib now) as well as my some of the docs/examples high-availability notes which i had worked on a few months back.

**Comment by DanyC97** [comment]
is seems #16830 been merged hence this PR can progress ?
