### ISSUE TITLE
GCE e2e fail

### ISSUE THREAD

**Issue by zhengguoyong** [kubernetes/kubernetes#17312]
Now PR run GCE e2e, it will fail and no test result,
is it the k8s-bot problem?
please see #17311 
thanks.

**Comment by wojtek-t** [comment]
The issue is that we are leaking resources somewhere in our tests, and thus after some time we are exceeding the quota so that no new tests can be run.

@piosz @kubernetes/goog-testing

**Comment by piosz** [comment]
cc @saad-ali @brendandburns @ixdy @mikedanese

**Comment by piosz** [comment]
I removed all unused resources and Jenkins is working now. I'll re-run e2e for all LGTMed PRs. Though this is a temporary solution and we should find the source of leaks.

**Comment by zhengguoyong** [comment]
thanks all.

**Comment by piosz** [comment]
Closing the issue since the tests pass.
