### ISSUE TITLE
kubectl scale's replicas parameter should be renamed to something more generic

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#17313]
If I want to scale an object (currently supported are only rc and job) I'm calling:
```
kubectl scale --replicas=3 resource name
```
The parameter `--replicas=3` is perfectly fine for RC which use replicas to define their size, but for Jobs, not necessarily, since Jobs have parallelism. More resources might come in the future. Thus, I propose renaming this parameter to be more generic. Maybe size?
The same applies to current-replicas flag. 

@kargakis @deads2k @brendandburns thoughts?

**Comment by kargakis** [comment]
I'm fine with --replicas as long as it's well documented what happens when used against a job.

**Comment by bgrant0607** [comment]
size and count are the obvious options for something more generic. 

However, the command needs to accept existing flags for the foreseeable future. 

I would also like the name to match the Scale API, which currently uses replicas.

Do we need to be able to scale jobs right now?

**Comment by soltysh** [comment]
I totally agree this would rather be adding a new, generic flag for scaling every possible resource. For obvious reasons we need to keep backwards compatibility keeping the old flags around. The scale API already [uses](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/scale.go#L99-L107) `newSize`, unless you're taking about different part. That's why `size` seems to be most appropriate, imho.
Finally - yes, jobs already [scale](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/scale.go#L122), which results in modifying `spec.parallelism` parameter.

**Comment by kargakis** [comment]
Agreed with @bgrant0607 regarding this matching the scale api

**Comment by bgrant0607** [comment]
Scale API field:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/autoscaling/v1/types.go#L107

**Comment by soltysh** [comment]
If scale api already uses replicas, then I assume there's no point in changing that. I'm closing this issue.
