### ISSUE TITLE
pre-commit checks should run on clean copy of repo

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#17336]
It's far too easy to have the pre-commit check pass only due to uncommitted changes.

Also, because it takes so long, I have moved it from pre-commit to pre-push anyway.  I propose we run all the checks inside a docker container, and we build the docker tarball from a clean checkout of HEAD.  This will take a bit longer, but it would provide a more useful signal.

**Comment by mml** [comment]
I note that `git archive` can directly export into .tar or .tar.gz files.

**Comment by ihmccreery** [comment]
@mml sounds reasonable to me, though I'm wary of going out of our way to make Git do something unexpected.  As a developer, I tend to prefer the "standard" over the "correct", even if that means I have to `git stash` or something.  Can you point to other instances where something like this has been implemented, or perhaps some way that Git itself has solved this problem?

**Comment by mml** [comment]
@kubernetes/sig-testing-misc

**Comment by xiangpengzhao** [comment]
/sig contributor-experience
Since pre-commit is removed in #47673, we can close these pre-commit related stale issues.
/cc @thockin

**Comment by cblecker** [comment]
/assign
Yup, this is stale.

**Comment by xiangpengzhao** [comment]
xref: #15630 #11497 #25931
