### ISSUE TITLE
unit test TestGenericScheduler is flaky

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#17332]
This unit test has flaked several times recently on Kubekins, always with the same error:
```
generic_scheduler_test.go:301: Failed : test 2, Expected: machine1, Saw: machine2
```

I suspect #16647 may be a culprit, though I'm not 100% sure.

cc @abursavich @kubernetes/goog-testing @kubernetes/goog-control-plane @kubernetes/rh-cluster-infra

**Comment by wojtek-t** [comment]
Fixed by #17343
