### ISSUE TITLE
fluentd-es pod stuck pending on soak cluster

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#17339]
[kubernetes-soak-continuous-e2e-gce](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gce/) was happily running until yesterday when the fluentd-es pod on one node went pending and got stuck that way. I poked at the cluster but couldn't determine why it's stuck pending. As far as I can tell the minion is healthy and has available resources.

```
jenkins@jenkins-master:~/jobs/kubernetes-soak-weekly-deploy-gce/workspace$ kubectl describe pods fluentd-elasticsearch-gce-soak-weekly-minion-b2k0 --namespace=kube-system
Name:				fluentd-elasticsearch-gce-soak-weekly-minion-b2k0
Namespace:			kube-system
Image(s):			beta.gcr.io/google_containers/fluentd-elasticsearch:1.12
Node:				gce-soak-weekly-minion-b2k0/
Labels:				<none>
Status:				Pending
Reason:				
Message:			
IP:				
Replication Controllers:	<none>
Containers:
  fluentd-elasticsearch:
    Image:	beta.gcr.io/google_containers/fluentd-elasticsearch:1.12
    Limits:
      cpu:		100m
    State:		Waiting
    Ready:		False
    Restart Count:	0
No events.
```

@dchen1107 to triage/reassign. Marking p0 since it blocks tests on what should be a healthy cluster.  The kubeconfig for this cluster is on `jenkins-master` at `/var/lib/jenkins/jobs/kubernetes-soak-weekly-deploy-gce/workspace/.kube/config`.

**Comment by dchen1107** [comment]
I might misread the information you posted above, but at least I saw pod status is Running and Container's status is running too. Did you post a wrong information here?

**Comment by jlowdermilk** [comment]
Sorry I posted the wrong one. The pending one is below (I'll edit original comment to match)
```
jenkins@jenkins-master:~/jobs/kubernetes-soak-weekly-deploy-gce/workspace$ kubectl describe pods fluentd-elasticsearch-gce-soak-weekly-minion-b2k0 --namespace=kube-system
Name:				fluentd-elasticsearch-gce-soak-weekly-minion-b2k0
Namespace:			kube-system
Image(s):			beta.gcr.io/google_containers/fluentd-elasticsearch:1.12
Node:				gce-soak-weekly-minion-b2k0/
Labels:				<none>
Status:				Pending
Reason:				
Message:			
IP:				
Replication Controllers:	<none>
Containers:
  fluentd-elasticsearch:
    Image:	beta.gcr.io/google_containers/fluentd-elasticsearch:1.12
    Limits:
      cpu:		100m
    State:		Waiting
    Ready:		False
    Restart Count:	0
No events.
```

**Comment by jlowdermilk** [comment]
You can fetch/use credentials for the cluster via the following (assumes you have access to the kubernetes-jenkins project)
```
$ gcloud compute copy-files --project=kubernetes-jenkins jenkins@jenkins-master:/var/lib/jenkins/jobs/kubernetes-soak-weekly-deploy-gce/workspace/.kube/config .
...
$ export KUBECONFIG=config
```

**Comment by dchen1107** [comment]
I looked at the issue this morning, and found the cluster was teared down, and new cluster doesn't have fluentd pending issue. @jlowdermilk do I miss anything here?

**Comment by jlowdermilk** [comment]
The soak-cluster gets torn down and recreated weekly. I was hoping we could debug the issue before that happened, but since that's no longer possible I'll close this as not reproducible. Hopefully we can catch it sooner if it happens again.
