### ISSUE TITLE
Feature request - remote file system.

### ISSUE THREAD

**Issue by gedw99** [kubernetes/kubernetes#17341]
As a user, I want to develop complex software, without having to install any k8 or docker locally.

I can use use my standard tools. Ide, terminal.
If the remote filesystem is exposed over NFS or whatever is easily mountable from osx, Linux or windows.

**Comment by thockin** [comment]
This is not really enough to stir a discussion.  What exactly do you envision being exposed over NFS?  Do you intend to run NFS over the public internet for cloud installations?

**Comment by gedw99** [comment]
i am not saying it has to be NFS, but more guessing logically this would be the best protocol. The choice of protocol is pretty important because you want it to work cross OS. 

What to expose over NFS?
- the remote file system. Thats it.

How it would be accessed ?
- You could mount it like a drive ?

**Comment by thockin** [comment]
What remote filesystem?  The one in a running container?  The one on the
master?  A node?  What do you want to DO with that filesystem?

There's no universal remote FS.  NFS is as close as you get and I have no
idea what the Windows/Mac state of affairs is.  But I still have no idea
what you're trying to achieve.

**Comment by gedw99** [comment]
1. Yes the FS running inside the container. It can be any container, because who knows which one you want to connect to and do work on.

2. With a remote FS; you can test faster, because its on the real infrastructure and so has a IP that is addressable. Also when you have a ton of data (e.g machine learning), you cant have it locally. 
So, you can work faster, and git commit the code on the remote FS etc like normal workflow

**Comment by mikedanese** [comment]
I think this is a dup of #16741

**Comment by gedw99** [comment]
@mikedanese 
Yes its possible that the implementation crosses over.
#16741 is more about a SAN type stuff -  The bottom layer of storage that the Docker containers can mount.
If that storage mount can also be exposed over a remote connection then yes it would be the same.
But,  because the way a FS is mounted from a network drive, is very often different from what you would want over a remote connection, conflating the two would be a bad move i think, because they have vary different needs.

Hope that makes sense.

**Comment by swagiaal** [comment]
@gedw99 I may not have understood your use case properly but would it be possible for you to use the NFS plugin and mount important data dirs from NFS which you can also mount from your dev mahcine ?
For example if you are developing a website being served by nginx you can create a pod which mounts an NFS export to /usr/share/nginx/html inside the container then mount the same nfs export from you dev machine. Updating the export would update the html served by your pod and you would not have to install docker nor kube locally.
See https://github.com/kubernetes/kubernetes/tree/master/examples/nfs

**Comment by joeblew99** [comment]
@swagiaal

It's close, but i have a few issues with that architectural approach to solving the use case.

I want to be able to expose the folder from inside my pod, independent of how the pod mounts the volume exposed by the storage layer. The reason is because I need to be independent of the storage protocol. This is the conflagration I was warning about.

It would be much more flexible if I can expose a folder from inside my pod to my desktop over NFS. The storage layer can expose to to pod over any protocol is wants, independent of how I expose from the pod to my desktop.

This design would imply that the docker instances, 100% independent of K8 architecture, would expose the volume to my desktop.

If the mapping is such that many docker instances are mapped to a single storage layer vume, e erything would work.

**Comment by thockin** [comment]
I appreciate the idea, but I don't think this is something we can reasonably do in a generic way, at least any time soon.  The NFS suggestion seems like your best bet.

**Comment by joeblew99** [comment]
Yes I will try it. I will also try the 2nd way and let you know
