### ISSUE TITLE
"Missing Service Entry" after cluster runs for a few hours

### ISSUE THREAD

**Issue by ben** [kubernetes/kubernetes#17347]
I've got what's pretty close to a vanilla cluster running in AWS. I altered the instance sizes and counts, turned off cluster/node logging, and I'm using `btrfs` for Docker storage, but otherwise everything is just as `kube-up` made it.

We have a few RCs and Services running, but after the cluster was up for a couple of hours these stopped responding. `curl`ing from one pod to another got really slow, and intermittenly would fail (even bypassing DNS and services). Running through the service-debugging guide, I found lines that look like this from the `kube-proxy` log on one of the minions:

```
Nov 16 23:17:19 ip-172-20-0-78 kube-proxy[11554]: E1116 23:17:19.958696   11554 proxysocket.go:93] Couldn't find an endpoint for default/nginx-welcome:https: missing service entry
Nov 16 23:17:19 ip-172-20-0-78 kube-proxy[11554]: E1116 23:17:19.958712   11554 proxysocket.go:138] Failed to connect to balancer: missing service entry
```

That particular service is one of three that route traffic to the same set of pods; [here's](https://gist.github.com/ben/7d9b89d693b47f268a2a) what I used to create all of them.

The maddening thing is that they work. For the first couple of hours after they're created, they work perfectly. Then it seems like they decay.

Our management strategy right now is to kick kube-proxy whenever it starts acting up, but this isn't really a good solution. Any ideas what might be causing this?

**Comment by thockin** [comment]
Have you tried the new iptables proxy in kubernetes v1.1?  Please try it (note that it is not on by default - look at the release notes) and let me know if this is still happening.
