### ISSUE TITLE
Clarify volume plugin errors

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#17344]
And generate an event, if we don't already.

Motivated by http://stackoverflow.com/questions/33606773/use-rbd-in-kubernetes-error

Currently Kubelet just logs "no volume plugins matched". 

What the plugin matching code does is:
```
	for k, v := range pm.plugins {
		if v.CanSupport(spec) {
			matches = append(matches, k)
		}
	}
```

The rbd CanSupport implementation checks whether the rbd command works:
```
func (plugin *rbdPlugin) CanSupport(spec *volume.Spec) bool {
	if (spec.Volume != nil && spec.Volume.RBD == nil) || (spec.PersistentVolume != nil && spec.PersistentVolume.Spec.RBD == nil) {
		return false
	}
	// see if rbd is there
	_, err := plugin.execCommand("rbd", []string{"-h"})
	if err == nil {
		return true
	}

	return false
}
```

If it doesn't, it's probably because the user didn't realize they needed to install it (the doc/example could be clearer).

However, CanSupport can't currently return an error string. The volume plugin interface should be changed to enable that, so that a useful error message could be returned.

cc @kubernetes/goog-cluster

**Comment by pmorie** [comment]
+1 to this, there are many things like this that should surface from `CanSupport`

**Comment by markturansky** [comment]
See https://github.com/kubernetes/kubernetes/issues/12650

**Comment by asalkeld** [comment]
Note #21805 (Remove host command sniffing from CanSupport), should this issue be closed now, or is there still something to do still?

**Comment by childsb** [comment]
Closing since this specific error path and message have since been removed.
