### ISSUE TITLE
EmptyDir should be allowed to be defined on PV to allow easy testing and local dev of pod templates that point to PV

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#17354]
There is no system component today that allows easy mock / development testing with PVs.  We should add EmptyDir as a valid source type to PV struct, and document it can be used for local testing.

It should be possible in the future for admins to configure some namespaces / app types to be automatically given empty dir to facilitate simple iteration.

**Comment by smarterclayton** [comment]
It is far too difficult to test PV for local developers or kick the tire users.

**Comment by smarterclayton** [comment]
@thockin this is based on feedback from app developers who find it difficult to validate precanned apps that depend on templates.  It doesn't solve the whole problem, but it enables someone to actually try out function.

**Comment by thockin** [comment]
PV already supports hostPath for this?

**Comment by smarterclayton** [comment]
HostPath doesn't have all the positive properties of EmptyDir - it doesn't
chown, set selinux labels, or cleanup content.  Someone testing / iterating
on a pod that uses a PV on a single machine has to go rm -rf a local dir
every time they want to reset the PV, and isn't getting the same security
behavior.  HostPath is useful as well.

It is extremely useful to people trying to build things against the system
to have a property of PV that emulates actual volumes.  HostPath is one
part, EmptyDir is another.  Down the road, we will probably have a third
that feels more like a combination of the two.  As an app builder, host
path doesn't help me iterate, and that's a gap in our ability to bring apps
to the platform.

On Nov 17, 2015, at 2:33 AM, Tim Hockin <notifications@github.com> wrote:

PV already supports hostPath for this?

On Mon, Nov 16, 2015 at 8:38 PM, Clayton Coleman <notifications@github.com>
wrote:

> @thockin <https://github.com/thockin> this is based on feedback from app
> developers who find it difficult to validate precanned apps that depend on
> templates. It doesn't solve the whole problem, but it enables someone to
> actually try out function.
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/issues/17354#issuecomment-157265791
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17354#issuecomment-157299239>
.

**Comment by smarterclayton** [comment]
Can we argue some more about this?  We keep hitting this in a number of levels:

* making it easy to deploy test / dev clusters that have persistent storage without requiring a side-by-side deployment of a storage server (gluster, ceph, nfs, etc) for non-cloud environments
* encouraging the use of persistent volumes to design and build applications without having to have "two paths" (one for persistent volumes for production, one for empty dir for testing).  
* simple testing of other PV mechanisms without having to commit to a storage solution (you can get experience with your patterns by using empty dir and then broaden)

This is a pretty big usability issue for anyone not deploying to a cloud provider.

**Comment by smarterclayton** [comment]
@thockin this is gradually creeping up into my "top-10 things people regularly yell at me about Kubernetes that we could sidestep by making PV easier to use off-cloud"

**Comment by asalkeld** [comment]
I can work up a PR for this.

**Comment by thockin** [comment]
@bprashanth is also discussing this, but he wants to bring it in as a
"real" feature.  Maybe you folks can coordinate.

**Comment by asalkeld** [comment]
OK, I'll wait for some feedback from him.
