### ISSUE TITLE
Swagger spec at http://kubernetes.io/swagger-spec/api/ seems not up-to-date

### ISSUE THREAD

**Issue by wing328** [kubernetes/kubernetes#17351]
The swagger spec at http://kubernetes.io/swagger-spec/api/v1/ seems not up-to-date as I found the following parameter definition for method `connectGetNamespacedPodExec ` 
```
{
  type: "",
  paramType: "query",
  name: "command",
  description: "Command is the remote command to execute. argv array. Not executed within a shell.",
  required: false,
  allowMultiple: false
},
```
while the updated swagger spec at[ Github repo](https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L6111) has a valid type (string) defined.

**Comment by nikhiljindal** [comment]
Thanks for reporting.
Sent https://github.com/kubernetes/kubernetes/pull/17352 to fix that.

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/17352
