### ISSUE TITLE
kube-proxy iptables should REJECT packets for services without endpoints

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#17359]
Currently we install the rules even if a service has no endpoints.  Connecting to such a service just hangs.  Some apps (curl) don't handle this well.

```
# curl --connect-timeout 3 10.0.231.31:443
curl: (28) connect() timed out!

# iptables -t filter -A OUTPUT -d 10.0.231.31/32 -p tcp -m comment --comment "default/myblackhole:https cluster IP" -m tcp --dport 443 -j REJECT

# curl --connect-timeout 3 10.0.231.31:443
curl: (7) couldn't connect to host
```

Something like that for when there are 0 endpoints.  I only tested with TCP, but from reading it sounds like UDP is OK.

**Comment by maclof** [comment]
@thockin I've started working on fixing this, could you tell me if I'm going in the right direction? https://github.com/maclof/kubernetes/commit/d394dfb96ebe73cc4c02835813dd5e3effef4285

I assume I will need to name the filter chains something other than OUTPUT?

**Comment by thockin** [comment]
Comments sent - looks like a great start!
