### ISSUE TITLE
"kubect describe jobs" include garbage charactor

### ISSUE THREAD

**Issue by jay-lau** [kubernetes/kubernetes#17364]
# kubectl describe jobs/pi
Name:           pi
Namespace:      default
Image(s):       perl
Selector:       app in (pi)
Parallelism:    1
Completions:    1
Labels:         app=pi
Pods Statuses:  0 Running / 1 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen     LastSeen        Count   From    SubobjectPath   Reason                  Message
  鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€   鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€        鈹€鈹€鈹€鈹€鈹€ 鈹€鈹€鈹€鈹€    鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€ 鈹€鈹€鈹€鈹€鈹€鈹€    攢鈹€鈹€鈹€鈹€鈹€鈹€
  3m            3m              1       {job }                  SuccessfulCreate        Created pod: pi-jw7q9

**Comment by gmarek** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
cc @mikedanese @erictune @soltysh @janetkuo

**Comment by soltysh** [comment]
Will work on it, please assign it to me.

**Comment by janetkuo** [comment]
@soltysh Thanks!

**Comment by soltysh** [comment]
These garbage you see are the lines under headers for events, here's my output for comparison:
```
$ kubectl describe job/pi
Name:		pi
Namespace:	default
Image(s):	perl
Selector:	app in (pi)
Parallelism:	1
Completions:	1
Labels:		app=pi
Pods Statuses:	0 Running / 1 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen	LastSeen	Count	From	SubobjectPath	Reason			Message
  ─────────	────────	─────	────	─────────────	──────			───────
  40s		40s		1	{job }			SuccessfulCreate	Created pod: pi-hu8pc
```

I assume you have some problems with displayed characters on your console. @jay-lau can you please check this?

**Comment by soltysh** [comment]
We're using there unicode 2500 fyi, so I'm guessing your console does not handle unicode well.

**Comment by soltysh** [comment]
[This is the line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe.go#L1516) that is responsible for that.

**Comment by jay-lau** [comment]
Yes, but I think that the command output should not care the console. ;-)

**Comment by janetkuo** [comment]
perhaps we should change all `─` to `-`

**Comment by soltysh** [comment]
:+1: yeah, using just the ASCII characters would be desirable. I'll try to find all the places and rework it accordingly.
