### ISSUE TITLE
No job related kubectl help info

### ISSUE THREAD

**Issue by jay-lau** [kubernetes/kubernetes#17363]
The current kubectl can create jobs but there is no help info when "kubectl get" or "kubectl describe"

**Comment by gmarek** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
Needs to be added to the overview also:
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl-overview.md

cc @soltysh @mikedanese @erictune
