### ISSUE TITLE
Api docs wrong for service name

### ISSUE THREAD

**Issue by owenhaynes** [kubernetes/kubernetes#17362]
The API doc list the v1.Service having a v1.ObjectMeta which contains a name. It says the name can be up to 253 characters in length. This however is not true for v1.Service which can have at most 24 characters.

```
The Service "myverlongservicename-svc" is invalid:metadata.name: invalid value 'myverlongservicename-svc', Details: must be a DNS 952 label (at most 24 characters, matching regex [a-z]([-a-z0-9]*[a-z0-9])?): e.g. "my-name"
```

**Comment by gmarek** [comment]
cc @bgrant0607

**Comment by owenhaynes** [comment]
The docs sort of exists (http://kubernetes.io/v1.1/docs/design/identifiers.html) but they are not very clear which one is used for which type. Should at least be made more clear.

**Comment by thockin** [comment]
Yeah, I am not sure how to fix this one, short of cloning ObjectMeta, since
that is where the description comes from.  will chew on this...

**Comment by bgrant0607** [comment]
Related: #3752

I think we'll have to clone ObjectMeta and other shared types eventually, but we could add a note to the share documentation about service names.

**Comment by thockin** [comment]
I'd love to make time (or for someone else to make time) to make the
go->swagger process do the right thing for cases like:

```
type Foo struct {
    OM struct {
        // Usual comment here
        ObjectMeta `json:",inline"`
        // Different Comment Here
        Name string
    } `json:"metadata"`
```

and to see us do more of this sort of inlining, rather than type-sharing.
I think it makes docs clearer too.

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by bgrant0607** [comment]
This is wrong for Namespace, too

/remove-lifecycle stale
/lifecycle frozen

**Comment by pacoxu** [comment]
Document：https://github.com/kubernetes/website/blob/04163e9a7c45aa447581bc567e9c86e555f7dab1/content/en/docs/concepts/overview/working-with-objects/names.md#names

> By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions.

In code, pod name and service name must be no more than 63 characters.
Labels of DNS1233 should be no more than 63 characters.
Subdomain of DNS1233 should be no more than 253 characters.

https://github.com/kubernetes/kubernetes/blob/8d7d7a5e0d4d7e75f5a860574346944b8cc0fc43/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L107


In my opinion, document of "Names" should mention that pod and service name and other v1 objects should no more than 63 characters.

**Comment by rikatz** [comment]
It seems that this is already solved.

```
$ kubectl  create -f svc.yaml 
service/f98jf9jq9f4fdinfiudsnafiunaiu4hf4hf9hf983f23q-dsadsdsa created

$ kubectl  create service nodeport myverlongservicename12312312-svc --tcp=5678:8080
service/myverlongservicename12312312-svc created

$ kubectl  create service nodeport thisisaverylongsvcnamethatsurpasses63charactersandmightbrakethings --tcp=5678:8080
The Service "thisisaverylongsvcnamethatsurpasses63charactersandmightbrakethings" is invalid: 
* metadata.name: Invalid value: "thisisaverylongsvcnamethatsurpasses63charactersandmightbrakethings": must be no more than 63 characters
```

So the thing here now is documentation now?

Thanks :)

**Comment by leilajal** [comment]
@owenhaynes  are there any updates at this issue? If this is resolved based on previous comment we can close it. Thanks!

**Comment by pacoxu** [comment]
https://github.com/kubernetes/website/pull/19106 has already added some extra intro for [dns label names and dns sub-domain names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names).
