### ISSUE TITLE
Improve unit-test for metrics client

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#17371]
We need to improve unit-test for metrics client:

 https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/metrics/metrics_client_test.go

Currently, our tests do not cover calculating requests. We need to do for them something similar as for resource consumption:
 - calculating average for many requests from different containers,
 - missing requests for some containers are handled correctly (error is returned),
 - mismatch of numbers in reported requests/consumption is handled correctly,
 - ...

**Comment by jszczepkowski** [comment]
* enforcement of downscale/upscaleForbiddenWindow,

**Comment by davidopp** [comment]
@piosz @mwielgus This is marked as 1.2 milestone -- is there something to do here? If so, we can do it after feature-complete deadline.

**Comment by davidopp** [comment]
ping

**Comment by piosz** [comment]
I think no. We can add some tests during migration to Metrics API once it will be ready.

**Comment by piosz** [comment]
It seems we have pretty good coverage here so closing the issue.
