### ISSUE TITLE
Can/should we enforce  singletons over the RESTClient?

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#17380]
In #16811 we had a conversation about RESTClient being singleton.  It appears to be invoked several times by each daemon... so there is nothing enforcing that a single process uses one global client.

Should this be forced at the level of restclient.go ?

**Comment by jiangyaoguo** [comment]
FYI, we need different rate limiters for different clients.

**Comment by lavalamp** [comment]
RESTClient is not a singleton, and should not be a singleton. Transports should be cached and reused. RESTClients are light and disposable.
