### ISSUE TITLE
kube-push.sh is broken

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#17397]
I'm getting this error on my Google Cloud cluster:

```
I1117 22:56:55.385576    3509 kubelet.go:977] Unable to register kubernetes-minion-frx1 with the apiserver: Post https://kubernetes-master/api/v1/nodes: x509: cert
ificate signed by unknown authority
```

Using the default `./cluster/kube-up.sh`

To reproduce:
- kube-up
- everything is working fine
- delete one of the instances from the autoscaling group
- the new instance will fail with this error continuously

**Comment by paralin** [comment]
The problem is that /srv/salt-overlay/salt/kubelet/kubeconfig does not have the certificate data.

**Comment by paralin** [comment]
It seems salt-overlay has the certificate data but /srv/salt/kubelet/kubeconfig does not. The overlay doesn't seem to be applied. If I copy the kubeconfig to /srv/salt/kubelet/kubeconfig from /srv/salt-overlay/salt/kubelet/kubeconfig it works.

**Comment by bprashanth** [comment]
@piosz

**Comment by paralin** [comment]
So I've redeployed the entire cluster and it seems to work now. Might be worth looking at. Nevertheless, killing this issue.

**Comment by piosz** [comment]
Did you use autoscaling feature or just resize manage instance group?

cc @jszczepkowski @mwielgus

**Comment by paralin** [comment]
@piosz The instance group is an autoscaling group. I "managed' it by deleting a couple instances from it and allowing them to be re-created.

**Comment by paralin** [comment]
@piosz @jszczepkowski @mwielgus @bprashanth 

This is still broken and seems like an extremely critical error.

I'm on HEAD as of the message posted here.

E1126 19:37:14.096399    4183 event.go:197] Unable to write event: 'Post https://kubernetes-master/api/v1/namespace
s/default/events: x509: certificate signed by unknown authority' (may retry after sleeping)

My cluster's broken because of this.

**Comment by mwielgus** [comment]
Can you please provide more information about your cluster? Like:
* Kubernetes Version
* Node type used
* Autoscaling configuration
* Info about any manual script changes or Kubernetes updates

**Comment by mwielgus** [comment]
The issue seams not to be caused by the Cluster autoscaling itself but probably by a broken template used in instance group. Cluster autoscaling doesn't create new instances on its own but changes the size of the instance group and new vm instances (nodes) are created based on the template passed to it at the creation time (kube-up).

**Comment by paralin** [comment]
Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.4.125+e85d3ef1a6f15b", GitCommit:"e85d3ef1a6f15b5eadea58a466cafbe34ca6a7e1", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.4.114+511b1f2943fbdd", GitCommit:"511b1f2943fbddc0728c1a0fd0a12ac598055bcd", GitTreeState:"clean"}
```

Node type used: `n1-standard-2`

For the configs do you want me to just pastebin them?

No manual script changes. Kubernetes version is HEAD with ./cluster/kube-push.sh to update. Builds are done with `make clean && KUBE_RELEASE_RUN_TESTS=n make release`.

**Comment by paralin** [comment]
Hmm @mwielgus what do you think?

```
ENV_TIMESTAMP: '2015-11-26T03:31:10+0000'
INSTANCE_PREFIX: 'kubernetes'
NODE_INSTANCE_PREFIX: 'kubernetes-minion'
CLUSTER_IP_RANGE: '10.244.0.0/16'
SERVER_BINARY_TAR_URL: 'https://storage.googleapis.com/kubernetes-staging-91a544c91e/devel/kubernetes-server-linux-amd64.tar.gz'
SERVER_BINARY_TAR_HASH: '438bd923abbb03d1ea2fc3c2a5fdb9f807970408'
SALT_TAR_URL: 'https://storage.googleapis.com/kubernetes-staging-91a544c91e/devel/kubernetes-salt.tar.gz'
SALT_TAR_HASH: '3a31f157882f5e8c38b57caa7cd2e873f17c47da'
SERVICE_CLUSTER_IP_RANGE: '10.0.0.0/16'
KUBERNETES_MASTER_NAME: 'kubernetes-master'
ALLOCATE_NODE_CIDRS: 'true'
ENABLE_CLUSTER_MONITORING: 'googleinfluxdb'
ENABLE_L7_LOADBALANCING: 'glbc'
ENABLE_CLUSTER_LOGGING: 'true'
ENABLE_CLUSTER_UI: 'true'
ENABLE_NODE_LOGGING: 'true'
LOGGING_DESTINATION: 'gcp'
ELASTICSEARCH_LOGGING_REPLICAS: '1'
ENABLE_CLUSTER_DNS: 'true'
ENABLE_CLUSTER_REGISTRY: 'false'
CLUSTER_REGISTRY_DISK: 'kubernetes-kube-system-kube-registry'
CLUSTER_REGISTRY_DISK_SIZE: '200GB'
DNS_REPLICAS: '1'
DNS_SERVER_IP: '10.0.0.10'
DNS_DOMAIN: 'cluster.local'
KUBELET_TOKEN: ''
KUBE_PROXY_TOKEN: ''
ADMISSION_CONTROL: 'NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota'
MASTER_IP_RANGE: '10.246.0.0/24'
RUNTIME_CONFIG: 'extensions/v1beta1=true,extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true'
CA_CERT: ''
KUBELET_CERT: ''
KUBELET_KEY: ''
NETWORK_PROVIDER: 'none'
OPENCONTRAIL_TAG: 'R2.20'
OPENCONTRAIL_KUBERNETES_TAG: 'master'
OPENCONTRAIL_PUBLIC_SUBNET: '10.1.0.0/16'
E2E_STORAGE_TEST_ENVIRONMENT: 'false'
KUBERNETES_MASTER: 'false'
ZONE: 'us-central1-b'
EXTRA_DOCKER_OPTS: '--insecure-registry 10.0.0.0/8'
```

In particular notice that CA_CERT is empty.

How to fix this?

**Comment by mwielgus** [comment]
cc: @roberthbailey

**Comment by mwielgus** [comment]
@paralin How did you generate the above dump? Did you catch it on your computer (either by gce/util.sh modification or by manual inspection of node-kube-env.yaml in kube-up temp dir) or somewhere else (like on the node)? If the former then there definitely should be CA_CERT, KUBELETE_CERT and KUBELETE_KEY populated - please provide more details about the operating system and check for any errors in kube-up.sh output (preferably paste it here).

**Comment by paralin** [comment]
@mwielgus I copied and pasted it from the instance template. It's a Debian setup with almost default config via kube-up and a bunch of kube-push. Probably somewhere the kube-push corrupted the instance template. Do any files need to be stored on the kube-up machine to generate these properties other than the env config? 

I've since nuked the cluster since I needed a working setup again. I would investigate what kube-push is doing - especially with a clean kubernetes repo.

**Comment by mwielgus** [comment]
Ok, if this is from the instance template then it should also have the certs populated. Probably the cert generating function somehow failed on the computer on which you executed kube-up.sh script. Nothing needs to be stored permanently on that computer - instance template as well as all configs and certs are generated on the kube-up.sh node in a temporary dir that is removed after kube-up is done. 

Please pay attention to errors/warnings printed in kube-up.sh and paste them here if they occur.

**Comment by roberthbailey** [comment]
> It's a Debian setup with almost default config via kube-up and a bunch of kube-push

The kube-push upgrade flow isn't tested nearly as well as the replace VM approach that is scripted in https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/upgrade.sh. Also, the `kubernetes-push-gce` jenkins job is not passing at the moment -- I'm not sure who is on the hook for making sure it works. @fgrzadkowski?

**Comment by paralin** [comment]
@roberthbailey Oh shoot, that makes sense. I'm going to go ahead and use upgrade.sh in the future. Thanks for the tip.

**Comment by paralin** [comment]
@roberthbailey There's a problem - you can't deploy local builds to the cluster nodes via upgrade.sh. How does that work, then?

And kube-push for sure breaks everything.

**Comment by roberthbailey** [comment]
kube-push is the current solution for local builds (for developers) so it's unfortunate that it doesn't work quite right. @mikedanese is working on an improved push workflow where images are uploaded to a private registry which might make it easier for the upgrade.sh script to work on local builds.

**Comment by paralin** [comment]
@roberthbailey It seems that to make kube-push work the solution would be to just grab the CA_CERT information from the current instance template.

Actually probably just patching the specific parts of the template that need to be changed would be better, rather than re-generating it. So maybe fetch the current template details and edit that startup script where necessary.

**Comment by quinton-hoole** [comment]
@davidopp this looks like a legit P1, and simply needs to be staffed.  Any volunteers?

**Comment by quinton-hoole** [comment]
@mikedanese FYI

**Comment by mikedanese** [comment]
I'm unable to reproduce this. The node autoscaler works by resizing a managed instance group. The only reason an new instance wouldn't have a cert was if the Instance Template didn't have a cert. @paralin can you confirm where the cert was lost? Did the instance template not have a cert? Did the node metadata not have a cert? Did the salt configs created from instance metadata not have a cert?

**Comment by paralin** [comment]
@mikedanese I was able to reproduce it originally by doing kube-up and then kube-push on gce with the autoscale enabled. The script goes to update the instance template but after the update the CA_CERT in the template is empty.

**Comment by mikedanese** [comment]
Ahhh, I was missing the kube-push. I'll try that.

**Comment by davidopp** [comment]
Meeting notes:
* Short-term just have kube-push.sh exit on GCE with a message saying it's not currently supported.
* Long-term decide if we want to support in-place upgrade on GCE.
* We should also try to verify that it is working on bare metal since it's the only way to do upgrades on bare metal.

**Comment by roberthbailey** [comment]
I think we've also heard reports that it doesn't work on AWS (at least to upgrade across minor versions).

**Comment by paralin** [comment]
I would request that you support in-place upgrade on GCE and other platforms

**Comment by paralin** [comment]
Any updates on this? I really need to update my kube cluster - there's some critical bugs in my running version. I'm a bit apprehensive to try anything without confirmation here that kube-push works.

**Comment by mikedanese** [comment]
We've disabled kube-push for gce and I don't know if we are going to fix it or remove it. We recommend you use ./cluster/gce/upgrade.sh to upgrade instead.

**Comment by paralin** [comment]
@mikedanese Can that upgrade the nodes as well as the master?

**Comment by roberthbailey** [comment]
@paralin - Yes: `-N:  Upgrade nodes only`

**Comment by paralin** [comment]
Great, works. Thanks.

**Comment by bgrant0607** [comment]
Related: #18467

**Comment by bgrant0607** [comment]
Related: #12640

**Comment by bgrant0607** [comment]
Somewhat related: #4806

**Comment by bgrant0607** [comment]
One user tried kube-push.sh on AWS yesterday to upgrade his master from 1.1 to 1.2, and it bricked his cluster. He then used kube-push.sh to revert, but had to reinstall docker 1.6 on the master manually in order for the master components to come up again.

**Comment by mikedanese** [comment]
Kube push shares pretty much no code between providers right now

**Comment by paralin** [comment]
I like the way the GCE upgrade script replaces nodes. It leaves little chance for failure, aside from an interrupted update process.

However I think this will be undesirable in a production cluster. You have some downtime and in particular the risk of a bricked cluster, as well as the inconvenience of recreating every node.

The kube-push way of updating the salt template and pushing the new binaries out to all the nodes seems like the best way to me. Having a centralized template for what a node looks like, regardless of where or how it was created, is the best way to ensure that this update propagates even across platforms.

This is why I think it might be good to rewrite kube-push to be provider agnostic with minor provider specific routines like commands to ssh to master and whatnot.

**Comment by paralin** [comment]
@justinsb As of v1.2.0-beta.1 running kube-push.sh on AWS gave me:

```
Updating cluster using provider: aws
Using master: kubernetes-master (external IP: 52.36.143.188)
Uploading to Amazon S3
+++ Staging server tars to S3 Storage: kubernetes-staging-574dfd9955b862e8c889c7a63b2e10f8/devel
upload: ../../../../../../tmp/kubernetes.ggw3vs/s3/bootstrap-script to s3://kubernetes-staging-574dfd9955b862e8c889c7a63b2e10f8/devel/bootstrap-script
Uploaded server tars:
  SERVER_BINARY_TAR_URL: https://s3.amazonaws.com/kubernetes-staging-574dfd9955b862e8c889c7a63b2e10f8/devel/kubernetes-server-linux-amd64.tar.gz
  SALT_TAR_URL: https://s3.amazonaws.com/kubernetes-staging-574dfd9955b862e8c889c7a63b2e10f8/devel/kubernetes-salt.tar.gz
  BOOTSTRAP_SCRIPT_URL: https://s3.amazonaws.com/kubernetes-staging-574dfd9955b862e8c889c7a63b2e10f8/devel/bootstrap-script
grep: ./../cluster/../cluster/aws/../../cluster/../cluster/aws/templates/common.sh: No such file or directory
Permission denied (publickey).
```

?

**Comment by oO-Zam** [comment]
From 1.2.0 to ( hopefully ) 1.2.2

````
Uploaded server tars:
  SERVER_BINARY_TAR_URL: https://s3.amazonaws.com/zam-kubernetes-artifacts/devel/kubernetes-server-linux-amd64.tar.gz
  SALT_TAR_URL: https://s3.amazonaws.com/zam-kubernetes-artifacts/devel/kubernetes-salt.tar.gz
  BOOTSTRAP_SCRIPT_URL: https://s3.amazonaws.com/zam-kubernetes-artifacts/devel/bootstrap-script
grep: ./../cluster/../cluster/aws/../../cluster/../cluster/aws/templates/common.sh: No such file or directory
````
This fails in the `.../cluster/aws/util.sh` at line 1500 because there is no `aws/templates/common.sh` file. even if you ignore the fact that after going through 3 different sourced scripts, the `$KUBE_ROOT`path becomes a mess. I guess it's technically correct, but reads like the steps in Salsa...

Any other way to force an upgrade from 1.2.0 to 1.2.2 in a production AWS cluster?

**Comment by felipejfc** [comment]
I also had the same error with a aws cluster

```
...

  SERVER_BINARY_TAR_URL: https://s3.amazonaws.com/kubernetes-staging-72103308bf31ce02d477c6a2b4c00f67/devel/kubernetes-server-linux-amd64.tar.gz
  SALT_TAR_URL: https://s3.amazonaws.com/kubernetes-staging-72103308bf31ce02d477c6a2b4c00f67/devel/kubernetes-salt.tar.gz
  BOOTSTRAP_SCRIPT_URL: https://s3.amazonaws.com/kubernetes-staging-72103308bf31ce02d477c6a2b4c00f67/devel/bootstrap-script
grep: ./kubernetes/cluster/../cluster/../cluster/aws/../../cluster/../cluster/aws/templates/common.sh: No such file or directory
```

**Comment by mikedanese** [comment]
Can we disable kube-push til this is fixed so people don't brick their clusters?

**Comment by davidopp** [comment]
@mikedanese That sounds like a good idea. Leave the script as-is except add at the beginning echo some kind of "you really shouldn't use this" message and exit.

**Comment by ihmccreery** [comment]
I'm unassigning myself because this is out-of-scope for what I'll be working on this quarter.

**Comment by zhouhaibing089** [comment]
I feel it is too aggresive, what if some providers do support `kube-push`? I have my own kubernetes provider for local development, and always use `kube-push` to do a binary update...

It feel it is good to print a warning, but totally disabling it is not good for me..

**Comment by bscott** [comment]
Any update as I cant upgrade existing clusters because kube-push gives me the message "kube-push is broken"

**Comment by sege** [comment]
Any update on this? How do I handle my local clusters running Ubuntu?

**Comment by paralin** [comment]
@sege :(

As far as I know there is a solution in the works for this still.

**Comment by roberthbailey** [comment]
kube-push was removed in https://github.com/kubernetes/kubernetes/pull/58246, so marking this as obsolete.
