### ISSUE TITLE
Keep a rolling average on resource creation and initial notification via watch

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#17391]
**Scenario:**
controller X has a WATCH against kube-api-server on resource Y
client A creates a new Y
1. kube-api-server creates a resource Y in etcd
2. etcd acknowledges create and responds with Y, Y createdIndex/modifiedIndex mapped to ResourceVersion
3. kube-api-server is notified via a WATCH event from etcd that Y exists
4. controller X is then notified that Y exists

**Goal:**
Measure the time between when the kube-api-server knows the resource was created (step 2) and when it is retold that the resource was created via a watch notification from etcd (step 3).  I think we could track this by recording the local kube-api-server time with the resource creationTimestamp for watch where the nodeAction is create.

There have been a few issues where as the number of keys in etcd grows to N, the time it takes to get notified in the api-server for N+1 resource appears to grow even when inside an etcd watch window, having a metric would make it easier to debug, but have encountered some issues where latency appears to ~20s in some cases where if reported could provide a dump of some metrics endpoint, it would have been easier to isolate the issue.

**Caveats:**

I am most interested in measuring the time when inside of an etcd watch window; so I think it's fine if we ignored the metric on LIST+WATCH scenarios.

@wojtek-t - have you done any measurements in this area?

**Comment by wojtek-t** [comment]
@derekwaynecarr - I was doing some experiments on density.go/load.go on 100-node cluster at some point (few months ago when we were launching it). And definitely it wasn't in the order of seconds - and definitely not 20s.

I completely agree it would be useful to have such a metric - I will try to add it.

**Comment by derekwaynecarr** [comment]
@wojtek-t - in this scenario, we were load testing a cluster with fake nodes.  So it was primarily stressing the limits of individual controllers before things fell down, or how long until those controllers observed a change and could act upon it.

**Comment by wojtek-t** [comment]
@gmarek - who will be adding different metrics to Kubernetes

**Comment by gmarek** [comment]
@derekwaynecarr - we're considering adding a similar metric today. We were also considering

  0. Component Z sends a create request for Y to api-server

to have a bigger picture. First idea that came along was to use annotations to store timestamps for different steps (we need something more that we have today, as currently we have a resolution of a second).

**Comment by derekwaynecarr** [comment]
@gmarek - assuming client side timestamps are synched with server time, i could see that being useful.  good to know we are all considering additional measures in similar areas.
