### ISSUE TITLE
aws profile is cleaned up

### ISSUE THREAD

**Issue by svennela** [kubernetes/kubernetes#17395]
Hi,

aws profile is being cleaned up after running kube-up.sh

1) aws iam list-instance-profiles I can see  profiles

after bash ./kubernetes/cluster/kube-up.sh

The config profile (ks-profile) could not be found

Thank you,
Sridhar

**Comment by svennela** [comment]
I am using MAC. Once i run 

bash ./kubernetes/cluster/kube-up.sh

 aws iam list-instance-profiles information is also gone from that shell command. If i open new tab, it works fine. Any pointers??

**Comment by davidopp** [comment]
ping @justinsb to see if he has any ideas

**Comment by justinsb** [comment]
Is it possible that the environment variables set in the script are somehow escaping into the shell?  I also don't know what environment variable would cause IAM credentials to disappear; we do set `AWS_DEFAULT_REGION` but IAM is cross-region.  I don't know _how_ the environment variables could be escaping (unless you run `. ./cluster/kube-up`), but it does fit the symptom that a new tab restores the normal behaviour.

@svennela maybe check that `which aws` is the same before and after running the script; check to see if any environment variables have changed after running the script (in particular `AWS_PROFILE`, `AWS_DEFAULT_PROFILE`, `AWS_REGION`, `AWS_DEFAULT_REGION` or `AWS_DEFAULT_OUTPUT`).  And if you can provide the before-and-after output from `aws iam list-instance-profiles` that would also be helpful.

**Comment by roberthbailey** [comment]
Obsoleted by https://github.com/kubernetes/kubernetes/pull/42196.
