### ISSUE TITLE
Implement "equivalence classes" and caching thereof

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#17390]
These are described in section 3.4 of the Borg paper.

There are a lot of ways to do this. One simple way is
1) When you apply the predicate and priority functions to a pod, cache the results (namely, for each machine, whether the pod is feasible on that machine, and the priority value for the pod on that machine)
2) Scheduler watches for bindings and unbindings and node changes, and marks a cached value as dirty whenever there is a change that invalidates a cached value. (For example, if the labels on a node change, or a new pod gets bound to a machine, then all cached values related to that machine are invalidated.) In the future when we have in-place updates, some updates to pods running on the machine would also cause the node to be marked dirty.
3) When scheduling a new pod, check to see if the scheduling result for an equivalent pod is already cached. If so, re-evaluate the predicate and priority functions just for the "dirty" values (i.e. not for all machines), and update the cache.

**Comment by brendandburns** [comment]
voting this down to p2 since rough estimates via micro benchmark indicate that this can save us at most 1 millisecond / scheduling.

**Comment by wojtek-t** [comment]
>
voting this down to p2 since rough estimates via micro benchmark indicate that this can save us at most 1 millisecond / scheduling.

@brendandburns - what assumption do you have in your benchmarks? If we have e.g. a relatively big replication controller (e.g. hundreds of replicas) being created at once - the savings should be huge..

**Comment by davidopp** [comment]
Benchmark is in #17415

**Comment by HaiyangDING** [comment]
+1. Great to see some Borg optimization to be introduced to Kubernetes.

**Comment by bgrant0607** [comment]
Described here:
http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43438.pdf

In general, techniques for speeding up memory allocation/management apply pretty well to placement, with the slight twist that it's multi-dimensional (cpu, memory, ...).

**Comment by resouer** [comment]
> 3) When scheduling a new pod, check to see if the scheduling result for an equivalent pod is already cached
@davidopp How to define the equivalent Pod of another. The same Predicates?

**Comment by davidopp** [comment]
> @davidopp How to define the equivalent Pod of another. The same Predicates?

Two pods are equivalent if every property of the pod that any predicate or priority function uses as input are equivalent.

**Comment by jiangyaoguo** [comment]
@davidopp Is there anyone working on this? If not, I could look into it.

**Comment by davidopp** [comment]
@wojtek-t are you convinced convinced that the scheduler is currently a bottleneck for scaling to 1k nodes? If so, then I think what's described in this issue would be a useful optimization. But if you're not sure, then we could wait for measurements from the 1k-node configuration.

**Comment by jiangyaoguo** [comment]
Whether the equivalence classes and  cache can speed up scheduling depends on nodes amount,cache size, equivalence pods ratio. I think we need this mechanism, but it should be optional and configurable for user to adapt different conditions.

**Comment by resouer** [comment]
Nope. The point is we are not sure whether the scheduler is a bottleneck for 1k nodes goal. So for anyone want to help here, doing a convincing measurement or benchmark will be more appreciated for now I think.

**Comment by jiangyaoguo** [comment]
Waiting for "integration test for scheduler" which @xiang90  mentioned in #17415.

**Comment by xiang90** [comment]
@jiangyaoguo We plan to push it to upstream this week (at least a proposal with some working code).

**Comment by mqliang** [comment]
Intuitively, equivalence pods are created by the same rc, and usually a rc would have a replica number 3-5, so it may improve the efficiency about 3-5 times. But some convincing measurement or benchmark are needed.

**Comment by davidopp** [comment]
#18831 is the caching part

**Comment by resouer** [comment]
Close by #30844
