### ISSUE TITLE
Kube proxy source address

### ISSUE THREAD

**Issue by nasdf** [kubernetes/kubernetes#17394]
Would it be possible for the kube proxy to preserve the source address of a packet?  I am trying to capture a UDP packet source address for later use but cannot find any way to do this currently.

**Comment by thockin** [comment]
In kubernetes v1.1 you can turn on the iptables proxy, which preserves source IP for clients within the cluster.  It still gets lost on load-balancers, though.

**Comment by nasdf** [comment]
Thanks for the response.  I've already upgraded to v1.1 and turned on the iptables, but I didn't realize the load-balancers changed the source address.  What is the recommended approach without using load-balancers?  Would I just point to a single node ip address on the cluster?

**Comment by thockin** [comment]
Because of how Kubernetes Services interact with most load-balancers today,
there is not a good way to preserve the source IP.  Trust me that it is
something I am concerned about fixing, but it's not easy.
