### ISSUE TITLE
Allow DnsPolicy=ClusterFirst for Pods with hostNetwork: true

### ISSUE THREAD

**Issue by ArtfulCoder** [kubernetes/kubernetes#17406]
With 1.1, we allow pods to be created with hostNetwork = true.
These pods should be allowed to use Cluster DNS, if the pod spec says so.

We have already wired the kube-proxy to support traffic from the host machine to be directed to kube-services. We should similarly allow cluster dns names to be looked up by pods with hostNetwork=true.

This way, pods can use hostNetwork = true and still leverage kubernetes' service discovery mechanisms.

I currently have a use case, where I am writing a GCE Firewall pod, that configures iptables on the nodes. This pod needs to run with hostNetwork=true to configure iptables and the same time needs to look up a kubernetes pod service to read some metadata.
Refer to #17405
https://github.com/ArtfulCoder/kubernetes/blob/prototype2/contrib/gce-firewall/client.yaml#L19

Currently, I have hard-coded a Kubernetes service-ip since we dont have cluster dns for hostNetworked-pods.  This is hardly a workable solution.

I would imagine that third-party network plugins would also face similar issues if they try to do a clean implementation.

Option 2:
The other option is to query API server to do service discovery. But this doesn't seem like a clean solution, especially since we have put in so much effort into our DNS based service discovery approach.

**Comment by ArtfulCoder** [comment]
@thockin

**Comment by thockin** [comment]
I think that some network setups (including a developer team I spoke to today) it is not true that hosts can access the pod network.  And in a VLAN'ed model it won't be true, either.

This is a tricky one.

@sig-network

**Comment by thockin** [comment]
@kubernetes/sig-network

**Comment by ArtfulCoder** [comment]
1.Another option for service discovery in such situations could be using a designated node port.
(Ideally, it would be great if the node port could somehow be templatized in some fashion)

**Comment by ArtfulCoder** [comment]
If APIServer can support the following templatized spec, i believe we would have an alternate (non-DNS) way of service discovery. 

containers:
      - name: client
        image: foo-httpclient:1.1
        command: [ "/client", "-server", "{{clusterIP.fooService.barNamespace}}", "-port", "{{port.fooService.barNamespace}}" ]

**Comment by ArtfulCoder** [comment]
The templatized spec limitation would be that once the template is populated, future modifications to the template variables cannot be easily propagated.

**Comment by ArtfulCoder** [comment]
Nth option: Pass in the dns server ip and have the client lookup the nameserver

**Comment by thockin** [comment]
Abhi,

I think you nailed it:

```
apiVersion: v1
kind: Pod
metadata:
  name: hostnet
  namespace: default
spec:
  hostNetwork: true
  containers:
  - name: busybox
    image: busybox
    command: [ "sh", "-c", "echo
$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT); sleep 1000" ]
```

You CAN do expansions in commands/args

**Comment by ArtfulCoder** [comment]
Thanks Tim.
Just that if a user deletes the service spec and recreates it, the client pods would have to be deleted and re-created as well ? Otherwise, the client pods will hit a service-ip that is no-longer around (or worse, pointing to something else.)

I guess, we can document this clearly and move on with this approach.

**Comment by thockin** [comment]
I think that is the best choice for now, but we do still have to answer the
question of whether this should work.

**Comment by ArtfulCoder** [comment]
Leveraging env variable to discover the kubernetes service works out. Closing issue.

**Comment by 2opremio** [comment]
We are experiencing the same problem with Weave Scope. We are using env variable expansions to work around it, but it's a hack because it imposes a specific deployment order. 

See point (5) of https://github.com/weaveworks/scope#using-weave-scope-with-kubernetes and https://github.com/TheNewNormal/kube-charts/blob/07a2fd485c7183e4a5bb5630724d7dd03ed1767c/weavescope/manifests/scope-probe-ds.yaml#L28-L40 

Related: https://github.com/docker/docker/issues/10384

**Comment by bscott** [comment]
@ArtfulCoder Is this still an issue in 1.2?, I have a POD using Host Network and I have dnsPolicy set to ClusterFirst but it's /etc/resolv.conf still is not getting updated to use SkyDNS.

How do we use that Env var?

**Comment by 2opremio** [comment]
@bscott it's still an issue

**Comment by thockin** [comment]
Opening for reconsideration.

**Comment by nick4fake** [comment]
Is there a good workaround other then hardcoding /etc/resolv.conf or adding patch to RC config?

**Comment by nick4fake** [comment]
@thockin it seems that there is a fix for docker:
https://github.com/docker/docker/pull/22408

**Comment by sols1** [comment]
With the following docker PR #https://github.com/docker/docker/pull/22408, this issue should be resolved by kubelet passing `--dns` and `--net=host` options to docker.

**Comment by thockin** [comment]
We do a lot of DNS processing, so it may be that docker's fix does not
"just work" for us.  I have been worn down on this.  I'm happy to entertain
patches :)

**Comment by vefimova** [comment]
@yifan-gu @thockin Guys, please have a look at #29378 it enables to use added in docker 1.12 hostnetwork+dns feature.

**Comment by 2opremio** [comment]
Thanks @vefimova , any news on when it will be merged? You seem to be getting close!

**Comment by sheerun** [comment]
My use case: I wanted to discover service ip address from load balancer pod that is deployed on host network and in daemon set

**Comment by zcahana** [comment]
I have a similar use case, which involves a pod using `hostNetwort: true` for messing with iptables rules on the host, while still using cluster DNS for resolving k8s services.

**Comment by cmluciano** [comment]
[Possibly related](https://github.com/kubernetes/kubernetes/issues/35761)

**Comment by bamb00** [comment]
Is there a fix for this issue? What version of Kubernetes can we expect the fix to be available? I try the workaround below (Variable Expansion) provided by @ArtfulCoder and did not work.  Is that the correct way to use it? Please correct me if I didn't use the workaround correctly.  And is there other workaround? I'm using Kubernetes 1.5.2.  Thanks.

---
apiVersion: v1
kind: Pod
metadata:
  name: hostnet
  namespace: default
spec:
  hostNetwork: true
  containers:
  - name: busybox
    image: busybox
    command: [ "sh", "-c", "echo
$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT); sleep 1000" ]

**Comment by thockin** [comment]
ClusterFirstWithHostNet

**Comment by bamb00** [comment]
ClusterFirstWithHostNet is available in 1.6 or later, right?

**Comment by bamb00** [comment]
ClusterFirstWithHostNet value is invalid value for 1.5.4

**Comment by thockin** [comment]
yes, 1.6 and higher

**Comment by bamb00** [comment]
Is there a workaround for Kubernetes 1.5.4?

**Comment by thockin** [comment]
I don't think so...

**Comment by smiller171** [comment]
ClusterFirstWithHostNet doesn't seem to work for me with Weave. Is this a known issue or may I be doing something wrong?

**Comment by rgarcia89** [comment]
ClusterFirstWithHostNet same here when using Calico CNI in VXLAN mode...

**Comment by alwaysastudent** [comment]
DNS resolutions are flaky with the setting for Calico VXLAN + CoreDNS
```
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
```
K8s version v1.17.0
