### ISSUE TITLE
Rename RawPodStatus/PodStatus in kubelet

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#17407]
Forked from #17259

We want to rename some types and functions in the container runtime interface.
 -  type RawPodStatus to PodStatus
 - GetPodStatus() to GetAPIPodStatus()  (should be eventually deprecated).
 - GetRawPodStatus() to GetPodStatus()

@Random-Liu, I am assigning this to you so that you do with, or after your pending PRs to avoid rebases.

**Comment by Random-Liu** [comment]
close this issue, because it has been done in #17420. :)
