### ISSUE TITLE
Prune apiserver dependencies

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#17412]
The `pkg/apiserver` package currently has a lot of dependencies:

![image](https://cloud.githubusercontent.com/assets/3272040/11231144/68cd7aee-8d5a-11e5-93d7-efa82fa03822.png)

This is problematic because we would like to use the apiserver library on the kubelet to host the [metrics api group](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/compute-resource-metrics-api.md).

Fortunately, there is lots of low hanging fruit, and many dependencies can be removed by splitting some packages. Once these cases are addressed, we should identify any particularly problematic packages that remain, and make the necessary refactorings to extract those dependencies.

Finally, we should introduce a `ForbiddenDepsTest` which will specify tests as a list of `package, []forbidden` pairs, and verify that `package` does not depend (directly or indirectly) on the forbidden packages.

**Comment by timstclair** [comment]
cc/ @lavalamp

**Comment by timstclair** [comment]
cc/ @nikhiljindal - Is there another issue I can dedup this to?

**Comment by lavalamp** [comment]
I think it's fine to have issues at this level of granularity. I don't think this is a dup, though it's probably a subset of something.

**Comment by nikhiljindal** [comment]
Yes subset of https://github.com/kubernetes/kubernetes/issues/2742.
Fine to have this as a separate issue.

I am trying to extract out the core apiserver library that does not depend on our API.

**Comment by smarterclayton** [comment]
Mostly done by the 1.6 refactors.
