### ISSUE TITLE
Has shippable tests been turned off?

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#17421]
I see there is no shippable tests on recent PRs, has shippable tests been turned off?

We can actually move shippable tests to travis, since travis is more fast than shippable.

**Comment by ihmccreery** [comment]
Yes, Shippable has been turned off.  Travis can't run our integration tests, due to containerization issues, I believe; Travis is just used for building & linting.  We now run unit & integration tests in our own Jenkins instance.
