### ISSUE TITLE
Support exposing a service as ingress

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#17429]
`kubectl expose` should support exposing a service as ingress.

It should probably be the default generator when trying to expose a service and default to exposing everything else ([rcs, pods](https://github.com/kubernetes/kubernetes/blob/2a929883929e64ab2cab2192ae7606de18426e36/pkg/kubectl/cmd/util/factory.go#L289)) as services.

@smarterclayton @bgrant0607 @bprashanth

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by bgrant0607** [comment]
Why would we assume that the service is HTTP? What mapping would be generated?

**Comment by smarterclayton** [comment]
It doesn't have to be http.  An on demand ingress can just as easily be L3,
or TCP over tls.  Mapping can either be automatic or port driven.  Path
settings are really an advanced case.

On Nov 18, 2015, at 8:01 PM, Brian Grant <notifications@github.com> wrote:

Why would we assume that the service is HTTP? What mapping would be
generated?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17429#issuecomment-157913351>
.

**Comment by bprashanth** [comment]
Yeah we'd have to give the user some way to say they wanted one or the other though, right? Today expose creates a new L4 per service. We could have a cluster L7 and make every expose join it (this is what you're thinking right?) or generate an on demand tcp ingress and a new L4 to back that (or sni).  

> Mapping can either be automatic or port driven. 

Can you clarify your port driven idea, 80/443 vs everything else? automatic meaning admin configured at cluster turnup?

**Comment by thockin** [comment]
This is premature, I think.  I don't think ingress is properly ready to
support L3/4 and I don't think it's the most useful thing to spend time
on.  Can we table this until we have more confidence in the Ingress
timeline?

**Comment by bprashanth** [comment]
I think we should revisit this for 1.2 as it will simplify setting up an L7 on cloud providers, but I want to do it via something like: `kubectl expose svc --protocol=http`. 

Just like `--protocol=tcp` (which will remain the default) this will only work on supported platforms and it requires a cluster-global Ingress resource in kube-system. Kubectl would edit this Ingress with a rule like `namespace/svcName -> svc` for each http service exposed this way (allow `--path` for configurable endpoint too?). We could also provide ssl termination for every service exposed this way. 

I'd like to continue ignoring the L4-expose-via-Ingress bit for now. Thoughts?

**Comment by thockin** [comment]
Agree that ignoring L4 in ingress is good.

I dislike the idea of editing a common instance of Ingress, though.  There
are practical limits to sizes, but it's also not tenable from a security
POV.  It can't work on (e.g.) openshift.  This is an advantage of the
routes model in openshift, I guess.

If we don't offer any of the ingress flags, what value does this provide?

**Comment by smarterclayton** [comment]
Tbh the extra flags on expose for Openshift routes lead to confusion
for expose in general - @deads2k and @kargakis and I roughly settled
on "running simple expose should do something logical, but more
complex flags need to be a specific command".  We had proposed moving
complex tls settings and helpers to a "set" command (under the
proposed "kubectl set" heirrarchy discussed elsewhere), which handles
the hardest problem of all (taking certs from end users correctly,
which is unbelievably hard given how poorly certificate authorities
are at giving people correct PEM files).  We can then restrict expose
to the things that are truly needed for it to be useful.

**Comment by bprashanth** [comment]
> If we don't offer any of the ingress flags, what value does this provide?

The main motivation for sharing a global ingress is cost cutting on cloud platforms, I'm not really against  creating one per expose. The main motivation for an "L7 expose" is that we get to hook up everything according to best practices, and hide implementation details like nodePort being a requirement on some clouds. 

Many users today seem to be just interested in loadbalancing a simple :80 -> :443. No urls even, let alone algorithms etc. This might be a sampling adultrated by the beta nature of the resource. 

> I dislike the idea of editing a common instance of Ingress, though.  There
are practical limits to sizes,

I think the target user group has < 10 backends and wants to pile as much as they possibly can on a single ip to cut costs. Users who know what they're doing probably won't bother with `expose` because of how limited it will be. The former can always describe the Service? 

> but it's also not tenable from a security POV.

If you mean privilege escalation, I think that's a solvable problem. We will need an admission controller before we share ingresses cross namespace. 

> It can't work on (e.g.) openshift.  This is an advantage of the routes model in openshift, I guess.

I naively believe this might be easier for OS, IIUC they join everything to a single haproxy anyway. 

> (taking certs from end users correctly, which is unbelievably hard given how poorly certificate authorities are at giving people correct PEM files)

You have a client tool that checks for intermediate certs? Maybe we can have 
```
kubectl create secret tls --pem
```
notify users about that?

**Comment by smarterclayton** [comment]
On Wed, Jan 20, 2016 at 11:04 AM, Prashanth B <notifications@github.com>
wrote:

> If we don't offer any of the ingress flags, what value does this provide?
>
> The main motivation for sharing a global ingress is cost cutting on cloud
> platforms, I'm not really against creating one per expose. The main
> motivation for an "L7 expose" is that we get to hook up everything
> according to best practices, and hide implementation details like nodePort
> being a requirement on some clouds.
>
> Many users today seem to be just interested in loadbalancing a simple :80
> -> :443. No urls even, let alone algorithms etc. This might be a sampling
> adultrated by the beta nature of the resource.
>

In the hundreds of deployments of OpenShift, and tens of thousands of users
accessing it, the vast majority care about L7 HTTP.  A significant minority
care about L4.  A smaller minority care about deep L3.  Most apps are HTTP,
just not all apps.



> I dislike the idea of editing a common instance of Ingress, though. There
> are practical limits to sizes,
>
> I think the target user group has < 10 backends and wants to pile as much
> as they possibly can on a single ip to cut costs. Users who know what
> they're doing probably won't bother with expose because of how limited it
> will be. The former can always describe the Service?
>
but it's also not tenable from a security POV.
>
> If you mean privilege escalation, I think that's a solvable problem. We
> will need an admission controller before we share ingresses cross namespace.
>

We do the control in the router itself (the load balancer controller) -
that's the only place you can get deterministic single writer.


> It can't work on (e.g.) openshift. This is an advantage of the routes
> model in openshift, I guess.
>
> I naively believe this might be easier for OS, IIUC they join everything
> to a single haproxy anyway.
>

We don't - we did that to start, but customers run lots of them.  We use
label selectors to aggregate them.  The routers are controllers that admit
routes.


> (taking certs from end users correctly, which is unbelievably hard given
> how poorly certificate authorities are at giving people correct PEM files)
>
> You have a client tool that checks for intermediate certs? Maybe we can
> have
>
> kubectl create secret tls --pem
>
> notify users about that?
>

Yes that is the right spot.
