### ISSUE TITLE
Containers not starting using private registry

### ISSUE THREAD

**Issue by drughi** [kubernetes/kubernetes#17437]
Hello!

i have a working installation with kubernetes 1.1.1 running on debian

i also have a private registry working nice running in v2 ..

i am facing a weird problem.

defining a pod in master

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: docker-registry.hiberus.com:5000/debian:ssh
  imagePullSecrets:
    - name: myregistrykey

i also have the secret on my master
myregistrykey         kubernetes.io/dockercfg               1         44m

and my config.json is made this way

{
    "auths": {
        "https://docker-registry.hiberus.com:5000": {
            "auth": "anNhdXJhOmpzYXVyYQ==",
            "email": "jsaura@heraldo.es"
        }
    }
}

and so i did the base64 and created my secret.

simple as hell

on my node the image gets pulled without any problem

docker images
REPOSITORY                                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker-registry.hiberus.com:5000/debian   ssh                 3b332951c107        29 minutes ago      183.3 MB
golang                                    1.4                 2819d1d84442        7 days ago          562.7 MB
debian                                    latest              91bac885982d        8 days ago          125.1 MB
gcr.io/google_containers/pause            0.8.0               2c40b0526b63        7 months ago        241.7 kB

but my container does not start 

./kubectl describe pod nginx
Name:               nginx
Namespace:          default
Image(s):           docker-registry.hiberus.com:5000/debian:ssh
Node:               192.168.29.122/192.168.29.122
Start Time:         Wed, 18 Nov 2015 17:08:53 +0100
Labels:             app=nginx
Status:             Running
Reason:
Message:
IP:             172.17.0.2
Replication Controllers:    <none>
Containers:
  nginx:
    Container ID:       docker://3e55ab118a3e5d01d3c58361abb1b23483d41be06741ce747d4c20f5abfeb15f
    Image:          docker-registry.hiberus.com:5000/debian:ssh
    Image ID:           docker://3b332951c1070ba2d7a3bb439787a8169fe503ed8984bcefd0d6c273d22d4370
    State:          Waiting
      Reason:           CrashLoopBackOff
    Last Termination State: Terminated
      Reason:           Error
      Exit Code:        0
      Started:          Wed, 18 Nov 2015 17:08:59 +0100
      Finished:         Wed, 18 Nov 2015 17:08:59 +0100
    Ready:          False
    Restart Count:      2
    Environment Variables:
Conditions:
  Type      Status
  Ready     False
Volumes:
  default-token-ha0i4:
    Type:   Secret (a secret that should populate this volume)
    SecretName: default-token-ha0i4
Events:
  FirstSeen LastSeen    Count   From                SubobjectPath               Reason      Message
  ─────────   ────────    ───── ────                ─────────────             ──────      ───────
  16s       16s     1   {kubelet 192.168.29.122}    implicitly required container POD   Created     Created with docker id 4a063be27162
  16s       16s     1   {kubelet 192.168.29.122}    implicitly required container POD   Pulled      Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  16s       16s     1   {kubelet 192.168.29.122}    implicitly required container POD   Started     Started with docker id 4a063be27162
  16s       16s     1   {kubelet 192.168.29.122}    spec.containers{nginx}          Pulling     Pulling image "docker-registry.hiberus.com:5000/debian:ssh"
  15s       15s     1   {scheduler }                                Scheduled   Successfully assigned nginx to 192.168.29.122
  11s       11s     1   {kubelet 192.168.29.122}    spec.containers{nginx}          Created     Created with docker id 36df2dc8b999
  11s       11s     1   {kubelet 192.168.29.122}    spec.containers{nginx}          Pulled      Successfully pulled image "docker-registry.hiberus.com:5000/debian:ssh"
  11s       11s     1   {kubelet 192.168.29.122}    spec.containers{nginx}          Started     Started with docker id 36df2dc8b999
  10s       10s     1   {kubelet 192.168.29.122}    spec.containers{nginx}          Pulled      Container image "docker-registry.hiberus.com:5000/debian:ssh" already present on machine
  10s       10s     1   {kubelet 192.168.29.122}    spec.containers{nginx}          Created     Created with docker id 3e55ab118a3e
  10s       10s     1   {kubelet 192.168.29.122}    spec.containers{nginx}          Started     Started with docker id 3e55ab118a3e
  5s        5s      1   {kubelet 192.168.29.122}    spec.containers{nginx}          Backoff     Back-off restarting failed docker container

it loops internally trying to start but it never does

the weird thing is that if y do a run command on my node manually the container starts without any problem, but using the pod pulls the image but never starts ..

am i doing something wrong?

if i use  a public image for my pod it starts without any problem .. this only happends to me when using private images ..

thanks in advance, i am puzzled :/

**Comment by brenix** [comment]
Try taking auths out and make it all one line (like below) before encoding it to base64:

     {"https://docker-registry.hiberus.com:5000": {"auth": "anNhdXJhOmpzYXVyYQ==","email": jsaura@heraldo.es"}

**Comment by drughi** [comment]
hello

ok i will try now, think i tired before but i an gonna check it

thanks!

**Comment by drughi** [comment]
no luck putting it into a single line like you said

> {"https://docker-registry.hiberus.com:5000": {"auth": "anNhdXJhOmpzYXVyYQ==","email": jsaura@heraldo.es"}

i did the base encode, reload the secret on master, deploy the pod again, and it starts looping again

root@kubernetes-master:/opt/kubernetes# ./kubectl describe pod nginx
Name:				nginx
Namespace:			default
Image(s):			docker-registry.hiberus.com:5000/debian:ssh
Node:				192.168.29.122/192.168.29.122
Start Time:			Thu, 19 Nov 2015 09:37:35 +0100
Labels:				app=nginx
Status:				Running
Reason:
Message:
IP:				172.17.0.2
Replication Controllers:	<none>
Containers:
  nginx:
    Container ID:		docker://a8affe209fcb313daa244271941ea361b9656ec129edd253bf7996504419714c
    Image:			docker-registry.hiberus.com:5000/debian:ssh
    Image ID:			docker://3b332951c1070ba2d7a3bb439787a8169fe503ed8984bcefd0d6c273d22d4370
    State:			Waiting
      Reason:			CrashLoopBackOff
    Last Termination State:	Terminated
      Reason:			Error
      Exit Code:		0
      Started:			Thu, 19 Nov 2015 09:38:34 +0100
      Finished:			Thu, 19 Nov 2015 09:38:34 +0100
    Ready:			False
    Restart Count:		4
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False
Volumes:
  default-token-ha0i4:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	default-token-ha0i4
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath				Reason		Message
  ─────────	────────	─────	────				─────────────				──────		───────
  1m		1m		1	{kubelet 192.168.29.122}	implicitly required container POD	Created		Created with docker id 893d04784bdf
  1m		1m		1	{kubelet 192.168.29.122}	implicitly required container POD	Started		Started with docker id 893d04784bdf
  1m		1m		1	{kubelet 192.168.29.122}	implicitly required container POD	Pulled		Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  1m		1m		1	{kubelet 192.168.29.122}	spec.containers{nginx}			Created		Created with docker id e87102f0724f
  1m		1m		1	{kubelet 192.168.29.122}	spec.containers{nginx}			Started		Started with docker id e87102f0724f
  1m		1m		1	{scheduler }								Scheduled	Successfully assigned nginx to 192.168.29.122
  1m		1m		1	{kubelet 192.168.29.122}	spec.containers{nginx}			Created		Created with docker id aab86d11118e
  1m		1m		1	{kubelet 192.168.29.122}	spec.containers{nginx}			Started		Started with docker id aab86d11118e
  1m		1m		1	{kubelet 192.168.29.122}	spec.containers{nginx}			Created		Created with docker id d2e00527dc77
  1m		1m		1	{kubelet 192.168.29.122}	spec.containers{nginx}			Started		Started with docker id d2e00527dc77
  1m		32s		4	{kubelet 192.168.29.122}	spec.containers{nginx}			Pulled		Container image "docker-registry.hiberus.com:5000/debian:ssh" already present on machine
  32s		32s		1	{kubelet 192.168.29.122}	spec.containers{nginx}			Created		Created with docker id a8affe209fcb
  31s		31s		1	{kubelet 192.168.29.122}	spec.containers{nginx}			Started		Started with docker id a8affe209fcb
  1m		12s		5	{k

on minion kubelet only says this

nov 19 09:32:46 minion01 kubelet[15150]: W1119 09:32:46.361138   15150 reflector.go:245] pkg/kubelet/kubelet.go:210: watch of *api.Service ended with: 401: The evvent in requested index is outdated and cleared [24596/23818]) [25595	
nov 19 09:37:36 minion01 kubelet[15150]: E1119 09:37:36.307650   15150 manager.go:1920] Error running pod "nginx_default" container "nginx": exceeded maxTries, some processes might not have desired OOM score
nov 19 09:37:44 minion01 kubelet[15150]: E1119 09:37:44.019987   15150 manager.go:1920] Error running pod "nginx_default" container "nginx": exceeded maxTries, some processes might not have desired OOM score
nov 19 09:37:53 minion01 kubelet[15150]: I1119 09:37:53.737492   15150 manager.go:2022] Back-off 10s restarting failed container=nginx pod=nginx_default
nov 19 09:38:04 minion01 kubelet[15150]: E1119 09:38:04.071134   15150 manager.go:1920] Error running pod "nginx_default" container "nginx": exceeded maxTries, some processes might not have desired OOM score
nov 19 09:38:13 minion01 kubelet[15150]: I1119 09:38:13.737260   15150 manager.go:2022] Back-off 20s restarting failed container=nginx pod=nginx_default
nov 19 09:38:23 minion01 kubelet[15150]: I1119 09:38:23.735727   15150 manager.go:2022] Back-off 20s restarting failed container=nginx pod=nginx_default
nov 19 09:38:34 minion01 kubelet[15150]: E1119 09:38:34.021409   15150 manager.go:1920] Error running pod "nginx_default" container "nginx": exceeded maxTries, some processes might not have desired OOM score
nov 19 09:38:43 minion01 kubelet[15150]: I1119 09:38:43.741968   15150 manager.go:2022] Back-off 40s restarting failed container=nginx pod=nginx_default
nov 19 09:38:53 minion01 kubelet[15150]: I1119 09:38:53.742604   15150 manager.go:2022] Back-off 40s restarting failed container=nginx pod=nginx_default
nov 19 09:39:03 minion01 kubelet[15150]: I1119 09:39:03.740848   15150 manager.go:2022] Back-off 40s restarting failed container=nginx pod=nginx_default


any idea?

if i list docker images on minion i see the container launched and being killed .. its spawning but it does not remain up

**Comment by drughi** [comment]
i have enabled more log level on kubelet

Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.283664    7508 config.go:252] Setting pods for source api
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.283880    7508 config.go:382] Receiving a new pod "nginx_default"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.283953    7508 kubelet.go:2005] SyncLoop (ADD): "nginx_default"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.284123    7508 kubelet.go:1986] SyncLoop (housekeeping)
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.286478    7508 volumes.go:109] Used volume plugin "kubernetes.io/secret" for default-token-ha0i4
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.286570    7508 secret.go:127] Setting up volume default-token-ha0i4 for pod 907c4178-8e9b-11e5-9e33-0050568153a7 at /var/lib/kubelet/pods/907c4178-8e9b-11e5-9e33-0050568153a7/volumes/kubernetes.io~secret/default-token-ha0i4
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.286609    7508 volumes.go:109] Used volume plugin "kubernetes.io/empty-dir" for
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.286750    7508 empty_dir_linux.go:39] Determining mount medium of /var/lib/kubelet/pods/907c4178-8e9b-11e5-9e33-0050568153a7/volumes/kubernetes.io~secret/default-token-ha0i4
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.286782    7508 empty_dir_linux.go:49] Statfs_t of %v: %+v/var/lib/kubelet/pods/907c4178-8e9b-11e5-9e33-0050568153a7/volumes/kubernetes.io~secret/default-token-ha0i4{61267 4096 7381523 6695457 6314734 1884160 1804941 {[547127878 499799027]} 255 4096 4128 [0 0 0 0]}
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.286879    7508 empty_dir.go:221] pod 907c4178-8e9b-11e5-9e33-0050568153a7: mounting tmpfs for volume  with opts []
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.286902    7508 mount_linux.go:97] Mounting tmpfs /var/lib/kubelet/pods/907c4178-8e9b-11e5-9e33-0050568153a7/volumes/kubernetes.io~secret/default-token-ha0i4 tmpfs []
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.289948    7508 volumes.go:193] Making a volume.Cleaner for volume kubernetes.io~secret/default-token-ha0i4 of pod 907c4178-8e9b-11e5-9e33-0050568153a7
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.290038    7508 volumes.go:229] Used volume plugin "kubernetes.io/secret" for 907c4178-8e9b-11e5-9e33-0050568153a7/kubernetes.io~secret
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.297168    7508 secret.go:153] Received secret default/default-token-ha0i4 containing (1) pieces of data, 846 total bytes
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.297215    7508 secret.go:158] Writing secret data default/default-token-ha0i4/token (846 bytes) to host file /var/lib/kubelet/pods/907c4178-8e9b-11e5-9e33-0050568153a7/volumes/kubernetes.io~secret/default-token-ha0i4/token
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.298257    7508 kubelet.go:1397] Not generating pod status for new pod "nginx_default"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.302155    7508 manager.go:1687] Syncing Pod &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:nginx GenerateName: Namespace:default SelfLink:/api/v1/namespaces/default/pods/nginx UID:907c4178-8e9b-11e5-9e33-0050568153a7 ResourceVersion:35605 Generation:0 CreationTimestamp:2015-11-19 09:57:29 +0100 CET DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:nginx] Annotations:map[kubernetes.io/config.source:api kubernetes.io/config.seen:2015-11-19T09:57:27.28389115+01:00]} Spec:{Volumes:[{Name:default-token-ha0i4 VolumeSource:{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil> Secret:0xc209b3add0 NFS:<nil> ISCSI:<nil> Glusterfs:<nil> PersistentVolumeClaim:<nil> RBD:<nil> Cinder:<nil> CephFS:<nil> Flocker:<nil> DownwardAPI:<nil> FC:<nil>}}] Containers:[{Name:nginx Image:docker-registry.hiberus.com:5000/debian:ssh Command:[] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-ha0i4 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false}] RestartPolicy:Always TerminationGracePeriodSeconds:0xc209b3adc8 ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:map[] ServiceAccountName:default NodeName:192.168.29.122 HostNetwork:false HostPID:false HostIPC:false ImagePullSecrets:[{Name:myregistrykey}]} Status:{Phase:Pending Conditions:[] Message: Reason: HostIP: PodIP: StartTime:<nil> ContainerStatuses:[]}}, podFullName: "nginx_default", uid: "907c4178-8e9b-11e5-9e33-0050568153a7"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.302483    7508 manager.go:1707] Need to restart pod infra container for "nginx_default" because it is not found
Nov 19 09:57:27 minion01 docker[15252]: time="2015-11-19T09:57:27.303333900+01:00" level=info msg="GET /images/gcr.io/google_containers/pause:0.8.0/json"

Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.302582    7508 manager.go:1726] Container {Name:nginx Image:docker-registry.hiberus.com:5000/debian:ssh Command:[] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-ha0i4 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.

Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.302658    7508 manager.go:1817] Got container changes for pod "nginx_default": {StartInfraContainer:true InfraContainerId: ContainersToStart:map[0:{}] ContainersToKeep:map[]}
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.302694    7508 manager.go:1823] Killing Infra Container for "nginx_default", will start new one
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.302711    7508 manager.go:1856] Creating pod infra container for "nginx_default"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.317720    7508 manager.go:223] Status for pod "nginx_default" updated successfully
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.318254    7508 config.go:252] Setting pods for source api
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.334019    7508 server.go:726] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx", UID:"907c4178-8e9b-11e5-9e33-0050568153a7", APIVersion:"v1", ResourceVersion:"35605", FieldPath:"implicitly required container POD"}): reason: 'Pulled' Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.334201    7508 kubelet.go:929] Will create hosts mount for container:"POD", podIP:: false
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.334409    7508 manager.go:752] Container default/nginx/POD: setting entrypoint "[]" and command "[]"

Nov 19 09:57:27 minion01 docker[15252]: time="2015-11-19T09:57:27.389869535+01:00" level=info msg="GET /containers/json"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.470343    7508 server.go:726] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx", UID:"907c4178-8e9b-11e5-9e33-0050568153a7", APIVersion:"v1", ResourceVersion:"35605", FieldPath:"implicitly required container POD"}): reason: 'Created' Created with docker id 6479aa1aa6d7
Nov 19 09:57:27 minion01 docker[15252]: time="2015-11-19T09:57:27.471683734+01:00" level=info msg="POST /containers/6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42/start"
Nov 19 09:57:27 minion01 docker[15252]: time="2015-11-19T09:57:27.519724766+01:00" level=info msg="GET /containers/json"
Nov 19 09:57:27 minion01 systemd[1]: Failed to set cpu.cfs_period_us on /system.slice/docker-6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42.scope: Permission denied
Nov 19 09:57:27 minion01 systemd[1]: Failed to set cpu.cfs_quota_us on /system.slice/docker-6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42.scope: Permission denied
Nov 19 09:57:27 minion01 systemd[1]: Failed to set cpu.cfs_period_us on /system.slice/var-lib-kubelet-pods-907c4178\x2d8e9b\x2d11e5\x2d9e33\x2d0050568153a7-volumes-kubernetes.io\x7esecret-default\x2dtoken\x2dha0i4.mount: Permission denied
Nov 19 09:57:27 minion01 systemd[1]: Failed to set cpu.cfs_quota_us on /system.slice/var-lib-kubelet-pods-907c4178\x2d8e9b\x2d11e5\x2d9e33\x2d0050568153a7-volumes-kubernetes.io\x7esecret-default\x2dtoken\x2dha0i4.mount: Permission denied
Nov 19 09:57:27 minion01 docker[15252]: time="2015-11-19T09:57:27.575175948+01:00" level=info msg="GET /containers/6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42/json"
Nov 19 09:57:27 minion01 docker[15252]: time="2015-11-19T09:57:27.895646534+01:00" level=warning msg="Your kernel does not support OOM notifications: There is no path for \"memory\" in state"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.896379    7508 server.go:726] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx", UID:"907c4178-8e9b-11e5-9e33-0050568153a7", APIVersion:"v1", ResourceVersion:"35605", FieldPath:"implicitly required container POD"}): reason: 'Started' Started with docker id 6479aa1aa6d7
Nov 19 09:57:27 minion01 docker[15252]: time="2015-11-19T09:57:27.898341328+01:00" level=info msg="GET /containers/6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42/json"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.928687    7508 factory.go:78] Using factory "docker" for container "/system.slice/docker-6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42.scope"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.929389    7508 manager.go:1596] DNS ResolvConfPath exists: /var/lib/docker/containers/6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42/resolv.conf. Will attempt to add ndots option: options nods:5

Nov 19 09:57:27 minion01 docker[15252]: time="2015-11-19T09:57:27.930153038+01:00" level=info msg="GET /containers/6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42/json"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.934937    7508 manager.go:803] Added container: "/system.slice/docker-6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42.scope" (aliases: [k8s_POD.6d00e006_nginx_default_907c4178-8e9b-11e5-9e33-0050568153a7_93463dbf 6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42], namespace: "docker")
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.936013    7508 handler.go:322] Added event &{/system.slice/docker-6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42.scope 2015-11-19 08:57:27.405478432 +0000 UTC containerCreation {<nil>}}
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.936156    7508 factory.go:71] Error trying to work out if we can handle /system.slice/var-lib-kubelet-pods-907c4178\x2d8e9b\x2d11e5\x2d9e33\x2d0050568153a7-volumes-kubernetes.io\x7esecret-default\x2dtoken\x2dha0i4.mount: invalid container name
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.936173    7508 factory.go:82] Factory "docker" was unable to handle container "/system.slice/var-lib-kubelet-pods-907c4178\\x2d8e9b\\x2d11e5\\x2d9e33\\x2d0050568153a7-volumes-kubernetes.io\\x7esecret-default\\x2dtoken\\x2dha0i4.mount"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.936159    7508 container.go:368] Start housekeeping for container "/system.slice/docker-6479aa1aa6d7e103912218883bf68975ee141554fb46051b94ba25f8e5726b42.scope"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.936206    7508 factory.go:78] Using factory "raw" for container "/system.slice/var-lib-kubelet-pods-907c4178\\x2d8e9b\\x2d11e5\\x2d9e33\\x2d0050568153a7-volumes-kubernetes.io\\x7esecret-default\\x2dtoken\\x2dha0i4.mount"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.936406    7508 manager.go:803] Added container: "/system.slice/var-lib-kubelet-pods-907c4178\\x2d8e9b\\x2d11e5\\x2d9e33\\x2d0050568153a7-volumes-kubernetes.io\\x7esecret-default\\x2dtoken\\x2dha0i4.mount" (aliases: [], namespace: "")
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.936556    7508 handler.go:322] Added event &{/system.slice/var-lib-kubelet-pods-907c4178\x2d8e9b\x2d11e5\x2d9e33\x2d0050568153a7-volumes-kubernetes.io\x7esecret-default\x2dtoken\x2dha0i4.mount 2015-11-19 09:57:27.569845336 +0100 CET containerCreation {<nil>}}
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.936622    7508 container.go:368] Start housekeeping for container "/system.slice/var-lib-kubelet-pods-907c4178\\x2d8e9b\\x2d11e5\\x2d9e33\\x2d0050568153a7-volumes-kubernetes.io\\x7esecret-default\\x2dtoken\\x2dha0i4.mount"

153a7-volumes-kubernetes.io\\x7esecret-default\\x2dtoken\\x2dha0i4.mount"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.949794    7508 hairpin.go:97] Enabling hairpin on interface veth8249cbe
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.949901    7508 manager.go:1893] Creating container &{Name:nginx Image:docker-registry.hiberus.com:5000/debian:ssh Command:[] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-ha0i4 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false} in pod nginx_default
Nov 19 09:57:27 minion01 docker[15252]: time="2015-11-19T09:57:27.950440150+01:00" level=info msg="GET /images/docker-registry.hiberus.com:5000/debian:ssh/json"
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.951960    7508 kubelet.go:929] Will create hosts mount for container:"nginx", podIP:172.17.0.2: true
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.951951    7508 server.go:726] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx", UID:"907c4178-8e9b-11e5-9e33-0050568153a7", APIVersion:"v1", ResourceVersion:"35605", FieldPath:"spec.containers{nginx}"}): reason: 'Pulled' Container image "docker-registry.hiberus.com:5000/debian:ssh" already present on machine
Nov 19 09:57:27 minion01 kubelet[7508]: I1119 09:57:27.952453    7508 manager.go:752] Container default/nginx/nginx: setting entrypoint "[]" and command "[]"

ov 19 09:57:28 minion01 docker[15252]: time="2015-11-19T09:57:28.027748310+01:00" level=info msg="GET /containers/json"
Nov 19 09:57:28 minion01 kubelet[7508]: I1119 09:57:28.050106    7508 server.go:726] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx", UID:"907c4178-8e9b-11e5-9e33-0050568153a7", APIVersion:"v1", ResourceVersion:"35605", FieldPath:"spec.containers{nginx}"}): reason: 'Created' Created with docker id dd85def9a5d1
Nov 19 09:57:28 minion01 docker[15252]: time="2015-11-19T09:57:28.051005383+01:00" level=info msg="POST /containers/dd85def9a5d14e3ce196a7224b5b8a5bc4cb7c39fe500d3d0d362ef712757e5c/start"
Nov 19 09:57:28 minion01 systemd[1]: Failed to set cpu.cfs_period_us on /system.slice/docker-dd85def9a5d14e3ce196a7224b5b8a5bc4cb7c39fe500d3d0d362ef712757e5c.scope: Permission denied
Nov 19 09:57:28 minion01 systemd[1]: Failed to set cpu.cfs_quota_us on /system.slice/docker-dd85def9a5d14e3ce196a7224b5b8a5bc4cb7c39fe500d3d0d362ef712757e5c.scope: Permission denied
Nov 19 09:57:28 minion01 docker[15252]: time="2015-11-19T09:57:28.074715385+01:00" level=info msg="GET /containers/dd85def9a5d14e3ce196a7224b5b8a5bc4cb7c39fe500d3d0d362ef712757e5c/json"
Nov 19 09:57:28 minion01 docker[15252]: time="2015-11-19T09:57:28.162710312+01:00" level=info msg="GET /containers/json"
Nov 19 09:57:28 minion01 docker[15252]: time="2015-11-19T09:57:28.206502749+01:00" level=warning msg="Your kernel does not support OOM notifications: There is no path for \"memory\" in state"
Nov 19 09:57:28 minion01 kubelet[7508]: I1119 09:57:28.207433    7508 server.go:726] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx", UID:"907c4178-8e9b-11e5-9e33-0050568153a7", APIVersion:"v1", ResourceVersion:"35605", FieldPath:"spec.containers{nginx}"}): reason: 'Started' Started with docker id dd85def9a5d1
Nov 19 09:57:28 minion01 kubelet[7508]: I1119 09:57:28.207722    7508 factory.go:78] Using factory "docker" for container "/system.slice/docker-dd85def9a5d14e3ce196a7224b5b8a5bc4cb7c39fe500d3d0d362ef712757e5c.scope"
Nov 19 09:57:28 minion01 docker[15252]: time="2015-11-19T09:57:28.209606918+01:00" level=info msg="GET /containers/dd85def9a5d14e3ce196a7224b5b8a5bc4cb7c39fe500d3d0d362ef712757e5c/json"
Nov 19 09:57:28 minion01 docker[15252]: time="2015-11-19T09:57:28.210416796+01:00" level=info msg="GET /containers/dd85def9a5d14e3ce196a7224b5b8a5bc4cb7c39fe500d3d0d362ef712757e5c/json"
Nov 19 09:57:28 minion01 kubelet[7508]: E1119 09:57:28.212190    7508 manager.go:1920] Error running pod "nginx_default" container "nginx": exceeded maxTries, some processes might not have desired OOM score

and then starts looping starting it :(

**Comment by drughi** [comment]
still no luck 

i have added an ubuntu node for discarding debian systems bug and same behavior,containers respawns and never starts ..

any help please? this is really weird

**Comment by drughi** [comment]
more info

i have downloaded from git last version and compiled it now i have this info

I1120 12:27:50.649995    2321 kubelet.go:2008] SyncLoop (UPDATE): "prueba_default"
I1120 12:27:50.650272    2321 kubelet.go:1986] SyncLoop (housekeeping)
I1120 12:27:50.711504    2321 volumes.go:193] Making a volume.Cleaner for volume kubernetes.io~secret/default-token-hxuq3 of pod b0a60cd3-8f79-11e5-9e33-0050568153a7
I1120 12:27:50.711575    2321 volumes.go:229] Used volume plugin "kubernetes.io/secret" for b0a60cd3-8f79-11e5-9e33-0050568153a7/kubernetes.io~secret
I1120 12:27:50.711655    2321 kubelet.go:1615] Keeping terminated pod "prueba_default" and uid "b0a60cd3-8f79-11e5-9e33-0050568153a7", still running
I1120 12:27:50.712272    2321 manager.go:1404] Killing container "f2d2112c19de963a031e506bed6ca67ab672fbc354fd252dc2db84528893604e default/prueba" with 30 second grace period
I1120 12:27:50.731738    2321 manager.go:858] Destroyed container: "/docker-daemon/docker/f2d2112c19de963a031e506bed6ca67ab672fbc354fd252dc2db84528893604e" (aliases: [k8s_POD.6d00e006_prueba_default_b0a60cd3-8f79-11e5-9e33-0050568153a7_7e8fe810 f2d2112c19de963a031e506bed6ca67ab672fbc354fd252dc2db84528893604e], namespace: "docker")
I1120 12:27:50.731850    2321 handler.go:322] Added event &{/docker-daemon/docker/f2d2112c19de963a031e506bed6ca67ab672fbc354fd252dc2db84528893604e 2015-11-20 12:27:50.731826372 +0100 CET containerDeletion {<nil>}}
I1120 12:27:50.880245    2321 manager.go:1438] Container "f2d2112c19de963a031e506bed6ca67ab672fbc354fd252dc2db84528893604e default/prueba" exited after 167.895773ms
I1120 12:27:50.880342    2321 kubelet.go:2728] Generating status for "prueba_default"

why is it killing the container within grace period?

**Comment by drughi** [comment]
please any clue? if have even tried using service accounts, and moving to ubuntu 10.04 LTS still the same problem,

thanks
