### ISSUE TITLE
Proposal for upstreaming OpenShift policy / auth components as a Kube extension

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#17440]
In order to
1. An example of external authorizations / authentication in the upstream Kube repo that can provide more sophisticated behavior than the simple checked in code
2. To prove that we can integrate 3rd party extension APIs in a clean way that do not live in the Kube codebase (via reuse of a shared 3rd party library, verify discovery works, prevent refactorings from breaking 3rd parties)

We're looking to split the Origin policy engine (supporting full namespace auth and user facing apis) and Origin user/group resources (supporting LDAP, integration with 3rd party github, etc) into their own project that can be easily integrated with Kube.

To do this, there are some up front questions that need to be answered:
1. Do we want to encourage Kube ecosystem pieces to be in the `kubernetes/` GitHub organization?
   1. How do we add ecosystem pieces to a regular flow (build, test, e2e) without being in the org and having some control?
   2. How do we appropriately label contributions that may overlap?
2. Do we want to encourage Kube ecosystem pieces to be focused on usefulness, or on clear decomposition?  Put another way, how willing are we to accept ecosystem parts that may be coupled (like any UAA server) together, but which breaking up may not make technical sense?

One plan might be
1. Ensure the upstream apiserver libraries are present for easily building a new client api server
2. Create a `kubernetes/kubernetes-uaa-server` project that contains the extracted components from OpenShift, marked as "ecosystem project", reusing those libraries and exposing a set of new apigroups to Kube
3. Add a kubernetes plugin for authz/authn to the Kube repo and e2e tests that validate that kubernetes-uaa continues to run and serve auth even when we iterate on Kube
4. Manage the `kubernetes-uaa-server` project as one possible way to run auth, integrated with Kube, documenting and describing it but making it clear that it is not part of the core.  Develop a set of processes for curating projects like this that are not part of the core, but reuse the same tools and patterns.

@bgrant0607 @liggitt @pweil- @ncdc @erictune

**Comment by bgrant0607** [comment]
Would be useful.

Ecosystem components in kubernetes org: Yes, if we like them.

CI and github automation for other repos: Yes, we need to solve that problem, for the UI, deployment manager, apiserver, contrib, etc.

Focus on usefulness. That's what we've done in K8s. Not everything needs to be independently usable, at least not now.

cc @lavalamp

**Comment by ncdc** [comment]
Also see #12209

**Comment by erictune** [comment]
Overall proposal sounds good to me.

I'm wondering if which Openshift Authentication plugins can be upstreamed to Kubernetes without depending on use of Group and User objects?   @liggitt may know.

**Comment by erictune** [comment]
@lavalamp @nikhiljindal

**Comment by erictune** [comment]
Also, do you see Origin Policy Engine as encompassing just the types [here](https://github.com/openshift/origin/blob/b12d9f1eb6de50f3fb2ddfb8ad4122797625d120/pkg/authorization/api/types.go), namely:
`PolicyRule, Role, RoleBinding, Policy, PolicyBinding, ResourceAccessReviewResponse, ResourceAccessReview, SubjectAccessReviewResponse, SubjectAccessReview, LocalResourceAccessReview, LocalResourceAccessReview` and their `Cluster*` and `*List` variants.

Or would you also include things that implement PodSecurityPolicy, and the like?

**Comment by smarterclayton** [comment]
Right now PSP is separate, seems likely to remain so.  As we've talked
about policy, we've wanted to see some unification, but I don't think it's
clear how that would be achieved.

There are similarities - for instance, being able to /bind
PodSecurityPolicy to a subject (user, group, or service account) is a lot
like the use case for role bindings.  But allowing them to evolve
separately is probably best for now (namespace defaulting, limits, and
quota are all "policy", but it's hard to say they should be coupled).

It's possible that Policy would be better named "AccessPolicy" or
"ActionPolicy" to distinguish it from other policies.

On Nov 19, 2015, at 9:29 PM, Eric Tune <notifications@github.com> wrote:

Also, do you see Origin Policy Engine as encompassing just the types here
<https://github.com/openshift/origin/blob/b12d9f1eb6de50f3fb2ddfb8ad4122797625d120/pkg/authorization/api/types.go>,
namely:
PolicyRule, Role, RoleBinding, Policy, PolicyBinding,
ResourceAccessReviewResponse, ResourceAccessReview,
SubjectAccessReviewResponse, SubjectAccessReview,
LocalResourceAccessReview, LocalResourceAccessReview and their Cluster* and
*List variants.

Or would you also include things that implement PodSecurityPolicy, and the
like?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17440#issuecomment-158261272>
.

**Comment by lavalamp** [comment]
The primary thing you need from us here is for apiserver infrastructure to be cleanly reusable, right?

**Comment by smarterclayton** [comment]
I would like to be a Guinea pig there for its usability, yes.  We could
however run today as soon as we add a simple, versioned Client authorizer
to Kube.  The auth engine is already something that runs standalone in an
image.

On Nov 20, 2015, at 7:22 PM, Daniel Smith <notifications@github.com> wrote:

The primary thing you need from us here is for apiserver infrastructure to
be cleanly reusable, right?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17440#issuecomment-158565744>
.

**Comment by smarterclayton** [comment]
It could also register itself with API discovery


On Nov 20, 2015, at 7:22 PM, Daniel Smith <notifications@github.com> wrote:

The primary thing you need from us here is for apiserver infrastructure to
be cleanly reusable, right?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17440#issuecomment-158565744>
.

**Comment by philips** [comment]
I read through the UAA docs and it seems like the overall proposal is for the API to hold on to sessions? But, it doesn't use cookie headers. Why not just use cookies?

**Comment by liggitt** [comment]
Cookies against an API are dangerous. That requires adding CSRF prevention to the API, which then means non-browser API clients have to jump through hoops.

**Comment by davidopp** [comment]
This is marked as v1.2 milestone. Is there anything actionable in the week remaining before we cut the release branch?

**Comment by erictune** [comment]
No.  The  impl is not going to be complete in 1.2 afaics.

**Comment by smarterclayton** [comment]
This is effectively done.
