### ISSUE TITLE
Kubernetes application definition

### ISSUE THREAD

**Issue by jackgr** [kubernetes/kubernetes#17447]
Forked from #17027.

Currently, there is no way to define higher level types in Kubernetes. For example, there's no way to abstractly define a Redis cluster, consisting of a Redis master, which consists of a service and replication controller, plus a set of Redis slaves, each of which consists of a service and replication controller pair, with appropriate wiring between the master and slaves.

Granted, one can easily instantiate the replication controllers and services, as demonstrated by [the guestbook example](https://github.com/kubernetes/kubernetes/tree/22e527fe2577e2ee29d557681ee388b2d10b91a6/examples/guestbook). Likewise, the Redis slaves in that example have a priori knowledge of the name of the Redis master service, and the port it's using. All fine for something hard wired.

However, these mechanisms don't generalize well. There's no programmatically discoverable information that identifies the pieces as part of a Redis cluster, or which exposes the role that each one plays.

Yes, there are labels, such as `app:redis` and `role:slave`. But those are ad hoc strings, not clearly related to each other or described by any form of type definition. Consequently, there's no way to programmatically determine what labels to use when creating a Redis cluster, or more importantly what labels were used to create a Redis cluster and its components.

Likewise, the dependencies between services are not defined in a discoverable way. How then can one assemble an application from multiple standalone services which didn't know a priori that they would be used together in that specific configuration?

We have opportunity at this point to move beyond configuration format discussions, and define a firmer notion of application for Kubernetes. While an application will likely be defined by one or more types or templates, it also needs metadata that tools and controllers can use to reason about it... e.g., metadata that:
- describes its monitoring, logging and alerting configuration,
- allows it to be listed in a marketplace,
- helps Ubernetes schedule it and/or its constituent components, etc.

Ultimately, we need to make it easy to answer questions like:
- What applications are running in this Kubernetes cluster?
- What components comprise a given application and how are they organized?
- How is component X configured and what other components does it use?
- What Kubernetes resources comprise component X?
- How is a Redis (Cassandra, RabbitMQ, Storm, Kafka) cluster defined?
- What are its configuration points?

The purpose of this issue is to start a discussion about what constitutes applications and components, and how they are defined/expressed.

**Comment by smarterclayton** [comment]
> Likewise, the dependencies between services are not defined in a discoverable way. How then can one assemble an application from multiple standalone services which didn't know a priori that they would be used together in that specific configuration?

Depend on whether you are building (accumulating) or defining (all at once) such an application.  They are two different problems (making it easy to add and consume services, vs defining the relationships between a set of components all at once), and we want that to be a clear spectrum.

Things we have said so far (in many different discussions of which only Brian knows the numbers):

1. We want to be able to capture the fundamentals of an application as a list of API objects, with unimportant values not specified
2. We want to make it easy to snapshot a set of kube objects out of a running system and transform them into a list of API objects suitable for instantiation elsewhere
3. We want it to be easy to take 1 or 2 and deploy them multiple times into multiple contexts
4. We want it to be easy to adapt existing applications into the Kube model by providing a wealth of transformation steps from external data into the actual pod container environment (downward api, volumes, init container, etc)
5. We want to be able to take repeatedly take the definition of an application in one namespace and move it to a different namespace easily (dev -> prod) with the things that are different separated (config, secrets, volumes, external services)
6. We want to be able to treat services as both concrete local implementation and references to remote services
7. We want to minimize the automatic elements of service injection into pods and replace it with a better declarative mechanism

**Comment by smarterclayton** [comment]
Why would you programmatically determine the set of labels for an application on creation?

**Comment by jackgr** [comment]
> Things we have said so far (in many different discussions of which only Brian knows the numbers):

Great list. Nice to have it extracted from the various issues and compiled into one place.

**Comment by jackgr** [comment]
> Why would you programmatically determine the set of labels for an application on creation?

Because you're creating objects programmatically from type definitions. The assumption here is that instead of creating everything in its own one-off way, we will define mechanisms that make it easy to create things from descriptions. I think that's the point of 7. in the list above, but it applies equally well to resources.

For example, with DM, one can create a Redis type that defines the labels to be applied, as well as other conventions, and that exposes the configuration points relevant to Redis (e.g., number of slaves). Granted, it's only a template, but this is a step in the right direction, IMO, since using such a template makes it possible to capture information about the higher level abstraction called Redis, and to then use that information to reason about it.

**Comment by jackgr** [comment]
> Ah - you're saying, what labels do we use.

Well, sort of. Actually, I'm saying more than that. I'd like to be able to chase a label to some kind of type definition. If the thing says it's an "app:redis", then I'd like to find some definition of "app:redis" that tells me something about what that kind of thing looks like.

**Comment by bgrant0607** [comment]
Service catalog is vaguely related: #17543

**Comment by bgrant0607** [comment]
This has been superseded by work in SIG Service Catalog and in the Application Definition Working Group. In both cases, ongoing work isn't in this repo, so closing as obsolete.
