### ISSUE TITLE
Ensure Logging Conventions Are Implemented

### ISSUE THREAD

**Issue by ashcrow** [kubernetes/kubernetes#17449]
https://github.com/kubernetes/kubernetes/pull/17438 noted a location where the logging did not meet the [conventions](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/logging.md). There is possibly other areas in the codebase that are not following the conventions and should be found and brought up to date. This issue is opened for folks who would like to fix specific areas of the codebase and reference an issue or, alternately, review and note that a section is following conventions.

**Comment by crassirostris** [comment]
/sig instrumentation

There are a lot of such places now and also ~ a dozen different verbosity levels used (not including vendor dir)
