### ISSUE TITLE
Non googlers should be able to get access to the unit/integration logs

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#17443]
It's very difficult to debug problems for non-googlers now that both shippable and travis are disabled - it wastes developer time (they have to test everything themselves, when the machine has run and tested the box, then they have to nag googlers).

Having access to the unit/integration logs is a must if they are going to gate merges.

**Comment by smarterclayton** [comment]
Assigning Jeff randomly

**Comment by ixdy** [comment]
They are accessible, but it's not super obvious how to find them right now.

Basically, navigating to https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/${git-sha}/kubernetes-pull-build-test-e2e-gce/kubernetes-pull-test-unit-integration/ will show you all test results (stdout, test XML reports, verbose test output). You can sorta navigate here by taking the "Test artifacts" link from a e2e test comment and remove everything after the git sha.

This definitely needs to be easier, though.

**Comment by feihujiang** [comment]
Just encountered the same problem.

**Comment by deads2k** [comment]
I hit this too

**Comment by derekwaynecarr** [comment]
@eparis - you have experience in the tools, is it possible to add the link for the commit as described here: https://github.com/kubernetes/kubernetes/issues/17443#issuecomment-157837780 to each pr?

**Comment by eparis** [comment]
@decarr of course.   @ixdy why are you reporting the status details as:
```
http://goto.google.com/prkubekins/job/kubernetes-pull-test-unit-integration/3556/
```
Instead of
```
https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/d5b0b4f321aa1c9806f569a4b52719d8362abd7e/kubernetes-pull-test-unit-integration/
```

**Comment by ixdy** [comment]
OK, the commit status now links to the developer console (see e.g. https://github.com/kubernetes/kubernetes/pull/17999). For Googlers to get to Jenkins directly, we can replace everything up to and including the git hash with `go/prkubekins/job`.

**Comment by smarterclayton** [comment]
Awesome, thanns

**Comment by gmarek** [comment]
@smarterclayton is this fixed?

**Comment by feihujiang** [comment]
:+1: This is fixed for me.

**Comment by gmarek** [comment]
Thanks. Closing.
