### ISSUE TITLE
Kubectl download links for 1.1.1 still point to 1.0.1

### ISSUE THREAD

**Issue by binarybana** [kubernetes/kubernetes#17448]
On the download link to the `kubectl` binary at http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html it still points to the v1.0.1 kubectl binary.

I'm not sure if this is intentional but it meant that things like `kubectl get jobs` didn't work for me.

**Comment by nikhiljindal** [comment]
The link is https://storage.googleapis.com/kubernetes-release/release/v1.0.1/bin/darwin/amd64/kubectl
cc @caesarxuchao 
Another prefix we need to look for https://storage.googleapis.com/kubernetes-release/release/ in the munger.

**Comment by bgrant0607** [comment]
We should have a munger automatically keep these links up to date.

**Comment by dims** [comment]
Looks like the docs moved to https://github.com/kubernetes/kubernetes.github.io and the references are already fixed as well. We should close this issue.

https://github.com/kubernetes/kubernetes.github.io/search?utf8=%E2%9C%93&q=darwin%2Famd64%2Fkubectl
