### ISSUE TITLE
Break up types.go

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#1744]
Forked from #635.

types.go is currently monolithic. It's getting bigger and bigger. Also, we want an easy way to plug in new APIs.

OpenShift organizes its API per resource type. For example:
https://github.com/openshift/origin/blob/master/pkg/deploy/api/v1beta1/types.go
https://github.com/openshift/origin/blob/master/pkg/template/api/v1beta1/types.go

This way the API and registry code for an entity can be located together:
https://github.com/openshift/origin/tree/master/pkg/deploy

/cc @smarterclayton @lavalamp @thockin

**Comment by lavalamp** [comment]
This is slightly improved now that we have groups. More work is needed.

**Comment by bgrant0607** [comment]
API groups are the solution, and moving versioned types out of tree to share with clients has taken precedence over colocating types and registry code, so closing this as obsolete.
