### ISSUE TITLE
Scheduler will assign to nodes out of resources pods that don't request specific compute resources

### ISSUE THREAD

**Issue by eliaslevy** [kubernetes/kubernetes#17453]
The PodFitsResources default predicate [will not filter out](https://github.com/kubernetes/kubernetes/blob/0798915490fa60137f8239fd62003516537f3917/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L178-L179) a node that has all of its resources already allocated to pods with requested resources when determining where to schedule a pod that makes no resource requests.  This can result is a node being over subscribed.

A pod, even one that makes no resource requests, should not be scheduled to a node that if fully subscribed by other pods with requested resources.

**Comment by davidopp** [comment]
Hi @eliaslevy . Your observation is correct, but I don't think we should automatically prohibit scheduling new pods with zero request onto a node that is "full." It reduces the flexibility of the system and makes the resource feasibility rules a bit harder to reason about. But a cluster administrator who desires a policy like the one you are describing can use the LimitRange feature
https://github.com/kubernetes/kubernetes/tree/master/docs/admin/limitrange
to force every Pod to request non-zero resources. This would have the same effect as what you described.

Also, note that nodes publish in their NodeStatus.Capacity a "pods" resource (defaults to 40) which limits the max number of pods per node -- the scheduler will never schedule more than this number of Pods to a node. This is done to protect the Kubelet from overload, not to prevent the node resources from being oversubscribed.

I'm going to close this issue, but feel free to re-open if you have additional questions or concerns.
