### ISSUE TITLE
Support running node e2e tests locally on linux

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#17458]
Node e2e tests are written to run on jenkins against gce hosts.  We must support running the node e2e tests against a local cluster compiled from local source.

**Comment by dchen1107** [comment]
@pwittrock Can you provide the latest status on this one and the remaining work items? Thanks!

**Comment by pwittrock** [comment]
We met our 1.2 goals for this - running the e2e tests locally is pretty simple.  We won't be able to support running tests on mac outside of a vm until cadvisor is fully functional on Mac (non-goal).
