### ISSUE TITLE
Deploying applications to Kube should take into account security and the permissions necessary to accomplish their goals

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#17456]
We are starting to discuss formalizing / defining how an application is deployed onto Kube (via config files, examples, deployment-manager, Helm, and OpenShift templates).  Many of those applications are going to be isolated with no external dependencies.  That's the easy problem.

The next problem is how those applications (or Kube extensions running as extensions) are:
1. Authorized to talk to the Kube API or extension API to:
   1. ... read resources in their namespace (cassandra example reading service endpoints)
   2. ... change resources in their namespace (pod that updates status of resources, like a local controller)
   3. ... read resources across all namespaces (heapster and logging integrations need to read pods)
   4. ... change some resources across all namespaces (controllers running in pods)
2. Authorized to talk to other namespaces
   1. ... via the network
   2. ... via a proxy endpoint
3. Are given secrets that allow them to securely connect to other services in Kube, in other clusters, or outside of clusters
   1. We can inject secrets, but we don't make it easy to tie secrets and config to services and access them via apps in a way that is not "copy your secrets to every other place"
4. Are given secrets that allow them to securely serve for other services to connect to
   1. ... it is hard to run an app that protects itself via SSL on the cluster (requires certs that are generated, but the certs need to be signed by the proper authority, but the cluster controls internal DNS, but the external DNS is not visible to the cluster today for ingress or load balancers)
5. Are properly authorized to do dangerous things on the cluster, including but not limited to:
   1. ... accessing hostPath (root access on node)
   2. ... accessing pid / net / ipc / privileged flags (root access on node in some cases)
   3. ... defining arbitrary volumes in their pod spec which can mount any AWS / GCE / Azure host in the cluster (because the node has permissions to attach disks to itself, and the kubelet accepts the pod, the kubelet is a confused deputy)
   4. ... running images that other containers have access to (by specifying PullIfNotPresent and guessing the other images name) or that come from arbitrary sources (unscreened code)

Currently, Kube has limited protection / solutions for any of the above.  A few are being added today as a result of work done in OpenShift or in the community:
- PodSecurity policy protects clusters from random pods getting root on boxes #7893
- Authn/z in the cluster would define a way for applications to request 1 #17440
- Network isolation is being discussed in #15465
- Service accounts are in the code, which allow roles to be assigned to pods to enable 1, but you can't assign roles
  - Service accounts can control what secrets are visible to containers via an optional admission controller
- Discussion of generating secrets for apps automatically

To properly deploy applications to Kube, we will need to separate the "what" of the thing being installed cluster with the "what is it allowed to do".  Running random code from an upstream repo on your infrastructure that also has access to your internal network generally leads to bad results.  Extension components to Kube also need this clarity - it is insufficient for them to expect to run as root on the cluster.

We should formalize:
- How applications request and are granted the permissions they need to operate on the cluster
- How applications request and are granted the access to other applications on the cluster
- How extension applications (logging, metrics, extension API groups) differ from regular applications
- How our clients know which actions are escalation actions (make kubectl confused deputy) and which are not
- How simple applications can be given complex permissions without requiring the details of each cluster to be defined

We should make all of the above items easy to layer _on top_ of application definitions.

@bgrant0607 @erictune this is my tracking issue for "it's not enough to just deploy apps, they have to not take root on your cluster when they do it".

**Comment by pmorie** [comment]
Also: host namespace access

**Comment by smarterclayton** [comment]
5.ii

**Comment by pmorie** [comment]
Retracted :8ball:

**Comment by smarterclayton** [comment]
As a concrete example, the OpenShift logging aggregator (https://github.com/openshift/origin-aggregated-logging/tree/master/deployment) is a productized version of the Kube elastic search cluster, but a) secured and b) able to be used from a UI securely.  The implications of that highlight all of the current gaps I mention above - the pieces that defend the cluster and ensure the cluster are whole dramatically increase the complexity of a deployment.  Our simple tools make it possible - but our security posture makes it hard.  Most of the items above were identified during the retrospective of the deployment process, which is roughly summarized as:

1. Use a template to parameterize the inputs an admin cares about - pass those to a pod that can generate and create certificates and templatize input
2. The pod generates certs for serving, creates templates that can deploy the individual components (also allows some reuse of the elastic search config to run a cluster for the node infra and a cluster for the apps on the infra)
3. The admin must grant the authority for the logging cluster to read the Kube API to see pods across all namespaces and then deploy the templates - resulting in concrete resources being created.

We would summarize this as - you parameterize and deploy a complex application as one step - and after that, you must properly ensure the app is authorized to do what it needs to do.  Secret and cert generation are hard but necessary.  Authorization must not be vulnerable to confused deputy.  Both pieces are critical for real apps.

**Comment by derekwaynecarr** [comment]
@smarterclayton - i think we need to draw some more distinctions on what it means to deploy an application.

If I look at what I do on my host:

```shell
$ yum install foo
$ vi /etc/sysconfig/foo
.. tweak parameters, etc. ...
$ sudo systemctl enable foo
$ sudo systemctl start foo
```

If we look at a similar flow in Kubernetes, I think we need to think about things in similar stages.

1. how do I get starting point for 'foo' (is that the template)
2. does installing foo mean add a deployment and a config resource that users go edit separately, do we expect users to lock things down themselves, etc.
3. ultimately do i call another command to start foo?

**Comment by smarterclayton** [comment]
Yeah, to be clear: yum install foo is three parts - laying down files, setting up default config, and configuring the system to allow the thing to run (as root).  This covers how the last bit works (since you have to sudo to run it).

**Comment by bparees** [comment]
unfortunately `yum install foo` basically encompasses "do anything you want, as root".

the equivalent would be "provide a shell script that, among other things, runs random kubectl commands with admin authority".  And certainly we can do that (whether explicitly as a shell script, or as a deployer image that contains that shell script, or some other mechanism), but it doesn't fundamentally make it any easier as an application packager, which is the real problem here imho.

The challenge in my mind is how to make it easier, as an application packager, to create a set of constructs that can be installed by an end user.  Templates (in openshift) were definitely our starting point for that, but as we saw today, there is a whole host of other actions that may need to be performed which templates don't cover today.

Wrapping the whole thing into a first class "install" flow which gets provided things like generated certs, endpoint/cluster-config information, etc, seems like a good starting point.  It still puts a lot of the onus on the install-author to do intelligent things with those pieces, however.

**Comment by bprashanth** [comment]
@erictune

**Comment by bprashanth** [comment]
>  it is hard to run an app that protects itself via SSL on the cluster (requires certs that are generated, but the certs need to be signed by the proper authority, but the cluster controls internal DNS, but the external DNS is not visible to the cluster today for ingress or load balancers)

Just so I understand, we want 2 certs for 2 hostnames and SNI right, internal hostname cert signed by cluster CA (vaporware), and real cert signed by whomever?

**Comment by pmorie** [comment]
@smarterclayton 5.v -- use `NodePort` ?

**Comment by pmorie** [comment]
@smarterclayton 5.vi -- run privileged containers

**Comment by pmorie** [comment]
@smarterclayton 5.vii -- use kernel capabilities

**Comment by smarterclayton** [comment]
> Just so I understand, we want 2 certs for 2 hostnames and SNI right, internal hostname cert signed by cluster CA (vaporware), and real cert signed by whomever?

Yes - bootstrap cluster starts with vaporware CA, then eventually someone sets up a delegate ca for the domain that inherits from their corp cert.  They start with a wildcard DNS (real name, usually) and may get that signed right away for ingress.  Eventually they'll have multiple ingress points.  It's useful to secure the internal communications of the cluster infra with the internal CA, but that doesn't help external.  Also, the process for signing internal components makes bootstrapping unnecessarily complicated.

**Comment by erictune** [comment]
Let's step back even earlier in the process.  How do I decide which packages and which package sources I want to use and which I trust? 

With apt-get:

1. you trust a repository by adding it to `/etc/apt/sources.list`.   Trusting the repository means you trust if you ask for a specific package name, it will send you a true copy of that package.  It doesn't mean that you like every package in that repo.
1. you may need a credential to access a private repository. you specify how to authenticate to a repository by adding adding a line like "deb ssh …" or "deb ftp..." to  `/etc/apt/sources.list`.  You also distribute a password to the client or client's public key to the server.
1. You implicitly trust a package and future versions of it by apt-get installing it.   This is the point where you decide if the individual package is secure enough for your taste, if it was written by people you trust, etc.
1. You typically run `apt-get update` periodically without reevaluating your trust in the repository or your selected pacakges.


We need analogous steps for a kubernetes cluster or namespace of a cluster.
However, unlike apt-get, where the package includes both install instructions and the actual binaries, we have a layer of indirection.  A Helm-type package is going to have "installation instructions" in the form of object templates to be filled and created, and the Pod(Template) objects have a pointer to a docker repo.

So, we need to decide:

1. how do I trust a Helm-type repo
  1. if I trust the Helm-type repo, then do I implicitly trust any Docker repos that it references in the Pods of its packages?  
  1. how do I add trust of that repo to my cluster (kubelets may need to `rkt trust` the repo, and the apiserver may have rules about what image prefixes are allowed that need to be updated)
1. how do I authorize to a Helm-type repo, 
  1. might Helm-type packages include Secret objects with sensitive corporate secrets, or is that injected in the template state?
  1. maybe the package itself is a trade secret, for internal users, or requires payment.
1. where are Helm-type-Repo credentials stored? 
  1. on cluster admin's laptop, if that is where the package install process is driven from?
  1. on the cluster itself, if that is where an automatic update process is run as a cluster cron job?
1. how do I specify and persist the choice that I want an individual Helm-style-package to be installed (e.g. redis).  
1. how does update work?  The choice of trusted repos and selected packages has to be persisted in order for update to be automated.

**Comment by erictune** [comment]
So far, I have been trying to keep Kubernetes agnostic about how authorization is done.  The idea there is that when Kubernetes is hosted on, say, Amazon, it can use Amazon's IAM, and on premises, it can use Openshift's Policy, and in some other situation it can use a third thing.

This issue makes it clear that being agnostic about authorization comes at a cost.   

If Kubernetes had a single standard API for authorization, then a single package could automate the process of creating a service account, and giving that service account the permissions it needs.

With multiple possible APIs for authorization, then either the user needs to do a manual initial step of creating the serviceAccount and authorizing it, or there need to be different packages tailored to different authentication systems, or the packages need to have conditional logic to support several standards.

RedHat folks:  do we effectively have the situation today with SELinux systems vs non-SELinux systems?  Do all packages typically work on either type of system, or are separate packages maintained for each flavor?

**Comment by ncdc** [comment]
> RedHat folks: do we effectively have the situation today with SELinux systems vs non-SELinux systems? Do all packages typically work on either type of system, or are separate packages maintained for each flavor?

Packages/code should work both with and without the presence of SELinux (we don't maintain separate packages).

**Comment by erictune** [comment]
@ncdc presumably, the same package won't work with SELinux or GrSecurity or AppArmour or none of the above?  I expect that RedHat doesn't support those alternatives, and that there is some distro provider that does provide packages for those?

**Comment by erictune** [comment]
Regarding namespace and Clayton's item 2.

Do we think the normal pattern will be to create a *new* namespace to install an application into, or to install an application into an *existing* namespace?

If we go with the *new* option, then:

- PRO: can use short names for objects and not worry about name collisions
- CON: on a service like openshift online, where a namespace corresponds to a customer account, it is going to be a pain to make a new namespace.  
- CON: if we start associating network partitions with namespaces, as is the direction today's OpenContrail demo is going, then each new package is going to have to poke holes in the network to each other package.  (Claytons item 2.i).  This means that after installing a package, the user has to enumerate the consumers of the package.  This seems like it will be a pain.
- CON: a user will have to specify namespace a lot when listing and dealing with kubernetes objects, if every package is in its own namespace. 

I think *existing* is probably the better pattern, and if you support *existing* then you also support *new*.

**Comment by ncdc** [comment]
@erictune of the ones you listed above, I'm only familiar with SELinux and our packages for Fedora/Centos/RHEL, so I can't speak to GrSecurity or AppArmour. For the SELinux case, if your executable is performing actions that the default policy denies, you will probably want to provide custom policy modules that are installed as part of the RPM installation.

**Comment by erictune** [comment]
Do we think that the common pattern will be for a single person/org to maintain both the YAML and the Images for a Kube-package?  

For example, will a Redis Kube-package use the Docker official Redis image (https://hub.docker.com/_/redis/), or would whoever maintains the YAML files also maintain the image (which might use `FROM redis`, but with changes to the image to integrate with kubernetes?

If it is going to be the *directly use official docker image* option, then we need to put more effort into making it easy to tweak stock images at runtime (e.g. things like what @pmorie did with Env vars).  If it is the latter, then it is going to be more effort to maintain a package, and explaining to users why they should trust the Kube-package is a bit harder.

**Comment by erictune** [comment]
@zmerlynn some of this might be relevant to what you are working on

**Comment by smarterclayton** [comment]
> Do we think the normal pattern will be to create a new namespace to install an application into, or to install an application into an existing namespace?

I don't think there's one or the other so - namespaces are an organizational concept, so different people will organize differently.  However, we can use your PROs and CONs to guide recommendations about how to organize.  Online actually doesn't assume namespace corresponds to account - we always want to enable multiple namespaces for users.

Using short names is good - having short names represent "the things you care about" is best.  The best packages fit neatly into a namespace in their intended function.  Generally, you don't need 2 cassandra clusters from the same app, or they may not be managed or accessed by the same applications.  That means the service name might be "cassandra" much of the time.  Occasionally, you'd have "cassandra-logs" and "cassandra-customer" - in those cases, someone has to take the package and parameterize it (hence why OpenShift templates are often flexible to allowing name to be parameterized).  

Worth remembering, cassandra / redis / mysql aren't really applications - they're tools that are used to build applications.  Applications are often composites of these pieces, sometimes under the same team, sometimes not.

**Comment by smarterclayton** [comment]
w.r.t. using stock images, there is a reasonable expectation today that you will need to *adapt* existing images for your needs, and having tools to do that in Kube is part of our goals for the pod API (downward API, secrets being mountable at user discretionary locations, config data, templates from config data, etc)

**Comment by smarterclayton** [comment]
Having some concrete way to annotate a set of objects that need permissions
on their service accounts, or other cluster policy, seems extremely
important for standardization of cluster security

On Nov 19, 2015, at 1:57 PM, Eric Tune <notifications@github.com> wrote:

So far, I have been trying to keep Kubernetes agnostic about how
authorization is done. The idea there is that when Kubernetes is hosted on,
say, Amazon, it can use Amazon's IAM, and on premises, it can use
Openshift's Policy, and in some other situation it can use a third thing.

This issue makes it clear that being agnostic about authorization comes at
a cost.

If Kubernetes had a single standard API for authorization, then a single
package could automate the process of creating a service account, and
giving that service account the permissions it needs.

With multiple possible APIs for authorization, then either the user needs
to do a manual initial step of creating the serviceAccount and authorizing
it, or there need to be different packages tailored to different
authentication systems, or the packages need to have conditional logic to
support several standards.

RedHat folks: do we effectively have the situation today with SELinux
systems vs non-SELinux systems? Do all packages typically work on either
type of system, or are separate packages maintained for each flavor?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17456#issuecomment-158155952>
.

**Comment by jackgr** [comment]
While this issue deals specifically with Kubernetes auth, it raises larger questions about provenance, package deployment, template expansion, bundling templates with images, etc. They start to lean in the direction of application lifecycle management.

There's an initiative afoot in Cloud Native Computing Foundation to define a simple, opinionated but general architecture for application lifecycle management, where steps like build from source, custom image baking, deployment and update can be orchestrated smoothly end to end by CI/CD tools.

The canonical use case is that an enterprise has a large number N of apps running that use image Y, built from base X, and a CERT bulletin has just been issued against a library used in X. The CIO wants to ask her team certify a new version of X, let's call it X2, and then sleep soundly while the change propagates into production automatically via dependency driven rebuilds, smoke tests, redeploys, roll outs, canaries, roll backs, etc. In some reasonable amount of time, Y is rebaked based on X2, yielding Y2, and all N apps are redeployed using Y2, with minimal human intervention beyond giving the thumbs up to X2.

**Comment by davidopp** [comment]
@zmerlynn

**Comment by jstrachan** [comment]
We want to be able to create cloud native applications on Kubernetes as a YAML file, Helm chart, OpenShift Template or whatever. However we never want to actually include the Secrets inside that YAML file ;) those should always be generated or imported from somewhere (Vault or whatever).

This feel very much like PersistentVolumeClaim versus PersistentVolume. The App developer wants to make a cloud native app and have it just work in any kubernetes cluster. Different clusters may live on different clouds using different kubernetes software & plugins which may use different kinds of PersistentVolume implementation. So the nice separation between the app defining its PersistentVolumeClaim and an admin then creates the PersistentVolumes to match the claims; or clusters can have dynamic PV implementations etc.

So I'd like to see something like a `SecretClaim` (my app wants a secret called jenkins-ssh which is ssh key/value pair and github-http-key which is a github token or whatever) so that users can then import them from some Vault like tool; or we can have automated tools to generate them automatically (kinda like the dynamic PV stuff).

There is a similar issue with Roles; we want our apps to clearly define the roles they require on their ServiceAccounts. However it probably requires some ops folks to review the permissions being requested and granting them on a case by cace basis. 

Then just like folks can run

```
kubectl get pvc
kubectl get pv
```

to see how the PVCs are bound and if new PVs need generating, we could have something similar for `SecretClaim` -> `Secret` and `RoleBindingClaim` -> `RoleBinding` or whatever. So its very clear if the dependencies of an app have been generated/installed/configured/approved.

This also helps make the apps more declarative; it avoids random failures deep inside an app if something doesn't have the right roles or the secret isn't mounted properly into a pod etc.

By having 2 new API resources; `SecretClaim` and `RoleBindingClaim` we'd be able to include these resources in any kind of app packaging; single YAML file, helm chart, openshift template or anything else etc

**Comment by jstrachan** [comment]
BTW in lieu of `SecretClaim` on the fabric8 project we've been using annotations to simulate the 'this app requires secrets of these kinds to be created` so that a tool can auto-generate them:
https://github.com/fabric8io/fabric8/blob/master/docs/secretAnnotations.md

its easy to generate, say, user name + passwords via things like OpenShift templates; its a little harder though to generate ssh public/private keys etc It feels like a simple API resource (that we could always add annotations to if the common 80% of requirements are not quite met)

**Comment by smarterclayton** [comment]
Regarding secret generation, generating server certs is a lot like this pattern (in OpenShift 1.3 it is an annotation on the service that creates a named secret with a serving cert signed for that service DNS name.  So I think annotations of various forms is the appropriate approach to get started.

Broader question?

Do you think that the majority of cases would include a secret an admin provisioned?  I'm wondering whether we can split the difference by defining an empty secret or a secret "hole" that is filled either by the aforementioned admin claim or via generation.

I.e., many templates require secrets, in many forms.

* root passwords to databases
* username/password for others to connect (mysql users, jenkins admin, etc)
* tokens or other dynamically created secrets (same vein as above)
* secrets that must only be unique, like salts and seeds for cryptographic hashes on things like sessions
* serving certs for a component - often in PEM format but sometimes in JKS or others
* client certs for connecting to a remote component (requires the participation of a remote signer - easier now with CSR resource)

From many sources:

* Local secrets that pre-exist
* Local secrets that do not exist yet but must exist for the app to work
* Secrets stored in a remote store like Vault (included for completeness, but that's really the app authors problem today)
* Generated on a rapid schedule and must be rotated

I suspect that many Helm style users (people trying out simple prepackaged apps) will expect to generate secrets.  Moving up the food chain in complexity, they may start integrating pre-existing secrets.  Once they want to reuse secrets, do we truly need a claim concept, or is the existing "failure to start" behavior sufficient (especially if we do a better job of propagating errors like that up to the top level controller)?  

I've tried to think of various ways that we could reuse the existing API objects as is and let their presence or absence be the signal to create / halt.  But ultimately we probably need to flag safe resources and have kubectl or the server require some sort of confirmation / acceptance to pass through, otherwise clients can't present relevant errors / warnings / choices to authors.  I think there's a lot of merit to having a resource like a RoleBindingClaim that is an idempotent grant that can be flagged / rejected / assessed - my worry would be that there could be many other resources like that (do we need a *Claim type for each one?).  

I think we should open an issue and try to get a working proposal for secret generation - that's one of the things missing in the template proposal that I think is critical to actual usability, and if we can broaden it out to multiple types of secrets and multiple participating agencies we can probably find a happy medium pretty fast (oc observe wants to help, I know it does..)

**Comment by smarterclayton** [comment]
Service secret generation documented here: https://docs.openshift.org/latest/dev_guide/secrets.html#service-serving-certificate-secrets

**Comment by bgrant0607** [comment]
ref #12732
