### ISSUE TITLE
Spark Example - Workers not reaching Master

### ISSUE THREAD

**Issue by wattsteve** [kubernetes/kubernetes#17463]
FYI @zmerlynn 

I've been following the new Spark Example https://github.com/kubernetes/kubernetes/tree/master/examples/spark updated with Zeppelin and the Step 2 Section where the Workers are meant to successfully register with the master appears to be broken. 

I can confirm that all the RCs, Pods, Services are submitted and running. Executing kubectl logs on the master looks fine and I get the same output as the example. However, when I execute the same command on the logs of the workers they are throwing the following exception:

15/09/09 17:06:04 INFO Utils: Successfully started service 'WorkerUI' on port 8081.
15/09/09 17:06:04 INFO WorkerWebUI: Started WorkerWebUI at http://192.168.58.22:8081
15/09/09 17:06:04 INFO Worker: Connecting to master spark-master:7077...
15/09/09 17:06:04 WARN ReliableDeliverySupervisor: Association with remote system [akka.tcp://sparkMaster@spark-master:7077] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://sparkMaster@spark-master:7077]] Caused by: [spark-master: unknown error]
15/09/09 17:06:04 WARN Worker: Failed to connect to master spark-master:7077
akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka.tcp://sparkMaster@spark-master:7077/), Path(/user/Master)]
	at akka.actor.ActorSelection$$anonfun$resolveOne$1.apply(ActorSelection.scala:65)
	at akka.actor.ActorSelection$$anonfun$resolveOne$1.apply(ActorSelection.scala:63)

In the original Spark Example, an overlay network was required in order for the Spark Worker containers to reach the Spark Master container. I realize this is enabled by default on GKE but not when using Kube on premise. The docs do not mention this as a requirement. However, I modified all the RCs to use hostNetwork: true, and it didn't seem to help.

**Comment by zmerlynn** [comment]
@wattsteve: Is DNS functional on your cluster?

**Comment by wattsteve** [comment]
I think so. Pings to FQDNs of other hosts can resolve with no issues?  

This is a ping from the Kube Master to a Kube Worker

[root@master kubernetes]# ping worker-1.fed
PING worker-1.fed (192.168.58.21) 56(84) bytes of data.
64 bytes from worker-1.fed (192.168.58.21): icmp_seq=1 ttl=64 time=0.403 ms
64 bytes from worker-1.fed (192.168.58.21): icmp_seq=2 ttl=64 time=0.554 ms

**Comment by zmerlynn** [comment]
No, I meant [https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns#how-do-i-test-if-it-is-working](SkyDNS).

**Comment by zmerlynn** [comment]
@wattsteve: BTW, since you have full debian image pod up already (the master), an easy way to check for DNS is just: `kubectl exec spark-master-controller-0c370 getent hosts kubernetes.default`. (replace `spark-master-controller` appropriately.

If DNS is working, try firing up the `zeppelin-controller` RC, because it probably won't crashloop on you, and see if `spark-master` resolves in there, e.g.

```
$ kubectl exec zeppelin-controller-d1fkg getent hosts spark-master
10.139.252.40   spark-master.default.svc.cluster.local
```

If that's not working, but DNS *is* make sure the service was created and the endpoints are active, check `kubectl describe svc/spark-master`. Check all of those, please? :)

**Comment by zmerlynn** [comment]
@wattsteve: Feel free to hop on https://kubernetes.slack.com/messages/sig-big-data/details/ if you want some realtime debugging, too.

**Comment by cpwais** [comment]
Running into this problem too; have hit it several times before ...  Is DNS broken in master ?

**Comment by cpwais** [comment]
I think I've had this problem every time I've tried the spark k8s example ...

```
# kubectl exec spark-worker-controller-td15t -it bash
root@spark-worker-controller-td15t:/# ping spark-master
PING spark-master.default.svc.cluster.local (192.168.3.90): 56 data bytes
^C--- spark-master.default.svc.cluster.local ping statistics ---
8 packets transmitted, 0 packets received, 100% packet loss
```

```
16/01/02 22:19:05 WARN Worker: Failed to connect to master spark-master:7077
akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka.tcp://sparkMaster@spark-master:7077/), Path(/user/Master)]
        at akka.actor.ActorSelection$$anonfun$resolveOne$1.apply(ActorSelection.scala:65)
        at akka.actor.ActorSelection$$anonfun$resolveOne$1.apply(ActorSelection.scala:63)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
```

**Comment by wattsteve** [comment]
Every time I've run this in my on-premise cluster, I've used Flannel, so
there has been an overlay network that helps ensure the workers can reach
the master. I think the Googlers that run it test it in Google Cloud which
I believe also has some sort of an overlay network where different
containers on different hosts can reach each other. I don't think an
overlay network is explicitly required for this example, I'm just relaying
the scenarios I know that it has been tested in.

**Comment by cpwais** [comment]
Thanks Steve!

Woof, looks like my DNS is broken:

```
# kubectl create -f /tmp/busybox.yaml
pod "busybox" created


# kubectl exec busybox -- nslookup kubernetes.default
Server:    192.168.3.10
Address 1: 192.168.3.10

nslookup: can't resolve 'kubernetes.default'
error: error executing remote command: Error executing command in
container: Error executing in Docker Container: 1
```

I'm using ubuntu and have found other things are broken too ...

Curious, any chance you could give me any quick pointers to what you did to
get a working setup?

**Comment by jayunit100** [comment]
So, is SkyDNS A Hard requirement of our spark impl?  I didn't know that it was, maybe this is changed, as it used to work ootb i thought using the spark akka env variable thingy....

**Comment by jayunit100** [comment]
Thanks again to @wattsteve for starting this thread, it needed to be updated in the docs.  Also E2E fix is pending in a PR i just put up.

**Comment by bgrant0607** [comment]
Is this resolved @jayunit100 ?

**Comment by jayunit100** [comment]
Yup, resolve this please, thanks guys.  The updated spark stuff works via dns.  The e2e tests can be run to verify.

**Comment by zmerlynn** [comment]
Thanks, @jayunit100!

**Comment by JRohitDQ** [comment]
> I think I've had this problem every time I've tried the spark k8s example ...
> 
> ```
> # kubectl exec spark-worker-controller-td15t -it bash
> root@spark-worker-controller-td15t:/# ping spark-master
> PING spark-master.default.svc.cluster.local (192.168.3.90): 56 data bytes
> ^C--- spark-master.default.svc.cluster.local ping statistics ---
> 8 packets transmitted, 0 packets received, 100% packet loss
> ```
> 
> ```
> 16/01/02 22:19:05 WARN Worker: Failed to connect to master spark-master:7077
> akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka.tcp://sparkMaster@spark-master:7077/), Path(/user/Master)]
>         at akka.actor.ActorSelection$$anonfun$resolveOne$1.apply(ActorSelection.scala:65)
>         at akka.actor.ActorSelection$$anonfun$resolveOne$1.apply(ActorSelection.scala:63)
>         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
> ```

Hey, even I'm facing the exact same error, tried installing it via default spark image, the spark worker pod is not able to connect to spark-master pod and gives error, but when I edit the statefulset of the worker pod and replace the spark-master-url with the clusterIP of the spark master svc instead of the name , it starts to work fine. can someone help me resolve this issue?
