### ISSUE TITLE
An error should pop out if creating an autoscaler without heapster running

### ISSUE THREAD

**Issue by jay-lau** [kubernetes/kubernetes#17467]
The current behavior is that if I create an autoscaler withput heapster, then the autoscaler does not work and the CURRENT value keeps waiting, it is difficult for end user for troubleshooting.

An ideal behavior should be the autoscaler need to report error if no heapster is running.

**Comment by piosz** [comment]
If there is no metrics available in HPA the appropriate event is exported, so closing this.
