### ISSUE TITLE
Inflexible assumptions for componentstatuses handler

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#17461]
From https://github.com/openshift/origin/issues/3667#issuecomment-122333811:

"the implementation from upstream assumes separate components for the controller manager, assumes everything is available via 127.0.0.1 from the master, and assumes no auth. All of those assumptions are invalid" for installations such as OpenShift.

These assumptions should be more flexible/configurable. This endpoint seems really useful for a single request to get a high level view of cluster health.

**Comment by deads2k** [comment]
@kubernetes/rh-cluster-infra ptal.  

/cc @simon3z

**Comment by derekwaynecarr** [comment]
I think the topics noted in this issue are intended to be covered by this proposal:

https://github.com/kubernetes/kubernetes/pull/13216

**Comment by lavalamp** [comment]
Yes, I think this is covered completely by that.
