### ISSUE TITLE
CrashLoopBackOff and confusing status

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes#17460]
Pods are crashing as reported by:

```
$ kubectl get po   
NAME                  READY     STATUS             RESTARTS   AGE
elasticsearch-attiy   0/1       CrashLoopBackOff   25         1h
elasticsearch-lkl4i   0/1       CrashLoopBackOff   25         1h
frontend-81lqv        1/1       Running            0          1h
frontend-ddanc        1/1       Running            0          1h
```

But the message isn't clear when trying to exec:

```
$ kubectl exec -it elasticsearch-attiy sh 
error: Error executing remote command: Error executing command in container: container not found ("elasticsearch")
```

And the describe gives an even more confusion "2/2 replicas created" and it did find the image:

```
$ kubectl describe po elastic
search-attiy
Name:                           elasticsearch-attiy
Namespace:                      default
Image(s):                       eu.gcr.io/foo/foo_elasticsearch:latest
Node:                           gke-small-cluster-7834f89-node-wke5/10.210.0.1
Labels:                         name=elasticsearch
Status:                         Running
Reason:
Message:
IP:                             10.180.1.11
Replication Controllers:        elasticsearch (2/2 replicas created)
Containers:
  elasticsearch:
    Image:              eu.gcr.io/foo/foo_elasticsearch:latest
    State:              Waiting
      Reason:           CrashLoopBackOff
    Ready:              False
    Restart Count:      26
Conditions:
  Type          Status
  Ready         False 
Events:
  FirstSeen                             LastSeen                        Count   From                                 S
...
  Wed, 18 Nov 2015 21:24:42 +0100       Wed, 18 Nov 2015 23:09:03 +0100 26      {kubelet gke-small-cluster-7834f89-node-wke5}        spec.containers{elasticsearch}  Pulled  Successfully pulled image "eu.gcr.io/foo/foo_elasticsearch:latest"
  Wed, 18 Nov 2015 23:09:03 +0100       Wed, 18 Nov 2015 23:09:03 +0100 1       {kubelet gke-small-cluster-7834f89-node-wke5}        spec.containers{elasticsearch}  Created Created with docker id a7429f37f133
  Wed, 18 Nov 2015 23:09:04 +0100       Wed, 18 Nov 2015 23:09:04 +0100 1       {kubelet gke-small-cluster-7834f89-node-wke5}        spec.containers{elasticsearch}  Started Started with docker id a7429f37f133
```

It would help to have clearer messages to help understand causes of crashes.

The `exec` command could say that the given container isn't running properly on the Pod (with a status or a command that could describe more in details the reasons).

The `describe` command here could clarify that replicas have been created but aren't healthy. More importantly I found missing the reason of why the container got restarted. I do suspect that my `command` statement is the cause.

**Comment by wernight** [comment]
The actually useful command to execute would have been:

    $ kubectl logs elasticsearch-attiy -p

**Comment by pires** [comment]
Where are you getting this from? I mean, there's nothing on `master` regarding gcr.io images of Elasticsearch containers.

**Comment by wernight** [comment]
The Docker Registry is Google Cloud. The issue was that my Pod had `command: ["elasticsearch", "--some-arg"]` instead of `args: ["elasticsearch", "--some-arg"]`.

By looking at `kubectl logs elasticsearch-attiy -p` I saw the correct error.

However `kubectl describe` outputs were not useful IMO.

**Comment by pires** [comment]
Nevermind, I was referring to the `examples/elasticsearch` instructions, which surely you are not following. Sorry for the confusion.

**Comment by bgrant0607** [comment]
At minimum, we could use some documentation about what this means.

**Comment by bgrant0607** [comment]
See also #18206

**Comment by linbrown** [comment]
I cannot figure out how to fix the problem from the description above. I am trying to create a pod in a three nodes cluster on google cloud, and got the pod log:

Pod "hello-node-lihpv" in namespace "default": container "hello-node" is in waiting state.

The pod state is:

 Name: hello-node-lihpv
Status 	Running on
Created 	Mar 4, 2016 9:08:54 PM
Host Networking 	/10.128.0.2
Pod Networking 	10.48.1.7 : 8080
Labels 	
run: hello-node
Namespace 	default
Containers 	
Name 	Image 	Ready 	Restarts 	State
hello-node 	gcr.io/nodewebserver/hello-node:v2 	false 	7 	
Waiting
Reason: CrashLoopBackOff

And the output of "@nodewebserver:~/project$ kubectl describe pods hello-node-lihpv":

Name:                           hello-node-lihpv
Namespace:                      default
Image(s):                       gcr.io/nodewebserver/hello-node:v2
Node:                           gke-hello-world-72ee8f2f-node-zsrg/10.128.0.2
Start Time:                     Fri, 04 Mar 2016 21:08:54 -0800
Labels:                         run=hello-node
Status:                         Running
Reason:
Message:
IP:                             10.48.1.7
Replication Controllers:        hello-node (1/1 replicas created)
Containers:
  hello-node:
    Container ID:       docker://7b0917887956a3b322c82b83ec344cf9d3dfe6d45322bafc175aa92d054527f2
    Image:              gcr.io/nodewebserver/hello-node:v2
    Image ID:           docker://d9fae1189f5ca74f298770d99b0bbadee1c60990014acc24e5a1a12e01ce5390
    QoS Tier:
      cpu:      Burstable
    Requests:
      cpu:                      100m
    State:                      Waiting
      Reason:                   CrashLoopBackOff
    Last Termination State:     Terminated
      Reason:                   Error
      Exit Code:                1
      Started:                  Fri, 04 Mar 2016 21:12:11 -0800
      Finished:                 Fri, 04 Mar 2016 21:12:11 -0800
    Ready:                      False
    Restart Count:              6
    Environment Variables:
Conditions:
  Type          Status
  Ready         False 
Volumes:
  default-token-0v4j6:
    Type:       Secret (a secret that should populate this volume)
    SecretName: default-token-0v4j6
Events:
  FirstSeen     LastSeen        Count   From                                            SubobjectPath                           Reason          Message
  ─────────     ────────        ─────   ────                                            ─────────────                           ──────          ───────
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    implicitly required container POD       Pulled          Container image "gcr.io/google_containe
rs/pause:0.8.0" already present on machine
  3m            3m              1       {scheduler }                                                                            Scheduled       Successfully assigned hello-node-lihpv 
to gke-hello-world-72ee8f2f-node-zsrg
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    implicitly required container POD       Created         Created with docker id 52106848e275
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Pulling         Pulling image "gcr.io/nodewebserver/hel
lo-node:v2"
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    implicitly required container POD       Started         Started with docker id 52106848e275
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Pulled          Successfully pulled image "gcr.io/nodew
ebserver/hello-node:v2"
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Created         Created with docker id 29cfe561249f
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Started         Started with docker id 29cfe561249f
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Started         Started with docker id 9cc172f2ffef
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Created         Created with docker id 9cc172f2ffef
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Created         Created with docker id 51f647ce6d99
  3m            3m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Started         Started with docker id 51f647ce6d99
  2m            2m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Created         Created with docker id 9a792e76e697
  2m            2m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Started         Started with docker id 9a792e76e697
  1m            1m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Created         Created with docker id 8013b51d47f5
  1m            1m              1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Started         Started with docker id 8013b51d47f5
  3m            18s             5       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Pulled          Container image "gcr.io/nodewebserver/h
ello-node:v2" already present on machine
  18s           18s             1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Created         Created with docker id 7b0917887956
  17s           17s             1       {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Started         Started with docker id 7b0917887956
  3m            8s              16      {kubelet gke-hello-world-72ee8f2f-node-zsrg}    spec.containers{hello-node}             Backoff         Back-off restarting failed docker conta
iner

Thanks!

**Comment by mellotron** [comment]
I'm affected by this on arm64 for kube-dns following this guide:

- https://kubernetes.io/docs/getting-started-guides/docker-multinode/

I think the image it's using is: gcr.io/google_containers/kubedns-arm64:1.9

**Comment by mellotron** [comment]
The above may be related to https://github.com/kubernetes/minikube/issues/947

**Comment by kargakis** [comment]
Seems like a documentation effort
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by seenickcode** [comment]
Hey update on this?

**Comment by bgrant0607** [comment]
Closing in favor of https://github.com/kubernetes/website/issues/7092

**Comment by scottman1987** [comment]
I was having this problem, until I changed the FROM line in my Dockerfile from:

FROM microsoft/aspnetcore:2.0.0
... to ...
FROM microsoft/aspnetcore:2.0.5

(I'm running in a linux docker image. Not sure what it would be if windows)
