### ISSUE TITLE
LEMP example

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes#17489]
TL;DR Suggesting a LAMP example to help traditional users (those still running apt-get install on a single Linux server or knowing even less) migrate to Kubernetes.

After some experiments I got a broader idea of how things work. The current documentation isn't too bad but it's lacking of some common end to end case. For example to bring a standard LEMP (Linux + Nginx + PHP/Python/... + MySQL/Redis/...) to Kubernetes users need to read:
1. Use a Nginx image, use a MySQL image linked to a MySQL storage, and probably build a Docker image (by writing a Dockerfile) based on PHP.
2. Create a Container Registry and push the built image(s)
3. Deploy those images
4. Scale

I'd suggest a LAMP/LEMP tutorial example covering/answering points above in the follow way:
1. The docker-specific knowledge should be briefly covered with some pointers. The existing tutorials assume everything can be done using (existing) pre-built (public) images. This is often not the case and removes all the power of Docker and what comes with it.
2. Set up a Container Registry and push the built image(s)
3. This step has some elements but it's missing an example of Nginx + PHP/Python/... most examples I found are Apache with PHP in a single container which isn't the Docker way. I could help but I'd need some advice on choosing between:
   - Nginx + PHP-FPM (or similar) on the same Pod (i.e. multiple container Pod)
   - Nginx linking to PHP each on different Pods (so possibly one machine connecting to another)
4. Scaling of most LEMP solutions have the same common points, like having **sessions** stored in a distributed database. PHP/Django/... all allow that and require that to allow scaling. I'd just chose one of them for that example to have a practical example.

It could point of course to the existing [Nginx](https://github.com/kubernetes/kubernetes/tree/master/examples/redis) example.

**Comment by wernight** [comment]
Looking more into this, Redis Cluster is a good fit for sessions.

There isn't yet a tutorial on **Redis Clusters**, so there is that. Redis cluster clients need a list of one or more Redis instance (by IP:PORT). One way could be to have a Service pointing to Pods running Redis (i.e. instead of a list of redis IPs, simply provide the host name of the redis server). This however may be suboptimal especially if the elected pod happens to be down, then I guess the Redis client wouldn't be able to fail over another Pod for that request. The alternative I see is either to have static IPs (very manual and rigid deployment), or have as many Redis Services as there are Redis Pods (also pretty manual and rigid). I don't see a simple way to tell client(s) about the current list of Redis instances.

**Comment by wernight** [comment]
Can someone please comment on good solutions? I mean LEMP is extremely common, I wouldn't put most web services directly without a Nginx/Apache proxy (many would be vulnerable or break like Flask/Bottle).

**Comment by wernight** [comment]
As some pointers after some testing:

 - pro single Pod with Nginx and PHP-FPM or uWSGI containers: Can mount a local writable disk and share it with both which is very useful if you've a single instance and want Nginx to serve for example user uploaded files. Lower latency?
 - pro multiple Pods, one for Nginx, one for PHP-FPM or uWSGI container: Can scale Nginx and backend independently, and `kubectl rolling-update --image` makes it easy to update images (that command doesn't support multiple containers per Pod.

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by bgrant0607** [comment]
I suggest posting to stackoverflow. Maybe someone in the community has a solution.

**Comment by dynek** [comment]
This is one very interesting topic. Still thinking on my side about such implementation. What comes to my mind if nginx and php-fpm are separate: managing uploaded files, serving both static and dynamic content means that nginx pod should be able to see all websites while php-fpm would only see one to be able to scale if one requires more ressources. And then what about cron jobs... In my case I have to deal with websites running cron jobs.

**Comment by chepurko** [comment]
Hi all, I am working on a Kubernetes LEMP Stack and have a working release over here https://github.com/chepurko/k8s-lemp. I would be very grateful for more pairs of eyes and brains. Currently I __do not__ have working TLS with kube-lego and am working on fixing that, but going through the README at least gets you fine Wordpress HTTP websites.

**Comment by wernight** [comment]
I've been using Kubernetes for a while now. I'd say that in most cases it's better to have one Pod of Nginx, one of MySQL, one of PHP-FPM... This allows scaling components individually, and allows upgrading only some of them.

The only downside is that you may have Nginx on one Pod talking to PHP-FPM on another even though there might be one on the current Pod, so you need a good network within your cluster.

**Comment by chepurko** [comment]
@wernight Thanks, I have two containers of NGINX and PHP-FPM in one pod which replicates for each extra site you want and one MariaDB running as a separate StatefulSet.

I guess you could separate out the RDBMS for each website but I think having one just reduces size and complexity. You can always scale our the RDBMS with Percona and Ceph, which is what I'm planning on. Redis is there as a scaleable Deployment to take load off of MariaDB.

Would be happy to continue the convo in the [k8s-lemp](https://github.com/chepurko/k8s-lemp/issues) repo...

**Comment by kargakis** [comment]
Please reopen this issue in the examples repo: https://github.com/kubernetes/examples
