### ISSUE TITLE
Finer grained service resource quota control

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#17484]
ResourceQuota currently has the option to enforce the maximum number of services, but unable to set the quota based on service type.  I think it would make more sense if we can limit, say max 2 services with LB, 5 services in total.

We can either add more info to service (i.e. type), or we can just add a new type Loadbalancer.

**Comment by bgrant0607** [comment]
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
This use case would be solved via: 
https://github.com/kubernetes/kubernetes/pull/19761

That proposal adds a `FieldSelector` that can scope a quota.  In this case, you would write a quota document that targets services with a specific `spec.type`.  I will add this as a use case to that proposal.

**Comment by ddysher** [comment]
@derekwaynecarr what's the status for quota scoping?  can we close this?

**Comment by derekwaynecarr** [comment]
this is already implemented.

the following are supported in quota:

services
services.nodeports
services.loadbalancers
