### ISSUE TITLE
hack/local-up-cluster.sh is missing in release

### ISSUE THREAD

**Issue by d4goxn** [kubernetes/kubernetes#17505]
The "getting started locally" instructions at http://kubernetes.io/v1.1/docs/getting-started-guides/locally.html go straight from "requirements" to "starting the cluster" with no mention of how to get Kubernetes itself. I downloaded and extracted the latest release, v1.1.2, but it is missing a file that is mentioned in the manual: hack/local-up-cluster.sh.

Not sure if that file was deliberately omitted from the releases. If so, then can we add a section to the docs explaining where to get Kubernetes and how to install it? I would be happy to test the instructions. In the meantime, I am going to try to build Kubernetes from source, since that missing file is on the master branch.

Related to #17504.

**Comment by reallax** [comment]
Does this problem fixed up? I use version of v1.2.4,it's still miss the file hack/local-up-cluster.sh.
It's confusing for newcomer, and how can I fix it?

**Comment by kargakis** [comment]
@kubernetes/sig-contributor-experience-misc

**Comment by dims** [comment]
https://kubernetes.io/docs/getting-started-guides/ redirects to https://kubernetes.io/docs/setup/pick-right-solution/ and there are no references local-up-cluster.sh, so we can close this out
