### ISSUE TITLE
boot2docker -> dockermachine

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#17508]
- Looks like there is alot of boot2docker references in the codebase.
- Lets update them to **docker machine** where necessary/appropriate.
  
  probably this is applicable in almost all the docs... But also in other places ... in particular... 

```
./hack/lib/golang.sh
./cluster/mesos/docker/config-default.sh
./cluster/mesos/docker/util.sh
./build/common.sh
./build/copy-output.sh
./build/README.md
./docs/getting-started-guides/mesos-docker.md
./docs/getting-started-guides/docker-multinode/testing.md
./docs/getting-started-guides/docker.md
./docs/design/clustering/Makefile
./docs/design/clustering/README.md
```

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
There are no boot2docker references in docs repository (kubernetes.github.io) anymore. /close
