### ISSUE TITLE
logs api returns bad error if container is deleted

### ISSUE THREAD

**Issue by bparees** [kubernetes/kubernetes#17501]
if the container has been deleted (but the pod still exists, as can occur with garbage collection), the logs api returns a 404 error directly from docker:
`API error (404): no such id: 7ef69dfb99d623cad1f0351b16b2bfa6c77f36336c4fec3063083e2750ba1155`

the logging api should return a cleaner error.

@kargakis

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra

**Comment by ashcrow** [comment]
@bparees Would a ```410 Gone``` with a payload stating the pod exists but the container does not make better sense?

**Comment by bparees** [comment]
@ashcrow i'm not too opinionated on the http status code, but your payload definitely sounds better.
