### ISSUE TITLE
s3_url_base in cluster/aws/utils.sh

### ISSUE THREAD

**Issue by zzq889** [kubernetes/kubernetes#17507]
`s3_url_base`should be like this
```
https://s3-${s3_bucket_location}.amazonaws.com.cn
```
if region is China ( `cn-north-1`)
reference: http://docs.amazonaws.cn/en_us/general/latest/gr/rande.html

**Comment by mikedanese** [comment]
cc @justinsb

**Comment by mikedanese** [comment]
We accept PRs!

**Comment by jtblin** [comment]
http://docs.amazonaws.cn/en_us/general/latest/gr/rande.html shows that the url is `s3.cn-north-1.amazonaws.com.cn` for `cn-north-1` which is the case today so this issue does not seem valid.

**Comment by justinsb** [comment]
Yes - this should have been fixed in #17814.  Closing, but reopen if this isn't now fixed.
