### ISSUE TITLE
"Getting started in Vagrant" document missing critical steps.

### ISSUE THREAD

**Issue by AlexChesser** [kubernetes/kubernetes#17504]
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/vagrant.md

The instructions in the vagrant document go directly from "prerequisites" to 

> Setting up a cluster is as simple as running:  
> 
> `export KUBERNETES_PROVIDER=vagrant`  
> `curl -sS https://get.k8s.io | bash`  

Required steps in between include (but are not necessarily limited to):
- which command "initializes the correct vagrant machine"? (as an example)

```
      vagrant init hashicorp/precise32  // download machine image
      vagrant up  // start virtual machine
      vagrant ssh  // connect to machine locally.
```
- how to ensure required linux configurations are correct per the prerequisites in https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/docker.md (or the name of a maintained & preconfigured image instead of the `hashicorp/precise32` option above)   
- how to install Docker and ETCD on the downloaded machine   

Once prerequisites, etcd, & docker are correctly installed on the downloaded vagrant machine I believe that _THEN_ the getting started on vagrant document might actually be able to continue with "it is as simple as..." though I'm not an expert so would prefer to pass this by a member of the expert developer team.

I am more than happy to test the documentation and help expand on the errors & troubleshooting steps I see along the way.

The eventual goal would be a document that can be run on a "clean" system from beginning to end with no un-handled errors and a working kubernetes system at the end.

**Comment by AlexChesser** [comment]
I've now got a kubernetes cluster running locally on a boot2docker machine on windows. The steps in the "getting started with docker" document worked when executed within the scope of the docker machine.

A key misunderstanding on my part was around finding the correct K8S_VERSION which I have corrected and updated.

**Comment by mikedanese** [comment]
Thanks for submitting PR.
