### ISSUE TITLE
Local instructions don't say how to get the code.

### ISSUE THREAD

**Issue by broady** [kubernetes/kubernetes#17519]
To reproduce:

1. Go to http://kubernetes.io/
2. Click "Try Kubernetes"
3. Click "Local"

Observe:
First step says to "cd kubernetes". Instructions don't say how to fetch whatever files are required.

Expected:
`$ git clone https://github.com/kubernetes/kubernetes.git`

**Comment by AlexChesser** [comment]
Made a pull request adding your expected option
https://github.com/kubernetes/kubernetes/pull/17552

**Comment by dims** [comment]
The referenced PR has merged. Can we please close this issue?

**Comment by paralin** [comment]
@broady @mikedanese close please :)
