### ISSUE TITLE
Service/Controller modifications using kube-push

### ISSUE THREAD

**Issue by geoah** [kubernetes/kubernetes#17513]
I have a cluster setup using `kube-up.sh` with `KUBE_ENABLE_CLUSTER_MONITORING=influxdb`.
Everything is working as expected, controllers `heapster-v10`, `monitoring-influxdb-grafana-v2` are deployed and running. Running branch `release-v1.1` btw.

I decided to move influx and grafana to a dedicated instance so I tried to change `KUBE_ENABLE_CLUSTER_MONITORING=influxdb` to `KUBE_ENABLE_CLUSTER_MONITORING=standalone` and modify `cluster/addons/cluster-monitoring/standalone/heapster-controller.yaml` setting a new name and adding some arguments to the container command.

I assumed that running `kube-push` would at least create the new heapster controller, and at best it would also remove the influx/grafana stuff.
But nothing changed on the cluster.

If I manually delete the controllers and services and manually add the new heapster controller, after a bit something returns them to the previous state - it removes the new controller and re-creates the influx/grafana ones.

Is this something that should be working with `kube-push` or not?
And if not, how do I make such a change?

Thank you very much in advance.

**Comment by geoah** [comment]
ps. I get how addons can be [manually managed](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons#cluster-add-ons) I'm trying to understand how `kube-push` fits into this.

**Comment by piosz** [comment]
I investigated the issue and according to [the documentation](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/README.md) you have to update also the name of an addon (for example ```heapster-v10``` -> ```heapster-v11```). ```kube-push``` updates the content of ```/etc/kubernetes/addons``` and then ```kube-addon``` service should perform an update based on the new content of the directory.

Closing as WAI.

Thanks @marekbiskup for help!
