### ISSUE TITLE
mounting secrets when running containerized kubelet only works with dash as /bin/sh

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#17522]
Ref: #13791
I know the PR is a work-around, but when running this on hosts which have bash symlinked to `/bin/sh`, it doesn't work. The `ca.crt` file in `/var/run/secrets/kubernetes.io/` has a lot of `\n`s in it. 
A small example: 
```
-----BEGIN CERTIFICATE-----\nMIIDRDCCAi6gAwIBAgIBATALBgkqhkiG9w0BAQswIjEgMB4GA1UEAwwXMTkyLjE2\nOC4xLjY5QDE0NDc4ODM0MjQwHhcNMTUxMTE4MjE1MDI0WhcNMTYxMTE3MjE1MDI0\nWjAiMSAwHgYDVQQDDBcxOTIuMTY4LjEuNjlAMTQ0Nzg4MzQyNDCCASIwDQYJKoZI\nhvcNAQEBBQADggEPADCCAQoCggEBANzppgrQO9hOUYGMcn5HhNuIPc4baqecc6j...
```

This makes serviceAccount secrets unusable on **hosts** with `/bin/sh -> bash`, because of https://github.com/kubernetes/kubernetes/blob/v1.1.1/pkg/util/io/writer.go#L60

`dash echo` automatically replaces `\n` with a newline, while bash writes it literally.
bash needs `echo -e` to function.

So, which alternative is the best?
I have to patch my system which runs with bash as `/bin/sh`. 
But the problem is that once when one has compiled with bash, what should happen on a `dash` platform?
@fgrzadkowski @dalanlan

**Comment by luxas** [comment]
From https://wiki.ubuntu.com/DashAsBinSh
> **echo**
> Options to echo are not portable. In particular, the echo -e option is implemented by some shells, including bash, to expand escape sequences. However, dash is one of the other family of shells that instead expands escape sequences by default. Do not rely on either behaviour. If you need to print a string including any backslash characters (related checkbashisms warning text: unsafe echo with backslash), use the printf command instead, which is portable and much more reliable.

> As a special exception, echo -n is supported on Ubuntu systems, although you may replace it with printf if you are concerned about wider portability.

Could we use `sh` with `printf` instead of `echo`? It should work just fine. 
@fgrzadkowski I could send a small PR with that change if you want. 
It would make that `nsenter` hack more portable.

**Comment by fgrzadkowski** [comment]
@luxas I guess ```printf``` should work. Please send a PR with a fix.

**Comment by luxas** [comment]
Already fixed on master, it seems: https://github.com/kubernetes/kubernetes/pull/16969#issuecomment-158374087

Thanks anyway.
