### ISSUE TITLE
We should have a concrete error in kubectl for kubernetes.io/cluster-service: "true" containers manipulation

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#17532]
I had a user report that they couldn't delete a system controller:
https://twitter.com/ericbuth/status/667069692109017088

ultimately we referred to:
https://github.com/kubernetes/kubernetes/issues/11435#issuecomment-122254035

But the existing behavior when this happens is bad/opaque.  If we don't want to allow people to do this, we should kick a very explicit message inside kubectl.

**Comment by nikhiljindal** [comment]
cc @janetkuo 
I am user support on call today and I see a lot of users are seeing this

**Comment by janetkuo** [comment]
So, in kubectl, when we see the following label `kubernetes.io/cluster-service: "true"` in a resource, we should print out error messages when users try to mutate (create, delete, update) that resource, right?

The error message looks like: `Error: Manipulation of add-ons is discouraged; the system will bring them back to the original state.`

**Comment by nikhiljindal** [comment]
Yes. We can say users should not manipulate cluster services and link to https://github.com/kubernetes/kubernetes/tree/master/cluster/addons

**Comment by sheerun** [comment]
Happened to me today. I wanted to deploy service, but it magically disappeared after a minute.

**Comment by bboreham** [comment]
Happened to me today - tried to create a DaemonSet and it had `kubernetes.io/cluster-service: "true"` because I was copy-pasting and didn't check what that might mean.  No way I would have figured it out without help from folks on Slack.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc 
@kubernetes/sig-cluster-lifecycle-misc

**Comment by luxas** [comment]
cc @justinsb on the new addon manager thingy
