### ISSUE TITLE
Remove branch conformance-test-v1

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#17536]
We got a question on Slack today about the `conformace-test-v1` branch.  According to @mikedanese it should be removed, and `hack/conformance-test.sh`'s documentation should be updated appropriately.

@erictune What is the current best practice for conformance testing?

cc @alexhersh

**Comment by spiffxp** [comment]
/cc @lavalamp @kubernetes/sig-scalability

This has come up a few times in the scalability SIG and we've gotten a different answer.  We want to be clear that whatever we're performance testing is considered a "conformant" cluster.  FWIW I'd be in favor of something like using tests from a given release branch

**Comment by spiffxp** [comment]
Relates to #14913

**Comment by quinton-hoole** [comment]
Yes, there is a meeting at 11:00 Pacific today to thrash this out.  Let me know if you want to attend.

**Comment by lavalamp** [comment]
What was the outcome of the meeting?

**Comment by ihmccreery** [comment]
Short answer: conformance tests should be run off of the release branches, where "v1 conformance" is defined as v1.0.

The three action items I foresee:

- [ ] clearly document what the conformance expectations are;
- [ ] fix existing conformance scripts to work according to those expectations; and
- [ ] incorporate these expectations into our (soon-to-be-documented) releasing plan going forward.

@spiffxp and I will be working on this when we have cycles.

**Comment by ixdy** [comment]
cc @karlkfi

**Comment by karlkfi** [comment]
@quinton-hoole Was that a scalability or testing sig meeting?

I think it's important to note that we will continue to run conformance/e2e tests on master and PRs with the tests and test harnesses on the branch being tested. This allows us to keep up to date with the HEAD conformance that will be be "current" on the the next release.  

The conformance testing against specific versions will have to happen in parallel.

**Comment by quinton-hoole** [comment]
@karlkfi the meeting was specifically about conformance testing, and wasn't actually a SIG meeting at all (although in retrospect, perhaps it should have been).  

And, yes, running tests in master against older release branches will definitely sometimes be useful, in anticipation of each release, as you suggest.  But we also need a set of stationary conformance standards for people to test against. If a particular person or organization wants to release something and claim it to be fully conformant with Kubernetes version x.y.z, we need a clear immovable definition of what the latter means.  We now define that to be the conformance tests in the x.y.z release branch.

Make sense?

**Comment by karlkfi** [comment]
Yup. 

We've added code to the mesos CI scripts to make that happen: https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/ci/test-conformance.sh#L35-L42

- By default (`CONFORMANCE_BRANCH` unspecified) it runs the tests from the branch being tested.
- When `CONFORMANCE_BRANCH` is set, it runs the tests from the specified branch.

**Comment by ihmccreery** [comment]
This is blocked on #18162.

**Comment by ihmccreery** [comment]
Removing myself as assignee, since this won't happen until #18162.

**Comment by ixdy** [comment]
I intend to delete the `conformance-test-v1` branch this week, since per #18162 we intend to use test tags + the release branches. Any objections to my doing this?

@erictune @kubernetes/sig-testing

**Comment by ihmccreery** [comment]
SGTM.

**Comment by ihmccreery** [comment]
cc especially @spiffxp @jayunit100.

**Comment by erictune** [comment]
Ok

**Comment by spiffxp** [comment]
SGTM as well

**Comment by bgrant0607** [comment]
Why is this attached to the 1.2 milestone?

**Comment by ixdy** [comment]
Deleting branch now.
