### ISSUE TITLE
Secret volume should have an explicit file->key mapping

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#17540]
The secrets volume assumes keys == filenames.  DownwardAPI does this better.  Maybe we can add an optional mapping construct to secret volumes.

@pmorie @derekwaynecarr @swagiaal

**Comment by pmorie** [comment]
:+1: I forgot to write this up after referring to it last night. Does anyone dispute that we should use the same API as we have for downward API volume?

**Comment by thockin** [comment]
Dup of #4789, 13000 issues later :)
