### ISSUE TITLE
Request Authorization vs Field Authorization

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#17549]
This issue is about defining a pattern we already have.

Proposed definitions:
- **object authorization**: deciding if a request is allowed based only on a limited set of attributes which are common to all Kubernetes-style objects and requests.
- **field authorization**: deciding whether creating or updating an object _with specific values in specific fields_ is authorized.

Reasons why it make sense to treat these as separate things:
1. _one needs to be pluggable but the other does not_.   Object authorization is a pretty generic concept.  It has been done many times before.  Therefore, people have opinions about it and existing systems they want to tie into.  So, it needs to be pluggable.  Field authorization is very specific to our types, such as Pod.  So, people are going to look to us on how to do it.  And their existing systems are not going to have support for it.  So, it is not clear that it needs to pluggable.
2. _need to happen at different times_: Object Authz should happen as early as possible, so we can reject totally unauthorized request as early as possible.  Since object authz ony depends on attributes found in the request path and HTTP headers, it can happen before the body is parsed.  Then if it it passes the Object Authorizer, then we parse it.  Then we should run admission controllers which do defaulting of fields.  Then, after that is done, we should do field authorization.  Doing it after most admission controllers run makes it less likely that the admission controllers are confused deputies.  Some admission controllers, like Quota, need to run after field authz, but that should be a small set.
3. _third party apiservers_: if I run a third party apiserver, I probably want to delegate object authz to be the same as whatever the first party apiserver uses.  Object Authz is generic.  But since Field Authz is specific to particular objects, it can be hard-coded into a third-party apiserver, for the types of objects it provides.

@deads2k @liggitt @smarterclayton @lavalamp @nikhiljindal

**Comment by deads2k** [comment]
I think splitting field level authorization makes sense, but I'm less sure about how far back in the admission chain we should push it.  I think I would put it closer to the beginning of admission.  Putting it near the end means that admission controllers that mutate system-ish fields would have the resulting object authorized afterwards.  I'm not sure that's the behavior that I want. 

Take the ServiceAccount admission controller.  It sets the `serviceAccountName`.  I might  not want my user mutating the saName, so I write a rule that precludes him from changing it.  Now he can't create pods.  Was my intent fulfilled?

**Comment by erictune** [comment]
I wasn't thinking about a generic mechanism for letting specific users access specific fields.  I see sub-resources like Scale as the way to do that.

I meant renaming admission controllers which are related to authorization from "admission controllers" to "field authorizers".

**Comment by erictune** [comment]
The admission controllers which modify fields (I call these "defaulters") should be separate from and run before the ones that check whether certain field values are allowed (I call these "field authorizers").

**Comment by davidopp** [comment]
Vaguely related (and if this is the wrong issue for this request, please let me know): I would like there to be some way for a cluster admin to prevent end-users from setting the nodeName field directly in the pod or pod template. In other words, admin should be able to say "only schedulers and the following controllers should be allowed to set nodeName"

Of course, this setting should be optional.

**Comment by lavalamp** [comment]
How about "resource authorization", "request authorization", or "metadata authorization" instead of "object authorization"?

**Comment by erictune** [comment]
I like "resource authorization" vs "field authorization".

Or "generic authorization" vs "type-specific authorization"

**Comment by deads2k** [comment]
I prefer "request authorization", "resource authorization", and "generic authorization" in that order.

I like "field authorization" over "type-specific authorization".

**Comment by davidopp** [comment]
Another possible use case
https://github.com/kubernetes/kubernetes/pull/18263#issuecomment-163436433

**Comment by erictune** [comment]
Okay, the names are:
- "Request Authorization", which uses non-body aspects of the request (user from headers, path components of the URL). 
- "Field Authorization", which uses fields of the Json from the body

**Comment by liggitt** [comment]
stratification between generic authorization (RBAC, webhook, etc) and admission validation (compiled in or via webhook) is pretty well defined at this point.
