### ISSUE TITLE
 Install kubernetes v1.1.1 faillure on ubuntu

### ISSUE THREAD

**Issue by wangqunOne** [kubernetes/kubernetes#17547]
Hi, I try to install kubernetes v1.1.1. 
My install main process is follow:
1. install docker.
2. run ./build.sh.  I use the default file.
3. config config-default.sh. 
config the content of config-default.sh:

export nodes=${nodes:-"root@9.5.125.51 root@9.5.125.52"}
role=${role:-"ai i"}
export NUM_MINIONS=${NUM_MINIONS:-2}

4. Run install command "KUBERNETES_PROVIDER=ubuntu ./kube-up.sh"
Kubernetes cluster is running.  The master is running at:

  http://9.5.125.51:8080

Using master 9.5.125.51
It looks as if you don't have a compiled kubectl binary

If you are running from a clone of the git repo, please run
'./build/run.sh hack/build-cross.sh'. Note that this requires having
Docker installed.

If you are running from a binary release tarball, something is wrong.
Look at http://kubernetes.io/ for information on how to contact the
development team for help.
5.Run "kubectl get nodes"
error: couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused.

**Comment by dalanlan** [comment]
This issue is fixed by #16850
My guess is that you didn't bring it up from HEAD, or you won't get any file named as `build.sh` as of today. And you would not suffer this.
Don't bother to download the binaries yourself, the script will take care of you.
