### ISSUE TITLE
Registry Renaming etcd -> storage

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#17546]
Now that all elements in the registry have been switched to use the storage layer we should probably move to rename the /etcd\* to something more generic, as we work to shard to different backends.  

I still have to finish up some other transformations 1st, but this is a placeholder. 

My vote might be keyval.  

/cc @jayunit100 @lavalamp @wojtek-t @rrati

**Comment by jayunit100** [comment]
Definitely agree , sooner the better if we are going to support more backends
"keyval" "kvstore" "dbstore" ... Any of those names would work

**Comment by wojtek-t** [comment]
cc @smarterclayton  - as he had some objections in the past

**Comment by smarterclayton** [comment]
If there is no mention of anything etcd specific in the packages, I'm fine with renaming the registries.  If they are still coupled to etcd (because of behavior, or the storage interface) I'm less comfortable.  You've made "generic.Etcd" "generic.KV" and purged any etcd isms from that class?

**Comment by timothysc** [comment]
I'm mid-flight on abstracting the error handling, which is the last vestige.  After that, the purge will be complete.

**Comment by smarterclayton** [comment]
Then I don't have an issue with the rename.

On Fri, Nov 20, 2015 at 5:08 PM, Timothy St. Clair <notifications@github.com

**Comment by timothysc** [comment]
xref #18163

**Comment by timothysc** [comment]
Re-starting down this road in prep for both etcd3 and potentially kafka.

**Comment by wojtek-t** [comment]
@timothysc - just to clarify what you would like to rename.
Are you talking about pkg/registry/*** ?
This one, I completely agree we should rename.

**Comment by timothysc** [comment]
@wojtek-t yup

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by timothysc** [comment]
sounds good, I actually have a PR I need to push on this.
