### ISSUE TITLE
support to delete resource<pod,service> via its ip 

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#17558]
It'd be great to have this, yet i'm not positive if I'm asking for too much.

My humble use case is that we run a health-check agent inside each container, which is maintained by `kubelet`. Once the agent complains that the app within runs too slow or sort of, it would trigger `kubelet` to kill the corresponding pod. The agent would give out the pod ip, and hopefully we can make it straightforward.

Or we could have a work around, kinda like reverse dns, ref #15763, which isn't supported either.

**Comment by mikedanese** [comment]
Could reverse DNS using kube-dns and delete by name

**Comment by liggitt** [comment]
Could we add field selector support for the IP, so you could *look up* the pod/service by its IP, then delete normally?

**Comment by dalanlan** [comment]
>Could reverse DNS using kube-dns and delete by name

kube-dns handles service thing, and It should work :) 
Unfortunately reverse dns is not yet supported AFAIK. Ref#15690

>Could we add field selector support for the IP, so you could look up the pod/service by its IP, then delete normally?

That's lovely

**Comment by thockin** [comment]
Why can't this agent simply act as the pod's health check - report
unhealthy if bad and thereby make kubelet restart the pod?

**Comment by thockin** [comment]
We do not make DNS be pod names

**Comment by thockin** [comment]
I don't understand the problem - kubelet knows the pod name

**Comment by liggitt** [comment]
Didn't know all the context… agree if the pod name is already known, this shouldn't be an issue.

**Comment by dalanlan** [comment]
@thockin kubelet knows the pod name of course, yet the so-called agent is actually a process runs within the pod. That said, it wants to be self-destroyed.

**Comment by dalanlan** [comment]
It would be awkward if the agent needs to know the pod name, 'cause it should not even be aware that it runs in the "matrix".

**Comment by liggitt** [comment]
If that's true, the agent making an API call to delete the pod seems very aware of the matrix.  Couldn't the health check be surfaced to the kubelet as a liveness check? Wouldn't that let the kubelet kill/restart the container?

**Comment by dalanlan** [comment]
>  the agent making an API call to delete the pod seems very aware of the matrix. 

It won't make api call directly. There exists a middleware which handles this job. 

> Couldn't the health check be surfaced to the kubelet as a liveness check? 

I assume the liveness check you're talking about is trying to use livenessProbe. Yet this agent expects a high degree of coupling with business logic (not my work though). It won't be easy to decouple, i'm afraid.

**Comment by dalanlan** [comment]
To be more specific, this agent i'm talking about is a JVM byte code Instrumentation (with a command-line interface). It helps with profiling and tracing, and reporting predefined exceptions to the middleware. 
I believe kubelet isn't capable of this heavy and messy work.

**Comment by liggitt** [comment]
can the middleware react to reported exceptions by surfacing a non-"ok" response to a /healthz endpoint the liveness probe can ping?

**Comment by thockin** [comment]
My suggestion was to have a small bridge container - it knows how to read your "agent" state and converts it to healthz HTTP, which kubelet uses to kill the pod.  This is what we do for DNS, for example.

**Comment by dalanlan** [comment]
Thank you for all your suggestion. I'll see what i can do.
Yet Is there any particular  reason to *avoid* field selector support for ip? I'm pretty sure it's extraordinarily useful. Other use cases may benefit a lot.

**Comment by liggitt** [comment]
It would be a relatively expensive operation, assuming you needed to look up a pod by IP only, without knowing which namespace it was in. Field selectors extract all items in the list from etcd, build field selector maps for each one, and compare to the specified filter.

**Comment by thockin** [comment]
The main reason to avoid it is that every feature has a cost over time, and
if there's a good workaround for a not-very-common feature, we should rely
on that.

**Comment by wangzhezhe** [comment]
May be you could start a demon to collect the info of  <podname,podip>  , than watching the etcd , if the information of pod have changed ,  than upgrading the map , but it's a little bit complex.

**Comment by bgrant0607** [comment]
@dalanlan Do liveness probes not do what you want? Killing the container is insufficient?

Would #17244 address your use case?

**Comment by bgrant0607** [comment]
Lookup by IP would be pretty useful for debugging -- see #3481.

However, it doesn't sound like the best solution for this use case.

**Comment by dalanlan** [comment]
@bgrant0607 Liveness probes would not fit in after i dug it up. The best thing we could ask for is to look up by ip. Since it's not gonna supported as i can foresee, we finally decided to cache pod/ip pair in etcd and turns to it for help everytime before we tried to make an api call (which might not be a good solution, i' ll admit).

**Comment by spzala** [comment]
@dalanlan  - hi, just a follow up, wondering if you had a chance to look at #17244?, and see if that provides a good solution for this issue?

**Comment by thockin** [comment]
This is 16 months since last update.  Closing :)

**Comment by spzala** [comment]
👍 :) Thanks @thockin
