### ISSUE TITLE
Define kubernetes node spec for systemd hosts

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#17556]
This is a tracking issue for identifying enhancements:

1. system daemon management (```kubelet```, ```kube-proxy```, ```docker```)
  * downstream providers (OpenShift) may combine ```kubelet``` and ```kube-proxy``` into a single node daemon, so make no assumptions on pid names
  * safe to assume daemons are launched via a ```systemd.service```
  * safe to assume daemons are in the ```system.slice```
  * assigning resource limits to system daemons must happen via ```systemd.SetUnitProperties``` and not via direct manipulation of cgroup hierarchy (unified model assumes single writer)
  * kube on non-systemd sets some values as a percentage of host capacity today (cpu/memory)
2. other operator host services / containers should go under the ```system.slice``` per normal
3. other operator virtual machines / containers (with init systems) should go under ```machine.slice``` per normal
4. kubelet should support tracking ```system.slice```, ```user.slice```, and ```machine.slice``` by default to compute an ```allocable``` scheduling capacity of the node
  * do we need to take list of additional slices to track as part of *system reserved*?
5. kubelet launched containers should go in a dedicated slice ```kubelet.slice```
  * do we need to let operators specify the name?
  * today, all containers go in ```system.slice/docker-xyz``` which makes future accounting of ```allocatable``` difficult, no ability to distinguish from containers not launched by kubelet
  * slice should have cpu and memory limits specified that align with low compute resource killer?
6. kubelet launched containers should go in a sub-slice per QoS tier for cgroup controlled resources
  * ```kubelet-besteffort.slice``` - hold all best effort containers
  * ```kubelet-burstable.slice``` - hold all burstable containers
  * ```kubelet-burstable-guaranteed.slice``` - hold all guaranteed containers
  * docker needs to be told the cgroup parent for it to place the ```systemd.scope``` that tracks cgroup settings
  * should we set any cap limits for best effort tier?
  * investigate usage of memory soft limits; docker run added ```memory-reservation``` option now to set soft-limit.
  * slices should be created through systemd APIs
7. Do we need to introduce systemd specific parameters to ```kubelet```?
8. Use https://github.com/coreos/go-systemd for slice creation and introspection
9.  Refactor the container_manager_linux file in the kubelet to handle systemd environment.
  * validate cgroup accounting features are on (this should really be checked on individual slices)
  * setup kernel tunables (this is probably shared as it is today)
  * manage system containers (this is the part that needs to be injected to use slices)
  * enforce system container limits (bundle this behavior with the above)
  * enforce docker is in container (in systemd env, i think its safe to assume its in system.slice)
  * oom score adjusting (this could be handled by unit file manipulation)
10. Define an interface that knows how to place a container in a cgroup based on qos-tier
  * if ```cgroup-parent``` was specified as a flag on kubelet, it would take precedence, but we should remove that argument (mark as deprecated)

**Comment by luxas** [comment]
You might know it already, but when using systemd > 225, `docker.service` must have this arg specified: `--exec-opt native.cgroupdriver=cgroupfs`

https://github.com/docker/docker/issues/16256

**Comment by derekwaynecarr** [comment]
Proposal document is here: https://github.com/kubernetes/kubernetes/pull/17688

**Comment by derekwaynecarr** [comment]
I am closing this issue because there is an active proposal PR that can track this.
