### ISSUE TITLE
Cinder Volume Plugin Should use mount.SafeFormatAndMount

### ISSUE THREAD

**Issue by swagiaal** [kubernetes/kubernetes#17565]
The Cinder volume plugin currently implements its own version of SafeFormatAndMount. It should use mount.SafeFormatAndMount from "util/mount"

@jsafrane @spothanis

**Comment by jsafrane** [comment]
I agree, there is nothing special about Cinder volume, it's just a block device, similar to AWS EBS, GCE PD or iSCSI.

**Comment by jsafrane** [comment]
I tested it with today's master and there was actually a bug, `cinder_util.go` should use `FormatAndMount` instead of plain `Format`:

```diff
--- a/pkg/volume/cinder/cinder_util.go
+++ b/pkg/volume/cinder/cinder_util.go
@@ -80,7 +79,7 @@ func (util *CinderDiskUtil) AttachDisk(b *cinderVolumeBuilder, globalPDPath stri
                }
        }
        if notmnt {
-               err = b.blockDeviceMounter.Mount(devicePath, globalPDPath, b.fsType, options)
+               err = b.blockDeviceMounter.FormatAndMount(devicePath, globalPDPath, b.fsType, options)
                if err != nil {
                        os.Remove(globalPDPath)
                        return err

```

I pushed fixed patch and tested that Cinder volumes with `FsType="xfs"` are now automatically formatted with `xfs`, which was not possible before this patch.
