### ISSUE TITLE
[Kubernetes][Mesos] Installation latest kubernetes version (1.1.1) on Mesos 0.25

### ISSUE THREAD

**Issue by slimshady986** [kubernetes/kubernetes#17562]
I am having problem installing the last version of kubernetes over mesos (https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/mesos.md).
- MESOS: 0.25.
- K8S:1.1.1.
- docker 1.7.1
- OS: centos 7 (3.10.0-229.20.1.el7.x86_64)

All goes right until the nginx pod deployment. I have the following for the describe command:

```
Name:                           nginx
Namespace:                      default
Image(s):                       nginx
Node:                           slave-2.localdomain/<ip>
Start Time:                     Thu, 19 Nov 2015 09:30:25 +0100
Labels:                         <none>
Status:                         Terminating (expires Thu, 19 Nov 2015 09:46:47 +0100)
Termination Grace Period:       30s
Reason:
Message:
IP:
Replication Controllers:        <none>
Containers:
  nginx:
    Container ID:
    Image:              nginx
    Image ID:
    State:              Waiting
      Reason:           ImageNotReady
    Ready:              False
    Restart Count:      0
    Environment Variables:
Conditions:
  Type          Status
  Ready         False
No volumes.
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath                           Reason                  Message
  ─────────     ────────        ─────   ────                            ─────────────                           ──────                  ───────
  17m           17m             3       {scheduler }                                                            FailedScheduling        Error scheduling: No suitable offers for pod/task
  17m           17m             1       {scheduler }                                                            Scheduled               Successfully assigned nginx to slave-2.localdomain
  17m           17m             1       {kubelet slave-2.localdomain}  implicitly required container POD       Failed                  Failed to start with docker id add3a9e3e70d with error: API error (500): Cannot start container add3a9e3e70d236d18ebd59774a01050af9f830fabc9db80e2de557fa36bdf40: [8] System error: Invalid argument

  17m   17m     1       {kubelet slave-2.localdomain}          FailedSync      Error syncing pod, skipping: API error (500): Cannot start container add3a9e3e70d236d18ebd59774a01050af9f830fabc9db80e2de557fa36bdf40: [8] System error: Invalid argument

  17m   17m     1       {kubelet slave-2.localdomain}  implicitly required container POD       Created Created with docker id add3a9e3e70d
  17m   17m     1       {kubelet slave-2.localdomain}  implicitly required container POD       Created Created with docker id 8ecd85810788
  17m   17m     1       {kubelet slave-2.localdomain}  implicitly required container POD       Failed  Failed to start with docker id 8ecd85810788 with error: API error (500): Cannot start container 8ecd85810788ceea14111290687b6f39cb189f4abfb23f7dd429f05eceb35ffa: [8] System error: Invalid argument

  17m   17m     1       {kubelet slave-2.localdomain}          FailedSync      Error syncing pod, skipping: API error (500): Cannot start container 8ecd85810788ceea14111290687b6f39cb189f4abfb23f7dd429f05eceb35ffa: [8] System error: Invalid argument

  17m   17m     1       {kubelet slave-2.localdomain}  implicitly required container POD       Failed  Failed to start with docker id c77a93c255f8 with error: API error (500): Cannot start container c77a93c255f8fbf933c488a20b1095a6b24d32fb05a78eab9b62ef5f77088470: [8] System error: Invalid argument

  17m   17m     1       {kubelet slave-2.localdomain}  implicitly required container POD       Created         Created with docker id c77a93c255f8
  17m   17m     1       {kubelet slave-2.localdomain}                                          FailedSync      Error syncing pod, skipping: API error (500): Cannot start container c77a93c255f8fbf933c488a20b1095a6b24d32fb05a78eab9b62ef5f77088470: [8] System error: Invalid argument
```

for your information, the docker pull on the slave-2 machine works fine.
and the docker logs gives this:

```
19 09:35:15 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:15.508037826+01:00" level=error msg="Handler for GET /images/{name:.*}/json ret
urned error: No such image: nginx"
Nov 19 09:35:15 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:15.508046766+01:00" level=error msg="HTTP Error" err="No such image: nginx" sta
tusCode=404
Nov 19 09:35:15 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:15.869861252+01:00" level=error msg="Handler for GET /images/{name:.*}/json ret
urned error: No such image: nginx"
Nov 19 09:35:15 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:15.869886174+01:00" level=error msg="HTTP Error" err="No such image: nginx" sta
tusCode=404
Nov 19 09:35:16 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:16.485117386+01:00" level=warning msg="signal: killed"
Nov 19 09:35:16 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:16.588399051+01:00" level=error msg="Error unmounting device 5a13e404c79048d605
1b39aa5bace34834e5bf6b02ac57e39d7e2f58d1e1ffdf: UnmountDevice: device not-mounted id 5a13e404c79048d6051b39aa5bace34834e5bf6b02ac57e39d7e2f58d1e1ffdf"
Nov 19 09:35:16 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:16.588883456+01:00" level=error msg="Handler for POST /containers/{name:.*}/sta
rt returned error: Cannot start container 5a13e404c79048d6051b39aa5bace34834e5bf6b02ac57e39d7e2f58d1e1ffdf: [8] System error: Invalid argument"
Nov 19 09:35:16 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:16.588964004+01:00" level=error msg="HTTP Error" err="Cannot start container 5a13e404c79048d6051b39aa5bace34834e5bf6b02ac57e39d7e2f58d1e1ffdf: [8] System error: Invalid argument" statusCode=500
Nov 19 09:35:16 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:16.624302812+01:00" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: nginx"
Nov 19 09:35:16 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:16.624325229+01:00" level=error msg="HTTP Error" err="No such image: nginx" statusCode=404
Nov 19 09:35:16 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:16.626896759+01:00" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: nginx"
Nov 19 09:35:16 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:16.626924120+01:00" level=error msg="HTTP Error" err="No such image: nginx" statusCode=404
Nov 19 09:35:17 slave-2.sid.atos.net docker[12434]: time="2015-11-19T09:35:17.646082496+01:00" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: nginx"
```

I tried successfully to make a docker run of the nginx image on the slave-2

any idea?
Thanks in advance

**Comment by alexisvincent** [comment]
+1

**Comment by mysterytree** [comment]
＋1

**Comment by mysterytree** [comment]
![image](https://cloud.githubusercontent.com/assets/6166794/12133584/914ad664-b461-11e5-88bd-f3504dee9ff1.png)

**Comment by mysterytree** [comment]
OS: centos 7 (3.10.0-229.20.1.el7.x86_64)

**Comment by jessesanford** [comment]
I can confirm that I see this as well on RHEL 7.1. 

[root@node2 vagrant]# uname -a
Linux node2 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[vagrant@node1 ~]$ mesos-master --version
mesos 0.28.0

[vagrant@node1 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.0.923+590038dcf13ca2", GitCommit:"590038dcf13ca280251c20fd88334069c732ac2f", GitTreeState:"clean", BuildDate:"2016-03-25T19:36:58Z", GoVersion:"go1.4.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.0.923+590038dcf13ca2-dirty", GitCommit:"590038dcf13ca280251c20fd88334069c732ac2f", GitTreeState:"dirty", BuildDate:"2016-03-26T00:26:57Z", GoVersion:"go1.4.2", Compiler:"gc", Platform:"linux/amd64"}

[root@node2 vagrant]# docker --version
Docker version 1.8.2-el7.centos, build a01dc02/1.8.2

.[root@node2 vagrant]# ./check-config.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-3.10.0-229.el7.x86_64 ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
  (RHEL7/CentOS7: User namespaces disabled; add 'user_namespace.enable=1' to boot command line)
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled
- CONFIG_NETPRIO_CGROUP: enabled (as module)
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

**Comment by jessesanford** [comment]
I should mention that I was following the same tutorial (at it's new location): http://kubernetes.io/docs/getting-started-guides/mesos/
