### ISSUE TITLE
Consider masking `Authorization` header value in debugging transports

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#17564]
`kubectl get pods --v=8` is very handy for collecting wire traces of API communications, and is a good starting point for debugging problems, but exposes any bearer/basic auth in use. Requiring redaction before posting output is probably not good.

cc @deads2k

**Comment by deads2k** [comment]
A local command that locally outputs information already available locally that demonstrates exactly what is being sent to the server seems pretty useful.  I've wanted to go to 11.....

**Comment by liggitt** [comment]
I know… seeing the password getting sent already helped catch an issue. I want it both ways, masked when sensitive (and when I'm asking someone else to run it and send me the results), unmasked when useful :-/
