### ISSUE TITLE
How do admins of non-cloud nodes apply node zone labels for Kubernetes Lite?

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#17575]
https://github.com/kubernetes/kubernetes/pull/16866#issuecomment-158125456 refers, copied here:

erictune commented:
We are going to want to have kubelet-computed labels, as well as labels that a user puts into a file on the kubelet and the kubelet automatically syncs to the node. We should think about how those two sets of labels interact.

Specifically, if a user is running on bare metal, and the user does not have a cloud provider to get the zone info from, the user are going to want to set the zone label via the file method.

Should the user should also use the failure-domain.kubernetes.io/zone label in this case?

Or should they use example.com/custom-zone, and then adjust the scheduler to somehow spread on this label instead?

I think this depends on whether the domain prefix means who owns the code that generated the label value, or if it means who owns the meaning of the label.

If we allow kubernetes.io/ domain labels in the file, then we need to decide which takes precedence, the file or the cloud provider. If we don't allow kubernetes.io in the file, then (maybe) we do not have to think about precedence.

**Comment by mikedanese** [comment]
Related to #13524 cc @pwittrock

**Comment by vishh** [comment]
Are file based labels required for v1.2? Do we have any use cases or customers requesting such a feature in the next release?

**Comment by quinton-hoole** [comment]
We would like Ubernetes Lite to work on bare metal machines, so yes, ideally required for 1.2.  Although we *could* postpone and instead require admins to manually label nodes via the API for Ubernetes Lite on bare metal for v 1.2.

**Comment by mikedanese** [comment]
> as well as labels that a user puts into a file

Why is kubectl or a bootstrapping pod not sufficient? Why is it important to have this feature baked into kubelet that just proxies to a request to an api client? This requirement seems like feature bloat.

**Comment by mml** [comment]
Assuming we do have the precedence question, I would expect (least surprise) the local file to win.

**Comment by vishh** [comment]
FYI: #17265 introduced two additional means to add labels to kubelets. We should decide on the precedence soon.

**Comment by quinton-hoole** [comment]
@erictune FYI, our conversation yesterday refers.

**Comment by vishh** [comment]
cc @pwittrock who is working on labels support in kubelet.

**Comment by davidopp** [comment]
ping -- this is marked as 1.2 milestone but I have not been following the PRs on this subject. Can someone summarize the status?

**Comment by mikedanese** [comment]
I think this is good to go now that --node-labels flag is in

**Comment by vishh** [comment]
Yes. We might have to document that flag a bit more though.

**Comment by goltermann** [comment]
Is this pending more code work, or just documentation?

**Comment by davidopp** [comment]
Just needs documentation. @quinton-hoole can you add something in the appropriate doc in admin/ for this?

BTW why does the flag definition in Kubelet say this feature is "alpha"? What does that mean in the context of a Kubelet flag.

https://github.com/kubernetes/kubernetes/blob/73b39e9f1e80ea79f423581c7761acdd1e1b19ba/docs/admin/kubelet.md

**Comment by davidopp** [comment]
ping @quinton-hoole

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#37.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
