### ISSUE TITLE
Flake: Horizontal pod autoscaling [Autoscaling Suite] should scale from 1 pod to 3 pods and from 3 to 5 (via deployment, with scale resource: CPU)

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#17584]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1766/

@davidopp please find an owner.

**Comment by piosz** [comment]
cc @jszczepkowski @mwielgus

**Comment by piosz** [comment]
duplicate of #16425
