### ISSUE TITLE
Flake: Services should work after restarting kube-proxy

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#17583]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9596/

@thockin, please find an owner.

**Comment by lavalamp** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9501/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9502/

Failed 3 times in two jobs now. Maybe look for something to revert.

**Comment by thockin** [comment]
afaik nothing has changed here, looking to repro

**Comment by ixdy** [comment]
This appears to have started failing after https://github.com/kubernetes/kubernetes/pull/17121 was merged. @mikedanese

**Comment by thockin** [comment]
Ahh, that WOULD make some sense.  my fresh e2e from head is passing though - are we setting up differently?

**Comment by wojtek-t** [comment]
I think that this is cause by https://github.com/kubernetes/kubernetes/pull/17121 - iit's pretty clear from looking into failures after this was merged.

@lavalamp @thockin @mikedanese

**Comment by mikedanese** [comment]
@wojtek-t can we merge the fix before reverting? I think #17588 is enough to fix this

**Comment by lavalamp** [comment]
Just confirming: appears fixed. Thanks @mikedanese, @wojtek-t, and @thockin!

**Comment by wojtek-t** [comment]
@mikedanese - sure; thanks for fixing it
