### ISSUE TITLE
Fedora cockpit attempting to access /api/v1beta3/watch

### ISSUE THREAD

**Issue by tedstirm** [kubernetes/kubernetes#17598]
I am running Kubernetes using the ([Vagrant Installation](http://kubernetes.io/v1.1/docs/getting-started-guides/vagrant.html)) and the Fedora Cockpit(file topology.js around line 829) is trying to access /api/v1beta3/watch which doesn't exist, so this results in constant 404 errors. I have tried the ([Vagrant Installation](http://kubernetes.io/v1.1/docs/getting-started-guides/vagrant.html)) on Release 1.1.2 and 1.2.0-alpha-3. The Fedora Cockpit in Release 1.2.0-alpha-3 was working for me last week, so I am not sure what has changed.

**Comment by mikedanese** [comment]
v1beta3 was removed before the v1.0 release. They need to upgrade to use the new API version. Shouldn't you file this issue in the Fedora Cockpit repository?

cc @stefwalter

**Comment by tedstirm** [comment]
I was unsure if this was due to the repo that the Vagrant provisioning was pulling from or was an issue with Cockpit directly. I have opened a tick with them: https://github.com/cockpit-project/cockpit/issues/3204

**Comment by stefwalter** [comment]
Because kubernetes has moved so quickly, you'll need to use a recent version of Cockpit to interact with kubernetes. In particular Cockpit 0.69 removed support for v1beta3 ... and Cockpit 0.84 is the latest release.

**Comment by tedstirm** [comment]
@stefwalter Thanks for following up.
@mikedanese Should I create a separate issue to address the fact that the Fedora base boxes being used when performing the [Vagrant Installation](http://kubernetes.io/v1.1/docs/getting-started-guides/vagrant.html) are no longer supported by Cockpit?

**Comment by stefwalter** [comment]
>  @mikedanese Should I create a separate issue to address the fact that the Fedora base boxes being used when performing the Vagrant Installation are no longer supported by Cockpit? 

It's not just Cockpit. Fedora 21 is no longer supported. This happened a couple weeks ago, but at some point the Vagrant VM should be updated to something supported.

**Comment by mikedanese** [comment]
We should remove cockpit from the vagrant kube-up for fix it. Shouldn't we deploy cockpit in a pod like the other addons?

**Comment by stefwalter** [comment]
> We should remove cockpit from the vagrant kube-up or fix it. 

The simplest fix would be to move the vagrant kube to Fedora 22. Fedora 21 is EOL. In fact the Fedora infrastructure won't even let us do package builds (in COPR) for Fedora 21 any longer.

You may be able to get a recent Cockpit build with a repo like this, but that would date itself soon anyway:

```
# cat /etc/yum.repos.d/_copr_sgallagh-cockpit-preview.repo 
[sgallagh-cockpit-preview]
name=Copr repo for cockpit-preview owned by sgallagh
baseurl=https://copr-be.cloud.fedoraproject.org/results/sgallagh/cockpit-preview/fedora-$releasever-$basearch/
skip_if_unavailable=True
gpgcheck=0
gpgkey=https://copr-be.cloud.fedoraproject.org/results/sgallagh/cockpit-preview/fedora-$releasever-$basearch/pubkey.gpg
enabled=0
```

> Shouldn't we deploy cockpit in a pod like the other addons?

There are two ways to do this:

 1. Make a full "operating system" container, with some system users (for login) and put cockpit in it. Add a kube config file to point it to the right kubernetes instance.
 2. Upstream we're working on a way to have just the kubernetes Cockpit component in a container with OAuth token authentication and no local system users.

See the following cards. Should land within the next month or so.

 * https://trello.com/c/RzpNoZ6w/235-3-oauth-authentication-in-cockpit-ws
 * https://trello.com/c/basH8cst/236-3-specialized-cockpit-bridge-for-non-local-users

**Comment by stefwalter** [comment]
Hmmm, someone helped me reenable fedora-21 support in our COPR. So you can simply add this repo to Fedora 21 and track the latest builds now. Place this repo in ```/etc/yum.repos.d/cockpit.repo``` and you'll be good to go:

```
[group_cockpit-cockpit-preview]
name=Copr repo for cockpit-preview owned by msuchy
baseurl=https://copr-be.cloud.fedoraproject.org/results/@cockpit/cockpit-preview/fedora-$releasever-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/@cockpit/cockpit-preview/pubkey.gpg
enabled=1
enabled_metadata=1
```

**Comment by mikedanese** [comment]
Upgraded
