### ISSUE TITLE
Broken on soak cluster: Job should run a job to completion when tasks sometimes fail and are not locally restarted

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#17599]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gce/3939/

**Comment by lavalamp** [comment]
...It looks like lots of stuff is broken on the soak cluster. I filed a rollup #17608.

**Comment by dims** [comment]
@lavalamp old flake?

**Comment by lavalamp** [comment]
Yes, obsolete.
