### ISSUE TITLE
Remove custom KUBE_GCS_STAGING_PATH_SUFFIXs in e2e.sh

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#17595]
As far as I can tell, we should just make KUBE_GCS_STAGING_PATH_SUFFIX equivalent to the job name, except for the PR-builder.

Alternatively, we could always make it `"-${JOB_NAME}-${NODE_NAME}-${EXECUTOR_NUMBER}"` or something?

Ran into this in #17539.

**Comment by ixdy** [comment]
This is being covered in #20036, right?

**Comment by ihmccreery** [comment]
Yup; good call.
