### ISSUE TITLE
Remove Autoscaling tests from GCE skip list

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#17596]
Per our email discussion while getting 1.1 out the door.  It looks like this never happened, though, which means we're not running autoscaling tests against GCE on the 1.1 branch, (we were running it on GKE with the 1.1-features job, but I'm removing that job in #17539).

I'd once again like to (strongly) suggest that we mirror test suites running against release branch to jobs running against master, so that we avoid this problem of accidentally not running tests when we think we are.  I'd much rather have a perhaps-unnecessary slow/HPA/whatever suite than continually try to figure out where slow/HPA/whatever tests are running, depending on if I'm looking at release jobs versus jobs running against master.

cc @jlowdermilk @ixdy

**Comment by jlowdermilk** [comment]
+1 We should be running the autoscaling tests in slow or continuous.
