### ISSUE TITLE
Soak cluster is not happy

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#17608]
A very small sampling of recently failed tests:

* Deployment deployment should delete old pods and create new ones
* Downward API should provide pod name and namespace as env vars [Conformance]
* EmptyDir volumes should support (non-root,0666,tmpfs) [Conformance]
* EmptyDir volumes should support (non-root,0777,default) [Conformance]
* Job should run a job to completion when tasks sometimes fail and are not locally restarted
* Kubectl client Kubectl expose should create services for rc [Conformance]
* Kubectl client Update Demo should do a rolling update of a replication controller [Conformance]

**Comment by lavalamp** [comment]
Some more:

* Kubelet experimental resource usage tracking over 30m0s with 50 pods per node.
* KubeletManagedEtcHosts should test kubelet managed /etc/hosts file
* Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host
* Pods should be restarted with a docker exec "cat /tmp/health" liveness probe [Conformance]
* ServiceAccounts should mount an API token into pods [Conformance]

**Comment by mikedanese** [comment]
Not sure what team label to give this

**Comment by quinton-hoole** [comment]
The [kubernetes-soak-continuous-e2e-gce[(http://kubekins.dls.corp.google.com/job/kubernetes-soak-continuous-e2e-gce/) test job ran relatively green for a full week from [build time Dec 8, 2015](http://kubekins.dls.corp.google.com/job/kubernetes-soak-weekly-deploy-gce/) until the following automated rebuild.

Closing this as obsolete.
