### ISSUE TITLE
Support importing containers from docker exported tar file

### ISSUE THREAD

**Issue by rothgar** [kubernetes/kubernetes#17604]
In some situations we would like to use kubernetes without needing a docker registry. We store images on a shared nfs file system by using `docker export -o container.tar some-container`. On docker hosts we then import that image using `docker import` and run the container.

It would be great if kubernetes could also support this so dependency on public internet access to the docker hub and running an internal registry are not required.

cc: @dchen1107

**Comment by mikedanese** [comment]
Is this a duplicate of #15484

**Comment by rothgar** [comment]
Sorry, didn't find that. Will subscribe to that issue.

**Comment by dchen1107** [comment]
This is not the dup of #15484. I think https://github.com/kubernetes/kubernetes/issues/1589 is the one more likely addressing your issue.
