### ISSUE TITLE
Broken on soak cluster: Kubectl client Update Demo should do a rolling update of a replication controller [Conformance]

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#17600]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gce/3939/

**Comment by lavalamp** [comment]
...It looks like lots of stuff is broken on the soak cluster. I filed a rollup #17608.

**Comment by janetkuo** [comment]
It's now 100% stability. Closing it. http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gce/lastCompletedBuild/testReport/(root)/Kubernetes%20e2e%20suite/Kubectl_client_Update_Demo_should_do_a_rolling_update_of_a_replication_controller__Conformance_/
