### ISSUE TITLE
kube-proxy cgroup problem

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/kubernetes#17619]
Hi,

I am keep getting the following errors on CoreOS when starting kube-proxy:

Failed to start in resource-only container "/kube-proxy": open /sys/fs/cgroup/cpu/kube-proxy/cpu.shares: no such file or directory
Not trying iptables proxy: can't get Node "ip-172-31-29-209.eu-central-1.compute.internal": node "ip-172-31-29-209.eu-central-1.compute.internal" not found
Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

Shouldn't the cgroup be kubelet instead of kube-proxy? 

Thanks,
Andrej

**Comment by dalanlan** [comment]
Not positive, but it looks like `kubelet` is trying to put `kube-proxy` into a cgroup, setting up resource limitation.
I guess following is expected by default, 
```
$ cat /sys/fs/cgroup/cpu/kube-proxy/cpu.shares 
1024
```

**Comment by opskumu** [comment]
I also have this problem.

```
11月 22 20:18:55  kube-proxy[32042]: E1122 20:18:55.048793   32042 proxier.go:193] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or directory
11月 22 20:18:55  kube-proxy[32042]: Try `iptables -h' or 'iptables --help' for more information.
11月 22 20:18:55 kube-proxy[32042]: E1122 20:18:55.049928   32042 proxier.go:197] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or directory
11月 22 20:18:55 kube-proxy[32042]: Try `iptables -h' or 'iptables --help' for more information.
# cat /sys/fs/cgroup/cpu/kube-proxy/cpu.shares
1024
```

**Comment by thockin** [comment]
Mike is on it.  #17621

**Comment by mikedanese** [comment]
You should pass `--resource-container="" ` to kube-proxy when yous start your container.

**Comment by dalanlan** [comment]
>You should pass --resource-container="" to kube-proxy when yous start your container.

This is expected only after #17121 was merged, right?

**Comment by mikedanese** [comment]
You should do this before and after #17121 if you are running kube-proxy in a container

**Comment by dalanlan** [comment]
Uhh..That makes sense:) Thanks

**Comment by thockin** [comment]
correct

**Comment by luxas** [comment]
Is it required to pass `--resource-container=""` when running in a container and it is `v1.2`?

**Comment by mikedanese** [comment]
yes

**Comment by luxas** [comment]
Why? I don't even see the flag in http://kubernetes.io/docs/admin/kube-proxy/

**Comment by mikedanese** [comment]
We can't remove the flag or change the default and the default is not "". It's still a flag but is not showing up because it's marked deprecated which is a stupid "feature" of cobra.

**Comment by luxas** [comment]
Ah, got it. But it's quite confusing when cobra doesn't display it. Thanks.

**Comment by thockin** [comment]
Do we consider flags to be part of the API (never removable?) or have we
just not tested the water on actually removing flags after deprecating?

**Comment by jsravn** [comment]
Are there plans to remove `--resource-container`? It took a long time to figure out why I couldn't put kube-proxy into a `runtime.slice` parent container (following advice in https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/). This flag doesn't show up anywhere except the source code.

**Comment by thockin** [comment]
I don't have state on that one, other than that it was deprecated - @dchen1107 or @vishh ?  I know the directional trend is to run kube-proxy as a DaemonSet, so the flag is less likely to be used.

**Comment by whypro** [comment]
Can someone please explain the background of "resource-only container"? Why kube-proxy need it before?
