### ISSUE TITLE
Pods are not scaled up correctly in RC

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#17613]
Using Kubernetes 1.1.2 with Vagrant provider.

Based upon the sample https://github.com/kubernetes/kubernetes/tree/master/examples/javaee, the following pods are running:

```
./cluster/kubectl.sh get po
NAME               READY     STATUS    RESTARTS   AGE
mysql-pod          1/1       Running   0          6m
wildfly-rc-2o8vd   1/1       Running   0          4m
```

Scaled pods as:

```
./cluster/kubectl.sh scale --replicas=2 rc wildfly-rc
replicationcontroller "wildfly-rc" scaled
```

The output shows:

```
./cluster/kubectl.sh get -w po
NAME               READY     STATUS    RESTARTS   AGE
mysql-pod          1/1       Running   0          10m
wildfly-rc-2o8vd   1/1       Running   0          9m
wildfly-rc-omyof   0/1       Pending   0          1m
NAME        READY     STATUS        RESTARTS   AGE
mysql-pod   1/1       Terminating   0          11m
wildfly-rc-2o8vd   1/1       Terminating   0         10m
wildfly-rc-r4t1m   0/1       Pending   0         0s
mysql-pod   1/1       Terminating   0         12m
mysql-pod   1/1       Terminating   0         12m
wildfly-rc-2o8vd   1/1       Terminating   0         11m
wildfly-rc-2o8vd   1/1       Terminating   0         11m
```

Additional pod does not created for 10 mins and then the MySQL pod is terminated as well. Two additional pods are created:

```
./cluster/kubectl.sh get -w po
NAME               READY     STATUS    RESTARTS   AGE
wildfly-rc-omyof   0/1       Pending   0          5m
wildfly-rc-r4t1m   0/1       Pending   0          2m
```

But they stay in pending state. The cluster is confused on what pods need to be created.

**Comment by davidopp** [comment]
Is this reproducible? I assume it used to work?

Can you send the event log (`kubectl get events`)?

**Comment by arun-gupta** [comment]
@davidopp I tried a couple of times and could reproduce only once. Kubernetes cluster has been destroyed and recreated multiple times since then.

Complete instructions are at: https://github.com/javaee-samples/docker-java/blob/master/chapters/docker-kubernetes.adoc#deploy-java-ee-application-multiple-configuration-files

**Comment by kargakis** [comment]
Shouldn't be an issue anymore, please reopen otherwise
