### ISSUE TITLE
--validate switch not supported for delete command

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#17623]
`kubectl.sh --validate=false create -f couchbase-rc.yaml` works fine.

But `kubectl.sh --validate=false delete -f couchbase-rc.yaml` prints the help message.

`--validate` should be supported for both create and delete commands.

**Comment by liggitt** [comment]
Delete doesn't send API content, it just deletes a named resource. What would you expect --validate to do for delete?

**Comment by arun-gupta** [comment]
Delete takes either a named resource or a filename. In case of the file name, I'd expect it to validate  contents of the file. This would be analogous to `create`.

**Comment by liggitt** [comment]
It only extracts the names of the resources in the file. Validation is intended to inform you of invalid API fields, since the API server drops unknown fields. In the case of deletion, none of those fields are used, so validation doesn't make sense.

**Comment by arun-gupta** [comment]
I see that makes sense.
