### ISSUE TITLE
init: kube-controller-manager respawning too fast, stopped

### ISSUE THREAD

**Issue by GuoHui89757** [kubernetes/kubernetes#17630]
On my ubuntu system,when i restart etcd,kube-controller-manager can't start,but kube-apiserver and kube-scheduler can.

when exec "sudo service etcd  restart", /var/log/syslog is:
Nov 23 12:46:39 master kernel: [ 3329.260354] init: kube-scheduler main process (5069) terminated with status 2
Nov 23 12:46:39 master NetworkManager[1251]:    SCPlugin-Ifupdown: devices removed (path: /sys/devices/virtual/net/flannel0, iface: flannel0)
Nov 23 12:46:39 master kernel: [ 3329.270001] init: kube-apiserver main process (5075) terminated with status 2
Nov 23 12:46:39 master kernel: [ 3329.304657] init: etcd main process (5061) killed by TERM signal
Nov 23 12:46:39 master kernel: [ 3329.419258] init: kube-controller-manager main process (5287) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.419281] init: kube-controller-manager main process ended, respawning
Nov 23 12:46:39 master kernel: [ 3329.467544] init: kube-controller-manager main process (5319) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.467568] init: kube-controller-manager main process ended, respawning
Nov 23 12:46:39 master kernel: [ 3329.513979] init: kube-controller-manager main process (5327) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.514002] init: kube-controller-manager main process ended, respawning
Nov 23 12:46:39 master kernel: [ 3329.565336] init: kube-controller-manager main process (5335) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.565359] init: kube-controller-manager main process ended, respawning
Nov 23 12:46:39 master kernel: [ 3329.620381] init: kube-controller-manager main process (5343) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.620407] init: kube-controller-manager main process ended, respawning
Nov 23 12:46:39 master kernel: [ 3329.676403] init: kube-controller-manager main process (5352) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.676426] init: kube-controller-manager main process ended, respawning
Nov 23 12:46:39 master kernel: [ 3329.741289] init: kube-controller-manager main process (5362) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.741317] init: kube-controller-manager main process ended, respawning
Nov 23 12:46:39 master kernel: [ 3329.784632] init: kube-controller-manager main process (5370) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.784654] init: kube-controller-manager main process ended, respawning
Nov 23 12:46:39 master kernel: [ 3329.828753] init: kube-controller-manager main process (5379) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.828774] init: kube-controller-manager main process ended, respawning
Nov 23 12:46:39 master kernel: [ 3329.871007] init: kube-controller-manager main process (5390) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.871028] init: kube-controller-manager main process ended, respawning
Nov 23 12:46:39 master kernel: [ 3329.913214] init: kube-controller-manager main process (5399) terminated with status 255
Nov 23 12:46:39 master kernel: [ 3329.913238] init: kube-controller-manager respawning too fast, stopped

/var/log/upstart/kube-controller-manager.log is:
I1123 12:43:42.251724    5076 plugins.go:71] No cloud provider specified.
I1123 12:43:42.251994    5076 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.252249    5076 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
F1123 12:43:42.253690    5076 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
E1123 12:43:42.255937    5076 resource_quota_controller.go:63] Synchronization error: Get http://127.0.0.1:8080/api/v1/resourcequotas: dial tcp 127.0.0.1:8080: connection refused (&url.Error{Op:"Get", URL:"http://127.0.0.1:8080/api/v1/resourcequotas", Err:(*net.OpError)(0xc20819ce00)})
E1123 12:43:42.256849    5076 nodecontroller.go:203] Error monitoring node status: Get http://127.0.0.1:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: connection refused
I1123 12:43:42.346470    5113 plugins.go:71] No cloud provider specified.
I1123 12:43:42.346714    5113 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.346964    5113 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
E1123 12:43:42.350560    5113 nodecontroller.go:203] Error monitoring node status: Get http://127.0.0.1:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: connection refused
E1123 12:43:42.350718    5113 resource_quota_controller.go:63] Synchronization error: Get http://127.0.0.1:8080/api/v1/resourcequotas: dial tcp 127.0.0.1:8080: connection refused (&url.Error{Op:"Get", URL:"http://127.0.0.1:8080/api/v1/resourcequotas", Err:(*net.OpError)(0xc2081a2140)})
F1123 12:43:42.351126    5113 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
I1123 12:43:42.391584    5121 plugins.go:71] No cloud provider specified.
I1123 12:43:42.391763    5121 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.391945    5121 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
F1123 12:43:42.397654    5121 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
I1123 12:43:42.444589    5129 plugins.go:71] No cloud provider specified.
I1123 12:43:42.444777    5129 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.444967    5129 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
F1123 12:43:42.448099    5129 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
I1123 12:43:42.499143    5138 plugins.go:71] No cloud provider specified.
I1123 12:43:42.499618    5138 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.500146    5138 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
F1123 12:43:42.506149    5138 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
I1123 12:43:42.555659    5146 plugins.go:71] No cloud provider specified.
I1123 12:43:42.560562    5146 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.562737    5146 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
F1123 12:43:42.564011    5146 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
E1123 12:43:42.564320    5146 resource_quota_controller.go:63] Synchronization error: Get http://127.0.0.1:8080/api/v1/resourcequotas: dial tcp 127.0.0.1:8080: connection refused (&url.Error{Op:"Get", URL:"http://127.0.0.1:8080/api/v1/resourcequotas", Err:(*net.OpError)(0xc2081ce200)})
E1123 12:43:42.564632    5146 nodecontroller.go:203] Error monitoring node status: Get http://127.0.0.1:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: connection refused
I1123 12:43:42.617778    5156 plugins.go:71] No cloud provider specified.
I1123 12:43:42.618287    5156 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.620948    5156 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
F1123 12:43:42.622052    5156 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
I1123 12:43:42.663392    5164 plugins.go:71] No cloud provider specified.
I1123 12:43:42.663563    5164 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.663774    5164 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
F1123 12:43:42.667397    5164 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
I1123 12:43:42.711991    5172 plugins.go:71] No cloud provider specified.
I1123 12:43:42.712322    5172 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.712600    5172 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
F1123 12:43:42.713286    5172 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
E1123 12:43:42.713479    5172 resource_quota_controller.go:63] Synchronization error: Get http://127.0.0.1:8080/api/v1/resourcequotas: dial tcp 127.0.0.1:8080: connection refused (&url.Error{Op:"Get", URL:"http://127.0.0.1:8080/api/v1/resourcequotas", Err:(*net.OpError)(0xc2081e2b80)})
E1123 12:43:42.714776    5172 nodecontroller.go:203] Error monitoring node status: Get http://127.0.0.1:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: connection refused
I1123 12:43:42.756896    5180 plugins.go:71] No cloud provider specified.
I1123 12:43:42.757361    5180 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.759255    5180 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
E1123 12:43:42.760071    5180 nodecontroller.go:203] Error monitoring node status: Get http://127.0.0.1:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: connection refused
F1123 12:43:42.761135    5180 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
I1123 12:43:42.806013    5189 plugins.go:71] No cloud provider specified.
I1123 12:43:42.807843    5189 nodecontroller.go:133] Sending events to api server.
E1123 12:43:42.808042    5189 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
E1123 12:43:42.809594    5189 nodecontroller.go:203] Error monitoring node status: Get http://127.0.0.1:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: connection refused
F1123 12:43:42.809695    5189 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused

**Comment by ddysher** [comment]
Which version?  This is a known issue in version 1.1, and was fixed in 1.1.2.  https://github.com/kubernetes/kubernetes/pull/17110

**Comment by GuoHui89757** [comment]
@ddysher version 1.1, i will try 1.1.2

**Comment by mikedanese** [comment]
Thisshould be fixed. Please reopen if it is not
