### ISSUE TITLE
Proposal: Authorizing use of a PodSecurityPolicy via the "Use" verb

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#17637]
## Summary of proposal
- a pod has a pointer to a serviceAccount.  (this is currently the case)
- a user must be authorized to **use** a serviceAccount in order to create a pod that has that serviceAccountName. (proposed new check)
- a user must be authorized to **use** a podSecurityPolicy in order to create a serviceAccount that points to that podSecurityPolicy. (proposed new check)
- a serviceAccount has a pointer to a PodSecurityPolicy  (proposed new field)
- a pod's PodSecurityContext and each of its container's SecurityContext must match the Pod's serviceAccount's PodSecurityPolicy. (proposed new check)
## Longer Version
- (prerequisite) @deads2k's proposal #12209 is implemented, in particular so that:
  - the Authorization interface knows the specific verb (e.g."create" or "logs") used.
  - the Authorization interface knows the name and namespace of the referenced object.
- (prerequisite) @pweil-'s proposal #7893 for PodSecurityPolicy is merged, except the `User` and `Groups` fields are dropped from it.
- (new thing) "serviceAccount" gets a new verb called "use".  The endpoint does not do anything, it is just for authorization purposes.
- (new thing) when a pod is created or updated by user U, and the pod has a serviceAccount S, then, in addition to our existing authorization checks, there is a new, second, authorization check that checks whether user U is allowed to "use" serviceAccount S.
  this check happens after an empty ServiceAccount is defaulted to "default".
- (new thing) serviceAccounts gain an objectReference to a PodSecurityPolicy.  
  (new thing) an admission controller enforces that a pod's securityContext(s) and podSecurityContext must match the podSecurityPolicy of its serviceAccount.
### Pod Creation Detailed Steps
1. request authenticated
2. modify authenticated user using "acting-as", if requested, for e.g. controller managers (see #16933, not strictly needed for this proposal but included to show all steps in eventual system)
3. check whether authenticated user U (in groups G) is allowed to create pods, in the general case, via `authorizer.Authorize(user=U, groups=G, verb="create", kind="pods", namespace=N, …)`
4. LimitRanger admission controller runs (per #17097, this may someday set security-sensitive fields, hence we ought to re-authorize after defaulting)
5. SecurityContextDeny plugin no longer used
6. ServiceAccount plugin may set default serviceAccount
7. Note: this marks the end of "mutating" admission controllers.  All further admission controllers are not allowed to modify the object from the request body.  Since the object is in its final form, the next step(s) can do final authorization of the object.
8. New UseServiceAccount admission controller checks whether authenticated user U (in groups G) is allowed to use the pod's service account S, via  `authorizer.Authorize(user=U, groups=G, verb="use", kind="serviceAccount", objectName=S, ...)` 
9. New PodSecurityPolicyCheck plugin compares the pod's securityContext(s) and podSecurityContext with the pod's serviceAccount's podSecurityPolicy, and rejects if not matching
10. DenyEscalatingExec is not needed anymore, since it is covered by UseServiceAccount check.
11. Quota admission controller runs.
### The "UseServiceAccount" admission controller
- for "create", "update", "exec", and "attach" verbs, it checks that the requesting user is authorized to "use" the serviceAccount of the Pod in question.
- for "logs", it does not make this check.  reasoning here is that sensitivity of logs (PII or not) is somewhat independent of the privileges of the pod that is doing the logging.   So, don't require the check. 
- for "portforward", "proxy" verbs: TBD
- for "status" verb, no check.
##### Use case 1

As an administrator, I can create a namespace for a person that can't create privileged containers AND enforces that the UID of the containers is set to a certain value

steps to implement use case:
- create namespace N1
- create PodSecurityPolicy P1 specifying desired UID.
- create service account S1 in N1, pointing to P1.
- allow user U1 to "do anything to pods in N1" and to "use S1".
##### Use case 2:

As a cluster operator, an infrastructure component should be able to create a pod with elevated
privileges in a namespace N where regular users cannot create pods with these privileges or execute
commands in that pod.

steps to implement use case:
- create totally permissive PodSecurityPolicy P2 which can create privileged pods.
- create special purpose service account S2 which references P2
- give cluster operator user U2 permission to use S2
- do not give any other users permission to use S2.  Create S2 in a namespace other than N2 if needed.
- U2 creates Pod with service account S2, and any security context desired.

Note that the cluster admin can (1) make a powerful service account and make a pod using that account or (2) make a pod that runs as any existing service account, with that service accounts limitations, but the cluster admin cannot make a powerful pod that runs as an existing weak service account.  This is the same as Unix.  Root is powerful when running as root, and can su to any other user, but it not powerful when su'ed to a weak user.
#### Reasons I like this approach
- We will need to add code that checks whether a user can read a secret before allowing creation of a pod that mounts it.  The pattern for that will be quite similar to this.  If we do  #7893 as proposed, then we end up with two quite different patterns.
- It will be easier to teach an existing outside-of-kubernetes authorization system that something called a "serviceAccount" has a "use" verb, than it will be to teach it about the exact format of a PSP object and its users and groups fields.
- Keeps users and groups (which belong to "object-level authorization") separate from  field-level authorization (see #17549).  
- The "use" verb idea is very similar to the "acting-as" header proposed in #16933 to avoid confused deputy problem.
- By putting a reference to PodSecurityPolicy into a serviceAccount, it allows you to know the maximum set of things that a serviceAccount can do from inspecting just that serviceAccount object.  Otherwise, you can have a privileged pod run by a serviceAccount that you don't expect to be privileged.
- Once the pod's service account has been determined, further policy checks need not make any reference to users or groups.  This should simplify pod policy.
- Rather than needing to check all the PSPs a user has access to, the correct PSP is known from the pod's SA.

TODO:
figure out how this would work with network policy.

**Comment by erictune** [comment]
@mikedanese @pweil- @smarterclayton @deads2k @liggitt

**Comment by deads2k** [comment]
My only concern with the approach is trying to describe a case where a user is allowed to use `PodSecurityPolicy`, but only on a particular node.  That sort of permission scoping seems to make sense since the pod permissions grant power on a node, not in a namespace.  It would allow me to have a single "dangerous" node.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/33080 added PodSecurityPolicy authorization based on a `use` verb authorizer check

**Comment by smarterclayton** [comment]
This can be closed?

**Comment by liggitt** [comment]
there's a lot else here, just noting the bit of progress made

**Comment by liggitt** [comment]
PodSecurityPolicy authorization via the `use` verb is in place now (documented at https://kubernetes.io/docs/concepts/policy/pod-security-policy/#authorizing-policies and active in CI with e2e tests)

Authorization for a specific user to use a specific service account would be a significant separate effort (and would require plumbing originating user info through all controlling objects, e.g. deployment->replicaset->pod)
