### ISSUE TITLE
Rename controller

### ISSUE THREAD

**Issue by zhengguoyong** [kubernetes/kubernetes#17648]
controller(https://github.com/kubernetes/kubernetes/tree/master/pkg/registry/controller) here means replication controller, i think it is better to rename it.
If no body reject it, i will make a change PR.

**Comment by davidopp** [comment]
@lavalamp

**Comment by lavalamp** [comment]
Yes, we may rename it again to "replicaset" but if you want to rename it in the mean time to "replicationcontroller" that's fine by me.

**Comment by oscerd** [comment]
Is this still needed?

**Comment by ReneSaenz** [comment]
Can I help with this? I am new to Kubernetes and I would like to contribute and get my feet wet

**Comment by kargakis** [comment]
@ReneSaenz sure, it's a simple package renaming so it should be pretty straightforward to take a stab at.

**Comment by oscerd** [comment]
I was interested too. By the way no problem

**Comment by ReneSaenz** [comment]
Can somebody point me in the right direction?  I am confused. I cannot find controller here
https://github.com/kubernetes/kubernetes/tree/master/pkg/registry

The controller I found is here
https://github.com/kubernetes/kubernetes/tree/master/pkg/controller

**Comment by kargakis** [comment]
@oscerd sorry about that, there are other onboarding issues you can have a look at:
https://github.com/kubernetes/kubernetes/labels/help-wanted

@ReneSaenz the respective registry package for RCs can be found below:

**Comment by ReneSaenz** [comment]
Picking up this issue. Thank you @kargakis

**Comment by ReneSaenz** [comment]
@lavalamp I am going to work on this issue and going to rename it to "replicationcontroller"

**Comment by lavalamp** [comment]
SGTM

**Comment by ReneSaenz** [comment]
@lavalamp I am done with my changes. Would you mind reviewing them before I submit the PR.

https://github.com/kubernetes/kubernetes/compare/master...ReneSaenz:rename-controller-17648?expand=1

**Comment by ReneSaenz** [comment]
@kargakis I am trying to email you directly and it bounces back. I am trying the email that is in your GitHub profile. Could you please email me so I can discuss with you?

**Comment by kargakis** [comment]
The email in my github account works fine - others are using it daily to
contact me. I guess it is related to your PR so I would expect Github to be
the best place to discuss :)

**Comment by ncdc** [comment]
#40393 took care of this, closing
