### ISSUE TITLE
Annoying "kube-proxy"-related logs

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#17646]
There are thousands of line in some of our tests like this:

01:10:24 Nov 23 01:10:24.778: INFO: Missing info/stats for container "/kube-proxy" on node "e2e-slow-minion-32dk"

@mikedanese @thockin

**Comment by mikedanese** [comment]
Fixed by #17621

**Comment by wojtek-t** [comment]
Awesome - thanks @mikedanese
