### ISSUE TITLE
I cannot start node2 container on glusterfs

### ISSUE THREAD

**Issue by kk580kk** [kubernetes/kubernetes#17645]
I have follow this guide http://kubernetes.io/v1.1/examples/glusterfs/ and create a glusterfs cluster on 2 compuiers. 
On the node1, its ok ,no issue.
Bug on the node2, I got a error like this

```
➜  ~  kubectl logs wordpress-controller-jvnij   
warning: both WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP found
  Connecting to WORDPRESS_DB_HOST (10.254.18.220)
  instead of the linked mysql container
sed: couldn't open temporary file ./sedFEDbAR: Permission denied
```

and I try to fix it by  mount | grep kube_vol and go into the dir.
I found the privillage is same with node1. and I can execute `mkdir` commend.
Even I execute  `chmod 777 dir` ,can't fix this problems.

Is therr something wrong.

**Comment by kk580kk** [comment]
I fix this problem by edit
```vim /etc/sysconfig/docker```
and remove ```--selinux-enabled```

**Comment by bgrant0607** [comment]
cc @kubernetes/goog-cluster

**Comment by bgrant0607** [comment]
cc @kubernetes/rh-storage

**Comment by rootfs** [comment]
This looks another selinux related issue. Have you set securitycontext in the Pod? 
cc @swagiaal

**Comment by pmorie** [comment]
Fairly certain this is #20813.'

@kk580kk can you post the output of `ls -ldZ /var/lib/kubelet` on the node where this is happening?

**Comment by kk580kk** [comment]
This is a problem from selinux, I thounght.
And I have already fixed by change selinux setting.
