### ISSUE TITLE
Ingress support different namespaces

### ISSUE THREAD

**Issue by owenhaynes** [kubernetes/kubernetes#17642]
Would be nice if the ingress could work with services in other namespaces, as we currently use namespaces to overcome restrictions of the service name length and only require one load balancer nginx to access theses services.

so something like the following:
```json
{
  "apiVersion": "extensions/v1beta1",
  "kind": "Ingress",
  "metadata": {
    "name": "test-ingress"
  },
  "spec": {
    "rules": [{
      "http": {
        "paths": [
          {
            "path": "/test",
            "backend": {
              "namespace": "group-one",
              "serviceName": "app1",
              "servicePort": "80"
            }
          }
        ]
      }
    }]
  }
}
```
to gain something like
test.com/group-one/app1/

**Comment by mikedanese** [comment]
> overcome restrictions of the service name length

Why do you need such long names?

**Comment by owenhaynes** [comment]
We launch the same service set for different organisation groups each
configured with different environments depending on the organisation.

Frontend-example-org

So we can not included the organisation in the name of the service as it
would make the service to long. So we move the organisation to the
namespace level which makes it cleaner and helps avoid the restriction.

We could of used labels but we would then have to generate random unique
names for the services to avoid clashes.

Namespaces also allow us to keep the services organised and all of there
components, and help with other restrictions later on

**Comment by bprashanth** [comment]
Lets continue discussion on https://github.com/kubernetes/kubernetes/issues/17088
