### ISSUE TITLE
AWS elb creation fails when vpc not tagged

### ISSUE THREAD

**Issue by jtblin** [kubernetes/kubernetes#17647]
Getting the following error when creating a service with type `LoadBalancer` when kubernetes has been deployed without tagging the vpc/node.

> Error when service created first time:
creating loadbalancer failed failed to create external load balancer for service default/service_name: error tagging security group: InvalidParameterValue: Value ( '' ) for parameter Tag key is invalid. Tag key cannot be null or empty. status code: 400, request id: []

This prevents from using ELBs with the AWS cloud provider when deploying kubernetes in an existing vpc (which cannot be tagged because they already have).

**Comment by peterbourgon** [comment]
I also experienced this failure when trying to provision Kubernetes on AWS with kube-up and specifying an explicit, existing VPC_ID — which wasn't tagged, but then I didn't know that was required :)

**Comment by bprashanth** [comment]
@jtblin I see we have a pr, can we also update the docs in time for 1.2.0?

**Comment by jtblin** [comment]
@bprashanth sure, what do you want me to update in the docs exactly?
