### ISSUE TITLE
e2e flake: "PrivilegedPod should test privileged pod"

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#17644]
Test failed with the following error:

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/privileged.go:68 Expected error: <*errors.errorString | 0xc208509700>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce-parallel/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.78.129 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel/workspace/.kube/config exec --namespace=e2e-tests-e2e-privilegedpod-lviv7 hostexec -- /bin/sh -c curl -q 'http://10.245.1.19:8080/shell?shellCommand=ip+link+add+dummy1+type+dummy'] [] error: pod hostexec is not running and cannot execute commands; current phase is Pending\n [] 0xc2085241c0 exit status 1 true [0xc208418828 0xc208418848 0xc208418868] [0xc208418828 0xc208418848 0xc208418868] [0xc208418840 0xc208418860] [0x7f0740 0x7f0740] 0xc208340c60}:\nCommand stdout:\n\nstderr:\nerror: pod hostexec is not running and cannot execute commands; current phase is Pending\n\n", } Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce-parallel/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.78.129 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-parallel/workspace/.kube/config exec --namespace=e2e-tests-e2e-privilegedpod-lviv7 hostexec -- /bin/sh -c curl -q 'http://10.245.1.19:8080/shell?shellCommand=ip+link+add+dummy1+type+dummy'] [] error: pod hostexec is not running and cannot execute commands; current phase is Pending [] 0xc2085241c0 exit status 1 true [0xc208418828 0xc208418848 0xc208418868] [0xc208418828 0xc208418848 0xc208418868] [0xc208418840 0xc208418860] [0x7f0740 0x7f0740] 0xc208340c60}: Command stdout: stderr: error: pod hostexec is not running and cannot execute commands; current phase is Pending not to have occurred

@liggitt

**Comment by wojtek-t** [comment]
The example failure is here:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/11784/

**Comment by wojtek-t** [comment]
This happened again - increasing priority to P0 according to the policy we discussed:

The failure is here:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/17579/

**Comment by wojtek-t** [comment]
@k8s-oncall FYI

**Comment by wojtek-t** [comment]
Yet another example:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/17479/

**Comment by liggitt** [comment]
Can you point to the publicly visible artifacts for those tests? It's not obvious to me from the description why I was @ mentioned

**Comment by wojtek-t** [comment]
@liggitt - I though that you were involved in this test - if not, please ignore that I mentioned you

**Comment by wojtek-t** [comment]
@kubernetes/goog-testing

**Comment by krousey** [comment]
Another:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/11811/

**Comment by ixdy** [comment]
I think @sttts is the right person to tag.

**Comment by ixdy** [comment]
It looks like the test doesn't wait for the hostexec pod to start running: https://github.com/kubernetes/kubernetes/blob/1a57cc8033158b1b703e2f80f88eef85962aa8c7/test/e2e/privileged.go#L55-L58

**Comment by ixdy** [comment]
Easy fix, I'll take it.

**Comment by ixdy** [comment]
#17690

**Comment by sttts** [comment]
Thanks Jeff.
