### ISSUE TITLE
Document the list format of $KUBECONFIG

### ISSUE THREAD

**Issue by orfjackal** [kubernetes/kubernetes#17658]
In http://kubernetes.io/v1.1/docs/user-guide/kubeconfig-file.html it says:

> Else, if EnvVarLocation (the value of $KUBECONFIG) is available, use it as a list of files that should be merged.

But the documentation does not say that how to define a "list of files". The first things that came to my mind were to separate the filenames by space or newline (as is common in bash), but only after reading the source code did I find out that they need to be separated by a colon (or probably semicolon on Windows).

The documentation should say that what character to use as a separator. Preferably also give an example usage.

Also, the documentation should not say "EnvVarLocation", because documentation should be understandable without reading the source code, and even the source code doesn't anymore use that variable name.

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
@orfjackal would you be up for contributing a patch to https://kubernetes.io/docs/tasks/access-application-cluster/authenticate-across-clusters-kubeconfig/ ?

**Comment by steveperry-53** [comment]
@ahmetb, @orfjackal, I'm working on the docs for this in https://github.com/kubernetes/kubernetes.github.io/pull/4439.
