### ISSUE TITLE
pods can not be deleted thoroughly with e2e density test

### ISSUE THREAD

**Issue by magicwang-cn** [kubernetes/kubernetes#17659]
I just run the density test, when reach the 50 pods per node or 100 pods per node, the test always failed with cleaning operation(delete rc, delelte namespace .etc) 
even more, even if the namespace is deleted,  pods  also will be created in the namespace.
i have delete everything related to this namespace in the etcd(use etcdctl), the result is the same.  :(

anyone else can help me?

**Comment by w00204372** [comment]
what's more, serviceaccounts, secrets and pods in etcd will not be deleted thoroughly, the parent dir always exist(registry/secrets/e2e-tests-density-y86cu, registry/pods/e2e-tests-density-y86cu and registry/serviceaccounts/e2e-tests-density-y86cu)

**Comment by w00204372** [comment]
@kubernetes/goog-testing

**Comment by kargakis** [comment]
@kubernetes/sig-scalability-misc
