### ISSUE TITLE
Using flocker, create flocker-pod.yml fail. Env variable(FLOCKER_CONTROL_SERVICE_HOST) is set, but not effective

### ISSUE THREAD

**Issue by ttllyy** [kubernetes/kubernetes#17651]
k8s version: 1.1.1 or 1.1.2 (Bare-metal Ubuntu Nodes)
flocker version: 1.7.1
I am already install and config flocker. But I don't install Powrstrip. 

I have set related env variables on all nodes.
export FLOCKER_CONTROL_SERVICE_HOST=10.x.x.x
export FLOCKER_CONTROL_SERVICE_PORT=4523
export FLOCKER_CONTROL_SERVICE_CA_FILE=/etc/flocker/cluster.crt
export FLOCKER_CONTROL_SERVICE_CLIENT_KEY_FILE=/etc/flocker/plugin.key
export FLOCKER_CONTROL_SERVICE_CLIENT_CERT_FILE=/etc/flocker/plugin.crt

Create flocker-pod.yml (kubernetes/examples/flocker/flocker-pod.yml) fail. 
kubectl describe pods flocker-web-j1pld  
Error syncing pod, skipping: Get https://localhost:4523/v1/configuration/datasets: x509: certificate is valid for control-service, my-hostname, not localhost

######################################
pkg/volume/flocker/plugin.go

func (b flockerBuilder) newFlockerClient() (*flockerclient.Client, error) {
	host := getenvOrFallback("FLOCKER_CONTROL_SERVICE_HOST", defaultHost)
	portConfig := getenvOrFallback("FLOCKER_CONTROL_SERVICE_PORT", strconv.Itoa(defaultPort))
	
	......
}
######################################

Related variables have come into effect. Why create flocker-pod fail?

**Comment by ttllyy** [comment]
flocker version: 1.7.1

**Comment by ttllyy** [comment]
@krousey 
I reset k8s and flocker, and try many times fail.

**Comment by Stephenitis** [comment]
hey @ttllyy can you run $ flocker-diagnostics this will create a .tar file of logsand email to support@clusterhq.com

**Comment by ttllyy** [comment]
@Stephenitis
In flocker-go client:
// NewClient creates a wrapper over http.Client to communicate with the flocker control service.
func NewClient(host string, port int, clientIP string, caCertPath, keyPath, certPath string) (*Client, error) {
	client, err := newTLSClient(caCertPath, keyPath, certPath)
	if err != nil {
		return nil, err
	}

	return &Client{
		Client:      client,
		schema:      "https",
		host:        host,
		port:        port,
		version:     "v1",
		maximumSize: defaultVolumeSize,
		clientIP:    clientIP,
	}, nil
}

Host variable is define by pkg/volume/flocker/plugin.go(get env).

**Comment by mattbates** [comment]
Hi @ttllyy

If you're running the kubelet as a service (?) then you'll need to ensure the env variables are set somewhere appropriate. For example, /etc/default/kubelet (best practice afaik) or the init script itself. 

Hopefully this will do the trick. Let us know how you get on. 

[ps: we'll take it as an action to update the docs with this clearer advice]

**Comment by ttllyy** [comment]
@mattbates  thanks!   I set env in /etc/init/xxx.conf, the problem has been solved.
