### ISSUE TITLE
Node-level authentication to a private registry is broken

### ISSUE THREAD

**Issue by peterbourgon** [kubernetes/kubernetes#17657]
I have deployed Kubernetes onto AWS using kube-up. I am trying to start a replication controller with a container spec of a Docker image pulled from a private registry (Quay). I am reading [this guide](http://kubernetes.io/v1.1/docs/user-guide/images.html#using-a-private-registry) for instructions. I would like to use the method "Configuring Nodes to Authenticate to a Private Registry". As far as I can tell, this method is broken.

First, I placed my dockercfg on the minion at /root/.dockercfg, as specified. Logging on to the minion, I can manually `docker pull` the image successfully. But the kubelet attempts to pull it without credentials:

```
Failed to pull image "quay.io/foo/bar:baz": image pull failed for quay.io/foo/bar:baz, 
this may be because there are no credentials on this request.  details: (Error: Status 
403 trying to pull repository foo/bar: "{\"error\": \"Permission Denied\"}")
```

Increasing kubelet --v to 4, I see that it's looking for the file in the wrong location(s) at startup:

```
Nov 23 10:37:34 ... config.go:85] looking for .docker/config.json at /var/lib/kubelet/config.json
Nov 23 10:37:34 ... config.go:85] looking for .docker/config.json at /config.json
Nov 23 10:37:34 ... config.go:85] looking for .docker/config.json at /.docker/config.json
Nov 23 10:37:34 ... config.go:85] looking for .docker/config.json at /.docker/config.json
```

Digging into the code, there appear to be a couple of subtle reasons this could be broken. 
- The [kubelet sets the credentialprovider's PreferredDockercfgPath to /var/lib/kubelet](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L520), which I don't think is correct. Perhaps different modules have different understanding of what "Root" means?
- Based on the log output of the kubelet, it looks like [when it runs through a list of paths to check](https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/config.go#L78), the [homeDirPath](https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/config.go#L55) (via [homeJsonPath](https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/config.go#L57)) may not be getting initialized correctly.
- Maybe other problems, too.

I copied the dockercfg to one of the paths the code was looking at, and it then claimed to load the file, logging "Registering credential provider: .dockercfg". But, whenever I created the replication controller, it still tried to pull the image without any credentials. Specifically, [this code path](https://github.com/kubernetes/kubernetes/blob/4cb0beeefdabebd9bfb8fa6771da4633d1fac7bd/pkg/kubelet/dockertools/docker.go#L158). I tried digging around in there for awhile, but I couldn't easily determine why that was happening.

In the end, I used the "Specifying ImagePullSecrets on a Pod" method of using a private registry, which worked.

(Thanks to @2opremio and @geoah for help debugging this issue.)

**Comment by geoah** [comment]
I'm also interested in this but would also appreciate a more generic way to do this on all nodes without having to touch them. eg. A secret of `type: kubernetes.io/dockercfg` and a special flag that would be used for pulling all pos/rcs?

**Comment by mikedanese** [comment]
@geoah see image pull secrets. https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/images.md#specifying-imagepullsecrets-on-a-pod

**Comment by geoah** [comment]
@mikedanese yeah this is the way I'm currently doing it but I'd prefer something that I don't have to specify this on every po/rc that's why the flag proposal for something like a "defaultImagePullSecret: true"

**Comment by gopinatht** [comment]
+1 on the importance of this bug. It looks like the only way around this (apart from the secrets approach) is to place config.json in the root folder. i.e., /config.json. It looks like kubelet is not looking in $HOME/.docker

**Comment by naphthalene** [comment]
I'm running into this (or a similar issue). Basically when declaring a pod with an `imagePullSecrets` `spec` option it works great, however if I try to create a `ReplicationController` --> `spec` --> `template` --> `spec` --> `imagePullSecrets` it is not getting picked up.

**Comment by drewr** [comment]
I'm not sure if I'm having exactly this issue, but I definitely cannot pull images from our private registry.  I've set up image pull secrets.  GCE doesn't send any credentials with the request.  I've verified this in our actual logs.

Here is an authenticated request from the docker command line:

 ```
16:54:07.769209       1 server.go:287] New token for {drewr:***@9.8.84.198 [{reposito
ry infra/tileprox [pull]}]}: {"iss":"registry-token-issuer","sub":"drewr","aud":"token-service
","exp":1479748147,"nbf":1479747237,"iat":1479747247,"jti":"5989781821287605163","access":[{"t
ype":"repository","name":"infra/tileprox","actions":["pull"]}]}
```

Here is the request from GCE.  It doesn't include a username.

```
17:11:51.299819       1 server.go:287] New token for {:@104.196.220.132 [{repository inf
ra/tileprox [pull]}]}: {"iss":"registry-token-issuer","sub":"","aud":"token-service","exp":147
9749211,"nbf":1479748301,"iat":1479748311,"jti":"2967927034164828378","access":[{"type":"repos
itory","name":"infra/tileprox","actions":[]}]}
```

Is this a bug, or am I doing something wrong?  Is hosted Kubernetes close enough to OSS Kubernetes that this is even the place to report this?

**Comment by gtaylor** [comment]
We just ran into this as well. Feels dirty sticking a /.docker/config.json in, but that appears to have worked. We can't pre-populate /var/lib/kubelet, since kubeadm freaks out of there are files already in that dir.

**Comment by HcgRandon** [comment]
Absolutely agree with @geoah this is something that should be handled by k8s.

I think a new resource should be created called 'registries'
so simply `kubectl create registry --server custom.docker.registry.tld --username foo --password bar`

and then anytime an image on `custom.docker.registry.tld` is seen k8s will simply use the username and password to authenticate

If you are looking for someone that has implemented this well check out rancher. as their solution to private registries is effortless. In k8s it is a massive hassle using imagePullSecrets
