### ISSUE TITLE
bare meta Ubuntu getting started guide refers to extinct build.sh

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#17666]
http://kubernetes.io/v1.1/docs/getting-started-guides/ubuntu.html#download-binaries says to run kubernetes/cluster/ubuntu/build.sh --- but there is no longer any such script.

**Comment by MikeSpreitzer** [comment]
Commit b836f0cf8591a8baeeab3c4f669f10a5c031f72a renamed it to download-release.sh.  The doc needs to be updated.

**Comment by dalanlan** [comment]
I'm not sure which branch the link locates, yet it won't suffer from HEAD. 
Ref https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

**Comment by dalanlan** [comment]
May expect cherry pick.

**Comment by MikeSpreitzer** [comment]
This has already been fixed.
