### ISSUE TITLE
cluster/gce/util.sh doesn't handle long firewall rule names properly

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#17665]
Discovered in #17539, if Jenkins job names are too long, logic in `cluster/` ungracefully fails on not being able to create firewall rules because they're too long.

**Comment by jlowdermilk** [comment]
Actually, I think the firewall rule names are derived from `E2E_NETWORK` not the job name. The jobs that were broken by #17539 had the network name changed, and e.g. upgrade tests kept the same network name and didn't break.

**Comment by ihmccreery** [comment]
They key off of `NETWORK`, `MASTER_NAME`, `MINION_TAG`, and `INSTANCE_PREFIX`, depending on what rule you're creating.  Specifically, creating the rule `"${MINION_TAG}-${INSTANCE_PREFIX}-nodeports"` seems to be the issue, (that's a pretty long name, generating things like `e2e-gce-current-release-minion-e2e-gce-current-release-nodeports`.

**Comment by ihmccreery** [comment]
This blocks #17682.
