### ISSUE TITLE
Add credential support to gitRepo volume plugin to pull private git repositories

### ISSUE THREAD

**Issue by ultimateboy** [kubernetes/kubernetes#17676]
Currently, the gitRepo volume plugin only supports pulling from a public repository. Support should be added for specifying credentials via a kube secret so that kube can correctly authenticate and pull private code repositories.

**Comment by brendandburns** [comment]
Yes please... fastest way is to code up a PR to make this happen.  Otherwise, it might take a little while...

**Comment by huggsboson** [comment]
Seems like the current train of thought is to use sidecars to do git checkouts, this would more than likely include support for credentials: #15421

I actually hacked together the go code for the change and it got pretty hairy.  You need to do an ssh-keyscan and other host modifying things that make the sidecar look pretty attractive.  I was going to look at the git-sync side car and see if I could get credential support into that.

The only other thing that is nice about volumes that are missing in side-cars is the ability to sequence containers relative to each other.  I assume I'll have to make that work through the use of "ready" files and containers not starting if the ready file isn't there.

**Comment by bgrant0607** [comment]
See also #16247

**Comment by thockin** [comment]
I really don't want to make the built-in gitRepo more fancy, I think the
sidecar really is the right way to do things.

**Comment by bgrant0607** [comment]
See #831

**Comment by evmin** [comment]
I'd be keen on getting this feature - there is a requirement for us not to have anything in the open, yet JIT deployment would cut the number of the images tenfold (custom batch processing).

Basic auth in the form "https://username:password@bitbucket.com" does not work with kubernetes (Erro 128). And I would prefer read only deployment key anyway.

In short: +1 here

**Comment by resouer** [comment]
I once mean to fix this but you know ... this will makes gitRepo more complicated

**Comment by evmin** [comment]
Indeed, it does add a degree of sophistication. 

Yet it makes the life a lot easier in situations where the implementation pattern is to have a docker image for the software engine only, and to source the interpreted code at the deployment.

Please correct me if I am missing something, yet I do not see how a sidecar could work for such scenario  - I am under impression that there is no way to define the startup order for the containers within a pod?

P.S. Also, I figured out how to pass on credentials AS-IS. Yet it would be great to be able to source them from a secret.

**Comment by resouer** [comment]
May I ask what's your work around for now?

Containers in Pod dose not guaranteed of order, so I suggest you to use lifecycle:
```
lifecycle:
      postStart:
```
to "check & wait" the condition is ready and then run real container CMD.

**Comment by evmin** [comment]
The workaround is simple - I think I might have made a mistake when defined the auth parameters the first time.

Now I am using:
          repository: "https://user:password@bitbucket.org/team/repo.git"

And it works.

The hook idea is great - I will play with it.
I am a bit concerned though with the following (quoting the doco):

> PostStart
>This hook is sent immediately after a container is created.  It notifies the container that it has been created.  No parameters are passed to the handler. It is NOT guaranteed that the hook will execute before the container entrypoint.

Myself I still prefer how it is right now - gitRepo.
Only if there was a way to source the credentials through environment.

How hard would it be to include parsing environment variables in gitRepo string? Then I could just reference them:
          repository: "https://${USER}:${PASSWORD}@bitbucket.org/team/repo.git"

**Comment by huggsboson** [comment]
@evmin you can make it so that the two containers coordinate to produce the desired "ordering".  The two ways I know of doing this:
1. Have the engine exit if it starts and doesn't find the source it expects.  Kube will restart the container until it does start running.  This feels "gross" at first but we got over it pretty quickly.
2. Implement a "wait" script on your engine side that waits for the folder containing the source or some other indicator file to appear.  This is easiest if you invoke bash to chain things together, but you can develop better ways.

(Note: I'm not sure how bash does with signals and reaping)

**Comment by evmin** [comment]
All these options are working solutions - and I am sure I will use them for other scenarios going forward.

But as you correctly noted - they do seem a bit "gross" in this particular case. Especially in the light of the existing, and a very nice feature - gitRepo.

Do I read it correctly that parsing ENV variables in "repository" clause is not possible?

**Comment by huggsboson** [comment]
The right solution is to use secrets to store at least the password.  This would cleanly fit into the side car proposal.  I understand their hesitance to implement ordering primitives in core kube given how slippery that slope is, especially given that all containers should be capable of "dealing" with networked resources being unavailable.

I implemented a lot of this here (this one tries to do ssh auth instead of basic auth):
https://github.com/huggsboson/kubernetes/tree/gitRepoSsh

but abandoned it when I saw the rationale around using side cars.  Now just looking for some time to add similar functionality there.

**Comment by evmin** [comment]
I see the rationale with the side cars. 
Unfortunately the amount of work required to implement the synchronisation dependency somewhat defeats the purpose.

The key takeout here I think that an easy way to source the git repo as a file system is required. 
How it is implemented - is another matter. Sidecar with startup order, gitRepo with ssh sync, something else.

I will check out the postStart hook - thank you for the hint on auto container restarts..

**Comment by resouer** [comment]
@evmin what if you mount a Secret volume and consume it as env in repo url?

**Comment by evmin** [comment]
@resouer That's what I have tried the first. Does not seem to work. 
Event log output:

Error syncing pod, skipping: failed to exec 'git clone 
https://$(BITBUCKET_USERNAME):$(BITBUCKET_PASSWORD)@bitbucket.org/team/project.git main: Cloning into 'main'...
fatal: Authentication failed
: exit status 128

**Comment by resouer** [comment]
Your secret value does not mapping to ENV successfully. Did you following:
http://kubernetes.io/docs/user-guide/secrets/#consuming-secret-values-from-environment-variables

**Comment by evmin** [comment]
I want to believe that the container is being set up correctly.
At least when I comment out gitRepo and the volume the container gets created and I can see the ENV variable:

>cubectl exec -ti experiment-2-gqmun sh
>/ # echo $BITBUCKET_USERNAME
>usernamehere

I think the issues might be coming from the fact that ENV variable is defined _per_container_ and container definition is somewhat external to volume declaration.

@resouer do you mind trying it out on your side - may be I am indeed missing something obvious.

**Comment by resouer** [comment]
Sure, will try out this and feedback here.

**Comment by stp-ip** [comment]
Didn't work for me either (same issues as @evmin). Referencing the secret within the repository url did not work. On the side: If it did work, it would leak the credentials into logs, which might be undesirable anyway.

**Comment by resouer** [comment]
The current implementation is not aware of ENVs in git command string, see: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/git_repo/git_repo.go#L171

@stp-ip We can change the log contents, that's easy. I wonder if anyone feels like to send a patch to fix this? It's straightforward.

**Comment by thockin** [comment]
I still think the right answer is to make sidecar containers work.  It's a little more cumbersome but please consider - if we keep extending gitRepo, we have no basis on which to deny the inevitable hgRepo and svnRepo and httpGet and scpVolume and bitTorrent and ...

We should make it easier to side-car properly, instead.  To prove how "easy" it is, I did this:

   https://github.com/thockin/random_code/tree/master/intra-pod-startup-sync

In so doing, I realize that git-sync's documentation is bad and it doesn't do an atomic first pull (and I don't think subsequent pulls either though that is less obvious to me how to do).  So I'll put a bounty on it.  I'll send a Kube t-shirt and stickers to whomever:

a) Fixes the docs for git-sync so they don't suck
b) Makes the initial pull go to a randomly-named tmpdir, and then rename that to the actual destination
c) Makes refresh pulls atomic, or proves that they already are.

That's three separate bounties.

In the mean time, I am closing this.  I do not want to extend the gitRepo volume.  Saying "no" is really hard.

**Comment by thockin** [comment]
BTW: https://github.com/kubernetes/contrib/tree/master/git-sync is the repo for git-sync

**Comment by resouer** [comment]
@thockin Why should we do b) ? And how we define that when dest is `.`?

**Comment by thockin** [comment]
Without b) you can't use the git-content as the interlock, you have to add
a surrogate file.  Consider I have a 10GB repo to pull and dest = /data.
As soon as git starts pulling, that directory exists, but clearly all 10 GB
has not been pulled down.

**Comment by evmin** [comment]
My concern would be that while this improvement request is closed the sidecar option does not eventuate.

The fantastic example with https://github.com/kubernetes/contrib/tree/master/git-sync shows how cumbersome the implementation could be with the logic spread across three layers - script, docker and kubernetes.

That's exactly what I would like to avoid.

My 2 cents. 

In either case - I would like to thank everyone who put in the effort of looking and thinking about the case.

**Comment by gregory-lyons** [comment]
@thockin I've coded up an implementation of atomic initial pulls using your suggested method, but there doesn't seem to be an easy way to extend that to the refresh pulls. What about the possibility of cloning the repo twice? One copy pulls while the other serves content, and then swap atomically when a pull is complete.

**Comment by thockin** [comment]
If we did that, it would have to be an option, because it will use more
disk space and bandwidth.  Ideally we would only re-pull if there were
changes.  Maybe something like:

pull to data.1
ln -s data.tmp data.1
mv data.tmp data # atomic
copy data.1 to data.2
while true
  try pull into data.2
  if changed
    ln -s data.tmp data.2
    mv data.tmp data
    rm -rf data.1
    copy data.2 to data.3
  endif
endwhile

Something like that.  The biggest problem I see is in how the DEST is
currently specified, is it safe to assume that you can write to the parent
of it or that it will be on the same filesystem (needed for atomic move).
If not, maybe "act atomically" is a flag that demands that you keep your
data in a subdir of DEST...

**Comment by gregory-lyons** [comment]
I'm not sure the rename way is going to work. I'm admittedly not super familiar with volumes, but it seems that I'm unable to do a rename that replaces the directory that holds the mounted volume. 

E.g. I've mounted an emptyDir volume at /git in the git-sync container, but trying to atomically replace /git with the tempdir gives an error with "Device or resource busy."

Given that the mounted volume is a pretty integral part of the git-sync sidecar idea, I'm not sure how to get around this if we can't modify the volume's directory directly and copying into the directory isn't atomic.

**Comment by gregory-lyons** [comment]
^Nevermind, ignore above comment. I see what you are saying about keeping data in a subdir of DEST, I was thinking about the case of pulling in the volume root.

**Comment by thockin** [comment]
Yeah, you got it. :)

**Comment by gregory-lyons** [comment]
How about a (string) flag/environment variable GIT_SYNC_ATOMIC_SUBDIR? If it is empty string (which is default), we don't worry about "acting atomically" and pull right into DEST. If a string is provided, that string is used as the target subdir of DEST for pulling.

That way you can use a single flag/variable to specify both your desire for atomic behavior and where you expect the data to end up (e.g. if you set GIT_SYNC_ATOMIC_SUBDIR as "data", then you need to look in DEST/data for your content).

**Comment by gregory-lyons** [comment]
Or perhaps there's a better way that involves changing "GIT_SYNC_DEST" to make it more like the equivalent in gitRepo: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L748

We would have a default mount location for the emptyDir volume (e.g. /git), and then the optional GIT_SYNC_DEST (or _TARGET, _DIRECTORY, whatever) is a subdir within the volume directory. If GIT_SYNC_DEST is unspecified, the default volume directory is the Git repository. Regardless of atomic pulling, this seems more intuitive to me.

As for atomic pulling, we would have an additional ATOMIC flag, and would give an error if ATOMIC was specified but GIT_SYNC_DEST was not.

@thockin @huggsboson
