### ISSUE TITLE
Restarting of kube-controller-manager shoudn't lead to re-emitting old endpoints events.

### ISSUE THREAD

**Issue by ssergiienko** [kubernetes/kubernetes#17675]
We are heavily relying on /endpoints?watch=true functionality, and we are stuck why restarting kube-controller-manager leads to re-emitting old events? We always use ?resourceversions=xxxx but this doesn't solve the problem.
We also listen for /pods and /nodes events, but they are not affected by this bug.

For example, if we don't touch any thing in the cluster, and just restart kube-controller-manager.service then we have this almost after each restart:

Logs of our application in form "listener_function | current_resource_version | last_resource_version"

```
process_endpoints_event 1294 1226
process_endpoints_event 1295 1294
==DELETED OBJ 1 ==
process_endpoints_event 1296 1295
==DELETED OBJ 2 ==
process_endpoints_event 1297 1296
process_endpoints_event 1298 1297
==DELETED OBJ 3==
process_endpoints_event 1299 1298
process_endpoints_event 1300 1299
==ADDED OBJ 1 ==
process_endpoints_event 1301 1300
process_endpoints_event 1302 1301
==ADDED OBJ 2 ==
process_endpoints_event 1303 1302
==ADDED OBJ 3 ==
```

This happends almost after each restart of kube-controller-manager (usually 1-3).
Events:

```
{u'object': {u'kind': u'Endpoints', u'subsets': []...
{u'object': {u'kind': u'Endpoints', u'subsets': []...
{u'object': {u'kind': u'Endpoints', u'subsets': [{u'addresses': [{u'ip': u'10.254.87.2'
{u'object': {u'kind': u'Endpoints', u'subsets': [{u'addresses': [{u'ip': u'10.254.42.3'
...
```

Kubernetes v1.0.3;

Is this a bug or we are doing something wrong?

**Comment by lavalamp** [comment]
I think what is going on is that endpoint controller is generating endpoints before it's finished loading the pods, and therefore it deletes all endpoints and then recreates them. Oops!

So you're not getting old watch entries, you're getting new ones. The problem is that they are being generated at all.

@davidopp if you can't find someone to fix this I might be able to throw something together.

**Comment by davidopp** [comment]
@bprashanth Do you think you could take a look at this?

**Comment by kargakis** [comment]
@kubernetes/sig-scalability-misc
