### ISSUE TITLE
http://kubernetes.io/v1.1/gs-custom.html refers to http://kubernetes.io/v1.0/docs/getting-started-guides/README.html

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#17677]
... which is a problem because the referent is not the latest version.

**Comment by MikeSpreitzer** [comment]
Where is the source for http://kubernetes.io/v1.1/gs-custom.html ?

**Comment by bgrant0607** [comment]
Looks like this was created directly in the gh-pages branch:
https://github.com/kubernetes/kubernetes/blob/gh-pages/_v1.1/gs-custom.md

**Comment by bgrant0607** [comment]
@MikeSpreitzer A PR would be welcome to fix this.

**Comment by MikeSpreitzer** [comment]
Is there a written procedure for creating a PR for gh-pages?

**Comment by MikeSpreitzer** [comment]
I would like to make a PR but am having a little trouble with the procedure.  GitHub pages are a bit odd.  Should I be looking for a directory or a branch?  I have been following the procedures at http://kubernetes.io/v1.1/docs/devel/development.html --- which address ordinary directories on the master branch.

**Comment by MikeSpreitzer** [comment]
I think I may have worked it out.

**Comment by MikeSpreitzer** [comment]
@bgrant0607 Can you please have a look at PR #20438 ?

**Comment by MikeSpreitzer** [comment]
Resolved by PR #20438
