### ISSUE TITLE
Volume Plugins Should Use fsnotify

### ISSUE THREAD

**Issue by swagiaal** [kubernetes/kubernetes#17680]
Currently volume plugins which require attachment of a device simply poll until the path exists. Using something like [fsnotify](https://github.com/go-fsnotify/fsnotify) would eliminate the need for polling.

Note: This introduces a dependency on fsnotify.
~~Note 2: If the attach detach controller proposed by @saad-ali here #15524 implements a signal to indicate the completion of the attach this might not be needed.~~

**Comment by pmorie** [comment]
@kubernetes/rh-storage

**Comment by saad-ali** [comment]
Neat! But, it'll add complexity, so not sure if it's worth it.
