### ISSUE TITLE
Disallow overrides in hack/jenkins/e2e.sh

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#17696]
Right now, we have case logic that (I believe) allows Jenkins configs to override the source-controlled config:

```
case
  ...)
    : ${E2E_CLUSTER_NAME:='my-cluster'}
...
```

We shouldn't allow Jenkins to override the source controlled configs.

cc @kubernetes/goog-testing

**Comment by ixdy** [comment]
That was somewhat intentional, so that we could hotfix things as necessary without having to worry about updating e2e.sh, but we could aim at retiring that.

**Comment by ihmccreery** [comment]
Hotfixing things via Jenkins configs leads to confusion.  If it's painful to update things in version control, (it is, for sure,) we should fix that.  Somehow.  `e2e-not-required`?

**Comment by ixdy** [comment]
Given that almost all Jenkins config has ported to YAML, it seems like this is probably safe to do? Not sure if anyone outside Google is (unwisely?) using our hack/jenkins/e2e.sh, though.

@kubernetes/sig-testing

**Comment by spiffxp** [comment]
what do we think about closing?  e2e.sh is now hack/jenkins/e2e-runner.sh, and my read of its history is that this has either been done or is much less of an issue?

**Comment by ixdy** [comment]
yeah, I'm fine closing as obsolete.
