### ISSUE TITLE
the error information of creating POD should be more precise

### ISSUE THREAD

**Issue by huangyuqi** [kubernetes/kubernetes#17705]
I always use `kubectl create -f pod.yaml` to create a pod, but if something wrong happened , **I can just get the state of POD is `pending`**, though there are **many kinds of internal error** objectively exists. For example:
- The URL of images is invalid
  
  Kubernetes just return the state `pending` to users. Unless you run `kubectl get pods -ojson`, you can get the real error:

```
"API error (500): repository name component must match \"[a-z0-9]+(?:[._-][a-z0-9]+)*\"\n"
```
- failed to schedule
  
  when resource of all nodes is limit, if you run `kubectl create -f pod.yaml`, the state of pod will also be `pending`. Until you run `kubectl describe pod ***` , you can get the real error 

```
{scheduler } failedScheduling Failed for reason PodFitsResources and possibly others
```

BTW, there are five states of PODs in kubernetes:

``` golang
type PodPhase string
const (
    PodPending PodPhase = "Pending"
    PodRunning PodPhase = "Running"
    PodSucceeded PodPhase = "Succeeded"
    PodFailed PodPhase = "Failed"
    PodUnknown PodPhase = "Unknown"
)
```

It can not represent the phase of PODs clearly enough.
So, should we add some **another phases** or **some different status code(or error code)** to   signify more states of PODs for users?

**Comment by feihujiang** [comment]
The discussion whether to add new phases is in #7856

**Comment by huangyuqi** [comment]
thanks @feihujiang

**Comment by bgrant0607** [comment]
We don't need a new phase for this. It sounds like the information is already available, but not displayed.

**Comment by yujuhong** [comment]
> We don't need a new phase for this. It sounds like the information is already available, but not displayed.

It is displayed in `kubectl describe` if I read/remember correctly. The issue seems to be more about adding more phases.
