### ISSUE TITLE
kubectl push to kube-registry

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#17707]
Thanks @uluyol for making this happen.  However, pushing image to private repository is a bit boring as one needs to find registry POD, port-forward, tag, push.  It seems we can simplify the process by just using `kubectl push IMAGE`. 

But:
- Registry addon is just an "addon", do we want to support that? or Do we have extension module for kubectl?
- `kubectl push` will transform image to localhost, e.g. if I do `kubectl push ubuntu`, I have to use `localhost:5000/ubuntu` to access the image.  I don't know if this makes sense for user.  We might do better if https://github.com/kubernetes/kubernetes/pull/11599 works.

**Comment by smarterclayton** [comment]
Copied from the pr:

I'm a bit skeptical that we're ready for something this opinionated in the cli without a larger discussion about the registry addon and extension CLIs.  I also don't think this has to be a kubectl command - it can very easily be something in contrib/.  It assumes details of the registry addon that I don't think represent the standard needs of a registry deployed with Kube (like security).

**Comment by bgrant0607** [comment]
See also #16010

**Comment by kargakis** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by kargakis** [comment]
Echoing Clayton's concerns - this doesn't have to be a kubectl command.

**Comment by adohe** [comment]
I really don't hope this be a kubectl command, we could have kubectl plugin for this.

**Comment by ddysher** [comment]
It's an old request.  Now I look at it, it shouldn't be part of kubectl.  I don't know if kubectl has a plugin or not; if we do, this could be a good candidate.
