### ISSUE TITLE
Make sure that every controller run by the controller manager uses separate client.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#17723]
It's needed for finer-grained monitoring.

In the same time we need to make sure that all clients reuse the same transport to avoid creating unnecessary connections.

cc @lavalamp @brendandburns @wojtek-t @fgrzadkowski

**Comment by wojtek-t** [comment]
This will also help with setting separate QPS limits per client (which on the other hand has disadvantages of not being able to set the "altogether limit").

**Comment by wojtek-t** [comment]
@kubernetes/goog-csi

**Comment by wojtek-t** [comment]
I agree that starting with just per-client QPS limit is a good idea. I think in many cases only a single controller is trying to do something non-trivial (e.g. starting RC with many replicas is triggering a bunch of writes from RC - but just RC, or deleting namespace is triggering namespace controller, but just it). 
So I think it shouldn't be a big problem (at least for now).

**Comment by gmarek** [comment]
I was looking at it today in hope that I can write the PR in an hour or so, but new transport logic copies the UserAgent to the very bottom of transport during the creation and wrapped inside the Decorated Round Tripper. So if I want to reuse the same transport I need to untangle this decorator first - I'll finish it tomorrow.
