### ISSUE TITLE
Add getEnvOr(...) feature to utils

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#17727]
Lets move 

https://github.com/kubernetes/kubernetes/blob/b9cfab87e33ea649bdd13a1bd243c502d76e5d22/pkg/volume/flocker/util.go

Into general utilities env library, and  add corner cases to the tests (empty, support for parsing ints and so on).

cc @krousey  this will be useful for ideas like you had for env guarding.  

(In general I think more support for env vars will make maintaining options alot easier anyway, and probably paves the way for what was mentioned by others in #5472, where we might start reducing cmd line options entirely... )

**Comment by jayunit100** [comment]
In general this util should support 

- getEnvAsIntOr
- getEnvAsStringOr
- getEnvAsFloat64Or

.. should cover most usecases.

**Comment by agonzalezro** [comment]
Hi @jayunit100, a "problem" with your approach is that the signatures of the returns of the functions are going to be different because parsing a string to int or float can fail:

```
getEnvAsIntOr(string, int) (int, error)
getEnvAsStringOr(string, string) string
getEnvAsFloat64Or(string, float64) (float64, error)
```

It could be easily solvable if in case of error we return the default but that will add more logic there:

1. key was found
  a) return it's value if cast'able
  b) return default if some error happened
2. key was not found
  a) return default

^ I think that this behaviour is ok.

PS: I called the default function `getenv` lowercased to keep the same naming that they used on the original function `os.Getenv`. I always though that it should be `os.GetEnv` though :)

**Comment by jayunit100** [comment]
Im also Happy to return error in all cases, along with a default value...
```
getEnvAsIntOr(string, int) (int, error)
getEnvAsStringOr(string, string) string
getEnvAsFloat64Or(string, float64) (float64, error)
```
i think we are all on the same page.  How smart the casting ==  just an impl detail.  for first iteration, Defaults will be relied on heavily and that should be ok.

**Comment by agonzalezro** [comment]
@jayunit100 I am not sure that error will be ever be needed in `getEnvAsStringOr`, but definitely, I am ok with make this more global than just residing in the Flocker plugin utils.

**Comment by nagarjung** [comment]
Hi @jayunit100 : Is this issue open to work on or anyone working on this issue? Please let me know if I can work on this issue.

**Comment by jayunit100** [comment]
Open to work on if you are working now, as I'm off until January 4.  If you beat me to the patch that's great :)!

**Comment by nagarjung** [comment]
@jayunit100 : I had asked this question because a week back you had asked me to work on 2 issues, one of which was this. As I'm new to opensource I was not clear with the status of the issue.

**Comment by jayunit100** [comment]
ah yes, I believe you asked for some easy golang patches to get started with? I think this is in that category.  So, are you working on this currently?  If so I won't look at it.

**Comment by nagarjung** [comment]
Sure, I will work on this.

**Comment by nagarjung** [comment]
Can you please re-assign it to me?

**Comment by nagarjung** [comment]
Hi @jayunit100 : As mentioned above I have re-written util.go,we can place this as flocker.go in kubernetes/pkg/util/flocker.go. Let me know for any changes. If the proposed change is good enough please let me know If can proceed further with PR. 

package flocker

import (
	"os"
	"strconv"
)

func GetEnvAsStringOr(key, defaultValue string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return defaultValue
}

func GetEnvAsIntOr(key string, defaultValue int) (int, error) {
	if v := os.Getenv(key); v != "" {
		value, err := strconv.Atoi(v)
		if err != nil {
			return defaultValue, err
		} else {
			return value, nil
		}
	}
	return defaultValue, nil
}

func GetEnvAsFloat64Or(key string, defaultValue float64) (float64, error) {
	if v := os.Getenv(key); v != "" {
		value, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return defaultValue, err
		} else {
			return value, nil
		}
	}
	return defaultValue, nil
}

**Comment by jayunit100** [comment]
For code snippets use three backticks 
```
``` code ```
```

**Comment by jayunit100** [comment]
@nagarjung craft a PR at very quick glance it looks ok.  it will be easier to eval as a PR.  Make sure to add unit tests for each in the PR

**Comment by agonzalezro** [comment]
It looks good. Only thing I would to say is that the names `GetEnvAsXxxOr` doesn't sound right to me. `Or` what? I know that perhaps `Fallback` as it was originally could not be a good name either, but it gives a little bit more info. What do you think?

**Comment by asalkeld** [comment]
please close this issue, fixing PR is merged.
