### ISSUE TITLE
Kubelet Stat fs failed

### ISSUE THREAD

**Issue by HardySimpson** [kubernetes/kubernetes#17725]
version: 1.1.1

when start the kubelet on node, with docker storage option devicemapper, nearly all CPU is used by kubelet

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                           
17478 root      20   0 1098260 113520  13120 S 40.8  2.8 203:48.04 kubelet  
```

check the log, can see

```
I1124 20:40:45.626406   29547 server.go:944] POST /stats/container/: (2.376501097s) 0 [[Go 1.1 package http] 33.1.3.72:46808]
E1124 20:40:47.563834   29547 fs.go:211] Stat fs failed. Error: EOF
I1124 20:40:47.718322   29547 server.go:944] POST /stats/container/: (4.397950894s) 0 [[Go 1.1 package http] 33.1.1.15:50056]
E1124 20:40:49.638118   29547 fs.go:211] Stat fs failed. Error: EOF
```

put more debug log in fs.go, and get this

```
E1124 20:25:30.253016   14151 fs.go:211] Stat fs failed. Error: no such file or directory
E1124 20:25:30.383152   14151 fs.go:372] Stat fs failed. poolName: docker-253:1-270437-pool
E1124 20:25:30.391324   14151 fs.go:382] Stat fs failed. dmStatus: 0 209715200 thin-pool 707 1215/524288 30282/1638400 - rw discard_passdown
E1124 20:25:30.391472   14151 fs.go:211] Stat fs failed. Error: EOF
```

compare to the code:

```
	_, err = fmt.Fscanf(bytes.NewReader(dmStatus),
		"%d %d %s %d %d/%d %d/%d %s %s %s %s",
		&bkt, &bkt, &bkts, &bkt, &bkt, &bkt, &used, &total, &bkts, &bkts, &bkts, &bkts)
```

that there is one more %s at the end. 

So, is it a bug ? is anyone else have seen it? the os of node is `"Ubuntu 14.04 LTS"`

**Comment by dchen1107** [comment]
cc/ @jimmidyson  I thought we fixed this in latest cadvisor release?

**Comment by jimmidyson** [comment]
Damn must have messed up the format string. Simple fix, dropping strings at end of format string. Sorry about that - will fix tomorrow if noone gets there first.

**Comment by jimmidyson** [comment]
@HardySimpson The high CPU is intriguing though - would you be able to run pprof against the kubelet & share the graph?

**Comment by jimmidyson** [comment]
Fix in google/cadvisor#976, will bump k8s dependencies when merged & cadvisor released.

**Comment by HardySimpson** [comment]
@jimmidyson  high CPU is another problem, we are running pprof now

**Comment by yujuhong** [comment]
@HardySimpson, pprof result will certainly be appreciated. Could you also post the output of `kubectl version`, as well as the number of pods/containers on the node?
