### ISSUE TITLE
Cassandra example Endpoints permissions

### ISSUE THREAD

**Issue by palonsoro** [kubernetes/kubernetes#17724]
Cassandra example requires a service account with permissions to read the namespaces endpoints via Kubernetes API. These seem not to be given to the default service account by default. Thus, further action is required from the user (creating and specifying a different service account or giving permissions to default ones).

However, neither the need of doing this nor the steps required to do it seem to be mentioned in the example README and they should. Else, a novice may find an example that just does not work without any guidance about why.

To be clear: I have no problem workarounding this. What I am suggesting is just to fix the documentation in order to help other people.

I have tested this on OpenShift 3. I am not sure whether this would make a big difference with a vanilla Kubernetes cluster, but at least a "warning" or a "troubleshooting" section talking about this might be a good idea anyway.

**Comment by chrislovecnm** [comment]
This service account is used by the SeedProvider.  Multiple ENV vars can be used to override default values as well.  Don't think this is documented.

They start here: https://github.com/amygdala/kubernetes/blob/cassandra2/examples/cassandra/java/src/io/k8s/cassandra/KubernetesSeedProvider.java#L121

Mentioned it here: https://github.com/kubernetes/kubernetes/issues/20961

**Comment by chrislovecnm** [comment]
@palonsoro I have https://github.com/kubernetes/kubernetes/issues/24290 open.  Feedback would be awesome!

Also have a PR in with the start of documenting this component: https://github.com/kubernetes/kubernetes/pull/24296

**Comment by chrislovecnm** [comment]
@palonsoro this is pretty much designed, tested, documented and done at scale.  Can we close?

**Comment by palonsoro** [comment]
Excuse me for the delay, I did not receive mail notifications for some reason.

I see that the new documentation documents the env variables, but that is not what I was pointing. I was talking about the fact that, by default, pods `default` service account does not have permission to read the `Endpoints`. You need to either give such permission to the `default` service account or deploy your cassandra pods with a service account that has that permissions.

**Comment by chrislovecnm** [comment]
Not the behavior I have seen with deployment with kube-up.sh. Are you deployed in another manner.

**Comment by palonsoro** [comment]
I am deploying it on top of OpenShift, which gives absolutely no permission to the `default` service account of namespaces by default. Anyway, giving or not giving such default permissions is up to administrators of each cluster, depending on how they want new namespaces to be bootstrapped.

I have tested it neither with a kube-up.sh deployment nor with other kind of vanilla Kubernetes. However, an administrator creating namespaces whose `default` service account lacks of appropriate permissions to read namespace `endpoints` may cause this cassandra example not to work, both in OpenShift and vanilla Kubernetes. 

Therefore, I think it is worth documenting that `default` service account requires enough permissions to read `endpoints` objects at the namespace, or that you have to use a different service account with such permissions.

**Comment by kargakis** [comment]
@ahmetb

**Comment by chrislovecnm** [comment]
Can we close this issue?  Stateful set is the recommended manifest now, and we do not use this code now.

**Comment by ahmetb** [comment]
@chrislovecnm +1
