### ISSUE TITLE
Installing v1.1.1 kubernetes and 1.8.3 docker on ubuntu is failure

### ISSUE THREAD

**Issue by wangqunOne** [kubernetes/kubernetes#17720]
Hi, I install v1.1.1 kubernetes and 1.8.3 docker on ubuntu. 
My install process is follow:
1. install docker 1.8.3
2.install kubernetes according to https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md
 I config the KUBE_VERSION=1.1.1 and  FLANNEL_VERSION=0.5.3 and export ETCD_VERSION=2.2.1 in build.sh file.
3. run KUBERNETES_PROVIDER=ubuntu ./kube-up.sh

 $ ./kubectl get nodes
NAME       LABELS                            STATUS     AGE
10.0.0.4   kubernetes.io/hostname=10.0.0.4   NotReady   1h

$docker ps
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

I check the dock.log.Its content is following:
, error: exit status 1
^[[34mINFO^[[0m[0002] Firewalld running: false
^[[31mFATA^[[0m[0005] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: bridge IPv4 (172.17.42.1) does not match requested configuration 172.16.23.1
^[[33mWARN^[[0m[0001] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\
^[[34mINFO^[[0m[0001] Listening for HTTP on tcp (127.0.0.1:4243)
^[[34mINFO^[[0m[0001] Listening for HTTP on unix (/var/run/docker.sock)
^[[34mINFO^[[0m[0002] [graphdriver] using prior storage driver "aufs"
^[[34mINFO^[[0m[0002] Option DefaultDriver: bridge
^[[34mINFO^[[0m[0002] Option DefaultNetwork: bridge

$ip a

3: docker0: <BROADCAST,MULTICAST> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:18:74:cb:b9 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
6: flannel0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1472 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 172.16.23.0/16 scope global flannel0
       valid_lft forever preferred_lft forever

**Comment by wangqunOne** [comment]
@ZJU-SEL

**Comment by HackToday** [comment]
ping @mwielgus  who maintain this page ?
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

Thanks

**Comment by dalanlan** [comment]
@wangqunOne  @HackToday  
We do. 

Could you please kindly check the content of `/etc/default/docker`?

**Comment by HackToday** [comment]
@dalanlan  the docker install first, it is following case:

# cat /etc/default/docker 


# Docker Upstart and SysVinit configuration file

# Customize location of Docker binary (especially for development testing).
#DOCKER="/usr/local/bin/docker"

# Use DOCKER_OPTS to modify the daemon startup options.
#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export TMPDIR="/mnt/bigdrive/docker-tmp"



After ubuntu kubernetes setup, it changed docker setting to something bip=172.16.**, ( which make docker not work anymore. I have deleted docker 1.8.3. and try reinstall it.) But I hope above details can help you think why ubuntu scripts failed

**Comment by dalanlan** [comment]
Something like `--bip=172.16.63.1/24 --mtu=1372` is expected. 
docker daemon intends to use bip read from subnet.env, which generated by `flanneld`

**Comment by zhengguoyong** [comment]
manually start docker daemon may work, you can try.
@wangqunOne

**Comment by HackToday** [comment]
@dalanlan  I tried remove docker, and install docker again, and then run 
KUBERNETES_PROVIDER=ubuntu ./kube-up.sh

But seems /etc/default/docker not change anything, still old content, 
$ cat /etc/default/docker

#DOCKER="/usr/local/bin/docker"

#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"
#export http_proxy="http://127.0.0.1:3128/"
#export TMPDIR="/mnt/bigdrive/docker-tmp"

Docker can work, But I suspect the kubernetes not configure docker 
Does it means kubernets not configure docker here ?

**Comment by dalanlan** [comment]
You(cluster admin) are supposed to handle networking setting, what k8s works based on. 
The script manages to bring down docker0 bridge, change the setting of docker daemon, and restart it for you.
If the setting of docker daemon remains still, you need to check out whether etcd or flanneld works expectedly.



Sent from myMail for iOS


Wednesday, November 25, 2015, 10:45 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by HackToday** [comment]
tried the second time, it works. So seems strange issue. Close it when reproduce it next time

**Comment by dalanlan** [comment]
@wangqunOne  @HackToday  Do you guys work together? If that's the case, this issue can be safely closed.
