### ISSUE TITLE
/componentstatus checks do not honor TLS settings via --etcd-config

### ISSUE THREAD

**Issue by thrawn01** [kubernetes/kubernetes#17737]
Looking at the code, it looks like `DoServerCheck()` in `pkg/apiserver/validator.go` creates a new Transport with a default TLS config if `EnableHTTPS` is true; which is not helpful if using custom certs to connect to etcd. In addition the way `getServersToValidate()` in `pkg/master/master.go` is currently written it will never instantiate `apiserver.Server{}` with `EnableHTTPS` enabled.

There are several todo's in `DoServerCheck()` which appear to indicate a larger issue with this code as written. I'm creating this issue in the hope that when `DoServerCheck()` is rewritten it will respect --etcd-config settings.

I may attempt a patch for this after the new years if no one picks it up.

**Comment by liggitt** [comment]
related: https://github.com/kubernetes/kubernetes/issues/17461

**Comment by lavalamp** [comment]
@karlkfi

**Comment by karlkfi** [comment]
componentstatuses needs to be nuked from orbit. feel free to monkey-patch the shit out of it.
I hope it becomes obsolete after component registrations gets further along.

**Comment by kargakis** [comment]
@mikedanese @kubernetes/sig-cluster-lifecycle-misc

**Comment by wojtek-t** [comment]
It has been fixed in https://github.com/kubernetes/kubernetes/pull/39716
