### ISSUE TITLE
kubelet attempts to delete/recreate Node API object

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#17731]
In kubelet.go#registerWithApiserver, if a Node API object already exists with a different ExternalID, the kubelet attempts to delete/recreate the Node API object.

If we expect this value to be able to mutate, why not allow mutation in update?

The current behavior requires giving nodes the ability to delete Node API objects, which seems bad.

I would also expect node deletion to potentially evacuate pods on the node, which also seems bad.

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by liggitt** [comment]
Also, the message logged in that case is incorrect (has previous and desired value swapped):
```
			glog.Errorf(
				"Previously %q had externalID %q; now it is %q; will delete and recreate.",
				kl.nodeName, node.Spec.ExternalID, currentNode.Spec.ExternalID,
			)
```

**Comment by liggitt** [comment]
cc @sdodson @ebalsumgo

**Comment by ebalsumgo** [comment]
Seems this might be of some relevance as well https://github.com/openshift/openshift-ansible/issues/943

**Comment by dchen1107** [comment]
cc/ @bgrant0607 we talked about deprecated ExternalID for a while. Today the node identification and addressing is totally messy. From code, I can tell most of cloud provider implementation default this to node name already. 

cc/ @roberthbailey on GKE side @justinsb on AWS case.

**Comment by derekwaynecarr** [comment]
@liggitt - +1 , or allow a specific subresource to support modification of ```ExternalID``` if its not entirely deprecated.

**Comment by roberthbailey** [comment]
The delete / recreate was an expedient way to do an update (because you could have a node on GCE change from g1-small to n1-standard-4 with the same name and we want the capacity to be updated). If we have a more efficient way to do an update that's ok with me. Or if we use something more unique (not the machine name) that changes if a machine's fundamental properties are changed then that would work too.

**Comment by bgrant0607** [comment]
Does this happen in practice?

Not sure if anyone depends on contents of ExternalID. At minimum, we need to rethink the name of this field and whether it should be in status instead. I'd be in favor of specifying that it should be stable.

cc @simon3z

**Comment by liggitt** [comment]
> Does this happen in practice?

Yes, happened when we started referring to existing nodes by IP for SDN purposes

**Comment by simon3z** [comment]
> Does this happen in practice?
> 
> Not sure if anyone depends on contents of ExternalID. At minimum, we need to rethink the name of this field and whether it should be in status instead. I'd be in favor of specifying that it should be stable.
> 
> cc @simon3z

@bgrant0607 we're currently collecting `ExternalID` in ManageIQ but we don't depend on the value.

In other words you can change the content of the field but removing it altogether would break us.
(Please consider to set it to an empty string if you want to stop maintaining it, and make sure it's **not** `omitempty` in case that applies to strings as well).

Thanks.

**Comment by simon3z** [comment]
@bgrant0607 in the long run you can plan to remove it (I'm in favor of that, I believe that `ProviderID` provides more consistent information).

**Comment by pmorie** [comment]
I support making `ExternalID` mutable on update; let's ensure that if it is made so, it's reflected in the docs.  We don't do a great job of articulating in the API docs which fields are mutable/immutable.

**Comment by ncdc** [comment]
This also happens if you e.g use the OpenShift ansible installer to deploy a cluster (which registers your nodes) and then manually edit the node config to set a cloud provider. The switch from not specifying a cloud provider to specifying one results in the node trying to delete and reregister itself, and OpenShift's policy doesn't allow nodes to delete themselves.
