### ISSUE TITLE
kubelet /healthz endpoint should not include docker daemon health

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#17743]
Supervisord babysits docker daemon and kubelet separately. Having kubelet's health depending on docker seems unnecessary and cause kubelet to (potentially) be restarted when docker restarts.
Note that kubelet already checks the container runtime healthiness when reporting the node status, so changing this should not affect pod scheduling.

/cc @dchen1107

**Comment by dchen1107** [comment]
Yes, you are right. That check should be removed when we introduced daemon babysitter and NodeStatus checking on container runtime.
