### ISSUE TITLE
Add metrics for rate limiter saturation

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#17762]
cc @wojtek-t @fgrzadkowski @davidopp @lavalamp @timothysc

**Comment by timothysc** [comment]
@gmarek could you please elaborate a bit more on what you want to measure and why?  

e.g. - Problem Statement.

**Comment by hongchaodeng** [comment]
@timothysc 
Last time @gmarek and I discussed offline a little bit.
Basically we want to know whether rate limiter is saturated.

**Comment by hongchaodeng** [comment]
I send a PR to solve this issue #17673

**Comment by gmarek** [comment]
@timothysc - I need to find a time to share a doc I wrote:/ Big picture is that we feel like we lack a number of metrics that might help catching performance regressions early and/or make finding misbehaving components easier. This is one of such things - I can go into details why rate limiter saturation is such thing, but I think it's more or less obvious.

**Comment by timothysc** [comment]
>I can go into details why rate limiter saturation is such thing 

I totally get that one, but please share the doc as we are back in business on our end to eval up to 1k nodes on openstack.

**Comment by gmarek** [comment]
Fixed by #17673
