### ISSUE TITLE
getaddrinfo ENOTFOUND when making request to kubernetes services

### ISSUE THREAD

**Issue by ntquyen** [kubernetes/kubernetes#17763]
I'm running 10 nodes and about 160 pods in our cluster. The cluster is up for a month and suddenly this error happened frequently when making request among services in cluster

```
"response": {
    "err": {
      "code": "ENOTFOUND",
      "errno": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "svc-api-mapper",
      "host": "svc-api-mapper",
      "port": "80"
    }
  },
  "attempt": 0
```

the pods selected by the service are up and running, there was no event indicating that pods are up and down but somehow the service name `svc-api-mapper` cannot be resolved. 

```
$ kubectl describe se svc-api-mapper
Name:           svc-api-mapper
Namespace:      production
Labels:         app=workflow-koa-api-mapper
Selector:       app=workflow-koa-api-mapper
Type:           LoadBalancer
IP:             10.3.0.33
Port:           <unnamed>   80/TCP
NodePort:       <unnamed>   30106/TCP
Endpoints:      10.2.8.126:80,10.2.80.248:80
Session Affinity:   None
No events.
```

When I looked at the skydns logs, there were a lot of errors that printed every second:
`2015/11/22 05:40:00 skydns: can not forward, name too short (less than 2 labels): svc-rethinkdb-driver.`

Notice that the ENOTFOUND error doesn't always happen, just frequently. Is it related to performance issue?

I'm using kubernetes 1.0.1 in CoreOS cluster 773.1.0

**Comment by ericuldall** [comment]
We are experiencing similar issues on a service running a couchdb cluster.

**Comment by JaysonRaymond** [comment]
What the original poster didn't specify is that this is occurring in NodeJS - which obscures the real error coming back from getaddrinfo: https://github.com/nodejs/node/blob/master/lib/dns.js#L17-L24

**Comment by kilianc** [comment]
@JaysonRaymond I am having the same problem. The link you posted is pointing to master and I think the content of the file changed since your post. Was there a resolution to this?

**Comment by mousavian** [comment]
The correct link posted by @JaysonRaymond is: https://github.com/nodejs/node/blob/1125c8a814030f16fc995d897181ac9920f9d3db/lib/dns.js#L17-L24

**Comment by birdream** [comment]
I am having the same problem, A services is requesting the B service through the B service name and they are both in the same k8s, but it just happen ENOTFOUND error sometimes,  and I am not sure the code you gave in the nodejs can solve that problem..is there anyone know how to fix that?

**Comment by JaysonRaymond** [comment]
The point is that [nodejs is (was) not properly handling the error when it reports ENOTFOUND](https://github.com/nodejs/node/blob/1125c8a814030f16fc995d897181ac9920f9d3db/lib/dns.js#L17-L24):

function errnoException(err, syscall, hostname) {
  // FIXME(bnoordhuis) Remove this backwards compatibility nonsense and pass
  // the true error to the user. ENOTFOUND is not even a proper POSIX error!
  if (err === uv.UV_EAI_MEMORY ||
      err === uv.UV_EAI_NODATA ||
      err === uv.UV_EAI_NONAME) {
    err = 'ENOTFOUND';
  }

Looks like your problem could possibly related to MEMORY, NODATA or NONAME.
