### ISSUE TITLE
 Failed to start Kubernetes API Server.

### ISSUE THREAD

**Issue by hitechmike** [kubernetes/kubernetes#17767]
Hello,
I have some problems with kube-apiserver on master.
the daemon doens't startup automatically after the boot of the server

[root@labcr1 ~]# systemctl status kube-apiserver
kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled)
   Active: failed (Result: start-limit) since mer 2015-11-25 10:11:31 CET; 1h 34min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 1244 ExecStart=/usr/bin/kube-apiserver $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBE_ETCD_SERVERS $KUBE_API_ADDRESS $KUBE_API_PORT $KUBELET_PORT $KUBE_ALLOW_PRIV $KUBE_SERVICE_ADDRESSES $KUBE_ADMISSION_CONTROL $KUBE_API_ARGS (code=exited, status=255)
 Main PID: 1244 (code=exited, status=255)
   CGroup: /system.slice/kube-apiserver.service

nov 25 10:11:31 labcr1 systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
nov 25 10:11:31 labcr1 systemd[1]: Failed to start Kubernetes API Server.
nov 25 10:11:31 labcr1 systemd[1]: Unit kube-apiserver.service entered failed state.
nov 25 10:11:31 labcr1 systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
nov 25 10:11:31 labcr1 systemd[1]: Stopping Kubernetes API Server...
nov 25 10:11:31 labcr1 systemd[1]: Starting Kubernetes API Server...
nov 25 10:11:31 labcr1 systemd[1]: kube-apiserver.service start request repeated too quickly, refusing to start.
nov 25 10:11:31 labcr1 systemd[1]: Failed to start Kubernetes API Server.
nov 25 10:11:31 labcr1 systemd[1]: Unit kube-apiserver.service entered failed state.

starting it manually work as expected

root@labcr1 ~]# systemctl status kube-apiserver
kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled)
   Active: active (running) since mer 2015-11-25 11:46:16 CET; 1s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 1457 (kube-apiserver)
   CGroup: /system.slice/kube-apiserver.service
           └─1457 /usr/bin/kube-apiserver --logtostderr=true --v=0 --etcd_servers=http://127.0.0.1:2379 --addres...

nov 25 11:46:15 labcr1 kube-apiserver[1457]: I1125 11:46:15.175939    1457 master.go:295] Will report 10.99....ess.
nov 25 11:46:15 labcr1 kube-apiserver[1457]: E1125 11:46:15.175950    1457 reflector.go:136] Failed to list ...used
nov 25 11:46:15 labcr1 kube-apiserver[1457]: E1125 11:46:15.175973    1457 reflector.go:136] Failed to list ...used
nov 25 11:46:15 labcr1 kube-apiserver[1457]: E1125 11:46:15.176024    1457 reflector.go:136] Failed to list ...used
nov 25 11:46:15 labcr1 kube-apiserver[1457]: [restful] 2015/11/25 11:46:15 log.go:30: [restful/swagger] list...api/
nov 25 11:46:15 labcr1 kube-apiserver[1457]: [restful] 2015/11/25 11:46:15 log.go:30: [restful/swagger] http...-ui/
nov 25 11:46:15 labcr1 kube-apiserver[1457]: I1125 11:46:15.242740    1457 server.go:441] Serving securely o...6443
nov 25 11:46:15 labcr1 kube-apiserver[1457]: I1125 11:46:15.242759    1457 server.go:483] Serving insecurely...8080
nov 25 11:46:16 labcr1 kube-apiserver[1457]: I1125 11:46:16.145773    1457 server.go:456] Using self-signed ...key)
nov 25 11:46:16 labcr1 systemd[1]: Started Kubernetes API Server.
Hint: Some lines were ellipsized, use -l to show in full.

root@labcr1 ~]# uname -a
Linux labcr1 3.18.17-13.el7.x86_64 #1 SMP Wed Jul 22 14:20:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

root@labcr1 ~]# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 

[root@labcr1 ~]# rpm -qa | grep kube
kubernetes-client-1.0.3-0.2.gitb9a88a7.el7.x86_64
kubernetes-master-1.0.3-0.2.gitb9a88a7.el7.x86_64
kubernetes-node-1.0.3-0.2.gitb9a88a7.el7.x86_64
kubernetes-1.0.3-0.2.gitb9a88a7.el7.x86_64

on /var/log/messages

Nov 25 10:11:30 labcr1 kube-apiserver: I1125 10:11:30.942205    1211 plugins.go:69] No cloud provider specified.
Nov 25 10:11:30 labcr1 kube-apiserver: I1125 10:11:30.943305    1211 master.go:273] Node port range unspecified. De
faulting to 30000-32767.
Nov 25 10:11:30 labcr1 kube-apiserver: F1125 10:11:30.943413    1211 master.go:291] Unable to find suitable network
 address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid th
is wait.
Nov 25 10:11:30 labcr1 systemd: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Nov 25 10:11:30 labcr1 systemd: Failed to start Kubernetes API Server.
Nov 25 10:11:30 labcr1 systemd: Unit kube-apiserver.service entered failed state.
Nov 25 10:11:31 labcr1 systemd: kube-apiserver.service holdoff time over, scheduling restart.
Nov 25 10:11:31 labcr1 systemd: Stopping Kubernetes API Server...
Nov 25 10:11:31 labcr1 systemd: Starting Kubernetes API Server...
Nov 25 10:11:31 labcr1 kube-apiserver: I1125 10:11:31.067831    1223 plugins.go:69] No cloud provider specified.
Nov 25 10:11:31 labcr1 kube-apiserver: I1125 10:11:31.067980    1223 master.go:273] Node port range unspecified. De
faulting to 30000-32767.
Nov 25 10:11:31 labcr1 kube-apiserver: F1125 10:11:31.068028    1223 master.go:291] Unable to find suitable network
 address.error='Unable to select an IP.' . Will try again in 5 seconds. Set the public address directly to avoid th
is wait.
Nov 25 10:11:31 labcr1 systemd: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Nov 25 10:11:31 labcr1 systemd: Failed to start Kubernetes API Server.
Nov 25 10:11:31 labcr1 systemd: Unit kube-apiserver.service entered failed state.

**Comment by lavalamp** [comment]
Sorry for slow response--

Our default setup stuff uses kubelet to run apiserver. It appears you're using systemd directly. I'm not a systemd expert. Can you expand on your question: what part of it is kubernetes specific? (Alternatively, you could try asking on stackoverflow.)

Anyway, my guess is that you have a startup order issue, where kube-apiserver is getting started before your network interfaces come up. (`Unable to find suitable network address.error='Unable to select an IP.'`) If that's the problem, the suggested resolution is in the log message.

Please reopen if that doesn't resolve the issue.
