### ISSUE TITLE
MonitorResources test is failing in flaky suite

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#17773]
For some reason it's failing with error: 
```
04:36:49   Expected error:
04:36:49       <*errors.errorString | 0xc20827f470>: {
04:36:49           s: "missing info for container \"/kube-proxy\" on node \"e2e-flaky-minion-ajl8\"",
04:36:49       }
04:36:49       missing info for container "/kube-proxy" on node "e2e-flaky-minion-ajl8"
04:36:49   not to have occurred
```
cc @wojtek-t @ixdy

**Comment by wojtek-t** [comment]
@mikedanese - you move kube-proxy to the "pod". Do you know what can be causing it?

**Comment by mikedanese** [comment]
Yes that's the cause. @gmarek if you don't get to this, feel free to assign to me.

**Comment by gmarek** [comment]
@mikedanese - thanks, as you know the context here it'd be faster if you fix it.

**Comment by gmarek** [comment]
Thanks for taking care of this.
