### ISSUE TITLE
Big increase in Kubelets memory usage

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#17774]
While looking into monitor-resources test failures on flaky suite I noticed that I had to bump allowed memory usage in kubelet from 150MB to 1GB, as it's using > 750MB. The tests was consistently failing for quite some time for different reason (I'm not yet sure why: #17773) so it's hard to tell when exactly this happened.

Test run without any issued on private cluster.

cc @wojtek-t @fgrzadkowski @davidopp @lavalamp @dchen1107 @yujuhong

**Comment by wojtek-t** [comment]
@kubernetes/goog-node

**Comment by yujuhong** [comment]
The memory usage is the working set memory that includes active anonymous and file-backed pages. Because we do not set memory limit for the /kubelet cgroup, there usually lacks the memory pressure to force kernel to move pages from the active to inactive list, causing the active list to keep growing. IMO,  failing tests based on this number is not that meaningful for now. Could we remove the memory check in the test?

**Comment by gmarek** [comment]
Is there a way to make it more meaningful instead of disabling the test? We don't want to hit a real regression of this kind.

**Comment by timstclair** [comment]
Could we set a memory limit for testing? We have the advantage of a known workload on a controlled environment, so we should be able to set limits more accurately. Would this make the testing environment too different from actual usage?

**Comment by gmarek** [comment]
+1 to what @timstclair wrote.

**Comment by dchen1107** [comment]
This is known issue, https://github.com/kubernetes/kubernetes/issues/16943#issuecomment-154565523 has the explanation. We do have an aggressive goal to set hard limit for kubelet for 1.2 release. I can attempt to set limit for test first.

**Comment by davidopp** [comment]
@dchen1107 I looked at the comment you mentioned, but it doesn't seem to explain why Kubelet requires > 750 GB of memory. In fact @bprashanth 's measurements in that issue show 55 MB with 40 pause pods, which seems quite far from 750 GB.

**Comment by dchen1107** [comment]
@davidopp I am just about asking @gmarek copy & paste the output of "cat /sys/fs/cgroup/memory/kubelet/memory.stat" on those bad nodes. Also it is 750M, not 750G. But anyway, it is pretty big based on our own measurement in #16943. Please note that the measurement we have done is applying some hard limit.

**Comment by davidopp** [comment]
Yes sorry I meant 750 MB. :)

**Comment by davidopp** [comment]
(Also, sorry, the 55 MB I mentioned was from @yujuhong not @bprashanth  -- I got confused by some quoting in one of the replies in that thread.)

**Comment by wojtek-t** [comment]
@dchen1107 - also note that we can start with some bigger limit (like e.g. 100MB) if that helps. And we can improve it over time.
The only we really need now is just some limit, as this is causing constant test failures.

**Comment by gmarek** [comment]
@dchen1107 - it's very repetitive, in all flaky suites there's a failure on 'test/e2e/monitor_resources.go' test. Last run:
http://kubekins.dls.corp.google.com/view/Flaky/job/kubernetes-e2e-gce-flaky/8174/
```
"e2e-flaky-minion-k8gy": { "/kubelet": { Name: "", Timestamp: {sec: 0, nsec: 0, loc: nil}, CPUUsageInCores: 0.03773195913091254, MemoryUsageInBytes: 887040409, MemoryWorkingSetInBytes: 164274995, CPUInterval: 0, }, }
```

I believe that you can grab logs from any running cluster if needed.

**Comment by yujuhong** [comment]
> Could we set a memory limit for testing? We have the advantage of a known workload on a controlled environment, so we should be able to set limits more accurately. Would this make the testing environment too different from actual usage?

I think we should set a memory limit for kubelet. However, for testing alone, if kubelet uses more than what's the limit is allowed, it'd get restarted and the test may not have even detected the situation. We would need the test to check OOM events.

**Comment by gmarek** [comment]
Good point. If I'm not mistaken checking of oom events generally means parsing `/var/log/messages`, but that should be doable.

**Comment by gmarek** [comment]
@yujuhong I looked into what cAdvisor returns and 'memory usage' makes no sense whatsoever. Memory workingSetInBytes is virtual memory, and there's no way to get residual one through cAdvisor. I think that virtual memory is a good think to look at, but if you're 100% convinced that residual is for some reason way better, we need to add this option to cAdvisor.

cc @wojtek-t @rjnagal @kubernetes/goog-node

**Comment by vishh** [comment]
Existing cAdvisor issue to support RSS : [#975](
https://github.com/google/cadvisor/issues/975)

**Comment by timothysc** [comment]
@gmarek can't we close this now?
