### ISSUE TITLE
kube-up.sh creates garbage directories under ~/.kube when $KUBECONFIG lists multiple files

### ISSUE THREAD

**Issue by orfjackal** [kubernetes/kubernetes#17778]
Given the KUBECONFIG environment variable is set to `/Users/esko/.kube/config:/Users/esko/.kube/project-test:/Users/esko/.kube/project-prod`, when `./kubernetes/cluster/kube-up.sh` is run, then it creates a file and its parent directories called `/Users/esko/.kube/config:/Users/esko/.kube/project-test:/Users/esko/.kube/project-prod` which is not desired.

The problem is at https://github.com/kubernetes/kubernetes/blob/742243bb4adc9dc83411354566667259bcd7d7ee/cluster/common.sh#L58-L62 where it doesn't take into consideration that [$KUBECONFIG is specified as a list of paths](https://cloud.google.com/container-engine/docs/kubectl/config). It looks likes that code is a legacy from an earlier time, because elsewhere the code uses kubectl instead of editing the kubeconfig file directly, so those lines should probably be removed.

**Comment by asalkeld** [comment]
I can work on this.
