### ISSUE TITLE
Start ubuntu cluster in vagrant cannot customise flannel default interface in config-default.sh.

### ISSUE THREAD

**Issue by tongda** [kubernetes/kubernetes#17788]
When running k8s cluster in vagrant and bootstrap it using cluster/ubuntu scripts, I found that pods cannot access each other using flannel ip. After digging into this problem, I found that it is because flannel would look for default interface after start up. Since the default interface (`eth0`, ip is `10.0.2.15` in my case) is a *nat* interface in vagrant VM, flannel will use `10.0.2.15` as external interface. However, the correct binding should be `eth1`, which is the hostonly network interface, so that I have to modify the `/etc/default/flanneld` like this:

```
FLANNEL_OPTS="-iface=eth1 --etcd-endpoints=http://172.28.128.12:4001"
```

I think the `-iface` option should be configurable in config-default.sh.

**Comment by dalanlan** [comment]
Agreed. I think @MikeSpreitzer has a pr ongoing.
If he's not available for this (cla thing), i'll pick it up.

**Comment by MikeSpreitzer** [comment]
I have a fix but my company has not done the CLA yet.  That is in progress, but I do not know when it will complete.  Until then I can not contribute a PR.

**Comment by MikeSpreitzer** [comment]
It is not a difficult fix.  We are talking about issue #17013.

**Comment by tongda** [comment]
I was planning to fix this myself. Since @MikeSpreitzer is working, I will wait for it. ;)

**Comment by MikeSpreitzer** [comment]
@tongda No, do not wait for me, I do not know when my company will sign the CLA.

**Comment by dalanlan** [comment]
Feel free to fix it then:)
