### ISSUE TITLE
e2e flake: "KubeProxy should test kube-proxy"

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#17781]
Test failed with the following error:

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubeproxy.go:101 Expected : 1 to be == : 2

Example run:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9692/

@kubernetes/goog-cluster 

@mikedanese - can this be related to your recent changes?

**Comment by gmarek** [comment]
It actually failed 2/3 of last runs. I think we should move it to flaky suite if we won't be able to fix it today.

@ixdy @mikedanese

**Comment by wojtek-t** [comment]
@kubernetes/goog-testing

**Comment by wojtek-t** [comment]
This is extremely flaky in gke suite. Most recent failures:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9701/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9699/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9696/

**Comment by gmarek** [comment]
Moving the GKE version of this test to the GKE_flaky suite.

**Comment by gmarek** [comment]
@thockin - can you investigate or reassign?

**Comment by wojtek-t** [comment]
@mikedanese - can this  be related to moving kube-proxy to a pod? (the timing when it started failing was around when your PR was merged)

**Comment by mikedanese** [comment]
I'm not sure and haven't looked yet but I will look today,

**Comment by wojtek-t** [comment]
@mikedanese - thanks!

**Comment by mikedanese** [comment]
#16344 #17121 #15777 all went in around the same time and affect kubeproxy e2e test.

The test is relying on hitting all hostnames which is a valid assertion when we are using roundrobin proxy, but seems like it could be flaky after switching to iptables which is probabilistic. That's the only thing that statnds out to me but haven't tested this theory.

Do we have an exact date of when this test started flaking or was it "about 2 weeks ago"?

Does this only affect gke-ci?

**Comment by wojtek-t** [comment]
It affects all suites (including gce).

Regarding the exact data - we don't have exact run, because there were a bunch of issues around that time (including starting clusters).

**Comment by ihmccreery** [comment]
It's possible #17965 is related to this.

**Comment by ArtfulCoder** [comment]
I am looking into it..
It is not related to 17965.
The test breaks after we reduce the number of endpoints..

(the first half of tests work..)
I believe its the test change that was made recently is causing this.#15777
<https://github.com/kubernetes/kubernetes/pull/15777>

**Comment by mikedanese** [comment]
@ihmccreery i think its not related as artfulcoder said. That looks more like #17583

**Comment by wojtek-t** [comment]
The potential fix: #17995 has already been merged. We should verify in few days whether it fixed the problem and move the test back out of flaky if that's the case.

**Comment by wojtek-t** [comment]
It seems that #17995 fixed the problem. I will leave this issue open until Monday and if there won't be any issues, I will move it non-flaky suite and close this issue then.

**Comment by zmerlynn** [comment]
This needs to be cherry-picked into the `release-1.1` branch as well, please. http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-release-1.1/885/

**Comment by gmarek** [comment]
We should cherry-pick #17995 to v1.1, as it failed in http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-1.1/937/

**Comment by gmarek** [comment]
Actually it isn't fixed. It just failed in gke-ci: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/10073/

**Comment by gmarek** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/1368/

**Comment by thockin** [comment]
please open new issues with new links if this pops up again.

@ArtfulCoder we need to prio this if it comes up
