### ISSUE TITLE
Error deploying to Azure

### ISSUE THREAD

**Issue by ShadySQL** [kubernetes/kubernetes#17789]
Upon running the command to build the cluster, I get an error: http://pastebin.com/wVhA91f4

**Comment by davidopp** [comment]
@errordeveloper any thoughts on this?

**Comment by tayzlor** [comment]
I got the same error. I didn't debug the root cause yet, but if I change the region to "North Europe" it provisions the cluster properly.

**Comment by ShadySQL** [comment]
How can I change the region? Could you pear share the process if you don't mind please?

**Comment by tayzlor** [comment]
easiest way is to do - 

```
export AZ_LOCATION="North Europe"
```

or change the default value in https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/azure/lib/azure_wrapper.js#L151

**Comment by errordeveloper** [comment]
@tayzlor thanks for more info here! Quick question to you, do you have a UK account or it's somehow belongs US or some other place? @abuehrle had a similar problem with a US-based account, while my UK account worked fine last time I tested (not very long ago).

**Comment by tayzlor** [comment]
I can't see anything specific that says my account is somehow tied to a region on my account setting, so yeah the error is a bit odd, but then again Azure is a bit odd generally. I created the account in the UK if that helps and its an enterprise MSDN account.

**Comment by abuehrle** [comment]
Hi Graham, 

I did run into a similar problem, and I ran the following to fix this issue: 

If a location error is returned after running ./create-kubernetes-cluster.js, return a list of available locations by running:

azure vm location list
Choose a suitable location, and then set the location variable by running:

export AZ_LOCATION=‘<your-location>’
This is from the guide we have in github which is located here: 

https://github.com/weaveworks/weave-kubernetes-coreos-azure <https://github.com/weaveworks/weave-kubernetes-coreos-azure>

**Comment by tayzlor** [comment]
Makes sense, if I run tha tI get the following - 

```
info:    Executing command vm location list
+ Getting locations
data:    Name
data:    ----------------
data:    South Central US
data:    Central US
data:    East US 2
data:    North Europe
data:    Southeast Asia
data:    East Asia
data:    Japan West
info:    vm location list command OK```

Which would explain perhaps why 'West Europe' was not working for me either. I've added a PR to update the docs to this effect.

**Comment by roberthbailey** [comment]
Obsoleted by https://github.com/kubernetes/kubernetes/pull/41672.
