### ISSUE TITLE
Possible to have verify-codecgen fail after running update-codecgen

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#17793]
See #6255 for an example branch where this happens.  One thing I noticed while investigating this is that the verify-script creates a fresh GOPATH in a temp dir, installs godep there, and builds codecgen there, then uses _that_ codecgen to verify the generated files.  I updated codecgen on my system gopath to ensure I wasn't having some kind of mismatch (even though update- runs codecgen using godep).

@lavalamp @wojtek-t 
cc @anish @tmrts @kubernetes/rh-cluster-infra

**Comment by anish** [comment]
Seen with pull #16877 as well.

**Comment by pmorie** [comment]
@kubernetes/goog-csi

**Comment by pmorie** [comment]
I cannot reproduce this in our branch for #6255 after rebasing on master this morning.

**Comment by pmorie** [comment]
I'm closing this since neither @anish or I can reproduce it.

**Comment by anish** [comment]
Same here

**Comment by wojtek-t** [comment]
@pmorie - the real issue was somewhere else.
It was fixed by:
https://github.com/wojtek-t/kubernetes/commit/20cf0609dd591de412cc56011d36db31466f6857

**Comment by pmorie** [comment]
@wojtek-t cool, thanks for the info
