### ISSUE TITLE
outdated references in Getting Started guide for Ubuntu and Calico

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#17794]
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu-calico.md says to download v1.1.1 but now v1.1.2 is the latest.

[erroneous complaint deleted here]

**Comment by davidopp** [comment]
@MikeSpreitzer any chance you could send a PR that fixes this?

**Comment by MikeSpreitzer** [comment]
Not until the relevant execs at my company sign the CLA.  This is in progress but I can not tell you to hold your breath.

**Comment by MikeSpreitzer** [comment]
Here is another thing: ubuntu-calico.md refers to calico-kubernetes-master/config/master/kubernetes-master.manifest but the master archive now includes no manifest at all.  However, it _does_ include systemd unit files for the api server, controller manager, and scheduler; I suppose the correct instructions would install them like the kubelet --- except that I thought the point of installing kubelet was to use it rather than systemd to run those three agents.

**Comment by dalanlan** [comment]
This issue could occur to almost all of the platforms, which may not harm much though.
