### ISSUE TITLE
Fix l7 controller watch on namespaces

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#17805]
Observed odd flakyness when watching Ingresses from the controller scoped to a namespace. Need to get to the bottom of it, but I suspect it's a bug higher up in the stack. For now it isn't that important because the controller watches all namespaces.

**Comment by ihmccreery** [comment]
Ping @bprashanth.  Shouldn't this issue be `kind/flake`?  And shouldn't the test under consideration be in the `FLAKY` suite?  Right now, there's a test in `PARALLEL_SKIP` that references this issue.

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc
