### ISSUE TITLE
Remove API versioning info from versioning.md

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#17807]
@bgrant0607, can you please add the information you think is necessary to [versioning.md](https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md)?  There's some info about how API versioning relates to releases, but it should probably be expanded?  (Or perhaps this information already exists elsewhere, and should just be linked in.)  (Came up while I was writing #17806.)

**Comment by bgrant0607** [comment]
We need to decouple API versioning from release versioning. We're going to have multiple API groups at different versions.

cc @lavalamp

**Comment by lavalamp** [comment]
Most likely, for a given release, we will "bless" a *set* of API group/versions as the default/recommended ones to use. Occasionally, there will be upgrade instructions to prepare for future releases.

As Brian says, there will not be any particular relationship between releases and api group/versions that will be predictable in advance, other than api versions won't go backwards.

**Comment by ihmccreery** [comment]
SGTM.  Can you please update `versioning.md` as such?  Right now there's a bunch of erroneous information in that file, based on what you've described above.

If you want versioning info for the APIs to live elsewhere, would you mind just linking from that doc?

**Comment by bgrant0607** [comment]
Done, finally
