### ISSUE TITLE
Using flocker, rc cann't relate to dataset?

### ISSUE THREAD

**Issue by ttllyy** [kubernetes/kubernetes#17815]
k8s: 1.1.2
flocker:1.7.1
backend: zfs

node cluster: node1, node2

uft-flocker-volumes --control-service=xx.xx.xx.xx --control-port=4523 create -m name=my-vol-demo1 -s 5G --node=node1
Create dataset successful.

Add index.html file to node1: /flocker/1172eee5-35e1-406c-9ad4-863609b51291.default.0131d9cf-5dbd-46d7-ae35-4f2fb3b126d1

Create automatic /flocker/1172eee5-35e1-406c-9ad4-863609b51291.default.0131d9cf-5dbd-46d7-ae35-4f2fb3b126d1 and index.html on node2.

create rc:
###### ###########rc.yml

apiVersion: v1
kind: ReplicationController
metadata:
  name: flocker-web1
  labels:
    name: flocker-web1
spec:
  replicas: 1
  selector:
    name: flocker-web1
  template:
    metadata:
      labels:
        name: flocker-web1
    spec:
      containers:
      - name: flocker-web1
        image: nginx:latest  
        ports:
        - name: flocker-web
          containerPort: 80  
        volumeMounts:
        - name: www-root
          mountPath: "/usr/share/nginx/html"
      volumes:
      - name: www-root
        flocker:  
          datasetName: my-vol-demo1
###### ###########rc.yml

create pod on node1. And curl pod's ip, dispaly index.html.

I delete pod, and rc creates automatic pod on node2.
But node2 create new dir /flocker/b083f1ba-75b0-41dd-8b2a-33bd4e624e81.default.0131d9cf-5dbd-46d7-ae35-4f2fb3b126d1. 
docker inspect xxx on node2:
            "Source": "/flocker/b083f1ba-75b0-41dd-8b2a-33bd4e624e81.default.0131d9cf-5dbd-46d7-ae35-4f2fb3b126d1",
            "Destination": "/usr/share/nginx/html",

Why new pod don't mount  /flocker/1172eee5-35e1-406c-9ad4-863609b51291.default.0131d9cf-5dbd-46d7-ae35-4f2fb3b126d1 on node2?

Flocker dataset cann't relate to rc?

**Comment by ttllyy** [comment]
Rc create pod, pod name contain rc name and hash str. Create new pod, so pod name isn't same to pre pod.  Flocker volume is bind to pod name?

**Comment by fgrzadkowski** [comment]
@kubernetes/goog-cluster

**Comment by ttllyy** [comment]
datails: https://github.com/ClusterHQ/flocker/issues/2234

**Comment by stmcginnis** [comment]
We may want to close this now given the current state of Flocker.
