### ISSUE TITLE
how to join the the sig-scale slack?

### ISSUE THREAD

**Issue by HardySimpson** [kubernetes/kubernetes#17811]
I tried but it refuse my email address,is there any limit?

![aa.png](http://photo.yupoo.com/qzone3732368368/F8aKtAbD/medish.jpg)

**Comment by fgrzadkowski** [comment]
CC-ing some of our slack admins - @bgrant0607 @goltermann @jbeda

**Comment by goltermann** [comment]
To access our Slack team, you have to be "invited".  We have a page where you can generate that self-service invite for your email address at http://slack.kubernetes.io/

**Comment by HardySimpson** [comment]
thanks, already in with my fellows from Huawei!
