### ISSUE TITLE
v1.1 getting start guide ubuntu document should be update

### ISSUE THREAD

**Issue by JeffChien** [kubernetes/kubernetes#17820]
root cause describe in https://github.com/kubernetes/kubernetes/issues/14474, fixed pr https://github.com/kubernetes/kubernetes/pull/14478 in the v1.2 branch which is in alpha stage, the document need to be update to notify user remove `DenyEscalatingExec`.

**Comment by dalanlan** [comment]
As you pointed out, it's been removed in #14478. You won't suffer this from HEAD.

**Comment by JeffChien** [comment]
Yes, the problem is gone in HEAD. But it doesn't make sense, HEAD and v1.1, a new-comer will prefer a stable release to getting start. it is better to address the issue and solution in the document.

**Comment by dalanlan** [comment]
This is a legacy problem. Ref [#14474(comment)](https://github.com/kubernetes/kubernetes/issues/14474#issuecomment-142929834).
It's a cherry pick issue.
