### ISSUE TITLE
Merge bot should not rerun tests in case of verify-X failure.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#17834]
They are not flaky.

cc @a-robinson @ixdy @brendandburns @wojtek-t

**Comment by wojtek-t** [comment]
Either I don't understand this issue, or I don't agree.
Can you please clarify (e.g. by giving an example)?

**Comment by gmarek** [comment]
Currently in case of e.g. a failure in `verify-gofmt.sh` merge bot reruns the test, assuming the flake. I believe that those tests are not flaky.

**Comment by gmarek** [comment]
OK, I made an error in the title;)

**Comment by wojtek-t** [comment]
OK - thank makes more sense :)

**Comment by ixdy** [comment]
Can you give an example of where this is occurring? The merge bot will automatically re-run tests periodically to ensure that test results are fresh, but I don't think it retries automatically on flakes.

@eparis

**Comment by eparis** [comment]
The bot should never re-run a failed test.  It will re-run tests which passed if the PR has LGTM every 48 hours...   Do you have an example of a PR where the bot did something wrong?

**Comment by gmarek** [comment]
It's not wrong per se. It's overly conservative, I can't recall in which PR it was but I had an impression that merge bot rerun missed 'unit/integration' tests (which include linter checks etc.). OTOH merge bot is behaving strangely lately: #17831

**Comment by eparis** [comment]
#17831 I have no idea why travis wasn't running...  obviously the bot didn't either   :)

Not sure what i can do to help...

**Comment by wojtek-t** [comment]
@eparis - I wouldn't worry about this one - those were some travis-github integration issues.

**Comment by ihmccreery** [comment]
Closing as obsolete; please reopen with an explanation if you disagree.
