### ISSUE TITLE
[DOCS] Public IPs of services on AWS Cluster

### ISSUE THREAD

**Issue by sils** [kubernetes/kubernetes#17837]
Hi, I'm just trying to set up a sample application using kubernetes on AWS. It's not obvious from the docs how I can get the public IP adress of the newly created service.

Could you add that to the tutorial? I've been googling for this quite usual usecase for quite some time without really good results, I think it would really be helpful.

**Comment by sils1297** [comment]
FWIW KubeDNS API gives 

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kube-dns\"",
  "reason": "ServiceUnavailable",
  "code": 503{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kube-dns\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

**Comment by davidopp** [comment]
@justinsb

**Comment by davidopp** [comment]
@mikedanese
