### ISSUE TITLE
Consider adding a Pod phase called PodAssigned

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#17849]
It would go between PodPending and PodRunning. It means the Pod has a NodeName but has not yet been acknowledged as started by the Kubelet.

I know there's generally strong opposition to adding new Phases but I think this would be very useful and it's easier to do it now than a year from now when it's even more obvious how useful it is. I'm not sure it causes a significant backward compatibility problem because every Pod would still go through PodPending and PodRunning. (I realize it causes a backward compatibility problem for people who wrote code that expects exactly the phases we currently have, and only those phases.)

In general even if we are reluctant to add new phases, surely there must be some way we can add them; it doesn't seem reasonable to lock ourselves into exactly the phases we have forever. I guess we could say we have to wait until we rev to v2 of the API, but it would be nice if we could make minor changes like this without having to wait for a major API version change.

@bgrant0607

**Comment by bgrant0607** [comment]
Adding new phases would break backward API compatibility. We're never going to do that.

See #7856.

Either close this issue or re-title it to reflect what you're trying to accomplish.

**Comment by bgrant0607** [comment]
Also related: #14181, #1899, #12143 (move printPodBase reason summarization to kubelet)

**Comment by smarterclayton** [comment]
Is checking spec.nodeName empty really that hard?  Creating a new condition for it seems like it creates more opportunities for confusion, because a user can directly set nodeName.  Do we not have a condition for node accepting pod?

**Comment by davidopp** [comment]
I'll continue the discussion on #7856 which @bgrant0607 mentioned.
