### ISSUE TITLE
Update doc/devel/scheduler.md to explain all the supported extension approaches

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#17857]
Like
https://github.com/kubernetes/kubernetes/issues/16845#issuecomment-160031718

**Comment by davidopp** [comment]
Actually, what we need is a doc about extensibility in general -- all the places where you can insert custom logic and/or replace the default logic. We could have one doc with an overview, that points to separate docs about each of the extensibility points.
- scheduler
- write your own controller
- ThirdPartyResource
- API server delegation
- admission controllers
- MetadataPolicy (when it exists)

I'm probably forgetting some....

cc/ @lavalamp

**Comment by lavalamp** [comment]
I have a slides presentation on this that I should share. There's like 3x more things than in the above list.

**Comment by lavalamp** [comment]
This should go in its own doc though. The scheduler doc could link to it. Scheduler extensibility is a small part of our extensibility story.
