### ISSUE TITLE
DownwardAPIVolumeSource.Items should be called Files in V2 API

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#17859]
The downward API volume source established a pattern of using `Items` for the array variable for a list of projections into a volume.  It should be called `Files` instead, but it looks like we are going to follow the existing pattern in #17554 for consistency, so this volume should also be refactored in the next version of the pod API.

...as requested by @thockin here: https://github.com/kubernetes/kubernetes/pull/17554#discussion_r45832617

**Comment by resouer** [comment]
So do you mean this should be fixed after #17554 was in?

**Comment by thockin** [comment]
So for v1 both DAPI and Config should use "Items" and v2 should be "Files"

**Comment by bgrant0607** [comment]
Ref #8190
