### ISSUE TITLE
Scheduler external API objects must use int32 or int64

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#17858]
As of #17353 this is now the API default.

**Comment by davidopp** [comment]
I assume you're talking about the types.go files under
https://github.com/kubernetes/kubernetes/tree/master/plugin/pkg/scheduler/api ?

**Comment by smarterclayton** [comment]
Yes, although in this case it should be the v1.  Internal doesn't have
to be forced to 32.

**Comment by jayunit100** [comment]
wait, i beleive in a conversation the other day @liggitt mentioned api int fields should be 32 , not 64?  I could be misremembering though.

**Comment by smarterclayton** [comment]
It doesn't have to be, it should be 32 or 64.  Code not in api groups can
continue to use int, although it's better to pick a size if you get your
input primarily from an API.

**Comment by jayunit100** [comment]
ok, so specifically, just to be fully explicit: 

i think we are saying external must be int32/64 to avoid ambigueties in the goreflect related generation that leads to inconsistent int32/int64/uint's for the same types - which ultimately will cause a *failure to compile* during generation...  is that accurate ?

**Comment by smarterclayton** [comment]
Yes.  External must be int32/64 because proto has no concept of generic
int.  Internal should be int32/64, and internal code using internal types
should prefer 32/64.

This is in API conventions (and if not well explained should be updated).

On Dec 16, 2016, at 2:20 PM, jay vyas <notifications@github.com> wrote:

ok, so specifically, just to be fully explicit:

i think we are saying external must be int32/64 to avoid ambigueties in the
goreflect related generation that leads to inconsistent int32/int64/uint's
for the same types - which ultimately will cause a *failure to compile*
during generation... is that accurate ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17858#issuecomment-267674275>,
or mute the thread

**Comment by liggitt** [comment]
External int64 fields that allow/use > 52 bits of precision will run into all sorts of problems with JSON libraries that use doubles to represent JSON numbers
