### ISSUE TITLE
Correct the expression of nodecontroller for the sync loop in admin/node.html

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#17860]
The expression right now is: "Node controller has a sync loop that creates/deletes Nodes from Kubernetes based on all matching VM instances listed from the cloud provider." But actually node controller does not create nodes from cloudprovider. Please refer to https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go

This issue was logged for the question with answer given: https://github.com/kubernetes/kubernetes/issues/17726.

So the document expression should remove "creates" from the sentence.

**Comment by davidopp** [comment]
Can we close this now that #17924 was merged?

**Comment by xinxiaogang** [comment]
@davidopp Sure, close this issue. Thanks.
