### ISSUE TITLE
aws deploy script: cannot download tar from s3 by a public url

### ISSUE THREAD

**Issue by themez** [kubernetes/kubernetes#17868]
The download script doesn't work.

```
#cluster/aws/util.sh
SALT_TAR_URL="${s3_url_base}/${AWS_S3_BUCKET}/${salt_tar_path}"
```

```
#download-release.sh
download-or-bust "$SALT_TAR_URL"
```

the file download would be an xml like this

```
<Error>
<Code>UnauthorizedAccess</Code>
<Message>You are not authorized to perform this operation</Message>
<RequestId>C5C90406ED8D8B7A</RequestId>
<HostId>
mDkmrFFmVNfrkRT3ix2GMQQ9ky6mAk6iv7gHtDqRtE/DgZBvub2lLJ+MozNwFLH6
</HostId>
</Error>
```

**Comment by fabioy** [comment]
@justinsb Could you help? Thanks.

**Comment by themez** [comment]
I just found out that ICP recordal is needed before making S3 files public in China region(http://docs.amazonaws.cn/en_us/aws/latest/userguide/accounts-and-credentials.html). That should be the problem.

**Comment by justinsb** [comment]
I think this is a documentation issue.  We could also make the bucket not-public and grant access via IAM.

**Comment by goltermann** [comment]
bringing a few P2 doc bugs back in the 1.3 milestone

**Comment by goltermann** [comment]
This is an issue marked v1.3 and kind/documentation.  Can you get it fixed up this week?

**Comment by justinsb** [comment]
We're not going to be making further changes to kube-up.  kops users shouldn't hit _this_ problem (although I think kops also has problems in cn-north-1 e.g. because of the lack of Route530.  We'll continue to work through the cn-north-1 restrictions in kops.  Closing.
