### ISSUE TITLE
Running status pod have no ip

### ISSUE THREAD

**Issue by zhengguoyong** [kubernetes/kubernetes#17870]
When create pod with a special but not exist NetworkPlugin.  It will fail when Network setup pod because the networkPlugin is not exist. As the pod cannot join up network, it has no ip.
What i expect of the pod state is Pending, but when i describe it , it shows Running,
I think it is not suitable and should be fixed.
@yujuhong  How do you think?
cc @judytong
[quark@k8s-quark-master kube]$ kubectl describe pod test-gzj2g 
Name:                           test-gzj2g
Namespace:                      default
Image(s):                       ubuntu
Node:                           192.168.20.2/192.168.20.2
Start Time:                     Fri, 27 Nov 2015 02:45:50 +0000
Labels:                         app=test
Status:                         Running
Reason:
Message:
IP:
Replication Controllers:        test (2/2 replicas created)

**Comment by dchen1107** [comment]
@zhengguoyong You raised a really interesting point here. Based on our initial description of pod phase: https://github.com/kubernetes/kubernetes/blob/22e527fe2577e2ee29d557681ee388b2d10b91a6/docs/user-guide/pod-states.md#pod-phase

The pod is indeed at Running state already. But do we allow pod at running state without IP? If that is not allowed, should we leave pod at Pending state with proper reason or error? Scan through the proposed pr #17893, and looks like it is toward this direction. Or we plan to have pod without IP in a long run?  cc/ @bgrant0607

**Comment by bgrant0607** [comment]
I'd create an event and fail the pod.

cc @thockin

**Comment by dchen1107** [comment]
Ok, sounds like we agree on that the PodIP is prerequirement of Pod's Running phase besides of all of the containers have been created. 

cc/ @kubernetes/goog-node

**Comment by yujuhong** [comment]
Kubelet currently does not distinguish errors, i.e., it doesn't know whether an error is permanent or transient, and it would retry eventually. If we are certain that some errors are not recoverable, we can fail the pod. Can we tell clearly that this is the case (permanent error)?

**Comment by dchen1107** [comment]
Kubelet already failed pods on events: host port conflicts, insufficient free cpu and memory, and disk today, so failing a pod on missing plugin is ok. 

But @yujuhong has a good point. Proposed pr only detects networkPlugin error, not necessary a missing plugin issue. On a given transient issue, we should leave pod at pending state, and next sync loop will retry.

**Comment by judytong** [comment]
@yujuhong @dchen1107 @zhengguoyong I think there are two cases to discuss: 1) what should pod status be if a network plugin is missing; 2) what should pod status be if a network plugin is not working and not assigning pod IP correctly? In my opinion, pod should be failed in both two cases.

**Comment by yujuhong** [comment]
@judytong, I am not sure how network plugin works, so ignore me if I am not making sense.

Would it be possible to have a transient error when determining the IP address? For example, if `docker ps` fails, it does not mean that there are no containers running. If transient error if possible and is indistinguishable from actual errors, we should not fail the pod.

**Comment by judytong** [comment]
@yujuhong  I do agreed what you said about transient error. But there still remains something to clarify. 
@zhengguoyong 
However, determining IP may return both transient errors or permanent errors. It depends on how you deal with interface "Status" in your network plugin. When error occurs in setting up a infrastructure container, for example, IP address is not assigned correctly, nowadays we still think this infra container is OK and pod is still running. This way, infra container will not be recreated, which is not what we expect.

**Comment by thockin** [comment]
I'm unclear on how this ends up "running":
 pkg/kubelet/dockertools/manager.go calls networkPlugin.SetUpPod(), which
can fail.  If it fails, we skip the pod.

**Comment by yujuhong** [comment]
> I'm unclear on how this ends up "running":
>  pkg/kubelet/dockertools/manager.go calls networkPlugin.SetUpPod(), which
> can fail.  If it fails, we skip the pod.

Good question. @zhengguoyong @judytong, shouldn't `networkPlugin.SetUpPod()` return error in this case?

**Comment by judytong** [comment]
@thockin @yujuhong @zhengguoyong @linzichang  
Actually, when I was adding our own network plugin, it returns an error in networkPlugin.SetUpPod(), but I can only see this error in an event. When I get this pod's status, it is still running. Failure of network plugin will not change pod's status. @zhengguoyong's methods will at least let us know the pod ip is not ok no matter it is because of error in networkPluin,SetUpPod() or due to transient error in networkPlugin.Status(). Below is the output:

![default](https://cloud.githubusercontent.com/assets/14867769/11580403/2049214a-9a72-11e5-841b-b7ff45a6957c.PNG)

**Comment by thockin** [comment]
Can you confirm this at head?  It's supposed to be a pod-fatal error, and
that is what I saw last week.

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/blob/release-1.1/pkg/kubelet/dockertools/manager.go#L1863

**Comment by judytong** [comment]
@thockin  It has been solved at branch master :), seen as
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1874

But I think we can still remain pod's status pending if networkPlugin.Status() returns an error in determining the pod ip.

**Comment by zhengguoyong** [comment]
Oh, yes! the code we use is a bit old.  I agree with @judytong 
If networkPlugin.SetUpPod() success but fail when determining the IP address. In this case i this we can have a transient error just as @yujuhong opinion.
So maybe we should leave pod at pending state, and determining the IP address next sync loop.
@dchen1107  @bgrant0607

**Comment by dchen1107** [comment]
sgtm. Thanks for looking into the issue, everyone. @zhengguoyong please close the pr and the issue. Thanks!

**Comment by zhengguoyong** [comment]
i mean we should attention the err networkPlugin.Status() (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L330), if we agnore the err, the pod ip may not right.
@dchen1107

**Comment by bprashanth** [comment]
@dchen1107 has context to judge 1.2 worthiness

**Comment by dchen1107** [comment]
Status on this one?

**Comment by yujuhong** [comment]
> Status on this one?

Commented the PR. I think the PR will not do what it intends to do and will leave the pod in the pending state with no new informaiton.

**Comment by krmayankk** [comment]
any update on this ?  The question related to this i have is , can a pod ip change and would that result in pod transitioning from running to pending again or is there a way to detect such a change?
