### ISSUE TITLE
Add monitoring of log generation rate to e2e tests

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#17879]

**Comment by ihmccreery** [comment]
@gmarek is this done?  Anything else need to happen?  If so, can you please clarify a bit what the workplan is?

**Comment by gmarek** [comment]
It's done-ish. We tried to enable it today, but test failed because of lack of file descriptors. I'll look into it given soon.

**Comment by gmarek** [comment]
Last (hopefully) PR in effort is #19162. Closing.
