### ISSUE TITLE
getting started ubuntu guide is out of date

### ISSUE THREAD

**Issue by paultag** [kubernetes/kubernetes#17887]
http://kubernetes.io/v1.1/docs/getting-started-guides/ubuntu.html

```
$ cd kubernetes/cluster/ubuntu
$ ./build.sh
```

Appears to be not super usable anymore -- cc @resouer (you're the only public member of @ZJU-SEL, the folks marked as the maintainer)

**Comment by resouer** [comment]
Yeah, it has been removed in HEAD: https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

Seems v1.1 doc need be update, I'll follow this up. Thanks for reporting.

**Comment by niceysj** [comment]
When I get fixed guide???

**Comment by bgrant0607** [comment]
It's unlikely we'll update the 1.1 docs significantly at this point. Updates will be reflected in the 1.2 docs.

@resouer Neither the getting-started guide nor the cluster/ubuntu directory appears removed in HEAD:
https://github.com/kubernetes/kubernetes/tree/master/cluster/ubuntu

**Comment by Pensu** [comment]
@bgrant0607 I want to pick this up. Will send a PR.

**Comment by bgrant0607** [comment]
Thanks @Pensu

**Comment by spzala** [comment]
@paultag hi, it seems like the issue is fixed under https://github.com/kubernetes/kubernetes/pull/20801 If you can please verify, and if it looks good can you please close this issue? Thanks!

**Comment by paultag** [comment]
Cool, thanks!

**Comment by spzala** [comment]
Thanks @paultag !!
