### ISSUE TITLE
create certificate error

### ISSUE THREAD

**Issue by shilpapadgaonkar** [kubernetes/kubernetes#17889]
Hello,
I am following the ansible installation on fedora23.
This fails at task
TASK: [kubernetes | Run create cert script on master] *************************

I have openssl installed on master, i also have tried the solution https://github.com/jeffbean/kubernetes/commit/ca8fb7cb4ec9c8f8c536abb65898fa2aea4ec0e7

However the problem still persists

Here are my logs ( I have removed >/dev/null 2 from the script to get more details)

Could you please let me know what is the problem here?

Thanks.

LANG=C HTTP_PROXY='"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"' CERT_DIR=/etc/kubernetes/certs MASTER_NAME=kube-master.example.com LC_CTYPE=C DNS_DOMAIN=cluster.local MASTER_IP=172.16.56.0,IP:172.16.56.1,IP:xx.xx.xx.xx,IP:172.30.15.38 CERT_GROUP=kube-cert HTTPS_PROXY='"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"' SERVICE_CLUSTER_IP_RANGE=10.254.0.0/16 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1448661738.15-275644033496308/command; rm -rf /root/.ansible/tmp/ansible-tmp-1448661738.15-275644033496308/ >/dev/null 2>&1'"'"''
failed: [kube-master.example.com] => {"changed": true, "cmd": ["/usr/libexec/kubernetes/make-ca-cert.sh"], "delta": "0:00:01.213574", "end": "2015-11-27 22:00:11.022303", "rc": 2, "start": "2015-11-27 22:00:09.808729", "warnings": []}
stderr: Generating a 2048 bit RSA private key
...............+++
..............................................................+++
writing new private key to '/tmp/kubernetes_cacert.txYH5f/easy-rsa-master/easyrsa3/pki/private/ca.key'
-----
string is too long, it needs to be less than  64 bytes long
problems making Certificate Request

Easy-RSA error:

Failed to build the CA

Easy-RSA error:

Missing expected CA file: ca.crt (perhaps you need to run build-ca?)
Run without commands for usage and command help.

Easy-RSA error:

Missing expected CA file: ca.crt (perhaps you need to run build-ca?)
Run without commands for usage and command help.

Easy-RSA error:

Missing expected CA file: ca.crt (perhaps you need to run build-ca?)
Run without commands for usage and command help.
=== Failed to generate certificates: Aborting ===

**Comment by yuandan** [comment]
@shilpapadgaonkar , may I know how you resolve this issue? I'm install kubernetes via Fedora(Ansible) and encounter the same issue you mentioned above. Look forward to your reply and thanks in advance!

**Comment by v1k0d3n** [comment]
@yuandan this was repaired by this change (6 days ago). repull your local copy of the repo...

https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes/files/make-ca-cert.sh

**Comment by andresetevejob** [comment]
@shilpapadgaonkar , how have you solved this error?
