### ISSUE TITLE
Unable to mount AWS EBS volume for persistence storage (v1.1.2)

### ISSUE THREAD

**Issue by sachingharge** [kubernetes/kubernetes#17882]
Hi Team,

I am trying to mount EBS volume as persistent disk for storage but it failed with below reasons:
Using latest stable release: v1.1.2 for cluster using CoreOS + AWS

FailedMount Unable to mount volumes for pod "test-ebs_default": Cloud provider does not support volumes
Error syncing pod, skipping: Cloud provider does not support volumes

Below Block in Pod file:
    # This AWS EBS volume must already exist.
    awsElasticBlockStore:
      volumeID: aws://us-west-1a/vol-da5ef222
      fsType: ext4

Do we support EBS volume for persistence storage with AWS  or not yet?
Please let me know if you need any more information on this.

Thanks!

**Comment by mikesplain** [comment]
@sachingharge Having been down this path: are you sure you've specified `cloud-provider` on the required kube components (e.g. api server, controller manager, and kubelets)?

**Comment by sachingharge** [comment]
@mikesplain, Thanks for reply.
Just to mention, cluster has created using cloudformation template however I can confirm that kube-apiserver and kube-controller-manager created using --cloud-provider=aws.

Shall I missing something here?

**Comment by mikesplain** [comment]
@sachingharge I would check your instance profiles to make sure they have the right permissions and check against what is setup in the the latest k8s release.

**Comment by fabioy** [comment]
PR #17958 may be related. Also see http://stackoverflow.com/questions/32594632/unable-to-mount-amazon-web-services-aws-ebs-volume-into-kubernetes-pod.

If this addresses the problem, please close this issue. 

Thanks.

**Comment by zmerlynn** [comment]
cc @justinsb @brendandburns

**Comment by sachingharge** [comment]
@fabioy, Yes, I will try to verify once fix is available.
I guess fix still not yet released?

**Comment by urashidmalik** [comment]
Issue persists. Validated on 1.1.2. (Cloudformation)

Tried on v1.1.2 getting same error

ERROR
![image](https://cloud.githubusercontent.com/assets/173068/11953232/6e570142-a853-11e5-92c8-1c8e2a4040cd.png)
Version
![image](https://cloud.githubusercontent.com/assets/173068/11953270/b5740264-a853-11e5-8867-23dadd003ff3.png)
POD
![image](https://cloud.githubusercontent.com/assets/173068/11953282/c251fb9e-a853-11e5-8394-e873180e5334.png)
CLOUD-PROVIDER (Control Machine)
![image](https://cloud.githubusercontent.com/assets/173068/11953299/e0b6b87c-a853-11e5-9213-7ba209ca4c49.png)
CLOUD-PROVIDER (Worker Machine)
![image](https://cloud.githubusercontent.com/assets/173068/11953309/fa02f2e6-a853-11e5-85da-733e51bd53f0.png)
