### ISSUE TITLE
Kubemark testing can save time by not creating/deleting master instance every time

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#17890]
I successfully tried to run kubemark by reusing the same master instance. This save me a lot of time in running kubemark testing.

I basically did the following things:
- deleting everything the same as `stop-kubemark.sh` except deleting the master machine instance
- resetting master machine
- resetting etcd (I run separate instances)
- creating everything the same as `start-kubemark.sh` except creating the master machine

Currently my scripts are really messy. But I would like to raise this discussion since it saves a lot of time.

@gmarek @wojtek-t @spiffxp

**Comment by wojtek-t** [comment]
I'm fine with that, modulo that I would like to ensure that not data can be migrated between runs.
So in other words, I would like to:
1. stop all components (etcd, apiserver, ...) in stop-kubemark
2. delete the PD where all the data is stored
3. recreated all the components from scratch in start-kubemark (including creating PD to store the data)

**Comment by wojtek-t** [comment]
BTW - thanks for looking into it @hongchaodeng - it would be great if you could do it.

**Comment by hongchaodeng** [comment]
> 2. delete the PD where all the data is stored

This is something I'm not sure about and raise the discussion for. I assumes all states are stored in etcd, and other components are stateless. That says, if I can clean up etcd (`rm data-dir`), restarting all other components should look like fresh start, right?

Deleting PD also consumes a lot of time as well.

**Comment by gmarek** [comment]
@hongchaodeng I believe that you're right and whole state is in etcd.

**Comment by wojtek-t** [comment]
Yup that's true.
The only persistent state is stored in etcd.

It's not true that other components are stateless, because they accumulate a bunch of state in memory - but restarting them clears their state.

**Comment by gmarek** [comment]
To make it clean they are not *completely* stateless in a sense that they'll be working exactly the same after restart, as they'll need to rebuild cache etc., but they are stateless in a sense that even if they'll loose whatever state they have, their semantics will still be the same (but they may work a bit slower in the beginning)

**Comment by davidopp** [comment]
@hongchaodeng are you interested in working on this? If so we can assign it to you.

**Comment by hongchaodeng** [comment]
@davidopp 
Yes. I have the changes working already. It wouldn't be hard to make some cleanup and put more generic changes. Thanks!

**Comment by hongchaodeng** [comment]
Closing this. Not interested anymore
