### ISSUE TITLE
kubectl desribe objects including garbage data

### ISSUE THREAD

**Issue by jay-lau** [kubernetes/kubernetes#17899]
Not only pod, but also others such as node, rc etc have same issue.

#kubectl  --server=xxx:8888 describe pods
Name:                           nginx1
Namespace:                      default
Image(s):                       nginx
Node:                           ma1demo4.eng.platformlab.ibm.com/9.21.58.24
Start Time:                     Sat, 28 Nov 2015 02:21:56 -0500
Labels:                         app=nginx
Status:                         Running
Reason:
Message:
IP:                             172.17.0.29
Replication Controllers:        <none>
Containers:
  nginx:
    Container ID:       docker://906296c7bd0779ad7f087a0fd8ebd743fd3839873b6667d2b384dddd62b07f9d
    Image:              nginx
    Image ID:           docker://5c82215b03d10884d98e0c074a69881e7428484c47855d49863233297f86fd9a
    State:              Running
      Started:          Sat, 28 Nov 2015 02:22:05 -0500
    Ready:              True
    Restart Count:      0
    Environment Variables:
Conditions:
  Type          Status
  Ready         True 
No volumes.
Events:
  FirstSeen     LastSeen        Count   From                                            SubobjectPath                           Reason                  Message
  鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€   鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€        鈹€鈹€鈹€鈹€鈹€ 鈹€鈹€鈹€鈹€                                            鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€                              鈹€鈹€鈹€鈹€鈹€鈹€                      鈹€鈹€鈹€鈹€鈹€鈹€鈹€
  24m           24m             4       {scheduler }                                                                            FailedScheduling        Error scheduling: No suitable offers for pod/task

**Comment by lavalamp** [comment]
Well, that's unexpected. Can you do `kubectl --server=xxx:8888 get events -o yaml` so we can see the object that triggered that behavior?

**Comment by jay-lau** [comment]
describe events works.

root@ma1demo3:~/gyliu/conf/k8s# kubectl --server=xxxx:8888 describe pods
Name:                           nginx1
Namespace:                      default
Image(s):                       nginx
Node:                           ma1demo4.eng.platformlab.ibm.com/9.21.58.24
Start Time:                     Thu, 03 Dec 2015 01:39:04 -0500
Labels:                         app=nginx
Status:                         Running
Reason:
Message:
IP:                             172.17.0.53
Replication Controllers:        <none>
Containers:
  nginx:
    Container ID:       docker://8f8ebb6f087e1f76b74cbaeccba6ed3d98b4ef27d952819eae35977543a26a04
    Image:              nginx
    Image ID:           docker://5c82215b03d10884d98e0c074a69881e7428484c47855d49863233297f86fd9a
    State:              Running
      Started:          Thu, 03 Dec 2015 01:39:14 -0500
    Ready:              True
    Restart Count:      0
    Environment Variables:
Conditions:
  Type          Status
  Ready         True 
No volumes.
Events:
  FirstSeen     LastSeen        Count   From                                            SubobjectPath                       Reason           Message
  鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€   鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€        鈹€鈹€鈹€鈹€鈹€ 鈹€鈹€鈹€鈹€                                 鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€                          鈹€鈹€鈹€鈹€鈹€鈹€              鈹€鈹€鈹€鈹€鈹€鈹€鈹€
  25s           25s             1       {scheduler }                                                                        Scheduled        Successfully assigned nginx1 to ma1demo4.eng.platformlab.ibm.com
  23s           23s             1       {kubelet ma1demo4.eng.platformlab.ibm.com}      implicitly required container POD   Pulled           Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  23s           23s             1       {kubelet ma1demo4.eng.platformlab.ibm.com}      implicitly required container POD   Created          Created with docker id 8eb71918bb98
  22s           22s             1       {kubelet ma1demo4.eng.platformlab.ibm.com}                                          FailedSync       Error syncing pod, skipping: open /proc/27671/cgroup: no such file or directory
  22s           22s             1       {kubelet ma1demo4.eng.platformlab.ibm.com}      implicitly required container POD   Started          Started with docker id 8eb71918bb98
  13s           13s             1       {kubelet ma1demo4.eng.platformlab.ibm.com}      spec.containers{nginx}              Pulled           Container image "nginx" already present on machine
  13s           13s             1       {kubelet ma1demo4.eng.platformlab.ibm.com}      spec.containers{nginx}              Created          Created with docker id 8f8ebb6f087e
  13s           13s             1       {kubelet ma1demo4.eng.platformlab.ibm.com}      spec.containers{nginx}              Started          Started with docker id 8f8ebb6f087e
 
 
root@ma1demo3:~/gyliu/conf/k8s# kubectl --server=xxxxx:8888 get events -o yaml
apiVersion: v1
items:
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:03Z
  involvedObject:
    kind: Node
    name: ma1demo4.eng.platformlab.ibm.com
    uid: ma1demo4.eng.platformlab.ibm.com
  kind: Event
  lastTimestamp: 2015-12-03T06:39:03Z
  message: Starting kube-proxy.
  metadata:
    creationTimestamp: 2015-12-03T06:39:03Z
    deletionTimestamp: 2015-12-03T07:39:03Z
    name: ma1demo4.eng.platformlab.ibm.com.141c5346bafb15b5
    namespace: default
    resourceVersion: "19"
    selfLink: /api/v1/namespaces/default/events/ma1demo4.eng.platformlab.ibm.com.141c5346bafb15b5
    uid: 8b106991-9988-11e5-a622-0050569d857c
  reason: Starting
  source:
    component: kube-proxy
    host: ma1demo4.eng.platformlab.ibm.com
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:04Z
  involvedObject:
    kind: Node
    name: ma1demo4.eng.platformlab.ibm.com
    uid: ma1demo4.eng.platformlab.ibm.com
  kind: Event
  lastTimestamp: 2015-12-03T06:39:04Z
  message: Starting kubelet.
  metadata:
    creationTimestamp: 2015-12-03T06:39:03Z
    deletionTimestamp: 2015-12-03T07:39:03Z
    name: ma1demo4.eng.platformlab.ibm.com.141c5346e3fe7b18
    namespace: default
    resourceVersion: "20"
    selfLink: /api/v1/namespaces/default/events/ma1demo4.eng.platformlab.ibm.com.141c5346e3fe7b18
    uid: 8b78f2d2-9988-11e5-a622-0050569d857c
  reason: Starting
  source:
    component: kubelet
    host: ma1demo4.eng.platformlab.ibm.com
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:04Z
  involvedObject:
    kind: Node
    name: ma1demo4.eng.platformlab.ibm.com
    uid: ma1demo4.eng.platformlab.ibm.com
  kind: Event
  lastTimestamp: 2015-12-03T06:39:04Z
  message: 'Node ma1demo4.eng.platformlab.ibm.com status is now: NodeReady'
  metadata:
    creationTimestamp: 2015-12-03T06:39:04Z
    deletionTimestamp: 2015-12-03T07:39:04Z
    name: ma1demo4.eng.platformlab.ibm.com.141c5346ed710759
    namespace: default
    resourceVersion: "23"
    selfLink: /api/v1/namespaces/default/events/ma1demo4.eng.platformlab.ibm.com.141c5346ed710759
    uid: 8b913b2e-9988-11e5-a622-0050569d857c
  reason: NodeReady
  source:
    component: kubelet
    host: ma1demo4.eng.platformlab.ibm.com
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:04Z
  involvedObject:
    kind: Node
    name: ma1demo4.eng.platformlab.ibm.com
    uid: ma1demo4.eng.platformlab.ibm.com
  kind: Event
  lastTimestamp: 2015-12-03T06:39:04Z
  message: 'Node ma1demo4.eng.platformlab.ibm.com status is now: NodeHasSufficientDisk'
  metadata:
    creationTimestamp: 2015-12-03T06:39:04Z
    deletionTimestamp: 2015-12-03T07:39:04Z
    name: ma1demo4.eng.platformlab.ibm.com.141c5346ed712fe4
    namespace: default
    resourceVersion: "24"
    selfLink: /api/v1/namespaces/default/events/ma1demo4.eng.platformlab.ibm.com.141c5346ed712fe4
    uid: 8b923837-9988-11e5-a622-0050569d857c
  reason: NodeHasSufficientDisk
  source:
    component: kubelet
    host: ma1demo4.eng.platformlab.ibm.com
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:05Z
  involvedObject:
    kind: Node
    name: ma1demo4.eng.platformlab.ibm.com
    uid: ma1demo4.eng.platformlab.ibm.com
  kind: Event
  lastTimestamp: 2015-12-03T06:39:05Z
  message: 'Node ma1demo4.eng.platformlab.ibm.com event: Registered Node ma1demo4.eng.platformlab.ibm.com
    in NodeController'
  metadata:
    creationTimestamp: 2015-12-03T06:39:05Z
    deletionTimestamp: 2015-12-03T07:39:05Z
    name: ma1demo4.eng.platformlab.ibm.com.141c53471f7f4a1b
    namespace: default
    resourceVersion: "30"
    selfLink: /api/v1/namespaces/default/events/ma1demo4.eng.platformlab.ibm.com.141c53471f7f4a1b
    uid: 8c23f6e6-9988-11e5-a622-0050569d857c
  reason: RegisteredNode
  source:
    component: controllermanager
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:02Z
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: nginx1
    namespace: default
    resourceVersion: "17"
    uid: 8aa00815-9988-11e5-a622-0050569d857c
  kind: Event
  lastTimestamp: 2015-12-03T06:39:02Z
  message: Successfully assigned nginx1 to ma1demo4.eng.platformlab.ibm.com
  metadata:
    creationTimestamp: 2015-12-03T06:39:02Z
    deletionTimestamp: 2015-12-03T07:39:02Z
    name: nginx1.141c534696a4af18
    namespace: default
    resourceVersion: "18"
    selfLink: /api/v1/namespaces/default/events/nginx1.141c534696a4af18
    uid: 8ac5bf56-9988-11e5-a622-0050569d857c
  reason: Scheduled
  source:
    component: scheduler
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:04Z
  involvedObject:
    apiVersion: v1
    fieldPath: implicitly required container POD
    kind: Pod
    name: nginx1
    namespace: default
    resourceVersion: "17"
    uid: 8aa00815-9988-11e5-a622-0050569d857c
  kind: Event
  lastTimestamp: 2015-12-03T06:39:04Z
  message: Container image "gcr.io/google_containers/pause:0.8.0" already present
    on machine
  metadata:
    creationTimestamp: 2015-12-03T06:39:04Z
    deletionTimestamp: 2015-12-03T07:39:04Z
    name: nginx1.141c53470e454b65
    namespace: default
    resourceVersion: "27"
    selfLink: /api/v1/namespaces/default/events/nginx1.141c53470e454b65
    uid: 8be4fb87-9988-11e5-a622-0050569d857c
  reason: Pulled
  source:
    component: kubelet
    host: ma1demo4.eng.platformlab.ibm.com
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:04Z
  involvedObject:
    apiVersion: v1
    fieldPath: implicitly required container POD
    kind: Pod
    name: nginx1
    namespace: default
    resourceVersion: "17"
    uid: 8aa00815-9988-11e5-a622-0050569d857c
  kind: Event
  lastTimestamp: 2015-12-03T06:39:04Z
  message: Created with docker id 8eb71918bb98
  metadata:
    creationTimestamp: 2015-12-03T06:39:04Z
    deletionTimestamp: 2015-12-03T07:39:04Z
    name: nginx1.141c534711bd976b
    namespace: default
    resourceVersion: "28"
    selfLink: /api/v1/namespaces/default/events/nginx1.141c534711bd976b
    uid: 8bff9fde-9988-11e5-a622-0050569d857c
  reason: Created
  source:
    component: kubelet
    host: ma1demo4.eng.platformlab.ibm.com
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:05Z
  involvedObject:
    apiVersion: v1
    fieldPath: implicitly required container POD
    kind: Pod
    name: nginx1
    namespace: default
    resourceVersion: "17"
    uid: 8aa00815-9988-11e5-a622-0050569d857c
  kind: Event
  lastTimestamp: 2015-12-03T06:39:05Z
  message: Started with docker id 8eb71918bb98
  metadata:
    creationTimestamp: 2015-12-03T06:39:05Z
    deletionTimestamp: 2015-12-03T07:39:05Z
    name: nginx1.141c53471eb627a4
    namespace: default
    resourceVersion: "29"
    selfLink: /api/v1/namespaces/default/events/nginx1.141c53471eb627a4
    uid: 8c1e1ae5-9988-11e5-a622-0050569d857c
  reason: Started
  source:
    component: kubelet
    host: ma1demo4.eng.platformlab.ibm.com
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:05Z
  involvedObject:
    apiVersion: v1
    kind: Pod
    name: nginx1
    namespace: default
    resourceVersion: "17"
    uid: 8aa00815-9988-11e5-a622-0050569d857c
  kind: Event
  lastTimestamp: 2015-12-03T06:39:05Z
  message: 'Error syncing pod, skipping: open /proc/27671/cgroup: no such file or
    directory'
  metadata:
    creationTimestamp: 2015-12-03T06:39:05Z
    deletionTimestamp: 2015-12-03T07:39:05Z
    name: nginx1.141c53471f2816db
    namespace: default
    resourceVersion: "31"
    selfLink: /api/v1/namespaces/default/events/nginx1.141c53471f2816db
    uid: 8c5b3ce2-9988-11e5-a622-0050569d857c
  reason: FailedSync
  source:
    component: kubelet
    host: ma1demo4.eng.platformlab.ibm.com
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:14Z
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{nginx}
    kind: Pod
    name: nginx1
    namespace: default
    resourceVersion: "17"
    uid: 8aa00815-9988-11e5-a622-0050569d857c
  kind: Event
  lastTimestamp: 2015-12-03T06:39:14Z
  message: Container image "nginx" already present on machine
  metadata:
    creationTimestamp: 2015-12-03T06:39:14Z
    deletionTimestamp: 2015-12-03T07:39:14Z
    name: nginx1.141c53495ecb4e5f
    namespace: default
    resourceVersion: "34"
    selfLink: /api/v1/namespaces/default/events/nginx1.141c53495ecb4e5f
    uid: 91d1f590-9988-11e5-a622-0050569d857c
  reason: Pulled
  source:
    component: kubelet
    host: ma1demo4.eng.platformlab.ibm.com
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:14Z
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{nginx}
    kind: Pod
    name: nginx1
    namespace: default
    resourceVersion: "17"
    uid: 8aa00815-9988-11e5-a622-0050569d857c
  kind: Event
  lastTimestamp: 2015-12-03T06:39:14Z
  message: Created with docker id 8f8ebb6f087e
  metadata:
    creationTimestamp: 2015-12-03T06:39:14Z
    deletionTimestamp: 2015-12-03T07:39:14Z
    name: nginx1.141c534964880cf5
    namespace: default
    resourceVersion: "35"
    selfLink: /api/v1/namespaces/default/events/nginx1.141c534964880cf5
    uid: 91e08432-9988-11e5-a622-0050569d857c
  reason: Created
  source:
    component: kubelet
    host: ma1demo4.eng.platformlab.ibm.com
- apiVersion: v1
  count: 1
  firstTimestamp: 2015-12-03T06:39:14Z
  involvedObject:
    apiVersion: v1
    fieldPath: spec.containers{nginx}
    kind: Pod
    name: nginx1
    namespace: default
    resourceVersion: "17"
    uid: 8aa00815-9988-11e5-a622-0050569d857c
  kind: Event
  lastTimestamp: 2015-12-03T06:39:14Z
  message: Started with docker id 8f8ebb6f087e
  metadata:
    creationTimestamp: 2015-12-03T06:39:14Z
    deletionTimestamp: 2015-12-03T07:39:14Z
    name: nginx1.141c53496711b8f3
    namespace: default
    resourceVersion: "36"
    selfLink: /api/v1/namespaces/default/events/nginx1.141c53496711b8f3
    uid: 91e72241-9988-11e5-a622-0050569d857c
  reason: Started
  source:
    component: kubelet
    host: ma1demo4.eng.platformlab.ibm.com
kind: List
metadata: {}

**Comment by jay-lau** [comment]
I think that this share same root cause with https://github.com/kubernetes/kubernetes/issues/17364

**Comment by soltysh** [comment]
It's already fixed in #18031.

**Comment by dims** [comment]
This bug can clearly be closed!
