### ISSUE TITLE
redis-proxy has no release yet

### ISSUE THREAD

**Issue by xrow** [kubernetes/kubernetes#17895]
Hello Folks,

This file examples/redis/redis-proxy.yaml mentions a v1 release. A v1 release has not been created. Therefore the pod will fail.

**Comment by bgrant0607** [comment]
Maybe this is a result of the change to the v2 registry?
cc @brendandburns

**Comment by dynaum** [comment]
There is no `v2` tag too. The only tag on hub.docker is `latest`. Where I can find the Dockerfile of redis-proxy?

**Comment by kargakis** [comment]
@ahmetb @kubernetes/sig-apps-misc

**Comment by ahmetb** [comment]
#44801 removed this example due to the reason described above.

/close
