### ISSUE TITLE
kubectl rolling-update incompatible with kubectl expose

### ISSUE THREAD

**Issue by sils** [kubernetes/kubernetes#17902]
When I do a rolling update with a service I previously exposed, the selector of that service apparently doesn't get updated to the new replication controller, effectively making my website unavailable.

**Comment by davidopp** [comment]
Please send us the exact YAML files and commands you ran.

**Comment by sils1297** [comment]
Hi, I cannot send you the yamls, they specify a very simple replication controller. Exposing was done via `kubectl.sh expose rc rc_name --port=80 --target-port=80 --type=LoadBalancer`. Rolling update was done via `kubectl.sh rolling-update rc_name -f same_yaml.yml`, while `same_yaml.yml` had the exact same contents except the labels and selectors where I appended `2` so kubernetes wouldn't complain.

**Comment by mpj** [comment]
@sils1297 Hej lasse! I'm having the same problem, did you ever figure out what you problem was?

**Comment by mpj** [comment]
Here is my theory, it's that expose will infer the selector from the rc. The problem is that this returns on a deployment label as well:
```$ kubectl get service
NAME         CLUSTER_IP     EXTERNAL_IP     PORT(S)    SELECTOR                                                          AGE
kubernetes   10.75.240.1    <none>          443/TCP    <none>                                                            3h
stealy       10.75.247.52   XXX.XXX.XXX.XXX   8080/TCP   deployment=f106f67513390ba00b766e6e730abff3,service_name=stealy   20m
```
(external ip masked)

**Comment by mpj** [comment]
Hmm. no. I tried my theory and specificed the selector to just service_name=stealy and the forwarding still breaks when I do a rolling-update.

**Comment by justinsb** [comment]
I'm going to remove the AWS label so this gets wider attention; this isn't AWS specific AFAICT.

**Comment by zefciu** [comment]
@davidopp

This is an interesting problem and the behaviour here seems to be quite counterintuitive, especially to a newcomer. My idea would be as follows:

When you `expose` an rc as a service and specify the selector explicitly, the rc stores a special annotation about what selector is used by the service. Also the pods get labelled to match this selector. Now when we do a rolling update, the new pods are also labelled this way.

Please comment if this fits the general design of kubernetes resource-controllers or if it falls out of scope of what we want rc's to be able to do.

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by zefciu** [comment]
I started a thread in a group about it as well:
https://groups.google.com/forum/#!topic/kubernetes-dev/WbqQVNkDZUE
I explain the simple scenario where this can be very baffling to a newcoming user.

**Comment by bgrant0607** [comment]
Relevant thread: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/WbqQVNkDZUE/1f5WZK2zCAAJ

**Comment by bgrant0607** [comment]
@zefciu Thanks for taking time to explain the problem and to propose a solution. You're right that this is confusing. We'd appreciate your help in fixing it.

However, `kubectl expose` adding a label isn't going to work, either. In the case that the user chooses labels and doesn't know they need to add the service's label to their new ReplicationController, they'll encounter a similar problem.

The way this is intended to work is that services should select the common subset of labels across all pods they target.

We should make it easy to exclude labels from the selector used by the service created by expose, and could exclude a couple common version-specific keys (e.g., deployment, version) by default.

And of course this needs clear documentation.

**Comment by bgrant0607** [comment]
We could also add the deployment label used by `kubectl rolling-update --image` to `kubectl run` by default, though that could break some existing uses.

**Comment by kargakis** [comment]
> We should make it easy to exclude labels from the selector used by the service created by expose, and could exclude a couple common version-specific keys (e.g., deployment, version) by default.

Agreed, that's what I was thinking too. The service generator should drop labels such as the deployment key used in `rolling-update`. Thankfully Deployments don't have this issue.

**Comment by zefciu** [comment]
OK, starting to work according to idea by @bgrant0607

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by soltysh** [comment]
@bgrant0607 given your suggestion here: https://github.com/kubernetes/kubernetes/issues/23276#issuecomment-359567626 I'd propose closing this.

**Comment by bgrant0607** [comment]
@soltysh Agreed. We should deprecate rolling-update. 

I would like to see `kubectl run` adopt a set of labels that more closely match best practices, though.

**Comment by soltysh** [comment]
> I would like to see kubectl run adopt a set of labels that more closely match best practices, though.

Would you mind explaining this a bit, not sure I follow. What kind of labels?
