### ISSUE TITLE
Rolling Update Docs: Add example with database

### ISSUE THREAD

**Issue by sils1297** [kubernetes/kubernetes#17903]
This is wrt http://kubernetes.io/v1.1/docs/user-guide/update-demo/README.html .

Usually one doesn't want to simply replace the application with another version/application, but one wants both to use the same database so users operating on the application won't end up reentering all their precious data. I think its thus very important to show an example where the application is updated while the DB container stays. (More advanced example could be even performing migrations)

**Comment by bgrant0607** [comment]
Improved support for stateful applications is ongoing. Given that kubectl rolling-update isn't intended for such applications, I'm going to close this. 

For now, if you don't want to lose data, I recommend using persistent volumes:
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/persistent-volumes.md
