### ISSUE TITLE
Cluster unreachable after some time

### ISSUE THREAD

**Issue by sils1297** [kubernetes/kubernetes#17904]
What I did:

1. Spawn a cluster on AWS using the appropriate export and `kube-up`.
2. Spawned a pod, all worked well.
3. Eat, code, sleep, leaving the cluster alone for a longer time. (12 hours?)

Results:

On the next morning the cluster was "unreachable".  Same PC, same configuration, I checked the IP which is the one from the master. AWS diagnostics show that the master and the nodes are up and running well though apparently I couldn't make any requests to them. The app was unreachable too.

For monetary reasons I had to `kube-down` the cluster (which worked well) so I cannot give you any logs, though I'll repeat my experiment with my new cluster this night.

**Comment by sils1297** [comment]
FWIW I couldn't reproduce this but I swear it happened.

**Comment by davidopp** [comment]
I'm going to close, but please reopen if you have the problem again, and also supply logs 
(/var/log/kube-*.log).
