### ISSUE TITLE
Remote admin to cluster via kubelet VM

### ISSUE THREAD

**Issue by eliaslevy** [kubernetes/kubernetes#17906]
Getting remote access to k8s cluster services for administrative purposes can be quite difficult because of the nature of k8s network architecture (virtual IPs, often overplayed networking, DNS that is only visible to Pods by default, namespaces), unless the services are HTTP based, in which case you can then access via `kubectl proxy`.  

One solution is to create a Pod in the cluster solely to allow admins access to the services. Admins can then use `kubectl exec` to execute commands within the admin Pod that have access to cluster services.  One downside with this approach is that is can be prohibitive for remote admins to upload large tools into the Pod. This is compounded by the lack of a `kubectl` command to copy files into Pods.

I would be useful to develop a VM that can pretend to be a Node and join the cluster remotely from an admin's workstation.  The VM would have a with a version of `kubelet` that refuses all Pods assigned to it.  The VM would execute a static Pod that would allow for administration of the cluster.

**Comment by smarterclayton** [comment]
My go to tool is kubectl run --image=mytools --restart=Never -i -a to get a shell into the cluster.  Once I'm in the container I tend to use rsync to copy things into it, although I agree it's not as easy as a direct copy command.

**Comment by eliaslevy** [comment]
Indeed, that is what I also do.  But often even rsync is rather painful.  E.g. when you need to upload a new massive Java based admin client from your remote system over a not-very-fast  DSL line.

What you really want is native cluster access from your local system.  I propose that this can be accomplished with a local VM.  On further reflection, `kubelet` may be unnecessary.  You just need to be running `kuibe-proxy`, configure the resolver to point to the `kube-dns` service, and have your overplayed networking configured within the VM or if you are using native networking, have a VPN configured appropriately.

I might try setting up a Vagrant image and see if that works.

**Comment by smarterclayton** [comment]
You can also run a VPN pod in the cluster that you then connect to via
SSH/exec, to redirect traffic to that pod back to the cluster.  Similar to
your suggestion, slightly different approach.

**Comment by eliaslevy** [comment]
That is an interesting notion I had not considered, although it would seem as if would require you to already have network connectivity to the Pod address space, otherwise, how would you connect to the VPN server in the Pod?

**Comment by obimod** [comment]
similar issue #14545

**Comment by smarterclayton** [comment]
Tunnel over exec :).  You can also expose it as a NodePort service (punch a
hole through the firewall) and run an ssh pod with a one time secret you
generate locally (at one point I had that scripted for kubectl run)

On Nov 30, 2015, at 2:49 PM, Elias Levy <notifications@github.com> wrote:

That is an interesting notion I had not considered, although it would seem
as if would require you to already have network connectivity to the Pod
address space, otherwise, how would you connect to the VPN server in the
Pod?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/17906#issuecomment-160739044>
.

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc
