### ISSUE TITLE
Validate all enum fields in API

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#17905]
The golang type aliases can take any value, regardless of what constants are defined for that type.  We currently validate some enum types in the API; this issue is to validate them all.

**Comment by lavalamp** [comment]
It's worth noting that some of those types are meant to be extendable and so we shouldn't just blanket start rejecting unknown enum values.

@thockin may be interested

**Comment by thockin** [comment]
We should make a list and consider them one by one.  I think that, for most
of them, validation is appropriate.  If the APIServer doesn't know then it
can't DTRT.  Some will be looser, I bet, but most not.

**Comment by bgrant0607** [comment]
Related: #14541
