### ISSUE TITLE
When Deploying Kubernetes on Vagrant, requires changes for tmpfs

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#17918]
When deploying Kubernetes to a laptop (on Vagrant), Salt deploy now is larger than the tmpfs.

So gotta tweak the vagrant master mem (go higher).

cc @mikedanese

**Comment by mikedanese** [comment]
Thanks, I think I know what this is. I'll send a patch. cc @jayunit100

**Comment by jayunit100** [comment]
yep, 2048 should do it iirc I played with this some as well

**Comment by mikedanese** [comment]
I think I'm going to try to make it so we don't use a ton of tmpfs to unpack salt. Deploy is probably borken on >1G memory machines (g1-smalls) as well
