### ISSUE TITLE
[AWS] Subnets for ELB are picked randomly so ELB may not be accessible

### ISSUE THREAD

**Issue by jtblin** [kubernetes/kubernetes#17912]
#14242 fixed the ELB creation with multiple subnets per AZ but it picks the subnets randomly. What happens in our case is that it picks private subnets for the ELB making it impossible to access the service (connection timeout) as it is not possible for external traffic to reach private subnets. 
Having public and private subnets is the AWS recommended design for VPCs.

Related to #16083.

**Comment by davidopp** [comment]
@justinsb

**Comment by justinsb** [comment]
Are you tagging the private subnets with the KubernetesCluster tag?  How are you using public & private subnets here?

I recognize that this fixes a problem introduced by #14242, but I'm not convinced that #14242 is necessary if you're tagging your subnets.  Similarly, I think if you tag only your public subnets with the KubernetesCluster tag, this patch should be unnecessary as it will ignore the untagged subnets.

Also, I believe that some people are using public/private subnets the other way round - i.e. running k8s in their private subnets...

**Comment by jtblin** [comment]
No I wasn't tagging the subnets/instances at all, I just discovered that https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md about it but didn't see anything in the doc originally. After tagging the public subnets and instances, Kubernetes picks the correct subnets to launch the ELB so feel free to decline the PR and close the issue if you think it's best. 

Note that the tags strategy won't work in the long run when internal ELBs are implemented, #17620 and #16083 (the logic in the PR could help in this case). The long term "fix" is probably to allow passing the subnets directly in the specs. Is there any design document for these? We need the possibility to launch internal ELBs and are keen to help.

**Comment by manojlds** [comment]
`KubernetesCluster =<clusterid>` - what should cluster id be, or just the  key is enough?

**Comment by jtblin** [comment]
It can be whatever value you want e.g. "dev", "my_cluster", etc. It just
needs to be set consistently on the different resources e.g. nodes,
subnets, etc.

**Comment by manojlds** [comment]
@jtblin i saw a `--cluster-name` argument to controller-manager. Not dependent on that? Need to go through `aws.go` to see what's happening.
