### ISSUE TITLE
Running multiple Kubernetes on Mesos

### ISSUE THREAD

**Issue by jay-lau** [kubernetes/kubernetes#17928]
The current design of k8s + mesos only support one k8s framework, but for some cases, there might be multiple k8s frameworks on top of mesos. We need to make the frameworkid store configurable.

**Comment by dchen1107** [comment]
@jdef

**Comment by jdef** [comment]
Thanks for filing this issue. We're pretty far away from being able to support multiple kubernetes frameworks sharing the same pool of slaves. If you statically partition your mesos cluster w/ roles then you're more likely to succeed: the k8sm scheduler just got support for roles. We haven't tested this yet.

Also, if you're running separate k8s frameworks, you probably want to run separate etcd registry stores for each cluster. This would solve the framework ID problem, yes?

**Comment by jay-lau** [comment]
Thanks @jdef 

1) The kubernetes role is working well.
2) Yes, if set different etcd servers, then we can run multiple kubernete clusters on one mesos cluster. I will use this as workaroud for now. But I do hope that we can fix this in future, it is better to use only 1 etcd for multiple k8s on top of mesos. ;-)

**Comment by jdef** [comment]
we're actually breaking the rules by writing to etcd directly. filed an issue in kubernetes-mesos to track this: https://github.com/mesosphere/kubernetes-mesos/issues/662

**Comment by jay-lau** [comment]
ok, thanks @jdef
