### ISSUE TITLE
SSH/SCP options customization for ubuntu install

### ISSUE THREAD

**Issue by pvcnt** [kubernetes/kubernetes#17934]
Hi,

Right now in the installation script for Ubuntu there are hardcoded SSH_OPTS. In my case I am using a custom SSH port, and, unless I am mistaken, I have no way to customize it, either globally or on a per-host basis. Would it be possible to do that? I can try to submit a patch if necessary.

Thanks.

**Comment by resouer** [comment]
Yes, please. Just send a PR to add `SSH_OPTS` in `config-default.sh` and make it configurable.
