### ISSUE TITLE
HPA Tests: taking 30+ minutes

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#17941]
Looks like the HPA tests are quite lengthy.  A couple failed.  I'm digging into the details now, will close this issue if its an anomoly or config issue. 

UPDATE (deleted lengthy debug trace to save readers eyes: The fact is polling takes a while depending on constants we pick + deployments need to be enabled, one of my tests i hadn't done that).

**Comment by jayunit100** [comment]
cc @karlkfi @piosz I am looking into this one now, just FYI :) will update in this thread.

**Comment by piosz** [comment]
Deployment is an experimental feature an is disabled by default. There is a flag [ENABLE_DEPLOYMENT](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L82) which should help you.

cc @kubernetes/autoscaling

**Comment by jayunit100** [comment]
Yes, thats true the deployments must be enabled.  
The main issue here is the length : `stabilityTimeout` is i think what we might want to update.

**Comment by piosz** [comment]
What do you mean?

**Comment by jayunit100** [comment]
well, i think the 10 min timeout is making the test run a while.  possibly we will want to parameterize these things so we can run a "fast HPA test"

**Comment by jayunit100** [comment]
i.e. `	stabilityTimeout = 1 * time.Minute` makes these run much faster. :)

**Comment by piosz** [comment]
In HPA e2e we test that our decision is stable - HPA should not change his mind without changed load. Field ```stabilityTimeout``` means how long should we wait to check it. It is set to 10 minutes because when the scale decision is made there is a [window](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L48) during which the next scaling decision is forbidden. Changing it to 1 minute will disable verification of the stability of decision.

**Comment by jayunit100** [comment]
Yup I think it's a 5 or 3 min window depending on the other parameters. 

 It seems like a baseline fast horizontal scaling test would be good to have, which was able to run in the CI...  which didn't verify stability ?

**Comment by jayunit100** [comment]
To be clear I am **not** suggesting that the stability timeout test be removed ... Just suggesting we also have some fast HPA test that is easy to run.

**Comment by jayunit100** [comment]
cc @DirectXMan12

**Comment by piosz** [comment]
To be clear a single test takes <20 minutes. This is because of the latency in monitoring pipeline. Once we will improve Heapster (should happen for 1.2) it should take 5 minutes.

**Comment by DirectXMan12** [comment]
> In HPA e2e we test that our decision is stable - HPA should not change his mind without changed load. Field stabilityTimeout specifies how long should we wait to check it. It is set to 10 minutes because when the scale decision is made there is a window during which the next scaling decision is forbidden. Changing it to 1 minute will disable verification of the stability of decision.

I think it's reasonable to make the scaling-forbidden window configurable (from the tests, at least), and then have a set of tests with a small window (e.g. 1m or 30s both ways), and another that tests stability with real-world values (like we currently have -- 3m and 5m)

**Comment by piosz** [comment]
cc @jszczepkowski

**Comment by jszczepkowski** [comment]
> I think it's reasonable to make the scaling-forbidden window configurable (from the tests, at least), and then have a set of tests with a small window (e.g. 1m or 30s both ways), and another that tests stability with real-world values (like we currently have -- 3m and 5m

This makes sense. However, to make it work, first we will need heapster latency to be reduced: https://github.com/kubernetes/heapster/issues/684.

**Comment by kargakis** [comment]
@kubernetes/sig-autoscaling-misc
