### ISSUE TITLE
Documentation about responses from apiserver

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/kubernetes#17951]
Hi,

I am looking for documentation about all possible responses from the API server in particular for this websocket watching endpoints:

ws://1.2.3.4/api/v1/watch/namespaces/some-namespace/endpoints/some-label

I have seen entries like ADDED, DELETED and MODIFIED. 

Moreover, are there any best practices for watching the apiserver?

Thanks,
Andrej

**Comment by bgrant0607** [comment]
Closing as dupe of #15666. Will comment there.
