### ISSUE TITLE
vSphere Cluster install fails with "Error: A Specified parameter was not correct"

### ISSUE THREAD

**Issue by casanova** [kubernetes/kubernetes#17950]
ust trying to install a test instance of Kubernetes on my vSphere cluster. I'm following the install instructions on kubernetes.io and get to the point where I run:

govc import.vmdk kube.vmdk ./kube/

The vmdk gets uploaded and imported, but the following happens on my cluster:

Create virtual machine  [Cluster]  -- Completes
Clone virtual machine   kube-srcvm -- Completes
Reconfigure vm          kube-srcvm -- Completes
Delete virtual machine  kube-srcvm -- Completes
Reconfigure vm          kube-dstvm -- Completes
Delete virtual machine  kube-dstvm -- Completes
Delete virtual disk                -- Completes

From there I try ./kube-up.sh:

... Starting cluster using provider: vsphere
... calling verify-prereqs
... calling kube-up
Starting master VM (This can take a minute)...
Error: A specified parameter was not correct.

I'm relatively sure my config is ok:

export GOVC_URL='https://user:pass@mydomain/sdk'
export GOVC_DATACENTER='My Datacenter'
export GOVC_DATASTORE='datastore3'
export GOVC_RESOURCE_POOL='/My Datacenter/host/My Cluster/Resources/Kubernetes/'
export GOVC_NETWORK='VM Network'
export GOVC_GUEST_LOGIN='kube:kube'
So yeah, not really sure where to go from here -- any insight would be greatly appreciated. I should add that I'm trying this on a vsphere 5.1 cluster -- but I have already switched the default API to that.

**Comment by davidopp** [comment]
It looks like there's some recent work to get Kubernetes working with vSphere (see recent comments in #18457), but we don't really expect it to work right now, so I'm going to close this issue and suggest you follow #18457. Feel free to re-open an issue if you still have problems after vSphere is believed to be working again.

**Comment by miracle2k** [comment]
FWIW I have the same error and also on 5.1, forcing the minimum version to that. It might be a versioning issue.
