### ISSUE TITLE
Kubelet using expensive /containers/json?all=1 call

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#17959]
We've been trying to squeeze a large number of pods onto a single node well beyond the recommended 30 pods per node. We first ran into this issue (#16296), where cadvisor was taking a huge chunk of cpu time. After decreasing the cadvisor run frequency and @vishh fix on cadvisor's networking parsing, cadvisor's cpu usage went down significantly to allow us to squeeze more containers onto a node. 

After more experiments, we found the next bottleneck seems to be Docker engine as it was getting hit very hard from several K8s components. More profiling indicates that things converge to this function:
```
func (dm *DockerManager) GetPodStatus(pod *api.Pod) (*api.PodStatus, error)
```
Within this function, the main culprit is:
```
containers, err := dm.client.ListContainers(docker.ListContainersOptions{All: true})
```
because when you have a large number of containers, it takes a lot of time for Docker to encode all the information to json, and then for k8s to decode it, i.e., a lot of `/containers/json?all=1` calls. As k8s already uses docker labels (specifically "io.kubernetes.pod.name") to annotate which containers belong to which pod, it would be less expensive by calling `/containers/json?filter=...` instead, so there's less encoding/decoding needed. I modified this code to:
```
    namespacedName := types.NamespacedName{Namespace: pod.Namespace, Name: pod.Name}
    filter := fmt.Sprint(kubernetesNameLabel, "=", namespacedName.String())
    labels := map[string][]string{
        "label": {filter},
    }
    containers, err := dm.client.ListContainers(docker.ListContainersOptions{All: false, Filters: labels})
```

Is there any downside of doing this? Or corner cases where it won't work? 

cc @yujuhong since you were looking at k8s scalability issues

**Comment by vishh** [comment]
@yujuhong has been working on reducing the number and frequency of `listContainers` that kubelet performs. Can you try a kubelet from latest HEAD? Thanks for sharing your observations BTW :+1:

**Comment by dchen1107** [comment]
This is known issue and we are working on this by introducing Pod-Lifecycle-Event-Generator (PLEG): https://github.com/kubernetes/kubernetes/pull/13571

I am closing this one as dup of https://github.com/kubernetes/kubernetes/issues/12540

**Comment by huang195** [comment]
@vishh sure, will give that a try. @yujuhong how much can these changes increase the number of pods per node? Officially, it's 30. With these changes, are we talking about 50, 100, 500, or 1000? Sure, it'll depend on the hardware of the nodes, but without being very specific. It'd be nice to understand how much room there is for improvement

**Comment by Random-Liu** [comment]
@huang195 For the filtering related things, maybe this is useful for you, :) #15089

**Comment by dchen1107** [comment]
@huang195 to answer your above question, please take a look at https://github.com/kubernetes/kubernetes/issues/16943

**Comment by huang195** [comment]
thank you @Random-Liu @dchen1107

**Comment by huang195** [comment]
@vishh Just make sure I didn't miss anything - the PLEG work that @yujuhong is working on isn't merged into HEAD yet, right? The work is described in #12829, which seems to be still work-in-progress. But it will be great to avoid all these polling of the docker engine, and instead use events from container runtime's event stream.

**Comment by vishh** [comment]
#13571 is the PR I was referring to.

**Comment by huang195** [comment]
@vishh I pulled from the head and it looks like cadvisor is acting up again - spending a lot of time parsing network information. Here's the pprof:

![kubelet](https://cloud.githubusercontent.com/assets/8008677/11488744/e4df2434-9796-11e5-9f8f-e33c729121ca.gif)

**Comment by vishh** [comment]
@jimmidyson is working on integrating the cadvisor fixes for this issue
into kubelet HEAD.

**Comment by huang195** [comment]
@vishh Just tried it after disabling cadvisor, and it looks like it is scaling better than before. It started to take a minute or more to create more pods when there are around 150 pods on the node, whereas in release-1.1, it was around 120 pods per node before it started to take more than a minute to create pods.

**Comment by yujuhong** [comment]
> @vishh Just tried it after disabling cadvisor, and it looks like it is scaling better than before. It started to take a minute or more to create more pods when there are around 150 pods on the node, whereas in release-1.1, it was around 120 pods per node before it started to take more than a minute to create pods.

@huang195, did you create the pod after the 150 pods have reached steady state? How did you measure the latency?

**Comment by huang195** [comment]
@yujuhong we're creating pods sequentially and only creating the next one when the previous one's state has changed to RUNNING. We're using poll with 0.5 sec in between so the latency is not exact, but it's pretty close. If there's a better way to measure latency without all the polling, please let me know.

**Comment by yujuhong** [comment]
FYI, #17545 should also remove some unnecessary load on docker.

A huge part of kubelet's pod status updates is limited by the QPS limit imposed on the apiserver client. If you didn't change the default QPS limit (5.0), you'll have to wait until all pods are "READY" (not just running) to start the extra pod for latency measurement. Otherwise, kubelet would be stuck at sending the status update for the previous 150 pods.

**Comment by huang195** [comment]
@yujuhong we also made local changes similar to #17545 so we can push larger number of pods on the node. I noticed quite a few number of "internal" timers that could be externalized as command line parameters. pod sync time is externalized, but things such as how often runtimeCache should refresh, or containerGC and imageGC should run, etc. could be parameterized. 

Just to clarify our experiment. We start our measurement from a clean slate, i.e., no pods, and start creating pods one at time. Only when the current pod is reporting to be "RUNNING" (maybe we should change this to "READY") do we start creating the next pod. When we run this benchmark, pods usually take a few seconds to create, no more than 10. However, when it get to 150 range, new pods start to take much longer to create.

I'm not entirely sure about how the QPS limit would impact our result. Should we increase the limit? As far as I could tell, Docker engine was getting hammered at almost constant 100% cpu at around 150 pods, which seems to be our bottleneck, but I could be wrong.

**Comment by yujuhong** [comment]
@huang195, you're right about the impact of QPS limit being low if it takes a a few seconds for one pod to become running. 

Do you have any graph showing the latency of pod startup time as the number of pods increase? It'd be interesting to see if the progression :-)

**Comment by huang195** [comment]
![test-kube-1000](https://cloud.githubusercontent.com/assets/8008677/11542384/0c970c52-9905-11e5-867e-6abc133f9469.png)

**Comment by huang195** [comment]
This is what we are able to achieve by tuning down various things including something similar to #17545 and also doing /containers/json?filter=.. optimization since we don't have to worry about legacy containers. In this setup, we're using 1 master + 2 slave nodes, so we were able to squeeze about 500 pods per node. This is also running k8s on top of mesos, thus, we are getting some jittery due to mesos offerings not always available. Also k8s-on-mesos executor is doing its own podSync that kubelet does, so this is also putting extra load to the docker engine. But as you can see, latency got crazy when we got to 800 pods range.
