### ISSUE TITLE
GCE PD mount fails if PD already attached

### ISSUE THREAD

**Issue by kshelton** [kubernetes/kubernetes#17955]
kubelet does not remove old PD mounts and does not check if the PD is already mounted.  This leads to repeated errors:

googleapi: Error 400: The disk resource '<PD VOLUME>' is already being used by '<INSTANCE>'

Where instance is the same instance that kubelet is running on.

**Comment by thockin** [comment]
@saad-ali it's a dup, please xref appropriately :)

**Comment by saad-ali** [comment]
@kshelton Thanks for the report.

Could you provide more information about where you see this, under what circumstances, what Kubernetes version you're running on, and on GCE or GKE?

We have an existing issue around PDs not getting detached when kubelet goes down, tracked by https://github.com/kubernetes/kubernetes/issues/14642.

We also had some stability issues with GCE PD attach/detach that were fixed in v1.1.

**Comment by kshelton** [comment]
Where: On restart of node (ungraceful kubelet shutdown)
Version: Master (69bb774dd487d67f9c1fd1568e71df16a36a5097)

I have to modify gce_util.go like this

```
diff --git a/pkg/volume/gce_pd/gce_util.go b/pkg/volume/gce_pd/gce_util.go
index bb38ae5..b64f132 100644
--- a/pkg/volume/gce_pd/gce_util.go
+++ b/pkg/volume/gce_pd/gce_util.go
@@ -134,8 +134,8 @@ func attachDiskAndVerify(b *gcePersistentDiskBuilder, sdBeforeSet sets.String) (

                if err := gceCloud.AttachDisk(b.pdName, b.plugin.host.GetHostName(), b.readOnly); err != nil {
                        glog.Errorf("Error attaching PD %q: %v", b.pdName, err)
-                       time.Sleep(errorSleepDuration)
-                       continue
+                       //time.Sleep(errorSleepDuration)
+                       //continue
                }

                for numChecks := 0; numChecks < maxChecks; numChecks++ {
@@ -153,6 +153,7 @@ func attachDiskAndVerify(b *gcePersistentDiskBuilder, sdBeforeSet sets.String) (
                        glog.V(3).Infof("Waiting for GCE PD %q to attach.", b.pdName)
                        time.Sleep(checkSleepDuration)
                }
+        time.Sleep(errorSleepDuration)
        }

        return "", fmt.Errorf("Could not attach GCE PD %q. Timeout waiting for mount paths to be created.", b.pdName)

```

Which just makes it continue to check if mounted even if atach fails, but I don't feel it's really the right solution.

**Comment by saad-ali** [comment]
Thanks for the details @kshelton. That sounds like #14642. We're working on a fix.

Close as dupe.
