### ISSUE TITLE
Check out overlapping subnets and flannel

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#17962]
People have complained about this and now it's easy to test because we've streamlined flannel setup: 
1. Make flannel use a 10. address space by modifying the network config (try a couple that overlap with the master's service-cluster-ip-range, eg: 10.0.0.0/16, 10.15.0.0/12 etc):
   https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/flannel-server/network.json#L2
2. Start a flannel cluster, just set this env var to flannel: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L128 and setup a normal e2e cluster (i.e: go run hack/e2e.go -pushup)
3. Test all the normal things (something like pods can ping across nodes, ping nodes, nslookup Kubernetes.svc, we can hit a service from a node, nodeport works, master proxy works etc -- probably start by running all the Services e2es against the cluster). I feel like one of these will fail.

@freehan in case you're interested in digging up flannel things

**Comment by thockin** [comment]
What's the goal here?

**Comment by knobunc** [comment]
Sorry... I don't understand the bug.  Are you saying "if you assign two things the same IP range, bad things happen?"  Or did I miss something subtler?

**Comment by bprashanth** [comment]
> What's the goal here?

To verify that overlaps between service-cluster-ip-range and the network range given to flannel to carve out CIDRs from dont mess up normal service operation (either because of iptables rules/routes from flannel or assumptions on our end).

**Comment by bprashanth** [comment]
to clarify, given the complaints ive seen to slack there's a chance one of the components is apply a general rule that intercepts rules from the other. I guess my overlapping comment was confusing.

**Comment by thockin** [comment]
Do we want that to be accpetable?  Pod IPs and Service IPs are different
animals..

**Comment by bprashanth** [comment]
Hmm, If it's acceptable to have overlap, we should make sure both components don't mess with each other by installing conflicting rules. if it's un-acceptable to have overlap, we should probably validate.  With configurable networks this is going to hit more people who don't realize that there is another service ip range given to the master. Maybe we should force them to designate a network for service-ip as well.

**Comment by eparis** [comment]
I don't see how two things with the same IP is really ever going to be expected to work. When a packet leaves a pod how is the host supposed to know if it was supposed to go to the service or to the other pod?

I also don't think it is predictable which will 'win'. If you are using the linux bridge as your backend the iptables rules for services will get processed before the packet is forwarded and will go to the service. If you have an OVS based backend which doesn't hit netfilter unless/until after all interpod connectivity is satisfied the pod will always win.

I don't think there is any reasonable way to make these things be able to overlap today...

**Comment by thockin** [comment]
I don't think Services and Pods can overlap - how would that ever turn out
OK?

**Comment by cmluciano** [comment]
@freehan Is this still relevant ?
