### ISSUE TITLE
Misspelled job name in Jenkins

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#17961]
@gmarek, looks like after #17821 you misspelled your Jenkins job. There's a job in Jenkins called `kubernetes-gke-e2e-flaky`, and a case in e2e.sh called `kubernetes-e2e-gke-flaky`. Apologies if I'm mistaken.

**Comment by gmarek** [comment]
Yup. @wojtek-t already fixed that in #17935. Thanks for noticing it though.
