### ISSUE TITLE
Need medium-scale kubelet test type

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#1796]
We have unit tests (kubelet_test.go, etc).
And we have system-level integration and e2e tests that include master and kubelet.
But we don't have anything in between.

Not having a medium sized option may result in insidious test-writing.  For example:
- tests that should be medium scale may end up getting written as unit tests against functions that really ought to be private.  So they end up being refactoring-detectors more than tests.
  - if the same test is written in large scale (integration and e2e), then it inevitably has more baggage and may become a false alarm when something other than kubelet breaks.

Other reasons:
- needed if we are to make kubelet a stand-alone project (#1599)
- best way to test things like kubelet flags, local config sources, etc.

One possible approach:
- shell functions to create a "standard" VM, and start pre-reqs like etcd, cadvisor in a "standard" fashion.
- shell functions to run kubelet with specific flags and config files.
- assorted shell functions to check expectations
- shell functions to write BoundPods into etcd to simulate messages from the master

**Comment by bgrant0607** [comment]
Closing as obsolete.
