### ISSUE TITLE
integration flake: Deployment flakes in test-cmd

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#17966]
Glancing through the logs it looks like a failure to update the deployment because of a conflict led to the test failing. 

```
port-1 2380
09:28:31 (BSuccessful get service etcd-server {{(index .spec.ports 1).name}} {{(index .spec.ports 1).port}}: port-2 4001
09:28:31 (Bservice "etcd-server" deleted
09:28:31 
09:28:31 FAIL!
09:28:31 Get rc {{range.items}}{{.metadata.name}}:{{end}}
09:28:31   Expected: frontend:
09:28:31   Got:      frontend:nginx-deployment-l7ln1:
09:28:31 (B
09:28:31 955 ./hack/test-cmd.sh
09:28:31 (B
09:28:31 !!! Err
```

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/3629/consoleFull

**Comment by davidopp** [comment]
@bprashanth does the PR you merged fix this, or should we still look into this?

**Comment by kargakis** [comment]
Have you seen this since https://github.com/kubernetes/kubernetes/pull/18013 ?

**Comment by wojtek-t** [comment]
I think we didn't. Let's close it now and we will reopen if we observe it again.
