### ISSUE TITLE
CPU not limited by limits

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#17970]
Most of our docs talk about resources (e.g. CPU, memory) as being guaranteed `request` and not to exceed `limit`.  Except CPU.  Now, I am intimately familiar with why CPU is burstable in Borg, but I thought our introduction of requests and limits being distinct settings obviated the need for it to not be limitable.  Put another way, if limit doesn't actually apply to CPU, how would I go about limiting CPU usage?

Why don't we follow our own rules for behavior with request/limit?

@vishh

**Comment by vishh** [comment]
Assuming that most of our existing users do not care about tail latency issues that CPU hardcapping can introduce, +1 for enforcing CPU `limits` by default. 

Today a user can run a pod in `Guaranteed` class without hardcapping. We will have to continue supporting that option for users who run latency sensitive workloads.

Note that not setting CPU `limit` to disable hardcapping will result in the pod being treated as `Burstable`, which could affect other features like eviction priority, etc.

**Comment by derekwaynecarr** [comment]
@thockin - there is a flag to enforce limits:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L339

FWIW, OpenShift defaults to this flag to true.  @vishh requested the opposite when I added CFS quota support for Kubernetes.

**Comment by thockin** [comment]
@vishh ok to close this now?

**Comment by vishh** [comment]
CPU limits are enforced by default now..
