### ISSUE TITLE
kubernetes-gke-e2e-flaky has been failing since it was created

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#17989]
We shouldn't be creating flaky test suites and then not even verifying that they pass at least once.

**Comment by roberthbailey** [comment]
The error appears to be in the test configuration: `14:31:01 bash: line 1577: E2E_CLUSTER_NAME: unbound variable`

**Comment by gmarek** [comment]
It was succeeding. E.g: http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-gke-e2e-flaky/234/

I'll see what has changed since then.

**Comment by gmarek** [comment]
I believe that the change here was a culprit: #17935. After changing the project name in Jenkins things look better.

**Comment by wojtek-t** [comment]
@gmarek - thanks for fixing it
