### ISSUE TITLE
e2e flaky: Horizontal pod autoscaling

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#17992]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/1893/

Horizontal pod autoscaling (scale resource: CPU) [Skipped] [Autoscaling] ReplicationController Should scale from 1 pod to 3 pods and from 3 to 5

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:56 Nov 30 13:28:33.651: timeout waiting 10m0s for pods size to be 3

**Comment by piosz** [comment]
We talked today about the problem and @jszczepkowski is going to fix it.
