### ISSUE TITLE
Idea: kubectl export-local-volume

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#18007]
### Idea

Make it easy to export "local" files as a (limited lifetime) volume which pods in a kubernetes cluster can mount.    
##### Interactive Development

I am developing an interpreted program such as a python or node.js program.  I want to use the editor/IDE on my desktop.  But I want to run the program in a pod because it relies on things that exist in the kubernetes environment, and not my desktop (e.g. DNS, service account credentials, services, more memory/cpu, etc).  I want to avoid the step of rebuilding an image and restarting a pod every time I make an edit.   I want a solution like this:
1. I develop my source files locally in my `$HOME/src` directory.  
2. I export `$HOME/src` as remote storage that can be mounted by Pods.  It contains my source code (e.g. `$HOME/src/hello.py`).
3. I `kubectl run` a pod that has an image that includes my interpreter, like `python:latest`, but not my source code.    The pod also mounts the exported volume ( `$HOME/src`), which contains the source code.  The command line is set in the pod spec to `/bin/sh` so I can run via `kubectl attach`.
4. I use `kubectl attach` to connect to the pod and then run `python ./src/hello.py`.  
5. In another window, I make edits on my local host, using my editor.
6. Then I restart the program in the `kubectl attach` session.
##### Porcelain for Docker-like experience

People use to docker may ask why `kubectl` has no equivalent to `docker run -d -P --name web -v /webapp training/webapp`.  

We could add a `--local-temporary-volumes <local-path>:<mount-path>` option to `kubectl run` which would automate the process of exporting <local-path> and add the needed volume mounts to the Pod spec.
### Proposed New Commands

When a user runs `kubectl export-local-volumes --local-path <path>`, the following things happen:
1. `kubectl` generates a credential that will be used by clients to access the local fileserver.
2. `kubectl` posts the secret to the current namespace with a generated name.
3. `kubectl` starts a file server (e.g. forks a process or starts a goroutine, implementation TBD) that serves the files under <path> on a port of the local machine's public IP.  This fileserver is exposed to the internet, in typical use cases.  The fileserver is protected by the credential from the first step.
4. when the user hits ctrl-c, `kubectl` stops the file server and cleans up the secret.

When a user runs `kubectl run --local-temporary-volumes <local-path>:<mount-path>`, then the following things happen:
1. pod spec is generated, as it currently is for `kubectl run`
2. steps 1, 2 and 3 from `kubectl export-local-volumes` happen
3. pod spec is patched to add an item to `.spec.volumes` with the appropriate volume type.  
   1. appropriate volume type depends on the implementation we choose
   2. the volumeSpec references to the appropriate secret (the one from previous step), e.g. how `CephFSVolumeSource` has a `secretRef`.
   3. the volumeSpec specifies its server (e.g. `NFSVolumeSource.Server`) as the local hostname and the port chosen in the previous step)
4. pod spec is patched to add an item to the `.spec.container[0].volumeMounts`, using the added volumeSpec and the user-specified `<mount-path>`.
5. cleanup as in  `kubectl export-local-volumes` when run is done.
### Implementation alternatives

NFS mounting is probably most widely supported volume type (see #16741).  

NFS server distribution options:
- rely on kernel nfs server
  - won't work on windows, and maybe not on Mac.
- nfs server as a library written in pure go, run as a goroutine in kubectl
  - could not find an existing pure go NFS server.
- nfs server as a library in c, linked via cgo, run as a goroutine in kubectl.
  - changes our build process to build gco, could be headache for cross-platform builds
- ship an extra binary with kubectl that it will fork, which runs a userspace nfs daemon 
  - pain to ship extra binary with kubectl
- kubectl launches a userspace NFS server in a docker container
  - requires docker on the users machine, but most users will have docker for building images.
  - can use a containerized userspace nfs server such as https://github.com/macadmins/unfs3 
  - seems like best option

Alternative to NFS would be FUSE volume type on the client.  The fuse module could talk whatever protocol (e.g. https) to the server, which can be written in pure go and linked into kubectl. 

Nodes inside the cluster may be firewalled making it difficult for them to reach the kubectl-user's local machine via NFS protocol.  Some kind of proxy or tunnel may be needed too.

**Comment by erictune** [comment]
@pmorie @brendandburns

**Comment by thockin** [comment]
I like the goal, but I am not seeing how my (e.g.) GCE project will NFS
mount my laptop?

**Comment by pmorie** [comment]
+1 to Tim's sentiments.  I like this idea, and it will enable much faster workflows for people developing applications inside of Kube.  Of course, the devil's in the details.  It's too bad no one has written us a pure-go NFS server yet. :sob:

**Comment by erictune** [comment]
@thockin 

1. Run userspace nfs server on your laptop.
2. Run a temporary Pod on kuberenetes with "ssh" and "nc" in it.
3. run other end of ssh tunnel on your laptop.

**Comment by pmorie** [comment]
I guess there's no reason you have to run a userspace nfs server -- run one in a docker container and bind-mount your local dir into it.

**Comment by erictune** [comment]
@pmorie great point about running regular NFS in docker.

**Comment by smarterclayton** [comment]
We have the rsync command in OpenShift for this - it basically has a multi-tier strategy for keeping the remote in sync with local.  Doesn't have all the advantages of NFS, but does have the advantage it works everywhere.  https://github.com/openshift/origin/blob/7f2185eaae9cea0f61ceae678d3d08ccad8376e8/pkg/cmd/cli/cmd/rsync/rsync.go

**Comment by erictune** [comment]
I'll LGTM `kubectl rsync` if someone upstreams it.

**Comment by smarterclayton** [comment]
It's a lot of code :). But it does seem to work well across all the
major platforms.

**Comment by bgrant0607** [comment]
See also #13776

**Comment by wstrange** [comment]
For those that want to try the oc rsync command, I found that that the openshift cli seems to work fine against a vanilla 1.5.x GKE cluster. 

I just did a brew install openshift-cli and I was good to go.

This is a nice feature. It would be great if it was added to the kubectl command.
