### ISSUE TITLE
Why does kubernetes builds docker/libcontianer?

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#18006]
Hi all,

I am building kubernetes using ./hack/build-go.sh. And in doing that I see that we are getting docker and libcontainer and building them. I am not sure about that, but the code flow looks like that. My point is, if that is happening, why is it needed? Why can't I just have a docker installation ready and point k8s to my local docker API. And if is not happening, why are those in source code to compile and build? 

TIA.

**Comment by fabioy** [comment]
Kubernetes only builds and links to the Docker client library (building other Docker components may be side-effects of the Docker client build rules). K8S certainly doesn't run a custom Docker -- you must have a supported version of Docker installed (see various getting started guides that mention installing Docker, like: https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/docker.md)

Hope this helps clear things up.
