### ISSUE TITLE
Support node proxy subresource

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#18009]
We created and added "pods/proxy" subresource to remove the need for the generic top level prefix proxy. We should add the equivalent for node and convert all code to use it (code that does not have to be backwards compatible with a Kube 1.0 or 1.1 server, such as e2e). We should mark the "proxy/nodes" construct deprecated for 1.2. Forked from #15830.

**Comment by dchen1107** [comment]
I like the proposal here, but this is more like a call from api team. cc/ @kubernetes/kube-api

**Comment by bgrant0607** [comment]
cc @ncdc

**Comment by bgrant0607** [comment]
Yes, we intend to deprecate top-level prefixes like /proxy, /watch, etc.

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra
