### ISSUE TITLE
 Pods stuck in Graceful Termination after upgrading master to 1.1.2 with 0.19.3 nodes

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#18018]
This came up in late GKE testing. (As a reminder, GKE GA'd on 0.19.x, and we still have a number of customers with 0.19.x and 0.21.4 nodes.)

After upgrading the master, the old, upgraded system pods come up and stayed stuck in `Terminating` state. @mikedanese already identified the culprit on our internal bug: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L332

(As a meta-point, I'm really dubious of that code doing version string checking at all, rather than some sort of capability/API level check. :/)

**Comment by zmerlynn** [comment]
@mikedanese: This is fixed in `master` and v1.1, and I verified it on GKE, so closing. Thanks!

**Comment by ntquyen** [comment]
@zmerlynn I'm using k8s version 1.1.7 and get this issue, which I never get at previous version (1.0.6). Got some pods stuck at `Terminating` while the ReplicationControllers were removed, and the containers are actually running. One thing to note that all `Terminating` pods are scheduled in the same worker node. So I think there's something related related to the kubelet that node, but I don't know how to check.

I'm using docker version 1.7.1 under CoreOS v773.0.0
