### ISSUE TITLE
Allow user defined aliases in kubectl

### ISSUE THREAD

**Issue by sils** [kubernetes/kubernetes#18023]
Git allows me to set personal aliases which saves me a lot of typing work daily. I'd love to see this kind of possibility in kubernetes as well, that would really make my day.

**Comment by thockin** [comment]
I could swear this was a dup, but I can not find the previous one.

YES.  I want this (but I also want standard aliases for commands like desc->describe and del->delete)

**Comment by bgrant0607** [comment]
I like this idea, but we should move preferences out of kubeconfig before we add any more. #10693

**Comment by bgrant0607** [comment]
Would also like user-defined aliases for resources (pods, etc.), which could replace the hardcoded short names.

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by bgrant0607** [comment]
This could be a mechanism used to provide a list alias: #11210

**Comment by kargakis** [comment]
@kubernetes/sig-cli-feature-requests

**Comment by thockin** [comment]
@pwittrock Keep or kill?

**Comment by bgrant0607** [comment]
Not likely to happen in kubectl
