### ISSUE TITLE
AWS Load Balancer creation works only the first time

### ISSUE THREAD

**Issue by sils1297** [kubernetes/kubernetes#18021]
When I create a service for my pod via `kubectl.sh expose rc gitmate --port=80 --target-port=80 --type=LoadBalancer` on an AWS cluster that works. HOwever when I now `kubectl delete svc gitmate` and recreate the service with the same command as above no loadbalancer is created.

**Comment by sils1297** [comment]
Apparently this is not deterministic. Now the fourth time (after waiting a bit after deletion) it worked again. I definitely think there's something wrong, maybe it doesn't like me to delete and recreate within a certain timeframe.

**Comment by ultimateboy** [comment]
Deleting an ELB does take a few minutes at times. I'm guessing the creation is failing because the old ELB is still hanging around. I'd be interested in seeing the output of `kubectl describe service` and `aws ec2 describe-load-balancers` before and after a failed service creation.

**Comment by bigkraig** [comment]
I've seen this problem. there wasn't any messages in describe service and nor an old LB in the ec2 load balancers.

**Comment by rafaljanicki** [comment]
I thought I had the same problem, but I just gave Kubernetes time and it has created LBs correctly after some time (5-15 minutes). The time-to-create is definitely non deterministic.

**Comment by justinsb** [comment]
Fully creating an ELB definitely takes a little while; it is typically fast to create in the API (you should see a hostname in `kubectl describe service` within 30 seconds or less), but then it takes several minutes to actually start resolving and handling traffic.

Do you think there is an additional bug here though?  e.g. if you rapidly go Type=LoadBalancer => Type=ClusterIP => Type=LoadBalancer.  Or is it simply a matter of waiting 5 minutes?

If it's just a matter of waiting, I don't know if there's a great solution here.  We could delay showing you the ELB hostname until after we have verified it is serving traffic, but that just seems user unfriendly, as normally you still have to set up a CNAME and we're just delaying you being able to do that.  On the other hand, it's not exactly friendly to show you a hostname that doesn't work yet.

**Comment by justinsb** [comment]
This may be related to #21625

**Comment by thockin** [comment]
Can we get confirmation or refute on this issue?

**Comment by justinsb** [comment]
I believe this will be fixed by #22069.

Do we want to backport to 1.1  @a-robinson ?

**Comment by a-robinson** [comment]
Yes, #22069 should almost certainly this. I've opened #22251 to make it cherry-pickable. It's admittedly not a P0, but is something that it's tough for a user to fix on their own when the system messes up.
