### ISSUE TITLE
kubernetes-e2e-aws failing to start cluster

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#18037]
kubernetes-e2e-aws has been running daily for about a week and failing each time after trying to check for salt-master repeatedly:

    e2e.go:141: Error starting e2e cluster. Aborting.

Once this is green, should it be moved to critical builds?

**Comment by spxtr** [comment]
Also related, there is a case in `e2e.sh` for `kubernetes-e2e-aws-parallel`, but no corresponding Jenkins job.

**Comment by jlowdermilk** [comment]
Ping on this. Cluster up is succeeding now, but the e2e test driver is timing out waiting for kube-system pods to start running.

**Comment by ixdy** [comment]
any update on this?

**Comment by spxtr** [comment]
It looks like both aws and aws-1.1 are running tests, with one failing consistently on aws and several failing on aws-1.1.

**Comment by spxtr** [comment]
There is one test failing now.
```
[BeforeEach] Services
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:70
Feb 11 18:52:03.192: INFO: >>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-e2e-aws/workspace/.kube/config

[It] should be able to change the type and ports of a service
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:699
...
STEP: changing the TCP service to type=LoadBalancer
STEP: changing the UDP service to type=LoadBalancer
STEP: waiting for the TCP service to have a load balancer
Feb 11 18:53:08.217: INFO: Waiting up to 20m0s for service "mutability-test" to have a LoadBalancer
Feb 11 18:53:10.291: INFO: TCP load balancer: a999de63bd13311e59c500a99e494a48-1780227540.us-east-1.elb.amazonaws.com
STEP: waiting for the UDP service mutability-test to have a load balancer
STEP: waiting for the UDP service to have a load balancer
Feb 11 18:53:10.291: INFO: Waiting up to 20m0s for service "mutability-test" to have a LoadBalancer
Feb 11 19:13:10.433: FAIL: Timeout waiting for service "mutability-test" to have a load balancer
...

• Failure [1281.610 seconds]
Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:885
  should be able to change the type and ports of a service [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:699

  Feb 11 19:13:10.433: Timeout waiting for service "mutability-test" to have a load balancer

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1602
```

**Comment by brendandburns** [comment]
Assigning to @justinsb since I believe he is fixing this stuff.  Ping back if not true.

**Comment by justinsb** [comment]
Thank you.  I'm pretty sure this is fixed (I'm running the e2e tests locally using a simulate-Jenkins hack), and they are currently all green.  But once we get the pending PRs merged I will verify / investigate whether there is something wrong with Jenkins!

**Comment by fejta** [comment]
Jenkins is ran AWS tests on 3/1 and 2/29

**Comment by spxtr** [comment]
The cluster successfully comes up, but the two tests: `Services should be able to up and down services` and `SSH should SSH to all nodes and run commands` are failing. We can either close this and open a new issue or just track those here.

On release-1.1 branch there are lots of tests failing, but I don't think that's a priority.

**Comment by justinsb** [comment]
@spxtr those are failing on 1.2?  The default SSH username changed to "admin" if you're using jessie, which is now the default if you don't set KUBE_OS_DISTRIBUTION.  So KUBE_SSH_USER needs to be changed from ubuntu -> jessie.  I can file a PR for that.

I think service up and down is a flake, but I've seen it come and go also.

I would hope 1.1 should pass tests, but that shouldn't be a priority over 1.2.

I propose we close this and open 2 issues: default SSH username change, and 1.1 e2e being not happy.  And then if we see the service up and down again we open it...

**Comment by spxtr** [comment]
SGTM

**Comment by justinsb** [comment]
Opened those two issues; closing this one.
