### ISSUE TITLE
in certain error conditions, hack/update-codecgen.sh deletes types.generated.go files

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#18035]
then subsequent runs of hack/update-codecgen.sh succeed incorrectly since it searches for .generated.go files to update here:

https://github.com/kubernetes/kubernetes/blob/master/hack/update-codecgen.sh#L36

I workaround this by touching the files that are deleted an rerunning.

@madhusudancs ran into this and so did #18011

cc @wojtek-t

**Comment by sdminonne** [comment]
@mikedanese I had a fail in ./hack/update-api-reference-docs.sh and I ended up without some types.generated.go files

**Comment by mikedanese** [comment]
@sdminonne did you fix it by touching the types.generated.go files?

**Comment by sdminonne** [comment]
I did

**Comment by wojtek-t** [comment]
Yes - I'm aware of that. This is definitely a bug, but I'm not sure what's the easiest way to fix it.

**Comment by dims** [comment]
@mikedanese @wojtek-t : we can close this out right?

**Comment by wojtek-t** [comment]
Sure - closing because of age.
