### ISSUE TITLE
[typo] confusing flag usage `--bind-address` for apiserver

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#18049]
The usage for [`bind-address`](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L186), a flag for `apiserver`, is kinda odd. 

There is no flag `--read-only-port ` for `apiserver` to my best knowledge(instead, it's a flag for `kubelet`), which is referenced here.

Hopefully it's a typo. 
```
fs.IPVar(&s.BindAddress, "bind-address", s.BindAddress, ""+
		"The IP address on which to serve the --read-only-port and --secure-port ports. The "+
		"associated interface(s) must be reachable by the rest of the cluster, and by CLI/web "+
		"clients. If blank, all interfaces will be used (0.0.0.0).")
```

**Comment by lavalamp** [comment]
Yes, the --read-only-port was deleted quite some time ago. Good find.
