### ISSUE TITLE
Running versionize-docs in release-1.1 branch fails

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#18055]
Running

```
./build/versionize-docs release-1.1
```

in release branch fails with the following error:
```
Generating api reference docs at v1
Reading swagger spec from: ~/code/kubernetes/src/github.com/nikhiljindal/kubernetes/./hack/gen-swagger-doc/../api/swagger-spec/
Error response from daemon: v1/v1/ includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
```

The error is generated by the last line in versionize-docs:
`./hack/gen-swagger-doc/run-gen-swagger-docs.sh v1`

**Comment by nikhiljindal** [comment]
@karlkfi pointed out in https://github.com/kubernetes/kubernetes/pull/18048#issuecomment-161159358:

> Looks like the error message is just confusing: docker/docker#17734

> The host-dir can either be an absolute path or a volume name. In this case it's a relative path, which is no longer allowed since volume name support was added.

**Comment by nikhiljindal** [comment]
cc @caesarxuchao

**Comment by asalkeld** [comment]
The PRs are merged, can we close this issue?
