### ISSUE TITLE
docs/getting-started-guides/ubuntu-calico.md refers to old version of image calico/node

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#18062]
The doc refers to version v0.9.0 but the latest is v0.12.0.  I do not know if the difference is material.

**Comment by mwielgus** [comment]
cc: @djosborne

**Comment by spzala** [comment]
@MikeSpreitzer Hi Mike, I guess we can close this issue? I don't see ubuntu-calico.md exist any more or 0.9.0 mentioned anywhere. The ubuntu-calico.md is replaced with this one https://kubernetes.io/docs/getting-started-guides/ubuntu/  Thanks!

**Comment by MikeSpreitzer** [comment]
Yeah, I can not find the relevant document any more.  That is probably bad in itself.

**Comment by spzala** [comment]
@MikeSpreitzer agree, it seems like the docs changed totally. I also found the link was broken in itself and tried to fix it here https://github.com/kubernetes/kubernetes/pull/46348#issuecomment-303742484  If you think this issue no longer relevant, does it make sense to close it? Thanks!

**Comment by caseydavenport** [comment]
That doc was removed due to it being really out of date and not the recommended install pattern any more.

If there are remaining links to that document they should be removed in favor of links to either the kubeadm documentation or docs.projectcalico.org.

**Comment by MikeSpreitzer** [comment]
Yes, I think the table at https://kubernetes.io/docs/setup/pick-right-solution/#table-of-solutions should have a pointer into the Calico docs with "IaaS Provider" = "any" or "bare metal" or "N/A" or "don't care".

**Comment by spzala** [comment]
@MikeSpreitzer thanks, sounds good, looking at the table I guess the right repo is https://github.com/kubernetes/kubernetes.github.io

**Comment by MikeSpreitzer** [comment]
See https://github.com/kubernetes/kubernetes.github.io/issues/3892 for the successor issue.

**Comment by spzala** [comment]
Thanks @MikeSpreitzer
