### ISSUE TITLE
Kuberntes executor does not kill pod when mesos executor was killed

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#18066]
I was doing some test for k8s+mesos integration, and when the k8s executor was killed, all of the pods started by this executor continue running.

After check mesos executor code, the problem is that the k8s mesos executor did not implement the API of terminateTask() for executor. It is better to implement this API to kill all pods belong to this executor.

**Comment by k82cn** [comment]
/close 

moved to https://github.com/kubernetes-incubator/kube-mesos-framework/issues/73
