### ISSUE TITLE
deleting a 'deployment' doesn't take down dependent rc and pods

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes#18078]
With the deployment object, if you create a 'deployment' via:

    kubectl create -f deployment-file.yaml
then later run 

    kubectl delete -f deployment-file.yaml
it deletes the 'deployment' itself, as evidenced by the fact that

    kubectl get deployment 
no longer lists it, but the dependent rc and pods are still there and are not taken down.

This doesn't seem right... is this 'works as intended'?
I'm using the 1.1.2 release.

**Comment by amygdala** [comment]
Hmm, maybe this is related?- https://github.com/kubernetes/kubernetes/pull/18077

**Comment by nikhiljindal** [comment]
Yes we do not have cascading delete for deployments yet.
cc @kargakis @janetkuo

**Comment by kargakis** [comment]
> Hmm, maybe this is related?- #18077

Yes, it is.
