### ISSUE TITLE
Able to deploy but upon switching subscriptions it doenst deploy to Azure

### ISSUE THREAD

**Issue by ShadySQL** [kubernetes/kubernetes#18076]
azure_wrapper/exec: [ 'network',
  'vnet',
  'create',
  '--location=North Europe',
  '--address-space=172.16.0.0',
  'kube-internal-vnet-2986c057a962b8' ]
Generating a 2048 bit RSA private key
..............................................................+++
.....................................+++
## writing new private key to './output/kube_2986c057a962b8_ssh.key'

  error: unknown option `--address-space'

azure_wrapper/fail: Exiting due to an error.
azure_wrapper/info: Saved state into `./output/kube_2986c057a962b8_deployment.yml`
azure_wrapper/info: You probably want to destroy and re-run.

I destroyed it and re ran it again and again and again, etc and it still doesnt work. 

I go thru the entire sequence over and over again but it doenst want to deploy.

**Comment by bitsofinfo** [comment]
bump

**Comment by brendandburns** [comment]
Closing this as obsolete. Please use Azure Container Service or [ACS-Engine](https://github.com/azure/acs-engine) for deployment.
