### ISSUE TITLE
make salt blow up if release binaries are out of sync 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#18079]
Salt provisioners need to be in sync w/ binaries, otherwise `vagrant up` can fail .

I'm thinking we should be able to have salt confirm that the files in the binary are in sync with whats in the salt provisioner sources... The error message coule be fast and obvious enough that people could disable it if they wanted... for the typical use case, where you pull source down

otherwise you get something like this: 

```
[root@kubernetes-minion-1 vagrant]# diff /vagrant/cluster/saltbase/salt/kube-node-unpacker/init.sls /srv/salt/kube-node-unpacker/init.sls
4d3
<     - makedirs: True
```

**Comment by mikedanese** [comment]
Salt blew up because there was a bug in salt that was surfaced by old salt and new kube-up. This is a separate issue from ./cluster/kube-up.sh being a different version of _output/ (which can only happen in dev builds). That will generally work if they are of reasonably close versions and you aren't making a bunch of changes to both salt and kube-up. By asserting this, we make it slower to develop and iterate on cluster/

**Comment by jayunit100** [comment]
ok.. Added an env var that is printed on error, so shouldnt slow anyone down too much?  or you think its still a bad idea... ?

**Comment by jayunit100** [comment]
```

+      Release commit and source are out of sync!
+      Salt and or other configs need to be in sync with binaries or this operation can lead to unusable clusters.
+      To fix this error, just re-run "make quick-release" OR export IGNORE_BINARY_CHECK=true
```
this is what i was hoping to blurt out before dying.   as a developer this helps me (1) forces me to know the bare minimum details about salt that i need to self-manage (2) prevents from making errors.

**My thought** is that for any program: If there is a dependency on versions cli/serv, then the versions should be checked where possible.  Overriding the check should be easy, but the check should still occur.

**Comment by mikedanese** [comment]
Warning SGTM

**Comment by jayunit100** [comment]
okidoki... so your suggesting ... warning but proceed? i guess thats ok

**Comment by mikedanese** [comment]
Warning and proceed if certain expert mode envvar is set is also ok

**Comment by mikedanese** [comment]
To clarify, I think it's good to print a huge warning exit on this error but I want an envvar that allows me to skip the exit behavior when I'm developing on cluster/

**Comment by jayunit100** [comment]
yup gotcha

**Comment by jayunit100** [comment]
after playing with a few solutions, closing - this gets pretty hairy when we consider the myriad of providers.
