### ISSUE TITLE
Modifications to HPA e2e tests for performance profiling

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#18097]
We would like to modify the e2e-tests to quickly determine:
1. Measure how fast can an HPA adjust to a burst in traffic, and to what density via configuration parameters vs. magic numbers. 
2. Test for (N) overlapping HPA (lifecycles for G generations) in parallel, with random (R) replica sizes.

/cc @jayunit100 @DirectXMan12 @piosz @wojtek-t

**Comment by piosz** [comment]
cc @jszczepkowski @mwielgus

**Comment by jayunit100** [comment]
- The first modifications, to create the `scale(..)` generic function are done and lgtm.
- Next step: Adding tolerance support to Unit tests and tolerance feature.  
- Then will add in the e2e test which runs extremely low tolerance/low forbidden change thresholds.  This will accomplish (1).

For (2), I will specifiy some more details after finishing the above bullets.

**Comment by ihmccreery** [comment]
This doesn't look like a test infra issue as much as an HPA-specific test issue.  Removing test-infra label, feel free to clarify with what you all need from test-infra to get this done.

**Comment by jayunit100** [comment]
Hi, we've been ccing test infra on all HOA related issues as a matter of practicality. Wether the label is required I'm not sure

**Comment by ihmccreery** [comment]
@jayunit100 Thanks.  The `area/test` label is sufficient for test stuff, unless you have something specific to infra (e.g. need some modification to the e2e framework).

**Comment by mwielgus** [comment]
cc: @wasylkowski - you worked on something similar. Does your work fix the issue?

**Comment by wasylkowski** [comment]
I did not exactly do this, but I did add a test that measures HPA+CA performance using ginkgo's infrastructure. My test runs only once, but it can be run multiple times (not sure if in parallel, though).

The test is here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling/autoscaling_timer.go
