### ISSUE TITLE
Scheduler Performance Testing Proposal

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#18091]
We have found that on 1k nodes cluster scheduling takes 60-200 ms and becomes the bottleneck. We want to have a standard way to reproduce scheduling latency metrics result and benchmark scheduler as simple and fast as possible. Only with that can we: 1. figure out underlying behaviors and potential bottlenecks quickly; 2. publish results in a standard way and prevent future performance degradation.

We have the following goals:
- Goal 1: Save time on testing. More accurate scheduling latency.
  - We mock up kubelets and only measure scheduling latency and do not care about the latency to start the pod. This is different from Kubemark -- scheduled pods won’t be run by mocked kubelets. We only need to set up the master components.
- Goal 2: Profiling runtime metrics and find out performance bottleneck.
  - Write scheduler integration test. Take advantage of go test and profiling tools, like cpu-profiling, memory-profiling and block-profiling. This is very fine-grained metrics.
- Goal 3: Reproduce test result easily.
  - We want to have a known place to do the performance related test for scheduler. Developers should just run one script to collect all the information they need. 

We have the following plans for writing scheduler tests:
- density test (by adding a new Go test)
  - schedule 30k pods on 1000 (fake) nodes and 3k pods on 100 (fake) nodes
  - print out scheduling rate every second
  - let you learn the rate changes vs number of scheduled pods
- benchmark (by modifying the existing benchmark in integration or simply add a new one)
  - make use of `go test -bench` and report nanosecond/op.
  - schedule b.N pods when the cluster has N nodes and P scheduled pods. Since it takes relatively long time to finish one round, b.N is small -- level of 10.

We are new to k8s codebase. We also want to know where is the best place (directory) to commit in these tests? 

Any suggestions are welcomed!

**Comment by hongchaodeng** [comment]
This extends #17415

**Comment by davidopp** [comment]
@kubernetes/sig-scalability

**Comment by timothysc** [comment]
> schedule 30k pods on 1000 (fake) nodes and 3k pods on 100 (fake) nodes
> print out scheduling rate every second
> let you learn the rate changes vs number of scheduled pods

So density already does this... the one option it looks like you may want is custom control #18099 real or fake is irrelevant as the e2e's just need to point to an api-server. 

re: benchmarks, seems like we could simply add to the unit-tests.

**Comment by timothysc** [comment]
After chatting with @xiang90, lets add this as an agenda item for the SIG meeting tomorrow.

**Comment by wojtek-t** [comment]
+1 for adding benchmark (howeveer this should be integration test, not unit-test in my opinion)

**Comment by HaiyangDING** [comment]
cc @HaiyangDING @hurf 

@timothysc 
The next SIG on scheduler meeting is on 12.07, isn't it? If there is one tomorrow, can I have the information please?

**Comment by timothysc** [comment]
> howeveer this should be integration test, not unit-test in my opinion 

retract, +1 to @wojtek-t .  

> The next SIG on scheduler meeting is on 12.07, isn't it? If there is one tomorrow, can I have the information please?

@HaiyangDING I was adding this to the @kubernetes/sig-scalability list given the context, but it crosses over into both.

**Comment by hongchaodeng** [comment]
Slides from today's meeting:
https://docs.google.com/presentation/d/1HYGDFTWyKjJveAk_t10L6uxoZOWTiRVLLCZj5Zxw5ok/edit?usp=sharing

**Comment by timothysc** [comment]
Here are are the action item notes from the SIG meeting: 

- Everyone agrees this is a good idea and long overdue, but the question is where would this live:
-- New category of tests?  (isolated/sandbox’d/**component**)
-- The current testing structure allows to easily append.
-- create new directory (component) + hack/script to execute 
-- Future "we could" gate on known good data, and fail performance regressions
