### ISSUE TITLE
Replace dependency on "rbd" command by /sys/bus/rbd kernel interface

### ISSUE THREAD

**Issue by wienczny** [kubernetes/kubernetes#18107]
When using Kubernetes on platforms like CoreOS where additional commands can hardly be installed it's hard to get storage plugins working (see #17344 for examples). Please replace the dependency on the "rbd" command by using the sysfs kernel interface provided by rbd.ko. Some documententation is provided at http://docs.ceph.com/docs/argonaut/rbd/rbd-ko/.
If you don't want to completely remove "rbd" support a fallback to using the sysfs interface at least.

**Comment by zmerlynn** [comment]
cc @kubernetes/rh-storage

**Comment by rootfs** [comment]
@idryomov

**Comment by idryomov** [comment]
@rootfs I remember you saying you were working on something like this a couple of months ago.  As far as rbd goes, it's a fairly easy thing to do.  The sysfs interface is stable enough for you to rely on it (see "testing" in Documentation/ABI/README) and is documented, at least to some extent, in Documentation/ABI/testing/sysfs-bus-rbd.  Besides building the string that is fed to sysfs, rbd map loads the kernel module with the right options (just one parameter, really) and adds a key to the kernel keyring using the keys API (which you can also do directly with secret=key or so, but it's discouraged).  rbd unmap is a little more involved as it needs to translate its input (image name or device node) into an ID, but it all boils down to traversing sysfs.

The problem I have with this however is we would end up with two independent implementations of the same thing in different projects, which in the long run is bound to cause problems.  rbd map/unmap bits are well abstracted but not packaged into a proper library - would doing that and providing whatever bindings help?  What about using standard rbd map/unmap CLI from a privileged container?

OTOH rbd map/unmap commands use udev for waiting for the device to show up/go away and last I checked that didn't really work with namespaces, so an implementation that doesn't use udev might not be a bad thing (I'd still like it to live in ceph.git though).  IIRC @liewegas had tried to start a discussion on these topics but I don't think it went anywhere.

**Comment by liewegas** [comment]
The code that interfaces with /sys is already wrapped up in a tidy interface--it's just not currently built and packaged as a .so and rpm/deb.  Would providing a bare-bones rpm/deb that includes just that .so with no dependencies make it easy to reuse that code in your base container image (or whatever)?

**Comment by rootfs** [comment]
@idryomov @liewegas  Appreciate your information on this matter. And yes, there is a separate project #13691 on wrapping rbd cli inside a container. It would resolve the package dependency.
