### ISSUE TITLE
kube-proxy and api don't agree on a nodes hostname

### ISSUE THREAD

**Issue by evanphx** [kubernetes/kubernetes#18104]
On a brand new clustered created under v1.1.2 on AWS, kube-proxy is not able to find annotations for the current node because it uses `uname -n` by default, which yielded `ip-172-20-0-147`. APIserver has the name with a full hostname: `ip-172-20-0-147.us-west-2.compute.internal`.

Change the node itself to advertise it's full hostname via `uname -n` fixes the issue. That should be done by default on minion creation.

**Comment by thockin** [comment]
Do you run kubelet with the hostname override flag?

**Comment by evanphx** [comment]
@thockin: The salt setup does not set kubelet up that way, no.

**Comment by evanphx** [comment]
@thockin: My mistake. YES, salt does setup kubelet with --hostname-override, so the scripts that write out `/etc/default/kube-proxy` need to do the same as for `/etc/default/kubelet`.

**Comment by thockin** [comment]
yeah, if you use it on one piece of the node, you really need to use it on
all pieces :)

**Comment by evanphx** [comment]
Yup! Do you know where salt configures that? I didn't do it manually.

**Comment by evanphx** [comment]
Looks like this was fixed in https://github.com/kubernetes/kubernetes/commit/a739fc44c4da7c5ec2b4348de3766826c7e8d6dd!
