### ISSUE TITLE
Node acceptance tests: validate the most popular images

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#18111]
As part of node / guest image validation, we need to make sure the most popular images can running successfully on the node. The belowing are the top 32 OSS applications people came up a while ago. Since not all of them have reliable working image, I put them into two big buckets:

OSS applications with reliable image (> 15 stars from docker hub) 
1) Database: MySQL, MongoDB, Redis, Cassandra, PostGres
2) Messaging: RabbitMQ
3) CMS: Wordpress, Joomla, Drupal, Moodle, Media Wiki
4) Big Data: Hadoop, Spark
5) Commerce: Magento
6) Web serving: HAproxy, Lamp stack, Ruby stack
7) Development: GitLab, redmine, Jenkins 
8) Infrastructure: zookeeper, memcache,  Docker
9) Web serving: Node.JS, Django stack, Tomcat, JBoss, 
10) Search: Solr

OSS applications without reliable image (<=15 stars from docker hub)
1) SAAS: SugarCRM
2) DevOps: salt, chef, puppet

cc/ @andyzheng0831 @bgrant0607 @thockin @mikedanese: we discussed this before
cc/ @kubernetes/goog-node: Eventually we should automate the image validation process and include some of them or all to our node acceptance tests

**Comment by andyzheng0831** [comment]
cc/ @yinghan @wonderfly

**Comment by timstclair** [comment]
cc/ @zmerlynn

**Comment by zmerlynn** [comment]
There will probably be images from the https://github.com/kubernetes/application-images repo as we add to there. At the very least, you should add Spark already.

I'm not sure how you're planning on testing them though. I mentioned testing in #17027 in the context of images and templates as well, so, for instance, if we wanted to, we could embrace DM to help deploy all of these, and then we just need somewhere to put the tests.

**Comment by zmerlynn** [comment]
cc @jackgr

**Comment by dchen1107** [comment]
@zmerlynn Added Spark to the list. I also missed HAProxy in above list ealier. Thanks!

We can discuss in detail on how to deploy them to the node for testing.

**Comment by bgrant0607** [comment]
A few other potential candidates: Storm, Kafka, Consul, HDFS, ElasticSearch
