### ISSUE TITLE
Convert GCP projects used for test runs from pets to cattle

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18119]
Right now, our individual Jenkins jobs all run on separate projects.  Instead, we'd like to just have a pool of projects from which to draw, and let clusters that failed tests linger in their projects, (which will be quarantined,) so that people can inspect them.

**Comment by quinton-hoole** [comment]
Bear in mind that different Jenkins jobs require different project quotas (e.g. scalability tests require lots of VM's, routes etc).  So I'm guessing that you'll need a few pools, each with different quotas.

**Comment by quinton-hoole** [comment]
Why closed?

**Comment by goltermann** [comment]
@ihmccreery is this finished?

**Comment by ihmccreery** [comment]
This isn't even started.  The script I wrote is a decent workaround, so might make this issue obsolete, but that's for @fejta et al. to decide.
