### ISSUE TITLE
Establish how much time we're spending on Jenkins, and drive it to < 1hr / week

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18118]
Right now, @ixdy is our Jenkins SRE.

Action items:

- [x] Where is time on Jenkins spent; why did we need to spend time there; how can we avoid that in the future?
- [x] Documentation for:
  - Reboot Jenkins
  - Add a Jenkins slave
  - Turnup a Jenkins master

**Comment by fejta** [comment]
@ixdy please get this documentation submitted and close this out.
