### ISSUE TITLE
Kubernetes should support Go/Golang 1.5

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18117]
Go/Golang 1.3 is no longer supported, 1.4 works, I'm not sure if 1.5 is fully functional yet, and definitely isn't tested.

**Comment by pmorie** [comment]
@kubernetes/rh-cluster-infra

**Comment by mikedanese** [comment]
It's super broken right now. See #13838

**Comment by wojtek-t** [comment]
@mikedanese - it's not that bad I think.
We have exactly 2 issues with our unit tests and I think that both of them have in-progress fixes.

I would like to upgrade our testing infrastructure to Go 1.5 as soon as these are solved - hopefully in O(days)

**Comment by wojtek-t** [comment]
It seems that there are 2 issues that we need to solve that are still remaining:
- #18701 
- #18708

**Comment by angelalay** [comment]
There seems to also be a TLS handshaking  issue with 1.5. I'm experiencing the issue mentioned on this thread (http://stackoverflow.com/questions/32449316/kubernetes-on-mesos-tls-error-on-kubectl-exec) and I'm seeing from various sources that it could be due to 1.5?

**Comment by ixdy** [comment]
x-ref #14873

**Comment by ixdy** [comment]
and #19110

**Comment by angelalay** [comment]
Okay, verified that TLS handshaking issue is definitely due to compiling with go 1.5. Switching back to go 1.4 solved the issue I was seeing.

**Comment by ixdy** [comment]
Given that we've been building for close to a week with 1.5.3, I'm going to close.
