### ISSUE TITLE
pod failed for `no such image` with the image present

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#18127]
We've got a pod failing with message `no such image`, yet according to the events, the image had been pulled successfully. 

k8s version: v1.0.5

If there is no obvious behavior problem with `kubelet`, then the events should probably be handled better (time, event order).

```
$ kubectl describe pods test3-aaaaaaaaaaaaa-ykm5p
Name:				test3-aaaaaaaaaaaaa-ykm5p
Namespace:			default
Image(s):			wzreg:5000/appfile:test3-test2-1.0.war,wzreg:5000/scloudtool-tomcat:default,packetbeat:v1
Node:				10.10.103.131/10.10.103.131
Labels:				env=test3,name=test3-test2.war-1.0
Status:				Pending
Reason:				
Message:			
IP:				10.1.23.36
Replication Controllers:	test3-aaaaaaaaaaaaa (1/1 replicas created)
Containers:
  test3aaaaaaaaaaaaa:
    Image:		wzreg:5000/appfile:test3-test2-1.0.war
    State:		Waiting
      Reason:		no such image
    Ready:		False
    Restart Count:	0
....
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath				ReasonMessage
 
 Wed, 02 Dec 2015 14:25:12 +0800	Wed, 02 Dec 2015 14:51:51 +0800	145	{kubelet 10.10.103.131}	spec.containers{test3aaaaaaaaaaaaa}	pulledSuccessfully pulled image "wzreg:5000/appfile:test3-test2-1.0.war"
 Wed, 02 Dec 2015 14:25:12 +0800	Wed, 02 Dec 2015 14:51:51 +0800	145	{kubelet 10.10.103.131}	spec.containers{test3aaaaaaaaaaaaa}	pullingPulling image "wzreg:5000/appfile:test3-test2-1.0.war"
 Wed, 02 Dec 2015 14:25:12 +0800	Wed, 02 Dec 2015 14:51:51 +0800	145	{kubelet 10.10.103.131}	spec.containers{test3aaaaaaaaaaaaa}	FailedFailed to create docker container with error: no such image

**Comment by mqliang** [comment]
It seems that the image is garbage collected before the container is created. 

https://github.com/kubernetes/kubernetes/issues/18140

**Comment by dalanlan** [comment]
That's not the case, i'm afraid. The image is still present even if the pod is failing. 
To confirm this: we kill this pod, a new pod being scheduled to the same node (lucky me), and everything works well then.

**Comment by mqliang** [comment]
你是浙大的？

**Comment by dalanlan** [comment]
@mqliang yeah ;-)

**Comment by mqliang** [comment]
Me too. but I have graduated. I get my bachelor's degree form ZJU this year. And now I work in NetEase.

**Comment by dalanlan** [comment]
Cool. Had no idea that NetEase has started to contribute to the community though.

**Comment by mqliang** [comment]
I cleared my comments. Could you give me your Wechat account. We can have a chat.

**Comment by dalanlan** [comment]
@mqliang  I‘ve sent you a mail.

**Comment by mqliang** [comment]
Unfortunately you are not willing to, bad. Hoping I can have further discussions with you about k8s.

**Comment by dalanlan** [comment]
@mqliang Ah, i've sent you an e-mail which encloses my wechat id. Could you please kindly check your gmail (posted on your profile)?

**Comment by mqliang** [comment]
nice~

**Comment by pmorie** [comment]
@rh0cluster-infra

**Comment by dchen1107** [comment]
You are running 1.0.5 kubelet, which by default doing concurrent pulling. It is a known docker issue of concurrent pulling might corrupt the image. For 1.1 kubelet release, we decided to switch to serializing pulling by default to workaround such docker issue. You can upgrade your kubelet to 1.1, or you can remove such corrupted image manually. 

To verify what I said here: you can simply log into your node, and manually docker run wzreg:5000/appfile:test3-test2-1.0.war ....

**Comment by dalanlan** [comment]
>To confirm this: we kill this pod, a new pod being scheduled to the same node (lucky me), and everything works well then.

The image is not compromised.

**Comment by dalanlan** [comment]
@dchen1107 If you take a closer look at the event order/time, it's even more confusing. This needs to be sorted out. 
Also I don't believe it's a support issue;-)

**Comment by Tejeev** [comment]
@dalanlan what was the RC here?
