### ISSUE TITLE
Get Jenkins job configs under source control

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18122]

**Comment by spxtr** [comment]
First step: #17996

**Comment by pmorie** [comment]
Check out the Jenkins Job Builder.  I added support for the GH PR builder plugin earlier this year.

http://docs.openstack.org/infra/jenkins-job-builder/

**Comment by ihmccreery** [comment]
@spxtr Can you please add documentation for how to easily lint/check updates to a YAML file?

**Comment by spxtr** [comment]
Yes, that sounds like a good idea, along with an automatic check for PRs.

**Comment by spxtr** [comment]
Done. Next up: #21015
