### ISSUE TITLE
Critical builds should fail eagerly and handle flaky tests better

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18123]
Per @cjcullen's https://github.com/kubernetes/kubernetes/issues/10353#issuecomment-144833150.

**Comment by fejta** [comment]
@lavalamp is working on adding retry logic to ginkgo (Daniel feel free to just close this as a dup of that if you want)

**Comment by lavalamp** [comment]
@fejta I interpret this as two requests, neither of which I'm doing:

* turn on the fast fail option -- I think this is pretty debatable actually
* flaky test handling on post submits -- this is already fixed.

Closing, reopen if you think fast fail would be net good.
