### ISSUE TITLE
Improve test results visualization

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18121]
It's really hard to see what tests failed across different runs, especially if you don't have access to Jenkins (#17443).

**Comment by pmorie** [comment]
Is this distinct from #17443?

**Comment by ihmccreery** [comment]
Yes. #17443 is "I don't work at Google, I need to see test results."

This is "I work wherever, and I have questions about what's passing, what's flaky, what should be passing, and I want an easy-to-use visualizer for," maybe something like [what Buildbot provides](http://trac.buildbot.net/wiki/ScreenShots).

**Comment by ihmccreery** [comment]
Oops, but this *is* a duplicate of #17079.  Closing in favor of that.
