### ISSUE TITLE
scheduler: using inefficient math library causes significant slowdown

### ISSUE THREAD

**Issue by xiang90** [kubernetes/kubernetes#18126]
We did a few benchmark and profiling tests for the scheduler for 1000 nodes cluster.

We found the scheduler component is the bottleneck of starting pods. And it spents most of the time in an external pkg (https://github.com/kubernetes/kubernetes/blob/master/pkg/api/resource/quantity.go#L27) that handling math operations.

Profiling result for schedule 1000 pods over 1000 nodes:
https://storage.googleapis.com/profiling/org.svg

By giving the library a closer look, I found it does too many unnecessary allocations and causes GC pressure.

By mocking an efficient version of rounding function (do not handle overflow), we reduced nearly 50% of the latency for secluding 1000 pods(23s vs 53s). As we scheduled more pods, the effect getting more significant since it generates more objects per schedule.

New profiling result for schedule 1000 pods over 1000 nodes:
https://storage.googleapis.com/profiling/fix.svg

Any suggestion on how we should improve this?

/cc @hongchaodeng @lavalamp @philips

**Comment by xiang90** [comment]
@kubernetes/sig-scalability

**Comment by lavalamp** [comment]
Probably just doing the rounding once per pod (instead of per pod-node combo as I'm sure it does now) would be sufficient--caching or doing something like a constructor.

Alternatively, writing a special-purpose Value/MilliValue function probably could solve this.

@timstclair is making some changes to quantity right now.

**Comment by xiang90** [comment]
> Alternatively, writing a special-purpose Value/MilliValue function probably could solve this.

That is what I did for the mock up. This seems not to be very hard. Or we can fix the upstream library if we want. 

@timstclair Any idea?

**Comment by timstclair** [comment]
I think once https://github.com/kubernetes/kubernetes/pull/17548 goes in, we should just optimize `ScaledValue()`. The math around scaling values up without overflow is a little tricky though (I think we just need to grab the right chunk of bits `q.Amount().UnscaledBig().Bits()`, and twiddle them to get the base10 scaled value.

**Comment by xiang90** [comment]
@timstclair Great! Let me know when it is merged. I am happy to work on the optimization.

**Comment by gmarek** [comment]
@xiang90 - this sounds very promising. Thanks a lot!

**Comment by wojtek-t** [comment]
@xiang90 - great job!

**Comment by timothysc** [comment]
:+1:

**Comment by davidopp** [comment]
ref/ #18418

**Comment by xiang90** [comment]
Closed by #18170
