### ISSUE TITLE
Image gc is racy

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#18140]
Image gc is racy: When kubelet creates a  docker container, it must pull a image if the image is not on the node. Just after the image is pulled and before the container is created, the image may be unfortunately garbage collected since there is no container using this image.

I am glad to submit a PR to help fix this(in a couple of days).

**Comment by dalanlan** [comment]
I don't believe so. The default gc policy is much less aggressive than you thought.

**Comment by pmorie** [comment]
@kubernetes/rh-cluster-infra

**Comment by dchen1107** [comment]
Do you know why image garbage collection is kicked out? Is it possible you are hitting Out-of-Disk issue? Maybe you have a too small disk here.

**Comment by mqliang** [comment]
@dalanlan It seems so. remove the related issue section.

**Comment by mqliang** [comment]
@dchen1107 Usually,  image garbage collection is triggered by insufficient  disk space. But there are two flags to control image gc policy:
```
fs.IntVar(&s.ImageGCHighThresholdPercent, "image-gc-high-threshold", s.ImageGCHighThresholdPercent, "The percent of disk usage after which image garbage collection is always run. Default: 90%%")
fs.IntVar(&s.ImageGCLowThresholdPercent, "image-gc-low-threshold", s.ImageGCLowThresholdPercent, "The percent of disk usage before which image garbage collection is never run. Lowest disk usage to garbage collect to. Default: 80%%")
```
And a flag to control Out-of-Disk policy:
```
fs.IntVar(&s.LowDiskSpaceThresholdMB, "low-diskspace-threshold-mb", s.LowDiskSpaceThresholdMB, "The absolute free disk space, in MB, to maintain. When disk space falls below this threshold, new pods would be rejected. Default: 256")`
```

Using default settings, assume we has a node with 50G disk space(I think a 50G disk is normal), when 45G disk space has been used, image GC will be kicked out. However, the `LowDiskSpaceThresholdMB` is 256M, which mean new pod can be scheduled to this node. In such a case, the image of the new pod may be unfortunately garbage collected before the container is created.

**Comment by mqliang** [comment]
My PR to help fix this https://github.com/kubernetes/kubernetes/pull/18151

**Comment by mqliang** [comment]
https://github.com/kubernetes/kubernetes/pull/18820 has been merged. This could be closed.
