### ISSUE TITLE
How to pass JSON to kubectl create

### ISSUE THREAD

**Issue by gabipetrovay** [kubernetes/kubernetes#18149]
`kubectl create` takes the -f argument:

```
-f, --filename=[]
```

Can this be a list of files? If yes, how? If no, how can you pass then the JSON description of a service, replication controller and pods in the same file?

**Comment by thockin** [comment]
We're making an effort to handle support/information requests like this through StackOverflow.  Please ask this there, where our user-support people will see it most readily and where it can benefit the largest audience.  This is a good question.
