### ISSUE TITLE
TODO for 1.2: cut a new kube2sky image and bump the DNS versions

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#18159]
We've had a change or two in kube2sky, so we'll need to cut a new image eventually.  Nothing worth cherry-picking to 1.1 yet.

**Comment by pmorie** [comment]
@kubernetes/rh-networking

**Comment by eparis** [comment]
I saw the pflag change, was there a big one I missed?

**Comment by thockin** [comment]
no, but we don't want to not cut a new build and I tend to forget things :)

**Comment by ArtfulCoder** [comment]
done.
