### ISSUE TITLE
Update HPA tolerance to be a flag 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#18155]
We'd like tolerance to be settable to a low value (for e2es) and of course a high value for some clusters which don't want too much unnecessary jitter.  I'll update with a PR shortly...  This can be an isolated fix.

**Comment by jayunit100** [comment]
cc @timothysc @piosz  part of the #18097

**Comment by piosz** [comment]
cc @jszczepkowski

**Comment by pmorie** [comment]
@DirectXMan12

**Comment by ihmccreery** [comment]
As far as I understand, this isn't something the test-infra team needs to be working on.  Please correct me if I'm wrong, but I'll remove the label until then.

**Comment by mattjmcnaughton** [comment]
Is this still a feature of interest? I see the `TODO:` still exists. If so - I'd love to take a stab. I've been looking for a starter project for the auto-scaling code base, and it seems like this could be a good fit.
