### ISSUE TITLE
Eliminate dependency on tools.EtcdClient from contrib/mesos/pkg

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18153]
Context: We're going to completely get rid of "tools.EtcdClient" interface.
Instead, we wish everyone to use storage.Interface.

Mesos code is the biggest (non-trivial) remaining part of dependency on "tools.EtcdClient" - the following files depend on it:

contrib/mesos/pkg/election/etcd_master.go
contrib/mesos/pkg/election/etcd_master_test.go
contrib/mesos/pkg/scheduler/service/service.go

@sttts @karlkfi @timothysc

**Comment by sttts** [comment]
@wojtek-t we will discuss internally how to get rid of that dependency soon. We don't like this the current situation to access the etcd in parallel to the apiserver either.

**Comment by lavalamp** [comment]
Maybe temporarily we can just move that code under the mesos/ directory?

**Comment by jdef** [comment]
this appears to have been resolved by #18635. granted, the mesos code is still storing things in etcd using the "keys API" but at least there no longer a dependency on `tools.EtcdClient`

**Comment by timothysc** [comment]
yup, @lavalamp please close.
