### ISSUE TITLE
Make the quick start page a bit 'higher level'

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes#18166]
The [quickstart](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/quick-start.md) is likely where a lot of people new to Kubernetes jump in, and I feel like its current content is not necessarily doing us any favors.  IMO we should give an example at a bit higher level of abstraction and more declaratively (e.g. create a simple 'all-in-one' file that starts up an nginx RC + service), instead of running a command that will look to a new user like they're just starting up some containers. (We can swap in a Deployment object example a bit down the road).  This page should also, IMO, include a lot more links to the descriptions of the various introduced concepts.

I could take a stab at this change, but there are probably lots of opinions as to what this page should contain, so I want to make sure there's some buy-in on the general idea before I do that.

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by bgrant0607** [comment]
cc @kubernetes/docs

**Comment by bgrant0607** [comment]
I disagree about kubectl run vs. declarative. 

Whatever we do will be covered by the doc overhaul:

https://docs.google.com/document/d/12Nfj2E8tZL-CMnnpkSH9m5k_oqd4qJh4qDwYDxPGJJI/edit?ts=5705b1fc#bookmark=id.hd0knav8aqkb
