### ISSUE TITLE
Complex lists render poorly with redcarpet in gh-pages

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#18168]
Ex: http://kubernetes.io/v1.1/docs/getting-started-guides/dcos.html
Source: https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/dcos.md

It looks like redcarpet doesn't want to allow linebreaks with indented blocks in bulleted/numbered lists.

Does anyone know if there is an easy way to work around this?

Has anyone tried the kramdown formatter with github mode enabled?

It looks like redcarpet was used because kramdown didn't support code fences (https://github.com/kubernetes/kubernetes/pull/11584), but I'm not sure that's true with "Github Flavored Markdown" mode enabled.

http://jekyllrb.com/docs/configuration/#markdown-options

/cc @thockin @nikhiljindal @caesarxuchao @bgrant0607

**Comment by caesarxuchao** [comment]
The link to the gh-pages source:
https://raw.githubusercontent.com/kubernetes/kubernetes/gh-pages/_v1.1/docs/getting-started-guides/dcos.md

**Comment by karlkfi** [comment]
Looks like a workaround is to use 4 space indentation in lists instead of 2.
Ex: http://kubernetes.io/v1.1/docs/getting-started-guides/mesos-docker.html
Src: https://raw.githubusercontent.com/kubernetes/kubernetes/gh-pages/_v1.1/docs/getting-started-guides/mesos-docker.md

Great, so i can fix the source myself. Is there a way to automate or enforce this by commit hook or munger?

**Comment by bgrant0607** [comment]
Yeah, we use mungers extensively to address these kinds of quirks.
https://github.com/kubernetes/kubernetes/tree/master/cmd/mungedocs

**Comment by karlkfi** [comment]
Automating detection of markdown lists seems to be more than a 2hr project. I give up for now. I'll just fix the indentation on my doc.

**Comment by karlkfi** [comment]
Resolving the dcos doc issue with #18181

**Comment by thockin** [comment]
For history we started with kramdown and switched to redcarpet because ...
I can't recall why but krandown was getting something really wrong...

**Comment by karlkfi** [comment]
dcos guide formatting has been fixed: http://kubernetes.io/v1.1/docs/getting-started-guides/dcos.html

I wasn't able to figure out how to write a munger for it in a reasonable amount of time. Someone else is welcome to try...

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by bgrant0607** [comment]
We're no longer using redcarpet, I believe.
