### ISSUE TITLE
gitRepo volume order matters

### ISSUE THREAD

**Issue by owenhaynes** [kubernetes/kubernetes#18167]
Kubernetes 1.1.2 on AWS 

If you have a secret volume before a gitRepo volume in the volumes list,  the gitRepo will not mount as it does not create the folder, it complains that it can not clone as the target folder does not exist, which is true the folder does not exist on the node.

**Comment by pmorie** [comment]
@kubernetes/rh-cluster-infra @kubernetes/goog-node

**Comment by thockin** [comment]
Post YAML?

**Comment by dchen1107** [comment]
cc/ @saad-ali

**Comment by owenhaynes** [comment]
Here is the describe for the pod when its failing and the rc controller

```json
{
  "apiVersion": "v1",
  "kind": "ReplicationController",
  "metadata": {
    "name": "test",
    "namespace": "test",
    "labels": {
      "app": "test",
      "type": "system"
    }
  },
  "spec": {
    "selector": {
      "app": "test",
      "type": "system"
    },
    "replicas": 1,
    "template": {
      "metadata": {
        "labels": {
          "app": "test",
          "type": "system"
        }
      },
      "spec": {
        "imagePullSecrets": [
          {
            "name": "test"
          }
        ],
        "containers": [
          {
            "name": "test",
            "image": "test",
            "imagePullPolicy": "Always",
            "ports": [
              {
                "name": "https",
                "containerPort": 443
              },
              {
                "name": "http",
                "containerPort": 80
              }],
            "volumeMounts": [{
              "name": "forgetest-ssl",
              "mountPath": "/etc/nginx/ssl/",
              "readOnly": true
            },
              {
                "name":"novnc",
                "mountPath": "/mnt/novnc",
                "readOnly": true
              }]
          }
        ],
        "volumes": [
          {
            "name": "test-ssl",
            "secret": {
              "secretName": "test-ssl"
            }
          },
          {
            "name": "novnc",
            "gitRepo": {
              "repository": "http://github.com/kanaka/noVNC.git",
              "revision": "fc00821eba469641c6c94706726c3d78e46460a2"
            }
          }
        ]
      }
    }
  }
}


```



```
Name:				test-iqkew
Namespace:			test
Image(s):			someimage:latest
Node:				
Start Time:			Fri, 04 Dec 2015 08:16:00 +0000
Labels:				app=test,type=system
Status:				Pending
Reason:				
Message:			
IP:				
Replication Controllers:	test (1/1 replicas created)
Containers:
  service-manager-http:
    Container ID:	
    Image:		someimage:latest
    Image ID:		
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  test-ssl:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	test-ssl
  novnc:
    Type:	GitRepo (a volume that is pulled from git when the pod is created)
    Repository:	http://github.com/kanaka/noVNC.git
    Revision:	fc00821eba469641c6c94706726c3d78e46460a2
  default-token-8hfze:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	default-token-8hfze
Events:
  FirstSeen	LastSeen	Count	From							SubobjectPath	Reason		Message
  ─────────	────────	─────	────							─────────────	──────		───────
  19s		19s		1	{scheduler }								Scheduled	Successfully assigned 
  19s		7s		3	{kubelet }			FailedMount	Unable to mount volumes for pod "service-manager-http-iqkew_forge-service-manager": failed to exec 'git clone http://github.com/kanaka/noVNC.git': : chdir /var/lib/kubelet/pods/40b73896-9a5f-11e5-a6ee-06900dd99da5/volumes/kubernetes.io~git-repo/novnc: no such file or directory
  19s		6s		3	{kubelet }			FailedSync	Error syncing pod, skipping: failed to exec 'git clone http://github.com/kanaka/noVNC.git': : chdir /var/lib/kubelet/pods/40b73896-9a5f-11e5-a6ee-06900dd99da5/volumes/kubernetes.io~git-repo/novnc: no such file or directory

```

**Comment by resouer** [comment]
Thanks for reporting and yes, I think this can be confirmed as a bug. 

GitRepo and Secret volume all depends on a wrapper EmptyDir, which will check if it is ready before creating the needed dirs, see: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/empty_dir/empty_dir.go#L165

So,  the Secret volume you defined first will set this wrapper EmptyDir as `ready`, then the GitRepo plugin will return immediately when seeing this flag, without executing the rest processes like `mkdir novnc` etc

Why it works when volumes are reversed? Because though `ready` flag is also set, Secret volume is a tmpfs volume, thus apply to https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/empty_dir/empty_dir.go#L166 but`!notMnt` is false, so it will continue the rest processes. 

I can send a patch anyway.

**Comment by pmorie** [comment]
@resouer I don't think it's quite the way you articulated.  The emptyDir plugin uses a directory per volume to hold the ready file -- so the ready file for one volume should never affect another volume.

**Comment by thockin** [comment]
Still, this is pretty scary if it reproduces.  Paul - do you or your
minions have time to dig in and verify/refute/debug ?

**Comment by pmorie** [comment]
@thockin I'll try to reproduce it.

**Comment by resouer** [comment]
@pmorie @thockin  I have already reproduced it. Here is the detail:
```
/plugins/kubernetes.io~empty-dir/ready // for emptyDir
/plugins/kubernetes.io~git-repo/ready // for gitRepo
/plugins/kubernetes.io~secret/rady // for secret
```
Your secret volume will create the `ready` file in `empty-dir`, then when your gitRepo create wrapper empty-dir, it will check that file and skip the all the rest.

That's because the getMetaDir here `if volumeutil.IsReady(ed.getMetaDir()` refers to `empty-dir`, not the `git-repo` or `secret` dir

But it's the `ready` file in emptyDir cause the problem.

**Comment by thockin** [comment]
/plugins ?  Do you mean that literally or
/var/run/kubelet/pods/123456678/plugins/ ?

**Comment by resouer** [comment]
@thockin yes, sorry for my lazy paste ...

**Comment by thockin** [comment]
You had me scared.  Can you paste a full path - it should include both the
pod ID and the volume name.  Specifically the code is:
`path.Join(ed.plugin.host.GetPodPluginDir(ed.pod.UID,
util.EscapeQualifiedNameForDisk(emptyDirPluginName)), ed.volName)`

**Comment by resouer** [comment]
```
/var/lib/kubelet/pods/df99e5c5-9e56-11e5-9b84-f8bc1298bf82/plugins/kubernetes.io~empty-dir/ready

ls /var/lib/kubelet/pods/df99e5c5-9e56-11e5-9b84-f8bc1298bf82/plugins/kubernetes.io~
kubernetes.io~empty-dir/ kubernetes.io~git-repo/  kubernetes.io~secret/ 
```
All the dirs are above.

**Comment by thockin** [comment]
It's supposed to have the volume name in the path.  Here's what is
happening.  When we 'wrap' another volume like this, we have to create the
wrapper structure.  You can see here (
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/secret/secret.go#L114)
that we are not passing a name.

NewWrapperBuilder() should assert that name is not empty.  This means that
all wrapper need to copy the spec for the wrappee and populate name with
something.  Name probably should not be the same name as the wrapper, or
risk conflicts.  Something random?

This is pretty nasty.  Paul - any bandwidth on your guys end?

**Comment by resouer** [comment]
Yes, I also noticed that line. I once thought it as designed by that. 

So you are suggesting that Secret and GitRepo etc should have their own emptyDir path, right?

**Comment by resouer** [comment]
Just proposed a way in #18445 PTAL cc @pmorie  :)

**Comment by pmorie** [comment]
@resouer Classy digging for finding this :trophy:
