### ISSUE TITLE
Modify conformance test policy to use tests from release branches

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#18162]
Currently conformance testing uses the 'conformance-test-v1' branch.  We've run into issues where this branch doesn't get as actively maintained as the release branches.  This is an umbrella issue to cover migrating to a new conformance test policy.  See discussion in #17536 for more details

New conformance tests policy: tests should be run off of the release branch that corresponds to the level of conformance being tested, eg:
- the release-1.0 branch should be used to test that a given cluster conforms up to v1.0
- the release-1.1 branch should be used to test that a given cluster conforms up to v1.1
- conformance tests are not guaranteed to be stable on the master branch, but stabilized once a release-X.Y branch is created

Proposed steps
- [x] update documentation for conformance testing (#14913)
- [x] update conformance test scripts to work according to the new policy
- [ ] ensure conformance tests pass according to the new policy, bug fix / cherry-pick as appropriate
  - [x] release-1.2 branch passes against a v1.2 cluster on AWS
  - [x] release-1.2 branch passes against a v1.2 cluster on GCE
  - [x] release-1.1 branch passes against a v1.1 cluster on AWS
  - [x] release-1.1 branch passes against a v1.1 cluster on GCE
  - [ ] release-1.1 branch passes against a v1.2 cluster on AWS
  - [ ] release-1.1 branch passes against a v1.2 cluster on GCE
- [x] update CI scripts as appropriate
- [ ] cleanup
  - [x] remove hack/conformance-test.sh, cluster/test-conformance.sh
  - [x] remove conformance-test-v1 branch (#17536)
  - [x] close out #16860
  - [x] close out #12014

related, #12941

**Comment by spiffxp** [comment]
/cc @ihmccreery @quinton-hoole @lavalamp @karlkfi @ixdy @jbeda @countspongebob 

Let me know if I left out any interested parties or steps.

I'm not super familiar with the hack/build scripts but I'm happy to take a crack at them.

Unsure if it makes sense to open an issue for each of those conformance combinations.  I was planning on opening bug-fix issues as I run into them for the AWS runs.  I don't yet have GCE access so will look to @ihmccreery for help there.  May need some assistance from @quinton-hoole on the CI side of things.

**Comment by zmerlynn** [comment]
@kubernetes/goog-testing

**Comment by karlkfi** [comment]
How do we know what conformance tests a particular branch is supposed to satisfy (programmatically)?

How do we programmatically ensure that new changes don't break conformance?

Do we need to run conformance tests from master and all previous releases on every PR change?

How do we make sure that master conformance tests is stable before we cut a new release?

**Comment by spiffxp** [comment]
My 2 weakly-held cents:

>How do we know what conformance tests a particular branch is supposed to satisfy (programmatically)?

Use the latest revision of the latest release branch in your commit's ancestry.  If you're on or branched off of a release branch, use the latest revision of that release branch.  If you're on master, use the latest revision of the latest release branch.  This should ensure you're remaining backwards compatible with the most recently released version of kubernetes.

>How do we programmatically ensure that new changes don't break conformance?

We should (eventually) gate on conformance tests from the latest release branch.  I'm not familiar with how many of the conformance tests are already included/excluded from the e2e runs that happen today.

>Do we need to run conformance tests from master and all previous releases on every PR change?

My vote would be no for master, and yes for releases.  For example, we would ensure that changes to the release-1.2 branch don't break v1.0 or v1.1 compatibility.

It would be nice to save some effort and assume that, eg: the release-1.1 tests passing would imply v1.0 compatibility as well, but I'm not sure that's a safe assumption.

>How do we make sure that master conformance tests is stable before we cut a new release?

My vote would be to focus on stabilizing conformance tests after a release branch has been started, but before an actual (beta?) release has been cut.  Eventually it would be nice to see conformance testing against a variety of cluster configurations/deployments as part of the release process.

**Comment by ihmccreery** [comment]
Mostly agreed, with some minor changes.

> My vote would be no for master, and yes for releases. For example, we would ensure that changes to the release-1.2 branch don't break v1.0 or v1.1 compatibility.

That sounds like a recipe for scrambling when we branch and realize we broke v1.0 conformance two months ago on master.  :smile: I'd much prefer to keep master conformant.  This is additionally a step in the right direction for, and related to, #17263.

> My vote would be to focus on stabilizing conformance tests after a release branch has been started, but before an actual (beta?) release has been cut. Eventually it would be nice to see conformance testing against a variety of cluster configurations/deployments as part of the release process.

Per [versioning.md](https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md#release-versioning), branching and cutting the beta version happen at the same time.  This is precisely to avoid having to do a bunch of catch-up work once the branch is already cut.  (Note we didn't do this for v1.1, and paid for it in many, many cherry-picks.)

**Comment by spiffxp** [comment]
>That sounds like a recipe for scrambling when we branch and realize we broke v1.0 conformance two months ago on master.

True.  Maybe I'm overestimating the add'l overhead this would add.  Just thinking down the line when we have N releases, it may be expensive / slow to do N compatibility checks on every commit.  Since master is in such high flux, capture that with a regularly scheduled job rather than gate per-commit.  But do it per-commit for the release branches.

>Per versioning.md, branching and cutting the beta version happen at the same time.

Would mandating that conformance tests pass prior to cutting alpha releases off of master make sense then?  I could see that imposing too much of a code-freeze mentality on master.  Alternatively, we focus on stabilizing conformance tests after the first beta release is cut, prior to the first non-beta release.

**Comment by ihmccreery** [comment]
> capture that with a regularly scheduled job rather than gate per-commit.

Definitely.  The conformance tests are (should be?) a subset of the tests we run continuously from HEAD anyway.

> But do it per-commit for the release branches.

Yeah, it's about equivalent.  Again, long-run it should be a subset of the tests we're running on a per-PR basis anyway.

> Would mandating that conformance tests pass prior to cutting alpha releases off of master make sense then?

I reckon so.  Right now we look for stability in our e2e's for a given build before marking it an alpha release.  Conformance should be one of those builds.  I'd love to see us start making progress on #4871 (wow, that's an old issue!) which would allow us over at Google (the ones cutting releases) know if a given build is passing for other providers.

**Comment by karlkfi** [comment]
I'm pursuing this strategy with the Mesosphere CI. We will probably end up running conformance tests from both release-1.1 and master when a new PR is made. I've backported our test harness changes to make this possible: #18686

**Comment by spiffxp** [comment]
I'm a good distance away from being able to contribute back to this, @karlkfi 's work in #18686 seems like a much further start than I have, and is already much better integrated with the existing build scripts

**Comment by ihmccreery** [comment]
I'm moving this to P0 and v1.2 milestone per community discussion today.

**Comment by ixdy** [comment]
What needs to be done here?

**Comment by jayunit100** [comment]
Ok, crafted two PRs to get us going.  

- #22379 
- #22380

**Comment by spiffxp** [comment]
@ixdy it's probably a matter of digging up links that prove each of the items above has been addressed; PR's linked by @jayunit100 and work previously done by @ihmccreery have probably addressed the documentation concerns

two biggest things are probably: 
- release-1.0: do we want to invest the time backporting all the release-1.1 cherry picks?  do we document it as a special case?
- aws: what happened to kubernetes-e2e-aws results linked from submit queue? if I guess the bucket name, it looks like they haven't been generated in a week or so?  As an alternative, @justinsb has results available at https://console.cloud.google.com/storage/browser/kubernetes-buildlogs-aws/logs/kubernetes-e2e-aws/ that look promising for a snapshot of a point in time, but AFAIK they're not running automatically on each PR

**Comment by spxtr** [comment]
Here's the latest kubernetes-e2e-aws results: https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-aws/160/

We only run this once a day.

**Comment by bgrant0607** [comment]
Does this need to be attached to the 1.2 milestone?

**Comment by spiffxp** [comment]
As a stake in the ground, yes.  I suspect the remaining work is docs.  Will see if I can put some cycles to this today.

**Comment by spiffxp** [comment]
Vetting release-1.0 doesn't make sense at this point, and would require a lot of backporting that I'm not sure anyone's heavily incentivized to do here.  Bumping up to release-1.1 and release-1.2

**Comment by fejta** [comment]
Anything else for this one?

**Comment by spiffxp** [comment]
1.1 tests don't pass against 1.2 clusters on both GCE and AWS, I'm working to repro and open issues for the specific tests that fail

**Comment by spiffxp** [comment]
I think that's all of them.  I'll try to dig into these issues as I get time.  I'm not sure if there's CI coverage around these particular failures or not.  Will look into whether I've got an CI cycles to spare there

**Comment by spiffxp** [comment]
should have been closed a while ago
