### ISSUE TITLE
Flags - use Durations or just use ints?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#18180]
We have both Duration-type flags (e.g. "2s" or "5m" are valid values) and we have int-typed time flags (usually seconds, but few are named as such).

Which should we be using?

**Comment by bgrant0607** [comment]
Related to #6013.

My preference is Duration.

**Comment by bgrant0607** [comment]
BTW, @thockin I assumed this is about k8s component binaries. That will be irrelevant, anyway, once we switch to config, where I believe we are using Duration already.
cc @mikedanese

**Comment by mikedanese** [comment]
Ya, and it's easy to do this with unversioned.Duration while we are still binding flags to the componentconfig objects. See:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L132-L134

**Comment by thockin** [comment]
Yeah, I'm fine leaving flags as-is and moving all time-related options to
duration.

**Comment by spzala** [comment]
@mikedanese Hi, a gentle touch base :), are we there to close this issue? Thanks!
