### ISSUE TITLE
Move unversioned#testClient to another package

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#18186]
When writing test for the generated client code, I want to reuse the `unversioned#testClient` (https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/client_test.go#L58). But that creates circular dependency, because `unversioned#testClient` needs to import the generated client, while the generated client needs to import `unversioned` package to access common objects like `RESTClientFor`, `Config`, etc. 

My proposal is moving `unversioned#testClient` to `pkg/client/unversioned/test#testClient`. What do you think? @lavalamp 

parent issue: #17468

**Comment by lavalamp** [comment]
SGTM

**Comment by lavalamp** [comment]
P1 since it's blocking you.
