### ISSUE TITLE
salt 2014.7 doesn't support systemd services

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#18201]
(at least as far as I can tell)

We rely on systemd on ubuntu on AWS (and possibly elsewhere) which means that these installs don't work properly (e.g. #18037)

We can either upgrade Salt on AWS, or switch back to sysv init for Ubuntu on AWS (which does appear to work)

I lean towards the second option.

@mikedanese @zmerlynn @justinsb

**Comment by mikedanese** [comment]
It seems like vagrant salt and kube-up is using systemd successfully. What leads you to believe this?

**Comment by justinsb** [comment]
Indeed ... I'm a little confused here.  Salt's support for systemd is indeed mostly broken, but we work around it by using our own script to manage systemd services...

**Comment by justinsb** [comment]
OK to close @brendandburns ?  We've worked around the problems in salt, kube-up is in maintenance mode, nobody in their right mind would choose salt again :-)
