### ISSUE TITLE
Document container states

### ISSUE THREAD

**Issue by sils** [kubernetes/kubernetes#18206]
I was not able to find any official documentation for the container states and troubleshooting information about them. I'd imagine this to be quite useful for people just getting started, just being able to e.g. look up `CrashLoopBackOff`, get a description, some common causes and debugging tips for related issues.

**Comment by bgrant0607** [comment]
Ref #15244

**Comment by bgrant0607** [comment]
We should document the maximum backoff interval, how long the container needs to run successfully before the crashloop state is reset, and other things, like changing the image, that could reset the crashloop state.

cc @dchen1107

**Comment by bgrant0607** [comment]
See also #17460

**Comment by bgrant0607** [comment]
ImagePullBackOff is another one we need to document.

**Comment by bgrant0607** [comment]
Some errors are listed here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/sync_result.go#L29
