### ISSUE TITLE
Proxy metrics exposed by scheduler and controller-manager through API server

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18212]
Currently there's no easy way to get there - only obvious solution is to ssh to the master machine and curl/wget them. I propose adding two endpoints `/metrics/scheduler` and `/metrics/controller-manager` that will proxy requests to appropriate components. For consistency we might want to move API server metrics to `metrics/apiserver`.

Another option would be to create `proxy/scheduler` and `proxy/controller-manager` endpoints which would only allow connections to `/metrics/ `, but I prefer first option.

cc @wojtek-t @fgrzadkowski @lavalamp @davidopp @bgrant0607

**Comment by lavalamp** [comment]
No, the easy (and correct) way to do this is to make a service object for the scheduler. Please don't write any special apiserver code for this.

**Comment by gmarek** [comment]
@lavalamp are you sure we want to create a "full" proxy for scheduler/controller manager, i.e. open them to the world?

**Comment by bgrant0607** [comment]
What exactly are you trying to do?

One possibility is to use the existing apiserver proxy.

Another would be to create another accessible authenticated endpoint.

**Comment by gmarek** [comment]
I want to be able to read `/metrics` and `/debug/pprof` scheduler/controller-manager endpoints without a need to SSH to the master machine.

**Comment by lavalamp** [comment]
We'll eventually want a status page for these components, anyway.

Note you'd still have to have credentials to get into the cluster, so this isn't "opening them to the world".

But yes, I was thinking you'd create a service, and then use the apiserver's service proxy to actually view the component. I'm not sure what the natural way of doing this is in GKE (@roberthbailey ?) -- we may have to populate the endpoints manually, which is unfortunate. Still better than adding custom API resources to apiserver, though.

This is how we view the logging dashboard, heapster, etc.

**Comment by roberthbailey** [comment]
On GKE, where the master is on a separate network, what would a service for the scheduler or controller manager look like? It would be reachable from the apiserver (since it runs in the same network as the other master components) so proxying should work. But the service wouldn't be reachable from any of the nodes (or any containers running on the nodes). This is unlike the kubernetes service, which is accessible from the nodes because the apiserver is accessible over a public address.

**Comment by gmarek** [comment]
To tell the truth I wasn't worrying about GKE too much. The whole reason before this effort is to be able to catch performance regressions automatically and make locating the reason faster. For this reason I think that as long as it'll work on any provider (read: GCE:), we're good. cc @fgrzadkowski 

If you think that exposing those metrics would be useful for other reasons, we can work on exposing them on GKE as well. For now we actually dropped the 'service' idea and proxy through the API server to Scheduler/ControllerManager pods.

**Comment by yuvipanda** [comment]
@roberthbailey did you ever figure out a way to get these metrics on GKE?

**Comment by roberthbailey** [comment]
I don't think anyone has looked into it after @gmarek's last update.
