### ISSUE TITLE
e2e flake: SchedulerPredicates validates resource limits of pods that are allowed to run [Conformance]

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18211]
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:352 Expected : 21 to equal : 22
```

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9736/

I'll look into it.

cc @sttts @wojtek-t @lavalamp @davidopp

**Comment by gmarek** [comment]
I looked a bit closer to this failure, and I think it's actually a small bug in the scheduler. This is the only run I was able to find with the 'edge' case scheduling. Namely this test schedules 500 millicore pods to saturate the cluster and on one of the Nodes (54c2 one) we have exactly 1500 millicores left after all system pods are scheduled:

```
fluentd-elasticsearch-e2e-gce-minion-54c2 100
elasticsearch-logging-v1-zt7hz 100
kube-ui-v3-f7bkt 100
monitoring-influxdb-grafana-v2-475z6 200
```

I think that it might be the problem is with resource quantity representation as we actually have a unit test for edge scheduling: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go#L117

cc @bgrant0607 @davidopp @derekwaynecarr

**Comment by sttts** [comment]
I still have a problem with the logic of this test in general. It makes pretty strong assumptions about a cluster, namely:
- the available resources are constant on each node over the runtime of the test
- the capacity arithmetically corresponds to the resource sum of pods
- the number of nodes is constant over the runtime of the test.

**Comment by gmarek** [comment]
> the available resources are constant on each node over the runtime of the test
> the capacity arithmetically corresponds to the resource sum of pods
> the number of nodes is constant over the runtime of the test.

Currently we only account resources explicitly claimed by some pods, and we require this test to be only one running in the cluster. Yes, we do assume that nothing goes very wrong (e.g. no Node dies) during the test, but we have the same assumption in quite a few other ones.

**Comment by sttts** [comment]
I guess I am a bit prejudiced because we have to take special care to keep a dev Mesos cluster quiet and static enough for this test to pass. It will be a matter of luck (or impossible in a reliable way) to calm down a production quality DCOS cluster enough with a number of pre-installed services and possibly node auto scaling.

I wonder whether those assumptions are really part of what the Kubernetes experience should be ("conformance") or just given by the implementation of some tests. To be honest I have no good idea either how to test `validates resource limits of pods that are allowed to run` in a more dynamic environment.

**Comment by gmarek** [comment]
I must admit I always forget how very different is Mesos environment. Somehow I always assume that K8s is the thing at the bottom, which is clearly not the case for Mesos. We probably can/should remove tests which has this assumption from Confromance suite... @brendandburns @thockin @bgrant0607

**Comment by sttts** [comment]
@gmarek that's a good summary of the situation. In my words: we have (a) the Kubernetes API with a certain behavior and (b) the concrete implementation (e.g. the scheduler and the kubelet binary). E2e tests sometimes have to do white box testing (b), but conformance tests should only black box test (a).

**Comment by bgrant0607** [comment]
Exporting allocatable resources should address this. #17201 cc @dchen1107 

If the test is fragile in other ways, those problems should be fixed.

**Comment by gmarek** [comment]
@bgrant0607 - this one failed only once to my knowledge.

**Comment by gmarek** [comment]
I'm unable to reproduce this problem. Let's wait for #18218 to be merged and monitor this test for some time.

**Comment by gmarek** [comment]
#18218 is merged. Let's wait a couple of days to see if it's stable.

**Comment by gmarek** [comment]
It's not failing anymore.
