### ISSUE TITLE
Environmental Variables for services causing conflict with external naming convention

### ISSUE THREAD

**Issue by ttomsu** [kubernetes/kubernetes#18219]
Hi K8S gurus - I'm having an issue with Spring + Services. Specifically, any Service I have injects an environmental variable like `MYSERVICE_PORT=tcp://1.2.3.4:5`. 

However, my application uses Spring-Boot to resolve configuration, and my app expect `MYSERVICE_PORT` to be just an integer. I need a way to turn off environment variable injection.

(Aside: I'm using the DNS way to resolve service endpoints, specifically the Google Container Engine's prepacked one)

**Comment by erictune** [comment]
If you explicitly define this variable as you like in your pod's `.spec.containers[].envvars` section, does it get set to your value or the kubernetes style value?

**Comment by ttomsu** [comment]
It does. 

```
spec:
  containers:
    - env:
    - name: REDIS_PORT
      value: 6379
```

However, since it is an int I'm trying to set it to. I get a 

"unable to load "1-spinnaker.yaml": json: cannot unmarshal number into Go value of type string" 

So I have to do: `value: "6379"`, which is strange

**Comment by zmerlynn** [comment]
I'd argue that this isn't that strange at all - environment variables are strings, at the end of the day. The schema makes that very explicit.

Thanks for using Kubernetes. Please reopen or consider posting your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes) if you have any further questions.

**Comment by ttomsu** [comment]
OK, yes, they're strings, but that was a side note and not my point about needing to disable the injection of these env vars in the first place. Could you please reopen?

**Comment by thockin** [comment]
Disabling injection is a pretty big change, due to the in-built assumptions
of docker compat.  This is the docker syntax, for better or worse.

You should be able to do something like assign it yourself, but assign it
to a string - `"6379" ` or even better `$(MYSVC_SERVICE_PORT)` which will
be expanded.  See, the non-docker form of these variables are simpler and
more useful :)

**Comment by huggsboson** [comment]
@ttomsu this just bit me today.  I find these env vars are generally fairly useless as we use a namespace per app, so I only see my own services anyway.  I'm wondering if you found a way to disable them.

**Comment by thockin** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/60099#issuecomment-367820278

Related: https://github.com/kubernetes/kubernetes/issues/1768#issuecomment-152665210

I don't think we ever added a way to disable this.  I think we'd be open to a patch.  ISTR someone started a patch - maybe there's a stagnant PR you can take over?  Here: https://github.com/kubernetes/community/pull/1249#discussion_r155979671

In fact:  https://github.com/kubernetes/kubernetes/pull/60206

**Comment by huggsboson** [comment]
thanks for diving in <3!
