### ISSUE TITLE
Containerized hyperkube fails to create certificates

### ISSUE THREAD

**Issue by 2opremio** [kubernetes/kubernetes#18227]
The [`setup`] (https://github.com/kubernetes/kubernetes/blob/d2dbe568205895817b52a71fbef8614f4d9931eb/cluster/images/hyperkube/master.json#L65) container was [recently added](https://github.com/kubernetes/kubernetes/pull/17262) by @brendandburns to automatically generate certificates.

However, [setup-files.sh](https://github.com/kubernetes/kubernetes/blob/ce90b83689f08cb5ebb6b632dab7f95a48060425/cluster/images/hyperkube/setup-files.sh) fails with `chgrp: invalid group: 'kube-cert'`. 

Setting ```CERT_GROUP=`id -g` ``` [when invoking `make-ca-cert.sh`](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/setup-files.sh#L34) fixes it  but after that I get 

```
hostname: Name or service not known
/make-ca-cert.sh: line 21: $1: unbound variable
``` 

Which I have narrowed down to the combination of `hostname -i` with host networking:

```
$ docker run --net=host --rm debian:jessie hostname -i
hostname: Name or service not known
```

```
docker run --rm debian:jessie hostname -i
172.17.0.57
```

`strace` reveals that `hostname -i` in the container simply does a DNS query of the hostname, which won't work in many cases like mine.

```
$ docker run --net=host -ti --rm debian:jessie bash 
root@vagrant-ubuntu-vivid-64:/# hostname
vagrant-ubuntu-vivid-64
root@vagrant-ubuntu-vivid-64:/# apt-get update
[...]
root@vagrant-ubuntu-vivid-64:/# apt-get install strace
[...]
root@vagrant-ubuntu-vivid-64:/# strace hostname -i
[...]
socket(PF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, 16) = 0
poll([{fd=3, events=POLLOUT}], 1, 0)    = 1 ([{fd=3, revents=POLLOUT}])
sendmmsg(3, {{{msg_name(0)=NULL, msg_iov(1)=[{"\337A\1\0\0\1\0\0\0\0\0\0\27vagrant-ubuntu-vivi"..., 41}], msg_controllen=0, msg_flags=0}, 41}, {{msg_name(0)=NULL, msg_iov(1)=[{"\335\254\1\0\0\1\0\0\0\0\0\0\27vagrant-ubuntu-vivi"..., 41}], msg_controllen=0, msg_flags=0}, 41}}, 2, MSG_NOSIGNAL) = 2
poll([{fd=3, events=POLLIN}], 1, 5000)  = 1 ([{fd=3, revents=POLLIN}])
ioctl(3, FIONREAD, [116])               = 0
recvfrom(3, "\335\254\201\203\0\1\0\0\0\1\0\0\27vagrant-ubuntu-vivi"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, [16]) = 116
poll([{fd=3, events=POLLIN}], 1, 4973)  = 1 ([{fd=3, revents=POLLIN}])
ioctl(3, FIONREAD, [116])               = 0
recvfrom(3, "\337A\201\203\0\1\0\0\0\1\0\0\27vagrant-ubuntu-vivi"..., 1932, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, [16]) = 116
close(3)                                = 0
write(2, "hostname: ", 10hostname: )              = 10
write(2, "Name or service not known", 25Name or service not known) = 25
write(2, "\n", 1
)                       = 1
exit_group(1)                           = ?
+++ exited with 1 +++
```

I would propose:

* Use `hostname -I` (note the capital `I`) and provide a SANs for all the interface IPs.
* Add SANs for the kubernetes service IP and all the full or partial domain names accesible when using the DNS add-on, so that pods can connect to the API server with service accounts. That is `IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local`

I am aware that the `.cluster.local` domain is configurable but it's a reasonable default.

**Comment by mikedanese** [comment]
@fgrzadkowski

**Comment by dalanlan** [comment]
I guess service ip is required to enable dns add on to my best knowledge. Ref [#17213(comment)](https://github.com/kubernetes/kubernetes/pull/17213#issuecomment-159777349).

**Comment by luxas** [comment]
I also got these errors and came to these conclusions.
In #17213, I added the line `addgroup kube-cert` to fix the issue with the non-existent group.
I also want to use `hostname -I`, but are there some disadvantages?
I think that we could hard-code `cluster.local` as a default for now...

**Comment by 2opremio** [comment]
> I guess service ip is required to enable dns add on to my best knowledge. Ref #17213(comment).

@dalanlan The service IP is in my proposal: `IP:10.0.0.1`

**Comment by dalanlan** [comment]
I don't believe this issue has been solved. Could anyone please kindly reopen it?

**Comment by fgrzadkowski** [comment]
@dalanlan You're right. I used wrong issue numbers in PR description. Sorry about that.

**Comment by gopinatht** [comment]
+1 for a quick resolution on this issue. We really cannot use containerized kubernetes without the certificates generated for the Master.

**Comment by luxas** [comment]
@fgrzadkowski Could this be fixed before `v1.2`? 
I think it should and I may look into it and see if there's something I may do

**Comment by gopinatht** [comment]
@luxas @fgrzadkowski I am also willing to help with this as well to get it into 1.2. I can test or make changes and submit a PR. I might need some hand holding though for changes and PR as I have never done it before for Kubernetes.

**Comment by luxas** [comment]
This is working in the latest `v1.2` release with #17213, #21504 and #23550

**Comment by cleverlzc** [comment]
Hi，@2opremio    I also got these errors  ＂ chgrp: invalid group: 'kube-cert'.＂Why are you "Setting CERT_GROUP=id -g"?

**Comment by luxas** [comment]
@cleverlzc Please don't use this method anymore, it has been deprecated for a long time and is now removed officially. I'd suggest you use kubeadm instead.

**Comment by cleverlzc** [comment]
Well，thanks for your suggestion！ @luxas
