### ISSUE TITLE
Upgrade tests can't find cluster, report SUCCESS anyway

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18225]
```
10:34:50 2015/12/04 10:34:50 e2e.go:309: Error running get status: exit status 1
10:34:50 2015/12/04 10:34:50 e2e.go:305: Step 'get status' finished in 287.79716ms
10:34:50 2015/12/04 10:34:50 e2e.go:271: Testing requested, but e2e cluster not up!
...
10:35:08 Finished: SUCCESS
```

If we are uploading JUnit results, this situation will fail because it can't find test results.  It should fail regardless of whether JUnit results are being uploaded, though.

**Comment by ihmccreery** [comment]
cc @kubernetes/goog-testing

**Comment by ixdy** [comment]
This happens because we swallow the exit code from running tests. (Otherwise, test failures would always appear as red on Jenkins, rather than yellow.)

To fix this, we should just need to call `go run hack/e2e.go -v --isup` in hack/jenkins/e2e.sh, probably only when `E2E_UP` is false.

**Comment by ihmccreery** [comment]
Ah, good, so this is intentional.  Will send a PR shortly.
