### ISSUE TITLE
Tolerance: not enough validation in HPA tests.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#18221]
After modified the tolerance levels in the HPA tests, and found that the tests themselves don't actually quantify expectations based on tolerance.
- It seems that unit tests expectations should be multiplied by the tolerance calibration, rather than assuming it is .1.
- Related, Right now, in the UTs... I think the bounds might be tightened up (possibly by increasing total pod # in mocks, the precision will be higher) i.e.  if you modify tolerance from .1->.4, the tests still pass.

In order to implement #18155 , we need to make sure that unit tests are actually aware of tolerance, otherwise it the behaviour of the tolerance feature may silently drift on accident.

**Comment by jayunit100** [comment]
in code, im talking about ... 

```
	hpaController := NewHorizontalController(testClient, metricsClient,.1)
```
which needs to be updated.  I'll bundle this into the issue above, since its required for unit testing tolerance parameterization.

**Comment by jayunit100** [comment]
cc @timothysc @piosz @jszczepkowski

**Comment by jayunit100** [comment]
cc @kubernetes/rh-cluster-infra @ncdc @DirectXMan12

**Comment by ncdc** [comment]
cc @mwielgus @fgrzadkowski

**Comment by jayunit100** [comment]
Closing, pr for this is here #18315

**Comment by jszczepkowski** [comment]
@jayunit100 
> Closing, pr for this is here #18315

As a rule, an issue should be closed after the corresponding PR is merged.

**Comment by mwielgus** [comment]
All required validation is there.
