### ISSUE TITLE
http liveness probe doesn't follow redirects

### ISSUE THREAD

**Issue by emaildanwilson** [kubernetes/kubernetes#18233]
It seems the http liveness probe will not follow a 302 redirect and instead reports a failure. I found this in some testing on 1.0.6 and have not yet verified the same behavior on latest. Do you agree that it should check the redirected path on a 302? If so, where would be the best place to check the response code and handle this?

**Comment by thockin** [comment]
Why would you set your health-check URL to a redirect?

**Comment by emaildanwilson** [comment]
In this case it was a versioned health check where /v1/health or /v2/health is the correct check and /health directs to the correct one.

**Comment by thockin** [comment]
hmm, I could buy following redirects, I guess.  It's a little weird if it
redirects off-host, but who am I to say it is wrong?

**Comment by liggitt** [comment]
following redirects for a health check seems weird to me as well...

**Comment by liggitt** [comment]
> In this case it was a versioned health check where /v1/health or /v2/health is the correct check and /health directs to the correct one.

Seems like it would be cleaner to make `/health` respond the same as `/<latest>/health` instead of making all health consumers follow redirects.

**Comment by emaildanwilson** [comment]
I agree that it's cleaner to call /health and make that route the same as /<latest>/health but due to the framework used for this project it's not handled that way. Following the HTTP standards is important as well, right? curl handles this with an additional option (-L), could we do the same by adding a parameter?

**Comment by thockin** [comment]
I think it should follow local redirects without complaining (can well
differentiate local vs non?).  The real question is non-local redirects -
should it a) work, b) not work, c) work iff a flag-field in the probe

**Comment by emaildanwilson** [comment]
old thread here... I agree with non-local redirects not being allowed, just doesn't seem to make sense. If we get a 301 perhaps we could get the value of the redirect ( it looks like there is a Location header with the new full path ) and then do something like the following:

1. Get the root URL of the redirect location.
2. If it's a DNS name attempt to resolve it to an IP. If that fails, just bail.
3. Check the IP to make sure it's in the cluster. If it's not in our CIDR block bail.
4. follow the redirect.

thoughts?

**Comment by cmluciano** [comment]
Adding to 1.8 milestone

**Comment by neverfox** [comment]
Is it not possible and easier to simply empower the user by adding an option for "unexceptional" status codes? They could declare 200-only or all-but-errors.

**Comment by redbaron** [comment]
This contradicts docs , opened https://github.com/kubernetes/kubernetes/issues/73172
