### ISSUE TITLE
Pod keep Terminating status and cannot be deleted

### ISSUE THREAD

**Issue by zhengguoyong** [kubernetes/kubernetes#18245]
When i kill pod, it cannot be deleted and the status keep Terminating always.  The reason is that my networkPlugin has some problem, so when TearDownPod(https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1318), it return fail.  Then killPod fail, and it will try next SyncPod. Unfortunately the err my networkPlugin cannot recover again,  So next SyncPod, it will fail again. 
The result is: A Terminating pod cannot be deleted.   Should we care about the err when TearDownPod? Or is there other ways to avoid this appearance?
@bgrant0607  @dchen1107 @yujuhong , please help have a look, Thanks!
cc @judytong @linzichang

**Comment by AdoHe** [comment]
@zhengguoyong I also experienced this in my test environment. I have no way but to restart everything. I think err get when TearDownPod should be treated as permanent error, the sync loop should not try it.

**Comment by wulonghui** [comment]
Is this issue fixed?

**Comment by spzala** [comment]
@zhengguoyong hi, it's over a year since this issue was reported. Can we please close it if it's not an issue any more? /cc @thockin  Thanks!

**Comment by spzala** [comment]
This is a two years old issue and inactive since long time with lack of latest information. The provided code link in issue description is outdated. Closing it per issue triage guidelines. Please reopen if needed. Thanks!
/close
