### ISSUE TITLE
Stop using/vendoring LGPLv3 dependencies

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#18241]
AFAIK, LGPLv3 code can vendor Apache2.0 code, but not the other way around. (I am not a lawyer.)

So we need to remove or replace our LGPLv3 dependencies in Godeps:

- gopkg.in/yaml.v2 (https://github.com/go-yaml/yaml)
- github.com/juju/ratelimit

Thankfully, [candiedyaml](https://github.com/cloudfoundry-incubator/candiedyaml) was written by Pivotal & IBM to replace go-yaml when they did their License clean up of CloudFoundry a while back.

Unfortunately candiedyaml has a "bug" that makes it slightly different then go-yaml: https://github.com/cloudfoundry-incubator/candiedyaml/issues/14 

We will either need to fix that issue or fix our tests that depend on sorted yaml map key ordering.

ratelimit needs investigation.

**Comment by xiang90** [comment]
@karlkfi juju/ratelimiter has a special license I think: see https://github.com/juju/ratelimit/blob/master/LICENSE#L8-L16

**Comment by mikedanese** [comment]
@brendandburns @thockin @eparis

**Comment by thockin** [comment]
We had this firedrill before.  Both libs have the "links statically or dynamically to this Library" exception.

If you think candiedyaml is better, I'm happy to consider it, but it's not a license thing/

**Comment by karlkfi** [comment]
Thanks for clarifying. 

On a related note: 
Does anyone know of a tool that can find licenses from Godep vendored dependencies? I've tried various things, but not of them catch all the cases.

**Comment by xiang90** [comment]
@karlkfi 

You can check Godep's code and get the part of code that actually copies in the Licenses.

**Comment by karlkfi** [comment]
Finding all the license files isn't all that hard. The hard part is identifying all the repos without license files, some of which have licenses specified in their readme.

**Comment by karlkfi** [comment]
For reference: #18322 uses license sentence matching to create a list of Godep project licenses.
