### ISSUE TITLE
scheduler: inefficient cache operation slows down scheduler

### ISSUE THREAD

**Issue by xiang90** [kubernetes/kubernetes#18255]
After https://github.com/kubernetes/kubernetes/issues/18126 fixed by https://github.com/kubernetes/kubernetes/pull/18170, I run density test again.

Now the hot spot on the critical path is an inefficient cache access(https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/store.go#L75) when listing nodes that uses reflection. Reflection causes a lot of allocations.

A simple fix would be

```go
func NodeKeyFunc(obj interface{}) (string, error) {
	key, ok := obj.(*api.Node)
	if !ok {
		return "", fmt.Errorf("not *api.Node type")
	}
	meta := key.ObjectMeta
	if len(meta.Namespace) > 0 {
		return meta.Namespace + "/" + meta.Name, nil
	}
	return meta.Name, nil
}
```

The simple fix improves the throughput of scheduler by 15%-20% on 1000 nodes case.

@lavalamp What do you think about this issue?

/cc @hongchaodeng @wojtek-t @gmarek @davidopp

**Comment by wojtek-t** [comment]
The MetaKeyFunc is a generic method - what you're suggesting is obviously not.
However, I think that it definitely makes sense to use what you're suggesting, if we already now that we are tranforming a node.

**Comment by xiang90** [comment]
@wojtek-t 

Yes. I suggest pass in a special keyfunc to nodeLister since you already know you are transforming a node struct.

**Comment by wojtek-t** [comment]
SGTM - since this is NodeLister, I agree it makes sense to use a dedicated type-specific functions there.

**Comment by lavalamp** [comment]
So a more general fix would be to add a type switch in the existing key function, or write one in scheduler that uses a type switch. e.g.,

```go
func KeyFunc(obj interface{}) (string, error) {
  switch t := obj.(type) {
  case *api.Node: return ObjectMetaToKey(&t.ObjectMeta)
  case *api.Pod: return ObjectMetaToKey(&t.ObjectMeta)
  case *api.Service: return ObjectMetaToKey(&t.ObjectMeta)
  ...
  }
  // fall through to reflection based method
}
```

**Comment by xiang90** [comment]
@lavalamp A cleaner way is probably to let all relevant types to satisfy a Key interface?

**Comment by lavalamp** [comment]
Yes-- actually @smarterclayton just proposed such a change in a large refactoring PR he's working on.

**Comment by xiang90** [comment]
@smarterclayton Can you please point me to the pr? So I can avoid duplicate work. Thanks!

**Comment by lavalamp** [comment]
It's #17922

**Comment by smarterclayton** [comment]
I plan on making a separate PR for that shortly - we see this check show up in lots of large profiles so I want to make sure it goes away.  Will update both issues once I do that.

**Comment by xiang90** [comment]
@smarterclayton Great. So I will wait for your update. Thanks!

**Comment by smarterclayton** [comment]
As a side node, making this change has dramatically reduced the ugliness and incomprehensibility of a bunch of nasty code paths.

**Comment by davidopp** [comment]
ref/ #18418

**Comment by smarterclayton** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/18473

**Comment by smarterclayton** [comment]
Actual fix will be in https://github.com/kubernetes/kubernetes/pull/18534

**Comment by smarterclayton** [comment]
Issue was merged

**Comment by hongchaodeng** [comment]
@smarterclayton 
#18534 was way too huge. Can you help explain how it avoids expensive reflect operations in `MetaNamespaceKeyFunc`.

**Comment by smarterclayton** [comment]
Instead of reflection to look up name and namespace, we use an
interface (a fast path) that allows direct field access.  That makes
cache key construction require no reflection.
