### ISSUE TITLE
Kubernetes examples probably should not rely on containers owned by other people

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#1827]
No offense to the other people, but if we can't rebuild a container, we get stuck sometimes. :)

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by chrislovecnm** [comment]
Are we talking about 

```docker
FROM google/debian:jessie
```

Or are we talking about where the built docker is hosted?  It would be nice to for instance have a stock debian instance hosted on  google's docker repo.

**Comment by kargakis** [comment]
There is another issue that advocates moving the examples to a separate repo (kubernetes/examples?). If that is ever done (I am +1 for it), we could think about requiring people to check-in tests for their examples and setup CI in a way that would run all of the tests every time a new Kubernetes release is out.

**Comment by pires** [comment]
Moving examples to a separate repo: +1.

**Comment by ahmetb** [comment]
/asign 

We moved the examples to their own repo (https://github.com/kubernetes/examples) for further maintenance.  All maintained examples (guestbook, mysql-wordpress-pd and cassandra) use either Docker Hub images, or gcr.io/google-samples. 

I've a longer term plan to make `gcr.io/google-samples` process more transparent and accessible to wider community: https://github.com/kubernetes/examples/issues/11#issuecomment-307921652

However it looks like this is not applying to maintained examples anymore, so I will go ahead and close.
