### ISSUE TITLE
kube2sky does not delete service entries when service is deleted

### ISSUE THREAD

**Issue by djablonski** [kubernetes/kubernetes#18289]
When deleting a service in Kubernetes, the corresponding DNS record is not deleted in SkyDNS.
The log output from ```kube2sky``` shows that no deletion and recreation of the entry is happening anymore, but the existing record is also not deleted.
Affected version is 1.11

**Comment by thockin** [comment]
What version of kube2sky is running?  I can't reproduce this...

```
$ kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o
go-template='{{range .items}}{{range
.spec.containers}}{{.image}}{{"\n"}}{{end}}{{end}}'
gcr.io/google_containers/etcd:2.0.9
gcr.io/google_containers/kube2sky:1.11
gcr.io/google_containers/skydns:2015-10-13-8c72f8c
gcr.io/google_containers/exechealthz:1.0
```

**Comment by djablonski** [comment]
@thockin:

```
gcr.io/google_containers/etcd:2.0.9
gcr.io/google_containers/kube2sky:1.11
gcr.io/google_containers/skydns:2015-03-11-001
gcr.io/google_containers/exechealthz:1.0
```

**Comment by thockin** [comment]
Try this:


```
$ kubectl run test-dns-svc-delete --image=
gcr.io/google_containers/serve_hostname:1.2 --replicas=1
replicationcontroller "test-dns-svc-delete" created

$ kubectl exec --tty -i $(kubectl get pods -l run=test-dns-svc-delete -o
name | cut -f2 -d/) nslookup test-dns-svc-delete
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'test-dns-svc-delete'
error: error executing remote command: Error executing command in
container: Error executing in Docker Container: 1

$ kubectl expose rc test-dns-svc-delete --port=80 --target-port=9376
service "test-dns-svc-delete" exposed

$ kubectl exec --tty -i $(kubectl get pods -l run=test-dns-svc-delete -o
name | cut -f2 -d/) nslookup test-dns-svc-delete
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      test-dns-svc-delete
Address 1: 10.0.119.62

$ kubectl delete svc test-dns-svc-delete
service "test-dns-svc-delete" deleted

$ kubectl exec --tty -i $(kubectl get pods -l run=test-dns-svc-delete -o
name | cut -f2 -d/) nslookup test-dns-svc-delete
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'test-dns-svc-delete'
error: error executing remote command: Error executing command in
container: Error executing in Docker Container: 1
```

**Comment by djablonski** [comment]
Environment: 
CoreOS: 884.0.0 (on Vagrant/VirtulBox using box image)
Kubernetes: v1.1.2

```
$ kubectl get svc
NAME         CLUSTER_IP   EXTERNAL_IP   PORT(S)   SELECTOR   AGE
kubernetes   10.3.0.1     <none>        443/TCP   <none>     17m
```

```
$ kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
```

```
$ kubectl run test-dns-svc-delete --image=gcr.io/google_containers/serve_hostname:1.2 --replicas=1
replicationcontroller "test-dns-svc-delete" created
```

```
$ kubectl get pods
NAME                        READY     STATUS    RESTARTS   AGE
test-dns-svc-delete-88muu   1/1       Running   0          1m
```

```
$ kubectl exec --tty -i $(kubectl get pods -l run=test-dns-svc-delete -o name | cut -f2 -d/) nslookup test-dns-svc-delete
Server:    10.3.0.10
Address 1: 10.3.0.10
```

```
nslookup: can't resolve 'test-dns-svc-delete'
error: error executing remote command: Error executing command in container: Error executing in Docker Container: 1
```

```
$ kubectl expose rc test-dns-svc-delete --port=80 --target-port=9376
service "test-dns-svc-delete" exposed
```

```
$ kubectl exec --tty -i $(kubectl get pods -l run=test-dns-svc-delete -o name | cut -f2 -d/) nslookup test-dns-svc-delete
Server:    10.3.0.10
Address 1: 10.3.0.10
```

```
Name:      test-dns-svc-delete
Address 1: 10.3.0.200
```

```
$ kubectl delete svc test-dns-svc-delete
service "test-dns-svc-delete" deleted
```

A few minutes later, the result is still

```
$ kubectl get svc
NAME         CLUSTER_IP   EXTERNAL_IP   PORT(S)   SELECTOR   AGE
kubernetes   10.3.0.1     <none>        443/TCP   <none>     30m
```

```
$ kubectl exec --tty -i $(kubectl get pods -l run=test-dns-svc-delete -o name | cut -f2 -d/) nslookup test-dns-svc-delete
Server:    10.3.0.10
Address 1: 10.3.0.10

Name:      test-dns-svc-delete
Address 1: 10.3.0.200
```

**Comment by thockin** [comment]
Can you look at logs for the kube-dns pod's kube2sky container?

**Comment by djablonski** [comment]
@thockin: Here is the log you asked for (I replayed the above scenario)

[kube2sky.log.txt](https://github.com/kubernetes/kubernetes/files/56061/kube2sky.log.txt)

**Comment by thockin** [comment]
Well, the logs shows it being created and never being removed.  It also
shows the DNS and master services being removed and recreated every couple
minutes with a watch EOF.  @lavalamp to maybe delegate to one of his team
for a clue?  I see none of those logs on my own install.

```
I1208 21:09:44.645972       1 iowatcher.go:102] Unexpected EOF during watch
stream event decoding: unexpected EOF
E1208 21:09:44.646346       1 reflector.go:183] watch of *api.Service ended
with: very short watch
I1208 21:09:44.646593       1 iowatcher.go:102] Unexpected EOF during watch
stream event decoding: unexpected EOF
E1208 21:09:44.646844       1 reflector.go:183] watch of *api.Endpoints
ended with: very short watch
I1208 21:09:45.686866       1 kube2sky.go:94] Removing
kubernetes.default.cluster.local. from DNS
I1208 21:09:45.697898       1 kube2sky.go:94] Removing
kubernetes.default.svc.cluster.local. from DNS
I1208 21:09:45.720067       1 kube2sky.go:246] Setting DNS record:
kubernetes.default.cluster.local. ->
"{\"host\":\"10.3.0.1\",\"priority\":10,\"weight\":10,\"ttl\":30,\"targetstrip\":0}",
with recordKey: kubernetes.default.cluster.local.
I1208 21:09:45.737114       1 kube2sky.go:246] Setting DNS record:
kubernetes.default.svc.cluster.local. ->
"{\"host\":\"10.3.0.1\",\"priority\":10,\"weight\":10,\"ttl\":30,\"targetstrip\":0}",
with recordKey: 6d73bb5e.kubernetes.default.svc.cluster.local.
I1208 21:09:45.753175       1 kube2sky.go:94] Removing
kube-dns.kube-system.cluster.local. from DNS
I1208 21:09:45.768996       1 kube2sky.go:94] Removing
kube-dns.kube-system.svc.cluster.local. from DNS
I1208 21:09:45.785170       1 kube2sky.go:246] Setting DNS record:
kube-dns.kube-system.cluster.local. ->
"{\"host\":\"10.3.0.10\",\"priority\":10,\"weight\":10,\"ttl\":30,\"targetstrip\":0}",
with recordKey: kube-dns.kube-system.cluster.local.
I1208 21:09:45.802001       1 kube2sky.go:246] Setting DNS record:
kube-dns.kube-system.svc.cluster.local. ->
"{\"host\":\"10.3.0.10\",\"priority\":10,\"weight\":10,\"ttl\":30,\"targetstrip\":0}",
with recordKey: 7c38c4e8.kube-dns.kube-system.svc.cluster.local.
```

Also worth noting - we have not cut a new kube2sky since July - a few
noteworthy changes have gone in.  We should rebuild and republish ASAP.

@artfulcoder

**Comment by lavalamp** [comment]
@djablonski What kind of setup are you running? It looks like you have two apiservers fighting over the kubernetes service address. If you're actually running two, you need to set the flag to tell them both there should be two. If you're not running two, then is it continuously shutting down and restarting, switching IP addresses each time? (from 10.3.0.10 to 10.3.0.1 and back)

**Comment by thockin** [comment]
10.3.0.10 is the DNS server, 10.3.0.1 is the master

**Comment by lavalamp** [comment]
Sorry, I can't read. Let me look again.

**Comment by lavalamp** [comment]
The "watch of *api.Service ended with: very short watch" bit is concerning, that really shouldn't happen. On the other hand, if kube2sky hasn't been built for 6 months, maybe it's not surprising.

But really it's pretty hard to tell anything from the kube2sky logs. It's unclear how much from apiserver is making it through the watch before it closes.

Logs from apiserver might help a little bit?

**Comment by djablonski** [comment]
@thockin: The reason you might not see some of these messages might be that I forgot to mention that I added a ```-v=2``` param to the ```kube2sky``` container.

**Comment by djablonski** [comment]
@lavalamp: Hmm... No relevant info from apiserver log. What log level should I use?

**Comment by thockin** [comment]
--v=2 is the default "not too chatty".  --v=4 is where it gets interesting.

**Comment by djablonski** [comment]
Sorry for all the inconvinience! I'm closing this issue, because I found out that there is something wrong with my local setup. When trying to create a completely stripped down sample repo, the issue disappeared. I still need to find out where exactly the root of the problem is, but is obviously not in kube2sky.
I will add details whenever I found the root cause. Thanks for the support!

**Comment by djablonski** [comment]
Finally, I figured out what was the reason for this issue. As @lavalamp hinted, the `watch of *api.Service ended with: very short watch` was the reason. In the original setup, there was a nginx based load balancer in front of the apiservers, which was misconfigured and therefore closed the connection after 60s, which caused the accoring events to get lost.
I switched to using the service IP of the `kubernetes` service, and now everything works fine. Sitll there is the question on how to configure the kube-proxy (see [here](https://stackoverflow.com/questions/34222193/how-to-configure-kube-proxy-master-url-with-multiple-apiservers) for details)...

**Comment by lavalamp** [comment]
Glad you figured it out. You are right that kube-proxy needs a fix, but if you make sure you've got the flag from #18628, and you tell all in-cluster clients the master service IP (or its DNS name), then all clients will correctly be loadbalanced by kube-proxy, as it reads the endpoints. kube-proxy itself won't be load balanced, but that's a separate issue.
