### ISSUE TITLE
add test-cmd test for output options "custom-columns=" and "custom-columns-file="

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#18288]
Add a test for the new output options that are enabled.  

@brendandburns promised :) https://github.com/kubernetes/kubernetes/pull/15210#issuecomment-162140086

**Comment by brendandburns** [comment]
@deads2k ack, will do soon.

**Comment by deads2k** [comment]
Looks like it was broken: https://github.com/kubernetes/kubernetes/pull/20226
