### ISSUE TITLE
Check that hpa.Spec.CPUUtilization is bound to 100%

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#18291]
I'm pretty sure we should we be doing
```
if hpa.Spec.CPUUtilization > 100 { 		glog.Errorf("CPUUtilization is too high ! %v .  Scale up starvation scenario can happen if pods reach maximum capacity.",  hpa.Spec.CPUUtilization) 	}
```
checks in horizontal.go ...  let me know your thoughts.  IF not, my understanding is that the following disaster might occur...

1. pod cpu utilization goal > pod resources (i.e. target defined as 50%, but podspec only requests 25%)
1. pod starts to scale up.  but only scales to 25% usage.
1. pod gets flooded w/ requests, needs more CPU, but stays below 50%.
1. HPA doesn't add new pods : because the CPU target is never breached.

cc @kubernetes/rh-cluster-infra @DirectXMan12 @ncdc

**Comment by ncdc** [comment]
cc @jszczepkowski @piosz @mwielgus @fgrzadkowski

**Comment by jayunit100** [comment]
Closing this issue and just moving it all to the PR
