### ISSUE TITLE
Using kubelet's internal pod status

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#18302]
Forked from https://github.com/kubernetes/kubernetes/pull/17420#issue-117536033, since the PR has already been merged, but we still need an issue to track the status.

 - [x] Wait for rkt-side to be implemented
 - [x] Remove the use of `runningPod` in `syncPod()` in kubelet.go
 - [ ] Retire the container.RuntimeCache
 - [x] Replace GetPodStatusAndAPIPodStatus() with GetPodStatus() and ConvertPodToAPIPodStatus()
 - [x] Deprecate ConvertPodToAPIPodStatus() by surfacing the pod syncing summary to kubelet (see #18172)

Assigning to @Random-Liu since he's working on it already. Feel free to extend the list if I missed anything.

**Comment by Random-Liu** [comment]
ACK! :)

**Comment by yifan-gu** [comment]
cc @dgonyeo

**Comment by Random-Liu** [comment]
Steps for removing `runningPod`:
- [x] Remove `runningPod` from runtime `SyncPod()`
- [ ] Stop using `runningPod` in rkt, now I just convert podStatus to runningPod.
- [ ] Stop using `runningPod` in `KillPod()` of container runtime. [Rely on pod cache #17700]
- [ ] Stop using `runningPod` in `syncPod()` of kubelet.go. [Rely on 2)]
- [ ] Pass podStatus into `syncPod()` of kubelet.go. [Rely on 3)]

**Comment by yujuhong** [comment]
> Retire the container.RuntimeCache

This is semi-done as pod workers no longer rely on this cache for syncing. It is still used by the periodic cleanup routines though.

@Random-Liu I think we can close this one since the majority of the work is done. We can discuss how and whether we should merge the internal pod status cache and the runtime cache offline or in another issue.

**Comment by Random-Liu** [comment]
@yujuhong Sure! :) Thanks

**Comment by Random-Liu** [comment]
@yujuhong Maybe we could have an offline discussion first then file an issue to track the progress. :)
