### ISSUE TITLE
Update scheduler.md for mesos

### ISSUE THREAD

**Issue by jay-lau** [kubernetes/kubernetes#18325]
There are two paramters in scheduler.md is not right and this caused k8sm scheduler cannot start up.

Wrong:
; interval in between internal task status checks/updates
explicit-reconciliation-max-backoff = 2m

; waiting period after attempting to cancel an ongoing reconciliation
explicit-reconciliation-abort-timeout = 30s

Right:
; interval in between internal task status checks/updates
explicit-reconciliantion-max-backoff = 2m
 
; waiting period after attempting to cancel an ongoing reconciliation
explicit-reconciliantion-abort-timeout = 30s

**Comment by jay-lau** [comment]
A patch is here https://github.com/kubernetes/kubernetes/pull/18329

**Comment by karlkfi** [comment]
Thanks for the PR. Closing this duplicate ticket.
