### ISSUE TITLE
e2e cluster didn't start because of certificates

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18335]
Cluster failed to start with the following error:

    00:50:00 e2e-scalability-master-https e2e-scalability 0.0.0.0/0  tcp:443          e2e-scalability-master
    00:52:07 /jenkins-master-data/jobs/kubernetes-e2e-gce-scalability/workspace/kubernetes/hack/e2e-internal/../../cluster/../cluster/../cluster/gce/util.sh: line 523: cd: easy-rsa-master/easyrsa3: No such file or directory
    00:52:07 === Failed to generate certificates: Aborting ===
    00:52:07 2015/12/08 00:52:07 e2e.go:309: Error running up: exit status 2
    00:52:07 2015/12/08 00:52:07 e2e.go:305: Step 'up' finished in 2m36.843513874s
    00:52:07 2015/12/08 00:52:07 e2e.go:141: Error starting e2e cluster. Aborting.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3336/console

@kubernetes/goog-testing

**Comment by wojtek-t** [comment]
@ixdy - can you please take a look?

**Comment by ixdy** [comment]
Seems like probably a one-off failure trying to [download/extract the easy-rsa tarball](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L521-L522)? Maybe we shouldn't ignore failures there. @roberthbailey

**Comment by roberthbailey** [comment]
Yeah, looks like the curl failed and we should add some retries. I sent #18380 and assigned it to @ixdy.

**Comment by gmarek** [comment]
It failed again:
http://kubekins.dls.corp.google.com/view/Kubemark/job/kubernetes-kubemark-gce-scale/287/

We call the same create-certs method as normal kube-up: https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/start-kubemark.sh#L108

**Comment by roberthbailey** [comment]
@ixdy -- either the retries didn't help or our guess as to the failure was wrong. Since all output in that subshell goes to /dev/null, it's hard to diagnose. Can you add some better logging in the subshell that generates certs?

**Comment by ixdy** [comment]
PR out to address logging.

**Comment by ixdy** [comment]
If anyone sees this again, it'd be helpful to link the failing builds so we can investigate with the additional logging enabled.

**Comment by ixdy** [comment]
Haven't seen any failures in the last week. Lowering priority.

**Comment by ixdy** [comment]
Closing as obsolete. Reopen if this happens again.
