### ISSUE TITLE
Kubemark - add retries in scripts.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18334]

**Comment by bprashanth** [comment]
I'd say this is higher than a p2, since it causes submit queue blockage even when tests might've passed

**Comment by gmarek** [comment]
It's a very rare flake - we have way more serious things to do first (like current perfromance regression).

**Comment by bprashanth** [comment]
Flakes are rare, yes. I leave it to you to prioritize.

**Comment by ihmccreery** [comment]
@gmarek In light of the test fixit work we're doing, this should be higher priority.  I'm bumping to P1; feel free to escalate if you disagree.

**Comment by gmarek** [comment]
OK, I'll do it today.

**Comment by davidopp** [comment]
@gmarek is out for the week, reassigning to @fgrzadkowski

**Comment by davidopp** [comment]
Oh actually I see @gmarek has a PR out, which was not LGTMd yet. I'll ping the reviewer.

**Comment by davidopp** [comment]
Reassigning to @fgrzadkowski as Marek is on vacation and this needs to be fixed ASAP. See PR for additional comments.

**Comment by davidopp** [comment]
@mwielgus can you please update the status on this?

**Comment by davidopp** [comment]
Ah never mind, I see #20158 now.

**Comment by davidopp** [comment]
#20158 has been merged, closing.

**Comment by davidopp** [comment]
Reopening as #20158 broke the test completely.
