### ISSUE TITLE
kube-up.sh with vagrant - error: couldn't read version from server

### ISSUE THREAD

**Issue by qwang1** [kubernetes/kubernetes#18344]
On the Kubernetes Release v1.1.2 I got the “error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused” when I setup cluster with "./cluster/kube-up.sh". I searched similar problems and they are closed but still can't solve my problem. Is there someone could take a look? Thanks.

### Version
Vagrant: 1.6.5
VirtualBox: 4.3.16
Kubernetes: tarball v1.1.2 
RHEL: 6.4
Kernel: 2.6.32-358.el6.x86_64

### Step
    # export KUBERNETES_PROVIDER=vagrant
    # ./cluster/kube-up.sh

### Log
    ==> minion-1: Created symlink from /etc/systemd/system/multi-user.target.wants/salt-minion.service to /usr/lib/systemd/system/salt-minion.service.
    ==> minion-1:  *  INFO: Running install_fedora_check_services()
    ==> minion-1:  *  INFO: Running install_fedora_restart_daemons()
    ==> minion-1:  *  INFO: Running daemons_running()
    ==> minion-1:  *  INFO: Salt installed!
    cluster "vagrant" set.
    user "vagrant" set.
    context "vagrant" set.
    switched to context "vagrant".
    Wrote config for vagrant to /root/.kube/config
    Each machine instance has been created/updated.
    Now waiting for the Salt provisioning process to complete on each machine.
    This can take some time based on your network, disk, and cpu speed.
    It is possible for an error to occur during Salt provision of cluster and this could loop forever.
    Validating master
    Connection to 127.0.0.1 closed.
    Validating minion-1
    ............
    Waiting for each minion to be registered with cloud provider
    error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443:  connection refused

[root@qwang kubernetes]# ./cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
error: couldn't read version from server: Get https://10.245.1.2/api: dial tcp 10.245.1.2:443: connection refused

[root@qwang kubernetes]# /var/log/kube-controller-manager.log
bash: /var/log/kube-controller-manager.log: No such file or directory
[root@qwang kubernetes]# /var/log/kube-apiserver.log
bash: /var/log/kube-apiserver.log: No such file or directory

[root@qwang kubernetes]# vagrant ssh master
[vagrant@kubernetes-master ~]$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.246.74.1  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 02:42:70:33:a5:9e  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fefd:ddda  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:fd:dd:da  txqueuelen 1000  (Ethernet)
        RX packets 68272  bytes 94923492 (90.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 32320  bytes 1949387 (1.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.56.106  netmask 255.255.255.0  broadcast 192.168.56.255
        inet6 fe80::a00:27ff:fec8:5a90  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:c8:5a:90  txqueuelen 1000  (Ethernet)
        RX packets 15509  bytes 2676817 (2.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 20839  bytes 87923628 (83.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1472
        inet 10.246.74.0  netmask 255.255.0.0  destination 10.246.74.0
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 51257  bytes 68196261 (65.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 51257  bytes 68196261 (65.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by jlowdermilk** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.
