### ISSUE TITLE
When delete pods, related volumes is exist on cluster nodes. How to automatic clean and delete local volumes?

### ISSUE THREAD

**Issue by ttllyy** [kubernetes/kubernetes#18342]
If I repeat create and delete pods with mount same volume(flocker or hostpath) on cluster nodes, but many related local volumes is exist.
On cluster nodes, run command: docker volume ls
local               4fcf729203ffd31cc0ca5c7c654ad1062101d1b05843421306a12be9c47e4256
local               4115cd9636d4a82e604912f788127e3fb945093c5d7a4a7b975f26b0230c1e65
local               2ce6ae33ab77c655e36a72ed8b110e6a11bd8e72ea5fb85ee398b0c23bcef737
local               d4e552c0c0400806826f4fb532e33f33e83586583a64d9717915f7ae3fab5468
local               2a336e0edfd0c375fbc5da03b8a7693d1cb4330b2dff4e493ad59d70dd3af16b
local               ed0040962eab1854c887a5dbdbcb907fa0e2a4a919186340d5ad18bfca64264e
local               2d59c16a1834515335dc4b4f4898be4cb9e13f487afc6d304f85abb0201e2c25
local               18843040e24e9c67a922b63a31dab33d5ed8ae52de37395f3153b02f43020b27
local               0659730676be3324cac4ab5bf73fde0547c907275a774f0d6267b837531af872
local               280cb8516033264970c6e69a97b7fa23c84b7136bb116c74e0b7113d566ea703
local               93fd44dbde36146904c4c515dd1c3c05f46e8f5f2fceb80445e4788f1277e97e
local               1d6476fc213ba0301d85d6a58fb25412bd9873c4f3a00a193ef27ea0df133b6e
local               b416927e4987d07370b2df2281ed5a188144b66e20901b3c5f1ccdb9dab2d57f
local               1d28013edc95c439b335d500b09ba204d3e609772c62f05e9c207e88223eae7d
local               0984f37a88610b41f1f225829d92a66af371fbce3473e33d5cc3b34c87f98d2c
local               65e455d1b10f1c6fc26a9e2f271838530f77aecfdad39460452aca7c90bac642
local               c7bf7f43eb78f34c10be028fcfd58e490b247ce03e1ebc47c49334a4ed26e203
local               f6ad9ab23bc1397b3cd4fb9924c20b7f4b84149b1faf2410b02eeadef96b7c73
local               5ce89853dcdb38741e9f4ab820735e32634990f973d6d3681307f39b3d142368
local               b85e3339a7b8be18ba0a1f23ee612b41e08473f400c0f77627935d50ced42f6b
local               0263fb02716eb80528ee248b41cdb732362f063990d02972051daac72aef3209
local               367bb9b818552304f0b76b7d127c9b0e8feac035f93f372c2239742166d47564
local               8b26f92c6bf10f194403c798b8311d295cecb2950417f779a2e80ca73a25533e
local               5ecddd53ba927412521d05efa56dcc594b6654ac9b47584cb6a6da71f9f77c65
local               d8ee2f49edb983052dbe98788f23326a425cd298d81e3c446a563b1d70e80426
local               b13364411b6440610a61218e65fa1d632e437a11c34ed46740ae3001b49db306
local               275ca2a572167340600d2b85defb676da85c4749a8cd2559c6ec27a5d5df6d58
local               fc988cc57e32a64cc6135e4b87a71826beaeeb53d304434a958754429e2c6d30
local               e96017927d25de0e0dee86d32920814e3d9dd5883ff9ca512ae8fa461f454439
local               41977ac91de10204002f3840da8963745270141af5ba0e57d392681cb9413a39
local               9d6de99b6cc6b472aaabf882424a9a4b952590e9208b0845d1c6e17955448240
local               aa5eefd83ae3e86b709601c8bd259650262fca7eb767c112d355a672f85b1733
local               605b0a9665cb6569a0f1508f567d36c462f533a310a97cbf44dd1b63c9f91af6
local               f4aab7fd084bf76f8b94f3f3a780d42def44df9a24bd856490bc8e0ba5ce003f
local               c3648a62c37082669eb726319918d818a6470e134446610776cf5539bffade7f
local               af3606c602f1cc2a38cc083765c74e0390c7f24b4925d0715b8a9006a95cdf7a
local               fb20a753ff1f1f47af2d9caddbe1e012b5735a4be68788467b7435295ea83d77

But related pods is deleted.

**Comment by jlowdermilk** [comment]
@dchen1107 do we gc ephemeral hostdir/emptydir/similar volumes?

**Comment by erictune** [comment]
I just noticed on my node that has been up for a while that I have loads of not-gc'ed volumes.

I have 7045 tmpfs volumes mounted, and only two pods on the node.  e.g.:
```console
# mount | grep ^tmpfs 
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=767964k,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /run/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1535920k)
tmpfs on /var/lib/kubelet/pods/11aa1519-a2d9-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/13375af4-a2d9-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/19dcbf85-a2d9-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/fc96b68b-a2d9-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/3233a2c6-a2e3-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/9873d171-a2e8-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/98c11767-a2e8-11e5-a771-42010af00002/volumes
...
tmpfs on /var/lib/kubelet/pods/23447c11-a38c-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/23a7108e-a38c-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/34c04002-a38c-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/406a2709-a38c-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/475a7acc-a38c-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
```

**Comment by erictune** [comment]
I have docker 1.8.3

**Comment by erictune** [comment]
Happening on all 3 of my nodes.

**Comment by erictune** [comment]
Kubelet log is full of 
```
I1216 00:37:41.658468   29296 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/f62c9b2360b1bfe433390f47acda128eb3962cbec62bc5824e156ef433381338 with ou
```

**Comment by erictune** [comment]
```console
# grep 80c28024 /var/log/kubelet.log
E1216 00:40:33.794380   29296 pod_workers.go:125] Error syncing pod 80c28024-a38d-11e5-a771-42010af00002, skipping: not all containers have started: 0 != 1
# mount | grep 80c28024
tmpfs on /var/lib/kubelet/pods/80c28024-a38d-11e5-a771-42010af00002/volumes/kubernetes.io~secret/default-token-8b2l2 type tmpfs (rw,relatime)
```

Maybe this error message is happening and then volumes of those pods are not getting cleaned up?  Just a guess.

**Comment by saad-ali** [comment]
@ttllyy Can you please clarify what exactly the problem you are seeing is and what the repro steps are? It appears you have lots of docker local volumes, are they created by k8s? Can you `docker volume inspect` a few of them. If I understand correctly, you're saying that rapidly creating/deleting a pod with a hostPath volume, causes bind mounts to not get cleaned up?

@erictune I created a new cluster from head and secret volumes for pods appear to be created and cleaned up correctly:

*Before creating pods*
```BASH 
root@e2e-test-saadali-minion-kbpr:/home/saadali# mount | grep tmpfs
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=959398,mode=755)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=767964k,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /run/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1535920k)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
```

*After creating pods:*
```BASH 
root@e2e-test-saadali-minion-kbpr:/home/saadali# mount | grep tmpfs
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=959398,mode=755)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=767964k,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /run/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1535920k)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
tmpfs on /var/lib/kubelet/pods/4b02b280-a393-11e5-bffe-42010af00002/volumes/kubernetes.io~secret/default-token-xewsd type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/4b030e67-a393-11e5-bffe-42010af00002/volumes/kubernetes.io~secret/default-token-xewsd type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/4b06bf60-a393-11e5-bffe-42010af00002/volumes/kubernetes.io~secret/default-token-xewsd type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/4b06b453-a393-11e5-bffe-42010af00002/volumes/kubernetes.io~secret/default-token-xewsd type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/4b06f401-a393-11e5-bffe-42010af00002/volumes/kubernetes.io~secret/default-token-xewsd type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/4b072623-a393-11e5-bffe-42010af00002/volumes/kubernetes.io~secret/default-token-xewsd type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/4b096f1b-a393-11e5-bffe-42010af00002/volumes/kubernetes.io~secret/default-token-xewsd type tmpfs (rw,relatime)
```

*After deleting pods:*
```BASH 
root@e2e-test-saadali-minion-kbpr:/home/saadali# mount | grep tmpfs
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=959398,mode=755)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=767964k,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /run/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1535920k)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
```

This is with docker version:
```BASH
saadali@e2e-test-saadali-minion-62qb:~$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64
```

Just to double check, you deleted the pods right? If not, can you try deleting these pods, once the pods are deleted wait a few minutes for the orphan volume GC to kick in, and see if the mount is cleaned up? If the pods are deleted and they still remain mounted, then maybe there's a bug in the clean up logic for pods that fail?

**Comment by ttllyy** [comment]
@saad-ali 
k8s version:1.1.2
docker version:1.9.0
Too many local volums.
On one nodes, run command: docker volume ls
partial results:
local               11206c68b6296244a875e80cfc932d78deb9f54b8b7bf25154b516c1d108ba1f
local               a6d23d68ec44870ab8b386dbbaf4af503b7d9b44ea249b2873ae245ced899b63
local               4adac6cb358132615a1e1421adc68b59d66b157e1659626e173b50998642a740
local               45ad3ae93c4b8b5fc57081f26544e0409324e4aaa6ac8d7cc010637fcb2ffa6f
local               3c7d4052c501c74bd0edf8ba9351ed62019fc08f42e07e40b666d40723f7b833
local               d3e7bf9b5866de6174ebaba8db6a645b386e420c0a1bff420f973fd71f35804c
local               1ec1d226991f075ef5a569d9ab62166f72a45e67c9602e6330b5a8dccee53437
local               7eebc5cf50e41554c58dd9dab7b5af03078611ffd9c0040c802257cc62fd7808
local               307e2f51d5f14e76a1b1b371511a28756fdcd287acf46a46f30a4fee7a342d63
local               bc4b04d959137a61bfffef4776311a3541228d4048dc2e5cc0e8cf5b9b3ce240
local               87f00ae46859df7e48a8f06be054a40f448d2cd7800f0940d8ecf3371c18ea5c
local               c3728dd99752482abd55dbc8134b8e0cd8f6d85590bddf2c283f8e95e2a42158
local               6efb6467d506581bdb495cb0002bdc0f17fbc903e3e15d2e7df8c577a4e80171
local               f3ae8974851034769cfb275fa6964d288238780e1e3c397e3c670a04f0089a73
local               68a8a92df8ef5137ae70c8fc87abb96b826add35789f643a1bdad6978eaac34d
local               52073d17718c984d6bfe01b892a9a06ea2a8991e06968851a6eb44323be10c6f
local               855d28ac81c97121045199525b60002a4dc694c16b0e117dbec6fd77c405ba66
local               19bb07c710361462f4bf4d12627dea62569e50074a74691ed36e25682cab1637
local               9c9ded521b570545038091779ecee94f54736c3ee8551b329b48f7e1344e2570
local               add6458551c6572a1fe9ce2f2365b422506d12d5b1ed7140146c2dd2e28e7c20

View one volume of the details
docker volume inspect 667d32fda17d93xxxxxxxxx
[
    {
        "Name": "667d32fda17d937513fb2af620ac424001a7251606c4ef526a3c38846a8c6904",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/667d32fda17d937513fb2af620ac424001a7251606c4ef526a3c38846a8c6904/_data"
    }
]

**Comment by erictune** [comment]
turns out I had not deleted the pods.

**Comment by saad-ali** [comment]
@ttllyy I am going to close this as no repro. If you run into this please re-open with detailed repro steps.
