### ISSUE TITLE
Horizontal pod autoscaling based on custom metrics

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#18352]
We are planning to implement horizontal pod autoscaling base on custom metrics.

The custom metrics need to be exposed by each of pods from RC/deployment as described in [custom metrics proposal](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/custom-metrics.md#custom-metrics-in-kubernetes).

Spec of HPA will contain a list of custom metric names together with their target utilizations. If the desired numbers of pods resulting from different custom metrics utilizations are different, the autoscaler will choose the bigger number. HPA Status will contain latest observed values of the custom metrics.

Proposed modification in the API:
```go
type CustomMetricTargetUtilization struct {
    Metric string
    Target float64
}

type HorizontalPodAutoscalerSpec struct {
    ...
    CustomMetricUtilizations []CustomMetricTargetUtilization
}

type CustomMetricCurrentValue struct {
    Metric string
    Value float64
}

type HorizontalPodAutoscalerStatus struct {
    ...
    CustomMetricValues []CustomMetricCurrentValue
}

```

**Comment by jszczepkowski** [comment]
CC @davidopp @bgrant0607 @DirectXMan12 @ncdc @derekwaynecarr @piosz @mwielgus @fgrzadkowski

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by ncdc** [comment]
cc @smarterclayton

**Comment by dchen1107** [comment]
cc/ @vishh @jimmidyson

**Comment by jszczepkowski** [comment]
@erictune Can you comment on this proposal (it is related to HPA API).

**Comment by erictune** [comment]
Why do we think that users need custom metrics?  Why is CPU utilization not sufficient, at least to get HPA out of alpha?

**Comment by erictune** [comment]
If the users are adding prometheus metrics to their pods, why don't they just run a prometheus collector.  Why does kubelet need to get involved.

**Comment by DirectXMan12** [comment]
> If the users are adding prometheus metrics to their pods, why don't they just run a prometheus collector. Why does kubelet need to get involved.

@erictune we need a standard way to have the metrics make their way into Heapster, so that the autoscaler can scale off of them.  The kubelet already exports metrics to Heapster that it collects using cAdvisor, and cAdvisor supports collecting custom metrics in Prometheus format, so it makes sense to just have kubelet configure the its cAdvisor to be able to collect metrics exported from pods.

**Comment by smarterclayton** [comment]
And long term, application metrics (a select subset) are fundamental to the
operational standardization of the platform.  Inventing a parallel system
for them (that reuses all of the same pieces that we gather from nodes)
limits the efficiency of the node.

Imagine how someone would gather application metrics on the platform.  They
would install an agent on the node, that collects metrics, and then wire
heapster to aggregate those metrics, which then stores them in the
backend.  If they didn't add them to heapster, they would add something
exactly like heapster, and then send the data to an influx backend.  So
there would be two heapsters, and two daemons per host, collecting metrics
in the same fashion.

Another angle of inquiry - what makes CPU an optimal metric for measuring
application scale?  Only a subset of applications are CPU bound, and only a
subset of decisions the platform makes about the health of an application
is visible from the standard disk, cpu, and memory budgets.

**Comment by jimmidyson** [comment]
Brain dump for a bit of hopefully useful background...

Applications generally expose many (10s,100s,1000s?) custom metrics. These metrics are specific to the running application (image). Collecting these metrics on the kubelet via embedded cadvisor will introduce a memory footprint which is also a duplication of the memory footprint that the application has for exposing the metrics in the first place. Cadvisor has a way to filter these metrics & limit memory requirement & what is scrapeable via the kubelet stats api. This is configured via Docker labels.

It is likely that most environments will have a separate collector for their custom metrics as well because cadvisor/heapster will only collect a subset of custom metrics. The deployment model for this is dependent on the implementation, but most will not require a daemon set on each node. Either remote pull (eg Prometheus), or push (eg statsd).

It is again likely that deployments will use this separate collector to collect cluster & container metrics via the kubelet stats api so there's more duplication/crossover there.

I think it would be useful if someone provides some use cases for scaling based on custom metrics?

**Comment by jszczepkowski** [comment]
> I think it would be useful if someone provides some use cases for scaling based on custom metrics?

The most obvious use case is scaling based on QPS: each pod handling a given service is exposing a custom QPS metric.

**Comment by DirectXMan12** [comment]
> I think it would be useful if someone provides some use cases for scaling based on custom metrics?

QPS (as above), perhaps concurrent connections to the app (e.g. there's some sort of known optimal "this is how many connections a single instance of an app can reasonable handle"),

**Comment by smarterclayton** [comment]
Applications that expose > 5 metrics definitely need different solutions.
Exposing a core set of simple metrics is about picking metrics for the use
case.   But I would challenge that 90% of applications need that.  Some
level of LCD provides coherent value across the platform.

**Comment by vishh** [comment]
cAdvisor is currently useful for monitoring. A user should be able to expose 10's or 100's of metrics per pod for the sake of monitoring. 
If cAdvisor were to be separated out from kubelet, do we still have to restrict custom metrics exposed per pod? 
Is the primary goal to restrict resource impact at the node or in heapster?
Ideally, a user should be able to expose whatever metrics they need for monitoring through cAdvisor and then use a few of those metrics for HPA.

**Comment by smarterclayton** [comment]
The initial goal was just to be cautious.  Practically, the sorts of
metrics you need to gather at high resolution differs from the sorts of
metrics you want at low resolution.  5 is an arbitrary number that
separates "what is my business measurement" from all the other use cases
(performance monitoring, predictive analytics, etc).  And it wasn't a hard
limit - it was a self imposed limits.  Would I run 60 pods per node and
gather sub 1s resolution metrics on 100 different metrics per pod?  Hard to
believe.

**Comment by jayunit100** [comment]
Agree that the number of metrics is pretty limited probably.  HPA  is a great middle of the road tool for app scaling. Once things get more complex: using another tool or a custom scaling algorithm is much cleaner.

**Comment by davidopp** [comment]
Reassigning to @mwielgus who will be working on this while @jszczepkowski is out.

**Comment by bgrant0607** [comment]
Still catching up, so quick comment: no floats.
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#primitive-types

**Comment by davidopp** [comment]
What's remaining here?

**Comment by mwielgus** [comment]
All things seems to be in place but we don't have e2e tests yet.

**Comment by mwielgus** [comment]
And one extra thing - update cAdvisor in Kubelet if we want to have a limit on the number of custom metrics (the code and the flag is already in cAdvisor).

**Comment by fgrzadkowski** [comment]
@mwielgus Updating cAdvisor is not a blocker IMO. Let's open a separate issue with proper priorities and milestones.

**Comment by fgrzadkowski** [comment]
Created https://github.com/kubernetes/kubernetes/issues/21548 and closing this one. E2e tests are covered by https://github.com/kubernetes/kubernetes/issues/21547
