### ISSUE TITLE
Implement PersistentVolumeSelector

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#18359]
See https://github.com/kubernetes/kubernetes/issues/18333

> Add “Labels” to the PersistentVolume object and “Selectors” to the PersistentVolumeClaim object. The binding controller(s) must resolve labels as it tries to fulfill PVCs.

This feature was deemed non-controversial and can be implemented separately from other proposals for provisioning and volumes.

@thockin @saad-ali @childsb @kubernetes/rh-storage

**Comment by solsson** [comment]
See http://stackoverflow.com/questions/34282704/can-a-pvc-be-bound-to-a-specific-pv

Please add to milestone 1.3.

**Comment by saad-ali** [comment]
Our highest priority items for v1.3 for storage are rock solid reliability. To that end we're making huge investments in stabilizing the existing mount/unmount/attach/detach/provision/delete/bind/recycle code. Completing dynamic provisioning (which includes introduction of selectors/classes) is something we really want and are tracking, but will be a lower priority for v1.3.

**Comment by asalkeld** [comment]
@saad-ali I am not sure of the status of this feature (is someone already working on it), but I need the functionality and can get started with implementing this, if that makes sense now that 1.3 is about done.

**Comment by jsafrane** [comment]
@asalkeld VolumeSelector is already implemented in #25917. I'm closing this issue.
