### ISSUE TITLE
GCE Getting Started is out of date

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#18367]
Placeholder - to be filled in momentarily :)

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/gce.md

**Comment by davidopp** [comment]
This is marked P1. What is the plan here?

**Comment by davidopp** [comment]
ping @aronchick -- what do you have in mind here?

**Comment by goltermann** [comment]
@aronchick I just did a walkthrough of the steps here, and everything looks in order.

The cluster had more services and pods in kube-system now than before, but I don't think keeping this walkthrough up-to-date with an exact list of default services is really needed.

**Comment by aronchick** [comment]
SGTM - let's close this.
