### ISSUE TITLE
Make latest version of the docs available via a stable URL

### ISSUE THREAD

**Issue by mhausenblas** [kubernetes/kubernetes#18363]
Why? Because, as already TimBL pointed out, [cool URL don't change](http://www.w3.org/Provider/Style/URI.html).

So, the latest version of the docs would always be available via http://kubernetes.io/latest/docs which ATM would mean it would redirect to http://kubernetes.io/v1.1/docs and that would change with every release. This increases UX a lot and also helps with search results.

For the context see also http://kubernetes.slackarchive.io/kubernetes-users/-/1449578718/1449595810/1449595572008533/

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by bgrant0607** [comment]
Good idea.

**Comment by bgrant0607** [comment]
Also suggested by #19444

**Comment by bgrant0607** [comment]
This is done.
