### ISSUE TITLE
Any possibility of using a persistent storage on AWS?

### ISSUE THREAD

**Issue by sils1297** [kubernetes/kubernetes#18361]
Hey, I'm desperately trying to build an application on AWS that uses a persistent database. However when I use the example in `examples/aws_ebs/aws-ebs-web.yaml` that doesn't work out, I suppose it's at least related to https://github.com/kubernetes/kubernetes/issues/15073 . (I'm using kubernetes 1.1.4 beta 0, so I guess https://github.com/kubernetes/kubernetes/pull/14493 should be already in there)

I think it would be very important to update documentation here so not everyone steps into the same pit, even if this bug cannot be solved timely; ideally providing an alternative like instructions on how to use AWS RDS and expose that to a container. (That sounds like something that would be simple if one knows kubernetes well enough which I don't yet...)

**Comment by bgrant0607** [comment]
Hopefully the EBS issue has been resolved.

Access to RDS should be documented in a FAQ.

cc @justinsb

**Comment by justinsb** [comment]
Going to close; persistence should work and right now there's no trick for accessing RDS, and it should also "just work" as normal.  We may in future add an IAM proxy for use within kubernetes, but I don't think you can use IAM with RDS anyway.
