### ISSUE TITLE
Cloud Configs templates for CoreOS

### ISSUE THREAD

**Issue by sachingharge** [kubernetes/kubernetes#18364]
Hi Team,

Cloud configs templates listed here should be to OK use with AWS+CoreOS, right?
https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides/coreos/cloud-configs

Please confirm.

Thanks in advance!

**Comment by mikedanese** [comment]
As the getting started guide says, yes.

https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides#turn-key-cloud-solutions
