### ISSUE TITLE
Timeouts for e2e tests running in a parallel environment

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#18366]
Many e2e tests running in parallel environments have been experiencing timeouts recently (e.g, #17656). I am not sure if there has been any change in the jenkins settings that have increased the parallelism, @kubernetes/goog-testing would know more. I did notice that image pulling has become the bottleneck quite often since we started serializing the pulling to work around docker bugs (#10959). Instead of bumping the timeouts aggressively, could we do something else instead? For example,

- Upgrade to docker 1.9 (https://github.com/docker/docker/issues/9718)
- Pre-pull images before the tests start
- Disable serialized image puller (this would result in occasional flaky test as discussed in #10959)
- Lower the number of concurrent tests for the test suites

/cc @kubernetes/goog-node

**Comment by vishh** [comment]
+1 for disabling serializer in parallel testing environments.

**Comment by dchen1107** [comment]
sgtm

**Comment by vishh** [comment]
Closing this issue since #18986 has been merged.
