### ISSUE TITLE
Kubernetes fails to build with "Unsupported host arch..."(on ppc64le)

### ISSUE THREAD

**Issue by jcajka** [kubernetes/kubernetes#18371]
Hello, kubernetes refuses to even try to build on architectures"unknown to it. Is there any reason to refuse to build on unknown arch? 
Except it's unsupported (and it will eat your kittens, fry you CPUs, etc.). It seems to my as unnecessary artificial pitfall, displaying warning and then failing with some build/tests errors(or even surprisingly building without any errors) instead seem more convenient to me.

**Comment by jlowdermilk** [comment]
I think it's mostly that the build scripts are fairly involved at this point, so building on an unknokwn arch is unlikely to work at all. If you want to change it to print a warning and continue, you're welcome to submit a pr.

**Comment by ihmccreery** [comment]
@jcajka We'll happily accept PRs to add support for whatever architecture(s) you're interested in.  I see it going in two ways:

1. somehow decouple the build infra from the architectures, or
1. explicitly support whatever architecture you're trying to build on.

**Comment by ihmccreery** [comment]
I'm marking as priority/P3 for now, but there's something more specific you want/need, please feel free to speak up.

**Comment by luxas** [comment]
I've fixed this with various PRs based on this proposal: #17981
Do you agree @pensu and co?

Closing this for now
