### ISSUE TITLE
GCE: kube-down doesn't clean up all resources

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#18375]
```
$ ./cluster/kube-down.sh
Bringing down cluster using provider: gce
You have specified individual components to update.  If you are trying
 to install new components, use:
  $ gcloud components install alpha

Do you want to run install instead (y/N)?  n


All components are up to date.
You have specified individual components to update.  If you are trying
 to install new components, use:
  $ gcloud components install beta

Do you want to run install instead (y/N)?  n


All components are up to date.

All components are up to date.
Project: xxx
Zone: us-central1-b
Bringing down cluster
...
Cleared config for xxxx from /Users/robertbailey/.kube/config
Done
```

Then an immediate kube-up:

```
$ ./cluster/kube-up.sh 
... Starting cluster using provider: gce
... calling verify-prereqs
You have specified individual components to update.  If you are trying
 to install new components, use:
  $ gcloud components install alpha

Do you want to run install instead (y/N)?  N


All components are up to date.
You have specified individual components to update.  If you are trying
 to install new components, use:
  $ gcloud components install beta

Do you want to run install instead (y/N)?  N


All components are up to date.

All components are up to date.
... calling kube-up
Project: xxx
Zone: us-central1-b
+++ Staging server tars to Google Storage: gs://kubernetes-staging-9f55a0cda4/devel
+++ kubernetes-server-linux-amd64.tar.gz already staged ('rm ./cluster/../cluster/../cluster/gce/../../cluster/../_output/release-tars/kubernetes-server-linux-amd64.tar.gz.uploaded.sha1' to force)
+++ kubernetes-salt.tar.gz already staged ('rm ./cluster/../cluster/../cluster/gce/../../cluster/../_output/release-tars/kubernetes-salt.tar.gz.uploaded.sha1' to force)
Looking for already existing resources
Persistent disk kubernetes-kube-system-kube-registry found.
Would you like to shut down the old cluster (call kube-down)? [y/N]
```

**Comment by roberthbailey** [comment]
@ixdy - can you check to see if we are leaking PDs on the jenkins runs?

**Comment by ixdy** [comment]
@roberthbailey which builds in particular? any that have `FAIL_ON_GCP_RESOURCE_LEAK` set to true in e2e.sh will fail if there are leaked PDs; the others we can check manually, but the check is not guaranteed since the build is running in a shared GCP project.

Builds with `FAIL_ON_GCP_RESOURCE_LEAK` set:
* kubernetes-e2e-gce
* kubernetes-e2e-gce-autoscaling
* kubernetes-e2e-gce-flaky
* kubernetes-e2e-gce-slow
* kubernetes-e2e-gce-parallel-flaky
* kubernetes-e2e-gke-ci
* kubernetes-e2e-gke-ci-reboot
* kubernetes-e2e-gke-flaky
* kubernetes-e2e-gke-subnet
* kubernetes-e2e-gke-prod
* kubernetes-e2e-gke-staging
* kubernetes-e2e-gke-test
* kubernetes-e2e-gke-1.1

**Comment by roberthbailey** [comment]
Depending on when the checks are being done, this might not count as a leak: the disk exists before the test is run because it wasn't cleaned up, the test runs and doesn't clean up the disk, so the disk exists after the test --> no leak.

**Comment by ixdy** [comment]
Right, this check only verifies that the state of the world after cluster teardown matches the state of the world before cluster creation.

**Comment by roberthbailey** [comment]
My main concern (for CI) was that this was causing us to leak PDs, but apparently we would catch that. 

Either way, we should fix the teardown scripts to reduce friction for new users of k8s.

**Comment by ixdy** [comment]
Yeah, for many of the builds we'll start failing builds if we leak resources.

(Incidentally, looking into this I discovered a small bug in the list-resources script: #18376)

**Comment by roberthbailey** [comment]
Marking as obsolete.
