### ISSUE TITLE
Optionally collect kernel logs from nodes in fluentd

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#18387]
Feature Request: Make `/var/log/kern.log` an optional log source in the [google-fluentd.conf](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd.conf) file.

StackOverflow question [here](http://stackoverflow.com/questions/34141748/kernel-logging-to-cloud-logging-for-container-engine-nodes).

**Comment by mark9white** [comment]
Not sure if this is the right place to post, but it seems this is a subset of providing more general configurability over google-fluentd.conf. Another use-case would be allowing structured logging (ie JSON) from container output instead of just text logging.
