### ISSUE TITLE
Abstract the exclusion mechanism out of LeaderElector implementation

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#18386]
Right now, LeaderElection uses operations over an annotation on Endpoints object as an exclusion mechanism. There is an EndpointsMeta field in the LeaderElectorConfig. This detail should be abstracted away from the libraries public API, and the code should be factored in a way to allow for that implementation to change.

cc @timothysc

**Comment by timothysc** [comment]
I likely won't be able to get to this until post-holiday.

**Comment by timothysc** [comment]
@mikedanese I was thinking of creating a simple interface and wrapping the endpoint details behind that interface.  

create
get
update
describe

thoughts?
