### ISSUE TITLE
Allow specifying --config option when spinning up a new ubuntu cluster

### ISSUE THREAD

**Issue by mamikonyana** [kubernetes/kubernetes#18397]
This is useful when trying to deploy run fluentd on all the nodes in the cluster, or some other addon/service that is not officially supported by kubernetes. I can specify ```--config=/etc/kubernetes/manifests``` and after that put the manifest i want to be run on each node in that folder. kubelet supports what but what doesn't seem to be part of the current script.

**Comment by mikedanese** [comment]
FIxed by #18398
