### ISSUE TITLE
Tracking issue for issues related to scheduler performance/scalability

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#18418]
Benchmarking-related
- Scheduler Performance Testing Proposal #18091
- Add a couple of benchmarks for the scheduler #17415
- Design a mechanism to record a real workload and replay it deterministically #3138

Performance/scalability improvement ideas
- Relaxed randomization #18414
- Equivalence classes and caching #17390
- Parallelizing predicate and priority functions across machines #17389

(If I forgot any, please add them. If you do a PR related to scheduler performance/scalability improvements, it's not necessary to add it to the list if it's not already on the list, but please try to remember to mention this issue number so it shows up in the issue log).

**Comment by davidopp** [comment]
@kubernetes/rh-scalability @kubernetes/sig-scalability @jbeda @xiang90 @hongchaodeng

**Comment by wojtek-t** [comment]
@gmarek /me

**Comment by HaiyangDING** [comment]
cc @HaiyangDING @hurf

**Comment by timothysc** [comment]
cc @rrati

**Comment by davidopp** [comment]
ref/ #18831 (which mentions a bunch of issues/PRs)
ref/ #18458

**Comment by davidopp** [comment]
@kubernetes/huawei
