### ISSUE TITLE
Missing dependency for juju provider

### ISSUE THREAD

**Issue by fgimenez** [kubernetes/kubernetes#18422]
Hi, when trying the juju provider following [1] I get:

```
$ export KUBERNETES_PROVIDER=juju
$ cluster/kube-up.sh 
... Starting cluster using provider: juju
... calling verify-prereqs
dpkg-query: no packages found matching juju-deployer
```

This branch [2] adds the missing dependency to the doc.

Thanks !

[1] https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/juju.md
[2] https://github.com/kubernetes/kubernetes/compare/master...fgimenez:added-missing-juju-dependency-to-doc?expand=1

**Comment by ihmccreery** [comment]
Hi @fgimenez, it looks like you have a solution to this on your branch.  Can you please submit a pull request?  See [development.md](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md).

**Comment by fgimenez** [comment]
Hey @ihmccreery, sure here it is #18562

Thanks!

**Comment by ihmccreery** [comment]
Reassigning to @bgrant0607 as reviewer of #18562
