### ISSUE TITLE
Save logs from nodes added during e2e tests (resize, autoscaling, reboot, etc.)

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18432]
Currently we do not, which makes debugging much harder than it should be (#17765)

cc @ixdy @wojtek-t @dchen1107

**Comment by gmarek** [comment]
cc @fejta @krousey @ihmccreery @ixdy @davidopp - has someone time and know-how to do this?

**Comment by ixdy** [comment]
Are the nodes deleted before the test run completes?

**Comment by gmarek** [comment]
There's no test run if cluster setup fails.

**Comment by ihmccreery** [comment]
I'm bumping this to P0 since it's blocking #17765 which is P0.

**Comment by ixdy** [comment]
@gmarek my question stated another way: I'm guessing the nodes added during resize do not persist through the rest of the e2e test run?

**Comment by gmarek** [comment]
No, they do not.

**Comment by lavalamp** [comment]
Maybe we can use a shutdown script? https://cloud.google.com/compute/docs/shutdownscript

**Comment by gmarek** [comment]
+1 - that would be great. This way each machine would be responsible for storing its logs, instead of waiting for Jenkins or something to pull them from it and process it further.

**Comment by lavalamp** [comment]
@ixdy is this something you can take care of?

**Comment by lavalamp** [comment]
I am adding the flake label because this blocks diagnosing flakes.

**Comment by ixdy** [comment]
This seems related to #10423.

It'd be nice if whatever solution we come up with solves both. (Maybe refactor test/e2e/core.go into a separate binary so it can be called from outside ginkgo?)

**Comment by ihmccreery** [comment]
@spxtr Can we close this?

**Comment by spxtr** [comment]
We can. The infrastructure is in place so that if we add or delete nodes in a test they can just call CoreDump as needed.

It's really not ideal, though. Might be worth opening a less-urgent issue to deal with this properly.

**Comment by ihmccreery** [comment]
cc @kubernetes/goog-control-plane @kubernetes/goog-node See above for test infra you can put in place.  I'm removing this from `kind/flake` and reducing priority for a "better" solution.

**Comment by gmarek** [comment]
@spxtr @fejta - is this done?

**Comment by ixdy** [comment]
per https://github.com/kubernetes/test-infra/issues/2112, this is not yet done.

**Comment by fejta** [comment]
This work is happening in test-infra https://github.com/kubernetes/test-infra/pull/2310

**Comment by gmarek** [comment]
@fejta - The work you reference is completely unrelated. It only improves the log download path, so we don't set few GB through network unnecessarily. This issue is about lack of logs from machines that were deleted during e.g. "scale down" tests (or whatever), and are not present when test ends, though we do not schedule this uploader pod there. This is clearly @kubernetes/test-infra-maintainers thing.

**Comment by shyamjvs** [comment]
/unassign @shyamjvs
This is unrelated to my logexporter work as mentioned above by gmarek.

**Comment by spiffxp** [comment]
/remove-help
I don't think this is friendly to new contributors
