### ISSUE TITLE
Ability for the scheduler to place BestEffort pods on nodes with lower utilization

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#18438]
I would like the scheduler to make better decisions on what nodes get `BestEffort` pods by taking into account a the node utilization and not just `node.status.allocable` or `node.status.capacity` to further reduce the risk of starving incompressible resources on my node (memory or disk).

If a node has been scheduled to use all of its `node.status.allocable` value, but actual utilization on the node is nowhere near what was allocated, then the scheduler will prioritize placing `BestEffort` pods on that node versus another node that is actually having greater utilization relative to its allocable limit.

Right now, the scheduler is blind as to what node is best capable of supporting a `BestEffort` pod because their utilization impact on the node is not accounted for when making a scheduling decision.

If the node could publish the following values:
- `node.status.capacity` - the total capacity of the node
- `node.status.allocable` - the amount reserved for scheduling pods

To support this solution, we would need a final design solution for reporting node utilization per the PR proposal here: https://github.com/kubernetes/kubernetes/pull/18634

Then we can make better choices, and further reduce risk of OOM on the node.

**UPDATED** - clarified this has a dependency on Metrics API

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra @timothysc

**Comment by timothysc** [comment]
So you basically want default rank applied, but isn't this really a case where best-effort pods are not specifying their limits accurately?  

It "sounds like" you want to put best effort on the least used nodes, but what if you wanted to compress your cluster size on the fly...?  That least used node is the one that should be drained and shutdown. 

Another problem with pods, is they don't update their attributes and hunt for best fit.

**Comment by derekwaynecarr** [comment]
@timothysc - by definition, best effort pods make no compute resource request.

**Comment by timothysc** [comment]
> by definition, best effort pods make no compute resource request.

For now... I'm sure the google folks can talk about their job sizing algorithms.  xref: http://web.stanford.edu/~cdel/2014.asplos.quasar.pdf

**Comment by derekwaynecarr** [comment]
I think the moment pods are sized (which I think something like what you referenced would do), then they are no longer `besteffort`, and I don't think that we are changing the fact that `besteffort` gets no resource guarantees.  So I am looking for incremental improvement I guess.

**Comment by davidopp** [comment]
I believe this is a dup of #12455. As mentioned there, this feature is blocked on the metrics API (see #11951 and related issues). I think we will have metrics API for 1.2 but we weren't planning to have a scheduling algorithm use it in 1.2. I can try to get a better ETA on the metrics API.

**Comment by vishh** [comment]
@derekwaynecarr: A few optimizations to consider that can improve stability until we have usage based scheduling are,

1. Backpressure from the node if it is noticing system OOMs. We will need this for pods evictions on the node as well.
2. Stronger feasibility checks on the node - reject best effort pods if the current availability is below certain threshold.
3. Cap the total resources that best effort pods can consume on the node - This combined with NodeAllocable should improve node stability. 

Worst fit scheduling using Usage is possible, but requires quite a bit of work and will increase system complexity. Relevant [proposal here](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/metrics-plumbing.md). The proposal itself might be a bit outdated at this point, but it should hopefully highlight some of the system complexity.

Thoughts?

**Comment by derekwaynecarr** [comment]
@vishh - doing items you listed in lieu of what is proposed here satisfies the spirit of what i was looking to support in 1.2 timeframe.

**Comment by davidopp** [comment]
Unless I'm misunderstanding, the stuff Vish listed is all stuff we hadn't planned to do for 1.2. So while it is probably easier than exposing utilizations through the metrics API  and using that in scheduling, it's still new work.

> Backpressure from the node if it is noticing system OOMs. We will need this for pods evictions on the node as well.

What does this mean?

> Stronger feasibility checks on the node - reject best effort pods if the current availability is below certain threshold.

This requires scheduler support. Scheduler needs to rate-limit retries of scheduling pods on nodes that it thinks are feasible but that end up rejecting the pods anyway.

> Cap the total resources that best effort pods can consume on the node - This combined with NodeAllocable should improve node stability.

I assume this means we need the scheduler to start using NodeAllocatable instead of capacity? (I didn't read through that whole issue so I don't know what the final design for NodeAllocatable looks like).

**Comment by derekwaynecarr** [comment]
>>Backpressure from the node if its noticing system OOMs.  We will need this for pods eviction on the node as well.

I read this as meaning that if a node is actively killing pods during low compute resource situations that the node will not accept new pods pending stabilization of the node.  As for the semantics around that, I think we need to close on the resource killing design.

>>Stronger feasibility checks on the node - reject best effort pods if the current availability is below certain threshold.

I am not sure if it mandates scheduler support, but I can see how making the scheduler smarter would help longer term.  Assuming you are not running your cluster at 100% capacity, wouldn't the scheduler potentially find a new node?  I need to refresh my memory on how best-effort pods are handled now.

>>Cap the total resources that best-effort pods can consume on the node...

The spec for node allocable states that the scheduler would no longer schedule on capacity.  As for this item, assuming there was no special cgroup management required and we would just sum up the usage as reported by cAdvisor across best-effort containers this is a :+1: on what we are looking to satisfy for node stability and memory management for best effort on node.

**Comment by derekwaynecarr** [comment]
@davidopp - I copied the node protection use case scenarios to #17186 as part of the general specification requirements for node out of resource killing, and am re-purposing the description of this issue to make the scheduler node metrics API aware.  Since node metrics API is not necessarily in a consumable state for 1.2, I do not think this should be a blocker.

**Comment by derekwaynecarr** [comment]
updated description to state prerequisite on metrics API design being completed, and think this issue should be scheduler specific.  node protection can be satisfied on #17186

**Comment by davidopp** [comment]
> > Stronger feasibility checks on the node - reject best effort pods if the current availability is below certain threshold.

> This requires scheduler support. Scheduler needs to rate-limit retries of scheduling pods on nodes that it thinks are feasible but that end up rejecting the pods anyway.

Sorry, I mis-read your suggestion.  I thought you were suggesting to put some new admission criteria in Kubelet that the scheduler wouldn't know about. But I see you were talking about a new scheduling rule.

Having a user's pods go pending even though they "fit" (resource request < free capacity on the node) seems extremely confusing. We already spread based on request
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/priorities/priorities.go#L118
so I'm not sure what more we can do that wouldn't be confusing. Can you explain your idea in more detail?

> The spec for node allocable states that the scheduler would no longer schedule on capacity. 

I thought the plan was to put node allocatable in the NodeStatus in one binary release, and then not start relying on it in the scheduler until the next release. Though honestly that issue got too long for me to read so I have no idea what the current plan is.

**Comment by vishh** [comment]
cc @timstclair for specific plans around `NodeAllocatable`

**Comment by timstclair** [comment]
I just filed https://github.com/kubernetes/kubernetes/issues/18848 for using Allocatable in the scheduler. We should start using Allocatable to schedule in 1.2, but we won't enforce it on the Kubelet side until a later release.

**Comment by timothysc** [comment]
@ConnorDoyle @balajismaniam want to triage this for tech-debt paydown.

**Comment by davidopp** [comment]
@piosz is working on this as a side project, and the last time I asked him he said he would probably be done with it around the end of this year. (though I think he said it would be in his private repo, so might require some work to upstream.)
