### ISSUE TITLE
Data race in pkg/registry tests with Go 1.5.1

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18437]
A bunch of our pkg/registry/ tests are failing in Go 1.5.1 with the following race:

    WARNING: DATA RACE
    Read by goroutine 28:
      github.com/coreos/etcd/store.(*Event).Clone()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/store/event.go:67 +0x111
      github.com/coreos/etcd/etcdserver/etcdhttp.trimEventPrefix()
      /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/client.go:660 +0x4c
      github.com/coreos/etcd/etcdserver/etcdhttp.writeKeyEvent()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/client.go:578 +0x6ca
      github.com/coreos/etcd/etcdserver/etcdhttp.(*keysHandler).ServeHTTP()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/client.go:151 +0x917
      net/http.(*ServeMux).ServeHTTP()
          /tmp/workdir/go/src/net/http/server.go:1699 +0x212
      github.com/coreos/etcd/etcdserver/etcdhttp.requestLogger.func1()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/http.go:85 +0x2a8
      net/http.HandlerFunc.ServeHTTP()
          /tmp/workdir/go/src/net/http/server.go:1422 +0x47
      net/http/httptest.(*waitGroupHandler).ServeHTTP()
          /tmp/workdir/go/src/net/http/httptest/server.go:200 +0xfe
      net/http.serverHandler.ServeHTTP()
          /tmp/workdir/go/src/net/http/server.go:1862 +0x206
      net/http.(*conn).serve()
          /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

    Previous write by goroutine 126:
      github.com/coreos/etcd/store.(*watcherHub).watch()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/store/watcher_hub.go:81 +0x31d
      github.com/coreos/etcd/store.(*store).Watch()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/store/store.go:402 +0x27a
      github.com/coreos/etcd/etcdserver.(*EtcdServer).Do()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/server.go:570 +0x293
      github.com/coreos/etcd/etcdserver/etcdhttp.(*keysHandler).ServeHTTP()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/client.go:143 +0x57b
      net/http.(*ServeMux).ServeHTTP()
          /tmp/workdir/go/src/net/http/server.go:1699 +0x212
      github.com/coreos/etcd/etcdserver/etcdhttp.requestLogger.func1()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/http.go:85 +0x2a8
      net/http.HandlerFunc.ServeHTTP()
          /tmp/workdir/go/src/net/http/server.go:1422 +0x47
      net/http/httptest.(*waitGroupHandler).ServeHTTP()
          /tmp/workdir/go/src/net/http/httptest/server.go:200 +0xfe
      net/http.serverHandler.ServeHTTP()
          /tmp/workdir/go/src/net/http/server.go:1862 +0x206
      net/http.(*conn).serve()
          /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

This example failure comes from:

k8s.io/kubernetes/pkg/registry/endpoint/etcd TestWatch

@timothysc @xiang90 @yichengq @gmarek @brendandburns

**Comment by timothysc** [comment]
This looks like the test server startup, but I'm running 1.5.1 and have never seen this... 

exact version details of our golang - http://koji.fedoraproject.org/koji/buildinfo?buildID=693253

**Comment by wojtek-t** [comment]
@timothysc - I looked at all the failure, and I don't think it's server startup.

All our failures are in TestWatch tests (for different resources) - so it's clearly related to the Watch.
[Note that we don't have any failures for Created, Update, Delete, List and Get].

So it's clearly related to Watch.

**Comment by wojtek-t** [comment]
@xiang90 @yichengq - since you are much more familiar with this code, maybe you can take a look?

**Comment by xiang90** [comment]
@wojtek-t I will take a look

**Comment by wojtek-t** [comment]
We believe that this race was fixd by https://github.com/coreos/etcd/pull/3972
So the remaining this is to update out etcd Godep to the newer version (once that change is cherrypicked).

**Comment by timothysc** [comment]
I can pull in with my next PR, once we get a cherry-pick.

**Comment by wojtek-t** [comment]
@timothysc - thanks; I'm happy to review that PR

**Comment by wojtek-t** [comment]
OK - this issue is gone now.

Thanks for your fix!
