### ISSUE TITLE
Rolling-update failing on unhealthy pods

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#18435]
(kubectl 1.1.1)

I have a RC with pods in a failing state:

```
NAME        READY     STATUS           RESTARTS   AGE
api-4z7kv   2/3       PullImageError   0          23m
api-es000   2/3       PullImageError   0          41m
api-jz71x   2/3       PullImageError   0          23m
```

I roll an update which fixes the issue (correct image tag):

```
Renaming rc api -> api-rollout ... [OK]
Created api
Scaling up api from 0 to 3, scaling down api-rollout from 3 to 0 (keep 3 pods available, don't exceed 4 pods)
Scaling api up to 1
.
(running for about 3 minutes)
.
error: timed out waiting for any update progress to be made
```

If I take a look at my pods:

```
NAME        READY     STATUS           RESTARTS   AGE
api-4z7kv   2/3       PullImageError   0          26m
api-es000   2/3       PullImageError   0          44m
api-f27mu   3/3       Running          0          3m
api-jz71x   2/3       PullImageError   0          26m
```

Looks like kubectl doesn't even try to delete the pods from the `api-rollout` rc unless these are in a `Running` state.

**Comment by nikhiljindal** [comment]
Yes, rolling-update will not proceed until there are 3 pods available.
It assumes that the pods were in a healthy state to begin with.

In your case, setting maxUnavailable to 2 will fix the issue. But we do not surface that as a flag in kubectl rolling-update.

You can use deployments to do the rolling update, which supports setting maxUnavailable: https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/deployments.md

**Comment by antoineco** [comment]
Thanks for pointing this out @nikhiljindal. It's a bit counter intuitive but if this is by design feel free to close the issue. I'll give deployments a try, I had it on my list anyway.

**Comment by janetkuo** [comment]
@antoineco we're working on making this more intuitive. You may refer to the proposal for more details #18404. Closing this issue now.
