### ISSUE TITLE
Data race in TestDoProbe test

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18440]
The pkg/kubelet/prober/worker_test.go TestDoProbe test is failing with data race in Go 1.5.1

    WARNING: DATA RACE
    Write by goroutine 40:
      k8s.io/kubernetes/pkg/kubelet/prober.TestDoProbe()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/prober/worker_test.go:120 +0x17c6
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

    Previous read by goroutine 41:
      k8s.io/kubernetes/pkg/kubelet/prober.(*manager).updateReadiness()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/prober/manager.go:225 +0x14b
      k8s.io/kubernetes/pkg/kubelet/prober.(*manager).(k8s.io/kubernetes/pkg/kubelet/prober.updateReadiness)-fm()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/prober/manager.go:93 +0x2d
      k8s.io/kubernetes/pkg/util.Until.func1()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:126 +0x58
      k8s.io/kubernetes/pkg/util.Until()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:127 +0x7d
      k8s.io/kubernetes/pkg/util.Forever()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:109 +0x54

It seems pretty clear that:
- NewManager() is calling "go util.Forever(m.updateReadiness, 0)
- and the in worker_test.go:120 you have:
  "m.statusManager = status.NewManager(&testclient.Fake{}, kubepod.NewBasicPodManager(nil))"

Can you please fix it? This is blocking update to Go 1.5.1

@dchen1107 @yujuhong @kubernetes/goog-node

**Comment by yujuhong** [comment]
@timstclair, could you take a look? Thanks!
