### ISSUE TITLE
Improve error message for failed builders

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#18444]
"Unsupported volume type" is the message in the logs when kubelet cannot obtain a builder from a volume plugin.

In the case of RBD, the first error in the log below is what causes a nil builder back to kubelet, but the 3rd line's error message does not reflect *why* the volume is unsupported.  

I'd even go so far as saying the volume *is* supported, but had a builder error, which is not the same thing.

This should be improved for a better user experience and easier debugging.

```
Dec  9 16:13:31 node-1 origin-node: E1209 16:13:31.125609   24447 rbd.go:88] Couldn't get secret mai/&{QxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMQ==}
Dec  9 16:13:31 node-1 origin-node: I1209 16:13:31.125649   24447 volumes.go:109] Used volume plugin "kubernetes.io/persistent-claim" for mongodb3-data
Dec  9 16:13:31 node-1 origin-node: E1209 16:13:31.125667   24447 kubelet.go:1461] Unable to mount volumes for pod "mongodb3-1-xq6ay_mai": unsupported volume type; skipping pod
Dec  9 16:13:31 node-1 origin-node: I1209 16:13:31.125677   24447 kubelet.go:2769] Generating status for "mongodb3-1-xq6ay_mai"
Dec  9 16:13:31 node-1 origin-node: I1209 16:13:31.125702   24447 server.go:732] Event(api.ObjectReference{Kind:"Pod", Namespace:"mai", Name:"mongodb3-1-xq6ay", UID:"8b279ec9-9e7e-11e5-8f87-44a842155c83", APIVersion:"v1", ResourceVersion:"1299", FieldPath:""}): reason: 'FailedMount' Unable to mount volumes for pod "mongodb3-1-xq6ay_mai": unsupported volume type
```

**Comment by markturansky** [comment]
@kubernetes/rh-storage

**Comment by pmorie** [comment]
What's the specific failure in this case?  Userspace tooling for rbd not installed?

**Comment by markturansky** [comment]
no, see the first line in the log.

The RBD code returns a nil builder and error if it cannot find the secret.  The nil builder yields a "unsupported volume type" error.

**Comment by pmorie** [comment]
Right, but _why_ does the rbd code do that?

**Comment by markturansky** [comment]
@roots for the answer.  I presume rbd requires some kind of auth.

**Comment by rootfs** [comment]
the error code for nil builder is hard coded [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumes.go#L142)

but what's odd to me is if rbd returned an err,  we should expect [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumes.go#L138) message first  before unsupported volume message.

What's your kube version?

**Comment by markturansky** [comment]
I think it is here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumes.go#L108

rbd.CanSupport() execs "rbd" and returns false if the binary is not available.

No plugin, so return nil/nil.  UnsupportedVolumeType error.

Improving CanSupport to return (bool, error) would fix this.  https://github.com/kubernetes/kubernetes/issues/12650

**Comment by childsb** [comment]
We removed the CanSupport(..) call, so the message isn't as cryptic.  Now the mount failure is more obvious (unsupported type in kubelet logs..) closing..
