### ISSUE TITLE
Cluster didn't started correctly because of non-empty workspace

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18441]
I've already seen it a couple of time.

The cluster just don't start with the following logs:

    06:31:54 Pulling binaries from GCS
    06:31:54 + [[ '' =~ ^[yY]$ ]]
    06:31:54 ++ find .
    06:31:54 ++ wc -l
    06:31:54 + [[ 2 != 1 ]]
    06:31:54 + echo /jenkins-master-data/jobs/kubernetes-e2e-gce-parallel/workspace not empty, 'bailing!'
    06:31:54 /jenkins-master-data/jobs/kubernetes-e2e-gce-parallel/workspace not empty, bailing!
    06:31:54 + exit 1

The example failure:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/12586/console

@kubernetes/goog-testing

**Comment by quinton-hoole** [comment]
+1 I saw this a few times yesterday, but it went away, so I chalked it up to fallout from the GCE outage, and didn't open an issue.  If we're still seeing it today, we should definitely try to track down and fix.

**Comment by ixdy** [comment]
Additional failures might be helpful to track this down. I can't see where the extra files came from in the Jenkins log, and the workspace has long since been destroyed and recreated. Created #18481 to help debug this.

**Comment by quinton-hoole** [comment]
FYI, I created a Jenkins Failure Cause for this yesterday, so it should be reasonably easy to spot from now on:

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/failure-cause-management/5c580714-b4f6-4714-b3b6-a582e59943bf/

**Comment by spxtr** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9799/console

Another example from before the debug patch.

**Comment by wojtek-t** [comment]
Another instance:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3442/console

@spxtr - this has just happened - you should have more information now

**Comment by spxtr** [comment]
Relevant log:
```bash
11:43:39 ++ find . -not -path './.config*'
11:43:39 ++ wc -l
11:43:39 + [[ 2 != 1 ]]
11:43:39 + echo /jenkins-master-data/jobs/kubernetes-e2e-gce-scalability/workspace not empty, 'bailing!'
11:43:39 /jenkins-master-data/jobs/kubernetes-e2e-gce-scalability/workspace not empty, bailing!
11:43:39 + find .
11:43:39 .
11:43:39 ./console-log.txt
11:43:39 + exit 1
11:43:39 + upload_logs_to_gcs
```

This might be an awkward race condition where most of the time Jenkins hasn't written out to console-log.txt by the time this check goes through, but occasionally it has. If that's the case, it might be worth printing a warning instead of failing the job when the workspace isn't empty, or else ignoring console-log.txt in the find.

**Comment by wojtek-t** [comment]
I'm fine with the fix.

@spxtr can you please do it?
