### ISSUE TITLE
Service status should include info about cloud load-balancer

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#18451]
We should find a way to jam info about the cloud load-balancer that is backing a service into the k8s API.  Ideally the LB name and maybe a URL.  This info is obviously going to vary by cloud provider.  Maybe something simple like a string-string map in status.ingress[*] ?

@arob for ideas
@justinsb I think we discussed this but did not implement it before 1.0

**Comment by ArtfulCoder** [comment]
We currently have coupled creation of LB with the creation of a k8s service.
i feel we should have kept them as separate concepts. 
Your suggestion would tighten the coupling between LBs and k8 services.

An alternative would be to go down a path of creating a separate object for LBs (Ingress or something else) that can map to a service, instead of tightening this coupling.

**Comment by thockin** [comment]
We might want to do that (I like the idea, but it's Yet Another Step), but
no matter what we HAVE this coupling right now and it is too opaque.

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by justinsb** [comment]
I'm not sure what more we would want to do.  We could include a "provider id" field for the load balancer, but in practice at least on AWS it doesn't gain us a lot - the DNS name itself is a better identifier.

Here is where we are today on AWS:

```
> k get services -owide
NAME           CLUSTER-IP       EXTERNAL-IP                                                              PORT(S)          AGE       SELECTOR
guestbook      100.64.32.128    ad55bee634ee011e7b89102561e08ab5-168463352.us-west-2.elb.amazonaws.com   3000:32664/TCP   4m        app=guestbook
...
```

```
> k get service guestbook -oyaml
...
status:
  loadBalancer:
    ingress:
    - hostname: ad55bee634ee011e7b89102561e08ab5-168463352.us-west-2.elb.amazonaws.com
```

`ad55bee634ee011e7b89102561e08ab5` is the name of the AWS load balancer.

```
> aws elb describe-load-balancers
...
             "DNSName": "abe7f60d14e5611e797370a9aefe8be7-637046823.us-east-1.elb.amazonaws.com",
            "SecurityGroups": [
                "sg-6e76971f"
            ],
            "Policies": {
                "LBCookieStickinessPolicies": [],
                "AppCookieStickinessPolicies": [],
                "OtherPolicies": [
                    "k8s-proxyprotocol-enabled"
                ]
            },
            "LoadBalancerName": "abe7f60d14e5611e797370a9aefe8be7",
```

**Comment by thockin** [comment]
@nicksardo

I do think it would be useful to provide a way to track back between
resources.  It could be annotations, though.

**Comment by thockin** [comment]
Dup of #52670 which has more details
