### ISSUE TITLE
Advocate Deployment instead of ReplicationController in documents once it's beta

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#18465]
Ref https://github.com/kubernetes/kubernetes/pull/18184#issuecomment-162782326 Everywhere we encourage users to use ReplicationController should change to advocate Deployment once it's beta (#15313). 

cc @bgrant0607 @amygdala @kargakis @pwittrock @kubernetes/sig-config

**Comment by janetkuo** [comment]
Follow up on update of deployment user guide https://github.com/kubernetes/kubernetes.github.io/pull/127#discussion-diff-56277180

**Comment by bgrant0607** [comment]
@janetkuo and @pwittrock are working on this.

**Comment by ravilr** [comment]
@bgrant0607 @janetkuo when can we expect Deployment to be promoted to v1 core out of beta extensions? in 1.3?

**Comment by bgrant0607** [comment]
@ravilr We have no specific plans for when Deployment should graduate from beta. We're working on a feature roadmap here:
https://github.com/kubernetes/community/wiki/Roadmap:-Deployment

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes.github.io/issues/3863
