### ISSUE TITLE
Incorrect default value of MaxUnavailable in kubectl rolling-update

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#18463]
The default value of maxUnavailable seems to be 0 instead of 1.

I tried rolling update for an RC with 3 replicas and it gave me:
```
Scaling up frontend-v2 from 0 to 3, scaling down frontend from 3 to 0 (keep 3 pods available, don't exceed 4 pods)
```

It should have said keep 2 pods available if maxUnavailable was 1.

cc @janetkuo @ironcladlou @kargakis

**Comment by mqliang** [comment]
```
config := &kubectl.RollingUpdaterConfig{
		Out:            out,
		OldRc:          oldRc,
		NewRc:          newRc,
		UpdatePeriod:   period,
		Interval:       interval,
		Timeout:        timeout,
		CleanupPolicy:  updateCleanupPolicy,
		MaxUnavailable: intstr.FromInt(0),
		MaxSurge:       intstr.FromInt(1),
	}
```

**Comment by nikhiljindal** [comment]
Maybe we did this because before we introduced MaxUnavailable, rolling-update was written in a way that max unavailable was zero and we didnt want to change that behavior.
@ironcladlou might remember.

**Comment by jsravn** [comment]
@mqliang 

This changes fundamental behaviour in rolling-update. If I'm upgrading a single replica, rolling update now succeeds immediately, even though the new replica isn't ready. It even deletes the old RC before the new one is ready.

With maxUnavailable set to 0, prior to this change, rolling-update would wait for the new replica to be ready before returning and deleting the old replica.

I don't understand why this behaviour was a bug. Can you explain before I open an issue for this? (I expect this will hit a lot of people when 1.2 is released).

**Comment by mqliang** [comment]
@nikhiljindal @janetkuo 

I think @jsafrane points out an interesting issue here: how should we handle the case where a RC with a single replica. Keep the default as 1(or 0) for all rolling-update, or set it as 0 when we are updating a RC with a single replica.

**Comment by nikhiljindal** [comment]
Yes I dont think that we want to change the behavior of kubectl rolling-update.

I think it is better to revert to keeping the default for maxUnavailable as 0 for all kubectl rolling-update (as it was in 1.1)

cc @bgrant0607

**Comment by bgrant0607** [comment]
maxSurge should be 1 and maxUnavailable should be 0 by default.

We need to ensure that rollback works, however, in the case that the newRC is unavailable.

cc @kargakis @ironcladlou
