### ISSUE TITLE
Swagger-spec is claiming that all resources are namespaced

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18497]
Looking at our swagger spec is look like e.g. Node is a namespaced resource:
https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L2728

This clearly looks like a bug somewhere.

@nikhiljindal @janetkuo @kubernetes/goog-ux

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/23091 fixes this
