### ISSUE TITLE
Add cluster wide metrics

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18506]
They should live in the API server and should contain:
- number of existing objects in the cluster (# pods, #services, #rc, etc.)
- number of restarts of 'master components' (API server, scheduler, controller manager)
- for HA setup: currently elected master, number of healthy replicas

cc @wojtek-t @davidopp @fgrzadkowski

**Comment by davidopp** [comment]
I assume we'd export it using expvar?

We could have 'kubectl cluster-info' return the info.

**Comment by gmarek** [comment]
I like the idea of adding this to cluster-info.

**Comment by leonidlm** [comment]
@gmarek how about additional metrics such as % allocated cpu/memory per cluster/namespace?

**Comment by gmarek** [comment]
Depends on the question you're asking:) Currently we want to focus on metrics that are useful for monitoring control plane performance. In such case % of cpu used by user is completely uninteresting.

On the other hand for people running clusters it'd be great to have those. But I don't think that single API server metric is a good way to do it, as it requires nontrivial amount of computation, especially if we want to have useful (read: fresh) data all the time, and CPU on master node is already a scarce resource. IIUC we want to expose this kind of information through heapster though - @piosz @mwielgus

**Comment by fgrzadkowski** [comment]
@leonidlm We already expose requested resources (CPU/mem) in Heapster.

**Comment by bgrant0607** [comment]
Number of objects etc. don't need to be collected in apiserver.

An addon has been started to do that:
https://github.com/kubernetes/kube-state-metrics

cc @ghodss

**Comment by bgrant0607** [comment]
This is in kube-state-metrics
