### ISSUE TITLE
Lots of error events concerning loadbalancers on GKE

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kubernetes#18502]
Hello,

I'm running a GKE cluster. It has been migrated from 1.0.7 to 1.1.2.
I'm seeing lots of errors in events related to loadbalancers. They were not present before migration.
They look like this:
```
intkubectl get ev
FIRSTSEEN   LASTSEEN   COUNT     NAME       KIND      SUBOBJECT   REASON                       SOURCE                  MESSAGE
7d          2s         254866    frontend   Service               CreatingLoadBalancer         {service-controller }   Creating load balancer
7d          2s         254818    frontend   Service               CreatingLoadBalancerFailed   {service-controller }   Error creating load balancer (will retry): Failed to create load balancer for service int/frontend: error creating gce static IP address: googleapi: Error 400: Invalid value for field 'resource.address': 'xxx'.  Specified IP address is already reserved., invalid
```

The service definition looks like this:
```
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "frontend",
    "namespace": "int",
    "labels": {
       "name": "frontend"
    }
  },
  "spec": {
    "type": "LoadBalancer",
    "ports": [
      {
        "protocol": "TCP",
        "port": 80,
        "targetPort": 80,
        "name": "http"
      },
      {
        "protocol": "TCP",
        "port": 443,
        "targetPort": 443,
        "name": "https"
      }
    ],
    "selector": {
      "name": "frontend"
    }
  }
}
```

I need to say that after service creation and ephemeral public ip created, I switched the public IP from ephemeral to static. Should I turn them back to ephemeral ?

Is there any way to ensure that public IP is stable across service deletion, creation if for any reason service would be deleted by mistake ?

**Comment by neelance** [comment]
We're seeing a similar issue:
```
prod   8d   3s   1341255   src-native-ci   Service   CreatingLoadBalancer         {service-controller }   Creating load balancer
prod   8d   3s   1341132   src-native-ci   Service   CreatingLoadBalancerFailed   {service-controller }   Error creating load balancer (will retry): Failed to create load balancer for service prod/src-native-ci: this gce project doesn't own the IP address: 104.197.142.113
```
Strangely it even continues after deleting the responsible service. I see no way in stopping this infinite loop via `kubectl`. Do I need to ask the GKE support to restart the master?

**Comment by rvrignaud** [comment]
Hi @neelance did you manage to get rid of the events ?

**Comment by roberthbailey** [comment]
> It has been migrated from 1.0.7 to 1.1.2.

Can you tell me the version of your master and your nodes?

> I need to say that after service creation and ephemeral public ip created, I switched the public IP from ephemeral to static. Should I turn them back to ephemeral?

Did you modify (delete recreate) the service afterwords?

> Is there any way to ensure that public IP is stable across service deletion, creation if for any reason service would be deleted by mistake?

I don't believe so. @thockin would know for certain.

**Comment by roberthbailey** [comment]
@kubernetes/goog-gke

**Comment by thockin** [comment]
The only way to ENSURE that an IP is available in ALL cases is to make it a static IP in the project and add it as `loadBalancerIP` in your Service definition.  Static IPs are quota'ed

**Comment by rvrignaud** [comment]
I just deleted all the problematic services and recreated them with loadBalancerIP specified in the service definition.
This seems to fix my problem (no events anymore).

**Comment by roberthbailey** [comment]
@rvrignaud I'm glad you were able to fix your problem. Is there anything else we can do here or can I close this issue?

**Comment by rvrignaud** [comment]
@roberthbailey Closing this one.

**Comment by speedplane** [comment]
For others who bump into this thread, you need to specify `loadBalancerIP` in your Services definition as follows:

```
apiVersion: v1
kind: Service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.10.10
  ...
```

**Comment by speedplane** [comment]
It does seem a bit problematic that we need to specify the static IP address in our YAML files, kind of defeats the purpose of what Kubernetes is trying to achieve.

**Comment by thockin** [comment]
You should not NEED to specify the IP.  If you do, something is wrong.
