### ISSUE TITLE
node services not able to deploy in Release v1.1.3.. kube-up.sh

### ISSUE THREAD

**Issue by jogendrajangid1** [kubernetes/kubernetes#18503]
Hi All,

i have tested with fresh os installation with prerequest. i have download and build kubernetes properly and also define node and master in config-default.. at time of kube-up.sh running kubernet will deploye only on master and close the process.

node and master is in same network properly connected. its look like kube-up.sh script issue

**Comment by roberthbailey** [comment]
Hi @jogendrajangid1. I'm sorry you never got a response to this issue. However, at this point we are long past the 1.1 branch so I'm going to close this as obsolete. If you are still having issues with kube-up with a recent release (1.6 or 1.5) please open a new issue. Thanks.
