### ISSUE TITLE
[E2E] Dockerfile (or build integration) for compiling image artifacts.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#18516]
Some of the containers need a compilation step for building:

``` ...
webserver: webserver.go
        CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-w' ./webserver.go
...
```
- I think we should have a top-level Dockerfile in `test/images/` which can build test/images golang binaries from zero. 
- Or else, we should just build these binaries as part of the standard kube build.  I dont think they are included as of now?
- any other ideas...

cc @ixdy

**Comment by jayunit100** [comment]
Im leaning towards "if possible, these should just compile in place as part of the build, so that a separate make step isn't required"....

**Comment by jayunit100** [comment]
cc @kubernetes/goog-testing

**Comment by jlowdermilk** [comment]
Are these images that have to be compiled during the test? I think we prefer to build and push images needed for tests to gcr.io if possible.

**Comment by jayunit100** [comment]
So, we don't want continuous integration for images?  If so... I can close this issue, but I'd vote that we should have CI for images.

**Comment by ihmccreery** [comment]
@mikedanese @fgrzadkowski Any thoughts?

**Comment by jlowdermilk** [comment]
Adding the test image files to kube build sgtm. We already compile in unit/integration/e2e binaries and examples. Might as well put test images in too.

**Comment by jayunit100** [comment]
I dug around some on this.  It looks to me like we have some special minimal golang images that we build, which may not work the same as the binaries built by hack/build-go... digging more , open to feedback

**Comment by mikedanese** [comment]
We already test compilation of test/image/ go binaries when we run `godep go install ./...` which runs during CI so we do catch breaks to those images. What is proposed sounds fine but I don't think we should build things that we don't include in the release tar during make release, or make quick-release.

**Comment by jayunit100** [comment]
The broader proposition is that "containers which kube depends on should be as easy to build as kube itself".  How we get there I think can shift throughout the course of this issue.  So far proposed.

- Dockerfile to build all images that anyone can use.
- Build image artifacts as binaries from the hack/build- steps.
- Don't rely on manual go compilation for images/gopath settings that isn't already automated in the build.
