### ISSUE TITLE
Expose metrics from kube-proxy

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#18519]
It would be great if we could throw off some sort of metrics from the proxy per-node.  Right now this is just an interface to drive iptables so we might be limited to what iptables exposes.

**Comment by thockin** [comment]
I'll happily take patches here.  I'm buried and will not get to it any time
soon.

**Comment by errordeveloper** [comment]
cc @squaremo @dpw

**Comment by smarterclayton** [comment]
Dupe of #9125
