### ISSUE TITLE
HorizontalPodAutoscaler API: requirements for graduation to GA

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#18528]
HPA wants to be GA in 1.2.

Let's collect graduation requirements here.

**Comment by erictune** [comment]
Proposed requirement:  Spec and Status of CPU are different style in HPA #18527

**Comment by erictune** [comment]
@jsz @mwielgus @vishh @bgrant0607

**Comment by erictune** [comment]
Evaulate whether these are GA requirements or not:

- Make HPA Controller use Namespacers #16667
- Tolerance: not enough validation in HPA tests. #18221
- HPA Tests: taking 30+ minutes #17941  
- HPA type should accept a resource #16734
- HPA controller needs more flexibility from APIInstaller
- HPA needs to handle discovery, controller credentials, privilege escalation protection
- [hpa] Parameterize tolerance, downscale, and upscale into HPAController, and add corresponding unit test for backsolved tolerance.
- HPA Metrics Client should take a list of pod names instead of a selector

**Comment by vishh** [comment]
@jszczepkowski: Where does custom metrics fit in this picture?

**Comment by jszczepkowski** [comment]
> Where does custom metrics fit in this picture?

Custom metrics are not going to GA in 1.2. They are supposed to be experimental/alpha feature.

**Comment by jszczepkowski** [comment]
Added some more links:

> - HPA controller needs more flexibility from APIInstaller

https://github.com/kubernetes/kubernetes/issues/16500

> - HPA needs to handle discovery, controller credentials, privilege escalation protection

https://github.com/kubernetes/kubernetes/issues/16177

> - [hpa] Parameterize tolerance, downscale, and upscale into HPAController, and add corresponding unit test for backsolved tolerance.

https://github.com/kubernetes/kubernetes/issues/18155

**Comment by jszczepkowski** [comment]
Another requirement:

- graduate scale subresource to GA

**Comment by jszczepkowski** [comment]
One thing to mention: for graduation of HPA to GA, we should consider blockers only issues that affect the API. GA means guarantee of API stability.

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra @smarterclayton @deads2k

**Comment by erictune** [comment]
I reviewed these issues with @mwielgus just now.

The following issues we need to discuss further to see if they are required for GA:

- [ ] #16734 
- [ ] #16732
- [ ] #16500

For all other issues mentioned above, they are either closed or we determined they are not a requirement for GA because fixing them does not require an API change, and they are not so severe as to block GA.

**Comment by piosz** [comment]
@erictune how about #18527? Also #16732 is closed now. Could you and @mwielgus please verify whether you listed correct issues?

**Comment by erictune** [comment]
@piosz updated list per your comments.

**Comment by bgrant0607** [comment]
The Scale resource needs to be updated to use LabelSelector.

**Comment by bgrant0607** [comment]
Or it could return the string that should be passed as the label selector query parameter.

**Comment by deads2k** [comment]
> The Scale resource needs to be updated to use LabelSelector.

I left unsure of whether or not we would extended the `APIResourceList` to include subresources.  I'd like to include that information to make it easier to determine whether something is scalable (or loggable, or bindable, etc).

**Comment by bgrant0607** [comment]
I'm going to update this PR with areas I think we agreed upon and proposals for areas that haven't yet been resolved.

First, areas of agreement:
* status.currentCPUUtilizationPercentage will not be changed in v1. spec.cpuUtilization.targetPercentage will be changed to spec.targetCPUUtilizationPercentage in v1.
* spec.targetCPUUtilizationPercentage isn't actually set to 80% by default. The comment will be fixed. When custom metrics and other criteria are added, targetCPUUtilizationPercentage will be entirely optional (either a member of ExactlyOneOf or AtLeastOneOf several options, though currently there is only one option), so clients must treat it as optional now.
* If write rate of currentCPUUtilizationPercentage causes a problem, then we'll add (implicit) significance thresholds and/or rate limits to reduce the update rate.

**Comment by bgrant0607** [comment]
Proposal regarding scaleRef:

* Rename scaleRef to scaleTargetRef
* The reference should be to the parent resources, not to the scale subresource. The scaleTargetRef must support the scale subresource and the user won't be able to choose a different subresource, which is reasonable, since the controller will only understand scale and, indeed, only specific versions of scale. The user shouldn't care about this implementation detail, anyway. 
* Concretely, the reference should only include apiVersion, kind, and name. 
* For ReplicationController, the scale subresource would need to be found at /api/v1/namespaces/myns/replicationcontrollers/myrc/..., not at a different prefix than the parent.

I think the main question then is how should API versioning and discovery work for polymorphic subresources such as scale.

One approach would be to use HTTP header for version negotiation and add a list of subresources to the APIResource type, each with the subresource name and list of accepted API group/versions.

Another would be to encode the information in the API path:
/api/v1/namespaces/myns/replicationcontrollers/myrc/_subapis/common/v1/scale

Which I agree is verbose/ugly, but we don't expect users to type such URLs.

As for the selector, I suggest we change to the serialized string form in status.

**Comment by deads2k** [comment]
@smarterclayton @liggitt bump for the new conversation

> One approach would be to use HTTP header for version negotiation and add a list of subresources to the APIResource type, each with the subresource name and list of accepted API group/versions.

I like the idea of doing this.  It provides useful information to the clients and gives a `RESTStorage` implementation the option of being forgiving on input and output.

**Comment by bgrant0607** [comment]
The question came up during the meeting why we need the selector at all:

Without the selector, something doing scaling wouldn't have a polymorphic way of knowing what it's scaling, so it couldn't make any decisions.

The count of the current number of replicas is needed to determine whether the scaling has occurred or not. For that purpose, we may want to add generation and observedGeneration, also.

**Comment by bgrant0607** [comment]
There was also activity here: https://github.com/kubernetes/kubernetes/issues/16500#issuecomment-172980593

**Comment by piosz** [comment]
Thank you @bgrant0607 for the proposal and writing the conclusions down. I like the proposal. Does anyone has any objections here (@deads2k, @erictune, @lavalamp, @kubernetes/rh-cluster-infra, @kubernetes/autoscaling)?

**Comment by deads2k** [comment]
> I like the proposal. Does anyone has any objections here

I'm still concerned about:
 1.  The request path and discovery mechanism for `scale` subresources
 2.  Forcing someone to specify an API version if all they care about is the (group,resource) tuple and would like auto-negotiation between the HPA controller and the api server.  The vast majority of the time that is unambiguous.

I'm fine with the rest.

**Comment by lavalamp** [comment]
HTTP headers are harder for dumb clients & browsers. (minor)

I have a slight preference for the `/api/v1/namespaces/myns/replicationcontrollers/myrc/_subapis/common/v1/scale` method, even though it's ugly. I think it's more consistent with the rest of our API.

@bgrant0607, when you say "apiVersion", do you mean "group/version", or one of the ways we talked about to omit the version, like "group/" or "group/..."

(Still not convinced that presenting a selector is the only or best factoring but I definitely don't have time to participate in that debate, so I'm not making any objections there)

**Comment by erictune** [comment]
I'm fine with anything Brian, Daniel and David agree on.

**Comment by smarterclayton** [comment]
HTTP headers in API version negotiation are a disaster for general API versioning (we've been down that path, you always want a version in your path just for sanity).  I am strongly against using accept headers as the primary API version selection mechanism.

However, using HTTP headers to further qualify the content you send and receive from the server is not crazy.  Part of #17922 is setting up so that we can do sub resource negotiation of versioned content types so that users can select what protocol they want for watch (because eventually, we will need to change how the watch protocol works).  In that case, this is fairly clear:

```
GET /api/v1/namespaces/foo/pods/bar
Accept: application/json;apiVersion=v2
---
Content-Type: application/json;apiVersion=v2
{"apiVersion":"v2"}
```

```
POST /api/v1/namespaces/foo/pods/bar
Content-Type: application/json;apiVersion=v2
{....}
```

I would prefer to allow alternate versioning to be associated with the content (or via another header) rather than build up multi stage paths.

**Comment by piosz** [comment]
To summarize the discussion here:
 1. HPA requires two changes
  - `spec.cpuUtilization.targetPercentage` to `spec.targetCPUUtilizationPercentage` #18527
  - `scaleRef` -> `scaleTargetRef`
 1. HPA with mentioned changes will be ready for GA
 1. SubresourceReference will include `apiVersion`, `kind` and `name`
 1. SubresourceReference will be ready for GA
 1. SubresourceReference should be renamed to ParentReference (other name?) since it no longer points to subresource
 1. Scale sub-resource requires at least one change:
 - serialized selector in status, the PR is in flight #19802 

@bgrant0607 @deads2k @lavalamp @smarterclayton do we have an agreement on those items?

The open questions are:
 1. Is Scale sub-resource ready for GA? My opinion is that it doesn't matter since this is just implementation detail. 
 2. If not can HPA be graduated to GA without it? My opinion is yes.
 3. What should be the path to Scale subresource? I like the option proposed by @lavalamp 

Any comments here?

**Comment by liggitt** [comment]
I'm -1 on multi-stage nested paths... differentiating between subresources which use those (e.g. scale), subresources which do not (e.g. all others), and subresources with additional subpaths (e.g. proxy) will be extremely difficult, especially at the outer boundaries for things like authorization which happen outside the web service routes set up by api_installer.go

**Comment by deads2k** [comment]
If you eliminate `subresource` as a field (which I'm fine with), does this become any different than `ObjectReference`?

I'd also prefer to have just `resource/scale` as opposed to an additional sub-api path.

**Comment by liggitt** [comment]
> HPA requires two changes
> - spec.cpuUtilization.targetPercentage to spec.targetCPUUtilizationPercentage #18527
> - scaleRef -> scaleTargetRef

Will conversions handle taking the v1beta1 version to the renamed v1 fields?

**Comment by bgrant0607** [comment]
@deads2k {apiVersion, kind, name} is a subset of ObjectReference, similar to LocalObjectReference. Arguably, we should use a type containing only the supported subset of ObjectReference fields everywhere we use ObjectReference today.

**Comment by bgrant0607** [comment]
As for what to name the ObjectReference subset type, something like CrossVersionObjectReference would be accurate.

The Go type names aren't part of the API, so we can change them later if necessary.

**Comment by bgrant0607** [comment]
Do we need to continue to support the current Scale subresource schema in 1.2?

**Comment by bgrant0607** [comment]
As for non-path-based version negotiation:

Most examples I see for custom content types look like `application/vnd.kubernetes.something-v2+json`. This is a [vendor mime type](http://tools.ietf.org/html/rfc4288#section-3.2). Or `x.kubernetes.something` if we don't want to register the type. The ones that append the version look like `application/x.kubernetes.something+json; version=2`.  I'm not sure what characters and patterns are legal/conventional.

I guess that wouldn't be horrible. We don't expect to hit subresources via browser. curl supports setting header fields. One of the main criticisms of this approach is only relevant to REST APIs that cross-link resources using HTML, which we don't do -- that there's no way to specify header fields in links.

For completeness, query param is also a possibility. That has all the advantages of being part of the URL, without the disadvantages of lengthening the path, IMO. Few people seem to advocate this, though. Debates are mostly URL paths vs. content types.

**Comment by bgrant0607** [comment]
BTW, if we decide not to put Scale's API version in the path, then I think we can punt on version negotiation itself for 1.2. We just need to settle on the path for now, since I expect to only support one API version at a given path.

**Comment by lavalamp** [comment]
Let's try to make a decision on header vs path at tomorrow's API machinery
SIG. I added it to the agenda.

**Comment by piosz** [comment]
@lavalamp good idea
cc @fgrzadkowski

**Comment by piosz** [comment]
@liggitt yes (see also https://github.com/kubernetes/kubernetes/issues/18527#issuecomment-171978591)

**Comment by piosz** [comment]
@bgrant0607 
> Do we need to continue to support the current Scale subresource schema in 1.2?

Since it's implementation details we don't want to graduate it to GA and provide backward compatibility.

>BTW, if we decide not to put Scale's API version in the path, then I think we can punt on version negotiation itself for 1.2. We just need to settle on the path for now, since I expect to only support one API version at a given path.

I like this option.

**Comment by piosz** [comment]
Also I'd like to propose to not graduate Scale subresource to GA. Any objections?

If not we should take into account this once making the decision on "header vs. path". AFAIU with this assumption the decision don't have to be final.

**Comment by ncdc** [comment]
Will extensions/v1beta1 continue to function for HPA?

**Comment by piosz** [comment]
@ncdc it is the plan.

**Comment by piosz** [comment]
It turned out that HPA should be moved out from `extensions` API group (there is no support for multiple versions within the same API group). Additionally there is no clear way how to support cross-group conversions (@lavalamp correct me If I'm wrong). So that to easiest way here is to move HPA related object to `autoscaling/v1` directory and drop support for `extensions/v1beta1`.

@deads2k @liggitt @ncdc would you be very sad with that solution? Any ideas how to support backward compatibility with the current version?

Related proposal is https://github.com/kubernetes/kubernetes/pull/20120

**Comment by ncdc** [comment]
@piosz you want to delete HPA from extensions/v1beta1 entirely?

**Comment by lavalamp** [comment]
@piosz Like I said in my email--

I think to change groups with conversions, you'd first copy the old object into newgroup/v1beta1, then make the new object in newgroup/v1, provide conversion functions, and then make the registry code and the URL paths for the two different groups under the hood go to the same registry. That last bit is explicitly allowed but I don't have a recent example-- minion -> node was the last big name change we did.

Also, we can't just drop support. If anyone is using the v1beta1 object, you need to have at least one release with both so they can upgrade.

**Comment by liggitt** [comment]
> there is no support for multiple versions within the same API group

What specifically do we lack support for... as far as I know, conversion, registration, and routing all can support this. We supported multiple versions in the legacy group prior to dropping v1beta3... we support multiple versions in some utility groups like the abac policy file serialization format.

> @deads2k @liggitt @ncdc would you be very sad with that solution? Any ideas how to support backward compatibility with the current version?

Yes, I would be very sad. I would expect to be able to convert across API groups and keep the old REST endpoint available for a deprecation period.

**Comment by lavalamp** [comment]
What we don't have support for is moving *only one* of the resources into the next version. We have a rule that a client need only know about one version of any group.

Anyway, we don't want an extensions/v1 group at all, extensions is just a holding ground until we find the right groups.

**Comment by piosz** [comment]
@liggitt @lavalamp you are right. There must be some deprecation period.

**Comment by lavalamp** [comment]
So I think what you need to do is:

1. Make the autoscaling group.
2. Copy the v1beta1 object into it verbatim.
3. Configure the registry code to expose the same object under both the extensions/v1beta1 and autoscaling/v1beta1 path, adjusting the type and kind as necessary. @nikhiljindal may be able to help.
  1. The old handler needs to start using the correct storage group/version!
4. Add the v1 object and conversion functions.

To do the upgrade, users should be able to run the existing upgrade storage objects script.

If I missed/forgot a step @smarterclayton might think of it.

**Comment by ncdc** [comment]
@lavalamp that makes me feel much less concerned. I need to talk about @smarterclayton to see how long we need to keep around support for extensions/v1beta1 in OpenShift.

**Comment by piosz** [comment]
@lavalamp thanks for explanation!

@deads2k @liggitt @ncdc apologies for the confusion. I misunderstood what Daniel explained me previously.

**Comment by smarterclayton** [comment]
I think you can simply move the Go structs to the new group, keep
register.go in extensions pointing to the structs in the new group (as long
as you are backcompat), and everything should work.  You'll then register
the REST storage object twice - once in extensions, once in the new group.
The API server should correctly set your version to extensions/v1beta1 or
autoscaling/v1whatever on the way out.

**Comment by liggitt** [comment]
There's already changes proposed to the fields, so a duplicate/conversion would be needed

**Comment by lavalamp** [comment]
Ah, yeah-- what Clayton says is an improvement on my suggestion.

**Comment by lavalamp** [comment]
Yeah, there'd be a duplicate & conversion, but between autoscaler/v1beta1
and autoscaler/v1. Clayton is saying we don't need an *additional* copy in
extensions/v1beta1.

**Comment by liggitt** [comment]
ah, missed "move vs copy" was in reference to v1beta1

**Comment by bgrant0607** [comment]
cc @madhusudancs @erictune 

With respect to #19802.

We need to keep around both the old Scale subresource and add the new Scale (not inter-convertible). 

The old one will be registered at the current extensions/v1beta1/...replicationcontrollers/.../scale path.

The new one will be registered in the appropriate paths under the parent resources:
api/v1/...replicationcontrollers/.../scale
apis/extensions/v1beta1/...replicasets/.../scale
apis/extesnions/v1beta1/...deployments/.../scale

/scale will no longer be supported for Job at all.

**Comment by bgrant0607** [comment]
Oops, forgot one detail: The new Scale type definition will go in the autoscaling group. The old one will remain where it is.

**Comment by lavalamp** [comment]
At the SIG meeting, we decided:

1. We’ll set a particular sub-resource name, e.g. /scale
2. The group/version/kind served at a /scale will depend on the parent group/version/kind. E.g.:
  1. group/v1/namespaces/default/kind/scale is set at first introduction and will never change. It need not match the parent group/version/kind; it could be e.g. extensions/v1beta1/scale
  2. group/v2/namespaces/default/kind/scale may change from the v1 choice, but again will not change for the lifetime of group/v2/kind
  3. Until we figure out how to present this in the discovery information clients will just have to know what group/version/kind the subresource is.
3. We will *not* do the subresource full path
4. We don’t need to do header-based negotiation, either.
5. Servers will support old and new paths long enough for old clients to be upgraded, so we shouldn’t have a problem with version skew between client and server.


(Note: I wrote this a week and a half ago and just found it sitting unsent in one of my many open tabs. Oops!)

**Comment by liggitt** [comment]
> group/v1/namespaces/default/kind/scale is set at first introduction and will never change. It need not match the parent group/version/kind; it could be e.g. extensions/v1beta1/scale

Letting the API server accept a groupVersion other than the parent resource's group version should be done carefully. At least one PR in progress is working on this (https://github.com/madhusudancs/kubernetes/commit/3e4cc6ae6c456b8440edc4f06b65f2053b8c32ad#diff-43c61491ecdb996d7e9eec68fc7f8f36, part of https://github.com/kubernetes/kubernetes/pull/20745). I'd be in favor of allowing targeted resources to accept a group/version other than the parent (like https://github.com/openshift/origin/commit/bac9493add80086f6d766f97b2046f800548d1aa) or removing the API server's responsibility for being the groupversion gatekeeper and letting conversion turn incoming objects into the groupversion the specific resthandler has said it handles.

**Comment by madhusudancs** [comment]
@piosz Now that PR #20501 is merged, we need to make progress on exposing scale at the appropriate paths, i.e. make progress on PR #20745. Will you have time to take over my PR?

cc @bgrant0607 @lavalamp

**Comment by fgrzadkowski** [comment]
@madhusudancs @bgrant0607 AFAIU we agreed that with new reference from HPA object moving Scale object is not a blocker anymore. I'll create a separate issue for it. We still have some blockers we need to work on, but after that we can take a look at scale subresource. Btw - what's left to be done in your PR? Would it be faster if you finish working on it?

**Comment by fgrzadkowski** [comment]
@piosz What's left apart from Scale subresource covered by #21549?

**Comment by piosz** [comment]
#20501 is in, created issues with work needed for 1.3 and 1.4, so closing the issue

**Comment by piosz** [comment]
Thanks everyone for the help!
