### ISSUE TITLE
unit tests on Jenkins are timing out

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18520]
I've seen a bunch of examples where unit tests are failing on Jenkins with timeout.

An example run:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/146e6ae7589b7af42be0be9908766e07c672b77f/kubernetes-pull-test-unit-integration/5291/

This is impacting our ability for merging.

@kubernetes/goog-testing 

@ixdy - can you please take a look? Maybe it's enough to increase timeout?

**Comment by ixdy** [comment]
Bumping up the timeout to 45m. It seems tests take anywhere from 20m to over 30m, depending on worker load - I guess we may want to spin up more slaves to distribute the load better.

**Comment by wojtek-t** [comment]
@ixdy - thanks!

**Comment by spxtr** [comment]
Is this fixed?

**Comment by wojtek-t** [comment]
I didn't see this problem over weekend and today. I guess we can close it (at least for now).
