### ISSUE TITLE
We shouldn't use node names as addresses

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#18525]
[This line in strategy.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/pod/strategy.go#L262) is causing problems for PR #17643. We tried to purge all uses of node names as addresses in #2462, but this one came back in in #6985. It looks like there are some TLS concerns that caused us to punt, but we never came back to it.

**Comment by spiffxp** [comment]
actually, it looks like this was fixed by #33718
/assign
