### ISSUE TITLE
Reject overly precise resource values

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#18538]
Currently, ResourceMemory and ResourceStorage will accept non-whole-number values (e.g. a Pod can request 10 mlli-bytes). This doesn't make sense, so we should reject (in validation) non-integer values for these. Along similar lines, ResourceCPU accepts and blindly rounds up values with sub-milli-core precision (rounding up to nearest milli-core). Rather than rounding, we should reject these values.

These changes are **breaking** changes to the API.

/cc @erictune @bgrant0607

**Comment by bgrant0607** [comment]
#18298 contains another bug fix that is also technically a breaking change (add omitempty to indicate an optional field). 

We've also previously discussed adding other kinds of validation for things that would silently do something other than what the user intended.

We need a standard way of handling such issues. Technically we should wait until a new API version, but, practically, we can't do that every time.

We should at least:
1. Announce that we're considering this change on a public forum for feedback
2. Add a clear section to release notes about possible breaking changes

We might also need to flag-gate the change to allow people to turn it off, if we think it could affect people in practice. (Which is hard to predict.)

@smarterclayton, do you have thoughts about what to do about such changes?

**Comment by smarterclayton** [comment]
Ironically I came back to this while doing performance work, where rounding quantities in the API is incredibly inefficient.

I think flag gating is a good compromise for these sorts of significant bugs with incompatible API.  No one should (for example) be setting millisecond fields, and the longer we wait to discourage that behavior the harder it is to fix.  Likewise, breaking a cluster on an upgrade is also bad.  So putting a set of behavioral flags in place that start automatically off for admins doing a cluster upgrade, but on for new clusters, makes sense on top of the 1/2 you discuss.

**Comment by vllry** [comment]
Someone on my team was just hit by this - requesting memory in `m` (mili) instead of `M` (mega) gave an arcane error during ContainerCreating. There's plenty of bug complaints caused by that behavior, EG #49442
