### ISSUE TITLE
Rolling update doesn't work with kubectl 1.1.2

### ISSUE THREAD

**Issue by dhawal55** [kubernetes/kubernetes#18537]
```
kubectl rolling-update my-app --image=my-app:1.1 --update-period=30s 

Created my-app-056aa8e8096be9448e27f6358466d33c
Scaling up my-app-056aa8e8096be9448e27f6358466d33c from 0 to 3, scaling down my-app from 3 to 0 (keep 3 pods available, don't exceed 4 pods)
Scaling my-app-056aa8e8096be9448e27f6358466d33c up to 1
^[error: timed out waiting for any update progress to be made
```

**Comment by dhawal55** [comment]
When we go back to kubectl 1.0.1, the same command works

**Comment by jlowdermilk** [comment]
If you're running kubectl 1.1.2 against a 1.0 apiserver, it might be a known incompatibility. cc @krousey @ihmccreery

**Comment by dhawal55** [comment]
Its kubectl v1.1.2 against apiserver v1.1.2

**Comment by ihmccreery** [comment]
Assigning to @krousey.

**Comment by krousey** [comment]
@dhawal55 could you report the output of kubectl version? It might help me try to reproduce this.

**Comment by krousey** [comment]
FWIW I have not been able to reproduce this after several attempts. Here's the versions I ran:

```
Client Version: GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171"
Server Version: GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171"
```

**Comment by dhawal55** [comment]
v1.1.2

**Comment by krousey** [comment]
@dhawal55 `kubectl version` should output both a client and server version, along with commit hashes like my comment above.

**Comment by dhawal55** [comment]
weird..it seems to work now. Earlier I was getting the timed out error every time.
