### ISSUE TITLE
Clean up the API initialization process in package registered and package install

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#18531]
Currently, API registration is in done in the [`registered` package](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/registered/registered.go) and the `install` package in each API, e.g., [the `install` package for group ""](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/install/install.go). The `registered` package keeps a hard-coded list of valid GroupVersions and a hard-coded list of GroupVersions that are enabled by default. This is against our goal of separating API machinery from the API.

We plan to remove the `init()` in package `registered` and do all the API initialization in each `install` package. To do so, we conceptually split the API initialization into 2 steps: 
The first step is registration, instead of a hard-coded list, each install package adds their group/versions to the `registered.validGroupVersions` list;
The second step is installation, each `install` package calls a function provided by the `registered` package to learn which group/version the user wants to install, as expressed in KUBE_API_VERSIONS, and then install them. If the environment variable is not set, then all registered group/version will be installed.

The `install` package should export the installation function so that an API can be installed after initialization. [edit] The installation function installs the API without checking `KUBE_API_VERSIONS`. I think @nikhiljindal needs this feature for his apiserver library.

cc @nikhiljindal @deads2k

**Comment by deads2k** [comment]
> as expressed in KUBE_API_VERSIONS, and then install them. If the environment variable is not set, then all registered group/version will be installed.


Can we abstract that out into a method or parameter of some sort that I can choose to describe my desired configuration without environment variables?

**Comment by deads2k** [comment]
> The first step is registration, instead of a hard-coded list, each install package adds their group/versions to the registered.validGroupVersions list;

I tend to think of `GroupMeta` as the source of truth.  Since `install` creates an entry for `GroupMeta`, why do I need the `registered` package?  With the code path you described, I think there's sufficient information contained in each individual `install` package.

**Comment by deads2k** [comment]
@liggitt @smarterclayton fyi

**Comment by caesarxuchao** [comment]
> why do I need the registered package?

This question leads me to find a flaw in my design. If the user specifies version KUBE_API_VERSION=W, but there is no `install` package for W, no error will be reported in my design. I think the `registered` package is used to detect this kind of problem in our current code base.

**Comment by deads2k** [comment]
> This question leads me to find a flaw in my design. If the user specifies version KUBE_API_VERSION=W, but there is no install package for W, no error will be reported in my design. I think the registered package is used to detect this kind of problem in our current code base.

I think that I would try to handle that at a different location.  You could separately validate your envvar value against the actual available `GroupMeta` after all installation is completed.

**Comment by caesarxuchao** [comment]
Yeah, we can make a function call in `import_know_versions.go`: https://github.com/kubernetes/kubernetes/blob/master/pkg/master/import_known_versions.go. It doesn't look elegant though. Do you have better idea?

**Comment by deads2k** [comment]
> Yeah, we can make a function call registered.Validate_KUBE_API_VERSIONS() in import_know_versions.go: https://github.com/kubernetes/kubernetes/blob/master/pkg/master/import_known_versions.go. It doesn't look elegant though. Do you have better idea?

No, I don't.  I don't know how to dynamically load packages in go.

**Comment by caesarxuchao** [comment]
> Can we abstract that out into a method or parameter of some sort that I can choose to describe my desired configuration without environment variables?

@deads2k, does "The `install` package should export the installation function so that an API can be installed after initialization. [edit] The installation function installs the API without checking `KUBE_API_VERSIONS`." meet your needs?

Or do you mean we should get rid of the environment variable completely and instead use a flag (I assumes that a flag is what you mean by `parameter`)? That would require we move all the code out of init() since a commandline flag is out of the reach of init().

**Comment by deads2k** [comment]
> "The install package should export the installation function so that an API can be installed after initialization. [edit] The installation function installs the API without checking KUBE_API_VERSIONS." meet your needs?

Yes, I think it does.

**Comment by caesarxuchao** [comment]
Currently `KUBE_API_VERSIONS` serves two purposes: 1. deciding if a version will be registered to `latest` and the `RESTMapper`; 2. deciding the order of the versions in the `RESTMapper`.

`I think we can relieve it from the version ordering responsibility`. Because 1. The order is not needed by the server, as @lavalamp pointed out this morning, versions are encoded in the url, and the etcd storage version can be specified via cmd line argument. 2. on the client side, the order will impact the result of the translation from `resource` to `fully-qualified kind`, but I think we can hard-code the order in the `install` package in each group, i.e., https://github.com/kubernetes/kubernetes/blob/master/pkg/api/install/install.go#L41. There's no use case that we need to change the order at runtime.

What do you think? @deads2k @smarterclayton

**Comment by deads2k** [comment]
> I think we can relieve it from the version ordering responsibility

I agree.  On the client side, I think that clients should either take the coded default (like you suggested) *or* they'll specify an preferred ordering in their kubeconfig file.

**Comment by smarterclayton** [comment]
The injection of preferred ordering has to go with the codec though.  Today
a RESTMapping is a value object which contains a codec.  We probably need
to be able to create a codec for a particular mapping, which might mean
that something about the rest mapper interface needs to be split out (the
part that returns mappings, and the part that returns client and codec).
That's a bigger refactor though.
