### ISSUE TITLE
AWS (Kubernetes 1.1.2, 1.1.3) KubernetesSeedProvider NullPointerException

### ISSUE THREAD

**Issue by rroopreddy** [kubernetes/kubernetes#18543]
Similar issue as : https://stackoverflow.com/questions/33838668/gke-v1-1-1-kubernetesseedprovider-nullpointerexception

We pretty much using Cassandra example image with a replication controller (3 of them, one for each node). When we start a new cluster then all pods from these replication controllers start fine and joined the same Cassandra cluster.

We have issues when one of the pod dies and restarts through replication controller. Here is the interesting part, if you manually delete/shutdown with "kubctl delete rc node1-rc" and then restart "kubctl create -f node1-rc" then you get the same error below. 

        INFO  22:48:56 Getting endpoints from https://kubernetes.default.cluster.local/api/v1/namespaces/default/endpoints/cassandra
        Exception (java.lang.NullPointerException) encountered during startup: null
        java.lang.NullPointerException
        	at io.k8s.cassandra.KubernetesSeedProvider.getSeeds(KubernetesSeedProvider.java:129)
        	at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:663)
        	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:119)
        	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:488)
        	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:622)
        ERROR 22:48:56 Exception encountered during startup

with the get pods output

        $ ./cluster/kubectl.sh get pods -o wide
        NAME              READY     STATUS             RESTARTS   AGE       NODE
        cassandra-dwwd1   0/1       CrashLoopBackOff   2          24s       ip-172-20-0-39.us-west-2.compute.internal

**Comment by frosenberg** [comment]
Seeing the same issue on v1.1.1. Upgrading to latest master example code and building the image from scratch is also having the same issue

**Comment by jlowdermilk** [comment]
cc @brendandburns

**Comment by brendandburns** [comment]
@rroopreddy @frosenberg what version of the cassandra image are you using?

From that stack trace it looks like its an old cassandra image...

thanks!
--brendan

**Comment by frosenberg** [comment]
I tried both, the one in the yaml file (i think v6) and I also built my own
by also rebuilding the java code.

**Comment by brendandburns** [comment]
please try `gcr.io/google_containers/cassandra:v7` which I just pushed with the latest code.  From looking at the line in the stack trace, I believe this is fixed at head, but I'm not sure it was pushed out in an image...

If it does re-occur, can you re-paste your stack trace?

Thanks!
--brendan

**Comment by brendandburns** [comment]
Closing this as I believe it is fixed.  Please re-open if there are problems.
