### ISSUE TITLE
Permissions on `/tmp/.../schema.json` prevents validations from happening when `kubectl` is run on the master

### ISSUE THREAD

**Issue by mikem** [kubernetes/kubernetes#18555]
I was following [the `coreos/azure` getting started guide][azure] to spin up a Kubernetes cluster on Azure, and the procedure breaks on the firs step of the [Deploying the workload][deploy] section:

[azure]: https://github.com/kubernetes/kubernetes/blob/229f40e69f99fe969a2900ec4a804da516631f33/docs/getting-started-guides/coreos/azure/README.md
[deploy]: https://github.com/kubernetes/kubernetes/blob/229f40e69f99fe969a2900ec4a804da516631f33/docs/getting-started-guides/coreos/azure/README.md#deploying-the-workload

```
core@kube-00 ~ $ kubectl create -f ~/guestbook-example
error validating "/home/core/guestbook-example/frontend-controller.yaml": error validating data: open /tmp/kubectl.schema/v1.1.2/api/v1/schema.json: permission denied; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/home/core/guestbook-example/frontend-service.yaml": error validating data: open /tmp/kubectl.schema/v1.1.2/api/v1/schema.json: permission denied; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/home/core/guestbook-example/redis-master-controller.yaml": error validating data: open /tmp/kubectl.schema/v1.1.2/api/v1/schema.json: permission denied; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/home/core/guestbook-example/redis-master-service.yaml": error validating data: open /tmp/kubectl.schema/v1.1.2/api/v1/schema.json: permission denied; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/home/core/guestbook-example/redis-slave-controller.yaml": error validating data: open /tmp/kubectl.schema/v1.1.2/api/v1/schema.json: permission denied; if you choose to ignore these errors, turn validation off with --validate=false
error validating "/home/core/guestbook-example/redis-slave-service.yaml": error validating data: open /tmp/kubectl.schema/v1.1.2/api/v1/schema.json: permission denied; if you choose to ignore these errors, turn validation off with --validate=false
```

The permissions on this file are:

```
core@kube-00 ~ $ ls -l /tmp/kubectl.schema/v1.1.2/api/v1/schema.json
-rw------- 2 root root 446225 Dec 10 01:33 /tmp/kubectl.schema/v1.1.2/api/v1/schema.json
```

and the user I'm `ssh`-ed into the master as is:

```
core@kube-00 ~ $ whoami
core
```

In #17289 it's mentioned that this is not an issue if one interacts with the cluster by running `kubectl` from your host. This is possible with providers like `vagrant` and `aws` (and indeed I didn't have any issues with those providers).

What's the proper way to interact with my Kubernetes cluster deployed to Azure?

In the meantime, I'm able to work around this issue by disabling validations as the error message suggests.

**Comment by jlowdermilk** [comment]
It looks like the permission issue was fixed by #14087. It missed 1.1, but we can pick it up in a patch release.

I'm not familiar with the azure setup. @errordeveloper, is the kubernetes apiserver exposed externally for azure?

**Comment by mikem** [comment]
Thanks for the link to #14087. I forgot to mention this in the original bug report, but I encountered this on `master` which was at 4f67b0b2117c72c86d365af2c2d338afa199f501 at the time of the report.

**Comment by jlowdermilk** [comment]
@mikem, what kubectl version were you running? From output, looks like 1.1.2. At head, kubectl's schema cache is under `HOME`.

**Comment by mikem** [comment]
@jlowdermilk indeed, it appears I'm running 1.1.2:

```
core@kube-00 ~ $ kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
```

This doesn't have the afea127a3e7a32099f676399efc13dbb653bdf28 commit in it which moves the schema version.

I was under the impression that following [the `coreos/azure` getting started guide][azure] from `master` would give me a Kubernetes cluster based on `master` as well. That's evidently not the case. I'll go looking for where the Azure scripts specify the Kubernetes cluster version and see if I can get a more recent one set up.

[azure]: https://github.com/kubernetes/kubernetes/blob/229f40e69f99fe969a2900ec4a804da516631f33/docs/getting-started-guides/coreos/azure/README.md
