### ISSUE TITLE
Refactor Kubelet with KubeletConfig

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#18554]
The [`Kubelet`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L480) struct definition is almost 200 lines, with over 70 fields. Those fields are a mix of stateful values, static configuration, and helper objects.

I propose factoring out a `KubeletConfig` object to house all of the static configuration parameters (such as `maxPods`, `hostname`, `nodeName`, etc.). This will reduce a lot of the plumbing which is currently necessary for adding new configuration values (such as flags), and also make kubelet construction and definition much more readable. There alread exists a ['KubeletConfig'](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L884) which has a lot in common with the proposed type, but also includes some stateful values such as `record.EventRecorder` and `client.Client`

/cc @kubernetes/goog-node

**Comment by timstclair** [comment]
On second thought, we should probably just wait for the kubelet config API. Is there an issue tracking that work that I can dedup this with, or should I repurpose this one?

/cc @mikedanese

**Comment by spzala** [comment]
@timstclair Hi Tim, are you still working on it? Since it's been over a year, can you please verify if it's still an issue and close it if not? I notice the struct field is now reduced to around 40 lines. Thanks!

**Comment by mtaufen** [comment]
Refactoring the KubeletConfiguration API object is one of my OKRs for this quarter. This doesn't directly impact the internal runtime Kubelet object, because the data from KubeletConfiguration gets forwarded to the Kubelet object. But it will probably make it easier to refactor the Kubelet object in the future.

**Comment by spzala** [comment]
@mtaufen thanks!

**Comment by mtaufen** [comment]
Closing this, as work is tracked in features/issues/281
