### ISSUE TITLE
RFC: Make ABAC policy be a REST object

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#18565]
The ABAC policy in `pkg/apis/abac/types.go` should be a REST object and saved in etcd.

Current, k8s just support load ABAC policy from files, and every time we modify the policy, apiserver should be restart. We should create a storage registry for ABAC policy object, and make it as a API object.

**Comment by mqliang** [comment]
The existing `Policy`struct is defined as follows:
```
type Policy struct {
	unversioned.TypeMeta

	// Spec describes the policy rule
	Spec PolicySpec
}
```

It should also have a `Status PolicyStatus`, for consistency with all other API objects. I could imagine recording status data like timestamp of last policy updated. 

And it should a `ObjectMeta` field, for consistency and make it possible to calculate the key when store it in etcd.

**Comment by jlowdermilk** [comment]
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
The ability to persist some type of Policy in etcd is a long-running discussion topic.

See https://github.com/kubernetes/kubernetes/issues/17440 for background on how we would like to support RBAC policy models as well.
