### ISSUE TITLE
e2e.sh: flock timing out

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#18579]
Saw this in the 1.1 jobs at lunchtime yesterday, and then again this morning in e2e-gce. It's [this line](https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L1173).

```bash
12:39:41 + flock -x -w 60 9
12:40:41 + upload_logs_to_gcs
```

[kubernetes-e2e-gce-release-1.1/972](http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-release-1.1/972/console)
[kubernetes-e2e-gce-release-1.1/973](http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-release-1.1/973/console)
[kubernetes-e2e-gke-1.1/749](http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-1.1/749/console)
[kubernetes-e2e-gce/9835](http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/9835/console)

@kubernetes/goog-testing

**Comment by ihmccreery** [comment]
Closing in favor of #18846.
