### ISSUE TITLE
Metrics du tests broken on F22

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#18576]
Broken tests for me on Fedora 22:

```
 hack/test-go.sh pkg/volume{,/host_path,/empty_dir}                                                                                                                                                               
Running tests for APIVersion: v1,extensions/v1beta1,metrics/v1alpha1 with etcdPrefix: registry
+++ [1211 10:40:39] Running tests without code coverage
--- FAIL: TestMetricsDuGetCapacity (0.00s)
        metrics_du_test.go:41: Expected Used 0 for empty directory to be 4096.
        metrics_du_test.go:60: Unexpected Used for directory with file.  Expected 8192, was 4096.
FAIL
FAIL    k8s.io/kubernetes/pkg/volume    0.011s
--- FAIL: TestMetrics (0.00s)
        host_path_test.go:309: Expected Used &{0 %!d(resource.Format=BinarySI)} to be 4096
FAIL
FAIL    k8s.io/kubernetes/pkg/volume/host_path  0.009s
--- FAIL: TestMetrics (0.00s)
        empty_dir_test.go:307: Expected Used 0 to be 4096
FAIL
FAIL    k8s.io/kubernetes/pkg/volume/empty_dir  0.017s
!!! Error in hack/test-go.sh:240
  'return ${rc}' exited with status 1
Call stack:
  1: hack/test-go.sh:240 main(...)
Exiting with status 1
```

**Comment by rootfs** [comment]
I don't have FC22, but FC 21 doesn't have this problem

**Comment by pmorie** [comment]
@pwittrock FYI

**Comment by eparis** [comment]
@rootfs said in irc that on tmpfs on f21 `du` shows him 0 in an empty directory.  `du` shows him 4096 on an empty directory on an ext4 filesystem. This is the same behavior I see on f23.

However @rootfs says that his unit test is passing.

@rootfs are you sure your tree is up2date and has this test?  I think it is brand new.

**Comment by pmorie** [comment]
I also see the same behavior re: `du`, but the tests fail for me -- I need to continue digging.

**Comment by rootfs** [comment]
rebased to latest and reproduced the problem. Left a [comment](https://github.com/kubernetes/kubernetes/pull/18232/files#r47375263) on the PR

**Comment by pmorie** [comment]
The problem is that the usage of an empty dir on tmpfs is reported differently between fedora and the version of debian in GCE.  From GCE:

```
pmorie@du-test-1:~$ mkdir foo
pmorie@du-test-1:~$ du -s -B 1 foo
4096    foo
pmorie@du-test-1:~$ mkdir /tmp/foo
pmorie@du-test-1:~$ du -s -B 1 /tmp/foo
4096    /tmp/foo
pmorie@du-test-1:~$
```

So, we need to parameterize these tests with the expected usage of an empty dir on tmpfs.  I'll open a PR.
