### ISSUE TITLE
Create a dashboard to monitor metrics from our scalability test runs

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18570]
As part of our continuous testing, we are running (among others) scalability tests.
They have some built-in tests e.g. on pod startup time or API calls latency. However, thee are many other metrics that can be interesting and we don't necessary want to put explicit limits on them.
For different metrics we would like to monitor you can look into: https://github.com/kubernetes/kubernetes/pull/18020

On top of that we would like to have some dashboard (open to the outside world) to:
- track those metrics over different runs (performance regressions)
- monitor metrics within a single run

There are a bunch of different options how to do it:
- use PromDash (since we are already exporting metrics via Prometheus)
- reuse dasboard that we already have (but it doesn't currently work): http://perf-dash.k8s.io/
- use Grafana
- build something from scratch
- use some other open source tool

The is an umbrella issue to decide how to do such a dashboard.
As a prerequisite we need to know the overhead of using Prometheus: #18571

@gmarek @fgrzadkowski @kubernetes/sig-scalability

**Comment by jayunit100** [comment]
cc @jimmidyson

**Comment by wojtek-t** [comment]
Also - we would like to present results from our benchmarks on this dashboard.

**Comment by davidopp** [comment]
@xiang90 @hongchaodeng

**Comment by gmarek** [comment]
We don't have a dashboard per se, as I completely suck UI-wise, but we have a binary that can compare metrics between runs to point us to regressing places and perf-dash is up for noticing them.

**Comment by gmarek** [comment]
perf-dash.io is running.

**Comment by fgrzadkowski** [comment]
Correct link is http://perf-dash.k8s.io/

**Comment by zhouhaibing089** [comment]
I am quite interested at some points:

1.  where is the code for `perf-dash.k8s.io`?
2.  how does those metrics generated?
3.  Is there any documentation for this?

**Comment by gmarek** [comment]
@zhouhaibing089:
(@Random-Liu FYI)

1) https://github.com/kubernetes/contrib/tree/master/perfdash
2) It's a hack now - we embed metrics in test logs which we put in our GCS buckets, and perfdash parses them. There's a plan to write a separate files and make it easy to point perfdash to arbitrary URL, but it wasn't prioritized highly enough.
3) No - it's a quickly hacked tool, so no one thought about writing documentation for it.

**Comment by Random-Liu** [comment]
@zhouhaibing089 Yeah, it's a hack now.
The performance data is printing like this https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubelet_perf.go#L105
in format of https://github.com/kubernetes/kubernetes/blob/master/test/e2e/perftype/perftype.go.

We also have plan to change this to Prometheus type, but also not prioritized now. Feel free to work on it if you are interested. :)
