### ISSUE TITLE
kubernetes service endpoint not in sync with master ip

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#18572]
Our apps running on kubernetes is not working after we restart one of the app's service.  After some debugging, we found that the root cause is due to wrong service endpoint of 'kubernetes' service, which is not the master's internal IP address.  This causes trouble for skyDNS to update records for the app service.

We have to manually update etcd to correct the 'kubernetes' endpoints.  During the process, we also found that API server keeps updating etcd to the wrong IP address, so we have to restart API server in order to make the correction.  (we initially thought it is controller manager that does the update, but it turns out to be apiserver).

I'm not entirely sure why master internal IP changed, it could be DHCP.  But it doesn't make sense for kubernetes to forcibly change to wrong IP, did we cache the information aggresively in api server?

**Comment by quinton-hoole** [comment]
@bprashanth could you take a look? 
@thockin FYI

**Comment by quinton-hoole** [comment]
@ArtfulCoder FYI

**Comment by thockin** [comment]
??  On what platform?

In almost 18 months I have never once seen anything that resembles this.
I'm not saying it doesn't exist, just that it's pretty hard to believe that
nobody else has seen this.

Can you fill in more details?  A step-by-step repro?  What does "restart
one of the app's service" mean?  What IP address did you find for
`kubernetes` ?

**Comment by ddysher** [comment]
Sorry for late reply.

I've tried hard to reproduce this but with no luck.  Nor do I have any clue of what the wrong 'kubernetes' service IP address is.  I'm closing this as it's not reproducible, will re-open if it happens again.
