### ISSUE TITLE
APIResourceList should give sufficient information to build a RESTMapper

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#18577]
We should be able to build a `RESTMapper` based on the discovered `APIResourceList`.  After taking into account the needs of the HPA controller in https://github.com/kubernetes/kubernetes/issues/16500, we need to represent the possible input and output kinds for an `APIResource` in preferred order to reliably build the `RESTMapper`.

Being able to build the `RESTMapper` based on that discovery would provide sufficient information to the generic HPA client to correctly create the URL.Path for a request.

@kubernetes/sig-api-machinery @kubernetes/goog-csi @kubernetes/kube-api @kubernetes/rh-cluster-infra 
@smarterclayton @caesarxuchao @liggitt

**Comment by caesarxuchao** [comment]
@nikhiljindal

**Comment by nikhiljindal** [comment]
This is required for federated API servers as well https://github.com/kubernetes/kubernetes/pull/17191.

kubectl should use the discovery API to discover the group versions, resources and operations supported in the cluster and build a RESTMapper accordingly.

**Comment by caesarxuchao** [comment]
I think we need to add `Kind` to `APIResource`. (https://github.com/kubernetes/kubernetes/pull/18835#issuecomment-166444637), and then devise a way to specify the preferred order in case a kind can be mapped to multiple resources.

**Comment by smarterclayton** [comment]
Resources can return multiple kinds - we should be careful.

On Jan 6, 2016, at 5:27 PM, Chao Xu <notifications@github.com> wrote:

I think we need to add Kind to APIResource. (#18835 (comment)
<https://github.com/kubernetes/kubernetes/pull/18835#issuecomment-166444637>),
and then devise a way to specify the preferred order in case a kind can be
mapped to multiple resources.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/18577#issuecomment-169482627>
.

**Comment by caesarxuchao** [comment]
> Resources can return multiple kinds

@smarterclayton what examples do you have in mind? Looking at the [DefautlRESTMapper.Add()](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta/restmapper.go#L115), it seems you won't have one resource mapping to multiple kinds.

**Comment by lavalamp** [comment]
@smarterclayton The only thing that comes to mind is returning a status when there's an error. Do you have a better example? I don't think Scale counts, since even if the server accepts multiple types, the type it emits would presumably be fixed.

**Comment by smarterclayton** [comment]
That's the common case today.  I think, for now, we can assume Kind is
"string".  There may be a future extension for "additionalKinds" when we
need it.  I generally agree most resources should only ever return one kind
(status being the alternate) until we get into polymorphic endpoints, and
even then it might be better to have the kind be a wrapper / list that
makes this a decoding issue.

**Comment by lavalamp** [comment]
I was about to close this, but I see that the merged PR leaks go type names into the API. Previously, those type names were not considered part of the API. I don't know if we have time to change this. @bgrant0607 How bad do you consider this?

**Comment by lavalamp** [comment]
@bgrant0607 pointed out that we already list this same string in every object-- duh. So I think this is done.
