### ISSUE TITLE
Check overhead of Prometheus in all components.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18571]
We use Prometheus to collect metrics in every component. We haven't measured what memory/cpu overhead it causes. This should be done before deciding how much other metrics to add.
Components to check:
- [ ] API server
- [ ] Controller Manager
- [ ] Scheduler
- [ ] Kubelet

cc @wojtek-t @fgrzadkowski @kubernetes/sig-scalability

**Comment by SuperQ** [comment]
I think this is less about Prometheus, and more about the cost to collect metrics, and the cost to scrape them.

**Comment by gmarek** [comment]
Yeah, but we're using Prometheus for this, so we should measure what we have and work from that.

**Comment by fabxc** [comment]
As far as Prometheus's Go client library goes, setting values is very efficient. See [these slides](https://github.com/gophercon/2015-talks/blob/master/Bj%C3%B6rn%20Rabenstein%20-%20Prometheus/slides.pdf) for a performance analysis.

As far as scraping goes, if there are no heavy computations triggered on collection time, this is hardly noticeable at all and happens once every 15s or so.

**Comment by gmarek** [comment]
I completely agree that it should't be much of a deal. But I want data from our system:).

**Comment by timothysc** [comment]
+1 to previous assertions, we see little impact even at 1/sec polling intervals.
