### ISSUE TITLE
e2e and main gce environments are different

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#18592]
We run w/ "standalone" kubelet in e2e and in main GCE we point the master's kubelet at the apiserver.

This leads to inconsistent behavior between GCE main and e2e.

**Comment by dchen1107** [comment]
This is dup of  #15803.

@gmarek has a pending PR for this: https://github.com/kubernetes/kubernetes/pull/18338

**Comment by dchen1107** [comment]
Send to quickly, to enable this, we need to fix our e2e test harness, and another pending pr to do it: https://github.com/kubernetes/kubernetes/pull/18509

**Comment by dchen1107** [comment]
Close this as dup of #15803.
