### ISSUE TITLE
flannel + gce doesn't work when kubelet on master registers w/ apiserver

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#18593]
If the kubelet registers with the master, it doesn't go through a hack that disables the flannel flag, even if it was specified.  This means that setting `NETWORK_PROVIDER=flannel` and running `cluster/kube-up.sh` results in a broken cluster (at least in GCE)

@bprashanth

**Comment by bprashanth** [comment]
This was fixed with https://github.com/kubernetes/kubernetes/pull/18625
