### ISSUE TITLE
Scale subresource enablement: Should we add note about it in the docs?

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#18594]
There is no specification in the docs about the `scale` subresource about how to enable it.

- I assume there is a flag to turn it on/off...   or is it meant to always be available?
- In general, we need to note what users should do to enable scale/ resources by default.  

Concretely: I'm seeing that its not made available on one of my clusters, even though `deployments/` and hpa are available.   It seems to definetely work when it comes to the salt GCE  deployments.  

cc @jszczepkowski .

I could be mistaken here...  But I really like how the HPA docs clarify exactly how to enable deployments.  If scale needs a similar config knob, we should update the docs.

**Comment by jayunit100** [comment]
UPDATE: I think this caused by tests failing due to heapster versioning issue... still tracking down...  but Looks like this scale/ resource failure could be do to tests going into a tailspin after this failure... 

```
Dec 11 16:34:27 kube-master-1.novalocal kube-controller-manager[30251]: W1211 16:34:27.076459   30251 horizontal.go:183] Failed to reconcile rc: failed to compute desired number of replicas based on CPU utilization for replicationController/e2e-tests-horizontal-pod-autoscaling-k6oh5/rc: failed to get cpu utilization: failed to get CPU consumption and request: failed to unmarshall heapster response: invalid character 'E' looking for beginning of value
```

So, I think (need verification).

- we should say `scale` is enabled by default: its not an API that needs to be turned on.
- there might be a possibility we  need to check heapster version when running HPAs, to avoid other hard-to-track-down failures.

**Comment by jayunit100** [comment]
It appears scale resources are always enabled after digging more.

These error logs, I think, are coming from the fact that HPAs seem to query subscale resource even after the RC has dissapeared. 

So in closing this issue we should:

- make HPA controller periodically confirm that the RC it references is valid.

**Comment by jszczepkowski** [comment]
@jayunit100 

> - make HPA controller periodically confirm that the RC it references is valid.

We have events and error logging [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L98) and [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L145). Do you think it is not enough?

**Comment by jayunit100** [comment]
Is it valid for an HPA to continue querying on a nonexistent RC ?   Seems like it could lead to chaos in the real world.  I could be wrong though, let me know your thoughts.... @jszczepkowski , im happy to close if I'm overthinking this one :)

**Comment by jszczepkowski** [comment]
> - HPAs should close after their RC is gone. IF so, keep this issue.

I think closing HPA may be error prone: RC may be gone for a while and then re-created. Disappearance of HPA will be confusing.

**Comment by jayunit100** [comment]
I guess that makes sense, HPAs can persist even though their RC died off. 

a generic dependency chain for api controllers might be a good idea for the future.

But I'll close for now .
