### ISSUE TITLE
https://github.com/GoogleCloudPlatform/kubernetes stopped redirecting to https://github.com/kubernetes/kubernetes

### ISSUE THREAD

**Issue by mamikonyana** [kubernetes/kubernetes#18596]
That breaks some of the cluster setup scripts.

**Comment by zmerlynn** [comment]
I reported this to @mikedanese a couple of hours ago, and he reported it to GitHub support.

**Comment by mikedanese** [comment]
I've filed an issue with github support.

**Comment by saad-ali** [comment]
From GitHub support via @mikedanese:
> On Fri, Dec 11, 2015 at 7:40 PM, John Greet (GitHub Staff): <support@github.com> wrote:
> ...We fixed the redirect from GoogleCloudPlatform/kubernetes to kubernetes/kubernetes a few hours ago.  I didn't notice any recent transfers or renames that would have changed the redirect behavior, so while we haven't tracked the exact cause down it seem quite possible that this was due to a change on our end.

The redirect appears to be functioning correctly now. Closing issue.
