### ISSUE TITLE
salt docker installtion does not work for debian

### ISSUE THREAD

**Issue by imkin** [kubernetes/kubernetes#18603]
I found that the salts docker/init.sls has debian section inside the redhat block.

https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/docker/init.sls#L10
is the start of redhat

and 

https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/docker/init.sls#L202

is the end of redhat-section [last line]

https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/docker/init.sls#L102

is the section of debian ... in the middle somewhere.

You would never enter the debian section.

Please correct me if I am wrong.

**Comment by jlowdermilk** [comment]
cc @smarterclayton

**Comment by davidopp** [comment]
@mikedanese

**Comment by mikedanese** [comment]
Thanks! @vishh

**Comment by mikedanese** [comment]
@imkin isn't https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/docker/init.sls#L51 the begining of the debian section? I.e.:
```
10: {% if grains.os_family == 'RedHat' %}
    [..]
51: {% else %} # do debian stuff since we aren't in redhat os faimily anymore.
```

**Comment by imkin** [comment]
@mikedanese Agreed. 
Thanks. I miscounted the if-else block as else and if were seperate.
