### ISSUE TITLE
kube-proxy: increase conntrack limits, decrease timeouts

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#18604]
At least one user has had issues with this, and I expect more.  It manifests as dropped packets/connections and dmesg show:

```
[1454500.910215] nf_conntrack: table full, dropping packet
[1454500.911030] nf_conntrack: table full, dropping packet
[1454502.184942] nf_conntrack: table full, dropping packet
[1454502.186097] nf_conntrack: table full, dropping packet
[1454503.898933] nf_conntrack: table full, dropping packet
[1454503.899431] nf_conntrack: table full, dropping packet
[1454505.211093] nf_conntrack: table full, dropping packet
[1454505.211688] nf_conntrack: table full, dropping packet
[1454506.507374] nf_conntrack: table full, dropping packet
[1454506.539645] nf_conntrack: table full, dropping packet
[1454508.027134] nf_conntrack: table full, dropping packet
[1454508.027234] nf_conntrack: table full, dropping packet
[1454509.461080] nf_conntrack: table full, dropping packet
[1454509.461217] nf_conntrack: table full, dropping packet
```

Maybe something like:

```
X=$(cat /proc/sys/net/netfilter/nf_conntrack_max); echo $((X*4)) > /proc/sys/net/netfilter/nf_conntrack_max; echo -n "was $X; now "; cat /proc/sys/net/netfilter/nf_conntrack_max

X=$(cat /sys/module/nf_conntrack/parameters/hashsize); echo $((X*4)) > /sys/module/nf_conntrack/parameters/hashsize; echo -n "was $X; now "; cat /sys/module/nf_conntrack/parameters/hashsize

X=$(cat /proc/sys/net/netfilter/nf_conntrack_generic_timeout); echo $((X/4)) > /proc/sys/net/netfilter/nf_conntrack_generic_timeout; echo -n "was $X; now "; cat /proc/sys/net/netfilter/nf_conntrack_generic_timeout 

X=$(cat /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established); echo $((X/5)) > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established; echo -n "was $X; now "; cat /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established
```

Or maybe we should monitor `nf_conntrack_count` and increase only when needed (it does consume some kernel memory)

Let's keep an eye on this for 1.2.

**Comment by satheessh** [comment]
Even though we cut down the all the  traffic to  kubernetes cluster, We do see lot of open connections from kube proxy.

**Comment by satheessh** [comment]
root@ip-172-20-0-57:~# lsof -i | grep 51922
kube-prox 20942   root   12u  IPv6 897161688      0t0  TCP *:51922 (LISTEN)
-----------------------------------------------------------------------------------------------------------
port 51922 is opened by kube-proxy. (see above command). The number of connections attached to port 51922 is 62k.

root@ip-172-20-0-57:~# netstat -ap | grep 51922 | wc -l
62278

**Comment by justinsb** [comment]
I hit this also.

I was also seeing this error in syslog around the same time (repeating rapidly):

```
Dec 23 00:29:52 ip-172-20-0-237 kube-proxy[11520]: E1223 00:29:52.484964   11520 proxysocket.go:93] Couldn't find an endpoint for default/traefik:http: missing service entry
Dec 23 00:29:52 ip-172-20-0-237 kube-proxy[11520]: E1223 00:29:52.484988   11520 proxysocket.go:138] Failed to connect to balancer: missing service entry
```

Is it possible that we "leak" connections in this case?  Or could it be that rapid retries just overwhelm the connection tracking table?

**Comment by thockin** [comment]
Justin,

It's possible, of course, but no other indicators of leaks.

**Comment by yenif** [comment]
Just ran into this in GKE, last reported measure had number of open tcp connections at 7,759 and 114 req/s with kube-proxy in iptables mode. It looks like the offending connections are udp connections to dns. Increasing sysctl net.ipv4.netfilter.ip_conntrack_max from 65536 to 6553600 stabilizes around 132466 for roughly 100 req/s to an ugly node app that dumps requests into bigquery.

**Comment by thockin** [comment]
PR is in flight.

**Comment by cobrowserAlex** [comment]
I know this is old and maybe the question is stupid, but can someone confirm this setting is updated for all nodes in the cluster at host OS level? If not, how does this work?

I ran into the max with k8s 1.1 and solved by updating the node Host OS with this setting.

**Comment by thockin** [comment]
This was "fixed" for some definition of fixed - apparently some
high-traffic sites still hit limits.
