### ISSUE TITLE
Cloud Configs templates for CoreOS/AWS

### ISSUE THREAD

**Issue by sachingharge** [kubernetes/kubernetes#18612]
Hi Team,

It would be good if cloud config template (YMAL) files provided for CoreOS AWS setup similar like below.
https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides/coreos

It would be really helpful for custom cloudformation template. In cloudformation template, I am trying to use latest stable version of CoreOS 835.9.0 and Kubernetes v1.1.3 version however facing some issues while communicating between containers (I think because of kube-proxy but not sure how to troubleshoot that)
One service is exposed via ClusterIP and one with Loadbalancer (using ELB). It is been working with cluster setup (Kubernetes stable v1.0.7 on EC2 powered by CoreOS 766.5.0)

Another questions, why do need to use alpha release in template? Can't we use stable version of CoreOS?

Also please confirm if below previous points are resolved till v1.1.3
1. AWS Hard coded VPC name (kubernetes-vpc): this seems to be fixed.
2. AWS multi AZ for nodes and creation of external loadbalancer using ELB: I think this is also fixed, please confirm?

Can you please let me know your inputs on this and also please review below cloud configs for Kube master and Node?

Master: https://github.com/sachingharge/automation-scripts/blob/master/cloud-config-master.yaml
Node: https://github.com/sachingharge/automation-scripts/blob/master/cloud-config-node.yaml

Cloudformation template link where above mentioned cloud config is used:
https://github.com/sachingharge/automation-scripts/blob/master/kube-cloudformation.template

Thanks in advance!

**Comment by davidopp** [comment]
@justinsb Can you take a crack at these questions?

**Comment by sachingharge** [comment]
Just to add, I am seeing below error in systemd logs for kube-proxy on nodes:

Dec 14 17:40:48 ip-10-19-2-116.us-west-1.compute.internal kube-proxy[980]: E1214 17:40:48.308099     980 server.go:357] Not trying iptables proxy: can't get Node "ip-10-19-2-116.us-west-1.compute.internal": node "ip-10-19-2-116.us-west-1.compute.internal" not found

Any idea why?


Systemd file for kube-proxy
cat /etc/systemd/system/kube-proxy.service
[Unit]
Description=Kubernetes Proxy
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
Requires=hostname-override.service
After=hostname-override.service

[Service]
ExecStartPre=-/usr/bin/mkdir -p /opt/bin
ExecStartPre=/usr/bin/curl -L -o /opt/bin/kube-proxy -z /opt/bin/kube-proxy https://storage.googleapis.com/kubernetes-release/release/v1.1.3/bin/linux/amd64/kube-proxy
ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-proxy
ExecStart=/opt/bin/kube-proxy \
--master=http://10.19.1.238:8080 \
Restart=always
RestartSec=10

**Comment by sachingharge** [comment]
Noticed one thing regarding kube-proxy, I have two nodes in the cluster and things are working fine on node where container is started however second node I could below exception:

● kube-proxy.service - Kubernetes Proxy
   Loaded: loaded (/etc/systemd/system/kube-proxy.service; static; vendor preset: disabled)
   Active: active (running) since Tue 2015-12-15 00:43:15 UTC; 5min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 966 ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-proxy (code=exited, status=0/SUCCESS)
  Process: 952 ExecStartPre=/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/v1.1.3/bin/linux/amd64/kube-proxy (code=exited, status=0/SUCCESS)
 Main PID: 967 (kube-proxy)
   Memory: 19.8M
      CPU: 194ms
   CGroup: /system.slice/kube-proxy.service
           └─967 /opt/bin/kube-proxy --master=http://10.19.1.152:8080

Dec 15 00:47:40 ip-10-19-2-250.us-west-1.compute.internal kube-proxy[967]: E1215 00:47:40.494264     967 proxysocket.go:104] Dial failed: dial tcp 10.244.47.2:8080: i/o timeout
Dec 15 00:47:40 ip-10-19-2-250.us-west-1.compute.internal kube-proxy[967]: E1215 00:47:40.994533     967 proxysocket.go:104] Dial failed: dial tcp 10.244.47.2:8080: i/o timeout
Dec 15 00:47:41 ip-10-19-2-250.us-west-1.compute.internal kube-proxy[967]: E1215 00:47:41.994790     967 proxysocket.go:104] Dial failed: dial tcp 10.244.47.2:8080: i/o timeout
Dec 15 00:47:43 ip-10-19-2-250.us-west-1.compute.internal kube-proxy[967]: E1215 00:47:43.995049     967 proxysocket.go:104] Dial failed: dial tcp 10.244.47.2:8080: i/o timeout
Dec 15 00:47:44 ip-10-19-2-250.us-west-1.compute.internal kube-proxy[967]: E1215 00:47:43.995093     967 proxysocket.go:138] Failed to connect to balancer: failed to connect to an endpoint.
Dec 15 00:48:46 ip-10-19-2-250.us-west-1.compute.internal kube-proxy[967]: E1215 00:48:46.099230     967 proxysocket.go:104] Dial failed: dial tcp 10.244.47.2:8080: i/o timeout
Dec 15 00:48:46 ip-10-19-2-250.us-west-1.compute.internal kube-proxy[967]: E1215 00:48:46.599516     967 proxysocket.go:104] Dial failed: dial tcp 10.244.47.2:8080: i/o timeout
Dec 15 00:48:47 ip-10-19-2-250.us-west-1.compute.internal kube-proxy[967]: E1215 00:48:47.599807     967 proxysocket.go:104] Dial failed: dial tcp 10.244.47.2:8080: i/o timeout
Dec 15 00:48:49 ip-10-19-2-250.us-west-1.compute.internal kube-proxy[967]: E1215 00:48:49.600081     967 proxysocket.go:104] Dial failed: dial tcp 10.244.47.2:8080: i/o timeout
Dec 15 00:48:49 ip-10-19-2-250.us-west-1.compute.internal kube-proxy[967]: E1215 00:48:49.600122     967 proxysocket.go:138] Failed to connect to balancer: failed to connect to an endpoint.

On working node, where container is deployed:
core@ip-10-19-1-158 ~ $ curl 10.244.47.2:8080
{"timestamp":1450140764580,"status":404,"error":"Not Found","message":"Not Found","path":"/"}core@ip-10-19-1-158 ~ $ curl 10.100.93.242
{"timestamp":1450140778660,"status":404,"error":"Not Found","message":"Not Found","path":"/"}core@ip-10-19-1-158 ~ $

On Second node: 
core@ip-10-19-2-250 ~ $ curl 10.100.93.242
curl: (56) Recv failure: Connection reset by peer
core@ip-10-19-2-250 ~ $ curl 10.244.47.2:8080
curl: (7) Failed to connect to 10.244.47.2 port 8080: Connection timed out

**Comment by aaronlevy** [comment]
Just an FYI, some of these questions were cross-posted here: https://github.com/coreos/coreos-kubernetes/issues/202

**Comment by justinsb** [comment]
Closing; I believe the recommended solutions are now:

* kube-aws from CoreOS if you want to use CoreOS (and can output CloudFormation)
* kops if you want to use other OSes on AWS
* kubeadm if you want to build your own

So kube-aws with terraform seems to meet the requirements here.  Please reopen if that's not right.
