### ISSUE TITLE
Failing Volume/Metrics Unit Tests

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#18619]
There has been a batch of recent unit tests that appear to be failing, I have not bisected what has changed just reporting b/c it is orthogonal to what I'm working on atm.  

Details: 
- golang 1.5.1 on fedora 23  
- recent pulls ~Thur-Fri 
- UT failures below 

-- FAIL: TestMetricsDuGetCapacity (0.14s)
	metrics_du_test.go:41: Expected Used 0 for empty directory to be 4096.
	metrics_du_test.go:60: Unexpected Used for directory with file.  Expected 8192, was 4096.
FAIL
FAIL	k8s.io/kubernetes/pkg/volume	0.180s

--- FAIL: TestMetrics (0.01s)
	empty_dir_test.go:307: Expected Used 0 to be 4096
FAIL
FAIL	k8s.io/kubernetes/pkg/volume/empty_dir	0.026s

--- FAIL: TestMetrics (0.01s)
	host_path_test.go:309: Expected Used &{0 %!d(resource.Format=BinarySI)} to be 4096
FAIL
FAIL	k8s.io/kubernetes/pkg/volume/host_path	0.043s

/cc @kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
I think @pmorie is on the case.

**Comment by pmorie** [comment]
I am: #18580

**Comment by timothysc** [comment]
close from #18580
