### ISSUE TITLE
Evolution of the kube-proxy

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#18623]
We are currently in the process of moving the kube-proxy into a pod - so it's a good time to talk about additional responsibilities for the Kube proxy and the long term evolution about how people experiment with it:
- Some people have developed kube-proxy replacements based on HAProxy that share a resemblance to ingress / route LBs - those have advantages in some cases over even the iptables implementation
- There is a PR from the fall to [move DNS responsibilities to the kube-proxy](https://github.com/kubernetes/kubernetes/pull/11599) - I believe this is the right  long term approach because DNS is service discovery and proxying is intimately associated with service discovery.  They also share the same data set and answer the same questions, and having local dns resolution is >> remote for tolerating outage.  It also means DNS answers and kube proxy LB results are in sync.
- There is the [unidling proposal](https://github.com/kubernetes/kubernetes/pull/3247) from earlier this year that I have someone working now that would add a proposed optional extension to the kube-proxy that would support semantic unidling (scale 0->1) with connection holding to allow administrators to do seamless autoscaling to 0 (which is somewhat disjoint).  This allows admins to transparently offer much higher cluster density.
- The kube proxy, moving to a pod, will now be better able to be replaced on demand and thus be extended.
- How do we leave the door open to extension for kube proxy?  Should the kube-proxy move to its own repo?

Wanted to get some discussion going because both 2 and 3 are in the short term implementation path for us - we're looking for a way to do that efficiently.

**Comment by smarterclayton** [comment]
@thockin @mikedanese @kubernetes/goog-cluster @knobunc

**Comment by thockin** [comment]
One of the things we are working on right now is disentangling network
setup from the core.  This starts with plugins, but it includes
kube-proxy.  In reality kube-proxy is just one (well, two kind of)
implementation of the service VIP abstraction.  There are other
implementations and some don't use kube-proxy at all.

Given that, I am reluctant to pile more behavior onto kube-proxy - if we
want to add more node-local behavior, we should consider how that exists in
a system where kube-proxy isn't running.

**Comment by smarterclayton** [comment]
Maybe I should clarify - those examples are modes of the proxy, sometimes
orthogonal, sometimes overlapping.  Materializing the service abstraction
as DNS, or being an unidling proxy, are simply facets of the proxy (you
have to have DNS point somewhere).  I might start the DNS aspect or the
proxying aspect, but I simply see them as compositional pieces of the node
level network.

One of the things we are working on right now is disentangling network
setup from the core. This starts with plugins, but it includes
kube-proxy. In reality kube-proxy is just one (well, two kind of)
implementation of the service VIP abstraction. There are other
implementations and some don't use kube-proxy at all.


Given that, I am reluctant to pile more behavior onto kube-proxy - if we
want to add more node-local behavior, we should consider how that exists in
a system where kube-proxy isn't running.


I think disentangling is good.  I'm looking to disentangle more - how do I
deliver extensible pieces to the node that allow me to plug in new service
VIP abstractions?  How do I develop them out of the core?

I'd like to split Kube-proxy into its own GIT repo and have it be compiled
into an image, which an admin delivers to the node via a daemon set and is
easily replaced / forked.  In our fork, we'd have DNS and unidling
replacement modes.  You guys can then choose whether you want those or not.

That seems like a valuable goal regardless - makes Kube proxy less tied to
the core.

**Comment by feiskyer** [comment]
How to ensure the HA of kube-proxy pod?

**Comment by smarterclayton** [comment]
Same approaches as today.  SO_REUSEPORT, fast restart, leveraging iptables
to potentially stall or queue packets during restart.

On Dec 13, 2015, at 9:33 PM, feisky <notifications@github.com> wrote:

How to ensure the HA of kube-proxy pod?

**Comment by thockin** [comment]
I'm all in favor of composition, but that says to me more smaller pieces
not more operational modes of a demi-monolith.

Why not make DNS a standalone daemonset?

The main argument against cracking this off the main repo is the same
argument for all the other major components - the coupling it too high, the
client lib is too entangled, the tooling is not ready (git munger, e2e,
etc), the versioning needs to be solved, the vendoring, etc.

I'm not against the idea - I like it.  But  we have repeatedly
de-prioritized many of these issues (or they are in slow flight now), which
makes it hard to do at this point in time.

**Comment by smarterclayton** [comment]
There should be an internet law about the invocation of "monolith", kind of like Godwin's law.  :)

To me, DNS and service proxying are fundamentally the same - whether they're decoupled or coupled is really just about operational cost.  I've seen an uptick in customers who want to run dnsmasq locally to deal with problems connecting to the DNS daemon to guarantee uptime of their containers.  The operational cost is that i really don't want to have two watchers of services/endpoints per node - and the decisions that DNS might make on a node are the same as the service proxy.  

I'm trying to weigh forking kube-proxy and carrying a set of functions that vary from upstream Kube (we already serve DNS differently, and I mostly don't regret it), vs contributing that function back to the upstream community.  Both of the proposed features are coupled to one aspect of the proxy today, so the path of least design resistance is to add that facet.  But I understand your concerns.

Agree the tooling is not totally solved - I'm just trying to find how to reduce long term development effort waste (carry a fork, possible behavior in openshift vs kube, etc).

**Comment by thockin** [comment]
On Mon, Dec 14, 2015 at 6:47 AM, Clayton Coleman
<notifications@github.com> wrote:
>
> To me, DNS and service proxying are fundamentally the same - whether they're decoupled or coupled is really just about operational cost.

The operational cost concern is real, but balance it with the
complexity of making kube-proxy a swiss-army-knife of
sort-of-related-but-only-barely functionality.  It's a totally legit
proposition to use our DNS without our VIP implementation.  I could
argue to bundle it with kubelet - at least that one is not
disableable.  The idling proposal is a bit more coupled than DNS.  How
will idling work if someone wants to run a totally different VIP
system?

> I've seen an uptick in customers who want to run dnsmasq locally to deal with problems connecting to the DNS daemon to guarantee uptime of their containers. The operational cost is that i really don't want to have two watchers of services/endpoints per node - and the decisions that DNS might make on a node are the same as the service proxy.

It's a balance between combined complexity of a single mega-agent vs
fine-grained complexity and resources of N simple agents.  I'm not
saying it's decided either way, but I haven't seen any measurements of
the resources needed to run a simple DNS server binary.

**Comment by smarterclayton** [comment]
>  It's a totally legit proposition to use our DNS without our VIP implementation.  

Sure - kube-proxy starting in "DNS only mode" doesn't seem terribly different to me than its current behavior of "iptables only" though.  I agree there is a swiss army knife fear here - but practically speaking I'm going to reimplement something that looks exactly like kube-proxy to do almost exactly what kube proxy does (it responds to IP connections and turns them into proxy endpoints, DNS responds to name requests and turns them into name endpoints).

> idling

Idling requires an endpoint somewhere that can hold traffic.  It also requires clients to know what endpoint that is.  That's either a VIP or a real physical port on a machine somewhere.  Most proxies are terrible at holding traffic - it's not worth trying to retrofit (read, hack) it into every proxy on the planet.  The implementation of an ideal unidler is a proxy component on each node that can easily take incoming traffic, hold it when there are no backends, and then when a backend arrives pass it onwards.  The kube-proxy is ideal because when new endpoints appear it creates new iptables rules, which transparently forward new connections on to the new endpoints.  The proxy keeps the original connection going until it disconnects, at which point it's not listening anymore.

>  measurements of the resources needed to run a simple DNS server binary.

It's watch traffic (double the watch traffic per node), plus list traffic (double again), plus the memory to hold the state map (65k services x ~1k data).  Then there's the DNS cache if using skydns, which is a bit more.  Finally, all the garbage collection overhead from maintaining the internal list-watch cache, which is again double than what the node-proxy uses.

**Comment by thockin** [comment]
>> It's a totally legit proposition to use our DNS without our VIP implementation.
>
> Sure - kube-proxy starting in "DNS only mode" doesn't seem terribly different to me than its current behavior of "iptables only" though. I agree there is a swiss army knife fear here - but practically speaking I'm going to reimplement something that looks exactly like kube-proxy to do almost exactly what kube proxy does (it responds to IP connections and turns them into proxy endpoints, DNS responds to name requests and turns them into name endpoints).

Again, yeah, I see the relationship, but it's a tradeoff that has not
bee fully worked through - a more complicated and larger kube-proxy vs
smaller and simpler agents.  I'd like to see actual numbers.

> idling
>
> Idling requires an endpoint somewhere that can hold traffic. It also requires clients to know what endpoint that is. That's either a VIP or a real physical port on a machine somewhere. Most proxies are terrible at holding traffic - it's not worth trying to retrofit (read, hack) it into every proxy on the planet. The implementation of an ideal unidler is a proxy component on each node that can easily take incoming traffic, hold it when there are no backends, and then when a backend arrives pass it onwards. The kube-proxy is ideal because when new endpoints appear it creates new iptables rules, which transparently forward new connections on to the new endpoints. The proxy keeps the original connection going until it disconnects, at which point it's not listening anymore.

This is problematic for installations like OpenContrail which don't
transit our iptables rules.  We have to be careful with features that
don't have a plausible story on other installations.

> It's watch traffic (double the watch traffic per node), plus list traffic (double again), plus the memory to hold the state map (65k services x ~1k data). Then there's the DNS cache if using skydns, which is a bit more. Finally, all the garbage collection overhead from maintaining the internal list-watch cache, which is again double than what the node-proxy uses.

Show me the numbers and alternatives.  Having a watch proxy per node
would mitigate all sorts of traffic - why don't we go that far?

**Comment by smarterclayton** [comment]
> This is problematic for installations like OpenContrail which don't transit our iptables rules.  We have to be careful with features that don't have a plausible story on other installations.

Any sort of unidling requires a proxy.  Solutions without proxies can't implement this, but proxies can (just by watching the endpoints list, for example).  I agree to the concern, but I'd say that specific network proxy implementations trade features / benefits all the time.  Different technologies can support different things.  To put it a different way, saying that rocket can't implement a Docker function isn't a reason not to support a rocket container function - most users / admins acknowledge the tradeoff.

> Having a watch proxy per node would mitigate all sorts of traffic - why don't we go that far?

Sure, then we have another API that we maintain between the watch proxy and its consumers.  In the short term, I think both of these features are things that are best dealt with as experimental features.  I guess the challenge seems to be - do you want development of them to happen someplace else so you don't have to review it, or because you don't think they have merit on their own?

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra @kubernetes/rh-networking

**Comment by bgrant0607** [comment]
cc @ghodss

**Comment by freehan** [comment]
reopen if needed
