### ISSUE TITLE
Pluralizing rest resource names in APIs is a mistake

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#18622]
The pluralization of rest resource names in URL paths is mostly human conceit that complicates every interaction from clients and leads to little practical benefit for end users.  In addition, it's an arbitrary transformation that cannot lead to predictable results.

The use of pluralization is entirely historical, and is not based on any pattern other than making readable urls for bookmarking in a web browser.  That is not the same use case as a well constructed API - the set of end users who create urls against our API are extremely limited.  

I believe for v2 versions of our APIs and new API resources we should abandon pluralization in our URL paths.  We can continue to support the old paths as aliases throughout each published API version, but removing the arbitrary process of generating a plurals will allow future api logic to be simpler.

Ie:

/api/v1/namespace/foo/pod/bar/subresource

**Comment by smarterclayton** [comment]
Each *currently* published API version.

**Comment by thockin** [comment]
Is tracking both singular and plural really a hardship?  I agree (and I
think I always did) but I am not sure its with changing at this point.

**Comment by smarterclayton** [comment]
Depends on what you mean by hardship.  It's already leaking into the code
today in RESTMapper (and a few client libraries where someone did the quick
hack).  The end result is Rails [1], which has an awesome library that
includes thousands of arbitrary rules, and you get to add your own
exceptions to those rules, and that never leads to bizarre or weird
behavior.  We'll shield clients from some of this with API discovery (we
have to) - I'd like to just shoot the conceit in the head now.  It would
only be on an API version boundary of course.

I don't think this is much work for us - we have to solve the discovery
problem anyway (at which point URLs become arbitrary for proper clients)
and naive clients can just be told what works.

[1]
http://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html

**Comment by smarterclayton** [comment]
Also, I've seen this
https://github.com/Automattic/mongoose/issues/1703 - there is no end
to the madness when you talk about the English language.

**Comment by thockin** [comment]
Yeah, the implications of auto-pluralization seemed unpleasant to me from
the beginning but I deferred to experience (Joe's and your in particular :)
since I had none in that area.

Does this imply that kubectl commandlines for plurals will not work?
 `kubectl get pod foo` vs `kubectl get pods` is pleasant.

Maybe we just expose multiple names as equivalent URL paths?  Or just
expose it thru discovery?

**Comment by smarterclayton** [comment]
It's one of those common wisdom things that you don't question until
you're 40 resources in.  I agree it's not top on my list, but I'm
starting to hate it.

Regarding aliases: I think discovery has to provide aliases for CLIs.
Otherwise extensions that follow novel English pluralization can't be
registered with the core.  Of course at that point the problem is
hidden from real clients, but we can still make the naive client
easier.

I'll just fold this into general v2 whinging.

**Comment by lavalamp** [comment]
Machine pluralization is hard, we shouldn't do it, we DEFINITELY shouldn't make clients do it. If our discovery is adequate, then it seems like the easiest thing to do is just require pluralized and non-pluralized versions of the word when you register a type.

Harder but better is to stop serving at the pluralized path.

**Comment by smarterclayton** [comment]
We can always serve at both for v1 and drop pluralized for v2.

**Comment by smarterclayton** [comment]
* Once discovery is adequate

**Comment by liggitt** [comment]
The current impl (changed in November, I think) now pluralizes ListOptions as listoptionses, PodLogOptions as podlogoptionses, etc. I'm as big a LotR fan as anyone, but...

**Comment by smarterclayton** [comment]
My.... presccccciiiooouuuussssss.....

**Comment by thockin** [comment]
On Tue, Jan 26, 2016 at 11:48 AM, Clayton Coleman
<notifications@github.com> wrote:
>
> My.... presccccciiiooouuuussssss.....

FTFY: presccccciiiooouuuusssssses

**Comment by bgrant0607** [comment]
Ref #8190

**Comment by bgrant0607** [comment]
I agree that pluralization is annoying as heck.

**Comment by bgrant0607** [comment]
@lavalamp @smarterclayton 

Does the discovery API have enough information to reduce this pain? It returns both the resource name (plural, lowercase) and the kind (singular, CamelCase), correct? Would it work to lowercase(kind)?

I've been wondering whether we should return short aliases (rc, svc) in discovery info, also. (ref #20293)

**Comment by lavalamp** [comment]
I think the discovery API is the canonical place for this info to go. Adding canonical short names at the same time makes sense.

Making people programmatically pluralize English nouns to use our API is sadistic.

**Comment by bgrant0607** [comment]
This is a pain for TPRs:
https://docs.google.com/document/d/1Gg158jO1cRBq-8RrWRAWA2IRF9avscuRaWFmY2Wb6qw/edit#

**Comment by morgs32** [comment]
You guys should make some of this conversation a blog post

**Comment by cben** [comment]
#43312 defined a `singularName` field in discovery APIResourceList.  Unfortunately, it was never implemented, it is always `""`.

**Comment by liggitt** [comment]
> #43312 defined a singularName field in discovery APIResourceList. Unfortunately, it was never implemented, it is always "".

it is populated by CRDs that set [singular names](https://github.com//kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go#L101-L103), and used by kubectl to resolve ambiguous command line requests

**Comment by cben** [comment]
Ouch.  So while client libraries can't rely on it, they SHOULD NOT just ignore it either :-|

Ruby `kubeclient` gem currently take lowecase `kind` vs plural `name` to figure it out.  Are there any known cases where singularName != lowercased kind?

**Comment by vbhakta8** [comment]
So are we leaving them plural?

**Comment by lavalamp** [comment]
Not all mistakes are fixable.

IMO we should close this issue as "won't fix". I don't think there's anything to be done about it now, the benefit of changing this is just too small compared to the user disruption it would cause.

**Comment by thockin** [comment]
Hypothetically, what would we need to make this migration seamless?  Could
etcd or apiserver (hypothetically) do some behind-the-scenes magic to offer
both names?

**Comment by logicalhan** [comment]
This thread is hilarious.

**Comment by dims** [comment]
LOL indeed @logicalhan :)

**Comment by lavalamp** [comment]
> Hypothetically, what would we need to make this migration seamless?

All existing clients have to use the plural form and the singular form in different places. We would have to keep this working approximately forever. That doesn't sound like an improvement to me. Since both paths have to be documented (not just work!) and the documentation has to explain why it is like that, it doesn't even really reduce complexity for users.

**Comment by smarterclayton** [comment]
Yeah, at the time we were considering this we considered "V2" as something we would do.  In the meantime, the cost of API change to the ecosystem has been measured as "really really high".  Even promotion of v1beta1 CRD to v1 has been enormously expensive.  Given that, dramatic changes like this to solve cleanliness issues don't really justify their expense to users (developer time in kube, crd author time, small confusion on pluralization bugs is vastly smaller than the cost to users).

A hypothetical Kube 2, a different API style endpoint that offered meaningful advantages (like a gRPC endpoint that followed gRPC conventions and reduced client creation time, using a different serialization format to allow us to drop gogo-protobuf) might justify such a change, but normal Kube incremental change and stability doesn't in any way justify it.

A future Clayton writing a REST API would never use pluralization of verbs.  But that doesn't impact Kube meaningfully at this point.

**Comment by anguslees** [comment]
Just putting it out there, even if we never remove the 'old' API - there is still a benefit to making a 'new' API available in addition to the old one.

All new client code could remove restmapper and associated complexity, since _new_ code could just go straight to/from  apiVersion+Kind to URL path (assuming we also preserve Kind upper/lower case: /api/v1b/namespace/foo/Pod/bar/subresource).

So I agree it doesn't simplify the server side of things, nor any 'complete' version of the API documentation.  It _does_ make new clients simpler and skip schema-based discovery in a number of cases.  ... So _I_ still think that's an improvement - particularly since the 'duplicated' server-side code and API documentation will be machine generated.
