### ISSUE TITLE
Enable Log size monitoring in scalability test when they become stable again.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18641]
cc @wojtek-t

**Comment by ihmccreery** [comment]
@gmarek (or @wojtek-t) What part of this is test-infra?  What does the test-infra team need to do to enable the performance work to be done?

**Comment by gmarek** [comment]
Well - it's performance test infrastructure, for which we don't have a specific team AFAIK. We're handling this ourselves.

**Comment by gmarek** [comment]
It's done.
