### ISSUE TITLE
PHP on guestbook example is setting its include_path and using short tags.

### ISSUE THREAD

**Issue by carlosrdrz** [kubernetes/kubernetes#18640]
We've found these issues after trying to run the guestbook example with a different set of containers. The issues are located at the file `kubernetes/examples/guestbook/php-redis/guestbook.php`, on the following lines:

```
<?

set_include_path('.:/usr/local/lib/php');
```

Although the Guestbook example works on the container referenced in the example (`gcr.io/google_samples/gb-frontend:v3`), it exposes some bad practices that binds that code to the specific configuration of that particular container. If you try to run the same code with a different configuration, it will fail because of that.

First, it is using PHP short tags, which won't work if the short_tags is disabled on PHP's configuration. It should use `<?php` instead, which is the recommended approach. Some references at http://www.php-fig.org/psr/psr-1/ or http://pear.php.net/manual/en/standards.tags.php

Also, it sets a new `include_path` which binds the code to a specific directory configuration, and it's not required by default. Its default value will point to the PEAR packages directory, so it should be left untouched and everything should continue to work.

**Comment by bgrant0607** [comment]
cc @jeffmendoza @amygdala

**Comment by bshaffer** [comment]
+1

Thanks for providing such good documentation and support for your suggestions!

**Comment by jeffmendoza** [comment]
@carlosrdrz Looks like #21327 was merged, can this be closed?

**Comment by carlosrdrz** [comment]
Yep, looks like it has been solved!
Thanks for working on this :)
