### ISSUE TITLE
The VersionedParams() does not decode the []EnvVar fields properly

### ISSUE THREAD

**Issue by mfojtik** [kubernetes/kubernetes#18649]
It seems like the https://github.com/kubernetes/kubernetes/blob/master/pkg/conversion/queryparams/convert.go#L62 function is currently handling only Go primitive types, so when having a field in a type like this:

``` go
struct Foo {
  env []EnvVar
}
```

This field will get no value set as the converter don't know how to convert it to QueryParams.
Additionally, this reveals a bigger problem, when having struct like above, to retain the ordering of fields, there is no indexing being done in that function. I would want to have something like this in POST params:

```
/foo?env.0.name=FOO&env.0.value=BAR
```

That said, the `DecodeParametersInto()` will have to be smarter when parsing the fields. Also it would be nice to add self-identification of the fields (to which struct they belongs).

**Comment by mfojtik** [comment]
@deads2k @smarterclayton @kargakis FYI

**Comment by mfojtik** [comment]
My first attempt to fix the query params converter: https://github.com/kubernetes/kubernetes/pull/18650

(still pending decoding part)

**Comment by kargakis** [comment]
> (still pending decoding part)

Good luck with that:)

**Comment by lavalamp** [comment]
Is this blocking anything we actually want to send over the query params?

**Comment by smarterclayton** [comment]
We had several use cases in OpenShift but for now just punted.  I'm
hesitant to define a query param syntax without defining field selectors.
