### ISSUE TITLE
Have a question about what the procedure to add features.

### ISSUE THREAD

**Issue by Hui-Zhi** [kubernetes/kubernetes#18644]
I appreciate if you can let me know about the procedure of add features.
I have read the development guide which at below link:
https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/devel/development.md

But I still have a question, if someone want to add some features, will you assigned own to them? Or anyone could take the own of any issues? Thanks for your answer in advance.

**Comment by thockin** [comment]
If you want to add a feature which you intend to develop, the usual process
is to file an issue describing the use-cases you need to handle and how you
propose to solve them, including possible alternatives and trade-offs.

**Comment by saad-ali** [comment]
Please use Slack for questions like this (see https://github.com/kubernetes/kubernetes/wiki/Slack-Team-Information).
