### ISSUE TITLE
e2e flake: Kubernetes e2e suite.SchedulerPredicates validates MaxPods limit number of pods that are allowed to run

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18647]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/1137/

**Comment by fgrzadkowski** [comment]
The same happened today:
```
SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:262 Expected <[]api.Event | len:0, cap:0>: [] not to be empty
```
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9991/

**Comment by fgrzadkowski** [comment]
False alarm. Failure I've listed has a different root cause.

**Comment by gmarek** [comment]
I haven't seen this in last ~100 runs. Closing.
