### ISSUE TITLE
Change HPA example to generate load from inside the cluster

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#18654]
In the current state to generate load the user should invoke from his/her computer `while true; do curl http://146.148.6.244; done`. It can be easily done from pod running in the cluster. This issue is about to change the [HPA example](https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/horizontal-pod-autoscaling) accordingly.

cc @jszczepkowski

**Comment by jayunit100** [comment]
Not a bad idea, but then, won't the interactive nature of the example be lost?
We are doing automatic thrusting of CPU in the e2es if the goal is just to automate hpa pod fluctuating...
