### ISSUE TITLE
Idea for an up to date documentation validator

### ISSUE THREAD

**Issue by stvnwrgs** [kubernetes/kubernetes#18659]
If you try to create a kubernetes example from the docs the chance is quite big that you get an outdated yml/json definition in the .md files or the example files. This results in searching another newer example which might lead to another outdated version. This results into looking into the code. I think many people just quit here. Especially when it happens more then once.

Idea:

Add an additional test that finds every .md and .yml .json file in the repository.
Then check if there is formated code ( if it's an .md file)

Search for keywords like 

```
apiVersion: "v1"
  kind: 
```

Check if the Code could be read from the kubectl parser.
If not, build fails. This would increase the maintenance costs, but would lead to a better general documentation for each new version.

**Comment by thockin** [comment]
I swear we have or had such a test, but I can't find it...

@krousey was that one of yours?

**Comment by krousey** [comment]
@thockin not mine. I think @janetkuo was working on something like that, but I don't know if it ever happened.

**Comment by feihujiang** [comment]
@thockin Maybe this [examples_test.go](https://github.com/kubernetes/kubernetes/blob/master/examples/examples_test.go) one. It reads json/yaml files from ../docs and ../example directories, then validates them.

**Comment by bgrant0607** [comment]
Related: #8341

cc @caesarxuchao

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
We have a [verify-docs-format.sh](https://github.com/kubernetes/kubernetes.github.io/blob/e2a898ad4139729834ad3f139b9063601d3f2a92/verify-docs-format.sh) that does YAML Markdown validation today. Feel free to submit PRs to the docs repo if you see ways to improve it.

/close
