### ISSUE TITLE
Upgrades on GKE from 1.0 to master time out

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18660]
**Cluster Upgrade [Skipped] upgrade-master should maintain responsive services**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:197 Dec 14 02:48:44.092: Failed to create 2 pods with name webserver: failed to wait for pods responding: timed out waiting for the condition

---

1.0 to 1.1, 1.1 to master all work fine.

**Comment by ihmccreery** [comment]
Similarly:

**Cluster Upgrade [Skipped] upgrade-cluster should maintain a functioning cluster**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:197 Dec 14 03:53:41.270: Failed to create 2 pods with name webserver: failed to wait for pods responding: timed out waiting for the condition

**Comment by ihmccreery** [comment]
Indeed, it looks like the master isn't getting bumped at all; on the following step, running 1.0 e2es, I still see:

```
02:55:41 Server Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.8-beta.65+8218bcbb79b5d4", GitCommit:"8218bcbb79b5d444082ce04137f2bf71056acc57", GitTreeState:"clean"}
```

Googlers can see results at:

- master upgrades: http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.0-master-step3-upgrade-master/
- cluster upgrades: http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.0-master-step5-upgrade-cluster/

**Comment by ihmccreery** [comment]
Looks like this is a precondition failure:

```
02:44:30 [BeforeEach] Cluster Upgrade [Skipped]
[...]
02:44:40 STEP: trying to dial each unique pod
02:45:10 Dec 14 02:45:10.057: INFO: Controller webserver: Failed to GET from replica 1 [webserver-482bf]: an error on the server has prevented the request from succeeding (get pods webserver-482bf):
02:45:40 Dec 14 02:45:40.062: INFO: Controller webserver: Failed to GET from replica 2 [webserver-81y17]: an error on the server has prevented the request from succeeding (get pods webserver-81y17):
02:46:12 Dec 14 02:46:12.071: INFO: Controller webserver: Failed to GET from replica 1 [webserver-482bf]: an error on the server has prevented the request from succeeding (get pods webserver-482bf):
02:46:42 Dec 14 02:46:42.076: INFO: Controller webserver: Failed to GET from replica 2 [webserver-81y17]: an error on the server has prevented the request from succeeding (get pods webserver-81y17):
02:47:14 Dec 14 02:47:14.071: INFO: Controller webserver: Failed to GET from replica 1 [webserver-482bf]: an error on the server has prevented the request from succeeding (get pods webserver-482bf):
02:47:44 Dec 14 02:47:44.076: INFO: Controller webserver: Failed to GET from replica 2 [webserver-81y17]: an error on the server has prevented the request from succeeding (get pods webserver-81y17):
02:48:14 Dec 14 02:48:14.085: INFO: Controller webserver: Failed to GET from replica 1 [webserver-482bf]: an error on the server has prevented the request from succeeding (get pods webserver-482bf):
02:48:44 Dec 14 02:48:44.091: INFO: Controller webserver: Failed to GET from replica 2 [webserver-81y17]: an error on the server has prevented the request from succeeding (get pods webserver-81y17):
[...]
02:48:45 • Failure in Spec Setup (BeforeEach) [255.552 seconds]
02:48:45 Cluster Upgrade [Skipped]
02:48:45 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:288
02:48:45   upgrade-master [BeforeEach]
02:48:45   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:232
02:48:45     should maintain responsive services
02:48:45     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:231
02:48:45 
02:48:45     Dec 14 02:48:44.092: Failed to create 2 pods with name webserver: failed to wait for pods responding: timed out waiting for the condition
02:48:45 
02:48:45     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1430
02:48:45 ------------------------------
```

**Comment by ihmccreery** [comment]
This seems like it may be related to https://github.com/kubernetes/kubernetes/issues/18581#issuecomment-164535146; subresource proxy is known broken in 1.0, and so the upgrade logic (in the e2es) can't validate that the cluster is functioning before doing the upgrade.

**Comment by ihmccreery** [comment]
Similar to https://github.com/kubernetes/kubernetes/issues/18581#issuecomment-164051905, it looks like [checkAllResponses](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/util.go#L883) is failing due to subresource proxy issues.  Confirmed that removing the `podsResponding` check in `verifyPods` allows upgrades to proceed.

**Comment by ihmccreery** [comment]
@cjcullen @liggitt Any ideas for how to contact unique pods without relying on `pods/proxy`?

**Comment by ihmccreery** [comment]
(We'll probably need to version-guard it, similar to https://github.com/kubernetes/kubernetes/pull/17416.)

**Comment by liggitt** [comment]
/proxy/namespaces/ns/pods/pod works, but that will break for namespace locked users

pods/proxy works for non-ssh-tunnel servers. GKE is in the minority of servers for using that setup.

**Comment by liggitt** [comment]
I would also only want to version guard the subresource proxy test if anything, leaving the root proxy tests as they were in 1.0
