### ISSUE TITLE
Set up email list for release announcements

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18662]
Per @roberthbailey's comment on #18598, we should set up some kind of mailing list so people outside of Google can get draft release notes.  @sarahnovotny, is this something you can take on?

**Comment by ihmccreery** [comment]
cc @jbeda @countspongebob

**Comment by jbeda** [comment]
We have [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce) we can use for that.  We probably need to do a better job of making folks aware of that.

Joe

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by spzala** [comment]
@ihmccreery @sarahnovotny hi, I believe this may not be an issue any more and we can close it? I see kubernetes-announce  is up to date and I guess email notification in place as well? Just a gentle touch base towards efforts on closing open issues as possible. Thanks!
