### ISSUE TITLE
kubectl create secret generic --type validate from known list of types by default

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#18663]
The `kubectl create secret generic` command let's a user specify a type for the secret.  It defaults to `opaque`.  

The kube server supports a set of known secret types with specific behaviors.  The client could support checking that the user specified secret type is one of the known types that are specified in `kubernetes` by default, and if it is not, require the client to pass a ``--confirm` flag to ack that they were not just making a typo.
- Pros
  - makes user less prone to fat fingering the type
- Cons
  - third-parties may define new types of secrets so central management of names may not be desirable

**Comment by elsonrodriguez** [comment]
@jsafrane @saad-ali @liggitt This related to https://github.com/kubernetes/kubernetes/pull/35675

kubectl no longer has the ability to create the types of secrets required by storage provisioners.

**Comment by liggitt** [comment]
what do you mean? as far as I can tell, it can create any type of secret:
```
$ kubectl create secret generic mysecret --type=kubernetes.io/bar --from-literal username=bob --from-literal password=s3cret
secret "mysecret" created

$ kubectl get secret mysecret -o yaml
apiVersion: v1
data:
  password: czNjcmV0
  username: Ym9i
kind: Secret
metadata:
  creationTimestamp: 2016-11-30T22:22:52Z
  name: mysecret
  namespace: test
  resourceVersion: "6479"
  selfLink: /api/v1/namespaces/test/secrets/mysecret
  uid: 88a72dc5-b74b-11e6-953e-acbc32c1ca87
type: kubernetes.io/bar
```

**Comment by elsonrodriguez** [comment]
Sorry, I was trying to specify `kubectl create secret <type>` instead of `--type=<type>`

I wasn't able to do a `kubectl edit` and change the type field so I let myself get thrown off.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc
