### ISSUE TITLE
Need a better way to specify plugin/extender specific arguments in the pod spec

### ISSUE THREAD

**Issue by ravigadde** [kubernetes/kubernetes#18670]
Annotations are map[string]string. Its difficult to encode arbitrary structure in to a string.

```json
{
 "kind": "Pod",
 "apiVersion": "v1",
 "metadata": {
  "name": "testpod",
  "namespace": "default",
  "annotations": {
     "test": {
	   "name": "foo",
	   "value": "bar"
     }
   }
 },
...
```
[root@tb1-01 ~]# kubectl create -f pod.json
unable to load "pod.json": json: cannot unmarshal object into Go value of type string

This works but its painful to escape every quote and fit all of it in a single line.
```json
 "annotations": {
     "test": "{\"name\": \"foo\", \"value\": \"bar\"}"
   }
```

map[string]interface{} makes it easier. The structure gets parsed as a map. The plugin would encode this map and then decode in to the structure. This scheme allows multiple plugins to define their own custom arguments.

There are two options to implement this:
1) Define a new field in the pod spec that is map[string]interface{}
2) Change the definition of Annotations and add conversion functions for existing annotations.

If there is a different way to handle this, please let me know.

cc @bgrant0607 @smarterclayton @davidopp @thockin

**Comment by ravigadde** [comment]
cc @brendandburns @nelcy

**Comment by jainvipin** [comment]
Useful feature to have.
@ravigadde - I use out of band mechanism to avoid this issue...

**Comment by ravigadde** [comment]
@jainvipin The goal is to use the standard interface for pod creation, which can be accomplished by providing flexibility in the pod spec.

**Comment by davidopp** [comment]
@smarterclayton @thockin have some input on this

**Comment by bgrant0607** [comment]
See also #12226

**Comment by thockin** [comment]
Dup of #12226
