### ISSUE TITLE
It's impossible to make a resource that is both cluster-scoped and namespace-scoped

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#18679]
A fully qualified kind (`GroupVersionKind`) maps to at most one `RESTMapping`.  A `RESTMapping` has exactly one `RESTScope`.  https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta/interfaces.go#L153 and https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta/interfaces.go#L132.

This causes problems when you want to have a single kind that is both cluster-scoped and namespace-scoped.  OpenShift faced this problem with `Roles`.  We wanted a single Kind that would be accessible at both scopes.  It failed because:
1. The `RESTMapper.RESTMapping` call had an ambiguous return.
2. namespace=`""` in a serialized object sometimes means "no namespace", sometimes means "default", sometimes means "current-namespace", and sometimes means "cluster-scoped".  (I can also mean "all namespaces" depending on where in the codebase you are).
3. `ObjectReferences` are hard to reason about because in most cases, namespace="" means "current namespace", but if a given resource can be at both scopes the meaning is ambiguous.

For a while we tried to have a "special" namespace that had resources which affected all namespaces.  This was a disaster.  It was extremely difficult to explain in documentation, caused special casing code to multiply to handle the magic namespace, and meant that granting power to maintain that one resource propogated power everywhere.

We ended up creating two separate Kinds that shared the same fields.  See `Role` https://github.com/openshift/origin/blob/master/pkg/authorization/api/types.go#L144 and `ClusterRole` https://github.com/openshift/origin/blob/master/pkg/authorization/api/types.go#L311.  Code that makes use of these resources and doesn't need to distinguish can manage getters via a common interface: https://github.com/openshift/origin/blob/master/pkg/authorization/interfaces/interfaces.go#L25-L30.

Conversion between cluster-scoped kinds and namespace-scope kinds turned out to be fraught because rules around `ObjectReferences` became difficult to explain.

**Comment by smarterclayton** [comment]
Clients use the RESTMapping to know what rules to impose and what defaults to apply to client actions - for instance - is the `--namespace` flag allowed to be empty when talking to a resource?  Check the scope.  Is --all-namespaces allowed?  Check the scope.  Should we ignore the default namespace (set via the config) when creating a new object on the server?  Check the scope.

**Comment by smarterclayton** [comment]
We should summarize this as:

1. Don't try to have a resource in both a cluster and namespace scope now
2. If we create new scopes, reevaluate (@quinton-hoole is considering a cross-cluster scope that spans instances)
3. If we fixed the internal NamespaceDefault == NamespaceAll, or removed namespace defaulting from the internal code in both client and server (but not the api), it would be less fraught
4. ObjectReferences might need a new field anyway - cluster, to identify their scope, and it may be that ObjectReferences need to be reassessed in light of all of our recent design points that have revolved around them

**Comment by quinton-hoole** [comment]
@smarterclayton I'm not a K8s namespace expert, but I have to agree with @deads2k that having multiple non-hierarchical, possibly overlapping namespaces is both cognitively challenging and fraught with implementation peril as exhibited by @deads2k's code examples. 

As you and I discussed briefly a few months back, is it not worth seriously considering moving towards hierarchical namespaces (possibly with both relative and absolute naming semantics)?  Think traditional filesystem semantics. This approach would seem to solve all of the problems highlighted in this issue rather elegantly?

**Comment by quinton-hoole** [comment]
@bgrant0607 FYI as I seem to recall that he has strong opinions on this matter :-)

**Comment by smarterclayton** [comment]
I think of traditional filesystem and all I see are POSIX :)  I certainly
agree that overlapping is challenging - will have to reflect more on
hierarchy (haven't thought about it recently).  The biggest use case is for
generic ownership / authz / quota enforcement with levels.  The downside is
that everything that has to deal with those has to understand hierarchy.

**Comment by quinton-hoole** [comment]
cc @etune also FYI.  He has opinions :-)

**Comment by quinton-hoole** [comment]
@smarterclayton Are you implying that POSIX filesystem namespace semantics are bad in some way?  If so, please elaborate.

**Comment by lavalamp** [comment]
Is there any action items for this? Is the point of this issue to debate whether it should be possible to make types of scope "both"?

**Comment by deads2k** [comment]
> Is there any action items for this? Is the point of this issue to debate whether it should be possible to make types of scope "both"?

Yes.  It was to demonstrate the need and to demonstrate a workaround that doesn't involve a "special" namespace.

I would like to be able to create a resource that is both cluster-scoped and namespace-scoped.  I think that it is reasonably achievable and that a first step would be narrowing the meaning of `namespace=""`

**Comment by derekwaynecarr** [comment]
Long ago, when I was looking at this problem, I had evaluated moving namespace out of `ObjectMeta` and instead have objects that belonged to a namespace embed `NamespaceMeta`.  Does that help?

**Comment by derekwaynecarr** [comment]
Never mind, I see that you want to have it both ways.
