### ISSUE TITLE
Parallelize starting/stopping multiple MIGs in kube-up script

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18699]
We should parallelize starting/stopping multiple MIGs in kube-up scripts in GCE to make large clusters starting/stopping faster.

**Comment by gmarek** [comment]
I think we did that to the extend it's safe.

**Comment by wojtek-t** [comment]
This isn't done:
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L1362

That said, I'm not sure if it's worth doing...
