### ISSUE TITLE
Data race pkg/storage

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18701]
There are 3 tests failing with the following data-race in Go 1.5:

    Write by goroutine 65:
      github.com/coreos/go-etcd/etcd.(*Client).Close()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go:188 +0x4a
      k8s.io/kubernetes/pkg/storage/etcd/testing.(*EtcdTestServer).Terminate()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/storage/etcd/testing/utils.go:129 +0x6c
      k8s.io/kubernetes/pkg/registry/generic/etcd.TestEtcdWatch()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd_test.go:508 +0xb5f
      testing.tRunner()
          /tmp/workdir/go/src/testing/testing.go:456 +0xdc

    Previous read by goroutine 54:
      net/http.(*persistConn).roundTrip()
          /tmp/workdir/go/src/net/http/transport.go:1146 +0x548
      net/http.(*Transport).RoundTrip()
          /tmp/workdir/go/src/net/http/transport.go:235 +0x6b3
      net/http.send()
          /tmp/workdir/go/src/net/http/client.go:220 +0x73d
      net/http.(*Client).send()
          /tmp/workdir/go/src/net/http/client.go:143 +0x1f7
      net/http.(*Client).doFollowingRedirects()
          /tmp/workdir/go/src/net/http/client.go:380 +0x1059
      net/http.(*Client).Do()
          /tmp/workdir/go/src/net/http/client.go:175 +0xc1
      github.com/coreos/go-etcd/etcd.(*Client).SendRequest()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go:238 +0x1442
      github.com/coreos/go-etcd/etcd.(*Client).getCancelable()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go:51 +0x4af
      github.com/coreos/go-etcd/etcd.(*Client).watchOnce()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/watch.go:96 +0x270
      github.com/coreos/go-etcd/etcd.(*Client).Watch()
          /workspace/kubernetes/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/watch.go:39 +0x3b5
      k8s.io/kubernetes/pkg/storage/etcd.(*etcdWatcher).etcdWatch()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_watcher.go:150 +0x247

The failing tests are:
- pkg/registry/generic/etcd
- pkg/storage
- pkg/storage/etcd

@timothysc @xiang90 

This is blocking upgrade to Go 1.5

**Comment by wojtek-t** [comment]
@hongchaodeng

**Comment by wojtek-t** [comment]
It seems like an issue in go-etcd.

Maybe submitting #18635 will solve the problem.
@timothysc - WDYT?

**Comment by timothysc** [comment]
@wojtek-t , let get that spruced up today and we'll find out.

**Comment by wojtek-t** [comment]
I've run it few times, and it seems that #18635 is indeed solving this issue (there seem to be another one, which I'm looking into right now).
However, for this one, we are waiting for #18635 to be merged.

**Comment by wojtek-t** [comment]
Seems to be fixed by #18635
