### ISSUE TITLE
DNS AddOn Release

### ISSUE THREAD

**Issue by stevesloka** [kubernetes/kubernetes#18705]
The kube2sky piece of the dns add-on is using version 1.11 (https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in#L43) but there aren't any release notes on it (https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kube2sky/Changelog). I built a new cluster and wanted to use pod dns, but it didn't work (had been using custom build since I sent the PR over for pod dns). Did the pod dns piece make it into 1.11 or does a new version need to be created? Also, the release notes stop at 1.10, would be nice to update. 

//cc @thockin

**Comment by ArtfulCoder** [comment]
I will create a new version today.

**Comment by stevesloka** [comment]
Awesome thanks!
