### ISSUE TITLE
Compartmentalize secrets between service accounts

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#18725]
A key use case for service accounts is compartmentalization of secrets.

In other words:

> As a user, I can create serviceAccounts/A, whose pods have access to secrets/A, but not secrets/B; and serviceAccount/B whose pods can access secrets/B but not secretsA.

A specific use case raised by a Kubernetes user was:

> The e-commerce pods can access Stripe API keys, but the email-sending pods can't.

These use cases as possible, but currently hard to get right

---

The way you could do the second use case currently is:
1. create secret "stripekey" with the Stripe API keys.
2. create Kubernetes Service Account called "ecommerce".
3. Add a reference from "serviceAccounts/ecommerce" to "secrets/stripekey".
4. create Kubernetes Service Account called "email".
5. create e-commerce pods/rcs with .spec.serviceAccount=ecommerce.  Mount the stripe secret in the pod.
6. create email pods/rcs with .spec.serviceAccount=email. 
7. ensure that pods with serviceAccount=email cannot GET  "secrets/stripekey".

Actions needed
- [ ]  This entire procedure needs to be well documented.  (e.g. in docs/user-guide/service-accounts.md).
- [ ] There needs to be e2e testing which ensures compartmentalization of secrets. 
- [ ] step 7 above needs to be easier, preferably happening by default rather than requiring action.

Step 7 deserves more detail:

Currently, a newly created service account has `root`-like API permissions.   There are two ways to reduce these permissions:

The first is to block the service account from accessing the API entirely.  Ways to do this are discussed in #16779.  The current way is a hack.  You have to put a certain `volumeMount` on each container in each pod of that service account, which in turn blocks the service account token from being mounted.  Issue #16779 suggest the alternative of having a flag on each service account that blocks creation of an API token entirely.  

The second is to edit the authorization config for each service account.  Currently, only "ABAC" authorization is supported, and requires manually editing a file read by the apiserver.  This doesn't work at all on GKE.

Both of these options requires specific action from the user to get the behavior they most likely want.  We should look at changing the defaults.  For example, we could change the default when creating a new service account to not have an API token.

**Comment by erictune** [comment]
I think the state we want to get to is this:

1. for each authorization plugin that we support, there needs to be some kind of default policy that applies to service accounts which:
  1. doesn't allow it blanket read access to secrets
  2. doesn't allow it access to other namespaces
2. when you add a secret to a service account,
3. on some systems (e.g. OpenShift), adding a secret to the service account could automatically update the policy (?).  On other systems this could be a manual step.  If it is manual, then service account controller and/or kubectl could still warn you if the serviceAccount is not allowed to access the secret (e.g. using SubjectAccessReview, from #12209).
4.  kubelet should act as the serviceAccount when pulling the secret, so it does not accidently become a confused deputy, to clarify audit logs, etc.

**Comment by erictune** [comment]
@kubernetes/sig-auth

**Comment by deads2k** [comment]
How close are we once we enable `LimitSecretReferences` in the admission controller: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/serviceaccount/admission.go#L67 ?

I didn't think we were expecting that an SA would directly have access to any part of the API to subdivide secrets.  Instead, the SA has a list of MountableSecrets (now called `Secrets`).  When a Pod is created, its SecretVolumes are checked for mountability by the SA.

This works today and it might cover your use-case, but in OpenShift we found that it was very painful to use as a default.

**Comment by erictune** [comment]
What in openshift, stops a pod with service account A from contacting the kubernetes API, after it started, and getting a secret that exists in its namespace, but which is not on its Secrets list?

**Comment by liggitt** [comment]
service accounts don't have GET access to secrets by default

**Comment by liggitt** [comment]
I think this is broader than just pods. The ability to give access to a subset of secrets across namespaces is valuable. Use cases:

* ingress controller should only be able to get the secret containing the referenced serving cert/key for all the Ingress objects it is responsible for
* volume provisioner should only be able to get secrets intended for it

of the API mechanisms we currently have for querying items (by namespace, by namespace+name, by label selector, by field selector), only namespace and name interact with authorization

**Comment by liggitt** [comment]
c.f. https://github.com/kubernetes/kubernetes/issues/40403
