### ISSUE TITLE
Clean up versioning structs

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18726]
Right now the `version` package contains three redundant version objects:
- `Info` struct,
- `GitVersion` struct, inside of the `Info` struct,
- `semver.Version`, from [github.com/blang/semver](https://github.com/blang/semver).

We should clean this up, along with the stuff in `version/base.go`, and make it easier to deal with and less redundant.

This came up in working on version guards for https://github.com/kubernetes/kubernetes/issues/18720.

**Comment by ihmccreery** [comment]
This should probably encompass #16815.

**Comment by ihmccreery** [comment]
This work might also include adding structures around the client `VersionInterface` to allow easy version guarding.

**Comment by ihmccreery** [comment]
We should consider just doing away with coded version structs entirely, and rely only on `git tags` for versioning.

That means we wouldn't be able to build versioned releases from a repo coming from a tar, but I have no strong aversion to that.  Checking out the repo should be the canonical way to do this anyway.

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc
