### ISSUE TITLE
Ability to pass cadvisor args to mesos executor?

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#18723]
In contrib/mesos/pkg/minion/server.go there is a function named launchExecutorServer, which launches the executor.  The flags for kubelet are allowed there, but not the flags for cadvisor.  But the executor runs both, right?

**Comment by MikeSpreitzer** [comment]
How do we make progress on this?

**Comment by vishh** [comment]
cc @kubernetes/kube-mesos

**Comment by jdef** [comment]
we don't have a great solution for flag pass-through. so instead we've hand-selected some flags to pass through that seemed important for us at the time. we've been looking forward to factoring out some of the flag stuff in favor of persistent config, but i don't think that's materialized yet.

which specific flags would you like support for?

**Comment by MikeSpreitzer** [comment]
The two of immediate interest are --housekeeping_interval and --global_housekeeping_interval

**Comment by linsun** [comment]
I am also interested in exposing the two params Mike described.   Q:  Can I pass them as part of scheduler-config similar as how we pass "--cadvisor-port" value to the executor (e.g. from Scheduler Config and adding them to ci.Arguments (in scheduler service.go)?  Thanks?

**Comment by jdef** [comment]
Yes, passing them using a similar code path is fine. Heads up: Tim St.
Clair has indicated that these flags may change down the road (they may not
even be exposed by the kubelet at somepoint).

**Comment by MikeSpreitzer** [comment]
I have drafted a fix, see https://github.com/MikeSpreitzer/kubernetes/tree/issue/18723
Does that look right?

**Comment by linsun** [comment]
@jdef @MikeSpreitzer:  I have reworked the patch based on the excellent feedback from Jeff on Mike's patch.   [https://github.com/linsun/kubernetes/commit/ce1e2f0694d753ef92fa34880322dc1cf8bc8cc0]  Let me know any comments you may have.

I'm also interested in any existing testing automation that I can extend.  Else, I can manually test it tmr.  Thanks!

**Comment by linsun** [comment]
@jdef thanks for your 2nd review.  I've reworked and posted here:  https://github.com/kubernetes/kubernetes/pull/20331/commits

I had thought the other change was not needed since I don't see that file (minion/server.go) handles the cadvisorPort so I hadn't thought of passing it explicitly in the file.

**Comment by k82cn** [comment]
The patches are merged. @jdef , would you help to close this one?

**Comment by jdef** [comment]
fixed by #22974
