### ISSUE TITLE
Add version-guard logic to tests, etc. for pods/proxy path broken in 1.0 in GKE

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18720]
#17002 introduced a backwards-incompatibility to our tests and other logic with some 1.0 masters, whose [subresource proxies were broken](https://github.com/kubernetes/kubernetes/pull/15224#issuecomment-146769463).  We should version-guard this logic to use subresource proxies for 1.1 and above, and root proxy for 1.0 and below.

This is blocking https://github.com/kubernetes/kubernetes/issues/18581 and https://github.com/kubernetes/kubernetes/issues/18660.

cc @smarterclayton @cjcullen

**Comment by feihujiang** [comment]
I'm a little confused, just ask some questions. The 1.0 release version doesn't have relevant e2e tests?Why e2e tests should backwards-compatibility, for example, if we add a new function for v1.1, and add a relevant e2e test for v1.1, how the e2e test could pass for v1.0?

**Comment by liggitt** [comment]
disagree... pods/proxy subresource is preferred, even for 1.0

**Comment by ihmccreery** [comment]
@feihujiang The e2e tests need to be backwards-compatible so that we can test upgrades and version-skewed cluster between 1.0 and master.  In order to do so, we want to make sure that pods created before an upgrade continue to function during and after an upgrade.  We have to run tests at some version, and we've decided that the appropriate version to run them at is the higher version.  (This makes more sense than asking tests to be "forward-compatible".)

> for example, if we add a new function for v1.1, and add a relevant e2e test for v1.1, how the e2e test could pass for v1.0?

Good question; we don't expect it to, unless it's a `kubectl` test, (or some subset, see #18581).  Thus what was proposed in #17416.  I can't say I love that solution, but that's where we're moving toward.  We need some signal to verify that the `kubectl` we ship with v1.2 will continue to work against a 1.0 cluster.

@liggitt An alternative might be that I could version-and-provider-guard the logic?  Would that be preferable?

**Comment by feihujiang** [comment]
@ihmccreery I understood, thanks for your detailed information.

**Comment by ihmccreery** [comment]
Closed #18720 via #18773.
