### ISSUE TITLE
[e2e failure] Kubelet regular resource usage tracking for 40 pods per node over 20m0s

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#18739]
This started failing this week on [kubernetes-soak-continuous-e2e-gke](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gke/).

The failure is
```
Kubelet regular resource usage tracking for 40 pods per node over 20m0s

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:182 Expected error: <*errors.errorString | 0xc208247c50>: { s: "Only 111 pods started out of 120", } Only 111 pods started out of 120 not to have occurred
```

@yujuhong, can you take a look? From the logs it looks like 9 out of 120 never get scheduled, which makes me think there isn't enough room on the machine. AFAICT, both this cluster and the one for [kubernetes-soak-continuous-e2e-gce](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gce/) are the same size (3 nodes, n1-standard-2), so I can't tell why it's failing on this but not the other. I'll try to catch it next run and post output of `kubectl describe`

**Comment by yujuhong** [comment]
It's my bad. I bumped the test from 35 to 40 pods per node, but the default --max-pods in kubelet is 40. For a GCE test cluster, we set the flag to >100. I will bump the default max pods in kubelet.

**Comment by jlowdermilk** [comment]
I relaunched the soak cluster with change and test is now passing again. Thanks @yujuhong.
