### ISSUE TITLE
Write proposal on how to self host the kubernetes control-plane

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#18735]
ref #246, #473

**Comment by polvi** [comment]
I heard there was recently a demo of some approaches at this during a community meeting. Are there any notes for that?

**Comment by bgrant0607** [comment]
Also requires #489

**Comment by mikedanese** [comment]
https://github.com/kubernetes/kubernetes/issues/246#issuecomment-64533959

**Comment by philips** [comment]
@mikedanese I put this doc together, does it help? https://docs.google.com/document/d/1VNp4CMjPPHevh2_JQGMl-hpz9JSLq3s7HlI87CTjl-8/edit?usp=sharing
