### ISSUE TITLE
Convince ourselves that two schedulers scheduling the same pod "at the same time" works

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#18745]
e.g. doesn't break queuedPods, assumedPods, or scheduledPods.

ref/ #17865

**Comment by davidopp** [comment]
@hongchaodeng @HaiyangDING

**Comment by davidopp** [comment]
@HaiyangDING said he would look into this. I think it's sufficient to just try to understand the code and convince that it works (or if it does not work, how to fix it).

I think @bprashanth may be familiar with this code, if you have questions.

**Comment by timothysc** [comment]
This can/should be an e2e test.
