### ISSUE TITLE
Wrong --to-destination determined // util.go uses gateway IP instead of real IP?

### ISSUE THREAD

**Issue by wfrank2509** [kubernetes/kubernetes#18753]
Hello,

I stumbled over this issue during installing openshift which is based on kubernetes. The problem is that the --to-destination points to the GATEWAY address of my network instead of the host IP. Therefore the nodes are not reachable.

E.g. 

```
-A KUBE-PORTALS-HOST -d 172.30.0.1/32 -p tcp -m comment --comment "default/kubernetes:https" -m tcp --dport 443 -j DNAT --to-destination **176.x.x.225:33790**
```

It looks like that in  /pkg/util/util.go  the wrong IP is determines.

> > route -v -n

```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         **176.x.x.225**     0.0.0.0         UG    0      0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 ethic
**176.x.x.225**     0.0.0.0         255.255.255.255 UH    0      0        0 ethic
```

where **176.x.x.225** is the Gateway that is used.

My real IP is;

> > ifconfig 
> > 
> > ```
> > eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
> >         inet **176.x.x.251**  netmask 255.255.255.255  broadcast 176.x.x.251
> >         inet6 2a01:4f8:x:51x::2  prefixlen 64  scopeid 0x0<global>
> >         inet6 fe80::5246:x:fe4d:2101  prefixlen 64  scopeid 0x20<link>
> >         ether 50:46:x:4d:x:01  txqueuelen 1000  (Ethernet)
> >         RX packets 10837  bytes 1025499 (1001.4 KiB)
> >         RX errors 0  dropped 1806  overruns 0  frame 0
> >         TX packets 8088  bytes 1568198 (1.4 MiB)
> >         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> > ```

The gateway needs to be configured as SCOPE peer 176.x.x.225 in the sysconfig/network/ifcfg-eth0 for my hoster (Hetzner).

Is there a way to override the IP to be used or can someone give me a hint if that is the right place for a fix in the util.go?

Thank you,
Wolfgang

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc
