### ISSUE TITLE
kubectl create behaves different with url on multi document yaml

### ISSUE THREAD

**Issue by maklemenz** [kubernetes/kubernetes#18751]
Using an url, kubectl creates only the first thing in a multi document yaml file:

	[root@master]# kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/examples/guestbook/all-in-one/guestbook-all-in-one.yaml
	service "redis-master" created
    [root@master]# kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/examples/guestbook/all-in-one/guestbook-all-in-one.yaml
    Error from server: error when creating     "https://raw.githubusercontent.com/kubernetes/kubernetes/master/examples/guestbook/all-in-one/guestbook-all-in-one.yaml": services "redis-master" already exists

But using the file all components in the file get handled:

	curl https://raw.githubusercontent.com/kubernetes/kubernetes/master/examples/guestbook/all-in-one/guestbook-all-in-one.yaml > guestbook-all-in-one.yaml
	[root@master]# kubectl delete -f guestbook-all-in-one.yaml
	service "redis-master" deleted
	Error from server: error when stopping "guestbook-all-in-one.yaml": replicationControllers "redis-master" not found
	Error from server: error when stopping "guestbook-all-in-one.yaml": services "redis-slave" not found
	Error from server: error when stopping "guestbook-all-in-one.yaml": replicationControllers "redis-slave" not found
	Error from server: error when stopping "guestbook-all-in-one.yaml": services "frontend" not found
	Error from server: error when stopping "guestbook-all-in-one.yaml": replicationControllers "frontend" not found

	[root@master]# kubectl create -f asd
	service "redis-master" created
	replicationcontroller "redis-master" created
	service "redis-slave" created
	replicationcontroller "redis-slave" created
	service "frontend" created

	[root@master]# kubectl version
	Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}
	Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}

This seems to be very inconsistent and unintended. A bug?

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by bgrant0607** [comment]
Looks like we need a test for this, also.

**Comment by bgrant0607** [comment]
@ethernetdan: Would you be interested in taking a look at this issue?

**Comment by aveshagarwal** [comment]
If nobody is looking into it, I would be happy to work on it.
