### ISSUE TITLE
Creating a new API group is really hard

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#18762]
Creating a new API group is really hard.  I'll keep this description up to date as I go through the pain.
1. You have to know to add yourself to the `import_known_versions.go` files in multiple packages to get included.
2. You have to manually update these files to get the generated output:
   1. `hack/after-build/update-generated-conversions.sh`
   2. `hack/after-build/update-generated-deep-copies.sh`
   3. `hack/after-build/verify-generated-conversions.sh`
   4. `hack/after-build/verify-generated-deep-copies.sh`
   5. `hack/update-generated-swagger-docs.sh`
3. You have to manually create `types.generated.go` in every internal and external package to get codec-gen to work.
4.  You have to update `pkg/api/registered/registered.go` to be allowed to install your group.

That's just to get your types registered.  Right now, there's no pluggable way to include custom `RESTStorage` into the API server for my new types.

@caesarxuchao @lavalamp @liggitt @smarterclayton 
@kubernetes/rh-cluster-infra @kubernetes/goog-csi

**Comment by caesarxuchao** [comment]
> You have to update pkg/api/registered/registered.go to be allowed to install your group.

This should be resolved when #18531 is solved.

Yeah, adding a group now is kind of painful. We should automate some steps. We have a doc on the steps required to add a group: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/adding-an-APIGroup.md

**Comment by deads2k** [comment]
> Yeah, adding a group now is kind of painful. We should automate some steps. We have a doc on the steps required to add a group: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/adding-an-APIGroup.md

I had no idea there was a doc.  Glad our steps line up. :)

Is there any plan to better automate the checking?  I'm worried about people accidentally skipping a step.  Code still compiles even with pieces missing.

**Comment by caesarxuchao** [comment]
> Is there any plan to better automate the checking? I'm worried about people accidentally skipping a step. Code still compiles even with pieces missing.

Agree, I don't have concrete plan though. I personally got bitten by missing `types.generated.go` twice. It just decodes everything to empty without giving an error message.

If we can reduce the steps involved adding a group, people will have much less chance missing a step. The most obvious improvement is keeping the groups in a central place and let all 5 shell scripts refer to it.

**Comment by ericchiang** [comment]
For anyone looking to add an API group, this is my incomplete list of files and directory structures needed to edit or create to add an API group for #24900 and #25634.

If uncommented, the edit was likely just adding a string or import statement to an existing list.

API Group:
* pkg/apis/{group} (copy directory structure from existing examples forgoing generated code)

Codegen:
* hack/update-swagger-spec.sh
* hack/update-generated-swagger-docs.sh
* cmd/libs/go2idl/conversion-gen/main.go
* cmd/libs/go2idl/deepcopy-gen/main.go
* cmd/libs/go2idl/go-to-protobuf/protobuf/cmd.go
* cmd/libs/go2idl/client-gen/main.go

Notes for codegen:
* Must add “// +genconversion=true” in doc.go
* Must add “// +genclient=true” or “// +genclient=true,nonNamespaced=true” above each top level type in both {group}/types.go and {group}/{version}/types.go
* Touch pkg/apis/{group}/{version}/types.generated.go before generating

Client:
* pkg/client/unversioned/client.go (add interface initializer)
* pkg/client/unversioned/helper.go (make sure client constructor initializes api group client)
* pkg/client/unversioned/import_known_versions.go
* pkg/client/unversioned/testclient/simple/simple_testclient.go
* pkg/client/unversioned/{resource}.go (copy code from existing files)
* pkg/client/unversioned/testclient/fake_{resource}.go (copy code from existing files)
* pkg/client/unversioned/{groups}.go (copy from existing templates)

Tests:
* pkg/api/testapi/testapi.go (add a test API Group)
* test/integration/framework/master_utils.go (import serializer)

API Server
* pkg/registry/cachesize/cachesize.go (initialize cache size for resources)
* pkg/registry/{resource} (copy directory structure from existing files)
* pkg/master/master.go (setup api group)
* pkg/master/master_test.go

Kubectl:
* Add printers to pkg/kubectl/resource_printer.go (add printer for each resource)
* pkg/kubectl/cmd/util/factory.go (in NewFactory() and ValidateBytes())

**Comment by pmorie** [comment]
@ericchiang could you ensure the doc linked earlier in this issue is updated with that info?

**Comment by ericchiang** [comment]
@pmorie yeah I'll open a PR when I get a chance

**Comment by danwinship** [comment]
FWIW note that adding-an-APIGroup.md has not been updated for the autogenerated client changes
