### ISSUE TITLE
Determine the fate of nsenter_mount.go

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#18776]
Now that mount propagation mode control is merged into docker and will be released with 1.10, we should begin considering what the eventual fate of nsenter_mount.go is.  A couple things to consider:
1.  We'll need to retain this to support pre-1.10 dockers
2.  Does it have utility for other runtimes?  I created an issue for rkt to support controlling the propagation mode of bind-mounts into rkt pods, haven't checked on whether it's been implemented yet.

@kubernetes/goog-node @yifan-gu @kubernetes/rh-cluster-infra

**Comment by yifan-gu** [comment]
cc @aaronlevy

**Comment by dchen1107** [comment]
cc/ @thockin @saad-ali

**Comment by dchen1107** [comment]
For cross-ref: https://github.com/docker/docker/pull/17034

**Comment by yifan-gu** [comment]
@pmorie On rkt side, we are adding new command `rkt fly` to launch images in host namespace.
https://github.com/coreos/rkt/pull/1833

Here you can find a recorded demo from today's rkt community sync, (demo about running kubelet using `rkt fly` started from 13min)
https://youtu.be/NMJTtg93PNY?t=13m41s

**Comment by yifan-gu** [comment]
cc @steveeJ @jonboulle

**Comment by vishh** [comment]
@yifan-gu: A part of the problem is that of kubelet running inside a mount namespace.
The other part is that of introducing mounts into containers. Perhaps @pmorie can better summarize the latter use case.

**Comment by steveeJ** [comment]
@vishh the rkt feature that @yifan-gu has linked doesn't use a new mount namespace, just chroot. 
I'm interested in learning about the second problem you mention, *introducing mounts into containers*. What parts of the host does the kubelet need to see, and is the chroot possibly too limiting for this?

**Comment by vishh** [comment]
@steveeJ: chroots are not an issue for kubelet. Kubelet might have to propagate mounts from the host mount ns into that of the user container.

**Comment by yifan-gu** [comment]
@vishh @pmorie Is kubelet required to run in a separate mount space than the host? What's the use case for it?

**Comment by pmorie** [comment]
Not sure I understand the question @yifan-gu

**Comment by yifan-gu** [comment]
@pmorie Sorry, I mean if kubelet is running as a "container", what's the reason that we can't let it run in the host mount namespace? I probably missed this part.

**Comment by saad-ali** [comment]
@yifan-gu Longer term we'd like to see third party volume plugin code removed from the Kubernetes code base and containerized. In order to support fully custom mount/unmount logic running inside a container we'd need something like Docker's volume mount propagation mode.

**Comment by philips** [comment]
@saad-ali  Is there a design document on how you see the third party plugins will be pulled out and isolated?

**Comment by saad-ali** [comment]
@philips No detailed design doc yet, but high level proposal here: https://github.com/kubernetes/kubernetes/issues/18333

**Comment by jonboulle** [comment]
@saad-ali it's unclear to me from that proposal whether the plugins just require access to the host namespace or to arbitrary mount namespaces

**Comment by saad-ali** [comment]
@jonboulle the plugins would just need access to the host namespace

**Comment by yifan-gu** [comment]
From the proposal #18333:

> Longer term all third party plugin code would be containerized and removed from the Kubernetes code base. The controllers on master could “docker run” the plugin container with the correct parameters to create/delete/attach/detach volumes. In order to support fully custom mount/unmount logic, the containerized plugin could contain mount/unmount code that Kubelet could similarly “docker run” (this will have to wait until Docker makes the changes needed to allow an executable running inside a container to mount to the host).

My understanding is the containerized plugin need to do mounts to the host. Currently, the processes started by `rkt fly` are in the host mount namespace, so we are good.

**Comment by pmorie** [comment]
@jonboulle @saad-ali @yifan-gu 

> the plugins would just need access to the host namespace

Correct, at least at first.

**Comment by pmorie** [comment]
@yifan-gu 

> Sorry, I mean if kubelet is running as a "container", what's the reason that we can't let it run in the host mount namespace? I probably missed this part.

At least in docker, there's not really a notion of running directly in the host's mount namespace because filesystems are provided to containers via their own mount namespaces.  Take away that mount namespace, and you basically lose the container's FS without something that can run the container process as chroot into where the container's FS is supposed to be.  So, 'run-in-host-mount-namespace' is not really a thing at all.

I need to catch up on `rkt fly` -- sorry for the latency on my reply.

**Comment by mikedanese** [comment]
How do the api types need to change to support mount propagation? Is it and extra field in host volume?

**Comment by pmorie** [comment]
@mikedanese in my mind it's an extra field in the security context.  Not sure if it should be pod, container, or both, though.  I think there's a strong case for container-level, less strong for pod-level.  It might be appropriate to limit shared mode to privileged containers.

**Comment by pmorie** [comment]
Alright, picking this back up:

I would like to remove NsenterMounter and NsenterWriter in 1.5.  The only reason these are needed is because docker did not allow setting mount propagation mode on bind-mounts before version 1.10.

@kubernetes/sig-node

**Comment by dchen1107** [comment]
SGTM.

**Comment by luxas** [comment]
SGTM, but when we do that, we have to support shared volumes first (https://github.com/kubernetes/kubernetes/pull/20698)

Also, we should deprecate `--containerized` now in v1.4

**Comment by euank** [comment]
I think we should have support for shared volumes in K8s due to self hosting, and there's some active discussion related to that as well. cc @aaronlevy @pbx0 @derekparker

**Comment by pmorie** [comment]
@euank Agree, self-hosting has always been one of my personal goals in this area.

Now, some bad news: I think we will actually have to keep the `NsenterMounter` around in 1.5 -- shared volumes have issues on some kernels, but we can at least assume everyone will have a workable slave propagation mode now.  However! We can at least lose the NsenterWriter, since that is a stop-gap from when you could only assume private propagation mode.

**Comment by luxas** [comment]
@pmorie Which are the problems with the shared mounts? On which kernels?

And if I understand you correctly, `NsenterWriter` is now unnecessary when mounting the `/var/lib/kubelet` path with `slave`?
