### ISSUE TITLE
Kubectl docs (long help) would look better if they coud use markdown

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#18771]
Our long command text doesn't look good when translated to markdown. (see [config.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/config/config.go#L71) which gets turned into [kubectl_config.md](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_config.md#synopsis)). It'd be wonderful if we could use markdown syntax in our long help so that our docs were more helpful.

It doesn't look like cobra supports that directly, so it'd probably have to be a pre-compile code-gen step (or a change to cobra).

**Comment by cjcullen** [comment]
@jlowdermilk

**Comment by brendandburns** [comment]
cobra is easy to change (we have several owners including myself and @eparis)

looks like its as simple as linking in:  https://github.com/russross/blackfriday

**Comment by eparis** [comment]
Definitely make any changes to cobra. I'm not sure if we'd want a LongMd: field or just a flag to indicate if Long was markdown...

We need some way to convert md back to just plain text for `--help` but leave it as md for the md docs...

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
@kargakis I don't think sig-docs can help much here.

**Comment by ahmetb** [comment]
this content is now at https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#config

Do we need to keep this open?
