### ISSUE TITLE
Kuberentes client no longer compiles due to change in docker repo

### ISSUE THREAD

**Issue by tnine** [kubernetes/kubernetes#18774]
Hi all,
  I'm attempting to write some kubernetes clients in go.  I'm attempting to download the latest client, and it fails with the following error.

```
 go get "k8s.io/kubernetes/pkg/client/unversioned"
# k8s.io/kubernetes/pkg/util/parsers
/Users/apigee/.go/src/k8s.io/kubernetes/pkg/util/parsers/parsers.go:30: undefined: parsers.ParseRepositoryTag
```

It appears the "ParseRepositoryTag" function has been removed from the latest docker client.

**Comment by tnine** [comment]
After going through the history, it appears it was removed in this commit.  It's been removed here.

https://github.com/docker/docker/commit/4352da7803d182a6013a5238ce20a7c749db979a#diff-8a4a471eeec9e5954d06c11472eb5044L113

However, there doesn't appear to be any documentation on where equivalent functionality is provided.

**Comment by ncdc** [comment]
Kubernetes uses Godeps to vendor in dependent code, such as `github.com/docker/docker`. We bump the vendored code and fix any breakages at that time. Unfortunately, when you're trying to use something that just imports `k8s.io/kubernetes` and have it work with `github.com/docker/docker` both at HEAD, you may run into an issue like this. In the short term, if you can use Godeps, you can version lock both kubernetes and docker to the appropriate revisions in your project.

**Comment by ncdc** [comment]
And btw, ParseRepositoryTag was replaced with `reference.Parse*` from `github.com/docker/distribution`

**Comment by tnine** [comment]
Hi @ncdc Thanks for the help.  I've been playing around with this and not having a lot of luck.  I've tried the following.

1. Clone the source
1. ``` git checkout v1.1.3```
1. ```./hack/build-go.sh```
1. ```cp -r Godeps/_workspace/ $GOPATH/``` to copy the dependencies and the source to my local gopath
1. ```godeps save``` in my own project to copy them from my global $GOPATH into my dependencies.  

However, I receive quite a few errors when godeps does not understand the copied git repo

Obviously this doesn't work, it seems I won't have the Kubernetes source.  What are the steps to developing with the Kubernetes client and go?  I'm new to both Kubernetes and go, unfortunately there isn't any documentation on getting running with the go client.

https://github.com/kubernetes/kubernetes/tree/release-1.1/pkg/client/

I'd be happy to contribute to the documentation once I have some instructions.  I'm just not sure where I should start.

**Comment by jlowdermilk** [comment]
@tnine the build setup for development is a bit finicky. The [development guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md) is a good place to start. There's a section on godeps that should help you fix your setup.

**Comment by jdoliner** [comment]
Has there been any activity on this? I see a number of things in the referenced issue but I'm still seeing this error with vendored code.

Is there a reason that the code hasn't been updated to use the `reference.Parse` yet? It seems like that supports identical functionality and would take 2 seconds to fix.

**Comment by bgrant0607** [comment]
@jdoliner Unfortunately, our code isn't factored in such a way to be go gettable, in whole or in part.

We also don't yet have a client library we support for other users.

In the meantime, you could check out kubelite:
https://github.com/technosophos/kubelite

If you'd like to help, I recommend checking out the API machinery SIG.
https://github.com/kubernetes/kubernetes/wiki/SIG-API-Machinery

See also #5660 and #20193

cc @lavalamp @caesarxuchao

**Comment by lavalamp** [comment]
1.2 is going to have a version-locked client available. But it will still have an overly broad import dependency tree. We will fix that over time.

**Comment by eparis** [comment]
To work with godeps and kube you basically need to do:
```
go get -u k8s.io/kubernetes
cd $GOPATH/src/k8s.io/kubernetes
godep restore
```
That should get both your $GOPATH and the stuff in Godep/_workspace 'the same'. and should let you do your own builds without using the hack/ scripts, as it seems you are trying to do.
