### ISSUE TITLE
Proposal: Split issue Priority into Importance and Urgency

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#18780]
cc @thockin @goltermann @bgrant0607 @smarterclayton
 
Status Quo
=========
Currently we apply a single **Priority** label to every issue, and (somewhat inconsistently) use that as a work queue mechanism for the project.  Each person in theory tries to work on a priority/P0 issue, and if there are none of those, or they're all already being worked on, or the person does not have the required skills to work on any of the P0 issues, they try to work on a P1 issue, P2 issue, etc.

Problems with this approach
======================
The core problem with that approach is that the two orthogonal concepts of **Urgency** (how soon we'd like something done), and **Importance** (how important we think it is in the long term that something gets done) are munged together into a single **Priority** value, and in the process we lose a very important signal.  

More specifically, without explicit steps to avoid this, it becomes too easy to focus too much attention on supposedly urgent issues and not enough on truly important, but less urgent issues.  Sometimes a similar distinction is made between **tactical** and **strategic** work.

This phenomenon has been well documented elsewhere, and is pretty main-stream thinking in management science, e.g. [Covey's Time Management Grid](http://www.usgs.gov/humancapital/documents/TimeManagementGrid.pdf).

Another practical problem with a combined **Priority** value is that it tends to be more volatile than the the individual **Importance** and **Urgency** values (when we get time to work on a P2 issue, it becomes a P1 issue. When a P1 issue starts blocking other important stuff like merge-bot it becomes a P0 issue etc, etc).  So priority values need to be updated a lot, and easily become inaccurate over time.  So while the Priority method involves fewer labels, and is therefore theoretically easier to understand, and less work to maintain, in practise people get very confused by it (is this thing a high priority because it's urgent, or because it's important?  Why are you working on this thing that is not a top priority?  Because we think it's strategically important. etc).  And they spend a lot of time prioritizing and re-prioritizing things, rather than getting things done.

Proposed Alternative
=================
Assign independent **Importance** and **Urgency** values to each issue.  This places every issue in one of 4 quadrants:

- **Quadrant 1: Import and Urgent** - clearly these should be worked on in preference to all else.  If we apply enough effort to important stuff in advance of it becoming urgent, it tends not to end up in this quadrant.  In a happy world this quadrant is empty.
- **Quadrant 2: Important but not Urgent** - this is the stuff that often doesn't get done, and causes big problems down the line.  Make sure that we do it in preference to the stuff below wherever practical.
- **Quadrant 3: Urgent but not Important** - time-pressured distractions.  These are often fallout from not doing enough important stuff in quadrant 2 above.  
- **Quadrant 4: Not Important and not Urgent** - just ignore this stuff - it's of low value.

In practise I think that we need more than binary values for Importance and urgency.  A scale of 0..3 as we use for priorities seems sensible, although we could possibly reduce this to 0..2.
  
Migration Plan
===========
Given the number of issues that we already have that have a priority label assigned to them, it could be a real pain to have to manually apply a the proposed new Importance and Urgency labels to them instead (and deprecate the Priority labels). But there is a potential short-cut as follows:

1. Use the existing priority label to automatically assign an Importance label to each issue.  So high priority items become important items in the new world.
1. Assign low urgency labels to everything by default.

Over time, new issues will get the right labels, and old issues will have their importance and urgency labels corrected (e.g. increase an issue's importance or urgency to get it into a release).

Thoughts? Unless anyone has objections, I'll implement it after appropriate consultation.

**Comment by quinton-hoole** [comment]
@aronchick FYI

**Comment by quinton-hoole** [comment]
#18764 is what prompted this.

**Comment by bgrant0607** [comment]
There's no getting around the fact that importance and urgency change, and that we decide to do certain things at certain times. I try to at least ensure P0s and P1s are accurate for the current milestone. We have too many open issues (over 2000 now) to keep all these values straight for all issues, and more values will make it harder. I've never seen both priority and severity used correctly together internally. Among other problems, the inevitable reaction to an important issue that's not acted upon is exactly how you reacted here: https://github.com/kubernetes/kubernetes/issues/1627#issuecomment-164900169

**Comment by aronchick** [comment]
IMHO, the ordering of addressing items is a numerical list, with each item
getting its own (unique) index. I've never been fond of P0, P1, etc - it
tells you how significant something is, but doesn't telling someone
unfamiliar with the issue _which_ significant item should be worked on.

This is not to say everything needs a number - but giving a number the top
<n> (where n = the space allotted for the next milestone plus a little bit)
would be best.

**Comment by quinton-hoole** [comment]
@bgrant0607 

- Regarding importance and urgency changing over time, agreed, they do.  My hypothesis is that they change less frequently than our work queue ordering (which is effectively what the manged-together priority label is currently used for).
- Regarding more values making it harder, see above and paragraph 4 of "Problems with this approach".
- Regarding my reaction in https://github.com/kubernetes/kubernetes/issues/1627#issuecomment-164900169 that is good example of the problem with the combined priority label (which is most often used as something closer to urgency than importance, but not consistently so), and that this proposal aims to improve upon.  In that particular case, the issue was labelled Priority 1, but upon cursory examination had not been actively worked on for more than a year. So it seemed to not be urgent, although in retrospect very important. With the current system we don't have a good way of capturing that in our database of work items, which is what lead to my confusion.
- Regarding not having seen priority and severity being used properly internally, I agree 100%.  I strongly believe that the reason for that is that nobody actually knows what the two terms mean, or how they differ.  Hence they almost never use the Severity label, and munge all vague notions of  importance, urgency and severity into the single Priority field, with aforementioned undesirable consequences.  In contrast "Importance" and "Urgency" are far more self-explanatory IMO, and will at the very least be well documented in this case, so that people have a fighting chance of using them correctly and consistently. 
- How about the proposed migration plan as a first step. It has, IMO, a chance of success, but is very easy to roll back if you turn out to be right about nobody using it properly.

**Comment by quinton-hoole** [comment]
@aronchick The problem with giving each item in the work queue a unique (relative) number, is that every time anything is added to or removed from the list, everything needs to be renumbered.  In addition, it's not possible to assign a number to any item without full knowledge of all other items.  Hence we use absolute numbers (P0..P3).  Perhaps you're arguing for a larger number of discrete values on that scale?  I've heard several grumblings that we don't even properly use the few numbers that we currently have, so I don't think that you'll find much support for a larger number.

**Comment by bgrant0607** [comment]
Build/test breakages and features targeting the current milestone are urgent. Everything isn't. Until it is.

**Comment by goltermann** [comment]
I don't think strict ordering is going to work for the number of issues we have (maybe it would work just for major features, but not for the general issue queue).

Perhaps the right thing is to capture urgency by just putting each issue in a milestone (which we've done at earlier points in the project, but not consistently).   We could have current, next and >next as the 3 milestones open at a given time.  This would signal both relative urgency, and be a first cut at when it might land in the codebase.

I do worry about having to constantly go over every issue and change a tag (i.e. 3 months go by, and we have to bump 500 issues from urgency 3 to urgency 2, or something like that).

**Comment by quinton-hoole** [comment]
@bgrant0607 @goltermann I'll table this for brief discussion at our pow-wow next week.  I'm not necessarily wedded to the process described in this issue, but it seems that we do need to make some sort of fundamental change to how we order issues into a work queue, as the currently process simply doesn't work well.  Alternative suggestions welcome (@golterman, I think that your proposal above can work).

**Comment by bgrant0607** [comment]
I'm in favor of a milestone-oriented approach to urgency.

**Comment by thockin** [comment]
Milestones give a sense of urgency, but it sort of overlaps with prio,
unless we redefine prio as importance rather than urgency.

I could maybe get behind something like that

**Comment by quinton-hoole** [comment]
@thockin To be clear my original proposal in this issue is to deprecate "priority" completely, replacing it with orthogonal "importance" and "urgency" labels.  @goltermann proposed a refinement of that, using "milestone" as the equivalent of urgency label (and implicitly removing "priority" and replacing it with "importance").  My proposed migration plan was to convert all high "priority" items to high "importance", and incrementally clean up from there.

As far as I can tell from the comments in this thread, all of @thockin, @golterman, @bgrant0607 are (potentially) in support of this refined approach.  Can I go ahead with it?

**Comment by bgrant0607** [comment]
I am not in favor of an urgency label. Milestones should be used to reflect urgency.

Feel free to rename priority labels to importance, but that's shuffling deck chairs, IMO.

**Comment by thockin** [comment]
That was really my point.  If we use milestones as an urgency indicator,
the existing P0..P3 labels become a spectrum of importance.  Maybe it's too
granular, but I actually get value from P0 vs P1 vs P2.  I could lose P3

**Comment by aronchick** [comment]
Don't think of the number as a unique, ordered list. Multiple items can have the same number (though not ideal) and there can be gaps. After each milestone, you can do a reordering exercise - or really any time you want to re-evaluate what you want to be next. Using priority labels, ideally, would accomplish this, but, due to their coarseness, they're an inefficient tool.

**Comment by thockin** [comment]
We should decide on this or close it before we start 1.3

**Comment by quinton-hoole** [comment]
I'm happy to close this as "will not implement", but that requires that we start to use "priority" to consistently mean "importance" and not "urgency" (the latter of which is captured in the "milestone" pseudo-label).  I still think that renaming "priority" to "importance" will make this more likely to happen, but it seems I'm in the minority here (see @bgrant0607 's "deckchairs" comment above, and @thockin's agreement with that.  

Closing.

**Comment by bgrant0607** [comment]
With respect to P3: I use P3 to distinguish things that I think are low enough that we'd never do them, but aren't objectionable, so someone from the community could potentially do them.

**Comment by quinton-hoole** [comment]
One final post-script comment.  Right now we are explicitly using "priority" as a sub-scale of "urgency" in the sense that P0 and P1 items for release-1.2 are blockers (must be done before we release 1.2).  Stuff that is not a true blocker, is being dropped to P2 in many cases (even though it might be very, very important). It's not yet totally clear to me how we reconcile this with the plan above. #21630 provides a concrete example.

More specifically, to be consistent with the above plan, I think that we should in general be changing the release label of non-blockers, and not reducing the "priority" (which is supposed to mean "importance" now. But some people might disagree with that.
