### ISSUE TITLE
docs.k8s.io is still pointing to v1.0 docs

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#18788]
docs.k8s.io takes me to http://kubernetes.io/v1.0/docs/
We should update it to redirect to http://kubernetes.io/v1.1/docs/

Not sure how it is setup

cc @caesarxuchao @janetkuo

**Comment by thockin** [comment]
It's very manual. Fixed.

**Comment by nikhiljindal** [comment]
@thockin Thanks for the quick fix!
Can you document the steps somewhere.
We will have to do this everytime we push docs for a new release.

I am trying to document all the steps in pushing a new release https://github.com/kubernetes/kubernetes/pull/17983

**Comment by thockin** [comment]
The steps are:

Reconfigure the nginx forwarder that services k8s.io to redirect to the
newer github branch.

I don't think we should document that here because it is very much an
internal-only thing.  Do we have an internal doc?  I would be happy to
document there :)
