### ISSUE TITLE
kube2sky go-etcd dependency

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#18791]
kube2sky is the only leftover that has a dependency on go-etcd, this is a note that owner should update to latest client in order to remove the godep.

**Comment by thockin** [comment]
@artfulcoder

On Wed, Dec 16, 2015 at 2:55 PM, Timothy St. Clair <notifications@github.com

**Comment by wojtek-t** [comment]
Once this is done, we should remove go-etcd dependency from Godeps.

**Comment by ArtfulCoder** [comment]
something similar to https://github.com/kubernetes/kubernetes/pull/18635/files

**Comment by timothysc** [comment]
@ArtfulCoder yes.  
xref: https://godoc.org/github.com/coreos/etcd/client

**Comment by timothysc** [comment]
closing, no longer applies. 0xDEADBEEF
