### ISSUE TITLE
1.1.1 privileged forbidden yet

### ISSUE THREAD

**Issue by manusu** [kubernetes/kubernetes#18803]
At first,i installed kubernete1.0.1.After found it not allowed privilege container, i install a higher version 1.1.1. now i meet two problem. 
1.when i build a example,i found service is up,but there is no pod running, describe it shows "Replicas:   0 current / 1 desired ;service Pods status 0 running/ 0waiting /0 succeeded /0 failed“
2.then i try to create a privilege container in a pod,it report the same error 
"spec.containers[0].securityContext.privileged: forbidden '<*>(0xc209034dc0)true'"
what's wrong with my kubernetes?
thanks a lot for help

**Comment by Dingshujie** [comment]
check kube-apiserver command flags, whether --admission-control contain SecurityContextDeny, This plug-in will deny any pod with a SecurityContext that defines options that were not available on the Container, so  restart kube-apiserver and delete it, you can create a privilege container

**Comment by timstclair** [comment]
Closing due to age. Please reopen if it's not resolved.
