### ISSUE TITLE
Proposal: kubernetes should have a lease mechanism for each Pod

### ISSUE THREAD

**Issue by kendung** [kubernetes/kubernetes#18807]
as we all know, the resources managed by Kubernetes are precious. We need to define a mechanism for kubernetes to manage the resources more efficiently:

1, when define Pod spec, we can introduce a expire time for it. 
2, Before expire time reached, kubernetes will send out notification mail to users for reclaiming the resources.
3, Kubernetes also have ability for users to extend the expire time under some conditions.
4, once expire time reached, kubernetes can safely reclaim the resources occupied by user.

**Comment by thockin** [comment]
This is a pretty good example of something that can be totally built on top
of kubernetes and doesn't need much help from the core of the system.

**Comment by kendung** [comment]
@thockin from some point of view, this can be built on top of kubernetes. Kubernetes has the capability to make users' pod more available by way of replication controller. From resource management perspective, resource allocation and resource reclaim should both exist for the closed loop system. At least, kubernetes should have a basic framework for users to define some rules bind to the pod for resource reclaim, such as, if no traffic to the service for a  long time, the pod should be reclaimed.  Users should have choice to use it or not.

**Comment by thockin** [comment]
My point was that there's nothing here that requires to be in the core of
the system.  It's very much a policy decision that can be implemented (or
not) differently for different installations.  Rules like "if no traffic to
the service for a long time, the pod should be reclaimed" are not really
generically applicable - a Pod may be "behind" any number of Services.

Anyway, I don't see this going into the core system, certainly not in the
near future - there's just SO MUCH stuff to do, and we need to be very
conscious of where the borders are.  It's an interesting idea, though - I'd
love to see a first-draft implemented entirely on top of kube.  That would
expose any things that kube needs to do to make it possible.
