### ISSUE TITLE
scheduler: filterNonRunningPods can be moved to add/update func

### ISSUE THREAD

**Issue by magicwang-cn** [kubernetes/kubernetes#18808]
every pod scheduling will traversal [pods cache](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L429) to filter the (`api.PodSucceeded`) and (`api.PodFailed`) pods,  can we move the filter to [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/framework/controller.go#L236) to reduse the filtering time/temporary mem use by pod scheduling?

@davidopp @xiang90 @HardySimpson

**Comment by mqliang** [comment]
How about move the filter logic to list&watch client?

**Comment by mqliang** [comment]
Why not move the filter logic to list&watch client?

**Comment by xiang90** [comment]
ref https://github.com/kubernetes/kubernetes/issues/18831

**Comment by xiang90** [comment]
I think this is a subset of the optimization we can do in #18831. Basically, we should try not to traverse pods when scheduling by caching the node state incrementally.
