### ISSUE TITLE
NodePort services broken by default-deny firewall rules

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#18802]
Non-cloud installs of fedora and centos include the iptables-service package by default, which adds the following rules:

    -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    -A INPUT -p icmp -j ACCEPT
    -A INPUT -i lo -j ACCEPT
    -A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
    -A INPUT -j REJECT --reject-with icmp-host-prohibited

These rules don't affect pod-originating traffic targeting a service, since that traffic is always routed locally (-i lo) to their hosting node's proxy.   However, non-pod traffic for NodePort services will be originating from outside of a node and slip through to the REJECT rule.  To ensure compatibility with hosts with this kind of default-deny rule, the proxy should probably be adding explicit ACCEPT rules for the proxy ports it is accepting traffic on.

**Comment by knobunc** [comment]
Related to bug https://bugzilla.redhat.com/show_bug.cgi?id=1280279

**Comment by marun** [comment]
cc: @thockin

**Comment by thockin** [comment]
Won't this reject all pod-pod traffic and node-pod traffic (kube-proxy
userspace)?

**Comment by knobunc** [comment]
There are other rules that aren't shown that allow traffic to hit the vxlan port (for pod-pod):
  ACCEPT     udp  --  anywhere             anywhere             multiport dports vxlan /* 001 vxlan incoming */
[Which is a little scary, we should probably filter that by nodes in the cluster]

And to allow local traffic from the node to the pod IPs:
ACCEPT     all  --  10.1.0.0/16          anywhere            
ACCEPT     all  --  anywhere             10.1.0.0/16

**Comment by marun** [comment]
This was fixed by #18804
