### ISSUE TITLE
Some Comments in test-cmd.sh are wrong

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#18800]
Tests for pods in ```test-cmd.sh``` just check whether pods are exist or not, they don't check the status of pods. So I think the comments as follows in ```test-cmd.sh```  are wrong
~~~
# Pre-condition: no POD is running
# Post-condition: valid-pod POD is running
~~~
Maybe could be replaced with the follows
~~~
# Pre-condition: no POD is exist
# Post-condition: valid-pod POD is created
~~~

**Comment by jlowdermilk** [comment]
Sounds right. A pr would be welcome.
