### ISSUE TITLE
integration flake: netcat isn't installed

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18811]
https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/4774e7146e0980b0ab9e0a8027e50254e7f6945d/kubernetes-pull-test-unit-integration/5270/

```
+++ [1210 06:35:02] Starting kubectl proxy
+++ [1210 06:35:02] On try 1, use proxy port 60486 if it's free

netcat isn't installed, can't verify if 127.0.0.1:60486 is free, skipping the check...
```

cc @kubernetes/goog-cluster 
@thockin please triage

**Comment by brendandburns** [comment]
I think we just need to install netcat on our jenkins worker box, I'll do that.

**Comment by brendandburns** [comment]
I installed netcat on the worker node.  That should fix this issue.

**Comment by gmarek** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/5570 printed:
```
03:21:16 netcat isn't installed, can't verify if 127.0.0.1:37704 is free, skipping the check...
```

**Comment by brendandburns** [comment]
netcat is installed on the other builder as well.  I'm going to close this for now.

If this fails again, there's something else going on with this issue...
