### ISSUE TITLE
Kubemark sometimes fails to start

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18828]
The error is as following:

    16:31:54 Removing intermediate container 18f25494a537
    16:31:54 Successfully built 7969077b67a9
    16:31:54 gcloud docker push gcr.io/k8s-jenkins-kubemark/kubemark
    16:31:54 The push refers to a repository [gcr.io/k8s-jenkins-kubemark/kubemark] (len: 1)
    16:31:54 push or pull gcr.io/k8s-jenkins-kubemark/kubemark is already in progress
    16:31:54 make: *** [all] Error 1

**Comment by gmarek** [comment]
It's caused by the concurent pushes of kubemark image to GCR. The fix is to append something unique to the name of the image.

**Comment by wojtek-t** [comment]
@gmarek - is this fixed now?

**Comment by gmarek** [comment]
Seems so.
