### ISSUE TITLE
Update Influxdb client to 0.9+ with api version v2

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#18826]
Currently we are on 0.8 with deprecated api.

**Comment by piosz** [comment]
The list of work items:
- [ ] support for new client in Heapster
- [ ] bump Heapster and Influxdb version
- [ ] update godeps 
- [ ] migrate InitialResources to use new client (and initial_resources e2e)
- [ ] migrate monitoring e2e test

**Comment by piosz** [comment]
We are mostly done. Decreasing the priority.

**Comment by mwielgus** [comment]
Done.

**Comment by dpratt** [comment]
Is there any movement on this? We run (like a lot of users) in AWS, and thus use InfluxDB directly to store our cluster metrics from heapster. It's not a dealbreaker, but it would be nice to be able to use the InitialResources admission controller.

**Comment by Pendoragon** [comment]
any plan on re-enable influxdb as a backend store? we also want to use the initialresource admission control

**Comment by piosz** [comment]
Reassigning to @jszczepkowski and @krzysztofgrygiel who will work on the new version of Iniital Resources/Vertical Pod Autoscaler.

**Comment by mwielgus** [comment]
Won't be fixed. Initial resources will be deleted in favor of VPA.
