### ISSUE TITLE
Godeps broken due to docker pkg move

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#18833]
Verifying Godeps failed:
```console
# hack/verify-godeps.sh 
Starting to download all kubernetes godeps. This takes a while
godep: restore, during download dep "github.com/docker/docker/pkg/timeutils": exit status 1
godep: restore, during download dep "github.com/docker/docker/pkg/units": exit status 1
godep: restore, during download dep "github.com/docker/libcontainer": exit status 1
godep: restore, during download dep "github.com/google/cadvisor/api": exit status 1
godep: restore, during download dep "github.com/google/cadvisor/http": exit status 1
godep: restore, during download dep "github.com/google/cadvisor/manager": exit status 1
godep: restore, during download dep "github.com/google/cadvisor/pages": exit status 1
godep: restore, during download dep "github.com/google/cadvisor/validate": exit status 1
!!! Error in hack/verify-godeps.sh:74
  '"${GODEP}" restore' exited with status 1
Call stack:
  1: hack/verify-godeps.sh:74 main(...)
Exiting with status 1
Removing /tmp/gopath.VwTtTO
```
[Recent Docker commit](https://github.com/docker/docker/commit/27220ecc6b1eedf650ca9cf94965cb0dc2054efd) moved `github.com/docker/docker/pkg/timeutils` and `github.com/docker/docker/pkg/units`, thus other Godeps such as `github.com/google/cadvisor/api` and `github.com/google/cadvisor/http` are also broken.

**Comment by rootfs** [comment]
@dchen1107 @lavalamp

**Comment by mephux** [comment]
any update on this?

**Comment by thockin** [comment]
Aren't we locked to a commit number?  Isn't that the point of godep?
Changes at head should not break us.

**Comment by jimmidyson** [comment]
This is a bug in godep itself. If packages are missing from dep's master branch then it can't restore them... There are some hacks iirc in the scripts to sort this out - I'm hitting the same issue in #17883 so will try to fix it as part of that.

**Comment by jimmidyson** [comment]
The (hacky) solution seems to be to use the `preload-dep` from https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh#L27-L43 to preload the Docker dependency. This is rubbish but not much else we can do I don't think.

@eparis - think it was you that guided me to this solution last time we hit it. Still the "right" thing to do or is there a better solution?
