### ISSUE TITLE
Failures when deleting dynamic volumes

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#18832]
There is a race between deleting a pod which uses a dynamically provisioned volume and deleting appropriate claim.

E.g:
1. User runs a pod with a dynamically provisioned claim.
2. User deletes the pod
3. User deletes the claim.

At step 2, the pod is deleted from the API server and kubelet starts (slowly) tearing the pod down - stopping containers, detaching volumes etc.

At step 3, when the user (or e2e test) is quick enough, Kubernetes should delete the dynamically provisioned volume. However, it's still attached to the dying pod and deletion fails. The PV enters 'Failed' state.

IMO, Kubernetes should at least retry the deletion. Or, detect that the volume is still attached and postpone the deletion until it's fullly detached.

cc: @markturansky @pmorie

**Comment by jsafrane** [comment]
@kubernetes/rh-storage

**Comment by markturansky** [comment]
This race will continue even after detaching moves from Kubelet to an attach/detach controller.

@thockin simple question for you... is it a standard practice to save state on an object using annotations that are known by all actors in the system?

e.g, Set a "provisioning required" annotation on a PV, which is processed by another controller that, in turn, sets the "provisioning completed" value.

The PV docs (or any object docs) would publish its list of known annotations, why/when they are used, and what values are expected as the interlock between various system components.

"Requires attach/detach" and "attach/detach" completed would follow the pattern we used in provisioning.

**Comment by markturansky** [comment]
https://github.com/kubernetes/kubernetes/issues/15524

**Comment by yujuhong** [comment]
I believe this has been fixed by @saad-ali's volume manager work in v1.3.
