### ISSUE TITLE
Pod backoff log not useful

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/kubernetes#18834]
The logging message [here](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L415) leads to log lines like:

```
I1217 11:45:52.541009   31579 factory.go:386] Backing off 16s for pod &{32000000000 {63585967552 541004994 0x4b19880} 1}
```

Which aren't terribly useful.

**Comment by yujuhong** [comment]
The code mentioned is from the scheduler: https://github.com/kubernetes/kubernetes/blob/080cb60dab7dcdddf22bd658b8f443b2fd2af1b9/plugin/pkg/scheduler/factory/factory.go#L453

**Comment by kargakis** [comment]
@kubernetes/sig-scheduling-misc

**Comment by timothysc** [comment]
Logging in the scheduler was audited in 1.6 and said log is V4.
