### ISSUE TITLE
Change scheduling complexity from O(containers) to O(nodes)

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#18831]
So far the scheduling algorithm complexity is O(containers) -- not O(pods) nor O(nodes). The scheduling latency becomes higher as more containers/pods get scheduled -- last time we observed 20 ms on 0 pods and it increased to 200ms on 30k pods.

After fixing #18255, #18452, #18466, #18413, #18170, and making use of scheduler test suite #18458, we found that majority of time was spent on `PodFitsResources` and `PodFitsHostPorts` as well as the GC burden they brought.

The root problem of both is that they list all containers for every schedule decision -- O(containers). With caching the entire nodes to pods map and aggregated requested resource of a node and incremental updating, they could be optimized to O(nodes) logically the same.

After optimizing only `PodFitsResources`, we are able to reduce the scheduling latency to 20ms. The scheduling rate doesn’t decrease much as more and more pods get scheduled. The benchmark results:

```
BenchmarkScheduling100Nodes0Pods-4           200           5530781 ns/op
BenchmarkScheduling100Nodes1000Pods-4        200           7058672 ns/op
BenchmarkScheduling1000Nodes0Pods-4          100          15344940 ns/op
BenchmarkScheduling1000Nodes10kPods-4        100          20022489 ns/op
BenchmarkScheduling1000Nodes20kPods-4        100          19291019 ns/op
BenchmarkScheduling1000Nodes29kPods-4        100          24107608 ns/op
```

Before optimized, `PodFitsResources` computes pod request for every node, lists all containers for every node, and calculate aggregated requested resource to compare it with pod request. We added a cache for aggregated requested resource of every node. When a pod is assumed, scheduled, or deleted, a watch based update is made upon the cache. Finally we just consume from the cache along with iterating the nodes. We also reused the cache for `MapPodsToMachines` in `findNodesThatFit` -- optimized from listing all pods to watch based incremental updates.

There are still places for improvement: latest profile output showed that `PodFitsHostPorts` is still a large consumer of cpu cycles; @wojtek-t mentioned in scheduler test suite that listing tens of thousands of pods can potentially affect scheduller performance; priorityFuncs are still O(containers); etc.

Latest benchmark result on master (0f22ba4be3ed9077de3662ab1086a97695ad3a4c):
```
BenchmarkScheduling100Nodes0Pods-4           200           6049842 ns/op
BenchmarkScheduling100Nodes1000Pods-4        200          10174731 ns/op
BenchmarkScheduling1000Nodes0Pods-4           50          22099051 ns/op
BenchmarkScheduling1000Nodes10kPods-4         20          85206355 ns/op
BenchmarkScheduling1000Nodes20kPods-4         5          220729042 ns/op
BenchmarkScheduling1000Nodes29kPods-4         5          211274674 ns/op

```

[benchcmp](https://godoc.org/golang.org/x/tools/cmd/benchcmp) shows our improvement:
```
benchmark                                 old ns/op     new ns/op     delta
BenchmarkScheduling100Nodes0Pods-4        6049842       5530781       -8.58%
BenchmarkScheduling100Nodes1000Pods-4     10174731      7058672       -30.63%
BenchmarkScheduling1000Nodes0Pods-4       22099051      15344940      -30.56%
BenchmarkScheduling1000Nodes10kPods-4     85206355      20022489      -76.50%
BenchmarkScheduling1000Nodes20kPods-4     220729042     19291019      -91.26%
BenchmarkScheduling1000Nodes29kPods-4     211274674     24107608      -88.59%
```

**Comment by hongchaodeng** [comment]
Scheduling rate raw data on density test (30k pods on 10k nodes):
https://storage.googleapis.com/profiling/2015-12-16/10knodes-30kpods-perf-density-log.txt

**Comment by wojtek-t** [comment]
Awesome - I'm happy to review your changes.

@kubernetes/sig-scalability @davidopp

**Comment by HaiyangDING** [comment]
Great work, I am expecting your PR!

**Comment by HardySimpson** [comment]
Is the change happens in etcd or in the memory of sheduler?

**Comment by wojtek-t** [comment]
I don't think we should change anything in etcd - this should be scheduler change.

**Comment by davidopp** [comment]
> We added a cache for aggregated requested resource of every node. When a pod is assumed, scheduled, or deleted, a watch based update is made upon the cache. 

I think the caching you're proposing doesn't cause any new problems to multiple-scheduler configuration (in the current code without a cache, with multiple schedulers the new pod can be bound by scheduler A in between scheduler B doing List and doing work on the result), but it's worth thinking about.

ref/ #18745

**Comment by davidopp** [comment]
Actually it's not the same as #18745; #18745 is about multiple schedulers scheduling the same pod at the same time, but my concern here is multiple scheduler scheduling different pods onto the same node at the same time. Kubelet will detect conflict anyway, so it is not a correctness problem, just maybe an increase in conflicts.

**Comment by hongchaodeng** [comment]
Hi @davidopp , Thanks for your comments.

The concern exist today without my changes. The optimistic scheduling will bring conflicts in one manner or the other. I'm not trying to make a tradeoff here. The changes proposed is just trying to make the existing cache more efficient.

**Comment by davidopp** [comment]
Yeah I was just thinking it might increase the rate of conflicts, if the cache replaces re-listing, so that the scheduler uses data that is less fresh when making scheduling decisions. It's not a reason to not make the change you suggested, but something to watch out for once we have multiple schedulers.

**Comment by timothysc** [comment]
@hongchaodeng Where is the PR on this one?

**Comment by davidopp** [comment]
It seems that a simple way to speed up `PodFitsHostPorts()` is to change it to something like this:
```
wantPorts := getUsedPorts(pod)
if len(wantPorts) == 0
    return true, nil
existingPorts := getUsedPorts(existingPods...)
for wport := range wantPorts {
[... rest of function as-is ...]
```

I think that's probably sufficient. The vast majority of pods will not request a hostPort.

**Comment by hongchaodeng** [comment]
@davidopp 
I agree with you that's gonna speed up both of benchmark and kubemark results.
Some realistic scenarios would be much better to back up the argument. Since we can't be sure on this, keeping it simple as you suggested looks good to me.

**Comment by davidopp** [comment]
Removing from 1.2 milestone, adding to next-candidate.

If we can hit our 1000 node scaling goals without this change, then we do not need it for 1.2.

**Comment by timothysc** [comment]
@hongchaodeng can we close this now?

**Comment by wojtek-t** [comment]
In fact there are already some things that are not solved here (e.g. spreading priority is O(pods)). But I'm fine with closing this one and filing separate issues for such things.
