### ISSUE TITLE
rkt pods stay in pending for a long time

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#18841]
For some reason, the rkt pod's state stays in `pending` for a while even it's already started and running. Needs investigation. 
```
$ kubectl get events
FIRSTSEEN   LASTSEEN   COUNT     NAME      KIND      SUBOBJECT                REASON      SOURCE                MESSAGE
36s         36s        1         nginx     Pod                                Scheduled   {scheduler }          Successfully assigned nginx to 127.0.0.1
35s         35s        1         nginx     Pod       spec.containers{nginx}   Pulled      {kubelet 127.0.0.1}   Container image "nginx" already present on machine
32s         32s        1         nginx     Pod       spec.containers{nginx}   Created     {kubelet 127.0.0.1}   Created with rkt id 1ffeb0be
32s         32s        1         nginx     Pod       spec.containers{nginx}   Started     {kubelet 127.0.0.1}   Started with rkt id 1ffeb0be
yifan@yifan-coreos:~/gopher/src/k8s.io/kubernetes$ kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
nginx     0/1       Pending   0          43s
```

Afther a while 
```
yifan@yifan-coreos:~/gopher/src/k8s.io/kubernetes$ kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
nginx     1/1       Running   0          1m
```

/cc @yujuhong

**Comment by yujuhong** [comment]
When kubelet first syncs the pod, it should
 1. create and start all containers
 2. generate the status

It seems that for `rkt`, the containers are still not considered running at step (2). Because kubelet syncs every minute now, it'd wait until the next sync to generate the status again. We should figure out why the containers are not considered running at the time.

**Comment by yifan-gu** [comment]
After oob discussion, we think this should be mitigated once #19436 is merged

/cc @sjpotter

**Comment by yujuhong** [comment]
This should be fixed now. @yifan-gu can you verify? Thanks.

**Comment by yifan-gu** [comment]
@yujuhong Yes, this issue is fixed, thanks :)
