### ISSUE TITLE
Clarify INSTANCE_PREFIX and KUBE_GCE_INSTANCE_PREFIX in e2e.sh

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18849]
Right now we set `KUBE_GCE_INSTANCE_PREFIX` separately from `INSTANCE_PREFIX` (which we set to `E2E_CLUSTER_NAME`), but in `cluster/gce/config-default.sh` and `cluster/gce/config-default.sh` `INSTANCE_PREFIX` gets overwritten with `KUBE_GCE_INSTANCE_PREFIX` anyway.  We should just have `KUBE_GCE_INSTANCE_PREFIX` set as `CLUSTER_NAME` and never touch `INSTANCE_PREFIX` at all in `e2e.sh`.

cc @spxtr in case you care.

**Comment by ihmccreery** [comment]
xref #18852

**Comment by ihmccreery** [comment]
Assigning to @spxtr since you've expressed interest in cleaning up `e2e.sh`.

**Comment by ihmccreery** [comment]
`KUBE_GCE_INSTANCE_PREFIX` was introduced in #3056.

**Comment by fejta** [comment]
e2e.sh no longer exists

**Comment by spxtr** [comment]
e2e.sh no longer exists, but there are still plenty of confusing environment variables that we ought to consolidate. Ike made a good step at this with his e2e.sh refactor before YAMLification, but it's still not great.

That can be a future issue, though.
