### ISSUE TITLE
Scheduler should use node `Allocatable` instead of `Capacity`

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#18848]
We added a new field to `NodeStatus`: `Allocatable`. Allocatable represents the *schedulable* resources on a node, while capacity is the total resources on a node (including resources claimed by non-k8s workloads, such as kernel usage, container runtime, and other native processes). More details here: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/node-allocatable.md

`Allocatable` [defaults](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/defaults.go#L202) to `Capacity` when not set, so this change will be backwards compatible with Kubelets that don't set `Allocatable`.

/cc @dchen1107 @davidopp

**Comment by davidopp** [comment]
@resouer Would you be interested in working on this?

**Comment by resouer** [comment]
@davidopp It's interesting, I'm in :)

**Comment by resouer** [comment]
And I can see on node side, #18611 is closely related and hopefully to be merged.

**Comment by timstclair** [comment]
@resouer - Yes, https://github.com/kubernetes/kubernetes/pull/18611 is the node side, but it should not block this issue (in fact it needs to not block it, in order to correctly handle version skew). As mentioned above, `Allocatable` is defaulted to `Capacity`, so just using allocatable will default to the current behavior. Just wanted to make sure that was clear :)

**Comment by davidopp** [comment]
@resouer do you have an update on your progress on this issue?

**Comment by davidopp** [comment]
Oh sorry, just noticed the PR. That's what happens when I go on vacation. :)
