### ISSUE TITLE
Integration flake: runReplicationControllerTest flake

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#18857]
Log here: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/324de120b7f3152cf68a61aed66d02ca9f63433f/kubernetes-pull-test-unit-integration/6475/

```
F1217 18:45:56.333708   11378 integration.go:469] FAILED: pods never started running timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:57
```

**Comment by davidopp** [comment]
I'm going to close this, please reopen when it recurs and we can look at the additional logging info.
