### ISSUE TITLE
Admission control settings don't match in gce for config-default.sh and config-test.sh

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#18851]
SecurityContextDeny is [enabled by default](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L116) when we run e2e tests but as of https://github.com/kubernetes/kubernetes/pull/16986 is has been removed from the admission control plugins in [config-default.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L110). 

This means that our e2e tests aren't testing representative clusters that would be created by users running `./cluster/kube-up.sh`.

/cc @pmorie @ArtfulCoder

**Comment by ixdy** [comment]
I'm not really sure what this setting does - should we just remove it for e2e tests?

**Comment by roberthbailey** [comment]
Me neither, but the change to the GCE environment hasn't been mirrored anywhere else that I can see. This admission control is still enabled in [AWS](https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/config-default.sh#L129), [Vagrant](https://github.com/kubernetes/kubernetes/blob/master/cluster/vagrant/config-default.sh#L56), [Kubemark](https://github.com/kubernetes/kubernetes/blob/master/cluster/kubemark/config-default.sh#L76), [Ubuntu](https://github.com/kubernetes/kubernetes/blob/master/cluster/ubuntu/config-default.sh#L38), etc. 

I don't understand a) why GCE is now being treated differently, and b) why it isn't mirrored in our e2e tests.

**Comment by ArtfulCoder** [comment]
we should not have securitycontextdeny in our e2e tests.
I thought we dont have it in e2e tests because I have a e2e test that expilictly ensures that privileged pods that have security context are allowed
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/privileged.go#L117

**Comment by roberthbailey** [comment]
It sounds like we first need to find out why that e2e test is passing, cause it to fail, and then fix the admission controllers so that it passes again. Likewise on GKE.

**Comment by ArtfulCoder** [comment]
My suspicion is that the cluster does not have the SecurityContextDeny...

**Comment by roberthbailey** [comment]
Looks like we never tracked this down, but I've sent #21004 to remove the admission controller from test clusters.

**Comment by roberthbailey** [comment]
@ArtfulCoder do you have any spare cycles to try and diagnose why that test is passing before approving my PR?

**Comment by ArtfulCoder** [comment]
diagnosed the test passing mystery https://github.com/kubernetes/kubernetes/pull/21004#issuecomment-186004952
