### ISSUE TITLE
Proposal for kubelet version reconciliation utility

### ISSUE THREAD

**Issue by pbx0** [kubernetes/kubernetes#18872]
Currently, CoreOS, is planning to ship the kubelet via a container to avoid having the kubelet version pinned to our OS release. We 'd like the kubelet version be based on the api-server version or user specified.

This is being implemented as a service file that runs a utility to determine, in a best-effort approach, the latest safe version of a kubelet to run by attempting to contact an api-server. The version is then reconciled against available kubelet container versions such that the kubelet version is less then or equal to the api-server and within the same major release. Then the correct kubelet image is pulled and run. 

In our case we use reconcile against the available version tags from a given Appc Image URL such as `coreos.com/kublet:<tag>`.

Would there be interest in creating this utility as an upstream kubernetes binary?

**Comment by philips** [comment]
One nice extension would be having the node object hold on to the version of the kubelet that should run. Then the node could boot, check itself on the k8s node API, and download and run the correct version of the kubelet. Having this metadata on node would also open the potential for having a rolling update policy on the kubelet versions.
