### ISSUE TITLE
Guestbook vagrant EXTERNAL_IP issue

### ISSUE THREAD

**Issue by Bretto** [kubernetes/kubernetes#18884]
Sorry for the newbie question but could someone explain how to setup the external Ip on the  'frontend' service. I know that Vagrant don't support "type: LoadBalancer" and I don't know how to expose an Ip to my host. Thanks

**Comment by ebreton** [comment]
Same question here. I have found some hint about using ingress in that matter, but nothing close to a tutorial, not mentioning adapted to this example :)

**Comment by kargakis** [comment]
Please use other channels found in https://github.com/kubernetes/community/blob/master/communication.md for support-related questions.
