### ISSUE TITLE
Corrupt TCP packets can be delivered to applications due to a veth driver bug

### ISSUE THREAD

**Issue by evanj** [kubernetes/kubernetes#18898]
*Summary*: when packets are routed from hardware to a veth device (like Kubernetes does), the veth device marks them as "checksum good". If those packets are corrupt, applications inside containers will receive corrupt data, instead of discarding them.

This is caused a [bug in the Linux kernel we are trying to get patched](http://thread.gmane.org/gmane.linux.kernel/2111961). We were [impacted by this bug at Twitter, on Mesos](https://issues.apache.org/jira/browse/MESOS-4105). In investigating it, we discovered that Kubernetes is also affected. 

*Workaround*: Kubernetes should disable rx checksum offloading on veth devices by invoking `ethtool -K eth0 rx off` when creating containers.

How to reproduce the bug on Google Container Engine:

1. Create a new cluster using Google Container Engine.
2. Create a container running something, so it gets its own IP address.
3. Connect to the container's host, and run netcat inside the new container: `docker exec -ti (container id) nc -l -p 12345`
4. Start a separate virtual machine in Google Compute Engine.
5. Copy my tcpping tool to the virtual machine: https://gist.github.com/evanj/4329312f5e27fd34ba90
6. On the new VM, run `./tcpping (container ip):12345`
7. You should see a sequence of "aaaaa 0", "aaaaa 1" etc.
8. On the VM, start corrupting all packets for 10 seconds with: `sudo tc qdisc add dev eth0 root netem corrupt 100%; sleep 10; sudo tc qdisc del dev eth0 root netem`
9. You should now see a sequence of messages with corruption appear for 10 seconds.
10. Turn of rx checksumming with `docker exec -ti (container id) ethtool -K rx off`
11. Repeat the experiment, you should now see the messages "pause" until the corruption is turned off, at which point the entire batch of messages will appear at once after they are retransmitted.

*Note*: I believe that Container Engine isn't *really* affected by this, since packets from the outside need to go through a load balancer, which drops corruption (tested). I also suspect Google Compute Engine runs some virtual overlay network, so even for internal packets, there is likely another layer of checksums between the bits on the wire and the application that will hopefully drop packets.

However, others probably are hoping to run Kubernetes on real hardware, and this bug will be in old kernel versions for a long time, so this workaround is probably required.

**Comment by evanj** [comment]
Upon further consideration, since I think Kubernetes relies on Docker to create containers (I think?), this probably needs to be fixed in Docker itself? I filed https://github.com/docker/docker/issues/18776 ; I'd love help getting someone's attention on it. Thanks!

**Comment by brendandburns** [comment]
@evanj yes, I think that this is exclusively a Docker bug.  We're happy to work around it in Kubernetes, but getting it fixed in Docker and in the kernel seems like the right solution.

**Comment by evanj** [comment]
Sounds reasonable to me. Apologies for the spam, but I'd love help getting the right people involved in Docker and/or the kernel to actually pay attention for this. Thanks! Marking as closed.

**Comment by thockin** [comment]
I chimed in on the Docker side.  If this doesn't land in docker.next, we can workaround in kube.
