### ISSUE TITLE
Usage of nss-switch for kubernates service name resolution

### ISSUE THREAD

**Issue by smil2k** [kubernetes/kubernetes#18911]
Hi All,

I'm just wondering whether anybody toyed with the idea already to use nss-switch to provide the DNS records for the services? 

It seems to me that running a DNS server internally and updating / configuring it everywhere seems to be a bigger job than creating s small NSS hosts backend which connects kubeproxy and asks for the service Ip.

What do you think?

Cheers,

Tamas

**Comment by thockin** [comment]
Unless you mean something else - nss just provides a handful of facilities
(and some config to prioritize between them) for name resolution.  The most
common cases being dns and /etc/hosts.

Are you talking about using /etc/hosts instead of DNS?  See teh Docker
debacle (which is still not solved in 1.9) regarding /etc/hosts.

**Comment by smil2k** [comment]
AFAIK nssswitch is used in order to define how "gethostbyname" does the name resolution (and other calls like users, groups etc...) 

It is fully modular, "files" and "dns" is only an SO file loaded dynamically under /lib, they provide certain functionalty.

This a new module could be introduced "k8s", which tries to lookup in kubeproxy first and then in files/dns. IPs within the SDN is meaningless outside of the cluster anyhow...

ps.
Can you give me some pointers for the docker hosts debacle?

**Comment by thockin** [comment]
libnss is a library - for us to use that, we'd have to force every
container to use our library, which is a non-starter.

That aside, read over https://github.com/docker/docker/issues/17190 for a
sense of why manipulating files in a user's container is a really hard
problem and a bad idea :)

**Comment by smil2k** [comment]
Hi,

I'm not talking about LibNSS! (https://en.wikipedia.org/wiki/Network_Security_Services)

/etc/nsswitch.conf is a part of libc! Every application which uses glibc is using  /etc/nsswitch.conf!
(http://man7.org/linux/man-pages/man5/nsswitch.conf.5.html)
Even static programs load dynamic libraries if they are using gethostbyname!
(http://stackoverflow.com/questions/15118408/compile-c-with-function-gethostbyname-to-static-linked-error)

Actually the /etc/hosts file is red by the "files" is plugin (/lib/x86_64-linux-gnu/libnss_files-2.19.so provided by libc6), so what I propose it to create a k8s plugin which interacts with the kubeproxy or any registry which contains the service ips.

This could be a solution for docker also. I think it is less work than integrating a DNS server and far more safer than rewriting hosts files...

Cheers,

Tamas

**Comment by thockin** [comment]
nsswitch is what I meant.

Not every app uses glibc.  Not every container has glibc present.  Not
every container wants us mucking with their internals.  Also, if we did
this we have to deal with a variety of library versions, which is
thoroughly unattractive.  On top of that, manipulating files that the user
can see across namespace boundaries is very ugly - as documented and n the
/etc/hosts debacle.

I think you over estimate how hard DNS is and underestimate how
hard/incomplete a shared lib is.  I appreciate your idea and zeal but this
is not something we want to do.

Tim
