### ISSUE TITLE
unit flake: pkg/storage/etcd is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18929]
=== RUN   TestWatch
--- FAIL: TestWatch (0.03s)
	etcd_watcher_test.go:269: An injected error did not cause a graceful shutdown

@timothysc 

I will take a look on Monday.

**Comment by timothysc** [comment]
This is weird, I literally ran the test dozens of times and never saw a flake.

**Comment by timothysc** [comment]
So I think there is subtle issues in the test around timing that I'm just not seeing locally.  A quick fix is to either sleep or forcing a Gosched to allow the other goroutines to cleanup prior to the check.

**Comment by wojtek-t** [comment]
This should also be fixed by #18956
