### ISSUE TITLE
Return a "disabled" message for extension APIs that are turned off.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#18924]
Right now, if an extension api (e.g. DaemonSet) is disabled, we return 404 and not much other info.  While this is legal, it doesn't give a great user experience.  We should return the 404, but also a message indicating how to activate the API.  e.g. a JSON status message that says "inactive" or something like that.

**Comment by jayunit100** [comment]
yup, any kube endpoint should be understandable by the apiserver, even if apiserver has to say "you disabled this feature!".  Thanks for creating this issue it will save a lot of documentation maintainance headaches !

**Comment by lavalamp** [comment]
Unfortunately, this is a lot harder than it sounds, as things are turned off long before the paths that go into go-restful are generated.

**Comment by jayunit100** [comment]
hmmm.... maybe, at least, 
- there could be a set of fields that could be shipped somewhere so that debug info for apiserver was returned alongside a 404 that happens.  
- but maybe that might be too indirect to be useful ...

**Comment by liggitt** [comment]
I don't think instructions to the cluster admin belong in API responses

The discovery doc use in kubectl makes the response more reasonable (indicates the kind is not available on that server)
