### ISSUE TITLE
Metrics do not get registered correctly for 4xx and 5xx HTTP requests

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#18920]
Repro:

1. Start up a kube cluster.
2. Make some API calls that result in 404 (e.g. http://apiserver/aaa or http://apiserver/api/v1/pods/aaa) or 503 (kill etcd and make some API calls).
3. Visit http://apiserver/metrics.

Expected behavior: The metrics that have a "code" tag (e.g. apiserver_request_count and rest_client_request_status_codes) should have lines referring to code="404" or code="503".
Actual behavior: No such lines exist. Only code="200" lines exist.

Happening at HEAD (730a6a1d). This is currently blocking us from monitoring and alerting on 5xx errors.

**Comment by bgrant0607** [comment]
cc @a-robinson

**Comment by a-robinson** [comment]
Thanks for finding this @bgrant0607, this is a nasty regression. I haven't looked at the API code in quite some time now, but I'm not shocked that some sort of refactoring broke this. Sticking into the 1.2 milestone, I can't imagine it's that nefarious of a cause.

**Comment by davidopp** [comment]
This is marked as 1.2 milestone but has no assignee.

**Comment by lavalamp** [comment]
@wojtek-t you were just saying something about this to me this morning.

**Comment by wojtek-t** [comment]
Sorry, I missed this - this is a duplicated of #16421
And actually was fixed by #19559
