### ISSUE TITLE
Spark Example - Incorrect worker hostPort property

### ISSUE THREAD

**Issue by itsjimbo** [kubernetes/kubernetes#18937]
Following the example for
http://kubernetes.io/v1.1/examples/spark/README.html

The worker-controller json file
http://kubernetes.io/v1.1/examples/spark/spark-worker-controller.json
 
Utilizes  "hostPort": 8888 which is incorrectly specified, this should be removed as all the replicas started will try to occupy the port 8888 (unless you change replicas: 1). After following the example and using kubectl get pods, only 1 worker will have been started.  The others will fail with the reason below.

```
kubectl get events
```

```
Failed for reason PodFitsHostPorts and possibly others
```

**Comment by bgrant0607** [comment]
cc @zmerlynn

**Comment by zmerlynn** [comment]
This example has been completely rewritten in `master` (1.2), see https://github.com/kubernetes/kubernetes/tree/master/examples/spark, and the Docker image sources have been moved to https://github.com/kubernetes/application-images/tree/master/spark as well.

**Comment by bgrant0607** [comment]
This is working in HEAD, so closing.
