### ISSUE TITLE
Generated client files should not have mixed case

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#18939]
We do not use mixed case filenames in our codebase - a few have cropped up as part of generation `pkg/client/types/generated/unversioned/componentStatus.go` that should be nixed.  They should be `componentstatus.go` or `component_status.go`.  coding-conventions.md should be updated to call this out explicitly, which I will do in a separate PR.

@caesarxuchao @lavalamp @krousey not sure who is active in the generator right now

**Comment by caesarxuchao** [comment]
I'll fix it. Thanks for catching that.

On Sunday, December 20, 2015, Clayton Coleman <notifications@github.com>
wrote:

> We do not use mixed case filenames in our codebase - a few have cropped up
> as part of generation
> pkg/client/types/generated/unversioned/componentStatus.go that should be
> nixed. They should be componentstatus.go or component_status.go.
> coding-conventions.md should be updated to call this out explicitly,
> which I will do in a separate PR.
>
> @caesarxuchao <https://github.com/caesarxuchao> @lavalamp
> <https://github.com/lavalamp> @krousey <https://github.com/krousey> not
> sure who is active in the generator right now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/18939>.
>


-- 
Regards,
Chao Xu

**Comment by smarterclayton** [comment]
Documented in https://github.com/kubernetes/kubernetes/pull/18942

**Comment by lavalamp** [comment]
I don't see that file any more-- @caesarxuchao did you change it? If so just close this. Thanks!
