### ISSUE TITLE
Missing allow-privileged flag for juju provider

### ISSUE THREAD

**Issue by fgimenez** [kubernetes/kubernetes#18931]
In the apiserver and kubelet upstart templates for juju the `--allow-privileged` flag is missing.

I've prepared this branch [1] with a fix, let me know if I should submit the PR

Thanks! :)

[1] https://github.com/kubernetes/kubernetes/compare/master...fgimenez:juju-allow-privileged?expand=1

**Comment by fabioy** [comment]
Please submit your changes as a pull request (PR) to be reviewed. Thanks.

**Comment by fgimenez** [comment]
@fabioy done, it's #19326

Thx! :)
