### ISSUE TITLE
e2e flake: Deployment deployment should create new pods

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18943]
Example failure:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/21458/

@nikhiljindal @janetkuo 

@nikhiljindal - can you please take a look?

**Comment by wojtek-t** [comment]
One more instance:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/21523/#

**Comment by nikhiljindal** [comment]
Could be due to https://github.com/kubernetes/kubernetes/pull/17398.
@janetkuo Can you please take a look?

**Comment by nikhiljindal** [comment]
cc @ironcladlou @kargakis

**Comment by kargakis** [comment]
I cannot access any of those links. Can somebody post the output that indicates the failure here?

**Comment by nikhiljindal** [comment]
First failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:35
Expected error:
    <*errors.errorString | 0xc208b6d2e0>: {
        s: "Pod name nginx: Gave up waiting 2m0s for 1 pods to come up",
    }
    Pod name nginx: Gave up waiting 2m0s for 1 pods to come up
not to have occurred
```
Second:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:35
Expected error:
    <*errors.errorString | 0xc20849f3b0>: {
        s: "failed to wait for pods running: [gave up waiting for pod 'nginx-deployment-2nxmk-k9gma' to be 'running' after 5m0s]",
    }
    failed to wait for pods running: [gave up waiting for pod 'nginx-deployment-2nxmk-k9gma' to be 'running' after 5m0s]
not to have occurred
```

**Comment by janetkuo** [comment]
I'm OOO and will be back on Jan 5. I don't have my laptop with me at this
moment. I'll look at this when possible.

Janet

On Wed, Dec 23, 2015 at 7:58 AM Nikhil Jindal <notifications@github.com>
wrote:

> First failure:
>
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:35
> Expected error:
>     <*errors.errorString | 0xc208b6d2e0>: {
>         s: "Pod name nginx: Gave up waiting 2m0s for 1 pods to come up",
>     }
>     Pod name nginx: Gave up waiting 2m0s for 1 pods to come up
> not to have occurred
>
> Second:
>
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:35
> Expected error:
>     <*errors.errorString | 0xc20849f3b0>: {
>         s: "failed to wait for pods running: [gave up waiting for pod 'nginx-deployment-2nxmk-k9gma' to be 'running' after 5m0s]",
>     }
>     failed to wait for pods running: [gave up waiting for pod 'nginx-deployment-2nxmk-k9gma' to be 'running' after 5m0s]
> not to have occurred
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/18943#issuecomment-166756698>
> .
>
-- 
Best,
Janet Kuo

**Comment by janetkuo** [comment]
Related issue for "failed to wait for pods running" error: #17931

**Comment by janetkuo** [comment]
We've seen this error before #17398.

**Comment by janetkuo** [comment]
Failed 4 times in the latest 385 tests (1%) in kubernetes-pull-build-test-e2e-gce. All related to "failed to wait for pods running". Closing this issue since #17931 will take care of this error in all e2e tests.
