### ISSUE TITLE
e2e fail: Services should be able to change the type and nodeport settings of a service

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18953]
It constantly fails on gke-test and gke-1.1:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-test/10906/

```
Services should be able to change the type and nodeport settings of a service

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:585 Expected error: <*errors.errorString | 0xc20864f5f0>: { s: "service mutability-service-test in namespace e2e-tests-services-vx02g doesn't have a LoadBalancer ingress point after 1200.00 seconds", } service mutability-service-test in namespace e2e-tests-services-vx02g doesn't have a LoadBalancer ingress point after 1200.00 seconds not to have occurred
```

@kubernetes/goog-gke 
@ihmccreery please reassign

**Comment by gmarek** [comment]
I cleaned up the project to bring it down below quota again. This needs to be monitored.

**Comment by ihmccreery** [comment]
> I cleaned up the project to bring it down below quota again. This needs to be monitored.

Am I inferring correctly that we ran out of static IP address quota in the project?

Reassigning to @fejta as this falls squarely inside his projects-as-cattle project.

**Comment by goltermann** [comment]
This is a P0 flaky test - can we either prioritize and fix, or change priority?

**Comment by ihmccreery** [comment]
I'll see what I can do.

**Comment by ihmccreery** [comment]
We currently `FAIL_ON_GCP_RESOURCE_LEAK` for this suite, so I don't think there's much more we can do until #18119 is fixed.  Closing.
