### ISSUE TITLE
AWS - EC2 API DescribeInstances outage brought down clusters in region

### ISSUE THREAD

**Issue by willmore** [kubernetes/kubernetes#18955]
On `2012.12.18` the AWS region us-east-1 experienced an outage affecting service of the DescribeInstances and DescribeTags APIs. This is turn brought our two independent clusters operating in the region, as [the Kubelet AWS clustering mechanisms](https://github.com/kubernetes/kubernetes/blob/7069a811164f68473dd1b94ee2b2abc169e35d81/pkg/cloudprovider/providers/aws/aws.go#L2100-L2119) rely on the DescribeInstances API. Networking was unaffected - master and nodes could still communicate without problem.

I propose that this AWS failure should not bring down a cluster.

The relevant Kubelet log message:
>Error updating node status, will retry: failed to get node address from cloud provider: no instances found for name: ip-*-*-*-*.ec2.internal

There are several issues that relate to this functionality. I am filing this issue to ensure that Kubernetes is not needlessly vulnerable to this type of outage.

*Possibly Related*
#17643 use private ip instead of local hostname for AWS
#18525 We shouldn't use node names as addresses

Incident details from http://status.aws.amazon.com/
>1:02 PM PST We are investigating elevated latencies and error rates for the DescribeInstances and DescribeTags APIs in the us-east-1 region. Customers may observe elevated error rates or missing tags for instances in the AWS Management Console.
1:44 PM PST We have identified the root cause of elevated latencies and error rates for the DescribeInstances and DescribeTags APIs and are currently working to resolve. Customers may observe elevated error rates or missing tags for instances in the AWS Management Console.
3:03 PM PST Between 12:30 PM and 2:44 PM PST, we experienced elevated latencies and error rates for the DescribeInstances and DescribeTags APIs. During this period, customers may have observed elevated error rates and missing tags for instances in the AWS Management Console. During this event, instances continued running normally. Tags requested during this period are now visible. This issue has been resolved and the service is operating normally.

**Comment by bgrant0607** [comment]
cc @justinsb

**Comment by iterion** [comment]
This happened to our cluster as well. Once the API failed master saw nodes as unavailable and kubelet shut down all of the pods on each node.

**Comment by davidopp** [comment]
@brendandburns

**Comment by davidopp** [comment]
#16593 ?

**Comment by willmore** [comment]
>#16593 ?

Yes - I strongly believe this is the same issue as #16593.
The fix appears to be in #16641.

Closing as a duplicate.
