### ISSUE TITLE
e2e fail: Services should serve identically named services in different namespaces on different load-balancers

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18952]
This test reliably fail on gke-test and gke-1.1: 
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-test/10906/

```
Services should serve identically named services in different namespaces on different load-balancers

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:861 Expected error: <*exec.ExitError | 0xc20875eee8>: { ProcessState: { pid: 24780, status: 256, rusage: { Utime: {Sec: 0, Usec: 244000}, Stime: {Sec: 0, Usec: 48000}, Maxrss: 32832, Ixrss: 0, Idrss: 0, Isrss: 0, Minflt: 18289, Majflt: 0, Nswap: 0, Inblock: 0, Oublock: 48, Msgsnd: 0, Msgrcv: 0, Nsignals: 0, Nvcsw: 59, Nivcsw: 25, }, }, } exit status 1 not to have occurred
```

@kubernetes/goog-gke 
@ihmccreery please reassign.

**Comment by gmarek** [comment]
I cleaned up the project to bring it down below quota again. This needs to be monitored.

**Comment by ihmccreery** [comment]
> I cleaned up the project to bring it down below quota again. This needs to be monitored.

Am I inferring correctly that we ran out of static IP address quota in the project?

Reassigning to @fejta as this falls squarely inside his projects-as-cattle project.

**Comment by gmarek** [comment]
We run also out of networks, firewall rules, backend services and target pools.

**Comment by ihmccreery** [comment]
Note that this test is in the parallel-flaky suite, and after #19021 is merged, it will simply be `[Flaky]`.  It should be cleaned up and moved out of that suite, or added to the `[Disruptive]` or `[Serial]` labels.

**Comment by goltermann** [comment]
This is a P0 flaky test - can we either prioritize and fix, or change priority?

**Comment by ihmccreery** [comment]
I'll see what I can do.

**Comment by ihmccreery** [comment]
We currently `FAIL_ON_GCP_RESOURCE_LEAK` for this suite, so I don't think there's much more we can do until #18119 is fixed.  Closing.

**Comment by ihmccreery** [comment]
"Services should serve identically named services in different namespaces on different load-balancers" is still marked as `[Flaky]` at HEAD.  I will send a PR to close this.

**Comment by ihmccreery** [comment]
This test is still failing in the `-flaky` suites, due to out-of-quota for static addresses.  I cleaned up the quota and will monitor (there are 4 addresses in the project `k8s-jkns-e2e-gce-flaky` as of now).

**Comment by ihmccreery** [comment]
Also with #20098 in, if this test seems to be going well for a couple of days, I'll promote it out of `[Flaky]`.

**Comment by thockin** [comment]
I don't see how this test could ever pass - the test itself seems deeply broken.

**Comment by thockin** [comment]
dup of  #16285
