### ISSUE TITLE
e2e flake: Services should work after restarting kube-proxy

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18958]
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/10042/

expected to retrieve pods
     [service1-48igt service1-57dir service1-i1ojq],
only retrieved
    [service1-i1ojq service1-i1ojq service1-48igt service1-i1ojq service1-48igt service1-48igt service1-i1ojq service1-48igt service1-48igt] 

@thockin

**Comment by wojtek-t** [comment]
Maybe with ip-tables based kube-proxy, we should increase the number of tries to connect to pods?

Currently, we are doing 3*#pods tries:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/service.go#L1339

maybe it's to few now?

@thockin - WDYT?

**Comment by gmarek** [comment]
cc @kubernetes/goog-gke
