### ISSUE TITLE
kubectl run --env parsing naive

### ISSUE THREAD

**Issue by romanmandryk** [kubernetes/kubernetes#18964]
I'm running application with several env variables. One of them has a key ending with ==. Another variable has a comma separated list of email addresses. While perfectly valid on *nix and windows, we can't pass these values into Kubernetes run command. It fails with "error: invalid env:"

Example command:
`kubectl run MyApp --env="THIS_ENV=isOK" --env="HAS_COMMAS=foo,bar" --env="HAS_EQUALS=jJnro54iUu75xNy==" `

The parsing in https://github.com/kubernetes/kubernetes/blob/51e8c2e5f8075b6a200f3fb4e06446cda27e2c4e/pkg/kubectl/run.go#L593 should be more robust

**Comment by mqliang** [comment]
@mikedanese I volunteer myself to fix this.

**Comment by holms** [comment]
Maybe they can be passed from file? I mean s'rsly.. you need to lits 20 variables by hand?? I've specified them in yaml file already, but kubectl-run have no way to specify it.. without this, deployment is totally impossible when you need to run migrations first!
