### ISSUE TITLE
Kubelet exec network plugin calls Setup Pod and TearDown pod in any order

### ISSUE THREAD

**Issue by ssergiienko** [kubernetes/kubernetes#18967]
Kubelet exec network plugin calls Setup Pod and TearDown pod in any order. This breaks logic, when Teardown is called for pod before this pod actually created (Setup not called at this moment).

More over sometimes Teardown even not called at all. When we create|delete pod fast - setup is called but Teardown - no.

We have made 3(!) workarounds to accomplish what we need.

Expected behaviour:
1. If Setup called then Teardown must be called too, in any case.
2. Setup always needs to be called before Teardown, not in reverse order as in some cases.

**Comment by AdoHe** [comment]
@ssergiienko what version you are using? and what tests you did? You know kubernetes is asynchronous and eventually consistent, I also did some tests and print out some logs from my test plugin, I think the test result is strange. I am not sure whether this is a bug for kubelet, next I will hack the kubelet and add some logs to the kubelet main loop.

**Comment by ssergiienko** [comment]
@AdoHe Kubernetes 1.0.3
If by "what tests you did?" you mean "how to reproduce this" then this is easy - create some RC via kubectl and then delete it... many times in loop with very little delay (we do this with our web-interface start|stop button).

I know that this is due asynchronous nature of kubernetes but if some events in pod lifecycle are lost then this is bug.

Let's assume that in Setup Pod we will do `ip addr add SOME_IP` and in TearDown Pod `ip addr del SOME_IP`, then if Teardown came faster then Setup - we break node's networking, etc.

**Comment by AdoHe** [comment]
@ssergiienko I know what you mean. Just like `calico` kubernetes plugin, if the `setup` `teardown` order is not guaranteed, there may be some network sources leak. I will add more logs to kubernetes main loop and try to reproduce this issue.

**Comment by ssergiienko** [comment]
@AdoHe Yes, `if the setup teardown order is not guaranteed` - this is the most annoying issue. And if Teardown is absent at all - it's wrong too, but it's easier to workaround.
Anyway, Thanks for help!

**Comment by AdoHe** [comment]
@ssergiienko Based on the latest kubernetes, I did more tests. First I use this script to do pod creation and deletion:
```
#!/bin/bash

for (( i=1; i<=10; i++ ))
do
  kubectl create -f /root/pods/busybox.yaml
  kubectl delete -f /root/pods/busybox.yaml
  sleep 15
done
```
Then I write a custom network plugin, add some log sentences to `setup`, `teardown` commands. I also add extra logs to `kubelet`, especially the `podStorage` <b>merge</b> method, `DockerManager` <b>SyncPod</b> <b>KillPod</b> methods. From the test result, I think the `setup`, `teardown` are executed in order. And also the `teardown` method will get executed. Below  is the explanation: First, `kubelet` will get pod updates in order, this is guaranteed by api-server(which use etcd watch). The `kubelet` main loop will handle all kinds of pod updates. The handler will call the `DockerManager` methods(which is the container runtime if you use docker). The `DockerManager` will compute pod containers change every time you sync pod, and if needed to create the <b>infra</b> container for this pod, the container runtime will call the network plugin `setup` method. For the pod deletions, the `podKiller` will call the runtime `KillPod` method and in this method, the network plugin `teardown` get called. For every pod deletion, if there is no running pod in the `runtime cache`, the `podKiller` do nothing. So the teardown will not get called.
I just hope this will help you, if any problem, we can have a discussion.

**Comment by ssergiienko** [comment]
Looks like should be fixed with https://github.com/kubernetes/kubernetes/issues/14940
