### ISSUE TITLE
Questions regarding HPA

### ISSUE THREAD

**Issue by sachingharge** [kubernetes/kubernetes#18976]
Hello Team,

I have few questions regarding HPA (Horizontal pod autoscaling) on CoreOS/AWS.

1. I noticed that when you create HPA for particular replication controller which don't have resources defined then current CPU column always displayed "Waiting" after even waited for longer time. Is that correct behaviour?

2. When I defined resources as stated below for one of the replication controller and create HPA for it then it shows the current CPU utilization value in CPU column.
        resources:
          requests:
            cpu: 200m

3. Do you some practices to define resources as it is hard to find out how much resources to define for particular replication controller? Please share some practices to define appropriate resources for replication controller.
On nodes, we have 2 Core CPU and 4GB RAM.

4. By mentioning below resources to begin, I could able to verify HPA scale up and down based on requests.
        resources:
          requests:
            cpu: 200m

5. Do we need define limits in resources as well?

We would like to go with production for this setup but need to figure out appropriate resources mapping for replication controller.

Please let me know your inputs/suggestions on this or feel free to ask if you need any more information on this.

Thanks!

**Comment by mikedanese** [comment]
cc @mwielgus @jszczepkowski since maybe we should add documentation

**Comment by ncdc** [comment]
cc @DirectXMan12

**Comment by DirectXMan12** [comment]
> I noticed that when you create HPA for particular replication controller which don't have resources defined then current CPU column always displayed "Waiting" after even waited for longer time. Is that correct behaviour?

Yes -- the target for CPU autoscaling is "percentage of CPU request", so if there are no CPU request values defined on your pods, the HPA controller will fail to calculate the scaling factor.

> Do we need define limits in resources as well?

Limits are not needed for horizontal pod autoscaling.  The target value for CPU-based autoscaling is specified as a percentage of the CPU request.  This is then compared to the actual CPU being used to determine a scaling factor.  For example, if you specified 50%, and your request was 200m, then the HPA would compare the current CPU usage to 100m to figure out a scaling factor.

**Comment by sachingharge** [comment]
@DirectXMan12 
Okay, it means CPU request value mentioned is compared against target to determine autoscaling.

As per my understanding, combination of request and limit resources will help to determine and use only dedicated resources values for particular pod.

I need some examples or inputs on how to determine and use most appropriate CPU and RAM values for resources.

**Comment by davidopp** [comment]
> I need some examples or inputs on how to determine and use most appropriate CPU and RAM values for resources.

The usual strategy is to observe the resource usage of your containers under normal load for a while, and then set the request to that value plus some safety margin. To find out how to observe resource usage of your containers a good place to start is
https://github.com/kubernetes/kubernetes/blob/b9cfab87e33ea649bdd13a1bd243c502d76e5d22/cluster/addons/cluster-monitoring/README.md

I'm going to close this issue; if you have additional questions, I'd encourage you to use [StackOverflow](http://stackoverflow.com/questions/tagged/kubernetes) so a wider audience can benefit from the answer (and offer answers).
