### ISSUE TITLE
WIP: Add pod-to-rc cache for RC/Job/DaemonSet/Endpoint

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#18972]
K8s use Labels and Selector to couple pods and the ReplicationController, currently, when find the rc for a pod, k8s will traverse all rcs to find the matching one, which is not efficiency.

Some optimization could be done to improve the look up time, such as:
1. add namespace index, so that filter first on namespace and then search in that namespace for a match. see https://github.com/kubernetes/kubernetes/pull/17277
2. add a "equivalent pod" cache: usually, a rc will have a replica number 3-5, which means there are 3-5 pods will have same labels(and thus same  rcs), so there is no need to search the matching rc for every "equivalent" pods. We can search the matching rc for the first pod, and cache the result. ControllerManager could watch the update/delete of rcs, and marks a cached value as dirty. When need find the matching rc for  a new pod, check to see if the search result for an equivalent pod is already cached. If so, re-search the matching rc just for the "dirty" values

**Comment by mqliang** [comment]
I will send some PRs address each in turn.

**Comment by mqliang** [comment]
The same "equivalent cache" optimization skills has been introduced into Scheduler:
https://github.com/kubernetes/kubernetes/issues/17390

**Comment by mqliang** [comment]
see PR https://github.com/kubernetes/kubernetes/pull/19043

**Comment by kargakis** [comment]
ns indexed caches are OK for now - I think the lookup cache in the RC controller was removed at some point
