### ISSUE TITLE
Receive "the namespace of the provided object does not match the namespace sent on the request" when creating a secret in the default namespace.

### ISSUE THREAD

**Issue by cpg1111** [kubernetes/kubernetes#18977]
Hey there, not entirely sure if this is an issue, but when I do not specify a namespace for a secret it fails saying I need a namespace in the secret's metadata.  So I use the default namespace for now.  I am trying to create this secret through a script that is not using kubectl to do this and is talking directly to the api server.  Is there any reason why the apiserver wouldn't assume it's using the default namespace in this case?  If not can we have it so by default the namespace is "default"?

**Comment by bgrant0607** [comment]
@cpg1111 What path are you posting to? The namespace must be specified in the path.

**Comment by bgrant0607** [comment]
Related: #6439

**Comment by cpg1111** [comment]
I realize it must be specified in the path, but wouldn't it make sense to use the "default" namespace if not specified?

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.

**Comment by marcinma** [comment]
\reopen
this happens on azure devops with kubernetes task, seems multi-namespace apply is not supported
