### ISSUE TITLE
Save logfiles from components even if cluster hadn't started successfully.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#18970]
We observe failures of 1000-node startups when one or few nodes don't get registered. Because cluster startup fails we don't save any logs from any component, which makes this pretty much impossible to debug.

Setting this a P0, as this blocks debugging of #18969.

cc @ixdy @brendandburns @davidopp @wojtek-t @kubernetes/goog-node @kubernetes/goog-control-plane

**Comment by ixdy** [comment]
dupe of #10423
