### ISSUE TITLE
Split e2e.sh into job definitions and runner scripts

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#18981]
I'd like to split e2e.sh in half. The first half contains the job definitions and the block of exports. There can be three of these files, each  in their own branch: master, release-1.0, and release-1.1. The second half contains the job runner itself in master only. Jenkins jobs will have to be modified to run both.

It's a bit of a pain to do this without breaking all the current jobs, so I'll have to be careful.

@ixdy @ihmccreery Does this seem reasonable? Know of any issues I'll run into? We can still keep the job definition files in their own branches if necessary, but I don't know why we would need to once this is in place.

This will allow me to move forward with #18846 and #18122 much more easily.

**Comment by ixdy** [comment]
I might vote for just 2 filenames: `e2e-runner.sh` and `e2e-jobs.sh`. `e2e-runner.sh` should only be called from the master branch, but `e2e-jobs`.sh would be different for each branch.

The advantage of this is when we create a new release branch, we don't have to do anything special other than updating the branch we pull `e2e-jobs.sh` from.

You could also combine steps 2+4 and 3+5 by making `e2e-runner.sh` call `e2e.sh` at first (rather than being empty).

**Comment by spxtr** [comment]
Ok, that sounds good.

**Comment by ixdy** [comment]
x-ref #17734

**Comment by ixdy** [comment]
also cc @karlkfi @justinsb @kubernetes/goog-testing as FYI

**Comment by spxtr** [comment]
Actually, I don't think it's worth calling e2e.sh from e2e-runner.sh, because it would need to know what branch to call it on, which I could pass as a parameter or something, and I don't think it's worth the effort :P

**Comment by ixdy** [comment]
Good catch.

**Comment by ihmccreery** [comment]
> I'd like to split e2e.sh in half.

Why?  Is this somehow a prerequisite to your work collapsing `e2e.sh` into `e2e.go`?

> Know of any issues I'll run into?

Yes.  The reason we originally split the runners out into versioned files (one on each branch) was that we wanted to make forward progress (potentially very drastic forward progress) on master without borking the release branch (there's plenty of reading material about this in #17734).  This is a very clear reversal of that intention.  We should be very, very clear about what should be versioned & what shouldn't be, if we want to go back to the some-stuff-versioned-some-stuff-not world.

Specifically, we wanted to be able to shift the names & tags of tests underneath e2e.sh without backporting all of those changes to other branches.  @spxtr you'll have to figure out how to sanely maintain skip lists, etc. for each branch; it's not just a matter of the runner versus the configs.  My work on #10548 should help with this on master, but I don't want to have to port that back to 1.0 and 1.1.

All that said, I'm theoretically in favor of this *as a stepping stone toward pulling test infra into its own repo*.

**Comment by spxtr** [comment]
> Why? Is this somehow a prerequisite to your work collapsing e2e.sh into e2e.go?

Turns out the test-running section of e2e.sh is badly out of date on the release branches, because nobody (myself included) took the time to backport their changes. In order to source control release jobs I'll have to backport some of the changes, but they're all to this part of e2e.sh, so it makes more sense to me to remove the need to do this before proceeding. My changes in particular can't be simple cherry-picks, I have to actually redo the changes.

I'm not sure that I understand your objection to this. I'm going to keep the e2e-jobs files in their own branches, which I think should be the same behavior we have now. I do see the issue with the skip-lists, and I was considering making a third file, `e2e-defs.sh` or something with those regex functions, the skip lists, and the upgrade function. This would live in master.

I'll take another look.

**Comment by ihmccreery** [comment]
> Turns out the test-running section of e2e.sh is badly out of date on the release branches

Yes, that's by design, (as weird as that sounds).  The idea was that test infrastructure should be self-contained, and that we should expect that a given branch could take care of itself.  Right now, though, test infra is (1) moving very quickly and (2) not self-contained, thus the painful state we're in right now.

See what you can do about the skip lists; that's the big blocker, as far as I can tell.

**Comment by spxtr** [comment]
Done.
