### ISSUE TITLE
apiserver: Should api prefix be configurable

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#18991]
Forked from review comments for https://github.com/kubernetes/kubernetes/pull/18113

Right now, we allow users to configure apiPrefix and apiGroupPrefix while bringing up apiservers (https://github.com/kubernetes/kubernetes/blob/master/pkg/genericapiserver/genericapiserver.go#L147).
But that doesnt really work since "/api" and "/apis" are hardcoded all through our code, both in server and client.
Do we want to allow configuring the prefixes? Or It will always be "/api" and "/apis"?

We should decide which direction we want to go and we can fix code as we touch it.

cc @smarterclayton @deads2k @lavalamp @caesarxuchao @kubernetes/goog-csi

**Comment by caesarxuchao** [comment]
I remember openshift needs this prefix to be configurable. IIRC, it's `/oapi`. Don't know if this is still true.

**Comment by nikhiljindal** [comment]
I see "api" hardcoded in kubectl: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L543 so kubectl will be broken for them if they were using a different prefix.

**Comment by smarterclayton** [comment]
It should be possible to prefix /API with something - the original code would work if --server was a URL with a prefix segment.  I don't think we want to allow /api, /apis, or /oapi to change, but letting someone do --server=http://foo.com/bar/bad (which looks for /bar/bad/api) I think is ok.

**Comment by smarterclayton** [comment]
I *think* we should allow third parties to have any URL prefix they want (i.e. /api and /apis are special for backcompat and discovery), but make sure someone does not configure the master that way.

**Comment by nikhiljindal** [comment]
Yes it seems fine to allow third parties to have any URL prefix, but is there a real use case?
We will need to do some work to enable that. 

cc @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
Third parties should be registering their endpoints for each version
with the apiserver - there should be no scenario under which a client
ever knows anything about the path except as an opaque value.
Anything other than the root discovery URL is arbitrary (and that
should be opaque as well to anything except the client defaulting
code).

**Comment by lavalamp** [comment]
We already have a group. I think that makes a separate prefix redundant.

*clients* need to handle arbitrary re-rootings, e.g. if we go through a
proxy or something. But I don't see any need for this in the server. IMO
the fewer options we give people when they make their own APIs the better.

**Comment by smarterclayton** [comment]
Agreed - just saying we have to support the legacy path configurable
just for Openshift oapi and Kube API.

**Comment by lavalamp** [comment]
Yes, I agree we need to do the minimum to support legacy clients.

**Comment by smarterclayton** [comment]
Ship has sailed.

**Comment by seh** [comment]
@lavalamp, I've looked for a way to configure the API server to use some path prefix, but couldn't find an existing flag that sounds pertinent. It _sounds_ like you (and others) decided here that the API server should not have such a capability, even if clients could respect an API server URL rooted at a path other than the root "/."

Is the idea that server administrators would need to front the API server with a proxy in order to host the API at a different URL path? Did I miss a flag that would allow me to run an API server that handled the API at, say, "/foo/api" instead of "/api?"

**Comment by lavalamp** [comment]
>  It sounds like you (and others) decided here that the API server should not have such a capability ...
> Did I miss a flag that would allow me to run an API server that handled the API at, say, "/foo/api" instead of "/api?"

Yeah, I think that's an anti-feature. I can't think of a reason to allow it off the top of my head.

> Is the idea that server administrators would need to front the API server with a proxy in order to host the API at a different URL path?

I think the idea is some (weird?) proxy situations unavoidably do that and we begrudgingly permit it in the client libraries.

**Comment by seh** [comment]
Yes, for clarification, with an AWS Application Load Balancer (ALB), you can use ["path conditions"](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#path-conditions) to route to different targets based on URL path components, but the ALB _will not_ rewrite these paths.
> Note that the path pattern is used to route requests but does not alter them.

Hence, if you wanted to use a single load balancer in front of several clusters, where a URL path component distinguishes one cluster from another (e.g. _kubernetes.example.com/c001_), you'd wind up with each set of API servers receiving requests with some path prefix (e.g. _/c001/api_) that we'd like to have the API server consume.

**Comment by lavalamp** [comment]
@seh I would recommend trying a virtual hostname for that use case (surely the LB supports that?), I think there's a chance that you could set it up so the clusters would just work. (You have to somehow get the kubeconfig files the system generates (for pods with api access) to work.)

**Comment by lavalamp** [comment]
Actually I'm not sure how you can make that work without also making the proxy do authentication. I think the path and/or virtual hostname is not the hard part of that setup.
