### ISSUE TITLE
Allow users to wait for conditions from kubectl and using the API

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#1899]
Spawned from #1325 

It should be easy for users do two things:
- Create new resources
- Determine when they are "ready"

Readiness (#620) is a complex topic, and readiness can mean different things in different contexts.  The Kubernetes client CLI and client library (see `pkg/client/conditions.go`) should provide tools for common readiness conditions and enable developers and administrators to easily script more complex readiness.  This issue _only_ covers client side readiness - server side readiness should be handled elsewhere.

Readiness must have an explicit upper bound (the system may never converge) - probably manifested as a maximum timeout.  Certain errors may be transient (network, server) and some fatal (resource deleted?).  It should be possible for end users to understand the ways that readiness can fail and work through those conditions.

Most resources are likely to have an implicit "ready" state:
- pods - when the state is "Running", "Succeeded", or "Failed", depending on the restart policy
- replicationControllers - when there are enough pods in running state to satisfy the label query
- services - when at least one pod is running and reachable via the service?

However, readiness can vary in infinitely complex ways
- services - user must wait for 2 pods to be running for HA, or pods must be running in X zones
- two services must be running and serving requests (web frontend and database tier) AND the backend database must have its schema created and at the latest version

It should be possible for users to define their own client ready conditions via scripting (potentially outside of kubectl), as long as the tools kubectl provide a common layer for behavior.

Possible CLI examples:

```
$ kubectl create -c foo.json --wait
$ kubectl create -c foo.json --wait=1m
$ kubectl get pod my-pod --wait --wait-for="pod-running"
$ kubectl get pod my-pod --wait --wait-for --format-template='{{ if .Status.Condition == "Running" }}1{{ else }}0{{ end }}'
```

Things I'd like to avoid end users doing:
- Bash `for | grep` loops on output as much as possible
- Implementing bash timeout logic
- Describing common yet complex conditions (replication controller at desired state) in template logic

**Comment by bgrant0607** [comment]
Bumping up the priority. This is an issue that every orchestrator on top of Kubernetes runs into. We need support in the API to simplify common waiting scenarios.

Related: #3585, #1768, #3692, #1535

**Comment by smarterclayton** [comment]
For API waits are you referring to watches for more specific conditions?  One thing we don't support on watch today is number of events or timeout - I don't know if a client closing its watch will release the server resources until the next event is available, and lots of clients waiting on the server is problematic until we unify the underlying watch queue on the apiserver.

**Comment by bgrant0607** [comment]
I meant a uniform schema and semantics across API resource kinds for conditions like:
* created (can be referenced by other objects)
* fully initialized (all fields are ready to read and propagate to other objects)
* fully active (reached successful deployment/reification)
* broken (unschedulable pods, bogus images, crashlooping containers, ...)
* ready (ready for application-level initialization/configuration)
* fully terminated and cleaned up

Phases and conditions aren't uniform and don't cover all these cases.

**Comment by smarterclayton** [comment]
Understood.

**Comment by thockin** [comment]
I just want to point out how much this looks like a certain state machine I know. :)

@dchen1107 

created,initialized = ACCEPTED
active,ready = ACTIVE
broken = FAILED
terminated = CLEANED

You left out our "-ing" states and subdivided a couple a bit further, and omitted "SUCCEEDED" but it's not far off.

I feel like something exists between active/ready and fully terminated.  This also doesn't capture things that naturally end (like run-to-completion)

**Comment by bgrant0607** [comment]
Except that they don't exactly align with system needs or behavior. For instance, fully reified and broken are fuzzy in a system that attempts self-healing indefinitely. Initialized is also fuzzy in the case of auto-scaling and auto-sizing; besides, components such as the scheduler need to look at specific fields rather than an overall indication. Ready may flap. 

Besides which, a custom state machine for a single object doesn't help. Generic orchestration tools want a model, schema, and notification mechanism that will work the same for all types of objects. It also would be suboptimal to force the orchestration mechanism to reason out which properties hold for which states. For instance, is an object initialized in ACCEPTED, ACTIVE, FAILED?

Created and gone can just be inferred from object existence or lack thereof -- there are cases that /operations could have covered had it not been so broken.

**Comment by thockin** [comment]
I'm not really trying to re-adjudicate the state machine discussion, just
saying that this is trending in that direction.  Of course the states we
defined for internal use don't match perfectly, but that's just a matter of
refinement of the definitions.

**Comment by bgrant0607** [comment]
My point was that they should be properties that span all relevant states, not states themselves.

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by pmorie** [comment]
Adding use-case from #9815:

It's a pretty common test to want to know how fast a cluster can resize a replication controller for some specific pod template. It would be great if there was a kubectl command that could:

1.  Resize some replication controller R to some new size N
2.  Watch R and time how long it takes the running replica count to go to N

**Comment by dsjgordon** [comment]
A simple use case I currently have is:

1. Create a Job with ```RestartPolicy: OnFailure``` to perform backwards compatible schema updates.
1. Wait for the Job to complete.
1. Perform a rolling-update.

While the schema changes have bc, they are not forward compatible, so I need to be sure the job has completed before update.  It can be achieved with custom polling for the change but this adds some ugly complexity to the deploy process.

I realise on highly distributed systems the job completion won't guarantee consistency, but for smaller web applications it would be sufficient.

**Comment by smarterclayton** [comment]
@bgrant0607 note that this is the primary use case for deployment hooks
(pre, post, or middle).  This is a pre-rolling - the other common kind is
mid-recreate (when pods hit zero)

On Nov 21, 2015, at 7:10 AM, Darren Gordon <notifications@github.com> wrote:

A simple use case I currently have is:

   1. Create a Job with RestartPolicy: OnFailure to perform backwards
   compatible schema updates.
   2. Wait for the Job to complete.
   3. Perform a rolling-update.

While the schema changes have bc, they are not forward compatible, so I
need to be sure the job has completed before update. It can be achieved
with custom polling for the change but this adds some ugly complexity to
the deploy process.

I realise on highly distributed systems the job completion won't guarantee
consistency, but for smaller web applications it would be sufficient.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/1899#issuecomment-158634432>
.

**Comment by mml** [comment]
It's likely that any standard way of expression "wait for $condition" would be useful in future implementations of #17393.

**Comment by bgrant0607** [comment]
Without this, test-cmd.sh will require a lot of scripted wait loops to make it robust.

**Comment by mml** [comment]
In reading the old discussion, it's unclear to me if we want to implement waiting logic in the API server or if an implementation in kubectl (optionally linkable by other users if they want it) is adequate.

**Comment by smarterclayton** [comment]
My preference is a good client library function first, a good kubectl
implementation second, and maybe a wait later in the api server.  We
probably do not want to have the API server have to deal with conditions
that never complete and the attack angles there.

**Comment by mikedanese** [comment]
> It should be easy for users do two things:
> 
> * Create new resources
> * Determine when they are "ready"

It would be nice to be able to infer causality and have a reasonable halting condition that is not timeout based.

**Comment by mml** [comment]
I think we should avoid asking users to write conditions in any template language.  If we provide waitrunning, waitsuccess, and waitfail, I believe that will cover almost all use cases and anything more complicated should probably be implemented in a monitoring system.  (Was just speaking to @erictune about this, and he's on the same page.)

**Comment by erictune** [comment]
Everyone who uses kubernetes will use kubectl.  A majority will not write
code against the API.  We should do the common cases in kubectl in a really
easy-to-use way first.

**Comment by smarterclayton** [comment]
I'm not against special case states for ease of use.  My point is that
they aren't enough, and real use cases we have today already exceed
what can be expressed with a few flags.  Monitoring systems are going
to be built using the primitives we provide - and there is a big
hurdle for most systems to integrate our API.  I can say with
certainty that not implementing reasonably flexible wait on the Cli
doesn't address the actual user need.

**Comment by smarterclayton** [comment]
More detail here - pod wait is the least interesting wait condition.
Service and deployment wait are all that really matter for most users,
and possibly claim wait.  There's also the generic wait - you run
create -f and want to wait until it's done.  What users actually want
is probably "all services with a label have at least one endpoint",
and if you had an ingress, it will be "the ingress points to a service
that is accepting traffic".

The other most common requests from users I've heard are for inside a
container - wait for service being the most common, followed by wait
for other container (which can be accomplished via network, but loses
the structural probes on that container).  Beyond that it branches out
into other concepts, like waiting for jobs or a particular deployment
version being up.

**Comment by erictune** [comment]
Let me take a step back.

I agree we need ways to wait for Services, deployments, ingresses, jobs,
petsets, and sets of those things.

And I agree we will need kind-specific go language code for waiting.

What I was hoping to avoid, and I thought you were suggesting, but I could
have misunderstood, was for users to have to type a jsonpath template or go
template to do any sort of waiting.

I agree that each Kind will have its own sort of conditions that you might
want to wait on.

But, if for each Kind, we could define 1 or 2 possible states to wait for,
I think that would cover a lot of use cases.

I think the two main states are "ready" for most objects, and "complete"
for terminating objects

For example:
- a Service is Ready when it has at least 1 Ready backend,
- a Deployment is Ready when most of its Pods are Ready
- a Claim is Ready when ...
- secrets and configMaps are Ready after they have been created
- default for kinds not mentioned: ready when they are created.
- builds are Ready when at least one image has been built
- set of objects (kubectl create -f, or PetSet): ready when all objects in
the set are ready.

then you can do:
 kubectl create -f stuff.yaml --wait-ready && use_it


For "Complete" state:
- Pods with restart != always are complete when they are Terminated
- Workflow and Jobs are complete when they are Completed
- a set of objects is complete when all the objects that have a
completeness check are complete

the you can do:

kubectl create -f job1.yaml -f job2.yaml && use_job_output

where kubectl returns 0 if all the complete objects had "success", else
return non-zero.

**Comment by scottstensland** [comment]
This open ticket is 18 months old ... in frustration I see tons of people have gone ahead and rolled their own poll-wait loops wrapping their calls to kubectl  ... in my case I need to wait until 

    kubectl get pods

comes back Ready with Status Running ... if I blindly avoid poll-wait my follow on kubectl exec fails with : 

error: pod web-controller-x is not running and cannot execute commands; current phase is Pending

Please advise

**Comment by smarterclayton** [comment]
> But, if for each Kind, we could define 1 or 2 possible states to wait
for, I think that would cover a lot of use cases.

Totally agree.  My concern was that there's a lot of nasty edge cases even
in "wait for pod to be running", so I don't want to "only" do the simple
thing and not actually solve the "kubectl wait --for='something'
--timeout=1m" tool that correlates to more use cases.  I'm hesitant to loop
these closely into create and apply simply because a good "wait" command
would link the two.

**Comment by bgrant0607** [comment]
@scottstensland Why do you need to exec into containers as soon as they are created? That's what the postStart hook does.

**Comment by Kamshak** [comment]
Is there a best-practice to achieve checks for readiness & completeness as explained by @erictune with 1.3? Would anybody perhaps have an example script? I need to check whether or not a deployment is ready (kubectl rollout status seems to check only if the replicasets are updated).

**Comment by erictune** [comment]
@kubernetes/sig-apps 
When we want to wait for readiness for objects that belong to charts, or for completion of test Jobs for charts, let's collect those wants here.

**Comment by kargakis** [comment]
For Deployments, we should switch `kubectl rollout status` to use Conditions (https://github.com/kubernetes/kubernetes/pull/19343)

**Comment by smarterclayton** [comment]
I think we should have a conceptual level in the API which is "ready" for most resources.  We should align that concept across the resources and have necessary support to handle that.

Example:

1. create a bunch of things
2. for those things, wait until they are all ready
3. be able to communicate if they are ready

Things that have concrete readiness

1. Pods (today)
2. Deployments (today)
3. Replication controllers (today)
4. Stateful Sets (today)
5. Services (could do this today, but need to define what ready for a service means)
6. PVCs (today)
7. Ingress (probably depends on services)
8. Node (today)
9. Any other type that doesn't require readiness (like RBAC, some policies) is roughly covered

Whether this is waiting for custom conditions (different ones per type), or a generic condition, or a level driven summarizer per type, I think it's achievable.

In a command, you could wait for conditions, wait for specific cases, or wait for generic readiness.  Template (helm) instantiations could wait for readiness across many different types consistently.

**Comment by erictune** [comment]
Thread about determining if a deployment is complete.  May need to distinguish between controller being ready vs update is complete: https://groups.google.com/forum/#!msg/kubernetes-dev/dFEDwhCBqCE/Fp6NG2AWDQAJ

**Comment by erikbgithub** [comment]
I'm not an expert on Kubernetes, so can I ask why this issue isn't prioritized as `urgent` since the first day of its creation? Maybe because I just come here due to having such a problem, but in my current context it feels quite normal that you would have something like this the moment you have the ability to deploy anything. Even `kubeadm` would profit a lot from not returning before the apiserver really is ready.

It's obviously a complicated issue, but I can't see why it's not top priority until at least a workaround for 80% of the usecases is provided. Sorry for my blindness in that regard.

**Comment by thrawn01** [comment]
From reading the comment history; It it occurs to me that defining the concept of various states like 'Ready' or 'Pending' is a bit of a red herring. It can mean different things depending on what you are trying to accomplish, and could change in meaning as the kubernetes project matures.

The most flexible option would be some style of expression evaluation as @thockin proposed early on. However, I worry there will be no compile time check to ensure API object modifications didn't invalidate a hardcoded expression in kubectl or third party code. Instead I would propose a API object based evaluator.

As an example
```yaml
apiVersion: alpha/v1
kind: WaitEvaluator
metadata:
  name: wait-for-pod
conditions:
  - apiVersion: v1
    kind: Pod
     - metadata:
      name: pod-example
      spec:
        containers:
        - image: ubuntu:trusty
```
Where calling `kubectl create -f` on this file would block until a pod with the name of 'pod-example' and a container with an image of 'ubuntu:trusty' existed.

With such an implementation users could easily join wait evaluators in spec files using `---` such that the following would deploy `app-1`, wait for a pod to appear in the `Ready=True` status and then deploy `app-2`.
```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-1
 **snip**
---
apiVersion: alpha/v1
kind: WaitEvaluator
conditions:
  - apiVersion: v1
    kind: Pod
     - metadata:
       name: app-1
    status:
     conditions:
     - type: Ready
     status: True
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-2
 **snip**
```

**Comment by erictune** [comment]
The Smith Resource Manager was presented at Sig-Apps on Jul 24th.  Smith handles readiness, for creation-order-dependcies, by having a function for each resource type.  For TPRs you can specify a field, which, if present, indicates readiness.  @ash2k hope I got that somewhat right.

**Comment by ash2k** [comment]
@erictune yes, that is correct. More information is in the readme https://github.com/atlassian/smith

Please note that not all object kinds are supported right now but it is trivial to add support. Also there are some other limitations (see issues).
Anyone interested is welcome to contribute to the project - open issues/PRs.

**Comment by smarterclayton** [comment]
A note of why this is so difficult to get right and should be on the
serverside - Smith's deployment readiness is wrong because you can have the
correct number of pods but not be within the availability condition (i.e.
maxUnavailable can be violated and smith will report ready).  Given the
complexity of these interactions, I think it's untenable to expect client
authors to get this right everytime.

On Mon, Jul 24, 2017 at 9:49 PM, Mikhail Mazurskiy <notifications@github.com

**Comment by smarterclayton** [comment]
And most people get this wrong, even people who are fairly familiar with
deployments :)  (no knock on Smith)

**Comment by cjw296** [comment]
Would be fantastic to have this for running one-shot database migration jobs that need to run to completion before doing a rolling update of a web app. Guess I'll go hack up a poll/wait loop in the meantime ;-)

**Comment by cjw296** [comment]
Testing...

**Comment by cjw296** [comment]
test

**Comment by mml** [comment]
I know this is an old one, but here's another upvote.  I've found another case where this would be quite useful:  running conformance tests inside a cluster, it would be nice to know when the job has completed.

**Comment by bgrant0607** [comment]
A related issue is that we don't make it easy to determine success or failure of a change, much less wait for it: #34363

**Comment by jpza** [comment]
Bumping this

**Comment by zoobab** [comment]
Damn this issue was created in 2014.

I need to wait for a Container to be in the state Running, will return to a shell loop watching the state.

**Comment by erikbgithub** [comment]
@zoobab also you probably want to check for the numbers `x/y` are the same. It's possible that the State is running but not all containers in the pod are available already. For instance `0/1 Running` is totally possible. Best is probably to check `healthz` and `logs`.

**Comment by daniilyar** [comment]
One more example: when I run something with:
```
kubectl run -it --image=<image>
```
And the <image> does not exist, the container will immediately fail with 'ErrImagePull' but kubectl will hang forever because it blindly waits for a 'Running' status forever!

**Comment by deads2k** [comment]
`kubectl wait --for=delete resource/foo` and `kubectl wait --for=condition=available --timeout=60s resource-string(deployment)/foo` exists after #64034

**Comment by chucky2305** [comment]
Either i am doing something wrong or i misunderstood the concept behind `kubectl wait`.

I use kubectl wait in my gitlab ci pipeline.

Stage 1: Deploy my app 
Stage 2: Detect if the app is deployed and running. 

In Stage 2 i wanted to use 
`kubectl wait --timeout=60s --for condition=ready pod -l release=branch123,pod-name=php-nginx`

When the deployment is not ready and no pod can be found with a labels "release=branch123" and "pod-name=php-nginx" `kubectl wait` ignores the define timeout (60 seconds) in my example. 
Why is this so? I was expecting to always wait 60 seconds.

I hope my request is clear. Maybe i am just doing something wrong here?

**Comment by Shivang44** [comment]
@chucky2305 Yeah, unfortunately it instantly returns if the selector does not match (I made a bug report for that https://github.com/kubernetes/kubernetes/issues/66349). Basically, it will only wait if that resource exists. It will not wait on nonexistent resources.

What you could do (I believe) is put those labels on the deployment, and wait until the deployment has a condition of available. The benefit of this is, since the deployment does exist, it won't instantly return.

So your command would be: 

`kubectl wait deployment --timeout=60s --for condition=available -l label1=value1,label2=value2`

**Comment by protometa** [comment]
For fellow noobs from google wondering how to wait for a deployment update, `rollout status` is actually the way to go:

    kubectl set image deployment/my-deployment my-container=my-image:tag
    kubectl rollout status deployment/my-deployment

**Comment by aakarshg** [comment]
Most of what was mentioned above seemed to have been accomplished, the only thing that I'm still finding myself using grep is for checking pod's phase. Not sure how it can be done purely using kubectl without the need for grep.

**Comment by soltysh** [comment]
What about `kubectl get pods -o jsonpath --template='{.items[].metadata.name} : {.items[].status.phase}'`
