### ISSUE TITLE
e2e flake: Deployment deployment should delete old pods and create new ones

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18996]
Example failure:

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/21619/#

@nikhiljindal @janetkuo

**Comment by fgrzadkowski** [comment]
This is actually happening pretty often in gce-parallel:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13230/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13239/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13246/

**Comment by gmarek** [comment]
New one: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13293/

**Comment by janetkuo** [comment]
I'm OOO and will be back on Jan 5. I don't have my laptop with me at this
moment. I'll look at this when possible.

Janet
On Thu, Dec 24, 2015 at 12:01 AM Marek Grabowski <notifications@github.com>
wrote:

> New one:
> http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13293/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/18996#issuecomment-166917675>
> .
>
-- 
Best,
Janet Kuo

**Comment by janetkuo** [comment]
Failure rate ~2% (6/351). 
Error looks like this: `total pods available: 1, less than the min required: 2` in test/e2e/deployment.go:186

**Comment by janetkuo** [comment]
Fix #19344 is merged. Will close this if the e2e test becomes stable.

**Comment by janetkuo** [comment]
All the fixes are merged. Will watch it in flaky tests build.

**Comment by janetkuo** [comment]
TODO: If this flaky test becomes stable, remove it from flaky test build.

**Comment by janetkuo** [comment]
Looks like these deployment e2e test flakes become stable: #19732 #19299 #19064 #18996. Closing them.
