### ISSUE TITLE
Use Docker to host most server components

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#19]
Right now we use salt to distribute and start most of the server components for the cluster.   

Instead, we should do the following:
* [x] Only support building on a linux machine with docker installed.  Perhaps support local development on a mac with a local linux VM
* [ ] Package each server component up as a Docker image, built with a Dockerfile
  * [ ] Support uploading these Docker images to either the public index or a GCS backed index with [google/docker-registry](https://index.docker.io/u/google/docker-registry/).  Or GCR?
  * [ ] Minimize docker image size by switching to single layer static golang binary docker images.
  * [ ] Support `docker save` to generate tars of the docker image(s) for dev/private development.
* [ ] Use the kubelet to run/health check the components.  This means the kubelet will manage a set of static tasks on each machine (including the master) and a set of dynamic tasks.
* [ ] The only task that shouldn't run under the docker should be the kubelet itself.  We may have to hack in something for (network mode = host) for the proxy.

**Comment by saad-ali** [comment]
CC: @saad-ali

**Comment by bgrant0607** [comment]
See also #5011.

**Comment by errordeveloper** [comment]
Isn't this mostly done already?

**Comment by bgrant0607** [comment]
Yes.

**Comment by maicohjf** [comment]
> You could have Dockerfile for individual binaries and have the resulting
> container image launch it has its ENTRYPOINT.
> 
> That way you could leverage the fact sources are sent from your workstation
> to the VM as the /build payload (context) over the remote API (no need to
> copy to the host) and the docker image is your artefact.
> On Jun 14, 2014 8:48 AM, "Joe Beda" [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Notes of work in progress:
> > 
> > * I'm starting out by moving our build process into Docker. A snapshot
> >   of a Dockerfile and a Makefile to automate some common stuff is here:
> >   [jbeda/kubernetes@6c4a6a8](https://github.com/jbeda/kubernetes/commit/6c4a6a8)
> >   [jbeda@6c4a6a8](https://github.com/jbeda/kubernetes/commit/6c4a6a8fa7794874862cadaf31948bdb9235f51a)
> > * If we say everyone has to build on Linux, this is much easier. With
> >   the boot2docker on a Mac, you essentially have a remote machine that you
> >   are talking to through a local TCP pipe. That means with any -v
> >   local-path:container-path the local-path is really local to the
> >   boot2docker VM and not the local workstation.
> > 
> > This leaves us with 2 choices:
> > 
> > 1. Build in the boot2docker VM and copy results back out, either
> >    through stdout from the docker run or via boot2docker ssh
> > 2. Build the final docker images inside the boot2docker VM inside of a
> >    docker container. Yup, this means running docker in docker. This is
> >    supported with dind but it gets complicated. There is a repo (
> >    https://github.com/jpetazzo/dind) with support but...
> >    
> >    * There is no license in that repo. Issue: [jpetazzo/dind#21](https://github.com/jpetazzo/dind/issues/21)
> >      [jpetazzo/dind#21](https://github.com/jpetazzo/dind/issues/21)
> >    * The Docker build process itself uses dind but has a forked script
> >      checked in to the Docker repo. These have diverged and I worry about
> >      continued support for the separate dind repo. Issue to harmonize these:
> >      [jpetazzo/dind#22](https://github.com/jpetazzo/dind/issues/22) [jpetazzo/dind#22](https://github.com/jpetazzo/dind/issues/22)
> > 
> > Right now I'm leaning toward copying stuff in and out (option 1).
> > —
> > Reply to this email directly or view it on GitHub
> > [#19 (comment)](https://github.com/kubernetes/kubernetes/issues/19#issuecomment-46091452)
> > .

15.
Check to see how many nodes are ready (not including nodes tainted NoSchedule) and write the
number to /opt/......

首先用kubectl get node 查看总共node 数量，然后kubectl describe node 查看
不包含污点值为NoSchedule 的node 数量

16. 
From the Pod label name=cpu-utilizer, find pods running high CPU workloads and write the name
of the Pod consuming most CPU to the file /opt/...... (which already exists)

方法一：
通过kubectl get pod -l name=cpu-utilizer -o wide 查看pod 所在的node
之后kubectl describe node 查看哪个pod 请求的cpu 最多
三个都是0，我就都写进去了
方法二：
kubectl top pod -l name=cpu-utilizer
