### ISSUE TITLE
scheduler: Maximum parallel for findNodesThatFit and PrioritizeNodes

### ISSUE THREAD

**Issue by magicwang-cn** [kubernetes/kubernetes#19005]
see [PR](https://github.com/kubernetes/kubernetes/pull/19004)
modify func (`PriorityFunction`) 's last param (`nodeLister NodeLister`) to (`nodes chan *api.Node`). then findNodesThatFit and PrioritizeNodes can be running parallel. 
1. once findNodesThatFit finishs predicate, insert the node to channel;
2. priorityFunc in PrioritizeNodes just waiting to read this channel

**Comment by magicwang-cn** [comment]
@xiang90 @davidopp @wojtek-t  @HardySimpson @hongchaodeng

**Comment by magicwang-cn** [comment]
before optimized,Latest benchmark result on master :
```
BenchmarkScheduling100Nodes0Pods	     300	   6127653 ns/op
testing: BenchmarkScheduling100Nodes0Pods left GOMAXPROCS set to 4
BenchmarkScheduling100Nodes1000Pods	     200	   7685995 ns/op
testing: BenchmarkScheduling100Nodes1000Pods left GOMAXPROCS set to 4
BenchmarkScheduling1000Nodes0Pods	     100	  15670299 ns/op
testing: BenchmarkScheduling1000Nodes0Pods left GOMAXPROCS set to 4
BenchmarkScheduling1000Nodes1000Pods	     100	  18310592 ns/op
testing: BenchmarkScheduling1000Nodes1000Pods left GOMAXPROCS set to 4
```

after optimized:
```
BenchmarkScheduling100Nodes0Pods	     300	   5781995 ns/op
BenchmarkScheduling100Nodes1000Pods	     200	   7319218 ns/op
BenchmarkScheduling1000Nodes0Pods	     100	  14025236 ns/op
BenchmarkScheduling1000Nodes1000Pods	     100	  15535794 ns/op
```

**Comment by timothysc** [comment]
@jayunit100 could you please triage this one.

**Comment by jayunit100** [comment]
I think suggest changing to P3 since there isnt any urgency to merge it.
