### ISSUE TITLE
Scheduler has 2 rate-limitters doing almost the same

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#19012]
In scheduler we have two rate-limitters:
- QPS limits: defining client QPS limits:
https://github.com/kubernetes/kubernetes/blob/master/plugin/cmd/kube-scheduler/app/server.go#L124
- Binding limits: defining max bindings limits:
https://github.com/kubernetes/kubernetes/blob/master/plugin/cmd/kube-scheduler/app/server.go#L148

It doesn't make much sense o have both - we have exactly 2 writes per binding, so these are basically rate-limitting exactly the same.

We should remove binding limit and leave only QPS limit for consistency with all other components

@kubernetes/sig-scheduling @davidopp

**Comment by bprashanth** [comment]
Fyi we didn't want to limit all queries sent by the scheduler (including events and anything else we might build into it down the line) to the rate at which the system can handle new pods (which is tied to the rate of new binds, and really what the bind qps is about). This reason might no longer be valid.

**Comment by mikedanese** [comment]
This is fixed by #19128?
