### ISSUE TITLE
Replace dashes with underscores in go2idl client generation code

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#19019]
`k8s.io/kubernetes/cmd/libs/go2idl/client-gen/generators/generator-for-type.go` should be `k8s.io/kubernetes/cmd/libs/go2idl/client-gen/generators/generator_for_type.go` as per coding conventions.

@caesarxuchao @wojtek-t

**Comment by smarterclayton** [comment]
`client-gen` may remove because it is a command.

**Comment by caesarxuchao** [comment]
Thanks for catching it.

**Comment by caesarxuchao** [comment]
I'll fix this after several of my PRs merged, to avoid multiple rebase.
