### ISSUE TITLE
Remove `Pods should cap back-off at MaxContainerBackOff` from [Slow]?

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19027]
Now that #12648 is merged, can we remove `Pods should cap back-off at MaxContainerBackOff` from the `[Slow]` suite?  https://github.com/kubernetes/kubernetes/pull/13180 marked it as slow with a PR reference to #12648.  We should either remove it, or mark it as slow-by-design.

**Comment by dchen1107** [comment]
We should mark it as slow-by-design, instead of removing it.
