### ISSUE TITLE
Namespaces should delete fast enough is flaky in parallel

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19026]
`Namespaces should delete fast enough (90 percent of 100 namespaces in 150 seconds)` is flaky in parallel.  It was marked as flaky-in-parallel in #13810.

It should be deflaked. Or, if they shouldn't be run in parallel, add the `[Disruptive]` or `[Serial]` label to the test.

**Comment by mikedanese** [comment]
@davidopp I can look at this if you like. I have 2 other flakes that I am assigned to at the moment though and I'm not familiar with the test.

cc @derekwaynecarr

**Comment by davidopp** [comment]
@derekwaynecarr would you mind taking a look at this? I read through the chain #13810 -> #7372 -> #18290, but it looks like #18290 was merged before this issue was opened, so presumably it's not fixed by #18290.

**Comment by derekwaynecarr** [comment]
I am investigating this now.  Will update if I find anything obvious.

**Comment by derekwaynecarr** [comment]
I am inclined to mark this test `[Serial]` and determine if the flakes are resolved.  The test is much more write-intensive than other tests (200 namespaces, service accounts, etc.) and it deletes all of the above.  I think we can evaluate running this parallel when more resources are being deleted in bulk collection calls.
