### ISSUE TITLE
fluentd logging should set dynamic elasticsearch type based on logged data

### ISSUE THREAD

**Issue by offlinehacker** [kubernetes/kubernetes#19022]
## Problem:

Currently all logs logged with fluentd are saved to elasticsearch under one type, which could cause problems if multiple containers are logging json output with same attributes. Fluentd logging should have distinct type names based on namespace name and container name
## Possible solution:

We fixed this by using elasticsearch_dynamic plugin type: https://github.com/uken/fluent-plugin-elasticsearch#dynamic-configuration which allows you to set dynamic type based on logged data.

This is snippet of configuration we use:

```
        <source>
          type tail
          path /var/log/containers/*.log
          pos_file /var/log/es-containers.log.pos
          time_format %Y-%m-%dT%H:%M:%S
          tag kubernetes.*
          format json
          read_from_head true
        </source>

        <filter kubernetes.**>
          type kubernetes_metadata
        </filter>

        <match kubernetes.**>
          type elasticsearch_dynamic
          log_level info
          include_tag_key true
          host elasticsearch.default.cloud.gatehub.net
          port 9200
          logstash_format true
          flush_interval 5s
          # Never wait longer than 5 minutes between retries.
          max_retry_wait 300
          # Disable the limit on the number of retries (retry forever).
          disable_retry_limit
          # Set type name dynamically
          type_name ''${record['kubernetes']['namespace_name']}-''${record['kubernetes']['container_name']}
        </match>
```

**Comment by dobesv** [comment]
Here's an example solution using `target_index_key` and the `record_modifier` plugin:

https://gist.github.com/dobesv/ffb27537fcc2df74ce8049fcfb937c4d

**Comment by dobesv** [comment]
Here's an example solution using `target_index_key` and the `record_modifier` plugin that could be adapted to work with `type` using `target_type_key` to solve this issue:

https://gist.github.com/dobesv/ffb27537fcc2df74ce8049fcfb937c4d
