### ISSUE TITLE
All DaemonRestart tests are flaky in parallel

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19023]
#17829 notes that the Controller Manager test is flaky, but actually, *all* of the DaemonRestart tests are in the `PARALLEL_FLAKY` suite.

They should all be de-flaked, or moved into [Serial] or [Disruptive] if they can't be run in parallel for some reason.

(In #19021, I'm removing the notion of parallel-flaky: either a test is flaky or it's not—and if it shouldn't be run in parallel, then it ought to be marked as [Serial] or [Disruptive].  If you disagree, feel free to chime in on #10548.)

Assigning to @davidopp, please feel free to reassign.

**Comment by ihmccreery** [comment]
Note that these tests were noted as parallel-flaky in #11339.

**Comment by davidopp** [comment]
Reassigning to @bprashanth who generously offered to take a look.

**Comment by davidopp** [comment]
IIUC #19973 is supposed to fix this, so closing the issue, of course we can re-open if the problem recurs.

Thanks @bprashanth  !

**Comment by bprashanth** [comment]
Oh, hmm, i was going to wait for the nodecontroller reverts and the pod sync fix, and they rerun in a loop overnight. I'll do that anyway and re-open if anything else breaks.

**Comment by davidopp** [comment]
Can you link to " the nodecontroller reverts and the pod sync fix, " ? I closed this because I didn't see any other outstanding PRs mentioned here.

**Comment by bprashanth** [comment]
Just the 2 above, namely: https://github.com/kubernetes/kubernetes/issues/20048, https://github.com/kubernetes/kubernetes/issues/19973

**Comment by davidopp** [comment]
Oh yeah, I was watching those before I closed this -- both of those were already merged.

**Comment by ihmccreery** [comment]
The "DaemonRestart" tests are still labeled `[Flaky]` at `HEAD`.  I will send a PR to promote them.

**Comment by ihmccreery** [comment]
Also see https://github.com/kubernetes/kubernetes/issues/20363.

**Comment by davidopp** [comment]
Now that #20455 has merged, should we close this issue?
