### ISSUE TITLE
missing  sentinel.py in redis image creation

### ISSUE THREAD

**Issue by rasekar2000** [kubernetes/kubernetes#19039]
Hello Team,

https://github.com/kubernetes/kubernetes/blob/release-1.1/examples/redis/image/Dockerfile#L8

COPY sentinel.py /sentinel.py file is missing in this latest version. 

Thanks and Regards,
Raj

**Comment by rasekar2000** [comment]
import json
import sys

data = json.load(sys.stdin)

if data and "endpoints" in data and len(data["endpoints"]) > 0:
  host = data["endpoints"][0].split(":")[0]
else:
  host = "localhost"

print "sentinel monitor mymaster %s 6379 2" % host
print "sentinel down-after-milliseconds mymaster 60000"
print "sentinel failover-timeout mymaster 180000"
print "sentinel parallel-syncs mymaster 1"

--> Taken from after getting inside the docker running image

Regards,
Raj

**Comment by bgrant0607** [comment]
cc @brendandburns

**Comment by bgrant0607** [comment]
It doesn't look like sentinel.py was in the original PR.

**Comment by bgrant0607** [comment]
Dupe of #17938, and also fixed.
