### ISSUE TITLE
Figure out the root cause for 1000 node cluster density flakes

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#19048]
In some of the runs we observe pod startup lantencies > 1m and we have no idea how.

cc @kubernetes/goog-control-plane @brendandburns @wojtek-t @fgrzadkowski @davidopp

**Comment by gmarek** [comment]
One observation: all 'bad' pods are created within few seconds - they generally have consecutive, or nearly consecutive numbers. E.g.
```
[
{density-latency-pod-6abfb701-a8d8-11e5-8ac8-42010af01555-10 e2e-scalability-minion-3jin 15.431706849s} 
{density-latency-pod-6abfb701-a8d8-11e5-8ac8-42010af01555-12 e2e-scalability-minion-ouk5 15.43286036s}
{density-latency-pod-6abfb701-a8d8-11e5-8ac8-42010af01555-11 e2e-scalability-minion-wjl4 15.433680136s}
{density-latency-pod-6abfb701-a8d8-11e5-8ac8-42010af01555-3 e2e-scalability-minion-jy2v 16.426253216s}
{density-latency-pod-6abfb701-a8d8-11e5-8ac8-42010af01555-5 e2e-scalability-minion-xigs 16.42698074s}
{density-latency-pod-6abfb701-a8d8-11e5-8ac8-42010af01555-6 e2e-scalability-minion-jgq0 16.427929014s}
{density-latency-pod-6abfb701-a8d8-11e5-8ac8-42010af01555-4 e2e-scalability-minion-s5ge 16.428706659s}
{density-latency-pod-6abfb701-a8d8-11e5-8ac8-42010af01555-7 e2e-scalability-minion-s5ge 16.430522777s}
{density-latency-pod-6abfb701-a8d8-11e5-8ac8-42010af01555-1 e2e-scalability-minion-1idc 17.423859514s}
{density-latency-pod-6abfb701-a8d8-11e5-8ac8-42010af01555-2 e2e-scalability-minion-3xsr 17.424973585s}]
```
Slowest ones are: 1, 2, 7, 4, 6, 5, 3, 11, 12, 10

With @wojtek-t we've seen the same thing on >1m startup latencies in 1000-node cluster runs. We're not seeing such failures in Kubemark, but it's possible that they are small enough to pass under the threshold (this needs to be checked by hand;/)

It's currently pretty hard to debug it, as we have no data, as scalability tests are run with `--v=1` and we're not gathering any saturation metrics during the run. Things we can do:
- increase verbosity level. This may have some unpleasant side effects.
- in 1000 node runs plug in new heapster to gather CPU usage from master and dump to some external storage (GCM?). This requires plugging in dev version of heapster in such a way, that jenkins will be able to use (@mwielgus) it and registering master's kubelet, so heapster will be able to monitor it.

**Comment by wojtek-t** [comment]
Regarding first point (logs verbosity), I think we need at least --v=2 logs to debug it (at least from apiserver, but probably also from kubelets)...

**Comment by gmarek** [comment]
We have first run with all the additional monitoring: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3808/

**Comment by gmarek** [comment]
Sadly metrics look normal to me. Plus they're hard to analyze, as maps in go print themselves in random order...

**Comment by gmarek** [comment]
cc @kubernetes/sig-scalability

**Comment by davidopp** [comment]
@gmarek @wojtek-t How often is this happening recently? Should we mark it "flake" and consider it part of the flake fixit? Sounds like there may not be much hope for debugging it soon. Note that it is marked as 1.2 milestone.

**Comment by wojtek-t** [comment]
I'm not sure - we just reverted back to Go 1.4 - with Go 1.5 we had a bunch of failures (actually all runs were failures). So we will see now...
Anyway - I'm planning to look into why "load.go" test is failing in 1000-node cluster, which in my opinion can be related to those failures...

**Comment by wojtek-t** [comment]
The issues with "load.go" test appeared to be completely unrelated things.

I took a look into 1000-node kubemarks, I've seen few such failures (something like 1/20 on average?).
The last such failure:
http://kubekins.dls.corp.google.com:8080/view/Kubemark/job/kubernetes-kubemark-gce-scale/741/

I think we need to try to understand this.

**Comment by wojtek-t** [comment]
We have a failure with exactly the same symptoms in our main scalability suite:
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4550/

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/4550/?project=kubernetes-jenkins

I will try to look into it either today or early next week.

**Comment by wojtek-t** [comment]
Got it - I think I understand what exactly is happening here.

So basically, looking into apiserver, scheduler & kubelet logs, it seems that everything works pretty good. All pods are started relatively fast and their "Running" status is recorder in apiserver pretty quickly.

The issue seem to be in the test itself. Because of some reason it takes quite long to read some of the pods [it seems that in all the cases those pods are first few pods].

Looking into the code, there is an Informer that is trying watch those pods.
However, lookingo into logs from apiserver we have:

    I0212 06:04:27.123318       5 handlers.go:130] GET /api/v1/namespaces/e2e-tests-density-u76zn/pods?labelSelector=name%3Ddensity-latency-pod-6e8dd7b3-d14e-11e5-b472-42010af01555&reso      urceVersion=0: (15.581038ms) 200 [[e2e.test/v1.2.0 (linux/amd64) kubernetes/b5c12d1] 104.197.45.156:38629]
    ....
    I0212 06:05:06.802012       5 handlers.go:130] GET /api/v1/watch/namespaces/e2e-tests-density-u76zn/pods?labelSelector=name%3Ddensity-latency-pod-6e8dd7b3-d14e-11e5-b472-42010af0155      5&resourceVersion=17036&timeoutSeconds=546: (29.482749436s) 200 [[e2e.test/v1.2.0 (linux/amd64) kubernetes/b5c12d1] 104.197.45.156:38629]

 These are the corresponding list and follow-up watch requests from the Informer.
 However, if you compute when the watch started... it started ~9 seconds after the list finished.

 And the mystery is solved - the reason of those failures is client "THROTTLING" .... AGAIN !!!

There are basically two options to solve this:
- wait until https://github.com/kubernetes/kubernetes/pull/21104 is merged
- or increase the QPS limit in client in Density test

**Comment by wojtek-t** [comment]
@lavalamp - FYI ^ - yet another bunch of examples of "throttling watches" issue: #20750

**Comment by timothysc** [comment]
awesome!

**Comment by lavalamp** [comment]
Nice detective work. Hopefully this won't bite us again. Maybe we should
start logging a message when a client gets throttled for more than 50ms or
something, to make this easier to find if it shows up in other contexts?

On Fri, Feb 12, 2016 at 7:23 AM, Timothy St. Clair <notifications@github.com

**Comment by wojtek-t** [comment]
Yeah - that makes sense. I can add something tomorrow.

**Comment by wojtek-t** [comment]
Ok - I added logging suggested by @lavalamp 
This seems solved - I will reopen if if we observe it again at some point.
