### ISSUE TITLE
e2e flake: Services should work after restarting apiserver

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#19053]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10009/
```
Services should work after restarting apiserver [Disruptive]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:351 Dec 23 00:34:07.616: error while waiting for apiserver up: waiting for apiserver timed out
```

@kubernetes/goog-csi

**Comment by nikhiljindal** [comment]
This doesnt seem to have happened again.
Closing. Feel free to reopen if you see this again.

**Comment by gmarek** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10425/

**Comment by nikhiljindal** [comment]
The first link doesnt work anymore.

Logs from the second failure show:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:352
Expected error:
    <*errors.StatusError | 0xc2088c6300>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "pods \"execpod\" is forbidden: no API token found for service account e2e-tests-services-c0r1o/default, retry after the token is automatically created and added to the service account",
            Reason: "Forbidden",
            Details: {Name: "execpod", Group: "", Kind: "pods", Causes: nil, RetryAfterSeconds: 0},
            Code: 403,
        },
    }
    pods "execpod" is forbidden: no API token found for service account e2e-tests-services-c0r1o/default, retry after the token is automatically created and added to the service account
not to have occurred
```

**Comment by nikhiljindal** [comment]
The "no API token found for service account" error seems to have been added in https://github.com/kubernetes/kubernetes/pull/10523.
@liggitt Any ideas on why this could be happening and how to fix this?

**Comment by liggitt** [comment]
On creation of a namespace, a service account and token are generated by the controller manager. The e2e tests wait for that to happen before considering a namespace ready for the test to begin.

**Comment by lavalamp** [comment]
@nikhiljindal even if the link doesn't work, the files should be available where they were uploaded by plugging the number in the right place:

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/10009/artifacts/

**Comment by nikhiljindal** [comment]
Thanks for the link @lavalamp 
The error in that run is
```
error while waiting for apiserver up: waiting for apiserver timed out
```

I have now run the test more than 10 times locally and the test failed once with that error. It never failed with "no API token found for service account" error.
I am going to run it a few more times and report the stats.

**Comment by lavalamp** [comment]
@nikhiljindal Is there any chance it's the same problem as #19467?

**Comment by nikhiljindal** [comment]
That could be it. The test hasnt failed at all since that PR was merged.
I am going to keep this open for another day and close it tomorrow, if we do not see any failures today.

Reducing the priority.
