### ISSUE TITLE
e2e flake: Deployment deployment should scale up and down in the right order

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#19064]
It failed 3 times in last half a day:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13297/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13289/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13287/

cc @janetkuo @nikhiljindal @wojtek-t @kubernetes/goog-csi @kubernetes/goog-control-plane

**Comment by janetkuo** [comment]
I'm OOO and will be back on Jan 5. I don't have my laptop with me at this
moment. I'll look at this when possible.

Janet
On Thu, Dec 24, 2015 at 12:04 AM Marek Grabowski <notifications@github.com>
wrote:

> It failed 3 times in last half a day:
>
>
> http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13297/
>
> http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13289/
>
> http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13287/
>
> cc @janetkuo <https://github.com/janetkuo> @nikhiljindal
> <https://github.com/nikhiljindal> @wojtek-t <https://github.com/wojtek-t>
> @kubernetes/goog-csi <https://github.com/orgs/kubernetes/teams/goog-csi>
> @kubernetes/goog-control-plane
> <https://github.com/orgs/kubernetes/teams/goog-control-plane>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/19064>.
>
-- 
Best,
Janet Kuo

**Comment by gmarek** [comment]
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/21911

**Comment by wojtek-t** [comment]
And again:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/22001/

**Comment by spxtr** [comment]
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/22144/

**Comment by gmarek** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/13892/

**Comment by janetkuo** [comment]
Fix #19344 is merged. Will close this if the e2e test becomes stable.

**Comment by ixdy** [comment]
Still seems to be failing. As seen in https://github.com/kubernetes/kubernetes/pull/19156#issuecomment-169913089:
```
[31] â€¢ Failure [65.361 seconds]
[31] Deployment
[31] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:46
[31]   deployment should scale up and down in the right order [It]
[31]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:42
[31] 
[31]   Expected
[31]       <int>: 3
[31]   to equal
[31]       <int>: 2
[31] 
[31]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:232
```

**Comment by janetkuo** [comment]
All the fixes are merged. Will watch it in flaky tests build.

**Comment by janetkuo** [comment]
TODO: If this flaky test becomes stable, remove it from flaky test build.

**Comment by janetkuo** [comment]
Looks like these deployment e2e test flakes become stable: #19732 #19299 #19064 #18996. Closing them.
