### ISSUE TITLE
skydns not working on local ubuntu setup

### ISSUE THREAD

**Issue by jmartin127** [kubernetes/kubernetes#19076]
I have kubernetes running locally using hack/local-up-cluster.sh.  I then installed the add-ons using: cluster/ubuntu/deployAddons.sh.  However, DNS is not working properly as seen by:

Running nslookup within a simple buxybox pod:
```bash
$ kubectl exec busybox -- nslookup kubernetes.default
Server:    127.0.1.1
Address 1: 127.0.1.1

nslookup: can't resolve 'kubernetes.default'
error: Error executing remote command: Error executing command in container: Error executing in Docker Container: 1
```

Here are the skydns logs:
```bash
$ kubectl --namespace=kube-system logs kube-dns-v9-k9awk -c skydns
2015/12/23 23:35:18 skydns: failure to forward request "read udp 127.0.1.1:53: i/o timeout"
2015/12/23 23:35:20 skydns: failure to forward request "read udp 127.0.1.1:53: i/o timeout"
2015/12/23 23:35:21 skydns: failure to forward request "read udp 127.0.1.1:53: i/o timeout"
```

resolv.conf on the skydns pod 

```bash
$ kubectl --namespace=kube-system exec kube-dns-v9-k9awk -c skydns -- cat /etc/resolv.conf
search localdomain
nameserver 127.0.1.1
options ndots:5
```

resolv.conf on the host

```bash
$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search localdomain
```

The skydns pod is not running with net=host

The command line args for theskydns process.

```bash
# command = "/skydns"
    - -machines=http://127.0.0.1:4001
    - -addr=0.0.0.0:53
    - -ns-rotate=false
    - -domain=cluster.local.
```

Endpoints

```bash
$  kubectl get ep --all-namespaces
NAMESPACE     NAME         ENDPOINTS
default       kubernetes   192.168.245.149:6443
kube-system   kube-dns     172.17.0.2:53,172.17.0.2:53
kube-system   kube-ui      172.17.0.3:8080
```

Note: the only change I made to the default configuration was in cluster/ubuntu/config-default.sh.  I changed the following lines to make the service ip range compatible with the range listed in local-up-cluster.sh:
```bash
...
export SERVICE_CLUSTER_IP_RANGE=${SERVICE_CLUSTER_IP_RANGE:-10.0.0.0/24} 
...
DNS_SERVER_IP=${DNS_SERVER_IP:-"10.0.0.10"}
```

Any help you can provide would be greatly appreciated.

**Comment by jmartin127** [comment]
I was able to get this working by adding the following to the kubelet startup command within hack/local-up-cluster.sh:
--cluster-dns=10.0.0.10 --cluster-domain=cluster.local

**Comment by guowenbo045889** [comment]
holsy shit i gotta the same problem

**Comment by tobegit3hub** [comment]
@jmartin127  @guowenbo045889  You need to run [deployAddons.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/ubuntu/deployAddons.sh) if you want to create namespace and dns addon.
