### ISSUE TITLE
ABAC example_policy_file.jsonl missing "spec":

### ISSUE THREAD

**Issue by jdreno** [kubernetes/kubernetes#19072]
pkg/auth/authorizer/abac/example_policy_file.jsonl does not have the "spec" element wrapping the policy spec parts ("user" and afterward), as required for version v1beta1.  Hence it does not parse correctly.

**Comment by fabioy** [comment]
I'm not sure how relevant that example file is, since it seems to reference the deprecated v1beta1 endpoint?

**Comment by jdreno** [comment]
Either way, maybe I should have been clearer.  The point is the sample file in master does not work with the code in master.  Since the Policy struct in pkg/apis/abac/types.go has the spec element, the code expects the input json to have "spec" wrapping, which the sample file does not have.

**Comment by bgrant0607-nocc** [comment]
cc @erictune @liggitt
