### ISSUE TITLE
Deploying/updating pods across multiple namespaces

### ISSUE THREAD

**Issue by jason-riddle** [kubernetes/kubernetes#19073]
So far, the examples listed for when using namespaces deal with isolating different environments (dev, prod, etc.). My use case is slightly different. I don't want to use namespaces to isolate pods at an environment level but at a team level (team A, team B, etc.).  While it looks like namespaces can accomplish this, I also need to roll out the same replication controller and service to each namespace. As of now, the current way to do this looks like the following.

```
$ kubectl create -f template.yaml --namespace=teamA
$ kubectl create -f template.yaml --namespace=teamB
< repeated>
```

Is there an easier, more automated way to accomplish this?

**Comment by jason-riddle** [comment]
I would ideally like to specify multiple namespaces.
```
$ kubectl create -f template.yaml --namespaces=teamA,teamB
```
and if possible, avoid using a bash for loop, since if the task were up to <code>kubernetes</code> then it could stop or minimize propagating failures or handle any other scenario that might come up.

**Comment by resouer** [comment]
I'm afraid what your request is conflicts with kubernetes's design. Personally, I did not feel that hard to accomplish that with some scripts :)

cc the authority of kube api area: @bgrant0607

**Comment by jason-riddle** [comment]
Makes sense. Just wanted to check to make sure I wasn't reinventing the wheel.
