### ISSUE TITLE
Cassandra (example) doesn't start. 

### ISSUE THREAD

**Issue by lakhindr** [kubernetes/kubernetes#19071]
The simplest way to reproduce is to run kubernetes in Docker, using hack/local-up-cluster.sh
(latest code from github, today: commit ac0ce7257b89e01d96fee4cecc3560beff682e9c)

And then run 'kubectl create -f /usr/src/kubernetes/examples/cassandra/cassandra.yaml'

/usr/src/kubernetes# kubectl get po
NAME        READY     STATUS             RESTARTS   AGE
cassandra   0/1       CrashLoopBackOff   2          20s

Ubuntu 14.04, and also tried on Ubuntu 15.04

/usr/src/kubernetes# go version
go version go1.5.1 linux/amd64

/usr/src/kubernetes# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

If I run the this following command, i.e. not from example directory, 
kubectl run my-cas --image=cassandra. 
It runs 'fine', as in it doesn't crash right away :-) 

/usr/src/kubernetes# docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
cassandra                            latest              13ea610e5c2b        23 hours ago        374.8 MB
gcr.io/google_containers/cassandra   v7                  e5dbaa758837        6 days ago          337.7 MB
gcr.io/google_containers/hyperkube   v1.0.7              1becb4903462        8 weeks ago         214.2 MB
gcr.io/google_containers/pause       2.0                 8950680a606c        11 weeks ago        350.2 kB
gcr.io/google_containers/cassandra   v6                  9e5edb8845e2        5 months ago        337.1 MB
gcr.io/google_containers/pause       0.8.0               2c40b0526b63        8 months ago        241.7 kB

BTW, I have tried to run the example in a two machine (one master, one minion) linux server mode. Similar results.

**Comment by gang99zheng** [comment]
I have problem for cassandra v7 image also. The error is "permission denied".  cassandra v6 image runs just fine.

**Comment by cpwais** [comment]
also seeing this issue

**Comment by pwais** [comment]
also seeing this issue

**Comment by lakhindr** [comment]
I am curious, what kind of setup(s) Google has, that a code checkin does not flag such basic issues as seen here?! 

Unfortunately, contacting some google developers directly by email just hasn't evoked any response. Perhaps there is a relevant mailing list? Thanks.

**Comment by bgrant0607** [comment]
Ref #19114

cc @uluyol

**Comment by bgrant0607** [comment]
cc @brendandburns

**Comment by uluyol** [comment]
Looks like the version rev+image push that was supposed to follow #19114 wasn't completed.

**Comment by lakhindr** [comment]
I could build my own image, and Cassandra container doesn't crash anymore for me.

But can different nodes of Cassandra see each other, that is a different story :-)

**Comment by lakhindr** [comment]
The above mentioned Cassandra private image was tested off Commit ID: 0c5cc1bde1075e8bca90f83a352af7f38948b328 of Master branch, Jan 29.

Pulling in the latest changes of Master branch, commit ID: 635cf5877f9e52292d8d4930fd3c9c9aae6efeaa, Feb 02, I see some other issue, perhaps due to some new rules put in:

`# kubectl create -f cassandra.yaml` 

`Error from server: error when creating "cassandra.yaml": pods "cassandra" is forbidden: no API token found for service account default/default, retry after the token is automatically created and added to the service account`

**Comment by bgrant0607** [comment]
cc @johndmulhausen @amygdala

**Comment by bgrant0607** [comment]
ref #17728

**Comment by amygdala** [comment]
I will take a look.

**Comment by lakhindr** [comment]
Success: Using Master, and with a recompiled Cassandra image I can run in a stand alone cluster with multiple Cassandra nodes on Ubuntu 15.04. 

I still have these issues, however: 

1. I could not build a Cassandra image on Ubuntu 14.04.

2. I for some reason can not see multiple Cassandra nodes if I run them in docker-multi example: docs/getting-started-guides/docker-multinode/master.sh

(My code is @ commit id #b4822a4768d1521dd7854558a30b35dace8dec14,)

**Comment by jtblin** [comment]
I fixed running the cassandra example in #20746 but I had to downgrade from `v7` to `v6`. Not sure what the `v7` changes were but need a new image.

**Comment by uluyol** [comment]
I mentioned this a few posts ago, but in #19114 I fixed the permissions denied issue. This was supposed to be pushed as a new v8 image by someone from Google as I do not have permissions to push to gcr.io/google_containers.

**Comment by lakhindr** [comment]
@uluyol, I think your code is checked in, if not the image. I have compiled it, and it works, in my limited set of tests. The container can start. Thanks.

**Comment by goltermann** [comment]
@amygdala are you finishing this off?  I guess we need to repush that image?

**Comment by amygdala** [comment]
I believe it should now be fixed, now that my PR's in (with new image to go with it).  LMK if that is not the case.

**Comment by goltermann** [comment]
Closing - this works now from head:

$ kubectl create -f ./examples/cassandra/cassandra.yaml
pod "cassandra" created
$ kubectl get po
NAME        READY     STATUS              RESTARTS   AGE
cassandra   0/1       ContainerCreating   0          4s
$ kubectl get po
NAME        READY     STATUS    RESTARTS   AGE
cassandra   1/1       Running   0          24s

**Comment by saad-ali** [comment]
A user on google-containers is running in to the cassendra "permission denied" issue with the latest image `gcr.io/google-samples/cassandra:v8`. See [https://groups.google.com/forum/#!topic/google-containers/MDSj8NCI6-k](https://groups.google.com/forum/#!topic/google-containers/MDSj8NCI6-k).

Anyone have any ideas what it might be?
