### ISSUE TITLE
Representation of Organizational Entites

### ISSUE THREAD

**Issue by cameronbrunner** [kubernetes/kubernetes#19079]
@davidopp 

We have a need to be able to label pods with the 'primary' user in order for our custom scheduler to make better decisions during periods of resource contention.  Additionally we would like to have our users belong to one-to-many groups representing an organizational hierarchy such that our group base scheduling decisions can be made.  I think that native representation of organizational groups and users would be generally beneficial to other schedulers, user interfaces, and reporting solutions that integrate with Kubernetes.  To meet our needs the following would be required:

1) An admission controller that sets the 'user' based on the authenticated user making the API call on controllers and pods when a 'human' user is making the request and copies the 'user' object from the parent controller on pods created by controllers.  Additionally the controller would prevent direct modification or explicit setting of this field.
2) Provide an easy method to select all of the pods of a given user
3) Provide an easy method to select all of the pods owned by users in a given group
4) Handle the change of user group membership on existing resources

The following describes a possible implementation

1) Add 'user' and 'group' as top level objects.
2) A 'user' object represents a person who is responsible for the object
3) A 'user' object minimally has a name and a primary 'group' that could be null.
4) A 'group' object has a list of user objects and a list of groups that belong to the group.
5) Add 'user' to ObjectMeta

This would allow for complex hierarchies and an easy way to get all of the users in a given group or branch of the tree.

Why labels aren't enough...
- Doing all of the above with labels would require complex API queries to get all pods that belong to all users in a group when dealing with hierarchies.  
- Simply relying on labels also would require the complete relabeling/reannotating of all objects when organizational configuration changes.

**Comment by davidopp** [comment]
@erictune

**Comment by davidopp** [comment]
@deads2k

**Comment by davidopp** [comment]
@smarterclayton

**Comment by deads2k** [comment]
/cc @liggitt @kubernetes/kube-iam 

A few thoughts while I'm here.  OpenShift has a concept of user, identity, and group objects (https://docs.openshift.org/latest/rest_api/openshift_v1.html) and we're discussing the idea of ownership at the namespace boundary: https://github.com/openshift/origin/pull/6226.

However, the idea of resource ownership is not an obvious extension.  We've had discussion in other issues about which user "owns" an object.  See this open pull: https://github.com/kubernetes/kubernetes/pull/13925 as example of trying to track users associated with a resource.

I'm also not seeing how you'd be able to perform a reverse lookup more efficiently with data in a "special" location.  Do you have a specific proposal in mind?

Finally, I suspect that some implementation of users will be forthcoming.

**Comment by cameronbrunner** [comment]
Thanks for the pointer to that openshift issue; that does provide some insight.  I have been following #13925 as well since it does have a big part of what I am looking for.  A little background on why I am looking for this; we are working on integrating our scheduler (Grid Engine) in kubernetes and from our past experience user ownership of compute tasks is important when organizations implement resource allocation policies.  It would be useful for us to be able to quota against users, favor pods created by one user over another, and group pods of certain users under hierarchical organizational groups.  With our scheduler we could do just about all of this now in kubernetes if there was a user tag on resources since we can manage the organizational structure in our scheduler.  

Have some of these concepts in kubernetes would allow for kubernetes to do a similar thing and provide a cleaner interface into configuring our scheduler when it is integrated with Kubernetes.

As for your question:
> I'm also not seeing how you'd be able to perform a reverse lookup more efficiently with data in a "special" location. Do you have a specific proposal in mind?

Are you curious as why the change I suggested would be easier for the use case of 'get all pods that belong to all users in a group'?

Also very sorry about the delay in my response!

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by kargakis** [comment]
@kubernetes/sig-auth-misc

**Comment by liggitt** [comment]
There are no plans to introduce API objects representing authenticated identities at this time.

/close
