### ISSUE TITLE
Image pull progress should be exposed

### ISSUE THREAD

**Issue by stuartbassett** [kubernetes/kubernetes#19077]
If a container is waiting for an image to be pulled before it can start, it would be nice to see the progress of that pull in kubectl, so that the user can know if they have time for another cup of coffee.

An api endpoint to give a progress update, possibly with a watch option, would be ideal.
It would also be helpful to include this in the container information in each pod.

For example, running `kubectl desribe pod/<pod>` should return, in addition to all info currently returned, a field containing the % pulled (or number of bytes) of the image that each container uses.

Additionally, running `kubectl pull-progress pod/<pod>` should return a json encoded summary of each image being pulled in order to start a pod. This should also support a watch option, to notify the client of changes in the progress. There should be an equivalent HTTP API endpoint for this.

I'm interested in using this capability to provide loading bars on a UI.

**Comment by maclof** [comment]
I have a similar usecase for this, so I would also like to see this added :)

**Comment by fgrzadkowski** [comment]
@kubernetes/goog-ux

**Comment by bgrant0607** [comment]
See also #19695

cc @vishh

**Comment by smarterclayton** [comment]
Yeah, very common request.  We've ended up adding heuristics "If PodStatus Pending and no containers, display message to user `Probably Pulling, but we aren't sure the node is there`", etc.

**Comment by vishh** [comment]
We generate events for this purpose. We currently have a [`pulling` and
`pulled`](
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/event.go#L29)
event.

AFAIK, docker does not surface image pull progress. Did that change
recently?

**Comment by smarterclayton** [comment]
Practically speaking, people use pod status to figure out what the pod is
doing.  The vast majority of the time between "user creates pod" and "user
sees success" is going to be spent pulling.  The fact that we have no
discrete status indicating that appears to be a bug to people.  The event
is useful, but if we're updating the status anyway we should know whether
we're pulling immediately or not when we write the pod status.

**Comment by vishh** [comment]
By Status are you referring to the output of `kubectl describe` or
`PodStatus`? If users have insight into when the pod was accepted by the
kubelet and when it starts and completes (or fails) to pull an image, would
that suffice?

**Comment by samsabed** [comment]
The requester seems to want a progress measure 30% pulled or x/y

**Comment by smarterclayton** [comment]
The use cases people have raised with us is an obvious indicator on
pull in Pod Status.  Progress is nice but practically not required for
a well run infra.  Right now there is no distinction between waiting
for schedule and pull, which is a common state people get into.

**Comment by stuartbassett** [comment]
https://github.com/kubernetes/kubernetes/pull/25032

**Comment by vishh** [comment]
@smarterclayton 

>  Right now there is no distinction between waiting
for schedule and pull, which is a common state people get into.

The output of `kubectl describe pod` today includes events that provide the information you seek. Here is an example:

```shell
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----					-------------			--------	------		-------
  8s		8s		1	{default-scheduler }							Normal		Scheduled	Successfully assigned busybox-573201948-x4rg4 to kubernetes-minion-31zg
  8s		7s		2	{kubelet kubernetes-minion-31zg}	spec.containers{busybox}	Normal		Pulling		pulling image "busybox"
  7s		7s		1	{kubelet kubernetes-minion-31zg}	spec.containers{busybox}	Normal		Created		Created container with docker id 7ac36eac5dc5
  7s		7s		1	{kubelet kubernetes-minion-31zg}	spec.containers{busybox}	Normal		Started		Started container with docker id 7ac36eac5dc5
  7s		6s		2	{kubelet kubernetes-minion-31zg}	spec.containers{busybox}	Normal		Pulled		Successfully pulled image "busybox"
  6s		6s		1	{kubelet kubernetes-minion-31zg}	spec.containers{busybox}	Normal		Created		Created container with docker id 8a1d39975f1c
  6s		6s		1	{kubelet kubernetes-minion-31zg}	spec.containers{busybox}	Normal		Started		Started container with docker id 8a1d39975f1c
```

We can possibly add more events that include the progress, if an image pull were to take longer than expected. 

@stuartbassett 

I don't see why #25032 is needed yet.

**Comment by smarterclayton** [comment]
Events aren't that useful to uis, because you have to read and parse
the event stream and correlate.  It would be much better to have a
container condition indicating that in the pod status.

**Comment by vishh** [comment]
@smarterclayton 

> Right now there is no distinction between waiting
for schedule and pull, which is a common state people get into.

**Comment by vishh** [comment]
Wouldn't UIs include events as well, at-least the critical ones?

**Comment by smarterclayton** [comment]
They should, but in large list views that correlation and setup is
complicated.  Both kubectl get pods and a naive UI should be able to
easily show "pulling" because 95% of the time that's what is actually
happening, but when it isn't, that's really important (after 10s of
pending without seeing pulling, you could infer something else is
wrong).

**Comment by Random-Liu** [comment]
@smarterclayton It is hard to update the image pulling progress in pod status for now. Pod status is updated before each `SyncPod`, while the whole image pulling process happens during `SyncPod`.

The plan for now is to periodically (maybe every 5, 10 senconds) send event telling what is the current image pulling progress, which will at least tell user that whether the image pulling is stuck there.

**Comment by smarterclayton** [comment]
Doesn't pulling then effectively block all sync progress for other
containers in the same pod?  Or does it merely block parallel startup of
the containers.

**Comment by vishh** [comment]
@smarterclayton Assuming that exposing image pull progress is mainly for human consumption, would the following work?

* If an image is being pulled for a container, then update `ContainerStateWaiting` to contain a reason `PullingImage` and a message "progress: x%". The progress will be made available on a best-effort basis.
* If a pod is in`Pending` phase because images are being pulled, reflect that in `PodStatus.Reason` and `PodStatus.Message`. Message could be an aggregate across all containers. 

This would essentially push the burden of generating human friendly pod and container status to Kubelet.

**Comment by smarterclayton** [comment]
I don't even think progress is required, I'd be happy with a single
reason.  But I'll take the message and say that it'll help users even on a
best effort.

**Comment by smarterclayton** [comment]
Basically, yes, I think that would make 90% of clients better.

**Comment by vishh** [comment]
@stuartbassett Will you be able to re-purpose your PR (#25032) to do what's mentioned in https://github.com/kubernetes/kubernetes/issues/19077#issuecomment-216686379 ? I can provide more specific design details, if you have difficulty parsing https://github.com/kubernetes/kubernetes/issues/19077#issuecomment-216686379

**Comment by Random-Liu** [comment]
@smarterclayton Yeah, for now it will block starting of all other containers.

**Comment by vishh** [comment]
@Random-Liu Why not update the pod status manager even on pleg events, instead of updating it only from sync pod?

**Comment by Random-Liu** [comment]
@vishh We can do that, but we need to separate pod status updating out of `SyncPod`. I think that is also one option @yujuhong mentioned before.

**Comment by vishh** [comment]
@Random-Liu Can you file a separate issue detailing the change that needs to happen to move pod status updates out of syncPod method?

**Comment by Random-Liu** [comment]
@vishh Will do! :)

**Comment by ncdc** [comment]
/me digs out an old comment from @vishh 

> We generate events for this purpose. We currently have a [`pulling` and
`pulled`](

With the serialized image puller, you don't actually get the "pulling" event until the puller receives the request from the channel. Unfortunately, if a pull "hangs" for whatever reason, other pods will get stuck in Pending with no visible information and no events, because they're waiting for the serialized image puller to process the pull request, but the channel is blocked due to the hung pull.

**Comment by metametadata** [comment]
It would be great to be able to see the pull progress in the dashboard. I'm now starting minikube and all my deployments from scratch and have no idea how long I should wait for the pod(s) to be up.

**Comment by EamonKeane** [comment]
@metametadata agree with your sentiments. A workaround if you have poor connectivity is to minikube ssh, docker pull the required images for your pods, and set your pull policy in deployment spec to IfNotPresent.

**Comment by weisjohn** [comment]
If there isn't a way to get the progress into the pod description, is there a way that someone could articulate how to work around. In my scenario, I'm using `minikube` on a terrible downlink and am wanting to know whether or not I should give up waiting, move on to another task, or to let the progress continue.

**Comment by mabushey** [comment]
Normal  Pulling    10m    kubelet, ip-10-132-2-185.us-west-2.compute.internal  pulling image "764210488972.dkr.ecr.us-east-1.amazonaws.com/image:v136"

Is it pulling or locked? It is a large container.

**Comment by lanoxx** [comment]
With Windows image sizes can be in the Gigabytes, combine that with a low bandwidth line to a public registry and you get pull durations of hours. That makes some good progress indicator even more important.

**Comment by amadav** [comment]
Do we know if there exists any better way of achieving this?

**Comment by saschagrunert** [comment]
We could write up a KEP for this and pitch it in SIG Node. I’d be happy to drive this topic forward, but we should get at least 3 people on board. Who is in? 🙃

**Comment by bboreham** [comment]
@saschagrunert I am interested - what sort of commitment do you need?

**Comment by saschagrunert** [comment]
> @saschagrunert I am interested - what sort of commitment do you need?

I never wrote a KEP, but I’m thrilled to write one. I would just need relevant input, review and maybe implementation support. We could create a small work group in slack if you want. :)

**Comment by smarterclayton** [comment]
I commented on the cri-o issue, but I think we could separate this into two parts:

1. Progress for end users of kube (the issue this was raised for)
2. Better administrative / operational insight into pulls

The former is definitely Kube since it would have to be exposed via an api.  However the second is likely to be fairly specific to container runtime implementation and the storage that backs it.  And given the improvements in monitoring since this issue was opened, and that most deployments likely have prometheus or something like it watching their container runtimes, the second might be the best place to start both to make a concrete first step now for admins, while also learning more about how we might expose progress.  I do not think the former item was intended to solve the latter, and the latter is probably more broadly applicable since the vast majority of clusters are single team owned.

**Comment by bboreham** [comment]
FWIW my interest comes from working on tools layered on top of Kubernetes, where the rollout is initiated by something other that `kubectl` (for instance a git commit).
And we'd like that tooling to be able to feed back status and/or issues without guessing.

Status needs to be tied to a specific update, since multiple overlapping updates can be issued. 

I can't immediately see how Prometheus solves this requirement.

**Comment by saschagrunert** [comment]
> I commented on the cri-o issue, but I think we could separate this into two parts:
> 
>     1. Progress for end users of kube (the issue this was raised for)
>     2. Better administrative / operational insight into pulls

I'd be happy to push both topics forward. From the runtime perspective: If we have the data at hand, then we could expose it to any interface.

I see four major points, whereas the first one could be dropped from here:
1. Getting the data inside the runtime (out of scope from here)
2. Getting the data into the kubelet via the CRI API (KEP)
3. Exposing the data via the API Server (KEP)
4. Exposing the data via the CLI (KEP)

Anything else?

**Comment by saschagrunert** [comment]
I wrote an email to the SIG Node mailing list regarding the topic and the plan:
https://groups.google.com/forum/#!topic/kubernetes-sig-node/JHEus_TlZzA

**Comment by metametadata** [comment]
Is there a ticket where one could vote for disabling fejta-bot? It pollutes the long-standing issues and eventually closes the important issues where, I suspect, people simply got tired of interacting with the bot.

**Comment by turowicz** [comment]
Is this ever going to be a thing?

**Comment by aminmr** [comment]
Is there no progress on this most-wanted feature request?

**Comment by dims** [comment]
For those of you interested in this issue, please coordinate your interest into something actionable which in our community is a KEP:
- https://github.com/kubernetes/enhancements#is-my-thing-an-enhancement

Please feel free to use community resources (sig-node mailing list, agenda on sig-node meetings, google docs to seed discussion etc) to figure out what needs to be in the KEP and how the feature progress(es) through community process(es). Some good info can be found in:
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/feature-gates.md
- https://github.com/kubernetes/community/tree/master/contributors/devel/sig-architecture
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md

You should probably read one of the KEP(s) from before in sig-node for example in:
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-node

Looking forward to folks stepping up to help with this! thanks in advance.

**Comment by saschagrunert** [comment]
Closing the loop, there is a KEP: https://github.com/kubernetes/enhancements/issues/3542
