### ISSUE TITLE
Create an opaque integer resource

### ISSUE THREAD

**Issue by cameronbrunner** [kubernetes/kubernetes#19082]
@davidopp 

There should be a simple way to add a new resource to a node (kubelet), bind the resource to specific data source on the node (ie number of open file descriptors), and dynamically update the value at the API server.  Once available at the API server the dynamic resources can be used by the scheduler when placing pods.

If/when #19080 is implemented this functionality should be extended to Cluster Scoped resources as well.

**Comment by davidopp** [comment]
#9044 is related

**Comment by davidopp** [comment]
cc/ @madhusudancs 

This issue was originally about "non-consumable" resources but seems like we should be able to use a similar mechanism for adding new consumable resources, as long as the consumption model is simple (e.g. capacity is an integer, and it gets consumed in integer units by pods). #19049 has some discussion of using it for consumable resources.

**Comment by bgrant0607** [comment]
The description sounds like this is talking about consumable resources.

**Comment by davidopp** [comment]
ref/ #24317
ref/ https://github.com/kubernetes/kubernetes/issues/19049#issuecomment-170292193

**Comment by davidopp** [comment]
My suggestion is that the Kubelet config (eventually will be in ConfigMap -- hopefully soon) defines for each opaque resource
   1. a name (TODO: how to prevent conflicts)
   2. a mechanism to determine the capacity of the resource on that node (this is the tricky part -- we don't want Kubelet executing arbitrary shell commands specified by users)
   3. (eventually) a mechanism to determine the "usage" of the resource on that node
Kubelet would execute (2) at startup, and report it in NodeStatus.Allocatable. (If the resource's capacity can change dynamically, we'd need an additional mechanism to detect changes.)

The good news is that container.Resources and NodeStatus.Allocatable both use ResourceList which is a map[string]resource.Quantity where the string is the resource name. So the representation is fundamentally extensible.

It won't "just work" though, as code that reasons about resources uses the code in pkg/api/resource_helpers.go to pick out particular resources (e.g. Memory() and Cpu()). So we will definitely have to change (hopefully only add to) things like scheduler predicate functions, scheduler priority functions, and anywhere else we currently handle individual resources. 

We can target this for 1.4.

**Comment by davidopp** [comment]
I wonder if we should have a notion of alpha/beta/GA opaque resources. Today we introduce new resources using annotations, which has some annoyances like requiring '-o yaml' to be able to see them in kubectl, and requiring a fair amount of code to be changed when it goes from alpha to beta (i.e. stops being an annotation). Examples of alpha resources are network bandwidth, and nvidiaGpu. If opaque resources could have an alpha/beta/GA designation, then promoting them from alpha to beta would be trivial. Though I guess we could do this for all resources, e.g. give them a name like alpha.kubernetes.io/resourcename when they are alpha...

**Comment by cameronbrunner** [comment]
I like the idea of this resource promotion process and think it might even have some use as a concept outside of resources.

As for this comment:
> 2. a mechanism to determine the capacity of the resource on that node (this is the tricky part -- we don't want Kubelet executing arbitrary shell commands specified by users)

Something we do in Grid Engine for this type of stuff is provide a `loadsensor` interface that is a script that can be executed on the exec host.  The script is started by our execution daemon with commands being passed via stdin (things like 'provide your current status').  The scripts must output formatted data on stdout which is read by our execution daemon and sent to the cluster master.  Only admins can configure the script and rely on normal filesystem permissions to prevent tapering by unprivileged users.

Here is a more detailed overview if you are interested...

https://arc.liv.ac.uk/SGE/howto/loadsensor.html

**Comment by therc** [comment]
As I mention in https://github.com/kubernetes/kubernetes/pull/24836#issuecomment-217482186, using annotations and even labels makes alpha resources look so different that they become second class citizens when it comes to support from monitoring tools, etc., which in turn makes it even harder to graduate them, as there will be less extensive data and increased friction for users. (Also, when the resource graduates, early adopters might get discontinuities, gaps or other artifacts in their historical data. I'm not sure it's realistic to demand that monitoring tools pay a lot of attention to these transitions.)

Whatever we end up doing, we should have one consistent approach and we should get people working on tools onboard — or at least complicate their lives as little as possible.

**Comment by ConnorDoyle** [comment]
Created an issue in the features repo for this: https://github.com/kubernetes/features/issues/76.

Some preliminary design work is ongoing here: https://goo.gl/iJW2yq (also tracking in #28312 and #28313. There the issue is broken down into scheduling versus isolation.)

@therc, agree w/ your point about annotations & labels. In last discussion with sig-node and sig-scheduling it sounded like general consensus for representing them together with the first-class resources in the node status. IMO same arguments apply here as were made in #24836.

**Comment by ConnorDoyle** [comment]
@davidopp could you please assign me to this issue? #31652 implements the beginning of this. We can break off sub-issues to cover the other items mentioned here.

**Comment by dims** [comment]
there you go @ConnorDoyle

**Comment by timothysc** [comment]
@ConnorDoyle Features repo is where epics live.  I'd probably move any future thoughts there and close this as the initial chapter.  Right now, we have a tremendous backlog of issues that seem to span releases since epoch.

**Comment by ConnorDoyle** [comment]
OK, this issue is already linked from the feature issue for posterity. I'm ok with closing it too.
