### ISSUE TITLE
Defaulting is 35% of total conversion time and ~10% of total decode time

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#19084]
Running a before (on top of #19047) and after with defaulting removed from our generated code (not generated), total conversion time drops significantly, and number of allocations is halved.

```
benchmark                                      old ns/op     new ns/op     delta
BenchmarkPodConversion-8                       14676         9143          -37.70%
BenchmarkNodeConversion-8                      12712         7005          -44.89%
BenchmarkReplicationControllerConversion-8     15129         10460         -30.86%

benchmark                                      old allocs     new allocs     delta
BenchmarkPodConversion-8                       81             49             -39.51%
BenchmarkNodeConversion-8                      74             38             -48.65%
BenchmarkReplicationControllerConversion-8     79             53             -32.91%

benchmark                                      old bytes     new bytes     delta
BenchmarkPodConversion-8                       9011          5170          -42.63%
BenchmarkNodeConversion-8                      7267          3425          -52.87%
BenchmarkReplicationControllerConversion-8     9236          5906          -36.05%
```

We should only generate defaulting for objects that have them, and we should inline to public methods (like #19047) rather than going through reflection.  It's likely we can realize most of the before / after improvements with no reflection.  With protobuf in place (#17922), conversion is going to be the slowest part of decode/encode (~9us for pod conversion, 6us for proto deserialize, 5us for defaulting, and 1-2us overhead).

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery @wojtek-t

**Comment by wojtek-t** [comment]
+1

We should also migrate our conversion generator to the new Daniel`s framework in the meantime (for better maintainability).

**Comment by smarterclayton** [comment]
Yes, I found several places where there are bugs caused by the two
pass "find imports / write function" code.

**Comment by smarterclayton** [comment]
Fixed.
