### ISSUE TITLE
Optimization in copy: structs with only primitives (no pointers) can be bulk assigned

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#19085]
DeepCopy is used in our etcd caching path, watch paths, and cache store paths.  Some of my upcoming changes (#17922) remove it from the decode critical path except in certain cases.  

Right now it's roughly ~3us and ~25 allocations to perform a copy:

```
BenchmarkPodCopy-8                            300000          4308 ns/op        3280 B/op         25 allocs/op
BenchmarkNodeCopy-8                           300000          3706 ns/op        2464 B/op         18 allocs/op
BenchmarkReplicationControllerCopy-8          300000          3908 ns/op        2960 B/op         22 allocs/op
```

That's not terrible, except this is the most expensive operation in those paths today in terms of master CPU.  A few optimizations to deep copy are worth experimenting with:
- Replace individual primitive assignment of structs with bulk assignment (not sure how well this is optimized)
  
  ```
  func deepCopy_v1_AWSElasticBlockStoreVolumeSource(in AWSElasticBlockStoreVolumeSource, out *AWSElasticBlockStoreVolumeSource, c *conversion.Cloner) error {
      out.VolumeID = in.VolumeID
      out.FSType = in.FSType
      out.Partition = in.Partition
      out.ReadOnly = in.ReadOnly
      return nil
  }
  ```
  
  with copy assignment 
  
  ```
  func deepCopy_v1_AWSElasticBlockStoreVolumeSource(in AWSElasticBlockStoreVolumeSource, out *AWSElasticBlockStoreVolumeSource, c *conversion.Cloner) error {
      *out = in
      return nil
  }
  ```
- Inline public methods for deep copy instead of reflection (nested s.DeepCopy() calls)
- Have all objects expose DeepCopy() method instead of reflection, generate them into individual packages
- Use copy() on arrays of primitives
- Inline common copies? (compiler should do that)

**Comment by lavalamp** [comment]
I recall making an optimization like this to fix []byte getting copied one at a time... But that was before the generators existed.

**Comment by smarterclayton** [comment]
Yup, but the generators actually delegate to the function today (we don't bulk operate on all primitive types).

**Comment by sttts** [comment]
Here is the result of a number of optimizations: https://github.com/kubernetes/kubernetes/pull/28592

Roughly twice as fast.

**Comment by smarterclayton** [comment]
Fixed.
