### ISSUE TITLE
Cluster Scoped Resources

### ISSUE THREAD

**Issue by cameronbrunner** [kubernetes/kubernetes#19080]
@davidopp 

Kubernetes should add Cluster Scoped Resources .  Cluster Scoped resources are consumable resources that do not belong to any specific node but instead belong to the cluster.  A simple example are software licenses that can be shared through an network license server.  These resources should be tracked as normal consumable resources and should be usable by the scheduler when determining if a pod can actually be scheduled.

Looking at the existing objects in Kubernetes I think there is definitely with expanding the PVClaim model to meet this request. I think if some thought is put into generalizing the functionality of PVClaims into a generic Claim type many of the gaps would be addressed. Group initialization (creating a pool of 100 resource instances) and being able to specific a resource magnitude are obvious enhancements that would have to be made.

**Comment by combk8s** [comment]
@davidopp @cameronbrunner 
+1
Recently, our team is working on add a cluster scoped resource (muti IPs) to k8s, and it’s now in heavy development, we plan to send a proposal of the design to community in a couple of days, hoping it could meet the general requirements of community.
But PVClaim model maybe have some problem in RC. PVClaim need an unique name but pod of RC need self's resource claim for public IP.

**Comment by mqliang** [comment]
multi IP is very flexible and useful, expect your PR.

As far the PV Claim model, it may not suitable for IPs: for PV, we need bind it to Pod, but for IP, it's a better choice to put it in ReplicationController, and let rc to distribute it to RC.

**Comment by davidopp** [comment]
> But PVClaim model maybe have some problem in RC. PVClaim need an unique name but pod of RC need self's resource claim for public IP.

> As far the PV Claim model, it may not suitable for IPs: for PV, we need bind it to Pod, but for IP, it's a better choice to put it in ReplicationController, and let rc to distribute it to RC.

I think we eventually want to do explicit scheduling of PVs. I haven't kept up with all of the PV proposals though. It would be much better if we can try to unify IMO.

@thockin @vishh @markturansky @bgrant0607 @smarterclayton @kubernetes/rh-storage @pmorie 

Also see #17324

**Comment by thockin** [comment]
If I understand what you mean by explicit scheduling wrt PV, yeah, I think
it will come, eventually.  But that doesn't solve the RC problem.

We have discussed arbitrary equiv groups of PV, where an RC pulls a PV from
the group, but we have not designed it further - time went to nominal
services (still not done) which seemed like it was/is more important.

Gentrifying PV to an arbitrary cluster Resource sounds attractive, but I am
worried about expressiveness - PV actually has a payload.

But PVClaim model maybe have some problem in RC. PVClaim need an unique
name but pod of RC need self's resource claim for public IP.

As far the PV Claim model, it may not suitable for IPs: for PV, we need
bind it to Pod, but for IP, it's a better choice to put it in
ReplicationController, and let rc to distribute it to RC.

I think we eventually want to do explicit scheduling of PVs. I haven't kept
up with all of the PV proposals though. It would be much better if we can
try to unify IMO.

@thockin <https://github.com/thockin> @vishh <https://github.com/vishh>
@markturansky <https://github.com/markturansky> @bgrant0607
<https://github.com/bgrant0607> @smarterclayton
<https://github.com/smarterclayton> @kubernetes/rh-storage
<https://github.com/orgs/kubernetes/teams/rh-storage> @pmorie
<https://github.com/pmorie>

Also see #17324 <https://github.com/kubernetes/kubernetes/issues/17324>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/19080#issuecomment-167257778>
.

**Comment by bgrant0607** [comment]
@cameronbrunner Could you please explain in more detail what you'd plan to use this for?

Maybe relevant: #18016

**Comment by cameronbrunner** [comment]
We have 100 licenses for an application with these licenses managed by a flexlm license server.  We can use these licenses on any machine in our cluster but we are limited to running 100 concurrent instances of the application.  We do not want Kubernetes to start up more than 100 concurrent containers that require this license.  

The behavior of licenses in this example is similar to a consumable host resource, like mem, it's just shareable across hosts instead of being host bound.

**Comment by bgrant0607** [comment]
Ref https://issues.apache.org/jira/browse/MESOS-2728

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by davidopp** [comment]
https://groups.google.com/forum/#!topic/kubernetes-users/eUUrdlBwa7g

**Comment by nikhildl12** [comment]
> Recently, our team is working on add a cluster scoped resource (muti IPs) to k8s, and it’s now in heavy development, we plan to send a proposal of the design to community in a couple of days, hoping it could meet the general requirements of community.

@combk8s: is there a proposal for a cluster scoped resource?

**Comment by vishh** [comment]
Assigning to myself since I have some ideas on how this issue can be resolved. I'll post a design proposal when I get some time.
