### ISSUE TITLE
misplaced cassandra-controller.yaml excerpt in examples/cassandra

### ISSUE THREAD

**Issue by bbgw** [kubernetes/kubernetes#19098]
It should be `cassandra.yaml` at the place of the current first occurrence of the sample `cassandra-controller.yaml`.

**Comment by fgrzadkowski** [comment]
@bbgw Can you please send a PR which fixes it?

**Comment by pwais** [comment]
The example also mentions v6 while the pod confs use v7.  @fabianofranz could you please have somebody at Google figure out maintenance for this example? See also #19071 .  I've tried this example at various times over the past few months and you are consistently shipping broken software here.

**Comment by fabianofranz** [comment]
This should be @mwielgus or @brendandburns. ^^

**Comment by bgrant0607** [comment]
cc @johndmulhausen @amygdala

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/config-best-practices.md#naked-pods-vs-replication-controllers-and-jobs

**Comment by bgrant0607** [comment]
@amygdala See PR #19098

**Comment by bgrant0607** [comment]
Oops, PR #20746
