### ISSUE TITLE
how to restore data form pod when use rc 

### ISSUE THREAD

**Issue by yunzhonghe71** [kubernetes/kubernetes#19096]
For example,I use a rc to start a pod to run a mongo database docker ,when the pod failures,the rc will automatically start another pod,but the data from the previous pod losts,how should i do to restore the data?

**Comment by fgrzadkowski** [comment]
What data do you mean? If you'd like to persist the data then they should be written to a persistent storage like GCEPersistentDisk (or equivalent).

**Comment by fgrzadkowski** [comment]
Also - can you please open a stackoverflow question for this? Please see this document for more ways to seek help/advise:

https://github.com/kubernetes/kubernetes/blob/master/docs/troubleshooting.md

**Comment by yunzhonghe71** [comment]
ok，thanks
