### ISSUE TITLE
[User Story] Improve HPA to bring to GA 

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#19095]
- [ ] HPA needs to handle discovery, controller credentials, privilege escalation protection - https://github.com/kubernetes/kubernetes/issues/16177

**Comment by jayunit100** [comment]
cc @timothysc

**Comment by davidopp** [comment]
@kubernetes/autoscaling

**Comment by davidopp** [comment]
This is labeled as v1.2 -- is there actually something to do for 1.2 here?

**Comment by piosz** [comment]
Closing as dupe of #18528
