### ISSUE TITLE
RFC: move region/zone informatiopn to node.spec or annotation, instead of as a label

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#19102]
@vishh @davidopp @justinsb @bgrant0607  @gambol99 @dchen1107 
https://github.com/kubernetes/kubernetes/pull/17265 and https://github.com/kubernetes/kubernetes/pull/16866  introduced  region/zone labels.

I propose to move region/zone information to `node.spec`, instead of as a label, since this is the information which kubelet could get from cloud provider, just like `ExternalID` and `ProviderID`. 

Make this information as label is flexible, but it will lead some updates and deletions related issue, see https://github.com/kubernetes/kubernetes/issues/18394

After all, if we make region/zone information a node label, why not make `ExternalID` and `ProviderID` as label, too?

**Comment by resouer** [comment]
Sorry man, have to -1 for this, `region/zone` information is not always comes from cloud provider, it  should be able to be set manually by admin (for example, consider the case that your k8s is running on bare-metal).

Moreover, being a `label` means it can be easily filtered by node selector and  updated freely on the fly, while `Node.Spec` wouldn't (not so easy at least).

**Comment by mqliang** [comment]
> region/zone information is not always comes from cloud provider, it should be able to be set manually by admin (for example, consider the case that your k8s is running on bare-metal).

If k8s run on bare-metal, admin could still set it manually(such as set it by startup flag, just like `nodeName`), if not set, all the nodes would belong to the same region/zone by default.

> being a label means it can be easily filtered by node selector and updated freely on the fly

Labels is flexibly, but it will lead some updates and deletions related issues https://github.com/kubernetes/kubernetes/issues/18394, and `Node.Spec` can also support update.

**Comment by mqliang** [comment]
In addition, labels ***should*** always be set by user, not by the some components of k8s. If some components of k8s, such as scheduler need those information, at least it ***should*** set as annotation, not label.

**Comment by liggitt** [comment]
Things that use selectors should use labels. Zone and region are two common dimensions for scheduling, but there could be others. I wouldn't want to make zone and region special cases. I also wouldn't want to repeat the zone/region info in the spec and in labels

**Comment by liggitt** [comment]
I think the root cause of https://github.com/kubernetes/kubernetes/issues/18394 is the node managing its own zone/region/label info. I think you'll have issues regardless of where that info is stored (spec or labels) if it is unclear whether the node has responsibility for that or not.

**Comment by mqliang** [comment]
> Things that use selectors should use labels.

But labels ***should*** always be set by user, not by the some components of k8s. Even if some components of k8s(such as scheduler need those information), at least it should set as ***annotation***, not label.

If we want those information easily filter by selector, why not extend annotation and add "AnnotationSelection", AFAIK, there are some proposal to make annotation more similar with label, eg. https://github.com/kubernetes/kubernetes/issues/18801

**Comment by liggitt** [comment]
If the kubelet sets labels that the user configured, I think that counts as user-set. When it is indirectly set via cloud provider data, that is a little less clear. I would prefer the kubelet-set labels be much more constrained ("set these labels in particular" rather than "stomp all labels"), but I still prefer region/zone being a specific use of a general mechanism, and wouldn't want to promote those to spec fields

**Comment by mqliang** [comment]
If most of maintainer disagree to move region/zone to `node.spec`, I wholeheartedly recommend to make it as annotation, we can benefit a lot if they are set as annotation:

1) it can be easily easily filtered by "AnnotationSelector" once https://github.com/kubernetes/kubernetes/issues/18801 is implemented. 

2) In addition, user could write a admission controller to apply those annotation automically once https://github.com/kubernetes/kubernetes/pull/18262 is implemented. https://github.com/kubernetes/kubernetes/pull/18262 propose an admission controller to list&watch a API resource `PodPolicy`, then apply annotation to pods base on the  `PodPolicy`, which is useful to select scheduler in a multi-scheduler system. We can use it to simulate a multi-zone cluster when k8s is running on bare-metal.

3) Last, and most important. It dose not violate the principle that "label is set by user, and annotation is set by component of k8s".

**Comment by davidopp** [comment]
@mqliang 

>  labels should always be set by user, not by the some components of k8s.

> But labels should always be set by user, not by the some components of k8s

> label is set by user, and annotation is set by component of k8s

Why do you say this? I looked at
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/labels.md
and it didn't say anything about only being set by humans.

**Comment by mqliang** [comment]
@davidopp 
>  Labels are intended to be used to specify identifying attributes of objects that are meaningful and relevant to users, but which do not directly imply semantics to the core system. 
Labels enable users to map their own organizational structures onto system objects in a loosely coupled fashion, without requiring clients to store these mappings.

I may misunderstand, it implies labels is user-oriented, and annotation is system-oriented

**Comment by bgrant0607** [comment]
@mqliang you didn't misunderstand.

In general, I do want to reserve labels for users, on objects they create. 

However:
* nodes are part of the infrastructure and ordinary users can't set their labels anyway
* labels are used for selection and currently the information needs to be labels for nodeSelector to be able to constrain against them
