### ISSUE TITLE
Build kubectl statically

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#19109]
Why is `kubectl` built dynamically for `amd64` at this time?
Is there any specific reason for this or could we change `kubectl` to be statically built?

For example: on hosts like RancherOS, this is a very big problem, because by default no `libc` is present, so `kubectl` doesn't work.

I assume it's only this line that will have to be updated: https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L134
I could send a PR that includes `kubectl` in that list.

@brendandburns @zmerlynn @thockin @jbeda @gmarek

**Comment by gmarek** [comment]
@bgrant0607 @janetkuo

**Comment by thockin** [comment]
I think it was the default and we only changed things to static if we had
good reason.  It makes sense to me to have it static.

**Comment by luxas** [comment]
Fixed with #19193 (forgot to make an auto-closing issue, so doing it manually :D)
