### ISSUE TITLE
Document use of AWS ECR with k8s

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#19113]
AWS now has a built-in registry called [ECR](https://aws.amazon.com/blogs/aws/ec2-container-registry-now-generally-available/), similar to Google Container Registry.

We should document how to use ECR for those kubernetes users who wish to use ECR with their AWS-hosted K8s clusters.

We should document and test how to get a credential from AWS (e.g using `aws ecr get-login`), and how to put that in a secret for use with imagePullSecrets, or how to `scp` that credential to all VMs.

**Comment by coleca** [comment]
This might be a problem to use with a K8S secret/imagePullSecrets since the AWS ECR credentials are only good for 12 hours according to this: 

http://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html

Unless maybe you create a container to self-update the secret on a schedule?

**Comment by therc** [comment]
This is how the ECS agent does it: https://github.com/aws/amazon-ecs-agent/blob/v1.7.0/agent/engine/dockerauth/ecr.go#L49

So perhaps lazydockerkeyring.Lookup() would refresh the credentials on demand when called by dockertools:docker and it'd get bonus points if it doesn't refresh them unless needed (it does say "lazy" right there...). That means that it would now need to know about AWS and potentially cooperate with the AWS cloud provider code (although I'm sure someone will try to run containers on bare hardware, trying to talk to ECR. Heck, I might end up doing that.)

The rkt PullImage() code seems to use similar code.

**Comment by therc** [comment]
Ah, credentialprovider already has a plugin mechanism, with only the GCP one being implemented at the moment, complete with credential TTL...

**Comment by erictune** [comment]
Please feel free to send a PR that adds a new credentialprovider that works on AWS.

**Comment by therc** [comment]
I am working on it. First, though, I have another PR to add aws-sdk-go 1.0.7, which is the first to support ECR APIs.

**Comment by therc** [comment]
I've been using the PR in our test clusters, but haven't been getting much feedback. It would be nice to have it in 1.2.

**Comment by ndtreviv** [comment]
+1 I'm using ECR on Kubernetes deployed to AWS, but just get PullImageError on all the pods.
The total set of instruction I have come across is to prefix the image part of the config with the ECR dets, eg:

`ID.dkr.ecr.REGION.amazonaws.com/IMAGE:TAG` 

But it's not working :(

Using kube cluster setup scripts from here: curl -sS https://get.k8s.io | bash

**Comment by innovia** [comment]
I am running the 1.2.0-beta.1 on local virtualbox
seems like the ECR is only supported  on ec2 instances since they have the metadata service of 169.254.169.254 that the plugin uses to fetch region etc..

@therc how can i get the ecr pluging to work locally on virtualbox? i was forced to copy all the images to dockerhub and add a secret, would be great not to do that and use the ecr for everything

**Comment by erictune** [comment]
@innovia 
Follow AWS instructions to docker login to ECR:
 http://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth

Then scp copy your .docker/config.json to /root/.docker/config.json on your virtualbox VM.  Should work.

**Comment by innovia** [comment]
@erictune there's a problem using that approach, since the login to ECR is not like docker hub AWS generate a valid token for 12 hours the code in kubernetes supports renewing the authentication token

**Comment by erictune** [comment]
oh, bummer.

**Comment by felipejfc** [comment]
how is the status here? are there any integrations between ecr and kubernetes that automatically updates the ECR login information? (since it is valid for only 12 hours?) Currently I'm updating them manually in every deploy

**Comment by therc** [comment]
This has worked for months from HEAD (and is in 1.2) if the cluster and ECR are in the same region. There's another PR out for cross-region support.

**Comment by felipejfc** [comment]
I'm using 1.2.2 and I always have to update the ecr login... The cluster is in us-east-1 and also the ECR repos... Do I need some specific configuration to make it work?

**Comment by therc** [comment]
Update? We never had to do it and it's been working for months, in multiple clusters. The kubelet does it if the AWS cloudprovider is on. If you're doing it in the deployment, it sounds like you are using your own set of ECR credentials.

**Comment by msaffitz** [comment]
@felipejfc make sure your kublets are running with the cloud-provider set to AWS (`--cloud-provider=aws`).  You should be able to confirm this by doing a `kubectl describe nodes` and confirming that the instance type appears in the label.  For example: 

`Labels:			beta.kubernetes.io/instance-type=m4.xlarge,...`

**Comment by felipejfc** [comment]
@msaffitz maybe I assumed I needed to include pullSecret into my RC's because it was needed in my staging cluster (in us-west-1), I'm using ECR in (us-east-1) where also is my production cluster... I'll try in the production cluster without adding the secret in my next deploy to see what happens...

Ty

**Comment by apinnecke** [comment]
@felipejfc Did it work without the secret?

**Comment by rca** [comment]
For those looking for docs: http://kubernetes.io/docs/user-guide/images/#using-aws-ec2-container-registry

**Comment by satyrius** [comment]
I have a *Kubernetes* cluster on a bare metal. How to work with *ECR* outside *AWS*?

**Comment by bryanerayner** [comment]
It's unclear to me how to start `minikube` using the AWS container registry.

What options exist for this?

**Comment by elblivion** [comment]
I'm successfully using ECR in a different region (and AWS account, to boot) - the documentation quoted above says this is unsupported though, so I'm unsure about whether to proceed with this in a production environment.

Running 1.5.2 on AWS eu-west-1, ECR registry in us-east-1.
```
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by therc** [comment]
I added the cross-region functionality since that documentation was written. Thanks for catching it, your scenario is indeed meant to be fully supported.

**Comment by elblivion** [comment]
@therc happy to pitch in and submit a PR for the docs if you point me in the right direction.

**Comment by therc** [comment]
Already created https://github.com/kubernetes/kubernetes.github.io/pull/2359

**Comment by olalonde** [comment]
It seems docker no longer stores credentials directly in `.docker/config.json`? Mine is simply:

```json
{
        "auths": {
                "MY_AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com": {}
        },
        "credsStore": "osxkeychain"
}
```

Opened an issue here: https://github.com/moby/moby/issues/32733

**Comment by gfegit** [comment]
@olalonde Thanks for tip.

**Comment by dolobanko** [comment]
@olalonde Thanks for tip.

**Comment by afirth** [comment]
I think this is done by @therc? https://kubernetes.io/docs/concepts/containers/images/#using-aws-ec2-container-registry and https://github.com/kubernetes/website/pull/2359

**Comment by Blue4x4Rebel** [comment]
Any word on support for bare-metal instances using ECR? I have tried automating this by scheduling aws ecr get-login from my hosts, but that only seems to work if kubernetes is restarted afterward. How can we use the provider without enabling all cloud functions?

**Comment by azban** [comment]
@satyrius, @Blue4x4Rebel, and other people trying to do this from outside of ec2: i got this working with the help of https://medium.com/@xynova/keeping-aws-registry-pull-credentials-fresh-in-kubernetes-2d123f581ca6 (thanks @xynova). you can then use this through standard [imagePullSecrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret)
