### ISSUE TITLE
Update kube-build to go1.5.2

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#19110]
Since @mikedanese updated the ci go version to `1.5.2`, shouldn't `kube-build` use it too?

It will also make cross-compilation easier, see this blog post: http://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5
So, if we upgrade to `go1.5.2`, we will not need `build/build-image/cross/Dockerfile` anymore.

Just now I'm working on getting ARM support into mainline k8s: #17981, and found out that we are able to build all binaries for ARM on `amd64` hosts. [Script](https://gist.github.com/luxas/e319b314f22b18243b1d)

To upgrade to `go1.5.2` would be a good first step, and I could make a PR for that

@brendandburns @jbeda @proppy @zmerlynn @mikedanese

**Comment by mikedanese** [comment]
We are working on it in #14873. See https://github.com/kubernetes/kubernetes/pull/14873#issuecomment-166703378

**Comment by mikedanese** [comment]
Closing as dup
