### ISSUE TITLE
kubernetes-soak-continuous-e2e-gke/gce failing

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#19118]
kubernetes-soak-continuous-e2e-* tests have been failing since at least Dec 22 

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gce/

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gke/ 

GCE failed tests:
Kubernetes e2e suite.Job should run a job to completion when tasks sometimes fail and are not locally restarted
Kubernetes e2e suite.Garbage collector should handle the creation of 1000 pods
Kubernetes e2e suite.Deployment deployment should delete old pods and create new ones
Kubernetes e2e suite.Kubelet [Serial] regular resource usage tracking for 0 pods per node over 20m0s
Kubernetes e2e suite.Cadvisor should be healthy on every node.
Kubernetes e2e suite.Resource usage of system containers [Serial] should not exceed expected amount.
Kubernetes e2e suite.Kubelet [Serial] regular resource usage tracking for 35 pods per node over 20m0s
Kubernetes e2e suite.SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching [Conformance]
Kubernetes e2e suite.Kubectl client Kubectl run --rm job should create a job from an image, then delete the job [Conformance]
Kubernetes e2e suite.KubeProxy should test kube-proxy
Kubernetes e2e suite.NodeOutOfDisk [Serial] runs out of disk space
Kubernetes e2e suite.Services should be able to up and down services
Kubernetes e2e suite.Kubelet [Serial] experimental resource usage tracking for 100 pods per node over 20m0s
Kubernetes e2e suite.Networking should function for intra-pod communication [Conformance]
Kubernetes e2e suite.SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]
Kubernetes e2e suite.kubelet Clean up pods on node kubelet should be able to delete 10 pods per node in 1m0s.
Kubernetes e2e suite.SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run
Kubernetes e2e suite.Daemon set should run and stop simple daemon

GKE Failed tests: timing out

**Comment by mwielgus** [comment]
@roberthbailey to triage

**Comment by roberthbailey** [comment]
@ihmccreery can you take a look at this and verify that we are running the expected set of tests? If so, then we can dig in deeper. 

The GCE build is completing successfully after ~3 hours and the GKE build is timing out after 6 hours.

**Comment by ihmccreery** [comment]
The tests that are running look fine to me.  From a somewhat cursory glance, looks like lots of tests are failing because they can't start pods.

**Comment by ihmccreery** [comment]
Looks like pods aren't moving from Pending to Running.  The scheduler seems to be scheduling pods to the node `qy4b` despite that node being in the `Not Ready` state.

That node is complaining directly to the command line when I log in:

```
kernel:[546478.600114] unregister_netdevice: waiting for vetha404972 to become free. Usage count = 1
```

Assigning to @dchen1107 to investigate further.

**Comment by ihmccreery** [comment]
This also seems like a scheduler problem though; we shouldn't be scheduling pods on `Not Ready` nodes, right?  @mikedanese for help on that.

**Comment by roberthbailey** [comment]
https://github.com/docker/docker/issues/5618 seems like it may also be related.

**Comment by ihmccreery** [comment]
@kubernetes/goog-control-plane for scheduling pods on `Not Ready` nodes.

**Comment by yujuhong** [comment]
This is happening again on one node in the soak cluster.
```
Message from syslogd@gce-soak-weekly-minion-61lh at Jan 15 19:14:15 ...
 kernel:[286304.952109] unregister_netdevice: waiting for veth916a835 to become free. Usage count = 1
```

**Comment by mikedanese** [comment]
This appears to be a kernel bug. Not sure how to proceed.

**Comment by yujuhong** [comment]
Rebooting the machine should temporarily solve the problem.

**Comment by quinton-hoole** [comment]
@mikedanese To be clear we have two problems here as far as I can tell:

1. The problem with the ethernet device, which could be a kernel bug.
2. The fact that the scheduler is continuing to try to schedule pods onto a node that is Not Ready.  

I don't think that it's worth solving 1, but 2 is definitely a bug in our scheduler that should be fixed.

Or am I missing something?

Q

**Comment by mikedanese** [comment]
I was not able to observe or reproduce 2 when I looked a week ago. Is that consistently reproducible? @ihmccreery can you give me some pointers? Is it possible that the pods were scheduled before the node reported NotReady?

**Comment by mikedanese** [comment]
Also since evictions are rate limited and the nodes if nodes are flapping NotReady 30 seconds, Ready 5 minutes, if nodes get scheduled to and pods aren't getting evicted during NotReady then node controller and scheduler are working as intended.

**Comment by mikedanese** [comment]
I think the main issue here is 1.

**Comment by quinton-hoole** [comment]
@mikedanese Good point.  As an aside I think that we should potentially have a mechanism in place for quarantining nodes that fail often/repeatedly.  We will of course need to be careful of "poisoned pods" which, when launched on a node, cause it to fail often and get quarantined. If the poison pod then gets rescheduled to another node in the cluster, eventually all nodes could become quarantined.  That would be very bad. But repeated hardware or system problems on a node should ultimately cause pods not to scheduled there, somehow, safely.

@mml @davidopp FYI in case they have any thoughts on this (i.e. how to prevent scheduling pods onto flapping nodes in a safe way).

**Comment by quinton-hoole** [comment]
@mikedanese I don't think that we can realistically solve 1 in a general way in kubernetes.  We're always going to get nodes with flaky hardware and/or flakey/buggy OS software.  The best we can hope to do is try to recognise it as such, tag it for repair/upgrade, and avoid scheduling onto it until it's fixed.

**Comment by mikedanese** [comment]
Ya I'm not sure how we would want to handle it. Here's the describe for the offending node if interested

```
mikedanese@gce-soak-weekly-master:~$ kubectl describe no gce-soak-weekly-minion-61lh 
Name:                   gce-soak-weekly-minion-61lh
Labels:                 failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-f,kubernetes.io/e2e-05622a95-b9b3-11e5-9983-42010af01555=42,kubernetes.io/e2e-16adc390-ba7f-11e5-8fb5-42010
af01555=42,kubernetes.io/e2e-2a9bc339-bb54-11e5-bd91-42010af01555=42,kubernetes.io/e2e-344d05bb-ba35-11e5-ad6c-42010af01555=42,kubernetes.io/e2e-3a95593b-bb1a-11e5-aba2-42010af01555=42,kubernetes.io/e2e-438cc9b4-bb2c-11e5-9c54-42010af015
55=42,kubernetes.io/e2e-520a3eea-bab4-11e5-9501-42010af01555=42,kubernetes.io/e2e-5c556345-bb6e-11e5-b683-42010af01555=42,kubernetes.io/e2e-639aeb6e-bb3a-11e5-921e-42010af01555=42,kubernetes.io/e2e-800ee848-bae6-11e5-8ec0-42010af01555=42
,kubernetes.io/e2e-82fbb12d-ba94-11e5-afb1-42010af01555=42,kubernetes.io/e2e-88b0ac96-b9e6-11e5-8da4-42010af01555=42,kubernetes.io/e2e-a0b61516-b98f-11e5-b123-42010af01555=42,kubernetes.io/e2e-a5f05c87-ba0c-11e5-b393-42010af01555=42,kube
rnetes.io/e2e-a923f4dc-b96a-11e5-8a27-42010af01555=42,kubernetes.io/e2e-aa6cf13b-b9d3-11e5-aa4e-42010af01555=42,kubernetes.io/e2e-b48adfc1-bac4-11e5-b458-42010af01555=42,kubernetes.io/e2e-b6b4cd95-ba07-11e5-9e0a-42010af01555=42,kubernete
s.io/e2e-c26dee35-b956-11e5-ae2a-42010af01555=42,kubernetes.io/e2e-d1bd6c53-b938-11e5-a7cf-42010af01555=42,kubernetes.io/e2e-d1f4ac71-ba58-11e5-804c-42010af01555=42,kubernetes.io/e2e-d3c54e5f-b983-11e5-b531-42010af01555=42,kubernetes.io/
e2e-fca1f518-ba48-11e5-a077-42010af01555=42,kubernetes.io/e2e-fdac9223-baf4-11e5-9b46-42010af01555=42,kubernetes.io/hostname=gce-soak-weekly-minion-61lh
CreationTimestamp:      Tue, 12 Jan 2016 09:54:01 +0000
Phase:
Conditions:
  Type          Status  LastHeartbeatTime                       LastTransitionTime                      Reason                          Message
  ----          ------  -----------------                       ------------------                      ------                          -------
  OutOfDisk     False   Fri, 15 Jan 2016 21:18:36 +0000         Tue, 12 Jan 2016 11:42:48 +0000         KubeletHasSufficientDisk        kubelet has sufficient disk space available
  Ready         True    Fri, 15 Jan 2016 21:18:36 +0000         Fri, 15 Jan 2016 21:18:36 +0000         KubeletReady                    kubelet is posting ready status
Addresses:      10.240.0.4,146.148.43.208
Capacity:
 cpu:           2
 memory:        7679608Ki
 pods:          110
System Info:
 Machine ID:
 System UUID:                   F26C7B21-B8FE-E1B3-04C1-9F0D9B1317F0
 Boot ID:                       e48ca431-d06a-44e9-ac4e-368078912d2e
 Kernel Version:                3.16.0-0.bpo.4-amd64
 OS Image:                      Debian GNU/Linux 7 (wheezy)
 Container Runtime Version:     docker://1.8.3
 Kubelet Version:               v1.2.0-alpha.5.805+5b43a127750abe
 Kube-Proxy Version:            v1.2.0-alpha.5.805+5b43a127750abe
PodCIDR:                        10.245.0.0/24
ExternalID:                     6587799767446618918
Non-terminated Pods:            (4 in total)
  Namespace                     Name                                                            CPU Requests    CPU Limits      Memory Requests Memory Limits
  ---------                     ----                                                            ------------    ----------      --------------- -------------
  default                       addon-test-v1-2bnjy                                             100m (5%)       0 (0%)          0 (0%)          0 (0%)
  e2e-tests-deployment-8pneg    nginx-deployment-4haq3-2b7uq                                    0 (0%)          0 (0%)          0 (0%)          0 (0%)
  kube-system                   fluentd-elasticsearch-gce-soak-weekly-minion-61lh               100m (5%)       100m (5%)       0 (0%)          0 (0%)
  kube-system                   kube-proxy-gce-soak-weekly-minion-61lh                          0 (0%)          0 (0%)          0 (0%)          0 (0%)
Allocated resources:
  (Total limits may be over 100%, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests  CPU Limits      Memory Requests Memory Limits
  ------------  ----------      --------------- -------------
  200m (10%)    100m (5%)       0 (0%)          0 (0%)
Events:
  FirstSeen     LastSeen        Count   From                                    SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                                    -------------   --------        ------                  -------
  58m           58m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  57m           57m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  57m           57m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  57m           57m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
  52m           52m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  51m           51m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  51m           51m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  51m           51m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
  46m           46m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  46m           46m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  46m           46m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  45m           45m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
  41m           41m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  40m           40m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  40m           40m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  40m           40m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
  35m           35m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  34m           34m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  34m           34m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  34m           34m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
  29m           29m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  29m           29m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  29m           29m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  28m           28m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
  24m           24m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  23m           23m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  23m           23m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  22m           22m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
  18m           18m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  17m           17m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  17m           17m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  17m           17m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
  12m           12m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  12m           12m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  12m           12m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  11m           11m             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
  6m            6m              1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  6m            6m              1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  6m            6m              1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  5m            5m              1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
  1m            1m              1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeNotReady            Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
  41s           41s             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          Starting                Starting kubelet.
  40s           40s             1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeHasSufficientDisk   Node gce-soak-weekly-minion-61lh status is now: NodeHasSufficientDisk
  9s            9s              1       {kubelet gce-soak-weekly-minion-61lh}                   Normal          NodeReady               Node gce-soak-weekly-minion-61lh status is now: NodeReady
```

It's consistenly flapping Ready 5 minutes, NotReady ~20 seconds

**Comment by quinton-hoole** [comment]
@mikedanese Yeah, I see what you mean - that node is definitely flapping.

I thought a bit more about safe ways to quarantine nodes, and it just occurred to me that a good approach might be to use a basic priority function.  For example, keep a sliding window not ready count per node, and add a priority function to put nodes with high not ready counts at the bottom of the list when selecting nodes.  That works around the poisoned pod problem outlined above, as we wouldn't actually lose real capacity by hard quarantining nodes. Only probabalistically avoid scheduling onto more flaky nodes.  I think that's both simple and effective.  Unless @mml or @davidopp have better ideas, I think that we should add this feature to the backlog.

**Comment by mikedanese** [comment]
Also logs are kubelet logs are suuuper unhelpful here.

```
I0115 21:34:27.896815   10894 config.go:265] Setting pods for source file
E0115 21:34:27.911941   10894 kubelet.go:867] Image garbage collection failed: unable to find data for container /
I0115 21:34:29.716430   10894 server.go:1063] GET /healthz?verbose: (55.713µs) 200 [[curl/7.26.0] 127.0.0.1:55895]
I0115 21:34:31.739465   10894 server.go:1063] GET /healthz?verbose: (72.083µs) 200 [[curl/7.26.0] 127.0.0.1:55896]
I0115 21:34:32.846417   10894 kubelet.go:2671] Recording NodeNotReady event message for node gce-soak-weekly-minion-61
lh
I0115 21:34:32.846606   10894 server.go:563] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"gce-soak-weekl
y-minion-61lh", UID:"gce-soak-weekly-minion-61lh", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' r
eason: 'NodeNotReady' Node gce-soak-weekly-minion-61lh status is now: NodeNotReady
I0115 21:34:33.760543   10894 server.go:1063] GET /healthz?verbose: (56.983µs) 200 [[curl/7.26.0] 127.0.0.1:55897]
I0115 21:34:35.781438   10894 server.go:1063] GET /healthz?verbose: (40.747µs) 200 [[curl/7.26.0] 127.0.0.1:55898]
I0115 21:34:37.583958   10894 server.go:1063] GET /healthz: (59.644µs) 200 [[curl/7.26.0] 127.0.0.1:55899]
```

We should print the caller when we emit an event in kubelet

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2611

**Comment by mikedanese** [comment]
@quinton-hoole ya we should definitely track handling node flapping in an issue.

**Comment by mml** [comment]
In order to make debugging easier, tests like these could have a basic invariant assertion like "during the test, all the nodes stay in Ready state the whole time".  If that fails, our failure reason is more clear.

As times goes on, we might think of other invariants like this to assert during complicated system tests, but for starters this one would probably prove useful.

**Comment by quinton-hoole** [comment]
@mml +100  Sounds like very useful approach.  The error message could be clear about the fact that the test is not at fault, the system is.

**Comment by dchen1107** [comment]
I took a look with both gke / gce soak test today, and here are current status: 

1) all tests requiring network connectivity failed now. Looking into it with @ArtfulCoder, and found we cannot talk to our own dns server. dns server pods are running successfully at ready state. Nodes are also at ready state. 
2) most runs are timeout
3) the only test related to kubelet is resource_tracking one. I will file a separate issue to track that.

**Comment by dchen1107** [comment]
cc/ @thockin

**Comment by thockin** [comment]
Do we have machines in this state - pods that can't talk on network?

**Comment by alex-mohr** [comment]
Unclear if this issue is the same underlying reason as #19875

**Comment by ArtfulCoder** [comment]
This issue was caused because of two reasons:

1. The firewall rules are incomplete.
Pods on different minions cant ping each other because we dont have the right firewall rules open.

![incompletefirewallrules](https://cloud.githubusercontent.com/assets/1220660/12462521/a1be8a28-bf73-11e5-92e8-b4b7b60b3636.png)

2. One of the minions has hit a kernel bug  
dmesg shows: "unregister_netdevice: waiting for veth36aa547 to become free"
https://github.com/docker/docker/issues/5618#issuecomment-164792088
We run on kernel 3.16x which does hit the issue.
 

We can't control the second reason, but we should totally fix reason 1..

**Comment by ArtfulCoder** [comment]
@roberthbailey Assigning to Robert to triage and decide who could work on the gke firewall setup issue..

**Comment by thockin** [comment]
If this is broken, how did it ever work?  If it changed recently, what
changed?

**Comment by ArtfulCoder** [comment]
is it possible to get the audit log for the pantheon project to see history of firewall rule changes..

**Comment by quinton-hoole** [comment]
@ArtfulCoder @thockin @roberthbailey The soak test cluster auto-rebuilds once a week:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-weekly-deploy-gke/

The tests passed up until 01/11, the cluster rebuilt on 01/12, and the tests have failed ever since.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gke/

So the bug you're looking for almost definitely merged between 01/05 and 01/12.

**Comment by cjcullen** [comment]
The firewalls that are missing are the ones created by the test script (not the ones that GKE creates).

I'll take a look into the soak test scripts to see why it's broken there but nowhere else.

**Comment by ArtfulCoder** [comment]
The firewalls that are missing (or atleast to that effect) should be created by GKE otherwise pods across nodes cannot even ping each other..

**Comment by ArtfulCoder** [comment]
pingable containers across nodes is more than just a test requirement.

**Comment by cjcullen** [comment]
:smiley:  I agree.

I'm just looking at the picture you posted. The active cluster (50bc5ce7) has all of the correct firewalls (other than the test ones).

The routes look very suspect, though. If we trust the 50bc5ce7-all firewall, the cluster's range is 10.80.0.0/14. The fact that we have routes for 10.231.239.0/24, 10.84.31.0/24, 10.117.15.0/24 all pointing to 50bc5ce7 nodes seems very wrong. And that would cause un-pingable pods.

**Comment by cjcullen** [comment]
Confirmed that the nodes had been allocated very wrong Pod CIDRs, and everything downstream is WAI... Now looking into WTH is going on in Pod CIDR allocation.

**Comment by cjcullen** [comment]
And the test firewalls are fine. I just missed them from Abhi's screenshot.

**Comment by cjcullen** [comment]
Looking into PR #17754 which appears suspect.

**Comment by cjcullen** [comment]
The math introduced in #17754 was wrong. Appears to have been fixed by #19580

**Comment by cjcullen** [comment]
This could have been causing flakes all over any gke-ci test.

**Comment by gmarek** [comment]
Sorry - if I new it's causing test flakes, I'd have merged it long time ago:/
