### ISSUE TITLE
add cleanup policy for deployemt

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#19111]
@kargakis @nikhiljindal @ironcladlou @davidopp 

Current, deployment has no cleanup policy, old rc will always be preserved, I propose to add a `CleanupPolicy` field to `DeploymentSpec` indicating delete/preserve/remove the old rc. Just like `kubectl rollingupdate` does.

```go
type DeploymentSpec struct {
	/*
	...
	*/
	CleanupPolicy DeploymentCleanupPolicy
}

type DeploymentCleanupPolicy string

const(
// DeleteDeploymentCleanupPolicy means delete the old controller.
	DeleteDeploymentCleanupPolicy DeploymentCleanupPolicy = "Delete"
// PreserveDeploymentCleanupPolicy means keep the old controller.
// if user not set DeploymentCleanupPolicy, this will be the default
	PreserveDeploymentCleanupPolicy DeploymentCleanupPolicy = "Preserve"
// RenameDeploymentCleanupPolicy means delete the old controller, and rename
// the new controller to the name of the old controller.
	RenameDeploymentCleanupPolicy DeploymentCleanupPolicy = "Rename"
)
````

I will send a PR to address this if it looks good.

**Comment by bgrant0607** [comment]
Rename doesn't make sense in this context.

Also, I think we'll want to support keeping N old RCs around.

Probably the policies that make sense could be reduced to a single knob, which is the number of old RCs to retain, with some way to express that all should be retained (-1?). 

If the number retained were 0, that would interfere with the ability to undo the last deployment change, so we might want to disallow 0.

cc @ironcladlou @nikhiljindal @janetkuo

**Comment by bgrant0607** [comment]
cc @dpratt

**Comment by dpratt** [comment]
I'd argue for making the default 1, with 0 being the sentinel 'retain-all' value.

**Comment by mqliang** [comment]
> If the number retained were 0, that would interfere with the ability to undo the last deployment change, so we might want to disallow 0.

Why we ***disallow*** 0 ? I think we should ***discourage*** 0. Just like what we in pod creation: 

> user could use rc to create a pod even if the replica number is 1, we ***recommend*** that user use a replication controller even if your application requires only a single pod. 

But if user insist to create pod directly, let it go. For deployment, we can handle analogously: default 1 and ***discourage*** 0, if we want ***disallow*** 0, how about adding an optional admission controller?

**Comment by ironcladlou** [comment]
@mqliang 
>>If the number retained were 0, that would interfere with the ability to undo the last deployment change, so we might want to disallow 0.

>Why we disallow 0 ? I think we should discourage 0. Just like what we do in pod creation:

>>user could use rc to create a pod even if the replica number is 1, we recommend that user use a replication controller even if your application requires only a single pod.

>But if user insist to create pod directly, let it go. For deployment, we can handle analogously: default 1 and discourage 0, if we want disallow 0, how about adding an optional admission controller?

This seems reasonable to me. With this model, @bgrant0607's suggestion of `-1` for the "retail all" makes sense.

**Comment by bgrant0607** [comment]
Given that we have to handle the possibility of there being no previous RC in `kubectl rollout undo` anyway, I don't have a strong objection to allowing 0. It means that if a rollout completes, the user won't be able to roll it back. C'est la vie

**Comment by mqliang** [comment]
@bgrant0607 Ok, allow 0 seems dangerous.
```
type DeploymentSpec struct {
    /*
    ...
    */
    OldRCPreserveNum int32    //  default 1, with 0 being the sentinel 'retain-all' value.
}
```

If a user want delete all the old rcs(he make sure that he don't want roll it back) after deployment, he must delete it manually(`kubectl delete rc`).

**Comment by mqliang** [comment]
@bgrant0607 @ironcladlou @dpratt 
```
type DeploymentSpec struct {
    /*
    ...
    */
    OldRCPreserveNum int32    //  default 1, with 0 being the sentinel 'retain-all' value.
}
```

Does this looks good? I will send a PR to address this once we reach a consensus.

**Comment by kargakis** [comment]
If a user doesn't want to keep any old rc around, I think we should allow it. How about the field being a pointer with nil preserving the current behavior?

**Comment by bgrant0607** [comment]
@kargakis SGTM. Enforcing a non-zero value doesn't permit any simplification, since there would still be a number of situations where there would be no prior RC.

In terms of names, I try to avoid abbreviations. I'd prefer something like RevisionHistoryLimit. Take a look at #18404 for how this information will be used in kubectl (e.g., kubectl rollout history).

**Comment by bgrant0607** [comment]
cc @janetkuo
