### ISSUE TITLE
Create generic/docker-registry secret with --output=wide,  error shows but secret is created

### ISSUE THREAD

**Issue by qwang1** [kubernetes/kubernetes#19129]
### Description
Create generic/docker-registry secret with --output=wide,  it shows "err accessing flag no-headers for command generic: flag accessed but not defined: no-headers" , but secret is created.

### Version
[root@ip-172-18-1-5 amd64]# ./kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.5.485+500493a3acf960", GitCommit:"500493a3acf9607f67b74cefe541a324a71108cf", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.5.485+500493a3acf960", GitCommit:"500493a3acf9607f67b74cefe541a324a71108cf", GitTreeState:"clean"}

### Step
    [root@ip-172-18-1-5 amd64]# ./kubectl create secret generic secret72 --from-literal=key1=b --from-file=./file4 --output=wide
    F1228 08:51:37.102808   12305 helpers.go:267] err accessing flag no-headers for command   generic: flag accessed but not defined: no-headers

    [root@ip-172-18-1-5 amd64]# ./kubectl describe secret secret72
    Name:		secret72
    Namespace:	default
    Labels:		<none>
    Annotations:	<none>

    Type:	Opaque

    Data
    ====
    file4:	5 bytes
    key1:	1 bytes

**Comment by ncdc** [comment]
cc @derekwaynecarr @kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
I will investigate further.  Thanks for the report.

**Comment by derekwaynecarr** [comment]
Looks like we need to use `AddPrinterFlags` since the internal printer assumes a common set of flags when building a printer.  Will update code and send a PR.
