### ISSUE TITLE
Kubernetes HA don't support to transfer the container with  cinder volume plugin to another normal minion node.

### ISSUE THREAD

**Issue by wangqunOne** [kubernetes/kubernetes#19132]
we have setup one kubernetes cluster to test the HA if support to transfer the container with the cinder volume plugin. I have three nodes. One Master Node, and two Nodes are minion nodes. I install with cinder volume plugin successfully. 
1.I use the case to create the pod on A minion node. It can run well. And the cinder can also be attached to the container.
apiVersion: v1
kind: ReplicationController
metadata:
  name: wqonlynginx
spec:
  replicas: 1
  selector:
    name: wqonlynginx
  template:
    metadata:
      labels:
        name: wqonlynginx
    spec:
      containers:
      - name: wqonlynginx
        image: nginx
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /nginx-data
          name: data
      volumes:
        - name: data
          cinder:
            # Enter the volume ID below
            volumeID: 37ef6468-dfde-4468-8317-2c4142a6827f
            fsType: ext4
2. I stop the A minion by the command "nova stop instance_id", But I find the status of pod is ContainerCreating all the time. I find the cinder volume isn't attached to the B minion node if HA supports, and the B minion node don't find the container to be transfered. 
          
From our test, it seems kubernetes HA Not support this container with cinder volume plugin to transfer to the another minion node.
Could any kubernetes developers confirmed that ?

**Comment by wangqunOne** [comment]
@spothanis

**Comment by spothanis** [comment]
@wangqunOne I think this is probably an area which common to all cloud backed volumes. I know that there was some talk about having a separate volume controller at some point. 

@saad-ali do we have any solutions for such scenarios with GCE?

**Comment by saad-ali** [comment]
Yes this is a known issue. See https://github.com/kubernetes/kubernetes/issues/14642. We're working on a redesign that should fix this. Summary of the issue: currently kubelet is responsible for determining when to attach/detach a volume from the node. When a node goes down, kubelet goes down, and this can lead to a volume getting stranded on the node.

Closing this issue as duplicate.

**Comment by HackToday** [comment]
@saad-ali  glad to know someone is working on the important issue. Will keep tack of it
