### ISSUE TITLE
unit test flake: pkg/master is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#19141]
This has just happened:

--- FAIL: TestGetServersToValidate (0.20s)
	<autogenerated>:31: 
                        
	Error Trace:	master_test.go:131
		
	Error:		Not equal: 3 (expected)
			        != 4 (actual)
		
	Messages:	unexpected server list: map[string]apiserver.Server{"controller-manager":apiserver.Server{Addr:"127.0.0.1", Port:10252, Path:"/healthz", EnableHTTPS:false, Validate:(apiserver.ValidatorFn)(nil)}, "scheduler":apiserver.Server{Addr:"127.0.0.1", Port:10251, Path:"/healthz", EnableHTTPS:false, Validate:(apiserver.ValidatorFn)(nil)}, "etcd-0":apiserver.Server{Addr:"", Port:4001, Path:"/health", EnableHTTPS:false, Validate:(apiserver.ValidatorFn)(0xb915a0)}, "etcd-1":apiserver.Server{Addr:"127.0.0.1", Port:49244, Path:"/health", EnableHTTPS:false, Validate:(apiserver.ValidatorFn)(0xb915a0)}}

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/bd58b05f3eaea3d3b21df7d80f8b0a0c6c2ec87e/kubernetes-pull-test-unit-integration/7420/artifacts/?debugUI=DEVELOPERS

**Comment by wojtek-t** [comment]
@gmarek

**Comment by gmarek** [comment]
cc @kubernetes/goog-control-plane @kubernetes/goog-csi

**Comment by smarterclayton** [comment]
Seeing this ~5% of my runs today

**Comment by wojtek-t** [comment]
Yes - it's pretty flaky.

Looking into failures it seems that in the expected situation we have:
- single etcd server on port 4001

But when the test is failing we have:
- etcd server on port 4001 (expected): 

        Server{Addr:"", Port:4001, Path:"/health", EnableHTTPS:false, Validate:(apiserver.ValidatorFn)(0xb9d330)}
- another etcd server on a random port

        Server{Addr:"127.0.0.1", Port:36995, Path:"/health", EnableHTTPS:false, Validate:(apiserver.ValidatorFn)(0xb9d330)}}

**Comment by wojtek-t** [comment]
I think I understand what is happening here. Will send a PR fixing this soon.
