### ISSUE TITLE
GCE L7 LoadBalancer Controller test failing in gke-flaky suite.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#19155]
`GCE L7 LoadBalancer Controller [Serial] [Slow] [Flaky] should create GCE L7 loadbalancers and verify Ingress`

It probably shouldn't be running in the gke-flaky suite. Looks like #19021 might've added it, and it's failed every run since then.

**Comment by bprashanth** [comment]
From logs:
```
18:03:45 E1229 02:02:53.428589       1 gce.go:294] GCE operation failed: googleapi: Error 403: Quota 'BACKEND_SERVICES' exceeded.  Limit: 3.0
18:03:45 E1229 02:02:53.428715       1 utils.go:74] Requeuing e2e-tests-glbc-gxdv6/app0, err googleapi: Error 403: Quota 'BACKEND_SERVICES' exceeded.  Limit: 3.0
18:03:45 I1229 02:02:53.428767       1 utils.go:86] Syncing e2e-tests-glbc-gxdv6/app0
```

These are the quota requirements for the test: 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/ingress.go#L41

This is the request I put in last time:
```
==Global Quota Requests==
Number of Forwarding Rules: 30
Number of Target HTTPS Proxies: 20
Number of URL Maps: 20
Number of Global External In-Use IP Addresses: 35
```

I don't seem to have access to the gke-ci-flaky project. 

Also somewhat tangentially the test is already running in gke-1.1 and I don't think it should be added to any CI suite.

**Comment by bprashanth** [comment]
I tracked down the issue:
1. We're right at the border of backend quota. The test currently uses 3. If there's even a single backend leaked, every test thereafter will fail because of quota.
2. Sometimes a run hangs on a request. This seems like a GCE bug since a GET should never hang. I'll need to dig and try a repro.
3. When it hangs the build times out and kills the cluster, leaking resources.

The logs should have:
```
15:39:57 Dec 29 15:39:57.075: INFO: Waiting for Ingress app0 to acquire IP, error <nil>
15:40:07 STEP: Found address 107.178.242.69 for ingress app0, took 1m0.005851808s to come online
15:40:07 Dec 29 15:40:07.076: INFO: Testing route http://107.178.242.69/foo0 host foo0.bar.com with simple GET
20:24:00 
Build timed out (after 300 minutes). Marking the build as aborted.
```

With the current quota the only option is to go in and cleanup l7s. Can somone who has access to gke-flaky bump up the quota? The test should also timeout GETs and retry. 

It's hard to avoid a resource leak from a mid-run cluster nuke unless we're sure that no other tests created those resources in parallel (and arguably this is not something that will happen in the wild).

**Comment by spxtr** [comment]
It looks like there's no Timeout set for the default http client used [here](https://github.com/kubernetes/kubernetes/blob/eeb727afd39ed04b9ac794edfa5561d65a67a905/test/e2e/ingress.go#L524).

**Comment by bprashanth** [comment]
@spxtr I'm ooo till the 7th and it seems like my desktop has gone offline. If this needs a fix please ASAP replace the default http client with something like:
```go
var timeoutClient = http.Client{
    Timeout: 60*time.Second,
}
```
I'll investigate the suspicious hangs when I get back.

**Comment by bprashanth** [comment]
nevermind, I was able to do it through a backup vm. Please review https://github.com/kubernetes/kubernetes/pull/19224

**Comment by spxtr** [comment]
Looks like it's fixed on GKE but now failing on GCE with

```
Ingress failed to acquire an IP address within 15m0s
````

**Comment by bprashanth** [comment]
I think the test gets killed sometimes, and it doesn't take too many killing to fill up 10 backend services (takes 2). I'll deflaky when I'm back in the office, for now I've cleaned up so it should pass.

**Comment by bprashanth** [comment]
This is passing now and I've been watching the cluster for leaked resources with no luck (http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-flaky/lastCompletedBuild/testReport/(root)/Kubernetes%20e2e%20suite/GCE_L7_LoadBalancer_Controller__Serial___Slow___Flaky__should_create_GCE_L7_loadbalancers_and_verify_Ingress/history/). 

That's the problem with these tests that create external resources, 2 tests in a 1000 are aborted for some reason (will happen in ~a month) and every single one of them fails thereafter. Maybe we can start cleaning up leaks across all tests based on ttl? tag with Jenkins build id? Obviously I need to figure out why those 2 runs aborted (I suspect the same GET hang discussed previously), I think these are orthogonal problems.

**Comment by ihmccreery** [comment]
Yup, we have plans to do that in #18119, hopefully this quarter.

**Comment by spxtr** [comment]
@bprashanth Looks like this job is passing most of the time. Should this issue stay open?
