### ISSUE TITLE
mungedoc should warn people to fetch upstream/release-1.1 if it already exists

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#19154]
In #18047, mungedoc checks if a doc exists in upstream/release-1.1. If upstream/release-1.1 in the local machine is out-dated, mungedoc will work improperly. We need to at least add a message to warn people to fetch the latest upstream/release-1.1.

cc @nikhiljindal @mattjmcnaughton

**Comment by jimmidyson** [comment]
This kind of assumes that people name their remote `upstream` (hard-coded at https://github.com/kubernetes/kubernetes/blob/master/cmd/mungedocs/mungedocs.go#L210). I, for one, don't so this breaks local checks for me.

**Comment by caesarxuchao** [comment]
@jimmidyson, if there is no `upstream/release1.1` on your local, the local check will print a message is printed to stdout, and the test doesn't fail. 
The munger will only misbehave if you have `upstream/release-1.1` on your local and that branch is not synced with https://github.com/kubernetes/kubernetes/tree/release-1.1. Is this your case?

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc
