### ISSUE TITLE
kube client should support multiple api server endpoints.

### ISSUE THREAD

**Issue by adohe** [kubernetes/kubernetes#19161]
FYI. just reference to #19152, #18174, maybe a round robin or random pick should be used with multiple endpoints.

**Comment by fgrzadkowski** [comment]
@kubernetes/goog-csi

**Comment by lavalamp** [comment]
I think we should solve this by having kube-proxy be aware of multiple apiservers, and have kubelet (and all in-cluster clients) use the service IP. That way only one component has to be aware. (The downside is that kubelet would have a dependency on kube-proxy, but I think that's already the case.)

out-of-cluster clients should be using a load balancer address anyway, so they shouldn't have to do anything at all. Basically, I think if we put a special case in kube-proxy, we fix this for everything.

I think this is P1 if HA is P1.

**Comment by AdoHe** [comment]
@lavalamp this should be a good enough solution at this moment. Especially when we implement this on kube client which is a little bit difficult. But I am worry about the kube-proxy, actually I noticed that many users have thoughts to remove this component or replace it.

**Comment by lavalamp** [comment]
@AdoHe As long as replacements to kube-proxy still let service IPs work (its main function!) my suggestion should continue to work.

**Comment by lavalamp** [comment]
Actually, now that I think about it, clients should already be using the service address. So I think there's nothing that needs to be done here.

**Comment by dalanlan** [comment]
> Actually, now that I think about it, clients should already be using the service address.

@lavalamp  Not for kubelet IIUC.
```
fs.StringSliceVar(&s.APIServerList, "api-servers", []string{}, "List of Kubernetes API servers for publishing events, and reading pods and services. (ip:port), comma separated.")
```

**Comment by AdoHe** [comment]
@dalanlan I think so, the source code just pick the first one as the apiserver address.

**Comment by dalanlan** [comment]
@AdoHe Exactly. Yet it's definitely not a service ip,right?

**Comment by AdoHe** [comment]
@dalanlan Definitely not, it's just the first apisever addresses you configured when you start kubelet.

**Comment by lavalamp** [comment]
But nothing is stopping you from putting the service IP in there, right? It should work that way. I guess I'll reopen this if we haven't actually tested that configuration.

**Comment by AdoHe** [comment]
@lavalamp I can see what you mean, but for many users I guess they will not put a service IP here, we should test put a service IP here at first and then document it.

**Comment by dalanlan** [comment]
@lavalamp Just confirm it functions well. I would love to help with the doc. 
OTOH i was wondering whether it would be less confusing to use `string` instead of `string slice` here for `--api-server` flag consumed by kubelet, since we are not gonna support internal round robin anyway.

**Comment by ramonrue** [comment]
Hi everyone,
I want to create a kubernetes cluster with multiple apiservers.
I use CoreOS Alpha on baremetal servers. In which files do I have to change the apiservers to the service IP?

**Comment by lavalamp** [comment]
Let's have this discussion here: #18174
