### ISSUE TITLE
kubectl create secret --output-version doesn't validate the value

### ISSUE THREAD

**Issue by qwang1** [kubernetes/kubernetes#19163]
### Description

Flag: --output-version=" " of "kubectl create secret" doesn't validate the input parameter.
### Version

[root@ip-172-18-1-5 amd64]# ./kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.5.485+500493a3acf960", GitCommit:"500493a3acf9607f67b74cefe541a324a71108cf", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.5.485+500493a3acf960", GitCommit:"500493a3acf9607f67b74cefe541a324a71108cf", GitTreeState:"clean"}
### Step

```
[root@ip-172-18-1-5 amd64]# ./kubectl create secret generic secret800 --from-literal=key1=b --output-version=
secret "secret800" created

[root@ip-172-18-1-5 amd64]# ./kubectl create secret generic secret801 --from-literal=key1=b --output-version=v1
secret "secret801" created

[root@ip-172-18-1-5 amd64]# ./kubectl create secret generic secret802 --from-literal=key1=b --output-version=v2
secret "secret802" created

[root@ip-172-18-1-5 amd64]# ./kubectl create secret docker-registry secret803 --docker-server=https://hub.docker.com  --docker-username=xxx --docker-password=xxx --docker-email=xxx@xxx.com --output-version=@
secret "secret803" created

[root@ip-172-18-1-5 amd64]# ./kubectl get secret
NAME                  TYPE                                  DATA      AGE
default-token-khzu2   kubernetes.io/service-account-token   2         1h
secret800             Opaque                                1         5m
secret801             Opaque                                1         5m
secret802             Opaque                                1         5m
secret803             kubernetes.io/dockercfg               1         10s
```

**Comment by smarterclayton** [comment]
This is due to how we create objects during conversion - we return NotRegisteredError when the provided kind, group, or version is not recognized.  The printer loop then silently ignores those.  We need to make a more specific not registered error for this case and tie it to how the resource printer invokes ConvertToVersion.  There should probably be a specific error if the version the user provides doesn't match any version we attempt to look at.

**Comment by derekwaynecarr** [comment]
Thanks for the tip @smarterclayton , will look to investigate.

**Comment by zefciu** [comment]
Will look at it.

**Comment by zefciu** [comment]
While looking I see, that this flag is simply non-functional. For example in kubectl convert it should control the output, but I get v1 whatever I put there (valid or invalid versions).

**Comment by zefciu** [comment]
@deads2k: In ``pkg/kubects/cmd/get_test.go`` you put the following:

> 3b. otherwise if the specified output-version is unrecognized, but the requested object (replicationcontroller) is recognized by the client's codec, then it will be converted to the client version, testapi.Default.GroupVersion().String() in this test.

So from your comment it seems that the behaviour reported here (no validation, but simple fallback to default version) is somehow desired. Could you explain?

**Comment by deads2k** [comment]
> So from your comment it seems that the behaviour reported here (no validation, but simple fallback to default version) is somehow desired. Could you explain?

It's an inherited comment that I updated, but didn't create. @caesarxuchao I believe.

**Comment by caesarxuchao** [comment]
Yeah, I left those comments. I was trying to describe the test logic, as I found it difficult to understand at that time.

That's not the desired behavior, I think Clayton's comment is right.

> While looking I see, that this flag is simply non-functional. For example in kubectl convert it should control the output, but I get v1 whatever I put there (valid or invalid versions).

What object are you trying on? We tried on convert batch/v1/job to extensions/v1beta1/job and it works. Though it doesn't report an error if the --output-version isn't valid.

**Comment by zefciu** [comment]
OK, now I get it. I was testing it on secrets, which apparently have only one version of API registered. So the two questions are:

1. What should be the behaviour when --output-version is set to a completely nonexistent version
2. What should be the behaviour when it is set to an existing version, but one that is unavailable for a given object type

Could someone decide and either close this ticket or give a blessing for implementation?

**Comment by zefciu** [comment]
@caesarxuchao @derekwaynecarr could you please answer my questions?

**Comment by derekwaynecarr** [comment]
@kubernetes/kubectl - can you please weigh in here:

https://github.com/kubernetes/kubernetes/issues/19163#issuecomment-220906195

**Comment by caesarxuchao** [comment]
> What should be the behaviour when --output-version is set to a completely nonexistent version

I think kubectl should return an error in this case

> What should be the behaviour when it is set to an existing version, but one that is unavailable for a given object type

IMO it should also return an error in this case.

cc @janetkuo @bgrant0607

**Comment by zefciu** [comment]
Still looking at the code it seems that fallback in any case is a very deliberate behaviour. The `ConvertToVersion` will always try the default version last and fail only if the object is not convertible to this version. So I would need a strong confirmation that this behaviour doesn't have any purpose and that removing this fallback wouldn't break anything.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-bugs

**Comment by shiywang** [comment]
@zefciu are you working on this, if not I will take a look

**Comment by liggitt** [comment]
--output-version has been deprecated

/close
