### ISSUE TITLE
Automatically announce new releases as part of the new release tooling

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19174]
We should have instructions for announcing new releases via email (kubernetes-announce, kubernetes-dev, and google-containers@).

cc @roberthbailey

**Comment by david-mcmahon** [comment]
This should be scripted and generated automatically as part of the release.

**Comment by david-mcmahon** [comment]
New release tooling will have this generated as part of the automated workflow.

**Comment by david-mcmahon** [comment]
https://github.com/kubernetes/release/issues/1
