### ISSUE TITLE
Upgrade the kube bot to identify flakes and open issues automatically

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#19178]
Most of the triage of flakes looks like:

1. Have a PR, observe various failures in tests
2. Open an issue (or link to an existing issue), extract relevant snippets, back reference it to the current issue, give it the right labels, 
3. Rerun the tests

It would be nice to automate / unify this process with a command to the k8s-bot... instead of saying:

    k8s-bot unit test this

say

    k8s-bot unit test flake

    > copy and pasted excerpt of the failing test

and the bot would spawn the issue, link to the previous PR log run and the current issue, add the snippet to the issue description, and kick off a new test because of the flake.

Some other things we could do are track flakes more formally (maybe have the submit-queue display the list of known flakes?) and track metrics on specific ones reported.  And have a searchable list of builds that are displayed as flakes?

Ultimately, we need to make flakes the responsibility of everyone to squash dead as soon as they're found, and we should have tools to find and identify the flakes as much as possible.

**Comment by smarterclayton** [comment]
@kubernetes/goog-testing

**Comment by smarterclayton** [comment]
Another thing - we should be rerunning tests on master repeatedly (3 times each merge?) and if any of them fail, stop the merge queue.

**Comment by ihmccreery** [comment]
My work in #19021 makes flake tracking rely on `[Flaky]` label in the test description rather than regexps in `e2e.sh`.

**Comment by quinton-hoole** [comment]
@ihmccreery How do you deal with the case where a given test is flaky in one environment and not others.  Stated another way, flakyness is a function of (test, environment) as per the existing regex scheme, not just (test).

**Comment by ihmccreery** [comment]
@quinton-hoole I answered that question in #19021, since it's not really related to this issue.

**Comment by dims** [comment]
@lavalamp @smarterclayton - We have this in place now right :)

**Comment by lavalamp** [comment]
I think this is obsolete now.
