### ISSUE TITLE
Starting a container with host networking enabled

### ISSUE THREAD

**Issue by yossi-cohen** [kubernetes/kubernetes#19171]
I run a pod (actually many of them) which read a video stream from an external MULTICAST address
multicast can reach only pods deployed on the same host as the multicast sender (pods running on other hosts do not get multicast packets)
I've managed to get multicast to remote hosts using 'docker run --net=host ...' 
Now I need to get the same result under kubernetes:
So as I understand, I have to run my pods with 'hostNetwork: true'
but the pods do not get into ready state and doing 'kubectl get events' says:
'Error syncing pod, skipping: pod with UID ... specified host networking, but is disallowed'

Am I missing something?

**Comment by thockin** [comment]
What environment (cloud, os, kube version) ?

**Comment by AdoHe** [comment]
@yossi-cohen yes, you can use host network mode if you specified in the pod spec. Besides what's your kube version?

**Comment by AdoHe** [comment]
@yossi-cohen by default, kubernetes will allow pod from all sources(`File`,`HTTP`,`apiserver`) to use host network, from the event you past, I guess the pod source is mismatched, what's your kube version, and how you create the pod?

**Comment by yossi-cohen** [comment]
Thanks for the quick response.
I've finally managed to overcome the problem by modifying ~/kubernetes/cluster/ubuntu/util.sh:
I'v added **'--allow_privileged=true'** to KUBE_APISERVER_OPTS
and **'--allow_privileged=true --host-network-sources=*'** to KUBELET_OPTS

*my 'worker-rc.yml' (including the __hostNetwork: true__) looks like this:*

    apiVersion: v1
    kind: ReplicationController
    metadata:
     name: worker
     namespace: default
    spec:
     replicas: 4
     selector:
       name: worker
     template:
       metadata:
         labels:
           name: worker
       spec:
        hostNetwork: true
        containers:
           - image: 10.0.0.1:5000/worker
             name: worker
             imagePullPolicy: IfNotPresent

Is there a way to pass multicast packets from the "real" network into the cluster **without 
using hostNetwotk** (e.g., through the docker0 bridge)?

**Comment by AdoHe** [comment]
@yossi-cohen actually you just need to add `allow_privileged`, by default `host-network-sources` is `*`. Actually I don't get the point why you have to use `host` network mode. the multicast packets are special so they have to be handled within the default network namespace?

**Comment by fgrzadkowski** [comment]
@kubernetes/goog-cluster

**Comment by yossi-cohen** [comment]
My problem is that the **multicast sender** is **not part of the cluster.**
If I'm running my pods inside the default network I don't get the multicast packets.
*(not cleared to me why)*
Is there a way to get the multicast packets while running my pods in the default network?

**Comment by AdoHe** [comment]
@yossi-cohen AFAIK, you just want to make the multicast sender(which is not part of the kube cluster) can communicate with multicast receivers which are kubernets pods. I think you have no need to run your pods in host network(if the multicast has to, I am afraid you have to), you can run in the default network but you have to make sure the iptables rules are ok.

**Comment by thockin** [comment]
I've never tried to use multicast across docker, but some quick googling
says it should work.

**Comment by prasenforu** [comment]
@ yossi-cohen,  
I was looking for this type solution (hostNetwork: true) but this I am not scale UP more than 1 container in each host.

**Comment by thockin** [comment]
If you use the host network, then you can't have multiple instances on a
node with statically assigned ports, obviously.  They will collide.  Is
that what you're describing?

**Comment by prasenforu** [comment]
Thank you Tim for reply.

But what is the alternative solutions to achieve this.

I want to do mapping /etc/hosts of host to pod host file as well as want to do scale up & scale down.

Environment I am using 
One Master & 2 node (minions) setup

**Comment by thockin** [comment]
What you're asking is essentially "I want multiple programs on a machine to
use the same port".  It just doesn't work (not the way you want).

Why do they need to be in the host network?

**Comment by prasenforu** [comment]
I have some important entry in /etc/hosts file same I need in pod host file.

Instead of using  host network can you suggest any alternative solution.

**Comment by thockin** [comment]
You could add a Service with no selector, and a corresponding Endpoints
that pointed to the IP.  That would get a real DNS name.

Or we could discuss the ability to inject extra /etc/hosts entries into
containers (would not ship until 1.4 earliest)

**Comment by prasenforu** [comment]
OK thanks.

**Comment by jobz** [comment]
Hi ,
I need to run my container with "docker run --net=none" command , what will be the corresponding yml file variable , like   hostNetwork: true used for "docker run --net=host"

**Comment by thockin** [comment]
Kubernetes does not have a non-network mode currently.  Can you explain
your use case?

**Comment by jerroydmoore** [comment]
I have a use case. I want to capture network IO for logging and auditing, using Metricbeat or Packetbeat.

https://www.elastic.co/guide/en/beats/metricbeat/current/running-in-container.html
https://agonzalezro.github.io/log-your-docker-containers-from-a-container-with-packetbeat.html

**Comment by jackielii** [comment]
I tried weave-net successfully to have UDP multicast

**Comment by jswierad** [comment]
> I tried weave-net successfully to have UDP multicast

How did you use weave-net to manage multicasts from outside the cluster?

**Comment by maaraneasi** [comment]
>How did you use weave-net to manage multicasts from outside the cluster?

I'd like to know as well as I am struggling with the same...
