### ISSUE TITLE
Images from a private repository on GKE are not visible to pods within the same project

### ISSUE THREAD

**Issue by dinvlad** [kubernetes/kubernetes#19181]
Hi guys, I'm trying to pull an image to a container cluster on GKE from private repository hosted on GKE under the same project, but getting errors that the image is not found. More specifically, I've created a cluster using Deployment Manager and verified that it works:
```
gcloud container clusters describe dev-cluster | grep '<project_id>\|endpoint\|zone'
endpoint: 104.196.xx.xxx
- https://www.googleapis.com/replicapool/v1beta2/projects/<project_id>/zones/us-east1-b/instanceGroupManagers/gke-dev-cluster-08e6bd03-group
selfLink: https://container.googleapis.com/v1/projects/<project_id>/zones/us-east1-b/clusters/dev-cluster
zone: us-east1-b
```
I also made sure that the correct cluster credentials are received:
```
gcloud config set container/cluster dev-cluster
gcloud container clusters get-credentials dev-cluster
kubectl cluster-info
Kubernetes master is running at https://104.196.xx.xxx
...
```
The IP addresses above are the same. After that, I build a docker image locally using the name us.gcr.io/\<project_id\>/\<image_name\> and push it to GKE under the same project using
```
gcloud docker push us.gcr.io/<project_id>/<image_name>
```
then verify it on a different system by authenticating on gcloud using the same <project_id> and pulling, which completes successfully and displays the same digest id.
However, when I try to create a pod within the cluster using
```
kubectl create -f pod.yaml
cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: <pod_name>
spec:
  restartPolicy: Never
  containers:
  - name: <container_name>
    image: us.gcr.io/<project_id>/<image_name>
```
it doesn't create the pod, displaying
```
Failed to pull image "us.gcr.io/<project_id>/<image_name>": image pull failed for us.gcr.io/<project_id>/<image_name>, this may be because there are no credentials on this request.  details: (Error: image <project_id>/<image_name>:latest not found)
```
The same error is displayed when I ssh to these nodes and try to ```sudo docker pull```.
What gives? Perhaps there's something I'm missing, but the documents specify that the credentials should be automatically configured for the nodes in a project on GCE/GKE: https://cloud.google.com/container-engine/docs/clusters/operations#passing_cluster_credentials_to_kubectl

Thanks a lot

**Comment by dinvlad** [comment]
Fwiw, the symptoms sound awfully similar to #17086

**Comment by fgrzadkowski** [comment]
Can you please check permissions of your GCE VM? There should be section called "Permissions" and "Storage".

**Comment by fgrzadkowski** [comment]
@kubernetes/goog-gke

**Comment by dinvlad** [comment]
Good catch! I had to enable 'https://www.googleapis.com/auth/devstorage.read_only' under oauthScopes[] in my deployment template and now it works well:
https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters#NodeConfig

**Comment by roberthbailey** [comment]
The important section from https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters#NodeConfig is:

The following scopes are recommended, but not required, and by default are not included:

 - https://www.googleapis.com/auth/compute is required for mounting persistent storage on your nodes.
 - https://www.googleapis.com/auth/devstorage.read_only is required for communicating with gcr.io (the Google Container Registry).

If unspecified, no scopes are added, unless Cloud Logging or Cloud Monitoring are enabled, in which case their required scopes will be added.
