### ISSUE TITLE
BoolFlag is a clumsy UX

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#19184]
It acts like a boolean flag but requires an argument, unlike boolean flag is pretty much every environment.  We need to find a better way to express the things that this is expressing.  Maybe a add a tristate to the pflag lib that behaves the same way but doesn't demand an argument?

**Comment by ncdc** [comment]
cc @deads2k

**Comment by deads2k** [comment]
> It acts like a boolean flag but requires an argument, unlike boolean flag is pretty much every environment. We need to find a better way to express the things that this is expressing. Maybe a add a tristate to the pflag lib that behaves the same way but doesn't demand an argument?

@eparis The `BoolFlag` handles "true", "false", "unset" and has a default value.  I seem to recall you were looking at changing it, but we needed to preserve the value.

The complain here is that you have to do `--flag=true` instead of just `--flag`.

/cc @liggitt

**Comment by eparis** [comment]
fixing `--flag` is really easy....
