### ISSUE TITLE
persistent volume claims get assigned to the same pv when created quickly

### ISSUE THREAD

**Issue by sjpotter** [kubernetes/kubernetes#19209]
I don't know if this is only a problem because I'm using hostPath for persistent volume testing / learning, but I've noticed that if I create N persistent volumes and then create N claims quickly (either in a for loop or just by loading a directory full of yml files) that the claims do not get assigned to individual persistent volumes but multiple claims can be assigned to one (or all to one in some cases)

[example.zip](https://github.com/kubernetes/kubernetes/files/75287/example.zip)

To recreate one can

mkdir /tmp/v{1,2,3}

kubectl create -f pv
kubectl create -f claims

and the claims don't get individual volumes

if on the other hand I do something like

kubectl create -f claims/c1.yml
kubectl get pvc  # see that it got assigned to one

kubectl create -f claims/c2.yml
kubectl get pvc # set that it got assigned to another one

kubectl create -f claims/c3.yml
kubectl get pvc # set that it got assigned to the last one

everything then works

I'd guess its a race of some sort but really have no clue.

**Comment by thockin** [comment]
@markturansky

**Comment by markturansky** [comment]
@sjpotter what version of kube are you running?  The race you're talking about was fixed fairly recently.

**Comment by sjpotter** [comment]
@markturansky using the hyperkube 1.0.1 container images from gcr for my testing.

**Comment by sjpotter** [comment]
I can test it locally with the instructions here 

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md

(basically what I was doing anyways w/ 1.0.1) with whatever version you tell me to try it with.

**Comment by markturansky** [comment]
The fix was merged Nov 25. I think you are using an older version that does not have this update.

  https://github.com/kubernetes/kubernetes/pull/16432

**Comment by sjpotter** [comment]
I guess it can be closed then as already fixed
