### ISSUE TITLE
Moving kube-proxy out of kube node

### ISSUE THREAD

**Issue by cheyang** [kubernetes/kubernetes#19211]
Current Kubernetes Deployment Mode is putting Kubelet and Kubeproxy together in the same kube node, I tried to move the kube-proxy out of the node and put it into the Service gateway node which doesn't have Pod on that. 
![kube diagram](https://raw.githubusercontent.com/cheyang/kubernetes_cd/master/kube.jpg)
The configuration in Node  is like this:
 ```
route add -net 192.168.254.0/24 gw 10.62.56.130
```
This can work.  Here are my thoughts of this deployment mode.

**Advantage**:
1. Make the compute resource in kube node only for Pods. As we know the kube-proxy will consume a lot of CPUs, Memories, IOs and Networks resources especially when using userland proxy in heavy load.
2. Service Gateway node can be focused as a route device, and even no need  for route capability for kube-proxy. We can only depend on route and iptables kernel level capabilities. 
3. No changes in existing iptables rule in Kube node.There are some default iptables rules conflicting and overwritten in kube nodes, so simplifying the iptables configuration in kube nodes are good for App Operators.  See [issue 10692](https://github.com/kubernetes/kubernetes/issues/10692)

**Disadvantage:**
1. The Service gateway is the single failure point
2. The Service gateway node has to be the in the same Layer 2 network with kube nodes which should be routed by it.

I am planning to use this deployment in our product env. I want to get the comments from kubernetes experts about this. 

Can you let me know the advantages and disadvantages in your perspectives. Thanks.

**Comment by thockin** [comment]
This is a viable way of implementing networking, I think, though I certainly have not tried it.  However:

1) you lose the HA aspect of the proxy being distributed (as you point out)
2) L2 (as you point out)
3) in the newer iptables mode the overhead of kube-proxy is very low, so this will surely perform worse
4) node-management of a new kind of "special" machine.

The only real requirement for Services is that the virtual IP exists and is backed by the Service's Endpoints.  If you can implement the VIP as you describe it sounds like it will satisfy the requirement.  I don't think it will be better, though.

**Comment by thockin** [comment]
I'm happy to leave this issue open for a while to collect feedback, but I don't think this is something we will be doing in the default implementation.

**Comment by AdoHe** [comment]
@cheyang I did some real tests about kube-proxy, I think it is quite ok if your cluster size is not that big. Your solution is a viable way, but to replace local proxy with center proxy is a big concern, for this case I prefer use other proxy solutions, like haproxy.

**Comment by cheyang** [comment]
@thockin and @AdoHe , thanks for your quick response.  It's helpful.

@AdoHe , I'd like to use several gateway nodes for  sharing the traffic. For example, 5 or 10 nodes share 1 gateway node. But I agree that the cluster management effort is not small.

**Comment by thockin** [comment]
In general we will have this tradeoff for lots of things.

Distributing work out to each node costs more resources in total, but
offers latency and HA and simplifying properties.  proxy, DNS, API proxy,
watch cache, etc.

**Comment by AdoHe** [comment]
@thockin good point :+1:
