### ISSUE TITLE
Dockerhub image pull documentation is incorrect in the user guide as of 12/31/2015

### ISSUE THREAD

**Issue by dstynchula** [kubernetes/kubernetes#19219]
The documentation says to create a secret by taking the output of docker login from ~/.docker/config.json  ,base64 the json and place it as a string into a secret.yaml. After a lot of wrangling, we found it necessary to remove the auth wrapper in the json as well as all of the spaces in the json leaving a single line for this authentication mechanism to work. Maybe the docker login config.json format has changed, but at the time of this writing these steps are required to successfully authenticate to Dockerhub and pull an image..

**Comment by dstynchula** [comment]
The resulting config.json looked like this:
{"https://index.docker.io/v1/":{"auth":"<SHA REDACTED>","email":"<EMAIL REDACTED>"}}

Base64'ing this string resulted in successful authentication to dockerhub and permitted us to pull down an image.

**Comment by bgrant0607** [comment]
Last updated by #18777, I believe.
cc @erictune

**Comment by bgrant0607** [comment]
cc @deads2k

**Comment by bgrant0607** [comment]
See also #20023

**Comment by erictune** [comment]
What OP said is true for a cluster with v1.1 kubelet, but not for HEAD.  My doc update is for HEAD.

I guess someone could backport a docs correction to v1.1.  not sure that is worthwhile.

 I tested the updated instructions when I did  #18777.

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
Can someone validate if this is still an issue in the docs? It's been open for 1.5 years. Consider sending a PR to the docs repository if so.
