### ISSUE TITLE
`kubectl get nodes` totally unreadable

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#19217]
I've just started e2e cluster. Output of `kubectl get nodes` doesn't fit my 24" screen :/

```
NAME                          LABELS                                                                                                                                                             STATUS    AGE
e2e-test-filipg-minion-8hev   failure-domain.alpha.kubernetes.io/region=europe-west1,failure-domain.alpha.kubernetes.io/zone=europe-west1-b,kubernetes.io/hostname=e2e-test-filipg-minion-8hev   Ready     2m
e2e-test-filipg-minion-x23b   failure-domain.alpha.kubernetes.io/region=europe-west1,failure-domain.alpha.kubernetes.io/zone=europe-west1-b,kubernetes.io/hostname=e2e-test-filipg-minion-x23b   Ready     2m
e2e-test-filipg-minion-xggb   failure-domain.alpha.kubernetes.io/region=europe-west1,failure-domain.alpha.kubernetes.io/zone=europe-west1-b,kubernetes.io/hostname=e2e-test-filipg-minion-xggb   Ready     2m
```

This is totally unreadable!

@kubernetes/goog-ux (assigning to @bgrant0607 as a TL of our UX team)

**Comment by bgrant0607** [comment]
We should just remove the labels column. If the user wants to know the labels, they can use describe, or `-L` to display specific label values.

**Comment by AdoHe** [comment]
@bgrant0607 I volunteer myself to do this.

**Comment by AdoHe** [comment]
@bgrant0607 I got one idea: by default, when we use `kubectl get nodes`, the `LABELS` column will not be displayed, since we already have the `-L` flag, we can use this, if we use `kubectl get nodes -L ALL` we will get result like current kubectl behavior, and if we use `kubectl get nodes -L ***` we will get the label presented as a separate column, how about this?

**Comment by bgrant0607** [comment]
Thanks, @AdoHe. 

I wouldn't use special sentinel values with `-L`. That's short for `--label-columns`, and current behavior is very different from that. We could perhaps add a new flag, which would print them at the end of each line.

However, is it possible to print them with existing template options, such as Go templates, jsonpath templates, or custom columns? If so, that might be good enough.

As we make it easier to attach labels to nodes they will be likely to carry more and more labels, which will make the current form of output less and less appealing. Often users just care about one or a couple properties, like which nodes have ssd.

**Comment by AdoHe** [comment]
@bgrant0607 Get it. I will try to use the `-o` option to implement this.

**Comment by AdoHe** [comment]
@bgrant0607 I gave a try to use the golang template to control labels display, it can meet our needs more or lees, but the template is quite complicate and also not that perfect. So I have got other idea:
* Update the default printer to not show lables by default
* Add a `--show-labels` flag, when the flag is true we show labels at the end of the line.
I did understand that users just care about one or a couple properties, for example users just want to get nodes which have ssd, for such use case I think we can use `--selector` to do this. How about this?

**Comment by bgrant0607** [comment]
@AdoHe --show-labels is fine. Ideally, it would work for any resource, not just nodes, similar to --label-columns.

Yes, either --selector or --label-columns should be sufficient for the case where users care only about a couple properties -- that was my point.

cc @janetkuo

**Comment by AdoHe** [comment]
@bgrant0607 if --show-labels is fine, I will add this flag to kubectl.

**Comment by janetkuo** [comment]
@AdoHe Sounds good. Can you give an example of how it'd look like when `kubectl get nodes --show-labels`?

**Comment by AdoHe** [comment]
@janetkuo I will paste example here when I finish the test today.

**Comment by AdoHe** [comment]
@janetkuo @bgrant0607 I tried to add a `show-labels` flag, and the result looks like:
```
[root@k8s-cluster-master ~]# kubectl get nodes
NAME             STATUS    AGE
192.168.0.1    Ready        1d
192.168.0.2    Ready       2d
[root@k8s-cluster-master ~]# kubectl get nodes --show-labels=true
NAME             STATUS    AGE       LABELS
192.168.0.1    Ready        1d           kubernetes.io/hostname=192.168.0.1
192.168.0.2    Ready        2d           ctype=one,kubernetes.io/hostname=192.168.0.2
```
how about this result? is it ok?

**Comment by AdoHe** [comment]
@bgrant0607 how about this? should I open a PR?

**Comment by bgrant0607** [comment]
Yes, sorry. Looks good. Please open a PR.

**Comment by AdoHe** [comment]
@bgrant0607 Ok, I will open a PR today.

**Comment by bprashanth** [comment]
While we're on this topic, can we have `kubectl get nodes -o wide` to show ips? I know users shouldn't have to care about ips, but it's useful (curling nodeport services, matching cidrs, debug logs etc)

**Comment by bgrant0607** [comment]
@bprashanth Sure, I have no problem with that.

**Comment by AdoHe** [comment]
Ok, I will also add this to this PR.

**Comment by AdoHe** [comment]
@bprashanth does this also apply to pod? I mean `kubectl get pods -o wide` should show IP for pod?

**Comment by bprashanth** [comment]
-o wide on pods already prints node names, i think that's more valuable than ip. My suggestion was to have -o wide on nodes print an extra column with the external ip of the node.

**Comment by bgrant0607** [comment]
This is done.
