### ISSUE TITLE
Ubuntu support broken on master (and likely several prior releases)

### ISSUE THREAD

**Issue by pwais** [kubernetes/kubernetes#19221]
I was mostly following this guide, which seems to be either deprecated and/or broken:
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md

One key bug, one of the scripts references the wrong Github account, fix:

```
diff --git a/cluster/ubuntu/download-release.sh b/cluster/ubuntu/download-release.sh
index 3fce5d0..5fb3ea1 100755
--- a/cluster/ubuntu/download-release.sh
+++ b/cluster/ubuntu/download-release.sh
@@ -56,7 +56,7 @@ grep -q "^${ETCD_VERSION}\$" binaries/.etcd 2>/dev/null || {
 KUBE_VERSION=${KUBE_VERSION:-"1.1.2"}
 echo "Prepare kubernetes ${KUBE_VERSION} release ..."
 grep -q "^${KUBE_VERSION}\$" binaries/.kubernetes 2>/dev/null || {
-  curl -L https://github.com/GoogleCloudPlatform/kubernetes/releases/download/v${KUBE_VERSION}/kubernetes.tar.gz -o kubernetes.tar.gz
+  curl -L https://github.com/kubernetes/kubernetes/releases/download/v${KUBE_VERSION}/kubernetes.tar.gz -o kubernetes.tar.gz
   tar xzf kubernetes.tar.gz
   pushd kubernetes/server
   tar xzf kubernetes-server-linux-amd64.tar.gz
```

But I still can't `kube-up.sh`:

```
$ export KUBE_VERSION=1.1.2
$ export KUBERNETES_PROVIDER=ubuntu

$ export nodes="root@10.0.10.xxx root@10.0.10.yyy"
$ export roles="ai i"
$ export NUM_MINIONS=2
$ export PATH=$PATH:~pwais/kubernetes/cluster/ubuntu/binaries

$ ./cluster/kube-up.sh 
... Starting cluster using provider: ubuntu
... calling verify-prereqs
... calling kube-up
/home/pwais/kubernetes/cluster/ubuntu /home/pwais/kubernetes
Prepare flannel 0.5.0 release ...
Prepare etcd 2.2.0 release ...
Prepare kubernetes 1.1.2 release ...
Done! All your binaries locate in kubernetes/cluster/ubuntu/binaries directory
/home/pwais/kubernetes

Deploying master and node on machine 10.0.10.240
saltbase/salt/generate-cert/make-ca-cert.sh: No such file or directory
config-default.sh                                                                                                                                100% 3441     3.4KB/s   00:00    
ubuntu/util.sh: No such file or directory
ubuntu/minion/*: No such file or directory
ubuntu/master/*: No such file or directory
ubuntu/reconfDocker.sh: No such file or directory
ubuntu/binaries/master: No such file or directory
ubuntu/binaries/minion: No such file or directory
```

I had more luck with v1.0.0 except that kube-proxy failed to launch on my minion because of an incorrect flag to the executable :P

If somebody can direct me to a **bona fide Ubuntu bare-metal setup guide**, please LMK.  Otherwise I guess I'll try to poke at master a bit more (and perhaps contribute a patch if I get anywhere).

**Comment by pwais** [comment]
FWIW this is master @ 7743a4ca8916a9e8acac481550ddc0ac813b42b1

**Comment by WIZARD-CXY** [comment]
It seems the download url of kubernetes need to be updated and the conf file are not 'scpped" to the master machine successfully.

**Comment by WIZARD-CXY** [comment]
can you confirm by seeing the '~/kube/' directory on master node, does it contain ubuntu/util.sh and all the other missing files?

**Comment by pwais** [comment]
Here is what I did to get things working:

https://github.com/kubernetes/kubernetes/compare/master...pwais:pwais_fix_ubuntu

One unsolved issue is that the role -> roles variable hack happens in `cluster/ubuntu/config-default.sh`; perhaps it should move to `ubuntu/util.sh`.  I found that without my change `kube-up.sh` was *not* sourcing `cluster/ubuntu/config-default.sh` on the deploy host-- this I believe is the root cause of the `role` bug mentioned in #11711 .  (If one had `role` and `roles` set in the env during testing, then the bug wouldn't appear).

This change helps fix the above problem, but in order for any of this to be useful the user has to basically copy `cluster/ubuntu/config-default.sh` and use `$KUBE_CONFIG_FILE`.  That's not bad, but would require editing the `ubuntu.md` setup guide, and likely invalidates any 3rd party ubuntu tutorials (which are probably broken anyways since all these scripts are broken currently).  A core problem in the `cluster/ubuntu` code (in master right as-is) is that the scripts seem to think env settings get carried thru the `ssh` calls, and they don't without further configuration.  I think whoever tested these scripts didn't do so on a clean setup, or only on a single node, or somebody refactored them and didn't test things.  AFAICT this stuff has been broken at least as of 1.0.

If this change looks mostly OK so far, I think the next course of action is to edit the `ubuntu.md` startup guide and create a formal PR.  It would be amazing if we could also add automated testing somehow so that this stuff doesn't get so broken in the future, but I'm not sure what resources the k8s project has for something like that.

**Comment by pwais** [comment]
Also FWIW https://github.com/kubernetes/kubernetes seems to be missing some releases (e.g. I couldn't pull 1.1.0 anymore today).  Is there a better place to pull releases?  (Also, how can I push code built from source?)

**Comment by mvoropaiev** [comment]
@pwais you can get 1.1.0 release from the following URL found in '[Releases](https://github.com/kubernetes/kubernetes/releases)' section:
https://github.com/kubernetes/kubernetes/releases/tag/v1.1.0

**Comment by resouer** [comment]
ping @dalanlan

First thought, I don't think we have to use `roles`, can we make decision based on `NODES` & `MASTER` like [this](https://github.com/kubernetes/kubernetes/pull/13901/files#diff-d70f09536b044cb2000a89053261a00eR110) ?

**Comment by resouer** [comment]
@pwais PR is always welcome, which is a better way to discuss how this can be fixed.

**Comment by pwais** [comment]
@mvoropaiev `curl https://github.com/kubernetes/kubernetes/releases/download/v1.1.0/kubernetes.tar.gz` 404s for me and that's what the k8s script runs.  

@resouer I imagine `roles` is a bit of tech debt from before the scripts used `MASTER` and `NODES` more uniformly.


New problems:
I've also recently discovered that `deployAddons.sh` (DNS in particular) seems to be broken, haven't debugged thoroughly yet.  After I run it I see:

```
# kubectl create -f /tmp/busybox.yaml
pod "busybox" created


# kubectl exec busybox -- nslookup kubernetes.default
Server:    192.168.3.10
Address 1: 192.168.3.10

nslookup: can't resolve 'kubernetes.default'
error: error executing remote command: Error executing command in container: Error executing in Docker Container: 1
```

`kube-down.sh` also fails after I run `deployAddons.sh`; get some stuck resources in `/var/lib/kubelet/pods/xxxx/volumes/kubernetes.io~secret/default-token-92vew`

kube-ui seems to work tho.  

I tried the docker multinode tutorial before the ubuntu one and the docker setup failed because it was starting kube-proxy with an invalid flag :P

**Comment by dalanlan** [comment]
@pwais 
Sorry bu I was OoO last week ;-)
First of all, thank you for reporting this.  And let me try to sort this out.
- KUBE_CONFIG_FILE env thing. I has exported it like util.sh #L309. 
- DNS. Please file another issue when you dig it up later. 
- kube-down. I've tried to clean up resource and would not tear down the cluster util there are no pods, secrets or whatever. If you could only confirm there remains a leak, you might wanna go to kubelet for details. 

Feel free to send a pr if you dont mind.

**Comment by gnudeep** [comment]
RUNTIME_CONFIG does not set apiserver runtime-config parameter. As a workaround I had to update create-kube-apiserver-opts in util.sh manually as follows.

node0:~/kubernetes/cluster/ubuntu$ git diff util.sh
diff --git a/cluster/ubuntu/util.sh b/cluster/ubuntu/util.sh
index 6d81ee0..b21a729 100755
--- a/cluster/ubuntu/util.sh
+++ b/cluster/ubuntu/util.sh
@@ -199,6 +199,7 @@ KUBE_APISERVER_OPTS="\
  --insecure-bind-address=0.0.0.0\
  --insecure-port=8080\
  --etcd-servers=http://127.0.0.1:4001\
+ --runtime-config=extensions/v1beta1/deployments=true,extensions/v1beta1/daemonsets=true\
  --logtostderr=true\
  --service-cluster-ip-range=${1}\
  --admission-control=${2}\

**Comment by dalanlan** [comment]
@gnudeep  We won't support every flag in the scripts. The users could do this manually if they want it badly.

**Comment by gnudeep** [comment]
@dalanlan How about adding an entry to the Ubuntu Bare Metal document page explaining this step.

**Comment by MikeSpreitzer** [comment]
Oddly, I have been following this guide for the past few months, without any of the problems reported above.  I have not tested kube-down or API extensions.

**Comment by MikeSpreitzer** [comment]
For one thing, the instructions in https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md do *not* reference the `download-release.sh` script nor anything that invokes it.

Since I have been trying this, the `kube-up` function in `cluster/ubuntu/util.sh` has had the line that defines `KUBE_CONFIG_FILE` and sources it.  And config-default.sh uses two distinct envars, `role` and `roles` so that each is assigned just once, even if the script is run multiple times.  So I have not had problems with envars defined in `config-default.sh` --- apart from the fact that `deployAddons.sh` does not ensure `KUBE_CONFIG_FILE` is defined (which I have opened as issue #19484 and submitted PR #19640 against).

**Comment by dalanlan** [comment]
>For one thing, the instructions in https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md do not reference the download-release.sh script nor anything that invokes it.

@MikeSpreitzer I can't see the necessity 'cause it would be triggered automatically.

**Comment by pwais** [comment]
@MikeSpreitzer: the scripts on master definitely don't work.  try setting up two `nodes` and run `kube-up.sh`.  the nodes will launch but verification will wait for three nodes due to how the defaults are set up.

**Comment by pwais** [comment]
@dalanlan: https://github.com/kubernetes/kubernetes/pull/19763

**Comment by pwais** [comment]
ok if i run `./deployAddons.sh` in `cluster/ubuntu` (in my PR branch) I can access `http://(master):8080/ui` OK.  I think `./deployAddons.sh` might be a little too sensitive to paths ...

**Comment by MikeSpreitzer** [comment]
@pwais: At the end of https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md#deploy-addons it specifically says to use that CWD.

**Comment by MikeSpreitzer** [comment]
Also, it seems to me that https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md#configure-and-start-the-kubernetes-cluster specifies the CWD to use when invoking `kube-up.sh`.  I have always been invoking `kube-up.sh` with CWD=cluster, and invoking `deploy-addons.sh` with CWD=cluster/ubuntu.

**Comment by MikeSpreitzer** [comment]
@pwais: regarding https://github.com/kubernetes/kubernetes/issues/19221#issuecomment-172246849 - do you mean to try a configuration with one master and two workers?  Did you update the definitions of `nodes` and `role` in config-default.sh correspondingly?

**Comment by MikeSpreitzer** [comment]
@dalanlan - oh, I somehow overlooked the fact that kube-up calls download-release.sh.  I have been exercising the one with the outdated reference all this time.  Now I am going to test release 1.1.4 from github.com/kubernetes/kubernetes.

**Comment by MikeSpreitzer** [comment]
@pwais: regarding https://github.com/kubernetes/kubernetes/issues/19221#issuecomment-172246849 --- I just tested a configuration in which one machine is both master and worker and two additional machines are just workers.  It worked.  Following are some relevant excerpts from `config-default.sh`.
```bash
export nodes="10.143.197.80 10.143.197.125 10.143.129.208 "
...
role="ai i i"
...
export NUM_NODES=3
```

I am using Ansible to automatically update `nodes`, `role`, and `NUM_NODES` in `config-default.sh` according to my chosen configuration.

**Comment by MikeSpreitzer** [comment]
I tested with download-release.sh setting `KUBE_VERSION=${KUBE_VERSION:-"1.1.4"}` a couple of times, and they worked.

**Comment by borg286** [comment]
I just did a fresh install of ubuntu 15.10 and also tried 14.04 targeting single node bare metal (ie. fixed nodes, role and NUM_NODES environment variables) and both times it fails at starting up etcd.  I am running virtualbox on windows desiring to have kubernetes running on bare metal ubuntu.

Under ubuntu 14.04 I look at /var/log/upstart/etcd.log and I see complaints about
 listen tcp 127.0.0.1:4001: bind: address already in use

I created a virtualbox, installed ubuntu, installed docker, git pulled kubernetes, edited config-defaults.sh under kubernetes/cluster/ubuntu with the following modifications

export nodes=${nodes:-"borg@127.0.0.1"}
role=${roles:-"ai"}
export NUM_NODES=${NUM_NODES:-1}
export SERVICE_CLUSTER_IP_RANGE=${SERVICE_CLUSTER_IP_RANGE:-10.0.0.0/8} 
and I set the DNS server to 10.0.0.1

I did this same setup with ubuntu 15.10 but had to install a package that allowed the util.sh script to run "service etcd start" and have it find the service definitions in init.d instead of systemd.  
(Side note: we should either update the docs to say that you need to install "<remember the package name>" if you're running ubuntu 15.05+ or to update the startup folder to have startup configs for both OSs.

**Comment by MikeSpreitzer** [comment]
I have continued to use this scripting without the problem described above.  I am not sure why.  I use this scripting only with Ubuntu 14.04.  Normally I do a multi-machine install, with one machine being master only and the others being minions.  To investigate @borg286's complaint just now, I did a single-machine install (one machine being both master and the only minion).  I still did not have the reported problem.  For comparison purposes, I have attached a zip archive including my config-default.sh, etcd.log, and the stdout and stderr from kube-up.
[debris.zip](https://github.com/kubernetes/kubernetes/files/160155/debris.zip)

Note that `role` and `roles` are different environment variables.  @borg286 you mixed up the two in your comment above.

I invoked kube-up like this:
`cd /home/mspreitz/kubernetes/cluster && KUBERNETES_PROVIDER=ubuntu DEBUG=true ./kube-up.sh`

This typescript shows exactly what I ran:
```
$ git branch -v
* merge304-14 1441b48 Merge branch 'issue/21697' into merge304-14

$ git remote -v
origin	https://github.com/MikeSpreitzer/kubernetes.git (fetch)
origin	https://github.com/MikeSpreitzer/kubernetes.git (push)
```

(Sorry, I meant to run master from upstream but goofed; anyway, as you can see at https://github.com/kubernetes/kubernetes/compare/master...MikeSpreitzer:merge304-14?expand=1 , there is no relevant delta.)

Also, @borg286, there was some quoting problem with the side note at the end of your comment above --- the thing to install is not visible.

**Comment by borg286** [comment]
the package that got the init.d scripts running on ubuntu 15.10 was
sudo apt-get install upstart-sysv

**Comment by borg286** [comment]
tell me what do I need to have preinstalled? AFAIK only docker and pasword-less ssh.
I am doing passwordless ssh to 127.0.0.1.

**Comment by MikeSpreitzer** [comment]
For now let's focus on 14.04, I suspect that will be sufficient to clear up whatever is going on here.

@borg286 did you understand my remarks about `role` vs `roles`?  It would help if you could exhibit your modified `config-defaults.sh`.

I hope you are aware that the docs as exhibited on the web (e.g., at http://kubernetes.io/v1.1/docs/getting-started-guides/ubuntu.html) are all outdated.  I used to read the latest docs at their source, such as https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md --- however, all the content has recently been moved from there and I do not know where the latest doc source really is.

The machines onto which k8s will be installed need to have docker and bridge-utils already installed.  BTW, docker does NOT need to be configured with a cluster store, and you do NOT need to have etcd already installed and running.

Password-less `ssh` needs to be enabled from the machine running kube-up to the machines on which k8s is being installed.  Note that the machine running kube-up does NOT need to be your k8s master, although it CAN be.

**Comment by WIZARD-CXY** [comment]
Thanks for your comprehensive  explanation @MikeSpreitzer 
@borg286 I think you can follow what Mike said

**Comment by dalanlan** [comment]
> I used to read the latest docs at their source, such as https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md --- however, all the content has recently been moved from there and I do not know where the latest doc source really is.

Ah, this is not cool. What are we supposed to do if we want to update the docs?

**Comment by borg286** [comment]
They've moved to a different github repo. They link to it from the website.

**Comment by dalanlan** [comment]
@MikeSpreitzer [This](https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/ubuntu.md) should do

**Comment by kostasp** [comment]
The line  -listen-client-urls ` -listen-client-urls http://127.0.0.1:4001,http://${1}:4001\` in `util.sh` is problematic and should be changed to `-listen-client-urls http://${1}:4001\` .  it is  causing the configuration in `/etc/default/etcd` configuration to have duplicate  etc client url entry.

**Comment by ido-ran** [comment]
I've run into the same issue, removing the http://${1}:4001 change something but the deployment still fail with the following outout. It continue retry but never did.

```
flanneld.conf                                                                                                                      100%  570     0.6KB/s   00:00
flanneld                                                                                                                           100% 2131     2.1KB/s   00:00
etcd start/running, process 3316
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Error:  100: Key not found (/coreos.com) [16]
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
sudo: brctl: command not found
stop: Unknown instance:
docker start/running, process 3499
Connection to 127.0.0.1 closed.
Validating master
Validating root@127.0.0.1
Using master 127.0.0.1
cluster "ubuntu" set.
user "ubuntu" set.
context "ubuntu" set.
switched to context "ubuntu".
Wrote config for ubuntu to /home/ubuntu/.kube/config
... calling validate-cluster
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
```

**Comment by kargakis** [comment]
@kubernetes/sig-onprem-misc

**Comment by resouer** [comment]
On prem scripts have been deprecated, I will close this.
