### ISSUE TITLE
unit flake: bind address in use

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#19233]
Use "kubectl create [command] --help" for more information about a command.
    +++ [0103 04:22:21] Starting kubectl proxy
    +++ [0103 04:22:21] On try 1, use proxy port 33300 if it's free

    netcat isn't installed, can't verify if 127.0.0.1:33300 is free, skipping the check...

    F0103 04:22:21.959031   28201 proxy.go:132] listen tcp 127.0.0.1:33300: bind: address already in use

Example failure:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/5505/consoleText

**Comment by thockin** [comment]
prio for flakes

**Comment by roberthbailey** [comment]
Where is this test running (I just checked and netcat is installed on containerVM instances by default). Can we use a different image (or base image if this is running in a container) that has netcat to fix this issue?

**Comment by ArtfulCoder** [comment]
closed via https://github.com/kubernetes/kubernetes/pull/19836
