### ISSUE TITLE
kubelet should handle the docker daemon down properly

### ISSUE THREAD

**Issue by adohe** [kubernetes/kubernetes#19249]
FYI. I am using docker `1.8.2` and kubernetes `1.1.2`, and just attach one node to the master. I create some pods using `kubectl`, and the pods are all running. Then I use `kill -15 docker` to kill the docker daemon process on the node, when the docker daemon process down, I query the pods status on master, they are all running. Even after ten minutes, the pods are still in running status. Of course from the source code, the kubelet main loop will check the container runtime up status and log the error. I am wondering simple logging is not enough, maybe we should report this to api server.

**Comment by yujuhong** [comment]
It's not clear from your description whether the docker daemon stayed down. The default cluster setup scripts sets up daemons (e.g., supervisord) to babysit the docker daemon and restart it if necessary. Could you check if docker stays down after you kill it?

Also, kubelet should report the node status as not ready if the daemon is down. If a node remains not ready for >5 minutes (the default threshold), the node controller should evict (delete) all pods assigned to the node. Could you confirm if node status transitioned to NotReady? Thanks.

**Comment by AdoHe** [comment]
@yujuhong yes, the docker daemon stays down after I kill it. I checked the node status, it is NotReady but when I use `kubectl get pods`, the pods are still running, after about <b>13m</b>, the pods get deleted. I know from source code, the node controller will delete all pods, but as I can see it should take that long. I will do another test today and make sure it really exists.

**Comment by yujuhong** [comment]
IIRC, the default pod eviction timeout is 5 minutes. When did the node transition to NotReady? It might help to check kube-controller-manager.log

**Comment by AdoHe** [comment]
@yujuhong I test this again. The node transition to NotReady after 5 minutes since when I kill the docker daemon, but the pods are still on running state, and after about 11m, pods get deleted.

**Comment by yujuhong** [comment]
I guess it can be 5 minutes for the transition of node status, and another 5 minutes for the eviction to kick in? if that's the case, you should be able to change the timeout to be more aggressive. It's been a while since I last looked at the code, someone from @kubernetes/goog-control-plane will know more.

**Comment by mikedanese** [comment]
Relevant controller-manager flags are:

```
      --deleting-pods-burst=10: Number of nodes on which pods are bursty deleted in case of node failure. For more details look into RateLimiter.
      --deleting-pods-qps=0.1: Number of nodes per second on which pods are deleted in case of node failure.
      --node-monitor-grace-period=40s: Amount of time which we allow running Node to be unresponsive before marking it unhealty. Must be N times more than kubelet's nodeStatusUpdateFrequency, where N means number of retries allowed for kubelet to post node status.
      --node-startup-grace-period=1m0s: Amount of time which we allow starting Node to be unresponsive before marking it unhealty.
      --node-sync-period=10s: The period for syncing nodes from cloudprovider. Longer periods will result in fewer calls to cloud provider, but may delay addition of new nodes to cluster.
      --pod-eviction-timeout=5m0s: The grace period for deleting pods on failed nodes.
```

We wait 5 minutes after the pods go not ready before evicting pods. That is consistent with your timeline. What is suspicious is that it took 5 minutes for your pods to become not ready. Are you using a getting started guide?

**Comment by AdoHe** [comment]
@mikedanese I will check our controller manager configuration and add more information here.

**Comment by gmarek** [comment]
NodeController should report Node as NotReady after 40s if Node is not updating it's status. The transition to NotReady in the case of DockerFailure is entirely on Kubelet's side. NodeController should notice it here and update its internal cache: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L602
Afterwards it should evict all pods here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L417

It means that it shouldn't take longer than `pod-eviction-timeout + pod-delete-grace-period + node-monitor-period`, which by default is `5m + 30s + 5s` after Kubelet update Node's status.

**Comment by AdoHe** [comment]
@mikedanese @gmarek I have checked that our controller manager uses the default configuration and the default node update frequency of kubelet is 10s, the expected time should be `5m + 30s + 5s + 10s`, but the result is `11m` before the pods get deleted. kind of tricky.

**Comment by gmarek** [comment]
@AdoHe - can you grab all the events mentioning the Node in question? There should be an event for any change of the status.

**Comment by yujuhong** [comment]
Closing a support issue due to age.
