### ISSUE TITLE
integration flake: timeouts in kubernetes-test-go-release-1.1

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#19248]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go-release-1.1/2055

I can't see anything immediately wrong, so it may be an honest timeout, i.e. solution would be to increase it.

We need an owner for integration tests in general...
@brendandburns @thockin @davidopp @dchen1107 @ixdy @bgrant0607

**Comment by gmarek** [comment]
We need to cherry pick #14802 into branch 1.1

**Comment by roberthbailey** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/19250.
