### ISSUE TITLE
Scheduler latency metrics should separate error case from normal

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#19246]
Currently scheduler latency [metrics](https://github.com/kubernetes/kubernetes/blob/c4fdb7a2d06db250f577f06e41182a9f22cc8f7c/plugin/pkg/scheduler/metrics/metrics.go#L31) are observed regardless of failure. For example, binding latency is [recorded](https://github.com/kubernetes/kubernetes/blob/c4fdb7a2d06db250f577f06e41182a9f22cc8f7c/plugin/pkg/scheduler/scheduler.go#L152) like:
```Go
err := s.config.Binder.Bind(b)
		metrics.BindingLatency.Observe(metrics.SinceInMicroseconds(bindingStart))
		if err != nil {
			glog.V(1).Infof("Failed to bind pod: %+v", err)
			...
			return
		}
```

This could be a potential confusion if latency spikes happen because of failure. We should better handle it like separating error case from normal

**Comment by gmarek** [comment]
I completely agree - @hongchaodeng are you going to change this?

**Comment by hongchaodeng** [comment]
Yes. I will do it. @gmarek
