### ISSUE TITLE
DNS add-on picking up wrong port on docker deployment

### ISSUE THREAD

**Issue by runseb** [kubernetes/kubernetes#19262]
Hi,

I have seen many issues related to the DNS add-on. But can't quite get it to work yet. So here is another one.

I have a single node docker deployment of k8s. With self-signed certs and token access. I managed to get the service accounts to work properly, I can run basic pods/rc etc. Even deployment manager.

But when launching the DNS add-on it seems that kube2sky is trying to reach the api server on 443 when I am serving on 6443.

    $ kubectl logs kube-dns-v8-1qsx7 kube2sky --namespace=kube-system
    I0104 17:24:46.607401       1 kube2sky.go:436] Etcd server found: http://127.0.0.1:4001
    I0104 17:24:47.609722       1 kube2sky.go:503] Using https://10.0.0.1:443 for kubernetes master
    I0104 17:24:47.609821       1 kube2sky.go:504] Using kubernetes API <nil>

The service accounts are created, the secrets are created, they are mounted on the pods...etc
I might have an issue with the validity of the self-signed certs but right now it's not reaching the API server at all, since using the wrong port.

Any thoughts ?

**Comment by luxas** [comment]
What does `kubectl get svc` output? 
The default internal `kubernetes` route should always be `10.0.0.10:433`, even though `apiserver` is listening on `0.0.0.0:6443`

I guess it's something other that's wrong. The `kube2sky` log seems fine.

**Comment by runseb** [comment]
Ok so that's a problem with the docker deployment.
Being fixed with https://github.com/kubernetes/kubernetes/pull/19069
so I will close this.
