### ISSUE TITLE
Garbage collect stale RCs from deployment

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#19266]
Long use of deployment can result in a lot of stale RCs. Currently there is no easy way to garbage collect them.

Note that we do need to keep the last RC to allow rollback, but all previous ones can be deleted.

cc @janetkuo @kargakis @ironcladlou

**Comment by dpratt** [comment]
It'd be nice to have the deployment controller do the cleanup, or alternatively if there's a way to query for RCs by replica count from kubectl/API, we could also use that in our deployment scripts.

**Comment by mqliang** [comment]
I send a issue several weeks ago to address this https://github.com/kubernetes/kubernetes/issues/19111

**Comment by bgrant0607** [comment]
Thanks @mqliang. Let's use the other issue.
