### ISSUE TITLE
kubectl: improve error message on syntax error

### ISSUE THREAD

**Issue by cpatulea** [kubernetes/kubernetes#19279]
```
$ cat example.json
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "example",
  },
  "spec": {
    "containers": [
       {
          "name": "example",
          "image": "phusion/baseimage:latest",
          "command": [
            "echo", "hello"
          ],
       },
    ],
  }
}
```

(There's a syntax error in there somewhere, not sure where.)

$ kubectl create -f example.json 
invalid character '}' looking for beginning of object key string

kubectl should include the line and column number so I can fix my json.

**Comment by AdoHe** [comment]
maybe duplicated with #12231

**Comment by bgrant0607** [comment]
Thanks @AdoHe. Closing in favor of #12231.
