### ISSUE TITLE
Remove pkg/api/latest

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#19275]
pkg/api/latest has generic code on what all groups are enabled and the GroupMeta corresponding to them.
pkg/registered seems a better place for this and already has some of the code (like what all groups are enabled).

I will move the relevant code from pkg/api/latest to pkg/api/registered and delete pkg/api/latest.

cc @lavalamp @smarterclayton @deads2k @caesarxuchao @kubernetes/goog-csi

**Comment by smarterclayton** [comment]
Can you do this after split codec (17922) lands?

**Comment by smarterclayton** [comment]
GroupMeta should never have been added to Latest - it's also not really appropriate because codecs won't work this way in the future (nor will versioning).  We shouldn't be using groupmeta internally - there is no one size fits all "this is the group meta for an object", since it's unlikely to have the right interfaces.

**Comment by smarterclayton** [comment]
Registered is a good place for most of latest.  We should move a lot of the global constants out of there (as much as possible) and have clients and apiserver initialize codecs and the new negotiated serializer.  Resource versioner can probably stay, although that might just need to get folded into metadata accessor (which is api/meta, but doesn't import api/, it's just interfaces compatible with our code).

**Comment by nikhiljindal** [comment]
Agreed that GroupMeta should not have been added to latest.
Why is it unlikely to have the right interfaces? We can still provide the Codec in GroupMeta?

**Comment by smarterclayton** [comment]
Codec won't be part of group meta - it's possible negotiated serializer
might be, but even that is unlikely.  It's more likely that clients will
instantiate a codec factory directly for the scheme the API is built on.
