### ISSUE TITLE
Where to define common api machinery objects used by genericapiserver and client

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#19273]
There are lots of objects like RESTMapper, GroupMeta (almost all of latest.go and registered.go), etc that are currently defined in `pkg/api` and are used by both `pkg/genericapiserver` and `pkg/clients`.

I want to remove `pkg/genericapiserver`'s dependency on `pkg/api` and hence want to move those objects somewhere else.

I was thinking of moving them to genericapiserver pkg, but @caesarxuchao pointed out that client should not depend on genericapiserver.
I am now thinking of moving them to a new `pkg/apimachinery` package. Both genericapiserver and client can depend on it.
But then, when we move `pkg/genericapiserver` to a separate repository (https://github.com/kubernetes/kubernetes/issues/2742), it will still depend on apimachinery package in kubernetes repo.

Thoughts?

@lavalamp @smarterclayton @caesarxuchao @kubernetes/goog-csi

**Comment by smarterclayton** [comment]
Apimachinery is a weird word :)

Rest mapper should not be dependent on our API objects, for sure.

Can you list the types out you plan to move? I would expect certain
ones to be under something like pkg/api/rest (which doesn't depend on
our API objects).

**Comment by nikhiljindal** [comment]
To clarify, api_machinery was proposed as a package for generic operations on API objects (conversion, defaulting, validation, etc) in https://github.com/kubernetes/kubernetes/pull/16062.
While that proposal only talks about `/apis`, my inference from that is that we do not want generic RESTMapper code in `pkg/api`. We should only have the v1 API objects and related code in `pkg/api`

**Comment by lavalamp** [comment]
Somewhere under apimachinery/ sounds good to me. (or api/machinery/...)

> But then, when we move pkg/genericapiserver to a separate repository (#2742), it will still depend on apimachinery package in kubernetes repo.

If we do that split, at or before the same time, we'd have to also split tools into its own repository for exactly this reason, so that client and server can both depend on it. Repository dependency needs to be acyclic :)

**Comment by nikhiljindal** [comment]
Thanks. Will move registered to `pkg/apimachinery`. Related: https://github.com/kubernetes/kubernetes/issues/19275

@smarterclayton How about moving `pkg/api/rest` to `pkg/apimachinery/rest`? We want that `pkg/genericapiserver` and untyped clients should not depend on `pkg/api`.

**Comment by caesarxuchao** [comment]
> If we do that split, at or before the same time, we'd have to also split tools into its own repository for exactly this reason, so that client and server can both depend on it. Repository dependency needs to be acyclic :)

I've discussed with @nikhiljindal. Our concern is that might cause a lot of development overhead. E.g., a developer who wants to change an interface in tools will need to submit PRs to all three repositories.

**Comment by smarterclayton** [comment]
pkg/genericapiserver/rest is fine - the package dependencies can go either
way.  I'm not a fan of api machinery as a package name - I'd prefer we come
up with something better before we start sticking stuff under it.

**Comment by lavalamp** [comment]
> Our concern is that might cause a lot of development overhead. E.g., a developer who wants to change an interface in tools will need to submit PRs to all three repositories.

Yeah, that is a big downside to actually physically splitting into separate repos. I think for now we should not expect to physically do that split, but we *should* arrange our repository so that such a split would involve *only* moving files and vendoring *without* any code changes whatsoever.

**Comment by smarterclayton** [comment]
And we should absolutely put import protections in place stat, so that we
fail merges that cross those boundaries

**Comment by lavalamp** [comment]
Yes, absolutely-- I plan to start on that as soon as I dig out from under
the mountain of email and PRs.

**Comment by nikhiljindal** [comment]
Another name which we can use instead of apimachinery: apiframework (suggested by @bgrant0607  at https://github.com/kubernetes/kubernetes/issues/4851#issuecomment-132052036).

**Comment by smarterclayton** [comment]
I'm ok with either for now, assuming that when we split them out of the
codebase we can think longer on a name (since a number of packages will go
with it - runtime, conversion, etc)

**Comment by bgrant0607** [comment]
Or restserver and restclient.

**Comment by nikhiljindal** [comment]
Closing this since we have `pkg/apimachinery` now.
