### ISSUE TITLE
Full Storage cause pod replication loop

### ISSUE THREAD

**Issue by arkkanoid** [kubernetes/kubernetes#19289]
Hi, 
I've created a new pod of replica=1 and when I run "get pods" I got a lot of replicas (~10) of the same pod with status "OutOfDisk".:
    omk-application-microservice-0864j   0/1       OutOfDisk   0          9m
    omk-application-microservice-0kk77   0/1       OutOfDisk   0          9m
    omk-application-microservice-0l13x   0/1       OutOfDisk   0          9m
    omk-application-microservice-0tuk4   0/1       OutOfDisk   0          4m
    omk-application-microservice-0zdrf   0/1       OutOfDisk   0          6m
    omk-application-microservice-14qxm   0/1       OutOfDisk   0          6m
    omk-application-microservice-1czde   0/1       OutOfDisk   0          8m
    omk-application-microservice-1dqkf   0/1       OutOfDisk   0          3m
    omk-application-microservice-1lojd   0/1       OutOfDisk   0          2m
    ...
I've deleted all pods "kubectl delete pods --all". After this execution, the list of pods was more extensive (~50).
Finnally I saw that my worker node had full storage and I removed some images of this node.
Now I can delete all pods and creating new successfully.

Why is kubectl trying to create new pods if the number of replicas is 1?

Thanks.

**Comment by fabioy** [comment]
It's a known issue (see #4135 and #7660). Those are failed pods, and since there are no replicas running, the scheduler keeps trying to schedule, not realizing the node is out of disk. There's a good explanation of it here:

http://stackoverflow.com/questions/32285003/outofdisk-pods-get-not-destroyed-correctly/32508419
