### ISSUE TITLE
Fix GKE reboot ci tests

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19291]
The GKE reboot CI tests are failing.

The four tests that are failing probably shouldn't even be running with the reboot suite.  The GKE reboot suite is running quite a different set of tests from the GCE reboot tests; they should be fixed so they're the same except for differences in provider.

Related to #10548.

**Comment by yujuhong** [comment]
A question, @ihmccreery: kubernetes-e2e-gke-ci also runs all the reboot tests. This seems undesirable. Should they be moved out from the suite now that we test reboot tests in gke-ci-reboot?

**Comment by ihmccreery** [comment]
Kubernetes should be expected to survive on reboot, so I've been thinking of the reboot tests as something we should run along with all of our other serial tests, and if it's flaky it should be deflaked.

They do take a long time to run, but once we move to only running serial jobs in serial and running parallelize-able tests in parallel (hopefully soon), the time lag should be alleviated.

I think the only strong argument for quarantining them is to contain failures, but I think having other tests run after them is a good sanity check that the cluster is in fact recovering as expected, similar to how we randomize the order of tests running.

**Comment by ihmccreery** [comment]
I'm closing this as obsolete and will instead put effort toward #10548.
