### ISSUE TITLE
e2e flake: Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance] 

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#19304]
I can see two failures out of the past approx 100 runs.  Both failures look the same. Logs below:

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/22348/testReport/(root)/Kubernetes%20e2e%20suite/Kubectl_client_Kubectl_describe_should_check_if_kubectl_describe_prints_relevant_information_for_rc_and_pods__Conformance_/
```
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:606
Jan  4 18:55:18.483: Failed to find Events: in Name:		redis-master
Namespace:	e2e-tests-kubectl-i7zpo
Image(s):	redis
Selector:	app=redis,role=master
Labels:		app=redis,role=master
Replicas:	1 current / 1 desired
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
No events.
```

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/22471/testReport/(root)/Kubernetes%20e2e%20suite/Kubectl_client_Kubectl_describe_should_check_if_kubectl_describe_prints_relevant_information_for_rc_and_pods__Conformance_/

```
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:606
Jan  5 22:16:22.752: Failed to find Events: in Name:		redis-master
Namespace:	e2e-tests-kubectl-6cabg
Image(s):	redis
Selector:	app=redis,role=master
Labels:		app=redis,role=master
Replicas:	1 current / 1 desired
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
No events.
```

**Comment by quinton-hoole** [comment]
@kubernetes/goog-ux

**Comment by davidopp** [comment]
This probably is unrelated to kubectl...

@lavalamp do you think you could take a look at it?

If not, feel free to unassign.

**Comment by gmarek** [comment]
http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce/23052/

**Comment by lavalamp** [comment]
@davidopp I won't be able to look until next week.

**Comment by lavalamp** [comment]
The issue is that the test searches for the string "Events:" in the output, but if no events are found kubectl outputs "No events." which doesn't match.

I think I'll make the test also accept "No events", since the point is to test kubectl output, not the rest of the system, and replication controller events should be tested elsewhere?

**Comment by bgrant0607** [comment]
This looks like it was added in #10920 by @mwielgus as part of #10764 -- just creating e2e tests for all kubectl commands.

We could just remove the events line.
