### ISSUE TITLE
Probably should not use float in our API

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#19315]
There are just SOOOOOO many corner cases around float, we should just change it to a Quantity or int 0-100 or 0-100000 (NodeUtilization.Value)

@jszczepkowski 
@bgrant0607

**Comment by bgrant0607** [comment]
Already documented:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#primitive-types

**Comment by bgrant0607** [comment]
The right fix to the ClusterAutoscaler API is to delete the whole thing, though.

**Comment by mqliang** [comment]
I can help with this

**Comment by mqliang** [comment]
@bgrant0607 https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L652

```
	// Target average utilization of the cluster nodes. New nodes will be added if one of the
	// targets is exceeded. Cluster size will be decreased if the current utilization is too low
	// for all targets.
	TargetUtilization []NodeUtilization `json:"target"`
```
Why this is an array? I think it should be a map.

**Comment by bgrant0607** [comment]
@mqliang https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#lists-of-named-subobjects-preferred-over-maps

**Comment by bgrant0607** [comment]
@mqliang At this point, we should just document in types.go that this type is deprecated and will be removed from extensions/v1beta1.

**Comment by mqliang** [comment]
@bgrant0607 I just notice that you sent another issue to address removing ClusterAutoscaler from extensions/v1beta1. https://github.com/kubernetes/kubernetes/issues/17486

Does any one has picking this up? If there is anyone working on this, I think I'd better not participate in to avoid messing things up.

**Comment by bgrant0607** [comment]
@mqliang Yes, I'm just going to close this.
