### ISSUE TITLE
Fully automate k8s release process

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#19312]
Effectively reduce the text of https://github.com/kubernetes/kubernetes/blob/master/docs/devel/releasing.md to a few lines calling a single entry point that automates the process from end to end.

**Comment by david-mcmahon** [comment]
Several open issues are related or already fixed by the pending new tooling.

- [ ] #16529
- [ ] #20946
- [ ] #20562
- [ ] #19966
- [ ] #19174
- [ ] #16937
- [ ] #16529

**Comment by roberthbailey** [comment]
@david-mcmahon status with respect to the upcoming 1.3 release?

**Comment by david-mcmahon** [comment]
Yes, this is a long standing / meta issue that is being fixed in kubernetes/release and is more a nice to have than a blocker for 1.3.
