### ISSUE TITLE
k8s ui

### ISSUE THREAD

**Issue by Toplife** [kubernetes/kubernetes#19316]
hi all genius,
when we have k8s ui can replace cli to manage cluster?

**Comment by luxas** [comment]
Here's the project: https://github.com/kubernetes/dashboard
Beta is probably coming in January-February

**Comment by jlowdermilk** [comment]
Closing this. For future reference, quick questions of this sort will usually get answered faster on [slack.k8s.io](http://slack.k8s.io/)

**Comment by Toplife** [comment]
ok,Thanks.
Expecting.
