### ISSUE TITLE
Remove validation of ResourceVersion in the Update() methods of typed clients

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#19323]
Some Update() methods in the typed clients checks if `len(ResourceVersion)==0` and if so invalidates the update. Such clients include that for endpoints, events, limit_ranges, namespaces, persistentvolumeclaim and persistentvolumes.

We should keep a thin client so we shouldn't do such validations at the client side. And our server has implemented the same validation: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L321

The twist is that at server side, for some objects we `AllowUnconditionalUpdate`, e.g., https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/namespace/strategy.go#L101. That means the server will default the ResourceVersion if the received object has an empty one, so the update will be valid. Hence, removing the client-side checks will change the behavior of some typed clients (e.g, client for namespace), they will no longer report an validation error for empty ResourdeVersion, which IMO is the correct behavior. Please let me know if you agree @kubernetes/goog-csi

**Comment by lavalamp** [comment]
I tend to agree that we should do such checks in the server.

**Comment by nikhiljindal** [comment]
Agreed that we can remove this from the client.
Thanks @caesarxuchao for finding this.
