### ISSUE TITLE
Error scheduling: No suitable offers for pod/task

### ISSUE THREAD

**Issue by mysterytree** [kubernetes/kubernetes#19325]
![image](https://cloud.githubusercontent.com/assets/6166794/12138743/3433a39a-b496-11e5-906b-d308869d202f.png)
![image](https://cloud.githubusercontent.com/assets/6166794/12138749/3c45edcc-b496-11e5-8b30-c2226975582a.png)

**Comment by mysterytree** [comment]
kube-dns-v9-ns0xe can't start

**Comment by k82cn** [comment]
@jdef , this's a really old issue with little logs. I'd suggest to close it first.

@mysterytree , if the issue is still there, please feel free to re-open it.

**Comment by jdef** [comment]
agreed
