### ISSUE TITLE
routecontroller tries to create routes with empty CIDR

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#19322]
Probably a race when trying to create a route for a node where the CIDR not yet assigned.  We should check for empty-string

```
E0106 05:32:55.787526       8 routecontroller.go:91] Could not create route ef26a98e-b436-11e5-b51a-0aa66b0667bf : error creating AWS route (): InvalidParameterValue: Value () for parameter destinationCidrBlock is invalid. This is not a valid CIDR block.
        status code: 400, request id:
E0106 05:32:55.788166       8 routecontroller.go:91] Could not create route edf6dc61-b436-11e5-b51a-0aa66b0667bf : error creating AWS route (): InvalidParameterValue: Value () for parameter destinationCidrBlock is invalid. This is not a valid CIDR block.
        status code: 400, request id:
```

**Comment by davidopp** [comment]
@justinsb I noticed you added v1.2 milestone. Do you think you can fix this in the next few days?

**Comment by davidopp** [comment]
Moving to v1.2, keeping at P2, to indicate "nice to have" for v1.2 but not blocker.

**Comment by justinsb** [comment]
Actually I don't know that this is AWS specific.  I think CreateRoute is being passed an empty string for route.DestinationCIDR.  That so me seems like an issue in the route controller (?)

Going to untag from AWS and move out of 1.2
