### ISSUE TITLE
reduce kubelet overhead

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#19341]
**Stack configuration:**
fedora 23 
k8's tip-of-master ee006e767ff1d435c525c4c11547e06d364e7621
etcd 2.2.1 
docker 1.9.1 
go 1.5.2

**experiment:**
1. mock local-up-cluster.sh to allow --max-pods="100" and start local cluster
2. create a simple replication controller 100 wide that starts gcr.io/google_containers/pause:2.0 container with no resource limits specified. 
3. during flux + steady state measure kubelet memory using smap data: https://raw.githubusercontent.com/pixelb/ps_mem/master/ps_mem.py, and watch cpu consumption with 'perf top' 

**observed (steady state):**
```
$ sudo ./ps_mem.py -p 17978
 Private  +   Shared  =  RAM used	Program
 93.9 MiB +   1.2 MiB =  95.1 MiB	docker

$ sudo ./ps_mem.py -p 18313
 Private  +   Shared  =  RAM used	Program
552.5 MiB + 259.5 KiB = 552.8 MiB	kubelet
```
cpu spikes occur for >2 cores on the kubelet as well. 

/cc @kubernetes/sig-node @kubernetes/sig-scalability

**Comment by yujuhong** [comment]
I wasn't able to reproduce this on my setup. I'm not sure where the discrepancy came from. 

**Setup**
 - A regular e2e cluster (Debian) in GCE 
 - docker 1.8.3
 - master branch 66d3cbf8898ed5c077be6a8df79b18d458d40c11 + #17700 
 - 110 pods on the node
    * 100 single container pods (`gcr.io/google_containers/pause:2.0`)
    * 10 cluster add-on pods on the node

Measured after all pods are running and ready.

```console
$ sudo ./ps_mem.py -p $(pidof kubelet)
 Private  +   Shared  =  RAM used	Program
120.0 MiB + 100.0 KiB = 120.1 MiB	kubelet

$ sudo ./ps_mem.py -p $(pidof docker)
 Private  +   Shared  =  RAM used	Program
120.9 MiB +   6.0 MiB = 126.9 MiB	docker
```

I'll measure again using just HEAD, but I don't think the memory consumption should change much.

> cpu spikes occur for >2 cores on the kubelet as well.

The cpu burst should be mitigated by this pending PR #17700, which adds a cache to cope with periodical syncing of pods. If we can get a reasonable usage number, we can start considering setting cpu limit for kubelet and docker.

**Comment by timothysc** [comment]
That is very odd that we have such a large difference, what version of golang are you running?

**Comment by ncdc** [comment]
@timothysc can you downgrade to the latest docker 1.8.x rpm and see if that makes a difference?

**Comment by ncdc** [comment]
@timothysc never mind, I was misreading which component it was

**Comment by dchen1107** [comment]
cc/ @jeder

**Comment by yujuhong** [comment]
> That is very odd that we have such a large difference, what version of golang are you running?

`go version go1.5.1 linux/amd64`

**Comment by timothysc** [comment]
I have greater usage on an idle kubelet, and we saw way worse #s on openshift.  

$ sudo ./ps_mem.py -p 2597
Private  +   Shared  =  RAM used	Program
159.6 MiB + 237.5 KiB = 159.8 MiB

**Comment by feiskyer** [comment]
I have greater usage on idle kubelet too

```sh
$ go version
go version go1.4.2 linux/amd64

$ python ps_mem.py -p $(pidof kubelet)
 Private  +   Shared  =  RAM used	Program

312.4 MiB + 110.0 KiB = 312.5 MiB	kubelet
---------------------------------
                        312.5 MiB
=================================
```

**Comment by AdoHe** [comment]
@feiskyer what you mean idle kubelet? no pod on this node?

**Comment by feiskyer** [comment]
@AdoHe y, no pod at all.

**Comment by AdoHe** [comment]
I used `hach/local-up-cluster.sh` to build the cluster and test usage of idle kubelet:
```
[tony@localhost ~]$ sudo python ps_mem.py -p $(pidof kubelet)
 Private  +   Shared  =  RAM used       Program

 34.4 MiB +  41.0 KiB =  34.5 MiB       kubelet
---------------------------------
                         34.5 MiB
=================================
[tony@localhost ~]$ go version
go version go1.5.1 linux/amd64
```
It seems the usage is not great.

**Comment by dchen1107** [comment]
@timothysc or @feiskyer can both of you run "docker info" and copy & paste the output here? I suspect the configuration of node (aufs vs. devicemapper, systemd node vs none-systemd, etc.) causes the differences of memory usage of idle kubelets here. 

@feiskyer how long your kubelet is running? I want to rule out of the potential memory leakage issue here. Can you post the result of memory profiling if possible here?

**Comment by timothysc** [comment]
@dchen1107 - https://paste.fedoraproject.org/308193/45217699/

**Comment by dchen1107** [comment]
@timothysc You mentioned above that your stat is collected from an idle kubelet, but I noticed that from pasted output: 

$ sudo docker info
Containers: 100

Are you running containers through docker daemon directly? If you do, that explains some of the greater usage here. Kubelet links with cAdvisor, which collects stats from all running containers (I mean all cgroups). 

Also are you running containerized Kubelet? And what's your cmdline?

**Comment by timothysc** [comment]
So I re-ran the whole experiment on the same machine cleaning everything and starting from ab6edd8170522fa775fb5054d1c54b4e0d791444

Cleaning Docker :  
``` 
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
# docker info 
Containers: 0
```

re-running experiment from idle:  

```
sudo ./ps_mem.py -p 8955
 Private  +   Shared  =  RAM used	Program
 60.6 MiB + 186.5 KiB =  60.7 MiB	kubelet
```

idle looks better after... Now loading up the machine: 
``` 
$ kubectl get pods | grep unning | wc -l 
100
$ sudo docker ps | grep pause | wc -l 
200
$ sudo docker info
Containers: 206  
Images: 2  ...
$ sudo ./ps_mem.py -p 8955
 Private  +   Shared  =  RAM used	Program
422.0 MiB + 212.0 KiB = 422.2 MiB	kubelet
// ^ NOTE: This value slowly attenuates to a high end ~500 when left alone
```

**Comment by dchen1107** [comment]
@timothysc I am in the plane, cannot verify it now. But based on your latest message, looks like we leak some PODInfra containers without cleanup, which results resource waste obviously. If that is true, it is a bug. 

Meanwhile, we can do some analysis on our management overhead per pod / container. The overhead is quite high here.

**Comment by yujuhong** [comment]
> @timothysc I am in the plane, cannot verify it now. But based on your latest message, looks like we leak some PODInfra containers without cleanup, which results resource waste obviously. If that is true, it is a bug.

I don't think there is a pod infra container leakage....they are just dead (exited) containers waiting to be garbage collected. They should not consume that much resource.


If the memory usage difference is caused by the configuration of the node, most of the extra overhead should come from cadvisor. @feiskyer, could you also run `docker info` and paste the output? Thanks.

**Comment by yujuhong** [comment]
> // ^ NOTE: This value slowly attenuates to a high end ~500 when left alone

This is alarming.

@timothysc would you mind getting the heap profile of kubelet?
`go tool pprof -inuse_space <kubelet_binary_path> http://localhost:8001/api/v1/proxy/nodes/<node_name>/debug/pprof/heap`

You can also check if it's leaking goroutines.
`http://localhost:8001/api/v1/proxy/nodes/<node_name>/debug/pprof/`

**Comment by dchen1107** [comment]
@yujuhong The infra container leakage I brought up is related to cAdvisor. Even those containers are dead, but cAdvisor might still collect disk related stats for those dead containers.

**Comment by timstclair** [comment]
As an aside, I think https://github.com/kubernetes/kubernetes/pull/19374 should reduce the cAdvisor usage by a little under 10x. I'll work on getting some hard numbers to back this claim up.

**Comment by yujuhong** [comment]
> As an aside, I think #19374 should reduce the cAdvisor usage by a little under 10x. I'll work on getting some hard numbers to back this claim up.

Too bad that would't help with the memory usage though

**Comment by timstclair** [comment]
I was referring to the memory usage, sorry I didn't make that clear. cAdvisor stores 2 minutes of historical collection data, which is 120 data points at the current collection rate of 1 second. With the 10 second interval, that will be decreased ot 12 points.

**Comment by yujuhong** [comment]
> I was referring to the memory usage, sorry I didn't make that clear. cAdvisor stores 2 minutes of historical collection data, which is 120 data points at the current collection rate of 1 second. With the 10 second interval, that will be decreased ot 12 points.

Ah...I see. 

@timothysc, it might worth checking the memory usage when setting a longer housekeeping interval `--housekeeping-interval=10`. Given that your usage numbers are much higher, maybe the impact would be more obvious.

**Comment by feiskyer** [comment]
@dchen1107 @yujuhong  I have running this kubelet with hyper runtime for more than a month. I just watched the output of `ps_mem.py` for a while. It's not stable indeed, varies from 30M-300M. Have you seen the same phenomenon?

**Comment by yujuhong** [comment]
@feiskyer, how many pods were you running on the node? I'll measure overnight to see if it fluctuates.

**Comment by yujuhong** [comment]
Also, it could fluctuate because of go GC, but the range you mentioned seems a bit extreme.

**Comment by feiskyer** [comment]
@yujuhong Only one pod on this node.

**Comment by jimmidyson** [comment]
cadvisor watches cgroups creation/deletion so if cgroups are only cleaned up on container delete (kubelet GC) then that could explain the leakage: GC is only triggered when hitting thresholds IIRC. I will try to validate docker behaviour today & how cadvisor behaves.

**Comment by AdoHe** [comment]
@jimmidyson so any pod deletion will not clean up cgroups as kubelet just call container stop?

**Comment by jimmidyson** [comment]
@AdoHe Correct: pod deletion does just call container stop. The kubelet periodically performs garbage collection (cleaning up of dead containers & unused images) but only when certain thresholds are reached. These are configurable but I'll defer to someone who knows this a little better than me to define what settings are possible & what their defaults are.

**Comment by jimmidyson** [comment]
Docker stop does clean up cgroups so the leak shouldn't be there in cadvisor - see https://gist.github.com/jimmidyson/1bf5fc07d7bd2251fb95 for cgroup creation/deletion via inotify on container start/stop.

**Comment by timothysc** [comment]
@yujuhong

odd thing is heap is not that much... 
https://paste.fedoraproject.org/308702/45227300/

**Comment by vishh** [comment]
FYI: Docker will clean up cgroups and namespaces as soon as the init process of a container exits. So cAdvisor will not be monitoring dead containers.

**Comment by yujuhong** [comment]
For the sake of comparison, below is the numbers for 110 pods on a node:


```console
 $ sudo docker ps | wc -l
226
```

*638	goroutines*
110 pod workers (1 per pod)
```
110 @ 0x42f053 0x42f114 0x405a81 0x40516b 0x7e5225 0x7f07f9 0x460471
#	0x7e5225	k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop+0x95		/snp/goland/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:107
#	0x7f07f9	k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1+0x59	/snp/goland/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:158
```
229 goroutines for tracking container stats in cadvisor (~1 per container)
```
229 @ 0x42f053 0x42f114 0x44a0d9 0xee3dab 0x460471
#	0x44a0d9	time.Sleep+0xf9								/usr/local/go/src/runtime/time.go:59
#	0xee3dab	github.com/google/cadvisor/manager.(*containerData).housekeeping+0x7db	/snp/kubernetes/kubernetes/Godeps/_workspace/src/github.com/google/cadvisor/manager/container.go:423
```
225 goroutines for tracking filesystem usage in cadvisor (~1 per container)
```
225 @ 0x42f053 0x43da74 0x43cfd2 0x1340a12 0x460471
#	0x1340a12	github.com/google/cadvisor/container/docker.(*realFsHandler).trackUsage+0x482	/snp/kubernetes/kubernetes/Godeps/_workspace/src/github.com/google/cadvisor/container/docker/fsHandler.go:82
```

@timothysc, how many pods/containers were running on this node?

**Comment by timothysc** [comment]
@yujuhong 100 pods/200containers 

This is about as full fidelity as I can make it: https://paste.fedoraproject.org/308727/27751014/

**Comment by yujuhong** [comment]
@vishh any idea of why cadvisor may use more goroutines on @timothysc's node for the same number of containers?

**Comment by vishh** [comment]
@yujuhong: I can't think of anything obvious off the top of my head. Pprof should have the data you need right?

**Comment by timstclair** [comment]
@timothysc do you have liveness/readiness probes on your containers?

**Comment by timothysc** [comment]
@timstclair no.

**Comment by timothysc** [comment]
I think I'm going to start pointing the finger at cadvisor at this this point.  I'll setup a separate experiment, but most of the heap, and 80+% of the goroutines are started there.

**Comment by AdoHe** [comment]
Guess a Standalone cAdvisor is better. #18770

**Comment by timothysc** [comment]
So I hacked the kubelet to: 

runtime.GOMAXPROCS(1)
const statsCacheDuration = 30 * time.Second
const maxHousekeepingInterval = 10 * time.Second

and adjusted memory usage by more then half, or ~= that of docker 

```
$ sudo ./ps_mem.py -p 2785
 Private  +   Shared  =  RAM used	Program
217.1 MiB +   1.4 MiB = 218.4 MiB	docker
$ sudo ./ps_mem.py -p 4880
214.6 MiB + 196.5 KiB = 214.7 MiB	kubelet
```

It definitely slows down the fill of the machine, so I'm onto cpu-load now.  

```
/debug/pprof/
profiles:
0	block
993	goroutine
2089	heap
15	threadcreate
```

Still seems odd that we spawn so many go-routines per pod.

**Comment by vishh** [comment]
Were you able to parse the goroutines and see what kinds of goroutines we
spawn?

**Comment by yujuhong** [comment]
@timothysc, I think we still need to understand why cadvisor spawns more goroutine for your cluster than mine, suppose we both use the default parameters.

**Comment by timothysc** [comment]
@yujuhong Yup, I'm digging into that part now.

**Comment by timothysc** [comment]
I'll submit a PR on this one to expose the tuning knobs on cadvisor, which is relatively minor and open a new issue on leaking goroutines, which I have a 100% repro across 2 platforms.

**Comment by timothysc** [comment]
I think we can close this now in lieu of 

#https://github.com/kubernetes/kubernetes/pull/19850 & https://github.com/kubernetes/kubernetes/issues/19633
