### ISSUE TITLE
kubelet not running in /kubelet

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#19346]
`/sys/fs/cgroup/cpuacct/kubelet` shows no increase of cpu usage. Jenkins builds also show that the resource monitoring test has been measuring 0 cpu usage for /kubelet as far back as 12/31/2015. The builds before that are no longer available.  

I confirmed the regression in my local cluster, which showed that kubelet is running in /system.

Bisecting using my local cluster, the offending PR seems to be #17883, which bumped cadvisor and migrated from docker/libcontainer to opencontainers/runc/libcontainer).

/cc @kubernetes/goog-node, @jimmidyson

**Comment by jimmidyson** [comment]
Just checked with a build from master & seems to be running in `/kubelet`:

````
$ ps -o cgroup $(pidof kubelet)

CGROUP
10:cpuset:/kubelet,9:blkio:/kubelet,8:perf_event:/kubelet,7:freezer:/kubelet,6:cpu,cpuacct:/kubelet,5:devices:/kubelet,4:memory:/kubelet,3:hugetlb:/kubelet,2:net_cls,net_prio:/kubelet,1:name=systemd:/user.slice/user-1000.slice/session-1.scope
````

**Comment by dchen1107** [comment]
Is docker daemon running under cgroup /docker-daemon?

**Comment by yujuhong** [comment]
On a  regular e2e cluster on GCE:
```console
$ ps -o cgroup $(pidof kubelet)
CGROUP
10:net_prio:/system,9:perf_event:/system,8:blkio:/system,7:net_cls:/system,6:freezer:/system,5:devices:/system,4:memory:/system,3:cpuacct:/system,2:cpu:/system,1:cpuset:/system

$ ps -o cgroup $(pidof docker)
CGROUP
10:net_prio:/docker-daemon,9:perf_event:/docker-daemon,8:blkio:/docker-daemon,7:net_cls:/docker-daemon,6:freezer:/docker-daemon,5:devices:/docker-daemon,4:memory:/docker-daemon,3:cpuacct:/docker-daemon,2:cpu:/docker-daemon,1:cpuset:/docker-daemon
```

**Comment by jimmidyson** [comment]
@dchen1107 Not sure if you're asking me or @yujuhong but on my system:

```
$ ps -o cgroup $(pidof docker)

CGROUP
10:cpuset:/docker-daemon,9:blkio:/system.slice,8:perf_event:/docker-daemon,7:freezer:/docker-daemon,6:cpu,cpuacct
```

I'm running with `hack/local-up-cluster.sh` - not sure if that's equivalent to what runs on GCE as part of e2e? If not please tell me how to reproduce.

**Comment by jimmidyson** [comment]
@yujuhong Can you share full kubelet cmd line run please?

**Comment by yujuhong** [comment]
@jimmidyson, do you mean this?
```
root      7127     1 15 21:08 ?        00:02:51 /usr/local/bin/kubelet --api-servers=https://e2e-test-username-master --enable-debugging-handlers=true --cloud-provider=gce --config=/etc/kubernetes/manifests --allow-privileged=True --v=4 --cluster-dns=10.0.0.10 --cluster-domain=cluster.local --configure-cbr0=true --cgroup-root=/ --system-container=/system --max-pods=110 --serialize-image-pulls=false
```

**Comment by jimmidyson** [comment]
Does that run containerized for GCE e2e?

**Comment by dchen1107** [comment]
@jimmidyson I were asking @yujuhong because if #17883 is the culprit, it should cause docker daemon process being move to a wrong cgroup too.

**Comment by yujuhong** [comment]
> Does that run containerized for GCE e2e?

No, it does not.

**Comment by jimmidyson** [comment]
Can you check the kubelet logs for either:

    Failed to move Kubelet to container

or

    Running in container

**Comment by yujuhong** [comment]
@jimmidyson I didn't see any error message that stood out. Below are the select lines from the log.

```
I0106 21:08:13.870433    5829 manager.go:128] cAdvisor running in container: "/system"
I0106 21:08:13.895433    5829 server.go:850] Started kubelet
I0106 21:08:13.906617    5829 kubelet.go:903] Running in container "/kubelet"
```

**Comment by jimmidyson** [comment]
Can you share the output of `grep cgroup /proc/self/mountinfo`on a node please? Just want to check that the cgroup mount points look sane.

**Comment by yujuhong** [comment]
From :4194/validate

```
cAdvisor version: 

OS version: Debian GNU/Linux 7 (wheezy)

Kernel version: [Supported and recommended]
	Kernel version is 3.16.0-0.bpo.4-amd64. Versions >= 2.6 are supported. 3.0+ are recommended.


Cgroup setup: [Supported and recommended]
	Available cgroups: map[cpu:1 cpuacct:1 memory:1 freezer:1 blkio:1 net_prio:1 cpuset:1 devices:1 net_cls:1 perf_event:1]
	Following cgroups are required: [cpu cpuacct]
	Following other cgroups are recommended: [memory blkio cpuset devices freezer]
	Hierarchical memory accounting enabled. Reported memory usage includes memory used by child containers.


Cgroup mount setup: [Supported and recommended]
	Cgroups are mounted at /sys/fs/cgroup.
	Cgroup mount directories: blkio cpu cpuacct cpuset devices freezer memory net_cls net_prio perf_event 
	Any cgroup mount point that is detectible and accessible is supported. /sys/fs/cgroup is recommended as a standard location.
	Cgroup mounts:
	cgroup /sys/fs/cgroup/cpuset cgroup rw,relatime,cpuset 0 0
	cgroup /sys/fs/cgroup/cpu cgroup rw,relatime,cpu 0 0
	cgroup /sys/fs/cgroup/cpuacct cgroup rw,relatime,cpuacct 0 0
	cgroup /sys/fs/cgroup/memory cgroup rw,relatime,memory 0 0
	cgroup /sys/fs/cgroup/devices cgroup rw,relatime,devices 0 0
	cgroup /sys/fs/cgroup/freezer cgroup rw,relatime,freezer 0 0
	cgroup /sys/fs/cgroup/net_cls cgroup rw,relatime,net_cls 0 0
	cgroup /sys/fs/cgroup/blkio cgroup rw,relatime,blkio 0 0
	cgroup /sys/fs/cgroup/perf_event cgroup rw,relatime,perf_event 0 0
	cgroup /sys/fs/cgroup/net_prio cgroup rw,relatime,net_prio 0 0


Docker version: [Supported and recommended]
	Docker version is 1.8.3. Versions >= 1.0 are supported. 1.2+ are recommended.


Docker driver setup: [Supported and recommended]
	Docker exec driver is native-0.2. Storage driver is aufs.
	Cgroups are being created through cgroup filesystem.
	Docker container state directory is at "/var/lib/docker/containers" and is accessible.


Block device setup: [Supported and recommended]
	At least one device supports 'cfq' I/O scheduler. Some disk stats can be reported.
	 Disk "sda" Scheduler type "cfq".
```

**Comment by jimmidyson** [comment]
Looks good, but could you also share the raw cgroup mount info so I can check format, etc?

**Comment by yujuhong** [comment]
```
23 14 0:19 / /sys/fs/cgroup rw,relatime - tmpfs cgroup rw,mode=755
24 23 0:20 / /sys/fs/cgroup/cpuset rw,relatime - cgroup cgroup rw,cpuset
25 23 0:21 / /sys/fs/cgroup/cpu rw,relatime - cgroup cgroup rw,cpu
26 23 0:22 / /sys/fs/cgroup/cpuacct rw,relatime - cgroup cgroup rw,cpuacct
27 23 0:23 / /sys/fs/cgroup/memory rw,relatime - cgroup cgroup rw,memory
28 23 0:24 / /sys/fs/cgroup/devices rw,relatime - cgroup cgroup rw,devices
29 23 0:25 / /sys/fs/cgroup/freezer rw,relatime - cgroup cgroup rw,freezer
30 23 0:26 / /sys/fs/cgroup/net_cls rw,relatime - cgroup cgroup rw,net_cls
31 23 0:27 / /sys/fs/cgroup/blkio rw,relatime - cgroup cgroup rw,blkio
32 23 0:28 / /sys/fs/cgroup/perf_event rw,relatime - cgroup cgroup rw,perf_event
33 23 0:29 / /sys/fs/cgroup/net_prio rw,relatime - cgroup cgroup rw,net_prio
```

**Comment by jimmidyson** [comment]
That all looks totally fine.

I wonder if there's some race between running kubelet in `/kubelet` & moving all non-kernel pids to `/system`.

Can you share the full kubelet log? Looking for something like `Moving non-kernel threads`.

**Comment by jimmidyson** [comment]
And see if the kubelet pid is in the list of moved pids.

**Comment by yujuhong** [comment]
The beginning (the interesting part) of the kubelet.log: https://gist.github.com/yujuhong/446e5b0fc45e8713fec8

@jimmidyson, yes, kubelet's pid 7127 was in the list of pids to move. I think your theory is right. If this is a race condition, it happens quite frequently though (the few jenkin builds I sampled all had this problem). Can this still be related to #17883, or do you think I just happened to run into this race with your PR?

**Comment by jimmidyson** [comment]
Investigating more it's just plain bad logic rather than a race I think...

Yeah I think it's related to #17883, although I'm surprised it didn't happen before. Just trying to work through the change & see what the impact was.

**Comment by jimmidyson** [comment]
OK got a fix - prevent moving pids in kubelet cgroup to system cgroup, if specified. PR coming.

**Comment by AdoHe** [comment]
@jimmidyson so the root cause is #17883?

**Comment by jimmidyson** [comment]
@AdoHe It seems to be, but the logic didn't change much & I would have expected this to happen before #17883 too. It could be the logic changed in the runc cgroups implementation getting pids in root cgroup.

**Comment by AdoHe** [comment]
@jimmidyson I tested the latest code on my laptop, the output of `ps -o cgroup $(pidof kubelet)` is just ok. So how to reproduce this issue?

**Comment by jimmidyson** [comment]
@AdoHe Hopefully you can't reproduce it after this fix :) The way to reproduce it with the previous version is to run the kubelet specifying:

    --resource-container=/kubelet --cgroup-root=/

**Comment by AdoHe** [comment]
@jimmidyson I will try this. Thanks very much.

**Comment by AdoHe** [comment]
@jimmidyson I did try to reproduce this issue on my laptop as you said, but the result of `ps -o cgroup $(pidof kubelet)` is still ok, kubelet is in the `/kubelet` cgroup, besides I am using the latest code.

**Comment by jimmidyson** [comment]
Can you share the git revision you built from & the  command you ran to start the kubelet?

I can reproduce this with master every time using the flags I specified above.

**Comment by AdoHe** [comment]
@jimmidyson 
```
[tony@localhost kubernetes]$ cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.5.682+b1e4831265f821-dirty", GitCommit:"b1e4831265f8219d7bfed350245e3e304490043b", GitTreeState:"dirty"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.5.682+b1e4831265f821-dirty", GitCommit:"b1e4831265f8219d7bfed350245e3e304490043b", GitTreeState:"dirty"}

[tony@localhost kubernetes]$ ps -o cgroup $(pidof kubelet)
CGROUP
10:hugetlb:/kubelet,9:devices:/kubelet,8:perf_event:/kubelet,7:blkio:/kubelet,6:cpuacct,cpu:/kubelet,5:net_cls:/kubelet,4:freezer:/kubelet,3:memory:/k...

[tony@localhost kubernetes]$ ps -ef | grep kubelet
/home/tony/Documents/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/kubelet --v=3 --chaos-chance=0.0 --container-runtime=docker --rkt-path= --rkt-stage1-image= --hostname-override=127.0.0.1 --address=127.0.0.1 --api-servers=127.0.0.1:8080 --resource-container=/kubelet --cgroup-root=/ --cpu-cfs-quota=false --cluster-dns=127.0.0.1 --port=10250
```
