### ISSUE TITLE
aws guide issue, coreos multinode cluster

### ISSUE THREAD

**Issue by bitsofinfo** [kubernetes/kubernetes#19345]
Followed this guide on AWS. 

https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/coreos/coreos_multinode_cluster.md

Nothing is available on the master @ 80/443 /ui

When I shell into the boxes (master or nodes I get)

```
CoreOS alpha (835.9.0)
Update Strategy: No Reboots
Failed Units: 1
  setup-network-environment.service
```

**Comment by jlowdermilk** [comment]
cc @pires

**Comment by pires** [comment]
AFAIK, the CoreOS documentation is now maintained by the CoreOS people.

**Comment by davidopp** [comment]
@robszumski @aaronlevy @bcwaldon any thoughts?

**Comment by robszumski** [comment]
The guides that we (CoreOS) are maintaining are under this heading https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos.md#official-coreos-guides.

I'm not sure that the UI add on is installed by default with that guide, however. Can you start this pod via kubectl, @bitsofinfo?

**Comment by justinsb** [comment]
I believe the guide is unmaintained: https://github.com/kubernetes/kubernetes.github.io/issues/1688

**Comment by justinsb** [comment]
Can't assign to @robszumski so reassigning ownership to @philips instead.

**Comment by robszumski** [comment]
@justinsb Correct, CoreOS does not maintain this guide. I think we can delete it.

**Comment by justinsb** [comment]
Proposed removal in #1689

**Comment by justinsb** [comment]
The PR to remove the obsolete guide merged.

**Comment by philips** [comment]
Right so this can be closed. I guess @davidopp can you close this?
