### ISSUE TITLE
Bare Metal CoreOS with Kubernetes (OFFLINE) Document Formatting

### ISSUE THREAD

**Issue by danehans** [kubernetes/kubernetes#19348]
Code block formatting is munged throughout this guide:

http://kubernetes.io/v1.1/docs/getting-started-guides/coreos/bare_metal_offline.html

For example:
1. Copy over the syslinux images we will need.
   
   ```
   su -
   mkdir -p /tftpboot
   cd /tftpboot
   cp /usr/share/syslinux/pxelinux.0 /tftpboot
   cp /usr/share/syslinux/menu.c32 /tftpboot
   cp /usr/share/syslinux/memdisk /tftpboot
   cp /usr/share/syslinux/mboot.c32 /tftpboot
   cp /usr/share/syslinux/chain.c32 /tftpboot
   
   /sbin/service dhcpd start
   /sbin/service xinetd start
   /sbin/chkconfig tftp on
   ```

Appears as:

Download the CoreOS PXE files provided by the CoreOS team.

MY_TFTPROOT_DIR=/tftpboot mkdir -p $MY_TFTPROOT_DIR/images/coreos/ cd $MY_TFTPROOT_DIR/images/coreos/ wget http://stable.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz wget http://stable.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz.sig wget http://stable.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.gz wget http://stable.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.gz.sig gpg --verify coreos_production_pxe.vmlinuz.sig gpg --verify coreos_production_pxe_image.cpio.gz.sig

This makes it difficult to follow the web version of the guide.

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
Looks like already fixed here: https://kubernetes.io/docs/getting-started-guides/coreos/bare_metal_offline/ 

/close
