### ISSUE TITLE
Proposal: move ConfigMap to core API, call it v1 in kube v1.2

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#19358]
We've already beta-tested ConfigMap - it was called Secret.  The objects are almost identical.  Having ConfigMap in the core API and fully GA makes it vastly more useful in the near term - there are many things that want to build on it.

Objections?

@bgrant0607 @pmorie @tmrts

**Comment by bgrant0607** [comment]
Discussed with both you and @pmorie earlier today. I agree, provided we can get it done by 1.2.

**Comment by bgrant0607** [comment]
cc @mikedanese

**Comment by ncdc** [comment]
:+1:

**Comment by davidopp** [comment]
@pmorie does this need to stay open as a separate issue?
