### ISSUE TITLE
one pod can not ping to other minion pod 

### ISSUE THREAD

**Issue by robcherish** [kubernetes/kubernetes#19397]
I used https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md to deploy a kubernetes cluster on three ubuntu machines.
and I used the latest git repo with 
$ export KUBE_VERSION=1.1.2
$ export FLANNEL_VERSION=0.5.5
$ export ETCD_VERSION=2.2.1
and I can lunch k8s successfully and use command 'kubectl get nodes'
NAME            LABELS                                 STATUS    AGE
10.65.**.**   kubernetes.io/hostname=10.65.**.**   Ready     22h
10.65.**.**   kubernetes.io/hostname=10.65.**.**   Ready     22h
10.65.**.**   kubernetes.io/hostname=10.65.**.**   Ready     22h

I cannot ping to pod which is on other minion.could u please help me?

some infomation about k8s : 

master-node:
kube-proxy.log:

E0106 23:09:04.419006    3078 server.go:357] Not trying iptables proxy: can't get Node "10.65.215.161": Get http://10.65.215.161:8080/api/v1/nodes/10.65.215.161: dial tcp 10.65.215.161:8080: connection refused
E0106 23:09:04.463807    3078 proxier.go:193] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
E0106 23:09:04.464976    3078 proxier.go:197] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
E0106 23:09:04.466307    3078 event.go:197] Unable to write event: 'Post http://10.65.215.161:8080/api/v1/namespaces/default/events: dial tcp 10.65.215.161:8080: connection refused' (may retry after sleeping)

cat flanneld.log

I0106 23:09:04.379531 03060 main.go:275] Installing signal handlers
I0106 23:09:04.384830 03060 main.go:188] Using 10.65.215.161 as external interface
I0106 23:09:04.384962 03060 main.go:189] Using 10.65.215.161 as external endpoint
E0106 23:09:04.391324 03060 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [1]
E0106 23:09:05.392121 03060 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [10]
E0106 23:09:06.393038 03060 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [18]
E0106 23:09:07.393928 03060 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [18]
I0106 23:09:08.420484 03060 etcd.go:204] Picking subnet in range 172.16.1.0 ... 172.16.255.0
I0106 23:09:08.421633 03060 etcd.go:84] Subnet lease acquired: 172.16.46.0/24
I0106 23:09:08.423730 03060 ipmasq.go:50] Adding iptables rule: FLANNEL -d 172.16.0.0/16 -j ACCEPT
I0106 23:09:08.427599 03060 ipmasq.go:50] Adding iptables rule: FLANNEL ! -d 224.0.0.0/4 -j MASQUERADE
I0106 23:09:08.434754 03060 ipmasq.go:50] Adding iptables rule: POSTROUTING -s 172.16.0.0/16 -j FLANNEL
I0106 23:09:08.438175 03060 ipmasq.go:50] Adding iptables rule: POSTROUTING ! -s 172.16.0.0/16 -d 172.16.0.0/16 -j MASQUERADE
I0106 23:09:08.441506 03060 vxlan.go:153] Watching for L3 misses
I0106 23:09:08.441570 03060 vxlan.go:159] Watching for new subnet leases
I0106 23:09:08.442549 03060 vxlan.go:273] Handling initial subnet events
I0106 23:09:08.442598 03060 device.go:159] calling GetL2List() dev.link.Index: 4
I0106 23:09:29.681126 03060 vxlan.go:232] Subnet added: 172.16.86.0/24
I0106 23:09:29.681227 03060 device.go:164] calling NeighAdd: 10.65.215.163, 36:4b:98:26:b2:db
I0106 23:09:48.949160 03060 vxlan.go:232] Subnet added: 172.16.83.0/24
I0106 23:09:48.949222 03060 device.go:164] calling NeighAdd: 10.65.215.164, 42:87:e5:8a:4a:fc
I0106 23:26:09.088937 03060 vxlan.go:345] L3 miss: 172.16.83.2
I0106 23:26:09.089019 03060 device.go:187] calling NeighSet: 172.16.83.2, 42:87:e5:8a:4a:fc
I0106 23:26:09.089226 03060 vxlan.go:356] AddL3 succeeded
I0106 23:26:39.852684 03060 vxlan.go:340] Ignoring not a miss: 42:87:e5:8a:4a:fc, 172.16.83.2
I0106 23:26:48.347283 03060 vxlan.go:345] L3 miss: 172.16.83.2
I0106 23:26:48.347374 03060 device.go:187] calling NeighSet: 172.16.83.2, 42:87:e5:8a:4a:fc
I0106 23:26:48.347514 03060 vxlan.go:356] AddL3 succeeded
I0106 23:27:19.020730 03060 vxlan.go:340] Ignoring not a miss: 42:87:e5:8a:4a:fc, 172.16.83.2
I0106 23:27:28.394390 03060 vxlan.go:345] L3 miss: 172.16.83.2
I0106 23:27:28.394470 03060 device.go:187] calling NeighSet: 172.16.83.2, 42:87:e5:8a:4a:fc
I0106 23:27:28.394592 03060 vxlan.go:356] AddL3 succeeded
I0106 23:27:59.084776 03060 vxlan.go:340] Ignoring not a miss: 42:87:e5:8a:4a:fc, 172.16.83.2
I0106 23:28:08.441671 03060 vxlan.go:345] L3 miss: 172.16.83.2
I0106 23:28:08.441766 03060 device.go:187] calling NeighSet: 172.16.83.2, 42:87:e5:8a:4a:fc
I0106 23:28:08.441962 03060 vxlan.go:356] AddL3 succeeded
I0106 23:28:39.148761 03060 vxlan.go:340] Ignoring not a miss: 42:87:e5:8a:4a:fc, 172.16.83.2
I0106 23:57:45.285165 03060 vxlan.go:345] L3 miss: 172.16.86.2
I0106 23:57:45.285247 03060 device.go:187] calling NeighSet: 172.16.86.2, 36:4b:98:26:b2:db
I0106 23:57:45.285443 03060 vxlan.go:356] AddL3 succeeded
I0106 23:58:02.220762 03060 vxlan.go:340] Ignoring not a miss: 36:4b:98:26:b2:db, 172.16.86.2
I0106 23:58:15.689707 03060 vxlan.go:345] L3 miss: 172.16.86.2
I0106 23:58:15.689854 03060 device.go:187] calling NeighSet: 172.16.86.2, 36:4b:98:26:b2:db
I0106 23:58:15.689963 03060 vxlan.go:356] AddL3 succeeded
I0106 23:58:32.620740 03060 vxlan.go:340] Ignoring not a miss: 36:4b:98:26:b2:db, 172.16.86.2
I0106 23:58:41.850183 03060 vxlan.go:345] L3 miss: 172.16.86.2
I0106 23:58:41.850249 03060 device.go:187] calling NeighSet: 172.16.86.2, 36:4b:98:26:b2:db
I0106 23:58:41.850402 03060 vxlan.go:356] AddL3 succeeded
I0106 23:59:08.908758 03060 vxlan.go:340] Ignoring not a miss: 36:4b:98:26:b2:db, 172.16.86.2
I0107 00:04:12.805193 03060 vxlan.go:345] L3 miss: 172.16.86.2
I0107 00:04:12.805271 03060 device.go:187] calling NeighSet: 172.16.86.2, 36:4b:98:26:b2:db
I0107 00:04:12.805428 03060 vxlan.go:356] AddL3 succeeded
I0107 00:04:42.220621 03060 vxlan.go:340] Ignoring not a miss: 36:4b:98:26:b2:db, 172.16.86.2
I0107 00:05:51.423719 03060 vxlan.go:345] L3 miss: 172.16.86.2
I0107 00:05:51.423785 03060 device.go:187] calling NeighSet: 172.16.86.2, 36:4b:98:26:b2:db
I0107 00:05:51.423947 03060 vxlan.go:356] AddL3 succeeded
I0107 00:06:20.908634 03060 vxlan.go:340] Ignoring not a miss: 36:4b:98:26:b2:db, 172.16.86.2
I0107 00:09:48.510234 03060 vxlan.go:345] L3 miss: 172.16.86.2
I0107 00:09:48.510316 03060 device.go:187] calling NeighSet: 172.16.86.2, 36:4b:98:26:b2:db
I0107 00:09:48.510544 03060 vxlan.go:356] AddL3 succeeded
I0107 00:10:25.388716 03060 vxlan.go:340] Ignoring not a miss: 36:4b:98:26:b2:db, 172.16.86.2
I0107 00:12:39.925179 03060 vxlan.go:345] L3 miss: 172.16.86.2
I0107 00:12:39.925263 03060 device.go:187] calling NeighSet: 172.16.86.2, 36:4b:98:26:b2:db
I0107 00:12:39.925453 03060 vxlan.go:356] AddL3 succeeded
I0107 00:13:16.780795 03060 vxlan.go:340] Ignoring not a miss: 36:4b:98:26:b2:db, 172.16.86.2
I0107 00:14:30.268375 03060 vxlan.go:345] L3 miss: 172.16.83.2
I0107 00:14:30.268452 03060 device.go:187] calling NeighSet: 172.16.83.2, 42:87:e5:8a:4a:fc
I0107 00:14:30.268664 03060 vxlan.go:356] AddL3 succeeded
I0107 00:15:02.256884 03060 vxlan.go:345] L3 miss: 172.16.86.2
I0107 00:15:02.256962 03060 device.go:187] calling NeighSet: 172.16.86.2, 36:4b:98:26:b2:db
I0107 00:15:02.257095 03060 vxlan.go:356] AddL3 succeeded
I0107 00:15:07.628652 03060 vxlan.go:340] Ignoring not a miss: 42:87:e5:8a:4a:fc, 172.16.83.2
I0107 00:15:39.628639 03060 vxlan.go:340] Ignoring not a miss: 36:4b:98:26:b2:db, 172.16.86.2
I0107 00:29:45.990330 03060 vxlan.go:345] L3 miss: 172.16.46.2
I0107 00:29:45.990401 03060 vxlan.go:349] Route for 172.16.46.2 not found
I0107 00:29:46.992679 03060 vxlan.go:345] L3 miss: 172.16.46.2
I0107 00:29:46.992757 03060 vxlan.go:349] Route for 172.16.46.2 not found
...
I0107 01:20:10.491716 03060 device.go:187] calling NeighSet: 172.16.83.2, 42:87:e5:8a:4a:fc
I0107 01:20:10.491986 03060 vxlan.go:356] AddL3 succeeded
I0107 01:20:44.652755 03060 vxlan.go:340] Ignoring not a miss: 42:87:e5:8a:4a:fc, 172.16.83.2
I0107 01:26:53.780924 03060 vxlan.go:345] L3 miss: 172.16.86.2
I0107 01:26:53.781011 03060 device.go:187] calling NeighSet: 172.16.86.2, 36:4b:98:26:b2:db
I0107 01:26:53.781249 03060 vxlan.go:356] AddL3 succeeded
I0107 01:27:27.212747 03060 vxlan.go:340] Ignoring not a miss: 36:4b:98:26:b2:db, 172.16.86.2
I0107 01:38:10.613641 03060 vxlan.go:345] L3 miss: 172.16.86.2
I0107 01:38:10.613797 03060 device.go:187] calling NeighSet: 172.16.86.2, 36:4b:98:26:b2:db
I0107 01:38:10.613978 03060 vxlan.go:356] AddL3 succeeded
I0107 01:38:53.420797 03060 vxlan.go:340] Ignoring not a miss: 36:4b:98:26:b2:db, 172.16.86.2
I0107 22:09:08.423678 03060 renew.go:41] Lease renewed, new expiration: 2016-01-09 05:09:08.422485506 +0000 UTC
I0107 22:09:29.681649 03060 vxlan.go:232] Subnet added: 172.16.86.0/24
I0107 22:09:29.681769 03060 device.go:164] calling NeighAdd: 10.65.215.163, 36:4b:98:26:b2:db
I0107 22:09:48.956624 03060 vxlan.go:232] Subnet added: 172.16.83.0/24
I0107 22:09:48.956690 03060 device.go:164] calling NeighAdd: 10.65.215.164, 42:87:e5:8a:4a:fc

cat /run/flannel/subnet.env
FLANNEL_NETWORK=172.16.0.0/16
FLANNEL_SUBNET=172.16.46.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true

minion1-node:
kube-proxy.log:
E0106 23:09:29.692245    2354 server.go:357] Not trying iptables proxy: can't get Node "10.65.215.163": node "10.65.215.163" not found
E0106 23:09:29.728024    2354 proxier.go:193] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
E0106 23:09:29.729448    2354 proxier.go:197] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
E0107 04:53:48.895607    2354 proxysocket.go:165] I/O error: write tcp 172.16.86.2:56749: broken pipe
E0107 04:53:48.895639    2354 proxysocket.go:165] I/O error: write tcp 172.16.86.2:57231: broken pipe
E0107 06:23:51.897812    2354 proxysocket.go:165] I/O error: write tcp 172.16.86.2:58203: broken pipe
E0107 08:23:55.900770    2354 proxysocket.go:165] I/O error: write tcp 172.16.86.2:60146: broken pipe
E0107 08:53:56.902378    2354 proxysocket.go:165] I/O error: write tcp 172.16.86.2:32886: broken pipe
E0107 09:23:57.903508    2354 proxysocket.go:165] I/O error: write tcp 172.16.86.2:32882: broken pipe
E0107 09:53:58.904522    2354 proxysocket.go:165] I/O error: write tcp 172.16.86.2:33368: broken pipe
E0107 20:24:19.921192    2354 proxysocket.go:165] I/O error: write tcp 172.16.86.2:43548: broken pipe
E0107 21:54:22.923812    2354 proxysocket.go:165] I/O error: write tcp 172.16.86.2:45001: broken pipe

 cat flanneld.log
I0106 23:09:29.655391 02348 main.go:275] Installing signal handlers
I0106 23:09:29.656261 02348 main.go:188] Using 10.65.215.163 as external interface
I0106 23:09:29.656299 02348 main.go:189] Using 10.65.215.163 as external endpoint
I0106 23:09:29.679819 02348 etcd.go:204] Picking subnet in range 172.16.1.0 ... 172.16.255.0
I0106 23:09:29.680935 02348 etcd.go:84] Subnet lease acquired: 172.16.86.0/24
I0106 23:09:29.682784 02348 ipmasq.go:50] Adding iptables rule: FLANNEL -d 172.16.0.0/16 -j ACCEPT
I0106 23:09:29.688864 02348 ipmasq.go:50] Adding iptables rule: FLANNEL ! -d 224.0.0.0/4 -j MASQUERADE
I0106 23:09:30.694216 02348 ipmasq.go:50] Adding iptables rule: POSTROUTING -s 172.16.0.0/16 -j FLANNEL
I0106 23:09:30.697982 02348 ipmasq.go:50] Adding iptables rule: POSTROUTING ! -s 172.16.0.0/16 -d 172.16.0.0/16 -j MASQUERADE
I0106 23:09:30.701503 02348 vxlan.go:153] Watching for L3 misses
I0106 23:09:30.701590 02348 vxlan.go:159] Watching for new subnet leases
I0106 23:09:30.703291 02348 vxlan.go:273] Handling initial subnet events
I0106 23:09:30.703360 02348 device.go:159] calling GetL2List() dev.link.Index: 4
I0106 23:09:30.703453 02348 device.go:164] calling NeighAdd: 10.65.215.161, c6:4a:0f:4a:36:4c
I0106 23:09:48.949443 02348 vxlan.go:232] Subnet added: 172.16.83.0/24
I0106 23:09:48.949488 02348 device.go:164] calling NeighAdd: 10.65.215.164, 42:87:e5:8a:4a:fc
I0107 22:09:08.426517 02348 vxlan.go:232] Subnet added: 172.16.46.0/24
I0107 22:09:08.426679 02348 device.go:164] calling NeighAdd: 10.65.215.161, c6:4a:0f:4a:36:4c
I0107 22:09:29.684158 02348 renew.go:41] Lease renewed, new expiration: 2016-01-09 05:09:29.680679414 +0000 UTC
I0107 22:09:48.959079 02348 vxlan.go:232] Subnet added: 172.16.83.0/24
I0107 22:09:48.959157 02348 device.go:164] calling NeighAdd: 10.65.215.164, 42:87:e5:8a:4a:fc

cat /run/flannel/subnet.env
FLANNEL_NETWORK=172.16.0.0/16
FLANNEL_SUBNET=172.16.86.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true

minion2-node:
kube-proxy.log

E0106 23:09:48.946656    2354 server.go:357] Not trying iptables proxy: can't get Node "10.65.215.164": node "10.65.215.164" not found
E0106 23:09:49.000983    2354 proxier.go:193] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
E0106 23:09:49.002673    2354 proxier.go:197] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-SERVICES':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

cat /var/log/upstart/flanneld.log
I0106 23:09:48.911223 02350 main.go:275] Installing signal handlers
I0106 23:09:48.911660 02350 main.go:188] Using 10.65.215.164 as external interfa
I0106 23:09:48.911705 02350 main.go:189] Using 10.65.215.164 as external endpoin
I0106 23:09:48.947549 02350 etcd.go:204] Picking subnet in range 172.16.1.0 ...
I0106 23:09:48.949045 02350 etcd.go:84] Subnet lease acquired: 172.16.83.0/24
I0106 23:09:48.950378 02350 ipmasq.go:50] Adding iptables rule: FLANNEL -d 172.1
I0106 23:09:48.954172 02350 ipmasq.go:50] Adding iptables rule: FLANNEL ! -d 224
I0106 23:09:48.958445 02350 ipmasq.go:50] Adding iptables rule: POSTROUTING -s 1
I0106 23:09:49.963014 02350 ipmasq.go:50] Adding iptables rule: POSTROUTING ! -s
I0106 23:09:49.967765 02350 vxlan.go:153] Watching for L3 misses
I0106 23:09:49.967867 02350 vxlan.go:159] Watching for new subnet leases
I0106 23:09:49.969677 02350 vxlan.go:273] Handling initial subnet events
I0106 23:09:49.969741 02350 device.go:159] calling GetL2List() dev.link.Index: 4
I0106 23:09:49.969858 02350 device.go:164] calling NeighAdd: 10.65.215.161, c6:4
I0106 23:09:49.969963 02350 device.go:164] calling NeighAdd: 10.65.215.163, 36:4

subnet.env:
FLANNEL_NETWORK=172.16.0.0/16
FLANNEL_SUBNET=172.16.83.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true

thanks for your kind.

**Comment by bgrant0607-nocc** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.1/)
  * [the troubleshooting guide](http://kubernetes.io/v1.1/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
