### ISSUE TITLE
kube-apiserver not starting for debian 8 with systemd

### ISSUE THREAD

**Issue by imkin** [kubernetes/kubernetes#19401]
after salt installed all the packages found that api-server control-manager and scheduler did not come up.

Saw the following logs in syslog.

I0107 18:56:58.932311   18723 server.go:806] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"kubernetes-master", UID:"kubernetes-master", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'MissingClusterDNS' kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. pod: "etcd-server-kubernetes-master_kube-system(89bcb3ce2e0d539d8532f98175510b71)". Falling back to DNSDefault policy.
E0107 18:56:59.185348   18723 manager.go:1815] Failed to create pod infra container: API error (500): Cannot start container 1ae6995b428f073eaaf38714e9f38f41fae296a6a196e6777bd1bc914f7f7268: [8] System error: Unit name /-1ae6995b428f073eaaf38714e9f38f41fae296a6a196e6777bd1bc914f7f7268.scope is not valid.
; Skipping pod "kube-controller-manager-kubernetes-master_kube-system(09c1cb5ffc657b84eb07d6e45e858857)"
I0107 18:56:59.185383   18723 kubelet.go:3100] Generating status for "kube-controller-manager-kubernetes-master_kube-system(09c1cb5ffc657b84eb07d6e45e858857)"
E0107 18:56:59.190589   18723 manager.go:1815] Failed to create pod infra container: API error (500): Cannot start container fd732d78a5d5d71470e51fe256367927fdef5569ad9b97751e55017451502151: [8] System error: Unit name /-fd732d78a5d5d71470e51fe256367927fdef5569ad9b97751e55017451502151.scope is not valid.
; Skipping pod "kube-scheduler-kubernetes-master_kube-system(1adf7c18fbee682958919fe20e8eb985)"
I0107 18:56:59.190621   18723 kubelet.go:3100] Generating status for "kube-scheduler-kubernetes-master_kube-system(1adf7c18fbee682958919fe20e8eb985)"
E0107 18:56:59.195742   18723 manager.go:1815] Failed to create pod infra container: API error (500): Cannot start container daf03cb8cd8a7249ff5e3e80b40edb389ca706df9c59f67087a018c210705c40: [8] System error: Unit name /-daf03cb8cd8a7249ff5e3e80b40edb389ca706df9c59f67087a018c210705c40.scope is not valid.
; Skipping pod "kube-apiserver-kubernetes-master_kube-system(3226c793a2dbb05c3aa888cb56c1b69d)"
I0107 18:56:59.195773   18723 kubelet.go:3100] Generating status for "kube-apiserver-kubernetes-master_kube-system(3226c793a2dbb05c3aa888cb56c1b69d)"
E0107 18:56:59.223737   18723 manager.go:1815] Failed to create pod infra container: API error (500): Cannot start container 90c6e93e6eb6436898024eccb8be0279364180b05d6efb07b985ebfbd03af539: [8] System error: Unit name /-90c6e93e6eb6436898024eccb8be0279364180b05d6efb07b985ebfbd03af539.scope is not valid.
; Skipping pod "etcd-server-kubernetes-master_kube-system(89bcb3ce2e0d539d8532f98175510b71)"

Ran the kubelet manually on the master again and saw the following. 
http://pastebin.com/ryydSHMt

The deployment was done after building from source from master branch.
OS: Debian 8.x with systemd
Install from Src
docker 1.9.1

**Comment by vishh** [comment]
Most likely, this is an issue with `--cgroup-parent` feature support in docker on systemd systems. 
cc @derekwaynecarr

**Comment by justinsb** [comment]
Are you using kube-up?

On AWS, I worked around `/-90c6e93e6eb6436898024eccb8be0279364180b05d6efb07b985ebfbd03af539.scope is not valid.`  by setting `--cgroup-root=docker`

**Comment by derekwaynecarr** [comment]
There was a bug using `--cgroup-parent` in docker on `systemd`.

It was fixed here:
https://github.com/docker/docker/pull/18612

The `cgroup-root` flag on the `kubelet` ultimately just delegates to that argument.

**Comment by imkin** [comment]
@justinsb 

Thanks this workaround worked thanks.

@derekwaynecarr thanks. @justinb' workaround helps.

**Comment by imkin** [comment]
Once I use the workaround suggested by @justinsb I also need https://github.com/kubernetes/kubernetes/pull/19354
to resolve the issue.

**Comment by vishh** [comment]
Closing this issue, since it is tracked elsewhere.
