### ISSUE TITLE
BufferQueueLimitError in the fluentd container of the master

### ISSUE THREAD

**Issue by ernestoalejo** [kubernetes/kubernetes#19405]
I have a cluster in GCE. `Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.3"`. I have enabled logging to GCP. Updated from a previous 1.1 version in November.

Yesterday the fluentd container of the master started emitting these errors twice per second approximately:
```
[warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="fluent.warn"
[warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="fluent.warn"
[warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="kubelet"
[warn]: suppressed same stacktrace
```

It kept that way until I manually restarted the Docker container today. It didn't send any logs to the console in the meantime.

Some logged errors had more details:
```
[error]: failed to emit fluentd's log event tag="fluent.warn" event={"error_class"=>"Fluent::BufferQueueLimitError", "error"=>"queue size exceeds limit", "tag"=>"kubelet", "message"=>"emit transaction failed: error_class=Fluent::BufferQueueLimitError error=\"queue size exceeds limit\" tag=\"kubelet\""} error_class=Fluent::BufferQueueLimitError error=#<Fluent::BufferQueueLimitError: queue size exceeds limit>
```

Tags are always `kubelet`, `kube-apiserver` or `fluent.warn` in all errors I have seen.

There were some `Faraday::Timeout` and `Faraday::SSLError` some hours before, but no other sign of malfunction. I have the minions fluentd pods in a permanent `Terminating` status which expired in November, but the containers are still alive and working and I think it has been solved in this other issue: https://github.com/kubernetes/kubernetes/issues/17929

If the real cause of this error can't be found at least the fluentd container of the master should be prepared to restart itself if it cannot work correctly anymore.

**Comment by heim** [comment]
I am also seing this in GKE. Tried to restart the pod, but no luck.

**Comment by ernestoalejo** [comment]
@heim Restarting the docker container of the master worked for me:
1) SSH into the master machine: `gcloud compute ssh XXX`
2) `docker ps` to see the list of containers.
3) `docker restart XXXX` to restart the one named fluentd.

At least I can keep reading the cluster logs again until this bug gets fixed or the container knows when to restart itself. Otherwise the cluster has magic silent periods where you don't receive logs (though they can be read with `kubectl logs`) and you don't have almost any clue where the error is coming from.

**Comment by robtuley** [comment]
Same deal for me, and can confirm @ernestoalejo restart works -- I was a bit more brutal and simply did a `docker kill XXXX` and let the process watcher restart the fluentd container itself but afterwards started seeing logs coming through again.

**Comment by heim** [comment]
@robtuley I fixed this by scaling up the cluster and killing the "old" nodes one by one. It's a bit of a hack but it goes a little something like this:
1. Resize cluster to cluster-size+1.
2. Wait until new node is up.
3. Kill one of the old nodes
4. Be really quick and scale cluster to original size
5. Repeat for each node in cluster.

Kind of a hack, but it worked for us.

**Comment by johanhaleby** [comment]
We're also experiencing this problem on GKE.

**Comment by robtuley** [comment]
@heim suggested rolling restart earlier in this thread across the gke cluster has resolved the problem for me so far (5 days). Thanks by the way!

**Comment by vishh** [comment]
cc @jimmidyson

**Comment by jimmidyson** [comment]
I'm not sure of the fluentd version or configuration on gke - can someone link to it please? Also are you sending events to gcm or elasticsearch?

Fluentd buffer plugins have an internal queue to batch up & send events to outputs. That queue is flushed regularly, normally based on queue size or time elapsed or a combination of the two, depending on output plugin implementation. If there is a problem communicating with the output destination (e.g. elasticsearch, gcm, etc) then the output plugin should retry regularly. During this time any new events are put on to the internal queue. If the queue size exceeds the configured limit, you get this error. The queue size limit is configurable, but in order to preserve memory for running real apps needs to be configured appropriately.

**Comment by ernestoalejo** [comment]
I use GCM. I see some sporadic errors like these (the only one that day):
```
2016-01-04 00:39:43 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-04 00:37:37 +0000 error_class="Faraday::TimeoutError" error="Connection timed out - connect(2) for \"169.254.169.254\" port 80" plugin_id="object:10c8b1c"
```

The next day I have:

```
2016-01-06 05:22:12.000 2016-01-06 04:22:12 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-06 04:21:13 +0000 error_class="Faraday::TimeoutError" error="Net::ReadTimeout" plugin_id="object:1981164"
2016-01-06 05:22:12.000 2016-01-06 04:22:12 +0000 [warn]: suppressed same stacktrace
2016-01-06 05:22:12.000 2016-01-06 04:22:12 +0000 [warn]: retry succeeded. plugin_id="object:1981164"
2016-01-06 06:38:26 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-06 06:37:27 +0000 error_class="Faraday::TimeoutError" error="Net::ReadTimeout" plugin_id="object:11adeb0"

[.... (stack trace of ruby + "retry succeeded") x several times ...]

2016-01-07 14:25:48.000 2016-01-07 13:25:48 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:304:in `pop'
2016-01-07 14:25:48.000 2016-01-07 13:25:48 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:321:in `try_flush' 2016-01-07 14:25:48.000 2016-01-07 13:25:48 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:140:in `run'
2016-01-07 14:27:20.000 2016-01-07 13:27:20 +0000 [warn]: retry succeeded. plugin_id="object:b9c7d8"
2016-01-07 19:55:45.000 2016-01-07 18:55:45 +0000 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="fluent.warn"
2016-01-07 18:55:45 +0000 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="kubelet"
```

From that timestamp until now I have the BufferQueueLimitError in kubelet and fluentd (it actively logs it right now in my GCE cluster). This time the logs of my applications are not affected; so I have not restarted the master container yet.

It's ok to have a size limit; but I think it should discard logs or something when it occurs and keep working afterwards instead of failing indefinitely.

**Comment by vishh** [comment]
cc @a-robinson

**Comment by a-robinson** [comment]
What zones were your folks' clusters running in when you hit this? It's possible that transient network problems caused a backlog in the agent and then some sort of bug in fluentd caused it to fail to recover after its buffer queue filled, but I'd hope for a better explanation than that.

Hitting the buffer queue size limit is just a symptom of an underlying problem sending the logs to cloud logging, so the real questions are why the queue filled up and why it never dropped back down.

@jimmidyson - the config is *very* similar to the config for fluentd-es, and can be found [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd.conf)

cc @mr-salty @repeatedly for thoughts on this fluentd buffer queue behavior

**Comment by ernestoalejo** [comment]
I won't restart the container by the moment if it doesn't affect my pods; so if any other debug info is needed I can get into the container to obtain it.

For the record I count 10 timeouts the 6 January and a `Faraday::SSLError` 5 hours before the first error the 7 January. There were some `Google::APIClient::ServerError` or timeouts daily (1 or 2 / day) before. All of them have `retry succeeded. plugin_id="object:XXX"` after the traceback with the same id of the original failed send.

**Comment by ernestoalejo** [comment]
I have SSH'ed into the failing container (this time is one of the minions). I have read `/etc/google-fluentd/google-fluentd.conf` and I have seen a reference to "kubelet":

```
<source>
  type tail
  format none
  path /var/log/kubelet.log
  pos_file /var/log/gcp-kubelet.log.pos
  tag kubelet
</source>
```

That file (`/var/log/kubelet.log`) is full of successful calls:

```
I0122 01:06:00.233718    2566 server.go:1082] GET /stats/default/taskqueue-rabbitmq-q3riz/90250241-c0a3-11e5-b651-42010af00002/taskqueue-rabbitmq: (7.427494ms) 0 [[Go 1.1 package http] 10.244.1.5:57639]
```

but also failing ones (3/4 errors per second):
```
I0122 01:06:12.291162    2566 server.go:1082] GET /healthz: (1.326108ms) 0 [[curl/7.26.0] 127.0.0.1:55136]
I0122 01:06:12.450894    2566 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/6639ad34709fbeac155f6fdf8fa59cc0327d0b7e3f47a3ee089d423082692596 with output du: cannot access `/var/lib/docker/aufs/diff/6639ad34709fbeac155f6fdf8fa59cc0327d0b7e3f47a3ee089d423082692596': No such file or directory
 - exit status 1
I0122 01:06:12.451977    2566 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/bb51dbbdd964ab458990e9bc8939fe8148ebe24dc60247e99ab47995954bbc01 with output du: cannot access `/var/lib/docker/aufs/diff/bb51dbbdd964ab458990e9bc8939fe8148ebe24dc60247e99ab47995954bbc01': No such file or directory
 - exit status 1
```

Logrotate is working correctly on the node (outside the container):
```
-rw-r--r-- 1 root root   6.4M Jan 22 00:17 kubelet.log.1.gz
-rw-r--r-- 1 root root    15M Jan 21 17:17 kubelet.log.2.gz
-rw-r--r-- 1 root root   5.2M Jan 21 00:17 kubelet.log.3.gz
-rw-r--r-- 1 root root    16M Jan 20 18:17 kubelet.log.4.gz
-rw-r--r-- 1 root root   5.1M Jan 20 00:17 kubelet.log.5.gz
```

**Comment by johanhaleby** [comment]
I have two failing nodes on GKE, let me know if there's something I can do to help out.

**Comment by a-robinson** [comment]
@ernestoalejo - are your fluentd instances getting backed up and not exporting logs, or did they just have a couple failures to export logs that succeeded on retry shortly afterwards? Your most recent logs sounds like the latter.

@johanhaleby - A full dump of the logs from the fluentd containers that are blocked would be fantastic. Feel free to email them to me if you don't want to share them publicly for some reason (arob@google.com).

**Comment by ernestoalejo** [comment]
The first error in this issue (in the master) caused all logs to stop getting delivered to the console. This was solved by restarting the master fluentd container manually through SSH. This time the error is in one of the nodes; and only kubelet seems affected.

I had a couple of daily timeouts that were retried successfully before; but since 6 January fluentd is broken. 

The issue is that the fluentd pod of that node is logging hundreds of BufferQueueLimitErrors to the console per minute; and it quietly dropped the logs of all pods in the cluster when the error was in the kubernetes master instance.

Because the errors mentioned `kubelet` and `fluentd.warn` I thought it was related to the kubelet log file (`/var/log/kubelet.log`) and I saw it is filled with "failed to collect filesystem stats" errors, and rotated every few hours because of the size (~0.12 MB per minute added to that file).

**Comment by a-robinson** [comment]
The actual contents of the kubelet log are unrelated. The interesting information is the contents of the fluentd logs, since they should hint at (1) why the build-up is occurring in the first place and (2) why fluentd fails to work through the build-up.

> The issue is that the fluentd pod of that node is logging hundreds of BufferQueueLimitErrors to the console per minute; and it quietly dropped the logs of all pods in the cluster when the error was in the kubernetes master instance.

There are two things here that don't quite make sense to me. Could you help me understand?

1. Are you saying that you're seeing the `BufferQueueLimitError`s show in the Cloud Log Viewer? It'd be very weird if it was able to send those logs along to the Cloud Logging API but not the logs from other pods running in the cluster.

1. So only the master node was having `BufferQueueLimitError` problems, but none of the logs from the other nodes were visible in the Cloud Log Viewer? That would make very little sense, since each Fluentd instance in the cluster is completely independent. Are you sure they weren't also having problems? Or that the logs really weren't accessible via the viewer, even by drilling down in a way that would filter out the BufferQueueLimitError logs from the master?

I'm on kubernetes.slack.com with the username a-robinson if you'd be up for trying to work through this a little faster :)

**Comment by ernestoalejo** [comment]
First time (errors logged on the masters):
1. They showed in Cloud Log Viewer. No other logs from other pods were received. I saw them using `kubectl logs`.
2. I only restarted the master container and it was working again.

Second time (current error):
1. Both errors and other pods logs received.
2. Only one of the nodes failing.

I do not have "@google.com, @redhat.com, @coreos.com or @intel.com" to access the chat; but I'm up for trying whatever you need to debug the issue.

**Comment by a-robinson** [comment]
You can register for our slack channel at http://slack.kubernetes.io/

And again, a dump of the fluentd logs from the node that's having problems is the most useful thing to work off of right now

**Comment by a-robinson** [comment]
Many thanks for the help providing log dumps, @ernestoalejo @johanhaleby! The problem you guys have hit appears to be due to the confluence of a few different issues.

First, our buffer chunks are somewhat small (only 512KB), and only one chunk can be flushed at a time, which with a high enough rate of logs, could cause the buffers to fill up.

Second, we didn't configure fluentd not to pipe its own logs directly back into itself. This meant that once the buffers filled up, the rate of logs would drastically increase from fluentd's own logging.

Finally, there appears to be a problem where fluentd hangs if it gets too backed up. I don't fully understand this part yet, but I'll be filing an issue against Fluentd after patching our config up.

I'll send a PR out to improve the first and second issues.

**Comment by a-robinson** [comment]
And for further improvement in 1.2, @mr-salty and I plan to adopt either buffering to disk instead of memory or the new fluentd feature to block reading from input files while the buffers are full. He's going to figure out whether the blocking one is available to build a release with yet and which will work better for us.

**Comment by ernestoalejo** [comment]
Thank you for the update to this issue and the solution

**Comment by a-robinson** [comment]
If you don't want to wait for 1.1.6 to be available and want to patch your existing nodes to see whether it's enough of an improvement to resolve your specific case, you can edit the `/etc/kubernetes/manifests/fluentd-gcp.yaml` file on the node to change the image from `gcr.io/google_containers/fluentd-gcp:1.14` to `gcr.io/google_containers/fluentd-gcp:1.15`. If you do try this, let me know how it goes! :)

**Comment by a-robinson** [comment]
So I tried to reproduce the hanging bug in the new version of fluentd (0.12.20) and haven't been able to, despite replicating what I had done before. Also on the plus side, 0.12.19 included a new json library that parses JSON logs (which includes all docker logs) 1.5x faster than before, making the buffer queue filling up at all less likely. I'm switching us over to the new version in #22539.

We can still open up a debate about whether to use the new `buffer_queue_full_action` setting that can block input when the buffer fills up, but I'm a little less confident in how stable that's likely to be. I've opened #22537 to cover this.

**Comment by zoidbergwill** [comment]
@a-robinson I bumped fluentd-gcp to 1.15 on all our nodes, and it seems happier so far.

Cluster master version: 1.1.8
Node version: 1.1.2

**Comment by zacharynevin** [comment]
@a-robinson Is there a reason that that the fluentd-gcp logger is not a daemonset? It seems to be set up as individual pods (e.g. I did `kubectl get daemonset --namespace kube-system` and couldn't find the gcloud logger). It would be much easier to update the fluentd-gcp version if this were the case.

**Comment by a-robinson** [comment]
It should be a daemonset soon. For more context, see #23306 and #32088

**Comment by xcompass** [comment]
In my case, I got a few thousands errors like below per second from fluentd container, a few nodes together took down my ES cluster. 
```
2017-09-10 07:39:30 +0000 [error]: Exception emitting record: queue size exceeds limit
2017-09-10 07:39:30 +0000 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitErrorerror="queue size exceeds limit" tag="kubelet"
  2017-09-10 07:39:30 +0000 [warn]: suppressed same stacktrace
```
My k8s was in non-stable status because of the multi master setup. (something related to https://github.com/kubernetes/kubernetes/issues/48865). Even after I reduced my master node to 1, I still got the same error above. The workaround I did is to remove the logs from journald
```
journalctl --vacuum-time=1h
```
Then fluentd is happy again. Not sure what log message causing above error, but it seems related to the errors thrown by kubelet during the non-stable period.

**Comment by crassirostris** [comment]
@xcompass This is expected, this means that fluentd is not able to process all logs it's reading. You can either make it block instead of throwing exceptions or increase the amount of resources/threads dedicated to processing logs so that fluentd never hits the limit

**Comment by lzbgt** [comment]
For who come up with this issue like me, just truncate the docker logs to size 0.
`sudo salt '*' cmd.run 'truncate -s 0 /var/lib/docker/containers/*/*-json.log'`

Reason for this situation in my case is that the elasticsearch ds cluster was down for some days , when the ds comes back online, fluentd pods will be overwhelmed by sending all the the stashed logs.
