### ISSUE TITLE
Better script to bring up Kubernete cluster

### ISSUE THREAD

**Issue by Andyccs** [kubernetes/kubernetes#19408]
If we run the `get-kube.sh` script using the following command and if this if the first time you run this script, then the create_cluster function will fail because the `kubernete` directory does not exist: 

```Shell
$ export KUBERNETES_PROVIDER=aws; export KUBERNETES_SKIP_DOWNLOAD=yes; curl -sS https://get.k8s.io | bash 
```

If you look at the script to bring up Kubernete cluster (https://github.com/kubernetes/kubernetes/blob/master/cluster/get-kube.sh)

```Shell
# Original
if [[ "${KUBERNETES_SKIP_DOWNLOAD-}" ]]; then
  create_cluster
  exit 0
fi
```

I propose the following

```Shell
directory=kubernetes

if [[ "${KUBERNETES_SKIP_DOWNLOAD-}" ]]; then
  if [ -d "${directory}" ]; then
    create_cluster
    exit 0
  else
    echo "The directory ${directory} is not in current directory. Bailing out. "
    exit 5
  fi
fi
```

**Comment by bgrant0607-nocc** [comment]
If you don't want to download, you could just use cluster/kube-up.sh directly.
