### ISSUE TITLE
Suppressing update checks in test infra

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19423]
Per #19394.

You can turn off update checking altogether:

```
$ export CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK=true
$ gcloud ...
```

We should investigate if/how to do this for all of our tests, and perhaps for all invocations of `gcloud`.

**Comment by spxtr** [comment]
Whoop, I probably should've responded to the email. #19370 suppresses this for all Jenkins jobs that call into e2e.sh or build.sh.

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by ixdy** [comment]
pretty sure this one is obsolete.
