### ISSUE TITLE
kubectl delete rc doesn't have good error messages

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/kubernetes#19427]
When a `kubectl delete rc <name>` times out waiting for something, you see `timed out waiting for the condition` in the terminal without explanation of which condition.

Seen at https://github.com/openshift/origin/issues/6568.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by stevekuznetsov** [comment]
@kubernetes/sig-cli-misc

**Comment by stevekuznetsov** [comment]
Guess SIG CLI is not interested?

/close
