### ISSUE TITLE
test-update-storage-objects.sh is flaky

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#19435]
Pasted from #16698 

```
!!! [0108 21:12:42] Timed out waiting for apiserver:  to answer at http://127.0.0.1:8080/healthz; tried 120 waiting 1 between each
!!! Error in ./hack/test-update-storage-objects.sh:48
  'return 1' exited with status 1
Call stack:
  1: ./hack/test-update-storage-objects.sh:48 startApiServer(...)
  2: ./hack/test-update-storage-objects.sh:123 main(...)
Exiting with status 1
+++ [0108 21:12:42] Killing api server
+++ [0108 21:12:42] Clean up complete
```

I've run this repeatedly, and all I can tell so far is that it's flaky.  The specific flakiness is that sometimes (more often than not) after we've run cluster/update-storage-objects.sh the API server will never become healthy.  The timeout is 2m, and even with --v=10, it's clear that the apiserver is not doing anything.  The process is running.

If after the test fails (I've commented out the cleanup code that kills etcd and apiserver), I kill it and manually start it, it seems to come up every time.

**Comment by mml** [comment]
Here's some output from a manual run inside docker with --v=10 and with the cleanup disabled.

```console
I0109 00:49:18.993317    1117 handlers.go:130] PUT /api/v1/namespaces/default/services/kubernetes: (2.064311ms) 200 [[kubectl/v1.2.0 (linux/amd64) kubernetes/c6e9ad0] 127.0.0.1:56483]
All objects updated successfully!!
+++ [0109 00:49:19] Killing api server
+++ [0109 00:49:19] api server exited
+++ [0109 00:49:19] Starting kube-apiserver with KUBE_API_VERSIONS: v1 and runtime-config: api/all=false,api/v1=true
Flag --address has been deprecated, see --insecure-bind-address instead
Flag --public-address-override has been deprecated, see --bind-address instead
Flag --port has been deprecated, see --insecure-port instead
Flag --public-address-override has been deprecated, see --bind-address instead
Flag --kubelet-port has been deprecated, kubelet-port is deprecated and will be removed
I0109 00:49:19.017833    1328 util.go:440] Default route transits interface "eth0"
I0109 00:49:19.017945    1328 util.go:285] Interface eth0 is up
I0109 00:49:19.017990    1328 util.go:330] Interface "eth0" has 2 addresses :[10.0.0.1/16 fe80::42:aff:fe00:1/64].
I0109 00:49:19.018015    1328 util.go:297] Checking addr  10.0.0.1/16.
I0109 00:49:19.018030    1328 util.go:306] IP found 10.0.0.1
I0109 00:49:19.018041    1328 util.go:336] valid IPv4 address for interface "eth0" found as 10.0.0.1.
I0109 00:49:19.018051    1328 util.go:446] Choosing IP 10.0.0.1 
I0109 00:49:19.018066    1328 server.go:377] Will report 10.0.0.1 as public IP address.
I0109 00:49:19.018081    1328 plugins.go:71] No cloud provider specified.
I0109 00:49:19.018226    1328 genericapiserver.go:311] Setting GenericAPIServer service IP to "10.0.0.1" (read-write).
I0109 00:49:19.018245    1328 genericapiserver.go:321] Node port range unspecified. Defaulting to 30000-32767.
[restful] 2016/01/09 00:49:19 log.go:30: [restful/swagger] listing is available at https://10.0.0.1:6443/swaggerapi/
[restful] 2016/01/09 00:49:19 log.go:30: [restful/swagger] https://10.0.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
!!! [0109 00:51:20] Timed out waiting for apiserver:  to answer at http://127.0.0.1:8080/healthz; tried 120 waiting 1 between each
!!! Error in ./hack/test-update-storage-objects.sh:48
  'return 1' exited with status 1
Call stack:
  1: ./hack/test-update-storage-objects.sh:48 startApiServer(...)
  2: ./hack/test-update-storage-objects.sh:127 main(...)
Exiting with status 1
root@23b8d06b0ffc:/go/src/k8s.io/kubernetes# ps auxwwwwwwwwwww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  20232  2000 ?        Ss   00:48   0:00 bash
root        29  0.4  0.0  26340  9864 ?        Sl   00:48   0:00 etcd -data-dir /tmp.k8s/tmp.THwSyqOOA6 --bind-addr 127.0.0.1:4001
root      1328  0.0  0.0  47848 18052 ?        Sl   00:49   0:00 /go/src/k8s.io/kubernetes/_output/dockerized/bin/linux/amd64/kube-apiserver --v=10 --address=127.0.0.1 --public-address-override=127.0.0.1 --port=8080 --etcd-servers=http://127.0.0.1:4001 --public-address-override=127.0.0.1 --kubelet-port=10250 --runtime-config=api/all=false,api/v1=true --cert-dir=/tmp.k8s --service-cluster-ip-range=10.0.0.0/24
root      1714  0.0  0.0  17484  1132 ?        R+   00:52   0:00 ps auxwwwwwwwwwww
root@23b8d06b0ffc:/go/src/k8s.io/kubernetes# /go/src/k8s.io/kubernetes/_output/dockerized/bin/linux/amd64/kube-apiserver --v=10 --address=127.0.0.1 --public-address-override=127.0.0.1 --port=8080 --etcd-servers=http://127.0.0.1:4001 --public-address-override=127.0.0.1 --kubelet-port=10250 --runtime-config=api/all=false,api/v1=true --cert-dir=/tmp.k8s --service-cluster-ip-range=10.0.0.0/24
Flag --address has been deprecated, see --insecure-bind-address instead
Flag --public-address-override has been deprecated, see --bind-address instead
Flag --port has been deprecated, see --insecure-port instead
Flag --public-address-override has been deprecated, see --bind-address instead
Flag --kubelet-port has been deprecated, kubelet-port is deprecated and will be removed
I0109 00:52:35.152436    1715 util.go:440] Default route transits interface "eth0"
I0109 00:52:35.152557    1715 util.go:285] Interface eth0 is up
I0109 00:52:35.152599    1715 util.go:330] Interface "eth0" has 2 addresses :[10.0.0.1/16 fe80::42:aff:fe00:1/64].
I0109 00:52:35.152623    1715 util.go:297] Checking addr  10.0.0.1/16.
I0109 00:52:35.152639    1715 util.go:306] IP found 10.0.0.1
I0109 00:52:35.152650    1715 util.go:336] valid IPv4 address for interface "eth0" found as 10.0.0.1.
I0109 00:52:35.152660    1715 util.go:446] Choosing IP 10.0.0.1 
I0109 00:52:35.152675    1715 server.go:377] Will report 10.0.0.1 as public IP address.
I0109 00:52:35.152690    1715 plugins.go:71] No cloud provider specified.
I0109 00:52:35.152829    1715 genericapiserver.go:311] Setting GenericAPIServer service IP to "10.0.0.1" (read-write).
I0109 00:52:35.152846    1715 genericapiserver.go:321] Node port range unspecified. Defaulting to 30000-32767.
[restful] 2016/01/09 00:52:35 log.go:30: [restful/swagger] listing is available at https://10.0.0.1:6443/swaggerapi/
[restful] 2016/01/09 00:52:35 log.go:30: [restful/swagger] https://10.0.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
I0109 00:52:35.229441    1715 server.go:641] Serving securely on 127.0.0.1:6443
I0109 00:52:35.785302    1715 server.go:653] Using self-signed cert (/tmp.k8s/apiserver.crt, /tmp.k8s/apiserver.key)
I0109 00:52:35.785342    1715 server.go:683] Serving insecurely on 127.0.0.1:8080
^Croot@23b8d06b0ffc:/go/src/k8s.io/kubernetes#
```

**Comment by mml** [comment]
Sadly, inserting `sleep 1` before Step 3 begins seems to work.

**Comment by mml** [comment]
Oh, and before anyone assumes that the problem is that the previous apiserver hasn't exited, that's not the problem.  I've already added the code below to make sure that the apiserver has exited, but I still need the `sleep`.

```diff
 function killApiServer() {
   kube::log::status "Killing api server"
   [[ -n ${APISERVER_PID-} ]] && kill ${APISERVER_PID} 1>&2 2>/dev/null
+
+  wait ${APISERVER_PID} || true
+  kube::log::status "api server exited"
   unset APISERVER_PID
 }
```

**Comment by mml** [comment]
I ran it 100 times on my workstation with 'sleep 1', and it still timed out 1 time.

Without the sleep, it times out almost every time I try.

So this is neither a root cause nor a fix, but it will reduce flakiness for now.

**Comment by lavalamp** [comment]
Looks like this happened again. @mml, any further ideas?

**Comment by mml** [comment]
Gonna dig back in to this today.  @lavalamp do we have logs from the failure?

**Comment by lavalamp** [comment]
@mml Looking at that PR, it should be one of these runs: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/19947/kubernetes-pull-test-unit-integration/

**Comment by mml** [comment]
@lavalamp am I looking at the right files?  I inspected */build-log.txt and none of them contains a failure of test-update-storage-objects.sh.

**Comment by lavalamp** [comment]
@ixdy I can't find the failure logs either. Can you help us? Did you tag
the right issue?

**Comment by ixdy** [comment]
@lavalamp the failing run is in the old sha1-based location for PR logs: https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/1b110bff0b1e8657317234422e48dcc2af8b4e1a/kubernetes-pull-test-unit-integration/10643/

**Comment by mml** [comment]
@ixdy thanks.  Same issue as before.  I'll see if anything's changed trying to repro it on my workstation.

**Comment by mml** [comment]
I built a hacked up version of the test that can do 12 runs in a minute by only building the docker container and go code once.  On 100 runs, I didn't get a failure, so now I'll do 720 (1h).

If the flake rate on my workstation is below 1 per hour of wall clock time, I guess I'll need a different approach.

**Comment by mml** [comment]
Able to reproduce once I took the sleep back out.

With laborious printf debugging I am tracking down exactly where/why the startup fails.  So far I know that when we call `m.NewBootstrapController().Start()` in master.go, we enter Start() but never return from it.

**Comment by mml** [comment]
OK, so when we are running the bootstrap, there's a step where we do some "repair" steps.

https://github.com/kubernetes/kubernetes/blob/master/pkg/master/controller.go#L78

We then try to run `repairClusterIPs`.  Sometimes this hangs right away, but sometimes we get `serviceipallocations "" cannot be updated: the provided resource version does not match` and then retry.  Eventually, we hang inside ListServices(), at this call: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/service/registry.go#L47

At this point the loose coupling and indirection are too much for me to follow and I don't know exactly where within the etcd registry code to continue debugging.  But I do know this call hangs indefinitely and that this seems to be an actual bug in the API server rather than any kind of logic bug in the test.

**Comment by lavalamp** [comment]
Thanks, that's a good find. @thockin @smarterclayton This code is your
baby, right?

It's weird that a call to etcd would just hang. Maybe some setup bug with
the cache? @mml, can you try to get a stack trace? SIGQUIT usually makes go
programs die with a stack trace, if the http debug endpoint isn't up and
running yet.

**Comment by mml** [comment]
The below looks like the thread in question.  I have the full stack trace (all threads) too but I need to slurp it from my workstation over to this laptop.

```
goroutine 1 [semacquire]:
sync.runtime_Syncsemacquire(0xc8202e2ad0)
        /usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8202e2ac0)
        /usr/local/go/src/sync/cond.go:62 +0x9b   
k8s.io/kubernetes/pkg/storage.(*watchCache).WaitUntilFreshAndList(0xc820378180, 0x14, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/storage/watch_cache.go:199 +0x6a
k8s.io/kubernetes/pkg/storage.(*Cacher).List(0xc820360420, 0x7fc45abc4030, 0xc8202d0480, 0x1c4d130, 0xf, 0xc8208baa30, 0x2, 0xc820408380, 0x7fc45abb5cf0, 0xc82049d140, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/storage/cacher.go:315 +0x316
k8s.io/kubernetes/pkg/registry/generic/etcd.(*Etcd).ListPredicate(0xc8203628f0, 0x7fc45abc4070, 0xc8202d0480, 0x7fc45abc4228, 0xc8202d0720, 0xc82049d080, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd.go:192 +0x429
k8s.io/kubernetes/pkg/registry/generic/etcd.(*Etcd).List(0xc8203628f0, 0x7fc45abc4070, 0xc8202d0480, 0xc82049d080, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd.go:174 +0x285
k8s.io/kubernetes/pkg/registry/service.(*storage).ListServices(0xc82033eb70, 0x7fc45abc4070, 0xc8202d0480, 0xc82049d080, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/service/registry.go:50 +0x12e
k8s.io/kubernetes/pkg/registry/service/ipallocator/controller.(*Repair).runOnce(0xc820485aa0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/service/ipallocator/controller/repair.go:108 +0x39a
k8s.io/kubernetes/pkg/registry/service/ipallocator/controller.(*Repair).(k8s.io/kubernetes/pkg/registry/service/ipallocator/controller.runOnce)-fm(0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/service/ipallocator/controller/repair.go:79 +0x2e
k8s.io/kubernetes/pkg/client/unversioned.RetryOnConflict.func1(0xa10b7b, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/conditions.go:68 +0x3e
k8s.io/kubernetes/pkg/util/wait.ExponentialBackoff(0x989680, 0x4014000000000000, 0x3fb999999999999a, 0x4, 0xc82045f330, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x93
k8s.io/kubernetes/pkg/client/unversioned.RetryOnConflict(0x989680, 0x4014000000000000, 0x3fb999999999999a, 0x4, 0xc82045f388, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/conditions.go:67 +0x97
k8s.io/kubernetes/pkg/registry/service/ipallocator/controller.(*Repair).RunOnce(0xc820485aa0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/service/ipallocator/controller/repair.go:79 +0x74
k8s.io/kubernetes/pkg/master.(*Controller).Start(0xc820899e60)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/master/controller.go:86 +0x31a
k8s.io/kubernetes/pkg/master.New(0xc8201e8d80, 0xd)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/master/master.go:161 +0x269
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc8202a0700, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:397 +0x2f4a
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:49 +0x128
```

**Comment by mml** [comment]
By the way, to reproduce on your own

1. Modify test-update-storage-object.sh as below.
2. build/shell.sh
3. hack/test-update-storage-objects.sh

From there you can use ^\ for a stacktrace or ^Z to otherwise inspect things while the processes stay up.

```diff
--- a/hack/test-update-storage-objects.sh
+++ b/hack/test-update-storage-objects.sh
 RUNTIME_CONFIG="api/all=false,api/${KUBE_NEW_API_VERSION}=true"
 
 # This seems to reduce flakiness.
-sleep 1
-startApiServer
+#sleep 1
+startApiServer || (
+  echo sleeping
+  sleep 30000
+)
```

**Comment by smarterclayton** [comment]
Is this on metal?

**Comment by smarterclayton** [comment]
We fixed `serviceipallocations "" cannot be updated: the provided resource version does not match` last week.

**Comment by mml** [comment]
If by metal you mean inside the docker container where the test runs, but that this docker container is on my workstation.  Yeah.

As far as that error message goes, I'm pretty sure I pulled from head this morning, but I can double check.

**Comment by lavalamp** [comment]
At first I thought maybe a startup order problem, but I don't see evidence of that.

**Comment by lavalamp** [comment]
@smarterclayton I think this has your fix, since I see a retry loop in the stack.

**Comment by lavalamp** [comment]
I think this is an off-by-one error. This puts a resource version into the List function, which then blocks with a <, not a <=. It's even worse if we return a resource version +1 like I seem to think we do.

Tagging: @wojtek-t (who is out at the moment)

I think we need to change the wait function it's blocked in. I'm not 100% sure.

We also need to make that timeout, because right now you could tie up resources just by making requests with huge RVs.

**Comment by lavalamp** [comment]
If my theory is right, editing a service object w/ etcdctl (either once or twice depending on whether we still +1, which I haven't checked) should wake apiserver up.

**Comment by mml** [comment]
Indeed, that did it.

**Comment by lavalamp** [comment]
Hm, actually I mentally swapped the operand order, so I think the code is right unless the resource version gets incremented somewhere.

**Comment by mml** [comment]
Huh, a single `etcdctl set /registry/services/specs/default/kubernetes VALUE` did what you predicted.

**Comment by lavalamp** [comment]
Yeah, I can't find any resource version +1, so that is not the problem.

Instead the problem (on second look) is that we take RV from one collection and pass it to the List of another collection. Oops! Since it is a global number, that's why @mml only had to do one modification.

**Comment by lavalamp** [comment]
OK, I think it's not as bad as it could have been, now that I understand it. This is a newish feature.

**Comment by lavalamp** [comment]
I'll make a quick PR anyway.

**Comment by lavalamp** [comment]
My "quick" PR wants to add a timeout to the cache code. I'll finish it on monday.

**Comment by lavalamp** [comment]
OK, #20433 fixes this two different ways.

**Comment by wojtek-t** [comment]
Thanks a lot for debugging and fixing it @mml and @lavalamp !
