### ISSUE TITLE
SEO: v1.1 docs should take precedence over v1.0

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#19444]
If you google e.g. "kuberentes ha" you hit http://kubernetes.io/v1.0/docs/admin/high-availability.html, which itself says that the page is an archived version of 1.1.  It would be better to send users straight to the latest version.

I think if we add canonical link tags pointing to the latest version that would both avoid a penalty for duplicated content and push people to the latest version by default, though I am sure that someone on the Google team has more knowledge here!

Related to #2838

**Comment by bgrant0607** [comment]
Closing in favor of #2838
