### ISSUE TITLE
Bare Metal Service Load Balancer: Error Get http://localhost:1936: dial tcp [::1]:1936: getsockopt: connection refused

### ISSUE THREAD

**Issue by donbeave** [kubernetes/kubernetes#19441]
Trying to run load balancer in my kubernetes cluster, unfortunately I get a error:

```bash
➜  fitseven git:(master) ✗ kubectl logs -f service-loadbalancer-vgm3s
I0109 12:00:05.362975       1 service_loadbalancer.go:550] Creating new loadbalancer: {Name:haproxy ReloadCmd:./haproxy_reload Config:/etc/haproxy/haproxy.cfg Template:template.cfg Algorithm: startSyslog:false lbDefAlgorithm:roundrobin}
E0109 12:00:05.363028       1 service_loadbalancer.go:241] Get : unsupported protocol scheme ""
I0109 12:00:43.833275       1 service_loadbalancer.go:560] Error Get http://localhost:1936: dial tcp [::1]:1936: getsockopt: connection refused
I0109 12:00:43.833770       1 service_loadbalancer.go:560] Error Get http://localhost:1936: dial tcp [::1]:1936: getsockopt: connection refused
I0109 12:00:43.834199       1 service_loadbalancer.go:560] Error Get http://localhost:1936: dial tcp [::1]:1936: getsockopt: connection refused
```

**Comment by bgrant0607-nocc** [comment]
cc @bprashanth

**Comment by bprashanth** [comment]
It's failing to connect to the stats port, which is used in health checking. Can you do the following:
1. Turn off the healthchecks so the pod isn't restarted (just delete it:
https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/rc.yaml#L26)
2. Deploy the rc, and get the external node ip
3. Navigate to nodeip:1936, you should see the haproxy stats page. I'm assuming this doesn't work. 
4. kubectl exec -it service-loadbalancer-pod-name /bin/sh and ps aux | grep haproxy
5. cat /etc/haproxy/haproxy.cfg inside the pod, it should have something like
```
# haproxy stats, required hostport and firewall rules for :1936
listen stats
    bind *:1936
    stats enable
    stats hide-version
    stats realm Haproxy\ Statistics
    stats uri /
```

We can take it from there. 

Also what platform are you running on, are you using any overlay? what version of serviceloadbalancer have you deployed? I just tried this on `gcr.io/google_containers/servicelb:0.2` on gce and wasn't able to reproduce.

**Comment by bprashanth** [comment]
I think this was addressed through a contrib repo bug, please re-open if that's not the case
