### ISSUE TITLE
Kubernetes, Docker Machine and exposing the API and other services.

### ISSUE THREAD

**Issue by lgomez** [kubernetes/kubernetes#19452]
Hi all,

I've been following these instructions to set up a local development environment that mimics a production environment: http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html

I start by creating a docker machine using:
```bash
docker-machine create --driver virtualbox kubetest
```
Get the host info:
```bash
eval "$(docker-machine env kubetest)"
```
I am able to run containers directly by using my local docker client.

Now, I then try this:
```bash
DOCKER_MACHINE_NAME=kubetest

docker stop $(docker ps -a -q) # Stop all running containers
docker rm $(docker ps -a -q) # remove all containers

# Run the following containers based on the instructions at 
# http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html
docker run -d \
  --net=host \
  gcr.io/google_containers/etcd:2.0.12 \
    /usr/local/bin/etcd \
    --addr=127.0.0.1:4001 \
    --bind-addr=0.0.0.0:4001 \
    --data-dir=/var/etcd/data

docker run -d \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/dev:/dev \
    --volume=/var/lib/docker/:/var/lib/docker:ro \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    gcr.io/google_containers/hyperkube:v1.0.1 \
      /hyperkube kubelet \
      --containerized \
      --hostname-override="127.0.0.1" \
      --address="0.0.0.0" \
      --api-servers=http://localhost:8080 \
      --config=/etc/kubernetes/manifests

docker run -d \
  --net=host \
  --privileged \
  gcr.io/google_containers/hyperkube:v1.0.1 \
    /hyperkube proxy \
    --master=http://127.0.0.1:8080 \
    --v=2


docker-machine ssh $DOCKER_MACHINE_NAME -f -N -L "8080:localhost:8080"

until $(kubectl -s http://localhost:8080 cluster-info &> /dev/null); do
    sleep 1
done
```
After a few seconds I do see it running when I try this:
```bash
kubectl -s http://localhost:8080 cluster-info
Kubernetes master is running at http://localhost:8080
```
Or this...
```bash
kubectl -s http://localhost:8080 get nodes
NAME        LABELS                             STATUS    AGE
127.0.0.1   kubernetes.io/hostname=127.0.0.1   Ready     26m
```

I then run these to test that I can get a service working:
```bash
kubectl -s http://localhost:8080 run nginx --image=nginx --port=80
kubectl -s http://localhost:8080 expose rc nginx --port=80
```
And then see it worked...
```bash
kubectl -s http://localhost:8080 get svc nginx
NAME      CLUSTER_IP   EXTERNAL_IP   PORT(S)   SELECTOR    AGE
nginx     10.0.0.3     <none>        80/TCP    run=nginx   9m
```

Now, the whole thing being inside a docker-machine means I should be able to access things through the IP reported by `docker-machine ip kubetest` but when I try to curl that ip, I get:
```bash
curl: (7) Failed to connect to 192.168.99.100 port 80: Connection refused
```
I get the same if I try localhost and 127.0.0.1 and other's I've tried.

### Questions

1. How do I expose the API service through the docker-machine's IP? I thought this would have worked with the steps that I am following.
2. Is there an environment variable I can set so i don't have to set the `-s` flag to every kubectl command I run? Ie: `kubectl -s http://localhost:8080 cluster-info`
3. When I run a service like nginx above, do I need to configure the external IP somehow? I've done that before using service configuration files on GKE but I'm not sure how to do it here and particularly when I'm not using service configuration files (.yml)?

Thank you so much for any help.

**Comment by lgomez** [comment]
Just in case:

##### docker version
```bash
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```
##### docker-machine version
```
docker-machine version 0.5.5, build 02c4254
```
##### kubectl -s http://localhost:8080 version
```
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
```

**Comment by bgrant0607-nocc** [comment]
cc @fgrzadkowski @brendandburns

**Comment by runseb** [comment]
@lgomez Hi, I have integrated the k8s single node docker deployment in https://github.com/skippbox/kmachine you might want to try that out.

**Comment by smparkes** [comment]
This should probably not be an issue. It's more of a question.

To avoid having to use `-s`, use
```bash
kubectl config set-cluster default --server=http://$(docker-machine ip default):8080
kubectl config set-context default --cluster=default
kubectl config use-context default
```
This all just ends up in `$HOME/.kube/config`. I use names that match the docker-machine name.

To access the port via the docker-machine ip, expose the deployment as an external ip, e.g.,
```bash
kubectl expose deployment nginx --port=80 --external-ip=$(docker-machine ip)
```

**Comment by lgomez** [comment]
@smparkes You're right... it's more of a question. I didn't realize that until I read the answers.

@runseb & @smparkes thank you both for your answers. I was confused by how kubectl handles configuration, what contexts are, how to switch between them, etc.
