### ISSUE TITLE
Error executing "make quick-release"

### ISSUE THREAD

**Issue by fgimenez** [kubernetes/kubernetes#19455]
Hi, I'm getting this error [1] when executing `make quick-release` from the tip of master, the problem seems to come from the `github.com/aws/aws-sdk-go` package. I'm executing on  ubuntu (latest xenial) amd64, please let me know if any further info of the environment is needed.

Thanks! :)

[1] http://paste.ubuntu.com/14458516/

**Comment by paralin** [comment]
Happens with `make WHAT=cmd/kubectl` too.

**Comment by bgrant0607-nocc** [comment]
Try `make clean` first.

kubernetes-dev at googlegroups.com would be a good place to ask questions like this.
