### ISSUE TITLE
Separate the e2e_test.go into a separate file which can be referenced and imported.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#19461]
`e2e_test.go` Is useful for any downstream consumers of kube, i.e. openshift.  

**Lets allow its constants and functionality to be easily called by a _test.go function in other projects** 

I proposed we can do this by 
- separating some of the arg/ test runner functionality out into a non _test *.go file.
- e2e_test.go can just be a thin wrapper.

**Comment by jayunit100** [comment]
cc @ixdy

**Comment by ixdy** [comment]
You shouldn't be accessing e2e_test.go directly. You should be calling it through `ginkgo`. What are you trying to do exactly?

**Comment by jayunit100** [comment]
The goal is to enable usage of the E2E tests in different contexts, i.e. publishing a build product which can adds new tests on top of the existing e2e tests, changes commandline options (or adds new options) and so on.

Specifically, we are using this so that in  openshift we can publish a binary e2e test artifact that is similar, but slightly extends, the existing kube e2e's, and can thus be used in a similar context as the regular e2e tests.

Does that make sense?

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc
