### ISSUE TITLE
build failed on alpine linux 3.3

### ISSUE THREAD

**Issue by asdfsx** [kubernetes/kubernetes#19464]
I am trying to build kubernetes on alpine 3.3, and build an docker image.
I create a project to save all script: https://github.com/asdfsx/docker-mesos-k8s
It seems like 

```
docker run -it --rm -v "$PWD"/go:/go -w /go/src/github.com/kubernetes/kubernetes -v "$PWD"/godepbuild:/godepbuild golang:1.5.2-alpine make
```

But when I execute 'make' I got the following problems

```
.....
# github.com/docker/libcontainer/system
Godeps/_workspace/src/github.com/docker/libcontainer/system/sysconfig.go:6:20: fatal error: unistd.h: No such file or directory
compilation terminated.
# github.com/docker/docker/pkg/term
Godeps/_workspace/src/github.com/docker/docker/pkg/term/tc_linux_cgo.go:10:22: fatal error: termios.h: No such file or directory
 // #include <termios.h>
                      ^
compilation terminated.
# github.com/google/cadvisor/utils/cpuload/netlink
Godeps/_workspace/src/github.com/google/cadvisor/utils/cpuload/netlink/defs.go:40:19: fatal error: errno.h: No such file or directory
compilation terminated. 
.......
```

but I can find these files in the system, for example

```
# find / -name "termios.h"
/usr/include/asm/termios.h
/usr/include/linux/termios.h
/usr/include/asm-generic/termios.h
```

Is there anything I should config before compile?

**Comment by djtm** [comment]
+1 trying to build cadvisor.

**Comment by kookster** [comment]
try `apk add linux-headers`?

**Comment by djtm** [comment]
In the case of cadvisor it was not compatible with the c library used inside alpine. Static glibc worked:
https://github.com/google/cadvisor/issues/1227
https://github.com/google/cadvisor/pull/1237

**Comment by djtm** [comment]
This might be fixed: https://github.com/google/cadvisor/pull/1299

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc
