### ISSUE TITLE
Differences in running k8s via docker vs natively in CoreOS (for production cluster)

### ISSUE THREAD

**Issue by Sarke** [kubernetes/kubernetes#19462]
Hi,

It seems the quickest way to get k8s up and running is via docker (http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html). It's my understanding that this creates a Docker inside of Docker situation for the services run by the kubelet container. 

1. Is this the recommended way, or are there drawbacks?

  A far more elaborate way of running it is using the official CoreOS guide (https://coreos.com/kubernetes/docs/latest/getting-started.html), which runs both the kubelet and etcd natively in CoreOS as services, and the rest in Docker/k8s.  Are there any benefits to doing it this way?

2. My other concern is with CoreOS' self-updater, which I like, but it is my understanding that it coordinates the updating with the other ones in the cluster to make sure the updates are staggered.  Does this still function correctly if the etcd container is running in docker/k8s?  Both for the host CoreOS, and the CoreOS container running etcd?

3. Are these two the primary ways of setting up a k8s cluster on a provider like DO?  I.e. I'm not leaving an option out?

4. P.S. Is there a more appropriate forum for these types of questions than github?

Thanks.

**Comment by luxas** [comment]
I guess you may discuss these things on [Slack](kubernetes.slack.com)
To answer your question: `docker` deployment isn't production ready. AFAIU `coreos` is.
There is some bugs with `docker` deployment. One of them: #19069

And a little correction, docker doesn't run in docker. `kubelet` runs in a docker container and controls the main docker daemon via `--volume=/var/run/docker.sock:/var/run/docker.sock`

Hope it helps!

**Comment by bgrant0607-nocc** [comment]
You could also ask on stackoverflow: http://stackoverflow.com/questions/tagged/kubernetes

CoreOS-specific questions need to be directed at CoreOS.

The guide to choosing a cluster configuration is here:
https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides/README.md

**Comment by Sarke** [comment]
@luxas 

> I guess you may discuss these things on Slack

I'm not a member, and I don't have a "@google.com, @redhat.com, @coreos.com or @intel.com" email.

> To answer your question: docker deployment isn't production ready. AFAIU coreos is. There is some bugs with docker deployment. One of them: #19069

> And a little correction, docker doesn't run in docker. kubelet runs in a docker container and controls the main docker daemon via --volume=/var/run/docker.sock:/var/run/docker.sock

Ok, thank you.  That does help.

**Comment by luxas** [comment]
BTW, anyone can join Slack, I don't know why it says that

**Comment by Sarke** [comment]
@luxas 

https://kubernetes.slack.com/signup

How?

**Comment by luxas** [comment]
From https://github.com/kubernetes/kubernetes/blob/master/docs/troubleshooting.md#slack:
https://slack.kubernetes.io is the invitation page.

Sorry, had forgot about the right URL.
