### ISSUE TITLE
api server: patch operation should use patched object to check admission control

### ISSUE THREAD

**Issue by csrwng** [kubernetes/kubernetes#19479]
Currently, patch will check admission control with an empty object and if it passes, then will proceed to update the object with the patch. Admission control plugins don't get a chance to see/validate what is actually going to be updated.

**Comment by csrwng** [comment]
@lavalamp @deads2k

**Comment by liggitt** [comment]
@derekwaynecarr

**Comment by deads2k** [comment]
@smarterclayton @kubernetes/goog-csi @kubernetes/rh-cluster-infra is there a group for API server?

@kubernetes/kube-iam this affects field level authorization.

**Comment by deads2k** [comment]
I think I want to apply the admission chain twice.  Once for patch as-is and once for "update" with the patched object.

**Comment by csrwng** [comment]
Why?

**Comment by csrwng** [comment]
If you check for the patch as is admission control plugins would have to special case objects that are not complete.

**Comment by deads2k** [comment]
> If you check for the patch as is admission control plugins would have to special case objects that are not complete.

Since the patch itself may mutate during the admission process, the "patched"  object created at the beginning of the admission change is not guaranteed to be correct, so it would be incorrect for an admission controller to do any work against the "patched" object.

**Comment by csrwng** [comment]
It may make sense then to have a separate operation (Patch?) for admission control plugins to explicitly check / mutate patches and not special case complete/incomplete objects on update.

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery

**Comment by lavalamp** [comment]
Update is a totally separate kind of operation from create, and IMO needs to have a different admission mechanism. Specifically, I think you need an admission call that passes the old object and the proposed object (patched, if appropriate).

Otherwise, you have no way to forbid certain transitions. Just because the initial and final states are independently valid, it does not necessarily mean that the transition between them is allowed.

**Comment by smarterclayton** [comment]
I had proposed that before and completely agree.  It's fairly involved
today because we'd have to deal with guaranteed update and commit
retries.
