### ISSUE TITLE
Need to expose image ID in downward API.

### ISSUE THREAD

**Issue by sdminonne** [kubernetes/kubernetes#19475]
Our auditing system needs to be aware of the image ID for each container. Use cases: our applications (built on C++) and sometimes the code composed with another code exposes different services. In case of error (for example core dump) we need to infer which specific images is misbehaving.

@thockin @pmorie @lhuard1A

**Comment by thockin** [comment]
I see the value of this, but it's unfortunate that it will not be a simple fieldPath but a whole new `valueFrom`.  We can either do:

```
valueFrom:
  imageID: {}
```

or

```
valueFrom:
  system: ImageID
```

or:

```
value: $(IMAGE_ID)
```

@bgrant0607 @pmorie 

We also need to define what this variable means for non-docker runtimes

@dchen1107 @yujuhong

**Comment by sdminonne** [comment]
@thockin  thanks for the prompt reply.
Waiting for the other feedbacks,

**Comment by pmorie** [comment]
What's the image ID in this context?  The sha of the image?  Value of the container.image field?

**Comment by bgrant0607** [comment]
@thockin Why can't it be fieldpath?

**Comment by thockin** [comment]
I assumed image ID would be the hash, not the name.  Is there maybe a
status field that has the hash?  Can that be available at pod start time?

**Comment by yujuhong** [comment]
> I assumed image ID would be the hash, not the name.  Is there maybe a
> status field that has the hash?  Can that be available at pod start time?

Image ID is part of the [container status](https://github.com/kubernetes/kubernetes/blob/27ca7dc71eff2b3b1abf7374e4e22ee38ed1ca59/pkg/api/types.go#L945)
I don't think the image ID is returned when pulling the image, so we'll have to perform an extra image listing or inspect before starting the pod.

> We also need to define what this variable means for non-docker runtimes

We don't support non-docker images yet. There is a proposal #18308 for supporting different image types.
For `rkt`, the [ACI image spec](https://github.com/appc/spec/blob/master/spec/aci.md#image-id) also defines an image ID. 

It may be besides the point, but docker registry v2 has moved on to using `digest`, which is easier to verify.

**Comment by sdminonne** [comment]
@pmorie for docker it should be the image sha of the image but it could be something else as well. For non docker runtime it could something else.
If it's advertised/published somewhere in the system I would say that we can imagine to have  _k8s image ID_.

**Comment by vishh** [comment]
-1 for exposing any attributes of an image that are not part of our existing API. Exposing Image Name sounds OK.

**Comment by sdminonne** [comment]
I'm OK for Image Name. 
@pmorie @thockin @yujuhong if for you it's OK I'll modify the name of this issue.

**Comment by pmorie** [comment]
@vishh Does that mean, literally expose the image name, or expose a field called `ImageName` and put the sha in it for docker images?

@sdminonne @bgrant0607 @thockin One design thing to iron out about this, what key should we use in the downward API?  As @yujuhong points out, the image ID is already part of the container status.  We have precedent for accessing part of status via the downward API (pod IP), the key for which is `status.podIP`.  The question is what the key should be for this, or should we have a new `ValueFrom` thing which is a container-scoped downward API source (I have considered this idea before for resource limits via downward API).  Say for example:

```yaml
valueFrom:
  containerFieldRef:
    fieldPath: status.imageID
```

**Comment by thockin** [comment]
Having a "root" for containerFieldRef is cute.  However, fieldRef has
really sort of stopped being a field ref.  It's really just a magic name
that is looked up in a table of magic names.  Do we REALLY see that
changing?  If not, maybe we should just start moving to a more abstract
model wherein we define a set of magic names that can be expanded as
$(MAGIC_NAME) or even more explicitly as `valueFrom: { downwardAPI:
MAGIC_NAME }`

I also feel like this is a bit under-designed and under-specified.  Do we
allow a single label to be extracted?  Will we have to add more magic roots
for other lists?

**Comment by pmorie** [comment]
@thockin 

> Having a "root" for containerFieldRef is cute. However, fieldRef has really sort of stopped being a field ref. It's really just a magic name that is looked up in a table of magic names. Do we REALLY see that changing? If not, maybe we should just start moving to a more abstract model wherein we define a set of magic names that can be expanded as $(MAGIC_NAME) or even more explicitly as `valueFrom: { downwardAPI: MAGIC_NAME }`

That's true re: magic name.  We intentionally punted on the problem of making fieldRef use JSON path syntax since we didn't have a JSONPath implementation available at the time.

I think magic names might be more descriptive and less risk-prone that supporting JSONPath, but we need a way to root container references that is portable across updates to a pod template.  I don't want to get the wrong thing if I reference `containers[0]` and then the pod template my pod is created from is changed and `container[0]` no longer points to what I expect it to.

**Comment by thockin** [comment]
`containers[0]` is pretty-obviously a non-starter.  We have "keys" that we
could use to treat things like containers[] as a map (patchMergeKey), but I
don't think our JSONPath impl is that smart.

I dislike ad hoc DSLs, so I think we should either move towards a DSL that
we use consistently in various places (i.e. our variant of JSONPath) or
magic names, whcih are far more restricted.

`$.status.containers[foobar].imageName`

or
`$THIS_CONTAINER_IMAGE_NAME`

or similar...

**Comment by pmorie** [comment]
I hope we can figure out some way to use JSONPath for this, I feel like magic keys are going to worm their way into people's setups and then we will lose all claims of low-coupling.

**Comment by thockin** [comment]
If the magic keys are limited to kube YAML it's fine.  We just don't want
to expose magic env vars INTO containers.  The reason we called it a
fieldRef was because we didn't want to keep track of a table of magic
values and add new ones when people asked and prevent people from using
things we had not thought about yet.  But that is exactly what we have.

**Comment by bgrant0607** [comment]
I'm against MAGIC_NAME. The whole point of using field paths was to use something principled and not completely ad hoc, creating another, undiscoverable API surface.

**Comment by thockin** [comment]
We have magic names now, they just happen to be field paths, but only a
select few hand-chosen field paths.

We should either generalize or stop pretending otherwise, was my point.

**Comment by paralin** [comment]
Was there an update to this? I need to access the image id from inside the container as well.

**Comment by lihan** [comment]
+1

**Comment by tyrsius** [comment]
Is there even a workaround for this? Any way to get the current version of the container as an ENV VAR?

**Comment by SneakyMax** [comment]
This is a problem we ran into, and we have not found a good workaround besides giving the service account access to the pods API and making a request to that.

**Comment by AgentME** [comment]
Just a tip for others who find themselves here: YAML repeated nodes may be useful if you just want to ensure certain fields match each other. See the usage of `&image` and `*image` below.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo-test
spec:
  containers:
    - name: client-container
      image: &image ubuntu:18.04
      command: ["/bin/bash", "-c"]
      args:
      - while true; do
          date
          sleep 5;
        done;
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      env:
        - name: CONTAINER_IMAGE
          value: *image
```

Note that the Kubernetes doesn't retain any knowledge of the repeated nodes. If you use `kubectl get -o=yaml ...`, then the returned yaml won't use the repeated nodes feature, and will instead show "ubuntu:18.04" twice.

**Comment by tyrsius** [comment]
@AgentME That doesn't really help here. The goal is to get information about the running container/pod.

**Comment by schmitch** [comment]
Actually it would also be great to actually get some parts of the `image` field.

I.e. `image: docker.io/library/nginx:1.13` to get the version out of the image field.

**Comment by thomas-riccardi** [comment]
/reopen
It seems it is still *not* possible to access the containers image ID using the downward API.

**Comment by GuiSim** [comment]
It's a shame this was closed, I would have used this feature.

**Comment by feisuzhu** [comment]
/reopen

Need this!

**Comment by rosscdh** [comment]
+1

**Comment by gecube** [comment]
It's nice idea. I'd like to have it implemented too.

**Comment by dobegor** [comment]
@sdminonne may I ask you to `/reopen` this?

**Comment by sdminonne** [comment]
@dobegor didn't work on this since 4 years.. But I'm more than happy to help (if needed)

**Comment by feisuzhu** [comment]
@sdminonne please /reopen this, it's still relevant.

**Comment by sdminonne** [comment]
@feisuzhu, I'm OK to reopen this issue but would you add more info here? Anything: ideas, implementation WIP, whatever. 
Thanks

**Comment by acnodal-tc** [comment]
Hi @sdminonne I'm not sure what info you're looking for but let me describe a use case that I'm working on. The Marin3r Envoy control plane https://github.com/3scale-ops/marin3r/ has a controller that launches Envoy proxy engine pods on demand. It uses its own image as an init container for the Envoy pods. It would be great if the controller could find out what image it is so it could use the same image for the Envoy pods. I've had no luck figuring out how to do that but this issue seems like it would enable this use case. Thank you!

**Comment by albertocavalcante** [comment]
+1

Any chance this is going to be implemented?

**Comment by Addyvan** [comment]
We already have the following which is supported:
```yaml
- name: MY_MEM_LIMIT
  valueFrom:
    resourceFieldRef:
      containerName: test-container
      resource: limits.memory
```

It feels incomplete to not also provide access to the limited number of other fields with something like:
```yaml
env:
- name: POD_IMAGE
  valueFrom:
    containerFieldRef:
      containerName: test-container
      fieldPath: image # or container.image
```

**Comment by kolluria** [comment]
I think @Addyvan's suggestion makes sense. 
I have been trying to pass the value of the `image` field on container to another but I don't seem to find a way.

**Comment by thockin** [comment]
I think the bar for adding new downward API values should be pretty low, IMO.    That said, we have `resourceFieldRef` distinct from `fieldRef`, so we would need something like `containerFieldRef` and maybe `containerStatusFieldRef` to extract `ImageID`.

KEPs are welcome.

**Comment by tatupesonen** [comment]
This would be very useful.
