### ISSUE TITLE
iptables rules not updated if or when hosts address changes

### ISSUE THREAD

**Issue by hir3npatel** [kubernetes/kubernetes#19480]
I dev locally using these docs:
http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html

The cluster works well until I move the laptop and wifi gets another address.

When starting the cluster iptables rules redirecting to the wifi network IP are setup, but then not updated if the address changes. This gets a bit annoying when the wifi address changes and I have to restart my cluster to use it again.

Are there any plans to have hyperkube watch for address changes or else easier ways to have the iptables rules updated if the wifi address changes for the host?

Thanks.

**Comment by thockin** [comment]
If there is a relatively easy way to know when this happens, I would not be
against refreshing iptables rules.  It's obviously not a production problem
(I hope!).  What makes this hard is that we jump through a bunch of hoops
to try to figure out which address to use, so it might not even be the one
that changes.

I'm open to proposals here.

**Comment by hir3npatel** [comment]
Hi, thanks. Yeah I can imagine it goes through hoops to get the right address. I'm not familiar with what sets up the iptables rules and which container it is. I was wondering though of adding an instruction to the piece that does the rules, to have it rerun the rules. So if it's one of the containers with hyperkube listening on localhost, I could maybe send it a command to tell it to rerun its iptables rules engine?
In this case I know when the address changes and so I can manually tell hyperkube to redo the rules without bringing down the whole cluster and bringing it up again.

**Comment by thockin** [comment]
On Jan 12, 2016 1:03 AM, "hir3npatel" <notifications@github.com> wrote:
>
> Hi, thanks. Yeah I can imagine it goes through hoops to get the right
address. I'm not familiar with what sets up the iptables rules and which
container it is. I was wondering though of adding an instruction to the
piece that does the rules, to have it rerun the rules. So if it's one of
the containers with hyperkube listening on localhost, I could maybe send it
a command to tell it to rerun its iptables rules engine?

We could catch SIGHUP and force-sync it all.  That's not too bad, but is
that good enough?

Patches welcome, I am happy to guide.

**Comment by hir3npatel** [comment]
It might be good enough, I could try it and see. It would involve changes to hyperkube I take it? Can you point me to what does the iptables rules and where it lives, I would be happy to attempt it.

**Comment by hir3npatel** [comment]
Don't know if this was resolved, but I don't care anymore. Feel free to close this.
