### ISSUE TITLE
+protobuf=true tags showing up in generated documentation

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#19483]
See documentation at https://godoc.org/k8s.io/kubernetes/pkg/runtime#TypeMeta and docs from the command line `go doc` tool. Please move these out of the type docstring.

**Comment by smarterclayton** [comment]
These belong in the type docstring.  That's how go2idl works.  I'm not sure what the alternative is.

**Comment by smarterclayton** [comment]
@lavalamp did you have a solution in mind for this?

**Comment by krousey** [comment]
Seems to work for the genclient tags. They appear before the docstrings.

**Comment by krousey** [comment]
I think this https://github.com/kubernetes/kubernetes/blob/master/cmd/libs/go2idl/types/types.go#L249 is what it does.

**Comment by smarterclayton** [comment]
Wow... that's ugly...

```
// +genclient=true

// PersistentVolumeClaim is a user's request for and claim to a persistent volume
type PersistentVolumeClaim struct {
	unversioned.TypeMeta `json:",inline"`
	ObjectMeta           `json:"metadata,omitempty"`

	// Spec defines the volume requested by a pod author
	Spec PersistentVolumeClaimSpec `json:"spec,omitempty"`

	// Status represents the current information about a claim
	Status PersistentVolumeClaimStatus `json:"status,omitempty"`
}
```

**Comment by krousey** [comment]
I would LGTM a better way that keeps it out of the type's docstring.

**Comment by smarterclayton** [comment]
I'm not seeing anything other than maybe a NOTE embedded in the type, which
has other issues.  This is going to make the nested structs pretty ugly for
field level overrides too.

**Comment by smarterclayton** [comment]
Will fix this after #19426 gets merged

**Comment by lavalamp** [comment]
Wow, that is super super ugly. I did not LGTM whatever added "SecondClosestCommentLines"

I was actually thinking that I *want* these things to show up in the documentation, as they convey information that is plausibly useful to humans, and that we should adjust the format until it's not hideous.

**Comment by smarterclayton** [comment]
I was thinking: "Generates to protobuf message Foo" or something similar,
with a leader like "GENERATES()" or something similar.

**Comment by lavalamp** [comment]
That SGTM

**Comment by smarterclayton** [comment]
Go now has a convention for this that they are using in the compiler

```
//go:something
```

We should consider having an equivalent, and filtering it from docs.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc
