### ISSUE TITLE
e2e tests failing on GKE due to "use of closed network connection"

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19491]
There are 2 `EmptyDir` tests and a `Secrets` test failing on GKE right now:

**EmptyDir volumes should support (root,0666,tmpfs) [Conformance]**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/empty_dir.go:69 "perms of file \"/test-volume/test-file\": -rw-rw-rw-" in container output Expected : to contain substring : perms of file "/test-volume/test-file": -rw-rw-rw-

**EmptyDir volumes should support (root,0644,tmpfs) [Conformance]**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/empty_dir.go:65 "perms of file \"/test-volume/test-file\": -rw-r--r--" in container output Expected : to contain substring : perms of file "/test-volume/test-file": -rw-r--r--

**Secrets should be consumable from pods [Conformance]**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/secrets.go:99 "content of file \"/etc/secret-volume/data-1\": value-1" in container output Expected : to contain substring : content of file "/etc/secret-volume/data-1": value-1

**Comment by ihmccreery** [comment]
These tests are all passing on GCE.

**Comment by ihmccreery** [comment]
Blech.  I was reading the error message completely wrong.  It's actually getting no response at all:

```
09:05:48   "content of file \"/etc/secret-volume/data-1\": value-1" in container output
09:05:48   Expected
09:05:48       <string>: 
09:05:48   to contain substring
09:05:48       <string>: content of file "/etc/secret-volume/data-1": value-1
```

Looks like we're failing to get logs (perhaps related to #19314):

```
09:05:41 STEP: Warning: Failed to get logs from node "gke-jkns-gke-e2e-ci-a2fe9df7-node-7yj4" pod "pod-secrets-6723b259-b885-11e5-9bf6-42010af01555" container "secret-test". Get https://gke-jkns-gke-e2e-ci-a2fe9df7-node-7yj4:10250/containerLogs/e2e-tests-secrets-vqs35/pod-secrets-6723b259-b885-11e5-9bf6-42010af01555/secret-test: use of closed network connection
```

I'm seeing similar error messages in other failed tests: "use of closed network connection".

@cjcullen?

**Comment by cjcullen** [comment]
This looks like the same problem as #19468. Did we recently change the set of tests running against GKE? We know we currently have tunnel flakiness issues after reboot/resize tests, but we've tiptoed around them up until now.

**Comment by ihmccreery** [comment]
The reboot tests were being skipped in the GCE_DEFAULT_SKIP, and I thought that was erroneous (see https://github.com/kubernetes/kubernetes/pull/19297#issue-125048577).

Unless we're running these tests in parallel (which we're not), I'd expect those tests to pass and not screw up a bunch of stuff.  Am I misunderstanding?

**Comment by cjcullen** [comment]
No, it is good that we are running them again. Should give more incentive to get #19314 in :).

Our current tunneling setup has the potential to hold on to a broken tunnel (from a rebooted/deleted node) for up to 5 minutes before all tunnels are dropped and recreated. Most tests make use of some proxy feature to verify functionality. So, if a reboot test runs right before a test that tries to get logs, for example, we may get unlucky and try to use a closed tunnel to a node that was recently rebooted.

#19314 will decrease that window from 5 minutes to 1 minute (time between healthchecks). I can think of some ways that we could reduce that unavailability-after-reboot window further, but they all come with worse tradeoffs: If we reduce the healthcheck period, we increase steady-state master CPU. If we healthcheck before proxying, or tunnel on demand, we add latency to every proxy connection.
