### ISSUE TITLE
Poor handling of host-networked pods

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#19508]
Seen when running the kube-proxy as a pod with `NetworkMode == "host"`.

The CNI plugin attempts to retrieve the IP address of the kube-proxy pod, but fails to do so due to the lack of an eth0 interface.

```
Jan 11 22:25:22 node-2 kubelet[877]: E0111 22:25:22.305240     877 manager.go:377] NetworkPlugin cni failed on the status hook for pod 'kube-proxy-172.24.114.32' - invalid CIDR address: Device "eth0" does not exist.
```

I think the plugin interface shouldn't be trying to get the IP address of host networked pods, or if it does it should just be using the node's IP address or some other field, since "eth0" won't always exist on a given node.

Additionally, I've seen the CNI interface call the network plugin setup and teardown hooks for pods with `NetworkMode == "host"` - I suspect that this is a bug, and the plugin interface shouldn't be executing network plugins for these pods (since they share host networking).

**Comment by bprashanth** [comment]
Yep, @dcbw fyi. I had to work around this in my (now obselete) pr: https://github.com/bprashanth/kubernetes/commit/118de18bf5669eb7a024ccc76ffd1b22faa20cf4

**Comment by thockin** [comment]
Can we peel that piece out of one of the PRs and get it in?

**Comment by caseydavenport** [comment]
Any chance we'll be able to get this in for v1.2?  Looks like most of the code has already been written.

**Comment by bprashanth** [comment]
I can try, good chance Dan will fix it anyway with his CNI changes (though unsure if that's making 1.2 proper)

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/20019

**Comment by caseydavenport** [comment]
Thanks @thockin :)

**Comment by thockin** [comment]
As an aside, even host network mode should find eth0...

**Comment by dcbw** [comment]
@thockin unless I misunderstand the issue here, there's no requirement that the host's network interface be named eth0.  That hasn't been true on Fedora for years, and any system that uses udev (which a lot of hosts will) won't be using the 'eth' namespace.

**Comment by caseydavenport** [comment]
@dcbw - yep, that's right.

**Comment by thockin** [comment]
Ahh, gotcha.  It's the hardcoded "eth0" that is at fault.  Yeah, ok.
