### ISSUE TITLE
Server side export error checking is not backwards compatible

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#19501]
https://github.com/kubernetes/kubernetes/blob/f5ea4f4671ae45f26537835f7ec8b4cdd1c0ea46/pkg/apiserver/resthandler.go#L150

started returning an error for get endpoints that had `?export=1` passed but didn't implement export.  That's not backwards compatible for callers that don't implement export (previously we ignored that request parameter) - it's probably better not to do the check.  Clients that really care can use swagger.

**Comment by smarterclayton** [comment]
Note that this isn't the worst non-backwards compatible change in the world, just that it adds an error surface area that wasn't previously an error.

**Comment by smarterclayton** [comment]
Identified in #17922 while updating other things

**Comment by bgrant0607-nocc** [comment]
@smarterclayton Previously `export=1` was a no-op, so, in some sense, adding this new parameter also breaks compatibility. 

How is this different from how we deal with unrecognized json fields? They are ignored, so if we add a new field with validation rules that someone happened to be passing before, they'll experience different behavior.

Whatever we decide should be clearly documented in release notes and in the API conventions.

cc @lavalamp

**Comment by brendandburns** [comment]
ignoring spurious parameters actually seems like a bad behavior, similar to when we didn't automatically validate 'json'

Suppose I typo and I send `?explort=1`  I'd really rather have an error than a drop.

So I guess I would argue that the previous behavior is a bug.  We should definitely document the change, but I think we should actually push in the opposite direction and validate all parameters.

**Comment by smarterclayton** [comment]
I'm ok with that.

Also, realized during this that the change to GetWithOptions is not
backwards compatible and that error checking has to be removed (clients
that implement GetWithOptions are responsible for implementing Export
because they are taking control of the request).  That'll be handled in
#17922.  That removes export support inside the specific code path served
by GetWithOptions.

**Comment by bgrant0607** [comment]
@brendandburns Scenario: kubectl gets updated and adds the export parameter to requests. However, the user's cluster hasn't been upgraded and doesn't know about the parameter.

Discussed in #5889 and #4855.

I don't see a compelling reason why we should apply different policies to query params than to the json schema. We should validate both or neither.

**Comment by brendandburns** [comment]
@bgrant0607 agree, but at this point `kubectl` validates by default, right?

**Comment by bgrant0607** [comment]
@brendandburns Yes, but it's optional and can be turned off. Also, since validation is in the client, a newer client will still work with an older apiserver.

**Comment by brendandburns** [comment]
actually, the 1.1 client didn't work with 1.0 because the swagger schema for `Service` objects that 1.0 served had a bug.  (this broke one of the e2e tests across version skew)

And I'm suggesting that parameter validation would be optional too, e.g. if you specify `?validate-parameters=false&...` we don't validate parameters.

**Comment by bgrant0607** [comment]
I'd be happy with a query param to control validation. If we're going to fix this in 1.2, we need to do it soon.

**Comment by smarterclayton** [comment]
Ship: sailed.
