### ISSUE TITLE
Shall we create subresource path for ServiceStatus

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#19504]
For top-level API types that have a `Status` field, we usually create a subresource path for it on the API server, and make an `UpdateStatus()` method in the client library. The `Service.Status` is the only exception, it doesn't have either of them. Is there a particular reason to break this convention?

I raised the issue because in #19349 we are autogenerating the UpdateStatus() method for the client library. The generator generates the `UpdateStatus()` method for the [client for Service](https://github.com/kubernetes/kubernetes/pull/19349/files#diff-6e7ec0db5816c399b12106abaad01f8bR80), but because there is no subresource path registered at the apiserver, that function will always fail.

@thockin @kubernetes/goog-cluster @nikhiljindal

**Comment by bprashanth** [comment]
We should have a subresource, I think we just forgot. Initially ServiceStatus was empty and we added loadbalancer in https://github.com/kubernetes/kubernetes/commit/3884d5fc59943e5745e3b7772898d0c160a3f754. 

I also don't think we validate servicestatus and we can probably do exactly the same thing we do for ingress: https://github.com/kubernetes/kubernetes/blob/3c3a24e1d4613574948deb163c6d4e869c26ee21/pkg/apis/extensions/validation/validation.go#L437

**Comment by nikhiljindal** [comment]
Is there anyone who updates the Status and will use the status subresource?

**Comment by bprashanth** [comment]
servicecontroller should be updating status with the loadbalancer ip for service.type = loadbalancer

**Comment by caesarxuchao** [comment]
@nikhiljindal, I just did a grep for ServiceStatus and that didn't show anything. Before creating this PR I did a more thorough search and found what bprashanth said.

**Comment by bprashanth** [comment]
eg: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L315

**Comment by caesarxuchao** [comment]
I'm going to add the path.

**Comment by lavalamp** [comment]
Adding services/status SGTM, thanks.

**Comment by bprashanth** [comment]
We already have a fix pr, I just ignored it because of the test heads down. I'll look at it now, I already did a couple of passes so it should be fine.
