### ISSUE TITLE
image manager should support multiple runtimes

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#19519]
Currently, the image manager in kubelet uses cadvisor to get the image file system info (capacity, usage, mountpoint, etc) for docker. (see [here](https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.5/pkg/kubelet/image_manager.go#L191)).

In order to make the image manager generic for other runtimes. We either:
- Have runtime implement the a similar interface (e.g. `ImageFsInfo()`)
- Patch cadvisor to support More container image fs info (e.g. `cadvisor.RktImagesFsInfo()`)

cross reference https://github.com/google/cadvisor/issues/858

cc @sjpotter @jonboulle  @feiskyer @kubernetes/sig-node

**Comment by feiskyer** [comment]
Ref #18770

**Comment by yujuhong** [comment]
> cAdvisor will be standalone, ref #18770

@feiskyer, IIUC, kubelet will still rely on the built-in cadvisor for basic metrics and container information. The standalone cadvisor is for monitoring and collecting advanced metrics.

**Comment by vishh** [comment]
I'm working on a patch to simply image management and as part of that I was
planning on proposing deleting all unused images whenever there is disk
pressure.
Tracking image specific disk usage is very tricky given that we use overlay
filesystems and the current implementation uses virtual size which is
incorrect.

Any objections?

**Comment by yujuhong** [comment]
This is outdated due to CRI
