### ISSUE TITLE
kubectl --validate doesn't work for optional APIs

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#19515]
kubectl fails to create deployment resource and emits the following:
`error validating "/examples/extensions/deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false`

I guess that is because deployment is disabled by default.

I could be wrong, but I think this used to work before. Not sure if we changed some validation code recently.

Steps I did:
`
 RUNTIME_CONFIG=extensions/v1beta1/deployments=true ./hack/local-up-cluster.sh
./cluster/kubectl.sh create -f examples/extensions/deployment.yaml
`

cc @kubernetes/sig-api-machinery @kubernetes/goog-csi @janetkuo

**Comment by caesarxuchao** [comment]
I think you are right, the validation error is because deployment is disabled by default, so the swaggerapi doesn't contain it in "models".

I tried with the steps you did, `kubectl create` doesn't return any error.

**Comment by janetkuo** [comment]
Works on my machine too. Did you try updating swagger spec? Or just run `hack/update-all.sh` and see if it still happens?

**Comment by caesarxuchao** [comment]
Doesn't kubectl fecth the swagger spec from apiserver at runtime? Does it change the behavior recently?

**Comment by caesarxuchao** [comment]
@janetkuo, I read the code again it seems the local swagger spec shouldn't affect the validation, see this [line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L510) :)

Btw that line should be refactored to use the client.SwaggerSchema.

**Comment by janetkuo** [comment]
I remembered ran into this error while modifying deployment spec (`types.go`). IIRC `hack/update-all.sh` solved the problem then.

**Comment by softwaredefinedworld** [comment]
This is still not working for me as well. I have 1.1.3 release downloaded only binaries and no sources. How do i fix it so that deployments start working ?

**Comment by caesarxuchao** [comment]
@softwaredefinedworld, did you start your apiserver using `RUNTIME_CONFIG=extensions/v1beta1/deployments=true ./hack/local-up-cluster.sh ./cluster/kubectl.sh`?

**Comment by krmayankk** [comment]
Sorry i am using a different account, now, but can you elaborate on what you mean by the above ? I downloaded the  binaries and those dont have a folder like 'hack' only the sources have it. Are you asking to rebuild the K8s ? The apiserver is started for me using kube-up.sh. Do you want me to restart the api server ? I am using GCE.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/deployments.md#enabling-deployments-on-a-kubernetes-cluster has details on what you need to do to enable deployments on your GCE cluster.

You can verify that it is working by going to `<kube-master-url>/apis/extensions/v1beta1` and you should see deployments in the list of resources.

**Comment by nikhiljindal** [comment]
The problem was that in my case, kubectl was reading the cached swagger spec (which did not have deployments).
I assumed that running `make clean` will clean everything but it doesnt.
Manually deleting the spec from `~/.kube/schema/` fixed the issue.

Will see if we can clear that directory on `make clean`.
We should also update the deployments doc to state this.

**Comment by krmayankk** [comment]
I already enabled ENABLE_DEPLOYMENTS=true before running kube-up.sh yesterday and it didnt work. Do i need to do something else ? How do i restart api server to run with the right config ?

**Comment by janetkuo** [comment]
@krmayankk: Not sure if it's just a typo but you should run `KUBE_ENABLE_DEPLOYMENTS=true cluster/kube-up.sh`. Could you try `kubectl get deployments` and see if it returns any error? If so, deployment isn't enabled correctly.

**Comment by krmayankk** [comment]
I think there are two versions of the document, https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/deployments.md#enabling-deployments-on-a-kubernetes-cluster and new https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/deployments.md which refer to both  different environment variables. One points to ENABLE_DEPLOYMENTS and other one to KUBE_ENABLE*. With KUBE_ENABLE_* it worked. Thanks for your help

**Comment by janetkuo** [comment]
@krmayankk thanks for the report. https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/deployments.md is outdated and we should update it.

**Comment by krmayankk** [comment]
get deployments doesnt return any errors now after enabling the environment variable.
kubectl.sh get deployments
NAME      UPDATEDREPLICAS   AGE

the http://localhost:8080/apis/extensions/v1beta1 (using kubectl proxy) returns the deployments
{
  "kind": "APIResourceList",
  "groupVersion": "extensions/v1beta1",
  "resources": [
    {
      "name": "deployments",
      "namespaced": true
    },

but when i try to create the deployment, it returns an error:-
kubectl.sh create -f nginx-deployment.yaml 
error validating "nginx-deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false

What else do i need to enable ?

**Comment by caesarxuchao** [comment]
@krmayankk, have you tried nikhiljindal's solution: `Manually deleting the spec from ~/.kube/schema/ fixed the issue.`

**Comment by krmayankk** [comment]
my ./kube folder only has a config file, nothing else

**Comment by krmayankk** [comment]
Just an update as the error message suggested, i set the validate flag to false --validate=false as follows and it worked. Please let me know what issues can this cause and how to fix it

**Comment by kargakis** [comment]
So this isn't really an issue?

**Comment by krmayankk** [comment]
It only works for me when i enable --validate=false flag. So how can we fix that ?

**Comment by janetkuo** [comment]
@krmayankk can you provide the result of `kubectl.sh version`?

**Comment by krancour** [comment]
I am running into this exact issue except with daemonsets.  API server has `--runtime-config=extensions/v1beta1/daemonsets=true` and I still get this warning unless setting the `--validate=false` flag when using `kubectl`.

Both client and server are at version 1.1.7.

**Comment by krancour** [comment]
@krmayankk I had the same problem as you.  No `schema` dir in `~/.kube`.  I discovered through another thread the existence of `/tmp/kubectl.schema`.  Try deleting that instead.  It worked for me.

**Comment by nikhiljindal** [comment]
Filed https://github.com/kubernetes/kubernetes/issues/21353 to provide a better way to delete cached swagger spec in kubectl

**Comment by AdoHe** [comment]
@kargakis in kubernetes 1.1.7 the schema-cache-dir will be `/tmp/kubectl.schema`, so you need to delete this.

**Comment by RaghavendraNandagopal** [comment]
Hi,
   Running into same issue.  Below are the versions and environment 
`Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T23:43:00Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}`

Minikube version: minikube version: v0.17.1

Here the error that I am getting:
**error: error validating "deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false**

**Comment by tkrille** [comment]
Same here. I'm taking the tutorial ["Running a Stateless Application Using a Deployment"](https://kubernetes.io/docs/tutorials/stateless-application/run-stateless-application-deployment/). There seems to be a typo in the YAML in the section ["Creating and exploring an nginx deployment"](https://kubernetes.io/docs/tutorials/stateless-application/run-stateless-application-deployment/#creating-and-exploring-an-nginx-deployment).

@RaghavendraNandagopal Try changing the line that says

```
apiVersion: v1beta1
```

to

```
apiVersion: extensions/v1beta1
```

At least, this worked for me.

**Comment by RaghavendraNandagopal** [comment]
@tkrille Thanks!.  It worked.

**Comment by dshamanthreddy** [comment]
~# kubectl create -f nginx-v1.yaml
error: could not read an encoded object from nginx-v1.yaml: API version "apps/v1" in "nginx-v1.yaml" isn't supported, only supports API versions ["v1"]
error: no objects passed to create
