### ISSUE TITLE
Proposal: Kubernetes use revocable resources from Mesos

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#19529]
After [MESOS-1607](https://issues.apache.org/jira/browse/MESOS-1607) and [MESOS-354](https://issues.apache.org/jira/browse/MESOS-354), the revocable resources will offer to Kubernetes; it'll improve the resources utilisation if Kubernetes used revocable resources.

I'm also working on [MESOS-4303](https://issues.apache.org/jira/browse/MESOS-4303) to clarify the protocol between Kubernetes & Mesos; if any suggestion, please let me know.

**Comment by qiujian16** [comment]
+1 for this feature

**Comment by k82cn** [comment]
/close

One of kube-mesos roadmap; tracing in kube-mesos
