### ISSUE TITLE
Kubernetes calls delete on CNI network plugin multiple times

### ISSUE THREAD

**Issue by tomdee** [kubernetes/kubernetes#19523]
Seen running kubernetes v1.1.3

I have a 200 nodes cluster with a single RC running scaled to 10000 pods. I scaled the RC down to 0 pods and received 10009 calls to the CNI plugin.

Is this expected behavior? If not, I can try to dig into some more and check through the logs. Which component's logs should I be looking at?

**Comment by bprashanth** [comment]
It can if deleting a pod failed, did that happen?

**Comment by AdoHe** [comment]
@tomdee you should look at the kubelet log, 10009 calls to CNI plugin, you know which method of CNI plugin get called?

**Comment by bprashanth** [comment]
I'm guessing `CNI_COMMAND=DEL`

**Comment by AdoHe** [comment]
@tomdee @bprashanth I think a possible cause is that the `podKiller` failed to delete some pods for some reason, so the periodic cleanup routine trigger deletion again.

**Comment by tomdee** [comment]
I don't see any kubelet lots of around the time of the failure. I see dockerd complaining about stop being called a second time though.

**Comment by tomdee** [comment]
Also, the two delete calls were <1s apart.

**Comment by thockin** [comment]
Any repro on this?

**Comment by AdoHe** [comment]
@tomdee any progress on this? Guess I meet the same problem when I am using a network plugin to configure network.

**Comment by bprashanth** [comment]
Closing this in favor of https://github.com/kubernetes/kubernetes/issues/20379 which has more context, even though it came after
