### ISSUE TITLE
Listing namespaced services from a specific resource version doesn't work

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#19525]
SSHing into master:

```
$ curl localhost:8080/api/v1/namespaces/default/services?resourceVersion=0
{
  "kind": "ServiceList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/default/services",
    "resourceVersion": "2578"
  },
  "items": [
    {
      "metadata": {
        "name": "default-http-backend",
        "namespace": "kube-system",
        "selfLink": "/api/v1/namespaces/kube-system/services/default-http-backend",
        "uid": "ce9e765b-b8ce-11e5-be38-42010af00002",
        "resourceVersion": "52",
        "creationTimestamp": "2016-01-12T01:50:07Z",
        "labels": {
          "k8s-app": "glbc",
          "kubernetes.io/cluster-service": "true",
          "kubernetes.io/name": "GLBCDefaultBackend"
        }
      },
      "spec": {
        "ports": [
          {
            "name": "http",
            "protocol": "TCP",
            "port": 80,
            "targetPort": 8080,
            "nodePort": 30219
          }
        ],
        "selector": {
          "k8s-app": "glbc"
        },
        "clusterIP": "10.0.68.57",
        "type": "NodePort",
        "sessionAffinity": "None"
      },
      "status": {
        "loadBalancer": {}
      }
    }
  ]
}
```

Note I listed namespace/default and the only result returned was a kube-system service. This also means that the first list of the reflector will return the kube-system service. It doensn't happen for namespaceAll (i.e /v1/services?resourceVersion=0). 

@kubernetes/goog-control-plane did we change list/watch semantics recently?

**Comment by mikedanese** [comment]
@kubernetes/goog-csi @caesarxuchao @lavalamp since api server

**Comment by gmarek** [comment]
@bprashanth - we did change the watch semantics lately, but not in this way. We're currently serving results from the cache, instead of etcd, which means that they may be a bit stale. But we certainly shouldn't be returning things from other namespaces. Sadly @wojtek-t who did this work is OOO until February, but maybe @timothysc will know something.

**Comment by bprashanth** [comment]
We should understand the scope of impact here, we might be open to worse forms of privilege escalation. Maybe someone on @kubernetes/goog-cluster is interested.

**Comment by timothysc** [comment]
@bprashanth given that we run things differently, could you give a complete list of expected results to actual results.

**Comment by wojtek-t** [comment]
@bprashanth - was it a single failure or was it reproducible? If you did the same request again, did it return the same result?

**Comment by bprashanth** [comment]
@wojtek-t I can reproduce on e2e-master in k8s-jenkins-e2e-gce. It is weird that I only get a single service from kube-system. Note that the sericeLink.selfLink says `namespaces/default` but the metadata.namespace of the item says kube-system. 

All this stuff got paged out or I'd debug it myself. 

@timothysc I'd expect https://master-ip/api/v1/namespaces/default/resourceName?resourceVersion=0 to *not* return something from a namespace other than default, because that's essentially the query the reflector would run for a listwatch client created via https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/listwatch.go#L49

**Comment by wojtek-t** [comment]
This definitely looks like a bug.
Unfortnately I'm on paternity leave now, so I'm not able to debug it myself...

**Comment by timothysc** [comment]
I'll take a look later today or tomorrow at this point.

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/pull/19663

Luckily most clients either list NamespaceAll or don't specify an rv (which bypasses the cache and hits etcd directly, so the list is still consistent).

**Comment by davidopp** [comment]
So is the idea that #19970 will fix this?

**Comment by bprashanth** [comment]
Yes

**Comment by wojtek-t** [comment]
@bprashanth - since #19970 is merged, can you please verify that it is fixed?

**Comment by liggitt** [comment]
serving from cache is now required to opt-in with resourceVersion=0
closing due to age, please reopen if this is an issue
