### ISSUE TITLE
Improve error messages for non-existent api groups/resource types

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#19530]
``` bash
kubectl version
# Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
# Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}

kubectl api-versions
# extensions/v1beta1
# v1

kubectl create -f resources
# error validating "resources/deployment.json": error validating data:
# couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false

kubectl create -f resources --validate=false
# Error from server: error when creating "resources/deployment.json":
# the server could not find the requested resource
```

``` json
{
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment",
  "metadata": {
    "name": "..."
  },
  "spec": { ... }
}
```

I couldn't find any documentation regarding having to manually enable the extensions API on GKE, but from the looks of it, it's not enabled by default (yet)?

Any documentation that I missed that explains how to enable this on a currently running GKE Kubernetes 1.1 cluster?

**Comment by JeanMertz** [comment]
Re-reading the documentation, I now understand this part better:

> Deployments is part of the extensions API Group and is not enabled by default.

So effectively, having the extensions API group enabled, does not guarantee any of its features being enabled. Is there an easy way to enable this on GKE?

**Comment by sijnc** [comment]
This bit me as well, if technically possible it would be great to be able to run beta extensions on GKE.

**Comment by mikedanese** [comment]
It is not possible to enable/disable resources in GKE beyond the default. Deployments will be enabled in GKE until v1.2 is release.

We do not enable resources in GKE until we can guarantee that we will no longer make backwards incompatible changes to them. It's impossible for us to (safely) upgrade a cluster if we've made backwards incompatible changes without deleting resources. At the time of v1.1 Deployment was not at a place where we wanted to commit to this requirement.

The error message could be better though. We should be able to distinguish between resource not found and resource not enabled.

**Comment by sijnc** [comment]
@mikedanese That makes sense and that you for explaining why GKE works this way.

**Comment by bgrant0607** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
There's another request in some issue for these error messages. I said it was hard, because we turn off the objects so early in the process that the api installer code has no idea they are even things.

Maybe we could register dummy objects? Not sure. @nikhiljindal, any thoughts?

**Comment by bgrant0607** [comment]
See also #6703

**Comment by bgrant0607** [comment]
This is a problem in `kubectl get` also. Omitting the resource type will cause kubectl to treat the resource name as the type. For example: `kubectl get my-pod-name`.

**Comment by bgrant0607** [comment]
See also #18924
