### ISSUE TITLE
Reclassify [Skipped] issues: Latency

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19548]
@wojtek-t there is a test that you've marked as skipped that needs to be reenabled or otherwise taken care of (see #19505):

- "Latency [Skipped]": What should we do with it?  You originally disabled it in #17714.

Happy to answer any questions if anything doesn't make sense.

**Comment by ihmccreery** [comment]
This is work toward #10548.

**Comment by wojtek-t** [comment]
I'm on  paternity leave now.

For me this test doesn't make sense - this is part of Density test basically. What we should do is to refactor Density test and allow running Latency test as Density with "--empty-cluster" flag (or sth like that).

**Comment by gmarek** [comment]
There's already a runLatencyTest "flag" in list of density tests. We just need to expose it. @ihmccreery please assign a priority for this.

**Comment by wojtek-t** [comment]
We need something different. There is a flag whether to run latency test in Density. But if we run it, it will be run in full cluster. Latency test runs in in empty cluster. So we need another flag.

**Comment by gmarek** [comment]
Do you believe that we want to run lantency test in empty clusters? I can add this easily enough, I'm just not sure it's worth the effort.

**Comment by wojtek-t** [comment]
For me adding this test was a bad idea. But some gues wanted to have it - we need to ask them what was the motivation.

**Comment by ihmccreery** [comment]
As long as we're talking about density, note that I also opened #19542 about "Density [Skipped]".

**Comment by ihmccreery** [comment]
Ping on this; @wojtek-t what do you want to do with this?  We shouldn't just be keeping dead code around, as it confuses what tests are running where.

**Comment by ihmccreery** [comment]
Based on the conversation above, I'm going to move this to `[Feature:Latency]` and opened #20188 to figure out if you all want to delete this test or run it somewhere (where?).

**Comment by ihmccreery** [comment]
Closing in favor of #19542.

**Comment by wojtek-t** [comment]
@ihmccreery sorry - I was on paternity leave for a month :)
