### ISSUE TITLE
Reclassify [Skipped] issues: HPA, Initial Resources, Load capacity, Density

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19542]
@piosz there are a few tests that you've marked as skipped that need to be reenabled or otherwise taken care of (see #19505):

- "Horizontal pod autoscaling (scale resource: CPU) [Skipped]": originally disabled due to flakiness in #17587; should it be marked as a flake and have an issue opened?
- "Initial Resources [Skipped]": originally disabled in #15655; similar, should be marked as a flake with an issue opened?
- "Load capacity [Skipped]": "can take a long time to run"; should this be `[Slow]`?

Happy to answer any questions if anything doesn't make sense.

**Comment by ihmccreery** [comment]
This is work toward #10548.

**Comment by ihmccreery** [comment]
@piosz Could you also comment on:

- "Density [Skipped]": "can take a long time to run"; should this be `[Slow]`?

**Comment by piosz** [comment]
> - "Horizontal pod autoscaling (scale resource: CPU) [Skipped]": originally disabled due to flakiness in #17587; should it be marked as a flake and have an issue opened?

The test should work now. I'll re-enable it.
> - "Initial Resources [Skipped]": originally disabled in #15655; similar, should be marked as a flake with an issue opened?

The source of flakiness is Heapster. We are working hard on reimplementing Heapster (see https://github.com/kubernetes/heapster/tree/heapster-scalability). This should be done for 1.2, so I'll re-enable the test then.
> - "Load capacity [Skipped]": "can take a long time to run"; should this be `[Slow]`
> - "Density [Skipped]": "can take a long time to run"; should this be [Slow]?

Those tests are owned now by @gmarek and @wojtek-t

**Comment by gmarek** [comment]
@ihmccreery - what is semantics of `[Slow]`?

**Comment by wojtek-t** [comment]
What we need from Density ad Load is the "[Performance]" tag (this is what scalability suite is running):
https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e.sh#L516

So [Skipped] is only used to not run it in standard suite. I'm not sure how it is solved for other tests that shouldn't be running there...

**Comment by ihmccreery** [comment]
Great, this is helpful.

> The source of flakiness is Heapster. We are working hard on reimplementing Heapster (see https://github.com/kubernetes/heapster/tree/heapster-scalability). This should be done for 1.2, so I'll re-enable the test then.

Then it should be marked `[Flaky]`.

> @ihmccreery - what is semantics of [Slow]?

See #19505.

> What we need from Density ad Load is the "[Performance]" tag

Let's change that to `[Feature:Performance]` per #19505.  Anything marked `[Feature:...]` will be skipped by default, serving the purposes of both `[Skipped]` and `[Performance]`.

**Comment by wojtek-t** [comment]
SGTM - @gmarek - can you please take care of it since I'm on paternity leave?

**Comment by gmarek** [comment]
If I manage to find time - it has low priority now, as we had serious performance regression during the weekend.

**Comment by ihmccreery** [comment]
@gmarek What can we do with:

- "Load capacity [Skipped]": "can take a long time to run"; should this be [Slow]
- "Density [Skipped]": "can take a long time to run"; should this be [Slow]?

I'm pushing hard on  #10548 as part of our test reliability surge.

**Comment by ihmccreery** [comment]
> What we need from Density ad Load is the "[Performance]" tag (this is what scalability suite is running).

Ah, didn't read that close enough; I will send a PR.

**Comment by gmarek** [comment]
Sorry - I missed this issue. Let's discuss it over VC today.

**Comment by ihmccreery** [comment]
With #19934 and #20274 in, this is now closed. Thanks folks!
