### ISSUE TITLE
Reclassify [Skipped] issues: Volumes and PersistentVolumes

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19549]
@markturansky there is are a couple of tests that you marked as skipped that needs to be reenabled or otherwise taken care of (see #19505):

- "PersistentVolumes [Skipped]"
- "Volumes [Skipped]"

Can we instead classify these as `[Feature:Volumes]`?  See #19505 for context.

Happy to answer any questions if anything doesn't make sense.

**Comment by markturansky** [comment]
They are skipped because they require privileged containers, which were not in e2e at the time.  Running NFS in a pod, for example, requires privileged.

So @jsafrane and I made e2e tests that we could run locally but would not be able to run elsewhere.

Are these kinds of tests able to be run now?

**Comment by ihmccreery** [comment]
@thockin Should we consider these tests auxiliary, or would you like to move these into the standard set that we run? See #19505 for context.

**Comment by ihmccreery** [comment]
This is work toward #10548.

**Comment by jsafrane** [comment]
The tests are skipped because they require user space tools for various volumes on all nodes in the cluster (e.g. /sbin/mount.nfs, /bin/rbd etc).

AFAIK, privileged containers are now enabled in e2e tests by default.

**Comment by ihmccreery** [comment]
> AFAIK, privileged containers are now enabled in e2e tests by default.

@jsafrane does that mean we expect these tests to pass on a "standard" cluster, or do the user space tools block that?

**Comment by jsafrane** [comment]
Additional "non-standard" user space tools are required to run the test.

These tools can be easily installed by:
```
export E2E_STORAGE_TEST_ENVIRONMENT=true
cluster/kube-up.sh
```

See https://github.com/kubernetes/kubernetes/pull/12393 for additional info
