### ISSUE TITLE
Create policy, infra, & best practices for testing contrib projects/pods

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19554]
Per @bprashanth's https://github.com/kubernetes/kubernetes/issues/19552#issuecomment-171017736, we need to nail down how we want to go about ensuring that contributed pods are working as intended.  People can contribute e2e tests and mark them as `[Feature:...]`, but they will then be expected to make sure they're running as necessary.

@kubernetes/goog-testing Do we want to be keeping track of these in some ways?

@bprashanth @thockin  Do you have any thoughts to contribute to this?

**Comment by bprashanth** [comment]
At one point @ArtfulCoder was interested in a labelling strategy which might work here. Say any change to services/ingress/endpoints could break the serviceloadbalancer, I'd apply the label to the relevant kubernetes pr, and it would pull down the contrib pod and run the e2e against HEAD+changes.

**Comment by bprashanth** [comment]
Another option is to run a public jenkins builder in the contrib repo, and setup cron jobs that periodically rev the godep and build images. That would be really nice, but probably too much work. It's essential that whichever way we run these tests, the results must be public, though.

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by justinsb** [comment]
@zmerlynn also created a great testing strategy for kops, which isolates k8s & kops from each other's breakages.  There is a "last known good" version of kops; we advance that version only when kops passes e2e.  So when kubernetes is tested against kops, it is tested with a kops version that is known not to be broken.  I'm sure he can explain much better than I!
