### ISSUE TITLE
Reclassify [Skipped] issues: ServiceLoadBalancer

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19552]
@bprashanth You originally marked the "ServiceLoadBalancer [Skipped]" test `[Skipped]` in #14988 and, as far as I can tell, never sent a follow-up PR.

Can we expect this test to run in a standard suite, or does it need special treatment?  If you want to classify it for special treatment, we'll need to find somewhere to make sure it's running.  See #19505 for context.

Happy to answer any questions if anything doesn't make sense.

**Comment by ihmccreery** [comment]
This is work toward #10548.

**Comment by bprashanth** [comment]
I don't think this test needs to run periodically. it's a contrib project, some handful of people out there actually use the pod, it's only purpose is to make sure that when we update the image, it isn't horribly broken. 

I don't know how to handle the situation, there are several totally untested contrib projects today (and it isn't feasible to test every contributed pod). At the same time you want an quick signal that things are still working everytime you push a new image.
