### ISSUE TITLE
Passing flags to docker from the container manifest

### ISSUE THREAD

**Issue by lexx587** [kubernetes/kubernetes#19565]
I have a customer who'd like to configure logging verbosity through the container manifest. There's a "--log-level" flag available for the docker CLI, but there doesn't seem to be any way to pass this through to the underlying docker command. I'm sure it would be useful in many contexts such as this to be able to pass flags through to docker from the manifest. Is there any plan to add this functionality? Better yet, is there any plan to allow the configuration of logging verbosity directly from the container manifest?

**Comment by thockin** [comment]
`--log-level` is a flag to the docker daemon, not to any container instance.  The container manifests are individual instances, so this does not map.
