### ISSUE TITLE
Add option to gc containers from deleted pods

### ISSUE THREAD

**Issue by dustymabe** [kubernetes/kubernetes#19571]
Kindly close this issue if it is not desirable.

In the past there have been some issues (#1148 is one) about cleaning up containers. Now in kubelet there are a few options to control garbage collection of containers.. (the docs for these was added in https://github.com/kubernetes/kubernetes/pull/13087)

- maximum-dead-containers-per-container
- maximum-dead-containers

Should we add an option to kubelet:

- delete-containers-on-pod-deletion=false

Then the user could change it to `true` as an option to kubelet and after pod deletion all related containers would go away.

**Comment by yujuhong** [comment]
I think we want to do this by default (see #8347) and may not provide a knob to turn it off.

**Comment by dchen1107** [comment]
@dustymabe  Can you share more on your usecases on why keeping dead containers of deleted pods around?

**Comment by dustymabe** [comment]
@yujuhong. I don't necessarily have a use case that warrants keeping dead containers around of deleted pods (my desire by opening this issue is to make it so that they will get cleaned up). That being said, changing functionality on people is not the best thing to do when you don't provide a way to go back (via config).

Since we don't currently clean them up then I would prefer giving the user an option to keep them around.

**Comment by yujuhong** [comment]
@dustymabe, let's close this issue and discuss in #8347 so it's easier to track.
