### ISSUE TITLE
Issues of Installing External Load Balancer with kube-proxy

### ISSUE THREAD

**Issue by cheyang** [kubernetes/kubernetes#19587]
Hi,
We are working on creating a k8s cluster in our production environment, and investigating how to setup external load balancer for  it so external system can access it. Here is the architecture.

![kube cluster diagram](https://raw.githubusercontent.com/cheyang/kubernetes_cd/master/kube-cluster.png)

We installed the kube-proxy/flannel/haproxy in the same machine to make it routable to Service and Pod, and configure the service ip in haproxy.  Here are my thoughts:

**Advantage**:
1. Make the router path shorter than [existing solution](http://www.dasblinkenlichten.com/kubernetes-101-external-access-into-the-cluster/)
original way:  haproxy->minion 3(kube proxy)->minion 1(real pod placement)
our way: haproxy->minion1(real pod placement)
2. The service metadata file doesn't need to configure something like PublicIPs to strict to environment.

**Disadvantage:**
haproxy machine may have heavy load in iptables NAT work, and I noticed if there is no kubelet installed with kube-proxy. It will use userland proxy rather than iptables. So I'm concerning the performance issue in haproxy machine.

```
server.go:355] Not trying iptables proxy: can't get Node "cycy-dev": node "cycy-dev" not found
kube-proxy[28184]: E1230 02:00:36.282376   28184 proxier.go:193] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't loa
kube-proxy[28184]: Try `iptables -h' or 'iptables --help' for more information.
```

It's  I want to get the insight from k8s experts about this.  And is it possible to enable iptable proxy without kubelet.

**Comment by lavalamp** [comment]
@thockin, I think this is up your alley.

**Comment by thockin** [comment]
2 things.

First: kube-proxy and kubelet are totally independent.  That error is not an error, if it is the error I think it is.

Second: You should not need kube-proxy at all.  Start with https://github.com/kubernetes/contrib/tree/master/service-loadbalancer and maybe expand to https://github.com/kubernetes/contrib/tree/master/Ingress as a more integrated model.

@bprashanth

**Comment by bprashanth** [comment]
> haproxy machine may have heavy load in iptables NAT work, and I noticed if there is no kubelet installed with kube-proxy. It will use userland proxy rather than iptables. So I'm concerning the performance issue in haproxy machine.

You can apply whatever loadbalancing algorithm directly to the endpoints of your service through  service-loadbalancer (and set the algorithm via: https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/service_loadbalancer.go#L73), no NAT.

**Comment by AdoHe** [comment]
also I think a service-loadbalancer is more considerable.

**Comment by bprashanth** [comment]
We have various ways to ingress into a cluster with/without kube-proxy now including a nginx ingress controller (https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx) and the haproxy loadbalancer mentioned above, so im closing this
