### ISSUE TITLE
Find a bug here ?

### ISSUE THREAD

**Issue by HardySimpson** [kubernetes/kubernetes#19583]
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/thread_safe_store.go#L246

the `indices` here is initialize with a new `Indices{}`, not from function param `indices Indices` at line 242 ?

**Comment by mikedanese** [comment]
Yup that looks incorrect. Care to send a PR to fix?

**Comment by HardySimpson** [comment]
Don't care, please come on

**Comment by Pensu** [comment]
@mikedanese Sould I send a PR regarding this?
