### ISSUE TITLE
There are many (u)int types in our API.

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#19595]
> All public integer fields MUST use the Go (u)int32 or Go (u)int64 types, not (u)int (which is ambiguous depending on target platform). Internal types may use (u)int.

But I notice there are may `(u)int` types, for example, should we replace all the `(u)int` as `(u)int32`?

BTW, what does the `Internal types` mean if I ask?

**Comment by thockin** [comment]
internal types are types that are not exposed in the API and are not
serialized.

Most of the remaining `int` fields are in places where the actual width is
so much smaller than int's limitations that it doesn't matter.  e.g. port
numbers are 0-65535, so it doesn't really matter whether int is 32 bits or
64.  That said, making those explicit is probably reasonable, but not
urgent.
