### ISSUE TITLE
Unknown address space

### ISSUE THREAD

**Issue by ShadySQL** [kubernetes/kubernetes#19598]
Upon deploying a new cluster to Azure - I noticed that the subscription was wrong so I killed the deployment. Now I changed the default subscription and ready to deploy once again but get this error:
## writing new private key to './output/kube_b523cd7be6617f_ssh.key'

  error: unknown option `--address-space'

azure_wrapper/fail: Exiting due to an error.
azure_wrapper/info: Saved state into `./output/kube_b523cd7be6617f_deployment.yml`
azure_wrapper/info: You probably want to destroy and re-run.

**Comment by Pensu** [comment]
Did you destroy and re-run again? Does the problem persist?

**Comment by raulk** [comment]
This occurs when you've switched to the Resource Manager deployment model. Switch back to Service Management:

    azure config mode asm

**Comment by fannaroh** [comment]
I had the same issue and switched to asm as @raulk suggested. Works like a charm.

**Comment by phagunbaya** [comment]
Will this be fixed soon ?

**Comment by xied75** [comment]
Related thought: shouldn't we use Azure Resource Management template as the deployment vehicle and come up with a tool similar to this:
https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/aws

**Comment by brendandburns** [comment]
Closing this as obsolete. Please use Azure Container Service or ACS-Engine for deployment.
