### ISSUE TITLE
mismatched types in an fmt.Errorf instance

### ISSUE THREAD

**Issue by majewsky** [kubernetes/kubernetes#19596]
Just a small papercut: https://github.com/kubernetes/kubernetes/blob/9fda7f181299e49dd5f28405952ee76821eab74c/pkg/kubectl/rolling_updater.go#L408

```go
return nil, false, fmt.Errorf("Invalid controller spec for %s; required: > 0 replicas, actual: %d\n", controller.Name, controller.Spec)
```

The last argument should be `controller.Spec.Replicas` to match the format verb `%d`. I would do a PR, but getting the corporate CLA signed is much too time-consuming, compared to the size of this issue.

**Comment by lavalamp** [comment]
Maybe @janetkuo? P1 since it's super easy and appears to be a user-seen error message.
