### ISSUE TITLE
Stop using bufio.Scanner in kubernetes/pkg/util/yaml

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#19603]
We're using bufio.Scanner to split YAML documents in `pkg/util/yaml`, but bufio.Scanner cannot handle lines longer than 64KB (you'll get "bufio.Scanner: token too long").  This prevents commands that output in YAML as lists of items to output from working correctly in a pipe if any line is >64KB.

The splitter should use a custom scanner that walks lines (we can safely ignore any line >64KB anyway) - there's a lower level incremental read to buffer command in bufio that we should use.

**Comment by AdoHe** [comment]
@smarterclayton I volunteer myself to do this.

**Comment by smarterclayton** [comment]
Great - https://golang.org/pkg/bufio/#Reader.ReadLine is the typical tool used in cases like this.  Thanks!

**Comment by AdoHe** [comment]
@smarterclayton I thought about this for a while, and write a simple `readLine` function:
```
func readLine(r *bufio.Reader) (string, error) {
	var (
		isPrefix bool  = true
		err      error = nil
		line, ln []byte
	)

	for isPrefix && err == nil {
		line, isPrefix, err = r.ReadLine()
		copy(ln, line)
	}
	return string(ln), err
}
```
Then I am trying to implement a custom scanner, but for the custom scanner's `Scan` method, we just walks by line, so I am guessing the default `yamlSeparator="\n---"` has to be changed.

**Comment by smarterclayton** [comment]
It's fine not to use scanner if you don't need it.

**Comment by AdoHe** [comment]
@smarterclayton ok, I will open a PR once I finish the test.

**Comment by wangqunOne** [comment]
@smarterclayton and @AdoHe , Are this issue progressing ? When can update it? Thanks.

**Comment by AdoHe** [comment]
@wangqunOne I have opened a PR #23265 ptal.

**Comment by smarterclayton** [comment]
We still need to fix this

**Comment by smarterclayton** [comment]
Fixed!
