### ISSUE TITLE
E2E Libraryzation:  More extensibility, possibly refactor testContext.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#19604]
**\* UPDATE **\* The original issue definition is obsolete.  I think the priority should be centering the E2E Test run functionality around testContext.

**\* ORIGINAL ISSUE **\* 
(Pauls idea, im rephrasing, correct if im missing anything) Right now, cloudConfig, reportDir, and PhodStartupTimeout are all hidden inside e2e.go (pending merge of 19476).  We'd like to make this one more step of modularity.

```
  type E2ETests struct {
      CloudConfig *CloudConfig
      ReportDir   string
      PodStartupTimeout int
  }

```

To implement i think we would need to bind  the flags to the struct fields and make sure we dont parse until after the base struct is created.

This I think could be a follow on PR to #19476 , or we could gate if we feel its a blocker.

As part of this, we should determine wether we only want CloudConfig accessible via cmd line options or not.  ReportDir and podStartupTimeout I think are straight forward.

Either way, openshift can use and consume the main portion of e2e's with or without this extensibility.

**Comment by jayunit100** [comment]
cc @pmorie.

**Comment by jayunit100** [comment]
- After thinking some more, `SetTestContext` should be able to manage this for us.
- Maybe the cmd line setter impl is flawed by design: It should be createing a struct, not modifying a global variable.   If that part was cleaned up, the extensibility would be natrual rather than imposed externally.
- that is, Im actually wondering, should testContext be a global variable, at all ?

**Comment by ixdy** [comment]
related issue: #19461

cc @kubernetes/goog-testing

**Comment by ixdy** [comment]
We need some way to pass environment info to the tests, and I think the global `testContext` is really the only way to do that.

**Comment by jayunit100** [comment]
Hmmm.. If we need that global, Maybe it would be better to create the object in e2e.go, and then use the provided `SetTestContext` function ?

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc
