### ISSUE TITLE
Cinder volume is detached from running pod.

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#19602]
There is a race between detaching a volume when an old pod is being destroyed and attaching the same volume to a new pod on the same node:

1. pod A happily uses a volume
2. pod A is deleted (and kubelet starts to clean up the stuff)
3. pod B starts, with the same volume (and kubelet starts to set it up...)

At this point, the volume is still attached to the node, kubelet is really slow when destroying it...

4. kubelet attaches the volume to the node, because pod B will need it. This does not do anything, because the volume is already attached there.
5. kubelet mounts the volume to pod B directory (which is OK)
6. kubelet unmounts the volume from pod A directory (again, OK)
7. kubelet detaches the volume from the node, because pod A is being destroyed. *This detaches the volume, while it's still mounted into pod B directory*
8. kubelet starts pod B containers -> problems.

There should be some usage counter, so kubelet just decreases "reference count'" at step 7 instead of detaching the volume. Similar approach is already present in AWS code.

@kubernetes/rh-storage

**Comment by jsafrane** [comment]
I was wrong, cinderVolumePlugint.SetUpAt() and TearDownAt() have some checks to prevent detaching of an used volume. The race is in the cinder volume plugin.

**Comment by jsafrane** [comment]
These two threads run in parallel:

```
 dying pod.TearDownAt("myVolume")          starting pod.SetUpAt("myVolume")
   |                                       |
   |                                       AttachDisk("myVolume")
   refs, err := mount.GetMountRefs()       |
   Unmount("myDir")                        |
   if refs == 1 {                          |
   |  |                                    Mount("myVolume", "myDir")
   |  |                                    |
   |  DetachDisk("myVolume")               |
   |                                       start containers - OOPS! The volume is detached!
   |
   finish the pod cleanup
```

**Comment by jsafrane** [comment]
I see very similar code in AWS EBS `SetupAt`/`TearDownAt` implementation, but I am not able to reproduce the bug there. Maybe because EBS is much faster in attaching volumes than Cinder?

**Comment by jsafrane** [comment]
Actually, most of the volume plugins probably have the same race.

@rootfs, you wrote many volume plugins, I am (randomly) looking at Ceph RBD, which has the same code flow as Cinder - can you confirm that the race is theoretically there? It's hard to reproduce though.

**Comment by markturansky** [comment]
The fencing provided by https://github.com/kubernetes/kubernetes/issues/15524 should be able to fix this race, but we also noted during discussion in Raleigh that we'll still need attach logic in Kubelet for a while.  This race would still exist for those not using the attach/detach controller.

@saad-ali

**Comment by jsafrane** [comment]
I forgot to mention that the race is between `TearDownAt()` seeing `GetMountRefs == 1`, i.e. the dying pod is the last one using the volume, before `SetupAt()` mounts the volume (which would increase `GetMountRefs` to 2, but it's too late...)

**Comment by saad-ali** [comment]
This race exists in most of the plugins because the the attach and detach code paths are triggered from two separate async loops: the pod creation loop triggers attach, and the kubelet main sync loop triggers detach (orphaned pods cleanup). Both loops are running on separate threads and unaware of what the other is doing.

I worked around this for GCE PDs by introducing locking between attach/detach; see `attachDetachMutex` in https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gce_pd/gce_util.go#L61. You could reuse that pattern here.

**Comment by jsafrane** [comment]
While GCE's `AttachAndMountDisk` is safe, it's `TearDownAt` is not. It checks how many times is a volume mounted (calls `GetMountRefs`), while the same volume can be already attached and not mounted yet by `SetUpAt` running in a separate thread.

This pattern is in all volume plugins. I'm going to add a mutex *before* `SetUp`/`TearDown` calls.

**Comment by jsafrane** [comment]
> I'm going to add a mutex before `SetUp/TearDown` calls.

That's not possible. Only the volume plugin knows the volume ID (i.e. AWS EBS VolumeID or GCE PD Name). We would have the same bug if two Kubernetes Volumes (with different `Volume.Name`) lead to the same AWS VolumeID (or GCE PD).

We can either make synchronize all `TearDown`/`SetUp` calls (i.e. they will run in sequence) or fix all volume plugins to synchronize `TearDown`/`SetUp` on the same volume (i.e. they will run mostly in parallel, unless they act on the same volume).

**Comment by jsafrane** [comment]
I posted a PR to fix this bug, but it's Cinder only. Similar changes are needed in most of  the volume plugins.

Maybe we could fix the plugins when refactoring them for the attach/detach controller.
@saad-ali @markturansky: opinions?
