### ISSUE TITLE
Build error caused by godep rewrite

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#19615]
On master right now:

```
➜  kubernetes git:(master) ✗ godep restore
➜  kubernetes git:(master) ✗ go install ./...        
# k8s.io/kubernetes/pkg/kubelet/rkt
pkg/kubelet/rkt/rkt.go:167: cannot use apisvcConn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/coreos/rkt/Godeps/_workspace/src/google.golang.org/grpc".ClientConn in argument to v1alpha.NewPublicAPIClient
```

Is there anyway to fix this so that I can build without godep go build ./...?

cc @yifan-gu

**Comment by yifan-gu** [comment]
related https://github.com/coreos/rkt/issues/1933

**Comment by yifan-gu** [comment]
cc @jonboulle @krnowak

**Comment by mikedanese** [comment]
@yifan-gu thanks

**Comment by yifan-gu** [comment]
@mikedanese Working on a fix based on https://github.com/coreos/rkt/issues/1933#issue-124629385

**Comment by DarkSkull91** [comment]
Hi @mikedanese! I'm very new in go and Kubernetes, I'm trying to modify some code but I ran in those same error... Where have I to launch that command (godep go build)? This problem comes to me when I add this to my imports "k8s.io/kubernetes/test/e2e/"

**Comment by yifan-gu** [comment]
coreos/rkt#1933 is now closed. Will update the godep for kuberentes

**Comment by mikedanese** [comment]
THanks
