### ISSUE TITLE
New docker images push breaks build/push-official-release.sh script

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#19623]
The PR #19061 added functionality to push docker images during the release, but the new workflow requires a special valentine-locked gcloud authorization to proceed.  The new workflow simply assumes the user is logged into gcloud with the k8s.production.user@gmail.com user.

We need to figure out a way to seamlessly auth and allow this new functionality to run without interrupting the release workflow.

Rolling back is an option, but preferably we could just fix this somehow.

**Comment by david-mcmahon** [comment]
This might be as simple as adjusting the ACLs for this new upload target.

**Comment by luxas** [comment]
It has already been rolled back once. Please find another solution than revert.
I guess you know, but @fgrzadkowski is away for now: https://github.com/kubernetes/kubernetes/issues/19227#issuecomment-171257268

Maybe you could assign push permissions to the `k8s.production.user`?

**Comment by fgrzadkowski** [comment]
Maybe we can just flag gate this until we have a proper fix?

**Comment by luxas** [comment]
@fgrzadkowski It's hard for me to know now if you're away or not :)

**Comment by fgrzadkowski** [comment]
@luxas I am, but I try to read the most important emails :)

**Comment by luxas** [comment]
OK, sounds good :)
