### ISSUE TITLE
Need documentation for ConfigMap

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#19620]
we have docs//proposals/configmap.md but nothing in docs/user-guide.

**Comment by erictune** [comment]
@thockin @pmorie

**Comment by therc** [comment]
I suspect #20200 will not become a real feature anytime soon, but it would be nice for the documentation to talk about the bad config issue and possible approaches.

**Comment by davidopp** [comment]
ping @pmorie - I'm going to assign this to you. This can be done as a cherrypick after the branch, though ideally before.

**Comment by pmorie** [comment]
@erictune @davidopp: somehow missed eric's tag, but I do have a WIP PR: #19782; wanted to get the volume stuff stabilized before that went in.

**Comment by davidopp** [comment]
@pmorie Now that #19782 has been merged, can we close this?

**Comment by pmorie** [comment]
@davidopp yep, this is done from #19782
