### ISSUE TITLE
1.1.4 release page doesn't publish checksums

### ISSUE THREAD

**Issue by mikem** [kubernetes/kubernetes#19635]
There are no checksums on the [v1.1.4 release page](https://github.com/kubernetes/kubernetes/releases/tag/v1.1.4) like there are on prior releases (ie: [v1.1.3](https://github.com/kubernetes/kubernetes/releases/tag/v1.1.3)).

**Comment by coleca** [comment]
There is also this bullet in the release notes which makes no sense outside of Google: 

Updated kube-ui to v4 (#18759) which fixes https://b.corp.google.com/issues/25974243 (you can easily describe the issue that was reported in that bug)

**Comment by mikedanese** [comment]
cc @david-mcmahon

**Comment by david-mcmahon** [comment]
Thanks for finding this and pointing it out.  The release page has been updated.
