### ISSUE TITLE
kubectl run --dry-run does not print object

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#19636]
This seems like a known issue (#11488, #17538) but I wanted to log this as a bug specifically because the help text is misleading.

```
$ kubectl help run
Create and run a particular image, possibly replicated.
Creates a replication controller or job to manage the created container(s).
...
Flags:
      --dry-run[=false]: If true, only print the object that would be sent, without sending it.
...
```

```
$ kubectl run --dry-run nginx --image=nginx
replicationcontroller "nginx" created
$ kubectl get rc
$
```

Replication controller is correctly not created but the object is not printed. We should either change the help text or print the object. I support the latter because I could really use the feature. :)

**Comment by nikhiljindal** [comment]
cc @janetkuo

**Comment by bgrant0607** [comment]
Doesn't seem very useful. :-)

**Comment by bgrant0607** [comment]
@ethernetdan This issue would also be useful to fix.

**Comment by sanchezpacofw** [comment]
Trying to run 
```
kubectl secret generic test --from-literal=test-url=test --dry-run
```

But it doesn't print the object, i'm only getting `secret "test" created (dry run)`
