### ISSUE TITLE
Technical debt:  refactor Kubelet.HandlePodCleanups into separate thread

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#19645]
`HandlePodCleanups` runs in the main kubelet thread and it needs to talk to API server (to find volume bound to a persistent claim, see https://github.com/kubernetes/kubernetes/pull/19600) and to cloud (to detach volumes). Both is usually fast enough, still it should be better if we refactor it to a separate thread and not block the main one.

**Comment by AdoHe** [comment]
@jsafrane even the `HandlePodCleanups` is executed in the main sync loop, but if it has no block call, I think this is ok. Of course we have to evaluate this.

**Comment by saad-ali** [comment]
Thanks for opening the issue, this definitely needs cleanup.

Cloud calls, in particular, can sometimes take a very long time. Which is why I put the GCE PD detach on a separate thread.

**Comment by resouer** [comment]
@yujuhong I think this needs a clean up. After we supported remote container runtime, even `GetPods(false)` can become a blocking call, we have encountered this once when using hyper. 

But not quite sure about the potential data race in `HandlePodCleanups`, any tips?

**Comment by yujuhong** [comment]
@resouer, @saad-ali has already moved volume related code to a separate volume manager, so the `HandlePodCleanups` function no longer handles volumes/PD, neither does it talk to the apiserver. That was the heaviest operation that the cleanup function did. 

I think the main race condition that may happen is described in https://github.com/kubernetes/kubernetes/issues/13418#issuecomment-183146070.

**Comment by saad-ali** [comment]
Yep, we can close this issue.
