### ISSUE TITLE
Kubelet: Introduce jitter on all interval stats and checks. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#19655]
In profiling the kubelet and mapping the data, we see cpu spikes on housekeeping intervals.

Same technique can apply in all cases, xref: https://github.com/google/cadvisor/issues/1053

/cc @kubernetes/sig-node @jimmidyson @ncdc @jeremyeder

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by pmorie** [comment]
@ingvagabund and I spoke to @timothysc about this earlier.  Tim mentioned that a pattern to follow is the one the proxy uses.

**Comment by timothysc** [comment]
Also see in leaderelection.go using wait.Jitter.

**Comment by timothysc** [comment]
I think this issue is moot with https://github.com/kubernetes/kubernetes/pull/19436 in.  

cpu profile is drastically different, closing and will reopen if needed.

**Comment by ingvagabund** [comment]
https://github.com/kubernetes/kubernetes/pull/19917

**Comment by timothysc** [comment]
I'll leave this open until patches are merged, I think @ingvagabund is on the right track.

**Comment by yujuhong** [comment]
@timothysc, #20726 has been merged. Have you seen any difference in your measurement?

**Comment by timothysc** [comment]
We have to wait on our rebase, or ask @jeremyeder really nicely.

**Comment by jeremyeder** [comment]
@yujuhong gear's tied up.  What is the deadline for results...can it wait a week?

**Comment by yujuhong** [comment]
@jeremyeder, sure. Let's keep this issue open while waiting for the update. I assigned the issue to you so that it'd be easier to find. Thanks!

**Comment by jeremyeder** [comment]
@yujuhong @timothysc here you go.

It submits 40 creates, waits for all of them to be fully running, then waits 180 seconds, then submits another 40, up to 240 total.  The bumps that appear every 180 seconds are when the test submits 40 pod-create operations.  The larger bump at the end is when the test deletes the entire namespace.

Here's the data from OpenShift 3.1 (note the Y-axis).

Before:
![node-cpu-3 1](https://cloud.githubusercontent.com/assets/1919640/13506546/9f3db080-e14c-11e5-8c2f-76b570504489.png)

And here it is from OpenShift 3.2 (OpenShift 3.1.1.908 is internal build number that contains up through kubernetesv1.2.0-alpha.7-703).

After:
![node-cpu](https://cloud.githubusercontent.com/assets/1919640/13506545/9f3a3e78-e14c-11e5-9451-a4807db07611.png)

I think the most telling part about this for me is that if you look at timestamps 12:10 and 12:12 of the second graph, there's not much difference anymore.  Very positive results, thanks to all the folks involved in PLEG and additional caches that were added (pr17545 seems to have been the biggest win.

- A 4x reduction in CPU used by the node daemons to run 120 pods.
- Also a 4x reduction in memory used by the node daemons as well.

Here's another visualization of the same data:
![ose_cpu](https://cloud.githubusercontent.com/assets/1919640/13506868/0aff3fea-e14e-11e5-89bd-15c212a39892.png)
![ose_memory](https://cloud.githubusercontent.com/assets/1919640/13506869/0b61273c-e14e-11e5-8a9f-28e08437853e.png)

P.S. we are trying to open source all this test code, it's progressing but not ready yet, sorry.

**Comment by timothysc** [comment]
Going to call this one done!

**Comment by yujuhong** [comment]
@jeremyeder, thanks for sharing the numbers/graphs! Looking forward to trying out the test code when it's available!
