### ISSUE TITLE
labels.SelectorFromSet does not match described behaviour of nil

### ISSUE THREAD

**Issue by paulbellamy** [kubernetes/kubernetes#19654]
The documentation of `k8s.io/kubernetes/pkg/labels.SelectorFromSet` says

> A nil and empty Sets are considered equivalent to Everything().

However, from the documentation on (Services without selectors)[http://kubernetes.io/v1.1/docs/user-guide/services.html#services-without-selectors], I would expect `labels.SelectorFromSet(labels.Set(nil))` to behave the same as `labels.Nothing()`

**Comment by bgrant0607** [comment]
Services without selectors just don't use the selector. Endpoints are populated via a different mechanism. We've been discussing other ways to specify that (#18610), for multiple reasons. It is pretty obscure.

We don't expect users to read our code documentation, though. :-)

The meaning of nil vs. empty has come up in other contexts, though.

cc @davidopp

**Comment by paulbellamy** [comment]
For context, this came up when I was using `k8s.io/kubernetes/pkg/api` (with the client) to gather some stats about the cluster and was surprised when `labels.SelectorFromSet(labels.Set(service.Spec.Selector))` matched all pods when service was the `kubernetes` service.
