### ISSUE TITLE
Ubuntu 15.10 support

### ISSUE THREAD

**Issue by codablock** [kubernetes/kubernetes#19653]
Hello,

are there any plans to support Ubuntu 15.10 with kube-up.sh in the future? 
@resouer as I see you are the current maintainer of the Ubuntu cluster code, do you still maintain it?

If noone is working on it right now, I may work on this and provide a PR in the future.

Alex.

**Comment by dalanlan** [comment]
We have no plan to touch ubuntu 15.10  to my best knowledge.
Feel free to send a pr. 
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu-calico.md may help though.
/cc @djosborne

**Comment by codablock** [comment]
Can be closed IMHO as we are not using 15.10 anymore.
