### ISSUE TITLE
kubelet: overlapping operations, settling time is too l...o...n...g...

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#19660]
In hunting down a goroutine leak #19633 I was able to consistently create a situation where the overall settling time for a declarative change was far too high imho.  

```
$ sudo ./hack/local-up-cluster.sh 
$ submit single pause with replica of 1
<wait until pod is running>
$ kubectl scale --replicas=50 rc/wide-pause
<wait till kubelets starts pods> 
$ kubectl scale --replicas=1 rc/wide-pause
<wait till kubelets starts terminating pods> 
$  kubectl scale --replicas=100 rc/wide-pause
<notice overlap, total pod count over 100> 
```

From there, the settling time to achieve 100 pods on a node > 20 minutes on average and was reproduced on two different environments as mentioned in the other issue. 

/cc @kubernetes/sig-node @kubernetes/sig-scalability @ncdc @jeremyeder

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by yujuhong** [comment]
Because you overlapped the operations, kubelet would have accumulated more pod statuses to report and pods to terminate.
 - replicas=50
 - replicas=1
    * kubelet needs to terminate 49 pods 
 - replicas=100
    * kubelet needs to start and report the status of 100 pods 

Termination of pods, especially, is expensive because of multiple statuses to report before the final deletion (see https://github.com/kubernetes/kubernetes/issues/18266#issuecomment-162715856).
Due to the overlapping overlapping operations, kubelet is likely to be limited by the QPS limit (5.0) of the apiserver client (see #14955) and appear to be very slow. This is a cluster-wide problem because we can't arbitrarily increase the QPS limit.

**Comment by timothysc** [comment]
@yujuhong if the QPS is limited, why wouldn't we also limit the number of operations that can occur so it isn't stuck in a backlog.

**Comment by yujuhong** [comment]
> @yujuhong if the QPS is limited, why wouldn't we also limit the number of operations that can occur so it isn't stuck in a backlog.

Do you mean that we should limit the update rate per pod in kubelet, or reduce the number of updates required per pod? 
I think the latter will mitigate the problem a bit, at the cost of clarity for introspection. Ultimately the #updates will grow as the #pods involved increases, and the current QPS limit doesn't hold up well during batch operations like these. 

That said, I am aware of a bug that would cause more QPS to be wasted on deleted pods during batch deletion. I have a semi-fix that I'll probably upload sometime next week.

**Comment by timothysc** [comment]
@yujuhong - I'm still pretty struct that even with a low qps it takes so long, there is only one node in this experiment.  Just how much data are are trying to send back<>forth?

**Comment by yujuhong** [comment]
@timothysc, is the 20 minute the latency of the last step, or the time takes to run through all the operations?

**Comment by yujuhong** [comment]
1 `kubectl scale --replicas=50` and wait until all the pods are running and ready
2 `kubectl scale --replicas=0` wait 3 seconds or so.
3 `kubectl scale --replicas=100`

Step 3 alone takes about 130s even though kubelet was still terminating pods from 2.
It'd be great If you have a script that I can run to reproduce the problem.

**Comment by timothysc** [comment]
@yujuhong the 20 minute latency was from the last operation.

**Comment by timothysc** [comment]
I believe https://github.com/kubernetes/kubernetes/issues/19801 is related.

**Comment by timothysc** [comment]
Fix happened a long time ago, closing.
