### ISSUE TITLE
Services should work after restarting kube-proxy failing on GKE

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19665]
**Services should work after restarting kube-proxy [Disruptive]**

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:311 Expected error: <*errors.errorString | 0xc20886dec0>: { s: "service verification failed for:\n 10.227.248.83, expected to retrieve pods [service1-6gwp1 service1-gdg5b service1-vtnfq], only retrieved [service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1]", } service verification failed for: 10.227.248.83, expected to retrieve pods [service1-6gwp1 service1-gdg5b service1-vtnfq], only retrieved [service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1 service1-6gwp1] not to have occurred

E.g.:

- http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-ci-reboot/6310/
- http://kubekins.dls.corp.google.com/view/GKE/job/kubernetes-e2e-gke-ci-reboot/6311/

**Comment by bprashanth** [comment]
Noted https://github.com/kubernetes/kubernetes/issues/19666 though I'm not sure they're related

**Comment by bprashanth** [comment]
Ok we should grab the following: 
https://github.com/kubernetes/kubernetes/pull/19493
https://github.com/kubernetes/kubernetes/pull/17741
https://github.com/kubernetes/kubernetes/pull/19668

I suspect that right after the reboot test the node is either not yet really ready, kube-proxy is not yet really up (i.e node reboot took < 5m), or the kubelet restarted and caused some other form of delay. Too many unknowns right now.

**Comment by bprashanth** [comment]
This is actually pretty stable now, I went through gke-ci results and the times it's flaked a lot of other tests have also failed indicating a deeper issue. It failed in gce-slow recently (http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-slow/1572/consoleFull) but that's because a node didn't come up, and that's probably being handled via reboot test.

@kubernetes/goog-cluster closing for now, we got a couple of fixes into https://github.com/kubernetes/kubernetes/issues/19665#issuecomment-171791565, reopen if it comes back
