### ISSUE TITLE
Empty responses from AWS when running `kube-down.sh`

### ISSUE THREAD

**Issue by mikem** [kubernetes/kubernetes#19684]
I can't bring a cluster down on AWS:

```
$ KUBERNETES_PROVIDER=aws cluster/kube-down.sh
Bringing down cluster using provider: aws
Done
```

Digging in to `cluster/aws/util.sh` I see that it's failing to retrieve the VPC ID. Adding some debugging (see patch below) and running `kube-down.sh` I see:

```
$ KUBERNETES_PROVIDER=aws cluster/kube-down.sh
Bringing down cluster using provider: aws
++ get_vpc_id
++ aws ec2 describe-vpcs --filters Name=tag:Name,Values=kubernetes-vpc Name=tag:KubernetesCluster,Values=kubernetes --query 'Vpcs[].VpcId'
+ local vpc_id=
+ echo '===> vpc_id: '
===> vpc_id:
+ set +x
```

Copy and pasting the command into the terminal myself gets me the VPC ID:

```
$ aws ec2 describe-vpcs --filters Name=tag:Name,Values=kubernetes-vpc Name=tag:KubernetesCluster,Values=kubernetes --query 'Vpcs[].VpcId'
[
    "vpc-XXXXXXXX"
]
```

I added the `--debug` flag to the `aws` commands and re-ran `kube-down.sh`. The XML response in the debug logs looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<DescribeVpcsResponse xmlns="http://ec2.amazonaws.com/doc/2015-10-01/">
    <requestId>4585ed82-6199-4f4b-948b-e1c41ea0ddb8</requestId>
    <vpcSet/>
</DescribeVpcsResponse>
```

The `vpcSet` in the XML response is not empty when I run this command myself.

---

These are the changes I made to `cluster/aws/util.sh` to get some debugging going:

```diff
diff --git a/cluster/aws/util.sh b/cluster/aws/util.sh
index b34f1ba..fd9340e 100755
--- a/cluster/aws/util.sh
+++ b/cluster/aws/util.sh
@@ -1178,7 +1178,11 @@ function check-cluster() {
 }

 function kube-down {
+  set -x
   local vpc_id=$(get_vpc_id)
+  echo "===> vpc_id: ${vpc_id}"
+  set +x
+  exit 0
   if [[ -n "${vpc_id}" ]]; then
     local elb_ids=$(get_elbs_in_vpc ${vpc_id})
     if [[ -n "${elb_ids}" ]]; then
```

**Comment by mikem** [comment]
This appears to be consistent for other calls to AWS. The next command, which tries to get the ELBs in the VPC also fails in the same way.

**Comment by justinsb** [comment]
In `cluster/aws/util.sh`, we do this:

```
AWS_REGION=${ZONE%?}

export AWS_DEFAULT_REGION=${AWS_REGION}
export AWS_DEFAULT_OUTPUT=text
```

So kube-up is looking at the region in ZONE.  ZONE is set in config-default.sh to `ZONE=${KUBE_AWS_ZONE:-us-west-2a}`

@mikem Can you please double-check that the AWS_DEFAULT_REGION/AWS_REGION in your shell is set consistently with KUBE_AWS_ZONE.  (Essentially, I'm guessing you're looking at a different region - this happens to me all the time...!)

**Comment by mikem** [comment]
@justinsb you nailed it, that's the issue. When I run the command manually there's no `AWS_DEFAULT_REGION` set and it defaults to `ap-southeast-1` (maybe they do IP geo-location). When running `cluster/kube-down.sh` the region becomes `us-west-2a` as you pointed out, and the VPC is not found.

Closing this issue.

**Comment by kant111** [comment]
I have VPC_ID set as environment variable. the kube-down script looks like it is not taking the existing VPC_ID into account and I fear  this will actually delete the existing VPC?
