### ISSUE TITLE
Update kr/pty Godep for arm64 building

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#19709]
My work ref: #17981

This `Godep` is over a year old: 
```
{
    "ImportPath": "github.com/kr/pty",
    "Comment": "release.r56-25-g05017fc",
    "Rev": "05017fcccf23c823bfdea560dcc958a136e54fb7"
},
```

It prevents building on ARM64 which I am adding support for right now.
Can we update this one to a newer version? Latest commit is kr/pty@f7ee69f31298ecbe5d2b349c711e2547a617d398 and it compiles on `ARM64`

Will test to build master Kubernetes with master pty.
@thockin @brendandburns @mikedanese @fgrzadkowski @vishh @jimmidyson @wojtek-t

**Comment by mikedanese** [comment]
Updating to newest version SGTM. Maybe it will fix vim in kubectl exec :)

**Comment by luxas** [comment]
Can you do it now or should I try to make a PR? (Haven't updated Godeps before)

**Comment by mikedanese** [comment]
I can do it if you prefer
