### ISSUE TITLE
Load Balancer: cannot specify security group to use, always creates new one

### ISSUE THREAD

**Issue by jwonesh** [kubernetes/kubernetes#19704]
Hello,

I have been looking into ways to specify an existing security group for the ELB to use, but have found that is not possible. I examined the API (https://github.com/kubernetes/kubernetes/blob/37b5726716231c13117c4b05a841e00417b92cda/pkg/cloudprovider/providers/aws/aws.go) and I see that a new security group is created when the ELB is created in EnsureLoadBalancer. AWS CLI has a flag for specifying security group upon creation:

  create-load-balancer
--load-balancer-name <value>
--listeners <value>
[--security-groups <value>]

It would be very nice to have this functionality, as we will be dynamically creating ELBs as needed, and we do not want to have to go in and change the security group associated with the ELB every time it is created.

**Comment by mgoodness** [comment]
This seems similar to [#14504](https://github.com/kubernetes/kubernetes/issues/14504). It would be awfully nice if we could create an appropriately-tagged security group, assign it to worker nodes, and have Kubernetes-created ELBs use it.

As it stands, Kubernetes creates its own SGs and attaches them to an arbitrary existing SG (call it SG1). This is troublesome when using Terraform, as it wants to revert SG1 to its original state by removing the K8s-created SGs.

**Comment by justinsb** [comment]
@jwonesh Why do you want to create your own security-group?  We now let you configure the permitted source-ip ranges - does this cover the requirement?

@mgoodness not sure what to say about those terraform limitations.  We now modify the ELB security group to support the source-ip range configuration, so we'll have the same problem there.  Is there a way to tell terraform to ignore certain changes after creation?

**Comment by stevenjack** [comment]
@mgoodness 👍  

@justinsb Have run into the same issue with terraform here. Would be great if we could tell kubernetes what security group to assign the ELB's to rather than it creating its own, terraform only wants to manage the state of resources it's created.

**Comment by mgoodness** [comment]
@justinsb that is what I ultimately did, by adding a `lifecycle { ignore_changes = ["ingress"] }` statement to my kubernetes-workers SG. It's also the only SG tagged with `KubernetesCluster = <clusterName>` assigned to the workers, making the process much more predictable.

The only downside is that Terraform now ignores ingress rule changes I make. That's not a common occurrence, though, and is easy enough to work around. I'm generally pleased with the current behavior.

**Comment by activars** [comment]
@justinsb Where can I find the documentation for the ELB `source-ip` configuration?

**Comment by timstoop** [comment]
@activars I had a search for that as well, apparantly you can now use ```loadBalancerSourceRanges``` in Service definitions for supported cloud providers. Mentioning it here as I found this issue about 45 minutes before I found a reference to ```loadBalancerSourceRanges```. There's nothing about it in the docs yet, but I found an explanation here: http://stackoverflow.com/questions/38360125/how-do-i-restrict-access-to-kubernetes-service

Hope this helps.

**Comment by ryan-dyer-sp** [comment]
I believe this is still an issue and the ability to add an IP whitelist is not entirely feasible.  For example we have a couple dozen IPs that make up our corporate IP whitelist.  Adding these dozens to every kubernetes definition file for all of our various services and then needing to update all of these files and re-apply them when we receive an IP addition/change/etc is not very manageable.  It makes more sense to have a single SG that contains this list that we can update via terraform from a single file and specify this security group within the kube definition files.

/reopen
/remove-lifecycle rotten
