### ISSUE TITLE
Load Balancer: name is tied to service UID, so state cannot be preserved upon cluster restart

### ISSUE THREAD

**Issue by jwonesh** [kubernetes/kubernetes#19705]
Hello,

I have been trying to figure out a way to preserve ELBs across cluster restarts. I need this functionality because we map dns names to ELB aliases via Route 53. We have a load balancer that points to the mapped dns name which does not change. However, AWS creates a new DNS for each ELB it creates. So, if the cluster were to be torn down and started up again, the new ELBs created would have new DNS names that are not mapped by Route 53. This means that we would have to manually change the resource record every time the ELB is recreated.

I will give some background on why this functionality is needed. I have a need to preserve VPC and Security Groups (as well as ELBs) across cluster restarts. I have been able to achieve this by removing the code from kube-down.sh that deletes the corresponding resources. This works fine, as kube-up.sh is able to detect the already-existing resources on startup and initialize correctly. As would be expected, the ELBs do not register with the newly created minions. In attempting to resolve this, I discovered it was impossible due to the issue described earlier. Even if I were to use AWS CLI commands to register new minions on start-up with existing ELBs, the Kube API would not have knowledge of these existing ELBS, as they are tied to service UIDs that no longer exist. This is why I need the ability to bind ELB names to service names. Since services are unique in Kube API anyway, this should not present an issue when trying to create another instance of the LoadBalancer service.

For reference, the name is set in GetLoadBalancerName in : https://github.com/kubernetes/kubernetes/blob/37b5726716231c13117c4b05a841e00417b92cda/pkg/cloudprovider/cloud.go

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by thockin** [comment]
This is over a year old.  There's an effort underway to de-centralize cloud-providers, so I am closing this in favor of that.
