### ISSUE TITLE
Flake: Density [Skipped] [Performance] should allow starting 30 pods per node

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#19711]
Failed twice in the last two days.

	
Density [Skipped] [Performance] should allow starting 30 pods per node

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:130 There should be no high-latency requests Expected : 1 not to be > : 0

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4024/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4006/

**Comment by Random-Liu** [comment]
It seems that the second one is load capacity test. :)

**Comment by mikedanese** [comment]
Ooops. Could they be related?

**Comment by Random-Liu** [comment]
I've no idea, either. :(

**Comment by mikedanese** [comment]
And again two more times:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4025/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4028/
cc @bprashanth @kubernetes/goog-control-plane

**Comment by mikedanese** [comment]
#19743 to stop the bleeding

**Comment by gmarek** [comment]
@mikedanese - if both of them are failing it's a strong signal for regression. They produce different pattern of loads.

**Comment by gmarek** [comment]
It was regression caused by update of goversion to 1.4.3. Fixed by #19847

**Comment by wojtek-t** [comment]
Great debugging BTW.

**Comment by davidopp** [comment]
+1 -- thanks for all of your consistent work on fixing test, Marek, even when we are not in a test fixit!
