### ISSUE TITLE
Broken link: Kubectl API Reference in kubernetes.io/docs

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#19721]
1. Open http://kubernetes.io/v1.0/docs/api-reference/definitions.html (or http://kubernetes.io/v1.0/docs/api-reference/operations.html)
2. Click on "View the latest version here."
3. It brings you to http://kubernetes.io/v1.1/docs/api-reference/definitions.html (404 not found). However the link should be http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
I thought it was an straight-forward bug, but it's not. I'll talk to @timstclair to see if he can help.

**Comment by bgrant0607** [comment]
Obsolete
