### ISSUE TITLE
Upload structured metadata to GCS at beginning and end of all Jenkins test jobs

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#19727]
At the start of every E2E or unit test run, I would like to upload a file to GCS that says "This job started running at this time using this version of kubernetes." Something like this:
```json
{
    "version": "v1.2.0-alpha.6.204+810544633e3c12",
    "timestamp": 1234567890
}
```

Then, at the end of the job, I would like to upload another report:
```json
{
    "timestamp": 123470000,
    "result": "SUCCESS"
}
```

This info can be paired with the JUnit artifacts we already upload to get a more complete picture of our Jenkins runs.

@ixdy how does this sound? Know of any issues I'll run into?

**Comment by ixdy** [comment]
[We already sorta do this](https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/upload-to-gcs.sh#L74-L79), though that file is more used to find the latest build, rather than save information on every build.

Seems like a reasonable idea in any case.

**Comment by spxtr** [comment]
Done.
