### ISSUE TITLE
Services e2e tests require different output between 1.1 and HEAD

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19723]
**Services should prevent NodePort collisions**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:639 Expected : Service "nodeport-collision-2" is invalid: spec.ports[0].nodePort: Invalid value: 31108: provided port is already allocated to equal : Service "nodeport-collision-2" is invalid: spec.ports[0].nodePort:
invalid value '31108', Details: provided port is already allocated*

**Services should check NodePort out-of-range**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:705 Expected : Service "nodeport-range-test" is invalid: spec.ports[0].nodePort: Invalid value: 26176: provided port is not in the valid range to equal : Service "nodeport-range-test" is invalid: spec.ports[0].nodePort: invalid value '26176', Details: provided port is not in the valid range*

This is just caused by the error messages changing:

> Invalid value: 31108: provided port is already allocated

vs.

> invalid value '31108', Details: provided port is already allocated

@kubernetes/kube-api Do we care?

**Comment by bgrant0607** [comment]
We have to be allowed to change/improve error messages in order to improve user experience. e2e tests shouldn't be testing for error strings, IMO.

**Comment by bgrant0607** [comment]
cc @kubernetes/goog-cluster
