### ISSUE TITLE
Change from "scheduler" to "default-scheduler" breaks backwards compatibility with e2es

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19724]
**SchedulerPredicates validates that NodeSelector is respected [Conformance]**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:389 Expected <[]api.Event | len:0, cap:0>: [] not to be empty*

**SchedulerPredicates validates resource limits of pods that are allowed to run [Conformance]**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:349 Expected <[]api.Event | len:0, cap:0>: [] not to be empty*

Investigating...

**Comment by ihmccreery** [comment]
Looks suspiciously similar to #15806.

Between 1.0 and HEAD, we also see:

**MaxPods Validates MaxPods limit number of pods that are allowed to run.**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/max_pods.go:174 Expected <[]api.Event | len:0, cap:0>: [] not to be empty*

Which is identical to #15806.

**Comment by ihmccreery** [comment]
This is also almost certainly linked to a similar failure, also in 1.1 and HEAD:

**Events should be sent by kubelets and the scheduler about pods scheduling and running [Conformance]**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/events.go:127 Expected error: <*errors.errorString | 0xc2080faa10>: { s: "timed out waiting for the condition", } timed out waiting for the condition not to have occurred*

That test [polls until the list of events is nonempty](https://github.com/kubernetes/kubernetes/blob/release-1.1/test/e2e/events.go#L87).

**Comment by ihmccreery** [comment]
Note that these failures occur as soon as a master is upgraded, even if the nodes haven't yet been upgraded.

**Comment by ihmccreery** [comment]
It looks like Events are now listed under `"default-scheduler"`: #17865 was the original backward-incompatible change, and #19009 fixed the e2e tests.

@kubernetes/kube-api I assume this isn't considered a breaking API change, so I will prepare a PR to make the tests forward-compatible, unless I hear otherwise.

**Comment by ihmccreery** [comment]
Or, is there any reason we can't just call the default scheduler "scheduler", like we had before, to maintain backwards-compatibility?

**Comment by ihmccreery** [comment]
Confirmed that **Events..** and **MaxPods...** (in 1.0) are suffering from the same problem.

**Comment by bgrant0607** [comment]
First, specific events don't have the guarantee of API stability. Not a breaking change. I know people want to depend on this, but I don't want them to. Think of it like a log message. It's for users, not for programs.

In this specific case, I wasn't aware of the change and would be fine with reverting it.

cc @davidopp

**Comment by ihmccreery** [comment]
@kubernetes/goog-control-plane How would you all feel about changing the default scheduler name back to "scheduler"?

**Comment by gmarek** [comment]
cc @davidopp.

We can probably rewrite this test to use things that are now present in PodStatus (or somewhere). At the time I was writing it only source of information about failedScheduling were Events. I'm not sure how high the priority for such rewrite would be, but I'd rather keep this test running, as it already pointed us to few bugs.

**Comment by davidopp** [comment]
Thanks a lot for the debugging, Ike.

As you might guess, "scheduler" is not a good name for any scheduler in a system with multiple schedulers. They're all the scheduler.

The problem with changing the name of the default scheduler to "scheduler" is that the default scheduler name *is* part of the API (it's defined in v1/types.go, on recommendation for Clayton) so it's not really possible to change it until the v2 API, and who knows when that's coming. So we'd be making a long-term commitment to calling the default scheduler "scheduler."

If there is absolutely no other reasonable choice, then this is OK, but it would be better to fix the tests. Events in general are not part of the API as Brian said, so relying on whatever we used to emit wasn't really the right thing to do.

cc/ @HaiyangDING

**Comment by gmarek** [comment]
It was the only thing possible at that moment:). The question is: do we want to rewrite this test now, as more data is available in Pods objects.

**Comment by davidopp** [comment]
If we can do it in a reasonable amount of time and someone is available to do it, then I would say yes.

**Comment by mikedanese** [comment]
Can we just submit a fix to the release1.0 branch that s/scheduler/default scheduler/? I think the more robust fix can probably wait

**Comment by ihmccreery** [comment]
> The problem with changing the name of the default scheduler to "scheduler" is that the default scheduler name is part of the API (it's defined in v1/types.go, on recommendation for Clayton) so it's not really possible to change it until the v2 API, and who knows when that's coming.

Was the name "scheduler" not part of the API before it got changed to "default-scheduler"?

> Can we just submit a fix to the release1.0 branch that s/scheduler/default scheduler/? I think the more robust fix can probably wait

That'd be a backwards-incompatible change on a patch version within 1.0, which sounds very questionable to me.

If we want to keep it at "default-scheduler", which seems reasonable to me, then I can pursue a forward-compatible test fix (or something).

**Comment by mikedanese** [comment]
> That'd be a backwards-incompatible change on a patch version within 1.0, which sounds very questionable to me.
> 
> If we want to keep it at "default-scheduler", which seems reasonable to me, then I can pursue a forward-compatible test fix (or something).

I meant we should s/scheduler/default scheduler/ when matching the event in the e2e test. No changes outside of test/. This is a smaller change than the one propsed by @gmarek:

> We can probably rewrite this test to use things that are now present in PodStatus (or somewhere). At the time I was writing it only source of information about failedScheduling were Events. I'm not sure how high the priority for such rewrite would be, but I'd rather keep this test running, as it already pointed us to few bugs.

@ihmccreery if that was already understood can you explain why it's a backwards-incompatible and questionable fix?

**Comment by mikedanese** [comment]
I say this having not looked at the test... We have modified tests in old release branches to match new and old outputs. I think that's what we should do here.

**Comment by ihmccreery** [comment]
@mikedanese Sorry I misunderstood; I thought you were proposing we rename the 1.0 scheduler from "scheduler" to "default-scheduler" to match newer versions.  If you're just talking about fixing the tests, I think that's the right thing to do.

**Comment by ihmccreery** [comment]
> Was the name "scheduler" not part of the API before it got changed to "default-scheduler"?

As long as the answer to that question is "no".

**Comment by davidopp** [comment]
The scheduler didn't have a name in 1.0. We just chose to use "scheduler" in the event.

The multi-scheduler feature added the concept of scheduler name, made it part of the API, and put the name in the event.

**Comment by spiffxp** [comment]
>First, specific events don't have the guarantee of API stability. Not a breaking change. I know people want to depend on this, but I don't want them to. Think of it like a log message. It's for users, not for programs.

@bgrant0607 I agree, except the conformance tests rely on events.  So, implicitly, a cluster has to have events coming from certain named sources to be conformant.  If the tests shouldn't be relying on events, what should they be using instead?

@davidopp what's the proposed strategy for dealing with this in a multi-scheduler world?  I'd like some way to validate that a kubernetes cluster with a set of non-default schedulers still acts conformant

**Comment by spiffxp** [comment]
eg: at the moment, the mesos scheduler sets itself up with the name "default-scheduler" to appear conformant as well, which doesn't seem quite right 

https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/pkg/scheduler/service/service.go#L795

**Comment by mikedanese** [comment]
The [test](https://github.com/kubernetes/kubernetes/blob/release-1.1/test/e2e/events.go#L37) in question just seems completely broken. If we want to conformance tests events, we should define an event in the test, emit it through an event recorder, and observe it in the API.

**Comment by ihmccreery** [comment]
If events aren't part of the API, why would we want a conformance test around them?

I'm more concerned about the SchedulerPredicates test which probably should be a conformance test, but also relies on `api.DefaultSchedulerName`.

Perhaps that test should be allowed to somehow specify what scheduler it cares about?  Or we should decouple it from events entirely?

**Comment by ihmccreery** [comment]
I'm focusing on making our old tests forward-compatible with this change, but that won't help with conformance going forward.  @spiffxp do you have a serious need for the v1.1 conformance tests working, or can we fix v1.2 and call it good?  (We can consider a fix-and-backport if necessary.)

**Comment by mikedanese** [comment]
I'd say that "events" are part of the api (they have a resource and a type in pkg/api/types.go). It's probably good to check that the events mechanism is working in a conformance tests. However the behavior that a specific event being omitted with a specific format when a specific thing occurs is not part of the api and should not be relied on in e2e tests. Does that make sense?

**Comment by mikedanese** [comment]
> If the tests shouldn't be relying on events, what should they be using instead?

Conformance tests should assert the expected state of the system (which coincidentally has a stable api), not that a particular log message was emitted.

> what's the proposed strategy for dealing with this in a multi-scheduler world

https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/multiple-schedulers.md

**Comment by spiffxp** [comment]
@mikedanese agreed, but I honestly don't know... is there a non-event mechanism to measure pod scheduling latency?

**Comment by mikedanese** [comment]
Ya it's tricky, you can observe the prometheus handler but that's not a stable api either.

**Comment by spiffxp** [comment]
@mikedanese and regarding the proposal, it specifically says nothing about events... I as a consumer of kubernetes' API would want some way to know when my pod has been scheduled, regardless of which scheduler actually made the decision

**Comment by spiffxp** [comment]
@ihmccreery fix-and-backport sounds good to me, end goal is "v1.1 conformance passes on v1.1 and v1.2 clusters"

**Comment by mikedanese** [comment]
You can observe that the nodeName in podspec gets set

**Comment by bgrant0607** [comment]
@mikedanese is correct.

The problem is that we don't have a document that describes how e2e tests should be written, so people have written brittle tests that test the implementation, not actual conformance. (A doc is in progress: #20041)

**Comment by gmarek** [comment]
@bgrant0607 a lot of e2e tests were written before 1.0, when API wasn't as rich as it is today. Are you suggesting that we should put engineering effort in rewriting those?

**Comment by bgrant0607** [comment]
@gmarek Yes, or replace them, or accept that they'll break at some point.

At minimum, we should establish clear guidance for tests that have yet to be written.

**Comment by gmarek** [comment]
I generally agree, but someone should sign under spending nontrivial amount of engineering effort to have this done.

**Comment by ihmccreery** [comment]
Fixed #19724 via #20740.
