### ISSUE TITLE
1.1 e2es can't verify services on a HEAD cluster

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19729]
**Services should be able to up and down services**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:254 Expected error: <*errors.errorString | 0xc208695290>: { s: "service verification failed for:\n set -e;\n\t\t\tsudo docker pull gcr.io/google_containers/busybox > /dev/null;\n\t\t\tsudo docker run gcr.io/google_containers/busybox sh -c 'for i in $(seq 1 9); do wget -q -T 1 -O - http://10.183.252.169:80 || true; echo; done' | sort -n | uniq", } service verification failed for: set -e; sudo docker pull gcr.io/google_containers/busybox > /dev/null; sudo docker run gcr.io/google_containers/busybox sh -c 'for i in $(seq 1 9); do wget -q -T 1 -O - http://10.183.252.169:80 || true; echo; done' | sort -n | uniq not to have occurred*

**Services should work after restarting kube-proxy**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:304 Expected error: <*errors.errorString | 0xc208269ee0>: { s: "service verification failed for:\n set -e;\n\t\t\tsudo docker pull gcr.io/google_containers/busybox > /dev/null;\n\t\t\tsudo docker run gcr.io/google_containers/busybox sh -c 'for i in $(seq 1 9); do wget -q -T 1 -O - http://10.183.241.162:80 || true; echo; done' | sort -n | uniq", } service verification failed for: set -e; sudo docker pull gcr.io/google_containers/busybox > /dev/null; sudo docker run gcr.io/google_containers/busybox sh -c 'for i in $(seq 1 9); do wget -q -T 1 -O - http://10.183.241.162:80 || true; echo; done' | sort -n | uniq not to have occurred*

Note this only occurs after the nodes have been upgraded to HEAD, not when the master is at HEAD and the nodes are still at 1.1.

Looks like [verifyServeHostnameServiceUp](https://github.com/kubernetes/kubernetes/blob/release-1.1/test/e2e/service.go#L1284) is failing.

Investigating...

**Comment by ihmccreery** [comment]
This also fails when running HEAD tests on a cluster that's been upgraded, which tells me it's an upgrade problem, not a version-skew problem:

**Services should work after restarting kube-proxy [Disruptive]**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:311 Expected error: <*errors.errorString | 0xc2089df300>: { s: "service verification failed for:\n 10.183.242.9, expected to retrieve pods [service1-49s4o service1-sxx0j service1-u6xs3], only retrieved [service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o]", } service verification failed for: 10.183.242.9, expected to retrieve pods [service1-49s4o service1-sxx0j service1-u6xs3], only retrieved [service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-49s4o service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-u6xs3 service1-49s4o service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-u6xs3 service1-49s4o service1-u6xs3 service1-49s4o] not to have occurred*

**Services should be able to up and down services**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:260 Expected error: <*errors.errorString | 0xc208e35c20>: { s: "service verification failed for:\n 10.183.245.120, expected to retrieve pods [service1-63l2u service1-8zaxq service1-hllvg], only retrieved [service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg]", } service verification failed for: 10.183.245.120, expected to retrieve pods [service1-63l2u service1-8zaxq service1-hllvg], only retrieved [service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-hllvg service1-hllvg service1-8zaxq service1-8zaxq service1-hllvg service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-hllvg service1-8zaxq service1-8zaxq service1-8zaxq service1-8zaxq service1-hllvg] not to have occurred*

**Comment by davidopp** [comment]
cc/ @thockin

**Comment by thockin** [comment]
Like many of these reports - there is not enough log here to do anything with.  Error messages in this area have already been improved this week.  Can wee get a re-run?

**Comment by ihmccreery** [comment]
Runs are here:

- http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step4-e2e-old/ (with nodes still at 1.1)
- http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step6-e2e-old/ (after nodes are upgraded)

**Comment by thockin** [comment]
The restart kube-proxy failure is because we changed the way the proxy is
run (now it is a docker image).  I can send a patch to 1.1 e2e, but it's a
little fugly.

**Comment by ihmccreery** [comment]
Ah hm.  So two different issues?  It seems to correlate well with non-version-skewed breakages: http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-serial/

**Comment by ihmccreery** [comment]
I'm closing this and will re-triage; lots has changed since this was filed.
