### ISSUE TITLE
load-balancers for a Service should only target nodes that actually have a backend for that Service

### ISSUE THREAD

**Issue by MikaelCluseau** [kubernetes/kubernetes#19754]
In order to solve part of #3760, more specifically https://github.com/kubernetes/kubernetes/issues/3760#issuecomment-172041623 work will have to be done in the service controller to allow  load-balancers to target only the relevant nodes for each defined service.

This is part of the effort to try to keep the remote IP accessing a service through the kubernetes cluster.

**Comment by thockin** [comment]
I think this is safe, even more so if we install proper node-level health
checks for cloud load-balancers.

**Comment by pires** [comment]
One needs to be extra careful when it comes to use cloud-providers LB solutions in front of Kubernetes since it can change the client remote IP addresses, e.g. [AWS ELB](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html#enable-proxy-protocol-cli).

**Comment by MikaelCluseau** [comment]
I think in this case there should be something to react to the change and update the publicIP in the Kubernetes service object.

**Comment by thockin** [comment]
On Wed, Jan 27, 2016 at 4:04 AM, Paulo Pires <notifications@github.com> wrote:
>
> One needs to be extra careful when it comes to use cloud-providers LB solutions in front of Kubernetes since it can change the client remote IP addresses, e.g. AWS ELB.

Well aware.  We can't do any better than the cloud provider on this front.

**Comment by thockin** [comment]
@aronchick regarding source IP, just FYI

**Comment by thockin** [comment]
Additional context in #24300

@matchstick @girishkalele

**Comment by MikaelCluseau** [comment]
We may even push this statement to "load balancers for a Service should directly target actual Endpoints". But this may be my routed design bias speaking :-)

**Comment by hjacobs** [comment]
This does not seem to work for AWS right now as the "aws" cloudprovider fills `Ingress.Hostname` and the iptables code in `proxier.go` uses `svcInfo.loadBalancerStatus.Ingress.IP`.

**Comment by solsson** [comment]
Can "preserve source IP" make it to beta in 1.5? What remaining work is there? Works perfectly in GKE --enable-kubernetes-alpha clusters.

**Comment by matchstick** [comment]
FYI currently this is targeted for beta in 1.5. As of now it seems to be on track.
@bprashanth is doing the development. He can correct me if I misunderstand anything.

**Comment by bprashanth** [comment]
It won't *just work* though. You will have to do 1 of 2 things:     
1. leverage a health check api to program your cloud lbs so they deem nodes without endpoints as "unhealthy"
2. or, use a special type of nodeport service

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/35758

**Comment by solsson** [comment]
> It won't just work though. You will have to do 1 of 2 things:
> 1. leverage a health check api to program your cloud lbs so they deem nodes without endpoints as "unhealthy"
> 2. or, use a special type of nodeport service

So GKE does 1? Or did I not test properly with unhealthy nodes? We use a regular `"type": "LoadBalancer"` service with `OnlyLocal`.

**Comment by bprashanth** [comment]
Yeah, GKE does 1 in those ephemeral alpha clusters and OnlyLocal is beta in HEAD (i.e sees light of day in 1.5 timeframe).
