### ISSUE TITLE
kubectl should process files recursively when given a directory

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#19767]
When given a directory, `kubectl apply -f <directory>` should search a directory recursively for any JSON|YAML files when given a directory. Currently it only finds the immediate children of the given directory.

I believe kubectl apply is exhibiting the same behavior as `kubectl create`, `kubectl delete`, etc., but to enable the original #1702 use case of a nested directory of configuration objects being reconciled with the server's state, kubectl apply especially should act recursively.

Current behavior:

```
$ ls pod/
pod2.yaml  pod.yaml
$ kubectl apply -f pod
pod "nginx-1" configured
pod "nginx-2" configured
$ cd pod
$ mkdir subpod
$ ls
pod2.yaml  pod.yaml  subpod
$ mv * subpod/
$ ls
subpod
$ cd ..
$ kubectl apply -f pod  # everything is now in pod/subpod/*.yaml
error: you must provide one or more resources by argument or filename (.json|.yaml|.yml|stdin)
$
```

Expected behavior:

```
$ kubectl apply -f pod  # everything is now in pod/subpod/*.yaml
pod "nginx-1" configured
pod "nginx-2" configured
$
```

**Comment by bgrant0607** [comment]
We should do the same for all commands, not just apply.

cc @kubernetes/kubectl

**Comment by bgrant0607** [comment]
Since this isn't the current behavior, we'll need to make it optional via a flag.

**Comment by metral** [comment]
This issue has been resolved by this set of PR's:
- https://github.com/kubernetes/kubernetes/pull/23116
- https://github.com/kubernetes/kubernetes/pull/23673
- https://github.com/kubernetes/kubernetes/pull/25110

It can be closed

**Comment by bgrant0607** [comment]
Thanks! Have you looked at #24649? :-)
