### ISSUE TITLE
Move "Containers" and "Images" out of `kubectl get rc` and into `-o wide`

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#19775]
Our `kubectl get rc` output is extremely wide:

```
$ kubectl get rc
CONTROLLER                CONTAINER(S)                           IMAGE(S)                                                                                               SELECTOR                                                                                                                   REPLICAS   AGE
convert-mon-rc-dev        convert-mon                            docker-registry.dev.internal.box/sam/convert-mon:0.0.0-21.2015_12_31_22_37_37.56e95-image-16           box.com/app-id=convert-mon,box.com/env=dev,box.com/version=2015-12-13                                                      1          16d
convert-mon-rc-live       convert-mon                            docker-registry.dev.internal.box/sam/convert-mon:0.0.0-21.2015_12_31_22_37_37.56e95-image-16           box.com/app-id=convert-mon,box.com/env=live,box.com/version=2015-12-13                                                     1          16d
convert-mon-rc-sanity     convert-mon                            docker-registry.dev.internal.box/sam/convert-mon:0.0.0-21.2015_12_31_22_37_37.56e95-image-16           box.com/app-id=convert-mon,box.com/env=sanity,box.com/version=2015-12-13                                                   1          16d
...
```

(Note the columns are wider than the text because I've omitted rows that have longer text in them.)

I would contend that when you are typically trying to list RC's, you're mostly looking for (1) which ones exist, (2) how many replicas they have and perhaps (3) the selector. Usually the name is enough to remind you what's inside of it, but if you want all the details of what specific containers and images it has you can do `kubectl describe rc <x>` or `kubectl describe pod <x>`. As such I suggest moving CONTAINER(S) and IMAGE(S) columns into -o wide only.

**Comment by AdoHe** [comment]
@ghodss I think this will make the `get rc` results more readable, I am happy to do this if we have to do this.

**Comment by bgrant0607** [comment]
Some discussion in #20009

**Comment by bgrant0607** [comment]
cc @janetkuo

**Comment by bgrant0607** [comment]
@ghodss I independently came to a similar conclusion.

https://github.com/kubernetes/kubernetes/pull/20009#issuecomment-174090568

**Comment by AdoHe** [comment]
I am happy to do this if possible.

**Comment by AdoHe** [comment]
@bgrant0607 should we add this feature?

**Comment by bgrant0607** [comment]
@AdoHe I do agree that it makes sense to move containers, images, and selector to `-o wide`. 

We should make other controllers similar. Job, for instance.

At the same time, we might as well change the handful of non-conforming column headers to NAME -- #8476.

cc @janetkuo @erictune @madhusudancs

**Comment by erictune** [comment]
+1

**Comment by AdoHe** [comment]
@bgrant0607 I just update the get rc display:
```
[tony@localhost kubernetes]$ cluster/kubectl.sh get rc
CONTROLLER         REPLICAS   AGE
nginx-controller   2          8s
[tony@localhost kubernetes]$ cluster/kubectl.sh get rc -o wide
CONTROLLER         REPLICAS   AGE       CONTAINER(S)   IMAGE(S)   SELECTOR
nginx-controller   2          2m        nginx          nginx      app=nginx
```
Also I update job controller:
```
[tony@localhost kubernetes]$ cluster/kubectl.sh get job
JOB       SUCCESSFUL
pi        1
[tony@localhost kubernetes]$ cluster/kubectl.sh get job -o wide
JOB       SUCCESSFUL   CONTAINER(S)   IMAGE(S)   SELECTOR
pi        1            pi              perl       app in (pi)
```
For other controllers, I think service and daemonset show keep similar.
What do you think about this? Should I update other controllers?

**Comment by bgrant0607** [comment]
Thanks @AdoHe! Yes, I'd like the controllers to be consistent. Please update the others also.

**Comment by erictune** [comment]
Thanks for updating Job!  Looks better, and will work well with my plan to
have longer selectors on Jobs.

**Comment by kargakis** [comment]
Should we show both current and desired replicas for rcs? Showing only desired is misleading.

**Comment by AdoHe** [comment]
@erictune @bgrant0607 I just update other controllers, I opened a PR #20557, would you mind reviewing this?

**Comment by bgrant0607** [comment]
@kargakis Yes, desired and current SGTM. Eventually I'd like to add more status info to the API, as with Deployment, but let's show what we have.
