### ISSUE TITLE
ResourceQuota for ConfigMap

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#19780]
The number of ConfigMaps in a namespace should be controllable via `ResourceQuota`.

@derekwaynecarr @bgrant0607

**Comment by derekwaynecarr** [comment]
I agree.  At the next API-machinery sig, I want to chat through the best way of handling this dynamically so people don't need to write code.

**Comment by erictune** [comment]
Are you actually trying to limit the amount f apiserver/etc memory used?  And indirectly doing that using object-count-quota * maximum-object-size (1MB).  

If so, how about explicitly tracking bytes?  Add a new resource called configmap-bytes or object-bytes.
On created, increment by length of serialized object.  On delete request, get it, compute length, and decrement.  On update, compute length before and after, take difference, apply difference to quota.

**Comment by erictune** [comment]
@lavalamp told me that my suggestion is quite hard to implement in practice without bugs that introduce a cumulative error.  So, I retract my suggestion above.

**Comment by vishh** [comment]
#22183 fixes this issue.
