### ISSUE TITLE
Size limit for ConfigMap

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#19781]
Currently we do not enforce any size limits on ConfigMap.  The limit for secrets is 1MB.  I think 1MB is on the small side for what some people might want, and suggest we consider up to 5MB.   The main questions are what the upper limit on a single piece of config data is and what granularity we want to quota total storage on.

@bgrant0607 @smarterclayton @thockin @erictune  @eparis @liggitt
cc @kubernetes/rh-cluster-infra

**Comment by ncdc** [comment]
A 1MB cap for an entire ConfigMap is potentially too low. I remember we talked about how to account for the resources (memory/disk) used by secrets, config, etc, in terms of if it is possible to charge it to the namespace vs the Kubelet, but I don't recall if we came to a resolution.

**Comment by smarterclayton** [comment]
The limit is 1MB because that's the limit for etcd.

**Comment by pmorie** [comment]
Sounds like a 1MB limit for ConfigMap is the ceiling for now then.  I'll make a PR.

**Comment by bgrant0607** [comment]
Do we need a fixed number?

We should use something like LimitRange and/or ResourceQuota to cap individual and aggregate resource sizes. Users could attach arbitrary amounts of data to anything given annotations.

**Comment by bgrant0607** [comment]
Of course, it can't be bigger than what etcd supports, so I'm fine with putting that hard limit in.

**Comment by toonsevrin** [comment]
I've proposed an extension to Kubernetes for this. Please take a look at #88709.

With this extension, you upload your configuration to s3 (or simply git) and reference it in a File resource. Finally the configmap references this file resource.

Feel free to upvote that proposal to raise awareness.

**Comment by MurzNN** [comment]
Current etcd version have 1.5mb limit already, with ability to increase it: https://etcd.io/docs/v3.5/dev-guide/limit/

> By default, the maximum size of any request is 1.5 MiB. This limit is configurable through --max-request-bytes flag for etcd server.

Does this mean, that we can increase this limit in fresh k8s versions too?

**Comment by ozbillwang** [comment]
this is old ticket. 

But I hit the size limit issue today when try to pass a large file like 50Mb with configMap. 

Should we set the limit on configmap, what's the purpose on it?

**Comment by thockin** [comment]
All kube resources have a limit of about 1 MiB.
