### ISSUE TITLE
kubectl apply should be able to delete objects missing from supplied config

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#19805]
The declarative configuration workflow described in #1702 implies that you can give kubectl apply a set of objects and all changes will be applied. One change that is trickier is to declaratively apply is the deletion of an object when a spec is missing. After all, how does kubectl apply know which objects to delete were previously created by kubectl apply and therefore should be deleted vs created by the system (e.g. pods from a replication controller) or other unrelated users?

The answer is the kubectl apply annotation itself. We should add a flag (`--prune`?) to kubectl apply which deletes all objects that (1) aren't in the list given to kubectl apply and (2) do have a kubectl apply annotation at `kubectl.kubernetes.io/last-applied-configuration`.

Note that currently it's hard to give kubectl apply many objects at once but once #19767 and/or #19639 are finished it will be much easier.

cc @kubernetes/sig-config

**Comment by bgrant0607** [comment]
Objects created by the system are a separate problem. I've proposed that we add a general existence dependency mechanism to handle that. (Discussed in #1535 and elsewhere.)

**Comment by bgrant0607** [comment]
Some clarifications:
* --prune would apply to annotated resources in the specified namespace
* we'll need a --cascade flag, as with delete, which should default to true
* we may want an option to ask for confirmation once the list of resources to delete is generated
* we may want to narrow the scope of apply (and prune) in the future, by label selector and/or by resource type

**Comment by bgrant0607** [comment]
A test case: #23471

**Comment by errordeveloper** [comment]
Would this be of any use to Helm? Or is it purely to do with `kubectl`?

cc @kubernetes/helm-maintainers

**Comment by mikedanese** [comment]
Kubectl apply can be used as a library, so it's potentially reusable. Not sure if helm is using it yet though.

**Comment by michelleN** [comment]
@errordeveloper yes - we're keeping the behavior of `helm upgrade` in line with the behavior as `kubectl apply` for now but we'll need delete functionality eventually, especially since we are tracking all of the resources that created on an install of a chart.

@mikedanese how can we go about using kubectl as a library? Do you have an example of that or any thoughts there? ... Would love to not re-invent the wheel :)

**Comment by mikedanese** [comment]
The actual patch can be create with [CreateThreeWayMergePatch }(https://github.com/kubernetes/kubernetes/blob/master/pkg/util/strategicpatch/patch.go#L1143-L1153) witch the apiserver can accept with a PATCH verb to a resouce with `ContentType: application/strategic-merge-patch+json`. kubectl apply does a bit more, e.g. use annotations to keep track of the original configuration but it's still fairly simple https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply.go

**Comment by errordeveloper** [comment]
@mikedanese so we are talking about retrieving original objects and comparing those? How can we figure out what belongs to the same directory/group/batch?

I've looked at `annotations.LastAppliedConfigAnnotation` and it seems to relate to the each individual object... Anyway, I don't think it'd make much sense to store previous versions of current object and other objects from the same directory in an annotation.

_Some more thoughts:_ I am thinking that local path wouldn't be very reliable, and I hope we aren't doing anything with that... May be the user could specify some kind of explicit group name through annotations, so it's also clear for them. May be internally this could be something like a named list?

**Comment by errordeveloper** [comment]
Also, I'm thinking that making this a dependency of #24649 may be a good idea, and users would probably find that reasonable.

**Comment by lukemarsden** [comment]
@errordeveloper and I are taking a look at this today. We're going to start by trying to understand the current behavior and the desired behavior and then write down some examples to make sure we're on the right track.

**Comment by lukemarsden** [comment]
We've reproduced the problem which we believe this ticket is intended to solve.

See https://gist.github.com/errordeveloper/b0b5bd07b2a69694c771b9047fc4d30d for files before and after and intended new behavior.

**Comment by lukemarsden** [comment]
Proposal in https://github.com/kubernetes/kubernetes/pull/29551, please provide feedback on that PR. It's entirely possible that we're missing something here.

cc @mikedanese @bgrant0607
