### ISSUE TITLE
kubectl apply should only submit a PATCH if something has changed

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#19809]
If you run kubectl apply on an unchanged replication controller several times in a row, it sends a PATCH every time. It should either only generate a PATCH in the first place if the server state needs to be changed, or only send a PATCH if the generated PATCH would change the state of the server.

cc @kubernetes/sig-config

**Comment by bgrant0607** [comment]
cc @jackgr

**Comment by bgrant0607** [comment]
One problem we have is that if a user specifies an optional field with the golang type default value (e.g., 0 or false), the field will be elided and might show as a diff.
