### ISSUE TITLE
release to gcr.io

### ISSUE THREAD

**Issue by jtbcgdv** [kubernetes/kubernetes#19815]
I'm setting up a cluster using the coreos team's template.
However, it pulls from gcr.io/google_containers/hyperkube and version v1.1.4 is not available.

How soon after 'releasing' a version in github do you push to the container registry?

**Comment by luxas** [comment]
That's fixed with #19061, and will be done automatically since `v1.2.0`
Now they do it manully

**Comment by geoah** [comment]
Same issue here, will someone be deploying v1.1.4 to gcr.io? :)
Thanks

**Comment by luxas** [comment]
@david-mcmahon released `v1.1.4`. I guess he should push it...

**Comment by david-mcmahon** [comment]
Done.  Working on getting a cherrypick for PR #19061 for the release-1.1 branch.
