### ISSUE TITLE
Unauthorized access error

### ISSUE THREAD

**Issue by shilpapadgaonkar** [kubernetes/kubernetes#19818]
Hello,
When I try to access
https://public-ip/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana I get Unauthorized access error. Could you please let me know the correct way to access the endpoints.. I have installed the monitoring-influx-db-grafana stack while installing Kubernetes.

Thanks

**Comment by jegesh** [comment]
I have this same problem.  What caused it for you?  What was your solution?
