### ISSUE TITLE
list option in kubectl label/annotate

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#19817]
I want to be able to see the current labels (or annotations) of a resource w/o getting the whole configuration.
This should probably be supported in kubectl {label,annotate} either by just passing the resource or via a `--list` option.

@kubernetes/kubectl

**Comment by bgrant0607** [comment]
#19689 doesn't do what you want?

**Comment by kargakis** [comment]
`kubectl label svc/registry` without any provided labels right now fails while it could show me just the labels of the service. `kubectl annotate svc/registry` could list all the service annotations in a similar fasion.

**Comment by dhawal55** [comment]
+1

**Comment by AdoHe** [comment]
@kargakis I will try to add this option later.

**Comment by ultimateboy** [comment]
For anybody else running across this, I created myself a go-template query which lists all the annotations of services (easily adaptable to labels). It's not pretty, but it gets the job done:

```kubectl get svc -o 'go-template={{range .items}}{{.metadata.name}}{{"\n"}}{{range $key,$value := .metadata.annotations}}{{$key}}: {{$value}}{{"\n"}}{{end}}{{"\n"}}{{end}}'```

**Comment by kargakis** [comment]
[kubectl view](https://github.com/kubernetes/kubernetes/issues/29679) should be the best place for this.

**Comment by ymqytw** [comment]
> kubectl view should be the best place for this.

What would it looks like?

**Comment by kargakis** [comment]
> What would it looks like?

```sh
$ kubectl view annotations dc/foo
deployment.kubernetes.io/revision: "1"
app: foo
```

**Comment by ymqytw** [comment]
SGTM. I have updated the tracking table in #29679.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by AdoHe** [comment]
This is part of our Q1 job, will open a PR asap.

**Comment by warmchang** [comment]
👍

**Comment by illyaMs** [comment]
> For anybody else running across this, I created myself a go-template query which lists all the annotations of services (easily adaptable to labels). It's not pretty, but it gets the job done:
> 
> `kubectl get svc -o 'go-template={{range .items}}{{.metadata.name}}{{"\n"}}{{range $key,$value := .metadata.annotations}}{{$key}}: {{$value}}{{"\n"}}{{end}}{{"\n"}}{{end}}'`

Thanks for the hint.
For me it was failing with `template: output:1: unexpected "\\" in command` error, but changing all `"\n"` occurrences to `println` go-template function did the job.
