### ISSUE TITLE
Container Termination Discrepancy  for Exit Code 137

### ISSUE THREAD

**Issue by nyxcharon** [kubernetes/kubernetes#19825]
In the documentation [here](http://kubernetes.io/v1.1/docs/user-guide/compute-resources.html#my-container-is-terminated)  it shows a pod using too much memory and is promptly killed.
When this happens it shows the error reason as "OOM"  and error code as 137 in the docs. When I go through similar steps myself, the termination reason is just "Error", though I do still get the 137 error code. Is there a reason this was changed?
OOM is very clear on what happened while "Error" can send people down a wild chase trying to
figure out what happened to their pod - hence me filing this issue.

For reference the script ran in my docker image just eats memory until it the container gets killed.

```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.1", GitCommit:"92635e23dfafb2ddc828c8ac6c03c7a7205a84d8", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}
```

```
$ kubectl get pod -o json  memtest
{
    "kind": "Pod",
    "apiVersion": "v1",
    "metadata": {
        "name": "memtest",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/pods/memtest",
        "uid": "c480d1ba-bec2-11e5-ad45-062d2421a4bd",
        "resourceVersion": "21949421",
        "creationTimestamp": "2016-01-19T15:39:03Z"
    },
    "spec": {
        "containers": [
            {
                "name": "memtest",
                "image": "nyxcharon/docker-stress:latest",
                "args": [
                    "python",
                    "/scripts/mem-fill"
                ],
                "resources": {
                    "limits": {
                        "memory": "10M"
                    },
                    "requests": {
                        "memory": "10M"
                    }
                },
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "Always"
            }
        ],
        "restartPolicy": "Never",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "nodeName": "<IP removed>"
    },
    "status": {
        "phase": "Failed",
        "conditions": [
            {
                "type": "Ready",
                "status": "False",
                "lastProbeTime": null,
                "lastTransitionTime": null
            }
        ],
        "hostIP": "<IP Removed>",
        "startTime": "2016-01-19T15:39:03Z",
        "containerStatuses": [
            {
                "name": "memtest",
                "state": {
                    "terminated": {
                        "exitCode": 137,
                        "reason": "Error",
                        "startedAt": "2016-01-19T15:39:15Z",
                        "finishedAt": "2016-01-19T15:39:16Z",
                        "containerID": "docker://3dd77f77dfd6e715c8792c625f388e0b31cbd36ccdb4a11dafbb6d381bf83943"
                    }
                },
                "lastState": {},
                "ready": false,
                "restartCount": 0,
                "image": "nyxcharon/docker-stress:latest",
                "imageID": "docker://bacbb71b34e92ed2074621d86b10ec15a856f5918537c4d75b6f16925b5b93e7",
                "containerID": "docker://3dd77f77dfd6e715c8792c625f388e0b31cbd36ccdb4a11dafbb6d381bf83943"
            }
        ]
    }
}
```

```
$ kubectl describe pod memtest
Name:               memtest
Namespace:          default
Image(s):           nyxcharon/docker-stress:latest
Node:               <IP removed>
Start Time:         Tue, 19 Jan 2016 10:39:03 -0500
Labels:             <none>
Status:             Failed
Reason:
Message:
IP:
Replication Controllers:    <none>
Containers:
  memtest:
    Container ID:   docker://3dd77f77dfd6e715c8792c625f388e0b31cbd36ccdb4a11dafbb6d381bf83943
    Image:      nyxcharon/docker-stress:latest
    Image ID:       docker://bacbb71b34e92ed2074621d86b10ec15a856f5918537c4d75b6f16925b5b93e7
    QoS Tier:
      memory:   Guaranteed
    Limits:
      memory:   10M
    Requests:
      memory:       10M
    State:      Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Tue, 19 Jan 2016 10:39:15 -0500
      Finished:     Tue, 19 Jan 2016 10:39:16 -0500
    Ready:      False
    Restart Count:  0
    Environment Variables:
Conditions:
  Type      Status
  Ready     False
No volumes.
Events:
  FirstSeen LastSeen    Count   From                    SubobjectPath               Reason  Message
  ─────────   ────────    ───── ────                    ─────────────             ──────  ───────
  2m        2m      1   {kubelet <IP removed>}  implicitly required container POD   Pulled  Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  2m        2m      1   {scheduler }                                    Scheduled   Successfully assigned memtest to <IP removed>
  2m        2m      1   {kubelet <IP removed>}  implicitly required container POD   CreatedCreated with docker id 65a446677edd
  2m        2m      1   {kubelet <IP removed>}  spec.containers{memtest}        PullingPulling image "nyxcharon/docker-stress:latest"
  2m        2m      1   {kubelet <IP removed>}  implicitly required container POD   StartedStarted with docker id 65a446677edd
  2m        2m      1   {kubelet <IP removed>}  spec.containers{memtest}        Pulled  Successfully pulled image "nyxcharon/docker-stress:latest"
  2m        2m      1   {kubelet <IP removed>}  spec.containers{memtest}        CreatedCreated with docker id 3dd77f77dfd6
  2m        2m      1   {kubelet <IP removed>}  spec.containers{memtest}        StartedStarted with docker id 3dd77f77dfd6
  2m        2m      1   {kubelet <IP removed>}  implicitly required container POD   KillingKilling with docker id 65a446677edd
```

Here is the pod definition i'm using:

```
kind: Pod
apiVersion: v1
metadata:
  name: memtest
spec:
  containers:
  - name: memtest
    image: nyxcharon/docker-stress:latest
    args:
    - python
    - /scripts/mem-fill
    resources:
      limits:
        memory: 10M
  restartPolicy: Never
```

**Comment by bgrant0607** [comment]
cc @vishh

**Comment by therc** [comment]
I can confirm this on AWS, with Kubelet built almost from HEAD. Two of us spent the past hour chasing error 137 left and right.

The problem is that even docker inspect on the node doesn't mention any OOM:
`    "State": {
        "Status": "exited",
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 137,
        "Error": "",
        "StartedAt": "2016-02-01T21:50:35.794765356Z",
        "FinishedAt": "2016-02-01T21:50:51.171492914Z"
    },
`

That's Docker 1.9.1 on CoreOS 935.

**Comment by therc** [comment]
Maybe it's upstream: https://github.com/docker/docker/issues/18510

**Comment by ApsOps** [comment]
I'm facing the same issue here. `Kube: v1.3.0` `docker: 1.10.3`. The upstream @therc mentioned has been fixed, so I thought this shouldn't happen :/

```
"State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "",
            "StartedAt": "2016-07-19T05:15:33.150413532Z",
            "FinishedAt": "2016-07-19T05:16:32.658433718Z"
        },
```

Could this be the case when kubelet killed the pod for some reason?

**Comment by javiercr** [comment]
I had the same issue with kubernetes v1.4.0, a pod crashed with ExitCode 137 but no indication of OOM.

**Comment by ApsOps** [comment]
I think this could happen when a container liveness probe fails.
@javiercr could you check if this was the case for you?

**Comment by javiercr** [comment]
@ApsOps sorry for my ignorance 😓 , but how can I check that?

**Comment by ApsOps** [comment]
@javiercr Have you setup a `LivenessProbe` in your pod config? If yes, `describe` the pod and look for `events` section.

**Comment by javiercr** [comment]
@javiercr nope, I didn't setup any `LivenessProbe` nor it appears in the pod description.

**Comment by ciokan** [comment]
I have the same `Exit 137` status showing up all over the place. One of the things that I discovered was a service `phpmyadmin` (which was limited to `512Mi` in ram) that was eating 2Gb of RAM. How it managed to do that I don't know but it was causing other probes on the same VM to crash:

	"resources": {
		"requests": {
			"cpu": "50m",
			"memory": "128Mi"
		},
		"limits": {
			"cpu": "200m",
			"memory": "512Mi"
		}
	}

I have frequent crashes of the same sort that occur on different VM's though so I can't place my finger exactly on the `phpmyadmin` service (which I completely removed now to test thing out).

All the pods that crash have liveness and readiness in place btw.

**Comment by vishh** [comment]
137 exit code is returned by docker engine whenever the container
experiences a OOM kill.

**Comment by roffe** [comment]
I have seen this as well in my setup. and it seems to happend more for containers running php than others.

It seems sometimes also the only thing making some containers work is to use USE_ZEND_ALLOC=0
which seems like a largly undocumented parameter for turning of php memory manager(!?)

**Comment by daniilyar** [comment]
I have seen the same on K8 1.5.4 and Docker 1.13.1. In my case, K8 pod shown:
```
    Last State:		Terminated
      Reason:		Error
      Exit Code:	137
```
But there were NO OOMKiller events in syslog for that time period. Does 127 code only signal about OOMKill? Can it indicate just a SIGKILL sent to container by Docker? It is not clear for me from Docker and K8 code..

**Comment by umerpk** [comment]
I am having issue where my java process is saying " abnormal termination with error code 137 " , Process destroyed without shutdown hock 

how will I get jvm crash report ?

**Comment by parthakom** [comment]
I suspect its because of liveliness probe failing, but not sure why it should exit with code 137 which is for OOM.

**Comment by bappr** [comment]
Hey guys,
Sorry to bump this up after 2 years, but still the same problem here.
I am getting a `137` error code while there is not OOM issue. And yes it's because of the liveness probe not being successful. But should not it get a different code since `137` should be reserved for OOM.

**Comment by kozell** [comment]
> (...) I am not even sure that this `137` should be even reserved for OOM. So my suggestion would be more about having a specific exitCode when the liveness probe is failed and the pod is running?

Subtract 128, and you will get the signal itself (signal 9 is SIGKILL).
See https://tldp.org/LDP/abs/html/exitcodes.html and https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html

**Comment by sowhatim** [comment]
I am also seeing one weird behaviour where container is using 40% the memory of the request, and it is getting restarted throwing 137 exit code. There is no logs for oom or liveliness check failures as it is set pretty high but container is getting kill repeatedly throwing 137 code. Also application in itself is not throwing any error, etc so I am guessing something from k8s is killing the pod. 

Any clue anyone on what might be going wrong.

**Comment by satuday** [comment]
more than 5 yrs and still no proper solution.

**Comment by e33ivanyauwai** [comment]
I also experienced this issue, pod got killed with exit code 137 and restarted for many times.  But docker logs <container> showed that OOMKilled is false below.

        "State": {
             ...
            "OOMKilled": false,
             ...
        },

I read from the above comments that liveness probe failed may induce this issue, but this is not related to OOMKilled (my node has sufficient memory for pods).

**Comment by e33ivanyauwai** [comment]
I set a higher memory limit for the pod and double the initial replicas number, and the problem was gone and there is no restarting now.

**Comment by symbol-z-unique** [comment]
I also experienced this issue too.
##### phenomenon 
1. container's **State.OOMKilled** is false, and **State.ExitCode** is 137.
2. use command "kubectl describe pod" to watch pod‘s events, nothing about exception.
##### try 
increase **memory limit** size.
##### monitor 
use command "kubectl describe pod" to watch pod‘s events again, i see the message is "container xxx failed liveness probe, will be restarted".
##### solution
increase **readinessProbe.initialDelaySeconds** or delete this config if you don't need it.

**Comment by ppp0** [comment]
In can confirm, seeing same discrepancy. on k8s v1.19

* `kubectl describe pod` shows reason for restarted pod is `OOMKilled`
* kubelet.go log trace shows repeated problems with liveness probes until threshold is reached and pod restarted
* No other signs of OOM killer activity and likely not the reason

**Comment by pachecopaulo** [comment]
I'm seeing the same issue on k8s v1.21
```
Last State:     Terminated
Reason:       Error
Exit Code:    137
```

I see that the probes failed and apparently that's why it got restarted, but only one replica out of 2 got restarted.

**Comment by cooldudesam** [comment]
We are seeing the same issue. @ pachecopaulo - Has your issue resolved? If so, what steps have you taken? any RCA?

EKS - 1.21 version with containerd

Last State:     Terminated
Reason:       Error
Exit Code:    137

Even though the exit code shows 137, I don't see any signs of OOM.
The pod got restarted due to problems with readiness probe.

Thanks!
