### ISSUE TITLE
Constraint solver to determine overlapping label selectors

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#19830]
Today, when we want to determine resources with overlapping selectors, for example overlapping replication controllers, we check if the selector of one resource matches the selector of the other and vice-versa. This is easy to do with the current map{string->string} selectors.

But determining overlaps in the case of new label selectors need a more sophisticated constraint solver. Implement one.

cc @bgrant0607

**Comment by bgrant0607** [comment]
Specifically, the check we have now is able to confirm some cases of definite overlap, which is used to warn the user in kubectl stop rc.

Definite overlap occurs when one controller's selector contains a subset of keys of the other controller's selector, and the intersection of the sets of matching values for each of those keys (where Exists implies all values) is non-empty.

Though we don't currently have such a check AFAIK, we could also implement a check for definite non-overlap, which could be determine in the case that for at least one key the intersection of values is empty (e.g., In {v1} intersect NotIn {v1}).

**Comment by bgrant0607** [comment]
See also #2210

cc @erictune

**Comment by bgrant0607** [comment]
cc @janetkuo

**Comment by soltysh** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/36859#issuecomment-262022027

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by bgrant0607** [comment]
Can revisit later if needed
