### ISSUE TITLE
default vagrant libvirt image is broken

### ISSUE THREAD

**Issue by marun** [kubernetes/kubernetes#19834]
The latest vagrant always restarts nfs when nfs is used to share folders:

https://github.com/mitchellh/vagrant/commit/c4733a02d483818c3e9a99f1e94582d9a43593ae#diff-843e141393278f0e09aa01c731529258R22

This doesn't work with the default kube libvirt image:

https://github.com/kubernetes/kubernetes/blob/master/Vagrantfile#L72

Attempting to restart nfs (systemctl restart nfs) on this image results in a failure from /usr/sbin/exportfs (invoked in the nfs unit file via ExecStartPre) of 'No file systems exported!' and this halts vagrant provisioning.

To replicate (centos 7.1+vagrant 1.8.1+vagrant-libvirt 0.0.32): 

    export KUBERNETES_PROVIDER=vagrant
    export VAGRANT_DEFAULT_PROVIDER=libvirt
    ./cluster/kube-up.sh

**Comment by marun** [comment]
This issue should be resolved by #15998 (already merged) and #19841.

**Comment by derekwaynecarr** [comment]
I marked #19841 as lgtm, so its basically blocked by the submit queue being fixed.
