### ISSUE TITLE
Reboot tests should check whether pods spec is *the same* as before rebooting

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#19844]
From https://github.com/kubernetes/kubernetes/pull/19436#issuecomment-172982445, it's possible that after a reboot test, some pods (especially mirror pods) have DeletionTimestamp set due to pod eviction. The tests should check if the pod spec is unmodified after rebooting to catch such scenarios. Failure to do so breaks the test isolation and leaves changes that may fail other tests.

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc
