### ISSUE TITLE
Pod template for DaemonSet/ReplicationController is pointer, but Job/Deployment not

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#19859]
I notice that PodTemplate for DaemonSet/ReplicationController is pointer, but Job/Deployment not, why they are not consistent? I think all the PodTemplate should not be a pointer, since PodTemplate is not a optional field for DaemonSet/ReplicationController/Job/Deployment.

**Comment by bgrant0607** [comment]
Yes, our intent is to make them consistent, except for maybe ReplicationController, which has backward-compatibility constraints.

cc @janetkuo @madhusudancs @mikedanese @erictune

**Comment by soltysh** [comment]
Job was done here: https://github.com/kubernetes/kubernetes/pull/14575
DaemonSet is here: https://github.com/kubernetes/kubernetes/pull/19510
ReplicationController stays as is.
Once DS is merged we can close this issue.

**Comment by soltysh** [comment]
@mqliang this can be closed now.
