### ISSUE TITLE
Better testing of --local

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#19853]
@deads2k said in #18835 : 
"I'm pretty sure that this chunk of code will cause something like the kubectl convert --local to fail because this will try to make a remote connection and the ObjectTyper is probably used. If this didn't fail tests, it would suggest that branch isn't being checked, which is probably worthy of a separate issue."

Tests don't fail, so, separate issue ;)

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc
