### ISSUE TITLE
Azure cluster tool should use the Azure Resource Manager

### ISSUE THREAD

**Issue by raulk** [kubernetes/kubernetes#19867]
Microsoft is recommending migrating from the classic deployment model to their [Resource Manager (RM)](https://azure.microsoft.com/en-us/documentation/articles/resource-manager-deployment-model/) deployment model.

Unfortunately, the API for Classic vs. RM is not compatible in several areas. Trying to deploy Kubernetes under RM leads to the following error:

```
error: unknown option `--address-space'
```

**Comment by brendandburns** [comment]
Deleting this as obsolute. https://github.com/Azure/acs-engine is the preferred way to deploy and uses ARM.
