### ISSUE TITLE
cannot register print handler function with non-exported printOptions param

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#19865]
In resource_printer.go, printers for additional types can be registered. However, the signature of the function must include a `printOptions` parameter. This type is not exported, which means other packages cannot register printers.

This should be exported (along with the fields, so called printer functions can use the options):
```
type printOptions struct
```

**Comment by AdoHe** [comment]
@erictune

**Comment by lavalamp** [comment]
I think as a follow-up the resource printer stuff should be made a subpackage under kubectl.

**Comment by liggitt** [comment]
That could be good… making the kubectl commands a consumer of the exported functions and structs ensures they have the right cross package visibility.
