### ISSUE TITLE
Dynamic provisioner sometimes creates two volumes for one claim

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#19860]
I noticed that sometimes (<10%) Kubernetes do not delete volumes it created. Digging into logs, I can see this sequence in the persistent volume controller:

```log
I0120 12:21:06.951473    2571 persistentvolume_claim_binder_controller.go:331] Synchronizing PersistentVolumeClaim[pvc-8z0kk]
I0120 12:21:06.951572    2571 persistentvolume_claim_binder_controller.go:342] A volume match does not exist for persistent claim: pvc-8z0kk
I0120 12:21:07.009176    2571 persistentvolume_provisioner_controller.go:174] PersistentVolumeClaim[pvc-8z0kk] provisioning
I0120 12:21:07.100719    2571 persistentvolume_provisioner_controller.go:197] Unprovisioned PersistentVolume[pv-cinder-uxgot] created for PVC[pvc-8z0kk], which will be fulfilled in the storage provider
I0120 12:21:07.128868    2571 persistentvolume_recycler_controller.go:161] Recycler: checking PersistentVolume[pv-cinder-uxgot]
I0120 12:21:07.128923    2571 persistentvolume_recycler_controller.go:193] PersistentVolume[pv-cinder-uxgot] phase Pending - skipping: The volume is not in a final state
I0120 12:21:07.129204    2571 persistentvolume_claim_binder_controller.go:193] Synchronizing PersistentVolume[pv-cinder-uxgot], current phase: Pending
I0120 12:21:07.129240    2571 persistentvolume_claim_binder_controller.go:214] Skipping PersistentVolume[pv-cinder-uxgot], waiting for provisioning to finish
I0120 12:21:07.186905    2571 persistentvolume_claim_binder_controller.go:331] Synchronizing PersistentVolumeClaim[pvc-8z0kk]
I0120 12:21:07.187018    2571 persistentvolume_claim_binder_controller.go:347] PersistentVolume[pv-cinder-uxgot] for PersistentVolumeClaim[e2e-tests-volume-provisioning-scooj/pvc-8z0kk] is still being provisioned.
I0120 12:21:07.190275    2571 persistentvolume_provisioner_controller.go:174] PersistentVolumeClaim[pvc-8z0kk] provisioning
I0120 12:21:07.250590    2571 persistentvolume_recycler_controller.go:161] Recycler: checking PersistentVolume[pv-cinder-bn5d6]
I0120 12:21:07.263177    2571 persistentvolume_recycler_controller.go:193] PersistentVolume[pv-cinder-bn5d6] phase Pending - skipping: The volume is not in a final state
I0120 12:21:07.254780    2571 persistentvolume_claim_binder_controller.go:193] Synchronizing PersistentVolume[pv-cinder-bn5d6], current phase: Pending
I0120 12:21:07.263275    2571 persistentvolume_claim_binder_controller.go:214] Skipping PersistentVolume[pv-cinder-bn5d6], waiting for provisioning to finish
I0120 12:21:07.255305    2571 persistentvolume_provisioner_controller.go:197] Unprovisioned PersistentVolume[pv-cinder-bn5d6] created for PVC[pvc-8z0kk], which will be fulfilled in the storage provider
E0120 12:21:07.270106    2571 persistentvolume_provisioner_controller.go:205] error updating persistent volume claim: %vpersistentvolumeclaims "pvc-8z0kk" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
I0120 12:21:07.270162    2571 persistentvolume_provisioner_controller.go:170] PersistentVolumeClaim[pvc-8z0kk] is already provisioned.
I0120 12:21:07.396334    2571 persistentvolume_provisioner_controller.go:212] PersistentVolume[pv-cinder-uxgot] reconciling
I0120 12:21:07.396385    2571 persistentvolume_provisioner_controller.go:246] PersistentVolume[pv-cinder-uxgot] provisioning in progress
I0120 12:21:07.537061    2571 openstack.go:1055] Created volume 0557d70c-3e7a-461b-88c4-d6f464a53d3d
I0120 12:21:07.537110    2571 cinder_util.go:166] Successfully created cinder volume 0557d70c-3e7a-461b-88c4-d6f464a53d3d
I0120 12:21:07.797214    2571 persistentvolume_recycler_controller.go:161] Recycler: checking PersistentVolume[pv-cinder-uxgot]
I0120 12:21:07.799584    2571 persistentvolume_recycler_controller.go:193] PersistentVolume[pv-cinder-uxgot] phase Pending - skipping: The volume is not in a final state
I0120 12:21:07.809612    2571 persistentvolume_claim_binder_controller.go:193] Synchronizing PersistentVolume[pv-cinder-uxgot], current phase: Pending
I0120 12:21:07.992698    2571 persistentvolume_provisioner_controller.go:212] PersistentVolume[pv-cinder-bn5d6] reconciling
I0120 12:21:07.992961    2571 persistentvolume_provisioner_controller.go:246] PersistentVolume[pv-cinder-bn5d6] provisioning in progress
I0120 12:21:08.053157    2571 persistentvolume_claim_binder_controller.go:331] Synchronizing PersistentVolumeClaim[pvc-8z0kk]
I0120 12:21:08.053652    2571 persistentvolume_claim_binder_controller.go:347] PersistentVolume[pv-cinder-bn5d6] for PersistentVolumeClaim[e2e-tests-volume-provisioning-scooj/pvc-8z0kk] is still being provisioned.
I0120 12:21:08.053689    2571 persistentvolume_claim_binder_controller.go:261] PersistentVolume[pv-cinder-uxgot] is available
I0120 12:21:08.054043    2571 persistentvolume_claim_binder_controller.go:318] PersistentVolume[pv-cinder-uxgot] changing phase from Pending to Available
I0120 12:21:08.188433    2571 openstack.go:1055] Created volume b615cae0-1f82-4f94-a1bb-eccf25b710a0
I0120 12:21:08.190127    2571 cinder_util.go:166] Successfully created cinder volume b615cae0-1f82-4f94-a1bb-eccf25b710a0
```

* Two volumes are created for claim `pvc-8z0kk`:
  * At `12:21:07.100719`, PV `pv-cinder-uxgot` is created. 
  * At `12:21:07.255305`, PV `pv-cinder-bn5d6` is created. **Note in the logs:** `error updating persistent volume claim: persistentvolumeclaims "pvc-8z0kk" cannot be updated: the object has been modified; please apply your changes to the latest version and try again`
* These two volumes are provisioned:
  * `pv-cinder-uxgot` at `12:21:07.537061`: `Created volume 0557d70c-3e7a-461b-88c4-d6f464a53d3d`
  * `pv-cinder-bn5d6` at `12:21:08.188433`: `Created volume b615cae0-1f82-4f94-a1bb-eccf25b710a0`
* Both these volumes are bound (!)
* When the claim is deleted, only one of the volumes is deleted.

It's *probably* caused by `Synchronizing PersistentVolumeClaim[pvc-8z0kk]` being called twice in parallel.
@markturansky, please confirm my suspicion. Can it be the periodic check + 'claim updated' event running at the same time? Any idea how to fix it? Lock could be appropriate, still I would prefer if there was possibility to atomically 'get current version of the claim, look at it and update it'. Too many things read/modify object annotations (and more are coming!) and it's pretty hard to keep them from colliding.

cc: @kubernetes/rh-storage, @saad-ali

**Comment by jsafrane** [comment]
I was wrong, there is nothing running in parallel, there are mutexes everywhere. Investigation continues...

**Comment by jsafrane** [comment]
Got it. A claim is added to API server + at the same time periodical sweep is run.

1. `PersistentVolumeProvisionerController.handleAddClaim() `is called by the claim watcher as result of "add event"
2. in another thread, `PersistentVolumeProvisionerController.handleUpdateClaim()` is called by the periodic sweep **with the same claim**
3. one of them gets a mutex, say `handleAddClaim` and calls `reconcileClaim(claim)`
4. `reconcileClaim(claim)` creates a PV, adds an annotation to the claim ("I'm already provisioned") and returns. So far so good.
5. `handleAddClaim` releases its mutex, `handleUpdateClaim` locks it and calls `reconcileClaim(claim)` **with the same claim**.
6. Now the bug: 2nd call to `reconcileClaim(claim)` still sees the old claim, without an annotation -> again creates a volume and adds the annotation, which fails. That's the "error updating persistent volume claim:" we see in the logs.

Fix: reconcileClaim(claim) should always reload a new version of the claim before taking any action. PR will follow shortly.

**Comment by markturansky** [comment]
@jsafrane thanks, Jan.  good detective work.  Looking forward to reviewing the PR.

This speaks loudly that we need controller consolidation and shared mutexes.

**Comment by jsafrane** [comment]
Fix is referenced above. Still, with an user (or other competing controller), we may leak a volume or two:

1. User creates a claim.
2. reconcileClaim(claim) is called.
3. reconcileClaim() (slowly) creates a volume.
3. The user updates the claim (with some dummy annotation).
4. Now, reconcileClaim() finished creation of the volume, wants to add an annotation to the claim,. This fails, because the user already updated the claim.
5. reconcileClaim() will create a new volume next time.
