### ISSUE TITLE
kubectl logs -l 

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#19873]
When I run a job, I want to check on the progress being made by the pods.   Likewise with an RC (either directly created or via `kubectl run`.

For listing the pods, I use the `-l` option, like this:

``` console
kubectl run foo --image bar -- /bin/blorp
kubectl get pods -l run=myrunname
```

But, usually the next thing I want to do is check logs.
I want to be able to do this:

```
kubectl logs -l run=myrunname
```

That doesn't work.  This is a request to implement it.

Something like this:
1. when -l option passed to `logs`, get a list of matching pods
2. for each pod name, get its logs.
3. print some kind of separator between logs from multiple pods.

**Comment by AdoHe** [comment]
@erictune in `kubectl get pods -l run=myrunname` command, `-l` means <b>label select</b>, so you mean that we should add a `-l` option to `logs` subCommand, thus we can check on the progress being made by the pods when run a job?

**Comment by erictune** [comment]
yes.

**Comment by AdoHe** [comment]
@erictune Ok, I will add this feature first, then add suggest next command feature.

**Comment by erictune** [comment]
sounds good.

**Comment by AdoHe** [comment]
@erictune guess `kubectl get pods -l run=myrunname` should be `kubectl logs pods -l run=myrunname`, the pods is really necessary here?

**Comment by erictune** [comment]
Correct, thanks.  Fixed my comment above.

**Comment by AdoHe** [comment]
@erictune clearly, I will add this feature implementation.

**Comment by erictune** [comment]
Sounds good.  You own this issue.  I'll assign to myself for tracking purposes.

**Comment by smarterclayton** [comment]
Interleaving logs like this can be problematic.  This opens up one connection to each node for each logs.  Are we sure we are ready to support this?

**Comment by bgrant0607** [comment]
Related: #8884, #20293

**Comment by smarterclayton** [comment]
(note, I want this too, I just want to be sure we're ready to blow up the master)

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by erictune** [comment]
I have written short shell scripts to do this several times.  If you need
to stop people from blowing up the master then your solution should work
for that case too.

That said, it would be polite for this tool to make the connections
sequentially, not in parallel.

**Comment by kargakis** [comment]
@erictune how about supporting `kubectl logs job/` / `kubectl logs rc/` / etc.?

**Comment by kargakis** [comment]
Note that we have already the code in place for logs to support different resources while maintaining backwards compatibility (`kubectl logs PODNAME`)

**Comment by erictune** [comment]
sgtm.

**Comment by smarterclayton** [comment]
Yeah, -l + support for deployments, rc, jobs, etc will be valuable.  We
should also make the parallel behavior clear and potentially limited on the
client side (if you open 50 log sessions to the master you'll be taking
1/8th of the available simultaneous connections to the server in a default
config, etc)

**Comment by erictune** [comment]
I'm fine with it refusing to allow `-f` when a selector is used (both `-l`
and `kubectl logs jobs/foo` cases).
That would not require parallel connections.

I'd also be fine with defaulting `--tail=10` in those cases.

**Comment by smarterclayton** [comment]
Yeah, omitting follow makes this much easier, with a default tail.

**Comment by erictune** [comment]
this would be useful for getting status of test jobs for Helm testing.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/32752
