### ISSUE TITLE
Flannel builder fails with connection issues

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#19871]
Started today: http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-flannel/
```
08:43:01 + bash -
08:45:08 
curl: (7) couldn't connect to host
08:45:08 Recording test results
08:45:08 ERROR: Step ‘Publish JUnit test
```

We install flannel from a tarball on gcs https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/flannel/init.sls#L9. @kubernetes/goog-testing standard build failure or cause for concern?

**Comment by ihmccreery** [comment]
I think Jenkins is having some networking trouble; @ixdy is investigating.

**Comment by bprashanth** [comment]
Note that the latest failure message seems to correlate with the other builders, but none of them suffered from "couldn't connect to host", so checking that this

**Comment by ixdy** [comment]
dupe of #19875
