### ISSUE TITLE
Unable to run e2e tests from gce VM with cloud-platform scope

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#19878]
I've been doing development from a GCE VM, and tried kicking off the e2e tests, but get the following error starting them up after the cluster has been created, despite the VM having the cloud-platform scope on it which gives it full access to everything in the project:

```
Project: arob-k8s
Zone: us-central1-b
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.5.707+a8f3235d3a9c24-dirty", GitCommit:"a8f3235d3a9c24c17b53b33f796cd7d05e90e85c", GitTreeState:"dirty"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.5.707+a8f3235d3a9c24-dirty", GitCommit:"a8f3235d3a9c24c17b53b33f796cd7d05e90e85c", GitTreeState:"dirty"}
2016/01/20 05:17:53 e2e.go:305: Step 'get status' finished in 905.275891ms
Your active configuration is: [default]

Project: arob-k8s
Zone: us-central1-b
2016/01/20 05:17:54 e2e.go:303: Running: Ginkgo tests
Setting up for KUBERNETES_PROVIDER="gce".
Your active configuration is: [default]

Project: arob-k8s
Zone: us-central1-b
Jan 20 05:17:56.460: INFO: Fetching cloud provider for "gce"

I0120 05:17:56.475246    1758 gce.go:196] Using DefaultTokenSource &oauth2.reuseTokenSource{new:(*oauth2.tokenRefresher)(0xc2083c1230), mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(0xc208401260)}
F0120 05:17:56.520773    1758 e2e_test.go:124] Error building GCE provider: Get https://www.googleapis.com/compute/v1/projects/arob-k8s/global/networks?alt=json: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_grant"
}

Ginkgo ran 1 suite in 155.967116ms
Test Suite Failed
```

My VM has no trouble accessing the project's networks using gcloud, so there's something wrong with our code:

```shell
$ gcloud compute networks list --project=arob-k8s
NAME    IPV4_RANGE    GATEWAY_IPV4
default 10.240.0.0/16 10.240.0.1
e2e     10.240.0.0/16 10.240.0.1
```

cc @saad-ali since this is similar to the problem observed in #17276, except that it's still happening.
cc @cjcullen because scopes and gce provider

**Comment by saad-ali** [comment]
@a-robinson If you don't provide a service account (via `GCE_SERVICE_ACCOUNT` parameter), then the GCE client will fall back to using the `DefaultTokenSource` which looks at a [number of locations](https://github.com/golang/oauth2/blob/master/google/default.go#L47) to try and discover the credentials to use. It uses a JSON file (`$HOME/.config/gcloud/application_default_credentials.json`) created by the gcloud command-line tool giving it the same permissions as the tool. When that file does not exist, and the code is being executed within GCE, it fetches the "default service account" credentials from the metadata server. When these credentials are not sufficient you get the `400 Bad Request` while `Fetching cloud provider for "gce"`. 

So to fix this, either make sure that the `$HOME/.config/gcloud/application_default_credentials.json` file exists with credentials that have access to the node/master machines or set the `GCE_SERVICE_ACCOUNT` environment variable with a GCE service account that has access to all the machines.

See https://github.com/kubernetes/kubernetes/pull/17276#issuecomment-159717244 and https://github.com/kubernetes/kubernetes/pull/17747

**Comment by a-robinson** [comment]
Thanks for the details. The problem wasn't that I didn't have a file at `$HOME/.config/gcloud/application_default_credentials.json`, but that there was apparently something malformed about it. Deleting it fixed the problem.

**Comment by jlowdermilk** [comment]
For someone else who encounters the same problem, `$HOME/.config/gcloud/application_default_credentials.json` can be restored/reset by running `gcloud auth login`.

**Comment by wonderfly** [comment]
For newer `gcloud` installations, it is `gcloud auth application-default login`.
