### ISSUE TITLE
Triage many broken k8s e2e "critical builds"

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#19875]
The majority of the k8s e2e tests in critical builds are failing.

**Comment by pwittrock** [comment]
kubernetes-e2e-gce
kubernetes-e2e-gce-autoscaling
* These have had only one failure each, and it looks like the issue listed below may be resolved

>
07:49:20 Kubernetes cluster is running.  The master is running at:
07:49:20 
07:49:20   https://146.148.32.24
...
07:49:51 Unable to connect to the server: dial tcp 146.148.32.24:443: i/o timeout
07:49:51 2016/01/20 07:49:51 e2e.go:309: Error running up: exit status 1
07:49:51 2016/01/20 07:49:51 e2e.go:305: Step 'up' finished in 7m14.579262533s
07:49:51 
2016/01/20 07:49:51 e2e.go:141: Error starting e2e cluster. Aborting.

kubernetes-e2e-gce-parallel
* Seeing a lot of failed test - seems to have started the e2e cluster successfully 

kubernetes-e2e-gce-reboot

>
Could not connect to host
Usually due to a failure to connect to github.
Indication 1

**Comment by alex-mohr** [comment]
There appear to be a bunch of correlated e2e failures that share networking issues: creating a cluster and pods not being reported as ready.  Given that they started across ~all jenkins builds, suspicion is a systemic issue either on the jenkins master or the GCE network.

**Comment by pwittrock** [comment]
I saw this message on a Jenkins PR builder e2e build:

>
Jan 20 19:22:32.961: INFO: Get service account default in ns e2e-tests-kubectl-6ov22 failed: Get https://104.154.90.226/api/v1/namespaces/e2e-tests-kubectl-6ov22/serviceaccounts/default: dial tcp 104.154.90.226:443: i/o timeout

Since the Jenkins PR builder is a separate machine, this may not be limited to the CI Jenkins

**Comment by pwittrock** [comment]
Looking at the jenkins-master in the dev console, the cpu usage has been ~50% for the past 2 days, so that should not be the problem.  Have we contacted GCE oncall about what we are seeing?

**Comment by pwittrock** [comment]
FYI @ixdy

**Comment by ixdy** [comment]
Seems to have recovered more or less. Still tracking internally.
