### ISSUE TITLE
Client transports no longer implement WrappedRoundTripper()

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#19885]
https://github.com/kubernetes/kubernetes/pull/16126 removed the implementations of `WrappedRoundTripper() http.RoundTripper` present in all of the client transports.

This is required to allow the proxy handlers to drill down and use the Dial and TLSConfig data in the innermost http.Transport when doing upgrade requests.

@krousey

**Comment by liggitt** [comment]
This implementation depends on transports constructed from kubeconfig files conforming to the `RoundTripperWrapper` interface:

```
type RoundTripperWrapper interface {
	http.RoundTripper
	WrappedRoundTripper() http.RoundTripper
}

type DialFunc func(net, addr string) (net.Conn, error)

func Dialer(transport http.RoundTripper) (DialFunc, error) {
	if transport == nil {
		return nil, nil
	}

	switch transport := transport.(type) {
	case *http.Transport:
		return transport.Dial, nil
	case RoundTripperWrapper:
		return Dialer(transport.WrappedRoundTripper())
	default:
		return nil, fmt.Errorf("unknown transport type: %v", transport)
	}
}
```

**Comment by krousey** [comment]
Interesting. We can certainly add them back for now, but this seems like something that should be done another way. Why rely on a http.RoundTripper to supply a dialer and TLS config, especially when wrapping them is such a common idiom? Wouldn't it be better for the proxy/upgrade handlers to just know what Dialer and TLSConfig they should use instead of trying (and failing in this case) to discover from a naively wrapped http.RoundTripper?

**Comment by liggitt** [comment]
The proxy code handles generically proxying/upgrading connections to node, pod, and service back ends. The transport to use is part of what is handed to the proxy code. 

I'm fine with a refactor, but I'd like to unbreak this asap and work on a better solution at leisure. This is seen to have an effect when connecting to things with custom diapers like GKE and a tunneling dialed.

**Comment by krousey** [comment]
Agreed whole-heartedly with quick fix + thinking about a better way. Are you doing this? Or should I?

FWIW this is a similar situation to http.Transport.CancelRequest(). People naively wrapped the round tripper, http.Client's Timeout would no longer worked. They ended up bypassing the need to type assert down to that method by adding a Cancel channel to the http.Request object.

**Comment by liggitt** [comment]
Also, there are e2e tests that should have caught this, but they may have been conditionalized away in GKE :-/

**Comment by liggitt** [comment]
If you can, I can do a quick review
