### ISSUE TITLE
e2e failure: Job should run a job to completion when tasks succeed

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#19898]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/14712

Unsure if this is cause or noise, but might be a node not ready issue and not a specific-to-this-test issue.

@erictune and @dchen1107 as last people to touch these tests in #15389 but bounce elsewhere if needed?  Note blocked merge queue for 30 minutes today.

14:27:34 Jan 20 14:26:57.020: INFO: Waiting up to 1m0s for all nodes to be ready
14:27:34 Jan 20 14:26:57.026: INFO: Condition Ready of node e2e-test-parallel-minion-prtl is false instead of true. Reason: KubeletNotReady, message: container runtime is down
14:27:34 Jan 20 14:26:59.034: INFO: Condition Ready of node e2e-test-parallel-minion-prtl is false instead of true. Reason: KubeletNotReady, message: ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now
[more PodCIDR not sets]
14:27:34 Jan 20 14:27:27.034: INFO: Condition Ready of node e2e-test-parallel-minion-prtl is false instead of true. Reason: KubeletNotReady, message: ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now
14:27:34 STEP: Destroying namespace "e2e-tests-job-tw5r8" for this suite.
14:27:34 
14:27:34 
14:27:34 • Failure [1033.825 seconds]
14:27:34 Job
14:27:34 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/job.go:198
14:27:34   should run a job to completion when tasks succeed [It]
14:27:34   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/job.go:58
14:27:34 
14:27:34   Expected error:
14:27:34       <*errors.errorString | 0xc208188280>: {
14:27:34           s: "timed out waiting for the condition",
14:27:34       }
14:27:34       timed out waiting for the condition
14:27:34   not to have occurred
14:27:34 
14:27:34   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/job.go:57

**Comment by dchen1107** [comment]
@erictune Can you take a look at this one? Looks like it is an expected failure since ConfigureCBR0 is not done yet. But the node is up for a while, and reboot tests are not included in parallel build. Could be some kernel panic, then the node rebooted?

**Comment by erictune** [comment]
I reviewed the kubelet log of the bad kubelet (e2e-test-parallel-minion-prtl).

Log available via 
```
gsutil cp gs://kubernetes-jenkins/logs/kubernetes-e2e-gce-parallel/14712/artifacts/104.197.47.216:22-kubelet.log .
``` 

I assume that the jenkins machine is using pacific time and the nodes use UCT, so `14:26:59.034` in jenkins logs is `22:26:59.034` in kubelet log.

Very near that time in the kubelet log, it looks like kubelet gives a 500 to a healthz check:
```
I0120 22:26:55.834103   18779 server.go:1050] GET /healthz: (74.144µs) 500
goroutine 244 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc2080ef500, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2080ef500, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
net/http.Error(0x7f211e4ddec8, 0xc2080ef500, 0xc2085c8660, 0x58, 0x1f4)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
k8s.io/kubernetes/pkg/healthz.func·002(0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/healthz/healthz.go:109 +0x46e
net/http.HandlerFunc.ServeHTTP(0xc2084b6040, 0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/emicklei/go-restful.func·011(0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:278 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc20849ad60, 0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208250a20, 0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        /usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/emicklei/go-restful.Container.ServeHTTP(0x0, 0x0, 0x0, 0xc208242580, 0xb, 0x10, 0xc208250a20, 0x0, 0x2bec1e0, 0x0, ...)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:264 +0x4f
k8s.io/kubernetes/pkg/kubelet/server.(*filteringContainer).ServeHTTP(0xc20849ace0, 0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        <autogenerated>:30 +0x8a
k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc208250990, 0x7f211e4dde90, 0xc2088214a0, 0xc2086b1d40)      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:1049 +0x13d
net/http.serverHandler.ServeHTTP(0xc2082ab740, 0x7f211e4dde90, 0xc2088214a0, 0xc2086b1d40)
        /usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.( [[curl/7.26.0] 127.0.0.1:39597]
```

I think the kubelet crashed as a result of that 500.  I'm judging from the fact that I don't see pid 18779 after that in the log, and I see the line:
```
I0120 22:26:57.864302   19433 server.go:289] Successfully initialized cloud provider: "gce" from the config file: ""
```

It takes the kubelet until 22:27:28.332746 to be ready:
```
I0120 22:27:28.332746   19433 kubelet.go:2628] Recording NodeReady event message for node e2e-test-parallel-minion-prtl
```
The test framework give up at `14:27:27.034` which is `22:27:27.034`.  So, the test gave up 1 second before the kubelet came back up.

So, this is definitely a node-related failure.

**Comment by erictune** [comment]
I filed issue for the kubelet failures. #20173


Although extending the wait from 1m to say 2m would have avoided this flake, I think that the first fix is to remove the kubelet crash, and only consider extending the timeout if it proves impossible to avoid all crashes.

**Comment by erictune** [comment]
Supervisord log confirms kubelet restarts.
