### ISSUE TITLE
Some client files use incorrect case for resource name

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#19894]
Both https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/persistentvolumeclaim.go and https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/replication_controllers.go, and possibly others, use incorrect case in the `Resource("")` sections. I'm not quite sure how it's working at all, since when I start a cluster and try to use the path, I get a 404, e.g. `https://146.148.88.233/api/v1/namespaces/default/persistentVolumeClaims`:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}
```

@madhusudancs (who reported this): All lowercase is correct, like I thought.

@caesarxuchao Presumably your generated client will not have this, right? In that case, I think all that needs to be done here is to understand why this works currently. I'm not entirely sure if auto-fixing the case is a feature or a bug.

**Comment by caesarxuchao** [comment]
My generated client also has the camel case: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/typed/generated/legacy/unversioned/persistentvolume.go#L108.
It should be a one-line fix.

**Comment by madhusudancs** [comment]
@lavalamp Thanks for confirming.
