### ISSUE TITLE
should introduce a knob to enable quorum read of etcd for HA

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kubernetes#19902]
Copied from #19816 
@mqliang  said

> One problem is that we may need enable quorum read when apiserver send read request to etcd, otherwise ControllerManager/Scheduler/Kubelet may get old data.
> 
> we found that ControllerManager/Scheduler/Kubelet may get old data since apiserver doesn't quorum read etcd. To solve this problem we add an option to api-server to enable quorum read, but it make read less effective.
> 
> I am not sure such a solution is fine to community. I am glad to upstream this to community if it looks good.
> 
> There are two cases where we may read old data if we have multi api-server:
> 
> 1) When a etcd member is isolated from etcd cluster, we can still read from it(but all the write request sent to the isolated member will failed). If unfortunately nginx forward some read request to the isolated member, those read request will get old data.
> 
> 2) Consider the following case:
> 
> A write request(e.g. ?key=hello&value=world) was forward to apiserver-1 and then forward to etcd-1, etcd-1 will return 200 indicating the write request was succeeded if the data has been written to a majority of members.(for example, written to etcd-1 and etcd-2)
> Almost immediately, a read request(?key=hello) was forward to etcd-3, if api-server doesn't enable quorum read, this read request will failed(key not found) since the data has not been synced to etcd-3.

**Comment by magicwang-cn** [comment]
@mqliang what's the scale of your cluster?(`how much nodes?`)

**Comment by mqliang** [comment]
@ magicwang-cn currently ~500

**Comment by lavalamp** [comment]
I agree that we need this knob and I'd be happy to accept a PR adding it.

**Comment by smarterclayton** [comment]
As a stop gap to a future client enhancement to accept read horizons, this seems ok to me.

**Comment by smarterclayton** [comment]
We think we may be seeing this in a customer environment with a large cluster, where monitorNodeStatus() gets the List of nodes and doesn't get all of them.  That raises the concern of why monitorNodeStatus isn't using a cache store and list watcher (which is going to have the same behavior, except it will now start seeing its own watch events, but practically that's not a real issue).  The node controller would have to guarantee that it doesn't "walk back in time" on a relist - I don't know that list watcher has that check today.

**Comment by wojtek-t** [comment]
I think that list watcher doesn't have such check, but it's highly unprobably for it to "walk back in time". And it should be very straighforward to add a check for it.

**Comment by smarterclayton** [comment]
I would probably like the client even to have that logic - however we would
have to deserialize the body today for that so it's probably more complex
than not.  In the future we discussed returning a header always that
represented the resource version of the resource, which would be easier for
a client to indicate.

On Wed, Feb 3, 2016 at 7:26 AM, Wojciech Tyczynski <notifications@github.com

**Comment by sttts** [comment]
This topic seems to repeatedly surprise people when setting up HA cluster. Compare https://github.com/coreos/tectonic-installer/issues/400 and https://github.com/openshift/origin/issues/14520. We know that `--enable-quorum-read` causes performance problems, leaving it out in HA leads to wrong behaviour. What's our plan? Should we address this in 1.8? /cc @kubernetes/sig-api-machinery-misc 

Just a possible way forward we could switch to opt-out for quorum reads (via `GetOptions`) and address performance bottlenecks with e.g. informers. Is that feasible?

**Comment by enj** [comment]
There is ongoing discussion at openshift/origin#14520 but we should try to consolidate it here.

So I was under the assumption that nothing in Kube used quorum and only the OAuth tokens in Origin used it.  Not sure about the former.

That being said a conversation I had with @liggitt recently made me think that we could enable quorum for everything with etcd v3 and not kill performance.

**Comment by sttts** [comment]
@wojtek-t @xiang90 can you comment on quorum+etcd3?

**Comment by enj** [comment]
https://github.com/coreos/etcd/issues/6829#issuecomment-259564546 and https://coreos.com/blog/etcd-3-1-announcement.html seem relevant.

**Comment by timothysc** [comment]
quorum read is the default for v3, and v3.1 has helped the iop issue.  There were several issues opened about this a while ago and the plan of record is to update to 3.1.X in 1.8.

**Comment by smarterclayton** [comment]
Does anyone have experience running very large clusters with quorum read on
and HA?  We realized in openshift we only had quorum reads on for 1
specific resource, and even that was a massive spike in IO.  Turning on
quorum for everything will at least double the number of quorum reads
(25-50% of reads on those very large clusters were quorum, there rest were
not).

My concern is anyone at scale who doesn't have this on already is going to
see a significant change in workload, even on etcd v3, unless they've
tested.

**Comment by timothysc** [comment]
@mffiedler had the experimental data and can compare against an upstream deploy.  We had seen a  very large drop when running the same experiment against 3.1.X months ago.  

/cc @rrati @jeremyeder

**Comment by smarterclayton** [comment]
There are two angles to this:

1. anyone who needs to do a "live read" in order to get causal consistency
is unlikely to know that they need to ask for a quorum read (it's very
common to not think about this when designing code) - that's 5-10% of
actual controllers
2. GC needs causal reads for everything, but if we turn it on for
everything that's a big hammer, but it might be the right default for small
- medium clusters

There's also the angle that changing the cluster default to quorum on
changes the behavior of the system in failures - if you have 3 etcd members
but are in partition, and quorum reads for endpoints are off, a kube-proxy
that gets restarted is going to coast.  If quorum reads are on, the
kube-proxy will start back up and serve nothing.  The error behavior of
quorum read changes as well - you get hard errors which change how
controllers react.  At some point we'll have checkpointing, but not yet.

Can we make "resourceVersion=latest" have meaning and force a quorum read?


On Fri, Jun 9, 2017 at 10:21 AM, Timothy St. Clair <notifications@github.com

**Comment by jeremyeder** [comment]
Very large was still 2x what it was in the prior tests...

**Comment by timothysc** [comment]
> Very large was still 2x what it was in the prior tests... 

What are the results for disabling multi-tenant sdn?

**Comment by jeremyeder** [comment]
Not sure -- we don't run without it.  Does the multi-tenant SDN hit oauth tokens? @liggitt

**Comment by liggitt** [comment]
> Does the multi-tenant SDN hit oauth tokens?

shouldn't... it runs with infrastructure credentials which are cert-based

**Comment by xiang90** [comment]
3.1's q-read does not touch disk at all. It is also faster than pervious non-q-read under heavy load. I strongly suggest to give etcd 3.1 a try.

**Comment by smarterclayton** [comment]
I did a quick prototype of letting the GC controller indicate it wants a Live read (which is what it's actually doing).  But I think it is probably just simpler to turn on quorum reads for everything and introduce a way to opt out (which technically we already have with `ResourceVersion: "0"`).

**Comment by sttts** [comment]
> turn on quorum reads for everything and introduce a way to opt out

Where do you want to opt-out?
