### ISSUE TITLE
kube::util::wait-for-jobs fails to set fail on fail

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#19908]
kube::util::wait-for-jobs has a fail count which is declared `local`.  cluster/gce/util.sh does this:

```
  # Wait for last batch of jobs
  kube::util::wait-for-jobs || {
    echo -e "${color_red}${fail} commands failed.${color_norm}" >&2
  }
```

But if wait-for-jobs fails, fail is not set.  This gives an error like `cluster/gce/util.sh: line 699: fail: unbound variable`  e.g. https://github.com/kubernetes/kubernetes/pull/17919#issuecomment-173378103

cc @quinton-hoole

**Comment by justinsb** [comment]
Introduced in 22cfa5ea7eaedfab9bcbba442e2f6918254cf91e I think, so cc @mikedanese

**Comment by mikedanese** [comment]
Oops thanks for catching.
