### ISSUE TITLE
Liveness probe fails with "use of closed network connection"

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#19904]
A GKE user has seen random yet frequent "use of closed network connection" errors from http liveness probes. It was confirmed that the container in question was running fine the entire time.

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}
```

This is _not_ caused by #15643 since the fix for that was included in v1.1.1.

I suspect that this is caused by https://github.com/golang/go/issues/9405, where request timeout errors aren't reported correctly. Opening this issue to track similar failures.

**Comment by scotloach** [comment]
I am seeing this on one of my containers.

**Comment by yujuhong** [comment]
According to https://github.com/golang/go/issues/9405, this will be fixed (i.e., the message will show the timeout error correctly) with go 1.5.

@scotloach, perhaps you can try increasing the probe timeout to see if it helps.

**Comment by rvrignaud** [comment]
Hi @yujuhong,

I'm the user who created the GKE support ticket. I increased probe timeout and I didn't got the issue anymore.
So except the misleading error message this seems to work correctly.

Thanks for your help.
Regards

**Comment by timstclair** [comment]
https://github.com/kubernetes/kubernetes/issues/18704 might be related to this? /cc @vishh

**Comment by vishh** [comment]
Thanks for the tip @timstclair. Indeed this is the same error that the e2e is catching. Given that we have already upgraded our build scripts to go1.5, I hope that the e2e flakes will no longer happen.

**Comment by yujuhong** [comment]
> Thanks for the tip @timstclair. Indeed this is the same error that the e2e is catching. Given that we have already upgraded our build scripts to go1.5, I hope that the e2e flakes will no longer happen.

The test will still fail since the liveness probe will fail due to probe timeout. To eliminate the flake, we should increase the timeout for the probe.

**Comment by vishh** [comment]
@yujuhong: The current timeout (15s) is sufficient for 99 out of 100 runs. Do you think it's an issue with the timeout?

**Comment by yujuhong** [comment]
*If* the frequency of the flake is not acceptable, we'll need to change the timeout. If it's okay for now, the test can stay as it is :)

**Comment by vishh** [comment]
The ideal goal is no flakes :) So I updated the initial delay for now.

**Comment by scotloach** [comment]
Increasing the probe timeout to 15 seconds solved this for me, thanks for the suggestion.
