### ISSUE TITLE
AWS cloudprovider restricts number of EBS volumes

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#19920]
The current AWS cloudprovider code must assign a mountpoint from the set of available mountpoints, but the list of mountpoints is hard-coded and probably too small:

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L805-L813

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html

We should expand the list, so that the limit that will be imposed by #19880 can be honored.

**Comment by bprashanth** [comment]
So it sounds like we're allowed 40 on AWS but we impose an artificial limit of f->p (https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L877). Why not jump bump it up? @justinsb assuming this is correct, it sounds easy enough to attempt for 1.2? (O(days))

**Comment by bprashanth** [comment]
I think this is fixed because we're now going 
```
for first := 'b'; count < DefaultMaxEBSVolumes; first++ {
```
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L913

When previously we were going from 'f' upto 'p' (I didn't understand my own previous comment for a moment). Please re-open if it's not fixed.
