### ISSUE TITLE
Watch doesn't work for apis/extensions with namespace 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#19939]
- This works http://127.0.0.1:8080/apis/extensions/v1beta1/watch/deployments?resourceVersion=66 (used by controller manager) 
- This doesn't work (gives me no response) http://127.0.0.1:8080/apis/extensions/v1beta1/watch/namespaces/default/deployments?resourceVersion=66 (used by kubectl)

api/v1 works fine, but I can reproduce this for other apis/extensions resources (deployments, hpa, ...). 

cc @caesarxuchao @nikhiljindal @lavalamp

**Comment by nikhiljindal** [comment]
Can you explain what you mean by "not works". Whats the response?
Is it a 404?

@kubernetes/sig-api-machinery

**Comment by caesarxuchao** [comment]
Not 404, just no responses.

**Comment by lavalamp** [comment]
Probably some namespace handling thing is misconfigured in the deployment registry.

**Comment by caesarxuchao** [comment]
Fixed in #19970

**Comment by janetkuo** [comment]
Thanks @caesarxuchao!
