### ISSUE TITLE
Markdown to HTML conversion excludes go template content inside double curly braces

### ISSUE THREAD

**Issue by hobti01** [kubernetes/kubernetes#19949]
For example:
https://github.com/kubernetes/kubernetes/blob/v1.1.4/docs/user-guide/images.md
![markdown](https://cloud.githubusercontent.com/assets/4631304/12495587/c9293ed2-c090-11e5-9f67-db78c930326b.png)
Compared to:
http://kubernetes.io/v1.1/docs/user-guide/images.html
![html](https://cloud.githubusercontent.com/assets/4631304/12495588/c92cd68c-c090-11e5-8cb3-51d914c8fae7.png)

Needless to say, this makes the documentation a bit confusing. :)

**Comment by bgrant0607** [comment]
Sounds like we need to add some escaping during translation.
https://github.com/kubernetes/kubernetes/blob/gh-pages/_tools/import_docs.sh

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by bgrant0607** [comment]
cc @kubernetes/docs

**Comment by janetkuo** [comment]
We need to adding `{% raw %}`; ref https://github.com/kubernetes/kubernetes.github.io/issues/85

**Comment by johndmulhausen** [comment]
All instances of this have been fixed by the community due to the bounty program. We can probably close this down.

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
Current docs https://kubernetes.io/docs/concepts/containers/images/ do not have this problem:

![image](https://user-images.githubusercontent.com/159209/27013231-c397d652-4e94-11e7-827a-d61c81d87b9b.png)


/close
