### ISSUE TITLE
Make release tooling work with `release-note-breaking-change` label

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#19966]
Per our new `release-note-breaking-change` label, we need to modify our release notes generation tools to work with it.

cc @bgrant0607

**Comment by david-mcmahon** [comment]
I have a standalone tool that is part of a bigger rewrite of our releasing tools.  That can be used for now by our release team.  1.3 will have a new release tool altogether.

**Comment by david-mcmahon** [comment]
https://github.com/kubernetes/release/issues/1
