### ISSUE TITLE
Question about network resource management (especially for switch buffer)

### ISSUE THREAD

**Issue by mitake** [kubernetes/kubernetes#19972]
Hi Kubernetes people,

I have a question about the network management functionality of Kubernetes. Is there a plan for managing buffers of switches from Kubernetes?

Currently, a switch buffer doesn't have a mechanism for isolation that can be used from distributed systems easily. Therefore problems like [microburst](https://www.arista.com/assets/data/pdf/7148sx-ixnetwork-microburst.pdf) can happen. The problem can increase latency so it is critical for user facing interactive systems.

Although there are [some solutions for solving the problem](http://simula.stanford.edu/~alizade/Site/DCTCP.html), they don't seem to be widely used yet. Straightforward solution would be careful capacity planning that tends to produce a situation of over provisioning. In addition, it requires difficult engineering tasks (e.g. voluntary scheduling by applications and operators).

I think Kubernetes is a suitable component for controlling the buffer. If it is possible to add a new resource type of the buffer [like other network resources](https://github.com/kubernetes/kubernetes/blob/master/docs/design/resources.md#future-network-bandwidth), the management of switch buffer would be easier for application developers and operators. Fortunately, recent white box switches provides their SDKs for managing buffers. Connecting Kubernetes and these SDKs would be possible.

I'm very new to Kubernetes. I'm happy if I can hear your opinions.

**Comment by thockin** [comment]
Is this what you are looking for?

http://conferences.sigcomm.org/sigcomm/2015/pdf/papers/p1.pdf

I think this is something we'd be looking to community to bootstrap, and
tell us what is needed to glue it all together.

**Comment by mitake** [comment]
Hi @thockin , thanks for your reply!

Yes, I hope such a functionality for DC network (maybe something like [this](http://research.microsoft.com/pubs/80693/vl2-sigcomm09-final.pdf)). If Kubernetes can provide such an  isolation mechanism, problems like microburst and [outages by malicious software](https://www.usenix.org/conference/hotos13/session/guo) can be solved.

I'm talking about this idea with networking people in my team now and will let you know about more concrete idea soon.

**Comment by liljenstolpe** [comment]
There's another paper in this space (related, anyway), with the nice benefit of not requiring integration with the intermediate switching points.  It basically allows any given workload to trade-off jitter and/or latency against bandwidth requirements.

https://www.usenix.org/system/files/conference/nsdi15/nsdi15-paper-grosvenor.pdf

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by cmluciano** [comment]
@mitake Are you still looking into a patch for this?

**Comment by mitake** [comment]
@cmluciano sorry for too long silence, I'm still interested in this kind of network resource management but my priority is shifting to RDMA related stuff (e.g. QP of RDMA). I'm not sure I can work on ethernet related things in the near future...

**Comment by cmluciano** [comment]
Since this this doesn't have a clear owner, we probably want to close it for now. cc @thockin

**Comment by byronyi** [comment]
@mitake I do not understand why you would like to manage switch buffer in k8s. There are a number of works on data center congestion control and flow scheduling (DCTCP, D2TCP, PDQ, PIAS, MQ-ECN, just to name a few), and all of them require collaboration between end host and switch (some even new NIC/switch hardware) to accomplish switch buffer management. Typically the algorithm is implemented in switch, and the end-host only does some marking to differentiate QoS for different switch queues).

Would you elaborate on the specific use case of this feature you request?

**Comment by mitake** [comment]
@byronyi I thought integrating switch buffer management and application deployment would make managing a cluster easier because the switches are multiplexed by the applications. k8s knows what applications are running on the cluster so it would a suitable place for the management e.g. judging a required congestion control is possible based on the cluster's state.

Currently I don't have motivating examples because the problems related to the buffer management don't happen in a small scale cluster. But I'm thinking that generally speaking distributed systems need network resource management mechanisms but there's no standard ways. If k8s can provide the functionalities, it would result interesting applications in the future.

**Comment by byronyi** [comment]
I use to work with some of the best guys in this field (congestion control and flow scheduling in data center networks), so hopefully I know a little bit of what you are trying to accomplish here. The problem with switch buffer management is its fast-paced temporal dynamics, not the global knowledge known by a cluster scheduler. Note we are dealing with 10-100 Gbps per link and hundreds of millions of packets per link in a typical data center network; the buffer allocation of switch could change easily in a scale of micro seconds. Take [TCP incast](http://www.pdl.cmu.edu/Incast/) as one motivating example; it represents a classic buffer over-subscription (thus a mis-allocation issue) because the shallow switch buffer is saturated with a single packet from each of the >1000 TCP flows starts sending in <1ms. In such dynamics it is very hard to design a centralised controller in k8s and allocate switch buffer in a timely manner, which may have problems to achieve we called [work conserving](https://en.wikipedia.org/wiki/Work-conserving_scheduler), i.e. you will be wasting the network bandwidth because you cannot allocate switch buffers fast enough.

One particular work that shares a similar spirit of your idea is FastPass from FaceBook, in SIGCOMM'14. If I remember it correctly, it kinda allocating the switch buffer, but through scheduling each packet to be transmitted. By doing that, it actually minimises buffer occupation and could achieve extremely low queuing delay and thus messaging latency of the whole network.

**Comment by mitake** [comment]
@byronyi thanks for your explanation. As you point out, the frequent controlling shouldn't be performed directly by k8s itself. I imagined that k8s can statically allocate (or at least recognize) what kind of control can be made by other higher level mechanisms. It would be similar to that resources allocated by k8s can be redistributed by other frameworks. How do you think about it?

**Comment by byronyi** [comment]
@mitake If you are talking about relatively static allocation of switch buffers and link capacity, there are works in this direction as well. For example, in HULL (High-bandwidth Ultra-Low Latency) in NSDI'12, network packets are classified into different categories, i.e. latency sensitive or bandwidth constraint. Then those packets will be marked differently in headers at end-host, queued with respect to different switch queues with different buffer allocation policies. K8s could certainly serve to mark those packets, and there are a number of ways doing so (the Linux traffic control or tc, Open vSwitch, customized tos bit in socket options, etc.), but the most important part is still collaboration with switches, which more or less have to be configured manually. Of course you could also look into those newer SDN switches or even programmable switches (like P4), and those provides standard API to manage switch, for example, OpenFlow. But it is largely integration work, and highly dependant on how the network of each particular user is architected. I believe this has way beyond the scope of k8s, and frankly speaking, network systems are still lagging behind in terms of standardisation of interfaces than ordinary Linux end-host (where we have VMs before container), and it too much effort at this stage to incorporate such features into k8s.

**Comment by mitake** [comment]
@byronyi sorry for my very late reply. I understood your opinion. Currently I'm not facing emergent problems so let's close this issue for now. But if the standardization efforts in the networking side can be mature in the future, having a way of controlling them from k8s would be valuable, I think.
