### ISSUE TITLE
kubernetes mount volume (hostdir) to container

### ISSUE THREAD

**Issue by drngsl** [kubernetes/kubernetes#19974]
Hi!
I want to provide volume to container, but the result is not what i want.

kubernetes version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}

docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

pod template
{
  "kind": "Pod",
  "spec": {
        "volumes": [{"name":"wordpress", "hostDir":{"path": "/mnt/nfs/wordpress_a"}}],
    "containers": [{
          "name": "dockerwordpress",
          "image": "wordpress",
          "args": [],
          "volumeMounts": [{"name": "wordpress", "mountPath": "/mnt/nfs/wordpress_a"}],
          "env": [
            {"name": "WORDPRESS_DB_HOST", "value": "10.0.0.12:3306"},
            {"name": "WORDPRESS_DB_USER", "value": "root"},
            {"name": "WORDPRESS_DB_PASSWORD", "value": "Huawei@123"}],
          "ports": [{"containerPort": 80}]}]},
  "apiVersion": "v1",
  "metadata": {
  "labels": {"id": "podvol"},
  "name": "podvol"
  }
}

after I deploy it, and i inspect the configuration of container on minion node.
"Volumes": {
        "/dev/termination-log": "/var/lib/kubelet/pods/cc5e0183-c0ae-11e5-88d5-fa163ee7f5b3/containers/dockerwordpress/8021dbb054a1df840969efa68f534cd108d183278341ba1f688678c03aeb6898",
        "/mnt/nfs/wordpress_a": "/var/lib/kubelet/pods/cc5e0183-c0ae-11e5-88d5-fa163ee7f5b3/volumes/kubernetes.io~empty-dir/wordpress",
        "/var/www/html": "/var/lib/docker/vfs/dir/f20f1edb22e8d87ba8c579542c023e4a423e0fc81acade2264a870968a53ed52"
    },
    "VolumesRW": {
        "/dev/termination-log": true,
        "/mnt/nfs/wordpress_a": true,
        "/var/www/html": true
    }

obviously, the mount key-value pair "/mnt/nfs/wordpress_a": "/var/lib/kubelet/pods/cc5e0183-c0ae-11e5-88d5-fa163ee7f5b3/volumes/kubernetes.io~empty-dir/wordpress" is not I want.

what I want is "/mnt/nfs/wordpress_a": "/mnt/nfs/wordpress_a".
So, How can I resolve it?
Thanks!

**Comment by thockin** [comment]
```
"volumes": [{"name":"wordpress", "hostDir":{"path": "/mnt/nfs/wordpress_a"}}],
```

Try `hostPath` rather than `hostDir`.  I am so confident in my answer that I am going to close this, and you can reopen if I am wrong :)

**Comment by drngsl** [comment]
@thockin , Thanks very much.
It does work!
