### ISSUE TITLE
Allow extra A records via Service annotations

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#19975]
People may have a number of different reasons for having additional A records in a Service, we should enable users to add annotations to services which then create arbitrary A records that map to that service.

For example, users may want foobar.internal.company.com to resolve to a service endpoint.  This would also help users fit their services into alternate DNS schemas.

**Comment by brendandburns** [comment]
@thockin @kubernetes/sig-network

**Comment by bprashanth** [comment]
why not just CNAME?

**Comment by brendandburns** [comment]
CNAME seems fine too, I don't really care one way or the other, though CNAME seems more indirect...

**Comment by brendandburns** [comment]
This came up in the context of a user wondering what SAN to use in their HTTPS cert, and not being 100% certain they wanted to use our DNS scheme for the SAN.

**Comment by bprashanth** [comment]
A client accessing the service from within the cluster should just go over HTTP while the same client accessing the same name from outside needs TLS. Then theyd create the cert for the outside service name (company.com), and add a CNAME in the cluster that redirects company.com -> cluster.svc. 
Either way you'd have a in cluster proxy that's aware of both DNS names. Roughly what you were thinking?

**Comment by thockin** [comment]
You want to make alt-names for a Service or put extra endpoints into it?  I
assume the former.

1) How do you ensure uniqueness of names?
2) How do you ensure security (e.g. no name hijacking)?
3) Our default DNS (which we could change) can only serve 1 domain
(cluster.local by default).

**Comment by brendandburns** [comment]
@bprashanth there are plenty of companies (eg finanacial) who have to have TLS even inside the cluster.

@thockin 

1) I'd be ok with <service>.<namespace>.<user-supplied-suffix> that would ensure uniqueness
2) We can set a whitelist of acceptable domains in kube-dns when the cluster adminstrator creates the kube-dns pod.
3) Not sure what you mean by "default DNS" does that mean the way that we set up sky-dns in the Pod?  That seems like a poor limitation.

**Comment by brendandburns** [comment]
though honestly, I'm not sure I care about uniqueness.  Have kube-dns fire an event if it detects a conflict.  This seems like one of those cases where restricting user freedom because there is a sharp edge out there somewhere is a bad idea.

**Comment by thockin** [comment]
On Thu, Jan 21, 2016 at 9:41 PM, Brendan Burns <notifications@github.com> wrote:
>
> @bprashanth there are plenty of companies (eg finanacial) who have to have TLS even inside the cluster.
>
> @thockin
>
> 1) I'd be ok with .. that would ensure uniqueness
> 2) We can set a whitelist of acceptable domains in kube-dns when the cluster adminstrator creates the kube-dns pod.
> 3) Not sure what you mean by "default DNS" does that mean the way that we set up sky-dns in the Pod? That seems like a poor limitation.

SkyDNS (our default DNS server, which could be replaced) only serves one domain.

This overall idea is certainly something useful, but it needs some
design to smooth out as many rough edges as possible.  An alternate
model for thinking about this is "external" DNS.  Suppose you have an
external DNS service that handles mycompany.com.  Could we define a
mechanism by which we program this external DNS for Services?

**Comment by bprashanth** [comment]
> @bprashanth there are plenty of companies (eg finanacial) who have to have TLS even inside the cluster.

HTTP was just an example, all I'd expect them to care about is:
1. not including the kubernetes DNS name in the company.com cert. They could easily generate another cert for the kubernets dns name.
2. a portable client (i.e resolving a single name, company.com)

It's just that if you end up at the proxy with company.com it's hard to use different certs via something like SNI

**Comment by ArtfulCoder** [comment]
financial companies that care about TLS within the cluster will not allow for an unsecure DNS Server..

**Comment by brendandburns** [comment]
@thockin another alternative would be to allow the user to program in an extra DNS server for the cluster, but then you are running perililously close to the limit of 3 nameservers.

If we had a split horizon DNS server as part of the cloud provider, then users could just program that...

--brendan

**Comment by brendandburns** [comment]
@bprashanth maybe (probably?) so that means we should implement DNSSEC in sky-dns ;)  (or switch DNS)

**Comment by thockin** [comment]
skydns supports DNSSEC already, though I know exactly nobody who uses it.

**Comment by bprashanth** [comment]
I think we should just start with cluster PKI, so we can issue certs for cluster services and have the CA cert installed in containers.  Otherwise even if the cert is signed by some company.com's private CA the root won't be in the container where the client is running.

**Comment by thockin** [comment]
I'm revisiting some DNS-related issues. I think I get this request, but I am struggling with the idea that we would be acting as an authoritative DNS for `company.com`.  Alternatively, it's pretty simple to describe this as a bridge pod that watches Services for a specific annotation and programs upstream DNS from those.

I can imagine a solution that has kube-dns serving multiple domains with some sort of pattern-expansion to massage our names into some customer-centric schema, but I am not sure that's warranted.  I'd like to hear more from people who are really running into troubles in this area.  Getting reliable and useful in-cluster TLS is sort of important.

**Comment by brendandburns** [comment]
@thockin while it seems unlikely that we'd be authoritative for an entire domain like `company.com` it seems quite possible that we would be authoritative for a subdomain, eg. `us-west.clusters.company.com`

**Comment by thockin** [comment]
I think a controller that programs upstream DNS is the right pattern here.
