### ISSUE TITLE
kube-proxy uses the entire forwarding mark

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#19983]
kube-proxy uses the kernel's forwarding mark to tag packets for different types of processing later in the pipeline.  Since it uses all 32 bits of the mark without a mask, it conflicts with Calico's use of the mark.

Could we alter kube-proxy to, for example, use configurable mark and mask?  (With a default to, say, use the top 16 bits so that it's easier to make it work with Calico out-of-the-box.)

Right now Calico has the same bug; we only need 1 bit of the mark at present but we're also setting that without a mask.  We're going to fix that up on our side https://github.com/projectcalico/calico/issues/964.

**Comment by thockin** [comment]
I'm ok with such a change.  I didn't use a bitmask at first exactly because
I presumed other people were using it and I would never find out how to
manage the space :)

proposals/patches are welcome

**Comment by matthewdupre** [comment]
I'm going to start on this now, aiming to get it into the 1.2 release.

The configurable mark/mask option with a non-full default sounds like a good option: I'll go with that for now; any comments welcome.

**Comment by matthewdupre** [comment]
@thockin when is the code freeze for 1.2 going to be?

**Comment by matthewdupre** [comment]
Written almost all the code; just a little bit more tidying up to add (cleaning up old rules with a different mark when adding rules; as well as when starting the userspace proxy).

I'll have a pull request with you on Monday.

**Comment by thockin** [comment]
Please @ me directly, I'll try to prioritize

**Comment by matthewdupre** [comment]
Thanks @thockin: I've opened PR #20496.

**Comment by caseydavenport** [comment]
@thockin - I think this guy can be closed.
