### ISSUE TITLE
Creating service account does not auto generate corresponding secret

### ISSUE THREAD

**Issue by macropin** [kubernetes/kubernetes#19980]
Following the docs http://kubernetes.io/v1.1/docs/user-guide/service-accounts.html I created a service account:

```
 cat > /tmp/serviceaccount.yaml <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
EOF
kubectl create -f /tmp/serviceaccount.yaml
```
Then run `kubectl get serviceaccounts/build-robot -o yaml`:

Output is

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2016-01-22T06:18:29Z
  name: build-robot
  namespace: default
  resourceVersion: "114"
  selfLink: /api/v1/namespaces/default/serviceaccounts/build-robot
  uid: f44ecb14-c0cf-11e5-bc53-08002702ea1b
```
I would expect to see a reference there to the `secrets` generated.

It's also work noting that the `default` system account did not have a secret generated.

System: Fedora 23, Docker 1.91.1, Running on docker as per http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html

**Comment by kelseyhightower** [comment]
@macropin The issue you describe almost feels like your Kubernetes cluster was bootstrapped without the `--service-account-private-key-file=` flag set on the kube-controller-manager. That flag should be set to a filename containing a PEM-encoded private RSA key used to sign service account tokens.

In addition you also need to ensure the [ServiceAccount](http://kubernetes.io/v1.1/docs/admin/admission-controllers.html#serviceaccount) admission controller has been enable which automates the creation of tokens for service accounts. See the docs for services accounts: http://kubernetes.io/v1.1/docs/user-guide/service-accounts.html

**Comment by macropin** [comment]
@kelseyhightower 

You're right, it was not bootstrapped with `--service-account-private-key-file=` I followed  http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html and ran the three docker commands there. As far as I can see that spawns a "controller-manager" container automatically, but the entry point does not have that set.

```
        "Entrypoint": [
            "/hyperkube",
            "controller-manager",
            "--master=127.0.0.1:8080",
            "--v=2"
        ],
```

So where exactly should I be setting `--service-account-private-key-file=` ? This flag is only mentioned twice in the documentation.

Thanks

**Comment by luxas** [comment]
@macropin This is fixed on `master`, and `hyperkube-amd64:v1.2.0-alpha.6` includes these commands (for the `docker` guide). Try to upgrade your version.

**Comment by macropin** [comment]
So following the guide for master/1.2.0-alpha.6, I've run the following:

```
export K8S_VERSION='1.2.0-alpha.6'

docker run \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/dev:/dev \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    -d \
    gcr.io/google_containers/hyperkube-amd64:v${K8S_VERSION} \
    /hyperkube kubelet \
        --containerized \
        --hostname-override="127.0.0.1" \
        --address="0.0.0.0" \
        --api-servers=http://localhost:8080 \
        --config=/etc/kubernetes/manifests \
        --cluster-dns=10.0.0.10 \
        --cluster-domain=cluster.local \
        --allow-privileged=true --v=10
```
 NB: the guide calls for running `gcr.io/google_containers/hyperkube:v${K8S_VERSION}` so the docs might need an update.

After waiting a minute or two.. I've found that setup failed: 
```
[root@localhost nginx-alpha]# docker logs 66a68cefe493
/setup-files.sh: line 31: /data/basic_auth.csv: Permission denied
```

And API server dies due to `basic_auth.csv` issue...

```
[root@localhost nginx-alpha]# docker logs 8a98f1c58da7
I0125 00:11:15.092069       1 util.go:440] Default route transits interface "enp0s3"
I0125 00:11:15.092811       1 util.go:285] Interface enp0s3 is up
I0125 00:11:15.093028       1 util.go:330] Interface "enp0s3" has 2 addresses :[192.168.3.11/24 fe80::a00:27ff:fe02:ea1b/64].
I0125 00:11:15.093083       1 util.go:297] Checking addr  192.168.3.11/24.
I0125 00:11:15.093112       1 util.go:306] IP found 192.168.3.11
I0125 00:11:15.093139       1 util.go:336] valid IPv4 address for interface "enp0s3" found as 192.168.3.11.
I0125 00:11:15.093170       1 util.go:446] Choosing IP 192.168.3.11 
I0125 00:11:15.093204       1 server.go:176] Will report 192.168.3.11 as public IP address.
I0125 00:11:15.093244       1 plugins.go:71] No cloud provider specified.
W0125 00:11:15.093450       1 server.go:293] No RSA key provided, service account token authentication disabled
F0125 00:11:15.093558       1 server.go:319] Invalid Authentication Config: open /srv/kubernetes/basic_auth.csv: no such file or directory
```

etcd also dies with a permissions error
```
[root@localhost nginx-alpha]# docker logs 2eb9f35b1bce
2016-01-25 00:12:32.484818 I | etcdmain: etcd Version: 2.2.1
2016-01-25 00:12:32.489259 I | etcdmain: Git SHA: 75f8282
2016-01-25 00:12:32.489525 I | etcdmain: Go Version: go1.5.1
2016-01-25 00:12:32.489756 I | etcdmain: Go OS/Arch: linux/amd64
2016-01-25 00:12:32.490046 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2016-01-25 00:12:32.490572 I | etcdmain: listening for peers on http://localhost:2380
2016-01-25 00:12:32.490928 I | etcdmain: listening for peers on http://localhost:7001
2016-01-25 00:12:32.491272 I | etcdmain: listening for client requests on http://127.0.0.1:4001
2016-01-25 00:12:32.491948 I | etcdmain: stopping listening for client requests on http://127.0.0.1:4001
2016-01-25 00:12:32.492257 I | etcdmain: stopping listening for peers on http://localhost:7001
2016-01-25 00:12:32.492530 I | etcdmain: stopping listening for peers on http://localhost:2380
2016-01-25 00:12:32.492973 C | etcdmain: mkdir /var/etcd/data: permission denied
```
And then `controller-manager` dies waiting for api.

I'm not sure where to go to from here.

**Comment by macropin** [comment]
Looks like most of the errors above were caused by `selinux` being enabled. I've disabled and now the only failure is the api server

```
[root@localhost nginx-alpha]# docker logs c29dea1fef98
I0125 00:20:53.920412       1 util.go:440] Default route transits interface "enp0s3"
I0125 00:20:53.921198       1 util.go:285] Interface enp0s3 is up
I0125 00:20:53.921532       1 util.go:330] Interface "enp0s3" has 2 addresses :[192.168.3.11/24 fe80::a00:27ff:fe02:ea1b/64].
I0125 00:20:53.921820       1 util.go:297] Checking addr  192.168.3.11/24.
I0125 00:20:53.922059       1 util.go:306] IP found 192.168.3.11
I0125 00:20:53.922300       1 util.go:336] valid IPv4 address for interface "enp0s3" found as 192.168.3.11.
I0125 00:20:53.922530       1 util.go:446] Choosing IP 192.168.3.11 
I0125 00:20:53.922758       1 server.go:176] Will report 192.168.3.11 as public IP address.
I0125 00:20:53.922969       1 plugins.go:71] No cloud provider specified.
W0125 00:20:53.923343       1 server.go:293] No RSA key provided, service account token authentication disabled
F0125 00:20:53.957683       1 server.go:319] Invalid Authentication Config: open /srv/kubernetes/ca.crt: no such file or directory
```

**Comment by macropin** [comment]
I've manually generated `/srv/kubernetes/server.key` and `/srv/kubernetes/server.crt` on the host. And now the API server runs (eventually). On the first start it dies with an error variously about either `ca.crt` or `basic_auth.csv`. I'm not sure what's going on here, but for sure `selinux` is an issue. At a guess I'd say there's a race condition with the autogeneration of credentials.

**Comment by Perfect-Web** [comment]
yeh, i just had the same problem and once i disabled selinux it started

**Comment by luxas** [comment]
This is fixed in the latest `v1.2` release thanks to #17213 and #23550
Closing as fixed, reopen if not

**Comment by mathisub** [comment]
I am running kubernetes v1.2.3 and have the same issue with the API server.
Invalid Authentication Config: open /srv/kubernetes/basic_auth.csv

**Comment by alifiroozi80** [comment]
Hello everyone
 i've read [this answer](https://github.com/kubernetes/kubernetes/issues/19980#issuecomment-173961597) and check my `kube-controller-manager.yaml`:

```shell
$ sudo vim /etc/kubernetes/manifests/kube-controller-manager.yaml
```
```yaml
[...]
spec:
  containers:
  - command:
    - kube-controller-manager
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-name=kubernetes
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --use-service-account-credentials=true
    image: k8s.gcr.io/kube-controller-manager:v1.24.1
[...]
```

As you can see,  `--use-service-account-credentials` is set to `true` and the `--service-account-private-key-file=/etc/kubernetes/pki/sa.key` is point to a private key...

But still the serviceaccount doesn't creates Tokens!

How can i fix this issue?

PS: Kubernetes versaion: `v1.24.1`

**Comment by aojea** [comment]
> The LegacyServiceAccountTokenNoAutoGeneration feature gate is beta, and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the TokenRequest API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the token controller to populate with a service account token by following this guide. (#108309, @zshihang)

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes
