### ISSUE TITLE
Flakes in hack/test-cmd.sh

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#19999]
Appears to be port conflict for port needed by kube-proxy.

[Build Log](https://00e9e64bac6163c5d10c6b08946aab1d3da4369abff3cec20a-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2F021cfe8e0915ab39a94f6345c98456702469d18b%2Fkubernetes-pull-test-unit-integration%2F10455%2Fbuild-log.txt?qk=AD5uMEsHwGp05eU2Z8Hsy8Hk7mwABlxwc3ALmRo-_4XhhonXVklkiIJGirJm5JVxMy8xQsftIMYQq5DuLRqgaMcGcRMPQXCQkn5Sqb-R9V1SoFUZCnbtZ0mxDFX8U6RIfJfySh04O0HoGm7TM0WWEGE4QenDusSdYEYNOv7rlSB6ZggokDNbB7tvaqkVvvow7cWNY0ryH3poCZ7oEp27dO7k5L-S7mXr2fZ3G0d3tC7vm09J_IVXVlEq7lUhDFMhpSiSDI8BgdaX64wkVmzdWgjCaFEaxJLdTzLBlIpTNasWM6VQNvx7n0Jov104qg_ilHJn2zeMa84vx_KtyxNKk4QIbVau6XE8cr2EQkJWbDiSnF-6Pnve_sSqlcrByTn7ngxCRS5NKkwH45C7s1JtaRbgsqqUXKWex_3W7CH87h5QRRlZbg61kh0pZs9yhHyBmqaKhEp_UMBc4h1nbKHz6WukqFsin5DjlLtGOa5jRJqm_9t3BlIhVuT9_ErNv-fj0jxxzkvDC3-TiY4BfDG4-6p01yrPUksB3MmW7KW6O7v8TEXX-9Fl2iLpvD6G7G5Yh7HUtjs8Wgeg8MEJPL3Rgf5QGkANtxgNq2GYwqjOg3i9txcq5ab8om6nDn4dEiEq0MsjVZ9mycnzpalzA7_k8vu7iJ41hJtDf9lFq-lbE5qHMuj-UglBiVFjlSThf5ChspI7WMruDoniI_PE6qOFz37Rp5JmLDLq6Jz-Yg2RTSO1frYzh8dC4xqf6kkRNMCZBeOZ62_Q9bAln0EoTDt2JNV3av9Sc21Y5IOdEu7eV2PSgwlAmvpc5Z91uRuPKYOUGXwz3vQzoPLGx39_fwM38nEwfJOOeLZS5lgo5XtQCCcXsXIeD_fc143lTNCgG1YFsr-UH-x-AqCKLiS7wwCTddboHiti-6uNzgUIyCnt2W_9T0x1xRixlOq6_jmqZMYuu2jcpbZSk0wsQxIcRFJVSa5Y5FUbQbFlLA)

Excerpt:
```
+++ [0122 07:38:55] Starting kubectl proxy
+++ [0122 07:38:55] On try 1, use proxy port 20236 if it's free
nc: connect to 127.0.0.1 port 20236 (tcp) failed: Connection refused
+++ [0122 07:38:55] 127.0.0.1:20236 is free, proceeding...
Starting to serve on 127.0.0.1:20236+++ [0122 07:38:56] On try 2, kubectl proxy: ok
+++ [0122 07:38:56] Starting kubectl proxy
+++ [0122 07:38:56] On try 1, use proxy port 28721 if it's free
nc: connect to 127.0.0.1 port 28721 (tcp) failed: Connection refused
+++ [0122 07:38:56] 127.0.0.1:28721 is free, proceeding...
Starting to serve on 127.0.0.1:28721+++ [0122 07:38:57] On try 2, kubectl proxy: ok
+++ [0122 07:38:57] Starting kubectl proxy
+++ [0122 07:38:57] On try 1, use proxy port 37207 if it's free
nc: connect to 127.0.0.1 port 37207 (tcp) failed: Connection refused
+++ [0122 07:38:57] 127.0.0.1:37207 is free, proceeding...
F0122 07:38:57.566765   27355 proxy.go:132] listen tcp 127.0.0.1:37207: bind: address already in use
```

**Comment by erictune** [comment]
I've seen this twice in the last 24 h.  

The problem is that there is still a race between the time that the shell script (hack/test-cmd.sh) thinks the port is free and the time that kubectl actually binds to it.

**Comment by lavalamp** [comment]
This is a dup of #19252, right?

**Comment by erictune** [comment]
Yes.

**Comment by davidopp** [comment]
I got what I believe is a different flake in hack/test-cmd.sh
```
Successful get service frontend-5 {{(index .spec.ports 0).port}}: 80
(BE0123 00:30:51.971527   25742 nodecontroller.go:395] pods "valid-pod" not found
Error from server: pods "valid-pod" not found
!!! Error in ./hack/test-cmd.sh:988
  'kubectl delete pod valid-pod "${kube_flags[@]}"' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:988 runTests(...)
  2: ./hack/test-cmd.sh:1352 main(...)
Exiting with status 1
```

**Comment by lavalamp** [comment]
@davidopp that looks like it might be #19403?

**Comment by goltermann** [comment]
All issues linked from this one are closed.  Anything left to do?

**Comment by lavalamp** [comment]
All the things this is a dup of are fix.
