### ISSUE TITLE
Kubelet complains about impossible errors

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20008]
Trace for a single pod (suffix go7lw) taken from the daemon restart flake: https://gist.github.com/bprashanth/c3a4a15e9e5fa3736194
To my untrained eye it looks like the pod was started after a REMOVE (but a failed delete): 
```
I0122 11:19:51.410989    3399 kubelet.go:2295] SyncLoop (REMOVE, "api"): "daemonrestart10-e44fe05e-c0f9-11e5-a7e6-ac162d075328-go7lw_e2e-tests-daemonrestart-9gi0h(0d81a7f0-c0fa-11e5-a227-42010af00002)"
I0122 11:19:51.411046    3399 kubelet.go:2428] Failed to delete pod "daemonrestart10-e44fe05e-c0f9-11e5-a7e6-ac162d075328-go7lw_e2e-tests-daemonrestart-9gi0h(0d81a7f0-c0fa-11e5-a227-42010af00002)", err: pod not found
```
leading to the impossible error: 
```
RunContainerError: "impossible: cannot find the mounted volumes for 
pod \"daemonrestart10-e44fe05e-c0f9-11e5-a7e6-ac162d075328-go7lw_e2e-tests-daemonrestart-
9gi0h(0d81a7f0-c0fa-11e5-a227-42010af00002)\""
```

I'm actually not sure if this contributed to the eventual flake, so just filing this standalone.

**Comment by yujuhong** [comment]
```
I0122 11:19:50.922752    3399 kubelet.go:2289] SyncLoop (ADD, "api"): "daemonrestart10-e44fe05e-c0f9-11e5-a7e6-ac162d075328-go7lw_e2e-tests-daemonrestart-9gi0h(0d81a7f0-c0fa-11e5-a227-42010af00002)"
I0122 11:19:51.410381    3399 kubelet.go:2292] SyncLoop (UPDATE, "api"): "daemonrestart10-e44fe05e-c0f9-11e5-a7e6-ac162d075328-go7lw_e2e-tests-daemonrestart-9gi0h(0d81a7f0-c0fa-11e5-a227-42010af00002)"
I0122 11:19:51.410989    3399 kubelet.go:2295] SyncLoop (REMOVE, "api"): "daemonrestart10-e44fe05e-c0f9-11e5-a7e6-ac162d075328-go7lw_e2e-tests-daemonrestart-9gi0h(0d81a7f0-c0fa-11e5-a227-42010af00002)"
```
It looks like the pod was created and then deleted non-gracefully in a short time. In this case, kubelet is more prone to having a race. The pod worker may still be in the middle of creating the pod, while the cleanup routine already started deleting associated resources (hence the failed delete). Even though the impossible error seems striking, I think this race would only cause transient errors. The pod worker will terminate after the failure and never try to sync again.

We should try eliminating the unnecessary race. That's a different issue: #19037
