### ISSUE TITLE
Document DNS schema

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20003]
we don't have a single doc that covers our DNS schema

@ArtfulCoder

**Comment by ArtfulCoder** [comment]
you had written something here:
https://github.com/kubernetes/kubernetes/blob/release-1.1/cluster/addons/dns/README.md#supported-dns-schema

**Comment by thockin** [comment]
Oh yeah.  That doesn't include the magic ip-based names nor your new set
names.  We should promote this to a full doc.

**Comment by ArtfulCoder** [comment]
It does seem to mention the ip-based names.
I was planning to do the set based names, in a pr where I update the version of skydns.
