### ISSUE TITLE
Test runs and failures not counted for some shell-based tests

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#20002]
When there is a failure in hack/test-cmd.sh, there is no junit.xml output, so the github checks box shows a confusing message like:

  :x: Jenkins unit/integration - 2571 tests run, 9 skipped, 0 failed

I'm like: why is there a red :x: when nothing failed.

Perhaps hack/test-cmd.sh can use https://github.com/akesterson/shunit to output a junit.xml, or something?

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by spxtr** [comment]
We should run test-cmd.sh in bazel. @mikedanese eh?
