### ISSUE TITLE
Need e2e testing of Kubelet/Docker memory and CPU usage

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#20012]
To replace test/e2e/monitor_resources.go which was removed in #19987 

ref/ #12429 

cc/ @gmarek @dchen1107

**Comment by yujuhong** [comment]
The cpu usage is already included in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubelet_perf.go
The memory usage, as I mentioned in https://github.com/kubernetes/kubernetes/issues/12429#issuecomment-173991665, needs more meaningful number from cadvisor.

**Comment by dchen1107** [comment]
Does test/e2e/kubelet_perf.go provide you enough?

**Comment by dchen1107** [comment]
Ok, I see you are also asking memory usage here. We need a better measurement first.

**Comment by vishh** [comment]
Shouldn't this belong to the node e2e test suite?

**Comment by yujuhong** [comment]
> Shouldn't this belong to the node e2e test suite?

A lot of tests should, but I think we're still in the middle of migrating those tests. It's orthogonal to adding memory usage checking for this test.

For reference, RSS has been added to cadvisor in https://github.com/google/cadvisor/pull/1055. I will update the test after we bump the cadvisor version.

**Comment by timothysc** [comment]
Ideally I would like to execute ~=density on a single node to measure memory. 

/cc @kubernetes/sig-scalability

**Comment by gmarek** [comment]
@timothysc - you want to run something like https://github.com/kubernetes/kubernetes/blob/master/test/e2e/resource_usage_gatherer.go on a test filling single Node?

**Comment by timothysc** [comment]
@gmarek not exactly, we want the system profile of the daemons themselves not the containers.  

We do this in a separate experiment using pbench: https://github.com/distributed-system-analysis/pbench on our side.
