### ISSUE TITLE
Add version to e2e.test binary artifact.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#20017]
We will want to ship the e2e binary w/ the ability to independently verify its version, esp pending #19624 .
cc @timothysc @liggitt @ixdy @pmorie @kubernetes/goog-testing .  

I'll craft a PR for this after looking at how version is handled in kubectl, im sure it will be quite simple.

**Comment by ixdy** [comment]
The magic happens in `pkg/version` and `hack/lib/version.sh`.

**Comment by ixdy** [comment]
The `MatchesServerVersion` func may also be relevant.

**Comment by pmorie** [comment]
+1 to this, do we want to have separate tag and sha fields?

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by ixdy** [comment]
not sure if we still want to do this, but it'd probably be pretty easy to do by linking against `pkg/version` and making sure the right linker flags are set.

**Comment by ixdy** [comment]
oh, I've even said that already.

**Comment by ixdy** [comment]
Does anyone still want this? It's trivial to add if desired.

**Comment by timothysc** [comment]
There is a pre-amble at the top of the output that indicates version now, it was done a while ago, so closing this issue.
