### ISSUE TITLE
In cases where we have debugging tips, we should include them in kubectl get ...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#20018]
I just helped a user debug an OOM problem.  It's pretty opaque unless you know what you are looking for.

I think that we should augement `kubectl get pods` so that we both highlight pods that we know are having problems, and if we know why they are having problems, we should print some tips to make them better.

**Comment by bgrant0607** [comment]
Highlighting is an interesting idea. Or we could add some kind of a PROBLEMS column.

I'd like to keep get output uniform (columnar, single row per resource) and relatively concise.

We can add as much as we like to describe.

In general, we should suggest to users that they follow up a get with describe if problems are flagged.

**Comment by bprashanth** [comment]
Can we flag control the smartness? I find the output type=nodeport dumps out to be mildly annoying

**Comment by bgrant0607** [comment]
Closing in favor of #19736
