### ISSUE TITLE
kube-proxy restart test may have left the pod in the not ready state

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#20021]
After the `Services should work after restarting kube-proxy [Disruptive]` test finished, the reboot test started checking the pods running on the node and failed because the kube-proxy pod is not ready.

In kubernetes-e2e-gke-ci-reboot/6487:
```
07:44:09 Reboot [Disruptive] 
07:44:09   each node by triggering kernel panic and ensure they function upon restart
...
07:44:11 Jan 22 07:44:11.223: INFO: Waiting up to 2m0s for pod kube-proxy-gke-jkns-gke-e2e-ci-reboot-6325f1b4-node-lilr status to be running and ready
07:46:13 Jan 22 07:46:13.126: INFO: Pod kube-proxy-gke-jkns-gke-e2e-ci-reboot-6325f1b4-node-lilr failed to be running and ready.
```

This caused the reboot test to fail before rebooting.

May be related: #19665

**Comment by dchen1107** [comment]
cc/ @thockin This is the one I mentioned to you earlier. The issue causes reboot test flakiness sometimes. Thanks!

**Comment by thockin** [comment]
I'm staring at what could POSSIBLY cause it to not be ready, and I just
can't figure it out.  There's no readiness check, it has to mean that the
pod isn't running or kubelet has not reported it.

**Comment by thockin** [comment]
I was going to add better logs, but the only place I can see that might
have produced this log already has good logs, but they are not included in
this issue.

**Comment by dchen1107** [comment]
I prioritize this as P1 for triage. Thanks for taking care of this.

**Comment by yujuhong** [comment]
There is a possibility that node controller changed the pod to be not ready and kubelet never recovers (corrects the status) from that. In that case, it will have nothing to do with the kube-proxy test.

The lack of useful kubelet.log makes it hard to debug. We should increase the log level of a gke cluster.

**Comment by freehan** [comment]
@yujuhong  I have a PR to test that case. Some of the Reboot tests will cause pods to be marked as notready. Based on my observation, the recovery usually takes around 1 minute after node comes back.

**Comment by dchen1107** [comment]
After all flakiness fix for reboot test, I never see the issue reported here. I am closing this one for now. If we found a new incident, please feel free to reopen it. Thanks!
