### ISSUE TITLE
unit flake: host_path.TestMetrics (from k8s.io_kubernetes_pkg_volume_host_path)

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#20026]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/6724/testReport/(root)/host_path/TestMetrics/

console output:
```
00:22:20 FAIL	k8s.io/kubernetes/pkg/volume/host_path	0.099s
```

test results output:
```
Error Message

Failed
Stacktrace

host_path_test.go:321: Expected Available to be greater than 0
```

**Comment by lavalamp** [comment]
@thockin to delegate. Possibly same root cause as #20028?

**Comment by thockin** [comment]
Dup of #20026
