### ISSUE TITLE
unit flake: volume.TestMetricsDuGetCapacity (from k8s.io_kubernetes_pkg_volume)

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#20027]
console output:
```
00:22:20 FAIL	k8s.io/kubernetes/pkg/volume	0.089s
```

test output:
```
Error Message

Failed
Stacktrace

metrics_du_test.go:59: Expected Available 0 to be greater than 0.
```

**Comment by jlowdermilk** [comment]
from http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/6724/testReport/(root)/volume/TestMetricsDuGetCapacity/

**Comment by lavalamp** [comment]
@thockin to delegate. Possibly same root cause as #20028?

**Comment by thockin** [comment]
Dup of #20028
