### ISSUE TITLE
Make #19061 backward-compatible

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20047]
When running the new `release/build-official-release.sh` against `release-1.1`, I get:

```
make: Entering directory `/tmp/kubernetes-build-release-v1.1.5-cmQJYh7/cluster/images/hyperkube'
make: *** No rule to make target `build'.  Stop.
make: Leaving directory `/tmp/kubernetes-build-release-v1.1.5-cmQJYh7/cluster/images/hyperkube'
```

The `build` make target didn't exist in `v1.1`, so that's a problem:

- [ ] Add a comment that `make release` is the *de facto* way to build a release, and one shouldn't add anything else
- [ ] Figure out a good workaround

xref #19061.

**Comment by david-mcmahon** [comment]
The immediate issue will be fixed when #19935 lands on the branch. 
This is a general interface issue between release/* and build/*.  Lowering priority.

**Comment by ihmccreery** [comment]
#19935 didn't work; the release process is still broken.

```
make: Entering directory `/tmp/kubernetes-build-release-v1.1.6-6cNPWJ1/cluster/images/hyperkube'
cp ./* /tmp/tmp.SdoPPOPQ04
cp ../../saltbase/salt/helpers/safe_format_and_mount /tmp/tmp.SdoPPOPQ04
cp ../../saltbase/salt/generate-cert/make-ca-cert.sh /tmp/tmp.SdoPPOPQ04
cp ../../../_output/dockerized/bin/linux/amd64/hyperkube /tmp/tmp.SdoPPOPQ04
cd /tmp/tmp.SdoPPOPQ04 && sed -i "s/VERSION/v1.1.6/g" master-multi.json master.json kube-proxy.json
sed: can't read kube-proxy.json: No such file or directory
make: *** [build] Error 2
make: Leaving directory `/tmp/kubernetes-build-release-v1.1.6-6cNPWJ1/cluster/images/hyperkube'
```

Bumping this back to P0.

**Comment by david-mcmahon** [comment]
The release tooling should not have any specific dependencies on granular build targets. 
As Ike said, the release tooling should hit a single high level target like "make release" (with any modifiers as needed.  I see a quick-release).

"make -C cluster/images/hyperkube/ build" and its related dependencies should be pulled into build/release.sh.

**Comment by ihmccreery** [comment]
For what it's worth, the current workaround is to comment-out the `HYPERKUBE ... make` line in the `release/cut-official-release.sh` script before trying to release off of 1.1.
