### ISSUE TITLE
Delete() methods in some client of resource have DeleteOptions parameter, but some have not

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#20060]
I notice that `Delete()` methods in some client of resource have a `DeleteOptions` parameter, but some have not

resource client which has a  `Delete()` methods with a `DeleteOptions` parameter
* Deployment
* HorizontalPodAutoscaler
* Job
* Ingress
* Event
* PodTemplates

resource client which has a  `Delete()` methods ***without*** a `DeleteOptions` parameter

* Deamonset 
* Endpoint
* LimitRange
* Namespace
* Node
* PersistentVolumeClaims
* PersistentVolumes
* ReplicationControllers
* ResourceQuotas
* Secrets
* ServiceAccounts
* Services
* ThirdPartyResources

Client of Deployment/HorizontalPodAutoscaler/Job/Ingress/Event/PodTemplates has a  `Delete()` methods with a `DeleteOptions` parameter, but others have not . Should we add the `DeleteOptions` to keep them consistent? Or is there any reason those client have not the parameter?

@bgrant0607

**Comment by mqliang** [comment]
BTW, I think we should add `DeleteCollection()` in all client, which could use to delete all the source in a namespace, it's very helpful in NamespaceController. Currently, NamespaceController will list all the source in a namespace and delete one by one, which is very inefficiency.

**Comment by bgrant0607** [comment]
cc @smarterclayton @lavalamp

**Comment by bgrant0607** [comment]
AFAIK, the only resource that actually uses DeleteOptions currently is Pod, which isn't in either of your lists. The others are either cargo-culting or future-proofing.

**Comment by smarterclayton** [comment]
DeleteOptions per type doesn't scale (or make for an easy to use API).
I think we just need to have the correct pattern for specialized types
(we have everything we need today to support this, except the actual
accept multiple types).  After all, most of these parameters are
likely "advanced" and with well chosen defaults PodDeleteOptions
simplifies to DeleteOptions.

**Comment by lavalamp** [comment]
@caesarxuchao is very close to having client generators working; when that is done, the clients will all be made consistent.

**Comment by caesarxuchao** [comment]
In the generated clients, DeleteOptions and DeleteColloctions() are added to all clients. They are under pkg/clients/types/generated/..
