### ISSUE TITLE
Can't abort kubectl edit

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20078]
I am running `kubectl edit` against an object.  I make a mistake, and it reopens (nice) with comments (nice).  I decide I don't want to edit, after all.  How do I abort?  In most scenarios, exiting without save or deleting all contents would trigger the process to abort.  Not so in kubectl.

**Comment by bgrant0607** [comment]
cc @janetkuo @deads2k @kargakis

**Comment by deads2k** [comment]
@fabianofranz

**Comment by smarterclayton** [comment]
Uh.... deleting all contents originally aborted.  Guess that got lost somewhere.

**Comment by smarterclayton** [comment]
@kargakis before you remove oc edit... make sure this is fixed :)

**Comment by Miciah** [comment]
I would use `:cq` in Vim.  It looks like the Emacs equivalent is `M-;` `(kill-emacs 1)` (maybe I'm missing some simpler way—I'm not very proficient with Emacs).

**Comment by smarterclayton** [comment]
Humorously, proof this used to work is the comment at the top of the editable section:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
```

**Comment by thockin** [comment]
Empty-save works on its own.  But once you trigger a validation error and
it re-opens, then empty-save does not work any more.

Example: edit a service, change the clusterIP field, save, observe it
reopens with an error, try to empty-save

**Comment by bgrant0607** [comment]
@kargakis sent a PR: #20481
