### ISSUE TITLE
Why upstream choose Salt as the configuration management tool?

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#20075]
I can see that upstream uses Salt as the configuration manager for installing and configuring k8s cluster. Just want to know more on the decision making story:
- What's the major factor for choosing Salt?
- Is there any other tool such as fleet considered? If so, who not use fleet or some else?
- Is Salt scalability tested in k8s' scenario? Say, 500 ~ 1000+ nodes?

**Comment by thockin** [comment]
Why?  It was what someone on the team knew how to do and we needed it done
ASAP.  It has grown a little out of hand since then.
