### ISSUE TITLE
sed -i in build/common.sh fails on OSX

### ISSUE THREAD

**Issue by mdaniel** [kubernetes/kubernetes#20073]
The change in #19990 caused `make quick-release` to fail on OSX because the [sed](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/sed.1.html) on OSX mandates a value, even if zero length, for the `-i` option - unlike [sed](http://manpages.ubuntu.com/manpages/trusty/en/man1/sed.1.html) on Linux.

```
+++ [0124 16:42:18] Verifying Prerequisites....
+++ [0124 16:42:19] Building Docker image kube-build:cross-1.4.2-1.
sed: 1: "/Users/mdaniel/proj/k ...": invalid command code m
!!! Error in build/../build/common.sh:451
  'sed -i "s/KUBE_BUILD_IMAGE_CROSS/${KUBE_BUILD_IMAGE_CROSS}/" ${build_context_dir}/Dockerfile' exited with status 1
Call stack:
  1: build/../build/common.sh:451 kube::build::build_image(...)
  2: build/release.sh:31 main(...)
Exiting with status 1
make: *** [quick-release] Error 1
```

There seems to be precedent for requiring `gsed` in `build/mark-new-version.sh` and `build/versionize-docs.sh` (and, as one might expect, replacing the `sed` with the `gsed` one built using `brew install gnu-sed` restores the prior functionality)

**Comment by mfanjie** [comment]
Specifying backup extension for sed -i is required on MAC, which is incompatible with on Linux. The sed -i code in build/common.sh is Linux compatible format and backup extension is not specified, this breaks MAC build.

I modified the checking by calling existing function kube::build::is_osx, if it is true, then add "" as backup extension, which is no backup.
