### ISSUE TITLE
--add-host support

### ISSUE THREAD

**Issue by mateeyow** [kubernetes/kubernetes#20079]
Is it possible to have a command adding host to a kubernetes pod the same as docker's `docker run --add-host host.local:122.125.51.1`?

**Comment by Pensu** [comment]
Good idea. The way we have hints in openstack environment? In general terms we can think of something that can filter out or choose some specific hosts, based on the values given.

**Comment by bgrant0607** [comment]
@mateeyow What are you trying to do? Why would you want to add a hosts entry?

If you're not familiar with it, please take a look at the documentation for services:
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md

**Comment by mateeyow** [comment]
@bgrant0607 I was trying to change the hostname of a running pod so as to automate creation of mongo replica set. I think it is one of their requirements. Anyway, this was before I found out about mongo-k8s-sidecar.

**Comment by bgrant0607** [comment]
In progress: #20688, #19295

Closing as a dupe.

cc @ArtfulCoder
