### ISSUE TITLE
kubectl edit comment has a golang printf error

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20077]
`%!s(func(runtime.Object) (string, error)=0x4ab560) hostnames was not valid:`

%s should be %v, I guess.

**Comment by kargakis** [comment]
Is this still an issue?

**Comment by thockin** [comment]
I still see it on my cluster which is about 2 weeks old.  Was it fixed in
the mean time?  It's easy to repro.

Make a service
`kubectl edit` the service and delete the clusterIP line
save

**Comment by thockin** [comment]
And I don't think it's %v.  I think it is a function that returns the type,
not the type.  It needs to be called.

**Comment by kargakis** [comment]
I thought this was fixed by https://github.com/kubernetes/kubernetes/pull/20481

**Comment by kargakis** [comment]
Same error in Origin: https://github.com/openshift/origin/issues/6926

**Comment by dims** [comment]
I can't recreate the problem using the step from @thockin - should this bug be closed?

Make a service
`kubectl edit` the service and delete the clusterIP line
save
