### ISSUE TITLE
Collect logs of failed containers in kube-system namespace

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#20099]
We are running heapster, dns server, kube-proxy etc. in kube-system namespace. Some e2e tests try to make sure all those kube-system pods are at ready state before firing the real tests, others just simply ingore them. But both cases might cause e2e flakiness when some of those kube-system containers are in crashloop, for example, https://github.com/kubernetes/kubernetes/issues/19986#issuecomment-174089670 for heapster crashloop, https://github.com/kubernetes/kubernetes/issues/19189#issuecomment-173419306 for influxdb crashloop, etc. When such cases happen, the developer doesn't have much information on why since the nodes might be teared down. 

We should watch those kube-system pods, and onContainerFailure, we should collect the related logs. One simple way is using kubectl logs <Pod> <Container> --previous

cc/ @kubernetes/goog-node @kubernetes/goog-testing

**Comment by ihmccreery** [comment]
@spxtr is this related enough to #19964 and #18432 that you can bundle it in?

**Comment by yujuhong** [comment]
The logs from the pods should be retrieved via the api server. This is different from the kubelet logs. I'll upload a PR for this.

**Comment by piosz** [comment]
Great job @yujuhong! It will be very helpful for debugging.
