### ISSUE TITLE
Fix 1.1.4 release notes

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#20091]
Hello, can you guys update the 1.1.3 release notes so it's the same as all prior release notes? That is, each fix has a link to the PR/issue and the contributor name. Not sure why it was skipped on 1.1.3.

Cheers

**Comment by a-robinson** [comment]
1.1.3 looks like it has links to PRs/issues and contributor names to me. Do you mean the 1.1.4 notes?

cc @david-mcmahon

**Comment by jsravn** [comment]
Thanks, I've fixed it.

**Comment by david-mcmahon** [comment]
"skipped" by me mostly because process is not strictly defined or controlled yet.  That's all changing Real Soon.  
Thanks for fixing this jsravn@.  Assuming this is closed now so closing.

**Comment by jsravn** [comment]
@david-mcmahon I meant I fixed the issue title (1.1.3->1.1.4), not fixed the release notes.

Release notes still need the details for 1.1.4.

**Comment by david-mcmahon** [comment]
Done.
