### ISSUE TITLE
clusterDNS broken with DNS servers without recursive lookup

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#20090]
https://github.com/kubernetes/kubernetes/pull/18089 changed the behavior of resolv.conf inside containers to not append the node's host nameservers when clusterDNS is specified. That assumes the nameserver pointed to by clusterDNS does recursive lookups for domains outside the cluster (e.g. github.com, google.com). That is not a valid assumption to make, and should be guarded by a config option.

**Comment by AdoHe** [comment]
I think so, this should be guarded by a config option.

**Comment by thockin** [comment]
If cluster DNS is not recursive you will run into resolvers that are
broken.  There is no specification for what recolv.conf really means, and
therefore implementations vary.  Some resolvers (e.g. musl libc) will try
all nameservers in parallel, taking the first response - even if that is a
NAK.  Busybox does something else (forget the details).  Glibc does
something else.

We made this change after a large amount of deliberation and testing of
various resolvers.

If you need something different you need to run a proxy that muxes (e.g.
dnsmasq can do this, I think).

**Comment by liggitt** [comment]
Hmm... thanks for the explanation

**Comment by thockin** [comment]
Same discussion happening in parallel about rkt...

**Comment by smarterclayton** [comment]
The problem is that we still have end users who won't allow an open DNS proxy in their environments, full stop.  And they only use glibc (which we test and certify against) to solve this problem.  Unfortunately that leaves us in a spot where we have to fork the Kube DNS implementation because it's not practical for non-cloud environments that have IT policies place.

**Comment by smarterclayton** [comment]
So musl vs glibc is not relevant in their environments

**Comment by liggitt** [comment]
an option to enable clusterDNS+node host with appropriate caveats would be sufficient, imo

**Comment by thockin** [comment]
I'm OK with a flag, but it has to be very well documented and sufficiently
scary that mere mortals will not set it.

--make-bad-assumptions-for-redhat-customers-only or something

**Comment by smarterclayton** [comment]
Ouch.

--use-dns-the-way-that-every-it-department-in-the-world-does-it

also works :)

**Comment by thockin** [comment]
Is it really sane policy to disallow (maybe caching) DNS proxies?  Why?
There is no spec on what resolv.conf really means.  we started this way
(obviously) and decided the pain outweighed the benefits.

--spec-what-spec-dns-behavior

**Comment by liggitt** [comment]
Or allow clusterDNS to take multiple values, which lets whoever is invoking the kubelet decide which name servers they want injected into pods.

**Comment by ArtfulCoder** [comment]
Having more than one NS has other problems beyond parallel v/s serial queries.
check out https://github.com/kubernetes/kubernetes/issues/15592#issue-111306439

If we still want more than one NS, we can go the flag approach, but its going to come at the cost of potentially incorrect DNS responses.

**Comment by smarterclayton** [comment]
DNS is one of the most tightly controlled infrastructure pieces in
real organizations today, after networks.  Just because there are
trade offs and disadvantages (and all of those are things to document)
doesn't negate the fact that we can't dictate the terms of deployment.
The real world is an ugly place :)
