### ISSUE TITLE
Help build cops track flakes better, especially in the PR builder

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20097]
We need to help the build cops track & file issues about flakes, especially in the PR builder.  We heard this morning in war room that folks are worried that flakes are coming up and issues aren't being filed.

**Comment by ihmccreery** [comment]
Assigning to @spxtr for discussion, brainstorming, and work estimate.

**Comment by spxtr** [comment]
I think it might be as simple as trying to make a policy of, "Never say @ k8s-bot test this again, instead say @ k8s-bot test this again #ISSUE", and if there is no open issue then open it right away.

It's what I've been doing, at least.

**Comment by ihmccreery** [comment]
Great idea; want to implement that?

**Comment by ihmccreery** [comment]
@ixdy Can you please explore implementing this?

**Comment by ihmccreery** [comment]
With @brendandburns' munger, I'm knocking this down to P1.

**Comment by lavalamp** [comment]
I think this has been a big success so far. Can we just close this? Is there more action to take?

**Comment by ihmccreery** [comment]
I'm fine with that; I think almost everything the @kubernetes/goog-testing team is working on goes toward this (very vague) issue.
