### ISSUE TITLE
Re-use fake clock in the kube repo for kubelet unit tests

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#20105]
Specifically, "github.com/ssoroka/ttime", should be repalced with "k8s.io/pkg/util".FakeClock

This should also invalidate the godep issue of missing LICENCE file for  "github.com/ssoroka/ttime" package.

**Comment by vishh** [comment]
@mqliang: Can you fix this issue?

**Comment by vishh** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/18820/files#r50745948 https://github.com/kubernetes/kubernetes/pull/18820#issuecomment-174619555

**Comment by mqliang** [comment]
@vishh Ok, I will send a PR to fix this ASAP. Sorry to introduced a Godep w/o a LICENSE file.

**Comment by vishh** [comment]
No worries. Thanks for working on this.

**Comment by yujuhong** [comment]
Closing the issue since the fix has been merged.
