### ISSUE TITLE
Should ConfigMapKeySelector and SecretKeySelector be the same type?

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#20101]
I probably would have made them the same type to begin with if I hadn't been doing the PRs at the same time.  They both have the structure:

```go
// Selects a key from a ConfigMap.
type ConfigMapKeySelector struct {
	// The ConfigMap to select from.
	LocalObjectReference `json:",inline"`
	// The key to select.
	Key string `json:"key"`
}
```

Should we just make them the same object?  They're differentiated in EnvVarSource by field, so there's really no need to to make them separate types.

@thockin @bgrant0607 @erictune @smarterclayton

**Comment by ncdc** [comment]
:+1: to same type

**Comment by bgrant0607** [comment]
One advantage of separate types is context-sensitive documentation, which we autogenerate from the type comments.

We reuse types in many cases today where we shouldn't, which causes documentation to be wrong, required/optional info to be wrong, fields that aren't actually supported to appear in types where they don't belong, etc.

Is there any real advantage to using the same types?

**Comment by thockin** [comment]
I agree with Brian.  The docs coming out as "The ConfigMap to select from"
[sic] is way better than "The object to select from".

Even LocalObjectRef is very generic

**Comment by pmorie** [comment]
@bgrant0607 @thockin accepted, I'll close the issue  out.
