### ISSUE TITLE
Write a test for a flapping container then reboot

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#20104]
See #19986. My suspicion for why the `container-vm` change is holding stable on GCE but NOT on GKE is that on GKE, Heapster is flapping. I'd like to see a new test on GCE that essentially flaps a container and then reboots. I think it'll show the same kernel shutdown issue.

**Comment by zmerlynn** [comment]
(FWIW, this is a realistic customer scenario of "Agggghhh! Something wrong! Reboot!")

**Comment by yujuhong** [comment]
I am not entirely sure that there is a clear connection between flapping containers and the kernel shutdown issue. This seems like a very specific (and slow) test. Can we try reproducing the issue first to confirm the connection? Also, if flapping containers *can* cause kernel shutdown issues, testing this repeatedly in our builds won't actually help.

**Comment by zmerlynn** [comment]
I'm actually fairly sure the `container-vm` issue is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812207

However, that leaves the question of why GKE is seeing it and GCE isn't. Do you have a better theory besides the flap?

**Comment by yujuhong** [comment]
> I'm actually fairly sure the container-vm issue is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812207

Thanks for the pointer! I don't have better theories, but "flapping container" sounds too vague/broad to test. 

In this particular case, (docker+aufs), our node conformance tests will be able to catch this in the future. /cc @pwittrock
