### ISSUE TITLE
Run all types of controllers in gce scalability tests

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#20119]
We should run DaemonSets, Deployments, Ingresses etc. in the scalability/performance tests, not just replication controllers especially since many of these are graduating to beta.

cc @davidopp @kubernetes/goog-control-plane @kubernetes/sig-scalability

**Comment by davidopp** [comment]
Assigning to @wojtek-t for now, though he's on leave for a while longer.

**Comment by wojtek-t** [comment]
Sure - I completely agree. This was also our plan, but we didn't get to it yet.

@gmarek

**Comment by davidopp** [comment]
As we introduce more complex scheduling constraints and preferences (node affinity is in 1.2, pod affinity and taints/tolerations will be in 1.3), we should also start using pods that use these features.

We should probably rename this issue to "make our scalability tests fully exercise/stress the system." 

It may be reasonable to have a looser scheduling SLO for workloads that involve a lot of complex constraints, but for now I think we should not change it.

**Comment by hongchaodeng** [comment]
@davidopp 
That sounds nice thing to do. But it's orthogonal to the controller testing. Why not create a new issue?

**Comment by davidopp** [comment]
Sure, I will file a separate issue instead of making this one more general.

Filed #20793

**Comment by gmarek** [comment]
Fixed by the number of changes in Q1 2017.
