### ISSUE TITLE
v2 API Proposal: Endpoints as subresources

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20112]
The link between a Service and its Endpoints object is very weak (same name).  It might be interesting in v2 API to manifest this as a subresource of Service.  We will one day need to paginate Endpoints, but I think that still applies in both cases.  Not sure if watch on sub-resources would work, but we could still have an Endpoints object, and carry the subresource as a reference to a more randomly named Endpoints (or a list of them when paginated, or a selector).  Also we can have Endpoints on other objects without silly name collisions.

**Comment by bgrant0607** [comment]
Ref #8190

**Comment by seh** [comment]
Also related: #28483.

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc
