### ISSUE TITLE
Kubelet fails to distinguish failure in running container from a quickly exiting container

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20117]
My (partly unfounded) theory is that we should refactor `ApplyOOMScoreAdjContainer` out of `runContainerInPod` because if the container exited real quick it won't have an entry in `/proc/pid/cgroup` (https://github.com/kubernetes/kubernetes/blob/d3b869ae14db522e5fca91a295b8bc870713013f/pkg/kubelet/dockertools/manager.go#L1537), and we confuse this for an error in running the container.

This is based off the following debugging session:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/14712/ 
`pod-995d097b-bfc2-11e5-9ce3-42010af01555_e2e-tests-emptydir-fbgqp` has `restart=Never` and it seems to exit, and we don't report it as failed/succeeded. 

1. Started container:
I0120 22:10:22.967700    3461 server.go:569] Event(api.ObjectReference{Kind:"Pod", 
Namespace:"e2e-tests-emptydir-fbgqp", Name:"__pod-995d097b-bfc2-11e5-9ce3-42010af01555__", 
UID:"995d410d-bfc2-11e5-9d46-42010af00002", APIVersion:"v1", ResourceVersion:"8929", 
FieldPath:"spec.containers{test-container}"}): type: 'Normal' reason: 'Started' Started container with 
docker id fab06c2e3ee6

2. Failed to set oom score:
__E0120 22:10:23.007292__    3461 manager.go:1890] Error running pod "pod-995d097b-bfc2-11e5-9ce3-42010af01555_e2e-tests-emptydir-fbgqp(995d410d-bfc2-11e5-9d46-42010af00002)" __container "test-container": open /proc/17193/cgroup: no such file or directory__

3. FailedSync event:
I0120 22:10:23.070581    3461 server.go:569] Event(api.ObjectReference{Kind:"Pod", 
Namespace:"e2e-tests-emptydir-fbgqp", Name:"pod-995d097b-bfc2-11e5-9ce3-42010af01555", 
UID:"995d410d-bfc2-11e5-9d46-42010af00002", APIVersion:"v1", ResourceVersion:"8929", 
FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: not all containers have 
started: 0 != 1

4. However if you track the next 2 container inspect results: 

  * I0120 22:10:23.053457    3461 manager.go:340] Container inspect result: 
{ID:__fab06c2e3ee6eaff383bbb3d9f77ded5d692e20e7c77d849bdfdfdc6fe475baf__ Created:2016-01-20 
22:10:22.821645807 +0000 UTC Path:/mt Args:[--fs_type=/test-volume --new_file_0644=/test-
volume/test-file --file_perm=/test-volume/test-file] Config:0xc208408fc0 State:{Running:true 
Paused:false Restarting:false OOMKilled:false __Pid:17193 ExitCode:0 Error: StartedAt:2016-01-20 
22:10:22.967310973 +0000 UTC FinishedAt:0001-01-01 00:00:00 +0000 UTC}__ 
Image

  * I0120 22:10:23.328738    3461 manager.go:340] Container inspect result: 
{ID:__fab06c2e3ee6eaff383bbb3d9f77ded5d692e20e7c77d849bdfdfdc6fe475baf__ Created:2016-01-20
 22:10:22.821645807 +0000 UTC Path:/mt Args:[--fs_type=/test-volume --new_file_0644=/test-
volume/test-file --file_perm=/test-volume/test-file] Config:0xc208748380 State:{Running:false 
Paused:false Restarting:false OOMKilled:false Pid:0 __ExitCode:0 Error: StartedAt:2016-01-20
22:10:22.967310973 +0000 UTC FinishedAt:2016-01-20 22:10:23.06969655 +0000 
UTC}__ ResolvConfPath:

5. And we sent the Running/Ready update but no status update after that:
I0120 22:10:23.080449    3461 manager.go:371] Status for pod "pod-995d097b-bfc2-11e5-9ce3-42010af01555_e2e-tests-emptydir-fbgqp(995d410d-bfc2-11e5-9d46-42010af00002)" updated successfully: {status:{Phase:Running Conditions:[{Type:Ready Status:True LastProbeTime:{Time:{sec:0 nsec:0 loc:0x2bba980}} LastTransitionTime:{Time:{sec:63588924623 nsec:0 loc:0x2bba980}} Reason: Message:}] Message: Reason: HostIP:10.240.0.5 PodIP:10.248.84.65 

@kubernetes/goog-node thoughts?

**Comment by bprashanth** [comment]
Oh, kubelet logs for the trace above https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gce-parallel/14712/artifacts/104.197.47.216%3A22-kubelet.log

**Comment by dchen1107** [comment]
https://github.com/docker/docker/pull/16277 was merged and targeted for docker 1.10 release. Once we moved to docker 1.10 and above release, we won't handle ApplyOOMScoreAdjContainer at Kubelet level anyway. Without proper support at container runtime which is doing process management in certain degree, there are always some races.

**Comment by bprashanth** [comment]
I'd expect correct reporting of the status as failed/succeeded though right? since we know that the container did finish from the finish timestamp, and it has restart=never, so the test was waiting till timeout for the Succeeded status.

**Comment by vishh** [comment]
The kubelet should handle quick exits. Even if we switch to docker v1.10, we might have to be backwards compatible for the next few releases. Good catch @bprashanth!
