### ISSUE TITLE
mitigate slowness of Go 1.5 builds

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#20133]
Per https://github.com/kubernetes/kubernetes/pull/19985#issuecomment-174053620 (and the [Go 1.5 release doc](https://golang.org/doc/go1.5#performance)) build performance is expected to be at least twice as slow compared to 1.4:
>Builds in Go 1.5 will be slower by a factor of about two. The automatic translation of the compiler and linker from C to Go resulted in unidiomatic Go code that performs poorly compared to well-written Go. Analysis tools and refactoring helped to improve the code, but much remains to be done. Further profiling and optimization will continue in Go 1.6 and future releases.

We started seeing some slowdown in PR builds when we started using Go 1.5 for unit/integration tests in December, but moving all builds to Go 1.5 last week have pushed things off a cliff.

I'm trying to mitigate some of the problem by bringing up additional Jenkins slaves and thinning out the number of executors on each slave (currently trying a maximum of 2 e2e and 2 unit/integration), but we maybe need to see if there are other places we can optimize (e.g. if we are unnecessarily building things, or building them multiple times).

Maybe there are also some knobs we can tune, so at least the builds are a little more isolated from each other?

@kubernetes/goog-testing @david-mcmahon

**Comment by ixdy** [comment]
cc @zmerlynn too

**Comment by ixdy** [comment]
Running `ps ax | grep "go/pkg/too[l]" | wc -l` on one of the slaves right now which is running 2 instances of unit/integration tests and 2 instances of e2e tests, and there are often in excess of 200 processes, with load averages to match:
`01:09:54 up 32 min,  1 user,  load average: 267.98, 246.18, 160.89`

We might just be thrashing a lot? Since `/var/lib/jenkins/` is backed by a GCE PD, we might be hitting iops limits, but I'm not sure how to check that. We have plenty of memory free.

**Comment by ixdy** [comment]
Looking at the GCE dashboard, I don't think we're being limited by disk iops or throughput. CPU usage is pegged at 100% pretty consistently, though.

**Comment by luxas** [comment]
I'll look into knobs to tune #19769
For instance, splitting up client targets into client target (`kubectl`) and test targets.
Then we can easily specify for which platforms it's worth it to build test targets.

@zmerlynn and I have come to the conclusion that the `kube-build:cross` image speeds up the compilation a bit, especially now when `protoc` is included.

**Comment by ixdy** [comment]
@luxas any help is appreciated. :)

I'm actually gonna lower this to P1. It seems like adding some additional Jenkins nodes and spreading the load has brought things under control today.

**Comment by bgrant0607** [comment]
See also #20656

**Comment by luxas** [comment]
Maybe we can close this as we have `go1.6` in some time ago already?

**Comment by wojtek-t** [comment]
Yes we can (also based on the fact that our Go folks explained it).

**Comment by ixdy** [comment]
Well, this issue was opened because Go 1.5 **builds** were much slower than 1.4. Go 1.6 builds are still pretty slow, though I'm not sure what can be done about it.

**Comment by wojtek-t** [comment]
Ahh ok - sorry. I misread it. I thought it was about system performance.

**Comment by ixdy** [comment]
I'm going to close as obsolete.
