### ISSUE TITLE
bugs in unversioned request

### ISSUE THREAD

**Issue by magicwang-cn** [kubernetes/kubernetes#20136]
- i think [this judgment](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/request.go#L649-L654) should close the response's body. 
- also its [UT test here](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/request_test.go#L482) is not a formal http response, it should has a response body.
- [this judgment](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/request.go#L782-L784) should behind [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/request.go#L778)

**Comment by magicwang-cn** [comment]
@davidopp @lavalamp

**Comment by lavalamp** [comment]
1. agree
2. it should be tested both ways, the client should live with error code and no body, even though I agree that's not what a server should send
3. I think it's OK the way it is

**Comment by magicwang-cn** [comment]
@lavalamp 
the second point, so why the [Stream test](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/request_test.go#L572) has't the [response](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/request_test.go#L482)? If so, [this code](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/request.go#L712) will be failed with using nil address.

**Comment by lavalamp** [comment]
@liggitt That Stream() function mentioned seems to lack clear semantics about when it is the caller's responsibility to close?

@magicwang-cn Any response going through the go http code will have a non-nil Body, so I'm not too worried about that. When I say "no body" I mean zero bytes, not literally nil Body pointer.

**Comment by liggitt** [comment]
> @liggitt That Stream() function mentioned seems to lack clear semantics about when it is the caller's responsibility to close?

It's the caller's responsibility whenever it gets a non-error response, right? The only time the Stream() func does a resp.Body.Close() is in the case where it is going to return a `nil, err`, so the caller would not be able to close it.

**Comment by lavalamp** [comment]
I see, thanks!

**Comment by magicwang-cn** [comment]
@lavalamp @liggitt 
yeah, i know that. but should not Stream() function take a test with as follows(`with a http.StatusForbidden response code, which is out of range with 200 to 300, if so, the test will failed with using nil pointer`), just like Watch()?

```
{
			Request: &Request{
				content: ContentConfig{GroupVersion: testapi.Default.GroupVersion(), Codec: testapi.Default.Codec()},
				client: clientFunc(func(req *http.Request) (*http.Response, error) {
					return &http.Response{StatusCode: http.StatusForbidden}, nil
				}),
				baseURL: &url.URL{},
			},
			Err: true,
		},
```

>Any response going through the go http code will have a non-nil Body, so I'm not too worried about that. When I say "no body" I mean zero bytes, not literally nil Body pointer.

**Comment by lavalamp** [comment]
Sure, we could add such a test and check for the nil pointer, it won't hurt anything. But it's also not an actual problem since as I understand it the go http framework would not do something like that, right?

**Comment by magicwang-cn** [comment]
ok, then i will send a PR.:)
