### ISSUE TITLE
test-cmd flake: first kubectl command (get nodes) fails

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#20154]
Encountered on #18901

```
!!! Error in ./hack/test-cmd.sh:203
  '[ "$(kubectl get nodes -o go-template='{{ .apiVersion }}' "${kube_flags[@]}")" == "v1" ]' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:203 runTests(...)
  2: ./hack/test-cmd.sh:1352 main(...)
Exiting with status 1
```

cc @kargakis

**Comment by kargakis** [comment]
kubectl is running with --match-server-version and versions between the client and the server fail to match
```sh
kube_flags=(
      -s "http://127.0.0.1:${API_PORT}"
      --match-server-version
    )
    [ "$(kubectl get nodes -o go-template='{{ .apiVersion }}' "${kube_flags[@]}")" == "v1" ]
```
```
Testing api version: 
error: server version (version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6.567+49b1b7c8b94d0b-dirty", GitCommit:"49b1b7c8b94d0b165aff87f0850d78f97ba075d6", GitTreeState:"dirty"}) differs from client version (version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6.567+49b1b7c8b94d0b", GitCommit:"49b1b7c8b94d0b165aff87f0850d78f97ba075d6", GitTreeState:"clean"})!
!!! Error in ./hack/test-cmd.sh:203
  '[ "$(kubectl get nodes -o go-template='{{ .apiVersion }}' "${kube_flags[@]}")" == "v1" ]' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:203 runTests(...)
  2: ./hack/test-cmd.sh:1352 main(...)
Exiting with status 1
```

**Comment by bgrant0607** [comment]
Thanks @kargakis.

Log:
https://00e9e64bac1987e009866fe0f2ff646b8f768a1861e5d901d6-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Ff3ca6064a59a00fc767f38216625ae1d0376e86c%2Fkubernetes-pull-test-unit-integration%2F10958%2Fbuild-log.txt?qk=AD5uMEsQggOGbuvt7hDBeqrpnKNODJ-3iNwAKdogdgNXgwojbU9dKWDBIFN0rtgdn5wwIZ9D_G5WT5g16Vw-YIe9YGjfJ2qSEzfxlbcBT_Oo_ZemhjuvThxtEuC3IWCiy_OQRdeqKC5fExwVCr2cQfGPOp1tXXrRMqGTT6qozYPOwcsvk7IUVRK6RQfF_p8ejVJWolrL3F-2JFxOHYEa4BacvRxNkccNOxWXTH2GmhUrwWXwc0k3j1lqD11NyVfIbtSWz9gltbZQtUB5g7AmInY_MQj51X3v_7UIWu8zxlAU-UXPJ9-RN35qnrxggTuLTyZIsAiBte5j8wHPY0--yA6j8PihaGWNgGreNizYWKKwLAV-neFRB1wIso7gwhLOCL7KJgtww7xPzsNEoB0UkcXxuvSIfteT6ULShWCRtEv8ATuskl0rKBRPtmEZXGVZ8RS8Lc5bkLB2GPsjOAxYrQ0kd7ulj8YxZ0VOjg0E95zYqVWI2u09OeyhslzO12T4wt-ZU7IICnKnHP2kXXC_FfocG5879mB3OLOhjHGbhKEW1FJSCbpMCN74XjuA_G-Ni0_2v9mckbeU7UQCUoGAgo4FbCH_Km8dpCUqhSULcN_OfTxZzSnjOdnvig75bC32q6uw5aBww9MHeABE07o_lNIC9GP7csuF1LBDlARHMegqVyCIwPKCX_Q_5Ijc7H83V-szWhjeRJ0FEyLEq9wPSbhJdCnMrxOX7JxzroOH7V3G15bhrDKyfraBzuCt3xtv0p4IkHMt_EzfIiul4v281VRchWlcyuHOv-FKmd7vbrCXhc7nfIv570Lt7VvaVR1gQgrWPiG1l5SEyGDt21w0sO0lmgA41NokJMGbEfedk0Gyjff5bpGKB_l0m8lAW8BO_7mlIYSgS8nSdTyesSDu1YI7xSaxlKTn4AF7Xr9JxYC5V4sIsMatiH70xE4VLHojzB_E0ituPDbCuQcsb7O4rskmboNLaquR3w

**Comment by bgrant0607** [comment]
Looks like it might be a problem with #18901 rather than a flake.

**Comment by kargakis** [comment]
> Looks like it might be a problem with #18901 rather than a flake.

Most probably the tmp file. Let's close this on green tests from 18901 and we can revisit it if we see that failure again

**Comment by bgrant0607** [comment]
Green
