### ISSUE TITLE
calling client.deployment.Update() without any change causes deployment to change

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#20168]
From https://groups.google.com/forum/#!topic/google-containers/ieYkPamnaw8

```
I am using the following client from kubernetes to drive a deployment:-
github.com/kubernetes/kubernetes/pkg/client/unversioned


Basically the scenario is :-

I use deployments.Update() to update the deployment by changing the replica count to 2. i see the following in 'kubectl get deployments


kubectl.sh get deployments

NAME                      UPDATEDREPLICAS   AGE

kudeplyreport-collector   0/2               13h

kubectl.sh get deployments

NAME                      UPDATEDREPLICAS   AGE

kudeplyreport-collector   2/2               13h



So we see the update got applied.


I use deployments.Update() again without changing anything in the k8s yaml and then 'get deployments' shows the following:-
kubectl.sh get deployments

NAME                      UPDATEDREPLICAS   AGE

kudeplyreport-collector   0/2               13h


So with no changing in the yaml, Update() api in the client, somehow starts the deployments but never completes it. This remains in this state forever. I am just thinking if this a bug in the client code or server side ?


Thoughts and how do i debug this?

Mayank
```

cc @krmayankk @janetkuo @caesarxuchao @kargakis @ironcladlou

**Comment by nikhiljindal** [comment]
I am unable to reproduce the problem.

I tried both `kubectl replace` (which uses unversioned.Client.Put()) and `curl PUT` directly.

The commands I ran are:
```
$ RUNTIME_CONFIG=extensions/v1beta1/deployments=true ./hack/local-up-cluster.sh
$ ./cluster/kubectl.sh create -f examples/extensions/deployment.yaml
$ ./cluster/kubectl.sh replace -f examples/extensions/deployment.yaml
$ curl -X PUT -d @/tmp//deployment.json http://localhost:8080/apis/extensions/v1beta1/namespaces/default/deployments/nginx-deploment -H "Content-Type:application/json" -v
```

@krmayankk can you please show the code that you are using?

**Comment by krmayankk** [comment]
I am using the go client in k8s , something like this and am testing against 1.1.3 release.

 config := client.Config{
        Host: "http://localhost:8080",
    }
    c, err :=client.NewExtensions(&config)
deployments := c.Deployments(ns)
deployment := new(extensions.Deployment)
newdeployment, err2 := deployments.Update(deployment)


Can you try the go client ?

**Comment by bgrant0607** [comment]
@krmayankk The Go client from what version of K8s? master/HEAD or release-1.1/HEAD, or ???

We've made non-backwards-compatible changes to Deployment since 1.1, so I wouldn't expect a client from the master branch to work with a 1.1 cluster.

**Comment by bgrant0607** [comment]
Also, replace generally doesn't work unless one does get-modify-replace.

**Comment by krmayankk** [comment]
@bgrant0607 go client from master against k8s cluster 1.1.3 in GCE. Yes  i am not doing get-modify-replace, so at the very release, i am defnitely not populating the resourceVersion while updating...

**Comment by lavalamp** [comment]
@krmayankk You really need to do get-modify-replace to have correct behavior. In addition to not getting the resource version, you're also not getting any of the server-applied field defaults. You're also asking the server to obliterate any annotations (or labels) applied by other components.

**Comment by lavalamp** [comment]
Please reopen if that doesn't solve the problem.
