### ISSUE TITLE
kubectl create secret tls

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20176]
Since we're getting basic tls support in ingress (https://github.com/kubernetes/kubernetes/issues/19497), it would be nice if kubectl created the right secret for you given a key/cert pair. Additionally it could verify that the key and cert match, and warn if there are missing intermediate certificates. I imagine this would work something like: 
`kubectl create secret tls NAME --key=path to private key --cert=path to cert`
- LoadX509KeyPair
- verify chain, or warn about self signed certs?
- create secret with type=tls

We could also probably warn about hostname mismatch, but that's hard to do without the context of the ingress.

**Comment by bgrant0607** [comment]
cc @derekwaynecarr

**Comment by smarterclayton** [comment]
@kargakis since we have equivalent code in routes today that needs to be moved into secrets

**Comment by derekwaynecarr** [comment]
I am in favor of doing this as well.

**Comment by bprashanth** [comment]
It would also be cool if:
```
kubectl create secret tls NAME
```
Just created a self signed cert usable in an Ingress. I put in some code to e2e test Ingress that one can use to do this: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/ingress_utils.go#L48
We can iterate on RSA vs ECDHE, size of key etc.

**Comment by smarterclayton** [comment]
Why would we want a self signed cert?

**Comment by bprashanth** [comment]
Why not? only if don't specify --key and --cert
Because I see a lot of confusion around getting off the ground with certs in general (base64 encoding, type/key names to use, etc). If people can create a working L7 with some valid self signed cert, and they know things work, they can easily swap it out for something real?

**Comment by smarterclayton** [comment]
Yeah, I can buy that.  I just suspect that folks might ask for infinite
parameterization here, so how do we draw the line to something reasonable.
I.e., we *don't* parameterize it, or have like 1 flag at best.

**Comment by bprashanth** [comment]
Not parameterizing makes sense. We should be able to choose unambigous defaults. We'll just keep updating the key size every 5 years :)

**Comment by bgrant0607** [comment]
@bprashanth Is this done?

**Comment by bprashanth** [comment]
The main parts are, https://github.com/kubernetes/kubernetes/issues/20176#issuecomment-198142836 is not (creating a self signed cert when no key/cert is given)

**Comment by thockin** [comment]
@bprashanth should we close this and open a new, more precise bug with an appropriate (not 1.3) milestone?

**Comment by bprashanth** [comment]
Sure

**Comment by pires** [comment]
What is the new issue then?

**Comment by bprashanth** [comment]
@pires yet unfiled, need to think through the features we need to add now that the basic stuff is in. 
is there something you want specifically captured in create secret?

**Comment by pires** [comment]
@bprashanth I just like the idea of simplifying the UX for making TLS cert/chain available to any Kubernetes resource without having to `cat`, `base64`, etc.

**Comment by bprashanth** [comment]
That'll already work in 1.3. What won't work yet is:
1. Validate certificate chain (https://github.com/kubernetes/kubernetes/issues/27010)
2. Create a self signed cert if no key/cert is specified

**Comment by pires** [comment]
@bprashanth ah, great. I'm good without those. Thank you!
