### ISSUE TITLE
ActiveDeadlineSeconds max value

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#20199]
While working on #20170, I realized there is no max value for `PodSpec.ActiveDeadlineSeconds`.  Obviously the max value of an int64 is not a reasonable number of seconds to request with this field.  What maximum value should we allow, if any?

@bgrant0607 @derekwaynecarr

**Comment by bgrant0607** [comment]
Why do we need a maximum? Is the presence of the feature expensive in Kubelet? Ideally we'd use some underlying OS timer mechanism.

I could imagine an admin wanting to set a configurable max, similar to LimitRange, so that batch jobs couldn't squat on resources indefinitely.

**Comment by derekwaynecarr** [comment]
I see no need to have a maximum.  The feature is not expensive to support on the Kubelet.

**Comment by soltysh** [comment]
I'd rather see this as yet another ResourceQuota item an admin could restrict along with cpu and memory rather than having separate max value for ADS.

**Comment by bgrant0607** [comment]
@soltysh This is more a LimitRange thing than a ResourceQuota thing. It doesn't need to be summed up across multiple resources.

**Comment by bgrant0607** [comment]
I'd like to be able to require that restartPolicy!=Always must have a reasonable deadline.

**Comment by soltysh** [comment]
@bgrant0607 agreed

**Comment by mdshuai** [comment]
RC control a pod with activeDeadlineSeconds!=nil and restartPolicy=always. it will always recreate a pod after exceed deadline seconds. 
should make restartPolicy!=Always
