### ISSUE TITLE
Steps to enable REST server components and client components to use versioned code, rather than the "__internal" APIs

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#20193]
### Goal

Most operations conducted by clients against the server are done using the primary API of the server (today, `v1`).  Internally, we must maintain a version of code that can be converted to all other API versions - we call this the `internal` version and it is denoted in the scheme as `__internal`.  All API operations start in a serialized form (either from a client or from etcd), are read as bytes / strings, loaded into a Go struct (known as an external type), defaulting is provided, then the object is converted to the internal API version and passed to the API machinery.  The value either then is sent to etcd or back to the client in a reversed process.  This conversion is mostly unnecessary - our internal objects track the primary external version quite closely, we end up maintaining N+1 versions of our objects instead of just N, and we generally require all objects to be 100% convertible to all supported API versions by introducing new fields on older versions that match the newer API version.  Removing the internal version results in less maintenance during refactors, and clearer outcomes in client code.

At the present time, a conversion operation is roughly ~15us, defaulting is roughly ~5us, and a JSON encode or decode is roughly ~60us.  When performing a simple GET from etcd, we decode, convert, default, process, convert, encode, which works out to about ~155us of CPU time for common operations in the apiserver (with associated garbage created), and on clients an equal amount of CPU time.  The forthcoming protobuf serialization drastically slashes the cost of encode/decode to ~5us. At that point the same operation might be about ~45us, of which ~30us is conversion.  We should be able to avoid the majority of that cost by skipping conversion on the common code path.  The reduction in CPU lost to garbage might be equally high, but is not quantified here.
### Steps on the path to removing __internal:
1. Define a way to perform defaulting on an object that doesn't go through conversion
2. Handle validation on versioned objects (moves validation from __internal to major external to start)
3. Be able to generate client libraries that are versioned and can avoid conversion if necessary
4. Generate conversions from the primary version to each other version instead of going through __internal.
5. Convert rest.Storage objects to use versioned form
6. Convert clients to use versioned client
7. ???
8. Remove internal types

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery taking notes here for tomorrow's meeting

**Comment by smarterclayton** [comment]
Discussion in meeting today:

1. The removal of __internal is effectively a rip and replace - find every "pkg/api" and turn it into "pkg/api/v1", remove code that depends on having internal representations.  This is a big refactor over the entire codebase, but is basically mechanical.
2. Protobuf is the first big win, so in 1.3 we'll try to get the core support in place, before we tackle the big refactor
3. Memory of controller caches is worth considering - may need a few things including:
  1. Lazy decode of the objects via interfaces in the cache
  2. Transforming the runtime.Object into a specific cached version (containing all the info needed) in reflector and hydrating it back on the way out (or force clients to fill them via gets)
  3. Using flyweights for common data patterns on the cache

**Comment by smarterclayton** [comment]
There have been arguments we should keep an internal version.  Arguments for are usually that it preserves flexibility to do internal refactors.  Arguments against is that it's one more conversion path to maintain, especially given that we *have* to round trip from our "preferred" version to all others with full fidelity.  I'm not convinced the internal refactor flexibility pays for itself in any of our practical use cases so far, but I respect the input.  We need to sort through what it would exactly look like.

Admissions definitely benefit from internal version, but any external admission controller (or initializers) get no benefit.

**Comment by bgrant0607** [comment]
@caesarxuchao Is some of this part of your current work?

**Comment by caesarxuchao** [comment]
> 3. Be able to generate client libraries that are versioned and can avoid conversion if necessary

This is done.

> 6. Convert clients to use versioned client

This is what I'm doing during the code freeze.

> 5. Convert rest.Storage objects to use versioned form

This can be done after my refactor. It needs step 4.

**Comment by smarterclayton** [comment]
Done.
