### ISSUE TITLE
strategicpatch.CreateTwoWayMergePatch cannot handle RawExtension fields

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#20208]
Extracted from https://github.com/kubernetes/kubernetes/pull/20093#issuecomment-175490502

The RawExtension type allows an API object to inline arbitrary JSON. strategicpatch.CreateTwoWayMergePatch returns an error trying to map that inlined JSON to struct fields. It should be able to compute a patch for an object containing a field of that type.

**Comment by liggitt** [comment]
cc @jackgr

**Comment by liggitt** [comment]
We need to decide what strategic merge patch should do in the following scenarios:
* unknown fields (can be encountered when the API or a user-defined object has a new field the compiled-in struct doesn't have yet)
* unmergeable fields (like RawExtension)

cc @soltysh @pwittrock @ymqytw

**Comment by ymqytw** [comment]
The current behavior is:

- unknown fields: trying to merge a unknown field will fail when lookup the metadata in the struct tags
- unmergeable fields: will be replaced as raw byte array

Maybe we can use generic json merge for unmergeable fields?

**Comment by liggitt** [comment]
> unmergeable fields: will be replaced as raw byte array

Did that change since 1.5? In 1.5, we were getting an error during patch computation

**Comment by ymqytw** [comment]
> unmergeable fields: will be replaced as raw byte array

Sorry. This behavior is in 1.4.7. e.g `ThirdPartyResourceData`. It will error in 1.5.

**Comment by liggitt** [comment]
> Sorry. This behavior is in 1.4.7. e.g ThirdPartyResourceData. It will error in 1.5.

Yeah, the `data []byte` field gets replaced. Even in 1.4.7, an unknown field (like initcontainers in pods) or an object including a RawExtension (anything with a field of type `interface{}` or `runtime.Object`) would error

**Comment by soltysh** [comment]
My personal favor would be to instruct the patch to ignore such field, seems the cleanest approach to me. Similarly to how we allow annotating deletion and merging.

**Comment by liggitt** [comment]
> instruct the patch to ignore such field

wouldn't it be confusing to submit a patch with stuff in that field, have the patch accepted, and have none of your submitted changes take effect? seems like the least surprising thing would be to treat unknown/unmergeable fields as `replace`

**Comment by soltysh** [comment]
How about both, iow. having `replace` as a default and `ignore` as an opt-in. This would allow the resource author to decide how his resource should be treated. Eventually on `ignore` we could return the ignored fields.
Having said that we could start with `replace` right away. I think I could work on a patch implementing that if majority agrees (@jackgr, @ymqytw).

**Comment by liggitt** [comment]
I think `replace` is a good place to start for known struct fields like RawExtension. I'll open a separate issue for client-side handling of unknown fields

**Comment by pwittrock** [comment]
@liggitt Ignore the field sounds like a really good solution.  WDYT of printing a warning to stdeer?

**Comment by liggitt** [comment]
> @liggitt Ignore the field sounds like a really good solution

what does ignoring instead of replacing get us?

**Comment by pwittrock** [comment]
Sorry I was reading the comment on my phone between other things.  Ignore my comment.
