### ISSUE TITLE
ECDSA not supported for CA

### ISSUE THREAD

**Issue by glerchundi** [kubernetes/kubernetes#20217]
Hi,

I tried to do this PKI configuration and didn't worked until I switch CA cert algorithm to RSA.

* This doesn't work:
```
Root CA: ECDSA-521
Intermediate CA: ECDSA-521
API Server Certificate: RSA-2048
```

* This works instead:
```
Root CA: RSA-4096
Intermediate CA: RSA-4096
API Server Certificate: RSA-2048
```

Is ECDSA unsupported?

Thanks,

**Comment by roberthbailey** [comment]
@liggitt

**Comment by liggitt** [comment]
The cert pool is parsed with https://golang.org/pkg/crypto/x509/#CertPool.AppendCertsFromPEM

I don't see anything explicit limiting that to RSA, but I'm not sure

**Comment by glerchundi** [comment]
Umm, I have two clusters (deployed using the same settings) one with ECDSA-521 and the other one with RSA-4096 for the Root/Int CAs and the former doesn't work. Doesn't work means that everything is working:
* can deploy rc/pods/, which means kubectl has valid client certificate & api server has a valid server certificate
* it can connect to etcd (which is outside) using a certificate issued by that CA.
* can exec into pods, which mean worker certificates are working properly

Except:
* cannot access master within a Pod using service account token and ca.crt in `/var/run...`. That was the main issue which forced me to investigate a little bit deeper. And everything seems to be OK, except kube-apiserver was continously throwing this line:

```
core@k8s-master ~ $ docker logs --tail=2 6a40f8e972ef
E0126 21:27:42.108131       1 handlers.go:37] Unable to authenticate the request due to an error: crypto/rsa: verification error
E0126 21:27:42.116646       1 handlers.go:37] Unable to authenticate the request due to an error: crypto/rsa: verification error
```

I'm using cfssl to create those certs, in case it matters.

**Comment by liggitt** [comment]
are you setting `--service-account-key-file` explicitly, or relying on it using `--tls-private-key-file`? Right now, only RSA keys are supported for generating service account tokens

**Comment by glerchundi** [comment]
Setting `--service-account-key-file` explicitly:

https://github.com/glerchundi/infrastructure-kubernetes/blob/master/files/kube-master.yml#L174

But take into account that API Server itself is a RSA-2048.

**Comment by liggitt** [comment]
Are you setting the same key in the controller manager as `--service-account-private-key-file`?

**Comment by glerchundi** [comment]
@liggitt yep: https://github.com/glerchundi/infrastructure-kubernetes/blob/master/files/kube-master.yml#L318

**Comment by liggitt** [comment]
Have you redeployed with different keys against old etcd data? Is it possible you have service account tokens that were created with a previous key still sitting in etcd?

**Comment by glerchundi** [comment]
Yes! Can you explain me why is that an issue? And how should I solve it?

**Comment by glerchundi** [comment]
As you can see I have two different repositories to deploy both in different stages:
* https://github.com/glerchundi/infrastructure-etcd2
* https://github.com/glerchundi/infrastructure-kubernetes

**Comment by liggitt** [comment]
The controller manager generates service account tokens for every service account using the private key it is given. Those tokens live in secrets in namespaces, and are injected into pods. If you restart the controller manager with a new service account key, new tokens it generates will use the new key, but old ones still exist until they are deleted.

Right now, only a single key at a time is supported, so if you change the key, you need to remove the secrets containing the old tokens from etcd, and the controller manager will regenerate new ones with the current key.

See https://github.com/kubernetes/kubernetes/issues/20165 for a discussion about supporting rotation of these keys.

**Comment by glerchundi** [comment]
@liggitt just to finish this up, how should I revert my failing cluster back to a state where I can connect to the master within Pod and do not have rsa errors y the api-server? ;)

In short, how should I proceed deleting service-account tokens manually in case I change api-server certs, for example, due to a renewal process?

**Comment by liggitt** [comment]
deleting the stale service account tokens and letting the controller manager regenerate them should be sufficient. __If you don't have other secrets you care about__, you can do a blanket delete of ALL secrets (`kubectl delete secrets --all-namespaces`).

If you do have other secrets you want to preserve, you'll likely need to do a fieldSelector of "type=kubernetes.io/service-account-token" to limit which secrets you want to delete.

**Comment by glerchundi** [comment]
@liggitt, i'm going to do a full test of this and come back again with the results. thanks for your help :)

**Comment by glerchundi** [comment]
@liggitt you were right, its not something related to the CA, it was something related to service tokens validity within a concrete CA.

I came across this snippet to delete all service tokens without touching anything else:

```
kubectl get secrets --all-namespaces -o jsonpath='{range .items[?(@.type=="kubernetes.io/service-account-token")]}{.metadata.namespace} {.metadata.name} {end}' | \
xargs -n 2 | \
xargs -I % sh -c "kubectl delete secrets --namespace=%"
```

As a bonus, i first backuped those using `jq`:
```
kubectl get secrets --all-namespaces -o json | jq -c '.items[] | select(.type == "kubernetes.io/service-account-token")?' > old-service-account-tokens.txt
```

Thanks for your valuable help @liggitt & @roberthbailey, closing this.
