### ISSUE TITLE
kube-addon-update fails badly if api server is unavailable

### ISSUE THREAD

**Issue by petermd** [kubernetes/kubernetes#20219]
`kube-addon-update.sh` does not check the status of the `get-addon-nsnames-from-server` call to fetch the list of installed addons.

if apiserver is unavailable (or if the request times out) this causes it to think the error message is the list of services and enter a loop of trying to remove imaginary services and re-create existing ones. 

i assume all of these just error out quickly but the retry policy means it ends up running all 60 retries x num addons which on a limited spec (eg the default aws t2.micro configuration) can amplify the original failure and help brick the master node (see #18975)

the simple fix to check status and abort (https://github.com/petermd/kubernetes/commit/4d4f1c645cbb75c444f7e33463b871c21da7890b) is enough to stop the problem, and any missing addons will be updated on the next iteration.

it _might_ be worth considering making the retry policy back off and/or not use the entire check interval as the retry period (otherwise you could potentially have multiple instances running trying to update the same service)

**Comment by davidopp** [comment]
@petermd can you send out the commit you referenced as a PR? I think that's the most we'll be able to do in time for the 1.2 release.

@fgrzadkowski Do you have a suggestion who should review it? I'm not sure who took ownership of kube-addon-update.sh after @marekbiskup left the team.

**Comment by marekbiskup** [comment]
Yes it's better that someone else takes the ownership of kube-addon-update.sh (probably a lot has changed since I worked on it). But I'm happy to help as a second reviewer, if needed.

**Comment by petermd** [comment]
Happy to submit PR but I need a valid CLA (submitted but not sure if it needs manual approval for corp agreements)

**Comment by fgrzadkowski** [comment]
@davidopp @petermd I can review it. Probably someone from GKE ( @roberthbailey ? ) should also take a look to verify it doesn't break GKE.

**Comment by roberthbailey** [comment]
@zmerlynn or I can take a look.

**Comment by davidopp** [comment]
@petermd Doesn't look like the CLA bot recognizes you yet. Please go to
https://cla.developers.google.com/clas
and follow the instructions for signing the CLA as an individual or as part of your company, whichever you prefer.

Do you think you can send a PR for this in the next couple of days?

**Comment by petermd** [comment]
@davidopp seems like the CLA ok. let me know if there is something missing

**Comment by davidopp** [comment]
Thanks a lot @petermd . The other ideas in your fist comment sound good too, but IIUC the PR you wrote (which is now merged) is sufficient for now.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
I'm assuming sig-cluster-lifecycle owns addon management
