### ISSUE TITLE
prefer kubectl output global flags on top of specific ones

### ISSUE THREAD

**Issue by mdaniel** [kubernetes/kubernetes#20225]
This is kind of like #4142 except my suggestion would be to place the global ones at the top of the output and the more specific ones at the bottom.

The reasoning is that in an 80x35 terminal, typing `kubectl port-forward --help` causes the 24 lines of global help to occupy almost the entire window, necessitating that one scroll back to see the content that the user _specifically_ requested: that of the sub-command.

A supporting reason is that after a while, one will certainly know the global flags (if for no other reason than the user will see that text for every invocation of `--help` right now), but remembering the flags for all 27 sub-commands is daunting.

**Comment by bgrant0607** [comment]
`| less` or `| head -20`? I wouldn't want to force users to wade through lots of flags, as we add more and more.

We also put these flags into docs and man pages.

Thanks for the suggestion, but I don't envision us reversing the order.
