### ISSUE TITLE
federated api servers: Implement a discovery merger

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#20229]
Subtask from https://github.com/kubernetes/kubernetes/pull/17191

A go program that will fetch discovery info from all federated servers and provide a summarized view.

In addition to the discovery information that apiservers currently surface, we need to add a server URL.

Open questions:
- Extend the existing APIGroupList (https://github.com/kubernetes/kubernetes/blob/e108a32b082f2c91d853c898f51a02729c911b1c/pkg/api/unversioned/types.go#L307) and add a server URL there or define a new one?
- Return the appropriate server URL for internal and external clients. 
  - Do we want to do this? 
  - Can we auto detect if the request is from a client inside the cluster or external? 
  - Or should the request have a way to specify that? 
  - How does the client figure out that is it inside the cluster for master or not?

@kubernetes/sig-api-machinery @kubernetes/goog-csi @smarterclayton @lavalamp @thockin @bgrant0607

**Comment by nikhiljindal** [comment]
Summarizing discussion with @thockin, @bprashanth and @lavalamp 

- We can let the summarizer decide that should it return the internal IP or the external one or let the summarizer return both and the client can choose which one it should use.
  - Not sure how can client know if its in the same cluster as master.
- One use case where client wants to know both the addresses is when it can talk to server using internal IP address, but wants to put external address in its output.
  - If we want to let summarizer decide but want to return both IPs to client, then we can return 2 addresses: one the address that client should use to contact the master and other the public IP address.
- Still need to figure out how can summarizer decide whether client and master are in the same cluster or not.

Just to clarify, nothing will be broken if we just use the public IP address everywhere. Its more efficient to use internal IP if possible. We can discuss if the gain is worth the additional complexity.

**Comment by bprashanth** [comment]
>We can let the summarizer decide that should it return the internal IP or the external one or let the summarizer return both and the client can choose which one it should use.

The public/internal ip problem is harder because the summarizer, apiserver and client can all be in different clusters, and going across the edge will incur NAT. It's easy if there are only 2 parties, the client and some server that responds with a public or private ip, because then we can prefix match for (10., 172., 192., public). I think we'll need to pack more information into the request, perhaps master and client are aware of a cluster-tag, and the client shoves the tag into a http header, and the master includes the tag in the discovery info it reports.

**Comment by bgrant0607** [comment]
Why do we need a server URL?

I wouldn't create a new struct/endpoint. Adding it to the existing discovery info seems fine.

Whatever our solution is, we should try to apply it to the swagger API, also.

**Comment by nikhiljindal** [comment]
Yes, so master and client will have to agree on a mechanism to get a cluster tag which should be unique for each cluster.

> Why do we need a server URL?

If clients want to talk to that server directly instead of going through the proxy.

> I wouldn't create a new struct/endpoint. Adding it to the existing discovery info seems fine.

The current discovery types are unversioned. I assume that we are allowed to change it because we are adding a field?

> Whatever our solution is, we should try to apply it to the swagger API, also.

You mean the summarizer should merge swagger spec from all individual servers as well?
