### ISSUE TITLE
kube-up scripts and GCE/gcloud create root owned directories

### ISSUE THREAD

**Issue by sjpotter** [kubernetes/kubernetes#20228]
every day gcloud creates a new $USER_DIR/.config/gcloud/logs/<date> directory.

kube-up runs gcloud under sudo w/ root permissions so if the first time you run it in a day, the directory gets created with root permissions and hence can't be used without root.

my hack fix is to run a gcloud compute instances list every day at the begnning to get the directory created as me.

A better Q might be why gcloud has to be run as root at all.  That's partly related to the fact that it tries to update itself but in my case it cant as I'm using the apt gcloud repository.  But even in that case, it would seem to cause problems.  Wondering why no one else has seen it?

**Comment by sjpotter** [comment]
@mikedanese signode meeting said you might know about this.

**Comment by quinton-hoole** [comment]
@sjpotter please try http://stackoverflow.com/questions/tagged/kubernetes.

**Comment by sjpotter** [comment]
?

**Comment by mikedanese** [comment]
This is not the normal behavior. Did you install gcloud with sudo? Feel free to fix.

**Comment by mikedanese** [comment]
> I'm using the apt gcloud repository.

this won't happen if you install it with `curl https://sdk.cloud.google.com | bash`

**Comment by sjpotter** [comment]
the problem is that kube-up runs gcloud under sudo in order to check if it should be updated (able to disable with an env variable).

that gcloud run (if the first of the day) creates the day's log dir as root and hence future runs of gcloud do not work.

I dont see a way to fix it without a hack.

**Comment by mikedanese** [comment]
it doesn't run as sudo if you install it with `curl https://sdk.cloud.google.com | bash`

**Comment by mikedanese** [comment]
This https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L76 check needs to be made better

**Comment by sjpotter** [comment]
Probably the correct fix is for gcloud to have a command to determine if
its package manager installed.  It already knows that it is and fails the
self update routines because of that.

**Comment by sjpotter** [comment]
kube-up still has this problem.  I think this is the proper fix (sorry for patch).

namely 

1) if running gcloud as root, need to change its home directory to root so it wont drop root owned dirs/files in the user's home directory

2) don't run gcloud as root if just need the version.

```diff
diff --git a/cluster/common.sh b/cluster/common.sh
index d250960..6a423ee 100755
--- a/cluster/common.sh
+++ b/cluster/common.sh
@@ -1014,7 +1014,7 @@ function parse-master-env() {
 function update-or-verify-gcloud() {
   local sudo_prefix=""
   if [ ! -w $(dirname `which gcloud`) ]; then
-    sudo_prefix="sudo"
+    sudo_prefix="sudo -H"
   fi
   # update and install components as needed
   if [[ "${KUBE_PROMPT_FOR_UPDATE}" == "y" ]]; then
@@ -1022,7 +1022,7 @@ function update-or-verify-gcloud() {
     ${sudo_prefix} gcloud ${gcloud_prompt:-} components install beta
     ${sudo_prefix} gcloud ${gcloud_prompt:-} components update
   else
-    local version=$(${sudo_prefix} gcloud version --format=json)
+    local version=$(gcloud version --format=json)
     python -c'
 import json,sys
 from distutils import version
```
