### ISSUE TITLE
All hyperkube and hyperkube-amd64 images should be pushed

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#20235]
There's an issue in https://github.com/kubernetes/kubernetes/pull/19061/files#r50636543, that makes `push-official-release.sh` only push `hyperkube-amd64`, not `hyperkube`.
We should also push v1.0.1 and higher images as `hyperkube-amd64`.
This is a blocker for: #19929 and using the `docker.md` and `docker-multinode.md` guides.

Could you bump this up to P1, because this have to be solved before `v1.2`?
@fgrzadkowski @mikedanese @ixdy @zmerlynn @brendandburns @thockin @wojtek-t @gmarek 

Currently pushed images:
```console
$ curl -k -s -X GET https://gcr.io/v2/google_containers/hyperkube/tags/list | jq -r '.tags[]'
0.14.1
dev
v0.14.1
v0.14.2
v0.15.0
v0.16.1
v0.16.2
v0.17.0
v0.18.2
v0.19.3
v0.21.2
v1.0.1
v1.0.2
v1.0.3
v1.0.5
v1.0.6
v1.0.7
v1.1.0-alpha.1
v1.1.1
v1.1.1-beta.1
v1.1.2
v1.1.3
v1.1.4
v1.1.7
$ curl -k -s -X GET https://gcr.io/v2/google_containers/hyperkube-amd64/tags/list | jq -r '.tags[]'
v1.1.2
v1.2.0-alpha.6
v1.2.0-alpha.7
```

**Comment by borg286** [comment]
Is it necessary to push etcd images also?

**Comment by danderson** [comment]
FWIW, it looks like v1.1.7 was released without being pushed to either repository.

**Comment by luxas** [comment]
@borg286 `etcd` was pushed by @thockin some days ago. I don't think that's tightly coupled with the release process. Instead, one should push a new `etcd` image when bumping the version numbers.

@danderson Yes, they do it manually right now. #19061 isn't back-ported to `release-1.1` yet.

**Comment by ihmccreery** [comment]
@danderson @luxas Sorry about that; it's not been pushed.

**Comment by ihmccreery** [comment]
Oops; it *has* been pushed (v1.1.7 `hyperkube`).

**Comment by luxas** [comment]
@ihmccreery Can you review #19769? It would be great to get it merged...
It contains a fix so plain `hyperkube` is being pushed in the same manner as `hyperkube-amd64`

**Comment by luxas** [comment]
Updated the list above. `v1,1.7` is now pushed, but only for `hyperkube` and `v1.2.0-alpha.x` only for `hyperkube-amd64`

**Comment by ihmccreery** [comment]
> @ihmccreery Can you review #19769? It would be great to get it merged...

Sorry, I'm not the right person to review that; I'm pretty unfamiliar with the build logic.  Looks like you've got some reviewers already though?

> Updated the list above. v1,1.7 is now pushed, but only for hyperkube and v1.2.0-alpha.x only for hyperkube-amd64

Yeah, unfortunately release-1.1 doesn't have logic in place to release hyperkube and hyperkube-amd64.  We tried to patch it in, which is what caused the v1.1.6 failure (see https://github.com/kubernetes/kubernetes/pull/19935).

**Comment by luxas** [comment]
OK, I'll try to get @zmerlynn's attention then...

But is it @fgrzadkowski who is gonna manually push `hyperkube-amd64` versions >= 1.0.1?
It's just a 
```
export REGISTRY="gcr.io/google_containers"
docker pull ${REGISTRY}/hyperkube:${VERSION}
docker tag ${REGISTRY}/hyperkube:${VERSION} ${REGISTRY}/hyperkube-amd64:${VERSION}
gcloud docker push ${REGISTRY}/hyperkube-amd64:${VERSION}
```
and vice versa (for `v1.2.0-alpha.x`)
Or could you do it? That's what this issue is about... (plus merging #19769)

**Comment by ihmccreery** [comment]
I'm not convinced we should be releasing hyperkube-amd64 for pre-v1.2 releases ... that seems like revising history to me.  But I will let @fgrzadkowski make that call.  @david-mcmahon might also have opinions.

**Comment by zmerlynn** [comment]
Unless there's a compelling reason to, I'm not convinced we should muck with build mechanics in the release branch either. It can be kind of painful and error prone because it involves making sure you cherry-pick any intermediate step, too. (I went through this with the documentation mechanics, and still have nightmares.)

**Comment by luxas** [comment]
@ihmccreery It's automatically released. @fgrzadkowski made a PR that automatically pushes `hyperkube-amd64` when doing a release: #19061

**Comment by ihmccreery** [comment]
@luxas Yes, but per @zmerlynn's comment above, which I agree with, we don't want to backport #19061 to v1.1.  So going forward, these images will be released, but not for v1.1.

**Comment by fgrzadkowski** [comment]
@luxas I tend to agree with @ihmccreery and @zmerlynn. Unless we have very good reasons, messing up with 1.1 is not the right thing to do. Especially that 1.2 will be here very soon.

**Comment by luxas** [comment]
@fgrzadkowski @ihmccreery I think we're not understanding each other. Sorry.
I do not think or propose that we should backport #19061 to the `release-1.1` branch.

The thing I would like though, is that @fgrzadkowski pushes all `hyperkube` images on the >= 1.0.1 as `hyperkube-amd64` too. You just have to run this script:

```bash
export REGISTRY="gcr.io/google_containers"
for VERSION in "v1.0.1 v1.0.6 v1.0.7 v1.1.1 v1.1.2 v1.1.3 v1.1.4 v1.1.7"; do
    docker pull ${REGISTRY}/hyperkube:${VERSION}
    docker tag -f ${REGISTRY}/hyperkube:${VERSION} ${REGISTRY}/hyperkube-amd64:${VERSION}
    gcloud docker push ${REGISTRY}/hyperkube-amd64:${VERSION}
done
```
The thing I want is harmonized pushes between `hyperkube` and `hyperkube-amd64`. We should slowly deprecate `hyperkube`, but until then they should be nearly identical.

So, this has nothing to do with the release code, it's just about harmonizing two identical images.

**Comment by fgrzadkowski** [comment]
@luxas Ok, know I understand :) This makes sense. I'll try to do it this week.

**Comment by fgrzadkowski** [comment]
@luxas We have discussed with @ihmccreery and it sounds like tweaking history. Why do you need `-amd64` images for `v1.0.1` or other old images? I think that for newer 1.1.7 we already published all images, so why change it for older? Also, as you in few weeks we will start pushing all images as part of regular release process, so maybe that's enough. WDYT?

**Comment by luxas** [comment]
For me (personally) it doesn't make sense (I'm living on the edge :smile:)
But I just thought that it could be useful, because now `1.2.0` or newer is a must for some of the guides in the docs, so there's really no choice for the user.

> Decide what Kubernetes version to use. Set the ${K8S_VERSION} variable to a released version of Kubernetes >= "1.2.0-alpha.7"

This fixes the issue partially, and was merged some days ago. 
Is it possible to compromise? I would like at least `v1.1.1` and `v1.1.7` to be pushed as `hyperkube-amd64`.
But I don't really get how you see this as rewriting history... Could you explain a little bit more what you mean?

Since the docs now requires `v1.2.0-alpha.7` and up, this isn't critical anymore, but I'm just wanting to make sure k8s images is somehow backwards-compatible.
Of course, this is up to you. 

If we go in for `hyperkube-amd64`, we should replace all `hyperkube` references and add a note to e.g. `docker.md` that `hyperkube` is deprecated (but still pushed for a while) since `v1.2`.

A thing that could be added also, is the script that I used here: `curl -k -s -X GET https://gcr.io/v2/google_containers/hyperkube/tags/list | jq -r '.tags[]'`. It's much easier than trying to pull them one by one.

**Comment by fgrzadkowski** [comment]
Documentation at HEAD that you're referring to is using `v1.2` which already has both images pushed. For older instructions we have older images, which is also ok. I think this means that if someone is using any version of documentation it should be ok.

Closing.

**Comment by luxas** [comment]
Yeah, this was fixed when I updated the docs to require `v1.2.0-alpha.7` or newer on `master`

Are a `v1.2.0-alpha.8` on its way btw?

**Comment by ihmccreery** [comment]
> Are a v1.2.0-alpha.8 on its way btw?

Yes; @david-mcmahon is cutting one today, I believe.

**Comment by luxas** [comment]
@david-mcmahon Please merge this first #21557!!

**Comment by david-mcmahon** [comment]
1.2.0-alpha.8 release failed with:
+++ [0219 18:04:50] Pushing hyperkube to gcr.io/google_containers/hyperkube-amd64:v1.2.0-alpha.8
The push refers to a repository [gcr.io/google_containers/hyperkube-amd64] (len: 1)
error getting tags for gcr.io/google_containers/hyperkube-amd64: Tag does not exist for v1.2.0-alpha.8
!!! Error in build/../build/common.sh:1538
  '"${docker_push_cmd[@]}" push "${docker_target}"' exited with status 1

Investigating...

**Comment by david-mcmahon** [comment]
False alarm.  User error.  Closing.
