### ISSUE TITLE
Consider removing influxdb-grafana-controller from kube-system when running e2e test? 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#20247]
Forked from #20230, and the detail reason can be found at: https://github.com/kubernetes/kubernetes/issues/20230#issuecomment-175906218

In summary, e2e test keeps reboot the node, which might corrupted checkpoints of influxdb. Most of our users use different backen storage for their heapster, including gke, and openshift. Also our monitoring test should retrieve stats through heapster API only anyway. 

cc/ @mwielgus

**Comment by dchen1107** [comment]
@mwielgus I assigned this to you for triaging. cc/ @vishh

**Comment by gmarek** [comment]
We shouldn't be removing from test clusters anything that's supposed to run in production ones. cc @davidopp @thockin

**Comment by vishh** [comment]
I think the idea is to make InfluxDB opt-in and have users place resource
requests/limits for InfluxDB. We have alternate dashboard(s) now which
provide some basic monitoring functionalities.

**Comment by gmarek** [comment]
I think that even if we want it to be opt-in only, we should make sure it works. I.e. don't remove it from tests.
