### ISSUE TITLE
Make our Reboot tests more specific

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20250]
Our "Reboot" tests have been causing us a lot of pain recently, but have been uncovering important issues.

In talking with @dchen1107 today, it seems like we need to write more specific reboot tests to catch a variety of underlying issues with the node and various startup and shutdown troubles.

@dchen1107 Can you provide some thoughts on how we might make these tests better or more useful?

**Comment by yujuhong** [comment]
Some random thoughts:
 - Validate that the cluster is healthy (nodes/pods are ready) *before* the test and *fail the test immediately* if cluster is unhealthy. Right now even if one node fails, the test'd go ahead and test other nodes.
 - Handle the logging messages better. The interleaved messages from different nodes makes triaging very difficult
 - Perform sanity checks after the reboot, .e.g, compare the node status and see if anything changes (docker version, node version, ...). 
 - ...
