### ISSUE TITLE
Kubelet doesn't detect changes in hostNetwork properly

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20251]
dockertools/manager.go: podIfraContainerChanged() checks if the pod is asking for hostNetwork and Docker is not currently using it, but not the other way around.

**Comment by cmluciano** [comment]
@yujuhong Any idea if this is still relevant?

**Comment by yujuhong** [comment]
@cmluciano not sure. You can check the pkg/kubelet/kuberuntime/kuberuntime_manager.go to see if it's fixed by the new implementation. Thanks!

**Comment by cmluciano** [comment]
@thockin I see similar logic in the new implementation [here](https://github.com/kubernetes/kubernetes/blob/release-1.6/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L388-L393). 

I'm not sure if I understand the issue enough to validate if it is fixed.

**Comment by thockin** [comment]
I am not sure how we would end up in this codepath, but it seems to me that
one is as likely as the other, and if we check one, we should check both
(and comment why).  Or neither.

**Comment by yujuhong** [comment]
From the code @cmluciano posted above: `sandboxStatus.Linux.Namespaces.Options.HostNetwork != kubecontainer.IsHostNetworkPod(pod) ` seems general enough. 
In reality, apiserver won't allow flipping the host network bit in the pod spec, so we won't hit this at all.

**Comment by thockin** [comment]
Agree - close this?
