### ISSUE TITLE
Sync pods with store before starting controllers

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#20259]
copy from https://github.com/kubernetes/kubernetes/pull/19043
>
the framework of controller(`Informer`) works as follows(use ReplicationManager ads example):

>1) ReplicationManager use Informer to list&watch rcs/pods
2) When restart, Informer first list all pods, and add them to `DeltaFIFO`
3) A Process routine pop pod one by one from `DeltaFIFO` and sync it to `podStore`, and call `ResourceEventHandlerFuncs`. 
4) `ResourceEventHandlerFuncs` will list all the rcs in `rcStore` to find the matching one, and put it into workqueue.
5) Several routines pop rc from workqueue and sync it(create new replicas or delete redundant ones)

> If cluster size is large, when the work routine pop rc from workqueue and start to sync it, podStore may has not been syned. A large number of Pods are 
still remained in  `DeltaFIFO`, but has not been synced to `podStore`. In such a case, ReplicationManager will make wrong decision when it manage 
replicas if `podStore` has not been synced..

>We do has a flag to indicate wheter `podStore` has synced (see: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L170) 
But it's not correct, this flag will be set as true once reflector list pods 
(https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/reflector.go#L253), 
but at that time, they has not been synced to `podStore`, they are still in `DeltaFIFO`)

Several solution to fix this `pod store synced` problem:

1) @bprashanth add a `SyncAllPodsWithStore` method which lists all pods and inserts them into the 
given store. see: https://github.com/kubernetes/kubernetes/pull/19973

***Pros*** 

* Easy to understand and implement.
* No need to hack `Informer`

***Cons***

* Informer｀ will receive "Update" events for all the pods in the store, instead of "Add", which means ReplicationManager must put the rc into workqueue when observe an "Update" event, even if the ｀rc.Spec｀ not change. Current, ReplicationManager work like this, so there is no problem. However we may eventually want just put rcs into workqueue only if `rc.Spec` changed when observe an `Update` event. 

2) Insert a dummy pod into `DeltaFIFO` after list and befor watch, when `Informer` observe this dummy pod, it will set`rm.podStoreSynced` as true.

***Pros*** 

* Easy to understand and implement.

***Cons***

* Need hack `Reflector`, which is called by other application, instead of just `Informer`. Not all application need a 
dummy pod to decide if `Store` has synced.
* `Process` routine of `Informer` could not run in parallel

3) Add a `SyncDeltaFIFO` to replace the current `DeltaFIFO`, `SyncDeltaFIFO` is only used by `Informer`

Details: 

```
//SyncDeltaFIFO` is exactly like a `DeltaFIFO`, but implement a `HasSynced()` method too, which is very helpful for `Informer`.
type SyncDeltaFIFO struct {
    
    lock sync.RWMutex
    cond sync.Cond

    items map[string]Deltas
    queue []string

    syncQueue []string // used to save the first batch of pods that would otherwise be save to SyncDeltaFIFO.queue.
    firstSync bool  // Indicaitng if Replace() method has been called

    keyFunc KeyFunc

    deltaCompressor DeltaCompressor

    knownObjects KeyListerGetter
}

```

`SyncDeltaFIFO` is exactly like a `DeltaFIFO`, but has a `HasSynced()` method too, which is very helpful for `Informer`. When the `Replace()` method of `SyncDeltaFIFO` is ***first*** called, it will put the first batch of items into `syncQueue`. When the`Pop()` method is called, it first pop from the `firstSyncQueue`. When `firstSyncQueue` becomes empty, `HasSynced()` will return true.

***Pros*** 

* No need to hack `Informer` and `Reflector`

***Cons*** 

* seems no drawbacks.

**Comment by mqliang** [comment]
@smarterclayton @lavalamp

**Comment by mqliang** [comment]
I vote for solution 3). Ff there are no better solution.

**Comment by smarterclayton** [comment]
Agree that solution 3 is better - sorry for the delay in responding :)

**Comment by mqliang** [comment]
This could been closed, since https://github.com/kubernetes/kubernetes/issues/20269 has been merged.
