### ISSUE TITLE
Kubernetes uses Openstack cloud provider, but X509 ERROR occurs

### ISSUE THREAD

**Issue by drngsl** [kubernetes/kubernetes#20266]
Hi!
(1)cloud-config for kubelet
/etc/cloud.conf
[Global]
auth-url=https://identity.hybrid.cloud.dt.com:443/identity/v2.0
username=admin
#user-id=ccb1020e9b9e47bd98c4df38cd426590
password=******
region=RegionOne1
tenant-id=a1fa87b6b770496e929685fd5f1e0e18

(2)restart kubelet service with cmd
kubelet --cloud-provider=openstack --cloud-config=/etc/cloud.conf --v=5

(3)Just two logs are printed like following
I0128 12:27:42.104244   15424 server.go:524] Using self-signed cert (/var/run/kubernetes/kubelet.crt, /var/run/kubernetes/kubelet.key)
could not init cloud provider "openstack": Post https://identity.hybrid.cloud.dt.com:443/identity/v2.0/tokens: x509: certificate is valid for *.*.*.domainname.com, not identity.hybrid.cloud.dt.com

And Other information
kubernetes version is v1.1.4.

So, why does X509 error occur?
And can kubernetes v.1.1.4 connect to openstack successfully?
Or need I update it to v1.2.0-alpha.6?

Thanks!

**Comment by a-robinson** [comment]
Closing in favor of your other issue (#20146)
