### ISSUE TITLE
Deprecate specifing resources with space

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#20265]
Currently when asking for a resource you can do either: `kubectl get pod nginx` or `kubectl get pod/nginx`. The latter syntax is broadly applied and more readable, whereas the former has some drawbacks I've raised in https://github.com/openshift/origin/issues/5685. Given the fact there's a lot of work on api grouping (#20120 and others not mentioned here) I'm proposing to deprecate providing resource with a space (`pod nginx`) and allow only slashed approach (`pod/nginx`). This should allow to simplify parsing, especially for commands allowing to provide more than one resource at a time and scriptability of kubectl.

@bgrant0607 @janetkuo @smarterclayton  wdyt
@deads2k @kargakis fyi

**Comment by deads2k** [comment]
I would be happy to see the space based syntax removed.

**Comment by smarterclayton** [comment]
We can stop introducing it in new places, but it's going to a long
time before we can remove it.  I would be hard pressed to justify
making out most common cli invocations suddenly stop working for end
users.

**Comment by bgrant0607** [comment]
The log command has been inconsistent with others for a long time: #8884, #8448

That's not a good reason to eliminate this syntax from all other commands. It's pretty convenient to be able to specify the resource type just once for many names, without commas or other punctuation. Also, we need to specify just the resource when using a label selector.
