### ISSUE TITLE
Ingress: Majority of faulty pods will take all backends offline

### ISSUE THREAD

**Issue by tback** [kubernetes/kubernetes#20270]
It seems that a majority of faulty backends will mark all backends as offline while there still healthy pods left. I'd expect the loadbalancer to work as long as a single healthy pod is left.

My example is located here:

https://github.com/tback/k8s-lbtest

(I know that something is fundamentally wrong if the majority of backends is faulty, but taking all backends offline in that case feels like adding fuel to the fire)

**Comment by tback** [comment]
Clarification: To me this looks like a game of probability. In theory it should be possible that a single faulty node takes down all backends and therefore the whole site.

**Comment by bprashanth** [comment]
@tback see explanation in https://github.com/kubernetes/kubernetes/issues/19927#issuecomment-173703098, duping this bug to that one (also this is not about the Ingress but specifically about GCE L7 -- not nitpicking, just pointing out the difference between the ingress api object and the controller that fulfills it ;)
