### ISSUE TITLE
Initial Resources e2es are broken

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20272]
According to @piosz, the "Initial Resources" e2e tests are broken (>50% flaky) and should be fixed.

@piosz for priority.

**Comment by piosz** [comment]
This is en experimental feature, so there is no high priority right now.

**Comment by piosz** [comment]
Reassigning to @jszczepkowski and @krzysztofgrygiel who will work on the new version of Iniital Resources/Vertical Pod Autoscaler.

**Comment by mwielgus** [comment]
Being removed in https://github.com/kubernetes/kubernetes/pull/47876.
Currently not run anywhere. Closing.
