### ISSUE TITLE
Kubelet errs out when AWS node has no public IP address

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#20280]
I'm trying out v1.2.0-alpha.6. I got `Unable to construct api.Node object for kubelet: failed to get node address from cloud provider: UnknownError: unknown error` in the kubelet log and the node fails to join the cluster. There are two things wrong:

- The error message needs to be better
- It shouldn't be a requirement for nodes to have public IP addresses

The relevant commit: https://github.com/kubernetes/kubernetes/commit/64aa189bd2e9a34b84068184ae66e43bfc05dacb

**Comment by dchen1107** [comment]
@justinsb Are you going to get this one for 1.2 release?

**Comment by justinsb** [comment]
Yes - I believe the required changes are already merged.  This work was done by @dpratt in #20372 and   @jtblin in #20378 .  Hopefully once we get the next alpha out, they can confirm.

**Comment by davidopp** [comment]
ping

**Comment by jtblin** [comment]
There hasn't been any 1.2 alpha or beta release since these changes have been merged.

**Comment by dchen1107** [comment]
@justinsb should we close this one since both prs are merged for a while? Thanks!

**Comment by dchen1107** [comment]
Closed this one based on above comment made by @justinsb and @jtblin. Please re-open it if disagree.
