### ISSUE TITLE
--label-columns option not working when getting ingress

### ISSUE THREAD

**Issue by dhawal55** [kubernetes/kubernetes#20291]
```kubectl get ingress -L app_name```

The above command always displays ```app_name``` column as empty even though ingresses have label ```app_name```. The command works for ```svc, rc, & pods``` so i guess this is just missing in the extensions package.

**Comment by AdoHe** [comment]
@dhawal55 This behavior is right according to code side, when you get ingress, kubectl will not print your `--label-columns` options as separate columns. Maybe this should be made consistent with other resource types.

**Comment by AdoHe** [comment]
@erictune can you confirm this?

**Comment by bgrant0607** [comment]
@AdoHe All resources should support --label-columns, yes.

**Comment by bgrant0607** [comment]
And --show-labels. :-)

**Comment by AdoHe** [comment]
@bgrant0607 Ok, I will add this today.

**Comment by AdoHe** [comment]
@bgrant0607 I add a quick fix to this #20409, would you mind reviewing this? Also I guess it's better to add test in `pkg/kubectl/cmd/cmd_test.go` though I add a test in `pkg/kubectl/resource_printer_test.go` now, I don't add the --show-labels flag here, actually this pr #19689 will add this.

**Comment by bgrant0607** [comment]
cc @bprashanth

**Comment by bprashanth** [comment]
@AdoHe thanks for the pr

**Comment by bgrant0607** [comment]
Done.
