### ISSUE TITLE
cluster/ubuntu should be generalized beyond flannel

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#20292]
The Doc for this suggests that it is not limited to Flannel, and I agree that this is essentially true.  The scripts should be generalized to actually support alternatives.  At least CNI plugins.

**Comment by MikeSpreitzer** [comment]
@banix

**Comment by dalanlan** [comment]
@MikeSpreitzer It could be way too late to ask, yet is CNI used to support overlay network which kubernetes requires or just cover the network of pods?

**Comment by MikeSpreitzer** [comment]
@dalanlan: I am not sure I understand the question, but will try to answer anyway.  You might be asking about how Kubernetes uses CNI in general, and you might be asking about the change in PR #21072.

Regarding Kubernetes and CNI in general: Kubernetes can be configured to use a CNI plugin to connect pods to (whatever network(s) the CNI plugin chooses).  This one bit of configuration does not change how Kubernetes does network-based health checking nor service load balancing.  It is the responsibility of the Kubernetes operator to use a complete configuration that works.  Kubernetes is modular regarding how service load balancing is done --- the kube-proxy provides two possible solutions, and the Kubernetes operator is free to use one of those or another solution.  Kubernetes does not yet offer any alternatives for how network-based health checks are done, but my team is working on that.

Regarding PR #21072: this change only generalizes the ubuntu cluster scripting so that it can install Kubernetes configured to use a CNI plugin.

**Comment by cmluciano** [comment]
Seems to be fixed with https://github.com/kubernetes/kubernetes/pull/21072 .
