### ISSUE TITLE
Move MinReadySeconds out of RollingUpdateDeployment 

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#20290]
Discussed here:
https://github.com/kubernetes/kubernetes/pull/20241#issuecomment-176395063

cc @janetkuo @kargakis @ironcladlou

**Comment by bgrant0607** [comment]
I think we should move MinReadySeconds to DeploymentSpec, since it is used to determine "availability" independent of the rollout strategy.

Needs to be applied to DaemonSet also (by moving it to DaemonSetSpec) @madhusudancs

**Comment by kargakis** [comment]
SGTM

**Comment by mqliang** [comment]
Is there anyone has working on this now? If not, I am glad to help.

**Comment by bgrant0607** [comment]
Fixed by #20389

**Comment by mqliang** [comment]
DaemonSet has not been addressed. @madhusudancs Could your plead send a PR to address this?
