### ISSUE TITLE
Shortening long api group names when typing into kubectl.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#20293]
# Problem

Need short way to type long resource type names.  Need to handle not only long Kind name (e.g. `replicationController`, but also the length of new API group names (e.g. `batch` which is proposed in #20120), and third-party resource types (e.g. `networkstartup.io/firewall`).
# TL;DR

We want user-defined short resource names &mdash; like `po` for `pods`, but user defined.
They go into a kubectl preferences file.  Until we have that feature, we will keep defining short names for our own types, as needed, once they graduate to v1 and out of extensions.
# Option 1: Matching

Allow user to type only the part of the type name after the slash.  For example, assuming `networkstartup.io/firewall` is an API group/kind, then you could type `kubectl get firewalls`.

In case of multiple matches,  there are two ways to resolve: a defined _sort order_ among api groups (suggested by lavalamp on #20120), or _error on multiple matches_.

Examples of a multiple matches are built-in `pod` vs `metrics.pod` (actual) and  `persistentVolumes` and `storagestartup.io/persistentVolume` (hypothetical).

This would extend the approach currently used by kubectl.  When you run `kubectl get jobs`, `kubectl` uses `RESTMapper.VersionAndKindForResource` to map the string `jobs` to  `(group: extensions/v1beta, kind:`Jobs`).  This approach is documented in [docs/proposals/api-group.md](docs/proposals/api-group.md).
# Option 2: Extensible Short Names

`kubectl` already maps `rc` to `replicationController`.  

We can keep hard-coding new mappings into kubectl for api groups that the project owns.
But, to support third-party resources, we need a way for others to add new short names.
# Comparison of 2 options

If we do _matching_, we may later want  _extensible short names_.  For example: `scheduledJob` is shorter than `jobs/scheduledJob`, but `sj` is even better.  But, if we do  _extensible short names_, do we really need  _matching_?

Extending `RESTMapper.VersionAndKindForResource` to include used-defined mappings exposes the user to reasoning about versions.  Also, that code is complex, and may not benefit from growing new responsibilities.

**Tenative Recommendation**: Implement _extensible short names_ for the third party use case with the mapping stored in a user preference file.

I'm not super confident in the recommendation because I don't understand `RESTMapper` well.
# Implementation of extensible short names

Mappings for project-owned resources can continue to be compiled in kubectl.

We will add a `.kube/preferences` file.  This will include a map from shortname to full type name.
Issue #1755 talks about storing prefs in a separate file from `.kube/config`.

The latter should take precedence.  That way, the core project can use new names without breaking user's third-party use cases.

Two third-parties might both want to use the same suffix (e.g. `faststorage.io/persistentVolume` and `cheapstorage.com/persistentVolume`).  K8s project should not be in the business of picking winners.  
Therefore, kubernetes project should not produce hard-coded aliases for third-party types.  This line may be a bit fuzzy.

Short-name mappings are separate from a more general user-defined aliases mechanism.  Issue #18023 talks about user-defined aliases.  It will presumably be like [git aliases](https://git.wiki.kernel.org/index.php/Aliases).  This is not a good choice because in order to map the short name `ba` to resource name `foo/bar`, you have to write several alias rules, e.g.:

```
# file: $HOME/.kube/preferences 
[alias]
        get ba = get foo/bar $*
        describe ba = describe foo/bar $*
        delete ba = delete foo/bar $*
        # ... and so on for all verbs
```

Therefore, we will need shortnames in addition to command aliases.

Scripts that use short names will not be portable.  This is okay.  There several `kubectl` command patterns that need to be avoided in portable scripts.  We will document these -- @bgrant0607 has a list of these rules somewhere.

With that said, expressing the short mappings as a user-defined preference makes it more clear to the user that a script is not portable to other users.   For example, you would not write a script that used your own git command aliases and expect it to work for another user.

**Comment by erictune** [comment]
@caesarxuchao @deads2k Definitely want your thoughts on this.

@kubernetes/goog-csi may be interested.

@bgrant0607 we talked about this.

**Comment by caesarxuchao** [comment]
cc @janetkuo

**Comment by lavalamp** [comment]
I came here to say we shouldn't allow these in scripts, but it looks like you already got that.

**Comment by caesarxuchao** [comment]
I think we should support both `Matching` and `Extensible short names`. And in kubectl , we should first expand the short name, and then do the matching, which is the current behavior of kubectl.

Regarding to the implementation, 
* Matching:
Our current implementation picks the first group that has a match: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta/restmapper.go#L560. We can modify that function to support either the *sort order* or the *error on multiple matches* behavior. 
I think thirdparty resources also builds a RESTMapper, not sure if that RESTMapper is added to the MultiRESTMapper. If so, thirdparty groups will be automatically taken into consideration. I think @deads2k knows the best.

* Extensible short name support:
We could build this [map](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/kubectl.go#L104) from .kube/preferences.
And I believe the current code would support expanding a short name to "group/resource", e.g., expanding "pv" to "faststorage.io/persistentVolume".

**Comment by bgrant0607** [comment]
Ref #10693

**Comment by bgrant0607** [comment]
We could potentially put official short names into the API discovery info.

That wouldn't address the issue of ambiguity among multiple API groups, though.

**Comment by soltysh** [comment]
This might relate #20265

**Comment by deads2k** [comment]
A few comments:
 1. I'm not sold on using `/`s as delimiters between group and resource.  We tried that briefly, but it led to some sticky code when trying to disambiguate `group/resource` and `resource/name`.  I liked @smarterclayton's suggestion of doing `resource.group/name`.

 1. Currently, we have the "matching" behavior with an error on ambiguous resources.  The `RESTMapper` has that behavior today and provides an API that returns all potential matches, so much of the plumbing is available.  I would like to see it extended to handle resolution based on a preferred order, but I don't think I want a default order.  A config file that describes a preferred ordering of groups is pretty simple to do, easy to understand, and easy for us prime.

 1. I also want extensible short names, but I don't want to it to the exclusion of matching.  Implementation-wise, extensible short names are a pretty straight-forward layer on top of an existing `RESTMapper`.  It could intercept and mutate the request from known-short-name->qualified-group-version and pass it along.  I don't think that I like extensible short names as a single solution since it cannot be primed and to be as successful would require a full enumeration of all resources.

 1. When describing the config file, why wouldn't we keep using yaml like we do for other serializations and simply have
```yaml
resourceAliases:
  persistentvolumes: "persistentvolumes.storagestartup.io"
```

@kubernetes/rh-ux

**Comment by lavalamp** [comment]
Do we really want everyone's set of shortcuts to be a special snowflake?
Like, I'm sure anyone else's vim config would be unusable for me. It also
annoys me that git has nonsensical command names unless you add a bunch of
aliases. Do we want kubectl to be similarly user-specific?

As an alternative, suppose we:

* Add a canonical short name, like Brian says
* Add a canonical group search order (Explicitly defined for groups that
are compiled in to kubectl, then other groups alphabetically)

I feel like this would be less work, still easy to use, easy to understand
what the system will do, portable across users, and not introduce
mysterious config files.

**Comment by smarterclayton** [comment]
Problem with any canonical order is that it is not backwards compatible
unless older entries are always first - i.e. alphabetic canonical search
order breaks as soon as you add a new A group to the list.

I don't really want to have extensible short names - I think bash is fine
for that if you really need the power.  We do need a registry of shortcuts,
names, and canonical names IANA style to prevent people from picking short
names they shouldn't have.

**Comment by lavalamp** [comment]
I'm operating under the assumption that we force users to spell it out in
scripts-- I think we have to do that no matter what we do. This means
backwards compatibility is not a problem.

**Comment by erictune** [comment]
we should add short names for objects in github.com/kubernetes/kubernetes.
we can't add them for third-party resources though.

**Comment by smarterclayton** [comment]
Changing the group that someone working on the cli gets when they type
"hpa" can be just as bad.  I'd prefer humans get stable ordering and
stable expectations when using defaults as much as possible - that
reduces wear and tear on stackoverflow, our docs, and increases admin
confidence.  Human back compat is an important measure of usability -
"what I did yesterday will be what I do tomorrow".

**Comment by erictune** [comment]
What clayton said makes sense for groups that chose to register their place in the sort order in an official  file.  But we cannot require all resources to do that.

**Comment by smarterclayton** [comment]
That's fair - but the discovery endpoint will be under our control so we
should work to ensure it is predictable.

**Comment by nikhiljindal** [comment]
I agree that we can do both - matching and extensible short names (I see value in both)

I also wanted to point out that we want this to work for federated api server resources as well.
As long as we use continue to use RESTMapper for matching as @caesarxuchao mentioned, we should be fine I think.

Also https://github.com/kubernetes/kubernetes/pull/14383 is adding a --preferred-version flag that users can use to change the groupVersion sorting order used for matching.

**Comment by spiffxp** [comment]
/sig cli
because kubectl
/sig api-machinery
because discovery

**Comment by deads2k** [comment]
Shortnames are extensible and group names match on prefix.
