### ISSUE TITLE
e2e failure: kube-up should retry on gcloud failure

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20306]
From https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/19970/kubernetes-pull-build-test-e2e-gce/25600/build-log.txt
```
17:27:08 - 0.0.0.0/0
17:27:08 targetTags:
17:27:08 - e2e-gce-builder-1-0-minion
17:27:26 ERROR: (gcloud.compute.firewall-rules.describe) Could not fetch resource:
17:27:26  - Backend Error
17:27:26  
```
Cluster came up but we failed to describe firewalls. Unable to find a bug, though I'm sure people (and I) have seen this before. Maybe just reuse the functions added https://github.com/kubernetes/kubernetes/pull/20158 ?

**Comment by lavalamp** [comment]
That's annoying. Why doesn't gcloud internally retry on 5xx errors after a delay?

We could use the --log-http flag to get the RPCs printed over stderr, if that would help debugging.

**Comment by davidopp** [comment]
@brendandburns is #20432 sufficient here and we should close until we see a recurrence, or should we leave this issue open?

**Comment by davidopp** [comment]
Filed, #20576, closing this one as fixed by #20432.

**Comment by pwittrock** [comment]
Not sure if this is the same or a different issue.
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26732/console

>
08:31:42 e2e-gce-builder-2-0-master-pd us-central1-f 20      pd-ssd READY
08:31:46 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
08:31:46  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
08:31:46  
08:31:46 Attempt 1 failed to create static ip e2e-gce-builder-2-0-master-ip. Retrying.
08:31:51 Created [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-builder-2-0-master-https].
08:31:51 NAME                             NETWORK             SRC_RANGES RULES   SRC_TAGS TARGET_TAGS
08:31:51 e2e-gce-builder-2-0-master-https e2e-gce-builder-2-0 0.0.0.0/0  tcp:443          e2e-gce-builder-2-0-master
08:31:56 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
08:31:56  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
08:31:56  
08:31:56 Attempt 2 failed to create static ip e2e-gce-builder-2-0-master-ip. Retrying.
08:32:10 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
08:32:10  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
08:32:10  
08:32:10 Attempt 3 failed to create static ip e2e-gce-builder-2-0-master-ip. Retrying.
08:32:29 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
08:32:29  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
08:32:29  
08:32:29 Attempt 4 failed to create static ip e2e-gce-builder-2-0-master-ip. Retrying.
08:32:54 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
08:32:54  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
08:32:54  
08:32:54 Attempt 5 failed to create static ip e2e-gce-builder-2-0-master-ip. Retrying.
08:33:23 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
08:33:23  - Quota 'STATIC_ADDRESSES' exceeded.  Limit: 25.0
08:33:23  
08:33:23 Failed to create static ip e2e-gce-builder-2-0-master-ip 
08:33:23 2016/02/04 16:33:23 e2e.go:309: Error running up: exit status 2

**Comment by brendandburns** [comment]
This is a different issue.  This is due to us leaking addresses somewhere.  This error should be a failure.  Re-closing.
