### ISSUE TITLE
Where could i get "/etc/kubernetes/manifests"

### ISSUE THREAD

**Issue by leewill1120** [kubernetes/kubernetes#20311]
I could not connect to gcr.io/google_containers/hyperkube, So I tried to build a hyperkube image locally, but i don't have the file "/etc/kubernetes/manifests". Where could i get it? 
P.S. line 155 @ https://github.com/kubernetes/kubernetes/blob/v1.1.4/docs/getting-started-guides/docker-multinode/master.sh

**Comment by thockin** [comment]
That is a directory into which you can write pod yaml or json files to run.
