### ISSUE TITLE
Retries too aggressive on AWS

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#20316]
It seems Kubernetes retries AWS API calls very aggressively. Any time ELB creations fails (admittedly due to configuration errors on my part), Kubernetes retries the calls and soon we are over our API rate limit. It's very disruptive to my coworkers who share the same account.

**Comment by bprashanth** [comment]
Don't think this is going to make 1.2.0, we can still target soem 1.2.X release

**Comment by SpencerBrown** [comment]
This needs to be top priority. It is killing us on AWS with a relatively small cluster (10 nodes).

**Comment by justinsb** [comment]
For the generic case, I think this is a dup of #12121. 

For the specific case of LoadBalancers retries, we are looking at it in in #21630.

@guoshimin is it OK to close as split into those two issues?

**Comment by guoshimin** [comment]
Yeah sgtm. Thanks!

**Comment by justinsb** [comment]
Thanks - closed in favor of those two issues.
