### ISSUE TITLE
Controller should not retry authorizing security group when duplicate rule already exists

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#20314]
Getting messages like the following repeatedly in the log:
```
W0129 04:35:07.724460       1 aws.go:1489] Error authorizing security group ingressInvalidPermission.Duplicate: the specified rule "peer: sg-fd3fc79a, ALL, ALLOW" already exists
```

It seems the controller should just be satisfied that the rule already exists and move on.

**Comment by therc** [comment]
This is pretty bad. It generates a lot of garbage in CloudTrail.

**Comment by therc** [comment]
This is weird. There are checks in ensureSecurityGroupIngress not to add ingress permissions that are already there: https://github.com/kubernetes/kubernetes/blob/5a6cf15c09e18597e3ab32585d0e1f1abb53ee33/pkg/cloudprovider/providers/aws/aws.go#L1500

cc: @justinsb

**Comment by therc** [comment]
For the record, I'm getting this:

```
    "errorCode": "Client.InvalidPermission.Duplicate",
    "errorMessage": "the specified rule \"peer: sg-KUBE-ELB, ALL, ALLOW\" already exists",
    "requestParameters": {
        "groupId": "sg-DEFAULT",
        "ipPermissions": {
            "items": [
                {
                    "ipProtocol": "-1",
                    "groups": {
                        "items": [
                            {
                                "groupId": "sg-KUBE-ELB"
                            }
                        ]
                    },
                    "ipRanges": {},
                    "prefixListIds": {}
                }
            ]
        }
    },
```

**Comment by therc** [comment]
I think this might be a duplicate of  #19619 and fixed by #20153

**Comment by therc** [comment]
Now that #20153 is in, is your problem fixed? Is your VPC already using existing security groups?

**Comment by guoshimin** [comment]
It's not that easy to reproduce the condition that triggered the issue last time. Closing for now. Will reopen if it happens again.
