### ISSUE TITLE
"Horizontal pod autoscaling" e2e's are flaky in parallel

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20338]
@piosz and I talked yesterday and he said that the HPA tests should run in parallel no problem, but they are flaking.

I'm going to move these into `[Serial]` for now.

E.g. https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/1624

**Comment by davidopp** [comment]
Can we remove the "flake" label if we're sure they won't flake in serial? (So we don't have to talk about this issue every morning.) I don't think we should close the issue, but we could move it to P1. Ike, what do you think?

**Comment by ihmccreery** [comment]
@piosz Told me he had no reason to think these tests wouldn't run in parallel, so as far as I'm concerned this is a flaky-in-parallel situation.  Once we have good reason that these shouldn't work in parallel, we ca knock it off.  What do you think?

**Comment by davidopp** [comment]
I feel like it's OK to move it out of the we-discuss-it-every-morning bucket if we have a way of running the test that doesn't flake. I do agree with leaving as a P1 to figure out why it flakes in parallel. 

Anyway, let's give @piosz a day to look into this, and if he can't figure out why it is flaking in parallel in one day, he should continue working on that as a top priority, but at that point let's remove the flake label so we don't have to talk about it every day.

Does that sound reasonable?

**Comment by ihmccreery** [comment]
SGTM!

**Comment by ihmccreery** [comment]
These tests actually just seem to be not working on GKE: see http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-serial/.

**Comment by piosz** [comment]
The reason here is lack of resources. There are 4 HPA tests, each of them runs up to 5 pods with cpu request specified to 500m. So in the worst case we need here 4*5*500m = 10 CPU. Reassigning to @ihmccreery for the decision whether we want to add an extra resources to parallel suite or drop an idea to run those tests there.

The confirmation from logs:
```
Jan 29 10:17:27.052: INFO: event for deployment-ie7wx-xmgrp: {default-scheduler } FailedScheduling: pod (deployment-ie7wx-xmgrp) failed to fit in any node
fit failure on node (e2e-slow-minion-65zw): CPU
fit failure on node (e2e-slow-minion-t4zv): CPU
fit failure on node (e2e-slow-minion-49qd): CPU
```

**Comment by ihmccreery** [comment]
Closing this (#21924 seems to have helped).
