### ISSUE TITLE
SafeFormatAndMount default fstype should be in defaults.go

### ISSUE THREAD

**Issue by swagiaal** [kubernetes/kubernetes#20332]
SafeFormatAndMount uses ext4 as the default fstype but this value is set inside SafeFormatAndMount instead of defaults.go.

**Comment by swagiaal** [comment]
please assign to me

**Comment by bgrant0607** [comment]
Sorry I wasn't clear in #19921. We can't do this in the v1 API. It's a non-backward-compatible API change.

ref #8190 for tracking

cc @kubernetes/goog-cluster @kubernetes/rh-storage

**Comment by jsafrane** [comment]
@bgrant0607 says it would break backward compatibility

/close
