### ISSUE TITLE
POST in HTTP log should show chosen name

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#20343]
When someone POSTs and that POST results in a resource being created, the HTTP log (`/var/log/kube-apiserver.log`) should show the name and namespace of the resource that was created.

Currently, it does not.  

This makes debugging from kube-apiserver logs difficult.  It makes them less useful as an audit log.
This will probably involve some messy plumbing in the apiserver code.  However, when we have a formal audit logging feature, we will need the same plumbing.

For example, consider this log snippet which is based on a real log

```
I0129 19:49:18.981787       5 handlers.go:131] POST /api/v1/namespaces/default/pods: (15.239636ms) 201 [[kube-controller-manager/v1.1.4 (linux/amd64) kubernetes/a5949fe] 127.0.0.1:44735]
I0129 19:49:18.981853       5 handlers.go:131] POST /api/v1/namespaces/default/pods: (16.243425ms) 201 [[kube-controller-manager/v1.1.4 (linux/amd64) kubernetes/a5949fe] 127.0.0.1:44732]
I0129 19:49:18.982245       5 handlers.go:131] POST /api/v1/namespaces/default/pods: (12.872161ms) 201 [[kube-controller-manager/v1.1.4 (linux/amd64) kubernetes/a5949fe] 127.0.0.1:44736]
I0129 19:49:18.982255       5 handlers.go:131] POST /api/v1/namespaces/default/pods: (10.890707ms) 201 [[kube-controller-manager/v1.1.4 (linux/amd64) kubernetes/a5949fe] 127.0.0.1:44737]
....
I0129 19:49:21.489616       5 handlers.go:131] DELETE /api/v1/namespaces/default/pods/pod-cuwdd (16.891471ms) 200 [[kube-controller-manager/v1.1.4 (linux/amd64) kubernetes/a5949fe] 
```

If I am interested in `pod-cuwdd` and want to see its history, I need to do `grep pod-cuwdd /var/log/kube-apiserver.log`.  But, that will not show who created it or when.  The POST lines do not have the resource name.

And, if I inspect the log, I may see many POSTs in the time preceeding the DELETE.

**Comment by liggitt** [comment]
audit feature supports including contents of requests - https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy
