### ISSUE TITLE
JsonPath nested condition and multiple conditions are not working

### ISSUE THREAD

**Issue by dhawal55** [kubernetes/kubernetes#20352]
I want to get the list of all pods that are ready to take requests. In order to do that I run the following queries:

`kubectl get pods -l app=my-app -o jsonpath='{.items[?(@.status.conditions[?(@.type == "Ready")].status == "True")].status.phase}'`

OR

`kubectl get pods -l app=my-app -o jsonpath='{.items[?(@.status.conditions[*].type == "Ready" && @.status.conditions[*].status == "True")].status.phase}'`

Neither of them works. Jsonpath doesn't support nested filters or multiple filters.

**Comment by 5tefan** [comment]
Ran into this as well: was trying to get a list of node addresses which have eg. Unknown status:

```
kubectl get nodes -o jsonpath='{.items[?(@.status.conditions[?(@.type=="Ready")].status=="Unknown")].status.addresses[?(@.type=="InternalIP")].address}'
```

**Comment by dhawal55** [comment]
Cannot use multiple filters:
```kubectl get pods --all-namespaces -o jsonpath='{.items[*].spec.containers[?(@.securityContext && @.securityContext.privileged==true)].name```
Erorr:
```error: error parsing jsonpath {.items[*].spec.containers[?(@.securityContext && @.securityContext.privileged==true)].securityContext.privileged}, unrecognized character in action: U+0026 '&'```

**Comment by seh** [comment]
As it stands, `jsonpath.Parser.parseFilter` only [parses a single top-level binary expression](https://github.com/kubernetes/kubernetes/blob/b48deebc7a67f86c091f6e03437d73f5327689b7/pkg/util/jsonpath/parser.go#L322-L360).

**Comment by spiffxp** [comment]
/sig cli
/sig api-machinery
kubectl seems to be the main entrypoint for jsonpath, but client-go seems to be where it's implemented

**Comment by kvaps** [comment]
/reopen
Issue still there

**Comment by marcellodesales** [comment]
And still is :( 

```$ kubectl get ingress -l app=config-service -o jsonpath="{..paths[?(@.backend[?(@.serviceName=='config-service-default')])]}"
error: error parsing jsonpath {..paths[?(@.backend[?(@.serviceName=='config-service-default')])]}, unterminated filter```

**Comment by spiffxp** [comment]
/assign
assigning to be able to reopen, I don't have the bandwidth to address, but I'll open it up if it's still happening
/remove-lifecycle rotten
/reopen

**Comment by rvesse** [comment]
/remove-lifecycle stale

This is still an issue in latest releases

**Comment by mariantalla** [comment]
👋 Is this being worked on anywhere? If not I could take a look.

**Comment by karthikeayan** [comment]
Me too facing this.

**Comment by PierreBeucher** [comment]
Same issue here with expression:
```
kubectl -n jinko-dev-pierre get pods -o jsonpath="{range .items[*]}{.status.conditions[?(@.type == 'Ready' && @.status == 'True')]}{' '}{.metadata.name}{'\n'}{end}"
```

**Comment by mariantalla** [comment]
Working to get the first part of the implementation merged over at #79227

**Comment by lavalamp** [comment]
I care slightly less if this is strictly a kubectl change, but for requests made against the API, we don't allow non-standard features for JSONPath, JSONPointer, JSONPatch, JSON Merge Patch, etc, due to issues around version change, and client interoperability expectations.

 I think this is the most authoritative spec? https://goessner.net/articles/JsonPath/

It doesn't mention any logical operators. If there is a different spec that does, please link it?

**Comment by liggitt** [comment]
> we don't allow non-standard features for JSONPath, JSONPointer, JSONPatch, JSON Merge Patch, etc, due to issues around version change, and client interoperability expectations.

I agree with this. Please reopen with details of an authoritative spec outlining logical jsonpath operators if there is one.

/close

**Comment by angelofdeauth** [comment]
> I care slightly less if this is strictly a kubectl change, but for requests made against the API, we don't allow non-standard features for JSONPath, JSONPointer, JSONPatch, JSON Merge Patch, etc, due to issues around version change, and client interoperability expectations.
> 
> I think this is the most authoritative spec? https://goessner.net/articles/JsonPath/
> 
> It doesn't mention any logical operators. If there is a different spec that does, please link it?

> > we don't allow non-standard features for JSONPath, JSONPointer, JSONPatch, JSON Merge Patch, etc, due to issues around version change, and client interoperability expectations.
> 
> I agree with this. Please reopen with details of an authoritative spec outlining logical jsonpath operators if there is one.
> 
> /close

That article/series is dated as 2007.
I found something a little more relevant: [https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html#filters](https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html#filters)

Though I have to say, I think logical filter grouping with parentheses would be more useful than their inline scripting implementation (e.g. `item[?( (@.var=="this" && @.othervar=="that) || @.some.othervar==true)`).

Regardless, multiple conditioned queries would be a very useful feature, and expanding multiple conditions into conditional groups would only enhance this into a better UX.

**Comment by lavalamp** [comment]
> I found something a little more relevant: https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html#filters

That's not a neutral, authoritative standard. I'd want something like: https://tools.ietf.org/html/rfc6901

Also, use `jq` :)

**Comment by dijitali** [comment]
Looks like there's one in the process of being drafted:
https://tools.ietf.org/html/draft-goessner-dispatch-jsonpath-00

**Comment by thoraage** [comment]
Seems a new draft was release three days ago: https://datatracker.ietf.org/wg/jsonpath/documents/

**Comment by elmazzun** [comment]
I wanted to get all those Roles and ClusterRoles that handles "servicemonitor" resources, I came up with something like

`oc get clusterrole -o jsonpath='{range .items[?(@.rules[*].resources[*]=="servicemonitors")]}{.metadata.name}{"\n"}{end}'`

but I always get no results
