### ISSUE TITLE
Kubelet should not need to restart docker to configure cbr0

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#20355]
This is trivial using docker 1.9 network with the bridge driver but I'm not sure if that's how we are going to do it. This will allow us to run kubelet and flannel in a daemonset. What's the plan? How much work is this?

```console
$ ip addr
...
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:4e:96:85:32 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:4eff:fe96:8532/64 scope link 
       valid_lft forever preferred_lft forever
$ docker network create --driver=bridge --subnet=172.19.0.0/16 pod
b362aa82ba886fdb2f17b873aef4c7d20de223fb1eb114e1b1e3d00ad7becf32
$ docker run -d --net=pod busybox sleep 10000
52b67481b187a220ed1d3a6db57db214cc342332b7904f311c5828260f85e665
$ ip addr
...
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:4e:96:85:32 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:4eff:fe96:8532/64 scope link 
       valid_lft forever preferred_lft forever
146: br-b362aa82ba88: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:1a:c9:7a:7a brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 scope global br-b362aa82ba88
       valid_lft forever preferred_lft forever
    inet6 fe80::42:1aff:fec9:7a7a/64 scope link 
       valid_lft forever preferred_lft forever
148: vethf4c7369: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-b362aa82ba88 state UP group default 
    link/ether 3e:5d:12:36:ae:9e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::3c5d:12ff:fe36:ae9e/64 scope link 
       valid_lft forever preferred_lft forever
```
@dchen1107 @bprashanth @kubernetes/goog-cluster

**Comment by bprashanth** [comment]
We won't be using docker's bridge driver (or their plugin model). The pause container will get created with net=none and we'll be using CNI plugins instead. Waiting on: https://github.com/kubernetes/kubernetes/pull/18795.

**Comment by mikedanese** [comment]
will it still require restarting docker?

**Comment by bprashanth** [comment]
No containers will get created on this bridge https://github.com/kubernetes/kubernetes/pull/18795/files#diff-4df925f5ace9ef618b2650b1d3f740c1R119

**Comment by dchen1107** [comment]
Yes, this is what CNI stuff we talked about during the lunch, but I didn't realize a pending pr  #18795 is going to be merged soon. :-) Cool!

**Comment by bprashanth** [comment]
configure-cbr0 will still be the default for now. The plan is to move all the networking code out of the kubelet (hairpin, bw-shaping etc) and into a Kubernetes CNI plugin, while ensuring the stability of the existing bridge plugin, before going all in.

**Comment by mikedanese** [comment]
Is this fixed now that #18795 is merged or does this require a little more work?

**Comment by bprashanth** [comment]
I don't think @dcbw ran e2e on > 1 platform with network-providre=kubenet, configure-cbr0 will probably stick around as default till post 1.2.

**Comment by dcbw** [comment]
Yeah, I wouldn't rip out configure-cbr0 yet.  The kubenet plugin doesn't have shaper support or flannel-experimental-overlay support quite yet.

(the hairpin stuff will work regardless since that's in docker manager code, not in plugins)

**Comment by thockin** [comment]
also I guess kubenet will not work for hostports and maybe /etc/resolv.conf
and /etc/hosts?

**Comment by bprashanth** [comment]
CNI has dns options: https://github.com/appc/cni/blob/master/SPEC.md#parameters, so we'd just grab it from our run container options: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1352, I think. The docker proxy might be a little harder to get rid of.

**Comment by thockin** [comment]
We can set up iptables port-forwards the same way docker does for hostports
(we don't use it because the flag that governs it is toooooo coarse grained)

**Comment by dcbw** [comment]
@thockin I wonder if we shouldn't try to push hostport/--expose/shaping stuff down to cni plugins on the same level as IPAM, with the corresponding CNI spec JSON additions.

**Comment by mikedanese** [comment]
I'd like it to be possible to run both network daemons (.e.g. flannel daemon) and kubelet in a daemonset. Opencontrail/flannel/calico integration shouldn't need to require modification to salt. I want them to be shipped like other cluster addons.

**Comment by mikedanese** [comment]
@freehan How much work do you think is left to do get this (including receiving a cidr assignment from nodespec)?

**Comment by freehan** [comment]
I am working on enabling `kubenet` as default network plugin, which avoids restarting docker. 

But first, I have to make `kubenet` production ready. Please refer to #24211

**Comment by dchen1107** [comment]
cc/ @jlowdermilk

**Comment by mikedanese** [comment]
kubenet is enabled by default now.
