### ISSUE TITLE
KUBE_BUILD_PLATFORMS is not respected

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20365]
hack/build-cross sets it without looking at the current value.  And the value has to be an array, which is a bit awkward to use.

**Comment by luxas** [comment]
This could be improved indeed. Maybe something like
```
KUBE_BUILD_PLATFORMS="linux/amd64 linux/arm64" hack/build-cross.sh
```
and 
```bash
SPECIFIED_KUBE_BUILD_PLATFORMS=(${KUBE_BUILD_PLATFORMS})

KUBE_BUILD_PLATFORMS=${SPECIFIED_KUBE_BUILD_PLATFORMS:-("${KUBE_SERVER_PLATFORMS[@]}")}
kube::golang::build_binaries "${KUBE_SERVER_TARGETS[@]}"

KUBE_BUILD_PLATFORMS=${SPECIFIED_KUBE_BUILD_PLATFORMS:-("${KUBE_CLIENT_PLATFORMS[@]}")}
kube::golang::build_binaries "${KUBE_CLIENT_TARGETS[@]}"
```
Haven't tested it though...
But why would one want to change the value?

**Comment by thockin** [comment]
I just wanted to build one, so I did the "obvious" thing:

`KUBE_BUILD_PLATFORMS="linux/amd64`  hack/dev-build-and-up.sh`

It failed for multiple reasons :)

**Comment by krancour** [comment]
This issue has been a major downer for me. It's much harder right now than it ought to be to articulate the few platforms for which you'd like to build each of server binaries, client binaries, test binaries, etc.

Every time I've tried to do this "the right way," I've spent hours looking at scripts and feeling frustrated that build options aren't documented better. Every time, I end up cutting my losses and resorting to temporary build script hacks instead, just to get the job done.

**Comment by fearphage** [comment]
Doesn't fix this issue exactly, but I've found that you can easily build only `linux/amd64` if you set `KUBE_FASTBUILD=true`.

https://github.com/kubernetes/kubernetes/blob/bd3c11df8abb1554b24287821edfec76108b9d91/hack/lib/golang.sh#L42-L57

**Comment by cmluciano** [comment]
Taking a look at this today, I also thought that setting ```KUBE_BUILD_PLATFORMS=``` seems to be the most reasonable.
