### ISSUE TITLE
Be more conservative with the `[Flaky]` label

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20363]
The `[Flaky]` label is just causing us to leave tests unattended:

- https://github.com/kubernetes/kubernetes/issues/17873#issuecomment-177035197
- https://github.com/kubernetes/kubernetes/issues/6541#issuecomment-177035310
- https://github.com/kubernetes/kubernetes/issues/18952#issuecomment-177035567
- https://github.com/kubernetes/kubernetes/issues/17829#issuecomment-177035881
- https://github.com/kubernetes/kubernetes/issues/19023#issuecomment-177035897
- https://github.com/kubernetes/kubernetes/issues/17518#issuecomment-177035960
- https://github.com/kubernetes/kubernetes/issues/20362

I propose we stop using the `[Flaky]` label, and instead deal with flaky tests by either fixing asap them or moving them into `[Feature:.+]` suites as necessary.  (This has the added benefit that we don't have to worry about the `-flaky` jobs which are currently just dumping grounds for tests people don't want to care about.)

cc @kubernetes/sig-testing @kubernetes/goog-testing

**Comment by ixdy** [comment]
using `[Feature:.+]` seems like it's only going to be worse. folks will relabel tests, and then they'll never run anywhere, ever again...

**Comment by ihmccreery** [comment]
@ixdy Agreed, but we can also monitor (how?) what `[Feature:.+]`s exist.

**Comment by lavalamp** [comment]
We should reopen all of those issues until the tests have been moved back.

**Comment by ihmccreery** [comment]
@lavalamp already done.

**Comment by lavalamp** [comment]
I think this is just a case of some combination of people writing "fix #blah" in a PR and that auto-closing, and people not being aware of the policy.

**Comment by ihmccreery** [comment]
I've sent out #20453 to resolve this, basically reserving the `[Flaky]` label to long-running flaky tests that we don't have a short-term solution for.  Happy to hear other ideas.
