### ISSUE TITLE
The default build should only compile for amd64

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20367]
99% of people do not want or need arm builds.  It should not be part of the default build.  As it is, I can't even figure out how to turn it off.

**Comment by luxas** [comment]
Which build do you mean? `make`, `make release`, `hack/build-go.sh`, `hack/build-cross.sh`?
`make` and `hack/build-go.sh` only builds for the host platform.
`hack/build-cross.sh` builds for all cross-platforms (soon four: #19769), well that's the purpose of the script
`make release` runs `hack/build-cross.sh`.
So I wouldn't say there's something strange here. CI builds have to build for all supported platforms to ensure nothing breaks.

But maybe you want something like `make super-fast-release` (not with that name of course) that both skips the tests and cross-compiling, but I can't see any advantage of that command.

Not sure what you want here...

**Comment by ixdy** [comment]
cc @david-mcmahon

**Comment by thockin** [comment]
I mean ./hack/dev-build-and-{push,up}.sh

I was trying to bring up an e2e cluster and my poor laptop was groaning
under the doubled workload.  I think our whole build is in need of a
reboot, and when we do, every build should be for one arch unless
explicitly requested otherwise.

**Comment by luxas** [comment]
`make release` should run `hack/build-cross.sh`
`hack/dev-build-and-{push,up}.sh` should not.
Maybe just rewrite the `hack/dev-build` files to do only what's needed for `kube-up` instead of making a full release?

**Comment by david-mcmahon** [comment]
Have not delved into Makefiles at all yet, but yes, at its most basic,  'make' should do sane things for developers and 'make release' for release.  If it is otherwise, what is the issue with just changing (and announcing) it?

**Comment by thockin** [comment]
It's plumbed through 8 layers of shell.  Hardcoded, defaulted, ignored, and
replaced.

**Comment by david-mcmahon** [comment]
So 2 issues here:
1. Complex layering of build rules
2. Sane defaults for dev and release

This seems related to [#19769](https://github.com/kubernetes/kubernetes/pull/19769/files).

I'll have a better look when I get a chance.

**Comment by thockin** [comment]
I'd love to brain dump my hopes and dreams on you some time :)

**Comment by mml** [comment]
Here is how I do this right now.  I keep this git stash around and apply it when it's time to do some heavy building.  We can and should do much better, but maybe this will enable someone else's velocity in the meantime.

```diff
% git stash show -u
diff --git a/hack/lib/golang.sh b/hack/lib/golang.sh
index 2166540..5a82bdb 100755
--- a/hack/lib/golang.sh
+++ b/hack/lib/golang.sh
@@ -50,7 +50,7 @@ readonly KUBE_SERVER_BINARIES=("${KUBE_SERVER_TARGETS[@]##*/}")
 # The server platform we are building on.
 readonly KUBE_SERVER_PLATFORMS=(
   linux/amd64
-  linux/arm
+  #linux/arm
 )
 
 # The set of client targets that we are building for all platforms
@@ -64,12 +64,12 @@ readonly KUBE_CLIENT_BINARIES_WIN=("${KUBE_CLIENT_BINARIES[@]/%/.exe}")
 # in 'build/build-image/cross/Dockerfile'. However, it's only a bit faster since go 1.5, not mandatory 
 readonly KUBE_CLIENT_PLATFORMS=(
   linux/amd64
-  linux/386
-  linux/arm
-  darwin/amd64
-  darwin/386
-  windows/amd64
-  windows/386
+  #linux/386
+  #linux/arm
+  #darwin/amd64
+  #darwin/386
+  #windows/amd64
+  #windows/386
 )
 
 # The set of test targets that we are building for all platforms
@@ -112,9 +112,9 @@ readonly KUBE_TEST_PORTABLE=(
 # Which platforms we should compile test targets for. Not all client platforms need these tests
 readonly KUBE_TEST_PLATFORMS=(
   linux/amd64
-  darwin/amd64
-  windows/amd64
-  linux/arm
+  #darwin/amd64
+  #windows/amd64
+  #linux/arm
 )
 
 # Gigabytes desired for parallel platform builds. 11 is fairly
```

**Comment by spiffxp** [comment]
/sig release
The linked KUBE_BUILD_PLATFORMS PR probably obviates this once merged

**Comment by YannickFricke** [comment]
Still no merge 👎

**Comment by thockin** [comment]
No merge of what?

**Comment by dims** [comment]
@YannickFricke - Just use `KUBE_BUILD_PLATFORMS="linux/amd64 linux/arm64" hack/build-cross.sh` as implemented in #46862

**Comment by luxas** [comment]
I think we should close this (and should have long ago)
The default build is the "fastbuild" which is only for amd64 or host platform.
If you do `make release`, then it indeeds builds everything, as should be

**Comment by spiffxp** [comment]
/close
I think the linked PR takes care of this, please /reopen if I'm mistaken

**Comment by jamesandrews-iopp** [comment]
`KUBE_FASTBUILD='true' make release`

This seems to do what the OP was asking
