### ISSUE TITLE
Opportunistic scaling in Deployment

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#20361]
As discussed here:
https://github.com/kubernetes/kubernetes/issues/16737#issuecomment-175242784
and here:
https://github.com/kubernetes/kubernetes/pull/19343#issuecomment-175307057

We should consider favoring scaling down RCs with not-ready pods (including pending, crashing, etc.).

cc @janetkuo @kargakis

**Comment by kargakis** [comment]
https://github.com/kubernetes/kubernetes/pull/20368

**Comment by bgrant0607** [comment]
Fixed by #20368 and subsequent PRs
