### ISSUE TITLE
GCE node MIA

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20375]
I had a node that was NotReady because kubelet stopped sending updates (don't know why).  I could not SSH into the node either (it just hung).  Nothing in Kubernetes or container VM tried to rectify that situation.

@dchen1107 @mml @alex-mohr @roberthbailey

**Comment by bprashanth** [comment]
If you still have it, can you get /var/log after a gce-reset on the node? startup.log would be more helpful but I think that's rewritten on instance reset.

**Comment by thockin** [comment]
Yeah, it's gone.  I didn't think to look at console before I hit reset.

**Comment by bprashanth** [comment]
I think we should spin up clusters with "Don't delete boot disk with vm", preserve the disk of all vms that failed to come up, and mount it on another vm to poke around for every e2e cluster. Probably the same thing hitting us at https://github.com/kubernetes/kubernetes/issues/18969

**Comment by roberthbailey** [comment]
Was the node up and then went out to lunch of did it fail to ever start in the first place?

**Comment by thockin** [comment]
Unclear - it was part of an e2e cluster, so I didn't verify that it was
ever up.
