### ISSUE TITLE
Deployment freezes at 0 and no RC created

### ISSUE THREAD

**Issue by michael-golfi** [kubernetes/kubernetes#20381]
Hi,

I'm having an issue with deployments. When I run through the deployment example I get a hanging deployment. 

The yaml file is the same as the example, except I was trying to experiment with updating pod versions.

    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      replicas: 3
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.7.9
            ports:
            - containerPort: 80

I try to investigate further using describe. I have the apiserver log level set to 5. I get the following:

    $ sudo kubectl get deployments
    NAME               UPDATEDREPLICAS   AGE
    nginx-deployment   0/3               34m

    $ sudo kubectl describe deployments
    Name:                           nginx-deployment
    Namespace:                      default
    CreationTimestamp:              Sat, 30 Jan 2016 06:03:47 +0000
    Labels:                         app=nginx
    Selector:                       app=nginx
    Replicas:                       0 updated / 3 total
    StrategyType:                   RollingUpdate
    RollingUpdateStrategy:          1 max unavailable, 1 max surge, 0 min ready    seconds
    OldReplicationControllers:      nginx (2/2 replicas created)
    NewReplicationController:       <none>
    No events.

When I check the events from kubernetes I see no events which belong to this deployment. 

The versions are as followed:

    Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}
    Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}

I already posted on StackOverflow, but in the event that this is a bug I thought I should post here as well. Has anybody experienced this? 

I checked out issue #19757, seems similar. But I enabled deployments with the apiserver, it seemed to be working but it just hangs and doesn't give me any noticeable output... I tried what #19757 did, I deleted the kubectl cache and I have the logging level at 5 but I don't see anything obvious at this point.

**Comment by a-robinson** [comment]
@nikhiljindal

**Comment by nikhiljindal** [comment]
yes apiserver seems fine.
The controller doesnt seem to be creating the new RC.

Can you please describe the old RC as well?

cc @janetkuo @kargakis

**Comment by michael-golfi** [comment]
Sure.

So I wasn't sure if there needed to be a preexisting RC when I tried the deployment. So I tried with and without an old RC and both yielded the same result.

The RC as follows:

    apiVersion: v1
    kind: ReplicationController
    metadata:
      name: nginx
    spec:
      replicas: 2
      selector:
        app: nginx
      template:
        metadata:
          name: nginx
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.7.5
            ports:
            - containerPort: 80

**Comment by bgrant0607** [comment]
@michael-golfi Which example did you try? The one from the user guide?
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/deployments.md

What did you update? The image tag, to 1.7.9?

Link to stackoverflow thread?

You don't need to create the RC first. Deployment does that for you.

Prior to the update were the replicas Ready?

Could you try the code at HEAD? Deployment was alpha in 1.1 and has changed a lot in 1.2.

**Comment by bgrant0607** [comment]
@nikhiljindal @kargakis @janetkuo @mqliang When a pre-existing RC is adopted, do we add the pod-template-hash or other labels to it?

**Comment by kargakis** [comment]
We only add the pod-template-hash label to new rcs.

**Comment by fatih** [comment]
I have the same problem. Here is my `kubectl version` output:

```
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.4+a5949fe", GitCommit:"a5949fea3a91d6a50f40a5684e05879080a4c61d", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}
```

I'm using this DeploymentSpec: http://kubernetes.io/v1.1/docs/user-guide/nginx-deployment.yaml manifest and created with:

```
kubectl create -f nginx-deployment.yaml
```

I've tried also with `kubectl` `v1.1.3` but with no luck. I have the following responses after creating the deployment:

```
➜ kubectl describe deployments
Name:				nginx-deployment
Namespace:			default
CreationTimestamp:		Mon, 08 Feb 2016 11:28:29 +0200
Labels:				app=nginx
Selector:			app=nginx
Replicas:			0 updated / 3 total
StrategyType:			RollingUpdate
RollingUpdateStrategy:		1 max unavailable, 1 max surge, 0 min ready seconds
OldReplicationControllers:	<none>
NewReplicationController:	<none>
No events.
```

```
➜ kubectl get deployments
NAME               UPDATEDREPLICAS   AGE
nginx-deployment   0/3               28m
```

**Comment by fatih** [comment]
Wow, after restarting the `kube-controller-manager` it just started to work!:

```
➜ kubectl get deployments
NAME               UPDATEDREPLICAS   AGE
nginx-deployment   3/3               2m
```

I only had started `kube-apiserver` after adding the flag` --runtime config=extensions/v1beta1/deployments=true`, I didn't know that I also had to restart `kube-controller-manager`.

Is this a requirement?

**Comment by kargakis** [comment]
Right now you need to [restart](https://github.com/kubernetes/kubernetes/blob/3cacc7e9ce276177adeeda7c853c4accc2672a8e/cmd/kube-controller-manager/app/controllermanager.go#L248) it but this is supposed to change.

**Comment by fatih** [comment]
Thanks @kargakis. It's also not written in the current doc: http://kubernetes.io/v1.1/docs/user-guide/deployments.html  It would be great if we could mention it there. I think a lot of people would benefit from it and I think it's a big problem. You only can see the problem when you increase the log level somehow (which in my case triggered the restart and I've found it by accident)

**Comment by michael-golfi** [comment]
This was the same solution for me.

As soon as I restarted the kube-controller-manager the deployments started to work.

**Comment by bgrant0607** [comment]
Seems to be resolved.

Deployment is enabled by default in 1.2, and the implementation has evolved pretty significantly, so I'm going to close this as obsolete.

**Comment by rshiva777** [comment]
can anyone please tell me how to restart "kube-controller-manager"

**Comment by cdennison** [comment]
> can anyone please tell me how to restart "kube-controller-manager"

I tried deleting the docker container (called something like k8s_POD_kube-controller-manager-MYNAME_kube-system) and that worked but I also needed to restart the scheduler as well (k8s_kube-scheduler_kube-scheduler-MYNAME_kube-system). See https://stackoverflow.com/questions/56320930/renew-kubernetes-pki-after-expired.

I had this issue after renewing my certs like this 
`kubeadm alpha certs renew all`

**Comment by Huangsh17** [comment]
can anyone please tell me how to restart "kube-controller-manager"

**Comment by cdennison** [comment]
@Huangsh17 - if it's a local cluster just kill the docker container with that name something like k8s_POD_kube-controller-manager-MYNAME_kube-system - otherwise check with your service provider.
