### ISSUE TITLE
Flannel and kube-proxy race for postrouting chain

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20391]
More recent versions of flannel when started with the --ip-masq flag, force a jump to the FLANNEL chain where there's an 'ACCEPT all traffic from node subnet' rule. i.e something like:

```
$ iptables -t nat -L flannel
$ iptables -t nat -A POSTROUTING -s $NODE_CIDR -j FLANNEL
$ iptables -t nat -A FLANNEL -d $NODE_CIDR -j ACCEPT

$ sudo service kube-proxy start
```

From: https://github.com/coreos/flannel/blob/master/network/ipmasq.go#L32

Since ACCEPT is a built in target like DROP, it'll stop processing any of the kube service rules. This manifests as a bug that looks like a misconfigured hairpin mode, i.e, if a pod gets loadbalanced to itself when accessing the service dns name, packets get dropped because of a martian source.

@kubernetes/goog-cluster how do we co-ordinate? is it safe to always have kube-proxy prepend?

**Comment by ArtfulCoder** [comment]
Users are hitting this issue. (referenced issue #22717)

**Comment by ArtfulCoder** [comment]
Other option could be along these lines: https://github.com/kubernetes/kubernetes/issues/22717#issuecomment-195049542

**Comment by mwhooker** [comment]
we're hitting this, too. Does anyone have a workaround? Tried `iptables -t nat -I FLANNEL -s 10.2.0.0/16 -d 10.2.0.0/16 -j MASQUERADE` without any luck.

I think we could get by setting `--proxy-mode=userspace`, but according to the invocation that's qualitatively worse than iptables

**Comment by thockin** [comment]
Can flannel maybe ONLY install this rule if the policy for POSTROUTING is DROP ?  @steveej what do you think?  We need to coordinate a bit...

**Comment by martynd** [comment]
@mwhooker 
At a guess, did you try that command based on [this comment](https://github.com/kubernetes/kubernetes/issues/22717#issuecomment-195048332?)?

If you are still experiencing the issue, try running `. /var/run/flannel/subnet.env && iptables -t nat -D FLANNEL -s $FLANNEL_NETWORK -d  $FLANNEL_NETWORK -j MASQUERADE` to automatically add the rule using the flannels runtime config.

If that isnt where your env file is stored, you can just use the ip/subnet on the flannel.1 interface as that should match. Just switch out the 10.2.0.0/16's in the original command. Alternatively just edit /var/run/flannel/subnet.env accordingly

RE the userspace proxy, it would work as a short term bandaid, but it wont scale as well, so id limit its use just to testing.

**Comment by mwhooker** [comment]
@martynd yes, that's the comment. I looked at `/var/run/flannel/subnet.env` and found `FLANNEL_NETWORK=10.2.0.0/16`, so I have to assume the result will be the same as when I tried it earlier.

I can try again but it will have to wait until later this week.

thanks for the thought, but still looking for alternate ideas.

**Comment by martynd** [comment]
I've come across a similar issue to this one.
Give this a go, it solved the other issue
`. /var/run/flannel/subnet.env && iptables -t nat -A POSTROUTING -s $FLANNEL_SUBNET -o docker0 -j ACCEPT`

**Comment by thockin** [comment]
@steveej ping?

**Comment by lxpollitt** [comment]
cc @tomdee

**Comment by steveeJ** [comment]
@thockin 
> ping?

I'll stick my head together with @tomdee to figure this out.
Some information upfront will be good, this seems also related to installation/configuration (documentation) of kubernetes. What is the official way of setting up flannel with kubernetes? Does kubernetes rely on flannel's `--ip-masq` behavior in any way?

**Comment by bprashanth** [comment]
> What is the official way of setting up flannel with kubernetes? 

There is no "official way", but there is a way that should just work. Run kube-up with NETWORK_PROVIDER=flannel (https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L134).

> Does kubernetes rely on flannel's --ip-masq behavior in any way?

Someone needs to add that masq rule (https://github.com/coreos/flannel/issues/318)

**Comment by tomdee** [comment]
I don't think it's right that flannel does an ACCEPT. A much better option would be a RETURN. As @thockin points out above that could be an issue if the default for the POSTROUTING table was DROP but as far as I understand it that would be an extremely strange thing to do.

I'm going to put up a PR for flannel to change ACCEPT to RETURN and that should resolve this bug.

**Comment by martynd** [comment]
Perhaps it could use ACCEPT/RETURN based on the default policy? Probably a better fit that way.

**Comment by changleicn** [comment]
any updates for this issue？

**Comment by tomdee** [comment]
@changleicn It looks like I fixed this back in May in flannel, so maybe this isn't an issue any more?

**Comment by Hades32** [comment]
Happening for me in a fresh "kubeadm init" installation.

My workaround is finding the "RETURN" rule in "POSTROUTING" that "ignores" intra-pod traffic ans simply delete it. Works fine until k8s restarts...

Could someone care to explain why this rule is needed in the first place? Is it just for optimization?

```
# symptom is like this:

[root@pine64 ~]# docker exec -it 3c93 bash
root@bash-2239139833-xavbo:/# dig grafana
;; reply from unexpected source: 10.244.0.47#53, expected 10.96.0.10#53
# find NAT rule
Chain POSTROUTING (policy ACCEPT 4 packets, 255 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1    22421 1487K KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */
2      803 52102 RETURN     all  --  *      *       10.244.0.0/16        10.244.0.0/16
# delete it
iptables -t nat -D POSTROUTING 2
```

Versions: (system is arm64)
```
ubeadm/kubernetes-xenial,now 1.5.0-alpha.2-421-a6bea3d79b8bba-00 arm64 [installed]
kubectl/kubernetes-xenial,now 1.4.4-00 arm64 [installed]
kubelet/kubernetes-xenial,now 1.4.4-01 arm64 [installed]
kubernetes-cni/kubernetes-xenial,now 0.3.0.1-07a8a2-00 arm64 [installed]
[root@pine64 ~]# docker ps | grep flann
2b7a51958274        quay.io/coreos/flannel-git:v0.6.1-28-g5dde68d-arm64
```

**Comment by thockin** [comment]
@tomdee I don't have a flannel install up right now to poke at, but maybe we can hash out a protocol for this between kube and flannel?  Is flannel still installing rules into POSTROUTING unilaterally?

**Comment by tomdee** [comment]
@thockin sounds good. I'd need to go and check but yes, I think flannel is still installing POSTROUTING rules unilaterally.

**Comment by thockin** [comment]
Should we plan a slack meeting or hangout or something maybe next week or
week after?

**Comment by abemusic** [comment]
Has there been any progress on this? I think we may also be hitting this, but not sure. All pod to pod interactions across nodes seem to be fine when using their service, but host to service works until the service gives back a pod running on the host. If that makes sense :)

**Comment by phillydogg28** [comment]
Bump this again. I am not able to use the service endpoints from inside a pod of the service. 
```
PodA is part of ServiceA.
PodB is part of ServiceB.
In PodA, I can curl ServiceB. In PodB I can curl ServiceA.
In PodA, I *cannot* curl ServiceA. In PodB I *cannot* curl ServiceB.
```
Should I be able to access ServiceA from inside PodA?

**Comment by jl-dos** [comment]
Same issue. Any update?

**Comment by codebreach** [comment]
Hey @phillydogg28, @abemusic and @jl-dos 

We are facing the same issue and were wondering if any of you had found a workaround or a resolution?

Happening on GKE with no plugins on both 1.9.4-gke.1 and 1.7.12-gke.1. Node/Master OS is ContainerOS

**Comment by rikatz** [comment]
A non related but related thing here is that after changing to a pure Calico stack (only Calico, without flannel) solved my race condition issue in a big environment.

**Comment by pickledrick** [comment]
> A non related but related thing here is that after changing to a pure Calico stack (only Calico, without flannel) solved my race condition issue in a big environment.

Hi @rikatz Do you have any guidelines on what you did for migration from Flannel to Calico?

**Comment by discostur** [comment]
Just installed a k8s v1.24.7 cluster with flannel v0.20.1 and the issue still seems to exist: 

```
;; reply from unexpected source: 10.244.0.45#53, expected 10.96.0.10#53
;; reply from unexpected source: 10.244.0.45#53, expected 10.96.0.10#53
;; reply from unexpected source: 10.244.0.45#53, expected 10.96.0.10#53
``` 

DNS only works if the coreDNS pod runs on the same node like the client. Pod to pod communication via services is broken ...

**Comment by aojea** [comment]
but that is a flannel problem, isn't it?

it should be reported on its repo

**Comment by aojea** [comment]
no worries, sometimes is the other way around
