### ISSUE TITLE
Controller manager missed a delete

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20393]
I had a test namespace, created a mixed-protocol service, and then added an LB.  The controller manager correctly generated an error in logs that mixed-protocol LB is not allowed.  I deleted the namespace.  Controller manager is still logging:

 Ensuring LB for service...

But the namespace doesn't exist any more.

**Comment by a-robinson** [comment]
This should be fixed by either #19879 or #19173 (which I haven't properly looked through yet...)

**Comment by thockin** [comment]
Thanks!

**Comment by a-robinson** [comment]
Fixed by #22069
