### ISSUE TITLE
Service validation should reject type=LoadBalancer with mixed-protocol ports

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20394]
Need to handle create and update

**Comment by freehan** [comment]
I can take this up if no one is working on it.

**Comment by thockin** [comment]
This is a good one, shouldn't take long

**Comment by moatazelmasry2** [comment]
Sorry to ask after this has been closed, but why is it not allowed to have mixed protocols and what can I do to mitigate that? I currently have a vpn service that needs to use  a mix of udp and tcp protocols. 

Thanks
