### ISSUE TITLE
e2e tests are monolithic and have symbol clashes

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20396]
Because the e2e tests are just one big mass of code, no sub-packages, we end up with global symbols like "timeout" and a tangle of code calling other code.

We should bust each test into a sub-pkg.

**Comment by Pensu** [comment]
+1 for pkging the test cases. Makes them much more easier to understand and debug.

**Comment by thockin** [comment]
This is actually something significant that community could tackle.  It doesn't require a ton of guidance but is significantly meaty.  One by one, move each test to a sub-pkg, find real "util" functions and move them to an "e2elib" package.  Good opportunity for someone to rack up LOC and commit points :)

**Comment by Pensu** [comment]
@thockin I want to take this up. Will send the PR.

**Comment by spiffxp** [comment]
/sig testing
/assign
I agree with the intent but think "we need to refactor e2e" is better covered by other issues, I'll just throw #42670 out there as one of them
