### ISSUE TITLE
Services and endpoints out of sync causing test flake

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#20402]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/10740/

`Services should be able to create a functioning NodePort service` and `Services should be able to change the type and nodeport settings of a service` failed with message:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:416 Feb 1 00:44:22.421: Could not reach nodePort service through node-ip 130.211.158.115:32285 in 45s
```

cc @thockin @kubernetes/goog-cluster

**Comment by thockin** [comment]
I have restructured this whole test, but not jacked up this timeout.  I'd like to get that PR in and see if this pops up.  I don't think it's reasonable to raise this timeout more.  I think it should be LESS not more.

**Comment by bprashanth** [comment]
Looked through the logs and it looks like the same drift problem. Difference between when the first and last kube-proxy grab the node port in question (30207) is 8:43:24 -> 8:44:39 (1.15 drift). The 15s seems to be just from them both starting up 15s apart, the 1m 

Fast: https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gce/10740/artifacts/104.197.227.132%3A22-kube-proxy.log
Slow: https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gce/10740/artifacts/130.211.158.115%3A22-kube-proxy.log

Now the slow kube-proxy received a service dump at the same time as the fast one, but the mutability-service-test svc in question (the one we're flipping to nodeport) has a resource version of 2330, which is << than the version received by the fast kube-proxy at the same time (3620).

This only seems to indicate updates piling up somewhere, can't point out where without adding logging etc though.

**Comment by jlowdermilk** [comment]
2 more failures from todays test runs: [kubernetes-e2e-gce/10850](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce/10850), [kubernetes-e2e-gce/10855](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce/10855)

**Comment by davidopp** [comment]
ref/ #18210

**Comment by wojtek-t** [comment]
This happened again for me:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26500/#
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/19200/kubernetes-pull-build-test-e2e-gce/26500/?project=kubernetes-jenkins

**Comment by bprashanth** [comment]
For the record
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/20569/kubernetes-pull-build-test-e2e-gce/26583/artifacts/
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26583/consoleFull

Test:
```
14:18:31 STEP: verifying service has 3 reachable backends
14:18:31 Feb  3 22:17:12.303: INFO: Executing cmd "set -e; for i in $(seq 1 150); do wget -q --timeout=0.2 --tries=1 -O - http://10.0.202.178:80 2>&1 || true; echo; done" on host 104.154.16.9:22
14:18:31 Feb  3 22:18:17.750: INFO: Waiting for expected pods for 10.0.202.178: [service3-dyvqi service3-ujhxf service3-xiujh], got: [service3-dyvqi]
14:18:31 STEP: deleting pod execpod in namespace e2e-tests-services-taqzy
14:18:31 Feb  3 22:18:22.757: INFO: Unexpected error occurred: service verification failed for: 10.0.202.178, expected [service3-dyvqi service3-ujhxf service3-xiujh], got []
14:18:31 [AfterEach] Services
```

And kube-proxy logs from 104.154.16.9: 
```
I0203 22:18:15.534332       6 proxier.go:379] Setting endpoints for "e2e-tests-services-taqzy/service3:" to [10.245.4.38:9376]
I0203 22:18:19.722352       6 proxier.go:379] Setting endpoints for "e2e-tests-services-taqzy/service3:" to [10.245.0.34:9376 10.245.4.38:9376]
I0203 22:18:20.939910       6 proxier.go:379] Setting endpoints for "e2e-tests-services-taqzy/service3:" to [10.245.0.34:9376 10.245.4.38:9376 10.245.5.34:9376]
```

Only the first endpoint made it in time (< 22:18:17.750).

**Comment by pwittrock** [comment]
I just saw this again [here](http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26644/console)

>>
18:12:54 Summarizing 1 Failure:
18:12:54 
18:12:54 [Fail] Services [It] should be able to change the type and ports of a service 
18:12:54 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1625
18:12:54 
18:12:54 Ran 117 of 219 Specs in 808.390 seconds
18:12:54 FAIL! -- 116 Passed | 1 Failed | 0 Pending | 102 Skipped

**Comment by bprashanth** [comment]
I believe the last failure was because of a bit of retarded code I wrote. More specifically:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26583/consoleFull#
```
18:12:15 Feb  4 02:07:00.461: INFO: Testing HTTP reachability of http://104.197.198.151:31458/echo?msg=hello
18:12:15 Feb  4 02:07:00.463: INFO: Got error testing for reachability of http://104.197.198.151:31458/echo?msg=hello: Get http://104.197.198.151:31458/echo?msg=hello: dial tcp 104.197.198.151:31458: getsockopt: connection refused
18:12:15 Feb  4 02:07:02.463: INFO: Testing HTTP reachability of http://104.197.198.151:31458/echo?msg=hello
18:12:15 Feb  4 02:07:02.467: INFO: Successfully reached http://104.197.198.151:31458/echo?msg=hello
18:12:15 STEP: hitting the UDP service's new NodePort
18:12:15 Feb  4 02:07:02.467: INFO: Testing UDP reachability of udp://104.197.198.151:30559
18:12:15 Feb  4 02:07:04.468: INFO: Testing UDP reachability of udp://104.197.198.151:30559
18:12:15 Feb  4 02:07:06.468: INFO: Testing UDP reachability of udp://104.197.198.151:30559
18:12:15 Feb  4 02:07:08.468: INFO: Testing UDP reachability of udp://104.197.198.151:30559
```

And if you open up the kube-proxy logs from 198.151: https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/pr-logs/pull/19932/kubernetes-pull-build-test-e2e-gce/26644/artifacts/104.197.198.151%3A22-kube-proxy.log

```
I0204 02:07:00.465111       6 proxier.go:320] Something changed for service "e2e-tests-services-36hhn/mutability-test:": removing it
I0204 02:07:00.465136       6 proxier.go:324] Adding new service "e2e-tests-services-36hhn/mutability-test:" at 10.0.9.159:80/TCP
I0204 02:07:00.465199       6 proxier.go:336] added serviceInfo(e2e-tests-services-36hhn/mutability-test:): (*iptables.serviceInfo)(0xc82039a200)({
 clusterIP: (net.IP) (len=16 cap=16) 10.0.9.159,
 port: (int) 80,
 protocol: (api.Protocol) (len=3) "TCP",
 nodePort: (int) 31458,
 loadBalancerStatus: (api.LoadBalancerStatus) {
  Ingress: ([]api.LoadBalancerIngress) (len=1 cap=1) {
   (api.LoadBalancerIngress) {
    IP: (string) (len=14) "104.154.61.193",
    Hostname: (string) ""
   }
  }
 },
 sessionAffinityType: (api.ServiceAffinity) (len=4) "None",
 stickyMaxAgeSeconds: (int) 180,
 externalIPs: ([]string) <nil>
})
I0204 02:07:00.465217       6 proxier.go:471] Syncing iptables rules
I0204 02:07:00.465227       6 iptables.go:377] running iptables -N [KUBE-SERVICES -t nat]
I0204 02:07:00.467015       6 iptables.go:377] running iptables -C [OUTPUT -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I0204 02:07:00.468814       6 iptables.go:377] running iptables -N [KUBE-SERVICES -t nat]
I0204 02:07:00.470043       6 iptables.go:377] running iptables -C [PREROUTING -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I0204 02:07:00.471391       6 iptables.go:377] running iptables -C [POSTROUTING -t nat -m comment --comment kubernetes service traffic requiring SNAT -m mark --mark 0x4d415351 -j MASQUERADE]
```

Which correlates with the passing HTTP test.

```
I0204 02:07:00.475106       6 config.go:266] Service handler already has a pending interrupt.
```

Which correlates with what I expect to have been the UDP node port update. And then 5m later, when we relist to find the udp node port 30559:
```
I0204 02:12:10.478041       6 proxier.go:324] Adding new service "e2e-tests-services-r890i/mutability-test:" at 10.0.197.29:80/UDP
I0204 02:12:10.478115       6 proxier.go:336] added serviceInfo(e2e-tests-services-r890i/mutability-test:): (*iptables.serviceInfo)(0xc8204e7000)({
 clusterIP: (net.IP) (len=16 cap=16) 10.0.197.29,
 port: (int) 80,
 protocol: (api.Protocol) (len=3) "UDP",
 nodePort: (int) 30559,
 loadBalancerStatus: (api.LoadBalancerStatus) {
  Ingress: ([]api.LoadBalancerIngress) (len=1 cap=1) {
   (api.LoadBalancerIngress) {
    IP: (string) (len=14) "104.197.228.30",
    Hostname: (string) ""
   }
  }
 },
 sessionAffinityType: (api.ServiceAffinity) (len=4) "None",
 stickyMaxAgeSeconds: (int) 180,
 externalIPs: ([]string) <nil>
})
```

Sent https://github.com/kubernetes/kubernetes/pull/20624

**Comment by pwittrock** [comment]
Just saw the same test failing.  Logs [here](https://doc-0icba-10oao-s-googleusercontent.commondatastorage.googleapis.com/gs/fuc2vio4jd536so122rmrf52ehn3qlv5/ujhl6npgfu4vupnbahoojac127n28a47/1454625000000/kubernetes-jenkins/01720166177040642613/ChJrdWJlcm5ldGVzLWplbmtpbnMSSXByLWxvZ3MvcHVsbC8xOTkzMi9rdWJlcm5ldGVzLXB1bGwtYnVpbGQtdGVzdC1lMmUtZ2NlLzI2Nzk0L2J1aWxkLWxvZy50eHQ?a=AGjQbs4j3Rt7D2s9KvYIV2kt8UyUtNxV3VX8IW2Utqu8WjpgkjEWzrGX15yiIKa9W_Zr9XcFgArY33VPxBQCETogqeE3Rgd8XuOF6Sm29zPnJ33lru74FmaWowBh9dSJjM71wmoWQD1HVbt-YzkghGQjYczkXVAh-HMUwCqzgzMUXFn37TAzcVE6Xd_JIJvKkNGz1PbvbRIeFYQ1BSaAfmfL-QfDNGCKbGeEC1YjYYpcRPqC9LCxTj9rADs-y_EpKdhTRKu2JKwQcSZ-SfEAJNedjNEz4hUelh9u3K8Nx6lufOuqEoeI7e-Bt-LbDXbaU5QNtFkeso6-SIa__ftwiTLGFuPOsHoEIaKTvl3WkDjqwXjRjSZMMBdZNCTV-CU7oQkl8fiLgQgEWJBmzG87pKaSM43zHVdyYeqy4R6ZtMlQ01wP4aW70FUvueDs2Az9H6NekkOWvfuX5bWi9diCOv6_9PcAEYK4E2eHGddyP9EnkbLNSRNwUvCh5KQZmsvRO1-aaw7Exz3OsnkFcVQ_PnZG6LC0Gyj7EOm28F9LeYBHLuT8MAUalxGi5kMVp2qW--bXhBJ9Pc_dZbvYaxdD31iU6wFLWnXeXV7qFnYAeOkehoEyZOkN1NxIEQV70teQA8b_Qvb0wA6aI4cJpGKlKvx71oJ5p3jqkuoFIJeGGldZ_GWENyP79RiToTIbB9Q-q4sG8UtvI76KOV5WNE6C_l5xvR46er9WZ9tgK6owPtz4Ih6mNdYk8CzzqEJ4V1ELOlYI5_y-SDpO5Nqu4wJ1e5ACX0EAnGPhLw&nonce=kal8c2692oaia&user=01720166177040642613&hash=khmabm3o7di21irnd455gu5ov5i445e5) 

>
â€¢ Failure [1488.615 seconds]
Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:862
  should be able to change the type and ports of a service [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:677
  Feb  4 21:46:33.091: Timeout waiting for service "mutability-test" to have no load balancer
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1606

Does this look like the same issue, or should I open a new one?

**Comment by bprashanth** [comment]
Your logs link doens't work for me

**Comment by bprashanth** [comment]
@pwittrock I'm guessing you mean the pr linked, i.e http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/26654
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/20621/kubernetes-pull-build-test-e2e-gce/26654/

Which failed with:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:677
Feb  4 03:34:08.833: Timeout waiting for service "mutability-test" to have no load balancer
```

That's not this issue, it's https://github.com/kubernetes/kubernetes/issues/20547.

If you have a service test failure that *isn't* a timeout on loadbalancer deletion please post here. If not, please close.

**Comment by pwittrock** [comment]
@bprashanth thanks that is very helpful
