### ISSUE TITLE
Client generating script doesn't update entry in test clientset

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#20414]
I created a new API group, then ran `./hack/update-codegen.sh`. The script hasn't updated entry in `pkg/client/testing/fake/clientset.go` so that I had to edit the file manually.

**Comment by piosz** [comment]
Assigned @lavalamp for triage.

cc @kubernetes/goog-csi

**Comment by caesarxuchao** [comment]
Glad to hear people starting to use the client-gen! It still needs some improvements. The fake clientset is not auto generated, I'll add the automation soon. For now hopefully it's not too much trouble to manually edit it, it should only require adding a method per group.

**Comment by piosz** [comment]
@caesarxuchao it's not hard to manually update the fake client, although the script fails with confusing error, so there would be at least great to add a proper error message.
