### ISSUE TITLE
Kube binary error messages are very verbose

### ISSUE THREAD

**Issue by jacobtomlinson** [kubernetes/kubernetes#20410]
When running image `gcr.io/google_containers/hyperkube-amd64:v1.2.0-alpha.6` and receiving an error message it prints the full usage after the error. The usage is 260 lines, not including wrapping. 

It may be sensible to have a short help message which prints some high level help information and the command to display the full usage.

**Comment by gmarek** [comment]
cc @bgrant0607

**Comment by techtonik** [comment]
Is it still actual
;
