### ISSUE TITLE
when use ./cluster/kube-up.sh provision k8s

### ISSUE THREAD

**Issue by henryon** [kubernetes/kubernetes#20416]
when provision k8s version 1.1.7 on vagrant . there have some issues as below:
==> master: sh: line 1: syntax error near unexpected token `newline'
==> master: sh: line 1: `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

anyone can help this?
Thanks in advance.

========Full log========================
./cluster/kube-up.sh
... Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'minion-1' up with 'virtualbox' provider...
==> master: Clearing any previously set forwarded ports...
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 => 2222 (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2222
    master: SSH username: vagrant
    master: SSH auth method: private key
    master: Warning: Connection timeout. Retrying...
==> master: Machine booted and ready!
==> master: Checking for guest additions in VM...
==> master: Configuring and enabling network interfaces...
==> master: Mounting shared folders...
    master: /vagrant => /Users/HenryWen/Docker/kubernetes
==> master: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> master: flag to force provisioning. Provisioners marked to run always will still run.
==> master: Running provisioner: shell...
    master: Running: /var/folders/st/7gf56xv52jn97pthscx8sdw00000gn/T/vagrant-shell20160201-945-zz3ww.sh
==> master: Provisioning network on master
==> master: Network configuration verified
==> master: Running release install script
==> master: /kube-install /home/vagrant
==> master: +++ Installing salt files into new trees
==> master: ‘./kubernetes/saltbase/salt’ -> ‘/srv/salt-new/salt’
==> master: ‘./kubernetes/saltbase/salt/debian-auto-upgrades’ -> ‘/srv/salt-new/salt/debian-auto-upgrades’
==> master: ‘./kubernetes/saltbase/salt/debian-auto-upgrades/init.sls’ -> ‘/srv/salt-new/salt/debian-auto-upgrades/init.sls’
==> master: ‘./kubernetes/saltbase/salt/debian-auto-upgrades/20auto-upgrades’ -> ‘/srv/salt-new/salt/debian-auto-upgrades/20auto-upgrades’
==> master: ‘./kubernetes/saltbase/salt/kube-apiserver’ -> ‘/srv/salt-new/salt/kube-apiserver’
==> master: ‘./kubernetes/saltbase/salt/kube-apiserver/kube-apiserver.manifest’ -> ‘/srv/salt-new/salt/kube-apiserver/kube-apiserver.manifest’
==> master: ‘./kubernetes/saltbase/salt/kube-apiserver/init.sls’ -> ‘/srv/salt-new/salt/kube-apiserver/init.sls’
==> master: ‘./kubernetes/saltbase/salt/base.sls’ -> ‘/srv/salt-new/salt/base.sls’
==> master: ‘./kubernetes/saltbase/salt/static-routes’ -> ‘/srv/salt-new/salt/static-routes’
==> master: ‘./kubernetes/saltbase/salt/static-routes/if-down’ -> ‘/srv/salt-new/salt/static-routes/if-down’
==> master: ‘./kubernetes/saltbase/salt/static-routes/init.sls’ -> ‘/srv/salt-new/salt/static-routes/init.sls’
==> master: ‘./kubernetes/saltbase/salt/static-routes/if-up’ -> ‘/srv/salt-new/salt/static-routes/if-up’
==> master: ‘./kubernetes/saltbase/salt/static-routes/refresh’ -> ‘/srv/salt-new/salt/static-routes/refresh’
==> master: ‘./kubernetes/saltbase/salt/helpers’ -> ‘/srv/salt-new/salt/helpers’
==> master: ‘./kubernetes/saltbase/salt/helpers/init.sls’ -> ‘/srv/salt-new/salt/helpers/init.sls’
==> master: ‘./kubernetes/saltbase/salt/helpers/safe_format_and_mount’ -> ‘/srv/salt-new/salt/helpers/safe_format_and_mount’
==> master: ‘./kubernetes/saltbase/salt/supervisor’ -> ‘/srv/salt-new/salt/supervisor’
==> master: ‘./kubernetes/saltbase/salt/supervisor/docker.conf’ -> ‘/srv/salt-new/salt/supervisor/docker.conf’
==> master: ‘./kubernetes/saltbase/salt/supervisor/kube-proxy-checker.sh’ -> ‘/srv/salt-new/salt/supervisor/kube-proxy-checker.sh’
==> master: ‘./kubernetes/saltbase/salt/supervisor/init.sls’ -> ‘/srv/salt-new/salt/supervisor/init.sls’
==> master: ‘./kubernetes/saltbase/salt/supervisor/kubelet.conf’ -> ‘/srv/salt-new/salt/supervisor/kubelet.conf’
==> master: ‘./kubernetes/saltbase/salt/supervisor/kube-proxy.conf’ -> ‘/srv/salt-new/salt/supervisor/kube-proxy.conf’
==> master: ‘./kubernetes/saltbase/salt/supervisor/docker-checker.sh’ -> ‘/srv/salt-new/salt/supervisor/docker-checker.sh’
==> master: ‘./kubernetes/saltbase/salt/supervisor/kube-addons.conf’ -> ‘/srv/salt-new/salt/supervisor/kube-addons.conf’
==> master: ‘./kubernetes/saltbase/salt/supervisor/kubelet-checker.sh’ -> ‘/srv/salt-new/salt/supervisor/kubelet-checker.sh’
==> master: ‘./kubernetes/saltbase/salt/supervisor/supervisor_watcher.sh’ -> ‘/srv/salt-new/salt/supervisor/supervisor_watcher.sh’
==> master: ‘./kubernetes/saltbase/salt/supervisor/kube-addons-checker.sh’ -> ‘/srv/salt-new/salt/supervisor/kube-addons-checker.sh’
==> master: ‘./kubernetes/saltbase/salt/kubelet’ -> ‘/srv/salt-new/salt/kubelet’
==> master: ‘./kubernetes/saltbase/salt/kubelet/initd’ -> ‘/srv/salt-new/salt/kubelet/initd’
==> master: ‘./kubernetes/saltbase/salt/kubelet/init.sls’ -> ‘/srv/salt-new/salt/kubelet/init.sls’
==> master: ‘./kubernetes/saltbase/salt/kubelet/kubelet.service’ -> ‘/srv/salt-new/salt/kubelet/kubelet.service’
==> master: ‘./kubernetes/saltbase/salt/kubelet/kubeconfig’ -> ‘/srv/salt-new/salt/kubelet/kubeconfig’
==> master: ‘./kubernetes/saltbase/salt/kubelet/default’ -> ‘/srv/salt-new/salt/kubelet/default’
==> master: ‘./kubernetes/saltbase/salt/cadvisor’ -> ‘/srv/salt-new/salt/cadvisor’
==> master: ‘./kubernetes/saltbase/salt/cadvisor/init.sls’ -> ‘/srv/salt-new/salt/cadvisor/init.sls’
==> master: ‘./kubernetes/saltbase/salt/kube-admission-controls’ -> ‘/srv/salt-new/salt/kube-admission-controls’
==> master: ‘./kubernetes/saltbase/salt/kube-admission-controls/init.sls’ -> ‘/srv/salt-new/salt/kube-admission-controls/init.sls’
==> master: ‘./kubernetes/saltbase/salt/kube-admission-controls/limit-range’ -> ‘/srv/salt-new/salt/kube-admission-controls/limit-range’
==> master: ‘./kubernetes/saltbase/salt/kube-admission-controls/limit-range/limit-range.yaml’ -> ‘/srv
==> master: /salt-new/salt/kube-admission-controls/limit-range/limit-range.yaml’
==> master: ‘./kubernetes/saltbase/salt/docker’ -> ‘/srv/salt-new/salt/docker’
==> master: ‘./kubernetes/saltbase/salt/docker/docker.service’ -> ‘/srv/salt-new/salt/docker/docker.service’
==> master: ‘./kubernetes/saltbase/salt/docker/docker-defaults’ -> ‘/srv/salt-new/salt/docker/docker-defaults’
==> master: ‘./kubernetes/saltbase/salt/docker/init.sls’ -> ‘/srv/salt-new/salt/docker/init.sls’
==> master: ‘./kubernetes/saltbase/salt/docker/default’ -> ‘/srv/salt-new/salt/docker/default’
==> master: ‘./kubernetes/saltbase/salt/salt-helpers’ -> ‘/srv/salt-new/salt/salt-helpers’
==> master: ‘./kubernetes/saltbase/salt/salt-helpers/services’ -> ‘/srv/salt-new/salt/salt-helpers/services’
==> master: ‘./kubernetes/saltbase/salt/salt-helpers/init.sls’ -> ‘/srv/salt-new/salt/salt-helpers/init.sls’
==> master: ‘./kubernetes/saltbase/salt/kube-registry-proxy’ -> ‘/srv/salt-new/salt/kube-registry-proxy’
==> master: ‘./kubernetes/saltbase/salt/kube-registry-proxy/kube-registry-proxy.yaml’ -> ‘/srv/salt-new/salt/kube-registry-proxy/kube-registry-proxy.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-registry-proxy/init.sls’ -> ‘/srv/salt-new/salt/kube-registry-proxy/init.sls’
==> master: ‘./kubernetes/saltbase/salt/generate-cert’ -> ‘/srv/salt-new/salt/generate-cert’
==> master: ‘./kubernetes/saltbase/salt/generate-cert/make-ca-cert.sh’ -> ‘/srv/salt-new/salt/generate-cert/make-ca-cert.sh’
==> master: ‘./kubernetes/saltbase/salt/generate-cert/init.sls’ -> ‘/srv/salt-new/salt/generate-cert/init.sls’
==> master: ‘./kubernetes/saltbase/salt/generate-cert/make-cert.sh’ -> ‘/srv/salt-new/salt/generate-cert/make-cert.sh’
==> master: ‘./kubernetes/saltbase/salt/kube-master-addons’ -> ‘/srv/salt-new/salt/kube-master-addons’
==> master: ‘./kubernetes/saltbase/salt/kube-master-addons/initd’ -> ‘/srv/salt-new/salt/kube-master-addons/initd’
==> master: ‘./kubernetes/saltbase/salt/kube-master-addons/init.sls’ -> ‘/srv/salt-new/salt/kube-master-addons/init.sls’
==> master: ‘./kubernetes/saltbase/salt/kube-master-addons/kube-master-addons.service’ -> ‘/srv/salt-new/salt/kube-master-addons/kube-master-addons.service’
==> master: ‘./kubernetes/saltbase/salt/kube-master-addons/kube-master-addons.sh’ -> ‘/srv/salt-new/salt/kube-master-addons/kube-master-addons.sh’
==> master: ‘./kubernetes/saltbase/salt/etcd’ -> ‘/srv/salt-new/salt/etcd’
==> master: ‘./kubernetes/saltbase/salt/etcd/init.sls’ -> ‘/srv/salt-new/salt/etcd/init.sls’
==> master: ‘./kubernetes/saltbase/salt/etcd/etcd.manifest’ -> ‘/srv/salt-new/salt/etcd/etcd.manifest’
==> master: ‘./kubernetes/saltbase/salt/fluentd-gcp’ -> ‘/srv/salt-new/salt/fluentd-gcp’
==> master: ‘./kubernetes/saltbase/salt/fluentd-gcp/init.sls’ -> ‘/srv/salt-new/salt/fluentd-gcp/init.sls’
==> master: ‘./kubernetes/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml’ -> ‘/srv/salt-new/salt/fluentd-gcp/fluentd-gcp.yaml’
==> master: ‘./kubernetes/saltbase/salt/logrotate’ -> ‘/srv/salt-new/salt/logrotate’
==> master: ‘./kubernetes/saltbase/salt/logrotate/init.sls’ -> ‘/srv/salt-new/salt/logrotate/init.sls’
==> master: ‘./kubernetes/saltbase/salt/logrotate/cron’ -> ‘/srv/salt-new/salt/logrotate/cron’
==> master: ‘./kubernetes/saltbase/salt/logrotate/conf’ -> ‘/srv/salt-new/salt/logrotate/conf’
==> master: ‘./kubernetes/saltbase/salt/logrotate/docker-containers’ -> ‘/srv/salt-new/salt/logrotate/docker-containers’
==> master: ‘./kubernetes/saltbase/salt/ntp’ -> ‘/srv/salt-new/salt/ntp’
==> master: ‘./kubernetes/saltbase/salt/ntp/init.sls’ -> ‘/srv/salt-new/salt/ntp/init.sls’
==> master: ‘./kubernetes/saltbase/salt/top.sls’ -> ‘/srv/salt-new/salt/top.sls’
==> master: ‘./kubernetes/saltbase/salt/kube-scheduler’ -> ‘/srv/salt-new/salt/kube-scheduler’
==> master: ‘./kubernetes/saltbase/salt/kube-scheduler/init.sls’ -> ‘/srv/salt-new/salt/kube-scheduler/init.sls’
==> master: ‘./kubernetes/saltbase/salt/kube-scheduler/kube-scheduler.manifest’ -> ‘/srv/salt-new/salt/kube-scheduler/kube-scheduler.manifest’
==> master: ‘./kubernetes/saltbase/salt/kube-proxy’ -> ‘/srv/salt-new/salt/kube-proxy’
==> master: ‘./kubernetes/saltbase/salt/kube-proxy/kube-proxy.service’ -> ‘/srv/salt-new/salt/kube-proxy/kube-proxy.service’
==> master: ‘./kuber
==> master: netes/saltbase/salt/kube-proxy/initd’ -> ‘/srv/salt-new/salt/kube-proxy/initd’
==> master: ‘./kubernetes/saltbase/salt/kube-proxy/init.sls’ -> ‘/srv/salt-new/salt/kube-proxy/init.sls’
==> master: ‘./kubernetes/saltbase/salt/kube-proxy/kubeconfig’ -> ‘/srv/salt-new/salt/kube-proxy/kubeconfig’
==> master: ‘./kubernetes/saltbase/salt/kube-proxy/default’ -> ‘/srv/salt-new/salt/kube-proxy/default’
==> master: ‘./kubernetes/saltbase/salt/kube-controller-manager’ -> ‘/srv/salt-new/salt/kube-controller-manager’
==> master: ‘./kubernetes/saltbase/salt/kube-controller-manager/kube-controller-manager.manifest’ -> ‘/srv/salt-new/salt/kube-controller-manager/kube-controller-manager.manifest’
==> master: ‘./kubernetes/saltbase/salt/kube-controller-manager/init.sls’ -> ‘/srv/salt-new/salt/kube-controller-manager/init.sls’
==> master: ‘./kubernetes/saltbase/salt/nginx’ -> ‘/srv/salt-new/salt/nginx’
==> master: ‘./kubernetes/saltbase/salt/nginx/kubernetes-site’ -> ‘/srv/salt-new/salt/nginx/kubernetes-site’
==> master: ‘./kubernetes/saltbase/salt/nginx/nginx.conf’ -> ‘/srv/salt-new/salt/nginx/nginx.conf’
==> master: ‘./kubernetes/saltbase/salt/nginx/init.sls’ -> ‘/srv/salt-new/salt/nginx/init.sls’
==> master: ‘./kubernetes/saltbase/salt/nginx/nginx.json’ -> ‘/srv/salt-new/salt/nginx/nginx.json’
==> master: ‘./kubernetes/saltbase/salt/kube-addons’ -> ‘/srv/salt-new/salt/kube-addons’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-loadbalancing’ -> ‘/srv/salt-new/salt/kube-addons/cluster-loadbalancing’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-loadbalancing/glbc’ -> ‘/srv/salt-new/salt/kube-addons/cluster-loadbalancing/glbc’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-loadbalancing/glbc/glbc-controller.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-loadbalancing/glbc/glbc-controller.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-loadbalancing/glbc/default-svc.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-loadbalancing/glbc/default-svc.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/kube-addon-update.sh’ -> ‘/srv/salt-new/salt/kube-addons/kube-addon-update.sh’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/initd’ -> ‘/srv/salt-new/salt/kube-addons/initd’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/dns’ -> ‘/srv/salt-new/salt/kube-addons/dns’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/dns/skydns-rc.yaml.in’ -> ‘/srv/salt-new/salt/kube-addons/dns/skydns-rc.yaml.in’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/dns/skydns-svc.yaml.in’ -> ‘/srv/salt-new/salt/kube-addons/dns/skydns-svc.yaml.in’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/namespace.yaml’ -> ‘/srv/salt-new/salt/kube-addons/namespace.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/init.sls’ -> ‘/srv/salt-new/salt/kube-addons/init.sls’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/registry’ -> ‘/srv/salt-new/salt/kube-addons/registry’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/registry/registry-svc.yaml’ -> ‘/srv/salt-new/salt/kube-addons/registry/registry-svc.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/registry/registry-pvc.yaml.in’ -> ‘/srv/salt-new/salt/kube-addons/registry/registry-pvc.yaml.in’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/registry/registry-pv.yaml.in’ -> ‘/srv/salt-new/salt/kube-addons/registry/registry-pv.yaml.in’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/registry/registry-rc.yaml’ -> ‘/srv/salt-new/salt/kube-addons/registry/registry-rc.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/kube-addons.service’ -> ‘/srv/salt-new/salt/kube-addons/kube-addons.service’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/kube-addons.sh’ -> ‘/srv/salt-new/salt/kube-addons/kube-addons.sh’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/googleinfluxdb’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/googleinfluxdb’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/googleinfluxdb/heapster-controller-combined.yaml’ -> ‘/srv/salt-new/salt/kube-addons/c
==> master: luster-monitoring/googleinfluxdb/heapster-controller-combined.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb/heapster-service.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb/heapster-service.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb/heapster-controller.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb/heapster-controller.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb/influxdb-service.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb/influxdb-service.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb/grafana-service.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb/grafana-service.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/standalone’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/standalone’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/standalone/heapster-service.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/standalone/heapster-service.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/standalone/heapster-controller.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/standalone/heapster-controller.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/google’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/google’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/google/heapster-service.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/google/heapster-service.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/cluster-monitoring/google/heapster-controller.yaml’ -> ‘/srv/salt-new/salt/kube-addons/cluster-monitoring/google/heapster-controller.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/fluentd-elasticsearch’ -> ‘/srv/salt-new/salt/kube-addons/fluentd-elasticsearch’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/fluentd-elasticsearch/kibana-controller.yaml’ -> ‘/srv/salt-new/salt/kube-addons/fluentd-elasticsearch/kibana-controller.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/fluentd-elasticsearch/es-service.yaml’ -> ‘/srv/salt-new/salt/kube-addons/fluentd-elasticsearch/es-service.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/fluentd-elasticsearch/es-controller.yaml’ -> ‘/srv/salt-new/salt/kube-addons/fluentd-elasticsearch/es-controller.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/fluentd-elasticsearch/kibana-service.yaml’ -> ‘/srv/salt-new/salt/kube-addons/fluentd-elasticsearch/kibana-service.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/kube-ui’ -> ‘/srv/salt-new/salt/kube-addons/kube-ui’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/kube-ui/kube-ui-rc.yaml’ -> ‘/srv/salt-new/salt/kube-addons/kube-ui/kube-ui-rc.yaml’
==> master: ‘./kubernetes/saltbase/salt/kube-addons/kube-ui/kube-ui-svc.yaml’ -> ‘/srv/salt-new/salt/kube-addons/kube-ui/kube-ui-svc.yaml’
==> master: ‘./kubernetes/saltbase/salt/fluentd-es’ -> ‘/srv/salt-new/salt/fluentd-es’
==> master: ‘./kubernetes/saltbase/salt/fluentd-es/fluentd-es.yaml’ -> ‘/srv/salt-new/salt/fluentd-es/fluentd-es.yaml’
==> master: ‘./kubernetes/saltbase/salt/fluentd-es/init.sls’ -> ‘/srv/salt-new/salt/fluentd-es/init.sls’
==> master: ‘./kubernetes/saltbase/salt/README.md’ -> ‘/srv/salt-new/salt/README.md’
==> master: ‘./kubernetes/saltbase/salt/kube-client-tools.sls’ -> ‘/srv/salt-new/salt/kube-client-tools.sls’
==> master: ‘./kubernetes/saltbase/pillar’ -> ‘/srv/salt-new/pillar’
==> master: ‘./kubernetes/saltbase/pillar/cluster-params.sls’ -> ‘/srv/salt-new/pillar/cluster-params.sls’
==> master: ‘./kubernetes/saltbase/pillar/systemd.sls’ -> ‘/srv/salt-new/pillar/sys
==> master: temd.sls’
==> master: ‘./kubernetes/saltbase/pillar/privilege.sls’ -> ‘/srv/salt-new/pillar/privilege.sls’
==> master: ‘./kubernetes/saltbase/pillar/top.sls’ -> ‘/srv/salt-new/pillar/top.sls’
==> master: ‘./kubernetes/saltbase/pillar/logging.sls’ -> ‘/srv/salt-new/pillar/logging.sls’
==> master: ‘./kubernetes/saltbase/pillar/README.md’ -> ‘/srv/salt-new/pillar/README.md’
==> master: ‘./kubernetes/saltbase/pillar/mine.sls’ -> ‘/srv/salt-new/pillar/mine.sls’
==> master: ‘./kubernetes/saltbase/pillar/docker-images.sls’ -> ‘/srv/salt-new/pillar/docker-images.sls’
==> master: ‘./kubernetes/saltbase/reactor’ -> ‘/srv/salt-new/reactor’
==> master: ‘./kubernetes/saltbase/reactor/highstate-masters.sls’ -> ‘/srv/salt-new/reactor/highstate-masters.sls’
==> master: ‘./kubernetes/saltbase/reactor/highstate-minions.sls’ -> ‘/srv/salt-new/reactor/highstate-minions.sls’
==> master: ‘./kubernetes/saltbase/reactor/README.md’ -> ‘/srv/salt-new/reactor/README.md’
==> master: ‘./kubernetes/saltbase/reactor/highstate-new.sls’ -> ‘/srv/salt-new/reactor/highstate-new.sls’
==> master: +++ Installing salt overlay files
==> master: ‘/srv/salt-overlay/salt/kube-apiserver/known_tokens.csv’ -> ‘/srv/salt-new/salt/kube-apiserver/known_tokens.csv’
==> master: ‘/srv/salt-overlay/salt/kube-apiserver/basic_auth.csv’ -> ‘/srv/salt-new/salt/kube-apiserver/basic_auth.csv’
==> master: ‘/srv/salt-overlay/salt/kubelet/kubernetes_auth’ -> ‘/srv/salt-new/salt/kubelet/kubernetes_auth’
==> master: ‘/srv/salt-overlay/salt/kubelet/kubeconfig’ -> ‘/srv/salt-new/salt/kubelet/kubeconfig’
==> master: ‘/srv/salt-overlay/salt/kube-proxy/kubeconfig’ -> ‘/srv/salt-new/salt/kube-proxy/kubeconfig’
==> master: ‘/srv/salt-overlay/pillar/cluster-params.sls’ -> ‘/srv/salt-new/pillar/cluster-params.sls’
==> master: +++ Install binaries from tar: kubernetes-server-linux-amd64.tar.gz
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/hyperkube’ -> ‘/srv/salt-new/salt/kube-bins/hyperkube’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kube-apiserver’ -> ‘/srv/salt-new/salt/kube-bins/kube-apiserver’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kube-apiserver.docker_tag’ -> ‘/srv/salt-new/salt/kube-bins/kube-apiserver.docker_tag’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kube-apiserver.tar’ -> ‘/srv/salt-new/salt/kube-bins/kube-apiserver.tar’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kube-controller-manager’ -> ‘/srv/salt-new/salt/kube-bins/kube-controller-manager’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kube-controller-manager.docker_tag’ -> ‘/srv/salt-new/salt/kube-bins/kube-controller-manager.docker_tag’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kube-controller-manager.tar’ -> ‘/srv/salt-new/salt/kube-bins/kube-controller-manager.tar’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kubectl’ -> ‘/srv/salt-new/salt/kube-bins/kubectl’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kubelet’ -> ‘/srv/salt-new/salt/kube-bins/kubelet’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kube-proxy’ -> ‘/srv/salt-new/salt/kube-bins/kube-proxy’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kube-scheduler’ -> ‘/srv/salt-new/salt/kube-bins/kube-scheduler’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kube-scheduler.docker_tag’ -> ‘/srv/salt-new/salt/kube-bins/kube-scheduler.docker_tag’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/kube-scheduler.tar’ -> ‘/srv/salt-new/salt/kube-bins/kube-scheduler.tar’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/server/bin/linkcheck’ -> ‘/srv/salt-new/salt/kube-bins/linkcheck’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/addons/gcr.io~google_containers~kube-registry-proxy:0.3.tar’ -> ‘/srv/salt-new/salt/kube-addons-images/gcr.io~google_containers~kube-registry-proxy:0.3.tar’
==> master: ‘/tmp/kubernetes.XhQkv6/kubernetes/addons/gcr.io~google_containers~pause:0.8.0.tar’ -> ‘/srv/salt-new/salt/kube-addons-images/gcr.io~google_containers~pause:0.8.0.tar’
==> master: +++ Swapping in new configs
==> master: ‘/srv/salt-new/salt’ -> ‘/srv/salt’
==> master: ‘/srv/salt-new/pillar’ -> ‘/srv/pillar’
==> master: ‘/srv/salt-new/reactor’ -> ‘/srv/reactor’
==> master: /home/vagrant
==> master: sh: line 1: syntax error near unexpected token `newline'
==> master: sh: line 1: `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by henryon** [comment]
I redownload the k8s.tar.gz and rerun script kube-up.sh
found below errors:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://copr.fedorainfracloud.org/coprs/saltstack/salt/repo/fedora-21/saltstack-salt-fedora-21.repo">here</a>.</p>
<hr>
<address>Apache/2.4.6 (Red Hat Enterprise Linux) Server at copr.fedoraproject.org Port 80</address>
</body></html>

**Comment by henryon** [comment]
I've modified the script of provision-master.sh by replacing 

    #wget https://copr.fedoraproject.org/coprs/sgallagh/cockpit-preview/repo/fedora-21/sgallagh-cockpit-preview-fedora-21.repo
    wget https://copr.fedorainfracloud.org/coprs/saltstack/salt/repo/fedora-21/saltstack-salt-fedora-21.repo

I've restart my Mac when rerun deploy script.
but still get errors as below picture. 
![Uploading 屏幕快照 2016-02-01 下午11.26.33.png…]()

**Comment by henryon** [comment]
`[root@kubernetes-master yum.repos.d]# ll
总用量 20
-rw-r--r--. 1 root root 1252 11月 22 2014 fedora.repo
-rw-r--r--. 1 root root 1270 11月 22 2014 fedora-updates.repo
-rw-r--r--. 1 root root 1328 11月 22 2014 fedora-updates-testing.repo
-rw-r--r--. 1 root root  388 2月   1 14:50 saltstack-salt-fedora-21.repo
-rw-r--r--. 1 root root  349 2月   1 14:46 sgallagh-cockpit-preview-fedora-21.repo
[root@kubernetes-master yum.repos.d]# more saltstack-salt-fedora-21.repo
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://copr.fedorainfracloud.org/coprs/salts
tack/salt/repo/fedora-21/saltstack-salt-fedora-21.repo">here</a>.</p>
<hr>
<address>Apache/2.4.6 (Red Hat Enterprise Linux) Server at copr.fedoraproject.or
g Port 80</address>
</body></html>
[root@kubernetes-master yum.repos.d]# exit`

**Comment by gmarek** [comment]
cc @thockin @derekwaynecarr to triage

**Comment by henryon** [comment]
@gmarek  any work around for this?

**Comment by fuggersbergerdavid** [comment]
you can find a work around for your issue here https://github.com/kubernetes/kubernetes/issues/20088

**Comment by derekwaynecarr** [comment]
I think this should fix things up for you: https://github.com/kubernetes/kubernetes/pull/20267

**Comment by davidopp** [comment]
Thanks @derekwaynecarr 

@henryon Please reopen if #20267 did not fix.
