### ISSUE TITLE
Add preemptible option for GCE Master

### ISSUE THREAD

**Issue by wstrange** [kubernetes/kubernetes#20417]
For development purposes, I'd like to see an option to start the GCE master as a preemptible VM. This allows individual developers gain access to GCE at a very low cost. For many developers, tolerating preemption is going to be acceptable.

I'm happy to submit the PR - it looks like a very simple change.

**Comment by gmarek** [comment]
cc @kubernetes/goog-control-plane

**Comment by davidopp** [comment]
I believe this is already implemented in #12384

**Comment by wstrange** [comment]
Hi David

From what I can see looking under cluster/gce/*, the minions are preemptible, but not the master. 

Probably off topic for this bug, but would also love to see preemptible for GKE :-) I did raise that issue on the mailing list.

**Comment by davidopp** [comment]
Oh sorry, I mis-read and thought you were asking about preemptible nodes.

I think enabling preemptible for the master would be trivial (similar to #12384); feel free to send a PR.

Note that the semantics of preemptible are that the VM terminates and does not restart, so once your master gets preempted, I'm not sure there's anything useful you can do other than tear down your cluster. I guess there might be some way you could bring up a replacement master and remount the PD from the terminated master, similar to how we do it for master upgrade in cluster/gce/upgrade.sh. But this seems like a lot of hassle compared to just using a normal (non-preemptible) small VM.

cc/ @roberthbailey

**Comment by wstrange** [comment]
Hi David

I agree - once your master is down practically speaking you probably need to blow away your cluster and start over.  I think for  (poor :-) ) developers, this is going to be an acceptable tradeoff. 

I'd also like to see the ability for the GCE cluster scripts to run the whole works (master + minion) on a single VM - like you can do on GKE.  That is probably a separate issue though.

I'll see if I can put together a PR for this.

**Comment by davidopp** [comment]
GKE does not run the master and minion on the same VM.

**Comment by wstrange** [comment]
Odd.  When I run with GKE and specify 1 node, all I see running under my GCE console is a single VM. Does the master not show up? Or at least I *think* I see one VM. I'll have to verify

**Comment by davidopp** [comment]
On GKE, Google runs the master for you, as a result you don't see it.

**Comment by wstrange** [comment]
Hi David 

I submitted a PR

This is not quite the panacea I was hoping for,  but it may help some folks, and the default is to not preempt - so it should not change any existing behaviour. 

Aside: I found that gce scripts did not tear down the master after a kube-down.sh. Is that by design, or did I just not wait long enough?

 This issue may not be the place to discuss, but what I really want as a independent developer is:
- An insanely inexpensive, all in one node, "GKE" like environment, that auto terminates if I forget to turn the cluster down.

The GCE provider turned out to be not what I was hoping for:
- Takes a long time to provision. Does it really need to upload the k8 binaries to gs? Why can't it use existing uploaded binaries?
- kube-down.sh did not clean up all the resources  (gs storage buckets, firewall rules, master did not get deprovisioned, etc)
- For whatever reason, it did not seem to use the NUM_NODES=1 parameter (still created 3 nodes). I think this is due to some funky min/max calculations and auto-scaling -not quite sure.

**Comment by roberthbailey** [comment]
> what I really want as a independent developer is an insanely inexpensive, all in one node, "GKE" like environment, that auto terminates if I forget to turn the cluster down.

Have you tried running a cluster [locally in docker](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md)? You could do this same thing inside a preemptible VM on GCE. You could even install a cron job that shuts down the machine every N hours (if you are using it, you can start it back up). 

> Does it really need to upload the k8 binaries to gs? Why can't it use existing uploaded binaries?

https://github.com/kubernetes/kubernetes/issues/7997 

> kube-down.sh did not clean up all the resources (gs storage buckets, firewall rules, master did not get deprovisioned, etc)

It won't clean up the storage buckets (if you run kube-up again, it won't upload the binaries a second time). If you have created services that are externalized, those won't be cleaned up either (see https://github.com/kubernetes/kubernetes/issues/4630). It *should* tear down the master VM though. Were you running the stock script or a modified variant (with a preemptible VM)?

> it did not seem to use the NUM_NODES=1 parameter

This sounds like a bug. If you can reproduce at HEAD (with no local modifications) please file a separate issue.

**Comment by roberthbailey** [comment]
> so once your master gets preempted, I'm not sure there's anything useful you can do other than tear down your cluster. 

This isn't actually true. If you use the existing pattern from GCE, then there isn't anything critical stored on the boot disk of the master VM (everything is on a GCE PD that is mounted onto the master). I haven't tried this, but I would expect that when the preemptible VM is terminated, the static IP address that has been reserved is maintained in your project. If that is true, then you could re-create your master by re-attaching the static IP address and the data PD when you want to restart your cluster. In the mean time, if your master is stopped but your nodes are still running, they should just coast along.

**Comment by davidopp** [comment]
^^^ Yeah, that's what I was alluding to when I said "I guess there might be some way you could bring up a replacement master and remount the PD from the terminated master, similar to how we do it for master upgrade in cluster/gce/upgrade.sh."

I was a bit harsh (and accidentally misleading) when I said there isn't anything useful you can do -- I just meant this would require some hacking to get it to work, there's nothing out-of-the-box that will do it. Having to re-create your master each time the old one is preempted seems like a big hassle, though I don't know what the actual preemption rates are of preemptible VMs, so maybe you wouldn't have to do it very often.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gce
since we lack a sig-gcp at the moment
