### ISSUE TITLE
--restart=always issues in docker-multinode

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#20411]
Hi,
I've deployed and tested `docker-multinode` a few times now. It worked, with a few issues
- `/dev/pts/ptmx` permissions is set with wrong permissions #18230
- A turndown script is missing, so one have to clean up by hand. Partially related: #19179
- If one runs e.g. `master.md` a few times, many `DOCKER_OPTS`-lines are created in `/etc/default/docker`: https://github.com/kubernetes/kubernetes/pull/19212#issuecomment-177497396

When I rebooted the computer though, the CPU usage was 100% on two of four cores.
It turned out five kubelets and kube-proxies had restarted, although I think I had `docker rm -f` them.
Two of them were zombies, one was running and I don't really know what the two other were doing.

I could kill three of them with `docker rm -f`, but then I had to reboot, `docker rm -f` one of them, reboot and finally kill the last one.
I had to reboot because the parent PIDs of hyperkube is 1 and of course I don't want to kill the whole system.

So I would say we should replace `--restart=always` with `--restart=on-failure`, because it's extremely annoying to not be able to `docker kill` those containers. Now and then they start when you least expect it.

And `on-failure` should do it's job.
I can make a PR for this.
@dalanlan @brendandburns @thockin @fgrzadkowski

**Comment by fgrzadkowski** [comment]
sgtm.

Thanks for improving docker based setup! :)
