### ISSUE TITLE
Networking. Kubernetes, direct access to a POD port without expose.

### ISSUE THREAD

**Issue by jdanielcano** [kubernetes/kubernetes#20420]
Hello,

We are running a cluster of Kubernetes / Docker and we would like to allow to a container to be accessed from an external IP and a random port if the service running in the container, in this case an Apache Tomcat, has establish a connection first with, for example, a database, in this case we do not know the port.
It means, in a not containerized world, we should have something like this in an IPTABLES 

-A INPUT -i eth0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o eth0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

Should be possible to have this configuration in a kubernetes cluster to allow all incoming communications if became from our internal network, without specifying a port?

Thanks a lot.

**Comment by thockin** [comment]
I'm sorry, I don't quite understand this request - can you explain it a
little more?

**Comment by jdanielcano** [comment]
Thanks for your reply and sorry for my poor explanation. Actually what I really would like to know if it is possible in kubernetes, to expose a range of ports or if it is possible to allow incoming / outgoing communications without knowing the port used. 

As fas as I know, both options are not possible to achieve in Kubernetes, but I would like to confirm.

Thanks a lot!

**Comment by thockin** [comment]
We do not currently support port ranges.  I wouldn't mind supporting them,
but the feasibility of it really depends on how they are to be used.  Can
you explain how you would use ranges?

We don't have a general way to give a "whole" external IP to a pod or
Service, yet.

**Comment by danbopes** [comment]
@thockin See this question: http://stackoverflow.com/questions/37992007/creating-ftp-service

I've attempted to create an FTP service, which needs to have multiple ports forwarded for the passive range.

**Comment by thockin** [comment]
So this needs someone to own the design and implementation.  I think we can
EOL the userspace proxier at some point, or at least say that ranges won't
be supported for it
