### ISSUE TITLE
Error handling on node-not-up in kube-up 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#20424]
Forked from issue: https://github.com/kubernetes/kubernetes/issues/18969#issuecomment-177010714

Today kube-up asks to bring N nodes, and wait for timeout check the number (M) of Ready nodes. If M is not equal to N, kube-up just simply quit. The user has to restart the entire kube-up process from the beginning. This is really a bad user experience. We should add self-healing so that nodes that fail to come up are replaced / repaired. There are many ways to achieve self-handling, and at GCE, managed instance group can easily delete nodes or recreate nodes with id:

https://cloud.google.com/compute/docs/instance-groups/#delete_from_group 
https://cloud.google.com/compute/docs/instance-groups/#recreate_instances

cc/ @bgrant0607 @davidopp @quinton-hoole @roberthbailey @gmarek

**Comment by gmarek** [comment]
I completely agree. The only question is how high is priority for adding this? I doubt it's 1.2 and I'm not sure if we started 1.3 list. @aronchick

**Comment by bgrant0607** [comment]
There are multiple parts to this.

The self-healing part may be non-trivial, depending on what MIGs provide.

OTOH, changing validate-cluster.sh to accept min and max numbers of nodes to expect should be trivial.

**Comment by davidopp** [comment]
IMO we should do this in a portable way if at all possible. On-prem, for example, obviously doesn't have MIGs.

If we change validate-cluster.sh to accept less than the request number of nodes (which I agree is a good first step), we should make that behavior be flag-controlled (e.g. --accept-startup-nodes=N or whatever) and default that to the number of nodes the user asked for.
