### ISSUE TITLE
KUBERNETES_CONTRIB=mesos build/run.sh failed on MacOS with sed error

### ISSUE THREAD

**Issue by linsun** [kubernetes/kubernetes#20422]
Following docs:  https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/mesos-docker.md

I was able to run 'KUBERNETES_CONTRIB=mesos make'.  However, 'KUBERNETES_CONTRIB=mesos build/run.sh' failed with sed error below.

Lins-MacBook-Pro-2:kubernetes linsun$ KUBERNETES_CONTRIB=mesos build/run.sh
+++ [0201 11:40:37] Verifying Prerequisites....
+++ [0201 11:40:38] Building Docker image kube-build:cross-1.5.3-1.
sed: 1: "/Users/linsun/workspace ...": extra characters at the end of l command
!!! Error in build/../build/common.sh:461
  'sed -i "s/KUBE_BUILD_IMAGE_CROSS/${KUBE_BUILD_IMAGE_CROSS}/" ${build_context_dir}/Dockerfile' exited with status 1
Call stack:
  1: build/../build/common.sh:461 kube::build::build_image(...)
  2: build/run.sh:29 main(...)

After googling and found "http://myshittycode.com/2014/07/24/os-x-sed-extra-characters-at-the-end-of-l-command-error/", then I was able to edit the code from 
sed -i "s/KUBE_BUILD_IMAGE_CROSS/${KUBE_BUILD_IMAGE_CROSS}/" ${build_context_dir}/Dockerfile

to 
sed -i '' "s/KUBE_BUILD_IMAGE_CROSS/${KUBE_BUILD_IMAGE_CROSS}/" ${build_context_dir}/Dockerfile

and able to pass this error.

**Comment by jlowdermilk** [comment]
Looks like this was very recently fixed in #20147. If you sync to head it should pick up fix.
