### ISSUE TITLE
Default ports and permissions on e2e test containers. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#20434]
Currently openshift has a different security model applied to containers see: https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/authorization.html#security-context-constraints as well as https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html.  

When running a number of test containers, they open default ports e.g. 80 , and in our env we will often encounter issues such as: 

```
$ sudo docker logs 3bfa2ba69d65
2016/02/01 20:11:20 listen tcp :80: bind: permission denied
```

I think this can be easily circumvented by setting up the containers to not assume root like capabilities in the pods and instead port forward where applicable. 

@ixdy @soltysh @jayunit100  
/cc @kubernetes/sig-testing

**Comment by timothysc** [comment]
xrefs: https://github.com/kubernetes/kubernetes/pull/12221 , https://github.com/openshift/origin/issues/6882

**Comment by soltysh** [comment]
The other option would be to allow injecting additional capabilities similarly to how we need to solve problem in #12221. I'll be working on it in the following days.

**Comment by timothysc** [comment]
@soltysh I think yes to both are probably a good approach ;-)

**Comment by soltysh** [comment]
@timothysc since we have #20808 in place already, do you think this is still valid? I mean with that PR we have pretty flexible approach into managing SCC inside of openshift, agreed?

**Comment by timothysc** [comment]
@soltysh agreed.
