### ISSUE TITLE
GET componentstatuses fails on 1000 node cluster on gce: 

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#20445]
In testing a 1000 node cluster with single master, attempting to health-check the cluster results in errors.

Fetching https://104.155.220.201/api/v1/componentstatuses gives:
429 Too Many Requests 429 HTTP/1.1 1 1 map[Content-Length:[43] Content-Type:[text/plain; charset=utf-8] Date:[Mon, 01 Feb 2016 21:44:14 GMT] Retry-After:[1]]

That consistently happens with both 1.1.7 and 1.2.0-alpha.6.  Looks to me like some form of rate limiting?  We clearly need the api server to reliably serve those health checking requests.

**Comment by alex-mohr** [comment]
@lavalamp Or maybe 429 Too Many Requests for /componentstatuses is a @kubernetes/goog-csi issue not control-plane?  Apologies if I got that wrong.

**Comment by krousey** [comment]
@alex-mohr Could you run the apiserver with `--max-requests-in-flight=0` flag (disabled the global rate limiting), and see if it still occurs? FWIW, the open source client automatically retires 429 statuses. Is it still failing after retries?

Rate limiting related:
https://github.com/kubernetes/kubernetes/blob/cd2e0c490e464f080ff76ae9be9145f3b9dc747c/cmd/kube-apiserver/app/options/options.go#L192
https://github.com/kubernetes/kubernetes/blob/cd2e0c490e464f080ff76ae9be9145f3b9dc747c/pkg%2Fgenericapiserver%2Fgenericapiserver.go#L565
https://github.com/kubernetes/kubernetes/blob/cd2e0c490e464f080ff76ae9be9145f3b9dc747c/pkg%2Fapiserver%2Fhandlers.go#L76

**Comment by davidopp** [comment]
cc/ @wojtek-t @gmarek

**Comment by alex-mohr** [comment]
I haven't had a chance to retry with a different flag, but re: retries, no there weren't explicit retries, but I looked at individual calls and 0 out of 20 succeeded, so it's not just a sporadic error -- it's a continuous condition.

**Comment by mqliang** [comment]
IIRC, the `--max-requests-in-flight` flag only work if we use https, for http request, there is no ratelimit, right?

**Comment by gmarek** [comment]
@alex-mohr what was the size of master's machine and what was the load you put on it? I checked on kubemark test for 32 core master during density run and it was quite happy (taken when there was ~20k running pods) `https://104.197.154.159/api/v1/componentstatuses`

```
{
  "kind": "ComponentStatusList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/componentstatuses"
  },
  "items": [
    {
      "metadata": {
        "name": "scheduler",
        "selfLink": "/api/v1/componentstatuses/scheduler",
        "creationTimestamp": null
      },
      "conditions": [
        {
          "type": "Healthy",
          "status": "True",
          "message": "ok"
        }
      ]
    },
    {
      "metadata": {
        "name": "controller-manager",
        "selfLink": "/api/v1/componentstatuses/controller-manager",
        "creationTimestamp": null
      },
      "conditions": [
        {
          "type": "Healthy",
          "status": "True",
          "message": "ok"
        }
      ]
    },
    {
      "metadata": {
        "name": "etcd-1",
        "selfLink": "/api/v1/componentstatuses/etcd-1",
        "creationTimestamp": null
      },
      "conditions": [
        {
          "type": "Healthy",
          "status": "True",
          "message": "{\"health\": \"true\"}"
        }
      ]
    },
    {
      "metadata": {
        "name": "etcd-0",
        "selfLink": "/api/v1/componentstatuses/etcd-0",
        "creationTimestamp": null
      },
      "conditions": [
        {
          "type": "Healthy",
          "status": "True",
          "message": "{\"health\": \"true\"}"
        }
      ]
    }
  ]
}
```

It's possible that we're putting less load on Kubemark master than the real one. I'll check the metrics when test finishes.

**Comment by gmarek** [comment]
@mqliang - yes, we limit only requests to the secure server, but @alex-mohr was connecting to it.

**Comment by gmarek** [comment]
@alex-mohr can you write what size of master are you using and what load were you putting on it?

**Comment by gmarek** [comment]
ping @alex-mohr

**Comment by gmarek** [comment]
I've seen something similar for the first time during 1000 node cluster startup: https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-enormous-startup/4/build-log.txt

Sadly we don't save any logs for failed cluster startups: #10423 which would be extremely helpful here.

**Comment by roberthbailey** [comment]
@kubernetes/goog-gke

**Comment by alex-mohr** [comment]
@gmarek I think it was an n1-standard-4 master.  I created a 10 node cluster and waited for that to stabilize, then did mig.resize(1000) with no other load.

I plan to try again with a -32 core master, but even so, if there's other load on it, we need the master to continue to service health-checking URLs -- GKE monitors those rather closely.  @fabioy

**Comment by lavalamp** [comment]
If you're getting a 429 on that endpoint, that means other components are getting 429s on things that matter, so just fixing this for the monitoring thingy is probably not a great idea.

I think what needs to happen:

* /healthz, /componentstatuses, perhaps others, need to be rate-limited out of a separate bucket.
* We need to count the rate of 429s and have some threshold for saying when the cluster is unhealthy due to the master not being responsive enough.

**Comment by gmarek** [comment]
I think that n1-standard-4 master got completely overloaded by NodeStatus updates, which made it completely useless. @wojtek-t 

We can do separate rate limitters for /healthz'ish stuff easily enough - IIUC this is v1.2 blocker right? @alex-mohr 

@lavalamp - do you have throughput in CSI team to deal with it, or do you need someone else to do it?

**Comment by lavalamp** [comment]
It sounds like the actual problem is using the wrong size master. I'm not convinced we should do anything at the moment; a cluster 429ing the health checks very possibly should be considered broken. @alex-mohr I chatted with this about @roberthbailey -- please sync up with him or with me.

**Comment by alex-mohr** [comment]
Krousey writes:
The handler is implemented here:
https://github.com/kubernetes/kubernetes/blob/9fda7f181299e49dd5f28405952ee76821eab74c/pkg/apiserver/handlers.go#L76

And installed here:
https://github.com/kubernetes/kubernetes/blob/4606d1408bb32642328e854b1c3e9f0d3639efcf/pkg/genericapiserver/genericapiserver.go#L614

It's all one bucket right now, with a regex escape hatch.

They are rate limited to prevent the master from being overloaded.

**Comment by alex-mohr** [comment]
@lavalamp (and @roberthbailey) *The* actual problem is not using the wrong size master in this case.  There are many ways a master can get overloaded and this particular case was just one trigger to make that happen, which exposed an underlying issue that the master sheds the wrong load on overload.  Obviously people can likely overload their master by making lots of API calls too.

But in order to monitor the master, that monitoring service must be able to actually contact it and collect telemetry.  On overload, the master should keep responding to those high-priority health checks and discard other traffic instead.

c.f. borg tasks generally attempt to answer /healthz even why cpu usage is greater than cpu limit, monitoring jobs run at higher priority than normal jobs, borglets hitting their CPU caps still allow borgmaster to talk to them, etc.

Of course, I agree that clusters 429ing large numbers of api calls is a poor situation and that monitoring should pick that signal up as well -- it's presumably exposed via prometheus metrics?

So, back to your comment:
>  I'm not convinced we should do anything at the moment
Are you convinced now, or should we chat further?

**Comment by alex-mohr** [comment]
Re: which endpoints we need,
- "/componentstatuses" 
- "/nodes"

I don't think we have great role-based identity support yet?  That is, cluster monitoring can be whitelisted to have either no bucket or a separate bucket?  If not, the most expedient is to whitelist those two paths to bypass buckets entirely, but that might allow nodes or users to accidentally DoS the master.  Other options would be tagging calls with bypass_ratelimiter=true, or adding a /monitoring/<real_endpoint> redirector, and presumably others.

**Comment by gmarek** [comment]
Why "/nodes"?

**Comment by zmerlynn** [comment]
> Why "/nodes"?

We (GKE) monitor both `/componentstatuses` and the `/nodes` endpoint. The latter is lesser priority, but we do watch it. cc @fabioy

**Comment by fabioy** [comment]
We fetch "/nodes" to get the number of nodes registered in the master for billing purposes (among other things).

**Comment by wojtek-t** [comment]
hmm - although I agree that having separate throttling/priority for /componentstatuses (and /healthz and stuff like that) makes sense, I don't think that making "/nodes" treated differently than other resources is what we would like to do. @lavalamp - thoughts?

**Comment by lavalamp** [comment]
There's no point in putting nodes in a separate bucket. Things other than monitoring talk to it!

If we want to bucket separately based on *user* rather than *path*, that would make sense.

**Comment by lavalamp** [comment]
Met up with @alex-mohr & @roberthbailey-- we decided not to rush for 1.2, that we should do user-based bucketing for monitoring users, and possibly also put healthz in a different bucket or make it unlimited.

**Comment by gmarek** [comment]
We forgot (?) about it for 1.3. Should we put it in a 1.4 list?

**Comment by alex-mohr** [comment]
@gmarek @wojtek-t If it's required for the 2k nodes work, it's 1.3.  If it's not, then 1.4.

**Comment by gmarek** [comment]
We don't think it's needed for 2k nodes. Let's do it for 1.4.

**Comment by gmarek** [comment]
cc @lavalamp for triage.

**Comment by lavalamp** [comment]
I agree with my past self:

> If we want to bucket separately based on user rather than path, that would make sense.

I just saw another PR out to raise the max-in-flight limit, which would resolve this as a side-effect.

**Comment by gmarek** [comment]
@wojtek-t - we need to check if it's still a problem.

**Comment by wojtek-t** [comment]
Well - once the size of the master is correct, it shouldn't be a problem, but if master is too small, the it will always be the problem. The question is how urgent it is and I'm not sure.

**Comment by gmarek** [comment]
Very obsolete.
