### ISSUE TITLE
Provide auth as a cluster service 

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#20443]
Forked from discussion in https://github.com/kubernetes/kubernetes/pull/17191

In the final proposal, each federated api server will do auth for the requests they get, but the auth mechanism has to be same across all servers in the cluster (so that clients can contact them via proxy). More details: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/federated-api-servers.md#auth

Hence, it will be good to factor out auth as a separate service, which all the federated servers can call.

cc @erictune @smarterclayton @lavalamp @kubernetes/sig-api-machinery @kubernetes/goog-csi

**Comment by smarterclayton** [comment]
Authz or authn?

**Comment by nikhiljindal** [comment]
Authentication for sure.
I am not so sure about authorization.

**Comment by smarterclayton** [comment]
It's very unlikely we'll be able to provide auth as a cluster service
in a way that works for everyone.  Authz is very clear, authn is
harder.  We've been discussion this in other forums, @liggitt what's
the most recent doc / proposal that covers the "consensus opinion"?

**Comment by erictune** [comment]
Something like https://github.com/kubernetes/kubernetes/pull/20347 might give us authorization delegation from apiserver A to a central authorizer, which might or might bot be Apiserver B.

Nothing planned for authentication.    They just need to run the same plugins.  

 People know how to do this stuff, so we should not spend time on it.   If you setup two MySQL databases, they don't talk to each other to do auth.  The admin just configures them the same.  This is not going to surprise anyone.

**Comment by erictune** [comment]
IMO, close this issue.

**Comment by smarterclayton** [comment]
We have other issues to track this.
