### ISSUE TITLE
Document how to set up a feature test suite in Jenkins

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20456]
Per https://github.com/kubernetes/kubernetes/pull/20354#discussion_r51474329

@spxtr mind taking this on?

**Comment by spxtr** [comment]
I can handle this, I suppose. It might also be useful to have a script that greps for `"\[Feature:.+\]"` in `.go` files and makes sure there's a corresponding job in `e2e.sh`. Not sure if it's worth the hassle, though.

**Comment by ihmccreery** [comment]
Yeah @spxtr I've considered something similar, but came to the same conclusion.  I'd like to get to a world where the norm is that if you're promoting a feature from experimental -> beta -> GA, making sure the tests are where they should be, but that may not be feasible without a linter.

**Comment by fejta** [comment]
https://github.com/kubernetes/kubernetes/blob/75b01662e61d8cd2b63b0ceaa8631a00ac01fdc0/docs/devel/e2e-tests.md

**Comment by ihmccreery** [comment]
I don't think @bprashanth's original concern has been addressed:

> Do you want to clarify that people are responsible for setting up their own `[Feature]` config subsections in `jenkins/e2e.sh` and (optionally) projects to run in?

There's nothing in `e2e-tests.md` about how to configure Jenkins, only that one should.
