### ISSUE TITLE
remove `NUM_NODES_PARALLEL` from Jenkins configs

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#20461]
Prior to #20276, the Ginkgo parallel jobs used clusters of size `NUM_NODES_PARALLEL`, while non-parallel jobs used clusters of size `NUM_NODES` (a smaller size). With that PR, things are inconsistent.

We should either
a) make sure all parallel jobs are using `NUM_NODES_PARALLEL`, or
b) get rid of `NUM_NODES_PARALLEL` entirely.

I think I created `NUM_NODES_PARALLEL` with the expectation that having a larger cluster would make the overall test run faster. I'm not sure whether this is still true, but we should have data on `kubernetes-e2e-gce` from over the weekend which can inform us.

@kubernetes/goog-testing

**Comment by quinton-hoole** [comment]
The reason for creating it was that some tests were failing with "cluster
full" errors in the parallel runs when the clusters had only 3 nodes.
Rather than increase the cluster size for all test jobs, we did so for only
parallel jobs.

**Comment by quinton-hoole** [comment]
Why closed?  It seems that we still need to do #1 in the original issue description above?

**Comment by spxtr** [comment]
We did b) `NUM_NODES_PARALLEL` has been removed from Jenkins configs.

**Comment by spxtr** [comment]
@quinton-hoole we don't actually use larger clusters for the parallel test runs anymore, but they seem stable. Do you think this issue should stay open?

**Comment by quinton-hoole** [comment]
@spxtr If we're running the same number of nodes for serial as for parallel tests, then we're wasting (approximately 2X) nodes for serial tests.  So yes, I think that that should be fixed.

**Comment by spxtr** [comment]
We're using 3 nodes for both serial and parallel runs. Think it's worth cutting serial runs down to 2 nodes?

**Comment by ixdy** [comment]
Isn't the minimum cluster size on GKE 3 nodes? ISTR also that our testing cluster was explicitly bumped from 2 to 3 nodes at some point last year, and not because of Ginkgo parallel mode.

**Comment by spxtr** [comment]
On GKE I can make a 1-node cluster.

It might be worth running tests against small clusters, actually.

**Comment by quinton-hoole** [comment]
@spxtr @ixdy I seem to remember that static system pods (DNS, Heapster etc) used up most of two nodes, leaving insufficient resources for test pods.  
Also, most tests need more than 1 node, so having 3 meant that one Node could fail without introducing flakes due to there being only one node left (in theory).

**Comment by spxtr** [comment]
Ok.

It sounds like we do need 3 nodes, and the stability of the parallel suites makes it look like we don't need more than three for those.

**Comment by fejta** [comment]
Sounds like we can close this after all?

**Comment by quinton-hoole** [comment]
@fejta Up to you, but I wouldn't recommend it.  In the past we needed to run different numbers of nodes in parallel vs serial clusters, to, amongst others, speed them up.  In the future I'm pretty sure we will too.  Claim is that today we don't. I don't quite understand why that is so - doesn't seem to make sense to me.

**Comment by fejta** [comment]
We can add it back to the yaml configs the next time it is necessary. This issue is done.
