### ISSUE TITLE
import loop with labelSelector

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#20462]
I am moving jobs to api group `batch`.  That is where it will live for v1.
So, I am putting the unversioned types there too.

This introduces an import loop.
- batch imports LabelSelector type from package extensions.
- package extensions needs to import batch to register it.

I think the right fix is to move LabelSelector to the legacy api group.   yes/no?

@lavalamp
@bgrant0607 
@smarterclayton 

I have limited time before 1.2 to move job and make other changes, so quick-and-dirty suggestions that can be fixed later are welcome.

**Comment by smarterclayton** [comment]
Probably it fits into "unversioned" (which doesn't mean unversioned, it
means "version 1 of all the things that are common across a bunch of
different groups").  I'm ok with the legacy API group though.

**Comment by bgrant0607** [comment]
I'm ok with putting it into api/v1, also. extensions are getting ObjectMeta from there already.

**Comment by erictune** [comment]
May need to.  Having trouble with generating conversions for
pkg/api/unversioned.

**Comment by lavalamp** [comment]
This appears to be fixed with that merge.
