### ISSUE TITLE
Persistent Volume Claims with different subpaths

### ISSUE THREAD

**Issue by parikhyash** [kubernetes/kubernetes#20466]
I've set up a persistent volume using an NFS mount (NFS server is managed by me).

I've also been able to create a PersistentVolumeClaim using the above NFS volume and launch a pod that uses the claim.

The issue is that I need to mount a particular subpath of the volume per claim. So I wanted to know if there's a way to have multiple claims, each having a different subpath mounted from the main PersistentVolume. In this way, different pods can be launched with claims corresponding to only that subpath as required by them and not the entire NFS volume. Currently, k8s doesn't accept a path parameter when creating a claim so there's no way to separate out parts of the volume.

Any thoughts about how this can be done or can a path parameter be added to the PersistentVolumeClaim spec to achieve this?

The only solution that fits now is to have multiple NFS volumes per cluster, which doesn't seem right.

Use case: The NFS server stores state information for a lot of application clusters and is used to restore state in case of crashes. Need to mount state information of only one application per application pod. Otherwise, pods would have access to state information of other applications as well.

**Comment by thockin** [comment]
Is it that you want to mount `/share/subdir` to the machine or that you
want to mount `/share` to the machine and `/share/subdir` to the pod?

We have discussed adding a directory in the "left hand side" of the mount,
but nobody has gotten around to implementing it yet.  I don't think anyone
is against it.  I could swear we had an issue open for it, but I can't find
it.

**Comment by parikhyash** [comment]
@thockin 

It's the second case. I want to mount `/share/subdir` to the pod. It doesn't matter what is mounted to the machine, but it would be better to have `/share` on all the nodes since there will be many pods on the same machine using `/share/subdir1`, `/share/subdir2`, etc.

Otherwise I would need to create different volumes on the same machine to have `/share/subdir1` and `/share/subdir2` which seems like repeating work as `/share` is coming from the same server.

**Comment by bdurette** [comment]
I can echo that having containers mount subpaths would be very useful for us. This could solve a couple of issues for us: 

1. The limited number of persistent disk mounts is an issue for us. However, if container visibility could be restricted to individual subpaths, then it would solve that for us because we could share pds between pods. We don't care that they are separate disks if the containers can see different subtrees. For this to be most useful, we'd probably also need resource-aware scheduling to ensure that all the pods that want subdirectories of the persistent disk land on the host where it is mounted.

2. In addition to sharing persistent disks between pods, we also have a need to further limit filesystem visibility on individual containers within our pods, so that the applications running there are not aware of the other "tenants" on the same disk.

**Comment by thockin** [comment]
I'm fine with the idea.  Help wanted - we're buried :)

This seems like a pretty approachable problem for someone who was only a little familiar with kubernetes

**Comment by MikaelCluseau** [comment]
I think I hit a related issue. Many docker images are expecting empty volumes and will not initialize a volume with something inside. For instance, I observe that the official mysql docker (often?) fails to do its initial setup in my setup, and I suspect it is because the volume has `lost+found`, because it is ext4 formatted (I'm using RBD devices and let Kubernetes format them). Thus, I'm interested in tackling this issue. This just to illustrate a problem, I'll try to remove lost+found in my volume auto-provisionner; no need to discuss this in details here.

About solutions, this is something that will need to be specified somewhere in the pod spec right? Which means it will be an API change?

The simplest solution I can think about now is adding a "subPath" property to VolumeMount. This would allow some nice things like using one volume for multiple mounts. For instance, a LAMP stack pod could be implemented this way:

```yaml
  spec:
    containers:
    - name: mysql
      image: mysql
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: site-data
        subPath: mysql
    - name: php
      image: php
      volumeMounts:
      - mountPath: /var/www/html
        name: site-data
        subPath: html
    volumes:
    - name: site-data
      persistentVolumeClaim:
        claimName: ...
```

This should solve the "number of mounts" issue since the PVC will be mapped to a unique folder like `/var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/volumes-image-xxx` for the RBD case.

Comments please :-)

**Comment by parikhyash** [comment]
@MikaelCluseau Would the subPath folder be created automatically if it doesn't exist?

- This would be useful if a new 'tenant' is using the volume in which case the folder would need to be created the first time.

**Comment by thockin** [comment]
On Fri, Mar 4, 2016 at 3:48 PM, Mikaël Cluseau <notifications@github.com> wrote:
>
> I think I hit a related issue. Many docker images are expecting empty volumes and will not initialize a volume with something inside. For instance, I observe that the official mysql docker (often?) fails to do its initial setup in my setup, and I suspect it is because the volume has lost+found, because it is ext4 formatted (I'm using RBD devices and let Kubernetes format them). Thus, I'm interested in tackling this issue. This just to illustrate a problem, I'll try to remove lost+found in my volume auto-provisionner; no need to discuss this in details here.

I don't think you can delete lost+found :)  Aside from that, this is a
bug in whatever.  They should not care if other files exist - if they
really do care, they can never run at the root of any modern
filesystem, and not at all in some filesystems.

> About solutions, this is something that will need to be specified somewhere in the pod spec right? Which means it will be an API change?

yep

> The simplest solution I can think about now is adding a "subPath" property to VolumeMount. This would allow some nice things like using one volume for multiple mounts. For instance, a LAMP stack pod could be implemented this way:

Precisely.  Define the default as "" in which case the implementation
will decide what to do.

> This should solve the "number of mounts" issue since the PVC will be mapped to a unique folder like /var/lib/kubelet/plugins/kubernetes.io/rbd/rbd/volumes-image-xxx for the RBD case.

I think the implementation still needs to be per-pod, just that the
volume spec we pass to docker includes the volume driver's GetPath() +
the subPath field.  We still don't want to share PVCs across pods.

**Comment by thockin** [comment]
good question.  I think the Docker behavior is to create it, and I think
that's correct.

**Comment by MikaelCluseau** [comment]
@parikhyash yes, docker autmatically creates the folder.

@thockin "I don't think you can delete lost+found :)" you can but it's recreated by fsck. I don't care if it's recreated after my database is created ;-)

Sure, the backwards-compatible subPath will be "", so (hopefully) nothing breaks when we introduce this property.

**Comment by MikaelCluseau** [comment]
@thockin "We still don't want to share PVCs across pods". In the NFS case, I think the kernel is clever enough to use the already mounted "connection" if it receives multiple "mount host:/subdir".

**Comment by thockin** [comment]
The kernel can do what it wants :)  NFS is shared writable, so the semantic
is fine.

**Comment by MikaelCluseau** [comment]
Soooo we're all happy, let's do something. :)

**Comment by MikaelCluseau** [comment]
Do we expect subPath to be trusted or should I handle the case where someone puts "../../../../etc/shadow" in it?

**Comment by thockin** [comment]
It must be validated the same way that paths are validated for configMap -
must not start with / and must have no element that is ".."

**Comment by MikaelCluseau** [comment]
Upload took forever, sorry. The PR lacks all the API-change chain but I wanted to validate the idea before getting a size/L tag ;)

**Comment by MikaelCluseau** [comment]
Just for justice to the mysql docker: the issue was because the user put a single quote in the root password. The initialization code then fails, and Kubernetes restarts the container; thus the log looks like no initialization took place. It looks for a "mysql" folder in the volume, not for an empty volume. End of subject ;-)

**Comment by erinboyd** [comment]
Note, you can do this already by using the NFS plugin and directly specifying the path you want on the NFS server. So long as the export/permissions are appropriate you could do this for each claim you are wanting. @swagiaal @pmorie with the current dynamic supplemental group implementation is this going to be possible? I assume you will have to look at the permissions in the directory above or require the user to specify in the pod. And if they specify in the pod, will it actually be able to create that subdirectory?? Just throwing a few thoughts out there...

**Comment by jowy** [comment]
This feature would be great!

**Comment by MikaelCluseau** [comment]
@jowy yes, it's in #22575 (not merged yet).

**Comment by jowy** [comment]
Oh excellent news! Thank you!

**Comment by parikhyash** [comment]
@MikaelCluseau How is the reclaim policy handled for this? For example, in NFS persistent volumes, a 'recycle' reclaim policy should only scrub part of the volume for the corresponding subpath in the PVC and not the entire PV itself.

**Comment by MikaelCluseau** [comment]
@parikhyash The subPath is a property of the Container.VolumeMount (see https://github.com/kubernetes/kubernetes/issues/20466#issuecomment-192526797), not of the PVC, so the PV will only be reclaimed as now, when no-one uses it anymore.

**Comment by thockin** [comment]
This seems to be resolved now?

**Comment by zchef2k** [comment]
Pardon the late response here, but can someone offer up some definitions for PVCs at the subpath level? Conceptually this makes sense and I get it. I'm struggling though, practically. Any help is greatly appreciated.

**Comment by MikaelCluseau** [comment]
@zchef2k does this helps? https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath

**Comment by fiatala** [comment]
Apologies for commenting on the dead thread, but I wanted to ask here before creating a new issue/request. Is there any way for the subPath to be dynamic per pod? I know it's a string and not a mapping, but supporting the downward API variables would provide a good way to share storage and avoid collisions.
Centralized log storage is one use case.
If there's another way to do something like this, I haven't been able to find it.

```
        volumeMounts:
        - mountPath: /var/log/mysql
          name: logs
          subPath:
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      volumes:
      - name: logs
        hostPath:
          path: /mnt/log-repo
```

Over time, the host storage would look something like this, and the containers would not need to change any of their logging logic.
```
/mnt/log-repo/mysql-113110829-v53jf
/mnt/log-repo/mysql-1174854418-plsf8
/mnt/log-repo/mysql-3521978760-s1m6x
```

**Comment by thockin** [comment]
Open a new issue.  It's not a terrible idea.

**Comment by redbaron** [comment]
@thockin , there is a PR to have  this dynamic subpath which is blocked since July :( https://github.com/kubernetes/kubernetes/pull/49388
