### ISSUE TITLE
Is the way of running iptables rules too slow?

### ISSUE THREAD

**Issue by qq690388648** [kubernetes/kubernetes#20479]
By reading the [code](https://github.com/kubernetes/kubernetes/blob/65c285f5ab32283420e6fd5ac481ab1d94ebae90/pkg/util/iptables/iptables.go#L376), we can find that the <code>kube-proxy</code> ensuring proxy rules by running <code>iptables</code> rules one by one.
So if we have 100 services in our cluster and each service has 2 node ports,  then they will generated 800 <code>iptables</code> rules which will take 40s to flush all rules once(writing one rules to iptables need about 50ms). It is really a big time consuming and cause the low speed of <code>proxy</code> creating.
Is there any where we can optimize so that the time spend for flushing iptables can be reduced?

**Comment by thockin** [comment]
The newer iptables proxier does it with iptables-save and
iptables-restore.  We did not retrofit the userspace proxier to do this,
but we could.  I hope that the userspace proxier can die out this year, so
it may not be worth large investments.

**Comment by qq690388648** [comment]
@thockin If I did not misunderstand, what you mean is that the newer iptables proxier does not have the problem of iptables rules flushing slowly, and the older userspace proxier does not have solution to that problem. Is that correct?

**Comment by AdoHe** [comment]
@qq690388648 we are going to replace the userspace proxier with iptables proxier.

**Comment by thockin** [comment]
That is my feeling.

**Comment by qq690388648** [comment]
@AdoHe  Understood!
Thanks again!

**Comment by thockin** [comment]
I've been thinking about this more.  There is value in having the userspace proxy as a fallback, so if someone wanted to fix this, I would help shepherd it.  I'll open a new help-wanted bug

**Comment by qq690388648** [comment]
Fix this? Did you mean changing the way of flushing iptables rule to batching in userspace proxy mode?

**Comment by thockin** [comment]
yes - I am scared of changing the userspace proxy, but I suspect it will be
around for a while, so making it perform better is attractive, as long as
the improvement is significant (and it is)

**Comment by qq690388648** [comment]
Understood!

**Comment by AdoHe** [comment]
Just refer #20567
