### ISSUE TITLE
Problem using Auth0 in Kubernetes OIDC Authentication

### ISSUE THREAD

**Issue by madziefe** [kubernetes/kubernetes#20476]
Kubernetes v1.1.2 and v1.1.4
 
I'm trying to use Auth0 in K8s Authentication.
And have come across this issue. 

apiserver.yaml
```
    - --oidc-issuer-url=https://sample.auth0.com
    - --oidc-client-id=CLIENT_SECRET_HERE
```

apiserver logs 
```
E0202 02:54:58.223319       1 oidc.go:99] Failed to fetch provider config, trying again in 3s: "issuer" in config (https://sample.auth0.com/) does not match provided issuer URL (https://sample.auth0.com)
```
it was able to check the openid configuration using the above url + /.well-known/openid-configuration in the k8s oidc codes
```
https://sample.auth0.com/.well-known/openid-configuration

and fails after comparing the retrieved  issuer from auth0 = "https://sample.auth0.com/"  and the defined issuer in the apiserver
```

Auth0 known configuration 
```
https://sample.auth0.com/.well-known/openid-configuration

{"issuer":"https://sample.auth0.com/","authorization_endpoint":"https://sample.auth0.com/authorize","token_endpoint":"https://sample.auth0.com/oauth/token","userinfo_endpoint":"https://sample.auth0.com/userinfo","jwks_uri":"https://sample.auth0.com/.well-known/jwks.json","scopes_supported":["openid","profile","offline_access","name","given_name","family_name","nickname","email","email_verified","picture","created_at","identities","phone","address"],"response_types_supported":["code","token","code token"],"response_modes_supported":["query","fragment","form_post"],"subject_types_supported":["public"],"id_token_signing_alg_values_supported":["HS256","RS256"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"],"claims_supported":["aud","auth_time","created_at","email","email_verified","exp","family_name","given_name","iat","identities","iss","name","nickname","phone_number","picture","sub"]}

```

Changing oidc-issuer-url to ` https://sample.auth0.com/ `will result to 
```
E0202 05:59:21.796520       1 oidc.go:99] Failed to fetch provider config, trying again in 3s: invalid character 'C' looking for beginning of value
```
Apparently, k8s is calling this link
```
https://sample.auth0.com//.well-known/openid-configuration

Cannot GET //.well-known/openid-configuration
```

**Comment by davidopp** [comment]
@erictune Can you take a look at this?

**Comment by erictune** [comment]
@yifan-gu you added this module.  Also @bobbyrullo seems to know about OIDC too.

**Comment by erictune** [comment]
Seems like the problem might be in Godeps/_workspace/src/github.com/coreos/go-oidc/oidc/provider.go

**Comment by erictune** [comment]
Looks like Google accepts `https://accounts.google.com//.well-known/openid-configuration` but auth-0 doesn't.  Maybe we didn't notice it before for that reason?

**Comment by erictune** [comment]
A fix might be to strip any trailing slash on `issuerURL` at line 90 in `plugin/pkg/auth/authenticator/token/oidc/oidc.go` before calling `oidc.FetchProviderConfig(hc, issuerURL)`

I can't code this up and test it any time in the next week as I need to finish other stuff for the 1.2 release.   Please send a PR if that is something you are comfortable doing.

**Comment by madziefe** [comment]
thanks @yifan-gu and @erictune
