### ISSUE TITLE
Kubelet: Add unit test for PodSyncResult and convertStatusToAPIStatus

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#20478]
We moved **reason cache** and **status convert function** from `dockertools` to `kubelet` by #18172, #19579, #20192 and #20205.

After this, we should also migrate related old unit test to kubelet level.

For `PodSyncResult` we should add test for:
- [x] Different image pull policy.
- [x] Pod creation failure.
- [x] Pod image failure. 

For `convertStatusToAPIStatus` we should add test for:
- [ ] ContainerStatuses order.
- [ ] Last termination state.
- [ ] How reason cache will affect the PodPhase:
  - [ ] Pull image failure reason
  - [ ] Pod creation failure reason

**Comment by yujuhong** [comment]
Time to close this issue? :)

**Comment by Random-Liu** [comment]
Not yet, The last 3 tests are in #21224. :)
