### ISSUE TITLE
Kubeproxy should always apply latest snapshot

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20470]
This bug is mostly to document the flow that most likely leads to the latency observed in https://github.com/kubernetes/kubernetes/issues/20402.

1. Watch comes in, sends an update/add/del to proxiers api source: https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/config/api.go#L56
2. ApiSource snapshots all services or endpoints and shoves them in a channel: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/undelta_store.go#L57
3. Merger pulls out of this channel, inserts into shared map, and sends notification down the update channel: https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/config/config.go#L156
4. Proxy notices update, invokes `OnService/EndpointUpdate`: https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/config/config.go#L276

If running OnEndpointsUpdate takes 100ms during which 4 other endpoints come down the watch, we'll perform 1-4 for each. Instead, if the update channel in step 3 is full we can just go back to pulling out new watch snapshots from 1. This will drop intermediate updates.

**Comment by AdoHe** [comment]
I am willing to do a more deep investigate.

**Comment by bprashanth** [comment]
Sure, @adohe i have a pending pr that does some small amount of performance cleanup https://github.com/kubernetes/kubernetes/pull/20471. The larger issue is: if i push services through, does the kube-proxy lag, and why? Suggest the following steps:
1. Start with the service latency test, and see (via log lines) how long it takes for the Nth service to get created
2. How long it takes to switch the last service to type=NodePort and have that reflect on all nodes. 
We're seeing various cases of flake where it's taking upto 60s to open up a node port of a service.

**Comment by bprashanth** [comment]
@AdoHe actually spare cycles will be better spent debugging https://github.com/kubernetes/kubernetes/issues/20547 since no-ones looked at it yet, if you can :)
