### ISSUE TITLE
Document which cloud providers support external load balancers

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#20472]
This was a source of user confusion:
http://stackoverflow.com/questions/34057711/external-ip-is-none-after-expose-my-service/35144573#35144573

It is not documented in the obvious place:
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md#type-loadbalancer

**Comment by bgrant0607** [comment]
/remove-lifecycle stale
/lifecycle frozen 

There should be a way to query the system regarding whether features like this are functional

**Comment by adeniyistephen** [comment]
@bgrant0607 Hi, I would really love to work on this, please kindly provide input and pointers for the documentation. Thanks
