### ISSUE TITLE
GCE upgrade tests are leaking addresses

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20489]
GCE upgrade tests are leaking addresses, target pools, and forwarding rules, but I'm not sure where yet.  We've seen plenty of these before, I'm filing another issue since this is for GCE.  (Similar to #13515)

**Comment by ihmccreery** [comment]
Of course, would like to see #18119 in the long-run to make this easier to debug.

**Comment by davidopp** [comment]
@mikedanese is there a chance you could look into this after the feature freeze?

Do you know when was the last time the GCE upgrade tests were passing?

**Comment by mikedanese** [comment]
Yes I can take a look next week

**Comment by davidopp** [comment]
Awesome. Ike, I'm going to reassign to Mike.

**Comment by mikedanese** [comment]
I'm looking at this now. Will update today.

**Comment by mikedanese** [comment]
I manually cleaned up the rules and will continue to monitor. There were a few leaks detected in master over the last couple of months. I'm hoping that they were plugged but never cleaned up in this project.

**Comment by mikedanese** [comment]
After two days of observation, it appears the leak is fixed. I attribute this to a leak on master that was plugged (e.g. #20098) and that we never cleaned up in gce-upgrade.
