### ISSUE TITLE
Slice shallow copy in registrytest/service.go

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#2049]
pkg/registry/registrytest/service.go ~L60 does a shallow copy, and ends up aliasing slices.

**Comment by gitfred** [comment]
Is this bug still valid?

**Comment by thockin** [comment]
yes, but now it in L78:

```
*r.Service = *svc
```

This is not a huge deal, but it is wrong.  It should call `api.DeepCopy_api_Service`

**Comment by gitfred** [comment]
ok I'll fix it
