### ISSUE TITLE
kubectl --record should avoid capturing secrets on the command line

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#20508]
Follow up #20035

https://github.com/kubernetes/kubernetes/pull/20035#issuecomment-177235273:

>  @smarterclayton: We need to be careful that security information does not get added to this annotation. I don't expect users would be surprised that --record records the command, but they would be surprised if we stored passwords or other attributes. (For example, --password, --token, possibly --username.)

@kubernetes/kubectl

**Comment by liggitt** [comment]
I think this is higher priority than p2, given the security implications

**Comment by ymqytw** [comment]
Any suggestions about how to fix this issue?

**Comment by pacoxu** [comment]
`--record` started to be deprecated in 1.22 since #102873. 
We may close this one. Discussions in #40422.
