### ISSUE TITLE
unit flake: TestCNIPlugin

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#20503]
Previous issues: #15239, #14931

Failure log: https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-test-go-release-1.1/3478

Test result:
```
Error Message

Failed
Stacktrace

cni_test.go:175: Failed to select the desired plugin: Network plugin "cni" not found.
```

**Comment by bprashanth** [comment]
@jlowdermilk do we periodically cleanup /tmp on the machines the unittests run on?

**Comment by jlowdermilk** [comment]
I think we do clean out /tmp, but I don't know if it can happen during the test. @ixdy, @spxtr, @ihmccreery could better answer.

**Comment by ixdy** [comment]
This is `release-1.1`, so these tests are all using a [hard-coded path](https://github.com/kubernetes/kubernetes/blob/release-1.1/pkg/kubelet/network/cni/cni_test.go#L44-L45).

Most likely a test case running in parallel is deleting the files.

**Comment by ixdy** [comment]
Since unit tests are running in a container, separate test runs or processes on Jenkins shouldn't affect a given run.

**Comment by bprashanth** [comment]
How come we only seem to have collected the xml files from http://kubekins.dls.corp.google.com/job/kubernetes-test-go-release-1.1/3478/console ? don't we usually grab stdout as well

**Comment by ixdy** [comment]
The [PR to save stdout](https://github.com/kubernetes/kubernetes/pull/15129) landed in `master` but not `release-1.1`.

**Comment by bprashanth** [comment]
> Most likely a test case running in parallel is deleting the files.

So can this happen on 1.1? or unitests run in containers everywhere

**Comment by ixdy** [comment]
Unit tests run in containers, but [we pass -p=2](https://github.com/kubernetes/kubernetes/blob/release-1.1/hack/jenkins/test-dockerized.sh#L52) to `go test`, so it's possible that two test cases in the same run could be colliding.

**Comment by bprashanth** [comment]
ick. thanks for the answers.

**Comment by bprashanth** [comment]
Cherrypick was merged so I'm closing this
