### ISSUE TITLE
With iptables proxy, rolling updates do not always seem to work as expected.

### ISSUE THREAD

**Issue by maclof** [kubernetes/kubernetes#20521]
I am trying to reproduce this issue for testing, but in my production environment with the iptables proxy, rolling updates do not always seem to work, causing our nginx proxy to 504 timeout when connecting to a service ip.

We have had to temporarily switch back to the userspace proxy as rolling updates are key to our app deployments.

@thockin

**Comment by thockin** [comment]
More details?  Is it that propagation of endpoint changes is happening, but
too slowly?  Or is propagation not happening?

**Comment by maclof** [comment]
I haven't really seen this issue since I've upgraded to 1.2, so will close it for now.
