### ISSUE TITLE
Investigate load balancer pod failure in gce / coreos / rkt environment

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#20529]
cc/ @yifan-gu for more detail information.

**Comment by yifan-gu** [comment]
cc @sjpotter This is solved when dns works correctly, right? Ref https://github.com/kubernetes/kubernetes/pull/20302

**Comment by sjpotter** [comment]
yes, but I have had a terrible time testing anything in GCE today, I
figured out what the problem is, it seems when docker tries to start up
many times there's a problem with a bridge device and the docker unit just
keep restarting and the master never makes any progress.

**Comment by yifan-gu** [comment]
I believe this is fixed after #20302 , so closing for now.
