### ISSUE TITLE
master and minion conflict wrt flannel in cluster/ubuntu/util.sh

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#20522]
When a node is both master and minion --- that is, the `provision-masterandnode` function in `util.sh` is invoked, the flannel files for both master and minion are copied to the same node.  That looks bad, the file names are the same but the contents are different.

**Comment by MikeSpreitzer** [comment]
@zmerlynn Can you please confirm this?  I think the resolution will be easy, it will mainly be a matter of removing duplication and resolving to let upstart make flannel follow etcd on such a combined machine (just as it does on a pure worker machine).

**Comment by MikeSpreitzer** [comment]
FYI, I noticed this while working on https://github.com/MikeSpreitzer/kubernetes/commit/7df8d2c114746d348b3a9329a0d48aff82f980b6 (to resolve issue #20292)

**Comment by MikeSpreitzer** [comment]
This is has been idle for almost a week, should I expect some action to be taken?
I am considering creating a PR myself, but would like some confirmation from other experts about the cluster/ubuntu scripting to confirm that I am on the right track.

**Comment by dalanlan** [comment]
@MikeSpreitzer  
Yes you're right. 
As to flannel, the scripts and configuration files of minion node, however, would overwrite the one of master role, by which i mean, it works expectedly if the order of copying files stand where it is.

**Comment by MikeSpreitzer** [comment]
Yes, the current scripting causes the minion version to overwrite the master version in this case.  That means that on a machine that is both master and worker, the Flannel daemon is *NOT* started after etcd but rather based on the condition `(net-device-up and local-filesystems and runlevel [2345])`.  Is that really what we want?  I expect that on a machine playing both roles, the Flannel daemon should start after etcd.  Or is it safe to start the Flannel daemon earlier than that?

**Comment by dalanlan** [comment]
Ah, i made a mistake. On the contrary, the master's role overwrites the minion one. So flannel is started based on etcd.

**Comment by MikeSpreitzer** [comment]
Oh, I was wrong about which overwrites which.  Yes, the master config prevails on a machine playing both roles --- which produces the desired result.
