### ISSUE TITLE
Client library should support patch

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#20527]
Since it's supported by the API, we'd like to use it in kubectl (#20437), and [users find Update confusing](https://groups.google.com/forum/#!topic/google-containers/_kCOnibZEqs). 

We should probably rename "Update" to "Replace", also, as we did in kubectl.

cc @lavalamp @caesarxuchao @soltysh @kargakis

**Comment by kargakis** [comment]
I was thinking about this and I totally agree. We already use it in a couple of places in the client (kubectl label, annotate, edit) and it would be more convenient to provide it as part of the client interface.

**Comment by lavalamp** [comment]
Heh, I was just telling @krousey that patch was a good reason to want to do updates with the dynamic client he's working on. It would be nifty if we made it convenient to do patches with the Unstructured objects.

**Comment by lavalamp** [comment]
@caesarxuchao Maybe we can also think about adding a Patch method to the generated clients. I can imagine taking a json patch directly, or maybe it'd be convenient if we let people pass an old and new object and the client library could produce the patch automatically.

**Comment by caesarxuchao** [comment]
We have an example of Patch for event: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/typed/generated/legacy/unversioned/event_expansion.go#L79, it's taking a json patch directly. We can start with that.

**Comment by caesarxuchao** [comment]
Client library supports patch now: https://github.com/kubernetes/client-go/blob/master/1.4/kubernetes/typed/core/v1/pod.go#L154.

Is there anything left in this issue?

**Comment by lavalamp** [comment]
I think the next step here is probably to add a bit where you send the server the old object and the new object, and the server computes the patch and then applies it.
