### ISSUE TITLE
hack/update-codegen.sh doesn't correctly generate expansions

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#20549]
During #20544, I found that when I added client generation for a new type, the `Expansion` type for that type was not generated correctly, and I had to add:

``` go
type ConfigMapExpansion interface{}
```

to `pkg/client/typed/generated/legacy/unversioned/generated_expansion.go`

**Comment by pmorie** [comment]
@pweil- I wonder if you're hitting this.

**Comment by pmorie** [comment]
a new flavor of it, anyway

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
