### ISSUE TITLE
service account kube-system/default was not found in ubuntu

### ISSUE THREAD

**Issue by yossi-cohen** [kubernetes/kubernetes#20556]
hi 

i'm trying to run with k8s version 1.1.7 
i updated config-default  script and removed DenyEscalatingExec key from ADMISSION_CONTROL(otherwise its not working)

after that i tried to run kube-ui (or any other pod with kube-system namespace)  without any success 

in  kube-controller-manager.log  i saw the following error 

**unable to create pod replica: Pod "kube-ui-v4-" is forbidden: service account kube-system/default was not found, retry after the service account is created**

i googled it  and  found the following  solution 

> Generate a signing key:
> 
> openssl genrsa -out /tmp/serviceaccount.key 2048
> Update /etc/kubernetes/apiserver:
> 
> KUBE_API_ARGS="--service_account_key_file=/tmp/serviceaccount.key"
> Update /etc/kubernetes/controller-manager:
> 
> KUBE_CONTROLLER_MANAGER_ARGS="--service_account_private_key_file=/etc/kubernetes/serviceaccount.key"

but  i couldn't found the keys in the config files 

 i tried to update util.sh 

and set the following flags (thats the only places that i found those keys)
--tls-private-key-file=/etc/kubernetes/serviceaccount.key"
--service-account-private-key-file=/etc/kubernetes/serviceaccount.key \

note: doing **kubectl serviceaccount** for default namespace returns 1 entry 
BUT **kubectl serviceaccount --namespace=kube-system** returns NO ENTRIES!

i'm really desperate :) does anyone have a  clue how to fix this issue 

tks a lot

**Comment by maty21** [comment]
me and @yossi-cohen  solved it by creating kube-system namespace before, so you can close that issue. 
in my opinion the main problem here is that kube-system namespace is not created by default
