### ISSUE TITLE
FakeClient DeleteCollection is reporting the wrong resource for all clients

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#20568]
See an example:
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/typed/generated/legacy/unversioned/fake/fake_limitrange.go#L60

@lavalamp @caesarxuchao

**Comment by derekwaynecarr** [comment]
Putting together a fix now.

**Comment by lavalamp** [comment]
@caesarxuchao

**Comment by caesarxuchao** [comment]
LGTMed the PR. Thanks!
