### ISSUE TITLE
No e2e coverage for auto-provisioned volumes

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#20564]
I'm excited to see that auto-provisioned volumes are going to be in 1.2 (even if in alpha), but AFAICT there's no e2e coverage yet.

**Comment by markturansky** [comment]
@kubernetes/rh-storage

**Comment by jsafrane** [comment]
Assign it to me, I have something almost ready, but I cannot post it before all provisioning and binding errors are fixed - the test would generate lot of flakes.

I need these two fixed first: https://github.com/kubernetes/kubernetes/pull/20213 https://github.com/kubernetes/kubernetes/pull/19868

**Comment by markturansky** [comment]
Thanks @jsafrane. Assigned.

You can cherry-pick your PRs into your branch w/ the e2e test.  You'll also need to work around this:  https://github.com/kubernetes/kubernetes/pull/19995#discussion_r52600326

Once those PRs get merged, the commits you cherry-picked should fall out on rebase.

**Comment by jsafrane** [comment]
Fixed by #21140 - can anyone close this issue?

**Comment by eparis** [comment]
I will close. If you put `fixes #20564` or `resolves #20564` in the FIRST comment of the PR, github will close it automatically when the PR merges.
