### ISSUE TITLE
Return valid API paths for GET /api/<version>

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2057]
Forked from #1052.

`GET /api` now returns valid API versions. `GET /api/<version>` should return valid API paths (collections, operations, etc.), similar to how `GET /api/<version>/<collection>` returns the list of objects belonging to that collection. This would at least make the API somewhat discoverable.

/cc @smarterclayton @lavalamp

**Comment by nikhiljindal** [comment]
swagger-ui now explains all the available resources and the available operations (GET, POST, DELETE, etc). It also provides a playground where users can try out these operations.

Once https://github.com/GoogleCloudPlatform/kubernetes/pull/3548 is merged, we will also get a list of all the valid paths on apiserver.

I assume thats all what we wanted.
Let me know if there is anything else required or else I will close this issue once https://github.com/GoogleCloudPlatform/kubernetes/pull/3548 is merged

**Comment by bgrant0607** [comment]
@nikhiljindal This issue was about returning information when specific path prefixes were operated upon, or at least documenting the expected behavior.

**Comment by bgrant0607** [comment]
The lack of this API makes it hard to inspect/update every object. See, for instance, #7819.

**Comment by nikhiljindal** [comment]
Proposal:

If the requested path is not a valid API path, but it is a prefix of a valid API path, then the apiserver should return all API paths that have the requested path as a prefix. Else apiserver can return a 404 resource not found.
For ex:
On accessing /api/v1beta3/, server should return all valid paths with /api/v1beta3 as prefix.
On accessing /api/v1beta3/pods/, the expected GET API operation happens.
On accessing /api/v1beta3/something a 404 is returned.

https://github.com/GoogleCloudPlatform/kubernetes/pull/7883

**Comment by bgrant0607** [comment]
Resolved by api groups discovery API.

cc @caesarxuchao @lavalamp
