### ISSUE TITLE
Kubelet should not rely on containerID for termination message detection.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#20583]
Now kubelet creates the container log by joining `(pod metadata)+(container name)+(containerID)` [(here)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L731), and then mount it to container by adding it to `bind` in `HostConfig` [(here)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L739), and pass it to container when start [(here)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L775).

It means that we could only creating container log directory after `create` the container, because we can only get `containerID` after creating it. [(here)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L714)

However, as is mentioned in issue #20454, `HostConfig` at container start will be deprecated from 1.10, and will be completely removed by 1.12. Although for 1.10 we could still use it, there will be quite a lot of annoying warning log in `docker.log`:
```
time="2016-02-03T20:28:57.867598821Z" level=warning msg="DEPRECATED: Setting host configuration options whe
n the container starts is deprecated and will be removed in Docker 1.12"
time="2016-02-03T20:28:58.330340910Z" level=warning msg="DEPRECATED: Setting host configuration options whe
n the container starts is deprecated and will be removed in Docker 1.12"
time="2016-02-03T20:39:38.184004120Z" level=warning msg="DEPRECATED: Setting host configuration options whe
n the container starts is deprecated and will be removed in Docker 1.12"
time="2016-02-03T20:39:38.624884402Z" level=warning msg="DEPRECATED: Setting host configuration options whe
n the container starts is deprecated and will be removed in Docker 1.12"
```

So after 1.12 we could only pass `HostConfig` to container create. If so, we should
  * not rely on containerID when creating the container log directory
  * Or, find some other ways to mount directory to container after it is created but not started.

/cc @kubernetes/sig-node

**Comment by Random-Liu** [comment]
Also ref #19720

**Comment by vishh** [comment]
A few ways to address this will be,
1. Get support for lifecycle hooks in docker :)
2. Use the container Name instead of container ID. Since each path element cannot be longer than 255 characters, we might have to reverse the container name to preserve uniqueness.

**Comment by vishh** [comment]
FYI: This issue is related to Kubelet's Termination Message collection feature.

**Comment by Random-Liu** [comment]
@vishh Thanks, :)

**Comment by Random-Liu** [comment]
@vishh I'll try to go with the second solution. :) Thanks

**Comment by dchen1107** [comment]
@Random-Liu the second solution doesn't work with Kubelet's Termination Message here.

**Comment by Random-Liu** [comment]
@dchen1107 Why?

**Comment by Random-Liu** [comment]
Close this since #20615 is merged.

**Comment by Random-Liu** [comment]
Reopen this issue, since #20615 is reverted

**Comment by yifan-gu** [comment]
I think it's because we don't want a restarted container to override the old one's termination message.
What I did for rkt (as I can't get containerID when creating the pod) is to generate a random UID, and store this message as an annotation of the rkt pod.

**Comment by Random-Liu** [comment]
Yeah, I went similar way with you for this issue. Thanks a lot! :)
