### ISSUE TITLE
kube-proxy userspace should use iptables-save and iptables-restore

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20589]
The current rule-by-rule update is slow and painful, and may be contributing to overall flakiness of tests.  It is valuable to have the userspace proxier for a while longer, so we should probably convert it to use save/restore like the iptables proxier does.

This is not too hard I think, and a good chance for community contributions.  I am happy to help shepherd.

**Comment by mqliang** [comment]
I volunteer myself to do this work.

**Comment by thockin** [comment]
Sounds great!  The word of the day is caution - we have to be very careful
not to destabilize it.  I would love to see it broken down into a series of
commits, so it's super easy to review.

Tim
