### ISSUE TITLE
#20098 causes e2e warning; passing zone instead of region

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#20593]
@brendandburns I think this line is passing a zone where it should pass a region:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/util.go#L2826

```
list, err := service.ForwardingRules.List(project, zone).Do()
```

e.g. https://github.com/kubernetes/kubernetes/pull/15938#issuecomment-179502676

```
Feb  3 13:24:51.648: INFO: Failed to delete cloud resources for service: 104.197.185.91 19482 (googleapi: Error 400: Invalid value for field 'region': 'us-central1-f'.  Unknown region., invalid)
STEP: stopping RC webserver in namespace e2e-tests-services-gb3yh
```

(Haven't yet figured out if this is actually a failed test or just a failed cleanup)

**Comment by justinsb** [comment]
Ah; I think this is only hit if the test has already failed (timed out waiting for the LoadBalancer to go away).  So it won't be the cause of an e2e failure.

**Comment by thockin** [comment]
yeah, it's passing a zone.  I have a fix as part of another PR.
