### ISSUE TITLE
e2e failures: heapster containers with unready status

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#20602]
On the serial and soak test suites, it looks like one or more containers in the heapster pod are crashlooping or failing in some way. The following suites have been failing/timing out

[kubernetes-e2e-gce-serial](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-serial/): [375](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/375), [374](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/374)

[kubernetes-e2e-gke-serial](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-serial/): [403](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/403), [402](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/402),

[kubernetes-soak-continuous-e2e-gce](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gce/): [4461](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-soak-continuous-e2e-gce/4461), [4460](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-soak-continuous-e2e-gce/4460)

[kubernetes-soak-continuous-e2e-gke](http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-soak-continuous-e2e-gke/): [5806](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-soak-continuous-e2e-gke/5806), [5805](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-soak-continuous-e2e-gke/5805), 

Looking at console logs for each, I see log lines sprinkled throughout about heapster being unready, either the entire pod or 1 or 2 containers

[kubernetes-e2e-gce-serial/375](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/375) timed out with heapster failing to come back after a resize test.
```
09:26:48 Feb  3 09:26:48.888: INFO: heapster-v13-fo6ny                            e2e-serial-minion-tov9  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-03 09:22:03 -0800 PST ContainersNotReady containers with unready status: [heapster eventer]}]
09:26:48 Feb  3 09:26:48.888: INFO: kibana-logging-v1-045z7                       e2e-serial-minion-yhay  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-03 09:26:15 -0800 PST ContainersNotReady containers with unready status: [kibana-logging]}]
...
09:26:50 • Failure in Spec Teardown (AfterEach) [335.805 seconds]
09:26:50 Nodes [Disruptive]
09:26:50 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:710
09:26:50   Resize [Slow]
09:26:50   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:548
09:26:50     should be able to delete nodes [AfterEach]
09:26:50     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:521
09:26:50 
09:26:50     Expected error:
09:26:50         <*errors.errorString | 0xc821c2ef30>: {
09:26:50             s: "Not all pods in namespace 'kube-system' running and ready within 2m0s",
09:26:50         }
09:26:50         Not all pods in namespace 'kube-system' running and ready within 2m0s
09:26:50     not to have occurred
09:26:50 
09:26:50     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:498
```

[kubernetes-soak-continuous-e2e-gce/4464](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-soak-continuous-e2e-gce/4464) has all tests failing because kube-system pods aren't all running
```
14:53:06 Feb  3 14:53:06.121: INFO: 10 / 12 pods in namespace 'kube-system' are running and ready (576 seconds elapsed)
14:53:06 Feb  3 14:53:06.121: INFO: expected 8 pod replicas in namespace 'kube-system', 6 are Running and Ready.
14:53:06 Feb  3 14:53:06.121: INFO: POD                                   NODE                         PHASE    GRACE  CONDITIONS
14:53:06 Feb  3 14:53:06.121: INFO: heapster-v13-zm56t                    gce-soak-weekly-minion-lvj8  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-03 14:50:30 -0800 PST ContainersNotReady containers with unready status: [heapster eventer]}]
14:53:06 Feb  3 14:53:06.121: INFO: monitoring-influxdb-grafana-v3-wsjco  gce-soak-weekly-minion-lvj8  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-03 14:49:04 -0800 PST ContainersNotReady containers with unready status: [influxdb]}]
```

Might be worth investigating if there is a systemic problem with heapster.

cc @saad-ali, @dchen1107

**Comment by yujuhong** [comment]
Also see #20100

**Comment by saad-ali** [comment]
@vishh

**Comment by vishh** [comment]
cc @mwielgus @piosz. Heapster image was updated recently. #20406

**Comment by thockin** [comment]
Prio on this?  @mwielgus @piosz

**Comment by piosz** [comment]
We bumped Heapster version recently #20650 which should help for this problem.

**Comment by piosz** [comment]
I'll take a look whether our changes in Heapster helped.

**Comment by piosz** [comment]
After our recent changes and bumping Heapster to the new version #20650 the Heapster is no longer the problem. There are still some issues with influxdb. Closing in favor of #20247 

cc @fgrzadkowski
