### ISSUE TITLE
Why does not GCE salt process use ntp?

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#20616]
As the subject say, I am curious why does not the GCE salt process use ntp.

**Comment by mikedanese** [comment]
Guest gce images are configured by default to use Google's internal NTP service so we don't need to do anything special with salt. Cool blog post: https://googleblog.blogspot.com/2011/09/time-technology-and-leaping-seconds.html

**Comment by mikedanese** [comment]
metadata.google.internal is an ntp server and is resolvable in a gce network

**Comment by codefx9** [comment]
Thanks for the info. It makes sense. I would probably change the `top.sls` file to only avoid install ntp for gce and gke.
