### ISSUE TITLE
Why does GCE salt setup does not use master-minion mode?

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#20617]
GCE salt setup scripts uses `--local` mode. Is there a reason, GCE scripts does not use master-minion salt mode?

**Comment by mikedanese** [comment]
Security and reliablity. #5112

**Comment by codefx9** [comment]
Thanks for the answer. Regarding security, how do you think anyone who has a large cluster in GCE upgrade things in place when a new vulnerability is exposed? Also, how does one does basic things like rotating keys etc, without a a master-minion salt setup in GCE? Does not that leave GCE cluster more vulnerable in the long run?
