### ISSUE TITLE
Push kube-cross to somewhere public so it can be used to host build tools

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#20610]
Some upcoming tools will be part of the build chain that are onerous for developers to build (protoc, grpc, etc).  Those binaries can be built as part of kube-cross, but today the image is not published so every developer has to build it themselves.  If we could push the image periodically publicly, we could use it (appropriately tagged) in both dev and build time scenarios, such as when developers need to run `hack/update-generated-protobufs.sh` and have some confidence all developers get a similar experience first time.

**Comment by ixdy** [comment]
@zmerlynn is there a reason we don't publish this? is it just because this predated gcr.io?

**Comment by ixdy** [comment]
cc @david-mcmahon

**Comment by zmerlynn** [comment]
No. I was thinking about this the other day and couldn't come up with a good reason, except airgapped environments. I think we still want the option to build from source (and go all the way through that way), so we might need a way to test that way as well. (Or we just keep Jenkins building that way, and we convert the dev workflow over to pull from gcr.io.)

**Comment by smarterclayton** [comment]
Dev workflow from gcr.io is fine - my preference is for formal build to
always build images from source unless there is a compelling reason not to.
