### ISSUE TITLE
Debian 8 support in GCE salt setup

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#20618]
Is there any plans to support Debian 8 in GCE setup scripts? How can I build a Debian 8 version of container-vm image? I have not found any scripts for building the container-vm images from raw Debian images.

**Comment by mikedanese** [comment]
Absolutely, it's just a bit of work to vet the upgrade. cc @dchen1107 @zmerlynn Are we tracking an upgrade to jessie anywehere?

**Comment by zmerlynn** [comment]
There are long discussions about moving `container-vm` to Jessie. Stay tuned, and sorry it's not already supported.
