### ISSUE TITLE
Write a test for NodeController rate limiting.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#20639]
Ref. #19124 

cc @davidopp @bgrant0607 @wojtek-t @fgrzadkowski @smarterclayton @quinton-hoole

**Comment by kargakis** [comment]
@kubernetes/sig-scalability-misc

**Comment by gmarek** [comment]
It's out of the scope of sig scalability. @kubernetes/sig-scheduling-feature-requests is probably closer.
