### ISSUE TITLE
e2e flake: e2e-gce timed out because of "Services" test

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#20631]
00:10:00 Build was aborted
    00:10:00 [BeforeEach] Services
    ....
    00:10:00 STEP: hitting the UDP service's LoadBalancer
    00:10:00 Feb  3 23:54:11.232: INFO: Testing UDP reachability of udp://104.197.234.65:81
    00:10:00 Feb  3 23:54:16.232: INFO: Testing UDP reachability of udp://104.197.234.65:81
    00:10:00 Feb  3 23:54:20.232: INFO: Testing UDP reachability of udp://104.197.234.65:81
    00:10:00 Feb  3 23:54:24.232: INFO: Testing UDP reachability of udp://104.197.234.65:81
    00:10:00 Feb  3 23:54:28.232: INFO: Testing UDP reachability of udp://104.197.234.65:81
    00:10:00 Feb  3 23:54:32.232: INFO: Testing UDP reachability of udp://104.197.234.65:81
    00:10:00 Feb  3 23:54:32.235: INFO: Successfully reached udp://104.197.234.65:81
    00:10:00 STEP: changing TCP service mutability-test back to type=ClusterIP
    00:10:00 Feb  3 23:54:32.242: INFO: Waiting up to 20m0s for service "mutability-test" to have no LoadBalancer
    00:10:00 
    00:10:00 ---------------------------------------------------------
    00:10:00 Received interrupt.  Running AfterSuite...

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/10928/?project=kubernetes-jenkins

http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gce/10928/consoleFull

@kubernetes/goog-cluster

**Comment by wojtek-t** [comment]
It may not be a flake - it failed in exactly the same way for the second time:
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gce/10929/console

**Comment by bprashanth** [comment]
It hung in both cases ~10-15m waiting for loadbalancer to disappear, might be https://github.com/kubernetes/kubernetes/issues/20547. @kubernetes/goog-testing looks like in the build timeout case we don't collect kubernetes daemon logs?

**Comment by thockin** [comment]
tastes like #20547?
