### ISSUE TITLE
If all Nodes are NotReady NodeController shouldn't evict Pods.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#20640]
Ref. #19124

We also should decide how to make sure that cluster can recover from such condition.

cc @davidopp @bgrant0607 @wojtek-t @fgrzadkowski @smarterclayton @quinton-hoole

**Comment by smarterclayton** [comment]
Probably should even be percentage based.  We've had users ask and build alternate plans around this - I think there's an expectation we do this already.

**Comment by quinton-hoole** [comment]
Yes, see #13430.  We already limit the number of pods that will be evicted.  Are you suggesting that we special-case the event where all nodes are unreachable, and reduce the limit to zero in such a case?

**Comment by bgrant0607** [comment]
Commented in another issue: https://github.com/kubernetes/kubernetes/issues/19124#issuecomment-180180996

**Comment by bgrant0607** [comment]
Certainly if there is nowhere for the pods to go, it doesn't help to evict them.

**Comment by davidopp** [comment]
Let's coalesce all the pod eviction rate-limiting discussion in #13430.
