### ISSUE TITLE
Decide if we want to act differently on Kubelet-driven node's problems.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#20641]
NodeController was written at the time when the only source of NotReady status was NodeController itself. It's no longer true and we may want to act upon this knowledge, by assuming that Kubelet-driven NotReady status is likely temporary and allow some more time to recover than normally.

cc @davidopp @bgrant0607 @wojtek-t @fgrzadkowski @smarterclayton @quinton-hoole @kubernetes/goog-node

**Comment by smarterclayton** [comment]
SGTM

**Comment by thockin** [comment]
What behaviors do you think would be different?

**Comment by gmarek** [comment]
Simplest one would be longer timeout. Or if we're feeling fancy we can even allow Kubelet to decide when it gives up.

**Comment by thockin** [comment]
So you are distinguishing "hurting" from "dead"?

**Comment by gmarek** [comment]
I'd put it differently, but yes.

**Comment by bgrant0607** [comment]
I originally proposed a distinct Reachable condition. Multiple conditions make sense

**Comment by quinton-hoole** [comment]
I don't have full context here, but I agree with Brian, distinguishing
between a kubelet declaring itself NotReady, and NodeController declaring
it unreachable makes a lot of sense.

**Comment by dchen1107** [comment]
Agreed with both @bgrant0607 and @quinton-hoole by distinguishing between Reachable and NotReady.

**Comment by thockin** [comment]
To be clear, I wasn't disagreeing, just clarifying :)
