### ISSUE TITLE
Controllers should define flags in their own codebase.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#20644]
Currently all flags are defined in the binary which makes a big mess. We need some way to deal with duplicate names.

cc @kubernetes/goog-control-plane

**Comment by AdoHe** [comment]
+1

**Comment by gmarek** [comment]
I'll send a PR tomorrow.

**Comment by mikedanese** [comment]
I will reapply #20702 or something similar when component config for controller-manager is merged.

**Comment by gmarek** [comment]
Thanks.

**Comment by gmarek** [comment]
/remove-lifecycle stale

@mikedanese - do have any idea who might do such a refactor?
