### ISSUE TITLE
[E2E] Add "k8s bot extended test this please" directive

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#20653]
For HPA, Density, Load, and other types of long running tests that may not run in CI, we should allow this directive in the comment dialogue.  OTherwise the only alternative is users spinning a cluster and manually running the extended tests/pasting the results. 

cc @kubernetes/sig-testing  @kubernetes/sig-scalability

**Comment by ihmccreery** [comment]
cc @kubernetes/goog-testing

**Comment by ixdy** [comment]
Seems like a reasonable proposal.

A few questions:
* PR e2e runs a limited subset of tests (non-flaky, non-serial, non-slow, non-disruptive, non-feature). What set of tests would this run? We could run everything that's non-flaky and non-feature (giving more coverage, taking many hours), though that's obviously still leaving out some stuff. If we wanted to test any features, that's a pretty large and growing set, so the list would probably require pretty continuous maintenance.
* If tests fail, should it block the merge of the PR? Or is just informational?

It'd be good to come up with estimates of how frequently we expect this to be used. We're already pretty close to our e2e quota limits as-is; we can always get more quota, but it's something to consider.

**Comment by ixdy** [comment]
other issue with feature tests is that some require either special kinds of resources or larger clusters.

**Comment by spiffxp** [comment]
The jenkins instance for PR's now has the ability to trigger a specific job given a specific trigger phrase.  Does this meet the ask in this issue?

eg for federation:
https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml#L489

eg for kubemark:
https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml#L559-L560

**Comment by spxtr** [comment]
I think this is still worth looking at. If we're adding a slow e2e test, for instance, it would be awesome to say some incantation and have it run the slow e2e tests.

**Comment by spiffxp** [comment]
/sig testing
/assign
I think it's time to close this or at least open over in test-infra if we still care
