### ISSUE TITLE
Investigate perf problems with go1.4.3 and go1.5.3

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#20656]
For background, see #20400. We had previously rolled forward to go1.4.3 when we standardized the go version we ran on, but that caused regressions. Then we put everything on go1.5.3. That was better, and it took us longer to notice the regressions, but it's still not as good as go1.4.2, which #20577 reverted us to.

Obviously we can't stay on go1.4.2 forever, so we need to dig in and understand what the cause was. Note it may be (probably is?) a different cause for go1.4.3 and go1.5.3...

@kubernetes/sig-scalability This was discussed this morning.

**Comment by timothysc** [comment]
@lavalamp , @smarterclayton had referenced what i believe is the root cause golang/go#14189 

Which is likely GC interference, under load.

**Comment by ixdy** [comment]
In the linked golang issue, they're comparing 1.5 and 1.6 to 1.4.3, though we noticed issues in 1.4.3 vs 1.4.2. Wonder if that's worth mentioning too?

**Comment by david-mcmahon** [comment]
Responding to my cc: on the parent bug, I don't claim to know all the details here, but If changes like this cause such havoc it's worth running "next go version" through a go-version-flag modified jenkins instance (or 5) to test go version upgrades in parallel (with normal HEAD testing).  This requires a flag for go version to be passed in and the jenkins instances set up of course.

**Comment by ixdy** [comment]
Based on https://github.com/golang/go/issues/14189 it's not clear that Go 1.6 is going to be any better for us right now, but we may want to try testing 1.6 to see what sort of numbers we get.

**Comment by ixdy** [comment]
@rsc comments in https://github.com/kubernetes/kubernetes/issues/17524#issuecomment-185987621:
> Hi, Go team here. David Crawshaw pointed this issue out to me. We'd really like to understand both this and the problems you found with Go 1.5. The problem with Go 1.4.3 is interesting because so little changed between Go 1.4.2 and Go 1.4.3. If there's a real regression there, perhaps it is the same one you hit trying Go 1.5, and there's a lot less to look through. Specifically:

>$ git log --oneline go1.4.2..go1.4.3
50eb39b [release-branch.go1.4] go1.4.3
5d9c280 [release-branch.go1.4] doc: document go1.4.3
cb65428 [release-branch.go1.4] net/http: backport some potential request smuggling vectors from Go 1.5
8f33959 [release-branch.go1.4] net/http: harden Server against request smuggling
8f42967 [release-branch.go1.4] net/textproto: don't treat spaces as hyphens in header keys
e938de2 [release-branch.go1.4] runtime: don't return a slice with nil ptr but non-zero len from growslice
a527bdb cmd/dist: remove -Werror from CFLAGS
$

> Honestly I can't see how any of those would have affected the performance of your test. All the more reason to try to reproduce it and track it down. And hopefully that experience will help when we move on to understanding why Go 1.5 doesn't work for you and then checking whether Go 1.6 does.

> Please do feel free to file issues against golang/go for this kind of thing too, or at least to @-summon me. If I can't help, I'll find the right person to help for a particular issue.

> Thanks very much.

**Comment by rsc** [comment]
Hi again. We'd love to help. I see in [this comment](https://github.com/kubernetes/kubernetes/issues/20400#issuecomment-179224443) that the metric that disqualified Go 1.5.3 was tail latency in a "kubemark" test. Am I right that Go 1.4.3 was disqualified for the same reason?

What would be ideal for us would be to build and spin up our own kubemark test using different versions of Go? Is that possible? Are there instructions somewhere? Thanks very much.

**Comment by wojtek-t** [comment]
@rsc - sorry for late response

Yes - the reason for Go 1.4.3 was exactly the same (performance was significantly higher than with Go 1.4.2). And I guess it should be much easier to pin down the reason of that between those two versions than between Go 1.5.3.

Regarding running kubemark - yes, it's definitely possible for you to run it.
Details explanation how to do it is here:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/kubemark-guide.md

Please let me know if you need any help with that (feel free to also email me directly at wojtekt@google.com)

**Comment by wojtek-t** [comment]
@rsc @lavalamp @ixdy - FYI

Yesteday we upgraded to Go 1.6 and from performance perspective we don't see any issues.
Since problems with Go 1.5 are kind of "by design" and we don't observe them with Go 1.6, I think that we should just close this issue. Thoughts?

**Comment by lavalamp** [comment]
SGTM
