### ISSUE TITLE
Reflector does unnecessarily frequent re-lists

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#20659]
If an etcd watch ends "normally", we still trigger a full relist:
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/reflector.go#L266

@bprashanth and I had a discussion on a tangentially related PR.. if this is a normal etcd server timeout, I think we should just restart the watch:
https://github.com/kubernetes/kubernetes/pull/20637#discussion_r51896817

**Comment by bprashanth** [comment]
Unless I've misunderstood I think this is fine, it'll end normally when the server (apiserver) decides to close the connection. This happens at some random interval for each client. You don't want this to be all client driven because they could all pick the same random timeout.

**Comment by justinsb** [comment]
(Good point it's apiserver not etcd server - whoops)

The question is why do we then do a full relist, vs just restarting the watch at the the last resourceVersion?  e.g. why don't we treat this like we do "connection refused" - it seems much more normal than that case.

**Comment by sclasen** [comment]
@justinsb  Not that its the normal case, but say you suffer a catastrophic failure of your etcd cluster, restore it from snapshots and restart the apiserver.

You will potentially be on a revision that is before wherever you are attempting to reconnect the watch at, and possibly miss updates, I think.

Similarly for catastrophic failures with https://github.com/kubernetes/client-go/blob/65ac4e638a79d49b7dbd5e1cef4e7785af7cbd39/tools/cache/reflector.go#L306-L318  there appears to be a window between the list and watch call where you could suffer a similar failure, and end up just retrying the watch indefinitely.  In the meantime you restore from a snapshot, and apiserver comes back, and the reflector starts watching at a revision higher than exists yet.

**Comment by spiffxp** [comment]
/sig api-machinery
I'm assuming sig-api-machinery owns client-go
