### ISSUE TITLE
EnsureLoadBalancer should take args like namespace and service name

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20668]
We could at least log them, or use them in description fields in cloud provider APIs.

@a-robinson 

not a hard fix

**Comment by therc** [comment]
Boy, would this have been useful while debugging today. I can take it and add an AWS implementation. Is namespace:service an acceptable format for a short description? There are times I wish kubectl understood that.

**Comment by a-robinson** [comment]
I think the preferred format is namespace/service, as in our [NamespacedName](https://github.com/kubernetes/kubernetes/blob/b9cfab87e33ea649bdd13a1bd243c502d76e5d22/pkg/types/namespacedname.go#L33) type. Adding it would be much appreciated :)

**Comment by therc** [comment]
Ugh, that's unfortunate. There's already the TYPE/NAME syntax, e.g.  rc/foo and deployment/bar...

**Comment by thockin** [comment]
yeah, there's not a formal grammar for the structure - it's contextual.
