### ISSUE TITLE
nginx deployment with containerPort other than 80, doesnt work

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#20677]
create a nginx-deployment with containerPort=84
create a service with port =81 and target-port=84

this doesnt work. If i login to the nginx container, the nginx container doesnt have port 84 but its still listening on 80.

I wondering if this is a bug in nginx container or kubernetes.

**Comment by krmayankk** [comment]
curl from a k8s node to <clusterip:81> returns the following :-1: 
curl: (52) Empty reply from server

**Comment by bgrant0607** [comment]
@krmayankk containerPort tells Kubernetes what port the application is listening on, not the other way around. If you want nginx to listen on a different port, you need to configure it to do so.
