### ISSUE TITLE
Docker version upgrade in 1.1.x branch

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#20684]
Hi,
Are there any plans to upgrade Docker version beyond 1.7.x in Kubernetes 1.8.3?

Thanks.

**Comment by dims** [comment]
@codefx9 @saad-ali - is this a Dup of issue https://github.com/kubernetes/kubernetes/issues/25893 ?

**Comment by saad-ali** [comment]
@dchen1107
