### ISSUE TITLE
Issues exposed in soak cluster

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#20707]
Currently tests in soak clusters are reliably failing for a number of reasons:
- bug in heapster (https://github.com/kubernetes/heapster/issues/945 - already fixed)
- influxdb OOM: 
```
  influxdb:
    Container ID:       docker://2d8dbe9663fd4db23ce93c59a3afae5d520f226a5b07d8d910f655cc50827679
    Image:              gcr.io/google_containers/heapster_influxdb:v0.5
    Image ID:           docker://5c3fc9fb0b98ea30400847bbd2f86715cd7677625f5f92e79321fd181de2aca4
    QoS Tier:
      cpu:      Guaranteed
      memory:   Guaranteed
    Limits:
      memory:   200Mi
      cpu:      100m
    Requests:
      memory:                   200Mi
      cpu:                      100m
    State:                      Terminated
      Reason:                   OOMKilled
      Exit Code:                137
      Started:                  Fri, 05 Feb 2016 04:36:57 -0800
      Finished:                 Fri, 05 Feb 2016 04:37:03 -0800
    Last Termination State:     Terminated
      Reason:                   OOMKilled
      Exit Code:                137
      Started:                  Fri, 05 Feb 2016 04:31:48 -0800
      Finished:                 Fri, 05 Feb 2016 04:31:53 -0800
    Ready:                      False
    Restart Count:              875
    Environment Variables:
```
Note that heapster-influxdb included influxdb 0.9.6. It seems that 200MB is too little for influxdb so we need to figure out what the good number is. It's especially worrying because soak cluster has only 3 Nodes...
- #20096 on one of the nodes.

cc @mwielgus @piosz @lavalamp @wojtek-t @kubernetes/goog-node @kubernetes/goog-control-plane @brendandburns

**Comment by davidopp** [comment]
It seems that most of the discussion is going on in #20096. Can we close this issue?

**Comment by gmarek** [comment]
Well, there's still influxdb issue, which is not related to #20096.

**Comment by vishh** [comment]
InfluxDB release v0.10 which is supposedly more optimized. Should we try upgrading to that before we sink in any time into optimizing InfluxDB? There is also #20247 which is suggesting moving InfluxDB + Grafana to be opt-in rather than opt-out.

**Comment by dchen1107** [comment]
Yes, #20096 and #20247 cover both issues listed here.

#20096: we are actively working on this. I pushed new soak-deploy build with hairpin mode disabled last night, and currently it is running in soak-continuous. So far so good. We are going to make decision based on the test result.

**Comment by dchen1107** [comment]
I am assigning this to myself and closing it. If you disagree with me, feel free to reopen it. I will address the rest of issue then. Thanks! :-)
