### ISSUE TITLE
e2e flake: "failed to create firewall" (gcloud flake?)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#20708]
Similar to #20306 I think.

This build: https://github.com/kubernetes/kubernetes/pull/20637#issuecomment-180022807

(direct link: https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/20637/kubernetes-pull-build-test-e2e-gce/26782/artifacts/)

Hit this error during kube-up: 

```
Failed to create firewall e2e-gce-builder-1-1-minion-e2e-gce-builder-1-1-http-alt in kubernetes-jenkins-pull
```

AFAICT, there's no relevant context in the logs.  kube-down fails to delete the rule (because it doesn't exist), but otherwise there is no mention of "http-alt" in the log.

My guess is that we should put the gcloud firewall rule creation into a retry loop (and I bet that we are sending the output to /dev/null or similar)

Edit: updated to fix links

**Comment by bprashanth** [comment]
Closing as dupe of https://github.com/kubernetes/kubernetes/issues/20576

**Comment by smarterclayton** [comment]
Appears to be the same symptom, reopening rather than create more issues.

**Comment by smarterclayton** [comment]
Actually will xref other.
