### ISSUE TITLE
Make e2e status link a public link

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#20729]
Currently, when the E2E tests fail for a PR, there is a comment from the bot with a public link to the build log, but the link in the status for the PR tests is a non-public one.  It would be extremely helpful if both links were public.

**Comment by lavalamp** [comment]
Is this true? Last time I clicked one of those I thought it took me to the public link?

**Comment by ixdy** [comment]
The unit/integration status URL used a public link, but the e2e one still went to internal Jenkins.

I updated both to use http://pr-test.k8s.io/${ghprbPullId}/${JOB_NAME}/${BUILD_NUMBER}/.
