### ISSUE TITLE
local-up-cluster.sh fails pod scheduling with "runContainer: container already exists"

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#20737]
running a pod on a local cluster fails do to "container already exists":

>
Fri, 05 Feb 2016 19:15:13 +0000   Fri, 05 Feb 2016 19:15:13 +0000   2         test-pd     Pod       spec.containers{hello-world}   Pulled                  {kubelet 127.0.0.1}      Container image "gcr.io/google_containers/busybox" already present on machine
Fri, 05 Feb 2016 19:15:13 +0000   Fri, 05 Feb 2016 19:15:13 +0000   2         test-pd     Pod       spec.containers{hello-world}   Failed                  {kubelet 127.0.0.1}      Failed to create docker container with error: container already exists
Fri, 05 Feb 2016 19:15:13 +0000   Fri, 05 Feb 2016 19:15:13 +0000   2         test-pd     Pod                                      FailedSync              {kubelet 127.0.0.1}      Error syncing pod, skipping: failed to "StartContainer" for "hello-world" with RunContainerError: "runContainer: container already exists"

**Comment by janetkuo** [comment]
+1

What's your docker version?

**Comment by yujuhong** [comment]
wild guess: you have docker v1.10 on your workstation? 

Since kubernetes/kubelet doesn't support docker v1.10  yet, some problems are expected. 
/cc @Random-Liu, who is verifying v.1.10

/cc @janetkuo, who ran into the same problem.

**Comment by dchen1107** [comment]
I sent an email out yesterday related to the new image layout introduced by docker 1.10.0 release. Have you tried to remove all your dead containers, then images and retry?

**Comment by janetkuo** [comment]
Did that and still hit the same problem.

**Comment by Random-Liu** [comment]
I'll try it.

**Comment by pwittrock** [comment]
I am running docker 1.9.1

It started failing for me at this commit:
https://github.com/kubernetes/kubernetes/commit/8118092d11e35cc7fffec50e7a93f2727b0a2802

**Comment by janetkuo** [comment]
Tried reverting https://github.com/kubernetes/kubernetes/commit/8118092d11e35cc7fffec50e7a93f2727b0a2802 and now the issue went away!

**Comment by yujuhong** [comment]
To clarify, the commit 8118092d11e35cc7fffec50e7a93f2727b0a2802 fails with docker v1.9.1 and above, but works with v1.8.3 (our official supported version).

**Comment by yujuhong** [comment]
Errors in docker.log
```
time="2016-02-05T21:00:09.117725452Z" level=error msg="Handler for POST /containers/create returned error: Conflicting options: hostname and the network mode"
time="2016-02-05T21:38:12.779143047Z" level=error msg="Handler for POST /containers/create returned error: Conflicting options: dns and the network mode"
```
I commented out the hostname and dns options in the code and the containers got started fine. 
The original error message was very unhelpful though.

**Comment by Random-Liu** [comment]
If so, the error message docker gave us is quite meaningless...

**Comment by Random-Liu** [comment]
FYI, the ambiguous error reason "already exists error" is reported by `go-dockerclient` [here](https://github.com/fsouza/go-dockerclient/blob/02a8beb401b20e112cff3ea740545960b667eab1/container.go#L408).

**Comment by Random-Liu** [comment]
"hostname and the network mode" is reported in docker code [here](https://github.com/docker/docker/blob/master/runconfig/hostconfig_unix.go#L39)
"dns and the network mode" is reported in docker code [here](https://github.com/docker/docker/blob/master/runconfig/hostconfig_unix.go#L51)

**Comment by yujuhong** [comment]
xerf; -h and --net should not be set at the same time (since v1.9) https://github.com/docker/docker/issues/17147

**Comment by Random-Liu** [comment]
I found the root reason cause this issue.

Before 8118092, we set `HostConfig` when `StartContainer()`. In `StartContainer()`, [DecodeHostConfig()](https://github.com/docker/docker/blob/master/api/server/router/container/container_routes.go#L1744) is called, in which there is no configuration check.

While, after 8118092, we set `HostConfig` when `CreateContainer()`. In `CreateContainer()`, [DecodeContainerConfig()](https://github.com/docker/docker/blob/master/api/server/router/container/container_routes.go#L368) => [ValidateNetMode()](https://github.com/docker/docker/blob/master/runconfig/config.go#L43), then docker reports errors in `ValidateNetMode()`

**Comment by bprashanth** [comment]
> It seems that if the NetworkMode is "host" or "container:", the DNS and HostName of container must be empty now. 
@kubernetes/sig-network Is the DNS option and HostName option still in use now?

We use --dns to set dns servers in resolv.conf in the pause pod which starts up the network namespace. Everything else in the pod just shares, though it's totally possible that we're piping the same dns for each container in the pod. I don't know what setting different dns options for each container in a pod will do. 

The pause pod will run with --net=none when we flip to cni. That should still work, do you have an issue? Unsure how much we care about hostname, @kubernetes/goog-cluster

**Comment by yujuhong** [comment]
The discussion on hostname: https://github.com/kubernetes/kubernetes/issues/4825

**Comment by yujuhong** [comment]
> The pause pod will run with --net=none when we flip to cni. That should still work, do you have an issue? Unsure how much we care about hostname, @kubernetes/goog-cluster

Yes, the pause pod still works, but the --net=container doesn't work anymore.

**Comment by Random-Liu** [comment]
Close this issue, since #20615 is reverted #20742.
I'll file another issue about the network configuration problem.

**Comment by Random-Liu** [comment]
Mistype...
