### ISSUE TITLE
Rewrite scheduler-centric e2e tests to avoid use of events for validation

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#20738]
We should have enough info available in other parts of the API to be able to test:
- whether a pod was scheduled
- scheduling latency per-pod
- reasons a pod failed to schedule

Events are deemed unstable / non-API, so at least the `[Conformance]` subset of tests should not rely on them

ref #19724

**Comment by spiffxp** [comment]
Fixes should be backported accordingly to ensure backwards compatibility (ref #18162).  May need to revisit depending on how much non-event info is available in `release-1.0`

**Comment by jdef** [comment]
would these tests be tagged instead with `[Feature:events]`?

**Comment by ihmccreery** [comment]
@jdef in our current scheme, no.  We expect these tests to pass on a "standard" cluster.  It's probably worth revisiting #14763 to consider modifying our conformance policy, cc @kubernetes/sig-testing

**Comment by davidopp** [comment]
Do we really need this for 1.2?

**Comment by ihmccreery** [comment]
Folks are working real hard on making clusters conformant, and having poortly-written/wrong conformance tests makes their lives very difficult.  I'm in favor of doing this, but it should of course be weighed against other things.

**Comment by bgrant0607** [comment]
We're not blocking 1.2 on this.

**Comment by spiffxp** [comment]
I'm fine punting to v1.2-candidate, seems like that's where "nice to have" issues are going, which is about where this sits on my current heap (unless there are any other takers)

**Comment by davidopp** [comment]
Moving this to next-candidate, upgrading to P1.

**Comment by timothysc** [comment]
@jayunit100 @sjug - would be a good tag-along exercise.

**Comment by sjug** [comment]
Sounds good to me.

**Comment by timothysc** [comment]
Closing this now, as folks have re-worked the scheduling tests.  Events are useful if/when used judiciously in the e2es.
