### ISSUE TITLE
Revisit scale e2e [5/20/2016]

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#20743]
Once e2e flakes smooth out, revisit the following PRs.  Priority order 1st, highest.  Please assign this issue to me.

cc @ixdy @timothysc @kubernetes/sig-testing   

I'm Happy to add other tests here which we can revisit later if others have them, please add below.

**Comment by jayunit100** [comment]
- HPA Config #18631 
- HPA Multitest #18633
- Networking Soak #15762

**Comment by spiffxp** [comment]
>once e2e flakes smooth out

😄 

/assign
I'm going to close this out due to inactivity, feel free to reopen and assign an appropriate sig if you're willing to tackle this @jayunit100
