### ISSUE TITLE
PersistentVolumeClaim doesn't bind to a volume when created again

### ISSUE THREAD

**Issue by parikhyash** [kubernetes/kubernetes#20753]
- I created a PersistentVolume and a PersistentVolumeClaim that binds to that volume.
- Everything worked as expected
- Went ahead and deleted the claim
- On creating the same claim again, it refuses to bind to the volume (to which it did the first time). Status is stuck in "pending" phase.
- The persistent volume status is shown as "released", however, the claim is still unable to bind to it.
- The only way to get around this was to delete the PersistentVolume itself and create it again.

Steps shown below
```
[yparikh@surpriseddevised ~]$ sudo kubectl create -f nfs-volume.yaml 
persistentvolume "nfs-test" created

[yparikh@surpriseddevised ~]$ kubectl get pv
NAME       LABELS      CAPACITY   ACCESSMODES   STATUS      CLAIM     REASON    AGE
nfs-test   type=test   5Gi        RWO,RWX       Available                       14s

[yparikh@surpriseddevised ~]$ sudo kubectl create -f nfs-volume-claim.json
persistentvolumeclaim "claim-test" created

[yparikh@surpriseddevised ~]$ kubectl get pvc --namespace=abc
NAME         LABELS    STATUS    VOLUME     CAPACITY   ACCESSMODES   AGE
claim-test   <none>    Bound     nfs-test   5Gi        RWO,RWX       7s

[yparikh@surpriseddevised ~]$ sudo kubectl delete -f nfs-volume-claim.json 
persistentvolumeclaim "claim-test" deleted

[yparikh@surpriseddevised ~]$ kubectl get pvc --namespace=abc
NAME      LABELS    STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE

[yparikh@surpriseddevised ~]$ sudo kubectl create -f nfs-volume-claim.json
persistentvolumeclaim "claim-test" created

[yparikh@surpriseddevised ~]$ kubectl get pvc --namespace=abc
NAME         LABELS    STATUS    VOLUME     CAPACITY   ACCESSMODES   AGE
claim-test   <none>    Pending   nfs-test   0                        5s

[yparikh@surpriseddevised ~]$ kubectl get pv
NAME       LABELS      CAPACITY   ACCESSMODES   STATUS     CLAIM                        REASON    AGE
nfs-test   type=test   5Gi        RWO,RWX       Released   content-dev-gq1/claim-test             1h

[yparikh@surpriseddevised ~]$ kubectl get pvc --namespace=content-dev-gq1
NAME         LABELS    STATUS    VOLUME     CAPACITY   ACCESSMODES   AGE
claim-test   <none>    Pending   nfs-test   0                        1h
```

This seems like a bug since only the deletion of the PersistentVolume itself solves the problem.

PersistentVolume Spec:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test
  labels:
    type: test
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  nfs:
    path: /home/yparikh/nfsshare 
    server: x.x.x.x
```

Claim spec:
```json
{
    "kind": "PersistentVolumeClaim",
    "apiVersion": "v1",
    "metadata": {
        "name": "claim-test",
	"namespace": "abc"
    }, "spec": {
	"volumeName": "nfs-test",
        "accessModes": [
	    "ReadWriteOnce",
            "ReadWriteMany"
        ],
        "resources": {
            "requests": {
                "storage": "1Gi"
            }
        }
    }
}
```

**Comment by parikhyash** [comment]
After some digging, found out that it is being caused due to https://github.com/kubernetes/kubernetes/pull/20495

Closing this out

**Comment by metral** [comment]
I'm still hitting this same issue with NFS volumes in v1.2.4 - can we reopen this issue?

**Comment by tutaidalal** [comment]
With the above steps I am getting the same issue and only the claim is usable after delete and re-create the volume. Could anyone please drive me to the solution? Or the only way is to delete and create the volume again ?

**Comment by luhkevin** [comment]
Try editing the claimref on the persistent volume
https://github.com/kubernetes/kubernetes/issues/48609

**Comment by abdennour** [comment]
Issue referenced by @luhkevin  saves my day.

**Comment by robersongomes** [comment]
> Try editing the claimref on the persistent volume
> #48609

This worked for me: 
`kubectl patch pv my-pv-name -p '{"spec":{"claimRef": null}}'` 

Thanks @luhkevin !

**Comment by lingyanmeng** [comment]
> > Try editing the claimref on the persistent volume
> > #48609
> 
> This worked for me:
> `kubectl patch pv my-pv-name -p '{"spec":{"claimRef": null}}'`
> 
> Thanks @luhkevin !

Thanks @robersongomes , it works for me!

**Comment by SKPuthumana** [comment]
> > Try editing the claimref on the persistent volume
> > #48609
> 
> This worked for me:
> `kubectl patch pv my-pv-name -p '{"spec":{"claimRef": null}}'`
> 
> Thanks @luhkevin !

Awesome!!
Worked for me as well.
Jus added and namespace as well as claim ref.
kubectl patch pv nfs2 -p '{"spec":{"claimRef": {"namespace":"dev","name":"my-claim"}}}'

**Comment by vinodhbasavani** [comment]
I can't remove the claimReference. without setting any claimRef to null, is there any resolution for this?

**Comment by erickfaustino** [comment]
This did the trick for me today!

`kubectl patch pv my-pv-name -p '{"spec":{"claimRef": null}}'`
Thank you, @robersongomes

**Comment by finkr** [comment]
**Data loss warning:**

Removing `claimRef` (or setting it to `null`) will cause the volume the be immediately removed by the storage class if `persistentVolumeReclaimPolicy`:`Delete`.

Also, removing `claimRef` (or setting it to `null`) will make the PV volume available for any new PVC. 

I have written a procedure to migrate/re-use a PV: https://stackoverflow.com/questions/66078689/move-or-change-a-volume-namespace/66078690#66078690
