### ISSUE TITLE
Client: Never throttle watch

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#20750]
As @wojtek-t notes in #20638, it's possible for our client throttling to allow a list and then block the corresponding watch. This is really bad, because if those two calls aren't close enough together, the window could expire and then we'd have to start all over with another list. Lists are expensive and we want to minimize them.

The first thing that comes to mind is to just not throttle watches. I don't know if it's necessary to be more complicated than that.

**Comment by wojtek-t** [comment]
To give slightly more information - the problematic code is here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/restclient.go#L124

If verb is always "watch" for watches, then it is really easy, but I'm not sure if that's always the case (at least it wasn't that in the past). We should verify it.

**Comment by hongchaodeng** [comment]
How about making read and watch an atomic operation from rate limiter's perspective? What do you guys think?

**Comment by wojtek-t** [comment]
@hongchaodeng - it's not that easy because:
1. you can have independent LIST operations without any associated watch
2. we explicitly break watches after 5-10 minutes and set it up again from that point, to avoid having extremely long operations; so a typical usage is:
list + watch + watch + ... + watch + relist + watch + watch + ... + watch + relist + ...

So I think it's not that easy...

**Comment by lavalamp** [comment]
@krousey Is this something you can look into?

@hongchaodeng Like @wojtek-t said, the calls are independent and there's no obvious way to do that.

**Comment by timothysc** [comment]
Morbid curiosity, what happens when we remove all the throttles?  A part of me believes that the throttles themselves are a form of ductape vs. proper back-pressure.

**Comment by krousey** [comment]
@wojtek-t the verb for watch is "GET".

@lavalamp I'll see if I can find something that makes sense.

**Comment by krousey** [comment]
Given the way the request object works, I think the only way to handle this is to pass the throttle down to the request object, and have it throttle on `Do()`, `DoRaw()`, and `Stream()`, but not `Watch()`. That seem ok to you guys?

**Comment by lavalamp** [comment]
That may be, but it's not duct tape we're removing for 1.2 :)

On Wed, Feb 10, 2016 at 2:29 PM, Timothy St. Clair <notifications@github.com

**Comment by lavalamp** [comment]
@krousey That sounds better to me. It looks like the wrong place right now anyway, it should block right before sending the request, not before constructing it. IMO anyway.

**Comment by wojtek-t** [comment]
I agree with @lavalamp - what @krousey suggests sounds better than what we have now

**Comment by krousey** [comment]
Got a PR out for this if one of you want to take it.

**Comment by smarterclayton** [comment]
Agree in 1.3 we should look at relying on client backpressure (which is mostly there, but nowhere near tested enough).  And the server throttler is also susceptible to getting starved by watches, which means we can livelock on watching in the other direction (can watch, but not list)

**Comment by lavalamp** [comment]
I thought we put long-running requests (watch, proxy) in a different rate
limiting bucket on the server?

**Comment by wojtek-t** [comment]
@lavalamp - SGTM

**Comment by smarterclayton** [comment]
I'm not positive but I thought the rate limit regex didn't discern
param watches (vs the old style).  Brendan may have fixed it.

**Comment by magicwang-cn** [comment]
@kubernetes/huawei
