### ISSUE TITLE
default LOGGING_DESTINATION not consistent between prod and test on GCE

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#20760]
For GCE:
`config-default.sh: LOGGING_DESTINATION="${KUBE_LOGGING_DESTINATION:-gcp}"`
`config-test.sh: LOGGING_DESTINATION="${KUBE_LOGGING_DESTINATION:-elasticsearch}"`

Should we use gcp logging in both settings? 
modify/add logging e2e to test against gcp logging? 
mark elasticsearch e2e test as [Feature]?

@kubernetes/goog-cluster

**Comment by a-robinson** [comment]
Writing an e2e test against GCP logging and switching over to using that in our test clusters would be a great improvement

**Comment by bprashanth** [comment]
Only real motivation to continue bringing up ES on e2e clusters (and the non-cloud addons in general, like influx+grafana) IMO is if users are pre-dominantly deploying the OSS equivalents, which doesn't *seem* to be the case? I can't think of a reason to bring up ES on e2e and never by default on kube-up GCE, so SGTM

**Comment by piosz** [comment]
@crassirostris the plan is to:
- [ ] implement e2e test for GCL 
- [ ] verify which tests relies on Elasticsearch and mark them as `[Feature:Elasticsearch]`
- [ ] change the default to `gcp`

cc @fgrzadkowski
