### ISSUE TITLE
e2e needed: kube-proxy REJECT rules

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20767]
#19576 introduced somethng that really should be e2e tested.

**Comment by bprashanth** [comment]
Would be nice to get this in in the 2 weeks we have after 1.2 branch cut, if no more flakes crop up (but I'm not too optimistic). Bumping to next-release.

**Comment by spiffxp** [comment]
/sig network
I'm assuming sig-network owns kube-proxy

**Comment by cmluciano** [comment]
@kubernetes/sig-network-misc I thought I noted a change related to this recently, but I may be mistaken.

**Comment by vllry** [comment]
Going to try to take this on.

**Comment by bowei** [comment]
thanks!

**Comment by vllry** [comment]
I've had some trouble constructing a test for this.

1. How should I determine the timeout? There doesn't appear to be an existing mechanism for waiting for service creation.
2. Connections seem to time out rather than be refused - I'm confused by this, as it seems to be the opposite of the intended behavior.

**Comment by bowei** [comment]
1. You can look at the endpoints + wait for longer than kube-proxy sync time.
2. Conn refused means packets got to their destination but there was nothing listening there. If traffic is blocked, then you will just get a timeout.

**Comment by thockin** [comment]
I have a cluster from HEAD as of 2 weeks ago:

```
$ cat /tmp/svc-has-no-endpoints.yaml
apiVersion: v1
kind: Service
metadata:
  name: has-no-endpoints
spec:
  ports:
  - port: 80
  selector:
    has: no-endpoints

$ k create -f /tmp/svc-has-no-endpoints.yaml
service/has-no-endpoints created

$ k get svc has-no-endpoints
NAME               TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
has-no-endpoints   ClusterIP   10.0.199.54   <none>        80/TCP    9s

$ k get ep has-no-endpoints
NAME               ENDPOINTS   AGE
has-no-endpoints   <none>      32s

$ k run -ti --restart=Never --rm thdbg-${RANDOM} --image=busybox -- sh
If you don't see a command prompt, try pressing enter.
/ # wget -qO- 10.0.199.54:80

^C
/ # wget -qO- 10.0.199.54:81
^C
```

So indeed it seems to not work.

If I hit that same service IP from the VM itself I immediately get `curl:
(7) Failed to connect to 10.0.199.54 port 80: Connection refused`.

If I insert an iptables jump to KUBE-SERVICES at the front of FORWARD, it
correctly rejects.  This seems in accordance with the iptables flowchart.

I'll do some spelunking to see if there's a reason NOT to reject in this
case.

**Comment by thockin** [comment]
This is why we need tests.  Sigh.

**Comment by thockin** [comment]
Proposed fix is https://github.com/kubernetes/kubernetes/pull/72534 - still needs your e2e :)

**Comment by vllry** [comment]
Thanks Tim, if I have time I’ll get a PR up tonight.

**Comment by m1093782566** [comment]
Sure @thockin, will check IPVS mode.

**Comment by m1093782566** [comment]
@thockin 

For my test, IPVS has no such issue.

```
[root@SHA1000130405 tmp]# kubectl create -f no-endpoints.yml 
service "has-no-endpoints" created

[root@SHA1000130405 tmp]# kubectl get svc has-no-endpoints
NAME               TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
has-no-endpoints   ClusterIP   10.0.0.57    <none>        80/TCP    8s

[root@SHA1000130405 tmp]# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.0.0.1:443 rr
  -> 100.106.89.164:6443          Masq    1      0          0         
TCP  10.0.0.10:53 rr
TCP  10.0.0.57:80 rr
UDP  10.0.0.10:53 rr

[root@SHA1000130405 tmp]#  kubectl get ep has-no-endpoints
NAME               ENDPOINTS             AGE
has-no-endpoints   <none>                28s

[root@SHA1000130405 tmp]# k run -ti --restart=Never --rm thdbg-${RANDOM} --image=busybox -- sh
bash: k: command not found...
[root@SHA1000130405 tmp]# kubectl run -ti --restart=Never --rm thdbg-${RANDOM} --image=busybox -- sh
If you don't see a command prompt, try pressing enter.
/ # wget -qO- 10.0.0.57:80
wget: can't connect to remote host (10.0.0.57): Connection refused
/ # wget -qO- 10.0.0.57:81
wget: can't connect to remote host (10.0.0.57): Connection refused
```
