### ISSUE TITLE
Nodes losing DNS service

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#20784]
Hi,

I'm using kubernetes 1.1.3 over AWS.

I get a repeated error in which nodes seem to lose the ability to resolve kubernetes services via DNS.
The DNS service is surely up as other nodes seem to have no problem to resolve kubernetes services.
I tried SSH-ing to the nodes and run:
`dig my-service.default.svc.cluster.local @10.0.0.10`

Here's a node which had a successful reply:
```
; <<>> DiG 9.9.5-9ubuntu0.5-Ubuntu <<>> my-service.default.svc.cluster.local @10.0.0.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5669
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;my-service.default.svc.cluster.local.	IN A

;; ANSWER SECTION:
my-service.default.svc.cluster.local.	30 IN A	10.0.226.41

;; Query time: 1 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Sun Feb 07 08:59:30 UTC 2016
;; MSG SIZE  rcvd: 72
```
And here's a node which failed due to timeout:
```
; <<>> DiG 9.9.5-9ubuntu0.5-Ubuntu <<>> my-service.default.svc.cluster.local @10.0.0.10
;; global options: +cmd
;; connection timed out; no servers could be reached
```
The timeout on this node is consistent - it has been this way for days.
Any thoughts about this and why it may be happening?
I'd be happy to supply additional data if needed.

**Comment by thockin** [comment]
Would first check that iptables rules are installed and that kube-proxy is
running properly.

Then check if the DNS server has a significant restart count.

Then I would check basic connectivity between the trouble node and the
actual DNS pod without the DNS service in between.  Look up the pod's IP
and try your nslookup.

**Comment by erez-rabih** [comment]
@thockin thanks for the fast reply.
About the iptables rules: What rules am I expecting to see?

**Comment by thockin** [comment]
Rules that redirect or NAT you the actual DNS pod, but it depends on which
proxy mode you are running which exact pattern you might see.

**Comment by erez-rabih** [comment]
I have bootstrapped the cluster using
```
export KUBERNETES_PROVIDER=aws; wget -q -O - https://get.k8s.io | bash
```
So I guess my setup is the default one for AWS.

**Comment by erez-rabih** [comment]
I haven't seen this happening since 1.1.3 so I think we can close this.
