### ISSUE TITLE
Add complex scheduling constraints and preferences to scalability tests

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#20793]
As we introduce more complex scheduling constraints and preferences (node affinity is in 1.2, pod affinity and taints/tolerations will be in 1.3), we should also start using pods that use these features.

It may be reasonable to have a looser scheduling SLO for workloads that involve a lot of complex constraints, but let's wait and see what effect these more complex scheduling rules have on performance.

cc/ @gmarek @wojtek-t @xiang90 @hongchaodeng

**Comment by jayunit100** [comment]
- We will handle simulating these scenarios in scheduler_perf.

- Also we will ping test infra on how to fire those
Tests up as part of the CI so the SLOs don't regress.
