### ISSUE TITLE
Kubernetes master should limit the number of nodes that can join

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#20822]
Masters have a limit to how large they can scale -- around 1000 nodes in 1.2.  We should have a flag that prevents significantly more nodes than that from being registered with the master.

**Comment by mqliang** [comment]
Maybe add a admission controller to limit the number of nodes/pods/rcs ?

**Comment by countspongebob** [comment]
Scalability limit is much more directly correlated to number of pods being scheduled than the number of nodes.  Anyone running clusters at this size is going to have to have to have a pretty good handle on provisioning at scale anyway, so I'm not sure how helpful this is. We ran 1000 node clusters pre-1.2, the actual limit is certainly higher in 1.2 than 1000 - there have been some very positive improvements in scaling in 1.2. Pod density and pod creation/destruction rate are more substantive scaling issues than raw node count. 

An optional flag with a default of "unlimited" might be useful for some operational scenarios, but would have to be adjustable on the fly. 

I'd be very concerned about coding in a marketing issue for the project similar to the unfortunate (and untrue) "only scales to 100 nodes" meme that ran around for a while.

**Comment by timothysc** [comment]
I'm actually not a fan of artificially capping this.  It's fine that google want to put their SLO stamp at a level, but I wouldn't artificially knee-cap others. 

/cc @kubernetes/sig-scalability
