### ISSUE TITLE
v1.1 kube-ui e2e does not work with v1.2 master 

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20825]
**kube-ui should check that the kube-ui instance is alive [Conformance]**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kube-ui.go:85 Expected error: <errors.errorString | 0xc20851ff70>: { s: "error waiting for service kube-system/kube-ui to appear: timed out waiting for the condition", } error waiting for service kube-system/kube-ui to appear: timed out waiting for the condition not to have occurred*

Triaging; my guess is this is expected due to #20330 (and #20563)

**Comment by ihmccreery** [comment]
#20330 set kubernetes-dashboard as the default UI addon, so the v1.1 tests no longer pass.

I can backport and version-guard the test fix.

cc @kubernetes/kube-api Just want to make sure you all are cool with this non-backward-compatible change.

**Comment by bgrant0607** [comment]
That's not an API change, IMO. It's a bogus test.

cc @bryk

**Comment by bryk** [comment]
I'm fine every solution to this problem. I'd like, however, to keep kubernetes-dashboard e2e test. It is useful. So backporting/version guarding or deleting kube-ui test SGTM. 

CC @roberthbailey

**Comment by roberthbailey** [comment]
I sent https://github.com/kubernetes/kubernetes/pull/20772 to unmark that test as a conformance test, since I agree with @bgrant0607 that it isn't an api change.

**Comment by ihmccreery** [comment]
Fixed #20825 via #20833.
