### ISSUE TITLE
Error when running kubectl e2e test: Unable to parse server version

### ISSUE THREAD

**Issue by aveshagarwal** [kubernetes/kubernetes#20823]
I am running kube from latest master branch, when I am testing kubectl run job e2e test on local cluster (hack/local-up-cluster.sh), I am seeing following errors:

```
• Failure [2.602 seconds]
Kubectl client
/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1030
  Kubectl run job
  /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:954
    should create a job from an image when restart is Never [Conformance] [It]
    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:952

    Feb  8 11:42:40.438: Failed to get server version: Unable to parse server version "v0.12.0.17515+dd0c313e8baf17-dirty": Invalid character(s) found in patch number "0.17515"

    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/util.go:306
------------------------------
```

**Comment by bgrant0607** [comment]
cc @janetkuo @erictune @soltysh

**Comment by bgrant0607** [comment]
Ah, this has nothing to do with Job.

**Comment by bgrant0607** [comment]
@aveshagarwal How did you build? That server version does not conform to our conventions.

**Comment by aveshagarwal** [comment]
@bgrant0607 I built it from master branch HEAD.

**Comment by soltysh** [comment]
@aveshagarwal can you retry, I've did a couple of local tests and there's nothing wrong with it. Like @bgrant0607 already mentioned the version you're seeing is not correct, when testing with latest master I see `v1.2.0-alpha.7.489+f637f08774e199-dirty` rather than `v0.12.0.17515+dd0c313e8baf17-dirty`.

**Comment by aveshagarwal** [comment]
@soltysh I will retry that, but I see similar to v1.2.0-alpha.7.something when I checkout the tag 1.2.0 alpha tag not with master.

**Comment by aveshagarwal** [comment]
@soltysh @bgrant0607 I am not seeing that issue now on my master branch and kubectl version shows v1.2.0-alpha.7.603+66e872227aedf4-dirty, but I am sure I noticed that day before yesterday even on my latest master branch at that point, so I am sure my repo had latest commits but may be something else was not updated in my repo, although not sure what.  Anyway as I am not seeing it any more, I am closing this, sorry for noise.

**Comment by jayunit100** [comment]
This will pop up any time you have version which have extra periods in them.    Put in a fix in the above patch (#21620) which makes sure there are semvar style periods. i.e. `x.y.z-` when we parse dirty versions.  I think this effects things during development, probably never effects a "real" release.  
```
{
  "major": "",
  "minor": "",
  "gitVersion": "v0.7.0.20842+e56838816aee80-dirty",
  "gitCommit": "e56838816aee800a02434eb1edc1d057f09179f5",
  "gitTreeState": "dirty"
```

**Comment by ihmccreery** [comment]
> This will pop up any time you have version which have extra periods in them.

We should never have a version that has extra periods.  Back in pre-v1.0, we had versions like `v0.7.0.1234`, but now it will be `v1.2.0-alpha.1234`, which should be perfectly compliant.

**Comment by ihmccreery** [comment]
See https://github.com/kubernetes/kubernetes/pull/16102
