### ISSUE TITLE
v1.1 e2es running against v1.2 master: 'no kind "APIVersions" is registered for version "v1"'

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20824]
**Kubectl client Kubectl api-versions should check if v1 is in available api versions [Conformance]**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:444 Expected error: <*errors.errorString | 0xc208641770>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.136.232 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/.kube/config api-versions] [] error: Couldn't get available api versions from server: no kind \"APIVersions\" is registered for version \"v1\"\n [] 0xc208382fa0 exit status 1 true [0xc208627148 0xc208627168 0xc208627188] [0xc208627148 0xc208627168 0xc208627188] [0xc208627160 0xc208627180] [0x6d81a0 0x6d81a0] 0xc2082fb2c0}:\nCommand stdout:\n\nstderr:\nerror: Couldn't get available api versions from server: no kind \"APIVersions\" is registered for version \"v1\"\n\n", } Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.136.232 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/.kube/config api-versions] [] error: Couldn't get available api versions from server: no kind "APIVersions" is registered for version "v1" [] 0xc208382fa0 exit status 1 true [0xc208627148 0xc208627168 0xc208627188] [0xc208627148 0xc208627168 0xc208627188] [0xc208627160 0xc208627180] [0x6d81a0 0x6d81a0] 0xc2082fb2c0}: Command stdout: stderr: error: Couldn't get available api versions from server: no kind "APIVersions" is registered for version "v1" not to have occurred*

See http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step4-e2e-old/ and http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step6-e2e-old/

Investigating...

cc @caesarxuchao

**Comment by ihmccreery** [comment]
Okiedokie.  Looks like the v1.1 client is getting a response from the v1.2 master,

```
Response Body: {"kind":"APIVersions","apiVersion":"v1","versions":["v1"]}
```

but the v1.1 client doesn't know how to handle the v1 APIVersions object, because in v1.1, that object was never expected to have an `apiVersion`.  From a 1.1 server, we get

```
Response Body: {
  "kind": "APIVersions",
  "versions": [
    "v1"
  ]
}
```

which doesn't include a `"apiVersion":"v1"`.  We should expect to have plenty of pre-v1.1.7 clients floating around, and releasing a fixed v1.1.8 probably isn't going to solve this; if we want to be backward compatible, we need to not return an `apiVersion` string with unversioned kinds like `APIVersions`.

Looking into more details about how we got here...

cc @kubernetes/kube-api cc @smarterclayton

**Comment by ihmccreery** [comment]
I have a maybe feeling that this is caused by #17922?  In particular, we went from:

```
var SchemeGroupVersion = unversioned.GroupVersion{Group: GroupName, Version: ""}
```

to

```
var Unversioned = unversioned.GroupVersion{Group: "", Version: "v1"}
```

**Comment by caesarxuchao** [comment]
Probably it's caused by this:
https://github.com/kubernetes/kubernetes/commit/125ef6fbc8cc70477071936cd93d064d71c773e6#diff-fdfac9813673596faeda07fdce9207e2R298

**Comment by caesarxuchao** [comment]
Let me double check the code. cc @smarterclayton

**Comment by ihmccreery** [comment]
@caesarxuchao What about that line?  I've never dealt with the version negotiation; should the server and client be negotiating in a way that the server can return an object without `apiVersion`?

**Comment by caesarxuchao** [comment]
More precisely it's this line:
https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/serializer/versioning/versioning.go#L181

This line sets the version to "v1".

In 17922, during encoding, we set unversioned object's APIVersion field to "v1".

**Comment by caesarxuchao** [comment]
I think in the long run, because we expect to move many unversioned types to group "common", so they should be versioned, so making APIVersion=v1 is the right move.

Back to the backwards compatibility issue, how's the situation at other url, like http://127.0.0.1:8080/apis/extensions? That address also returns a versioned object, which at release 1.1 is unversioned:
```
{
  "kind": "APIGroup",
  "apiVersion": "v1",
  "name": "extensions",
  "versions": [
    {
      "groupVersion": "extensions/v1beta1",
      "version": "v1beta1"
    }
  ],
  "preferredVersion": {
    "groupVersion": "extensions/v1beta1",
    "version": "v1beta1"
  }
}
```

Do we need to keep all unversioned objects unversioned, or do we only need to ensure the server returns unversioned object at api/?

**Comment by caesarxuchao** [comment]
cc @lavalamp

**Comment by ihmccreery** [comment]
> Do we need to keep all unversioned objects unversioned, or do we only need to ensure the server returns unversioned object at api/?

Per our versioning rules, we should expect a v1.2 server to remain backward compatible with v1.1 clients.  I don't have much experience with the api machinery, but if clients weren't expecting an unversioned object, it seems like we can't up and switch to versioned objects.

**Comment by lavalamp** [comment]
I think we have to maintain compatibility somehow. @smarterclayton any ideas for a fix other than the obvious one?

**Comment by bgrant0607** [comment]
Yes, we have to maintain backward compatibility with 1.1 (and 1.0) clients.

New paths that old clients didn't know about could behave differently than paths that existed in previous releases.

**Comment by smarterclayton** [comment]
Nope, let's make sure we leave a test and comment.

**Comment by smarterclayton** [comment]
We can't make the change here though, this would break "versioned
unversioned" objects (like v1.status)

**Comment by smarterclayton** [comment]
The other implication of course is now we "versioned unversioned"
objects (v1 status) and "unversioned unversioned", which means we
shouldn't ever add new objects that don't return a version.  I don't
think anything in 1.2 qualifies as a new object without a version,
just 1.1 objects that didn't have correct versions.

Having objects from extensions group be returned without versions
terrifies me - I don't see any way of describing that except as a bug.

**Comment by smarterclayton** [comment]
We may need per API group version rules registered on scheme about
whether "unversioned" objects are returned in their scheme version or
as empty.  That's probably the backward compatible fix that gives us a
hope of reasoning about behavior correctly (status in 1.0 is v1,
status in extensions might be "", apiversions in any new group is
"v1").

The unversioned marker on the objects should ensure 1.2 clients can
receive objects in both "" and "v1" form, we should add a test to
verify that.

I'm against letting empty API versions spread, but agree backcompat
for existing groups versions should match previous behavior.

**Comment by lavalamp** [comment]
Can we make (or use) a different serializer/codec just for the endpoints that 1.1 clients used?

**Comment by caesarxuchao** [comment]
Probably we just need to change the version registered here: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/register.go#L106

**Comment by smarterclayton** [comment]
That won't work like you expect - the type registry then has no knowledge
in v1 of what schema the object is.  That's not what we want - we want to
not serialize the version of the object for specific API groups, which is a
much more targeted change.  This is a special, exceptional case (v1 group
*should* return v1 Status.  v1beta1 *should not*).

**Comment by smarterclayton** [comment]
Changing v1 breaks 1.0 backwards compat (we always returned apiVersion=v1
for 1.0)

**Comment by caesarxuchao** [comment]
I mean this:
```
	Scheme.AddUnversionedTypes(Unversioned,
		&unversioned.ExportOptions{},
		&unversioned.Status{},
        )
        Scheme.AddUnversionedTypes(unversioned.GroupVersion{},
		&unversioned.APIVersions{},
		&unversioned.APIGroupList{},
		&unversioned.APIGroup{},
		&unversioned.APIResourceList{},
	)
```

Will this work?

**Comment by smarterclayton** [comment]
I'm not sure without looking at the outcome  (which is why unversioned
is a bit of a disaster in our codebase).

I would much prefer to explicitly identify which objects should have
an unset apiversion via a method on the scheme, and do the explicit
check at the time we do convert to version.  That's an extremely
controlled change, is obvious, and doesn't make the unversioned
problem worse.

**Comment by caesarxuchao** [comment]
I remember somewhere in 17922 asserts version cannot be empty, so I guess my proposed solution won't work without extra work. I'll take approach suggested by @smarterclayton.
