### ISSUE TITLE
Don't use ":latest" or non-tagged images in e2e tests

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#20836]
If a image is not tagged or is tagged with :latest, the image pull policy is defaulted to PullAlways. This causes unnecessary image pulling in e2e tests, leading to various timeout flakes (e.g. #20418). 
Unless a test is meant to test image pulling, we should not allow using of such images.

The alternative is to explicitly set PullIfNotPresent in such cases, which seem harder to enforce.

**Comment by fejta** [comment]
Can you look into adding this ability?

**Comment by fejta** [comment]
$ grep -o -E -e 'gcr.io/[-a-z0-9/_:.]+' test/e2e/*.go | grep -v -E "gcr.io/.*:" | cut -d ":" -f 1 | sort | uniq
test/e2e/container_probe.go
test/e2e/dns.go
test/e2e/downward_api.go
test/e2e/downwardapi_volume.go
test/e2e/expansion.go
test/e2e/garbage_collector.go
test/e2e/job.go
test/e2e/networking.go
test/e2e/pd.go
test/e2e/persistent_volumes.go
test/e2e/pods.go
test/e2e/pre_stop.go
test/e2e/security_context.go
test/e2e/service.go
test/e2e/volumes.go

**Comment by fejta** [comment]
`$ grep -o -E -e 'gcr.io/[-a-z0-9/_:.]+' test/e2e/*.go | grep -v -E "gcr.io/.*:" | cut -d ":" -f 1 | sort | uniq`

shows nothing at head

**Comment by yujuhong** [comment]
[test/e2e/deployment.go](https://github.com/kubernetes/kubernetes/blob/9e5d1b61faaf23393a617a78620cf3153f0fb195/test/e2e/deployment.go) still uses the "nginx" image, among others. Maybe the @kubernetes/sig-config can help with this file?

**Comment by fejta** [comment]
Have a PR out for deployment.go and and #13288 is also relevant.

**Comment by fejta** [comment]
(the pkg/api tests don't actually talk to anything as they are unit tests)

**Comment by yujuhong** [comment]
@kubernetes/kubectl, `test/e2e/kubectl.go` still uses yaml files from `docs/user-guide` and those files pull non-tagged images such as ["nginx"](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/pod.yaml). Please fix it.

**Comment by janetkuo** [comment]
Running on head:
```console
$ grep -o -E -e 'gcr.io/[-a-z0-9/_:.]+' test/e2e/*.go | grep -v -E "gcr.io/.*:" | cut -d ":" -f 1 | sort | uniq
test/e2e/volume_provisioning.go
```

**Comment by janetkuo** [comment]
We should add some check in hack/verify-xxx.sh to prevent regressions.

**Comment by janetkuo** [comment]
> We can add some check in hack/verify-xxx.sh to prevent regressions.

#26365 for this

**Comment by janetkuo** [comment]
All fixed now. Closing.
