### ISSUE TITLE
Create another jenkins job for a soak test clone

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#20832]
@dchen1107 and @thockin are figuring out why soak test clusters are broken, but in order to make faster progress, it'd be helpful to have a clone of the existing "kubernetes-soak-continuous-e2e-gce" jenkins job to try different flags or kernels with.

@spxtr volunteered to do the jenkins cloning -- thanks Joe!

**Comment by spxtr** [comment]
Done.
