### ISSUE TITLE
1.2: support 1000 node / 32000 core clusters

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#20834]
We'd like to support 1000 node clusters for 1.2.  I didn't see an issue explicitly for that yet, so filing this one.  @kubernetes/goog-control-plane @gmarek @mwielgus @cjcullen

**Comment by wojtek-t** [comment]
Yeah - there were a bunch of related issues, but no umbrella issue...

**Comment by davidopp** [comment]
Personally I'm not a fan of umbrella issues. People never remember to keep the dependency list up-to-date, never remember to close the umbrella issue when it is finished, etc.

My personal preference would be to mark all of the specific issues needed for 1000 node support with the "v1.2" milestone, and not have an umbrella issue.

**Comment by xiang90** [comment]
What do we mean by "support"? Any specific goals?

**Comment by mikedanese** [comment]
@xiang90 Run the load.go e2e test which starts 30 pods per node:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/load.go#L102

while maintaining api performance below these thresholds:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/metrics_util.go#L39-L48

**Comment by gmarek** [comment]
I think that we mean running density.go e2e test for now. Load test is kind of broken currently - @wojtek-t is fixing it, but I'm not sure fixes are already in.

**Comment by davidopp** [comment]
As before, I'd really like to close this issue. As long as all the blockers for 1k nodes are labeled v1.2 milestone, we won't lose track of them. Please make sure they are labeled as such.

**Comment by alex-mohr** [comment]
Fair enough
