### ISSUE TITLE
Differentiate ResourceVersion by collection

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#20841]
It's bad when clients take a RV from one collection (e.g. pods) and list/watch on another collection (e.g., services). It's already caused some bugs with the cacher, and if we shard storage by collection it could be a bigger disaster. Therefore, we should take steps now to get clients out of the habit of doing this.

My idea is to just add some string, maybe just a letter or two, different by collection, and if we get a string that doesn't match we can reject the request or ignore the RV.

@wojtek-t @smarterclayton Thoughts?

**Comment by derekwaynecarr** [comment]
sgtm

**Comment by smarterclayton** [comment]
Would need to ensure it's backwards compatible for clients that assume
version is a number.  I would prefer to do it at a higher level, because we
have use cases today where we have resources in the same group but
different collections that *must* coordinate, and so we specify that as a
requirement.  I agree we want to discourage accidental use.

**Comment by smarterclayton** [comment]
Use cases in openshift resources across two collections which are required
to be on the same etcd store.

**Comment by lavalamp** [comment]
Should any clients be making that assumption? We document this like you should treat it as an opaque blob. I don't think clients should even be parsing it.

I could see doing something by storage backend instead of by collection, but it's still invalid for clients to pass the things between collections, and that won't help that.

**Comment by wojtek-t** [comment]
As I mentioned when talking with @lavalamp f2f (and what Clayton wrote above), we need to think about backward compatibility. But in general the idea sounds good.

**Comment by smarterclayton** [comment]
I would recommend we not try to do this for 1.2 - let's save the subtle
breaking things for the next release.

On Tue, Feb 9, 2016 at 8:42 AM, Wojciech Tyczynski <notifications@github.com

**Comment by wojtek-t** [comment]
+1

**Comment by lavalamp** [comment]
Sure. Then we should audit where we pass RV to list methods; it's been wrong in two places so far--subtle breakage is possibly already out there...

**Comment by wojtek-t** [comment]
Sure, although after the recent bug I looked into all places where I added it and there are only few of them now. And in my opinion they look ok.

**Comment by lavalamp** [comment]
Great. We can do something on this for 1.3 then.
