### ISSUE TITLE
bash stack trace in go-build failure is excessive

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#20849]
It takes up my entire screen and I have to scroll up to see what actually failed to compile. The information in the trace doesn't seem useful.

hack/build-go.sh 
+++ [0208 13:04:14] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubemark
    cmd/hyperkube
    cmd/linkcheck
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/integration
    cmd/gendocs
_output/local/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:203: cannot use s.KubeControllerManagerConfiguration.ServiceSyncPeriod (type "k8s.io/kubernetes/pkg/api/unversioned".Duration) as type time.Duration in argument to serviceController.Run
_output/local/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:203: cannot use s.KubeControllerManagerConfiguration.NodeSyncPeriod (type "k8s.io/kubernetes/pkg/api/unversioned".Duration) as type time.Duration in argument to serviceController.Run
_output/local/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:213: cannot use &s.KubeControllerManagerConfiguration.ClusterCIDR (type _string) as type *"net".IPNet in argument to route.New
_output/local/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:214: cannot use s.KubeControllerManagerConfiguration.NodeSyncPeriod (type "k8s.io/kubernetes/pkg/api/unversioned".Duration) as type time.Duration in argument to routeController.Run
_output/local/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:222: cannot use s.KubeControllerManagerConfiguration.ResourceQuotaSyncPeriod (type "k8s.io/kubernetes/pkg/api/unversioned".Duration) as type time.Duration in argument to controller.StaticResyncPeriodFunc
_output/local/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/plugins.go:48: undefined: options.VolumeConfigFlags
_output/local/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/plugins.go:91: undefined: options.VolumeConfigFlags
_output/local/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:222: too many errors
!!! Error in /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/hack/lib/golang.sh:395
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${goldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
Call stack:
  1: /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/hack/lib/golang.sh:395 kube::golang::build_binaries_for_platform(...)
  2: /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/hack/lib/golang.sh:537 kube::golang::build_binaries(...)
  3: hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/hack/lib/golang.sh:458
  '( kube::golang::setup_env; local host_platform; host_platform=$(kube::golang::host_platform); local goflags goldflags; eval "goflags=(${KUBE_GOFLAGS:-})"; goldflags="${KUBE_GOLDFLAGS:-} $(kube::version::ldflags)"; local use_go_build; local -a targets=(); local arg; for arg in "$@";
do
    if [[ "${arg}" == "--use_go_build" ]]; then
        use_go_build=true;
    else
        if [[ "${arg}" == -_ ]]; then
            goflags+=("${arg}");
        else
            targets+=("${arg}");
        fi;
    fi;
done; if [[ ${#targets[@]} -eq 0 ]]; then
    targets=("${KUBE_ALL_TARGETS[@]}");
fi; local -a platforms=("${KUBE_BUILD_PLATFORMS[@]:+${KUBE_BUILD_PLATFORMS[@]}}"); if [[ ${#platforms[@]} -eq 0 ]]; then
    platforms=("${host_platform}");
fi; local binaries; binaries=($(kube::golang::binaries_from_targets "${targets[@]}")); local parallel=false; if [[ ${#platforms[@]} -gt 1 ]]; then
    local gigs; gigs=$(kube::golang::get_physmem); if [[ ${gigs} -ge ${KUBE_PARALLEL_BUILD_MEMORY} ]]; then
        kube::log::status "Multiple platforms requested and available ${gigs}G >= threshold ${KUBE_PARALLEL_BUILD_MEMORY}G, building platforms in parallel"; parallel=true;
    else
        kube::log::status "Multiple platforms requested, but available ${gigs}G < threshold ${KUBE_PARALLEL_BUILD_MEMORY}G, building platforms in serial"; parallel=false;
    fi;
fi; if [[ "${parallel}" == "true" ]]; then
    kube::log::status "Building go targets for ${platforms[@]} in parallel (output will appear in a burst when complete):" "${targets[@]}"; local platform; for platform in "${platforms[@]}";
    do
        ( kube::golang::set_platform_envs "${platform}"; kube::log::status "${platform}: go build started"; kube::golang::build_binaries_for_platform ${platform} ${use_go_build:-}; kube::log::status "${platform}: go build finished" ) &> "/tmp//${platform//\//_}.build" &
    done; local fails=0; for job in $(jobs -p);
    do
        wait ${job} || let "fails+=1";
    done; for platform in "${platforms[@]}";
    do
        cat "/tmp//${platform//\//_}.build";
    done; exit ${fails};
else
    for platform in "${platforms[@]}";
    do
        kube::log::status "Building go targets for ${platform}:" "${targets[@]}"; kube::golang::set_platform_envs "${platform}"; kube::golang::build_binaries_for_platform ${platform} ${use_go_build:-};
    done;
fi )' exited with status 1
Call stack:
  1: /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/hack/lib/golang.sh:458 kube::golang::build_binaries(...)
  2: hack/build-go.sh:26 main(...)
Exiting with status 1
make: **\* [all] Error 1

**Comment by therc** [comment]
On the scale of annoyances alone, this is a P-1.
