### ISSUE TITLE
Make hack/e2e.go work with other providers

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20861]
Per @timothysc's https://github.com/kubernetes/kubernetes/pull/20758#discussion_r52209174.

**Comment by ihmccreery** [comment]
(To be clear, I'm not sure what the state of this is; I know it works on GKE and GCE, but not sure about elsewhere.  @spiffxp? or @jayunit100?)

**Comment by ihmccreery** [comment]
cc @kubernetes/sig-testing

**Comment by jayunit100** [comment]
I was under the impression the goal was to decouple deployment from e2e... Right?  If we do this, we are going to immortalize hack/e2e....?

**Comment by spiffxp** [comment]
Perhaps I'm being too conservative but it seems like a good step to first stabilize the patient.  To even get hack/e2e.go to work consistently across providers will help us better judge what is provider-specific vs. deployment-specific behavior

**Comment by justinsb** [comment]
Well, I use it through e2e.sh, but it works on AWS.  Happy to check anything specific...

**Comment by jayunit100** [comment]
by "make it work " we mean "make the testing part work"? That makes sense. 

Otherwise we will be chasing our tail regarding the other requirement of eventually decoupling deploy from test.

**Comment by spiffxp** [comment]
What remains to be done here?  We've more or less consolidated on hack/e2e.go as The One True Way to run e2e tests, and I've seen tests run (if not pass) against AWS.

There are a variety of assumptions non-conformance e2e tests make that don't necessarily work on cloud providers other than gce/gke, is that what this is about?  Or is that blowing scope here?

**Comment by spxtr** [comment]
This can probably be closed. `e2e.go` should work anywhere k8s works.

**Comment by spiffxp** [comment]
What do we think about closing this?  The skeleton provider could stand to be a little more fully fleshed out to support more e2e's than conformance (eg: those that require SSH access), but that's a separate issue
