### ISSUE TITLE
Remove On-Call docs from wiki

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#20860]
Now subsumed by `docs/devel/on-call-*.md`

Someone with edit rights to the wiki will need to remove these pages:

https://github.com/kubernetes/kubernetes/wiki/Kubernetes-on-call-rotations
https://github.com/kubernetes/kubernetes/wiki/Github-and-Build-Cop-Rotation
https://github.com/kubernetes/kubernetes/wiki/User-Support-Rotation

ref #20345
/cc @kubernetes/sig-testing @ihmccreery

**Comment by ihmccreery** [comment]
Done.
