### ISSUE TITLE
Eliminate float max/min from Deployment

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#20863]
Forked from https://github.com/kubernetes/kubernetes/pull/20368#discussion_r51837534

Go's standard library doesn't include integer min/max functions. The float versions were used in several places in Deployment's implementation. We should create some integer min/max functions in util to avoid this.

cc @kargakis @janetkuo @mqliang

**Comment by bgrant0607** [comment]
I think this is done.

**Comment by lavalamp** [comment]
Yeah I gave you the standard line from go's authors of "just write an if,
it's not that hard".

I guess it is that hard. This is tons better than people using the float
max/min functions, so I won't complain.
