### ISSUE TITLE
e2e flake: error creating e2e-gce-minion-template

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#20878]
https://console.developers.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/11228/

My reading is that the first attempt to create e2e-gce-minion-template looks like it failed with "Backend error", but it seems that the template was actually created, so subsequent attempts failed because it already existed.

```
Attempt 1 to create e2e-gce-minion-template
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks/persistent-disks#pdperformance.
ERROR: (gcloud.compute.instance-templates.create) Some requests did not succeed:
 - Backend Error
 
Attempt 1 failed to create instance template e2e-gce-minion-template. Retrying.
Attempt 2 to create e2e-gce-minion-template
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks/persistent-disks#pdperformance.
ERROR: (gcloud.compute.instance-templates.create) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-e2e-gce/global/instanceTemplates/e2e-gce-minion-template' already exists
 
Attempt 2 failed to create instance template e2e-gce-minion-template. Retrying.
...
```

**Comment by bgrant0607** [comment]
From @ixdy:
kubernetes-e2e-gce/11227 claims to have deleted:
```
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce/global/instanceTemplates/e2e-gce-minion-template].
```

But it apparently wasn't.

Looks like we need to improve handling of this:
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L360
```
# First, ensure the template doesn't exist.
# TODO(zmerlynn): To make this really robust, we need to parse the output and
# add retries. Just relying on a non-zero exit code doesn't
# distinguish an ephemeral failed call from a "not-exists".
```

cc @zmerlynn 

There were previous attempts to make instance template more robust, such as in #8014.

**Comment by bgrant0607** [comment]
And, after this failed, the subsequent test run failed the leaked-resource check.

**Comment by zmerlynn** [comment]
Ha, an old @mbforbes TODO strikes again. :)

**Comment by zmerlynn** [comment]
It's actually pretty disturbing that `gcloud` claimed `Deleted` when it wasn't. There may be an internal bug here, since the name should be available for use if delete occurred, in theory.

**Comment by davidopp** [comment]
@roberthbailey Do you think someone from your team could take a look at this one?

**Comment by justinsb** [comment]
It sounds like the hypothesis is that the delete failed in 11227, but gcloud reported 'deleted'.

But the `Backend Error` failure message from the first create operation in 11228 is one I haven't seen before:

```
Attempt 1 to create e2e-gce-minion-template
<snip>
ERROR: (gcloud.compute.instance-templates.create) Some requests did not succeed:
 - Backend Error

Attempt 1 failed to create instance template e2e-gce-minion-template. Retrying.
```

`Backend error` reads to me as "something went wrong, I don't know the state of the world".  It looks like the template was created OK (ish), but we try recreating with the same name which then fails (as expected).

Is there evidence that the delete actually failed in 11227?

My inclination would be that we should have a retry loop that looks more like:

```
attempt := 0
for {
  attempt++
  if exists() {
    break
  }
  if attempt > maxAttempts {
    error()
  }
  created, err := create()
  if err {
    warn(err)
  }
  if created {
    break
  }
}
```

(That is go-bash; neither go nor bash.  Just be grateful there's no salt in there!)

**Comment by roberthbailey** [comment]
@zmerlynn - can you take a look at this one this morning?

**Comment by zmerlynn** [comment]
I was out this morning but I'll see if I can look into it later this afternoon.

**Comment by davidopp** [comment]
ping

**Comment by wojtek-t** [comment]
This just happened again:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4859/console

I'm going too apply P0 label to the PR that is supposed to fix it.

**Comment by ixdy** [comment]
Ah, this is the same as #22029. We created an internal bug for this too, ref 27367941.
