### ISSUE TITLE
update-api-reference-docs needs to do all groups

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#20877]
It's not obvious how to add more groups to this file. This blocks job & hpa moves.

https://github.com/kubernetes/kubernetes/blob/master/hack/update-api-reference-docs.sh#L43

@nikhiljindal or @caesarxuchao, this file looks like yours. Can one of you make it take a list of groups like other similar files?

**Comment by caesarxuchao** [comment]
I'll refactor it.

**Comment by lavalamp** [comment]
Thank you!!
