### ISSUE TITLE
e2e: Kubelet becomes unresponsive because docker ps hangs

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#20876]
This is *not* a new issue, and it has been mentioned in many flaky test issues and has hosed our soak cluster multiple times. Creating a new issue so that we have one place to update/refer.

The *best* way to spot such a failures is to open `supervisord.log` of the nodes. You will see docker being restarted *many times* due to failed health checks. 
```
2016-02-09 01:12:50,975 INFO exited: docker (exit status 2; expected)
2016-02-09 01:12:51,977 INFO spawned: 'docker' with pid 7415
2016-02-09 01:12:53,009 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-02-09 01:14:12,016 INFO exited: docker (exit status 2; expected)
2016-02-09 01:14:13,018 INFO spawned: 'docker' with pid 7861
2016-02-09 01:14:14,047 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-02-09 01:15:33,052 INFO exited: docker (exit status 2; expected)
2016-02-09 01:15:34,055 INFO spawned: 'docker' with pid 8099
2016-02-09 01:15:35,086 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-02-09 01:16:54,091 INFO exited: docker (exit status 2; expected)
2016-02-09 01:16:55,093 INFO spawned: 'docker' with pid 8291
2016-02-09 01:16:56,121 INFO success: docker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Note that this issue is believed to be a kernel bug and cannot be solved by restarting docker (hence the multiple restarts in the log). The only way to fix it is to reboot the node.

xref: https://bugzilla.kernel.org/show_bug.cgi?id=81211, https://github.com/docker/docker/issues/5618

**Comment by ncdc** [comment]
cc @timothysc @jeremyeder @kubernetes/rh-cluster-infra

**Comment by jeremyeder** [comment]
@ncdc has anyone on our network team looked at those 2 issues?

**Comment by timothysc** [comment]
@jeremyeder @yujuhong is this different from - https://bugzilla.redhat.com/show_bug.cgi?id=880394#c7 ?

**Comment by ncdc** [comment]
@jeremyeder not sure. I just remember you taking a look at the bz Tim linked above, so I thought I'd cc you.

**Comment by jeremyeder** [comment]
I will bring them in.

**Comment by yujuhong** [comment]
> @jeremyeder @yujuhong is this different from - https://bugzilla.redhat.com/show_bug.cgi?id=880394#c7 ?

Looks the same to me, but I don't have much insight on the cause of failure. 

@kubernetes/goog-cluster is trying to reproduce this since we've been hitting this way too often.  Any help is appreciated.

**Comment by yujuhong** [comment]
By the way, I was able to reproduce this by running docker-stress in https://github.com/docker/docker/issues/17443

**Comment by dchen1107** [comment]
I am closing this one as dup of https://github.com/kubernetes/kubernetes/issues/20096. Please reopen it if you disagree. Thanks!

**Comment by alok87** [comment]
@yujuhong Were you able to solve this? This kernel bug was solved in which version? I am facing the exact same issue and my kernel version is `4.4.78-k8s`

**Comment by yujuhong** [comment]
@alok87, please see #20096. A workaround was added to kubelet to avoid triggering this issue long ago. Please open a new issue if you are still seeing this with a recent kubernetes version (1.5+).

**Comment by alok87** [comment]
@yujuhong yes it reoccured, couple of times for us under huge load. Not occurred very recently. We are on latest version 1.7.6

**Comment by yujuhong** [comment]
@alok87 are you using the GCP+CVM image? If so, you may want to move to an image with a newer kernel. The CVM image has been deprecated

**Comment by nailgun** [comment]
I've this issue too on GKE.

Node version	1.8.1-gke.1
Node image	Container-Optimized OS (cos)

`kubectl describe node` shows this event:
`Warning  UnregisterNetDevice  3s (x14245 over 1d)  kernel-monitor, gke-c1-cpu8-mem52-e7a9e3b3-3w22  unregister_netdevice: waiting for eth0 to become free. Usage count = 21`

And I can't terminate any pods on this node. Just migrated to GKE and this instability terrifies me. 

Please reopen the issue.
