### ISSUE TITLE
Modify E2E tests to use the GCE API instead of gcloud exec

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#20885]
PR https://github.com/kubernetes/kubernetes/pull/17747 laid the ground work to enable E2E tests to use the GCE API instead of gcloud exec. That PR only modified the PD tests to do so.

In order to make E2E more robust, we should switch over all other instances of gcloud exec in E2E tests to use the GCE API instead.

**Comment by spiffxp** [comment]
/assign
closing in favor of #13535
