### ISSUE TITLE
Heapster's user agent string is wrong

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#20888]
Seen in logs: `heapster/v0.0.0 (linux/amd64) kubernetes/$Format`

**Comment by mwielgus** [comment]
@lavalamp what logs?

**Comment by lavalamp** [comment]
This is in my own GKE apiserver logs. Kubernetes 1.1.7. Maybe it's fixed already?

**Comment by mwielgus** [comment]
Probably. Please reopen if not.
