### ISSUE TITLE
Switch to Docker's engine-api

### ISSUE THREAD

**Issue by cyphar** [kubernetes/kubernetes#20895]
Currently, we are using fsouza/go-dockerclient to talk to the Docker daemon. However, this is causing us issues (#16670) and will undoubtedly cause even more. Docker has released [an official, supported way of communicating with a Docker daemon using the API](https://github.com/docker/engine-api), it's written in Go and it shouldn't be too difficult to swap go-dockerclient with engine-api.

**Comment by vishh** [comment]
+1. @cyphar will you be able to post a patch?

**Comment by cyphar** [comment]
I'll take a look at this over the weekend.

**Comment by Random-Liu** [comment]
@cyphar Thanks for doing this. :)

**Comment by vishh** [comment]
@cyphar: Were you able to make any progress?

**Comment by cyphar** [comment]
@vishh Unfortunately no, there's a lot of things that need to be updated. Sorry for not posting an update.

**Comment by Random-Liu** [comment]
Hi, @cyphar~ I'll start working on this. Would you mind I close this one, and track this issue here #23563?

**Comment by cyphar** [comment]
Sure.

**Comment by Random-Liu** [comment]
@cyphar Thanks! :)
