### ISSUE TITLE
Containers In a pod should run with the same SELinux Context

### ISSUE THREAD

**Issue by swagiaal** [kubernetes/kubernetes#20899]
Docker containers which share the same IPC namespace are given the same SELinux label by docker. This is not the case though for containers within a pod which do not end up with the same SELinux label even though they share the IPC namespace of the infra container.

If this is fixed then SELinux relabeling for volumes (through the docker :Z flag) can be turned on by default for all pods. Since all containers within the pod will end up sharing the same SELinux label which is randomly assigned by Docker to the infra container.

please assign to me

**Comment by spiffxp** [comment]
/sig node
since the issue referencing this was tagged with sig/node
