### ISSUE TITLE
"kubectl exec" does not like "=" in command passed to it

### ISSUE THREAD

**Issue by deepaktawri** [kubernetes/kubernetes#20898]
"kubectl exec <podname> date --date=5/5/1925" gives error --date as invalid option.

kubectl does not seem to like = in whatever command passed to it.

**Comment by ncdc** [comment]
@deepaktawri you can use `--` to separate arguments you pass to `kubectl exec` from arguments you want to pass to the command you're executing. For example:

```
kubectl exec mypod -- date --date=5/5/1925
```

**Comment by deepaktawri** [comment]
Thank you. It worked!
