### ISSUE TITLE
kubect logs on pod should show available containers

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20915]
What are the names of the containers?
```
$ kubectl logs kube-dns-v10-iinak --namespace=kube-system
Error from server: a container name must be specified for pod kube-dns-v10-iinak
```

**Comment by bprashanth** [comment]
Fyi till now I've resorted to -o yaml, which I usually jump to anytime kubectl doesn't do what I expect

**Comment by sliranc** [comment]
Which version are you running ?

its working for me and I am running version 1.1.3

kubectl --namespace=kube-system logs influxdb-grafana-nr1it
error: Pod influxdb-grafana-nr1it has the following containers: influxdb, grafana; please specify the container to print logs for with -c

**Comment by bprashanth** [comment]
Yeah this is fixed
