### ISSUE TITLE
SSH access required to nodes for e2e tests

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#20919]
Followup from @kubernetes/sig-testing meeting

We'd prefer to avoid ssh access if at all possible; some tests can probably be re-written to use kubernetes features to accomplish the same thing

For those cases where we need SSH access, the test code assumes that the cluster has been stood up via the salt-based clusters code; SSH access is tied to certain cloud providers, and hardcoded key locations / env vars

SSH access should be orthogonal to the cloud provider, I think?  

For a first step was thinking look for `KUBE_SSH_KEY` and `KUBE_SSH_USER` env vars before falling back to old behavior of hardcoded assumptions.  This will mean redoing the `providersWithSSH` check that a few tests use.

**Comment by erictune** [comment]
Agree some uses of SSH in tests can be eliminated (some were written before `kubectl exec` existed.

Of the remaining tests, from what I recall, there are two uses cases. One is using ssh to help diagnose why the test is failing: these can be made optional when running on a cloud provider that doesn't support SSH.  The other is checking that things work when components are restarted/upgraded/fail.  It might be necessary to label this type of test as `[Availability]` and just say that `[Availability]` tests are not expected to run on every platform.

**Comment by spiffxp** [comment]
It might be useful to differentiate "ssh access to nodes" vs. "ssh access to a special thing called master that has kubernetes deployed in an assumed manner"

**Comment by jeffvance** [comment]
@erictune @spiffxp I'm writing an e2e test to verify that host mounts and the host pod's uid dir are removed when a pod is deleted under non-ideal conditions. This is to support issue #31272. If it is recommended to not use ssh  (I also want to support "local" as a provisioner) then can you suggest or point me to the preferred way to run a shell command on a host? Eg. I was thinking of executing _/usr/bin/ls_ and _/usr/bin/mount |grep nfs_ on the target host.

**Comment by spiffxp** [comment]
/sig testing
I'm not sure we're solving this any time soon, but I still think it's test hygiene worth advocating
