### ISSUE TITLE
Scrape jenkins results from publicly accessible buckets instead of private jenkins instance

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#20921]
Followup from @kubernetes/sig-testing meeting

We're looking at the idea of using GCS buckets as the basis for federated test result collection.  ref: kubernetes/contrib#467, kubernetes/contrib#477

We'd like to see perf-dash and submit-queue using publicly accessible data, rather than data that only lives on private jenkins instance.  It seems like this should be doable now with improvements to testing over the past few weeks.

**Comment by wojtek-t** [comment]
As for perf-dash, it should definitely be doable. What it is currently doing, it is reading data from Jenkins logs and creating a csv file somewhere, which is then being read by the front-end. We should just place this csv in a public location.

@gmarek

**Comment by gmarek** [comment]
It's not working exactly as @wojtek-t - we're generating JSON objects, but that's not important. I'll do this for perfdash in some free cycles (maybe today, maybe next week), though it'll be more of a duct tape.

I think that we should uniformize the output for various summaries and generalize contrib/compare/src/scraper.go to handle all of them. It's probably a couple days worth of work, so it'll need to wait.

**Comment by spiffxp** [comment]
what do we think about closing this? /cc @kubernetes/sig-testing 

AFAIK this has been done a while, and the results format is documented at https://github.com/kubernetes/test-infra/blob/master/docs/federated_testing.md

**Comment by ixdy** [comment]
It's fun finding all of the old issues we've already fixed.
