### ISSUE TITLE
Allow cloud loadbalancers to terminate HTTPS

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#20927]
I'm not sure if GCE can do it, but AWS' ELB can be told to have listeners that terminate SSL connections with an existing IAM certificate. It would be great to allow that.

**Comment by therc** [comment]
I'm assuming this would require adding something like a "certificate" field to ServicePort, then perhaps a targetProtocol, to tell ELB whether to talk over HTTPS or plain HTTP to the pod.

**Comment by bprashanth** [comment]
Yeah this will be possible via the Ingress in 1.2 https://github.com/kubernetes/kubernetes/issues/19497 (already in HEAD). We're not at the stage where we can express SNI/L4 yet, but will also be possible soon.

**Comment by therc** [comment]
Do you need help with the AWS code? We run HEAD, plus whatever PRs I might have outstanding at any time, plus perhaps a few more. :-) I assumed the Ingress stuff was about implementing load balancing inside Kubernetes, not using cloud providers.

**Comment by therc** [comment]
One use case I don't see mentioned in the Ingress TLS work is where the certificate credentials are in the cloud provider already and you can only refer to them by name (if you use IAM's Certificate Manager, you can't ever take them out, only use them on ELBs and CloudFront).

**Comment by bprashanth** [comment]
> One use case I don't see mentioned in the Ingress TLS work is where the certificate credentials are in the cloud provider already and you can only refer to them by name (if you use IAM's Certificate Manager, you can't ever take them out, only use them on ELBs and CloudFront).

You mean you can't create a Kubernetes secret for them? the way to handle that would be to add an k8s.io/aws/credential annotation that points to them, and is understood by the Ingress controller (ignored by non aws controllers), i think. The Ingress is supposed to hold information that is common and understood by nginx/haproxy, gce, aws etc. We need to bring in integration points that "break the glass" as annotations, third party resource or config data objects. 

> Do you need help with the AWS code? We run HEAD, plus whatever PRs I might have outstanding at any time, plus perhaps a few more. :-) I assumed the Ingress stuff was about implementing load balancing inside Kubernetes, not using cloud providers.

Yes please. There is actually community interest on the same topic: https://github.com/kubernetes/contrib/issues/346.

**Comment by therc** [comment]
I meant that the private key for the certificate is locked inside CM and you can't terminate traffic yourself. That's both a big minus and a big plus.

I didn't realise that the actual Ingress controller lived outside of the main tree. I'll have a look at the contrib issue. Thanks a lot!
