### ISSUE TITLE
discovery summarizer: should it merge swagger spec from all servers

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#20935]
Ref https://github.com/kubernetes/kubernetes/issues/20229

We didnt discuss this in the federated servers proposal.
Do we need a single complete swagger spec of the federated cluster? So that the same client (which might use swagger spec, for ex: kubectl) can work the same way with a single server or with a federated cluster?

The summarizer will fetch spec from all servers, summarize them and expose it at `/swagger-spec`.

Thoughts?

@lavalamp @smarterclayton @kubernetes/sig-api-machinery @bgrant0607 @kubernetes/kubectl

**Comment by smarterclayton** [comment]
Hrm - what happens if two swagger routes / names / models conflict?

**Comment by nikhiljindal** [comment]
We can drop the conflicting routes from the summary ( for ex: `/version`) ?
Otherwise proxy does not know where to redirect. (for ex: `<proxyIP>/version` should go to which server?).

Re: conflicting models: We can include any one if they are exactly same (for ex: I assume `Status` is an example which will be same across servers). Else we can probably add a prefix to model names based on the server (models from same server have same prefix).

This is definitely considerable work.

An alternative is that kubectl has a set of swagger specs and it tries to validate the resource using all of them. If it is valid as per any spec, then it is valid. Else not.

**Comment by smarterclayton** [comment]
Each API group owns it's swagger spec. Why are we not just having
kubectl use the spec for a given groupversion?  Why do we need to
merge?

Kubectl already has abstraction for schema per group version, I don't
know why we would need an additional layer.  Merging sounds like it
isn't going to actually make the problem easier.

And ultimately, a swagger doc isn't required for kubectl to function,
so if an extension doesn't have one it seems like you just don't do
whatever the path action is.

The original spec here is to do the minimum possible for a client to
find all group versions the admin wants to expose.  We can probably
put this in the "we don't need this yet" bucket

**Comment by bgrant0607** [comment]
I agree with @smarterclayton. 

We don't want to merge swagger specs, IMO. We should expose group-specific swagger API paths. We need to change to versioned paths (i.e., swagger version), as well.

**Comment by lavalamp** [comment]
I agreed with both of you guys initially and even suggested splitting it by
group, but Nikhil pointed out that if it's merged, you can use swagger told
to generate complete clients. It sounds hard to me, though. I think we
should worry about this only after we get kubectl working through the
proxy/discoverizer.

**Comment by smarterclayton** [comment]
Well, two groups can have the same sub model name for a struct that
don't have the same schema, so I don't think merging works without
transformation of some form. Either way, it seems like we're in
agreement that we can discuss it in 1.3

**Comment by liggitt** [comment]
-1 on merging specs

**Comment by liggitt** [comment]
Aggregator attempts to merge openapi schemas now
