### ISSUE TITLE
federated api servers: expose a discovery endpoint for possible api prefixes

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#20933]
Forked from https://github.com/kubernetes/kubernetes/pull/20626#issuecomment-182093497

In a federated api servers setup, cluster admin can bring up a new server that exposes its groups at some other location than `/apis`. Discovery and Dynamic client wont know that there is a new prefix in the cluster that they should use to figure out the list of all resources in the cluster.

One way to fix this is to add another discovery endpoint which lists all api group prefixes in the cluster. Discovery client can then look at that endpoint to become aware of the new prefix.

Thoughts?

@lavalamp @smarterclayton @kubernetes/sig-api-machinery

**Comment by nikhiljindal** [comment]
Actually rereading https://github.com/kubernetes/kubernetes/issues/18991, it seems we do not want to allow different api prefixes. We will only support legacy servers (/api and /oapi).
I can close this issue in that case?

**Comment by smarterclayton** [comment]
I don't think discovery of discovery is important.  I think
unambiguous config of the summarizer (use these endpoints) is the
normal case, and eventually that would just be an API instead.
