### ISSUE TITLE
Make kubectl describers and resource printers more consistent

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#20941]
Noticed when reviewing #20886

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe.go

Describers should all print object metadata consistently (name, namespace if relevant, labels).

All controllers should print at least pod templates the same way -- using DescribePodTemplate.

I'm sure there are other opportunities to improve consistency. I just noticed these differences at a glance.

The resource printers (for get) are also inconsistent. @AdoHe has been improving on them (e.g., #20557, #20409).

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go

cc @kubernetes/kubectl @mqliang @erictune @mikedanese @janetkuo @kargakis @madhusudancs @AdoHe

**Comment by AdoHe** [comment]
@bgrant0607 I can do more work to improve consistence should I start working on this?

**Comment by bgrant0607** [comment]
@AdoHe That would be great, but let's get your existing PRs in and also wait for the initial ReplicaSet implementation to be merged.

**Comment by bgrant0607** [comment]
I just noticed another inconsistency: job, ingress, daemonset don't have AGE columns.

**Comment by AdoHe** [comment]
@bgrant0607 I will add this after these two PRs(#21369, #21295 ) get merged.

**Comment by smarterclayton** [comment]
Here's the annotation output we use in Origin:

```
func formatAnnotations(out *tabwriter.Writer, m api.ObjectMeta, prefix string) {
	values, annotations := extractAnnotations(m.Annotations, "description")
	if len(values[0]) > 0 {
		formatString(out, prefix+"Description", values[0])
	}
	formatMapStringString(out, prefix+"Annotations", annotations)
}
```

We haven't formally defined description (yet) so it's really:

```
func formatMapStringString(out *tabwriter.Writer, label string, items map[string]string) {
	keys := sets.NewString()
	for k := range items {
		keys.Insert(k)
	}
	if keys.Len() == 0 {
		formatString(out, label, "")
		return
	}
	for i, key := range keys.List() {
		if i == 0 {
			formatString(out, label, fmt.Sprintf("%s=%s", key, items[key]))
		} else {
			fmt.Fprintf(out, "%s\t%s=%s\n", "", key, items[key])
		}
	}
}
```

**Comment by smarterclayton** [comment]
We probably want special handling on annotations to deal with very long annotations (trim past a certain length) and to deal with newlines and ansi escape sequences (we may have to strip them)

**Comment by AdoHe** [comment]
@smarterclayton ok, I will think about this more.

**Comment by timbunce** [comment]
Meanwhile, for those who find their way here and want a quick workaround `kubectl get service $foo -o yaml | grep "key:"` is basic and `kubectl get service apex-main -o json | jq .metadata.annotations` is smarter.

**Comment by zjj2wry** [comment]
ref #52484
