### ISSUE TITLE
Update the master branch constant for doc generation

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20946]
New release series only happen every three months, so this isn't particularly important, but would be nice to streamline.  Will add more xrefs as I build out docs.

**Comment by david-mcmahon** [comment]
There are [two items](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/releasing.md#manual-tasks-for-new-release-series) here:

1. Update latestReleaseBranch in mungedocs.go - This is done automatically as part of the upcoming release automation now.  I'll ref this issue when things finally land in kubernetes/release.
1. Jenkins config updates are handled by the test team. (cc: @ixdy @spxtr @fejta)

This is effectively done.  I'll leave this open until the new tooling is checked in.

**Comment by david-mcmahon** [comment]
Filed #24639 to address the jenkins step.  Resetting this to track the latestReleaseBranch change (which is already done in https://github.com/kubernetes/release/pull/1 but not submitted yet).

**Comment by david-mcmahon** [comment]
https://github.com/kubernetes/release/issues/1
