### ISSUE TITLE
Mysql-wordpress-pd example needs improvement

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#20949]
https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-wordpress-pd

The example doesn't follow best practices: #11361.
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/config-best-practices.md

Some of these practices are newer than the example, and it needs to be updated. For instance, it shouldn't use `name` as a label key.

More significantly, now that we have [persistent volume provisioning](https://github.com/kubernetes/kubernetes/tree/master/examples/experimental/persistent-volume-provisioning), we should make it provider-independent. Perhaps we could put a GCE-specific PD example in the GCE getting-started guide.

The biggest problem with the example is that it creates a naked Pod, which isn't self-healing.
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/config-best-practices.md#naked-pods-vs-replication-controllers-and-jobs
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/pods.md#durability-of-pods-or-lack-thereof

If we want to start with a pod for explanatory purposes, we need to follow up with an explanation of why that's not sufficient, and show the recommended solution. In 1.2, that will be to use a single-replica Deployment. In 1.3, it will probably be PetSet.

cc @amygdala

**Comment by bgrant0607** [comment]
We should use Secret for the password, also.

**Comment by bprashanth** [comment]
I wanted to re-write this example using ghost (essentially the blogging part of wordpress without the CMS etc: https://hub.docker.com/_/ghost/) because it's a lot simpler to start with. 

My idea was to start with a single container, then add a database (even sqllite using emptydir), then grow it to mysql + pv in a different service, then add ingress in front. Additionally we can configure ghost with a config data object. 

Just a suggestion, the two examples can obviously co-exist.

**Comment by amygdala** [comment]
@bprashanth Those sound like two different demos to me, but that would be an interesting one.

@bgrant0607 Brian - yes, the example is pretty old.  Plus, it would be great to confirm that we could get it to run properly on AWS.
I assigned it to myself. To double check- assuming you meant, 'put a GCE-specific example in the GKE getting started guide'?

**Comment by bgrant0607** [comment]
Maybe @johndmulhausen has a better suggestion regarding where we should put user-focused, cloud-provider-specific examples. It would be cool to be able to select from a cloudprovider drop-down menu: "Show me this example for: GCE/AWS/Azure/...".

**Comment by bgrant0607** [comment]
@amygdala Let's decide which examples we want to focus on in the short term before we work on any specific example.

**Comment by amygdala** [comment]
@bgrant0607 SG.

**Comment by bprashanth** [comment]
What I didn't like about the wordpress example the first time I read it (a year ago) was that it hid complexity. The image on dockerhub is writtent to honor certain environment variables (https://hub.docker.com/_/wordpress/), one of which we employ to discover the mysql service. This is not the case for most other images out there.

**Comment by jeffmendoza** [comment]
@bprashanth Ghost is sweet, having both examples would be good. About the wordpress docker image, since it is the "official" dockerhub image, It seems like using the expected env vars and hostnames to connect to the database should be acceptable. It looks nicely documented there on the hub.

**Comment by jeffmendoza** [comment]
WIP: https://github.com/jeffmendoza/kubernetes/tree/wordpress-update/examples/mysql-wordpress-pd

**Comment by bprashanth** [comment]
>It seems like using the expected env vars and hostnames to connect to the database should be acceptable. It looks nicely documented there on the hub.

Oh, no it is, and it's totally fine to do it this way. Just that people need one example they can refer to for "how do i setup a website on kubernetes". Till now that has been wordpress, and wordpress falls short because of the env var simplification because most prepackaged web-app frameworks (eg: django) are configured to point to a db via config file.

**Comment by jeffmendoza** [comment]
Ah I see. Sounds like we need a django example.

**Comment by jeffmendoza** [comment]
This has been fixed for a while, please close
#22195
