### ISSUE TITLE
AWS volume auto-provision not working

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#20955]
I think AWS volume auto-provision is not working, last I checked because the provider now attempts to resolve the volume template with a name of "dummy" and fails.

Two things to check:

1) That it works again
2) That auto-labelling of zones works with Ubernetes-Lite

**Comment by justinsb** [comment]
(this is mostly a note to remember to file a proper bug report and/or fix this...)

**Comment by markturansky** [comment]
@kubernetes/rh-storage

**Comment by bprashanth** [comment]
@justinsb assigning to you till you've had a chance to report back with verification and next steps

**Comment by bprashanth** [comment]
Closing this as a dupe of https://github.com/kubernetes/kubernetes/issues/21041, please re-open if you disagree

**Comment by justinsb** [comment]
I'd rather leave it open to make sure this gets fixed for AWS if that's OK?  It is assigned to me...

**Comment by saad-ali** [comment]
This should be fixed by https://github.com/kubernetes/kubernetes/pull/21738
Re-open if it is not.

**Comment by justinsb** [comment]
Thanks for the fix!

I'm going to reopen while I verify that it works with Ubernetes-Lite...

Also note to self... make sure that the created PV has a fully qualified volume name ("aws://az/vol-123456", not just "vol-123456"

**Comment by markturansky** [comment]
@jsafrane see Justin's note above about fully qualified volume name.

**Comment by justinsb** [comment]
I'm actually not sure whether we do not a fully qualified volume name after all.  I just don't want to close until I've has a chance to test it out with Ubernetes-Lite.  Thanks for the fixes on volume autoprovisioning & sorry for the conflict!

**Comment by justinsb** [comment]
Works great!  Thanks for fixing :-)

```
 "awsElasticBlockStore": {
            "volumeID": "aws://us-east-1b/vol-fd031135",
            "fsType": "ext4"
        },
```
