### ISSUE TITLE
AWS kube-up.sh Ubuntu 1.2.0-alpha.7 missing git

### ISSUE THREAD

**Issue by coleca** [kubernetes/kubernetes#20957]
Just did a fresh kube-up.sh install on AWS using Ubuntu trusty as the dsitribution.  It seems that the git package is not installed by default which causes issues for K8S elements that are pulling from git, such as a gitRepo volume.

Receive this error in the logs:
failed to exec 'git clone https://github.com/<REPO>': : executable file not found in $PATH

Manually installing git corrects the issue.

**Comment by justinsb** [comment]
Anyone know if git is included in the base image on GCE?

**Comment by justinsb** [comment]
@coleca I'd recommend using vivid (the default) if you can over trusty - Docker needs a recent kernel.

I'm still going to fix this, but is there a particular reason for using trusty?

**Comment by coleca** [comment]
No, just had so many issues with Vivid on AWS in the past (with K8S 1.1.x - after reboot of the node Docker not coming back up - looks like its fixed in 1.2) that I figured I'd try something else.  Trusty is also LTS vs Vivid which is out of support as of 2/4/16.

**Comment by justinsb** [comment]
Hopefully we'll fix all those problems with vivid!  Although you raise a great point wrt vivid EOL - let's track that in #21143

My experience with the trusty kernel was not great, but perhaps it is time to revisit that.
