### ISSUE TITLE
Consider using pleg container events to start/stop probers

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#20950]
I've been thinking whether it makes sense to start/stop probers using pleg events.

Pros:
- Faster reaction to container events.
- No need for `CleanupPods` now that the probers will be stopped when the container no longer exists
- The potential to simplify some logic in prober (see https://github.com/yujuhong/kubernetes/commit/918477ccea9ddfc341c05c7bf0ac2dd7dd5ad057 and ignore prober/testing.go. Note that the commit can compile, but I didn't test if it works).

Cons:
- Need to pass internal pod status cache to probers (since the status manager may not have the latest result yet, and we need to know the pod IP for probing)
- Relying on events. 

/cc @timstclair @Random-Liu

**Comment by Random-Liu** [comment]
@yujuhong I have one question. :)
If a container is dead, shouldn't the liveness prober keep monitoring and update pod status?

**Comment by yujuhong** [comment]
> If a container is dead, shouldn't the liveness prober keep monitoring and update pod status?

In this case, a probe worker will be tied to a container ID, not a container name. If the given container with the ID is already dead, there is no point of updating the liveness anyway.
Also, the liveness manager uses container ID as the key, not the container name, so ideally there should be no change to it. :)

**Comment by Random-Liu** [comment]
@yujuhong Ah, I see. I didn't notice that you change the code of probe manager. :)

**Comment by Random-Liu** [comment]
Maybe we could let the prober only relies on specific container spec and "pod metadata" instead of the whole pod spec.
There may be more and more mutable fields in pod spec, it will be hard to keep consistency if we let pod spec spread among different components.

**Comment by yifan-gu** [comment]
Sounds reasonable to me.
