### ISSUE TITLE
Moving resources: essential 1.3 cleanup

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#20951]
We moved job into batch and HPA into autoscaling. We need to recover from that before 1.3.

* Switch all code to use batch/__internal instead of extensions/__internal for Job.
  * This may involve magic to get the conversions to do everything we want.
* As above for HPA.
* Update the storage upgrade test to remove extensions from the KUBE_NEW_API_VERSIONS variable to test the above.

I will add more things as I think of them.

**Comment by lavalamp** [comment]
Tagging @erictune to remember things I've forgotten.

**Comment by piosz** [comment]
\sub

**Comment by wojtek-t** [comment]
As for conversions, we may want to rewrite them to your framework before doing more magic in the current code. Once I'm done with my work for 1.2, I'm going to finish migrating deep-copy generator and then I can work on conversions.

**Comment by erictune** [comment]
In 1.4 we will delete Job and HPA from `extensions/v1beta1`.
We need to warn people with clients to recompile by 1.4, move storage, and translate files.
In 1.3 we need to move the namespace controller, job controller, and any other controllers that touch job, to use the batch/ and autoscaler/ groups.
We will also delete client support for extensions in 1.4.


This plan allows apiserver version to be 1 ahead or behind clients (kubectl, controller, others) at all times.

"Proof" of upgrade safety, and why we need to do across several versions:
 - apiserver 1.1 -> 1.2:  client using extensions/
 - apiserver 1.1 <- 1.2: (rollback)  client using extensions/
 - during 1.2:  not safe to move clients to batch if you want to be able to rollback apiserver at any time.
 - apiserver 1.2 -> 1.3:  client using extensions/ at this time
 - during 1.3: safe to move clients to batch (takes some time).  You can rollback apiserver at any time and jobs will still work. 
 - apiserver 1.2 <- 1.3:  safe to do regardless of whether clients use batch or extensions
 - apiserver 1.3 -> 1.4: clients need to have moved entirely to batch/ prior to this
 - apiserver 1.4 -> 1.3: clients are on batch/ and are fine with downgrade.

**Comment by erictune** [comment]
For 1.2, generation of selectors happens in Create strategy.  We put it there because UID is not available as early as defaulting.  This is awkward.  For 1.3, we should move UID generation early enough to generate selector in the defaulting pass.

**Comment by erictune** [comment]
Currently, we cannot test jobs in examples/examples_test.go due to above comment.

**Comment by lavalamp** [comment]
@erictune Why not just replicate the necessary logic here: https://github.com/kubernetes/kubernetes/blob/master/examples/examples_test.go#L114

**Comment by dims** [comment]
@lavalamp : should this be marked as milestone 1.3?

**Comment by lavalamp** [comment]
I believe all of the items mentioned have been finished.
