### ISSUE TITLE
Cleanup policy should work for paused Deployments

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#20966]
This was discovered during [#18077](https://github.com/kubernetes/kubernetes/pull/18077#issuecomment-178730733), current logic of reaper is infected by additional logic bypassing this problem.

**Comment by krousey** [comment]
@kargakis Any idea which area this is (for issue labels)? Could you update?

**Comment by kargakis** [comment]
@krousey I have no tagging powers but this is related to deployments

@bgrant0607 please tag appropriately

**Comment by bgrant0607** [comment]
cc @janetkuo @mqliang @ironcladlou

**Comment by soltysh** [comment]
@nikhiljindal can you assign this one to yourself since you're addressing it in the linked PR.

**Comment by kargakis** [comment]
> @nikhiljindal can you assign this one to yourself since you're addressing it in the linked PR?

#21857 just syncs the status, doesn't have to do anything related to the cleanup policy. I have addressed it already in #20273.

**Comment by soltysh** [comment]
I see
