### ISSUE TITLE
Remove Set() method from storage.Interface

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#20963]
Set method from storage.Interface:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/interfaces.go#L91

is used only in few tests. We should get rid of it completely.

**Comment by wojtek-t** [comment]
@hongchaodeng - FYI

**Comment by hongchaodeng** [comment]
@wojtek-t 
One question: how didi it refresh ttl keys without Set()?

/cc @xiang90

**Comment by wojtek-t** [comment]
@hongchaodeng - using GuaranteedUpdate - the UpdateFunc returns the new TTL that should be aplied.
Note that I'm talking about Set at the storage.Interface level (not Set from etcd, which is probably necessary).

**Comment by hongchaodeng** [comment]
Got that.

FYI, my search shows that etcdHelper.Set is used only in etcd helper tests.

**Comment by wojtek-t** [comment]
Actually - there is one more place that is more problematic:
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/registrytest/etcd.go#L192

**Comment by wojtek-t** [comment]
Actually, it's not that difficult how I thought it will be.
I already started doing this - will try to send out PR later today or early next week.

**Comment by wojtek-t** [comment]
#23490 is supposed to do that.
There are two more tests that I need to fix:
- pkg/storage/cacher_test.go
- pkg/storage/etcd/etcd_watcher_test.go

Both are non-trivial, but doable.

**Comment by wojtek-t** [comment]
Will try to finish it early next week.

**Comment by hongchaodeng** [comment]
Thanks for the update.
I would remove Set() method from etcd3 changes too.

**Comment by timothysc** [comment]
IMHO we should refactor set to become GaurenteedUpdate, b/c GuarenteedUpdate is weird interface convention.

**Comment by wojtek-t** [comment]
@timothysc I would like to do one step at the time - we should first remove things that are generally unused, and then we can cleanup what is remaining).
