### ISSUE TITLE
GCE load-balancer resources should get descriptions

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#20962]
Once #20731 lands, we have the service name and can stick that into description fields for IP addresses, forwarding rules, target pools, and firewalls.

**Comment by therc** [comment]
I can try doing this, but have no way of testing. See me getting stumped on e2e failures with a similar PR, #20909.

**Comment by therc** [comment]
Does #21319 work for you?

**Comment by therc** [comment]
Also cc @bprashanth for his Ingress/GlobalStaticIP stuff.

**Comment by therc** [comment]
@thockin can this make it into 1.2? I just rebased it.

**Comment by bprashanth** [comment]
@freehan fyi, in case you want to pick this up since Tim most likely won't get to it till next week

**Comment by freehan** [comment]
@bprashanth Tim covered this already. :)

**Comment by freehan** [comment]
Maybe we should also consider adding cluster name into description. That will help distinguish different clusters in the same project.
