### ISSUE TITLE
Provide the namespace in container as ENV var

### ISSUE THREAD

**Issue by mfojtik** [kubernetes/kubernetes#20970]
It would be nice to provide the namespace name in the container, preferably as an environment variable.
Currently it is possible to create that environment variable using downward API, but it is pretty ugly ;-)

The use case for this is for example when I want to do an API call from inside the container to list other
resources in the same namespace.

**Comment by mfojtik** [comment]
@smarterclayton FYI

**Comment by smarterclayton** [comment]
Ultimately we decided we won't auto inject things, so the env car downward API is your best bet.  However, @liggitt and I discussed that the service account secrets for each project should have a "namespace" key equal to their namespace to make it easier for the implicit container client to provide a default namespace.

**Comment by mfojtik** [comment]
@smarterclayton so in theory I would be able to extract the current namespace from `/run/secrets/kubernetes.io`, correct? I think that will be OK.

In my case, I use `oc get -n <ns-here> is` to discover the Jenkins Slave image streams... Currently I have this as a parameter for the template, but I would love to have this set automatically.

**Comment by mfojtik** [comment]
@smarterclayton https://github.com/openshift/origin/pull/7145/files#diff-5d6c0cc58ee615297d5826697fefd9b9R212

this works well, closing this issue. thanks for explanation :)
