### ISSUE TITLE
Implement kubectl autoscale for ReplicaSet

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#20986]
Investigate and implement autoscaler support for ReplicaSet in kubectl.

cc @kargakis @janetkuo @bgrant0607 @mqliang

**Comment by mqliang** [comment]
So we should:
1) make Scale a subresource of ReplicaSet, instead of ReplicationController in API server
2) implement autoscaler support for ReplicaSet in kubectl
3) Address e2e test

Hoping I have not missing anything.

**Comment by bgrant0607** [comment]
@mqliang Yes (well, ReplicaSet in addition to ReplicationController), but the scale subresource is on hold at the moment, until the autoscaling API group is created. There was some discussion on PRs #19802 and #20745

**Comment by ncdc** [comment]
Is this a requirement for 1.2 still? If so, is anyone working on it?

(This seems more like 1.3 to me)

**Comment by bgrant0607** [comment]
Punting to 1.3

**Comment by bgrant0607** [comment]
Done.
