### ISSUE TITLE
cluster/ubuntu/deployAddons.sh refers to extinct addon kube-ui

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#20992]
https://github.com/kubernetes/kubernetes/blob/master/cluster/ubuntu/deployAddons.sh refers to `${KUBE_ROOT}/cluster/addons/kube-ui` but there is no longer a `kube-ui` in the `addons` directory.

@dalanlan

**Comment by dalanlan** [comment]
Care to send a pr to replace it with dashboard, maybe?

**Comment by MikeSpreitzer** [comment]
What's up with the UI?  kube-ui is gone, but dashboard is not ready for production use.  What's a guy to do?

**Comment by dalanlan** [comment]
It's not clear to me why kube-ui is wiped out. @mikedanese for more information:)

**Comment by mikedanese** [comment]
You can very easily run both the Uis right now.

**Comment by MikeSpreitzer** [comment]
@mikedanese: I do not understand.  https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/ no longer contains `kube-ui`

**Comment by mikedanese** [comment]
Kube ui was deprecated and no longer developed. We are not going to ship with it by default anymore. You can still run it if you would like.
