### ISSUE TITLE
Move e2e ENV from e2e.sh into job-configs

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20997]
I was working this morning on reconciling `e2e.sh` with our Jenkins job-configs, and realized I shouldn't really need to do that at all.  We should get rid of the massing `case` statement completely, and rely on job-configs as the authoritative source of truth.

I would like to get this in before v1.2 branches, so it's easier to reconcile the branch.

Blocked by #20996.

**Comment by spxtr** [comment]
Done.
