### ISSUE TITLE
Document how to add elastic search to an existing cluster

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#21002]

**Comment by davidopp** [comment]
@roberthbailey Can you provide more context? IIUC ElasticSearch is started at cluster creation time and should be kept running as a static pod?

**Comment by roberthbailey** [comment]
This was for a GKE user that wanted to use elastic search. We don't offer that as a startup option on GKE, but it should be possible (and not too difficult) to add after the fact. In addition, if you don't choose elastic search logging on GCE at cluster startup time, we shouldn't force you to delete your cluster to add it later. The logging pods have historically been run using manifest files, but we should be able to transition them to a DaemonSet (now that it is in beta).

**Comment by jstordeur** [comment]
Is there any update on this?
Is it possible at the moment to switch from google cloud logging to elastic search after the cluster was created? Also you seem to indicate that it is possible to choose elastic search logging on GCE, I haven't seen that option, could you point me to it?

**Comment by roberthbailey** [comment]
> Is there any update on this?

There isn't any update on this specific issue (as far as I know). However, the cluster lifecycle SIG is working on simplifying cluster bootstrapping, and part of that effort is to simplify addon management (which includes the logging addons). 

> Is it possible at the moment to switch from google cloud logging to elastic search after the cluster was created?

Not on GKE. On GCE, it may be possible if you ssh into each node and tinker with the salt configuration, but there isn't a supported script that does it. 

> Also you seem to indicate that it is possible to choose elastic search logging on GCE, I haven't seen that option, could you point me to it?

`export LOGGING_DESTINATION=elasticsearch; ./cluster/kube-up.sh` (see https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L91).

**Comment by mamoit** [comment]
No updates on this?
I'm not quite feeling like tearing down my cluster...

**Comment by sfrique** [comment]
It would be nice if we could choose logs destination after the cluster creation.

**Comment by davidopp** [comment]
@piosz  @kubernetes/sig-cluster-lifecycle-misc 
(BTW, is there a reason why sig-instrumentation doesn't have a Github team?)

**Comment by piosz** [comment]
There was one but was remove by someone. We haven't created a new teams yet.
@DirectXMan12 @coffeepac, do you want to create them?

**Comment by coffeepac** [comment]
<begin thread hijack>
@piosz I'll get started.  I'll share a checklist in a bit on the mailing list so others can help.
<end>

**Comment by ahmetb** [comment]
Just FYI: We moved the examples to their own repo (https://github.com/kubernetes/examples) for further maintenance. And we don't want to add such big topics to the examples repo anymore.

We encourage the community to create a separate repo (e.g kubernetes-elasticsearch) and/or maintain a Helm chart. This way, the example would stay more up to date and have clearer ownership structure.

@piosz @coffeepac

**Comment by piosz** [comment]
@ahmetb thanks for the update.
+1 for having helm charts for ES.

cc @fgrzadkowski

**Comment by coffeepac** [comment]
is there anything we still want out of this issue?  there a couple of helm charts that exist for running elasticsearch and the entire logging pipeline and the cluster addon is now daemonsets so can be installed at any time.

anyone need this issue anymore?  if not I'll the bot close it.
