### ISSUE TITLE
CrashBackOffLoop despite clean exit?

### ISSUE THREAD

**Issue by dlitwin-autodesk** [kubernetes/kubernetes#21008]
I have a service I would like to update from time to time.
I have it perform a clean exit periodically, relying on the replication controller to start up a fresh service in its place.
Although I am careful to exit with an exit status of zero, the second instance to exit triggers the service into the CrashBackOffLoop status and my restart is delayed.

From what I can see here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1931
the back off code doesn't consider the exit status at all, just the duration between exits when setting the service into what is described as a crash, although no crash is happening.
Should it not also check for containerStatus.ExitCode != 0 ?

**Comment by Random-Liu** [comment]
The `ExitCode` is considered in [`ShouldContainerBeRestarted()`](https://github.com/kubernetes/kubernetes/blob/71bcc25409cc284c874cd31b52371b0d4d81fbf0/pkg/kubelet/container/helpers.go#L48).

Moreover, how did you configure the [`RestartPolicy`](http://kubernetes.io/v1.1/docs/user-guide/replication-controller.html)? I think for your case `RestartPolicyOnFailure` may be what you want.

**Comment by dchen1107** [comment]
@dlitwin-autodesk do you have a reprod case?

**Comment by yujuhong** [comment]
> I have a service I would like to update from time to time.
> I have it perform a clean exit periodically, relying on the replication controller to start up a fresh service in its place.
> Although I am careful to exit with an exit status of zero, the second instance to exit triggers the service into the CrashBackOffLoop status and my restart is delayed.

@dlitwin-autodesk, does the entire pod terminates voluntarily or only one of the container in the pod exits? If you have a replication controller to start up a "new pod", the new pod will not be subject to the backoff at all since we have per-pod backoff quotas.

If you mean that a single container in your pod that exits periodically and backoff gets applied, this is by design. As long as the restart policy of the pod is "Always", kubelet assumes that the containers should be long running. Whether the container crashes or exits voluntarily, the crashBackOff mechanism will be engaged. Note that if kubelet didn't enforce this, a container that always exits immediately can drag down kubelet.

Maybe it'd be more clear what's the best way to achieve what you want if we can understand your use case more.

**Comment by dlitwin-autodesk** [comment]
@Random-Liu: My restart policy is "Always".
I want the replication controller to restart the service, I just don't want a clean exit considered a crash and take the back off hit.
Not sure I see how ShouldContainerBeRestarted() affects the backoff logic, can you explain?

@dchen1107:  I am currently on the 1.1.4 version but from what I can see the code, although changed, does not alter its behavior in regard to this decision.

@yujuhong : Ah, good point on multi-container pods.  It happens there is only one container in this pod though.

The use case is a service that caches some dependency data on startup and over time builds up cached artifacts.
From time to time its dependencies need to be upgraded and artifacts purged.  One solution is to add synchronization, periodically update the deps and clean things out (LRU or other policy) but in a containerized world simply exiting and having a new version come up fresh was appealing for a few reasons:
1.) Services determine they are out of date with periodic checks so exiting/restarting performs a form of rolling update randomized over this period
2.) Although synchronization is not that hard, it is convenient to assume a fixed set of dependencies rather than to have to stop all the tasks, update, invalidate, and restart things again.  Certainly more maintainable in that fewer people need to understand sync issues.
3.) There are a set of resource related profiling and debugging tasks with long running services, and garbage collected languages (Go, in my case) can behave unpredictably in this regard.  I enjoy such challenges as much (perhaps more?) as the next engineer but sometimes there is a priority tradeoff between fixing every last bug and avoiding situations where outlier bugs occur.
4.) A distributed system must expect these services to be transient and in designing around this we can take advantage of this expectation to simplify implementation.  Essentially the proposition is to make a small investment in culling the herd rather than a large investment in geriatric care.

I understand protecting the kubelet from fast restarts, but it still seems an odd choice to consider an exit(0) a failure/crash.
If a service is pulling down a kubelet with fast clean exits then perhaps that case better determined by the container lifetime rather than by the time since previous service shutdown.
In my case the expected lifetime of a service is not short at all really, but since I have more than one pod on the node the kubelet seems to confuse separate services near each other with frequent crashes.

Can we perhaps add a new restart type that doesn't assess the backoff penalty for clean exits and assume those choosing this new policy will be responsible for avoiding fast clean exits taking down their kubelet?

**Comment by yujuhong** [comment]
> In my case the expected lifetime of a service is not short at all really, but since I have more than one pod on the node the kubelet seems to confuse separate services near each other with frequent crashes.

@dlitwin-autodesk, by multiple "services" do you mean kubernetes pods?

If your pods are long running and only occasionally exits, it should not be affected by the backoff mechanism much. I am not sure how backoff would be a problem in this case.

As for "kubelet seems to confuse separate services near each other with frequent crashes.", if you mean kubelet backs off starting a container due to crashes from other unrelated containers, it would be a bug. The backoff mechanism/accounting is per-container and one container crashing should not affect other containers in the same pod, let alone containers in *other* pods. Would you mind posting the output of `kubectl describe pod <pod_name>`?

**Comment by dlitwin-autodesk** [comment]
I think I had a few points of confusion:
The first was on a clean startup there was indeed an unavailable dependency and it was rightfully in a crash loop state for a window of time (this has been removed).  I'm not sure how I missed the logging of this earlier.
The second was that even with everything in place I am seeing a 15 second delay between a container clean exit (even after running stable for more than 300sec) and the next container coming up.  I don't think this is related to crash back off but it looked that way due to confusion #1 above and my perusal of the source. (Ignore my misunderstanding about multiple crashes, I was apparently misreading the source)
So perhaps I just need to understand RC latency and why it takes so long to restart.
One further complication is that while in production we expect long runtimes, in development deps change more frequently so I think it is very easy for me to hit these backoffs.

So I suppose there are two remaining issues that outlive my confused early comments:
1.) Is there a way to have a different policy to allow clean exits not to be considered backoff (for the dev case where service cycling within 5 minutes is expected)?
2.) Is the 15 second delay I am seeing (unrelated to backoff, perhaps) able to be reduced?

Thanks for your patience and clarification

**Comment by yujuhong** [comment]
If you're seeing a constant ~15 second delay, it probably has nothing to do with the backoff (as you said).
The v1.1 kubelet has a sync period of 10s, meaning that it checks the containers every 10s to see if there are any changes, and restart any container if needed. This is tunable using the --sync-frequency flag. However, it's not recommended to use a shorter period if you have more than a few pods on one node, as it causes huge load on docker.

In v1.2 (the coming release), we've made quite some improvements in kubelet's performance. kubelet will now detect container changes at ~1s period (unless there is a sudden surge of load on the node, e.g., batch creation/deletion of pods). That will be much better than the 15 second delay you've been seeing. 

Hope this helps.

**Comment by dlitwin-autodesk** [comment]
That sounds great, thanks again!
