### ISSUE TITLE
Known issues for kubernetes 1.2 release

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#21000]
It is the time to collect all known issues for our coming release now. 

cc/ @thockin @bgrant0607 @davidopp @lavalamp @roberthbailey

**Comment by bgrant0607** [comment]
#16737: kubectl rolling-update can't rollback if the rollout is already stuck on maxUnavailable

**Comment by dchen1107** [comment]
Known issues with docker 1.9.1:
https://github.com/kubernetes/kubernetes/issues/16110#issuecomment-164523276

**Comment by bgrant0607** [comment]
Paused deployments can't be resized and don't clean up old ReplicaSets. Fix is in progress (#20273), but didn't make it into 1.2.

**Comment by bgrant0607** [comment]
The known-issues doc is very, very out of date:
http://kubernetes.github.io/docs/user-guide/known-issues/

**Comment by bgrant0607** [comment]
@dchen1107 requests a separate doc for docker issues

We should also link to known issues from the release description on github

**Comment by bgrant0607** [comment]
1.1 issues don't seem to be documented: #15747

**Comment by bgrant0607** [comment]
I think the most important of these are in the release notes.
