### ISSUE TITLE
Easier service account key rotations: Allow for multiple service account token verification certs

### ISSUE THREAD

**Issue by huggsboson** [kubernetes/kubernetes#21007]
Sorry I don't have a test case to demonstrate this yet, I'm mostly going on visual inspection.  I'll try to come back here with a demonstration case once I get a good experimental environment set up, but from visual code inspection it looks like only one public key is allowed in service-account-key-file that is passed to API server.  If multiple were allowed then to rotate the service-account-private-key-file passed to controller-master we'd just:
1. add the new public key to the pem passed to api servers via service-account-key-file
2. update the service-account-private-key-file passed to the controller-manager
3. update all the service-account tokens
4. remove the old public key from the pem.

Unless you folk can think of a better key rotation method.

**Comment by bgrant0607** [comment]
cc @liggitt

**Comment by liggitt** [comment]
that's correct... we can update that option to take a list of keyfiles... the underlying impl already allows multiple keys for rotation validation

**Comment by erictune** [comment]
@huggsboson if you are up to sending a PR that would be great!

**Comment by huggsboson** [comment]
I've got a fewer higher priority items than this at the moment.  When the time comes to rotate the secrets I'll try to put one together.  If someone gets to this ahead of me, feel free to pick it up.
