### ISSUE TITLE
Docker validation test: restart and upgrade

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#21013]
We ran into the issues with docker restart and upgrade a couple of times already:
- https://github.com/kubernetes/kubernetes/issues/20995#issuecomment-182594941 for docker 1.9.1
- https://github.com/docker/docker/issues/13850

We should automate this kind of tests in our docker validation test suite. 

cc/ @kubernetes/goog-node 

@liangchenye I am assigning this to you since you are in charge of docker validation work. Thanks!

**Comment by liangchenye** [comment]
@dchen1107 Look into it. Thanks.
