### ISSUE TITLE
kubectl help bug: --sort-by lists bad example JSONPATH

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#21018]
The help for --sort-by says `The field specification is expressed as a JSONPath expression (e.g. 'ObjectMeta.Name')` but that should be '{.metadata.name}'

**Comment by bgrant0607** [comment]
@AdoHe This would be a pretty easy fix if you have time.

**Comment by AdoHe** [comment]
@bgrant0607 I am happy to do and will fix this as soon as as I can.

**Comment by AdoHe** [comment]
@bgrant0607 I just send a PR #21238, would you mind reviewing this?
