### ISSUE TITLE
kube-up on GCE creates 3x the number of nodes expected

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#21027]
Spinning up a new GCE cluster, I get 9 nodes in 3 instance groups, but the validate-cluster call is only checking for 4 nodes (presumably one instance group's 3 nodes plus the master):

`Detected 5 ready nodes, found 5 nodes out of expected 4. Found more nodes than expected, your cluster may not behave correctly.`

Once 4+ nodes are found it happily continues and says that the cluster is running. But if you immediately run `kubectl get nodes` there are multiple nodes in the `NotReady` state, which should block validate-cluster from completing successfully.

**Comment by roberthbailey** [comment]
The problem is `for i in $(seq $((${NUM_MIGS} - 1)))` ([here](https://github.com/kubernetes/kubernetes/blob/208e98b58e3a018f3c4a27cf477678e6da840aa4/cluster/gce/util.sh#L650)):


```
$ NUM_MIGS=1
$ for i in $(seq $((${NUM_MIGS} - 1))); do echo $i; done
1
0
```

which will create two migs (suffixes of `-1` and `-0`) followed by the last group (no suffix).

**Comment by roberthbailey** [comment]
It looks like this was added in https://github.com/kubernetes/kubernetes/pull/18567 by @gmarek

**Comment by roberthbailey** [comment]
I believe that the intent is to still create a single MIG with 3 nodes.

**Comment by gmarek** [comment]
It's the problem with OS X (so probably BSD in general) implementation of seq. On ordinary linux:
```
$ seq 0
$ 
```

On OS X:
```
$ seq 0
1
0
```

**Comment by roberthbailey** [comment]
Wow, and here I thought it was just `sed` that was messed up on my mac. :/

**Comment by gmarek** [comment]
At least in sed you can add some flags to make it work correctly (https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/start-kubemark.sh#L211).

Here I think I'll just add an `if 0` outside this loop...

**Comment by roberthbailey** [comment]
The linux man page (http://linux.die.net/man/1/seq) seems consistent with the bsd one (https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/seq.1.html) in that first defaults to 1 and if last is less than first it should count down.

**Comment by gmarek** [comment]
Well, it doesn't;)

**Comment by roberthbailey** [comment]
You could also just write a more normal looking for loop (from http://stackoverflow.com/questions/6191146/variables-in-bash-seq-replacement-1-10):

```
START=1
END=10
for ((i=START; i<=END; i++))
do
   echo "i: $i"
done
```

If I set END to 0 that prints nothing.

**Comment by gmarek** [comment]
Nice - I didn't knew that such syntax is allowed in bash. Thanks.

**Comment by roberthbailey** [comment]
Me neither, I was just searching for an alternative to `seq`.
