### ISSUE TITLE
e2e Flake: clientset should create pods, delete pods, watch pods

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#21045]
```console
• Failure [12.590 seconds]
Generated release_1_2 clientset
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/generated_clientset.go:154
  should create pods, delete pods, watch pods [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/generated_clientset.go:153

  Expected
      <int>: 0
  to equal
      <int>: 1

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/generated_clientset.go:102
```

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by piosz** [comment]
Yet another failure
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/11395/

**Comment by wojtek-t** [comment]
There is already fix in flight

**Comment by piosz** [comment]
Ok. I see

**Comment by mikedanese** [comment]
This was closed 5 days ago but appears to not be fixed. Many PRs have referenced it as a flake since the fix went in.

**Comment by wojtek-t** [comment]
@mikedanese @caesarxuchao - I referenced to it 2 after it was closed, but all of those failures were from runs before this was merged. So it's possible that it's already fixed.

**Comment by mikedanese** [comment]
When was the fix merged? I saw this a couple hours ago: https://github.com/kubernetes/kubernetes/pull/20882#issuecomment-185004106

**Comment by mikedanese** [comment]
Oops, same test but the error is slightly different... Maybe this is a seperate flake

**Comment by wojtek-t** [comment]
Yeah - it seems to be something different.

**Comment by wojtek-t** [comment]
Also - I'm not claiming it's definitely fixed - I just said that we need to double check, because the two that I linked was from before merge.

**Comment by caesarxuchao** [comment]
I'll close this one for now. Please reopen the issue and cc us if the flake occurs again.
