### ISSUE TITLE
Kubernetes can no longer use TLS for etcd

### ISSUE THREAD

**Issue by danderson** [kubernetes/kubernetes#21051]
I hope I'm just missing something, but a grep of source code seems to confirm that I'm not...

Kubernetes 1.1 supported using TLS for the connection to etcd, via the deprecated etcd client. With 1.2alpha, it seems that this has been lost in the migration to the supported etcd client.

To be more specific: there's no way to specify a certificate for client authentication, or to specify a non-systemwide CA certificate to authenticate the Etcd server.

This is a pretty serious regression. Please fix.

**Comment by AdoHe** [comment]
@danderson I will open a PR to fix this as soon as possible.

**Comment by maclof** [comment]
There is already a PR open for this https://github.com/kubernetes/kubernetes/issues/18760

**Comment by lavalamp** [comment]
Yup, let's discuss in #18760
