### ISSUE TITLE
invalid character '%' looking for beginning of object key string

### ISSUE THREAD

**Issue by MaksymBilenko** [kubernetes/kubernetes#21065]
Hello,
I'm getting error wen trying to create heapster RC.
Seems like issue is that my k8s installation unable to handle this logic:
```
{% set heapster_memory = "300Mi" -%}
{% set num_nodes = pillar.get('num_nodes', -1) -%}
{% if num_nodes >= 0 -%}
  {% set heapster_memory = (200 + num_nodes * 12)|string + "Mi" -%}
{% endif -%}
```

I'm running k8s 1.1.2 on CoreOS alpha (949.0.0)

Could you please help me with that issue
Cheers

**Comment by a-robinson** [comment]
Those yaml configs aren't mean to be used directly, only via salt when the cluster is created. If you really want to create heapster yourself, just remove the templating from the top of the file and replace the heapster_memory template expansion in the body of the yaml object with a reasonable value based on how big your cluster is.
