### ISSUE TITLE
HPA should ensure that number of replicas is in specified range

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#21060]
@thockin suggested that HPA should ensure that the current number of pods should be in range [minReplicas, maxReplicas] even in case of lack of signals for scaling decision.

cc @fgrzadkowski @mwielgus

**Comment by davidopp** [comment]
Please add 1.2 milestone label if you think this is needed for 1.2

**Comment by fgrzadkowski** [comment]
+1 We should fix this.

@mwielgus Can you fix this? This shouldn't be too hard.

**Comment by mwielgus** [comment]
Filip, since yesterday you are reviewing the PR that fixes it :) 
See entry just above your comment:
"Handle scenarios when replica count is outside of HPA's replica range #21149"

**Comment by fgrzadkowski** [comment]
Ooops :)
