### ISSUE TITLE
Error out if a kubeconfig's current-context doesn't exist

### ISSUE THREAD

**Issue by danderson** [kubernetes/kubernetes#21062]
In 1.1, if you specify "current-context: i-do-not-exist" in a kubeconfig, and there's no matching context by that name in the contexts, kubelet silently uses what I assume is either an empty or a default configuration.

This can result in hilarity like wondering why your kubelet isn't using the TLS settings you provided, and spending several hours debugging the whole stack only to discover that you typo'd current-context :).

It would be better if kubelet and other users of kubeconfig.yaml errored out on such a misconfiguration, to make the failure obvious and trivial.

**Comment by bgrant0607** [comment]
cc @feihujiang

**Comment by AdoHe** [comment]
I think kubelet silently uses an empty configuration. Guess we should give a waring here.

**Comment by feihujiang** [comment]
@AdoHe Did you start to work on this?

**Comment by AdoHe** [comment]
@bgrant0607 @feihujiang Below is related code:
```
func (config DirectClientConfig) getContextName() string {
	if len(config.overrides.CurrentContext) != 0 {
		return config.overrides.CurrentContext
	}
	if len(config.contextName) != 0 {
		return config.contextName
	}

	return config.config.CurrentContext
}
func (config DirectClientConfig) getContext() clientcmdapi.Context {
	contexts := config.config.Contexts
	contextName := config.getContextName()

	var mergedContext clientcmdapi.Context
	if configContext, exists := contexts[contextName]; exists {
		mergo.Merge(&mergedContext, configContext)
	}
	mergo.Merge(&mergedContext, config.overrides.Context)

	return mergedContext
}
``` 
@feihujiang can you confirm this? Besides if we want to log a waring in kubelet, we may need to get `clientcmdapi.Config` in kubelet.

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-node

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by jlowdermilk** [comment]
@AdoHe I believe kubelet already uses `clientcmdapi.Config`. Adding a check in [getContext()](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/client_config.go#L277) that current context exists if specified sounds like the right approach.

**Comment by smarterclayton** [comment]
Are there any backwards compatibility implications here?  would this break
users who have existing configs (that fallback to default namespace)?

**Comment by AdoHe** [comment]
@jlowdermilk I think kubelet directly use `client.Config` not `clientcmdapi.Config`. Also [getContext()](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/client_config.go#L277) already checks whether the user-specified current context exists, the problem is that if not exist, we just skip. We need to do something if the current context not exist, like log a warning.

**Comment by deads2k** [comment]
Erroring on a specified and bad `current-context` seems reasonable.  If it is not specified and there's only one option, I don't think we should fail.

**Comment by AdoHe** [comment]
@deads2k yeap, the case is that user specify the `current-context` but not exist, in such case we should just fail.

**Comment by asalkeld** [comment]
If no one is working on this I can take it.

**Comment by AdoHe** [comment]
```
Also getContext() already checks whether the user-specified current context exists, the problem is that if not exist, we just skip.
```

@asalkeld I think this is the root cause. Basically we should error on this not exist context. If you have extra bandwidth, please go ahead :)

**Comment by smarterclayton** [comment]
This is related to https://github.com/kubernetes/kubernetes/pull/30808 - the defaulting is what allows us to continue.  When that merges, only kubectl will have the "use localhost:8080" as defaulting.
