### ISSUE TITLE
HPA should log an event if it can't create pods

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#21079]
quota failure, no limit on the pods, etc should all surface as events on the HPA

**Comment by bgrant0607** [comment]
cc @piosz @mwielgus @jszczepkowski @madhusudancs @janetkuo @kargakis @mikedanese @erictune @soltysh 

Actually, all controllers should raise events when they can't create objects as expected (Pods, ReplicaSets, whatever), except when namespace deletion is in progress.

**Comment by piosz** [comment]
So my proposal is to export extra events from HPA when:
- pod has set no limits
- autoscaler controller failed to create HPA object

>quota failure
I think this is already handled by event from scheduler

Anything else?

cc @kubernetes/autoscaling

**Comment by piosz** [comment]
There is a problem with exporting events from HPA #21763, also kubectl describe doesn't print events for hpa (fix in #21756).

**Comment by piosz** [comment]
I verified that HPA exports appropriate events for all cases mentioned here, but due to #21763 the events was not successfully exported.

**Comment by soltysh** [comment]
@bgrant0607 isn't the part of this issue relating to all controllers still valid, maybe a separate issue?

**Comment by bgrant0607** [comment]
@soltysh Yes. Has anyone filed another issue?

**Comment by soltysh** [comment]
@bgrant0607 created #21912, mind tagging it appropriately?

**Comment by bgrant0607** [comment]
Thanks.
