### ISSUE TITLE
LimitRange admission control updates to support sharing

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#21077]
There are a number of downstream use cases where we want to re-use this code, but its current structure makes it difficult.  Making an issue to track them so we can solve.
- Separate the core code into a "Defaulting" and "Reject/Admit" flow
- Expose it's internal cache for reuse

/cc @deads2k @sosiouxme - please add to this list and I will look to address once kube 1.2 is branched.

**Comment by sosiouxme** [comment]
It would be nice to declaratively indicate ordering wants/dependencies between plugins that treat the same subjects. E.g. "if LimitRanger is also in the chain, ensure it runs after this plugin to still enforce the resource settings it's changing." Or "must run after LimitRanger sets defaults". This may be too elaborate to be worth it though.

Re internal caches - these ought to be common resources requested by each plugin at init as needed, so they can be easily shared.

**Comment by spiffxp** [comment]
/sig api-machinery
because admission control
