### ISSUE TITLE
In-container client config doesn't work for many common use cases because no namespace available

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#21073]
This is kind of last minute, but I'd like to consider this for 1.2 because we've had a recent rash of users who want to script this and are effectively blocked.

Today, by default service accounts inject one of their secrets into `/var/run/secrets/kubernetes.io/default`.  That secret enables API access.  We have support in the client config to read that value and provide a default client connection using that service account, which means `kubectl` inside of the container can effectively perform operations as the service account and is easily scriptable.  The one gap today is that `kubectl` does not have access to a default namespace.  Since the point of this injection is to enable easy use of the API by a pod, and most of our APIs that a pod would mutate are namespace scoped, and the service account is scoped to a namespace (although it may have other privileges), the fact that the secret comes with no identifying information as to the namespace means that in order to do "easy" integration with the API, the caller also has to inject the pod namespace via the downward API. 

I would like to add a `namespace` key to each service account token secret, and change in-cluster-config to check for that file and use its value as a default namespace for kubectl and other kubectl like tools.  The secret is a "default injected convention" and the convention is meant to enable easy API integration.  Auto-injecting a downward API volume / env is more complex.  

This enables scenarios like:

* Create a pod that has the command `/bin/sh -c "kubectl rolling-upgrade $SOURCE $DESTINATION && curl -X POST https://myserver/deployment/successful`
* Fetch endpoints for the current service from any pod that has kubectl `kubectl get endpoints db -o jsonpath={.endpoints.subset.addresses}`

**Comment by smarterclayton** [comment]
@bgrant0607 @liggitt and I discussed this this morning and I got him over the hump - would you be willing to allow a targeted change to secret generation to add `namespace` for the service account token to go into 1.2?  It's a fairly small change, but a big usability win.

**Comment by bgrant0607** [comment]
@smarterclayton Makes sense to me, though if we had service linking, it would be more correct to put the info into a ConfigMap.

I assume that existing service-account secrets would not be updated, so InClusterConfig would have to be tolerant of a missing namespace.

cc @lavalamp @erictune

**Comment by liggitt** [comment]
the token controller will update secrets on resyncs as needed to make the ca key current, but yes, InClusterConfig should tolerate it being missing

**Comment by lavalamp** [comment]
I agree this is annoying and I work around it every time I want to write something that runs in a cluster.

I'm willing to accept such a change if it shows up in a PR, I don't think it's too risky.
