### ISSUE TITLE
hack/test-cmd.sh complains about acquiring locks

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#21078]
```
Use "kubectl [command] --help" for more information about a command.
+++ [0211 11:50:56] Starting kubelet in masterless mode
I0211 11:50:56.951313   11509 server.go:267] aquiring lock on "/var/run/lock/kubelet.lock"
unable to aquire file lock on "/var/run/lock/kubelet.lock": open /var/run/lock/kubelet.lock: permission denied
```

@vishh @mikedanese - I remember there was work to do pid locking in kubelet, but this should be stubbed out to not be required when running hack/test-cmd.sh

/cc @deads2k

**Comment by mikedanese** [comment]
We can either default this behavior to off or fix it for the integration tests.

**Comment by derekwaynecarr** [comment]
@mikedanese - I would prefer we default the behavior to off.

**Comment by vishh** [comment]
By default, we do not ever want to run more than one kubelet. So it
probably makes sense to keep the current behavior. We can change the
default directory to a different path for tests. `/tmp/kubelet.lock` is one
option.

**Comment by derekwaynecarr** [comment]
@vishh - I am still confused on the motivation that brought in the lockfile to be honest.  We have gone this far without one, what motivated it's presence now?

**Comment by liggitt** [comment]
The kubelet should probably not be deciding how it should be run, and even if it did, a lock file is the wrong way to go about it. It wouldn't work with containerized kubelet, for example. I vote to revert.

**Comment by mikedanese** [comment]
I still prefer /var/run/lock which is a standard location to put file locks. For integration testing we can use a tempfile in /tmp. I think the people should explicitly express that they desire to run multiple kubelets and it's a good safety feature to have in general.

As for what motivates us now, this allows us to run and upgrade kubelets that are running in a daemonset. This absolutely works with containerized kubelets. Obviously the lock needs to be placed in a mount that's shared between kubelets. See https://github.com/kubernetes/kubernetes/pull/20253#issuecomment-181596016

We aren't voting to revert, we are discussing changing the default behavior. You can opt-in to turn this behavior off. The default should be picked that works best for most users.

**Comment by liggitt** [comment]
The thing running the kubelet should decide whether or not it is ok to run. Whether that's a systemd unit or something checking a lock file, that logic/control belongs outside the kubelet, not inside. I don't think there was sufficient discussion on the addition, so I would like to revert it until agreement is reached.

**Comment by derekwaynecarr** [comment]
When I looked at the PR, it appeared to be discussed as experimental, experimental meant to me off by default ( https://github.com/kubernetes/kubernetes/pull/20253#issuecomment-176464861 )

**Comment by derekwaynecarr** [comment]
It's literally described as Alpha warning in the flag, it should not have a default value that results in a lock until its no longer alpha.

**Comment by vishh** [comment]
I agree with the alpha policy though. Alpha features should be disabled by
default. I'm still curious as to why this is an issue though? This feature
should help avoid running multiple kubelets, in addition to allowing for
self-bootstrapping. Docker daemon has a similar feature.

**Comment by mikedanese** [comment]
@dchen1107 and @vishh reviewed this. The PR was open for 2 weeks. I think it's fine to default this to off for 1.2 while the feature is alpha. I think that this is good behavior to have on by default. I disagree that we should force this to be managed externally of the kubelet.

**Comment by derekwaynecarr** [comment]
@vishh @mikedanese - The immediate concern was that this change affects a lot of scripts that were broken by default when this merged.  I think its fair to revisit after kube 1.2.

**Comment by liggitt** [comment]
> “But the plans were on display…”
> “On display? I eventually had to go down to the cellar to find them.”
> “That’s the display department.”
> “With a flashlight.”
> “Ah, well, the lights had probably gone.”
> “So had the stairs.”
> “But look, you found the notice, didn’t you?”
> “Yes,” said Arthur, “yes I did. It was on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying ‘Beware of the Leopard.”

:-)

I think a switch to in-process managed locking deserves a proposal and wider input than a PR.
