### ISSUE TITLE
GroupVersion types should use Empty, not IsEmpty

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#21076]
`Empty` is more accepted than `IsEmpty`, so https://github.com/kubernetes/kubernetes/blob/master/pkg/api/unversioned/group_version.go should be updated to use `Empty`.  See: https://github.com/kubernetes/kubernetes/pull/20511/files#r52620458

**Comment by ardnaxelarak** [comment]
#dibs

**Comment by ardnaxelarak** [comment]
Fixed by #30821
