### ISSUE TITLE
Trying to add a new volume plugin.

### ISSUE THREAD

**Issue by pault84** [kubernetes/kubernetes#21082]
Hey guys, 
I'm trying to add a new volume plugin for the volume driver we've created.
But seem to be failing.

When i try to use my plugin inside of a PersistentVolume yaml file.
it says it can't find "pwx"  inside of v1.PersistentVolumeSpec

I've followed every step on http://kubernetes.io/v1.1/docs/devel/api_changes.html
i've looked at the changes that were made in the latest azureFile addition.

When i change pwx to azureFile it works like a charm , but obviously throws errors on the fields i've used.

here are all the files touched:

modified:   api/swagger-spec/v1.json
modified:   api/swagger-spec/v1beta1.json
modified:   cmd/kubelet/app/plugins.go
modified:   cmd/libs/go2idl/client-gen/testdata/apis/testgroup/types.generated.go
modified:   cmd/libs/go2idl/client-gen/testdata/apis/testgroup/v1/types.generated.go
modified:   pkg/api/deep_copy_generated.go
modified:   pkg/api/types.generated.go
modified:   pkg/api/types.go
modified:   pkg/api/v1/conversion_generated.go
modified:   pkg/api/v1/deep_copy_generated.go
modified:   pkg/api/v1/types.generated.g
modified:   pkg/api/v1/types.go
modified:   pkg/api/validation/validation.go
modified:   pkg/apis/extensions/v1beta1/conversion_generated.go
modified:   pkg/apis/extensions/v1beta1/deep_copy_generated.go
new file:   pkg/volume/pwx/doc.go
new file:   pkg/volume/pwx/plugin.go
new file:   pkg/volume/pwx/plugin_test.go
new file:   pkg/volume/pwx/pwx_util.go

@saad-ali @thockin @pmorie any idea what i've missed?

**Comment by thockin** [comment]
From slack: 

Without seeing the patch it is hard to say.  Is it a client-side error or server-side.   I assume it is client-side, which suggests it is kubectl that doesn't know about the API fields, but maybe I am wrong.  try --validate=false on the kubectl commandline?

**Comment by pmorie** [comment]
+1, if we can see the patch it will help.

**Comment by pault84** [comment]
i run make everytime i do a code change. in combination with:  hack/update-generated-conversions.sh hack/update-generated-deep-copies.sh and hack/update-codecgen.sh not sure what else to run

Also here is a rtf version of my patch.: [patch](https://www.dropbox.com/s/5ywbpsaxbtvf50j/pwx.rtf?dl=0)

**Comment by pault84** [comment]
here is the fork plus commit.

[fork](https://github.com/pault84/kubernetes)

**Comment by pault84** [comment]
After forking and building again, kubectl seems to accept my yaml
