### ISSUE TITLE
GCE / GKE containerVM image for 1.2 release

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#21086]
Kubelet supports cpu hardcapping by default for `Guaranteed` jobs now. To support that feature, we need to enable `CONFIG_FAIR_GROUP_SCHED` on the kernel.

cc @zmerlynn @dchen1107

**Comment by dchen1107** [comment]
Move this one to 1.2. Here are several things required or might be to containerVM image:

1) replace docker -d with docker daemon to embrace docker 1.10.X 
2) docker 1.9.1 (TBD: still need last signal for restart)
3) kubelet 1.2.X 
4) kernel.hung_task_panic = 1 & kernel.hung_task_timeout_secs = 300 (TBD, and see detail at https://github.com/kubernetes/kubernetes/issues/20096)

**Comment by dchen1107** [comment]
re 2): docker 1.9.1 is going to be the recommended docker daemon based on #20995 and #16110

**Comment by roberthbailey** [comment]
Will this change enforce hard capping on the (really small) cpu limits for the master components?

**Comment by vishh** [comment]
Yes, if limits are set.

**Comment by roberthbailey** [comment]
The limits are currently [250m cpus](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest#L120-L123). I think we use *a bit* more than that for master components on 1k node clusters. 

@wojtek-t

**Comment by vishh** [comment]
Is it OK to avoid setting `limits` on master components and let them burst?

**Comment by dchen1107** [comment]
Yes, those limits I configured for 1.0 release when both request and qos were not introduced yet. We could update the master manifest files. I can pick up this after lunch if no one does it then.

**Comment by roberthbailey** [comment]
Hard limits will also affect cluster add-ons ([gclb](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-loadbalancing/glbc/glbc-controller.yaml), [heapster](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/google/heapster-controller.yaml), [dashboard](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dashboard/dashboard-controller.yaml), [dns](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in), [registry](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/registry/registry-rc.yaml)). Have we done any testing to see what the limits should be on these components or also just set them to burstable?

**Comment by vishh** [comment]
Setting to `Burstable` might be ok for now. In the future though, the
semantics for QoS might change in which case we will have to figure out
appropriate `limits` for these pods.

**Comment by dchen1107** [comment]
@roberthbailey I did plan to make all of addons burstable, but thought that might require some discussion, so decide to send a separate one. :-)

**Comment by zmerlynn** [comment]
#1 and #2 are done in `container-v1-2-v20160218`. I'm going to try to figure out how to get `CONFIG_FAIR_GROUP_SCHED` enabled soon.

**Comment by dchen1107** [comment]
@zmerlynn I double checked the kernel config file of ContainerVM image:

# cat /boot/config-3.16.0-4-amd64 | grep CONFIG_FAIR_GROUP
CONFIG_FAIR_GROUP_SCHED=y

# cat /boot/config-3.16.0-0.bpo.4-amd64 | grep CONFIG_FAIR_GROUP
CONFIG_FAIR_GROUP_SCHED=y

I am pretty sure the flag is enable by default already. Sorry for not checking when the issue was filed initially.

**Comment by vishh** [comment]
Sorry for the confusion. The param that needs to be set is
`CONFIG_CFS_BANDWIDTH` and not `CONFIG_FAIR_GROUP_SCHED`. The latter is
already enabled.

**Comment by roberthbailey** [comment]
@dchen1107 / @zmerlynn / @vishh - what remains to do here for 1.2?

**Comment by vishh** [comment]
Enabling `CONFIG_CFS_BANDWIDTH`.

**Comment by dchen1107** [comment]
I am going to close this one. We are going to create containervm image with CONFIG_CFS_BANDWIDTH for testing.
