### ISSUE TITLE
Support vendor/ directories for vendoring code

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#21098]
Go 1.5 introduced experimental support for vendor directories that are enabled via an environment variable. In Go 1.6, it will be enabled by default, but you can turn it off. In Go 1.7, you will no longer be able to turn it off.

http://tip.golang.org/cmd/go/#hdr-Vendor_Directories

This is obviously becoming the Go community's way of vendoring code. Recent releases of Godep support this by enabling the environment variable. https://github.com/tools/godep#go-15-vendor-experiment They even have instructions on how to convert.

- I think for Go 1.4 and up `GO15VENDOREXPERIMENT=1 godep go build` should work even though Go 1.4 has no native support for vendor directories. (Need to verify)
- For Go 1.5 and up `GO15VENDOREXPERIMENT=1 go build` should work.
- For Go 1.6 and up `go build` should work.

**Comment by luxas** [comment]
Related: #22149

**Comment by spxtr** [comment]
It looks like this was started in #19157 but didn't get far. One major issue is that our licensing stuff depends on godeps, although it shouldn't be too touch to switch it over.

**Comment by spxtr** [comment]
Okay, #22149 is in. Note that `hack/verify-godeps.sh` will break once the experimental flag is disabled, which is tentatively scheduled for go 1.7. There's probably a simple fix, but I'd rather just have switched over by then.

**Comment by eparis** [comment]
@thockin we talked a bit about this....

**Comment by thockin** [comment]
I have a `glide` branch open in my fork (with no PR yet), but that moves us
off godep completely, and uses vendor/ exclusively.  PTAL

**Comment by krousey** [comment]
@thockin migration to glide is probably completely independent of supporting vendor directories. Also, why? Do we gain anything over godep + vendor directory? I was under the impression that with vendor directories, godep all but goes away in the day to day build process. You only need to use it to update the vendored dependencies.

If there are distinct advantages, I would say it deserves its own issue to discuss and track.

**Comment by thockin** [comment]
Godep is constantly breaking.  Godep is thoroughly unhelpful when it comes
to telling you what it is doing and why.  Godep development does not seem
to be making it better.  Glide seems to be a better tool all around, modulo
a couple open bugs, and the developers are actively working on it and
making the UX significantly better.

We could move to vendor before that, I guess, but I don't really want to
retest everything with godep just to retest again with glide.  Lemme see if
I can extract that from my PR.

**Comment by thockin-cc** [comment]
As a point in favor.

I did a godep restore.

I removed Godep/_workspace (wtf is _workspace_aux?)

I ran godep save ./...

It worked silently for 5 minutes

It installed exactly 2 deps into vendor/, with no error message or clue as
to why or what went wrong.

I ran it again with -v

It produced thousands of lines of totally useless output and still failed
with no clue.


And now I am left with literally no clue what to do about it.  Godep is a
dead end.

**Comment by krousey** [comment]
I would suggest updating godep because I don't see these issues. `_workspace_aux` is a terrible terrible hack for licenses. Some licenses for some reason aren't in the `_workspace` tree, so `_workspace_aux` is manually populated. This directory is is used by scripts that verify and update licenses.

**Comment by spxtr** [comment]
On a totally fresh kubernetes clone, I did this:
```
godep restore
rm -rf Godeps
godep save ./...
```
It seemed to install everything. Maybe you have to remove the entire folder and not just the _workspace? I'm not sure.

**Comment by thockin** [comment]
OK, nuking Godeps/ worked (not that this is excusable).

https://github.com/kubernetes/kubernetes/pull/24242

Still doesn't compile.  Not sure why.

**Comment by krousey** [comment]
#24242 fixed this.
