### ISSUE TITLE
hack/test-integration.sh should check etcd version

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#21093]
@kubernetes/goog-csi @lavalamp

**Comment by lavalamp** [comment]
This is mostly to help out humans who have an old etcd version. I think the test infra gets it right by installing it every time.

**Comment by caesarxuchao** [comment]
In hack/test-integration.sh we only check if it's lower than v2.0.0: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal_test.go#L82
