### ISSUE TITLE
hack/test-integration.sh should turn on watch cache

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#21096]
@kubernetes/goog-csi @lavalamp

**Comment by lavalamp** [comment]
Or have one run with it on & one with it off. @wojtek-t can you turn this on? I think it's important to test this.

**Comment by wojtek-t** [comment]
I think that e2e test give us pretty good coverage. But I agree it makes sense to turn it on. Will take a look tomorrow.

**Comment by lavalamp** [comment]
Yeah, I don't think it's urgent, but still important. I asked Chao to file
this so we wouldn't forget.

**Comment by wojtek-t** [comment]
Sure - I agree that it definitely makes sense to do it :)

**Comment by caesarxuchao** [comment]
Sorry I didn't see it's already assigned to @wojtek-t. I assembled a PR it when waiting for some test results :)
