### ISSUE TITLE
Flake: Kubernetes e2e suite.Generated release_1_2 clientset should create pods, delete pods, watch pods

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#21094]
I've seen this a couple times, e.g.

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/28103/#

cc @caesarxuchao

**Comment by mikedanese** [comment]
And here http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/28105/ in #28105

**Comment by madhusudancs** [comment]
Duplicate of #21045?

**Comment by mikedanese** [comment]
Thanks
