### ISSUE TITLE
If POD creation fails due to node being "read-only" force the POD to a different node

### ISSUE THREAD

**Issue by ghost** [kubernetes/kubernetes#21109]
In cases when a POD creation fails (in my case kube-dns restarted but failed) due to node having a "read-only file system" the POD should be assigned to a different node. I believe ROFS errors are not currently caught.

Events on the failing POD:
`Events:
  FirstSeen    LastSeen    Count    From                    SubobjectPath    Reason        Message
  1h        5s        483    {kubelet ip-xxx.ec2.internal}            FailedSync    Error syncing pod, skipping: mkdir /mnt/ephemeral/kubernetes/kubelet/pods/d5277dcb-d0e8-11e5-8d44-0a58bb451775: read-only file system`

@thockin helped to debug the issue.

**Comment by vishh** [comment]
@dchen1107: Should we fix this in v1.2?

**Comment by dchen1107** [comment]
This is not targeted for 1.2 release.

**Comment by bgrant0607** [comment]
This should cause permanent failure of the pod.
