### ISSUE TITLE
Scalability e2es should be in their own project

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#21107]
Right now, our scalability suite runs in `kubernetes-jenkins` project; it should be running in its own project.

**Comment by gmarek** [comment]
cc @wojtek-t

**Comment by wojtek-t** [comment]
Yeah - but we need a project with high enough quota. @ihmccreery - would you be able to get such a project?

**Comment by wojtek-t** [comment]
Default quota is not enough for it.

**Comment by ihmccreery** [comment]
You should be able to request quota yourself—I don't know the details of what quota you need.  If you get pushback, feel free to escalate to @alex-mohr

**Comment by alex-mohr** [comment]
There's a fancy "request quota" button on the compute engine quota's page in the console.  Fill it out, get auto-approved if it's a smallish increase, and get approved a day or two later otherwise.

**Comment by wojtek-t** [comment]
So far created the new project:
https://pantheon.corp.google.com/compute/quotas?project=google.com:k8s-jenkins-scalability

I will request more quota today.

**Comment by wojtek-t** [comment]
I've just sent out request for more quota.

**Comment by wojtek-t** [comment]
We have got approved quota increased (hopefully I didn't miss anything).
We should try to just migrate it to the new project.

**Comment by wojtek-t** [comment]
Unfortunately I missed quota for IP adresses (I though they are not counting ephemeral IP addresses).

I requested quota, but we are reverting back to kubernetes-jenkins project for now.

**Comment by wojtek-t** [comment]
Hopefully we've already have all necessary quota now. Will try to move it tomorrow again.

**Comment by wojtek-t** [comment]
This has already been moved.
