### ISSUE TITLE
Add configurable delay when scaling

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#21113]
When scaling pods, there's no way to do it with a certain delay between instance(s) scheduling/launching.

This is needed, for instance, to scale apps that rely on topology gossiping for discovery - and when said gossiping happens only on connection and not periodically.

**Comment by pires** [comment]
Just letting @thockin know of this since we've discussed it very lightly over Slack.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by pires** [comment]
Statefulsets kinda help deliver this but as a last option, an operator also takes care of it.
