### ISSUE TITLE
v1.1 kubectl can't deploy v1.2 deployments very well.

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#21116]
If you try to create a deployment now with a v1.1 kubectl, everything succeeds but the v1.1 kubectl silently drops the .spec.selector because we changed it to a generalized label selector. I imagine we will have similar issues when we move it to ReplicaSet if they json structure changed at all. I'm not sure there's anything we can do about this.

cc @bgrant0607 @janetkuo @madhusudancs

**Comment by bgrant0607** [comment]
@mikedanese Deployment was alpha in 1.1 and was not enabled by default. Deployment in 1.2 is not backward compatible, in multiple ways.

I'm not sure what your point about ReplicaSet is. It's just another new API.

cc @kargakis @mqliang

**Comment by bgrant0607** [comment]
@mikedanese Did you specify --validate=true?

**Comment by bgrant0607** [comment]
We could document this as a known issue #21000.

**Comment by bgrant0607** [comment]
The root cause of this type of problem is round-trip conversion/defaulting in kubectl: #3955

**Comment by mikedanese** [comment]
@bgrant0607 Isn't that on by default? iiuc validate == true works when the json matches the server version because the schema is passed to kubectl from the apiserver.

**Comment by mikedanese** [comment]
@bgrant0607 My point with replicaset is once we move deployment to replicaset, other fields may be silently dropped.

**Comment by bgrant0607** [comment]
@mikedanese Deployment has been moved to ReplicaSet, which is what enabled/required the selector change. 

We've discussed adding optional strict parsing in both client and server. #5889 

I'm not sure what we can do about existing 1.1 kubectl binaries in the wild, though.

**Comment by bgrant0607** [comment]
This is documented in release notes.
