### ISSUE TITLE
kubectl throws i/o timeout

### ISSUE THREAD

**Issue by sahas-** [kubernetes/kubernetes#21115]
I deleted a cluster using the UI and since then any kubectl command throws this error 

**kubectl get services**
`error: couldn't read version from server: Get https://107.178.212.121/api: dial tcp 107.178.212.121:443: i/o timeout`

**kubectl get nodes**
`error: couldn't read version from server: Get https://107.178.212.121/api: dial tcp 107.178.212.121:443: i/o timeout`

Not sure if its something wrong in my box.. everything was working fine just before deleting the cluster..

**Comment by bgrant0607** [comment]
If you deleted the cluster, then it's gone -- there is nothing to respond to kubectl.

In the future, please ask such questions on stackoverflow.com.
