### ISSUE TITLE
Leaking test resources in non-test binaries

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#21114]
For example, our builds include the `-httptest.serve` flag from the `net/http/httptest` package (pulled in through `github.com/stretchr/testify/assert`).

Files which should probably be excluded from release binaries (but are currently included):
```
pkg/volume/mock_volume.go
pkg/volume/testing.go
pkg/kubelet/network/testing.go
pkg/kubelet/container/runtime_mock.go
pkg/kubelet/prober/testing.go
pkg/kubelet/cadvisor/cadvisor_mock.go
pkg/kubelet/server/stats/mock_stats_provider.go
```

**Comment by timstclair** [comment]
I propose introducing a `test` build tag to be included whenever running tests. See https://github.com/google/cadvisor/pull/1110 for an example.

**Comment by mikedanese** [comment]
Fix it and add it to the symbol check precommit.
```
➜  kubernetes git:(master) nm _output/local/bin/linux/amd64/hyperkube| grep httptest                                                                                                                                               
00000000019e31b0 t net/http/httptest.init                                                                                                                                                                                          
00000000039895f7 b net/http/httptest.initdone.                                                                                                                                                                                     
00000000039787c8 b net/http/httptest.serve
```
https://github.com/kubernetes/kubernetes/blob/master/hack/after-build/verify-symbols.sh

**Comment by ncdc** [comment]
It's not just code from Kubernetes that leaks httptest flags. I tracked it additionally to e.g. https://github.com/mesos/mesos-go/blob/068d5470506e3780189fe607af40892814197c5e/detector/zoo/mocked_conn.go which we end up importing as well. Anything that imports stretchr/testify/assert and/or stretchr/testify/mock will have this problem.

**Comment by mikedanese** [comment]
cc @thockin @lavalamp @timothysc

**Comment by timstclair** [comment]
FYI, here's the dependency graph from `k8s.io/kubernetes/cmd/hyperkube` to the problematic `net/http/httptest` library:
![hyperkube_httptest](https://cloud.githubusercontent.com/assets/3272040/13025303/f0b45822-d1b8-11e5-8a32-412c10e5d00c.png)

The cadvisor & k8s paths should be removed soon. I'll follow up with mesos and coreos.

**Comment by thockin** [comment]
If we can have such a build flag, I am 100% in favor.   I really relied on
that capability in our internal build tools.

**Comment by timothysc** [comment]
We can simply append to the symbol checks as we had done b4.

**Comment by lavalamp** [comment]
UGH AGAIN?!????

**Comment by lavalamp** [comment]
We should not fix this with bulid tags IMO. We should fix it by never mixing test and production code.

**Comment by lavalamp** [comment]
And we should have a test that fails when any of our binaries respond to the testing flags. We can add it to test-cmd.sh...

**Comment by lavalamp** [comment]
Oh, I see. It's just the "httptest" package, not the "testing" package. That's a little better. @mikedanese has the right solution: https://github.com/kubernetes/kubernetes/issues/21114#issuecomment-183141133

**Comment by ncdc** [comment]
We have code in Kube that defines a mock struct in 1 package and uses it in another. That's 1 reason httptest leaks. Similar things are done in packages in our Godeps (mock structs). See https://github.com/kubernetes/kubernetes/issues/21114#issuecomment-183148939 for 1 example.

**Comment by lavalamp** [comment]
Right, that's a big anti-pattern. We should stop doing that immediately.
(Yes, I've been guilty of it in the past...)

**Comment by timstclair** [comment]
@lavalamp can you clarify what the prefered pattern is in that case? Possible solutions I see are

1. don't reuse mocks across code - leads to code duplication :(
2. move all shared mocks to a testing package - leads to circular dependency issues
    - the go standard library seems to get around this by using *_test packages for all tests, and adding an [export_test](https://golang.org/src/net/http/export_test.go) when unexported values are used in tests (which may encourage better testing practices, but would be a big mess with our current tests)

**Comment by thockin** [comment]
Don't export mocks from the shared pkg, define JUST the interfaces you need
in the consumer of the shared pkg and mock it there.

It's a little clunky because go doesn't really have (at least as far as I
have seen_ the facilities for mock scripts the same way that we're used to
in C++, but I have not tried very hard.

Concretely, in C++ it is typical to have a lib expose a base-class, a
concrete class, and a mock class.  In Go, libs should expose a concrete
type.  Consumers of the lib should ideally consume an interface that just
so happens to include methods fulfilled by the lib's concrete type.

This is not always possible (or at least not convenient) and it is not
always followed in Kubernetes.

That said, I am OK with a build tag, but it would be nicer to fail the
compile if test code got linked to real code.

**Comment by lavalamp** [comment]
I agree w/ @thockin

**Comment by timstclair** [comment]
If I followed correctly, you're suggesting duplicating the mock code in packages that need to mock it? That's going to be really annoying whenever a new method is added to the interface :(

BTW, I fully agree with adding more symbols to the symbol check presubmit, but we need to fix the problem before we can do that.

**Comment by lavalamp** [comment]
No-- the mock/fake implementation is in some 3rd package that all consumers
can import.

**Comment by timstclair** [comment]
Ok, but I think you'll still run into cicrular dependency issues without some significant refactoring. I aggree that limiting test resources to test-only packages is ideal, but it can require some careful planning. For example:

```go
package example

type Foo struct { ... }

type Bar interface {
  SetFoo(foo Foo)
}
```

Now you want to add MockFoo in the testing package, but it needs to import `example` for the `Foo` type, meaning that MockFoo can't be used in package example due to circular dependencies. This could be avoided by ensuring that all type declarations come in their own packages (and testable functionality is separated), but that's the significant refactoring I was refering to. Is this what you're recommending, or am I missing something?

**Comment by lavalamp** [comment]
That's the condition for which the example test code can be put in package
`example_test`. Then it can import both example and the example mock.
