### ISSUE TITLE
Investigate how many time ReplicationManager/ReplicaSetController must wait before they start to work

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#21127]
If ControllerManager restart, ReplicationManager/ReplicaSetController/DeploymentController could not start to work until the PodStore/RCStore has been synced, otherwise, they will make incorrect decision when sync ReplicationController/ReplicaSet/Deployment. 

Client of ControllerManager first list all Pods and put them into a `DeltaFIFO`, a Process route then pop the Pod one by one from the `DeltaFIFO` and put into `PodStore`, and call `ResourceEventHandlerFuncs`. For ReplicationManager/ReplicaSetController, `ResourceEventHandlerFuncs` need list all the RCs/RSs in RCStore/RSStore to find the RC/RS which control the Pod, and put it into workqueue. ReplicationManager/ReplicaSetController can not start work until the first batch of Pods inserted by the first list has been synced to PodStore.

When cluster size is large, ReplicationManager/ReplicaSetController may must wait a long time, since `ResourceEventHandlerFuncs` of ReplicationManager/ReplicaSetController is time-consuming(list all the RCs/RSs in RCStore/RSStore to find the corresponding RC/RS which control the Pod).

We need investigate how many time ReplicationManager/ReplicaSetController must wait before they start to work. If it take a long time to wait PodStore synced, we should optimize `ResourceEventHandlerFuncs`(`getPodController()`/`getPodReplicaSet()`) of ReplicationManager/ReplicaSetController. Speed up `getPodController()`/`getPodReplicaSet()` is also very helpful when relist occurs from the perspective of user experience(otherwise, a new created RC/RS may wait a long time when relist occurs).

**Comment by mqliang** [comment]
We could add namespace index https://github.com/kubernetes/kubernetes/pull/17277 and look-up cache https://github.com/kubernetes/kubernetes/pull/19043 to speed up `getPodController()`/`getPodReplicaSet()`. 

But if it does not take a long time to wait PodStore synced, those optimization skills are meaningless. So we should investigate how many time it takes first. Could anyone kindly help statistic the hasSynced() waiting time in real production environment? I just has a PC, and could only write benchmark, it may not
very helpful.  

@bgrant0607 @janetkuo @bprashanth @smarterclayton @kargakis

**Comment by wojtek-t** [comment]
Just based on my experience, it shouldn't be more than single-digit seconds for 1000-node clusters.

**Comment by mqliang** [comment]
@wojtek-t There is a bug in `Informer`, we should investigate waiting time with this PR https://github.com/kubernetes/kubernetes/pull/20269

**Comment by wojtek-t** [comment]
@mqliang what bug in Informer? What problems do you observe?

**Comment by mqliang** [comment]
@wojtek-t See https://github.com/kubernetes/kubernetes/issues/20259, I have fixed it in https://github.com/kubernetes/kubernetes/pull/20269

**Comment by mqliang** [comment]
@wojtek-t So, with the bug of informer, ControllerManager will start to work early(before `PodStore` has been synced). ControllerManager may will wait a longer time with the bug fixed. We should investigate how many time ControllerManager must wait. 

If it the wait time is longer than 10 minutes in 1000-node clusters(about 1000 namespace, each has 10 rcs with 10 replica counts, so ~100000 pods in total), it's worth optimizinng `ResourceEventHandlerFuncs`(`getPodController()`/`getPodReplicaSet()`) of ReplicationManager/ReplicaSetController.

If you could help statistic the `hasSynced()` waiting time in real production environment, it will be mush helpful. I just has a PC, and could only write benchmark.

**Comment by wojtek-t** [comment]
So it's not a bug in Informer - it's just incorrect usage of it.

As I wrote - it definitely shouldn't take 10 minutes - it should take seconds. And note that we are officially not supporting more than 30.000 pods in a cluster.

**Comment by mqliang** [comment]
IIRC, we want to support 1000 nodes, 100+ pods/node, so at most 100.000 pods in total, right?

**Comment by wojtek-t** [comment]
No - we support 1000 nodes, but not all of the conditions for large clusters yet. See:
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/cluster-large.md#support
for more details.

**Comment by timothysc** [comment]
@mqliang version?  Is this master?

**Comment by mqliang** [comment]
> version? Is this master?
No matter, all version with this patch https://github.com/kubernetes/kubernetes/pull/20269 is ok. I write a benchmark about this. Cache sync time for 30.000 pods take seconds, but for 100, 000 pods, it take minutes, for 300, 000, result was much worse(~10 minutes).  So, this was not a big problem at current stage, but if we want to support a larger cluster, optimization was worth doing.

**Comment by timothysc** [comment]
I see, it looks like your patch was merged.  

Do you want to close this issue then...

**Comment by mqliang** [comment]
This issue was not a support issue for my patch. But pointing out a potential problem for a larger cluster. No sure whether k8s want support a larger cluster though.

**Comment by wojtek-t** [comment]
Yes - we are planning to support larger cluster (we will definitely support 5000-nodes at some point - it's not yet defined when).
