### ISSUE TITLE
Consider maintaining gcr.io/google_containers/* images on docker hub

### ISSUE THREAD

**Issue by 0x777** [kubernetes/kubernetes#21126]
We've been working to add an offline 'kubernetes' setup for development in [pangaea](https://github.com/hasura/pangaea).

To achieve this, we use a [pull through cache](https://github.com/docker/distribution/blob/master/docs/mirror.md) of the docker hub registry. Unfortunately, this only works with the docker hub registry (a limitation of docker). Since all the official kubernetes images are on gcr.io, we have to clone the images under our organization on dockerhub for the offline setup to work. However, `gcr.io/google_containers/pause` seems to be hardcoded into one the kubernetes binaries. So, our offline setup is completely offline except for this component. 

I understand that hosting the official kubernetes images additionally on docker hub is a maintenance overhead, but sometimes it helps with the unforeseen use cases (like our offline kubernetes setup) and limitations (registry mirroring only works with docker hub).

**Comment by jdakesworth** [comment]
This gets into the realm of having multiple "sources of truth" which is a pretty big "no no" in the realm of distributed systems.  Have you filed an issue about this upstream with @docker or tried any of the alternative registries?

**Comment by mikedanese** [comment]
cc @david-mcmahon

**Comment by dims** [comment]
@mikedanese @0x777 - The "--pod-infra-container-image" option should help here right?

https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=pod-infra-container-image

This was introduced in March:

https://github.com/kubernetes/kubernetes/pull/23059/commits/c6172e58cf52888d53bb0d3d87c17a3d0760d960

**Comment by mikedanese** [comment]
Yes you are correct, that should no longer be a problem.
