### ISSUE TITLE
delete option doesn't delete docker containers on minions

### ISSUE THREAD

**Issue by bitchecker** [kubernetes/kubernetes#21136]
when i create containers, i can stop with delete options it but on minions if i run:

```bash
docker ps -a
```

i still see all stopped containers and this create space problem on disks.

there's a way to remove stopped containers on minions when i delete pods?

**Comment by sjenning** [comment]
the kubelet should clean these up eventually

http://kubernetes.io/v1.1/docs/admin/garbage-collection.html

are they not being cleaned up within the garbage collection window?

**Comment by bitchecker** [comment]
how can i check value for those variables?
in which config file can i modify them?

**Comment by sjenning** [comment]
it is part of the kubelet config on the node

https://github.com/kubernetes/kubernetes/blob/master/docs/admin/kubelet.md

**Comment by bitchecker** [comment]
on every single node?

**Comment by mikedanese** [comment]
Yes.

**Comment by mikedanese** [comment]
This is by design.
