### ISSUE TITLE
Plugin developer guidelines -- plugin code guidelines / scafolding ? 

### ISSUE THREAD

**Issue by FlorianOtel** [kubernetes/kubernetes#21133]
Hello all, 

First, apologies in advance if this is not as crisp and to the point question as I'd like. The reason for this "fuzziness" is that I am in the confusing stage of starting / making-sense. So, please bear with me :) 

My question is: I'm looking for guidance in writing a K8S plugin (particularly, a networking plugin). To start with a simple "plugin" that "watches" Namespaces and Services would do, with "proper" (networking) plugin logic to be added later. 

What I am looking for is: 
- High-level guideline / walk-through the "proper" way to do this -- use of dedicated service accounts, API for config data, use of kubectl API (vs master API) etc.

This was just a quick list of things to consider that come to mind -- no idea what else is missing that I should consider. Please advise.  
- "Pedagogical" scaffolding / bolierplate code that I can take a look at as an example on how a "canonical" plugin should look like 

I've looked around but the only bits I found was [this README](http://kubernetes.io/v1.1/docs/devel/README.html). The [Developer FAQ](https://github.com/kubernetes/kubernetes/wiki/Developer-FAQ) on GitHub is a "TODO" from Sept. 2014 :) 

Kindest thanks in advance for the help and guidance,

/Florian

**Comment by mikedanese** [comment]
cc @lavalamp @thockin

**Comment by AdoHe** [comment]
@FlorianOtel I am happy to offer some help if you are trying to write a network plugin.

**Comment by lavalamp** [comment]
> that "watches" Namespaces and Services would do

I'd recommend looking at the endpoints controller. It watches pods and services and writes endpoints, but it should be easy enough to adapt. 

As for getting a client while running in a cluster, take a look here, this should work both in and out of a cluster:

https://github.com/kubernetes/kubernetes/blob/95b265390e530eb137beac4288ba28d63c1142da/pkg/client/unversioned/clientcmd/doc.go#L18
