### ISSUE TITLE
Depending on kubernetes client packages injects command-line flags

### ISSUE THREAD

**Issue by paulbellamy** [kubernetes/kubernetes#21148]
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/logs.go#L29 modifies the pflag global variable.

Any binary which uses any kubernetes package and pflags, accidentally gets a `log-flush-frequency` flag added.

**Comment by mikedanese** [comment]
We should move it into a subdir of util and only depend on it from inside cmd/

**Comment by mqliang** [comment]
see https://github.com/kubernetes/kubernetes/pull/20713

**Comment by resouer** [comment]
@mikedanese will fix that in 20713

**Comment by spiffxp** [comment]
/sig cli
looks like it's still present in https://github.com/kubernetes/kubernetes/commit/6a4d5cd7cc58e28c20ca133dab7b0e9e56192fe3
