### ISSUE TITLE
Clean up PUT semantics

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#2114]
PUTs are not doing what I expect them to do.
## Bad Case 1

`PUT /api/v1beta1/pods/a`
Body:

```
        {
          "kind": "Pod",
          "apiVersion": "v1beta1",
          "id": "a",
          "desiredState": {
            "manifest": {
              "version": "v1beta1",
              "id": "a",
              "containers": [{ "name": "foo", "image": "bar/foo", }]
            }
          },
        }
```

I expected 200 since POST of the same body to "/api/v1beta1/pods".
Or, if that is the wrong way to do a PUT, then I would expect a 400, but not a 500.  500 is for server errors.

Here is the response body:

```
{"kind":"Status","creationTimestamp":null,"selfLink":"/api/v1beta1/pods/a","apiVersion":"v1beta1","status":"Failure","message":"100: Key not found (/registry/pods) [9]","code":500}
```
## Bad Case 2

Previous cases are where no object existed.
Next case is an update (created object named `a` with a POST already)

`PUT /api/v1beta1/pods/a`
Same body as above.

I was expecting 200, but I got 500.  I'd take a 400 or 404 over a 500, though.

Response body:

```
{"kind":"Status","creationTimestamp":null,"selfLink":"/api/v1beta1/pods/a","apiVersion":"v1beta1","status":"Failure","message":"105: Key already exists (/registry/pods/default/a) [10]","code":500}
```

**Comment by bgrant0607** [comment]
cc @ArtfulCoder

**Comment by roberthbailey** [comment]
Is this necessary for v1.0?

**Comment by bgrant0607** [comment]
No, after 1.0 is fine.

**Comment by bgrant0607** [comment]
Some updates:

1. I believe PUT to a collection returns 404 now, as mentioned somewhere above. We should add the case to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/integration/auth_test.go, however.
2. We do support creation on PUT. However, we should ensure it works for all objects (e.g., services), and that we perform the proper initialization, validation, and defaulting in this scenario, ideally by sharing code with create.
3. We now support PATCH.
4. We've added retries in various places and also update --force, which deletes and re-creates. The more general problem of false conflicts is #8625. True conflicts need to be addressed by re-patch and re-try, with client-side preconditions for continuation, as we do for kubectl scale.
5. We need to finish adding /status subresources to the remaining resources with status fields.
6. We should file a separate issue for returning the resource, or at least the resourceVersion, with 409.

This issue can be closed after we do (1), (2), and (6).

**Comment by nikhiljindal** [comment]
FWIW, There was a TODO for point 6 which I recently removed https://github.com/GoogleCloudPlatform/kubernetes/pull/10074#discussion_r32876561 :)

**Comment by smarterclayton** [comment]
We agreed returning just version is bad.  Returning the updated resource is a performance win and easier for clients.

**Comment by bgrant0607** [comment]
AllowCreateOnUpdate is currently false for most resources (except services, endpoints, events, limitranges). I think we should enable it for most resources (namespaces TBD) and use the uid as a precondition, if set, in addition to resourceVersion.
