### ISSUE TITLE
AWS: Change default OS to Wily

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21143]
Ubuntu Vivid in now EOL, because it is not an LTS.   We should probably add support for Wily and also check the current state of Trusty.  (And maybe Jessie too!)  Hopefully 16.04 (which will be an LTS) will be a good one that we can stick with for a long time.

Background: Trusty had problems because of having an older kernel with Docker & with btrfs, as I recall.  It might be we can update to a backported kernel.

**Comment by justinsb** [comment]
Although maybe Debian would be more appropriate, given that Wily support ends in a few months as well...  Unfortunate timing!

**Comment by davidopp** [comment]
@justinsb IIUC this issue is now moot since you decided to go to Jessie. If so, please close it. Thanks!

**Comment by justinsb** [comment]
I think we're going to make Jessie the default, yes (though we will support Wily), so closing
