### ISSUE TITLE
kube-up: should we put the master pd in /etc/fstab ?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21155]
We currently remount the master PD every boot, as part of the GCE instance-boot script.  I'm wondering if this is safe: if we have services that start concurrently, should we put the master-pd into /etc/fstab instead?

I think we'll have to do this on AWS, in any case.

**Comment by davidopp** [comment]
@roberthbailey @alex-mohr any thoughts on whether we should also do this for GCE?

**Comment by alex-mohr** [comment]
@lavalamp too for @kubernetes/goog-csi.

I don't pretend to understand the startup dance of the various master components like etcd,  kube*, etc., though it does seem reasonable to add it to /fstab to me.

I'm also interested in getting us to something other than containervm like trusty and friends and getting rid of as much of the instance-boot dance as possible.

**Comment by roberthbailey** [comment]
@zmerlynn helped build the master pd dance and may have some input as well.

**Comment by zmerlynn** [comment]
Actually @a-robinson did the initial work there.

The main problem is that GCE PDs (I don't know if this is different in AWS?) are unformatted, so at least on cluster creation, we have to come up, format and mount them. I don't think we can easily move it inside `/etc/fstab` until after first boot.

**Comment by a-robinson** [comment]
If I understand correctly, new EBS volumes also start unformatted, and it looks as though something like #21165 would still let us automatically format the disk on initial startup because the fstab entry wouldn't exist on the first boot.

**Comment by a-robinson** [comment]
Although if there is some sort of race among services starting up on boot, we'll still hit that problem on the initial boot, and on the initial boot of each recreated master VM if we tear it down and bring it back up with the same disk/IP for upgrades.

**Comment by davidopp** [comment]
ping - someone who understands this issue (not me) please confirm doing this for GCE is a 1.2 blocker, or else move it to next-candidate or remove milestone tag completely and demote to P2.

**Comment by a-robinson** [comment]
I wouldn't consider it a 1.2 blocker to do this for GCE - @zmerlynn?

**Comment by zmerlynn** [comment]
I don't either. I'd actually rather not touch this path right now; we've lived with it this way for a while.

**Comment by justinsb** [comment]
OK well we can see how it goes on AWS :-)
