### ISSUE TITLE
AWS: Make sure docker/kubelet/kube-proxy auto-restart in systemd

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21162]
Splitting out a component on #18975, we need to be sure that if any of our components are killed by the OOM killer, that they are restarted.  I think that actually means configuring systemd to restart docker, kubelet & kube-proxy; other components will be started as long as kubelet is running.

**Comment by justinsb** [comment]
docker & kubelet will auto-restart already; kube-proxy is managed by kubelet.  All is well :-)

**Comment by gopinatht** [comment]
Guys, I see a problem with at least the kubelet when killed by the OOM killer. When the minion runs out of memory, it looks like the kubelet gets killed by the kernel but does not get restarted even when I specify `restart=always` in the systemd unit description:

```
 - name: kube-kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=setup-network-environment.service fetch-kubeconfigs.service
        After=setup-network-environment.service fetch-kubeconfigs.service
        
        [Service]
        EnvironmentFile=/etc/network-environment
        ExecStartPre=/usr/bin/curl -L -o /opt/bin/kubelet -z /opt/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/v1.2.0/bin/linux/amd64/kubelet
        ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
        # wait for kubernetes master to be up and ready
        ExecStartPre=/opt/bin/wupiao xx.xx.xx.xx 8080
        ExecStart=/opt/bin/kubelet \
        --address=0.0.0.0 \
        --port=10250 \
        --hostname-override=${HOSTNAME} \
        --api-servers=https://xx.xx.xx.xx \
        --kubeconfig=/var/lib/kubelet/kubeconfig \
        --allow-privileged=true \
        --logtostderr=true \
        --cadvisor-port=4194 \
        --healthz-bind-address=0.0.0.0 \
        --healthz-port=10248 \
        --cloud-provider=aws \
        --maximum-dead-containers=10 \
        --image-gc-low-threshold=50 \
        --minimum-container-ttl-duration=10s \
        --cluster-dns=10.100.0.10 \
        --cluster-domain=cluster.alpha
        #--api-servers=xx.xx.xx.xx:8080 \
        Restart=always
        RestartSec=10
```

Is this a known issue now? Is there any workaround for this? I am using k8s 1.2.0 with the latest version of CoreOS Alpha (991.0.0) on AWS EC2.

**Comment by justinsb** [comment]
@gopinatht can you please open a new issue, including the output that shows kubelet not restarting (ideally why it is not restarting, but just whatever output you have)
