### ISSUE TITLE
HPA 'describe' metrics are different scales?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#21166]
Trying out HPA.  I ran 10 pods with 100m CPU each, and each one burns 100% CPU.  I set an HPA with a target utilization of 25%.

When I ran `describe` on it, I saw the 25% goal, but the "current" was 996% (makes sense, 10 pods at ~100% usage).  The problem is that these numbers  are not really comparable.  I assume 25% is a threshold for `sum(cpu_utilization)/num_pods` (or some similar function with smoothing or history), so I expect "current" to also be the same function.  Instead it appears to just be the sum.

What am I missing?

@vishh

**Comment by davidopp** [comment]
ping @vishh @mwielgus @piosz

**Comment by piosz** [comment]
I'll fix it.

**Comment by piosz** [comment]
Pod autoscaler set status in a wrong way. Increasing priority.

**Comment by piosz** [comment]
I investigated this issue and it's seems that everything works as intended. Added unit tests which verifies it.

@mwielgus could you also please verify that everything here is ok?

**Comment by piosz** [comment]
@thockin is it possible that your pods were using ~1000% od cpu (which is 1core in this case)?

**Comment by thockin** [comment]
They were all run with `--limits=cpu=100m` - I can try to repro later today

**Comment by thockin-cc** [comment]
I am, of course, dumb.  I totally forgot that CPU cgroup is
work-conserving, so even with limit=100m, it will still use more CPU.

**Comment by piosz** [comment]
Thanks @thockin for verifying!
