### ISSUE TITLE
Jobs e2e test failures on PR builder

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#21169]
3 tests failed on one of the builds of PR #21012.

```
Summarizing 3 Failures:

[Fail] Job [It] should run a job to completion when tasks sometimes fail and are locally restarted 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/job.go:76

[Fail] Job [It] should run a job to completion when tasks sometimes fail and are not locally restarted 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/job.go:94

[Fail] Job [It] should stop a job 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/job.go:171

Ran 123 of 226 Specs in 1020.632 seconds
FAIL! -- 120 Passed | 3 Failed | 0 Pending | 103 Skipped 
```

[Build Log](http://pr-test.k8s.io/21012/kubernetes-pull-build-test-e2e-gce/28235/build-log.txt)

**Comment by davidopp** [comment]
cc/ @erictune

**Comment by davidopp** [comment]
@erictune  do you think you could take a look at this one?

**Comment by erictune** [comment]
For the first one, it seems one of the pods never fully started during the 2 minutes before the test timed out.
```
Feb 12 07:23:04.218: INFO: fail-once-local-r6hqn                                  e2e-gce-builder-2-0-minion-xobd  Pending           [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-12 07:08:11 -0800 PST ContainersNotReady containers with unready status: [c]}]
```

We know it got scheduled and started to pull its image:
```
Feb 12 07:23:04.191: INFO: event for fail-once-local-r6hqn: {default-scheduler } Scheduled: Successfully assigned fail-once-local-r6hqn to e2e-gce-builder-2-0-minion-xobd
Feb 12 07:23:04.191: INFO: event for fail-once-local-r6hqn: {kubelet e2e-gce-builder-2-0-minion-xobd} Pulling: pulling image "gcr.io/google_containers/busybox:1.24"
```
but there is no event about creating or starting this container ... all the other 3 have such messages.

**Comment by erictune** [comment]
```
Feb 12 07:23:06.812: INFO: 
Logging kubelet events for node e2e-gce-builder-2-0-minion-xobd
Feb 12 07:23:07.042: INFO: 
Logging pods the kubelet thinks is on node e2e-gce-builder-2-0-minion-xobd
Feb 12 07:23:07.221: INFO: fail-once-local-r6hqn started at <nil> (0 container statuses recorded)
Feb 12 07:23:07.221: INFO: rand-non-local-vln05 started at <nil> (0 container statuses recorded)
Feb 12 07:23:07.221: INFO: foo-zdcga started at <nil> (0 container statuses recorded)
Feb 12 07:23:07.221: INFO: l7-lb-controller-usdzc started at <nil> (0 container statuses recorded)
Feb 12 07:23:07.221: INFO: elasticsearch-logging-v1-jgmxe started at <nil> (0 container statuses recorded)
Feb 12 07:23:07.221: INFO: fluentd-elasticsearch-e2e-gce-builder-2-0-minion-xobd started at <nil> (0 container statuses recorded)
Feb 12 07:23:07.221: INFO: kubernetes-dashboard-v0.1.0-vd0xn started at <nil> (0 container statuses recorded)
Feb 12 07:23:07.221: INFO: kube-proxy-e2e-gce-builder-2-0-minion-xobd started at <nil> (0 container statuses recorded)
Feb 12 07:23:07.516: INFO: ERROR kubelet_docker_errors{operation_type="info"} => 1 @[0]
Feb 12 07:23:07.516: INFO: ERROR kubelet_docker_errors{operation_type="inspect_image"} => 16 @[0]
Feb 12 07:23:07.516: INFO: ERROR kubelet_docker_errors{operation_type="list_containers"} => 32 @[0]
Feb 12 07:23:07.516: INFO: ERROR kubelet_docker_errors{operation_type="list_images"} => 5 @[0]
Feb 12 07:23:07.516: INFO: ERROR kubelet_docker_errors{operation_type="pull_image"} => 1 @[0]
Feb 12 07:23:07.516: INFO: ERROR kubelet_docker_errors{operation_type="stop_container"} => 1 @[0]
Feb 12 07:23:07.516: INFO: ERROR kubelet_docker_errors{operation_type="version"} => 22 @[0]
```

**Comment by erictune** [comment]
@timstclair seems like you added the "ERROR kubelet_docker_errors" lines to e2e output.  How do I make sense of these lines?  It seems like they are cumulative counts for the whole test, so you cannot tell which errors are from this test case and which are from a previous one.  I guess the test cases are concurrent, so you still can't separate out which test case causes errors?

**Comment by erictune** [comment]
Same symptom for other 2 failed tests.  The never-started pod was always on the same minion (e2e-gce-builder-2-0-minion-xobd).  

Anyhow, definitely not a problem with job controller.  It starts the pods that it should start, and waits for them.

**Comment by erictune** [comment]
Examining the kubelet log [104.197.134.184:22-kubelet.log](https://00e9e64bacb7878cf3e85d17a69684673061418aa77a0dd969-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F21012%2Fkubernetes-pull-build-test-e2e-gce%2F28235%2Fartifacts%2F104.197.134.184:22-kubelet.log?qk=AD5uMEuL1aX7CXjMkdfZCUNLOue8d5jpu9TUfURlDLwqO2ZHdwDiNMqUPIPztiTKao9P2VW3QCK6Li0_Wj7Sn8LXwaYsXYGFSgpN2gI8S2ECFiZrSW2aMwif7JSzvjbK-E52KjIOBrnfWcjN251iFnGiLvsMuZY13bLk3tZMfcAKlypoqW3BxvHv3PxZfNa5Nd7mSPy8DVFuKA1tQqsaPHwLsRMZljxkHk1pRSSdZ05GzsI1pzQKI7s61ACdqSjVi361f-EjFsPskt8VVZ-9NYklhZ0KiCfQ5OZbfeV_JCdchUjRRxXLSC3ND1pl1r6zYhwGZf-45VD-IvGw9IUib6TO9-9wA_4CKSds5Ld64bWI5pwDFdXz7Qs1N_IKmqMSWJuVRgbQ1wp9RxW7y20HuW5V2bNrQiGyKDMDMk61xd2hMpUteS3d9JJH586sa6x2S8rUyXORM9aIjLHYcbO6pBIVXEDc5mowSs4e1mUGMsfkitQrCjJ9ZalKpZRwPCvmJi7dqKzknuObw4bya4aA5eIj67zb_hPzh7fWG0ZVkIe9z_8WMCI_mspss2ECccqco4CV7WnqsWkj8QWg4_TMNptNFkP0yC0aUlqTGDDfN0w6FexhU4pYtHrPPfMUNnNZFCKwfIxyHFAE_JLYZ4ehzf3hz7pWxl94zT4W-MoHqbwFgZLc_SmTSNtetZtiBuNiXzgY5x0aBqH7vfum3pr-KAbzl2Da5575drbYx9jJqazMOoUX7tpMzxXPc-ylpp--aFMZPHxMTIUhP8AhYO0gfI4acdtlnZpGzgWFh2DdoCX2Arxh3egTcqe9pN6pnFTXWC_GVi9qhjS0rCJ_6Lb-PwcP20weJRUGHHamf7zra7CJUdhK3ucmQi-cbunfkQUVW1MlA8kuoNphnoodaLdLIEiWv5-kQDJISpxUhBrhtr2cPXUGKnfzoBzYoLGK9tO2MZumHpNS-hqfQPMdB8UsFrYzegaquTcfMw)

**Comment by erictune** [comment]
Confused as to why times are different between the kubelet and e2e log.  I get that they have different time zones, and so differ by hours, but the minutes should be the same.
I see this in the kubelet log:

```
I0212 15:08:11.249194    3890 config.go:393] Receiving a new pod "fail-once-local-r6hqn_e2e-tests-job-r1z3y(6e23f2c1-d19a-11e5-8e8a-42010af00002)"
``` 

and this in the e2e log:
```
Feb 12 07:23:04.191: INFO: event for fail-once-local-r6hqn: {kubelet e2e-gce-builder-2-0-minion-xobd} Pulling: pulling image "gcr.io/google_containers/busybox:1.24"
```

**Comment by erictune** [comment]
I carefully compared kubelet logs from bad kubelet and a good kubelet.
The good and bad are the same up to this point (from bad one; good is similar)
```
I0212 15:08:11.894177    3890 kubelet.go:2324] SyncLoop (PLEG): "fail-once-local-r6hqn_e2e-tests-job-r1z3y(6e23f2c1-d19a-11e5-8e8a-42010af00002)", event: &pleg.PodLifecycleEvent{ID:"6e23f2c1-d19a-11e5-8e8a-42010af00002", Type:"ContainerStarted", Data:"5032a5cb8b882e6eb82ce7d8abba525c4bc9ce53c47dc342567de0d0b3712834"}

```

After that, there are no more log lines in the bad kubelet log about that pod until 15:23:07.

**Comment by erictune** [comment]
Okay, the times make sense, actually.
The failing test starts at `07:08:02` in the jenkins log, and then times out at `07:23:04`.
And the pods are created around `15:08` in the kubelet logs, and then there is a remove at `15:23`.

**Comment by erictune** [comment]
It seems that the container did exit but kubelet missed the exit.

**Comment by timstclair** [comment]
Re: "ERROR kubelet_docker_errors" - I'm afraid I just touched that line in a refactoring and don't know much about it

Also, times between the kubelet and e2e logs usually line up, I'm not sure why they don't here.

/cc @yujuhong has been looking into some issues and flakes around image pulling

**Comment by erictune** [comment]
Filed 21336 with details for node team to debug kubelet issue.
