### ISSUE TITLE
Re-enable rhel and centos targets for node e2e tests once they pass

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#21173]

**Comment by vishh** [comment]
cc @derekwaynecarr @ncdc

**Comment by derekwaynecarr** [comment]
How is the kubelet configured when running these tests?  Is this via the salt config?  I can look to see if incorrect options are being passed to RHEL derived distros.

**Comment by vishh** [comment]
@derekwaynecarr: Look [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/e2e_service.go#L137). Salt is not used. The kubelet binary is copied over the test machine and started by a test runner framework. It should be easy to use the runner directly on RHEL or CentOS nodes.
