### ISSUE TITLE
cluster/ubuntu scripting establishes insecure connections from kubelet and kube-proxy to API server

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#21171]
The kubelet and kube-proxy are given no certificate and connect to the insecure port of the API server.

**Comment by dalanlan** [comment]
Do we really want this, a secure connection from kubelet/kube-proxy to api-server? It will introduce unnecessary overhead IMO.

**Comment by MikeSpreitzer** [comment]
Yes, some k8s operators want this as an option.  It is a standard security practice in some shops.

**Comment by roberthbailey** [comment]
`cluster/ubuntu` was removed in https://github.com/kubernetes/kubernetes/pull/44344 so I'm marking this issue as obsolete.
