### ISSUE TITLE
Kubelet issue pulling docker images

### ISSUE THREAD

**Issue by PhilibertDugas** [kubernetes/kubernetes#21189]
Hi,

I'm facing an issue with the Kubelet trying to pull docker images and I can't seem to figure it out.

When creating a new replication controller, the pod seem to be in a looping failure complaining it can't pull the Docker image.

However, if I go on the Node itself and execute a docker pull on the image it seems to have no error.

We are using a private repository JFrog Artifactory version 4.2.2

Kubelet Logs:
`Feb 12 21:40:16 dselilx5553 kubelet[31271]: I0212 21:40:16.453013   31271 docker.go:156] Pulling image <private-image> without credentials`

`Feb 12 21:40:16 dselilx5553 kubelet[31271]: W0212 21:40:16.579187   31271 manager.go:1569] Failed to pull image "<private-image>" from pod "backend-controller-ntbqd_default" ...10, this may be b`

Docker Command
``# docker pull <private-image>
Trying to pull repository <private-image>: Pulling from <private-image>
bdc9b1e5061c: Pull complete
e241de3df6f5: Pull complete
f5ccee591802: Already exists
ef573796f521: Already exists
12dd95ea14b2: Already exists
790ad9392c6e: Already exists
8f86cb978197: Already exists
bb4936805c54: Already exists
Digest: sha256:d0fa70dc3b0725e7eb435b5fd42abc90399257f7d239a10b3dcde7830e0c27ae
Status: Downloaded newer image for <private-image>
``

# kubelet --version
`Kubernetes v1.0.3.34+b9a88a7d0e357b`

# uname -a
`Linux dselilx5553 3.10.0-229.el7.x86_64 #1 SMP Thu Jan 29 18:37:38 EST 2015 x86_64 x86_64 x86_64 GNU/Linux`

# docker --version
`Docker version 1.8.2, build bb472f0/1.8.2`

# Release
`NAME="Red Hat Enterprise Linux Server"
VERSION="7.1 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.1"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.1 (Maipo)"`

**Comment by dchen1107** [comment]
@PhilibertDugas Have you checked this doc: https://github.com/kubernetes/kubernetes/wiki/User-FAQ yet?

**Comment by PhilibertDugas** [comment]
@dchen1107 I went through the doc!

I pre-fetched the images, I'm able to user a docker pull on all the minions, but the issue still occurs on the Kubelet level when trying to spawn the pods

I actually have another cluster running the same images with Docker 1.7 and there are no issues for this one, so I'm not too sure what's going on

**Comment by PhilibertDugas** [comment]
Seems like docker login stores the authorization config in ~/.dockercfg while kubelet was looking in /var/lib/kubelet/.dockercfg

**Comment by rmahajan2420** [comment]
Thank you so much . @PhilibertDugas . I have been struggling with this since yesterday morning. you have saved me..
