### ISSUE TITLE
AWS: allow users to specify that their node ASG should use spot instances

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21200]
Particularly now we have KUBE_USE_EXISTING_MASTER, it would make sense to allow users to add an ASG which uses spot instances.

Probably yet another env var.

**Comment by binarybana** [comment]
In addition to the spot based ASGs we've been using in our cloudformation scripts, we've also begun experimenting with spot fleets for multiple instances types and more granular control over instance termination on cluster spin down as our long running jobs complete.

**Comment by gy8** [comment]
+1 for spot fleet, that would sweeet

**Comment by therc** [comment]
Does this need any new code to detect in a timely fashion that a node is getting evicted? Amazon recommends checking metadata for the termination notice every five seconds, but the AWS cloudprovider's isAlive() already considers a machine in "shutting down" state as not present. That could use better log messages, but is it already enough? I haven't tried it, but I assume that the spot instance would also be in "shutting down" state during those two minutes. And the nodecontroller runs every five seconds.. right?

**Comment by justinsb** [comment]
I believe an ASG using spot instances will work with today's code.  Maybe we'll make some poor scheduling decisions if we don't listen to notifications, but it should look like our instances are just a little less reliable.
