### ISSUE TITLE
AWS: Should we have our own AMI?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21217]
If we bake our own AMI, we can make installation much faster, and we can also solve reboot-required problems that prevent us from using Jessie, for example.

It is obviously work to maintain, but we should consider doing so, particularly as it would let us take complexity out of the boot scripts (and get us closer to k8s-on-k8s world!)

**Comment by justinsb** [comment]
To do this, we would need at least the following:

- an automated process for building these AMIs that was open and that we could (potentially) check into the git repo (Packer?  Animator?)
- we'd have to make these AMIs available as public AMIs
- the procedure must be able to be done by others - i.e. using our public AMIs should be a time-saver, but the paranoid could always build their own
- we'd have to make sure the AMIs were available in every region

**Comment by TamalSaha** [comment]
@justinsb, will be possible to build the AMI using Jessie 8.3? The official Debian AMI is Debian 8.1. It will be great to have OS version parity between GCE and AWS. Thanks.

**Comment by justinsb** [comment]
Well first of all, I'm not sure we're doing this, but...

I hope to get parity, yes.  I believe Debian 8.3 is jessie with all the latest updates applied, so we likely do that anyway to save time during first boot by avoiding having to upgrade.  The question of how often we would re-build the image is an open question.

I have asked on slack how the GCE image is built.  I would love to use the exact same tools as they do, and ideally even share scripts for 100% parity.

**Comment by davidopp** [comment]
@zmerlynn

**Comment by justinsb** [comment]
Consensus seems to be that we should build our own image, at least for AWS.  We can converge with the GCE/GKE custom image also.

As such, closing this one - we're going to build one!
