### ISSUE TITLE
e2e: make sure we have a partition mounting test

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21219]
See issue #15050; we should make sure that we have a test that checks that partitions are respected with AWS EBS volumes

**Comment by justinsb** [comment]
I'm not going to get the time to work on this, I don't think.  We don't have an e2e test, I think because it's not obvious how to set up the partitions.  This problem applies to GCE also (I thought I was just going to copy the GCE test for AWS...)

**Comment by thockin** [comment]
I'm unblocking 1.2 on this
