### ISSUE TITLE
Kubernetes support in AWS for systemd flavored Debian

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#21214]
@justinsb, we are trying to create Kube cluster using Debian jessie in AWS. But the master will not stay on and we can't also see the system log. Given vivid is now officially EOL, AWS is lacking any working systemd enabled Debian flavored host OS support. Can you please look into this? Is there any way I can debug this issue?

**Comment by rastut** [comment]
You can check this PR for solve the boot problem #18821

All the AMI used on `cluster/aws/jessie/util.sh` are flavored with systemd. 

```
admin@ip-172-31-29-61:~$ curl http://169.254.169.254/latest/meta-data/ami-id
ami-02b78e1f
admin@ip-172-31-29-61:~$ ps -p 1 -o comm=
systemd
```
https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/jessie/util.sh#L44-L46

**Comment by justinsb** [comment]
I have Ubuntu 15.10 support in a branch (tracking as issue #21143); I'll make sure it gets merged in 1.2.  Also, I'm trying to make sure 14.04 (LTS)  continues to work, though I don't think I'd recommend using a non-systemd system.

I would love to have Jessie working, but it requires a reboot to enable the memory controller.  I think maybe I have an approach, but sadly there's more to it than just 18821.  I opened issues for two approaches: #21216 for the non-AMI approach, and #21217 for building an AMI

**Comment by davidopp** [comment]
@zmerlynn

**Comment by justinsb** [comment]
We will support wily and jessie in 1.2.  Both are working in my integration branch.  I believe once #21904 merges, both will work on master also.

**Comment by justinsb** [comment]
Closing as we have a systemd working now via jessie.  And we'll have wily & vivid as well.
