### ISSUE TITLE
AWS: Support jessie (non-AMI version)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21216]
Given Ubuntu's short non-LTS support policy, it becomes even more important to support Debian (jessie).  Jessie support is broken currently, but I think we can fix it.  The biggest problem is that by default the memory cgroup is not enabled, so it requires a reconfiguration and reboot.

We could build our own AMI (tracking as issue #21217 ), but we can also fix it by:
- [ ] Merge support for non-sda boot AMIs (#18821 - thanks @rastut)
- [ ] Check if the memory controller is enabled, and if not enable it and trigger a reboot (maybe after a kernel update)
- [ ] Fix salt scripts e.g. Docker 1.8.3
- [ ] Unknowns

**Comment by rastut** [comment]
In order to trigger we can check it on `/sys/fs/cgroups/memory` and can be executed during the checks. After that perform the best approach in order to reboot the instance. Let me know if i can help with a pr @justinsb

**Comment by justinsb** [comment]
I think I would welcome that PR @rastut :-)  I'm a little overloaded, as you can probably tell given my review delays...

I'm also seriously thinking that we should do an AMI.  What do you use for your AMIs?  I'm exploring at bootstrap-vz, because that seems to be what Debian uses for the official images and because it supports multiple clouds.  But this is just from some very preliminary googling...

**Comment by rastut** [comment]
I think that the idea of the k8s AMI is great, we will get fast deploy and fast troubleshooting. Also if we have and official AMI we can implement, an other kind of deploy based on Cloudformation or User-Data.

Actually for automated AMI i have been using Packer, but i can take a look to bootstrap-vz.

**Comment by justinsb** [comment]
Apparently GCE's image is built using bootstrap-vz, so I looked into that.  I put up a WIP-for-discussion PR as well; with that Debian appears to work well: #21226

**Comment by davidopp** [comment]
@zmerlynn

**Comment by justinsb** [comment]
I think for 1.2 we're going to do the AMI version only.  Hopefully by 1.3 we won't have to enable the cgroup memory controller with the official image, or at least it will use a bootloader that makes it easier to change flags & reboot.
