### ISSUE TITLE
Exec should use AttachablePodForObject so that we can exec into a deployment

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#21227]
Would allow:

```
kubectl exec deployment/foo ...
```

Basically make it equivalent with attach. Not 1.2 at this point.

**Comment by Pensu** [comment]
+1 for it. That's a good idea. Is there any other way to attach to a container that is currently present in kubernetes?

**Comment by AdoHe** [comment]
@Pensu kubectl has a `attach` command, you can attach to running container.

**Comment by Pensu** [comment]
Yeah, just saw it. Thanks @AdoHe

**Comment by kargakis** [comment]
Supported by `kubectl attach` in https://github.com/kubernetes/kubernetes/pull/40365
