### ISSUE TITLE
Nginx Logging in Volume tests

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#21229]
Right now it appears to me that the function `testVolumeClient` doesn't log whats happening at server spin up time.  This means that when testing a volume, if the nginx part doesn't come up, we don't know why.  

Lets look into nginx verbosity and see if we can put more data into the RCs started in the volume 

This would help with issues such as  https://github.com/openshift/origin/issues/7287

**Comment by jayunit100** [comment]
cc @kubernetes/sig-testing

**Comment by jayunit100** [comment]
Really the issue here is decoupling, more than just logging.  
we need either
- a Before which makes sure nginx works b4 trying to mount storage
- more verbose logging setup for nginx so that if it fails in the tests its immediately apparent why.

right now, we just get 
```
STEP: reading a web page from the client
Mar  4 16:11:37.918: INFO: body: Error: 'dial tcp 10.1.0.53:80: i/o timeout'
Trying to reach: 'http://10.1.0.53:80/'
```

which can be confusing in the test logs, since its not clear unless you know the code wether its a client or just a dump of a container error message

**Comment by jayunit100** [comment]
After thinking more , i realized the real problem is the coupling, not nginx itself....

In certain network configs, you can get this faulre when running test/e2e/volumes.go
```
 <[]uint8 | len:83, cap:512>: Error: 'dial tcp 10.1.0.13:80: i/o timeout'
        Trying to reach: 'http://10.1.0.13:80/'
    to contain substring
        <string>: Hello Ceph!
```
However, in this case, the  volumes work just fine:
```
[root@ip-172-18-10-82 ec2-user]# docker exec -t -i 3a0b80139eb6 /bin/bash
root@cephfs-client:/# ls /usr/share/nginx/html/
index.html
root@cephfs-client:/# cat  /usr/share/nginx/html/index.html
Hello Ceph!
```
- We can easily decouple the volume tests from the need to serve web pages on port 80.
- and in fact, from any web server - by simply listing directory contents and scanning them
- This also decouples us from needing to rely on nginx logging.

**Comment by stmcginnis** [comment]
Looks like this should have been closed with the associated patch?
