### ISSUE TITLE
AWS kube-up: Node disk size is incompatible with instance storage

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21225]
Currently we can configure the node disk size, but it won't be used for containers if instance storage is also available.  Also, if you choose e.g. btrfs, it won't work unless you have instance storage.

We should at least fix the docs in 1.2, and ideally fix the behavior to be more understandable/consistent.

**Comment by goltermann** [comment]
bringing a few P2 doc bugs back in the 1.3 milestone

**Comment by justinsb** [comment]
We actually have a workaround, so this really is a docs issue:

In 1.3, you can `export KUBE_AWS_STORAGE=ebs` and we will not use instance storage.  Arguably it should be the default, but that behavioural change would probably surprise some people.  Current plan is for upup will not use instance storage (by default)

**Comment by goltermann** [comment]
This is an issue marked v1.3 and kind/documentation.  Can you get it fixed up this week?
