### ISSUE TITLE
Add a pod exec conformance test

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#21231]
see #21230 for motivation

**Comment by Pensu** [comment]
Do you want any help with this? I would like to take this up and try to implement.

**Comment by jayunit100** [comment]
@sig-testing

**Comment by jayunit100** [comment]
If someone gets a patch before me that's great I won't be able to look at it until tonite

**Comment by ncdc** [comment]
We have exec e2e tests in kubectl.go. Do those just need to be marked [Conformance]?
