### ISSUE TITLE
e2e flake: LimitRange [It] should create a LimitRange with defaults and ensure pod has those defaults applied.

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#21234]
LimitRange e2e flake:

```
Failure [7.616 seconds]
LimitRange
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/limit_range.go:95
  should create a LimitRange with defaults and ensure pod has those defaults applied. [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/limit_range.go:93

  Expected error:
      <*errors.errorString | 0xc20853e960>: {
          s: "resource cpu expected 100m actual 0",
      }
      resource cpu expected 100m actual 0
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/limit_range.go:64
------------------------------
```

https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/20114/kubernetes-pull-build-test-e2e-gce/28527/

**Comment by lavalamp** [comment]
Maybe @nikhiljindal has time?

**Comment by nikhiljindal** [comment]
This test seems to have flaked again in http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/29036.

I cant repro this locally (I keep hitting https://github.com/kubernetes/kubernetes/issues/21261#issuecomment-185509681)

Sent https://github.com/kubernetes/kubernetes/pull/21516 to improve failure logs

**Comment by bprashanth** [comment]
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/29285/consoleFull
https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21326/kubernetes-pull-build-test-e2e-gce/29285/artifacts/
```
• Failure [88.596 seconds]
LimitRange
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/limit_range.go:95
  should create a LimitRange with defaults and ensure pod has those defaults applied. [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/limit_range.go:93

  Expected error:
      <*errors.errorString | 0xc208527830>: {
          s: "resource cpu expected 100m actual 0",
      }
      resource cpu expected 100m actual 0
```

**Comment by nikhiljindal** [comment]
Should be fixed by https://github.com/kubernetes/kubernetes/pull/21470 from @deads2k

**Comment by deads2k** [comment]
@derekwaynecarr fyi

**Comment by derekwaynecarr** [comment]
@deads2k - thanks for the heads up... i will make the corresponding change to the quota admission handler.

**Comment by ncdc** [comment]
@deads2k I just hit this in 21781 :-(

**Comment by derekwaynecarr** [comment]
since @deads2k is ill, I will take a look.

**Comment by derekwaynecarr** [comment]
So my current theory is the following:

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/limitranger/admission.go#L98

The limit ranger lru cache is being populated to an empty list when the `LimitRange` resource itself is being created.  The watch is not notifying of the new `LimitRange` before the pod creation then happens.  The limit range cache looks at its last entry (which was the empty list), and the default is then not applied.

I think for now, the right fix is have limit range ignore non-pod resources since it only supports pod today.  If/when it supports pvcs, we can expand the list.
