### ISSUE TITLE
Add pod executable check to Volume test

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#21230]
Since 
- volume tests rely on executing commands in pods `_, err = lookForStringInPodExec(config.namespace, clientPod.Name, []string{"ls", "-ld", "/usr/share/nginx/html"}, strconv.Itoa(int(*fsGroup)), time.Minute)`
- almost no other tests rely on this feature

... we should make sure that this command actually is working properly before starting the tests. (i.e. make sure that lookForStringInPodExec is working).  Its a non-trivial failure that could create several hard-to-debug false-negatives.

Its not used commonly, and we don't want false correlations between pod exec failures and storage failures.

cc @kubernetes/sig-testing

**Comment by spiffxp** [comment]
/close
Looks like `lookForStringInPodExec` doesn't exist anymore, and tests that reference /usr/share/nginx/html don't rely on executing commands / parsing pod output
