### ISSUE TITLE
Progamatically ensure that all predicate/priority functions that are tested are registered

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#21236]
@resouer I just noticed you forgot to register the image locality priority function in `init()` in `plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go`

I also missed it when I reviewed your PR.

I have fixed this in #21235. But it would be great if you could figure out a mechanism that would ensure that all predicate/priority functions that are tested (you can assume they will always live under `plugin/pkg/scheduler/algorithm/{predicates,priorities}`) are registered, and fail the test if not. That will allow us to prevent this mistake in the future.

**Comment by resouer** [comment]
Thanks! Will fix this soon!

**Comment by resouer** [comment]
Seems need to wait for #21235 in before I send PR? Otherwise this test will always fail ...
