### ISSUE TITLE
Can't access kube-ui via docs urls

### ISSUE THREAD

**Issue by razvip91** [kubernetes/kubernetes#21246]
Hello!

I've been playing around with kubernetes for some time now and have hit my head against this issue every time: I launch kube-ui like in the kubernetes docs and everything works as expected, but when I try to access the dashboard via the given URLs (http://master-node-IP:8080/ui and http://master-node-ip:8080/api/v1/proxy/namespaces/kube-system/services/kube-ui/#/dashboard/) I get the following error:

Error: 'dial tcp kube-ui-container-IP:8080: no route to host'
Trying to reach: 'http://kube-ui-container-IP:8080/'

I have a cluster of 3 VMs with coreOS running kubernetes.

Any suggestions would be welcome!

Thanks!

**Comment by sjenning** [comment]
The docs say http**s**.  Can you try that?

**Comment by razvip91** [comment]
I just did. It gave me an ERR_SSL_PROTOCOL_ERROR

**Comment by sjenning** [comment]
It is using a self-signed cert.  Do you just need to accept the untrusted cert?  Or is it a different issue?

**Comment by razvip91** [comment]
I think it is a different issue. I doesn't make me accept any certificate. It is an error (the one above) from Chrome.

**Comment by sjenning** [comment]
I can see what you are talking about.  It  would seem that documentation is out of date.

https://github.com/kubernetes/kubernetes/tree/master/www

kube-ui has moved out of the main kubernetes project and if you go to the kube-ui repo

https://github.com/kubernetes/kube-ui

You see:

> Also please check out the new Dashboard for Kubernetes available at: https://github.com/kubernetes/dashboard
> 
> This codebase will be retired once the new and improved Dashboard is production ready.

**Comment by razvip91** [comment]
That I know. I run the kube-ui server on my localhost and proxied its requests through nginx (for CORS headers addition) to the k8s-api server. This way it works. So, we may call it a success (somehow). Will close the issue. Thanks!
