### ISSUE TITLE
How to use the flag   --log-dir?

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#21248]
I want  to collector K8s's  logs. So when I use --help like   kubelet --help:   It showed that with the flag:
`--log-dir`  I can  write logs into the specificed directory.  I tried it with the command : `kubelet --log-dir="/app/logs/" (and some other flags,such as --alsologtostderr=true)` , Of course I create  the directory before.
But It doesn't work.Nothing created in the directory.

I run a k8s cluster by starting binary files but not systemctl service.  So I really wonder how to  use it.

**Comment by resouer** [comment]
Use `--logtostderr=false --log-dir=XXX`

**Comment by ZhengRongTan** [comment]
set --logtostderr=false and --log-dir=xxx , not work !!

**Comment by zhanglx96** [comment]
@ssslkj123 It is available, but kubelet logs can still be seen in /var/log/messages, how can I make /var/log/messages not show kubelet logs.

**Comment by bertreyking** [comment]
[root@k8s-master03 log]# kubelet --version
Kubernetes v1.16.2

[root@k8s-master03 log]# cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS="--cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=10.6.203.60:5000/pause:3.1 --log-dir=/var/log/kubelet/ --log-file=/var/log/kubelet/kubelet.log --logtostderr=false"

it's ok

**Comment by yuzhiquan** [comment]
> @ssslkj123 It is available, but kubelet logs can still be seen in /var/log/messages, how can I make /var/log/messages not show kubelet logs.

BTW, why don`t want shows log in syslog?

**Comment by vsxen** [comment]
kubelet --version
Kubernetes v1.21.1

when use text format STDERR also print in screen.

```
root@ubuntu-focal:/home/vagrant# /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/run/containerd/containerd.sock --pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.4.1 --log-file=kubelet.log --logtostderr=false
E0610 02:55:28.185750   64201 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
E0610 02:55:28.211701   64201 cri_stats_provider.go:369] "Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache" mountpoint="/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs"
E0610 02:55:28.211823   64201 kubelet.go:1306] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
E0610 02:55:28.384965   64201 kubelet.go:1870] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
E0610 02:55:28.490893   64201 kubelet.go:1870] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
E0610 02:55:28.573492   64201 container_manager_linux.go:553] "Failed to find cgroups of kubelet" err="cpu and memory cgroup hierarchy not unified.  cpu: /user.slice, memory: /user.slice/user-1000.slice/session-1.scope"
E0610 02:55:28.721630   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"kube-scheduler-ubuntu-focal\" already exists" pod="kube-system/kube-scheduler-ubuntu-focal"
E0610 02:55:28.724433   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"kube-controller-manager-ubuntu-focal\" already exists" pod="kube-system/kube-controller-manager-ubuntu-focal"
E0610 02:55:28.727126   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"etcd-ubuntu-focal\" already exists" pod="kube-system/etcd-ubuntu-focal"
E0610 02:55:29.013179   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"kube-apiserver-ubuntu-focal\" already exists" pod="kube-system/kube-apiserver-ubuntu-focal"


^Croot@ubuntu-focal:/home/vagrant# tail kubelet.log
I0610 02:55:28.723587   64201 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/4e1754d14671547e805dcefd376ee94b-kubeconfig\") pod \"kube-scheduler-ubuntu-focal\" (UID: \"4e1754d14671547e805dcefd376ee94b\") "
I0610 02:55:28.723605   64201 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/d5eaea6e2bbfc49976c19f6cdc41f78f-k8s-certs\") pod \"kube-apiserver-ubuntu-focal\" (UID: \"d5eaea6e2bbfc49976c19f6cdc41f78f\") "
I0610 02:55:28.723624   64201 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/d5eaea6e2bbfc49976c19f6cdc41f78f-usr-local-share-ca-certificates\") pod \"kube-apiserver-ubuntu-focal\" (UID: \"d5eaea6e2bbfc49976c19f6cdc41f78f\") "
I0610 02:55:28.723640   64201 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"flexvolume-dir\" (UniqueName: \"kubernetes.io/host-path/bb47329f88794e5e9d58a656ecf47f1b-flexvolume-dir\") pod \"kube-controller-manager-ubuntu-focal\" (UID: \"bb47329f88794e5e9d58a656ecf47f1b\") "
I0610 02:55:28.723658   64201 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/73f2ed0d-2164-44c5-9294-5d13ad76412c-config-volume\") pod \"coredns-57d4cbf879-5j6x2\" (UID: \"73f2ed0d-2164-44c5-9294-5d13ad76412c\") "
I0610 02:55:28.723665   64201 reconciler.go:157] "Reconciler: start to sync state"
E0610 02:55:28.724433   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"kube-controller-manager-ubuntu-focal\" already exists" pod="kube-system/kube-controller-manager-ubuntu-focal"
E0610 02:55:28.727126   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"etcd-ubuntu-focal\" already exists" pod="kube-system/etcd-ubuntu-focal"
E0610 02:55:29.013179   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"kube-apiserver-ubuntu-focal\" already exists" pod="kube-system/kube-apiserver-ubuntu-focal"
I0610 02:55:31.170211   64201 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/etc/kubernetes/pki/ca.crt
```


when I use json format, kubelet will exit

```
/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/run/containerd/containerd.sock --pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.4.1 --log-file=kubelet.log --logtostderr=false --logging-format=json
Flag --logging-format has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --logging-format has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
E0610 02:57:09.020577   64401 server.go:224] "Failed to validate kubelet configuration" err="[non-default logging format doesn't honor flag: log_file, non-default logging format doesn't honor flag: logtostderr]" path="&TypeMeta{Kind:,APIVersion:,}"
```
ping 
https://github.com/kubernetes/kubernetes/pull/102716

**Comment by shenshouer** [comment]
set --logtostderr=false and --log-dir=xxx , not work 
kubelet --version
Kubernetes v1.21.1

**Comment by yuzhiquan** [comment]
> kubelet --version
> Kubernetes v1.21.1
> 
> when use text format STDERR also print in screen.
> 
> ```
> root@ubuntu-focal:/home/vagrant# /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/run/containerd/containerd.sock --pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.4.1 --log-file=kubelet.log --logtostderr=false
> E0610 02:55:28.185750   64201 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
> 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
> E0610 02:55:28.211701   64201 cri_stats_provider.go:369] "Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache" mountpoint="/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs"
> E0610 02:55:28.211823   64201 kubelet.go:1306] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
> E0610 02:55:28.384965   64201 kubelet.go:1870] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
> E0610 02:55:28.490893   64201 kubelet.go:1870] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
> E0610 02:55:28.573492   64201 container_manager_linux.go:553] "Failed to find cgroups of kubelet" err="cpu and memory cgroup hierarchy not unified.  cpu: /user.slice, memory: /user.slice/user-1000.slice/session-1.scope"
> E0610 02:55:28.721630   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"kube-scheduler-ubuntu-focal\" already exists" pod="kube-system/kube-scheduler-ubuntu-focal"
> E0610 02:55:28.724433   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"kube-controller-manager-ubuntu-focal\" already exists" pod="kube-system/kube-controller-manager-ubuntu-focal"
> E0610 02:55:28.727126   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"etcd-ubuntu-focal\" already exists" pod="kube-system/etcd-ubuntu-focal"
> E0610 02:55:29.013179   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"kube-apiserver-ubuntu-focal\" already exists" pod="kube-system/kube-apiserver-ubuntu-focal"
> 
> 
> ^Croot@ubuntu-focal:/home/vagrant# tail kubelet.log
> I0610 02:55:28.723587   64201 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kubeconfig\" (UniqueName: \"kubernetes.io/host-path/4e1754d14671547e805dcefd376ee94b-kubeconfig\") pod \"kube-scheduler-ubuntu-focal\" (UID: \"4e1754d14671547e805dcefd376ee94b\") "
> I0610 02:55:28.723605   64201 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"k8s-certs\" (UniqueName: \"kubernetes.io/host-path/d5eaea6e2bbfc49976c19f6cdc41f78f-k8s-certs\") pod \"kube-apiserver-ubuntu-focal\" (UID: \"d5eaea6e2bbfc49976c19f6cdc41f78f\") "
> I0610 02:55:28.723624   64201 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"usr-local-share-ca-certificates\" (UniqueName: \"kubernetes.io/host-path/d5eaea6e2bbfc49976c19f6cdc41f78f-usr-local-share-ca-certificates\") pod \"kube-apiserver-ubuntu-focal\" (UID: \"d5eaea6e2bbfc49976c19f6cdc41f78f\") "
> I0610 02:55:28.723640   64201 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"flexvolume-dir\" (UniqueName: \"kubernetes.io/host-path/bb47329f88794e5e9d58a656ecf47f1b-flexvolume-dir\") pod \"kube-controller-manager-ubuntu-focal\" (UID: \"bb47329f88794e5e9d58a656ecf47f1b\") "
> I0610 02:55:28.723658   64201 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/73f2ed0d-2164-44c5-9294-5d13ad76412c-config-volume\") pod \"coredns-57d4cbf879-5j6x2\" (UID: \"73f2ed0d-2164-44c5-9294-5d13ad76412c\") "
> I0610 02:55:28.723665   64201 reconciler.go:157] "Reconciler: start to sync state"
> E0610 02:55:28.724433   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"kube-controller-manager-ubuntu-focal\" already exists" pod="kube-system/kube-controller-manager-ubuntu-focal"
> E0610 02:55:28.727126   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"etcd-ubuntu-focal\" already exists" pod="kube-system/etcd-ubuntu-focal"
> E0610 02:55:29.013179   64201 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"kube-apiserver-ubuntu-focal\" already exists" pod="kube-system/kube-apiserver-ubuntu-focal"
> I0610 02:55:31.170211   64201 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/etc/kubernetes/pki/ca.crt
> ```
> 
> when I use json format, kubelet will exit
> 
> ```
> /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/run/containerd/containerd.sock --pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.4.1 --log-file=kubelet.log --logtostderr=false --logging-format=json
> Flag --logging-format has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> Flag --logging-format has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
> E0610 02:57:09.020577   64401 server.go:224] "Failed to validate kubelet configuration" err="[non-default logging format doesn't honor flag: log_file, non-default logging format doesn't honor flag: logtostderr]" path="&TypeMeta{Kind:,APIVersion:,}"
> ```
> 
> ping
> #102716

JSON log format doesn't implement logtostderr flag now, so it's exited, and here is proposal for this https://github.com/kubernetes/kubernetes/issues/99270#issuecomment-864605988.

**Comment by gengwg** [comment]
Might be unrelated to this problem. I am experiencing a weird problem with log redirection. Specifically, on the virtual machines, the logs are being redirected to stderr, whereas on the physical machines, they are being redirected to stdout. Both the VMs and physical machines are running Kubernetes v1.22.9 and have the same configuration. If anyone has any insights into why this inconsistency is occurring, I would greatly appreciate your input.

- VM:

```
[root@VM kubernetes]# ll
total 180
-rw-r--r-- 1 root root 184316 Jun 28 17:23 kubelet.err
-rw-r--r-- 1 root root      0 Jun 28 16:57 kubelet.log
```

- PM:

```
[root@PM kubernetes]# ll
total 948
-rw-r--r-- 1 root root 970326 Jun 28 17:35 kubelet.log
```
