### ISSUE TITLE
e2e flake: Scalability tests are failing with "not able to ssh" error

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#21249]
Recently, we have 5+ failures, which failed with:

    17:06:30 Build was aborted

log. However, before that, we have 1GB+ logs like this one:

    17:06:30 Feb 14 17:06:30.375: INFO: Error while trying to SSH to 104.197.188.188:22, skipping probe. Error: error getting signer for provider gce: 'error reading SSH key /var/lib/jenkins/jobs/kubernetes-e2e-gce-scalability/workspace/.ssh/google_compute_engine: 'open /var/lib/jenkins/jobs/kubernetes-e2e-gce-scalability/workspace/.ssh/google_compute_engine: too many open files''

Example failures:
https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/4605/build-log.txt
https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/4607/build-log.txt

**Comment by gmarek** [comment]
This issue went away for some time, and now it's back... There's a bug in backoff logic. I'll fix this, as it will help with the sizes of logs and hopefully it will solve the whole issue, as the problem is limit on a number of open FDs.

**Comment by gmarek** [comment]
Decreasing priority, and removing flake label, as PR is in flight.

**Comment by wojtek-t** [comment]
I don't think we should remove "kind/flake" label.

**Comment by wojtek-t** [comment]
Should be fixed in #21262 - I will reopen it in case it's not true.
