### ISSUE TITLE
kube-apiserver will not start in AWS Wily

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#21241]
Hi,
I tried running the Kube 1.1.7 using AWS Wily AMI. But the api-server will not start. I see the following log snippet in kubelet log.

Feb 15 07:06:52 ip-172-20-0-9 kubelet[9913]: E0215 07:06:52.018206    9913 manager.go:1864] Failed to create pod infra container: API error (500): Cannot start container d53b014092f54a3f4229826c0c304f2c000ecd035fe5d5a150e8a37d1b0ca33c: [8] System error: Invalid unit type.

Is this related to https://github.com/docker/docker/issues/17126 ? Can you please look into this?

**Comment by justinsb** [comment]
Fixed in my 1.2 integration branch, probably only once #21904 merges though

**Comment by justinsb** [comment]
Believed fixed but will verify after #21904 merges

**Comment by justinsb** [comment]
#21904 fixed this
