### ISSUE TITLE
Decide on the names of master component pods

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#21267]
Assuming that we're going to register 'master Node' we should decide on a common way of naming all the 'system pods'. We need to consider HA setups.

Currently we have the schema: `<component>-<master machine>`, e.g. `kube-controller-manager-kubernetes-master` and I like it - it'll make physically locating given component easy.

If we agree on this, we should add this as conformance requirement to our docs.

cc @bgrant0607 @spiffxp @thockin @dchen1107 @davidopp @wojtek-t

**Comment by spiffxp** [comment]
I don't like the idea of tacking on node or machine names to pod names.  `kube-controller-manager` and `kube-scheduler` could be running on entirely different machines.  If you need to colocate them, why not just have a `master` pod?

cc @mikedanese curious what this would look like for k8s-on-k8s

**Comment by mikedanese** [comment]
Should running the control-plane in static pods be required by the spec? Should registering the master kubelet be required by the spec? What are the implications of encoding information into names of pods? We should take these into account when making a decision here. 

@spiffxp As far as selfhosting, this precludes us from running control-plane components in deployments (which create pods with two levels of generated names). We could possibly modify deployment or replicaset to allow us to create pods from deployment controlled replicasets to conform to this naming schema but would @bgrant0607 let us?

What do we gain by doing this? Is there no other way to go about these (e.g. component registration)?

**Comment by spiffxp** [comment]
>Should running the control-plane in static pods be required by the spec? Should registering the master kubelet be required by the spec?

Some of the tests make these assumptions today (eg: density) and I don't think they should long term #20919

**Comment by bgrant0607** [comment]
Why do we need conforming names? And names of what?

If it's names of pods, that's an anti-pattern in Kubernetes.

**Comment by bgrant0607** [comment]
We absolutely want to self-host the Kubernetes control-plane components.

Additionally, in addition to HA configurations, some people plan to run their own schedulers, others run a different set of "addons", etc.

Component registration and labels sound like better solutions to me, but it's hard to say without understanding the motivation.

**Comment by gmarek** [comment]
Conforming labels for various components SG. Can we decide on them? `kube-component: api-server` etc?

**Comment by mikedanese** [comment]
I like e.g.: 
```
            "namespace": "kube-system",
            "labels": {
               "component": "controller-manager",
               "tier": "control-plane",
               "version": "v1.2.0"
            }
```
Which is what I've been using in self hosting configs [here](https://github.com/mikedanese/k8s-on-k8s/blob/master/apps/controller-manager.deployment.json#L21-L22). I've been using tier: node for kubelet, kube-proxy, fluentd. It should be understood by tests that a query that matches these labels is not guaranteed to match only a single pod. It could match zero or many.

**Comment by gmarek** [comment]
I'm all for it (well - I'm all for anything, as long as we can decide quickly on it). Can we have a decision that we're going with what @mikedanese proposed and describe the labeling schema in some doc somewhere? @bgrant0607

**Comment by bgrant0607** [comment]
@gmarek @mikedanese's proposal SGTM

**Comment by bgrant0607** [comment]
Note that addons already have labels:
```
metadata:
  name: kube-dns-v10
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v10
    kubernetes.io/cluster-service: "true"
```

`kubectl cluster-info` selects based on `kubernetes.io/cluster-service`.

I believe only e2e tests use `k8s-app`, but I could be wrong.

**Comment by bgrant0607** [comment]
Also, because label selectors are scoped by namespace, we don't really need the `kubernetes.io` prefixes on the label keys.

**Comment by bgrant0607** [comment]
@gmarek What do you plan to use the labels for?

**Comment by gmarek** [comment]
For monitoring. I need some way to get all, say, ReplicationController pods, when we move to self-hosted components, to read metrics from them.

**Comment by thockin** [comment]
We might get away with calling ourselves the user here, but I don't think
we should.  Namespaced keys are unambiguous in any case.

**Comment by gmarek** [comment]
@mikedanese - can you write a proposal?

**Comment by mikedanese** [comment]
I can submit a PR to add this. I'm thinking:
```
deploy.alpha.kubernetes.io/tier in (control-plane,node,monitoring)
deploy.alpha.kubernetes.io/component in (kube-controller-manager,kube-scheduler,kube-proxy....)
```

**Comment by gmarek** [comment]
cc @Random-Liu - you'll need to change performance data struct to use this.

**Comment by Random-Liu** [comment]
@gmarek Thanks! and /sub

**Comment by bgrant0607** [comment]
@thockin We own kube-system. Prefixes on labels are hostile to users. We should only use them when there is a real, compelling need to avoid conflicting with user-applied labels and/or to convey the stability level (alpha, beta, GA). I don't understand the motivation in this case.

Annotations are different. Annotations are primarily for machines. Labels are primarily for users.

**Comment by bgrant0607** [comment]
Are we going to depend on these specific label keys and values in tooling?

**Comment by mikedanese** [comment]
> Are we going to depend on these specific label keys and values in tooling?

@bgrant0607 I believe @gmarek want's to use these labels to target kube components for both monitoring and e2e testing

**Comment by bgrant0607** [comment]
@mikedanese @gmarek When adding dependencies on specific labels, please document that, since I suspect some breakages may not be immediately obvious in the case that someone were to change the labels.

**Comment by gmarek** [comment]
@bgrant0607 - we it should be documented? In the manifest by the label definition, or in one of many doc files?

**Comment by bgrant0607** [comment]
In the manifest, so someone making a change would see it. Thanks
