### ISSUE TITLE
refactor Printer arguments

### ISSUE THREAD

**Issue by pweil-** [kubernetes/kubernetes#21260]
The signature for creating a printer is growing pretty large now.  We should refactor the signature to take a `PrinterOptions` struct to make it a bit more friendly.

Example:

```
 func(mapping *meta.RESTMapping, noHeaders, withNamespace, wide bool, showAll bool, showLabels bool, absoluteTimestamps bool, columnLabels []string)
```

**Comment by deads2k** [comment]
@kubernetes/kubectl

**Comment by kargakis** [comment]
I am pretty sure I had seen a PR for this but I cannot find it.

**Comment by AdoHe** [comment]
+1 really necessary.

**Comment by ivan4th** [comment]
I'm working on this one.
