### ISSUE TITLE
kubectl - insecure-skip-tls-verify option is not (completely) skipping TLS verification

### ISSUE THREAD

**Issue by fiksn** [kubernetes/kubernetes#21283]
Hi,

I am running kubectl 1.1.7 (trying to connect to 1.1.7 kube api server on CoreOS 835.12.0) and get the following:

> F0215 22:24:22.421577   32722 helpers.go:96] error: couldn't read version from server: Get https://127.0.0.1:4433/api: x509: certificate is valid for A.B.C.D, not 127.0.0.1

(example is from "kubectl version" but nothing else works either)

That is of course completely legitimate if I wasn't using --insecure-skip-tls-verify (also tried through kubeconfig for specific cluster - doesn't make a difference). 

I am aware of the security implications. Problem is that I can reach the kubernetes cluster just through SSH tunnel from certain locations (strict firewall rules). I guess insecure-skip-tls-verify should not be tied just to certificate chain verification. 

Or what would be a simple workaround? If I wasn't using SubjectAltName IP address I could perhaps do some "hack" through /etc/hosts on my machine (to make CN match).

Thanks,
Gregor

**Comment by fiksn** [comment]
Yeah, if I could SSH directly to the CoreOS machine running api server I could probably use the insecure port (127.0.0.1:8080).

**Comment by AdoHe** [comment]
I will take a look.

**Comment by rata** [comment]
I think this just got fixed by this commit: https://github.com/kubernetes/kubernetes/commit/c0af96ccc241a9402ceeaafc73c9f57f046a64b9

**Comment by discordianfish** [comment]
I came here wondering if there is a less-insecure flag like --insecure-skip-san-verify which would still validate that the server cert is signed by the trusted CA but ignore SAN IPs. Is that something worth a feature request?

**Comment by liggitt** [comment]
> I came here wondering if there is a less-insecure flag like --insecure-skip-san-verify which would still validate that the server cert is signed by the trusted CA but ignore SAN IPs. Is that something worth a feature request?

I would say no. It's not an option supported by the go http transport, and trusting the signature but not verifying the subject/sans means you are extending your trust beyond the CA to everyone holding a certificate ever issued by the CA.

**Comment by discordianfish** [comment]
@liggitt That's true, I'm was just hoping that most people using 'insecure-skip-tls-verify' would be fine with insecure-skip-san-verify too and much more secure. But yes, possibly not worth it.
