### ISSUE TITLE
Scripts in releases have missing dependencies

### ISSUE THREAD

**Issue by luebken** [kubernetes/kubernetes#21296]
Scripts like `cluster\test-e2e.sh` start other scripts / tests in `hack` but this folder is missing in a release. There is a TODO in the script: https://github.com/kubernetes/kubernetes/blob/master/cluster/test-e2e.sh#L18

Why is this important? As a newbie you download an release because you figured this is a tested package. If something is wrong with your cluster and you try to debug these scripts seems helpful. But than they miss `hack`.

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc
