### ISSUE TITLE
iscsi: Allow multiple portal ips

### ISSUE THREAD

**Issue by tobad357** [kubernetes/kubernetes#21306]
To add proper redundancy to iscsi we would ideally allow for primary and secondary discovery ips. Currently the iscsi volume provider only takes one portal ip which causes issues if that portal goes down.

Suggestion would be to either add a "backup_portal" property or probably better a "portals" property that allows a list of ips. The provider would then go through them one by one and try to login to the iqn provided on each one. If one times out then the others would work.

**Comment by tobad357** [comment]
@saad-ali do you have any preference for the following change
It is quite crucial for us to prevent our pods to go down if the primary portal ip becomes unavailable so I would like to work on this asap

**Comment by saad-ali** [comment]
Sounds good to me. Only thing to keep in mind is backwards compatability. That means leave the existing field as is, just add a optional `backup_portals` field that can be used to list alternate servers to try if `portals` is unavailable.

**Comment by rootfs** [comment]
@tobad357 are you working on this? want to coordinate with you, thanks.

**Comment by tobad357** [comment]
@rootfs Sorry haven't had a chance due to work commitments.
I'm still interested in fixing it but if someone wants to go ahead the please proceed.
I haven't started

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by fortcollins** [comment]
I have a project due in a month or so which requires the support for iSCSI MLPT (multiple LUNs per target). Appreciate if you could make it in 1.5 assuming 1.6 will not be ready by then. If anybody is interested in my use cases, I can provide the details and steps how it works manually.

**Comment by tobad357** [comment]
@fortcollins please outline your setup as I was intending to look at this in the next week or two
Would want to see if I can cover it at the same time

**Comment by humblec** [comment]
@tobad357 @fortcollins The multipath support is added to iscsi plugin. Basically it is multiple TPs for same IQN support which is the very common multipath support in many iscsi setups.

**Comment by ethernetdan** [comment]
Moving to 1.7 because too late for 1.6. Feel free to move back if this is incorrect.

**Comment by fabiand** [comment]
@ethernetdan I think this bug is fixed, as #39928 was merged and provides the multi portal support.
