### ISSUE TITLE
findmnt doesn't work on all distros

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#21303]
I can't run any containers with newest `hyperkube:v1.2.0-alpha.7`. I get the following error:

```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Reason		Message
  ─────────	────────	─────	────			─────────────	──────		───────
  3m		3m		1	{default-scheduler }			Scheduled	Successfully assigned nginx-c2rdu to 127.0.0.1
  3m		1m		11	{kubelet 127.0.0.1}			FailedMount	Unable to mount volumes for pod "nginx-c2rdu_default(8dfd262c-d49e-11e5-bad9-bc305be02f04)": IsLikelyNotMountPoint("/var/lib/kubelet/pods/8dfd262c-d49e-11e5-bad9-bc305be02f04/volumes/kubernetes.io~secret/default-token-eorir"): file does not exist
  3m		1m		11	{kubelet 127.0.0.1}			FailedSync	Error syncing pod, skipping: IsLikelyNotMountPoint("/var/lib/kubelet/pods/8dfd262c-d49e-11e5-bad9-bc305be02f04/volumes/kubernetes.io~secret/default-token-eorir"): file does not exist
```

I'm using docker 1.9.1.

@bryk

**Comment by fgrzadkowski** [comment]
So the problem is on Ubuntu (on debian for example this works). The problematic code is that `findmnt` for a directory which is not a mount behaves differently for different platforms - on debian it returns `/`, on ubuntu it returns error. We expect debian behavior.

@luxas

**Comment by fgrzadkowski** [comment]
It seems it's only broken for older versions of `util-linux` (package with `findmnt`). On Ubuntu 14.04 it broken, on Ubuntu 15.04 it's working.

**Comment by luxas** [comment]
Quite funny, came across this this morning when I tried to fix #18227
I have some fixes for #18227, but I hit this issue instead. I'm using Ubuntu 15.10.
Will research some more... This have to be fixed before `v1.2`

**Comment by fgrzadkowski** [comment]
@luxas Can you post output of the following command: `findmnt --target <some_directory_which_is_not_a_mounpoint>`? I believe that if this returns `/` and exit status is 0 we should be ok.

**Comment by bgrant0607** [comment]
cc @kubernetes/goog-cluster

**Comment by saad-ali** [comment]
cc @kubernetes/rh-storage

**Comment by luxas** [comment]
On Ubuntu 15.10:
```
$ findmnt --target $(pwd)
TARGET SOURCE         FSTYPE OPTIONS
/      /dev/dm-0 ext4   rw,relatime,errors=remount-ro,data=ordered
$ echo $?
0
$ findmnt --version
findmnt from util-linux 2.26.2
```
When I am in a normal folder in under my ´/home/dir`.
The same output from my Raspberry Pi, which runs `HypriotOS` and has `findmnt from util-linux 2.25.2`

Which `findmnt` version do you think isn't working?

**Comment by fgrzadkowski** [comment]
@luxas I have version `2.20.1` and it doesn't work.
