### ISSUE TITLE
Factory forces os.Args[0] to kubectl

### ISSUE THREAD

**Issue by pweil-** [kubernetes/kubernetes#21316]
https://github.com/kubernetes/kubernetes/pull/20035/files#diff-9765b963cad9ecc6ef9416a1f15ded86R478 was introduced that is forcing the `os.Args[0]` to `kubectl` for anything that uses the Factory.  This breaks some of the commands we have in OpenShift, particularly the `rsync` command.

I'm not yet sure what needs to happen with this, perhaps a whitelist or being able to inject the recorder function.  I'll defer to folks who have more cli experience.

@cewong @deads2k @kubernetes/kubectl

**Comment by kargakis** [comment]
recordCommand should be part of the Command method so we could override it.

**Comment by liggitt** [comment]
Also, I would not expect it to mutate the passed in slice

**Comment by liggitt** [comment]
@janetkuo

**Comment by liggitt** [comment]
and use `filepath.Base(args[0])` instead of hard-coding "kubectl"

**Comment by deads2k** [comment]
I see no reason to mutate it at all.  This annotation is already non-portable, tied to env vars you executed from, sensitive to cwd, relies on the current state of a disconnected kubeconfig, exposes sensitive arguments to the entire cluster, and only provides a value already available in your command history.

Why would we bother trying to beautify it at all?  In fact, that beautification probably keeps it from running again on the original user's machine.

**Comment by liggitt** [comment]
> In fact, that beautification probably keeps it from running again on the original user's machine.

that's true

**Comment by bgrant0607** [comment]
As @janetkuo mentioned here: https://github.com/kubernetes/kubernetes/pull/21318#issuecomment-184921702
the command isn't intended to be reproducible. It's a mnemonic.
