### ISSUE TITLE
Reference Pod.Spec.NodeName within a manifest

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/kubernetes#21317]
I need to pipe in the NodeName of a pod as an environment variable at startup of an app. This way I can report the NodeName instead of the container hostname when sending host level metrics to influx.

The downward api looks like a great place to add this type of functionality (would be even better if we could somehow expose all values of the pod in the downward api) but would love to hear if anyone else has a solution before I go and hack up telegraf to get this information from the kube api directly.

**Comment by thockin** [comment]
Downward API is for exactly this

**Comment by justinsb** [comment]
AFAICT, there's no way to get the node _name_ though @thockin .  It is possible to get the hostIP, but not the node name.

**Comment by thockin** [comment]
Sorry, I read it as pod name.  Node name is intentionally omitted.  I would
rather find or make other solutions for looser node coupling.  We should
start with what you're trying to achieve.

**Comment by jchauncey** [comment]
I need to report the node name for host level metrics into influx. Right now telegraf uses the os.Hostname which doesnt make much since when you are running in a container.

**Comment by tnachen** [comment]
I think the ability to get the Node name information is still valuable, as you might need to be able to access more information from the k8s api and read node labels of the node you're on.

**Comment by nhlfr** [comment]
I think that if we are looking for extending downward API with information about nodes, we shouldn't only focus on the name. IMO to keep a consistency and to avoid more feature requests in future, we may cover all the information we have currently about pods, so:

* environment variables
  * node's name
  * node's namespace
  * node's IP address
* volume
  * node's labels
  * node's annotations

Of course in case of volumes, we have to choose some other filenames, to my proposition is to place these mounts in i.e. _/etc/host_labels_ and _/etc/host_annotations_.

**Comment by nhlfr** [comment]
FYI, I am working on this and I'll propose PR soon.

**Comment by ghodss** [comment]
@nhlfr That would be great - we currently have a need for node name in the pod because our log tailer that generates metrics is containerized in the pod, and it needs access to the node name to annotate the metrics with it.

**Comment by ghodss** [comment]
@thockin Can you think of another way to satisfy that use case?

**Comment by jchauncey** [comment]
Sam check out github.com/deis/monitor and look at he telegraf dir at the
start script and it shows how to get the node name using curl

**Comment by ghodss** [comment]
Do you need something special in your policy file JSON to allow all pod service account tokens to read their own specs? Or is that allowed by default?

**Comment by jchauncey** [comment]
Not that I know of

**Comment by ghodss** [comment]
@jchauncey By default ABAC will deny the kind of curl you make at https://github.com/deis/monitor/blob/master/telegraf/rootfs/start-telegraf#L8, so that wouldn't work for us. I generally wouldn't want to let every pod query its entire spec either, in case of compromise of the pod. Though I don't think there's even a way to currently say "let any pod's service account only query itself," anyways.

**Comment by nhlfr** [comment]
This pull request introduces node labels and annotations to volume downward API.

@ghodss it **doesn't** include the hostname (as an environment variable) yet, but no worries, I'm working on that too and will raise an another pull request.

**Comment by nhlfr** [comment]
The PR #26160 is introducing node name in environment variables.

To sum it up, both PR-s are introducing the following downward API for node information:

* environment variables
  * node's name
  * node's IP address
* volume
  * node's labels
  * node's annotations

**Comment by thockin** [comment]
Merged in 1.4!

**Comment by mingfang** [comment]
Is this in v1.4?
I'm getting this error

```
error validating data: found invalid field nodeFieldRef for v1.EnvVarSource;
```

my version
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mingfang** [comment]
nvm the node name is available like this
```
          - name: NODENAME
             valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
```

**Comment by brandoncole** [comment]
A colleague just pointed this out to me, big change in previous policy.  Could we get http://kubernetes.io/docs/user-guide/downward-api/ updated with this feature so it's more discoverable?

```
valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
```
