### ISSUE TITLE
Fix node e2e issues introduced by isReadOnly

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#21320]

**Comment by dchen1107** [comment]
@pwittrock logs? link to failed builds? Thanks!

**Comment by pwittrock** [comment]
Sorry about that:

For context see: https://github.com/kubernetes/kubernetes/pull/20782

Looks like the issue is a compile error that wasn't checked:
Looks like this broke the node e2e test suite:

09:00:58 I0216 09:00:58.908726 31269 run_e2e.go:103] Failure Finished Host e2e-node-coreos-beta.c.kubernetes-jenkins.internal Test Suite Failed to compile e2e_node:
09:00:58 
09:00:58 # k8s.io/kubernetes/test/e2e_node
09:00:58 test/e2e_node/kubelet_test.go:107: undefined: isReadOnly

**Comment by pwittrock** [comment]
Fixed in #22215
