### ISSUE TITLE
Write a Service e2e to validate session affinity

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#21329]
spinoff from https://github.com/kubernetes/kubernetes/issues/10268

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by cmluciano** [comment]
Can anyone confirm if we added these?

I still see the [TODO](https://github.com/kubernetes/kubernetes/blob/bcccbc3d0b28171d383eda5eac16b487bcda9cf6/test/e2e/networking.go#L193) but I thought this went GA.

cc @MrHohn

**Comment by bowei** [comment]
Session affinity does exist, but it looks like there is no e2e test.

**Comment by cmluciano** [comment]
/assign

will work on this for 1.8

**Comment by cmluciano** [comment]
dup #31712
