### ISSUE TITLE
AllowUnconditionalUpdate is very frightening

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#21330]
We provide an option to violate the semantics of our API, and on top of that, it is the default if you don't pass a resourceVersion. This has the ability to do very bad things.

If we want to encourage people to start writing their own controllers on top of kubernetes, we shouldn't make it so easy for them to shoot themselves in the face. Is there a reason this option exists?

**Comment by cjcullen** [comment]
@alex-mohr @lavalamp @bgrant0607

**Comment by bprashanth** [comment]
I think this matches etcd CAS with prevIndex=0 (i.e that's just a set operation)

**Comment by lavalamp** [comment]
Yes, it's a set, but that doesn't make it safe. If you read -> change (and delete RV) -> write, you blow away anyone else's intermediate changes instead of getting a conflict.

@smarterclayton may recall why we allow this. I imagine there's some old client we're scared of breaking, or some resource that we want to avoid conflicts on or something.

To make it safer, we could require a header/query parameter e.g. `&unsafeSet=true` or something.

I would prefer to remove it completely, but I lost that argument last time it came up, and I forget why exactly.

**Comment by nikhiljindal** [comment]
I had added AllowUnconditionalUpdate in https://github.com/kubernetes/kubernetes/pull/10074.
I dont see any issue referred by the PR, but @bgrant0607 pointed in the PR that our documentation was already assuming that we were doing that: https://github.com/kubernetes/kubernetes/pull/10074#issuecomment-114963953

**Comment by bgrant0607** [comment]
At this point, changing this would break API compatibility. There would have to be a better motivation than "this is scary".

I also disagree with the characterization that this "violates the semantics of the API". It's part of the semantics of the API.

IIRC, prior to PR @nikhiljindal cited, the behavior was just broken in this scenario.

One potential use is to circumvent a DoS attack.

In practice, I'd guess some people implicitly take advantage of this when doing `kubectl replace`. Anyway, it's up to us to decide how `kubectl replace` interprets the lack of a resourceVersion in the user's config.

This is admittedly more useful with PATCH than with PUT.

**Comment by cjcullen** [comment]
(okay, "violates the semantics of the API" may be a little hyperbolic :smiley: )

How would you use this to circumvent a DoS attack? If you built your client to fallback on unconditional update  in times of high load, you may have sidestepped DoS while self-inflicting much worse.

I think there are probably good reasons to have this option if you know what you're doing and you need it (e.g. PATCH on a heartbeat-type field), but it's scary that it is so easy to do.

**Comment by smarterclayton** [comment]
I agree with Dan, that the affordance should be there to make sure this is
exactly what you want (a special resource version, rather than the absence
of one).  We should put that on the V2 list.

**Comment by ZP-AlwaysWin** [comment]
But now that some of the resource objects built in kubernetes can be updated unconditionally, why can't we update the custom CRD update rules?


CRD is widely used nowadays. Some CRDs do have the need for mandatory updates. Otherwise, we need to retry on conflict all the time on the client side.
