### ISSUE TITLE
Kubelet does not notice pod has completed

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#21336]
## Problem

Pod that should run quickly to completion almost always does, but at least one time, it did not, causing a test flake (#21169). 
## Symptoms

We see pod get to the point of pulling its image, according to events on apiserver, but we don't ever see "Created" or "Started" events, until test times out after 15 minutes.  Kubelet logs show ContainerStarted even according to PLEG, and shows volumes being cleaned for the pod again and again.  
## Logs

I've attached a kubelet log from an e2e test: [bad-kubelet.txt](https://github.com/kubernetes/kubernetes/files/133194/bad-kubelet.txt)

The pod of interest is called `fail-once-local-r6hqn` in namespace `e2e-tests-job-r1z3y`.

I've also attached a version of that log that just includes lines from the pod I am interested in (lines matching its pod name, uid, or docker container id):
[bad-kubelet-filtered.txt](https://github.com/kubernetes/kubernetes/files/133210/bad-kubelet-filtered.txt)
## Discussion

A similar pattern occured 3 times on a single node in a single e2e run, and not at all on the other nodes.  See #21169.  So, it might be a bad node or bad docker.  However, other many other containers ran successfully during the e2e test time frame.

The pod's command line is `if [[ -r /data/foo ]] ; then exit 0 ; else touch /data/foo ; exit 1 ; fi`.  This command will exit quickly, and so there could be a race where docker or kubelet doesn't notice that the container exited because it exited so fast.  However, this has to be a rare race because the test passes many times.

The pod gets as far as the `ContainerStarted` state according to PLEG.

```
I0212 15:08:11.894177    3890 kubelet.go:2324] SyncLoop (PLEG): "fail-once-local-r6hqn_e2e-tests-job-r1z3y(6e23f2c1-d19a-11e5-8e8a-42010af00002)", event: &pleg.PodLifecycleEvent{ID:"6e23f2c1-d19a-11e5-8e8a-42010af00002", Type:"ContainerStarted", Data:"5032a5cb8b882e6eb82ce7d8abba525c4bc9ce53c47dc342567de0d0b3712834"}
```

But there are no "Created" or "Started" events on the APIserver for the pod.   That seems odd.

After the `ContainerStarted` event from PLEG, the kubelet logs show kubelet considering unmountin the Pod's volumes every few second for the next 15 minutes, like this:

```
I0212 15:08:12.648445    3890 volumes.go:234] Making a volume.Cleaner for volume kubernetes.io~empty-dir/data of pod 6e23f2c1-d19a-11e5-8e8a-42010af00002
I0212 15:08:12.648493    3890 volumes.go:316] Used volume plugin "kubernetes.io/empty-dir" to unmount 6e23f2c1-d19a-11e5-8e8a-42010af00002/kubernetes.io~empty-dir
I0212 15:08:12.648525    3890 volumes.go:234] Making a volume.Cleaner for volume kubernetes.io~secret/default-token-kp0b0 of pod 6e23f2c1-d19a-11e5-8e8a-42010af00002
I0212 15:08:12.648561    3890 volumes.go:316] Used volume plugin "kubernetes.io/secret" to unmount 6e23f2c1-d19a-11e5-8e8a-42010af00002/kubernetes.io~secret
```

These log lines appear to be coming from getPodVolumesFromDisk.  I think these lines just mean that the Pod's volumes are still on disk and that they are still in use by a container.

**Comment by yujuhong** [comment]
This is the timeline:
 1. kubelet receives the pod.
 2. kubelet starts syncing the pod and create a pod infra container 5032a5cb8b8 (pleg reports the container started).
 3. kubelet starts pulling image for pod (in the per-pod goroutine)
 4. test timed out and deleted the pod.
 5. kubelet observed that the pod has been deleted and cleaned up the volumes.
 6. kubelet finally pulled down the image.
 7. kubelet tries to start the pod but the volumes have been cleaned up.

The real cause of the failure is that the image pulling took too long for unknown reasons (#21029)

**Comment by yujuhong** [comment]
Currently, kubelet doesn't have the ability to cancel a in-progress sync (by a per-pod goroutine) until the sync ends. This is tied with the fact that we have a huge `SyncPod` function which does millions of things in one sync.
