### ISSUE TITLE
RFE 1.3 + : Integration with traditional monitoring systems.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#21333]
In order to determine node health @ scale we would likely want integration with traditional scale out monitoring systems, e.g. - ganglia or nagios, which is outside of the kubernetes control plane. 

/cc @kubernetes/sig-node @jeremyeder @kubernetes/rh-cluster-infra @kubernetes/sig-scalability

**Comment by jeremyeder** [comment]
via what...snmp? You want a kubernetes mib? Incidentally I think that would be freaking awesome.

**Comment by timothysc** [comment]
Integration is basically to give the other system a liveness check for k8s.

**Comment by timothysc** [comment]
Folks are doing this outside via daemonsets, closing.
