### ISSUE TITLE
`GetFirstPod` infinite loops when pod never appears

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#21334]
If a pod is never created (think quota rejection), then commands that end up in `GetFirstPod` loop forever waiting for a pod that is never coming.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L534

@kubernetes/kubectl

**Comment by smarterclayton** [comment]
I have a set of patches to add a utility "wait for pod X over watch" that is like wait.Poll (thus, bounded).  I don't think we'll get to that in 1.3 but I want to refactor everything to stop doing their own things and use that.

**Comment by deads2k** [comment]
I think I want

```go
func WaitForResource(Watcher, resourceVersion, timeout, matchesFunc func(runtime.Object) bool) (runtime.Object, error)
```

**Comment by smarterclayton** [comment]
See the debug pr
