### ISSUE TITLE
kubectl: provide a way to delete cached swagger schema

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#21353]
A very common issue people report on slack channel is that kubectl does not work with alpha resources (deployment and daemonsets) even after they have enabled the resources on master.
The reason is that kubectl has a cache of swagger spec, which needs to be deleted.

Right now users have to manually delete the cached spec from `~/.kube/schema/`.

We need to provide a better way to fix that.

Some user complaints: https://github.com/kubernetes/kubernetes/issues/21042 and https://github.com/kubernetes/kubernetes/issues/19515

**Comment by AdoHe** [comment]
@nikhiljindal I will take a look into this.

**Comment by AdoHe** [comment]
@nikhiljindal how about add an extra flag to control this behavior? for example `kubectl create --force-update` this will always refresh the the cache of swagger spec?

**Comment by nikhiljindal** [comment]
We use --force in kubectl replace and drain as well.

cc @bgrant0607 and @kubernetes/kubectl

**Comment by deads2k** [comment]
Why not try to handle this by recognizing a failure due to missing swagger information and either removing the file (easy) or asking the server for the new one using an `If-Modified-Since` header?

I'd rather not have to specify a flag for a case that should be fully reconcilable automatically.

@smarterclayton

**Comment by smarterclayton** [comment]
I like David's suggestion a bit better - I don't like that users have to
understand that our swagger caching doesn't work well.  I think that's the
core issue, so we should fix that cache to not fail.

**Comment by bgrant0607** [comment]
Do we record the Kubernetes release version in the swagger cache? If we did, we could invalidate it if the server version changed.

**Comment by bgrant0607** [comment]
I would rather not add a flag. That wouldn't reduce the number of user questions at all.

**Comment by nikhiljindal** [comment]
Yes we store the server version.
For ex, running `$ ls ~/.kube/schema/` gives me:

```
v1.2.0-alpha.6.499+10f7985dfba8a2-dirty  v1.2.0-alpha.7.621+c70c7fde4d400a-dirty  v1.2.0-alpha.7.989+b23d990467ea10-dirty
```

The problem happens when users change the runtime config flag on their servers.

**Comment by lavalamp** [comment]
* The runtime-config setting needs to make it into the file's name (or hash or whatever we're using).
* as a temporary hack, kubectl could re-get the file if validation fails for the type not found reason.

**Comment by nikhiljindal** [comment]
ok, that sounds good to me. Lets re-fetch the spec when validation fails for type not found.

@AdoHe You want to send a PR for that?

Marking this as 1.2 P2 as per https://github.com/kubernetes/kubernetes/issues/21042

**Comment by AdoHe** [comment]
@nikhiljindal I will send a PR to fix this.

**Comment by nikhiljindal** [comment]
Any progress @AdoHe?
This is a 1.2 issue.
Would be great if we can get this fixed asap.

**Comment by AdoHe** [comment]
@nikhiljindal I will open a PR this weekend.

**Comment by AdoHe** [comment]
@nikhiljindal First I use the latest master branch code to test this:
```
./hack/local-up-cluster.sh
./cluster/kubectl.sh create -f docs/user-guide/deployment.yaml
```
The result is ok, I can create a deployment named `nginx-deployment` even though I just have `v1.1.2` scheam under `~/.kube/schema` before I create the deployment. And I just noticed that after I run this command, a new schema version will be downloaded into the schema directory.

**Comment by nikhiljindal** [comment]
deployments is now enabled by default on HEAD.

To test it, you can first bring up a server with deployments turned off and use kubectl so that it fetches a schema without deployments.
Then restart the server with deployments turned on and then you will see this issue.

**Comment by AdoHe** [comment]
I did another test under kubernetes 1.1.7
First bring up a cluster with deployment turned off:
```
./hack/local-up-cluster.sh
```
Then use kubectl to verify deployment disable:
```
$ ./cluster/kubectl.sh get deployments
Unable to list "deployments": the server could not find the requested resource
```
Also kubectl will fetch `v1.1.7` version schema and put it in `/tmp/kubectl.schema/`.
Next I bring up a cluster with deployment turned on:
```
RUNTIME_CONFIG=extensions/v1beta1/deployments=true ./hack/local-up-cluster.sh
```
And the result of kubectl:
```
$ ./cluster/kubectl.sh get deployments
NAME      UPDATEDREPLICAS   AGE
$ ./cluster/kubectl.sh create -f examples/extensions/deployment.yaml
deployment "nginx-deployment" created
```
It seems it's ok, the schema cache dir get updated if you check the `/tmp/kubectl.schema/`.
Besides if you do the same test under kubernetes 1.1.4, you will fail.

**Comment by nikhiljindal** [comment]
cc @brendandburns

**Comment by lavalamp** [comment]
What's the PR that fixes this?

**Comment by AdoHe** [comment]
@nikhiljindal I did test again with kubernetes 1.1.4&1.1.7, I can create deployment. So could you provide your test environment that I can reproduce this issue?

**Comment by nikhiljindal** [comment]
In both the referred issues #21042 and #19515, users tried it on HEAD when deployments was not enabled by default.

I will try it once more and let you know how it goes.

**Comment by nikhiljindal** [comment]
I was able to repro this with the following steps on HEAD:

```
$ RUNTIME_CONFIG=extensions/v1beta1/deployments=false ./hack/local-up-cluster.sh
$ ./cluster/kubectl.sh create -f docs/user-guide/deployment.yaml
```
This gave the expected error:
```
error validating "docs/user-guide/deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false
```
Also, I could see that there was `apis/extensions/v1beta1/schema.json` in `~/.kube/schema`.

Then, I restarted the server with deployments enabled:
```
$ ./hack/local-up-cluster.sh
```
Now, I still got the validation error, when I tried to create the deployment:
```
$ ./cluster/kubectl.sh create -f docs/user-guide/deployment.yaml
error validating "docs/user-guide/deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false
```
Also, I could see that there was no difference in `~/.kube/schema`.

**Comment by AdoHe** [comment]
@nikhiljindal I have fixed this on my local, will open a PR asap.

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/22420
