### ISSUE TITLE
e2e test of auth

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#2136]
Once authentication and authorization are firmly in place, we'll need to make sure that some later change does not inadvertently disable it.   Ideally, that would be an e2e test for GCE and maybe some other cloud providers that uses the actual binaries and network settings and defaults and salt config and all that jazz.  Exhaustive testing should go in unit tests and test/integration/auth_test.go  But a basic "alice can GET/PUT a pod and Bob can't" e2e test is needed.

**Comment by liggitt** [comment]
if we assume service accounts are not privileged by default, and that the cluster under test is using RBAC, we can easily add this test. I know those assumptions have not always been valid in the past

**Comment by liggitt** [comment]
e2e now includes service account tests, node authorization tests, and pod security policy tests, all of which exercise authentication and authorization paths
