### ISSUE TITLE
AWS docs: update CoreOS link?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21387]
Our docs say this:

> A contributed [example](coreos/coreos_multinode_cluster.md) allows you to setup a Kubernetes cluster based on [CoreOS](http://www.coreos.com), using
EC2 with user data (cloud-config).

I think though that example is out of date (?).  We should make sure to point it to the right place.

**Comment by justinsb** [comment]
cc @colhom

**Comment by colhom** [comment]
@robszumski where should this point?

**Comment by robszumski** [comment]
The official CoreOS guides are documented/linked here: https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos.md#getting-started-on-coreos

The decision made a few months ago was to leave the previous community content, but should we revisit that?

**Comment by robszumski** [comment]
Side note, a link to our AWS tool/guide probably needs to be there as well

**Comment by robszumski** [comment]
@justinsb What file contains that sentence?

**Comment by justinsb** [comment]
@robszumski `docs/getting-started-guides/aws.md`
