### ISSUE TITLE
unit flake: Cloning into '/go/src/github.com/jstemmer/go-junit-report'...

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#21380]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/21264/kubernetes-pull-test-unit-integration/14730/build-log.txt

```
# cd .; git clone https://github.com/jstemmer/go-junit-report /go/src/github.com/jstemmer/go-junit-report
Cloning into '/go/src/github.com/jstemmer/go-junit-report'...
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
```

cc @kubernetes/goog-testing

**Comment by spxtr** [comment]
I saw this before when trying to check out a large repository, #18960, except there we had `result=18`.

**Comment by lavalamp** [comment]
@ixdy to fix or find an owner?

**Comment by fejta** [comment]
Do we have stats about cpu usage? When we had networking flakes in jenkins historically it was often due to cpu starvation.

**Comment by ixdy** [comment]
Has this happened more than once?

Due to Jenkins upgrades last night, we may have been using a bit more CPU and GitHub traffic than normal due to rebuilding Docker images etc. If it only happened once I'm inclined to just close this issue.
