### ISSUE TITLE
kubectl create -f ./quota.json invalid character '}' looking for beginning of object key string

### ISSUE THREAD

**Issue by tvalasek** [kubernetes/kubernetes#21385]
I'm following step by step tutorial on how to create resource quotas per namespace (http://kubernetes.io/v1.1/docs/admin/resource-quota.html)

quota.json looks like this:

`{
  "apiVersion": "v1",
  "kind": "ResourceQuota",
  "metadata": {
    "name": "quota",
  },
  "spec": {
    "hard": {
      "memory": "1Gi",
      "cpu": "20",
      "pods": "10",
      "services": "5",
      "replicationcontrollers":"20",
      "resourcequotas":"1",
    },
  }
`
when i'm about to create quota it fails with:

`kubectl create -f ./quota.json --namespace=prod
invalid character '}' looking for beginning of object key string
`
Namespace "prod" exists:

`kubectl get namespace
NAME          LABELS             STATUS    AGE
default       <none>             Active    26d
dev           name=development   Active    8d
kube-system   <none>             Active    26d
prod          name=production    Active    8d
`

kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}

**Comment by justinsb** [comment]
Those trailing commas are wrong.  quota.json should look like:


```
{
  "apiVersion": "v1",
  "kind": "ResourceQuota",
  "metadata": {
    "name": "quota"
  },
  "spec": {             
    "hard": {           
      "memory": "1Gi",  
      "cpu": "20",      
      "pods": "10",     
      "services": "5",  
      "replicationcontrollers":"20",
      "resourcequotas":"1"      
    }
  }
}
```

I'll submit a docs patch

**Comment by tvalasek** [comment]
sweet. ta. That seem to do the trick:

kubectl create -f ./quota.json --namespace=prod
resourcequota "quota" created

**Comment by justinsb** [comment]
I'm going to reopen until the PR which fixes this merges, when it should autoclose...

**Comment by ElishaKay** [comment]
I'm following this tutorial on installing percona with kubectl, and I'm getting a similar error:

https://www.percona.com/blog/2016/12/21/installing-percona-monitoring-management-google-container-engine-kubernetes/#comment-10968714

When I run:

kubectl create -f pmm-server-init.json

I get:

error: json: line 1: invalid character ‘Â’ looking for beginning of object key string
