### ISSUE TITLE
AWS: Make sure we still run `apt-get dist-upgrade` on boot

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21382]
This means that we won't rely on our image (AMI) having all the latest security enhancements.  Building a new image is an optimization to prevent reboots etc.

We should install some form of safety valve just in case Debian/Ubuntu publishes a bad package.

cc @zmerlynn @brendandburns

**Comment by justinsb** [comment]
See comments in https://github.com/kubernetes/kubernetes/pull/21226#issuecomment-185229449 for background.

**Comment by davidopp** [comment]
ping

**Comment by justinsb** [comment]
This is PR #21471

**Comment by davidopp** [comment]
#21471 has been merged, so closing.
