### ISSUE TITLE
GKE Monitoring multiple filters

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#21394]
When creating dashboards, it seems we're only allowed to set one single filter. It would be nice to be able to set multiple (AND) filters, e.g. `app=myapp, namespace=stage`.

**Comment by dchen1107** [comment]
cc/ @a-robinson

**Comment by alex-mohr** [comment]
Is this a v1.2 release issue?

**Comment by a-robinson** [comment]
Not really. It needs to be fixed in Stackdriver, not Kubernetes. cc @katzj

Also, @pires , it's not quite as straightforward, but in the meantime you can create a Group with multiple filters, then filter by Group in your dashboard graph.

**Comment by pires** [comment]
@a-robinson oh why didn't I think of that? Thank you!

**Comment by devth** [comment]
@a-robinson great suggestion, but it looks like Groups (or any other Stackdriver resource) don't have a namespace filter. e.g. I'd like to to create a `prod` group filtered to `namespace=prod`.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gke
since we lack a sig-gcp at the moment
