### ISSUE TITLE
Container manifest should allow specifying interface to listen on

### ISSUE THREAD

**Issue by nikhilk** [kubernetes/kubernetes#2139]
The -p argument to 'docker run' allows specifying the interface on which a port will be published:
  -p, --publish=[]           Publish a container's port to the host
format: ip:hostPort:containerPort | ip::containerPort | hostPort:containerPort | containerPort

However, the container VM manifest only allows specifying hostPort and containerPort:

containers[].ports[] -- Ports to expose from the container.  _All of these are exposed out through the public interface of the VM._
containers[].ports[].containerPort
containers[].ports[].hostPort

https://cloud.google.com/compute/docs/containers/container_vms

This is useful for implementing defense-in-depth, and as such an important feature. Specifically it would allow opening a port that is not accessible off-machine when that is all that is needed.

In our scenario, the only intended client of that port is the local SSH daemon. Securing the port through just a firewall setting has been deemed as insufficient, as opening that port inadvertently opens up a large surface area of capabilities.

**Comment by wikiwi** [comment]
+1 I just ran into this problem. It would make things easier if we can specify the interface.

**Comment by thockin** [comment]
Can you explain why?  The same arguments apply - specifying an interface is
an even deeper level of coupling that we should not enable without serious
use-cases.

**Comment by smarterclayton** [comment]
This is not exactly the published issue, but we are definitely getting folks with standard multi network setups who want to have pods listen on distinct interfaces (which correspond to existing network infrastructure choices, like control plane vs storage plane vs public plane).  I had been leaning towards allowing a network plugin to solve this use case, but it would have to involve some level of setup in the cluster.  Then the network plugin can look at annotations or labels.

**Comment by thockin** [comment]
For bridging to physical networks, I think we can consider some first class
support for Networks.  I think that is a real use case.

I am less sure aboyt host ports, or at least it shouldn't be per-pod but a
config of the kubelet.  But I think we need some real explorations before
we jump on this.

**Comment by xiangpengzhao** [comment]
As per the discussion in the issue, this can be a use case of multiple-networks.

@nikhilk Would you please join the mailing list and post your use case there?
 see: https://groups.google.com/forum/#!topic/kubernetes-sig-network/8nDSQ2hF40w

**Comment by caseydavenport** [comment]
Given the age of the conversation here I think we should close this and re-open / create a new issue if there are more recent requests for this. Will close in a few days if there are no objections.

/assign
