### ISSUE TITLE
NodePort services not proxied correctly in Userspace Kube-Proxy

### ISSUE THREAD

**Issue by caleblloyd** [kubernetes/kubernetes#21396]
I had previously been successfully using NodePort to connect my own Load Balancer, but after upgrading to 1.1.7, I can only access services through NodePort if a pod is running on the Node.

    kind: Service
    apiVersion: v1
    metadata:
      name: router
    spec:
      type: NodePort
      ports:
        - name: http
          protocol: TCP
          port: 80
          nodePort: 30080
        - name: https
          protocol: TCP
          port: 443
          nodePort: 30443
      selector:
        role: router

I have 2 nodes in my cluster, 10.240.0.7 and 10.240.0.9.  I have 1 router pod running on the 10.240.0.7 Node.

When I curl 10.240.0.7:30443 from any machine inside my firewall, I get a valid response.  When I curl 10.240.0.9:30443 from any machine inside my firewall, the connection hangs and never completes.

In previous versions, nodes that didn't have the pod running on it  forwarded the connection to a node that did.

**Comment by caleblloyd** [comment]
This seems to be a problem in the kube-proxy with --proxy-mode=userspace (the default mode).  When I switch it to --proxy-mode=iptables, it works as expected

**Comment by AdoHe** [comment]
@caleblloyd I will confirm this.

**Comment by caleblloyd** [comment]
@AdoHe yes, I have been running like this since 0.19.  I don't know when it stopped working specifically, but it doesn't work in the userspace Kube-Proxy in 1.1.7 if there is no pod for the service on the node.  I'm observing this behavior on 2 separate GKE clusters running 1.1.7.

**Comment by AdoHe** [comment]
@thockin can you confirm this? I think the default behavior is node has no pod running this service should redirect the traffic to node that did.

**Comment by caleblloyd** [comment]
@AdoHe @thockin anyone had time to look into this?  Seems like a pretty big problem unless the next minor release is going to default to using the IP Tables KubeProxy instead of the Userspace KubeProxy.

**Comment by bgrant0607** [comment]
@caleblloyd Yes, we are expecting to default to IP tables in 1.2.

cc @kubernetes/sig-network

**Comment by umiyosh** [comment]
Is there workaround when I apply the minor release v1.2?

**Comment by thockin** [comment]
Is this still an issue?  I'm going to close it for inactivity, but if it is real and reproduces on 1.2.5 or 1.3.0, please reopen.

**Comment by Dacode45** [comment]
I'm having the same issue. The connection hangs.
