### ISSUE TITLE
unversioned.Time#UnmarshalJSON should leave time in UTC

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#21402]
It currently converts to local time, but should remain as close to the wire-format as possible.

Anywhere we display time and want to show local time should be ensuring conversion to local time at point of output.

**Comment by smarterclayton** [comment]
Ugh, I agree.  I just hit this.  It's dumb.

**Comment by ironcladlou** [comment]
As an example of a practical implication, I discovered while working on https://github.com/kubernetes/kubernetes/pull/48065 that `Unstructured` method impls for `Object` cause time fields to be stored in the struct as UTC but retrieved as local times.
