### ISSUE TITLE
Handle errors in namespace controller sync

### ISSUE THREAD

**Issue by pweil-** [kubernetes/kubernetes#21406]
If the namespace controller gets an error when doing a sync and the error is not a `contentRemainingError` error the error will not be handled.

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/namespace/namespace_controller.go#L112-L113

Ran in to this when we found https://github.com/kubernetes/kubernetes/pull/21340.   When deleting a namespace it received a `NotFound` error that wasn't reported anywhere and the namespace stuck in `Terminating` because a finalizer was left.

**Comment by pweil-** [comment]
@liggitt

**Comment by liggitt** [comment]
Other things noticed in the namespace controller:
- need a crash handler in https://github.com/kubernetes/kubernetes/blob/17325ef6ef61918d49a28d615c717bccec5b5a71/pkg/controller/namespace/namespace_controller.go#L115
- sweep https://github.com/kubernetes/kubernetes/blob/17325ef6ef61918d49a28d615c717bccec5b5a71/pkg/controller/namespace/namespace_controller_utils.go#L198 for all error return cases and determine whether `contentRemainingError` should be returned
- determine what to do with non-`contentRemainingError` errors at https://github.com/kubernetes/kubernetes/blob/17325ef6ef61918d49a28d615c717bccec5b5a71/pkg/controller/namespace/namespace_controller.go#L113 ... I think that currently it just hangs termination of that namespace until a resync

**Comment by derekwaynecarr** [comment]
I will take a look.  Thanks for the heads up.
