### ISSUE TITLE
e2e-tests.md doc for local testing is broken

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/kubernetes#21414]
Documentation for locally testing end-to-end tests [here](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#local-clusters) is broken:

Running specific tests should read:
```sh
$ go run hack/e2e.go -v --test --test_args="--host=http://127.0.0.1:8080 --ginkgo.focus=Secrets"
```

Furthermore, after setting up a local cluster, setting `KUBECONFIG` as in this guide, then running the above command, it still thinks I'm trying to use GCE.

**Comment by yifan-gu** [comment]
cc @euank @yifan-gu @sjpotter 
I think if we can running some e2e tests on local, it would be super helpful for us to debug.

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-testing

**Comment by asalkeld** [comment]
I think my PR fixed this: https://github.com/kubernetes/kubernetes/commit/032ef61c3daccb05e9674d5b53c65c30516fd770

Note: this #28469 should also make it a bit easier (so you don't need the --host)

**Comment by ixdy** [comment]
@stevekuznetsov is this fixed?

**Comment by stevekuznetsov** [comment]
The changes linked above seem to fix my issues, but I reported them seven months ago so I'm not sure if there's been UI drift since then. I'll close this and open a new issue if I run into anything next time I execute E2E.
