### ISSUE TITLE
In HPA metrics client check if all pods and their containers were running long enough  

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#21425]

**Comment by mwielgus** [comment]
cc: @piosz @fgrzadkowski

**Comment by piosz** [comment]
@MaciekPytel for triage

**Comment by MaciekPytel** [comment]
I probably won't be able to properly look into this before 1.10, but this is something that should be addressed and I'm planning to get to it as soon as we close features for 1.10. 

/remove-lifecycle rotten
