### ISSUE TITLE
Issue and PR templates

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#21437]
https://github.com/blog/2111-issue-and-pull-request-templates

cc @eparis @dchen1107

**Comment by dchen1107** [comment]
Super! After resolving all 1.2 release related issue, I will attack this if no one already pick up. :-)

**Comment by eparis** [comment]
I think @derekwaynecarr had some thoughts....

**Comment by thockin** [comment]
this is the best news I have heard all week.

**Comment by magicwang-cn** [comment]
@kubernetes/huawei

**Comment by david-mcmahon** [comment]
See also #23743

**Comment by bgrant0607** [comment]
We should update our contributing guidelines, split it into issues vs. PRs, inline the critical content into the templates, and link to the rest:
https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md
