### ISSUE TITLE
Consider pre-pulling images in e2es

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#21449]
This doesn't look like a horrible list, and honestly 90% of our images are just [pause, nginx, busybox, hostexec, netexec].

```
18:21:38-beeps~/goproj/src/k8s.io/kubernetes/test/e2e] $ grep -iroh "gcr.io/.*" | awk -F "/" '{print $3}' | sed -e "s/[,\")}]//g" | sort | uniq 
busybox:1.24
dnsutils
eptest:0.1
fakegitserver:0.1
gb-redisslave:v1
hostexec:1.2
jessie-dnsutils
liveness
mounttest:0.2
mounttest:0.5
mounttest:0.6
mounttest-user:0.3
netexec:1.4
nettest:1.7
nettest: + version
nginx:1.7.9
n-way-http:1.0
pause:2.0
pause:2.0 podLabels
porter:cd5cb5791ebaa8641955f0e8c2a9bed669b1eaab
portforwardtester:1.0
resource_consumer:beta2
serve_hostname:1.1
servicelb:0.1
test-webserver
ubuntu:14.04
update-demo:kitten
update-demo:nautilus
volume-ceph
volume-gluster
volume-iscsi
volume-nfs
volume-rbd
```

Feels like we're wasting time hunting issues like https://github.com/kubernetes/kubernetes/issues/21029 and https://github.com/kubernetes/kubernetes/issues/20550. We can employ other means to test image pulling? @kubernetes/goog-testing

**Comment by yujuhong** [comment]
Note that we still need to tag the images properly (#20836) unless we change the image pull setting.
