### ISSUE TITLE
Multiple nodes have the same podCIDR

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#21458]
While debugging enormous cluster failures, we found that multiple nodes have the same podCIDR

    wojtekt@jenkins-master:~$ sudo kubectl --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-enormous-cluster/workspace/.kube/config get nodes -o json | grep podCIDR | sort | wc -l
    1000
    wojtekt@jenkins-master:~$ sudo kubectl --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-enormous-cluster/workspace/.kube/config get nodes -o json | grep podCIDR | sort | uniq | wc -l 
    995

What is interesing if we look into nodes sharing podCIDR, they are all ready.

@kubernetes/goog-node @kubernetes/goog-control-plane

**Comment by gmarek** [comment]
Things fixed itself before I was able to find a cause.

**Comment by gmarek** [comment]
Reopen if happens again.
