### ISSUE TITLE
k8s cluster (pull images from private registry error)

### ISSUE THREAD

**Issue by Toplife** [kubernetes/kubernetes#21452]
Hi,
Error message: image pull failed for xxxxxx/app/ctcrawler:latest, this may be because there are no credentials on this request.  details: (Authentication is required.)
How to fix it?
waiting answer online
Thanks a lot....

**Comment by Toplife** [comment]
pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ctcrawler
spec:
  containers:
    - name: ctcrawler
      image: xxxxxx/app/ctcrawler:latest
  imagePullSecrets:
    - name: test-secret

secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  data-1: {$mySecret}
type: kubernetes.io/dockerconfigjson

**Comment by pwittrock** [comment]
@Toplife Please post your question to [http://stackoverflow.com/search?tab=newest&q=kubernetes](StackOverflow).  We are trying to consolidate all user support questions in that forum.  Thanks.

**Comment by Toplife** [comment]
@pwittrock sames this link http://stackoverflow.com/search?tab=newest&q=kubernetes can not working...
