### ISSUE TITLE
Have DaemonSet controller use predicates.GeneralPredicates

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#21454]
Once #20204 is submitted, we should have the DaemonSet controller use predicates.GeneralPredicates. Then we won't have to worry about the rules getting out of sync anymore.

Assigned to @HaiyangDING 

cc/ @mikedanese

**Comment by HaiyangDING** [comment]
Thanks for filing up a new issue. This should be part of #20204, but I just chose not to implement in it for the sake of simplicity. Anyway, I will do this in a follow up PR once #20204 accepted.

**Comment by mikedanese** [comment]
We should also move kubelet to predicates.GeneralPredicates

**Comment by davidopp** [comment]
> We should also move kubelet to predicates.GeneralPredicates

That's in #20204, see changes to kubelet.go

**Comment by davidopp** [comment]
cc/ @madhusudancs @bgrant0607
