### ISSUE TITLE
kubelet: add a route to periodically check health state of pod and update it's status

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#21459]
Intuitively, there should be a route to periodically check the health state of all pods and update their status. Unfortunately, I look through the code of kubelet but could not found such a health check route. Did I miss anything, or there is a good reason to not has a such health check route?

@yujuhong @vishh

**Comment by yujuhong** [comment]
We have a [pod lifecycle event generator (pleg)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pleg/generic.go) which detects container state changes and wakes up the corresponding pod worker to sync. We also have a [fallback resync interval](https://github.com/kubernetes/kubernetes/blob/392fc6668f5536af71950f7df56fe3f89256a66b/pkg/kubelet/pod_workers.go#L80) which is currently 1 minute.

**Comment by mqliang** [comment]
IIRC, k8s v1.0 has not such a "pleg" and "fallback resync interval", right?

**Comment by mqliang** [comment]
So, for v1.0:
1) if container state changed, kubelet will not update it's status or sync it
2) it pod status updated failed at the first time, it will never retry

Right? Free free to correct me. I just observed case 2). But for case 1), I am not sure.

**Comment by mqliang** [comment]
@chaolou

**Comment by yujuhong** [comment]
> So, for v1.0:
> 1) if container state changed, kubelet will not update it's status or sync it

For v1.0, there is a simple 10s resync interval and kubelet will regenerate the pod status in every sync.



> 2) it pod status updated failed at the first time, it will never retry
> 
> Right? Free free to correct me. I just observed case 2). But for case 1), I am not sure.

You should've started your question with this observation and version number :-)

I don't remember how pod status update (request to the apiserver) was handled in details in v1.0. I *think* it should be updated on every sync, but I could be wrong.

**Comment by mqliang** [comment]
> For v1.0, there is a simple 10s resync interval and kubelet will regenerate the pod status in every sync.

I carefully read the code, but just could not find where the resync logic is. Could you please kindly point it out? It will be very helpful for our trouble shooting. Great thanks!

**Comment by yujuhong** [comment]
@mqliang, could you post the version (`kubectl version`) and also describe the problem you found? That'd help narrow down the issue.

**Comment by mqliang** [comment]
The problem I met was: A new created Pod should update it's status from Pending to Running, but the update failed(conflict) at the first time, but kubelet never retry to update it, so the Pod was always `Pending`, but in fact, it works fine on node.

We use V1.0(but we make secondary development on it and add a lot of features, to meet our own usage scenario), so I am not sure the problem is already existing in V1.0, or it was introduced by our own secondary development. Therefore, it will be a great help if you could kindly point out where the 10s resync logic is.

**Comment by yujuhong** [comment]
Since you don't have a specific version number, I'll use 1.0.7 as an example.

The resyncinterval is used here: https://github.com/kubernetes/kubernetes/blob/v1.0.7/pkg/kubelet/kubelet.go#L1774
The status update will be retried if there are errors in https://github.com/kubernetes/kubernetes/blob/v1.0.7/pkg/kubelet/status_manager.go#L174
What it does is that it deletes the cached pod status in statusManager if the update request failed, so that when the next time the pod is resync'd, it will set the pod status, triggering a new update.

If you find a bug in the existing logic, we can perhaps patch the branch :-)
