### ISSUE TITLE
Cannot access RC named "run", "runexample" or "exec" through api proxy

### ISSUE THREAD

**Issue by bryk** [kubernetes/kubernetes#21464]
When my replication controller is named "run" or "exec" I cannot get is through API proxy.

This is caused by reject regex https://github.com/lavalamp/kubernetes/blame/e68ea9e8d480240ad5bbbb98e0cc83fa51a37c79/pkg/kubectl/proxy_server.go#L38 that rejects all calls to `^/api/.*/run`. This also includes `http://proxy:8080/api/v1/namespaces/default/replicationcontrollers/runexample` which is perfectly valid. 

Maybe we can tighten the regexes so that they only protect URLs that are prone to attacks? As opposed to rejecting averything that has `/run.*` inside. 

@brendandburns @smarterclayton

**Comment by bryk** [comment]
This blocks https://github.com/kubernetes/dashboard/issues/373

**Comment by bryk** [comment]
CC @codegoblins

**Comment by lavalamp** [comment]
I'm totally open to making these more specific. Note you can also pass different parameters when you invoke kubectl, so you're not blocked by getting the defaults changed, I would imagine.

**Comment by smarterclayton** [comment]
@stefw introduced this because of a CVE (or the potential for one).
Definitely agree the regex should be more selective.

**Comment by sgrimee** [comment]
+1, been hit by this for RC with name starting with 'attach'
