### ISSUE TITLE
e2e flake: Detected 3 ready nodes, found 3 nodes out of expected 6

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21475]
There's not a lot to go on here, but an e2e test hit `Detected 3 ready nodes, found 3 nodes out of expected 6`

https://github.com/kubernetes/kubernetes/pull/21142#issuecomment-185531308

https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21142/kubernetes-pull-build-test-e2e-gce/29098/

For some reason, only 3 out of 6 nodes came up.  The PR does change salt to add git, but this feels more like a flake than a real failure.

**Comment by lavalamp** [comment]
Is it possible this is the docker thing?

**Comment by dchen1107** [comment]
Not sure about this one because pr builder doesn't collect enough debugging information.

**Comment by justinsb** [comment]
Yeah, I was obliged to create an issue to track the flake, though I don't see how anyone could magically debug this.  I propose we treat as low priority unless we see it happen again.  Do we have a P4?

**Comment by dchen1107** [comment]
@justinsb haha... thanks! I marked this as P3 for now. Also I do think @lavalamp might be right on this. So far all node not ready issue can be categorized into two issues: 

1) https://github.com/kubernetes/kubernetes/issues/20096 Hairpin mode triggers the kernel issue which cause docker process becoming zombie process.
2) docker unclean restart https://github.com/kubernetes/kubernetes/issues/21261#issuecomment-187350526

Thanks!

**Comment by roberthbailey** [comment]
Just saw this again: https://github.com/kubernetes/kubernetes/pull/21004#issuecomment-188535853

**Comment by wojtek-t** [comment]
yeah - it seems it's not solved:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/22047/kubernetes-pull-build-test-e2e-gce/30604/build-log.txt

**Comment by dchen1107** [comment]
The issue was fixed and obsolete now.
