### ISSUE TITLE
Client library should support update retries

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#21479]
By taking a function to check preconditions and apply changes. Every client doing Update needs to do this to deal with conflicts, timeouts, etc.

```
func updateRSWithRetries(rsClient unversionedextensions.ReplicaSetInterface, rs *extensions.ReplicaSet, applyUpdate updateFunc) (*extensions.ReplicaSet, error) {
 +  var err error
 +  oldRs := rs
 +  err = wait.Poll(10*time.Millisecond, 1*time.Minute, func() (bool, error) {
 +      // Apply the update, then attempt to push it to the apiserver.
 +      applyUpdate(rs)
 +      if rs, err = rsClient.Update(rs); err == nil {
 +          // rs contains the latest controller post update
 +          return true, nil
 +      }
 +      // Update the controller with the latest resource version, if the update failed we
 +      // can't trust rs so use oldRs.Name.
 +      if rs, err = rsClient.Get(oldRs.Name); err != nil {
 +          // The Get failed: Value in rs cannot be trusted.
 +          rs = oldRs
 +      }
 +      // The Get passed: rs contains the latest controller, expect a poll for the update.
 +      return false, nil
 +  })
 +  // If the error is non-nil the returned controller cannot be trusted, if it is nil, the returned
 +  // controller contains the applied update.
 +  return rs, err
 +}
```

cc @janetkuo

**Comment by lavalamp** [comment]
@caesarxuchao and @krousey-- this seems pretty easy to add to generated clients. Let's do it for 1.3.

**Comment by caesarxuchao** [comment]
Is this necessary if we add patch to generated clients?

**Comment by bgrant0607** [comment]
@caesarxuchao We should have a retry helper for patch also. :-)

**Comment by lavalamp** [comment]
Yeah, the retry loop for patch and update could take the same function. Actually they could just be the same, and have a patch or update parameter. There's not much difference between them!

**Comment by caesarxuchao** [comment]
Patch is retried at the server side already. I think it will be redundant to retry it on the client side.

I thought this "Update with updateFunc and retry" doesn't provide any additional feature over "Patch", or did I miss something?

**Comment by bgrant0607** [comment]
See also #14280

**Comment by bgrant0607** [comment]
#22384 is moving these to their own util packages for now.

**Comment by bgrant0607** [comment]
cc @janetkuo @nikhiljindal
