### ISSUE TITLE
Improve parameter option encoding/decoding

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#21476]
Follow up from https://github.com/kubernetes/kubernetes/pull/21398

Parameter encoding/decoding follows an odd and asymmetric path today:

Encoding:

```
runtime.NewParameterCodec(...).EncodeParameters(runtime.Object, destination groupversion)
  -> queryparams.Convert(runtime.Object)
    uses json tag names as parameter names
    primitive values are added as query parameter string values
    struct values (currently only unversioned.Time) can convert themselves to a query parameter string value
```

Decoding:

```
runtime.NewParameterCodec(...).DecodeParameters(url.Values, source groupversion, destination object)
  -> conversion.convert(url.Values, versioned destination object)
    uses defined conversion functions between `*[]string` and field types to convert url query parameters to options structs
```

I'm not sure we want lots of arbitrary struct->queryparam serialization, but these paths should be more unified.

cc @smarterclayton

**Comment by techtonik** [comment]
Is there anything going on about this ticket?

**Comment by liggitt** [comment]
not currently, no

**Comment by techtonik** [comment]
@liggitt any ideas how to make parameters encoding/decoding symmetric?

**Comment by techtonik** [comment]
If I understand correctly. `golang` allow to annotate structures, and these annotations could be used for operations. What I don't like about the API is that it operates on parameters indirectly.

    runtime.NewParameterCodec(...).DecodeParameters()

It would be more readable for me to see:

    runtime.params = UpdateFromPOST()

or something like this.
