### ISSUE TITLE
Add system test that exercises all the informers in the node controller

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#21506]
This would have caught #21496.  Unlikely to happen again, but we should be exercising those informers.

In this case, bringing up a DaemonSet, waiting for the pods to be everywhere, then trying to drain with kubectl would have failed.

Not sure if the other two informers are well exercised already, but I'll check.

**Comment by mml** [comment]
Actually, what we need to do is force a kubelet to time out and then verify that the daemon set pod is not deleted.

@kubernetes/sig-testing is there any existing e2e test that intentionally breaks a node (kubelet) after bringing the cluster up?

**Comment by jayunit100** [comment]
Specified chaos tests:  they can be complex and hard to maintain .  And rarely can run in a CI unless it's heavily funded by a downstream use case that is directly profiting someone.

A better solution is to run a generic Kube chaos monkey in the background I think, and then run e2es atop of it?

**Comment by mml** [comment]
That would probably point out a lot of breakage, but sorting out where the bugs lie would be complicated.

At some point, if we're not doing it already, we will want to write tests that verify what happens when a node goes unreachable.  It's not that out there for a system test of a cluster scheduling system, but I gather from your reply I'm the first.

I'm also open to any suggestion that would have uncovered the bug fixed by #21496.

**Comment by ixdy** [comment]
@mml we have a number of "disruptive" tests which break various things in the cluster and check that certain invariants are met - search for `[Disruptive]` in the e2e tests. In particular, `test/e2e/daemon_restart.go` may be a reasonable place to put something like this, though there are disruptive tests defined a few other places, too.

**Comment by mml** [comment]
@ixdy perfect, thanks.

**Comment by mml** [comment]
Not sure if this is relevant any more.
