### ISSUE TITLE
Figure out the resource requirement for master components

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#21500]
Forked from https://github.com/kubernetes/kubernetes/issues/21261 since they are totally different issues. 

Reported from @gmarek and @wojtek-t when bringing up a large cluster with 1000 nodes, there were 210 Nodes cannot be Ready state during validation phase (https://github.com/kubernetes/kubernetes/issues/21261#issuecomment-185628072)

After some debugging, it turns out that the node cannot join the cluster because it cannot get subnet file /var/run/flannel/subnet.env from flannel_server for about two and half hours, so  that it cannot config the node properly and docker cannot start properly too:

```
I0218 04:22:33.680863    3803 kubelet.go:2671] Flannel server handshake failed Waiting for subnet file /var/run/flannel/subnet.env
...
I0218 06:51:10.022449    3911 kubelet.go:2671] Flannel server handshake failed Waiting for subnet file /var/run/flannel/subnet.env
```

I checked the flannel-server pods, and found the etcd-container within that pod is in crashloop all the time. It turns out the etcd-container is oom-killed on master node.

We need to figure out how much resource required by flannel-server pods, especially the etcd-container one. 

cc/ @bprashanth @thockin @kubernetes/goog-cluster

**Comment by bprashanth** [comment]
This is a system oom repeatedly killing flannel's etcd. I had initially set its limits to a paltry 50m based on observations in a 100node cluster (https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/flannel-server/init.sls#L30). How much can we spare on the 1000 node master? And if we don't know, should we just allow flannel to use the master etcd, and let that one take as much as it needs modulo other master components? I think this is a control-plane issue because it directly relates to recommended master size for 1000 nodes.

**Comment by wojtek-t** [comment]
>
This is a system oom repeatedly killing flannel's etcd. I had initially set its limits to a paltry 50m based on observations in a 100node cluster (https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/flannel-server/init.sls#L30). How much can we spare on the 1000 node master?

How much does it need? I think it's not a problem to give it significantly more than on smaller clusters. But we need to know how much it needs.

>
 And if we don't know, should we just allow flannel to use the master etcd, and let that one take as much as it needs modulo other master components?

I don't think so. I think it shouldn't write to the main etcd instance.

@davidopp

**Comment by bprashanth** [comment]
> I don't think so. I think it shouldn't write to the main etcd instance.

We're in agreement, which is why i setup a different one to begin with. 

> How much does it need? I think it's not a problem to give it significantly more than on smaller clusters. But we need to know how much it needs.

Is this something you guys can profile? I have not profiled it on various master sizes, and am currently swamped with release worthy stuff.

**Comment by dchen1107** [comment]
I re-examine the kernel log, and actually most of them are memory exceeded oom-kill, not sys oom here. Docker inspect result is misleading here. I think there is a regression bug with this docker version. 

Also based on the configuration at https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/flannel-server/flannel-server.manifest: 
The pod has qos: Guarantee, not Burstable here. 

@bprashanth I think you have to figure out how much memory required for 1000 nodes first, then we can decide how big the node is required for those large clusters.

**Comment by bprashanth** [comment]
> @bprashanth I think you have to figure out how much memory required for 1000 nodes first, then we can decide how big the node is required for those large clusters.

Let it take as much as it needs and back track? The other etcds don't have a mem limit.

**Comment by bprashanth** [comment]
I'm retitling this, since none of the master components don't seem to set memory limits. https://github.com/kubernetes/kubernetes/issues/21505 just removes the memory limit from flannel etcd. 

@dchen1107 mentioned that we should pick a couple of cluster sizes, profile components and document their cpu/memory (if not set limits), SGTM, if we come up with a list and profiling methodology I'd be happy to do so for flannel on the master (for a 100 nodes I just ran top during density).

**Comment by magicwang-cn** [comment]
@HardySimpson @magicwang @kevin-wangzefeng @alfred-huangjian

**Comment by davidopp** [comment]
@wojtek-t or @gmarek can one of you take this?

**Comment by gmarek** [comment]
Yes we can. We would be doing it continuously if master node were registered...

I'll spin a self-hosted master and run a Density30 test with `gather-resource-usage` set to true. I'll probably need to slightly modify it to gather resident memory data instead of whatever we had few months back.

**Comment by gmarek** [comment]
For 100 Node cluster:
```
99 percentile:
container                                                                 cpu(cores) memory(MB)
"etcd-server-e2e-test-gmarek-master/etcd-container"                       0.135      242.00
"etcd-server-events-e2e-test-gmarek-master/etcd-container"                0.082      237.22
"kube-apiserver-e2e-test-gmarek-master/kube-apiserver"                    1.233      895.38
"kube-controller-manager-e2e-test-gmarek-master/kube-controller-manager"  0.345      319.96
"kube-scheduler-e2e-test-gmarek-master/kube-scheduler"                    0.232      48.28
```

CPU usage seems a little low for my liking, but that's the data.

**Comment by bprashanth** [comment]
Nice. IMHO we should start by documenting this, and actually set resource limits in 1.3 (my eager setting of the flannel-etcd memory limit is a lesson to learn from).

**Comment by gmarek** [comment]
I'm running bigger clusters now, to have more data, as it's long time since we were checking how big master machines should be. Above shows that 2 core machine for 100 nodes would probably be slightly too small.

**Comment by gmarek** [comment]
Note that those are results from a single runs, which already takes way too much time. I'd really, really, really love to have self-registered master, as then we'd gather this data continuously.

**Comment by gmarek** [comment]
For 300 Node cluster:
```
99 percentile:
container                                                                 cpu(cores) memory(MB)
"etcd-server-e2e-test-gmarek-master/etcd-container"                       0.200      450.74
"etcd-server-events-e2e-test-gmarek-master/etcd-container"                0.091      505.11
"kube-apiserver-e2e-test-gmarek-master/kube-apiserver"                    2.103      1726.28
"kube-controller-manager-e2e-test-gmarek-master/kube-controller-manager"  0.517      916.42
"kube-scheduler-e2e-test-gmarek-master/kube-scheduler"                    1.041      107.36
```

It's strange that everything grew ~2x.

**Comment by gmarek** [comment]
For 500 Node cluster (n1-standard-16 master):
```
99 percentile:
container                                                                 cpu(cores) memory(MB)
"etcd-server-e2e-test-gmarek-master/etcd-container"                       0.241      706.85
"etcd-server-events-e2e-test-gmarek-master/etcd-container"                0.099      746.35
"kube-apiserver-e2e-test-gmarek-master/kube-apiserver"                    2.998      2439.88
"kube-controller-manager-e2e-test-gmarek-master/kube-controller-manager"  0.633      1624.04
"kube-scheduler-e2e-test-gmarek-master/kube-scheduler"                    1.576      167.41
```

**Comment by wojtek-t** [comment]
Please do NOT set limits just based on Density test. It's possible to do some more extensive tests (I think that even load.go would generate more load but we should first make it work in larger clusters: #20638)

**Comment by gmarek** [comment]
On top of what @wojtek-t wrote - those are 99th percentiles. I can produce 100th ones, but it still won't be enough, as we're probing containers every 60 seconds. Hence we do need to leave some slack for all the components.

**Comment by gmarek** [comment]
Note that most critical component is an API server, throttling which could have huge performance impact. OTOH if we really do need to limit components it'd be better to do it on ControllerManager/Scheduler. Throttling those will still have an impact by reducing system responsiveness, but it's still better than throttling API server which could break our SLO (on top of reducing system responsiveness).

**Comment by thockin** [comment]
We will have the same issue with the DNS server at some point.

**Comment by gmarek** [comment]
We should make an effort to have master self register, which will allow for easier monitoring of resource usage.

**Comment by davidopp** [comment]
^ We can do that for 1.3, we already decided to drop it from 1.2.

**Comment by gmarek** [comment]
Yup. That's what I meant.

**Comment by gmarek** [comment]
I tried to run gatherer on 1000 node cluster, but I failed (cluster startup issues, and later client throttling problem for huge clusters)

**Comment by gmarek** [comment]
Finally got data from 1000 node cluster:
```
99 percentile:
container                                                                 cpu(cores) memory(MB)
"etcd-server-e2e-test-gmarek-master/etcd-container"                       0.312      1792.36
"etcd-server-events-e2e-test-gmarek-master/etcd-container"                0.095      1846.36
"kube-apiserver-e2e-test-gmarek-master/kube-apiserver"                    5.924      4285.18
"kube-controller-manager-e2e-test-gmarek-master/kube-controller-manager"  3.570      4507.16
"kube-scheduler-e2e-test-gmarek-master/kube-scheduler"                    1.758      5541.92
```
I also gathered 100th percentile this time:
```
```

**Comment by davidopp** [comment]
OK, I'll add this information to `docs/admin/cluster-large.md` and then for 1.3 we can use it to set limits.

**Comment by davidopp** [comment]
@gmarek any thoughts on why the scheduler memory consumption blows up going from 500 to 1000 nodes?

**Comment by wojtek-t** [comment]
>
@gmarek any thoughts on why the scheduler memory consumption blows up going from 500 to 1000 nodes?

Is it possible that it was a different version (e.g. where we had this new cache?) Or sth like that?

Also note, that for 500-node we have 99th percentile and for 1000-node we have 100th percentile. :)

BTW - 167MB in 500-node cluster seems really low - in fact I'm quite skeptical about this data.
We have an informer for all AssignedNonTerminated pods:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L109
which mean we are storing all active pods in the system in the cache. Assuming averated pod is 5KB, then in 500-node full cluster, we have 75MB of raw data, without any data structure overhead etc.
So I'm not fully convinved by this data...

And we should measure 100th percentile in all cases in my opinion.

**Comment by gmarek** [comment]
The data are what cAdvisor reports and is RSS size, not allocated virtual memory size. It's possible that OS dumped something on disk. 

I can rerun those tests when I come back from Kubecon.

**Comment by davidopp** [comment]
@wojtek-t https://github.com/kubernetes/kubernetes/issues/21500#issuecomment-188770116 shows both 99th percentile and 100th percentile numbers. In kubernetes/kubernetes.github.io/#77 I used 99th percentile for all cluster sizes.

@gmarek If you want to give me new/more accurate numbers, that would be great. 100th percentile for everything sounds good. Please distill it into the format I used in kubernetes/kubernetes.github.io/#77, and post the numbers here, and I will incorporate it into the PR.

**Comment by davidopp** [comment]
Actually in kubernetes/kubernetes.github.io#77 @wojtek-t suggested just omitting the CPU/memory usage numbers. If that's preferred then it's probably still a good idea to measure it (and set limits in the next release), but we can leave it out of the docs.

**Comment by wojtek-t** [comment]
@davidopp - just to clarify a bit - I think that in general we should have these numbers and should be setting at least requests (but probably also limits) based on them. However, as for now, I don't have enough confidence in these numbers. That said, for sure I don't want to set limits based on those in 1.2, but also I'm not sure if we should publish them in the docs officially...
I think we need some more & better experiments before doing that...

**Comment by gmarek** [comment]
Since we enabled master registration we gather this data continuously for 100 Node cluster. We should turn it on for 1000 Node one.

**Comment by davidopp** [comment]
Moving this to next-candidate
