### ISSUE TITLE
Factour our Service.type=Loadbalancer tests intoto gce slow

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#21512]
The cutoff is 5m for the normal gce suite, which times out in 30m inclusive of cluster up and down. So we should factor out the part of https://github.com/kubernetes/kubernetes/blob/master/test/e2e/service.go#L490 that sets up and waits on external loadbalancers into gce-slow. 

@kubernetes/goog-testing @fejta @spiffxp

**Comment by spiffxp** [comment]
cc @kubernetes/sig-testing

**Comment by fejta** [comment]
Should help with https://github.com/kubernetes/kubernetes/issues/21138

**Comment by bprashanth** [comment]
This is probably not getting done for 1.2, there's an email thread about creating external resources and the time we can expect it to take in general

**Comment by thockin** [comment]
I'm going to lower this to P2 since it is not something we expect to wrap soon.

**Comment by fejta** [comment]
So the plan is to punt all of the `should be able to change the type and ports of a service test` to the slow suite?

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/service.go#L406

**Comment by bprashanth** [comment]
If we must have a lower runtime and are ok not running type=loadbalancer tests per pr (don't remember how that email discussion panned out), then we'd move just the type=loadbalancer tests out: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/service.go#L501. Unfortunately that would involve duplication, since we need to setup a service of some other type, verify it works, then switch it to type=loadbalancer. I think we definitely want to run the other "change type and ports" tests per pr.

**Comment by fejta** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/service.go#L406

https://github.com/kubernetes/kubernetes/commit/39de4be40dbdbd544200efbed457d0fc89375e1f
