### ISSUE TITLE
kube-up.sh failed with KUBERNETES_PROVIDER=vagrant

### ISSUE THREAD

**Issue by mfanjie** [kubernetes/kubernetes#21529]
Steps to reproduce.
1. fetch the latest code from master branch 
2. export KUBERNETES_PROVIDER=vagrant
3. make build and run cluster/kube-up.sh
The process will failed on salt setup steps with 3 failures.
==> master: [ERROR   ] {'pid': 5871, 'retcode': 1, 'stderr': '/tmppR9bNG.sh: line 21: DEBUG: unbound variable', 'stdout': ''}
==> master: [ERROR   ] Parent directory not present
==> master: [ERROR   ] Parent directory not present

==> master:           ID: pkg-core
==> master: ----------
==> master:           ID: kubernetes-cert
==> master:     Function: cmd.script
==> master:       Result: False
==> master:      Comment: Command 'kubernetes-cert' run
==> master:      Started: 07:42:20.080680
==> master:     Duration: 153.923 ms
==> master:      Changes:   
==> master:               ----------
==> master:               pid:
==> master:                   5871
==> master:               retcode:
==> master:                   1
==> master:               stderr:
==> master:                   /tmppR9bNG.sh: line 21: DEBUG: unbound variable
==> master:               stdout:
==> master: ----------
==> master:           ID: /srv/kubernetes/known_tokens.csv
==> master:     Function: file.managed
==> master:       Result: False
==> master:      Comment: Parent directory not present
==> master:      Started: 07:42:20.258421
==> master:     Duration: 1.93 ms
==> master:      Changes:   
==> master: ----------
==> master:           ID: /srv/kubernetes/basic_auth.csv
==> master:     Function: file.managed
==> master:       Result: False
==> master:      Comment: Parent directory not present
==> master:      Started: 07:42:20.260430
==> master:     Duration: 1.759 ms
==> master:      Changes:   
==> master: ----------

**Comment by mfanjie** [comment]
1. from the logs we can see the certificates are not successfully generated with error "DEBUG: unbound variable"
2. check generate-ca-cert.sh, the following codes are around line 21.
if [ "${DEBUG}" == "true" ]; then
	set -x
fi
3. Checking the change history, the change was introduced by #21110, while the DEBUG variable is only defined in ubuntu/configure-default.sh

So the root cause is a general shell script calls a platform dependent variable, this call other platforms build fail.
I do not see the motivation of enable debug capabilities in generate-ca-cert.sh for all platforms as the script is one of the most stable one, so I'd rather to remove the debug stuff.
@ixdy @MikeSpreitzer @roberthbailey

**Comment by mfanjie** [comment]
Talking about the alternative of #21110, I am behind of proxy so this script failed me as well before as it need to get https://storage.googleapis.com/kubernetes-release/easy-rsa/easy-rsa.tar.gz during the cluster boot up time.
And this this not the only place that cluster bootstrapper attempts to connect to external network.
It also require to pull kubernetes addon images from gcr.io as the very late steps of master node boot up.

A general question is what's the prerequisite of cluster boot strapping? do we allow the K8S being booted in isolated network? 
If yes, what's the approach we should allow users to do?
Option 1: prepare all necessary files/package like easyrsa and docker images for kubernetes addons
A bunch of steps need to be provided as doc then.
Option 2:  require users to enable proxy for boot strapping, this is more easier to end users, but we need different implements for each kubernertes provider.(Actually, I have a implementation for vagrant and I found this issue when I tested my patch)

**Comment by mfanjie** [comment]
After DEBUG issue is fixed, kube-up still failed for a server behind a proxy, I am using KUBERNETES_PROVIDER=vagrant.

Observation:
1. there is not error on master and node-1 provision logs while the kube up stuck at waiting kube-apiserver services.
cluster "vagrant" set.
user "vagrant" set.
context "vagrant" set.
switched to context "vagrant".
Wrote config for vagrant to /Users/fmeng/.kube/config
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
...................................................................................
..

2. vagrant ssh to master, check apiserver log, found etcd cluster is not available.

[root@kubernetes-master vagrant]# tail -f /var/log/kube-apiserver.log 
E0222 04:47:56.563499       9 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *extensions.HorizontalPodAutoscaler: client: etcd cluster is unavailable or misconfigured
E0222 04:47:56.564558       9 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *extensions.Deployment: client: etcd cluster is unavailable or misconfigured
E0222 04:47:56.564689       9 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *extensions.DaemonSet: client: etcd cluster is unavailable or misconfigured
E0222 04:47:56.564831       9 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *extensions.Job: client: etcd cluster is unavailable or misconfigured
E0222 04:47:56.564975       9 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *extensions.Ingress: client: etcd cluster is unavailable or misconfigured
E0222 04:47:56.565314       9 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *extensions.ReplicaSet: client: etcd cluster is unavailable or misconfigured
E0222 04:47:56.565475       9 cacher.go:212] unexpected ListAndWatch error: pkg/storage/cacher.go:160: Failed to list *extensions.HorizontalPodAutoscaler: client: etcd cluster is unavailable or misconfigured
[restful] 2016/02/22 04:47:56 log.go:30: [restful/swagger] listing is available at https://10.245.1.2:443/swaggerapi/
[restful] 2016/02/22 04:47:56 log.go:30: [restful/swagger] https://10.245.1.2:443/swaggerui/ is mapped to folder /swagger-ui/
F0222 04:47:56.594278       9 controller.go:86] Unable to perform initial IP allocation check: unable to refresh the service IP block: client: etcd cluster is unavailable or misconfigured

3. Run docker images, etcd images is not there as it is pulled from gcr.io while we are behind of proxy.
cat /etc/kubernetes/manifests/etcd.manifest
{
"apiVersion": "v1",
"kind": "Pod",
"metadata": {
  "name":"etcd-server",
  "namespace": "kube-system"
},
"spec":{
"hostNetwork": true,
"containers":[
    {
    "name": "etcd-container",
    "image": "gcr.io/google_containers/etcd:2.2.1",
    "resources": {
      "requests": {
        "cpu": "200m"
      }
    },

[root@kubernetes-master vagrant]# docker pull gcr.io/google_containers/etcd:2.2.1
Trying to pull repository gcr.io/google_containers/etcd ... failed
unable to ping registry endpoint https://gcr.io/v0/
v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp 74.125.203.82:443: i/o timeout
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp 74.125.203.82:443: i/o timeout

**Comment by MikeSpreitzer** [comment]
Yes, there is also the problem of the image pulls done by the docker engines.  Regarding usage of the cluster/ubuntu scripting when the target machines are in a restricted environment but the machine running kube-up is not, this can be fixed without any changes to the scripting maintained at https://github.com/kubernetes/kubernetes/.  In my own work I am pursuing this approach: before installing kubernetes, get the necessary images to those docker engines by saving image tarchives elsewhere and loading them on the target docker engines.

If I understand correctly, your use case is different: you are running cluster/kube-up.sh using the Vagrant provider and your VM host machine is not able to open TCP connections to gcr.io.  I have a further question about your use case.  Do you need only a certain set of docker images, or unbounded access to external registries?
