### ISSUE TITLE
Kinds not added to DefaultRESTMapper when using rewritten Kube imports (breaks Godeps, 1.5 vendor experiment, etc)

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#21525]
Kinds are not being added to DefaultRESTMapper when the Kubernetes import path has been rewritten, something that is commonly done to manage Golang dependencies. This makes it harder to use Kubernetes as a dependency.

The problem is that in NewDefaultRESTMapper, there is a line which skips adding any Kind that's not from an unmodified Kubernetes import path. The path is determined using reflection.

**[/pkg/api/mapper.go](https://github.com/kubernetes/kubernetes/blob/ed95a6d7/pkg/api/mapper.go#L49):**
```go
// TODO: Remove import path prefix check.
// We check the import path prefix because we currently stuff both "api" and "extensions" objects
// into the same group within Scheme since Scheme has no notion of groups yet.
if !strings.HasPrefix(oType.PkgPath(), importPathPrefix) || ignoredKinds.Has(kind) {
	continue
}
```
I see a couple ways to resolve this:
* Add proper group support as noted by the TODO. I tried unsuccessfully to find a relevant open issue.
* Check for a partial match on the import path

**Comment by ncdc** [comment]
cc @kubernetes/sig-api-machinery

**Comment by ncdc** [comment]
cc @deads2k

**Comment by nikhiljindal** [comment]
Changing HasPrefix to Contains seems fine to me.

@ethernetdan Feel free to send a PR.
