### ISSUE TITLE
Allow Scale type, which is in a different API group, to be registered as a subresource of a api/v1 object

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#21549]
Fork from https://github.com/kubernetes/kubernetes/issues/18528

@piosz @mwielgus @bgrant0607 @madhusudancs @kubernetes/goog-control-plane

**Comment by fgrzadkowski** [comment]
PR https://github.com/kubernetes/kubernetes/pull/20745

**Comment by madhusudancs** [comment]
> AFAIU we agreed that with new reference from HPA object moving Scale object is not a blocker anymore. I'll create a separate issue for it. We still have some blockers we need to work on, but after that we can take a look at scale subresource. Btw - what's left to be done in your PR? 

This issue and a whole lot of Deployments and ReplicaSet code that is commented out due to its dependency on Scale subresource.

> Would it be faster if you finish working on it?

That, I am not sure. We should discuss this together.

cc @bgrant0607 @lavalamp

**Comment by davidopp** [comment]
Can someone give a status update on this issue?

**Comment by madhusudancs** [comment]
@davidopp I posted an update here - #22505. Sorry, seeing this now. PR #21909 was merged yesterday, so we can close this issue. Issue #22505 should track the WIP PRs.
