### ISSUE TITLE
Rescheduler Proposal Draft: manually rescheduling part

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#21543]
Rescheduler Proposal Draft: manually rescheduling part
-----

##### Use case 1: manually rescheduling for cluster migration
-----
There are some cases where a batch of nodes need to be temporarily/permanently 
removed from kubernetes cluster, for example:

* We want upgrade some node's OS version. Since it's a better choice to upgrade all the nodes in parallel, instead of update one by one, it may cause some services unavailable. Thus, we should migrate all the pods on those nodes first. 
* Some nodes need to be removed permanently for some business reasons, i.e. we may want change the cloud provider.

##### Use case 2: auto-rescheduling for defragmentation
There should also a route in Rescheduler run continuously in the background to optimize cluster layout, make sure once resource utilization of nodes unbalanced, it will try to reschedule some pods. 

#### Initial Implementation
-----
1) manually rescheduling for cluster migration: ReschedulingJob

User could submit a Rescheduling Job:
```
type ReschedulingJob struct {
    unversioned.TypeMeta `json:",inline"`
	api.ObjectMeta       `json:"metadata,omitempty"`

	// Specification of the desired behavior of the ReschedulingJob.
	Spec ReschedulingJobSpec `json:"spec,omitempty"`

	// Most recently observed status of the ReschedulingJob.
	Status ReschedulingJobStatus `json:"status,omitempty"`
}

type ReschedulingJobSpec struct {
	// Pods on those nodes will be evicted
	SourceNodeSelector	map[string]string `json:"sourceNodeSelector,omitempty"`
	// Pods will be scheduled to those nodes.
	DestinationNodeSelector	map[string]string `json:"destinationNodeSelector,omitempty"`	
	// Minimum number of seconds for which a rescheduled pod should be ready
	// without any of its container crashing, for it to be considered available.
	// Defaults to 0 (pod will be considered available as soon as it is ready)
	MinReadySeconds int	`json:"minReadySeconds,omitempty"`
	// The maximum number of pods that can be unavailable during the rescheduling.
	// Value must be percentage of total pods belongs to the same ReplicationController/ReplicaSet(ex: 10%)
	MaxUnavailable intstr.IntOrString `json:"maxUnavailable,omitempty"`
}

type ReschedulingJobSpec status {
	// Conditions represent the latest available observations of an object's current state.
	Conditions []ReschedulingJobCondition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type"`

	// StartTime represents time when the rescheduling job was acknowledged by the rescheduler.
	// It is not guaranteed to be set in happens-before order across separate operations.
	// It is represented in RFC3339 form and is in UTC.
	StartTime *unversioned.Time `json:"startTime,omitempty"`

	// CompletionTime represents time when the rescheduling job was completed. It is not guaranteed to
	// be set in happens-before order across separate operations.
	// It is represented in RFC3339 form and is in UTC.
	CompletionTime *unversioned.Time `json:"completionTime,omitempty"`

	// Succeeded is the number of pods which has been successfully rescheduled(PodStatus==Ready).
	Succeeded int `json:"succeeded,omitempty"`

	// Remaining is the number of pods which were waiting to be rescheduled.
	Remaining int `json:"remaining,omitempty"`
}

```

Example:
Some nodes need to be removed from k8s cluster, first we we add a label "nodeKind":"srcNode" to those nodes, then we add some new nodes as destination nodes, and we add a label "nodeKind":"desNode" to them. Then we submit a ReschedulingJob, and rescheduler will work as follows:

a) make all source nodes unschedulerable

b) reschedule all pods on source nodes, rescheduler guarantee that there are at most MaxUnavailable pods which belongs to the same
 ReplicationController/ReplicaSet been rescheduled at the same time.

2) auto-rescheduling for defragmentation
----
Have not considered a good implementation about this. A good algorithm is needed, since I think we want try to kill as little pods as possible when rescheduling.

**Comment by mqliang** [comment]
I am really interested in cluster migration functionality, I think it could be supported by rescheduler. As for auto-rescheduling functionality for defragmentation, I have not considered a good implementation. 

If the cluster migration functionality in this draft looks good, I think it is a good start to implement rescheduler: manually rescheduling functionality was much easier to implement and verify.

As long as the rescheduler feature is put on the table. We could gradually add more and more feature on it step by step, some helpful features such as:

1) Redistribute Pods onto new nodes added by a cluster auto-scaler; 
2) move Pods around to get a PENDING Pod to schedule
3) move Pods around when node resource allocation unbalance was detected

Any feedbacks were welcomed.
@davidopp @bgrant0607 @HaiyangDING @timothysc @hurf @kevin-wangzefeng

**Comment by mqliang** [comment]
In addition, for auto-rescheduling feature, I think the most important task was designing a good algorithm,  
since:
1) I think we want try to kill as little pods as possible when rescheduling.
2) rescheduler should have the ability to trade off between rescheduling and adding new nodes:  if rescheduler must kill a lot of pods to keep resource allocation balanced or a PENDING Pod to scheduled, 
it's a better choice to add new nodes.

**Comment by mml** [comment]
Use case 1 is what we'd generally call draining for maintenance.  The maintenance might be for software or hardware reasons, but in any case you just want to gracefully remove all the work from nodes so you can do something to them.  In this case, there's no *re*scheduling, per-se.  You simply mark the node as unschedulable, delete the pods following whatever rules are appropriate, and you're done.  The existing pod controller (e.g. a replication controller) and scheduler do all the work.

Use case 2 is generally what we mean by *re*scheduler.

**Comment by mqliang** [comment]
> but in any case you just want to gracefully remove all the work from nodes so you can do something to them. In this case, there's no rescheduling, per-se. You simply mark the node as unschedulable, delete the pods following whatever rules are appropriate, and you're done. The existing pod controller (e.g. a replication controller) and scheduler do all the work.

Agree! But I think there should be two ReschedulingJobType:

1) DrainingForMaintenanceType, which is what I proposed in this proposal
2) DrainingForClusterScaleDownType: If we have a large cluster, but with low resource usage rate, and Pods just spreading on all nodes, we want to empty out some nodes so they could be recycled. In this case, rescheduling is needed.

So, I think rescheduler should support both manually rescheduling and auto-rescheduling:
1) manually rescheduling(user submit a ReschedulingJob to activate rescheduling):
 * DrainingForMaintenance
 * DrainingForClusterScaleDown
2) auto-rescheduling(there is a route in Rescheduler run continuously in the background to optimize cluster layout) : 
 * Redistribute Pods onto new nodes added by a cluster auto-scaler;
 * Move Pods around to get a PENDING Pod to schedule
 * Move Pods around when node resource allocation unbalance was detected

**Comment by mqliang** [comment]
And DrainingForClusterScaleDown feature should be implemented as a manually-rescheduling job, instead of as a background route, since:
1) The objective function of DrainingForClusterScaleDown feature and "Redistribute Pods onto new nodes added by a cluster auto-scaler/Move Pods around when node resource allocation unbalance was detected" are conflict.  
2) DrainingForClusterScaleDown feature should mark the empting out nodes as unschedulable.

Just my random thought for discussion.

**Comment by hurf** [comment]
cc myself and @HaiyangDING

**Comment by mqliang** [comment]
##### Part 2: "Work Stealing" Algorithm for "Redistribute Pods onto new nodes added by a cluster auto-scaler" feature

"Work Stealing"  algorithm, see http://supertech.csail.mit.edu/papers/steal.pdf is very suitable for the  "Redistribute Pods onto new nodes added by a cluster auto-scaler" feature. If this algorithm generally looks good, I will send I proposal to describe the design&implementation detail

**Comment by mqliang** [comment]
close this in favour of https://github.com/kubernetes/kubernetes/issues/21679
