### ISSUE TITLE
Kubelet should monitor number of inodes, not just disk space

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21546]
I hit a problem where a node was reporting healthy, but all docker actions were hanging silently.   e.g. pods were stuck Terminating, couldn't launch pods etc.  I tried restarting Docker, and when I did, Docker failed to start with this error: `Unable to open the database file`

There is a Docker issue: https://github.com/docker/docker/issues/10178

Unfortunately I nuked the machine before I thought to check inodes.  I will monitor to see if I can find another machine in the same situation.  But checking for no-more-inodes seems like a good thing to do, along with checking for no-more-space.

A similar problem was reported on slack though, but that user (andy) said he had not run out of inodes.

**Comment by dchen1107** [comment]
@justinsb I agreed with you that kubelet through cAdvisor should detect out-of-resource including inodes issue and propagate it. But currently we froze the api between cAdvsior and Kubelet and plan to do major refactory at 1.3 timeline. https://github.com/kubernetes/kubernetes/issues/18770

For 1.2 release, we can document it as a known issue: #21000. 

cc/ @timstclair @vishh

**Comment by vishh** [comment]
@dchen1107: Tracking inodes for the root filesystem that docker is using
should be OK for v1.2. WDYT?

**Comment by dchen1107** [comment]
Chatted with @vishh offline. We are going to report inode limit and usage on root filesystem to protect the node itself.  @vishh will try to get this into 1.2 release. But deferred the rest to next release.

**Comment by mark9white** [comment]
I’m not sure if it’s already in scope in this issue, but not only should inodes be reported, but a low inode situation should also trigger container GC.

**Comment by ronnielai** [comment]
**Work items**

- Check for inodes exhaustion and transition to `OutOfDisk` or `DiskPressure` conditions
- Trigger evictions if inodes are exhausted

**Comment by ojongerius** [comment]
The commit used to fix this issue was reverted (https://github.com/kubernetes/kubernetes/pull/28536) but AFAICS https://github.com/google/cadvisor/issues/1366 allows us to revert the revert. Is that right?

**Comment by ojongerius** [comment]
Never mind, OutOfDisk will be replace by NodeDiskPressure. See https://github.com/kubernetes/kubernetes/pull/41654.

**Comment by iobond** [comment]
still have the same issue... any resolution?
