### ISSUE TITLE
Create e2e tests for HPA with custom metrics.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#21547]
Unit tests are already there

**Comment by fgrzadkowski** [comment]
Adding this test should not block cutting release branch.

**Comment by davidopp** [comment]
ping?

**Comment by fgrzadkowski** [comment]
Marcin - what's the plan here?

**Comment by mwielgus** [comment]
Pivoted the cm strategy in HPA. Closing the issue.
