### ISSUE TITLE
Kubectl describe horizontalpodautoscaler should print annotations

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#21541]
Now it doesn't .

**Comment by mwielgus** [comment]
cc: @piosz @fgrzadkowski

**Comment by piosz** [comment]
I'm not sure whether describe should print annotations. I know that custom metrics are specified by annotations but describe doesn't print annotations for any other resource. Annotations for hpa are accessible with `kubectl get hpa -o yaml`.

@bgrant0607 any opinion?

**Comment by bgrant0607** [comment]
@piosz Feel free to describe the content of the specific annotations you are using.
