### ISSUE TITLE
integration flake: "nginx-deployment" cannot be updated: the object has been modified [reaper]

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#21544]
```
Error from server: deployments.extensions "nginx-deployment" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/21537/kubernetes-pull-test-unit-integration/15153/build-log.txt

cc @bgrant0607 @janetkuo

**Comment by bgrant0607** [comment]
cc @kargakis @mqliang

**Comment by bgrant0607** [comment]
I'll take a look at this one.

**Comment by bgrant0607** [comment]
Failure looks like it's in the reaper:
```
  kubectl delete deployment nginx-deployment "${kube_flags[@]}"
```
cc @soltysh

**Comment by bgrant0607** [comment]
Paused is set to true with no retry:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/stop.go#L409
```
	deployment, err = deployments.Get(name)
	if err != nil {
		return err
	}
	deployment.Spec.Paused = true
	deployment, err = deployments.Update(deployment)
	if err != nil {
		return err
	}
```

**Comment by bgrant0607** [comment]
@kargakis @soltysh Does one of you have time to fix this?

**Comment by bgrant0607** [comment]
Several tests appear to be failing due to this.

**Comment by janetkuo** [comment]
Filed #21572

**Comment by bgrant0607** [comment]
Appears to be fixed.
