### ISSUE TITLE
Vagrant getting started: provisioning of vm fails with "Failed to run install_fedora_deps()!!!"

### ISSUE THREAD

**Issue by devopstiger** [kubernetes/kubernetes#21555]
I followed the guide [here] (https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/vagrant.md)

The provisioning script fails with this error: 

```
==> master: File contains no section headers.
==> master: file: file:///etc/yum.repos.d/saltstack-salt-fedora-21.repo, line: 1
==> master: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n'
==> master:  * ERROR: Failed to run install_fedora_deps()!!!
```

**Comment by dchen1107** [comment]
cc/ @derekwaynecarr

**Comment by rsuniev** [comment]
Temp fix. Change your ~/kubernetes/vagrant/provision-minion.sh
-    curl -sS -L --connect-timeout 20 --retry 6 --retry-delay 10 https://bootstrap.saltstack.com | sh -s
+    curl -sS -L --connect-timeout 20 --retry 6 --retry-delay 10 https://gist.githubusercontent.com/rmohr/43941d0881f0682b99a7/raw/5b5e075e373cd81689e991eaef6cd95beb7b2d2a/bootstrap-salt.sh | sh -s
and ./cluster/kube-up.sh again

**Comment by derekwaynecarr** [comment]
I will investigate this tomorrow morning.

**Comment by derekwaynecarr** [comment]
I recommend working from master/HEAD ; the base box has been bumped to Fedora 23 and you should not see this issue with salt bootstrapping.  If you continue to have problems, please re-open.
