### ISSUE TITLE
Improve Node Management documentation

### ISSUE THREAD

**Issue by alexgorbatchev** [kubernetes/kubernetes#21558]
As a user who just went through the [Getting Started w. Vagrant](http://kubernetes.io/v1.1/docs/getting-started-guides/vagrant.html) guide, it's not obvious (and I mean after an hour of searching I still have no idea how) to provision nodes/minions.

The [Node Management](http://kubernetes.io/v1.1/docs/admin/node.html) page says the following:

> ## Node Management
> 
> Unlike Pods and Services, a Node is not inherently created by Kubernetes: it is either taken from cloud providers like Google Compute Engine, or from your pool of physical or virtual machines. What this means is that when Kubernetes creates a node, it is really just creating an object that represents the node in its internal state.

It would be very useful for newcomers to see a link or have en explanation here how to actually create new nodes. I'm still at a complete loss on this.

**Comment by bgrant0607** [comment]
In the getting-started guide, did you see the instructions about how to change the number of nodes?

In general, these types of questions should be asked in the support forums, such as stackoverflow.

I'll leave this issue open to add a reference from the node management doc back to the getting-started guides.
