### ISSUE TITLE
Make status info in describe.DescribeContainers optional

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#21551]
See https://github.com/kubernetes/kubernetes/pull/21341

In order to re-use this helper for describing higher level resources such as replica sets, deployments, daemon sets, etc. we need to make container status info optional since it's only useful if we have the status from a pod. Fanning out a {deployment,rc, rs, ...} to its pods just to get that info is not an option while we are in the describer.

cc: @smarterclayton

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by smarterclayton** [comment]
Easiest check is to use presence in the map as whether to show the status section.  Or to pass a nil map and treat the map as nil.

**Comment by AdoHe** [comment]
I will add a quick fix to this. Also I prefer using presence in the map as whether to show the status section.

**Comment by AdoHe** [comment]
@smarterclayton I decide to add a `showStatus` field to every describer.

**Comment by kargakis** [comment]
This is fixed now by https://github.com/kubernetes/kubernetes/pull/21661. Thanks @AdoHe
