### ISSUE TITLE
1000 node cluster: GCE api calls have low success rate

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#21561]
From https://console.developers.google.com/project I see that my project (mohr-instance-manager1, used exclusively for GKE clusters) has 66k successful API requests and 353k errors.  A skim of other kubernetes and GKE projects turns up many that have 10-20% error rates, which isn't the 80% error rate my project is seeing, but it still seems unlikely that's WAI and there's a bug in something that calls GCE's api.

**Comment by alex-mohr** [comment]
@wojtek-t @gmarek for 1k nodes

**Comment by alex-mohr** [comment]
Primary reason for sustained API errors appears to be that the route controller does not seem to notice that routes already exist, given the following API calls to the GCE API today:
```
+-----------------------+------+-----------------------------------+--------+
| METHOD                | CODE | REASON                            | CNT    |
+-----------------------+------+-----------------------------------+--------+
| compute.routes.insert |  409 | alreadyExists                     | 313335 |
| compute.routes.insert |  403 | usageLimits.rateLimitExceeded     |   1695 |
| compute.routes.insert |  403 | usageLimits.userRateLimitExceeded |   1136 |
| compute.routes.insert |  200 |                                   |   1000 |
+-----------------------+------+-----------------------------------+--------+
```
Note that only the 409 alreadyExists count is steadily increasing; the two rateLimitExceeded were during cluster creation.

Who owns routecontroller?

**Comment by davidopp** [comment]
@cjcullen for routecontroller

**Comment by davidopp** [comment]
I think I found the problem with the route controller.

RouteController.reconcileNodeRoutes() appears to run once every 5s (it actually uses the same flag as the NodeController, NodeSyncPeriod). It calls GCECloud.ListRoutes() which calls gce.service.Routes.List(gce.projectID) but it is just once, not once per node or per route. So I don't think that's a problem. Then it calls reconcile().

reoncile() calls GCECloud.CreateRoute() up to once per node and GCECloud.DeleteRoute() up to once per route. But the route creations and deletions are done in goroutines (one per node and route, respectively), and unless I'm missing something, reconcile() can return before the goroutines finish, which means that reconcileNodeRoutes() can be invoked again before the goroutines finish. As a result, I think that if you create a large burst of nodes (say 100 all at once) and the cloud provider processes route creation requests slowly (for a simple example, say 1 every 5s), then the first call to reconcile() will try to create 100 routes, the next call will try to create 99 routes, the next call will try to create 98 routes, etc., and these are all the same sets of routes (minus the one that actually got created in the previous 5s). If this is the problem, then having reconcile() wait until all the goroutines finish before it returns should fix it.

**Comment by alex-mohr** [comment]
I looked into route controller issues and even with #21663 from @gmarek we were getting a lot of already exists.

The end result is we have two bugs:
- #21663 only guards deletion with a waitgroup, but not creation, which results in a lot of excessive API spam.  That's the cause of the rate limit exceeded -- route creation can take 60s, and running every 10s causes lots of extra traffic and some "already-exists" errors.
- The other issue is in pkg/cloudprovider/provider/gce/gce.go.  The GCE api object we use has a maxResults: 500 (which is the limit for the api call).  Currently we get only 500 routes, see that there should be another 500 that should exist, and try to create those 500.  We need to issue multiple Routes.List calls (and Instance.List and all the other *.List calls for that matter) when the result has a non-empty NextPageToken.  See https://godoc.org/google.golang.org/api/compute/v1#RoutesListCall's PageToken field.

I have some time tomorrow to put some PRs together, but if someone else wants to beat me to it, you're welcome to.

**Comment by alex-mohr** [comment]
Also, because route creation and deletion can take a minute or two, so instead of a waitGroup on a batch of operations, it'd be nice if we had e.g. a concurrentSet object that could keep track of whether an operation is pending on a per-route basis.  That would mean the 10s iteration of routeController could start new operations for not-yet-acted-upon routes more quickly.

**Comment by davidopp** [comment]
> #21663 only guards deletion with a waitgroup, but not creation, which results in a lot of excessive API spam. That's the cause of the rate limit exceeded -- route creation can take 60s, and running every 10s causes lots of extra traffic and some "already-exists" errors.

Oh I'm very sorry, I mentioned both creation and deletion in my comment https://github.com/kubernetes/kubernetes/issues/21561#issuecomment-186772036 but then didn't check to make sure the PR covered both. I'll send out a PR to fix this. Longer-term we can try something more sophisticated like your concurrentSet idea.

It would be great if you have time to take care of the other issue you mentioned (about the GCE api object).

**Comment by wojtek-t** [comment]
Thanks for debugging @alex-mohr !
@davidopp already sent out a PR fixing it; and regarding your idea about concurrentSet - I agree it would be good to do it, but maybe not for 1.2. WDYT?

**Comment by alex-mohr** [comment]
With PR #22094 together with PR #22044 this seems fixed -- thanks!
