### ISSUE TITLE
RESTMapper broken by hpa.autoscaling

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#21568]
The HPA that was registered in autoscaling (https://github.com/kubernetes/kubernetes/pull/20501) only "worked" because of a bug in the `MultiRESTMapper` that chooses winning groups based on the order of package import evaluation.

https://github.com/kubernetes/kubernetes/pull/21272 provides a fix to this problem by allowing ordering, but because of the ambiguity it should merge with https://github.com/kubernetes/kubernetes/pull/20829 .

@lavalamp can you take a look at https://github.com/kubernetes/kubernetes/pull/20829 (assigned to you), so I can combine into one pull and we'll be able to get a working RESTMapper for 1.2?

**Comment by lavalamp** [comment]
will do, thanks.

**Comment by lavalamp** [comment]
We are just waiting for #21272 to get finished up.

**Comment by lavalamp** [comment]
Actually, I'm going to call this a dup of #19941
