### ISSUE TITLE
Distributed CRON jobs in k8s

### ISSUE THREAD

**Issue by jeefy** [kubernetes/kubernetes#2156]
Talked with @brendandburns and @jbeda about this briefly.

Being able to submit a job that fires in the k8s cluster periodically (like Chronos) would be a good feature to offer. Something that mirrors the replicationController (periodicController was @jbeda off the cuff name)

JSON would also be pretty similar (in my mind) as well, mirroring replicationController's, with the addition of a timing attribute and possibly a means to notify output.

Thoughts? (Typing this up quick before I run to a bunch of meetings)

**Comment by smarterclayton** [comment]
@soltysh please link your proposal here once it's more complete

**Comment by soltysh** [comment]
@smarterclayton will do so as soon as I gather some more feedback around that. 

In the meantime I have a question for @jeefy. Given what @smarterclayton proposed with the ability to run in-container commands (eg. using https://github.com/GoogleCloudPlatform/kubernetes/pull/3763) are you convinced on having just one job type which will, similarly to RCs, specify which image to run and the schedule?

**Comment by xudifsd** [comment]
Hi, I'm interested in implementing this as gsoc work, but it seems @soltysh is already doing this, I'm not sure if this still is a gsoc idea?

**Comment by soltysh** [comment]
@xudifsd me and a couple of folks we are currently working on a proposal to drive the discussion in this topic. I can't tell you when exactly the implementation of it will start.

**Comment by bgrant0607** [comment]
@soltysh Does that imply you plan to build it?

@xudifsd Sorry, it's a bit hard to tell what people will start working on.

**Comment by soltysh** [comment]
On Fri, Mar 13, 2015 at 5:44 AM, Brian Grant <notifications@github.com>
wrote:

> @soltysh <https://github.com/soltysh> Does that imply you plan to build
> it?
>
Definitely I'll be one of the implementers.

**Comment by smarterclayton** [comment]
http://queue.acm.org/detail.cfm?id=2745840 A little light reading for the weekend.

**Comment by bgrant0607** [comment]
Thanks for the pointer. Yes, Stepan was TL of our internal cron service.

**Comment by bgrant0607** [comment]
Also worth a look: https://github.com/mesos/chronos

**Comment by davidopp** [comment]
#11980 is implementing a version of this.

**Comment by abevoelker** [comment]
It would be neat if this distributed cron allowed the use of [ISO8601 repeating interval](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals) notation like Chronos uses, because it's impossible to express some types of schedules with cron's limited modulo syntax.

**Comment by jdc2172** [comment]
just wondering if this feature is still in the works

**Comment by soltysh** [comment]
It's still being worked on, unfortunately it didn't meet the 1.3 deadline so it'll sleep into 1.4.

**Comment by eghobo** [comment]
@soltysh: sorry to hear that this feature missed 1.3 ):. do you have any ETA in mind? we have big interest at this feature, how we can help?

**Comment by soltysh** [comment]
@eghobo we're waiting for 1.3 to land and additionally we need to figure out some multi-versioning problems. But the general idea is to have it as soon as possible.

**Comment by SEJeff** [comment]
Not seeing a link to it in this issue, so to help the next person looking, this is fixed in master #24970. It implements the [scheduled job api](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/scheduledjob.md) which seemingly uses a normal crontab style API for job scheduling.

**Comment by soltysh** [comment]
@SEJeff not quite, that PR introduces only the API part. The remaining (not merged yet) parts are tracked in https://github.com/kubernetes/features/issues/19.

**Comment by SEJeff** [comment]
Gotcha, thanks

**Comment by erictune** [comment]
ScheduledJob is alpha in 1.4.
