### ISSUE TITLE
Proposal: Required node selector labels for pod creation

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#21566]
## Problem statement

Sometimes you want to partition your nodes into different pools, because they have different properties. For example, they may have different networking setups, different hardware, or may be owned by different sub-divisions inside an organization. It's common to delineate these features with node labels. And it's common for an organization to have some policies regarding what kind of pods can be scheduled on which pools.

Right now there's no way for a cluster admin to enforce this kind of policies, for two reasons:
1.  If a pod creation request doesn't specify any NodeSelector, the scheduler will happily schedule the pod on any node.
2.  Even if the pod creation specifies NodeSelector to select a pool, there is no way to enforce policies regarding who can use which pool

This proposal aims to solve problem 1, with the assumption that problem 2 can be solved with a more beefed up ABAC solution than the current one.
## Proposed solution

We propose a new admission controller, RequiredNodeSelector. When using this admission controller, the cluster admin will provide a config file, specifying the list of required node selector labels, possibly with default values. It could be something like:

```
requiredNodeSelectorLabels:
  - name: pool
    default: default
  - name: arch  # no default means must explicitly specify
```

The RequiredNodeSelector admission controller will, for each label in `requiredNodeSelectorLabels`, check whether it's present in pod.Spec.NodeSelector.
- if present, the request is left alone
- if not, does the required label has a default?
  - if yes, add `$name=$default` to pod.Spec.NodeSelector
  - if not, deny the request

**Comment by bgrant0607** [comment]
See also #17151, #17097, and https://github.com/kubernetes/kubernetes/blob/master/docs/design/taint-toleration-dedicated.md

cc @davidopp

**Comment by guoshimin** [comment]
The dedicated nodes design doc describes exactly what we need. Any projection on when that will land?

**Comment by quinton-hoole** [comment]
@davidopp for when taints and tolerations lands.

**Comment by davidopp** [comment]
Hopefully will be in 1.3.

**Comment by guoshimin** [comment]
Is there an issue/PR I can follow?

**Comment by davidopp** [comment]
Not yet; the work on it is just starting.  (@kevin-wangzefeng's team at Huawei is working on it.)

**Comment by aveshagarwal** [comment]
There is an existing admission plugin PR with taints/tolerations that does similar https://github.com/kubernetes/kubernetes/pull/30302 .

**Comment by davidopp** [comment]
+1 -- I'm going to close this issue since I think #30302 does cover this use case. @guoshimin please re-open if you disagree. (I see you already thumbs-up'd @aveshagarwal 's comment)

**Comment by bgrant0607** [comment]
Closing since #30302 was merged.
