### ISSUE TITLE
Support 100 pods per node

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#21570]
This is a meta issue for aggregating the TODO items to support 100 pods per node.
 
- [x] change kubelet default parameters to match the new capability
- [x] change how container garbage collection works to ensure we don't leave 200 dead containers lying around when there are only a few pods running (#8347)
- [x] add e2e tests to ensure kubelet can reliably runs 100 (pause) pods per node 
- [x] ensure on a larger cluster (e.g., 100 nodes), the master components can reliably support 100 pods per node.
- [x] investigate adding a rate limiter for docker client to limit the cpu spike in batch container container creation/deletion 
- [x] set RSS memory limits for kubelet/docker in e2e tests
- [ ] update documentations if there are any

/cc @dchen1107

**Comment by yujuhong** [comment]
> investigate adding a rate limiter for docker client to limit the cpu spike in batch container container creation/deletion

We discussed in the team meeting today and decided to punt this. We'll have a better, more well-thought out solution for the next release. For example, we can reserve and limit the resources for kubelet/docker properly, in additional to rate-limiting the docker client. Also, we'll set these resource/qps limits based on the machine size as well.

**Comment by AdoHe** [comment]
@yujuhong I just open a PR #21886 to update the kubelet default parameters, would you mind take a look? I am keeping on this to think about more to do.

**Comment by gmarek** [comment]
I'm waiting for quota increase to run 100pod/node kubemark.

**Comment by dchen1107** [comment]
I am closing this one. Supporting 100 pods (actuall configured with 110 pods) is in release notes, and we are going to document it separately.
