### ISSUE TITLE
PR builder finished running tests, succeeded, didn't post green on PR

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#21575]
For http://pr-test.k8s.io/20833/kubernetes-pull-build-test-e2e-gce/29032/.

In the build-log, I see:

```
Ran 110 of 175 Specs in 949.519 seconds
SUCCESS! -- 110 Passed | 0 Failed | 2 Pending | 63 Skipped 

Ginkgo ran 1 suite in 16m1.581218301s
Test Suite Passed
2016/02/17 13:44:25 e2e.go:305: Step 'Ginkgo tests' finished in 16m2.185932505s
++ exitcode=0
...
```

But in the PR, the line item for **Jenkins GCE e2e** still says "Build started sha1 is merged."

**Comment by ihmccreery** [comment]
(This is all 2 days after the build finished, so this is a hang, not a transient issue of some kind, I think.)

**Comment by ihmccreery** [comment]
Oh, perhaps this is important: that PR's based against `release-1.1`, not `master`.

**Comment by fejta** [comment]
Looks like this needed an lgtm?
