### ISSUE TITLE
kubectl command does not support delete <pod_name> command

### ISSUE THREAD

**Issue by YnR** [kubernetes/kubernetes#21589]
REPRO
deploy pod with name **pod_name** using json description
try to delete pod with `kubectl delete pod_name`

CURRENT
Does not work
Need to run `kubectl delete -f pod_definition_file`

EXPECTED
Deletes the pod with that name

**Comment by AdoHe** [comment]
@YnR have you ever tried this:
```
# Delete pods and services with same names "baz" and "foo"
$ kubectl delete pod,service baz foo
```

**Comment by bgrant0607** [comment]
There are examples in the kubectl help text:
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_delete.md
