### ISSUE TITLE
When deploying new pod to cluster, provide blocking process option to get notified when it is done and where it fails. 

### ISSUE THREAD

**Issue by YnR** [kubernetes/kubernetes#21588]
CURRENT
Run the `kubectl create -f ./pod.json` command (with pod file)

CURRENT
Returns right away, but if not sure if it is done or if something wrong happens
Need to figure out how to inspect the state of the pods e.g. `kubectl get pod [pod_name]` or `kubectl describe pod [pod_name]`
Need to call  `kubectl get services [pod_name]` repeatedly until it is created

EXPECT
Can make the call and keep the thread to receive information about the deployment (when ready, when fails, etc.)

**Comment by ParagDoke** [comment]
+1

**Comment by kargakis** [comment]
You can use `kubectl rollout status` today with Deployments, DaemonSets, and StatefulSets to block until they get deployed. The command can only fail if you have specified ProgressDeadlineSeconds in Deployments and the deadline is exceeded during an upgrade. Eventually we should move ProgressDeadlineSeconds in the rest of the controllers.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-misc

**Comment by guoshimin** [comment]
/reopen

`kubectl rollout status` is woefully underpowered. A lot of times rollouts fail for simple reasons like typos in image names/tags, insufficient resources, or crash loops. If users can be notified of these errors, it's usually easy for them to fix the issues. But as it stands, it takes multiple kubectl commands for them to discover the reason why their rollouts are not progressing, if at all, and it requires them to have certain knowledge about how things work under the cover. It's a big usability issue. In fact in one of my previous employers we developed an in-house tool that did just that. It would be great if the issue can be tackled upstream.
