### ISSUE TITLE
Random pod latency issues - CoreOS/AWS

### ISSUE THREAD

**Issue by l0neranger** [kubernetes/kubernetes#21604]
**OS**: CoreOS
**Env**: AWS - 3 kubelets
**Kubernetes Version**: 1.1.1

**Issue references**: https://github.com/kubernetes/kubernetes/issues/14315, https://github.com/kubernetes/kubernetes/issues/14051

**CC**: @ArtfulCoder @thockin 

This still appears to be a problem in k8s v1.1.1 running on CoreOS/AWS. This has been tested with no resource limits on the SkyDNS and the test pods.

The test I'm running is a bash curl loop -

```
for i in $(seq 1 100); \
do \
curl -o /dev/null -s -w "DNS-Lookup [%{time_namelookup}] Time-Connect [%{time_connect}] Time-PreTransfer [%{time_pretransfer}] Time-StartTransfer [%{time_starttransfer}] Total-Time [%{time_total}]\n" https://www.google.com/ ; \
done
```

And seemingly at random intervals the DNS, SkyDNS in this instance, takes around 5s to respond. The 5s delay is almost always reproducible give or take a few msec. Truncated output with the second line showing the delay -

```
...
DNS-Lookup [0.084] Time-Connect [0.086] Time-PreTransfer [0.106] Time-StartTransfer [0.533] Total-Time [0.533]
DNS-Lookup [5.582] Time-Connect [5.584] Time-PreTransfer [5.602] Time-StartTransfer [6.035] Total-Time [6.035]
DNS-Lookup [0.090] Time-Connect [0.092] Time-PreTransfer [0.106] Time-StartTransfer [0.440] Total-Time [0.440]
DNS-Lookup [0.138] Time-Connect [0.140] Time-PreTransfer [0.191] Time-StartTransfer [0.571] Total-Time [0.571]
DNS-Lookup [0.058] Time-Connect [0.062] Time-PreTransfer [0.098] Time-StartTransfer [0.593] Total-Time [0.593]
...
```

Interestingly this seems to be only from inside a container when talking to SkyDNS. All other cases, including querying SkyDNS from kubelets/master, have no latency issues.

My SkyDNS container has the following config to enabled response cache and rotate between Google and OpenDNS servers to avoid the DNS throttling issue but that doesn't seem to make a dent.

```
        # command = "/skydns"
        - -addr=0.0.0.0:53
        - -domain=fake.domain.
        - -machines=http://127.0.0.1:2379
        - -nameservers=8.8.8.8:53,208.67.222.222:53
        - -ns-rotate=true
        - -rcache=10000
        - -rcache-ttl=30
        - -round-robin=true
        - -rtimeout=1s
```

Interestingly I absolutely can't reproduce this, regardless of the number of retries, trying to use just dig -

```
for i in $(seq 1 100); \
do \
dig google.com | grep "Query time" ; \
dig google.com +tcp | grep "Query time" ; \
done
```

**Comment by ArtfulCoder** [comment]
1. are you using AWS routes v/s flannel or some other network plugin ?
2. are you using kubeproxy in userspace mode or iptables mode ?

3. did you use kube-up to bring up the cluster ?

**Comment by l0neranger** [comment]
@ArtfulCoder 

1. We are using flannel overlay network
2. kube-proxy is in iptables mode
3. No - we did not deploy our clusters using kube-up.sh

**Comment by ArtfulCoder** [comment]
1. can you ping one container from another container on a different host ?
2. Does dns resolution/curl work from a container that is on the same host as skydns ?

**Comment by l0neranger** [comment]
Confirmed.

1. Yes. Tried with from a few different containers and this communication seems to be intact.
2. Yes - both internal and external resolutions with google forwarders works.

**Comment by alph486** [comment]
Also seeing this. We are using 1.1, kube-proxy is in userspace currently, we used kube-up.sh to bring up the cluster.

**Comment by thockin** [comment]
Please try the iptables proxy?

**Comment by alph486** [comment]
Am planning on spinning up a new cluster to try... My time to first byte from a browser --> ELB --> Node --> Service is about 30s... I have heard userspace is slow... having trouble believing it could be THAT slow though?

**Comment by thockin** [comment]
oh, no, that's not right...something else is timing out...

**Comment by alph486** [comment]
@thockin My problems seem to be related to this: https://github.com/kubernetes/kubernetes/issues/11632#issuecomment-125732094 . Early simple tests are showing the problem is resolved, but time and reports of the issue over the next few days will tell.

**Comment by ichekrygin** [comment]
Hi, we see a similar issue with 
- `v1.4.8` 
- `image: gcr.io/google_containers/kubedns-amd64:1.8`
- kube-dns pod count: 8
Running from inside the pod the dns lookup seems to be all over the place
```
DNS-Lookup [0.028] Time-Connect [0.111] Time-PreTransfer [0.281] Time-StartTransfer [0.366] Total-Time [0.366]
DNS-Lookup [0.061] Time-Connect [0.133] Time-PreTransfer [0.283] Time-StartTransfer [0.359] Total-Time [0.359]
DNS-Lookup [0.012] Time-Connect [0.086] Time-PreTransfer [0.237] Time-StartTransfer [0.312] Total-Time [0.312]
DNS-Lookup [0.125] Time-Connect [0.200] Time-PreTransfer [0.353] Time-StartTransfer [0.430] Total-Time [0.431]
DNS-Lookup [0.070] Time-Connect [0.154] Time-PreTransfer [0.325] Time-StartTransfer [0.411] Total-Time [0.413]
DNS-Lookup [0.066] Time-Connect [0.144] Time-PreTransfer [0.306] Time-StartTransfer [0.386] Total-Time [0.386]
DNS-Lookup [0.004] Time-Connect [0.076] Time-PreTransfer [0.225] Time-StartTransfer [0.299] Total-Time [0.299]
```
