### ISSUE TITLE
serve_hostname container exiting immediately

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#21605]
What I'm really trying to say is i haven't figured out why they're sigtermed from the logs (there are really only 2 cadvisor lines inbetween).

https://github.com/kubernetes/kubernetes/pull/21326#issuecomment-186460951
http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce//29493

Failed because one pods in an RC flipped from Running to something else intermittenly:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:272
Expected error:
    <*errors.errorString | 0xc208ac8a90>: {
        s: "1 containers failed which is more than allowed 0",
    }
    1 containers failed which is more than allowed 0
not to have occurred
```

Specifically one pod behind the RC for Service3, mentioned here:
```
STEP: deleting pod execpod in namespace e2e-tests-services-xzftm
STEP: creating service3 in namespace e2e-tests-services-xzftm
STEP: creating service service3 in namespace e2e-tests-services-xzftm
STEP: creating replication controller service3 in namespace e2e-tests-services-xzftm
Feb 19 15:52:01.851: INFO: Created replication controller with name: service3, namespace: e2e-tests-services-xzftm, replica count: 3
Feb 19 15:52:04.851: INFO: service3 Pods: 3 out of 3 created, 3 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady
Feb 19 15:52:04.851: INFO:
```

The pod in question is service3-7byu5, and we see from the events that it went through an extra Create/Delete loop:
```
Feb 19 15:52:05.079: INFO: event for service3-7byu5: {kubelet e2e-gce-master-1-minion-qcpx} Created: Created container with docker id 5b9ddc340ac9
Feb 19 15:52:05.079: INFO: event for service3-7byu5: {kubelet e2e-gce-master-1-minion-qcpx} Started: Started container with docker id 5b9ddc340ac9
Feb 19 15:52:05.079: INFO: event for service3-7byu5: {kubelet e2e-gce-master-1-minion-qcpx} Created: Created container with docker id f498adfc39b2
Feb 19 15:52:05.079: INFO: event for service3-7byu5: {kubelet e2e-gce-master-1-minion-qcpx} Started: Started container with docker id f498adfc39b2
Feb 19 15:52:05.079: INFO: event for service3-fm4im: {default-scheduler } Scheduled: Successfully assigned service3-fm4im to e2e-gce-master-1-minion-y0z7
Feb 19 15:52:05.079: INFO: event for service3-fm4im: {kubelet e2e-gce-master-1-minion-y0z7} Pulled: Container image "gcr.io/google_containers/serve_hostna
```

Looking through kubelet logs on e2e-gce-master-1-minion-qcpx (104.197.123.109): 
https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/pr-logs/pull/21326/kubernetes-pull-build-test-e2e-gce/29493/artifacts/104.197.123.109%3A22-kubelet.log

```
I0219 23:52:02.530452    3421 server.go:587] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-services-xzftm", Name:"service3-7byu5", UID:"c567a1af-d763-11e5-b46a-42010af00002", APIVersion:"v1", ResourceVersion:"8122", FieldPath:"spec.containers{service3}"}): type: 'Normal' reason: 'Created' Created container with docker id 5b9ddc340ac9
I0219 23:52:02.657493    3421 server.go:587] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-services-xzftm", Name:"service3-7byu5", UID:"c567a1af-d763-11e5-b46a-42010af00002", APIVersion:"v1", ResourceVersion:"8122", FieldPath:"spec.containers{service3}"}): type: 'Normal' reason: 'Started' Started container with docker id 5b9ddc340ac9
I0219 23:52:02.658341    3421 factory.go:78] Using factory "docker" for container "/5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a"
I0219 23:52:02.662407    3421 manager.go:799] Added container: "/5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a" (aliases: [k8s_service3.37cd3a0d_service3-7byu5_e2e-tests-services-xzftm_c567a1af-d763-11e5-b46a-42010af00002_b4a137ab 5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a], namespace: "docker")
I0219 23:52:02.663114    3421 handler.go:320] Added event &{/5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a 2016-02-19 23:52:02.465452292 +0000 UTC containerCreation {<nil>}}
I0219 23:52:02.663169    3421 container.go:386] Start housekeeping for container "/5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a"
I0219 23:52:02.705016    3421 manager.go:852] Destroyed container: "/5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a" (aliases: [k8s_service3.37cd3a0d_service3-7byu5_e2e-tests-services-xzftm_c567a1af-d763-11e5-b46a-42010af00002_b4a137ab 5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a], namespace: "docker")
I0219 23:52:02.705085    3421 handler.go:320] Added event &{/5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a 2016-02-19 23:52:02.705056864 +0000 UTC containerDeletion {<nil>}}
I0219 23:52:02.967740    3421 manager.go:308] Container inspect result: {ID:5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a Created:2016-02-19 23:52:02.465452292 +0000 UTC Path:/serve_hostname Args:[] Config:0xc20908a000 State:{Running:false Paused:false Restarting:false OOMKilled:false Pid:0 ExitCode:2 Error: StartedAt:2016-02-19 23:52:02.656658207 +0000 UTC FinishedAt:2016-02-19 23:52:02.715915198 +0000 UTC} Image:00619279d4083019321e4865829a65a550a23c677d76cbb44274ade0d92ca7a9 Node:<nil> NetworkSettings:0xc20879e000 SysInitPath: ResolvConfPath:/var/lib/docker/containers/937c2668c892f7510d9ed91cb0440fa4d4993a34188b4fab3422d88ec36a65f2/resolv.conf HostnamePath:/var/lib/docker/containers/937c2668c892f7510d9ed91cb0440fa4d4993a34188b4fab3422d88ec36a65f2/hostname HostsPath:/var/lib/kubelet/pods/c567a1af-d763-11e5-b46a-42010af00002/etc-hosts LogPath:/var/lib/docker/containers/5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a/5b9ddc340ac93f2523ad79516d97300cd76ff970ddafeb50a1fca7b2a9d1a51a-json.log Name:/k8s_service3.37cd3a0d_service3-7byu5_e2e-tests-services-xzftm_c567a1af-d763-11e5-b46a-42010af00002_b4a137ab Driver:aufs Mounts:[{Name: Source:/var/lib/kubelet/pods/c567a1af-d763-11e5-b46a-42010af00002/volumes/kubernetes.io~secret/default-token-mnwvq Destination:/var/run/secrets/kubernetes.io/serviceaccount Driver: Mode:ro RW:false} {Name: Source:/var/lib/kubelet/pods/c567a1af-d763-11e5-b46a-42010af00002/etc-hosts Destination:/etc/hosts Driver: Mode: RW:true} {Name: Source:/var/lib/kubelet/pods/c567a1af-d763-11e5-b46a-42010af00002/containers/service3/b4a137ab Destination:/dev/termination-log Driver: Mode: RW:true}] Volumes:map[] VolumesRW:map[] HostConfig:0xc208e58b00 ExecIDs:[] RestartCount:0 AppArmorProfile:}
```

Most importantly note that the last container inspect result has an ExitCode of 2, which corresponds to the code emitted when a sigterm is sent to the serve_hostname process in the pod. You can confirm this by:
```
$ docker run -d gcr.io/google_containers/serve_hostname:1.2
$ docker exec -it hash sh
container $ ./serve_hostname --port=8084
container $ kill serve_hostname_pid
container $ echo $?
```

**Comment by lavalamp** [comment]
@dchen1107 to delegate

**Comment by bprashanth** [comment]
This potentially also happened on https://github.com/kubernetes/kubernetes/issues/21803 (didn't want to sink time into parsing logs once again, but that bug has a brief summary)

**Comment by dchen1107** [comment]
@pwittrock Can you take a look at this one?

**Comment by pwittrock** [comment]
Yes I will take a look

**Comment by pwittrock** [comment]
I spent some time looking through the logs today with Vish, and wasn't able to find anything too helpful.  I managed to get an exit code of 2 by passing invalid arguments as well (not sending a sigterm).  The  kubelet sees that the container exists ~50ms, which is pretty quick.  I think the best way to proceed is to add some debug output to the serve_hostname image to try to capture what is going on.

**Comment by bprashanth** [comment]
> I spent some time looking through the logs today with Vish, and wasn't able to find anything too helpful. I managed to get an exit code of 2 by passing invalid arguments as well (not sending a sigterm)

I'm suspicious of the container exiting with wrong args theory, because we send the same args to the same container in every test. But we can start by adding clarity.

**Comment by pwittrock** [comment]
I doubt it is the args, but am wondering if there are other things that could cause the container to exit with status 2 besides sigterm.

**Comment by pwittrock** [comment]
Immediately killing the container with docker gives the same result in similar time (50ms)
`docker run --name s1 -d gcr.io/google_containers/serve_hostname:1.2; docker stop s1`

>
"State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 2,
            "Error": "",
            "StartedAt": "2016-02-26T01:29:51.318236382Z",
            "FinishedAt": "2016-02-26T01:29:51.378123131Z"
        },

**Comment by bprashanth** [comment]
Yeah that's because docker stop sends a sigterm, waits for 10s by default, then sends a sigkill :)

**Comment by pwittrock** [comment]
I think the next step then should be to try to verify that docker is stopping the container, and the kubelet is telling it to.  The attached docker logs don't log when docker tries to stop/start containers, so may be increasing the verbosity level of the docker daemon to "debug" and adding V(3) info lines to the kubelet when it stops containers would be appropriate.

**Comment by pwittrock** [comment]
Following up on this, it looks like go panics on SIGTERM, and the exitcode 2 is from the panic.  I have verified this by adding a panic("DONE") to serve_hostname.go and it exits 2 immediately.

I have a PR to add a signal handle to serve_hostname that should tell us if it is indeed getting a SIGTERM, or panicing for some other reason.  kubernetes/contrib#529

**Comment by pwittrock** [comment]
bumped the version to 1.4.  Is there a way to query gcr.io to see what tags exist for an image?

**Comment by bprashanth** [comment]
@pwittrock thanks for the contrib pr

**Comment by pwittrock** [comment]
@bprashanth my pleasure

Pull #22443 to move serve_hostname into the kubernetes/kubernetes repo from contrib

**Comment by pwittrock** [comment]
PR #22443 pending accepting non-1.2 PRs into master.

**Comment by pwittrock** [comment]
#23293 #23289

**Comment by pwittrock** [comment]
Debug info has been added to the serve_hostname container and test output.  Closing for now.  Please reopen when we see this again and can investigate further.
