### ISSUE TITLE
Examples: Deploying Clusters - Redis listed twice

### ISSUE THREAD

**Issue by andyhky** [kubernetes/kubernetes#21619]
CLA is inbound.

Minor nit with the Examples TOC listing- redis was listed twice.

Diff is prepared here:

https://github.com/kubernetes/kubernetes/compare/gh-pages...andyhky:redis_dupe?expand=1

**Comment by fabioy** [comment]
Please make it into a pull request, else it can't be reviewed or merged. Closing this issue.
