### ISSUE TITLE
The servicecontroller loop is racy

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21625]
In pkg/controller/service/servicecontroller.go, we start 10 goroutines that process service events: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L139-L141

Each of these workers then locks on a per-service mutex when processing events: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L225-L228

But I believe there is no guarantee that the order of lock acquisition is the same as the order of events.  Thus I think we might process events out of order when services change rapidly.

An alternative design might be to have a per-service goroutine with a per-service event queue.  This would mean that service events would be guaranteed to be processed in order.  It would also make caching of the previous state much simpler.  Finally, when we hit an error like a failure to create a LoadBalancer, we could simply sleep without risking exhausting our "thread pool".

**Comment by justinsb** [comment]
I'd love for us to at least triage this to consider whether we should address it in 1.2

**Comment by AdoHe** [comment]
@justinsb just like kubelet, per pod per pod worker, easy to reason about, but we have to take care about the load, under big cluster, there may be many services.

**Comment by justinsb** [comment]
@AdoHe right - I'd say we should make sure it's correct before worrying about scalability of goroutines.  Not that we won't have to worry about it, just maybe not yet! The code may actually be correct & I might be missing a trick though.

**Comment by AdoHe** [comment]
@justinsb you are right we have to make sure it's correct before worrying about scalability of goroutines. Will we address this in 1.2? I am happy to offer some help if need.

**Comment by thockin** [comment]
Any help proving there is a problem would be useful to help prioritize.  @AdoHe if you have any bandwidth at all, go for it.  Mission #1: convince ourselves that there is an actual problem or document why not.

**Comment by justinsb** [comment]
From the user's log (I don't think there's anything secret in here...):

```
E0220 21:00:26.205601       1 servicecontroller.go:187] Failed to process service delta. Retrying: Failed to create load balancer for service kube-system/kubedash: InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.
    status code: 409, request id: f705192d-d814-11e5-ac5e-f119f1542d21
I0220 21:00:26.789398       1 aws_loadbalancer.go:50] Creating load balancer with name: a6f809bfcca2d11e581350a7769f923d
E0220 21:00:27.090195       1 servicecontroller.go:187] Failed to process service delta. Retrying: Failed to create load balancer for service kube-system/kubedash: Throttling: Rate exceeded
    status code: 400, request id: f7ac0749-d814-11e5-b6fa-5126063012a3
I0220 21:00:27.743317       1 aws_loadbalancer.go:50] Creating load balancer with name: a6f809bfcca2d11e581350a7769f923d
E0220 21:00:28.113412       1 servicecontroller.go:187] Failed to process service delta. Retrying: Failed to create load balancer for service kube-system/kubedash: Throttling: Rate exceeded
    status code: 400, request id: f84847ad-d814-11e5-b3d3-ed4223eb7ce4
I0220 21:00:28.697279       1 aws_loadbalancer.go:50] Creating load balancer with name: a6f809bfcca2d11e581350a7769f923d
E0220 21:00:29.036503       1 servicecontroller.go:187] Failed to process service delta. Retrying: Failed to create load balancer for service kube-system/kubedash: Throttling: Rate exceeded
```

This was triggered by an AWS CoreOS 1.1.7 configuration where the user had two subnets (in the same AZ), but hadn't tagged anything with a KubernetesCluster tag, so AWS was rejecting the call.  (I believe we've actually remedied this in 1.2)  But any persistent problem with ELB creation should trigger the same problem.  For example, I suspect that if you create as many ELBs as your quota allows, and then try to create another, ELB creation will fail, we will rapidly retry and your AWS account will hit rate limits within a few minutes, locking your whole account.

In 1.2 I've just added a "delay of last resort" so this won't happen any more, though we don't want to rely on it - it inserts synchronous delays into all AWS calls once it sees AWS resource limits being hit.

I think this was one of the major causes of all the AWS rate limit problems we've been hitting.  (The other being volumes).

**Comment by justinsb** [comment]
Sorry, commented on the wrong issue.  I'm going to delete the above comment.

**Comment by bprashanth** [comment]
@adohe @justinsb this has evolved into 2 issues:    

1. Races in the current code. The easiest solution of course is to just drop the parallelism to 1. The delta fifo should always give us the latest update and everything should work out OK.

2. Rewriting the service controller. We shouldn't use the kubelet pattern IMO because we don't care about instantaneous response when a container dies (which is the rationale behind podworkers). We should use the same pattern we use in the RC manager and the Ingress controller (which does exactly this: watch and reconcile the kubernetes api with cloud resources). I'd be happy to help get this through design/review etc in the 1.3 timeframe. 

If either of you can help with 2, please file a spin off bug for next-milestone so we don't forget about it.

**Comment by ncdc** [comment]
Have we determined if there actually are races or not?

**Comment by AdoHe** [comment]
@ncdc I am doing test to determine whether there are actually races.

**Comment by a-robinson** [comment]
Yeah, I can almost guarantee you that it's racy. Rewriting it to use a similar pattern as the other controllers would be nice for maintainability, as long as the fact that its operations take much longer than, for example, the replication controller's do doesn't make the pattern incompatible.

In the meantime, I believe #19879 should help reduce the raciness. I've let it slip onto the back burner, but I'll get it rebased, and can @bprashanth or @cjcullen review it?

**Comment by bprashanth** [comment]
I'll try to get to it by end of week. @justinsb or anyone else with cycles, feel free to leave comments in the meanwhile.

**Comment by bgrant0607** [comment]
Is this really a release blocker? I don't see any activity.

**Comment by bprashanth** [comment]
Clearing 1.2 mileston since we put in a mitigation https://github.com/kubernetes/kubernetes/pull/22069 and have a failsafe backoff so things don't go completely awry https://github.com/kubernetes/kubernetes/pull/21982.

**Comment by a-robinson** [comment]
Not a release blocker. I'd actually claim that this is completely resolved by #22069, since any reordering of events gets sorted out by getting the current state from the apiserver.

**Comment by justinsb** [comment]
Agreed - this should be fixed now.  We could probably fix them better if we weren't under the constraints of a pending release - do you think we should look at this whole controller again in 1.3?

**Comment by bprashanth** [comment]
Yes, it's a question of bandwidth :)
I'm willing to help review/debug but most likely won't get the time to re-write it. We should probably start with a help-wanted bug, if there isn't one already.

**Comment by justinsb** [comment]
Oh absolutely, I just meant we should make sure we have a tracking issue to revisit in 1.3 or later.  What we've got into 1.2 is great & a huge improvement.

**Comment by mfanjie** [comment]
@bprashanth @justinsb @a-robinson seems the fix in 1.2 is not a long term solution, so want to check if there is anyone working on rewrite the logic to apply the pattern like other controllers? I am working on federation service controller now, and same logic would be applied.

**Comment by bprashanth** [comment]
If you have the bandwidth, help would be appreciated. I'm not re-writing it any time soon.

**Comment by mfanjie** [comment]
okey, then I am going to work on this.

**Comment by thockin** [comment]
Awesome!
