### ISSUE TITLE
AWS: Volume attachment/detachment requires polling of DescribeVolume

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21623]
See comment here: https://github.com/kubernetes/kubernetes/issues/12121#issuecomment-186665825

It would sure be nice to find a way of doing this that doesn't hit our AWS API quota.  For example, looking at the disk state.  Now that we've harmonized with GCE maybe we can do this.

**Comment by justinsb** [comment]
It's not great, but we haven't had any problem reports so moving to 1.4

Also there doesn't appear to be an easy way.

**Comment by matchstick** [comment]
This might be fixed in 1.3.4 can you try again?

**Comment by pwittrock** [comment]
@justinsb I am moving this out of the blocking issues we are tracking for the 1.4 release.  If there is still 1.4 work to be done here, move it back and provide daily updates to this issue.

**Comment by saad-ali** [comment]
@justinsb ok with punting this to 1.5?

**Comment by justinsb** [comment]
Absolutely ... moved to 1.5

**Comment by dims** [comment]
@justinsb @saad-ali ok with punting this to 1.6? :)

**Comment by justinsb** [comment]
I actually propose closing, in that it is aspirational.  If we observe the problem, we can fix at that time.  I think there's actually a separate issue that might have hit it which I re-found in my triage yesterday, in which case we can track there: #31858
