### ISSUE TITLE
Please provide a feedback mechanism on kubernetes.io --> github.com/kubernetes/kubernetes

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/kubernetes#21635]
I may be missing something (!) but, when I wish to file bugs against kubernetes.io, instead of a "Click here to submit feedback", I'm resorting to Googling a section of text on the kubernetes.io to find the relevant page on github in order to reference the github content for github issues!

E.g.
From here:
http://kubernetes.io/v1.1/docs/user-guide/connecting-applications.html#securing-the-service

Must Google to help find this:
https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/connecting-applications.md#securing-the-service

From here:
http://kubernetes.io/v1.1/examples/https-nginx/README.html

Must Google to help find this:
https://github.com/kubernetes/kubernetes/blob/release-1.1/examples/https-nginx/README.md

Recommend providing a feedback feature that facilitates submitting bugs against kubenetes.io pages by either auto-referencing or facilitating finding the reference on the github page.

Alternatively, do you just accept kubernetes.io references in github issues?

**Comment by thockin** [comment]
@johndmulhausen

**Comment by bgrant0607** [comment]
Every page now has "I wish this page ..." at the bottom.

**Comment by DazWilkin** [comment]
Awesome! Thank you
