### ISSUE TITLE
Assumptions in "Securing the Service" no longer hold

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/kubernetes#21631]
Learning more Kubernetes, I wanted to follow the documentation through "Securing the Service". This example references another and opaquely, this second reference references code that is broken :-(

http://kubernetes.io/v1.1/docs/user-guide/connecting-applications.html#securing-the-service

https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/connecting-applications.md#securing-the-service

The page references "Nginx https service":

http://kubernetes.io/v1.1/examples/https-nginx/README.html

https://github.com/kubernetes/kubernetes/blob/release-1.1/examples/https-nginx/README.md

Which provides instructions on generating the secret. It was not immediately obvious from the page that there's an assumption that the reader will have downloaded Kubernetes/examples sources.

make keys secret KEY=/tmp/nginx.key CERT=/tmp/nginx.crt SECRET=/tmp/secret.json

After attempting and failing to download/build the sources, I believe that this script no longer works:

https://github.com/kubernetes/kubernetes/issues/14558

I'll break the issue into separate issues, since, by fixing the make, the "Nginx https service" will be fixed (https://github.com/kubernetes/kubernetes/issues/21633). However, I wasted quite some (free time) to realize this mistake and was blocked for some time.

Ironically, I found generate-secrets-from-file on the following page and, through grokking this and the make_secret.go file, I was able to muddle through and create a secret.json file for Kubernetes.

https://tectonic.com/enterprise/docs/latest/deployer/tls.html

Recommend:

Add documentation that explicitly documents (separately) how to generate a Kubernetes secret from self-signed certificates.

Please add (if there's not already) an easier way to submit bugs against kubernetes.io by helping the reader reference the github source directly. I googled for duplicates to find the correct github page.

It's challenging in documentation but please be mindful of introducing nested assumptions to do this, do this, which requires doing this..... as, if any part of the chain fails...

**Comment by bgrant0607** [comment]
cc @bprashanth

**Comment by bprashanth** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/issues/21633
The example was fixed a while back
