### ISSUE TITLE
https-nginx example can clarify secrets/cert generation step

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/kubernetes#21633]
Had started on a page that references this page. Have filed an issue against the parent but part of its resolution involves fixing this page too:

https://github.com/kubernetes/kubernetes/issues/21631

The page:

http://kubernetes.io/v1.1/examples/https-nginx/README.html

https://github.com/kubernetes/kubernetes/blob/release-1.1/examples/https-nginx/README.md

Provides instructions on generating a secret. It was not immediately obvious from this page (I linked directly to it to a 1. Download/build the code, 2. You should have a "make" command....) that there's an assumption that the reader will have downloaded Kubernetes/examples sources. The make command obviously won't work as the correct "make" command won't exist:

make keys secret KEY=/tmp/nginx.key CERT=/tmp/nginx.crt SECRET=/tmp/secret.json

After attempting and failing to download/build the sources, I believe that this script no longer works:
#14558

Ironically, I found generate-secrets-from-file on the following page and, through grokking this and the make_secret.go file, I was able to muddle through and create a secret.json file for Kubernetes.

https://tectonic.com/enterprise/docs/latest/deployer/tls.html

Recommend:

Add documentation that explicitly documents (separately) how to generate a Kuberenetes secret from self-signed certificates.

Please add (if there's not already) an easier way to submit bugs against kubernetes.io by helping the reader reference the github source directly. I googled for duplicates to find the correct github page.

**Comment by bprashanth** [comment]
>make keys secret KEY=/tmp/nginx.key CERT=/tmp/nginx.crt SECRET=/tmp/secret.json
After attempting and failing to download/build the sources, I believe that this script no longer works:
#14558

It works, I just tried it. the issue you mentioned has the fix. 


> Recommend:
Add documentation that explicitly documents (separately) how to generate a Kuberenetes secret from self-signed certificates.

If you can contribute, I believe this would be a lot more useful:https://github.com/kubernetes/kubernetes/issues/20176

Eitherway, creating a secret should be easy, you just need to base64 encode it. make secret just does this through a go client. Having this in the nginx-https example is convenient because 90% of the people coming to one are going to want the other. I also think a generic "Secrets" example that walks the reader through different types of secrets makes sense. 

> Provides instructions on generating a secret. It was not immediately obvious from this page (I linked directly to it to a 1. Download/build the code, 2. You should have a "make" command....) that there's an assumption that the reader will have downloaded Kubernetes/examples sources. The make command obviously won't work as the correct "make" command won't exist:

We should clarify this in the doc. Please send a pr if you have time.

**Comment by DazWilkin** [comment]
Thanks for your prompt response.

You are correct. I am able to get make to work to generate the secret.

However, in order to do so (and perhaps this is where I'm confused) I had to build a copy of Kubernetes and then install mercurial to install godep:

http://kubernetes.io/v1.1/docs/getting-started-guides/binary_release.html
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md

All I really wanted to do was run the https-nginx example.

What I'm unable to find is instructions for the downloading just the examples or, better yet, just the https-nginx example that the referring page took me to. I'm using GKE and so don't need everything else.

If this is the only|correct way, I'll submit a separate issue which would be a request to provide instructions for standalone example(s) creation.

With regards the simplicity of generating the secret, the challenge is that, while is easy for you, it's not obvious to me :-).

I wanted to use your go code as the manifestation of your expertise but I'm unfamiliar with Go and Kubernetes and was not able to infer the code's behavior (not understanding the APIs it uses) from a cursory read.

https://github.com/kubernetes/kubernetes/issues/20176 would be very helpful!

I'm happy to send a PR. Perhaps you can help me by clarifying whether the examples can be treated standalone?

Thank you for your help.
