### ISSUE TITLE
apiserver was unable to write a JSON response: Internal error occurred:

### ISSUE THREAD

**Issue by g0194776** [kubernetes/kubernetes#21643]
Hi guys,

```
  I've gotten an error after I updated the Kubernetes to the version of "Kubernetes-1.2.0-0.6.alpha1.git8632732.el7.x86_64". When I deleted the Pods of what I specified the RC automatically helps me create the new Pods. About 1 minute later, the recent Pods of RC created still being the state of "Pending".

  I've checked the logs of Kubernetes API-SERVER and getting what I listed at below:
```

> Feb 21 05:13:47 localhost.localdomain kube-apiserver[1774]: W0221 05:13:47.245943    1774 controller.go:290] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default  84ea6c44-d311-11e5-89a6-000c29d6fa13 8 0 2016-02-14 03:53:10 -0800 PST <nil> <nil> map[] map[]} [{[{192.168.38.129 <nil>}] [] [{https 6443 TCP}]}]}
> Feb 21 05:13:47 localhost.localdomain kube-apiserver[1774]: I0221 05:13:47.253309    1774 server.go:622] Serving securely on 0.0.0.0:6443
> Feb 21 05:13:47 localhost.localdomain kube-apiserver[1774]: I0221 05:13:47.787366    1774 server.go:634] Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)
> Feb 21 05:13:47 localhost.localdomain kube-apiserver[1774]: I0221 05:13:47.788568    1774 server.go:664] Serving insecurely on 127.0.0.1:8080
> Feb 21 05:13:47 localhost.localdomain systemd[1]: Started Kubernetes API Server.
> Feb 21 05:17:17 localhost.localdomain kube-apiserver[1774]: E0221 05:17:17.622525    1774 apiserver.go:440] apiserver was unable to write a JSON response: Internal error occurred: Pod "redis-slave-wjt7l" in namespace "default" : pod is not in 'Running', 'Succeeded' or 'Failed' state - State: "Pending"
> Feb 21 05:17:52 localhost.localdomain kube-apiserver[1774]: E0221 05:17:52.655605    1774 apiserver.go:440] apiserver was unable to write a JSON response: Internal error occurred: Pod "redis-slave-bzrtu" in namespace "default" : pod is not in 'Running', 'Succeeded' or 'Failed' state - State: "Pending"
> Feb 21 05:20:28 localhost.localdomain kube-apiserver[1774]: E0221 05:20:28.917423    1774 apiserver.go:440] apiserver was unable to write a JSON response: Internal error occurred: Pod "redis-slave-bzrtu" in namespace "default" : pod is not in 'Running', 'Succeeded' or 'Failed' state - State: "Pending"

```
 Is there anyone can tell me whether is or not that the current Kubernetes version which I used is unstable? 
```

thanks a lot,
Kevin Yang.

**Comment by fabioy** [comment]
That build seems to be pretty old. v1.2 is currently at alpha8: https://github.com/kubernetes/kubernetes/releases/tag/v1.2.0-alpha.8

Can you try again with a newer build?

**Comment by g0194776** [comment]
Okay, thanks a lot.
I am going to try it on the next Monday.

**Comment by xrow** [comment]
Hi,

 we have the same issue. The issue is that a pending pod doesn`t get deleted. After sending a termination command the pod gets status "Terminating", the error shows in the log and the pod doesn`t get deleted.

I can`t try a new version since it is not yet available for centos 7.

```
Mar 31 14:00:48 admin01 kube-apiserver: E0331 14:00:48.855351    8551 apiserver.go:440] apiserver was unable to write a JSON response: Internal error occurred: Pod "jenkins-5dmsq" in namespace "kube-system" : pod is not in 'Running', 'Succeeded' or 'Failed' state - State: "Pending"
```

```
[root@admin01 ~]# yum info kubernetes
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.de.leaseweb.net
 * epel: ftp.nluug.nl
 * extras: mirror.cuegee.de
 * updates: ftp.hosteurope.de
Installed Packages
Name        : kubernetes
Arch        : x86_64
Version     : 1.2.0
Release     : 0.6.alpha1.git8632732.el7
Size        : 0.0  
Repo        : installed
From repo   : extras
Summary     : Container cluster management
URL         : k8s.io/kubernetes
License     : ASL 2.0
Description : Container cluster management
```

**Comment by g0194776** [comment]
@xrow 
Yep, As you said, That is a BUG on the last version of the official CentOS 7 repo in the Kubernetes.
