### ISSUE TITLE
Proposal: First-generation of `kubectl set *` commands

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#21648]
For 1.3 we'll be considering adding a number of commands developed upstream in OpenShift into kubectl - specifically, commands that assist the user in performing very common mutations to our core objects.

Current implementations are:
- Adding or removing volumes from an object with a pod template
- Adding or removing environment variables from an object with a pod template
- Adding or removing liveness and readiness probes from objects with a pod template.

As proposed in https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/deploy.md#kubectl-set, these commands would live under `kubectl set` and operate generically on classes of objects (for the commands above, they would operate on objects with mutable pod templates, for other commands, more generic structure should be possible).

The commands would take as input a JSON/YAML file, a real object on the server, or a synthetic resource generated by looking at multiple server resources, transform the object, and create a patch on the original object that results in the desired mutation.  The patch would be applied to the object and then the object mutated on the server.

It should be possible to specify `-o yaml` and generate a file that can be chained to later commands, for instance:

```
kubectl set volume -f deployment.yaml --add --claim-name=foo -o yaml | kubectl set probe --liveness --get-url=https://foo.bar -o yaml | kubectl apply -f -
```

We need to ensure the usability of chaining (both apply, patch, replace, and create are all viable terminations) as part of this work.

In practice, we have found it valuable to have the default mode for the set commands to "list" the current state in a pattern that enables users to guess at what they need to do to change the field.  Mutation via CLI flags is hard - each flag must be carefully chosen to balance ease of comprehension with ability to express most of the API.  It is acceptable to punt some use cases in mutation to the `edit` command.  Most commands should focus on having a "clear" or "remove" flag that can remove a targeted entry, a simple set of flags that set the default values, and where possible try to support the minimum amount of simultaneous change.

Set commands should have a consistent code pattern to make implementing new setters easy.  As much as possible, it should be able to take an existing set command, define a business transformation (adding X to Y) and map that to existing code that is tested in a standard way, following https://github.com/kubernetes/kubernetes/blob/master/docs/devel/kubectl-conventions.md#command-implementation-conventions.

OpenShift implementations of the various commands need varying levels of cleanup:
- `oc set env` is the oldest of the downstream implementations and does not support downward API flags at the current time.  However, it is tuned very well to make adding and removing structured variables easy.  https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/set/env.go
- `oc set volumes` is the most complex of the commands today - given the number of volumes we have a choice was made to focus on the most common (claims, empty dir, secrets) and force users to patch other commands.  Helpers were added to make creating a claim and adding it to a template very easy.  https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/set/volume.go
- `oc set probe` is brand new and formalizes some of the more recent kubectl behaviors into a set of core library methods (specifically, iteratively patching a set of objects) as well as handling the transformation pattern cleanly.  https://github.com/openshift/origin/pull/7331
- `oc set triggers` represents a command that exposes a generic interface across two similar, but not identical concepts (build and deployment triggers, which result in a mutation of the object based on external stimulus).  It is the most complex because the underlying API is dissimilar, but tries to present a common and simple pattern to users.  It explicitly does not handle setting multiple triggers of certain types at a time as an 80% use case solution.  https://github.com/openshift/origin/pull/7423

| Subcommand | PR # | Assignee |
| --- | --- | --- |
| \- [x] image | #25509 | @janetkuo |
| \- [x] selector | #38966 | @kargakis |
| \- [x] serviceaccount | #48432 | @chandanmad |
| \- [x] env | #50998 | @zjj2wry |
| \- [ ] probe | #52243 | @zjj2wry |
| \- [ ] volume |  |  |
| \- [x] resources | #27206 | @JacobTanenbaum |
| \- [ ] security |  |  |
| \- [ ] port |  #51947  |  @zjj2wry  |

**Comment by bgrant0607** [comment]
cc @janetkuo

**Comment by bgrant0607** [comment]
This sounds pretty good to me, though we might want to break some of the volume functionality into multiple commands.

I'd like `set image`, which would achieve the equivalent of `rolling-update --image` when used with Deployment.

Can we chain `kubectl labels` and `kubectl annotations` in this way today, or could they be extended to do so?

Nit: I might prefer `--dry-run` to indicate the mutation shouldn't actually be performed rather than `-o yaml`. I view `-o yaml` as just indicating that yaml is requested rather than json.

Even if edit supports reading from stdin, we may want a --edit flag for these and other mutators/generators.

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by bgrant0607** [comment]
@ncdc I didn't see this on your 1.3 list. Should it be on the list?

**Comment by janetkuo** [comment]
> Can we chain `kubectl labels` and `kubectl annotations` in this way today, or could they be extended to do so?

Yes we can chain `kubectl label` and `kubectl annotate` with -o yaml.

**Comment by ncdc** [comment]
@bgrant0607 it wasn't originally, but I will discuss it with my team and see if we can fit it in.

**Comment by bgrant0607** [comment]
We need at least `kubectl set image`. cc @janetkuo @pwittrock

**Comment by smarterclayton** [comment]
So here's a concrete proposal before I start moving code upstream.

Implement the two most valuable primitives - `set image` and one other (`env`?) as a first step, setting up the proper pattern for these commands.  Then fan out to the others.

**Comment by kargakis** [comment]
sgtm

**Comment by janetkuo** [comment]
Is anyone planning to work / already working on this?

**Comment by smarterclayton** [comment]
I've got probe and env in a branch.  Volumes is more involved, because
it's not as simple.

Some points raised by folks:

* users want to see the current env or probes.  The commands today
under set handle that (oc set env rc/bar prints the env vars in bash
form).  There was discussion about having another command show that,
but all the possible locations had trade offs
* some folks felt using "set X" to remove something was unintuitive
and suggested "unset X".  My concern there is that it scatters
commands across two hierarchies and reduces discoverability (and some
commands may not have an unset).  Label and annotate today combine set
and unset
* for complex commands, like volume, there are enough flags that
splitting the command was reasonable - except that led to "oc set
volume add|remove" which could be redundant (or the previous
discussion about unset)

Will post some examples.

**Comment by janetkuo** [comment]
I'll start working on `kubectl set image`.

**Comment by smarterclayton** [comment]
I'll do probe - probably the least controversial, and the most recent

On May 10, 2016, at 7:52 PM, Janet Kuo <notifications@github.com> wrote:

I'll start working on kubectl set image.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/21648#issuecomment-218325522>

**Comment by smarterclayton** [comment]
PR for probe is https://github.com/kubernetes/kubernetes/pull/25451

**Comment by deads2k** [comment]
Any chance of having `kubectl set <foo>` take `-f -` so I could do things like `kubectl convert -f foo | kubectl set probe -f - --dry-run > new-file.yaml`?

**Comment by smarterclayton** [comment]
It should take -f.  I think all set commands should.

**Comment by deads2k** [comment]
> It should take -f.  I think all set commands should.

Yeah, but I want to actually use the input object, not parse the name out and retrieve the server version of that object.  Any chance of that instead of the behavior of `-f ` for delete or patch?

**Comment by smarterclayton** [comment]
Yeah, although we might have to make it a different flag.  Agree I want to
be able to mutate objects locally.

**Comment by janetkuo** [comment]
PR for `kubectl set image`: #25509

**Comment by JacobTanenbaum** [comment]
I can start working on `kubectl set limits` to set resource requests/limits.

**Comment by ymqytw** [comment]
I'm using this to keep tracking the progress of all the `kubectl set` subcommands

| Subcommand  |  PR #     |  Assignee | 
|---|---|---|---|
| - [x] image                | #25509 | @janetkuo 
| - [ ] env               |               | 
| - [ ] probe             | #25451 | @smarterclayton 
| - [ ] volume         |               | 
| - [ ] limits              | #27206  | @JacobTanenbaum
| - [ ] security          |               | 
| - [ ] port             |               | 
| - [ ] trigger        |                |

**Comment by pwittrock** [comment]
@monopole This might be a good place to get started

**Comment by bgrant0607** [comment]
@smarterclayton @fabianofranz @pwittrock @kubernetes/sig-cli-feature-requests 

What is the status of this? I think having tooling that could modify Kubernetes resource manifests locally would be very useful, in conjunction with kubectl apply.

For example, I would like to use `kubectl set image` to update an on-disk Deployment's image.

In the past, we've had a number of problems with this kind of flow:
* Round-tripping of the resources (#3955) loses information in the case of version skew between kubectl and the modified resource manifest.
* Encoding creates crufty configurations, with fields like creationTimestamp and status, fields with default values, etc.
* I see many issues filed related to dry-run (original issue was #11488, but many others recently). 
* I've heard of issues with export, also (e.g., #41880)

It looks like set image does a patch, at least:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/set/set_image.go

Though the abstraction of the pod template could be improved, to work with extensions and third-party controllers:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory_client_access.go#L219

My proposal of creating a template subresource (#170) wouldn't work in this case. :-(  We'd need to use the OpenAPI schema description, or something.

**Comment by smarterclayton** [comment]
Yeah, pod template today in OpenShift is fairly complete and is
https://github.com/openshift/origin/blob/master/pkg/api/meta/pods.go, but
needs to be server driven.

With OpenAPI we can identify known types for the struct if they have the
standard name, or we can add an extension on the struct that identifies it
as following a certain role (`x-kubernetes-role=api/core/v1/PodTemplate` or
similar).

These mutation functions are useful for task based actions for sure.

**Comment by bgrant0607** [comment]
cc @alexandercampbell

**Comment by zjj2wry** [comment]
@smarterclayton seems interesting for this. can i have a go for ```kubectl set env```?

**Comment by kargakis** [comment]
@zjj2wry yes, please, here is the downstream implementation of the command, it will be helpful.

https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/set/env.go

**Comment by zjj2wry** [comment]
@kargakis nice, thank you very much 😊

**Comment by bgrant0607** [comment]
configmap set command: #24049

**Comment by zjj2wry** [comment]
@smarterclayton i am working with set probe and lifecycle. it is helpful for user.

**Comment by zjj2wry** [comment]
@mengqiy can you help add my name in `port` , i add ```kubectl set port``` command in pr #51947 ,thank you very much

**Comment by kargakis** [comment]
@zjj2wry done

**Comment by mengqiy** [comment]
> @mengqiy can you help add my name in port , i add kubectl set port command in pr #51947 ,thank you very much

Done.

**Comment by WanLinghao** [comment]
@smarterclayton i am working with set volume

**Comment by shiywang** [comment]
@mengqiy @kargakis I would like to pick up the last `security` if no one already did.

**Comment by ericchiang** [comment]
PR for `set volume` is here: https://github.com/kubernetes/kubernetes/pull/54284

I was assigned but don't have much background. Maybe someone on this thread would be interested in reviewing?
