### ISSUE TITLE
AWS: Add configurable source range for LoadBalancers

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21651]
The equivalent of #21431

**Comment by bprashanth** [comment]
@freehan fyi

**Comment by thockin** [comment]
Is anyone working on this?  I don't know that it should be a release blocker if nobody is owning it.

To do this, we should probably change "net.beta.kubernetes.io/gce-source-ranges" to "service.beta.kubernetes.io/load-balancer-source-ranges" so it is not GCE specific.  @freehan we should probably make that change, anyway, for clarity.

**Comment by justinsb** [comment]
I hope I can get to it if nobody else has bandwidth.

**Comment by davidopp** [comment]
Can we close this? Looks like the PR was merged but then there were a bunch of comments after it was merged.

**Comment by justinsb** [comment]
Not for AWS, it wasn't done AFAIK.

**Comment by thockin** [comment]
I will circle back to this PR today, if it is ready for re-review

**Comment by thockin** [comment]
Justin,

Why did we close this?  Did something happen?  I thought we really wanted this in?

**Comment by thockin** [comment]
Nevermind, I am looking at the issue, not the PR
