### ISSUE TITLE
Create 'kubectl undrain' as an alias for 'kubectl uncordon' ?

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#21653]
It's non-intuitive that the opposite of 'kubectl drain' is 'kubectl uncordon'. Should we create a 'kubectl undrain' that is an alias for 'kubectl uncordon'? My only concern would be that people might assume undrain will move the pods that were running on that machine prior to the drain, back onto that machine.

cc/ @mml

**Comment by mml** [comment]
Has someone actually complained?  I don't know that anybody actually *expects* `unfoo` to exist, and the docs for drain explicitly point you to `uncordon`.

**Comment by gmcquillan** [comment]
I just had to look it up...

**Comment by mml** [comment]
@gmcquillan Fair enough.  If you send a patch I'm happy to review.

**Comment by gmcquillan** [comment]
Deal.

**Comment by AntonOfTheWoods** [comment]
@mml , I'm guessing it's far too late to complain now? I certainly expected it to exist, and thought it strange that it didn't...

**Comment by mml** [comment]
@AntonOfTheWoods I'm no longer working on k8s, but I suspect if you wanted to reopen this issue and find a willing reviewer from sig-cli, a patch would probably be accepted.
