### ISSUE TITLE
Quota error formats memory as milli-bytes

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#21654]
Re-running my demo for quota.  The error I get when I ask for `4.1Gi` is:

```
Error from server: error when creating "./quota/pod1.yaml": pods "quota-demo-large" is forbidden: [memory quota is 4Gi, current usage is 0, requesting 4402341478400m., cpu quota is 4, current usage is 0, requesting 4100m.]
```

4100m CPU makes sense, but formatting memory as milli-bytes is pretty silly.

@sdminonne @lavalamp

**Comment by sdminonne** [comment]
:)  @thockin. Having a look and let you know

**Comment by lavalamp** [comment]
Why did you ask for milli-bytes, then? 4.1Gi = 4.1*2^30 = 4402341478.4 :)

**Comment by thockin** [comment]
I thought we had a notion of max-precision, but I guess I should STFU and
eat my words :)

**Comment by sdminonne** [comment]
You asked 4.1Gi and quota reports 4402341478400m. We all agree that is the same value but why not in Kb then?

**Comment by thockin** [comment]
It would be nice to know that, for some resources, units less than 1 are
nonsense.  I am not sure how hard that will be (I suspect not worthwhile).
It's less-than-ideal from a UX point of view.  Maybe we should allow some
small number of decimal places if they are a perfect fir for right-sizing a
quanitity.  4.1G is MUCH friendlier than 4402341478400m or even 4402341478
(assuming the extra 0.4 bytes doesn't matter :)).
