### ISSUE TITLE
Draining Node for Planned Maintenance/Cluster Scaling Down Proposal

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#21679]
Draining Node for Planned Maintenance/Cluster Scaling Down Proposal
---

#### Motivation
----
1. Bringing an individual node or a batch of nodes down for planned maintenance is a common administrative task, to for example install a Service Pack or hardware upgrades.
2. If we have a large cluster, but with low resource usage rate, and Pods just spreading on all nodes, we want to drain some nodes so they could be recycled. 

#### Design
----
```
type NodeDrain struct {
    unversioned.TypeMeta `json:",inline"`
    api.ObjectMeta       `json:"metadata,omitempty"`

    // Specification of the desired behavior of the NodeDrain.
    Spec NodeDrainSpec `json:"spec,omitempty"`

    // Most recently observed status of the NodeDrain.
    Status NodeDrainStatus `json:"status,omitempty"`
}

type NodeDrainType string

const (
	MaintenanceNodeDrainType NodeDrainType = "Maintenance"
	ScalingDownNodeDrainType NodeDrainType = "ScalingDown"
)

type NodeDrainSpec struct {
	// Type of NodeDrain. Can be "Maintenance" or "ScalingDown".
	Type NodeDrainType `json:"type,omitempty"`

	Maintenance *MaintenanceNodeDrain `json:"maintenance,omitempty"`

	ScalingDown *ScalingDownNodeDrain `json:"scalingDown,omitempty"`

	// Minimum number of seconds for which a rescheduled pod should be ready
    // without any of its container crashing, for it to be considered available.
    // Defaults to 0 (pod will be considered available as soon as it is ready)
    MinReadySeconds int `json:"minReadySeconds,omitempty"`

    // The maximum number of pods that can be unavailable during the rescheduling.
    // Value must be percentage of total pods belongs to the same ReplicationController/ReplicaSet(ex: 10%)
    MaxUnavailable intstr.IntOrString `json:"maxUnavailable,omitempty"`
}

type MaintenanceNodeDrain struct {
 	// target nodes that will be drained
    TargetNodeSelector  NodeSelector `json:"targetNodeSelector,omitempty"`
}

type ScalingDownNodeDrain struct {
	//strategy of draining
	Strategy ScalingDownStrategy `json:"strategy,omitempty"`
	// prefer to drain nodes that satisfy PreferredNodeSelector, if ScalingDownStrategy is "PreferredNodeFirst"
    // nil pointer indicates no preference
    PreferredNodeSelector *NodeSelector `json:"preferredNodeSelector,omitempty"`

	// Target number of the cluster nodes that will be drained
	// nil pointer indicates draining nodes as many as possible
	TargetDrainingNodeNum  *int `json:"targetDrainingNodeNum,omitempty"`
	// max retry num 
	MaxRetryNum int `json:"maxRetryNum,omitempty"`
}

type ScalingDownStrategy string

const(
	PreferredNodeFirst ScalingDownStrategy = "PreferredNodeFirst"
	FewestPodNodeFirst ScalingDownStrategy = "FewestPodNodeFirst"
	FewestNonReplicatedPodNodeFirst ScalingDownStrategy = "FewestNonReplicatedPodNodeFirst"
	LowestLoadNodeFirst ScalingDownStrategy = "LowestLoadNodeFirst"
)

type NodeDrainStatus struct {

}
```

#### Implementation
---
1) MaintenanceNodeDrainType
* first, mark the target nodes(nodes that satisfy `TargetNodeSelector`) as "Unschedulable"
* delete all pods on the target nodes, guarantee that there are at most MaxUnavailable pods which belongs to the same
ReplicationController/ReplicaSet been deleted at the same time. 
* if the remaining resource of cluster is insufficient, node draining will fialed due to time out.
2) ScalingDownNodeDrainType
```
sort nodes based on drain.ScalingDownStrategy first 

for conut := 0; count < drain.MaxRetryNum; count++ {
	num := 0
	for _, node := range nodes {
		a) mark node as "Unschedulable";
		b) delete all pods on node, guarantee that there are at most MaxUnavailable pods which belongs to the same ReplicationController/ReplicaSet been deleted at the same time;
		if b) succeed {
			num++
		} else {
			remark node as "Schedulable";
		}

		if drain.TargetDrainingNodeNum != nil && num == drain.TargetDrainingNodeNum {
			return NodeDrainingSucceeded
		}
	}
}

return NodeDrainingFailed

```

**Comment by mqliang** [comment]
@mml @davidopp

**Comment by davidopp** [comment]
Thanks for your thoughts on this. We'll take a look after the 1.2 push is finished.

**Comment by davidopp** [comment]
Hi @mqliang . I took a quick look at what you've done here, and I think it is actually a proposal for (at least part of) moving `kubectl drain` to the server (something hypothesized in #17393). One quick comment I'd make is that I think we want the constraints on the impact on the pod (like `MaxUnavailable`) to be specified in a separate object (see #12611) so that it can be used to limit disruptions due to multiple causes (node drain, cluster scale-down, moving pods onto empty nodes resulting from cluster scale-up, scheduler preemption, etc.)

**Comment by mml** [comment]
@mqliang how much flexibility do you need when specifying `MaxUnavailable`?  For example, is it sufficient to specify a single flag cluster-wide, like `10%`, such that during all operations like this we'll never go below 90% available for each daemon set's or replication controller's pods?

**Comment by mqliang** [comment]
@mml 
A single flag cluster-wide may be not reasonable, since different Pod may have different availability requirements. So usually, I think user should check the Pods on the Nodes first, and set the `MaxUnavailable` value.

**Comment by mqliang** [comment]
Close this in flavour of https://github.com/kubernetes/kubernetes/pull/17393
