### ISSUE TITLE
Headless services fail validation if targetPort is set

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#21682]
In 1.0 and 1.1, headless services that specified a mismatched port/targetPort were tolerated (the targetPort was ignored).

https://github.com/kubernetes/kubernetes/pull/17862#issuecomment-186666199 tightened validation to reject these services. That causes problems when upgrading from currently-working clusters.

**Comment by liggitt** [comment]
1.2 candidate to avoid breaking backwards compatibility

**Comment by thockin** [comment]
oh hell.  Yeah.  I don't think this is worth a breaking change.  We should either roll that back ASAP or change it to nuke any user-provided value and replace it with the `port` value.  I think the latter is potentially dangerous and also not worth the risk, so I think we should rollback #17862 and just update the docs for targetPort.

@feihujiang objections?

**Comment by thockin** [comment]
Who has time to do this?  It doesn't look like an auto-rollback is doable.

**Comment by liggitt** [comment]
Already opened a PR in https://github.com/kubernetes/kubernetes/issues/21680

**Comment by feihujiang** [comment]
Yes, I agree this isn't worth a breaking change, But could we give an warning log that targetPort isn't equal to port and would be ignored?

**Comment by liggitt** [comment]
There's no facility in validation for warning. I don't think spamming the server log in response to API requests is that helpful here

**Comment by feihujiang** [comment]
Yes, that sounds reasonable. I just think that targetPort was ignored is a little unfriendly to user.
