### ISSUE TITLE
We should sanitize mountPath

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21681]
A user made an error setting their mountPath - they set a docker-style mountpath `mountPath: /data/ldap/db:/var/lib/ldap`

However, the error that they got (and inspection of the code) indicates that we just passed that straight through to docker (`API error (500): invalid mode for volumes-from: /var/lib/ldap`).  Docker treats the 3rd argument as a mode flag.

We should sanitize the input, both to help users when they make mistakes, but also because if Docker allowed other options in its mounts this could become a security issue.

**Comment by thockin** [comment]
Docker doesn't have a way to specify colons in paths (unless they have fixed it and I didn't notice), so we should probably also reject colons, even though it is broken and wrong.

**Comment by ncdc** [comment]
This doesn't sound like a regression. Is it strictly required for 1.2 or could it wait for 1.3?

**Comment by thockin** [comment]
demoting to P2, even though there is a PR in flight

**Comment by pmorie** [comment]
I'm sorry for being late to the party here, but I am glad that this didn't slip through the cracks, thanks a lot for pointing this out.
