### ISSUE TITLE
ElasticSearch should be backed by persistent volumes

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21691]
Now that our PV support is greatly improved, we should see whether it is now possible to back ES with persistent volumes.  Not having PVs makes it too easy to ES to get into a weird state when it loses the leader.

**Comment by spiffxp** [comment]
/sig instrumentation
I'm assuming sig-instrumentation owns https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch
