### ISSUE TITLE
Prioritized pods (ubernetes)

### ISSUE THREAD

**Issue by juanjoperl** [kubernetes/kubernetes#21705]
For a possible workaround to the problem of federation, can kubernetes have this behabour?: the ability the services have several sets of labels to select pods. The first set would be the priority, the second come into play if the priority pods do not respond, and so on.
With this capability, could have pods tagged area, and the services have sorted priority areas

**Comment by thockin** [comment]
That implies support for this sort of priority at the load-balancers, which I don't think is a broad-enough feature to be a core part of the system.  Or maybe I don't understand the suggestion?

**Comment by juanjoperl** [comment]
Forgiveness because I am newcomer to kubernetes. My question arises from some days when I read the documentation.

My need is to have two centers, with a few tens of milliseconds of latency between them, and I would like to have a single cluster. I know the future existence of Ubernetes but I was wondering if a partial solution to the current kubernetes be possible. I think my choice would focus on Kube-proxy, so it does not round-robin is applied, but the proxy is driven by labels: round robin over label priority pods, and go to another labeled pods if there is a fault.

nodeA1 --> label_Azone                   
nodeA2 --> label_Azone                   
nodeB1---> label_Bzone
nodeB2---> label_Bzone

rc of podX_A --> label_Azone, select node label_Azone   (X=redis by example)
rc of podX_B --> label_Bzone, select node label_Bzone

serviceX_A  --> select pod [label_Azone,label_Bzone]
serviceX_B  --> select pod [label_Bzone,label_Azone]

Not knowing in depth Kubernetes not know if you meant external load balancers or type of service called "LoadBalancer", or perhaps both are the same. I think than modify the kube-proxy all is ok, is this right?

Another option (I´m thinking, sorry) could be that the rolling is performed taking into account the latency, that is, the number of requests to a pod is inversely proportional to the ratio of latencies that are from one node to the set of pods. It would be transparent to users (only set service.spec.sessionAffinity to "latency").

Thank you for this project, which I found great.

**Comment by thockin** [comment]
> My need is to have two centers, with a few tens of milliseconds of latency between them, and I would like to have a single cluster. I know the future existence of Ubernetes but I was wondering if a partial solution to the current kubernetes be possible. I think my choice would focus on Kube-proxy, so it does not round-robin is applied, but the proxy is driven by labels: round robin over label priority pods, and go to another labeled pods if there is a fault.
>
> nodeA1 --> label_Azone
>
> nodeA2 --> label_Azone
>
> nodeB1---> label_Bzone
> nodeB2---> label_Bzone
>
> rc of podX_A --> label_Azone, select node label_Azone (X=redis by example)
> rc of podX_B --> label_Bzone, select node label_Bzone
>
> serviceX_A --> select pod [label_Azone,label_Bzone]
> serviceX_B --> select pod [label_Bzone,label_Azone]

Got it.  We do not have that capability in kube-proxy right now,
though as Ubernetes Lite rolls out, it might start to matter
(@quinton-hoole @justinsb).  The kube-proxy (as of 1.2) is pretty dumb
and doesn't really know whether a backend is "up" or not.  It's just a
VIP.  We *could* start to bias traffic to zone-local backends, but
we'd have to talk about the heuristic to use.

In other words, traffic that hits a node in Zone A would always choose
a backend in zone A unless no backends are Ready, in which case it
would choose a backend in zone B.  Or maybe s/always/usually/ ?

> Another option (I´m thinking, sorry) could be that the rolling is performed taking into account the latency, that is, the number of requests to a pod is inversely proportional to the ratio of latencies that are from one node to the set of pods. It would be transparent to users (only set service.spec.sessionAffinity to "latency").
>
> Thank you for this project, which I found great.

We don't really have latency numbers.

**Comment by quinton-hoole** [comment]
@thockin @juanjoperl See also docs/design/federated-services.md in #19313 (sorry, it's not merged yet).  The solution proposed there involves using DNS and multiple A records with client failover rather than trying to magic away the distinction between different latency zones. Feel free to comment on the above PR if you have better ideas or disagree with the approach proposed there.

**Comment by quinton-hoole** [comment]
To be clear, by "magic away" I was referring to having a single IP address for all clients, that somehow dynamically redirects to the closest, non-overloaded, fully functional pod (by some definition of all of those terms) for every possible client.  Building that complexity into kube-proxy is, in my opinion, prone to undesirable mass failures.  I agree with Tim's implied desire to keep kube-proxy as simple as possible to reduce the probability of really bad failure scenarios.

**Comment by juanjoperl** [comment]
@thockin @quinton-hoole I read the information you said. As expected it is a plan that makes you want to have it already in place.

Regarding load metrics that are mentioned in the document for load balancing, it may not be so necessary to have pods with the ability to auto-scaling and Auto reset. I guess it would be for lower loads than loads that trigger these actions, is it ?.Is in this point kubernetes similar as ubernetes?.

**Comment by quinton-hoole** [comment]
@juanjoperl We have no active work under way yet to add proximity or load-based balancing to Kubernetes/kube-proxy, but if anyone wants to add it, I would suggest that be consistent with what's described in the above doc for Ubernetes.

**Comment by thockin** [comment]
We could make this a more dynamic thing where the default is "equal balance
across all pods, ignoring load or zone" but a non-realtime process could
get stats (somehow, out of scope) and feed us clues about weights.

**Comment by quinton-hoole** [comment]
@thockin yes, that's covered in the above doc, BTW.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#40.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
