### ISSUE TITLE
Cluster logging support for rkt

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#21702]
Currently, kubernetes uses fluentd to read and export docker logs. The logs are json files which have been symlinked to `/var/log/containers/*.log`[1]

As rkt pods save logs as journal files under the pod's directory, in order for the fluentd to work for rkt pods, we need to make it understand the journal log files. We might need to symlink the log files under `/var/log/containers/` as well to apply necessary tags

@kubernetes/sig-node 
@jonboulle @sjpotter

@vishh IIRC, you have some plans of changing the current logging mechanism, if so, how would that look like? Do you have any designs already?

[1] https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.8/pkg/kubelet/dockertools/manager.go#L1477

**Comment by vishh** [comment]
For the short-term, is it possible to configure fluentd to ingest logs from
journald?

**Comment by yifan-gu** [comment]
@vishh There is a [journald plugins for fluentd](https://github.com/reevoo/fluent-plugin-systemd)
Will try that out.

**Comment by yujuhong** [comment]
> For the short-term, is it possible to configure fluentd to ingest logs from
> journald?

Does that mean `kubectl logs` won't work? We'll need more documentation in this case.

**Comment by vishh** [comment]
No kubectl logs will translate to an equivalent command on rkt, which I
believe works already. This is specific to cluster level logging.

**Comment by therc** [comment]
This is similar to running kube-apiserver & co. on CoreOS. They all store their logs in journald, while the fluentd image looks for /var/log/kube-apiserver.log, etc. So you end up with no logs at all. One way to solve this would be to stream the output of journalctl from everything and retain only entries with either kube-* or rkt container logs. Otherwise you need to run one plugin per log type, which I assume to be more expensive.

**Comment by philips** [comment]
cc @colhom as you setup fluentd on our prod CoreOS cluster.

**Comment by yifan-gu** [comment]
Moving to 1.1 as no one is actively working on this today.

**Comment by colhom** [comment]
@yifan-gu i would much prefer to have rkt output to journald with well-defined/selectable metadata, and not have the kubelet do the symlinking dance to expose individual container logs.

We could filter the container log streams out on retrieval and use something like [journalbeat](https://github.com/mheese/journalbeat) to ship the logs out.

**Comment by yifan-gu** [comment]
@colhom What metadata you need?

**Comment by colhom** [comment]
@yifan-gu the same metadata that is currently encoded in the `/var/log/containers/*.log` files. Container name, namespace, etc

**Comment by yujuhong** [comment]
Closing this since relevant issues should be handled by CIR or moved to the rktlet repo
