### ISSUE TITLE
All Trusty GCE e2e jobs failing due to moved ENV variable definitions

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/kubernetes#21707]
They all started to fail on Feb 19th with the error of `bash: line 102: KUBERNETES_PROVIDER: unbound variable`. Seems to have been caused by #21524 that moved environment variable definitions to job configs, which did it for all jobs but Trusty GCE jobs. I was pulling my hair out trying to get it fixed, but there are many pieces moved from/into branches, so I'd lean on @spxtr to help out. :smile: 

/cc @andyzheng0831

**Comment by andyzheng0831** [comment]
I see there is a PR #21708 sent out for review by @spxtr. Is that PR able to fix this issue, or there is additional work to do?

**Comment by spxtr** [comment]
That should fix it. It was a small mistake on my end that led to calling the master-branch e2e script instead of that on release-1.1, where the trusty configs live.

**Comment by andyzheng0831** [comment]
OK. So I leave it to you, or you can reassign the issue to you. I don't have permission for reassignment.
