### ISSUE TITLE
kubernetes-e2e-gke failed after upgrading to latest gcloud package

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#21712]
Since 12:30pm today, kubernetes-e2-gke started to fail after upgrading to the latest gcloud packages

For example, http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/1531/consoleFull

This blocks our merge-bot too. 

cc/ @ihmccreery

**Comment by jlowdermilk** [comment]
The above link isn't a gcloud failure. The cluster failed to create in the 30min time limit, possibly due to transient networking problems in us-central1-f.

**Comment by jlowdermilk** [comment]
Last 3 runs are green, so this was a transient problem.
