### ISSUE TITLE
integration flake: In hack/test-cmd.sh, get unexpected frontend pod

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#21716]
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21713/kubernetes-pull-test-unit-integration/15643/?debugUI=CLOUD
```
I0222 14:50:43.494360    9763 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"frontend", UID:"b32e8642-d9b6-11e5-ba54-0242ac110002", APIVersion:"v1", ResourceVersion:"1033", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: frontend-9i1jc
replicationcontroller "frontend" deleted
I0222 14:50:43.915532    9763 replication_controller.go:422] Replication Controller has been deleted default/frontend
horizontalpodautoscaler "frontend" deleted

FAIL!
Get pods {{range.items}}{{.metadata.name}}:{{end}}
  Expected: 
  Got:      frontend-9i1jc:
(B
711 ./hack/test-cmd.sh
(B
!!! Error in ./hack/test-cmd.sh:51
  'return 1' exited with status 1
```

Looks like in `hack/test-cmd.sh` L707, pod frontend-9i1jc hasn't been deleted by `kubectl delete rc,hpa frontend "${kube_flags[@]}"` before we check that no pod exists. Maybe it's related to delete grace period.

cc @caesarxuchao

**Comment by caesarxuchao** [comment]
Could you try if adding `--grace-period=0` to the cleanup command fix the flake?

**Comment by janetkuo** [comment]
> Could you try if adding `--grace-period=0` to the cleanup command fix the flake?

@caesarxuchao Thanks, this should work. Will add this to all delete in hack/test-cmd.sh.

**Comment by caesarxuchao** [comment]
Just in case you don't already know, --grace-period=0 only works for pods.

**Comment by janetkuo** [comment]
@caesarxuchao I thought grace-period also works for other resources such as deployments, jobs, replicasets since it's referenced in their reaper? Is it not the case?

```go
func (reaper *DeploymentReaper) Stop(namespace, name string, timeout time.Duration, gracePeriod *api.DeleteOptions) error {
...
	return deployments.Delete(name, gracePeriod)
}
```
```go
func (c *deployments) Delete(name string, options *api.DeleteOptions) error {
	return c.client.Delete().Namespace(c.ns).Resource("deployments").Name(name).Body(options).Do().Error()
}
```

**Comment by janetkuo** [comment]
Per in-person discussion with @caesarxuchao, `--grace-period` doesn't work for `kubectl delete rc` or `hpa`, so adding it to `kubectl delete rc,hpa frontend "${kube_flags[@]}"` won't fix this flake. 

After this delete command, rc reaper should scale rc down to 0 so there should be no pods. A temp fix will be to add `kubectl delete pods --all` after this line to clean up potential remaining pods. However, the root cause is still not clear.

**Comment by janetkuo** [comment]
Un-assigning myself to fix other e2e test flakes first.

**Comment by lavalamp** [comment]
Can't you change the default by setting a field in the pod's metadata? (In the template in the RC/Job/deployment/etc.)

**Comment by caesarxuchao** [comment]
Thanks @lavalamp, I think set the [TerminationGracePeriodSeconds](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1204) to 0 would work. @janetkuo do you want to do this?

**Comment by janetkuo** [comment]
Thanks I'll submit the fix.

**Comment by caesarxuchao** [comment]
I might be wrong. `TerminationGracePeriodSeconds` probably only affects the grace period given by kubelet to the target container, but doesn't affect when the pod is deleted from etcd. Let me double check.

**Comment by caesarxuchao** [comment]
Sorry, it looks I'm wrong. We should set [DeletionGracePeriodSeconds](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L122) to 0.

**Comment by janetkuo** [comment]
@caesarxuchao is #22418 going to address this?

**Comment by janetkuo** [comment]
This is happening again in #22384.

**Comment by caesarxuchao** [comment]
#22418 shouldn't affect this issue.

**Comment by bgrant0607** [comment]
We should delete hpa first, so it doesn't might the rc reaper.

**Comment by bgrant0607** [comment]
fight

**Comment by bgrant0607** [comment]
```
I0303 12:24:34.488964   12618 horizontal.go:248] Successfull rescale of frontend, old size: 0, new size: 1
I0303 12:24:34.500904   12618 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"namespace24", Name:"frontend", UID:"f0ad96c9-e17d-11e5-a56c-0242ac110003", APIVersion:"v1", ResourceVersion:"1189", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: frontend-rfm3w
I0303 12:24:35.121711   12618 replication_controller.go:500] Replication Controller has been deleted namespace24/frontend
```

**Comment by janetkuo** [comment]
Filed #22466
