### ISSUE TITLE
AWS support for docker 1.9.1 workarounds

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21731]
We need an AWS equivalent to #21727 and #21703

It might be that systemd doesn't have the same problems, because it properly tracks when processes are running, though it seems more likely that the AWS testing has not yet been thorough enough to find these problems.

**Comment by justinsb** [comment]
cc @dchen1107

**Comment by justinsb** [comment]
This might be as simple as creating a script mirroring the GCE workarounds, and then adding it to the docker systemd manifest with ExecStartPre=.  We already replace the Docker manifest...

**Comment by davidopp** [comment]
@justinsb Do you have an update on this?

**Comment by justinsb** [comment]
Just testing the PR now :-)
