### ISSUE TITLE
"Running Kubernetes locally via Docker" should address services opening ports on node's public IP

### ISSUE THREAD

**Issue by jumpkick** [kubernetes/kubernetes#21735]
The stated objective of [Running Kubernetes locally via Docker](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker.md) is to setup a **single node** Kubernetes cluster using Docker.

The instructions do produce a functioning installation on a single node via hyperKube.  

However, every service that is exposed for internal communication inside the single node is also made available on the node's public IP address (they are exposed because multi-node clusters would use those ports for load balancing) directly with no protection.   

In the case these instructions were followed on an internet facing server, kubernetes-master, skydns, cadvisor, and any database services could be attacked directly.  This makes for a very poor security posture.

Ideally, the instructions should mention a method of limiting the node's public ports to those used to administer the machine (i.e. ssh) + those allowed by the Kubernetes Ingress rules (i.e. a Ingress/LB controller on a designated port like http/80 or https/443).

At the very least, there should be a big fat warning on this document advising people not to use it on a server not behind a firewall for the reason outlined above.

**Comment by bprashanth** [comment]
I agree we should follow best practices. I think the installation assumes the same things as say, apt-get install nginx does, but in this case some services are created for free and they might expose system information when the user didn't intend to. @fgrzadkowski

**Comment by jumpkick** [comment]
@bprashanth in the case of something like MySQL when apt-get installs it on Ubuntu, by default only local unix socket connections are allowed.   A administrator must reconfigure it to bind remote tcp ports/addresses.

When folks build docker images they most certainly override that behaviour to make service accessible on tcp 3306, as IP communication is needed for a database container to be at all useful to other containers.   As soon as port 3306 is bound, running a kubernetes expose makes that port remotely accessible on on the Node's public IP port, which could be very bad.

**Comment by thockin** [comment]
We should probably audit the master components, the kubelet, and the kube-proxy for assumptions of "listening on all interfaces" and find a consistent way to express what interfaces the user really wants.  This has come up a few times and we tend to forget that nodes with one NIC on public internet are not that uncommon.

**Comment by jumpkick** [comment]
It looks like without something like guilhem's patch from #21070 to the way kube-proxy to add --bind-address were going to be stuck.

**Comment by bgrant0607** [comment]
cc @dlorenc @vishh @pwittrock
