### ISSUE TITLE
cluster/kube-push.sh fails

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#21746]
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/developer-guides/vagrant.md

I have a running cluster in vagrant, had to make some code changes and push back but `cluster/kube-push.sh` fails with:
```
$ ./cluster/kube-push.sh 
Updating cluster using provider: vagrant
./cluster/../cluster/../cluster/vagrant/util.sh: line 165: KUBE_BEARER_TOKEN: unbound variable
```

**Comment by kargakis** [comment]
cc: @derekwaynecarr

**Comment by derekwaynecarr** [comment]
Adding to queue of vagrant stuff to look at tomorrow.

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/21972
