### ISSUE TITLE
KubeletManagedEtcHosts [It] should test kubelet managed /etc/hosts file 

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#21755]
Observed during: 

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21043/kubernetes-pull-build-test-e2e-gce/29860/

```
Feb 22 15:36:09.661: FAIL: /etc/hosts file should be kubelet managed, but is not: "10.245.5.7\ttest-pod\n127.0.0.1\tlocalhost\n::1\tlocalhost ip6-localhost ip6-loopback\nfe00::0\tip6-localnet\nff00::0\tip6-mcastprefix\nff02::1\tip6-allnodes\nff02::2\tip6-allrouters\n"
[AfterEach] KubeletManagedEtcHosts
```

**Comment by lavalamp** [comment]
@dchen1107 to delegate

**Comment by ncdc** [comment]
This might have been caused by Paul's (not yet merged) PR; we're investigating.

**Comment by DirectXMan12** [comment]
I've reproduced with Paul's branch as well, and the problem seems to go away when part of the change is undone, so it looks like that's the cause.

**Comment by pmorie** [comment]
Yep, this is due to a problem with my PR.  I'll close this issue out.
