### ISSUE TITLE
Need more clarifications on Kubernetes on Mesos HA setup

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#21761]
Kubernetes HA setup in standalone mode is well explained where there are multiple api servers, but only one instance of scheduler and controller manager running at any instance in time. A process called podmaster will use etcd backend to elect a leader where the scheduler and controller manager will be running.

However, in the case of Kubernetes-on-Mesos, this is more complicated (and not well documented). There's some documentation here: https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/docs/ha.md, but for folks who are more familiar with running Kubernetes in standalone mode, it feels a bit different. K8sm scheduler could run in `--ha` mode by itself, but not the k8sm controller manager? IMO, the generic solution of using podmaster to manage HA for both scheduler and controller manager seems like a better way to go. At least the documentation should offer the podmaster-based HA setup as an alternative. 

One other thing that is different between K8s and K8sm in HA is executorID. In a mesos cluster, there could be multiple frameworks running at the same time, and even multiple Kubernetes instances (e.g., different versions). Thus, one should not mix up executor used by different frameworks, but this introduces some complications that make HA setup in K8sm more different to get right. In the documentation I linked above, it was mentioned that `--km-path` need to be identical for all schedulers. Its importance needs to be stressed more as without it multiple schedulers running in HA mode would generate different executorIDs and not be able to work together correctly and resulting in cryptic "declined incompatible offer..." error messages.

I'd be interested to enrich the current HA documentation to also include the Kubernetes-native approach (i.e., using podmaster) to achieve HA in K8sm. Also after getting the K8sm HA cluster working, I feel some more meaningful error messages would be extremely helpful to sysadmins who might not be as familiar with the K8s and K8sm code base.

**Comment by huang195** [comment]
@sttts @jdef I'd be interested to take on this work. Is this something of interest?

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/787

**Comment by jdef** [comment]
I don't think anyone on the k8s-mesos team has explored podmaster yet. A point of conflict may be that podmaster has one process to elect leaders, and the k8s-mesos scheduler HA has another. I have no idea what's involved in using k8s podmaster, or what the guarantees are re: split-brain scenarios.

If podmaster is an external controller (it runs outside of the master binaries), then it might be pretty straight-forward. If it runs internally, then there's probably some code changes required.

There's also a new leader election API (requires go code changes in order to use) that recently landed in k8s:  https://github.com/kubernetes/kubernetes/blob/80ff0cbbda4418ab40a383e08ab6f55244219e52/pkg/client/leaderelection/leaderelection.go

Having a better HA story is something we're definitely interested in - we'd be happy to accept contributions here.

**Comment by huang195** [comment]
@jdef thanks for the pointers on the related works. It seems that the Mesos team has taken a slightly different approach from Kubernetes when trying to address HA. Kubernetes in HA mode has only 1 scheduler + 1 controller manager running at any time. However Kubernetes-on-Mesos in HA mode will have multiple schedulers running at any time (it seems controller manager's HA mode will be similarly designed, and currently it doesn't support it). In other words, K8sm is going for the hot-standby approach whereas K8s is going for cold-standby. I don't know which one is better, but I like having different options :-)

I've done some experiments getting K8sm masters running in HA mode using podmaster. I thought it would be good to document the steps so that folks who are interested in running K8sm in HA mode would have another option.

**Comment by jdef** [comment]
By all means, a PR for additional docs is welcome

**Comment by huang195** [comment]
OK, will work on the docs over the next few days and submit for review later this week. Thanks!
