### ISSUE TITLE
Pr builder times out running across 30 nodes

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#21769]
Or maybe I'm misreading the logs. From https://github.com/kubernetes/kubernetes/pull/21730#issuecomment-187492710,  https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21730/kubernetes-pull-build-test-e2e-gce/29886/?debugUI=CLOUD

The "received interrupt" message stands out the most but I think that's only during upload-to-gcs.sh.
```
+ export PROJECT=kubernetes-jenkins-pull
+ PROJECT=kubernetes-jenkins-pull
+ export NUM_NODES=6
+ NUM_NODES=6
+ export E2E_UP=true
+ E2E_UP=true
+ export E2E_TEST=true
+ E2E_TEST=true
...

Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1456192790 - Will randomize all specs
Will run 138 of 235 specs

Running in parallel across 30 nodes
...


+ [[ -x ./hack/jenkins/upload-to-gcs.sh ]]
+ ./hack/jenkins/upload-to-gcs.sh
Uploading to gs://kubernetes-jenkins/pr-logs/pull/21730/kubernetes-pull-build-test-e2e-gce/29886 (attempt 1)

---------------------------------------------------------
Received interrupt.  Running AfterSuite...
^C again to terminate immediately



---------------------------------------------------------
Received interrupt.  Running AfterSuite...
^C again to terminate immediately

```

@kubernetes/goog-testing

**Comment by ixdy** [comment]
This might be another manifestation of #20778, but I'm not sure.

**Comment by wojtek-t** [comment]
This just happened to me again:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/22175/kubernetes-pull-build-test-e2e-gce/30948/build-log.txt

**Comment by fejta** [comment]
@spxtr how will your log collection improvements change this?

**Comment by spxtr** [comment]
I can make the change in #22374 on PR Jenkins and then we'll get more logs for this sort of thing.

**Comment by spxtr** [comment]
Okay, from now on we should get logs from this.
