### ISSUE TITLE
Surface quota issues better in loadbalancer e2es 

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#21775]
**Services should serve identically named services in different namespaces on different load-balancers** started failing sometime overnight when run from v1.1 against a v1.2 cluster:

```
05:01:03 • Failure [1237.432 seconds]
05:01:03 Services
05:01:03 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:861
05:01:03   should serve identically named services in different namespaces on different load-balancers [It]
05:01:03   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:860
05:01:03 
05:01:03   Expected error:
05:01:03       <*errors.errorString | 0xc208c34040>: {
05:01:03           s: "service test-svc in namespace e2e-tests-services-jtt6t doesn't have a LoadBalancer ingress point after 1200.00 seconds",
05:01:03       }
05:01:03       service test-svc in namespace e2e-tests-services-jtt6t doesn't have a LoadBalancer ingress point after 1200.00 seconds
05:01:03   not to have occurred
05:01:03 
05:01:03   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:829
```

See http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step4-e2e-old/ and http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step6-e2e-old/

Perhaps related to #21693?

**Comment by ihmccreery** [comment]
Hm... looks like we're maxed out on quota for forwarding rules & global addresses, and we're close to full on target pools.  My guess is that's what's causing this, not anything in the code.

**Comment by ihmccreery** [comment]
(Except of course that we're leaking stuff.)

**Comment by bprashanth** [comment]
This is what a failure to just not create loadbalancers would look like. I don't think the leaks are going to get addressed in 1.2 (it's known and we've opened and closed several issues for them), I'm fine leaving this open to track the leaks though.

**Comment by ihmccreery** [comment]
Can we add logic, either to the test or the lb controller logic, so that a lack of quota gives a more reasonable response than just "it didn't come up, we don't know why"?

**Comment by bprashanth** [comment]
The easiest would be to teach the servicecontroller to just send an event anytime the error code returned from the cloudprovider corresponds to out of quota, and print all events associated with the service on failure. This would still not show up in the failure message. 

To get this to show up in the failure message we can:   

1. surface out-of-quota as some more generic field in service.lb.status
2. surface in annotations (this is what I do for L7)
3. Teach the test to scrape output of gcloud compute project-info describe for limit/usage numbers

3 sounds like the easiest, becase the output of `gcloud compute project-info describe --format=json` is a compute project (https://cloud.google.com/compute/docs/projects#getprojectinformation) with one field being "quota", so we can just deserialize and compare limit to usage. 

I'm retitling the issue. Unsure if I'll be able to pick it up soon, but we should do this.
