### ISSUE TITLE
AWS: Error logged from ECR

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21783]
```
Feb 23 19:23:55 ip-172-20-0-9 kubelet[18305]: E0223 19:23:55.751468   18305 aws_credentials.go:130] while requesting ECR authorization token RequestError: send request failed
Feb 23 19:23:55 ip-172-20-0-9 kubelet[18305]: caused by: Post https://ecr.us-west-2.amazonaws.com/: dial tcp 54.240.253.59:443: i/o timeout
```

Not sure if it's because I'm running in us-west-2 or because I haven't launched/opted-in to ECR.

**Comment by justinsb** [comment]
Ugh... ECR is only available in us-east-1.  I'm not sure if we are supposed to use it from e.g. us-west-2.

**Comment by druidsbane** [comment]
I was just having this same issue as in the image is in East but I can't pull the image while in the west region for the pods.

**Comment by therc** [comment]
That's very dumb of Amazon... but the GA announcement seems to imply it's a supported, suboptimal arrangement:

https://aws.amazon.com/blogs/aws/ec2-container-registry-now-generally-available/

> With Amazon ECR you only pay for the storage used by your images and data transfer from Amazon ECR to the internet or other regions.

**Comment by druidsbane** [comment]
@therc but technically:

> Launch Region
> Effective today, Amazon ECR is available in US East (Northern Virginia) with more regions on the way soon!

**Comment by justinsb** [comment]
I'm inclined to say we only support ECR in us-east-1 for now (in 1.2).  And as long as this is just a warning and not affecting functionality, we accept that this warning will appear (in 1.2).  I don't want to disable ECR in k8s in us-west-2, and then have AWS launch ECR in us-west-2 but k8s users be unable to use it.

It's not clear whether the us-west-1 ECR and the us-east-1 ECR will share images.  I would guess not - does anyone have any information on this?

**Comment by justinsb** [comment]
Oh ... scratch that.  They definitely don't share images, because the hostname is baked into the image name.

We probably should be fetching credentials only when we see a request for the image.  Ideally we would be able to log in to the us-east-1 registry when a us-east-1 hosted ECR image is requested, but I don't know if we have the credentials to do that when we're in us-west-2.

**Comment by therc** [comment]
I can try cooking up a PR this weekend. I've been swamped with a lot of other stuff or I would have worked on it earlier. us-east-1 is the center of the universe for us, so I'll have to see test my deployment scripts to create a toy cluster in another region (something that we'll need soon anyway).

**Comment by justinsb** [comment]
No worries - it isn't the end of the world, looks like it is a 2 minute delay starting the kubelet.  Here's a log extract from us-west-2.

```
Mar 05 02:49:26 ip-172-20-0-9 kubelet[3301]: I0305 02:49:26.974282    3301 manager.go:1667] Need to restart pod infra container for "kube-scheduler-ip-172-20-0-9.us-west-2.compute.internal_kube-system(e0070b7919de16958e0b6c07205cc597)" because it is not found
Mar 05 02:49:26 ip-172-20-0-9 kubelet[3301]: I0305 02:49:26.985750    3301 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
Mar 05 02:49:27 ip-172-20-0-9 kubelet[3301]: I0305 02:49:26.985878    3301 provider.go:91] Refreshing cache for provider: *aws_credentials.ecrProvider
Mar 05 02:51:27 ip-172-20-0-9 kubelet[3301]: E0305 02:51:27.333679    3301 aws_credentials.go:130] while requesting ECR authorization token RequestError: send request failed
Mar 05 02:51:27 ip-172-20-0-9 kubelet[3301]: caused by: Post https://ecr.us-west-2.amazonaws.com/: dial tcp 54.240.253.59:443: i/o timeout
Mar 05 02:51:27 ip-172-20-0-9 kubelet[3301]: I0305 02:51:27.333752    3301 docker.go:160] Pulling image gcr.io/google_containers/pause:2.0 without credentials
Mar 05 02:51:29 ip-172-20-0-9 kubelet[3301]: I0305 02:51:29.379397    3301 docker.go:160] Pulling image gcr.io/google_containers/pause:2.0 without credentials
```

Note there's some complexity around a simple timeout here, e.g. https://github.com/kubernetes/kubernetes/pull/22555

I haven't really looked into the code here, so I'm not sure what the right fix is...

**Comment by therc** [comment]
The biggest problem is that the credential provider is refreshed wholesale and there's no information propagated on which URL we are trying to access, even if you declare one for each AWS region.
I was tempted to call `RegisterCredentialProvider()` once for region, but that means that `Provide()` is still called for all of them. And Enabled() doesn't get access to enough information to determine if a region's provider should be on or off. I don't know, short of changing the APIs to split the registry URL enumeration from fetching credentials for a given endpoint, if we can avoid yet another command line flag...

**Comment by therc** [comment]
In other words, lazyDockerKeyring isn't lazy enough.

**Comment by justinsb** [comment]
Given ecr is only in us East for now, how about we always go to us East, or
just disable it if not in us East. I can do an experiment to see what
happens if we target us East from us West ..  Not sure about iam here.

In 1.3 we can make the changes to fetch based on the image name

On phone, sorry for spelling.

**Comment by therc** [comment]
@erictune for 1.3 wisdom. I'd like [lazyDockerKeyring.Lookup()](https://github.com/kubernetes/kubernetes/blob/24d82b6c4a5a1266d22e1f04d0cb2fd2b40b72a5/pkg/credentialprovider/keyring.go#L247) to stop calling `Provide()` blindly on all providers. Instead, it would use a new `Locations()`, or something similarly named, to grab just the list of URL patterns for registries the provider supports. Then, it would be the loop inside [BasicDockerKeyring.Lookup()](https://github.com/kubernetes/kubernetes/blob/24d82b6c4a5a1266d22e1f04d0cb2fd2b40b72a5/pkg/credentialprovider/keyring.go#L218) to call Provide(), but only after a match.

As to 1.2: causing a two minute delay on startup is a big deal to me. Imagine you're adding nodes for capacity under load: AWS instances are already slow, now we're adding an extra two minutes. For all we know, ECR could be supported everywhere in a week or two. Would we issue a 1.2 point release to revert a change that restricts the support only to us-east-1?

**Comment by therc** [comment]
Can we close this? I think it's solved now

**Comment by justinsb** [comment]
SGTM ...  we can always reopen if needed!
