### ISSUE TITLE
e2e flake: deployment should delete old replica sets [failed remove pods]

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#21798]
Should be related to #21753 since they share the same failure mode. 

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21793/kubernetes-pull-build-test-e2e-gce/30058/artifacts/?debugUI=CLOUD

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/30058/

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:56
Feb 23 14:07:29.295: Failed to remove deployment redis-deployment pods!
```

cc @bgrant0607 @kargakis @mqliang @nikhiljindal @ironcladlou @soltysh

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/21857 should fix this

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/21857.
Verified that the test is not flaky anymore.
