### ISSUE TITLE
Allow local releases for one platform

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#21791]
I'm trying to get at the release tarballs for individual binaries. I'm not talking about the compressed ones, but rather `_output/release-stage/server/linux-amd64/kubernetes/server/bin/kube-controller-manager.tar` and co. Unfortunately, it looks like I have to build stuff for seven between server and client platforms in order to get them. I only want to build local containers for the various binaries, through `docker import`, per instructions at https://github.com/kubernetes/kubernetes/blob/master/docs/admin/high-availability.md.

I tried to make a clone of `build/release.sh` that calls `build-go.sh` instead of `build-cross.sh`, but that still tries to package all platforms. By lucky coincidence, linux/amd64 is the first platform on the list and the one I happen to need, so it kinda works for me at the moment, but it's all very ugly. And trying to understand the whole build system to add an option or new script is easier said than done.

**Comment by mml** [comment]
Dup of #20367
