### ISSUE TITLE
Job & HPA need to be in upgrade storage object test

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#21806]
I had this fixed in my version of the job move, but I guess it got lost somewhere along the way.

The upgrade storage test needs to exercise the upgrade path for both Job and HPA.

@nikhiljindal @erictune @piosz

**Comment by ncdc** [comment]
@lavalamp is this something I could help out with? If so, can you point me to the specific test that needs editing?

**Comment by piosz** [comment]
@ncdc It would be great if you could help with it.

There is a test [test-update-storage-objects.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/test-update-storage-objects.sh). Also there is an attempt to do it by @lavalamp  [here](https://github.com/kubernetes/kubernetes/pull/20866/files#diff-8dc3ac3856b6ae7bb59360438f5b4fe6). I'm not sure whether it makes sense. This is what I know.

**Comment by piosz** [comment]
cc @fgrzadkowski @mwielgus

**Comment by davidopp** [comment]
ping @ncdc - do you think you can take care of this, as it is a 1.2 blocker?

**Comment by ncdc** [comment]
@davidopp I had some minor surgery yesterday and am still recovering today. I expect to be back tomorrow and hopefully can finish it up then, if it can wait until then.

**Comment by davidopp** [comment]
no problem - hoping for a quick recovery!

**Comment by ncdc** [comment]
PR submitted for this - PTAL!
