### ISSUE TITLE
Can one run multiple K8sm instances in the same mesos cluster

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#21813]
Couple of questions about K8sm:

1) Can one run multiple K8sm frameworks in a mesos cluster? E.g., different K8sm versions or the same version but belongs to different users. 

2) If the answer is 'yes' to the first question, will mesos assign part of a mesos node to one K8sm framework and another part to a different K8sm framework?

@jdef @sttts

**Comment by huang195** [comment]
I found this issue: https://github.com/mesosphere/kubernetes-mesos/issues/201

Looks like the answer to the first question is 'no'. What if we're talking about different frameworks, e.g., 1 K8sm + 1 Spark? Will that work? If so what is the answer to the 2nd question?

**Comment by jdef** [comment]
Now that k8sm supports roles, you could (and people have, I'm told) run
multiple instances of k8sm on the same cluster by statically partitioning
your mesos slaves using roles. For example, if you had 6 slaves you could
assign all the resources from slaves 1 - 3 to role A, and all the resources
from slave 4 - 6 to role B; then run two instances of k8sm, each instance
configured to consume resource offers from different role classes (A and B
in this case).

Spark is orthogonal to k8sm, they should be able to share mesos resources
on the same slaves. I've heard that Spark can be greedy so some fine tuning
may be required to increase fairness of resource sharing.

**Comment by huang195** [comment]
I didn't know k8sm already support roles :-) Have to try that out.
Regarding running spark along with k8sm, I'd imagine they would have different executors, but if I'm looking at k8sm code here: (https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/pkg/scheduler/components/framework/framework.go#L136), if an offer comes with multiple executor ids, k8sm would decline the offer. Is this the intended behavior?

**Comment by jdef** [comment]
Pretty sure that the executorIDs received by k8sm are only for executors of
the same framework. So k8sm wouldn't see spark executors.

**Comment by huang195** [comment]
Thanks for the reply. Closing this issue.
