### ISSUE TITLE
Decide what to do about suites.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#21818]
Given that we dont really have suites in ginkgo, we discussed in @kubernetes/sig-testing today possible alternatives.

- one idea: actually implementing, in code, a programmatic way to define tests.
- another more practical idea: improve the docs and add a README right inside of tests/e2e which pointed to the exact definition of conformance tests and so on, and how to use the filters.

Since the first bullet is really more of a wacky idea, the second would be the implementation to start with.  

CC @kubernetes/sig-testing

**Comment by spiffxp** [comment]
what do we think about closing this?

https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#kinds-of-tests  is an attempt at the 'practical' idea, documenting the labels currently used in tests

the issue referenced therein (#10548) has since been closed out

**Comment by timothysc** [comment]
I think using the regex's + the e2e suite breakouts such as the node and main are good examples now. 

closing
