### ISSUE TITLE
Busybox pod running on GCE cluster can't resolve "metadata"

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#21819]
Repro:
* Created cluster at master (in my case, roughly `v1.2.0-alpha.8.225+c1bd13ec4bcedf`) on GCE
* Create busybox template ala https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns
* Badness:
```
$ kubectl exec busybox nslookup metadata
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'metadata'
error: error executing remote command: Error executing command in container: Error executing in Docker Container: 1

$ kubectl exec busybox nslookup metadata.google.internal
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      metadata.google.internal
Address 1: 169.254.169.254 metadata.google.internal

$ kubectl exec busybox cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local c.artful-fortress-786.internal. google.internal.
nameserver 10.0.0.10
options ndots:5
```

(I found this with the Spark template trying to extend it to use an ACL'd GCS bucket, but it's easy to see with `busybox`.)

**Comment by zmerlynn** [comment]
Confusingly:
```
$ kubectl exec -it kube-dns-v10-aaslb --namespace=kube-system -c skydns nslookup metadata 127.0.0.1
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      metadata
Address 1: 169.254.169.254 metadata.google.internal
```

**Comment by thockin** [comment]
Confirm.  It looks like something is only allowing 4 search paths now.
This is double screwy because we are supposed to have an e2e for metadata!
Investigating more.  @artfulcoder

```
root@kubernetes-minion-1esy:/home/thockin# docker run -ti --dns=10.0.0.10
--dns-search=foo --dns-search=bar --dns-search=google.internal busybox
nslookup metadataServer:    10.0.0.10
Address 1: 10.0.0.10

Name:      metadata
Address 1: 169.254.169.254 metadata.google.internal

root@kubernetes-minion-1esy:/home/thockin# docker run -ti --dns=10.0.0.10
--dns-search=foo --dns-search=bar --dns-search=qux
--dns-search=google.internal busybox nslookup metadata
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'metadata'
```

**Comment by thockin** [comment]
ubuntu does not seem to have this problem.

**Comment by thockin** [comment]
Edit: busybox seems to allow 3 now.  It used to work.  THIS RIGHT HERE is
why EVERYONE needs to manage upstream images.

**Comment by thockin** [comment]
busybox:glibc works, busybox:uclibc does not work, and that happens to be
what :latest points to.

**Comment by zmerlynn** [comment]
Hm, maybe I'm having a separate issue in Spark, then, and I stripped it down to the wrong repro. :P 

Try:
```
sudo docker run --dns=10.0.0.10 --dns-search=foo --dns-search=bar --dns-search=google.internal debian:jessie getent hosts metadata
```
(It looks like my spark image is Jessie based, in the end.)

**Comment by zmerlynn** [comment]
I actually can't get the smaller search path busybox repro to work, either.

**Comment by thockin** [comment]
Jessie works for me:

```
root@kubernetes-minion-1esy:/home/thockin# docker pull debian:jessie
jessie: Pulling from library/debian

Digest:
sha256:f4261eae2011306946bca423ae16940467fa6bee6e9c2c549189d9d83ca22112
Status: Image is up to date for debian:jessie
root@kubernetes-minion-1esy:/home/thockin# docker run --dns=10.0.0.10
--dns-search=foo --dns-search=bar --dns-search=google.internal
debian:jessie getent hosts metadata
169.254.169.254 metadata.google.internal
```

**Comment by thockin** [comment]
https://github.com/docker-library/busybox/issues/9

**Comment by ArtfulCoder** [comment]
Binaries/libs cannot link against busybox since busybox is a statically linked binary. 
So programs that run in busybox container would probably bring in their own libc.

But there are two scenarios where busybox ndots issue could hurt:
1. user directly uses busybox nslookup/dig. 
2. program does an exec and invokes busybox's nslookip.

**Comment by zmerlynn** [comment]
Alright, so there are two bugs here:
* `busybox:latest ` is not a great diagnostic because of the aforementioned search path issues.
* My cluster, which is bog standard head, came up with an environmental issue that's blocking it either short search path `busybox` or any flavor of `debian` from resolving `metadata`. When I get in I'll dig in and see if I can figure out why my cluster is a special snowflake.

**Comment by zmerlynn** [comment]
I forked off a second issue for what's probably a network issue, #21896.

**Comment by thockin** [comment]
This appears to never have worked.  I am demoting to P2 for now, will continue investigating.

**Comment by thockin** [comment]
I am removing this from the milestone.  The patch is being reviewed upstream for uclibc, and docker is willing to carry it until then: https://github.com/docker-library/busybox/pull/10

**Comment by thockin** [comment]
in fact I am going to close this - it is not a Kube bug in any way.  If you need search paths and busybox, use busybox-glibc.
