### ISSUE TITLE
Add timeout to all docker calls

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#21821]
forked from #21029    
tracking related cases in this issue

The go-dockerclient we use don't support timeout for any operation. We are switching to use docker engine-api #20895  
Strongly suggest we enforce timeout for image pull once we switch to the new docker client.

**Comment by yujuhong** [comment]
I think we have an old issue lying somewhere; will update if I find it.

**Comment by AdoHe** [comment]
+1 really necessary for image pulling.

**Comment by Random-Liu** [comment]
@yujuhong Are you mentioning this one #9896 ? :)

**Comment by yujuhong** [comment]
Yes! This issue is broader because it applies to all docker calls (not just the ones that can block syncloop).

**Comment by yujuhong** [comment]
Let's merge this with #9896 to avoid duplication.
