### ISSUE TITLE
Remove outdated E2E scripts

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#21843]
### These should probably be supported

**`hack/e2e.go`** with various flags to turn on and off various options.
**`make e2e_test`** is an alias for `go run hack/e2e.go -v --build --up --test --down`
### These are used by `hack/e2e.go`

**`hack/e2e-internal/*`**
**`hack/ginkgo-e2e.sh`**
### These should probably be removed right away

~~**`cluster/test-conformance.sh`**~~ #23353
~~**`hack/conformance-test.sh`**~~ #23353
**`cluster/test-e2e.sh`** calls `hack/ginkgo-e2e.sh`.
**`cluster/test-network.sh`** calls `hack/ginkgo-e2e.sh --ginkgo.focus=Networking`.
**`cluster/test-smoke.sh`** calls `hack/ginkgo-e2e.sh --ginkgo.focus=Guestbook.application`.
~~**`hack/upgrade-e2e-test.sh`**~~ was removed in #21850.
**`hack/jenkins/e2e-runner.sh`** should be split into individual `hack/e2e.go` calls.
~~**`hack/parallel-e2e.sh`**~~  was removed in #21802.
~~**`hack/e2e-from-release.sh`**~~  was removed in #21725.
~~**`hack/e2e-test.sh`**~~  was removed in #21342.

I'm sure I missed some.
@kubernetes/sig-testing

**Comment by jdef** [comment]
what would be the new way to run the conformance or smoke tests?

**Comment by jdef** [comment]
#21818

**Comment by spxtr** [comment]
I'm not sure what it'll look like in the end, but it might be worth adding `--conformance`, `--feature=bla`, or `--focus=Guestbook` flags to `hack/e2e.go`. It's already pretty easy to get this behavior by using a current flag, but it's ugly.

**Comment by spiffxp** [comment]
It would be nice if eventually something like `e2e.test` or `hack/e2e.go` was distributed with kubernetes so there was an out-of-the-box way to validate and exercise your cluster.  

As it stands today, we seem to be adopting the stance that you can only do this with the kubernetes source code, so I'm very much in favor of ripping out the `cluster/` cruft

**Comment by ixdy** [comment]
We already have `e2e.test` and `hack/e2e.go` included in the kubernetes-test tarballs. (And a lot of other cruft, too, including some stuff we probably shouldn't be.)

**Comment by spxtr** [comment]
Closing, since we're making changes to `e2e.go` in test-infra.
