### ISSUE TITLE
Kubelet could not tear down volume NFS

### ISSUE THREAD

**Issue by cdpb** [kubernetes/kubernetes#21859]
Hi all,

I am using a 3 node coreos test cluster with kubernetes 1.1.17.
My kublets complaing something like:

```
Feb 24 03:34:33 coreos1 bash[11741]: W0224 03:34:33.651446   11741 kubelet.go:1595] Orphaned volume "ba9600ab-a63d-11e5-8071-000c29181a89/pv-gitlab-logs" found, tearing down volume
Feb 24 03:34:33 coreos1 bash[11741]: E0224 03:34:33.651822   11741 kubelet.go:1601] Could not tear down volume "ba9600ab-a63d-11e5-8071-000c29181a89/pv-gitlab-logs": remove /var/lib/kubelet/pods/ba9600ab-a63d-11e5-8071-000c29181a89/volumes/kubernetes.io~nfs/pv-gitlab-logs: directory not empty
```

Indeed, the volume is not empty, but how is it even possible that some persistent data are on the host system, if I mount everything via NFS from a external host? The volume `pv-gitlab-*` no longer exist on the NFS host and there are currently no mounted nfs volumes on the coreos host (`mount | grep nfs`).

Also there are no running pods on the coreos host.

Did the kubelet something like shadow copying data?

**Comment by cdpb** [comment]
same in v1.2.0

**Comment by childsb** [comment]
Any chance of testing this on kube 1.3? We've made heavy changes to the volume binding and attach/detach which might resolve the issue.

**Comment by matchstick** [comment]
If this reoccurs on 1.3.4 or later please reopen.
