### ISSUE TITLE
AWS policy and role in region cn-north-1 has cn suffix

### ISSUE THREAD

**Issue by dengshuan** [kubernetes/kubernetes#21858]
As documented [here](http://docs.amazonaws.cn/en_us/aws/latest/userguide/iam.html)

> In the Beijing region, the Amazon Resource Name (ARN) syntax includes a cn. For example: arn:aws-cn:iam::123456789012:user/division_abc/subdivision_xyz/Bob.

and

> The syntax is different than it is for other regions. For example, if you create a role to assign to an EC2 instance, the trust policy should have a format similar to the following: 
> 
> ``` json
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Effect": "Allow",
>       "Principal": {"Service": "ec2.amazonaws.com.cn"},
>       "Action": "sts:AssumeRole"
>     }
>   ]
> } 
> ```

So policy template in cluster/aws/templates/iam/kubernetes-{master,minion}-policy.json and role principal in cluster/aws/templates/iam/kubernetes-{master,minion}-role.json should be treated differently for cn-north-1 region.
The role `Statement.Principal.Service` should be `ec2.amazonaws.com.cn` and `Resource` in policy files should be `arn:aws-cn:s3:::kubernetes-*`

**Comment by beary** [comment]
Did you resolved?
