### ISSUE TITLE
[docs] commands incorrectly formatted in kubectl-overview

### ISSUE THREAD

**Issue by rutsky** [kubernetes/kubernetes#21876]
Here: http://kubernetes.io/v1.1/docs/user-guide/kubectl-overview.html#operations
![selection_021](https://cloud.githubusercontent.com/assets/46573/13288091/702c9cf2-db1b-11e5-84dd-73a8c4aa268d.png)

**Comment by bgrant0607** [comment]
cc @johndmulhausen

**Comment by janetkuo** [comment]
This now redirects to http://kubernetes.io/docs/user-guide/kubectl-overview/#operations and is fixed.
