### ISSUE TITLE
One Dev pushes, triggering a rolling-update, the other deletes the replication controller.

### ISSUE THREAD

**Issue by cpg1111** [kubernetes/kubernetes#21883]
Hi there,
My team just ran into an issue of pushing an update for a rolling-update, and then another team member was deleting an outdated replication controller manually, both happening at the same time.  This caused the rolling-update to failed, which makes sense being there was no replication controller to update anymore, however neither actions gave an error message saying the other event was occurring.  I'm wondering if we should have an error message at least on the rolling update saying that the replication controller was deleted at a particular time?

**Comment by nikhiljindal** [comment]
Whats the error message that rolling-update printed for failing?

**Comment by cpg1111** [comment]
error: couldn't find a replication controller with source id == default/<service name>

**Comment by kargakis** [comment]
Use RevisionHistoryLimit and this shouldn't be a problem with Deployments (don't manually update ReplicaSets!)

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
