### ISSUE TITLE
Cloning godeps fails before integration tests

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#21887]
Not sure if this concided with a Jenkins restart. 
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21856/kubernetes-pull-test-unit-integration/15944/?debugUI=CLOUD
```
# cd .; git clone https://github.com/tools/godep /go/src/github.com/tools/godep
Cloning into '/go/src/github.com/tools/godep'...
fatal: unable to access 'https://github.com/tools/godep/': gnutls_handshake() failed: Error in the pull function.
package github.com/tools/godep: exit status 128
Build step 'Execute shell' marked build as failure
Recording test results
```

**Comment by lavalamp** [comment]
Not sure what we can do about this. Retry a few times?

**Comment by ixdy** [comment]
GitHub seemed to hiccup last night and fail a bunch of our builds. I'm not sure a retry would've helped, unless we kept retrying for many minutes.

**Comment by ncdc** [comment]
This is the sort of thing that just happens occasionally. We've seen this a lot in OpenShift CI runs. I'm not sure there's much you can do other than try to avoid external network access (e.g. bake tools into the VM image).

**Comment by bprashanth** [comment]
It seems to have occurred twice in the last 12h so retry w/ timeout can't hurt?

**Comment by ncdc** [comment]
It can't hurt... but it may or may not help depending on the extent of the external issue

**Comment by lavalamp** [comment]
If the problem is really bad, we could toss it somewhere on GCS?

**Comment by fejta** [comment]
https://github.com/kubernetes/kubernetes/blob/b7a89bfd475ed993801cd1f1a00c13862e28fd16/hack/jenkins/test-dockerized.sh#L29

```
+ docker run --rm=true -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/bin/docker -v /var/lib/jenkins/workspace/kubernetes-pull-test-unit-integration:/go/src/k8s.io/kubernetes -v /var/lib/jenkins/workspace/kubernetes-pull-test-unit-integration/_artifacts:/workspace/artifacts -v /etc/localtime:/etc/localtime:ro --env REPO_DIR=/var/lib/jenkins/workspace/kubernetes-pull-test-unit-integration -i gcr.io/google_containers/kubekins-test:0.7 bash -c 'cd kubernetes && ./hack/jenkins/test-dockerized.sh'
```

Looks like it failed on `go get github.com/tools/godep`:
https://github.com/kubernetes/kubernetes/blob/b7a89bfd475ed993801cd1f1a00c13862e28fd16/hack/jenkins/test-dockerized.sh#L29

We should probably put this in a retry loop or else do something more fancy
