### ISSUE TITLE
AWS: We download safe_format_and_mount from github

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#21885]
We should probably source it from a more reliable location and/or prebake it into our images!

**Comment by bprashanth** [comment]
Hmm, we already have it checked in so you should just be able to use: https://github.com/kubernetes/kubernetes/blob/b9cfab87e33ea649bdd13a1bd243c502d76e5d22/cluster/saltbase/salt/helpers/safe_format_and_mount

If aws needs some custom script we can upload it to GCS.

**Comment by justinsb** [comment]
kube-up in maintenance mode; closing.
