### ISSUE TITLE
Deployment reports invalid status.unavailableReplicas 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#21900]
Found this in kube-controller-manager.log. Seems unrelated to test flakes (test didn't fail when this happens). 

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21852/kubernetes-pull-build-test-e2e-gce/30209/artifacts/?debugUI=CLOUD
```
Error syncing deployment: Deployment.extensions "redis-deployment-2" is invalid: status.unavailableReplicas: Invalid value: -1: must be greater than or equal to 0
```

cc @bgrant0607 @kargakis @mqliang @nikhiljindal @ironcladlou @soltysh @kubernetes/sig-config

**Comment by kargakis** [comment]
I have been seen this in https://github.com/kubernetes/kubernetes/pull/20273, sup
