### ISSUE TITLE
e2e flake: gce-scalability node failed to start within 30 minutes

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#21911]
99 nodes came up fine, but the 100th never registered with the master.

https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/4823/

**Comment by yujuhong** [comment]
Without any logs (#21722), this is not actionable

**Comment by lavalamp** [comment]
We need to get logs from nodes that don't come up. I guess this is a dup of #21722
