### ISSUE TITLE
Hyperkube 1.1.8 packaging issue

### ISSUE THREAD

**Issue by williamsandrew** [kubernetes/kubernetes#21918]
While trying to run the Hyperkube v1.1.8 container I receive the error "exec format error". It appears the Hyperkube binary may not have been packaged correctly:

```
# docker run -ti gcr.io/google_containers/hyperkube:v1.1.8 sh -c 'file /hyperkube && cat /hyperkube'
/hyperkube: XML 1.0 document text
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>
```

**Comment by david-mcmahon** [comment]
All fixed.  Looks like a curl to grab the hyperkube binary in the old Makefile on the branch wasn't using --fail and it just failed with a 404 and we got that mess in the "binary".

**Comment by david-mcmahon** [comment]
See also https://github.com/kubernetes/kubernetes/pull/20710.  Going to defer to @fgrzadkowski

**Comment by williamsandrew** [comment]
Looks good. Thanks for the quick response!
