### ISSUE TITLE
Discovery Client hides the API path associated wtih an API group

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#21916]
See:

https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/discovery_client.go#L98

I think `unversioned.APIGroup` should hold the API path associated with that group.

Hiding the API path makes coupling usage of a dynamic client with discovery client difficult.

/cc @kubernetes/sig-api-machinery

**Comment by derekwaynecarr** [comment]
Or the signature for `DiscoveryClient` should change to not hide the API group.

**Comment by caesarxuchao** [comment]
If we add two methods `ServerGroupsAtPrefix(prefix string)` and `ServerResourcesForGroupVersionAtPrefix(prefix string, gv string)`, will that be flexible enough?

Or we can include a self-link in the discovery results, but I suspect that opens another can of worms.

**Comment by derekwaynecarr** [comment]
@caesarxuchao - It helps.
