### ISSUE TITLE
Deployment: preserve availability when maxUnavailability is not 100%

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#21922]
Forked from #21872 

If maxUnavailable isn't 100% or equal to the replica count, the user probably doesn't want all their replicas unavailable, so we should ensure at least one is available in that case. Similarly, for maxSurge, if it's non-zero, the user probably wants some surge.

cc @kargakis @janetkuo @mqliang @ironcladlou

**Comment by kargakis** [comment]
So we should use math.Floor for maxUavailable and continue using math.Ceil for maxSurge.

**Comment by bgrant0607** [comment]
GetValueFromIntOrPercent could take a parameter to indicate round up vs. round down.

**Comment by bgrant0607** [comment]
Deployment was fixed by #21957
