### ISSUE TITLE
/etc/hosts is not mounted by kubelet for rkt pods

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#21923]
Since the pod IP is unknown before the rkt pod is running, so the kubelet won't mount the /etc/hosts file:
https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.8/pkg/kubelet/kubelet.go#L1164

So what we should do here? Should we have a hosts file that doesn't have the entry: `$podIP $podName`? 

cc @kubernetes/sig-node @kubernetes/sig-network @jonboulle @sjpotter

**Comment by vishh** [comment]
AFAIK, mounting in `/etc/hosts` started out to be workaround for a docker issue.
As long as rkt sets up `/etc/hosts` with the appropriate pod hostname and domainname, this should not be an issue.

**Comment by yifan-gu** [comment]
Re @vishh , can we add `--hostname` for `rkt run/run-prepared` so that rkt writes the `/etc/hosts` with `$hostname $ip` in addition to other entries (localhost 127.0.0.1, etc) @jonboulle @steveeJ

**Comment by sjpotter** [comment]
One thought I had is that perhaps its not right for kubelet to be setting up the /etc/hosts itself as per the problem it doesn't have all the info needed.

Rkt stage1 does have the info, so it make sense for it to be there.

perhaps the best approach is to not have kubelet try to add the local ip to the /etc/hosts file, but have rkt add it during stage1 while its bind mounting it into place.

**Comment by vishh** [comment]
In the case of `rkt`, we can totally skip bind mounting `/etc/hosts` as long as `rkt` does the right thing.

**Comment by thockin** [comment]
where "right thing" involves configuring it for an FQDN and a hostname, if
an FQDN is present.

ie. if user provides a domainname, you generate `1.2.3.4 hostname.domain.com
hostname`.  If user provides only a hostname, you generate `1.2.3.4
hostname`.  Now what do you do if user provides an FQDN as a hostname?  The
right thing is to treat it as if they had split it themselves, but set the
actual `hostname` (/etc/hostname, uts) to the fqdn

**Comment by steveeJ** [comment]
@yifan-gu when you say `$hostIP`, do you actually mean the Pod's IP? If so, how is it determined? Which IP is used if the pod is configured for multiple networks?

I seem to be blind, if someone could link a doc that describes how hostnames are passed to a pod and it's containers I'd appreciate that.

**Comment by ncdc** [comment]
cc @pmorie, since you've been digging around with pod ip :-)

**Comment by yifan-gu** [comment]
@steveeJ Sorry I meant pod's IP. 
> If so, how is it determined? Which IP is used if the pod is configured for multiple networks?

Good question, I think it's IP of the network that's passed to rkt when creating the pod [1].

[1] https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.8/pkg/kubelet/rkt/rkt.go#L717

**Comment by steveeJ** [comment]
@yifan-gu I'm not sure of the use-case.

* Why can't k8s not just use the hostname that rkt generates?
* How should rkt register itself to machined when a hostname is given?
* Could it suffice to update any additional hostname in the SkyDNS service running for the cluster?

In any case:
* In case of multiple networks, which IP should be used for the given hostname?

**Comment by yifan-gu** [comment]
> Why can't k8s not just use the hostname that rkt generates?

One thing I can think of is we should keep the UX same for different container runtimes. Currently when using docker, the hostname is set to the pod name, so I think that's what users will expect for rktnetes.

> How should rkt register itself to machined when a hostname is given?

Good question, if two pods have the same name, they will conflict with each other. Maybe as we discussed OOB, we can keep the `rkt-uuid` for registering, but set the hostname to the pod name in the new uts?

> Could it suffice to update any additional hostname in the SkyDNS service running for the cluster?

Are you suggesting make the DNS resolve `rkt-uuid`? Can you give examples what to update?

> In case of multiple networks, which IP should be used for the given hostname?

Good question. For now, the pod only adds to one network, so it can be solved. Not sure about what to do with multiple networks. Could you share some thoughts here ? @thockin

**Comment by woodbor** [comment]
> Re @vishh , can we add --hostname for rkt run/run-prepared so that rkt writes the /etc/hosts with $hostname $ip in addition to other entries (localhost 127.0.0.1, etc) @jonboulle @steveeJ 

@yifan-gu : :+1: IMHO - it could be the similar mechanism like rkt now fill `/etc/resolv.conf` file (I mean through cmd line flags in kubelet). And then we can drop the mounts for `/etc` files in generated pod manifest, which the root cause for that was docker, what do you think ?

**Comment by thockin** [comment]
Faced with multiple interfaces, one of them has to be "primary".  For lack of any better information, we should probably start with the first one.

> Why can't k8s not just use the hostname that rkt generates?

Hostname is something that users will be able to set (they have been asking for it for a long time).  Like it or not, there is a body of software that makes assumptions about hostnames, and we need to accommodate that.

**Comment by steveeJ** [comment]
@thockin
> Faced with multiple interfaces, one of them has to be "primary". For lack of any better information, we should probably start with the first one.

This could be solved by introducing a *primary* property for networks that is handed down all the way to CNI.

@yifan-gu 

> > Could it suffice to update any additional hostname in the SkyDNS service running for the cluster?
> 
> Are you suggesting make the DNS resolve rkt-uuid? Can you give examples what to update?

Which of the following information related to the pod has to be consistent with the hostname set by k8s?
* machined registered name (this probably effects cAdvisor because it occurs in the cgroup name-scheme)
* DNS forward/reverse
* `gethostname()` inside the Pod
* */etc/hosts* primary IP
* */etc/hostname* (imoprtant at all?)

**Comment by yifan-gu** [comment]
> Which of the following information related to the pod has to be consistent with the hostname set by k8s?

I think except for the machined registered name (as we discussed yesterday, it can cause problems if two pods with the same pod name try to register with machined), other things should be consistent with the hostname set by k8s. Point me out if I am wrong @thockin

**Comment by thockin** [comment]
>> Faced with multiple interfaces, one of them has to be "primary". For lack of any better information, we should probably start with the first one.
>
> This could be solved by introducing a primary property for networks that is handed down all the way to CNI.

CNI plugins are supposed to be independent, right?  What is a CNI
plugin going to DO with that information?

> Which of the following information related to the pod has to be consistent with the hostname set by k8s?

> gethostname() inside the Pod
> /etc/hosts primary IP
> /etc/hostname (imoprtant at all?)

**Comment by thockin** [comment]
We don't want pod hostnames in DNS unless explicitly put them there.

**Comment by jellonek** [comment]
Connected with https://github.com/coreos/rkt/issues/2256

**Comment by euank** [comment]
This will be fixed by the combination of #25902 and #26096 being merged.

**Comment by yifan-gu** [comment]
This can be closed now.
