### ISSUE TITLE
Creating HPA using docs/user-guide/horizontal-pod-autoscaling/hpa-php-apache.yaml fails validation

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#21938]
I ran:
```
$ ./cluster/kubectl.sh create -f docs/user-guide/horizontal-pod-autoscaling/hpa-php-apache.yaml
```
which gave:
```
error validating "docs/user-guide/horizontal-pod-autoscaling/hpa-php-apache.yaml": error validating data: found invalid field namespace for v1beta1.SubresourceReference; if you choose to ignore these errors, turn validation off with --validate=false
```

Adding validate=false ran fine.
```
$ ./cluster/kubectl.sh create -f docs/user-guide/horizontal-pod-autoscaling/hpa-php-apache.yaml --validate=false
```

I was running HEAD code locally.

cc @piosz @kubernetes/autoscaling

**Comment by piosz** [comment]
Thanks @nikhiljindal for reporting. I'll take a look.

**Comment by aveshagarwal** [comment]
I think the issue is that there is no field "namespace" in "type SubresourceReference struct" in ./pkg/apis/extensions/types.go and thats why its failing validation.

**Comment by aveshagarwal** [comment]
Removing that namespace from from docs/user-guide/horizontal-pod-autoscaling/hpa-php-apache.yaml works. Only new field that could be added is apiVersion.

**Comment by ncdc** [comment]
@aveshagarwal if you have time, please submit a PR for this

**Comment by aveshagarwal** [comment]
https://github.com/kubernetes/kubernetes/pull/22075
