### ISSUE TITLE
unit/integration flake: kubernetes-test-go timing out

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#21937]
kubernetes-test-go has failed in this way 5 times today. I'm not actually sure what the `Timeout starting apiserver` message is referring to. From the logs, it looks more like the real issue is `Build timed out (after 30 minutes). Marking the build as failed.` The integration test ran for about 10 minutes before the build timed out.
https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-test-go/8807/

This may be the same as #20613, but that's been closed for 3 weeks.

**Comment by lavalamp** [comment]
I don't see anything obviously wrong. I did file #22000, client throttling might be slowing down the integration test a tad.

We did recently start testing multiple combinations of api versions. So that would double the time for the unit and integration tests, since we run them two ways now.

**Comment by ixdy** [comment]
The `Timeout starting apiserver` failure cause has been mis-triggering a lot. Most of the failures have been due to something else - either timeouts or #21451.

**Comment by ixdy** [comment]
OK, the `Timeout starting apiserver` failure cause looks for `.*apiserver.*` in the log, which is approximately the most useless regex possible. I'm gonna delete it.

**Comment by ixdy** [comment]
In general, it looks like unit tests are taking right around 30m, so probably we need to bump that timeout up.

**Comment by ixdy** [comment]
I'm a little worried about what made the unit tests slower (the 1.1 branch still takes only 12-14m). No clear cause yet.

**Comment by ixdy** [comment]
@kubernetes/goog-testing anyone have cycles to investigate why unit/integration got slower?

**Comment by spxtr** [comment]
`hack/verify-api-reference-docs.sh` is pretty slow.

**Comment by spxtr** [comment]
That's not what caused it, the build just got ~10 min slower a few days ago. I'll figure out why.

**Comment by spxtr** [comment]
https://github.com/kubernetes/kubernetes/pull/21352

Looks like it was purposeful.

**Comment by wojtek-t** [comment]
Another significant reason of slowing down that we did consciously was:
https://github.com/kubernetes/kubernetes/pull/21105
