### ISSUE TITLE
kubemark can't work with google cloud Project ID prefixed with domain name

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#21967]
Some google cloud Project IDs are prefixed with domain name such as "example.com:my-project" (see https://cloud.google.com/compute/docs/projects).

My project id is also domain name prefixed. When I tried to start a kubemark cluster following [the guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/kubemark-guide.md), I found that kubemark can't work with such project ids.

In https://github.com/kubernetes/kubernetes/blob/master/cluster/images/kubemark/Makefile, it uses project id to generate the image tag. However, docker doesn't support image tag containing colon **:** .

In https://cloud.google.com/container-registry/docs/, it says that colon in project id like "example.com:my-project" should be replaced with slash to "example.com/my-project".

**Comment by mattmoor** [comment]
It looks like in place of `$(PROJECT)` this should use `$(subst :,/,$(PROJECT))`

**Comment by spiffxp** [comment]
/sig scalability
I'm assuming sig-scalability owns kubemark
