### ISSUE TITLE
Wrong binary location in ./hack/local-up-cluster.sh

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#21961]
Hi,

The script hack/local-up-cluster.sh is looking for binaries in /_output/local/bin/${host_os}/${host_arch} directory here: https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L166

While the binaries are in _output/local/go/bin directory. Same issue is with cluster/kubectl.sh script.
https://github.com/kubernetes/kubernetes/blob/master/cluster/kubectl.sh#L90

**Comment by jayunit100** [comment]
dont we copy the binaries from local/bin into hostarch/?

**Comment by Pensu** [comment]
I don't think so. I ran ./hack/build-go.sh and then I ran ./hack/local-cluster-up.sh. It couldn't find the binaries.

**Comment by jayunit100** [comment]
Hmm. How is this working for anyone, at all then?

**Comment by Pensu** [comment]
Okay, so I reran it, not sure what's the issue, but when I run both scripts together, I can't find the binaries, but when I am running just hack/local-up-cluster.sh, I am able to find the binaries. Something else I need to figure out, I guess.

**Comment by jayunit100** [comment]
Ok or maybe it's a bug in build-go... But it's worth getting to the bottom of . Thanks for digging

**Comment by fabioy** [comment]
Is this issue still active? Closing for now. Please feel free to reactivate.
