### ISSUE TITLE
e2e flake: RollingUpdateDeployment should delete old pods and create new ones [timed out waiting for the condition] 

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#21975]
Yet another one in deployments, seen in https://github.com/kubernetes/kubernetes/pull/21776, full log is [here](https://00e9e64bac0662611cc1fd38830c9c7e1b30c5fec7aa823483-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F21776%2Fkubernetes-pull-build-test-e2e-gce%2F30377%2Fbuild-log.txt?qk=AD5uMEvw8FmYbO6x2nikTJOUDV4ngBo-BwpJyIgQnkALKA3h7EFknWG57RlkfDTvtpFIOQUAmxCK7DM11Nkw9YbVpEfq5vA4DXaiT2Aa2m3_cjfmaDpJRwf4Wx-LElKVg9LTvifHE0fQfrIW7YC16GB7SLtjf6pY5s00txsBWTvsEU_N1zHUeKx3zFrR79QrIrQ7S_Wo-Btw2adFQp_DxmWxUW5oLCSbQDycCqNZwjYrvK-xahTDcD-71WMvFX_4lIeAcECwfJVjAS0mmqjuAwDoO6e0Y3pQ15H_ccoSiIjRsXO3QTf_81wQmodvtTIHOQuTzJbiR-M7dAZM7apugAYpL7NqFmzNTESJ5o7Q1Yt-aZdSIsN3uZ3AuiXrQKSQp8N2D0-4kLpU4ldKDz0CIvgIdd6NSPPdgqU7hL-hAtAB9Wra5EW7NF37e7BczMyitgwUc9_0ayk6xCximb0FZH78ISHLq_8XDdIF0xdMAENKIJVRxTe4ozkfe-GKN-uC4iCeyqNznWF-gP5dGQyng_5MwsFWTJaj0xlsl5hyBXIAO0udslYa_IwP54n0waInJ2DfEppHWv-rmuzueVIq-0OVJdp2awS81BgylrOvwRjBCD7etrCX7tlxSBt5nmJ8pv0NTne0fkfm57xBO4gSk9DKnUoZW0HQdcysa5h2VpX1-S3cjUY1oHXGm8vU0U-MgPaur_exTq2QFeZTR7NcYyvi1dtghE_yf6KUNLhQPemTJ3XJqDVKLy8eUIcHD9RKS9UO1dFJUbMHb-eaBW-rUg7PeJmp7ydmO_9ZX0ZqsMf5M7sBx3DsYaMJzkueDeKMOq03r3w2qQRevkC-XQGhXBzziIK-efbQd8nHjReSjpjr2F9RV6mgQm4qWjWAF99X1PhjTzIl5L6-BMLDXYrTW8H5c4F1jBlchGU_6IqrHq0Sc4NdVj4i2YM):
```
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:72
  RollingUpdateDeployment should delete old pods and create new ones [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:47

  Expected error:
      <*errors.errorString | 0xc20802c8a0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:275
```

cc @janetkuo @kargakis @mqliang @nikhiljindal @ironcladlou @bgrant0607

**Comment by bgrant0607** [comment]
Previous failure for this test: #21810

Probably same issue as #19299

**Comment by janetkuo** [comment]
Looking at the [log](https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21776/kubernetes-pull-build-test-e2e-gce/30377/?debugUI=CLOUD), the timeout is due to waiting for pod expectations (0 add, 1 del) before reconciling old rs.

**Comment by bgrant0607** [comment]
Accounting of deletion expectations is very fishy (see #22061, #21963), but the workaround in #21963 should address this.
