### ISSUE TITLE
RFC: Create cloudprovider.Volumes interface

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#21984]
It would be nice if we had `Volumes` interface in our cloud providers which would encapsulate all volume operations:

```
type Interface interface {
	...
	Volumes() (Volumes, bool)
}

type Volumes interface {
	// Attach the disk to the specified instance
	// instanceName can be empty to mean "the instance on which we are running"
	// Returns the device (e.g. /dev/xvdf) where we attached the volume if known (on AWS), "" otherwise (GCE, OSP).
	// It's up to kubelet to find the device using udev when "" is returned.
	AttachVolume(volumeName string, instanceName string, readOnly bool) (string, error)

	// Detach the disk from the specified instance
	// instanceName can be empty to mean "the instance on which we are running"
	// Returns the device where the volume was attached if known (AWS), "" otherwise (GCE, OSP).
	DetachVolume(volumeName string, instanceName string) (string, error)

	// Create a volume with the specified options
	CreateVolume(volumeOptions *VolumeOptions) (volumeName string, err error)

	// Check if the cloud supports creation of volume with given options
	// (to report errors early, before attempting to create a volume with potentionally unsupported options)
	CheckCreateOptions(volumeOptions *VolumeOptions) error

	// Delete the specified volume
	// Must return no error when the volume was already deleted.
	DeleteVolume(volumeName string) error

	// Get labels to apply to volume on creation
	GetVolumeLabels(volumeName string) (map[string]string, error)
}
```
`Volumes` may not be the best term to use here, it can be confused with Kubernetes volumes and persistent volumes. Would `Disk` be better? `AttachDisk()`, `DetachDisk()`, ...

Especially note `CreateDisk` method. It accepts `VolumeOptions` argument, which specifies what voulme should be created in **a cloud agnostic way**. So far there are not so many options to choose from (see below). Is it future-proof? Will there be any really specific feature that would require one set of options on e.g. AWS and completelly different set on GCE?
```
// Options for CreateVolume() with requirement on the created volume
type VolumeOptions struct {
	// Requested size, required to be >0
	// (all three clouds work with GB)
	CapacityGB int64
	// Tags to be attached to the volume.
	// (GCE does not support tags, they are serialized as JSON to Description)
	Tags       *map[string]string
	// Type of the volume. "" = some default one.
	// (uknown volume type -> error)
	VolumeType string
	// Required IOPS. 0 means no preference.
	// When >0  and the cloud does not support IOPS -> error.
	IOPS       int64
	// Encryption requirement. nil - use default, true/false - do/don't encrypt
	// When no encryption explicitly requested and the cloud must encrypt (e.g. CGE) -> error
 	Encrypt    *bool

	// Additional parameters in future, e.g.:
	// Zone string
	// Region string
}
```

Benefits:
* Single interface to talk to - provisioners, deleters and attachers in some volume plugins could be probably simplified.
* Easier testing - there is no interface in openstack and gce cloud providers that I could mock in my provisioner tests.

Risks:
* It might not be possible to abstract all future options into generic `VolumeOptions` struct.

All three clouds already have required functionality, appropriate functions just needs to be renamed / moved and the function parameters and return values need to be adjusted accordingly.

I am willing to implement this proposal (i.e. rework the cloud providers and try to simplify provisioning plugins) if my schedule allows.

**Comment by jsafrane** [comment]
@saad-ali, you are my GCE contact, opinions?
@anguslees. anything to add for OpenStack?

And who's responsible for AWS?

cc: @kubernetes/sig-storage

**Comment by rootfs** [comment]
what about making `VolumeOptions` an union of types for individual volumes? Each cloud provider exposes the create volume input as part of the union.

What if you also add `ceph`, `iscsi` and `fc` (maybe want to set admission control, etc) into the picture?

**Comment by thockin** [comment]
This has been discussed before - there is not a 1:1 mapping of cloud
provider to volume type.  Any such API would have to overcome that extra
level of indirection.

**Comment by jsafrane** [comment]
@thockin, can you please point me to the discussion? If I look at current implementation of AWS, GCE and OSP cloud providers they do exactly the same thing, but each with different interface. I can make a generic one for volume management relatively easily, as suggested above.

Of course, there will be other volume plugins (NFS, iSCSI, ...) that will use other means of accessing the volumes and I won't touch these. There still will be VolumePlugin interfaces and anyone can implement them in any way. Which also answers @rootfs suggestion about ceph - you can still implement `volume.ProvisionableVolumePlugin`, you really don't need `cloudprovider.Interface` for that.
