### ISSUE TITLE
Have LimitRanger show ratio inputs when rejecting based on ratio

### ISSUE THREAD

**Issue by sosiouxme** [kubernetes/kubernetes#21996]
A user complains:

> If I set CPU Max Limit/Request Ratio=2 and memory Max Limit/Request Ratio=5 in LimitRange, when create a pod without resources specified, I got the error "[memory max limit to request ratio per Pod is 5, but provided ratio is 7.500000. cpu max limit to request ratio per Pod is 2, but provided ratio is 3.636364]". I have no idea where the provided ratios came from and how they were calculated.

Now this is partly just not knowing what the ratio is about, however I think there's a valid concern here: the user doesn't "provide" the ratio, it's calculated from the limit/request numbers, and those aren't necessarily provided by the user either.

So this is an enhancement request to have this error message also supply the actual numbers of the limit / request to give the user more clues about what's going on.

**Comment by derekwaynecarr** [comment]
Makes sense to me, will look to get a PR.

**Comment by spiffxp** [comment]
/sig api-machinery
because admission control
