### ISSUE TITLE
GKE upgrade-cluster step failed after 5 hours

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#21994]
Jenkins should never time out that suite; the timeout should be baked into the test.

http://kubekins.dls.corp.google.com/job/kubernetes-upgrade-gke-1.1-master-step5-upgrade-cluster/449/

**Comment by ihmccreery** [comment]
@saad-ali This isn't a test infra issue; it's an issue with the test itself.

**Comment by saad-ali** [comment]
@ihmccreery Thanks Ike. Please add the correct team label so that it can be triaged appropriately.

**Comment by ihmccreery** [comment]
No team owns upgrades right now, as far as I know.  It's team @ihmccreery :stuck_out_tongue:

**Comment by ihmccreery** [comment]
I'll put it in the control-plane team, since that's what subsumed cluster lifecycle, and will probably be responsible for upgrade quality, along with the GKE team.

**Comment by saad-ali** [comment]
> It's team @ihmccreery :stuck_out_tongue:

Ha! Nice

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gke
since we lack a sig-gcp at the moment

/assign
closing because we no longer use jenkins for upgrade tests
