### ISSUE TITLE
unable to create service with AWS load balancer for a pod running in single az.

### ISSUE THREAD

**Issue by supershal** [kubernetes/kubernetes#22004]
Kubernetes version: 1.1.7
I have one replica of a pod A running in AZ: us-west-2a. There is no other replica of pod A running in any other AZ.
btw, I have other different type of unrelated pods (B, C, D) deployed in all AZs (us-west-2a, us-west-2b and us-west-2c) 

I am trying to create service with ELB in front of the a pod A that exists only in us-west-2a zone.
ELB should pickup proper subnets before adding nodes.
I am getting following errors upon `kubectl describe svc <svcname>`
`Failed to create load balancer for service infra/influxdb-grafana-svc: InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.
        status code: 409, request id: 2b6cffba-dbe7-11e5-9671-655f0bcfa3a9`

```
  FirstSeen LastSeen    Count   From            SubobjectPath   Reason              Message
  ─────────   ────────    ───── ────            ───────────── ──────              ───────
  2m        2m      1   {service-controller }           CreatingLoadBalancerFailed  Error creating load balancer (will retry): Failed to create load balancer for service infra/influxdb-grafana-svc: error tagging security group: InvalidParameterValue: Value ( '' ) for parameter Tag key is invalid. Tag key cannot be null or empty.
        status code: 400, request id:
  2m        2m  1   {service-controller }       CreatingLoadBalancerFailed  Error creating load balancer (will retry): Failed to create load balancer for service infra/influxdb-grafana-svc: InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.
        status code: 409, request id: 2b6cffba-dbe7-11e5-9671-655f0bcfa3a9
  2
```

ref issue: [#13056](https://github.com/kubernetes/kubernetes/issues/13056)

**Comment by jcderr** [comment]
I'm also seeing this.

**Comment by quinton-hoole** [comment]
@justinsb FYI
Possibly related to "AWS Feature: Services can share an ELB (#23483)"

**Comment by justinsb** [comment]
@jcderr  @supershal did you use kube-up?  It sounds like your subnets are not tagged.

**Comment by supershal** [comment]
@justinsb we are not using kube-up to bring up minions in aws. Our subnets are tagged. We will again try with version 1.2 in a day or two and get back to you.

**Comment by justinsb** [comment]
@supershal interesting.... we're reworking kube-up so that it works for everyone.  Can I ask why you didn't want to use kube-up?  I want to make sure everyone's use-case is covered for kube-up v2...

**Comment by supershal** [comment]
@justinsb We use terraform and ASG for our current cloud provisioning. We want to have same set of tools for our existing cloud and kubernetes. We provisioned kubernetes masters, etcd and minions using terraform and ASG.

**Comment by paralin** [comment]
@supershal https://github.com/kubernetes/kubernetes/issues/23478

I like that you're using terraform. I think the only problem here is that Kubernetes expects some things to be constant about the environment you're under, like tagged subnets. It might be good to document this and maybe make an official Terraform repo for setting up Kubernetes?

**Comment by lattwood** [comment]
@paralin might want to touch base with these folks to see if what they've done is usable for an 'official' terraform repo.

**Comment by justinsb** [comment]
We now have logic to better choose subnets; I am going to assume this is resolved.  Please reopen if not.

**Comment by jcderr** [comment]
@justinsb what version did this better logic arrive in?
