### ISSUE TITLE
hack/lib/etcd.sh should enforce a higher version of etcd

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#22002]
Currently it enforces etcd version >= 2.0. https://github.com/kubernetes/kubernetes/blob/master/hack/lib/etcd.sh#L35

etcd 2.0 has known issues such as missing watch events (https://github.com/kubernetes/kubernetes/issues/20498#issuecomment-183095279), we should enforce a higher version, probably enforce the version defined in install-etcd.sh: https://github.com/kubernetes/kubernetes/blob/master/hack/install-etcd.sh#L23

@lavalamp for triage.

**Comment by lavalamp** [comment]
I think @ixdy regularized the etcd version we install? Maybe this script should get its etcd version from the same place.

**Comment by ixdy** [comment]
Unfortunately the etcd version is specified in many places.

`hack/install-etcd.sh` is what we use in CI, and it's currently installing v2.2.1.
A pretty simple search for "2.2.1" shows it's specified in many other places, too:
* build/build-image/cross/Dockerfile
* cluster/centos/config-build.sh
* cluster/images/etcd/build-etcd.sh
* cluster/images/etcd/Makefile
* cluster/images/hyperkube/etcd.json
* cluster/mesos/docker/docker-compose.yml
* cluster/mesos/docker/test/bin/install-etcd.sh
* cluster/saltbase/salt/etcd/etcd.manifest
* cluster/saltbase/salt/flannel-server/flannel-server.manifest
* cluster/ubuntu/download-release.sh
* docs/admin/etcd.md
* docs/getting-started-guides/docker-multinode/master.md
* docs/getting-started-guides/docker-multinode/master.sh
* docs/getting-started-guides/docker-multinode.md
* docs/getting-started-guides/mesos.md
* docs/getting-started-guides/scratch.md
* docs/getting-started-guides/ubuntu.md
* test/kubemark/start-kubemark-master.sh

(And there may be places specifying a different version.)

I'd love to have a single source of truth for the version of etcd to use, but I'm not sure how to get there.

I guess at the very least it'd be easy to update hack/lib/etcd.sh to enforce etcd >= 2.2.1. I don't have bandwidth to do that right now, but I'll review a PR if you want to send one.

**Comment by ixdy** [comment]
Actually, easy enough to fix. PR incoming...

**Comment by caesarxuchao** [comment]
Maybe we should check etcd version in the apiserver and give warning from there?

**Comment by ixdy** [comment]
@caesarxuchao not sure where the error message would be sent in that case, but it seems like a reasonable idea (if not already done).

**Comment by fejta** [comment]
@ixdy looks like your PR is nearly merged, I'm assigning this back to you (and also added a P1 label to the PR).
