### ISSUE TITLE
actors participating in leaderelection should annotate objects with a sequence number of the leadership

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#22007]
This allows actors to self validate their leadership over single objects.

We can implement a monotonically incrementing sequence number in the leader election record easily. Actors should annotate objects that they sync with this sequence number. Actors should not sync objects that have a sequence number greater then the actor's current sequence number.

This ensures that leader transition is atomic over single objects in the worst case, which is a guarantee we do not have today.

cc @bgrant0607 @davidopp @timothysc

**Comment by timothysc** [comment]
> We can implement a monotonically incrementing sequence number in the leader election record easily.  

This is very similar to http://zookeeper.apache.org/doc/trunk/recipes.html#sc_leaderElection use of sequence number.

**Comment by bgrant0607** [comment]
cc @thockin @saad-ali @childsb

**Comment by timothysc** [comment]
@mikedanese is there any reason we couldn't just use the objects ResourceVersion ?

**Comment by mikedanese** [comment]
@timothysc resource version of what?
