### ISSUE TITLE
Documentation breaks command-click to open in new tab

### ISSUE THREAD

**Issue by davidmankin** [kubernetes/kubernetes#22018]
I've been reading the docs as I learn Kubernetes (e.g. http://kubernetes.io/v1.1/docs/user-guide/connecting-applications.html).  When I command-click on a link (such as "how we achieve this") it doesn't open the link in a new tab but instead replaces the same page I reading.  This is not very nice and gets in the way of my exploring effectively. 

Control click and choosing "open in new tab" works, but command-click is standard so there must be some javascript nonsense that breaks it.

In general, it seems like the k8s docs are trying to be too clever. e.g. Why is there an inch of screen realestate wasted in top nav at all times? Pressing space or page down scrolls up too far and I lose several lines behind the top nav. Why does the color at the top change as I scroll? That is distracting.

_Browser Chrome Version 48.0.2564.116 (64-bit) on OS X 10.10.5._

**Comment by bgrant0607** [comment]
We've redone the whole site. This seems to work now.
