### ISSUE TITLE
Add documentation explaining steps required to add a node to a cluster

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#22012]
I am user support on call today and people are asking for documentation regarding steps required to add a node to a cluster.
I could not find any good documentation on searching.

There was a SO answer explaining it: http://stackoverflow.com/a/32657176

I think it will be good to explain it in our official documentation.

**Comment by roberthbailey** [comment]
The flags to pass to each binary on the nodes varies based on the install method, so there isn't a single "right" way that we could or should document this.

Since kubeadm is designed specifically to address this use case, I'm going to close this as obsolete.
