### ISSUE TITLE
Sporadic "too old resource version" errors from master pods

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#22024]
We see sporadic "too old resource version" errors from the master pods.

(We understand from http://stackoverflow.com/questions/34322969/cause-of-apiserver-received-an-error-that-is-not-an-unversioned-errors-from-ku/34330607 that this could be expected behavior during an upgrade -- can we get confirmation of that, and will those be changed from "error" level to "warning" level at any point?)

Our bigger concern is that these errors continue to occur -- not constantly, but routinely, anywhere from hours to minutes between them.

Is there something we need to perform in order to alleviate this error spam?

Specifically, when we restart our HA masters (eg for an upgrade), we delete the master nodes, regenerate pod yamls, restart hyperkube, then patch the master nodes to be unschedulable:

```
kubectl --server=https://10.1.4.41:6443 --kubeconfig=... delete node sea5m1kmaster1
node "sea5m1kmaster1" deleted

kubectl --server=https://10.1.4.41:6443 --kubeconfig=... delete node sea5m1kmaster2
node "sea5m1kmaster2" deleted

# generate fresh yamls for apiserver / podmaster / scheduler / controller manager
# restart hyperkube

kubectl --server=https://10.1.4.41:6443 --kubeconfig=... patch node sea5m1kmaster1 -p {\"spec\":{\"unschedulable\":true}}
"sea5m1kmaster1" patched

kubectl --server=https://10.1.4.41:6443 --kubeconfig=... patch node sea5m1kmaster2 -p {\"spec\":{\"unschedulable\":true}}
"sea5m1kmaster2" patched
```

Every now and then, unrelated to any restarts or other visible errors, we get 1-2 of these errors on our masters:

```
2016-02-25T18:42:48.7850+00:00 tuk6r2kmaster2 [err] [docker] E0225 18:42:48.785758       1 errors.go:62] apiserver received an error that is not an unversioned.Status: too old resource version: 1785219 (1787027)
2016-02-25T18:42:48.7870+00:00 tuk6r2kmaster2 [err] [docker] E0225 18:42:48.787036       1 reflector.go:227] /usr/src/go/src/runtime/asm_amd64.s:2232: Failed to watch *api.Pod: too old resource version: 1785219 (1787027)
2016-02-25T18:46:00.7180+00:00 tuk6r2kmaster2 [err] [docker] E0225 18:46:00.718118       1 errors.go:62] apiserver received an error that is not an unversioned.Status: too old resource version: 1785219 (1787027)
2016-02-25T18:46:00.6850+00:00 tuk6r2kmaster1 [err] [docker] E0225 18:46:00.685606       1 errors.go:62] apiserver received an error that is not an unversioned.Status: too old resource version: 1785219 (1787027)
2016-02-25T18:46:00.7880+00:00 tuk6r2kmaster1 [err] [kubelet] E0225 18:46:00.716662    3999 reflector.go:227] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: too old resource version: 1785219 (1787027)
2016-02-25T18:46:01.1700+00:00 tuk6r2kmaster2 [err] [kubelet] E0225 18:46:00.688601   62642 reflector.go:227] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: too old resource version: 1785219 (1787027)
```

Is this indicative of a problem, perhaps in our upgrade flow? Or is this expected routine log behavior?

**Version Info:**

```
$ kubectl --server=https://10.1.4.41:6443 --... version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}
```

**Comment by bgrant0607** [comment]
An example from @termit on slack https://gist.github.com/roman-shuhov/fb3fe7605152a7e9e7f7

```
I0309 05:56:57.564279       1 handlers.go:131] GET /api/v1/watch/endpoints?resourceVersion=14145456: (468.125µs) 500
goroutine 297 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2087c7140, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7fc1dd355fe0, 0xc2080a1320, 0x7fc1dd3567f8, 0xc209508d80, 0x7fc1dd1a3050, 0xc2087c7140, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:389 +0x89
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7fc1dd350fc0, 0xc208395ba0, 0x7fc1dd355fe0, 0xc2080a1320, 0x7fc1dd1a3050, 0xc2087c7140, 0xc208356c80)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:416 +0xab
k8s.io/kubernetes/pkg/apiserver.func·026(0xc208dbb830, 0xc2087c7260)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:256 +0xc2a
github.com/emicklei/go-restful.func·009(0xc208dbb830, 0xc2087c7260)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc208dbb920, 0xc208dbb830, 0xc2087c7260)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc208dbb830, 0xc2087c7260, 0xc208dbb920)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:62 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc208dbb920, 0xc208dbb830, 0xc2087c7260)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2087370e0, 0x7fc1dd1a3050, 0xc2087c7140, 0xc2095f2f70)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246 +0xee3
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7fc1dd1a3050, 0xc2087c7140, 0xc2095f2f70)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/sr [[hyperkube/v1.1.8 (linux/amd64) kubernetes/a8af33d] 10.242.114.51:60742]
E0309 05:56:57.565001       1 errors.go:62] apiserver received an error that is not an unversioned.Status: too old resource version: 14145457 (14145478)
```

cc @wojtek-t @lavalamp

**Comment by bgrant0607** [comment]
Should be documented in known issues #21000 if we're not going to fix it. It generates a lot of noise, though.

**Comment by wojtek-t** [comment]
Looking into logs from the original post, it seems there are 2 different issues:

first is the problem in the communication apiserver <->etcd:
    
     2016-02-25T18:42:48.7850+00:00 tuk6r2kmaster2 [err] [docker] E0225 18:42:48.785758       1 errors.go:62] apiserver received an error that is not an unversioned.Status: too old resource version: 1785219 (1787027)

second is the problem with communication apiserver <-> client

    2016-02-25T18:42:48.7870+00:00 tuk6r2kmaster2 [err] [docker] E0225 18:42:48.787036       1 reflector.go:227] /usr/src/go/src/runtime/asm_amd64.s:2232: Failed to watch *api.Pod: too old resource version: 1785219 (1787027)

The latter is a clear consequence of the former (the time is also matching).

The former: "apiserver <-> etcd" error seems strange - we don't observe those even in very large clusters.
@DreadPirateShawn - do you have enough network bandwidth between apiserver and etcd? This might be related to something like that.

For the former, I don't think we can do much other than documenting it.

**Comment by lavalamp** [comment]
Filed #22830 about the error message, still reading rest of issue.

**Comment by lavalamp** [comment]
Basically, you're getting an out-of-window message, which is totally normal and expected, and has nothing whatsoever to do with your upgrade flow AFAICT. We will continue to print a message here. The thing wrong is that the error is not interpreted correctly, somehow we've started returning a 500 and the message is confusing. This should not be 500 nor should it print a stack trace. I will follow up on this in #22830, since I already filed it.

**Comment by lavalamp** [comment]
As pointed out in #22830, the error message was fixed by #16628.

IMO you should not worry about "errors" in Kubernetes log files unless there's a corresponding symptom. Kubernetes is designed to be self-healing; errors should all be recoverable & not require admin intervention. If they do require admin intervention, the error message should make that very clear, and/or I'd expect some obvious symptom, like the program exiting.

**Comment by DreadPirateShawn** [comment]
@lavalamp First and foremost, many thanks for your help and attention! 

That being said, will this still be an "error"-level log, or will it be lowered to "warning/info/etc"-level, since it's expected behavior?

The problem with ignoring errors (quotes deliberately omitted) in Kubernetes log files that is that it's basically recommending to put tape over the engine warning lights.

For instance, one big problem is that the symptom may not always be immediately apparent -- they don't all result in pods dying. (For instance, routing misconfiguration can cause "kubectl log" to fail even though scheduling works fine, which can be a nasty surprise once someone tries to check logs in prod... node advertise-address misconfiguration can result in etcd thrashing and steady error logs without technically "breaking" anything...) Kubernetes does self-heal errors, but when you see the same error occurring steadily and always, that's generally a sign that you're looking at something that isn't working properly, not simply a random error that Kubernetes recovered from.

Logging something as "error"-level means that you're concerned about it, which means that I'M concerned about it too.

Waiting until something breaks heavily enough to get a phone call in the middle of the night, or until some new service pod runs into the previously-subtle symptom and fails a deployment -- that's not a sustainable approach.

(Also, as you get more adoption by companies using Kubernetes clusters in prod environments, you're going to have more QA & prod requirements that any and all error logs are investigated fully to completion -- saying "we don't see anything obviously broken" isn't sufficient for us to close our tickets, whether we personally suspect that we don't need to worry about it or not.)

**Comment by DreadPirateShawn** [comment]
PS: I'm in the #kubernetes-users slack chat as well, user sfalknerhorine, if you want to chat more without an audience :-) -- this is admittedly a bit more philosophical and tangential to the main topic of fixing the etcd response handler, but it may very well come up again as we pursue other various error-level logs.

**Comment by lavalamp** [comment]
This will now print in API server as a 410 HTTP response, instead of the stack trace.

I think components doing watches may still log something when a watch is dropped. I can definitely see your point, and there have been other complaints about this message.

**Comment by lavalamp** [comment]
I have a lot to say about this message, but lack the time today to say it. So I'll leave this issue open a bit longer.

**Comment by DreadPirateShawn** [comment]
@lavalamp Any update on this?

**Comment by wojtek-t** [comment]
@DreadPirateShawn - a looooot of things has changed since this issue was opened. Do you observe the same issue in the newer releases?
[BTW - once we luanch etcd v3 as our backend storage, which should happen soon, this should also help with that]

**Comment by DreadPirateShawn** [comment]
@wojtek-t Great question.

We definitely see it on Kubernetes 1.2.2.

However, we attempted to upgrade to Kube 1.4 and Docker 1.12 recently, but ultimately ran into docker/docker#27607 as a blocker issue, and we needed to perform a full rollback. We considered trying to upgrade each separately, but at this point it makes more sense to wait for Docker 1.13 (pending soon) and revisit.

**Comment by obeattie** [comment]
We definitely see it in our production cluster running 1.3.x. We'll be upgrading to 1.4.6 in the next few days, so I will post an update soon about whether the issue is still present.

**Comment by yvespp** [comment]
Seeing this with client-go 1.5 and Kubernetes v1.4.3 on minikube. See https://github.com/containous/traefik/pull/836

**Comment by jianzhangbjz** [comment]
@wojtek-t I encounter the same problem, how to solve it? The errors as the following:
```
W1117 07:31:01.865813       1 reflector.go:330] vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: watch of *v1.Endpoints ended with: too old resource version: 1205751 (1205872)
```
K8s version:
```
root@heatonli-test1:~/sl-vpn# kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.5-beta.0+$Format:%h$", GitCommit:"5f79a5d3909d62b20a87c9cd4e3699cb4dc94d25", GitTreeState:"dirty", BuildDate:"2016-10-25T07:14:10Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.5-beta.0+$Format:%h$", GitCommit:"f4f5c21d73fc8eaff3dbec55e3d902fb3f32cedb", GitTreeState:"dirty", BuildDate:"2016-11-01T05:49:02Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
Docker version:
```
root@mfeng-m60-2:/tmp# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64
```

**Comment by lavalamp** [comment]
Looks like this message is now a warning only. It really is not a problem unless you see it continuously (like, multiple times per second). If we make it informational only will that make you all feel better? :) :)

**Comment by DreadPirateShawn** [comment]
It'll most certainly make our QA dept and error-monitoring tools feel better. ;-) :-D

**Comment by jianzhangbjz** [comment]
Sure, certainly.

**Comment by timoreimann** [comment]
We also see it happening sporadically (every few minutes) with client-go 2.x and Kubernetes 1.6 (through [containous/traefik](https://github.com/containous/traefik/)).

@lavalamp I'd be interested in taking a stab at lowering the log level to informational. Is this still something you'd be okay with?

**Comment by grzesuav** [comment]
Spotted in v1.10.12

**Comment by Disturbing** [comment]
Spotted v1.11.7 on GKE.

**Comment by lavalamp** [comment]
My prior [comment](https://github.com/kubernetes/kubernetes/issues/22024#issuecomment-261629605) remains accurate. This is expected at least occasionally during the normal course of operations. I'm fine with lowering the log level (I'm surprised if it hasn't already happened).

**Comment by OlegPS** [comment]
These messages creates noise in the logs with warn severity. If you make it informational that will be right, as this is just a "normal course of operations". Thanks!

**Comment by sharkymcdongles** [comment]
+1 If this isn't useful info or relevant we should put this to a info log level. It creates a bunch of noise.

**Comment by Starefossen** [comment]
I'm seeing this is logs from application connecting to the kubenretes API using the official API clients. This should definitly be handled better then just ignore it.

**Comment by gmauleon** [comment]
If it's something we don't have to act upon and we don't want to be polluted, I would go even further and push that to debug level. 
Honestly, I would love not to see it at all. All our Prometheus are spitting that out every 3/5 seconds and that means $$$ in stackdriver bills on GKE :(

**Comment by smiklosovic** [comment]
please is this going to be fixed? My operator is failing on this and it restarts constantly.

**Comment by wojtek-t** [comment]
See this comment: https://github.com/kubernetes/kubernetes/issues/22024#issuecomment-195107535
This is working as expected and is not going to be fixed.

**Comment by lavalamp** [comment]
Given the bookmarks @wojtek-t has recently added, I'd expect this to be happening much less.

Folks reporting this happening to you: what version are you running? If it's a recent version, and you're seeing a lot of these, it's possible your cluster is so highly loaded that your controllers are having a hard time maintaining watches.

@smiklosovic: 
> please is this going to be fixed? My operator is failing on this and it restarts constantly because it is trying to write to a file in /tmp and it says it cant because the file it tries to write it to does not exist.

This doesn't sound related.

**Comment by smiklosovic** [comment]
The issue I have is that I had read-only fs in my operator container so it failed to write it hence it crashed container. Once I made it possible to be writable, it is not an issue anymore (at least it does not crashes) but the fact that it writes these messages in the first place is another problem. My cluster is not under heavy load at all. I have it provisioned it locally on my notebook, completely self-hosted.

**Comment by lavalamp** [comment]
@smiklosovic 

> Once I made it possible to be writable

Yeah, we have lots of log messages in general so you needed to do that. It's not related to this particular message.

> the fact that it writes these messages in the first place is another problem

Unless you see gobs of these they really are working as intended. If you do see gobs of them, maybe your cluster is more loaded than you think.

**Comment by tvvignesh** [comment]
Getting the same logs on v1.15.1 Hope, I don't have to worry about this.

![Screenshot from 2020-01-30 16-35-30](https://user-images.githubusercontent.com/1165845/73444464-a1571300-437e-11ea-926b-2fcf260a29da.png)

**Comment by lavalamp** [comment]
Yeah, those are multiple minutes apart, completely expected behavior. Also, almost certainly exercising the case that the previously mentioned Bookmarks will optimize.

**Comment by connatix-cradulescu** [comment]
I am facing same warring too, on my Nginx controller on AWS EKS cluster

```text
Server Version: version.Info{Major:"1", Minor:"14+"
W0226 20:14:23.742568       6 reflector.go:299] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:159: watch of *v1.Pod ended with: too old resource version: 3559888 (3561932)
W0226 23:08:00.770436       6 reflector.go:299] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:159: watch of *v1.Pod ended with: too old resource version: 3632506 (3636033)
W0226 23:56:05.779997       6 reflector.go:299] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:159: watch of *v1.Pod ended with: too old resource version: 3713676 (3713744)
W0227 02:50:02.810742       6 reflector.go:299] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:159: watch of *v1.Pod ended with: too old resource version: 3740760 (3742356)
W0227 06:11:06.846067       6 reflector.go:299] k8s.io/ingress-nginx/internal/ingress/controller/store/store.go:159: watch of *v1.Pod ended with: too old resource version: 3820919 (3824391)
```

**Comment by antoineco** [comment]
@connatix-cradulescu this is perfectly expected, no worries. The messages are several hours apart.

When nothing happens in your cluster, the watches established by the Kubernetes client don't get a chance to get refreshed naturally, and eventually time out. These messages simply indicate that these watches are being re-created.

**Comment by dobber** [comment]
Is it possible to change the error message from
`v1.ConfigMap ended with: too old resource version`
to
`Maintenance of client connections due to low traffic, re-creating"
or something like that. 

I'm debugging an issue in my cluster and the only warning in my logs leads me to this rabbit hole here. I spend an hour chasing this, instead of fixing the real issue.

**Comment by lavalamp** [comment]
Yes, I'm totally open to the message being improved.

**Comment by fvigotti** [comment]
> I'm debugging an issue in my cluster and the only warning in my logs leads me to this rabbit hole here.
Me too, another thing is that this message if it's a normal and expected should not be leveled as "W"arning but "I"nfo

**Comment by TetsujinOni** [comment]
> Yes, I'm totally open to the message being improved.

Has there been an unlinked PR proposed to make this language change?

**Comment by renepupil** [comment]
> These messages simply indicate that these watches are being re-created.

@antoineco @lavalamp How long should that take?

In our case we had that warning persisted over several releases when timing out waiting for a specific job in our releases `kubectl wait --for=condition=complete --timeout=300s job/migration`.

My only guess is, that this was "bad timing" in a way that we always waited for the condition when the watches are being recreated again, but I would not expect that to take more then 5 minutes...

Any idea how to mitigate that?
