### ISSUE TITLE
Can the submit queue merge PRs in batches?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22035]
Could we process the submit queue faster if we batched PRs together?  For example if we took the next 10 PRs in the queue, applied them all together, tested, and then merged all 10 if they passed.  I presume that the need to run e2e on every merging PR in series is the primary bottleneck?

The downside is that it will be harder to track down a bad commit that causes flakes (because there will be more PRs), but I'm not sure we find this particularly easy now anyway.

**Comment by mikedanese** [comment]
cc @lavalamp @eparis @ixdy

**Comment by bprashanth** [comment]
> The downside is that it will be harder to track down a bad commit that causes flakes (because there will be more PRs), but I'm not sure we find this particularly easy now anyway.

This will help if most prs pass e2es, or fail for completely unrelated reasons. Currently we have a lot of test flake, but the goal is to have little to none of it, so if you hit a failure you *know* it's your fault. This will not be true with a batched run, and after a group fails someone has to go through and identify the bad pr so it doesn't infect the next batch.

**Comment by justinsb** [comment]
I guess I first want to be sure that the problem causing our submit queue merges to be slow is that merging a PR requires a full e2e test run (of master + PR), and that this must be done in series.  It could be that the actual root cause is our high volume of PRs for 1.2, but I think our volume will only increase.  I also don't want us to be thinking about reducing e2e checks because we think they will slow down merges - my personal feeling is that the more brutal our e2e checks the less likely we are to have flakes later.

We do have freedom in how the system chooses a batch - I don't think a human should have to intervene.  We could say that every time a PR fails a batch commit it gets kicked out of the queue and must be re-tested individually.  I for one would have a lot of fun with a heuristic system that tried to pick PRs for the batch, with say a suspicion score on a PR, increasing the score each time it failed a batch commit.  There's some experimental design theory we could leverage.

To be merged today, a PR must pass an e2e run before being eligible to be merged, and then must pass e2e again as part of the merge.  A flake therefore occurs when it passes those two e2e runs but then fails later.  I don't think this changes here if we "randomize" the batch.

The downside I was trying to describe is that we advance the head much faster.  So if we assume a PR has 10% chance of failure, it can pass two e2e runs fairly easily through luck, but it'll likely fail sometime in the next ~10 e2e runs.  With single-advancing, that failure can likely be attributed to 1 or 2 PRs, but now it would be 10 or 20 PRs.  But I think the bigger problem here is when PRs have a 1% chance of failure: we're not going to find that by looking at the merge history - we have to look at the error and look at the code.  You all have more experience here, but I think our problems are more in the 1% than the 10% category - i.e. we have to look at the code.

Of course, this also suggests a strategy to pick a batch comprised of PRs with good "distance" from each other (i.e. don't commit 10 PRs all tweaking the scheduler in a batch), so when you have a scheduler flake you can easily whittle down the 20 PRs to the 2 PRs that touched the scheduler.

**Comment by eparis** [comment]
The problem with out submit queue is that the google internal e2e stay red so often it almost never makes progress. Not the time it takes to run the e2e.  e2e takes < 30 minutes, so we should be able to merge ~48 PRs per day. Now look at the bot history:

https://github.com/k8s-merge-robot

Right after we did the mad test flake scramble we had the 2 highest days ever. 34 one day and 39 the next. Then we started treading downhill again.

You can see here:
http://submit-queue.k8s.io/#/history
When the google internal e2e goes red and green. I have been thinking about tracking how often and how long each test/all tests are green. But if we get that to stay green all day the queue will stay empty.

Yes the batch thing is likely somehow possible (we'd have to work with @ixdy to figure out how to build the commit/branch for the branch we wanted tested) and it would keep the queue empty, but it wouldn't fix the 'real' problem.....

**Comment by justinsb** [comment]
Ah OK @eparis thanks for the correction.  We'll need batching one day, but it is not today's problem!

**Comment by lavalamp** [comment]
The point of the merge queue is to serialize merges so that we don't merge
things that make the tests go red.

We could "batch" by:
1. Define N merge branches (like 5)
2. In branch n, merge the first n PRs in the queue
3. Run tests on all N branches
4. Merge the highest-indexed branch that passes.

This is complicated & resource intensive, so we haven't done it.

**Comment by justinsb** [comment]
I think it's moot, but I was proposing the most optimistic strategy, where we pick N commits and then run the tests all-or-nothing only on that set of N.  Your strategy of evaluating subsets concurrently is better, but is indeed harder!

**Comment by kargakis** [comment]
Yes, now it does.
