### ISSUE TITLE
skydns not working properly

### ISSUE THREAD

**Issue by mfanjie** [kubernetes/kubernetes#22042]
We are using K8S as our private container engine and we ran into several problems on skydns addons, our host OS is fedora
[fedora@kubernetes-minion1 ~]$ cat /etc/issue
Fedora release 21 (Twenty One)
Kernel \r on an \m (\l)
####Problem description
1). kube2sky terminated with OOMKilled error
 PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    1     0 root     S     392m  0.3   5  0.0 /kube2sky -domain=kubernetes.local
We fixed this problem by remove the resource limit on kube2sky container, and I found previous discussion on the memory setting for those containers in issue #8042, seems in our environment, the memory consume of kube2sky is extremely high.
Our env info is like following
kubectl get pods --all-namespaces|wc -l
     310
kubectl get svc --all-namespaces|wc -l
     117
kubectl get nodes|wc -l
      54
2) skydns container got killed repeatedly
check pod description
skydns:
    Container ID:	docker://d4c3f3273d34443bac0da954ebfd3319ad53681a6ac3964f89dbcecda401b7c4
    Image:		conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c
    Image ID:		docker://a0835f7bffb9231347e5bbcb5a68f0ed45598978a9b15365ba440a136a5097d6
    QoS Tier:
      cpu:	Guaranteed
      memory:	Guaranteed
    Limits:
      memory:	50Mi
      cpu:	100m
    Requests:
      cpu:			100m
      memory:			50Mi
    State:			Running
      Started:			Fri, 26 Feb 2016 10:27:50 +0800
    Last Termination State:	Terminated
      Reason:			Error
      Exit Code:		2
      Started:			Fri, 26 Feb 2016 10:27:10 +0800
      Finished:			Fri, 26 Feb 2016 10:27:48 +0800
    Ready:			True
    Restart Count:		27
    Environment Variables:
...
Events:
  FirstSeen	LastSeen	Count	From								SubobjectPath		Reason	Message
  ─────────	────────	─────	────								─────────────		──────	───────
 1m	1m	1	{kubelet kubernetes-minion1}	spec.containers{skydns}	Created		Created with docker id e5712f554649
  1m	1m	1	{kubelet kubernetes-minion1}	spec.containers{skydns}	Started		Started with docker id e5712f554649
  19h	18s	1462	{kubelet kubernetes-minion1}	spec.containers{skydns}	Unhealthy	Readiness probe failed: Get http://172.20.124.131:8080/healthz: dial tcp 172.20.124.131:8080: network is unreachable
  19h	18s	1235	{kubelet kubernetes-minion1}	spec.containers{skydns}	Unhealthy	Liveness probe failed: Get http://172.20.124.131:8080/healthz: dial tcp 172.20.124.131:8080: network is unreachable
  17s	17s	1	{kubelet kubernetes-minion1}	spec.containers{skydns}	Killing		Killing with docker id e5712f554649

I put script on both healthz and skydns to wget http://172.20.124.131:8080 and http://127.0.0.1:8080, and both works, the only different in very short time(seconds to minutes), container skydns is killed with above error.

the following is logs on the minion, please note nslookup works when skydns container is running.

Feb 26 02:31:33 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:33Z" level=info msg="GET /images/conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c/json"
Feb 26 02:31:33 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:33Z" level=info msg="+job image_inspect(conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c)"
Feb 26 02:31:33 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:33Z" level=info msg="-job image_inspect(conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c) = OK (0)"
Feb 26 02:31:33 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:33Z" level=info msg="POST /containers/create?name=k8s_skydns.a2cb16fd_kube-dns-v10-etqab_kube-system_7636e496-db7d-11e5-8ed1-74dbd1a04bc0_c5e1ee82"
Feb 26 02:31:33 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:33Z" level=info msg="+job create(k8s_skydns.a2cb16fd_kube-dns-v10-etqab_kube-system_7636e496-db7d-11e5-8ed1-74dbd1a04bc0_c5e1ee82)"
Feb 26 02:31:34 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:34Z" level=info msg="+job log(create, 12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f, conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c)"
Feb 26 02:31:34 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:34Z" level=info msg="-job log(create, 12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f, conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c) = OK (0)"
Feb 26 02:31:34 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:34Z" level=info msg="-job create(k8s_skydns.a2cb16fd_kube-dns-v10-etqab_kube-system_7636e496-db7d-11e5-8ed1-74dbd1a04bc0_c5e1ee82) = OK (0)"
Feb 26 02:31:34 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:34Z" level=info msg="+job log(start, 12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f, conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c)"
Feb 26 02:31:34 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:34Z" level=info msg="-job log(start, 12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f, conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c) = OK (0)"
Feb 26 02:31:35 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:31:35Z" level=error msg="Unable to RegisterMachine k8s_skydns.a2cb16fd_kube-dns-v10-etqab_kube-system_7636e496-db7d-11e5-8ed1-74dbd1a04bc0_c5e1ee82 for 12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f: Invalid machine name"
Feb 26 02:32:07 kubernetes-minion-52-3770 kubelet[18925]: I0226 02:32:07.056562   18925 prober.go:129] Liveness probe for "kube-dns-v10-etqab_kube-system:skydns" failed (failure): Get http://172.20.124.131:8080/healthz: dial tcp 172.20.124.131:8080: network is unreachable
Feb 26 02:32:07 kubernetes-minion-52-3770 kubelet[18925]: I0226 02:32:07.056648   18925 manager.go:1769] pod "kube-dns-v10-etqab_kube-system" container "skydns" is unhealthy (probe result: failure), it will be killed and re-created.
Feb 26 02:32:07 kubernetes-minion-52-3770 kubelet[18925]: I0226 02:32:07.057023   18925 manager.go:1404] Killing container "12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f skydns kube-system/kube-dns-v10-etqab" with 30 second grace period
Feb 26 02:32:07 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:32:07Z" level=info msg="+job log(die, 12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f, conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c)"
Feb 26 02:32:07 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:32:07Z" level=info msg="-job log(die, 12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f, conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c) = OK (0)"
Feb 26 02:32:07 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:32:07Z" level=info msg="+job log(stop, 12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f, conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c)"
Feb 26 02:32:07 kubernetes-minion-52-3770 docker[11798]: time="2016-02-26T02:32:07Z" level=info msg="-job log(stop, 12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f, conatiner.repositry/kubernetes/skydns:2015-10-13-8c72f8c) = OK (0)"
Feb 26 02:32:08 kubernetes-minion-52-3770 kubelet[18925]: I0226 02:32:08.177747   18925 manager.go:1438] Container "12e11c1fceac2ee102a69ff79faf479ef23a5be10bdc43aa432275dd345dc21f skydns kube-system/kube-dns-v10-etqab" exited after 1.120643896s

**Comment by bprashanth** [comment]
@ArtfulCoder

**Comment by mfanjie** [comment]
something I am sure about is the skydns image should be updated, the current skydns skydns:2015-10-13-8c72f8c is based on a quite old busybox, and if you run ip addr inside the container, ip segement fault will always be thrown, this is a known issue of busybox container, and it has been fixed.
But it does not help us to resolve the skydns crashes problem, even I rebuilt skydns with latest busybox and skydns build, the problem is identical.
I need some hints here about why "network is unreachable" is reported. To me it looks like skydns container can not reach healthz on 8080, but actual it can.

**Comment by bprashanth** [comment]
Can you just exec into the exechealthz container of skydns and check that the probe command works? something like:
kubectl exec -it kub-dns-pod -c exechealthz /bin/sh
nslookup kubernetes 127.0.0.1

And the ssh into the node and curl the /healthz endpoint just like the kubelet does?

**Comment by mfanjie** [comment]
@bprashanth thanks for help. No, this command always failed.
kubesys exec kube-dns-v10-etqab -c healthz nslookup kubernetes.default 127.0.0.1
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

nslookup: can't resolve 'kubernetes.default'
error: error executing remote command: Error executing command in container: Error executing in Docker Container: 1
I am sure at the same moment, nslookup on other pod worked.
kubectl exec busybox-sleep nslookup kubernetes.default
Server:    10.247.0.10
Address 1: 10.247.0.10

Name:      kubernetes.default
Address 1: 10.247.0.1

**Comment by mfanjie** [comment]
I was tend to narrow down the problem so I created a simple liveness pod with the following Dockerfile and the same problem happened.
After the pod being created, it was assigned ip 172.20.182.147, curl on the probe path, 
some time it return ok, and the container would be killed and restarted repeatedly.
curl 172.20.182.147:8080/healthz
ok
some time it return with error
curl 172.20.182.147:8080/healthz
error: 12.922568008

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - args:
    - /server
    image: gcr.io/google_containers/liveness
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 15
      timeoutSeconds: 10
    name: liveness

**Comment by ArtfulCoder** [comment]
My suspicion without going into much depth yet, is, kube2sky can't talk to APi server.
Check kube2sky logs..

**Comment by mfanjie** [comment]
kube2sky did not dump any logs.

**Comment by mfanjie** [comment]
one quick update, after I recompile skydns and exechealthz with latest code from community and rebuild image. The problem was gone, keep monitoring over weekend.

**Comment by mfanjie** [comment]
skydns image in gcr.io should be refreshed, at least one problem was observed, ip addr always throws segment fault, it's a known issue in old busybox. For healthz problem, I would have some updates next week.

**Comment by ArtfulCoder** [comment]
Ok, does skydns use Ip addr ?
If not, it should not be impacted by the busybox bug.
Of course we should update the image for debuggability reasons, but the bug shouldn't be the cause of failures that saw.

**Comment by mfanjie** [comment]
@ArtfulCoder skydns doesn't use ip addr, so the segment fault does not impact the function.
I finally found the image of skydns is not sync with gcr.io, after we synced the image, the crash problem was gone.
I am going to close the issue, except the segment fault in busybox might be addressed in the further.
