### ISSUE TITLE
Random thought about Rescheduler implementation

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#22054]
Rescheduler: Stealing Pods from high load Nodes
-------

#### Introduction

This proposal try to implement two features of Rescheduler: 
1) Redistribute Pods onto new nodes added by cluster auto-scaler or cluster administrator
2) Move Pods around when CPU/MEM starvation is detected on a node

Rescheduler will use "Pod stealing" algorithm: low load Nodes could steal pods from nods suffering
CPU/MEM starvation. 

The idea of "Pod stealing" is inspired from "Work stealing" algorithm, see https://en.wikipedia.org/wiki/Work_stealing, which is widely used in Golang programming language, he Java fork/join framework, and the .NET Task Parallel Library. 

"Pod stealing" is easy to implement and verify.

#### Design

Rescheduler will have two flags:
```
--CPUUtilizationHighThresholdPercent
--MEMUtilizationHighThresholdPercent
```
Rescheduler will get CPU/MEM utilization metrics from Heapster, once utilization is above threshold, Rescheduler will think the Nodes suffer CPU/MEM starvation and try to reschedule Pods to low load Nodes.

#### Pseudo code
```
for i, node := range starvationNodes {
	pods := All Pods on node
	sort.Sort(SortPodByCPUUtilizationDescending(pods))
	for {
		pod := ChoosePodToReschedule(pods)
		des := Reschedule(pod)
		// rebind pod to des
		ReBind(pod, des)
		reduce node cpu utilization accordingly // use "Expectation" here,  which is supposed to be used to await previous rescheduler actions to be seen in the near future
		if (node no longer starvation){
			break
		}
	}
}

func ChoosePodToReschedule(pods) pod{
	// return a pod which is best for rescheduling, we can use some priority funcs here,
        // for example pod with large replicas nums,  pods with high CPU but low MEM utilization 
        // when node is suffering CPU starvation, etc.
}

func Reschedule(pod) api.Node {
    // Filters the nodes to find the ones that fit based on the given predicate functions
    // Each node is passed through the predicate functions to determine if it is a fit
	filteredNodes := findNodesThatFit(pod, NoStarvationNodes)
	// The node scores returned by the priority function are multiplied by the weights to get weighted scores
	// We use some priority funcs for rescheduler, such as: priority funcs take into account CPU/MEM utilization 
	// information collected from Heapster
	prioritizeNodes := prioritizeNodes(pod, filteredNodes)

	return prioritizeNodes[0]
}
```

And since the multi-scheduler support is under heavy development, user can configure muti-scheduler using different configuration(different predicate func, different scheduler extender ). Rescheduler should also know those configuration(especially the scheduler extender). So, it's reasonable to implement rescheduler as a  "virtual rescheduler" in scheduler, instead of as a single component.

**Comment by mqliang** [comment]
@davidopp @bgrant0607 
Just my random thoughts for discussion. May be a little simple, and has not address defragmentation feature yet, but could be a good start for Rescheduler implementation.

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra @kubernetes/rh-scalability @smarterclayton

**Comment by timothysc** [comment]
@ncdc we may re-prioritize this to be higher for online.

**Comment by davidopp** [comment]
@bgrant0607 and I had some discussions about rescheduler earlier this week but I haven't had time to write them down. Will do that and take a look at this PR next week.

cc/ @HaiyangDING

**Comment by mqliang** [comment]
@davidopp Sounds fascinating. Expecting your manuscript and hoping they could be complementary.

**Comment by mqliang** [comment]
### Preemption: allow a high-priority pending pod been scheduled

Copy from Brog paper:

>
What happens when more work shows up than can be accommodated? Our solutions for this are priority and quota.
Every job has a priority, a small positive integer. A high-priority task can obtain resources at the expense of a lower-priority one, even if that involves preempting (killing) the latter. Borg defines non-overlapping priority bands for different uses, including (in decreasing-priority order): monitoring, production, batch, and best effort (also known as testing or free). For this paper, prod jobs are the ones in the monitoring and production bands.
>
Although a preempted task will often be rescheduled elsewhere in the cell, preemption cascades could occur if a high-priority task bumped out a slightly lower-priority one, which bumped out another slightly-lower priority task, and so on. To eliminate most of this, we disallow tasks in the production priority band to preempt one another. Fine-grained priorities are still useful in other circumstances – e.g., MapReduce master tasks run at a slightly higher priority than the workers they control, to improve their reliability.
>
Priority expresses relative importance for jobs that are running or waiting to run in a cell. Quota is used to decide which jobs to admit for scheduling. Quota is expressed as a vector of resource quantities (CPU, RAM, disk, etc.) at a given priority, for a period of time (typically months). The quantities specify the maximum amount of resources that a user’s job requests can ask for at a time (e.g., “20TiB of RAM at prod priority from now until the end of July in cell xx”). Quota-checking is part of admission control, not scheduling: jobs with insufficient quota are immediately rejected upon submission.
>
Higher-priority quota costs more than quota at lower-priority. Production-priority quota is limited to the actual resources available in the cell, so that a user who submits a production-priority job that fits in their quota can expect it to run, modulo fragmentation and constraints. Even though we encourage users to purchase no more quota than they need, many users overbuy because it insulates them against future shortages when their application’s user base grows. We respond to this by over-selling quota at lower-priority levels: every user has infinite quota at priority zero, although this is frequently hard to exercise because resources are over-subscribed. A low-priority job may be admitted but remain pending (unscheduled) due to insufficient resources.
>
Quota allocation is handled outside of Borg, and is intimately tied to our physical capacity planning, whose results are reflected in the price and availability of quota in different datacenters. User jobs are admitted only if they have sufficient quota at the required priority. The use of quota reduces the need for policies like Dominant Resource Fairness (DRF) [29, 35, 36, 66].
>
Borg has a capability system that gives special privileges to some users; for example, allowing administrators to delete or modify any job in the cell, or allowing a user to access restricted kernel features or Borg behaviours such as disabling resource estimation (§5.5) on their jobs.

It's a very helpful feature to make a pending pod schedule. 

There is another proposal which also propose to add priority to pod see https://github.com/kubernetes/kubernetes/pull/20203, but that PR focusing on schedule latency if there are a large number of pods in the schedule queue:
>
if there are 100 pods in namespace A and 1 pod in namespace B waiting for scheduling, scheduler will not start to schedule the one pod in namespace B until all the 100 pods in namespace A have been scheduled!

So, some strategy, such as HPF(Hing-Priority-First), Round-robin is very helpful. But the preemption feature could allow a high-priority pending pod preempt low-priority pods.

**Comment by bgrant0607** [comment]
Queue sort order and preemption are separable.

Borg's preemption mechanism was not designed with disruption budgets (#12611) in mind, and wasn't designed to decouple user specification from operational intent (https://github.com/docker/docker/issues/11187). We shouldn't follow Borg's example in this case.

@davidopp and I have discussed this topic, too, and should be in his notes.

**Comment by mqliang** [comment]
close this in favour of https://github.com/kubernetes/kubernetes/issues/22217
