### ISSUE TITLE
AWS: Fix cluster tag

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22058]
We currently rely on a cluster tag called "KubernetesCluster".  This has two problems:
1. It doesn't follow the kubernetes.io namespacing pattern
2. It doesn't allow for something to be tagged with two clusters

While in general we have to be careful with something being owned/managed by two clusters (which is what the cluster tag implies), there are cases where it might be OK.  For example with a public subnet for your ELBs, when running k8s in private subnets.  That public subnet can be shared between clusters.

Instead of `KuberentesCluster=mycluster`, it could be `kubernetes.io/cluster:mycluster=1` or something like that.

Another alternative is to allow a comma-separated list of values.  We can't query this as efficiently though.

(Tag keys must be unique per resource)

**Comment by kenden** [comment]
Is this implemented?
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/tags.go#L30

**Comment by justinsb** [comment]
It is - great point!
