### ISSUE TITLE
Revisit use of expectations in controllers

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22061]
Esp. the Deployment controller.

When working on #21963 and #19299 we discovered a lot of suspect behavior in the expectation behavior.

Expectations are supposed to be used to await previous controller actions to be seen in watch.

However, there appear to be a number of issues:
- Can't distinguish unexpected events from controller actions. For RC and RS, in theory the pods are fungible, but actually they aren't, since they differ in availability (pending vs. running, crashing, readiness, ready time, etc.). For Deployment, they aren't fungible, since they can also be different versions.
- Deletes appear to show up late and maybe are sometimes double-counted
- The Deployment controller is reliant on expiration of the expectations in order to function
- RC and RS may have erratic behavior now that they don't use expiration -- we may need to do something similar to what was done in Deployment

cc @bprashanth @mqliang @janetkuo @madhusudancs @kargakis @nikhiljindal

**Comment by bgrant0607** [comment]
This relates to a discussion @mikedanese, @davidopp, and I had yesterday.

Also related: #14961 (controllerRef, observedGeneration), #22007 (controller annotation of managed resources)

**Comment by bgrant0607** [comment]
I effectively added expiration to RS and RC. However, pod creation appears to be fairly slow, so the timeout needs to be long.

#22138 sets the timeout to 5 minutes.

It also eliminates expectations from Deployment.

**Comment by bprashanth** [comment]
Is this about the need for refcounting in the RC manager, or something larger? The issues hint at a unified theory of controllers *much* larger than the adhoc implementation of expectations that has been cargo culted around.  

The RCs need to be precise, so they need to refcount. Not all controllers have the same requirements. Fwiw in the controllers I've written (ingress/service) I've just invented different synchronization mechanisms of my own using annotations. I believe leaving this upto the controller author should work for the 60% case.

**Comment by bgrant0607** [comment]
I'd like to make the RC and RS controllers have deterministic/idempotent behavior.

We already made deletion idempotent by ensuring victims to delete are chosen deterministically.

I'd like to do the same for creation by making pod names deterministic. 

I don't want to use dense indices, however, since that would have misleading connotations. However, we could do something like hash the pod template with a monotonic counter. Deployment takes the max of outstanding revisions and adds one (but doesn't use it in object names) and uses the pod template hash in the RS name. RC/RS could take the max of outstanding incarnations, add one, and hash that with the pod template. As with Deployment revisions, incarnations could be recorded as annotations (on the pods, in this case).

**Comment by bgrant0607** [comment]
Would need to rewrite incarnation annotations in the case of adoption.

**Comment by bgrant0607** [comment]
See also #7369

**Comment by sftim** [comment]
Is this issue still one we'd want to track and work on?

**Comment by bgrant0607** [comment]
I haven't looked at reported bugs for a long time, but probably we can close this in favor of addressing user-reported issues, if any.

/close
