### ISSUE TITLE
Controllers: Better choices of what to kill

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22065]
ReplicationController and ReplicaSet use the following priority function to decide which pods to kill:
```
func (s ActivePods) Less(i, j int) bool {
	// Unassigned < assigned
	if s[i].Spec.NodeName == "" && s[j].Spec.NodeName != "" {
		return true
	}
	// PodPending < PodUnknown < PodRunning
	m := map[api.PodPhase]int{api.PodPending: 0, api.PodUnknown: 1, api.PodRunning: 2}
	if m[s[i].Status.Phase] != m[s[j].Status.Phase] {
		return m[s[i].Status.Phase] < m[s[j].Status.Phase]
	}
	// Not ready < ready
	if !api.IsPodReady(s[i]) && api.IsPodReady(s[j]) {
		return true
	}
	return false
}
```

It does take Readiness into account, but this is insufficient for Deployment (and for users), since it doesn't take how long the pods have been ready into account. We might eventually  push minReadySeconds into pods and report an Available condition, but it would be sufficient for now to add the following prioritization criteria:

* Prefer to kill pods that have been ready for less time (use transition time, similar to how availability is determined)
* Prefer to kill pods with containers with higher restart counts
* If all else is equal, kill newer pods (by creation timestamp) -- which is desirable in the case of overshooting, anyway

Note that FilterActivePods already filters out terminated and terminating pods, but we may want to account for those in this function, in case we use it elsewhere.

Eventually we'll want to take into consideration scheduling quality, also: #4301. However, I wouldn't do that by putting the logic into the controllers. We could think about how the rescheduler(s) #12140 could indicated preferred victims to the controllers (e.g., pods that should be moved but can't yet due to lack of disruption budget #12611).

@janetkuo @kargakis @madhusudancs @mqliang @nikhiljindal

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/22078

**Comment by davidopp** [comment]
@janetkuo @bgrant0607 Can we move this out of the 1.2 milestone now that #22078 has been merged? If so, please do it.

**Comment by bgrant0607** [comment]
@davidopp Yes, done.

**Comment by bgrant0607** [comment]
Actually, I'm going to close this, since #4301 is still open.
