### ISSUE TITLE
broken link on troubleshooting/logging page

### ISSUE THREAD

**Issue by asquare** [kubernetes/kubernetes#22068]
The link to 'Collecting log files within containers with Fluentd' is broken on the page [Cluster Level Logging to Google Cloud Logging](http://kubernetes.io/v1.1/docs/getting-started-guides/logging.html) and also on this page [Logging](http://kubernetes.io/v1.1/docs/user-guide/logging.html)

**Comment by bgrant0607** [comment]
All these links seem to work now.
