### ISSUE TITLE
Run ubernetes-lite e2e CI tests on AWS

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#22077]
Blocked on #22076

**Comment by fejta** [comment]
You should be unblocked now. Assign back to me if this is not the case.

**Comment by quinton-hoole** [comment]
Yup, I think we're sorted thanks.  Will get back to you if I hit any snags.

**Comment by quinton-hoole** [comment]
Blocked on #22572 now (test infra).  Need to get this running reliably on GCE again first, before trying on AWS.

**Comment by quinton-hoole** [comment]
Unblocked now that #22572 is resolved.  Tackling this now.

**Comment by davidopp** [comment]
ping

**Comment by quinton-hoole** [comment]
@davidopp I started this and it's slightly more complicated than I thought, because the scripts that build e2e test clusters need to be extended slightly to build multi-zone clusters.  It's WIP, but I have a few higher priority things happening this week.  Hope to get back to it next week.

**Comment by quinton-hoole** [comment]
Needless to say, I didn't get back to this due to other conflicting priorities.
If anyone else want to take a look at this, contributions would be most welcome.  I've added the "help-wanted" label.
You can use #19578 as a guideline.
@spiffxp Do you perhaps want to take a swing at it?

**Comment by spiffxp** [comment]
thanks for the ping, but I'm buried under a pile of other PR's at the moment, I likely won't have bandwidth for this for a few weeks

**Comment by roberthbailey** [comment]
@quinton-hoole is this on your radar for 1.3 (or should it be)?

**Comment by quinton-hoole** [comment]
I doubt I'll get to it. Feel free to take it.

**Comment by roberthbailey** [comment]
I wasn't asking about taking it, but whether we should move it out of the 1.3 milestone. It sounds like the answer is yes.

**Comment by quinton-hoole** [comment]
Yup!  SGTM.

**Comment by quinton-hoole** [comment]
@colhom Could you do this while you're busy with the other AWS Federation test stuff?

**Comment by goltermann** [comment]
Moving out of v1.4 as this is a P2.

**Comment by quinton-hoole** [comment]
@colhom

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree) @justinsb @quinton-hoole

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by marun** [comment]
No update since 1.5, not a release blocker.
