### ISSUE TITLE
MESOS: K8sm scheduler --kubeconfig flag overloaded?

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#22081]
K8s scheduler has a --kubeconfig flag so one can specify information about API server, TLS, user, etc. K8sm scheduler also have the same --kubeconfig flag. Is this flag being used by the K8sm scheduler itself or being used by the K8sm executor to download and use? 

From what I can see, it's being used by both K8sm scheduler and executor. If so, scheduler and executor would be using the same TLS certificate?

**Comment by huang195** [comment]
cc: @jdef @sttts @karlkfi

**Comment by jdef** [comment]
Yes, it's overloaded. Probably not ideal if we ever want to use different configs in the scheduler vs the kubelet. In general I'd say that configuration in k8sm needs an overhaul.

Semi-related:
* https://github.com/mesosphere/kubernetes-mesos/issues/516
* https://github.com/mesosphere/kubernetes-mesos/issues/758

**Comment by huang195** [comment]
@jdef In the Kubernetes documentation on authorization, there are some examples:

```
Example AUTHORIZATION_FILE_NAME:
{"user":"admin"}
{"user":"scheduler", "readonly": true, "resource": "pods"}
{"user":"scheduler", "resource": "bindings"}
{"user":"kubelet",  "readonly": true, "resource": "pods"}
{"user":"kubelet",  "readonly": true, "resource": "services"}
{"user":"kubelet",  "readonly": true, "resource": "endpoints"}
{"user":"kubelet", "resource": "events"}
{"user":"alice", "namespace": "projectCaribou"}
{"user":"bob", "readonly": true, "namespace": "projectCaribou"}
```

So, I think it would be prudent to have scheduler and kubelet having different authorization capabilities (defined by different kubeconfig files). While I completely agree that k8sm configuration needs an overhaul, in the mean time, do you think we can separate scheduler-kubeconfig from kubelet-kubeconfig so we have this functionality available?

**Comment by huang195** [comment]
Similar to #22085, can we add a `--executor-kubeconfig` flag to make this more clear. The idea is:

* `--kubeconfig` specifiies kubeconfig file the km scheduler will use for itself
* `--executor-kubeconfig` specifies kubeconfig scheduler will host and executor can download for the kubelet to use

Both flags are optional. What do you think?

**Comment by jdef** [comment]
sounds good to me. in this case there would be no fallback, the flags are
completely independent, correct?

**Comment by huang195** [comment]
@jdef yes, there should be no dependencies between the flags.

**Comment by huang195** [comment]
Would it be better to call this flag `--kubelet-kubeconfig` following the existing naming convention since this is a parameter that the executor will eventually pass it to the kubelet?

**Comment by jdef** [comment]
i'm fine with the kubelet prefix
