### ISSUE TITLE
K8sm scheduler --api-servers flag overloaded?

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#22085]
This parameter is used both by the K8sm scheduler as well as the executor. However, sometimes I want the scheduler to connect to the api server differently from how executor/kubelet connects to the api server. For example, my scheduler is always co-located with the api server, so I want it to connect to the api server through the loopback interface via the insecure port, whereas kubelet should connect to the api server over https on the api server's public ip address. 

Is there a way around this problem?

**Comment by huang195** [comment]
cc: @jdef @sttts @karlkfi

**Comment by jdef** [comment]
code doesn't support your intent, at least in it's current form. I could perhaps see justification for an `--executor-api-servers` flag, whose value defaults to that of `--api-servers` and is never allowed to be empty. The value of which is passed along as `--api-servers` in the scheduler's `prepareExecutorInfo` func.

**Comment by huang195** [comment]
@jdef: I like that approach as it minimizes the change. I can add this flag per your suggestion.
