### ISSUE TITLE
k8sbot not re-running tests when requested

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#22090]
In at least one case - not sure if this is more widespread.

See #22083

I accidentally closed (then re-opened) the issue, which didn't re-trigger the tests. Then I did "e2e test this" twice and still nothing happened.

cc/ @ixdy @lavalamp

**Comment by davidopp** [comment]
Never mind, it *just* started -- but took many minutes, unlike my experience in the past.

**Comment by davidopp** [comment]
(About 23 minutes to be precise)

**Comment by ixdy** [comment]
The trigger phrase is "@k8s-bot e2e test this" - you didn't include "this" on the first comment. Closing/opening a PR won't re-trigger tests, either.
