### ISSUE TITLE
Move more to genericapiserver

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#22093]
- `pkg/apiserver/api_installer.go` is generic (or should be made generic)
- `cmd/kube-apiserver/app/server.go`:
  - newEtcd should be moved to a genericapiserver/etcd package or something
  - All the if blocks (`if !apiGroupVersionOverrides["extensions/v1beta1"].Disable {`) should be refactored into something that operates in a loop over a map or something, and moved to the generic apiserver

**Comment by lavalamp** [comment]
@nikhiljindal

**Comment by sttts** [comment]
Moved to https://github.com/kubernetes/kubernetes/issues/32792. @lavalamp I propose to close this.
