### ISSUE TITLE
Kubelet log spam

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#22098]
This log line is repeated multiple times in succession very periodically if docker daemon is down. instead logging once should be enough...

```E0227 00:52:24.367135     639 generic.go:164] GenericPLEG: Unable to retrieve pods: cannot connect to Docker endpoint```

**Comment by yujuhong** [comment]
It's a V(4) message with a period of 1s, serving as an indication of pleg running for debugging purpose. We have more noisy messages in the log. I'd like to keep this for a while until we are sure that our builds are stable.

**Comment by jumpkick** [comment]
Once a second is not bad as log spam goes...  I'm running 1.2.0a7 and there hundreds of messages being spammed to the API server log regarding missing daemonset config (404)...  Literally 75% of the log is that message [ docker logs $(docker ps | grep k8s_apiserver | cut -d" " -f1) 2>&1 | tail -20 | grep daemonset |wc  -l == 14 ]

**Comment by yujuhong** [comment]
@jumpkick, yon can file a separate issue to have this fixed :)
