### ISSUE TITLE
Cannot run Kubernetes on Amazon

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#22106]
Downloaded Kubernetes 1.1.8 from: 

https://github.com/kubernetes/kubernetes/releases/download/v1.1.8/kubernetes.tar.gz

Followed the instructions at:

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/aws.md

And got the following error:

```
kubernetes-1.1.8 > ./kubernetes/cluster/kube-up.sh 
... Starting cluster using provider: aws
... calling verify-prereqs
... calling kube-up
Starting cluster using os distro: vivid
Uploading to Amazon S3
Creating kubernetes-staging-0eaf81fbc51209dd47c13b6d8b424149
make_bucket: s3://kubernetes-staging-0eaf81fbc51209dd47c13b6d8b424149/

A client error (NoSuchBucket) occurred when calling the GetBucketLocation operation: The specified bucket does not exist
+++ Staging server tars to S3 Storage: kubernetes-staging-0eaf81fbc51209dd47c13b6d8b424149/devel
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --region: expected one argument
```

AWS Console showed that the bucket was created but was empty.

**Comment by justinsb** [comment]
Sorry this is still happening.  We believe it is because S3 is eventually consistent.  If you try again, it should work because it will now have created the bucket.

Thanks for the bug report though - will help with identifying the timeout that needs boosting!

**Comment by davidopp** [comment]
@justinsb were you planning to look into the "timeout that needs boosting" in the 1.2 timeframe? If not, please remove the v1.2 milestone from the issue.

**Comment by davidopp** [comment]
ping @justinsb - can you confirm there's nothing to do here for 1.2?

**Comment by paralin** [comment]
I think the deployment process at least works now. I've deployed 10-15 clusters in the last month with no errors of this nature.

**Comment by roberthbailey** [comment]
I'm going to close this as obsolete. Please reopen it if you are still using this issue for tracking anything.
