### ISSUE TITLE
[v1.2.0-alpha.8] --hostname-override with kubectl logs

### ISSUE THREAD

**Issue by Calpicow** [kubernetes/kubernetes#22109]
Running in AWS with an environment where the given hostname does not resolve. So I set --hostname-override to the raw IP for kubectl logs to work. This no longer works after upgrading to v1.2.0-alpha.8 from v1.1.4.

**Comment by AdoHe** [comment]
@Calpicow I will take a look at this asap.

**Comment by bgrant0607** [comment]
See also #22770 and #22063

cc @justinsb
