### ISSUE TITLE
AWS: Make sure created ELBs have cluster & service tags

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22118]
I'm pretty sure we do now tag ELBs with the service name now with a recent PR, but we should verify that we have a service tag & a cluster tag.  See request here:
https://github.com/kubernetes/kubernetes/issues/15203#issuecomment-189316080

Note this is the ELB, not just the security groups.

cc @guoshimin and @davidopp

**Comment by justinsb** [comment]
I believe this was fixed by #20731:

```
+               createRequest.Tags = []*elb.Tag{
+                       {Key: aws.String(TagNameKubernetesCluster), Value: aws.String(s.getClusterName())},
+                       {Key: aws.String(TagNameKubernetesService), Value: aws.String(namespacedName.String())},
+               }
```

**Comment by therc** [comment]
It is indeed. But I wish we went one step further and gave the LoadBalancer the name CLUSTER:NS:SVC. It still takes too many clicks to figure in the console bwhat a88bd3.. is.

**Comment by justinsb** [comment]
@therc we're constrained by the restrictions on ELB names `This name must be unique within your set of load balancers for the region, must have a maximum of 32 characters, must contain only alphanumeric characters or hyphens, and cannot begin or end with a hyphen.`

We use "a" + a prefix of the service UUID right now.  I agree it's not great, but we do have the tags now (thanks to your work, it looks like!)  Unless you have a suggestion that could still work reliably here... (that isn't outrageously hard to implement!)
