### ISSUE TITLE
node node summary metrics missing pods on systemd

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#22112]
When running on a systemd host, pod metrics don't show up in the summary api.  Can be tested on ubuntu wily.

**Comment by timstclair** [comment]
Is it all pod metrics (network + volumes + starttime) or just network + starttime? If the latter, it's probably not identifying the pod infra container correctly ([summary.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/stats/summary.go#L202)). How are the pod infra containers labeled on systemd machines?

**Comment by pwittrock** [comment]
It is all pod metrics.  You can reproduce the issue by enabling e2e-node-ubuntu-wily-image against the PR builder and setting cleanup=false.  This will leave the instance around with the binaries.  The labels appear to be present in docker.

**Comment by dchen1107** [comment]
cc/ @derekwaynecarr and @vishh

**Comment by euank** [comment]
On my systemd host, `/stats/summary` works. I suspect this issue is stale and can be closed.

**Comment by vishh** [comment]
Let's close this then!
