### ISSUE TITLE
kubectl container not available with latest version

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kubernetes#22121]
Hi,

This is probably a documentation issue.
When checking the docs for how to use service accounts we have this page:

http://kubernetes.io/v1.1/docs/user-guide/service-accounts.html

it points to "accessing the cluster": 

http://kubernetes.io/v1.1/docs/user-guide/accessing-the-cluster.html#accessing-the-api-from-a-pod

Which if we don't use a client library points to using a kubectl container described in:

http://kubernetes.io/v1.1/examples/kubectl-container/

But this page does not have any links. If we check the source:

https://github.com/kubernetes/kubernetes/tree/4ca66d2aefa20c27b670b2fa890052daadc05294/examples/kubectl-container

we do see the Makefile and Dockerfile, it indicates that there should be a kubectl container on GCR:

```
gcloud docker push gcr.io/google_containers/kubectl:$(TAG)
```

But this container does not have the latest version: 1.1.4, 1.1.8

So questions are:

1- is using a kubectl proxy sidecar still recommended ?
2- if yes, why is the latest version not pushed ?

**Comment by bgrant0607** [comment]
cc @david-mcmahon

**Comment by david-mcmahon** [comment]
The answer to #2 comes from https://github.com/kubernetes/kubernetes/tree/4ca66d2aefa20c27b670b2fa890052daadc05294/examples/kubectl-container:

_It's not currently automated as part of a release process, so for the moment this is an example of what to do if you want to package kubectl into a container/your pod._

**Comment by runseb** [comment]
@david-mcmahon yes, I found the source, but the doc page created from this source:
http://kubernetes.io/v1.1/examples/kubectl-container/

Does not link to the Dockerfile.

Happy to make a simple PR for it.

**Comment by david-mcmahon** [comment]
I see.  Yes, please do.

**Comment by runseb** [comment]
FWIW, here is a blog I just wrote that explains how to setup a kubectl proxy sidecar to use a Python client. Since the kubectl container was not published for 1.1.8 and even much before that, I had to create my own image at gcr.io/skippbox/kubectl:v1.1.8

http://www.skippbox.com/using-a-kubernetes-api-python-client/

**Comment by spiffxp** [comment]
@kubernetes/sig-cli-feature-requests @kubernetes/sig-release-feature-requests is this a release artifact we want to support? otherwise this can be closed due to working as expected
```
$ gcloud container images list-tags gcr.io/google_containers/kubectl
DIGEST        TAGS                               TIMESTAMP
15c6ba4985e3  v1.0.7                             2017-01-11T15:56:35
71473dd62257  v0.18.0-350-gfb3305edcf6c1a        2017-01-11T15:56:17
0edbc41c8b59  v0.18.0-120-gaeb4ac55ad12b1-dirty  2017-01-11T15:56:11
```

**Comment by sebgoa** [comment]
@spiffxp yes we can close

**Comment by clhodapp** [comment]
This is really unfortunate, given that the [the recommended way to connect to the API from within pods](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-a-pod) is to use a sidecar `kubectl proxy`. You even have CNCF projects [*removing* convenient, direct service account support](https://github.com/linkerd/linkerd/pull/385) due to this recommendation.

**Comment by sebgoa** [comment]
Agreed, we should re-open this issue.

We need to make a better recommendation in the docs or make that kubectl container available.

Do note that with the python client you can make API calls to the APi server without a proxy because the client can load the service account token properly.

cc/ @ahmetb would be nice to get you to check that doc page about kubectl proxy being recommended.

**Comment by ahmetb** [comment]
> cc/ @ahmetb would be nice to get you to check that doc page about kubectl proxy being recommended.

To be clear, that way is only one of the ways that are recommended in [the doc](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-a-pod). If you don't have a k8s client library in the language you’re using, then `kubectl proxy` makes it easy to authenticate. If you are using Go/Python or another language that we have a client in, you don't need a sidecar running `kubectl proxy` most definitely.

**Comment by clhodapp** [comment]
@ahmetb The recommendation is presently language-unconditional when the access is from within a pod.

**Comment by ahmetb** [comment]
@clhodapp sent a docs PR to better clarify:  https://github.com/kubernetes/website/pull/6259

**Comment by AssafKatz3** [comment]
Curretnly there is no real way to run kubectl command in job. If I need to run simple cleanup script for HELM, it is very complex task. I understand why the recommand way to more complex options is to use client kit, but there is good use case for supporting kubectl image.

**Comment by dims** [comment]
closing since kubernetes/website#6259 has merged

/close
