### ISSUE TITLE
e2e flake: deployment should support rollback [status not updated]

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22122]
kubernetes-jenkins/logs/kubernetes-e2e-gce/12369

```
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:72
  deployment should support rollback [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:65

  Expected
      <int>: 0
  to equal
      <int>: 1

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:629
```

cc @janetkuo @nikhiljindal @kargakis @mqliang @ironcladlou

**Comment by bgrant0607** [comment]
```
	// Verify that the required pods have come up.
	err = verifyPods(unversionedClient, ns, "nginx", false, deploymentReplicas)
	if err != nil {
		Logf("error in waiting for pods to come up: %s", err)
		Expect(err).NotTo(HaveOccurred())
	}
	deployment, err = c.Extensions().Deployments(ns).Get(deploymentName)
	Expect(err).NotTo(HaveOccurred())
	// DeploymentStatus should be appropriately updated.
	Expect(deployment.Status.Replicas).Should(Equal(deploymentReplicas))
	Expect(deployment.Status.UpdatedReplicas).Should(Equal(deploymentReplicas))
```

This test should wait for status to become equal rather than checking it immediately after pods are observed. The test is racing the controllers. ReplicaSet needs to observe the pods and then Deployment needs to observe the ReplicaSet.

Note: verifyPods and related routines should be moved from resize_nodes.go to util.go.

**Comment by bgrant0607** [comment]
Another failure mode:
```
• Failure [37.356 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:72
  deployment should support rollback [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:65

  Expected
      <string>: 2
  to equal
      <string>: 3

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:148
```
This is the revision annotation check:
```
	newRS, err := deploymentutil.GetNewReplicaSet(*deployment, c)
	Expect(err).NotTo(HaveOccurred())
	Expect(newRS.Annotations).NotTo(Equal(nil))
	Expect(newRS.Annotations[deploymentutil.RevisionAnnotation]).Should(Equal(revision))
```
kubernetes-jenkins/logs/kubernetes-e2e-gce/12379

**Comment by bgrant0607** [comment]
Latest failure:

```
• Failure [32.778 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:72
  deployment should support rollback [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:65

  Expected
      <string>: 3
  to equal
      <string>: 4

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:151
```
kubernetes-jenkins/logs/kubernetes-e2e-gce/12453

**Comment by bgrant0607** [comment]
The problem above may be related to #20497.

A bunch of changes have been made to ReplicaSet and Deployment. We should wait to see whether this recurs or not.

**Comment by bgrant0607** [comment]
Oops, comment moved to #22088.

This appears to be the most common Deployment flake. We need to resolve it ASAP. See my comment here:
https://github.com/kubernetes/kubernetes/issues/22122#issuecomment-189642102

Please also search the controller-manager logs for MISSING, and fix them. For example, line 746 in deployment_controller.go presumably was intended to print the Deployment:
```
		glog.V(4).Infof("updating replica set %q's revision to %s - %+v\n", rs.Name, newRevision)
```

Additionally, naming the controllers and pods to something unique to each test would be super-helpful, especially since we don't normally log the namespace. For example, instead of `nginx-deployment`, we could call it `test-rollback`.

**Comment by janetkuo** [comment]
> This test should wait for status to become equal rather than checking it immediately after pods are observed. 
...naming the controllers and pods to something unique to each test would be super-helpful. 

Filed #22202 for both. 

> verifyPods and related routines should be moved from resize_nodes.go to util.go.
Please also search the controller-manager logs for MISSING, and fix them.

Filed #22210 for both.

**Comment by janetkuo** [comment]
> This test should wait for status to become equal rather than checking it immediately after pods are observed. 

Adding this to other deployment e2e tests as well.

**Comment by bgrant0607** [comment]
The above issues have been fixed. Closing.
