### ISSUE TITLE
Make Policy be a proper REST object with its own registry

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#2212]
Make type policy in pkg/auth/authorizer/abac/abac.go be stored in REST storage.

This would be a good use case for plugins, which have not been entirely sorted out yet.

Having them as a rest object will make it easier to dynamically create policies.

**Comment by chancez** [comment]
@erictune Does this even make sens with RBAC anymore, or are there still plans for ABAC?

**Comment by erictune** [comment]
No plans to improve ABAC.  It will continue to exist for bootstrapping and back-compat purpose, but closing this.
