### ISSUE TITLE
Kubelet on master unable to write to TLS secured apiserver

### ISSUE THREAD

**Issue by aknuds1** [kubernetes/kubernetes#22135]
Running kubelet on a master node on CoreOS alpha (970.1.0), I've got the problem that the kubelet is unable to write to the TLS secured apiserver, because the certificate is signed by an unknown authority:
```Feb 28 00:28:23 ip-172-31-28-248.eu-central-1.compute.internal kubelet[2941]: E0228 00:28:23.526855    2941 event.go:197] Unable to write event: 'Post https://127.0.0.1:443/api/v1/namespaces/default/events: x509: certificate signed by unknown authority' (may retry after sleeping)```

How do I solve this?

The kubelet is started as follows:
```/usr/bin/kubelet \
  --api_servers=https://127.0.0.1:443 \
  --register-node=false \
  --allow-privileged=true \
  --config=/etc/kubernetes/manifests \
  --tls-cert-file=/etc/ssl/etcd/master1-master-client.pem \
  --tls-private-key-file=/etc/ssl/etcd/master1-master-client-key.pem \
  --hostname-override=172.31.29.111 \
  --cluster-dns=10.3.0.10 \
  --cluster-domain=cluster.local \
  --log-dir=/var/log/kubelet```

The apiserver is started like so:
```/usr/bin/docker run \
-p 443:443 \
-v /etc/kubernetes:/etc/kubernetes:ro \
-v /etc/ssl/etcd:/etc/ssl/etcd:ro \
gcr.io/google_containers/hyperkube:v1.1.2 \
/hyperkube apiserver \
--bind-address=0.0.0.0 \
--insecure-bind-address=127.0.0.1 \
--etcd-config=/etc/kubernetes/etcd.client.conf \
--allow-privileged=true \
--service-cluster-ip-range=10.3.0.0/24 \
--secure-port=443 \
--advertise-address=172.31.29.111 \
--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota \
--kubelet-certificate-authority=/etc/ssl/etcd/ca.pem \
--kubelet-client-certificate=/etc/ssl/etcd/master1-master-client.pem \
--kubelet-client-key=/etc/ssl/etcd/master1-master-client-key.pem \
--client-ca-file=/etc/ssl/etcd/ca.pem \
--tls-cert-file=/etc/ssl/etcd/master1-master-client.pem \
--tls-private-key-file=/etc/ssl/etcd/master1-master-client-key.pem```

**Comment by iamthemuffinman** [comment]
+1 Also having this issue.

**Comment by sekannia** [comment]
Were you able to solve this issue.

**Comment by aknuds1** [comment]
@sekannia Too long ago, don't remember actually. Moved to Google Container Engine in the meantime.

**Comment by sekannia** [comment]
thanks

**Comment by liggitt** [comment]
the kubeconfig used by the kubelet either needs to reference a trusted CA bundle to verify the API server's cert, or contain `insecure-skip-tls-verify: true` to skip TLS verification (don't do this for any real setup)
