### ISSUE TITLE
Scalable iperf3 server

### ISSUE THREAD

**Issue by pjebs** [kubernetes/kubernetes#22145]
Is there any way I can use k8s to make a scalable iperf3 server?

Iperf3 is used to measure internet connection speed between server and client.
I need all clients connecting using single unified endpoint.
The server program can only deal with 1 client at a time hence need to run it a container. It a second client tries to connect whilst it is busy with first client, the second client gets error message returned. I'm not sure if there is a clean way to then get second client to then connect with another container running iperf3.

As far as I know, iperf makes it difficult to tell if it's busy with a client - except for a different client actually trying to connect to it while busy and then being sent an error message that it is busy.

If this is not possible as per discussion in link below, this is a serious limitation to k8s

**Comment by pjebs** [comment]
https://github.com/kubernetes/kubernetes/issues/21925

**Comment by pjebs** [comment]
Would I be able to use kubernetes with AWS lambda to kick start a pod for a request and route request to iperf container?

**Comment by spiffxp** [comment]
/sig apps
given that the linked issue is also sig/apps

**Comment by castrojo** [comment]
I think you'd get a better response if you posted this to the sig apps mailing list directly: https://groups.google.com/forum/#!forum/kubernetes-sig-apps

As this is more of a deployment/configuration request and not a bug I'm going to close this, thanks!
