### ISSUE TITLE
Documentation shows different kubectl client output 

### ISSUE THREAD

**Issue by levmichael3** [kubernetes/kubernetes#22142]
I am not sure that I'm right here but my kubectl client shows different output. this might be confusing for new learners like me.

http://snag.gy/fKpam.jpg

my output shows only 'IP'. Is this correct?

![image](https://cloud.githubusercontent.com/assets/2282643/13378192/debe355e-de04-11e5-8018-8000dafadcc8.png)

**Comment by AdoHe** [comment]
@levmichael3 can you provide your kubernetes version? use `kubectl version` can get this.

**Comment by levmichael3** [comment]
Issue resolved. Its an older version. Thanks!
