### ISSUE TITLE
Avoid supposing a default python version

### ISSUE THREAD

**Issue by txomon** [kubernetes/kubernetes#22147]
I have found many `python -c` calls, and submitted a PR #22144, but speaking with @justinsb , doesn't seem the best option to use python3, as OS X for example doesn't have any python3 installed by default.

Also, we are assuming python 2.6 onwards on some of the python calls. I can think on the following options:
- Make python 2.7 a default and check for >python2.6
- Get rid of python for yaml/json processing

Anyway, we should _always_ avoid using `python -c` in any piece of code, as you don't know the version running. Use at least `python2 -c` or `python3 -c`

**Comment by txomon** [comment]
The issue is that I am running python3 by default, and during AWS cluster creation:

```
Adding IAM role to instance-policy: kubernetes-minion
  File "<string>", line 1
    import string,random; print "".join(random.SystemRandom().choice(string.ascii_letters + string.digits) for _ in range(16))
                                 ^
```

**Comment by euank** [comment]
I think that using `python -c` and then ensuring all code run is python 2.7 + 3.x compatible is the best option.

The `./cluster/gce` code right now works that way, and that certainly is the most future-proof option for once the world finally uses python3 (any decade now...)
