### ISSUE TITLE
Add apparmor and seccomp to PodSecurityPolicy

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#22159]
I was speaking with a customer this week who has a fairly established app stack using apparmor.  As we explored how to make it work in Kubernetes it dawned on me that, even if the config of an apparmor profile is opaque, the existence of it can be exposed in the API and carried all the way down to container runtime (e.g. Docker).

We could do something like:

```
type SecurityContext struct { 
   ...
   SecurityProfileName string
}

type SecurityProfile struct {
    TypeMeta
    ObjMeta
    SecurityProfileSource `json:,inline`
}

type  SecurityProfileSource struct {
   // one of the following
   SELinux SELinuxOptions
   AppArmor string
}
```

Just jotting notes for future work. We'll want to accommodate seccomp before long and who know what else.

**Comment by thockin** [comment]
@pmorie @smarterclayton @erictune

**Comment by smarterclayton** [comment]
With SELinux we made the assumption that your policy across the cluster was either homogenous, or that you were responsible for defining a pattern and applying it and controlling access to nodes.  Does the indirection from pod to profile have any particular benefit or disadvantages?  For selinux it's been a fairly mechanical range / enforcement usage, although we're starting to ask how to propagate assigned labels from pod to PVC to PV.

**Comment by erictune** [comment]
We have this.  It is called [PodSecurityPolicy]( https://github.com/kubernetes/kubernetes/blob/f5a92cc13cddb6f2fed2c8412216dd912524ac37/pkg/apis/extensions/v1beta1/types.go#L908
).

The type is checked in.  Enforcement code is not in yet.
@pweil- what is timeline for upstreaming more of this?

**Comment by erictune** [comment]
@pweil- any plans to add seccomp support?

**Comment by pweil-** [comment]
@erictune I'll be able to focus more on this when we close out 1.2 (which mostly corresponds to our 3.2) so likely in after the next sprint.  

I'd like to add the seccomp support somewhere in the PSP.  I haven't thought through where the actual profile lives and how it makes its way to the node if we're not expecting it to be there already.

**Comment by thockin** [comment]
Awesome.  Since I clearly can't read every PR (sad face), I'll pick a
couple nits here:

The yaml is going to be pretty mouthy for SELinux:

```
kind: PodSecurityPolicy
spec:
    seLinuxContext:
        type: MustRunAs
        seLinuxOptions:
            user: foo
```

Could we reduce it to:

```
kind: PodSecurityPolicy
spec:
    seLinux:
        rule: MustRunAs
        options:
            user: foo
```

In the next cycle we'll need to add apparmor here, and we can discuss the
details at that time.

Tim

**Comment by pweil-** [comment]
:+1:

**Comment by erictune** [comment]
And seccomp modes and filters?

**Comment by thockin** [comment]
something like https://github.com/kubernetes/kubernetes/pull/22419 ?

**Comment by thockin** [comment]
Retitled to better reflect current needs :)

**Comment by erictune** [comment]
Lemme compare that to
https://github.com/kubernetes/kubernetes/pull/22402

**Comment by sttts** [comment]
Seccomp PSP support is on its way: https://github.com/kubernetes/kubernetes/pull/28300

**Comment by philips** [comment]
How does this play with the CRI? https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/container-runtime-interface-v1.md

cc @yujuhong ?

**Comment by yujuhong** [comment]
We will have to extend CRI to support this as well. There are a few things in the pipeline that we will need to add later, and this is one of them. Let me file an issue.
