### ISSUE TITLE
update git ignore file to just ignore untracked yaml files.

### ISSUE THREAD

**Issue by AdoHe** [kubernetes/kubernetes#22157]
FYI. I used the latest master code to setup a local cluster by running `hack/local-up-cluster.sh`, now this will create three yaml files: `namespace.yaml`, `skydns-rc.yaml` and `skydns-svc.yaml` under your `$GOPATH/k8s.io/kubernetes/`, I don't know whether we should put these files on other directory like `/tmp` but at least we should update `.gitignore` to just ignore this file, or if someone use `git add .` we will  add these to track.

**Comment by pmorie** [comment]
I made a PR to use /tmp instead of the working directory: #22131

**Comment by AdoHe** [comment]
Ok, just close this.
