### ISSUE TITLE
can't delete a daemonset if an existing rc (with > 0 replicas) uses the same label for its pods

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes#22158]
Not sure if this will be considered a bug.
Suppose you create a RC with a given label selector for its pods (and > 0 replicas), then create a daemonset that uses the same label for its pods.

Then, if you try to delete that daemonset, the deletion will never terminate, since the termination process is waiting for the associated pods to shut down before it exits.  Things will just thrash back and forth-- the daemonset will shut down the pods and then the rc will re-create them...

(also, perhaps more obviously.. if the number of nodes in the cluster that the daemonset is mapping to, and the number of replicas in the rc are set to different values, they will thrash back and forth even prior to deletion :)

It seems like there ought to be some precedence ordering for these resources so that if they are playing chicken, one 'wins'.

**Comment by bgrant0607** [comment]
Known issue: #2210. Hopefully we'll be able to make time in 1.3 to address it.
