### ISSUE TITLE
Informer should abstract graceful deletion

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#22150]
Graceful deletion is the default now. We should apply a consistent policy to all controllers about how this is handled. A possible outline:      
1. When a pod with a deletion timestamp is noticed, it should count as a delete instead of an update.
2. The same pod should not show up as another delete notification when the kubelet wacks it.
3. delete with --grace-period=0 should continue to work as it currently does
4. a pod created with a deletion timestamp should actually be a delete. 

The real intent is that a controller should take corrective action right away instead of waiting the default 30s for a "real" delete, because for eg: webservers will stop accepting new connections right away and wait for grace period to drain existing connections. 

@lavalamp

**Comment by lavalamp** [comment]
This is a good point, but I won't agree it belongs in the informer until it applies to all objects. You can make a filter for the DeltaFIFO, I suggest fixing this by providing a filter for pods.

**Comment by bprashanth** [comment]
DeletionTimestamp is part of ObjectMeta, so in theory it applies to everything? you can always go the opposite way in your handlers (i.e check if deletion timestamp is set, and invoke another handler), but I think the common case is to treat an update with deletion timestamp as a delete.

**Comment by lavalamp** [comment]
In practice, it doesn't, though. Maybe it will in the future, in which case I think a default filter function may be useful.

However we should nail down whether a Delete event means the object is leaving the system, or if it means a delete has been initiated. Right now these two events are conflated by the system. And now that I think about this, I think this proposal is actually not the right way to fix this at all. I think the consumers of this code need to understand "in deleting state" as separate from "removed from system".

I think if we want to *force* code to handle this right, we'd have to get away from the OnAdd/OnUpdate/OnDelete trichotomy. I think it really muddies the water to start declaring that OnDelete means "will soon be deleted". What would you say when it's *actually* deleted? The messages should match presence/absence in the local store, which should match up with the rest of the system, on a literal, not semantic level.

**Comment by bprashanth** [comment]
A new handler for "deleting" would work too

**Comment by lavalamp** [comment]
Not really, how would you represent the opposite transition, if the
deletion is canceled? I think "deleting" really is just an update.

**Comment by bprashanth** [comment]
Currently you can't cancel it. it's irreversible, you can only lower it.

**Comment by bprashanth** [comment]
Deleting *is* just an update but i think the common case is to handle deleting like you don't care about the pod anymore (and this should be the default) and for the uncommon case there should be an escape hatch.

**Comment by bgrant0607** [comment]
cc @janetkuo @madhusudancs

**Comment by smarterclayton** [comment]
In practice this hasn't been an issue for controllers.
