### ISSUE TITLE
Master proxy sometimes hangs when Node becomes unresponsive

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#22165]
When proxying to the Node that is not responsive proxy hangs indefinitely, comment: https://github.com/kubernetes/kubernetes/issues/21313#issuecomment-189173573

ResourceGatherer uses some fancy tooling together with proxy, but MetricsGrabber don't - it's just plain proxy call, which also hangs.

@kubernetes/sig-api-machinery

**Comment by wojtek-t** [comment]
Just to give more context - it seems it's not always when just node is unresponsive, because @gmarek wasn't able to reproduce it locally. See this comment for details:
https://github.com/kubernetes/kubernetes/issues/21313#issuecomment-189258894

**Comment by lavalamp** [comment]
Someone must not be setting a timeout somewhere.

Ref #22164, which might be revertable once this is fixed.

**Comment by wojtek-t** [comment]
@lavalamp - actually I took a look before @gmarek filed this bug, and from what I've seen it seem that "timeout" is not supported for proxy calls at all. So it's not just not setting it, IIUC.

**Comment by lavalamp** [comment]
Well, I mean, the request by the server should be setting a timeout even if it doesn't use the ?timeout= query parameter.

**Comment by wojtek-t** [comment]
Yeah - but the problem is whether we have something like "default" timeout.
What if proxy call is streaming? Then setting timeout is probably wrong?

So unless I'm not missing anything, we should only set timeout of it is set in the original request (which is not supported now, i.e. proxy call is not even trying to read it from the request).

**Comment by lavalamp** [comment]
How urgent is this?

**Comment by wojtek-t** [comment]
For our usecases in scalability tests, we have an workarounds. So from my perspective it's not a 1.2 blocker.

**Comment by lavalamp** [comment]
OK, great, thanks.

**Comment by gmarek** [comment]
It happened again in 'normal' scalability test: http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-e2e-gce-enormous-cluster/79/consoleText

Proxy to `a8po` was hanging for 6 hours.

**Comment by smarterclayton** [comment]
I'd prefer to fix this with go context, deadlines, and the http.Client
changes in 1.5 across the board if possible (not opposing targeted
fixes, but we're not handling timeouts well in general, not just
here).

Another thing for 1.3

**Comment by lavalamp** [comment]
Ah, here's the issue. We should roll back #22510 when this is fixed.

**Comment by lavalamp** [comment]
I agree w/ @smarterclayton, but we still have a big task of making sure every outgoing http call is found and set up correctly.

**Comment by wojtek-t** [comment]
Yes - I also agree with @smarterclayton

**Comment by gmarek** [comment]
I think we all agree:) I had to make those workarounds to deflake tests.

**Comment by gmarek** [comment]
@lavalamp - is this on your roadmap?

**Comment by lavalamp** [comment]
Not at the moment.. Too much to do, not enough people.

**Comment by gmarek** [comment]
As everywhere;) Just asking.
