### ISSUE TITLE
e2e flake: Cluster size autoscaling

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#22176]
Cluster autoscaling tests fail with because Heapster can't detect that it runs on GCE:
```
I0229 13:35:54.618647       1 gce.go:32] Waiting for GCE metadata to be available
...
I0229 13:36:53.374667       1 gce.go:32] Waiting for GCE metadata to be available
E0229 13:36:55.374864       1 factory.go:68] Failed to create sink: not running on GCE
```

**Comment by piosz** [comment]
cc @mwielgus @fgrzadkowski @kubernetes/autoscaling

**Comment by davidopp** [comment]
ping

**Comment by piosz** [comment]
The problem is with metadata server. See https://github.com/GoogleCloudPlatform/gcloud-golang/issues/194

**Comment by piosz** [comment]
The problem with metadata server is now fixed. The tests still don't pass because of deleting RC is hanging forever:
```
22:02:45 STEP: Removing consuming RC mem-utilization-1
```

**Comment by piosz** [comment]
Obsolete.
