### ISSUE TITLE
docker multiple nodes flannel container not found

### ISSUE THREAD

**Issue by geoHeil** [kubernetes/kubernetes#22178]
Following the (head) https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.md documentation 
I set these variables:

```
export MASTER_IP=127.0.0.1
export K8S_VERSION=1.2.0-alpha.8
export ETCD_VERSION=2.2.1
export FLANNEL_VERSION=0.5.5
export FLANNEL_IFACE=eno2 --> as ifconfig returns this as the interface but tried also with eth0
```

executing:

```
sudo docker -H unix:///var/run/docker-bootstrap.sock run -d \
    --net=host \
    --privileged \
    -v /dev/net:/dev/net \
    quay.io/coreos/flannel:${FLANNEL_VERSION} \
        --ip-masq=${FLANNEL_IPMASQ} \
        --iface=${FLANNEL_IFACE}
```

results in 

```
834666fdad11e41ca7ca6866f9eaad23003e555886e8d60c03254e1861f4ae68
docker: Error response from daemon: Container command not found or does not exist..
```

using it without the last options

```
--ip-masq=${FLANNEL_IPMASQ} \
        --iface=${FLANNEL_IFACE}
```

like this results in no error message being displayed.
Is this a problem? e.g. would I need these options?

Running the `mster.sh`

```
sudo ./master.sh
K8S_VERSION is set to: 1.2.0-alpha.7
ETCD_VERSION is set to: 2.2.1
FLANNEL_VERSION is set to: 0.5.5
FLANNEL_IFACE is set to: eth0
FLANNEL_IPMASQ is set to: true
MASTER_IP is set to: 10.100.4.31
ARCH is set to: amd64
Detecting your OS distro ...
Starting bootstrap docker ...
Starting k8s ...
0a2cb64cc93d2a2baeeb91f6d53c6b53cb284870035241443320b5eb79f3fd55
{ "Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}
Error response from daemon: lstat /var/lib/docker-bootstrap/aufs/mnt/2624579c6358c123bbf34f9e74c25d787c3e0721aaf13b71aea222c7174a6f76/tmp/flannel/subnet.env: no such file or directory
```

Does not work. Could this be connected somehow?

**Comment by Perfect-Web** [comment]
same happens to me

**Comment by ndtreviv** [comment]
+1 This was the command I ran (as part of these instructions: http://kubernetes.io/docs/getting-started-guides/docker-multinode/master/):

```
sudo docker -H unix:///var/run/docker-bootstrap.sock run -d \
    --net=host \
    --privileged \
    -v /dev/net:/dev/net \
    quay.io/coreos/flannel:${FLANNEL_VERSION} \
        --ip-masq=${FLANNEL_IPMASQ} \
        --iface=${FLANNEL_IFACE}
```
This was the result:
```
[HASH HERE]
docker: Error response from daemon: Container command not found or does not exist..
```

And then if I run the next instruction and ignore the error, I get a message about the container not running:
`Error response from daemon: Container [HASH HERE] is not running`

So if I run it without the last two options I don't get the error, and then I run this (the next instruction):
`docker -H unix:///var/run/docker-bootstrap.sock exec [HASH HERE] cat /run/flannel/subnet.env`

This is the output:
```
FLANNEL_NETWORK=10.1.0.0/16
FLANNEL_SUBNET=10.1.48.1/24
FLANNEL_MTU=1472
FLANNEL_IPMASQ=false
```

**Comment by backender** [comment]
Make sure Port 4001 is exposed for your master node. This solved the issue for me.

**Comment by mathsnunes** [comment]
Same problem here, @backender no success even with port exposed =/

**Comment by demohi** [comment]
+1  same problem

**Comment by rpahli** [comment]
I had the same problem.

`0a2cb64cc93d2a2baeeb91f6d53c6b53cb284870035241443320b5eb79f3fd55
{ "Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}
Error response from daemon: lstat /var/lib/docker-bootstrap/aufs/mnt/2624579c6358c123bbf34f9e74c25d787c3e0721aaf13b71aea222c7174a6f76/tmp/flannel/subnet.env: no such file or directory`

I run the docker in a virtual maschine.

for me it works to export FLANNEL_IFACE= to the correct adapter ( -> enp0s3 for me).

**Comment by cmluciano** [comment]
The fix is to add the export as rpahli referenced. I tried clicking on the document to see if the instructions need updated, but I get a 404. I believe this deployment was removed and is now unsupported.
