### ISSUE TITLE
SchedulerPredicates tests flaking regularly

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#22189]
See

  - http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step7-e2e-new/
  - http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-serial/
  - http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-serial/

Or

  - http://ci-test.k8s.io/kubernetes-upgrade-gke-1.1-master-step7-e2e-new
  - http://ci-test.k8s.io/kubernetes-e2e-gke-serial
  - http://ci-test.k8s.io/kubernetes-e2e-gce-serial

**Comment by ihmccreery** [comment]
cc @kubernetes/goog-node 

More specifically, see for example

 - http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step7-e2e-new/453

**Comment by dchen1107** [comment]
This is not node team issue. I discussed with @davidopp offline on this very test. SchedulerPredicates test requires a very deterministic testing environment, for example, number of test nodes, number of kube-systm pods, and each kube-system pod's resource requirement, etc. Unfortunately, e2e environment cannot meet this requirement all the time. It shouldn't written for e2e test since it only verify predictate logic.

**Comment by dchen1107** [comment]
@davidopp I am assigning this to you for delegating or dup to other issue. Thanks!

**Comment by yujuhong** [comment]
FWIW, I looked at http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-serial/709. 
```
15:13:43 Feb 29 15:13:43.759: INFO: At 2016-02-29 15:05:46 -0800 PST - event for maxp-315: {default-scheduler } FailedScheduling: pod (maxp-315) failed to fit in any node
15:13:43 fit failure on node (jenkins-e2e-minion-ayci): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 fit failure on node (jenkins-e2e-minion-yivs): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 fit failure on node (jenkins-e2e-minion-yg0s): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 
15:13:43 Feb 29 15:13:43.759: INFO: At 2016-02-29 15:05:51 -0800 PST - event for maxp-311: {default-scheduler } FailedScheduling: pod (maxp-311) failed to fit in any node
15:13:43 fit failure on node (jenkins-e2e-minion-ayci): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 fit failure on node (jenkins-e2e-minion-yivs): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 fit failure on node (jenkins-e2e-minion-yg0s): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 
15:13:43 Feb 29 15:13:43.759: INFO: At 2016-02-29 15:05:52 -0800 PST - event for maxp-313: {default-scheduler } FailedScheduling: pod (maxp-313) failed to fit in any node
15:13:43 fit failure on node (jenkins-e2e-minion-ayci): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 fit failure on node (jenkins-e2e-minion-yivs): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 fit failure on node (jenkins-e2e-minion-yg0s): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 
15:13:43 Feb 29 15:13:43.759: INFO: At 2016-02-29 15:07:51 -0800 PST - event for maxp-314: {default-scheduler } FailedScheduling: pod (maxp-314) failed to fit in any node
15:13:43 fit failure on node (jenkins-e2e-minion-ayci): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 fit failure on node (jenkins-e2e-minion-yivs): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
15:13:43 fit failure on node (jenkins-e2e-minion-yg0s): Node didn't have enough resource: PodCount, requested: 1, used: 110, capacity: 110
```
The scheduler claimed that all three nodes were at its max capacity, but at the end of the test, the test dumped all the pods on the nodes. 

```
15:13:43 Feb 29 15:13:43.892: INFO: POD                                            NODE                     PHASE    GRACE  CONDITIONS
15:13:43 Feb 29 15:13:43.892: INFO: maxp-0                                         jenkins-e2e-minion-yg0s  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 15:02:46 -0800 PST  }]
15:13:43 Feb 29 15:13:43.892: INFO: maxp-1                                         jenkins-e2e-minion-yg0s  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 15:02:43 -0800 PST  }]
...<skipped>...
15:13:43 Feb 29 15:13:43.894: INFO: maxp-310                                                                Pending         []
15:13:43 Feb 29 15:13:43.894: INFO: maxp-311                                                                Pending         []
15:13:43 Feb 29 15:13:43.894: INFO: maxp-312                                                                Pending         []
15:13:43 Feb 29 15:13:43.894: INFO: maxp-313                                                                Pending         []
15:13:43 Feb 29 15:13:43.894: INFO: maxp-314                                                                Pending         []
15:13:43 Feb 29 15:13:43.894: INFO: maxp-315                                                                Pending         []
15:13:43 Feb 29 15:13:43.895: INFO: elasticsearch-logging-v1-gma1n                 jenkins-e2e-minion-ayci  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:01:31 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: elasticsearch-logging-v1-rt5gp                 jenkins-e2e-minion-yivs  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:01:24 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: fluentd-elasticsearch-jenkins-e2e-minion-ayci  jenkins-e2e-minion-ayci  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:00:32 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: fluentd-elasticsearch-jenkins-e2e-minion-yg0s  jenkins-e2e-minion-yg0s  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:33:17 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: fluentd-elasticsearch-jenkins-e2e-minion-yivs  jenkins-e2e-minion-yivs  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:04:18 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: heapster-v14-gewbs                             jenkins-e2e-minion-ayci  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:26:43 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: kibana-logging-v1-335i2                        jenkins-e2e-minion-yivs  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:01:48 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: kube-dns-v10-prh7x                             jenkins-e2e-minion-yivs  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:01:42 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: kube-proxy-jenkins-e2e-minion-ayci             jenkins-e2e-minion-ayci  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 15:01:53 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: kube-proxy-jenkins-e2e-minion-yg0s             jenkins-e2e-minion-yg0s  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:33:06 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: kube-proxy-jenkins-e2e-minion-yivs             jenkins-e2e-minion-yivs  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:04:18 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: kubernetes-dashboard-v0.1.0-5cvjh              jenkins-e2e-minion-ayci  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:26:41 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: l7-lb-controller-v0.5.2-bblhb                  jenkins-e2e-minion-ayci  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:01:32 -0800 PST  }]
15:13:43 Feb 29 15:13:43.895: INFO: monitoring-influxdb-grafana-v3-5eawn           jenkins-e2e-minion-ayci  Running         [{Ready True 0001-01-01 00:00:00 +0000 UTC 2016-02-29 14:01:46 -0800 PST  }]
```
You can see that there are 330 pods in total and the --max-pods of each node is 110, but not all pods could be scheduled. Note that this test runs in the "Serial" suite and all the kube-system pods had stayed ready since the beginning of this test. There should've been enough resource for all the pods. 

This test started flaking around build 679, when the scheduler cache #20669 was added. I did *not* read the PR, but it's worth checking whether this PR causes the problem.

**Comment by gmarek** [comment]
I'm looking into it. It's usually a problem with interaction with other tests.

**Comment by wojtek-t** [comment]
@yujuhong @gmarek  #20669 is supposed to be a no-op, but sure, there may be a bug in the new cache
I'm happy to help investigating if you have any specific logs that I should look at

**Comment by gmarek** [comment]
I'll keep in mind that possibility. Currently it seems that some pods from daemon_restart test can be left over on Kubelet. I'll add a check in scheduler predicates to check if all namespaces from other tests are gone.

**Comment by yujuhong** [comment]
> Currently it seems that some pods from daemon_restart test can be left over on Kubelet

Scheduler makes it decision (how many pods to create) by looking at the current node usage and capacity. Unless there are pods being created *during the middle of the tests*, it'd be strange that left over pods from another tests would cause problems. As one can see from the pods printed out at the end of the tests, these *extra* pods also need to be destroyed during the test to not show up in the list. Given that this test runs in the serial suite and it started flaking very often recently, I think it's worth checking out. Just my 2 cents.

**Comment by wojtek-t** [comment]
@yujuhong - we think that @gmarek already fixed itin #22278

**Comment by wojtek-t** [comment]
ohh - actually it was running in serial suite - this is a good point

**Comment by wojtek-t** [comment]
but there potentially could be left-over pods from the previous test

**Comment by gmarek** [comment]
Looking at the Kubelet logs that were the case. We'll see if waiting for namespace deletion will solve this problem.

**Comment by yujuhong** [comment]
> Looking at the Kubelet logs that were the case. We'll see if waiting for namespace deletion will solve this problem.

IIUC, kubelet doesn't report how many pods are running on the node, so scheduler shouldn't relying on that for scheduling decisions anyway. Also, leftover pods should be visible either at the beginning or the end of the tests. I am a bit puzzled, but I don't understand the scheduler well enough to suggest that this is a test issue or not. Either way, I think we should fix it :-)

**Comment by gmarek** [comment]
What I saw was logs about killing container (or sth like that) from the previous test, during the next one. If #22278 won't fix it I'll dig deeper.

**Comment by yujuhong** [comment]
> What I saw was logs about killing container (or sth like that) from the previous test, during the next one.

This is expected if you nuke the entire namespace without waiting for pods to be cleaned up properly, but I don't think I saw that in the log. Maybe I've missed it. I'd be happy to help if that's the case. 
On the other hand, this should not affect how the predicate test's and scheduler's views of the pods.


> If #22278 won't fix it I'll dig deeper.

Sure, thanks.

**Comment by gmarek** [comment]
OK, I finally understood @yujuhong comment: https://github.com/kubernetes/kubernetes/issues/22189#issuecomment-190499518

This test indeed prints pods that Kubelet thinks are on them, and there's only 104 of them (not 110 as scheduler seems to think). This suggests that indeed there might be a bug in scheduler cache @wojtek-t @davidopp @dchen1107 @hongchaodeng

**Comment by gmarek** [comment]
I'm trying to reproduce it locally without any success yet.

**Comment by gmarek** [comment]
I managed to get repro, and it's pretty straightforward - just run the test twice. Second run should fail. If not, repeat until it does.

**Comment by gmarek** [comment]
#22355 will make things normal again. Repro from my previous comment is reliably working, so it should be easier to debug. The problem looks like cache not handling correctly Pod removal and keeping some ghost pods in itself.

Reassigning to @hongchaodeng

**Comment by hongchaodeng** [comment]
Thanks folks for helping with it.

I found the root. If you look at the scheduler log, it has a long list of error messages.
In the scheduler cache I added a strong check with state machine.
I have gone through several refactoring in the scheduler cache and unfortunately in the last round I neglected something to update the pod state. I apologize for it.

Should be easy to fix. I will add a test for it too.

**Comment by gmarek** [comment]
@hongchaodeng - no worries, I'm glad that's a small fix.

**Comment by wojtek-t** [comment]
@hongchaodeng - thanks for debugging! I will take a look into your new PR tomorrow.

**Comment by hongchaodeng** [comment]
Now I'm really sure what's causing the problem. 

Thank @yujuhong for sharing the logs to me. Complaint: I have been trying to reproduce that but unfortunately unsuccessful. Meanwhile unable to access the google internal logs and unwilling to ask.

```
➜  Downloads cat kubernetes-e2e-gce-serial_709_173.255.116.165_22-kube-scheduler.log| grep RemovePod
E0229 22:02:55.575468       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-daemonrestart-fknmr/daemonrestart10-fcb3d28f-df2f-11e5-9715-42010af01555-0wbvp
E0229 22:02:55.582835       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-daemonrestart-fknmr/daemonrestart10-fcb3d28f-df2f-11e5-9715-42010af01555-47bd0
E0229 22:02:55.594029       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-daemonrestart-fknmr/daemonrestart10-fcb3d28f-df2f-11e5-9715-42010af01555-brskh
E0229 22:02:55.611872       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-daemonrestart-fknmr/daemonrestart10-fcb3d28f-df2f-11e5-9715-42010af01555-k73f1
E0229 22:02:55.615439       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-daemonrestart-fknmr/daemonrestart10-fcb3d28f-df2f-11e5-9715-42010af01555-ken5c
E0229 22:02:55.624888       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-daemonrestart-fknmr/daemonrestart10-fcb3d28f-df2f-11e5-9715-42010af01555-nzxqx
E0229 22:02:55.634992       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-daemonrestart-fknmr/daemonrestart10-fcb3d28f-df2f-11e5-9715-42010af01555-o0qvx
E0229 22:02:55.643240       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-daemonrestart-fknmr/daemonrestart10-fcb3d28f-df2f-11e5-9715-42010af01555-un1fe
E0229 22:02:55.643259       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-daemonrestart-fknmr/daemonrestart10-fcb3d28f-df2f-11e5-9715-42010af01555-xpldh
E0229 22:02:55.649389       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-daemonrestart-fknmr/daemonrestart10-fcb3d28f-df2f-11e5-9715-42010af01555-yppm2
E0229 22:27:11.373069       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: kube-system/fluentd-elasticsearch-jenkins-e2e-minion-91ld
E0229 22:27:11.376563       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: kube-system/heapster-v14-syc72
E0229 22:27:11.387416       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: kube-system/kube-proxy-jenkins-e2e-minion-91ld
E0229 22:27:11.391838       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: kube-system/kubernetes-dashboard-v0.1.0-6b3zi
E0229 23:01:11.377702       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: kube-system/fluentd-elasticsearch-jenkins-e2e-minion-7cww
E0229 23:01:11.383210       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: kube-system/kube-proxy-jenkins-e2e-minion-7cww
E0229 23:35:31.435645       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: kube-system/fluentd-elasticsearch-jenkins-e2e-minion-yg0s
E0229 23:35:31.440666       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: kube-system/kube-proxy-jenkins-e2e-minion-yg0s
E0229 23:36:04.848943       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-resize-nodes-e3tsz/additionalpod
E0229 23:51:21.164705       7 factory.go:160] scheduler cache RemovePod failed: pod state wasn't added but get removed. Pod key: e2e-tests-kubelet-perf-b6a2m/resource105-b687d783-df34-11e5-9715-42010af01555-pvlum
```

Previously this breaks the assumption of scheduler cache. See https://github.com/kubernetes/kubernetes/pull/22381#issuecomment-194724349.

Those pods haven't gone through scheduler path. I believe this will be fixed by https://github.com/kubernetes/kubernetes/pull/22381.

**Comment by yujuhong** [comment]
@hongchaodeng, I just tried with my personal account. The bucket is public, but you have to login in order to access the data (there is an internal bug for GCS). Sorry for the trouble.
https://storage.cloud.google.com/?arg=kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/709

**Comment by wojtek-t** [comment]
@hongchaodeng - yes what you wrote above makes perfect sense. Thanks for debugging it!

**Comment by wojtek-t** [comment]
Actually, this one is now debugging (and it was already fixed by reverting a harmful PR).
Closing this issue.
