### ISSUE TITLE
Workqueue Jobs for long running processes in continuous deployment

### ISSUE THREAD

**Issue by ch-acctg** [kubernetes/kubernetes#22188]
Hi, we have been trying to implement a reliable continuous deployment on top of Kubernetes.  We originally looked in to replication controllers, but our services are streams that cannot be reconnected once started and the version of graceful termination for an rc is much less than what we need.

What we need is a way to keep an older service alive until the clients have disconnected from the stream, and then terminate the pod.  We assume that we will be able to steer new stream requests to newly deployed services.

Is it possible that workqueue based jobs could be utilized to bring up new service releases in this way?  Are there better patterns now or in the future planned?

I understand that when a workqueue job terminates successfully, all other pods must be ready to terminate as well.  Is there a way to modify the job to terminate unsuccessfully and not restart (and before the upgrade be set to restart on failure) or other solution to reduce the workqueue count to those only still serving clients?

We are interested in any solution that would automate in some form the draining of our stream servers.

Thanks!

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by erictune** [comment]
I don't think Workqueue Jobs are a good fit.

**Comment by wuestkamp** [comment]
Is there a good pattern you found @ch-acctg?
