### ISSUE TITLE
Example API server test always fails if local cluster is running

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#22182]
...because they both use http://127.0.0.1:8080

The example API server should use another port like 8081 that isn't likely to be used by something already running on a dev machine.

**Comment by bgrant0607** [comment]
@pmorie Which test specifically?

**Comment by nikhiljindal** [comment]
Yes. 
I assume its for https://github.com/kubernetes/kubernetes/tree/master/examples/apiserver
I can fix it once other 1.2 items are done.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/22898 fixes this
