### ISSUE TITLE
Kube proxy/endpoints controller should handle graceful delete ASAP

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#22191]
When a graceful delete is initiated the deletion timestamp on an endpoint is set. This usually means the webserver will refuse new connections and start draining existing connections, the database has been sigtermed and is checkpointing to disk, follower is leaving quorum etc. 

When kube-proxy notices a deletion timestamp it should stop routing traffic to the endpoint immidiately, or at least I think this should be the default, and a service can opt out via annotation or something. The default grace period is currently 30s which means we might be blackholing traffic for a while.

**Comment by bprashanth** [comment]
and/or endpoints controller should treat deletionTimestamp as a signal to remove the pod from the endpoints list.

**Comment by luksa** [comment]
This issue can be closed. The endpoints controller already removes terminating pods from the endpoints list. See https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L405-L408
