### ISSUE TITLE
System container stats ["kubelet", "runtime"] not visible to kubelet

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#22198]
System container stats are not visible to kubelet

kubelet_test is failing stats collection test when checking for system container stats:

>
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/kubelet_test.go:255
12:05:09 
12:05:09       Expected
12:05:09           <[]string | len:0, cap:0>: []
12:05:09       to consist of
12:05:09           <[]interface {} | len:2, cap:2>: ["kubelet", "runtime"]
12:05:09 

Disabled test for now until this is resolved

**Comment by vishh** [comment]
Is this happening only on a few distros? #21337 should have fixed the only known issue on ContainerVM.

**Comment by pwittrock** [comment]
No, it is happening on all tested distros - containervm, coreos, ubuntu

**Comment by dchen1107** [comment]
This is a regression and we should fix it for 1.2 release.

**Comment by vishh** [comment]
How is the kubelet being run for these tests? We set a few flags using salt? Do we have to update configuration elsewhere in addition to salt?

**Comment by vishh** [comment]
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
@vishh - I would think we fixed all this in: #20687

I will look to see if I can reproduce from HEAD using Salt on a RHEL distro...

**Comment by vishh** [comment]
I doubt that salt has any issues. Our regular e2es are happy. That's why I suspect that the node e2e setup has to be updated to include recent flag updates.

**Comment by vishh** [comment]
@derekwaynecarr: I think this [logic](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/e2e_service.go#L129) needs to include `--system-cgroups=/system`, `--runtime-cgroups=/docker-daemon`, `--kubelet-cgroups=/kubelet`.

**Comment by vishh** [comment]
@pwittrock: Can you post a pointer to the test that needs to be re-enabled as part of fixing this issue?

**Comment by vishh** [comment]
nvm found it. Updated #22311 to re-enable the tests.
