### ISSUE TITLE
Can't create pods with multiple gitRepo volumes in 1.1.8

### ISSUE THREAD

**Issue by wkharold** [kubernetes/kubernetes#22221]
When preparing to upgrade from 1.0.x to 1.1.x we discovered that some of our pods would not instantiate properly in 1.1.8. They work fine in 1.0.x. The issue appears to involve gitRepo volumes. We were able to get some of the pods in question to instantiate by moving the gitRepo volume declaration to the beginning of the volumes: section. Some of our pods, however, use multiple gitRepo volumes; we haven't found a way to get them to come up under 1.1.8.

This gist reproduces the problem: https://gist.github.com/wkharold/f7c3a818448360204f1f

**Comment by childsb** [comment]
@wkharold we've made a LOT of updates around the volume framework code for 1.3.  Can you try this again on 1.3?

**Comment by matchstick** [comment]
Please re-open if you can reproduce on 1.3.4 or later.
