### ISSUE TITLE
fluentd images don't send the cluster name

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#22222]
Is the expectation that there will be one elasticsearch cluster per Kubernetes cluster? That might not always be the case.

**Comment by therc** [comment]
cc @jimmidyson

**Comment by jimmidyson** [comment]
Where would the cluster name come from?

**Comment by therc** [comment]
Downward API? Passed explicitly by the admin?

**Comment by therc** [comment]
Just to be clear: I'm referring to the case where more than one Kubernetes cluster forwards to the same ES cluster, not the other way around. They are all set up to talk the same endpoint. If you do that, though, there's no easy way to tell if a log entry came from Kubernetes cluster A or B. You need to correlate with pod names running at the time in both.

**Comment by jchauncey** [comment]
How would you do this normally? How do you tell two clusters apart?

My first thought is the labels of a pod

**Comment by therc** [comment]
As far as I'm aware, the only component that knows about such a thing is the controller manager. It uses the cluster name to tag routes, load balancers, etc. Even the apiserver doesn't know about it and thus can't return it through any means.
I keep the cluster names outside of the cluster in the first place. For kube-dns, I just generate separate YAML files for separate clusters, with the cluster name expanded in the command line.
In 1.2, you could put the cluster name in a ConfigMap at bootstrap time. Everything that needs to know the cluster name could access it. I wanted to do just that for kube-dns, which means one template less to explicitly expand.

**Comment by therc** [comment]
It occurred to me that if we allow to set the ES index name (see #23195 for a discussion on how to tweak fluentd configurations in general), then the administrator could tell fluentd to forward to per-cluster indices, which might be better than adding yet another field. But I'm very new to ES, so maybe the latter is still preferable to some? I'm wary of adding too many options.

**Comment by jimmidyson** [comment]
We actually do something similar in the OpenShift aggregated logging images, sending logs from different namespaces to separate ES indices. The fluentd Elasticsearch plugin allows that configuration now so that is all doable.

**Comment by spiffxp** [comment]
/sig instrumentation
because fluentd addon
