### ISSUE TITLE
Unable to utilize existing routing table on AWS

### ISSUE THREAD

**Issue by smugcloud** [kubernetes/kubernetes#22224]
Hello,

We are looking to utilize Kubernetes on AWS within an existing VPC, Subnet, and Routing Table.  These items are configured to work within a larger VPN, but provide full access to internal services, as well as the public Internet.

Currently, I have modified the `kube-up.sh` script to utilize these components, and not create any of the resources as `kube-up` currently does, including the routing table.  The instances start up but I am observing issues getting all of the components properly configured.

In chatting with @justinsb, this is outside of the expected kube-up path and I was hoping to get some guidance on how this can be accomplished (or have this incorporated in a future version), even if I need to fork the script (which we've already done).  Adding any values to the routing table _could_ be a possibility but I am hoping that is not necessary and we can align with a current route.

**kube-apiserver**
`Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
I0229 22:27:08.826404       8 logs.go:40] http: TLS handshake error from 10.178.155.18:44214: EOF`

 **kube-controller**
`routecontroller.go:52] Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: kubernetes`

**Routing table**

```
10.178.152.0/22 local

0.0.0.0/0 igw-xxxxx

10.0.0.0/8 vgw-xxxxxxxx

10.255.0.0/22 pcx-xxxxxxxx
```

**Comment by jeremyd** [comment]
You can have it use an existing VPC route table by tagging the route table with the tag KubernetesCluster=kubernetes

**Comment by paultyng** [comment]
I'm hitting this same issue as well.  How would you modify the cluster name? Should you pass it explicitly to the controller manager?

**Comment by vchan2002** [comment]
The code seems to indicate that the tag to look for 
`	filters := []*ec2.Filter{newEc2Filter("tag:"+TagNameKubernetesCluster, clusterName)}`
However... either putting in TagNameKubernetesCluster or KubernetesCluster with the cluster name (I just stuck with the default kubernetes) doesn't seem to work.... the controller still complains about it.

**Comment by justlaputa** [comment]
I met same problem in my AWS cluster, is this a issue or by-design? would it be fixed later?

**Comment by justlaputa** [comment]
if you are not using native aws route table to route traffic to pods, instead using other network implementations like flannel (my case), you can add this flag to controller manager to prevent this issue from happening:

```
--configure-cloud-routes=false
```
