### ISSUE TITLE
MESOS: K8sm build problem

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#22237]
Using HEAD of master branch
```shell
$ git clone http://github.com/kubernetes/kubernetes
$ export KUBERNETES_CONTRIB=mesos
$ ./build/run.sh hack/build-go.sh
+++ [0229 19:18:20] Verifying Prerequisites....
+++ [0229 19:18:24] Building Docker image kube-build:build-b9cb2642b7.
+++ [0229 19:18:31] Running build command....
+++ [0229 19:18:31] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubemark
    cmd/hyperkube
    cmd/linkcheck
    plugin/cmd/kube-scheduler
    contrib/mesos/cmd/k8sm-scheduler
    contrib/mesos/cmd/k8sm-executor
    contrib/mesos/cmd/k8sm-controller-manager
    contrib/mesos/cmd/km
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    cmd/genswaggertypedocs
    examples/k8petstore/web-server/src
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    test/e2e_node/e2e_node.test
# k8s.io/kubernetes/contrib/mesos/cmd/k8sm-executor
runtime.main_main: main.main: not defined
runtime.main_main: undefined: main.main
!!! Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:433
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${goldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
```

Compiling Kubernetes without Mesos works fine. Did something change here?

**Comment by huang195** [comment]
cc: @jdef @sttts @karlkfi

**Comment by huang195** [comment]
I'm not sure what happened, but seems to have resolved by itself.

**Comment by huang195** [comment]
I still seem to have this problem, but there's a workaround.
If I just `git clone` a fresh local repo and compile by `KUBERNETES_CONTRIB=mesos ./build/run.sh hack/build-go.sh`, it would result in the problem described above. But if I compile `release-1.1` first (which compiles fine), and then switch back to `master` branch and do another compile, it now works. This seems to be reproducible.

**Comment by jdef** [comment]
related? http://stackoverflow.com/questions/14739188/how-to-fix-this-error-runtime-main-undefined-main-init

**Comment by jdef** [comment]
possible culprit: https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/cmd/km/hyperkube_test.go#L18

**Comment by jdef** [comment]
upstream does this too:
https://github.com/kubernetes/kubernetes/blob/master/cmd/hyperkube/hyperkube_test.go#L19

**Comment by huang195** [comment]
@jdef are you able to reproduce this problem in your environment with a freshly cloned local repo? The error message above seems to complain about `k8s.io/kubernetes/contrib/mesos/cmd/k8sm-executor`, which only have main.go and doc.go files.

**Comment by jdef** [comment]
Haven't attempted to reproduce as per your exact steps. But my typical flow
after switching between branches is to "make clean all" -- that has worked
every time for me. I'm a little swamped today, but I'll try to circle back
around to this

**Comment by huang195** [comment]
Sure, whenever you get a chance. After compiling release-1.1 and then switching back to master, I'm able to compile it fine. I tried your "make clean all" suggestion. After I compiled release-1.1, I switched back to master, did a "make clean all", and the same problem is happening again. It seems compiling master with KUBERNETES_CONTRIB=mesos in a "clean state" (whatever that means) is failing.

**Comment by jdef** [comment]
very strange. we don't have that problem in our CI setup and I don't
experience that on my dev box.

what version of Go are you building with? I'm using 1.4.2

**Comment by huang195** [comment]
I'm also using 1.4.2 inside of the kube-build Docker container.

```shell
root@rsch-dal09-haih-k8sm-2:~/kubernetes# KUBERNETES_CONTRIB=mesos build/run.sh hack/build-go.sh
+++ [0303 09:12:24] Verifying Prerequisites....
+++ [0303 09:12:28] Building Docker image kube-build:build-b9cb2642b7.
+++ [0303 09:12:40] Running build command....
+++ [0303 09:12:40] Creating data container
Go version: go version go1.4.2 linux/amd64
+++ [0303 09:12:42] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/kubemark
    cmd/hyperkube
    cmd/linkcheck
    plugin/cmd/kube-scheduler
    contrib/mesos/cmd/k8sm-scheduler
    contrib/mesos/cmd/k8sm-executor
    contrib/mesos/cmd/k8sm-controller-manager
    contrib/mesos/cmd/km
    cmd/kubectl
    cmd/integration
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/mungedocs
    cmd/genbashcomp
    cmd/genconversion
    cmd/gendeepcopy
    cmd/genswaggertypedocs
    examples/k8petstore/web-server/src
    github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    test/e2e_node/e2e_node.test
# k8s.io/kubernetes/contrib/mesos/cmd/k8sm-executor
runtime.main_main: main.main: not defined
runtime.main_main: undefined: main.main
```

```
root@rsch-dal09-haih-k8sm-2:~/kubernetes# docker run kube-build:build-b9cb2642b7 go version
go version go1.4.2 linux/amd64
```

It's very strange that we're using the same Go version and my build environment is standardize since it's encapsulated inside of a Docker container, and yet the result is different.

**Comment by huang195** [comment]
Closing this since there's a workaround and this can't seem to be reproducible by others.
