### ISSUE TITLE
DNS should store reverse records for service IPs.

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#22252]
Apparently it's a thing for some software to resolve a name to an IP and then reverse-resolve that IP to a name again.  I can't think of any reason not to add reverse records for kube services.  This will lighten the load on upstream DNS servers

@smarterclayton @ArtfulCoder

**Comment by smarterclayton** [comment]
I thought we already did this - I know in Openshift we implemented it
(since the backing service cache has an index for reverse records).

**Comment by thockin** [comment]
Nope.  We don't.  We should.

**Comment by thockin** [comment]
Dup of #15690
