### ISSUE TITLE
Priority function should return bigger values

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#22272]
Currently in scheduler we assume that a priority function returns value from 0 to 10. This makes scoring quite flat, especially when we are getting to large clusters like 1000-nodes.
We should change it to support bigger values and/or float values.

@davidopp

**Comment by resouer** [comment]
Also agree with this.  Any more progress here, like, what's the reasonable score range?

**Comment by davidopp** [comment]
We could do that, but see also
https://groups.google.com/d/msg/kubernetes-sig-scheduling/jz-IjaoLfm8/3JU7Exd5DAAJ

If we have bigger priority function values, that approach might not fit the total in an int64 (actually it might not fit even with 0-10 range for priority functions, if you have a large enough number of priority functions; I hadn't really thought about it.)
