### ISSUE TITLE
kube2sky has too many restarts

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#22290]
On a 1000 node cluster, kube-dns doesn't seem very stable.  Unclear if the underlying issue has anything to do with the 1k nodes or not.  @kubernetes/sig-network 
```
% export NUM_NODES=1000
% export NUM_MIGS=1
% export MAX_INSTANCES_PER_MIG=1000
% export MASTER_SIZE=n1-standard-32
NAME                                           READY     STATUS             RESTARTS   AGE
...
kube-dns-v10-e2tnx                             4/4       Running            28         13h
...

28 restarts seems higher than expected?  Note that it's 26 for kube2sky and 2 for skydns:

```
% kubectl --namespace=kube-system describe pod kube-dns-v10-e2tnx
Name:                           kube-dns-v10-e2tnx
Namespace:                      kube-system
Image(s):                       gcr.io/google_containers/etcd-amd64:2.2.1,gcr.io/google_containers/kube2sky:1.12,gcr.io/google_containers/skydns:2015-10-13-8c72f8c,gcr.io/google_containers/exechealthz:1.0
Node:                           kubernetes-minion-zco9/10.240.0.11
Start Time:                     Mon, 29 Feb 2016 19:25:43 -0800
Labels:                         k8s-app=kube-dns,kubernetes.io/cluster-service=true,version=v10
Status:                         Running
Reason:
Message:
IP:                             10.244.80.2
Replication Controllers:        kube-dns-v10 (1/1 replicas created)
Containers:
  etcd:
    Container ID:       docker://765b3f90414fa614b7d226498a3f7d55f4b918e7b4b52d4cf8a6729885307958
    Image:              gcr.io/google_containers/etcd-amd64:2.2.1
    Image ID:           docker://202873aab189580883e6e7ec9b1479989db6fe8ce91a34bc3b786eb3d5db57c2
    QoS Tier:
      memory:   Guaranteed
      cpu:      Guaranteed
    Limits:
      cpu:      100m
      memory:   50Mi
    Requests:
      memory:           50Mi
      cpu:              100m
    State:              Running
      Started:          Mon, 29 Feb 2016 19:26:06 -0800
    Ready:              True
    Restart Count:      0
    Environment Variables:
  kube2sky:
    Container ID:       docker://65bf43ea4e7fbc53646a99bf7fa94f4f778428d8b043e66d4ccdd5e37a9e7a69
    Image:              gcr.io/google_containers/kube2sky:1.12
    Image ID:           docker://e81ceeee48ea7dd5647598acd6c35f8f9b605424cf7b0024b0de9df9cc4e50ef
    QoS Tier:
      cpu:      Guaranteed
      memory:   Guaranteed
    Limits:
      cpu:      100m
      memory:   50Mi
    Requests:
      cpu:                      100m
      memory:                   50Mi
    State:                      Running
      Started:                  Tue, 01 Mar 2016 08:28:12 -0800
    Last Termination State:     Terminated
      Reason:                   Error
      Exit Code:                137
      Started:                  Tue, 01 Mar 2016 07:58:10 -0800
      Finished:                 Tue, 01 Mar 2016 08:28:12 -0800
    Ready:                      True
    Restart Count:              26
    Environment Variables:
  skydns:
    Container ID:       docker://a79758e5563d465b430d790647879d79505cac36400e0305b9932c1aa8deb358
    Image:              gcr.io/google_containers/skydns:2015-10-13-8c72f8c
    Image ID:           docker://763c92e53f311c40a922628a34daf0be4397463589a7d148cea8291f02c12a5d
    QoS Tier:
      memory:   Guaranteed
      cpu:      Guaranteed
    Limits:
      cpu:      100m
      memory:   50Mi
    Requests:
      cpu:                      100m
      memory:                   50Mi
    State:                      Running
      Started:                  Mon, 29 Feb 2016 19:27:33 -0800
    Last Termination State:     Terminated
      Reason:                   Error
      Exit Code:                2
      Started:                  Mon, 29 Feb 2016 19:27:03 -0800
      Finished:                 Mon, 29 Feb 2016 19:27:33 -0800
    Ready:                      True
    Restart Count:              2
    Environment Variables:
  healthz:
    Container ID:       docker://e2db75954db07022f1e53087c3e37355451746d4e9813c3b748732056962e43e
    Image:              gcr.io/google_containers/exechealthz:1.0
    Image ID:           docker://ade0092735d8b2a2ece16e7452debe2d773591ceae9af0b98253f4d1bcc95965
    QoS Tier:
      cpu:      Guaranteed
      memory:   Guaranteed
    Limits:
      memory:   20Mi
      cpu:      10m
    Requests:
      cpu:              10m
      memory:           20Mi
    State:              Running
      Started:          Mon, 29 Feb 2016 19:25:45 -0800
    Ready:              True
    Restart Count:      0
    Environment Variables:
Conditions:
  Type          Status
  Ready         True 
Volumes:
  etcd-storage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-poka6:
    Type:       Secret (a secret that should populate this volume)
    SecretName: default-token-poka6
Events:
  FirstSeen     LastSeen        Count   From                                    SubobjectPath                   Reason  Message
  ─────────     ────────        ─────   ────                                    ─────────────                   ──────  ───────
  30m           30m             1       {kubelet kubernetes-minion-zco9}        spec.containers{kube2sky}       Created Created container with docker id 05d4741045d1
  30m           30m             1       {kubelet kubernetes-minion-zco9}        spec.containers{kube2sky}       Started Started container with docker id 05d4741045d1
  12h           28s             26      {kubelet kubernetes-minion-zco9}        spec.containers{kube2sky}       Pulled  Container image "gcr.io/google_containers/kube2sky:1.12" already present on machine
  28s           28s             1       {kubelet kubernetes-minion-zco9}        spec.containers{kube2sky}       Created Created container with docker id 65bf43ea4e7f
  28s           28s             1       {kubelet kubernetes-minion-zco9}        spec.containers{kube2sky}       Started Started container with docker id 65bf43ea4e7f

```

Logs:
```
% kubectl --namespace=kube-system logs kube-dns-v10-e2tnx -c skydns
2016/03/01 03:27:33 skydns: falling back to default configuration,cluster could not read from etcd: 100: Key not found (/skydns) [3]
2016/03/01 03:27:33 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2016/03/01 03:27:33 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
% kubectl --namespace=kube-system logs kube-dns-v10-e2tnx -c kube2sky
I0301 16:28:12.486375       1 kube2sky.go:436] Etcd server found: http://127.0.0.1:4001
I0301 16:28:13.487519       1 kube2sky.go:503] Using https://10.0.0.1:443 for kubernetes master
I0301 16:28:13.487538       1 kube2sky.go:504] Using kubernetes API <nil>
```
previous logs for kube2sky are the same, but 30 minutes earlier.

**Comment by bprashanth** [comment]
That looks like OOM, either from the system of because of our 50m limits. I'm just removing the limits in https://github.com/kubernetes/kubernetes/pull/22253

**Comment by bprashanth** [comment]
I'm assuming you don't really have any Services? in which case out dns pod shouldn't be doing anything proportional to the size of the cluster, so it's weird that we aren't seeing this in other cluster. Or this could be  https://github.com/kubernetes/kubernetes/issues/21940 and it has nothing to do with 1000 nodes.

**Comment by thockin** [comment]
kube2sky still does a pod watch, which might blow out resources.

Have we settled on a way to allocate resources for kube-system pods that considers cluster size?  This is going to keep biting us.

**Comment by bprashanth** [comment]
> kube2sky still does a pod watch, which might blow out resources.

Yeah I noticed that. That's the most likely suspect. 

> Have we settled on a way to allocate resources for kube-system pods that considers cluster size? This is going to keep biting us.

I'm planning to extend https://github.com/kubernetes/kubernetes/issues/21500 to do it

**Comment by thockin** [comment]
Maybe I misunderstand #21500 (skimmed) - is it going to be parameterized?  On what?

**Comment by alex-mohr** [comment]
Re: OOM suspected, do we generate events in those cases?  How is a user supposed to debug such issues if it's in their pods instead of ours?  Can we do something better re: introspectability that will help both them and us?

**Comment by bprashanth** [comment]
@alex-mohr https://github.com/kubernetes/kubernetes/issues/22322

**Comment by bprashanth** [comment]
The few enormous cluster logs I checked (there are only a few available) didn't show restarts, but we don't track this. Please reopen if it's still an issue with a cluster built post https://github.com/kubernetes/kubernetes/pull/22253.

> Maybe I misunderstand #21500 (skimmed) - is it going to be parameterized? On what?

@thockin the kubelet exports stats and we can access it from tests via the master proxy. We'd probably have to aggregate over some period in a soak cluster.
