### ISSUE TITLE
jenkins flake: Jenkins unit/integration reported "no data"

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#22291]
#21187 reported "no data" for Jenkins unit/integration and required a manual "@k8s-bot unit test this" to re-trigger.  PR had been idle for 8+ hours.

**Comment by fejta** [comment]
http://submit-queue.k8s.io/#/history was restarted and doesn't preserve state I suspect is the problem. Going to ignore for now.
