### ISSUE TITLE
kubectl scale should use scale subresource

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22308]
We reverted it to use Update (PUT) while scale was broken. We should revert back, for ReplicationController, ReplicaSet, and Deployment.

cc @janetkuo @madhusudancs @soltysh @kargakis

**Comment by kargakis** [comment]
@bgrant0607 is everything ok now with the scale subresource?

**Comment by bgrant0607** [comment]
@kargakis No, not done yet.

**Comment by kargakis** [comment]
@bgrant0607 can you link any issues that need to be fixed before we proceed here?

**Comment by bgrant0607** [comment]
@kargakis @soltysh I believe this can be fixed now.

**Comment by pwittrock** [comment]
Duplicate of #29698
