### ISSUE TITLE
Cassandra cannot reach apiserver

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/kubernetes#22307]
Hi,

On kube v1.2.0-alpha8, I am trying the cassandra example with the image gcr.io/google_containers/cassandra:v6 but the apiserver fails to resolve DNS for the apiserver on kubernetes.default.cluster.local:

```
INFO  19:59:03 Getting endpoints from https://kubernetes.default.cluster.local/api/v1/namespaces/default/endpoints/cassandra
WARN  19:59:16 Request to kubernetes apiserver failed
java.net.UnknownHostException: kubernetes.default.cluster.local
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625) ~[na:1.7.0_79]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160) ~[na:1.7.0_79]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.7.0_79]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.7.0_79]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.7.0_79]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275) ~[na:1.7.0_79]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371) ~[na:1.7.0_79]
....
```

How can I override DNS and make the container use my local (insecure) apiserver?

This is the Pod spec I am using:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cassandra
  name: cassandra-1
spec:
  containers:
  - args:
    - /run.sh
    resources:
      limits:
        cpu: "0.1"
    image: gcr.io/google_containers/cassandra:v6
    name: cassandra
    ports:
    - name: cql
      containerPort: 9042
    - name: thrift
      containerPort: 9160
    volumeMounts:
    - name: data
      mountPath: /cassandra_data
    env:
    - name: MAX_HEAP_SIZE
      value: 256M
    - name: HEAP_NEWSIZE
      value: 64M
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  volumes:
  - name: data
    hostPath:
      path: /var/lib/cassandra-1
```

Thanks,
Andrej

**Comment by saad-ali** [comment]
https://github.com/kubernetes/kubernetes/issues/20961

**Comment by chrislovecnm** [comment]
So this is because Kubernetes example uses a custom seed provider.  

You can see that the DNS name is hardcoded in the customer provider https://github.com/amygdala/kubernetes/blob/cassandra2/examples/cassandra/java/src/io/k8s/cassandra/KubernetesSeedProvider.java#L121

Using a custom docker is probably the way to go if you want to work around this.

The seed provider is also configured in cassandra.yaml https://github.com/amygdala/kubernetes/blob/cassandra2/examples/cassandra/image/cassandra.yaml#L257

**Comment by chrislovecnm** [comment]
@andrejvanderzee I cannot read source code today :)

Have you tried overriding the url with the env var? `KUBERNETES_PORT_443_TCP_ADDR`?

**Comment by chrislovecnm** [comment]
@andrejvanderzee any progress?

**Comment by chrislovecnm** [comment]
@andrejvanderzee ping ... otherwise can we close?

**Comment by andrejvanderzee** [comment]
@chrislovecnm go ahead and close!
