### ISSUE TITLE
Implement scheduler --run-once mode

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#22301]

**Comment by jdef** [comment]
can you elaborate on this?

**Comment by quinton-hoole** [comment]
I think this is for @mikedanese.  Could you also add a priority Mike?

**Comment by quinton-hoole** [comment]
Tentatively assigned priority p2.

**Comment by timothysc** [comment]
I'm going to enqueue this now.

**Comment by roberthbailey** [comment]
Closing as obsolete as discussed during the SIG meeting.
