### ISSUE TITLE
Summary API should report network stats from `eth0`

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#22319]
Currently the summary API reports network stats summed over all interfaces ([code](https://github.com/kubernetes/kubernetes/blob/bef2b8f1edd509c7bb209a5df8fae53ad0d7ea56/pkg/kubelet/server/stats/summary.go#L299-L304)), but this is not correct.

We should search for the [`DefaultInterface`](https://github.com/kubernetes/kubernetes/blob/bef2b8f1edd509c7bb209a5df8fae53ad0d7ea56/pkg/kubelet/network/kubenet/kubenet_linux.go#L41) and only report the stats for that interface.

/cc @kubernetes/goog-node

**Comment by rakesh-k** [comment]
I am seeing this in my log and looks like it is related to the default interface being treated as `eth0`. The default interface in case of my node is `ens192`.

`summary.go:311] Missing default interface "eth0" for s%!(EXTRA string=node:`

**Comment by ShashankYadav** [comment]
Using kubernetes 1.3 here. Even thought the default interface is eno1 for my node, I see:
`summary.go:311] Missing default interface "eth0" for s%!(EXTRA string=node`

**Comment by stregatto** [comment]
Me too, kubernetes v1.3.0
Error "`Missing default interface "eth0" for pod:kube-system`" for all kube-system pods

**Comment by timstclair** [comment]
See https://github.com/kubernetes/kubernetes/issues/28407

**Comment by stregatto** [comment]
I think is a wrong assumption.
Perhaps it can be correct for standard pods, but pods can use the worker network (like kube-system's pods, api, controller, proxy, scheduler), this mean the pods do not use eth0 for sure but uses lot of different interfaces (enoX, bondX ... and so on).
