### ISSUE TITLE
Consider adding metadata.internal to /etc/hosts

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#22325]
Sometimes DNS resolution of metadata.internal flakes. In pods, it flakes because eg: kube-dns is down, on the master it flakes for reasons unknown (https://groups.google.com/forum/#!topic/google-containers/SPDYR-MqVZo). We can probably get away with adding the well known ip of the metadata server to /etc/hosts. This will have to be cloud provider specific.

**Comment by justinsb** [comment]
FYI, on AWS there is no name; you just use 169.254.169.254.  At least as far as I know!

**Comment by bgrant0607** [comment]
I want to block metadata.internal entirely. See #8867
