### ISSUE TITLE
Surface oom kills better

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#22322]
Figuring out something was oom killed because of a draconian memory limit is too hard, or am i missing a trick? I simulated an oom and had to ssh into the node and grep logs. Events didn't tell me much.

**Comment by therc** [comment]
I look for error code 137 in Docker logs or oom entries in syslog...

**Comment by bprashanth** [comment]
> I look for error code 137 in Docker logs or oom entries in syslog...

Exactly. That's too hard. You can also look for the OOMKiled fieldl in docker inspect which probably won't work for sysoom, but we should get something that shows up in kubectl to display this.

**Comment by dchen1107** [comment]
I assume you are referring memory-exceeded OOM killer here. We asked docker to provide such information a while back, and looks like there is a regression now: https://github.com/docker/docker/issues/18510

**Comment by bprashanth** [comment]
@dchen1107 I'm asking that we send an event if we notice OOMKilled:true in docker inspect. If there's a regression we won't send the event, but in the happy case this will help.

**Comment by yujuhong** [comment]
We [set the ContainerStatus.Reason to OOMKilled](https://github.com/kubernetes/kubernetes/blob/6dee237d858daad29a402f9316a6df52ad95d0a4/pkg/kubelet/dockertools/manager.go#L362). @bprashanth, do you just want an event?

**Comment by bprashanth** [comment]
Usually I come back and the containers in crash loop backoff or Error, and `-o yaml |grep -i oom` shows nothing, so I'm guessing we clobber it?

2 things would make life easier:

1. Communicate OOMKill clearly in a non-clobbering way
2. Surface tasks *in* containers getting killed because of a memory limit (this can be hard, but just throwing it out there). I.e kern.log has:
```
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.918110] Call Trace:
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.922154]  [<ffffffff8150db3f>] ? dump_stack+0x41/0x51
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.929095]  [<ffffffff8150b757>] ? dump_header+0x76/0x1e8
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.936176]  [<ffffffff8114044d>] ? find_lock_task_mm+0x3d/0x90
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.942535]  [<ffffffff8114088d>] ? oom_kill_process+0x21d/0x370
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.950127]  [<ffffffff8114044d>] ? find_lock_task_mm+0x3d/0x90
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.956260]  [<ffffffff811a053a>] ? mem_cgroup_oom_synchronize+0x52a/0x590
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.964732]  [<ffffffff8119fac0>] ? mem_cgroup_try_charge_mm+0xa0/0xa0
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.971585]  [<ffffffff81141040>] ? pagefault_out_of_memory+0x10/0x80
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.979747]  [<ffffffff81057505>] ? __do_page_fault+0x3c5/0x4f0
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.986043]  [<ffffffff8109d017>] ? put_prev_entity+0x57/0x350
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273521.993578]  [<ffffffff8109be86>] ? set_next_entity+0x56/0x70
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273522.001013]  [<ffffffff810a2c61>] ? pick_next_task_fair+0x6e1/0x820
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273522.007658]  [<ffffffff810115dc>] ? __switch_to+0x15c/0x570
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273522.014828]  [<ffffffff81515d28>] ? page_fault+0x28/0x30
Mar  3 02:15:50 e2e-test-beeps-minion-8k43 kernel: [273522.020784] Task in /faac96160031ed54697a37bc3dd05f129e259406c79fd77b401fcd7c2c57ff11 killed as a result of limit of /faac96160031ed54697a37bc3dd05f129e259406c79fd77b401fcd7c2c57ff11
```
I believe this corresponds to the kubelet logs:
```
I0303 03:26:38.139296    2478 volumes.go:316] Used volume plugin "kubernetes.io/secret" to unmount fac30ffa-e0ee-11e5-ba95-42010af00002/kubernetes.io~secret
I0303 03:26:38.276759    2478 handler.go:320] Added event &{/faac96160031ed54697a37bc3dd05f129e259406c79fd77b401fcd7c2c57ff11 2016-03-03 03:25:14 +0000 UTC oom {<nil>}}
I0303 03:26:38.276836    2478 manager.go:1020] Created an OOM event in container "/faac96160031ed54697a37bc3dd05f129e259406c79fd77b401fcd7c2c57ff11" at 2016-03-03 03:25:14 +0000 UTC
```

But faac96160031ed54697a37bc3dd05f129e259406c79fd77b401fcd7c2c57ff11 has OOMKilled:false, presumably because the oom killer in the container did the killing but we don't allow oom-kill-disable fiddling (right?). 

As a side note I'm seeing docker kill on:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  nodeName: e2e-test-beeps-minion-g77n
  containers:
  - image: bprashanth/nginx-test:1.0
    command:
      - sh
      - -c
      - "while true; do stress --vm 4 --timeout 100 --vm-bytes 500M; done"
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      hostPort: 80
    resources:
      limits:
        memory: 50Mi
      requests:
        memory: 50Mi
    name: nginx
  restartPolicy: Always
```
getting reported as OOM, no idea what's going on, probably that docker bug Dawn mentioned.

**Comment by yujuhong** [comment]
> Usually I come back and the containers in crash loop backoff or Error, and -o yaml |grep -i oom shows nothing, so I'm guessing we clobber it?

What does LastTerminationState show? Even if the current state is waiting, the last termination state should still have the relevant information. Of course, if docker never reported that the container was OOMKilled, it wouldn't have shown.

**Comment by bprashanth** [comment]
It oom killed multiple times, then probably restarted for some other reasons and enters "Error" with a random exit code. I can report specifics when it happens again.
