### ISSUE TITLE
rkt runtime apiVerson() returns binVersion?

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#22339]
@yifan-gu I encountered this when fixing another issue, correct me if I made mistake :)

In apiVersion() :  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/rkt/rkt.go#L1064

It seems rkt runtime returns `binVersion` instead of `apiVersion`, is this a bug?

**Comment by yifan-gu** [comment]
@resouer Thanks for catching this, This is added originally in 
https://github.com/kubernetes/kubernetes/pull/19675/files . I think I had some misunderstood of the change. Will push a fix.
