### ISSUE TITLE
kubectl code cleanup: overhaul the resource alias introduced #6573

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#22337]
https://github.com/kubernetes/kubernetes/pull/6573 introduces the alias for resources. As our code base evolves, this code needs overhaul. I've noticed several problems:
1. `aliasToResource` is a global variable, so every `DefaultRESTMapper` has the same alias map. https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta/restmapper.go#L492
   (This hasn't caused any bug yet because the problem is hidden by `SplitResourceArgument`)
2. So far the only alias we have is "all", added in https://github.com/kubernetes/kubernetes/blob/master/pkg/api/install/install.go#L119, which will be translated to `"rc", "svc", "pods", "pvc"`. I think this map needs to be updated. And I'd suggest use another alias, because kubectl also has a flag `--all`, which is confusing.

FWIW, I thought about using our ShortcutExpander to replace the alias code, but it doesn't seem to work because they are in different stages of the cmdline argument processing.

@kargakis @janetkuo

**Comment by kargakis** [comment]
cc: @deads2k

**Comment by deads2k** [comment]
I don't see aliases are related the `RESTMapper`.  Aliases are about mapping one virtual resource to multiple actual resources (probably `map[string][]GroupResource`) and will only work effectively if the code making use of them understands the one to many expansion which is distinct from all the other `RESTMapper` functions.

I think I'd like to see a new interface for the expansion plumbed through where it's used as opposed to piggy-backing on the `RESTMapper`.

**Comment by caesarxuchao** [comment]
Thanks @deads2k. I agree it shouldn't be part of the RESTMapper.

**Comment by bgrant0607** [comment]
Resource aliases are discussed in #18023 and #20293.

**Comment by janetkuo** [comment]
"kubectl run" changed behavior to create deployments by default. A user mentioned in https://github.com/kubernetes/kubernetes/issues/23604#issuecomment-218890376:

> ... deployments do not list in 'kubectl get all', which only added to the confusion.

**Comment by kargakis** [comment]
We should use the discovery client when we start combining resources from different api groups into the same aliases.
