### ISSUE TITLE
Restarting kube proxy doesn't update iptables correctly

### ISSUE THREAD

**Issue by cheyang** [kubernetes/kubernetes#22335]
version 1.1.2

1. Start kube-proxy as 
```
/usr/local/bin/kube-proxy --master=http://abc:8080  --proxy-mode=iptables --masquerade-all=true
```
2. The iptables add
```
iptables -L -t nat|grep MASQUERADE
MASQUERADE  all  --  anywhere             anywhere             /* kubernetes service traffic requiring SNAT */ mark match 0x4d415351
```
I think it's for --masquerade-all=true

3. Stop the kube-proxy, and restart it with `--masquerade-all=false`
```
/usr/local/bin/kube-proxy --master=http://abc:8080  --proxy-mode=iptables --masquerade-all=false
```
4. The expected result is that we don't have "MASQUERADE  all" in iptables

But the real result is that we are still able to see  

```
iptables -L -t nat|grep MASQUERADE
MASQUERADE  all  --  anywhere             anywhere             /* kubernetes service traffic requiring SNAT */ mark match 0x4d415351
```

Is it as design? Or I misunderstand?

**Comment by cheyang** [comment]
I think I need to add --cleanup-iptables, right? And what does --v=1 mean? I didn't see it from http://kubernetes.io/v1.0/docs/admin/kube-proxy.html

```
/usr/local/bin/kube-proxy --master=http://9.123.102.90:8080 --kubeconfig=/var/lib/kube-proxy/kubeconfig --proxy-mode=iptables --masquerade-all=false  --v=1
```

**Comment by thockin** [comment]
I think you're misunderstanding.  External traffic always is SNAT'ed for
now.

**Comment by cheyang** [comment]
But my issue with k8s `1.1.2` is 
-  If I run

```
/usr/local/bin/kube-proxy --master=http://abc:8080  --proxy-mode=iptables --masquerade-all=false
```
I can't see sNAT for all in iptables

```
iptables -L -t nat|grep MASQUERADE
```

- Then If I run 
```
/usr/local/bin/kube-proxy --master=http://abc:8080 --kubeconfig=/var/lib/kube-proxy/kubeconfig --proxy-mode=iptables --masquerade-all=false  --v=1
```
I am able to see sNAT for all in iptables this time
```
iptables -L -t nat|grep MASQUERADE
MASQUERADE  all  --  anywhere             anywhere             /* kubernetes service traffic requiring SNAT */ mark match 0x4d415351
```

- The difference is '--v=1',  I want to know is what '--v=1' affects?

**Comment by thockin** [comment]
We apply the masquerade by a mark.  Grepping for MASQUERADE won't show you the diff.  Try diffing the whole `iptables-save` output.
