### ISSUE TITLE
e2e flake: density and load are failing with too high latency of api calls

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#22340]
Examples:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4970/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4955/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4967/

@gmarek

**Comment by wojtek-t** [comment]
@davidopp 

We started looking into it with @gmarek and it clearly looks like a regreesion (or even few regressions).

Below observations are based on http://perf-dash.k8s.io/

1. looking into "List" "pods" "Density" graph - it seems like a regression around 4915 run
2. looking into "Get" or "Put" or "List" "replicationControllers" "load" graph - it seems like a regression around 4948 run (similarly you can look into "nodes" in "load" graph

Especially the second one seems like a more serious regression because it's when scalability started failing significantly more frequently.

However, we took a look into PRs merged around that time and neither of them seems suspicious so far.

**Comment by gmarek** [comment]
@ixdy @spxtr - are any of you aware of any configuration changes made last weekend?

**Comment by wojtek-t** [comment]
Or to be more clear:
- the first one was Sunday 28th Feb ~noon PST time
- the second one Monday-Tuesday around midnight

**Comment by wojtek-t** [comment]
It's possible that the failures in load test were cause by #22340 which I already reverted.

However, there is still a problem of the first regression, which couldn't be related, because by PR was touching explicitly load test, and the regression is visible in density.

**Comment by wojtek-t** [comment]
Looking into logs of apiserver of one of the failed runs:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/4970/consoleFull

It failed on "POST pods" requests (which was extremely high).

However, looking into its logs, I'm seeing a tens of traces like these:

    I0302 01:55:54.442176       6 trace.go:57] Trace "Create /api/v1/namespaces/e2e-tests-density-zrcqr/pods" (started 2016-03-02 01:55:51.579243536 +0000 UTC):
    [19.404µs] [19.404µs] About to convert to expected version
    [233.493µs] [214.089µs] Conversion done
    [2.859225868s] [2.858992375s] About to store object in database
    [2.862722513s] [3.496645ms] Object stored in database
    [2.862735887s] [13.374µs] Self-link added
    [2.862884095s] [148.208µs] END

[Actually all traces that we have from POST pods are like this].

However, looking into the code in resthandler.go we have:

     386     trace.Step("Conversion done")
     387 
     388     if admit != nil && admit.Handles(admission.Create) {
     389       userInfo, _ := api.UserFrom(ctx)
     390 
     391       err = admit.Admit(admission.NewAttributesRecord(obj, scope.Kind.GroupKind(), namespace, name, scope.Resource.GroupResource(), scope.Subresource, admission.Create, userInfo))
     392       if err != nil {
     393         scope.err(err, res.ResponseWriter, req.Request)
     394         return
     395       }
     396     }
     397 
     398     trace.Step("About to store object in database")

This basically means, that all that we do in this ~2s step is admission.

@liggitt @derekwaynecarr - did we change anything in it recently? What should happen to make admission work for that long? [Note that 90th percentile is very small - ~10ms]

**Comment by gmarek** [comment]
Looking at metrics we embed in results I notices that in load test there was a HUGE (<10x) spike in `kubelet_pod_worker_latency_microseconds` for `sync`:
```
kubelet_pod_worker_latency_microseconds
Bucket                            Component                                                   4935       4936
operation_type=sync, quantile=0.9 e2e-scalability-minion-q0lo#e2e-scalability-minion-yfoy#MIN 9126.00    788548.00  
operation_type=sync, quantile=0.9 e2e-scalability-minion-04j9#e2e-scalability-minion-nlrf#MAX 1001669.00 1003770.00 
```

This is consistent - minimums from 90 percentile from runs before 4935 are around 10k, from 4936 it > 100k. Nothing of substance was merged in 4936, so I expect some environment change. CC @yujuhong @ixdy @spxtr

**Comment by derekwaynecarr** [comment]
@gmaerk @wojtek-t - I am unable to see the logs referenced, but am I understanding correctly that 90% of the time, the call is taking 10ms, but it peaks at ~2s?  My review of the density test appears to show that it creates a single namespace and basically adds variable amounts of pods in that namespace per node.  Nothing in that test screams out to me for why admission is chugging.  

There were recent changes in admission control for limit range and resource quota to fall back to a live lookup cache if the index was empty for a namespace to address other e2e flakes, but it's not clear to me that that alone would be causing this impact.

An example is here:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/limitranger/admission.go#L103

That cache is good for 30s intervals per namespace, so it would be an additional lookup every 30s in the density population...  not sure if that is enough to cause the problem here since the lookup should just return no limit ranges...

**Comment by wojtek-t** [comment]
@derekwaynecarr 

@gmaerk @wojtek-t - I am unable to see the logs referenced, but am I understanding correctly that 90% of the time, the call is taking 10ms, but it peaks at ~2s? My review of the density test appears to show that it creates a single namespace and basically adds variable amounts of pods in that namespace per node. Nothing in that test screams out to me for why admission is chugging.

Everything correct.
The link to test logs are here, although there isn't anything special in them:
https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/4970/build-log.txt

>
There were recent changes in admission control for limit range and resource quota to fall back to a live lookup cache if the index was empty for a namespace to address other e2e flakes, but it's not clear to me that that alone would be causing this impact.

An example is here:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/limitranger/admission.go#L103

Do we create a LimitRange object by default in newly created namespace? If not, then we don't have LimitRange object in that namespace, so it shouldn't cause any problems, right?

>
That cache is good for 30s intervals per namespace, so it would be an additional lookup every 30s in the density population... not sure if that is enough to cause the problem here since the lookup should just return no limit ranges...

Additional lookup of what?

**Comment by derekwaynecarr** [comment]
@wojtek-t - we do not create a limit range by default in a namespace, and I do not think it should cause problems.

**Comment by lavalamp** [comment]
I haven't finished reading, but could RC put increase be caused by something starting to use patch, which does a retry loop in apiserver on a conflict?

**Comment by davidopp** [comment]
@fejta 
@kubernetes/goog-testing

**Comment by lavalamp** [comment]
My reading of the perf dashboard is that 4938 is the first bad run.

**Comment by lavalamp** [comment]
(Looking at pod delete there's a very clear bump there on 50%ile)

**Comment by dchen1107** [comment]
cc/ @Random-Liu who is doing perf validation for docker 1.9.1 release.

**Comment by fejta** [comment]
@ixdy says nothing has changed on the jenkins/infra side.

**Comment by derekwaynecarr** [comment]
how often is this test run?  is it per PR or daily?  when was it last run?

**Comment by lavalamp** [comment]
Actually my hypothesis for pod delete is https://github.com/kubernetes/kubernetes/pull/22156-- if you look at the load test instead of the density test, it ramps up slower.

**Comment by lavalamp** [comment]
That adds back a second write in the delete path, which adds to the number of updates RCs have to process, which could cause more status writes and hence more conflicts.

Hm, but that means we should have seen unexplained an improvement when the change that #22156 rolled back went in?

**Comment by wojtek-t** [comment]
>
My reading of the perf dashboard is that 4938 is the first bad run.

@lavalamp 
There are some issues with numbers - there may be few numbers off, if there are runs where cluster didn't started correctly. So it probably is not exactly 4938, but something around.

>
how often is this test run? is it per PR or daily? when was it last run?

@derekwaynecarr 
We are running these tests in a loop - so generally every ~hour

>
Actually my hypothesis for pod delete is #22156 if you look at the load test instead of the density test, it ramps up slower.

This may explain higher latency of delete pods - but this should have nothing to do with POST pods IIUC. Or things like LIST replicationcontrollers. which are also higher.

>
@ixdy says nothing has changed on the jenkins/infra side.

@fejta - thanks for confirmation!
Although that's a bad information :(

**Comment by wojtek-t** [comment]
BTW - note that #22349 helped with load test, but didn't fix the problem completely.

**Comment by jlowdermilk** [comment]
Currently causing roughly 1 in 5 runs of kubernetes-e2e-gce-scalability to fail. Recent hits:
[kubernetes-e2e-gce-scalability/4995](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/4995)
[kubernetes-e2e-gce-scalability/4988](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/4988)
[kubernetes-e2e-gce-scalability/4984](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/4984)

**Comment by wojtek-t** [comment]
OK - I just debugged one of the issues here.

The problem with POST pods (which seems to be the most important problem for now) is again the problem with client throttling - @davidopp @lavalamp - FYI :) [again, 5th time during last 2 weeks or so]
Looking into logs from apiserver we have:

    W0302 21:38:27.990221       5 request.go:627] Throttling request took 1.08136749s, request: GET:http://127.0.0.1:8080/api/v1/namespaces/e2e-tests-load-6cqci/limitranges
    I0302 21:38:27.993185       5 trace.go:57] Trace "Create /api/v1/namespaces/e2e-tests-load-   6cqci/pods" (started 2016-03-02 21:38:26.908569973 +0000 UTC):
    [21.125Âµs] [21.125Âµs] About to convert to expected version
    [213.617Âµs] [192.492Âµs] Conversion done
    [1.082970115s] [1.082756498s] About to store object in database
    [1.084403983s] [1.433868ms] Object stored in database
    [1.084416414s] [12.431Âµs] Self-link added
    [1.084563409s] [146.995Âµs] END

...

    W0302 21:38:28.190204       5 request.go:627] Throttling request took 1.281100127s, request: GET:http://127.0.0.1:8080/api/v1/namespaces/e2e-tests-load-6cqci/limitranges
I0302 21:38:28.191235       5 handlers.go:152] GET /api/v1/namespaces/e2e-tests-load-6cqci/limitranges: (853.53Âµs) 200 [[kube-apiserver/v1.2.0 (linux/amd64) kubernetes/2cf9157] 127.0.0.1:58515]
    I0302 21:38:28.193396       5 trace.go:57] Trace "Create /api/v1/namespaces/e2e-tests-load-6cqci/pods" (started 2016-03-02 21:38:26.908795629 +0000 UTC):
    [20.412Âµs] [20.412Âµs] About to convert to expected version
    [239.558Âµs] [219.146Âµs] Conversion done
    [1.282815499s] [1.282575941s] About to store object in database
    [1.284377959s] [1.56246ms] Object stored in database
    [1.284389884s] [11.925Âµs] Self-link added
    [1.284548334s] [158.45Âµs] END

and so on.

The solution for it is to increase QPS limit for admission controller client. I will send out a PR for it soon.

**Comment by wojtek-t** [comment]
I've opened #22422 for a proper fix, but temporarily I'm going to just increase QPS limit for admission controller clients. But we should solve it properly for 1.3 (it probably is not a blocker for 1.2)

**Comment by wojtek-t** [comment]
#22423 should stop the bleeding in POST pods operations (and potentially other failures too)

**Comment by wojtek-t** [comment]
I'm decreasing priority after merging #22423 - please increase it again if you see those failures again.

**Comment by derekwaynecarr** [comment]
@wojtek-t - the LRU cache pattern was introduced in `LimitRange` and `ResourceQuota` to address other flakes where indexes were slow to populate.  If they continue to cause problems, we can look to provide alternate solutions to those flakes or do the lock on `List` semantic you described if an index is empty.

**Comment by wojtek-t** [comment]
@derekwaynecarr - I hope my workaround is good enough for 1.2. But we should provide some locking (or potentially some other solution) for 1.3 to solve it properly.

**Comment by lavalamp** [comment]
Awesome. Super glad we (you) added those messages!

On Thu, Mar 3, 2016 at 7:29 AM, Wojciech Tyczynski <notifications@github.com

**Comment by wojtek-t** [comment]
Scalability suite didn't failed in last 30 runs (since I merged the fix). I'm closing this issue. We should reopen it if that happens again, but I think it is now fixed.
