### ISSUE TITLE
Detect version mismatches between nfs client and nfs server

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#22354]
We should look into checking the client and server NFS versions and validate the combination to provide debugging info when diagnosing issues with NFS mounts.  I don't know of a 100% portable way to do this, but generally rpcinfo can be used to get information about which versions a server supports and nfsstat can be used to get version information about the client.

@thockin @jmccormick2001 @kubernetes/rh-storage

**Comment by rootfs** [comment]
[mount.nfs](http://linux.die.net/man/8/mount.nfs) is able to try v4 first, and fall thru to v3 if server doesn't support v4. That sort of serves the purpose.

`rpcinfo` results aren't really reliable: the NFS program and port can be registered but there is no guarantee the ports are served by NFS RPC daemons.

**Comment by jsafrane** [comment]
Closing for now, I don't remember any user complaining about NFS versions. Reopen if you find some.
