### ISSUE TITLE
Updating gophercloud dep to last version

### ISSUE THREAD

**Issue by AlbertoPeon** [kubernetes/kubernetes#22365]
We'd like to update the last gophercloud into kubernetes as it provides interesting bugfixes. I tried to do a merge request myself by following: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#godep-and-dependency-management
but following the recipe didn't provide the expected results. 

Could anyone update to the latest gophercloud?

/cc @spothanis as you did the last gophercloud update #14364, could you provide some help?

**Comment by spothanis** [comment]
Back when I was did it, the thing that didn't work was https://github.com/kubernetes/kubernetes/issues/10195. I followed the worked around described in the issue. Not sure what is happening now.

**Comment by AlbertoPeon** [comment]
Closing this as https://github.com/kubernetes/kubernetes/pull/23131 has been merged
