### ISSUE TITLE
Deployment controller should handle errors better when retrying updates

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#22388]
For example, ignore pods not found error when trying to label it. https://github.com/kubernetes/kubernetes/issues/22300#issuecomment-191413641

We should also avoid retrying when the error is perm-failed (retry won't help), and emit events. We should also have pre-condition for retrying updates. 

@kubernetes/sig-config

**Comment by bgrant0607** [comment]
NotFound at least needs to be handled in 1.2.

**Comment by janetkuo** [comment]
We've handled NotFound in #22384 and preconditions in #22392.

**Comment by bgrant0607** [comment]
Done enough for 1.2.

**Comment by kargakis** [comment]
cc: @mfojtik

**Comment by kargakis** [comment]
Shouldn't be an issue anymore
