### ISSUE TITLE
Expose controller manager and scheduler metrics

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/kubernetes#22382]
Right now when you provision a new k8s cluster the `controller manager` and `scheduler` are bound to the loopback interface which makes it difficult to fetch their metrics. In this particular case I would love to know how long it is taking for pods to be scheduled on the cluster and be able to graph that over time.

**Comment by quinton-hoole** [comment]
cc @gmarek @wojtek-t 
@jchauncey You should be able to do that today by watching pod creation and state changes.  e.g. see https://github.com/kubernetes/kubernetes/blob/master/test/e2e/density.go#L379

I'm not sure whether we yet have any concrete plans to expose that data in a more generic way.

**Comment by gmarek** [comment]
In some setups (like GCE) master is self-registered and both scheduler and controller-manager runs as pods. You can then use master-proxy to get to theirs /metrics endpoints.
