### ISSUE TITLE
Improvements to API Documentation

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#22389]
Here are some suggestions for improving our API documentation.

By API documentation, I mean:
- _Operations_: http://kubernetes.io/v1.1/docs/api-reference/v1/operations.html
- _Definitions_: http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html
- and so on for [other api groups](http://kubernetes.io/v1.1/docs/api-reference/extensions/v1beta1/operations.html) and newer versions (like 1.2)
#### CSS Changes
1.  Don't have the k8s.io nav sidebar when viewing docs.  The docs need their own nav sidebar, since docs are so long.  
2. Don't have the k8s.io top nav bar when viewing docs.  If the person has found the API docs, they probably already are comfortable navigating other K8s.io documentation and don't need the top nav bar.
3. Reduce padding in tables, and reduce font sizes so more text fits on the screen.
4. In the parameters table, give the "Description" column more width. 
#### Generated Formatting Changes
1. Remove the Tags field, as it does not have any meaning to users.
2. Remove the "Type" Column and instead have separate headings for "Query Parameters", "Body" and "Path Parameters"
3. Omit "Consumes: /" sections.  This is implied by there being no BodyParameter.
4. Group together all methods that have the same group/version/kind.  Currently, proxy Node and watch Node and create node and get node are scattered throughout a file.
5.  There is only ever one BodyParameter, AFAICS.  So, instead of having the BodyParameter link to "Descriptions", consider inlining the description at the start of the section for that Kind.
#### Client Library Changes
1. Have client libraries for multiple languages.  Swagger can generate these.
2. Have examples for each method for multiple languages, and show next to the method documentation.  For example, look at https://stripe.com/docs/api/python#retrieve_balance.  I'm not sure how to autogenerate these, but it seems possible.

**Comment by erictune** [comment]
@lavalamp @bgrant0607 since we talked about this

@johndmulhausen the section "CSS Changes" is stuff that may be most immediately actionable for you.

@nikhiljindal since you last touched swagger generation I think.

**Comment by nikhiljindal** [comment]
Related https://github.com/kubernetes/kubernetes/issues/19680

cc @caesarxuchao

**Comment by bgrant0607** [comment]
Filed a separate issue for client libraries: #22405

**Comment by bgrant0607** [comment]
Still lots of room for improvement, but doesn't belong here
