### ISSUE TITLE
kubectl run --replicas=N doesn't work

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#22399]
I tried to do some stress test against my cluster by running cmd: ./cluster/kubectl.sh run hostnames --image=kubernetes/serve_hostname --replicas=200 --port=9376 --labels=app=hostnames 

It failed immediately with error:

```
Error from server: deployments.extensions "hostnames" already exists
```

kubectl get pods shows I only have one pod, not 200 replicas:

```
$ cluster/kubectl.sh get pods --all-namespaces
NAMESPACE     NAME                                                  READY     STATUS    RESTARTS   AGE
default       hostnames-1963821055-xdksp                            1/1       Running   0          6m
default       nginx                                                 1/1       Running   0          23h
kube-system   elasticsearch-logging-v1-9k90q                        1/1       Running   1          1d
kube-system   elasticsearch-logging-v1-j08ky                        1/1       Running   0          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-fo98   1/1       Running   2          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-rg3g   1/1       Running   0          1d
kube-system   fluentd-elasticsearch-e2e-test-dawnchen-minion-tikv   1/1       Running   0          1d
kube-system   heapster-v14-cfenb                                    2/2       Running   4          1d
kube-system   kibana-logging-v1-xz7hy                               1/1       Running   2          1d
kube-system   kube-dns-v10-qrv2j                                    4/4       Running   0          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-fo98              1/1       Running   1          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-rg3g              1/1       Running   0          1d
kube-system   kube-proxy-e2e-test-dawnchen-minion-tikv              1/1       Running   0          1d
kube-system   kubernetes-dashboard-v0.1.0-9rabh                     1/1       Running   0          1d
kube-system   l7-lb-controller-v0.5.2-1k4co                         2/2       Running   0          1d
kube-system   monitoring-influxdb-grafana-v3-op3cp                  2/2       Running   0          1d
```

Also kubectl get replicaset shows I only asked for one copy:

```
$ cluster/kubectl.sh get replicaset
NAME                   DESIRED   CURRENT   AGE
hostnames-1963821055   1         1         34m
```

This is definitely a regression with 1.2 release. @lavalamp I am assigning this to you for triage.

**Comment by lavalamp** [comment]
I think this is caused by the scale work that hasn't been done, which @madhusudancs is implementing right now, but I'll verify

**Comment by bgrant0607** [comment]
It should have nothing to do with scale. The Deployment is created with the desired number of replicas:
```
	deployment := extensions.Deployment{
		ObjectMeta: api.ObjectMeta{
			Name:   name,
			Labels: labels,
		},
		Spec: extensions.DeploymentSpec{
			Replicas: count,
			Selector: &unversioned.LabelSelector{MatchLabels: labels},
			Template: api.PodTemplateSpec{
				ObjectMeta: api.ObjectMeta{
					Labels: labels,
				},
				Spec: *podSpec,
			},
		},
	}
```

@dchen1107 The error implies that a Deployment of that name already existed. Is that possible?

cc @janetkuo @nikhiljindal @kargakis

**Comment by janetkuo** [comment]
FWIW it didn't fail on my machine. Maybe there's already a existing "hostnames" deployment with 1 replica?

**Comment by lavalamp** [comment]
Oh, the error even says "deployments" in it. ...I must be tired.

**Comment by bprashanth** [comment]
I've run into this before. It's weird because scale has trained us to do:
kubectl scale --replicas=5
Ctrl^R, backspace, --replicas=1

So why not just apply the scale to the existing deployment if everything else checks-out?

**Comment by bprashanth** [comment]
I'm guessing Dawn just did the crtl^r bit and replaced --replicas in:
./cluster/kubectl.sh run hostnames --image=kubernetes/serve_hostname --replicas=200 --port=9376 --labels=app=hostnames

**Comment by dchen1107** [comment]
Here is the output of get deployments:

```
$ cluster/kubectl.sh get deployments
NAME        DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
hostnames   1         1         1            1           17h
```

**Comment by dchen1107** [comment]
@bprashanth I did apply the scale to the existing deployment, but failed too. I couldn't find the initial failure reason now. But even the previous one failed, but it still create deployment object. Close the issue.
