### ISSUE TITLE
NFS Example is misleading

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#22407]
We had a customer get confused by the NFS example: https://github.com/kubernetes/kubernetes/tree/master/examples/nfs 

They did not realize that the NFS Server setup by https://github.com/kubernetes/kubernetes/blob/master/examples/nfs/nfs-server-rc.yaml and https://github.com/kubernetes/kubernetes/blob/master/examples/nfs/nfs-server-service.yaml was not backed by a persistent store and should not be relied on for real world usage.

We should update the example to make this explicitly clear, and, if possible, offer a more robust implementation of an NFS server running on k8s.

CC @kubernetes/examples @kubernetes/sig-storage

**Comment by thockin** [comment]
This is a great use for the new auto-provisioning, for those platforms that
support it.

**Comment by rootfs** [comment]
The example README needs to be augmented to reflect the case that we don't have an NFS auto provisioner yet. The NFS shares have to be manually created and PVs have to match them. @saad-ali @thockin is it a good plan for short term fix?

A better NFS implementation on k8s probably has to wait for the arrival of NFS auto provisioner. Once we settle on the framework on provisioning non-Cloud storage, I am happy to get it done.

**Comment by thockin** [comment]
Sorry, I mean that the NFS example could use auto-provisioning of a backing
store (PD or EBS) to provide a more robust NFS server.  Yes, provisioning
of NFS has to wait for the general provisioning scaffolding.

**Comment by rootfs** [comment]
That's a cool idea!

**Comment by saad-ali** [comment]
Bare minimum we should add a comment saying the NFS server created by this example is not backed by persistent storage (it is a toy example).

Better, as @thockin suggested, would be to modify the example to back the NFS server with a GCE PD.

**Comment by rootfs** [comment]
I'll get access to GCE and create an example as @thockin suggested.

**Comment by rootfs** [comment]
There is an issue with NFS image used in the example (#22529). Will use a new NFS image first.

**Comment by bgrant0607** [comment]
cc @jeffmendoza @amygdala 

New example guidelines:
https://github.com/kubernetes/kubernetes/blob/master/examples/guidelines.md

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by bgrant0607** [comment]
+1 to auto-provisioning

**Comment by ixdy** [comment]
Related: #22658
