### ISSUE TITLE
Jenkins AWS e2e: SSH username for jessie is admin

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22403]
The SSH username to get onto our jessie based images is 'admin'.  So we need to change KUBE_SSH_USER from ubuntu -> admin.

This should allow the SSH test to succeed.  (Without it, it will definitely fail anyway)

**Comment by justinsb** [comment]
(This is a piece of #18037)

**Comment by fejta** [comment]
@justinsb I believe this is controlled by https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e.yaml#L427 

Will you send @spxtr a PR with this change?

**Comment by fejta** [comment]
@spxtr @justinsb what's left on this?

**Comment by spxtr** [comment]
I think this is done. The SSH tests are passing on AWS.
