### ISSUE TITLE
AWS: Docker debian repo was down

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22417]
Salt failed to download the docker deb file which we're using on AWS.

We should figure out a way to retry the download or similar.  Maybe another helper script.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5

**Comment by calebamiles** [comment]
@justinsb how would you feel about moving this out of the 1.5 milestone? This issue sounds like an improvement that wouldn't land in 1.5 unless the work is already complete.


**cc: @saad-ali, @dims**

**Comment by justinsb** [comment]
With kube-up in maintenance mode, going to close.  Replacements (e.g. kops) already have open issues tracking the need to run without dependencies.
