### ISSUE TITLE
Confusing results from discovery client confuses namespace deletion

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#22413]
If I do the following:

```
$ curl http://127.0.0.1:8080/apis/extensions/v1beta1/
...
    {
      "name": "replicationcontrollers",
      "namespaced": true,
      "kind": "ReplicationControllerDummy"
    },
    {
      "name": "replicationcontrollers/scale",
      "namespaced": true,
      "kind": "Scale"
    }
...
```

Looking at the configuration in master.go I find this confusing:
https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L681

If you follow it to its implementation, we are registering an object into storage that does nothing but implement `New()` but supports no verbs.  Swagger does the correct thing and only returns support for `replicationcontrollers/status` but as a user of the discovery client, it's confusing that we return the parent resource that supports no verbs...

https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/experimental/controller/etcd/etcd.go#L42

This makes no sense to me right now, but it causes unexpected behavior.  

If I do the following:

```
$ curl http://127.0.0.1:8080/apis/extensions/v1beta1/namespaces/default/replicationcontrollers
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}
```

I would have expected a 405 if I work against the discovery client rather than consulting swagger.  This is the ONLY resource in the API that supports no top-level HTTP verb.

Is there any reason why we are registering in storage an object that only implements `New`, but we are returning that object in the discovery results?  Should the discovery result just return "replicationcontrollers/scale".

I am trying to find the best way to work around this in namespace clean-up and while I could choose to ignore not found, it seemed odd and want to raise the issue now.

@lavalamp @caesarxuchao @DirectXMan12

**Comment by ncdc** [comment]
cc @deads2k @smarterclayton

**Comment by ncdc** [comment]
cc @piosz @mwielgus

**Comment by deads2k** [comment]
The dummy extensions resource is broken and we've reached agreement that we should move the scale subresource to the legacy kube group.  @madhusudancs 

Of course, that raises the next problem of needing to indicate that a given resource accepts a kind from a different group/version. :)

**Comment by lavalamp** [comment]
This was added because we didn't have cross-group registration. @madhusudancs is implementing that. Unfortunately it would break old clients if we removed this now. But we won't do this again ever in the future. Maybe we can remove in 1.3, but probably we have to live with it until 1.4.
