### ISSUE TITLE
Add metric for client rate limiter saturation (for all clients)

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#22421]
As we found out recent regression was caused by hitting rate limit in one of components (#22340). It's not the first time it hits us, so we really need to make sure it will be easier to debug in future. To do this we can add a per-client prometheus metric exposing rate limiter saturation level. cc @smarterclayton @lavalamp @wojtek-t @fgrzadkowski @davidopp 

I see two options. Either make client rate limiter injectable, and let the client owner handle exposing and updating the metrics, or let the client itself do all of this (i.e. register metric and have a go-routine that periodically updates it). I'm leaning towards the first option.

**Comment by wojtek-t** [comment]
@kubernetes/sig-scalability

**Comment by smarterclayton** [comment]
I am very strongly in favor of making rate limiter injectable.

**Comment by lavalamp** [comment]
The things I care about are:
* each registered metric has a name that makes it easy to identify the rate
limiter
* hard to accidentally make a rate limiter without also registering the
metric

**Comment by gmarek** [comment]
@lavalamp - this is why I even thought of the second option. Client has a name, so it's pretty easy to get a name, and it's also quite easy to get the metric registered (I believe). The problem is that we'll need to require some non-obvious arguments during client creation (http server?), so maybe we should have two versions: 'internal' and 'external' client. @bgrant0607 

I can make rate limiter injectable however we want to proceed.

**Comment by bgrant0607** [comment]
Do we even have an external client yet, or just versioned and unversioned?

**Comment by wojtek-t** [comment]
@bgrant0607 - the latter

**Comment by smarterclayton** [comment]
One point to be careful of - unbounded metrics growth if someone
creates new client names dynamically or adds metrics with high
cardinality.  Has bit us before.

**Comment by lavalamp** [comment]
I do not see what internal/external has to do with this?

**Comment by gmarek** [comment]
I don't think we want to register prometheus metric for client saturation for clients that external users are using to communicate with API server. I'm not sure that we want to do this for e2e tests as well. At some level we need to inject (or not) HTTP server, which will distinguish 'internal' from 'external' IMO.

**Comment by spiffxp** [comment]
I would very much be in favor of e2e test clients having these metrics, but not so much arbitrary clients

**Comment by lavalamp** [comment]
I guess I would expect our client (or rate limiter) to have a function
which returns something in the format that prometheus wants, so that you
can import our client without importing prometheus. Then if you want it
registered, it should be a one-liner after you create the client. The
client should *not* need the actual http server injected.

**Comment by gmarek** [comment]
OK, so action items:
1) make rate limiter injectable
2) make client return it's "prometheus metric name"
3) write a helper function(s) that takes both: rate limiter and name, and both registers the metric and starts a goroutine that monitors the client.

**Comment by timothysc** [comment]
I would prefer backoff tracking, which we had proposed an earlier patch on.

/cc @jayunit100

**Comment by gmarek** [comment]
@timothysc - can you point me to that?

**Comment by lavalamp** [comment]
@gmarek I don't think you need to do 2. e.g. I expect to see something like this at the places where clients are created:

```go
func doFancyThing() {
  c := constructNewClient()
  metrics.Register("my fancy client", c.GetRateLimiter())
  ...
}
```

@timothysc I think backoff recording is a separate issue completely-- let's fix them one at a time.

**Comment by gmarek** [comment]
This is done for controllers and framework is there for anyone to use.
