### ISSUE TITLE
parsers.go uses removed docker parsers.ParseRepositoryTag(image)

### ISSUE THREAD

**Issue by Goblain** [kubernetes/kubernetes#22427]
Hoped to built a simple ingress controller based on Go examples in kubernetes/contrib. I'm facing an issue though: When I do `go get k8s.io/kubernetes/pkg/client/unversioned` the result is 
```
# k8s.io/kubernetes/pkg/util/parsers
k8s.io/kubernetes/pkg/util/parsers/parsers.go:30: undefined: parsers.ParseRepositoryTag
```
I tried to trace it and it led me to https://github.com/kubernetes/kubernetes/blob/master/pkg/util/parsers/parsers.go and with parsers.ParseRepositoryTag to https://github.com/docker/docker/commit/4352da7803d182a6013a5238ce20a7c749db979a which seems to remove it from docker

**Comment by Goblain** [comment]
seems that current implementation used in docker moved to `github.com/docker/distribution/reference`

**Comment by AdoHe** [comment]
@Goblain you must use a higher version docker, IIRC this is not moved in docker 1.9.1

**Comment by Goblain** [comment]
well, it seems that `godep` was the thing I was missing from the picture

**Comment by harryge00** [comment]
How to use godep to fix this?

**Comment by therealplato** [comment]
I am seeing this issue while trying to use `govendor` to add kubernetes to my vendor folder.

Are there specific git hashes I can vendor to have kubernetes 1.2 alongside docker?

Duplicate https://github.com/kubernetes/kubernetes/issues/18774
