### ISSUE TITLE
docker logs ID

### ISSUE THREAD

**Issue by t5unamie** [kubernetes/kubernetes#22428]
There is a situation right now where by you can't list off stopped containers/POD's.

The reson this is important is because the function "docker ps -a" and "docker log ID" allowed you to troubleshoot.

If you want people to love Kub's it must be easy to troubleshoot containers that won't start. As allowing people to troubleshooting a container in a vast cluster will allow them to not have to find the physical node it tried to start on and run from there.

**Comment by AdoHe** [comment]
@t5unamie IIUC you want to be able to list stopped containers/POD's, I think `kubectl get pods --show-all=true` can give you all pods info(include terminated pods). Besides pod is the smallest deployable unit of kubernetes.

**Comment by t5unamie** [comment]
Hi Adohe,

I cam across a situation as follows. I started a Jenkins slave through the Jenkins plugin "Kubernetese plugin". this starts a slave using an online image to run as a slave temporarily. However, when the container failed, the POD did not show up at all in the output of "kubectl get pods".

Also, when running "kubectl logs PODID" on POD's which have failed containers and not starting correctly. The output is empty. I have to log onto the target server where the POD failed to start the container and then run a docker log CONTAINERID to show me logs that I can use to debug the issue.

Thats a detailed decription of the core issue with "kubectl logs" and "kubectl get pods" there are some situations where the current setup does not work. I ahve seen "kubeclt get pods show me when containers don't get started correctly as a 0/1 output. However even in that situation I can't see the logs of the dead container unless I do the above.

Regards

John

**Comment by dchen1107** [comment]
@t5unamie  kubectl get pods --show-all=true should give the terminated pods. For a given pod and container, kubectl logs --previous show you logs of previous failed container.

**Comment by t5unamie** [comment]
thanks got it - sorry about that

**Comment by dchen1107** [comment]
@t5unamie Thanks for using Kubernetes!
