### ISSUE TITLE
Document that using autoscaling/v1/HPA might return unexpected results until 1.3

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#22449]
Ref https://github.com/kubernetes/kubernetes/issues/22431#issuecomment-191876983

**Comment by davidopp** [comment]
ping - we're getting close to the end for 1.2

**Comment by piosz** [comment]
Sorry for the delay. I'll take a look tomorrow.

**Comment by fgrzadkowski** [comment]
Ping. Please add it to the release notes and/or user guide.

**Comment by piosz** [comment]
Added to the release notes.
