### ISSUE TITLE
End-to-end tests rely on SSH key path

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#22452]
I am not entirely sure why the test suite needs to SSH into node in the first place, but it definitely should not hardcode SSH key path and use keychain instead.

This is an error I'm seeing while running the suite agains my cluster which is being deployed in a non-upstream fashion.

```
Mar  3 17:52:10.747: INFO: error while SSH-ing to node: error getting signer for provider aws: 'error reading SSH key /root/.ssh/kube_aws_rsa: 'open /root/.ssh/kube_aws_rsa: no such file or directory'' (code 0)
```

**Comment by errordeveloper** [comment]
Having looked at `pkg/util/ssh.go`, I found that `Auth: []ssh.AuthMethod{ssh.PublicKeys(signer)}` is used, and using agent would require a bit more code, but there is [`golang.org/x/crypto/ssh/agent`](https://godoc.org/golang.org/x/crypto/ssh/agent) package for it.

**Comment by fejta** [comment]
FYI, if you want to run e2e tests, please follow [the docs](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/testing.md) to deploy your cluster in a canonical fashion.

@ixdy how to define ssh creds is something to consider when working on canonical test running.

**Comment by errordeveloper** [comment]
Why does it have to be the case? I think tests should be agnostic of how
the cluster had been provisioned, and thereby provide a way of measuring
the compliance of any deployment.

**Comment by errordeveloper** [comment]
Otherwise, I don't see a point of having a test suite.

**Comment by ixdy** [comment]
@errordeveloper the e2e test infra will look for a key in the file pointed to by the environment variable `AWS_SSH_KEY`, which seems to be pretty standard.

We use `ssh` in a few tests where we must muck with things outside the cluster (e.g. killing daemons).

**Comment by errordeveloper** [comment]
Ok, is there a way to disable test that rely on SSH? And, the environment
variable is good, but I would rather use the key forwarded by the agent.

**Comment by errordeveloper** [comment]
@mikedanese were you saying this is no longer the case, or is it something that we are getting close to solving?

**Comment by mikedanese** [comment]
https://github.com/kubernetes/kubernetes/commit/2d6c2eb8976db71f5fe8a2afc1dc365efd8fdd39 should replace majority use cases for ssh. Not sure how plumbed it is though.

**Comment by pskrzyns** [comment]
@mikedanese ssh will be still needed with hypervisor based containers - price for isolation ;/

**Comment by mikedanese** [comment]
I think we use kubectl exec now instead of ssh everywhere
