### ISSUE TITLE
Kubernetes Network Policy

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#22469]
Raising this issue to track the status of network policy in Kubernetes so it isn't hidden within the network SIG.

Current rough plan:
- [x] Short-term: Define v1alpha1 network policy using API extensions.
- [x] Medium-term [v1.3]: Implement as Kubernetes v1beta API object. (#25638)
- [x] Medium-term: Refine and add to API based on user-feedback.
- [x] Long-term: Implement as first-class API in k8s.

v1beta API is outlined here: https://github.com/kubernetes/kubernetes/pull/24154/files

and here: https://docs.google.com/document/d/1qAm-_oSap-f1d6a-xRTj6xaH1sYQBfK36VyjB5XOZug/edit

Some future considerations and discussion points:
- [x] Egress (outgoing) network policy
- [x] External policy (from outside the cluster)
- [ ] How does policy fit in to multi-tenancy model? 
- [ ] Further policing cross-namespace connectivity (e.g allow from these labels in these namespaces).

**Comment by tomdee** [comment]
CC @philips

**Comment by caseydavenport** [comment]
I don't know everyone's GitHub names, so please do summon those that I haven't included!

@thockin @dcbw @jainvipin @lxpollitt @MikeSpreitzer

**Comment by AdoHe** [comment]
@kubernetes/sig-network

**Comment by errordeveloper** [comment]
cc @monadic @rade @sqaremo @bboreham

**Comment by caseydavenport** [comment]
I think there is a problem with the current spec and NodePort services.

The current spec allows traffic from a pod's host by default to allow for kubelet health checks.  This opens a window where a pod might be in an isolated namespace but can still be accessed if selected by a NodePort service, and traffic is directed at <pods_host>:<nodeport>, thus circumventing the policy in place.

**Comment by MikeSpreitzer** [comment]
Casey:
(1) I suspect you used angle bracket quotes and github mistook them for HTML markup, in your last sentence where you say "traffic is directed at :".
(2) I think the intent is that a Network Policy is about the relationship between the "origin client" and the "origin server" and if there is a (kube or other) proxy in between then that proxy has to play its part in implementing the policy.  Or perhaps I do not understand the problem to which you are referring.

**Comment by MikeSpreitzer** [comment]
(I posted these on the SIG mailing list recently, but since this now seems to be the right forum, I am repeating them here.)

I drafted example network policies, for the k8s guestbook example.  Find them in https://review.openstack.org/#/c/290172/ .

While doing that I realized I did not know how to express the white-listing of connections to a given TCP port on a given pod from any client on the open Internet.  So I supposed an extension in which a CIDR block can be used to identify the remote peer, and used 0.0.0.0/0 to allow from anybody.  Which makes me a bit unhappy, because I know some operators that want to *disallow* connections from *some* parts of their platform to the workload containers.  So I am thinking of a further extension that allows the use of a difference of CIDR blocks.

**Comment by danwinship** [comment]
> This opens a window where a pod might be in an isolated namespace but can still be accessed if selected by a NodePort service

FWIW, in OpenShift, isolation only applies to pod and service IP addresses; making your pod available on a node IP address (via NodePort, ExternalIP, HostPort, etc) explicitly bypasses isolation.

**Comment by caseydavenport** [comment]
@MikeSpreitzer Thanks, fixed up my comment.  It might be good enough to say that if you're using some sort of proxy (in this case NodePort) then you need to make sure it works with your policy.  I guess my thought was that 1) we should document which of the standard k8s proxies are compatible and 2) it would be nice if the proxies that ship with k8s are compatible with policy.

If you take a look at the google doc linked in this issue, at the very bottom there is an example for allowing all traffic sources access to a specific protocol / port.  It basically looks like this:

```
ingress:
    ports:
      - protocol: TCP
        port: 80
```

**Comment by MikeSpreitzer** [comment]
@caseydavenport: thanks for the reference, I missed the example with no "from".  I will have to update my impl outline, I had assumed that no "from" is the same as an empty "from".
I am not sure I would consider node port to be a "proxy".  It seems more of an "alias" to me.  I think the design intent is that an alias does not introduce an exception to the policy.

**Comment by MikeSpreitzer** [comment]
I assume that a NodePort service is implementing using Docker port mapping --- and Docker has two available implementations of that: a userspace proxy and iptables hacking (deja vu all over again).  The design intent is that a network policy is about the relationship between origin client and origin server regardless of whatever proxying and/or aliasing the platform puts in between them.  So an implementation that works with Docker's userspace port mapping of NodePort services has to get in iptables bed with Docker :-(

**Comment by bprashanth** [comment]
> I assume that a NodePort service is implementing using Docker port mapping

kube-proxy opens the node port on every node in the cluster and sends traffic to the endpoint ips. 
HostPort is still docker.

**Comment by caseydavenport** [comment]
v1beta1 API has been merged to master as of #25638

**Comment by HuKeping** [comment]
Hi, team:

I see the docs about the network-policy says that 
```
type NetworkPolicyPeer struct {
        // Exactly one of the following must be specified.

        // This is a label selector which selects Pods in this namespace.
        // This field follows standard unversioned.LabelSelector semantics.
        // If not provided, this selector selects no pods.
        // If present but empty, this selector selects all pods in this namespace.
        PodSelector *unversioned.LabelSelector `json:"podSelector,omitempty"`
...
        NamespaceSelector *unversioned.LabelSelector `json:"namespaceSelector,omitempty"`
}
```

I'm a little confused about the `If present but empty, this selector selects all pods in this namespace`,
what does the `this namespace` mean? For example:
```
podSelector:
 - tier: database
ingress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 50
      protocol: UDP
    from:
      - pods:
      - namespaces:
          blah: bar
```
Does it mean the namespace with label `blah:bar` or the namespace the same as the selected pod which with label `tier:database`?

Thanks.

**Comment by caseydavenport** [comment]
@HuKeping - "this namespace" refers to the namespace that is the parent of the NetworkPolicy.

So, if you create a NetworkPolicy in namespace "foo", `podSelector` can only match pods in namespace "foo".

**Comment by HuKeping** [comment]
Get it , thanks @caseydavenport

**Comment by shouhong** [comment]
I tried K8S 1.3 Network Policy + Calico implementation. Once I set network isolation for a namespace, the pods in this namespace can only be accessed by the local K8S node. Then I can create Network Policies to make some pods in the namespace can be accessed by some other pods. All of these are fine.

Now the question is: is it possible to make some pods in the namespace can be accessed from other K8S nodes or even from the nodes outside of the K8S cluster?  Thanks!

**Comment by MikeSpreitzer** [comment]
@shouhong: Example 3 of https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/network-policy.md --- which originally had a bug but is now fixed --- shows one way to write a `NetworkPolicy` that allows all ingress regardless of source.

**Comment by shouhong** [comment]
Thanks! I tried as below and it works! Any source can access the selected pod's 8080 port.
ingress:
  - ports:
     - protocol: tcp
       port: 8080

But it seems there is a bug for multiple ports. Below specification does not work. My K8S version is 1.3.0.
ingress:
  - ports:
     - protocol: tcp
       port: 8080
     - protocol: http
       port: 80

**Comment by devurandom** [comment]
Are you sure `http` is a valid protocol?

**Comment by MikeSpreitzer** [comment]
@devurandom found it.  `http` is *NOT* a valid protocol.

**Comment by yiwang8621** [comment]
@caseydavenport, 
I'm trying to use network policy to do the network isolation between different namespaces by following the steps in:
http://kubernetes.io/docs/getting-started-guides/network-policy/walkthrough/

After I created the "DefaultDeny" isolation against the namespace, I can't hit the service from browser (using nodePort), 
I guess I must have missed something, this sounds like some basic function in the k8s, do you know what I might have missed?

I have posted this question in the slack and forum, but no answers so far, hope you can provide some tips to me. Many thanks for your help.

**Comment by thockin** [comment]
You should be able to omit the 'from' block of NetworkPolicy to allow traffic from anything.

**Comment by heartlock** [comment]
@thockin It not works. If ingress field is empty then this NetworkPolicy does not affect ingress isolation.

**Comment by MikeSpreitzer** [comment]
We have a bug or two.  Try another way.  IIRC, I update the example set somewhere to show what you need.

**Comment by MikeSpreitzer** [comment]
Example 3 in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network-policy.md shows what @yiwang8621 had trouble figuring out, namely how to write an `ingress` clause that allows everything in.

**Comment by yiwang8621** [comment]
Thanks @MikeSpreitzer and @thockin for the tips. Really appreciated.
I am working a project that needs to support multi tenants, after I read http://kubernetes.io/docs/getting-started-guides/network-policy/walkthrough/, I found it is a very nice feature and it can help me to prevent tenant A to access tenant B's services and PODs. So I give each tenant a new namespace, all his services and PODs are in his own namespace, all PODs have a label "tenant" with the tenant id.  

Here are commands and yaml file I have used, initially I only created "policy1", then I found that all nodePorts not reachable from outside. With the help of "policy2", now I can reach the service from outside, such as browser, but I found tenant b's containers can also access tenant A's service with the IP of the service and port number. Is there any other options for me to configure so that tenant b's container can't reach the tenant a's service by ports exposed in "policy2"? 
It will be very helpful if k8s network policy also has serviceSelector in the configuration of networkPolicy.

kubectl create namespace ns-tenant-a
kubectl label namespace ns-tenant-a name=tenant-a
kubectl annotate ns ns-tenant-a "net.beta.kubernetes.io/network-policy={\"ingress\": {\"isolation\": \"DefaultDeny\"}}"

# network policy "policy1" prevents other tenants to access tenant A's service and PODs, but it blocks the nodePort too.
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: policy1
spec:
  podSelector:
    matchLabels:
      tenant: "tenant-a"
  ingress:
    - from:
      - namespaceSelector:
         matchLabels:
          name: "tenant-a"

# network policy "policy2" to unblock the nodePorts exposed to outside. But it exposes these ports to other tenant's containers.
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: policy2
spec:
  podSelector:
    matchLabels:
      tenant: "tenant-a"
  ingress:
    - from:
      - namespaceSelector:
         matchLabels:
          name: "tenant-a"	
    - ports:
        - protocol: tcp
          port: @nodePort1_https@
        - protocol: tcp
          port: @nodePort2_https@
        - protocol: tcp
          port: @nodePort3_https@

**Comment by thockin** [comment]
You have a semantic conflict.  By putting it on a NodePort, you really are
saying "anyone can access this", but you don't want anyone to include that
other tenant.  That doesn't really make sense.  What you can do it limit
the Service with `loadBalancerSourceRanges` which is really a per-Service
construct.

NetworkPolicy will probably get the ability to specify CIDR ranges at some
point, too.

**Comment by ymariappan** [comment]
can anyone explain what is expected from the below network policy?

apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
 name: np
spec:
 podSelector:
  matchLabels:
    run: nginx-isolated-ns
 ingress:
  - from:
     - podSelector:
        matchLabels:
         app: ubuntuapp-isolated-ns
    ports:

as per https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network-policy.md documents, i can see the conflicts.

type NetworkPolicyIngressRule struct {
	// List of ports which should be made accessible on the pods selected for this rule. 
	// Each item in this list is combined using a logical OR.  
	// If this field is not provided, this rule matches all ports (traffic not restricted by port). 
	// If this field is empty, this rule matches no ports (no traffic matches).
	// If this field is present and contains at least one item, then this rule allows traffic 
	// only if the traffic matches at least one port in the ports list. 
	Ports *[]NetworkPolicyPort `json:"ports,omitempty"`
	
	// List of sources which should be able to access the pods selected for this rule.
	// Items in this list are combined using a logical OR operation.
	// If this field is not provided, this rule matches all sources (traffic not restricted by source).
	// If this field is empty, this rule matches no sources (no traffic matches). 
	// If this field is present and contains at least on item, this rule allows traffic only if the 
	// traffic matches at least one item in the from list. 
	From *[]NetworkPolicyPeer `json:"from,omitempty"`
}

According to NetworkPolicyPort, no ports should be selected.

type NetworkPolicyPort struct {
	// Optional.  The protocol (TCP or UDP) which traffic must match.
	// If not specified, this field defaults to TCP. 
	Protocol *api.Protocol `json:"protocol,omitempty"`
	
	// If specified, the port on the given protocol.  This can 
	// either be a numerical or named port.  If this field is not provided,
	// this matches all port names and numbers.
	// If present, only traffic on the specified protocol AND port
	// will be matched.
	Port *intstr.IntOrString `json:"port,omitempty"`
}

According to Port, all ports should be selected.

what is the expected behavior?

**Comment by MikeSpreitzer** [comment]
Note that
```
ports: []
```
is different from
```
ports: [{}]
```
The first one says the value of `ports` is the empty list, while the second one says the value of `ports` is a list containing one object (which has zero fields).

BTW, I am not sure that
```
ports:
```
is even valid YAML, since it says there is a `ports` field but does not say what its value is.

BTW, there is a bug in all the doc (due to the fact that we do not currently know an easy way to implement the distinction that we designed).  Both `ports: []` and omitting `ports` mean the same thing, which is that all ports are selected.

**Comment by ymariappan** [comment]
I have two questions.
1. ports: [{}] should omit all the ports or according to the port rule, should select all the ports?
2. what is expected behavior for ports:[{'protocol': 'TCP'}]

Thanks,
Yuvaraja

**Comment by danwinship** [comment]
"ports: [{}]" is

    Ports: &[]NetworkPolicyPort{
            { Protocol: nil, Port: nil },
    }

The docs for Protocol say: "If not specified, this field defaults to TCP", so "ports: [{}]" is equivalent to "ports:[{'protocol': 'TCP'}]"

The docs for Port say "If this field is not provided, this matches all port names and numbers.". So "ports:[{'protocol': 'TCP'}]" means "match all TCP ports".

> BTW, I am not sure that
> 
>     ports:
> 
> is even valid YAML

I don't know about YAML in general, but in kubernetes, that's equivalent to "ports: nil" or not specifying the field (so it means "all ports").

**Comment by xeor** [comment]
Is there any time estimate when we will get more powerful networkPolicy in kubernetes, or is this getting dragged behind because of 3rd party solutions like what `calicoctl` gives us?

**Comment by thockin** [comment]
"more powerful" isn't helpful.  Can you say more about what actual problems
you are trying to solve?

**Comment by farcaller** [comment]
I'm looking forward to egress rules.

**Comment by thockin** [comment]
Can you explain what you hope to achieve, rather than the mechanism you
think you might achieve it by?  As concretely as possible, please.

**Comment by farcaller** [comment]
I want to limit network access of specific pods to specific destination ip addresses, in case if the application inside of the pod is compromised.

**Comment by thockin** [comment]
You want to apply out-going firewall rules, based on destination IP address
(rather than hostname), varied by source pod?  Is that right?  Usually when
we dig into this, people want hostnames (e.g. github.com), not IP addresses.

**Comment by xeor** [comment]
@thockin : sorry for being a little wage..

I'm currently experimenting with kubernetes in a small on-premise cluster using `canal` (calico/flannel) for networking.

Looking at the [calico policy](http://docs.projectcalico.org/v2.1/reference/calicoctl/resources/policy), there are at least a couple of things missing from [kubernetes networkPolicy](https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_networkpolicyspec), which I already now (just started looking into network policies) am going to miss.
  * egress
  * define `to`, not just from
  * use network/subnet in rules as well as labels.
  * A way to define a `deny` and `log` action

Or is this something `calico` should provide as a 3rd party type?

**Comment by farcaller** [comment]
> You want to apply out-going firewall rules, based on destination IP address (rather than hostname), varied by source pod? 

I'd love to do it by host, but that brings a whole lot of additional complications, so it's fine if we start with IP-only.

**Comment by rikatz** [comment]
@xeor About the 'to', you define in which object this rule applies. See the podSelector attribute [here](https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_networkpolicyspec).

Anyway I don't think that a issue is the best place to look at this doubts, instead I would suggest you to use the Kubernetes Slack channel :)

Thanks

**Comment by thockin** [comment]
On Fri, May 5, 2017 at 12:18 PM, Lars Solberg <notifications@github.com> wrote:
>
> @thockin : sorry for being a little wage..
>
> I'm currently experimenting with kubernetes in a small on-premise cluster using canal (calico/flannel) for networking.
>
> Looking at the calico policy, there are at least a couple of things missing from kubernetes networkPolicy, which I already now (just started looking into network policies) am going to miss.
>
> egress

I need to understand what people want to achieve with egress.
- pod-to-pod egress?
- pod-to-outside egress?
- based on target IP or based on hostname?

> define to, not just from

We have "to" in the form of podSelector

> use network/subnet in rules as well as labels.

"from CIDR" has been proposed, we just wanted to GA before adding more.

> A way to define a deny and log action

logging is not a universal feature, so we can't easily add it to
NetPolicy, I think.

**Comment by thockin** [comment]
On Fri, May 5, 2017 at 12:29 PM, Vladimir Pouzanov
<notifications@github.com> wrote:
>
> You want to apply out-going firewall rules, based on destination IP address (rather than hostname), varied by source pod?
>
> I'd love to do it by host, but that brings a whole lot of additional complications, so it's fine if we start with IP-only.

You're in the vast minority of people I speak to.  Digging into
use-cases it is almost always of the form "allow pod to hit github but
nothing else".

**Comment by xeor** [comment]
@thockin , by egress, at least for my case is about pod-to-outside based on (also in my case), a subnet. In short, I want a pod to not have access to certain parts of my network. Or a pod that only can get out on the internet.

**Comment by thockin** [comment]
> I want a pod to not have access to certain parts of my network

Thanks.  That is much clearer.

**Comment by lxpollitt** [comment]
>Looking at the calico policy, there are at least a couple of things missing from kubernetes networkPolicy, which I already now (just started looking into network policies) am going to miss.
>- egress
>- define to, not just from
>- use network/subnet in rules as well as labels.
>- A way to define a deny and log action
>Or is this something calico should provide as a 3rd party type?

@xeor you should still be able to use Calico policy objects (specified via calicoctl) alongside k8s policy objects (specified va kubectl) today.  So you don't "lose" these features.  Support for egress policies via annotations and/or TPRs so you can use kubectl for those in the future is also planned.

**Comment by sege** [comment]
> I need to understand what people want to achieve with egress.
> - pod-to-pod egress?
> - pod-to-outside egress?
> - based on target IP or based on hostname?

Mostly pod-to-outside egress in our case. We have a lot of pod-to-legacy-data sources. We can't implement SDN on those old sources and they might even be external sources. Both hostname and IP-based would be nice.

**Comment by rikatz** [comment]
The same as @sege here. 

Actually most of our egress traffic is to legacy servers (including but not limited to Oracle and Mainframes), based on hostnames and IP Addresses.

An additional case are systems that shall not communicate with Internet and should have a default denied Egress traffic.

We use calico by hand here to limit the egress traffic, and I know there's a PR in Calico to read namespaces annotations (or something like that) to automatically create those rules.

But I think the most correct path here is to support in Namespace annotation ``net.beta.kubernetes.io/network-policy`` an egress isolation also, and that the NetworkPolicy object supports both ingress and egress rule, and also objects containing IP addresses (and not only other kubernetes objects).

Thanks!!

**Comment by danwinship** [comment]
NetworkPolicy egress support is #26720 although it has stalled while we finalize NetworkPolicy v1...

I think my egress NetworkPolicy uses cases doc (https://docs.google.com/document/d/1-Cq_Y-yuyNklvdnaZF9Qngl3xe0NnArT7Xt_Wno9beg) covers all the things people have mentioned in the last few comments here.

**Comment by coresolve** [comment]
looks like https://github.com/kubernetes/kubernetes/pull/26720 closed due to inactivity. Are folks still working on it?

**Comment by caseydavenport** [comment]
I think we'l re-open or open another if/when that becomes active again.  For now, no one is actively working on it so it's probably right to close.

**Comment by ahmetb** [comment]
@caseydavenport Do you mind bringing the design proposal up to date: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network-policy.md. It appears like the NamespaceSpec proposal did not make it and the default-deny got implemented with selectors on NetworkPolicy. (Although, I am not sure if proposals are meant to be updated later on to reflect the actual implementation.)

**Comment by caseydavenport** [comment]
I was under the impression that proposals were not living documents, though I could be wrong.

For example, not sure if egress policy will get a new proposal or a modification to the existing one.  

@thockin any thoughts?  Happy to update if we think that's the right process.

**Comment by ahmetb** [comment]
I would assume so. I was just reading the proposal to get more info about how the feature works. I realized some of the details of how the NetworkPolicy behaves lives only in the proposal and not in the docs. I’m hoping to study it further and release a comprehensive guide and update the documentation.

**Comment by phsiao** [comment]
Want to see if now is a good time to resume the discussion around supporting hostname as peer for both ingress and egress.   Our use case is for restricting both ingress and egress, and the hostname can returns multiple A records that is managed externally, for example CDN hostnames.

I suspect a major concern is how to handle consistency --- NPC and the pod may resolve different IPs for the same hostname if the DNS record return a random subnet of IPs, for example, S3, but I am also not convinced that is a normal case.  As a policy I think it is a reasonable option in addition to ipBlock.

**Comment by cmluciano** [comment]
@caseydavenport Is this issue stale?

**Comment by caseydavenport** [comment]
@cmluciano yes, I think we should close this and use the features issue or new separate issues for other topics relating to NP.

/close

**Comment by caseydavenport** [comment]
@phsiao could you open another feature request, or send an email on the sig-network mailing list to have that discussion?

I don't think this is the right place anymore.

**Comment by phsiao** [comment]
Will do a feature request ticket.

**Comment by dmitris** [comment]
for reference, Network Policy proposal is at https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network/network-policy.md (points to this ticket in References)
