### ISSUE TITLE
AWS: Document ownership and 2 security group trick

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22479]
I should document how the KubernetesCluster tag implies ownership, and how if you want to modify a security group or IAM policy you should add a second one (where only one is tagged)

See e.g. https://github.com/kubernetes/kubernetes/pull/21987#issuecomment-191923383 but this has come up a lot.

**Comment by goltermann** [comment]
bringing a few P2 doc bugs back in the 1.3 milestone

**Comment by goltermann** [comment]
This is an issue marked v1.3 and kind/documentation.  Can you get it fixed up this week?
