### ISSUE TITLE
scheme.ObjectKind() returns arbitrary API group for *extensions.HorizontalPodAutoscalers

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#22484]
From https://github.com/kubernetes/kubernetes/issues/22454#issuecomment-192034464

`kubectl get hpa -o yaml` prints the output in `autoscaling/v1` but `kubectl.sh convert -f docs/user-guide/horizontal-pod-autoscaling/hpa-php-apache.yaml` prints the output in `extensions/v1beta1`

We should have one default group version for all kubectl commands for hpa.

@kubernetes/kubectl @piosz @kubernetes/autoscaling @kubernetes/sig-api-machinery

**Comment by AdoHe** [comment]
I could see we should use `autoscaling/v1` as the default group version for hpa.

**Comment by liggitt** [comment]
Depends. @deads2k and @lavalamp had discussed an ordering determined from the server's discovery doc, I believe

**Comment by nikhiljindal** [comment]
Yes. I think we had decided to keep extensions/v1beta1 as the default in 1.2.
Will switch to autoscaling/v1 in 1.3.

**Comment by AdoHe** [comment]
I would help with updating `kubectl get hpa` behavior.

**Comment by piosz** [comment]
It seems that #19941 is not fixed yet.

When I build locally using just `make` I've got object in version `autoscaling/v1`. When I build locally using `make quick-release` I've got object in version `extensions/v1beta1`.

**Comment by deads2k** [comment]
> When I build locally using just make I've got object in version autoscaling/v1. When I build locally using make quick-release I've got object in version extensions/v1beta1.

Can you show me the `kubectl get hpa --v=8` command?  `autoscaling` isn't in the priority list at all.

**Comment by piosz** [comment]
I'm compiling with go 1.6.
```
./cluster/kubectl.sh get hpa -o yaml --v=8
I0304 14:06:11.586754   29272 loader.go:229] Config loaded from file /usr/local/google/home/pszczesniak/.kube/config
I0304 14:06:11.588939   29272 round_trippers.go:264] GET https://<ip>/api
I0304 14:06:11.588961   29272 round_trippers.go:271] Request Headers:
I0304 14:06:11.588971   29272 round_trippers.go:274]     Authorization: Bearer xxxxxxx
I0304 14:06:11.588982   29272 round_trippers.go:274]     Accept: application/json, */*
I0304 14:06:11.771773   29272 round_trippers.go:289] Response Status: 200 OK in 182 milliseconds
I0304 14:06:11.771807   29272 round_trippers.go:292] Response Headers:
I0304 14:06:11.771817   29272 round_trippers.go:295]     Content-Type: application/json
I0304 14:06:11.771826   29272 round_trippers.go:295]     Date: Fri, 04 Mar 2016 13:06:11 GMT
I0304 14:06:11.771835   29272 round_trippers.go:295]     Content-Length: 132
I0304 14:06:11.771889   29272 request.go:870] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]}
I0304 14:06:11.772123   29272 round_trippers.go:264] GET https://<ip>/apis
I0304 14:06:11.772139   29272 round_trippers.go:271] Request Headers:
I0304 14:06:11.772148   29272 round_trippers.go:274]     Accept: application/json, */*
I0304 14:06:11.772157   29272 round_trippers.go:274]     Authorization: Bearer xxxxxxxx
I0304 14:06:11.805333   29272 round_trippers.go:289] Response Status: 200 OK in 33 milliseconds
I0304 14:06:11.805391   29272 round_trippers.go:292] Response Headers:
I0304 14:06:11.805416   29272 round_trippers.go:295]     Content-Type: application/json
I0304 14:06:11.805441   29272 round_trippers.go:295]     Date: Fri, 04 Mar 2016 13:06:11 GMT
I0304 14:06:11.805464   29272 round_trippers.go:295]     Content-Length: 766
I0304 14:06:11.805559   29272 request.go:870] Response Body: {"kind":"APIGroupList","groups":[{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]}]}
I0304 14:06:11.807361   29272 round_trippers.go:264] GET https://<ip>/api
I0304 14:06:11.807378   29272 round_trippers.go:271] Request Headers:
I0304 14:06:11.807386   29272 round_trippers.go:274]     Accept: application/json, */*
I0304 14:06:11.807395   29272 round_trippers.go:274]     Authorization: Bearer xxxxxx
I0304 14:06:11.840592   29272 round_trippers.go:289] Response Status: 200 OK in 33 milliseconds
I0304 14:06:11.840652   29272 round_trippers.go:292] Response Headers:
I0304 14:06:11.840666   29272 round_trippers.go:295]     Date: Fri, 04 Mar 2016 13:06:11 GMT
I0304 14:06:11.840681   29272 round_trippers.go:295]     Content-Length: 132
I0304 14:06:11.840710   29272 round_trippers.go:295]     Content-Type: application/json
I0304 14:06:11.840819   29272 request.go:870] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]}
I0304 14:06:11.841260   29272 round_trippers.go:264] GET https://<ip>/apis
I0304 14:06:11.841314   29272 round_trippers.go:271] Request Headers:
I0304 14:06:11.841351   29272 round_trippers.go:274]     Accept: application/json, */*
I0304 14:06:11.841388   29272 round_trippers.go:274]     Authorization: Bearer xxxxxxxx
I0304 14:06:11.874910   29272 round_trippers.go:289] Response Status: 200 OK in 33 milliseconds
I0304 14:06:11.874966   29272 round_trippers.go:292] Response Headers:
I0304 14:06:11.875000   29272 round_trippers.go:295]     Content-Type: application/json
I0304 14:06:11.875009   29272 round_trippers.go:295]     Date: Fri, 04 Mar 2016 13:06:11 GMT
I0304 14:06:11.875018   29272 round_trippers.go:295]     Content-Length: 766
I0304 14:06:11.875079   29272 request.go:870] Response Body: {"kind":"APIGroupList","groups":[{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]}]}
I0304 14:06:11.877844   29272 round_trippers.go:264] GET https://<ip>/apis/extensions/v1beta1/namespaces/default/horizontalpodautoscalers
I0304 14:06:11.877866   29272 round_trippers.go:271] Request Headers:
I0304 14:06:11.877876   29272 round_trippers.go:274]     Authorization: Bearer xxxxxxxx
I0304 14:06:11.877885   29272 round_trippers.go:274]     Accept: application/json, */*
I0304 14:06:11.877893   29272 round_trippers.go:274]     User-Agent: kubectl/v1.2.0 (linux/amd64) kubernetes/60430ca
I0304 14:06:11.911856   29272 round_trippers.go:289] Response Status: 200 OK in 33 milliseconds
I0304 14:06:11.911905   29272 round_trippers.go:292] Response Headers:
I0304 14:06:11.911923   29272 round_trippers.go:295]     Content-Type: application/json
I0304 14:06:11.911941   29272 round_trippers.go:295]     Date: Fri, 04 Mar 2016 13:06:11 GMT
I0304 14:06:11.911958   29272 round_trippers.go:295]     Content-Length: 715
I0304 14:06:11.912042   29272 request.go:870] Response Body: {"kind":"HorizontalPodAutoscalerList","apiVersion":"extensions/v1beta1","metadata":{"selfLink":"/apis/extensions/v1beta1/namespaces/default/horizontalpodautoscalers","resourceVersion":"4777"},"items":[{"metadata":{"name":"rc","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/horizontalpodautoscalers/rc","uid":"4e83c3ea-e1fb-11e5-af05-42010af00002","resourceVersion":"2886","creationTimestamp":"2016-03-04T11:21:57Z"},"spec":{"scaleRef":{"kind":"ReplicationController","name":"rc","apiVersion":"v1","subresource":"scale"},"minReplicas":1,"maxReplicas":3,"cpuUtilization":{"targetPercentage":80}},"status":{"currentReplicas":1,"desiredReplicas":1,"currentCPUUtilizationPercentage":0}}]}
I0304 14:06:11.913729   29272 round_trippers.go:264] GET https://<ip>/api
I0304 14:06:11.913764   29272 round_trippers.go:271] Request Headers:
I0304 14:06:11.913781   29272 round_trippers.go:274]     Accept: application/json, */*
I0304 14:06:11.913797   29272 round_trippers.go:274]     Authorization: Bearer xxxxxx
I0304 14:06:11.947001   29272 round_trippers.go:289] Response Status: 200 OK in 33 milliseconds
I0304 14:06:11.947063   29272 round_trippers.go:292] Response Headers:
I0304 14:06:11.947099   29272 round_trippers.go:295]     Content-Type: application/json
I0304 14:06:11.947165   29272 round_trippers.go:295]     Date: Fri, 04 Mar 2016 13:06:11 GMT
I0304 14:06:11.947195   29272 round_trippers.go:295]     Content-Length: 132
I0304 14:06:11.947294   29272 request.go:870] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]}
I0304 14:06:11.947683   29272 round_trippers.go:264] GET https://<ip>/apis
I0304 14:06:11.947720   29272 round_trippers.go:271] Request Headers:
I0304 14:06:11.947742   29272 round_trippers.go:274]     Accept: application/json, */*
I0304 14:06:11.947777   29272 round_trippers.go:274]     Authorization: Bearer xxxxxxx
I0304 14:06:11.980973   29272 round_trippers.go:289] Response Status: 200 OK in 33 milliseconds
I0304 14:06:11.980995   29272 round_trippers.go:292] Response Headers:
I0304 14:06:11.981004   29272 round_trippers.go:295]     Content-Type: application/json
I0304 14:06:11.981013   29272 round_trippers.go:295]     Date: Fri, 04 Mar 2016 13:06:11 GMT
I0304 14:06:11.981021   29272 round_trippers.go:295]     Content-Length: 766
I0304 14:06:11.981057   29272 request.go:870] Response Body: {"kind":"APIGroupList","groups":[{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"<ip>"}]}]}
apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: 2016-03-04T11:21:57Z
    name: rc
    namespace: default
    resourceVersion: "2886"
    selfLink: /apis/extensions/v1beta1/namespaces/default/horizontalpodautoscalers/rc
    uid: 4e83c3ea-e1fb-11e5-af05-42010af00002
  spec:
    maxReplicas: 3
    minReplicas: 1
    scaleTargetRef:
      apiVersion: v1
      kind: ReplicationController
      name: rc
    targetCPUUtilizationPercentage: 80
  status:
    currentCPUUtilizationPercentage: 0
    currentReplicas: 1
    desiredReplicas: 1
kind: List
metadata: {}
```

**Comment by deads2k** [comment]
> I'm compiling with go 1.6.

So that one is dealing in `hpa.extensions`, do you have the alternate example that gives you `hpa.autoscaling` too?

**Comment by deads2k** [comment]
> So that one is dealing in hpa.extensions, do you have the alternate example that gives you hpa.autoscaling too?

Oh neat.  It's getting the correct resource and then mutating the kind.  That's pretty cool, but not a `RESTMapper` problem

**Comment by piosz** [comment]
Isn't it `autoscaling` group?
> `apiVersion: autoscaling/v1`

**Comment by deads2k** [comment]
> Isn't it autoscaling group?

The `RESTMapper` is giving correct information, which results in hitting this URL: `https://<ip>/apis/extensions/v1beta1/namespaces/default/horizontalpodautoscalers`.  The response from that URL is wrong because its converting the object into a different group on the way out, but that's a server-side flaw, not a `RESTMapper` or client problem.

I just want to be sure we're looking in the correct location.

**Comment by piosz** [comment]
So closing #19941

**Comment by liggitt** [comment]
Incorrect group serialization on the server side is p0

**Comment by liggitt** [comment]
Do we want a new issue for that, or to adjust this to cover the server side problem?

**Comment by deads2k** [comment]
Taking a deeper look, looks like the server response correctly for the URL, but a client-side conversion is happening to a different group for display and for some reason `kubectl` is asking for more discover information *after* the list request.

**Comment by bgrant0607** [comment]
Let's just use this issue, if a new one wasn't created already

**Comment by liggitt** [comment]
> `kubectl get hpa -o yaml` prints the output in `autoscaling/v1`

I'm not seeing that behavior. How are you triggering that?

**Comment by piosz** [comment]
`make clean & make` with go in version 1.6

**Comment by liggitt** [comment]
I see it now with go1.5.3 and go1.6. difference in behavior between go versions points to reliance on map iteration order or import+init() order, neither of which are stable

**Comment by deads2k** [comment]
`ObjectKind` needs to return an error for ambiguous matches and pretty much every caller should use `ObjectKinds` anyway.  Not sure how much work it is yet.

**Comment by deads2k** [comment]
The assumption of exactly one `ObjectKind` for a given object runs deep and was broken when `hpa.autoscaling` went in with https://github.com/kubernetes/kubernetes/pull/21603.

**Comment by liggitt** [comment]
Actually, I think it broke when the extensions.HPA was registered into the autoscaling API group in https://github.com/kubernetes/kubernetes/commit/2fbc5bb767875b3e276b3970b8c2b3c0286ed10c#diff-a5dba1721ceb4681d2db5c7196419f3cR48

**Comment by deads2k** [comment]
This line: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/autoscaling/register.go#L51

**Comment by deads2k** [comment]
> Actually, I think it broke when the extensions.HPA was registered into the autoscaling API group in 2fbc5bb#diff-a5dba1721ceb4681d2db5c7196419f3cR48

Ah, you're right.  It was this pull: https://github.com/kubernetes/kubernetes/pull/20501.  I just checked for when the types appeared instead of thinking that we had an API group that didn't declare any types.

**Comment by lavalamp** [comment]
@deads2k at this point, you believe it's a client problem, correct?

**Comment by liggitt** [comment]
The server is returning the correct responses from the API group endpoints, if that is what you're asking.

When the `*extensions.HPA` go type was registered into two API groups, that introduced undefined behavior for anything calling `scheme.ObjectKind` (depending on map ordering or import registration order, both of which are unstable). This manifestation of that undefined behavior is client-side, but there are likely other issues we just haven't thought of yet.

**Comment by deads2k** [comment]
> @deads2k at this point, you believe it's a client problem, correct?

It's a `Scheme` problem, so it could cause problems everywhere.  For instance, `Scheme.Convert` calls out to `Scheme.ObjectKind` and expects a single result.  It does that client-side AND server-side.

**Comment by piosz** [comment]
I'll take a look on Monday, so if anyone can do it earlier that would be great.

**Comment by nikhiljindal** [comment]
I will try to take a look and let you know if I make any progress.

**Comment by piosz** [comment]
I don't see any progress here so taking over once again

**Comment by piosz** [comment]
I wasn't able to fix this today, so re-assigning back to @nikhiljindal

**Comment by AdoHe** [comment]
I could help fix this today. @nikhiljindal if you don't have extra bandwidth

**Comment by liggitt** [comment]
would probably be good to discuss approaches to possible solutions before putting together a PR

**Comment by nikhiljindal** [comment]
@AdoHe Thanks! Please feel free to suggest a solution here.

Pre 1.2, we were using the ordering in KUBE_API_VERSIONS to determine the priority order.
We need a place where users can specify the order. We can reuse the same env var or introduce a new one.

**Comment by nikhiljindal** [comment]
Actually, looks like we are using the KUBE_API_VERSIONS ordering in PriorityRESTMapper: 
https://github.com/kubernetes/kubernetes/blob/master/pkg/apimachinery/registered/registered.go#L200. So we can use the same here in scheme.ObjectKind() as well?

cc @caesarxuchao who I think had worked on stop relying on KUBE_API_VERSIONS ordering.

**Comment by deads2k** [comment]
Why not try to fix all the code to properly handle `ObjectKinds` instead of `ObjectKind`?  Those calls that require disambiguation could take a `disambiguator` of some kind.  That would allow us to plumb through the correct knowledge through the codebase instead of using optional "psuedo-globals" to make it work.

Also, the `PriorityRESTMapper` used by `kubectl` is made here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L211

**Comment by nikhiljindal** [comment]
Yes that will work as well.
What do you think is the right disambiguator? Does KUBE_API_VERSIONS seem fine to you?

If all of them are using the same disambiguator and have the same logic of getting all ObjectKinds using scheme.ObjectKinds() and then passing them through the disambiguator to get one ObjectKind, then we can have a single function do that. Can scheme.ObjectKind() can be that function?

**Comment by liggitt** [comment]
I wasn't aware of `KUBE_API_VERSIONS` doing anything client-side

**Comment by deads2k** [comment]
> If all of them are using the same disambiguator and have the same logic of getting all ObjectKinds using scheme.ObjectKinds() and then passing them through the disambiguator to get one ObjectKind, then we can have a single function do that. Can scheme.ObjectKind() be that function?

I'd expect disambiguation to vary depending on use.  For instance, in some cases we'll want it based on user choice. In others, we'll want to express the intent that the code can only handle certain options.  In still others, ambiguity means failure.  And the final one I noticed in the code was "ignore errors".

However, if we find that all those actually collapse, then by all means, plumbing it into the `Scheme` (not directly using an env var) seems very reasonable.

**Comment by deads2k** [comment]
> What do you think is the right disambiguator? Does KUBE_API_VERSIONS seem fine to you?

In the printing case here, no.  I think the disambiguation should go like this, but I'm not completely certain:
 1. If there is exactly one hit from `ObjectKinds` has a group that is specified in the `--output-version`, use that.
 1. If there are multiple hits from `ObjectKinds` that match a group specified in `--output-version`, then look to see if one matches the group of the resource (distinct from kind) that you used to get the original data.  If there's exactly one match, use it.
 1. If you ended up with more than one potential match in step 2, but one of the `--output-version` matches exactly matches the `GroupVersion` of the resource you used, use that one.
 1. If `--output-version` isn't specified, then you should use the `ObjectKind` that matches the group of the resource (not kind) that you requested and then use that group to locate the preferred external version for that group.

You can see that disambiguation for something like printing is going to be different than for something like conversion.

**Comment by AdoHe** [comment]
At this point, `ObjectKind` just return the first one of `ObjectKinds`, we need to return an error if more than one matching get or we need to use some priority rule.

**Comment by deads2k** [comment]
> At this point, ObjectKind just return the first one of ObjectKinds, we need to return an error if more than one matching get or we need to use some priority rule.

Not just that, it returns a *random* first since its based on map ordering.

**Comment by AdoHe** [comment]
> Not just that, it returns a random first since its based on map ordering.
I just noticed the map ordering, it should returns a random first.

**Comment by bgrant0607** [comment]
Is someone working on this? It needs to be fixed in the next 24 hours to make 1.2.

**Comment by nikhiljindal** [comment]
I am working on this.
Trying to get a PR ready based on @deads2k comment: https://github.com/kubernetes/kubernetes/issues/22484#issuecomment-193784766

**Comment by nikhiljindal** [comment]
I am still debugging, but this seems like a bug in visitor code to me.
The builder in GET is using PriorityMapper from kubectl factory: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/get.go#L199.

Hence resource.AsVersionedObject should be converting to extensions.v1beta1: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/result.go#L259
But `info.Mapping.GroupVersionKind.GroupVersion()` is `autoscaling/v1` there.

The visitors being called in `kubectl get hpa -o yaml` are:
```
NewSelector
EagerVisitorList
VisitorList
NewFlattenListVisitor
ContinueOnErrorVisitor
```
I see that when NewFlattenListVisitor's Visitor callback function is called (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/visitor.go#L324), info.Mapping is:
```
&{Resource:horizontalpodautoscalers GroupVersionKind:extensions/v1beta1, Kind=HorizontalPodAutoscaler Scope:0x215c3e0 ObjectConvertor:0xc8200a0240 MetadataAccessor:{}}
```
But, when it calls ContinueOnErrorVisitor's callback (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/visitor.go#L348), it passes info.Mapping as:
```
&{Resource:horizontalpodautoscalers GroupVersionKind:autoscaling/v1, Kind=HorizontalPodAutoscaler Scope:0x215c3e0 ObjectConvertor:0xc8200a0240 MetadataAccessor:{}}
```

**Comment by nikhiljindal** [comment]
Is NewFlattenListVisitor's visitorFunc expected to change Info.Mapping?

**Comment by nikhiljindal** [comment]
It did boil down to ObjectKind() :)
`NewFlattenListVisitor` calls `mapper.InfoForObject` which calls ObjectKind: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/mapper.go#L89.

The object that it got was:
```
&{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:php-apache GenerateName: Namespace:default SelfLink:/apis/extensions/v1beta1/namespaces/default/horizontalpodautoscalers/php-apache UID:ba312008-e706-11e5-9835-6c3be516adae ResourceVersion:15 Generation:0 CreationTimestamp:2016-03-10 13:26:18 -0800 PST DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[]} Spec:{ScaleRef:{Kind:ReplicationController Name:php-apache APIVersion: Subresource:scale} MinReplicas:0xc820151ca0 MaxReplicas:10 CPUUtilization:0xc820151ca8} Status:{ObservedGeneration:<nil> LastScaleTime:<nil> CurrentReplicas:0 DesiredReplicas:0 CurrentCPUUtilizationPercentage:<nil>}}
```
and it returned gvk:
```
autoscaling/__internal, Kind=HorizontalPodAutoscaler
```
and thats why the final object ends up in autoscaling/v1.

**Comment by liggitt** [comment]
We have the original `GroupVersionKind` used to fetch the list of HPAs in the list info object. Using that to pick a preferred version when there are multiple possibilities could work.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/22840 is one way we could do this

**Comment by nikhiljindal** [comment]
Yes, thanks @liggitt for sending that PR.

We should look closely at other InfoForObject() calls as well and see if we can pass meaningful preferredGVKs. We should return an error if we cant rather than silently choosing a random one.

**Comment by nikhiljindal** [comment]
I was discussing this with @caesarxuchao and it seems that we can get away without using ObjectKind() at many (if not all) places.
For ex: for `kubectl get`, we already have the resource name, we can get the kind from resource using the RESTMapper (which supports priority).
In `kubectl create`, we unnecessarily try to find kind from go type using ObjectKind(). We have the kind directly in the input object.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/22840 has fixed the critical `kubectl get hpa` issue.

We now need to scrub the codebase and fix other places as well. But thats beyond 1.2
Filed https://github.com/kubernetes/kubernetes/issues/22866 to track.
