### ISSUE TITLE
fixing detecting docker version

### ISSUE THREAD

**Issue by pstauffer** [kubernetes/kubernetes#22485]
In the getting-started-guides matches the detection of the docker version not with a version 1.1x.

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.sh#L108

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/worker.sh#L105

**Comment by pstauffer** [comment]
I found the original pull request for this docker version detection... Maybe this can help for understanding.
https://github.com/kubernetes/kubernetes/pull/20281

**Comment by yujuhong** [comment]
Closing based on https://github.com/kubernetes/kubernetes/pull/22488#issuecomment-228206183
