### ISSUE TITLE
Unable to use client certificates with etcd after change to new client

### ISSUE THREAD

**Issue by kshelton** [kubernetes/kubernetes#22498]
When the switch to the new client occurred, client certificate support wasn't included.

**Comment by liggitt** [comment]
dupe of https://github.com/kubernetes/kubernetes/issues/18760

**Comment by kshelton** [comment]
I've been looking for an open issue/pr for this since December - strange how github search couldn't find it.

**Comment by lavalamp** [comment]
Yeah, sorry it can be hard to find things.
