### ISSUE TITLE
Kubelet should respect ACPI shutdown

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#22494]
If I shut off my instance, it should receive an [ACPI](https://en.wikipedia.org/wiki/Advanced_Configuration_and_Power_Interface) shutdown signal, (e.g. [in GCE](https://cloud.google.com/compute/docs/instances/stopping-or-deleting-an-instance#delete_timeout)).  Kubelet should respect that signal and self-evacuate, or, at least, signal to the node controller that it's going down and is `NotReady`.

I'm branching this off of https://github.com/kubernetes/kubernetes/issues/7351, because a node- or cloud provider-initiated shutdown is different from going through the API.

**Comment by ihmccreery** [comment]
cc @dchen1107 this is the issue I mentioned earlier today.

**Comment by dchen1107** [comment]
We talked about this offline. I agreed that Kubelet should respect that signal, and push new NotReady status with new Condition similar to #14140. But who should initiate this shutdown is a different story. I think it should be managed through cluster API, not node- or cloud provider- initiated directly.

**Comment by jkhelil** [comment]
When using the preemtible vms on gce, we need to handle the ACPI shutdown. gce provides shutdown scripts, which can send sigterm to kubelet. 
@ihmccreery  What is the status of this issue, are you working on it ?

**Comment by ihmccreery** [comment]
As far as I know, this is not being prioritized and no one is working on it.  @dchen1107 would know better.

**Comment by kevincox** [comment]
/reopen

GKE still lacks graceful shutdowns. If not fixed soon this should be mentioned in the docs. It makes preemptable instances less suitable.
