### ISSUE TITLE
GKE e2e flake: Horizontal pod autoscaling (scale resource: CPU) [Serial] [Slow] ReplicationController Should scale from 5 pods to 3 pods and from 3 to 1

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#22491]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-serial/691/

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:62
Mar  3 08:59:13.439: Number of replicas has changed: expected 3, got 4

cc/ @mwielgus @piosz

**Comment by ihmccreery** [comment]
@piosz Any update on this?  We're seeing this in GKE, and would like to get it worked out.

**Comment by ihmccreery** [comment]
e.g.

- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial-release-1.2/15
- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial-release-1.2/13
- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial-release-1.2/11

**Comment by gmarek** [comment]
And again: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-serial/834/

**Comment by piosz** [comment]
@ihmccreery #21664 should help. I've started working on it.

@gmarek there was a problem with network:
```
01:38:55 Mar 22 01:38:55.053: INFO: At 2016-03-22 01:36:44 -0700 PDT - event for test-deployment-3901643370-qlyk8: {kubelet gke-jenkins-e2e-b121a934-node-uekb} Failed: Failed to pull image "gcr.io/google_containers/resource_consumer:beta2": API error (500): unable to ping registry endpoint https://gcr.io/v0/
01:38:55 v2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable
01:38:55  v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 169.254.169.254:53: dial udp 169.254.169.254:53: network is unreachable
```

**Comment by pwittrock** [comment]
I am seeing the networking issue pretty frequently in the node e2e tests:

http://kubekins.dls.corp.google.com/view/Node/job/kubelet-gce-e2e-ci/785/consoleFull

**Comment by gmarek** [comment]
This is not a good sign as well.

**Comment by piosz** [comment]
dupa of #23536
