### ISSUE TITLE
Make sure HPA works for Deployments and enable appriopriate e2e tests

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#22505]
In #19840 @madhusudancs disabled e2e tests which verify that HPA can scale Deployment. There is the following comment there:
> TODO(madhusudancs): Fix this when Scale group issues are resolved (see issue #18528).

Since #18528 is fixed should we re-enable the tests? Is there anything that should be fixed before?

@bgrant0607 @fgrzadkowski @janetkuo @mwielgus

**Comment by madhusudancs** [comment]
@piosz What I wanted from #18528 is now being tracked in #21549. There are a bunch of PRs we need to get done before enabling these e2e tests. I don't think it can be enabled yet. 

Relevant PRs:
1. #21966
2. #21910 
3. And I am working on a PR which I haven't even published yet.

**Comment by piosz** [comment]
Thanks for the update. So once you are done please re-enable them.

**Comment by madhusudancs** [comment]
@piosz sure, will do.

**Comment by fgrzadkowski** [comment]
@madhusudancs What will happen if you don't merge those PRs before the cut? Does the current code work without your changes? Can we scale Deployment and ReplicaSet (we run tests for Replication controller so this should work).

**Comment by bgrant0607** [comment]
@fgrzadkowski No, Deployment and ReplicaSet cannot yet be scaled.

**Comment by bgrant0607** [comment]
Scale is in.

@madhusudancs Please close this once you've confirmed that tests pass.

**Comment by madhusudancs** [comment]
All HPA tests are passing, both e2e and unit tests. And both e2e and unit tests now have HPA targeting Deployments and ReplicaSets. Closing this issue.

**Comment by piosz** [comment]
Thanks @madhusudancs
