### ISSUE TITLE
json: cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by jayme-github** [kubernetes/kubernetes#22506]
I belive this is similar to #2763. I'm unable to create the rc from the following yaml template:

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-logging-1
  namespace: kube-system
  labels:
    app: elasticsearch-logging
    version: v1
spec:
  replicas: 1
  selector:
    app: elasticsearch-logging
    version: v1
    replica: 1
  template:
    metadata:
      labels:
        app: elasticsearch-logging
        version: v1
        replica: 1
    spec:
      containers:
      - image: gcr.io/google_containers/elasticsearch:1.7
        name: elasticsearch-logging
        resources:
          limits:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
      volumes:
      - name: es-persistent-storage
        emptyDir: {}
```

```sh
$ kubectl create -f /tmp/controller.yaml
unable to load "/tmp/controller.yaml": json: cannot unmarshal number into Go value of type string
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}
```

Quoting the `replica` value works around this.

**Comment by thockin** [comment]
> I belive this is similar to #2763. I'm unable to create the rc from the following yaml template:

Let's play "find the place where YAML is too subtle for humans to
use" :)  Our clue is that it thinks it is parsing a number.


>   selector:
>     app: elasticsearch-logging
>     version: v1
>     replica: 1

First instance.  Try "1" or "one" :)

>   template:
>     metadata:
>       labels:
>         app: elasticsearch-logging
>         version: v1
>         replica: 1

Second instance

**Comment by mikedanese** [comment]
This seems to be working as intended.

**Comment by jayme-github** [comment]
@thockin @mikedanese thanks for your help. I'm unsure if I got that right. It was clear to me that quoting the number fixes the parsing problem but I don't understand why this is intended. Shouldn't numbers be possible (like for ports) or is this an limitation of labels/selectors?

**Comment by thockin** [comment]
Selectors are explicitly string-string maps, but YAML parses `1` as a
number, and then can't figure out how to convert that to a string.

**Comment by jayme-github** [comment]
> Selectors are explicitly string-string maps, but YAML parses `1` as a
number, and then can't figure out how to convert that to a string.

Okay, makes sense now (still silly that the number can't be converted :smile:).
Thank you very much for clarification! :+1:
