### ISSUE TITLE
kubectl edit job returns apiVersion: extensions/v1beta1

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#22517]
Steps to reproduces:

```
kubectl run pi --image=perl --restart=OnFailure -- perl -Mbignum=bpi -wle 'print bpi(2000)'
kubectl edit job/pi
```

In the editor you'll see `apiVersion: extensions/v1beta1` instead of `batch/v1`. It does not matter if you create a job using above command or if you create one with explicit `batch/v1.

@erictune

**Comment by AdoHe** [comment]
I think we should keep this on 1.2

**Comment by dims** [comment]
`kubectl get job/pi -o yaml` also gives the wrong apiVersion

**Comment by dims** [comment]
kubectl is making the following calls

`I0518 17:44:26.983681   13465 handlers.go:161] GET /apis/batch/v1/jobs?resourceVersion=0: (924.71µs) 200 [[hyperkube/v1.3.0 (linux/amd64) kubernetes/952e830/job-controller] 127.0.0.1:33560]
I0518 17:44:43.958482   13465 handlers.go:161] GET /apis/extensions/v1beta1/namespaces/default/jobs/pi: (593.349µs) 200 [[kubectl/v1.3.0 (linux/amd64) kubernetes/952e830] 127.0.0.1:33568]`

the json response from ` /apis/batch/v1/jobs?resourceVersion=0` is good (correct namespace and resource path for job/pi). So looks like kubectl is turning around and calling the wrong resource

Also calling `curl http://localhost:8080/apis/batch/v1/namespaces/default/jobs/pi` gives the correct namespace.

cc @janetkuo

**Comment by soltysh** [comment]
@dims the reason for that is that jobs co-exists in both `extensions` and `batch` groups. We left `extensions` for backwards compatibility. If you're able to find some time and fix this, PRs are welcome :)

**Comment by dims** [comment]
@soltysh - Took a while to debug to get the bare minimum change that at least works with `kubectl get job/pi -o yaml`

**Comment by AdoHe** [comment]
@dims @soltysh any updates on this? should I pick this up?

**Comment by dims** [comment]
@AdoHe go for it!

**Comment by soltysh** [comment]
@AdoHe I'd leave it for now, since I'm closing the PR which removes `extensions/v1beta1.Jobs` entirely and the problem should be gone with it.

**Comment by soltysh** [comment]
`extensions/v1beta1.Jobs` were removed in https://github.com/kubernetes/kubernetes/pull/38614.
