### ISSUE TITLE
kubectl run generator for jobs is job/v1beta1

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#22518]
@erictune with your recent changes, where you moved jobs from `extensions/v1beta1` to `batch/v1` shouldn't we update the generator name to `job/v1` at least?

**Comment by bgrant0607** [comment]
@soltysh @erictune We should still support the old generator version as long as extensions/v1beta1 job is still supported. Please add a new generator rather than modify the old one.

**Comment by AdoHe** [comment]
we already have `JobV1Beta1`, maybe we should add a `JobV1`

**Comment by soltysh** [comment]
@erictune, I've looked into this issue, currently all our generators use the internal types. Should I use batch/v1 for this particular case? 
@bgrant0607 shouldn't all our generators use the actual versioned objects rather then internal, in the first place?

**Comment by bgrant0607** [comment]
@soltysh Yes, kubectl in general should not use internal. #3955

Please create a "job/v1". There will be other APIs in the batch API group.

Note that the generator version doesn't map 1-to-1 with API version. If we changed what the generator produced by default without changing the API version, we'd still need to add a new generator version.

**Comment by soltysh** [comment]
Ok, thx. Will do.

**Comment by davidopp** [comment]
ping @soltysh -- we're getting very close to closing 1.2

**Comment by soltysh** [comment]
I'll try to prepare a PR later today. Sorry was quite busy that last few
days.

**Comment by bgrant0607** [comment]
@soltysh Thanks. This needs to be done by tomorrow to get into 1.2.
