### ISSUE TITLE
AWS: Need a 1.1 -> 1.2 upgrade routine

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22535]
We need a way to upgrade from 1.1 to 1.2.  In 1.2 we're using the same scripts & up procedure as GCE, so future upgrades should be cleaner (tracking that as #22534), but getting from 1.1 to 1.2 may be messy.  We need some sort of procedure/script.

**Comment by drora** [comment]
great! +1
really expecting that...

**Comment by justinsb** [comment]
Yes .. worked on it this weekend & continuing working on it today.  1.2 => >1.2 should be easier because we're on the "standard" GCE approach now, but 1.1 => 1.2 is harder sadly...

**Comment by justinsb** [comment]
Very early preview available here:
https://github.com/kopeio/kope/blob/master/UPGRADE.md

Still in progress, but tested on my clean clusters.

If anyone has a non-prod cluster & is feeling bold enough to be the first, please find me on slack and I will go through it with you to answer or fix anything that comes up :-)

I would like to put this into contrib or something, but need faster iteration at this stage...

**Comment by willmore** [comment]
Hi @justinsb  - any updates on this?

We're planing to make the leap with our 1.1 clusters, and were wondering if we should wait for a "supported" process.

**Comment by justinsb** [comment]
Coming very soon, via upup!  Just grappling with the fact that we didn't save the CA key in kube-up (on any platform), so have to issue a new one and keep the old one around I think.

**Comment by justinsb** [comment]
"upup" became kops.  I recommend kops as the natural successor: the ease-of-use of kube-up without many of its shortcomings.  Closing as we have an option now (use kops per https://github.com/kubernetes/kops/blob/master/docs/upgrade_from_k8s_12.md) and we're not going to be making further changes to kube-up.
