### ISSUE TITLE
Add timeout to http.Client used for componentstatus

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#22540]
As reported in #22231, the backends can get into a state (somehow) where our connection attempt just hangs. We should timeout relatively quickly in that case, like 5s or 10s. Right now the global timeout handler triggers (causing us to leak a goroutine).

**Comment by AdoHe** [comment]
Seems I have extra bandwidth, would take it in the next-candidate.

**Comment by AdoHe** [comment]
@lavalamp IIUC seems we already have timeout on http.Client [https://github.com/kubernetes/kubernetes/blob/master/pkg/probe/http/http.go#L48](https://github.com/kubernetes/kubernetes/blob/master/pkg/probe/http/http.go#L48) and the default probeTimeout is `time.Minute`

**Comment by lavalamp** [comment]
@AdoHe Oh! The problem is that our global timeout is also a minute. So maybe we just need to reduce that timeout to something less. (10s? 30s?)

**Comment by AdoHe** [comment]
@lavalamp this is considerable, will do this in the next-candidate.

**Comment by AdoHe** [comment]
@lavalamp IIUC `client ---> apiserver ---> components servers`, the `global timeout` is used at phase one(client->apiserver), the `probe timeout` is used at phase two(apiserver-components servers), and now both of them are a minute, definitely we need just to reduce the global timeout to some value acceptable, for me 30s is ok.

**Comment by lavalamp** [comment]
No-- the global timeout *must* be longer than any other timeout.

**Comment by AdoHe** [comment]
I must hang my head, definitely the global timeout must be longer than any other timeout.

**Comment by lavalamp** [comment]
No worries, that's what I'm here for :)

**Comment by AdoHe** [comment]
This can be closed.
