### ISSUE TITLE
Daemonsets are forever

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#22545]
Two nodes went away as I updated the instances, but they still appear and, more importantly/confusingly, their daemonset pods are still in Running state. 

```
$ fleetctl list-machines
MACHINE         IP              METADATA
729947b9...     10.0.12.180     role=node
a0883347...     10.0.8.4        instance=m0,role=master
$ kubectl get nodes
NAME                          STATUS                     AGE
ip-10-0-10-222.ec2.internal   NotReady                   2d
ip-10-0-12-147.ec2.internal   NotReady                   1d
ip-10-0-12-180.ec2.internal   Ready                      17m
ip-10-0-8-4.ec2.internal      Ready,SchedulingDisabled   2d
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                    READY     STATUS        RESTARTS   AGE
kube-system   fluentd-logging-2gxb1   1/1       Running       0          1d
kube-system   fluentd-logging-33y2f   1/1       Running       0          1d
kube-system   fluentd-logging-b1yuv   1/1       Running       0          17m
kube-system   fluentd-logging-o9hvp   1/1       Running       0          1d
```

There are only two instances and thus two daemons up, not four.
I understand the rationale for not killing the pods outright, but is there a timeout after which they change state or perhaps the nodes do?

My concern is twofold:
 1. `Running` is a lie. Things will be confusing for monitoring/accounting/troubleshooting purposes.
 1. State about pods and nodes is kept around for a long time. Imagine someone using DaemonSets on a pool of EC2 spot instances...

**Comment by bgrant0607** [comment]
@therc I agree that Running is misleading. They should be NotReady or something similar.

Our current node timeout is 5 minutes -- long enough for nodes to reboot, for instance. Once we're able to control this timeout on a per-pod basis (#1574), I plan to reduce this default.

cc @mikedanese @madhusudancs

**Comment by therc** [comment]
Hours later, the nodes are still there, according to the API Server. Perhaps because of the Running pods?

**Comment by mikedanese** [comment]
@therc if you kubectl delete node {node} for the nodes they are on, they will go away i think. only kubelet is allowed to say whether the nodes are running or not. Hopefully the pods have the not ready condition :). Without the nodes being deleted from the api, the master thinks there is a network partion and has no way to know whether the pods are running or not. I think surfacing Unkown, condition in the api would be a good idea here.

@mml @davidopp this is the "no evict" stuff we added to the node controller.

**Comment by therc** [comment]
In my case, the node is NotReady because the cloud provider says it isn't there. I think this is one case where we could override/augment what the kubelet says, i.e. it's more clear cut than just a potential network partition.

I deleted one of the nodes with kubectl and the four pods are still there, five minuts later. I verified that all four are supposed to be on different machines, two of which are missing.

About the other missing machine, from controller-manager:
```
Recording Deleting Node ip-10-0-12-147.ec2.internal because it's not present according to cloud provider event message for node ip-10-0-12-147.ec2.internal
Deleting node ip-10-0-12-147.ec2.internal is delayed while pods are evicted
```

**Comment by mikedanese** [comment]
Ok that's not good. If i get my way and we do https://github.com/kubernetes/kubernetes/issues/20497#issuecomment-190473498, this will be true for all pods, not just pods created by daemonsets. We should figure out how we want to handle this.

**Comment by davidopp** [comment]
Oh I see what's going on.

We broke this code
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L394-L408
when we made DaemonSet pods un-evictable, i.e.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L788-L792

I think the easiest fix is to change NodeController.hasPods() to ignore unevictable pods (currently only DaemonSet, unless I'm mistaken).

We also need to make sure we will delete all the pods when we delete a node, even if some of the pods are un-evictable.

We need to fix this for 1.2.

cc/ @mml

**Comment by gmarek** [comment]
Why exactly we made Daemons un-evictable? I'm getting worried by the amount of special cases to handle during machine drain: I thought that only mirror pods are special (and I believe there's a discussion on how special they are) and we made Daemons special as well.

Is there a strong reason why we're doing it? If the system decides that the Node is unhealthy and need to be drained, or user wants to drain a machine I see no reason why we should keep anything running on it (except system stuff: kubelet, docker, sshd).

**Comment by mikedanese** [comment]
There are two special cases that we did for damonset pods and we did them for different reasons:

1. We made drain ignore daemonset pods. If a daemonset is deleted from a node during a drain, it's immediately recreated. Drain uses the unschedulable bit which daemonset ignores.

2. We made Daemon sets non evicatable. We are special casing this until we have a general purpose forgiveness api (#1574). We want to run kube-proxy and monitoring (fluentd) in a daemonset. This is not feasible if they get evicted when the node is NotReady.

**Comment by mikedanese** [comment]
We need to verify if #22336 fixed this.

**Comment by therc** [comment]
Rebuilding binaries...

**Comment by mikedanese** [comment]
The node does get deleted and the pods are deleted but the daemonset controller immediately recreates them (probably because of node store in the daemonset controller is eventually consistent). The pods stay in pending because the node doesn't exist. Looks like we don't enqueue a daemonset update when a node is deleted but more imporantly daemonsetcontroller.manage() doesn't handle daemonset pods that are on nodes that don't exist.

**Comment by therc** [comment]
That's what I noticed, too. At least now the daemons show as pending.

I also got into a state where I had two daemons on the same node. I think this might have started before I started the new binary. As long as I killed the newer pod, it would get reincarnated. Killing the older of the two (which had been up for longer than the new binary) left me with just one daemon on the node.

I'm about to whack more moles and see if anything else unusual occurs.

**Comment by therc** [comment]
We're lucky. I have two daemons on each node and, although I corrected the first, the second one still has a duplicate. On the same machine as the other duplicate daemon (so the node had four daemons running instead of two), even. Before I clean things up, anything I should probe?

**Comment by mikedanese** [comment]
```
kubectl get no,po,ds -o json
```

would be very helpful and might as well backup the logs of the controller-manager

**Comment by mikedanese** [comment]
I'm testing #22667 as a solution to the first reported issue. I will start to look into the new issue after.

**Comment by mikedanese** [comment]
This code is meant to catch  the case you are seeing. Not sure why it isn't. https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/controller.go#L471-L477,

**Comment by mikedanese** [comment]
Check that the labels and the selectors match and it's not a config error would be my first thing :)

I manually verified #22667 and it fixed the issue

**Comment by therc** [comment]
Actually, the node no longer exists, but its pod CIDR has been recycled. I assumed that the pod IP being equal meant that they were on the same machine, but that's not the case:

```
Node:           ip-10-0-31-206.ec2.internal/10.0.31.206
IP:             10.68.8.2
Node:           ip-10-0-28-220.ec2.internal/10.0.28.220
IP:             10.68.8.2
```

**Comment by therc** [comment]
I cherry-picked #22667 and it got rid of the pending pods.

**Comment by mikedanese** [comment]
@therc Thanks for reporting all these daemonset issues before we go to release!

**Comment by therc** [comment]
Thank you for the fixes and making the feature useful!
