### ISSUE TITLE
[Azure k8s] Can't reach http://10.16.0.1:443 kubernetes service

### ISSUE THREAD

**Issue by theobolo** [kubernetes/kubernetes#22550]
cc @bryk 

Hello everyone,

I've a problem with the getting-started azure guide.
I use that repo to deploy a cluster in Azure, but i've seen that the kubernetes service expose the port 443 on 10.16.0.1.

![sans titre](https://cloud.githubusercontent.com/assets/7281773/13538059/a2e2fe96-e248-11e5-8091-6107db97dd50.png)

A lot of logging services ask to the kubernetes endpoint to discover other pods and application endpoints, like elasticsearch or the dashboard.

My problem is that kubernetes internal endpoint is not accessible from my pods, i always got a 
Connection reset by peer or Unknow SSL error.

I can bypass that problem by using the public kube-master IP (172.18.0.12) on the unsecure port  8080.

I've opened a bash into a pod and tried to curl 10.16.0.1

![sans titre2](https://cloud.githubusercontent.com/assets/7281773/13538163/355f7b1e-e249-11e5-835d-8669c273fac3.png)

BTW the azure getting started guide doesn't include the cert generation for the Kube-API and the kube-controller-manager by default. 

Is it possible to update the azure doc with the last 1.1.8 kubernetes version and with the certs generation ?

**Comment by errordeveloper** [comment]
You should be able to upgrade to `v1.1.8` by changing this line:
```
docs/getting-started-guides/coreos/azure/cloud_config_templates/kubernetes-cluster-main-nodes-template.yml:194:        Environment=KUBE_RELEASE_TARBALL=https://github.com/GoogleCloudPlatform/kubernetes/releases/download/v1.0.1/kubernetes.tar.gz
```

**Comment by errordeveloper** [comment]
TLS is not included in this guide, it would probably take quite a bit of work. However, this guide use Weave Net crypto as well as private network, so you cluster is secure.

**Comment by theobolo** [comment]
I close this issue in view of the coming work on azure integration.
let's see :
https://github.com/colemickens/azkube
