### ISSUE TITLE
round trip tests print a modest 200,000 lines when they fail.

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#22558]
e.g. these commits

https://github.com/kubernetes/kubernetes/commit/14d7263b1289eed6001353696aed9dea85739c9e plus running ./hack/update-all.sh

**Comment by mikedanese** [comment]
http://storage.googleapis.com/public-mikedanese-k8s/serial.log 

cc @smarterclayton @caesarxuchao

**Comment by caesarxuchao** [comment]
I remember this is a bug of the side-by-side printer added by Clayton in 17922. I'll fix it if I can get to it faster than Clayton.

**Comment by smarterclayton** [comment]
We can probably fail early on round trip tests.  Printing more than one
failure was a relic of the very first introduction of it.

If we fail early, only the most recent entry should be shown and the side
by side is useful for figuring out what was broken.

**Comment by smarterclayton** [comment]
I think we can also remove the incremental part where it prints the kind we
are testing - that was a very early debug tool as well.

**Comment by smarterclayton** [comment]
I think this is better now.  Might only be 100k.
