### ISSUE TITLE
Document kubectl run best practices

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22569]
Guidelines for how kubectl run can satisfy:
http://martinfowler.com/bliki/InfrastructureAsCode.html

Off the top of my head:
- Always tag your image with a version-specific tag and don't move that tag to a new version. For example, use :v1234, v1.2.3, r03062016-1-4, or somesuch, rather than :latest.
- If the image is lightly parameterized, capture the parameters in a checked-in script, or at least use --record, to annotate the created objects with the command line.
- If the image is heavily parameterized, definitely check in the script.
- If features are needed that are not expressible via kubectl run flags, switch to config files checked into source control. Those files could be created using kubectl run --edit followed by kubectl get --export.
- Pin to a specific generator version, such as kubectl run --generator=deployment/v1beta1

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by bgrant0607** [comment]
```
resource=$(kubectl run ... -o name)
#if that didn't fail...
kubectl expose $(resource)
```

**Comment by janetkuo** [comment]
Once we have this doc, link to it in `kubectl run --help`
