### ISSUE TITLE
etcd server appears twice in componentstatuses

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#22581]
Moved this from #22231 since it's no longer related.

I noticed that on `v1.1.8`, I had only a single etcd instance listed in componentstatuses, but on `master` had two (despite that I'm only running a single instance). I've added code to `pkg/master/master.go` to print the list of endpoints that it is going to health check during a call to componentstatuses. 

My etcd is configured:

```
advertise-client-urls: "http://127.0.0.1:2379,http://10.0.1.4:2379"
listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
```

In `v1.1.8`:

```
"etcd-0" = { "127.0.0.1" .... }
"controller-manager" = { "127.0.0.1" .... }
"scheduler" = { "127.0.0.1" .... }
```

In `master`:

```
"etcd-0" = { "10.0.1.4" .... }
"etcd-1" = { "127.0.0.1" .... }
"controller-manager" = { "127.0.0.1" .... }
"scheduler" = { "127.0.0.1" .... }
```

Even though "10.0.1.4" _is_ "127.0.0.1".

Is this expected?

(This came to my attention because I originally was advertising a third etcd endpoint that was unreachable and was causing componenstatuses check to timeout. I just ran it again with `master` to confirm and I get a third etcd: `"etcd-2" = { "kube-20160304-112303.westus.cloudapp.azure.com" ... }"`)

cc: @lavalamp @davidopp

**Comment by davidopp** [comment]
cc/ @wojtek-t

**Comment by wojtek-t** [comment]
Isn't is the second etcd that we use to store events?

**Comment by colemickens** [comment]
That was mentioned by @lavalamp as well, but I'm afraid that I don't really understand what that means.

For another piece of data, if I change `etcd2`'s advertise URLs to only include a single URL, then the behavior returns to looking the same as with `v1.1.8` -- the second etcd entry in componentstatuses goes away. 

This again makes me wonder if it's expected that there is a health check per-etcd-advertise-URL, rather than per-etcd-instance, since it wasn't that way in `v1.1.8`.

**Comment by lavalamp** [comment]
We run two separate etcd clusters, one for everything but events, and one
for events. So this explains why there's two.

The big question is why one is 127.x.x.x and one is 10.x.x.x. They should
both be on 127.0.0.1.

**Comment by colemickens** [comment]
If that's the case, why are there then three entries whenever I add a third announce URL to my etcd configuration? I suspect there would be `n` `etcd-n` entries if I were to add `n` values to etcd's `announce-urls`.

I'm still confused how there are "two separate etcd clusters" whenever I only run a single instance of etcd on a single machine in my cluster. Terminology issue on my part?
