### ISSUE TITLE
MESOS: km inherits junk flags from cadvisor

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#22584]
When I run `km scheduler --help`, `km proxy --help`, etc., I'm getting the following:

```
--global_housekeeping_interval=1m0s: Interval between global housekeepings
--ir-data-source="influxdb": Data source used by InitialResources. Supported options: influxdb, gcm.
```

and a dozen others that came with cadvisor. These flags don't make any sense here. Probably the only place they would make sense is `km scheduler` so that it can pass these flags to `km executor` to start cadvisor.

Is there anyone looking at why these cadvisor flags are getting inherited? And also are there any other junk flags other than the ones from cadvisor?

**Comment by huang195** [comment]
cc @jdef

**Comment by jdef** [comment]
- cadvisor flag leakage is a known problem #19432
- stretchr/testify/mock is probably leaking flags as well; several upstream PR's have been filed/merged for this. not sure if work is complete here. there's likely still some cleanup left for k8sm

**Comment by huang195** [comment]
Closing this as this is a known issue. Not much can be done until the cleanup work is done in these other packages.
