### ISSUE TITLE
v1.2.0-alpha8: performance regression

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#22585]
Moving the discussion from slack to here for better tracking.

I'm running a simple benchmark that just sequentially creates replicasets. Each replicaset has only 1 pod (busybox). My cluster has 1 master and 3 slave nodes. Each node has 4 cores and 8 GB of memory. When using v1.2.0.alpha-8, I see several problems in performance:

1. There's a high variance in pod creation time
2. Even in the beginning of my benchmark when it's just a clean slate, it takes roughly 10 seconds to create a single pod. (And it goes up when more pods are created)

*I understand --max-pods is default to 110, and I'm overriding this parameter to be able to run a larger number of pods per node here, but even without reaching anywhere near this max number, I'm getting poor performance.*

**Comment by huang195** [comment]
![vanilla-release-1 2](https://cloud.githubusercontent.com/assets/8008677/13548205/c5d28852-e2b8-11e5-97d7-f21359625af2.png)

**Comment by huang195** [comment]
@Random-Liu pointed out this issue: https://github.com/kubernetes/kubernetes/issues/20836
After changing `--image:busybox` to `--image:busybox:1` in my benchmark, it did remove some of the variance. 

![vanilla-master-1500-container-haproxy-tls](https://cloud.githubusercontent.com/assets/8008677/13548214/1b30e97e-e2b9-11e5-956e-78e7d8211ecc.png)

**Comment by huang195** [comment]
But the problem of taking 10 seconds to create pod at low pod count still remains.

cc @Random-Liu @yujuhong @timothysc @kubernetes/sig-scalability

**Comment by timothysc** [comment]
You're likely hitting controller loop sync intervals, vs. bulk (wide-rc) operations.

**Comment by Random-Liu** [comment]
@huang195  In the current implementation, if container is `running`, kubelet should have seen this container in `docker ps` and `docker inspect`.

I commented out the connectivity check and run you test with HEAD:
* I find that it usually takes 1s~3s for the container to become `running`, which I think is reasonable.
* Sometimes it may take 10s or more. When that happens I always see that kubectl keeps complaining that `can't find such pod`. Now `kubectl run` will create a `Deployment`, looks like it takes some time before really creating the pod.

As for the connectivity, because your script ssh into the container and check the port, I've no idea how long that we take. I'll do more test about that. :)

I can't see the black points clearly. In your result, how long does it take for the container to become `running`?

**Comment by huang195** [comment]
> You're likely hitting controller loop sync intervals, vs. bulk (wide-rc) operations.
@timothysc can you point me somewhere in the code or documentation on these as I am not sure how these could impact the result, thanks!

**Comment by huang195** [comment]
@Random-Liu 

> I find that it usually takes 1s~3s for the container to become running, which I think is reasonable.

Are you getting these from the event stream between container "created" and "started" events?

> I think that is because you are using kubectl run to start pod, now kubectl run only creates Deployment and return, after that it may take some time before really creating the pod. 

Oh, can this be the reason that release-1.2 has longer latency to fully create a pod? If I understand you correctly, something is creating pods from deployments asynchronously, which adds latency. 

> I can't see the black points clearly. In your result, how long does it take for the container to become running?

This is because in most cases black and purple dots overlap. No worry about ssh or purple dots, as black dots represent the time when a pod enters "running" state, and this time imo takes much longer than release-1.1.

**Comment by Random-Liu** [comment]
@huang195 
> Are you getting these from the event stream between container "created" and "started" events?

No. I just used your script https://github.com/huang195/kube-test. It usually just takes 1-3 seconds before the container become `running`.

> Oh, can this be the reason that release-1.2 has longer latency to fully create a pod? If I understand you correctly, something is creating pods from deployments asynchronously, which adds latency.

Yeah, that's what I mean. I asked @lavalamp about this last week. IIUC, the pod is created asynchronously when using `kubelet run`.

**Comment by huang195** [comment]
@Random-Liu Are you saying in your environment if you run my script and you plot the result in a graph, the black dots will be in 1-3 seconds range?

I also modified my script to run `kubectl create -f` to create just pods instead of `kubectl run` to create deployments, and unfortunately, I'm getting the same result.

**Comment by yujuhong** [comment]
@huang195, I believe @Random-Liu used a regular GCE e2e cluster.

We didn't see the severe regression you observed in our test environment.  Could you share your environment -- OS, cloud, and any custom flags, etc? 

It seems like pod startup time is generally long in your environment, even when creating pods regularly (~10s). If you see a pod that is slow to start, perhaps you can run `kubectl describe pod` to see the events to help figure out the bottleneck. Alternatively, if you have the kubelet.log file with logging verbosity >= 4, you can share it with us and we can reconstruct the timeline of how kubelet process this specific pod. It might also worth taking a look at the log to see if there are other obvious errors.

**Comment by Random-Liu** [comment]
@huang195 Yeah, the black dots (`$trun` in your script) will be in 1-3 seconds range.

**Comment by huang195** [comment]
@yujuhong @Random-Liu 

I'm using Ubuntu 14.04, running on a private cluster of 1 master and 3 slaves. Each node has 4 cpus and 8 gb of memory.

Here are the flags I'm using to start each of the components:
```shell
kube-apiserver \
  --bind-address=${KUBERNETES_MASTER_IP} \
  --insecure-bind-address=${KUBERNETES_MASTER_IP} \
  --etcd-servers=http://${KUBERNETES_MASTER_IP}:4001 \
  --service-cluster-ip-range=10.10.10.0/24 \
  --insecure-port=8080 \
  --secure-port=8443 \
  --v=0 >apiserver.log 2>&1 &
sleep 3
kube-controller-manager \
  --kubeconfig=/root/kubernetes/controller-manager-kubeconfig \
  --v=0 >controller.log 2>&1 &
kube-scheduler \
  --kubeconfig=/root/kubernetes/scheduler-kubeconfig \
  --v=0 >scheduler.log 2>&1 &
```

The kubeconfig files are minimalistic ones that just have namespace and kubernetes master ip:port info.

On the slave node, I'm using:
```shell
kubelet --event-qps=5000 --kube-api-qps=5000 --api-servers=http://10.143.100.209:8080 --max-pods=500 --kubeconfig=/root/kubernetes/kubelet-kubeconfig --v=10 >kubelet.log 2>&1 &
```

One thing I found strange is that when I'm looking at the event stream of a pod, it looks like it takes the kubelet 6-7 seconds from creating a container to starting it. See below:

```
Events:
  FirstSeen     LastSeen        Count   From                                    SubobjectPath           Type            Reason                  Message
  ---------     --------        -----   ----                                    -------------           --------        ------                  -------
  13s           13s             1       {default-scheduler }                                            Normal          Scheduled               Successfully assigned cont3-333702030-6jxkv to rsch-dal09-haih-k8sm-3
  13s           13s             2       {kubelet rsch-dal09-haih-k8sm-3}                                Warning         MissingClusterDNS       kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  13s           13s             1       {kubelet rsch-dal09-haih-k8sm-3}        spec.containers{cont3}  Normal          Pulled                  Container image "busybox:1" already present on machine
  13s           13s             1       {kubelet rsch-dal09-haih-k8sm-3}        spec.containers{cont3}  Normal          Created                 Created container with docker id 32d37f7bd710
  6s            6s              1       {kubelet rsch-dal09-haih-k8sm-3}        spec.containers{cont3}  Normal          Started                 Started container with docker id 32d37f7bd710
```

**Comment by Random-Liu** [comment]
> One thing I found strange is that when I'm looking at the event stream of a pod, it looks like it takes the kubelet 6-7 seconds from creating a container to starting it.

@huang195 That is really wired...Do you still have the kubelet log?

**Comment by dchen1107** [comment]
@huang195 I couldn't reproduce the performance regression issue you reported here. Which docker version you are using? Also can you try docker run directly on the node to see if the performance regression is caused by docker itself?

**Comment by huang195** [comment]
@Random-Liu I've checked in a kubelet.log file in the repo that contains benchmark script that I shared with you before.

**Comment by yujuhong** [comment]
@huang195 

The kubelet.log seems ok, even though it's full of `MissingClusterDNS` events. From what I've seen, there is a gap between container creation and start, with no meaningful messages in between. I'd guess that starting container itself is slow on your node.

You can double check this (high docker latency) by accesing kubelet metrics/ endpoint:
On the node:  `curl --insecure https://localhost:10250/metrics`
Through apiserver proxy: `http://<apiserver_IP>:8080/api/v1/proxy/nodes/<node_name>:10250/metrics`
E.g.,
```
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.5"} 119023
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.9"} 119023
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.99"} 119023
```
The metrics, IIRC, uses a rolling window of  N minutes, so you may want to check during or right after running the script.

@dchen1107's https://github.com/kubernetes/kubernetes/issues/22585#issuecomment-193521923 is probably the most relevant.
You should check your docker version and try running the container directly on your node to see if it's slow.

**Comment by huang195** [comment]
@dchen1107 Is there a way to run the exact `docker` command that kubelet uses to run the different containers within a pod? In my environment, if I just run a container using `docker run`, it seems to start within 1 or 2 seconds as normal. 

Also, I'm using 1.9.1 version of Docker.

**Comment by huang195** [comment]
@yujuhong Thanks for your suggestion about metrics. I will check that later today. What kind of puzzles me is I'm running release-1.1 and release-1.2.alpha8 on the same cluster of machines. How come release-1.1 performs so much better? If the problem is due to Docker, won't this impact both releases?

**Comment by dchen1107** [comment]
@huang195 If it is not sensitive, could you please share your podSpec/containerSpec? Or you can convert your container create & start to json commands to docker directly. We made some compatibility changes with docker remote API on both creation & start requests in this release, for example, https://github.com/kubernetes/kubernetes/pull/20842  I am wondering if some of those changes cause this regression with your containerSpec?

**Comment by huang195** [comment]
@yujuhong Here's the metrics information after starting 15 pods on a single node. Quite a few docker operations take an abnormal amount of time.

```
kubelet_docker_operations_latency_microseconds{operation_type="create_container",quantile="0.5"} 363618
kubelet_docker_operations_latency_microseconds{operation_type="create_container",quantile="0.9"} 383721
kubelet_docker_operations_latency_microseconds{operation_type="create_container",quantile="0.99"} 396123
kubelet_docker_operations_latency_microseconds_sum{operation_type="create_container"} 1.0983657e+07
kubelet_docker_operations_latency_microseconds_count{operation_type="create_container"} 30
kubelet_docker_operations_latency_microseconds{operation_type="info",quantile="0.5"} NaN
kubelet_docker_operations_latency_microseconds{operation_type="info",quantile="0.9"} NaN
kubelet_docker_operations_latency_microseconds{operation_type="info",quantile="0.99"} NaN
kubelet_docker_operations_latency_microseconds_sum{operation_type="info"} 141468
kubelet_docker_operations_latency_microseconds_count{operation_type="info"} 1
kubelet_docker_operations_latency_microseconds{operation_type="inspect_container",quantile="0.5"} 1411
kubelet_docker_operations_latency_microseconds{operation_type="inspect_container",quantile="0.9"} 10594
kubelet_docker_operations_latency_microseconds{operation_type="inspect_container",quantile="0.99"} 134543
kubelet_docker_operations_latency_microseconds_sum{operation_type="inspect_container"} 1.360927e+06
kubelet_docker_operations_latency_microseconds_count{operation_type="inspect_container"} 176
kubelet_docker_operations_latency_microseconds{operation_type="inspect_image",quantile="0.5"} 1113
kubelet_docker_operations_latency_microseconds{operation_type="inspect_image",quantile="0.9"} 9908
kubelet_docker_operations_latency_microseconds{operation_type="inspect_image",quantile="0.99"} 10184
kubelet_docker_operations_latency_microseconds_sum{operation_type="inspect_image"} 117143
kubelet_docker_operations_latency_microseconds_count{operation_type="inspect_image"} 30
kubelet_docker_operations_latency_microseconds{operation_type="list_containers",quantile="0.5"} 550
kubelet_docker_operations_latency_microseconds{operation_type="list_containers",quantile="0.9"} 4216
kubelet_docker_operations_latency_microseconds{operation_type="list_containers",quantile="0.99"} 6.711771e+06
kubelet_docker_operations_latency_microseconds_sum{operation_type="list_containers"} 2.68483414e+08
kubelet_docker_operations_latency_microseconds_count{operation_type="list_containers"} 126810
kubelet_docker_operations_latency_microseconds{operation_type="list_images",quantile="0.5"} 34920
kubelet_docker_operations_latency_microseconds{operation_type="list_images",quantile="0.9"} 56928
kubelet_docker_operations_latency_microseconds{operation_type="list_images",quantile="0.99"} 76678
kubelet_docker_operations_latency_microseconds_sum{operation_type="list_images"} 2.76538296e+08
kubelet_docker_operations_latency_microseconds_count{operation_type="list_images"} 7111
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.5"} 294469
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.9"} 7.341933e+06
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.99"} 7.37394e+06
kubelet_docker_operations_latency_microseconds_sum{operation_type="start_container"} 1.09818241e+08
kubelet_docker_operations_latency_microseconds_count{operation_type="start_container"} 30
kubelet_docker_operations_latency_microseconds{operation_type="version",quantile="0.5"} 396
kubelet_docker_operations_latency_microseconds{operation_type="version",quantile="0.9"} 710
kubelet_docker_operations_latency_microseconds{operation_type="version",quantile="0.99"} 123657
kubelet_docker_operations_latency_microseconds_sum{operation_type="version"} 6.775381e+07
kubelet_docker_operations_latency_microseconds_count{operation_type="version"} 131393
```

**Comment by huang195** [comment]
@dchen1107 This is the exact command I'm using to sequentially starting pods and measure the time it takes to start each.

```shell
    kubectl run $containerName --image=busybox:1 --limits="cpu=10m,memory=8Mi" --port=3000 --command -- httpd -f -p 3000
```

Is there a way to translate this `kubectl` command to its `docker` commands so I can run them manually to see if I can reproduce this problem by hand? Specifically I'd like to create/start infrastructure container and then create/start the busybox container, with all the runtime parameters that kubelet uses to create/start them.

**Comment by huang195** [comment]
@yujuhong Just for comparison, here's the metrics information using HEAD of release-1.1. It looks much better. Again, I'm using the same command to start Kubernetes, using the same benchmark, and using the same cluster of nodes.

```
kubelet_docker_operations_latency_microseconds{operation_type="create_container",quantile="0.5"} 413494
kubelet_docker_operations_latency_microseconds{operation_type="create_container",quantile="0.9"} 444542
kubelet_docker_operations_latency_microseconds{operation_type="create_container",quantile="0.99"} 732635
kubelet_docker_operations_latency_microseconds_sum{operation_type="create_container"} 3.0089988e+07
kubelet_docker_operations_latency_microseconds_count{operation_type="create_container"} 70
kubelet_docker_operations_latency_microseconds{operation_type="info",quantile="0.5"} 148001
kubelet_docker_operations_latency_microseconds{operation_type="info",quantile="0.9"} 148001
kubelet_docker_operations_latency_microseconds{operation_type="info",quantile="0.99"} 148001
kubelet_docker_operations_latency_microseconds_sum{operation_type="info"} 148001
kubelet_docker_operations_latency_microseconds_count{operation_type="info"} 1
kubelet_docker_operations_latency_microseconds{operation_type="inspect_container",quantile="0.5"} 14920
kubelet_docker_operations_latency_microseconds{operation_type="inspect_container",quantile="0.9"} 181997
kubelet_docker_operations_latency_microseconds{operation_type="inspect_container",quantile="0.99"} 318386
kubelet_docker_operations_latency_microseconds_sum{operation_type="inspect_container"} 7.6333961e+07
kubelet_docker_operations_latency_microseconds_count{operation_type="inspect_container"} 1486
kubelet_docker_operations_latency_microseconds{operation_type="inspect_image",quantile="0.5"} 1193
kubelet_docker_operations_latency_microseconds{operation_type="inspect_image",quantile="0.9"} 10113
kubelet_docker_operations_latency_microseconds{operation_type="inspect_image",quantile="0.99"} 91522
kubelet_docker_operations_latency_microseconds_sum{operation_type="inspect_image"} 609859
kubelet_docker_operations_latency_microseconds_count{operation_type="inspect_image"} 71
kubelet_docker_operations_latency_microseconds{operation_type="list_containers",quantile="0.5"} 99139
kubelet_docker_operations_latency_microseconds{operation_type="list_containers",quantile="0.9"} 437224
kubelet_docker_operations_latency_microseconds{operation_type="list_containers",quantile="0.99"} 1.8798494e+07
kubelet_docker_operations_latency_microseconds_sum{operation_type="list_containers"} 3.15485671e+08
kubelet_docker_operations_latency_microseconds_count{operation_type="list_containers"} 840
kubelet_docker_operations_latency_microseconds{operation_type="list_images",quantile="0.5"} 48574
kubelet_docker_operations_latency_microseconds{operation_type="list_images",quantile="0.9"} 48574
kubelet_docker_operations_latency_microseconds{operation_type="list_images",quantile="0.99"} 48574
kubelet_docker_operations_latency_microseconds_sum{operation_type="list_images"} 97695
kubelet_docker_operations_latency_microseconds_count{operation_type="list_images"} 2
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.5"} 294412
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.9"} 319574
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.99"} 437705
kubelet_docker_operations_latency_microseconds_sum{operation_type="start_container"} 2.0627196e+07
kubelet_docker_operations_latency_microseconds_count{operation_type="start_container"} 70
kubelet_docker_operations_latency_microseconds{operation_type="stop_container",quantile="0.5"} 1.0140625e+07
kubelet_docker_operations_latency_microseconds{operation_type="stop_container",quantile="0.9"} 3.7971578e+07
kubelet_docker_operations_latency_microseconds{operation_type="stop_container",quantile="0.99"} 3.9666497e+07
kubelet_docker_operations_latency_microseconds_sum{operation_type="stop_container"} 1.923395374e+09
kubelet_docker_operations_latency_microseconds_count{operation_type="stop_container"} 86
kubelet_docker_operations_latency_microseconds{operation_type="version",quantile="0.5"} 3028
kubelet_docker_operations_latency_microseconds{operation_type="version",quantile="0.9"} 121713
kubelet_docker_operations_latency_microseconds{operation_type="version",quantile="0.99"} 213091
kubelet_docker_operations_latency_microseconds_sum{operation_type="version"} 1.5214e+06
kubelet_docker_operations_latency_microseconds_count{operation_type="version"} 40
```

**Comment by yujuhong** [comment]
@huang195, the container start takes unusually long in your cluster, which matched our theory.
```
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.5"} 294469
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.9"} 7.341933e+06
kubelet_docker_operations_latency_microseconds{operation_type="start_container",quantile="0.99"} 7.37394e+06
```
We did slightly change the container create/start code to prepare for docker upgrade (#20842), but I fail to see how that PR might've caused this.
If you could bisect and confirm that this PR is the cause, we'll have more to go on...

**Comment by Random-Liu** [comment]
@huang195 We couldn't reproduce the regression in our environment. Could you please tell us your test environment? Or try again with kubelet version before #20842?

**Comment by huang195** [comment]
@yujuhong I built from 1 commit earlier than #20842, and I'm getting the same result, so something else is causing this problem.

**Comment by yujuhong** [comment]
@huang195, again, it's kind of hard to debug without the knowing testing environment :-) 
Another wild guess will be #20873, where we upgraded the go-dockerclient. 
The exact configs kubelet uses to create a docker container should also be apparent in /var/lib/docker/containers/<container_ID>/*.json

**Comment by huang195** [comment]
@Random-Liu @yujuhong I posted my testing environment information earlier:
>I'm using Ubuntu 14.04, running on a private cluster of 1 master and 3 slaves. Each node has 4 cpus and 8 gb of memory.
>Also, I'm using 1.9.1 version of Docker.

If there's anything else that might help, please let me know.

**Comment by huang195** [comment]
It looks like #19900 is the culprit here since I'm using `kubectl run ... --limits="cpu=10m,memory=8Mi" ...` and by default `--cpu-cfs-quota=true` since that PR, whereas it was set to `false` in release-1.1. As a result, `docker start` works under this cpu constraint and starts very slowly. It's mentioned that 

>Our Container VM base image still does not have hardcapping enabled by default

which could be the reason you cannot reproduce the problem I was seeing even running the same benchmark script. Setting `--cpu-cfs-quota=true` by default is kind of confusing as it could have a such a big impact on performance and there's no easy way to track it down. 

Thanks @Random-Liu @yujuhong @dchen1107 for your help. I will close this now.

**Comment by yujuhong** [comment]
@huang195, thanks for the thorough debugging!

According to https://github.com/kubernetes/kubernetes/pull/19900#issuecomment-173747795, setting "requests" instead of "limits" is better for your performance benchmark. 

In short, kubernetes v1.2+ enforces hard cpu limits. Setting small cpu limits for containers may cause very slow container start (e.g., 7s). @kubernetes/sig-node, in case anyone runs into the same issue.

**Comment by Random-Liu** [comment]
@huang195 Thanks for digging it out!

**Comment by dchen1107** [comment]
@huang195, great that you found the culprit here. 

For kubernetes 1.2 release, we enable cpu cfs quota by default for qos. But unfortunately the kernel in our containerVM image isn't compiled with CONFIG_CFS_BANDWIDTH, so that we introduced a warning message to NodeStatus if CONFIG_CFS_BANDWIDTH is not on:

```
conditions:
   - lastHeartbeatTime: 2016-03-11T18:25:56Z
     lastTransitionTime: 2016-03-10T20:07:03Z
     message: kubelet has sufficient disk space available
     reason: KubeletHasSufficientDisk
     status: "False"
     type: OutOfDisk
   - lastHeartbeatTime: 2016-03-11T18:25:56Z
     lastTransitionTime: 2016-03-10T20:07:50Z
     message: 'kubelet is posting ready status. WARNING: CPU hardcapping unsupported'
     reason: KubeletReady
     status: "True"
     type: Ready
```

**Comment by huang195** [comment]
@Random-Liu Right, that's what I ended up doing.
@dchen1107 I never paid attention to those message before, thanks for the heads up.
