### ISSUE TITLE
MESOS: km proxy cannot take kubeconfig as a parameter

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#22583]
After configuring a Kubernetes-on-Mesos environment using TLS, each component is talking to the API server via HTTPS, I noticed that there were a lot of error messages like the following in API server's log:

```
{"log":"I0305 03:00:18.806312       1 logs.go:41] http: TLS handshake error from 172.17.0.3:48681: remote error: bad certificate\n","stream":"stderr","time":"2016-03-05T03:00:18.806549845Z"}
```

The cluster appears in a working condition, e.g., I can create pods, rs, etc. After further investigation, it appears the culprit of all these error messages is the `km proxy`. This is due to `km minion` not setting `--kubeconfig` flag when starting `km proxy`.

There are several approaches to solve this problem:
1. Pass `--kubelet-kubeconfig` that `km scheduler` passes to `km executor` to also `km proxy`. 
2. Add another flag `--proxy-kubeconfig` to `km scheduler` so it can pass it to `km proxy`

The second approach seems more "complete". In theory, we could set up different certificate for kubelet and proxy. But if we don't add this flag, we can't do that. The flags `--kubelet-kubeconfig` and `--proxy-kubeconfig` should be independent of one another.

**Comment by huang195** [comment]
@jdef What do you think?

**Comment by jdef** [comment]
if we picked option 2, what's the default value of the flag? my assumption would be that it defaults to the value of kubelet-kubeconfig; and if that's not specified either, then use the scheduler's kubeconfig

**Comment by huang195** [comment]
In my opinion, the 3 kubeconfig flags should be independent. The reason is when someone is setting up a Kubernetes cluster in standalone mode, the scheduler, kubelet, and proxy are set up separately. And for security reasons, each will likely have a separate certificate and key pair, which will be used in the kubeconfig file. 

If the 3 kubeconfig flags are dependent, I don't know if it makes sense for the kubelet or proxy to use scheduler's kubeconfig. Another complication is if scheduler-kubeconfig and kubelet-kubeconfig are both defined but proxy-kubeconfig is not, should proxy-kubeconfig be set to scheduler-kubeconfig or kubelet-kubeconfig?

**Comment by jdef** [comment]
after giving this more thought I think completely independent flags is the
way to go because it's the most clear thing we can do. it doesn't prevent
someone from using the same config file for all 3, and there's no
complicated defaulting logic.

**Comment by huang195** [comment]
Ok, I will work on this the next few days.
