### ISSUE TITLE
Add Critical builds to Submit Queue E2E Page

### ISSUE THREAD

**Issue by goltermann** [kubernetes/kubernetes#22580]
http://submit-queue.k8s.io/#/e2e lists 8 builds now.  We should add all critical builds to that page.  And it probably makes sense to separate them into two sections: queue blocking and critical builds.

**Comment by spxtr** [comment]
cc @kubernetes/sig-testing

**Comment by spiffxp** [comment]
what currently defines 'critical' vs 'non-critical' ?

**Comment by spxtr** [comment]
The general rule is that it's the oncall's duty to keep critical builds green. Non-critical builds have specific owners to keep track of them. Not all critical builds block the merge queue, but all merge-queue-blockers are in critical builds.

**Comment by spiffxp** [comment]
@david-mcmahon is there a list of 'critical' builds someplace?

**Comment by david-mcmahon** [comment]
'Critical builds' are visible on the (internal) Jenkins instances, but I believe the Jenkins configs at least that define those sections are in the repository.  @ixdy?

**Comment by spiffxp** [comment]
The jenkins configs for each job maybe, but the list of jobs themselves? 

https://github.com/kubernetes/kubernetes/tree/master/hack/jenkins/job-configs

**Comment by eparis** [comment]
see https://github.com/kubernetes/contrib/pull/467 and https://github.com/kubernetes/contrib/pull/470 which get us here. They just need someone new to pick up the ball and run given the recent changes.

**Comment by spxtr** [comment]
This is pretty much done now that there is a non-blocking section.
