### ISSUE TITLE
Ubernetes Lite: Dynamic provisioned volumes are not labeled

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22592]
It appears that dynamically provisioned volumes bypass the labelling admission controller, and so are not labeled with zone information.

**Comment by saad-ali** [comment]
Fix pending: https://github.com/kubernetes/kubernetes/pull/22602

**Comment by saad-ali** [comment]
This issue appears to be a duplicate of https://github.com/kubernetes/kubernetes/issues/22532
Do we need both?

**Comment by bgrant0607** [comment]
Closing in favor of #22532. Reopen if that's wrong.

**Comment by justinsb** [comment]
I don't know what I was doing opening a duplicate issue here... sorry.

**Comment by justinsb** [comment]
Ah - I think this was supposed to be about tags in the EC2 API.  Opened #22792 instead (and PR-ed a fix)
