### ISSUE TITLE
TCP Socket liveness sample

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#22598]
https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/liveness contains application level health-check using HTTP and Container Exec. TCP Socket example configuration file and docs are missing.

For example, there are no links to TCP socket example at: http://kubernetes.io/v1.1/docs/user-guide/walkthrough/k8s201.html#application-health-checking

**Comment by alexandrst88** [comment]
@arun-gupta this works fine for me
```         ports:
           - containerPort: 8080
         livenessProbe:
           tcpSocket:
             port: 8080
           initialDelaySeconds: 180
         readinessProbe:
           tcpSocket:
             port: 8080
           initialDelaySeconds: 10
```

**Comment by spiffxp** [comment]
/sig network

/assign
closing because of working example commented above, and linked PR that adds an example to docs
