### ISSUE TITLE
Dynamic volume provisioning is missing an e2e test

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22590]
There's no e2e test for dynamic volume provisioning AFAICT.

Also, on Ubernetes-Lite, we should verify that a dynamically provisioned volume gets zone labels.

**Comment by saad-ali** [comment]
Definitely needs to be done, and the sooner the better.

@kubernetes/sig-storage @kubernetes/rh-storage: Can someone jump on this. 

Beta/RC for v1.2 are targeted within a week, so if we can get this in and cherry picked, that would be wonderful--if not, this is not a 1.2 blocker.

**Comment by bgrant0607** [comment]
@saad-ali Please add a priority label

**Comment by rootfs** [comment]
I believe @jsafrane is working on these e2e tests.

**Comment by jsafrane** [comment]
Yes, there is a PR since Feb 12: https://github.com/kubernetes/kubernetes/pull/21140

**Comment by saad-ali** [comment]
Thanks @jsafrane. I'll take a look at that PR.

**Comment by saad-ali** [comment]
That PR has been ok'd to merge.
Going to close this issue since it is a duplicate of https://github.com/kubernetes/kubernetes/issues/20564
