### ISSUE TITLE
kubelet high CPU usage after CoreOS upgrade ; failed to ensure docker daemon state

### ISSUE THREAD

**Issue by Alex-Wauters** [kubernetes/kubernetes#22610]
Hi,

we upgraded CoreOS (stable) and rebooted on our kubernetes cluster (using the Azure VM installation scripts with weave), and ever since the CPU usage on the master+node VMs is 95%

Kubelet hits 40% CPU:

kubelet log (similar issues on all nodes): 
`Mar 06 12:45:10 kube-01 kubelet[902]: W0306 12:45:10.544302     902 container_manager_linux.go:278] [ContainerManager] Failed to ensure state of "/docker-daemon": [failed to apply oom score -900 to PID 19451, failed to find container of PID 19438: open /proc/19438/cgroup: no such file or directory, failed to move PID 19438 (in "") to "/docker-daemon", failed to apply oom score -900 to PID 19438]
Mar 06 12:44:13 kube-01 kubelet[902]: E0306 12:44:13.160288     902 kubelet.go:2284] Error updating node status, will retry: node "kube-01" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
Mar 06 12:43:58 kube-01 kubelet[902]: E0306 12:43:58.377153     902 kubelet.go:2284] Error updating node status, will retry: Timeout: request did not complete within allowed duration
Mar 06 12:42:16 kube-01 kubelet[902]: W0306 12:42:09.748998     902 container_manager_linux.go:278] [ContainerManager] Failed to ensure state of "/docker-daemon": [failed to find container of PID 45686: open /proc/45686/cgroup: no such file or directory, failed to move PID 45686 (in "") to "/docker-daemon", failed to apply oom score -900 to PID 45686]
Mar 06 12:40:09 kube-01 kubelet[902]: W0306 12:40:09.446055     902 container_manager_linux.go:278] [ContainerManager] Failed to ensure state of "/docker-daemon": [failed to apply oom score -900 to PID 19809, failed to move PID 19803 (in "/") to "/docker-daemon", failed to apply oom score -900 to PID 19803, failed to find container of PID 19754: open /proc/19754/cgroup: no such file or directory, failed to move PID 19754 (in "") to "/docker-daemon", failed to apply oom score -900 to PID 19754]
Mar 06 12:39:09 kube-01 kubelet[902]: W0306 12:39:09.129784     902 container_manager_linux.go:278] [ContainerManager] Failed to ensure state of "/docker-daemon": [failed to move PID 6902 (in "/system.slice/docker-38f72a4892143f02532836652f706b4440270b18aae5122f3a53f0b0331b2034.scope") to "/docker-daemon", failed to apply oom score -900 to PID 6902]
Mar 06 12:38:39 kube-01 kubelet[902]: E0306 12:38:39.868915     902 kubelet.go:2284] Error updating node status, will retry: node "kube-01" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
Mar 06 12:37:08 kube-01 kubelet[902]: W0306 12:37:08.837940     902 container_manager_linux.go:278] [ContainerManager] Failed to ensure state of "/docker-daemon": [failed to find container of PID 46518: open /proc/46518/cgroup: no such file or directory, failed to move PID 46518 (in "") to "/docker-daemon", failed to apply oom score -900 to PID 46518, failed to move PID 46494 (in "/system.slice/docker-38f72a4892143f02532836652f706b4440270b18aae5122f3a53f0b0331b2034.scope") to "/docker-daemon", failed to apply oom score -900 to PID 46494, failed to find container of PID 46450: open /proc/46450/cgroup: no such file or directory, failed to move PID 46450 (in "") to "/docker-daemon", failed to apply oom score -900 to PID 46450]
Mar 06 12:36:08 kube-01 kubelet[902]: W0306 12:36:08.552753     902 container_manager_linux.go:278] [ContainerManager] Failed to ensure state of "/docker-daemon": [failed to move PID 34299 (in "/system.slice/docker-38f72a4892143f02532836652f706b4440270b18aae5122f3a53f0b0331b2034.scope") to "/docker-daemon", failed to apply oom score -900 to PID 34299, failed to find container of PID 34188: open /proc/34188/cgroup: no such file or directory, failed to move PID 34188 (in "") to "/docker-daemon", failed to apply oom score -900 to PID 34188]
Mar 06 12:35:08 kube-01 kubelet[902]: W0306 12:35:08.405976     902 container_manager_linux.go:278] [ContainerManager] Failed to ensure state of "/docker-daemon": [failed to find container of PID 21665: open /proc/21665/cgroup: no such file or directory, failed to move PID 21665 (in "") to "/docker-daemon", failed to apply oom score -900 to PID 21665]
Mar 06 12:33:57 kube-01 kubelet[902]: W0306 12:33:57.715668     902 manager.go:108] Failed to updated pod status: error updating status for pod "kube-dns-v9-zyuha_kube-system": pods "kube-dns-v9-zyuha" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
Mar 06 12:33:55 kube-01 kubelet[902]: E0306 12:33:55.668330     902 kubelet.go:2284] Error updating node status, will retry: node "kube-01" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
Mar 06 12:33:49 kube-01 kubelet[902]: E0306 12:33:49.738599     902 kubelet.go:2284] Error updating node status, will retry: Timeout: request did not complete within allowed duration
Mar 06 12:33:07 kube-01 kubelet[902]: W0306 12:33:07.991575     902 container_manager_linux.go:278] [ContainerManager] Failed to ensure state of "/docker-daemon": [failed to find container of PID 60470: open /proc/60470/cgroup: no such file or directory, failed to move PID 60470 (in "") to "/docker-daemon", failed to apply oom score -900 to PID 60470, failed to apply oom score -900 to PID 60322]
Mar 06 12:32:07 kube-01 kubelet[902]: W0306 12:32:07.177477     902 container_manager_linux.go:278] [ContainerManager] Failed to ensure state of "/docker-daemon": [failed to find container of PID 49837: open /proc/49837/cgroup: no such file or directory, failed to move PID 49837 (in "") to "/docker-daemon", failed to apply oom score -900 to PID 49837]
Mar 06 12:31:37 kube-01 kubelet[902]: E0306 12:31:37.081150     902 kubelet.go:2284] Error updating node status, will retry: node "kube-01" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
Mar 06 12:31:28 kube-01 kubelet[902]: E0306 12:31:28.643360     902 kubelet.go:2284] Error updating node status, will retry: node "kube-01" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
Mar 06 12:31:04 kube-01 kubelet[902]: E0306 12:31:04.057224     902 kubelet.go:2284] Error updating node status, will retry: node "kube-01" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
Mar 06 12:30:26 kube-01 kubelet[902]: E0306 12:30:26.130317     902 kubelet.go:2284] Error updating node status, will retry: node "kube-01" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
`

The azure VM installation scripts do not include cAdvisor

Related: For the Azure VM installation scripts, it is not entirely clear on how to upgrade the kubernetes version (it is currently at 1.1.2). I have noticed a CoreOS service install-kubernetes runs at every start-up (and fails because downloaded files are present), is it sufficient to change the source of the kubernetes tarballs to point at the latest 1.1.x branch; or is this method of upgrading unsupported? It seems future versions of CoreOS will include the kubelet binary.

**Comment by theobolo** [comment]
I work with the same cluster but with the 1.1.7 kubernetes version.

You just have to change in your kubernetes cloud-config : 

`Environment=KUBE_RELEASE_TARBALL=https://github.com/kubernetes/kubernetes/releases/download/v1.1.7/kubernetes.tar.gz`

or you can try the 1.1.8 but i've experienced some issues with it on that cluster.

BTW i don't know why the CPU is so high :/  try to deploy it with a newest version.

If you'r working with Azure it would be a cool stuff to read :  https://pieterjong.wordpress.com/2015/07/28/azure-local-ssd-optimization/ 
For Docker optimisation

**Comment by Alex-Wauters** [comment]
Thanks for the SSD link! As for the kubernetes install; there is a systemd unit called install-kubernetes.service which has the KUBE_RELEASE_TARBALL line; if I change it the installation fails as it tries to overwrite the existing kubectl binary files:

`Mar 06 22:07:58 kube-00 systemd[1]: Starting Download Kubernetes Binaries...
Mar 06 22:07:58 kube-00 curl-retry.sh[664]: + curl --silent --location https://github.com/GoogleCloudPlatform/kubernetes/releases/download/v1.1.7/kubernetes.tar.gz --output /tmp/kubernetes.tgz
Mar 06 22:08:11 kube-00 systemd[1]: install-kubernetes.service: Control process exited, code=exited status=1
Mar 06 22:08:11 kube-00 ln[1089]: /bin/ln: failed to create symbolic link '/opt/bin/kubectl': File exists`

Should I move the kubernetes binaries before reboot? [The Weave installation script](https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/coreos/azure/README.md) seems to differ from the normal k8s installation on CoreOS in a number of ways which are undocumented for updating k8s or monitoring.

**Comment by theobolo** [comment]
First of all you right,

For the moment the Azure guide differ from the classic installation with kube-up.sh or other classic ways. I never tried to upgrade the Kubernetes environment without tearing down the cluster and make a new one.

Yesterday i've talked with the maintainer of the Azure/CoreOS/Weave repo and he told me that is aware about that problems. 

The very next step is to implement the TLS authentification on the Kube-apiserver and the kube-controller-manager. Without TLS most of the Metrics and Logging addons are not working.

If you want some metrics you need to change manually the kube-apiserver endpoint in each logging apps to point to http://kube-00:8080.

For the moment Alex, i don't know if there is a solution tu upgrade Kubernetes without tearing down the cluster :/

the problem about TLS is that you always got a Connection reset by peer when an app try to reach the https://10.16.0.1:443.

BTW i've found that if we want to implement the TLS certs we just have to use the make_ca_cert.sh and make_cert.sh there : https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt/generate-cert

And add the correct lines to the cloud-config : 

     - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem$

And in the controller-manager also.
Someone can tell me if there is a way to implement the TLS certs in the Azure getting started guide ?

**Comment by theobolo** [comment]
@Alex-Wauters just forget about that : https://github.com/colemickens/azkube

They actually work on a better way to deploy a Kube cluster on Azure with the implementation of the TLS certs and the Azure variables. Take a look at it !

**Comment by theobolo** [comment]
@davidopp Hello David, even if the docs are not updated yet, is it possible to use your work to deploy a cluster now ?

**Comment by davidopp** [comment]
@theobolo It is not my work, it is @colemickens but yes the PR is merged (#22231).

Please close this issue if you think it is addressed.

**Comment by Alex-Wauters** [comment]
Thank you for the clarification, closing issue.
