### ISSUE TITLE
Update Azure documentation for new Azure kube-up

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#22612]
@colemickens 

I think the best thing to do is to add a new row in the table at
`docs/getting-started-guides/README.md`
and a new corresponding docs page. You don't need to write anything fancy -- just a few sentences explaining how to use `kube-up` to target Azure is fine for now. If you're pressed for time, you don't even need to document the various env vars--you can just say "see the script for a description of the env var's you'll need to set."

We can leave the CoreOS-Azure stuff as-is, and figure out how/whether to evolve that separately.

cc/ @errordeveloper

ref/ #22231

**Comment by theobolo** [comment]
Maybe can you put a Warning in the actual azure doc to aware users about the non TLS support problem. 
Because i've spend a lot of time trying to figure out why most of the logging and kubernetes addons aren't working in that cluster ;)

**Comment by colemickens** [comment]
@theobolo This issue is for the new Azure cluster bring up which does support TLS.

**Comment by colemickens** [comment]
(But I could also add such a note to the existing coreos-azure setup, if that's desired.)

**Comment by theobolo** [comment]
It was in the case that you'll "leave the CoreOS-Azure stuff as-is" and precisely the doc.
Thanks for that.

**Comment by colemickens** [comment]
@theobolo I'm addressing this Issue right now and wanted to circle back around to your comment. Can you elaborate on how you were deploying the Kubernetes addons? I would expect them to be able to connect to the insecure apiserver port if they were configured correctly. I don't want to add a comment to the CoreOS documents unless I really understand the issue.

**Comment by theobolo** [comment]
@about the kubernetes addons, i wasn't able to get all of them working.

My solution as you said was to configure them to connect to the insecure kube-apiserver port.
on the azure setup it's 172.18.0.12:8080 or kube-00:8080

By the way my real struggle is that the kubernetes service inside the cluster is not usable because of the certs problem and it's not mentioned in the docs. 

It wasn't clear that i'll need to modify each yml (heapster, dashboard, kubedash, grafana) to configure them to point on the insecure public kube-00 ip :)

Is that what you asked ?

**Comment by colemickens** [comment]
>By the way my real struggle is that the kubernetes service inside the cluster is not usable because of the certs problem and it's not mentioned in the docs.

I don't know what this means.

Can we please move this discussion to a separate issue where we can suss out the details of what didn't work in that scenario for you? I don't really understand if you got it working after modifying files, if it still failed after modifying files, etc.

Thanks.

**Comment by colemickens** [comment]
The PR for this Issue is over on the docs repo: https://github.com/kubernetes/kubernetes.github.io/pull/149

**Comment by theobolo** [comment]
inside the Utils.sh in /cluster/azure/ there is a problem with the AZURE_DOCKER_REGISTRY and AZURE_DOCKER.

By default the utils.sh is looking to gcr.io/google_containers/"hyperkubeimage"
But the last hyperkube 1.1.2 release can find at gcr.io/v2/google_containers/"hyperkubeimage"

You can Add to set

export AZURE_DOCKER_REGISTRY="gcr.io/v2"
export AZURE_DOCKER="google_containers"

Or just change the utils.sh

Cheers
