### ISSUE TITLE
e2e flake: Garbage collector [Slow] should handle the creation of 1000 pods

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#22611]
The test failed multiple times like that:

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:62 Expected : 131 to be == : 100

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/2944/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/2940/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/2935/

**Comment by bgrant0607** [comment]
This appears to be a new regression as of today.

**Comment by bgrant0607** [comment]
Most recent failure is kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/2953:
```
• Failure [135.562 seconds]
Garbage collector [Slow]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:63
  should handle the creation of 1000 pods [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:62

  Expected
      <int>: 105
  to be ==
      <int>: 100

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:61
```

**Comment by bprashanth** [comment]
In all the fail cases i actually see the pods getting gc'd till the threshold:
```
I0306 20:58:43.443553       9 gc_controller.go:97] garbage collecting 23 pods
I0306 20:59:03.564090       9 gc_controller.go:97] garbage collecting 201 pods
I0306 20:59:32.105003       9 gc_controller.go:97] garbage collecting 285 pods
I0306 21:00:04.860034       9 gc_controller.go:97] garbage collecting 328 pods
I0306 21:00:39.762430       9 gc_controller.go:97] garbage collecting 63 pods
```

The differnce is in the pass cases the gc started much sooner:
```
I0305 18:36:09.920738       8 gc_controller.go:97] garbage collecting 14 pods
I0305 18:36:30.020479       8 gc_controller.go:97] garbage collecting 51 pods
I0305 18:36:51.080435       8 gc_controller.go:97] garbage collecting 52 pods
I0305 18:37:12.217662       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:37:33.410184       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:37:54.534657       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:38:15.697556       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:38:36.841060       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:38:57.978227       8 gc_controller.go:97] garbage collecting 52 pods
I0305 18:39:19.078753       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:39:40.225270       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:40:01.399748       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:40:22.702595       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:40:43.836870       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:41:04.984863       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:41:26.128950       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:41:47.275983       8 gc_controller.go:97] garbage collecting 53 pods
I0305 18:42:08.515021       8 gc_controller.go:97] garbage collecting 42 pods
```

Anyway I don't think it's worth cutting it that fine with the timeouts so I have: https://github.com/kubernetes/kubernetes/pull/22617

**Comment by bprashanth** [comment]
It's possible the only difference is we started creating the pods much faster because we recently swapped out the default client in the tests with a 20qps client (default is 5qps right?)

**Comment by bgrant0607** [comment]
This looks like it was resolved by #22617.

**Comment by wojtek-t** [comment]
This started failing again:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/2999/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/3000/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-slow/3001/

**Comment by wojtek-t** [comment]
OK - I took a look into it and here are some findings

Basically, the problem is that NodeController is watching all pods changes:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L186
and for each pod that is assigned to non-existent node it's trying to remove it:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L352

And I'm seeing a bunch of such logs in apiserver & controller manager.


The thing that I don't yet understand is why DeletionTimestamp is not null for those pods (only such pods are picked up by nodecontroller).
@gmarek

**Comment by bprashanth** [comment]
I believe deleting a pod with 0 graceperiod will first update the pod to have a deletiontimestamp set to now, then pop it from etcd, so you'll get 2 notifications down the watch. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/generic/etcd/etcd.go#L413
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/rest/delete.go#L79

**Comment by mml** [comment]
@mikedanese you're working on this, right?

**Comment by mikedanese** [comment]
I had not seen this issue. It's possible that https://github.com/kubernetes/kubernetes/commit/d8eaed912accf65e7159df9f1cce1ac483e60a32 will have helped this issue but I'll keep an eye on it over the next couple days.

**Comment by mikedanese** [comment]
These failures https://github.com/kubernetes/kubernetes/issues/22611#issuecomment-193640443 were probably caused by #22667

**Comment by wojtek-t** [comment]
Yes - I'm pretty sure this was because of that - after reverting that PR it was fixed.

**Comment by wojtek-t** [comment]
Yeah - reverting that PR solved the issue. Closing.

**Comment by mml** [comment]
OK, AIUI this is now fixed, but reopen if I'm mistaken.
