### ISSUE TITLE
Can't open new docs url in kubernetes.github.io with "404 Error!"

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#22629]
As some doc has moved to http://kubernetes.github.io/docs, now can't open the url in the README.md

like: https://github.com/kubernetes/kubernetes/tree/master/docs/admin/resourcequota
" This file has moved to: http://kubernetes.github.io/docs/admin/resourcequota/README/ " But can't open the new url
Many docs has this issue.

**Comment by mdshuai** [comment]
@eparis

**Comment by eparis** [comment]
I'm working on more 'in tree' doc fixes. But I'll try to take a look these sooner.

**Comment by eparis** [comment]
fixed!
