### ISSUE TITLE
Static pod terminating status can not be bring back

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#22625]
If the mirror pod of static pod be deleted via apiserver, the mirror pod status would stuck at `Terminating`. Even restarting `kubelet` does not work.

`kubelet` should sync the running static pod status to mirror pod.

**Comment by AdoHe** [comment]
@kubernetes/sig-node

**Comment by Random-Liu** [comment]
@xinxiaogang Now kubelet ignores all modifications to the mirror pod as long as the [annotation](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/types/pod_update.go#L26) remains unchanged. There are more related discussion in #16627, you can follow up if you are interested.

However, I think what you suggested is reasonable somehow. 

@yujuhong except for the annotation change, if the `Deletiontimestamp` of the mirror pod is set, shouldn't we recreate it?

**Comment by xinxiaogang** [comment]
Thanks @Random-Liu . I have a PR for the fix and it works in our cluster now. https://github.com/kubernetes/kubernetes/pull/22626

**Comment by Random-Liu** [comment]
@xinxiaogang Thanks very much for the fix. :) We'll review it.

**Comment by yujuhong** [comment]
@xinxiaogang, as a quick workaround, you can force delete the mirror pods (`kubectl delete pod --grace-period=0 <pod_name>`), and kubelet will recreate all of them.
 

> @yujuhong except for the annotation change, if the Deletiontimestamp of the mirror pod is set, shouldn't we recreate it?

Yes, we should do it. Ideally we should resolve the mirror pod issue #16627 altogether, but this seems like a relatively isolated fix.


> Thanks @Random-Liu . I have a PR for the fix and it works in our cluster now. #22626

Thanks for the PR!
