### ISSUE TITLE
jessie image in us-gov-west and cn-north-1

### ISSUE THREAD

**Issue by kastork** [kubernetes/kubernetes#22638]
The plain jessie ami's are available, 

`debian-jessie-amd64-hvm-2015-06-07-13-16-ebs -`

but not the k8s optimized ones.

It would be helpful to either

a. post the optimized image in 'us-gov-west', or
b. provide pointers to instructions for creating the optimized image from the standard jessie image.

**Comment by dchen1107** [comment]
cc/ @mikedanese @zmerlynn

**Comment by mikedanese** [comment]
also @justinsb

**Comment by justinsb** [comment]
I can definitely put together instructions - part of the idea is that you shouldn't be dependent on pre-baked images.

The short-form is:

From https://github.com/kubernetes/contrib/pull/486  , run something like:
```
~/k8s/bin/imagebuilder --subnet subnet-<mysubnetid> --securitygroup sg-<mysgid> --sshkey <sshkeyid> --v=2 --template ~/k8s/src/k8s.io/kubernetes/cluster/cloudimages/k8s-ebs-jessie-amd64-hvm.yml
```

This will build the images in your account and copy them to all regions.  Then you change the aws_account in the cluster/aws/jessie/util.sh script.

---

@kastork  It would be better if we didn't force you to do this (you might still choose to do it).  How can I/we copy images into the us-gov-west region?  I don't know how to go about getting access to that region.

**Comment by kastork** [comment]
@justinsb I'll give that procedure a try.

As for getting AMI's into the gov region, I really don't know. The selection of distributions is kind of lean - probably has to do with information assurance issues -- for example Centos is available, but Fedora isn't. I did see that CoreOS (or somebody who's using CoreOS) has figured it out, as their images are available.  Perhaps you have contacts with them who could give you the secret handshake.

While having your ami's available directly would be great, particularly while we're just experimenting, it may turn out that for production we would need to document all sources.  If so, having the cookbook will be very valuable.   I've never seen a STIG for debian or Ubuntu, just Centos and RHEL, so that could end up being an issue for us also.

**Comment by justinsb** [comment]
@kastork thanks for that - I'll try to write up some real docs, and let me know if any problems when running with us-gov-west - I definitely haven't tested it!  We should definitely figure out whether we can provide the image, but I think everyone is better off if we also make it simple to build your own image.

If you're effectively mandated to use RHEL/Centos, can you please open a new issue saying we should have a kube-up image that uses a RHEL-based distro (with a link to the STIG if it is available publicly).  There is support for RHEL in some configurations, but I don't think kube-up currently supports it; it shouldn't be too hard to add though given we have all the pieces.

**Comment by kastork** [comment]
Could be a year from now before I can answer that question, but if that mandate comes along, you can be sure I'll come looking.

**Comment by justinsb** [comment]
We have the same problem for cn-north-1; expanding the issue to cover that also

**Comment by kastork** [comment]
I'm having trouble tracking down the `k8s-ebs-jessie-amd64-hvm.yml` file you mentioned in the procedure for making the ubuntu machine.  Any clues?

**Comment by justinsb** [comment]
@kastork: here https://github.com/kubernetes/kubernetes/tree/master/cluster/cloudimages :-)

**Comment by kastork** [comment]
@justinsb  thanks!

**Comment by kastork** [comment]
What's the word on getting the images into gov-cloud?

**Comment by dhoeric** [comment]
@kastork I basically create a temp EC2 instance, based on Debian 8.1 

Install https://github.com/andsens/bootstrap-vz#amazon-ec2-ebs-backed-ami and create the image based on `k8s-ebs-jessie-amd64-hvm.yml`

**Comment by davidopp** [comment]
This is not tied to a Kubernetes release so I'm removing the 1.3 milestone label, leaving at P1.
