### ISSUE TITLE
Jenkins in not able to ssh node in kubernetes-e2e-gce-scalability

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#22636]
Looking into recent runs of scalability suite, there are thousands of error like these:

    error dialing jenkins@104.154.31.56:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain', retrying

Example:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/5112/consoleText

This started after migrating scalability suite to the new project:
https://pantheon.corp.google.com/compute/instances?project=google.com:k8s-jenkins-scalability&graph=GCE_CPU&duration=PT1H

I guess it's related to some missing service accounts or something like that, but I can't figure it out comparing with other projects.

Can someone please take a look?

@kubernetes/goog-testing @fejta @ixdy @spxtr @gmarek

**Comment by gmarek** [comment]
A though: doesn't ":" in project name interfere with something?

**Comment by ixdy** [comment]
Did you install the Jenkins ssh key in this project? (I think `gcloud ssh` from the Jenkins master has a similar effect.)

**Comment by ixdy** [comment]
Looks like it was not. I just installed it; we'll see if things start working.

**Comment by wojtek-t** [comment]
@ixdy - it seems that it helped - thanks for looking into it.

Can you write what exactly you did?

**Comment by ixdy** [comment]
@wojtek-t it's step 5 on the internal doc on setting up a new project. :)
