### ISSUE TITLE
API error (500): Container command not found or does not exist

### ISSUE THREAD

**Issue by mysterytree** [kubernetes/kubernetes#22631]
Got this error when rc created
![image](https://cloud.githubusercontent.com/assets/6166794/13573410/98bed128-e4ba-11e5-9c0a-770fc27cdaab.png)

The rc.yaml 

```
command:
        - bundle exec unicorn -c config/unicorn/production.rb -E production
```

The pods logs 

![image](https://cloud.githubusercontent.com/assets/6166794/13566607/4e1894b6-e491-11e5-89de-53fef0ab27d2.png)

**Comment by ncdc** [comment]
You need to specify each argument in the command as a separate entry, e.g.:

```yaml
command:
  - bundle
  - exec
  - unicorn
  - ...
```

**Comment by mysterytree** [comment]
@ncdc 
```
command:
        - bundle
        - exec 
        - unicorn
        - -c config/unicorn/production.rb -E development
```

The logs 

Error syncing pod, skipping: failed to "StartContainer" for "momoapi" with CrashLoopBackOff: "Back-off 10s restarting failed container=xxapi pod=xxapi-m7cr5_default(b0a8fa42-e47b-11e5-a878-0800274f2cef)"

**Comment by ncdc** [comment]
@mysterytree can you provide logs from the pod?

**Comment by mysterytree** [comment]
![image](https://cloud.githubusercontent.com/assets/6166794/13588800/a47a3504-e50d-11e5-8306-b77df7e49a70.png)
@ncdc

**Comment by ncdc** [comment]
You need each argument specified separately

**Comment by mysterytree** [comment]
I have tried this .
```
command:
        - bundle
        - exec 
        - unicorn 
        - -c /u/apps/momoapi/current/config/unicorn/production.rb -E development
```
Got this 
![image](https://cloud.githubusercontent.com/assets/6166794/13588987/5dcc1300-e50f-11e5-85ba-d39bce48ac95.png)

------------

```
command:
        - bundle
        - exec 
        - unicorn 
        - -c 
        - /u/apps/momoapi/current/config/unicorn/production.rb 
        - -E 
        - development
```
![image](https://cloud.githubusercontent.com/assets/6166794/13589067/02d83112-e510-11e5-9ed7-d9f265a51bde.png)

Thanks a lot ! This really help me !
