### ISSUE TITLE
move test images to separate gcr.io project

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#22658]
We currently have all of the test images in `test/images` uploaded to the `gcr.io/google_containers` project. We should move these into a separate project and limit the scope of `gcr.io/google_containers` only to official Kubernetes images.

For example, the [NFS volume example](http://kubernetes.io/v1.1/examples/nfs/README.html) uses `gcr.io/google_containers/volume-nfs`, which doesn't really indicate that this image was only designed for functional testing. (See #22561 and http://stackoverflow.com/questions/35815736/kubernetes-nfs-server-is-taking-100-cpu for examples of actual usage of this image outside e2e tests.)

I'm not sure how we'd deprecate these images given that e2e tests and external users depend on them. Hopefully over time everything would just migrate to the new images?

Thoughts?
@kubernetes/sig-testing @david-mcmahon

**Comment by jayunit100** [comment]
@ixdy ok sounds good ; how about thoughts on  auto publishing of the images ?

**Comment by david-mcmahon** [comment]
Not sure about the typical workflow/use of these containers, but maybe a message to the user about the intended move on the final few(?) releases that land on google_containers?

**Comment by timothysc** [comment]
We need a way for non-google folks to automate a image build and push.

**Comment by ixdy** [comment]
Yes, I'd love to automate the process of building and pushing a new image on merge. Pretty sure there's even a Jenkins plugin to do that, though I haven't looked into it (and don't immediately have bandwidth for it).

**Comment by spiffxp** [comment]
/sig release
/sig testing

I'll just throw in two cents that IMO there should be a repo for test-infra, vs. images that are used as examples or part of e2e tests

**Comment by ixdy** [comment]
Thanks to @mkumatag, this is done, in #44910 and others - the e2e test images now live in `gcr.io/kubernetes-e2e-test-images`.

/assign @mkumatag 
/close

**Comment by ixdy** [comment]
(auto-building of images is not yet done, but that probably warrants a separate issue?)
