### ISSUE TITLE
e2e flake: Scalability suite is failing

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#22660]
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-e2e-gce-scalability/5119/

The fix for it is to add
  "PROXY"
to ignoredVerbs here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/metrics_util.go#L202

@k8s-oncall - can you do it (I don't have access now).

@kubernetes/goog-testing

**Comment by davidopp** [comment]
I can do it.

**Comment by wojtek-t** [comment]
Sorry - I meant add "CONNECT" to ignoredVerbs

**Comment by wojtek-t** [comment]
"PROXY" is already there :)
