### ISSUE TITLE
Start release-1.2 CI

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#22672]
This is a tracking issue to which I'll link 1.2 CI PRs.

**Comment by bgrant0607** [comment]
cc @eparis @smarterclayton @david-mcmahon

**Comment by bgrant0607** [comment]
Where are we on this? We have lots of PRs to cherrypick.

#22710

**Comment by bgrant0607** [comment]
cc @spiffxp

**Comment by spxtr** [comment]
These jobs should be fairly uncontroversial:

- kubernetes-e2e-aws-release-1.2
- kubernetes-e2e-gce-release-1.2
- kubernetes-e2e-gke-release-1.2
- kubernetes-e2e-gce-serial-1.2
- kubernetes-e2e-gke-serial-1.2
- kubernetes-e2e-gce-slow-1.2
- kubernetes-e2e-gke-slow-1.2
- kubernetes-soak-...-1.2
- kubernetes-upgrade-... (both to and from 1.2, cc @ihmccreery)

Possibly we want to create some features jobs to test out 1.2 features? Possibly we want to bump the scalability-1.1 to test 1.2 instead, since that's a fairly expensive test?

**Comment by bgrant0607** [comment]
How about scalability?

cc @wojtek-t

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-testing @roberthbailey @thockin @davidopp

**Comment by roberthbailey** [comment]
I've created a view in Jenkins for the release-1.2 branch tests (which currently includes the only 2 that are running thus far).

**Comment by bgrant0607** [comment]
Moving scalability to 1.2 seems reasonable to me. We don't expect much to change in 1.1 at this point.

Feature tests for 1.2 features makes sense to me.

Getting the upgrade tests up is pretty critical at this point. The existing upgrade tests are upgrading from what to what? 

Many of them are failing. For example, kubernetes-upgrade-gce-1.1-master-step2-kubectl-e2e-new:
```
 ERROR: (gcloud.compute.instance-templates.list) Some requests did not succeed:
16:19:59  - Invalid value for project: kubernetes-jenkins-gce-upgrade
```

**Comment by ihmccreery** [comment]
I wrote docs about how to spin up jobs for a new branch, to avoid vagueness of what should be done:

https://github.com/kubernetes/kubernetes/blob/master/docs/devel/releasing.md#manual-tasks-for-new-release-series

Especially:

> Make sure all features that are supposed to be GA are covered by tests, but remove feature tests on the release branch for features that aren't GA. You can use `hack/list-feature-tests.sh` to see a list of tests labeled as `[Feature:.+]`; make sure that these are all either covered in CI jobs on the release branch or are experimental features. (The answer should already be 'yes', but this is a good time to reconcile.)

Re: upgrade jobs—the GCE jobs have not worked for a long time; we've deprioritized making them work in favor of the GKE jobs.  I can add the new GKE upgrade tests for v1.2.

**Comment by wojtek-t** [comment]
Sorry - I missed this email.
Yes, I agree that moving scalability to 1.2 and dropping 1.1 is fine.

**Comment by spxtr** [comment]
Core jobs are all in. These are our feature labels in 1.2. Which should we run? We are already hitting upgrades and scalability suites.
```
[Feature:ClusterSizeAutoscaling]
[Feature:ComprehensiveNamespaceDraining]
[Feature:Elasticsearch]
[Feature:Example]
[Feature:ExperimentalNodeUpgrade]
[Feature:ExperimentalResourceUsageTracking]
[Feature:FSGroup]
[Feature:HighDensityPerformance]
[Feature:Ingress]
[Feature:InitialResources]
[Feature:ManualPerformance]
[Feature:MasterUpgrade]
[Feature:NodeAffinity]
[Feature:NodeUpgrade]
[Feature:Performance]
[Feature:Reboot]
[Feature:SecurityContext]
[Feature:ServiceLoadBalancer]
[Feature:Upgrade]
[Feature:Volumes]
```

**Comment by spxtr** [comment]
@bgrant0607 which of the above should we get running today? Reboot is an obvious candidate but I don't know much about the others.

**Comment by bgrant0607** [comment]
cc @piosz @bprashanth @thockin @ihmccreery Any opinions re. which e2e tests you'd like run on the release branch? 

My wild guess would be whichever of the following are reasonably stable (basically, subtract out experimental features):
```
[Feature:ClusterSizeAutoscaling]
[Feature:ComprehensiveNamespaceDraining]
[Feature:FSGroup]
[Feature:HighDensityPerformance]
[Feature:Ingress]
[Feature:ManualPerformance]
[Feature:MasterUpgrade]
[Feature:NodeAffinity]
[Feature:NodeUpgrade]
[Feature:Performance]
[Feature:SecurityContext]
[Feature:ServiceLoadBalancer]
[Feature:Upgrade]
[Feature:Volumes]
```

**Comment by bprashanth** [comment]
`[Feature:Ingress]` is good. It's was running on realease 1.1 as well.

**Comment by bprashanth** [comment]
`[Feature:ServiceLoadBalancer]` doesn't need to be run on the release branch, see https://github.com/kubernetes/kubernetes/issues/19552#issuecomment-171017736

**Comment by david-mcmahon** [comment]
Can I request that we standardize on a naming convention for jobs on Jenkins?
I have some tooling that is scraping data from Jenkins, but we have different naming conventions for jobs between branches.  Some jobs use the -N.N suffix and some use the -release-N.N suffix.

kubernetes-test-go
kubernetes-test-go-release-1.1
kubernetes-test-go-release-1.2

kubernetes-e2e-gke-serial
kubernetes-e2e-gke-serial-1.1
kubernetes-e2e-gke-serial-release-1.2

kubernetes-build
kubernetes-build-1.1
kubernetes-build-1.2

kubernetes-e2e-gce
kubernetes-e2e-gce-release-1.1
kubernetes-e2e-gce-release-1.2

**Comment by spxtr** [comment]
@david-mcmahon file an issue against me about that. It's something I'd like to do soon.

**Comment by spxtr** [comment]
Hmm, I'm really not sure about some of these. The Volumes tests aren't currently run anywhere, and many of these aren't actually 1.2 features, but are experimental. Aside from reboot and ingress, are there any that actually need to be done now?

**Comment by spxtr** [comment]
In the meantime, I temporarily pointed the master jobs at release-1.2 to make sure they're not broken. They all passed, and I switched them back.

[gke-ingress](https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke-ingress/2759/)
[gke-reboot](https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke-reboot/939/)
[gce-ingress](https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-ingress/2722/)
[gce-reboot](https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-reboot/1478/)

**Comment by piosz** [comment]
`[Feature:ClusterSizeAutoscaling]` won't pass on release branch because it requires custom monitoring configuration. Since this is an experimental feature it doesn't need to run there.

cc @fgrzadkowski @mwielgus

**Comment by bprashanth** [comment]
@spxtr if you're planning to use a different project for the Ingress tests please set the quota to the limits in gce/gke-ingress

**Comment by bgrant0607** [comment]
What's up with kubernetes-e2e-gce-scalability-release-1.2 ? Looks like it doesn't work yet.

**Comment by spxtr** [comment]
Looks like scalability-release-1.2 is failing to make more than 10 nodes. cc @wojtek-t

**Comment by roberthbailey** [comment]
We don't have enough CPU quota to make a larger cluster.

**Comment by spxtr** [comment]
Out of all the features above, it looks like only reboot and ingress are good candidates for 1.2. I checked which of the other features are actually being run, and a disappointingly large number of them aren't.

**Comment by spxtr** [comment]
By the way, my work YAMLfying the jobs makes it very easy to add new jobs. Here's a sample commit where I add just one feature job: https://github.com/kubernetes/kubernetes/pull/23094/commits/17898025f5086672fcb5066bea86dcc870e9a0e1 .

I think the original goal of adding the Feature labels was for owners of the features to manage their own jobs.
