### ISSUE TITLE
Implement PersistentVolume recycler for EBS volumes

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#22689]
When I try to use the "Recycle" policy on an AWS EBS PersistentVolume, I get an error about no recycler found for this type of volume.

I'm not sure if this is related to #15073 or #17882 

Anyway this means that I have to manually re-create PVs if I want to reuse them.

**Comment by preillyme** [comment]
I've seen the same issue @paralin

**Comment by ncdc** [comment]
cc @kubernetes/rh-storage

**Comment by childsb** [comment]
hi @paralin. We are building up user stories for Recycle function.  Is there a reason that you'd prefer to recycle an existing volume over deleting and re-creating?  If the delete and recreate where automated, would that be sufficient?

**Comment by paralin** [comment]
@childsb I'd be quite happy if there was a delete and recreate on AWS or GCE. As far as I knew there wasn't yet. But yeah, that'd be fine.

**Comment by markturansky** [comment]
"Delete" works for AWS and GCE as a reclamation policy.

The recycler controller ignores volumes set to Retain and either recycles
or deletes volumes w/ Recycle or Delete policy, respectively.  The plugins
for the volumes will correctly delete a cloud volume.

Manually created EBS PVs (and GCE) can use the delete policy.  The downside
is that without dynamically provisioning, the pool of available volumes
empties as they are consumed/deleted.

**Comment by paralin** [comment]
@markturansky Okay so there is currently no implementation for creating volumes, correct?

**Comment by markturansky** [comment]
There is the 1st pass here:
https://github.com/kubernetes/kubernetes/tree/master/examples/experimental/persistent-volume-provisioning

The newer, fuller feature is in development.

**Comment by paralin** [comment]
@markturansky Thanks, I will have a look at that and see if I can contribute at all.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @justinsb @paralin

**Comment by paralin** [comment]
Unless the decision was made to make a recycler for aws, I think the way to do it now is to just have it delete and recreate the volume automatically. I'll close this one unless people feel this hasn't been addressed
