### ISSUE TITLE
Creating pod infra container for non-intel archs

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#22683]
Hi,

In order to run kubernertes on non-intel arch, running pod infra container is a big issue. As the official container image i.e. gcr.io/google_containers/pause is available for intel only (Correct me if I am wrong). I have been able to create the image for ppc64le arch too, but not sure how to get that into official repos. Since, there is no namespace attached to the image, how should we identify the image based on arch?

**Comment by Pensu** [comment]
I have tried to add pause-ARCH to the image name, if that could be appropriate or should we go with namespace i.e. either gcr.io/google_containers/pause-ppc64le or gcr.io/google_containers/ppc64le/pause?

cc: @luxas

**Comment by liangchenye** [comment]
Thanks. He must be very interest in this. I've sent an email to him.

These two ways are new features on the todo list, right?
The later one seems better, to me.

cc @maquanyi

**Comment by luxas** [comment]
Ref: #5770 and #15140
I lean towards option one, which doesn't require the flag

**Comment by luxas** [comment]
@Pensu To answer your question, the way we tag images is `binary-arch:version`, so for pause it means `pause-ppc64le:2.0`, but I think you have noticed that already.

Just `pause:2.0` is backwards-compability for `amd64`, and the only used image in kube code right now.

I think quite a lot will change with pause to `1.3`. @thockin discussed if we should use C instead of go when compiling it and so on.

Also ref: #22876

**Comment by Pensu** [comment]
@luxas, yeah, I have seen that and I have named the image accordingly in my PR. My point would be how do it arch dependent? I mean how would the code base know what arch is it running on and which image would be downloaded, i.e. either pause:2.0 or pause-ppc64le:2.0. Would docker do it or k8s?

**Comment by Pensu** [comment]
@dchen1107 I too like the first option. Shouldn't be too difficult to let kubelet know which pause to download. But how do I push the image for ppc64le to gcr.io? What's the way to do that?

**Comment by luxas** [comment]
@Pensu I'm working on a PR that chooses the right `pause` image based on `runtime.GOARCH`.
And BTW, we don't have permission to push to `gcr.io`, so you have to convince some k8s maintainer to do it.
