### ISSUE TITLE
Can only curl a service, using node-port and node ip, where POD is running.

### ISSUE THREAD

**Issue by JaydiptaBiswas** [kubernetes/kubernetes#22688]
I am trying to access a Service from outside the cluster. The cluster has 3 nodes 1) x.y.z.105, 
2) x.y.z.54, 3) x.y.z.57. Both 54 and 57 are cluster nodes and 105 is used as both master and node.

Created a service  which exposes node-port 30822.
I have created a POD(single container TOMCAT pod) using a RC. The RC creates only one POD replica in a node, lets's say in 54.

Now I am able to curl http://x.y.z.54:30822, but cannot curl http://x.y.z.57:30822 or http://x.y.z.105:30822, both gives error messages like,
E0308 12:06:14.968642   28933 proxysocket.go:104] Dial failed: dial tcp 172.17.0.5:8080: connection refused
E0308 12:06:14.969581   28933 proxysocket.go:138] Failed to connect to balancer: failed to connect to an endpoint.
curl: (56) Recv failure: Connection reset by peer

**Service JSON def:**

{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "tomcat-master"
    },
    "spec": {
        "type": "NodePort",
        "selector": {
            "app": "tomcat-web"
        },
        "ports": [
            {
                "name": "kube-tomcat",
                "protocol": "TCP",
                "port": 9092,
                "targetPort": 8080
            }
        ]
    }
}

**Service description command result:**
Name:                   tomcat-master
Namespace:           default
Labels:                  <none>
Selector:                app=tomcat-web
Type:                     NodePort
IP:                         10.100.229.247
Port:                       kube-tomcat  9092/TCP
NodePort:               kube-tomcat  30822/TCP
Endpoints:              172.17.0.5:8080
Session Affinity:      None
No events.

**RC YAML def:**

apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-replication-controller
spec:
  replicas: 1
  selector:
    app: tomcat-web
  template:
    metadata:
      labels:
        app: tomcat-web
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080

**For your information** :While Running kube-proxy in every node I am getting a common error,
**Command:** ./kube-proxy --master=10.242.138.105:8080 --bind-address=0.0.0.0 &
**Result:**
Try `iptables -h' or 'iptables --help' for more information.
E0308 12:00:06.415707   28933 proxier.go:197] Error removing pure-iptables proxy rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target`KUBE-SERVICES':No such file or directory

**Comment by ArtfulCoder** [comment]
Q1. If you bring up 3 containers, one per node, can the containers ping each other ?
Q2. How do the iptables rules look on each node (you can run `sudo iptables-save`)

**Comment by JaydiptaBiswas** [comment]
Q1.
a. Created a docker container[generated IP: 172.17.0.79] in x.y.z.105 and another container   [generated IP: 172.17.0.7] in x.y.z.54. Then trying to execute 'ping 172.17.0.7' from 172.17.0.79 and vice-versa. Both gives error : ' Destination Host Unreachable'.
 
b. Then created a tomcat container[172.17.0.8] forwarding 8080 to 9096 in HOST[x.y.z.54]. Then successfully able to curl from Container[172.17.0.79] of HOST[x.y.z.105] to tomcat container[172.17.0.8] of HOST[x.y.z.54].

Q2. Attached results of sudo iptables-save for 54,57,105. PFA.
[IP_Tables.zip](https://github.com/kubernetes/kubernetes/files/165096/IP_Tables.zip)

**Comment by JaydiptaBiswas** [comment]
Q1.
a. Created a docker container[generated IP: 172.17.0.79] in x.y.z.105 and another container [generated IP: 172.17.0.7] in x.y.z.54. Then trying to execute 'ping 172.17.0.7' from 172.17.0.79 and vice-versa. Both gives error : ' Destination Host Unreachable'.

b. Then created a tomcat container[172.17.0.8] forwarding 8080 to 9096 in HOST[x.y.z.54]. Then successfully able to curl from Container[172.17.0.79] of HOST[x.y.z.105] to tomcat container[172.17.0.8] of HOST[x.y.z.54] using 
'curl http://x.y.z.54:9096'.

Q2. Attached results of sudo iptables-save for 54,57,105. PFA.
[IP_Tables_140316.zip](https://github.com/kubernetes/kubernetes/files/171870/IP_Tables_140316.zip)
