### ISSUE TITLE
smart storage labels for kubelets

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#22699]
In #22613 we had the idea of labelling nodes that support  storage types and then using those labels as filters for storage tests , rather than manual skipping (i.e. run gluster test if at least 1 node supports it based on Volume plugin canSupport status).

This can be done like so.
-  we should have the nodes broadcast wether they support what storage types.  Maybe add to `NodeSystemInfo`...
- we should modify all storage e2es to use that selector when running tests rather than just broadly skipping them.  iirc think (for example) iscsi works on GCE as is, and Ceph basic tests work on oepnshift-ansible as-is.

**Comment by jayunit100** [comment]
cc @timothysc

**Comment by timothysc** [comment]
This should belong to the @kubernetes/sig-storage & @kubernetes/rh-storage teams.  

But yes we need node-capabilities in order to do this.

**Comment by thockin** [comment]
@fejta here's a place that maybe test engineer could help streamline.
