### ISSUE TITLE
Add QoS documentation to docs/user-guide/compute-resources.md

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#22694]
We don't have any user guide documentation about QoS. 

`docs/user-guide/production-pods/#resource-management` points to `docs/proposals/resource-qos.md` which, while probably mostly accurate, is a "proposal" doc that doesn't inspire confidence in the reader.

`docs/user-guide/compute-resources.md` doesn't mention QoS at all.

There's a random example in 
`examples/runtime-constraints/README.md`
which isn't pointed to from anywhere.

We should add QoS documentation to `docs/user-guide/compute-resources.md`
At least explain the definition and treatment of best-effort vs. burstable vs. guaranteed

@vishh Can you do it?

**Comment by vishh** [comment]
Yeah. I will handle this.

**Comment by vishh** [comment]
I'm closing this as a dup of #10781.
