### ISSUE TITLE
Update semi-broken OpenShift-Origin example

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#22693]
I've put quite a bit of work into deploying OpenShift to existing Kubernetes clusters easily and reliably since the last few issues I made about the topic - #16901 

I have written a Python CLI for deploying OpenShift to existing Kubernetes clusters called [openshift-under-kubernetes](http://github.com/paralin/openshift-under-kubernetes). It does a complex sequence of queries against the Kubernetes API to determine the current cluster state and safely deploy/remove OpenShift. It can also update `master-config.yaml` in place easily (one command to pop open an editor / apply changes). 

I think it might be worth mentioning that here. It's a bit off-putting to try to deploy OpenShift with the current example in this repo, as as-of the last time I tested it, it doesn't seem to work correctly. Furthermore, the example here doesn't use any kind of storage volumes. I used OpenShift before this way and ended up losing everything when the etcd cluster temporarily went down.

Anyway, please let me know what you think, and if it's worth mentioning here.

**Comment by paralin** [comment]
@stevekuznetsov @derekwaynecarr

**Comment by derekwaynecarr** [comment]
I will review your repository today as well.

I have local changes that fixes the basic example when working on GCE that I hope to get a PR in place for today/tomorrow.  

We have actually been discussing changing `openshift start` to support deployment on kubernetes directly to eliminate the need for anything complicated in bash, etc

**Comment by derekwaynecarr** [comment]
fyi @smarterclayton @csrwng - this is related to the topic we discussed yesterday.

**Comment by paralin** [comment]
@derekwaynecarr Did you have a chance to look at it?

**Comment by derekwaynecarr** [comment]
@paralin - I did.  It's very cool.  In general, I think my only complaint was the need to specify a PV name rather than take part in the normal PVC binding process.  I am curious if you found the scope of flags in your current solution sufficient or if there are other things you want to parameterize?

I want to get your feedback on the experimental command I am working on downstream so I can ensure we get the Kubernetes example fixed in time for Kubernetes 1.2, so I will make sure to cc you on the pertinent PRs.

You can follow progress on that command via this trello card:
https://trello.com/c/Luji5Gdn/318-3-to-improve-community-awareness-of-openshift-make-it-easy-to-deploy-openshift-on-kubernetes

**Comment by paralin** [comment]
@derekwaynecarr I'd love to help out on that front (downstream). 

I think it might be good to add an option to poll the users list until someone signs in and make them cluster admin so that the admin user can easily get access to the oadm commands without using admin.kubeconfig. On that front as well it would be good to offer to put a kubectl context for the user in admin.kubeconfig into their kubeconfig.

Overall it's just ease of use. I think hitting the API directly to avoid using "kubectl" is a good improvement. I've been using the deployer myself lately as part of a 1 command turn-key deploy script for the company I'm consulting for. It seems to be very reliable.

The other thing was - I need a reliable way of checking which cloud provider we're running on and disallowing LoadBalancer (use NodePort instead) if it's not supported. I think querying for that might be a good improvement to Kubernetes overall.

Also it would be good if Kubernetes could implement the automatic PV allocation and deallocation on AWS and GCE and maybe Vagrant so we can have the setup script automatically allocate / maintain the config volume.

**Comment by derekwaynecarr** [comment]
@paralin on GCE, you can add an annotation to automatically provision a PV for a PVC.  Will cc you on the `openshift ex on-kubernetes install` command in downstream PR which will need to be done before this is fixed.

**Comment by paralin** [comment]
@derekwaynecarr I added `deploy --create-volume` which will automatically allocate a cloud volume for the OpenShift etcd storage. I've also added the command `addclusterrole` which lets you easily add a cluster role to a user (such as cluster-admin).

There's a function in os_kube called `escalate_admin_kubeconfig` which uses the Kubernetes access level to fetch the OpenShift config and escalate to OpenShift system:admin via the use of `admin.kubeconfig`.

It's so incredibly fast to edit the master config, add roles, etc now.. All of this took me ages before. 

Probably going to implement a proper registry deployment setup next. I'm not too interested in using routes (because I prefer just having LoadBalancers or Ingress) but I might add a router deployer as well.

**Comment by paralin** [comment]
Downstream we're working on ways to deploy Origin under Kubernetes automatically. 

I have this almost completely done with the openshift_under_kubernetes project, but eventually it will become part of OpenShift itself.

For now I'm going to close this because OpenShift is probably going to become something downstream, not an example here, pretty soon.
