### ISSUE TITLE
Networking tests: Expanding and modularizing.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#22707]
We need to come up with the set of use cases for measuring network perf on Kube.  

Basically, we should have a networking suite which answers a few  questions, such as the following.

- pod to pod communication: can all pods reach each other (networking.go)
- pod to pod throughput: whats the min/max throughput of info for pods->pod communication on the network compared with the theoretical max.
- service endpoint stability: are all pods getting equally exersized for requests ?
- maximum services: how many services can we run on a cluster without dropping/timeouting connections ?

For this issue, lets define what we care about measuring ^ .  then we can write tests to fill the gaps.

cc @kubernetes/sig-testing @kubernetes/sig-network

**Comment by bprashanth** [comment]
A lot of the correctness stuff above is done through the services and kubeproxy e2es (and e2e/networking.go as you noted). 

> service endpoint stability: are all pods getting equally exersized for requests ?

Currently kube-proxy sets a statistical distribution paramerter in iptables. We need a test that confirms that if we get a sudden burt of reqests, they get evenly distributed according the the iptables stats. Current tests only check that *at least* one request out of, say 150, go to each backend. 

> maximum services: how many services can we run on a cluster without dropping/timeouting connections ?

services_load already does something like this. IPTables has a limit of entries (sort of, it'll get slow after a point, but that's when the kernel gets slow so it's really pretty high), other than that I think as long as you're using iptables kube-proxy it's a function of the size of the nodes. 

We really need a performance benchmark, something that showcases different networking providers on different clouds (eg: openshift+ovs vs aws+flannel vs just gce networking etc). This will become more important with CNI plugins.

**Comment by jeremyeder** [comment]
Each network benchmark has different licensing challenges.  Do you have a preference?  Look at PerfKitBenchmarker -- they don't ship benchmarks for this reason.  What would we do differently in Kube e2e?

We have something similar, but it's not written in Go and it's tied to our infra and test harness.  We could consider implementing it as an e2e.

**Comment by sostheim** [comment]
sig-networking slack channel posted this up in the last week: https://kubernetes.slack.com/archives/sig-network/p1457102221000195

**Comment by bprashanth** [comment]
It doesn't have be to an e2e, but we already know and document how to execute an e2e through ginkgo. I think the important part is that someone should be able to setup a cluster with CNI-plugin=X, on cloudprovider=Y, run the benchmark, and get some numbers. Presumably they already have numbers from their existing clusters (non-kube or kube with different networking) they can compare against. Checking it in will be a good step forward, even if it just uses iperf. 

We went through a similar process for proving that the iptables kube-proxy was better but just didn't have time to code up and checkin something formal. Say we re-structured the userspace kubeproxy so it uses splice, how would I prove it's any better or worse?

**Comment by jeremyeder** [comment]
We have such a thing:  https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/pbench-uperf People can pick that up right now and run it anywhere kube/openshift runs (subject to setting up ports, firewall rules etc).

**Comment by bprashanth** [comment]
It would be great if you removed the openshift specific bits and checked it into contrib/ with a README mentioning any setup required

**Comment by jayunit100** [comment]
+1 to making it an e2e if that wasnt already clear in my suggestion

**Comment by jeremyeder** [comment]
How would you prefer we handle the benchmark installation?  Should we just fail if the benchmark is not installed?  We cannot distribute netperf, uperf or iperf.

**Comment by bprashanth** [comment]
Can you exec in a container that has those?

**Comment by bprashanth** [comment]
I suppose it would have to be net=host so it doesn't disrupt the benchmark

**Comment by jeremyeder** [comment]
Yes, that's roughly how we do it now.  Doing this is a much larger mouthful than just porting a network test into e2e.  Need some internal discussions first.

**Comment by jayunit100** [comment]
Some folks on our team also are interested in the `*perf` stuff (netperf, uperf, i perf).  Its pretty easy to run from containers...

```
 docker run --name iperf mattgruter/iperf -s 
```
```
docker run --link iperf:target mattgruter/iperf
```
And you get a nice little output
```
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  30.6 GBytes  26.3 Gbits/sec
```

**Comment by jayunit100** [comment]
After looking at a few different workloads and talking to more people,  for any cluster , the metrics we care about that I was able to find:

- TCP : GBits per second between pods w/ Max packet size.
- TCP : GBits per second between pods at with x*n services present (n=num of nodes, x=1...100).
- TCP : GBits per second between pods when large packets.
- TCP: (Real world) GBits per second between pods when 100/1000 requests per second are occuring on a service endpoint 

Meanwhile , I've created a base iperf implementation and confirmed it works properly from what i can tell (over TCP) in kubernetes.  Its around 30GB/sec locally for containers, 3GB/sec on GCE.

**Comment by ofthecurerh** [comment]
In our testing we do throughput and latency for TCP and only latency for UDP. Does iperf only do throughput?

@jayunit100 what do you define as large and max packet size? We usually run 64, 1024, 16384 bytes to cover small/medium/large packets.

**Comment by jayunit100** [comment]
maxpacketsize: cluster dependent.  
re: latency - if we want to track this, then lets track it.  w/ or w/o iperf.  I'll add it to the list :)
