### ISSUE TITLE
Enabling Deployment doesn't work with ENABLE_DEPLOYMENTS=true

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#22703]
http://kubernetes.io/v1.1/docs/user-guide/deployments.html
As per documentation on this page , before kube-up.sh, setting ENABLE_DEPLOYMENTS= true should enable deployments but it doesn't. 

The right environment variable to set is KUBE_ENABLE_DEPLOYMENTS . Please fix the documentation page

**Comment by mikedanese** [comment]
@johndmulhausen

**Comment by bgrant0607** [comment]
That doc is for 1.1 and is obsolete.
