### ISSUE TITLE
Clarify kubectl get/describe service output

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22702]
Too many ports and IPs for users to figure out.

https://groups.google.com/forum/#!topic/google-containers/IMYhmPsXdxE

cc @thockin @bprashanth @kubernetes/kubectl

**Comment by smarterclayton** [comment]
I think we want to consider compacting hosts, ports, and directions into a more succinct format that indicates how information flows.

**Comment by AdoHe** [comment]
I think a more intuitive way to display the network directions is much more user friendly.

**Comment by spiffxp** [comment]
/sig cli
because kubectl output
