### ISSUE TITLE
More info in NodeSystemInfo

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#22701]
@dchen1107 It would be awesome to have more metadata available in NodeSystemInfo.  what are the limits ?  Anyone else thinking about this.  some ideas
- what storage is supported
- what binaries are available on the system path
- total amount of storage available (not sure we might already have this somewhere)
  obviously there are a million things we might want to add.  I'm sure the node folks have deeper knowledge of what we actually _should_ add to the metadata. 

For context, this idea came up in #22613 where tim brought up the idea of matching storage tests against labelled nodes that can run "gluster" or "Ceph" or ...

**Comment by jayunit100** [comment]
cc @kubernetes/sig-node

**Comment by dchen1107** [comment]
This has to be case-by-case, and not necessary to NodeSystemInfo here. 

> what storage is supported

From #22613, looks like if Node run "gluster" or "ceph" is required by upstream components / control system, like scheduler, Kubelet should export such node attribute as node labels. This information can be included in NodeSystemInfo too. 1.2 Kubelet release already support a --nodel-labels now. Auto detect such storage information and export as node labels doesn't support today yet. We need more discussion.

> what binaries are available on the system path

Can you clarify this with more detail? 

> total amount of storage available? 

Yes, Kubelet should export this information, but as part of Capacity and Allocatable in NodeStatus, not in NodeSystemInfo. Kubelet has those information already, or relatively easy to get those information. The blocker issue is how to represent at Kubernetes API. 

There are many other information at node level which are not required by control system, but very useful for debugging & introspection. Kubelet / cAdvisor already discover those information, but not necessary to propagate those to APIserver. We could provide a Kubelet page which can be accessed through apiserver proxy: http://<apiserver_IP>:8080/api/v1/proxy/nodes/<node_name>:10250/

**Comment by jayunit100** [comment]
We need to clarify what info goes in labels vs what goes in NodeSystemInfo.  From conversation w/ tim: probably NodeSystemInfo should be hardened well defined data, and labels can be used for other stuff.

**Comment by jayunit100** [comment]
Some of this stuff could also  be a case for taints and tolerations ? not sure what is "system info" vs. a "node taint" vs. a "node label".
