### ISSUE TITLE
cluster/azure e2e test setup and framework

### ISSUE THREAD

**Issue by WeixuZhuang** [kubernetes/kubernetes#22715]
cluster/azure support was missing from kubernetes. This issue tracks adding cluster/azure support so that e2e tests can be run for that cluster. The proposed methodology includes using saltstack for bringup and openvpn to setup network.

https://github.com/kubernetes/kubernetes/pull/21207

**Comment by davidopp** [comment]
cc/ @colemickens

**Comment by jdumars** [comment]
Closing this issue.
