### ISSUE TITLE
Automatically set master size appropriately on AWS

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#22711]
Like how we do it in `get-master-size` in `cluster/gce/config-common.sh`

**Comment by justinsb** [comment]
We do set it automatically!  Are you saying we should try to correlate more closely to the GCE recommended sizes?  I believe @brendandburns originally picked the sizes, and then in 1.2 I increased the minimum size and avoided the t2 (burstable) instance types.  But generally, I'm in favor of aligning our configuration with GCE as much as possible so we could change the defaults, at least so we have the same memory requirements as GCE.

Are you thinking 1.2 or 1.3?

**Comment by davidopp** [comment]
Oh you're right, I should have checked. I'm going to close the issue because I was just mistaken. Feel free to re-open if you think we should re-evaluate the defaults. (I definitely wasn't suggesting to do this for 1.2 in any event).
