### ISSUE TITLE
 CreatingLoadBalancerFailed   {service-controller }   Error creating load balancer (will retry):  issue

### ISSUE THREAD

**Issue by rasekar2000** [kubernetes/kubernetes#22721]
Deleting the service in LoadBalancer is not working and hence new LoadBalancerIP is not getting attached to the recreated service.

1) Created a service with Global static IP mistakenly instead of Regional static IP.
 IP address: 107.178.253.100

2) Deleted the service .. yet seeing the Re-Creation attempt 

23h         2s         93759     lb4b-haproxy   Service               CreatingLoadBalancerFailed   {service-controller }   **Error creating load balancer (will retry)**: Failed to create load balancer for service default/lb4b-haproxy: this gce project doesn't own the IP address: 107.178.253.100

3) Recreated with proper static IP in the LoadBalancer 

![image](https://cloud.githubusercontent.com/assets/3443965/13620312/82845cf0-e543-11e5-8148-84dcef1cab12.png)

 3.a)
           `RajRajen:scripts rajrajen$ kubectl get service lb4b-haproxy -o yaml
             apiVersion: v1
             kind: Service
             metadata:
               creationTimestamp: 2016-03-08T22:58:51Z
               labels:
                   app: lb4bfehaproxy
                tier: frontend
              name: lb4b-haproxy
               namespace: default
                 resourceVersion: "295779"
                 selfLink: /api/v1/namespaces/default/services/lb4b-haproxy
              uid: 52fe9071-e581-11e5-a8c4-42010af000b8
            spec:
                clusterIP: 10.219.240.179
                loadBalancerIP: 104.197.125.150
           ports:
             - name: httpport
                 nodePort: 30576
                 port: 80
                 protocol: TCP
               targetPort: 80
           selector:
               app: lb4bfehaproxy
               tier: frontend
              sessionAffinity: None
              type: LoadBalancer
          status:
              loadBalancer: {}`

4) This time, new the static IP is not getting attached to the LoadBalancer
 4.a) 
![image](https://cloud.githubusercontent.com/assets/3443965/13620227/0696fd0a-e543-11e5-9e8a-1824cf5da079.png)

5) kubectl version

RajRajen:scripts rajrajen$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}
RajRajen:scripts rajrajen$

Please let me know how to delete the old RECREATION attempt?

Thanks

**Comment by mikedanese** [comment]
cc @bprashanth

**Comment by bprashanth** [comment]
I believe we fixed this when we started re-getting the service https://github.com/kubernetes/kubernetes/pull/22069
@a-robinson @justinsb

**Comment by a-robinson** [comment]
Yeah, this'll be fixed in 1.2.

In the meantime, if you're managing your own cluster, you should be able to fix things by restarting the kube-controller-manager process on the master VM.

If you're running on GKE, feel free to send me an email at `arob at google.com` and I'll make sure it gets fixed up for you. Sorry for the trouble!

**Comment by rasekar2000** [comment]
Hello Alex - @a-robinson , I am running this in GKE only - Google Container Engine ...I overcame this by creating another service name .. Yet this error message is annoying as well, potentially going to bring some kubectl service with infinite retry attempt. Regards, Raj

**Comment by a-robinson** [comment]
@rasekar2000 - the problem of infinitely retrying deletes should be resolved on your cluster.

**Comment by webattitude** [comment]
Hi @a-robinson, same issue here : 
```
Error creating load balancer (will retry): Failed to create load balancer for service api-1dt-dc/review-k8s-4yl6zk: requested ip 35.186.202.220 is neither static nor assigned to LB ad3c982840d0311e7b45942010a84004(api-1dt-dc/review-k8s-4yl6zk)
```

**Comment by a-robinson** [comment]
@webattitude - I'm pretty sure that's a different problem. I'd recommend opening a new issue or a question on stackoverflow with more detail about your cluster and configuration.

**Comment by webattitude** [comment]
Ok thanks, right I misread this issue.
I've posted the whole warning message (http://stackoverflow.com/questions/42894405/kubernetes-on-google-failed-to-create-load-balancer-ip-static), yet it's weird since the IP is static...

**Comment by Zhomart** [comment]
It didn't work for me too when static ip address was global.

**Comment by gytisgreitai** [comment]
Same here, 
- created ip address with `gcloud compute addresses create vpn --global` and it did not work
- create ip address with `gcloud compute addresses vpn`, selected region and it worked

**Comment by Reifier** [comment]
Yep, same issue here. No go with static global address. Why?

**Comment by Lawouach** [comment]
I'm curious about this difference as well @a-robinson. If you have some insights :)

**Comment by a-robinson** [comment]
I recommend opening a new issue with the relevant details to try to catch someone else's attention. I don't have the time to look into this right now.
