### ISSUE TITLE
Explain how to turn on verbose logging in troubleshooting guide

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22723]

**Comment by bgrant0607** [comment]
The option doesn't even appear on the man pages. :-(

**Comment by bgrant0607** [comment]
`--v=4` for any kube-* component

**Comment by bgrant0607** [comment]
@dchen1107 to document how to add this and push the changes via salt

**Comment by bprashanth** [comment]
This should just be log_level, I think:
https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest#L95
https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/pillar/logging.sls
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L78

**Comment by bprashanth** [comment]
Though it shouldn't matter what options we start since we have configobjects, right?

**Comment by dchen1107** [comment]
There are a couple of ways to enable verbose logging for debugging. 

* If you are running cluster on GCE, upon cluster creation, you can export *_CLUSTER_LOG_LEVEL (* can be KUBELET, API_SERVER, CONTROLLER_MANAGER, and SCHEDULER). https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L78
* If your cluster is created already, you want to enable verbose logging for one of master component pods, you can ssh into your master node. All master component pod manifest files are located at /etc/kubernetes/manifest (default configured directory. If you changed it, you can find it through kubelet flags). You can modify the manifest file you care about by updating command:

```
# vi /etc/kubernetes/manifests/
etcd-events.manifest              etcd.manifest                     kube-apiserver.manifest           kube-controller-manager.manifest  kube-scheduler.manifest           
```

If your cluster is created with REGISTER_MASTER_KUBELET=true, you can view your master components pod status and logs through kubectl.

**Comment by bgrant0607** [comment]
Also, APISERVER_TEST_ARGS, KUBELET_TEST_ARGS, CONTROLLER_MANAGER_TEST_ARGS, SCHEDULER_TEST_ARGS

**Comment by bgrant0607** [comment]
@bprashanth Not all components (e.g., apiserver) have config types yet.

I also don't see any fields corresponding to --v in any existing ones.

We may want a special API to flip that dynamically, without restart. Or, if each component watches its config, we could have another config for which options can be changed dynamically.

**Comment by bprashanth** [comment]
> We may want a special API to flip that dynamically, without restart. Or, if each component watches its config, we could have another config for which options can be changed dynamically.

We did this for kube-proxy for the iptables mode in 1.1, we stored this config in the node annotations (this was before config objects came about)

**Comment by discordianfish** [comment]
Can somebody reopen this perfectly valid issue?
/remove-lifecycle stale
/lifecycle freeze
