### ISSUE TITLE
pkg/apis/componentconfig should not exist

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22725]
componentconfig is not an API served by apiserver, so it doesn't belong in /apis.

The config objects for components belong with those components, similar to scheduler config:
https://github.com/kubernetes/kubernetes/tree/master/plugin/pkg/scheduler/api

As an aside, we've also discussed moving more code into cmd:
https://github.com/kubernetes/kubernetes/issues/4851#issuecomment-132088777

cc @mikedanese @lavalamp

**Comment by mikedanese** [comment]
Where should shared objects live: e.g. LeaderElectionConfiguration?

**Comment by lavalamp** [comment]
Who shares that? Why not just copy it?

IMO, components should each have their own /apis/ tree.
