### ISSUE TITLE
/etc/hosts is not needed during run-prepared command through kubelet with rkt

### ISSUE THREAD

**Issue by wlodekb** [kubernetes/kubernetes#22739]
Actually there is mount point for `/etc/hosts` created from kubelet in pod manifest:

```
...,{
"name": "k8s-managed-etc-hosts",
"path": "/etc/hosts
},...
```

It seems that there is another [PR](https://github.com/coreos/rkt/pull/2251) in `rkt` project (not merge yet) that is closely related with it.
So, IMHO we can  we get rid off from creating this part in kubelet, and add `--hostname` flag similar like in `--dns` cmd line flag in kubeletet.
@yifan-gu, @iaguis

**Comment by yifan-gu** [comment]
@woodbor Yeah, kubelet doesn't need to manage /etc/hosts if rkt can populate it with correct content. 
Also see https://github.com/kubernetes/kubernetes/issues/21923

**Comment by dchen1107** [comment]
cc/ @ArtfulCoder we discussed this earlier.
