### ISSUE TITLE
nginx container vulnerable to CVE's

### ISSUE THREAD

**Issue by macropin** [kubernetes/kubernetes#22734]
The container `gcr.io/google_containers/nginx` has not been updated for a long time and is vulnerable to multiple SSL CVE's.

```
# docker images|grep "gcr.io/google_containers/nginx "
gcr.io/google_containers/nginx             latest              9f4cd86c1aec        11 months ago       425.6 MB
```

**Comment by mikedanese** [comment]
cc @bprashanth

**Comment by bprashanth** [comment]
Very possible, plase use `gcr.io/google_containers/nginx-slim:0.3` instead till we've repushed (https://github.com/kubernetes/contrib/tree/master/ingress/images/nginx-slim). Currently the nginx on gcr.io is only used in e2e testing as a placeholder container, AFAIK.

**Comment by mikedanese** [comment]
We now monitor this.
