### ISSUE TITLE
Fix 'kubectl get rc' for rcs with more than one container 

### ISSUE THREAD

**Issue by jmastr** [kubernetes/kubernetes#22742]
Commit 53d4b15 moved columns into wide option to make result more readable. However, the patch did not consider more than one container in the rc, e.g.:
```
NAME              DESIRED          CURRENT                                                               AGE
kube-dns-v10      1                1                                                                     5d
                  kube2sky         gcr.io/google_containers/kube2sky:1.12                                          
                  skydns           gcr.io/google_containers/skydns:2015-10-13-8c72f8c                              
                  healthz          gcr.io/google_containers/exechealthz:1.0
```
The desired output shall be probably something like that:
```
NAME              DESIRED          CURRENT                                                               AGE
kube-dns-v10      1                1                                                                     5d
```
and the remaining information in `-owide`.

**Comment by AdoHe** [comment]
@jmastr IIUC you want to move the containers display row to `-o wide` option, I am not sure whether we should do this, if we do this with rc, we have to do same thing with rs, ds etc, in order to keep consistence. @kubernetes/kubectl

**Comment by jmastr** [comment]
@AdoHe No, that was only my guess. I would like to revert commit 53d4b15. This also should keep the consistency...

**Comment by dchen1107** [comment]
commit 53d4b15 is in 1.2 release branch. I marked this as P0 and 1.2 milestone for now. We need to make the decision asap.

**Comment by bgrant0607** [comment]
We shouldn't revert the change. We should move the other containers to the wide output.

In general, `kubectl get` output should NEVER be multi-line.

**Comment by bgrant0607** [comment]
Could you please work on this, @AdoHe ?

**Comment by bgrant0607** [comment]
Personally, I think we could omit all of the container names.

**Comment by bgrant0607** [comment]
And probably repo names

**Comment by jmastr** [comment]
Having the container names was what I wanted in the first place. It gives a
nice overview. Good for a huge cluster.

Please do not remove that behavior...
Am 09.03.2016 22:27 schrieb "Brian Grant" <notifications@github.com>:

**Comment by AdoHe** [comment]
@bgrant0607 sure I will work on this.

**Comment by bgrant0607** [comment]
@AdoHe Thanks! Keep both container names and images for now. For multi-container pods, the output will be long, but we can improve the output more in 1.3.

**Comment by bgrant0607** [comment]
That is, keep them in the wide output

**Comment by bgrant0607** [comment]
@AdoHe How is it going? We need to get this fix in soon in order to make the next beta release. Do you need help?

cc @janetkuo @madhusudancs

**Comment by bgrant0607** [comment]
cc @kargakis @soltysh

**Comment by AdoHe** [comment]
@bgrant0607 I have opened a PR already #22772

**Comment by bgrant0607** [comment]
@AdoHe Sorry. I didn't see it, because it didn't reference this issue.
