### ISSUE TITLE
Fix infra for last two failing example e2es

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#22759]
The main work of fixing examples/ code for the obvious failures was done in #20999 .

We still have a couple of minor things left to do for making examples/ 100% perfect.

- cassandra: Needs to use the containers that are built from maven jars in the examples/ source.  Otherwise endpoints fail.  This is an easy fix.  Ive run cassandra many times, and confirmed its stable iff we use the new containers built fresh from source in examples/cassandra/java. 

- k8petstore: Network flakes out about 1/2 the time.  Maybe its due to parallel tests running on the same node.  To fix this, we will need test logs for the failures.   I ran it 50 times in a row on GCE 3 node clusters and saw 0 failures, so the flaking is definetly infra related.

cc @ixdy @kubernetes/sig-testing @brendandburns

**Comment by ixdy** [comment]
@jayunit100 Thanks for your hard work on this! Build logs and artifacts should be viewable at http://ci-test.k8s.io/kubernetes-e2e-gce-examples/.

**Comment by ixdy** [comment]
FYI, the petstore test has failed every build since 8197 (most recently in 8227), which suggests a recent regression. Before that, it failed in 8192, 8190, 8182, 8180, 8173, 8171, 8169, 8168, 8166, and more even older builds.

**Comment by jayunit100** [comment]
interesting.  ok.  I'll need to dig into the logs because for some reason, i cannot reproduce these failures when running it on a GCE cluster built via kube-up.sh.

**Comment by spiffxp** [comment]
What do we think about closing this?  Looking at https://k8s-testgrid.appspot.com/google-gce#gce-examples, cassandra's been pretty happy... but I can't find any results for the k8spetstore example

**Comment by jayunit100** [comment]
Close, `examples/` as a whole is going to die eventually i think.  k8petstore works on any machine w/ kubectl setup.
