### ISSUE TITLE
Local cluster should support DNS

### ISSUE THREAD

**Issue by mattseh** [kubernetes/kubernetes#22752]
Hi,

This guide is a good start - http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html - but IMO it doesn't go far enough. I think most people will want the DNS (and maybe the UI) addons, but the information on how to do this is scattered around. It'd be nice to be able to do the getting started guide, then instantly move on to one of the examples (which require DNS).

**Comment by mikedanese** [comment]
Feel free to make it better!

https://github.com/kubernetes/kubernetes.github.io

**Comment by bgrant0607** [comment]
See efforts here: https://github.com/kubernetes/minikube

cc @vishh @dlorenc

**Comment by bgrant0607** [comment]
See also #8413

**Comment by luxas** [comment]
The local cluster does support DNS, but there are manual step that have to be taken.
[Here's how to do it](https://github.com/luxas/kube-deploy/blob/1d50a01f62732fa9441875875235b774c25e2e3d/docker-multinode/deployDNS.md) and [here's one example manifest](https://github.com/luxas/kube-deploy/blob/1d50a01f62732fa9441875875235b774c25e2e3d/docker-multinode/skydns.yaml.in) that works cross-platform (`amd64`, `arm`, `arm64` and `ppc64le`)

I'll work on getting `kube-addon-manager` cross-platform, and getting it merged with `hyperkube`.
That's the goal for `v1.3`

**Comment by mikedanese** [comment]
./hack/local-cluster-up.sh does not support dns last I checked
