### ISSUE TITLE
Automated docker validation tests

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#22765]
We introduced node test infrastructure for 1.2 release, and engineers are working on docker validation test suite too. We should automate today's docker release validation process by fetching the latest docker release candidate from docker.io and run our node conformance tests. 

cc/ @kubernetes/goog-node

**Comment by dchen1107** [comment]
@liangchenye I am assigning this one to you for now. Please let us know if you don't have the bandwidth for this.

**Comment by liangchenye** [comment]
@dchen1107 I have 1/3 of my working hour on this between March and April. I'll update my progress by submit PRs.

**Comment by dchen1107** [comment]
@liangchenye Could you delegate this to one of your co-workers since I don't have their github names? Thanks!

**Comment by liangchenye** [comment]
@dchen1107, I'll catch up with the 'docker unique test' this week and see if it is necesary to delegate to other co-workers.

**Comment by Random-Liu** [comment]
Also ref #21013
