### ISSUE TITLE
Fuzzer for LabelSelector type

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#22761]
LabelSelector type fields - keys, values and operators, have more stringent validation requirements than other string fields. The current fuzzer implementation has no capability to generate the values that conform to these validation requirements. A fuzzer that satisfies these requirements must be implemented.

cc @bgrant0607 @lavalamp

**Comment by lavalamp** [comment]
@madhusudancs you can write arbitrary fuzzing functions; see https://github.com/kubernetes/kubernetes/blob/108f72265774c39637623b2b20a07dfd1a06d972/pkg/api/testing/fuzzer.go#L42
