### ISSUE TITLE
Unable to restrict pod access to Kubernetes API

### ISSUE THREAD

**Issue by mlucy** [kubernetes/kubernetes#22764]
Hi,

I'm using GKE, and trying to set it up so that individual pods can't issue commands to the Kubernetes API.  (I'm planning to run arbitrary code in these pods, so it would be really bad if a single pod getting pwned gave someone access to all the other pods.)

Is there a standard way of doing this?  GKE is automatically mounting a token at `/var/run/secrets/kubernetes.io/serviceaccount/token`, and as far as I can tell:

* There's no way to tell Kubernetes not to mount that secret.
* There's no way to tell Kubernetes to restrict a pod's ability to access the master over the network.
* It *is* possible to tell Kubernetes to use a specific serviceaccount for a pod, but:
  - It isn't possible to set up a serviceaccount that doesn't automount a token.
  - It isn't possible to set up a serviceaccount with no privileges.
  - It isn't possible to tell the pod to not use a serviceaccount.

---

My current workaround is to do `chmod o-rx /var/run/secrets/kubernetes.io` as root on startup and then run the arbitrary code as an unprivileged user, but that seems like a pretty scary solution.  So, three questions:

* Is there any way to not let individual pods access the Kubernetes API?
* Is there any way in general to prevent pods from accessing certain things over the network?
* Is the workaround I'm using at the moment actually safe?

Thanks!

**Comment by MaksymBilenko** [comment]
+1 also I've noticed:
When I'm using credentials at `/var/run/secrets/kubernetes.io` for default namespace I'm able to create/delete rc/svc at kube-system namespace and other.
Is there a way to configure security for this?
Cheers

**Comment by davidopp** [comment]
cc/ @roberthbailey @a-robinson

**Comment by davidopp** [comment]
cc/ @erictune

**Comment by roberthbailey** [comment]
@erictune is working on this; see https://github.com/kubernetes/kubernetes/issues/16779

**Comment by davidopp** [comment]
Thanks; @MaksymBilenko please direct any followup questions to #16779.
