### ISSUE TITLE
leader election issue for controller manager and scheduler

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#22775]
When multiple controller managers are scheduled onto the same node while leader elect is enabled, they would all think themselves as leader because  `HolderIdentity` is set to be hostname, see https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L159.

**Comment by AdoHe** [comment]
IIRC this should not be a problem even in multi master nodes, I am not certainly sure.

**Comment by zhouhaibing089** [comment]
Firstly, It is truth in current situation that one host could not run multiple instances of controller-managers and kube-schedulers due to the log file(`/var/log/kube-controller-manager.log`) and port binding(hostnetwork).

Secondly, it will not cause problem since both controller-manager and kube-scheduler are all running as static pods.

My point is that hostname is not reliable for the identity, in future, I believe that control-plane need not have to be running as static pods.

**Comment by lavalamp** [comment]
Thank you for the report and the PR. I will make some comments in the PR.

**Comment by davidopp** [comment]
cc/ @mikedanese

**Comment by mikedanese** [comment]
This is only true if they are running on the hostNetwork in which case you also likely have a port conflict. unless schedulers run on different ports. The hostname is the pod name which is unique even if the pods are on the same node.

**Comment by zhouhaibing089** [comment]
@mikedanese thanks for this clarification, it turns out to be true that `hostname` is the same as `podname` without setting `hostNetwork` to be true.
