### ISSUE TITLE
Secret dir mounted, but empty

### ISSUE THREAD

**Issue by macpoint** [kubernetes/kubernetes#22778]
Hi, 
I know similar issues have been already discussed, but this seems to be different. I have a secret:

```
$ kubectl get secret redissecret -o yaml
apiVersion: v1
data:
  password: aGVzbG8=
kind: Secret
metadata:
  creationTimestamp: 2016-03-10T09:32:17Z
  name: redissecret
  namespace: app
  resourceVersion: "1400750"
  selfLink: /api/v1/namespaces/app/secrets/redissecret
  uid: fabb7240-e6a2-11e5-a824-00163e5316db
type: Opaque
```

... and a pod

```
apiVersion: v1
kind: Pod
metadata:
  name: redis-test
  annotations:
    volumesUser: oracle
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:3.0.6
    volumeMounts:
      - name: mysecret
        mountPath: /var/mysecret
        readOnly: true
  volumes:
  - name: mysecret
    secret:
      secretName: redissecret
  nodeName: somename
  restartPolicy: Always
```

The pod is started without any errors, the pod describe command shows the secret volume:

```
Volumes:
  mysecret:
    Type:   Secret (a secret that should populate this volume)
```

But the mount point is empty:

```
$ kubectl exec redis-test -- ls -l /var/mysecret
total 0

$ kubectl exec redis-test -- mount | grep mysecret
/dev/xvda2 on /var/mysecret type ext4 (ro,relatime,data=ordered)
```

And this is interesting - docker inspect shows the bind and mount

```
"HostConfig": {
        "Binds": [
            "/var/lib/kubelet/pods/c1704ca6-e6a8-11e5-a824-00163e5316db/volumes/kubernetes.io~secret/mysecret:/var/mysecret",
            "/var/lib/kubelet/pods/c1704ca6-e6a8-11e5-a824-00163e5316db/etc-hosts:/etc/hosts",
            "/var/lib/kubelet/pods/c1704ca6-e6a8-11e5-a824-00163e5316db/containers/redis/62cb03eff6e467c100781314d3320e43ba8f7165f36ed0226c20c83544fb7f28:/dev/termination-log"
        ],
```

...

```
{
            "Source": "/var/lib/kubelet/pods/c1704ca6-e6a8-11e5-a824-00163e5316db/volumes/kubernetes.io~secret/mysecret",
            "Destination": "/var/mysecret",
            "Mode": "ro",
           "RW": false
},
```

The file seems to be in place:

```
$ ls -l /var/lib/kubelet/pods/c1704ca6-e6a8-11e5-a824-00163e5316db/volumes/kubernetes.io~secret/mysecret
total 4
-r--r--r-- 1 root root 5 Mar 10 10:35 password
```

I have also tried mounting the secret volume rw and creating a file in /var/mysecret from inside the container. But this new file did not appear in /var/lib/kubelet/pods/c1704ca6-e6a8-11e5-a824-00163e5316db/volumes/kubernetes.io~secret/mysecret. 

Although the docker inspect shows the dir as mounted, it seems to me that it is not.

Not using ServiceAccounts, Kubelet is run directly (not run in a container).

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}

$ docker info
Containers: 24
Images: 96
Storage Driver: devicemapper
 Pool Name: docker-202:2-135642-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/docker_vg/data
 Metadata file: /dev/docker_vg/metadata
 Data Space Used: 4.429 GB
 Data Space Total: 71.4 GB
 Data Space Available: 66.97 GB
 Metadata Space Used: 7.246 MB
 Metadata Space Total: 3.754 GB
 Metadata Space Available: 3.747 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Library Version: 1.02.95-RHEL6 (2015-09-08)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.8.13-118.el6uek.x86_64
Operating System: Oracle Linux Server 6.7
CPUs: 4
Total Memory: 9.789 GiB
Name: somename
ID: WOPP:32WW:XXUU:YOZX:K3L2:QXPK:IX73:U2MG:GNDQ:MAQF:B7XH:UN3G
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

$ docker version
Client:
Version:      1.8.3
API version:  1.20
Go version:   go1.4.2
Git commit:   f0bb124
Built:        Wed Oct 14 04:06:48 UTC 2015
OS/Arch:      linux/amd64

Server:
Version:      1.8.3
API version:  1.20
Go version:   go1.4.2
Git commit:   f0bb124
Built:        Wed Oct 14 04:06:48 UTC 2015
OS/Arch:      linux/amd64
```

**Comment by jayunit100** [comment]
As a sanity check: Can you run the `EmptyDir` e2e tests and confirm how many pass?  That will help us diagnose the details better.

**Comment by macpoint** [comment]
Will try that. Before I do that, I think I am facing the issue when Docker cannot see shares (tmpfs in this case) mount after the daemon starts. I am not running on systemd so no luck with MountFlags=slave.

**Comment by jayunit100** [comment]
Also run `--ginkgo.focus=Secret` , that will be a very clear diagnosis i bet.

**Comment by lavalamp** [comment]
@derekwaynecarr ideas?

**Comment by davidopp** [comment]
ping @derekwaynecarr

**Comment by aanm** [comment]
@jayunit100 Have you try it with docker 1.9.1?

**Comment by thockin** [comment]
@pmorie @swagiaal trivial attempt at repro did not repro the problem...

**Comment by jayunit100** [comment]
I haven't been able to either... maybe what we need is a node conformance test for this type of thing ... As is not sure if we can reproduce or diagnose unless it's done using vagrant or Kube-up

**Comment by jayunit100** [comment]
Vote to close unless @macpoint is still having this issue , in which case let's run the e2e suite battery of EmtpyDir tests and see what passes

**Comment by derekwaynecarr** [comment]
Assuming Oracle Linux 6 is tracking RHEL 6, then RHEL does not support running docker on RHEL 6.

https://access.redhat.com/solutions/1378023

@eparis - am I missing something here?  The kernel version is different than RHEL 6.7 so it looks like the other Oracle kernel, so I am not sure what behavior to expect here or can really claim that this should work.

**Comment by macpoint** [comment]
@derekwaynecarr AFIK Oracle has backported docker required features to its kernel (UEK 3.8.13-68.3.4.el6uek.x86_64 - this is the version that I run) and Docker should be supported on 6.7 (https://docs.oracle.com/cd/E37670_01/E37355/html/section_kfy_f2z_fp.html) ... However I admin that this combination (UEK 3.8, Docker 1.8.3, OEL 6.7) might cause the issue ...

@aanm No, haven't tried that. The OS image I need to use is comes with UEK 3.8 which is not supported by Docker 1.9.1 ...

**Comment by pmorie** [comment]
@macpoint I would try @jayunit100's suggestion of running the emptyDir e2es and see if you can recreate the failure that way.

**Comment by pmorie** [comment]
@macpoint there's also a secrets e2e you can use as a reproducer

**Comment by castrojo** [comment]
This issue is over a year old, do you still have this issue with newer versions of kubernetes? Should we close this issue? Thanks!

**Comment by macpoint** [comment]
@castrojo yes, closing

**Comment by ricardbejarano** [comment]
@macpoint did you ever solve this? how?

I'm facing the same issue.
