### ISSUE TITLE
null pointer error with openstack cloud provider

### ISSUE THREAD

**Issue by PradeepSingh1988** [kubernetes/kubernetes#22789]
Hi, 

--Version Info
`Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
`

I am trying to use cinder volume in my container.

I am starting kubelet with below command.
`/opt/bin/kubelet --address=10.0.16.6 --port=10250 --hostname_override=10.0.16.6 --api_servers=10.0.16.3:8080 --logtostderr=false --log_dir=/var/log/kubernetes --v=4 --cloud-provider=openstack --cloud-config=/etc/init/cloud_config.conf`

My cloud_config.conf is as below:
`[Global]
auth-url=https://*.*.*.*:5000/v2.0
username=admin
password=*******
tenant-id=6779d980830f4abcb60ae6cac5c810c8`

I am getting below error:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x53c6e2]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/cloudprovider/openstack.(_OpenStack).Instances(0x0, 0x0, 0x0, 0x9)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/openstack/openstack.go:162 +0x7e2
k8s.io/kubernetes/cmd/kubelet/app.RunKubelet(0xc208180000, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:588 +0x12a
k8s.io/kubernetes/cmd/kubelet/app.(_KubeletServer).Run(0xc2081dc000, 0xc208066990, 0x0, 0x9, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:382 +0x13a2
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:46 +0xd0

goroutine 7 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1c03720)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 18 [sleep]:
k8s.io/kubernetes/pkg/util.Until(0x15181a8, 0x12a05f200, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:114 +0x98
k8s.io/kubernetes/pkg/util.Forever(0x15181a8, 0x12a05f200)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:94 +0x3b
created by k8s.io/kubernetes/pkg/util.InitLogs
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/logs.go:50 +0x9f

goroutine 26 [IO wait]:
net.(_pollDesc).Wait(0xc2080cb020, 0x72, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc2080cb020, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).accept(0xc2080cafc0, 0x0, 0x7f953e810e88, 0xc2080cdbf8)
        /usr/src/go/src/net/fd_unix.go:419 +0x40b
net.(_TCPListener).AcceptTCP(0xc20803a768, 0x5d9124, 0x0, 0x0)
        /usr/src/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20803a768, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1976 +0x4c
net/http.(_Server).Serve(0xc208047560, 0x7f953e81c690, 0xc20803a768, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1728 +0x92
net/http.(_Server).ListenAndServe(0xc208047560, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1718 +0x154
k8s.io/kubernetes/pkg/kubelet/cadvisor.func·001()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:99 +0x5f
created by k8s.io/kubernetes/pkg/kubelet/cadvisor.(*cadvisorClient).exportHTTP
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:105 +0x4c2`

Could you please help me out  with this

**Comment by spothanis** [comment]
I think it is an issue with your openstack config file
Please see http://stackoverflow.com/questions/32714756/kublet-doesnt-start-with-cloud-provider-openstack/32721296#32721296 for more info

**Comment by PradeepSingh1988** [comment]
@spothanis , thanks i will check on monday and will update accordingly.

**Comment by xsgordon** [comment]
@PradeepSingh1988 is this issue still valid?

**Comment by xiangpengzhao** [comment]
Since there is no update of this issue for more than one year (and it was found in v1.0), we are closing this.

@thockin
