### ISSUE TITLE
roles[${ii}]: unbound variable error in ubuntu environment

### ISSUE THREAD

**Issue by shshang** [kubernetes/kubernetes#22799]
Hi, guys:

I ran into this issue in my ubuntu environment since 2 days ago. The kube-up.sh just ended here and installation was incomplete. Would you please take a look?

...
docker stop/waiting
docker start/running, process 2076
Connection to 172.16.7.13 closed.
Validating master
Validating shshang@172.16.7.11
Validating shshang@172.16.7.12
Validating shshang@172.16.7.13
./../cluster/../cluster/ubuntu/util.sh: line 47: roles[${ii}]: unbound variable

Thanks!

Shixiong

**Comment by robertBrem** [comment]
I have exactly the same problem!

**Comment by louisyw** [comment]
I have the same problem!

... Starting cluster using provider: ubuntu
... calling verify-prereqs
... calling kube-up
~/kubernets/kubernetes/cluster/ubuntu ~/kubernets/kubernetes/cluster
Prepare flannel 0.5.0 release ...
Prepare etcd 2.2.0 release ...
Prepare kubernetes 1.0.5 release ...
Done! All your binaries locate in kubernetes/cluster/ubuntu/binaries directory
~/kubernets/kubernetes/cluster
./../cluster/../cluster/ubuntu/util.sh: line 47: roles[${ii}]: unbound variable

**Comment by ctrld** [comment]
Bug was introduced in the commit 9c5d82d9bd72d2f837eb11b50500c31a0d38d0fa

**Comment by shshang** [comment]
Hi, Oleg:

I changed the shell script and it really worked well now!

Thanks for the help!

Shixiong

**Comment by nebirhos** [comment]
Solved by rolling back commit 9c5d82d.
Why this is not reverted on release-1.2 branch?

**Comment by bgrant0607** [comment]
This was fixed by PR #22845? 

Nobody requested that it be cherrypicked into the release branch.

**Comment by goltermann** [comment]
does this issue still exist?

**Comment by anmolnagpal** [comment]
Getting same Error

	root@ubuntu:~/kubernetes/cluster# KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
	... Starting cluster using provider: ubuntu
	... calling verify-prereqs
	Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
	... calling kube-up
	~/kubernetes/cluster/ubuntu ~/kubernetes/cluster
	Prepare flannel 0.5.5 release ...
	Prepare etcd 2.3.1 release ...
	Prepare kubernetes 1.4.6 release ...
	Done! All your binaries locate in kubernetes/cluster/ubuntu/binaries directory
	~/kubernetes/cluster
	./../cluster/../cluster/ubuntu/util.sh: line 47: roles_array[${ii}]: unbound variable

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
because kube-up

**Comment by bgrant0607** [comment]
We're trying to move these providers out of tree. Closing here
