### ISSUE TITLE
Update HPA design doc

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#22797]
https://github.com/kubernetes/kubernetes/blob/master/docs/design/horizontal-pod-autoscaler.md

@madhusudancs could you please update Scale Subresource section? 

cc @mwielgus @fgrzadkowski

**Comment by fgrzadkowski** [comment]
To be honest I think that we shouldn't update design docs. Overtime we'd have to update too many of them.

As a workaround I'd suggest to:
1. Add a warning at the top that this design doc might be updated
2. Add "last update" timestamp to the design doc.

@bgrant0607 @davidopp

**Comment by bgrant0607** [comment]
@fgrzadkowski

I'd rather not have obsolete docs in the tree.

We need to ensure that everything in this doc that's still relevant is covered and up to date somewhere.

We definitely need a doc for the scale API. (And for the rest of the API #19680)

The kubectl details needs to be covered in kubectl user docs. Other user-facing details need to be in an autoscaling guide and example in the user guide.

We need documentation for the HPA controller-manager flags and other details, in the code.

Ensure there are github issues for the incomplete roadmap items.

cc @johndmulhausen

**Comment by fgrzadkowski** [comment]
@bgrant0607 SGTM. I guess it's a policy decision so if we decide to update all design docs I'm fine with this :)

**Comment by bgrant0607** [comment]
@fgrzadkowski Yes, please file an issue that we should update proposals and design docs. Some of them should really be converted to user docs, too.

**Comment by davidopp** [comment]
I don't think it's a good use of time to update design docs. Features morph infinitely over time; it's not practical to keep their original design doc up to date. I don't think people expect that a design doc will even reflect what was originally implemented, much less how the feature exists at the time they are reading the design doc.

Now, I *do* agree "We need to ensure that everything in this doc that's still relevant is covered and up to date somewhere." When something is implemented, we should write proper user guide documentation for it, which we keep up-to-date indefinitely, 

I don't think anything @bgrant0607 contradicts this, except "I'd rather not have obsolete docs in the tree." I think there's no way around that with design docs (and proposals), and people should just understand that's how such docs work. We can put a README.md in proposals/ and design/ to explain this.

**Comment by fgrzadkowski** [comment]
@davidopp @bgrant0607 AFAIU you're both saying different things here :) We have already updated user guides. Should we update the [design doc](https://github.com/kubernetes/kubernetes/blob/master/docs/design/horizontal-pod-autoscaler.md)?

**Comment by davidopp** [comment]
Please hold off on doing it until I discuss with Brian. I definitely don't think this is a good policy.

**Comment by fgrzadkowski** [comment]
@davidopp Any update here?

**Comment by davidopp** [comment]
I talked to @bgrant0607 about this just now. He was OK with just putting a big warning at the top of any design docs that contain out-of-date information, warning that the doc is just for historical purposes and pointing to the up-to-date docs. This assumes we actually document our APIs properly and write user-guide docs for the feature that we keep up-to-date. So we need to get better at that -- I agree with him that we should *not* have any features that are only documented in a design doc that is not up-to-date.

**Comment by bgrant0607** [comment]
And I reserve the right to gut/delete out-of-date docs at some point.

**Comment by fgrzadkowski** [comment]
SGTM. @piosz Can you please look into this?
