### ISSUE TITLE
Should we add daemonset info to docs/user-guide too?

### ISSUE THREAD

**Issue by amygdala** [kubernetes/kubernetes#22798]
I noticed that the daemonset info is only under docs/admin, not part of the user guide. 
Maybe there should be `user-guide` info on it too, since some of our examples pitched to 'users' use daemonsets and that is where they will look for it.  Feel free to just close if you disagree...

cc @johndmulhausen @bgrant0607

**Comment by bgrant0607** [comment]
The examples are perhaps dubious, but any examples that mention it should link to where it lives. It belongs in admin. It's not safe for general usage.
