### ISSUE TITLE
e2e flake: "Kubectl client Simple pod should support inline execution and attach" hangs

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#22814]
Log at http://pr-test.k8s.io/22762/kubernetes-pull-build-test-e2e-gce/32254/ while testing #22762.

Looks like this test hung at the "executing a command with run and attach with stdin with open stdin should remain running":

```
STEP: executing a command with run and attach with stdin with open stdin should remain running
Mar 10 09:05:30.376: INFO: Running '/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/kubernetes/platforms/linux/amd64/kubectl --server=https://104.154.28.247 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/.kube/config --namespace=e2e-tests-kubectl-asrfq run run-test-3 --image=busybox --restart=Never --attach=true --leave-stdin-open=true --stdin -- sh -c cat && echo 'stdin closed''
Mar 10 09:05:35.116: INFO: stderr: ""
Mar 10 09:05:35.116: INFO: stdout: "Waiting for pod e2e-tests-kubectl-asrfq/run-test-3-5c56n to be running, status is Pending, pod ready: false\nWaiting for pod e2e-tests-kubectl-asrfq/run-test-3-5c56n to be running, status is Pending, pod ready: false"

---------------------------------------------------------
Received interrupt.  Running AfterSuite...
```

Based on output and looking at the code, it seems this may have gotten stuck in [`util.GetFirstPod`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L599-L613), which looks like it may loop forever if no pods match the selector.

**Comment by soltysh** [comment]
@ixdy actually it was related to abug in the code so this can be closed as well. Thx

**Comment by ncdc** [comment]
@soltysh what PR fixed it? #22762?

**Comment by ixdy** [comment]
@soltysh even if it was due to a bug in the code, the test should have failed instead of hanging, probably.

**Comment by soltysh** [comment]
@ixdy the thing is this test attaches to a running pod. Exec timeout is the
only reasonable way of failing it. See execOrDie in e2e's util.go.

**Comment by ixdy** [comment]
@soltysh well, as I mentioned originally, it appears that `execOrDie` returned without hanging. It was the later `GetFirstPod` call that never returned.

**Comment by lavalamp** [comment]
@soltysh Can you send a PR?

**Comment by soltysh** [comment]
@lavalamp sorry for the confusion, but it was already addressed in the PR I've noticed it happening, iow. #22762.
