### ISSUE TITLE
What is the alternative for "A mirror pod may not reference secrets" ?

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#22826]
Today I got hit by this old issue #8180 while creating a static pod with secrets. What is the recommended alternative for this use-case? We would like to not wait for daemonsets, since daemonsets are not going GA with 1.2 . Also, it will be great to document these various corner cases. Testing stuff in k8s is really time consuming.

**Comment by yujuhong** [comment]
@codefx9, if your goal is to run a pod on every node and allows the pod to access the secrets (and you don't want to use daemonset until it goes GA) you can try the old trick of assigning a host port to your container to ensure that only one pod can be scheduled on a node. Not recommended but it should work.

**Comment by lavalamp** [comment]
Yup, wait for daemonset-- it's going beta in 1.2, it should be usable. Or use the trick @yujuhong describes.
