### ISSUE TITLE
"error that is not an unversioned.Status: too old resource version"

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#22830]
Somehow, a raw etcd error is finding its way into apiserver. I suspect the InterpretEtcdError functions are perhaps not catching it, or not getting called everywhere they ought to be.

**Comment by lavalamp** [comment]
Split from #22024.

It seems some watch requests return 500 (example in #22024) and print a stack trace when this happens, this should *not* happen.

@wojtek-t @smarterclayton @kubernetes/sig-api-machinery 

(Also @janetkuo since she fixed another thing about these functions last week)

**Comment by wojtek-t** [comment]
@lavalamp - from #22024 it seems that they are using v1.1.3
The fix for it: #16628 was merged on December 1 - which means it's not included in 1.1.3
So it's already fixed, by not in that old release

**Comment by lavalamp** [comment]
@wojtek-t Thanks!
