### ISSUE TITLE
How to Determine the Pod Terminating status using REST API

### ISSUE THREAD

**Issue by pgmahesh** [kubernetes/kubernetes#22839]
Hi,

We like to understand how the terminating status "Terminating" can be determined using the response payload of interface /Namespaces/<namespace>/pods. We always noticed that the Status.Phase is "pending" and Even the Container.statuses is "running". 

However when we use Kubectl to know the status it indicates "Terminating". can you please let us know how to determine the pods status "Terminating"?.

Seems to be some discrepancy between the Rest API response and the Kubectl response for the status of the pods. please clarify.

Regards
Maheshwaran.G

**Comment by AdoHe** [comment]
@pgmahesh ptal [https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L561-L590](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L561-L590)

**Comment by pgmahesh** [comment]
Thanks a lot. it was very useful.
why not "Terminating" not of status.Phase?.

**Comment by cogitate** [comment]
Is there any way to determine the status 'Terminating' using kubernetes REST API?

**Comment by polonel** [comment]
Link is dead. Any Information on this?

**Comment by jeffmhastings** [comment]
It seems like kubectl looks at `metadata.deletionTimestamp`. That will be set when the pod is terminating.

**Comment by radu-matei** [comment]
Shouldn't this be a part of the pod status?

**Comment by jbbarth** [comment]
Link of the code as it was on March 2016 (similar to original link above I guess): https://github.com/kubernetes/kubernetes/blob/v1.2.0/pkg/kubectl/resource_printer.go#L561-L590

The code now lives here: https://github.com/kubernetes/kubernetes/blob/a9f6b93b62a98598913180c640ab044c85a6718b/pkg/printers/internalversion/printers.go#L695-L781
