### ISSUE TITLE
Support for AWS ELB SSL Services

### ISSUE THREAD

**Issue by zombor** [kubernetes/kubernetes#22854]
Right now services that setup amazon ELBs setup a TCP port 443 listener. It would be swell if there was a way to setup an HTTPS protocol listener that included specifying an SSL certificate.

Currently I have to manually go into the aws console and re-configure the ELB for each service to use https with our certificates, which isn't really manageable because k8s occasionally reconfigures them to match the service definition.

**Comment by zombor** [comment]
Paging @justinsb !

**Comment by stepanstipl** [comment]
+1
I was thinking about implementing support for this via annotations, in similar fashion that support for internal ELBs is implemented via `service.beta.kubernetes.io/aws-load-balancer-internal`.

At first I would propose to implement most common and relatively simple use cases - add support for http, https and ssl ELB type, in case of https and ssl allow to set certificate (certificate would have to be pre-uploaded to AWS - outside of this scope) and in case of https and ssl allow to specify ssl port.


I propose to add following annotations:
- `service.beta.kubernetes.io/aws-load-balancer-protocol` - ELB type, one of tcp (default), ssl, http, https
- `service.beta.kubernetes.io/aws-load-balancer-ssl-port` - ELB port for https & ssl types (defaults to 443)
- `service.beta.kubernetes.io/aws-load-balancer-ssl-certificate` - SSL certificate name (no default, error if ELB type is https or ssl and none specified)

Limitations:
- for https & ssl the load balancer would be limited to one listener (at least in initial implementation)
- protocol would be set for the ELB as a whole (all listeners will have same one) as opposed to per listener

My reasons for this are mainly:
- Allow to use SSL handled by AWS ELB
- Allow to use L7 protocol, mainly because this preserves original IPs in X-Forwarded* headers

I would like to know your thoughts first.

@zombor would this cover your use case & make sense?
@justinsb I'm happy to pick this up and start working on it if you think it would make sense

**Comment by zombor** [comment]
> would this cover your use case & make sense?

Generally, yes. Right now I have two listeners setup on each ELB, one for port 80 and the other for 443 (since we want http -> https redirection). I have to do the redirection in software as I don't think there are any redirection options on ELBs like there would be with haproxy.

**Comment by stepanstipl** [comment]
Thanks for comment, so you want both http & https. My use-case is https only, but I can see that keeping both http & https (or tcp & ssl) around makes sense. Perhaps one more annotation, smth. like:
- `service.beta.kubernetes.io/aws-load-balancer-ssl-only` - if set to true, only https (ssl) listener is set, else both original and ssl one are created

would cover this. (Not sure what would I prefer as default for this one).

**Comment by rata** [comment]
It might make sense to write an Ingress Controller, as the one on GCE (beta), that handles the SSL with an ELB. I haven't looked into it.

**Comment by zombor** [comment]
Yeah, if there's an Ingress controller that will setup an ELB that would probably be best. I haven't heard of any such thing though.

**Comment by rata** [comment]
On Thu, Mar 17, 2016 at 03:31:41PM -0700, Jeremy Bush wrote:
> Yeah, if there's an Ingress controller that will setup an ELB that would probably be best. I haven't heard of any such thing though.

There isn't, I'm just saying maybe this is something to take into account when
solving this :)

**Comment by therc** [comment]
There isn't one yet, but I'll be working on the Ingress controller for AWS.

**Comment by rata** [comment]
On Thu, Mar 17, 2016 at 03:36:00PM -0700, Rudi C wrote:
> There isn't one yet, but I'll be working on the Ingress controller for AWS.

Ohh, great! :-)

**Comment by mogren** [comment]
I'm very interested in the "Allow to use L7 protocol, mainly because this preserves original IPs in X-Forwarded* headers", that would solve a lot of my problems

**Comment by paralin** [comment]
We need this too in our use cases! :)

**Comment by rata** [comment]
@paralin if it helps, as a workaround until there is an option to manage this within kubernetes, we are using services with type "NodePort". This creates a service that when you connect to any node in that port (can be auto-selected or selected manually), it is redirected to the appropriate pods (type LoadBalancer does this too).

So, we then create an ELB and attach it to the ASG. And use the port created in the service as a destination port in the ELB. This means you handle the ELB yourself, but you can do SSL or whatever you want in the ELB.

**Comment by zombor** [comment]
> we are using services with type "NodePort".

This is what I'm doing as well as a "workaround". My ELBs are all managed by hand.

**Comment by paralin** [comment]
@rata @zombor That's a problem, what if the instances die or get replaced? You need to manually update the host list.

**Comment by zombor** [comment]
> You need to manually update the host list.

Yep. This issue is for doing it automatically. What we described is a workaround if you can't use Ingress controllers for some reason.

**Comment by rata** [comment]
On Thu, Apr 07, 2016 at 09:11:13AM -0700, Christian Stewart wrote:
> @rata @zombor That's a problem, what if the instances die or get replaced? You need to manually update the host list.

No. You can not select any instance when creating the ELB and go to the ASG and
attach the created ELB to it. Then, when you scale the ASG up/down, instances
will be added or removed. Sorry if it wasn't clear before.

**Comment by mettjus** [comment]
I need to add HTTPS to some services in my k8s cluster. I also appreciate the possibility to manage the worker count via AutoScalingGroups.

To achieve the result I first created the ELB with a k8s service and then manually added HTTPS to it. I tried scaling up and down the ASG (also manually killed some instances) and the ELB didn't lose the HTTPS configuration. To me it looks like the best workaround at this time.

@zombor could you provide an example (if this is the case) of when an ELB gets reconfigured by k8s and loses its HTTPS configuration, except that in the case of manually modifying the service via `kubectl`?

**Comment by zombor** [comment]
@mettjus From my experience, the ELB was reset "randomly", I could not reliably reproduce it. I just got angry emails from clients about services being down :(

**Comment by therc** [comment]
It gets reset exactly when kube-controller-manager restarts. #23495 provides a solution until Ingress support is done.

**Comment by mettjus** [comment]
@zombor I'd love to avoid the scenario you describe ;)

Thanks @therc, I'll have a look at the PR. If I'm not wrong it would imply a bit of work to deploy it (I guess until the PR gets eventually merged I should make a custom build of k8s).

**Comment by zombor** [comment]
@mettjus I've found the best way to manage this right now is via `NodePort` services and setting up ELBs by hand. I've had 100% uptime since then.

**Comment by mettjus** [comment]
@zombor I was planning to attempt also this approach but from what I remember when you manually create an ELB it cannot be bound in any way to the ASG node count (you will need to manually add/remove the instances to/from the ELB, which to be honest might be an acceptable compromise until I can work out a better solution, or implement a custom automation)

**Comment by rata** [comment]
@mettjus No. You can assign the ASG to a load balancer and the ELB will automatically have them. See my comments above explaining just that.

**Comment by justinsb** [comment]
I believe this is now implemented, via https://github.com/kubernetes/kubernetes/pull/23495.  Please reopen if I've overlooked something (we also have https://github.com/kubernetes/kubernetes/issues/23484 for tracking 1.4 improvements)

**Comment by therc** [comment]
I'm trying to finish #24978 today

**Comment by therc** [comment]
Errrr... I meant #26268 (mixed HTTP/HTTPS)
