### ISSUE TITLE
decide on insecureSkipVerify setting when run against secured etcd

### ISSUE THREAD

**Issue by adohe** [kubernetes/kubernetes#22858]
We just restore ability to run against secured etcd here #21535, but InsecureSkipTLSVerify is still questionable in secured etcd. We need to decide whether we should add this. @liggitt @timothysc @bgrant0607 @xiang90 ptal.

**Comment by bgrant0607** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
We're doing client cert to etcd, right? So I think it's OK, since etcd will be doing the cert checking, not apiserver. But maybe we can get confirmation from @xiang90.

**Comment by liggitt** [comment]
This is about the client verifying the server's serving cert (2-way TLS), and whether the client has to have a way to disable that check.

**Comment by lavalamp** [comment]
@liggitt you mean whether the client has a way to *enable* that check?

**Comment by liggitt** [comment]
no... `TLSInfo.ClientConfig()` never returns a `&tls.Config{}` with `InsecureSkipVerify` set to true.

**Comment by lavalamp** [comment]
Oh, you're right. That changed since I saw it.

**Comment by lavalamp** [comment]
I think admins can add their ca to the system list if they want to use self-signed certs for etcd.

Will raise priority again if I see a bunch of admins here complaining. :)
