### ISSUE TITLE
Stop using scheme.ObjectKind

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#22866]
Based on discussion in https://github.com/kubernetes/kubernetes/issues/22484.

Now, that we have multiple possible kinds for a go type (HorizontalPodAutoscaler has 2 kinds - extensions/v1beta1 and autoscaling/v1), we cant use scheme.ObjectKind().
scheme.ObjectKind() arbitrarily returns the first possible kind.
We should replace it by ObjectKinds() and then disambiguate appropriately.

@kubernetes/sig-api-machinery @liggitt @deads2k

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/22840 is an example way to fix this

**Comment by liggitt** [comment]
#22840 was a contained fix at the edge of one use. I wouldn't recommend that as a pattern. I'd like to revisit usage after 1.2 closes.

**Comment by nikhiljindal** [comment]
@liggitt @deads2k What do you guys think about using mapper.KindFor(resource) instead of scheme.ObjectKind(obj) to get the kind in kubectl commands.
https://github.com/kubernetes/kubernetes/issues/22484#issuecomment-195234347

**Comment by nikhiljindal** [comment]
Example PR: https://github.com/kubernetes/kubernetes/pull/22872

**Comment by deads2k** [comment]
> @liggitt @deads2k What do you guys think about using mapper.KindFor(resource) instead of scheme.ObjectKind(obj) to get the kind in kubectl commands.

For some commands, it seems like they could explicitly indicate what they're creating.  The `create` subcommands you called out only know how to make one thing, right?
