### ISSUE TITLE
generated doc scripts (e.g. for kubectl) should update the new docs repo

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#22863]
We have a number of scripts in https://github.com/kubernetes/kubernetes/tree/master/hack/after-build that generate docs (markdown, manpages etc) from source. Those should be updated to require a docs path so they can still be used to push updates to https://github.com/kubernetes/kubernetes.github.io.

cc @johndmulhausen

**Comment by bgrant0607** [comment]
cc @kubernetes/docs

**Comment by bgrant0607** [comment]
Redundant with the issue about eliminating generated docs
