### ISSUE TITLE
Add API endpoint to query cluster capabilities

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#22871]
I'm not sure if this exists at the moment (I browsed through the API and couldn't find anything like this).

I'd like to be able to query what Cloud Provider the cluster is running on as well as for other settings. Is this possible?

This might be a node specific thing, if the cluster spans multiple locations.

**Comment by paralin** [comment]
Another thing here would be a `capabilities` endpoint to check if the cluster can create volumes, create load balancers... 

The main reason for this is because in the Openshift-Under-Kubernetes deployment script I would like to automatically check if the cluster is able to create LoadBalancers and pick NodePorts instead if it can't.

**Comment by quinton-hoole** [comment]
Agreed, good feature idea.  A detailed design proposal would be welcomed.
Probably more an API consideration than control plane, so I've relabelled accordingly.
@bgrant0607 FYI.

**Comment by bgrant0607** [comment]
cc @kubernetes/kube-api
