### ISSUE TITLE
Help with defining the right ABAC authorization policies

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#22873]
I'm in the process of creating ABAC authorization policies for our Kubernetes cluster and ran into several issues:

1. Is there a cookie cutter example of what a "normal user" and an "admin user"'s policy should look like?

2. We expect our users to use `kubectl` to interact with our k8s cluster, is the following policy safe to use?

```
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"*",         "nonResourcePath": "*", "readonly": true}}
```

3. If I add a new user to the cluster with the corresponding changes to the ABAC authorization policy file, do I always need to restart API server? If so, is there a better way to handle this as we don't want to always having to restart things.

Thanks!

**Comment by huang195** [comment]
cc @erictune, @liggitt

**Comment by mkulke** [comment]
it depends on your definition of admin and user, when users are supposed to create all kinds of objects, you probably want to restrict them to a namespace.

http://kubernetes.io/docs/admin/authorization/ has pretty good examples.

According to those docs you still have to restart the apiserver when adding/removing policies. We hand out namespace'd group-tokens to development-teams.

**Comment by huang195** [comment]
@mkulke in my environment, i'd like a *user* to be able to do anything within a namespace, but not anything outside of his namespace. Is the following sufficient?

```
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "user1", "namespace": "user1-space"}}
```

An *admin* on the other hand can perform any operation in the cluster, so I'm using the following:

```
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "admin"}}
```

yet, this is insufficient due to `nonResourcePath` if admin were to access the cluster via `kubectl`, so I would also need to add

```
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "*", "readonly": true, "nonResourcePath": "*"}}
```

but does the above inadvertently give normal *user* any additional access to things that shouldn't be given? It feels like if one is not intimately familiar with all the RESTAPIs, you always get the feeling that you might have missed or overlooked something. 

It's like setting up firewall rules, it's tedious but at least it's quantifiable. Somehow I'm not getting the same feeling here after setting up the authorization rules. It would be nice to have an end-to-end guide on how to set up authorization **completely** in a small environment rather than just a few examples.

**Comment by mkulke** [comment]
The policies you posted should work as intended (they look exactly like ours), but I understand your concern regarding the nonResourcePath. The current implementation is actually discerning requests as *either* `nonResourcePath` *or* `resource` and choosing policies accordingly:

https://github.com/kubernetes/kubernetes/blob/master/pkg/auth/authorizer/abac/abac.go#L120

which relies on :

https://github.com/kubernetes/kubernetes/blob/7c801f217c09e83e8ed6d723ac5f1613f2e77d79/pkg/apiserver/handlers.go#L484

the docs do not specifically mention this behavior i think, and maybe a unit-test would be good (asserting that a `nonResourcePath` policy does not give matching users access to resources).

**Comment by huang195** [comment]
@mkulke thanks for those pointers. I will take a look and see it's actually implemented to give me more confidence that I'm creating an authorization policy without holes.

**Comment by huang195** [comment]
@mkulke where is a "group" getting defined in all this? If I'm using TLS certificate, I understand that the CommonName of the cert is used as the username, but where is the group concept comes in?

**Comment by liggitt** [comment]
Currently, only the tokenfile auth and OIDC auth providers populate group information for users. Service account auth includes group info as well

**Comment by huang195** [comment]
@liggitt Is there some way to fake having groups when using TLS? If not, is there a plan to add general support of a group concept? Thanks!

**Comment by huang195** [comment]
Closing this, but it is a pain to define ABAC policies on a granularity of a user. For fine-grained control, that just means a lot of repetitive rules for different users. This isn't good especially for ABAC as it impacts performance as it linearly searches each policy for matches.

**Comment by liggitt** [comment]
the ABAC authorizer is more useful as a bootstrapping policy, and a minimal implementation (live updating and reusable definitions are just two things that would be needed for it to be broadly useful)

fwiw, we're working on getting reusable role definitions upstreamed from OpenShift into Kube (hopefully in the 1.3 timeframe), so you could define a role once, then assign it to users globally or within the context of a namespace

**Comment by deitch** [comment]
I also found myself struggling with this (and this issue helped, so thanks for opening it @huang195 ).

When getting started, a typical policy might be:

* role `app` can do anything in app namespaces (starting just with `default`)
* role `admin` can do anything anywhere
* plus the rest of the usual accounts

Since roles aren't really supported yet, I am using the _users_ `app` and `admin`, plus the ability to have multiple CN in the certificate. I just add the user as the primary CN plus allowed roles.

This isn't ideal - I would prefer having proper RBAC - but a step in the right direction.
