### ISSUE TITLE
Pod start prerequisites

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#22887]
Are there any plans to implement a setup where a pod could define some prerequisites (e.g. label selectors) for starting?

The problem this would solve is the problem of trying to deploy something all in one go. Usually you would `kubectl create -f configs/` to create all the configs for a system. But in many cases certain components have (sub-optimal) requirements to start properly, particularly the first time. For example, an etcd cluster needs (or really _should_ have) the etcd discovery pod to be running before the members start. A distributed job system might have a prerequisite of a running database pod before starting.

**Comment by ncdc** [comment]
See also #4245 #1768

**Comment by bgrant0607** [comment]
See also #16448
