### ISSUE TITLE
Docker failed to start in master node

### ISSUE THREAD

**Issue by dachulin** [kubernetes/kubernetes#22886]
Deployed a vsphere cluster according to the latest instruction. Docker was not able to start in master, but started ok in minion.

In master:
root@da-master:/var/log# docker ps
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.22/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer

looking at the /var/log/syslog:
syslog:Mar 11 11:14:23 kube docker[14759]: flag provided but not defined: -d
syslog:Mar 11 11:14:23 kube docker[14759]: See '/usr/bin/docker --help'.
syslog:Mar 11 11:14:23 kube systemd[1]: docker.service: main process exited, code=exited, status=125/n/a
syslog:Mar 11 11:14:23 kube systemd[1]: Unit docker.service entered failed state.
syslog:Mar 11 11:14:26 kube kubelet[12648]: E0311 11:14:26.007430   12648 generic.go:164] GenericPLEG: Unable to retrieve pods: Get http://unix.sock/containers/json?all=1: read unix /var/run/docker.sock: connection reset by peer
syslog:Mar 11 11:14:26 kube docker[14765]: flag provided but not defined: -d
syslog:Mar 11 11:14:26 kube docker[14765]: See '/usr/bin/docker --help'.
syslog:Mar 11 11:14:26 kube systemd[1]: docker.service: main process exited, code=exited, status=125/n/a
syslog:Mar 11 11:14:26 kube systemd[1]: Unit docker.service entered failed state.
syslog:Mar 11 11:14:28 kube kubelet[12648]: E0311 11:14:28.257381   12648 generic.go:164] GenericPLEG: Unable to retrieve pods: Get http://unix.sock/containers/json?all=1: read unix /var/run/docker.sock: connection reset by peer
syslog:Mar 11 11:14:28 kube docker[14772]: flag provided but not defined: -d
syslog:Mar 11 11:14:28 kube docker[14772]: See '/usr/bin/docker --help'.
syslog:Mar 11 11:14:28 kube systemd[1]: docker.service: main process exited, code=exited, status=125/n/a
syslog:Mar 11 11:14:28 kube systemd[1]: Unit docker.service entered failed state.
syslog:Mar 11 11:14:30 kube kubelet[12648]: E0311 11:14:30.508307   12648 generic.go:164] GenericPLEG: Unable to retrieve pods: Get http://unix.sock/containers/json?all=1: read unix /var/run/docker.sock: connection reset by peer
syslog:Mar 11 11:14:30 kube kubelet[12648]: E0311 11:14:30.508439   12648 kubelet.go:2615] Container runtime sanity check failed: docker: failed to get docker version: Get http://unix.sock/version: read unix /var/run/docker.sock: connection reset by peer

**Comment by yujuhong** [comment]
I assume you have docker 1.10 on your master node, because of the v1.22 API and the fact that docker 1.10 stopped supporting the "-d" flag. You'll need to change the docker options to use "daemon" instead of "-d". You may also want to check why the docker version is different only on your master node.

**Comment by dachulin** [comment]
Yes seems like I have 1.10.3. Change to daemon brings it up.
