### ISSUE TITLE
Set MAC addresses of pods deterministically, allow prefixing

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#2289]
In a large organization, MAC addresses are used for internal auditing.  It would be valuable to make the pod's MAC address deterministic based on the pod ID, and to allow a common prefix for all pods created by one cluster.  This would probably be part of Kubelet or Docker config, and require changes for docker, but the use case starts at the cluster level.

E.g.:

    Pod ID: "podA" -> MAC: "<mac_prefix>+<hash_of_pod_id>" ->
    $ docker run --name=pod-net-container --mac-address=<addr> kubernetes/pause

Will spawn a Docker issue.

**Comment by stainboy** [comment]
As for now, docker run supports both `--mac-address={some specific mac address}` and `--hostname={some desired hostname}` while **kubernetes** doesn't.

In our business, the target product **generates** the hardware key based on `hostname` and `mac-address`, which is used to apply product license. In order to make the license `generic`, I have to specify the hostname and mac-address statically at run-time.

Since docker has already supported the feature, would you consider to support it eventually? Thanks

**Comment by thockin** [comment]
I think we've already said yes to hostname, though we need to iron out the
final design details.  Mac address is more fun - in the face of network
plugins, what does that even mean?  We might be able to support if for our
default plugin, but no guarantees on other plugins.

Anyway, consider this "in the queue".  It's just a matter of getting to all
the great ideas in that queue. :)

**Comment by thockin** [comment]
This is covered by net plugins.  I don't think it will be part of core feature set.

**Comment by pdbogen** [comment]
Is there any guidance about *how* to accomplish this with network plugins?

**Comment by bergtwvd** [comment]
I currently have a few docker containers that require a certain MAC address to run. This works fine under docker using the mac-address option on docker run. I am currently looking into using Kubernetes as container environment. I came across this post on MAC address. What is the current status? Does Kubernetes support setting the MAC address for a container?

**Comment by thockin** [comment]
It is not something we support directly.  It's possible that some network
drivers support this via annotations, but I have not heard about it.

**Comment by bergtwvd** [comment]
Referring to the post of dec 1, could a pod with a static mac address be considered as a "singleton" that cannot be replicated more than once? If the concept of mac address is an issue in Kubernetes, maybe this is a way to look at it. No mac is just a no-goer for me.

**Comment by thockin** [comment]
It's hard to say what it would be considered, since there is just no way of
representing such a thing, right now.

**Comment by zakkg3** [comment]
Someone did add the NET_ADMIN capability and changing the MAC to an environment variable with "ip link" in the entrypoint.sh ..
https://www.reddit.com/r/kubernetes/comments/8a36jw/set_mac_address_possible_with_k8s/

**Comment by ideceddy** [comment]
The feature of defining a MAC Address at manifest apply time is something that I would definitely need to be able to use docker in our deployment. Currently, we have a server that is tied to the hostname and MAC address for licensing. Right now we create a docker image and use the --mac-address --hostname flags to get by. Being able to do this in a stateful set or deployment would be very useful for our team.

**Comment by SebastianHurubaru** [comment]
Is this feature being addressed? Having the same issue with creating a serverless architecture including license servers that are hostname & mac address dependent! Thanks!

**Comment by thockin** [comment]
This one s something a CNI implementation might choose to offer, but not
something we can demand of them all.

That said, I had a discussion recently about a possible future API that
would maybe make this easier to represent and govern.  For the near term,
it's net plugins or bust.
