### ISSUE TITLE
Build fails from 404 on cloud-sdk-testing/

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#22895]
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-ingress/2548/console
https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/logs/kubernetes-e2e-gke-ingress/2548/build-log.txt
```
18:34:37 + [[ -x ./cluster/gce/list-resources.sh ]]
18:34:37 + gcp_list_resources=true
18:34:37 + [[ ! -z gs://cloud-sdk-testing/ci/staging ]]
18:34:37 + gsutil -mq cp -r gs://cloud-sdk-testing/ci/staging /var/lib/jenkins/jobs/kubernetes-e2e-gke-ingress/workspace
18:34:38 NotFoundException: 404 gs://cloud-sdk-testing/ci/staging/components-2-TESTING.json does not exist.
18:34:41 CommandException: 1 file/object could not be transferred.
18:34:41 + rc=1
18:34:41 + [[ 1 -ne 0 ]]
18:34:41 + [[ -x kubernetes/cluster/log-dump.sh ]]
18:34:41 + [[ -d _artifacts ]]
18:34:41 + echo 'Dumping logs for any remaining nodes'
18:34:41 Dumping logs for any remaining nodes
18:34:41 + ./kubernetes/cluster/log-dump.sh _artifacts
```
Just another case that needs retries?

**Comment by spxtr** [comment]
I don't think we should retry on 404.

**Comment by bprashanth** [comment]
Unless it was a race where we were checking before the thing that uploads it?

**Comment by spxtr** [comment]
It looks like `gsutil cp -r` might have a race condition.

**Comment by bprashanth** [comment]
I think gsutil rsync (https://cloud.google.com/storage/docs/gsutil/commands/rsync) is better than cp -r for performance (especially if you have subdirs) and *may* not be subject to the same race

**Comment by yujuhong** [comment]
I don't think we own the "cloud-sdk-testing" bucket. How can we be sure that the cloud-sdk ci wasn't modifying the directory at the same time?

**Comment by spxtr** [comment]
I think that's the race condition. `gsutil cp` doesn't handle syncing up across multiple files, which it shouldn't. Rather than retry, maybe switching to rsync will fix it?
