### ISSUE TITLE
AWS: Check that dynamic volumes are deleted

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22907]
It was reported that dynamic volumes were not deleted on AWS.  Maybe we need to enable the PersistentVolumeRecycler somehow?

**Comment by paralin** [comment]
I'm going to double check this is an issue later today.

**Comment by paralin** [comment]
This is definitely an issue. Two pvs are created via pvcs with the "magic annotation" for automatic PV allocation. I then delete the PVCs, wait a bit, and delete the PVs themselves. The volumes remain.

**Comment by justinsb** [comment]
Closing in favor of #23032 , which is not AWS specific.
