### ISSUE TITLE
Controller selector changes can create orphans

### ISSUE THREAD

**Issue by njoneja** [kubernetes/kubernetes#22909]
The kubectl update mechanism (e.g. for replication controllers) can create orphans. A more consistent approach to this verb (consistent wrt delete for example) would be:

(Proposal is a summary of conversation with Brendan Burns)
update that would create orphans fails with a warning
update -f updates anyway and creates orphans (e.g. if someone wants to do an in-place update of the RC)
update --cascade=true ensures clean-up of pods that would be orphaned

**Comment by AdoHe** [comment]
would take a look.

**Comment by AdoHe** [comment]
@brendandburns could you confirm this?

**Comment by bgrant0607** [comment]
My guess is that this is about selector changes. We probably should have just prevented that in API validation.

"kubectl replace --force" already cleans up orphans.

Don't know how much of a problem this is.

We're also moving towards default selector generation.
https://github.com/kubernetes/kubernetes/blob/master/docs/design/selector-generation.md

**Comment by kargakis** [comment]
Documented in https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates

**Comment by bgrant0607** [comment]
cc @kow3ns

**Comment by kow3ns** [comment]
Selectors are immutable in apps/v1beta2 (releasing kubernetes 1.8)

**Comment by bgrant0607** [comment]
We made selectors immutable for this reason.
