### ISSUE TITLE
apiserver POST now requires appropriate JSON or YAML Content-Type

### ISSUE THREAD

**Issue by benmcrae** [kubernetes/kubernetes#22904]
Just upgraded to hyperkube 1.2.0-beta.0. On creating the 'kube-system' namespace against the apiserver...

```curl -XPOST -d '{"apiVersion":"v1","kind":"Namespace","metadata":{"name":"kube-system"}}' "http://127.0.0.1:8080/api/v1/namespaces"```

I get the following error back.
```                      
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the body of the request was in an unknown format - accepted media types include: application/json, application/yaml",
  "reason": "UnsupportedMediaType",
  "code": 415
}
```

Should this default to ```application/json``` to stop a breaking change?

The following works successfully

```curl -H "Content-Type: application/json" -XPOST -d '{"apiVersion":"v1","kind":"Namespace","metadata":{"name":"kube-system"}}' "http://127.0.0.1:8080/api/
v1/namespaces"```

The Content-Type was not required in 1.1.

**Comment by ncdc** [comment]
cc @bgrant0607 @smarterclayton @kubernetes/rh-cluster-infra @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
Curl is sending an incorrect content type by default (use -H "Content-Type: application/json")

If you don't set a content type by default we use the default, but sending an incorrect content type is now rejected.  No clients I am aware of send incorrect content types.

**Comment by smarterclayton** [comment]
This is an intentional change in 1.2 to allow us to properly support future alternate serializations.  Accepting the incorrect content type was a bug.  If you can find a client in wide use that is dependent on that behavior please let us know.

**Comment by bgrant0607** [comment]
@benmcrae Thanks for trying the beta release!

It would be useful to document this. Sadly, we don't even have a client-focused API doc. #19680

Since it is a change that could break some clients (including curl), we should document this in release notes. I'll add it now.
https://docs.google.com/document/d/1qVWj3mmrYfYcS68t_rPvuym8xkj4O5PkL5YcoEorYMM/edit?ts=56e36ad0#heading=h.1zlusrq4rqmk

cc @lavalamp

**Comment by bgrant0607** [comment]
@smarterclayton Could you please make an announcement on kubernetes-dev@, to give client developers a heads-up?

**Comment by smarterclayton** [comment]
Done.  In our testing so far curl is the only client we've had reports
of being affected.

**Comment by lavalamp** [comment]
sounds like this is WAI
