### ISSUE TITLE
Use pod metdata to generate mount paths in Pod specs

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#22903]
We would like to be able to mount host paths inside pods based on pod metadata. Is this possible today? If not, can we make a feature request for this?

**Comment by thockin** [comment]
Can you be a bit more specific about what you are tying to do?

**Comment by codefx9** [comment]
I have a use-case where a proccess does not log to stdout. I would like to use the existing host fluentd to collect logs from this process, instead of running a side-car fluentd. Fluentd seems to be pretty memory hungry. Since, I am using RC with replica > 1, I can't just mount a host path inside Pod's /var/log folder. I can use downward api to achieve this today. But a more clean approach will be if I could, say, mount host path `/var/log/$NS/$POD_NAME` into `/var/log` inside a pod. Then use fluentd's regex parsing tricks to send Kube metadata with the process logs to ElasticSearch.

**Comment by codefx9** [comment]
Closing this, since we don't need this feature any more.

**Comment by thockin** [comment]
The best answer I can give around this, for now, is to mount, for example,
host's /var/log/myapp into your container, then use Downward API to get
your pod name or UID into an env var and pass something like
`--logdir=/var/log/myapp/$(MYNAME)/` to your app.

**Comment by anandsinghkunwar** [comment]
@thockin Anyway to do this now?
