### ISSUE TITLE
verify-symbols.sh complained error when importing etcd/clientv3

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#22908]
ref: https://github.com/kubernetes/kubernetes/pull/22604#issuecomment-195658011

When I wrote [v3Helper](https://github.com/kubernetes/kubernetes/commit/21f089f27f94440ce6713630168f368c411cfaa1), which is a completely parallel struct and not used by anything, hack/verify-symbols.sh will complain:
```
output binaries contain bad symbols "testing[.]"
!!! Error in ./hack/../hack/verify-symbols.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-symbols.sh"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-symbols.sh:28 main(...)
Exiting with status 1
FAILED   ./hack/../hack/verify-symbols.sh
```

This happened when importing "github.com/coreos/etcd/clientv3" even in a completely isolated file.
What's causing the problem? How can I fix that?

/cc @timothysc @wojtek-t @xiang90

**Comment by hongchaodeng** [comment]
Here is some analysis of hyperbuke binary
```
➜  kubernetes git:(6388c07) ✗ nm _output/local/bin/linux/amd64/hyperkube | grep testing
0000000003d383f6 b runtime.testingAssertE2I2GC
0000000003d383f7 b runtime.testingAssertE2T2GC
0000000003d0a8e0 b testing.benchmarkMemory
0000000003d0a8d8 b testing.benchTime
0000000003d0a8e8 b testing.blockProfile
0000000003d0a8f0 b testing.blockProfileRate
0000000003d0a8f8 b testing.chatty
0000000003d0a900 b testing.count
0000000003d0a908 b testing.coverProfile
0000000003d0a910 b testing.cpuListStr
0000000003d0a918 b testing.cpuProfile
0000000001ce8500 t testing.init
0000000003d38404 b testing.initdone.
0000000003d0a920 b testing.match
0000000003d0a928 b testing.matchBenchmarks
0000000003d0a930 b testing.memProfile
0000000003d0a938 b testing.memProfileRate
0000000003d0a940 b testing.outputDir
0000000003d0a948 b testing.parallel
0000000003d0a950 b testing.short
0000000003d0a958 b testing.timeout
0000000003d0a960 b testing.traceFile
```

**Comment by wojtek-t** [comment]
@timothysc - I think you wrote this tool, right? Can you please take a look?

**Comment by timothysc** [comment]
@hongchaodeng you're transitively pulling in testing dependencies... The check is to ensure we don't do that.  Someone in the dependency chain for etcd3 has linked against the testing libraries.

**Comment by hongchaodeng** [comment]
@xiang90 

I have found the sequence:
```Go
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/etcdserver/api/v3rpc
github.com/coreos/etcd/etcdserver
github.com/coreos/etcd/pkg/testutil
testing
```

In this way, the client imports "testing" packages.

**Comment by timothysc** [comment]
@lavalamp ^ There you go ;-)

**Comment by xiang90** [comment]
@hongchaodeng Can you try to fix this in etcd then?

**Comment by lavalamp** [comment]
Yup, WAI :)

(sidenote YAY we caught this in advance for once!)
