### ISSUE TITLE
Job created with no selector and  extra template labels fails validation

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#22920]
When creating a job like this:
```go
job := &extensions.Job{}
job.Name = "testjob"
job.Spec.Template.Labels = map[string]string{"foo": "bar"}
job.Spec.Template.Spec = ...
job.Spec.Template.Spec.RestartPolicy = kapi.RestartPolicyNever
_, err = client.Extensions().Jobs(testutil.Namespace()).Create(job)
```
the API returns the following error:
> Job.extensions "testjob" is invalid: spec.selector: Invalid value: {"matchLabels":{"controller-uid":"db5d1cc3-e8f0-11e5-914d-acbc32c1ca87","foo":"bar"}}: `selector` not auto-generated

This is the object passed to `ValidateGeneratedSelector`, which seems like it should validate:
```
(api.ObjectMeta) {
 Name: (string) (len=7) "testjob",
 GenerateName: (string) "",
 Namespace: (string) (len=11) "integration",
 SelfLink: (string) "",
 UID: (types.UID) (len=36) "db5d1cc3-e8f0-11e5-914d-acbc32c1ca87",
 ResourceVersion: (string) "",
 Generation: (int64) 0,
 CreationTimestamp: (unversioned.Time) 2016-03-13 03:54:47.477573961 -0400 EDT,
 DeletionTimestamp: (*unversioned.Time)(<nil>),
 DeletionGracePeriodSeconds: (*int64)(<nil>),
 Labels: (map[string]string) (len=1) {
  (string) (len=3) "foo": (string) (len=3) "bar"
 },
 Annotations: (map[string]string) <nil>
}
(extensions.JobSpec) {
 Parallelism: (*int)(0xc20b1caaa0)(1),
 Completions: (*int)(0xc20b1caaa8)(1),
 ActiveDeadlineSeconds: (*int64)(<nil>),
 Selector: (*unversioned.LabelSelector)(0xc209403220)({
  MatchLabels: (map[string]string) (len=2) {
   (string) (len=3) "foo": (string) (len=3) "bar",
   (string) (len=14) "controller-uid": (string) (len=36) "db5d1cc3-e8f0-11e5-914d-acbc32c1ca87"
  },
  MatchExpressions: ([]unversioned.LabelSelectorRequirement) <nil>
 }),
 ManualSelector: (*bool)(<nil>),
 Template: (api.PodTemplateSpec) {
  ObjectMeta: (api.ObjectMeta) {
   Name: (string) "",
   GenerateName: (string) "",
   Namespace: (string) "",
   SelfLink: (string) "",
   UID: (types.UID) "",
   ResourceVersion: (string) "",
   Generation: (int64) 0,
   CreationTimestamp: (unversioned.Time) 0001-01-01 00:00:00 +0000 UTC,
   DeletionTimestamp: (*unversioned.Time)(<nil>),
   DeletionGracePeriodSeconds: (*int64)(<nil>),
   Labels: (map[string]string) (len=3) {
    (string) (len=3) "foo": (string) (len=3) "bar",
    (string) (len=8) "job-name": (string) (len=7) "testjob",
    (string) (len=14) "controller-uid": (string) (len=36) "db5d1cc3-e8f0-11e5-914d-acbc32c1ca87"
   },
   Annotations: (map[string]string) <nil>
  },
  Spec: (api.PodSpec) {
   Volumes: ([]api.Volume) <nil>,
   Containers: ([]api.Container) (len=1 cap=1) {
    (api.Container) {
     Name: (string) (len=9) "container",
     Image: (string) (len=10) "test/image",
     Command: ([]string) <nil>,
     Args: ([]string) <nil>,
     WorkingDir: (string) "",
     Ports: ([]api.ContainerPort) <nil>,
     Env: ([]api.EnvVar) <nil>,
     Resources: (api.ResourceRequirements) {
      Limits: (api.ResourceList) <nil>,
      Requests: (api.ResourceList) <nil>
     },
     VolumeMounts: ([]api.VolumeMount) <nil>,
     LivenessProbe: (*api.Probe)(<nil>),
     ReadinessProbe: (*api.Probe)(<nil>),
     Lifecycle: (*api.Lifecycle)(<nil>),
     TerminationMessagePath: (string) (len=20) "/dev/termination-log",
     ImagePullPolicy: (api.PullPolicy) (len=6) "Always",
     SecurityContext: (*api.SecurityContext)(<nil>),
     Stdin: (bool) false,
     StdinOnce: (bool) false,
     TTY: (bool) false
    }
   },
   RestartPolicy: (api.RestartPolicy) (len=5) "Never",
   TerminationGracePeriodSeconds: (*int64)(0xc20b1caab8)(30),
   ActiveDeadlineSeconds: (*int64)(<nil>),
   DNSPolicy: (api.DNSPolicy) (len=12) "ClusterFirst",
   NodeSelector: (map[string]string) <nil>,
   ServiceAccountName: (string) "",
   NodeName: (string) (len=20) "nodename.example.com",
   SecurityContext: (*api.PodSecurityContext)(0xc20943c5c0)({
    HostNetwork: (bool) false,
    HostPID: (bool) false,
    HostIPC: (bool) false,
    SELinuxOptions: (*api.SELinuxOptions)(<nil>),
    RunAsUser: (*int64)(<nil>),
    RunAsNonRoot: (*bool)(<nil>),
    SupplementalGroups: ([]int64) <nil>,
    FSGroup: (*int64)(<nil>)
   }),
   ImagePullSecrets: ([]api.LocalObjectReference) <nil>
  }
 }
}
```

**Comment by liggitt** [comment]
it looks like the issue is that the expected labels *only* include the generated labels:
```go
	expectedLabels := make(map[string]string)
	expectedLabels["controller-uid"] = string(obj.UID)
	expectedLabels["job-name"] = string(obj.Name)
```
whereas the selector includes some of the actual template's labels

including the actual labels from the template in addition to the generated ones correctly indicates if the selector will match

**Comment by bgrant0607** [comment]
You created a v1beta1 Job, which defaults manualSelector to true, but provided no selector. I believe Job was changed to not set the selector by default from its labels in that scenario.

**Comment by bgrant0607** [comment]
Actually, that can't be right, because ValidateGeneratedSelector would have bailed out earlier.

**Comment by bgrant0607** [comment]
I'll let @erictune figure it out. :-)  (I was just triaging cherrypick-candidates)

**Comment by liggitt** [comment]
still not sure what the priority on this should be... would like @erictune to weigh in

**Comment by liggitt** [comment]
marking priority to match associated PR until we're sure this isn't blocking

**Comment by soltysh** [comment]
@bgrant0607 actually @liggitt created Job using the internal representation (`extensions` vs `v1beta1`), in which case the `manualSelector` is not set which means the selector should be generated (same as for `batch/v1`). For `v1beta1` there's no `manualSelector` but `autoSelector`, which has the opposite meaning, for backwards compatibility. That's why I'm giving his PR LGTM. @erictune agreed?

**Comment by erictune** [comment]
As mentioned [at the end of this commit description](https://github.com/kubernetes/kubernetes/pull/21776/commits/875755f992ada8639229b010a0a22d1f943e499b), but obviously not called out well enough:
`Users who are creating extensions.Job go objects and then posting them using the go client
will see a change in the default behavior.  They need to either stop providing a selector (relying on
selector generation) or else specify "spec.manualSelector" until they are ready to do the former.`.

So, Jordan should have set manualSelector=true, and then I think we would not have seen this behavior.  So I think this is working as intended.

**Comment by erictune** [comment]
I'm reclassifying this as P2.

**Comment by liggitt** [comment]
I actually wanted an automatic selector, so I stopped providing a selector... was that not right?

**Comment by bgrant0607** [comment]
@liggitt automaticSelector isn't true by default for v1beta1

**Comment by liggitt** [comment]
ok, got a recreator with a raw API request:

```
$ more job.json
{
    "kind":"Job",
    "apiVersion":"extensions/v1beta1",
    "metadata":{"name":"myjob"},
    "spec":{
        "template": {
            "metadata": {"labels": {"foo":"bar"}},
            "spec":{"containers": [{"name":"c","image":"i"}],"restartPolicy":"Never"}
        },
        "autoSelector":true
    }
}

$ curl http://localhost:8080/apis/extensions/v1beta1/namespaces/test/jobs -X POST -d @job.json -H "Content-Type: application/json"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Job.extensions \"myjob\" is invalid: spec.selector: Invalid value: {\"matchLabels\":{\"controller-uid\":\"e648a79e-eb29-11e5-ac94-acbc32c1ca87\",\"foo\":\"bar\"}}: `selector` not auto-generated",
  "reason": "Invalid",
  "details": {
    "name": "myjob",
    "group": "extensions",
    "kind": "Job",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "Invalid value: {\"matchLabels\":{\"controller-uid\":\"e648a79e-eb29-11e5-ac94-acbc32c1ca87\",\"foo\":\"bar\"}}: `selector` not auto-generated",
        "field": "spec.selector"
      }
    ]
  },
  "code": 422
}
```

**Comment by bgrant0607** [comment]
Hmm. Ok. Looks the e2e test is not testing autoSelector at all?

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/job.go#L209

**Comment by bgrant0607** [comment]
Sequence AIUI:
1. Defaulting in v1beta1: copies labels from template to selector, as original behavior, *ignoring autoSelector*
2. Conversion to internal rep: sets ManualSelector
3. Job strategy Validate: calls generateSelector, which sets controller-uid and job-name labels, and adds controller-uid to the selector
4. Validation: checks whether selector matches labels in template (2 times, if autoGenerated?)

So, yeah, this is broken, due to #1.

But I believe the fix @erictune intended was to not copy the labels to the selector if manualSelector was false.

Given that manualSelector=true is tested in e2e, that seems to work.

batch/v1 doesn't have this problem, since the selector defaulting code is gone.
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/v1/defaults.go#L23

Bumped to P0.

Sadly, I don't think this is the right fix. We should check autoSelector in the defaulting code and not copy the labels into the selector if that's true.

**Comment by erictune** [comment]
@bgrant0607 there is a separate e2e test called https://github.com/kubernetes/kubernetes/blob/master/test/e2e/batch_v1_jobs.go

**Comment by erictune** [comment]
Well, we have e2e test of extensions/v1beta1 without auto, and batch/v1 with auto, but not the other two ways, one of which is the one Jordan is pointing out.

**Comment by erictune** [comment]
Agree with Brian's description of the fix.  I should have caught this case with more testing.
