### ISSUE TITLE
Document how to change kubernetes api port

### ISSUE THREAD

**Issue by randykunkee** [kubernetes/kubernetes#22927]
I wanted to kick the tires of Kubernetes by following the instructions at ([Running Kubernetes Locally via Docker](http://kubernetes.io/docs/getting-started-guides/docker/)), but the system I was on already was using port 8080. After poking around I recalled this bit of knowledge and therefore tried to change the --api-servers=http://localhost:8080  flag to use another port, 9080, but internally the kubernetes pod still wants to use port 8080.

Of all the ways to try Kubernetes, this is certainly the easiest way yet I've seen to stand it up on a machine. Just install docker-engine and then you have Kubernetes - pretty sweet. It would nice if that page would mention how to alter the port. Is this just a matter of documentation, or should the change to --api-servers have worked?

I was trying this with v1.2.0-beta.1, as in:
K8S_VERSION="1.2.0-beta.1"
docker run \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    -d \
    gcr.io/google_containers/hyperkube-amd64:v${K8S_VERSION} \
    /hyperkube kubelet \
        --containerized \
        --hostname-override="127.0.0.1" \
        --address="0.0.0.0" \
        --api-servers=http://localhost:9080 \
        --config=/etc/kubernetes/manifests \
        --allow-privileged=true --v=2

But even so, docker logs of the proxy servers showed failed posts to port 8080.

**Comment by bgrant0607** [comment]
cc @dlorenc @vishh
