### ISSUE TITLE
Write a guide for new contributors

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#22923]
docs/devel has a lot of stuff in it at this point.

**Comment by mikebrow** [comment]
I wrote one. I didn't make it very generic choosing to focus on using ubuntu in a vm, it would need tweaks to expand to RHL etc. 

Feel free to take from it what you will. I'd be happy to help out...  

https://developer.ibm.com/opentech/2016/06/15/kubernetes-developer-guide-part-1/

**Comment by nikhita** [comment]
Ref https://github.com/kubernetes/community/issues/892.

**Comment by bgrant0607** [comment]
I'm going to close this issue in favor of the one in community.
