### ISSUE TITLE
Pods not starting on Kubernetes 1.2-beta.1 with CNI

### ISSUE THREAD

**Issue by tobad357** [kubernetes/kubernetes#22932]
We have been running a Kube cluster on 1.2-alpha.7 for quite a while with no problems.
Now trying to upgrade to Kube 1.2-beta.1 the pods end up in a restart loop and never come online.
The upgrade is done via a complete reinstall of OS and Kubernetes and the issue has been recreated several times by upgrading and downgrading between alpha.7 and beta-1

OS: Centos 7.2
Docker: 1.9.1
Kube version: 1.2-beta.1
CNI Provider: calico cni 1.1.0 / calicoctl: 0.17.0

kubectl --namespace=kube-system get pod -o wide

```
NAME                     READY     STATUS    RESTARTS   AGE       NODE
kube-dns-v10-0nh1i       3/4       Running   68         20m       srv07
kube-dns-v10-vfj6d       3/4       Running   60         20m       srv05
kube-registry-v0-m0or6   1/1       Running   44         20m       srv05
kube-ui-v5-gxs27         1/1       Running   197        20m       srv04
```

kubectl get events for one pod
```
 FirstSeen	LastSeen	Count	From			SubobjectPath			Type		Reason			Message
  ─────────	────────	─────	────			─────────────			────────	──────			───────
  11m		10m		5	{default-scheduler }					Warning		FailedScheduling	no nodes available to schedule pods
  10m		10m		1	{default-scheduler }					Normal		Scheduled		Successfully assigned kube-dns-v10-0nh1i to srv07
  10m		10m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Pulling			pulling image "gcr.io/google_containers/etcd:2.0.9"
  10m		10m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Pulled			Successfully pulled image "gcr.io/google_containers/etcd:2.0.9"
  10m		10m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Created			Created container with docker id 3efd24477ee2
  10m		10m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Started			Started container with docker id 3efd24477ee2
  10m		10m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Pulling			pulling image "gcr.io/google_containers/kube2sky:1.12"
  10m		10m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Pulled			Successfully pulled image "gcr.io/google_containers/kube2sky:1.12"
  10m		10m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Created			Created container with docker id f6ce0663c34b
  10m		10m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Started			Started container with docker id f6ce0663c34b
  10m		10m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Pulling			pulling image "gcr.io/google_containers/skydns:2015-10-13-8c72f8c"
  9m		9m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Pulled			Successfully pulled image "gcr.io/google_containers/skydns:2015-10-13-8c72f8c"
  9m		9m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Created			Created container with docker id bf3ecc042ffd
  9m		9m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Started			Started container with docker id bf3ecc042ffd
  9m		9m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Pulling			pulling image "gcr.io/google_containers/exechealthz:1.0"
  9m		9m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Pulled			Successfully pulled image "gcr.io/google_containers/exechealthz:1.0"
  9m		9m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Created			Created container with docker id 28a0783cf48f
  8m		8m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Started			Started container with docker id 28a0783cf48f
  8m		8m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Killing			Killing container with docker id bf3ecc042ffd: Need to kill pod.
  8m		8m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Killing			Killing container with docker id f6ce0663c34b: Need to kill pod.
  8m		8m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Killing			Killing container with docker id 28a0783cf48f: Need to kill pod.
  8m		8m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Killing			Killing container with docker id 3efd24477ee2: Need to kill pod.
  8m		8m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Created			Created container with docker id f37dd5c64348
  8m		8m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Started			Started container with docker id f37dd5c64348
  8m		8m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Created			Created container with docker id bf2c1a408754
  8m		8m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Started			Started container with docker id bf2c1a408754
  8m		8m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Created			Created container with docker id 0668fa66b8f7
  8m		8m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Started			Started container with docker id 0668fa66b8f7
  8m		8m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Created			Created container with docker id 739e3f9c828d
  7m		7m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Started			Started container with docker id 739e3f9c828d
  7m		7m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Killing			Killing container with docker id f37dd5c64348: Need to kill pod.
  7m		7m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Killing			Killing container with docker id 739e3f9c828d: Need to kill pod.
  7m		7m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Killing			Killing container with docker id bf2c1a408754: Need to kill pod.
  7m		7m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Killing			Killing container with docker id 0668fa66b8f7: Need to kill pod.
  7m		7m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Created			Created container with docker id b208af539d35
  7m		7m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Started			Started container with docker id b208af539d35
  6m		6m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Killing			Killing container with docker id b208af539d35: Need to kill pod.
```

journalctl -xn 200 -u kubelet  (kubelet running with -v=5)

I can't see anything weird in the logs for the API Server, Scheduler or Controller Manager

**Comment by zhouhaibing089** [comment]
`healthz` is a process which checks the name `kubernetes.default` to see whether it is resolvable, if it is not, it will kill the container `kube2sky` and `skydns`, seems so, maybe you could get some luck by checking the log of `healthz`

**Comment by tobad357** [comment]
The problem is that it isn't only skydns and kube2sky dying.
The registry (which I haven't added health checks to) and kube-ui dies as well very quickly

**Comment by dchen1107** [comment]
@tobad357 From the log you attached, I saw the error message from Kubelet:

Mar 11 06:47:53 srv04 kubelet[21599]: E0311 06:47:53.706664   21599 manager.go:309] NetworkPlugin cni failed on the status hook for pod 'kube-ui-v5-whtv9' - invalid CIDR address: Device "eth0" does not

Looks like there is a configuration issue of cni on your node, which causes PodInfra container failure. 

cc/ @kubernetes/goog-cluster

**Comment by bprashanth** [comment]
> CNI Provider: calico cni 1.1.0 / calicoctl: 0.17.0

Hmm, kubernetes will pass eth0 in as CNI_IFNAME and expect the plugin to create such an interface.
The error message pointed out by Dawn:
```
Mar 11 06:47:53 srv04 kubelet[21599]: E0311 06:47:53.706664 21599 manager.go:309] NetworkPlugin cni failed on the status hook for pod 'kube-ui-v5-whtv9' - invalid CIDR address: Device "eth0" does not
```
 makes me think this isn't happening for calico? (you're not running your DNS pod with host networking for some reason, right?). 
@caseydavenport

**Comment by caseydavenport** [comment]
Looks like it might be an issue with the Calico install - I'm out of the office this week, but @tomdee should be able to help!

**Comment by tomdee** [comment]
I'm looking into this now. A `cni.log` from `/var/log/calico/cni` would be really useful

**Comment by tobad357** [comment]
@tomdee here you go
[cni.log.txt](https://github.com/kubernetes/kubernetes/files/173111/cni.log.txt)

I've also included the config I'm using 


```
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_authority": "172.16.1.1:2379",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    }
}
```

**Comment by tobad357** [comment]
Reupload of log with only relevant parts
[partial_log.txt](https://github.com/kubernetes/kubernetes/files/173123/partial_log.txt)

**Comment by tomdee** [comment]
@tobad357 Thanks, I'm taking a look now.

**Comment by tobad357** [comment]
@tomdee for your information I ran same version of calico under 1.2-alpha.7 and don't have issues however I do see similar things in the logs.. 
I can also see that an IP has been assigned to the pod if I do kubectl desribe pod on beta.1

**Comment by caseydavenport** [comment]
I took a look at the logs (couldn't resist) and it looks like the Calico CNI plugin is doing what I'd expect.

From the logs:
```
2016-03-11 07:14:24,110 5325 [kube-system/kube-ui-v5-whtv9] INFO Provisioned eth0 in netns /proc/5305/ns/net`
```

It reports that it creates `eth0` in the pod namespace right before kubelet reports that `eth0` doesn't exist.  I'd be interested to know which one is telling the truth...

The Calico CNI plugin would notice if the pod was running with host networking, and it wouldn't try to configure networking, so I don't think that is the issue here.

**Comment by tobad357** [comment]
@caseydavenport Host networking isn't used unless I've screwed up completely
All pods call each other on the 10.240 network and services on 10.241
The hosts are on 172.16

**Comment by tomdee** [comment]
I'm struggling to get to the bottom of this. This piece of code is where the kubelet error is coming from - https://github.com/kubernetes/kubernetes/blob/v1.2.0-beta.1/pkg/kubelet/network/cni/cni.go#L145

It would seem that GetContainerIP is returning the string "Device "eth0" does not" and not signalling an error. That is then tripping up net.ParseCIDR.

I'll continue working on this tomorrow - still not sure if it's a Calico problem or a more general Kubernetes-with-CNI problem

**Comment by tobad357** [comment]
Hmm this may be a timing issue.
I added some debug logs around the line above and then the error statement goes away.
I'm also pretty sure I've seen this error in alpha7 which means the issue with eth0 may not be the issue causing restarts but still filling the logs with red herrings. 
Not sure though

**Comment by tobad357** [comment]
Some more information
All works well with 1.2-beta.0
The issue with constantly restarting containers still happens with 1.2-beta.1

**Comment by tomdee** [comment]
I'm still looking at this but struggling to reproduce it. @pmorie - have you make any changes in this area? @thockin said that you might have.

**Comment by bprashanth** [comment]
@dcbw

**Comment by tomdee** [comment]
If it really is a regression from beta0 to beta1, the diff here might help - https://github.com/kubernetes/kubernetes/compare/v1.2.0-beta.0...v1.2.0-beta.1

The one change that jumps out this this one from @dcbw https://github.com/kubernetes/kubernetes/commit/bc62096ad5ea8ce15156b39cfd2333bc6f589905

**Comment by pmorie** [comment]
@tomdee the changes that I made were at a higher level, and were around how the kubelet determines the pod IP to inject into:

1.  The hosts file that is bind-mounted into the container
2.  Environment variables that consume the pod IP via the downward API

Relevant PR is #22666

**Comment by thockin** [comment]
I'm bringing up a new cluster, to be 100%v sure, but given the lack of failure on e2e, it looks like this is CNI specific, yes?  I need a signal on whether this is a stop-ship - @dcbw can you confirm or deny?  Marking p0 for triage

@goltermann @bgrant0607

**Comment by bprashanth** [comment]
Make sure you grab https://github.com/kubernetes/kubernetes/issues/23011 if you're running with kubenet (which btw we can also P0 triage, I thought ship had sailed)

**Comment by thockin** [comment]
I don't think #23011 is a release-blocker, and I am not 100% sure this is either.

**Comment by errordeveloper** [comment]
xref https://github.com/weaveworks/weave/issues/2030

**Comment by errordeveloper** [comment]
It'd be easy for me to try reproducing this with `v1.2.0-beta.0`, if that could help?

**Comment by errordeveloper** [comment]
@thockin are you thing whether this may be final release blocker or the the next alpha? How alphas are cut, by the way?

**Comment by bgrant0607** [comment]
@errordeveloper There's 1.2.0-beta.0 and 1.2.0-beta.1. 

What we thought was the last batch of cherrypicks for 1.2.0 is in #23024 and, barring problems, we expect that to merge within the hour.

Then, if tests pass consistently, we expect to build 1.2.0 tomorrow morning.

So, if we decide this is a release blocker, it is the last remaining blocker.

**Comment by thockin** [comment]
Any confirmation would be helpful

**Comment by errordeveloper** [comment]
I'll be able to run my test agains `v1.2.0-beta.0` AM GMT, it's pretty late here now...

**Comment by errordeveloper** [comment]
> It would seem that GetContainerIP is returning the string "Device "eth0" does not" and not signalling an error. That is then tripping up net.ParseCIDR.

@tomdee so `Device "eth0" does no` come from `ip addr eth0`, that is called with a pipe like this `nsenter -- bash -c "ip addr show %s | grep inet | awk '{ print $2 }'"`, and we are clearly not handling the return code properly... Although, I do wish this code wasn't shelling out, debugging it as is should be doable if I knew how to stop the world in a reliable way, so any hint on that would be hugely appreciated (I heard that gdb doesn't work quite well with Go...).

**Comment by bprashanth** [comment]
I'm not able to reproduce this with a simple test that creates a busybox pod using the stock CNI bridge plugin. The "eth0" thing might be a transient race of Status invocation that just fixes itself.  

To isolate the unknown can either @tobad357 or @errordeveloper please try with:
1. Pass `--network-plugin=cni` and `--network-plugin-dir=/etc/cni/net.d` to the kubelet 
2. Install CNI plugins into `/opt/cni/bin`
3. Install a netconf into `/etc/cni/net.d`, like:
```json
{"bridge":"cbr0","ipMasq":true,"ipam":{"routes":[{"dst":"0.0.0.0/0"}],"subnet":"10.240.1.0/24","type":"host-local"},"isGateway":true,"name":"kubenet","type":"bridge"}
```

And you're off to the races.

Also can you also please confirm that this isn't a DNS problem? since by default we proxy all DNS lookups through kube-dns your other containers like kube-ui might be restarting because they can't lookup.

**Comment by tobad357** [comment]
I've done some testing on my side
I built 1.2.0-beta0 up until the commit before https://github.com/kubernetes/kubernetes/commit/bc62096ad5ea8ce15156b39cfd2333bc6f589905 which works fine and then I rebuilt with https://github.com/kubernetes/kubernetes/commit/bc62096ad5ea8ce15156b39cfd2333bc6f589905included and the issues with restarting pods comes back.. looking at the logs of one pod it shows that the termination signal has been sent to it.

I also did some logging inside of [dockertools/manager.go.podInfraContainerChanged](https://github.com/kubernetes/kubernetes/blob/bc62096ad5ea8ce15156b39cfd2333bc6f589905/pkg/kubelet/dockertools/manager.go#L801) and can see that the last check comparing hash [dockertools/manager.go.podInfraContainerChanged](https://github.com/kubernetes/kubernetes/blob/bc62096ad5ea8ce15156b39cfd2333bc6f589905/pkg/kubelet/dockertools/manager.go#L830) always returns that it has changed. Not sure why yet

**Comment by errordeveloper** [comment]
@bprashanth I am testing bridge plugin now, as you suggested, instead of Weave plugin.

**Comment by tobad357** [comment]
I've found the issue for the restarting pods. It is when using CNI and the docker image exports ports as well. This is due to a difference between the creation of the Container object when creating the pod and when checking if it has changed.
You should be able to replicate this by running a docker image with exported ports under kubernetes + cni. I should have pull request ready soon

**Comment by errordeveloper** [comment]
Also, I have discovered #23039, which makes me a little suspicious whether tests agains CNI only ran on internal system of whoever uploaded the build...

**Comment by bboreham** [comment]
One thing that makes this kind of thing very hard to debug (at least for me, not hugely experienced working with k8s) is that after a short while k8s decides things are bad, kills a bunch of things and restarts them to try again.  I understand why it does that, but is there a way to stop it while I get a chance to look at what happened?

**Comment by errordeveloper** [comment]
@tobad357 I am not sure what you are saying exactly, but will wait for your pull-request.

**Comment by tobad357** [comment]
@errordeveloper check this if statement https://github.com/kubernetes/kubernetes/blob/bc62096ad5ea8ce15156b39cfd2333bc6f589905/pkg/kubelet/dockertools/manager.go#L805

vs

https://github.com/kubernetes/kubernetes/blob/bc62096ad5ea8ce15156b39cfd2333bc6f589905/pkg/kubelet/dockertools/manager.go#L1593

you can see that the case is slightly different which means the container the hash is calculated against originally will always differ from the one that is checked for changes in the case where the docker image exports ports

**Comment by errordeveloper** [comment]
@tobad357 that would explain why `kubectl run -i --tty busybox --image=busybox --restart=Never` worked just fine with Weave plugin!

**Comment by tobad357** [comment]
@errordeveloper  correct

**Comment by errordeveloper** [comment]
Also, using the CNI binaries from the released tarball with a workaround #23039 and config from @bprashanth (https://github.com/kubernetes/kubernetes/issues/22932#issuecomment-197124674) I get this:
```
2016-03-16 09:24:57 +0000 UTC   2016-03-16 09:26:36 +0000 UTC   41        redis-master-9wkyg   Pod                 Warning   FailedSync   {kubelet kubedev}   Error syncing pod, skipping: failed to "SetupNetwork" for "redis-master-9wkyg_default" with SetupNetworkError: "Failed to setup network for pod \"redis-master-9wkyg_default(e10c3705-eb58-11e5-a8ce-0242ac110004)\" using network plugins \"cni\": ARGS: invalid key \"K8S_POD_NAMESPACE\"; Skipping pod"
```

**Comment by tobad357** [comment]
@thockin @bgrant0607 please see the pull request which is minimal.
Personally I'm ok to wait to put it in 1.2.1 as I have a patched build
However for someone new to kubernetes that decides to use weave, calico or similar and deploys a docker image with exported ports they will end up with pods restarting and zero logs on why
It's quite a bad experiance

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-network

**Comment by bgrant0607** [comment]
@tobad357 Please reference this issue from the PR, not from commits.

**Comment by tobad357** [comment]
@bgrant0607 sorry about that, added it to the pull request.

**Comment by bprashanth** [comment]
@errordeveloper @tobad357 we're not quite at the stage where we're dog fooding CNI yet (kubenet is off by default). We hope to get there sometime between now and 1.3. Thanks for the quick turn around on this, please keep filing issues where different plugins/environments diverge.

**Comment by euprogramador** [comment]
Personal 'm having this error also in version 1.2.3

**Comment by euprogramador** [comment]
this error not viewed in version 1.3.0-alpha.2.

**Comment by jonathan-kosgei** [comment]
Hi I'm having the same error,  NetworkPlugin cni failed on the status hook for pod 'nginx' - invalid CIDR address: Device "eth0" does not exist, what was the fix exactly?

**Comment by euprogramador** [comment]
@jonathan-kosgei Bug for CNI driver tab caracteres not allowed in file, i am submit pull request for correction. Verify tour file contains tab caracters and remove

**Comment by jonathan-kosgei** [comment]
@euprogramador My `/etc/cni/10-calico.conf` and `/etc/rkt/10-calico.conf` look like:
```
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_authority": "{{ etcd_authority }}",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    }
}
```
My `/etc/network-environment` has:
```
# This host's IPv4 address (the source IP address used to reach other nodes
# in the Kubernetes cluster).
DEFAULT_IPV4={{ ansible_default_ipv4['address'] }}

# The Kubernetes master IP

# IP and port of etcd instance used by Calico
ETCD_AUTHORITY={{ etcd_authority }}
```
I've checked and I don't have tabs in either files.

**Comment by euprogramador** [comment]
@jonathan-kosgei you are running it in a ansible playbook ?,
/etc/cni/net.d/10-calico.conf "etcd_authority": "{{etcd_authority}}" should have ip ETCD server, and the environment must have the tambpém DEFAULT_IPV4 settings such as the server ip and ETCD_AUTHORITY with the ip of the server ETCD.

**Comment by euprogramador** [comment]
@jonathan-kosgei you using systemd? /etc/enviroment should be set in kubelet variables section

**Comment by jonathan-kosgei** [comment]
Yes, on the server I have :
`/etc/cni/net.d/10-calico.conf`
```
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_authority": "172.1.1.4:6666",
    "log_level": "info",
    "ipam": {"type": "calico-ipam"}
}
r
```
and `/etc/network-environment`:
```
# This host's IPv4 address (the source IP address used to reach other nodes
# in the Kubernetes cluster).
DEFAULT_IPV4=172.1.2.4

# The Kubernetes master IP

# IP and port of etcd instance used by Calico
ETCD_AUTHORITY=172.1.1.4:6666
```
and the following flags on kubelet:
` --network-plugin=cni --network-plugin-dir=/etc/cni/net.d`

**Comment by euprogramador** [comment]
@jonathan-kosgei post your kubelet.service?

**Comment by jonathan-kosgei** [comment]
```
[Unit]
Description=Kubernetes Kubelet Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=calico-node.service
Requires=calico-node.service

[Service]
WorkingDirectory=/var/lib/kubelet
EnvironmentFile=-/etc/kubernetes/config
EnvironmentFile=-/etc/kubernetes/kubelet
ExecStart=/usr/bin/kubelet \
	    $KUBE_LOGTOSTDERR \
	    $KUBE_LOG_LEVEL \
	    $KUBELET_API_SERVER \
	    $KUBELET_ADDRESS \
	    $KUBELET_PORT \
	    $KUBELET_HOSTNAME \
            $KUBELET_POD_INFRA_CONTAINER \
            $KUBELET_ARGS \
--network-plugin=cni \
--network-plugin-dir=/etc/cni/net.d \
--allow-privileged=true \
--cluster-dns= 10.254.0.10 \
--cluster-domain=cluster.local
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by euprogramador** [comment]
@jonathan-kosgei you are not setting the / etc / network-environment in your file as variables, it may be the error, add EnvironmentFile=-/etc/network-environment

**Comment by euprogramador** [comment]
@jonathan-kosgei inform it is work, ok?

**Comment by jonathan-kosgei** [comment]
Okay, let me try that.

**Comment by jonathan-kosgei** [comment]
Tried it, but I still get the same error:
```
Jul 04 15:32:28 sc-minion-1 kubelet[11694]: E0704 15:32:28.536232   11694 manager.go:212] Docker container factory registration failed: docker found, but not using native exec driver.
Jul 04 15:32:28 sc-minion-1 kubelet[11694]: I0704 15:32:28.537239   11694 factory.go:97] Registering Raw factory
Jul 04 15:32:28 sc-minion-1 kubelet[11694]: I0704 15:32:28.808954   11694 manager.go:1003] Started watching for new ooms in manager
Jul 04 15:32:28 sc-minion-1 kubelet[11694]: I0704 15:32:28.809472   11694 oomparser.go:198] OOM parser using kernel log file: "/var/log/kern.log"
Jul 04 15:32:28 sc-minion-1 kubelet[11694]: I0704 15:32:28.827490   11694 manager.go:256] Starting recovery of all containers
Jul 04 15:32:29 sc-minion-1 kubelet[11694]: I0704 15:32:29.159217   11694 kubelet.go:1150] Node 172.1.2.4 was previously registered
Jul 04 15:32:30 sc-minion-1 kubelet[11694]: I0704 15:32:30.108809   11694 manager.go:261] Recovery completed
Jul 04 15:32:34 sc-minion-1 kubelet[11694]: W0704 15:32:34.206340   11694 kubelet.go:1979] Orphaned volume "7523441b-41a9-11e6-981f-000d3a117eb7/default-token-mxate" found, tearing down volume
Jul 04 15:33:06 sc-minion-1 kubelet[11694]: E0704 15:33:06.737394   11694 manager.go:309] NetworkPlugin cni failed on the status hook for pod 'nginx' - invalid CIDR address: Device "eth0" does not exist.
Jul 04 15:33:08 sc-minion-1 kubelet[11694]: I0704 15:33:08.491848   11694 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
```

**Comment by jonathan-kosgei** [comment]
I deleted and recreated the nginx pod.

**Comment by jonathan-kosgei** [comment]
#https://github.com/projectcalico/calico-containers/issues/949
