### ISSUE TITLE
Eventer has the same memory requirements as Metrics Heapster

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#22937]

**Comment by mwielgus** [comment]
cc: @piosz

**Comment by mwielgus** [comment]
in progress: #22940

**Comment by mwielgus** [comment]
The problem is that heapster has the same memory limits set for both containers instead of one.

**Comment by davidopp** [comment]
@mwielgus says he is still testing on 1k node cluster, so we should hold off on merging this

**Comment by davidopp** [comment]
As an aside, some of us (including me) were surprised to discover that we are running two instances of heapster (one as "eventer"). Can you explain this architecture, and the difference in functionality between the two heapsters?

**Comment by mwielgus** [comment]
https://github.com/kubernetes/heapster/blob/master/docs/proposals/vision.md

**Comment by piosz** [comment]
https://github.com/kubernetes/heapster/blob/master/docs/proposals/vision.md#separation-of-use-cases

**Comment by davidopp** [comment]
#22940 merged, so closing this issue.
