### ISSUE TITLE
Generated protobuf tags seems to be incorrect

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#22941]
The "protobuf" tags that we are generating seems to be wrong - in particula most of them claim the type to be bytes, e.g.:

    HostPath *HostPathVolumeSource `json:"hostPath,omitempty" protobuf:"bytes,1,opt,name=hostPath"`

    EmptyDir *EmptyDirVolumeSource `json:"emptyDir,omitempty" protobuf:"bytes,2,opt,name=emptyDir"`

@smarterclayton - FYI

**Comment by wojtek-t** [comment]
I will take a look and try to fix it.

**Comment by wojtek-t** [comment]
Or maybe it is correct? @smarterclayton

**Comment by wojtek-t** [comment]
If that's correct (and now I think it is, but I will try to look deeper) this code:
https://github.com/kubernetes/kubernetes/blob/master/cmd/libs/go2idl/go-to-protobuf/protobuf/generator.go#L471

doesn't make much sense then.. (becuase it's always varint, bytes or fixed64)

**Comment by wojtek-t** [comment]
Yes - actually those values are correct - there are just few possible values:
https://github.com/golang/protobuf/blob/master/proto/properties.go#L262

That means the code that is trying to parse it:
https://github.com/kubernetes/kubernetes/blob/master/cmd/libs/go2idl/go-to-protobuf/protobuf/generator.go#L471
doesn't make sense.

I will clean it up.

**Comment by wojtek-t** [comment]
Will send out a slightly bigger (with some refactoring) PR tomorrow.

**Comment by smarterclayton** [comment]
I'm trying to remember, but it may be that the parsing code existed before
the read back of tags.  So it should be able to go away.
