### ISSUE TITLE
Configuration File Examples

### ISSUE THREAD

**Issue by lgreenlee** [kubernetes/kubernetes#22950]
I am having a hard time finding a comprehensive resource for valid values permissible in configuration files. It would be really nice to have a reference that just describes the valid values and their use. For example: what are the total optional and required fields for a replication controller definition? A Service? A Pod? The documentation has many examples, but when there is any discussion of configuration files there should at least be a reference to the full definition of the configuration file.

Take for example th following documentation: 

http://kubernetes.io/docs/user-guide/configuring-containers/

It has a YAML example, but there is no description of all of the valid fields for a Pod configuration. So creating specs outside of the examples becomes rather difficult.

**Comment by rwillard** [comment]
http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_pod

**Comment by lgreenlee** [comment]
Thanks, this helpful but it is very difficult to construct a working configuration file from that document alone. These fields map to configuration values in the files but there is no discussion of the actual syntax. Links to "spec" for example, a rather important section of the configurations is largely unexplained: https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/devel/api-conventions.md#spec-and-status. Also, the "kind" is an important keyword but is set as optional in that document, but in reality can you have a definition without "kind"? Every example in the documentation has a "kind".

What I'm really looking for is a standalone document for the various valid configurations in a format where potential options are enumerated. For example, the type field for Service goes unmentioned in the api-reference documentation but appears to have only two valid options now LoadBalancer and NodePort. The format could be in either JSON or YAML. A JSON schema for each major type such as Pod, ReplicationController, Service, Node, PersistentVolume ... etc. might be one solution. YAML schemas seem a little difficult to interpret.

I do appreciate the copious examples, it would just be nice to see all of the options for the different types in coherent set of locations.

**Comment by harshal-dhumal** [comment]
Even I'm facing same issue. I want to run kubelet on node but I can't cause I don't have config file for kubelet. I was able to run etcd and api server as they don't require any config file.

I searched on internet for sample config file and documentation for kubelet config file but no success. :(
