### ISSUE TITLE
Revisit Container Runtime interface 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#22964]
In many threads / meetings I mentioned that we are not satisfied with today's container runtime interface due to many reasons. Here are the top reasons off my head:
- Duplicated code for supporting SyncPod for all container runtime implementations, especially with Kubernetes defined policy: StartPolicy, PullPolicy, etc. We talked about changing today's declarative API to imperative API at this lowest extensible point. 
- Tight coupled with image format: docker runtime supports docker image, while rkt support appc image by converting docker image to its own format. In a long run, we want to add support for other image format without changing each runtime. There is no easy way to achieve that goal with today's API.
- Logging management is very different on different os distro and with different runtime implementation. We should make this pluggable with runtime.
- Part of resource isolation is handled by runtime today, while another part is handled by Kubelet. The decision is ad-hoc without much thinking. We need to decide if we want runtime interface to handle resource management or completely hand over to ResourceManager module in Kubelet since qos policy is defined by Kubernetes, and it might be redefined over releases. 
- ...

In my mind, we should separate image management, resource / cgroup management, logging management from today's runtime interface. After this effort, we effectively make today's runtime interface as pod / container lifecycle management interface.

cc/ @kubernetes/sig-node, @bgrant0607 
cc/ @philips and @jonboulle @yifan-gu from coreos
cc/ @smarterclayton @derekwaynecarr from redhat

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
cc @mrunalp

**Comment by derekwaynecarr** [comment]
I am supportive of a `ResourceManager` module

I am also supporting of defining a clear `PodLifecycleManager` module that I can invoke to kill a pod without needing to know about all the other related managers.

**Comment by yujuhong** [comment]
> I am also supportive of a PodLifecycleManager module that I can invoke to kill a pod without needing to know about all the other related managers.

@derekwaynecarr, I understand your pain. I think half of the problem originates from the fact that kubelet doesn't have this feature, i.e., telling the pod worker to do something explicitly. Each worker today takes actions autonomously based on the pod spec and status (with the famous all-in-one SyncPod() function). We can certainly explore options to make this easier (e.g., saving internal states or use a merge queue). The other half is about getting the status to confirm the action is completed, which we can potentially hide behind an interface.

**Comment by derekwaynecarr** [comment]
@yujuhong this is related to my need for out of resource killing having a place to call to kill a pod, ideally with an option to block.

**Comment by yujuhong** [comment]
> @yujuhong this is related to my need for out of resource killing having a place to call to kill a pod, ideally with an option to block.

Yes, I knew :-)  I was just pointing out that It's *hard* to implement partly because it's not something kubelet supports naively. Until now, there has been no need for pod workers to do anything other than looking at the pod spec call SyncPod. We need to put into more work for sure, and I definitely agree that having a better interface will help.

**Comment by dchen1107** [comment]
cc/ @kelseyhightower

**Comment by dchen1107** [comment]
Here is the high level draft we are coming with: 

https://docs.google.com/document/d/1ietD5eavK0aTuMQTw6-21r67UU73_vqYSUIPFdA0J5Q/edit#

**Comment by dchen1107** [comment]
cc/ @rajatchopra @mrunalp

**Comment by yujuhong** [comment]
The new proposal PR: #25899

**Comment by yujuhong** [comment]
Closing this in favor of #28789 for tracking.
