### ISSUE TITLE
Mapping VMs to Pods using Guestbook sample

### ISSUE THREAD

**Issue by yahavb** [kubernetes/kubernetes#22968]
Hello - I'm new to kubernetes and I just finish to work on the Guestbook sample. As indicated in the tutorial, after issueing the command kubectl scale --replicas=5 rc front-end I get 5 replicas for the frontend service. However, when I look at my list of VMs in my Compute Engine project is see only three VMs provisioned. Is there any way to understand how the 5 services/pods are deployed across the three VMs? What if the 5 replicas exhausting the three VMs capacity, will it spin another VM or should I need to manually spin more VMs using gcloud?
Thanks

**Comment by viglesiasce** [comment]
Kubernetes itself does not handle autoscaling of the cluster. It will bin pack the containers onto the existing cluster. You can use the following if your are using GKE:
https://cloud.google.com/container-engine/docs/resize-cluster

**Comment by yahavb** [comment]
That make sense. thanks!
