### ISSUE TITLE
The right way for Deployments to list ReplicaSets

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#22961]
In deployment controller and deployment util, we list old ReplicaSets and new ReplicaSet of a deployment by listing the ones with labels matching deployment's selector. 

We should instead:

1. find the ReplicaSet that controls the pods that deployment targets (pods with labels matching deployment's selector), but this doesn't allow us to find the old ReplicaSet with 0 replicas; or 
2. find the ReplicaSet whose label selector is a superset of deployment's selector, once we implement the comparison between `LabelSelector`s, see #19830, or 
3. use `controllerRef` once we implement it, see #2210

@kubernetes/sig-config @nikhiljindal

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/31306
