### ISSUE TITLE
Advice on troubleshooting stuck pv creation at pending state

### ISSUE THREAD

**Issue by moomou** [kubernetes/kubernetes#22963]
Hey guys, I am trying to create `pv` and `pvc` resources via `kuberctl create -f pv-definition.json` but k8s doesn't make any progress and it just kept reporting `PENDING` states for them. 

Looked at `kubectl get events` and logs from `api`, `controller`, but I don't see anything related to messages to `pv` or `pvc` creation. I have the disk created beforehand on gcloud and I have verified that the name and disk size matches.

Does anyone have any suggestion for debugging?

PV definition: https://gist.github.com/moomou/47f08f5130045e45ffee

Edit: I am on v1.1.3

**Comment by pwittrock** [comment]
@moomou We are trying to standardize keeping help / debugging questions on StackOverflow and Slack.  You will probably get a more prompt response through those channels.
