### ISSUE TITLE
Bind IP Address to the Pod

### ISSUE THREAD

**Issue by jay-lau** [kubernetes/kubernetes#22976]
Does Kubernetes have the feature of binding an IP address to a a Pod, even if the Pod restarted, it will still get its old IP?

**Comment by viglesiasce** [comment]
You can bind the IP to a service and put pod(s) behind the service. Check out http://kubernetes.io/docs/user-guide/services/#choosing-your-own-ip-address

**Comment by ArtfulCoder** [comment]
@jay-lau I am closing this issue. If your requirement is not met by cluster-ip, please re-open the issue.

**Comment by jay-lau** [comment]
Thanks @ArtfulCoder and @viglesiasce  will try for cluster-ip.
