### ISSUE TITLE
Lack of apiserver logs from kubemark-scale

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#22978]
We are not able to debug kubemark-scale failure due to lack of apiserver logs.
The problem is the consequence of the following log:

    Uploading to gs://kubernetes-jenkins/logs/kubernetes-kubemark-gce-scale/885 (attempt 1)
    Error copying file:///var/lib/jenkins/jobs/kubernetes-kubemark-gce-scale/workspace/_artifacts: CommandException: Inadequate temp space available to compress file:///var/lib/jenkins/jobs/kubernetes-kubemark-gce-scale/workspace/_artifacts/kubemark-1000-kubemark-master/kube-apiserver.log. See the CHANGING TEMP DIRECTORIES section of "gsutil help cp" for more info.
    CommandException: 1 file/object could not be transferred.

@ixdy @spxtr @gmarek

**Comment by wojtek-t** [comment]
@spxtr - can you please take a look what can we do with it?

**Comment by spxtr** [comment]
https://cloud.google.com/storage/docs/gsutil/commands/cp#changing-temp-directories

Seems reasonable to set this to something in the workspace for the upload. This should get better once we're using multiple Jenkins machines to run e2e tests.

**Comment by spxtr** [comment]
This is something that should be fixed once we use Jenkins slaves properly.

**Comment by gmarek** [comment]
Awesome:)

**Comment by spxtr** [comment]
Should be fixed, let me know if you see it again.
