### ISSUE TITLE
Allow ABAC authorizor to load policy file from etcd

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#22988]
I'm interested to have ABAC module to load the policy file directly from ETCD. This is useful for a multi-apiserver HA setup as they're already using the same ETCD cluster and having a policy file replicated to multiple nodes is just less clean.

**Comment by huang195** [comment]
I'm thinking the way for ABAC to differentiate between loading from a local file vs. ETCD is that ETCD should always start with etcd://, e.g., etcd://path/to/policy/file.

cc @smarterclayton @liggitt @erictune This is a small change. What do you think?

**Comment by huang195** [comment]
By default, we can assume the list of ETCD servers that ABAC should load from are what the apiserver also uses. However, user should be allowed to specific a different set of ETCD servers, e.g., `--authorization-policy-file=etcd://1.1.1.1:2379/policy,etcd://1.1.1.2:2379/policy,etcd://1.1.1.3:2379/policy`, but this looks kind of ugly.

**Comment by huang195** [comment]
another complication is http vs. https for reaching etcd. Now to think about it, it might be OK just to default to the list of etcd servers that the apiserver is using, and then one just need to specify `--authorization-policy-file=etcd://path/to/file`

**Comment by huang195** [comment]
xref: #18565
xref: #17440

**Comment by liggitt** [comment]
I don't think I want to add side-loading objects from etcd using a non-API method

**Comment by huang195** [comment]
@liggitt I'm looking for a quick but clean way for ABAC to take input from a REST storage rather than from a local file. If I'm understanding the xrefs correctly, eventually all the runtime authorization policies should be stored in the Kubernetes etcd. When the authorization policy needs to be changed, well defined API methods will be invoked to allow these changes and persist them into the etcd. 

The problem we're solving here is different. Here, we're just talking about the bootstrapping of an initial set of authorization policies from a **source location**. Today, that source location can only be a local file, and I'd like to extend this to other REST storage options, e.g., etcd. Once the policies are loaded from a source location, it can be stored/manipulated/quarantized or whatever before storing into the Kubernetes backend etcd (this part is not implemented today and are described in the xrefs, but that is not to related to this work).

**Comment by liggitt** [comment]
Right. In general, I don't think it's a good idea to have more things talking to the etcd used to store API objects, in order to store non-API objects. Maybe I'm misunderstanding the proposal.

**Comment by huang195** [comment]
Put it more concretely, we have 2 etcd clusters in our environment, where 1 is used for kubernetes, and 1 is used for storing other configuration information. I'd like to put my abac policy file on the latter. This, however, doesn't work as abac can only load the file locally, not from etcd. So what I'm proposing is to have abac to also be able to load file directly from etcd (i.e., the one not used by kubernetes).

**Comment by huang195** [comment]
I realized maybe the title was confusing. Hopefully this clarifies it.

**Comment by huang195** [comment]
@liggitt I'm currently working on adding this function, and it's completely backward compatible. Once I've got it working and fully tested it, I'd like to push it upstreams. Do you have any other suggestions on this proposal?

**Comment by smarterclayton** [comment]
RBAC has supplanted this.
