### ISSUE TITLE
Cannot create pod with the same name as a pod that has already finished

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#22986]
I created pod with the following command:
```
kubectl run load-generator --image=busybox --restart=Never
```
The pod has finished successfully. The pod is not displayed in pod list, although when I try to run a pod with the same name I've got an error:
```
Error from server: pods "load-generator" already exists
``` 

@bgrant0607 not sure if this works as intended. If yes it's at least very confusing. 

cc  @fgrzadkowski @gmarek

**Comment by bgrant0607** [comment]
@piosz Finished != deleted. WAI

Do `kubectl get pods --show-all`

**Comment by bgrant0607** [comment]
We intentionally don't delete pods when they finish so people can see what status they finished with.

**Comment by bgrant0607** [comment]
We should definitely document this behavior, though.

**Comment by fgrzadkowski** [comment]
Maybe it'd help if we print some warning that the existing pod which we conflict with is in state finished? We can also print a warning in `kubectl get pods` that some pods may have been omitted and you need to run `--show-all` to print everything. WDYT? @bgrant0607

**Comment by bgrant0607** [comment]
Good idea @fgrzadkowski

**Comment by AdoHe** [comment]
also SGTM.

**Comment by vefimova** [comment]
Hi guys, as it's not possible to assign issue to myself, just posting comment here, that I'm going to prepare patch for it, to not be working on the same isuue with somebody else. 
BTW, is there another method to annonce that you started to work on the issue?

**Comment by janetkuo** [comment]
@vefimova thanks!

**Comment by idvoretskyi** [comment]
@vefimova just let us know here in the thread. Usually, that's enough.

If someone would like to work on this issue as well, I hope, they will reach you in the thread.
