### ISSUE TITLE
kubelet --hostname-override is ignored in v1.2.0-beta.1

### ISSUE THREAD

**Issue by alexkappa** [kubernetes/kubernetes#22984]
Running `kubectl get nodes` shows the master node name in the default aws format.

```
NAME                                       LABELS                                                                                                                                                                             STATUS                     AGE
254.1.161.115                              kubernetes.io/hostname=254.1.161.115                                                                                                                                               Ready                      14h
254.1.35.13                                kubernetes.io/hostname=254.1.35.13                                                                                                                                                 Ready                      14h
ip-254-1-0-10.eu-west-1.compute.internal   beta.kubernetes.io/instance-type=m4.large,failure-domain.beta.kubernetes.io/region=eu-west-1,failure-domain.beta.kubernetes.io/zone=eu-west-1a,kubernetes.io/hostname=254.1.0.10   Ready,SchedulingDisabled   14h
```

The `kubelet` is started using the following options. I only started seeing this when I used the `--register-schedulable=false` (`kubectl get nodes` wouldn't list the master node previously).

```
kubelet \
  --address=$private_ipv4 \
  --allow-privileged=true \
  --api-servers=http://127.0.0.1:8080 \
  --cadvisor-port=4194 \
  --cloud-provider=aws \
  --cluster-dns=10.100.0.10 \
  --cluster-domain=cluster.local \
  --config=/etc/kubernetes/manifests \
  --hairpin-mode=promiscuous-bridge \
  --healthz-bind-address=0.0.0.0 \
  --healthz-port=10248 \
  --hostname-override=$private_ipv4 \
  --port=10250 \
  --register-node=true \
  --register-schedulable=false
```

I believe this is causing new nodes to not be able to register, as I am getting the following errors on a newly added node.

```
Mar 15 12:23:14 k8s-node kubelet[1009]: E0315 12:23:14.565088    1009 kubelet.go:2697] Error updating node status, will retry: error getting node "254.1.106.101": nodes "254.1.106.101" not found
Mar 15 12:23:14 k8s-node kubelet[1009]: E0315 12:23:14.566390    1009 kubelet.go:2697] Error updating node status, will retry: error getting node "254.1.106.101": nodes "254.1.106.101" not found
Mar 15 12:23:14 k8s-node kubelet[1009]: E0315 12:23:14.567792    1009 kubelet.go:2697] Error updating node status, will retry: error getting node "254.1.106.101": nodes "254.1.106.101" not found
Mar 15 12:23:14 k8s-node kubelet[1009]: E0315 12:23:14.567805    1009 kubelet.go:1173] Unable to update node status: update node status exceeds retry count
Mar 15 12:23:24 k8s-node kubelet[1009]: E0315 12:23:24.569728    1009 kubelet.go:2697] Error updating node status, will retry: error getting node "254.1.106.101": nodes "254.1.106.101" not found
Mar 15 12:23:24 k8s-node kubelet[1009]: E0315 12:23:24.576356    1009 kubelet.go:2697] Error updating node status, will retry: error getting node "254.1.106.101": nodes "254.1.106.101" not found
Mar 15 12:23:24 k8s-node kubelet[1009]: E0315 12:23:24.577641    1009 kubelet.go:2697] Error updating node status, will retry: error getting node "254.1.106.101": nodes "254.1.106.101" not found
Mar 15 12:23:24 k8s-node kubelet[1009]: E0315 12:23:24.578926    1009 kubelet.go:2697] Error updating node status, will retry: error getting node "254.1.106.101": nodes "254.1.106.101" not found
Mar 15 12:23:24 k8s-node kubelet[1009]: E0315 12:23:24.580302    1009 kubelet.go:2697] Error updating node status, will retry: error getting node "254.1.106.101": nodes "254.1.106.101" not found
Mar 15 12:23:24 k8s-node kubelet[1009]: E0315 12:23:24.580314    1009 kubelet.go:1173] Unable to update node status: update node status exceeds retry count
```

Related: #8195, #15108.

Thanks in advance!

**Comment by AdoHe** [comment]
@alexkappa IIRC if you are using a cloud provider, kubelet  will query cloud provider for the node name, and when kubelet register the node, this node name is used as the `ObjectMeta.Name`, the host name is used as one of the node labels. @dchen1107 for more detailed explanation.

**Comment by alexkappa** [comment]
@AdoHe indeed when `--cloud-provider` is set, `--hostname-override` is ignored. Should that be documented maybe? I could have saved me some trouble.

My particular issue was that my nodes kubelet didn't have `--cloud-provider` set so `--hostname-override` was in effect thus resulting in two different host naming conventions.

Thanks!

**Comment by AdoHe** [comment]
@kubernetes/sig-node

**Comment by vishh** [comment]
We should add a test under `test/e2e_node` for this feature to prevent this issue from happening again.

**Comment by AdoHe** [comment]
@vishh I am not very clear about what you mean, add a e2e for what feature? `--cloud-provider` and `hostname-override`?

**Comment by mzupan** [comment]
I noticed the same issue using `1.2.0` that it was using the reverse dns for the pod and completely ignoring the override. 

We use the override hostname to let the nodes self label.

**Comment by vishh** [comment]
@AdoHe: Yeah.

**Comment by AdoHe** [comment]
@vishh I will add this test this week.

**Comment by vishh** [comment]
@AdoHe: :+1: Kindly add the test to the node test suite under `/test/node_e2e`

**Comment by developerinlondon** [comment]
yes i am having the same issue. i need to be able to self-label the node in AWS cloud.

**Comment by AdoHe** [comment]
Initially this is how we handle `hostname-override` in kubelet:
```
kcfg.Hostname = nodeutil.GetHostname(kcfg.HostnameOverride)

	if len(kcfg.NodeName) == 0 {
		// Query the cloud provider for our node name, default to Hostname
		nodeName := kcfg.Hostname
		if kcfg.Cloud != nil {
			var err error
			instances, ok := kcfg.Cloud.Instances()
			if !ok {
				return fmt.Errorf("failed to get instances from cloud provider")
			}

			nodeName, err = instances.CurrentNodeName(kcfg.Hostname)
			if err != nil {
				return fmt.Errorf("error fetching current instance name from cloud provider: %v", err)
			}

			glog.V(2).Infof("cloud provider determined current node name to be %s", nodeName)
		}

		kcfg.NodeName = nodeName
	}
```
there are `nodeName` and `hostName`, they are different. For `nodeName`, `hostname-override` will be ignored if you are using cloud provider, we will use the node name determined by your cloud provider to register the node with apiserver. Perhaps we need some flag like `nodename-override` thus we can override node name even using cloud provider. @vishh @alexkappa @developerinlondon @mzupan wdyt?

**Comment by gtaylor** [comment]
To necro this thread, nodename-override would be wonderful.

**Comment by d-shi** [comment]
+1 to this as well. We use custom hostnames inside our VPCs, and I would like the node names inside k8s to match our hostnames rather than get them from AWS metadata.

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/54482

**Comment by dims** [comment]
for the record, what we should be doing from @liggitt : https://github.com/kubernetes/kubernetes/pull/58114#discussion_r160840393

**Comment by cabrinha** [comment]
Can we simply get a nodename-override flag added to kubelet?
