### ISSUE TITLE
Version-skewed client/master causing `fullyLabeledReplicas` errors in Kubectl apply

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#22996]
When Kubectl is at v1.2 and master is at v1.1:

**Kubectl client Kubectl apply should apply a new configuration to an existing RC**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:537 Expected error: <errors.errorString | 0xc2084e5b20>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.99.26 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/.kube/config apply -f - --namespace=e2e-tests-kubectl-nb5k6] [] 0xc20837a1e0 error validating \"STDIN\": error validating data: found invalid field fullyLabeledReplicas for v1.ReplicationControllerStatus; if you choose to ignore these errors, turn validation off with --validate=false\n [] 0xc208436b60 exit status 1 true [0xc2083e7a60 0xc2083e7a90 0xc2083e7aa8] [0xc2083e7a60 0xc2083e7a90 0xc2083e7aa8] [0xc2083e7a68 0xc2083e7a88 0xc2083e7aa0] [0x95e260 0x95e380 0x95e380] 0xc20839d500}:\nCommand stdout:\n\nstderr:\nerror validating \"STDIN\": error validating data: found invalid field fullyLabeledReplicas for v1.ReplicationControllerStatus; if you choose to ignore these errors, turn validation off with --validate=false\n\nerror:\nexit status 1\n", } Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.99.26 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/.kube/config apply -f - --namespace=e2e-tests-kubectl-nb5k6] [] 0xc20837a1e0 error validating "STDIN": error validating data: found invalid field fullyLabeledReplicas for v1.ReplicationControllerStatus; if you choose to ignore these errors, turn validation off with --validate=false [] 0xc208436b60 exit status 1 true [0xc2083e7a60 0xc2083e7a90 0xc2083e7aa8] [0xc2083e7a60 0xc2083e7a90 0xc2083e7aa8] [0xc2083e7a68 0xc2083e7a88 0xc2083e7aa0] [0x95e260 0x95e380 0x95e380] 0xc20839d500}: Command stdout: stderr: error validating "STDIN": error validating data: found invalid field fullyLabeledReplicas for v1.ReplicationControllerStatus; if you choose to ignore these errors, turn validation off with --validate=false error: exit status 1 not to have occurred*

In the reverse case, when Kubectl is as v1.1 and master is at v1.2:

**Kubectl client Kubectl apply should apply a new configuration to an existing RC**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:463 Expected error: <errors.errorString | 0xc2082aefa0>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.99.26 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/.kube/config apply -f - --namespace=e2e-tests-kubectl-ody8f] [] 0xc20854f830 error validating \"STDIN\": error validating data: field fullyLabeledReplicas: is required; if you choose to ignore these errors, turn validation off with --validate=false\n [] 0xc208370e60 exit status 1 true [0xc208784968 0xc2087849a0 0xc2087849d8] [0xc208784968 0xc2087849a0 0xc2087849d8] [0xc208784970 0xc208784998 0xc2087849d0] [0x6da490 0x6da5b0 0x6da5b0] 0xc20820a0c0}:\nCommand stdout:\n\nstderr:\nerror validating \"STDIN\": error validating data: field fullyLabeledReplicas: is required; if you choose to ignore these errors, turn validation off with --validate=false\n\n", } Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.99.26 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-1.2-step1-deploy/workspace/.kube/config apply -f - --namespace=e2e-tests-kubectl-ody8f] [] 0xc20854f830 error validating "STDIN": error validating data: field fullyLabeledReplicas: is required; if you choose to ignore these errors, turn validation off with --validate=false [] 0xc208370e60 exit status 1 true [0xc208784968 0xc2087849a0 0xc2087849d8] [0xc208784968 0xc2087849a0 0xc2087849d8] [0xc208784970 0xc208784998 0xc2087849d0] [0x6da490 0x6da5b0 0x6da5b0] 0xc20820a0c0}: Command stdout: stderr: error validating "STDIN": error validating data: field fullyLabeledReplicas: is required; if you choose to ignore these errors, turn validation off with --validate=false not to have occurred*

cc @bgrant0607

**Comment by ihmccreery** [comment]
@nikhiljindal Can I assign this to you to work on with #22884?

**Comment by ihmccreery** [comment]
EDIT: this is for v1.1 to v1.3, not v1.2.

**Comment by ihmccreery** [comment]
Or, rather, I'm not sure if it's for v1.2, because our jobs were configured wrong.

**Comment by ihmccreery** [comment]
Looks like this applies to v1.2 as well as v1.3:

http://kubekins.dls.corp.google.com/job/kubernetes-upgrade-gke-stable-1.2-step2-kubectl-e2e-new/27/

**Comment by ihmccreery** [comment]
@caesarxuchao I assume this was caused by https://github.com/kubernetes/kubernetes/pull/22847—is that a backward incompatible change?  It looks like v1.2 masters won't accept RCs without a `fullyLabeledReplicas` field?

**Comment by caesarxuchao** [comment]
Yes, I missed the "omitempty".

What's the easiest way to reproduce? I want to verify my PR will fix it.

**Comment by ihmccreery** [comment]
Launch a cluster at v1.1 and run Kubectl tests against it at v1.2 (for the first failure) and launch a cluster at v1.2 and run v1.1 Kubectl tests against it (for the second).

**Comment by bgrant0607** [comment]
We'll want this fix, but it shouldn't block the next bulk cherrypick.
cc @eparis

**Comment by bgrant0607** [comment]
cc @janetkuo

**Comment by caesarxuchao** [comment]
Explanation of the error:

The following is how the e2e test generates the data for `kubectl apply`:
```
func modifyReplicationControllerConfiguration(filename string) io.Reader {
	rc := readReplicationControllerFromFile(filename)
	rc.Labels[applyTestLabel] = "ADDED"
	rc.Spec.Selector[applyTestLabel] = "ADDED"
	rc.Spec.Template.Labels[applyTestLabel] = "ADDED"
	data, err := json.Marshal(rc)
        ...
	return bytes.NewReader(data)
}
```
Becuase FullyLabeledReplicas is not `omitempty`, `json.Marshal` applies the default value and the validation will fail because the schema pulled from the 1.1 master doesn't have this field.

**Comment by caesarxuchao** [comment]
Sent #23012 to fix.
