### ISSUE TITLE
e2e flake: "PreStop [It] should call prestop when killing a pod" is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#22991]
â€¢ Failure [308.652 seconds]
    PreStop
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pre_stop.go:167
      should call prestop when killing a pod [Conformance] [It]
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pre_stop.go:166

      waiting for server pod to start
      Expected error:
          <*errors.errorString | 0xc2084c86e0>: {
              s: "gave up waiting for pod 'server' to be 'running' after 5m0s",
          }
          gave up waiting for pod 'server' to be 'running' after 5m0s
      not to have occurred

      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pre_stop.go:64

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/22310/kubernetes-pull-build-test-e2e-gce/32670/build-log.txt

I looked into Kubelet logs and it seems like some registry issue - I've few logs like this:

    E0315 14:56:21.231105    3375 pod_workers.go:138] Error syncing pod 0ae95ac2-eabe-11e5-bb3a-42010af00002, skipping: failed to "StartContainer" for "server" with ErrImagePull: "unable to ping registry endpoint https://gcr.io/v0/\nv2 ping attempt failed with error: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable\n v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 10.240.0.1:53: dial udp 10.240.0.1:53: network is unreachable"

@kubernetes/goog-node - anything we can with that?

**Comment by yujuhong** [comment]
This is #20550.

**Comment by lavalamp** [comment]
Closing as a dup, then.
