### ISSUE TITLE
Fluentd writes to the same index for all namespaces

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#23001]
It would be nice to have logs end up in different indices based on a pod's namespace.

It looks like the ES plugin has a new feature in 1.4, which takes priority over `logstash-format`
https://github.com/uken/fluent-plugin-elasticsearch#target_index_key

**Comment by sosiouxme** [comment]
Since namespaces can be deleted and re-created, it is also a good idea to index by both namespace and its UUID so that different incarnations of the same namespace can be distinguished easily.

**Comment by therc** [comment]
I was able to implement this by putting td-agent.conf in a configmap and mounting that as a volume. I changed the file thus, also including the cluster name:

```
 <match **>
-   type elasticsearch
+   # This is expensive, but allows to separate logs by namespace
+   type elasticsearch_dynamic
    log_level info
    include_tag_key true
    host elasticsearch-logging
    port 9200
    logstash_format true
+   logstash_prefix logstash-MYCLUSTERNAME-${record['kubernetes']['namespace_name']}
    reload_connections false
    # Set the chunk limit the same as for fluentd-gcp.
    buffer_chunk_limit 2M
```

**Comment by jakubbujny** [comment]
@therc works like a charm! Thank you! It's probably the best way to separate logs from multideployment kubernetes cluster :)

**Comment by crassirostris** [comment]
Elasticsearch deployment in this repo is only an example and not a solution that works in any deployment, so I don't think we should change it here

Thanks for the workaround anyways!

**Comment by grebois** [comment]
https://github.com/kubernetes-incubator/kubespray/pull/2182

**Comment by sharmmoh1983** [comment]
I am trying to write custom config map for my fluentd daemonset for creating elastic search index based on kubernetes namespace.

```
 # we send the logs to Elasticsearch
    <match kubernetes.**>
        @type elasticsearch
        include_tag_key true
        host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
        port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
        scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
        ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
        reload_connections true
        logstash_prefix logstash-MYCLUSTERNAME-$['kubernetes']['namespace_name']
        logstash_format true
        <buffer>
            flush_thread_count 8
            flush_interval 5s
            chunk_limit_size 2M
            queue_limit_length 32
            retry_max_interval 30
            retry_forever true
        </buffer>
    </match>



```
Now when I see the index in ES , I get logstash-myclustername-$['kubernetes']['namespace_name']-2019.01.28

and not the equivalent values 

I have tried logstash-myclustername-${record['kubernetes']['namespace_name'] also but no use

Please let me know how to access these values in config map

**Comment by grebois** [comment]
@sharmmoh1983 

```
<match **>
  @type elasticsearch_dynamic
  #user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
  #password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
  @log_level info
  include_tag_key true
  host "#{ENV['OUTPUT_HOST']}"
  port "#{ENV['OUTPUT_PORT']}"
  logstash_format true
  logstash_prefix logstash-${record['kubernetes']['namespace_name']}
  <buffer>
    @type file
    path /var/log/fluentd-buffers/kubernetes.system.buffer
    flush_mode interval
    retry_type exponential_backoff
    flush_thread_count 2
    flush_interval 5s
    retry_forever
    retry_max_interval 30
    chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
    queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
    overflow_action block
  </buffer>
</match>

```

**Comment by fog1985** [comment]
> @sharmmoh1983
> 
> ```
> <match **>
>   @type elasticsearch_dynamic
>   #user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
>   #password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
>   @log_level info
>   include_tag_key true
>   host "#{ENV['OUTPUT_HOST']}"
>   port "#{ENV['OUTPUT_PORT']}"
>   logstash_format true
>   logstash_prefix logstash-${record['kubernetes']['namespace_name']}
>   <buffer>
>     @type file
>     path /var/log/fluentd-buffers/kubernetes.system.buffer
>     flush_mode interval
>     retry_type exponential_backoff
>     flush_thread_count 2
>     flush_interval 5s
>     retry_forever
>     retry_max_interval 30
>     chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
>     queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
>     overflow_action block
>   </buffer>
> </match>
> ```

And here what index was created with this approach:
```
test.k8s-${record['kubernetes']['namespace_name']}-2019.04.25
```
Any other options available? :)
