### ISSUE TITLE
NETWORK_PROVIDER=kubenet broken on GCE

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#23011]
Event for a pod: 
```console
Error syncing pod, skipping: failed to "SetupNetwork" for "kube-dns-v11-zbufd_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-v11-zbufd_kube-system(ea05b8bd-eada-11e5-8ced-42010af00002)\" using network plugins \"kubenet\": Error adding container to network: fork/exec /opt/cni/bin/bridge: no such file or directory; Skipping pod"
```

The cni plugins do exist at /opt/cni/bin. They cannot be executed and bash is complaining:
```console
root@e2e-test-mixia-minion-suyg:/opt/cni/bin# ls -al
total 37964
drwxr-x--- 2 8119 5000    4096 Jan 28 21:17 .
drwxr-xr-x 3 root root    4096 Mar 15 18:22 ..
-rwxr-xr-x 1 8119 5000 4781424 Jan 28 21:17 bridge
-rwxr-x--- 1 8119 5000 3615096 Jan 28 21:17 cnitool
-rwxr-x--- 1 8119 5000 9233472 Jan 28 21:17 dhcp
-rwxr-x--- 1 8119 5000 4017040 Jan 28 21:17 flannel
-rwxr-x--- 1 8119 5000 3863224 Jan 28 21:17 host-local
-rwxr-x--- 1 8119 5000 4256816 Jan 28 21:17 ipvlan
-rwxr-x--- 1 8119 5000 4256872 Jan 28 21:17 macvlan
-rwxr-x--- 1 8119 5000 4821840 Jan 28 21:17 ptp
root@e2e-test-mixia-minion-suyg:/opt/cni/bin# ./bridge 
bash: ./bridge: No such file or directory
```

**Comment by yifan-gu** [comment]
cc @dcbw @kubernetes/sig-network

**Comment by bprashanth** [comment]
I'm guessing this is a shared lib problem, since /usr/grte/v4/lib64/ld-linux-x86-64.so.2 doesn't exist on my gce vm. We should update docs to make it clear how someone would install manually (if they run into such problems again) and statically link (if the problem is indeed the shared lib) with something like  `CGO_ENABLED=0 GOOS=linux godep go install ...`

Unsure how we'd support different GOOS (vend different tarballs vs checking in and building the plugin inline with our make scripts)

**Comment by thockin** [comment]
uggh.  These binaries need to be ultra-static or else we need to containerize them.

**Comment by bprashanth** [comment]
Essentially doing https://github.com/appc/cni/issues/85 would've prevented this bug :)

**Comment by tomdee** [comment]
And see https://github.com/appc/cni/issues/126 for the CNI_ARGS problems

**Comment by errordeveloper** [comment]
@tomdee also #23049, re `CNI_ARGS`... however I'm not too sure if your comment was mean to be on this ticket.

**Comment by philips** [comment]
cc @steevej @jonboulle

**Comment by philips** [comment]
cc @steveej @jonboulle

**Comment by freehan** [comment]
I have a working version. I uploaded my cni binary with bug fix on GCS. 

[Here](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/cni/init.sls#L15) change source to `https://storage.googleapis.com/cni_plugins/cni.tar.gz `
[Here](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/cni/init.sls#L17) change source_hash to `md5=6f16c11b4bf662ecb05d59d925602c24`

Welcome to give it a try.

**Comment by freehan** [comment]
ref: https://github.com/appc/cni/issues/163
