### ISSUE TITLE
NodeProblem API

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#23028]
We should introduce NodeProblem to Kubernetes Node API, so that different daemons on the node can report machine health issues to the control-plane through Kubelet. The machine health issues include bad cpu, bad memory, kernel deadlock, corrupted filesystems, etc. Once the control-plane has the visibility to those issues, we can discuss the remedy system.

**Comment by gmarek** [comment]
+1 - I'd like to be kept up to date with this effort.

**Comment by liggitt** [comment]
as we build integrations to the node api from other components, don't forget the potential need for things using the kubelet API to be able to provide auth (client cert or bearer token, etc).

**Comment by alex-mohr** [comment]
FWIW, looks like on GCE that nodes can report as healthy even if the route controller has not yet fully programmed their route into GCE's network.  Unsure if that warrants a separate issue or should be solved control-plane side by unioning node-reported readiness with environment-of-node-readiness?

**Comment by gmarek** [comment]
@alex-mohr - IUUC this is an ubrella issue for v1.3 feature. GCE route thingy is a bug that we need to fix sooner. I filed #23327

**Comment by mikedanese** [comment]
@klizhentas

**Comment by Random-Liu** [comment]
Ref #23028

**Comment by dchen1107** [comment]
We already have Event, NodeCondition today to report some issues on the node. Also a Taint API object is proposed and under reviewed. I don't want to introduce another API object blindly here. Instead of we should consolidate those objects or have a clear definition for each of them. 

@Random-Liu and I had API related discussion with @bgrant0607 and @davidopp. We settled down with:
* No new API object is introduced for now.
* NodeProblemDetector (newly introduced daemon here) will use either Event or NodeCondition to carry a node problem. Most likely a triansient problem will be reported as an event, and a permanent problem as a condition, like what we are having today for out-of-resource (memory and disk).
* In a long term, scheduler is going to only check against taints, not conditions at all. A separate controller will be introduced to the ecosystem to convert the problem related events and conditions to taints. But this is out of the scope of 1.3 release.

@Random-Liu and I had several design discussion today. Here is the current plan for 1.3 release
* We are going to have a very simply and dump NodeProblemDetector implemention as a reference implementation. 
* The detector will run as a separate daemon on the node.
* The daemon will only detect the issues from kernel log. :-) 
* The daemon will use watch API to propagate problem events or conditions to upstream layers. We initially had some concern with API server's scalability since this design is introduced another watcher channel per node. After talking to @lavalamp we think it is acceptable for 1.3 release. 
* In a long term, there might be more problem daemons introduced to the node to detect different failures on a node (for example, hardware failures, etc.), then API server's scalability might become to the real problem. We will reconsider the architecture of the problem reporting pipeline. But that is the implementation detail for the users. We have several alternative proposals to address the issue already. 

@Random-Liu is working on the detail design for this. Thanks!

**Comment by dchen1107** [comment]
cc/ @jlowdermilk for our later discussion on GKE node health tracking.

**Comment by davidopp** [comment]
> The daemon will use watch API to propagate problem events or conditions to upstream layers.

What is the daemon watching? It sounds like the daemon is write-only.

BTW an advantage of NodeCondition over Event is that NodeCondition can be piggybacked on existing NodeStatus updates (though of course it makes the NodeStatus object larger). But anyway, I agree events is reasonable if you are essentially just proxying kernel log messages.

**Comment by Random-Liu** [comment]
@davidopp To update the NodeStatus, the daemon needs to know the newest NodeStatus. But of course, a simple `Get` before update should also works. :)

**Comment by davidopp** [comment]
I am not suggesting to use NodeStatus here, I just wanted to mention it.

**Comment by Random-Liu** [comment]
@davidopp Updated the comment above to make it less ambiguous.

**Comment by gmarek** [comment]
Events as `api.Events`? I thought that those are for human consumption only. cc @bgrant0607

**Comment by zmerlynn** [comment]
Is this landing for v1.3? I was assuming it as a solution for #24295, but if that's not the case, that bug will need a different mitigation.

**Comment by Random-Liu** [comment]
@zmerlynn The node-problem-detector will only monitors kernel log for 1.3. But it is extensible and will support more node problem in the future.
Is there any symptom in the kernel log for #24295?

**Comment by zmerlynn** [comment]
Nope. And yeah, that log is all over the place for basically any running container.

**Comment by dchen1107** [comment]
re #24295, I updated it at https://github.com/kubernetes/kubernetes/issues/24295#issuecomment-218597689 That issue shouldn't be handled by node problem detector.

**Comment by Random-Liu** [comment]
FYI, the first version of node problem detector is ready for review https://github.com/kubernetes/node-problem-detector/pull/1

**Comment by davidopp** [comment]
Since kubernetes/node-problem-detector#1 has been merged, can we remove v1.3 milestone?

**Comment by davidopp** [comment]
ping

**Comment by Random-Liu** [comment]
@davidopp This is almost done, only several things left:
1) E2e test for node problem detector: https://github.com/kubernetes/kubernetes/pull/26648
2) Temporary hack for unsupported OS distros like GCI: https://github.com/kubernetes/node-problem-detector/pull/13
3) Re-enable node problem detector in the cluster, we temporarily disable it because of https://github.com/kubernetes/node-problem-detector/issues/9.
4) Document for node problem detector: https://github.com/kubernetes/node-problem-detector/issues/4, https://github.com/kubernetes/node-problem-detector/issues/5

The PRs of 1) and 2) are under review and 3) and 4) will be sent out soon. And 4) should not be blocker for this issue. :)

**Comment by dchen1107** [comment]
I removed the control-plane team label since this one only covers node level change to make the problem visible to the upstream layers. There is no remedy controller built for 1.3 release.

**Comment by Random-Liu** [comment]
@dchen1107 All things are done. Can we close this one?

**Comment by matchstick** [comment]
Closing as we scrub bugs for 1.3. If it needs to be re-opened please do so for next-candidate.

**Comment by pwittrock** [comment]
@Random-Liu   
@dchen1107  

Would you provide an update on the status for the documentation for this feature as well as add any PRs as they are created?

Not Started / In Progress / In Review / Done

Expected Merge Time

Thanks
@pwittrock

**Comment by Random-Liu** [comment]
@pwittrock I have documentation for this feature, but I don't know whether or where we should put them in kubernetes.io.

**Comment by Random-Liu** [comment]
@pwittrock @dchen1107 The document is In Review now: https://github.com/kubernetes/kubernetes.github.io/pull/696.

**Comment by Random-Liu** [comment]
@pwittrock Doc Status Upgrade: The doc is Done now. :)
