### ISSUE TITLE
Standardize jenkins' job names for release branches

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#23021]
Can I request that we standardize on a naming convention for jobs on Jenkins?
I have some tooling that is scraping data from Jenkins, but we have different naming conventions for jobs between branches. Some jobs use the -N.N suffix and some use the -release-N.N suffix.

kubernetes-test-go
kubernetes-test-go-release-1.1
kubernetes-test-go-release-1.2

kubernetes-e2e-gke-serial
kubernetes-e2e-gke-serial-1.1
kubernetes-e2e-gke-serial-release-1.2

kubernetes-build
kubernetes-build-1.1
kubernetes-build-1.2

**Comment by spxtr** [comment]
@david-mcmahon do you prefer `-release-1.x` or `-1.x`? Both will require about the same number of changes.

**Comment by david-mcmahon** [comment]
No preference.  Whatever works best/easiest for infra.
