### ISSUE TITLE
kube-apiserver service endpoints got flushed after restart controller-manager

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#23034]
This is a race condition issue for controller-manager especially when we use VIP to connect apiserver for both controller-manager and kube-proxy.
1. During controller-manager restart, an endpoints controller loop will started which responsible for service endpoints sync;
2. Two list-watch thread started which list-watch changes for services and pods;
3. The service list-watch will put changed service into a queue compared with its local cache `serviceStore`;
4. The pod list-watch will load pods from apiserver and store them into its local cache `podStore`;
5. A worker will dequeue a service and try to get all its pods from `podStore` and build endpoints based on this.
6. If the worker find current endpoints is different with original one, it will do service endpoints update to apiserver.

Problem found on step 4:
During restart, usually, service list is faster than pod list, so the worker get `kube-apiserver` service from the queue and try to get its pods from `podStore`. While, at that time, pod list-watch is not complete and the worker got empty pods.
Then, endpoints controller update the `kube-apiserver` endpoints to be empty.
Then, kube-proxy got this change and update its forwarding rule. But iptables still exists which dnat VIP to kube-proxy.
After above, both controller-manager and kube-proxy could not connect to apiserver anymore.

And there is no way for them to be automatically recovered.

**Comment by zhouhaibing089** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L136

Would it help by change this time longer?

**Comment by xinxiaogang** [comment]
@zhouhaibing089 I think to make the logic strong, call apiserver after failing to get pod from cache would be better. But your recommendation would also an alternative.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
