### ISSUE TITLE
Errors in second density test runs

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#23036]
When running Density test second time on the same cluster I'm seeing errors like:

```
E0316 09:56:45.788713   12132 iowatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
```

cc @wojtek-t @kubernetes/sig-api-machinery

**Comment by fejta** [comment]
I'm removing the test-infra label because I don't understand how this is related to the infrastructure at this point.

**Comment by lavalamp** [comment]
This is not a very good bug report. Is this reproducible? What component is this even in?

**Comment by gmarek** [comment]
It's a line that appears it test, sorry for not being more clear about it. So it's either the test that does something wrong, or API server.

And yes - it is (was a week ago) reproducable by running density test few times on the same cluster.

**Comment by lavalamp** [comment]
Does this cause the test to fail?

**Comment by gmarek** [comment]
Not reliably.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
