### ISSUE TITLE
UXP: generic volume error - 'unsupported volume type' should be reworded

### ISSUE THREAD

**Issue by screeley44** [kubernetes/kubernetes#23048]
in volumes.go there is a generic error variable defined that is used when a failure occurs and no other error is surfaced, it is a catch-all when something goes wrong.

```
var errUnsupportedVolumeType = fmt.Errorf("unsupported volume type")
```

Think this should be reworded to something that is more reflective of the true issue and not so confusing for users.  This error mostly comes when a builder can not be created and it is typically not true that the volume type is unsupported, but rather some other underlying issue, such as missing secrets or endpoints or etc...

propose something like:

```
"failed volume mount, check previous pod describe events or logs for more details"  
```

or

```
"volume mount error - make sure the volume type is supported and also check previous pod describe events or logs for a more accurate root cause explanation"
```

**Comment by jayunit100** [comment]
@screeley44 are you working on this?

**Comment by screeley44** [comment]
@jayunit100 - yes, I would like to submit the PR for this
