### ISSUE TITLE
CNI_ARGS are not valid

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#23049]
This might belong to CNI code, but failing it here to understand if I might be missing something.

We are currently calling CNI plugins with `CNI_ARGS` set to something like:
```
K8S_POD_NAMESPACE=default;K8S_POD_NAME=frontend-k96d0;K8S_POD_INFRA_CONTAINER_ID=7769635de7cdb37c2d602524aac6a8505a74aed1b464063db9dee58438fe152f
```
But the CNI code doesn't accept these keys, so I am really not sure how was this supposed to work...

**Comment by errordeveloper** [comment]
cc @dcbw @rajatchopra @bprashanth

**Comment by errordeveloper** [comment]
The error event looks like this:
```
2016-03-16 09:24:57 +0000 UTC   2016-03-16 09:26:36 +0000 UTC   41        redis-master-9wkyg   Pod                 Warning   FailedSync   {kubelet kubedev}   Error syncing pod, skipping: failed to "SetupNetwork" for "redis-master-9wkyg_default" with SetupNetworkError: "Failed to setup network for pod \"redis-master-9wkyg_default(e10c3705-eb58-11e5-a8ce-0242ac110004)\" using network plugins \"cni\": ARGS: invalid key \"K8S_POD_NAMESPACE\"; Skipping pod"
```

**Comment by bprashanth** [comment]
Yep, I swear we have a bug for this but maybe I forgot to file one, just ignore the extra args in your wrapper plugin if that's possible :)

Honestly I don't think the CNI plugins should barf if they're passed unknown env vargs. They should log a warning. I also don't think we should be passing custom env vars, given that they *do* barf.

I also don't like piling information down the one exec operation by passing more and more env vars, but that's a bigger problem.

**Comment by freehan** [comment]
Here is the issue: https://github.com/appc/cni/issues/126

**Comment by errordeveloper** [comment]
Closing, as this needs to be fixed in the CNI.
