### ISSUE TITLE
[Bug] When "KUBE_MAX_PD_VOLS" > DefaultMax should use DefaultMax

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#23041]
When KUBE_MAX_PD_VOLS > DefaultMax, should use DefaultMax
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithmprovider/defaults/defaults.go#L39-L51

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by AdoHe** [comment]
@mdshuai this should be a bug, have open a PR #23054

**Comment by DirectXMan12** [comment]
I'm not convinced that this is undesired behavior: https://github.com/kubernetes/kubernetes/pull/23054#issuecomment-197389156

**Comment by jayunit100** [comment]
By definition KUBE_MAX_PD_BOLS is clearly overriding the defaultVal.  So I vote to close this issue.

**Comment by AdoHe** [comment]
I agree that we can close this issue.

**Comment by mdshuai** [comment]
Thanks the comment
