### ISSUE TITLE
Alert someone when kubernetes-test-history stops running, and add report date

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#23062]
The software that generates http://storage.googleapis.com/kubernetes-test-history/static/tests-e2e.html has crashed/stopped running a few times, and nobody knew.  Please add an alert.

Also, the above report does not indicate what date the report pertains to, which makes it very confusing, and difficult to tell whether the report is up to date (e.g. I looked today, and it was a week old, although this was entirely non-obvious).

**Comment by spxtr** [comment]
http://storage.googleapis.com/kubernetes-test-history/static/index.html

That shows the date that it started, which is one day after the date it covers. That's not ideal. It's on my plate to improve this.

**Comment by quinton-hoole** [comment]
Aah - fair enough.  I always use the direct link, so I didn't see that index page at all.

**Comment by spxtr** [comment]
Oh, looks like I get an email when this breaks, I just filter it out XD

I'll stop that, so at least I'll know if it's broken.
