### ISSUE TITLE
Consider publishing the service account public key somewhere

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#23064]
See: https://github.com/openshift/origin/issues/7973#issuecomment-197415222

It may be useful to expose this key in the API as a mechanism for verifying with the key in systems like OpenShift.

Presently to deploy OpenShift I have to SSH into the kubernetes master and grab the service account private key. [My efforts](http://github.com/paralin/openshift-under-kubernetes) towards deploying without touching ssh, or anything but the API.

I'm looking for another API-only workaround for fetching this file.

**Comment by simonswine** [comment]
I am quite interested in that. As far as I am aware there is no way to get those public keys in many hosted kubernetes environments (EKS, GKE, ...), certainly not in an unified way. I think it would be really useful to expose that on the apiserver.

/reopen
/remove-lifecycle stale
/sig auth

**Comment by liggitt** [comment]
key publishing is proposed in https://github.com/kubernetes/community/pull/2314

**Comment by liggitt** [comment]
will track via the linked proposal

/close
