### ISSUE TITLE
Track features that needs to be a part of release notes

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#23070]
Currently, PRs having `release-note` label is automatically included as part of the release notes. This process does not work for big features though.
We need to track issues that represent features as well and include a gist from those issues in the release notes.

**Comment by bgrant0607** [comment]
From email to kubernetes-dev:

One thing that was clear is that most people didn't know what should go into the release notes. In a number of cases, I had to ask specific people to add specific items to specific sections. The only way I could do that is I knew what was in the release and how the release notes should be organized.

We need a template for release notes, guidelines for what belongs in release notes, and an example set of release notes (1.2.0).

We also need to capture items that belong in release notes before the PRs merge.

David M. has a proposal to automate release-note collection. We need to extend it with the categories we've created and require every PR assign a category (including something like release-note/none-minor-fix) before being merged by the submit queue. PRs that belong in the release notes will need to have extractable release note text in their PR descriptions.

Writing release notes should be added to the documented developer workflow.

**Comment by david-mcmahon** [comment]
For now the workaround here is to ensure that the first PR that enables a feature contain the appropriate `release-note-*` label.  https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/release-notes.md#caveats--considerations

**Comment by david-mcmahon** [comment]
Closing.  Moved to release repo.
