### ISSUE TITLE
kubelet: Allow kubelet to contact apiserver in runonce mode

### ISSUE THREAD

**Issue by derekparker** [kubernetes/kubernetes#23073]
Currently kubelet is limited to on-disk pod manifests and anything received from `--manifest-url` when in runonce mode.

**Comment by mikedanese** [comment]
cc @dchen1107 @vishh

**Comment by vishh** [comment]
Can you describe the use case @derekparker ?

**Comment by derekparker** [comment]
@vishh definitely.

So, one of the biggest improvements that allowing a runonce kubelet to register with an apiserver provides is the ability to write higher level kubernetes objects into the apiserver (think daemonsets for example). Currently, all runonce modes simply assume static pod manifests live somewhere, but this can be limiting in certain situations.

Specifically, imagine you had a `kubelet` daemonset. This patch open up the ability for an external loop (think bash, systemd, etc) to run the kubelet in runonce mode, talking to an apiserver, until it runs that kubelet. Additionally, that same external loop could, for instance, be used to ensure that a kubelet is always running on the system (by invoking the kubelet in runonce mode again as described above).

**Comment by dchen1107** [comment]
> ability to write higher level kubernetes objects into the apiserver (think daemonsets for example)
@derekparker  I am having difficulty to understand what you you mean above. I  guess you are referring to "read higher level kubernetes objects from the apiserver". If my understanding is right, what you described here does make sense to me.

**Comment by derekparker** [comment]
@dchen1107 exactly, sorry for the confusing wording!

**Comment by vishh** [comment]
@derekparker: To summarize,

Goal is to get kubelet to run as pods and make upgrades/downgrades easier.
This PR proposes adding a functionality to kubelet that will make it run only a specific kind of pod (details TBD) and then exit?

**Comment by derekparker** [comment]
@vishh 

> Goal is to get kubelet to run as pods and make upgrades/downgrades easier.

Correct, that is the ultimate motivation for this feature.

> This PR proposes adding a functionality to kubelet that will make it run only a specific kind of pod (details TBD) and then exit?

This PR does not restrict the kind of pod a kubelet will run, that is handled externally. As opposed to my initial patch (`--bootstrap-pod-label` flag) this feature is more general than just using a kubelet to run a kubelet (or any specific pod), but that is certainly our motivation.

This PR only proposes allowing the kubelet to contact apiserver, run a single pod, and then exit.

**Comment by mikedanese** [comment]
> contact apiserver, run a single pod, and then exit

Why can't it do a single list and run all assigned pods?

**Comment by derekparker** [comment]
> Why can't it do a single list and run all currently assigned pods?

By default it will, only problem is pods will only be assigned to that node once it registers. So:

1) Kubelet registers
2) Kubelet does a "list" against apiserver (this is already default code path, list then watch)
3) Kubelet has only just registered, nothing has been scheduled to it, so it gets nothing from the list
4) Pod is then scheduled to Kubelet, and is picked up by the Kubelet via the watch
5) Kubelet runs that pod and exits.

I would certainly like to discuss the possibility of a "drain" behavior, if it's possible.

**Comment by vishh** [comment]
@mikedanese and I chatted offline about this feature and came up with an alternative. Here is the summary:

Implementation goals are to have the primary kubelet run until a secondary kubelet is ready to take over and rerun the primary kubelet whenever the secondary kubelet exits.
The primary and secondary kubelet synchronize using a file lock.
A bootstrapping controller will be created to coordinate node bootstrapping. 

1. The primary kubelet will come up and register themselves with a `misconfigured` taint.
2. The bootstrapping controller will then spawn a secondary kubelet on each node, which will not register itself until it can take over the file lock.
3. The bootstrapping controller will then explicitly instruct the primary kubelet to hibernate (or exit), using the API (details TBD). The primary kubelet can either exit and be expected to be started by an external entity, or can enter a hibernation mode where it can inotify on the lock file and shut down all its operations. 
4. The secondary kubelet will then register itself appropriately, without the `misconfigured` taint.

Another _alternative_ is to make the primary kubelet inotify on the lock file by default and enter the hibernation mode (or exit) whenever it notices another process attempting to access the lock file.

**Comment by derekwaynecarr** [comment]
I feel like I just read Inception... a little more flow on how the upgrade/downgrade process is envisioned would help to give some more context here.  I am still trying to work out which kubelet listens on what ports, etc.

**Comment by vishh** [comment]
@derekwaynecarr :) The goal is to make kubelet upgrades seamless. A solution for that is to self-host which is what this issue is talking about.
One primary assumption is that of not running more than one fully functional kubelet at the same time.

**Comment by vishh** [comment]
@derekparker: As I mentioned earlier, a formal proposal will definitely help here. The proposal can serve as a design doc once it is implemented. So its worth the effort.

**Comment by derekwaynecarr** [comment]
@vishh - I am wondering who launches the primary kubelet and who babysits the kubelet in a pod when the primary kubelet shuts down?  the launching container runtime?

**Comment by vishh** [comment]
@derekwaynecarr: The turtle at the bottom is systemd or upstart or some other init.
The secondary kubelet is partly managed by the container runtime.

**Comment by derekwaynecarr** [comment]
@vishh - so the bottom turtle is something like `kubelet.service` that has been enabled to start on-boot via `systemd`, but whose unit `Restart=` is set to something like 'on-failure'.  That primary kubelet probably had `--cgroup-parent` flag that was set so it launches the secondary kubelet somewhere appropriate.  That primary `kubelet` launches the secondary `kubelet` as a pod using the container runtime and then exits.   That secondary `kubelet` is now running with a different `--cgroup-parent` setup than the original `kubelet` so it separates its end-user pods from itself appropriately... I am trying to reconcile this with the systemd node spec, and how things like node allocatable and its enforcement would work when bootstrapping this way.  It's also late on a Friday and I am officially too tired to think this through, but it seems important.

**Comment by derekparker** [comment]
@vishh thanks for the response.

I really like the idea of using taints/tolerations, and we had discussed that before when @mikedanese came out to the CoreOS office, but it feels like we can achieve the same goal without adding new concepts, just simply using slightly modified versions of what already exists. In other words, instead of introducing a bootstrapping controller that knows how to tell the primary kubelet to spawn another kubelet, and knows how to tell that kubelet to exit, why not just use the existing `runonce` semantics? My justification there is, regardless of either approach we need something external to make sure that _a_ kubelet is running (whether bootstrap or managed) on the host.

So essentially, this looks like:

1) Primary kubelet comes up in runonce mode with the file lock and the `misconfigured` taint.
2) Kubelet daemonset (or w/e higher level kubernetes object) already exists in etcd with a toleration to that taint
3) Kubelet can (more or less) deterministically pull down and run that kubelet due to taint/tolerations
4) Due to runonce semantics, bootstrap kubelet automatically exits
5) Managed kubelet acquires lock, takes over
6) Outer loop sees kubelet is running, does nothing

In my opinion this offers the least amount of change and special casing in the system in order to do this initial pivot, and introduces a minimal amount of new concepts (specifically no new concepts that are bootstrap specific, everything can be generalized).

@vishh additionally, I am definitely open to a formal proposal if that would make things easier. Would it make sense to start on a formal proposal using the above concepts?

**Comment by derekwaynecarr** [comment]
@derekparker - I am interested in a proposal, but I am also most concerned on the impact it has to the cgroup topology and ability to enforce node allocatable so we can keep a hierarchy that looks something like this at the end of the day:

https://github.com/kubernetes/kubernetes/pull/17688/files#diff-2d458913eb3f03bfd7f4b1fddb0e043cR305

**Comment by vishh** [comment]
> 4) Due to runonce semantics, bootstrap kubelet automatically exits

What does runonce mean? It might be incorrect to assume that the kubelet
daemon set already exists on the API server.

If we had an external controller, the actions we perform will be explicit
and hence less magic added to each component/layer.

+1 for considering and including how all the shared state will be handled
during the handover.

**Comment by derekparker** [comment]
> What does runonce mean? It might be incorrect to assume that the kubelet
daemon set already exists on the API server.

In this case it means literally starting the kubelet with the `--runonce` flag (via systemd or some other system mechanism), and allowing it to contact an API server, run a pod and exit. Also, at some point there must be a seeding process to get the control/worker manifests stored somewhere, whether that's the apiserver/etcd or this new bootstrap controller. The user will need to control those manifests and input them in some way so that they can properly configure their components. So, with that in mind, it doesn't seem like a big jump to assume that we can provide a mechanism (currently we're looking into a "monokube" type route in a single binary) for a thin bootstrap control plane that can read in manifests, ensure they are sent to the apiserver, and can be scheduled to kubelets.

> If we had an external controller, the actions we perform will be explicit
and hence less magic added to each component/layer.

I guess I'm still not fully understanding the need for a bootstrap controller. All we're trying to do is deploy apps (in this case the control plane / node procs), which Kubernetes can already do. And we want to describe these components using kubernetes objects, which the apiserver already understands.

I will go ahead and submit a formal proposal of our current goals/understandings of this initial bootstrap and what that process looks like. This is all great feedback, and I think having a single proposal, and a single place to consolidate all this discussion is going to be very beneficial for moving this work forward.

**Comment by derekparker** [comment]
@vishh as an amendment to my comment, I suppose all configuration would not have to happen in the manifests, as we could provide "stock" manifests without configuration, and use a configMap to configure the components separately.
