### ISSUE TITLE
Document adoption FAQs

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#23085]
Common questions about people wanted to adopt K8s/Docker/Rkt that we should document as FAQs:
1. What graph driver / filesystem do we recommend for distro Foo X.Y? Or how should we choose?
2. What networking solution would you recommend for cloudprovider Bar? Or how should we choose?
3. What network-attached storage system would you recommend? Or how should we choose?
4. We need to do X (e.g., mount over /etc/hosts) before running our app. That gets blown away upon every container restart. Is there a recommended init/setup solution? Or how should we choose?
5. What's the recommended solution for the "pid 1" problem? Or how should we choose?
6. How to you recommend we build our containers? Or how should we choose?
7. Do you have a way to squash container layers?
8. How should we choose between Docker and Rkt?

I'm sure there are others.

cc @thockin @davidopp @dchen1107 @smarterclayton

**Comment by vishh** [comment]
> What graph driver / filesystem do we recommend for distro Foo X.Y? Or how should we choose?

We (Google) don't test against multiple graph drivers. We test only against `Aufs`. More information on graph drivers [here](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/).

> What's the recommended solution for the "pid 1" problem? Or how should we choose?

https://github.com/Yelp/dumb-init

**Comment by bprashanth** [comment]
> What networking solution would you recommend for cloudprovider Bar? Or how should we choose?

IMO Kubernetes should have a default networking solution that works cross-cloudprovider. We should strive to document the shortcoming of using this default option, if any, but it should *just work* if they don't care about specifics. 

Currently this should be true for:
```
$ NETWORK_PROVIDER=flannel ./cluster/kube-up.sh
```

Or if it isn't, I'd consider it a bug that needs investigation (because I haven't tried on DO etc). 

>What's the recommended solution for the "pid 1" problem? Or how should we choose?

There are several solutions like the one Vish mentioned and dinit (https://github.com/miekg/dinit), we should say this IMO, instead of blessing one (this comment is at odds with my networking comment, but I think they're problems with diffrent levels of complexity).

**Comment by mikedanese** [comment]
> What's the recommended solution for the "pid 1" problem? Or how should we choose?

There seems to be a lot of hubbub over this. Is the only issue zombies? `while(;;) wait();` works pretty well.

**Comment by bprashanth** [comment]
I think it's a request from people who want to start multiple daemons in a container (i.e vms), it's convenient to have something handle sigterm and gracefully turn down the other daemons, just like init is notified of a reboot

**Comment by bprashanth** [comment]
i.e https://github.com/phusion/baseimage-docker#whats_inside

**Comment by bgrant0607** [comment]
I don't think we want to recommend Phusion. Container-as-VM is the wrong model.

**Comment by IanLewis** [comment]
> Do you have a way to squash container layers?

https://github.com/jwilder/docker-squash

**Comment by bprashanth** [comment]
> I don't think we want to recommend Phusion. Container-as-VM is the wrong model.

I was justifying the request not advocating the solution. 
We should call this out in the FAQ.

**Comment by derekwaynecarr** [comment]
@mikedanese - you may find this interesting:

http://blog.dscpl.com.au/2015/12/issues-with-running-as-pid-1-in-docker.html?m=1

It's a good write up on challenges we had with Python and educated me a lot.

**Comment by bgrant0607** [comment]
cc @kubernetes/docs

**Comment by bgrant0607** [comment]
cc @viglesiasce

**Comment by bgrant0607** [comment]
These issues are up to providers
