### ISSUE TITLE
api-ref docs: Generate an index for operations.html

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#23081]
We generate an index for definitions.html. We should do the same for operations.html as well

Ex: https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/HEAD/docs/api-reference/autoscaling/v1/definitions.html
https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/HEAD/docs/api-reference/batch/v1/operations.html

@kubernetes/docs @caesarxuchao @bgrant0607

**Comment by nikhiljindal** [comment]
Actually the index in definitions.html does not look correct.
https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/HEAD/docs/api-reference/autoscaling/v1/definitions.html shows only 2 items in index, even tough the doc has many definitions.

@caesarxuchao any idea why is this happening?

**Comment by caesarxuchao** [comment]
> Actually the index in definitions.html does not look correct.

It's as expected. The index only shows the top-level objects.

**Comment by bgrant0607** [comment]
We're generating API docs differently now
