### ISSUE TITLE
Incorrect annotation copied from deployment to RS after rolling back

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#23087]
Scenario:
1) Create a deployment d and record it. Change cause: d = "create", rs1 (v1) = "create" (copied from d). 
```console
$ kubectl create -f docs/user-guide/nginx-deployment.yaml --record
deployment "nginx-deployment" created
$ kubectl rollout history deployment
deployments "nginx-deployment":
REVISION	CHANGE-CAUSE
1		    kubectl create -f docs/user-guide/nginx-deployment.yaml --record
```
2) Update d with apply. Change cause: d = "apply", rs2 (v2) = "apply" (copied from d)
```console
$ kubectl apply -f docs/user-guide/new-nginx-deployment.yaml
deployment "nginx-deployment" configured
$ kubectl rollout history deployment 
deployments "nginx-deployment":
REVISION	CHANGE-CAUSE
1		    kubectl create -f docs/user-guide/nginx-deployment.yaml --record
2		    kubectl apply -f docs/user-guide/new-nginx-deployment.yaml
```
3) Rollback d. Change cause: d = "apply" (unchanged since we don't record command in `kubectl rollout undo`), rs1 (v3) = "apply" (copied from d). However, **it should be either "create" or "rollout undo"** (depending on how we want to implement it). This confuses users. 
```console
$ kubectl rollout undo deployment 
deployment "nginx-deployment" rolled back
$ kubectl rollout history deployment 
deployments "nginx-deployment":
REVISION	CHANGE-CAUSE
2		    kubectl apply -f docs/user-guide/new-nginx-deployment.yaml
3		    kubectl apply -f docs/user-guide/new-nginx-deployment.yaml
```

@bgrant0607 @kargakis @kubernetes/sig-config @kubernetes/kubectl

**Comment by janetkuo** [comment]
Other annotations (except for revision and apply) will also be copied from deployments to RSes after rolling back, and will have the same problem.

**Comment by bgrant0607** [comment]
I'd prefer to record `undo`.

**Comment by janetkuo** [comment]
> I'd prefer to record `undo`.

Recording undo/pause/resume is implemented in #23088.

**Comment by janetkuo** [comment]
After in-person discussion with @bgrant0607, we decided not to record `kubectl rollout` commands at all. It's intentional because `kubectl rollout pause/resume` doesn't really change the rollout (revision doesn't change), and recording `kubectl rollout undo` is less meaningful than the original change-cause (such as create/apply/edit...etc.) 

I'll just fix the bug that the annotation is copied from deployment to RS after rollback (should be the other way around).

**Comment by janetkuo** [comment]
We should document that we don't record `kubectl rollout` as well.
