### ISSUE TITLE
Local docker cluster on mac cannot create service with "External-IP"

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#23093]
I tried doing the wordpress example on my mac using the local docker cluster.  When I create the service, it does not assign an "EXTERNAL-IP", only a "CLUSTER-IP".

It would be great if the local dev k8s supported our examples (minus GCE specific stuff such as PVCs).

**Comment by paralin** [comment]
I think this isn't possible in the same way Vagrant LoadBalancers aren't possible because you can't allocate a ip address outside a cloud provider.

I suppose you might be saying the examples need to be changed to make this more clear?

**Comment by bgrant0607** [comment]
This is also true for many cloud providers.

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by bgrant0607** [comment]
We should have examples that demonstrate various approaches to external access:

* type=LoadBalancer
* type=NodePort
* Ingress
* apiserver proxy (for debug/admin purposes, not actual user traffic)

**Comment by derekwaynecarr** [comment]
It would help if we had a way to detect if a cluster supported
type=LoadBalancer

**Comment by paralin** [comment]
@derekwaynecarr Exactly why I made the issue #22871
