### ISSUE TITLE
Getting started: "Running Kubernetes Locally via Docker" doesn't work on Max OS X

### ISSUE THREAD

**Issue by juretta** [kubernetes/kubernetes#23092]
## Problem description

The "**Download kubectl**" section mentions the following:

> Create configuration:
> 
> ```
> $ kubectl config set-cluster test-doc --server=http://localhost:8080
> $ kubectl config set-context test-doc --cluster=test-doc
> $ kubectl config use-context test-doc
> ```
> 
> For Max OS X users instead of localhost you will have to use IP address of your docker machine, which you can find by running docker-machine env <machinename> (see documentation for details).

The `docker run` command doesn't publish any ports though, so the above does not work even if `localhost` is replaced with the correct IP address of the docker machine.

`kubectl get nodes` will then fail with:

```
The connection to the server 192.168.99.100:8080 was refused - did you specify the right host or port?
```

_Note: `192.168.99.100` is the IP of the docker machine that I configured as described_
## Hypothesis

It looks like the API server (?) port `8080` needs to be published.
## Workaround

A workaround is to keep using `localhost` in the configuration line above and to then set up an SSH tunnel:

```
docker-machine ssh $MACHINE_NAME -N -L 8080:localhost:8080
```

(where `$MACHINE_NAME` is the name of the docker machine being used, `docker-machine ls` can be used to list all running machines).

This is sufficient to make `kubectl get nodes` work as described.

**Comment by ElielHaouzi** [comment]
Hi @juretta
Do you have any idea that when I try to establish the ssh tunnel I get "Incorect usage":

```
elielhaouzi@Eliels-MBP Applications $ docker-machine ssh default -N -L 8080:localhost:8080
Incorrect Usage.

Usage: docker-machine ssh [arg...]

Log into or run a command on a machine with SSH.

Description:
   Arguments are [machine-name] [command]
``` 

Thanks

**Comment by skeswa** [comment]
I just bumped into this today. Its really disappointing that I have to resort to a hack to make it work. Thanks for your post though.

**Comment by augieschwer** [comment]
Thank you! I thought I was going crazy. Bump.

**Comment by bprashanth** [comment]
@pwittrock

**Comment by pwittrock** [comment]
It may be possible to fix this by chaning `--insecure-bind-address=127.0.0.1` in master.json to `--insecure-bind-address=0.0.0.0` and rebuilding the image.  This may have security implications when running outside a vm.

**Comment by pwittrock** [comment]
Thinking more on this, I wouldn't actually use `--insecure-bind-address=0.0.0.0` since it is pretty dangerous to expose outside loopback and prefer the ssh tunnel solution.  The docs should be updated.

**Comment by apobbati** [comment]
How would I go about connecting to the secure port? Is that listening on 6443? Where are the certs kept?

**Comment by pwittrock** [comment]
@vishh Are you familiar with the steps for configuring some simple authentication for the localcluster?

**Comment by augieschwer** [comment]
Is it just me or is the

> kubectl expose deployment nginx --port=80

step wrong too?

My version of `kubectl` doesn't have an "deployment" type available to the "expose" sub-command.

`➜  ~ kubectl expose deployment nginx --port=80
Error from server: deployments.extensions "nginx" not found`

Whereas this works for me:

`➜  ~ kubectl expose rc nginx --port=80
service "nginx" exposed`

Just me?

`➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.7", GitCommit:"c0fd002fbb25d6a6cd8427d28b8ec78379c354a0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}`

**Comment by pwittrock** [comment]
@augieschwer The most recent version of `kubectl run` should now create a `deployment` instead of a `replication controller`.  I am not sure if this change made it into the v1.2.0-alpha.7 release.  `kubectl run` should now say `created deployment`.  Do you still see the same behavior when running the non-alpha client?

**Comment by augieschwer** [comment]
@pwittrock `v1.2.1-beta.0` seems to work as the documentation expects. Maybe the problem then is that the docs (http://kubernetes.io/docs/getting-started-guides/docker/) list `1.2.0-alpha.7` and the links in "Download kubectl" link to that version of `kubectl`. Thanks for the reply!

**Comment by pwittrock** [comment]
@augieschwer Thanks for pointing that out.  We need to update that page to correct the version as well as add the ssh tunnel command.  We have discussed some solutions to make bootstrapping a local environment more user friendly and are hoping to improve this experience.

@vishh Since you are planning on working on / coordinating this update, would you make sure all of the version are correct.  The docker image version should probably be changed to v1.2.0 as well.

**Comment by bgrant0607** [comment]
cc @vishh @dlorenc

**Comment by kant111** [comment]
For google this is not acceptable especially when they preach on how to build systems that can take care of all the internal plumbing with single command.

**Comment by onlydole** [comment]
@pwittrock This doesn't work on Docker for Mac. I keep setting the `The connection to the server localhost:8080 was refused - did you specify the right host or port?` message

**Comment by pwittrock** [comment]
> @pwittrock This doesn't work on Docker for Mac either. I keep setting the The connection to the server localhost:8080 was refused - did you specify the right host or port? message.

What version of docker + OSX are you using?

@dlorenc Are you able to reproduce / what other information do you need?

**Comment by pwittrock** [comment]
Due to the challenges around developing a good local kubernetes experience through docker / docker-machine, we are developing an alternative solution that we hope to release soon called [minikube](https://github.com/kubernetes/minikube).  We are hoping to replace the existing local solutions with minikube.  The solution is pretty far along, so I would recommend checking it out if you are having issues with the local-docker solution.

**Comment by pwittrock** [comment]
cc @dlorenc

@onlydole would you be willing to try https://github.com/kubernetes/minikube to see if it provides you what you need?  It hasn't been generally released yet, but it would be helpful to get your feedback.

**Comment by onlydole** [comment]
@pwittrock - I'd love to! I'll give that a go and make sure to give my feedback too...thank you so much!

**Comment by pwittrock** [comment]
@onlydole my pleasure

**Comment by dlorenc** [comment]
Docker for Mac has made quite a few changes to their networking model recently, but last I tried it didn't work at all for me. Maybe we should add something to the documentation mentioning that the local cluster in Docker setup doesn't work in Docker for Mac yet.

I can send a PR to the docs repo if no one has objections.

**Comment by pwittrock** [comment]
@dlorenc That would be great.  Go ahead and assign the review to me.

**Comment by yurifrl** [comment]
what i was missing was 'gcloud beta auth application-default login'

**Comment by spzala** [comment]
@juretta @pwittrock hi, since the issues was last discussed over a year ago, a gentle touch base if it's still valid or we can please close it? I noticed that  docs/getting-started-guides/docker.md now simply points to minikube, and installation minikube/kubectl as such using doc seems working fine on Mac. Thanks!

**Comment by 0x69676f72** [comment]
root@vagrant-ubuntu-trusty-64:~# kubectl expose rc nginx --port=80 service "nginx" exposed
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root@vagrant-ubuntu-trusty-64:~#
