### ISSUE TITLE
Documentation for DNS is outdated - template fails sed replacement

### ISSUE THREAD

**Issue by innovia** [kubernetes/kubernetes#23103]
the following document is broken
http://kubernetes.io/docs/getting-started-guides/docker-multinode/deployDNS/

the following template http://kubernetes.io/docs/getting-started-guides/docker-multinode/skydns.yaml.in

has {{pillar['var']}} replacements - sed could not replace them since they are saltstack replacements

the [other document on github](https://github.com/kubernetes/kubernetes/tree/release-1.2/cluster/addons/dns#how-do-i-test-if-it-is-working) tell you that

Second, you need to start the DNS server ReplicationController and Service. See the example files (ReplicationController and Service), but keep in mind that these are templated for Salt. You will need to replace the {{ <param> }} blocks with your own values for the config variables mentioned above. Other than the templating, these are normal kubernetes objects, and can be instantiated with kubectl create.

**Comment by bgrant0607** [comment]
cc @ArtfulCoder

**Comment by thockin** [comment]
Dup of  #25020
