### ISSUE TITLE
Make pod-with-node-affinity.yaml match the description in the documentation

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#23106]
http://kubernetes.io/docs/user-guide/node-selection/
says "This node affinity rule says the pod can only be placed on a node with a label whose key is kubernetes.io/e2e-az-name and whose value is either e2e-az1 or e2e-az2. In addition, among nodes that meet that criteria, nodes with a label whose key is foo and whose value is bar should be preferred."

But the example, which is at
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/node-selection/pod-with-node-affinity.yaml
(this used to be at
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/node-selection/pod-with-node-affinity.yaml
until we moved the docs, though temporarily there is still a copy in the old location)
does not show the second part ("In addition, among nodes that meet that criteria, nodes with a label whose key is foo and whose value is bar should be preferred.")

We should modify
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/node-selection/pod-with-node-affinity.yaml
and
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/node-selection/pod-with-node-affinity.yaml
so that they match the description. I think ti is good to show both "hard" and "soft" affinity in the example.

BTW due to #23105 we need to modify both copies of the example.

**Comment by bibryam** [comment]
It seems to me that the docs has been updated to match the example and this ticket can be closed.

**Comment by spiffxp** [comment]
/sig scheduling
because node selection

/assign
closing because the example at https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature matches the description, this has been fixed
