### ISSUE TITLE
doc issue

### ISSUE THREAD

**Issue by osallou** [kubernetes/kubernetes#23108]
in api.md there is a link to swagger-ui API view

http://kubernetes.io/third_party/swagger-ui/

link does not work

**Comment by bgrant0607** [comment]
cc @nikhiljindal

**Comment by nikhiljindal** [comment]
Yes, http://kubernetes.io/third_party/swagger-ui/ stopped working when we updated our site. Its tracked in: https://github.com/kubernetes/kubernetes.github.io/issues/112.

There is an open PR to change that link in api.md to point to api-ref docs instead of swagger-ui.
