### ISSUE TITLE
Unable to create Secrets as Environment Variables.

### ISSUE THREAD

**Issue by jadhavnitind** [kubernetes/kubernetes#23120]
Firstly tried create Secrets as Environment Variable in Pod as instructed on "http://kubernetes.io/docs/user-guide/secrets/" URL. But it is giving error like below 
<snip>
error validating "pod.yaml": error validating data: [field fieldRef: is required, found invalid field secretKeyRef for v1.EnvVarSource, field fieldRef: is required, found invalid field secretKeyRef for v1.EnvVarSource]; if you choose to ignore these errors, turn validation off with --validate=false
</snip>

I was trying to use it in ReplicationController. Tried to create ReplicationController using Secrets as Environment Variable but getting below error message.

<snip>
error validating "tomcatrc.yml": error validating data: [field fieldRef: is required, found invalid field secretKeyRef for v1.EnvVarSource, field fieldRef: is required, found invalid field secretKeyRef for v1.EnvVarSource]; if you choose to ignore these errors, turn validation off with --validate=false
</snip>

Found few stuffs on "https://github.com/pavlovml/match/blob/master/rc.yml" but getting same issue.

Kindly suggest on this.

**Comment by zhouhaibing089** [comment]
@jadhavnitind is this the thing you are talking about? https://github.com/zhouhaibing089/downward/blob/master/pod.json

**Comment by jadhavnitind** [comment]
Kubectl binaries are upto date.

**Comment by zhouhaibing089** [comment]
@jadhavnitind I am able to run `kubectl create -f rc.yml`, the file is from the link you pasted above: https://github.com/pavlovml/match/blob/master/rc.yml

**Comment by jadhavnitind** [comment]
Its strange. Please pass your current version of Kubectl.

**Comment by zhouhaibing089** [comment]
I do not use a download version, I am using the built one, so there is no meaning version, :)

Could you try to use the `kubectl` while you run a `./cluster/hack/build-go.sh`?

Anyway, it would be better to give the kubectl version you are using, so other guys could help to reproduce it and fix it.

**Comment by jadhavnitind** [comment]
root@# gcloud version
Google Cloud SDK 101.0.0
bq 2.0.24
bq-nix 2.0.18
core 2016.03.11
core-nix 2016.02.22
gcloud 
gsutil 4.17
gsutil-nix 4.16
kubectl 
kubectl-linux-x86_64 1.1.7

root@# kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}


root@# kubectl create -f tomcatrc.yml
error validating "tomcatrc.yml": error validating data: [field fieldRef: is required, found invalid field secretKeyRef for v1.EnvVarSource, field fieldRef: is require
d, found invalid field secretKeyRef for v1.EnvVarSource]; if you choose to ignore these errors, turn validation off with --validate=false

root@# cat tomcatrc.yml
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: testtomcat
spec:
  replicas: 2
  selector:
    app: testtomcat
  template:
    metadata:
      labels:
        app: testtomcat
    spec:
      containers:
      - name: testtomcat
        image: gcr.io/fluted-oasis-107921/tomcat:vcs6
        ports:
        - containerPort: 8080
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: vcs-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vcs-db-secret
              key: password

**Comment by zhouhaibing089** [comment]
@jadhavnitind it seems that you are using v1.1. and the feature you requested does not exist there, see the related code:

https://github.com/kubernetes/kubernetes/blob/release-1.1/pkg/api/v1/types.go#L793-L796

There is only `fieldRef`.

**Comment by pmorie** [comment]
@zhouhaibing089 is right (thanks a lot for responding on this issue).

This feature is available in 1.2.0, which is released today.

**Comment by pmorie** [comment]
@jadhavnitind, is it possible for you to try it out on 1.2?

**Comment by jadhavnitind** [comment]
Firstly I am using Kubernetes on Google Container Cluster. Its not on standalone instance or server.
So, I will have to use Kubectl to create any kind of resource using yaml/json file.
@pmorie I am not getting what version are you talking about?

**Comment by vincentheet** [comment]
You are using a feature which is only available in Kubernetes v1.2.0. and newer. Currently your GKE cluster has Kubernetes v1.1.x. So your GKE cluster needs an upgrade to the newest version of Kubernetes. But as you can see here Google only supports version 1.1.8 and 1.0.7 for now: https://cloud.google.com/container-engine/release-notes#supported_kubernetes_api_versions They will probably start with rolling out master node updates in the coming weeks after which you can issue a cluster upgrade command as described here: https://cloud.google.com/container-engine/docs/clusters/upgrade For now you have to wait and can't use that feature.

**Comment by jadhavnitind** [comment]
@vincentheet Thanks for the inputs on this.

**Comment by jadhavnitind** [comment]
I have installed Kubernetes 1.2 on GCS instance now and trying to create Replication Controller/Pod but unable to create it using secrets to export it as variable into the pods.

root@standalone-kubernetes:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}

root@standalone-kubernetes:~# kubectl get secrets
NAME                  TYPE                                  DATA      AGE
mysecret              Opaque                                2         2h
vcs-db-secret         Opaque                                2         2h

root@standalone-kubernetes:~# cat pod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: mycontainer
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
  restartPolicy: Never

root@standalone-kubernetes:~# kubectl create -f pod.yaml
The Pod "secret-env-pod" is invalid.

* spec.containers[0].env[0].valueFrom: Invalid value: "": may not have more than one field specified at a time
* spec.containers[0].env[1].valueFrom: Invalid value: "": may not have more than one field specified at a time


root@standalone-kubernetes:~# cat tomcatrc.yaml 
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: testtomcat
spec:
  replicas: 2
  selector:
    app: testtomcat
  template:
    metadata:
      labels:
        app: testtomcat
    spec:
      containers:
      - name: testtomcat
        image: gcr.io/fluted-oasis-107921/tomcat:vcs6
        ports:
        - containerPort: 8080
        command: [ "/bin/sh", "-c", "env" ]
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: vcs-db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vcs-db-secret
                key: password
        securityContext:
            capabilities: {}
            privileged: true
        imagePullPolicy: IfNotPresent

root@standalone-kubernetes:~# kubectl create -f tomcatrc.yaml
The ReplicationController "testtomcat" is invalid.

* spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not have more than one field specified at a time
* spec.template.spec.containers[0].env[1].valueFrom: Invalid value: "": may not have more than one field specified at a time

**Comment by jadhavnitind** [comment]
I tried to create another manual yaml file and its working fine for now.

root@standalone-kubernetes:~# /usr/local/kubernetes/cluster/kubectl.sh exec -it testtomcat-7qd12 /bin/bash
root@:# echo $DB_USERNAME
testdb
root@:# echo $DB_PASSWORD
nG145849p8R484yS
root@:#
