### ISSUE TITLE
Starting Kubernetes Cluster on Centos7 and Fedora23 fails

### ISSUE THREAD

**Issue by deromka** [kubernetes/kubernetes#23124]
I'm trying setting up the Kubernetes cluster v1.2.0-beta.0 on Centos7 (and also tried on Fedora23) using cluster/kube-up.sh command, 
I have added vsphere support into vagrant, so the Kubernetes scripts could provision VMs from my vSphere (it works, there is a pending pull request on this [link](https://github.com/kubernetes/kubernetes/pull/23121)). 

The problem is during salt script execution: etcd failed to start

`
==> master: Error:  client: etcd cluster is unavailable or misconfigured
==> master: error #0: client: endpoint http://10.245.1.2:4379 exceeded header timeout
`

Trying to start etcd manually from the master machine gives me the following reason: **listen tcp 10.245.1.2:4380: bind: cannot assign requested address**

**Centos7 log**
    `
    -- Unit etcd.service has begun starting up.
    Mar 17 16:27:17 kubernetes-master etcd[23995]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.245.1.2:4379
    Mar 17 16:27:17 kubernetes-master etcd[23995]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.245.1.2:4380
    Mar 17 16:27:17 kubernetes-master etcd[23995]: recognized and used environment variable ETCD_INITIAL_CLUSTER=flannel=http://10.245.1.2:4380
    Mar 17 16:27:17 kubernetes-master etcd[23995]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.245.1.2:4380
    Mar 17 16:27:17 kubernetes-master etcd[23995]: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag 
    Mar 17 16:27:17 kubernetes-master etcd[23995]: recognized environment variable ETCD_DATA_DIR, but unused: shadowed by corresponding flag 
    Mar 17 16:27:17 kubernetes-master etcd[23995]: recognized environment variable ETCD_LISTEN_CLIENT_URLS, but unused: shadowed by corresponding flag 
    Mar 17 16:27:17 kubernetes-master etcd[23995]: etcd Version: 2.2.2
    Mar 17 16:27:17 kubernetes-master etcd[23995]: Git SHA: 6335fdc
    Mar 17 16:27:17 kubernetes-master etcd[23995]: Go Version: go1.4.2
    Mar 17 16:27:17 kubernetes-master etcd[23995]: Go OS/Arch: linux/amd64
    Mar 17 16:27:17 kubernetes-master etcd[23995]: setting maximum number of CPUs to 2, total number of available CPUs is 2
    Mar 17 16:27:17 kubernetes-master etcd[23995]: listen tcp 10.245.1.2:4380: bind: cannot assign requested address
    Mar 17 16:27:17 kubernetes-master systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
    Mar 17 16:27:17 kubernetes-master systemd[1]: Failed to start Etcd Server.
`

**Fedora23 log**

```
`
-- Unit etcd.service has begun starting up.
Mar 17 14:57:32 kubernetes-master etcd[9504]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.245.1.2:4379
Mar 17 14:57:32 kubernetes-master etcd[9504]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd/flannel.etcd
Mar 17 14:57:32 kubernetes-master etcd[9504]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.245.1.2:4380
Mar 17 14:57:32 kubernetes-master etcd[9504]: recognized and used environment variable ETCD_INITIAL_CLUSTER=flannel=http://10.245.1.2:4380
Mar 17 14:57:32 kubernetes-master etcd[9504]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://10.245.1.2:4379
Mar 17 14:57:32 kubernetes-master etcd[9504]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.245.1.2:4380
Mar 17 14:57:32 kubernetes-master etcd[9504]: recognized and used environment variable ETCD_NAME=flannel
Mar 17 14:57:32 kubernetes-master etcd[9504]: etcd Version: 2.2.1
Mar 17 14:57:32 kubernetes-master etcd[9504]: Git SHA: 75f8282
Mar 17 14:57:32 kubernetes-master etcd[9504]: Go Version: go1.5.1
Mar 17 14:57:32 kubernetes-master etcd[9504]: Go OS/Arch: linux/amd64
Mar 17 14:57:32 kubernetes-master etcd[9504]: setting maximum number of CPUs to 2, total number of available CPUs is 2
Mar 17 14:57:32 kubernetes-master etcd[9504]: listen tcp 10.245.1.2:4380: bind: cannot assign requested address
Mar 17 14:57:32 kubernetes-master systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
Mar 17 14:57:32 kubernetes-master audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=etcd comm="systemd" exe="/usr/lib/s
Mar 17 14:57:32 kubernetes-master systemd[1]: Failed to start Etcd Server.
`
```

What is the problem here? Why etcd cannot start?

**Comment by liggitt** [comment]
vagrant provider has been removed
/close
