### ISSUE TITLE
rolling update throws loglines to screen

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#23134]
W0317 10:09:49.374877   21568 request.go:627] Throttling request took 53.854473ms, request: GET:https://104.154.56.141/api/v1/namespaces/default/pods?labelSelector=app%3Dbuttonmasher-backend%2Cversion%3Dv1

**Comment by bprashanth** [comment]
duping into https://github.com/kubernetes/kubernetes/issues/23007
