### ISSUE TITLE
kubectl does not respect osx VPN dns

### ISSUE THREAD

**Issue by macb** [kubernetes/kubernetes#23130]
I have a feeling this is more related to Go than kubernetes specifically but the `CGO_ENABLED=0` builds cause this problem to occur.

```
➜  amd64 ./kubectl get po
Unable to connect to the server: dial tcp: lookup kube-apiserver01.internal: no such host
```

When rebuilding off the v1.2.0 tag with `CGO_ENABLED=1` in the `hack/lib/golang.sh` DNS works as expected:

```
➜  kubernetes git:(5cb86ee) ./_output/local/bin/darwin/amd64/kubectl get po
NAME                            READY     STATUS    RESTARTS   AGE
pod123   3/3       Running   0          19h
```

You can also reproduce that the go dns implementation is lacking with the `CGO_ENABLED=1` bin via env variables:

```
➜  kubernetes git:(5cb86ee) GODEBUG=netdns=go ./_output/local/bin/darwin/amd64/kubectl get po
Unable to connect to the server: dial tcp: lookup kube-apiserver01.internal on 8.8.8.8:53: no such host
```

As expected, it isn't an option to force cgo resolution via runtime env variables for the `CGO_ENABLED=0` bin:

```
➜  amd64 GODEBUG=netdns=cgo ./kubectl get po
Unable to connect to the server: dial tcp: lookup prod-kube-apiserver01.nyc3.internal.digitalocean.com: no such host
```

**Comment by cmoad** [comment]
+1 Hitting this same problem. Had to add a hard-coded entry to `/etc/hosts` for now.

**Comment by ixdy** [comment]
Is this still true for kubectl 1.4.3?

**Comment by jfoy** [comment]
I'm still seeing it on kubectl 1.4.5.

**Comment by fabianofranz** [comment]
We're seeing a similar issue in OpenShift, seems related: 

https://bugzilla.redhat.com/show_bug.cgi?id=1389116

@macb @cmoad @jfoy can you please add here the OS X versions?

**Comment by macb** [comment]
I've had this issue on El Cap and the version before it. Go version has been from 1.5 to 1.7 I do believe.

It's pretty consistently a problem with `CGO_ENABLED=0` builds and macOS. go's approach to finding nameservers doesn't seem to respect some configured resolvers in osx. Instead it only seems to pickup whatever is found in `/etc/resolv.conf` which osx documents as:
```
$ cat /etc/resolv.conf
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
nameserver 8.8.8.8
```

The go source contains [this gem](https://github.com/golang/go/blob/master/src/net/conf.go#L68-L74) which may or may not be related. I believe it ends up populating the dns config [here](https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L480) which as seen above isn't adequate on macOS.

This can also be seen with `scutil`:
```
$ scutil --dns
➜  src git:(docc/check_docker_image) ✗ scutil --dns
DNS configuration

resolver #1
  search domain[0] : foo
  search domain[1] : bar
  nameserver[0] : 8.8.8.8
  flags    : Request A records, Request AAAA records
Reachable

resolver #2
  domain   : foo
  nameserver[0] : x.x.x.x
  nameserver[1] : x.x.x..x
  flags    : Request A records, Request AAAA records
Reachable
  order    : 100600
```

**Comment by NickClark** [comment]
Issue here as well. Mac is notorious for tools like `dig` and `nslookup` not using the Mac resolver. In my case, I have a custom entry under `/etc/resolver/`, but either way, `kubectl` needs to resolve DNS using the Mac stack. (interestingly enough, `ping` has always respected it)

**Comment by kargakis** [comment]
Removed the version from the title since this has recurred in later versions too

**Comment by greenboxal** [comment]
I have the same problem.

As a temporary workaround of some sort, I wrote this small utility: https://github.com/greenboxal/dns-heaven

It servers as a DNS proxy that answers requests based on macOS name resolution stack config. Basically, anything that uses /etc/resolv.conf will work with the rest of macOS DNS config.

**Comment by kiangj** [comment]
1.9.3 still having the same issue.

**Comment by bitglue** [comment]
This is probably a duplicate of https://github.com/kubernetes/release/issues/469

**Comment by macb** [comment]
https://github.com/kubernetes/release/issues/469 would resolve this issue. Seems difficult for this to be a duplicate given it was reported 1.5 years earlier :wink:

**Comment by hobbit1983** [comment]
Still a problem on 1.10.2 and Mac OS 10.13.4 adding a line in etc hosts fixes it but is a pain

**Comment by jfoy** [comment]
Looks like this is fixed by #64219 in v1.11.0: https://github.com/kubernetes/kubernetes/blob/c005b9d0ab6cd963abf66a9a12fb8ad5e48121ad/CHANGELOG-1.11.md#other-notable-changes-4

**Comment by ixdy** [comment]
@jfoy yes, somewhat. If you use the "officially" built `kubectl` from the release, the issue remains unfixed, since the binaries are cross-compiled and have cgo disabled, relying on the go-native DNS resolvers.

If you built `kubectl` yourself (e.g. through homebrew), then you should use the native macOS C-based DNS resolvers.

**Comment by bitglue** [comment]
/remove-lifecycle stale

Would be great to see the fix incorporated in the official releases.

**Comment by bitglue** [comment]
Still broken.

```console
philfrost:~ philfrost$ curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 46.3M  100 46.3M    0     0  4266k      0  0:00:11  0:00:11 --:--:--  641k
philfrost:~ philfrost$ otool -L kubectl 
kubectl:
	/usr/lib/libSystem.B.dylib (compatibility version 0.0.0, current version 0.0.0)
philfrost:~ philfrost$ chmod a+x ./kubectl
philfrost:~ philfrost$ GODEBUG=netdns=1 ./kubectl version
go package net: built with netgo build tag; using Go's DNS resolver
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: Get https://dex.redacted:5556/.well-known/openid-configuration: dial tcp: lookup dex.redacted on redacted:53: no such host
philfrost:~ philfrost$ dscacheutil -q host -a name dex.redacted
name: dex.redacted
ip_address: redacted
```

**Comment by docwhat** [comment]
/remove-lifecycle-stale

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bitglue** [comment]
broken, still

```console
$ curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 47.2M  100 47.2M    0     0  16.8M      0  0:00:02  0:00:02 --:--:-- 16.8M
$ otool -L kubectl
kubectl:
	/usr/lib/libSystem.B.dylib (compatibility version 0.0.0, current version 0.0.0)
$ chmod a+x kubectl 
$ GODEBUG=netdns=1 ./kubectl version
go package net: built with netgo build tag; using Go's DNS resolver
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: Get https://redacted:5556/.well-known/openid-configuration: dial tcp: lookup redacted on x.xx.x.x:53: no such host
```

**Comment by ixdy** [comment]
/sig release

I won't speak for the release team, but it seems unlikely that the "official" macOS builds of kubectl will be linked against macOS cgo.

The best workaround is to install kubectl using Homebrew. Further discussion in https://github.com/kubernetes/release/issues/469.

**Comment by bitglue** [comment]
There are probably other possible solutions, see the underlying [go issue](https://github.com/golang/go/issues/12524).

**Comment by docwhat** [comment]
/remove-lifecycle-stale

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JohnStarich** [comment]
We had the same issue with our cross-compiled macOS binaries.

I've created a library that fixes this for our own CLI users: https://github.com/JohnStarich/go/tree/master/dns
```go
import _ "github.com/johnstarich/go/dns/init"
```

It's not the "right" solution, but it does actually work with CGO disabled. Hopefully the above mentioned [Go issue][] will get some progress soon.

[Go issue]: https://github.com/golang/go/issues/12524#issuecomment-617453108

**Comment by vasuadari** [comment]
Bump

**Comment by vasuadari** [comment]
Temporary workaround i found was to set dns on every command in OSX. You could create your own alias for it.

```bash
networksetup -setdnsservers Wi-Fi 172.25.0.2 | kubectl
```

Would have been even better if there is a unwind for a command.

**Comment by rikatz** [comment]
folks, is this still a problem on MacOS X? Or this issue can be closed?

As this is a Go problem, I don't know if this should remain open on Kubernetes repo or can be closed.

@liggitt when this ships into Go code, do you think we need to keep this issue opened and follow the compiler update (and provide this same update here?)

Thanks

**Comment by bitglue** [comment]
As far as I know, nothing has changed to fix the issue. By default, Go behaves fine. Disabling cgo is what makes it fail. So arguably, it's a kubernetes build problem, not a go problem. Which is probably why there's been nearly zero traction on fixing this issue on either end: the go team and the teams that release go binaries are just pointing at each other.

**Comment by paulchoi** [comment]
Still seeing the same issue. Recently upgraded the Homebrew version, I believe.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mallman** [comment]
Running into this issue. kubectl is using the loooooong deprecated `/etc/resolv.conf` on Mac instead of its supported api for name resolution.

> As far as I know, nothing has changed to fix the issue. By default, Go behaves fine. Disabling cgo is what makes it fail. So arguably, it's a kubernetes build problem, not a go problem.

Hmmm... I'm wondering... what's the motivation behind disabling cgo in the kubectl build? And why can't we just enable it for the macos build to dry all these tears?

**Comment by mallman** [comment]
I’m confused. This issue was closed as “completed” yet no PR is mentioned. Has this work been completed?

**Comment by JohnStarich** [comment]
@mallman The triage bot doesn't appear to distinguish between close reasons. Looks like you can reopen with a command though.

**Comment by hakman** [comment]
The `completed` status is a new "feature" from GitHub, which seems to confuse people. See more info here: https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/.
Once the API changes are properly released, the k8s-ci-robot should be able to add the reason as `not planned`.

**Comment by weltonrodrigo** [comment]
This article explains how to work around this issue: https://medium.com/@danieljimgarcia/its-always-dns-a-kubectl-story-1326de8b2f67

**Comment by mallman** [comment]
Just saw your message, @weltonrodrigo. Yes, the Homebrew version works correctly. The version on kubernetes.io does not work correctly.

Let me (cynically) summarize the gist of this issue as I understand it:

1. Kubernetes does not interface with macOS's DNS system correctly.
2. The Kubernetes team says it's Go's fault.
3. The Go team says it's not their fault.
4. Six years later, it's still broken.

Do I have it right?

The moral of the story: don't use the official version of kubectl for macOS. It uses a legacy, unmaintained, unsupported name resolution subsystem that can only lead to tears.

**Comment by weltonrodrigo** [comment]
> Just saw your message, @weltonrodrigo. Yes, the Homebrew version works correctly. The version on kubernetes.io does not work correctly.
> 
> Let me (cynically) summarize the gist of this issue as I understand it:
> 
> 1. Kubernetes does not interface with macOS's DNS system correctly.
> 2. The Kubernetes team says it's Go's fault.
> 3. The Go team says it's not their fault.
> 4. Six years later, it's still broken.
> 
> Do I have it right?
> 
> The moral of the story: don't use the official version of kubectl for macOS. It uses a legacy, unmaintained, unsupported name resolution subsystem that can only lead to tears.

I suppose you can just use a version compiled with `CGO_ENABLED=1` and go on with your life.

**Comment by mallman** [comment]
I know that now. I wish I could get the hours back figuring out the problem and helping others debug their setup. I think one could fairly assume that this kind of thing would work OOTB from a mature, maintained project. And yet it doesn't...

**Comment by rohitagarwal003** [comment]
I think this is fixed in Go 1.20+ (https://github.com/golang/go/issues/12524#issuecomment-1297455410) and so fixed in kubectl 1.27. 🎉

**Comment by BenTheElder** [comment]
Yes, it was: https://go-review.git.corp.google.com/c/go/+/446178

**Comment by dims** [comment]
https://go-review.googlesource.com/c/go/+/446178 @BenTheElder ?

**Comment by dims** [comment]
> Yes, it was: https://go-review.git.corp.google.com/c/go/+/446178

https://go-review.googlesource.com/c/go/+/446178 @BenTheElder ?
