### ISSUE TITLE
SSH tunnels flakiness in GKE

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#23149]
**KubeProxy should test kube-proxy [Slow]**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubeproxy.go:105 Expected error: <errors.errorString | 0xc208554840>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gke-slow-release-1.2/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.105.26 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gke-slow-release-1.2/workspace/.kube/config exec --namespace=e2e-tests-e2e-kubeproxy-dtjqf host-test-container-pod -- /bin/sh -c for i in $(seq 1 5); do echo 'hostName' | timeout -t 3 nc -w 1 -u 10.180.0.5 8081; echo; sleep 1s; done | grep -v '^\\s*$' |sort | uniq -c | wc -l] [] Error from server: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \"gke-c5d9e45b81848219014b\"?\n [] 0xc2084e48e0 exit status 1 true [0xc2083e82c0 0xc2083e82e8 0xc2083e8308] [0xc2083e82c0 0xc2083e82e8 0xc2083e8308] [0xc2083e82e0 0xc2083e8300] [0x95de00 0x95de00] 0xc2083d5f20}:\nCommand stdout:\n\nstderr:\nError from server: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \"gke-c5d9e45b81848219014b\"?\n\nerror:\nexit status 1\n", } Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gke-slow-release-1.2/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.105.26 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gke-slow-release-1.2/workspace/.kube/config exec --namespace=e2e-tests-e2e-kubeproxy-dtjqf host-test-container-pod -- /bin/sh -c for i in $(seq 1 5); do echo 'hostName' | timeout -t 3 nc -w 1 -u 10.180.0.5 8081; echo; sleep 1s; done | grep -v '^\s*$' |sort | uniq -c | wc -l] [] Error from server: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-c5d9e45b81848219014b"? [] 0xc2084e48e0 exit status 1 true [0xc2083e82c0 0xc2083e82e8 0xc2083e8308] [0xc2083e82c0 0xc2083e82e8 0xc2083e8308] [0xc2083e82e0 0xc2083e8300] [0x95de00 0x95de00] 0xc2083d5f20}: Command stdout: stderr: Error from server: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-c5d9e45b81848219014b"? error: exit status 1 not to have occurred*

e.g.:

- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow-release-1.2/97
- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow-release-1.2/80
- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow-release-1.2/55
- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow-release-1.2/46
- https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow-release-1.2/14

**Comment by ihmccreery** [comment]
cc @fabioy

**Comment by ihmccreery** [comment]
This is causing Pod Disks tests to fail as well.

**Comment by cjcullen** [comment]
Fixed by #23167

**Comment by vincentwoo** [comment]
Is there a workaround for people on GKE right now? I can't connect to my dashboard!

**Comment by cjcullen** [comment]
Are your nodes firewalled off from the master? Was the master able to insert a "gke-*" SSH key into your project metadata?

**Comment by vincentwoo** [comment]
It was working last night, but mysteriously stopped working since then.

I think GCE allows all internal traffic by default, which I haven't changed. There IS a gke metadata SSH key.

**Comment by cjcullen** [comment]
@vincentwoo Take a look at #12167 for some debugging tips, or send me an email at cjcullen at google.com and I can help debug.
