### ISSUE TITLE
build_version value in logs has lost .build_number+hash metadata on Jenkins runs

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#23148]
These values are critical for the release infrastructure.  

$ curl -s http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-release-1.2/383/consoleText | awk -F= '/^[+ ]*build_version=/ {print $2}'
v1.2.1-beta.0

$ curl -s http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-release-1.1/2249/consoleText | awk -F= '/^[+ ]*build_version=/ {print $2}'
v1.1.9-beta.0.19+08de67eb0be382

**Comment by spxtr** [comment]
Curiously, it's working as expected in master.

**Comment by spxtr** [comment]
This is happening because `git describe` doesn't give you the commit if the tag points to HEAD.
