### ISSUE TITLE
Extract SIG information out of wiki

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#23146]
As a SIG owner I'd like to be able to edit my SIG's page in the wiki.  In order to do this, I need write access to the kubernetes/kubernetes wiki.  This is effectively the same as write access to the repo, lgtm privileges, etc.

It would be way more convenient if we could put SIG information in a place that is less critical to restrict.  Separate repo with a wiki?  Seperate repo with no wiki?  Specific location in kuberentes/kubernetes.github.io?

/cc @kubernetes/docs @sarahnovotny

**Comment by bgrant0607** [comment]
We need help implementing automation to work around github's woefully inadequate ACL model.

See also: https://github.com/kubernetes/contrib/pull/474

**Comment by mml** [comment]
@bgrant0607 is there a team/ label appropriate for things that are neither test nor release infra, but otherwise involve improving the developer/contributor/community experience?  If not, I think there should be.

**Comment by bgrant0607** [comment]
@spiffxp I created a new repo for this: https://github.com/kubernetes/community

@mml There is resistance to creating team labels that nobody monitors on a regular basis.

**Comment by sarahnovotny** [comment]
please use MD pages instead of the GH wiki function for the community
documentation.  (and leave breadcrumbs on the
github.com/kubernetes/kubernetes/wiki pages when their locations move.)

**Comment by mattfarina** [comment]
For anyone interested in furthering the community wiki discussion see kubernetes/community#1. I pulled this together quickly after talking with @sarahnovotny. Glad to see the community project coming together.

**Comment by spiffxp** [comment]
SIG-related docs have been copied over to the new repo, I think what remains to be done is someone with wiki access to redirect or remove SIG-related pages as appropriate, see kubernetes/community#3 for more details

**Comment by sarahnovotny** [comment]
I think this is done.  many thanks to @spiffxp for the lift and shift.  i just reconciled and deleted all the SIG wiki pages and updated a few more pages with a "this page has moved".  please reopen if you see anything that still needs a tuneup.
