### ISSUE TITLE
hyperkube config files: system pods should be in namespace kube-system

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#23153]
All the .json files here need to change: https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube

**Comment by luxas** [comment]
I may take a look at it. 
If I understand you correctly, the only thing that should be changed is adding `namespace: kube-system` to the files.

BTW, a thing I have been thinking about, why isn't kube-system automatically created? I have done this `namespace: kube-system` change locally a few times, and at least with `v1.1`, the static pods were in `kube-system`, but the `kube-system` namespace didn't exist, which is a bit counter-intuitive

**Comment by colemickens** [comment]
There's a chicken-egg problem. I tried it and it just ignored the missing namespace, it seems.

**Comment by luxas** [comment]
@colemickens To clarify, the static pods were created and ran in `kube-system` ns just fine. `kubectl --namespace=kube-system get pods` returned the static pods as expected, but `kubectl get ns` returned only the default ns
