### ISSUE TITLE
Replace htmlpreview links by kubernetes.io links in release docs

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#23159]
Right now, we replace HEAD by release version in htmlpreview links in versionize-docs: https://github.com/kubernetes/kubernetes/blob/0e229d59f09c0f221eb45ad193f5c0f8ef875fc9/build/versionize-docs.sh#L67.

We can probably replace the htmlpreview links by kubernetes.io links instead.

Ref https://github.com/kubernetes/kubernetes/issues/15910 for problem with htmlpreview links

cc @kubernetes/docs @caesarxuchao

**Comment by bgrant0607** [comment]
cc @kubernetes/docs

**Comment by spiffxp** [comment]
/close
I don't think this is relevant anymore.  The referenced script doesn't exist in this repo today.
