### ISSUE TITLE
test-linkchecker has been red for a long time

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#23162]
Here's a recent run: https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-test-linkchecker/29/

@caesarxuchao did you want this to be in critical builds? Right now I don't think anyone sees it.

**Comment by caesarxuchao** [comment]
Thanks, @spxtr. Most errors are caused by the doc move. I've informed the related parties. I'll send out alarms if the build is still red after the docs are stable.

**Comment by spxtr** [comment]
@caesarxuchao any updates?

**Comment by caesarxuchao** [comment]
Sorry, I haven't worked on this yet. I'll figure out if we are going to fix it or abandon it next week.

**Comment by caesarxuchao** [comment]
One obstacle for the linkchecker to work on the kubernetes.io is the .md files are using templates: e.g., a link in this [doc](https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/7b4ca8b1c3b1d7541d2758c227dd50b25f140212/docs/admin/namespaces/index.md):

https://github.com/kubernetes/kubernetes/blob/{{page.githubbranch}}/docs/design/namespaces.md#example-openshift-origin-managing-a-kubernetes-namespace
