### ISSUE TITLE
Change --storage-version default for 1.3

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#23166]
for both Job and HPA. Tag the PR with a release-note label so we'll be sure and give the instruction to run update-storage-objects.sh in the release notes for 1.3.

I think it's safe to do this in head ~now.

@erictune @piosz

**Comment by liggitt** [comment]
cc @deads2k

**Comment by alex-mohr** [comment]
@lavalamp I thought upgrade-storage-objects.sh was for major version changes, not minor version changes based on http://kubernetes.io/docs/admin/cluster-management/?  That is, only v1 -> v2 api would require it.

And since it's timely, is there a need to run that script between 1.1 and 1.2?  (Or for clusters created at 1.0, upgraded to 1.1, and now upgrading to 1.2?)  I don't see anything on release notes but double-checking to be sure I'm not missing anything.

**Comment by lavalamp** [comment]
@alex-mohr `upgrade-storage-objects.sh` is for API changes, and in fact we *are* making an api change: extensions/v1beta1/Job -> batch/v1/Job and similar for HPA.

@erictune and I debated in the release notes, and we think it won't be necessary to run this until after upgrading to 1.3. It shouldn't hurt anything to run it now, but unless you also change the defaults for your 1.2 binary, you'd have to run it again after 1.3. Conceivably, we'd want to get folks into the habit of running it after point release upgrades? I think it's not an issue right now though.

**Comment by alex-mohr** [comment]
@lavalamp Okay, that makes sense to me.  Thanks Daniel!

**Comment by AdoHe** [comment]
@lavalamp what's the status of this issue? Besides the default `--storage-version` now is:
```
apps/v1alpha1,authorization.k8s.io/v1beta1,autoscaling/v1,batch/v1,componentconfig/v1alpha1,extensions/v1beta1,metrics/v1alpha1,policy/v1alpha1,v1
```
you mean we should change this for kubernetes 1.3?

**Comment by lavalamp** [comment]
@AdoHe that list looks correct.

**Comment by lavalamp** [comment]
We'll leave this issue open to make sure we get this in the release notes.

**Comment by erictune** [comment]
@lavalamp is going to find a person to edit the relnote on the already merged PR, and the right relnotes are going to be generated.  Then this can be closed.

**Comment by goltermann** [comment]
This is an issue marked v1.3 and kind/documentation.  Can you get it fixed up this week?
