### ISSUE TITLE
Proposal: single parameter kubelet bootstrap

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#23172]
Kubelet bootstrap can take a single parameter and be achieved in three phases, each optoutable. The single parameter is the cluster-id.

The kubelet configuration (including kubeconfig) can be divided into three buckets. These three buckets answer the questions:
1. Where is the API and how do I trust it? This bucket consists of a list of endpoints of the API and a ca.crt to trust a secure to the endpoints.
2. How do I allow the API to trust me? This bucket consists of the authentication goodies.
3. How often do I run my sync loop? How many pulls of images should I allow to run in parallel? This is [everything else](https://github.com/kubernetes/kubernetes/blob/280897350316f3b40064699bdffbd64f37ff2dd1/pkg/apis/componentconfig/types.go#L100-L336).

Each phase pulls the configuration for the corresponding bucket. The phases are:
1. Bootstrap the client.  #5754. The kubelet uses the cluster-id to discover the cluster API.
2. Bootstrap auth. #20439 and #18112. The kubelet uses the cluster API to authenticate as a new kubelet.
3. Bootstrap config. #1627. The kubelet pulls it's configuration from the cluster API in a ConfigMap.

Once these three phases are complete. The kubelet starts it's sync loop.

cc @vishh @dchen1107 @roberthbailey @fgrzadkowski @davidopp @smarterclayton @kubernetes/sig-cluster-lifecycle

**Comment by roberthbailey** [comment]
I'd like to see a design doc written as PR and submitted to https://github.com/kubernetes/kubernetes/tree/master/docs/proposals.

**Comment by aronchick** [comment]
does this an umbrella that includes the bootstrap api? or vice versa?

**Comment by mikedanese** [comment]
@aronchick the bootstrap api as we've discussed is phase 1.

**Comment by smarterclayton** [comment]
Covered by other issues and proposals.
