### ISSUE TITLE
Another performance test

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#23178]
We may want to create the following performance test (assuming 1000-node cluster);
- create 29,000 running pods
- create 1000 pending pods
- list just the pending pods (using server-side filtering). 

That's probably a realistic debugging scenario, and I would assume it gets much better performance than listing all 30,000 pods?

@davidopp @gmarek

**Comment by davidopp** [comment]
The test definitely sounds useful (and as you say, more representative) but since it's a test I'm going to remove it from the 1.3 milestone.

**Comment by gmarek** [comment]
Outdated.
