### ISSUE TITLE
kubelet does not shut down old static pods when restarting the same time as manifest change

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#23186]
I do `kube-push` to my cluster and meet the following issue:
- In my push, I update control plane manifest as well as kubelet command line arguments.
- After push, old static pods still running while new pods failed to run. Take apiserver as an example:
  - There are 3 running containers after push: `old apiserver`, `old apiserver pause`, `new apiserver pause`.
  - Run `docker ps -a | grep apiserver` and find that new apiserver container exit because of error.
- To solve the problem, I do `docker rm -f` on `old apiserver` and `old apiserver pause` containers.

I think this should be fixed since there is high risk for `kube-push` failure.

**Comment by xinxiaogang** [comment]
@krousey Can anyone take a look at this? We meet this problem for every push now. And it is very suffer to manual kill the old version process each time.

**Comment by wikiwi** [comment]
Experiencing the same.

**Comment by quinton-hoole** [comment]
Assigning to @mikedanese to add a priority label.

**Comment by mikedanese** [comment]
What are you using to deploy the clusters? Are you using kube-push? This sounds like it could be a node issue.

**Comment by mikedanese** [comment]
closing as a dup of #17397, kube-push is utterly broken. it should be disabled.
