### ISSUE TITLE
Network flapping cause service LB pool creation failure

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#23184]
This case happens when there is network flapping.

During LB creation in servicecontroller, if there is network problem when getting response from cloudprovider, while, actually the LB has been created correctly, the LB creation will retry and retry with no chance to be success.

**Comment by xinxiaogang** [comment]
https://github.com/kubernetes/kubernetes/pull/23185

**Comment by anguslees** [comment]
`provider.EnsureLoadBalancer` is supposed to return success if the loadbalancer already exists.  I gather from comments on #23185 that the bug here is the openstack provider doesn't do the right thing when the LB pool already exists.

**Comment by idvoretskyi** [comment]
@xinxiaogang is this issue still actual?

**Comment by xinxiaogang** [comment]
@idvoretskyi we can close, thanks.
