### ISSUE TITLE
kube-down.sh releases AWS Elastic IP

### ISSUE THREAD

**Issue by hdanniel** [kubernetes/kubernetes#23181]
When bringing down the cluster in AWS, the kube-down.sh script releases the Elastic IP address defined with MASTER_RESERVED_IP . The Elastic IP was allocated before the creation of the cluster.
This is an unexpected behavior, different from 1.1.8 where the Elastic IP was only disassociated from the kubernetes master instance not released from the AWS account. I think it should be released only when is created with kube-up.sh.

**Comment by paralin** [comment]
Is it possible to tag these somehow?

**Comment by justinsb** [comment]
Sadly Elastic IPs cannot be tagged.  But we instead record a tag on the master EBS volume, so it's not entirely clear why this happened.

That said, we're not going to be making more changes to kube-up.  kops is the natural successor to kube-up for an easy-to-use replacement, and kubeadm is a building block for people that want to build things up according to different opinions.  Closing (sorry - I know this isn't resolved, but I think we're going to say that reuse of elastic ips is out of scope!)
