### ISSUE TITLE
When Jenkins master disk is full latest-build.txt is not updated

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#23182]
It makes GCS not a perfect source of truth about build status.

cc @ixdy @spxtr

**Comment by spxtr** [comment]
I'm not sure that we should even try to fix all the things that go wrong when Jenkins runs out of disk. There are just too many things.

Instead, we should just try to keep Jenkins from running out of disk :)

**Comment by gmarek** [comment]
SGTM - we can start by setting up cron job which cleans up the tmp folder, but we probably want to clean other stuff as well.

**Comment by ixdy** [comment]
We already do that. I think we're just running too many things on one host, which is something I'm working on fixing.
