### ISSUE TITLE
Create a post-upgrade stability test

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#23189]
Test whether:
- Nodes are ready after upgrade
- Containers are immediately killed after upgrade
- Pods are killed within 10 minutes after upgrade
- Pods remain terminating 10 minutes after upgrade

cc @dchen1107 @mikedanese @quinton-hoole

**Comment by quinton-hoole** [comment]
cc @fejta @kubernetes/goog-testing 

I think that we already have such a thing, for the most part (compliments of @ihmccreery I believe).  In our CI system we install a previous version of Kubernetes on a cluster, create bunch of stuff on the cluster, upgrade the cluster, and run another bunch of tests against the created stuff. These are the so-called upgrade tests.  I will dig out the relevant PR's.

**Comment by ihmccreery** [comment]
#24014 should provide a lot of the infrastructure necessary for this kind of thing.  However, @bgrant0607, your list above isn't entirely clear to me:

> - Nodes are ready after upgrade

We already test this.

> - Containers are immediately killed after upgrade
> - Pods are killed within 10 minutes after upgrade

We recreate every VM during an upgrade, so all containers will get restarted at least once.

> - Pods remain terminating 10 minutes after upgrade

Pods should *not* be terminating, right?

**Comment by bgrant0607** [comment]
Sorry, @ihmccreery. Most of the things I listed were undesirable (which fits under "test whether"). And many make the most sense in the case that the node is updated in place, which a number of users do.
