### ISSUE TITLE
clientcmd loader should use go-homedir or similar to get home directory

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#23199]
For cross-platform compatibility (i.e. windows) https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/loader.go#L46 should use [go-homedir](https://github.com/mitchellh/go-homedir) or something similar to obtain user's home directory.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/17590 is open to look up homedir on Windows correctly

**Comment by mengqiy** [comment]
@jlowdermilk Can we close this? since #17590 has been merged.

**Comment by jlowdermilk** [comment]
Fixed by #17590
