### ISSUE TITLE
Can't install Kubernetes cluster on AWS using Juju

### ISSUE THREAD

**Issue by trodriguez-photobox** [kubernetes/kubernetes#23198]
Following the official documentation for creating a Kubernetes cluster using Juju on AWS gives the following error:
make: *** No rule to make target `clean'.  Stop.

### Steps to reproduce
* Use the docker image pointed in the documentation to start a juju client
```
docker run -v ~/.juju:/home/ubuntu/.juju -ti jujusolutions/jujubox:latest
```
* Install curl
Log in as root and install curl: apt-get update && apt-get install -y curl
* Choose juju provider
```
export KUBERNETES_PROVIDER=juju
```
* Launch the install
```
curl -sS https://get.k8s.io | bash
```

### Possible hints
Once the script has failed for the first time, if we launch kube-up.sh using bash debug we get the following:
```
ubuntu@19ea950394f5:~/kubernetes/cluster/juju$ bash -x ../../cluster/kube-up.sh 
+ set -o errexit
+ set -o nounset
+ set -o pipefail
++ dirname ../../cluster/kube-up.sh
+ KUBE_ROOT=../../cluster/..
+ EXIT_ON_WEAK_ERROR=false
+ '[' -f ../../cluster/../cluster/env.sh ']'
+ source ../../cluster/../cluster/kube-env.sh
++ KUBERNETES_PROVIDER=juju
++ [[ -z '' ]]
++ declare -r 'color_start=\033['
++ declare -r 'color_red=\033[0;31m'
++ declare -r 'color_yellow=\033[0;33m'
++ declare -r 'color_green=\033[0;32m'
++ declare -r 'color_norm=\033[0m'
+ source ../../cluster/../cluster/kube-util.sh
+++ dirname ../../cluster/../cluster/kube-util.sh
++ KUBE_ROOT=../../cluster/../cluster/..
++ '[' -n juju ']'
++ PROVIDER_UTILS=../../cluster/../cluster/../cluster/juju/util.sh
++ '[' -f ../../cluster/../cluster/../cluster/juju/util.sh ']'
++ source ../../cluster/../cluster/../cluster/juju/util.sh
+++ set -o errexit
+++ set -o nounset
+++ set -o pipefail
++++ readlink -m ../../cluster/../cluster/../cluster/juju/util.sh
+++ UTIL_SCRIPT=/home/ubuntu/kubernetes/cluster/juju/util.sh
++++ dirname /home/ubuntu/kubernetes/cluster/juju/util.sh
+++ JUJU_PATH=/home/ubuntu/kubernetes/cluster/juju
++++ readlink -m /home/ubuntu/kubernetes/cluster/juju/../../
+++ KUBE_ROOT=/home/ubuntu/kubernetes
+++ source /home/ubuntu/kubernetes/cluster/juju/config-default.sh
+++ source /home/ubuntu/kubernetes/cluster/juju/prereqs/ubuntu-juju.sh
++++ set -o errexit
++++ set -o nounset
++++ set -o pipefail
+++ export JUJU_REPOSITORY=/home/ubuntu/kubernetes/cluster/juju/charms
+++ JUJU_REPOSITORY=/home/ubuntu/kubernetes/cluster/juju/charms
+++ KUBE_BUNDLE_PATH=/home/ubuntu/kubernetes/cluster/juju/bundles/local.yaml
+ '[' -z '' ']'
+ echo '... Starting cluster using provider: juju'
... Starting cluster using provider: juju
+ echo '... calling verify-prereqs'
... calling verify-prereqs
+ verify-prereqs
+ gather_installation_reqs
+ check_for_ppa juju
+ local repo=juju
+ grep -qsw juju /etc/apt/sources.list /etc/apt/sources.list.d/juju-stable-trusty.list /etc/apt/sources.list.d/juju-stable-trusty.list.save
+ package_status juju-quickstart
+ local pkgname=juju-quickstart
+ local pkgstatus
++ dpkg-query -W '--showformat=${Status}\n' juju-quickstart
+ pkgstatus='install ok installed'
+ [[ install ok installed != \i\n\s\t\a\l\l\ \o\k\ \i\n\s\t\a\l\l\e\d ]]
+ package_status juju-deployer
+ local pkgname=juju-deployer
+ local pkgstatus
++ dpkg-query -W '--showformat=${Status}\n' juju-deployer
+ pkgstatus='install ok installed'
+ [[ install ok installed != \i\n\s\t\a\l\l\ \o\k\ \i\n\s\t\a\l\l\e\d ]]
+ [[ '' == \t\r\u\e ]]
+ echo '... calling kube-up'
... calling kube-up
+ kube-up
+ build-local
+ targets=(cmd/kube-proxy cmd/kube-apiserver cmd/kube-controller-manager cmd/kubelet plugin/cmd/kube-scheduler cmd/kubectl test/e2e/e2e.test)
+ local targets
+ make clean
make: *** No rule to make target `clean'.  Stop.
```
It looks like we call make while we are at the root directory of the kubernetes repository, and there doesn't exist any Makefile there.

**Comment by mml** [comment]
@trodriguez-photobox Can you link to the official documentation in question?

**Comment by mml** [comment]
Ah, probably http://kubernetes.io/docs/getting-started-guides/juju/

**Comment by trodriguez-photobox** [comment]
@mml Yes, this is the link.

**Comment by lodotek** [comment]
How do I get past  this? :~/kubernetes$ cluster/kube-up.sh
... Starting cluster using provider: juju
... calling verify-prereqs
... calling kube-up
make: *** No rule to make target 'clean'.  Stop.


I am running ubuntu 16.04

**Comment by lodotek** [comment]
This issue has been open for a long time, no one reviews these?

**Comment by lodotek** [comment]
@trodriguez-photobox  did you ever get past this?

**Comment by trodriguez-photobox** [comment]
I spent several days trying to get it working but I couldn't. Then I tried with the AWS install method.

**Comment by chuckbutler** [comment]
@trodriguez-photobox  Thank you for your interest in juju and filing the bug. We apologize you ran into this issue, we were re-tooling the cluster/kube-up scripts to work with the latest beta's, and that drifted from breaking changes upstream.

We were a bit short handed and this bug did slip through our radar, however we've taken some time to update the scripts to work with the latest beta.  Thanks again for filing the bug, and bringing our attention to the issue.

We will be watching the issue tracker closer now for issues that mention 'juju' to try and prevent this from happening again in the future.

Thank you as well @lodotek for chiming and lending a hand. If you are still interested in giving it a try, once #30092 is merged, this behavior should be corrected for you.

**Comment by mbruzek** [comment]
We also updated the getting started guide for Juju in the latest revision of the tools.
