### ISSUE TITLE
Allow tuning of fluentd configuration without building new images

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#23195]
There are several knobs in the plugins used by the fluentd setups, but none of them are exposed to users of the images. It would be great to have that, without requiring custom images: they're more work, tend to rot, etc.

I noticed that td-agent.conf supports an `@ include` directive. Would that work, along with drop-in files in e.g. /etc/td-agent/conf.d/? Is there a way perhaps to inject environment variables into configurations? I can help with PRs once there's agreement on which approach to choose.

cc @a-robinson @jimmidyson

**Comment by a-robinson** [comment]
We'll have to work out the specifics, but I'd be a huge fan of making it more configurable through file includes or environment variables. Would you be up for figuring out a proposal?

As an (out of date) example of one option, last year I crafted [fluentd images](https://github.com/kubernetes/contrib/tree/master/logging/fluentd-sidecar-gcp) that could be used as sidecar containers in pods by specifying the file paths to collect from as environment variables. Not that I'd necessarily recommend doing it that way :)

**Comment by therc** [comment]
I can write a proposal, but I know almost nothing about fluentd and even less about Ruby. For simple substitution, I had thought of scripting the creation of files at startup with Bash, e.g. a bunch of
```
cat <<EOF
bla
BeAwsome: ${VAR:True}
bla
EOF > FILE1
```

Your example is already more advanced than that. It does answer a few of my questions, though. Thanks! Let's see what I can come up with.

**Comment by therc** [comment]
It looks like @jimmidyson's [image](https://github.com/fabric8io/docker-fluentd-kubernetes/blob/master/start-fluentd) already does a lot of that. And his currently unused [configuration file](https://github.com/fabric8io/docker-fluentd-kubernetes/blob/master/fluent.conf#L122) shows how to expand environment variables without scripting. Should we just adopt his image and build on top of that, e.g. adding an @ included drop-in directory that admins can mount as a volume?

**Comment by therc** [comment]
I was trying to experiment with a couple of options, but I am stuck because of something like https://github.com/fabric8io/fabric8/issues/5823#issuecomment-200564844 and I can't figure what's going wrong with my service account. Rebuilding the image, I get version 0.18.0 of the metadata filter plugin, which tries to be smarter (too smart, in my case).

**Comment by a-robinson** [comment]
Ah, looks very promising. @jimmidyson, do you have thoughts on what we should do here?

**Comment by therc** [comment]
Another reason why knobs are needed: https://discuss.elastic.co/t/elasitcsearch-ruby-raises-cannot-get-new-connection-from-pool-error/36252/11

**Comment by therc** [comment]
ConfigMaps work for the purpose. I was able to tune override the built-in config, which is a bit more drastic than tweaking knob, but still works:

https://github.com/kubernetes/kubernetes/issues/23001#issuecomment-219456480

**Comment by a-robinson** [comment]
cc @piosz @fgrzadkowski @igorpeshansky

**Comment by igorpeshansky** [comment]
Re: the first comment, I was going to propose something similar when I looked at the multiple duplicated config files with just one change in each pair. Happy to look at the options.

**Comment by igorpeshansky** [comment]
@crassirostris Hasn't this been addressed already?

**Comment by piosz** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/logging-stackdriver/
Changing fluentd parameters
