### ISSUE TITLE
Multiple restarts of Docker based quick start guide kube cluster leads to serviceAccount tokens not functioning

### ISSUE THREAD

**Issue by huggsboson** [kubernetes/kubernetes#23197]
Quick context: I like to use the docker image based hyperkube kubelet to allow developers internally to quickly spin up and tear down a local instance of kubernetes to test code and configuration changes.  I use he manifests-multi set of json files (though I noticed it with the normal manifests as well) so that I can quickly reset kube's etcd back to a clean state.  I'm using docker-machine (1.10.3, which is working better than 1.9.1).
The quickstart guide is here: http://kubernetes.io/docs/getting-started-guides/docker/
The related images: https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube

With the 1.2 hyperkube images I've noticed that if I restart the cluster a couple of times that the service account tokens that we mount work on the first run of the cluster, but on the second or third restart they stop functioning.  This most noticeably causes skydns to stop functioning because kube2sky is unable to connect to the api with the mounted token (and also the cert is out of date so you have to pass --insecure to curl).  

The easiest way to see this is to stop and start the cluster a few times then start a debian image with curl
```
apiVersion: v1
kind: Pod
metadata:
  name: debian
  namespace: default
spec:
  containers:
  - image: tutum/curl:trusty
    command:
      - sleep
      - "3600"
    name: debian
  restartPolicy: Always
```

Then run:
```
curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://10.0.0.1
```

But you'll actually have to do  (because the cert is out of date)
```
curl --insecure -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://10.0.0.1
```

If I then shut down the cluster and laboriously clear out /var/lib/kubelet the serviceAccount tokens begin working there.  I'm not 100% sure which state being squirreled away in /var/lib/kubelet which is causing the problem but I hypothesize that it's a race between setupfiles and the api server.  As in the apiserver starts up with the previous certs in /var/lib/kubelet and then setup files comes along and overrites them which the podmaster picks up and uses to create the serviceaccount token.  But I really don't have an idea.

I believe this is the cause of a bunch of issues people are having with skydns that I'm seeing in slack.

**Comment by huggsboson** [comment]
@fgrzadkowski

**Comment by huggsboson** [comment]
Also the docker run command I landed on (because it worked better than all the --make-shared mounting and /var/lib/kubelet:shared stuff, even with docker 1.10.3) is:
```
docker run \
    --name=kubelet \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/run:/var/run:rw \
    --volume=/var/lib/kubelet:/var/lib/kubelet:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    -d \
    gcr.io/google_containers/hyperkube-amd64:v1.2.0 \
    /hyperkube kubelet \
        --containerized \
        --hostname-override="127.0.0.1" \
        --address="0.0.0.0" \
        --api-servers=http://localhost:8080 \
        --config=/etc/kubernetes/manifests-multi \
        --cluster-dns=10.0.0.10 \
        --cluster-domain=cluster.local \
        --allow-privileged=true --v=2 >/dev/null 2>&1
```

**Comment by huggsboson** [comment]
I wanted to use mktemp -d to work around this issue, but I think kubelet passes /var/lib/kubelet to the docker daemon for containers to mount files so the paths need to match inside the container and outside.  @fgrzadkowski suggested I could just remove the mount all-together, but I found that docker couldn't mount things under /var/lib/kubelet (probably because it only existed inside the container).

**Comment by huggsboson** [comment]
I'm gonna try cleaning out the /var/lib/kubelet using:
```
mount | grep -o 'tmpfs on /var/lib/kubelet.*type' | cut -c 10- | rev | cut -c 5- | rev | xargs sudo umount
sudo rm -Rf /var/lib/kubelet/*
```

**Comment by fgrzadkowski** [comment]
@huggsboson I was obviously wrong in my comment in the other issue. As you say, we need `/var/lib/kubelet` mounted because we need to propagated directories and mounts to the host machine and docker daemon. Please check if clearing this directory between restarts helps.

**Comment by fgrzadkowski** [comment]
@mikedanese

**Comment by huggsboson** [comment]
@fgrzadkowski No problem!  It took me 3 seconds to try the change you suggested and realize it was broken, and also helped cement my understanding for how the directory is used.  The clearing the directory has fixed all of my issues, you can see the whole script at:
https://github.com/huggsboson/docker-compose-kubernetes/blob/SwitchToSharedMount/kube-up.sh

The lines for clearing are:
```
mount | grep -o 'on /var/lib/kubelet.* type' | cut -c 4- | rev | cut -c 6- | rev | sort -r | xargs --no-run-if-empty sudo umount
sudo rm -Rf /var/lib/kubelet
```

**Comment by fgrzadkowski** [comment]
@huggsboson Can send a PR to our docker instructions that would help future users? Maybe in the 'Troubleshooting` section?

**Comment by huggsboson** [comment]
Sorry I've been too swamped with other work to prep this change.  It feels like we should fix the underlying issue or make the clearing of /var/lib/kubelet each time part of the setup process.  As it tends to just "break DNS" (or any other service account token using service that you have).  I'll  prep some changes to the turnup script and docs if I get a chance in the next few days.

**Comment by fgrzadkowski** [comment]
I'm not sure that clearing this directory by default is always a good solution. I imagine someone may want to restart kubelet, but keep the state...

**Comment by huggsboson** [comment]
Yeah, I think fixing the bug/race is the best option.  I just don't have the time to take that on.

**Comment by huggsboson** [comment]
Cross posting from: #23111.

Just to be clear about things I know:
1. I know that the issue is related to service account tokens not functioning correclty
2. This is reproducible, turnup and turndown the cluster a few times and then try to use service account tokens.
3. I know that /var/lib/kubelet has some state in it that is causing this because if I blow it away between runs I don't have any issues.

Let me dive into my theory.

When people are using the moral equivalent of the turnup and turndown scripts, they create the containers and then destroy them (but don't clear /var/lib/kubelet where all emptyDir and secrets mounts live). The setup-files.sh script writes to an empty dir which are shared by apiserver (the thing that verifies tokens) and controller-manager (the thing that mints and signs tokens). When kubelet starts a pod from an on-disk file it gets the same pod-id every time, so any emptyDirs that were mounted will have the files in there from before (because we didn't kill /var/lib/kubelet).

My guess is:
1. apiserver starts up with certs from previous kube-up. controller-manager waits for the api to become available to create the token in a secret.
2. setup-files.sh completes
3. controller-manager sees the api-server starts up and mints/signs the token and creates the secret with the token and cert (which is also broken) but with the now modified ca.crt and keyfile that setup-files.sh wrote.

An easy way to test this theory would be to have setup-files.sh exit early if the ca.crt and keys are already generated. I won't have time over the next few days to work on this so if someone wants to try it out, I'd gladly help out in anyway I can.
