### ISSUE TITLE
Dashboard is run by default, but could allow privilege escalation when used with custom authorization

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#23201]
Dashboard is run by default (by virtue of the file: cluster/addons/dashboard/dashboard-controller.yaml).   Dashboard lets anyone who can connect to it view, edit, and delete objects.  
Kubernetes authorization plugins allow putting very flexible restrictions on what users can do what to which objects.

I plan to immediately edit Authorization docs, Addons docs, and 1.2 release notes docs to recommend that users who are using fancy Authorization should disable the Dashboard addon.

I'm not sure what the best long term solution is.  The best ones I can think of so far are:

1. implement [acting-as](https://github.com/kubernetes/kubernetes/pull/16933) and dashboard uses that for all accesses to the API, and does no caching.
1. do not run dashboard by default, and leave it to users to decide if their authorization scheme is compatible with dashboard.

**Comment by erictune** [comment]
@kubernetes/sig-auth

**Comment by erictune** [comment]
@kubernetes/dashboard-maintainers

**Comment by erictune** [comment]
@lavalamp

**Comment by erictune** [comment]
Note, the dashboard is only 1.2, not 1.1, so this is not a security concern for users who are running official kubernetes releases.

```console
git tag --contains 46f51d74bbaf695b2effae74d62d44ded3e7d2a9
v1.2.0-alpha.8
v1.2.0-beta.0
v1.2.0-beta.1
v1.3.0-alpha.0
```

**Comment by roberthbailey** [comment]
> this is not a security concern for users who are running official kubernetes releases.

The latest official release is 1.2.0 and contains dashboard running by default.

**Comment by bryk** [comment]
@erictune Hasn't this problem been present since 1.0 when kube-ui was added? Dashboard UI is basically similar UI + a few write capabilities. I don't see a reason why at the time it wasn't a problem, but now it is.

Of course, when somebody changes default auth scheme, then the configuration for Dashboard and other addons should be reevaluated (like heapster publishing metrics data). 

We want, however, to implement auth and working-on-behalf-of-a-user in the UI, but AFAIK there is no single blessed solution for this in K8s. So that's why this hasn't happened yet.

**Comment by roberthbailey** [comment]
@bryk It wasn't an issue with kube-ui because that UI was read-only.

**Comment by deads2k** [comment]
> @bryk It wasn't an issue with kube-ui because that UI was read-only.

If the UI displayed secrets, then that would allow escalation via service account tokens.

**Comment by roberthbailey** [comment]
@deads2k kube-ui pretty basic and doesn't show secrets:

<img width="1431" alt="screen shot 2016-03-21 at 10 12 12 am" src="https://cloud.githubusercontent.com/assets/7751204/13927342/9ae7c330-ef4e-11e5-9456-9675407bbe28.png">

**Comment by bryk** [comment]
Yeah, abstracting from whether kube-ui was good in this matter, I agree that Dashboard UI security model is primitive and should be improved.

@erictune Can we have a meeting between @kubernetes/dashboard-maintainers and you to describe us the problem and brainstorm possible solutions?

**Comment by erictune** [comment]
There are no issues I am aware of with the current dashboard and @bryk is aware of this issue for ongoing development.
