### ISSUE TITLE
Go unit tests are failing in jenkins

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#23200]
```console
10:50:24 + godep go install ./...
10:50:24 godep: godep should only be used inside a valid go package directory.
10:50:24 godep: You are probably outside of your $GOPATH.
10:50:24 godep: 	Current Directory: /workspace/kubernetes
10:50:24 godep: 	$GOPATH: /go
```

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/9833/

**Comment by krousey** [comment]
@kubernetes/sig-testing any idea what is causing this?

**Comment by krousey** [comment]
@ixdy pointed out that this is probably due to https://github.com/tools/godep/commit/670c16bc098f626edb93e9bcc1001e44333d1db8 and us not setting $GOPATH properly.

**Comment by ixdy** [comment]
Yeah, hack/jenkins/test-dockerized.sh runs `go get github.com/tools/godep` on each run, so we are now getting the latest and greatest godep binary, which coincidentally is now broken. We probably need to set GOPATH to $WORKSPACE or something, and then cherry-pick that fix to the release-1.1 and release-1.2 branches.

**Comment by ixdy** [comment]
Looks like it's not just Jenkins broken; if I update godep to v59 locally, `hack/update-generated-swagger-docs.sh` fails:
```
godep: godep should only be used inside a valid go package directory.
godep: You are probably outside of your $GOPATH.
godep:  Current Directory: /go/src/k8s.io/kubernetes
godep:  $GOPATH: /go/src/k8s.io/kubernetes/_output/local/go:/go/src/k8s.io/kubernetes/Godeps/_workspace
go: GOPATH entry is relative; must be absolute path: "".
Run 'go help gopath' for usage.
!!! Error in /go/src/k8s.io/kubernetes/hack/update-generated-swagger-docs.sh:49
  'GOPATH=$(godep path):$GOPATH go run cmd/genswaggertypedocs/swagger_type_docs.go -s "pkg/$(kube::util::group-version-to-pkg-path "${group_version}")/types.go" -f - >> "$TMPFILE"' exited with status 2
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/update-generated-swagger-docs.sh:49 generate_version(...)
  2: /go/src/k8s.io/kubernetes/hack/update-generated-swagger-docs.sh:65 main(...)
Exiting with status 1
```

This is probably due to our munging of GOPATH in `hack/lib/golang.sh`.

**Comment by ixdy** [comment]
(there may be other stuff broken, too. who knows!)

**Comment by eparis** [comment]
godep must be pinned to v53 until my PR to fix it....

**Comment by eparis** [comment]
https://github.com/kubernetes/kubernetes/pull/22807

**Comment by eparis** [comment]
That is the fix.  Pin godep to v53 (how did it get unpinned?

**Comment by eparis** [comment]
ohhhhhhhhhh, I see, this is a different godep issue  :-(   this one is just a bug in godep. @freeformz

**Comment by freeformz** [comment]
@eparis AFAICT The $GOPATH listed above is busted and should contain `/go` if you plan to build code / use godep in `/go/src/k8s.io/kubernetes`

**Comment by freeformz** [comment]
FWIW: I spend a HUGE amount of time going back and forth with troubleshooting stuff that ends up being because people are doing stuff outside of a $GOPATH. Hence this "feature".

**Comment by ixdy** [comment]
It would've been nice is this was a warning, first. Now we get to have a fire drill fixing all of our builds, which were more or less working.

**Comment by freeformz** [comment]
@ixdy I am sorry about that. FWIW: I've also gotten flack for adding things as Warnings. I also wonder, would it have been noticed if it had been a warning?

**Comment by freeformz** [comment]
@ixdy also, re my initial comment ... I didn't read the initial output.

It looks like the script is trying to do stuff in `/workspace/kubernetes` when the GOPATH is set to `/go`. Why not check it out to `/go/src/k8s.io/kubernetes`? 

Maybe I should relax the restriction for `godep go` as well. As that just manipulates $GOPATH to add `./Godeps/_workspace` and then shells out to `go`. But you still aren't in a valid $GOPATH and there have been odd bugs associated with the use of the go tool outside of the $GOPATH at times (AFAIK these are all fixed atm, but yeah).

**Comment by freeformz** [comment]
After thinking about this some more, maybe I should just make it a warning.

**Comment by ixdy** [comment]
Depends how long it was a warning. If a month or so, I'm sure someone would have noticed it.

I fixed the [initial `godep go install` failure](https://github.com/kubernetes/kubernetes/issues/23200#issue-141935611) by `cd`ing into a path in the GOPATH in #23202, which is probably more correct anyway.

We had another failure in `hack/update-generated-swagger-docs.sh` because we change the GOPATH to something hermetic in `hack/lib/golang.sh`. Doing this ensures that we don't have accidental dependencies outside the tree, but it means that now `godep` doesn't work in some places.

**Comment by freeformz** [comment]
godep v60 pushed changing this to a warning.

**Comment by ixdy** [comment]
Thanks!

I'll still work on fixing this properly.

**Comment by eparis** [comment]
And I do think the idea of not complaining at all on `godep go` is a good idea...

**Comment by freeformz** [comment]
@ixdy :+1:
