### ISSUE TITLE
Don't sync daemonset or deployment when their pod selector is Everything

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#23218]
This is useful for most controllers but critical for daemonset and deployment due to bugs like #23170

@davidopp @bgrant0607

**Comment by bgrant0607** [comment]
cc @ghodss

**Comment by davidopp** [comment]
Once we have controllerRef, we could also have a check that a controller should not delete a pod unless its controllerRef points to that controller. (Though I haven't thought this through carefully, so maybe there is some problem with the idea. And maybe it should be "unless its contorllerRef points to that controller or is unset.") It's not a replacement for the check described here, just something we could do in addition.

**Comment by bprashanth** [comment]
would be nice if we got `gcloud container clusters upgrade` to handle this with a before/after hook @kubernetes/goog-gke

**Comment by mikedanese** [comment]
I'm not convinced this is necessary to do for deployment. Shouldn't this validation:

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/validation/validation.go#L705-L707

Prevent a deployment from rolling forward to a replicaset with a `{}` label selector?

**Comment by bgrant0607** [comment]
@mikedanese: @ghodss ran into a problem where alpha Deployments appeared to be selecting all pods when updating from 1.1.X to 1.2.0.

The ReplicaSet wouldn't be empty because we add a pod-template-hash label, but no user labels would be selected, so it would select all the pods in the namespace.

**Comment by bgrant0607** [comment]
cc @janetkuo
