### ISSUE TITLE
Move internal types of job & hpa

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#23216]
We left the internal types of job and hpa in the extensions group for 1.2. Now it's time to move them over to the correct groups. This needs to happen before 1.3, and sooner is probably better.

@erictune @piosz

**Comment by liggitt** [comment]
cc @deads2k

**Comment by piosz** [comment]
HPA part is covered by #21577

**Comment by soltysh** [comment]
@lavalamp are we also removing the extensions/v1beta1 objects for the two, or that will happen in 1.4?

**Comment by soltysh** [comment]
As usual, I'll take care of the job part.

**Comment by piosz** [comment]
@soltysh I'm not planning to remove extensions/v1beta1 in 1.3 but only deprecate it. In 1.4 this will be removed.

**Comment by soltysh** [comment]
@piosz thx, just wanted to make sure.

**Comment by lavalamp** [comment]
Right, we will *not* move extensions/v1beta1 objects. 1.3 deprecation, 1.4 removal (theoretically).

**Comment by soltysh** [comment]
Job part of this issue has merged over night.

**Comment by bgrant0607** [comment]
HPA types moved by #25279
