### ISSUE TITLE
Support differentiating the OS distribution in e2e tests

### ISSUE THREAD

**Issue by andyzheng0831** [kubernetes/kubernetes#23221]
The test case "[k8s.io] Addon update should propagate add-on file changes" uses "/etc/init.d/kube-addons restart" to restart kube-addons service. This way only works in ContainerVM. In our Jenkins running on trusty, this test case keeps failing. Please add a method in the e2e testing code to differentiate the OS distribution in use, just like the env variable KUBE_OS_DISTRIBUTION used in cluster creation. After this issue is fixed, I will change the test code to work in trusty.

cc/ @dchen1107 @roberthbailey @zmerlynn @wonderfly

**Comment by ixdy** [comment]
cc @kubernetes/sig-testing

**Comment by ixdy** [comment]
Not sure if there's an easy way to automatically detect the OS distribution from a running cluster. I guess we could add a flag to `test/e2e/e2e.go` that's set in `hack/ginkgo-e2e.sh`.

**Comment by andyzheng0831** [comment]
I had thought about that before. But it seems that the machine running e2e should differentiate it, as it runs commands in remote vms of a cluster. A cluster knows which os distro is in use seems not adequate.

**Comment by ixdy** [comment]
Well, I mean it would be nice if the e2e test infra could query the cluster under test, rather than requiring the user running the e2e tests to supply that information. We already do this with cluster versions, for example.

**Comment by andyzheng0831** [comment]
That sounds reasonable and doable, I think. There is an env variable OS_DISTRIBUTION (https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L38) and we can add it in the kube-env file in function build-kube-env (https://github.com/kubernetes/kubernetes/blob/master/cluster/common.sh#L454), and the test infra can query this variable.

**Comment by spiffxp** [comment]
There are a couple of assumptions here, not just that the cluster is deployed as a specific set of named services on a particular OS, but also that SSH access to the cluster under test is even available.  This is particularly apparent when you try to run e2e tests on a cluster deployed with something other than `e2e.go` or `kube-up.sh`.

All that to say that keying off of OS distribution probably isn't enough here.

I don't have a better proposal other than somehow exposing component restarts via something other than SSH, which is quite a bit larger in scope.

**Comment by andyzheng0831** [comment]
I see. I did not mean to cover all of these cases when logging this issue.
The major motivation is to make the known failed test cases work on trusty,
as it has an assumption that kube-addon service is running in debian. We
used to be able to blacklist a known failed test, but the new e2e framework
seems not support it any more. So, we see the same test case failing in our
jenkins every 8 hours

**Comment by roberthbailey** [comment]
@spiffxp -- many of the tests (and test infrastructure) do assume the ability to log into a node. If we want to address this, we should open a separate issue, since it is a larger problem to solve (and I think relates to other initiatives like self hosting and running addons as deployments). 

@andyzheng0831 - I think there is still a mechanism to blacklist a specific test if we wanted to take that route (@spxtr would know for certain).

**Comment by andyzheng0831** [comment]
Blacklisting it is a short-term approach that can exclude the noise from our testing result. But in long-term we should have this test to catch potential breakage.

**Comment by spiffxp** [comment]
@roberthbailey ref #20919

**Comment by spxtr** [comment]
`go run hack/e2e.go -v --test --test_args="--ginkgo.skip=blacklist\sthis\stest"` ought to do the trick.

**Comment by ixdy** [comment]
Short of being able to query the cluster itself for OS distro, passing a flag to `test/e2e/e2e.go` and saving it in `testContext` is probably fine. We already use this pattern for cloud provider (https://github.com/kubernetes/kubernetes/blob/master/hack/ginkgo-e2e.sh#L95 and https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L70).

**Comment by andyzheng0831** [comment]
Sounds good! I will make a PR for it.
