### ISSUE TITLE
move kube-proxy into a daemonset

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#23225]
ref #23174

**Comment by luxas** [comment]
@mikedanese How do you plan to access the apiserver from the daemonset?
I totally forgot about this when making the manifest for docker-multinode.
It's a chicken-and-egg-problem where kube-proxy needs to connect to the apiserver in order to setup the 10.0.0.1 mapping from endpoint to service.

I obviously know you know this, but summarizing anyway.

The first solution I can think of is that the apiserver would advertise itself by making a `APISERVER_INITIAL_ENDPOINT` configmap that could be used by the kube-proxy. That also might make sense in HA configs later on, when comma separated values are supported by the --master flag.

WDYT? I know it's too late for v1.3, so I'll remove the daemonset for now, but please answer asap so I can proceed on it

**Comment by mikedanese** [comment]
@luxas kube-proxy and kubelet should not use the service IP

> The first solution I can think of is that the apiserver would advertise itself by making a APISERVER_INITIAL_ENDPOINT configmap that could be used by the kube-proxy.

This sounds like a good idea. We can mount a kubeconfig file into the kube-proxy container and configure the apiserver client using the --kubeconfig= flag. The kube-proxy should talk directly to the apiserver (using the node ip if using host port or another method that doesn't depend on the master service).

The reason we haven't just pulled the trigger on this is it's a bit tricky from the upgrade perspective and how we handle addons. The problems

1. How do we do this in version skewed clusters where nodes are from a version where kube-proxy ran in a static pod?
1. How do we upgrade daemonsets since they don't have an upgrade mechanism yet?

I would definitely be happy for some help on this one if you have an idea on how to do this and want to bump the priority.

**Comment by bgrant0607** [comment]
ref #15324

**Comment by theothermike** [comment]
Just wanted to add a story from an outage we just had relating to this. (also #36539 above)

We're heavy users of Kubernetes, and it appears this past Friday Dec 3rd, GCE had major spikes on all our VMs, including k8s nodes.   This caused kube-proxy to be evicted from two of our clusters, causing intermittent service outage (very bad)

This needs to be addressed ASAP, and frankly I'm kind of surprised k8s is called 'production ready' with such a huge point of failure

we're mitigating by actively looking for evicted pods, and also adding extra deep pingers to take any pods out of service that could be affected by this

**Comment by mikedanese** [comment]
That certainly sounds terrible but I'm not sure this issue would have helped. I think you are looking for a fix for https://github.com/kubernetes/kubernetes/issues/35521. Sorry for the bad experience!

cc @dchen1107 @kubernetes/sig-node

**Comment by bprashanth** [comment]
@kubernetes/sig-network we should try and do this in 1.6, it's the cleanest way to handle kubeproxy failing admission checks (3 in https://github.com/kubernetes/kubernetes/issues/38322#issuecomment-267408017, but NOT handled in the fix for that issue)

**Comment by thockin** [comment]
This intersection of kube-proxy and eviction was unforeseen.  We're working
on a short-term fix for 1.4 and 1.5, and I think a DaemonSet is correct for
1.6.  we'll either use the 'critical' annotation or a new priority system
TBD.  Being in a Daemonset also means we can mutate things like resource
requests in response to cluster size.

**Comment by edwardfung123** [comment]
Hello. I aware that they is going to be fixed in the release 1.6 on 22nd of March. I am not sure it is available for google container engine immediately. But before the release, do we have any hot-fix or workaround for this? I can imagine to run a cron job outside the cluster to check if any kube-proxy is down and restart that instance... 

By the way, is there any way to restart the kube-proxy manually besides restarting the node?

**Comment by thockin** [comment]
Kube-proxy should be better protected now (1.52, I think?), and it will get
even better on 1.6.

@vishh

**Comment by vishh** [comment]
@thockin yeah. Kube-proxy will be better protected from OOM kills and will not be evicted when run as a static pod. 

The act of moving Kube-proxy to a daemonset is still pending as of v1.6. It needs an owner.
Kube-proxy needs to be moved to the Guaranteed QoS class as well.

**Comment by luxas** [comment]
> The act of moving Kube-proxy to a daemonset is still pending as of v1.6. It needs an owner.

@vishh I suppose you mean for kube-up + GCE,GKE, right?
kubeadm has run kube-proxy in a DaemonSet from the get go, and I believe other deployments do that as well

**Comment by luxas** [comment]
> Kube-proxy needs to be moved to the Guaranteed QoS class as well.

@vishh Can this be done easily? How?

**Comment by vishh** [comment]
> kubeadm has run kube-proxy in a DaemonSet from the get go

Yeah. What I was describing was for kube-up.sh. However given that master are upgraded prior to upgrading nodes, kube-proxy upgrades have to somehow be tied to node upgrades. I'm not super familiar with kubeadm setup to know if that's already taken care of.

> @vishh Can this be done easily? How?

@thockin's idea is to run a controller that will adjust kube-proxy's memory and cpu requirements based on the number of services that exist in the cluster. A daemon set helps with that.
We need some benchmarks to measure kube-proxy's resource requirements relative to the number of services. This needs an owner as well AFAIK.
With the benchmarks and a controller (or better Vertical Pod Autoscaling) it will be safe to transition kube-proxy to the `Guaranteed` QoS class.

**Comment by luxas** [comment]
So moving kube-proxy to the Guaranteed class depends on https://github.com/kubernetes/features/issues/21?

> I'm not super familiar with kubeadm setup to know if that's already taken care of.

We're aiming to have a `kubeadm upgrade` command that takes care of this for v1.7
cc @lukemarsden

**Comment by spiffxp** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/sig-network-pr-reviews @luxas @thockin @vishh We are treating all issues in the v1.6 milestone as blockers.  Does this issue justify blocking the 1.6 kubernetes release?  If yes, can you give an estimate on who will fix this by when?  If no, would you mind kicking this out of the v1.6 milestone?

**Comment by MrHohn** [comment]
This is not blocking v1.6. We plan to make more progress on it in the next release.

**Comment by roberthbailey** [comment]
Based on some offline discussions it sounds like this is a stretch goal for 1.7 and if it misses we will try to prioritize for 1.8. 

@matchstick / @dchen1107 - does that sound right to you?

**Comment by matchstick** [comment]
That is the plan for now.

**Comment by thockin** [comment]
Moving out of 1.7

**Comment by roberthbailey** [comment]
I moved this from 'next-candidate' (which seems to get ignored) into v1.8. Also note that kubeadm already runs kube-proxy as a daemonset (for better or worse).

**Comment by mikedanese** [comment]
Is @freehan working on this?

**Comment by thockin** [comment]
Not in 1.7

**Comment by spiffxp** [comment]
/remove-priority P1
this already has priority/backlog on it, I'm not actually sure this is the right priority, just trying to remove the old priority/PN labels

**Comment by roberthbailey** [comment]
@matchstick @bowei @thockin - can we prioritize doing this in kube-up / GKE for 1.8? We already use kube-proxy in a daemonset in kubeadm and if there is something preventing that scenario from being production ready we need to address it.

**Comment by matchstick** [comment]
This is currently being targeted for 1.8. @MrHohn has it on his list of delveirables and we will be tracking this in the network SIG also.

**Comment by MrHohn** [comment]
A few updates, #50705 adds the option to run kube-proxy as a DaemonSet for GCE. That is the first step of the works, while some remaining tasks in my mind:
- [ ] Priority/preemption setup: put kube-proxy in [System Priority Class](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/pod-priority-api.md#system-priority-class-names).
- [ ] Use service account for kube-proxy.
- [ ] CI to test network functionalities when run kube-proxy as a DaemonSet.
- [ ] CI to validate the upgrade/migration path (static pods -> daemonset).
- [ ] (Maybe?) Move kube-proxy to Guaranteed QoS class.

**Comment by luxas** [comment]
cc @kubernetes/sig-auth-feature-requests 
> Use service account for kube-proxy.

Should we do the same for kube-proxy as we do for kube-dns [1], i.e. bind the `kube-proxy` SA to the `system:node-proxier` ClusterRole by default? I think that would make sense, as that's not a depoyment-specific option really, instead a common requirement for everyone.

That is:
```go
rbac.NewClusterBinding("system:kube-proxy").SAs("kube-system", "kube-proxy").BindingOrDie(),
```

1: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L406

**Comment by deads2k** [comment]
> Should we do the same for kube-proxy as we do for kube-dns [1], i.e. bind the kube-proxy SA to the system:node-proxier ClusterRole by default? I think that would make sense, as that's not a depoyment-specific option really, instead a common requirement for everyone.

The choice of which SA to bind is a deployment-specific need, but the role is not. That is why we create the role, but not the rolebinding.  The rolebinding is deployment specific.

**Comment by luxas** [comment]
> The choice of which SA to bind is a deployment-specific need, but the role is not. That is why we create the role, but not the rolebinding. The rolebinding is deployment specific.

The rolebinding is created for kube-dns already. I don't think this is very deployment specific, any deployment is kind of gonna need this any way. Also, there is a `kube-proxy` binding already to the `kube-proxy` user (using a cert CN), but _that_ is insufficient for most deployments.

I don't think we should make the move to RBAC harder than it really is. This seems like a sane thing to do to me. We don't want more sprawl, we want more unity between the deployments. This is a no-op for k8s to do, let's use a good default here and make it easier for folks to run kube-proxy in a DS.

**Comment by liggitt** [comment]
I think the service account (and associated binding) should be part of the manifest that deploys kube-proxy. In retrospect, kube-dns should probably do the same.

**Comment by luxas** [comment]
We know that virtually every deployment will use kube-proxy right. Most of them are deploying kube-proxy as a DS. Kubernetes _should not_ create the SA for the proxy. But why force all the ~70 providers to duplicate this rolebinding? Why end up with 70 duplicate roles per provider vs one auto-bootstrapped?

Again, this is not generally applicable. But in this case (kube-proxy) I really think it is.

@kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by liggitt** [comment]
The provider of the component should define the role (which we do as a bootstrap role).

The binding logically belongs with the service account, since there's no reason for kubernetes to care what you name the service account or what namespace you place it in.

Like I said, I think the kube-dns default service account binding should not have been in bootstrap bindings, but part of the kube-dns RBAC manifest.

**Comment by shashidharatd** [comment]
Ref: https://docs.google.com/document/d/1x1h_i-nHUtLZJqbXbaok4QaP0cLexaxYjQKpqITEzUw

**Comment by cmluciano** [comment]
@MrHohn Should this be moved to 1.9?

**Comment by MrHohn** [comment]
> @mrhohn Should this be moved to 1.9?

@cmluciano SGTM. We made some progress in 1.8, but there are remaining tasks needed to be done in following releases.

**Comment by luxas** [comment]
@MrHohn @bowei @thockin @dchen1107 We're targeting beta quality for this on GKE in v1.9, right?

**Comment by bowei** [comment]
@luxas 
Yes, that is correct.

**Comment by MrHohn** [comment]
Update:

Because the dependent feature (Priority/preemption - https://github.com/kubernetes/features/issues/268) will stay in Alpha in 1.9, the latest plan is to not run kube-proxy as DaemonSet by default in 1.9.

We should modify the milestone accordingly.

**Comment by jberkus** [comment]
removing status approved-for-milestone, because this issue was approved for 1.9.  If it's actually approved for 1.10, please put the label back.  Thanks!

/remove-status approved-for-milestone

**Comment by jberkus** [comment]
What's the status on this issue?  All related PRs I can find are closed.  What work remains to be done, and where are the PRs for that work?

**Comment by MrHohn** [comment]
Thanks for modifying the millstones. We had punted this to the next milestone.

**Comment by luxas** [comment]
@kubernetes/cloud-provider-gcp-maintainers @MrHohn I'm closing this issue, I guess it is done.
If it's not, you may reopen, but if so kube-up/GKE is probably the only one that doesn't run kube-proxy in DS...

**Comment by mikedanese** [comment]
I'd like this to be the on by default in our CI before we resolve. @MrHohn have we made progress on this?

**Comment by MrHohn** [comment]
@luxas @mikedanese Thanks for bumping this up, this is not done yet. But with pod priority becomes beta (https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/), we should try promoting this to default!

One issue though is https://github.com/kubernetes/kubernetes/issues/65114, which means flipping it to default will break our upgrade CI (1.13 -> HEAD). I will look into that before flipping the bit.

**Comment by MrHohn** [comment]
This hasn't been prioritized but we will work on it.
/remove-triage unresolved

**Comment by rikatz** [comment]
Hey folks, quick question as I've taken a look:

this seems to be already delivered by kubeadm as a default, so we can consider this a success, right? There are plenty other scenarios already running kube-proxy as a Daemonset.

Also Pod Priority Preemption is stable since v1.14, so @MrHohn @luxas @neolit123 wdyt? can we close this one?

**Comment by neolit123** [comment]
given kubeadm is already doing kube-proxy as a DS and kube-up is deprecated this seems to be resolved WRT the k/k repository.
please re-open if needed.

/close

**Comment by rikatz** [comment]
And there it goes a 4 year old issue :)
