### ISSUE TITLE
Change addon yamls and the addon-resizer to reflect best practices for resource requirements

### ISSUE THREAD

**Issue by Q-Lee** [kubernetes/kubernetes#23229]
In #22893 we noticed that our yaml's resource requirements for addons don't match the [best practices](http://kubernetes.io/docs/user-guide/config-best-practices/). It seems #18216 added requests to all addons.

We'll also want to change the addon-resizer's behavior to understand this. Currently it would update the deployment so that requests = limits if requests is unspecified.

**Comment by gmarek** [comment]
I'll add my 2c here. I don't like the defaulting behavior of setting up request to the limit value, if request is omitted. I see it as a discontinuity at 0 - I know that 0 and unset are different values, but one would need to look at the API definition to notice that request is a pointer, not a plain value - my first and thought would be that it's plain `int` thus unset = 0. I understand why we did that for v1.0, I think that we shouldn't encourage this pattern as it's confusing. 

cc @bgrant0607

**Comment by fgrzadkowski** [comment]
To be honest I don't see any value in specifying exactly the same number twice. Simpler/shorter configs are usually better. @gmarek What's the advantage?

**Comment by gmarek** [comment]
Consistence around 0. My perspective is the following:
- people will expect that both request and limit to be plain ints (not pointers)
- default value if int is unspecified is 0
- there shouldn't be much difference between 1 and 0 (similar argument that we have against different semantics of value `0` for `graceful_deletion_period`) - currently the semantics of 1 and 0 are close, but between 1 and undefined differ drastically - which I think is bad.

I'm just stating my opinion, backed by the fact I saw a confusion about it a few times already. I'm not going to fight for it or anything.

**Comment by roberthbailey** [comment]
@gmarek / @Q-Lee - is this still an issue with our current addon configs? Should we prioritize fixing it?
