### ISSUE TITLE
move fluentd into a daemonset in salt

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#23224]
ref #23174

**Comment by quinton-hoole** [comment]
@mikedanese what priority?  Provisionally assigning p2.

**Comment by mikedanese** [comment]
This is implemented in #23306, so hopefully will be done for 1.3

**Comment by bgrant0607** [comment]
ref #15324

**Comment by bgrant0607** [comment]
@mikedanese Is this done?

**Comment by mikedanese** [comment]
This is done in kubernetes-anywhere but not merged in kube-up. Considering this issue refs kube-up v2 issue, I'm not sure if there is huge motivation to do this in kube-up.

This was implemented in https://github.com/kubernetes/kubernetes/pull/23306 but not merged due to some work that needed to be done around cluster upgrades. @piosz do we still care to do this? What is the motivation?

**Comment by piosz** [comment]
We need to make fluentd more manageable (ie. add a possibility to change resource limits/requests). I'm taking over this and try to finish your work.

**Comment by piosz** [comment]
Bumping priority: there is a lot of problems with fluentd, migrating it to daemon set will make it more managable.

**Comment by pwittrock** [comment]
@mikedanese @piosz Please provide daily updates to this issue or move it to v1.4-nonblocking

**Comment by piosz** [comment]
The change is too risky IMO, so moving out of 1.4
