### ISSUE TITLE
Debian specific e2e tests?

### ISSUE THREAD

**Issue by sjpotter** [kubernetes/kubernetes#23232]
There are a number of tests that fail in our rktnetes work that seem to be Debian specific (though not 100% sure)

There are 3 DNS tests that do "jessie"/"wheezy" lookups.  dont quite understand what they are doing but they seem to fail when tested with CoreOS

[k8s.io] DNS [It] should provide DNS for services [Conformance]
[k8s.io] DNS [It] should provide DNS for pods for Hostname and Subdomain Annotation 
[k8s.io] DNS [It] should provide DNS for the cluster [Conformance] 

There is also one that that expects to be able to restart a service via an /etc/init.d script which doesn't exist in CoreOS.

[k8s.io] Addon update [BeforeEach] should propagate add-on file changes 

@spiffxp

**Comment by ixdy** [comment]
@kubernetes/sig-testing

**Comment by mml** [comment]
These should probably be broken out with a specific approach for each test: either make it more platform agnostic or label some tests as [Debian].

**Comment by euank** [comment]
I investigated the DNS tests a bit more, and it looks like the failure is not due to them being coded to debian, but rather due to some behavioural differences (well, probably bugs) in CoreOS/rkt. See https://github.com/kubernetes/kubernetes/issues/24563 re the dns tests.

**Comment by yifan-gu** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/24563
