### ISSUE TITLE
kubectl command --help doesn't mention deployments

### ISSUE THREAD

**Issue by sah** [kubernetes/kubernetes#23231]
In 1.2.0, `kubectl expose --help` and other command help talks about replication controllers rather than deployments. Because `kubectl run` creates a deployment now, it's important that help explain how to work with them.

**Comment by AdoHe** [comment]
@sah I think in the HEAD, we have add deployments in help message:
```
# Create a service for an nginx deployment, which serves on port 80 and connects to the containers on port 8000.
kubectl expose deployment nginx --port=80 --target-port=8000`
# If the deployment named mysql's current size is 2, scale mysql to 3.
kubectl scale --current-replicas=2 --replicas=3 deployment/mysql
```
not every command mention deployments, but we did add this.

**Comment by sah** [comment]
Looks like this is indeed fixed in HEAD, but unfortunately didn't make it into 1.2.0, leaving kubectl confusing in that release.

**Comment by nikhiljindal** [comment]
cc @janetkuo @bgrant0607

**Comment by nikhiljindal** [comment]
Added to milestone 1.2 since we will need to cherrypick the fix.

**Comment by bgrant0607** [comment]
Will consider it.
cc @madhusudancs

**Comment by janetkuo** [comment]
Filed #23305 to further update kubectl help docs for 1.2.

**Comment by martinp** [comment]
I'm new to Kubernetes and I'm trying it out on GCE.

I tried following https://github.com/kubernetes/kubernetes/blob/release-1.2/examples/simple-nginx.md and spent a lot of time trying to understand both why no replication controller was created, and why my containers were being recreated while no replication controller existed. Not a good experience.

I think the same applies to https://cloud.google.com/container-engine/docs/tutorials/http-balancer as well.

**Comment by madhusudancs** [comment]
@martinp We are trying to fix (document) this behavior change in the all the examples and docs, but we might have overlooked some of them. I agree that this isn't a good experience. I am sorry about that. Please let us know if you find any more of these docs inconsistencies, we will fix them. We rely on our community's help, so your help is appreciated.

**Comment by madhusudancs** [comment]
@martinp Also, I forgot to mention that I sent a PR (#23524) to fix [examples/simple-nginx.md](https://github.com/kubernetes/kubernetes/blob/release-1.2/examples/simple-nginx.md). I have also sent a fix for https://cloud.google.com/container-engine/docs/tutorials/http-balancer to the GKE team.

**Comment by janetkuo** [comment]
@martinp thanks for your feedback. In 1.2 release, `kubectl run` creates deployments and jobs by default. Please check docs of [deployment](http://kubernetes.io/docs/user-guide/deployments/) and [job](http://kubernetes.io/docs/user-guide/jobs/) for more information.

**Comment by martinp** [comment]
@madhusudancs, @janetkuo: Great, thanks!

**Comment by janetkuo** [comment]
Closing since it's cherry-picked.
