### ISSUE TITLE
kube-up aws with specific us-east-1 region is in loop for ever

### ISSUE THREAD

**Issue by josemolmomillan** [kubernetes/kubernetes#23245]
With release 1.1.8 this setup works correctly, but with 1.2.0 kube-up is in loop constantly. If we change to us-west works correctly, but with us-east-1 dont work

export KUBERNETES_PROVIDER=aws
export KUBERNETES_SKIP_DOWNLOAD=1
export KUBE_AWS_ZONE=us-east-1d
export KUBE_OS_DISTRIBUTION=jessie
export AWS_S3_REGION=us-east-1
 export AWS_S3_BUCKET=prevvy-k8s
export INSTANCE_PREFIX=prevvy_dev

**Comment by justinsb** [comment]
Can you please provide some output, so I can figure out where the loop is?

**Comment by justinsb** [comment]
We're not going to be making further changes to kube-up.  I recommend kops as the natural successor: the ease-of-use of kube-up without many of its shortcomings.  Closing.
