### ISSUE TITLE
Ubuntu Provider is not working

### ISSUE THREAD

**Issue by bpatelcs** [kubernetes/kubernetes#23241]
I have been trying to deploy the kubernetes cluster for ubuntu provider by following the instruction on 
http://kubernetes.io/docs/getting-started-guides/ubuntu, I am getting following error for etcd.

Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused

**Comment by zhouhaibing089** [comment]
@mfanjie maybe you have some experience here..

**Comment by mfanjie** [comment]
the ubuntu provider is developed by ZJU SEL, I successfully deployed that before.
@bparees , if you got problem during the installation, please post more info like how you set your environment variables, and logs during the deployment.
It seems your etcd was not installed properly.

**Comment by bpatelcs** [comment]
I setup three environment variables as described in the instructions,

export KUBE_VERSION=1.1.8
export FLANNEL_VERSION=0.5.0
export ETCD_VERSION=2.2.0


As long as I know we do not need to install etcd , kube-up will download dependencies from declared environment variables, please correct me if I am wrong, which log will help me debug this?

**Comment by DahuK** [comment]
+1, Met the same issue with v1.2.0 and ubuntu provider

**Comment by luguangzhen** [comment]
If your machines are located in a private network that need proxy setting to connect the Internet, mybe you should configure no_proxy.
lgzh@ubuntu:~$ vi .bashrc
 export no_proxy=127.0.0.1,localhost,10.136.XX.XX
lgzh@ubuntu:~$ source .bashrc

Then, validate-cluster is success...

**Comment by rsabir** [comment]
+1, Meet the same issue. @luguangzhen : For me, I have no proxy.

**Comment by tobegit3hub** [comment]
It seems that the scripts may be out-of-date and it doesn't expose `2379` when starting etcd. @resouer

**Comment by kolov** [comment]
I tried to run set up kubernetes on fresh Ubuntu 14.04 and 16.04 servers on Digital Ocean (with private networking) with no success.

If I try user different than root (like vcap in config-default), the script breaks fast with:

    vcap@10.129.12.16's password:
    sh: 4: source: not found  // this originates from cluster/ubuntu/util.sh:471

With root it goes further:

    flanneld.conf  100%  568     0.6KB/s   00:00
    flanneld           100% 2131     2.1KB/s   00:00
    root@10.129.12.16's password:
    Failed to start etcd.service: Unit etcd.service not found.
    Connection to 10.129.12.16 closed.

**Comment by tobegit3hub** [comment]
I got this when following the official tutorial with `KUBE_VERSION=1.1.8`, `FLANNEL_VERSION=0.5.0` and `ETCD_VERSION=2.2.0` in `Ubuntu 14.04`. All the processes seem to run but the final register step fails.

```
etcd start/running, process 6816
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001).
Error:  client: no endpoints available
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
Error:  100: Key not found (/coreos.com) [18]
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
sudo: brctl: command not found
docker stop/waiting
docker start/running, process 7050
Connection to 10.69.1.247 closed.
Validating master
Validating root@10.69.1.247
Using master 10.69.1.247
cluster "ubuntu" set.
user "ubuntu" set.
context "ubuntu" set.
switched to context "ubuntu".
Wrote config for ubuntu to /root/.kube/config
... calling validate-cluster
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 1 registered. Retrying.
......
```

**Comment by resouer** [comment]
ping @dalanlan and @wangzhezhe  to this, could u please take look and see if this scripts needs update?

**Comment by dalanlan** [comment]
@tobegit3hub Hopefully I didn't mis-parse your words, you've managed to set this up right?

From your previous message `sudo: brctl: command not found`, looks like it failed to bring up or down docker0 bridge.

**Comment by dalanlan** [comment]
@kolov

`Failed to start etcd.service: Unit etcd.service not found.`  This is odd. We wanna take care of the setup process of etcd for you and raise it up via a upstart service, you don't need to worry about that.
Could you please kindly check that if all of the config file and scripts are well placed?

And also `After Ctrl-C, retry:..` just ignore those noises come out from etcd, it's unpleasant but fine though. It won't harm much anyway.

**Comment by dalanlan** [comment]
@resouer 
I'll admit we didn't handle a quite good job when it comes to shell, but I guess the main part of the script is, like ok or something.
Truly that we need to update it to a newer releases of k8s and etcd, unfortunately it won't be possible for me to access any available machine to conduct a test as of now. 
For anyone who's interested in this, please kindly take care of the port thing of etcd in the meantime.

**Comment by wangzhezhe** [comment]
I could look at this script to check the port thing when installing the etcd. @resouer @dalanlan

**Comment by tobegit3hub** [comment]
Thanks @dalanlan @wangzhezhe . The log above "brctl" has been be fixed after installing `brctl-utils`. I have installed `docker 1.11.2` and make `/etc/default/docker` can not be modified. I found kubernetes may modify the docker configuration which make it down because of `port in used`.

And the scripts and document work after installing `docker` in advance. I think @bpatelcs @DahuK @rsabir should checkout the logs of `kubelet` and `docker` to figure out the real reason about the failure.

**Comment by dalanlan** [comment]
@tobegit3hub 
Good for you then. We do need to overwrite the config file of docker, cuz we're using flannel. However k8s is totally free of this thing, just pick up whatever you may like when it comes to network setting.

**Comment by kolov** [comment]
@dalanlan 

Scripts are certainly well placed: I start on a pristine Digital Ocean instance and all I do is:
  - git clone https://github.com/kubernetes/kubernetes.git
  - edit config-default.sh: nodes="root@10.129.12.16", role="ai", NUM_NODES=1, ERVICE_CLUSTER_IP_RANGE=0.129.12.0/24
  - passwd root
  - kube-up.sh

About the noices at the and: thee real problems is that the script hangs there, the installation does not finish and no apiserver gets started.

**Comment by dalanlan** [comment]
@kolov 
Ah no, say from the very beginning, you shouldn't be stuck here `Failed to start etcd.service: Unit etcd.service not found.` By config file I mean `init_conf/etcd.etcd.conf` and `init_scripts/etcd`. If `upstart` fails to bring `etcd` up with all of these files properly placed, it's likely that you should check the system log, like `dmsg` maybe?

**Comment by dalanlan** [comment]
About the `hang forever` thing, `apiserver` has a strong dependency of `etcd` for now, you cannot expect it work without that.

**Comment by resouer** [comment]
From a offline talk, I expect @wangzhezhe can work out a way to 1). deploy kubelet as daemons on machines 2). use these kubelet to bootstrap master.  Thus will make ubuntu scripts much simpler I hope.

If anyone see any disadvantage of this self-managed k8s cluster (which is a classical way of the community did today), please let us know.

**Comment by wangzhezhe** [comment]
I tested the scripts on ubuntu 14.04 with kubernetes v1.3.0 , it's ok to deploy this version of kubernetes. I doubted the etcd client may needed some time to send messages into etcd after etcd started (or some other reasons?), after some retries , the scripts could function well.
```
etcd start/running, process 20156
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001).
Error:  client: no endpoints available
Error:  100: Key not found (/coreos.com) [21]
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}

...

Found 1 node(s).
NAME          STATUS    AGE
10.211.55.5   Ready     7m
Validate output:
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   
controller-manager   Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at http://10.211.55.5:8080
```
@kolov @dalanlan

**Comment by kolov** [comment]
I confirm it works with `KUBE_VERSION=1.3.0` - this is great, thanks. Can someone fix http://kubernetes.io/docs/getting-started-guides/ubuntu/ where the default version is `KUBE_VERSION=1.1.8`. I tried to make it first working following the instructions and I started with the versions from the tutorial.

**Comment by Yannovitch** [comment]
I still encounter this issue "Failed to start etcd.service: Unit etcd.service not found" 
(trying to deploy Kubernetes on one node, with master+worker role, Ubuntu 16.04 on a fresh VM)

**Comment by roachmd** [comment]
I've thus far failed at getting the ubuntu provider up. 

I'm attempting to deploy to one node [ ai ] through vagrant.
https://github.com/roachmd/ubuntu-kubernetes-sandbox.

### What I get is this: 
Deploying master and node on machine 10.10.103.250
make-ca-cert.sh                                                                                                                              100% 4136     4.0KB/s   00:00    
easy-rsa.tar.gz                                                                                                                              100%   42KB  42.4KB/s   00:00    
config-default.sh                                                                                                                            100% 3795     3.7KB/s   00:00    
util.sh                                                                                                                                      100%   29KB  28.9KB/s   00:00    
kube-proxy.conf                                                                                                                              100%  688     0.7KB/s   00:00    
kubelet.conf                                                                                                                                 100%  645     0.6KB/s   00:00    
kube-proxy                                                                                                                                   100% 2233     2.2KB/s   00:00    
kubelet                                                                                                                                      100% 2158     2.1KB/s   00:00    
kube-apiserver.conf                                                                                                                          100%  682     0.7KB/s   00:00    
kube-scheduler.conf                                                                                                                          100%  682     0.7KB/s   00:00    
kube-controller-manager.conf                                                                                                                 100%  761     0.7KB/s   00:00    
etcd.conf                                                                                                                                    100%  707     0.7KB/s   00:00    
etcd                                                                                                                                         100% 2073     2.0KB/s   00:00    
kube-controller-manager                                                                                                                      100% 2672     2.6KB/s   00:00    
kube-scheduler                                                                                                                               100% 2360     2.3KB/s   00:00    
kube-apiserver                                                                                                                               100% 2358     2.3KB/s   00:00    
reconfDocker.sh                                                                                                                              100% 2082     2.0KB/s   00:00    
flanneld                                                                                                                                     100%   11MB  10.8MB/s   00:00    
etcdctl                                                                                                                                      100%   12MB  12.1MB/s   00:00    
etcd                                                                                                                                         100%   14MB  13.7MB/s   00:00    
kube-controller-manager                                                                                                                      100%   95MB  94.8MB/s   00:00    
kube-scheduler                                                                                                                               100%   56MB  56.2MB/s   00:01    
kube-apiserver                                                                                                                               100%  105MB 104.6MB/s   00:00    
flanneld                                                                                                                                     100%   11MB  10.8MB/s   00:01    
kube-proxy                                                                                                                                   100%   48MB  48.3MB/s   00:00    
kubelet                                                                                                                                      100%  103MB 102.5MB/s   00:00    
flanneld.conf                                                                                                                                100%  579     0.6KB/s   00:00    
flanneld                                                                                                                                     100% 2121     2.1KB/s   00:00    
flanneld.conf                                                                                                                                100%  570     0.6KB/s   00:00    
flanneld                                                                                                                                     100% 2131     2.1KB/s   00:00    
etcd start/running, process 22754
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001).
Error:  client: no endpoints available
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
Error:  100: Key not found (/coreos.com) [3]
{"Network":"172.16.10.0/24", "Backend": {"Type": "vxlan"}}
{"Network":"172.16.10.0/24", "Backend": {"Type": "vxlan"}}
docker stop/waiting
docker start/running, process 23055
Connection to 10.10.103.250 closed.
Validating master
Validating root@10.10.103.250
Using master 10.10.103.250
cluster "ubuntu" set.
user "ubuntu" set.
context "ubuntu" set.
switched to context "ubuntu".
Wrote config for ubuntu to /root/.kube/config
... calling validate-cluster
The connection to the server 10.10.103.250:8080 was refused - did you specify the right host or port?
(kubectl failed, will retry 2 times)
The connection to the server 10.10.103.250:8080 was refused - did you specify the right host or port?
(kubectl failed, will retry 1 times)
The connection to the server 10.10.103.250:8080 was refused - did you specify the right host or port?
('kubectl get nodes' failed, giving up)

**Comment by Rachitmehrotra** [comment]
Getting same error same thing was working fine with me 30 days back ....

**Comment by kolov** [comment]
I tried on 2 new instances yesterday and I couldn't make it work with any of the tricks mentioned here.

**Comment by life1347** [comment]
@Yannovitch @kolov 

for people that encounter the problem 
`
Failed to start etcd.service: Unit etcd.service not found.
`

16.04 use systemd to manage service, the following config should solve the problem.

/etc/systemd/system/etcd.service
```
[Unit]
Description=etcd key-value store
Documentation=https://github.com/coreos/etcd
After=network.target

[Service]
User=etcd
Type=notify
Environment=ETCD_DATA_DIR=/var/lib/etcd
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd
Restart=always
RestartSec=10s
LimitNOFILE=40000

[Install]
WantedBy=multi-user.target
```

https://github.com/coreos/etcd/blob/master/contrib/systemd/etcd.service

**Comment by dalanlan** [comment]
Seems that we've got a brand new way to bootstrap a kubernetes cluster in v1.4. Let's move on folks!

**Comment by amolsh** [comment]
I am getting same issue "Failed to start etcd.service: Unit etcd.service not found" 
OS: Ubuntu 16.04 
Anyone know it's root cause?

**Comment by resouer** [comment]
The ubuntu scripts does work for systemd

**Comment by chinmayb** [comment]
@amolsh same

**Comment by undassa** [comment]
@amolsh @chinmayb 
It seems that you have no etcd installed. 
`sudo apt-get install etcd`

Than check that etcd is started
`sudo service etcd start`
`sudo service etcd status`

And after that repeat kube-up.sh

**Comment by mancubus77** [comment]
Folks,
Any ideas about 
`Unit etcd.service not found `
Can not find a solution for a long time

**Comment by noahzaozao** [comment]
Failed to start etcd.service: Unit etcd.service not found.
I met the same error when I'm using a ubuntu16.04 desktop on laptop without VM.

**Comment by resouer** [comment]
@noahzaozao current ubuntu scripts does not support systemd based Ubuntu version i.e. distro newer than 15.04 , I have no enough bandwidth to update it but if you (or any one else) are interested in to make it work I can definitely get it in.

**Comment by resouer** [comment]
Otherwise, I would suggest use `kubeadm` for any deployment requirement on latest distro.

**Comment by hxquangnhat** [comment]
I made `etcd` run with `systemctl enable etcd`, check it `status` and try to `restart` if it is not running.

**Comment by castrojo** [comment]
/close 

I'm going to close this issue, if someone runs into this and wants to update the manual guide please open at PR against: https://github.com/kubernetes/kubernetes.github.io

Thanks!
