### ISSUE TITLE
GCE PD driver should be mounting with `discard` (TRIM support) when mounting an FS that supports it

### ISSUE THREAD

**Issue by orospakr** [kubernetes/kubernetes#23258]
GCE PD docs [recommend using the `discard` option](https://cloud.google.com/compute/docs/disks/persistent-disks#formatting) so unused blocks can be freed back into the cloud and performance gains realized.

Rummaging through the source of the GCE PD and mounter stuff in Kube, it does not appear that that's being done (the old shell script version of safe_format_and_mount does, but I don't think that's used).

I haven't confirmed that it's the case at runtime for sure, though, although I will be able to shortly.

**Comment by matchstick** [comment]
@orospakr @pmorie @saad-ali @ciwang 

I LGTMed the PR and then realized it needed more work. Reverting it and assigning it to ciwang. 

We need to make sure that we only use the "discard" mount option when the fs supports it.
Assigning to ciwang for now. If anyone else wants to work on it feel free to grab it.

**Comment by matchstick** [comment]
Assigning to @saad-ali. This fell through the cracks as ciwang was working in other areas.
This did not make 1.4 either moving to next-candidate.
