### ISSUE TITLE
AWS: We require the DescribeLoadBalancers permission

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23257]
@mzupan reported that: Even if we aren't using services with type=LoadBalancer, we still require the DescribeLoadBalancers permission (I believe so that we can delete any ELB).

https://github.com/kubernetes/kubernetes/issues/22906#issuecomment-198941460

**Comment by bprashanth** [comment]
Suggest modifying title to reflect that only the master needs it (or clarify that all nodes need it, but I don't see why that would matter).
 
Is there a possibility of qps blacklisting of the project for too many failed requests? -- theoretically, i know we put in backoff.
