### ISSUE TITLE
AWS: Public IP warning every second

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23256]
@mzupan reported that the "no public IP" warning was being logged every second.  It should not be logged that often:
https://github.com/kubernetes/kubernetes/issues/22906#issuecomment-198935575

**Comment by jsravn** [comment]
I think the warning is silly anyways, can we just remove it, or reduce its level? (any node in an internal VPC logs this)

**Comment by jsravn** [comment]
/close

was fixed.
