### ISSUE TITLE
Kubelet I/O usage abnormally high

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#23255]
After upgrading to Kubernetes 1.2.0, kubelet's `du` sub-process is using 95-99% of my read I/O constantly:

```
$ iotop
Total DISK READ :     321.10 K/s | Total DISK WRITE :      10.76 M/s
Actual DISK READ:     321.10 K/s | Actual DISK WRITE:       4.24 M/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN      IO    COMMAND
18979 be/7 root      321.10 K/s    0.00 B/s  0.00 % 99.12 % du -s -B 1 /
27430 be/4 9999        0.00 B/s    6.49 M/s  0.00 % 31.45 % Passenger RubyApp: /app/public (production) [utils.rb:110]
14566 be/4 9999        0.00 B/s    3.82 K/s  0.00 %  0.00 % nginx: worker process
14639 be/4 9999        0.00 B/s    3.82 K/s  0.00 %  0.00 % nginx: worker process
```

```
$ ps axjf | grep 18979 -B 2
    1  7889  7889  7889 ?           -1 Ssl      0   3:16 /opt/bin/kubelet --api-servers=https://k8s.example.com --config=/etc/kubernetes/manifests --cloud-provider=aws --cluster-dns=10.10.0.10 --cluster-domain=cluster.local --image-gc-high-threshold=70 --image-gc-low-threshold=50 --maximum-dead-containers=15 --allow-privileged=true --v=2
 7889  8030  7889  7889 ?           -1 S        0   0:01  \_ journalctl -k -f
 7889 18979  7889  7889 ?           -1 DN       0   0:08  \_ du -s -B 1 /
```

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.4G     0  7.4G   0% /dev
tmpfs           7.4G     0  7.4G   0% /dev/shm
tmpfs           7.4G  3.0M  7.4G   1% /run
tmpfs           7.4G     0  7.4G   0% /sys/fs/cgroup
/dev/xvda9       56G   33G   21G  62% /
/dev/xvda3      985M  551M  384M  59% /usr
tmpfs           7.4G     0  7.4G   0% /media
tmpfs           7.4G     0  7.4G   0% /tmp
/dev/xvda1      128M   66M   63M  52% /boot
/dev/xvda6      108M   60K   99M   1% /usr/share/oem
```

**Comment by AdoHe** [comment]
@kubernetes/sig-node

**Comment by antoineco** [comment]
Please note that the maximum disk read speed is low in the figures I posted above because AWS throttles I/O operations when these get abnormally high for a certain period of time (~ 1 hour). Before that my read I/O was capped at ~8 MiB/s for an hour (600,000 IOPS). Looks like this `-B 1` flag is too aggressive for some environments.

My instances are running on Amazon's SSD, which are limited to 20,000 IOPS. This should be comfortable enough for running Kubernetes, at least it was before v1.2.0.

![screenshot from 2016-03-20 17-58-20](https://cloud.githubusercontent.com/assets/3299086/13907592/e9dc3956-eef1-11e5-9fd2-3aa6b3571753.png)

**Comment by antoineco** [comment]
Apparently this is not related to garbage collection. With `--image-gc-high-threshold=90` and `--image-gc-low-threshold=80` (and a disk ~50% full) the `du` command [still kicks in](https://github.com/kubernetes/kubernetes/blob/11cdc919f50ae632871f45ad19eb3628729de7d5/pkg/volume/util/fs_linux.go#L48-L61), with the same consequences.

I updated my original comment.

**Comment by antoineco** [comment]
I managed to narrow it down even more. My monitoring agent pods mount the entire FS of the host they run on as a read-only hostPath volume:

```yaml
          volumeMounts:
          - mountPath: /host
            name: rootfs
            readOnly: true
        volumes:
        - hostPath:
            path: /
          name: rootfs
```

After disabling it everything is back to normal, this is just a temporary workaround though.

**Comment by timstclair** [comment]
@vishh - Do you think it makes sense to disable collecting disk usage for read-only filesystems?

**Comment by vishh** [comment]
@timstclair: Yes. It does make sense.

**Comment by vishh** [comment]
@timstclair: Read-only filesystem is only one kind of pitfall. We are currently vulnerable to any container that mounts the root filesystem. We need to ideally ignore mounts while calculating disk usage.

**Comment by vishh** [comment]
Filed https://github.com/google/cadvisor/issues/1173

**Comment by jeremyeder** [comment]
Very interesting, thanks for cc'ing me.

**Comment by vishh** [comment]
@timstclair @antoineco: cAdvisor does not enter the container's filesystem. It attempts to compute disk usage of just the top most writable layer.

**Comment by ncdc** [comment]
@timothysc @jeremyeder this shouldn't affect RHEL/devicemapper, especially if we're using the journald logging driver for Docker.

**Comment by vishh** [comment]
Kubelet accounts host path volumes and that is the root cause. Running `du` on host path could result in a loop.

**Comment by ncdc** [comment]
Ah, my bad. I assumed this was from cadvisor's accounting.

**Comment by vishh** [comment]
@ncdc: Apologies for misguiding early on. This is an issue in kube v1.2. I'm working on a patch.

**Comment by robinmonjo** [comment]
I'm experiencing the same kinds of issue with kubernetes 1.5.2 installed with kops on AWS. I have periods where some of my nodes get crazy with iops. Here is what I see:

<img width="1280" alt="screen shot 2017-03-21 at 22 34 59" src="https://cloud.githubusercontent.com/assets/1815076/24191947/b20ec72e-0eed-11e7-9490-16a7330ef37c.png">

So `du` take all my iops in the docker overlay directory.  Here is what the kubelet logs display:

````
fsHandler.go:131] du and find on following dirs took 4.22914425s: [/var/lib/docker/overlay/592c1d88d1fd115f21e8fe6f198a8a27cd44efefb9b5dc58940fbf6d7999eda3 /var/lib/docker/containers/2347d28886bc0e6b74fc326538e1483927ddeb89b38e035acd845d5db621cb79]
fsHandler.go:131] du and find on following dirs took 24.94283434s: [/var/lib/docker/overlay/81f24df3624ebf7b7e45edc38fafeb41958bc675ae57fd0126c44cb2c3a6d6d6 /var/lib/docker/containers/43d576931081500fd4cd316afe5bfc6ff2442ff20e8e8266c27e930a0a77dd34]
fsHandler.go:131] du and find on following dirs took 18.478782737s: [/var/lib/docker/overlay/422ef31413df4e76de51acaa7d6ff6f77edc65fabde88a7c70e7edad3b1e55e5 /var/lib/docker/containers/1519a33729c8fb13297358edc53fe22f0b4b684636884976dfcb67c47fbf320b]
helpers.go:101] Unable to get network stats from pid 13515: couldn't read network stats: failure opening /proc/13515/net/dev: open /proc/13515/net/dev: no such file or directory
fsHandler.go:131] du and find on following dirs took 7.971745844s: [/var/lib/docker/overlay/45b83939bd1b4ec7dfa627bb6a9eb8b89a380007f9e22a93fff2ba4054252271 /var/lib/docker/containers/f6d3387423398d7dd4fac6c19ee0a1446d0465b5f9cf90289fcd605ad28c0d6e]
fsHandler.go:131] du and find on following dirs took 5.886763577s: [/var/lib/docker/overlay/8c01a73671eedb2e62c58fa12fc2d25df58c506545b6ea048fa0db1756d19f2c /var/lib/docker/containers/1d9c0ebcc6dbbd7065923f7f81c05c0d9d710aed0d353a1bab90ce1c994dfb57]
fsHandler.go:131] du and find on following dirs took 5.714942029s: [/var/lib/docker/overlay/26213ba30a17f240a9b9756a0d23ab32550f921de533667c9ab91cfb7f10ed5b /var/lib/docker/containers/7c27c242a49d8d33cee8b2e8335dae450af13b26f010794dc83ef5750a212d0d]
fsHandler.go:131] du and find on following dirs took 6.111478835s: [/var/lib/docker/overlay/0fe2bd0feeda24699bd6d443ca126ac1a33071cdff039ae9fd9159bbef80867b /var/lib/docker/containers/ec6fb966139e9666ec0be5e13399773f1971ddd99841b84167a7463402e28d73]
fsHandler.go:131] du and find on following dirs took 2.661604836s: [/var/lib/docker/overlay/04f9d01a8863cfee26e678e938fced84f826dda6ed03626dda11b6aad6901465 /var/lib/docker/containers/a4e37aee69c7523c46c5252c1834fa3fcd5a804a7aee256a468e44b4d6bcbd64]
fsHandler.go:131] du and find on following dirs took 11.834409809s: [/var/lib/docker/overlay/4cb1476621b90e2c2ee2b1131c0e6ac62f62dc3ca418129812b487bffac1d827 /var/lib/docker/containers/5a01521cfdd3041aff128dce7353ab336ddafa60c8c0b2254fb6bae697cb1676]
````

I asked for help on stackoverflow but didn't get any feedback: http://stackoverflow.com/questions/42753567/kubernetes-node-high-disk-io-and-cpu-usage

**Comment by vishh** [comment]
cc @dashpole We are working on some optimizations to alleviate `du` issues.

**Comment by dashpole** [comment]
@robinmonjo I would love more information, if you are willing to share.  How large are the container's writable layers that are taking that long?  Do you have lots of smallish files, or just a couple larger files, or some of each?

**Comment by robinmonjo** [comment]
Thank you for being interested in my problem :) I would love to share !!

- First can you tell me why the kubelet launch the `du` command ? What is the purpose ? When does it happens ?

> How large are the container's writable layers that are taking that long?

I'm missing some context on why the kubelet is doing this to tell you exactly which containers causes the issue, but I can give you more general info on my cluster:

- 3 nodes cluster running on EC2 m4.xlarge with 70Gb disk provisioned at 1500 iops
- my cluster runs rails and nodejs apps + a bunch of redis database (redis:alpine docker image)
- all our apps are deployed with deis workflow so they run in the [deis slugrunner image](https://github.com/deis/slugrunner)

I'll probably be able to give you more details when I better understand what the kubelet is tryinng to accomplish :)

**Comment by dashpole** [comment]
> First can you tell me why the kubelet launch the du command ? What is the purpose ? When does it happens ?

We run 'du' on each container's writable layer, and on each empty-dir-volume's directory in order to get disk usage metrics containers and volumes.  We use this information largely to determine which pod to evict if we are under disk pressure.  We also expose these metrics as part of the summary API (/stats/summary).

It is very possible that running 'du' on large directories with lots of files can use up a lot of iops, although this is the worst I have seen.

**Comment by robinmonjo** [comment]
@dashpole, I have more info on my container causing the issue. It is the container that runs our biggest app (a rail + react app, bundled in a unique container). We have 15 containers of this app running simultaneously on our cluster. 

This app is packaged by a heroku buildpack so everything is packaged (gem npm packages, ruby ...). When I run `du` manually in the upper container directory, it is indeed very slow. So to answer your question it's mostly small files (`du -h` returns 7109 lines).

This is really affecting our production setup. Any short term workaround ?

**Comment by dashpole** [comment]
@robinmonjo i'm afraid i'm not aware of a workaround right now, other than increasing iops.  This is a known issue, but without an easy solution since the Kubelet needs those stats to function.  In the future, the solution will be to use a local persistent volume, but sadly that is a long way off.

Another possibility would be to use remote storage mounted as a volume, but it sounds like this may be too slow for your use cases.

**Comment by vishh** [comment]
The easiest solution would be that of using SSDs as your primary storage.
Is that an option for you?

**Comment by tsuna** [comment]
Why not put everything in RAM while you're at it.  Seriously, recommending to use an SSD is not an option.  We have hundreds of spinning HDDs and they are currently kept spinning all the time by `du` commands.

**Comment by vishh** [comment]
@dashpole worth considering adding an opt-out for disk stats collection. If users do not specify disk based evictions, then we can entirely disable disk metrics collection.

**Comment by dashpole** [comment]
@vishh They could still have disk-based evictions, it would simply evict based on QoS, but not usage.

Another possible workaround, if most of your disk usage is volume-based, would be to [disable volume disk stats collection](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L233) by setting the period to 0.  If all of the usage is in container writable layers, moving some of the largest users of disk space from the writable layer to volumes could also help.

**Comment by mirath** [comment]
Is there an issue open for the du processes eating up IO? I don't know if the issue is resolved as this issue is close, or if there is no open issue to begin with

**Comment by dashpole** [comment]
I dont see any issues directly related to diskio, but https://github.com/google/cadvisor/issues/735 has been open for a long time and is related to CPU usage.

**Comment by mirath** [comment]
So the issue highlighted by @robinmonjo is not resolved I assume. Is there a timeline for a fix?

**Comment by antoineco** [comment]
This issue is closed and a patch was submitted for it. The context I described above was different since the high read I/O I observed in v1.2.0 was being triggered by a host mount (the entire `/` partition to be more precise). 

I think the best way to bring attention to this "new" problem is to open a new issue with the details of what's happening.

**Comment by markhilton** [comment]
The high IO usage due to running "du" happens to my AWS KOPS k8s 1.9 cluster. My deployments are mostly PHP apps, running inside pods with multiple containers (php-fpm & nginx). 

Since both containers require access to the application code, I deploy it from a separate app image, which then runs as an init container to copy the app code into an EmptyDir volume. 
I take that even on SSD drives this process takes several seconds per each pod to deploy and creates IO activity. 

Now imagine several deployments simultaneously when horizontal scaler starts deploying new pods. That plus "du", plus NewRelic daemon running on each node which I use to monitor the infrastructure (also seems to be mounted to host root) effectively brings down the node and renders it as unresponsive. Basically, an avalanche of IO activity can easily bring down the cluster with minimal CPU or memory usage.

I'm looking forward to KOPS 1.10 release and in the meantime updating deployments to use new Docker image with application code already baked into the php-fpm image, in order to avoid creating EmptyDir volumes. I also tried with memory EmptyDir, but it did not help.

Kubernetes is lacking a "container as a volume" feature in my view.

**Comment by markhilton** [comment]
I was able to resolve the issue by editing kops cluster.spec with `kops edit cluster [cluster_name]`.
I added following under specs:
```
  docker:
    logDriver: json-file
    logLevel: warn
    storage: overlay2
```
It looks like by default kops configures docker to use overlay as default storage driver, while docker recommends using overlay2 as newer, more stable and faster.

**Comment by 0312birdzhang** [comment]
Change `overlay` to `overlay2` not works for me, i'm sure the issue still there.

**Comment by lastboy1228** [comment]
set volume-stats-agg-period to 0
