### ISSUE TITLE
Fixing scheduler benchmark

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#23263]
Even though existing scheduler benchmark showed almost linear scheduling rate, in kubemark density test we didn't see as huge improvement.

This is caused by the discrepancies between scheduler benchmark and density test in mostly two places:

- [ ] Replication controller: 
  - Scheduler benchmark creates pod one by one. See [here](https://github.com/kubernetes/kubernetes/blob/e664ef922fd3ecc2dcb692c8d012950cd4646af6/test/component/scheduler/perf/util.go#L115). Density test creates pods by using replication controller. See [here](https://github.com/kubernetes/kubernetes/blob/9a71dfe753b4e67016f306ac18d6a27698f4517b/test/e2e/density.go#L303). 
  - This affected how SelectorSpreadPriority made calculation and in Kubemark we saw it's the largest time consumer.
- [ ] Port: 
  - Scheduler benchmark creates pod without specifying port. Density test specifies ports. See [here](https://github.com/kubernetes/kubernetes/blob/4402e57588522d6d94870a86ed494e3c1fbd479e/test/e2e/util.go#L1833).
  - This affected how PodFitsHostPort() predicate made calculation and in Kubemark we saw it's the second largest time consumer.

Meanwhile, there is one left issue in scheduler benchmark we should fix:

- [ ] Avoid scheduling path in pod setup. In some benchmarks, we want to see scheduling behavior when  a number of pods have been scheduled. Currently the setup needs go through scheduling. See [here](https://github.com/kubernetes/kubernetes/blob/e664ef922fd3ecc2dcb692c8d012950cd4646af6/test/component/scheduler/perf/scheduler_bench_test.go#L57-L64). It's unnecessary and time consuming, and most importantly, stopping us from making large setup.

We are planning to fix these and improve scheduler performance in 1.3 timeline.

**Comment by xiang90** [comment]
Sure, we can add different types of micro-benchmarks and try to match the results of other e2e tests. These are useful to analysis any performance decrease or catch some low hanging fruits for performance improvement.

But as we discussed a few months ago, I think the only way to make scheduler benchmark meaningfully is to get the trace of real workload or at least simulate the real world workload.

**Comment by wojtek-t** [comment]
>
But as we discussed a few months ago, I think the only way to make scheduler benchmark meaningfully is to get the trace of real workload or at least simulate the real world workload.

In general I agree, but we cannot have benchmark that is using different priority functions that we are using in production. So we should definitely fix at least that one.
