### ISSUE TITLE
kube-up (GCE & AWS) should not delete the CA Key

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23264]
kube-up currently deletes the SSL CA Key, after kube-up finishes (because it runs easyrsa in a temporary directory).

This will make it impossible to generate more trusted certs in future, for example to rotate the kubelet / kubecfg / master keys.

We also don't have a great way to push a new CA cert right now (it's possible, but I think it would be very tricky).

I think we should probably include the CA key into the master metadata, given that we include some keys that give full permissions anyway.  But we should probably fix this properly in 1.3

**Comment by ScubaDrew** [comment]
@justinsb -- Is there a way to use your own keys for the master HTTPS using Kube-Up?

**Comment by justinsb** [comment]
@ScubaDrew not in kube-up.

Given that kube-up is now in maintenance mode, I'm inclined to close this issue.

**Comment by roberthbailey** [comment]
@mikedanese -- didn't we fix this?

**Comment by mikedanese** [comment]
Yes.
