### ISSUE TITLE
confused apiserver.Mux usage

### ISSUE THREAD

**Issue by adohe** [kubernetes/kubernetes#23266]
In apiserver.go, we define a `Mux` interface:

```
// mux is an object that can register http handlers.
type Mux interface {
    Handle(pattern string, handler http.Handler)
    HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
}
```

we use this in `genericapiserver.go`:

```
mux := http.NewServeMux()
s.mux = mux

handler := http.Handler(s.mux.(*http.ServeMux))
```

I can't see why we have to use `apiserver.Mux` here, I think `http.ServerMux` is enough.

**Comment by zhouhaibing089** [comment]
Yes, `http.ServerMux` implements `apiserver.Mux`, however, I am guessing that maybe it is some kind of narrowing dependency, we only need an interface `apiserver.Mux` with these only two methods, not all of the methods in `http.ServerMux`.

Kind of guessing, :)

**Comment by sttts** [comment]
As far as I see `apiserver.Mux` is only used to abstract away the `MuxHelper` such that one can pass either `MuxHelper` or `http.ServeMux` e.g. to `InstallVersionHandler`.
