### ISSUE TITLE
verify-godep-licenses.sh fails in kubernetes-test-go

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#23268]
cc: @ixdy

**Comment by ixdy** [comment]
The issue is that `hack/update-godep-licenses.sh` looks for remote files at `master`, so this is going to keep failing.

We should probably use the revision we've specified in the Godeps instead. This is an easy fix.

cc @david-mcmahon @karlkfi @eparis

**Comment by ixdy** [comment]
... though I'm realizing that several of packages didn't have LICENSEs at the version we've imported. Arguably we should not have introduced them without a license.

**Comment by ixdy** [comment]
Looking at the code further, I think we only try to look for files at master if they don't exist in the local Godeps tree. So it's not as bad as I first thought, but it's still likely to spontaneously break.

**Comment by david-mcmahon** [comment]
So this is still still failing despite https://github.com/kubernetes/kubernetes/pull/23164 ?
If that's the case, we might want to implement the previously considered option of creating a parallel _workspace tree to locally hold the license and copyright files that godeps doesn't want to get.  This would eliminate the need to look on the interwebs for missing items (at least until another package is introduced).  If this continues to be an ongoing problem, please file an issue to me.

**Comment by ixdy** [comment]
@david-mcmahon we started failing at 3:54pm on March 20 with
```
Verifying ./hack/../hack/verify-godep-licenses.sh
Created workspace: /go/src/k8s.io/kubernetes/kube-godep-licenses.UN1frb
Your godep licenses file is out of date. Run hack/update-godep-licenses.sh and commit the results.
--- /go/src/k8s.io/kubernetes/Godeps/LICENSES	2016-03-20 15:55:11.533682720 -0700
+++ /go/src/k8s.io/kubernetes/kube-godep-licenses.UN1frb/Godeps/LICENSES	2016-03-20 16:04:45.138034502 -0700
@@ -23768,6 +23768,12 @@ the --go_out argument to protoc:
 
 	protoc --go_out=plugins=grpc:. *.proto
 
+## Plugins ##
+
+The `protoc-gen-go/generator` package exposes a plugin interface,
+which is used by the gRPC code generation. This interface is not
+supported and is subject to incompatible changes without notice.
+
 ================================================================================
 = Godeps/_workspace/src/github.com/google/btree licensed under: =
 
Removing workspace: /go/src/k8s.io/kubernetes/kube-godep-licenses.UN1frb
FAILED   ./hack/../hack/verify-godep-licenses.sh	11s
```

which was due to https://github.com/golang/protobuf/commit/2fea9e168bab814ca0c6e292a6be164f624fc6ca.

I'm worried that downloading from `master` for a lot of these files (especially `README`s) means we're going to frequently break.

**Comment by david-mcmahon** [comment]
The script generates `LICENSES` using local files under Godeps/ or pulls upstream copies.  `hack/verify-godep-licenses.sh` run from `hooks/pre-commit` will do the right thing and catch these updates, but #22681 short-circuits that check by requiring that Godeps/ has changed.  That isn't valid in this new world where we are pulling down the latest lawyer docs from upstream.  

A couple of options:

1. Quick fix - Undo the check that skips verifying if no Godeps/ changes happened.  `hack/update-godep-licences.sh` runs faster now than its predecessor despite grabbing everything from upstream and generating a complete license and copyright text file (vs. a list of some of the licenses). `hack/verify-godep-licenses.sh` runs in 17 seconds which isn't bad at all.

2. Bigger and more complex fix - Store the missing files pulled from upstream in a parallel directory (thank you godeps), making everything 'local' and no more surprises from upstream.

So 1 will solve the immediate issue. File an issue if we want to go the 2 route.

**Comment by david-mcmahon** [comment]
I guess this is happening because KUBE_FORCE_VERIFY_CHECKS is set in when running `verify-godep-licenses.sh` the CI builds but not in pre-commit?

**Comment by ixdy** [comment]
Correct. Without that, `hack/verify-godep-licenses.sh` would never run in CI, since we are effectively checking the branch against itself for Godeps changes.

**Comment by ixdy** [comment]
Also, the check is intermittently flaking, even with #23164.
https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-test-go/9969 and https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-test-go/9974 are two recent flakes.

**Comment by david-mcmahon** [comment]
So if we just force KUBE_FORCE_VERIFY_CHECKS=y (in pre-commit), then the files will not look out of date when they hit the CI.

**Comment by david-mcmahon** [comment]
re: https://github.com/kubernetes/kubernetes/issues/23268#issuecomment-200069282, what am I looking at there? :)

**Comment by ixdy** [comment]
Setting `KUBE_FORCE_VERIFY_CHECKS=y` in pre-commit means that PRs will randomly start failing when our Godeps licenses change, even if the PRs don't touch Godeps. I don't think that's really improving things.

In the two builds I linked, `hack/verify-godep-licenses.sh` flaked because it appears to have failed to download the remote files.

**Comment by david-mcmahon** [comment]
Yes, it would then put the burden of keeping the LICENSES file up to date effectively on everyone.  And based on what I've seen so far, the missing upstream licenses and copyrights we're pulling are changing fairly often.  

The good news is I took a closer look and it's a relatively easy fix to write the parallel tree and sync the full state.  I'll send a PR shortly.

**Comment by eparis** [comment]
Great! 17 seconds to `git commit` didn't seem acceptable to me.

**Comment by ixdy** [comment]
@eparis verify-godep-licenses is hardly the worst offender... there are several verify- checks which take O(minutes).

**Comment by david-mcmahon** [comment]
If you didn't like 17 seconds, you would really hate how long it took when verify-* and update-* were calling out to https://github.com/mesosphere/godep-licenses.  That took just under a minute and only generated a list of a subset of licenses, rather than the entire set of full text.

And worse than that, have you run a `git commit` with the pre-commit hook (lately)?  That runs a ton of things, to ixdy's point, and takes a few minutes at least.  That's an area that needs some work.  I suspect lots of people skip that for just that reason.
