### ISSUE TITLE
Introducing protobuf tags changes behavior api.ObjectMetaFor

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#23278]
After running protobuf generator some unit tests are not passing, e.g.: TestAnnotateObjectFromFile

I did some debugging and the issue is basically, that (at least in this particula case):
  api.ObjectMetaFor(&v1.Pod{})
returns:
  unexpected error: couldn't assign/convert *v1.ObjectMeta to *api.ObjectMeta

The reason for that is that:
https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/helper.go#L52

underlying is calling:
ConvertibleTo:
https://github.com/golang/go/blob/f2772a49353e09e4e00121ca4e538a3b3302a1de/src/reflect/type.go#L97

And the issue is that ConvertibleTo requires tags for all fields to be exactly the same:
https://github.com/golang/go/blob/f2772a49353e09e4e00121ca4e538a3b3302a1de/src/reflect/type.go#L1410

So we:
- either need to generate tags also for internal types
- review all usecases of ConvertibleTo in our code and change it to our custom code

I think the first one is much better.

@smarterclayton - thoughs?

**Comment by smarterclayton** [comment]
Is that the struct tag?  Go requires it to be equal?  That's insane....

**Comment by smarterclayton** [comment]
Why in the world would the struct tag have anything to do with convertible to?

**Comment by wojtek-t** [comment]
>
Is that the struct tag? Go requires it to be equal? That's insane....

I agree, but that's what I see in the Go code:
https://github.com/golang/go/blob/f2772a49353e09e4e00121ca4e538a3b3302a1de/src/reflect/type.go#L1410

**Comment by wojtek-t** [comment]
@smarterclayton - any thoughts on how to proceed - my suggestions were:
- either need to generate tags also for internal types
- review all usecases of ConvertibleTo in our code and change it to our custom code

I agree that's insane in Go, but this is what already exists and we cannot change it.

**Comment by smarterclayton** [comment]
The latter seems more correct to me - generating tags for internal types
isn't really solving the problem, it's pretending it doesn't exist.  If we
are dependent on ConvertibleTo working correctly, we should probably make
it work correctly (by having an equivalent).

**Comment by smarterclayton** [comment]
If ConvertibleTo doesn't work, don't we fall back to field by field casts?

**Comment by wojtek-t** [comment]
Not in this particular case that I found:
https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/helper.go#L66

But now, when I'm looking into it, this code actually looks incorrect for me. We are not even trying to convert it using our Converter, which I think we should.

I will try to fix it tomorrow.

**Comment by smarterclayton** [comment]
Although that code is infrequently called, and is assumed to be about
internal classes mostly.

**Comment by wojtek-t** [comment]
@smarterclayton - in general yes, but it seems we leaked it to some places.
I will try to fix it today.

**Comment by wojtek-t** [comment]
hmmm - I spent some time trying to fix it today and failed.

Basically the problem is that api.ObjectMetaFor:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/meta.go#L42

is supposed to return a pointer to the ObjectMeta which can then be modified.
Thus changing it to our own conversions will not work, because it will be a copy.

So the only reasonable approach that I can currently see (other than generating tags for internal types) is to actually fork the go code that is doing the conversion and change it to not look into tags.
@smarterclayton @lavalamp - what do you think?

BTW - how I wanted to solve it (but it doesn't work) is here:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:fix_convertible?expand=1

**Comment by smarterclayton** [comment]
ObjectMetaFor ConvertibleTo should only work on internal types anyway,
right?  It's only ConvertibleTo during reflection conversion or defaulting
that is the problem?

**Comment by wojtek-t** [comment]
>
ObjectMetaFor ConvertibleTo should only work on internal types anyway,
right?

Yes - it works fine for internal types.
The problem is that we are calling it for non-internal types, example is:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/annotate.go#L329

**Comment by smarterclayton** [comment]
Ah, the expectation was that you would never call that on external types.
It was before we started using external types in our code.

**Comment by lavalamp** [comment]
We should NOT generate tags for internal structs, I think.

Ways to fix this, from grossest to least gross:

* Use unsafe package to fool the type system
* Fork reflect, remove check, like you say (I think part of reflect may already be forked in third_party? need to check)
* Use the external ObjectMeta even on our internal objects? (but I haven't thought this through...)

**Comment by lavalamp** [comment]
So the language itself (compiler) considers structs that differ only in tags to still not be convertible: https://golang.org/src/go/types/predicates.go#L165

Confirmed: https://play.golang.org/p/j5Bn_4TJKO

What is the justification for this? It seems unhelpful. I can't find anything in the language spec that would explain this. Maybe we should file an issue with the go team? @rsc, is there any chance we could convince the go team to drop this requirement from struct conversions?

**Comment by rsc** [comment]
This is golang/go#6858 (old but a few recent messages). Mainly we haven't
heard a good reason to make an exception for the struct tags yet. It just
hasn't come up much. Please comment there about why this change would be
useful for you. Thanks very much.

**Comment by wojtek-t** [comment]
I added comment in golang/go#6858
However, for now we need to workaround it (even if it will be changed in Go, we will need it pretty soon for protobuf support).

I'm going to try to fork the necessary parts of reflect to our forked third_party to try to fix that.

Regarding your idea about using external ObjectMeta even on internal objects - I think that would be much bigger change. And if there is a chance that with never versions of Go we it will be fixed, it doesn't make sense to invest much into it.

**Comment by wojtek-t** [comment]
hmmm  - I spent 2 hours trying to fork the reflect code and failed.

First, since ConvertibleTo() is a method on Type, we actually cannot fork just this function - we basically need to fork the whole "reflect" package.
Second, even if we fork the whole package, there are some magic constructs there, that make the code non-compiling. As an example there is:
"typedmemmove"
function that has just defined a signature and is not defined anywhere is this package.

To be honest, I have no idea how to workaround it.

For completeness, this is how I was trying to do it:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:fix_convertible_to?expand=1

And while compiling I'm getting errors as following:

    k8s.io/kubernetes/third_party/forked/reflect.packEface: call to external function k8s.io/kubernetes/third_party/forked/reflect.unsafe_New
    k8s.io/kubernetes/third_party/forked/reflect.callMethod: call to external function k8s.io/kubernetes/third_party/forked/reflect.typedmemmovepartial
    k8s.io/kubernetes/third_party/forked/reflect.Value.Cap: call to external function k8s.io/kubernetes/third_party/forked/reflect.chancap
    k8s.io/kubernetes/third_party/forked/reflect.Value.Close: call to external function k8s.io/kubernetes/third_party/forked/reflect.chanclose
    k8s.io/kubernetes/third_party/forked/reflect.Value.Len: call to external function k8s.io/kubernetes/third_party/forked/reflect.chanlen
    k8s.io/kubernetes/third_party/forked/reflect.Value.MapKeys: call to external function k8s.io/kubernetes/third_party/forked/reflect.maplen
    k8s.io/kubernetes/third_party/forked/reflect.Value.Set: call to external function k8s.io/kubernetes/third_party/forked/reflect.typedmemmove
    k8s.io/kubernetes/third_party/forked/reflect.Value.SetMapIndex: call to external function k8s.io/kubernetes/third_party/forked/reflect.mapdelete
    k8s.io/kubernetes/third_party/forked/reflect.typesByString: k8s.io/kubernetes/third_party/forked/reflect.typelinks: not defined
    k8s.io/kubernetes/third_party/forked/reflect.packEface: k8s.io/kubernetes/third_party/forked/reflect.unsafe_New: not defined
    k8s.io/kubernetes/third_party/forked/reflect.packEface: k8s.io/kubernetes/third_party/forked/reflect.typedmemmove: not defined
    k8s.io/kubernetes/third_party/forked/reflect.Value.call: k8s.io/kubernetes/third_party/forked/reflect.typedmemmove: not defined
    k8s.io/kubernetes/third_party/forked/reflect.Value.call: k8s.io/kubernetes/third_party/forked/reflect.call: not defined
    k8s.io/kubernetes/third_party/forked/reflect.Value.call: k8s.io/kubernetes/third_party/forked/reflect.memclr: not defined
    k8s.io/kubernetes/third_party/forked/reflect.Value.call: k8s.io/kubernetes/third_party/forked/reflect.memclr: not defined
    k8s.io/kubernetes/third_party/forked/reflect.Value.call: k8s.io/kubernetes/third_party/forked/reflect.unsafe_New: not defined
    k8s.io/kubernetes/third_party/forked/reflect.callMethod: k8s.io/kubernetes/third_party/forked/reflect.typedmemmovepartial: not defined
    k8s.io/kubernetes/third_party/forked/reflect.callMethod: k8s.io/kubernetes/third_party/forked/reflect.call: not defined
    k8s.io/kubernetes/third_party/forked/reflect.callMethod: k8s.io/kubernetes/third_party/forked/reflect.typedmemmovepartial: not defined
    k8s.io/kubernetes/third_party/forked/reflect.callMethod: k8s.io/kubernetes/third_party/forked/reflect.memclr: not defined
    k8s.io/kubernetes/third_party/forked/reflect.Value.Cap: k8s.io/kubernetes/third_party/forked/reflect.chancap: not defined

Please let me know if you have any suggestions how to proceed with this.

**Comment by smarterclayton** [comment]
So specifically for the use case of our external types, I think it's
ObjectMetaFor that is broken, not ConvertibleTo.  External types were
*never* intended to be used by code internally.  Places that use
ObjectMetaFor should never deal with external types - instead we need to be
using pkg/api/meta to get the accessor that allows direct set / unset of
those values.  If there are things ObjectMetaFor allows that meta.Accessor
doesn't, then we probably need to add a new method on meta.Accessor that
exposes them.

**Comment by wojtek-t** [comment]
@smarterclayton - actually, this is very good point. I will try to fix it tomorrow.

**Comment by rsc** [comment]
Sorry, but you cannot meaningfully fork reflect, just as you cannot meaningfully fork the garbage collector.

**Comment by lavalamp** [comment]
Yeah it looks like reflect is even harder than the `go/types` package was (I wanted to use it from go 1.3 & 1.4 *without changing the import path* because we build in all versions-- that was a huge pain, the library has a bunch of stuff to make it *hard* to fork.).

I guess it's follow up on what Clayton says, or if it's an emergency, use `unsafe`, but we've avoided using that until now and I'd hate to start.

**Comment by wojtek-t** [comment]
Will do my best tomorrow.

**Comment by wojtek-t** [comment]
Switching from ObjectMetaFor to meta.Accessor seems to solve this problem.
https://github.com/kubernetes/kubernetes/pull/23472 is fixing this issue.
PTAL
