### ISSUE TITLE
Remove pkg/storage's dependency on pkg/api/errrors

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#23284]
Forked from #22965. pkg/storage should emit errors defined in pkg/storage/errors.go rather than the ones defined in pkg/api/errors. We should add a .import-restrictions to enforce the rule.

cc @lavalamp

**Comment by AdoHe** [comment]
I have did something about storage, will take a look.

**Comment by caesarxuchao** [comment]
Thank you @AdoHe! Please cc us if you have a PR.

**Comment by smarterclayton** [comment]
Resolved.
