### ISSUE TITLE
e2e flake: gsutil cat fails with a 503

### ISSUE THREAD

**Issue by maisem** [kubernetes/kubernetes#23299]
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/13616/ failed with 
```
13:20:54 ++ gsutil cat gs://kubernetes-release/ci/latest.txt
13:21:14 ServiceException: 503 Service Unavailable. If you have recently changed
13:21:14     https_validate_certificates from True to False in your boto configuration
13:21:14     file, please delete any cached access tokens in your filesystem (at /var/lib/jenkins/jobs/kubernetes-e2e-gce/workspace/.gsutil/credstore)
13:21:14     and try again.
```
subsequently https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/13617 passed

```
4:08:20 ++ gsutil cat gs://kubernetes-release/ci/latest.txt
14:08:22 + build_version=v1.3.0-alpha.0.731+4b1b291a9f402a
14:08:22 + echo 'Using published version ci/v1.3.0-alpha.0.731+4b1b291a9f402a (from ci/latest)'
```

Maybe we need to retry here?

**Comment by fejta** [comment]
Thanks for adding this!

I investigated and gsutil already retries 503. I suspect cloud storage was having issues at that time, which means there isn't a lot for us to do about this.

Please reopen if you see in the future.

**Comment by maisem** [comment]
Just saw it again.
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/1989/

**Comment by fejta** [comment]
@ixdy will you make sure we have the latest gsutil installed?

An unlikely alternative is that cpu pegging is causing this 503, but that seems confusing.

**Comment by ixdy** [comment]
We update `gcloud` daily, which should also update `gsutil`.

The gke-test failure snippet is 
```
12:00:37 ++ gsutil cat gs://kubernetes-release/ci/latest.txt
12:00:58 ServiceException: 503 Service Unavailable. If you have recently changed
12:00:58     https_validate_certificates from True to False in your boto configuration
12:00:58     file, please delete any cached access tokens in your filesystem (at /var/lib/jenkins/jobs/kubernetes-e2e-gke-slow/workspace/.gsutil/credstore)
12:00:58     and try again.
```
In both cases it took ~20s for `gsutil` to fail, suggesting it did retry, though possibly not waiting long enough.

**Comment by ixdy** [comment]
I'm guessing these failures were due to Jenkins being overloaded. I'm going to close out, but please reopen if we see this happening still.
