### ISSUE TITLE
Stop UID defaulting in ValidateObjectMetaUpdate

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#23297]
When handling PUT request, if the UID field is empty in the new object, API server defaults the UID of the new object to that of the existing object: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L344-L346

This was introduced to fix #14126 from the server side. A client-side fix is introduced in https://github.com/kubernetes/kubernetes/pull/15268.

I think users should always supply the UID, because otherwise the update might end up being applied on a different object that bears the same name, which could happen if an object is deleted and then recreated.

I think we should stop performing the defaulting in head, and inform the users to turning it on if they are using a pre-1.1 client.

@lavalamp @bgrant0607 @liggitt Do you have concerns?

**Comment by liggitt** [comment]
in general, UID has been defaulted on update server-side since 1.0 (events were just not going through the common code path which accomplished that). I wouldn't change that now.

**Comment by liggitt** [comment]
I don't mind moving defaulting out of the validation step, but I still want defaulting to occur server side (possibly in a common PrepareForUpdate impl?)

**Comment by caesarxuchao** [comment]
> in general, UID has been defaulted to the currently persisted object's value on update server-side since 1.0 (events were just not going through the common code path which accomplished that). I wouldn't change that now.

Agree we cannot remove the defaulting if it has been there since 1.0.

I think it's fair if the user doesn't provide the UID in the new object, the API server won't guarantee the update is applied on the expected object.

**Comment by lavalamp** [comment]
This is a tough one for me. I'd argue that we should make it hard for users to do the bad thing of clobbering a resource they didn't intend. On the other hand, I don't want to break existing clients.

At least we can say, if they *do* provide a UID, we should treat that as a precondition.

**Comment by liggitt** [comment]
Agree that a mismatched UID should fail update

**Comment by smarterclayton** [comment]
We can't really break old clients, but agree mismatched UID should fail update.  Moving to 1.7 as a bug.

**Comment by deads2k** [comment]
> We can't really break old clients, but agree mismatched UID should fail update. Moving to 1.7 as a bug.

So specifying a UID instead of specifying a resourceVersion and wanting an unconditional update of your particular object?  I could probably see it as an API choice, but I suspect its impractical for 1.7.
