### ISSUE TITLE
/etc/kubernetes/bootstrap fails if there are no ephemeral volumes (1.2, AWS)

### ISSUE THREAD

**Issue by dmcnaught** [kubernetes/kubernetes#23292]
I copied the launch config for the k8s cluster (v1.2) and changed the instance type from c3.2xlarge to m3.xlarge. bootstrap fails due to no ephemeral volumes:

```
bash -x /etc/kubernetes/bootstrap
...
+ ensure-local-disks
+ grep /mnt/ephemeral /proc/mounts
+ block_devices=()
++ curl --silent http://169.254.169.254/2014-11-05/meta-data/block-device-mapping/
++ grep ephemeral
+ ephemeral_devices=
```

justinsb on Slack: I think this needs to go into my kutil tool....
I think you have two options:
1) Figure out how to do this with the awscli (no AWS console).  Including mapping the blockdevicemappings
2) Bug me every day until I put it into "kutil"

**Comment by gy8** [comment]
+1

**Comment by dmcnaught** [comment]
adding ephemeral storage to the new launch config in aws console works (after changing the instance type) - so as long as the instance has ephemeral storage it looks ok.

**Comment by maisem** [comment]
cc @justinsb
