### ISSUE TITLE
kubectl documentation: generate .yaml files

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#23301]
Just putting our current documentation in the form of yaml would make it much easier to get nice documents. We already generate .man files and .md, so this shouldn't be too much work.

**Comment by johndmulhausen** [comment]
I suppose this would also go for kube-apiserver, kube-proxy, kube-scheduler, kubelet, and kube-controller-manager.

**Comment by lavalamp** [comment]
Yeah, we use the same mechanism for all of those components. kubectl is the most important, though.

**Comment by tyangliu** [comment]
Hello!

I gave this task a try (PR #23526). Let me know if something like this is what you were looking for. First time doing this, so I'd be happy to make changes and/or also implement generation for the other mentioned docs, kube-apiserver, kubelet, etc.

Background: Currently playing around with kubernetes and CRIU for a course project, and decided to take a quick break.

**Comment by lavalamp** [comment]
@tyangliu thanks, I left a comment on your PR :)
