### ISSUE TITLE
rktnetes can't run k8s guestbook frontend

### ISSUE THREAD

**Issue by sjpotter** [kubernetes/kubernetes#23300]
This is both a rkt bug and a k8s bug in terms of the image used for this app.

https://github.com/coreos/rkt/issues/2300

The best approach might be to change the image to not depend on being able to open /proc/self/fd/2 but to use apache's pipe log syntax to just fork a process that writes to it's stderr.

**Comment by tmrts** [comment]
Fixed in #23381
