### ISSUE TITLE
Reconsider default value for DeploymentSpec.MaxUnavailable

### ISSUE THREAD

**Issue by dhawal55** [kubernetes/kubernetes#23304]
I'm exploring the new `Deployment` resource in Kubernetes 1.2 and it seems it is not quite correct. It scales down the old replica set before scaling up for the new set. This is inconsistent with the rolling-update command which waited for new replication controller to scale up successfully first. As a result, deployment resource cannot be used for zero-downtime deployment in case of a single replica pod.

Please correct this to match the way `kubectl rolling-update` works which seems to be the right way.

**Comment by dhawal55** [comment]
After little exploring, i found that this can be fixed by setting spec.strategy.rollingUpdate.maxUnavailable to 0. Probably, the default value should be 0 instead of 1.

**Comment by bgrant0607** [comment]
Defaults set here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/defaults.go#L70

cc @janetkuo @kargakis

**Comment by kargakis** [comment]
Having maxUnavailable as a default is useful in cases you cannot scale up due to limits, host ports, etc. I think we don't want to allow 100% maxUavailable, so switching the integers to percentages probably makes sense (since percentages play better with ensuring availability). In OpenShift, we use 25%-25%.

**Comment by janetkuo** [comment]
Another case http://stackoverflow.com/questions/37435540/if-number-of-replicas-in-a-deployment-is-1-and-the-deployment-is-bad-the-deplo

**Comment by soltysh** [comment]
Fix in-flight in https://github.com/kubernetes/kubernetes/pull/39683

**Comment by soltysh** [comment]
Fix merged, closing.
