### ISSUE TITLE
Should master kubelet register itself?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#23310]
It looks like there are now two registration flags. One to register the node, the other to register it as schedulable. I currently have the master kubelet configured to register itself, but not register as schedulable.

This works, but during `validate-cluster.sh` there is a non-fatal, but red-colored output line that indicates there are too many nodes.

What is the recommendation?

1. Don't register the master kubelet at all.
2. Ignore the error from validate-cluster.
3. Patch validate-cluster to expect the master kubelet to be registered.

**Comment by yujuhong** [comment]
[validate-cluster.sh](https://github.com/kubernetes/kubernetes/blob/9845639e143223ff73c05f8e8f6a9256dd228a08/cluster/validate-cluster.sh#L40) should expect N+1 nodes if you set your register your master node.

```sh
EXPECTED_NUM_NODES="${NUM_NODES}"
if [[ "${REGISTER_MASTER_KUBELET:-}" == "true" ]]; then
  EXPECTED_NUM_NODES=$((EXPECTED_NUM_NODES+1))
fi
```

Did you set REGISTER_MASTER_KUBELET (which actually defaults to true)?

**Comment by colemickens** [comment]
>Did you set REGISTER_MASTER_KUBELET (which actually defaults to true)?

No. That's my issue. Thanks!
