### ISSUE TITLE
e2e flake: Nodes [Disruptive] [k8s.io] Network when a node becomes unreachable [replication controller] recreates pods scheduled on the unreachable node AND allows scheduling of pods on a node after it rejoins the cluster

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#23329]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-serial/824/

```
Node gke-jenkins-e2e-0cf1639d-node-izan did not become ready within 2m0s
```

It seems that Node failed to become running - do we plan to do something with such failures? @dchen1107

**Comment by dchen1107** [comment]
The test has passed for last 100 runs at kubernetes-e2e-gce-serial jenkins job, no flaky at all. Close this one.
