### ISSUE TITLE
kubelet: Incorrect fallback to hairpin-mode "hairpin-veth"

### ISSUE THREAD

**Issue by MurgaNikolay** [kubernetes/kubernetes#23322]
Hi guys. I have issue with connecting to PODs itself via service ip.
I determined that the problem with the wrong fallback to harpin-veth.

In kubelet output I have message:

    W0322 09:27:09.399179   25899 kubelet.go:508] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
    I0322 09:27:09.399219   25899 kubelet.go:380] Hairpin mode set to "hairpin-veth"

But hairpin_mode for interfaces is 0:

    cat /sys/devices/virtual/net/docker0/brif/veth*/hairpin_mode
    0
    0
    0
    0
   
If I set kubelet `--hairpin-mod=hairpin-veth` all is ok.
 
Kubelet output

    I0322 09:29:08.234951   28239 kubelet.go:380] Hairpin mode set to "hairpin-veth"

and

    cat /sys/devices/virtual/net/docker0/brif/veth*/hairpin_mode
    1
    1
    1
    1

I think problem is there 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L408
Because used hairpinMode variable, but value was set above to klet.hairpinMode (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L378) .

**Comment by MurgaNikolay** [comment]
Fix #23325

**Comment by bprashanth** [comment]
Closed via https://github.com/kubernetes/kubernetes/pull/23325
@MurgaNikolay thanks for the fix
