### ISSUE TITLE
Service definition do not support HTTP protocol

### ISSUE THREAD

**Issue by sachingharge** [kubernetes/kubernetes#23337]
Hi Team,

We have scenario where service is exposed as Loadbalancer in AWS cluster through supported protocol TCP.
As a result, we don't see HTTP headers passing to pods from ELB specially X-Forwarded-For which is really required for validating client IP address.
- spec.ports[0].protocol: unsupported value 'HTTP': supported values: TCP, UDP
- spec.ports[0].protocol: invalid value 'HTTP': cannot create an external load balancer with non-TCP ports

Any plan in coming days to support HTTP protocol for communication from Loadbalancer (ELB) to pod?

As intermediate solution, we probably need to add web server (Nginx or Apache) layer before the application to honor HTTP headers.

Please let us know your inputs on this.

Thanks!

**Comment by bprashanth** [comment]
>Any plan in coming days to support HTTP protocol for communication from Loadbalancer (ELB) to pod?

Yeah, you want Ingress for L7 proxying/loadbalancing: https://github.com/kubernetes/contrib/issues/346
If you have bandwidth I'm sure @therc could use help in getting L7 support for AWS.

For some context see http://kubernetes.io/docs/user-guide/ingress/, https://github.com/kubernetes/kubernetes/issues/23291
