### ISSUE TITLE
LoadBalancer creation failed

### ISSUE THREAD

**Issue by tspecht** [kubernetes/kubernetes#23341]
Hey guys,

I'm currently experiencing an issue regarding LoadBalancers and adding / removing nodes from the cluster. Since I applied EC2 autoscaling to my minion nodes its regularly the case that new nodes join and other nodes leave the cluster. I witnessed that kubernetes automatically removed them after a certain grace period.

However if I'm deploying something while a node is marked as `NotReady` when issuing `kubectl get nodes` my servic fails to update the ELB it is exposing with the error message below. This leads to my application being completely offline until the node was automatically removed by kubernetes and the service re-tries updating the ELB.
Shouldn't the desired behaviour in this case be to "skip" nodes that are `NotReady`? This would simply lead to the ELB having `x out of y` nodes available which is fine from my point of view.

```
$ kubectl describe service my-service --namespace="staging"
Name:           my-service
Namespace:      staging
Labels:         name=nginx-my-service,role=ssl-proxy
Selector:       name=nginx-my-service,role=ssl-proxy
Type:           LoadBalancer
IP:         10.3.0.53
LoadBalancer Ingress:   myelb.eu-west-1.elb.amazonaws.com
Port:           https   443/TCP
NodePort:       https   31439/TCP
Endpoints:      10.2.8.12:443
Port:           http    80/TCP
NodePort:       http    30056/TCP
Endpoints:      10.2.8.12:80
Session Affinity:   None
Events:
  FirstSeen LastSeen    Count   From            SubobjectPath   Type        Reason              Message
  --------- --------    -----   ----            -------------   --------    ------              -------
  12m       1m      376 {service-controller }           Warning     CreatingLoadBalancerFailed  Error creating load balancer (will retry): Failed to create load balancer for service staging/my-service: unable to find instance "ip-10-0-0-77.eu-west-1.compute.internal"
  11m       1m      142 {service-controller }           Warning     CreatingLoadBalancerFailed  Error creating load balancer (will retry): Failed to create load balancer for service staging/my-service: unable to find instance "ip-10-0-0-145.eu-west-1.compute.internal"
```

**Comment by tspecht** [comment]
Any idea why this could happen? Just occured again and I had to manually fix it :(

**Comment by justinsb** [comment]
Yeah, that is a bug.

But this should only affect _new_ services, right?  So it's just a bigger delay in creating the service?  (I don't think that's great, but it shouldn't be a huge problem unless you're creating services all the time...)

**Comment by tspecht** [comment]
Maybe a short background to what I'm doing:

My CI is rendering a huge template which contains the deployment object, the services and secrets needed to run the whole microservice I'm deploying into a single namespace. This template I'm then deploying using `kubectl apply -f ...`. Hence I would guess that the service is usually not re-created but stays the same (especially because if all the nodes are there the ELB gets updated but keeps the same URL so I would be very suprised if a new service would be created under the hood).
Regarding the "bigger delay": Since kubernetes seems to take a really long time (multiple hours?!) before auto-removing dead nodes (if at all tbh ...) this is not "just" a bigger delay since my application would be effectively offline for hours.
Could you come up with any way to fix that?

**Comment by tspecht** [comment]
Any update on this?
