### ISSUE TITLE
make sizes of persistent volume and persistent volume claims to be case sensitive and to check volume units 

### ISSUE THREAD

**Issue by ekuric** [kubernetes/kubernetes#23357]
If in pv/pvc file is specified 
"storage": "5Gi"
it will create pv of 5 GB size and oc get pv output will be 
pvol-5087a6e7   5Gi        RWO           Bound     clusterproject0/pclaimvol-5087a6e7             52s

However, if one specify 
"storage" :"5" 
then output of oc get pv will be 
NAME            CAPACITY   ACCESSMODES   STATUS    CLAIM                                REASON    AGE
pvol-f88aab4f   5          RWO           Bound     clusterproject0/pclaimvol-f88aab4f             30s

where unit for capacity in later case will not be visible. 
This will work as long as pv claim is not bigger than pv size

If one specify in pv/pvc files eg,
in pv file : "storage" : "5"
and in pvc "storage" : "100" 

pv claim will not be able to bound to volume  as it is not clear what actually "100" is - 100 Gi, or 100Mi ,...or some other unit

**Comment by thockin** [comment]
5 means 5 bytes - the base unit.
@jingxu97 to see if we can improve UX here - maybe an optional units suffix?

**Comment by jeremyeder** [comment]
similar UX issues with nodeallocable cf https://github.com/openshift/origin/issues/8547

**Comment by ekuric** [comment]
@thockin @jeremyeder  I think it should report syntax error / fail in case storage value is without specified unit for it 
``` "storage" : "5" ``` 
If one in PV file leave it without value and in PVC specify same value but add unit [eg. Gi ]  then that is causing troubles if value in PVC file for storage is bigger than one in PV file, and as now it will be
eg. in pv "storage":"5" and pvc file "storage":"5Gi" will cause pvc never to bind to pv

**Comment by thockin** [comment]
5 has a well-defined meaning - 5 bytes.  5Gi means 5 *10^30.  This is not a
case of forgetting.  You're asking a 5 GiB claim to match a 5 B volume.
Doesn't work.
