### ISSUE TITLE
Imports are dropped when generating conversions for extensions

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#23367]
There's a chance this is use error, but I just ran `./hack/update-all.sh` and it croaked with:

```
codecgen error: error running 'go run codecgen-main-1234.generated.go': exit status 2, console: # _/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/pkg/apis/extensions/v1beta1
./conversion_generated.go:3802: undefined: runtime in runtime.Object
./conversion_generated.go:5133: undefined: runtime in runtime.Object

!!! Error in ./hack/../hack/update-codecgen.sh:127
  '${CODECGEN} -d 1234 -o "${base_generated_file}" "${base_file}"' exited with status 1
Call stack:
  1: ./hack/../hack/update-codecgen.sh:127 main(...)
Exiting with status 1
```

I'm defining an extension with a runtime.Object field (just like list: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L2125, but in an extension), the generated `conversion_generated.go` file has runtime.Object in it, but no `k8s.io/kubernetes/pkg/runtime` import. 

I added it by hand ignoring the big comment to not do so, and re-ran update-codecgen.sh. 
What did I do wrong?

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
