### ISSUE TITLE
Investigate using easyjson for JSON (un)marshalling

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#23363]
[easyjson](https://github.com/mailru/easyjson) claims to be 2-3x faster than ugorji for JSON marshalling (I don't see any benchmarks for unmarshaling). If the claims hold, it may be worth investigating using it in k8s.

(Found on reddit: https://www.reddit.com/r/golang/comments/4bh0uk/easyjson_a_json_library_in_go_which_is_much/)

/cc @wojtek-t @lavalamp

**Comment by lavalamp** [comment]
We plan to switch to proto for system components, so hopefully this won't be an issue for much longer. :)

**Comment by wojtek-t** [comment]
Agree - let's wait for protobuf and then check if it makes sense to do anything else (it's possible that we may be able even to remove ugorji)

**Comment by lavalamp** [comment]
Removing would be really nice. Also we could write our own if we really
needed to, we have the code gen framework...

**Comment by smarterclayton** [comment]
We have other issues to cover this.
