### ISSUE TITLE
after update kube-apiserver fails to start

### ISSUE THREAD

**Issue by bitchecker** [kubernetes/kubernetes#23370]
hi @all,
i've update my kubernetes cluster and after this update i'm running:

```bash
# kubectl version 
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"86327329213fed4af2661c5ae1e92f9956b24f55", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"86327329213fed4af2661c5ae1e92f9956b24f55", GitTreeState:"clean"}
```

but kube-apiserver fails to start.

i've noted that in file ```/etc/kubernetes/apiserver ``` on previous version there is ```KUBE_API_ARGS=""``` but in the updated version, i've found ```KUBE_API_ARGS="--service_account_key_file=/tmp/serviceaccount.key"```

the problem is that this file doesn't exists!

i've created it with: ```# openssl genrsa -out /tmp/serviceaccount.key 2048``` and after that service started.

**Comment by AdoHe** [comment]
@bitchecker how you update your kubernetes cluster? binary replace?

**Comment by bitchecker** [comment]
yes, i'm opening the same bug on red hat bugzilla

**Comment by AdoHe** [comment]
@bitchecker if you are doing binary replace, I think the `/etc/kubernetes/apiserver` should not be updated.

**Comment by bitchecker** [comment]
it was updated and i've found differences running a diff

**Comment by mml** [comment]
This seems like a problem with the update done by the package manager.  Please re-open if I've misunderstood.
