### ISSUE TITLE
unit flake: TestScheduler is racy

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#23372]
==================
WARNING: DATA RACE
Write by goroutine 37:
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:353 +0x1e6
  testing.(*common).Logf()
      /usr/local/go/src/testing/testing.go:366 +0x82
  testing.(*common).Logf-fm()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/scheduler_test.go:74 +0x5f
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartLogging.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:211 +0x2a7
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:232 +0x14e

Previous read by main goroutine:
  runtime.convT2E()
      /usr/local/go/src/runtime/iface.go:128 +0x0
  testing.(*T).report()
      /usr/local/go/src/testing/testing.go:538 +0xa18
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:591 +0xbdf
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      k8s.io/kubernetes/plugin/pkg/scheduler/_test/_testmain.go:66 +0x210

Goroutine 37 (running) created at:
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:234 +0x8f
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartLogging()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:212 +0xa5
  k8s.io/kubernetes/plugin/pkg/scheduler.TestScheduler()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/scheduler_test.go:74 +0x112
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/23302/kubernetes-pull-test-unit-integration/19143/build-log.txt

**Comment by lavalamp** [comment]
@davidopp to delegate

**Comment by spxtr** [comment]
This is blocking #23302.

**Comment by wojtek-t** [comment]
This is a stupid bug - there shouldn't be defer in the call. Will send a PR in few minutes.
