### ISSUE TITLE
JSONpath fails to return keys containing dots in a map

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#23386]
(Kubernetes 1.2)

Consider the following `secret` definition:

```
{
    "kind": "Secret",
    "apiVersion": "v1",
    "metadata": {
        "name": "rails"
    },
    "data": {
        "db.conf": "cmVkYWN0ZWQK",
        "dbdotconf": "cmVkYWN0ZWQK"
    },
    "type": "Opaque"
}
```

`kubectl get secrets rails -o "jsonpath={.data['db.conf']}"` returns:

```
error: error executing jsonpath "{.data['db.conf']}": db is not found
```

while `kubectl get secrets rails -o "jsonpath={.data['dbdotconf']}"` works.

**Comment by AdoHe** [comment]
This is a bug of our JSONPath parser, the child operator failed to recognize this filed, since we dot is allowed in key, we have to fix this in JSONPath parser @kubernetes/kubectl

**Comment by timstclair** [comment]
FYI, you can use go-template as a workaround (not saying we shouldn't fix this):
```
kubectl get secrets rails -o 'go-template={{index .data "db.conf"}}'
```

**Comment by bgrant0607** [comment]
cc @daizuozhuo

**Comment by zefciu** [comment]
I will try to fix this.

**Comment by AdoHe** [comment]
@zefciu please take a look at #23919

**Comment by zefciu** [comment]
Yeah, this is a duplicate. If that patch passes the tests given there it fixes this issue.

**Comment by rjhowe** [comment]
Looks like this PR fixes the issue 1.5 #33901

**Comment by antoineco** [comment]
Escaping dots works now. To revisit the example in my original message:
```
~ $ kubectl get secrets rails -o "jsonpath={.data['db\.conf']}"
cmVkYWN0ZWQK
```

Closing :tada:

**Comment by marcellodesales** [comment]
Same with the external-dns!

```console
$ kubectl -n istio-system get service http2-service-ingress \
 -o jsonpath="{.metadata.annotations['external-dns\.alpha\.kubernetes\.io/hostname']}"
http2-gateway-ppd.pytest-iks-external-dns.a.company.com%
```

**Comment by sslavic** [comment]
Would it make sense to add an example to the docs? https://kubernetes.io/docs/reference/kubectl/jsonpath/

**Comment by marcelloromani** [comment]
This is a very old thread, I know, but just for reference and hoping to help some poor soul facing this (which might be me in a few weeks!):

Escaping the dot works, but you need to add the usual dot as well! (Makes perfect sense actually.)

Example:
```
jsonpath={ .data.\.dockerconfigjson }
```
