### ISSUE TITLE
kubectl describe doesn't show annotations

### ISSUE THREAD

**Issue by chbatey** [kubernetes/kubernetes#23380]
E.g

```
Name:           chris-test-svc
Namespace:      default
Labels:         app=serverspec,kubernetes.io/aws-lb-cname-zone=k8s.api.bskyb.com
Selector:       app=serverspec
Type:           LoadBalancer
IP:         10.254.80.188
LoadBalancer Ingress:   internal-a706c9285f10611e58a8b064e140b16c-521920650.eu-west-1.elb.amazonaws.com, chris-test-svc-default-cirrus-core.k8s.api.bskyb.com
Port:           <unset> 80/TCP
NodePort:       <unset> 31220/TCP
Endpoints:      172.16.31.9:80,172.16.5.7:80
Session Affinity:   None
Events:
  FirstSeen LastSeen    Count   From            SubobjectPath   Type        Reason          Message
  --------- --------    -----   ----            -------------   --------    ------          -------
  19m       19m     1   {service-controller }           Normal      CreatingLoadBalancer    Creating load balancer
  19m       19m     1   {service-controller }           Normal      CreatedLoadBalancer Created load balancer
  16m       16m     1   {service-controller }           Normal      CreatingLoadBalancer    Creating load balancer
  16m       16m     1   {service-controller }           Normal      CreatedLoadBalancer Created load balancer
  16m       16m     1   {service-controller }           Normal      UpdatedLoadBalancer Updated load balancer with new hosts

```

Happy to raise a PR for this if you think they should be shown a long with the labels.

**Comment by AdoHe** [comment]
@chbatey I guess you mean show along with the labels. Actually I don't want to display annotations along with labels, they are not the same, if you show them together it will just confuse users which one is label and which one is annotation.

**Comment by chbatey** [comment]
I meant as well as the labels in their own section

**Comment by AdoHe** [comment]
@kubernetes/kubectl

**Comment by smarterclayton** [comment]
We should show annotations on all describes, and put them probably below labels.

**Comment by AdoHe** [comment]
Just refer #20941. I will apply this to all this week.

**Comment by bgrant0607** [comment]
Thanks @AdoHe. I changed the title to be more general.

**Comment by bgrant0607** [comment]
cc @php-coder

**Comment by mrook** [comment]
+1

**Comment by seffenberg-naspers** [comment]
+1

**Comment by si74** [comment]
+1

**Comment by AdoHe** [comment]
@kubernetes/sig-cli consuming annotation metadata could be another part of 1.6 goal.

**Comment by email2liyang** [comment]
+1 it's very useful to see the annotation when we use k8s with promethues's auto discovery

**Comment by kargakis** [comment]
Annotations can be arbitrarily large and the output of `describe` is starting to get bloated for various resources. Showing *just* the annotations is going to be a thing with `kubectl view annotations`, isn't that enough?

**Comment by AdoHe** [comment]
yes, `kubectl view annotations` should be something fit this case.

**Comment by Miyurz** [comment]
Not sure why would this happen in 1.5.2 but I can't see annotation for the pod when I describe the pod

```
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  labels:
    name: aws-cli
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::12312312312:role/Engineer
spec:
  containers:
  - image: fstab/aws-cli
    command:
      - "/home/aws/aws/env/bin/aws"
      - "s3"
      - "ls"
      - "kops-production-euwest-1"
    name: aws-cli
```

**Comment by xiangpengzhao** [comment]
@Miyurz See https://github.com/kubernetes/kubernetes/issues/44914#issuecomment-297031844 please.
