### ISSUE TITLE
Generation of servicekey in coreos cloud-config

### ISSUE THREAD

**Issue by fonk** [kubernetes/kubernetes#23388]
Hi,

in this line https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/cloud-configs/master.yaml#L36 you generate a servicekey on every boot, regardless of any key that's still present there. In my opinion this will invalidate all secrets for the pods after a reboot of the master. Is there a specific reason for that? I think it would be better to generate a certificate + key only if not present and then use it as tls-cert-file and tls-private-key-file for kube-apiserver and root-ca-file and service-account-private-key-file for kube-controller-manager. Are there any drawbacks with that? Otherwise I would generate a pullrequest to change that.

Best regards,
Frank

**Comment by therc** [comment]
I worked around this. I make the key file immutable by running chattr +i after generating it. Then I alo changed the openssl command to ignore failures (the chattr one doesn't, so that if the file is e.g. missing, the service ends up in failed state).

**Comment by bgrant0607** [comment]
CoreOS's main documentation is on their site:
https://coreos.com/kubernetes/docs/latest/getting-started.html

**Comment by roberthbailey** [comment]
Given the lack of updates in the past year, I'm going to close this as obsolete.
