### ISSUE TITLE
Conflicting aws os reccomendations for kube-up.sh 

### ISSUE THREAD

**Issue by Stephenitis** [kubernetes/kubernetes#23399]
Trusty is no longer supported, kube-up suggest using jessie or wiley.
However wiley is not supported when attempted.

```sh
$ KUBE_OS_DISTRIBUTION=trusty
$ ./kube-up.sh
```
>trusty is no longer supported by kube-up; please use jessie or wily instead

```sh
$ KUBE_OS_DISTRIBUTION=wiley
$ ./kube-up.sh
```
>Cannot start cluster using os distro: wiley
>The current recommended distro is jessie

**Comment by justinsb** [comment]
It's `wily`.  Did I make a typo somewhere in the docs?

**Comment by justinsb** [comment]
Pretty sure this is just a typo error.  I'm going to close; feel free to reopen if e.g. the docs led you astray
