### ISSUE TITLE
ARP cache stops nodes from reaching master

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23395]
Observed this on AWS, but I am unsure why it would not happen on GCE also.  If GCE has a workaround/fix, I would like to use the same one on AWS.

Here's what happened:  I was upgrading from 1.1 to 1.2, which requires launching new nodes.  One of my nodes did not come up, I think (but am not sure) that it had the same address as one of the old nodes.  That node could not ping the master.   The master had an incorrect ARP entry in the arp table for the node in question (compared vs the node's ifconfig).  I flushed the node's ARP entry from the master and immediately ping resumed and the node came up soon thereafter.

I believe this is the problem, it might only affect newer kernels: https://news.ycombinator.com/item?id=8732151

**Comment by bprashanth** [comment]
The arp cached should get flushed periodically anyway? I think the default is 60s and you can set it in /proc/sys somewhere

**Comment by bprashanth** [comment]
This is why immediately recycling ips is generally not a good idea, but cluster up/down should've been enough time (one hopes)

**Comment by evanphx** [comment]
@bprashanth There is a bug (introduced here https://github.com/torvalds/linux/commit/2724680bceee94eac391552863771af105a7355c) in I think linux 3.13-3.15 that makes it such that small arp caches don't expire at all. That's why the cluster up/down/upgrade time isn't enough.

**Comment by gy8** [comment]
+1

**Comment by bprashanth** [comment]
Hmm, can you repro with just container ips then? or is there more to it.
you should be able to force docker to re-allocate the same ip by just using a smaller subnet (in fact i *think* pre docker 1.8 it would cycle ips only after using all 255, but from 1.9 they re-allocate ips as containers die)

**Comment by thockin** [comment]
GCE doesn't do L2, so no ARP cache issues.

Maybe we need to just periodically force a flush?

**Comment by davidopp** [comment]
@justinsb Do you think this should be a 1.3 release blocker?

**Comment by davidopp** [comment]
Since this is not AWS-specific, I don't think there's any reason Justin in particular needs to work on it. So ignore my previous comment--we can have anybody fix this.

I'm leaving it as a release blocker.

**Comment by erictune** [comment]
This seems like it affects both 1.2 and 1.3, and is a function of whether or not you have a kernel bug.  So, I don't think this is a release blocked, since it is not a regression.  But, if the fix is small, it does seem like something that could make it into a later patch release.  Removing from 1.3 milestone.

**Comment by bprashanth** [comment]
A solid repro would be a great starting point, I think at this point there's too much hand waving for an actionable fix. In the meanwhile, maybe we can surface an inability to ping kubelet's `--api-servers` through NPD? @Random-Liu

**Comment by justinsb** [comment]
AWS recommends setting `net.ipv4.neigh.default.gc_thresh1 = 0`.  Amazon Linux AMIs do this also:
https://forums.aws.amazon.com/thread.jspa?messageID=572171

**Comment by justinsb** [comment]
Fix in #27682 (applies the recommended sysctl)
