### ISSUE TITLE
Change test tests using b.gcri.io to use gcr.io

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#23391]
These tests use a b.gcr.io reference for a private image.  We should move the private image bucket to gcr.io and update the references.

https://github.com/kubernetes/kubernetes/blob/da582561870f48f9eaee610aae355f60398e7cbc/test/e2e/replica_set.go#L45
https://github.com/kubernetes/kubernetes/blob/da582561870f48f9eaee610aae355f60398e7cbc/test/e2e/rc.go#L43

**Comment by spiffxp** [comment]
/assign
fixed by #40335
