### ISSUE TITLE
Unable to delete replication set

### ISSUE THREAD

**Issue by Swaagie** [kubernetes/kubernetes#23406]
Documentation seems to be lacking on the replication set feature. Tried deleting a `rs` multiple times now with both cluster and CLI on version `1.2.0` no succes.

```
kubectl delete rs mongodb-1825932598    # falsely reports: replicaset "mongodb-1825932598" deleted
```

Also, current pod is terminated and immediately a new pods is created from the same replication set.

Edit: these replication sets got created without explicit config files, simply by running 
```
kubectl run [name] --image=[name] --port=[port] --replicas=1
```

**Comment by zhouhaibing089** [comment]
From the release notes, I see:

> `kubectl run` now produces Deployments (instead of ReplicationControllers) and Jobs (instead of Pods) by default.

maybe you should delete the `Deployment` object?

**Comment by Swaagie** [comment]
Your right, thanks for that catch, just ran `kubectl delete deployments [name]` and the jobs are now deleted fine. Closing this, although updating documentation while adding new features would be nice.

**Comment by jonathan-kosgei** [comment]
I'm having a similar issue on 1.3, I create a deployment which creates a replicaset , however deleting the deployment does not delete the replicaset and hence the pods it is under

**Comment by tinkercloud** [comment]
@zhouhaibing089  Just I have encountered the same problem, thank you for your answer
