### ISSUE TITLE
Add a munger (bot) to require release-note-* on all PRs and release-note-(!NONE) on cherrypicks (to branches)

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#23409]
Following a revelation in https://github.com/kubernetes/kubernetes/pull/23315#issuecomment-200573266, it became clear we could solve the release note issue (at least the simple case) with labels and a bot.

We need a new munger/bot to do the following:

1. Initiate a `needs-release-note` label on all new PRs
1. Disallow/Remove the `lgtm` label on all PRs labeled as `needs-release-note`
1. Create new labels: `release-note-NONE`, maybe others for new release note categories
1. Auto-remove `needs-release-note` when one of the release-note-* labels is added
1. Special case for cherry-picked/branch PRs, release-note-NONE is not allowed

**Comment by david-mcmahon** [comment]
cc @eparis

**Comment by eparis** [comment]
is the complete list of `release-note-*`
- release-note
- release-note-breaking-change
- release-note-none

Do we have a doc where to point people so they know what labels to add and what they should be doing when the bot starts blocking up their PRs?

(but yes, this logic is very easy to implement)

**Comment by eparis** [comment]
https://github.com/kubernetes/contrib/pull/615 implements the logic. I will not merge/turn on until we work out the message which should be left in a PR.

**Comment by david-mcmahon** [comment]
Yes, that is the list for now.  We may want to add to it later.
As far as messaging. what options do we have?

Can we insert something in the conversation stream?  If so let's go with:

This pull request needs a release note label.  Label with one of:
* `release-note` (standard release note)
* `release-note-breaking-change` (a possibly breaking change - flag modification)
* `release-note-NONE` (PR should not be included in any release notes)

For any release note label other than `release-note-NONE`, ensure your PR title is the release note you want to include.

**Comment by eparis** [comment]
Do we really want `release-note-NONE`? Does it need to be all caps?

I can certainly put that as a text comment in a PR any time the labels look bad. I'd also like to link to 'more info'. Do we have a 'more info' ?

**Comment by david-mcmahon** [comment]
All caps only a way to raise visibility of it being a special 'opt-out' label, but not necessary.
I'll create a more info then.  We don't have it yet.

**Comment by david-mcmahon** [comment]
See #23460.  You can add this link for [more info](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md/#release-notes)

**Comment by david-mcmahon** [comment]
The [proposal](https://github.com/kubernetes/kubernetes/pull/23315#issuecomment-199569867) was updated to change `release-note-breaking-change` to `release-note-action-required`

**Comment by liggitt** [comment]
looks like the bot doesn't know about `release-note-breaking-change` (it keeps readding the `release-note-needed` label in https://github.com/kubernetes/kubernetes/pull/24008)

**Comment by liggitt** [comment]
also, the release-note labels should follow other labels' format (`release-note/needed`, `release-note/none`, etc)

**Comment by eparis** [comment]
@liggitt I didn't think `release-note-breaking-change` was still a thing. I thought it was only `release-note-action-required`. Will look into it.

**Comment by eparis** [comment]
@david-mcmahon I see someone did actually change the label name back to 'breaking-change'    Where was this discussed?

**Comment by eparis** [comment]
@liggitt I'll work with @david-mcmahon to get the labels renamed today. Agreed and that should be easy...

**Comment by david-mcmahon** [comment]
I believe release-note-action-required was in place for some time.  I have no idea how release-note-breaking-change got back into the mix.

**Comment by eparis** [comment]
closing this. I think at least this issue is complete.
