### ISSUE TITLE
kubectl: global flags makes output from every command very noisy

### ISSUE THREAD

**Issue by broady** [kubernetes/kubernetes#23402]
Currently, there are 22 lines of output from any kubectl command describing global flags.

This means you always need to scroll the terminal buffer backwards to see the useful help output (toward the top).

Suggestions to fix:
- Remove global flags from every help output (put a separate help subcommand for it)
- Use the $PAGER environment variable to page help text

**Comment by AdoHe** [comment]
@kubernetes/kubectl

**Comment by deads2k** [comment]
We've done something that prevents this in openshift.  I don't actually know where or what, but global flags get suppressed, so it can be done without too much surgery.

**Comment by deads2k** [comment]
Looks like we changed the help template and wired up a new command to give us the global options: https://github.com/openshift/origin/blob/master/pkg/cmd/templates/templates.go

**Comment by smarterclayton** [comment]
And we do that specifically so we can do this -
https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cli.go#L87 -
group commands by function.

which is something I've been meaning to upstream to kubectl.

**Comment by bgrant0607** [comment]
@kubernetes/docs

**Comment by bgrant0607** [comment]
We absolutely need something like this.

**Comment by bgrant0607** [comment]
See also #7496

**Comment by fabianofranz** [comment]
Correct. We hide global flags by default (but they can still be individually exposed if wanted, like we do with `--certificate-authority` in `oc login` for example) and we put them under a separate command called `oc options`, which [is referenced](https://github.com/openshift/origin/blob/master/pkg/cmd/templates/templates.go#L53) at the bottom of every command. The only caveat is that we don't automatically get fixes applied to the default templates in Cobra. But we should definitely upstream this.

**Comment by andreykurilin** [comment]
will work on this issue

**Comment by andreykurilin** [comment]
PR was not bound to this issue:(
https://github.com/kubernetes/kubernetes/pull/29150

**Comment by andreykurilin** [comment]
@bgrant0607 Can you look at proposed change?

**Comment by smarterclayton** [comment]
@fabianofranz will do the review since he's fairly familiar with this.

**Comment by AdoHe** [comment]
@kubernetes/kubectl can close this issue now.
