### ISSUE TITLE
Revisit cAdvisor housekeeping (collection) period

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#23413]
The current default “housekeeping” (metrics collection) period is 10 seconds, but Heapster only scrapes the metrics from the Node every 30 seconds by default, so 2 of every 3 stats sets are thrown away. We can reduce cAdvisor resource usage within the Kubelet by nearly 66% just by changing the default period to match that of Heapster. This would impact the granularity of metrics available for introspection, but under this model that would be handled by a separate system (possibly another cAdvisor instance).

Issues requiring further investigation:
- With a 30s collection period, Heapster could be gathering stats that are up to 30s old. Determine whether this is acceptable, or provide a solution (such as on-demand scraping or collection syncing)
- Heapster is not the only consumer of the data. Out of resource killing ([proposal](https://github.com/derekwaynecarr/kubernetes/blob/eviction_policy_spec/docs/proposals/kubelet-eviction.md#eviction-monitoring-interval)) is expecting a 10s interval. We need to evaluate the requirement here, and determine whether some metrics can be gathered at the larger interval without impacting the system.

/cc @derekwaynecarr @kubernetes/sig-node

**Comment by vishh** [comment]
What are we attempting to optimize for, Cpu or Memory? If it is memory, we can store less samples, but at the same time keep the most recent sample around for OOR purposes.
If we were to significantly reduce the number of metrics that we collect and store within the kubelet process, would this issue become less relevant?

**Comment by timstclair** [comment]
I was thinking about CPU when I created this issue, but I agree we should consider reducing the memory usage by storing no more than 1-2 stat points (though that would render the UI all but useless). There isn't a well defined goal here, hence the "investigate" phrasing - I just think this is low hanging fruit for further reducing our resource overhead.

**Comment by vishh** [comment]
The side effect as you mentioned is that it will make recovery from Out of Resource situations take longer, which is not what we want. From that perspective, it is possibly a sub-optimal solution.

**Comment by derekwaynecarr** [comment]
I am biased to keep the lower window and storing fewer stats.  I planned in the out of resource killing module to keep the last measured signal locally in the stability manager for each configured signal we do out of resource killing against so I can properly implement grace period, so I do not need cadvisor to hold older data than the last observed value.
