### ISSUE TITLE
kubectl describe fix

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#23429]
All objects that contain podtemplates should start using the PodTemplateDescriber instead of selectively printing volumes, containers, or whatever is a part of the pod template. 

cc: @smarterclayton @janetkuo @AdoHe @kubernetes/kubectl

**Comment by AdoHe** [comment]
ref #20941 will follow up this.

**Comment by kargakis** [comment]
Ah, https://github.com/kubernetes/kubernetes/issues/20941 supersedes this. Closing.
