### ISSUE TITLE
Failed to start Kubernetes API Server on centos7.1.1503

### ISSUE THREAD

**Issue by loveresolution** [kubernetes/kubernetes#23423]
I do all the configurations as the kubernetes sites told.(http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/)

When I come to this step, I encourter the following error.
. Start the appropriate services on master:

for SERVICES in etcd kube-apiserver kube-controller-manager kube-scheduler; do 
	systemctl restart $SERVICES
	systemctl enable $SERVICES
	systemctl status $SERVICES 
done

etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; enabled)
   Active: active (running) since Thu 2016-03-24 05:06:51 EDT; 49ms ago
 Main PID: 13164 (etcd)
   CGroup: /system.slice/etcd.service
           └─13164 /usr/bin/etcd --name=default --data-dir=/var/lib/etcd/default.etcd --listen-client-urls=http://localhost:2379

Mar 24 05:06:51 centos-master etcd[13164]: heartbeat = 100ms
Mar 24 05:06:51 centos-master etcd[13164]: election = 1000ms
Mar 24 05:06:51 centos-master etcd[13164]: snapshot count = 10000
Mar 24 05:06:51 centos-master etcd[13164]: advertise client URLs = http://localhost:2379
Mar 24 05:06:51 centos-master etcd[13164]: loaded cluster information from store: <nil>
Mar 24 05:06:51 centos-master etcd[13164]: restarting member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit index 14699
Mar 24 05:06:51 centos-master etcd[13164]: ce2a822cea30bfca became follower at term 10
Mar 24 05:06:51 centos-master etcd[13164]: newRaft ce2a822cea30bfca [peers: [ce2a822cea30bfca], term: 10, commit: 14699, applied: 10001, lastindex: 14699, lastterm: 10]
Mar 24 05:06:51 centos-master etcd[13164]: starting server... [version: 2.2.2, cluster version: 2.2]
Mar 24 05:06:51 centos-master systemd[1]: Started Etcd Server.
Job for kube-apiserver.service failed. See 'systemctl status kube-apiserver.service' and 'journalctl -xn' for details.
kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2016-03-24 05:07:01 EDT; 80ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 13186 (code=exited, status=255)

Mar 24 05:07:01 centos-master systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Mar 24 05:07:01 centos-master systemd[1]: Failed to start Kubernetes API Server.
Mar 24 05:07:01 centos-master systemd[1]: Unit kube-apiserver.service entered failed state.
kube-controller-manager.service - Kubernetes Controller Manager
   Loaded: loaded (/usr/lib/systemd/system/kube-controller-manager.service; enabled)
   Active: active (running) since Thu 2016-03-24 05:07:01 EDT; 82ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 13206 (kube-controller)
   CGroup: /system.slice/kube-controller-manager.service
           └─13206 /usr/bin/kube-controller-manager --logtostderr=true --v=0 --master=http://centos-master:8080

Mar 24 05:07:01 centos-master systemd[1]: kube-controller-manager.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 24 05:07:01 centos-master systemd[1]: Unit kube-controller-manager.service entered failed state.
Mar 24 05:07:01 centos-master systemd[1]: Starting Kubernetes Controller Manager...
Mar 24 05:07:01 centos-master systemd[1]: Started Kubernetes Controller Manager.
Mar 24 05:07:01 centos-master kube-controller-manager[13206]: I0324 05:07:01.734405   13206 plugins.go:71] No cloud provider specified.
Mar 24 05:07:01 centos-master kube-controller-manager[13206]: I0324 05:07:01.734484   13206 nodecontroller.go:133] Sending events to api server.
Mar 24 05:07:01 centos-master kube-controller-manager[13206]: E0324 05:07:01.734571   13206 controllermanager.go:277] Failed to start service controller: ServiceController should not be run without a cloudprovider.
Mar 24 05:07:01 centos-master kube-controller-manager[13206]: E0324 05:07:01.740352   13206 resource_quota_controller.go:63] Synchronization error: Get http://centos-master:8080/api/v1/resourcequotas: dial tcp 192.168.10.193:8080: connection refused (&url.Error{Op:"G...
Mar 24 05:07:01 centos-master kube-controller-manager[13206]: E0324 05:07:01.740426   13206 nodecontroller.go:203] Error monitoring node status: Get http://centos-master:8080/api/v1/nodes: dial tcp 192.168.10.193:8080: connection refused
Hint: Some lines were ellipsized, use -l to show in full.
kube-scheduler.service - Kubernetes Scheduler Plugin
   Loaded: loaded (/usr/lib/systemd/system/kube-scheduler.service; enabled)
   Active: active (running) since Thu 2016-03-24 05:07:01 EDT; 79ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 13224 (kube-scheduler)
   CGroup: /system.slice/kube-scheduler.service
           └─13224 /usr/bin/kube-scheduler --logtostderr=true --v=0 --master=http://centos-master:8080

Mar 24 05:07:01 centos-master systemd[1]: kube-scheduler.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 24 05:07:01 centos-master systemd[1]: Unit kube-scheduler.service entered failed state.
Mar 24 05:07:01 centos-master systemd[1]: Starting Kubernetes Scheduler Plugin...
Mar 24 05:07:01 centos-master systemd[1]: Started Kubernetes Scheduler Plugin.
___________________________________________________________________________

The kuber api server can't start. Please give me some help.

**Comment by jayunit100** [comment]
paste the logs for the apiserver ?`journalctl -xn`

**Comment by mml** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/docs/user-guide/)
   * [the troubleshooting guide](http://kubernetes.io/docs/troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by jeffchanjunwei** [comment]
@loveresolution , how do you solve this problem at last? I have the same journal inform.
