### ISSUE TITLE
AWS: We don't actually create the cloudwatch alarm

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23431]
We have the function to do so, but we don't actually call it:

https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/util.sh#L535-L562

We should fix, provide a workaround for running clusters.

**Comment by davidopp** [comment]
ping @justinsb - do you think this is a release blocker? It sounds like we had the same behavior in 1.2 (since this was originally in the 1.2 milestone), so it's not clear to me it should be a release blocker.

**Comment by justinsb** [comment]
Concur that this is next-candidate.  kube-deploy tools include the ability to do true HA master, in auto-scaling groups on AWS, which are much more reliable and generally better.  I think we should generally prefer that approach to CloudWatch alarms, which were only ever temporary.

**Comment by justinsb** [comment]
kube-up in maintenance mode; closing.
