### ISSUE TITLE
kubectl exec does not accept quotes

### ISSUE THREAD

**Issue by maciek123** [kubernetes/kubernetes#23442]
`kubectl exec mypod -- date --date '-1 day'` becomes 
`kubectl exec mypod -- date --date -1 day` (quotes dropped)
and fails

**Comment by zhouhaibing089** [comment]
Surprising, It is fine on v1.1:

```sh
$ kubectl exec nginx-lyaof -- date --date '-1 day'
Thu Mar 24 05:45:09 UTC 2016
```

**Comment by AdoHe** [comment]
@maciek123 please provide your kubernetes version. `kubectl version` can give you that info. It would be quite useful for us to debug this issue with version info.

**Comment by tspecht** [comment]
Hey,

I'm having the same issue running 1.2.0. I'm trying to execute a command remotely that is not only consisting of one word but contains multiple. In fact, I'm trying to execute `python manage.py shell` to open up a Django shell in my container. When I do `exec -it -- bash ` and then manually execute the command its all working fine, only directly jumping into the shell is not working. Any idea?

**Comment by maciek123** [comment]
I did some debugging and figured out that the problem was with the kubectl wrapper I'm using, not the kubectl itself. I'm sorry for any confusion it might have caused.
