### ISSUE TITLE
AWS: ENABLE_CLUSTER_MONITORING defaults to influxdb - does this work with HPA?

### ISSUE THREAD

**Issue by rosskukulinski** [kubernetes/kubernetes#23441]
cc: @justinsb, from our discussion on slack.

In [cluster/aws/config-default.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/config-default.sh#L103), ENABLE_CLUSTER_MONITORING defaults to 'influxdb'.  My understanding of [HPA](http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaler/), is that it currently only works with heapster.

Does the default need to be changed to heapster?  Does HPA work with influxdb or other metrics systems?

(Aside: I'm fine with any/all of the above -- I just want to make sure that things 'just work' with sane defaults)

**Comment by rosskukulinski** [comment]
Ok.  So after some further digging, I think I understand why I got confused.

ENABLE_CLUSTER_MONITORING=influxdb uses influxdb as the datastore... but data still comes from heapster (which drives HPA)

**Comment by justinsb** [comment]
Going to close; HPA seems to work with any data storage backend AFAIK.  Please reopen if there's anything more to do here.
