### ISSUE TITLE
Better handle Codec() and Versioner() of storage.Interface

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#23458]
@timothysc has a comment on this on #23387. It's orthogonal to the issue but of course we could extend it to a discussion.

Currently, Codec() and Versioner() wrap an input object that could be shared across different storage back-ends. The code is just a repeat for each implementation:

``` Go
func NewSomeImpl(codec runtime.Codec, ...) {}

func (i *someImpl) Codec() {
  return i.codec
}
```

**Comment by hongchaodeng** [comment]
Any idea to handle this?

/cc @wojtek-t @lavalamp

**Comment by lavalamp** [comment]
I don't think this repetition is a big deal, but if you want to factor out into a third package it's fine with me.

**Comment by wojtek-t** [comment]
I agree with @lavalamp - those are very simple getters. So it's not a big code duplication. So although extracting it would be good, I would treat it as P4 :)

**Comment by timothysc** [comment]
Yeah it's a low prio cleanup work.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.
