### ISSUE TITLE
Provide flag to scale up/down > 1 pods at a time during rolling-update

### ISSUE THREAD

**Issue by azell** [kubernetes/kubernetes#23455]
`kubectl rolling-update` works by bringing up and taking down a single pod at a time.  Even with `--update-period` set to a low value, deploying to a controller with a decent replica size can take a non-trivial amount of time.

It would be useful to create a flag allowing the client to specify the number of pods to bring up/take down in batch with a default value of 1.

**Comment by zhouhaibing089** [comment]
@azell I do not think there is a default value in 1.2: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/rolling_updater.go#L261-L342.

kubectl will decide to scale up and scale down as much as possible.

**Comment by bgrant0607** [comment]
Please try Deployment instead. It supports maxUnavailable and maxSurge options:

http://blog.kubernetes.io/2016/04/using-deployment-objects-with.html
http://kubernetes.io/docs/user-guide/deployments/

cc @janetkuo
