### ISSUE TITLE
e2e flake: "Services should be able to change the type and ports of a service" is flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#23468]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:716 Expected error: <*errors.errorString | 0xc20854bb10>: { s: "failed to create static IP: ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:\n - The resource 'projects/k8s-jkns-e2e-gce/regions/us-central1/addresses/e2e-external-lb-test-78a722ee-f25f-11e5-a6eb-42010af01555' already exists\n", } failed to create static IP: ERROR: (gcloud.compute.addresses.create) Some requests did not succeed: - The resource 'projects/k8s-jkns-e2e-gce/regions/us-central1/addresses/e2e-external-lb-test-78a722ee-f25f-11e5-a6eb-42010af01555' already exists not to have occurred

https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce/13766/build-log.txt

**Comment by bprashanth** [comment]
```
STEP: creating a static load balancer IP
I0325 01:00:02.125107   23581 google_compute.go:39] Creating static IP with name "e2e-external-lb-test-78a722ee-f25f-11e5-a6eb-42010af01555" in project "k8s-jkns-e2e-gce"
E0325 01:00:08.270973   23581 google_compute.go:49] output from failed attempt to create static IP: ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - Internal Error
E0325 01:00:09.250926   23581 google_compute.go:49] output from failed attempt to create static IP: ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-e2e-gce/regions/us-central1/addresses/e2e-external-lb-test-78a722ee-f25f-11e5-a6eb-42010af01555' already exists
E0325 01:00:15.204950   23581 google_compute.go:49] output from failed attempt to create static IP: ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-e2e-gce/regions/us-central1/addresses/e2e-external-lb-test-78a722ee-f25f-11e5-a6eb-42010af01555' already exists
E0325 01:00:26.174075   23581 google_compute.go:49] output from failed attempt to create static IP: ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-e2e-gce/regions/us-central1/addresses/e2e-external-lb-test-78a722ee-f25f-11e5-a6eb-42010af01555' already exists
[AfterEach] [k8s.io] Services
```

So we got an internal error (http 5xx) from gce api, but subsequent requests failed with "already exists'. This sounds like: b/27367941
