### ISSUE TITLE
AWS Feature: kube-up replacement that works for everyone

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23478]
Whatever kube-up becomes in 1.3 should:
- be good
- should work with the installation technologies that people want to use (in particular Terraform & CloudFormation seem important on AWS)
- should allow changes
- should offer reasonable configuration (multi-AZ, internal CIDR, networking layer)
- allow groups of nodes to be added & managed easily, with different configurations (AZs, instance types, spot vs non-spot)

There is a lot of overlap here with the kube-up v2 work here: #23174

The AWS upgrader tool has much of the machinery to do this: it can build AWS clusters directly and idempotently.  But it can also render to different targets, so it might be a matter of adding Terraform & CloudFormation targets here.

https://github.com/kopeio/kope

**Comment by huhlig** [comment]
- Allow for named multi cluster configuration. (something akin to --cluster=foobar) 
 - Support Configuration file based cluster creation rather than environment variable based
 - Allow parameterized use of Cloud Formation on AWS
     - VPC IP Range specification(instances, services, and pods)
     - Support AZ Subnet Configuration
     - Support Prefix/Suffix parameter for resources (VPC, Subnets, Instances, etc.)
     - Support Creation/Updating of ELB/Route53 configuration
     - Support using existing preconfigured VPC
     - Support AWS KMS Keys for security
     - Support aws Key Pairs
 - Better documentation on all options for AWS use

**Comment by justinsb** [comment]
Great list - thanks @huhlig .  It's important to figure out everyone's requirements, so please do comment with anything unobvious that you are using, that is missing!

**Comment by memes** [comment]
Been lurking on sig-aws and users channels and still looking for an idempotent, reliable way to setup an HA master that can be managed by ASG. So, adding to the list,

- HA master with ASG support

> - Support using existing preconfigured VPC

+1 This is critical for some of my use cases and would allow me to move from handcrafted CF template to supported tool.

**Comment by mikesplain** [comment]
Agreed with @memes.  We setup terraform for bootstrapping the aws components (including internal ELBs for HA master) and wrote custom scripts to drive configuration via cloud-config so we can scale up / down masters and minions as needed.  Idempotency, little config management infra, and little human intervention on HA node failure was key for us.  

So my addition would be: 

- Internal ELB support for HA master (et, all)

Also thanks @justinsb for the great new feature issues; looking forward to v1.3!

**Comment by c4po** [comment]
+1 for enable the configuration for VPC CIDR. This will allow us create multi K8S clusters in one region.
should be a easy fix.

**Comment by thenayr** [comment]
* Support private networks without allocating public IP's to master (minions already have the `KUBE_ENABLE_NODE_PUBLIC_IP` option)
* Support existing security groups for master / minion
* +1 for better AWS documentation, lots of the options are hidden in config-default

**Comment by danielfm** [comment]
* Allow the creation of EBS root volumes instead of relying on the default storage for the chosen instance type

Some types of instances do not provide a root storage device sufficiently large to hold Docker images (m3.medium), or do not provide storage at all (m4.\* , c4.\*).

**Comment by nVitius** [comment]
- Allow the customization of apiserver flags
- Allow custom files to be uploaded (authorization-policy-file, token-auth-file, basic-auth-file, all the SSL certs).

I'd like to be able to enable ABAC authorization. This would also require being able to pass in a policy file.  http://kubernetes.io/docs/admin/authorization/

**Comment by roberthbailey** [comment]
@justinsb - is this feature request describing kops?

**Comment by justinsb** [comment]
If you say so @roberthbailey ;-)  I believe kops (powered by kubeadm) is closest to closing it.

There's a great list of requirements here, and I think we're really close to covering _everything_ here.  But not _quite_ e.g. KMS and custom authn.

**Comment by roberthbailey** [comment]
I guess my question is whether we should close this issue and file issues for the remaining pieces in the kops repo or if this issue is still worth tracking.
