### ISSUE TITLE
ObjectMeta for templates

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#23475]
Per [this comment](https://github.com/kubernetes/kubernetes/pull/21675/files#r57190315) we need stripped down `ObjectMeta` to be used for templates (eg. `PodTemplate`, `JobTemplate`, etc.).

@bgrant0607 @deads2k @lavalamp

**Comment by deads2k** [comment]
> Per this comment we need stripped down ObjectMeta to be used for templates (eg. PodTemplate, JobTemplate, etc.).

Can you stub in what you think it should look like?  I think the comment got lost to an outdated diff, but I'm guessing that we don't need things like name or namespace?

**Comment by soltysh** [comment]
From looking into the usage patterns we have both in k8s and openshift I'm proposing following meta for templates:

```go
type ObjectTemplateMeta struct {
    GenerateName string
    Namespace string
    Labels LabelSet `json:"labels,omitempty"` 
    Annotations map[string]string `json:"annotations,omitempty"`
}
```

@deads2k @bgrant0607 opinions?

**Comment by bgrant0607** [comment]
@soltysh All of the fields should be optional. I don't think we need namespace, since we don't allow cross-namespace control currently.

**Comment by soltysh** [comment]
@bgrant0607 :+1: for the optional, for the namespace I wasn't sure, will change it. Once we agree on the contents I'll start working on impl.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.
