### ISSUE TITLE
AWS Feature: >50 node networking support for AWS

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23477]
We need built-in support for some networking layer that gets past the 50 node limit of VPC.

Built-in might just mean bundling one of the existing options into the installer.  But we should also see whether another option is more suitable on AWS, e.g. #23476

**Comment by caseydavenport** [comment]
I think there are a bunch of network providers which don't have this limit today, so this issue isn't relevant any more.

@justinsb WDYT? Can we close?
