### ISSUE TITLE
"kubectl-only Ubernetes": enabe kubectl to target any one of many clusters

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#23492]
Think --cluster=x cmdline param). Most of it is there already, I think. Just needs cleaning up into a product. I think that pairing this with the multi-cluster UI work that I proposed for the Warsaw guys (enable dahsboard-ui to target one of many clusters) will be a pretty cool 1.3 feature set. Particularly because I don't think that Federated ReplicaSet and Federated Service in isolation for Ubernetes Proper are particularly useful on their own.

**Comment by quinton-hoole** [comment]
cc @kubernetes/sig-cluster-federation

**Comment by nelcy** [comment]
@quinton-hoole I can take this item.

**Comment by bgrant0607** [comment]
--cluster= and --context= already exist. In what way do you want to change them?

See also #20605

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl
