### ISSUE TITLE
get pods list API for large datasets, pagination in plans?

### ISSUE THREAD

**Issue by darkgaro** [kubernetes/kubernetes#2349]
Are there plans to add Pagination to those api endpoint results that can end up possibly being large, like listing all of the pods.

**Comment by bgrant0607** [comment]
Some links I dug up for https://github.com/coreos/etcd/issues/860:
http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pagination
https://blog.apigee.com/detail/restful_api_design_can_your_api_give_developers_just_the_information
https://cloud.google.com/appengine/docs/python/datastore/queries#Python_Query_cursors

**Comment by smarterclayton** [comment]
Discussion in the store proposal: https://github.com/coreos/etcd/pull/1634#issuecomment-62639942

----- Original Message -----

**Comment by bgrant0607** [comment]
We should try to use the same approach for paging for metrics, logs, events, lists, etc.
cc @vishh @timstclair @dchen1107

**Comment by smarterclayton** [comment]
I'd prefer to go down the (prefix for start, next page token, limit) route
rather than pure numeric paging.  Numeric paging doesn't really help
clients much and is a pain to optimize at the limit.

**Comment by bgrant0607** [comment]
@smarterclayton I agree. Best practice for Google APIs is to allow list request to specify a max size and page token (empty for first page), with each page returning an opaque next page token. To ensure opacity, page tokens are typically base64 encoded, and often contain structured data.

**Comment by lavalamp** [comment]
Yes, I think the internal rules around this are good and we should use them.

**Comment by lavalamp** [comment]
@bgrant0607 @smarterclayton I am getting a bit worried that someone is going to run a huge cluster and this will turn into an emergency overnight, but it's a fair amount of work, so I think we want to have it in before it becomes an emergency. Does it make sense to target this for 1.3? @krousey is interested in adding this to API server.

**Comment by smarterclayton** [comment]
I wanted to wait for etcd3, because I suspect with protobuf + etcd we will
push back the urgency of this by a few months.

**Comment by bgrant0607** [comment]
@smarterclayton How much work is there left to do on protobuf?

**Comment by smarterclayton** [comment]
* Merge the serializer implementation
* Add dev tooling (protoc in an image to run hack/update-generated-protobuf)
* Finish the watch implementation refactor (to support multiple types of
streaming protocol), which is mostly complete
* Determine a versioning policy on protobuf schema (internal only for 1.3,
experimental, etc)
* Review the generated protobuf schema by an expert and the details of the
streaming protocol
* Give clients command line flags to ask for protobuf (kubelet, controllers)
* Stress test the system with protobuf on
* Fix bugs

A few weeks of effort altogether and the necessary soak time

**Comment by liggitt** [comment]
Chunking is now supported via the api
