### ISSUE TITLE
Cluster fails to come up with login issues

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#23496]
Just an intermittent flake. Subsequent runs succeeded:
```
:03 
09:51:03 to select an already authenticated account to use.
09:51:05 ERROR: (gcloud.compute.instances.list) You do not currently have an active account selected.
09:51:05 Please run:
09:51:05 
09:51:05   $ gcloud auth login
09:51:05 
09:51:05 to obtain new credentials, or if you have already logged in with a
09:51:05 different account:
09:51:05 
09:51:05   $ gcloud config set account ACCOUNT
09:51:05 
09:51:05 to select an already authenticated account to use.
09:51:06 ERROR: (gcloud.compute.routes.list) You do not currently have an active account selected.
09:51:06 Please run:
09:51:06 
09:51:06   $ gcloud auth login
09:51:06 
09:51:06 to obtain new credentials, or if you have already logged in with a
09:51:06 different account:
09:51:06 
09:51:06   $ gcloud config set account ACCOUNT
09:51:06 
```
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-ingress-release-1.2/203
Passed in http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-ingress-release-1.2/204

**Comment by fejta** [comment]
Happy case: 

```ssh
++ gcloud auth list
++ grep active
++ cut -f3 '-d '
+ export GCE_SERVICE_ACCOUNT=661044217466-compute@developer.gserviceaccount.com
+ GCE_SERVICE_ACCOUNT=661044217466-compute@developer.gserviceaccount.com
```

sad case:

```ssh
++ gcloud auth list
++ grep active
++ cut -f3 '-d '
+ export GCE_SERVICE_ACCOUNT=
+ GCE_SERVICE_ACCOUNT=
```

**Comment by ixdy** [comment]
Interesting. I'm pretty sure that we don't actually need to set `GCE_SERVICE_ACCOUNT`, since the account we get from `gcloud auth list | grep active` is the same as the default. If it's not set we follow a slightly different code path which may be less tolerant to the overloaded Jenkins VM environment (I'm guessing).

cc @saad-ali since I was just talking to him about this (but not re: this issue)

**Comment by fejta** [comment]
Well it sounds like we should immediately bomb out if gcloud auth list | grep active returns non-0

**Comment by fejta** [comment]
Here is what bites us: 

```sh
export GCE_SERVICE_ACCOUNT=$(gcloud auth list 2> /dev/null | grep active | cut -f3 -d' ')
```

https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/job-configs/global.yaml#L190

**Comment by fejta** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/23545
