### ISSUE TITLE
Storage version needs priority order

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#23508]
e.g., if you're adding v2alpha1, you may want to store objects in v1 still. But then how can you test the alpha objects at all? So the storage version codec should first try v1, then try v1alpha1.

This came up in #21675.

I think this is just fixing the codec setup.

**Comment by AdoHe** [comment]
@lavalamp also what's status of this issue?

**Comment by lavalamp** [comment]
I believe @deads2k added the ability to do this in code. It's not hooked up to the command line flags afaik. I think this should only affect alpha things so it's not urgent.

**Comment by lavalamp** [comment]
We will probably have to do this for 1.4.

**Comment by lavalamp** [comment]
This seems to not be a burning issue at the moment. Punting.
