### ISSUE TITLE
Unable to set up SkyDNS on single node cluster

### ISSUE THREAD

**Issue by tooda02** [kubernetes/kubernetes#23505]
I'm unable to install the SkyDNS addon to a Kubernetes 1.2 single-node cluster on Centos 7 and encountering issues.  The first is that there's an apparent error in the skynet-rc.yaml file referenced by the  [documentation](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns#how-do-i-configure-it): it's necessary to specify --validate=false when creating the replication controller, as the command otherwise gets the message:

    error validating "skydns-rc.yaml": error validating data: [found invalid field successThreshold for v1.Probe, found invalid field failureThreshold for v1.Probe]; if you choose to ignore these errors, turn validation off with --validate=false

If I specify --validate=false, all four containers start successfully, but the kube2sky container gets terminated by heathz after about a minute:

    [david@centos dns]$ kubectl --server="http://centos:8080" --namespace="kube-system" logs -f kube-dns-v11-t7nlb -c kube2sky
    I0325 20:58:18.516905       1 kube2sky.go:462] Etcd server found: http://127.0.0.1:4001
    I0325 20:58:19.518337       1 kube2sky.go:529] Using http://192.168.87.159:8080 for kubernetes master
    I0325 20:58:19.518364       1 kube2sky.go:530] Using kubernetes API v1
    I0325 20:58:19.518468       1 kube2sky.go:598] Waiting for service: default/kubernetes
    I0325 20:58:19.533597       1 kube2sky.go:660] Successfully added DNS record for Kubernetes service.
    F0325 20:59:25.698507       1 kube2sky.go:625] Received signal terminated

I've determined that the termination is done by the healthz container after reporting:

    2016/03/25 21:00:35 Client ip 172.17.42.1:58939 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
    2016/03/25 21:00:35 Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local', at 2016-03-25 21:00:35.608106622 +0000 UTC, error exit status 1.

My setup is that I've modified /etc/kubernetes/kubelet to include:

    KUBELET_ARGS="--cluster-dns=10.0.0.10 --cluster-domain=cluster.local"

and used the OOB skynet-rc.yaml and skynet-svc.yaml with minimal changes for an explicit API server address and to remove Salt dependencies.  

Here is the skydns-rc.yaml I used: 

    apiVersion: v1
    kind: ReplicationController
    metadata:
      name: kube-dns-v11
      namespace: kube-system
      labels:
        k8s-app: kube-dns
        version: v11
        kubernetes.io/cluster-service: "true"
    spec:
      replicas: 1
      selector:
        k8s-app: kube-dns
        version: v11
      template:
        metadata:
          labels:
            k8s-app: kube-dns
            version: v11
            kubernetes.io/cluster-service: "true"
        spec:
          containers:
          - name: etcd
            image: gcr.io/google_containers/etcd-amd64:2.2.1
            resources:
              # TODO: Set memory limits when we've profiled the container for large
              # clusters, then set request = limit to keep this container in
              # guaranteed class. Currently, this container falls into the
              # "burstable" category so the kubelet doesn't backoff from restarting it.
              limits:
                cpu: 100m
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 50Mi
            command:
            - /usr/local/bin/etcd
            - -data-dir
            - /var/etcd/data
            - -listen-client-urls
            - http://127.0.0.1:2379,http://127.0.0.1:4001
            - -advertise-client-urls
            - http://127.0.0.1:2379,http://127.0.0.1:4001
            - -initial-cluster-token
            - skydns-etcd
            volumeMounts:
            - name: etcd-storage
              mountPath: /var/etcd/data
          - name: kube2sky
            image: gcr.io/google_containers/kube2sky:1.14
            resources:
              # TODO: Set memory limits when we've profiled the container for large
              # clusters, then set request = limit to keep this container in
              # guaranteed class. Currently, this container falls into the
              # "burstable" category so the kubelet doesn't backoff from restarting it.
              limits:
                cpu: 100m
                # Kube2sky watches all pods.
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 50Mi
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 5
            readinessProbe:
              httpGet:
                path: /readiness
                port: 8081
                scheme: HTTP
              # we poll on pod startup for the Kubernetes master service and
              # only setup the /readiness HTTP server once that's available.
              initialDelaySeconds: 30
              timeoutSeconds: 5
            args:
            # command = "/kube2sky"
            - --domain="cluster.local"
            - --kube-master-url=http://192.168.87.159:8080
          - name: skydns
            image: gcr.io/google_containers/skydns:2015-10-13-8c72f8c
            resources:
              # TODO: Set memory limits when we've profiled the container for large
              # clusters, then set request = limit to keep this container in
              # guaranteed class. Currently, this container falls into the
              # "burstable" category so the kubelet doesn't backoff from restarting it.
              limits:
                cpu: 100m
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 50Mi
            args:
            # command = "/skydns"
            - -machines=http://127.0.0.1:4001
            - -addr=0.0.0.0:53
            - -ns-rotate=false
            - -domain="cluster.local"
            ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          - name: healthz
            image: gcr.io/google_containers/exechealthz:1.0
            resources:
              # keep request = limit to keep this container in guaranteed class
              limits:
                cpu: 10m
                memory: 20Mi
              requests:
                cpu: 10m
                memory: 20Mi
            args:
            - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
            - -port=8080
            ports:
            - containerPort: 8080
              protocol: TCP
          volumes:
          - name: etcd-storage
            emptyDir: {}
          dnsPolicy: Default  # Don't use cluster DNS.

and skydns-svc.yaml:

    apiVersion: v1
    kind: Service
    metadata:
      name: kube-dns
      namespace: kube-system
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"
        kubernetes.io/name: "KubeDNS"
    spec:
      selector:
        k8s-app: kube-dns
      clusterIP:  "10.0.0.10"
      ports:
      - name: dns
        port: 53
        protocol: UDP
      - name: dns-tcp
        port: 53
        protocol: TCP

**Comment by dchen1107** [comment]
cc/ @ArtfulCoder

**Comment by ArtfulCoder** [comment]
can you (for testing only), increase the timeouts on the probes then manually verify:
1. etcd contains the entry. you can run /usr/local/etcdctl ls --recursive on the etcd container
2. verify that dns container works by doing the nslookup of "kubernetes.default.svc.cluster.local yourself ?
you can run nslookup on the healthz container on 127.0.0.1, and on the node at 10.0.0.10

**Comment by tooda02** [comment]
Thanks for looking at this issue.  This is a test server and I have no problem with doing anything to it you need.

I've increased the timeout on both probes from 5 seconds to 60 and run the two commands you requested.  Here is their output:

/usr/local/bin/etcdctl ls -- recursive on etcd

    [david@centos dns]$ kcsys exec kube-dns-v11-1e72w  -c etcd -- /usr/local/bin/etcdctl ls --recursive
    /skydns
    /skydns/local"
    /skydns/local"/"cluster
    /skydns/local"/"cluster/svc
    /skydns/local"/"cluster/svc/default
    /skydns/local"/"cluster/svc/default/countries
    /skydns/local"/"cluster/svc/default/countries/23a31b32
    /skydns/local"/"cluster/svc/default/mysql
    /skydns/local"/"cluster/svc/default/mysql/7d3ba3a4
    /skydns/local"/"cluster/svc/default/kubernetes
    /skydns/local"/"cluster/svc/default/kubernetes/7ec1e7c0
    /skydns/local"/"cluster/svc/kube-system
    /skydns/local"/"cluster/svc/kube-system/kube-dns
    /skydns/local"/"cluster/svc/kube-system/kube-dns/cc4be02e
    /skydns/local"/"cluster/pod
    /skydns/local"/"cluster/pod/default
    /skydns/local"/"cluster/pod/default/172-17-0-3
    /skydns/local"/"cluster/pod/default/172-17-0-3/edc9142
    /skydns/local"/"cluster/pod/default/172-17-0-2
    /skydns/local"/"cluster/pod/default/172-17-0-2/c6db276b
    /skydns/local"/"cluster/pod/kube-system
    /skydns/local"/"cluster/pod/kube-system/172-17-0-4
    /skydns/local"/"cluster/pod/kube-system/172-17-0-4/7e8a3051

nslookup on healthz

    [david@centos dns]$ kcsys exec kube-dns-v11-1e72w  -c healthz -- nslookup kubernetes.default.svc.cluster.local
    Server:    192.168.87.2
    Address 1: 192.168.87.2

    nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
    error: error executing remote command: Error executing command in container: Error executing in Docker Container: 1

    [david@centos dns]$ kcsys exec kube-dns-v11-1e72w  -c healthz -- nslookup kubernetes.default
    nslookup: can't resolve 'kubernetes.default'
    Server:    192.168.87.2
    Address 1: 192.168.87.2

    error: error executing remote command: Error executing command in container: Error executing in Docker Container: 1

In both the above, `kcsys` is an alias for `kubectl --namespace="kube-system" --server="http://centos:8080"`

**Comment by ArtfulCoder** [comment]
you have an additional double quote in the etcd path 

local" should be local

**Comment by ArtfulCoder** [comment]
in the yaml, can you just say cluster.local (minus the double quotes) and see if it helps

**Comment by tooda02** [comment]
I've done that (sorry for not noticing this issue earlier).  It improves the look of the output from etcdctl, but unfortunately the nslookup still fails:

    [david@centos dns]$ kcsys exec kube-dns-v11-84yia  -c etcd -- /usr/local/bin/etcdctl ls --recursive
    /skydns
    /skydns/local
    /skydns/local/cluster
    /skydns/local/cluster/svc
    /skydns/local/cluster/svc/kube-system
    /skydns/local/cluster/svc/kube-system/kube-dns
    /skydns/local/cluster/svc/kube-system/kube-dns/cc4be02e
    /skydns/local/cluster/svc/default
    /skydns/local/cluster/svc/default/kubernetes
    /skydns/local/cluster/svc/default/kubernetes/7ec1e7c0
    /skydns/local/cluster/svc/default/countries
    /skydns/local/cluster/svc/default/countries/23a31b32
    /skydns/local/cluster/svc/default/mysql
    /skydns/local/cluster/svc/default/mysql/7d3ba3a4
    /skydns/local/cluster/pod
    /skydns/local/cluster/pod/kube-system
    /skydns/local/cluster/pod/kube-system/172-17-0-5
    /skydns/local/cluster/pod/kube-system/172-17-0-5/404c8068
    /skydns/local/cluster/pod/default
    /skydns/local/cluster/pod/default/172-17-0-3
    /skydns/local/cluster/pod/default/172-17-0-3/edc9142
    /skydns/local/cluster/pod/default/172-17-0-2
    /skydns/local/cluster/pod/default/172-17-0-2/c6db276b

    [david@centos dns]$ kcsys exec kube-dns-v11-84yia  -c healthz -- nslookup kubernetes.default.svc.cluster.local
    nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
    Server:    192.168.87.2
    Address 1: 192.168.87.2

    error: error executing remote command: Error executing command in container: Error executing in Docker Container: 1

    [david@centos dns]$ kcsys exec kube-dns-v11-84yia  -c healthz -- nslookup kubernetes.default
    nslookup: can't resolve 'kubernetes.default'
    Server:    192.168.87.2
    Address 1: 192.168.87.2

    error: error executing remote command: Error executing command in container: Error executing in Docker Container: 1

The etcdctl output contains a number of occurrences of strings like "172-17-0-2" that look like they're derived from IP addresses.  However, there's no IP address 172.17.0.2 associated with this cluster.   The server is on 192.168.87.2 and the Kubernetes IP range is 10.254.0.0/16.

**Comment by ArtfulCoder** [comment]
Can you run
`` kcsys exec kube-dns-v11-84yia  -c healthz -- nslookup kubernetes.default 127.0.0.1``

**Comment by tooda02** [comment]
[david@centos ~]$ kcsys exec kube-dns-v11-84yia -c healthz -- nslookup kubernetes.default.cluster.local 127.0.0.1
    Server:    127.0.0.1
    Address 1: 127.0.0.1 localhost

    nslookup: can't resolve 'kubernetes.default.cluster.local'
    error: error executing remote command: Error executing command in container: Error executing in Docker Container: 1

**Comment by ArtfulCoder** [comment]
I am sorry, my command should be 
kcsys exec kube-dns-v11-84yia -c healthz -- nslookup kubernetes.default.svc.cluster.local 127.0.0.1

I missed the "svc" segment.

**Comment by ArtfulCoder** [comment]
I am closing this for now. Please reopen if you are still seeing issues.

**Comment by tooda02** [comment]
@ArtfulCoder Sorry for the delay in responding - I changed my environment to work from 1.2 GA source (it turns out Centos yum install brings in alpha 1), and am having trouble recreating the environment where I observed the issue (node will not go active).  I will keep trying and let you know the results of your command and whether or not this appears to be an alpha 1 issue.

**Comment by tooda02** [comment]
@ArtfulCoder I finally was able to get my environment recreated and your command runs successfully:

    [david@centos ~]$ kcsys exec kube-dns-v11-iq8p2 -c healthz -- nslookup kubernetes.default.svc.cluster.local 127.0.0.1
    Server:    127.0.0.1
    Address 1: 127.0.0.1 localhost

    Name:      kubernetes.default.svc.cluster.local
    Address 1: 10.254.0.1

It looks like things are working now, and that the original problem was a setup error.  Thanks for your help.

**Comment by mootezbessifi** [comment]
@tooda02 please what was the setup error ? i am facing the same issue from several days.

**Comment by mootezbessifi** [comment]
@ArtfulCoder

**Comment by tooda02** [comment]
@mootezbessifi sorry, I don't have any further info on the setup error.  As noted in my earlier comments, I lost my environment and had to re-create it.  Once I did, the problem did not recur.

**Comment by mootezbessifi** [comment]
@tooda02  what was the exact version of kubernetes master and minion components that you were working with?
