### ISSUE TITLE
integration flake: FAILED: pods never started running timed out waiting for the condition

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/kubernetes#23503]
Integration test for #23287
```
F0325 11:41:38.824845   11413 integration.go:475] FAILED: pods never started running timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:57
  'KUBE_API_VERSIONS="v1,extensions/v1beta1" KUBE_TEST_API_VERSIONS="$1" "${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
Call stack:
  1: ./hack/test-integration.sh:57 runTests(...)
  2: ./hack/test-integration.sh:71 main(...)
Exiting with status 1
```

Full logs: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23287/kubernetes-pull-test-unit-integration/19365/

**Comment by dchen1107** [comment]
I quickly scanned through the log posted by @wonderfly, and I noticed that both pods are running on the node without any issues. Is it possible the known issue of delay watching? 

cc/ @yujuhong since you looked at this before.

**Comment by yujuhong** [comment]
As far as I can tell , `nginx-controller-rst26' was assigned to `127.0.0.1` but kubelet never *saw* the pod. 
On the other hand, `nginx-controller-iv0zh` was assigned to `localhost` and was running fine. 

Not sure if this is a watch or a kubelet issue.

**Comment by fejta** [comment]
Made a best guess at assigning this flake with no owner for 2 weeks

**Comment by yujuhong** [comment]
Removing the test in #25054

**Comment by yujuhong** [comment]
Closing since the tests in question have been removed.
