### ISSUE TITLE
move jobs examples to jobs site.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#23511]
per https://github.com/kubernetes/kubernetes/pull/17345#issuecomment-197153744

**Comment by erictune** [comment]
https://github.com/kubernetes/kubernetes.github.io/pull/252 adds to docs repo (with some styling issues).

**Comment by erictune** [comment]
https://github.com/kubernetes/kubernetes/pull/23513 deletes from this repo.

**Comment by spiffxp** [comment]
/assign
this has been fixed
