### ISSUE TITLE
deployment prestop timeout

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#23515]
Testing out prestop hooks on upgrades of deployments with kubernetes 1.2.0. I started with the attached test example deployment. (note the max values look weird cause I was doing it on a one node test machine. its unimportant to the conversation). I then changed the container tag to watch it change out the container and then did a kubectl apply on it. I see the docker exec sleep 60 get executed, but it only runs for 30 seconds before getting killed. So there is a timeout of 30 seconds somewhere that needs adjusting. I can't find anywhere to specify it in this use case. Is this a bug or did I just miss the right config value?

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testdeployment
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 10
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.io/elasticsearch:2.1
        lifecycle:
          preStop:
            exec:                
              command: ["bash", "-c", "sleep 60"]

**Comment by tomlanyon** [comment]
You should be able to increase terminationGracePeriodSeconds in your pod spec above the default of 30 seconds.

Reference: http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1_podspec

**Comment by kfox1111** [comment]
Ah. yup. that fixed it. Thank you very much.

Closing the issue.
