### ISSUE TITLE
RBD volume plugin uses rbd utility instead of kernel driver

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes/kubernetes#23518]
Currently the RBD volume plugin expects the rbd utility to be present on the host, as it just executes shell commands ([Example](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/rbd/rbd_util.go)). This means that  on hosts where Ceph packages are not available (i.e. CoreOS) RBD volumes cannot be used.

**Comment by thecanadianbaker** [comment]
While there are work-around methods, I propose that the dependency on the binary should be removed and instead the volume plugin should interact with the kernel module and coordinate locking, limiting the dependency to the host running a modern kernel.

**Comment by flyingcougar** [comment]
[go-ceph](https://github.com/ceph/go-ceph) binds to user space librbd and exposes it's API in go, there is no rbd kernel module involvement at all. In case @thecanadianbaker mentioned, maybe the best approach would be to implement rbd plugin in k8s like [this](https://github.com/ceph/ceph/blob/master/src/krbd.cc) ?

**Comment by elsonrodriguez** [comment]
Are we sure we want to incur the overhead of maintaining Ceph/RBD mounting logic directly in K8s?

What if something changes in the way Ceph volumes need to be mounted? What if there's incompatibilities between versions, how many versions of Ceph will the Kubernetes mounting logic need to support? What if there's a bug in the mounting logic?

With the issue count in Kubernetes slowly but surely cresting past 4,000, shelling out to somebody else's maintained binary seems like a code-bloat victory.

**Comment by chaosaffe** [comment]
This can be handled as part of the CSI initiative, and does not belong in upstream any longer
