### ISSUE TITLE
Default type for GCE dynamic volumes?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23525]
(Mostly a note to self to investigate...)

On GCE, we don't specify the type when creating a PD.  I think this means that dynamic volumes will be created as pd-standard.  pd-ssd is probably a more sensible default.

**Comment by chrislovecnm** [comment]
@bprashanth @bgrant0607 @smarterclayton is this still the case?  Cassandra really needs pd-ssd on gce :)  Let me know if I can hack it in temporarily .. like only provision ssd.

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-storage

**Comment by saad-ali** [comment]
> On GCE, we don't specify the type when creating a PD. I think this means that dynamic volumes will be created as pd-standard.

Correct, GCE PD creation [does not specify a type](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L2190) which defaults to `DISK_TYPE` `pd-standard` not `pd-ssd`.

> pd-ssd is probably a more sensible default.

Dynamic provisioning is an alpha feature, so we could change the default type without having to worry about backwards compatibility. That said, I think it makes sense to keep `pd-standard` (i.e. the cheap/default option) as be the default for dynamic provisioning. The storage classes work (design proposal from @pmorie https://github.com/kubernetes/kubernetes/pull/26908) will address the use case of being able to tweak the disk creation parameters and provide a mechinism for creating SSD PDs instead.

**Comment by chrislovecnm** [comment]
@saad-ali can someone point me toward how to specify only ssd? I may have to do a one off.  Also where the heck are the numbers for president ssd iops vs local spinning in GCE??

**Comment by saad-ali** [comment]
> @saad-ali can someone point me toward how to specify only ssd? 

You will need to specify the `Type` variable [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L2190) (currently not set). Example:

```GO
	diskToCreate := &compute.Disk{
		Name:        name,
		SizeGb:      sizeGb,
		Description: tagsStr,
		Type:   typeStr,
	}
```
Possible values for `Type` are `pd-standard` or `pd-ssd` (you'll want the latter).

> Also where the heck are the numbers for president ssd iops vs local spinning in GCE??

https://cloud.google.com/compute/docs/disks/performance

**Comment by chrislovecnm** [comment]
Much thanks!!!!!

**Comment by chrislovecnm** [comment]
@saad-ali I will let you know where my work is, not sure if it will be reusable, but maybe.

**Comment by saad-ali** [comment]
> @saad-ali I will let you know where my work is, not sure if it will be reusable, but maybe.

Sounds good!

> And the line number I think is here. https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L2213

Bah, the perils of linking to an everchanging HEAD

**Comment by chrislovecnm** [comment]
@saad-ali so you pointed me in the right direction ... eventually I will get there.  Just for documenting this...

'types' actually now takes a url.  Hopefully these docs are ok: https://cloud.google.com/compute/docs/reference/beta/disks#resource-representations

Which matches what `gcloud` tool gives yah.

```console
$ gcloud compute disk-types describe pd-ssd
creationTimestamp: '2014-06-02T11:07:28.529-07:00'
defaultDiskSizeGb: '100'
description: SSD Persistent Disk
kind: compute#diskType
name: pd-ssd
selfLink: https://www.googleapis.com/compute/v1/projects/aronchick-apollobit/zones/us-east1-c/diskTypes/pd-ssd
validDiskSize: 10GB-65536GB
zone: https://www.googleapis.com/compute/v1/projects/aronchick-apollobit/zones/us-east1-c
```

So I am implementing as:

```go
  diskToCreate := &compute.Disk{
                Name:        name,
                SizeGb:      sizeGb,
                Description: tagsStr,
                Type:        "https://" + path.Join("www.googleapis.com/compute/v1/projects/", gce.projectID, "zones", zone, "diskTypes", "pd-ssd"),
}
```

**Comment by JeanMertz** [comment]
Are GCE dynamic volumes still `pd-standard` only?

Using something like this doesn't seem to work (as in, I get a disk, but it's of `standard` class:

```yml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: europe-west1-d
```

Any thoughts on if this will be fixed in 1.5? I don't see a milestone attached, but the priority was recently added, so I guess there's a good chance this will make it in?

**Comment by JeanMertz** [comment]
Hmm, In fact, I can see [the type being implemented here](https://github.com/kubernetes/kubernetes/blob/dbc4121e16938d73ba66ee5f2ddc826347b5e471/pkg/cloudprovider/providers/gce/gce.go#L2488), so I'm not sure if I'm doing something wrong here, or if the offending code is somewhere else.

**Comment by saad-ali** [comment]
@JeanMertz The alpha version of dynamic provisioning, introduced in v1.2, hard coded all the parameters to pass to provisioners (including disk type). The beta version of dynamic provisioning, introduced v1.4, allows cluster administrators to set the parameters to use for provisioning by defining new `StorageClass` API objects. See [blog post](http://blog.kubernetes.io/2016/10/dynamic-provisioning-and-storage-in-kubernetes.html) and [GCE disk type handling code](https://github.com/kubernetes/kubernetes/blob/release-1.4/pkg/volume/gce_pd/gce_util.go#L88).

If setting `type: pd-ssd` in your storage class is not resulting in a SSD disk type, that sounds like a bug. Some things to verify, ensure that the annotation you are using on your PVC to trigger dynamic provisioning is beta, not alpha, e.g.: `"volume.beta.kubernetes.io/storage-class": "myStorageClass"`.

**Comment by pierreozoux** [comment]
I'm using GCE, and I didn't manage to make this storageClass working as expected.

Here is my kubectl version:
```
kubectl version 
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

Here is my default storage class:
```
kubectl describe storageclass default       
Name:		default
IsDefaultClass:	Yes
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"kind":"StorageClass","apiVersion":"storage.k8s.io/v1beta1","metadata":{"name":"default","creationTimestamp":null,"labels":{"kubernetes.io/cluster-service":"true"},"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"}},"provisioner":"kubernetes.io/gce-pd","parameters":{"type":"pd-ssd"}},storageclass.beta.kubernetes.io/is-default-class=true
Provisioner:	kubernetes.io/gce-pd
Parameters:	type=pd-ssd
No events.
```

And if I:
```
helm install --namespace production --set persistence.size=20Gi --set persistence.storageClass=default --name mongo stable/mongodb
```

the actual volume that get provisioned is a `standard` one and not an `ssd`.

I'd love to have this working :)

I just tried as @chrislovecnm said to s/pd-ssd/ https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west1-b/diskTypes/pd-ssd/g, but without success either.

**Comment by jsafrane** [comment]
@pierreozoux, please open a new issue for this so we don't pollute discussion about the default storage type with bugs. And please post `kubectl get pvc -o yaml && kubectl get storageclass -o yaml` there and tag me, thanks!

**Comment by chrislovecnm** [comment]
@justinsb can we close?

**Comment by msau42** [comment]
You can specify pd-standard and pd-ssd in the storageclass now.
/assign
