### ISSUE TITLE
http://$master-ip:8080/ui redirect is broken (for ubuntu)

### ISSUE THREAD

**Issue by pwais** [kubernetes/kubernetes#23523]
Using the Ubuntu startup guides, which sets up the dashboard in this context: https://github.com/kubernetes/kubernetes/blob/master/cluster/ubuntu/deployAddons.sh#L67

`http://$master-ip:8080/ui` redirects to `http://$master-ip:8080/api/v1/proxy/namespaces/kube-system/services/kube-ui/#/dashboard/` which is broken (shows [1]).  I poked around and this works instead: `http://$master-ip:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard`

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.4", GitCommit:"a5949fea3a91d6a50f40a5684e05879080a4c61d", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.4", GitCommit:"a5949fea3a91d6a50f40a5684e05879080a4c61d", GitTreeState:"clean"}
```

[1]
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "endpoints \"kube-ui\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kube-ui",
    "kind": "endpoints"
  },
  "code": 404
}
```

Looks like this feature gets broken a ton, maybe Google should test it. #12468 #13009 #11684

**Comment by srikanthpeetha** [comment]
I think you can manually launch kube-ui  using this
`kubectl create -f cluster/addons/kube-ui/kube-ui-rc.yaml`
`kubectl create -f cluster/addons/kube-ui/kube-ui-svc.yaml`
#10697


You can check the direct link to access the dashboard using
`kubectl cluster-info`

I had a testing cluster with server version 1.2.0. For me 
`http://$master-ip:8080/ui` is perfectly redirecting to `http://$master-ip:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard`

I think this a problem with may be older vesrion. I faced similar problem with v1.1.7

**Comment by pwais** [comment]
Ah ok I will see if a newer release works for me. Thanks!

**Comment by dchen1107** [comment]
Thanks for reporting the issue.
