### ISSUE TITLE
Make storage.Preconditions a function

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#23528]
In #22965, it introduced storage.Preconditions as very specific struct:
```
type Preconditions struct {
 	// Specifies the target UID.
 	UID *types.UID `json:"uid,omitempty"`
 }
```

It'd better to make this a predicate function:
```
type Precondition func(uid types.UID) bool
```

The immediate reason is for testing. Nonetheless, changing it to a function would give user more flexibility to do dynamic checking, logging, etc.

**Comment by lavalamp** [comment]
Sorry, but-- no, it's not good to have it be a function. The reason is that if it's a function, there's no possibility of passing it down into the storage layer to have the constraint enforced there.

**Comment by lavalamp** [comment]
I mean, you're of course welcome to argue with me. But I don't see advantages to making it a function, and it's not clear to me what your function signature implies.
