### ISSUE TITLE
Ubernetes: Where to put the code

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#23557]
We will have ubernetes code that is similar to a lot of kubernetes code in the following directories:

* cmd/kube-apiserver
* pkg/apis
* pkg/client
* pkg/controller
* api/swagger-spec
* docs/api-reference

The current PRs are adding ubernetes code to these directories.

@madhusudancs and I think that creating a new pkg/ubernetes directory and putting all ubernetes code their seems better. 
We can have cmd/, apis/, client/, controller/ sub directories under that.
In future, we can move pkg/ubernetes code into a separate repository.

What do others think? I think @lavalamp had also suggested creating a new directory to contain all ubernetes code.

Is pkg/ubernetes the right name? or is pkg/clusterfederation better?

@kubernetes/sig-cluster-federation @kubernetes/sig-api-machinery

**Comment by nikhiljindal** [comment]
Ref existing ubernetes PRs: https://github.com/kubernetes/kubernetes/pull/23509 and https://github.com/kubernetes/kubernetes/pull/23430

**Comment by lavalamp** [comment]
I pretty strongly think as much as possible should go under cmd/uber-apiserver/...

That is:

`cmd/uber-apiserver/pkg/apis/...` (maybe without the pkg/)

Client is interesting, what would be going under there? Anything that @caesarxuchao's client generator won't make?

Controllers should maybe go under `cmd/uber-controller-manager/pkg/...`.

@quinton-hoole

**Comment by smarterclayton** [comment]
I prefer clusterfederation to ubernetes.

**Comment by lavalamp** [comment]
If you do add stuff under pkg/ then I agree it'd be good to start with pkg/clusterfederation/... or pkg/cluster/federation/...

**Comment by nikhiljindal** [comment]
Yes we will have clientset_generated in pkg/client.
Do we want to put the ubernetes clientset at the same place?

We will also have api-ref docs and swagger-spec of the ubernetes server.
We can put them under pkg/clusterfederation/swagger-spec or alongside the kubernetes swagger-spec at api/swagger-spec (same for api-ref docs).

**Comment by nikhiljindal** [comment]
@lavalamp how about `clusterfederation/cmd/uber-apiserver` and `clusterfederation/cmd/uber-controller-manager` and `clusterfederation/client/clientset_generated`?

**Comment by smarterclayton** [comment]
How about federated-apiserver?   I don't hate uber as a prefix, but I
like being specific about what the point of it is.

**Comment by lavalamp** [comment]
The issue is there's two sorts of federation: multiple apis in the same
cluster, vs multiple clusters. "federation" by itself will be very
confusing.

**Comment by smarterclayton** [comment]
I don't know that API federation is as big a deal as cluster
federation (I would just say you register more APIs) but I concede the
point.

**Comment by quinton-hoole** [comment]
I'd like us to stick to semantic names rather than "brand" names, i.e. clusterfederation rather than uber... 
I like Daniel's suggestion of cluster/federation.

**Comment by lavalamp** [comment]
The thing that makes it super confusing is that ubernetes will probably
want both kinds of federation...

**Comment by madhusudancs** [comment]
I started thinking about this after our discussion. Is there a reason to not make this a root-level directory? kubernetes/federation?

Also, I think we should drop "cluster" and just call it "federation". Kubernetes is a cluster management system and "federation" means federation of clusters. It is implicit. API federation can then be called apifederation, if we need a separate directory.

**Comment by smarterclayton** [comment]
+1

**Comment by lavalamp** [comment]
I can live with that.

**Comment by nikhiljindal** [comment]
Great. Looks like we have consensus on adding a top-level directory named `federation` and putting ubernetes code there.

There is a somewhat related discussion on what should be the API groupname for Ubernetes resources (like `cluster`, which is used to keep track of clusters registered with the ubernetes server). I assume we can use `federation` there as well.

**Comment by quinton-hoole** [comment]
Cool.  I'm good with that in principle.  We just need to make sure that existing Kubernetes API clients, config files etc work correctly against Ubernetes, ideally with zero change, or in the worst case with trivially small change (e.g. a change to an API group name in one place the config).  Daniel and I discussed this briefly this morning. We don't forsee it being a problem - I just want to make sure that everyone's clear that it's an important requirement, and should not be overlooked.

**Comment by madhusudancs** [comment]
@quinton-hoole Sure, point noted.

**Comment by quinton-hoole** [comment]
@madhusudancs @nikhiljindal Thanks for bringing this to consensus.  Can we close this issue now?

**Comment by nikhiljindal** [comment]
Closing this since we now have the top level federation directory: https://github.com/kubernetes/kubernetes/pull/23509
