### ISSUE TITLE
cloud.Instance.NodeAddress() --node-ip to generate list of node addresses

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#23568]
https://github.com/kubernetes/kubernetes/pull/18541 adds a node-ip flag to kubelet.  However, it's only used for non-cloudprovider case.  The same can also happen in a cloud environment (e.g. if you want to form a private network in the cloud).   

Passing --node-ip to NodeAddress() can give hint to cloudprovider plugin.

**Comment by kokhang** [comment]
Hi @ddysher, I also would like a solution for this issue as we deploy kubernetes with cloud provider.
Do you have a fix for this at the moment?

**Comment by ddysher** [comment]
In one cloud provider, we query private ip via its API; in another, there is no such API, we have to find it in kubelet (listing all interface and filter), a bit hacky, but works.

**Comment by kokhang** [comment]
@ddysher i provided a fix. Can you review it if that works for you?
