### ISSUE TITLE
Dockerfile's CMD / ENTRYPONT ignored

### ISSUE THREAD

**Issue by ibalashov** [kubernetes/kubernetes#23571]
It seems that in order to start container in a pod we always needs to specify a command, either in yaml 
``` 
command: [ "bin/bash", "-c", "mycommand" ]
```
or programmatically:

```
  def setCmd(job: Job, cmd: List[String]) = {
    job.getSpec.getTemplate.getSpec.getContainers.toList.head.setCommand(cmd)
  }
```

Otherwise container runs just with plain `Args`, and no `CMD` and `ENTRYPOINT` is prepended to command line. 

Is this expected or something not right in my env?

**Comment by zhouhaibing089** [comment]
The docker file you used to create the image could also specify an `ENTRYPOINT`.

**Comment by ibalashov** [comment]
If I run the image with `docker run -ti imageId`, the `CMD` section in Dockerfile does run. However, the same image in k8s with `setArgs` only – the `CMD` section of Dockerfile is not run.

**Comment by a-robinson** [comment]
cc @kubernetes/sig-node

**Comment by thockin** [comment]
Kubernetes "command" == Docker "entrypoint"

Kubernetes "args" == Docker "cmd"

It's unfortunate that Docker's naming and semantics are so brain-damaged
(understanding full well that it evolved, so such is the way of things).
There is no way to use docker's CMD *and* add more args.

Specifically:

**Comment by yifan-gu** [comment]
@ibalashov Could you please post what's in the image's ENTRYPOINT and CMD? Also how's your container spec look like?

**Comment by ibalashov** [comment]
@thockin Thanks, that was helpful.

The combination of Docker's `ENTRYPOINT` + Kubernetes `setArgs` seems to be working fine.

Also found this #8235

Closing.

**Comment by vishh** [comment]
cc @kubernetes/kubernetes-docs-maintainers - If this is not documented already, we should fix that.
