### ISSUE TITLE
AWS Feature: GPU support

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23587]
GPU support, both assigning only to nodes that support GPUs & ensuring that we don't overcommit GPUs.

**Comment by justinsb** [comment]
@therc you said you would work on this :-)

**Comment by zhouhaibing089** [comment]
@chengyli to know this.

**Comment by a-robinson** [comment]
Cross reference #19049, #17035,

**Comment by brandoncole** [comment]
Watching this closely, this will definitely help us!  Kudos to taking this on for v1.3!

**Comment by therc** [comment]
I'm trying to implement this through Docker volume plugins, since that's already been requested in https://github.com/kubernetes/kubernetes/issues/16405 and would reduce the amount of custom code (we still need to pass `--device` somehow... docs coming).

**Comment by therc** [comment]
@brandoncole what instance types do you use? For v0 I am targeting g2.2xl.

**Comment by gopinatht** [comment]
@therc Answering on behalf of @brandoncole (I work with him). We are using g2.2xl so that works perfectly for us.

**Comment by brandoncole** [comment]
@therc We would be pretty happy with g2.2xl to start with.  We're also running Kubernetes on a pretty large scale internally with machines that have multiple NVidia GPUs which we'd love to take advantage of and schedule accordingly as well eventually.  @gopinatht is our main guy for this! :+1:

**Comment by Hui-Zhi** [comment]
@therc Docker already support GPU, but the K8s doesn't have the "--device" ability, could you let know the details about "implement this through Docker volume plugins"? I enabled the "--device" in my repo, but the code still need to refine. And so far it works with NVIDIA GPU. Have tested that.

**Comment by Hui-Zhi** [comment]
#19049

**Comment by therc** [comment]
@Hui-Zhi I'm almost done with the design doc. I'll send it out tomorrow. You're right that `--device` is needed. That's the most invasive set of changes. I refer to my work as v0, as it involves few changes to the Kubernetes daemons and keeps most of the new code in external ones. Your work is v1, where the scheduling and runtime configuration are more sophisticated and robust, plus they live inside kube-scheduler and kubelet.

**Comment by davidopp** [comment]
@justinsb Now that our v0 GPU support has merged, are there any AWS-specific bits needed to enable it on AWS?

**Comment by Hui-Zhi** [comment]
I filed a new issue to collect the details needed and risks for NVIDIA GPU workloads, also have some tech needed for kubelet. @davidopp Could you give some feedback on it?
#25557

**Comment by justinsb** [comment]
Moving to 1.4

**Comment by justinsb** [comment]
Actually @therc perhaps you can comment on the GPU support that is merged and what (if anything) we need to do additionally for AWS?

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5

**Comment by dims** [comment]
@justinsb all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/sig-aws

**Comment by calebamiles** [comment]
@justinsb, how do you feel about closing this issue or moving it out of the 1.5 milestone because there have been no updates to this issue in quite some time.


**cc: @saad-ali, @dims**

**Comment by cmluciano** [comment]
Can this issue be closed since multi-GPU support is merged with #42116 ? I have a follow-up proposal for some other features kubernetes/community#414

**Comment by dchen1107** [comment]
Close this one, and please address the rest enhancement separately. Thanks!
