### ISSUE TITLE
AWS: running kube-up simultaneously fails

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23588]
Because we don't scope kubectl - we should specify a content directly.

**Comment by paralin** [comment]
Add new context -> specify --context= in the command line. This doesn't damage the user's existing contexts anyway. Could even add a prompt to ask if they want to switch contexts / if there is none already set it as the current-context.

**Comment by justinsb** [comment]
Given kube-up is in maintenance mode, we aren't going to fix this I believe.
