### ISSUE TITLE
Chaning Service from LB to ClusterIP should clear status.ingress right away

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#23583]
I swear this used to work properly, but fails on my cluster (1.2).  No test == broken, as usual.  It does eventually clear.

@ArtfulCoder @justinsb

**Comment by bprashanth** [comment]
Why? I'd want to know if some public ip is pointing to my service, till that ip is torn down. Or do you just mean from a backkward compatibility perspective

**Comment by thockin** [comment]
The NodePort is cleared instantly (it's deactivated async, but we don't
wait for ACK from all nodes before clearing).

I could maybe buy keeping this behavior, but I can say that it is not
intended, and somewhere there is a block of code that THINKS it is clearing
this...  or there was...

**Comment by bprashanth** [comment]
We should get to the bottom of the bug (it might be related to the /status endpoint we added in 1.2 and needing a new status update), but I think if we fail to cleanup the loadbalancer we should leave some clue around that the user needs to follow up

**Comment by roberthbailey** [comment]
Has anyone followed up on this in the last two months?

**Comment by thockin** [comment]
I could be talked into defining this as correct, but it needs to be intentional, and as-is we don't know why.

**Comment by cmluciano** [comment]
/unassign @bprashanth 

@kubernetes/sig-network-bugs Anyone know if this is something that is still happening frequently?

**Comment by thockin** [comment]
I think it still happens.  As before, I could accept this as "correct" if
we understood why it changed.
