### ISSUE TITLE
Failed to pull image "gcr.io/google_containers/guestbook:v2"

### ISSUE THREAD

**Issue by edevil** [kubernetes/kubernetes#23584]
I was following the [guide](https://github.com/kubernetes/kubernetes/blob/release-1.1/examples/guestbook-go/README.md#step-five) but the [replication controller](https://github.com/kubernetes/kubernetes/blob/master/examples/guestbook-go/guestbook-controller.json) references an image that I cannot find:
```
Mar 29 15:18:05 minion1 kubelet-wrapper[773]: W0329 15:18:04.577928     773 manager.go:1897] Failed to pull image "gcr.io/google_containers/guestbook:v2" from pod "guestbook-jbp6n_default" and container "guestbook": image pull failed for gcr.io/google_containers/guestbook:v2, this may be because there are no credentials on this request.  details: (Tag v2 not found in repository gcr.io/google_containers/guestbook)
```

**Comment by zhouhaibing089** [comment]
@edevil you should use image `kubernetes/guestbook:v2` instead of `gcr.io/google_containers/guestbook:v2`. see here for the documents https://github.com/kubernetes/kubernetes/blob/release-1.2/examples/guestbook-go/guestbook-controller.json.

**Comment by edevil** [comment]
@zhouhaibing089: Yeah, I've since checked out the release branch and have used that. I just wasn't sure you guys were aware of the missing images but I guess using the master branch is asking for trouble. :)

**Comment by zhouhaibing089** [comment]
@luebken I see you committed this change, however the image used there did not work: https://github.com/kubernetes/kubernetes/commit/1531700f4230011a844b052840e3c75ed2bfa697

```sh
$ docker pull gcr.io/google_containers/guestbook:v3
Pulling repository gcr.io/google_containers/guestbook
Tag v3 not found in repository gcr.io/google_containers/guestbook
```

**Comment by luebken** [comment]
@edevil: as @zhouhaibing089 pointed out please use `kubernetes/guestbook:v2` it should work fine for release 1.2

@zhouhaibing089 thanks for pointing to the missing image. we need to push it (discussed here https://github.com/kubernetes/kubernetes/pull/21314#issuecomment-187831435 ) /cc @zmerlynn

**Comment by zmerlynn** [comment]
`gcr.io/google_containers/guestbook:v3` has been pushed, sorry for the inconvenience.
