### ISSUE TITLE
authz refactorred to act more like plugin model

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#23585]
Currently if we would like to add a new authorizer, we have to modify the code in `pkg/apiserver/authz.go` to reflect this, and it is not just add one more package import, but also do some modification here:

``` go
const (
    ModeAlwaysAllow string = "AlwaysAllow"
    ModeAlwaysDeny  string = "AlwaysDeny"
    ModeABAC        string = "ABAC"
    ModeWebhook     string = "Webhook"
)

// Keep this list in sync with constant list above.
var AuthorizationModeChoices = []string{ModeAlwaysAllow, ModeAlwaysDeny, ModeABAC, ModeWebhook}
```

also here:

``` go
for _, authorizationMode := range authorizationModes {
    if authorizerMap[authorizationMode] {
        return nil, fmt.Errorf("Authorization mode %s specified more than once", authorizationMode)
    }
    // Keep cases in sync with constant list above.
    switch authorizationMode {
    case ModeAlwaysAllow:
        authorizers = append(authorizers, NewAlwaysAllowAuthorizer())
    case ModeAlwaysDeny:
        authorizers = append(authorizers, NewAlwaysDenyAuthorizer())
    case ModeABAC:
        if config.PolicyFile == "" {
            return nil, errors.New("ABAC's authorization policy file not passed")
        }
        abacAuthorizer, err := abac.NewFromFile(config.PolicyFile)
        if err != nil {
            return nil, err
        }
        authorizers = append(authorizers, abacAuthorizer)
    case ModeWebhook:
        if config.WebhookConfigFile == "" {
            return nil, errors.New("Webhook's configuration file not passed")
        }
        webhookAuthorizer, err := webhook.New(config.WebhookConfigFile)
        if err != nil {
            return nil, err
        }
        authorizers = append(authorizers, webhookAuthorizer)
    default:
        return nil, fmt.Errorf("Unknown authorization mode %s specified", authorizationMode)
    }
    authorizerMap[authorizationMode] = true
}
```

maybe we should change it a little bit to move some logic into the separate plugin package, so whenever we implement a new authorizer, we just add a simple package import which is very like what we do for cloudprovider, and, maybe `authn.go` also should be considered.

**Comment by zhouhaibing089** [comment]
@liangjinebaycom do you have any thoughts?

**Comment by quinton-hoole** [comment]
Assigning to etune@ to add priority label.

**Comment by zhouhaibing089** [comment]
@erictune any comments about this, if it does have some value, I would volunteer to do some findings here.

**Comment by erictune** [comment]
I am hoping that future authorizer development uses webhook where possible.  If that is not possible, I'd like to understand why before doing an executable-plugin type of model.

**Comment by zhouhaibing089** [comment]
I think my point is about making things easier for downstream, with a executable-plugin mode, the downstream does not need to touch this file necessary, thus a cleaner code..

**Comment by erictune** [comment]
With webhook, downstream does not have to touch this file either, IIUC.

**Comment by zhouhaibing089** [comment]
Yeah, webhook is an option to go, if all with webhook, then that would be okay, however what if we have to inline an auth plugin into k8s? For example, if we want to keep things easy for maintaining and do not expect one more project, that is just a random thought from me, I believe people would still be doing this to inline into the code instead of write a webhook..

Another idea, how will we manage the webhooks, along with the image policy, I think things may become crazy if we are going to add more and more, should there be a unified interface for webhook, let us say something like Github Webhook...

**Comment by liggitt** [comment]
webhook is preferred method for injecting additional authorization methods
