### ISSUE TITLE
Can't create sample Job using extensions/v1beta1 API Group on v1.2.0-alpha.6

### ISSUE THREAD

**Issue by balopat** [kubernetes/kubernetes#23599]
I'm using multi-node docker v1.2.0-alpha.6 on RHEL7.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6", GitCommit:"cf7d2af14a47bf9ee1e05078b384075fdfd09ec8", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6", GitCommit:"cf7d2af14a47bf9ee1e05078b384075fdfd09ec8", GitTreeState:"clean"}
```

Based on the guide: http://kubernetes.io/docs/user-guide/jobs/ I should use the batch/v1 apiVersion to create a job, but that API group seems to be unsupported: 

```
$ cat job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
$ kubectl create -f job.yaml
error validating "job.yaml": error validating data: API version "batch/v1" isn't supported, only supports API versions ["v1" "metrics/v1alpha1" "extensions/v1beta1" "componentconfig/v1alpha1"]; if you choose to ignore these errors, turn validation off with --validate=false
```

If I change it to extensions/v1beta1 then I seem to run into a bug with regards to the selector handling. I skimmed through the job selector design doc, but I just learned that this should work out of the box without specifying selectors. 

```
$ cat job.yaml
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: pi
spec:
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
$ kubectl create -f job.yaml
The Job "pi" is invalid.

* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: null: `selector` does not match template `labels`
```

Any help is appreciated, thank you!

**Comment by a-robinson** [comment]
@erictune, was the selector changed between v1beta1 and v1?

**Comment by soltysh** [comment]
@balopat there's a selector difference between `batch/v1` and `extensions/v1beta1`. For the former the first example will work ootb, since the server will generate the selectors for you. For the former you need to force using the generated selectors with `.spec.autoSelector = true`. By default it's not set which keeps the old behavior of working with manual selectors. That's why you're getting the error.

**Comment by balopat** [comment]
@soltysh thanks for the suggestion! I might be doing something wrong, but it didn't seem to work: 

```
$ cat job.yaml
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: pi
spec:
  autoSelector: true
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
$ kubectl create -f job.yaml
error validating "job.yaml": error validating data: found invalid field autoSelector for v1beta1.JobSpec; if you choose to ignore these errors, turn validation off with --validate=false
$ kubectl create -f job.yaml --validate=false
The Job "pi" is invalid.

* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: null: `selector` does not match template `labels`

```

**Comment by soltysh** [comment]
@balopat I've just checked this against 1.2 release branch and it's working for me correctly. Can you show me the exact version (`kubectl version`) what you're running?

**Comment by balopat** [comment]
Hi @soltysh 

This is a multi-node docker v1.2.0-alpha.6, manually downloaded kubectl.
This might be a hyperkube-only issue? Not sure. 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6", GitCommit:"cf7d2af14a47bf9ee1e05078b384075fdfd09ec8", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.6", GitCommit:"cf7d2af14a47bf9ee1e05078b384075fdfd09ec8", GitTreeState:"clean"}
```

As you can see the binaries I'm using are the gcr.io version v1.2.0-alpha.6"

```

$ docker ps -a
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS              PORTS               NAMES
d389e497358f        gcr.io/google_containers/hyperkube-amd64:v1.2.0-alpha.6   "/hyperkube scheduler"   47 hours ago        Up 47 hours                             k8s_scheduler.4270ff53_k8s-master-master.redacted-domain.com_default_d90f2097bb62f69806c88fc9dc390445_7d161fa6
4738f56b2395        gcr.io/google_containers/hyperkube-amd64:v1.2.0-alpha.6   "/hyperkube apiserver"   47 hours ago        Up 47 hours                             k8s_apiserver.1e1f4116_k8s-master-master.redacted-domain.com_default_d90f2097bb62f69806c88fc9dc390445_6f1c1447
0f1419b38cae        gcr.io/google_containers/hyperkube-amd64:v1.2.0-alpha.6   "/hyperkube proxy --m"   47 hours ago        Up 47 hours                             k8s_kube-proxy.4e393dc3_k8s-proxy-master.redacted-domain.com_default_e513e62ea641585218de8b3495fc7a21_c683446a
0b606edc73d2        gcr.io/google_containers/hyperkube-amd64:v1.2.0-alpha.6   "/hyperkube controlle"   47 hours ago        Up 47 hours                             k8s_controller-manager.2f421a5e_k8s-master-master.redacted-domain.com_default_d90f2097bb62f69806c88fc9dc390445_59eed136
f524dfd9b284        gcr.io/google_containers/pause:2.0                        "/pause"                 47 hours ago        Up 47 hours                             k8s_POD.6059dfa2_k8s-proxy-master.redacted-domain.com_default_e513e62ea641585218de8b3495fc7a21_d888b556
b5b1bfabfab2        gcr.io/google_containers/pause:2.0                        "/pause"                 47 hours ago        Up 47 hours                             k8s_POD.6059dfa2_k8s-master-master.redacted-domain.com_default_d90f2097bb62f69806c88fc9dc390445_a4eb08de
7433cd502dad        gcr.io/google_containers/hyperkube-amd64:v1.2.0-alpha.6   "/hyperkube kubelet -"   47 hours ago        Up 47 hours                             naughty_pasteur
9d0a06227eb3        gcr.io/google_containers/hyperkube-amd64:v1.2.0-alpha.7   "/hyperkube controlle"   47 hours ago        Created                                 k8s_controller-manager.e2654dfb_k8s-master-master.redacted-domain.com_default_d08ea44229cf48249a900710d1f9930b_06453e79

```

Please [see my comment here](https://github.com/kubernetes/kubernetes/issues/20514#issuecomment-202982104) for the reason I'm not going higher in versions, and please see [my stackoverflow question to understand why I'm using multi-node docker](http://stackoverflow.com/questions/36141438/where-is-the-kubernetes-extensions-api-group-in-rhel-7-2).

**Comment by soltysh** [comment]
@balopat can you show me the versions you have enabled on the server using either `kubectl api-versions`, eventually do the same with `curl http://127.0.0.1:8080/apis` to get additional apis and check what objects are within do `curl http://127.0.0.1:8080/apis/batch/v1` to get objects available inside `batch/v1`. I'd like to see what is enabled inside your cluster. I'm assuming the extended APIs are disabled there.

**Comment by bgrant0607** [comment]
IIRC, this was a bug that was fixed later. Please upgrade to 1.2.1.

**Comment by balopat** [comment]
I managed to build a docker multinode image behind the proxy, so I could try it with 1.2.1, and **I confirm that the job creation works in 1.2.1.** Thank you!

**Comment by vinayk06** [comment]
@soltysh  can you explain where put those values. I am pretty much a new bee here. you r input is really helpful.
I am not trying to do anything fancy but just trying the examples given by redhat-atomic site.

https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/getting-started-with-containers/

I was trying to create replicaton-controller for webserver.

**Comment by soltysh** [comment]
@vinayk06 reach me out on #openshift-dev on freenode and I'll help you step by step with what you need. It'll be much easier.
