### ISSUE TITLE
kubectl run creates non-deletable pod

### ISSUE THREAD

**Issue by luebken** [kubernetes/kubernetes#23604]
After creating a simple pod on an empty cluster I wan't able to delete it.

Way to reproduce:
```
kubectl run example --image=nginx
kubectl get rc
# empty
kubectl get pods
NAME                       READY     STATUS    RESTARTS   AGE
example-1934187764-swmqv   1/1       Running   0          38s
kubectl delete pod example-1934187764-swmqv

kubectl get pods
NAME                       READY     STATUS              RESTARTS   AGE
example-1934187764-l36b7   0/1       ContainerCreating   0          2s
example-1934187764-swmqv   1/1       Terminating         0          57s
kubectl get pods
NAME                       READY     STATUS    RESTARTS   AGE
example-1934187764-l36b7   1/1       Running   0          6s
```

Tested with GKE 1.2 and local vagrant (Mac) 1.2.

**Comment by thesandlord** [comment]
+1 on this

```
kubectl get deployments
```

This is the solution for this. In Kubernetes 1.2, run creates a deployment and not a replication controller.

We need to update our docs for the "run" example. Also, why is run creating a deployment vs a replication controller now?

I can update the docs and send in a PR if needed

**Comment by jayunit100** [comment]
yeah , the main definition in the docs should be clarified, this confused me to
- right now it says "job or deployment", it should differentiate why sometimes its a job, since semantics of jobs vs deployments are very different i think.

**Comment by a-robinson** [comment]
You guys aren't the only folks who've been confused by this.

cc @kubernetes/docs @kubernetes/kubectl @kubernetes/goog-gke

**Comment by a-robinson** [comment]
Doc fixes are always very welcome :)

**Comment by thockin** [comment]
It's more than just docs - formerly valid scripts are now invalid.  There
are many examples and blog posts and presentations that show the pattern of
`kubectl run foo` and `kubectl expose rc foo` and those are all broken
now.  We need a big info campaign.

**Comment by kargakis** [comment]
> right now it says "job or deployment", it should differentiate why sometimes its a job, since semantics of jobs vs deployments are very different i think.

Depends on the restart policy you want to run your image with. It used to be Replication Controller (restartPolicy=Always) vs Pod (restartPolicy=Never,OnFailure), now it is Deployment (same policy as RC) vs Job (same policy as Pod).

**Comment by luebken** [comment]
@thockin What was the reason for the change in behaviour?

**Comment by ihmccreery** [comment]
cc @janetkuo @bgrant0607

**Comment by janetkuo** [comment]
@luebken This is because [Deployments](http://kubernetes.io/docs/user-guide/deployments/) and [Jobs](http://kubernetes.io/docs/user-guide/jobs/) are higher level resources. It's easier to use them instead of managing replication controllers (when you want to do rolling update) and pods (when you want to make sure a number of pods successfully terminate) manually.

In case you still need the old behavior of `kubectl run`, you can set `--generator` to `run/v1` to create rc, and `run-pod/v1` to create pods.

**Comment by derekwaynecarr** [comment]
@thockin - maybe our presentations should have a giant * that shows the --generator used on this particular command.

**Comment by bgrant0607** [comment]
I posted a longer explanation here:
https://groups.google.com/forum/#!topic/kubernetes-announce/mOFVst-iNZY

**Comment by luebken** [comment]
@bgrant0607 great explanation. I love these postings (e.g. learned about expose). 

I learned a lot with this thread. Thanks!

We should think of a way of exposing these to the general audience. From the top of my head: a) have the release notes ready before releasing. b) have something like a "new and noteworthy" on the docs homepage. "hiding" something like this in the release notes would be a bummer.

**Comment by jmound** [comment]
Additionally, The docs at http://kubernetes.io/docs/user-guide/simple-nginx/ state that you can create a replication controller with `kubectl run my-nginx --image=nginx --replicas=2 --port=80` and to delete it with `kubectl delete rc my-nginx` which leaves the deployment intact.

**Comment by bgrant0607** [comment]
@timoreimann reported in #25248 that the following pages need to be updated:

* http://kubernetes.io/docs/user-guide/simple-nginx/
* http://kubernetes.io/docs/user-guide/pods/multi-container/
* http://kubernetes.io/docs/user-guide/walkthrough/k8s201/

There is at least one outstanding PR:
https://github.com/kubernetes/kubernetes.github.io/pull/198

**Comment by ewindisch** [comment]
+1. I ended up deleting a (non-production) cluster because I couldn't sort this out. It also seems that deployments do not list in 'kubectl get all', which only added to the confusion.

@janetkuo FYI, as a user renaming this issue made it difficult to find.

**Comment by janetkuo** [comment]
https://github.com/kubernetes/kubernetes.github.io/pull/198 for updating http://kubernetes.io/docs/user-guide/simple-nginx/ & http://kubernetes.io/docs/user-guide/pods/multi-container/

**Comment by bgrant0607** [comment]
Done

**Comment by roblapp** [comment]
I had to run `kubectl delete rc --all` to get rid of the Nginx pod. Note that the `--all`  will delete all replica controllers.
