### ISSUE TITLE
ClaimRef is not enforced when binding PVs to PVCs

### ISSUE THREAD

**Issue by erinboyd** [kubernetes/kubernetes#23615]
If a claim is created first that matches both accessMode and size defined by the PV with a pre-defined ClaimRef , it will match it instead of the PVC that is the named ClaimRef

**Comment by jayunit100** [comment]
cc  @kubernetes/sig-storage

**Comment by smarterclayton** [comment]
Someone was saying that there is a desire to not fix this, can someone explain?  Without this fix, there is no way to steer a particular PV to a given user / namespace / claim in a deterministic way, which makes administrators unable to predictably allocate a volume for a claim.  That is a very serious functional gap that would impact cluster bootstrapping where volumes have to be assigned to claims before a scheduler is started.

**Comment by smarterclayton** [comment]
I don't care about the exact mechanism, but it is a functional requirement to be able to steer volumes to claims in a race free and predictable path.

**Comment by markturansky** [comment]
can you provide steps and/or yaml to recreate?  

This exact scenario is covered in a unit test. I'm interested in learning where the bug is.

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/persistentvolume/persistentvolume_index_test.go#L535

**Comment by erinboyd** [comment]
@markturansky Create the PV with a specific ClaimRef:
  ClaimRef:
    Namespace: default
    Name: nsf-claim-prebind

Then create two claims:
One with the name and another with the same size and accessMode.

Submit the first claim before the named one, it will bind to the first one.

**Comment by markturansky** [comment]
Are you attempting to create the PV first with a claimRef and then create the PVCs?

**Comment by markturansky** [comment]
This works:

1.  Create 2 identical PVCs.   I used the ones in docs/user-guide/persistentvolumes/claims.  Edit "claim-02.yaml" to have to same capacity.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

2.  Add the claimRef to docs/user-guide-persistentvolumes/volumes/local-01.yaml.

Pre-bind to the 2nd one.  You'll need the UID (kubectl get pvc myclaim-2 -o yaml).

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0001
  labels:
    type: local
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: myclaim-2
    namespace: default
    uid: 43f18c16-f6a4-11e5-aee4-80e6500a981e
    resourceVersion: "15"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/somepath/data01"
```


That PV will only ever bind to myclaim-2.  It shouldn't matter that myclaim-1 is nearly identical.

**Comment by screeley44** [comment]
@markturansky - are you saying that the `uid` field is needed and not the `name` field meaning that for the prebind to work the pvc's need to already be created to collect the uid?  I would think that as a storage/openshift admin I would define and create the persistent volumes before I had pods be able to submit pvc's against it.

**Comment by smarterclayton** [comment]
I would expect the same - the UID is not required to make a bind from PV ->
PVC, it's required to handle races with deletions in the binder.

**Comment by erinboyd** [comment]
@markturansky I assume this is more how Dyn Prov works in that the PVC is created first, then the PV is matched. Does my use case not seem reasonable. Especially when considered brownfield deployments where an admin wants to create a PV to an existsing storage asset and wants to allow users to bind to that one specifically. Maybe you have an application that is reading from that storage and performing an action on it (ie. Data Analytics). Seems like both paths should be supported imo since in the non-dyn prov case, the admin is defining the storage and control over it.

**Comment by screeley44** [comment]
as a test, I added this snippet to the types.go

```
			// do one more search just for name
			if claim.Name == volume.Spec.ClaimRef.Name && claim.Namespace == volume.Spec.ClaimRef.Namespace {
```

if I didn't have this, the *exact match* condition would not occur and the claim would then search for any suitable claim to match a pv by other attributes (size, etc...).  I then submitted both claims and only the one I expected matched and bound:

```
[root@k8dev glusterfs]# kubectl get pvc
NAME                    STATUS    VOLUME           CAPACITY   ACCESSMODES   AGE
claim-gluster-nomatch   Pending                                             24s
claim-gluster-ref       Bound     pv-gluster-ref   1Gi        RWO           9s
```

what do we break if we add a second conditional based on namespace + name only?  Maybe there is a case for keeping the super strict match based on namespae + name + uid?

and maybe the same could be true, what if I didn't supply a name in my claimRef: but did supply a `uid` - I would probably hit a similar case based on existing code matching on all 3 fields exactly

```
			if claim.Name == volume.Spec.ClaimRef.Name && claim.Namespace == volume.Spec.ClaimRef.Namespace && claim.UID == volume.Spec.ClaimRef.UID {
				// exact match! No search required.
				return volume, nil
			}
```

Just thinking out loud here, so correct any false assumptions I have made

**Comment by erinboyd** [comment]
@jeffvance and I talked about just such a conditional. I think it makes sense if the ClaimRef exists - it is the matching mechanism. The size could still be used later for quota, but not for binding the claim.

**Comment by markturansky** [comment]
It used to be just Name and Namespace of the PVC, but we fixed a bug where a rapid deletion of the claim (which should release the volume) and subsequent re-creation of a claim with the same name would "bind" to the existing volume before it was able to be released.

UID was added because in the above scenario, those are 2 distinctly different claims.

**Comment by markturansky** [comment]
@erinboyd your brownfield use case is served by PersistentVolumeSelector.  You want the ability to label volumes and allow users to target specific ones.

**Comment by erinboyd** [comment]
@markturansky Selectors aren't strict. We are talking about a precise way to make this bind which guarantees the PVC is tied to a specific storage asset.

**Comment by smarterclayton** [comment]
That requires the user to ABSOLUTELY know for sure the target volume is
labelled a certain way, which is excessive.

The UID is required to be absolutely sure a known PVC (preexisting)
matches.  It is not required to match a PVC by name.

The right solution here is to match PV claim to a PVC if the PV is set to
name, ignoring UID.  Dynamic provisioning *should* set UID, but it is not
required.

**Comment by markturansky** [comment]
@smarterclayton that opens the race condition (which may be entirely correct, but this was an Origin/BZ bug I fixed) where you can delete and recreate a claim with the same name and it will bind to the same volume if that volume hasn't yet been "released" from the first claim.

**Comment by smarterclayton** [comment]
So in that case the volume would have the UID set on its claim ref, correct?

So the flow being:

1. Admin creates PV with name
2. User creates PVC with name
3. Binder observes PV with claim ref to PVC but without UID
4. Binder should update PV claim ref to have PVC uid
5. Binder updates PVC

Since the binder would normally go and update the PV claim ref, it seems
(based on my admittedly older understanding of the code) that allowing the
claim ref on the PV to be considered valid without UID, but then updating
it with UID, would then ensure that the resulting PVC was safe.  If a user
deletes the PVC after 3 but before 4, the PV would be claimed, but a new
PVC with the same name would not be bound.

**Comment by markturansky** [comment]
What you say works and I agree overall.  It allows the admin to target claims by name before the claim is created.

More nuance to the model:

```
on pv sync:
  pv.Spec.ClaimRef == nil:
      volume = available
  pv.Spec.ClaimRef != nil:
      claim is not found (404):
          volume = released  (user deleted their claim)
      claim is found:
          pv.Spec.ClaimRef.UID == nil
              volume = bound   (pre-bound by admin who knows namespace/name of claim)
          pv.Spec.ClaimRef.UID == claim.UID:
               volume = bound  (by binder/provisioner using the claim for an objectRef)
          pv.Spec.ClaimRef.UID != nil && pv.Spec.ClaimRef.UID != claim.UID:
                error state, fixes "different claim/same name" race
```

**Comment by erinboyd** [comment]
@smarterclayton can you please assign this bug to @jeffvance from my team, he will be fixing it.

**Comment by smarterclayton** [comment]
Can't assign here, but @jeffvance you're it :)

**Comment by jeffvance** [comment]
ack

**Comment by jeffvance** [comment]
Using this version of k8s (hack/local_up_cluster):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.1.18+812b9a47d6625b", GitCommit:"812b9a47d6625b0fd02af18f9b147720f3c6bfce", GitTreeState:"clean", BuildDate:"2016-03-30T02:48:27Z", GoVersion:"go1.5.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.1.18+812b9a47d6625b", GitCommit:"812b9a47d6625b0fd02af18f9b147720f3c6bfce", GitTreeState:"clean", BuildDate:"2016-03-30T02:48:27Z", GoVersion:"go1.5.3", Compiler:"gc", Platform:"linux/amd64"}
```
and this PV spec file referencing *ClaimRef*:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /opt/nfs  #export dir
    server: 192.168.122.73
  persistentVolumeReclaimPolicy: Recycle
  ClaimRef:
    Namespace: default
    Name: nfs-claim2
```
I get this create erro:
_error validating "nfs-pv2.yaml": error validating data: found invalid field ClaimRef for v1.PersistentVolumeSpec; if you choose to ignore these errors, turn validation off with --validate=false_


Instead, if is use `*volumeName*` in the PVC spec file:
```
piVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim3
spec:
  volumeName: nfs-pv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
then binding the PVC to the PV appears to work. More testing is needed which I will do shortly.

**Comment by markturansky** [comment]
@jeffvance I think it's the capitalization. Look at "ClaimRef" versus "claimRef" in the YAML.

**Comment by jeffvance** [comment]
@markturansky You're correct. When I change the PV spec to:
```
...
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
...
  claimRef:
    namespace: default
    name: nfs-claim2
```
then the PV is created. However, the claimRef is not shown in the `kubectl get pv` output:
```
# kc get pv nfs-pv2 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: 2016-03-31T01:41:02Z
  name: nfs-pv2
  resourceVersion: "845"
  selfLink: /api/v1/persistentvolumes/nfs-pv2
  uid: a0526a87-f6e1-11e5-a88c-5254008f071b
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /opt/nfs
    server: 192.168.122.73
  persistentVolumeReclaimPolicy: Recycle
status:
  phase: Available
```
So, even though **claimRef** was syntactically allowed in the PV spec, it didn't have any impact in the resulting PV object.

**Comment by jeffvance** [comment]
More on using **volumeName** in the PVC spec from my (https://github.com/kubernetes/kubernetes/issues/23615#issuecomment-203698259)[comment above]:

**Comment by saad-ali** [comment]
We've been having detailed discussions about refactoring the existing provisioner, binder, and recycler controllers and consolidating them in to a single controller. As part of this redesign we're planning on handling "pre-bound" claims. We'll discuss this design at tomorrow's SIG meeting (Thursday morning 9 AM PST).

CC @childsb @pmorie

**Comment by smarterclayton** [comment]
Ok, as long as we have agreement that "pre binding" volumes by admins for
consumption by PVCs that the admin later creates (guaranteeing the EXACT
volume the admin intends is bound to a specific PVC), I'm fine with
whatever the implementation is.

**Comment by screeley44** [comment]
@smarterclayton @erinboyd @markturansky @jeffvance 
as a temp fix until all the refactoring is done, why not add another conditional in types.go to also look for a match on name + namespace when claimRef is present and then in the binder if claimRef again is present and there is a match, just add the UID from claim into the pv that is bound to it (similar to what Clayton layed out above).  I mocked this up and seems to work fine, not sure of all implications but seems like a simple temp fix for now?

```
[root@k8dev glusterfs]# kubectl get pv pv-gluster-ref2 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: 2016-03-31T14:11:10Z
  name: pv-gluster-ref2
  resourceVersion: "47"
  selfLink: /api/v1/persistentvolumes/pv-gluster-ref2
  uid: 6b336500-f74a-11e5-a259-52540092b5fb
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    name: claim-gluster-ref2
    namespace: default
    uid: 7aa01cc7-f74a-11e5-a259-52540092b5f
```

**Comment by erinboyd** [comment]
ack @saad-ali 
looking forward to a lively discussion about it ;)

**Comment by jeffvance** [comment]
@erinboyd 's original issue was pv prebind --> pvc using claimRef in the pv spec. I've done some testing using **volumeName** in the pvc spec and ran into a similar issue -- namely the pv binds to the wrong pvc.

PV spec for "nfs-pv2":
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /opt/nfs
    server: 192.168.122.73
  persistentVolumeReclaimPolicy: Recycle
```
PVC spec with **volumeName** set to "nfs_pv1" (not "nfs-pv2", but otherwise matching capacity and accessModes):
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim3
spec:
  volumeName: nfs-pv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
1) create PV:
```
# kc create -f nfs-pv2.yaml 
persistentvolume "nfs-pv2" created
# kc get pv
NAME      CAPACITY   ACCESSMODES   STATUS      CLAIM     REASON    AGE
nfs-pv2   1Gi        RWO           Available                       1m
```
2) create PVC where **volumeName** specifies "nfs-pv1":
```
# kc create -f nfs-claim3.yaml 
persistentvolumeclaim "nfs-claim3" created
# kc get pvc
NAME         STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
nfs-claim3   Pending   nfs-pv1   0                        12s

# kc get pv
NAME      CAPACITY   ACCESSMODES   STATUS    CLAIM                REASON    AGE
nfs-pv2   1Gi        RWO           Bound     default/nfs-claim3             2m
```
Note that "nfs-pv2" is bound to the claim even though the claim was pre-bound to "nfs-pv1". But also see that the same claim is considered "Pending".

More details:
```
## PV:
# kc get pv nfs-pv2 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: 2016-03-31T17:03:13Z
  name: nfs-pv2
  resourceVersion: "489"
  selfLink: /api/v1/persistentvolumes/nfs-pv2
  uid: 74102e08-f762-11e5-bcbc-5254008f071b
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nfs-claim3
    namespace: default
    resourceVersion: "487"
    uid: bb2dfe69-f762-11e5-bcbc-5254008f071b
  nfs:
    path: /opt/nfs
    server: 192.168.122.73
  persistentVolumeReclaimPolicy: Recycle
status:
  phase: Bound

## PVC:
# kc get pvc nfs-claim3.yaml 
Error from server: persistentvolumeclaims "nfs-claim3.yaml" not found
[root@rhel7/nfs]# kc get pvc nfs-claim3 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2016-03-31T17:05:12Z
  name: nfs-claim3
  namespace: default
  resourceVersion: "487"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/nfs-claim3
  uid: bb2dfe69-f762-11e5-bcbc-5254008f071b
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-pv1
status:
  phase: Pending
```

**Comment by jsafrane** [comment]
Soo... as part of recycling, when we recycle a volume we mark it as Pending, still pointing to the old ClaimRef that's not existing. Binder controller then finds the volume and clears the ClaimRef.
https://github.com/jsafrane/kubernetes/blob/master/pkg/controller/persistentvolume/persistentvolume_claim_binder_controller.go#L242

This code then sees pre-bound PV that points to a claim that does not exists yet. It thinks that this volume has just been recycled and deletes the ClaimRef -> bug.

IMO, when we put the recycled volume back to Pending, its ClaimRef must be already cleared. The we won't need to have weird conditions for volumes in Pending state and everything becomes much clearer (and working).

@markturansky, was there any special reason to clean PV.ClaimRef in Pending state that we can't do it in Released state?

**Comment by thockin** [comment]
Can someone please explain more concretely (sorry, I am dumb that way) the use case for this?  It feels a little abstract and hypothetical to me.

Let's assume that you have a real use case.  Options:

1) allow pre-binding by pv.claimref and just handle it
2) wait for taints/toleration to be implemented
3) use a "reserved for" annotation (or new field) that is distinct from the claimref field, but equivalent
4) use a "reserved for" annotation that is basically a reverse-selector (only allow claims that have label X, e.g team=eng)  (this is basically taints)

I think we already have a solution for this in our revamped controller logic, so it's not a huge deal.  It's a weird semantic to me, and I would rather we not support it at all, if we could get away with it.  I don't understand the whole lifecycle.

What happens when:
* create PV pre-bound to PVC foo/mypvc
* create foo/mypvc
* run pod which uses foo/mypvc, writes data, exits
* delete foo/mypvc

What happens to the PV if the release policy is "recycle"?
* unbind, scrub, and make it available for anyone?
* unbind, scrub, and make it available on for the pre-bind PVC?

After writing all this, I think I prefer something like option 4 above.  Imagine a `PV.spec.claimSelector` field.  We will only bind a PV to a PVC that matches that selector.  To me, that is a much more general and obviously useful feature.

**Comment by screeley44** [comment]
@thockin   -  why is #4 from above any different than the current implementation - doesn't the claimRef: name + namespace accomplish the same?  Even better since we can isolate by project and a keyword value (name) or you don't like the idea of using the "name" and "namespace" fields and want a new special "taint" as those fields affect other things?

**Comment by smarterclayton** [comment]
The use case is an admin is bootstrapping a cluster, and wants to run a
service that uses a PV.  They want to create the PV during bootstrapping
(such and such disk).  Why would they want to specify a selector?  The
selector implies that they are happy that ANY PVC matches it, when in
reality this is a very 1-2 step.  Create a PV for a PVC.  Make sure the PVC
is using it.  Any possibility of failure / mismatch / accidental mismatch
violates the intent of the admin action.

In this case, we're creating the PV for a registry to be deployed on the
cluster.  During initialization, we create the PV for use with the
registry.  We don't want anyone else claiming it.  Anyone else even being
able to claim it would be an error.  We could create the registry PVC first
- but we don't want to bind to any random volume out of the pool - we want
to bind to a very specific volume.

Specifying the label seems like a pointless abstraction - I'm not intending
the PV to be used by "a class of PVCs".  It's for a specific set.

**Comment by erinboyd** [comment]
@thockin @smarterclayton @bc 
Use Case (PV->PVC with strict binding):

1) Storage asset exists (NFS server at 10.1.0.1:/finance/supersecretinfo/)
2) Admin creates PV with path to ^^ and populates claimRef with name: finance-pvc namespace:finance, with Recycle
---(PV is in Available 
---( check is added for binding to check name+namespace+UID, if claimRef exists then it will strictly enforce this when another claim tries to bind to the PV)

3) User Tom in namespace creates PVC with name finance-pvc
(PV is bound, UID from PVC is updated in the PV and status going to BOUND) (see @screeley44 hack above)

4) User Tom is done, deletes PVC
(Recycler scrubs volume and UID is removed (undoing the bind)) ClaimRef is kept intact. 

5) PV goes back to Available
(Maybe this is a gotcha where you can't ever get rid of it because then it's never in the Released state?? But wouldn't this be true of all volumes that are recycled? They are intended to be used again and again)

6) User Sally in project finance creates PVC to PV, repeat Step 3->>

I guess I don't see what the hassle is with recycling. If the VOLUME says to recycle it should be available for re-consumption. The only thing claimRef does is limit what PVC can consume it. Maybe I am missing something completely....

Pros: Claim doesn't have to exist when PV is created
Cons: Limited to namespace (though this could be a pro in some cases)
           Complicates current recycler in that it deletes the claimRef in the PV as part of recycling. It would need to know the original intent of the PV

User Case 2: (PVC->PV strict)
1) User creates a PVC with either a dyn prov annotation OR volumeName
2) Dyn Prov: Claim is created and UID generated. Process is kicked off to create PV. PV is created and then populated with UID to bind to PVC (possible race during update process? unless strict enforcement is done here. Dyn Prov is requesting particular storage type)
2b) volumeName: User specifies the claim with volumeName set to PV name
4) PVC is either bound or pending (not sure what happens when two simultaneous requests for the same volume come in at once, I assume it's pending if PV doesn't exist)
5) PV becomes available and UID is populated to create bind. Today, is this where the claimRef gets populated then?

How does user know they want to use that volume? Do they oc describe all the PVs to see if it's going to the server/path they want and then specify it? Am I guaranteed a SPECIFIC storage asset and location with this method? Dyn Prov I don't care. I just want a flavor of that storage, I am not going to a specific target supersecret path location, right? Am I going to have to add more logic to the PVC to obtain this when it's already a function of the PV to say what plugin and where?

**Comment by thockin** [comment]
> I guess I don't see what the hassle is with recycling. If the VOLUME says to recycle it should be available for re-consumption.

The hassle is that we use ClaimRef as part of the controller logic, and we unilaterally clear it upon recycle.  You're asserting that we must distinguish the case of a user-provided ClaimRef from a system-provided ClaimRef.  In our revamped logic (just pseudocode for now) we actually DO track that information, conveniently.  I just want to make sure we understand the semantics we expect.  pre-bound + recycle is a weird edge case, let's just decide and move on.  Keeping the pre-bound like is fine with me.

After a lot of discussion between storage folks, I think we can keep this "feature" and respect the user's wishes.  It will be covered in the pseudocode we post.

**Comment by erinboyd** [comment]
@thockin yep, I put that as a CON in my list. But since you are now tracking that with the new design I guess it's all good...except how we handle it now. We can modify the code to add in the UID to the PV after the PVC is bound and have the binding respect the claimRef...but in the near term we will need to figure out if we just don't support recycling in this case or what...

**Comment by jeffvance** [comment]
Here is a summary of the error cases when pre-binding via pv.claimRef or pvc.volumeName:
```# kc version
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.1.220+22f01f104188e2", GitCommit:"22f01f104188e211c3926a6f49a5bef90077ff2d", GitTreeState:"clean", BuildDate:"2016-04-07T21:00:22Z", GoVersion:"go1.5.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.1.220+22f01f104188e2", GitCommit:"22f01f104188e211c3926a6f49a5bef90077ff2d", GitTreeState:"clean", BuildDate:"2016-04-07T20:58:20Z", GoVersion:"go1.5.3", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by erinboyd** [comment]
@kubernetes/sig-storage where are we with this? I know it will be fixed in the next version but are we going to provide a patch in the mean time?

**Comment by ibotty** [comment]
That's fixed now, is it?

**Comment by smarterclayton** [comment]
Should be but prolly need a retest.

**Comment by jingxu97** [comment]
Since the PR #24682 was closed without merge, could anyone point out which PR is for fixing this? What is the behavior that user should expect "pre-bound" claims? What is the status for refactoring the existing provisioner, binder, and recycler controllers

**Comment by jeffvance** [comment]
@jingxu97 I think this issue is resolved by the binder controller rewrite. @erinboyd or I will verify tomorrow.

**Comment by jeffvance** [comment]
This is no longer an issue and can be closed.
Version:
```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0+507d3a7", GitCommit:"447cecf", GitTreeState:"clean", BuildDate:"2016-08-25T00:55:06Z", GoVersion:"go1.6.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.3.274+f839c5ffdf5062-dirty", GitCommit:"f839c5ffdf5062346766f0edbf1abf3ebd2dcd98", GitTreeState:"dirty", BuildDate:"2016-08-31T18:46:48Z", GoVersion:"go1.6.1", Compiler:"gc", Platform:"linux/amd64"}
```

Test:
pv with claimRef:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /opt/nfs  #export dir
    server: 192.168.122.73
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: nfs-claim3
```

Claim (not matched by pv's claimRef):
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
Create pv and pvc:
```
# kc create -f nfs-pv3.yaml 
persistentvolume "nfs-pv3" created

# kc create -f nfs-claim1.yaml 
persistentvolumeclaim "nfs-claim1" created

 # kc get pv,pvc
NAME             CAPACITY   ACCESSMODES   STATUS      CLAIM                REASON    AGE
pv/nfs-pv3       1Gi        RWO           Available   default/nfs-claim3             6m
NAME             STATUS     VOLUME        CAPACITY    ACCESSMODES          AGE
pvc/nfs-claim1   Pending
```

**Comment by smarterclayton** [comment]
Thanks!

**Comment by bambrozio** [comment]
I'm facing this problem. The issue was closed, but what's the solution?
My case: 

```
$ cat pv/pv.yml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-mongo-node-1
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /pv/mongo-node-1/data/db
    server: 9.162.163.148
---
(...)

$ cat pvc.yml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mongo-node-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
(...)

$ kubectl get pv,pvc
NAME                  CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS     CLAIM                      REASON    AGE
pv/pvc-mongo-node-1   8Gi        RWO           Retain          Released   default/pvc-mongo-node-2             12m
pv/pvc-mongo-node-2   8Gi        RWO           Retain          Released   default/pvc-mongo-node-3             12m
pv/pvc-mongo-node-3   8Gi        RWO           Retain          Released   default/pvc-mongo-node-1             12m

NAME                   STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
pvc/pvc-mongo-node-1   Pending                                      10m
pvc/pvc-mongo-node-2   Pending                                      10m
pvc/pvc-mongo-node-3   Pending                                      10m
```

**Comment by jeffvance** [comment]
@bambrozio Your 3 claims will remain Pending until a pv is Available for binding. All of your pvs are "Released" so no binding will occur. Did you delete the claims before generating the output above? For nfs volumes when a claim is deleted the volume is recycled, which deletes the data. What happens if you change the pv's ReclaimPolicy to "Delete" (since the data is deleted by nfs recycling anyway)?

**Comment by bambrozio** [comment]
Hi @jeffvance - Thanks for the answer.
I figure it out the problem. Actually my NFS configuration was wrong. The PVs (or even a mount command) was not creating the volumes. To fix it I have done:

Edit my "/etc/exports" in order to use the the netmask instead of the full IP ([my case my range was /16](https://www.ietf.org/rfc/rfc1878.txt))
```
$ cat /etc/exports
/pv/mongo-node-0/data/db        9.162.0.0/255.255.0.0(rw)
/pv/mongo-node-1/data/db        9.162.0.0/255.255.0.0(rw)
/pv/mongo-node-2/data/db        9.162.0.0/255.255.0.0(rw)
```

Then I restart the NFS server and deactivate the firewall:
```
Restart NFS server and configure the firewall:
sudo systemctl restart nfs-server
sudo firewall-cmd --permanent --zone=public --add-service=nfs
sudo firewall-cmd --reload
```

And then I changed my pv.yml a little bit:
```
$ cat ../templates/mongodb/pv.yml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-storage-mongo-0
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: mongo-persistent-storage-mongo-0
  nfs:
    path: /pv/mongo-node-0/data/db
    server: 9.162.163.112
---
(... repeat changing the path for each directory ..)
```

And thus my pvc.yml too:
```
$ cat ../templates/mongodb/pvc.yml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-mongo-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
(... repeat changing the metadata:name for each pv claimRef:name ..)
```

Then happy days!:
```
$ kubectl create -f pv.yml 
persistentvolume "mongo-persistent-storage-mongo-0" created
persistentvolume "mongo-persistent-storage-mongo-1" created
persistentvolume "mongo-persistent-storage-mongo-2" created
$ kubectl create -f pvc.yml 
persistentvolumeclaim "mongo-persistent-storage-mongo-0" created
persistentvolumeclaim "mongo-persistent-storage-mongo-1" created
persistentvolumeclaim "mongo-persistent-storage-mongo-2" created
$ kubectl get pvc,pv
NAME                               STATUS     VOLUME                             CAPACITY   ACCESSMODES                                AGE
mongo-persistent-storage-mongo-0   Bound      mongo-persistent-storage-mongo-0   8Gi        RWO                                        4s
mongo-persistent-storage-mongo-1   Bound      mongo-persistent-storage-mongo-1   8Gi        RWO                                        4s
mongo-persistent-storage-mongo-2   Bound      mongo-persistent-storage-mongo-2   8Gi        RWO                                        4s
NAME                               CAPACITY   ACCESSMODES                        STATUS     CLAIM                                      REASON    AGE
mongo-persistent-storage-mongo-0   8Gi        RWO                                Bound      default/mongo-persistent-storage-mongo-0             8s
mongo-persistent-storage-mongo-1   8Gi        RWO                                Bound      default/mongo-persistent-storage-mongo-1             7s
mongo-persistent-storage-mongo-2   8Gi        RWO                                Bound      default/mongo-persistent-storage-mongo-2             7s
```

Thank you very much again!

**Comment by arianitu** [comment]
Hello everyone, we are struggling to find a deterministic way of getting Kubernetes to NOT bind to a PV->PVC pair that is awaiting binding.

Here is what happened for us:

1. A GKE PersistentDisk was cloned containing sensitive data
2. A PV (let's call it PV1) with a ClaimRef and a PVC (PVC2) was created to bind that sensitive data to a Deployment (D1). 

Then in the cluster another Deployment (D2) with a new PVC (PVC3) was created in a completely different namespace while the above was happening. The PVC3 got binded to PV1 instead of PVC2 to PV1.

Is there no way to prevent dynamic PVCs from being attached to PV-PVC awaiting attachment? We tried to use LabelSelectors on the PVC but we got an error saying "GKE: Selectors not supported on PVCs.). The LabelSelector had a NOT EXISTS:

```
			Selector: &metav1.LabelSelector{
				MatchExpressions: []metav1.LabelSelectorRequirement{
					{
						Key:      "sensitive-pv",
						Operator: metav1.LabelSelectorOpDoesNotExist,
					},
```

What options are we left with? There appears to be no way to tell Kubernetes to NOT bind to a specific PV for a newly created PVC. 

Things to note, both PVCs have the same storage class, size and name, but different namespaces. But doesn't ClaimRef check both Name and Namespace? The sad reality is looking to be creating the disks manually and using the above LabelSelector, but then we can't use dynamically provisioned PVCs which really sucks for us,

Can someone help us understand what options we have here?

**Comment by jeffvance** [comment]
@arianitu Do you have the option of pre-binding the sensitive PV and PVC?

**Comment by arianitu** [comment]
@jeffvance it appears the issue we were running into with a library is that they were using volumeName only instead of ClaimRef which led to the above condition.

So I think my point above is moot since I assumed they were using ClaimRef but in reality they are using volumeName. I don't see VolumeName having any implications with PVC checking if a PV can be mounted (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/util/util.go#L214)

I've suggested they use ClaimRef instead, am I correct in my assumptions that ClaimRef will only bind to a PV if the Name and Namespace matches?

**Comment by jeffvance** [comment]
@arianitu Unless things have changed, binding is two ways: the PVC binds to the PV via `pvc.volumeName` and the PV binds to the pvc via `pv.claimRef` Both sides need to be filled-in for binding.
