### ISSUE TITLE
Turn off Travis

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#23611]
We have all of the checks that used to run only in Travis running in Jenkins, and it generally seems to be more reliable. We should just turn off Travis for PRs. (We might want to leave it running post-commit, just in case we ever want to go back?)

Necessary tasks:
- [ ] Make the submit queue not require a passing Travis run
- [ ] Make the munger not try to trigger Travis if it's missing
- [ ] Turn off the Travis webhook for PRs (need an owner of the project to do this)

cc @kubernetes/sig-testing @eparis

**Comment by ixdy** [comment]
One other issue is that Jenkins unit/integration is only running the same set of tests as Travis on `master`; there's still a disparity on `release-1.2` (and all older release branches). We can either

* (a) cherry-pick my changes (at least #22681) to `release-1.2`
* (b) keep Travis running on release branches (not sure if this is actually possible)
* (c) decide we don't care about the missing coverage
* (d) suggest something else?

**Comment by spiffxp** [comment]
(a) would be my vote, always in favor of fewer differences between release branches and master as far as test execution goes

**Comment by eparis** [comment]
- submit queue does not require travis

(b) is possible, but like today it will still run on mater
(c) I'm all for that, I think....

yall tell me, I'll fix the submit queue....

**Comment by ixdy** [comment]
Travis is having another bad day. We should just turn it off.

**Comment by spxtr** [comment]
I'm okay with (c).

**Comment by eparis** [comment]
How about we just remove .travis.yaml from master. That will keep travis running on release-1.2 but will stop it on master....

**Comment by jayunit100** [comment]
+1 to remove

**Comment by david-mcmahon** [comment]
I'm getting a travis timeout on release-1.2 #24897.  Maybe time to disable travis everywhere at this point?

**Comment by spxtr** [comment]
I think an admin just needs to go into the settings and remove it.

**Comment by eparis** [comment]
travis should now be dead (I think).
checks were not enforced on release-1.x branches, so it shouldn't have mattered.
travis is not longer 'required' on master.
long live no travis.

**Comment by eparis** [comment]
I'm closing this issue. reopen and ping me if I failed at killing travis.

**Comment by spxtr** [comment]
Thanks :)

There's still some docs and code mentioning travis, plus `.travis.yml`, but not too much.

**Comment by tmrts** [comment]
How about running lightweight tests first in Travis (verifying docs, licenses, commit messages etc.) so that it fails-fast if there are trivial mistakes to reduce load of Jenkins infra?

**Comment by ixdy** [comment]
@tmrts we'd been doing that for a bit, but Travis was having trouble keeping up even with that. (Part of the problem was likely that our verify-* checks have become very heavyweight.)

**Comment by eparis** [comment]
The straw the broke my back was when travis started failing even though the ONLY thing it was doing was

https://github.com/kubernetes/kubernetes/blob/master/.travis.yml#L5

seriously, echo-ing two lines started failing. I vote no to travis after that   :)

**Comment by tmrts** [comment]
@ixdy didn't realize that even the `verify-*` checks are heavyweight now

@eparis I don't think anybody would vote Travis after hearing what you described :smile:
