### ISSUE TITLE
Addon Manifests are Not Production Ready

### ISSUE THREAD

**Issue by danehans** [kubernetes/kubernetes#23620]
The contrib/ansible project is focused on deploying kubernetes in a production-ready fashion. For example, [1] and [2] hard-code env variables meant for developer deployments. Here are a few proposals for improving the addon manifests:
1. If they must be hard-coded, then the manifests should support production deployment requirements by default.
2. Turn the yamls into templates (i.e. Jinja) and support a minimal number of parameters that meet dev/prod deployment use cases.

The addon manifests should be opinionated by default, but flexible enough to support *_common *_ production use cases such as how services get exposed (NodePort, ClusterIP, etc..). Otherwise contrib/ansible and potentially other projects that leverage addons need to maintain variations of the manifests to meet production deployment requirements. This can lead to less than optimal user experience.

[1] https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml#L56-L67
[2] https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/grafana-service.yaml#L10-L12

/cc: @rutsky @adamschaub

**Comment by bprashanth** [comment]
I agree they shouldn't be hardcoded, templatizing them would also make e2e testing with stricter args easier. The addon-controller itself needs a re-write from bash to go. 

@kubernetes/sig-config

**Comment by roberthbailey** [comment]
@justinsb

**Comment by bgrant0607** [comment]
Ref #23233
