### ISSUE TITLE
Secrets are not working properly as environment variable

### ISSUE THREAD

**Issue by jadhavnitind** [kubernetes/kubernetes#23621]
I am running Kubernetes cluster on Google Container Engine. Trying to expose username and password as environment variable in the pod for tomcat webapp database connection. Its showing environment variable after login into the pod like below
root@testtomcat-hauaf:/usr/local/tomcat/conf# echo $DB_USERNAME
admin
root@testtomcat-hauaf:/usr/local/tomcat/conf# echo $DB_PASSWORD
Password

Try to echo it out of the pod it shows nothing/blanck in the environment variable.
$ kubectl exec -it testtomcat-hauaf echo $DB_USERNAME

$ kubectl exec -it testtomcat-hauaf echo $DB_PASSWORD

Same thing tried with secret mount point and its working fine and it shows mounted secrets in the pod like below but I am looking forward to use secrets as environment variable in the pods. Looks like exposing secrets as environment variable not working properly. Seems "source" command missed in the setps for the secrets expose.
$ kubectl exec -it testtomcat-skdae cat /etc/secrets/stage-username
admin
$ kubectl exec -it testtomcat-skdae cat /etc/secrets/stage-password
Password

Following are the YAML file which are using to create  secrets and RC.
cat db-user-pass.yaml 
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: vcs-db-secret
type: Opaque
data:
  stage-username: YWRtaW4K
  stage-password: UGFzc3dvcmQK

cat env-tomcatconfig.yaml 
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: testtomcat
  labels:
    app: testomcat
    name: testtomcat
spec:
  replicas: 2
  selector:
    app: testtomcat
  template:
    metadata:
      labels:
        app: testtomcat
    spec:
      containers:
        - name: testtomcatcontainer
          image: gcr.io/project/tomcat:7
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vcs-db-secret
                  key: stage-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vcs-db-secret
                  key: stage-password
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
             capabilities: {}
             privileged: true
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst

**Comment by jadhavnitind** [comment]
Tried adding "command: [ "/bin/sh", "-c", "env" ]" but its not working. Pods are going in "CrashLoopBackOff" mode.

**Comment by a-robinson** [comment]
Potentially related to #23629 and #23638

**Comment by pmorie** [comment]
@jadhavnitind can you try to reproduce with an image like busybox and `env` for the command?

**Comment by pmorie** [comment]
Reading this again, I am not certain if I think there is a bug - do you believe there is a bug because of the behavior of `kubectl exec`? If the env var is set correctly in the pod, the problem with kubectl exec may be that a buffer isn't being flushed.

**Comment by jadhavnitind** [comment]
@pmorie Tried to create new pod using busybox image but its giving me blank output at kubectl get pods command. But if I try to delete pod it shows deleted.

/kubernetes/docs/user-guide/secrets# kubectl create -f secret.yaml 
secret "test-secret" created
/kubernetes/docs/user-guide/secrets# kubectl create -f secret-env-pod.yaml 
pod "secret-env-pod" created
/kubernetes/docs/user-guide/secrets# kubectl get pods 

Tried to connect it and It gave me message like below
/kubernetes/docs/user-guide/secrets# kubectl create -f secret-env-pod.yaml
Error from server: error when creating "secret-env-pod.yaml": pods "secret-env-pod" already exists
/kubernetes/docs/user-guide/secrets# kubectl delete pods secret-env-pod
pod "secret-env-pod" deleted

Tried to creating new RC/pod with tomcat image using env for the command but its going in CrashLoopBackOff. Tried to create RC/Pod without "env command" and its working fine with tomcat image.

**Comment by sgrimee** [comment]
@jadhavnitind kubectl get pods does not show the pod because it exited cleanly after running the env command. That is expected, you can see the pod with 'kubectl get pod -a' and you need to delete it before re-creating. You can still see its logs with 'kubectl logs secret-env-pod'

I confirm seeing the same behavior with a minimalist setup, totally unable to use secrets as ENV variables. The variable is seen in the environment but is empty.

`kubectl create secret generic test-secret --from-literal=user=produser --from-literal=password=Y4nys7f11`

```
cat test-pod.yaml 

apiVersion: v1
kind: Pod
metadata:
  name: testsecret
spec:
  containers:
    - name: test
      command: ["/bin/sh", "-c", "env"]
      image: busybox
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: username
  restartPolicy: Never
```
`kubectl create -f test-pod.yaml`

```
kubectl  describe pod testsecret

    Environment Variables:
      SECRET_USERNAME:
```

```
ktest logs testsecret | grep USERNAME
SECRET_USERNAME=
```

**Comment by pmorie** [comment]
@sgrimee I realize from looking at your last message that the output of `describe pod` isn't going to contain the right information for env vars populated by secret or configmap keys, so the output you see from that command is the expected one right now.

**Comment by sgrimee** [comment]
@pmorie thanks! Understood, I understand the value may be passed on at runtime to the pod or something like that. That part seems to be broken though as the container does not get the value.

**Comment by marshallpowell** [comment]
I am seeing the same behavior. The environment variable values are blank in the container when trying to use secrets. I can mount the secrets as a volume no problem. This is running on GCE, kubernetes v1.2.0 client, v1.2.1 server

Example config...
                spec:
                  containers:
                  - name: pod-name
                    image: img-name
                    env:
                    - name: DB_USER
                      valueFrom:
                        secretKeyRef:
                          name: mysecrets
                          key: db-user

**Comment by pmorie** [comment]
@sgrimee @marshallpowell I have this one on my list for today.  Sorry for the latency, was on-site in meetings all last week and then travelling / digging out from a mountain of email.

**Comment by pmorie** [comment]
So, I ran the secret env var e2e against a GCE cluster, and it passed, so perhaps there is something else going on.  I guess you folks ping me on slack and we'll do an interactive session; that will probably be faster than trading github postcards.  My slack name is 'pmorie'

**Comment by pmorie** [comment]
I spoke with @marshallpowell on slack; in his case the problem appears to be that the upgrade process he used to update his GCE cluster to 1.2 left a 1.1 kubelet running:

```yaml
apiVersion: v1
kind: Node
metadata:
  creationTimestamp: 2016-04-05T01:25:11Z
  labels:
    kubernetes.io/hostname: gke-dev-cluster-59c8f6dc-node-24jj
  name: gke-dev-cluster-59c8f6dc-node-24jj
  resourceVersion: "728346"
  selfLink: /api/v1/nodes/gke-dev-cluster-59c8f6dc-node-24jj
  uid: 3dd63786-facd-11e5-addb-42010af0002e
spec:
  externalID: "7968049688063421812"
  podCIDR: 10.8.0.0/24
  providerID: gce://app-name/us-east1-b/gke-dev-cluster-59c8f6dc-node-24jj
status:
  addresses:
  - address: 10.240.0.2
    type: InternalIP
  - address: 104.196.101.0
    type: ExternalIP
  allocatable:
    cpu: "2"
    memory: 7679608Ki
    pods: "40"
  capacity:
    cpu: "2"
    memory: 7679608Ki
    pods: "40"
  conditions:
  - lastHeartbeatTime: 2016-04-05T19:26:49Z
    lastTransitionTime: 2016-04-05T01:25:11Z
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"
    type: OutOfDisk
  - lastHeartbeatTime: 2016-04-05T19:26:49Z
    lastTransitionTime: 2016-04-05T01:25:49Z
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images: null
  nodeInfo:
    bootID: a5b6e734-ab85-49fb-b94a-9300908079a7
    containerRuntimeVersion: docker://1.8.3
    kernelVersion: 3.16.0-0.bpo.4-amd64
    kubeProxyVersion: v1.1.3
    kubeletVersion: v1.1.3
    machineID: ""
    osImage: Debian GNU/Linux 7 (wheezy)
    systemUUID: 9D2CDA9B-C924-5015-5B15-5F5C956C38E2
```

**Comment by pmorie** [comment]
@jadhavnitind @sgrimee will you both do the following, please:

1.  Run a pod which exhibits this bug
2.  Post the output of `kubectl get node <node where pod ran> -o yaml`

It looks like there is at least one case where an upgrade in GCE didn't work correctly; let's establish that you're both using the right version of the kubelet.

**Comment by a-robinson** [comment]
@pmorie - can you clarify? Are you saying that secrets will not work properly with a 1.2 master and 1.1 nodes? Because that's [supposed to be a supported configuration](https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md#upgrades).

**Comment by pmorie** [comment]
@a-robinson Secrets in environment variables is a 1.2 feature, so no, I would not expect that to work at all.

**Comment by a-robinson** [comment]
Ack, thanks.

**Comment by erictune** [comment]
Is this on Google Container Engine or on Google Compute Engine?

**Comment by pmorie** [comment]
@marshallpowell could you answer @erictune's question?

**Comment by a-robinson** [comment]
@johndmulhausen @roberthbailey - should we indicate in the release notes if a new API feature will only work if both the master and nodes have been upgraded?

**Comment by marshallpowell** [comment]
@erictune this on Google Container Engine

**Comment by sgrimee** [comment]
@pmorie I confirm, wrong kubelet version!
kubectl --context=bdb-citeis get nodes -ojson | jq '.items[] | .status.nodeInfo.kubeletVersion'
"v1.1.2+1abf20d"
"v1.1.2+1abf20d"
...

many thanks for your help tracking this down.

**Comment by a-robinson** [comment]
@marshallpowell - did you attempt upgrade your cluster's nodes or just its master? The node instructions are here: https://cloud.google.com/container-engine/docs/clusters/upgrade

**Comment by pmorie** [comment]
@sgrimee no problemo, happy to help

**Comment by marshallpowell** [comment]
@a-robinson  I upgraded through the GCE webUI and can't say with 100% certainty exactly which screen it was. It was a notification next to my dev-cluster saying an "upgrade is available".
it took about 8 minutes to process before the cluster came back up. Everything seemingly went fine.

**Comment by marshallpowell** [comment]
I was able to get the secrets working in my env variable by upgrading my cluster to 1.2.1 through the gcloud cli: `gcloud container clusters upgrade <cluster-name>` big thanks to @pmore @a-robinson

**Comment by pmorie** [comment]
awesome, @marshallpowel

**Comment by jadhavnitind** [comment]
@pmorie Firtly I wasn't able to upgrade the cluster 1.1 to 1.2 hence I just deleted old cluster and created new one.

Following are the logs for the reference and the pod is still not running using [Secrets](https://github.com/kubernetes/kubernetes/tree/release-1.2/docs/user-guide/secrets).

root@gce-tools-1:~/secrets# kubectl get pods  -a
NAME             READY     STATUS      RESTARTS   AGE
secret-env-pod   0/1       Completed   0          10m
root@gce-tools-1:~/secrets# 
root@gce-tools-1:~/secrets# kubectl get pods  -a -o wide
NAME             READY     STATUS      RESTARTS   AGE       NODE
secret-env-pod   0/1       Completed   0          11m       gke-demo-cluster-1-b9cf7fcd-node-zlds
root@gce-tools-1:~/secrets# kubectl get node gke-demo-cluster-1-b9cf7fcd-node-zlds -o yaml
```
apiVersion: v1
kind: Node
metadata:
  creationTimestamp: 2016-03-31T07:31:56Z
  labels:
    beta.kubernetes.io/instance-type: n1-standard-1
    cloud.google.com/gke-nodepool: default-pool
    failure-domain.beta.kubernetes.io/region: us-east1
    failure-domain.beta.kubernetes.io/zone: us-east1-b
    kubernetes.io/hostname: gke-demo-cluster-1-b9cf7fcd-node-zlds
  name: gke-demo-cluster-1-b9cf7fcd-node-zlds
  resourceVersion: "155251"
  selfLink: /api/v1/nodes/gke-demo-cluster-1-b9cf7fcd-node-zlds
  uid: a56dc9e2-f712-11e5-9cb2-42010af0005c
spec:
  externalID: "6046894938045640472"
  podCIDR: 10.228.2.0/24
  providerID: gce://PROJECT/us-east1-b/gke-demo-cluster-1-b9cf7fcd-node-zlds
status:
  addresses:
  - address: 10.240.0.2
    type: InternalIP
  - address: 104.196.4.0
    type: ExternalIP
  allocatable:
    cpu: "1"
    memory: 3801024Ki
    pods: "110"
  capacity:
    cpu: "1"
    memory: 3801024Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: 2016-04-06T09:00:39Z
    lastTransitionTime: 2016-03-31T07:31:56Z
    message: kubelet has sufficient disk space available
    reason: KubeletHasSufficientDisk
    status: "False"
    type: OutOfDisk
  - lastHeartbeatTime: 2016-04-06T09:00:39Z
    lastTransitionTime: 2016-03-31T07:32:36Z
    message: 'kubelet is posting ready status. WARNING: CPU hardcapping unsupported'
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - gcr.io/PROJECT/tomcat:v10
    sizeBytes: 979948657
  - names:
    - busybox:latest
    sizeBytes: 1112820
  - names:
    - gcr.io/PROJECT/httpd:v4
    sizeBytes: 376485088
  - names:
    - gcr.io/google_containers/kube-proxy:6a3c7bde4710fbeb04cee371779c437b
    sizeBytes: 165646845
  - names:
    - gcr.io/PROJECT/tomcat:v6
    sizeBytes: 949240315
  - names:
    - gcr.io/google_containers/PROJECT-gcp:1.18
    sizeBytes: 411450900
  - names:
    - redis:latest
    sizeBytes: 177586452
  - names:
    - gcr.io/google_containers/pause:2.0
    sizeBytes: 350164
  - names:
    - kubernetes/mounttest:0.1
    sizeBytes: 1752375
  - names:
    - gcr.io/google_containers/pause:0.8.0
    sizeBytes: 241656
  - names:
    - gcr.io/google_containers/busybox:latest
    sizeBytes: 2433303
  nodeInfo:
    bootID: ea1cc7c8-1fd9-4da5-a9ea-204493c24a83
    containerRuntimeVersion: docker://1.9.1
    kernelVersion: 3.16.0-4-amd64
    kubeProxyVersion: v1.2.0
    kubeletVersion: v1.2.0
    machineID: ""
    osImage: Debian GNU/Linux 7 (wheezy)
    systemUUID: CBBE35E8-B9C7-CA00-1D78-AC5A7F278C00
```

**Comment by pmorie** [comment]
@jadhavnitind Can I see the your pod spec, the output of `kubectl get pod <pod-name> -o yaml`, and the logs of the pod that you ran?

**Comment by jadhavnitind** [comment]
@pmorie Pod Spec output.

```
# kubectl get pods -a
NAME             READY     STATUS      RESTARTS   AGE
secret-env-pod   0/1       Completed   0          15s
# kubectl get pod secret-env-pod -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      test-container'
  creationTimestamp: 2016-04-11T06:47:12Z
  name: secret-env-pod
  namespace: default
  resourceVersion: "281377"
  selfLink: /api/v1/namespaces/default/pods/secret-env-pod
  uid: 38a7f21b-ffb1-11e5-ad76-42010af0005c
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - env
    env:
    - name: MY_SECRET_DATA
      valueFrom:
        secretKeyRef:
          key: data-1
          name: test-secret
    image: gcr.io/google_containers/busybox
    imagePullPolicy: Always
    name: test-container
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-dv4l0
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: gke-demo-cluster-1-b9cf7fcd-node-zlds
  restartPolicy: Never
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-dv4l0
    secret:
      secretName: default-token-dv4l0
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2016-04-11T06:47:12Z
    reason: PodCompleted
    status: "False"
    type: Ready
  containerStatuses:
  - containerID: docker://2e39d3ac079d0b1dbedc86e8b2faa57d6dfb541bab985609d78576159592a21d
    image: gcr.io/google_containers/busybox
    imageID: docker://8d83bde9424777eb0ba69fc61fb7283fd0a51f6f9202dd558c9fbe44359a3bc6
    lastState: {}
    name: test-container
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://2e39d3ac079d0b1dbedc86e8b2faa57d6dfb541bab985609d78576159592a21d
        exitCode: 0
        finishedAt: 2016-04-11T06:47:13Z
        reason: Completed
        startedAt: 2016-04-11T06:47:13Z
  hostIP: 10.240.0.2
  phase: Succeeded
  podIP: 10.228.2.4
  startTime: 2016-04-11T06:47:12Z
```

Pod Logs
# kubectl logs secret-env-pod
APACHE_FRONTEND_SERVICE_HOST=10.231.242.106
KUBERNETES_PORT=tcp://10.231.240.1:443
KUBERNETES_SERVICE_PORT=443
HOSTNAME=secret-env-pod
SHLVL=1
HOME=/root
APACHE_FRONTEND_PORT=tcp://10.231.242.106:80
APACHE_FRONTEND_SERVICE_PORT=80
APACHE_FRONTEND_PORT_80_TCP_ADDR=10.231.242.106
APACHE_FRONTEND_PORT_80_TCP_PORT=80
APACHE_FRONTEND_PORT_80_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.231.240.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
MY_SECRET_DATA=value-1

APACHE_FRONTEND_PORT_443_TCP_ADDR=10.231.242.106
APACHE_FRONTEND_PORT_80_TCP=tcp://10.231.242.106:80
APACHE_FRONTEND_PORT_443_TCP_PORT=443
APACHE_FRONTEND_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP=tcp://10.231.240.1:443
KUBERNETES_SERVICE_PORT_HTTPS=443
APACHE_FRONTEND_SERVICE_PORT_HTTP=80
PWD=/
KUBERNETES_SERVICE_HOST=10.231.240.1
APACHE_FRONTEND_PORT_443_TCP=tcp://10.231.242.106:443
APACHE_FRONTEND_SERVICE_PORT_HTTPS=443

**Comment by pmorie** [comment]
@jadhavnitind looks like it worked to me:

```
MY_SECRET_DATA=value-1
```

**Comment by jadhavnitind** [comment]
Not sure whats happening with me but its not working here :(

**Comment by pmorie** [comment]
@jadhavnitind it looks like it's working to me from the information you posted, grep for 'MY_SECRET_DATA' in the output you posted.

**Comment by callmeradical** [comment]
I am having this issue, well similarly. 

I attach to the pod and they are there, however my application (a go binary) launches and doesn't see any of the ENVs.

Only happens when the ENV is valueFrom: secretKeyRef

Am I missing something?

**Comment by BertHartm** [comment]
Sorry to resurrect an old thread, but I just hit the same issue, and thanks to the thread here was able to figure it out.

The issue for me was that I had a newline at the end of my secret (you'll notice the newline after `MY_SECRET_DATA=value-1` also). Removing the newline solved that for me.

You can re-encode your secrets using something like `echo 'YOUR_BASE64_SECRET_HERE' | base64 --decode | tr -d '\n' | base64` to get rid of the trailing newline.

**Comment by lfaoro** [comment]
You can use 'echo -n' to not out the '\n' char

`echo -n "SECRET" | base64`

**Comment by alexvicegrab** [comment]
Initial issue is that here:

```
kubectl exec -it testtomcat-hauaf echo $DB_USERNAME
```

The $DB_USERNAME environmental variable expands from your local environment (it's probably not defined). Which is why it shows nothing.

Unfortunately `kubectl exec` does not appear to support quoting the command, which would allow passing raw commands, instead you can use a workaround like this:

```
kubectl exec my-wonderful-pod -- bash -c 'echo $DB_USERNAME'
```

**Comment by shubhambhattar** [comment]
I was having the same issue and I found out that my indentation wasn't proper in yaml file.

What I did to cross-check was I opened my  Kubernetes Dashboard and clicked on `View/Edit YAML` of the concerned deployment.
There in `spec`, I checked my `env` was showing as below:
```
"env": [
    {
        "name": "REDIS_AUTH",
    }
],
```

instead of 
```
"env": [
    {
        "name": "REDIS_AUTH",
        "valueFrom": {
            "secretKeyRef": {
                "name": "redis",
                "key": "REDIS_AUTH"
            }
        }
    }
],
```

Thus, I cross checked my YAML and found out that `env` was defined as
```
env:
- name: REDIS_AUTH
   valueFrom:
   secretKeyRef:
       name: redis
       key: REDIS_AUTH
```
instead of
```
env:
- name: REDIS_AUTH
   valueFrom:
       secretKeyRef:
           name: redis
           key: REDIS_AUTH
```

**Comment by jamesmedice** [comment]
kubectl create secret generic mysqlcontainer --from-literal=username='user' --from-literal=password='pass'
kubectl get secret  mysqlcontainer -o yaml > secret.yaml
kubectl apply  -f secret.yaml


*********************************************
my pod. yaml
apiVersion: v1
kind: Pod
metadata:
  name: secretenv
spec:
  containers:
  - name: secretcontainer
    image: redis
    env:
      - name: SECRETS_USER
        valueFrom:
          secretKeyRef:
            name: mysqlcontainer
            key: username
      - name: SECRETS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysqlcontainer
            key: password
  restartPolicy: Never

run the command : 
kubectl create -f pod.yaml
kubectl apply  -f pod.yaml


once i try to run the app and use the env vars, exception .

here is the repo :  https://github.com/jamesmedice/Spring-Boot-GCP

OBS: i see all the env vars on the pod :  kubectl exec mysqlcontainer -it -- env
