### ISSUE TITLE
Secrets should be consumable from pods e2e flake

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#23638]
See http://pr-test.k8s.io/23097/kubernetes-pull-build-test-e2e-gce/32863/

**Comment by ihmccreery** [comment]
Note that that was on the v1.1 branch.

**Comment by fejta** [comment]
Made a best guess at assigning this flake with no owner for 2 weeks. Look like you may have fixed this @ihmccreery?

**Comment by ihmccreery** [comment]
I think I opened this issue wrong.  http://pr-test.k8s.io/23097/kubernetes-pull-build-test-e2e-gce/32863/ is actually https://github.com/kubernetes/kubernetes/issues/23389.
