### ISSUE TITLE
AWS: Check/document required VPC options (DNS hostnames)

### ISSUE THREAD

**Issue by trodriguez-photobox** [kubernetes/kubernetes#23633]
Hi,

I'm trying to create a Kubernetes cluster on AWS with debian jessie on the region _us-east-1_. After the creation of the EC2 instances is done, the master node is failing to start the kubelet service because the file _/etc/sysconfig/kubelet_ used as environment config file for the kubelet systemd unit doesn't exist. When I look into the salt minion logs I find that:

```
2016-03-30 13:31:50,695 [salt.state       ][INFO    ] Executing state file.managed for /etc/sysconfig/kubelet
2016-03-30 13:31:50,754 [salt.state       ][ERROR   ] Unable to manage file: Jinja variable list object has no element 0; line 12

---
[...]
  {% set api_servers = "--api-servers=https://" + grains.api_servers -%}
{% elif grains.apiservers is defined -%} # TODO(remove after 0.16.0): Deprecated form
  {% set api_servers = "--api-servers=https://" + grains.apiservers -%}
{% elif grains['roles'][0] == 'kubernetes-master' -%}
  {% set master_ipv4 = salt['grains.get']('fqdn_ip4')[0] -%}
  {% set api_servers = "--api-servers=https://" + master_ipv4 -%}    <======================
{% else -%}
  {% set ips = salt['mine.get']('roles:kubernetes-master', 'network.ip_addrs', 'grain').values() -%}
  {% set api_servers = "--api-servers=https://" + ips[0][0] -%}
{% endif -%}

[...]

---
2016-03-30 13:31:50,754 [salt.state       ][INFO    ] Completed state [/etc/sysconfig/kubelet] at time 13:31:50.754164
```

I don't know which Jinja variable is talking about, or when I can get that Jinja template to check for the missing variable, but I suspect, if I understood well, that maybe there is something missing in my _/etc/kubernetes/kube_env.yaml_ file.

**Comment by trodriguez-photobox** [comment]
When I log in into the instance and I display the grains, the value **fqdn_ip4** is missing. Googling around I found that in order to get a public DNS name for an EC2 instance the VPC must have the option [DNS Hostnames](http://stackoverflow.com/questions/20941704/ec2-instance-has-no-public-dns) enabled, which is obviously not the case for the VPC I'm using. I will try with this option enabled and post here the results.

**Comment by trodriguez-photobox** [comment]
Ok, with the DNS hostnames option activated the install works like a charm. Just for the record, I don't have the permissions to create a VPC with my current AWS account, so I had to ask the creation of the VPC and to use the VPC_ID and SUBNET_ID env vars to use the manually created VPC. The problem is that this VPC didn't have this option activated. I think it would be a good idea to update the documentation to warn that the VPC must have this option enabled, it could save a lot of time to the next one that is in a situation similar to mine.

**Comment by justinsb** [comment]
Yeah, kube-up will create the options correctly, but if you use an existing VPC we don't check it.

We're reworking kube-up so hopefully we can do better.  Or at least have better docs!

**Comment by clueware** [comment]
I met the same issue while deploying on VMware - and found a related issue on Salt Github (https://github.com/saltstack/salt/issues/34129). Changing 
`{% set master_ipv4 = salt['grains.get']('fqdn_ip4')[0] -%}`
to 
`{% set master_ipv4 = salt['grains.get']('fqdn')[0] -%}` 
was enough to solve the issue for me.

**Comment by wirtsi** [comment]
@clueware I can confirm that your change also fixes https://github.com/kubernetes/kubernetes/issues/28505
