### ISSUE TITLE
Cluster addon resource usage needs to be tracked and tested

### ISSUE THREAD

**Issue by fabioy** [kubernetes/kubernetes#23641]
We're seeing some failures for customers that upgrade to k8s 1.2 because the various addons now require more cluster node resources to run (i.e. https://github.com/kubernetes/kubernetes/issues/23556). Customers with high cluster utilization or small machine/node configuration may have situations where their v1.1 cluster no longer works properly after an upgrade to 1.2 because of this.

At the least, we need to track the resource utilization/reservation of addons, with a test that also fails if this increases (i.e. a test that schedules an "almost all free resource" pod that fails if kube-system pods resource use increases). Any increase needs to be investigated and justified (it is a "breaking change" of sorts, since it may result in a non-working clusters for some customers). 

Related issues: 
https://github.com/kubernetes/kubernetes/issues/13695
https://github.com/kubernetes/kubernetes/issues/13048

**Comment by quinton-hoole** [comment]
Removing redundant teams.  I think it's better if one team/TL track this.  A good solution would be to write an e2e test against GKE clusters that fails if resource consumption by kube-system pods increases beyond some specified maximum.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
I'm assuming sig-cluster-lifecycle owns addon management

**Comment by razvanm** [comment]
/remove-lifecycle rotten

This seems still relevant from a reliability point of view.
