### ISSUE TITLE
pkg/registry/*/etcd unit tests should not be integration tests

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#23648]
These tests all spin up a local etcd server, talk with it, and then tear it down. It seems likely to me that that integration-like behavior is not actually be necessary, they should instead talk to a fake etcd server. We have lots of integration tests already that talk to a real etcd server.

For an idea of how slow these are: they take up approximately a quarter of our test time. This is about 200 seconds for each api version, so 400 seconds per `kubernetes-test-go` run. We run that suite about 43 times a day, which means we're blowing about 1700 compute hours a year on these tests. `kubernetes-test-go-1.2` is the same story, and PR builder will add a similar figure... they come out to about half a year of compute time every year.

The extra three minutes are also painful for devs.

cc @krousey @liggitt

**Comment by liggitt** [comment]
I'd rather just switch back to non TLS etcd for unit tests (see https://github.com/kubernetes/kubernetes/pull/22919 ) than try to make sure we keep parity with a fake etcd server.

**Comment by spxtr** [comment]
The other option is to just make these integration tests, which already have an etcd server to talk to. That should speed them up a fair amount, since they spend quite a bit of time upping and downing 190 etcd servers.

In principle though, we should have some integration tests that talk to a real etcd server and make sure that interface doesn't change, and then these unit tests should assume the interface works and talk to a fake.

**Comment by liggitt** [comment]
There are interactions between successive calls to etcd storage I don't think we should try to mimic/fake/stub. I would have less confidence in our registry unit tests if we did

**Comment by spxtr** [comment]
Sounds like they should be reworked as integration tests then. They spend a significant amount of their time creating and destroying the etcd server for each test.

**Comment by krousey** [comment]
My main question would be how does `pkg/registry/deployment/etcd.TestCreate` differ in a way from `pkg/registry/job/etcd.TestCreate` that the etcd interactions may matter?

I haven't looked too closely, but to me, it seems there's a set of etcd interactions that we want to test, and a set of API type things we want to test... and we're testing the cross product of those two sets instead of isolating them out.
