### ISSUE TITLE
making container pruning prefix more flexible

### ISSUE THREAD

**Issue by bparees** [kubernetes/kubernetes#23640]
Currently the k8s pruning logic explicitly considers only certain prefixes:

https://github.com/kubernetes/kubernetes/blob/be8ce6c38578c244ac6ebdb1c402f74e5a282140/pkg/kubelet/dockertools/docker.go#L358-L361

this is despite the fact that the pruning logic appears to be intended to handle "unidentified"(non-k8s?) containers:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/container_gc.go#L158-L161

We'd like to be able to define additional prefixes that would be considered by the pruning logic, but we do not want to use the k8s prefix since the containers are not otherwise managed by k8s.

Would it be possible to extend this logic to allow a list of prefixes that should be considered for pruning?

@ncdc @smarterclayton @rhcarvalho

**Comment by smarterclayton** [comment]
These would be containers created by reasonably well behaved pods that have
access to the docker socket where having Kubelet GC them (because Kubelet
ultimately owns the lifecycle of the creating pod) makes sense.

**Comment by jeremyeder** [comment]
Is this the latest status for container pruning or is it being tracked elsewhere?
