### ISSUE TITLE
Decide how kubenet handles promiscuous mode

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#23657]
To work around #20096 we introduced a --hairpin-mode flag that flips cbr0 to promiscuous mode. Users of kubenet run with --configure-cbr0=false, so before we push kubenet to production we need to decide how to handle this. 

If we decided to stick with promiscuous mode, kubenet should set it on whatever bridge it creates. We will (hopefully) not have to continue relying on promiscuous mode on newer kernel versions. Maybe it still makes sense to do in the interim? or maybe we can push it down into the CNI bridge driver (unsure of a valid generic use case to make a bridge promiscuous)?

@yifan-gu @dcbw @kubernetes/sig-network

**Comment by bprashanth** [comment]
Another option for rkt is to flip to `hairpin-mode=hairpin-veth` when using network plugin + rkt, and handle setting the hairpin flag in the container runtime like docker does: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1895 (I don't think rkt ever did this, so I think hairpin didn't work with or without promiscuous mode)

**Comment by yifan-gu** [comment]
> Another option for rkt is to flip to hairpin-mode=hairpin-veth when using network plugin + rkt, and handle setting the hairpin flag in the container runtime like docker does: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1895 (I don't think rkt ever did this, so I think hairpin didn't work with or without promiscuous mode)

Can't really use this interface as we can't operate on container level for rkt today.
Besides, I am still seeing l7 restarts because of it can't reach the dns service located on the same node even we set PROMISC up manually.

**Comment by yifan-gu** [comment]
cc @sjpotter

**Comment by bprashanth** [comment]
> Besides, I am still seeing l7 restarts because of it can't reach the dns service located on the same node even we set PROMISC up manually.

1. You need to be able to do a DNS lookup from the l7 pod, check that with `nslookup kubernetes default-http-backend`, where the default-http-backend is the service supplied to --default-backend-service arg of the RC.
2. The l7 controller is specific to GCE, it will restart if it's not on GCE, or not on a node with compute r/w (ssh into the node and try gcloud compute backend services list)

Please post the debug information from the penultimate reply on: https://groups.google.com/forum/#!msg/google-containers/SPDYR-MqVZo/HwahJITSEAAJ

I don't expect promiscuous mode to fix anything cross-service.

**Comment by sjpotter** [comment]
#1 is the point, if skydns and l7 are on the same node, l7 can't connect to metadata and hence fails (well its healthcheck fails and liveness check kills it)

#2 it works when l7 ends up on a different node than skydns in GCE so our GCE is setup correctly

**Comment by bprashanth** [comment]
Do nslookups work from other pods on the same node?

**Comment by sjpotter** [comment]
yes, we tested this (a while ago) by launching a lot of busybox containers, we could exec nslookup into all of them and it worked on the ones that weren't colocated with skydns

**Comment by bprashanth** [comment]
So your problem is: nslookup fails form any pod on the same node as skydns? (i.e it has nothing to do with the L7 controller)

**Comment by sjpotter** [comment]
yes, 

or in more general, it seems we have issues connecting to pods servicing services if the client pod and the service pod are on the same node

**Comment by bprashanth** [comment]
> or in more general, it seems we have issues connecting to pods servicing services if the client pod and the service pod are on the same node

So it's not even a DNS problem? i.e can you curl the svc ip directly from a busybox to some other Service on the same node

**Comment by sjpotter** [comment]
no, we cant connect to the service ip directly.  if we could dns would works as /etc/resolv.conf just has an ip in it.

**Comment by bprashanth** [comment]
DNS is a more complicated protocol that can break in ways unrelated to IP (most obvious example is something wrong with port 53). This narrows down the problem space by a lot.

So this sounds like a pure L3/4 problem of not being able to hit your own node, are you running an overlay?

**Comment by sjpotter** [comment]
I dont think so.  @yifan-gu ?

**Comment by yifan-gu** [comment]
>  are you running an overlay?
@bprashanth We run with kubenet plugin on gce.

**Comment by bprashanth** [comment]
Ok so normal GCE routes? kubenet won't route between nodes, you need the route controller programming routes (gcloud compute routes list) or something like flannel (various other solutions too). I'll assume you're using routes. What's iptables-save?

**Comment by yifan-gu** [comment]
@sjpotter I had a guess that is because we set the promics later after dns is up. so l7 can't connect it. maybe kill and restart the dns pod would solve the problem, let me try.

**Comment by bprashanth** [comment]
I though we were beyond anything to do with L7 or DNS and concluded that this was a pure L3/L4 probelm?

**Comment by yifan-gu** [comment]
@bprashanth Yes. it's not l7 or dns specific. So translate what I said in https://github.com/kubernetes/kubernetes/issues/23657#issuecomment-204603558:

I guess it's because we set the promics later after the targeting pod is up, so it doesn't work in that case.

**Comment by sjpotter** [comment]
@yifan-gu don't we promisc is kubelet startup so how could anything predate it?

**Comment by yifan-gu** [comment]
@sjpotter No, there is a time window. We can only achieve this reliably by the bridge plugin binary itself, since it's the one who sets the bridge.

**Comment by yifan-gu** [comment]
Inside the container:

Ping the assigned IP of the pod, works
```
 / # ping 10.244.0.13
PING 10.244.0.13 (10.244.0.13): 56 data bytes
64 bytes from 10.244.0.13: seq=0 ttl=64 time=0.080 ms
```

Ping the service IP, doesn't work, traceroute
```
/ # traceroute  10.0.0.10
traceroute to 10.0.0.10 (10.0.0.10), 30 hops max, 46 byte packets
 1  10.244.0.1 (10.244.0.1)  0.007 ms  0.007 ms  0.002 ms
 2  *  *  *
 3  *  *  *
 4  *  *  *
 5  *  *

```

iptables-save:
```
 $ sudo iptables-save
# Generated by iptables-save v1.4.21 on Fri Apr  1 23:55:14 2016
*filter
:INPUT ACCEPT [17:1092]
:FORWARD ACCEPT [67:14149]
:OUTPUT ACCEPT [13:1312]
:KUBE-SERVICES - [0:0]
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A KUBE-SERVICES -d 10.0.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp has no endpoints" -m tcp --dport 53 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.112.40/32 -p tcp -m comment --comment "kube-system/default-http-backend:http has no endpoints" -m tcp --dport 80 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.115.58/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: has no endpoints" -m tcp --dport 80 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns has no endpoints" -m udp --dport 53 -j REJECT --reject-with icmp-port-unreachable
COMMIT
# Completed on Fri Apr  1 23:55:14 2016
# Generated by iptables-save v1.4.21 on Fri Apr  1 23:55:14 2016
*nat
:PREROUTING ACCEPT [25:2014]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:CNI-kubenet - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-UDU5ETJFU43KPV77 - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:KUBE-SVC-XGLOHA7QRQ3V22RZ - [0:0]
:KUBE-SVC-XP4WJ6VSLGWALMW5 - [0:0]
:RKT-PFWD-DNAT-624c8f27 - [0:0]
:RKT-PFWD-DNAT-7acbea7b - [0:0]
:RKT-PFWD-DNAT-af88aa9a - [0:0]
:RKT-PFWD-DNAT-b0c7756d - [0:0]
:RKT-PFWD-DNAT-b4d30bec - [0:0]
:RKT-PFWD-SNAT-624c8f27 - [0:0]
:RKT-PFWD-SNAT-7acbea7b - [0:0]
:RKT-PFWD-SNAT-af88aa9a - [0:0]
:RKT-PFWD-SNAT-b0c7756d - [0:0]
:RKT-PFWD-SNAT-b4d30bec - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j RKT-PFWD-DNAT-b0c7756d
-A PREROUTING -m addrtype --dst-type LOCAL -j RKT-PFWD-DNAT-af88aa9a
-A PREROUTING -m addrtype --dst-type LOCAL -j RKT-PFWD-DNAT-624c8f27
-A PREROUTING -m addrtype --dst-type LOCAL -j RKT-PFWD-DNAT-7acbea7b
-A PREROUTING -m addrtype --dst-type LOCAL -j RKT-PFWD-DNAT-b4d30bec
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -m addrtype --dst-type LOCAL -j RKT-PFWD-DNAT-b0c7756d
-A OUTPUT -m addrtype --dst-type LOCAL -j RKT-PFWD-DNAT-af88aa9a
-A OUTPUT -m addrtype --dst-type LOCAL -j RKT-PFWD-DNAT-624c8f27
-A OUTPUT -m addrtype --dst-type LOCAL -j RKT-PFWD-DNAT-7acbea7b
-A OUTPUT -m addrtype --dst-type LOCAL -j RKT-PFWD-DNAT-b4d30bec
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A POSTROUTING -s 127.0.0.1/32 ! -d 127.0.0.1/32 -j RKT-PFWD-SNAT-b0c7756d
-A POSTROUTING -s 127.0.0.1/32 ! -d 127.0.0.1/32 -j RKT-PFWD-SNAT-af88aa9a
-A POSTROUTING -s 127.0.0.1/32 ! -d 127.0.0.1/32 -j RKT-PFWD-SNAT-624c8f27
-A POSTROUTING -s 127.0.0.1/32 ! -d 127.0.0.1/32 -j RKT-PFWD-SNAT-7acbea7b
-A POSTROUTING -s 127.0.0.1/32 ! -d 127.0.0.1/32 -j RKT-PFWD-SNAT-b4d30bec
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 10.244.0.0/24 -j CNI-kubenet
-A CNI-kubenet -d 10.244.0.0/24 -j ACCEPT
-A CNI-kubenet ! -d 224.0.0.0/4 -j MASQUERADE
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-NODEPORTS -p tcp -m comment --comment "kube-system/default-http-backend:http" -m tcp --dport 31486 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "kube-system/default-http-backend:http" -m tcp --dport 31486 -j KUBE-SVC-XP4WJ6VSLGWALMW5
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-SEP-UDU5ETJFU43KPV77 -s 10.240.0.2/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-UDU5ETJFU43KPV77 -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-UDU5ETJFU43KPV77 --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 10.240.0.2:443
-A KUBE-SERVICES -d 10.0.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES -d 10.0.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES -d 10.0.112.40/32 -p tcp -m comment --comment "kube-system/default-http-backend:http cluster IP" -m tcp --dport 80 -j KUBE-SVC-XP4WJ6VSLGWALMW5
-A KUBE-SERVICES -d 10.0.115.58/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-SVC-XGLOHA7QRQ3V22RZ
-A KUBE-SERVICES -d 10.0.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 180 --reap --name KUBE-SEP-UDU5ETJFU43KPV77 --mask 255.255.255.255 --rsource -j KUBE-SEP-UDU5ETJFU43KPV77
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-UDU5ETJFU43KPV77
-A RKT-PFWD-DNAT-624c8f27 -p tcp -m tcp --dport 0 -j DNAT --to-destination 172.16.28.3:8080
-A RKT-PFWD-DNAT-7acbea7b -p udp -m udp --dport 0 -j DNAT --to-destination 172.16.28.13:53
-A RKT-PFWD-DNAT-7acbea7b -p tcp -m tcp --dport 0 -j DNAT --to-destination 172.16.28.13:53
-A RKT-PFWD-DNAT-7acbea7b -p tcp -m tcp --dport 0 -j DNAT --to-destination 172.16.28.13:8080
-A RKT-PFWD-DNAT-af88aa9a -p tcp -m tcp --dport 0 -j DNAT --to-destination 172.16.28.4:8080
-A RKT-PFWD-DNAT-b0c7756d -p tcp -m tcp --dport 0 -j DNAT --to-destination 172.16.28.5:8080
-A RKT-PFWD-DNAT-b4d30bec -p tcp -m tcp --dport 0 -j DNAT --to-destination 172.16.28.2:9090
-A RKT-PFWD-SNAT-624c8f27 -s 127.0.0.1/32 -d 172.16.28.3/32 -p tcp -m tcp --dport 0 -j MASQUERADE
-A RKT-PFWD-SNAT-7acbea7b -s 127.0.0.1/32 -d 172.16.28.13/32 -p udp -m udp --dport 0 -j MASQUERADE
-A RKT-PFWD-SNAT-7acbea7b -s 127.0.0.1/32 -d 172.16.28.13/32 -p tcp -m tcp --dport 0 -j MASQUERADE
-A RKT-PFWD-SNAT-af88aa9a -s 127.0.0.1/32 -d 172.16.28.4/32 -p tcp -m tcp --dport 0 -j MASQUERADE
-A RKT-PFWD-SNAT-b0c7756d -s 127.0.0.1/32 -d 172.16.28.5/32 -p tcp -m tcp --dport 0 -j MASQUERADE
-A RKT-PFWD-SNAT-b4d30bec -s 127.0.0.1/32 -d 172.16.28.2/32 -p tcp -m tcp --dport 0 -j MASQUERADE
COMMIT
# Completed on Fri Apr  1 23:55:14 2016
```

**Comment by bprashanth** [comment]
Ping never works on service ips, anyway, we don't install icmp rules :) (if you actually want to ping the endpoints it's a lot more rules, and a rule for the service ip doesn't prove you can ping the eps) 

It looks like your kube-dns is just hosed:
```
-A KUBE-SERVICES -d 10.0.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns has no endpoints" -m udp --dport 53 -j REJECT --reject-with icmp-port-unreachable
```

Lets get rid of that first? You'll lose the REJECT rule when kubectl get ep shows some healthy endpoints. If there are none, please run logs on kube2sky container in dns and poke around (describe etc) to see what's happening. 

Also I suggest taking DNS out of the loop alltogether and starting a simple nginx pod behind a service to test. DNS has a lot of failure modes. You can do so with something like:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: my-node-name
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx
        ports:
        - containerPort: 80

```

**Comment by sjpotter** [comment]
so, I wasn't able to duplicate this with or without promisc mode so you're probably right that it doesn't relate and promisc mode is only needed for the kubeproxy test and our dns issues are possibly something else.

**Comment by yifan-gu** [comment]
@bprashanth @sjpotter So I did another experiment, I spin up two clusters, one with kubenet + configureCBR0=true, one with kubenet + configureCBR0=false
In the first cluster(configureCBR0=true), service IP is reachable.
In the second cluster(configureCBR0=false), service IP is not reachable.

I compared the iptables-save result, and find there is one rule doesn't appear in the second cluster's node:
`-A POSTROUTING ! -d 10.0.0.0/8 -m addrtype ! --dst-type LOCAL -j MASQUERADE`

I suspect this is the reason. 

The full iptables-save result can be found [here](https://gist.github.com/yifan-gu/63894c604934238d180e418aced58dfd)

**Comment by bprashanth** [comment]
Then kubenet isn't including the masquerade rule: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container_bridge.go#L145, that's essentially natting traffic not destined for the 10-dot space. Given that it's a known range piped through a flag to the kubelet I'm not sure it needs to be hidden behind configure-cbr0. 

Can you add it yourself and confirm there isn't something else blocking traffic? (iptables -t nat "that command")

**Comment by yifan-gu** [comment]
@bprashanth I tried that, then the service IP is reachable from the host, but still not reachable inside a pod.

**Comment by freehan** [comment]
hmm interesting... That should not matter tough...
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L286

**Comment by yifan-gu** [comment]
@freehan I manually commented out this piece to force configureCBR0=true in the first cluster for testing.

**Comment by dcbw** [comment]
> Then kubenet isn't including the masquerade rule: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container_bridge.go#L145, that's essentially natting traffic not destined for the 10-dot space. Given that it's a known range piped through a flag to the kubelet I'm not sure it needs to be hidden behind configure-cbr0.

kubenet sends "IpMasq": true to CNI's bridge plugin, but it appears that's not quite equivalent to what Kubernetes is doing, as it'll just set up NAT for the pod's IP instead of a whole 10.0.0.0/8 range.

**Comment by bprashanth** [comment]
I believe this can be close in favor of https://github.com/kubernetes/kubernetes/issues/24018 once https://github.com/kubernetes/kubernetes/pull/23711 goes in
