### ISSUE TITLE
gcloud complains about node not found

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#23659]
Was tempted to dupe this into the gcloud meteadata server issue, but I think this is some other race:
```
Bringing down cluster
+ rc=124
+ [[ 124 -ne 0 ]]
+ [[ -x cluster/log-dump.sh ]]
+ [[ -d _artifacts ]]
+ echo 'Dumping logs for any remaining nodes'
Dumping logs for any remaining nodes
+ ./cluster/log-dump.sh _artifacts
Dumping master and node logs to _artifacts
Warning: Permanently added '23.251.147.86' (ECDSA) to the list of known hosts.
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-3pon' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-78tp' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-s93o' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-7qxp' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-9lwz' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-sikw' was not found
```
gcloud.compute.copy-files failed, but we do have logs from those nodes, so not sure what happened. 

https://github.com/kubernetes/kubernetes/pull/23646#issuecomment-203688517
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23646/kubernetes-pull-build-test-e2e-gce/33989/artifacts/e2e-gce-builder-2-0-minion-sikw/

**Comment by sunzen** [comment]
unsubscribe

On Thu, Mar 31, 2016 at 8:00 AM, Prashanth B <notifications@github.com>
wrote:

> Was tempted to dupe this into the gcloud meteadata server issue, but I
> think this is some other race:
>
> Bringing down cluster
> + rc=124
> + [[ 124 -ne 0 ]]
> + [[ -x cluster/log-dump.sh ]]
> + [[ -d _artifacts ]]
> + echo 'Dumping logs for any remaining nodes'
> Dumping logs for any remaining nodes
> + ./cluster/log-dump.sh _artifacts
> Dumping master and node logs to _artifacts
> Warning: Permanently added '23.251.147.86' (ECDSA) to the list of known hosts.
> ERROR: (gcloud.compute.copy-files) Could not fetch instance:
>  - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-3pon' was not found
> ERROR: (gcloud.compute.copy-files) Could not fetch instance:
>  - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-78tp' was not found
> ERROR: (gcloud.compute.copy-files) Could not fetch instance:
>  - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-s93o' was not found
> ERROR: (gcloud.compute.copy-files) Could not fetch instance:
>  - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-7qxp' was not found
> ERROR: (gcloud.compute.copy-files) Could not fetch instance:
>  - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-9lwz' was not found
> ERROR: (gcloud.compute.copy-files) Could not fetch instance:
>  - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/instances/e2e-gce-builder-2-0-minion-sikw' was not found
>
> gcloud.compute.copy-files failed, but I do have logs, so not sure what
> happened.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/23659>
>



-- 
sunzen
<<freedom & enjoyment>>

**Comment by a-robinson** [comment]
Potentially related to https://github.com/kubernetes/kubernetes/issues/23544#issuecomment-203691992
