### ISSUE TITLE
Run l7 controller as a static pod on the master

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#23663]
This is advantageous for many reasons, but most notably because the master has compute/rw. An nginx controller would still run as an RC in the cluster.

The biggest blocker for this is the acquisition of UIDs. The problem is one can create multiple GKE clusters within a GCE project, and simply computing a cluster local random UID is insufficient, because if 2 controllers end up using the same "UID" there would be a lot of confusion (i.e *not* blackhole, but something like X% requests that get loadbalanced to the wrong backend are lost). 

Currently the solution is just to throw an error if we detect nodes in our loadbalanced instance group that don't match the Kubernetes nodes (assuming another Kubernetes cluster put them there), and document how users can manually assign a unique ID to the controller (https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/BETA_LIMITATIONS.md#running-multiple-loadbalanced-clusters-in-the-same-gce-project).

This work-around will not be possible once we run it on the master.

I have a pr locally that orchestrates real UIDs in a project by using the IG name as a lock, and writing the acquired UID to a config map. It's tricky and needs testing is all: https://github.com/kubernetes/contrib/pull/680

@kubernetes/goog-gke

**Comment by thockin** [comment]
Generating UUIDs should be unique enough, no?  I mean, if that's not true,
we're dead in so many ways.

**Comment by alex-mohr** [comment]
Instead of each component trying to build its own uuid allocator, perhaps we can have that provided as part of cluster setup?  In particular, ubernetes @quinton-hoole will presumably need some unique way of identifying clusters.  On GKE, each cluster has a globally unique name in the form $location/$clustername.

I'd propose each cluster-component use $unique-cluster-name as a prefix for the objects they create in GCE and/or externally.  That'd eliminate the need for  kubernetes/contrib#680 style logic.

**Comment by bprashanth** [comment]
> Generating UUIDs should be unique enough, no?  I mean, if that's not true,
we're dead in so many ways.

Feel uncomfortable not allowing a work around with a know flaw that could cause a really bad bug, but yeah in general.

> I'd propose each cluster-component use $unique-cluster-name as a prefix for the objects they create in GCE and/or externally. That'd eliminate the need for kubernetes/contrib#680 style logic.

There are 2 problems with this:    

1. Name length limit. Since we generally encode more information in the resource name (eg: our node names are gke-$(instance-template-tag)-node-$(uid)) the amount of space we get for $(uid) is really small. Url maps have a limit of 60 chars, I should probably file an internal bug for this.
2. The cluster addons are not templatized (https://github.com/kubernetes/kubernetes/issues/23620). This makes piping anything from the `gcloud container cluster create` or `kube-up` level hard. We can fix this with more salt.

Till now in Kubernetes we've used ns/name as a unique identifier in many cases. My first instinct was to use ns/name/cluster-id but it is not guaranteed to fit. 

The servicecontroller uses service.UID, which *may* be sufficient if it fit into url-maps, but a big difference between L4 and L7 loadbalancing is that in L7 we *must* share resources (it is forbidden to use 2 IGs for the same set of loadbalanced instances, we also need to share backends and firewall rules) so tagging with any 1 object UID doesn't make sense.

We could generate an arbitrary UID that has no link to the Ingresses using it, but then we need to engineer consistency somehow by writing to local etcd, or scribbling to config maps etc. 

Given all these issues it felt easiest to handle this completely in the L7 controller, though I agree we need a solution that applies for all Cloudprovider controllers.

**Comment by quinton-hoole** [comment]
@bprashanth I'm with @thockin .  UUID's are unique enough.  2^128 is an awfully large number.

**Comment by bprashanth** [comment]
I explained why UIDs won't really work in previous comment :)
There's a name length limit, amongst other things.
Also how are you sure every cluster won't get the same UID everytime (same seed etc)? Note that we're talking about *cross cluster* uid. It is more of a danger when resources are shared, because an IG with 50% vms from 1 cluster and 50% from another, will black hole half traffic. 

IMO a problem solved badly is not worth solving at all, but I agree if there was a sureshot way to acquire a MOSTLY unique ID that's ~30chars in length, that would work.

**Comment by bprashanth** [comment]
Clarified in person, will look up the UUID approach. It should fit. Was confused about how the UIDs are generated.

**Comment by bprashanth** [comment]
With https://github.com/kubernetes/kubernetes/pull/24391 and https://github.com/kubernetes/contrib/pull/791 it should be trivial to run the controller as a static pod on the master instead of an addon. 

Before we do so we need some way to turn it off after users have updated their clusters. I know people who want advanced nginx features are currently running the nginx controller on gce by sizing the rc down to 0 and this will become impossible once it's a static pod (right?).

**Comment by roberthbailey** [comment]
For GCE, you should be able to set [ENABLE_L7_LOADBALANCING](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L66) to empty string to disable the L7 addon during cluster creation. For GKE, we have an API option to turn it on/off for a cluster at creation time or afterwords. We should be able to provide some pretty straightforward documentation for how to disable it on GCE (remove the pod configuration on the master) for users that upgrade.

**Comment by bprashanth** [comment]
No I mean if someone is running today, with the l7 controller --replicas=0 and the nginx controller, they will no longer be able to turn it off once they upgrade. I don't think the cluster startup time config is sufficient. 

If we can't toggle it on/off on a running cluster I can teach it to ignore ingresses with a certain annotation, and ask everyone to apply the annotation ingress=nginx or something to current ingresses.

**Comment by roberthbailey** [comment]
We don't currently have an API in k8s core to toggle static pods on/off after cluster creation (e.g. fluentd on the nodes or any of the master components on the master). I don't think we should gate moving this functionality onto the master on designing and adding such a capability, when you can do it via an ssh command.

**Comment by bprashanth** [comment]
On GKE I want to move manifest files out of /etc/kubernetes/manifests, that's the equivalent of scaling an RC down to 0. 

I think it's ok to do the annotation thing I mentioned and say it's a fallout of the feature still being in beta, wdyt?

**Comment by bprashanth** [comment]
>We don't currently have an API in k8s core to toggle static pods on/off after cluster creation (e.g. fluentd on the nodes or any of the master components on the master).

I think the difference here is that we're moving something that *was* toggle-able to something static, and I know some advanced users have toggled it off.

**Comment by roberthbailey** [comment]
> I think the difference here is that we're moving something that was toggle-able to something static

We don't have an API in k8s core to toggle L7 on/off, but we **do** have such an API for GKE. So advanced users will still be able to turn it off in GKE clusters (at cluster creation or after the fact). Users that have turned it off should not get it enabled when their cluster gets upgraded (because we should suppress the static pod from running on the master if you've requested no L7 addon).

**Comment by bprashanth** [comment]
Ah, thanks for the clarification. As long as people can toggle it off on GKE we should be fine with the ssh workaround everywhere else.

**Comment by alex-mohr** [comment]
Is L7 enabled but RC scaled to 0 pods a valid (== works today) GKE config?  If so, we need an upgrade strategy that keeps that working.

Also, does L7 enabled set to false perform admission control and/or disable ability to create Ingress objects?  If so, need some way of keeping Ingress objects but subbing their own controller.

**Comment by roberthbailey** [comment]
> Is L7 enabled but RC scaled to 0 pods a valid (== works today) GKE config?

No. But an end user could scale their RC to 0 instead of using the GKE API to disable L7. 

> Also, does L7 enabled set to false perform admission control and/or disable ability to create Ingress objects?

No. It just turns off the gclb ingress controller.

**Comment by roberthbailey** [comment]
@bprashanth - Any updates on this issue?

**Comment by bprashanth** [comment]
@roberthbailey the upgrade path is a little tricky. 
If the new controller comes up with a uid, and the old controller create l7s without a uid, we can't resolve the conflict. I'm currently planning to have the new controller detect when this happens (old controller has running l7s without a uid) and halt it with a log message. 

Preserving static ip will require manual arbitration. Till such intervention, the user won't be able to create new Ingresses if they had previously running Ingresses. In all other cases it should just work. 

The more complicated solution involves an intermediate push of the controller image. This inbetween image will remember the existing cluster-uid in a config map (even if it's empty string). Then even if I write out the rc spec with a different uid and restart the controller it will respect the stored uid in the config map, for the lifetime of that cluster.

I have an implementation locally of the second option, but I'm prioritizing other features right now (petset). What do you think about the first?

**Comment by Q-Lee** [comment]
In late, but have a question about the UUIDs. 30 chars of base64 gives 180 bits of encoding. Unless we're expecting at least 2^90 objects, I doubt we'll have a collision on randomly generated UUIDs.

You'll end up finding that MAC addresses aren't actually unique, especially if they're virtualized, and timestamps aren't a great source of entropy.

**Comment by bprashanth** [comment]
The uid changes are already finished

**Comment by Q-Lee** [comment]
1. As long as no one ever depends on the semantic values of the time and MAC fields, then we really ought to be able to change this at any time.
2. I haven't seen the code, but I do imagine it would take a pretty small code change to switch to UUID version 4: https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29

**Comment by bprashanth** [comment]
Lets move past the uids to the upgrade scenario :)
Swapping uids is easy enough, and I think we have enough entropy for now (I'm using https://docs.python.org/2/library/uuid.html).

**Comment by bprashanth** [comment]
And as noted in other places, GKE already uses a time based stamp, and if there're collisions we'll just fail to create resources and presumably no one is going to race multiple concurrent kube-ups

**Comment by simonswine** [comment]
It took me a while to find the command for GKE so I will just post it here:

```
gcloud container clusters update <cluster-name> --update-addons HttpLoadBalancing=DISABLED
```
https://cloud.google.com/container-engine/docs/clusters/operations#updating_a_container_cluster

**Comment by bprashanth** [comment]
@simonswine you can also simply "disable" it by specifying an annotation like: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/BETA_LIMITATIONS.md#disabling-glbc

**Comment by simonswine** [comment]
@bprashanth I have tried that before, but it did not work for me (setting ingress class annotation to nginx). Even after deleting the object in GCE it was constantly recreated by the lbc controller. Maybe GKE is using an slightly older version...

**Comment by bprashanth** [comment]
That'll only work in a 1.3+ cluster, which by this time should be rolled out throughout gke. On 1.3 we're running the gce ingress controller on the master, fyi. I just tried it with:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echomap
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: echoheadersx
          servicePort: 80
  - host: bar.baz.com
    http:
      paths:
      - path: /bar
        backend:
          serviceName: echoheadersy
          servicePort: 80
      - path: /foo
        backend:
          serviceName: echoheadersx
          servicePort: 80
```
Please let me know if that doesn't work for you, and also include kubectl version.

**Comment by simonswine** [comment]
@bprashanth 
Yes before I upgraded yesterday we had a 1.2 GKE cluster (I disabled L7 lbc with scaling the RC down). Then after the upgrade on the master, the forwarding rules were created in GCE. Then  I applied with a v1.3.0 kubectl:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lgtm
  namespace: lgtm
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - lgtm.xxx.net
    secretName: lgtm-tls
  rules:
  - host: lgtm.xxx.net
    http:
      paths:
      - path: /
        backend:
          serviceName: lgtm
          servicePort: 80
```

But the forwarding rules were not deleted afterwards, even a manual deletion did not help.

**Comment by bprashanth** [comment]
I'm willing to believe that it didn't do anything. The controller will completely ignore the ingress, not treat it as a deletion. I can be convinced eitherway, because I didn't want the controller to inadvertently tear down a production setup with the annotation change. Please file a bug if you'd like me to consider the teardown use case.

**Comment by bprashanth** [comment]
One would want to leave the old vip up and running for, eg: the long tail of dns disobeyors

**Comment by simonswine** [comment]
@bprashanth seems like your last message is not related

I will make a new issue for that teardown. I just verified when I create a new ingress with the annotation, it gets ignored as expected... Thanks for your help!

**Comment by bprashanth** [comment]
no it was, I meant: 
* you have a working gce l7 with vip 1.2.3.4
* you plug that in dns for foobar.com
* clients have resolved foobar.com to 1.2.3.4
* now you change the ingress to ingress.class=nginx
* the gce controller ignores the ingress, the nginx controller allocates a new vip, say 2.3.4.5
you plug 2.3.4.5 into foobar.com DNS

If the controller were to immediately teardow 1.2.3.4 all clients that disobeyed dns ttl and cached the old vip would immediately start failing. You might want to switch over immediately to using nginx, but keep the old vip around for a couple of hours/days to satisfy dns disobeyors.

**Comment by simonswine** [comment]
@bprashanth : Now I see the connection. I thought of VIPs in the service range.

I get your point, I think you're right: There is no need for tearing down load balancers, in fact it's a bad idea.
Thanks
