### ISSUE TITLE
kubectl describe pod does not correctly handle env vars populated by secret or configmap keys

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#23679]
I found while looking at #23621 that `kubectl describe pod` does not correctly handle env vars populated by secret or configmap keys:

```
kubectl  describe pod testsecret

    Environment Variables:
      SECRET_USERNAME:
```

I think the right output here would be something like:

```
kubectl  describe pod testsecret
<snip>
    Environment Variables:
      SECRET_USERNAME: <populated by key 'username' of secret 'credentials'>
      SOME_CONFIG_VAR: <populated by key 'some-property' of configmap 'my-config'>
```

**Comment by pmorie** [comment]
@kubernetes/kubectl @kubernetes/rh-ux

**Comment by ncdc** [comment]
Suggested output LGTM

**Comment by pmorie** [comment]
One alternative to what I proposed would be to try to resolve the value of the referenced key, which I think would be a poor idea because it might give the impression that the values are static, when they are not.

**Comment by derekwaynecarr** [comment]
+1

**Comment by smarterclayton** [comment]
@jwforres

**Comment by jwforres** [comment]
some very relevant discussion from where we just did this in the web console https://github.com/openshift/origin/pull/7931

**Comment by jwforres** [comment]
particularly helpful would be the final screenshot https://cloud.githubusercontent.com/assets/1668218/13784443/92ed6a96-eacf-11e5-897f-5a141f2e4c16.png

**Comment by pmorie** [comment]
@jwforres that seems like a vote in favor of what i proposed, using the same text as is used in the console?

**Comment by jwforres** [comment]
Yep, and I think leave your < > chars, they help in the CLI to add the visual differentiation that we get with font style in the console
