### ISSUE TITLE
kubemark-5 e2e test broken for 5 hours

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#23670]
Seemingly all because after creating its resources, it checks whether resources of a different name exist:

```
22:09:50  - The resource 'projects/k8s-jenkins-kubemark/zones/us-central1-f/instances/kubemark-5-kubemark-master' was not found
22:09:51 ERROR: (gcloud.compute.disks.delete) Some requests did not succeed:
22:09:51  - The resource 'projects/k8s-jenkins-kubemark/zones/us-central1-f/disks/kubemark-5-kubemark-master-pd' was not found
22:09:51 ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
22:09:51  - The resource 'projects/k8s-jenkins-kubemark/global/firewalls/kubemark-5-kubemark-master-https' was not found
```

The resources that were created are named `kubemark-5-master.*`, not `kubemark-5-kubemark-master.*`. This broke between 4:32pm and 4:56pm today although no changes were checked in around then.

I thought Jenkins configs were under version control -- what went wrong here?
@kubernetes/sig-testing @kubernetes/sig-scalability

**Comment by a-robinson** [comment]
Link to one such failure: https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/659/

**Comment by a-robinson** [comment]
Looks like it might have correlated with @jlowdermilk putting a CI build of gcloud onto the jenkins master?
https://github.com/kubernetes/kubernetes/issues/23544#issuecomment-203691992

**Comment by a-robinson** [comment]
I've switched the jenkins master back to the released version of gcloud, hopefully in a way that won't break things even further.

**Comment by a-robinson** [comment]
Switching the gcloud version doesn't appear to have had an effect on this. The submit queue will just have to stay blocked overnight, since that seems preferable to me trying to remove that test from the submit queue's list of blockers at 11:50pm.

cc @gmarek to look at this tomorrow

**Comment by ixdy** [comment]
`kubemark-5-kubemark-master` is a red herring - the last green build shows that, too.

**Comment by ixdy** [comment]
The last green build and first failing build both used the same version of Kubernetes, so you're right that it doesn't appear to be a code change.

**Comment by ixdy** [comment]
Ah, here's the issue:
```
+ ./test/kubemark/start-kubemark.sh
Please install kubectl before running this script
```

**Comment by ixdy** [comment]
`kubectl` should be installed on the Jenkins master VM now.

kubemark should really not require it to be in the `PATH`. It should detect if it's in the output tree like the rest of our test scripts do.

**Comment by wojtek-t** [comment]
>
kubemark should really not require it to be in the PATH. It should detect if it's in the output tree like the rest of our test scripts do.

@gmarek - can you please take a look ^^

**Comment by a-robinson** [comment]
Thanks for fixing this up last night, @ixdy!
