### ISSUE TITLE
Kubernetes 1.1.8 cluster setup with Flannel 0.5.5: cannot ping pod-ips from different nodes

### ISSUE THREAD

**Issue by junelee05** [kubernetes/kubernetes#23683]
We currently have setup Kubernetes 1.1.8 cluster with two VMs, using Flannel 0.5.5 with vxlan backend:
    vm-1 (public-ip: 10.85.81.165):  master + worker-node
    vm-1 (public-ip: 10.85.81.165): worker-node

The VMs have ubuntu trusty installed.
# uname -a

Linux ngsn02 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

We followed this Kubernetes ubuntu setup guide:
http://kubernetes.io/docs/getting-started-guides/ubuntu/

The Flannel config at the etcd is:
# etcdctl get /coreos.com/network/config

{"Network":"20.1.0.0/16", "SubnetLen": 24, "Backend": {"Type": "vxlan", "VNI": 1}}
# etcdctl ls /coreos.com/network/subnets

/coreos.com/network/subnets/20.1.36.0-24
/coreos.com/network/subnets/20.1.1.0-24
# etcdctl get /coreos.com/network/subnets/20.1.36.0-24

{"PublicIP":"10.85.81.165","BackendType":"vxlan","BackendData":{"VtepMAC":"de:71:6e:55:36:75"}}
# etcdctl get /coreos.com/network/subnets/20.1.1.0-24

{"PublicIP":"10.85.81.166","BackendType":"vxlan","BackendData":{"VtepMAC":"06:c8:be:55:f2:e6"}}

From master node vm-1:
# ip route

default via 10.85.81.129 dev eth0
10.85.81.128/25 dev eth0  proto kernel  scope link  src 10.85.81.165
20.1.0.0/16 dev flannel.1  proto kernel  scope link  src 20.1.36.0
20.1.36.0/24 dev docker0  proto kernel  scope link  src 20.1.36.1

From node vm-2:
~# ip route
default via 10.85.81.129 dev eth0
10.85.81.128/25 dev eth0  proto kernel  scope link  src 10.85.81.166
20.1.0.0/16 dev flannel.1  proto kernel  scope link  src 20.1.1.0
20.1.1.0/24 dev docker0  proto kernel  scope link  src 20.1.1.1

After the setup, we deployed two pods:
The pod-ip at node vm-1:  20.1.36.2:80
The pod-ip at node vm-2:  20.1.1.2:80

The problem is that we cannot ping the pod-id from the different node, while can ping the pod-id from the same node.

vm-1~# ping 20.1.1.2
PING 20.1.1.2 (20.1.1.2) 56(84) bytes of data.
^C
--- 20.1.1.2 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

By reviewing the flannel.log, we found the "L3 miss" and "AddL3 succeeded" logs, but not any "L2 miss" and "AddL2" logs. 
## flannel.log from vm-1:

I0331 09:56:02.102326 01852 main.go:275] Installing signal handlers
I0331 09:56:02.106208 01852 main.go:188] Using 10.85.81.165 as external interface
I0331 09:56:02.106289 01852 main.go:189] Using 10.85.81.165 as external endpoint
E0331 09:56:02.278504 01852 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [1]
E0331 09:56:03.279482 01852 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [10]
E0331 09:56:04.280478 01852 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [13]
E0331 09:56:05.281463 01852 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [13]
I0331 09:56:06.633421 01852 etcd.go:204] Picking subnet in range 20.1.1.0 ... 20.1.255.0
I0331 09:56:06.634529 01852 etcd.go:84] Subnet lease acquired: 20.1.36.0/24
I0331 09:56:06.637852 01852 ipmasq.go:50] Adding iptables rule: FLANNEL -d 20.1.0.0/16 -j ACCEPT
I0331 09:56:06.644230 01852 ipmasq.go:50] Adding iptables rule: FLANNEL ! -d 224.0.0.0/4 -j MASQUERADE
I0331 09:56:06.650452 01852 ipmasq.go:50] Adding iptables rule: POSTROUTING -s 20.1.0.0/16 -j FLANNEL
I0331 09:56:06.658806 01852 ipmasq.go:50] Adding iptables rule: POSTROUTING ! -s 20.1.0.0/16 -d 20.1.0.0/16 -j MASQUERADE
I0331 09:56:06.665567 01852 vxlan.go:153] Watching for L3 misses
I0331 09:56:06.665658 01852 vxlan.go:159] Watching for new subnet leases
I0331 09:56:06.666996 01852 vxlan.go:273] Handling initial subnet events
I0331 09:56:06.667053 01852 device.go:159] calling GetL2List() dev.link.Index: 4
I0331 09:56:28.184209 01852 vxlan.go:232] Subnet added: 20.1.1.0/24
I0331 09:56:28.184401 01852 device.go:164] calling NeighAdd: 10.85.81.166, 06:c8:be:55:f2:e6
I0331 10:04:40.677618 01852 vxlan.go:345] L3 miss: 20.1.1.2
I0331 10:04:40.677708 01852 device.go:187] calling NeighSet: 20.1.1.2, 06:c8:be:55:f2:e6
I0331 10:04:40.677976 01852 vxlan.go:356] AddL3 succeeded
I0331 10:05:00.388439 01852 vxlan.go:340] Ignoring not a miss: 06:c8:be:55:f2:e6, 20.1.1.2
I0331 10:05:08.902727 01852 vxlan.go:345] L3 miss: 20.1.1.2
I0331 10:05:08.902816 01852 device.go:187] calling NeighSet: 20.1.1.2, 06:c8:be:55:f2:e6
I0331 10:05:08.903024 01852 vxlan.go:356] AddL3 succeeded
I0331 10:05:28.612475 01852 vxlan.go:340] Ignoring not a miss: 06:c8:be:55:f2:e6, 20.1.1.2
I0331 10:08:07.298189 01852 vxlan.go:345] L3 miss: 20.1.1.2
I0331 10:08:07.298292 01852 device.go:187] calling NeighSet: 20.1.1.2, 06:c8:be:55:f2:e6
I0331 10:08:07.298666 01852 vxlan.go:356] AddL3 succeeded
I0331 10:08:29.924520 01852 vxlan.go:340] Ignoring not a miss: 06:c8:be:55:f2:e6, 20.1.1.2
## .............

Also some more info from node vm-1 (node vm-2 info is similar):
# ip -d link show flannel.1

4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether de:71:6e:55:36:75 brd ff:ff:ff:ff:ff:ff promiscuity 0
    vxlan id 1 local 10.85.81.165 dev eth0 port 32768 61000 nolearning ageing 300
# arp -n

Address                  HWtype  HWaddress           Flags Mask            Iface
10.85.81.129             ether   3c:8a:b0:8a:a3:31   C                     eth0
20.1.36.2                ether   02:42:14:01:24:02   C                     docker0
20.1.1.2                         (incomplete)                              flannel.1
10.85.81.166             ether   00:50:56:a9:58:7a   C                     eth0
# bridge fdb show dev flannel.1

06:c8:be:55:f2:e6 dst 10.85.81.166 self permanent
# bridge fdb show dev docker0

02:42:cf:32:13:6f vlan 0 permanent
# bridge fdb show dev eth0

01:00:5e:00:00:01 self permanent
33:33:00:00:00:01 self permanent
33:33:ff:a9:11:21 self permanent
# ifconfig

docker0   Link encap:Ethernet  HWaddr 02:42:cf:32:13:6f
          inet addr:20.1.36.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:cfff:fe32:136f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:80 errors:0 dropped:0 overruns:0 frame:0
          TX packets:25 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:20968 (20.9 KB)  TX bytes:3043 (3.0 KB)

eth0      Link encap:Ethernet  HWaddr 00:50:56:a9:11:21
          inet addr:10.85.81.165  Bcast:10.85.81.255  Mask:255.255.255.128
          inet6 addr: fe80::250:56ff:fea9:1121/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:14131 errors:0 dropped:13 overruns:0 frame:0
          TX packets:21040 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1793686 (1.7 MB)  TX bytes:80814089 (80.8 MB)

flannel.1 Link encap:Ethernet  HWaddr de:71:6e:55:36:75
          inet addr:20.1.36.0  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::dc71:6eff:fe55:3675/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:26 errors:0 dropped:0 overruns:0 frame:0
          TX packets:85 errors:0 dropped:8 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2016 (2.0 KB)  TX bytes:9186 (9.1 KB)

Also we tried to use Flannel backend "udp", and it did not have this above-described issue when using  backend "vxlan". When using backend "udp", the pods from different nodes can ping/communicate with each other. And we noticed in the flannel.log file, both "L3 miss"/"Added L3 succeeded" and "L2 miss"/"Added L2 succeeded" logs. 

It is strange that when use Flannel backend "vxlan",  the pods from different nodes cannot ping/communicate with each other. And in the flannel.log file, only "L3 miss"/"Added L3 succeeded" logs are there, without any "L2 miss"/"Added L2 succeeded" logs. 

Any insight and help with this issue will be appreciated very much.

**Comment by junelee05** [comment]
Correction:
Our Kubernetes two-nodes-cluster setup is:

vm-1 (public-ip: 10.85.81.165): master + worker-node
vm-2 (public-ip: 10.85.81.166): worker-node

**Comment by ganting** [comment]
@junelee05 i got the same problem with you, do you solve it?

**Comment by yanyixing** [comment]
got the same problem.so sad

**Comment by vladar** [comment]
Same here with ubuntu-based cluster on 1.3.4
