### ISSUE TITLE
kubernetes-e2e-gce-enormous-startup still running even after deletion of job definition yaml.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#23681]
We removed it in #23042 but it's still running on Jenkins.

cc @wojtek-t

**Comment by spxtr** [comment]
Right, we don't automatically clean up old jobs yet. Want me to delete this now?

**Comment by gmarek** [comment]
Yes please;)

**Comment by gmarek** [comment]
But we need to clean up GCE resources as well.

**Comment by spxtr** [comment]
OK, the Jenkins job is gone now.

**Comment by gmarek** [comment]
Thanks!

**Comment by spxtr** [comment]
It looks like kubernetes-kubemark-gce is also removed from source?

**Comment by gmarek** [comment]
Yup.

**Comment by spxtr** [comment]
OK, removed that as well. Is this issue taken care of?

Eventually we'll want to switch on the flag to remove old jobs.

**Comment by gmarek** [comment]
Assuming that resources are removed as well, then yes.
