### ISSUE TITLE
Kubernetes reconstructs the container LogPath instead of querying Docker

### ISSUE THREAD

**Issue by elyscape** [kubernetes/kubernetes#23695]
After starting a container, Kubernetes places a symlink to the container's log file in `/var/log/containers`. Unfortunately, rather than querying Docker for the `LogPath`, [it replicates the logic used to build it][reconstruction]. This means that any change upstream in the path or filename that Docker uses to store its logs (e.g. to `/var/lib/docker/containers/$ID/json.log` so that a file name transition would be a workable solution for docker/docker#21672) would result in broken symlinks being put in place. It would be a better idea to query for the `LogPath`, potentially by doing something like this:

```go
if nativeContainer, err := dm.client.InspectContainer(id.ID.ID); err != nil {
	// handle errors
}
containerLogFile := nativeContainer.LogPath
```

This would allow Docker to put the log files anywhere and have symlinks put in the right place.

[reconstruction]: https://github.com/kubernetes/kubernetes/blob/v1.2.0/pkg/kubelet/dockertools/manager.go#L1537

**Comment by asalkeld** [comment]
I will start work on this one, PR coming soon.
