### ISSUE TITLE
rkt should support running the pod in HostPID/HostIPC namespace

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#23692]
In the [api.PodSecurityContext](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1240-L1243), we can specify the pod to be running in the host pid/ipc namespace. I think this can be implemented in rktnetes by using `rkt fly`.

@kubernetes/sig-node @sjpotter @euank @steveeJ @jonboulle

**Comment by jonboulle** [comment]
Do we need to worry about other namespaces?

**Comment by yifan-gu** [comment]
@jonboulle Actually the containers should be in different mount namespace, but that's another question.

**Comment by yifan-gu** [comment]
@jonboulle Speaking about pods, then the docker provides finer grain control, e.g. it can launch a contianer with host pid namespace and separate ipc namespace. But I don't know the use case for this.

rkt can do either all in separate namespace (`rkt run`), or all in host namespace (`rkt fly`).

**Comment by yujuhong** [comment]
Not directly related to this issue, but we want containers in the same pod to share PID and UTS namespaces eventually (#1615).

**Comment by yifan-gu** [comment]
As I am implementing this, I found the below problems:
1. `rkt fly` does not support multiple apps(containers) as it is essentially just chroot.
2. `rkt fly` makes the pod share the same mount namespace as host, which seems will surprise users.

Some thoughts how we can solve this:
- Make the `rkt fly stage1` be able to:
  - Unshare the specified namespace
  - After unshare, fork and exec each apps
  - Pause there to hold the namespace.

- Or, we can do this with `systemd-nspawn`, which already provides `--share-system`, but that also requires we replace the systemd in stage1 with some process which will do `fork, exec, pause` as mentioned above...

cc @jonboulle @philips @alban @iaguis

**Comment by alban** [comment]
Is there any existing Kubernetes pods with HostIPC=true without HostPID? In a [quick look on GitHub](https://github.com/search?p=2&q=hostIPC&type=Code&utf8=%E2%9C%93), HostIPC and HostPID always seem to have the same value, unless it is in k8s tests.

**Comment by yujuhong** [comment]
Closing this since relevant issues should be handled in CRI or moved to the rktlet repository.
