### ISSUE TITLE
About upper-case letters in label keys

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#23706]
From [docker labels doc](https://docs.docker.com/engine/userguide/labels-custom-metadata/), it's recommended that the keys do not contain upper-case letters. But we do have keys with upper-case letters today in some [labels used by kubelet](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/labels.go#L40-L41)

This causes a problem for rkt because appc/spec [doesn't allow upper-case letters in annotation keys](https://github.com/appc/spec/blob/master/spec/types.md#ac-name-type). As the annotation key follows the [DNS_LABEL](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L40-L43) rule.

So what we can do?
- Change the labels we use today to use only lower-case letters, which follows the DNS_LABEL rule and docker's recommended convention.
- Make the appc/spec to accept upper-case letters (https://github.com/appc/spec/issues/588), because even we after 1) is done, we still cannot prevent users from injecting upper-case letters in the docker images' labels, as docker doesn't prevent this. 

cc @kubernetes/sig-node @jonboulle @thockin @smarterclayton @sjpotter

**Comment by vishh** [comment]
Update the labels to conform to Kubernetes API conventions?

**Comment by smarterclayton** [comment]
Changing the labels is not a backwards compatible change without extra
work, but the impact is minor.  The graceful termination labels are used in
the event that the API server is not available and the pod should be
gracefully shut down (because something else is going on).  If we change
the key, we'll need to continue reading the old value.  That's probably
sufficient for now.

I don't know of anyone relying on the labels (under our prefix).

**Comment by Random-Liu** [comment]
Offline discussed with @yifan-gu, we could fall back to get data from the old labels, if it is an old container.

**Comment by yujuhong** [comment]
We do plan to rely on labels more so that we don't have to keep polluting the docker container names, but like @Random-Liu said, we can make it backward compatible.

**Comment by jonboulle** [comment]
+1 on moving to lower case (also per https://github.com/appc/spec/issues/588#issuecomment-204656503)

**Comment by yifan-gu** [comment]
Assign to @sjpotter who is clearer with the use case of this.

**Comment by yifan-gu** [comment]
This can be closed, right? @sjpotter

**Comment by Random-Liu** [comment]
@yifan-gu We could close this one and track #25326 on #24702.
