### ISSUE TITLE
Mention the new #kubernetes-novice Slack channel in relevant places

### ISSUE THREAD

**Issue by timbunce** [kubernetes/kubernetes#23702]
The #kubernetes-users channel has >3700 users online at the moment and get fairly busy with detailed technical discussions so novice questions can be drowned out and lost in the backlog.

There's now a [#kubernetes-novice Slack channel](https://kubernetes.slack.com/archives/kubernetes-novice) created by @sarahnovotny.

It would be helpful to mention, and link to, the channel in relevant places in the documentation, Kubernetes.io, wikis etc.

**Comment by mikebrow** [comment]
Sure.. I'll post a PR.  Don't see a good spot on the wikis for this as it currently just points to the slack domain for Kubernetes in general.  But I do see a good spot on the troubleshooting.md guide.

**Comment by mikebrow** [comment]
This issue should be closed.
