### ISSUE TITLE
epic: Reducing network overhead and optimizing kubernetes control plane communications

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#23709]
Per @quinton-hoole's request, I'm attempting to chart a well established path such that we can address some of the larger communications issues.  Hopefully this can serve as a jump point for the communications issues we wish to target in the 1.3 cycle. 
## Problem Statement

The **overhead** and data flow of the kubernetes control plane has led to a series of artificial limits, or **caps** (qps,max-inflight, etc), that have been placed on different system components.  These caps are an attempt to limit the system from overloading the api-server, and to ensure certain SLOs are met.  The core issue is not that the caps exist, but the fact that the interaction between the components can cause system overload in the first place.  

This epic, targeted for 1.3, is intended to help breakdown some of the different facets of this issue as we see them today, and address each aspect independently, provided there are resources available to do so.

The higher level objective would be to fix the system where possible, in order to prevent the degenerative case of overloading from occurring... at all.
## Breakdown

From operations and tests, we have witnessed the following issues which relate to this broader epic:

**P1:** There are a large number of connections in the system. (#21081) 
- _Worst offenders are not quantified?_
- **A1.1:** Analyze api-server metrics, and add metrics on who is creating the most connections, investigate their usage, and optimize their workflow.  Different solutions may exist depending on the situation, which in turn may become their own issues.  (This is a meta-problem).
- _Each new connection incurs an overhead in the system (TLS+kernel+application), and there isn't a single choke-point to throttle during overloaded situations._
- **A1.2:** Pursue http2 for internal communications, each component should have only 1, or 2 connections to the main api-server, as well as golang 1.6 for the decreased EC/TLS overhead.  

**P2:** Components do not properly back-off under extraneous load conditions. 
- _We can create a number of conditions which can cause the system to overload, e.g. fail-over, or aggressive loading._
- **A2.1:** Once we've addressed P1, and have a single choke-point it's relatively trivial to back-off during loaded situations. 

**P3**:  Enconding and decoding dominate api-server load 
- **A3.1:** We've known this for a long time, and there are a series of issues around protobuf and gRPC to address. @wojtek-t has an issue list. 

/cc @kubernetes/sig-scalability @jeremyeder

**Comment by mqliang** [comment]
I am also interested in this issue. +1 for golang 1.6 w/ http2. And I have some suggestion:

1) Analyze how many requests sent to API server, and find out who is sending those requests
2) Is every http request necessary? Could we remove it? If a request is indeed necessary, should it be so frequent?

I find that at least one kind of frequent request is not necessary: 
>
In 1.2, every node will frequently send PUT request to API server to update it's status(every 10s using default configure), If we let NodeController initiatively do the health check, We could significantly reduce the number of request.
>
IIRC, in kubernetes v0.12, we make NodeController initiatively do the health check [DoChecks](https://github.com/kubernetes/kubernetes/blob/release-0.12/pkg/cloudprovider/controller/nodecontroller.go#L344), but after v1.0, we make kubelet update it's status. Is there good reason for this change?

**Comment by timothysc** [comment]
Currently analyzing A1.1 issues, which relates to finding the worst offenders. 

#23819 is related due to it's inefficiencies.

**Comment by magicwang-cn** [comment]
+1 too.  
and there are also a lot of duplicate list-watch request with the same resource in the same component.

++1
>P3: Enconding and decoding dominate api-server load

A3.1: We've known this for a long time, and there are a series of issues around protobuf and gRPC to address. @wojtek-t has an issue list.

**Comment by timothysc** [comment]
P1 and P3 are done now, P2 is partially done but there are other issues around it... closing.
