### ISSUE TITLE
Static build of kubectl for containers w/minimal base images

### ISSUE THREAD

**Issue by jackgr** [kubernetes/kubernetes#23708]
In https://github.com/kubernetes/helm, we're looking to use alpine:3.3 as a base image to keep the footprint small. However, we run kubectl in the container. That's a problem on alpine, and probably other minimalist base images, because kubectl is dynamically linked and so won't launch. Please consider including a static build of kubectl in binary releases.

/cc @david-mcmahon, @jlowdermilk

**Comment by jlowdermilk** [comment]
We've talked about just making kubectl a static build [before](https://github.com/kubernetes/kubernetes/pull/11694#issuecomment-144429998), but I can't recall why we chose not to. If it doesn't increase binary size too much or cause other problems, would be useful.

**Comment by david-mcmahon** [comment]
@lavalamp is this something we can or want to do?   Was anyone actively looking into it at some point?

**Comment by lavalamp** [comment]
We *do* make a static kubectl binary for incorporation into a container.

https://github.com/kubernetes/kubernetes/tree/master/examples/kubectl-container

**Comment by lavalamp** [comment]
I don't know if we auto build that when we cut a release.

**Comment by redbaron** [comment]
FYI, dynamic kubectl works just fine, at least one from hyperkube, all is needed is to call it via dynamic linker explicitly:

`/lib/ld-musl-x86_64.so.1 /opt/bin/hyperkube kubectl $@`
