### ISSUE TITLE
density test assumes cluster of uniform node size

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#23710]
Looks like #22284 modified the e2e density test to use dynamically computed resource requests based on the size of an arbitrary node in the cluster.  

Problem: I have a cluster consisting of differently sized nodes.  It appears the test occasionally picks a larger node, and uses resource requests that are eventually too large to fit on the smaller nodes.

Do we..
a) compute resource requests based on the smallest node in the cluster
b) go back to hardcoded resource requests for the initial batch of pods, leave the latency pods dynamically computed
c) mandate that density can only be run against clusters of uniform node size
d) other?

/cc @kubernetes/sig-scalability @wojtek-t

**Comment by wojtek-t** [comment]
@spiffxp - this test is NOT supposed to run correctly on clusters with different node sizes
That's by design - changing it would complicate the code a lot.

I think that what we need to do is (c) from your list.

**Comment by spiffxp** [comment]
@wojtek-t I guess I'm trying to understand the motivation behind dynamically computing the resource requests for the initial batch vs making them as small as possible, to ensure the initial batch would fit everywhere?

If we go the (c) route, it would be nice to use a `SkipUnless`-style gate to ensure all nodes have the same resources

/cc @kubernetes/sig-testing

**Comment by wojtek-t** [comment]
>
@wojtek-t I guess I'm trying to understand the motivation behind dynamically computing the resource requests for the initial batch vs making them as small as possible, to ensure the initial batch would fit everywhere?

@spiffxp - the motivation is that we would like to have pods spread evenly between nodes (or as evenly as possible). I don't want to have all pods being scheduled on the same node. 
This seems to be the easiest way to achieve it.
Note that, scheduling priority is a pretty complicated function, so achieving it in a different way would be very tricky.

>
If we go the (c) route, it would be nice to use a SkipUnless-style gate to ensure all nodes have the same resources

Yes.

**Comment by spiffxp** [comment]
OK thanks for explaining, that makes sense.  I'll see if I can get to a PR on the `SkipUnless` piece in the next week

**Comment by jayunit100** [comment]
Nice find. We should make the --scale option do a more organic density test that is relevant to large heterogenous cluster types

**Comment by spiffxp** [comment]
don't think we really need this anymore
/close
