### ISSUE TITLE
wait.Until() has no way to guarantee goroutine termination

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#23715]
Spun out of #22848, which spells it out in detail.  The interface needs to be changed in at least two ways as I see it, but there might be something simpler we can do.  (1) We need a way to determine that the goroutine running the loop has been stopped.  (2) Once we do that, we'll need to change something to avoid the potential for deadlock that this would expose.  I have end-of-day brain, but I might sketch some solutions tomorrow.

**Comment by timothysc** [comment]
This is general tool-ing issues.  I've been in this code so self assigning, but not for 1.6.

**Comment by spiffxp** [comment]
/sig testing

@timothysc will you have the cycles to get this in for v1.7?
