### ISSUE TITLE
Kubernetes allows to create pods in a namespace when namespace object doesn't exist.

### ISSUE THREAD

**Issue by flashvoid** [kubernetes/kubernetes#23713]
So, just discovered that kubernetes allows to create a pod in a namespace when namespace object itself doesn't exist.

```
root@ip-192-168-0-10:/home/ubuntu# kubectl get pods -o wide --namespace=tenant-a
NAME             READY     STATUS    RESTARTS   AGE       NODE
nginx-frontend   1/1       Running   0          33m       i-b6cd1203

root@ip-192-168-0-10:/home/ubuntu# kubectl get namespaces 
NAME      LABELS    STATUS    AGE
default   <none>    Active    34m

root@ip-192-168-0-10:/home/ubuntu# cat romana/kubernetes/pod-frontend.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-frontend
  namespace: tenant-a
  labels:
    app: nginx
    segment: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80


root@ip-192-168-0-10:/home/ubuntu# kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
```

With multi-tenancy coming to kubernetes and namespaces representing tenants - having pods running outside of namespaces, let alone in a namespace that doesn't exist, isn't something that should be allowed, is it ?

**Comment by zhouhaibing089** [comment]
@liangjinebaycom since you are interested in auto namespace.

**Comment by liggitt** [comment]
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
How is your cluster configured?

Are you running with the recommended set of admission controllers?

See: http://kubernetes.io/docs/admin/admission-controllers/#namespacelifecycle

Please re-open if you are using a project supported getting started guide so we can update its documentation error in how to bootstrap the cluster.
