### ISSUE TITLE
Decouple Group Population from Authentication

### ISSUE THREAD

**Issue by bobbyrullo** [kubernetes/kubernetes#23720]
Upon successful Authentication, authentication plug-ins are responsible creating the `user.Info` object. Authorization plugins are expected to call that object's `GetGroups []string` method to determine which groups a user belongs to. 

The main problem with binding authn and groups together in this way is that not every authn method has a well-defined notion of groups, in which cases you'd want some other plug-in to populate groups. The OIDCAuthenitcator is motivating example (for me anyhow): OpenID Connect has well-defined authentication semantics, but there's no standard around group membership.

In an discussion with @erictune and @sym3tri, we outlined several different possible solutions to the problem:
1. There is a new method added to `user.Info` with the signature `ExternalGroups() bool`; if this flag is true, during the AuthorizationAttribute building phase (before the authz plug in is called), the authz attr builder will call out to some groupifier plug-in which will populate the groups in the `Info` object, and pass it along to the authz plug-in
   ![groups_1](https://cloud.githubusercontent.com/assets/9629/14194892/f9326460-f767-11e5-9d5a-6f63d09c75eb.png)

The advantage to this solution is that Authorizers do no have to worry about group population, so very little needs to change on their end. A disadvantage is that it's rather coarse: The authorizer might only care about a user's membership in a particular group, but instead they have to get all of them (which in a large company might be a sizeable number, and in some cases (for example some LDAP configurations) such enumeration might be disallowed by policy)
1. A second solution is similar to the first, except that authorizers are responsible for calling out to the groupifier.
   ![groups_2](https://cloud.githubusercontent.com/assets/9629/14194983/26df5cdc-f769-11e5-8357-d657565600dd.png)

The advantage here is that Authorizers can ask the groups API which groups they'd like to check the membership of (eg. `CheckMembership(user, group) bool`) instead of having to ask for them all, since the Authorizer knows what groups it is interested in.

The disadvantage here is that all authorizers now have to deal with getting groups.

With either solution, there would have to be a reasonable Groups API defined for plugins, and some reference implementation - An initial implementation could be a file based groups solution. I'd be most interested in a web hook type solution (or, if it's time for that sort of thing, a GRPC based one)

**Comment by bobbyrullo** [comment]
CC: @ericchiang, @sym3tri

**Comment by bobbyrullo** [comment]
@deads2k and @liggitt : I'd love feedback from you guys, since I'd really like to be able to use the Openshift authz stuff when it lands upstream, and that would depend in a large part on how groups are populated.

**Comment by liggitt** [comment]
I don't see a need to change the interface. You can wrap an existing authn impl with a group-adding impl. In openshift, in addition to groups determined by the authenticator impl, we assign synthetic groups (`system:authenticated:oauth` is added to any user authenticated with an OAuth token, `system:authenticated` is added to any user authenticated via any source, etc)

**Comment by liggitt** [comment]
For example, this is our auth chain in openshift:
https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/master_config.go#L295

**Comment by liggitt** [comment]
I need to think through the implications of authorizers interrogating the user info about specific groups some more

**Comment by bobbyrullo** [comment]
> You can wrap an existing authn impl with a group-adding impl. 

But then you are mandating that a particular authn implementation is tied to a particular groups implementation which seems wrong.

**Comment by liggitt** [comment]
Right. The authentication layer (request in, user info out) can be composed from multiple sources

**Comment by bobbyrullo** [comment]
Hmmm. So are you proposing some new sort of way of configuring authenticators that let's them chain or something?

**Comment by liggitt** [comment]
> So are you proposing some new sort of way of configuring authenticators that let's them chain or something?

I think I'm proposing something similar to your first proposal, but without modifying the user.Info interface. An `authenticator.Request` impl that delegates to the existing auth chain, and on success determines additional group info could be very useful, though expressing all the desired configurations could be tricky. I could see use cases for all of these:
* hard-coded groups for different authenticators (e.g. OpenShift's oauth or anonymous groups)
* remote call group lookups
* cached group lookups

**Comment by bobbyrullo** [comment]
follow up from the sig-auth meeting:

Here's the broad strokes of a proposal, based on what I think we all agreed to:

* User Groups should be pluggable
* The Interface for groups should be essentially `AddGroups(user UserInfo)`
  * (note that because UserInfo is an interface, we'd have either have to have a new UserInfo implementation that wraps an underlying UserInfo and return that or add AddGroups([]string) to UserInfo)
* The (optional) configured groups plugin will be called after authentication and before authorization
* Authenticators populating groups is still supported - in the case where the Authenticator populates groups and the plugin does as well, it's additive and not namespaced (everyone agreed that namespacing will break things unless the authorizer is de-namespacing, which is a weird coupling)


Things we are not doing at this point:
* upstreaming RedHat Users/Groups
* providing a IsMember(user, group) method.

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-auth

**Comment by bobbyrullo** [comment]
@slashk, @kfox1111

**Comment by kfox1111** [comment]
One thing I'm not really clear about.... Will there be the ability to have more then one authentication plugin, and if so, how are group/username collisions avoided? 

In keystone, they solved it this way:
There can be multiple domains. The user must select the domain when authenticating. Each domain has one and only one authenticator plugin. user/group names are unique within that domain only. a group is a collection of usernames. a group can only have users in it from the same domain.  groups can't have other groups in them. Every group/user has a uuid which is unique to the whole cloud assigned by the cloud to guarantee uniqueness across the whole cloud. Every time a permanent record is made of a user or group, its done by that unique id.

so for users, taking about group/user name "foo", they have to also specify a domain.

For example, if they are authenticating via a scoped token (the normal way), they need to specify:
user_name
user_domain
project_name
project_domain

user_domain and project_domain can be different.

Or they can just refer to user_id = x and project_id = y, since that is guaranteed to be unique.

Rbac in k8s should probably just use id's for dealing with keystone things then.

**Comment by ericchiang** [comment]
> One thing I'm not really clear about.... Will there be the ability to have more then one authentication plugin, and if so, how are group/username collisions avoided?

@kfox1111 What Bobby is proposing here is separating authentication and groups membership retrieval. For our purposes, it's not always practical to bake in every group a user is a part of into a signed token. In a sense you'd have a two phase authentication where the group membership is a different plugin and possibly gets some context about what was actually being requested.

As for Openstack auth vs. Kubernetes. These concepts of groups and users shouldn't be conflated as one to one mappings between other systems. They're Kubernetes constructs. A username is just a string and groups are set of strings. It's up to the authorizer to determine what the actual semantic meaning is.

There seems to be a lot to your question, and I don't know if it's entirely related to this PR. Perhaps some discussion might be better suited for kubernetes/kubernetes#24982?

**Comment by kfox1111** [comment]
Yeah, I get that. I'm just worried that it might already be a problem where groups might have conflicting meanings between different authn/authg(group adder plugins?), and this has the potential for increasing the problem. Do you know how that works? Can there ever only be one authn plugin? how does that work with serviceusers?

I mentioned keystone not in that its specifically an issue with keystone, but that, keystone's been doing authentication/authorization for a long time now, and they have tripped across a lot of the things that k8s is now facing as k8s adds authn/authz. The experience gained by the keystone team may help the k8s sig-auth team avoid some missteps keystone made.

**Comment by ericchiang** [comment]
> Yeah, I get that. I'm just worried that it might already be a problem where groups might have conflicting meanings between different authn/authg(group adder plugins?), and this has the potential for increasing the problem. Do you know how that works? Can there ever only be one authn plugin? how does that work with serviceusers?

Yes, you can declare multiple authenticators, though only one will ever trigger for a specific request. No, there's no attempts to prevent conflicts. It's up to the auth(n/z) implementations to provide meaning to things like usernames and groups (which may or may not parallel with actual users and groups) and avoid conflicts. This is true for the existing authn plugins and this proposal doesn't attempt to address this.

> I mentioned keystone not in that its specifically an issue with keystone, but that, keystone's been doing authentication/authorization for a long time now, and they have tripped across a lot of the things that k8s is now facing as k8s adds authn/authz. The experience gained by the keystone team may help the k8s sig-auth team avoid some missteps keystone made.

Right, and that's appreciated. I just want to ensure we're using the proper form to discuss concerns and not hijacking @bobbyrullo's proposal :)

**Comment by kfox1111** [comment]
Ok. Thanks for the clarification.

So... the one thing I think may be needed here then, is a way for a plugin that is adding more group information to an existing authn authentication is a way for it to know which authn plugin was used, so it can determine if it should add groups or not.

**Comment by ericchiang** [comment]
Been thinking about this a lot and would like to propose something a bit more concrete. I'd like to see an implementation of this thread that changed the auth flow from:

```
auth-N -> auth-Z -> admission
```

To:

```
auth-N -> groups -> auth-Z -> admission
```

The groups interface would look something like.

```go
// Grouper is a component which adds additional groups to an existing user.
type Grouper interface {
    Groups(u user.Info) (groupNames []string, err error)
}
```

Groups returned by this interface would be added (union) to the user.Info object between auth-N and auth-Z.

Additionally I'd like to propose an initial implementation that read groups from the API in order to determine which groups a user had. This would add the following `authentication.k8s.io` types:

```go
// Group is a set of users that share authorization policies. Not namespaced.
type Group struct {
    unversioned.TypeMeta `json:",inline"` // Name used as group name
    v1.ObjectMeta        `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`

    // Users that are associated with this group.
    Members []Member `json:"members,omitempty"`
}

// Member of a group.
type Member struct {
    Kind string `json:"kind"` // Initially only support "User", might expand to service accounts or groups of groups
    Name string
}
```

I'd like to see this because it means I can develop syncers to dump groups into Kubernetes without having to compile plugins into Kubernetes or write webhooks. An obvious use case is to write a CRON like job to grab groups from LDAP or any other teams based system.

cc @kubernetes/sig-auth

**Comment by deads2k** [comment]
I'm ok with the interface, but I don't care for the API.

It would be really strange to be opinionated about the representation of a group when we have no opinion about a user.  Then, when you start talking about having a user, its not very useful to have the concept of a user without the corresponding concept of identities which map to that user.  It's really hard to have a meaningful API without covering all three concepts and those three concepts are by-nature strongly opinionated.

**Comment by ericchiang** [comment]
FYI I'd like to working on adding this webhook in 1.7. Specifically, adding a interface like:

```go
// Grouper is a component which adds additional groups to an existing user.
type Grouper interface {
    Groups(u user.Info) (groupNames []string, err error)
}
```

and adding a webhook implementation.

**Comment by mikedanese** [comment]
@ericchiang have you decided whether you are going to tackle this for 1.7?

**Comment by ericchiang** [comment]
@mikedanese yes I'm planning on working on this over 1.7.

**Comment by mlbiam** [comment]
@ericchiang i'm a little confused by the word "sync".  would this be in real-time or something that would create objects inside of k8s similar to openshift's User an Group objects?  Also, i wouldn't assume "union", it should be configurable.  I've worked on several deployments over the years (not k8s related, generic idm) where groups from a central idp are completely worthless because the owner of the idp isn't the same person as the owner of the group information so it would be better to have a way to simply ignore it if you don't need or want it.

**Comment by ericchiang** [comment]
@mlbiam it would just be a webhook. E.g. webhook gets the current userinfo, then gets to add groups.

**Comment by mikedanese** [comment]
Should we expect that the group plugin will be called during a TokenReview and that the response will be used to populate the UserInfo returned?

**Comment by ericchiang** [comment]
@mikedanese I was planning on writing a RequestAuthenticator wrapper similar to the way the `system:authenticated` groups get added. So yes, it should be passed along to the TokenReview registry.

**Comment by liggitt** [comment]
> @mikedanese I was planning on writing a RequestAuthenticator wrapper similar to the way the system:authenticated groups get added

Can you update the design/description to reflect the proposed approach?

**Comment by ericchiang** [comment]
@liggitt I can't edit the original comment but will open a PR to community today with updated proposal. That work?

**Comment by liggitt** [comment]
yes, that should replace this

**Comment by ericchiang** [comment]
@liggitt After internal debate I don't think I'm going to be pursuing this for 1.7. Much of this can be achieved through token access reviews or bulk syncing to RBAC roles and it's not clear how much benefit we'd actually get from adding another webhook. Going to put this on hold for now rather then try to get in into 1.7.

**Comment by cosmincojocar** [comment]
@ericchiang @liggitt Do you have any plans to move on with this feature? 

I'm investigating the integration of Azure Active Directory groups with RBAC roles. Azure Active Directory typically embeds a custom claim into the JWT, which points to the Graph API from where the groups can be fetched, something like this:
```
"_claim_names": {
     "groups": "src1",     
   },
   "_claim_sources": {
     "src1": {"endpoint": "https://graph.windows.net/developertenant.onmicrosoft.com/users/ a21197f6-5ac6-460b-b5d3-2a1ae6bd08c1/getMemberObjects"}
   }
```  
The call to the Graph API must be authenticated as well. I am curios to hear you recommendations regarding this.

**Comment by ericchiang** [comment]
@cosmincojocar I moved away from implementing this in 1.7 because the token auth-N webhook is probably sufficient for our use cases. A group webhook is probably even harder because it'd require the OpenID Connect plugin to start passing more claims via the user Extra fields. e.g. how would your webhook get the `_claim_name` custom claim?

I wrote up a short proposal for CoreOS explaining our current pain points around the OpenID Connect plugin and how moving to the token auth-N webhook would solve some of our internal issues, including group information. Hope that helps. https://docs.google.com/document/d/1uMBo9dkQozaZn25NzsL_bklONCzLPtXeXIhteD2t_dE/edit?userstoinvite=josh.hull@lypht.com&ts=5963997d

**Comment by cosmincojocar** [comment]
@ericchiang Thanks, this is very helpful. The solution would be to deploy a webhook service between api-server and AAD, which can receive `TokenReview` requests over a mutually authenticated TLS connection. It verifies the bearer token, fetches the groups from Graph API if token is valid, and then returns the groups in the `TokenReview` response to the api-server.

**Comment by mikedanese** [comment]
cc @jboeuf

**Comment by liggitt** [comment]
closing inactive issues

if this is desired, a [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/) can be opened with a proposal

/close
