### ISSUE TITLE
Getting started guide, no user/pass for getting into UIs

### ISSUE THREAD

**Issue by txomon** [kubernetes/kubernetes#23727]
I know this might be obvious for people long using kubernetes, but I have been unable to find how to access all these interfaces in the getting started guide.

```
cluster/kubectl.sh cluster-info
Kubernetes master is running at https://10.245.1.2
Heapster is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
```

I have tried with the getting started guide from vagrant, and although it centers itself on getting access through the command line, which works, I believe someone trying may be interested in knowing how to access those interfaces.

Would it be possible to add a line in the docs to know where the user/pass to get in those interfaces are located?

I tried with `cat ~/.kube/config` but it doesn't have information about it...

**Comment by zhouhaibing089** [comment]
I think the document already shows how to authenticate with master from here: http://kubernetes.io/docs/getting-started-guides/vagrant/#authenticating-with-your-master

**Comment by txomon** [comment]
Sorry, I forgot to tell, such file doesn't get generated. I am able to successfully login into the machines, but the file with the credentials, I cannot find it anywhere

**Comment by bgrant0607** [comment]
cc @bryk

**Comment by bgrant0607** [comment]
cc @derekwaynecarr re. vagrant

cc @dlorenc @vishh re. avoiding this problem in minikube

**Comment by derekwaynecarr** [comment]
Is the issue logging into heapster or kube itself?

Vagrant uses vagrant/vagrant as a user/password.

Will check documentation, but thought it was there.

**Comment by txomon** [comment]
Yes, but would it be possible to print those credentials when using some of the quick start scripts? That would be really helpful!

**Comment by benhosmer** [comment]
I _think_ what @txomon 's original post meant was that it was unclear how to login in to the GUI('s) provided using the local vagrant `kube-up.sh`.

While the most recent install, referenced from the [kubernetes with vagrant](http://kubernetes.io/docs/getting-started-guides/vagrant/) guide does print the instructions to stdout, it isn't mentioned anywhere in the online documentation. I can see how a user could miss these, since on my machine they scrolled by.

```
The user name and password to use is located in /home/bhosmer/.kube/config

... calling validate-cluster
Found 1 node(s).
NAME                STATUS    AGE
kubernetes-node-1   Ready     1m
Validate output:
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   
scheduler            Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
etcd-1               Healthy   {"health": "true"}   
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://10.245.1.2
Heapster is running at https://10.245.1.2/api/
...
```

This `The user name and password to use is located in /home/bhosmer/.kube/config` did not get me into cockpit, however vagrant/vagrant did.

Also, vagrant/vagrant gets me past the auth password, but results in: `Forbidden: "/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard"`

**Comment by txomon** [comment]
Yes, sorry for not answering but that was indeed what happened to me. Even
if I had the user pass it wouldn't work everywhere.

Would be possible to print all the credentials at once?

**Comment by paulosotu** [comment]
hey guys any update on this?

**Comment by mlbiam** [comment]
Has anyone found a fix for this?  I'm only able to access the dashboard via port forwarding to 8080 on the master host

**Comment by bryk** [comment]
Is this an issue with Vagrant setup documentation? 

What other way do you want to access the Dashboard UI?

**Comment by mlbiam** [comment]
I'm trying to access the dashboard through the URL printed in the output: kubernetes-dashboard is running at https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard am I missing something?

**Comment by bryk** [comment]
That's OKay. You should get the password from your kubeconfig file. I assume that you have kubectl configured and working correctly.

**Comment by mlbiam** [comment]
Actually, got it working with kubectl proxy.  Basic auth doesn't seem to
work for the API server on 443.

**Comment by benhosmer** [comment]
@bryk check my comment from above. The credentials stored in `~.kube/config` didn't work for me. I haven't tested this issue lately though.

**Comment by bryk** [comment]
@benhosmer I think that's because the server does not know how to serve SSL on port 443.

**Comment by derekwaynecarr** [comment]
This fell off my radar.  I will doc something up.

**Comment by etotheipi** [comment]
I have the same problem as @benhosmer:  in my vagrant cluster I ran into the `Forbidden: "/api/v1/proxy/namespaces/kube-system/services/"` issue.

* Used the kube-up.sh script which setup my vagrant boxes and printed the instructions as others have mentioned
* Went to `https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard` in my browser, which requested a login
* Attempted the `admin` and `<longrandomstring>` from the  `~/.kube/config`.  Does not work.
* I use `vagrant ssh master` to get into the master and use `ps aux` to find the api-server process.  I see that it uses `--basic-auth-file=/srv/kubernetes/basic_auth.csv`
* Viewing `/srv/kubernetes/basic_auth.csv` reveals `vagrant,vagrant,admin`.  As far as I can tell, that means that user/pass=vagrant/vagrant should get me the privileges of `admin`
* `vagrant`/`vagrant` gets me past the login but gets the forbidden issue:  `Forbidden: "/api/v1/proxy/namespaces/kube-system/services/"` 

How am I supposed to to get to the dashboard?  It's been good I have to learn all the CLI tools, but I really would like to explore the UI as well.

**Comment by mlbiam** [comment]
use kubctl proxy then point your browser at http://localhost:8000

Marc Boorshtein
CTO Tremolo Security
marc.boorshtein@tremolosecurity.com
(703) 828-4902
Twitter - @mlbiam / @tremolosecurity

**Comment by alexanderilyin** [comment]
Worked for me in this way:

In 1st `Terminal.app`
```
$ ./cluster/kubectl.sh proxy
Starting to serve on 127.0.0.1:8001
```

In 2nd `Terminal.app`
```
open http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
```

Result:

![screen shot 2016-10-06 at 8 08 01 pm](https://cloud.githubusercontent.com/assets/272409/19177763/edadd51a-8c00-11e6-8201-3e317db89e27.png)

**Comment by mikeyp** [comment]
I have the exact same scenario as @etotheipi with 1.4.1. Brought up a single node cluster and I am able to create deployments, services, etc and they work as expected. UI won't work at all. Password from ~/.kube/config isn't valid for dashboard, using vagrant/vagrant gets past basic auth only to get `Forbidden: "/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard"`. Tried using the kubectl proxy but when accessing it I just get 403 and `<h3>Unauthorized</h3>`

Quasi-related: I'm trying to get cockpit running as a pod, and it works, but no combination of credentials from /srv/kubernetes/basic_auth.csv or ~/.kube/config work with it's login page.

**Comment by Ademord** [comment]
I'm having the same issue (win10). Did anyone find a workaround?

**Comment by sivadatla** [comment]
I too faced the exact issue mentioned  - 
[here](https://github.com/kubernetes/kubernetes/issues/23727#issuecomment-252823272)

I could see dashboard by passing the following header:
`Authorization Bearer iUeq9ps8BSRs8JodL1gzbRmBYCWOmIOM`
For this I have to install modHeader plugin to Chrome to keep the above mentioned header before hitting the following URL
[https://github.com/kubernetes/kubernetes/issues/23727#issuecomment-252823272](https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard)
