### ISSUE TITLE
flexVolumes pass only one part of a secret to the plugin

### ISSUE THREAD

**Issue by rrayst** [kubernetes/kubernetes#23728]
https://github.com/kubernetes/kubernetes/blob/master/docs/design/secrets.md#use-case-pod-with-ssh-keys describes how the two parts of an SSH key (the id_rsa and id_rsa.pub file) can be stored within one secret (using `kubectl create secret generic my-secret --from-file=ssh-privatekey=id_rsa --from-file=ssh-publickey=id_rsa.pub`).

Setting up a flexVolume as shown below only passes one of the parts on the mount script (which part is passed, seems random).

```
  volumes:
  - name: test
    flexVolume:
      driver: "my/sshfs"
      secretRef:
        name: "my-secret"
```

(The mount script is called with the parameters `mount <mountpoint> {"kubernetes.io/fsType":"","kubernetes.io/readwrite":"rw","kubernetes.io/secret":"<part>"}` where `<part>` is sometimes the content of `id_rsa` and at other times the content of `id_rsa.pub`.)

--

This issue is https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/flexvolume/flexvolume.go#L118, where the last piece listed wins.

fa76de79e5d1670b8e6add30f0159c833534a298 copied the code over from cephfs (and rbd), where SSH keys seem not to be used for authentication.

**Comment by nelcy** [comment]
I am taking a look at this one.

**Comment by nelcy** [comment]
Add support for multiple secrets in PR: #23862 

@saad-ali When you get a chance, please add labels for this issue & PR. Thanks.

**Comment by nelcy** [comment]
The fix is merged. The secrets are passed as options to the flex volume in the following format.
``` 
kubernetes.io/secrets/<secret-key>=<base64 encoded secret-value>
```
