### ISSUE TITLE
decouple conformance from examples/ directory.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#23735]
Problem:

Running `[Conformance]` tests forces dependencies on several ad-hoc directories in the kuberenetes repo tree.  Core kubectl functionality should be ascertainable in a simple manner, maybe just a python or busybox container with inline RCs/Pods.

Possible Solutions:

1. inline strings  written to files just-in-time
2. sent via pipe
3. use `go generate` to embed required files in the binary

If the third solution works, that would be a elegant solution IMO which would allow examples to co-evolve with release artifacts with minimal changes to `test/e2e/kubectl.go`

... 
I'll eval this afternoon i think (3) would be very elegant.  Other opinions on 1/2/3 ?

**Comment by jayunit100** [comment]
@kubernetes/sig-testing @timothysc

**Comment by jayunit100** [comment]
concretely: 
- should create and stop a replication controller (docs/user-guide/update-demo)
- rolling update
- create and stop working application (examples/guestbook)
- should check if kubectl describe prints (examples/guestbook-go)
- should update the label (docs/user-guide/pod.yaml)
...

**Comment by timothysc** [comment]
+1000 a binary output should not depend on its source repository

**Comment by spiffxp** [comment]
Not entirely disagreeing, but FWIW it's possible to run these without the source repo.  There's a test tarball built by CI that's not linked on the github releases page, maybe it should be?

https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L965-L993

**Comment by jayunit100** [comment]
Yeah, some kind of embedding even if the tarball into the dist would be ok , as long as it's not an external juggled thing

**Comment by spiffxp** [comment]
Took v1.3.5 release of kubernetes.  Expanded `kubernetes-{,test}.tar.gz`, removed `docs` and `examples`, and tried giving conformance a go per https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#conformance-tests

All of the aforementioned tests passed, but there was one new failure: `[k8s.io] ClusterDns [Feature:Example] should create pod that uses dns [Conformance]`

It's not happy with the lack of `examples/cluster-dns/dns-backend-rc.yaml`

**Comment by timothysc** [comment]
I think the gobindata finished this iirc... 

closing
