### ISSUE TITLE
kubectl: Error from server: No SSH tunnels currently open.

### ISSUE THREAD

**Issue by ScyDev** [kubernetes/kubernetes#23737]
Experiencing this right now:

```
$ kubectl attach mongo-controller-xxxxx
Error from server: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-xxxxxxxxxxxxxxxxxxxx"?
```

What is this caused by?

**Comment by Blasterdick** [comment]
+1, Sometimes getting this, while making command:

`for name in `kubectl get pod |awk '/redis/{print $1}'`; do echo $name && kubectl exec $name redis-cli keys "*"; done`

from every server in RC. But, next time it could be OK.
