### ISSUE TITLE
Intent of namespaces

### ISSUE THREAD

**Issue by huggsboson** [kubernetes/kubernetes#23738]
We run an application that is composed of ~100 connected services, from a compliance perspective we would love to restrict kubectl exec/logs to pods for which a team is responsible. Currently the most effective way of isolating and enforcing access control over these services and pods would be to create a namespace per service and its related-pods and using ABAC or the upcoming openshift policies.  But it feels like an abuse of the namespace mechanism, and I worry that this usage will come into conflict with future improvements around access control and namespaces.

The options at current feel like:
1. Create ~100 namespaces per cluster each containing ~1 service, ~deployment, n pods and use ABAC to restrict access to certain ops using those namespaces.
2. Have 1-3 namespaces (dev, staging, prod) and extend/fork the ABAC policies to support rules on pod labels within a single namespace. 

We basically need the access control parts of namespaces without the name-isolation parts.  In fact a lot of people would love to have the connected services located in the same namespace.  To take advantage of the DNS shortening simplifications.

@derekwaynecarr @erictune

**Comment by derekwaynecarr** [comment]
A few questions that may help steer us to a good outcome:

1. Is exec/log output of a pod associated with a team your only concern?
2. Is it not a concern that those teams can modify/view secrets that are consumed by those pods?
3. Is it not a concern that those teams can modify/view service accounts that are consumed by those pods?
4. Is it not a concern that those teams can modify replica sets, daemon sets, deployments from which those pods were derived?
5. Do teams have different compute budgets?  For example team A can have X CPU but team B can have Y?

Does each teams pods go through a separate dev/staging/prod scenario with different user rights?

**Comment by huggsboson** [comment]
Thank you for the quick reply, with such thoughtful questions.

1. Probably not, it is just the most visible at this moment.  Other examples I can think of is network reachability between service foo and service bar.  If they don't need to talk to each other then they probably shouldn't be allowed to.  This can be enforced using an authZ mechanism like mutual auth TLS, but most compliance asks want some level of network isolation too.
2.  This is a good point.  We probably do only want secrets to be isolated to only the services that need it.
3. We aren't leveraging service accounts very much today except for in services that we treat as part of the cluster (service loadbalancers) and they live in kube-system.  So the serviceAccounts in both (dev, staging, live) and (foo, bar) worlds will have no real api access.
4. That is a concern that I should have mentioned in the original, but it largely seemed like any mechanism we chose to restrict exec/logs could also be used to restrict this type of visibility/mutability.
5. Not at the moment, but this is definitely a future concern.

A service team usually has more rights in dev/staging than it does in prod.

**Comment by huggsboson** [comment]
A couple of quick questions, while I have you:
1. I wasn't sure if the intent of namespaces going forward would be for hosted kube providers (like openshift) to use namespaces to isolate multiple companies from each other which feels like it will require much stronger walls (harder lines separation in service discovery) than those used between multiple service teams at the same company where the services want to communicate with each other on a regular and lightweight basis.
2. If I do a service per namespace the naming itself gets kind of odd.  So if I run service foo, create a "foo" namespace with a "main" service provisioned in there?  So the dns would be main.foo.cluster.local, as opposed to foo.dev.cluster.local).

**Comment by huggsboson** [comment]
The overall point I'm getting at is that namespaces seems like the hammer and name collision, access control, relative service disco and resource limits all seem to be getting hung off of it instead of offering multiple orthogonal mechanisms for it.

**Comment by huggsboson** [comment]
Another mis-alignment for our use-case is that without a cluster DNS solution kubernetes service discovery won't work with a namespace per service model.   As in if we rely on env vars to get injected to discover the vips and service foo needs to talk to service bar (though they are owned by different teams) service foo won't know service bar's vip because you only get the env vars for services which occupy your namespace.

**Comment by derekwaynecarr** [comment]
I had to leave office early today, but will pick up this discussion more on
Monday.

**Comment by huggsboson** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
Regarding DNS, I think the assumption is that everyone would use cluster DNS (or in general we want it to be felt like a normal part of the cluster) and that VIPs and ENV vars are things that should be less important than they are (put another way, naming is better than VIPs).  However, there are a number of challenges with names (end to end TLS) if they aren't absolute, so this has definitely been a struggle.  Ultimately, if you need name indirection you'll need to bring in another layer of complexity - we've discussed adding name indirection to services via DNS, and there are the higher levels of naming like Eureka and finagle that should have *some* integration with the cluster.  I would hope that we can find ways to make that multi-level story feel as painless as possible.

Agree regarding orthogonality - we find that there is a tradeoff between easy comprehension (a namespace is a bucket for stuff with policy attached) and separating concerns (I want auth to behave this way for these resources and this way for other resources but only when in these clusters, etc).  We *want* to use labels on namespaces to apply policy, but we lack many of the descriptors required for that today.  So quota on a label selector of buckets, or limit ranges applied to the buckets by policy, or access control applied in bulk via label, but those are all much further out.

Regarding what to use namespaces for... the "right-now" answer is "use a namespace to group a set of related things, people, or limits".  The hard answer is "how do you set up and maintain those in bulk".  I suspect most people doing service oriented stuff would have namespaces that clearly correlate to service + environment (prod, dev) and also to team.  From an naming perspective, that might mean service "api", namespace "account-prod", with two teams with rights on that namespace - account team devs, and ops team.  If a team maintains many services, the namespace might be the group name "infrastructure-prod".  

Note today in DNS you can do `servicename.namespace.svc` if you want a shorter name.

And to your initial question, applying ABAC based on labels is possible, but comes with a lot of complexity.  We've considered it from a lot of angles, but it is just hard enough that it doesn't clearly justify itself against using the "role per namespace" bucketing. You have to control who can set labels, who can query labels, enforce ACL filtering on label queries, and the mechanism that does those checks has to be able to read the body of every object going through the system.  It would be powerful... but also complex.

**Comment by huggsboson** [comment]
Thank you for your very useful response!

**Comment by huggsboson** [comment]
Just to add a little more color.

DNS: I hadn't thought through the fact that non-absolute names on TLS.  So we should be using FQDN's (even if they are cluster levels most everywhere to make TLS SAN's "easier" i.e. more compact and easier to reason about at generation time).

If we pursue, which we are likely to, the namespace per service-ish model I agree that namespace labels and auth/limits/ based on those labels will make management a whole heck-of-a-lot-easier.  Is it being considered for 1.3 or any milestone after that?  We can make due until then, but it will add some friction (maybe in the interim we can make apiservers dynamically pick up changes to policy.jsonl files) to at least make the tooling a little more automated.

I hadn't really considered labels on namespaces so I'm pretty happy to let go of label based ABAC.

**Comment by huggsboson** [comment]
One question I assumed VIPs + cluster DNS as opposed to VIPs + env vars was the path forward, but it sounds like you're considering a different path for naming.

**Comment by smarterclayton** [comment]
Sorry, just meant to imply cluster DNS instead of using VIPs.  Since
names have to match for non-proxied TLS we might offer "easy CNAME"
via services that point to other services, but client code would have
to chase the CNAME to get the right target name.

**Comment by ghodss** [comment]
Just to clarify, the cluster DNS name that points to a service does eventually always resolve to a VIP, right? With VIP referring to the IPtables-routed virtual IP's managed by kube-proxy. And you're just saying don't use the VIP to connect directly, use a cluster DNS name that resolves to that VIP.

**Comment by smarterclayton** [comment]
Correct.  We've discussed having the env vars point to the DNS name as
well as future options with DNS to do region aware VIPs.
