### ISSUE TITLE
hack/update-codecgen.sh not working

### ISSUE THREAD

**Issue by goltermann** [kubernetes/kubernetes#23749]
I had a change where I needed to run this command.  It appears to be generating the .tmp files just fine, but the mv "${base_generated_file}.tmp" "${base_generated_file}" must be silently failing.  After the script is run, my folder has both a types.generated.go and types.generated.go.tmp.  If I just do the mv myself, everything works, so the .tmp file has the right updates.

Also, while we're in there, the year 2015 is hardcoded.  We should parse the output of "date" or something like that.

**Comment by lavalamp** [comment]
@goltermann is this still happening to you?

**Comment by goltermann** [comment]
I don't see it now, so I suspect it got fixed along the way.  Closing.
