### ISSUE TITLE
kubelet will never terminate a pod if image registry is unavailable for a pod container

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#23742]
After an unbelievable amount of time debugging the following this past week:

https://github.com/kubernetes/kubernetes/issues/22045
https://github.com/openshift/origin/issues/8176

I discovered that I could reliably cause the `kubelet` to never delete a pod that was `Terminating` if the pod had never been started correctly because the docker image pull returned a `RegistryUnavailable` error.

I verified this by modifying the kubelet to always return `RegistryUnavailable` for a particular image name.  I then created a namespace, added a replication controller that referenced the image, and then watched as the pods got stuck in "Waiting" state but never actually reported a reason.  I then deleted the namespace, and was able to see that in-fact the `kubelet` never properly handled the `terminated` response.

I was able to fix this issue by modifying:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/serialized_image_puller.go#L124

to return `ErrImagePull` when the repository was not available.  This change resulted in letting my `kubelet` properly terminate the pod.  I think this is the correct behavior to not special case `RegistryUnavailable` since in many cases the registry may never become available (its most definitely not a temporary situation).

I suspect this is the potential source of a number of instances of the namespace failed to delete flake because pods remained.

/cc @kubernetes/sig-node @vishh @dchen1107 @yujuhong @kubernetes/rh-cluster-infra

**Comment by ncdc** [comment]
+1 to not special casing RegistryUnavailable errors as treating them instead as normal ErrImagePull errors

**Comment by ncdc** [comment]
cc @kubernetes/sig-node @kubernetes/rh-cluster-infra @timothysc @jeremyeder

**Comment by derekwaynecarr** [comment]
We can also look to handle RegistryUnavailable here if we want to continue to distinguish:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L3382

**Comment by derekwaynecarr** [comment]
ok, properly handling RegistryUnavailable in the above code block fixes everything.  will go that route.

**Comment by Random-Liu** [comment]
This is related to #21125.

**Comment by derekwaynecarr** [comment]
sending a PR now and going on a long vacation ;-)

**Comment by Random-Liu** [comment]
My theory is that:
1) The container is never created because it failed to pull image [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1925)
2) The container never existed in the runtime, so the `containerStatus` was never set and kept as "no state"[here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L3402)
3) Then the container was treated as "Unkown" and the pod was reported as `Pending` without any reason [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L3246)
4) The `containerStatus` was always "no state", the status manager could never delete the pod even though the timestamp was set [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/manager.go#L395)

**Comment by derekwaynecarr** [comment]
@Random-Liu - and now you understand why 

a) it was hard to reproduce since it required docker to randomly flake on getting latest of hub image
b) the 4 pts above are crazy non-obvious ;-)

**Comment by Random-Liu** [comment]
@derekwaynecarr Yeah, thanks so much for reproducing this!!

**Comment by yujuhong** [comment]
> 2) The container never existed in the runtime, and the error reason is not in the "special error list", so the containerStatus was never set and kept as "no state" here

I think this is they key -- the container should default to some non-running state (e.g., waiting) in this case.

> 4) The containerStatus was always "no state" after each syncPod(), the status manager could never delete the pod even though the timestamp was set here

With a default container state, the status manager should be able to delete the pod.


> @Random-Liu - and now you understand why
> 
> a) it was hard to reproduce since it required docker to randomly flake on getting latest of hub image
> b) the 4 pts above are crazy non-obvious ;-)

@derekwaynecarr, Thanks for finding the culprit.

**Comment by Random-Liu** [comment]
@yujuhong If we set it to `Waiting` by default, while the container should never be restarted again, then we may fall into another trap. :) We should still set the state based on the restart policy.

**Comment by yujuhong** [comment]
> @yujuhong If we set it to Waiting by default, while the container should never be restarted again, then we may fall into another trap. :) We should still set the state based on the restart policy.

"waiting" == no container is running. If there is no dead or alive containers associated with this name, why shouldn't the container stay in the waiting state?

**Comment by Random-Liu** [comment]
Offline discussed with @yujuhong , we decided to continue with #21224 for now. :)
