### ISSUE TITLE
regarding abac & groups while using client cert mixed with token based authentication

### ISSUE THREAD

**Issue by jowy** [kubernetes/kubernetes#23745]
As far as I can tell, there's currently no way to define or authorize joined groups of a username that's been authenticated via CN of a valid cert. I've defined tokens for these users which have been set along with the certs in their kubeconfig. These users can now authenticate with one or the other, but not both. The issue is using ABAC policy: when a client is authenticated using a cert, I'm only able to authorize against the username, there's no group to authorize even if the same username is defined in the tokens file. The user's groups seem to only be associated when the user is authenticated against a token.

Possible solutions:

* Defining a users groups just within the ABAC authorization plugin?
* Simply use both authentiaction mechanisms, if available.
* I may be overlooking something here, but it seems that there should be some kind of talk between these two authentication systems or at least some kind of common database or file defining the these users and their groups.

With my k8s setup, the preferred method of external authentication would be using certs, but with a more complex policy, it can become difficult to manage a policy block for individual users rather than a single group.

**Comment by liggitt** [comment]
Correct, groups defined in the CSV token file only apply to token auth. Relevant discussion in https://github.com/kubernetes/kubernetes/issues/23720

**Comment by jowy** [comment]
Ah thanks, sorry I did look around for this first :P Please close.
