### ISSUE TITLE
Jenkins can create CI versions that release scripts don't like

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#23759]
On the `release-1.2` build today, the builds started failing due to the version not matching required regular expressions.

The last passing build had version `v1.2.1-beta.0.42+60bda7b53ec344-dirty`.
Then the release version updated, making the next build have version `v1.2.2-beta.0-dirty`, and this failed:
```
!!! [0401 11:18:38] Invalid ci version: 'v1.2.2-beta.0-dirty', must match regex ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)-(beta|alpha)\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)\+[-0-9a-z]*)?$
```

It looks like the previous version worked because the `+[sha1]` part allowed the `-dirty` tag at the end to match. Without that sha1 appended, the `-` in `-dirty` was now disallowed.

I'm not familiar enough with our versioning scheme to know if the version generated is incorrect, or if the regex matching it is incorrect. (My personal opinion is that `-dirty` builds should always fail on Jenkins, though that's an aside.)

cc @kubernetes/goog-testing @david-mcmahon @ihmccreery

**Comment by david-mcmahon** [comment]
if #23757 happens, we can certainly change the regex to be more restrictive.
I can only assume -dirty was specifically allowed before because #23757 wasn't there to stop it? @ihmccreery

**Comment by ihmccreery** [comment]
`-dirty` builds are considered valid versions, but probably shouldn't be considered valid CI versions, so I like @david-mcmahon's change.
