### ISSUE TITLE
Kubernetes scheduler doesn't support N+1 fault tolerance in the presence of automated shutdowns and restarts of VMs

### ISSUE THREAD

**Issue by eddytruyen** [kubernetes/kubernetes#23758]
I experienced that the kubernetes scheduler doesn't redistribute pods of a service across multiple nodes after suspended or shutdown VMs come back on-line. This isn't a problem with clusters with high number of nodes but in small clusters with 2 or 3 nodes, it is a problem in the sense that N+1 fault tolerance is not guaranteed for services. I was able to arrive at situation where all pods of a service are placed on the same node, and there is no timeout handler that triggers the scheduler to relocate the pods. 

I have experienced the same scheduler behavior with Juju as Kubernetes Provider and also in Google Container Engine. In the latter environment, GKE shutdowns the single node were all pods of a service were located, leading to temporary unavailability of the service.

Below you find my findings in Juju and GKE
## Juju

I have an openstack environment with 3 kubernetes units, and a redis service deployed with 4 replicated pods

```
ubuntu@juju-openstack-machine-5:~$ kubectl get nodes
NAME            LABELS                                 STATUS    AGE
172.17.13.141   kubernetes.io/hostname=172.17.13.141   Ready     1d
172.17.13.144   kubernetes.io/hostname=172.17.13.144   Ready     1d
172.17.13.145   kubernetes.io/hostname=172.17.13.145   Ready     1d

ubuntu@juju-openstack-machine-5:~$ kubectl get services
NAME          CLUSTER_IP    EXTERNAL_IP   PORT(S)     SELECTOR                            AGE
kubernetes    10.1.0.1      <none>        443/TCP     <none>                              1d
redis-slave   10.1.2.166    <none>        6379/TCP    app=redis,role=slave,tier=backend   1d

ubuntu@juju-openstack-machine-5:~$ kubectl get rc
CONTROLLER    CONTAINER(S)   IMAGE(S)                                 SELECTOR                            REPLICAS   AGE
redis-slave   slave          gcr.io/google_samples/gb-redisslave:v1   app=redis,role=slave,tier=backend   4          1d
```

First when I suspend 2 machines in my openstack dashboard, all pods are placed on the remaining machine after a timeout of 5 minutes..

Then, when I resume the two suspended machines in my openstack dashboard,  the pods are not replicated across different machines to ensure fault tolerance of services
I thought the specification of scheduling entails that when you create a service and thereafter a replicacontroller, pods should always be placed on different machines if that is possible However, this behavior does not occur. Below you find some command output for the redis-slave service which have 4 replicated pods.  It shows that all 4 pods are placed on the same machine.

```
ubuntu@juju-openstack-machine-5:~$ kubectl describe pod -l app=redis | grep Node
Node:                           172.17.13.144/172.17.13.144
Node:                           172.17.13.144/172.17.13.144
Node:                           172.17.13.144/172.17.13.144
Node:                           172.17.13.144/172.17.13.144
```
## GKE

I found out that the reported behavior of Kubernetes Juju bundle also appears in Google Container Engine. See attached RAW file.

Below I describe the findings

This was my initial desired state:

```
[centos@public-kubernetes-gw ~]$ kubectl get nodes
NAME                               STATUS    AGE
gke-cluster-1-09071288-node-7mmj   Ready     1m
gke-cluster-1-09071288-node-buym   Ready     1m
gke-cluster-1-09071288-node-demf   Ready     1m
[centos@public-kubernetes-gw ~]$ kubectl run nginx --image nginx --port=80
deployment "nginx" created
[centos@public-kubernetes-gw ~]$ kubectl describe pods -l run | grep Node
Node:           gke-cluster-1-09071288-node-7mmj/10.128.0.2
[centos@public-kubernetes-gw ~]$ kubectl scale deployment nginx --replicas=0
deployment "nginx" scaled
[centos@public-kubernetes-gw ~]$ kubectl expose deployment nginx
service "nginx" exposed
[centos@public-kubernetes-gw ~]$ kubectl scale deployment nginx --replicas=3
deployment "nginx" scaled
[centos@public-kubernetes-gw ~]$ kubectl describe pods -l run | grep Node
Node:           gke-cluster-1-09071288-node-7mmj/10.128.0.2
Node:           gke-cluster-1-09071288-node-demf/10.128.0.4
Node:           gke-cluster-1-09071288-node-buym/10.128.0.3
```

Then I suspended 2 machines via the google cloud engine dashboard. These machines were automatically restarted by google container engine

At a certain moment I reached the following state:

```
[centos@public-kubernetes-gw ~]$ kubectl get nodes
NAME                               STATUS    AGE
gke-cluster-1-09071288-node-7mmj   Ready     1m
gke-cluster-1-09071288-node-buym   Ready     4m
gke-cluster-1-09071288-node-demf   Ready     22m
[centos@public-kubernetes-gw ~]$ kubectl describe pods -l run | grep Node:
Node:           gke-cluster-1-09071288-node-demf/10.128.0.4
Node:           gke-cluster-1-09071288-node-demf/10.128.0.4
Node:           gke-cluster-1-09071288-node-demf/10.128.0.4
```

Then google container engine's behavior diverted from the kubernetes-core bundle. In fact google container engine did something very surprising: It suspended the machine where all 3 replicas were placed:

```
[centos@public-kubernetes-gw ~]$ kubectl get nodes
NAME                               STATUS     AGE
gke-cluster-1-09071288-node-7mmj   Ready      5m
gke-cluster-1-09071288-node-buym   Ready      8m
gke-cluster-1-09071288-node-demf   NotReady   26m
[centos@public-kubernetes-gw ~]$ kubectl describe pods -l run | grep Node:
Node:           gke-cluster-1-09071288-node-demf/10.128.0.4
Node:           gke-cluster-1-09071288-node-demf/10.128.0.4
Node:           gke-cluster-1-09071288-node-demf/10.128.0.4
```

At this point the nginx service was unavailable:

```
[centos@public-kubernetes-gw ~]$ kubectl describe pods -l run | grep IP:
IP:
IP:
IP:
```

I think google container engine suspended 10.128.0.4 in order to trigger the replication controller (aka deployment manager) to redistribute the pods. Indeed after some time 

```
[centos@public-kubernetes-gw ~]$ kubectl describe pods -l run | grep IP:
IP:             10.0.1.2
IP:             10.0.1.3
IP:             10.0.0.4
[centos@public-kubernetes-gw ~]$ kubectl describe pods -l run | grep Node:
Node:           gke-cluster-1-09071288-node-7mmj/10.128.0.2
Node:           gke-cluster-1-09071288-node-7mmj/10.128.0.2
Node:           gke-cluster-1-09071288-node-buym/10.128.0.3
[centos@public-kubernetes-gw ~]$ kubectl get nodes
NAME                               STATUS     AGE
gke-cluster-1-09071288-node-7mmj   Ready      10m
gke-cluster-1-09071288-node-buym   Ready      13m
gke-cluster-1-09071288-node-demf   NotReady   31m
```
## Summary

I think there is an issue with Kubernetes. I had a look at how the scheduler of kubernetes is designed It is policy-configurable and extensible. 

The default policy of the scheduler corresponds with the policy below. As you can see, the scheduler policy would definitively change the situation where all pods of a service run a single node and the other nodes are idle. 
So the question is: why is the scheduler never invoked to change that situation in the Kubernetes-core bundle? 

In Google Container Engine scenario, a too drastic approach is taken to trigger the scheduler: Shutting down that single node in order to let the scheduler become active. 

```
{
    "kind" : "Policy",
    "version" : "v1",
    "predicates" : [
        {"name" : "PodFitsPorts"},
        {"name" : "PodFitsResources"},
        {"name" : "NoDiskConflict"},
        {"name" : "MatchNodeSelector"},
        {"name" : "HostName"}
    ],
    "priorities" : [
        {"name" : "LeastRequestedPriority", "weight" : 1},
        {"name" : "BalancedResourceAllocation", "weight" : 1},
        {"name" : "ServiceSpreadingPriority", "weight" : 1}
    ]
}
```

[googlecontainerengine.txt](https://github.com/kubernetes/kubernetes/files/200250/googlecontainerengine.txt)

**Comment by herry13** [comment]
@eddytruyen If you check Pod's lifecycle (http://kubernetes.io/docs/user-guide/pod-states/), you'll notice that there is no state that describes whether the pod violates the policy or not. Probably this is the reason why the schedule doesn't re-schedule the containers to re-distribute them.

One of the solutions for this problem may require an update on the Pod's lifecycle by adding a state that represents the pod is violating the policy. This state can be set by the Pod Probe. Any pod that is in this state should be re-scheduled by (gracefully) shutting down some containers and redistributing them.

**Comment by eddytruyen** [comment]
@herry13  your proposal seems like an interesting solution in theory for a single pod, but according to the conceptual architecture of Kubernetes, all containers of a single pod are meant to be co-located on the same node as they share the same fate. A pod is a single unit of failure.  

I am referring to the situation of multiple pods: A set of pod replica's, behind a replication controller, and exposed as a service. 
The issue is that, in small clusters, say a 3 node cluster, after 2 shutdowns of nodes,  the set of replicated pods is driven to a permanent undesirable states: all pods are placed on the same node and remain on that node even after the 2 shutdown nodes come up again. 

There are multiple ways to migitate this issue:
- Ideal solution IMHO : let kubernetes reschedule automatically: what's the additional complexity of that?
- Similar to your proposal: users specify nodeSelector properties of Pod carefully to prevent going into that undesirable state
- Autoscale approach: scale down the replicacontroller and scale up again
- Google Container Engine's approach: shutdown the node with the undesirable state

**Comment by eddytruyen** [comment]
I found another way to migitate this issue: assign to a container within the pod a `hostPort`.
See https://github.com/kubernetes/kubernetes/wiki/User-FAQ#how-can-i-ensure-that-at-most-one-of-my-pods-is-scheduled-on-each-node.

This implies that 2 replica's of a pod cannot be assigned to the same node by the scheduler.

In this way, pods get always placed on a different node. When nodes shutdown, some pods may not get scheduled when the number of total `Ready` nodes is less than the number of desired replicas of the pod. When nodes come back up, additional pods are immediately started across different nodes in order to increase the number of replicas of the pod to the desired state.

Pro/Contra analysis of this solution:

- Pro:
  - Easy and automated solution that solves the issue. 
  - You need to manage a centralized bookkeeping of host ports which can be allocated for this purpose. As this issue only affects clusters with a few number of nodes, there are various simple ways to implement such centralized bookkeeping cost-effectively and reliably.     
- Contra:
  - After nodes shutdown, the observed pod replicas of the service are less than the desired pod replicas. If Pods have associated resource requests with quality-class Guaranteed, the quality-class is violated

**Comment by quinton-hoole** [comment]
Plan to address this requirement with a rescheduler. 
https://github.com/kubernetes/kubernetes/issues/12140

**Comment by timothysc** [comment]
@jayunit100 rescheduler problem, enqueue for interleave on 1.6, or 1.7-ish.

**Comment by bsalamat** [comment]
This issue seems to be old and out-dated. Scheduler does perform spreading of ReplicaSets and StatefulSets by default. It also support inter-pod anti-affinity which ensures distribution of pods across multiple nodes, zones, etc.

/close
