### ISSUE TITLE
kubectl "overcommited" warning points to source code, not docs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23778]
In kubectl describe nodes:

```
Allocated resources:
  (Total limits may be over 100%, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests  CPU Limits      Memory Requests Memory Limits
```

The link http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md points to the code (it should not), and then another redirect, and finally http://kubernetes.io/docs/user-guide/compute-resources/

Also, the word "over" (as in overcommitment) only appears once on that page, in the "planned features" section, so even the final destination is not a great link...

**Comment by bgrant0607** [comment]
cc @vishh @erictune

**Comment by vishh** [comment]
I can fix this! cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
I actually think we should remove the more info link altogether and just
say total limits may exceed 100% because the scheduler schedules to
requests.
