### ISSUE TITLE
ELASTICSEARCH_LOGGING_REPLICAS is off-by-one ?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23780]
On AWS (and I think GCE), when ELASTICSEARCH_LOGGING_REPLICAS=1, two elasticsearch pods get deployed by kube-up.  Is it off-by-one?

**Comment by saad-ali** [comment]
CC @freehan

**Comment by freehan** [comment]
The ES replicas is defined here: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/es-controller.yaml#L11

Not sure what is up with `ELASTICSEARCH_LOGGING_REPLICAS`
