### ISSUE TITLE
kube-dns should always be scheduled

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23781]
We need some notion of pod priority or a critical pod - a user had a cluster with insufficient capacity, and kube-dns was not scheduled due to insufficient resources, so the cluster was not functional.

**Comment by therc** [comment]
Borg has priorities: monitoring, production, batch and best effort, in that order. But that's also reflected in quotas.

**Comment by thockin** [comment]
It's a very slippery slope to introduce priorities.  Now you have to quota those priorities, have a concept of eviction and rescheduling, have SLAs around eviction, etc.  It's not that priority is inherently a bad idea, but it's not as simple as adding an int field :)

Agree that the DNS thing is pretty bad.  The real problem, IMO is that the cluster was too full.  You MUST leave some amount of capacity in a cluster for things to move, or else you get gridlocked.  An internal bug was started on this but there's no reason for it to be internal (old habits die hard).

@davidopp @alex-mohr @mml

**Comment by davidopp** [comment]
I think we do want priorities and preemption, as long as we can do it in a way that it does not add complexity for users who do not care about it. There's a design proposal up at
https://github.com/kubernetes/kubernetes/pull/22217
which is still open for comment. As a coincidence, it discusses all of the issues @thockin mentioned. :)

But it doesn't obviate the need to do what @thockin mentioned above. People who are trying to use a machine to 100% capacity is going to be in for a bad time regardless. We need to create a reasonable policy/documentation around this.

ref/ #23556 (the issue @justinsb is referring to)

**Comment by dchen1107** [comment]
@thockin I filed an issue related to this too: https://github.com/kubernetes/kubernetes/issues/22212

**Comment by thockin** [comment]
Dup of #22212
