### ISSUE TITLE
AWS: Need a better approach to instance storage & EBS

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23787]
In #23776 I created a hacky but cherry-pickable approach to letting users _not_ use instance storage, e.g. on the m3.medium the instance storage is only 4GB and that's a little small for some people.

#23776 does this though by not mounting any ephemeral volumes.  It would be nice to have a way to keep the (free) ephemeral volumes available, while also using EBS for instance storage.

Likely something TODO as part of kube-up v2.

**Comment by roberthbailey** [comment]
@justinsb If this is going to be part of kube-up v2 should we create an issue in the kube-deplo repo and close this? Even if not, I think we should remove it from the 1.3 milestone.

**Comment by goltermann** [comment]
Removing v1.3 milestone, this won't be in on that timeline.

**Comment by justinsb** [comment]
Thank you for moving to next-candidate.  I think we're doing this work in kube-deploy.  I opened https://github.com/kubernetes/kube-deploy/issues/118, so I'm going to close this one.
