### ISSUE TITLE
Support vitess in PetSet

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#23792]
Use of PetSets with Vitess

Spawned from #18016 
- https://github.com/kubernetes/kubernetes/tree/master/examples/vitess
- http://vitess.io/getting-started/

Vitess has three component tiers - tablets (data layer), vctld (admin tier), and gates (client proxies).  Tablets are singleton instances that must be durable - each tablet contains a portion of the keyspace.  Gates are stateless and best implemented with a replicaset/deployment.  ctld is also stateless (?) and can be implemented with a replicaset/deployment (verify this).

Each tablet is a pet, named based on the keyset it serves and the shard and keyspace it belongs to.  Each tablet may also have a type.  A representation of the template for the tablet is here: https://github.com/kubernetes/kubernetes/blob/master/examples/vitess/vttablet-pod-template.yaml and the script that generates the tablets is here: https://github.com/kubernetes/kubernetes/blob/master/examples/vitess/vttablet-up.sh
#### Initialization
1. Start the gates and vctld instances 
2. Decide number and count of shards, distribution of types
3. Create all the tablets for the distribution
4. Wait for the tablets to show up in the topology

Dynamic reconfiguration involves making calls to the vctld and then materializing the tablets.
#### Upgrade (TODO)

There appear to be two main types of update - blue/green shard (migrate from one to another) or rolling update on a shard via promotion.  Migration would involve a new shard being stood up and using vctld to shift transactions to the new shard, and rolling update would involve updating replicas and then having the master step down the new replica being promoted (as well as other members of the set.
#### Reconfiguration (TODO)

Requires commands to be invoked on the vctld instances for reconfiguration to take effect.  A babysitter / config change pod _could_ invoke those commands, although it's likely most migrations will be directed by admins and not automated for other reasons.
#### Thoughts on vitess

Tablets and how they are constructed for keyspaces, shards, and types demonstrate a multi-dimensional instance template, where a few key variables are expanded into instances that vary based on a few parameters.  Vitess could succinctly be represented by a single petset with a set of member spans (or nested spans) that represent the different scaling dimensions, and then parameterized the resulting pod name and environment variables with a few parameter instances (keyspace, tablet-type).  

It is likely that certain parameters would differ by template such as CPU, memory, or disk size.  Read-only tablet types might have slightly different resource requirements than masters or replicas.  The other tablet types may be divergent enough that they do not fit into the petset, but should be represented as additional sets.

**Comment by enisoc** [comment]
Thanks for writing this up! I'll try to add some thoughts from the Vitess side:

> Gates are stateless and best implemented with a replicaset/deployment. ctld is also stateless (?) and can be implemented with a replicaset/deployment (verify this).

Agreed. I plan to make vtgate and vtctld use Deployments once I get used to this new feature.

> Dynamic reconfiguration involves making calls to the vctld and then materializing the tablets.

For creation of a new keyspace/shard, or adding more replica tablets to an existing shard, materializing the tablets themselves is actually enough. They will self-register from there. Down-sizing also doesn't necessarily require any admin calls (you can just stop the tablet pods); some cruft may be left behind in our etcd store, but we have plans to get rid of that.

> Migration would involve a new shard being stood up and using vctld to shift transactions to the new shard

As you mention, we do envision this being directed by an admin, not automated through k8s.

> rolling update would involve updating replicas and then having the master step down the new replica being promoted

In Borg, our update automation system does something like this (on a per-shard basis):
1. Update non-master tablets first.
2. Promote one of the updated tablets to be the new master (by calling into vtctld).
3. Update old master tablet.
Upon updating each tablet, it waits for it to report healthy before moving on.

There are other ways of doing it, but this is what we've found results in the least downtime during rollouts. I'll need to learn more about Deployments to see what makes sense in k8s.

> Tablets and how they are constructed for keyspaces, shards, and types demonstrate a multi-dimensional instance template

That's interesting; I never thought about having a single PetSet represent multiple shards or keyspaces before. In Borg we have a separate Job for each (zone, keyspace, shard, tablet type) tuple. The update automation system takes care of per-Job operations. If PetSet can handle multiple dimensions like that, it would eliminate the need for a separate update automation system, which would be great.

**Comment by enisoc** [comment]
StatefulSet works for Vitess: https://github.com/youtube/vitess/tree/master/helm/vitess
