### ISSUE TITLE
GroupVersion not present in src

### ISSUE THREAD

**Issue by microadam** [kubernetes/kubernetes#23799]
I have been having the kube-controller-manager (running in a container) crash quite frequently with this error:

```
F0403 14:47:52.372732       1 controllermanager.go:277] Failed to get supported resources from server: converting (unversioned.APIGroupList) to (unversioned.APIResourceList): GroupVersion not present in src
```

I cant fathom what seems to cause it. It seems to happen consistently for a while (CrashLoopBackoff occurs) and then fixes itself after an undetermined amount of time.

Kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
```

Docker version:

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
OS Version: Ubuntu 16.04
```

Networking: Calico (with the calico k8s policy agent)

Please do let me know if there is any other information that I can supply. I appreciate I haven't given much to go off of. I am not sure what the steps to reproduce are...

**Comment by bgrant0607** [comment]
cc @lavalamp @caesarxuchao

**Comment by caesarxuchao** [comment]
It looks like a bug. I'll take a look.

**Comment by lavalamp** [comment]
Weirdly, the description showed up in the email github sent me but it appears absent on the github issue?

**Comment by caesarxuchao** [comment]
The description was there when I read it but disappeared now.

**Comment by microadam** [comment]
@lavalamp Well thats very odd! If you have it on your email, could you post it on here please (and I will update the description)? I unfortunately haven't got the error message to hand now...

**Comment by lavalamp** [comment]
I took the liberty of just editing the OP.

**Comment by microadam** [comment]
thanks a lot! Not sure what happened there!

**Comment by caesarxuchao** [comment]
@microadam, could you paste the returned output at "server-ip:port/api" and "server-ip:port/apis"?

**Comment by microadam** [comment]
Sure.

`/api`

```
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "178.x.x.x:443"
    }
  ]
}
```

`/apis`

```
{
  "kind": "APIGroupList",
  "groups": [
    {
      "name": "autoscaling",
      "versions": [
        {
          "groupVersion": "autoscaling/v1",
          "version": "v1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "autoscaling/v1",
        "version": "v1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "178.x.x.x:443"
        }
      ]
    },
    {
      "name": "batch",
      "versions": [
        {
          "groupVersion": "batch/v1",
          "version": "v1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "batch/v1",
        "version": "v1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "178.x.x.x:443"
        }
      ]
    },
    {
      "name": "extensions",
      "versions": [
        {
          "groupVersion": "extensions/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "extensions/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "178.x.x.x:443"
        }
      ]
    },
    {
      "name": "net.alpha.kubernetes.io",
      "versions": [
        {
          "groupVersion": "net.alpha.kubernetes.io/v1alpha1",
          "version": "v1alpha1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "",
        "version": ""
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "178.x.x.x:443"
        }
      ]
    }
  ]
}
```

**Comment by caesarxuchao** [comment]
Thanks @microadam. "net.alpha.kubernetes.io" has an empty preferred version and that's causing the error you reported.
Is "net.alpha.kubernetes.io" created via the thirdparty resource api? (https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/types.go#L173)

**Comment by microadam** [comment]
aha! Good spot! Yes, it was created via that API. This is the Yaml file I used to create it:

```
kind: ThirdPartyResource
apiVersion: extensions/v1beta1
metadata:
  name: network-policy.net.alpha.kubernetes.io
description: "Specification for a network isolation policy"
versions:
- name: v1alpha1
```

**Comment by caesarxuchao** [comment]
Thanks for the confirmation @microadam. Your configuration is correct. The preferred version is left empty by the thirdparty resource controller, while our discovery client has an assumption that the preferred version won't be empty. 
I'll patch the discovery client to tolerate an empty preferred version, and will discuss with @lavalamp on if we should make a default preferred version for a thirdparty resource.

**Comment by microadam** [comment]
Thanks a lot @caesarxuchao! Great job on working it out :)

**Comment by caesarxuchao** [comment]
Sent #23985 to fix.

**Comment by sgrimee** [comment]
What would be a workaround for this before the release, how can one specify the preferredVersion?

**Comment by caesarxuchao** [comment]
AFAIK, there is no workaround. There is no way to specify the preferredVersion for the thirdPartyResource.

**Comment by ufernis** [comment]
I have a quick workaround to fix this : 

1) Change the kubernetes apiserver.yaml to reflect the following :

from : thirdpartyresources=true
to : thirdpartyresources=false

2) Then restart 'kubelet' service OR reboot the K8S Master server
systemctl restart kubelet

3) Revert back the changes done to kube-apiserver.yaml
from : thirdpartyresources=false
to : thirdpartyresources=true

4) Verify whether the above change on the above manifest file has been automatically picked up by the kubernetes API

ps aux | grep -i thirdpartyresources

5) Finally you may restart kubelet service
systemctl restart kubelet

6) Now verify whether the 'kube-controller-manager'  is in a 'Running' state

kubectl  get pods --all-namespaces | grep -i controller-manager

Hope this fix works for you guys as well !!
