### ISSUE TITLE
Kubernetes v1.2.1: release.sh tests failure

### ISSUE THREAD

**Issue by mapolone** [kubernetes/kubernetes#23802]
I'm trying to build v1.2.1 on top of CoreOS (beta version 991.2.0), getting following errors:

--- FAIL: TestMetricsDuGetCapacity (0.01s)
    metrics_du_test.go:73: Unexpected Used for directory with file.  Expected 12288, got 16384.
FAIL
FAIL    k8s.io/kubernetes/pkg/volume    0.022s

!!! Error in hack/test-go.sh:241
  'return ${rc}' exited with status 1
Call stack:
  1: hack/test-go.sh:241 main(...)
Exiting with status 1
!!! Error in ./../build/common.sh:604
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: ./../build/common.sh:604 kube::build::run_build_command(...)
  2: ./release.sh:36 main(...)
Exiting with status 1

**Comment by alexey-cheptsov** [comment]
Same issue on Ubuntu 12.04
