### ISSUE TITLE
Support zookeeper in PetSet

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#23804]
__I haven't deployed zookeeper to production, I'll incorporate comments from anyone who has into this missive.__

Zookeeper exposes a filesystem like api similar to chubby or etcd. Write requests sent to followers are forwarded to the leader, which executes then broadcasts the result as a proposed state change to all servers in the ensemble. Servers respond with an ACK, leader only waits for a quorum of ACKs before committing.

### Initial Deployment

Initial deployment of zookeeper is quite easy because the members of the ensemble will poll on a timeout for peers to show up. Each server takes its configuration from a zoo.cfg file that contains a total list of servers (including itself), and a myid file that contains its own identity in zoo.cfg.

Kube implementation notes:
1. Create a service with ClusterIP: None and name zk.
2. Create 3 RCs, with the pod.beta.kubernetes.io/hostname and subdomain set to, eg: "server$(ID)", "zk"
3. Each RC/replica has a unique ID. The id is used in 2 places:
    - zoo.cfg: this is a list of all peers, including this replica
    - myid: this reflects the index in zoo.cfg of the current replica
4. Each RC/replica has a pvc that stores its data files and transaction log.

#### Standalone to quorum

A standalone member needs to restart in quorum mode with the right configuration.

#### Observers

Zookeeper has a role called "Observer" that allows the scaling of reads by adding members that don't participate in voting. Adding observers is easier than adding followers. Observers still proxy writes to master.

1. Write all server config files with server.$(observer id):ip:observer.
2. Write observer config file with peerType=observer.

#### Core members

Scaling core members is somewhat brittle. The first option that springs to mind is: shutdown the 3 member cluster, bring up a 5 member cluster. This is racy because of the following scenario:
- A,B,C steady state cluster
- C lags, A,B are in quorum
- Shutdown cluster
- A,B,C,D,E cluster started
- A,B are slow to start
- C,D,E form quorum and accept some writes
- A,B come up, erase state that C didn't initially have

Newer releases of zookeeper have a "reconfig" command to help with this dance.
1. Make sure there is quorum.
2. Join new members as non-participants, so they sync state with master but don't vote.
3. Run zkCli.sh reconfig -add

The third step will promote non-participants specified after "add" to participants, commit the new config, and link it from the existing config through the "dynamicConfigFile" variable.

In older release, this needs to be done manually. Points to note when doing so:
* It's only safe to scale one member at a time. 
* If the joiner reboots during 3, the babysitter will have to clear out the config file, leaving it in a corrupt state confuses the ensemble. 
* One needs to be careful that the new joiner/joiners don't somehow form a quorum with a lagging follower. This involves listing them as observers and promoting them to participants (TODO elaborate on how this is done manually). 
* There are other situations where admin intervention maybe necessary to recover the cluster consistently, see: https://zookeeper.apache.org/doc/trunk/zookeeperReconfig.html#sc_reconfig_modifying for details. 

#### Hierarchical quorum

AKA deploying another zookeeper cluster and reconfiguring existing clusters to perform a weighted quorum. The weights of each group need to be computed by the admin or babysitter to distribute voting rights. All writes go to the leader, then out to the periphery, and a reply is stalled till a quorum replies from each group (this actually depends on the configured weights).

TODO: Update how one goes from normal to co-loc/hierarchical quorum and if that incurs downtime. Docs don't help clarify: https://zookeeper.apache.org/doc/r3.3.4/zookeeperInternals.html#sc_quorum. Can this be done by a generic autoscaler? 

### Upgrade

Very similar to etcd upgrade. See #23790. Babysitter needs to be careful in upgrading, you can't just eg: jump to version 3.5.0 without first updating to 3.4.6 (https://zookeeper.apache.org/doc/trunk/zookeeperReconfig.html#ch_reconfig_upgrade).

### Failures

Observer crash: all observers can crash and this will only affect read throughput.
Follower crash: as long as there's a quorum, the ensemble doesn't care about follower crash.
Leader crash: incurs downtime because new leaders will not start till there is agreement on the inital state of the epoch.

### Thoughts

Easier:
* Bootstrap as a static cluster. 
* Scale read throughput by adding observers.
* Update, as long as there isn't a version chain dependency. 
* Take down and rehabilitate a single server.

Harder: 
* Scale for write throughput by adding core members
* Re shuffle clients evenly across new members
* Distribute failures across a WAN (hierarchical groups)
* Take proactive action on failure

Some way to send an interrupt to existing replicas with some json about a new member might help with the harder points.

**Comment by bgrant0607** [comment]
see also #5017

**Comment by bgrant0607** [comment]
https://cloudplatform.googleblog.com/2016/04/taming-the-herd-using-Zookeeper-and-Exhibitor-on-Google-Container-Engine.html

**Comment by thockin** [comment]
@bprashanth Prio for this wrt 1.3 ?

**Comment by bprashanth** [comment]
It's done https://github.com/kubernetes/contrib/tree/master/pets/zookeeper but the example won't work till we've pushed a dns imaage with https://github.com/kubernetes/kubernetes/pull/26393
