### ISSUE TITLE
DNS testing docs need small tweak

### ISSUE THREAD

**Issue by borg286** [kubernetes/kubernetes#23805]
Under kubernetes/cluster/addons/dns/
namely [here](url=https://github.com/kubernetes/kubernetes/tree/release-1.2/cluster/addons/dns#how-do-i-test-if-it-is-working) Please update the following line

kubectl exec busybox -- nslookup kubernetes.default

to be instead

kubectl exec -ti busybox -- nslookup kubernetes.default

Without the -ti the command will hang without any output from the command being reported to the user. For many months I thought that DNS wasn't working.

**Comment by borg286** [comment]
The url link didn't paste right
https://github.com/kubernetes/kubernetes/tree/release-1.2/cluster/addons/dns#how-do-i-test-if-it-is-working

**Comment by xiangpengzhao** [comment]
/sig docs

current the very doc has been changed a lot from this issue on. That line doesn't exist any more. So we can close this issue.

/cc @thockin
