### ISSUE TITLE
Write documentation for inter-pod affinity/anti-affinity

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#23803]
Kevin, I can do this. 

We'll need to figure out how documentation is supposed to work for functionality that is only available at HEAD and not in the currently-released version, under the new docs repo system.

cc/ @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Thanks for mentioning this. What do you mean by "only available at HEAD and not in the currently-released version"?

**Comment by davidopp** [comment]
I mean if I write the documentation next week, should we merge it into the master branch in the docs repo (which could confuse people who are using 1.2, since it's not in 1.2). We don't have versioned documentation set up for the new docs repo yet, so I'm not sure what to do.

**Comment by davidopp** [comment]
(Ideally we want the documentation to be visible to people who are building from HEAD or using one of the 1.3 alpha releases, but not people who are using 1.2).

**Comment by kevin-wangzefeng** [comment]
Yes. For long term I think we still need to support documentation versioning, but currently, for shor term, maybe we can just add some comments/descriptions saying that this part is supported in HEAD/1.3 alpha, not in 1.2? (It's an ugly way, but easy to do.)

**Comment by davidopp** [comment]
Yes, I think that's the only choice for now.

**Comment by davidopp** [comment]
This feature is disabled by default in 1.3 due to performance issues (#26144), so while I will still write documentation for it since someone might enable it, I'm going to remove the 1.3 milestone.

**Comment by kevin-wangzefeng** [comment]
Closing since it has been addressed.
