### ISSUE TITLE
Memory cgroup must be enabled on Debian 8 with Docker 1.10

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#23816]
I've used Docker 1.10 on Debian 8 with k8s 1.1 and it works just fine, however something broke with 1.2 and nodes fail to register. Enabling memory cgroup (via kernel args) fixes the problem.

**Comment by errordeveloper** [comment]
It's possibly related to #20121...

**Comment by Smana** [comment]
Hi, just to confirm the issue, we needed to build our own gce image for https://kubespray.io.
Same issue with the base debian jessie images on AWS or GCE.

**Comment by errordeveloper** [comment]
ping #19720.

**Comment by errordeveloper** [comment]
I have noticed that the kernel argument is referenced in the code, including the end-to-end test suite and new AMI builder script:
```
cluster/cloudimages/k8s-ebs-jessie-amd64-hvm.yml:       - [ 'chroot', '{root}', '/bin/sh', '-c', 'echo "GRUB_CMDLINE_LINUX_DEFAULT=\"cgroup_enable=memory oops=panic panic=10 console=ttyS0\"" >> /etc/default/grub' ]
test/e2e_node/environment/conformance.go:const cmdlineCGroupMemory = `cgroup_enable=memory`
test/e2e_node/environment/conformance.go:               return printError("Kernel Command Line Check %s: cgroup_enable=memory not enabled in /proc/cmdline", failed)
test/e2e_node/environment/setup_host.sh:  sudo sed -i 's/GRUB_CMDLINE_LINUX="\(.*\)"/GRUB_CMDLINE_LINUX="\1 cgroup_enable=memory"/' /etc/default/grub
```

**Comment by dchen1107** [comment]
Yes, both cpu and memory cgroup must be mounted properly, otherwise both docker and kubelet won't work. We introduced this prerequisite to Kubelet 1.1 release, and added node environment validation including kernel configs in Kubernetes 1.2 release.

**Comment by errordeveloper** [comment]
@dchen1107 is that explicitly documented somewhere?

**Comment by errordeveloper** [comment]
`/lifecycle frozen`

**Comment by ehashman** [comment]
/remove-lifecycle frozen

Docker 1.10 is no longer supported.

/close
