### ISSUE TITLE
Leader election causes a lot of endpoint updates

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#23812]
After enabling leader election for scheduler and controller-manager there's a lot of noise on `/api/v1/endpoints?watch=true`:

```
{"type":"MODIFIED","object":{"kind":"Endpoints","apiVersion":"v1","metadata":{"name":"kube-scheduler","namespace":"kube-system","selfLink":"/api/v1/namespaces/kube-system/endpoints/kube-scheduler","uid":"817fe020-fa4f-11e5-b3f8-9457a55ed624","resourceVersion":"1141419","creationTimestamp":"2016-04-04T10:25:08Z","annotations":{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"kubetest2\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-04-04T10:25:08Z\",\"renewTime\":\"2016-04-04T11:33:38Z\",\"leaderTransitions\":0}"}},"subsets":[]}}
{"type":"MODIFIED","object":{"kind":"Endpoints","apiVersion":"v1","metadata":{"name":"kube-controller-manager","namespace":"kube-system","selfLink":"/api/v1/namespaces/kube-system/endpoints/kube-controller-manager","uid":"8143a91d-fa4f-11e5-b3f8-9457a55ed624","resourceVersion":"1141421","creationTimestamp":"2016-04-04T10:25:08Z","annotations":{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"kubetest2\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2016-04-04T10:25:08Z\",\"renewTime\":\"2016-04-04T11:33:39Z\",\"leaderTransitions\":0}"}},"subsets":[]}}
```

 This noise is also hard to filter out because there are no labels set for these two endpoints.

**Comment by zhouhaibing089** [comment]
I think each renew would cause a `MODIFY`.

**Comment by bgrant0607** [comment]
cc @mikedanese

**Comment by j-vizcaino** [comment]
Endpoints being modified all the time, `kube-proxy` syncs (ie. flush/restore) `iptables` entries **very often** (about every 500ms on a 3 node install).
This is really annoying if you want to tackle `iptables` related problems (and maybe lead to performance problems for large clusters)

**Comment by mikedanese** [comment]
You can reduce the frequency of renew at the expense of a speedier master failover. In larger clusters this will likely be dwarfed by pods flucuating. If this causes performance issues in large clusters, we need to fix kube proxy or apiserver or whatever component is affected. We need to support frequent object updates. There isn't evidence that this is the case and we run scalability tests that apply significantly more load in large clusters.

This is different then the issue described by OP. For that we need to add labels to the master endpoints.

**Comment by j-vizcaino** [comment]
@mikedanese Do you want me to file a new issue regarding the kube-proxy flushing iptables way too often?

**Comment by mikedanese** [comment]
Yes please

**Comment by jonaz** [comment]
The only thing changeing is renewTime so we get those events every second.

**Comment by timothysc** [comment]
Is this still an issue?

**Comment by j-vizcaino** [comment]
I haven't had the time to update to 1.3, so I cannot say.

**Comment by obeattie** [comment]
This is definitely an issue in 1.3. I see `iptables-restore` on all my nodes very frequently, and I can see the elected masters causing an endpoint update every second.

**Comment by timothysc** [comment]
We should try to filter updates to the proxy when the only change is an annotation that it's not watching.  This seems to be an unintended consequence of leveraging endpoints.
