### ISSUE TITLE
slack channel invite - not received.

### ISSUE THREAD

**Issue by streamnsight** [kubernetes/kubernetes#23823]
used the slack.kubernetes.io page to try to join the channel, but never got an email.

When i try again it says I already for the invite and i should check for that feedback@slack.com which I never got.

How do I get this email resent to me? 

PS: Tryign to get on Slack to answer another question: My real question is actually here:
http://stackoverflow.com/questions/36322006/kubernetes-using-openstack-cinder-from-one-cloud-provider-while-nodes-on-anothe

**Comment by yujuhong** [comment]
@goltermann, help?

**Comment by goltermann** [comment]
Odd, haven't seen anyone else have this issue.  I can direct add you or re-ping the invite.  Can you send me your email address to [GitHubID]@google.com ?

**Comment by streamnsight** [comment]
i just got an invite now. and got in. not sure if someone did anything but i'm good now. thanks

**Comment by streamnsight** [comment]
actualy i had emailed slack support too and i just got a note from them, so i guess that did it.

**Comment by goltermann** [comment]
Cool, glad it's working.

**Comment by csehra** [comment]
> Odd, haven't seen anyone else have this issue. I can direct add you or re-ping the invite. Can you send me your email address to [GitHubID]@google.com ?

can you help me for adding me there.
My Email ID : chiragsehra44@gmail.com

**Comment by kpj2006** [comment]
Could you please send the invite to  jaihanumanji2006@gmail.com
I’d really appreciate it. Thanks!
