### ISSUE TITLE
Expose externally proxied service addresses

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#2382]
Use case: logging or monitoring wants to expose data about the cluster, but only to people authorized to see it. External IPs seem not ideal for this situation.

Instead, I propose that we route all such traffic through apiserver's /proxy endpoint. We can enforce auth rules at this point. (@erictune will file an issue about this.)

A common pattern is for a pod to deliver a frontend HTML/js/css package to a browser that needs to make calls back to the pod (or services consumed by the pod). To make this possible, we need to give pods service URLs that will route a request back through apiserver to the relevant services. (Pods can't construct such URLs right now because they don't know the apiserver public address. It's also not advisable to make pods figure this out, because we want to be able to easily change the mechanism.)

So, I propose that, along with $FOO_SERVICE_HOST and $FOO_SERVICE_PORT, we supply $FOO_SERVICE_EXTERNAL_URL, which will be a string that looks like "https://1.2.3.4/api/v1beta1/proxy/services/foo". In the future, we'll provide the possibility to replace the IP address with a DNS name.

@satnam6502 @vishh I think this would make your lives easier.

**Comment by thockin** [comment]
Is this still an issue?  I feel like proxy does this well now...
