### ISSUE TITLE
ConfigMap is not readable by non-root users

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#23825]
This is fixed by https://github.com/kubernetes/kubernetes/pull/23793. Opening this issue to discuss whether the fix should be cherry-picked into v1.2.

cc @davidopp @pmorie @thockin

**Comment by pmorie** [comment]
I think this should be cherry-picked. It has a high benefit:patch size ratio

**Comment by paralin** [comment]
+1 for cherry-pick

**Comment by ncdc** [comment]
Cherry pick!

**Comment by saad-ali** [comment]
+1

**Comment by mikedanese** [comment]
cherry pick merged
