### ISSUE TITLE
kubectl get all should show resource types in headers or column

### ISSUE THREAD

**Issue by rothgar** [kubernetes/kubernetes#23838]
When running `kubectl get all` I can see the different types of resources running in the cluster but if I want to delete/remove/get one of the resources I don't know what type it is.

e.g.
```sh
$ kubectl get all --all-namespaces
NAMESPACE     NAME                DESIRED        CURRENT            AGE
kube-system   kube-dns-v9         1              1                  26m
NAMESPACE     NAME                CLUSTER-IP     EXTERNAL-IP        PORT(S)         AGE
default            kubernetes          172.23.0.1     <none>             443/TCP         45m
kube-system   kube-dns            172.23.0.100   <none>             53/UDP,53/TCP   26m
NAMESPACE     NAME                READY          STATUS             RESTARTS        AGE
default       kube-proxy-node1   1/1            Running            0               35m
default       kube-proxy-node2   1/1            Running            0               33m
default       kube-proxy-node3   1/1            Running            0               32m
kube-system   kube-dns-v9-yoir3   3/4            CrashLoopBackOff   7               26m
```

But if I want to do anything with kube-dns-v9 I have to know what resource type it is.

The header row should say what type of objects it is listing so I can more easily get details about the objects.

e.g.
```sh
(ReplicationControllers) NAMESPACE     NAME                DESIRED        CURRENT            AGE
kube-system   kube-dns-v9         1              1                  26m
(Services) NAMESPACE     NAME                CLUSTER-IP     EXTERNAL-IP        PORT(S)         AGE
default            kubernetes          172.23.0.1     <none>             443/TCP         45m
kube-system   kube-dns            172.23.0.100   <none>             53/UDP,53/TCP   26m
(Pods) NAMESPACE     NAME                READY          STATUS             RESTARTS        AGE
default       kube-proxy-node1   1/1            Running            0               35m
default       kube-proxy-node2   1/1            Running            0               33m
default       kube-proxy-node3   1/1            Running            0               32m
kube-system   kube-dns-v9-yoir3   3/4            CrashLoopBackOff   7               26m
```
Or maybe it'd be helpful for interactive usage to leave off the headers and add a new column with TYPE

```sh
NAMESPACE     NAME                DESIRED        CURRENT            AGE     TYPE
kube-system       kube-dns-v9     1              1                 26m       rc
```

This would make other cli tools (grep, awk) much easier to use with `kubectl` output because then I can do something like `kubectl get all --all-namespaces | grep rc` and get all of the replication controllers. I know I can use `kubectl get rc` but there are still more powerful cli tools that I may want like excluding rc ( `grep -v rc` ) or printing and looping on a specific column from the output (eg `kubectl get all | grep -v ing | awk '{print $2}'` )

**Comment by AdoHe** [comment]
@rothgar sounds like a good advice, thanks very much. And I prefer the second option, will add this asap.

**Comment by AdoHe** [comment]
@kubernetes/kubectl

**Comment by kargakis** [comment]
@AdoHe note that indentation should be ok

**Comment by AdoHe** [comment]
@kargakis first that we should make sure whether we should add this, for me I think it's reasonable, but need more members thought. so what do you think?

**Comment by kargakis** [comment]
sounds reasonable to me

**Comment by AdoHe** [comment]
Ok I will add this asap, of course indentation should be ok.

**Comment by smarterclayton** [comment]
What's the proposal?

**Comment by AdoHe** [comment]
@smarterclayton I prefer adding a new column named `TYPE` when use `get all`, just like this:
```
NAMESPACE     NAME                DESIRED        CURRENT         AGE     TYPE
kube-system   kube-dns-v9         1              1               26m     rc
```
This would make other cli tools(grep, awk) much more easier to integrate with kubectl. what do you think about?

**Comment by kargakis** [comment]
Should be the first field

**Comment by smarterclayton** [comment]
Sure, but type should be in the left most column if we're going to do this

**Comment by rothgar** [comment]
I agree TYPE field should be on the first column. I was just trying to modify the existing output and obviously doing a poor job keeping columns aligned with markdown spacing.

**Comment by fabianofranz** [comment]
Another option would be to replace the `NAME` column header with the actual kind name (short version if it's too long), like `POD`, `RC`, `SVC`, etc. E.g.:

```
NAMESPACE     POD                 READY          STATUS             RESTARTS        AGE
default       kube-proxy-node1    1/1            Running            0               35m
default       kube-proxy-node2    1/1            Running            0               33m
```

**Comment by rothgar** [comment]
I also thought the syntax could use the slash syntax that kubectl takes because it wouldn't require a new column.

```
NAMESPACE     NAME                    READY          STATUS             RESTARTS        AGE
default       pod/kube-proxy-node1    1/1            Running            0               35m
default       pod/kube-proxy-node2    1/1            Running            0               33m
```

But I didn't like that as much from a post filtering option. It would be much harder to grep/awk without a dedicate column and instead would need `| awk -F '/'` which isn't necessary with columns.

**Comment by kargakis** [comment]
@rothgar's latest suggestion made me think that we are going to have the same problem again once resources spread across api groups. So how about retaining NAME when a specific resource has been provided and have a RESOURCE column instead of NAME when multiple resources are provided? Syntax would be the same as in the cli.

**Comment by AdoHe** [comment]
I think for a specific resource, we should keep the original output, retain NAME. For resources spread across api groups, I don't really want to replace NAME column with RESOURCE column, I want to still keep the NAME column, as some other tools may use this, I prefer to add a new column to identify the resource type.

**Comment by bgrant0607** [comment]
See also #8476

**Comment by bgrant0607** [comment]
How about printing the resource type on a row by itself before the corresponding `get` output?

**Comment by AdoHe** [comment]
@bgrant0607 like this:
```
svc:
NAMESPACE   NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
default     kubernetes   10.0.0.1     <none>        443/TCP   5m
rc:
NAMESPACE     NAME                DESIRED        CURRENT         AGE
kube-system   kube-dns-v9         1              1               26m
```

**Comment by bgrant0607** [comment]
@AdoHe Yes, though I'd prefer to use the full resource type names (services, replicationcontrollers).

**Comment by krmayankk** [comment]
i could give this a try as my first PR. would need some hand holding though. Not very familiar with kubectl code. What is the final decision on this, do we just want a new column for the resource type or do we want resource type on a line by itself. I prefer the former. I am thinking more in terms of piping the output of kc get all and doing some machine grepping/cutting. thoughts ?

**Comment by AdoHe** [comment]
@kubernetes/kubectl we need to make a final decision. @krmayankk it would be great if you have bandwidth to do this. I can help reviewing your code. Also if any problem please comment here.

**Comment by krmayankk** [comment]
@AdoHe sure, will start looking where this change is needed as soon as we have a decision on this.

**Comment by krmayankk** [comment]
@adohe @janetkuo kubernetes/pkg/kubectl/cmd/get.go is where i see a flag called "show-all". I am not sure where its being handled. Am i looking in the the right place. Also another question, how do(what commands to use) i just build kubectl to quickly test my changes or put some debug flags. Thanks for your help

**Comment by krmayankk** [comment]
never mind i figured, it was 'make all WHAT=cmd/kubectl GOFLAGS=-v'

**Comment by krmayankk** [comment]
@AdoHe question, when i do get all --all-namespaces, i only see services and pods, i dont see rs. I am running 1.2 client against 1.2.4 server. Did we start showing rs in a release after that ?

**Comment by rothgar** [comment]
@krmayankk There are a few things that are missing from `kubectl get all` (rs, ds, deployments) I was looking last night if there's already an issue for those missing types but didn't see one. I was going to open a separate issue for that after asking in slack if someone else knows if work is already being done to fix it.

**Comment by krmayankk** [comment]
@adohe @janetkuo kubernetes/pkg/kubectl/cmd/get.go is where i see a flag called "show-all". I am not sure where its being handled. Can someone help me figure where all the resources are being get and where the display is being handled.

**Comment by krmayankk** [comment]
@AdoHe  can you help with figuring out where this change is needed and i can do some testing

**Comment by krmayankk** [comment]
@AdoHe ah somewhere in resource_printer.go
