### ISSUE TITLE
rkt does not support read-only rootfs container

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#23837]
Currently, rkt does not support changing the rootfs of the container to be read-only at the runtime.

cc @jonboulle @iagius @alban @euank

**Comment by jonboulle** [comment]
@iaguis

**Comment by jonboulle** [comment]
also https://github.com/appc/spec/issues/245

**Comment by yifan-gu** [comment]
FYI, @tmrts is looking at this.

**Comment by tmrts** [comment]
With appc/spec#603 appc/spec v0.8.1 and coreos/rkt#2624 rkt v1.6.0, container rootfs can be modified to be read-only at the runtime.
