### ISSUE TITLE
Ubernetes Service Controller

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#23848]
Service controller comprises two major parts (see docs/design/federated-service.md for details):

1. Delegating service creation to underlying Kubernetes clusters.
1. Creating load balancing apparatus across the top of the resulting Kubernetes services.
    1. kubectl needs to be able to do this too, without an Ubernetes control plane, at least for GCE

**Comment by quinton-hoole** [comment]
Initial design notes on details of service discovery via DNS:

https://docs.google.com/document/d/1Lqe8rhiLveoDRoRQHRqL5p91_yQ1M9wIT8THvbTVH4M/edit#

Will add these to docs/design/federated-services.md after a round of initial comments.

**Comment by quinton-hoole** [comment]
ref: #24009

**Comment by quinton-hoole** [comment]
cc @jianhuiz FYI

**Comment by mfanjie** [comment]
@quinton-hoole some discussions
About CloudProvider: 
In k8s the cloud provider info is loaded from configure file, in federation, as we are handling multiple clusters, cloud providers for each cluster might be different, is there a way to retrieve the cloud provider info outside the actual cluster? I did not see such code, maybe we need to add that. 
An alternative is in current phase we do not support heterogeneous federation, by that way we still can load provide from config file as is.
About Authentication:
If the unsecure port of the cluster is disabled, how controller manager could talk to k8s clusters?

**Comment by quinton-hoole** [comment]
@mfanjie The service controller should only need to interact with the clusters via the Kubernetes API, so there should be no need to access the cloud provider directly.  For DNS we use a DNS provider API, which is actually independent of the cloud provider.

If we do find it necessary to handle clusters differently based on which cloud provider they're running on, then yes, we might need to expose the cloud provider via the Kubernetes API.  As a temporary work-around (and this might even be permanently sufficient), I think it's possible to determine the cloud provider by inspecting the node attributes via the Kubernetes API.  AWS nodes are labelled as being in well-know AWS zones, GCE in GCE zones etc.

**Comment by quinton-hoole** [comment]
@mfanjie Regarding heterogenous federation, I think that we need to support that from phase 1.

Regarding authentication, yes, the controller manager needs authenticated access to the cluster's API server.  Same as for the current Federated ReplicaSets.

**Comment by mfanjie** [comment]
@quinton-hoole here is my understanding on responsibilities of each related component, please correct me if I have any misunderstanding. I am coding based on these understandings and assumptions.

controller manager
  - init federation clientset
  - init dns provider by reading config file
  - start controllers including cluster controller and service controller

cluster controller
  - init clientset to actual k8s clusters
  - build kubeclientmap and expose it as public

dns provider
  - provider implmentation on DNS related operations

service controller
  - watch clusters, even we already hold kubeclientmap, we need to get every event of cluster state changes, e.g. when a cluster is newly added to federation, we need to create all service info to it.
  - watch service delta
  	- for each service detail, write dns entries by calling dns provider api
  	- create service in each available clusters
  	- if there is newly added cluster, add all services to it.

**Comment by quinton-hoole** [comment]
Yes, that's about right.

**Comment by mfanjie** [comment]
write down and tracking the dependencies here:

- [ ]  cluster controller(@huangyuqi): 
clusterClientMap to be public so service controller can reuse the clientset instead of creating own ones.
- [ ] apiserver(@nikhiljindal): 
service to be registered in federation apiserver and provide core client to access service
- [ ] dns provider(@quinton-hoole):
dns provider to talk to dns server.

There are two major tasks in service controller:
1. organize basic code flow, as the dependencies listed above, I can not test anything at the moment even though I have write most of the code skeleton.
2. rewrite the logic of watchServices, to apply the best pattern like other controller, this change is required for both k8s service controller and federation controller.

Confirm in issue 21625 about who is working on the rewrite, maybe we can start here(work on k8s service controller and then apply to federation) if no one working on it yet.

**Comment by mfanjie** [comment]
In k8s controller manager, every controller holds its own clientset, like https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L200-L206. We might need to follow the same, then we have no dependency on cluster controller anymore. But need to maintain our own clientsetMap, and need to consider secure access of k8s clusters.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/25232 is adding service resource to federation-apiserver
and https://github.com/kubernetes/kubernetes/pull/25443 is updating the generated federation_clientset to include services.

**Comment by mfanjie** [comment]
thanks, working on service controller coding, will send out a wip by this week.

**Comment by quinton-hoole** [comment]
@mfanjie Could you send the WIP PR in now, even if it's not done.  I'd like to get a sense of where we are.  Thanks.

**Comment by nikhiljindal** [comment]
Documenting the discussion I had with @mfanjie regarding how to create services in k8s clusters and how to tie them with the parent federation service.

The first approach we discussed was to create k8s services with the same name as the federation service. But then what if a k8s service already exists with that name? Do we say federated service failed? How do we represent that?

The second approach we discussed was to use labels. Similar to deployments, we use a label whose value is hash of ServiceSpec. We add this label to the federation service. ServiceController in its sync loop looks at all federationServices, then for each federation service, asks each k8s cluster for services with that same label. If it gets back a service, all is well and it does nothing, else it creates a service in that k8s cluster with that label.

The second approach seems better.
If a client wants to get all k8s services corresponding to a federation service, it first calls get clusters API from federation apiserver and then calls get service in each of those k8s cluster with the label selector.
Post 1.3, we can provide an API for that in apiserver.

Thoughts?

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-cluster-federation

**Comment by mfanjie** [comment]
wip #25517, I marked the remaining actions in the PR.

**Comment by nikhiljindal** [comment]
The label key for deployments is "pod-template-hash". We can call it "service-spec-hash" here.

We also need to figure out how deletion will work. How will we delete k8s services when federation service is deleted. One way is that the ServiceController looks at all k8s services with the service-spec-hash label (with any value) and if there is a k8s service for which there is no corresponding federation service with the same hash value, then it deletes that k8s services. 
Long term, we can use something like ownerReferences as proposed in https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/garbage-collection.md. We wont be able to use the ownerReferences field, but can add a similar field.

**Comment by madhusudancs** [comment]
@nikhiljindal sounds good to me for 1.3. But we will soon (post 1.3) need something like /services/shards  endpoint that you proposed.

**Comment by mfanjie** [comment]
@quinton-hoole I want to describe more detail of the federation service controller flow, which is different with current k8s service controller. The major difference per my current understanding is service controller won't talk to dnsprovider until step 7, after it get LB info from k8s cluster. This is a major different, so we need to an informcontroller to every registered cluster and watch the service changes.

Create service(with LB info specified) use case:
1. service controller watch federation api-server for services and clusters, service controller WATCH all register k8s clusters for services
2. service controller get new service request
3. service controller clone service
4. service controller create label to cloned service based on hash, and  assign random generated service name
5. service controller iterate all running clusters, and for each cluster
5.1 service controller query service info with the labels on each cluster
5.2 if service is found, simply return the service(check dnsprovider for dns existence?)
5.3 if service is not found create the service
6. cluster service watch get service update info of k8s services
7. check LB info, if LB info exists, create DNS entry by calling dnsprovider api

**Comment by mfanjie** [comment]
One thing I am not quite sure about is do we need a watcher for each cluster? or we simply try to get the service info for update? as we only care about the specified service. So to make it simple, after the service is created, we pull the service info from k8s apiserver like 5 times with 5s as interval, if the LB info is not there, mark it failed? This is much more simple.

**Comment by quinton-hoole** [comment]
See #25517 for federation service controller.

**Comment by quinton-hoole** [comment]
@mfanje, @nikhiljindal I'm working through all your questions and code now.  Will have answers within the next few hours.

**Comment by quinton-hoole** [comment]
@mfanjie @nikhiljindal (after discussion with and approval from @nikhiljindal and @bgrant0607)To 

To answer @nikhiljindal 's questions:

1. services created in underlying kubernetes clusters should have the same name as those in the federation.  This enables, amongst other things, adoption of existing services.  It also makes the DNS resolution simpler, as the federated service name, kubernetes service name and DNS name are all directly related by name, and do not include any e.g. random number, inconsistent hashes etc.
2. if a service with that name already exists in the underlying kubernetes cluster, it should be "adopted" by the federation, and the federation must update it's spec accordingly.
3. Deletion should be possible in either a cascading (delete underlying services) or non-cascading (leave the underlying services)  fashion.  For v1.3 alpha I'm happy if we only support non-cascading deletion.

To answer @mfanjie 's questions:

Yes, DNS records are only updated once each underlying service both exists and has healthy backends/endpoints.  We don't want to send traffic to kubernetes services which have zero healthy backends.

And using your numbering:

1. yes (watch federation API for clusters and services, watch all kubernetes clusters for services)
2.
3. 
4. and
5. Yes, except rather implement this as a reconciliation loop, so that the federation service controller is constantly applying changes to the underlying kubernetes controllers to make them consistent with the federation service specs.  You can do this efficiently by only responding to:
   1. additions of new federated services
   2. updates of federated service specs
   3. spec changes on the underlying kubernetes services (e.g. if a user updates the spec, the federation should set it back to the federation service spec value).
6. and 7 yes, except as per above, only publish the IP address of the underlying kubernetes service loadbalancer IP once the service exists AND has healthy backends/endpoints (and vice verse - if the number of healthy backends/endpoints drops to zero, unpublish it's IP - this you can do efficiently with a reconciliation loop as described above).

I will post a separate comment here describing exactly what the DNS records need to look like.

**Comment by quinton-hoole** [comment]
Regarding what DNS A records to publish, see https://github.com/kubernetes/kubernetes/pull/25107#issuecomment-218026648
We will be implementing that for v1.3.

**Comment by nikhiljindal** [comment]
> One thing I am not quite sure about is do we need a watcher for each cluster? or we simply try to get the service info for update? as we only care about the specified service. So to make it simple, after the service is created, we pull the service info from k8s apiserver like 5 times with 5s as interval, if the LB info is not there, mark it failed? This is much more simple.

Watching is better. We can create DNS entry whenever we get LB info. It does not have to be within 5 seconds.

Re: deletion. yes cascading deletion post 1.3 sounds fine. We will need to do that for cluster as well (when a k8s cluster is removed from federation, delete all resources in that k8s cluster that were created for federation resources). That deletion can look like namespace deletion (we delete all resources in the namespace when a namespace is deleted). Will tackle that post 1.3

**Comment by quinton-hoole** [comment]
@mfanjie I suggest that you focus on the reconciliation of the services in the underlying kubernetes clusters in #25517, and I can, in parallel, write a library to program the DNS entries.  Sound good?  I can start on the DNS library today.

**Comment by mfanjie** [comment]
@quinton-hoole do you mean you will wrap the dns provider call like ensureDNSRecord or something like that so I do not need care about the detail? sounds fair to me.

**Comment by quinton-hoole** [comment]
@mfanjie Yes.  I am busy working out the details of ensureDNS.... .
You can focus on getting the services deployed to the underlying clusters in a manner as per my code review comments in #25517.

**Comment by mfanjie** [comment]
@quinton-hoole One more thing want to discuss is how can we ensure the service health status? when watcher in federation service controller caught a service update event with LB IPs, it only means the loadbalancer provider assigned ips to the services, but as you mentioned, there might be 0 healthz backend for that service, then we should not create DNS record for it. The problem is that in order to ensure healthz backend, we need to check the pod info in that cluster right? it sounds much heavy operations than I expected before. the flow would behave like
1. create a watcher to watch k8s service
2. watcher caught service update event
3. check LB info
4. query pod info using selector
5. if 1 or more pods returns, update DNS records.

**Comment by quinton-hoole** [comment]
@mfanjie `kubectl describe service` does this already.  You can check the code there.
All you should need to do is get the endpoints of the service with a single get call.
If the list length is zero, the service is unhealthy.

**Comment by quinton-hoole** [comment]
@mfanjie See http://kubernetes.io/docs/user-guide/services/#defining-a-service for details.

**Comment by davidopp** [comment]
ping @quinton-hoole - this is listed as 1.3 milestone, I see #26034 (and a related PR mentioned there) have merged, can we close this or move it to 1.4 milestone if there will be additional work in the next release?

**Comment by quinton-hoole** [comment]
Yup, this can be closed.  All related PR's are merged.
