### ISSUE TITLE
https://storage.googleapis.com/govmomi/vmdk/kube.vmdk.gz should include curl

### ISSUE THREAD

**Issue by mbhinder** [kubernetes/kubernetes#23850]
`kubernetes/cluster/vsphere/templates/salt-minion.sh` uses `curl` to bootstrap saltstack but the vmdk image above does not include curl.

**Comment by dagnello** [comment]
@saad-ali this issue is not related to issue #23932

**Comment by imkin** [comment]
@mbinder which doc did you use to setup the environment?

The vmdk you are supposed to use is provided here. You are using a very old  http://kubernetes.io/docs/getting-started-guides/vsphere/

**Comment by mbhinder** [comment]
I don't remember where I got the link from but we can close this if it has been updated in the image pointed to in the docs
