### ISSUE TITLE
Kafka Crash makes AWS cluster unstable

### ISSUE THREAD

**Issue by bpatelcs** [kubernetes/kubernetes#23859]
Hi,

This happened when I tried to deploy kafka and zookeeper clusters on AWS using the below mentioned images,  after running config files, all nodes in the cluster was showing NOT READY status in kubectl get nodes.

kafka image: https://github.com/eliaslevy/docker-kafka
zookeeper image: https://github.com/eliaslevy/docker-zookeeper

**Comment by paralin** [comment]
Do you have any logging from the instances that went not ready?

**Comment by bpatelcs** [comment]
Sorry, I did not capture any logs, but one thing we noticed about kafka crashes was that dns lookup was taking too long and kafka connection to zookeeper eventually times out, not sure if this finding is anyway related to node not available issue.

**Comment by justinsb** [comment]
I think that without logs there's not a lot to go on here; we have a separate issue for wily unexpectedly going NotReady and right now we have nothing to differentiate this case, so I'm going to close as a dup.  Feel free to reopen if we discover anything different!
