### ISSUE TITLE
Improve docs on external ip and loadbalancer ip

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#23855]
This keeps confusing people so clearly we're not doc'ing it well enough. When to use what, why is external IP a list, what happens when you set both external and lb ip, what happens to the old lb ip etc? 

Not to mention deprecated public ip :)

I think we should recommend:
- Spec.LoadblancerIP if they just want to use an existing static IP on gce (and clarify that the old ip will get purged)
- externalIP if they have some non-gce static ip already in DNS (and clarify that they need to handle routing up to the nodes)

**Comment by bprashanth** [comment]
Actually I'd like to deprecate externalIP to an annotation, but that's P3

**Comment by thockin** [comment]
I don't think we can realisitically deprecate that.  It's a clumsy feature, though, to be sure.

**Comment by pwittrock** [comment]
@bprashanth Is this something we would block the 1.3 release for?  If not, would you change the milestone or reduce the priority?

**Comment by bprashanth** [comment]
no but don't we usually do a week of docs etc before the release?

**Comment by goltermann** [comment]
This is an issue marked v1.3 and kind/documentation.  Can you get it fixed up this week?
