### ISSUE TITLE
AWS: Old versions of awscli fail with kube-up (including debian stable version)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23868]
As reported by brady.brenot on slack, the version of awscli shipped with debian stable (1.4.2) does not include support for the fileb:// "protocol" for binary user instance data.  Apparently it was introduced in 1.6.3.

Apparently the older awscli actually uploads the literal `fileb:///tmp/kubernetes.j3faov/master-user-data.gz` as the user instance data.

We should avoid depending on awscli if we can, or check the version to make sure it meets our threshold.

**Comment by roberthbailey** [comment]
@justinsb status on this one?

**Comment by justinsb** [comment]
Reducing priority to P2.  Nice to fix, not a deal-breaker.

**Comment by justinsb** [comment]
kube-up in maintenance mode; closing.
