### ISSUE TITLE
Jenkins e2e node builder is failing

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#23878]
Example PR:
https://github.com/kubernetes/kubernetes/pull/23876

/cc @kubernetes/goog-node @smarterclayton

**Comment by vishh** [comment]
PR builder has been failing for a while now. cc @pwittrock

**Comment by pwittrock** [comment]
Duplicate of #23873.

tl;dr: jenkins wasn't correctly flushing configs to disk and things broke when it restarted.

Marking as fixed
