### ISSUE TITLE
kubectl get nodes (command returns empty). 

### ISSUE THREAD

**Issue by jaags** [kubernetes/kubernetes#23877]
How to fix it?

Env:
OS: centos 7

**Comment by AdoHe** [comment]
@jaags you sure your kubernetes cluster has minion nodes?

**Comment by jaags** [comment]
Yes, I have 2 minion nodes. 
Master : 192.168.1.10Minion1: 192.168.1.11  Minion2: 192.168.1.12
1. all able to ping each-other2. All the services are running (IN GREEN) [like etcd, flanneld etc]
please let me know if you need any information.

Thanks


Date: Tue, 5 Apr 2016 17:17:12 -0700

**Comment by AdoHe** [comment]
@jaags  please try `kubectl get nodes --all-namespace`, I guess you are using wrong namespace.

**Comment by jaags** [comment]
Hi,
  I tried $kubectl get ndoes --all-namespace nothing happensShould I replace namespace with something else?
I followed the setup from the following link
https://devops.profitbricks.com/tutorials/deploy-a-multi-node-kubernetes-cluster-on-centos-7/
and 
https://www.vultr.com/docs/getting-started-with-kubernetes-on-centos-7
didn't do any thing extra other than, what's give in these two links.
Thanks
Date: Tue, 5 Apr 2016 20:07:11 -0700

**Comment by AdoHe** [comment]
Try `kubectl get namespaces` to list all namespaces
and what about `kubectl get nodes --all-namespaces` output?

**Comment by jaags** [comment]
what about kubectl get nodes --all-namespaces output?
Its says usage is incorrect and display the usage of kubectl command.

Date: Tue, 5 Apr 2016 22:31:13 -0700

**Comment by jaags** [comment]
Sorry, please ignore the previous mail.


what about kubectl get nodes --all-namespaces output?
— Output : empyt again 
Date: Tue, 5 Apr 2016 22:31:13 -0700

**Comment by zhouhaibing089** [comment]
@jaags since you get the result from api-server, so I would suggest that `kube-apiserver` runs correctly, but the case you get an empty response, I would suggest you check the logs from `kubelet` and see whether it fails to register the node to api-server.

**Comment by jaags** [comment]
Hi,
 I am get the following error. Pleas guide me from there.

[root@kube-minion1 ~]# kubelet --hostname-override=192.168.1.11
I0406 11:35:25.067814    8482 plugins.go:71] No cloud provider specified.
I0406 11:35:25.067991    8482 manager.go:128] cAdvisor running in container: "/"
I0406 11:35:25.271810    8482 fs.go:108] Filesystem partitions: map[docker-253:0-205457246-pool:{mountpoint: major:7 minor:0 fsType:devicemapper blockSize:128} /dev/mapper/centos-root:{mountpoint:/ major:253 minor:0 fsType: blockSize:0} /dev/sda1:{mountpoint:/boot major:8 minor:1 fsType: blockSize:0}]
I0406 11:35:25.602317    8482 manager.go:163] Machine: {NumCores:1 CpuFrequency:2298052 MemoryCapacity:1929736192 MachineID:a636aa937eef4dfb889cf15b9fe9e6f9 SystemUUID:6C4FB201-EED4-4480-8E64-B22FCA8A4EB3 BootID:50617b6d-6594-4055-8416-6aa219655d0c Filesystems:[{Device:/dev/mapper/centos-root Capacity:48898473984} {Device:/dev/sda1 Capacity:520794112} {Device:docker-253:0-205457246-pool Capacity:107374182400}] DiskMap:map[253:0:{Name:dm-0 Major:253 Minor:0 Size:48922361856 Scheduler:none} 253:1:{Name:dm-1 Major:253 Minor:1 Size:3221225472 Scheduler:none} 253:2:{Name:dm-2 Major:253 Minor:2 Size:107374182400 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:52716273664 Scheduler:cfq}] NetworkDevices:[{Name:enp0s3 MacAddress:08:00:27:c6:f7:c8 Speed:1000 Mtu:1500} {Name:enp0s8 MacAddress:08:00:27:3e:30:55 Speed:1000 Mtu:1500} {Name:flannel0 MacAddress: Speed:10 Mtu:1472} {Name:virbr0 MacAddress:00:00:00:00:00:00 Speed:0 Mtu:1500} {Name:virbr0-nic MacAddress:52:54:00:33:19:03 Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:2147016704 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Data Level:1} {Size:6291456 Type:Data Level:2}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown}
I0406 11:35:25.660203    8482 manager.go:169] Version: {KernelVersion:3.10.0-327.el7.x86_64 ContainerOsVersion:CentOS Linux 7 (Core) DockerVersion:1.9.1 CadvisorVersion: CadvisorRevision:}
I0406 11:35:25.662206    8482 cadvisor_linux.go:116] Failed to register cAdvisor on port 4194, retrying. Error: listen tcp :4194: bind: address already in use
W0406 11:35:25.662384    8482 server.go:747] No api server defined - no events will be sent to API server.
I0406 11:35:25.883286    8482 plugins.go:56] Registering credential provider: .dockercfg
I0406 11:35:25.982833    8482 server.go:781] Started kubelet
E0406 11:35:25.982979    8482 kubelet.go:856] Image garbage collection failed: unable to find data for container /
W0406 11:35:25.983000    8482 kubelet.go:867] No api server defined - no node status update will be sent.
I0406 11:35:25.986380    8482 kubelet.go:877] Running in container "/kubelet"
I0406 11:35:25.986465    8482 server.go:104] Starting to listen on 0.0.0.0:10250
E0406 11:35:25.987861    8482 server.go:502] Starting health server failed: listen tcp 127.0.0.1:10248: bind: address already in use
F0406 11:35:26.069138    8482 server.go:133] listen tcp 0.0.0.0:10255: bind: address already in use


Thanks
Date: Wed, 6 Apr 2016 06:46:17 -0700

**Comment by saad-ali** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
