### ISSUE TITLE
Warn if nodes are on a different version than the master?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23874]
We have a health check that warns us if a node has full disk space.  I think we should consider including some form of warning if the nodes have a version of the kubelet that is different from the master.  This is expected to happen during an upgrade, but I don't think users will mind being warned.

Background: use alessio on slack reported problems with configmap.  Turned out he was running kubelet 1.1, because it was the kubelet that shipped with CoreOS.

This information is visible in `kubectl describe nodes`, but we should probably consider surfacing it more obviously to help users.

**Comment by pmorie** [comment]
We had at least a couple of users that had thought that they had upgraded an entire cluster but had only upgraded the master:

#23621 

I worked through it with them by looking at the node information, but I agree that it might be better to surface this in the status as a condition.

**Comment by bgrant0607** [comment]
See also #4855.

cc @aronchick
