### ISSUE TITLE
docs/devel/automation.md: points to nonexistent blunderbuss.yml

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#23875]
In section about [Github Mungers](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/automation.md#github-munger):

>blunderbuss - Tries to automatically find an owner for a PR without an owner, uses mapping file here: https://github.com/kubernetes/contrib/blob/master/mungegithub/blunderbuss.yml

Link https://github.com/kubernetes/contrib/blob/master/mungegithub/blunderbuss.yml shows 404 page.

**Comment by php-coder** [comment]
One more in https://github.com/kubernetes/kubernetes/blob/master/docs/devel/on-call-rotations.md:

>If you need help to cover all of the tasks, partners with oncall rotations (e.g., [Redhat](https://github.com/orgs/kubernetes/teams/rh-oncall)).

Here link to Redhat is broken (and also use improper name, it should be "Red Hat").

**Comment by bgrant0607** [comment]
cc @eparis @hongchaodeng @fejta

**Comment by bgrant0607** [comment]
cc @kubernetes/contributor-experience

**Comment by asalkeld** [comment]
This seems to be fixed with this commit 2fba6d2d6303d02e919f4e14a24bf7cacc8ca2df
Can someone close the issue please.

**Comment by php-coder** [comment]
I'm closing issue because currently on this page no such link.
