### ISSUE TITLE
`FinishedAt` in ContainerStateTerminated is not supported by rkt

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#23887]
Previous discussion in https://github.com/coreos/rkt/issues/1789

Missing `FinishedAt` caused 2 e2e tests to fail. But it seems no tests are testing the `Signal` field yet.

cc @kubernetes/sig-node @jonboulle @sjpotter @euank

**Comment by yujuhong** [comment]
> Missing FinishedAt caused 2 e2e tests to fail.

What e2e tests? `FinishedAt` timestamps are used for container restart backoffs. AFAIK, we don't have container (or pod) restart backoff in rkt yet. Are we going to add that as well?

> But it seems no tests are testing the Signal field yet.

What is `Signal`? Do you mean `ExitCode`?

**Comment by sjpotter** [comment]
@yujuhong yea 2 tests (the restart backoffs) are failing partly because we return a finishedat as 0 which results in incredibly large numbers.  With that said, the way you state it makes me think that rkt will never be able to support this test as is due to no container level operations?

**Comment by yujuhong** [comment]
@sjpotter I didn't mean that. What I mean is rkt will also need to start using the [backoff mechanism](https://github.com/kubernetes/kubernetes/blob/d4dc037bf7501e44647742f18d60fbd85c1b4560/pkg/kubelet/rkt/rkt.go#L1127) in order to pass these test.  Adding the `FinishedAt` timestamp alone isn't enough. I was trying to understand the scope of this issue :-)

Container-level backoff is not possible for now, but rkt should be able to do pod restart backoff, which should be sufficient to pass the tests IIRC.

**Comment by yifan-gu** [comment]
@yujuhong The failing tests are 
`[Fail] [k8s.io] Pods [It] should have their auto-restart back-off timer reset on image update [Slow]`
`[k8s.io] Pods [It] should cap back-off at MaxContainerBackOff [Slow]`

**Comment by yifan-gu** [comment]
> What is Signal? Do you mean ExitCode?

I mean the [terminated state](https://github.com/kubernetes/kubernetes/blob/v1.3.0-alpha.1/pkg/api/types.go#L998) has a field 'Signal' which is not set by rkt.

**Comment by yujuhong** [comment]
> I mean the terminated state has a field 'Signal' which is not set by rkt.

I can't find anywhere in our code that we set this for docker containers...

**Comment by yujuhong** [comment]
> @yujuhong The failing tests are 
> [Fail] [k8s.io] Pods [It] should have their auto-restart back-off timer reset on image update [Slow]
> [k8s.io] Pods [It] should cap back-off at MaxContainerBackOff [Slow]

Yeah, both tests need the container restart backoff mechanism, which should be implemented as pod restart backoff. We should either include this in this issue, or file a separate issue for it.

**Comment by Random-Liu** [comment]
> I can't find anywhere in our code that we set this for docker containers...

I didn't find it, either. It's interesting to know what does the `Signal` mean here...

**Comment by yujuhong** [comment]
We don't have support for `Signal` yet (even for docker), so this should not block rktnetes 1.0

**Comment by yifan-gu** [comment]
Good to know :)

**Comment by euank** [comment]
Now that we've got this in rkt (via https://github.com/coreos/rkt/pull/2402), I can give a shot at plumbing that through here.
