### ISSUE TITLE
Scale down gracefully

### ISSUE THREAD

**Issue by joshk0** [kubernetes/kubernetes#23885]
Currently, the maxSurge and maxUnavailable rules for Deployments only come into play when a rolling-update from one ReplicaSet to another is desired. However, I would love for there to be a generalized notion of maxUnavailable for either a ReplicaSet or a Deployment, so that when I request a scale-down from 7 to 5 (e.g.) with a maxUnavailable of 1, it will kill 1, wait for it to terminate, and only then kill the next one.

Right now, when you attempt this either using kubectl apply on the deployment with a modified replica count OR kubectl scale, it will kill all the downscaled pods at once, which is not desireable for our use case (we lose replication guarantees.)

**Comment by bgrant0607** [comment]
cc @janetkuo @kargakis

**Comment by bgrant0607** [comment]
See also #12611 and #22774

cc @mqliang @mml @davidopp

**Comment by kargakis** [comment]
Once we add MaxUnavailable in PDB, that should do it. We probably need to switch `kubectl delete` and the controllers to use the Eviction subresource. Finally, we need MinReadySeconds in Pods.

cc: @mwielgus @davidopp @ymqytw

**Comment by davidopp** [comment]
I don't think we should change the default behavior of `kubectl delete`. We should either add a new command `kubectl evict` or add a flag to `kubectl delete` to request it to use eviction subresource.

**Comment by kargakis** [comment]
Just reread the initial post, @joshk0 if you want more guarantees during scale down because there is some sort of state your app needs to maintain/rebalance, then you should be using StatefulSet which is optimized for these sorts of consistency guarantees as opposed to the Deployment api which is optimized for availability.
