### ISSUE TITLE
Generates containers until disk space is full on failure

### ISSUE THREAD

**Issue by rwillard** [kubernetes/kubernetes#23881]
Over the weekend I had a pod created with a daemon set on one of my nodes fail. Kubernetes kept trying to restart the pod thus creating new containers until it filled the disk space and crashed the node. How can I avoid this in the future? 3 worker nodes and 1 master node on CoreOS m3.medium instances on AWS if it matters.

**Comment by dchen1107** [comment]
cc/ @mikedanese on daemon set and @vishh on disk management. 

I suspected the root cause is that daemon set controller keep creating new daemon set pods for your failed one, but not recycle the old ones.

**Comment by vishh** [comment]
@rwillard Kubernetes (actually the kubelet) is expected to delete old containers and free up disk space. However all this is currently on a best effort basis and we are working towards making it more robust with some degree of predictability wrt. to Node Stability.

I wonder why the backoff policy did not kick in to prevent the containers from being restarted too often. Can you post your DaemonSet Spec and also the output of `kubectl describe pods <pod name of the failing pod>`?

**Comment by mikedanese** [comment]
Two issues here:
1) figure out how the kubelet gc isn't working well
2) Daemonsets (and all controllers) should backoff if an operation is failing repeatedly #22298 and raise events #21912

**Comment by rwillard** [comment]
Pretty sure this was the daemonset that bugged out.

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-app
  labels:
    tier: monitoring
    app: fluent
    version: v1
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: fluent
    spec:
      containers:
      -
        name: fluent
        image: docker.workpology.com/fluent
        imagePullPolicy: Always
        volumeMounts:
          - name: log
            mountPath: /var/log
          - name: containers
            mountPath: /var/lib/docker/containers
      volumes:
        - name: log
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
      imagePullSecrets:
      -
        name: dockersecret
