### ISSUE TITLE
Deleting in-use PVs and PVCs leads to erratic behavior

### ISSUE THREAD

**Issue by cdragga** [kubernetes/kubernetes#23886]
Currently, Kubernetes places no restrictions on deleting PVs and PVCs.  Because of this, if users delete these resources in an unexpected order, strange and incorrect behavior can result.  There are essentially two parts to this issue, but they seem similar, so I'm grouping them in the same issue for now.
## Deleting bound PVs before PVCs

Suppose a user has a PV, `test-vol`, currently bound to a PVC, `test-claim`.  Then the following sequence of events happens:

```
    kubectl delete test-vol
    kubectl create -f test-claim2.yaml
    kubectl create -f test-vol.yaml
```

Once this is done, running `kubectl get pvc` will show both `test-claim` and `test-claim2` to be bound to `test-vol`.  Pods that reference `test-claim2` will be able to start successfully, while pods that reference `test-claim` will hang in the ContainerCreating state.
## Deleting PVCs in use by a pod

As long as the pod remains up, the pod will continue running successfully (assuming the storage underlying the PVC has not been deallocated).  However, if the pod crashes and is brought back up, one of two cases can happen:
- If no PVC with the name of the deleted PVC exists, the pod will enter CrashLoopBackoff (this should be expected.
- If a new PVC has been created with the same name, the pod will restart with the underlying storage for that PVC mounted.  This will occur even if the PVC has bound to a different PV.

Neither of these cases seem like urgent problems--they rely on users behaving badly--but they could easily lead to confusion or, in the case of in-use PVC deletion, they could enable attacks.  There may be other cases similar to these, but these are what I've noticed so far.

**Comment by thockin** [comment]
We are retooling the storage controller.  Here's how I see this playing out:
@saad-ali @childsb @swagiaal @jsafrane 

If the user deletes a PV that is bound and then recreates it (without a ClaimRef), there's a race.  If the controller finds this before it gets bound to another node, it will try to fix the situation.  If a new PVC is bound to the volume before the PVC syncer catches up, the new PVC will get it and the old PVC will be considered "lost".

To "fix" this is a relatively large amount of work and semantic change.  I don't think we should do it.  We could, on the other hand, inhibit deletion of a PV with a live ClaimRef.  We would have do something like add a "released" field, and change the controller to set the released field and clear the claim ref, and change the recycling condition to consider "released".  But then it would fail to delete a PV  at all in this case.

In the case of a PVC being deleted, I think you're getting what you asked for.

**Comment by swagiaal** [comment]
@cdragga thanks for this detailed test case. Perhaps we can turn this into an e2e test.

As @thockin described I think we handle this case in the new controller design (https://github.com/pmorie/pv-haxxz/blob/master/controller.go) but perhaps this use case is an argument against trying to fix the binding after it has come undone. That is if we find a claim (which was previously bound) which points to a PV which does not point back mark the PVC as lost.

@cdragga what did you expect to happen when you were doing this ?

**Comment by cdragga** [comment]
@swagiaal It does look like the new controller design will handle it, for the most part; having the PVC move to the lost state seems correct.  I would have expected either that behavior, or for the delete command to have failed (command failure doesn't seem to happen in Kubernetes, though, so I'd more expect the former option, though).

As you said, I think this argues against trying to fix the binding.  If I'm reading the code correctly, in the new controller, it's possible for the PV to be deleted, and then for a new PV to be created with the same name that points to different storage; the PVC would rebind to the new PV seamlessly and any data that had been there would be lost.  This is a pretty minor edge case, but it seems semantically wrong to me; I would think PVCs should bind to a specific instance of a name, rather than the name itself, as they're currently doing.

Some degree of recovery could still be attempted if the PV's UID was included in the PVC; the recovery process would look up the PV by UID, rather than name.  It'd be necessary, though, to not have the PVC report itself as bound until the UID was finalized in both objects.  This would require additional steps in the controller's state machine and complicate recovery from partial failure states accordingly, which I'm guessing is something that you'd rather not deal with; it may also get unavoidably racy.

**Comment by swagiaal** [comment]
@cdragga you have read the code correctly yes. So I think that for the time being we can just not fix it. That is mark the PVC as 'lost'. In the future we can explore adding the PV's UID or delete inhibition.. lets see what @thockin says.

**Comment by thockin** [comment]
I thought that was correct from the beginning.  Someone talked me into
keeping the "try to reconnect".  I specifically remember discussing how it
might work sometimes, and how crappy that is. :)

**Comment by jeffvance** [comment]
Out of curiosity,
1) what is the reason for not adding a check that if the PV to be deleted is bound && its target claim is also bound (to target pv) then the pv delete fails (and possibly is retried later)? Maybe this opens the door for too many race conditions?
2) Similar logic for deleting a PVC ?
3) Is there a potential security issue if: the crashed pod is re-launched, and in the mean time a new PVC of the same name was created and points to a different PV, will the pod now have access to data that it previous would not have had access to?
