### ISSUE TITLE
Whether or not to use systemd on host to babysit rkt process

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#23889]
There are both pros and cons on whether or not to use systemd to babysit the rkt process.

Pros of using host systemd:
- The process are grouped into the cgroup slice created by systemd, makes it easier to clean up remaining process when the pod's crash. e.g. https://github.com/coreos/rkt/issues/2384
- More reliable way to get the `FinishAt` timestamp (https://github.com/kubernetes/kubernetes/issues/23887) of the whole pod, e.g. we can add a hook to write down the timestamp in `ExecStopPost` when a pod exits.

Cons:
- Not easy to implement `kubectl run -i` [feature](https://github.com/kubernetes/kubernetes/issues/23335#issuecomment-204180056) when running as a systemd service. (`systemd-run` has the `--pty` options. but `systemctl start` doesn't cc @albal @iaguis 
- Race between cgroups is created and detected by cAdvisor, and the pod is actually running. When run as a systemd service, the systemd creates the cgroup for rkt, this can happen before the pod is running, so cAdvisor will see the cgroup and query the rkt api service for the pods, but the api service will return the pod is not running. See here for a [clearer explanation.](https://github.com/coreos/rkt/issues/2341#issuecomment-203455155)

I think both pros and cons can be solved in one way or another. 
If we don't use systemd on host:
- We can implement the `FinishAt` in rkt, but ignore the situation when it's impossible to write down anything (e.g. stage1 or PID1 is killed)

If we use systemd on host:
- For the `kubectl run -i`, can we have systemd to support `--pty` for `systemctl start`?
- For the cAdvisor issue, there are several ideas:
  - Just ignore the pod level cgroup(which is created by systemd before the pod is running), however this is not preferrable as we miss the resource usage of the pod's systemd/journald.
  - Drop support for stage1 that contains systemd version < v226, as after [v226](https://github.com/systemd/systemd/commit/efdb02375beb0a940c3320865572913780b4d7de), the PID1 of the container will be put into `init.scope` under the root cgroup created by the host systemd. So we can just subscribe the inotify events of the `init.scope`. Correct me if I am wrong here @alban @iaguis

cc @kubernetes/sig-node @jonboulle @philips @sjpotter @euank

**Comment by alban** [comment]
> For the kubectl run -i, can we have systemd to support --pty for systemctl start?

I think that systemd upstream (https://github.com/systemd/systemd/issues/2069) would prefer to not have that feature in systemd, as this would require an extra process to process the data on the pty.

I think that using `rkt run --interactive` prevents the output from going to journald. That's also a concern.

> Just ignore the pod level cgroup(which is created by systemd before the pod is running), however this is not preferrable as we miss the resource usage of the pod's systemd/journald.

I am not sure what you mean with "ignore the pod level cgroup".

> Drop support for stage1 that contains systemd version < v226, as after v226, the PID1 of the container will be put into init.scope under the root cgroup created by the host systemd. So we can just subscribe the inotify events of the init.scope. Correct me if I am wrong here @alban @iaguis

Correct. That would work for me. But at the moment, rkt uses systemd-v225 in stage1. So it would require an update. Does cadvisor have any plans to support VMs in addition to containers? If so, @jellonek had concerns on https://github.com/coreos/rkt/issues/2341#issuecomment-205799519

**Comment by jellonek** [comment]
Argh... VM based containers in addition to cgroups based containers.

Please, do not put equal sign between cgroups and containers, try to remember that there were containers before linux kernel had cgroups. Please remember about openvz, bsd jails and other techs from https://en.wikipedia.org/wiki/Operating-system-level_virtualization

I'm sure that You are disgusted in similar way as I when You hear that many users speaks about containers having docker in mind.

**Comment by yifan-gu** [comment]
Close for now as we are going to stick with the systemd service approach.
