### ISSUE TITLE
e2e flake: `kubernetes-e2e-gke` fails with "GCP resources leaked"

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#23888]
The `kubernetes-e2e-gke` test suite randomly fails with  "GCP resources leaked".

Sample log from build # 3791:
```
14:33:07 --- /var/lib/jenkins/jobs/kubernetes-e2e-gke/workspace/_artifacts/gcp-resources-before.txt	2016-04-05 14:15:35.021752841 -0700
14:33:07 +++ /var/lib/jenkins/jobs/kubernetes-e2e-gke/workspace/_artifacts/gcp-resources-after.txt	2016-04-05 14:33:07.053261760 -0700
14:33:07 @@ -10,0 +11 @@ [ instance-templates ]
14:33:07 +gke-jenkins-e2e-default-pool-45e89bdf n1-standard-2             2016-04-05T14:15:54.643-07:00
14:33:07 + echo '!!! FAIL: Google Cloud Platform resources leaked while running tests!'
14:33:07 
!!! FAIL: Google Cloud Platform resources leaked while running tests!
```

Examples:
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/3791/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/3793/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/3794/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/3796/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/3808/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/3814/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/3816/

**Comment by saad-ali** [comment]
Setting priority to P0, since this is happening every few (3rd or 4th) build and blocking the merge queue.

**Comment by saad-ali** [comment]
`kubernetes-e2e-gke` has been consistently red since 3:30 AM PST due to this issue.

**Comment by bprashanth** [comment]
Fwiw it looks like we're leaking an instance template because it's being used by an instance group, and we're using the same instance group across runs (i.e nodes for new clusters are showing up in the IG gke-jenkins-e2e-default-pool-45e89bdf-grp that is preventing the gke-jenkins-e2e-default-pool-45e89bdf from being deleted every time)

```
central1-f/clusters/jenkins-e2e'
04:47:05  zone: u'us-central1-f'>] finished with error: Google Compute Engine: The instance_template resource 'gke-jenkins-e2e-default-pool-45e89bdf' is already being used by 'gke-jenkins-e2e-default-pool-45e89bdf-grp'
04:47:06 2016/04/06 04:47:06 e2e.go:200: Error running teardown: exit status 1
```

**Comment by roberthbailey** [comment]
This was resolved on the GKE side around noon today.
