### ISSUE TITLE
missing branch conformance-test-v1 in upstream

### ISSUE THREAD

**Issue by woodbor** [kubernetes/kubernetes#23905]
According to comments in a `conformance-test.sh` there is : `git checkout upstream/conformance-test-v1` in line 30. But seems that that branch has been already deleted from an upstream. IMHO, there should be `checkout to desired revision` instead, as far as `conformance-test.sh` is included in an every release.

**Comment by saad-ali** [comment]
`conformance-test.sh` no longer exists. Closing issue.
