### ISSUE TITLE
Decouple TTL in storage.Interface and DeletionTimestamp

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#23902]
Currently, setting TTL will change an object's DeletionTimestamp in [APIObjectVersioner](https://github.com/kubernetes/kubernetes/blob/2699be2e7ecfaf448427122cf5c2f0ef8a352642/pkg/storage/etcd/api_object_versioner.go#L40-L42). This affects [all methods](https://github.com/kubernetes/kubernetes/blob/2699be2e7ecfaf448427122cf5c2f0ef8a352642/pkg/storage/interfaces.go#L99-L162) in storage.Interface in the returned "out" object. 

This is some legacy code from graceful deletion which doesn't use TTL anymore. Hence, I am proposing to decouple TTL logic from DeletionTimestamp, i.e. not changing DeletionTimestamp in storage.Interface.

**Comment by smarterclayton** [comment]
That's fine with me.

**Comment by timothysc** [comment]
+1

**Comment by hongchaodeng** [comment]
Created https://github.com/kubernetes/kubernetes/pull/23923
Please help review

**Comment by wojtek-t** [comment]
+1 from me too

**Comment by hongchaodeng** [comment]
Fixed by #23923
