### ISSUE TITLE
Extend ClusterVerification framework to use Node state.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#23913]
@spiffxp needs node state in some interesting tests hes running on hetero-clusters.  We can incorporate some handy node filters into ClusterStateVerifier once #23771 merges.

Some cleanup on the data model might be useful, in particular, making the PodState filters more modular.

**Comment by jayunit100** [comment]
cc @kubernetes/sig-testing

**Comment by jayunit100** [comment]
cc @timothysc

**Comment by spiffxp** [comment]
thanks for opening @jayunit100, concrete use case I had in mind is verifying that all schedulable nodes are homogenous for density, ref #23710

**Comment by spiffxp** [comment]
/sig testing
/priority awaiting-more-evidence
Closed out the original use case I had in mind but still view this as a nice to have for writing cleaner pre-conditions for e2e tests
