### ISSUE TITLE
Node images doesn't expose digests, which means locked pods can't get scheduling benefits

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#23917]
Anyone who wants reproducible deployments can use image digests/content-addressable-hash (image@sha256:abceouth).  In Docker 1.10, all images locally will be identified by the CAH as well as their tags.  In OpenShift, 80-90% of pods use the digest because we have the machinery to resolve to digest up front for guaranteed exact deployment.

The current implementation of node images does not expose image digests, so creating a pod that is using the digest gets no scheduling benefit.  The node should return the list of digests for matching (if two images have different tags but the same digest, they are the same image under the covers and the scheduler should prefer putting a pod referencing that digest on the same node).

**Comment by smarterclayton** [comment]
@kubernetes/rh-cluster-infra this means we get no benefit in practice from the current scheduling setup.

**Comment by smarterclayton** [comment]
I think there are three changes needed:

1. Add the digest to the `node.status.images[].names` object as a new name or new field
2. The kubelet should identify terminal image names that have been or have recently been in use (since each layer is also an image, there's some risk that we'd show too many layers). In practice only tagged and terminal images (images not covered by other images) need to be returned.  Images can be untagged but be in use.
3. The scheduler predicate, looking to schedule a pod with name `a/b@digest` should match ANY name that ends in `@digest`.

**Comment by ncdc** [comment]
With Docker 1.10 and beyond, my understanding is that the layer-is-image behavior is no longer available, and you can only run images. Maybe that isn't in 1.10 yet (I haven't checked), but if it isn't, it will be eventually.

I'm not sure exactly what you're getting at with terminal image names. Right now the node status contains the output from `docker images` as best I can tell (I haven't looked at the code).

As for 3, the first v2 image manifest format includes the image repository name and tag, so matching just by `@digest` is potentially appropriate. The second v2 format, however, removes name/tag from the manifest, meaning that its digest is actually portable across image repositories and tags, so I think it might be best to do a strict match against the full `a/b@digest`.

**Comment by smarterclayton** [comment]
For terminal images I meant images that are only ever pulled by tag - if I
pull foo/bar@digest it is not "tagged" in 1.9 and thus doesn't show up.  If
that has changed in docker 1.10, then that's good.

**Comment by ncdc** [comment]
You can see images pulled exclusively by digest using `docker images --digests`.

**Comment by smarterclayton** [comment]
Yes, those are the ones that need to be returned by the node.

**Comment by ncdc** [comment]
Roger. So I would say start by including `a/b@digest` and having the scheduler do a strict match on the full pull spec. We can consider relaxing it later if needed.

**Comment by smarterclayton** [comment]
The digest mapping still matters, since a pull wouldn't bring down new
layers.  Why would we do strict matching?

**Comment by ncdc** [comment]
If you have a node 1 with `a/b@digest`, node 2 with `x/y@digest` (same digest), and you're scheduling a pod with image `a/b@digest`, the relaxed match would presumably give equal weight/priority to both nodes, whereas a strict match would give higher priority to node 1. You're right that you wouldn't be pulling down new layers, but if the pod were scheduled to node 2, that node would be required to contact the registry to pull down the image in image repo `a/b`. It would be a fast series of `HEAD` requests, but still slightly more network traffic and processing than if you scheduled to node 1.

**Comment by smarterclayton** [comment]
I would agree that a/b should be higher priority, but I would still want x/y to be a match.  Wasn't sure when you said strict you meant "exclude x/y" which I think is too aggressive.

**Comment by ncdc** [comment]
That works for me - check strict first, relaxed second.

**Comment by ncdc** [comment]
@smarterclayton the scheduler priority function compares container.Image to the names of the images in the node's status. I'm hesitant to put any logic to parse `@sha256:...` since that's Docker specific. WDYT?

**Comment by smarterclayton** [comment]
I think the node should be abstracting that

On May 3, 2016, at 1:39 PM, Andy Goldstein <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> the scheduler priority
function compares container.Image to the names of the images in the node's
status. I'm hesitant to put any logic to parse @sha256:... since that's
Docker specific. WDYT?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/23917#issuecomment-216606244>

**Comment by ncdc** [comment]
Are you suggesting that the `ContainerImage` that is in the node status have both `Names` and `Digests`?

**Comment by smarterclayton** [comment]
Technically the digest is a name.

On May 3, 2016, at 2:02 PM, Andy Goldstein <notifications@github.com> wrote:

Are you suggesting that the ContainerImage that is in the node status have
both Names and Digests?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/23917#issuecomment-216613731>

**Comment by ncdc** [comment]
True. Here are the options I can think of:

1. Augment the list of names for an image in the node to include digests, including the repo; e.g. you would see `busybox@sha256:abcd1234` in addition to `busybox:latest` for the same image
  1. No change to scheduler priority, so it requires an exact match on `repo:tag` or `repo@digest`
1. Augment the list of names for an image in the node to include digest, excluding the repo; e.g. you would see `sha256:abcd1234` in addition to `busybox:latest` for the same image
  1. No change to scheduler priority, but because the image name excludes the repo, this would result in loose matches where only the digest needs to match and the repo is ignored
1. Modify the image data structure to include a separate field for digests (either with or without the repo)
  1. Modify the scheduler priority to look at the digest field too

My PR #25088 currently implements option 1

**Comment by smarterclayton** [comment]
Digest name for Docker runtimes is a valid image target, so 1 or 2 seem ok
(name is vague in our spec, but equates to tag OR digest in docker).
Arguably 2 would give us better matching across the cluster (when tags
change but images don't), but changes the semantics of "name" (you can't
pull by digest).

We can potentially do a 1b option later - have the scheduler be a bit more
aware of digest.

**Comment by ncdc** [comment]
I'm going to mark the PR as a fix for this issue if that's ok?

**Comment by smarterclayton** [comment]
I'm fine with it.
