### ISSUE TITLE
Up to golang 1.6 in golang.sh

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#23915]
As a follow up to #22149, we should also run all tests in Go 1.6.

However, [this line](https://github.com/kubernetes/kubernetes/blob/ce9b2ab3e3cd24a5dc4359a9741709a61d19258f/hack/lib/golang.sh#L281) in golang.sh is still using go1.4.

There are two things to be resolved:
- We should change that in golang.sh to require >= go1.6
- We need to make sure test infrastructure upgrade to go1.6. Maybe we should use container with specific Go version without relying on underlying host env for all test.

**Comment by luxas** [comment]
@ixdy Should we completely jump to go1.6, in other words, make go1.4.2 builds unsupported?

I guess we should, cause of the docker go1.6 vs 1.4 socket issue (don't have the issue number now).

However, that deprecation should be done in another PR (may send one if you like), as it is now

**Comment by hongchaodeng** [comment]
docker issue: #23809

**Comment by luxas** [comment]
Yep, so after that one (which will be in before `v1.3.0-alpha.2`), should we keep `go1.4.2` support or not?

On the other hand, it might be dangerous to drop support for something we've leaned on until yesterday, so it might be best to fix bugs like #23809

/cc @lavalamp @wojtek-t @ncdc @Random-Liu

**Comment by hongchaodeng** [comment]
This issue is not about the go version we support.

We want to update to go 1.6 in all jenkins VMs. In the future, we should make something that doesn't rely on the host

**Comment by spxtr** [comment]
We use 1.6 in Jenkins for unit/integration tests with [hack/jenkins/test-image/Dockerfile](https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/test-image/Dockerfile).

**Comment by hongchaodeng** [comment]
Good to know that.

There is one test called "node-e2e-test" which is added recently. It relies on the host Go to do "e2e" test: ./test/e2e_node/jenkins/e2e-node-jenkins.sh

**Comment by hongchaodeng** [comment]
One example in PR build: [link](https://00e9e64bacd74a2e11ffe6f2198500465e993160e8d56f9428-apidata.googleusercontent.com/download/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F23808%2Fnode-pull-build-e2e-test%2F644%2Fbuild-log.txt?qk=AD5uMEvZJzBiZ6GQMasa3qp7N6YjbGBwAnJ09V6GHJBwg7fIB0hN_0d-zcQrL0JKHDJgUZHK-Ui3jiJ65-8xqPCRMB_upthdY9rc9pGaD64d2lIJqEJ8n0X_jXpl4NtNvQP1ydnLO08XGJUfs1t8g7FRV_vBOOcj8zQ_tTKCxTRtfcTlxdkzczBZojWx8DoG0m45RyIL1bmmeqfaSeUJSCFZjpV7-fLeu33XkvfAOarRC7WFiA4DHgtqGE7-JEozK5NKc5H1ZbdrggozpAuOC2Sk8u04SzrndjZYFcjAAR7xaHMg8Nv5wuP7R9JF6MUao4znR_O_rwK30J4hOF93Y8s2RNCr5904F-ONe3kvgW-6mRR5AjrJxnU5TzlP81V3sBB2qXWDe0OXaMFfZU9UGFv8jteWQmRaEA31_cmQc1L5w0moGggFoiyXbg-58IWMFphpKb0IcicRK3yYelqGo4EWIF8cARcsfFNqviy0eFu9VvYeE4w18r9SK9p-Y2D5ZZr0Uo8Jot5JrdfQJHCtOwbSByFgP2qwlMoCzf5zpn4m8Rz4cS9VyAmS4RlcJKiFIcnlQ1Q0BDhv-NTd-YT4VoX_1s4gSVYMinbZrkQRtNGvRdLVsbBxy8X-lPHfGOeC_fRJKZs-Re6wSy6cMgF13vJIKeDBq8-8niGzS8Sgn5m_6exemUR_jR51UgxYtHb7j6TNlwQVua20BAcr5i5ML1p5VpKdPDF1_cHRYmMaH1rS5hjh5M5YDWA4emx6OCDClt0xx2w5BvP-mp3vIWsV6OTAw-LxYi9WQkD8OZ-MV2d6qPKxoiuj_z4rpz4dJi19X5sFjcvx5zR6cLp0dpj9D6nP9yCPwc5TrA)

In the log it showed:
```
Go version: go version go1.4.3 linux/amd64
```

**Comment by ixdy** [comment]
Once #23808 merges, we lose support for building on Go <1.5, so yes, we probably should
- [ ] explicitly decide to break support building Kubernetes for Go <1.5
- [ ] update `hack/lib/golang.sh` and any other refs to require Go 1.5+ (really Go 1.6+, since I don't think we'll ever support 1.5, x-ref #20656)

I'm not sure who can decide that ratcheting to Go 1.5+ is clear to proceed.

**Comment by hongchaodeng** [comment]
From my perspective, requiring >= Go 1.5 is clear. 

We have 3 months before 1.3 release. It gives community enough time to fix any issues we observe. It's unwise if we stick to go 1.4 for a release cycle.

Not only etcd, but also other issues that wants http2, vendoring would like to do more work with Go 1.6.

Giving it a few days to see things get stable is pretty reasonable.

**Comment by hongchaodeng** [comment]
I know some redhat folks want to deal with specifically GC in apiserver and connection reuse with Go 1.6.

**Comment by ixdy** [comment]
Related: #24599

**Comment by hongchaodeng** [comment]
This is fixed. Closing.
