### ISSUE TITLE
Use services with endpoints using a hostname

### ISSUE THREAD

**Issue by rata** [kubernetes/kubernetes#23921]
Hi,

It will be nice if an Amazon RDS, Amazon ELB or some other hosted service that provides a hostname and not a static IP (like searchify.com or tons of other hosted services) can be a kubernetes service.

If it is a kubernetes service, it can connect to it using the same way, use a simple name, connect to public services exposed in an ELB on another region (maybe by kubernetes ;)) on AWS, just a hosted service like I already said, etc.

The problem right now with that is that a service and an Endpoint needs to be created, and the endpoint can only point to an IP address IIUC [1].

Talking with @justinsb on slack, the immediate way seems to resolve the hostname when the TTL is about to expire and update the IP addresses in the endpoint. But haven't checked the Endpoint code and maybe is possible/desirable to add hostname support. 

Do you also think it is valuable to have a way to use kubernetes services with hostnames? Do you have any suggestions on how to do it?

Thanks a lot!
Rodrigo

[1]: http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_endpointaddress

**Comment by justinsb** [comment]
This is a great idea!  We should do something in the 1.3 timeline.  It might not be a full integration into core, but even just an example pod that can mirror DNS into an external service would be great I think!

**Comment by thockin** [comment]
This is dup of #13748 and/or #13358 (which haven't been de-duped because they are subtly different).  Let's please take the conversation there :)
