### ISSUE TITLE
GCE install broken because of bug in Google Cloud Storage JSON API

### ISSUE THREAD

**Issue by mbhinder** [kubernetes/kubernetes#23926]
When I run cluster/kube-up.sh it hangs on the `gsutil.py mb -l` step because of GoogleCloudPlatform/gsutil#348 

Workaround: Add the following to `$HOME/.boto`:
```
[GSUtil]
prefer_api = xml
```

**Comment by quinton-hoole** [comment]
I wonder why we're not seeing this in our continuous integration tests?

**Comment by quinton-hoole** [comment]
Downstream bug fixed: GoogleCloudPlatform/gsutil#348. Closing.
