### ISSUE TITLE
Add vSphere support to Cloud Providers 

### ISSUE THREAD

**Issue by dagnello** [kubernetes/kubernetes#23932]
This issue will track work associated with adding vSphere cloud provider support in Kubernetes.

**Comment by mbhinder** [comment]
Don't we already have ```export KUBERNETES_PROVIDER=vsphere; cluster/kube-up.sh```? That didn't work for me because of #23850 and even after fixing the image to include curl, it failed because `kube-addons` didn't run.

**Comment by dagnello** [comment]
@mbhinder looking in 'k8s.io/kubernetes/pkg/cloudprovider/providers/' I don't see an implementation for vSphere.

**Comment by vipulsabhaya** [comment]
A full cloudprovider implemention for vSphere doesn't exist today, so at runtime kube can not leverage the cloud provider.  

@saad-ali an appropriate label might be 'area/cloudprovider' as well

**Comment by chrislovecnm** [comment]
What open issues still exist?  Ubernetes?  Ingress and loadbalancing?

**Comment by dagnello** [comment]
vSphere supported added
