### ISSUE TITLE
hack/build-go.sh is too forgiving w/ weird targets.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#23947]
Problem: 

`hack/build-go.sh` accepts any weird argument, like  `hack/build-go.sh test/e2e/blahblahblah`.  This confuses the usability, making it seem like we need to specify a file name, without actually verifying that the filename target means anything.  

Example: 

Obviously "blahblahblah" is not a build target anyone might mistakenly create, but realistically, as a user, if i do something that is logical but meaningless, like `hack/build-go.sh test/e2e/integration.test` I want the system to explode, because there is no "e2e/integration" target.  

Solution.

Either just allow directories and throw an error if the full binary name is given, or else use the binary name .

Notes: 

I beleive when I run with `set -x` go install is just using dirname, so i think we dont really need to support file names as inputs to hack/build-go.sh?  I could be wrong... 

```
+ go install -ldflags ' -X k8s.io/kubernetes/pkg/version.buildDate=2016-04-06T22:00:50Z -X k8s.io/kubernetes/pkg/version.gitCommit=fb19d21dca434853784a5f58cef9454b6a527461 -X k8s.io/kubernetes/pkg/version.gitTre
eState=dirty -X k8s.io/kubernetes/pkg/version.gitVersion=v1.3.0-alpha.1.204+fb19d21dca4348-dirty -X k8s.io/kubernetes/pkg/version.gitMajor=1 -X k8s.io/kubernetes/pkg/version.gitMinor=3+' k8s.io/kubernetes/test/e2e_node/
```

**Comment by spiffxp** [comment]
/sig release
I'm assuming sig-release owns the build-go script
