### ISSUE TITLE
Allow changing heapster service address in HPA controller

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#23942]
Currently heapster service is hardcoded:

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/metrics/metrics_client.go#L38

We should make it a flag to HPA controller to address use-cases where people might want to run heapster elsewhere.

**Comment by nickschuch** [comment]
Just got bitten by this one as well.

Will have a look and see if I can bang together a PR.

**Comment by piosz** [comment]
It would be great @nickschuch

**Comment by nickschuch** [comment]
I see what is happening here, so the current Heapster metrics client is calling the apiserver proxy and routing to the heaster service and pods.

```
$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080
Heapster is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster
```

Ok, so here is my plan:

* Contribute a new heapster metrics client called "external" which uses the same Heapster client interface
* Toggle between the "cluster-info" and "external" client here https://github.com/kubernetes/kubernetes/blob/825cd920ffd49f6115d0d3f38add9ea15543e875/cmd/kube-controller-manager/app/controllermanager.go#L330

**Comment by kargakis** [comment]
@mwielgus which SIG owns this one if not sig/autoscaling?

**Comment by fgrzadkowski** [comment]
We should close it.

For reading metrics (either CPU, mem or custome) we will be using master metric API or custom metrics API, which will be exposed using kube-aggregator. This FR is obsolete.
