### ISSUE TITLE
rkt: Support per-pod stage1-image

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes/kubernetes#23944]
It would be useful to be able to set the rkt stage1-image on a per-pod basis (overriding the global `--rkt-stage1-image` flag on the kubelet).

A example use-case would be using the [rkt-fly stage1](https://coreos.com/rkt/docs/latest/running-fly-stage1.html) when running a self-hosted kubelet, while using the global stage1 for all other pods.

One option might be to use annotations on the pod which the rkt runtime could parse for stage1-image. This would be somewhat lightweight in that no api-changes would need to be made. Eventually this could be replaced if/when runtime-specific pod configuration was available.

A concern with using annotations is that the stage1 could essentially be running the pod with escalated privileges. It might mean that at the kubelet side, pods with a stage1 annotation would need to be rejected if they did not also contain the `privileged=true` flag (however, the annotations wouldn't be enforceable from the api-server `--allow-privileged` side).

@yifan-gu @philips

**Comment by yifan-gu** [comment]
@bgrant0607 This raises the question about how can we add some runtime specific options to the pod spec effectively?

**Comment by bgrant0607** [comment]
@aaronlevy Please explain more about what this means and why we'd want it. 

cc @kubernetes/sig-node

**Comment by philips** [comment]
@bgrant0607 Two use cases:

- Have rkt use [kvm isolation](https://coreos.com/blog/rkt-0.8-with-new-vm-support/) instead of namespace/cgroups
- Have rkt use [less isolation](https://coreos.com/rkt/docs/latest/running-fly-stage1.html), essentially just a chroot, for running really privileged stuff like the kubelet

**Comment by philips** [comment]
@bgrant0607 Ping https://github.com/kubernetes/kubernetes/issues/23944#issuecomment-206691009

**Comment by aaronlevy** [comment]
To add a bit more detail to this request:

__From a selfish "I want this" perspective:__

This comes from the need to be able to run a kubelet pod using specific rkt runtime options (in this case, using a different stage1-image). This would currently be necessary for running a self-hosted kubelet with rkt as the container runtime.

For example:

Starting from a self-hosted kubelet proposal: https://github.com/kubernetes/kubernetes/pull/23343

1. Bootstrap kubelet (on host) starts with `--container-runtime=rkt`
1. Bootstrap kubelet starts getting pod definitions from api-server and running them using default stage1-image (namespace/cgroup isolation).
1. Bootstrap kubelet receives pod definition for a "self-hosted" kubelet -- which runs using a different `--stage1-image` (rkt-fly) due to different isolation needs (part of host namespaces).

__From a more general perspective:__

There might be some other options that would allow a self-hosted kubelet with rkt as the container runtime, potentially without needing to specify per-pod runtime options.

Possibly setting mount propagation in the spec (https://github.com/kubernetes/kubernetes/pull/20698), and creating a rkt stage1 that does not have systemd as pid1 in the running container (https://github.com/kubernetes/kubernetes/issues/23692) so hostPID works as expected.

However, it seems like container runtime configuration (potentially at the pod level) is going to be somewhat necessary no matter what. Some of the options in the pod spec are already runtime specific, and may not map well to various container runtimes. For example, what does "hostPID" mean when the runtime could be VM based (e.g. hyper or kvm isolation)? Or, how/why is some runtime configuration blessed, but potentially not others?

So I guess back to the originally posted (and selfish) issue: being able to specify a runtime configurable (stage1-image in this case) as part of the pod would allow for situations where we may need to change the isolation mechanics of a pod (in a concrete use-case: for self-hosting the kubelet).

**Comment by philips** [comment]
@aaronlevy What is an example of runtime configuration?

**Comment by aaronlevy** [comment]
I think the pod/container [securityContexts](https://github.com/kubernetes/kubernetes/blob/master/docs/design/security_context.md) are a good example of pod-based runtime configuration.

**Comment by bgrant0607** [comment]
Ref #17064

**Comment by bgrant0607** [comment]
cc @dchen1107

**Comment by bgrant0607** [comment]
@yifan-gu @philips For now, experimental runtime-specific options could be passed via annotations on the pod. Something like `rkt.alpha.kubernetes.io/image-stage: stage1`. It would be non-portable, though, and might be subsumed by future first-class API features. #17064 is a good place to discuss that issue.

**Comment by yifan-gu** [comment]
> @yifan-gu @philips For now, experimental runtime-specific options could be passed via annotations on the pod. Something like rkt.alpha.kubernetes.io/image-stage: stage1. It would be non-portable, though, and might be subsumed by future first-class API features. #17064 is a good place to discuss that issue.

I am happy to implementing something like this.

**Comment by yifan-gu** [comment]
@bgrant0607 But the problem for using annotation for stage1 image in rkt, as mentioned in https://github.com/kubernetes/kubernetes/issues/23944#issue-146443351, is that this could give users privilege without noticing the API server, and API server has no way to check and prevent it..

**Comment by aaronlevy** [comment]
@yifan-gu it seems like eventually this would be a good candidate for an admission controller that can validate runtime options (ex. the [admissions section](https://github.com/kubernetes/kubernetes/blob/master/docs/design/security_context.md#admission) of securityContext)

If the crashloop / events are clear that the reason a pod is failing to run is that a `privileged=true` context is required, that would seem reasonable enough. Another option might be to have something like an `--rkt-approved-stage1-images` flag on the kubelet which would restrict the set a user could specify. But if it is assumed that `--privileged` essentially means root already, not sure this is much extra protection.
