### ISSUE TITLE
e2e flake: `Generated release_1_2 clientset should create pods, delete pods, watch pods` with "Failed to observe pod deletion"

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#23952]
The e2e test `Generated release_1_2 clientset should create pods, delete pods, watch pods` is flaky. It often fails with the error `Failed to observe pod deletion` in the `kubernetes-e2e-gce` test suite.

Sample failures:
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/14347/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/14339/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/14338/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/14337/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/14332/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/14323/
* http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/14306/

Marking it P0 since it frequently blocks the merge queue.

**Comment by nikhiljindal** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
The pod is deleted with grace-period=30, but there is no guarantee that the pod is going to be deleted from etcd in 30s, thus the flake.

This piece of test is copied from the pod e2e test: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/pods.go#L380. In that test, the timeout is actually larger than 30s, because there is some extra logic (< 30s) between the time when a deletion is requested, and when the timer is started. 

Given that there is no flake reported for test in pods.go, I will fix this flake by extending the timeout to 60s.

**Comment by caesarxuchao** [comment]
This flake should have the same root cause as #21367.

**Comment by jlowdermilk** [comment]
ETA on fix? This is the most frequent cause of test flakes and submit queue blockage.

**Comment by caesarxuchao** [comment]
@mikedanese sent out https://github.com/kubernetes/kubernetes/pull/23999 as a temporary fix.

**Comment by bprashanth** [comment]
Hmm, happened in: 
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/34768/consoleFull
```
STEP: deleting the pod gracefully
STEP: verifying pod deletion was observed
E0407 15:21:53.022025   23791 iowatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
[AfterEach] [k8s.io] Generated release_1_2 clientset
```
Which looks like we're just not handling the watch cancellation properly.

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23541/kubernetes-pull-build-test-e2e-gce/34768/

**Comment by bprashanth** [comment]
@caesarxuchao does the timeout really fix the watch cancellation? (didn't look too deep at the pr)

**Comment by caesarxuchao** [comment]
> does the timeout really fix the watch cancellation?

I think so.

@mikedanese see bprashanth's last comment, the timeout occurs again.

**Comment by caesarxuchao** [comment]
Last failure occurs at 3:13:18pm, Apr. 7, Mike's fix is merged at 15:04:42, Apr. 7.
