### ISSUE TITLE
Dedicate a soaking cluster in gce Jenkins project to node team

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#23954]
We, node team needs a separate soaking cluster to validate a lot of features which is not pushed into upstream yet. For example, 
- Validating docker new release. Based on our previous validating experience, tons of docker issues are found at soaking stage. Currently there is no good way to do it without pushing the changes to upstream. 
- Validate a new image with different kernel config. 

cc/ @kubernetes/goog-testing @ixdy @spxtr 

We used to have one, and recently is torn down.

**Comment by dchen1107** [comment]
cc/ @kubernetes/goog-node

**Comment by dchen1107** [comment]
@spxtr I am assigning this one to you so that we can speed up our test cycle. Thanks!

**Comment by spxtr** [comment]
See [hack/jenkins/job-configs/kubernetes-jenkins/kubernetes-soak.yaml](https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/job-configs/kubernetes-jenkins/kubernetes-soak.yaml) for our soak configs. It's pretty straightforward to make a new entry.

**Comment by fejta** [comment]
@spxtr it is not at all obvious how one might update kubernetes-soak.yaml to control which docker release and/or kernel config is used.

**Comment by spxtr** [comment]
@dchen1107 In bc326af6daba9eece7441eac9feb4ee156a60dde I added a soak job for release 1.2. To add a new job you need to copy that commit and fill in your own details.

I'm not too sure how you configure your job to use a different docker version or kernel config. Is that just an environment variable? If so, set it under `job-env`. If it's something more complicated than that then let me know.

**Comment by dchen1107** [comment]
@spxtr and @fejta thanks for the instructions. I will follow those instruction and kick out the second soaking cluster first. Thanks!

**Comment by dchen1107** [comment]
@spxtr I noticed that we still have kubernetes-soak-continuous-e2e-gce-2 job running in our jenkins. Is there any difference between this one and kubernetes-soak-continuous-e2e-gce? Anyway I am going to add a new one dedicating to node team.

**Comment by spxtr** [comment]
There isn't a difference.

**Comment by spiffxp** [comment]
/sig node

/assign
going to close because I'm assuming the need's been fulfilled by now
