### ISSUE TITLE
kubectl ModifyConfig doesn't prevent concurrent access

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#23964]
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/config/config.go#L193

If multiple kubectl's run `kubectl set ...` at the same time, they might leave the file in a bad state. This is probably an edge case now, but if some of the ideas from #23066 get implemented, it could be a slightly worse problem.

@jlowdermilk @deads2k

**Comment by deads2k** [comment]
Just a note if someone tries to tackle this, locking order could become a problem.  The kubeconfig is merged from a list in `$KUBECONFIG`.  If you start trying to lock files and someone has two different orders, you could deadlock.  Not a likely problem, but it could happen.

I could probably be convinced that those people get the pain they asked for.

**Comment by fabianofranz** [comment]
We spotted this too, the kubeconfig file was left in a broken state after some concurrent access. Here is a snippet of how it ended up (last 7 characters of `client-key-data` repeated in the tail of the file):

```
(...)

client-key-data: (...)0tLS0tCg==
S0tCg==
```

**Comment by krousey** [comment]
Yay me. I'm going to see if I can create a lock file to prevent concurrent access. There will probably need to be more improvements after this, but it should at least stop the bleeding.

**Comment by lavalamp** [comment]
Adding to the milestone so we discuss in the burndown meeting.

**Comment by lavalamp** [comment]
Is a lock file sufficient, or will two kubectls just end up fighting and invalidating each other's tokens?

**Comment by lavalamp** [comment]
I guess that just means the lock file needs to be held over the entire read/refresh/write cycle.

**Comment by krousey** [comment]
I'm going to initially do it across the write cycle to at least prevent file corruption. Later, we should re-work it to do:

1. Read file and determine if need to update
2. Lock
3. Re-read to make sure.
4. write
5. release

**Comment by lavalamp** [comment]
That sounds OK as long as kubectls fighting still make progress. If they fight so hard they can't make progress, then it's probably not sufficient.

**Comment by krousey** [comment]
For the case that is bringing this up, the token is still refreshed in memory and everything continues on. If it failed to update the file, it will just try again next invocation.

**Comment by alex-mohr** [comment]
Status update: #28034 is PR, it's lgtm, per-PR tests have passed, and labelled retest-not-required.  It's waiting on submit-queue to merge it.  SQ is testing a different PR, so it'll be ~40 minutes before it looks at head and merges.   Alternative is a manual merge.

**Comment by roberthbailey** [comment]
Now that #28034 has merged can we close this?

**Comment by alex-mohr** [comment]
As far as I understand, yes.  Closing and @krousey can reopen if not.

**Comment by lavalamp** [comment]
Reopening to convince Eric to accept the cherrypick.

**Comment by krousey** [comment]
This was fixed and reopened for a cherry-pick that did not happen.
