### ISSUE TITLE
kube-addons service failed to start on some OS distribution(Atomic as an example)

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#23973]
When I kube-up a kubernetes cluster, I find that kube-addons service failed to execute on the master node due the logs below:

```
Apr 07 04:09:39 kubernetes-master-1-6278.example.com kube-addons.sh[8786]: error validating "STDIN": error validating data: mkdir .kube: permission denied; if you choose to ignore these errors, turn validation off with --validate=false
Apr 07 04:09:39 kubernetes-master-1-6278.example.com kube-addons.sh[8786]: == Failed to start /etc/kubernetes/addons/namespace.yaml in namespace  at 2016-04-07T04:09:39+0000. 92 tries remaining. ==
```

It shows the `mkdir .kube` failed due to the permission denied. After a search here, I see this one is very related: https://github.com/kubernetes/kubernetes/issues/17340

And the last comment mentioned it is fixed by https://github.com/kubernetes/kubernetes/pull/14087.

But cases become a little different for a systemd service, since `os.Getenv('HOME')` would return an empty which causes the schema is written to `/.kube` and unluckily, on some OS, a dir creation on root dir is not allowed, Atomic as an example(by default it is now allowed, needs to hack by `chattr -i /`).

so I would suggest to add an environment variable entry in the kube-addons.service.

cc @mikedanese @bgrant0607 @brendandburns and cc @chengyli who helps me find the root cause.

**Comment by bgrant0607** [comment]
cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
Is there a script you are running to reproduce?  It looks like the referenced fix makes an update to the salt scripts, but I didn't think we had support for Salt on atomic for kube?

**Comment by zhouhaibing089** [comment]
@derekwaynecarr we installed salt on atomic.

@bgrant0607 I am thinking it is not tied to atomic but any systemd os, since it is not an intended behavior to write `/.kube`, `/root/.kube` is the expected one.

**Comment by derekwaynecarr** [comment]
I assume you are wanting to run a more recent version of kube than what
comes with atomic?

/cc @eparis

**Comment by zhouhaibing089** [comment]
yeah, we are running release-1.2 code along with customization from our side.

/cc @ashw7n

**Comment by mikedanese** [comment]
Does the root user have a home directory in /etc/passwd on atomic?

**Comment by gouyang** [comment]
I've  the same problem on Atomic host.

> Does the root user have a home directory in /etc/passwd on atomic?
```
$ cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
cloud-user:x:1000:1000:Cloud User:/home/cloud-user:/bin/bash
```
