### ISSUE TITLE
import-boss rule should support back-slash

### ISSUE THREAD

**Issue by adohe** [kubernetes/kubernetes#23979]
@lavalamp I think in the current import-boss, we can't use back-slash in rules to do some kind regex check, [https://github.com/kubernetes/kubernetes/blob/master/cmd/libs/go2idl/import-boss/generators/import_restrict.go#L214](https://github.com/kubernetes/kubernetes/blob/master/cmd/libs/go2idl/import-boss/generators/import_restrict.go#L214), I am not so sure whether we should support this, if so, that's should be easy enough to do.

**Comment by lavalamp** [comment]
Only the selector is a regexp, the allowed/forbidden sections are prefixes. Can you describe a scenario that doesn't work for?

**Comment by AdoHe** [comment]
as you comment in this PR #23521 
```
You can add just / as an allowed prefix.
```
IIUC, you mean add back-slash as an allowed prefix, so I changed the `.import-restrictions` like this:
```
{
  "Rules": [
    {
      "SelectorRegexp": "k8s[.]io",
      "AllowedPrefixes": [
        "/"
      ],
      "ForbiddenPrefixes": [
        "k8s.io/kubernetes/pkg/api/errors"
      ]
    }
  ]
}
```
then I ran `hack/verify-import-boss.sh` and just get many errors, every single import is not allowed, as it can not match any allowed prefixes.

**Comment by lavalamp** [comment]
Heh. Sorry, I definitely misspoke there. I think if I'd thought about it I would have said to use "" as the prefix, because that is a prefix of everything. I was thinking "/" was a prefix of everything when I wrote that, because apparently I was confusing import names with file paths. :)

**Comment by AdoHe** [comment]
@lavalamp thanks for explanation :) 
But I found another problem about import-boss, it seems when we analyze imports for a package, not only we consider the directly import, but also we consider some deep level imports, as I found even there is no direct import of `pkg/api/errors` in `pkg/storage`, in the final import array which import-boss gets, there is still `pkg/api/errors`. is this intended or I am just wrong?

**Comment by lavalamp** [comment]
Yes, this is intended :)
