### ISSUE TITLE
bindata for examples, docs, and testing the docs

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#23987]
Kubectl.go, examples.go, and other e2e tests need the repository root.  Overall, We have ~ 30 different dependencies (`It("...")`) in the e2es referencing files from examples/ docs/ ...  This is specified via `repo-root` at the moment.

**Problem**
- This makes the shipped binary `e2e.test` unusable for `Conformance` testing,  since some Conformance specs rely on files that ship w/ kube.
-  This also forces hacky bootstrappy things like needing to make a tarball, clone a repo, check out a commit -  just to run the e2es.

**Goal**

These can all be eliminated permanantly, making the binary completely self sufficient for e2e testing.

**Solution**

Looks like its easy to serialize docs/examples as code: 

```
➜  kubernetes git:(kubectl-files) ✗  ~/Development/gopath/bin/go-bindata -o docs.go ./docs 
➜  kubernetes git:(kubectl-files) ✗  ~/Development/gopath/bin/go-bindata -o examples.go ./examples
➜  kubernetes git:(kubectl-files) ✗ ls -altrhy docs.go 

```

and you get some minified go files...

```
➜  kubernetes git:(kubectl-files) ✗ ls -altrh docs.go 
-rw-r--r--  1 jayunit100  staff    74K Apr  7 14:03 docs.go
➜  kubernetes git:(kubectl-files) ✗ ls -altrh examples.go 
-rw-r--r--  1 jayunit100  staff    52K Apr  7 14:03 examples.go
```

Then you can call functions on those files in the tests, telling them to create the assets, by calling functions in the generated files that recreate the static files:

```
107 
108 func examplesReadmeMd() (*asset, error) {
109         bytes, err := examplesReadmeMdBytes()
110         if err != nil {
111                 return nil, err
112         }
113 
114         info := bindataFileInfo{name: "examples/README.md", size: 2368, mode: os.FileMode(420), modTime: time.Unix(1458824586, 0)}
115         a := &asset{bytes: bytes, info: info}
116         return a, nil
117 }
```

Should this be part of the build, rather than needing `--repo-root` for the e2es ? That way they just bootstrap themselves using the `Asset(...)` thingy. 

cc @kubernetes/sig-testing  .....

**Comment by jayunit100** [comment]
This would allow us to 
- easily write doc/examples validation unit tests in go
- easily reference docs in e2es unit tests (we *already* do this alot, so its nothing new) and delete "repo root" args.

**Comment by timothysc** [comment]
IMHO we should only start with the [Conformance] tests.  A lot of the other data in examples still needs to move out of the main repository this cycle.

**Comment by jayunit100** [comment]
k diving back into this .  current status is that i dont know how CI is supposed to be installing the go-bindata stuff

**Comment by ixdy** [comment]
Why are we making `test/e2e/e2e.test` the deliverable for conformance tests, rather than `kubernetes.tar.gz`?

The e2e tests currently have dependencies on `test/e2e/testing-manifests` and `test/images`, too. Are we going to `go-bindata`-ize them too?

**Comment by jayunit100** [comment]
We can, but as per the comment above, the priority is to get Conformance tests working without external deps.  That paves the way for everything else (without major  forklifting of the whole test suite )

**Comment by spiffxp** [comment]
/sig testing
/priority awaiting-more-evidence
I still think a single test binary, nothing more, would be a good goal to strive for.  I'm unsure how much of a pain point this is today
