### ISSUE TITLE
Rollout history not maintained when updated `kubectl edit`

### ISSUE THREAD

**Issue by deech** [kubernetes/kubernetes#23989]
I have an initial deployment I created with `kubectl create -f deployments/blah.yaml --record`. When I look at the rollout history with `kubectl rollout history deployment/blah`, I see:
```
REVISION        CHANGE-CAUSE
1               kubectl create -f deployments/blah.yml --record
```

I then use `kubectl edit deployments/blah` and update the number of replicas. This successfully scales up/down but when I do `kubectl rollout history deployment/blah` I only see: 
```
REVISION        CHANGE-CAUSE
1               kubectl edit deployments/blah
```

Manually updating the Revision # in the meta-data does nothing. I also tried `kubectl edit deployments/blah --record`but got similar results.

**Comment by AdoHe** [comment]
@kubernetes/kubectl

**Comment by janetkuo** [comment]
@deech this is expected behavior. The Deployment only create a new revision (i.e. another Replica Set) when you update its pod template. Scaling it won't create another revision.

**Comment by kargakis** [comment]
The only thing apart from the replicas and the resource version of the deployment that should change is its generation.

**Comment by deech** [comment]
Great. Thanks! I guess I just misunderstood the feature. Will close the issue.

**Comment by janetkuo** [comment]
@deech Thanks for your feedback on this! I've updated the document to clarify this  http://kubernetes.io/docs/user-guide/deployments/#rolling-back-a-deployment
