### ISSUE TITLE
Add some troubleshooting docs to the DNS addon README.md

### ISSUE THREAD

**Issue by timbunce** [kubernetes/kubernetes#23981]
The [cluster/addons/dns/README.md](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/README.md) has a section for "How do I configure it?" and one for "How do I test if it is working?" which ends with "If you see that, DNS is working correctly". But what if you don't see that?

The DNS addon is one of the first that novices are likely to try to use, along with dashboard, and it's also a common source of problems. (There are [many issues with dns in the title](https://github.com/kubernetes/kubernetes/issues?utf8=✓&q=is%3Aissue+is%3Aopen+in%3Atitle+dns+)).

It would be helpful if the docs had something like a Troubleshooting section pointing out how to query relevant logs and what's expected to be seen in them.

**Comment by paralin** [comment]
Isn't the DNS Plugin pretty much a standard part of any cluster at this point?

**Comment by vishh** [comment]
cc @kubernetes/sig-network

**Comment by bprashanth** [comment]
There are a few different ways dns can fail (can't contact apiserver, can't talk between containers in a pod so nslookup on kube2sky fails, service vips are 172 and pod ips are 10-dot and we have the wrong masq rule etc).  Some of thse a are "normal" networking setup problems that manifest as DNS. still makes sense adding a section with some links, and some troubleshooting tips. 

Re: logs, you should be ablet to run kubectl logs on containers in kube-dns.

**Comment by timbunce** [comment]
@paralin, you're right that DNS is included now, and most of my frustrations do stem from pre-1.2.0 experiences.

I agree with @bprashanth though, that "a section with some links, and some troubleshooting tips" would still be useful. Both for helping people experiencing actual DNS problems, and to help those experiencing other problems that happen to manifest as DNS problems (so DNS doesn't get the blame and people can get closer to the root cause more quickly).

**Comment by timbunce** [comment]
Looking at the [Deploying DNS](http://kubernetes.io/docs/getting-started-guides/docker-multinode/deployDNS/) page again I notice that the instructions in "Replace the corresponding value in the template and create the pod" aren't very clear to a novice (like me).

The command `kubectl create -f ./kube-system.yaml` refers to a `./kube-system.yaml` file without saying where that has come from. Someone following instructions like those in [Running Kubernetes Locally via Docker](http://kubernetes.io/docs/getting-started-guides/docker/) won't have a copy of ./kube-system.yaml handy. I presume that's referring to [this file](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/kube-system.yaml) (the only kube-system.yaml in the source tree).

Since that file does nothing special, couldn't the command be changed to `kubectl create namespace kube-system`?

p.s. It didn't seem worth creating an extra ticket for this. Let me know if you'd prefer one.

**Comment by girishkalele** [comment]
@MrHohn Have a look at the docs for the DNS addons and add more details as requested.

**Comment by MrHohn** [comment]
This should be closed by kubernetes/kubernetes.github.io#1449.
