### ISSUE TITLE
Deploy HA Master cluster (e.g. cluster with 3 master) using get.k8s.io

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#23997]
This feature would be awesome!

Do we have plan for doing that?

Regards

**Comment by vishh** [comment]
cc @kubernetes/sig-cluster-federation @kubernetes/goog-control-plane

**Comment by quinton-hoole** [comment]
Dupe of #21124.  We don't have anyone assigned to do this for v 1.3 (~07/2016), but would welcome community contributions.

**Comment by mikedanese** [comment]
Oops fumble fingers.
