### ISSUE TITLE
PR bot should immediately remove comments it adds, for some comments

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#24007]
Comments that the PR bot adds solely to trigger email notification of a label change, should be immediately deleted by the bot after it adds them.

I have no idea what team to assign this to...

cc/ @thockin @lavalamp

**Comment by thockin** [comment]
@eparis

**Comment by davidopp** [comment]
(Motivation, of course, is to avoid having PR threads that are 90% bot comments...)

**Comment by eparis** [comment]
This should really be an issue over in github.com/kubernetes/contrib/   that's where (some of) the bots live.

Lets make a list of which comments we want deleted immediately.

- Label size.
- Needs rebase.
- @k8s-bot test this

I don't want to make it all comments. There are way too many times people have asked me "Why did the bot add 'do-not-merge'?" and I can just link them the comment 2 lines above which tells exactly why....

**Comment by thockin** [comment]
"Test this" with an issue is also useful, isn't it?

**Comment by thockin** [comment]
OK to test

Add to whitelist

**Comment by eparis** [comment]
I was envisioning deleting the `@k8s-bot test this` added by the bot. (every 48 hours after LGTM, when retesting right before merge) not those added by users (with an issue)

After LGTM the bot will add `ok to test`, that one I can remove.

The request to `add to whitelist` comes from the jenkins bot. And in that I am clueless...

**Comment by eparis** [comment]
@thockin @davidopp any interest in a review (I'm trying to not just self merge all my own bot changes).  This deleted hundreds and hundreds of comments.

**Comment by davidopp** [comment]
Looks like @thockin reviewed it since your last message:
https://github.com/kubernetes/contrib/pull/765#issuecomment-209183559
