### ISSUE TITLE
Accessing dashboard results in i/o timeout

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kubernetes#24002]
I'm starting my cluster with the following:

```
export KUBE_AWS_ZONE=us-east-1b
export NUM_NODES=2
export MASTER_SIZE=t2.small
export NODE_SIZE=t2.small
export AWS_S3_REGION=us-east-1
export AWS_S3_BUCKET=cw-users

export KUBERNETES_PROVIDER=aws; curl -sS https://get.k8s.io | bash
```

The cluster is setup with no errors. I can access the master with the IP printed out by the script. However, when I attempt to access /ui I receive the following error:

```
Error: 'dial tcp 10.244.0.6:9090: i/o timeout'
Trying to reach: 'http://10.244.0.6:9090/'
```

Listing the kube-system pods shows me that something is wrong with `kibana-logging`:

```
NAME                                                 READY     STATUS             RESTARTS   AGE
elasticsearch-logging-v1-kmiom                       1/1       Running            0          7m
elasticsearch-logging-v1-oljhw                       1/1       Running            0          7m
fluentd-elasticsearch-ip-172-20-0-151.ec2.internal   1/1       Running            0          7m
fluentd-elasticsearch-ip-172-20-0-152.ec2.internal   1/1       Running            0          7m
heapster-v1.0.2-qvya4                                2/2       Running            0          7m
kibana-logging-v1-8ciwe                              0/1       CrashLoopBackOff   1          48s
kube-dns-v11-0uz05                                   4/4       Running            0          7m
kube-proxy-ip-172-20-0-151.ec2.internal              1/1       Running            0          7m
kube-proxy-ip-172-20-0-152.ec2.internal              1/1       Running            0          7m
kubernetes-dashboard-v1.0.0-0y0mp                    1/1       Running            0          7m
monitoring-influxdb-grafana-v3-16sii                 2/2       Running            0          7m
```

Logs for kibana-logging:

```
{"@timestamp":"2016-04-07T22:18:12.301Z","level":"error","message":"Request Timeout after 1500ms","node_env":"production","error":{"message":"Request Timeout after 1500ms","name":"Error","stack":"Error: Request Timeout after 1500ms\n  at [object Object].<anonymous> (/kibana-4.0.2-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)\n"}}
{"@timestamp":"2016-04-07T22:18:12.303Z","level":"fatal","message":"Request Timeout after 1500ms","node_env":"production","error":{"message":"Request Timeout after 1500ms","name":"Error","stack":"Error: Request Timeout after 1500ms\n  at [object Object].<anonymous> (/kibana-4.0.2-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)\n"}}
```

I don't know if the kibana-logging errors have anything to do with my dashboard i/o errors or if they are unrelated.

**Comment by yissachar** [comment]
I've changed the region to one that I haven't used before and the dashboard shows up correctly. I suspect that `kube-down` from a previous attempt didn't properly clean itself up and there is something lying around still that is causing a conflict.

**Comment by bryk** [comment]
Problem solved? So you see any action items for the UI team?

**Comment by yissachar** [comment]
The problem still exists in `us-east` for me. This isn't an out of the box problem, but rather seems to be triggered by some sequence of `kube-up` and `kube-down`. I'm not particularly sure what that sequence is at the moment.

This definitely isn't a UI issue though - deploying my own services results in the same error. It seems possibly network related.

**Comment by yissachar** [comment]
Comparing the working region to the non-working one, I see that the proper setup has a route table with entries pointing to the master node, as well as to the minions. In my broken setup only the master node has an entry. The entries for `10.244.0.0/24` and `10.244.1.0/24` which should map to the minion nodes, are missing. This lines up nicely with the error message posted above:

```
Error: 'dial tcp 10.244.0.6:9090: i/o timeout'
Trying to reach: 'http://10.244.0.6:9090/'
```

I've tried to add these routes manually but it doesn't help. I'm also still not sure why `kube-up` would fail to add these routes in one region, but add them correctly in the other.

**Comment by yissachar** [comment]
Can someone with more knowledge of the `kube-up` process point me to where the minion node route tables are added?

**Comment by yissachar** [comment]
I found that the minion node route tables are being added by the createRoute function in https://github.com/kubernetes/kubernetes/blob/c6e995a824094a96f7d43a25e897283f83a12997/pkg/cloudprovider/providers/aws/aws_routes.go#L112. Seeing what that does I figured out that the Source/Dest check was enabled on my minions, even though it shouldn't have been.

Now, I can manually fix my cluster after bringing it up by doing the following:

- Add a route table entry for each minion
- Disable Source/Dest checking on each minion

I'm still trying to figure out where createRoute is called from and why it fails to properly handle the above steps automatically.

**Comment by yissachar** [comment]
I found that the minion node route tables are being added by the createRoute function in https://github.com/kubernetes/kubernetes/blob/c6e995a824094a96f7d43a25e897283f83a12997/pkg/cloudprovider/providers/aws/aws_routes.go#L112. Seeing what that does I figured out that the Source/Dest check was enabled on my minions, even though it shouldn't have been.

Now, I can manually fix my cluster after bringing it up by doing the following:

- Add a route table entry for each minion
- Disable Source/Dest checking on each minion

I'm still trying to figure out where createRoute is called from and why it fails to properly handle the above steps automatically.

**Comment by yissachar** [comment]
I figured out that createRoute is called from kube-controller on the master, when I had been looking at the minion logs the whole time. Knowing that it was trivial to look at the master logs for kube-controller and see this message:

```
Couldn't reconcile node routes: error listing routes: found multiple matching AWS route tables for AWS cluster: kubernetes
```

As it turns out, I had attempted to run `kube-up` previously using an existing VPC. I had thought that I had cleaned up the effects of this but there was still a `kubernetes` tag lying around on my existing route table. `createRoute` expects only a single route table with that tag and so bailed out, leaving my networking in an incomplete state. After removing this tag from my other route table, the networking works properly, and I am able to access the dashboard as expected.

**Comment by bryk** [comment]
Can you maybe improve documentation about this or send a PR to fix `kube-up`? You've done a good investigation here which is worth contributing :)

**Comment by yissachar** [comment]
I'm not sure how much the documentation can be improved; it's all there, but just not so easy for a Kubernetes newcomer to know where to look. However, the linked `kube-up` issue I've created would really have saved me a lot of time by quickly pointing me in the right direction.

**Comment by nebirhos** [comment]
Hi guys!

I'm getting the same error with a fresh installation on bare-metal Ubuntu machines.

I'm following [this guide](http://kubernetes.io/docs/getting-started-guides/ubuntu/) with Kubernetes v1.2.2, etcd v2.2.5 and flannel v0.5.5.

Kubernetes 1.1.8 used to run smoothly with the same configurations.

**Comment by tweakmy** [comment]
I tried to access via the apiserver through
http://kube-master:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/

I got the same error on kubernetes v1.2.0

**Comment by bryk** [comment]
@nebirhos @tweakmy 

How about other addons? Do they work? E.g., heapster? I guess this is problems with the cluster setup guide or your env. Dashboard UI works nicely with typical Kubernetes setups

**Comment by tweakmy** [comment]
I am using calico v0.15 as per documented in the http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/

heapster are working via nodeport, the insecure way.

**Comment by bryk** [comment]
So you say that when you access the Dashboard UI through nodeport, it works? And when through apiserver proxy, it does not?

**Comment by tweakmy** [comment]
Yes. That is correct

**Comment by nebirhos** [comment]
@bryk it seems a flannel setup error indeed, no pod is reachable from a different node.

Don't know where to look though, the only suspicious thing is the lack of `vethXXX` interface on master node.

**Comment by bryk** [comment]
@nebirhos Can you report an issue to the documentation repo? This looks like a problem many people encounter, so I guess you're doing this correct, but the guide is invalid. It is not the first time I see people reporting problems to me while using ubuntu-based setup.

**Comment by tweakmy** [comment]
Hi there, I have also found the problem to my issue as well. It is not quite because of configuration (http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/) but it was dodgy on my kvm switch. It was doing nat instead of forwarding. 

I was using tcpdump port 9090 on both node01 and node02 and found out that node02 had nat request and response (from kvm switch) and my kvm switch got confused what to do after getting the response. 

I end up adding a new interface that does only forwarding and switch all my endpoints for kubelet/calico to the ip address of the second interface and reserve the first interface for internet access.

I hope this would help other people to troubleshoot.

**Comment by remoe** [comment]
i had the same with coreos 1185, kube 1.4.5, kube-dashboard 1.4.2 after shutdown/restart of master (one api-server). It was working after shutdown all nodes and restart of the master and nodes.
