### ISSUE TITLE
Service IP is not reachable because the bridge netfilter module is not loaded

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#24019]
- Container runtime: rkt
- OS: coreos
- Cloud: gce
- network plugin: kubenet

With the above config, the service IP is not reachable inside a pod. We tracked the issue, it turns out that it's because the netfilter module is not loaded. (in the docker's case, however, docker loads the module).

Now we know the reason, the next question is what's the best place to put the code that enables the module?
In the bridge plugin? or in the rkt runtimes code?

cc @kubernetes/sig-node @kubernetes/sig-network @sjpotter @steevj @jonboulle

**Comment by bprashanth** [comment]
I'd say plugin https://github.com/kubernetes/kubernetes/issues/2401

**Comment by yifan-gu** [comment]
Fixed by #24107
