### ISSUE TITLE
Load netfilter module in kubenet for bridge plugins

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#24018]
So Services work. 
Can't hurt to load bridge too (though that can happen in the CNI plugin as well)? Just: 
```
$ modprobe -a bridge br-netfilter
```
ref https://github.com/kubernetes/kubernetes/issues/23657
@yifan-gu @dcbw @freehan

**Comment by AdoHe** [comment]
If we are using default bridge network mode, I think libnetwork bridge driver has already done this:
[https://github.com/docker/libnetwork/blob/master/drivers/bridge/bridge.go#L375](https://github.com/docker/libnetwork/blob/master/drivers/bridge/bridge.go#L375)

**Comment by bprashanth** [comment]
This is not about libnetwork but about kubenet and the bridge CNI plugin. When won't be invoking both libnetwork and kubenet at the same time.

**Comment by thockin** [comment]
Curious.  We check for it but do not modprobe it in kube-proxy.

We should probably modprobe it in kubenet and set
the net/bridge/bridge-nf-call-iptables sysctl (which already do in
kube-proxy).  It's strictly a function of the network driver, not
kube-proxy.

**Comment by bprashanth** [comment]
> We should probably modprobe it in kubenet and set
the net/bridge/bridge-nf-call-iptables sysctl (which already do in
kube-proxy). 

We moved it out of kube-proxy and into the no-op plugin because it only makes sense in bridged networks.

I'd say the iptables part is under kubenet's purview and the bridge modprobe is under the CNI plugin's jurisdiction, but it can't hurt to do both in kubenet.

**Comment by yifan-gu** [comment]
Either let bridge plugin or kubenet do it sounds fine to me. Let kubenet do it seems to be a little less work.

**Comment by bprashanth** [comment]
I think the reason to let bridge plugin do modprobe bridge is so it outside Kube :)
I agree bridge plugin should probably not care about iptables, because it has no idea if the caller cares about iptables

**Comment by yifan-gu** [comment]
@bprashanth Yeah, but in kubenet's case. Users can carry their own bridge binary, right? So if we do it in kubenet driver code, does that seem to be more reliable?

**Comment by thockin** [comment]
We should do it everywhere.  Belts and suspenders.

**Comment by dcbw** [comment]
> This is a little clunky without an Init function (CNI still doesn't have that right?).

No, it doesn't.  Is the netfilter stuff really needed before any pods are born though?

**Comment by bprashanth** [comment]
Clunky because we're loading a module for every pod, and if we fail to do so once for some unrelated reason the pod won't start. If we fail to do so for 10s for same unrealted reason the pod will probably enter crash loop backoff or something. 

Periodically checking the module is loaded makes sense, I don't think a failure to *check* should block pods starting though. We still have an init and that's good enough, though.

**Comment by dcbw** [comment]
> Clunky because we're loading a module for every pod

Isn't it once for the first pod ever run on the machine?  This isn't done inside the pod net namespace...
