### ISSUE TITLE
Create a release process/automation roadmap

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#24029]
There are lots of known release process/automation issues. We should prioritize them and create a roadmap we can execute against.

cc @zmerlynn @roberthbailey @ihmccreery @quinton-hoole @lavalamp @eparis @dchen1107

**Comment by david-mcmahon** [comment]
https://docs.google.com/document/d/1OhAjw5YIb_Z0z9-r5QiVovjF1BDOzfo45CgcptVfTgI/edit#
