### ISSUE TITLE
AWS: kube-down doesn't delete all resources

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kubernetes#24028]
After running kube-down I consistently see that it leaves the following around:
- dhcp-options
- key-pair

**Comment by ajohnstone** [comment]
```
This should take care of the dhcp will submit a PR

aws --output=text ec2 describe-dhcp-options --filters Name=tag:KubernetesCluster,Values=kubernetes-services --query DhcpOptions[].DhcpOptionsId |  tr "\t" "\n" | sed 's/,//g' | xargs -n1 --no-run-if-empty echo aws ec2 delete-dhcp-options --dhcp-options-id |bash
```

**Comment by ajohnstone** [comment]
I'm not sure whether its wise to clean up the key-pairs.

**Comment by activars** [comment]
👍

**Comment by scottstensland** [comment]
Please progress the delete of DHCP Options Sets  by kube-down.sh     uncouple this change from dealing with key-pairs  ...  every cluster launch/teardown is leaving dangling DHCP Options Sets
