### ISSUE TITLE
DaemonSets unavailable for v1.2.0-alpha.8

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/kubernetes#24037]
```
$ kubectl create -f api-gateway-ds.yaml --validate=false
unable to decode "api-gateway-ds.yaml": no kind "DaemonSet" is registered for version "v1"
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.8", GitCommit:"5918967a86489460846af94a5c393d971337be29", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.8", GitCommit:"5918967a86489460846af94a5c393d971337be29", GitTreeState:"clean"}
```

In v1.1 we could enable DaemonSets with the apiserver option --runtime-config="extensions/v1beta1/daemonsets=true". This does not work for v1.2.0-alpha.8. 

If I am correct, in v1.2 DaemonSets should be enabled by default, but they aren't yet.

**Comment by andrejvanderzee** [comment]
Same behavior for Kubernetes v1.2.2

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}

**Comment by bgrant0607** [comment]
@andrejvanderzee The message indicates you are using the wrong API version. DaemonSet is in extensions/v1beta1. It is enabled by default in 1.2.x, so that's not the problem.

**Comment by andrejvanderzee** [comment]
@bgrant0607 That is what I expected too, but it is not enabled by default in V1.2.2:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}

$ curl localhost:8080/apis/extensions/v1beta1
{
  "kind": "APIResourceList",
  "groupVersion": "extensions/v1beta1",
  "resources": [
    {
      "name": "daemonsets",
      "namespaced": true,
      "kind": "DaemonSet"
    },
...
}

$ curl localhost:8080/version
{
  "major": "1",
  "minor": "2",
  "gitVersion": "v1.2.2",
  "gitCommit": "528f879e7d3790ea4287687ef0ab3f2a01cc2718",
  "gitTreeState": "clean"
}

**Comment by andrejvanderzee** [comment]
@bgrant0607 This is what CentOS Atmoic Host offers via the apiserver:

[centos@love-master-01 ~]$ curl localhost:8080/
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/resetMetrics",
    "/swaggerapi/",
    "/version"
  ]
}

Are there any plans to move the DaemonSets out of the extensions into groupVersion v1?

**Comment by bgrant0607** [comment]
@andrejvanderzee DaemonSet is going to be in extensions/v1beta1 for at least 1.2 and 1.3. 

What is the problem? The output you show confirms that DaemonSet is present and enabled.

**Comment by andrejvanderzee** [comment]
@bgrant0607 On CentOS Atomic Host the /apis/extensions endpoint is removed, like shown in my comment above, so we are unfortunately unable to use it (for at least 1.2 and 1.3).

**Comment by bgrant0607** [comment]
@andrejvanderzee I suggest asking on stackoverflow.
