### ISSUE TITLE
kubernetes1.2 build error

### ISSUE THREAD

**Issue by Huimintai** [kubernetes/kubernetes#24033]
Hi，when I build kubernetes1.2，It makes an error like this：
`# go build `
`# k8s.io/kubernetes/pkg/util`
`../../../../pkg/util/throttle.go:59: t.limiter.Capacity undefined (type *ratelimit.Bucket has no field or method` `Capacity, but does have ratelimit.capacity)`
`../../../../pkg/util/throttle.go:60: t.limiter.Available undefined (type *ratelimit.Bucket has no field or` `method Available)`
It puzzled me ,who can help me?Thanks a lot.

**Comment by vishh** [comment]
Kubernetes vendors all its dependencies and it does not confirm to `go build` expectations. I'd recommend running `make` instead.

**Comment by Huimintai** [comment]
OK,Thank you:)
