### ISSUE TITLE
K8sm with multiple mesos master

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#24043]
Is there a way to specify multiple mesos masters when starting `km apiserver`? It seems the config file that `--cloud-config` expects is only expecting to receive one mesos master IP+port.

cc @jdef @sttts @karlkfi

**Comment by huang195** [comment]
Also, it seems that both apiserver and controller-mgr will take the `--cloud-config` parameter, but scheduler takes `--mesos-master` parameter directly, where a list of zookeepers that the mesos masters use for leader election can be passed in the format of `zk://...`. 

After going through the code, it seems that `--cloud-config` param passed to the apiserver and controller-mgr are used only for initialization purposes to set up what kube wants a `cloudprovider` to look like, but if mesos lead master changes later, it won't impact apiserver and controller-mgr whatsoever. So this means whatever we set to `mesos-master` field does not matter as long as it is one of the mesos masters.  Scheduler, on the other hand, as is passed a list of zk nodes, will be able to detect mesos lead master changes. Just want to verify that this is the proper way of setting up a HA k8sm on top of a HA mesos cluster. Thanks in advance!

**Comment by jdef** [comment]
vagrant@node-1:~/mesosphere-kubernetes$ cat ~/mesos-cloud.conf
[mesos-cloud]
  mesos-master          = zk://10.2.0.5:2181,10.2.0.6:2181,
10.2.0.7:2181/mesos

**Comment by huang195** [comment]
@jdef so it also take `zk://...` list of masters. Thanks!
