### ISSUE TITLE
Rename release-note-* and cherrypick- labels to conform to category/sub-category norm

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#24057]
Most labels in kubernetes follow a `category/sub-category` form. Both `release-notes-*` and `cherry-pick-*` do not. I verified that if you `edit` a label (instead of `delete`/`create`) the label is updated on existing PRs/Issues.
- [ ] Update documentation to discuss `cherrypick/*` and `release-note/*` instead of what we have today (@david-mcmahon)
- [ ] Update bot code to use the new label names (@eparis)
- [ ] Update https://github.com/kubernetes/kubernetes/labels (@eparis)
- [ ] Launch the bot with the new code (@eparis)
- [ ] PSA to community about change

cc @bgrant0607 @liggitt @david-mcmahon

**Comment by bgrant0607** [comment]
Makes sense to me.

**Comment by spiffxp** [comment]
/sig release
/sig contributor-experience
/priority important-soon

yes, if we're doing the prefix thing, we should do this, and document it
ref #34255

**Comment by spiffxp** [comment]
/remove-lifecycle stale
This would be a good thing to get done for 1.10 @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort

**Comment by spiffxp** [comment]
This seems like it should be more of a kubernetes/community issue than k/k, but yeah this would fix one of our larger broken windows re: non-prefixed labels.  If we don't do it _soon_ within the 1.11 cycle though I would punt to 1.12

**Comment by spiffxp** [comment]
/area github-management
/remove-lifecycle stale
The release note and cherrypick processes could both use an overhaul to the point where this issue may be irrelevant.  But if I do overhaul them, I want label names to conform as part of the overhaul.

**Comment by nikhita** [comment]
/remove-lifecycle stale

Is this still something we want? If yes, I can help with it!

**Comment by nikhita** [comment]
I am not sure if it makes sense to update the cherry-pick labels today. Currently, the cherry-pick labels are `cherry-pick-approved` (manually added by the patch manager) and `do-not-merge/cherry-pick-not-approved` (added automatically by prow), which sound fine to me.

I have created https://github.com/kubernetes/test-infra/pull/10627 to update the release note labels.

**Comment by nzoueidi** [comment]
/remove-lifecycle rotten

Do we still want to have this? If so, I might tackle some points from the above :)

**Comment by riking** [comment]
It looks like the PRs were closed with a decision not to do this. Additionally, this seems like a multi-repository issue and should be discussed somewhere more appropriate for that.
