### ISSUE TITLE
API field name wrong: DaemonEndpoint "port" field

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24064]
Tag is malformed. "port" was intended, but we're getting "Port".

https://github.com/kubernetes/kubernetes/blob/421249785d15fb7af203a34fd3054a4765b96b67/pkg/api/v1/types.go#L2052

@bgrant0607 

This seems like something we could catch automatically in the future.

**Comment by bgrant0607** [comment]
See #23660

**Comment by bgrant0607** [comment]
Now officially `Port`. This is something a linter could have caught.
