### ISSUE TITLE
genericapiserver: move flag install to common place

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24062]
genericapiserver should have a function to install common flags. People don't have to use it if they don't want to install all of its flags, of course--we should factor it such that it's easy to get the set of flags you want.

e.g., s.InstallUniversalFlags(), s.InstallEtcdStorageFlags(), etc

@nikhiljindal

**Comment by sttts** [comment]
We have a number of `*Options` structs which carry flags as well. They can be manually added to a custom apiserver. Moreover, there is a `RecommendedOptions` struct for the default set.

Closing.
