### ISSUE TITLE
kubectl delete all does not deleted all API objects

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#24065]
`kubectl delete all -l foo=bar` currently deletes only pods and services. Ideally we can suggest users to run `kubectl delete all` following a `kubectl run`, but that is not possible today.

@bgrant0607 suggested that using the discovery API is the correct way to fix this since that will help delete resources that do not belong to Kubernetes core. 

cc @kubernetes/kubectl 

A short term fix to delete deployments might be useful right away.

**Comment by kargakis** [comment]
dupe https://github.com/kubernetes/kubernetes/issues/23215
