### ISSUE TITLE
Convert ns/name to --namespace=ns

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#24078]
Minor improvement in UX maybe?
```
$ kubectl get pod kube-system/pod-name
```

**Comment by thockin-cc** [comment]
We have semi-ambiguous syntax because 'get pod/foo' is also valid.  We
should have define syntax for this early on.

**Comment by zhouhaibing089** [comment]
+1 for the UX improve.

**Comment by bprashanth** [comment]
get pod/foo != get pod ns/foo ?

**Comment by zhouhaibing089** [comment]
`kubectl get pod/ns/name`.... LOL

**Comment by luxas** [comment]
This would make `kubectl` SO much easier to use :+1:

**Comment by thockin** [comment]
I dont disagree, but it is somewhat complicated to transition now.  Maybe
something  like 'kind/ns:name' which would be less ambiguous and strictly
compatible (ns:name is not a valid name, nor is it confusing wrt kind/name).

Need to define precedence of this with --namespace flag and in-file
namespace yaml.

I also don't see it as a huge win, personally.  It would have been nice
from day1 but relatively minor now, IMO.  But this is a decision for UX
team - if someone sent a patch implementing something like it, or at least
a proposal that worked through all the details, it would be a better
starting place.

**Comment by therc** [comment]
This is more like P0 to me. Somewhere else I complained about having to type too much and the kind/name syntax. My vote if for kind/ns:name, too.

**Comment by bgrant0607** [comment]
cc @smarterclayton @lavalamp

**Comment by bgrant0607** [comment]
@bprashanth @zhouhaibing089 @luxas @therc What is the scenario you're trying to simplify? You often need to use resources from multiple namespaces on the same command line?

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by smarterclayton** [comment]
ns:name is not a valid name for namespaces and our core resources, but it can be a valid name for extension resources in the Kube ecosystem, like users, roles, authorizations.  We'd have to add more slashes

**Comment by deads2k** [comment]
> This is more like P0 to me. Somewhere else I complained about having to type too much and the kind/name syntax. My vote if for kind/ns:name, too.

Attaching the namespace to the "name" part won't work well because then you have to chose whether `kubectl get resource/token` is "list all resources in namespace token" or "get the resource named token in the current namespace".  To allow both cases, you must attach the information as a discretely tokenized part or as part of the "resource" part.

I think that `kubectl get resource.group:namespace/name` parses unambiguously since resource can't have dots groups can't have colons and namespaces can't have slashes.

**Comment by bprashanth** [comment]
> What is the scenario you're trying to simplify? You often need to use resources from multiple namespaces on the same command line?

I can assign short names to namespaces and end up with a small kubectl get line, --namespace= just feels unnecessary. I guess it would feel more natural if I could also do `kubectl get po --node=foo`. This isn't a huge deal for me personally because I just bash alias my way out of typing.

**Comment by therc** [comment]
In my case, I work with multiple namespaces, not on the same command line (I use --all-namespaces frequently, too). I guess I could create bash aliases, but I also tend to reinstall the machines I run kubectl from on a regular basis.

**Comment by smarterclayton** [comment]
--all-namespaces is so long anyway that it makes me cringe.

**Comment by bgrant0607** [comment]
What api group syntax did we settle on? I don't see it documented anywhere.
cc @caesarxuchao

**Comment by bgrant0607** [comment]
With Ubernetes, we'll also have multi-cluster scenarios coming.

**Comment by smarterclayton** [comment]
Syntax is:

    kubectl get hpa.v1beta1.extensions frontend

<resource>[[.<version>].<group>]

**Comment by felixbuenemann** [comment]
I think either a short option, like `kubectl command -n myns` or `kubectl command -ns myns` could be a solution or suffic the namespace using "@": `kubectl command po/mypod@myns`.

**Comment by deads2k** [comment]
> I think either a short option, like kubectl command -n myns or kubectl command -ns myns could be a solution or suffix the namespace using "@": kubectl command po/mypod@myns.

@smarterclayton was hoping to save `@` for indicating a `resourceVersion` for the day when we'd be able to retrieve a historical version of an object via the API.

Does `kubectl ` not alias `--namespace` to `-n` like openshift?

**Comment by felixbuenemann** [comment]
> Does kubectl not alias --namespace to -n like openshift?

No it does not.

**Comment by silasbw** [comment]
`kubectl command -n myns` would be an improvement for me: it's noticeably shorter than `--namespace`.

Does `-n` introduce ambiguities with other flags?  or introduce some other issue?  or is the hope that there's a nicer unambiguous solution (e.g., something similar to the original proposal)?

**Comment by deads2k** [comment]
I don't know of any conflicts.  I'm in favor of the short flag because it gets used all the time.

**Comment by AdoHe** [comment]
I am fine with `kubectl command -n myns`, @silasbw really appreciate if you could help with this.

**Comment by smarterclayton** [comment]
We originally had -n in Kube but took it out while we sorted out the other
config.  We went and added it in OpenShift because it was used all the
time, but forgot to add it in in kubectl.  I think it's time to bring it
back to kubectl.

Other folks who care about this in kubectl should v oice objections in the
next day or so, otherwise I think we have consensus to add `-n` as the
alias for `--namespace`.  Can someone scan over the flags in use today in
kubectl and verify that no one has introduced a `-n`?

**Comment by deads2k** [comment]
> We originally had -n in Kube but took it out while we sorted out the other
> config.  We went and added it in OpenShift because it was used all the
> time, but forgot to add it in in kubectl.  I think it's time to bring it
> back to kubectl.
> 
> Other folks who care about this in kubectl should v oice objections in the
> next day or so, otherwise I think we have consensus to add `-n` as the
> alias for `--namespace`.  Can someone scan over the flags in use today in
> kubectl and verify that no one has introduced a `-n`?


Already did, just client generation.

@silasbw has opened https://github.com/kubernetes/kubernetes/issues/30630 to add this.  I've got a minor comments unrelated to the code and tagged @bgrant0607 to give him a chance to object.

**Comment by luxas** [comment]
I'm also in favor for adding `-n` as a shorthand for `--namespace`
