### ISSUE TITLE
regression on apiserver CORS

### ISSUE THREAD

**Issue by pendoragon** [kubernetes/kubernetes#24086]
We found a regression on apiserver CORS that was previously fixed by #17093. It seems the regression is caused by #18113 during apiserver refactoring. 
Related issue #16431.

**Comment by Pendoragon** [comment]
@nikhiljindal Is this intended or did I miss anything?

**Comment by lavalamp** [comment]
Sorry about this, it probably got lost in a rebase. That said, the original PR should have included a test, and it's totally my fault for not requesting one.

**Comment by nikhiljindal** [comment]
yes sorry it was not intentional.
Thanks for pointing it out. Will fix.

**Comment by Pendoragon** [comment]
Good to know! Thanks!

**Comment by nikhiljindal** [comment]
Sorry for sitting on this for so long.
I have a WIP PR here: https://github.com/kubernetes/kubernetes/pull/27386 which doesnt seem to be doing what it is supposed to do. I am still trying to figure out why.

**Comment by nikhiljindal** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/27076 (kubernetes 1.3 known issues)
