### ISSUE TITLE
[kubectl] abbrev "dpl" for deployments

### ISSUE THREAD

**Issue by Frostman** [kubernetes/kubernetes#24083]
Most of the objects have the abbreviation (short form) in kubectl, for ex. rc == replicationcontroller. It'll be useful to have an abbrev for "deployments" as well and I'm proposing to use "dpl" for it.

**Comment by AdoHe** [comment]
@kubernetes/kubectl

**Comment by bgrant0607** [comment]
Dupe of lots of issues.
