### ISSUE TITLE
Pathological testing mode

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#24082]
Would be nice to have an e2e testing mode that ran with:
- No retries
- Crash on panic
- Really long/really short timeouts (whichever is worse, eg: watch should never timeout)

Maybe pass --fail-fast to all daemons and pipe that through kube-up?

**Comment by spxtr** [comment]
What does this get us?

**Comment by bprashanth** [comment]
Hard failures instead of stacktraces in controller manger logs that no-one notices till ship time, watch being broken but this not showing up because we periodically relist, apiserver throwing 500s that are masked because we retry etc. 

Quoting: http://static.googleusercontent.com/media/research.google.com/en//archive/paxos_made_live.pdf

In closing we point out a challenge that we faced in testing our system for which we have no systematic
solution. By their very nature, fault-tolerant systems try to mask problems. Thus they can mask bugs or
configuration problems while insidiously lowering their own fault-tolerance.

**Comment by ixdy** [comment]
I might be overly pessimistic, but I bet such a mode would just cause all tests to fail. I'm not sure how much signal that gets us...

**Comment by bprashanth** [comment]
That's just sad then. Catching panics and retrying 500s should be the exception. I don't mean don't retry an external dep like GCE or gcr.io, we don't care about those. The services we're responsible for shouldn't be failing in an isolated test environment that's carefully crafted according to best practice.

**Comment by spxtr** [comment]
I think it'd be helpful if you provide example of a particular place where we should try testing without a retry.

**Comment by bprashanth** [comment]
That should really be upto the team that handles --fail-fast. 
To being with, set this 
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/runtime/runtime.go#L26


Make these infinite
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L47
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L51
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/controller_utils.go#L55

Make this 0
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L58

(the above would pretty much apply for all controllers I think, not just rc)

Decrease nodecontroller's node timeout to 40s so if the kubelet is sluggish in reporting node status the node is marked dead.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L91

Run this once 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1028

Make this high https://github.com/kubernetes/kubernetes/blob/1186f4bf8512f1506e9dbe0221f4d8067a0016ce/pkg/kubelet/kubelet.go#L131 (not 100% sure on this one)
 
Make this low
https://github.com/kubernetes/kubernetes/blob/1186f4bf8512f1506e9dbe0221f4d8067a0016ce/pkg/kubelet/kubelet.go#L141

...that's the general idea at least

**Comment by spiffxp** [comment]
/sig testing
/priority awaiting-more-evidence
I'm inclined to say we've already got enough failures in our test suites as-is
