### ISSUE TITLE
hyperkube + kubectl - unknown flag

### ISSUE THREAD

**Issue by andrewmichaelsmith** [kubernetes/kubernetes#24088]
When trying to use kubectl from hyperkube I'm met with "unknown flag" errors. It looks as if the flags aren't being passed through to kubectl but hyperkube is trying to handle them itself (and subsequently giving an error when you give it flags it doesn't understand).

You can reproduce simply by running:

```
docker run -it gcr.io/google_containers/hyperkube-amd64:v1.2.2 /hyperkube kubectl create -f x
```

And you'll see the error:
```
Error: unknown shorthand flag: 'f' in -f

Kubernetes command line client

Usage:
  Kubernetes command line client [flags]

Available Flags:
..
..
..
```

**Comment by colhom** [comment]
@lavalamp @bgrant0607 I have a fix up in PR #25512.
