### ISSUE TITLE
potential issue of API server cache

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#24091]
Copy from discussion in https://github.com/kubernetes/kubernetes/pull/23795#issuecomment-208176276

> When API server watched a event, it need to insert the event into ALL watchers' "input" channel, then each watcher has a goroute running in background to pop events from the "input" channel and sent it to the corresponding client.
> 
> Since we process event sequentially(see [processEvent](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L362-L363) ), if one watcher was blocked due to some reasons, all other watchers will be blocked! We can ensure correctness by terminating this blocked watcher if it timeout(5 seconds) though, it may make watch really slow. For example, if we have 100 watcher watching a key, 10 watchers blocked and timeout by some reasons, the remaining watchers will receive the event after 50 seconds!

May be artificial and speculative though, @wojtek-t will send a PR to address this

**Comment by wojtek-t** [comment]
@kubernetes/sig-api-machinery
