### ISSUE TITLE
rktnetes: Update the kube-up to make master node uses rkt as well

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#24103]
Today, the master node is still using docker to run master components. The master components are built as docker images and pushed to google storage together with release tarballs. Then the master runs [kube-master-addons.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-master-addons/kube-master-addons.sh) to load the docker images.

For rktnetes 1.0, we want the master node to use rkt as well. And there are two ways to do this:
- Modify the kube-master-addons.sh, use docker2aci to load the images into rkt image store.
- Use hyperkube image? cc @aaron 

Will investigate the first option this week.

cc @sjpotter @euank

**Comment by mml** [comment]
@mikedanese

**Comment by yifan-gu** [comment]
We actually has implemented this in our fork'd branch, but doesn't seem good enough to upstream such change. https://github.com/yifan-gu/kubernetes/commit/aad45b908e621d3fbcf20b3487a371e8c0734b5a

On the other hand, coreos image on the gce contains python in `/usr/share/oem/python/`, but the os team high suggest we do not depend on that /cc @crawford

**Comment by crawford** [comment]
Correct. We will remove that without notice. Do not use that python (it's very crippled anyway).

**Comment by dchen1107** [comment]
ping ...

cc/ @philips Is this required for rktnetes-v1.0 (Kubernetes v1.3)?
