### ISSUE TITLE
Azure setup guide broken 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#24116]
The [Azure setup guide](http://kubernetes.io/docs/getting-started-guides/coreos/azure/) seems to be not working properly in k8s v.1.2, see [this question on StackOverflow](http://stackoverflow.com/questions/36545597/cannot-access-apiserver-on-kubernetes-v1-2-0). 

cc @errordeveloper @squillace @chanezon @vishh @kubernetes/docs

**Comment by janetkuo** [comment]
Copying @errordeveloper's reply on StackOverflow:

> Up-to-date code lives in weaveworks/weave-kubernetes-coreos-azure no and we have to PRs outstanding to update the docs kubernetes/kubernetes.github.io#314 and kubernetes/kubernetes#23818

**Comment by roberthbailey** [comment]
Closing since the referenced guide no longer exists and azure support in kube up was removed in https://github.com/kubernetes/kubernetes/pull/41672.
