### ISSUE TITLE
Block updates to most fields in PV and PVC objects

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#24111]
Add validate update function to block updates to all fields in the PersistentVolume (PV) and PersistentVolumeClaim (PVC) objects except those that must be updated by the controller for binding (claim ref, status, etc.).

CC @thockin @bgrant0607

**Comment by saad-ali** [comment]
This can be done as part of the binder/provisioner/recycler controller consolidation.

**Comment by thockin** [comment]
We need consider whether this can be done at all wrt api compat.

**Comment by msau42** [comment]
This has been implemented.
/assign
