### ISSUE TITLE
rate_limited_queue_test TestTryOrdering can fail under CPU load

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#24125]
It's possible for TestTryOrdering to flake:

```
--- FAIL: TestTryOrdering (0.02s)
	rate_limited_queue_test.go:179: order was wrong: [first third second]
FAIL
coverage: 61.4% of statements
```

because the test doesn't send back synthetic time.Now() values via the nowFn.  Test should be changed so that it can't fail no matter how slow the CPU is.

**Comment by fgrzadkowski** [comment]
@gmarek That's a flake in node controller. Can you please take a look?

**Comment by gmarek** [comment]
I believe that what @smarterclayton wrote is right. We just need to inject 'now' function in test.

@timothysc - can @jayunit100 work on it, or should I?

**Comment by smarterclayton** [comment]
I haven't had a chance in the past week to come back to this, don't think
I'll get to it before Monday at best.

On Apr 15, 2016, at 8:54 AM, Marek Grabowski <notifications@github.com>
wrote:

I believe that what @smarterclayton <https://github.com/smarterclayton>
wrote is right. We just need to inject 'now' function in test.

@timothysc <https://github.com/timothysc> - can @jayunit100
<https://github.com/jayunit100> work on it, or should I?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/24125#issuecomment-210452128>

**Comment by gmarek** [comment]
I also won't have time before next week, and even that it's probably the second half of it.

**Comment by smarterclayton** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/24382

**Comment by gmarek** [comment]
Thanks @smarterclayton

**Comment by smarterclayton** [comment]
Needs to merge first :)
