### ISSUE TITLE
Eliminate the docker load from the production

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#24123]
We built docker images for master components for dev cluster on the fly (https://github.com/kubernetes/kubernetes/issues/5011) before 1.0 release, which uses docker load instead of docker pull from the registry. The initial proposal I made is targeting for dev and test cluster since there is no proper release tag associated with it. Unfortunately, later we abused this functionality to the most master components except etcd image. In 1.2 release, we even abused this more to load kube-proxy image on each node. 

This is bad because
- There is no uniform way to get system images. For example, on master node, etcd image is pulled from gcr.io, while rest of images are loaded through script; on worker node, fluentd image is pulled from gcr.io, while kube-proxy image is loaded through script.
- Docker load sometimes hung. To self-healing, I introduced a simple logic to timeout that procedure and restart docker daemon as a workaround. That is a hacky way which makes the node bootstrap even more complicated. 
- gcr.io collects many useful stats, and we cannot use them. 

The initial counter argument to do docker load is that people feel gcs is more reliable than gcr. But that is not true today, not even mentioning that some of critical images are pulled from gcr at the first place.

cc/ @mikedanese @roberthbailey

**Comment by mikedanese** [comment]
We have the ability to do this today #17580, we just have to make it the default. It's a dev "action required" as developers will have to specify a DOCKE_REGISTRY in there cluster/env.sh because they don't have access to push dev builds to gcr.io/google_containers. I can make the switch.

Do we remove these images from the release tar altogether?

ref #23605

**Comment by roberthbailey** [comment]
What if we make kube-up fail (or prompt users for a docker registry that they can push to) if they are launching a locally built version? Running the script against a released version should just pull officially released images.

**Comment by dchen1107** [comment]
Do we plan to switch for both production release and dev/test? Can we just limit this to the user using official release?

**Comment by mikedanese** [comment]
I don't think that's a good idea. There is plenty to get in dev/test and we should make the dev/test environment as similar as possible to prod. FWIW, I've been doing this in dev/test for ~6 months. Why don't you want to use this in dev/test?

**Comment by roberthbailey** [comment]
I think we should switch dev/test as well as production. Otherwise we won't get a good signal as to whether the code is ready for production until it is too late to fix it.

**Comment by mikedanese** [comment]
cc @maisem

**Comment by roberthbailey** [comment]
This is still an issue, and we now side-load more images than when @dchen1107 originally filed this issue. :/

**Comment by ixdy** [comment]
I think kubeadm uses the registry, not the docker tarfiles, right (@luxas @mikedanese)? That's probably more reason we should get away from side-loading.

**Comment by luxas** [comment]
> I think kubeadm uses the registry, not the docker tarfiles, right (@luxas @mikedanese)? That's probably more reason we should get away from side-loading.

@ixdy We are using the registry yes, not side-loading

**Comment by ixdy** [comment]
Do we want to try to achieve this for v1.8?
I've got a few PRs out (https://github.com/kubernetes/kubernetes/pull/47939, https://github.com/kubernetes/release/pull/355) to support pushing server components to gcr.io (or any other registry) as part of the normal dev process, not just official releases. I'll follow up with a few changes in test-infra to make sure CI can do this.

The images are tagged with the standard semantic version, except that the `+` is replaced with a `_` (`${VERSION/+/_}`).

Somebody in want to handle plumbing through changes to allow specifying an arbitrary docker registry at startup, and pulling out the `docker load` calls? Not sure which team that falls under - cluster lifecycle?

The federation builds are already pulling images from CI gcr.io registries, so I think a lot of the hard work might already be done.

**Comment by roberthbailey** [comment]
We definitely want to enable CI testing of kubeadm at head before 1.8. Whether we can take the additional step of cleaning up the kube-up.sh scripts to remove the side-loading is currently TBD.

**Comment by roberthbailey** [comment]
I think we are now getting close to being able to do this.

**Comment by xmudrii** [comment]
@mikedanese Any idea has anything changed regarding this issue? Would it be possible to move forward?

**Comment by mikedanese** [comment]
I think this is obsolete now that most providers have moved out of tree.
