### ISSUE TITLE
AWS: kube-up should warn if there are existing resources tagged with KubernetesCluster

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kubernetes#24141]
`kube-up` generally expects a clean state to operate on. If there are existing resource tagged with KubernetesCluster `kube-up` can fail in subtle ways, even though the script seems to have run successfully. A recent example of this that I experienced was an existing route-table tagged with KubernetesCluster that caused my [networking to break](https://github.com/kubernetes/kubernetes/issues/24002), with no obvious indication that something had gone wrong during `kube-up`.

It would be really helpful if `kube-up` checked for existing Kubernetes tagged resources and warned about them. This can be done with the [describe-tags](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-tags.html) command, for instances:

`aws ec2 describe-tags --filters "Name=key,Values=KubernetesCluster"`

This can be tweaked to also filter on the value, matching the passed in cluster name, to handle multi-cluster situations.

If `KUBE_USE_EXISTING_MASTER` is true, the warning should be skipped since in this case pre-existing resources are expected.

**Comment by roberthbailey** [comment]
Marking as obsolete as kube-up no longer supports aws (https://github.com/kubernetes/kubernetes/pull/42196).
