### ISSUE TITLE
Update Ginkgo 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#24140]
Problem:

- Although Upstream tests can be run using `gingko.focus=k8s.io`, downstream tests have no mechanism for `focus`.
- New tests being constructed in `e2e_node` and so on have no global namespace.

Solution: 

- Ginkgo now provides a mechanism for skipping via `code location` (https://github.com/onsi/ginkgo/pull/228).  We should update to the latest Ginkgo, so that kube builds a e2e product that allows for easy global skip/focus in case tests aren't properly namespaced and annotated either upstream or downstream.

(Additionally, we should consider leveraging KubeDescribe in node tests as well so that those tests don't hit the same test crowding which are inevitable in large ginkgo suites, but that is a separate issue...)

**Comment by jayunit100** [comment]
cc @timothysc @kubernetes/sig-testing

**Comment by timothysc** [comment]
I can take this.  I'm pinging to see if folks are planning to switch to go vendoring now that 1.6 is in. 

xref: https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit

**Comment by spxtr** [comment]
We are interested in switching to vendoring, see #21098. There is a little work that needs to happen to get there, though.

**Comment by timothysc** [comment]
welp I'm not going to gate on vendoring, I'll just update

**Comment by ixdy** [comment]
@timothysc did you ever open a PR to update Ginkgo?

**Comment by timothysc** [comment]
whoops, I'll do that today.
