### ISSUE TITLE
Move generic packages from `pkg/util` into a separate repo

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#24156]
The code in there is useful for many other projects. It will add some vendoring overhead for Kubernetes, but given that the util package doesn't change that often, it might be ok.

@thockin @pmorie

**Comment by lavalamp** [comment]
I don't think we're ready for this yet.

**Comment by thockin** [comment]
Agree.  We need all the bot tooling to be packaged better before we spin up
new repos.  I am not against a util repo, but I also don't think it is too
bad for people as is.  It's a little fat, I guess...

**Comment by vishh** [comment]
As long as `pkg/util` is independent of rest of kubernetes, a new repo is
not necessary for now.

**Comment by thockin** [comment]
everything in util should be isolated from core kube.  If it is not, we should fix THAT
