### ISSUE TITLE
v1.2 kubectl test can't see v1beta1.Deployment object

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#24159]
When running v1.2 kubectl tests against v1.1; e.g. https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/70

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:179 Expected error: <errors.errorString | 0xc2085666f0>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.27.241 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook --namespace=e2e-tests-kubectl-p9ue1] [] service \"frontend\" created\nservice \"redis-master\" created\nservice \"redis-slave\" created\n error validating \"/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/frontend-deployment.yaml\": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false\nerror validating \"/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/redis-master-deployment.yaml\": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false\nerror validating \"/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/redis-slave-deployment.yaml\": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false\n [] 0xc2084f8580 exit status 1 true [0xc2083f6110 0xc2083f6130 0xc2083f6150] [0xc2083f6110 0xc2083f6130 0xc2083f6150] [0xc2083f6128 0xc2083f6148] [0x963fe0 0x963fe0] 0xc2083f8420}:\nCommand stdout:\nservice \"frontend\" created\nservice \"redis-master\" created\nservice \"redis-slave\" created\n\nstderr:\nerror validating \"/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/frontend-deployment.yaml\": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false\nerror validating \"/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/redis-master-deployment.yaml\": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false\nerror validating \"/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/redis-slave-deployment.yaml\": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false\n\nerror:\nexit status 1\n", } Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.27.241 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook --namespace=e2e-tests-kubectl-p9ue1] [] service "frontend" created service "redis-master" created service "redis-slave" created error validating "/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/frontend-deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false error validating "/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/redis-master-deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false error validating "/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/redis-slave-deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false [] 0xc2084f8580 exit status 1 true [0xc2083f6110 0xc2083f6130 0xc2083f6150] [0xc2083f6110 0xc2083f6130 0xc2083f6150] [0xc2083f6128 0xc2083f6148] [0x963fe0 0x963fe0] 0xc2083f8420}: Command stdout: service "frontend" created service "redis-master" created service "redis-slave" created stderr: error validating "/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/frontend-deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false error validating "/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/redis-master-deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false error validating "/jenkins-master-data/jobs/kubernetes-e2e-gke-1.1-1.2-kubectl-skew/workspace/kubernetes/examples/guestbook/redis-slave-deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false error: exit status 1 not to have occurred*

**Comment by ihmccreery** [comment]
My guess is this was caused by https://github.com/kubernetes/kubernetes/pull/23965

Reassigning to @janetkuo.

**Comment by janetkuo** [comment]
@ihmccreery `Deployment` isn't enabled by default in v1.1 so this test won't pass in v1.1 as expected.

**Comment by ihmccreery** [comment]
This is for the following test:

**Kubectl client Guestbook application [It] should create and stop a working application [Conformance]**

> Deployment isn't enabled by default in v1.1 so this test won't pass in v1.1 as expected.

Does that mean that if a user upgrades to the v1.2 `kubectl` the Guestbook tutorial won't work against their existing clusters?

**Comment by janetkuo** [comment]
> Does that mean that if a user upgrades to the v1.2 kubectl the Guestbook tutorial won't work against their existing clusters?

@ihmccreery it depends on which release branch of guestbook tutorial they read - v1.2 guestbook contains deployment yaml files which v1.1 (and earlier) guestbook contains replication controller yaml files.
