### ISSUE TITLE
kubelet tries to kill rkt pods more than once when `kubectl delete pod`

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#24158]
When testing against rkt's prestop hooks support (https://github.com/kubernetes/kubernetes/pull/23532),
I found that kubelet will try to kill pod more than once when deleting the pod. And the first when it kills, it calls rkt.KillPod() with a valid runningPod, and things work fine. But shortly after the pod is killed, it invokes rkt.KillPod() again. Not sure if this is a normal race case or a bug.

To reproduce:

```
$ cat /tmp/pod
# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "600"

$ LOG_LEVEL=5 CONTAINER_RUNTIME=rkt RKT_PATH=/home/yifan/rkt/build-rkt-1.3.0+git/bin/rkt hack/local-up-cluster.sh

$ kubectl create -f /tmp/pod
$ kubectl delete -f /tmp/pod

```

kubelet logs can be found [here](https://storage.googleapis.com/public-logs/kubelet.txt)

cc @kubernetes/sig-node

**Comment by yujuhong** [comment]
I checked the code and this sort of works as intended.
1. Pod worker sees the DeletionTimestamp and tries to kill the pod.
2. After the pod is killed, PLEG detects the container state changes and triggers the pod worker again.
3. Pod worker gets the exited container states, but still tries to kill the pod at https://github.com/kubernetes/kubernetes/blob/e93c0d727fb40b752411c3f7b9ab20c5d53ffecd/pkg/kubelet/kubelet.go#L1742

We should probably add a check here to skip the killing if there is nothing to kill.

**Comment by yifan-gu** [comment]
@yujuhong But I didn't see the same behavior (2 and 3) in docker's case, and I don't understand why.

**Comment by yujuhong** [comment]
> @yujuhong But I didn't see the same behavior (2 and 3) in docker's case, and I don't understand why.

(2) should happen and (3) simply doesn't log anything in docker's case.

**Comment by yifan-gu** [comment]
@yujuhong OK, thanks for explaining :)

**Comment by dchen1107** [comment]
Looks like we should clean up at (3) for both docker and rkt cases.

**Comment by yujuhong** [comment]
Yes, we just need to add a check in kl.killPod().

**Comment by yujuhong** [comment]
Closing this since relevant issues should be handled in CRI or moved to the rktlet repository.
