### ISSUE TITLE
Finer granularity of ACLs, specifically for labels on issues/pull requests

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#24169]
Concerns raised in related meeting.  Capturing this here so we can develop ideas and work toward a conclusion on it.

Aaron C: The label management for cherry picks is very frustrating for folks without write access to github. One idea would be to separate out the github issues into a separate repository from the code so that we can give broader access to edit / assign / add labels to issues

Brendan B: Github’s ACL model sucks. We should also clearly document the state machine for which labels we expect for cherry picks so that it’s clear to users where they are in the process.

Brendan B: Another idea is to write a simple App Engine app that allows folks to put labels onto their own PRs to help make this process easier. PRs welcome. 

cc @spiffxp @brendandburns @roberthbailey

**Comment by luxas** [comment]
How about ACLs for `gcr.io`?

**Comment by roberthbailey** [comment]
@luxas that seems like a reasonable concern about the build/release process, but should be split off into a separate issue. This one is specifically about the PR-flow for contributing code to the main repo (and the cherry pick process).

**Comment by david-mcmahon** [comment]
#23743 might offer some more flexibility here.

**Comment by spiffxp** [comment]
related, something to allow more granular wiki access (or replacement of the wiki with something that better suits our needs), ref #23146

**Comment by luxas** [comment]
@roberthbailey ok

Another thing ~related to this is the `needs-ok-to-merge` label. 
I don't think it's documented where those privs live and what one should do to earn a removal of that check. The same about k8s-bot retest permission (which I have, but I don't know where that lives either). As an outside-google contributor, none of these things are obvious.

It would be nice with some devel docs about how to earn privs etc. Of course, it would be nice if you had the possibility to let anyone or some chosen people in the hierarchy apply specific labels `cherrypick-candidate`, `help-wanted`, `area/*` or some other useful labels. That would obviously require a change in @github's ACL model.
WDYT?

**Comment by roberthbailey** [comment]
Those are great points. @david-mcmahon -- we may want to address those in a community meeting (like what you are planning to do for release notes tomorrow). 

@luxas The ok to merge list is kept in https://github.com/kubernetes/contrib/blob/master/mungegithub/whitelist.txt

**Comment by david-mcmahon** [comment]
@roberthbailey I don't see any mention of `needs-ok-to-merge` in the kubernetes repo - certainly not in docs/.  I would say that these mechanisms certainly need a place somewhere in docs/devel and a link to it in the bot message that applies the label.  I'll file an issue.  cc @eparis

**Comment by david-mcmahon** [comment]
cc: @erictune, possibly elated to feature workflow, specifically using another repo with looser ACLs for labeling and committing.

**Comment by luxas** [comment]
@david-mcmahon Please consider https://github.com/kubernetes/kubernetes/issues/24228#issuecomment-210119344. 
I'm not sure we should move out issues and such things out of k8s main repo just because Github's ACL model is bad

**Comment by david-mcmahon** [comment]
@luxas Agreed, that sounds like a great solution.  cc @eparis.  I don't know what if any work has / is being done with OWNERS files but that seems like a good use of them coupled with a labeling bot.

**Comment by luxas** [comment]
Sounds great.
It seems like it's @eparis that's the bot ninja :), maybe he can do it?

**Comment by bgrant0607** [comment]
@hongchaodeng is working on automatic application of `lgtm` and `approved` labels.

We also need a solution to release-note and cherrypick labels, which was the original impetus for this issue, and any other labels used as part of the PR workflow.

**Comment by david-mcmahon** [comment]
Prow fixed this.
