### ISSUE TITLE
Should serviceAccountLookup be set to true in kubernetes apiserver

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#24167]
Forked from https://github.com/kubernetes/kubernetes/pull/23959#discussion_r59069701.

Setting serviceAccountLookup to true ensures that we verify that the service account tokens mentioned in the request are actually present in etcd.
Without it we just verify that the token is valid. That check breaks if a service account is used after it is deleted.

@liggitt mentioned that we should set it to true in kubernetes apiserver (we dont currently). Openshift sets it to true. He also mentioned that @erictune had some performance concerns for setting it to true.

What do others think?

cc @liggitt @erictune @lavalamp @kubernetes/sig-auth

**Comment by deads2k** [comment]
> What do others think?

I think that having long lived, irrevocable token is a security problem.  I think that a cache with a fixed expiry time could be used if performance did become a problem.

**Comment by erictune** [comment]
If you want revocation, you have to give up federation.  How do we see service accounts working in a federated environment?  Cluster 1 can't really check cluster 2's etcd.

**Comment by liggitt** [comment]
The check can be done via etcd or via the API (there's implementations for both in tree)

**Comment by erictune** [comment]
Whitelist approach seems like it makes it hard to distinguish between just-created vs just-deleted.  Delay in propagating updates to service accounts in HA/federated setup leads to weird failures, maybe?

Blacklist seems preferable.  Article about revoking JWTs using a `jti` claim: https://auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys/

**Comment by deads2k** [comment]
> Blacklist seems preferable. Article about revoking JWTs using a jti claim: https://auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys/

If I'm reading correctly, that still requires a lookup to see if the JWT (or its identifier) is in a list.  If we're going to do that, why not use the mechanism we already built to hit a cache a SA tokens and check if its there?

**Comment by connec** [comment]
I've just been digging through code/issues along this path too, it seems quite bad to me that revoking service accounts is so difficult (impossible?) with the default deployment options (we're using AWS).

A reasonable middle ground between security and performance could be to cache successful authorisation with a configurable length, with some sane default to prevent bursts of requests from being painfully expensive. I'd imagine `serviceAccountLookupTtl` or something.

If this wasn't changed, what would be the recommended approach to revoking a leaked token? Change the `serviceAccountKeyFile`, restart the API server, and update all the valid tokens?

**Comment by liggitt** [comment]
I think this should be enabled by default. Agree that we can add a TTL if there is an issue with performance, but we've been running with this enabled for 2+ years at scale in OpenShift without incident.
