### ISSUE TITLE
Generate yaml kubectl files for 1.2 and 1.1 

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes#24160]
When https://github.com/kubernetes/kubernetes/pull/23526 gets merged, it would be great if we had output not just going forward for 1.3 but also for the 1.2 and 1.1 docsets. 1.1 is lower priority, but 1.2 is the current default version of k8s on the site so it would be awesome for it to have the upgraded CLI docs. 

@tyangliu @lavalamp

**Comment by lavalamp** [comment]
So anyone who has time can (locally) manually merge that into the 1.2 branch & run it. @johndmulhausen where would you like the resulting files?

We could also just cherry-pick it.

**Comment by johndmulhausen** [comment]
How about in /_data/cli

**Comment by lavalamp** [comment]
Of the docs repo? Is there a subdirectory per version?

**Comment by johndmulhausen** [comment]
@lavalamp - Yes, in the docs repo. There are no subdirectories per version, just branches. See: release-1.1 and release-1.3
