### ISSUE TITLE
Consider changing E2E cloud provider flags to gce_not_gke and gke_not_gce

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#24170]
@thockin's suggestion:

To prevent E2E tests that should run on both gce and gke from accidently only being run on one or the other, maybe we should rename gce and gke so that it is blatantly obvious to the author that they are exclusive, e.g. `SkipUnlessProviderIs("gce_not_gke", "aws")` instead of `SkipUnlessProviderIs("gce", "aws")`

**Comment by fejta** [comment]
I don't see a lot of value from this on the test-infra side, but it sounds like it might be useful for people writing tests.

**Comment by mml** [comment]
I'm @mml and I endorse this disambiguation.

**Comment by alex-mohr** [comment]
1.3 is getting closer and I'd rather avoid some of the issues we saw with 1.2 where tests were only running on GCE but not GKE, so I'm bumping priority and tagging milestone 1.3.

**Comment by roberthbailey** [comment]
@jlowdermilk just took a look through our test cases to see what the delta was between gce and gke tests and it isn't too bad. @alex-mohr how do you feel about bumping it out of the 1.3 milestone?

**Comment by goltermann** [comment]
We @alex-mohr @roberthbailey should make a call on this for v1.3 soon.

**Comment by ihmccreery** [comment]
Why is this marked at `area/upgrade`?

**Comment by jlowdermilk** [comment]
I don't think this change adds much value. I recently audited all skip on gke e2e tests to make they were intended, and found only a few that needed updating.

**Comment by roberthbailey** [comment]
I vote to bump it out of the 1.3 milestone. @alex-mohr do you concur?

**Comment by alex-mohr** [comment]
@roberthbailey sgtm.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gke
since we lack a sig-gcp at the moment

**Comment by spiffxp** [comment]
/close
If someone finds evidence that this has been a problem, please reopen with that evidence.  From my experience lately, the issue has been that tests are failing on GKE, not that the wrong tests are running in the wrong place.
