### ISSUE TITLE
e2e failures: Error deleting container: Error response from daemon: Unable to remove filesystem for... device or resource busy

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24174]
It seems that Jenkins disk is full again.

**Comment by fejta** [comment]
I believe this is under control:

* Increased the size of the docker disk: `gcloud compute disks resize --size=1TB`
* Cleaned up old containers and images: `docker rm -v $(docker ps -a -q -f status=exited -f status=dead)`
* Deleted everything in it `sudo rm -rf /jenkins-master-docker`
* restarted docker: `sudo /etc/init.d/docker restart`
* repulled the e2e image:  `gcloud docker ^Cll gcr.io/google_containers/kubekins-test:0.9`

Things seem to be running again.

@ixdy has a PR out to add most of this functionality to our daily maintenance script: https://github.com/kubernetes/kubernetes/pull/24168
