### ISSUE TITLE
help-need: some requests are really slow

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#24188]
Some requests are really slow. The following log is grep from our production environment. Any suggestion about this?

```
I0413 11:23:06.872431       6 handlers.go:142] GET /api/v1/namespaces/22acf3cfc70b48e38b4951bc63b7f976/pods?labelSelector=name%3Dnnnnnn-87148-a5993ca4: (15m39.068989377s) 200 [[Jakarta Commons-HttpClient/3.1] 10.166.84.218:60178]
I0413 11:23:06.908202       6 handlers.go:142] GET /api/v1/pods?fieldSelector=spec.nodeName%3D10.174.11.210: (15m39.753840196s) 200 [[kubelet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.11.210:58867]
I0413 11:23:09.433123       6 handlers.go:142] GET /api/v1/namespaces/5c1e15f8813144519ff0b0bf550adf3c/pods/apitestyqpub145851352364547772d-47196-dff846b8-maddi: (15m39.183550829s) 200 [[kubelet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.7.234:46544]
I0413 11:23:10.457268       6 handlers.go:142] GET /api/v1/namespaces/5c1e15f8813144519ff0b0bf550adf3c/pods/apitestyqpub1458520723291d530a2-47272-11165372-dqsmg: (15m39.100244529s) 200 [[kubelet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.8.14:39349]
I0413 11:23:10.969196       6 handlers.go:142] GET /api/v1/namespaces/5c1e15f8813144519ff0b0bf550adf3c/pods/apitestyqpub14585171237035adac0-47223-14e070eb-zpihe: (15m39.375256689s) 200 [[kubelet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.7.246:36824]
I0413 11:23:11.009290       6 handlers.go:142] GET /api/v1/pods?fieldSelector=spec.nodeName%3D10.174.11.211: (15m39.641273771s) 200 [[kubelet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.11.211:49304]
I0413 11:23:13.017259       6 handlers.go:142] GET /api/v1/namespaces/21a927a2a9b449b6931bb993acb08d89/pods/m2048-49569-8d91b037-hwj16: (15m39.037857845s) 200 [[kubelet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.14.242:55576]
I0413 11:32:06.552542       6 handlers.go:142] GET /api/v1/namespaces/9d8c830da64943beb86109a3d9fa9348/pods?labelSelector=name%3Dzwhmaybe-87177-9073ab7f: (15m39.320187208s) 200 [[Jakarta Commons-HttpClient/3.1] 10.166.84.218:41955]
I0413 11:32:07.090325       6 handlers.go:142] GET /api/v1/namespaces/9d4b7df05aea46bbbc6b1f6e3016205c/pods?labelSelector=name%3Dwapcmp-87150-8c146209: (15m39.43856157s) 200 [[Jakarta Commons-HttpClient/3.1] 10.166.84.218:56837]
I0413 11:32:07.545182       6 handlers.go:142] GET /api/v1/namespaces/cceb6b3b890e4501a0ccf6c4791edf68/pods?labelSelector=name%3Daaaa-87149-5be3900c: (15m39.219536987s) 200 [[Jakarta Commons-HttpClient/3.1] 10.166.84.218:57136]
I0413 11:32:08.560649       6 handlers.go:142] GET /api/v1/pods?fieldSelector=spec.nodeName%3D10.174.11.53: (15m40.304486081s) 200 [[kubelet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.11.53:38964]
I0413 11:32:09.080846       6 handlers.go:142] GET /api/v1/namespaces/bc7ce8bd04c3430f964a8822a98cf120/pods/zxc-85869-9882df8f-si78i: (15m39.371914344s) 200 [[kube-controller-manager/v1.0.0.13 (linux/amd64) kubernetes/unknown] 127.0.0.1:58766]
I0413 11:32:10.104905       6 handlers.go:142] GET /api/v1/namespaces/default/pods/k8stest001-40835-97228aaa-z1494: (15m39.001388424s) 200 [[kube-scheduler/v1.0.0.13 (linux/amd64) kubernetes/unknown] 127.0.0.1:47288]
I0413 12:01:03.738434       6 handlers.go:142] GET /api/v1/namespaces/0f2e96afba09493694c6ef105fe32c4c/pods/chenzuo-87272-ba398773-59470: (15m43.471241106s) 404 [[kubelet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.12.62:55887]
I0413 12:42:32.087959       6 handlers.go:142] GET /api/v1/namespaces/7129a8bb511c4e4e95e12587e8f52f7b/pods/centos-73708-f621454e-ob8i6/log?container=centos-73708-f621454e-container&tailLines=1000: (190h1m17.664131275s) 200 [[Jakarta Commons-HttpClient/3.1] 10.166.84.215:53811]
I0413 13:00:52.856281       6 handlers.go:142] GET /api/v1/namespaces/63b21c0c1e5f45158957bb92cf7c06e7/pods/liu44447777-87463-5f7531f6-jsnir: (15m43.582855825s) 404 [[kubelet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.15.203:55075]
I0413 13:00:53.414006       6 handlers.go:142] GET /api/v1/pods?fieldSelector=spec.nodeName%3D10.174.15.223: (15m43.913611542s) 200 [[kubelet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.15.223:44866]
I0413 13:00:55.929034       6 handlers.go:142] GET /api/v1/namespaces/c0f37d8f48b54eefb7d94394ee16e382/pods?labelSelector=name%3Dsbwml-87467-b78d1869: (15m43.490749082s) 200 [[Jakarta Commons-HttpClient/3.1] 10.166.84.219:59164]
```

This problem is really strange and hard to debug. Not all requests becomes slow, just little does. And we just don't know how to reproduce it. There are other strange issues we met, for example https://github.com/kubernetes/kubernetes/issues/24094

Do you guys met similar issues before? @wojtek-t @xiang90 @kubernetes/sig-scalability

**Comment by wojtek-t** [comment]
Can this be some kind of throttling?

It's suspicious that most of these requests took exactly 15m39s

**Comment by wojtek-t** [comment]
@lavalamp @kubernetes/sig-api-machinery

**Comment by mqliang** [comment]
There is a request took 190h1m17.664131275s. It seems that Kubernetes has no client/serve side timeout mechanism. Intuitively, I think client(kubelet/scheduler/kubelet) should have a timeout option when send requests. And when API server send request to etcd, it should also have a timeout option. The only  exception is WATCH request.

In addition, the log in API server is not detailed enough, I think we should print out etcd response time, decode time, etc. It will be every helpful for debugging.

BTW, mind take a look at https://github.com/kubernetes/kubernetes/issues/24094? It's also very strange.

**Comment by wojtek-t** [comment]
@mqliang - actually there is a support, but client library seems to not setting it by default.

Regarding log details, you may try to look at "traces" in apiserver logs. For example for List requests, a trace log will be created for all requests that processing took longer than 500ms:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L311

[This is the "real" processing time, it doesn't include waiting because of throttling, etc.]. Do you see such logs in your apiserver logs?

I don't think that adding those information to all logs is a good idea - this would make them unreadable, and they are useless in most cases. That's why I think traces for long requests are better idea.

**Comment by AdoHe** [comment]
Actually apiserver has the timeout support
[https://github.com/kubernetes/kubernetes/blob/master/pkg/genericapiserver/genericapiserver.go#L658](https://github.com/kubernetes/kubernetes/blob/master/pkg/genericapiserver/genericapiserver.go#L658) when timeout, the response code should be 503

**Comment by wojtek-t** [comment]
@AdoHe - that's what I wrote above

**Comment by AdoHe** [comment]
@wojtek-t from the log @mqliang paste, the request took 15m39s, it should already timeout, but the status code is still 200.

**Comment by wojtek-t** [comment]
@AdoHe 

>
@mqliang - actually there is a support, but client library seems to not setting it by default.

from the above. Yes - it should be 503 if timeout is set. But it seems it isn't.

**Comment by smarterclayton** [comment]
Note that we don't yet support (or have queued up) the ability to
*actually* cancel long running HTTP requests by propagating our go.Context
down to all subordinate calls and verifying that a timeout cancels the
request.  It's something we should eventually do.

**Comment by lavalamp** [comment]
There's actually a global 1m timeout. Is this disabled in OP's environment?

**Comment by lavalamp** [comment]
Actually, since you're on 1.0, I'm not sure if the timeout was in then. What is the scale of your cluster?

I think you'll have a much better experience if you use 1.2 or at least 1.1.

**Comment by wojtek-t** [comment]
Ohh yeah - actually with 1.0 release is not very scalable - there are 10x+ improvements in 1.2 compared to 1.0

**Comment by mqliang** [comment]
@wojtek-t trace log is as follows:

```
I0416 21:46:35.128548       6 trace.go:57] Trace "ExtractToList *api.PodList" (started 2016-04-16 21:30:51.60213102 +0800 CST):
[6.428µs] [6.428µs] About to list etcd node
[15m43.526294273s] [15m43.526287845s] Etcd node listed
[15m43.526374224s] [79.951µs] Node list decoded
[15m43.526381672s] [7.448µs] END
I0416 21:46:35.128593       6 trace.go:57] Trace "List *api.PodList" (started 2016-04-16 21:30:51.602127416 +0800 CST):
[1.57µs] [1.57µs] About to list directory
[15m43.52642562s] [15m43.52642405s] List extracted
[15m43.526440727s] [15.107µs] List filtered
[15m43.526441429s] [702ns] END
I0416 21:46:35.128689       6 handlers.go:142] GET /api/v1/namespaces/e726244b5a814b9d89c753ee906653ea/pods?labelSelector=name%3Dh446460112-98849-5014e1d1: (15m43.526936797s) 200 [[Jakarta
Commons-HttpClient/3.1] 10.166.84.218:39565]
I0416 21:46:35.128860       6 trace.go:57] Trace "Get *api.Pod" (started 2016-04-16 21:30:51.659893242 +0800 CST):
[2.08µs] [2.08µs] About to read object
[15m43.468936013s] [15m43.468933933s] Object read
[15m43.468937361s] [1.348µs] END
I0416 21:46:35.128878       6 trace.go:57] Trace "Get *api.Pod" (started 2016-04-16 21:30:51.737225521 +0800 CST):
[2.984µs] [2.984µs] About to read object
[15m43.391622735s] [15m43.391619751s] Object read
[15m43.39162412s] [1.385µs] END
I0416 21:46:35.129148       6 handlers.go:142] GET /api/v1/namespaces/5c1e15f8813144519ff0b0bf550adf3c/pods/apitestyqpub145851352364547772d-47196-dff846b8-maddi: (15m43.392228707s) 200 [[ku
belet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.7.234:50375]
I0416 21:46:35.129156       6 handlers.go:142] GET /api/v1/namespaces/501bb681f0df4f9ab33b3de724d0d4f6/pods/a1a1-94473-7dc0816f-ffqtk: (15m43.469555466s) 200 [[kubelet/v1.0.0.13 (linux/amd6
4) kubernetes/unknown] 10.174.8.64:37819]
```

Seems that etcd response time is slow. @xiang90 Could please take a look? Our etcd version is v2.2.5. kubernetes version is v1.0, our cluster has about 3500 nodes, each has one pod.

**Comment by xiang90** [comment]
@mqliang How do you calculate the time? How large is the response from etcd? How many nodes does the response contain from etcd?

**Comment by mqliang** [comment]
> How do you calculate the time? How large is the response from etcd? How many nodes does the response contain from etcd?

There are actually 4 request in the log I post. The first 2 request is LIST request, the latter 2 is GET request. Even for List request, usually we have less than 5 pods in a namespace. 

```
I0416 21:46:35.128548       6 trace.go:57] Trace "ExtractToList *api.PodList" (started 2016-04-16 21:30:51.60213102 +0800 CST):
[6.428µs] [6.428µs] About to list etcd node
[15m43.526294273s] [15m43.526287845s] Etcd node listed
[15m43.526374224s] [79.951µs] Node list decoded
[15m43.526381672s] [7.448µs] END
```

```
I0416 21:46:35.128593       6 trace.go:57] Trace "List *api.PodList" (started 2016-04-16 21:30:51.602127416 +0800 CST):
[1.57µs] [1.57µs] About to list directory
[15m43.52642562s] [15m43.52642405s] List extracted
[15m43.526440727s] [15.107µs] List filtered
[15m43.526441429s] [702ns] END
```

```
I0416 21:46:35.128689       6 handlers.go:142] GET /api/v1/namespaces/e726244b5a814b9d89c753ee906653ea/pods?labelSelector=name%3Dh446460112-98849-5014e1d1: (15m43.526936797s) 200 [[Jakarta
Commons-HttpClient/3.1] 10.166.84.218:39565]
I0416 21:46:35.128860       6 trace.go:57] Trace "Get *api.Pod" (started 2016-04-16 21:30:51.659893242 +0800 CST):
[2.08µs] [2.08µs] About to read object
[15m43.468936013s] [15m43.468933933s] Object read
[15m43.468937361s] [1.348µs] END
I0416 21:46:35.128878       6 trace.go:57] Trace "Get *api.Pod" (started 2016-04-16 21:30:51.737225521 +0800 CST):
[2.984µs] [2.984µs] About to read object
[15m43.391622735s] [15m43.391619751s] Object read
[15m43.39162412s] [1.385µs] END
I0416 21:46:35.129148       6 handlers.go:142] GET /api/v1/namespaces/5c1e15f8813144519ff0b0bf550adf3c/pods/apitestyqpub145851352364547772d-47196-dff846b8-maddi: (15m43.392228707s) 200 [[ku
belet/v1.0.0.13 (linux/amd64) kubernetes/unknown] 10.174.7.234:50375]
I0416 21:46:35.129156       6 handlers.go:142] GET /api/v1/namespaces/501bb681f0df4f9ab33b3de724d0d4f6/pods/a1a1-94473-7dc0816f-ffqtk: (15m43.469555466s) 200 [[kubelet/v1.0.0.13 (linux/amd6
4) kubernetes/unknown] 10.174.8.64:37819]
```

**Comment by mqliang** [comment]
@xiang90 The following is the code writing the trace log
```
// Get retrieves the item from etcd.
func (e *Etcd) Get(ctx api.Context, name string) (runtime.Object, error) {
	obj := e.NewFunc()
	trace := util.NewTrace("Get " + reflect.TypeOf(obj).String())
	defer trace.LogIfLong(time.Second)
	key, err := e.KeyFunc(ctx, name)
	if err != nil {
		return nil, err
	}
	trace.Step("About to read object")
	//if err := e.Helper.ExtractObj(key, obj, false); err != nil {
	if err := e.Storage.Get(ctx, key, obj, false); err != nil {
		return nil, etcderr.InterpretGetError(err, e.ResourceName, name)
	}
	trace.Step("Object read")
	if e.Decorator != nil {
		if err := e.Decorator(obj); err != nil {
			return nil, err
		}
	}
	return obj, nil
}
```

**Comment by xiang90** [comment]
@mqliang 

It is still not clear to me how do you calculate the request-response latency from etcd. I am not sure the how many requests you sent to etcd in one storage call, how many data you got back from etcd, etc..

Try to do
```go
start := time.Now()
resp,err := etcdclient.Get()
took := time.Since(time.Now())
// print took, size of response, number of nodes in response here
``` 

I cannot really help you until you provid the information I asked for etcd side.

**Comment by mqliang** [comment]
@xiang90 

```
 trace.Step("About to read object")
    if err := e.Helper.ExtractObj(key, obj, false); err != nil {
        return nil, etcderr.InterpretGetError(err, e.EndpointName, name)
    }
    trace.Step("Object read")
```

```
I0416 21:46:35.128860       6 trace.go:57] Trace "Get *api.Pod" (started 2016-04-16 21:30:51.659893242 +0800 CST):
[2.08µs] [2.08µs] About to read object
[15m43.468936013s] [15m43.468933933s] Object read
[15m43.468937361s] [1.348µs] END
```

As the "trace" log and code demonstrate, function `e.Helper.ExtractObj(key, obj, false)` takes about 15m, right? Function basically do two thing:
 
* [h.Client.Get()](https://github.com/kubernetes/kubernetes/blob/release-1.0/pkg/tools/etcd_helper.go#L350)
* [Decode](https://github.com/kubernetes/kubernetes/blob/release-1.0/pkg/tools/etcd_helper.go#L356)

But, unfortunately, there is no log showing exactly how many time the "Get" part takes and the "Decode" part takes. 

Note: We are in kubernetes 1.0, this is a GET request here(`recursive=false`), not a LIST request, so the data get from etcd should be not large.

**Comment by chaolou** [comment]
@AdoHe  @wojtek-t 
> the request took 15m39s, it should already timeout, but the status code is still 200.
> from the above. Yes - it should be 503 if timeout is set. But it seems it isn't.
because we use k8s restful api directly and set timeout 1minute in http lib instead of using the inner  timeout parameter of kubernets api

**Comment by xiang90** [comment]
@mqliang 

Here is the thing:

If you want me or @hongchaodeng to debug etcd, you have to provide etcd related log as I asked.

Personally, I have no interest to debug kubernetes 1.0 codebase. As @wojtek-t mentioned, k8s changed a lot since 1.0. If you can reproduce in k8s 1.2 or later, I can give it a more careful look.

**Comment by mqliang** [comment]
@xiang90 Yeah. I definitely understand that I should provide more information, but unfortunately I have no more log. And the statistical information in prometheus helps little for this problem:

```
apiserver_request_latencies_bucket{resource="pods",verb="GET",le="125000"} 1.023445e+06
apiserver_request_latencies_bucket{resource="pods",verb="GET",le="250000"} 1.026572e+06
apiserver_request_latencies_bucket{resource="pods",verb="GET",le="500000"} 1.027847e+06
apiserver_request_latencies_bucket{resource="pods",verb="GET",le="1e+06"} 1.028411e+06
apiserver_request_latencies_bucket{resource="pods",verb="GET",le="2e+06"} 1.029052e+06
apiserver_request_latencies_bucket{resource="pods",verb="GET",le="4e+06"} 1.029083e+06
apiserver_request_latencies_bucket{resource="pods",verb="GET",le="8e+06"} 1.029091e+06
apiserver_request_latencies_bucket{resource="pods",verb="GET",le="+Inf"} 1.029229e+06
```

```
etcd_request_latencies_summary{operation="get",type="*api.Pod",quantile="0.5"} 552
etcd_request_latencies_summary{operation="get",type="*api.Pod",quantile="0.9"} 9511
etcd_request_latencies_summary{operation="get",type="*api.Pod",quantile="0.99"} 561626
etcd_request_latencies_summary_sum{operation="get",type="*api.Pod"} 1.664583112e+09
etcd_request_latencies_summary_count{operation="get",type="*api.Pod"} 28613
```

For "etcd_request", we only have “latencies_summary” information, I'd suggest add "latencies_bucke" information. And the "le="8e+06" limit in "latencies_bucket" seems not enough, may be add "le="16e+06", le="32e+06"? @wojtek-t @lavalamp @smarterclayton

**Comment by mqliang** [comment]
Will add more log, but this problem cold only be reproduced when we have a large cluster and running for a long time. Close this and may open a new one with more information when we meet this problem again. 

Will file an issue for my suggestion about "etcd_request_latencies_bucket"

**Comment by mqliang** [comment]
Reopen to here @wojtek-t 's feedback about the trace log, if he has no ideas, will close this.

**Comment by wojtek-t** [comment]
I'm not sure we can get anything useful from that logs.

Also, as we mentioned earlier, you shouldn't run 3.5k nodes on 1.0 release - this is a configuration that we officially do not support on any release yet, especially on 1.0. So we shouldn't spend time on it.
If you can reproduce the same problems with 1.2 release, then we will definitely spend more time trying to understand it.
