### ISSUE TITLE
Scheduler infrastructure is too slow

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#24192]
I did a simple experiment around scheduling throughput today.
Basically:
- I removed all priorities and predicates functions
- I replaced the whole scheduling algorithm with "choose random node from the existing ones".

This gives us an estimation on the maximum scheduling throughput we can get (assuming that scheduling algorithm is infinitely fast).

The bad news is that I get throughput of ~45pods/second, which is pretty sad.

So, if we want to go higher than that (and I believe we really want and need), we need some deeper changes in the scheduler infrastructure itself (instead of optimizing priority/predicates function for now).

@davidopp @gmarek 
@kubernetes/sig-scheduling @kubernetes/sig-scalability

**Comment by wojtek-t** [comment]
There are multiple improvements - I think the easiest one is to not wait for "binding" function to finish before starting to process the next pod.

**Comment by wojtek-t** [comment]
I guess the first option is significantly better.

**Comment by wojtek-t** [comment]
Anyway - I'm not sure how far we can get with this improvment. I will try to run some experiments.

**Comment by wojtek-t** [comment]
BTW, we already have a support in the scheduler that if we don't observe binding via watch for some time, we start to ignore the assumedPod. So that might be actually pretty easy to add, and shouldn't cause any correctness issues.

**Comment by wojtek-t** [comment]
It seems that it gives at least 5x improvements (which seems to be enough for now).
I'm going to send out a PR for it soon.

**Comment by hongchaodeng** [comment]
> optimistically assume that the binding will succeed

It sounds OK to assume. From scheduler's perspective, binding is no different than the final step of running pod. If we think both as one logically, then:

- if succeeded, the added information is confirmed in scheduler's view
- if failed, I'm not worried about the resources being under-estimated (until we have excessive packed workload). But we need to make sure no race between the assumed info and assuming the new one.

I have one question w.r.t. failure case. What's the workflow to tell client the creation of a pod has failed? What happen if client just recreates the same pod (specifically the same name) again? I'm worried about the recreation of the same pod -- if so, cache should have a path in state machine to do re-assume.

**Comment by spiffxp** [comment]
FWIW I think we've tried optimistic bindings before (#8261) and had to rollback (#8533).  Still think this is a good idea though

**Comment by wojtek-t** [comment]
@spiffxp - yes, I remember that. But we significantly change the scheduler and I think that this time it shouldn't be a problem.

>
I have one question w.r.t. failure case. What's the workflow to tell client the creation of a pod has failed? What happen if client just recreates the same pod (specifically the same name) again? I'm worried about the recreation of the same pod -- if so, cache should have a path in state machine to do re-assume. See this.

@hongchaodeng - you cannot create the pod with exactly the same name until the previous one exists (it will just conflict in etcd, so it will fail). So you will get a "delete" event first.
