### ISSUE TITLE
Deploying Kubernetes on bare metal Ubuntu - kube-up.sh doesn't run if /tmp is mount noexec

### ISSUE THREAD

**Issue by autostatic** [kubernetes/kubernetes#24190]
When trying to run `kube-up.sh` with `KUBERNETES_PROVIDER=ubuntu` and `/tmp` mounted with the `noexec` option the process stops with the following message:
`Deploying master on machine 10.35.15.151 failed`
Nothing gets logged but after some investigating I found out that the Ubuntu scripts try to execute scripts from `/tmp` and this is not allowed when `/tmp` is mounted with `noexec`. Would it be possible to add some kind of check to the Ubuntu scripts that issues a warning when you try to use `kube-up.sh` with `/tmp` mounted `noexec`? Thanks in advance.

Jeremy

**Comment by lavalamp** [comment]
I think we're willing to accept PRs to fix this, but it's probably not going to be at the top of the list for us. Let us know if you disagree.

**Comment by autostatic** [comment]
I've submitted a PR.

**Comment by autostatic** [comment]
K8s 1.2.4, back in the days....
