### ISSUE TITLE
changing update strategy and "applying" is not allowed

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#24198]
I have a replicaset running without a deployment strategy pre-defined.

When defining one in the template, and setting its type to `Recreate`, when deploying with `kubectl apply`, I get:

```
spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

I would expect the strategy to be allowed to change using `apply`, _and_ have it apply to the current rollout as well.

**Comment by zhouhaibing089** [comment]
you could not setup `spec.strategy.rollingUpdate` while you are using `Recreate` strategy.

```
type DeploymentStrategy struct {
	// Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
	Type DeploymentStrategyType `json:"type,omitempty"`

	// Rolling update config params. Present only if DeploymentStrategyType =
	// RollingUpdate.
	//---
	// TODO: Update this to follow our convention for oneOf, whatever we decide it
	// to be.
	RollingUpdate *RollingUpdateDeployment `json:"rollingUpdate,omitempty"`
}
```

so if you decide to use `Recreate`, just try omitting the rollingUpdate part.

**Comment by JeanMertz** [comment]
@zhouhaibing089 but there is no "rollingUpdate" part in the config. I guess it's still as a "default" in the config on the server, but this prevents me from "applying" a different strategy.

**Comment by zhouhaibing089** [comment]
@JeanMertz it would help if you could paste the file you used to run `kubectl create` and `kubectl apply`, :)

**Comment by janetkuo** [comment]
@JeanMertz thanks for reporting this. It's because `spec.strategy.rollingUpdate` is added by default when you create this resource (deployment & its replica set) and apply didn't remove it when you apply the change. This sounds like a bug in `kubectl apply`. 

A workaround for this case it to use `kubectl edit` to update the `strategy`. 

@kubernetes/sig-config @kubernetes/kubectl

**Comment by janetkuo** [comment]
cc @AdoHe

**Comment by bgrant0607** [comment]
It's not a bug in apply as much as a shortcoming. apply merges changes by the user with the live state. There's no way for apply to know that those 2 fields are related. The rollingUpdate field would need to be explicitly nulled.

**Comment by AdoHe** [comment]
I did try to explicitly set the rollingUpdate field to null, but still failed. I will take a deep a look today.

**Comment by AdoHe** [comment]
I did a test like this:
```
[tony@localhost kubernetes]$ cluster/kubectl.sh create -f deployment.yaml
deployment "nginx-deployment" created
[tony@localhost kubernetes]$ cluster/kubectl.sh get deployment nginx-deployment -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2016-04-21T04:01:28Z
  generation: 2
  labels:
    name: nginx-deployment
  name: nginx-deployment
  namespace: default
  resourceVersion: "59"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx-deployment
  uid: b93e65ba-0775-11e6-b7bf-b05adacd35f7
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  observedGeneration: 2
  replicas: 3
  updatedReplicas: 3
[tony@localhost kubernetes]$ cat deployment.yaml
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
```
Then apply:
```
[tony@localhost kubernetes]$ cluster/kubectl.sh apply -f deployment_2.yaml
The Deployment "nginx-deployment" is invalid.
spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
[tony@localhost kubernetes]$ cat deployment_2.yaml
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx-deployment
spec:
  replicas: 3
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

```

**Comment by janetkuo** [comment]
It failed on my machine too even when rollingUpdate is nulled explicitly.

**Comment by AdoHe** [comment]
I will take some time to fix this.

**Comment by AdoHe** [comment]
@janetkuo I think after [Decode](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource/mapper.go#L54) here, the null `rollingUpdate` field is just missed.

**Comment by janetkuo** [comment]
@AdoHe is this one fixed?

**Comment by AdoHe** [comment]
@janetkuo even use `apply` to create the original resource, this will fail. The root cause is the default value of `strategy` is not set in client side, so the [deletionsMap](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/strategicpatch/patch.go#L1189) would be empty, and the final [patchMap](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/strategicpatch/patch.go#L1194) will not include this update.

**Comment by AdoHe** [comment]
As a workaround, user can create the original resource like this:
```
[tony@localhost kubernetes]$ cluster/kubectl.sh apply -f deployment.yaml
deployment "nginx-deployment" created
[tony@localhost kubernetes]$ cat deployment.yaml
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
```
This is just a workaround.

**Comment by AdoHe** [comment]
@bgrant0607 @janetkuo I think we really need to think about how to deal with the default value of some field, like strategy of deployment, spec.selector. Both of this issue and #26202 have this problem, the default value is not included in `last-applied-configuration`. WDYT?

**Comment by bgrant0607** [comment]
Sorry, quick response: We intentionally do not record the default values, and we should not.

**Comment by bgrant0607** [comment]
I put an explanation of apply here: https://github.com/kubernetes/kubernetes/issues/15894#issuecomment-222194015

To fix this properly, we need to represent OneOf unions in the API (there are several such cases).

Until then, the previous selection needs to be manually nulled when applying changes.

**Comment by bgrant0607** [comment]
Example of why we should not set default values in last-applied-configuration:
https://github.com/kubernetes/kubernetes/issues/25238#issuecomment-217928835

**Comment by andronat** [comment]
I'm trying to support the following configuration syntax to generate a patch that includes `null` values given by the user.

```
# Configuration file includes:
  strategy:
    type: Recreate
    rollingUpdate: null

# Kubectl patch submitted to Apiserver should include:
    "strategy": {
      "type": "Recreate",
      "rollingUpdate": null
    }
```

To achieve this we need:

- [x] Alter 3 ThreeWayMergePatch to propagate fields with `null` values to the end patch (3d7ccf4cb8fcab54a84ee77fc0a2e9ac4a7e42ea)
- [ ] Find a way to read and preserve user defined `null` values from the configuration file to Go structs (WIP: 08da2281c64685bc9c37361f3de33efd4b8d635f)

The problem rises by the fact that we:

1. Unmarshal the configuration file from the user, 
2. represent it as structs in Go
3. Marshal it to make the diff and create the patch (`CreateThreeWayMergePatch` accepts `[]byte`)

Between steps 1 and 2, `null` values are not preserved. In other words there is no way to distinct a field that is declared with null and a non existing field. Step 3 also has the problem that there is no way to print a null value.

To overcome those issues, I tried to get the configuration file as `[]byte` (read it from source) and merge it with `info.VersionedObject`.

I'll create a PR soon to discuss the issue more explicitly but any early feedback is more than welcomed.

(I'll pick up this issue)

**Comment by liggitt** [comment]
explicit nulls are propagated in apply in https://github.com/kubernetes/kubernetes/pull/40630

can you verify this is working as expected in 1.6?

**Comment by swizzlr** [comment]
I can confirm this worked for me under Kubernetes 1.6.1.

**Comment by liggitt** [comment]
Great, thanks
