### ISSUE TITLE
Unit flake in pkg/storage: TestFiltering

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#24194]
```
--- FAIL: TestFiltering (0.97s)
	cacher_test.go:167: (called from line 342)
	cacher_test.go:168: Expected: DELETED, got: ADDED
	cacher_test.go:167: (called from line 343)
	cacher_test.go:168: Expected: ADDED, got: DELETED
	cacher_test.go:171: (called from line 343)
	cacher_test.go:172: Expected (ADDED): &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"filter":"foo"}, Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc8203ae650), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc82089ec80), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}, got: &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"5", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc8206ffed0), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc8206c4c40), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}
	cacher_test.go:167: (called from line 344)
	cacher_test.go:168: Expected: MODIFIED, got: ADDED
	cacher_test.go:171: (called from line 344)
	cacher_test.go:172: Expected (MODIFIED): &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"filter":"foo"}, Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc8203ae660), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"fakeNode", SecurityContext:(*api.PodSecurityContext)(0xc82089ed00), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}, got: &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"6", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"filter":"foo"}, Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc820386e28), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc8201893c0), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}
	cacher_test.go:167: (called from line 345)
	cacher_test.go:168: Expected: DELETED, got: MODIFIED
FAIL
FAIL	k8s.io/kubernetes/pkg/storage	12.878s
```

Running in an endless loop, I wasn't able to immediately reproduce, BUT I was able to reproduce as soon as I started running `stress -c 4` in a separate terminal.

**Comment by ncdc** [comment]
cc @wojtek-t

**Comment by wojtek-t** [comment]
Will take a look

**Comment by ncdc** [comment]
cc @liggitt

**Comment by ncdc** [comment]
I'm guessing that #24008 has something to do with this

**Comment by wojtek-t** [comment]
@ncdc - I have a different hypothesis, let me verify

**Comment by wojtek-t** [comment]
Yup - the reason is different.

The problem is that if the watch is already initiated (but it still has resourceVersion in the future comparing to the cacher current state) it doesn't check if the event that it has just received is fresh enough that should be send to the watcher.

For reproducing this problem, see:
https://github.com/kubernetes/kubernetes/compare/master...wojtek-t:fix_cacher?expand=1

The test that I added there should be failing, but it's passing.

I will fix this.

**Comment by liggitt** [comment]
@wojtek-t your example shouldn't get the added event unless it occurred past resourceVersion 1000, right?

**Comment by liggitt** [comment]
oh, misread... should be failing, but is passing :)

**Comment by wojtek-t** [comment]
@liggitt - exactly;
I'm afraid I won't be able to finish the fix today. I can do it tomorrow morning (or feel free to pick it up - my test is already a reproduction to check if it is fixed :P)

**Comment by wojtek-t** [comment]
To clarify - the fix is to pass resourceVersion together with events to the "cacheWatcher" (as part of watchCacheEvent) and in filtering function check if the RV is greater then the initial one.

**Comment by liggitt** [comment]
right

**Comment by ncdc** [comment]
Does something like this look like it's going in the right direction? https://gist.github.com/47d197657af47d43a5717a2de2b68743

**Comment by wojtek-t** [comment]
@ncdc - I wanted to avoid parsing the number you are doing in process() method, and instead of that add a new field "ResourceVersion" to watchCacheEvent where we already have this parsed.
On the other hand, maybe this kind of optimization doesn't make much sense. WDYT?

**Comment by ncdc** [comment]
@wojtek-t I've now read through more of the cache code and I think it's best to avoid parsing the resource version twice. I'll update accordingly.

**Comment by ncdc** [comment]
When comparing the event's resourceVersion with the value passed to `Watch`, do we pass the event through if its resourceVersion is `>` starting value, or `>=` starting value?

**Comment by ncdc** [comment]
Also, @wojtek-t, your unit test that you added above that passes now but should fail once the corrected code is in place... is there an easy way to add a "future" test that runs quickly and won't flake? I feel like checking for the absence of an event could be problematic.

**Comment by liggitt** [comment]
> do we pass the event through if its resourceVersion is `>` starting value, or `>=` starting value?

`>`

**Comment by wojtek-t** [comment]
>
Also, @wojtek-t, your unit test that you added above that passes now but should fail once the corrected code is in place... is there an easy way to add a "future" test that runs quickly and won't flake? I feel like checking for the absence of an event could be problematic.

Yeah - that's problematic. What we can do is to wait e.g. 1s for it and pass then. It's far from being ideal, but probably better than nothing.

**Comment by ncdc** [comment]
I'm really hesitant to add something that waits 1s. That sounds really dangerous (flakey). What about sending data to etcd with various resource versions and making sure you only get the ones newer than the initial resource version?

**Comment by liggitt** [comment]
watch a few forward in the future, then add enough to reach your watch window, and ensure you didn't get the ones prior to that

**Comment by ncdc** [comment]
Yeah that's what I was thinking

**Comment by liggitt** [comment]
1. start etcd
2. add an object
3. watch at object.resourceVersion + 10
4. add 10 objects
5. ensure you only get one event
