### ISSUE TITLE
One node test cluster failed to start

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24203]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-kubemark-5-gce/1370/console

We should track how often such failures happen.

cc @dchen1107 @wojtek-t

**Comment by dchen1107** [comment]
@gmarek Thanks for filing the issue. 

Looks like the node stuck at downloading our binary. Here is what I found at startup script:

Apr 13 14:25:48 kubemark-5-master startupscript: Downloading binary release tar (https://storage.googleapis.com/kubernetes-staging-e222be933b/kubemark-5-devel/kubernetes-server-linux-amd64.tar.gz)
...

Anything change lately with our startup script?

**Comment by gmarek** [comment]
I even don't know who to ask... @mikedanese ?

**Comment by mikedanese** [comment]
Looks like [download-or-bust](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/configure-vm.sh#L144-L171) is not retrying correctly

**Comment by fejta** [comment]
Thanks Mike! Agree with Dawn and Mike that this looks more like a node or cluster issue than test infra.
