### ISSUE TITLE
Unit test flake: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#24207]
From #24150, see https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24150/kubernetes-pull-test-unit-integration/20999/

**Comment by spxtr** [comment]
```
=== RUN   TestWatch
--- FAIL: TestWatch (41.03s)
	resttest.go:945: unexpected error: client: etcd cluster is unavailable or misconfigured
	resttest.go:950: unexpected result from result channel
```

Note that this is release-1.2 branch and golang 1.5.3.

**Comment by madhusudancs** [comment]
It looks like test etcd cluster did not start correctly just for this one test. I looked at that code and am not sure what I can do to fix it. Not even sure what caused the cluster startup failure. Also, this test does what 100s of tests do, it does not do anything special while setting up the test cluster. So, I am closing this issue for now. If you see these flakes again, please reopen the issue.

**Comment by zmerlynn** [comment]
I saw this again on `release-1.2`, in a different test (`k8s.io/kubernetes/pkg/storage`)
```
cacher_test.go:119: Unexpected error: client: etcd cluster is unavailable or misconfigured cacher_test.go:130: Incorrect resource version: 8
```.

See https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24543/kubernetes-pull-test-unit-integration/22067/

**Comment by zmerlynn** [comment]
And again, in the same run on the rerun of that same `release-1.2` cherrypick:
```
=== RUN   TestWatch
--- FAIL: TestWatch (54.75s)
	resttest.go:945: unexpected error: client: etcd cluster is unavailable or misconfigured
```
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24543/kubernetes-pull-test-unit-integration/22073/

**Comment by madhusudancs** [comment]
I have now run this an aggregate total of 120,000 times across three different machines (all physical machines) and haven't encountered a single failure. Not sure how to even debug this.

Is it some environment thing? Wondering if I should run this in a GCE VM. Also, not sure how much parallelism helps.

**Comment by spxtr** [comment]
Doesn't look like anyone has linked this issue in a while, so it could just be fixed due to newer go version or something else? Unfortunately there's not an easy way to find out how often it's failing yet...

**Comment by madhusudancs** [comment]
@spxtr that's likely the case.

I am attaching a file here with 140K runs - 
[stressout.txt](https://github.com/kubernetes/kubernetes/files/264221/stressout.txt)

I am closing this issue again. Please re-open if you find a flake again.
