### ISSUE TITLE
Why can I not install addons/cluster-monitoring/google/heapster-controller.yaml?

### ISSUE THREAD

**Issue by aknuds1** [kubernetes/kubernetes#24212]
I am unable to install [cluster/addons/cluster-monitoring/google/heapster-controller.yaml](https://github.com/kubernetes/kubernetes/blob/release-1.2/cluster/addons/cluster-monitoring/google/heapster-controller.yaml) with Kubernetes 1.2 due to the following error: 

    Error from server: error when creating "/tmp/heapster-controller.yaml": Deployment in version extensions/v1beta1 cannot be handled as a Deployment: json: cannot unmarshal object into Go value of type string

What is going wrong here?

My heapster-controller.yaml looks like this (expanded from template):

    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: heapster-v1.0.2
      namespace: kube-system
      labels:
        k8s-app: heapster
        kubernetes.io/cluster-service: "true"
        version: v1.0.2
    spec:
      replicas: 1
      selector:
        matchLabels:
          k8s-app: heapster
          version: v1.0.2
      template:
        metadata:
          labels:
            k8s-app: heapster
            version: v1.0.2
        spec:
          containers:
            - image: gcr.io/google_containers/heapster:v1.0.2
              name: heapster
              resources:
                # keep request = limit to keep this container in guaranteed class
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
              command:
                - /heapster
                - --source=kubernetes.summary_api:''
                - --sink=gcm
                - --metric_resolution=60s
              volumeMounts:
                - name: ssl-certs
                  mountPath: /etc/ssl/certs
                  readOnly: true
            - image: gcr.io/google_containers/heapster:v1.0.2
              name: eventer
              resources:
                # keep request = limit to keep this container in guaranteed class
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
              command:
                - /eventer
                - --source=kubernetes:''
                - --sink=gcl
              volumeMounts:
                - name: ssl-certs
                  mountPath: /etc/ssl/certs
                  readOnly: true
            - image: gcr.io/google_containers/addon-resizer:1.0
              name: heapster-nanny
              resources:
                limits:
                  cpu: 50m
                  memory: 100Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
              env:
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              command:
                - /pod_nanny
                - --cpu=100m
                - --extra-cpu=0m
                - --memory=200Mi
                - --extra-memory=4Mi
                - --threshold=5
                - --deployment=heapster-v1.0.2
                - --container=heapster
                - --poll-period=300000
            - image: gcr.io/google_containers/addon-resizer:1.0
              name: eventer-nanny
              resources:
                limits:
                  cpu: 50m
                  memory: 100Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
              env:
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              command:
                - /pod_nanny
                - --cpu=100m
                - --extra-cpu=0m
                - --memory=200Mi
                - --extra-memory=500Ki
                - --threshold=5
                - --deployment=heapster-v1.0.2
                - --container=eventer
                - --poll-period=300000
          volumes:
            - name: ssl-certs
              hostPath:
                path: "/etc/ssl/certs"

**Comment by lavalamp** [comment]
[[Did you try the --validate flag?]]

Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by aknuds1** [comment]
@lavalamp Cool, I did.

**Comment by djzager** [comment]
If you get here via Google search, the SO post is --> http://stackoverflow.com/questions/36616652/why-can-i-not-install-google-heapster-kubernetes-addon
