### ISSUE TITLE
kubectl exec does not accept pod/foobar syntax

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#24225]
I feel like I should be able to do:

```
$ P=$(kubectl get pods -l run=hairpin-test -o name)

$ kubectl exec --tty -i $P sh
```

but I get `error: invalid resource name "pod/hairpin-test-1119317711-4qmtf": name may not contain "/"`

**Comment by AdoHe** [comment]
or we have to do something like this:
```
P=$(cluster/kubectl.sh get pod -l run=hairpin-test -o name | cut -f2 -d/)
```
sounds reasonable to me. @kubernetes/kubectl needs more comments.

**Comment by smarterclayton** [comment]
All commands that accept resources should accept resource/NAME syntax.
In this case for back compat we must only accept a single argument,
@kargakis is familiar with this.

**Comment by kargakis** [comment]
> In this case for back compat we must only accept a single argument,

Exactly. ResourceNames in the resource builder is what is needed here to handle the default resource (pod in this case) and provide the ability to specify more.

**Comment by bgrant0607** [comment]
Related #8884

**Comment by gluke77** [comment]
@thockin If nobody is working on it, I'd like to pick the issue, pls.

**Comment by gluke77** [comment]
So could you please assign me?

**Comment by thockin** [comment]
I can't assign to just anyone, unfortunately, but by responding here,
anyone else who might work on it will see that you are already in progress.

**Comment by AdoHe** [comment]
@gluke77 please go ahead, you did own this now. :)

**Comment by bronger** [comment]
Has this been reverted again?  I cannot use “pod/podname” for `kubectl exec` v1.11:
```
error: invalid resource name "pod/pop3-65987b5954-gtzvl": [may not contain '/']
```

**Comment by ryankemper** [comment]
^ Seconding the above. I'm getting the same 'may not  contain /' error. Naturally it's trivial to use unix commands to filter this, but this is such a basic feature and matches the way the rest of kubectl works, so it's quite a shocking omission.

**Comment by ryankemper** [comment]
@laurieboyes If you use selectors, you can do something like this:

`kubectl exec -it "$(kubectl get po -l app=$YOUR_APP_NAME -o name | cut -d '/' -f 2)" -c $YOUR_CONTAINER_NAME -- /bin/sh`

Otherwise you'll need to manually grep, something like this: `kubectl exec -it "$(kubectl get po -o name | grep -o $YOUR_REGEX | cut -d '/' -f 2)" -c $YOUR_CONTAINER_NAME`

**Comment by sboardwell** [comment]
FWIW you can use `custom-columns` combined with the `--no-headers` flag, e.g.
```
$ kubectl get pods -l app=mongodb --no-headers -o custom-columns=:metadata.name
my-app-mongodb
```

**Comment by osebelin** [comment]
> Just ran into this on a brand new default installation.
> 
> Local Mac Docker for Desktop
> Enabled k8 in preferences
> 
> ```
> helm init
> helm repo update
> helm install stable/postgresql
> kubectl port-forward --namespace default svc/broken-gorilla-postgresql 5432:5432 &
> ```
> error: invalid resource name "svc/broken-gorilla-postgresql": [may not contain '/']

Had the same problem. Updating kubectl resolved the issue for me.
