### ISSUE TITLE
Deployment API nit

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#24238]
For when we move out of beta?

type DeploymentStrategy has a `type` field which could be redundant with the params blocks.  Rather than:

```
type: RollingUpdate
rollingUpdate:
  maxsurge: 2
```

it could just use the existence of the rollingUpdate field as a clue that type is RollingUpdate.  We would need to add an empty `recreate` struct.  We do this other places, e.g. volumes, and it seems to work.  Any reason not to be consistent?

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @janetkuo

**Comment by bgrant0607** [comment]
This was deliberate. Some client developers have asked for discriminating types for unions.

**Comment by thockin** [comment]
I assume "some client developers" had sound enough arguments to justify the
extra cruft?  Should we then file a v2 bug to discriminate volumes and any
other places we do this?
