### ISSUE TITLE
kubectl describe --events=false flag

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#24239]
I have a demo case where I want to describe an object, but not see events.

**Comment by ncdc** [comment]
I can probably find someone to work on this

**Comment by ingvagabund** [comment]
Introduction of new flag in cobra and one if condition should be enough. Let me take a look.

**Comment by ingvagabund** [comment]
We did some analysis of the code with @hodovska. There are some points:

1. every objects has its own describe method: ``Describe(namespace, name string)``
2. ``kubectl describe`` command call factory to provide mapping of objects to describers [1]
3. kubectl then calls describe.Describe over requested object.
4. factory calls ``describerMap`` method that provides the object-to-describe mapping [2]
5. factory provides Describer method [3] that is called and returns the mapping

**Possible ways to implement the functionality**:

1. for each object extend its Describe method with additional argument for describer setting
2. extend kubectl Factory's Describer [3] with additional argument for describer setting

The former way is problematic as not every object prints events. So not every object Describe method would use the argument. Golang compiler would complained about it anyway.
 
The latter is cleaner is none of the object Describe method will have to change. On the other hand, ``Factory`` [4] data type gets modified. The ``Describer`` field is exported so it can break backward compatibility with projects that import ``k8s.io/kubernetes/pkg/kubectl/cmd/util.Factory`` symbol. On the other hand the ``Factory`` struct is filled by ``NewFactory`` method so as long as noone sets the field, it will always get initialized correctly. Other projects that call Describer method directly will have to add additional parameter with default setting for describers.

So what we recommend:

1. Introduce new data type ``DescriberSetting`` (or maybe ``DescriberConfig``):

  ```
  type DescriberSetting struct {
      ShowEvents bool
  }
  ```

  with the default settings to true.
  Later, it can be extended with other flags if it is reasonable

2. Extend Describer method [4] to

  ```
  Describer func(mapping *meta.RESTMapping, describerSetting DescriberSetting) (kubectl.Describer, error)
  ```

3. Updating ``describerMap`` [2] to inject settings to all describers that display events:

  ```
  func describerMap(c *client.Client, s DescriberSetting) map[unversioned.GroupKind]Describer {
  	m := map[unversioned.GroupKind]Describer{
  		api.Kind("Pod"):                   &PodDescriber{c, s},
  		api.Kind("ReplicationController"): &ReplicationControllerDescriber{c, s},
  		...
  ```

4. Extend all affected object describes with new ``DescriberSetting`` field and update local describe methods to display events only then ShowEvents is true.

[1] https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/describe.go#L136
[2] https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/describe.go#L79
[3] https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L341
[4] https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L91

Any suggestion how to make it better?

**Comment by ingvagabund** [comment]
@kubernetes/rh-ux @kubernetes/kubectl

**Comment by smarterclayton** [comment]
I'm ok with the proposed Describer behavior - but we should pass DescriberSetting all the way into the `kubectl.Describe` method.

**Comment by ingvagabund** [comment]
@smarterclayton all the way into the ``kubectl.Describe`` method as introduce argument to each ``Describe`` method or by injecting the ``DescriberSetting`` into each object Describer struct?

a)
```
func (d *PodDescriber) Describe(namespace, name string, setting DescriberSetting) (string, error) {
...
	if setting.ShowEvents {
	...
	}
...
}
```

or b)
```
type PodDescriber struct {
	client.Interface
	setting DescriberSetting
}

func (d *PodDescriber) Describe(namespace, name string) (string, error) {
...
	if d.setting.ShowEvents {
	...
	}
...
}
```

**Comment by smarterclayton** [comment]
Pass argument to describe - a).  There's really no need to put it it on the struct.

**Comment by fabianofranz** [comment]
I'm good with the proposal. Not every resource kind prints events but I can foresee other `DescriberSetting` values we could add in future. Making the settings an argument to `kubectl.Describe` will force every object describer to have it.

**Comment by ingvagabund** [comment]
DescriberSetting integrated, about to finish unit-tests. Thanks @hodovska for the heads-up. Will attach PR soon.

**Comment by deads2k** [comment]
> I have a demo case where I want to describe an object, but not see events.

@thockin What was the demo case?  It seems a little unusual to say, "describe this for me, but don't try to show me the available information".  I could see "tell me everything you can by looking at just this object", but specifically excluding events seems unusual.

**Comment by thockin** [comment]
Describe often has valuable, useful information - how many pods are running
in an RC, daemonset expectations, etc, but then the events flush that info
right off the screen.  Demos in particular tend to be done on a low-ish
resolution with a large-ish font.
