### ISSUE TITLE
rktnetes doesn't setup resolv.conf and hosts correctly for hostNetwork pods  

### ISSUE THREAD

**Issue by sjpotter** [kubernetes/kubernetes#24235]
Currently we write the same /etc/resolv.conf for every pod based on cluster-dns, this is incorrect, k8s depends on docker's default behavior of essentially mounting in the hosts version of those files.  This prevents master components from working correctly if run under rkt

I've looked at the code and can't seem to figure out how to make it work right,  tried specifying the files on the command line but it didn't work (https://github.com/coreos/rkt/issues/2418)

@yifan-gu

**Comment by yifan-gu** [comment]
A fix would be setting the mounts to mount the host's /etc/hosts, /etc/resolv.conf and set the hostname to host's hostname.

I had a fix on this. Need to update the tests.
