### ISSUE TITLE
kubectl pods creating showing status Container Creating

### ISSUE THREAD

**Issue by arjunm183** [kubernetes/kubernetes#24241]
Hello Team,

It will be really helpfull if someone helps me with this .

I have kubernetes  2 node cluster running sles12 and i am able to see the nodes when i do kubectl get nodes

I have an private image registry for docker and i wanted to create a pod and make them run in the node

Below is what i have done
=============================================
**Created a yaml file for pod **

host1:~ # cat walk2space.yaml
kind: Pod
apiVersion: v1
metadata:
 name: walk2space
spec:
 containers:
  - name: walk2space
    image: <private docker registry servername >:5000/walk2space:1.0
    imagePullPolicy: Always
    command: [ "echo", "SUCCESS" ]

==========================================================

**Viewing the status of the pod which i created using the above yaml file**

host1:~ # kubectl describe pod walk2space
Name:           walk2space
Namespace:      default
Node:           53.111.69.162/53.111.69.162
Start Time:     Thu, 14 Apr 2016 08:12:46 +0200
Labels:         <none>
Status:         Pending
IP:
Controllers:    <none>
Containers:
  walk2space:
    Container ID:
    Image:              <privatedocker registry servername>:5000/walk2space:1.0
    Image ID:
    Port:
    Command:
      echo
      SUCCESS
    QoS Tier:
      cpu:              BestEffort
      memory:           BestEffort
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Environment Variables:
Conditions:
  Type          Status
  Ready         False
Volumes:
  default-token-3zwlo:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-3zwlo
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  39s           39s             1       {default-scheduler }                    Normal          Scheduled       Successfully assigned walk2space to 53.111.69.162
  39s           1s              4       {kubelet 53.111.69.162}                 Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/pause:2.0\""

In the above error it shows me syncing pod failed and it connects to the internet google container but i have mentioned in my yaml to take the container from my local registry. It shows Statusbelow as container creating and on the kubelet status i get the error as below
##################
 15081 pod_workers.go:138] Error syncing pod e7f80889-0207-11e6-80ed-005056b69c1a, skipping: failed to "StartContainer" for "POD" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/pause:2.0\""
##################

========================================================

host1:~ # kubectl get pods
NAME                                READY     STATUS              RESTARTS   AGE
kubernetes-dashboard-v1.0.1-vv2qt   0/1       ContainerCreating   0          2h
walk2space                          0/1       ContainerCreating   0          44s
walk2space-3912986566-c6lun         0/1       ContainerCreating   0          2h
========================================================

Can someone help me with this on how do i run a container from a private registry instead of contacting outside world.

I would like to know is it possible to in this way.Since i have firewall restrictions in the network.

**Comment by zhouhaibing089** [comment]
`gcr.io/google_containers/pause:2.0` is the infra pod, you could pull it and then push into your own registry, then you could change the flag for kubelet:


> `--pod-infra-container-image`="gcr.io/google_containers/pause:2.0": The image whose network/ipc namespaces containers in each pod will use.

**Comment by arjunm183** [comment]
Thanks for the reply. Can you let me know how do I push this from my google repository to my private repository
That would be really a great help.

Thanks and Regards,
Arjun Murugan

**Comment by boynux** [comment]
@arjunm183:

    docker pull gcr.io/google_containers/pause:2.0
    docker tag gcr.io/google_containers/pause:2.0 your-repo:5000/pause:2.0
    docker push your-repo:5000/pause:2.0

then add `--pod-infra-container-image="your-repo:5000/pause:2.0"` to kubelet

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by arjunm183** [comment]
Hello Team,

I am unable to reach find anything in stackoverflow. As per your last update i am able to pull the image from gce named pause. and now i am getting a new error. 

 34m           14s             159     {kubelet <ip address>}                 Warning         FailedSync              Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): No command specified\n"

Please help with this case.

**Comment by anuthaa** [comment]
while deploying an application to kubernetes cluster showing :  Image: tomcat is ready, container is creating
