### ISSUE TITLE
NFS example: unable to mount the service

### ISSUE THREAD

**Issue by Smana** [kubernetes/kubernetes#24249]
Hi guys,

I just noticed that i'm not able to mount the nfs service as described in the nfs example.
Mounting using the pod's ip works fine:

```
kubectl describe po nfs-server-e6qzy | grep ^IP
IP:     10.233.127.3

mount.nfs 10.233.127.3:/ /mnt

cat /mnt/index.html
Hello from NFS!
```

But when i use the service it doesn't work

```
kubectl get svc | grep nfs
nfs-server   10.233.45.48   <none>        2049/TCP   2m

mount.nfs 10.233.45.48:/ /mnt
mount.nfs: Connection timed out
```

There are no error logs in the kube-proxy logs:

```
I0414 12:28:50.569854       1 proxier.go:415] Adding new service "default/nfs-server:" at 10.233.45.48:2049/TCP
I0414 12:28:50.569999       1 proxier.go:360] Proxying for service "default/nfs-server:" on TCP port 49291

kubectl get endpoints  | grep nfs
nfs-server   10.233.127.3:2049   8m
```

The forwarding rule seems to be configured: 

```
DNAT       tcp  --  0.0.0.0/0            10.233.45.48         /* default/nfs-server: */ tcp dpt:2049 to:10.128.0.2:49291
```

This has been reproduced with flannel and calico on GCE and baremetal.
I'm going to try with the proxy-mode = iptables, though i don't know if that will change anything.
Do you have any idea ?

**Comment by Smana** [comment]
Same behavior with iptables mode.

Further info.
Same errors after completing the steps:
```
kubectl describe po nfs-busybox-txf6o | tail -n 10

Output: mount.nfs: Connection timed out


  21s	21s	1	{kubelet smana-p8j480}		Warning	FailedSync	Error syncing pod, skipping: Mount failed: exit status 32
Mounting arguments: 10.233.45.48:/ /var/lib/kubelet/pods/bf41d3f1-023f-11e6-8ab8-42010a800002/volumes/kubernetes.io~nfs/nfs nfs []
Output: mount.nfs: Connection timed out
```

**Comment by ncdc** [comment]
When I tested this a few days ago, if I waited long enough (5 to 10 minutes), the timeout error eventually went away and everything was good. Do you see the same behavior?

cc @kubernetes/sig-network @kubernetes/rh-networking

**Comment by ovanes** [comment]
I probably found the bug/problem this. It has smth to do with the iptable rules.
If I create an RC and throw in a few more instances of the same pod everything works fine.
I saw the the load balancer was implemented with iptables as well. Here the comparisons:

Single POD + Service *DOES NOT WORK*
```
$ sudo iptables-save | grep redis-cluster
-A KUBE-SEP-3HO5IUUYYOQYCOWC -s 10.2.8.2/32 -m comment --comment "default/redis-cluster:" -j KUBE-MARK-MASQ
-A KUBE-SEP-3HO5IUUYYOQYCOWC -p tcp -m comment --comment "default/redis-cluster:" -m tcp -j DNAT --to-destination 10.2.8.2:30001
-A KUBE-SERVICES -d 10.3.0.233/32 -p tcp -m comment --comment "default/redis-cluster: cluster IP" -m tcp --dport 30001 -j KUBE-SVC-MFCTP2GDPQP4R6UC
-A KUBE-SVC-MFCTP2GDPQP4R6UC -m comment --comment "default/redis-cluster:" -j KUBE-SEP-3HO5IUUYYOQYCOWC
```

Multiple PODS + Service *WORKS*
```
$ sudo iptables-save | grep redis-ha
-A KUBE-SEP-HOO27LVK6N73KSOO -s 10.2.32.2/32 -m comment --comment "default/redis-ha:" -j KUBE-MARK-MASQ
-A KUBE-SEP-HOO27LVK6N73KSOO -p tcp -m comment --comment "default/redis-ha:" -m tcp -j DNAT --to-destination 10.2.32.2:26380
-A KUBE-SEP-QLVDFURI7RZHXDPY -s 10.2.31.2/32 -m comment --comment "default/redis-ha:" -j KUBE-MARK-MASQ
-A KUBE-SEP-QLVDFURI7RZHXDPY -p tcp -m comment --comment "default/redis-ha:" -m tcp -j DNAT --to-destination 10.2.31.2:26380
-A KUBE-SEP-TVDFKNQ4EIEH4WFO -s 10.2.72.2/32 -m comment --comment "default/redis-ha:" -j KUBE-MARK-MASQ
-A KUBE-SEP-TVDFKNQ4EIEH4WFO -p tcp -m comment --comment "default/redis-ha:" -m tcp -j DNAT --to-destination 10.2.72.2:26380
-A KUBE-SERVICES -d 10.3.0.64/32 -p tcp -m comment --comment "default/redis-ha: cluster IP" -m tcp --dport 26380 -j KUBE-SVC-2XOQJ6XFWENJIX4U
-A KUBE-SVC-2XOQJ6XFWENJIX4U -m comment --comment "default/redis-ha:" -m statistic --mode random --probability 0.33332999982 -j KUBE-SEP-QLVDFURI7RZHXDPY
-A KUBE-SVC-2XOQJ6XFWENJIX4U -m comment --comment "default/redis-ha:" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-HOO27LVK6N73KSOO
-A KUBE-SVC-2XOQJ6XFWENJIX4U -m comment --comment "default/redis-ha:" -j KUBE-SEP-TVDFKNQ4EIEH4WFO
```

Single POD promoted with RC to multiple PODs *WORKS*:
```
$ sudo iptables-save | grep redis-cluster
-A KUBE-SEP-3HO5IUUYYOQYCOWC -s 10.2.8.2/32 -m comment --comment "default/redis-cluster:" -j KUBE-MARK-MASQ
-A KUBE-SEP-3HO5IUUYYOQYCOWC -p tcp -m comment --comment "default/redis-cluster:" -m tcp -j DNAT --to-destination 10.2.8.2:30001
-A KUBE-SEP-B75DDUYBXPQEQ3V2 -s 10.2.72.3/32 -m comment --comment "default/redis-cluster:" -j KUBE-MARK-MASQ
-A KUBE-SEP-B75DDUYBXPQEQ3V2 -p tcp -m comment --comment "default/redis-cluster:" -m tcp -j DNAT --to-destination 10.2.72.3:30001
-A KUBE-SEP-YXAYEQKMTKJHNTKU -s 10.2.31.3/32 -m comment --comment "default/redis-cluster:" -j KUBE-MARK-MASQ
-A KUBE-SEP-YXAYEQKMTKJHNTKU -p tcp -m comment --comment "default/redis-cluster:" -m tcp -j DNAT --to-destination 10.2.31.3:30001
-A KUBE-SERVICES -d 10.3.0.233/32 -p tcp -m comment --comment "default/redis-cluster: cluster IP" -m tcp --dport 30001 -j KUBE-SVC-MFCTP2GDPQP4R6UC
-A KUBE-SVC-MFCTP2GDPQP4R6UC -m comment --comment "default/redis-cluster:" -m statistic --mode random --probability 0.33332999982 -j KUBE-SEP-YXAYEQKMTKJHNTKU
-A KUBE-SVC-MFCTP2GDPQP4R6UC -m comment --comment "default/redis-cluster:" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-B75DDUYBXPQEQ3V2
-A KUBE-SVC-MFCTP2GDPQP4R6UC -m comment --comment "default/redis-cluster:" -j KUBE-SEP-3HO5IUUYYOQYCOWC
```

**Comment by bprashanth** [comment]
You can't access yourself through your Service VIP in iptables kube-proxy (i.e 1 endpoint Svc, kubectl exec into endpoint, curl svc ip won't work) without either hairpin mode on all your veth's (for intf in /sys/devices/virtual/net/cbr0/brif/*; do cat $intf/hairpin_mode; done) or a promiscuous mode cbr0 (netstat -i).

**Comment by bprashanth** [comment]
The default cluster setup should give you promiscuous mode. We had a bug in between where we weren't defaulting to old hairpin behavior, but that should be fixed with: https://github.com/kubernetes/kubernetes/pull/23325. What hairpin-mode is you kubelet operationg with?

**Comment by ncdc** [comment]
@bprashanth for my test, I had:

- nfs service
- nfs server pod
- nfs pv
- pvc
- client pod using pvc

Are you saying that should not work by default?

**Comment by erinboyd** [comment]
Are you using nfsv3 or nfsv4?

**Comment by bprashanth** [comment]
As long as the client pod is talking to the Service VIP that's talking to the nfs server pod (and these 2 are different pods), hairpin mode doesn't matter. It only matters if you're talking to a service that loadbalances back to the same pod. I couldn't make out if that was what @ovanes was asking about. 

All setups should work by default. There was a window (before https://github.com/kubernetes/kubernetes/pull/23325, after 1.2)  where one configuration didn't work (i.e if you're running with --configure-cbr0=false but still using a linux bridge), for the specific hairpin mode case.

**Comment by ncdc** [comment]
@bprashanth yes, that's what I have (client pod -> service VIP -> nfs server pod). The first time it attempted to mount the PV into the client pod, it failed (connection timed out). I then waited several minutes and it magically cleared up and was able to connect and mount.

**Comment by thockin** [comment]
There's noting in the iptables dumps that indicates that there's a bug - it all looks exactly as I expect it to.  

http://docs.k8s.io/user-guide/debugging-services might apply, though I r ealize it needs an update for iptables.

**Comment by ovanes** [comment]
@bprashanth Indeed, taling to ther service from a non-service related container distributes load to all containers. Thanks for clarification.

**Comment by innovia** [comment]
Im having the same issue, after being forced to delete all the nodes (would not unmount EBS) when nodes were recreated with labels, and since then it fails for me too on connection timeout

the pod itself listen to 2049 and 111

**Comment by innovia** [comment]
the nfs image is messed up - bring up your own nfs-server and it works fine

if you need to tweak the mount points other than exports look at any entrypoint for any nfs-server docker file out there
```
FROM ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq  \
    && apt-get install -y nfs-kernel-server nfs-common \  \
    && mkdir /exports \
    && echo "/exports *(rw,fsid=0,insecure,no_root_squash)" >> /etc/exports \
    && echo "Serving /exports" \
    && /usr/sbin/exportfs -a

EXPOSE 111/udp 2049/tcp

COPY run.sh /run.sh
ENTRYPOINT  [ "/run.sh" ]
```

```
#!/bin/bash
echo "Starting NFS Server"

rpcbind
service nfs-kernel-server start

echo "Started"

echo "Done all tasks - Running continious loop to keep this container alive"
while true; do
  sleep 3600
done
```

**Comment by jingxu97** [comment]
Hi NFS users, the support of NFS on GCI image is not available on release 1.4.7 and 1.5. Please give it a try and let us know if you have any problem. Thanks!

**Comment by groundnuty** [comment]
I have tried a couple of nfs-server images from docker hub, I've built and image based on what @innovia supplied above. I've used Deployment, tried 1 and many replicas. In all cases, I can access the nfs servers when using pods ip-s, but not service ip.

Running k8s 1.5.3 on bare-metal ubuntu setup with kubeadm.

**Comment by jingxu97** [comment]
@groundnuty could you provide more details about your setup? Also could you try to use service name? I have a simple setup which uses service name and it works for me.

1. Glusterfs Pod
```
apiVersion: v1
kind: Pod 
metadata:
  name: gluster-server
  labels:
    k8s-app: glusterfs
spec:
  containers:
  - name: gluster-server
    image: gcr.io/google_containers/volume-gluster:0.5
    ports:
      - name: gluster
        hostPort: 24007
        containerPort: 24007
        protocol: TCP
      - name: glusters
        hostPort: 49152
        containerPort: 49152
        protocol: TCP
      - name: glusterfs
        hostPort: 24008
        containerPort: 24008
        protocol: TCP
```
2. Glusterfs Service

```
kind: Service
metadata:
  name: gluster-service
  labels:
    app: mine
spec:
  ports:
    - port: 24007
      name: gluster
      protocol: TCP
  selector:
    k8s-app: glusterfs
```
3. Gluster client
```
apiVersion: v1
kind: Pod
metadata:
  name: gluster-client
  labels:
    name: gluster
spec:
  containers:
  - name: app-pod
    image: redis 
    volumeMounts:
    - name: webapp 
      mountPath: /gluster
  volumes:
  - name: webapp
    glusterfs:
      endpoints: gluster-service
      path: "test_vol"
      readOnly: false
```

**Comment by maclof** [comment]
@jingxu97 how is that at all related? You're talking about GlusterFS, not NFS.

**Comment by jingxu97** [comment]
the way to mount NFS and GLusterFS is very similar. It would be very helpful if you could provide more details about your set up so that I can have a try to see the problem. Thanks!

**Comment by groundnuty** [comment]
@jingxu97 I was not able to test glusterfs (need to install some packages on nodes to make it work), but after modifying your example for NFS it seems to be working well. 

As some people here tested this against single pod and multiple-pod setups, I provide single and multiple files for testing. 

*IMPORTANT*: Please modify nfs volume server field in the client pods so that it matches the service.

Single pod test:
~~~
---
#Single NFS Server Pod
apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  labels:
    k8s-app: nfs-pod
    tag: nfs-pod-test
spec:
  containers:
  - name: nfs-server
    image: gcr.io/google-samples/nfs-server:1.1
    ports:
      - name: nfs
        hostPort: 2049
        containerPort: 2049
        protocol: TCP
      - name: mountd
        hostPort: 20048
        containerPort: 20048
        protocol: TCP
      - name: rpcbind
        hostPort: 111
        containerPort: 111
        protocol: TCP
    securityContext:
      privileged: true
---
#Single Pod NFS Service
kind: Service
metadata:
  name: nfs-pod-service
  labels:
    k8s-app: nfs-pod
    tag: nfs-pod-test
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
    - name: mountd
      port: 20048
      protocol: TCP
    - name: rpcbind
      port: 111
      protocol: TCP
  selector:
    k8s-app: nfs-pod
    tag: nfs-pod-test
---
#Single Pod NFS client
apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod-client
  labels:
    name: nfs-pod-client
    tag: nfs-pod-test
spec:
  containers:
  - name: app-pod
    image: redis
    volumeMounts:
    - name: webapp
      mountPath: /mnt
  volumes:
  - name: webapp
    nfs:
      # FIXME: The ip or domain of nfs-pod-service
      server: nfs-pod-service.default.svc.cluster.local
      path: "/exports"
      readOnly: false
~~~

Multiple pods test:
~~~
---
#Group of NFS Server Pods
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-servers
  labels:
    k8s-app: nfs-pods
    tag: nfs-pods-test
spec:
  replicas: 3
  template:
    metadata:
      name: nfs-server
      labels:
        k8s-app: nfs-pods
        tag: nfs-pods-test
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google-samples/nfs-server:1.1
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
---
#Group of Pods NFS Service
kind: Service
metadata:
  name: nfs-pods-service
  labels:
    app: mine
    tag: nfs-pods-test
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
    - name: mountd
      port: 20048
      protocol: TCP
    - name: rpcbind
      port: 111
      protocol: TCP
  selector:
    k8s-app: nfs-pods
    tag: nfs-pods-test
---
#Group of Pods NFS client
apiVersion: v1
kind: Pod
metadata:
  name: nfs-pods-clientt
  labels:
    name: nfs-pods-client
    tag: nfs-pods-test
spec:
  containers:
  - name: app-pod
    image: redis
    volumeMounts:
    - name: webapp
      mountPath: /mnt
  volumes:
  - name: webapp
    nfs:
      # FIXME: The ip or domain of nfs-pods-service
      server: nfs-pods-service.default.svc.cluster.local
      path: "/exports"
      readOnly: false
~~~

**Comment by xiaokugua250** [comment]
i found a new way to solve this problem ,you can set nfs-server port to be fixed ,then mount nfs-server by service . you can refer to https://wiki.debian.org/SecuringNFS. 

![image](https://user-images.githubusercontent.com/4617763/50872442-bcb15200-13fa-11e9-8681-69382ec87a66.png)
![image](https://user-images.githubusercontent.com/4617763/50872610-e0749800-13fa-11e9-97bc-046e210e8ee0.png)
![image](https://user-images.githubusercontent.com/4617763/50872993-f7b38580-13fa-11e9-9a20-a7b56fd439a2.png)
