### ISSUE TITLE
vagrant developer guide vs vagrant getting started guide (dup or missing?)

### ISSUE THREAD

**Issue by mikebrow** [kubernetes/kubernetes#24259]
Vagrant getting started guide:

The file: kubernetes/docs/getting-started-guides/vagrant.md is an empty shell pointing to its new location on the web at http://releases.k8s.io/release-1.2/docs/getting-started-guides/vagrant.md with the source for said web page being located at kubernetes.github.io/docs/getting-started-guides/vagrant.md. 

All good so far.

At the bottom of the web page there is a link to a vagrant developer guide, see:

```
I want to make changes to Kubernetes code!

To set up a vagrant cluster for hacking, follow the vagrant developer guide.

```
The link points to https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/devel/developer-guides/vagrant.md.

However, after reviewing the differences docs/devel/developer-guides/vagrant.md is really just an older version of the getting-started-guides/vagrant.md which as discussed above has moved to kubernetes/kubernetes.github.io/docs/getting-started-guides/vagrant.md.

Suggested resolution:

1) In this fork -  either (a) make docs/devel/developer-guides/vagrant.md an empty shell pointing to the same location that docs/getting-started-guides/vagrant.md is pointing to or (b) delete docs/devel/developer-guides/vagrant.md. Note vagrant.md is currently the only file in the devel/developer-guides tree.

2) On the kubernetest.github.io fork remove the pointer to the "for hacking" vagrant developer guide.  

Suggestions? Comments? If it is agreed that 1a or 1b makes sense I'll gladly PR the two forks.

**Comment by lavalamp** [comment]
@johndmulhausen

**Comment by bgrant0607** [comment]
cc @derekwaynecarr @dlorenc @vishh

**Comment by bgrant0607** [comment]
@mikebrow Did you see the "This file has moved to..." message?

**Comment by mikebrow** [comment]
@bgrant0607 Yes, I did.  Both versions of the vagrant doc that are in the kubernetes fork point to the new location. That's not the issue.  There are currently three different versions of vagrant.md. (1) Two of the three different versions are in the kubernetes fork.  getting-started-guides/vagrant.md is empty pointing to it's new location (good)...  devel/developer-guides/vagrant.md is not empty, yes it points to it's new location...  I presume this version should be made empty or simply deleted.  (2) The new version in k8s.io is incorrectly pointing to https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/devel/developer-guides/vagrant.md (the old incorrect version) The old link says it is a link "To set up a vagrant cluster for hacking, follow the vagrant developer guide."  But there is no vagrant hacking guide for developers there is only the getting started guide.  Thus this link is pointing to an older version of itself.

**Comment by mikebrow** [comment]
NVM... I just saw that Vish recently deleted vagrant.md (the latest version of the doc) from the kubernetes.github.io/docs/getting-started-guides directory.  https://github.com/kubernetes/kubernetes.github.io/pull/294

Closing this issue.
