### ISSUE TITLE
FLANNEL_OTHER_NET_CONFIG emptied after export

### ISSUE THREAD

**Issue by autostatic** [kubernetes/kubernetes#24251]
Currently `cluster/ubuntu/config-default.sh` has the following lines:

``` bash
# Optionally add other contents to the Flannel configuration JSON
# object normally stored in etcd as /coreos.com/network/config.  Use
# JSON syntax suitable for insertion into a JSON object constructor
# after other field name:value pairs.  For example:
# FLANNEL_OTHER_NET_CONFIG=', "SubnetMin": "172.16.10.0", "SubnetMax": "172.16.90.0"'

export FLANNEL_OTHER_NET_CONFIG
FLANNEL_OTHER_NET_CONFIG=''
```

So when uncommenting or copying the example `FLANNEL_OTHER_NET_CONFIG` line the variable gets set, then exported and successively emptied which could result in errors like "Failed to acquire subnet: out of subnets" on the nodes. Would it be an option to change the example line by prepending it with the `export` command and omitting the following export of the variable and the line setting the variable to an empty value? So like this:

``` bash
# Optionally add other contents to the Flannel configuration JSON
# object normally stored in etcd as /coreos.com/network/config.  Use
# JSON syntax suitable for insertion into a JSON object constructor
# after other field name:value pairs.  For example:
# export FLANNEL_OTHER_NET_CONFIG=', "SubnetMin": "172.16.10.0", "SubnetMax": "172.16.90.0"'
```

If preferred I could put this in a PR too of course.

Jeremy

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
because `cluster/*` scripts

/assign
closing because I can't find FLANNEL_OTHER_NET_CONFIG in the `cluster/*` scripts anymore
