### ISSUE TITLE
Organize examples

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#24264]
Forked from #24260 and other issues.

We need to organize the examples by category:
- monitoring
- logging
- storage
- database
- multi-tier
- paas
  ...

cc @kubernetes/examples

**Comment by bgrant0607** [comment]
Dupe of #22618

**Comment by ahmetb** [comment]
We moved the examples to their own repo (https://github.com/kubernetes/examples) for further maintenance and the intention is to remove examples such as the ones categorized above in the long term if people do not stand up for maintaining them.

I this we can just close this issue.
