### ISSUE TITLE
Turn prometheus into a real example

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#24260]
Don't understand why this is in contrib:
https://github.com/kubernetes/contrib/tree/master/prometheus

It's not very discoverable there.

We should also group all monitoring-related examples together somehow.

cc @mikedanese @mwielgus @jayunit100 @kubernetes/examples

**Comment by bgrant0607** [comment]
cc @jimmidyson

**Comment by jimmidyson** [comment]
cc @fabxc

**Comment by chancez** [comment]
I took some of @jimmidyson's existing dashboards and tidied them up a bit, to fix issues like orphaned grafana panels for pods long-gone, etc. I'd be glad to help get some of those initial dashboards working. I also worked through getting things working with grafana (v3.0.0-beta7 atm) with Prometheus 0.18.0. 

Let me know if you guys want some of that, and I can get that stuff exported.

**Comment by spiffxp** [comment]
/assign
closing because we now have https://github.com/kubernetes/charts/tree/master/stable/prometheus and https://github.com/coreos/prometheus-operator (both of which are linked by the contrib README now)
