### ISSUE TITLE
Scalability flake: Not all pods in namespace 'kube-system' running and ready within 10m0s

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24265]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/6129/

https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/6129/

**Comment by lavalamp** [comment]
Again.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/6136/

https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/6136/

**Comment by lavalamp** [comment]
@davidopp to delegate

**Comment by wojtek-t** [comment]
To clarify - this is more "cluster failed to start" than "scalability failure". We didn't even start tests in those runs.

**Comment by wojtek-t** [comment]
@gmarek @kubernetes/goog-node

**Comment by wojtek-t** [comment]
Unfortunately, we again don't have logs from components from runs where we didn't started tests.
@spxtr @fejta - can we do something about it?

**Comment by gmarek** [comment]
I think it may be indeed a control plan thing - my experience with such failures is that it's caused by an OOM in some addon. We should come up with limits that actually work for big clusters.

**Comment by wojtek-t** [comment]
I think we need logs to confirm this hypothesis (but I agree that sounds reasonable).

**Comment by wojtek-t** [comment]
Sorry, it seems that from some runs we have logs.

So I took a look into the logs:
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/6136/artifacts

And basically the reason from both v3g1 and llq3 nodes is that Kubelet hung on "pulling image for fluentd" - it started pulling and it never finished.

@yujuhong @dchen1107 - do we have any timeouts for pulling the image? Can we somehow avoid such errors (97 kubelets correctly pulled that image). Maybe if it failed after say 1m, recreating it would help? Is there anything we can do with that as a quick fix?

**Comment by Random-Liu** [comment]
@wojtek-t That's why we decided to switching to the official docker client #23563.
After #23800 is merged, we can add timeout for `PullImage` and report image pulling progress in a following PR soon. I think that will help us avoid or at least better surface the reason of this issue.

**Comment by gmarek** [comment]
@Random-Liu - that's great. I'm removing flake and priority labels, as it seems to be a known issue with a fix on a way.

**Comment by dchen1107** [comment]
We are introducing timeout to all docker related operations for 1.3 release, including PullImage. On another hand, we are talking to our image team, who is building Container Registry Mirror. Hope that integration will make image pulling performance much better and much predictable.

**Comment by spiffxp** [comment]
/sig scalability

/assign
closing because https://k8s-testgrid.appspot.com/google-gce#gce-scalability doesn't appear to be failing due to this
