### ISSUE TITLE
Jenkins unit/integration tests don't survive control plane/node update

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#24267]
My PR was unlucky enough to be running tests while the cluster was updated to 1.2. It eventually timed out at the 1h mark, but all over the place there were failures:

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23594/kubernetes-pull-test-unit-integration/21280/

```
E0414 10:13:18.924328   12588 kubelet.go:1020] Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]
I0414 10:13:18.925563   12588 manager.go:123] Starting to sync pod status with apiserver
I0414 10:13:18.925672   12588 kubelet.go:2395] Starting kubelet main sync loop.
I0414 10:13:18.925912   12588 kubelet.go:2404] skipping pod synchronization - [Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory] container runtime is down]
E0414 10:13:18.925818   12588 kubelet.go:2749] Container runtime sanity check failed: container runtime version is older than 1.20
[...]
```

And a lot more. I'm assuming that others like this are not fatal:
```
E0414 10:13:20.613259   12667 reflector.go:316] pkg/controller/serviceaccount/serviceaccounts_controller.go:139: Failed to watch *api.ServiceAccount: too old resource version: 4 (13)
```

**Comment by therc** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
If you're talking about the upgrade I was chattering about in slack at the same time, the upgrade was of the cluster running the submit queue, not jenkins. So it's unrelated.

**Comment by lavalamp** [comment]
```

Build timed out (after 60 minutes). Marking the build as aborted.
Build timed out (after 60 minutes). Marking the build as failed.
FATAL: Unable to delete script file /tmp/hudson5866264222592844755.sh
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:147)
	at hudson.remoting.Channel.call(Channel.java:780)
	at hudson.FilePath.act(FilePath.java:979)
	at hudson.FilePath.act(FilePath.java:968)
	at hudson.FilePath.delete(FilePath.java:1422)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:104)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:64)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build was aborted
Recording test results
```

This is actually a timeout problem.

**Comment by lavalamp** [comment]
@spxtr who is looking at other timeout problems.

@spxtr @ixdy @fejta I think we need one place in the system to put a "this is how long a build should take" setting, since every time that changes many of our builds start flaking?

**Comment by spxtr** [comment]
I don't think the unit/integration job should have gotten slower with the build, since it only builds for linux/amd64.

**Comment by therc** [comment]
Is this a dupe of #24325, due to excessive load on Jenkins?

**Comment by spxtr** [comment]
I'm a little confused by this. The unit/integration tests don't spin up a cluster, they only use what's in your source tree.

As for Jenkins timeouts, our unit/integration runs have been getting a little slower for various reasons, so I bumped the timeout to keep them 2x their current average time.

> Is this a dupe of #24325, due to excessive load on Jenkins?

I don't think so, since it's on PR Jenkins where we more carefully control how many jobs can be running at the same time on each node.
