### ISSUE TITLE
Bad pod may affect whole cluster

### ISSUE THREAD

**Issue by roman-shuhov** [kubernetes/kubernetes#24276]
We recently got an issue with pods that had a small memory limit. It was good enough to start the pod, but it fails as soon as it gets any load. In our case, it was Apache container with 32Mb limit.

Kubernetes tries to reschedule it, but keeps getting OOM errors, and at the end this generates a lot of traffic (66.7 Mbit/s in an empty cluster) and, as a result, a lot of nodes went down, which made the whole cluster unusable.

It was fixed by removing these pods and restarting failed nodes. 

As a side note, we have these pods in a separate namespace with a specified resource quota, but this didn't save us from this issue.

I think it makes sense to implement an ability to set up a restart limit for pods.

**Comment by lavalamp** [comment]
How many of these pods were you running? I don't think network traffic should take down nodes. Why did the nodes go down?

**Comment by yujuhong** [comment]
What did you use to create these pods and how did they get rescheduled?

**Comment by roman-shuhov** [comment]
I have 2 deployment objects, each with 8 pods. Nodes went down because of a lot OOM errors, as  i see from documentation of the killed containers can be pricey. 

I can send you more details in private messages...

**Comment by roman-shuhov** [comment]
I saw a lot of errors such as 

API error (500): Cannot start container 30a5f1ccb9590669560f80f5f84f3b6c34d0565b84fde936961073f0bbad7b5b: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-30a5f1ccb9590669560f80f5f84f3b6c34d0565b84fde936961073f0bbad7b5b.scope/cpu.cfs_quota_us: no such file or directory

**Comment by yujuhong** [comment]
> I have 2 deployment objects, each with 8 pods. Nodes went down because of a lot OOM errors, as i see from documentation of the killed containers can be pricey.

Killing containers are pricey.. but not this pricey. In our e2e tests, we kill 100 pods on one node every build. 

Could you elaborate more on how a node behaves when it's considered "down"? Was kubelet still posting the node status or did it record any event explaining why (i.e., `kubectl describe node <node_name>`)?
The output of this command should also help us know the version of kubelet and docker.


> API error (500): Cannot start container 30a5f1ccb9590669560f80f5f84f3b6c34d0565b84fde936961073f0bbad7b5b: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-30a5f1ccb9590669560f80f5f84f3b6c34d0565b84fde936961073f0bbad7b5b.scope/cpu.cfs_quota_us: no such file or directory

What's your kernel version? kubelet [enabled `--cpu-cfs-quota` in v1.2 by default](https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/admin/kubelet.md). You can set this flag to false to disable this feature. Nonetheless, this should not cause the node to crash.

**Comment by roman-shuhov** [comment]
here is some details - https://gist.github.com/roman-shuhov/dae32f27d85b1596bdc520ec7e53fd3a
here is Deployment which caused this - https://gist.github.com/roman-shuhov/cb6046795b3e2389b4420b86af5390de

**Comment by yujuhong** [comment]
@roman-shuhov Most of your nodes encountered multiple system OOMs:
```
  23m		23m		2	{kubelet ip-10-242-128-66.ec2.internal}				Warning		SystemOOM		System OOM encountered
  21m		21m		1	{kube-proxy ip-10-242-128-66.ec2.internal}			Normal		Starting		Starting kube-proxy.
  21m		21m		1	{kubelet ip-10-242-128-66.ec2.internal}				Normal		Starting		Starting kubelet.
```
Looks like kubelet and/or docker might have been killed in this case. From what I can see, the `kubectl describe` output indicates that your nodes were *not* over-committed at the time of querying as far as k8s knows. However, even if you did over commit the node, kubelet/docker should have lower oom scores than pods with no QoS guarantees.  Was there any other non-k8s workload running on your nodes that could've consumed significant amount of memory? Are there any error messages in kubelet.log that implied kubelet could not apply the oom scores correctly?

**Comment by roman-shuhov** [comment]
Nothing else was running in this cluster. It wasn't over-commited as well. Don't have kubelet.log

**Comment by yujuhong** [comment]
If nothing else was running in your cluster, then some pods and/or kubelet/docker  must've been behaving badly. I'd like to rule out the possibility that docker or kubelet was leaking memory -- have you seen high memory from either of them? If we can rule out the daemons, the next questions are 1) which pod(s) was using all the memory and 2) why wouldn't the pod(s) be killed first.

**Comment by roman-shuhov** [comment]
Here is a `mayday` log from one bad node 
https://transfer.sh/s2vhB/mayday.tar.gz

**Comment by roman-shuhov** [comment]
@yujuhong Did you have a change to check it? Do you need any other input from me? Overall it was 10 pods which were restarted about 1K times each

**Comment by yujuhong** [comment]
@roman-shuhov, the `mayday` tarball doesn't include information of memory usage per process, or kernel logs, so it doesn't seem that useful to me. I think it's necessary to nail down which process is using up all the memory though.

cc more folks @kubernetes/sig-node to see if anyone has better idea or more insights..

**Comment by roman-shuhov** [comment]
these nodes had a free memory available... OOM happened because pods tried to use more memory than allowed

**Comment by yujuhong** [comment]
> these nodes had a free memory available... OOM happened because pods tried to use more memory than allowed

AFAIK, kubelet reports the "system oom" event when the machine is out of memory (not when the container is killed). Your kubelet (or maybe docker as well) was restarted a few times probably due to this.
You can check our kern.log for related messages. An example for the system oom event: https://github.com/google/cadvisor/blob/b9e36443c490f54cee2f1539d27364730a226e33/utils/oomparser/systemOomExampleLog.txt
For a regular container oom: 
https://github.com/google/cadvisor/blob/b9e36443c490f54cee2f1539d27364730a226e33/utils/oomparser/containerOomExampleLog.txt

**Comment by quinton-hoole** [comment]
@yujuhong Anything remaining to be done here?  Can this be closed?
