### ISSUE TITLE
httpHeaders in httpGet probe does not work for Host header.

### ISSUE THREAD

**Issue by errm** [kubernetes/kubernetes#24288]
I noticed that httpHeaders were added to the httpGet probe in #20116 to fix #14713

Sadly the httpHeaders addition to the httpGet probe does function correctly for all headers *except* the `Host` header.  I think this must be to do with the way `net/http` make a special case of the Host header [for example](https://groups.google.com/forum/#!topic/golang-nuts/pvG-9DSkKaw) [and](https://golang.org/pkg/net/http/#Request).

I have some code I used to debug the issue that I can share if needed.

**Comment by lavalamp** [comment]
Sigh, letting you set Host was the entire point of providing that option.

**Comment by bassrock** [comment]
@errm Does the host header work in probes now? I have been browsing the issues but can not tell, as I am having trouble with it in my setup.

**Comment by errm** [comment]
@bassrock my fix should be in kubernetes 1.2.3+

I found some code that exercises the issue... could you try this on your cluster https://github.com/errm/muffins

I cannot reproduce in the environment I have to hand that is running k8s 1.7
