### ISSUE TITLE
Cassandra on Kubernetes - Seed Provider and Snitch

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#24286]
# Background

This project currently contains a custom [SeedProvider](https://github.com/kubernetes/kubernetes/blob/master/examples/cassandra/java/src/io/k8s/cassandra/KubernetesSeedProvider.java) that allows for discovery within a kubernetes cluster.  This issue is covering design and improvements around this initiative.  Once stable these components are stable recommended that this code gets moved into the Apache Cassandra code base.  But since the code lives here ... This is where we start.

# Definitions

## Seed Provider / Gossip

https://docs.datastax.com/en/cassandra/3.x/cassandra/configuration/configCassandra_yaml.html?scroll=configCassandra_yaml__seed_provider

> When a node first starts up, it looks at its cassandra.yaml configuration file to determine the name of the Cassandra cluster it belongs to; which nodes (called seeds) to contact to obtain information about the other nodes in the cluster; and other parameters for determining port and range information.

> seed_provider 
> The addresses of hosts deemed contact points. Cassandra nodes use the -seeds list to find each other and learn the topology of the ring.
> class_name (Default: org.apache.cassandra.locator.SimpleSeedProvider)
> The class within Cassandra that handles the seed logic. It can be customized, but this is typically not required.
> 
> - seeds (Default: 127.0.0.1)
> A comma-delimited list of IP addresses used by gossip for bootstrapping new nodes joining a cluster. When running multiple nodes, you must change the list from the default value. In multiple data-center clusters, it is a good idea to include at least one node from each data center (replication group) in the seed list. Designating more than a single seed node per data center is recommended for fault tolerance. Otherwise, gossip has to communicate with another data center when bootstrapping a node. Making every node a seed node is not recommended because of increased maintenance and reduced gossip performance. Gossip optimization is not critical, but it is recommended to use a small seed list (approximately three nodes per data center).

Snitches - https://docs.datastax.com/en/cassandra/3.x/cassandra/architecture/archSnitchesAbout.html

> A snitch determines which data centers and racks nodes belong to. They inform Cassandra about the network topology so that requests are routed efficiently and allows Cassandra to distribute replicas by grouping machines into data centers and racks. Specifically, the replication strategy places the replicas based on the information provided by the new snitch. All nodes must return to the same rack and data center. Cassandra does its best not to have more than one replica on the same rack (which is not necessarily a physical location).

# Tasks

- Document Current State - Document how the current provider operates, and is configured
- Asses Architecture - Are there any short term changes that are recommended
- PetSet - Determine architecture with future needs of the PetSet initiative
- Write code and drink much Scotch or Green Tea.
- Determine needs for allowing racks and multiple datacenter implementations.

# Current Challenges

- Documentation is lacking
- Current seed provider sets every C* node as a seed ... not the best
- Code is not tested well
- Code is not built on correct version
- No multi rack support
- No multiple DC support

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by chrislovecnm** [comment]
From @bgrant0607 - thoughts?

> So from a quick look at the seed provider, I have a couple of questions. Looks like we're using endpoint ips https://github.com/chrislovecnm/kubernetes/blob/cassandra-seed-provider-docs/examples/cassandra/java/src/io/k8s/cassandra/KubernetesSeedProvider.java#L149

That is correct!

> What happens If the Service just doensn't have endpoints populated yet? (most people put the service def in the same file as the RC used for cassandra and kubectl create -f, so if the cassandra pods start running before the endpoints are populated all of them will set themselves as the seed right?)

It looks like the provider will drop back to the
`- seeds:  "110.82.155.0,110.82.155.3"`

In `cassandra.yaml`.
But the default value is 127.0.0.1.  More testing needs to occur.

> What happens if the IP of your seed goes down and gets re-assigned to some other container (either a cassandra node in your cluster, another cassandra cluster or like an unrelated nginx pod) and we're bringing up a node that still observes the old list of endpoints (so it gets the wrong ip).

This provider needs to be tweaked to only provide 2 or some number of active seeds. 

> Using the global endpoints list and IP doesn't sound reliable. I'd rather have each c* pod update, eg a config map with its own hostname (which it gets by running hostname), and takes the first member of the list in the config map as the seed.

So a couple of things:
- We need 2-3 nodes for redundancy
- Picking the same nodes all the time would be helpful
- How would we configure the config map before the cassandra nodes are up?  I am thinking we have a causality dilemma. 

> If we only start one at a time, it's a guaranteed single writer to that config map. Changes to the configmap are reflected in all pods that mount it. That hostname will never get re-assigned even when the pod gets rescheduled.

We may be saying the same thing.  But a use case is this: 
1. We deploy six C* nodes in a cluster. 
2. First node uses 127.0.0.1 as the seed
3. x number of C* nodes need to be seeds.  2 or 3 seeds is recommended. 
4. If one of the C* seeds is lost the provider needs to responds with two valid C* node ip addresses. 
5. `nodetool decommision` has to be run to remove the dead node.

> Doing that won't be easy without petset, but just throwing it out there to get your thoughts.

I think we are ok even without PetSet

**Comment by bprashanth** [comment]
so say you want 2 seeds.

The first node comes up, updates the config map with the output of hostname (no endpoint watching or IPs).
config map=[c1.default.cluster.local]
config file on disk for c1: seeds [c1]

Second node comes up, gets the config map, sees it's the second node and appends to the list:
config map=[c1, c2]
config file on disk for c1: [c1, c2]
config file on disk for c2: [c1, c2]

Each node comes up, see there are already 2 nodes in the map and just set those as seeds. 
The important part here is (I think):   

1. Single writer to config map, so there's no race for seed position
2. c1 and c2 are hostnames, and don't ever get reassigned to pods from another c* cluster
3. If c1 or c2 go down, they will always comes back up with the same volume (that's not to say there isn't a partition scenario where we wouldn't need a babysitter process, but lets go for the simple case first)

> How would we configure the config map before the cassandra nodes are up? I am thinking we have a causality dilemma.

"Init containers" or "pre-start" hooks is a work in progress, but even today, you can create an entrypoint script that first updats config map and then starts the c* daemon. 

> I think we are ok even without PetSet

of course it will, without petset you need to create 1 service per node to get persistent ips/hostnames, and you can't guarantee single writer to any shared state because the RC will start a new pod ASAP (i.e while the old one is running, so in your 1 Service per c* pod example you will have 2 c* pods behind the service for some span of time). Also there will always be a propogation delay between when an ip can get re-assigned to some other pod in your cluster and the endpoints list is updated. It's possible to build a seed provider that works aroud these, but I'm not sure it's worth it.

**Comment by chrislovecnm** [comment]
Also openned https://issues.apache.org/jira/browse/CASSANDRA-11585 requesting assistance, and contacted a couple of gurus.

**Comment by chrislovecnm** [comment]
PR is in with intial documentation for how the Seed Provider works: https://github.com/kubernetes/kubernetes/pull/24296

**Comment by chrislovecnm** [comment]
PR is in updating example https://github.com/kubernetes/kubernetes/pull/24945

**Comment by chrislovecnm** [comment]
PR is in refactoring SeedProvider https://github.com/kubernetes/kubernetes/pull/24945

**Comment by shashiranjan84** [comment]
@chrislovecnm is there a way to control the version of Cassandra I want use.  For my application(Kong) which currently only supports Cassandra 2.2, I tried using gcr.io/google-samples/cassandra:v8 but its failing with 
![screenshot 2016-08-26 14 23 25](https://cloud.githubusercontent.com/assets/8146958/18020883/c6c0efe2-6b98-11e6-8d36-e623203116c5.png)

gcr.io/google-samples/cassandra:v9 works find but it comes with Cassandra 3.5. 

Thanks
Shashi

**Comment by chrislovecnm** [comment]
Which version of k8s are u using? What version of Cassandra do you need?

**Comment by shashiranjan84** [comment]
1.3

![screenshot 2016-08-26 15 01 08](https://cloud.githubusercontent.com/assets/8146958/18021680/f6e29018-6b9d-11e6-8f6a-296733586075.png)

**Comment by shashiranjan84** [comment]
Looking for Cassandra v 2.2.x

**Comment by chrislovecnm** [comment]
I think the problem you are having is with the seed provider, and you need to use a version that is compiled against c* 2.2 binaries. Have not looked if we released a version.

The other option, which is in alpha with 1.3 is pet set. Here is my PR https://github.com/kubernetes/kubernetes/pull/30577#event-768260534

**Comment by chrislovecnm** [comment]
To be clear if use my pet set example you don't need the seed provider, also you will need to build you own docker. The docker will need to use the correct cassandra.yaml.

**Comment by shashiranjan84** [comment]
ok thanks @chrislovecnm, I will give it a try.

**Comment by chrislovecnm** [comment]
@bgrant0607 https://github.com/kubernetes/kubernetes/pull/30577 is merged, closing.

**Comment by GordonJiang** [comment]
@chrislovecnm, see this thread be closed 20 days back. Is it resolved? Are we able to deploy cassandra in Petset for multiple datacenter in kubernetes? The key is cassandra nodes in different datacenter needs to talk to each other for data replication. How can we achieve it in kubernetes?

**Comment by chrislovecnm** [comment]
We are able to deploy multiple DC inside the same cluster. Theoretically with the correct routing you should be able to route cross cluster, but have not done that. So I have not had time to try 2x C* DC in 2x K8s clusters. We should have another issue open about the routing.

**Comment by blak3mill3r** [comment]
I've done something similar on AWS with IPsec for Kafka replication. If you make a virtual bridge across regions between 2 vpc subnets, the nodes will all see stable addresses/names

**Comment by chrislovecnm** [comment]
@blak3mil3r do you have that documented?

**Comment by chrislovecnm** [comment]
Sorry I typo'ed your name @blak3mill3r and am on mobile ... Edit button GitHub

**Comment by blak3mill3r** [comment]
@chrislovecnm Sort of... not very _well_ documented, but I do have notes. I should clarify though: I'm only talking about setting up a secure VPN tunnel connecting two private VPC subnets in different regions... I did not combine that with k8s Petsets. I can't see why it wouldn't work though, if k8s exposes the nodes in a Petset to the VPC, and the IPsec tunnel allows connecting from the remote VPC ...

I'm interested in trying it, but unfortunately I won't be able to dedicate time to it right away. I'd be glad to dig up my notes on the tunneling config and share them (not at the office now).

**Comment by blak3mill3r** [comment]
After reading more on Petsets, it's not clear to me that it supports exposing each pet as a stable IP/name.

**Comment by chrislovecnm** [comment]
@blak3mill3r first can we open an issue, secondly static IPs are an enhancement that I have requested.

**Comment by surajpasuparthy** [comment]
@chrislovecnm 
Would be possible to have a tunnel between the 2 k8s clusters, enable source NAT on the kube proxy to enable handshaking between the cluster IPs?
The POD IPs would be private in the K8S network. so would just a handshake between the service IPs of C* on both the K8s be sufficient to set up a sync across clusters ?

**Comment by chrislovecnm** [comment]
Every C* instance has to talk to every other C* instance.

**Comment by surajpasuparthy** [comment]
Ah, i feared as much.
So is Ubernetes the ONLY way i can expose the POD ips on say DC1 to DC2 ? is there any possible configuration i could have to set up multi DC sync across kubernetes clusters without ubernetes.
At the moment, i have a workaround by using the "hostNetwork=true" for the cassandra deployment yaml file. Doing this will assign my VMs ip as the pod ip for cassandra. The limitations being i can have only 1 pod for cassandra and ofcourse the host network being exposed.
Any suggestion to can get around this issue?

**Comment by chrislovecnm** [comment]
@surajpasuparthy no this is a routing problem not a federation / ubernetes problem.  You have to route between nodes, which is a pure networking issue.

**Comment by surajpasuparthy** [comment]
@chrislovecnm 
I see, could you give me an idea about how i can set up this networking ?
So far, i only can think of a tunnel (TLS) between the 2 VMs(2 single node K8S clusters). but that will still forward the handshake only to the svc ip and the Pod IPs are private to the cluster.
Thanks in advance

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kubernetes/issues/27239 is where I would ask you to continue this conversation, and I will close this again.

**Comment by chrislovecnm** [comment]
Closing this please refer to https://github.com/kubernetes/kubernetes/issues/27239 in order to network K8s clusters together.
