### ISSUE TITLE
Unit test flake: TestCheckVersionCompatibility() Expected value not to be nil

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#24298]
The recently merged PR #21741 added a version cache in dockertools, which makes the test [`TestCheckVersionCompatibility`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager_test.go#L1856-L1895) flaky.
```
--- FAIL: TestCheckVersionCompatibility (0.01s)
         <autogenerated>:31:                                 Error Trace:    manager_test.go:1892
                 Error:          Expected value not to be nil.
                 Messages:       test case #0 test version "1.20" version error check

FAIL
```

The reason is that `TestCheckVersionCompatibility` injected error into fake_docker_client and then expected to see the error from `fake_docker_client.Version()` right after that (See [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager_test.go#L1890-L1892)). However, the error was consumed by the goroutine which periodically updates the version cache (See [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L262)).

The docker daemon version is rarely updated, and we only need version once for each container creating, during which we also do container create, start, inspect  #etc.
1) Do we care about the cost of the `Version` call so much that we have to introduce the complexity?
2) Kubelet periodically calls `runtime.Status()`, can we rely on that to update the cache? 

Anyhow, at least, we should disable the cache or have a fake one in the unit test. :)

@yujuhong @vishh @resouer 
/cc @kubernetes/sig-node

**Comment by resouer** [comment]
Oh no, did not see this data race in my local. 

I once considered move this cache to runtime level, while thus may need to change runtime interface. 
What if only cache apiversion?

**Comment by Random-Liu** [comment]
@resouer We can only get `apiversion` via `client.Version`, so there will still be the data race. :)

One option is to update the version in `Status()`, now kubelet periodically call `Status()` to check the runtime status.

**Comment by resouer** [comment]
@Random-Liu OK, well look into this tonight

**Comment by yujuhong** [comment]
The unit test itself should not start a goroutine to update the cache (unless you're actually testing the goroutine). We should disable it anyway, as we often do in our unit tests.

It also sounds like we don't need a goroutine dedicated for this. If we can tolerate the additional overhead from time to time, we can set a expiration time (e.g., 1 minute), and only call the runtime if the entry expires.
```
kubelet_docker_operations_latency_microseconds{operation_type="version",quantile="0.5"} 629
kubelet_docker_operations_latency_microseconds{operation_type="version",quantile="0.9"} 758
kubelet_docker_operations_latency_microseconds{operation_type="version",quantile="0.99"} 865
```

**Comment by Random-Liu** [comment]
@yujuhong Totally agree. :)
Maybe a new `Version()` call wraps the update logic in `DockerManager` layer, or wrapping the logic in the `kube_docker_client`.

**Comment by resouer** [comment]
expiration time sounds good in this case

**Comment by wojtek-t** [comment]
This is happening quite frequently - increasing priority to P0.
