### ISSUE TITLE
Kubelet e2e test flakes against coreos

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#24297]
Looks like it maybe the ssh connect is getting killed

**Comment by pwittrock** [comment]
#23667

**Comment by pwittrock** [comment]
[link](https://00e9e64bac5229ea6cdcb588d68d536a4836d718a73039969c-apidata.googleusercontent.com/download/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F23667%2Fnode-pull-build-e2e-test%2F1428%2Fbuild-log.txt?qk=AD5uMEteibGz2qM2P7iC7cJ9mQ5HQjxTTK5iyVxjd4ZO9HOO5JMVwPhNfwx3UZ7woxBh6NDg7K5cJl9Em9O5-ckh_wHwIyVbu-V0R7YeCMOLAlHGLTIJNjce5e50S9ZoCkLZoWOnOrxIuot19GfVeaPedJYxGgvsKa0S1g18WlhG0CpgukShw4Mla6t7O86d4eafF1WEqT9k4Lf8JWPoft6vNqzZ01af3_CxKYqlLmGEt1zeba5DzInHSPI-p1tDAG_4a7nrgayXnLOaMR7zDbWq8soEYgZ88WtVz8F0I484mbbjp5mXmXkgS52wrM0-3bSaAwnZ3wXjRBPh48ghxditLTQ65fg89JEetxhCfI68Mo62zsTLBzDB_u-wgp_lm8NUJ7HGIVMyDXxndb6wt9UkkEpnnTt5q976S0XpNyggWMaU916syJDe0u_n82BVRjUemMBqH2MvEeWDK1sot8EJuwS71ewU4g21ygs7glds3oS2tAEJeHP3j9-7SsdfYyRlixRyWaf0B7XlnIqkibX_x7Ontu0kY6HcgX02ufh2zeI9okNd83tGe4VWNLpeI0OocdzeBxpNpWDXCkpKg7l7VBAscGcIME54SdxKQ_R0MShWk0olr_XkzB2Gk_eGpjYHyy_BTwYaY036fxqy6-ZFNLDfjQ0ymX99-bx28HGclLv9Sf3U-twhGtFIhsh5lrvpsyDlrSExlvS33UWP1PG57VkCMknCtx49ygzyzlStiaMKXZ370LczeWR541QNGp28xmK9yUfLtc5CeiariDwDhXGznHEmj-jVEvpivcXfsKMjMvHKuj8kWmd9M5qTYzqhXCcxRYdAh2RAGO9USk0SONsT11Aj_Q)

**Comment by yujuhong** [comment]
The relevant log snippet:
```
E0413 13:18:44.382200    4904 e2e_remote.go:132] Failed to cleanup tmp directory /tmp/gcloud-e2e-169525228 on host Command [ssh -i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no tmp-node-e2e-433d8995-e2e-node-coreos-stable20160218-image -- rm -rf /tmp/gcloud-e2e-169525228] failed with error: exit status 255 and output:
ssh_exchange_identification: Connection closed by remote host
.  Output:
ssh_exchange_identification: Connection closed by remote host
================================================================
Failure Finished Host tmp-node-e2e-433d8995-e2e-node-coreos-stable20160218-image Test Suite
```

**Comment by mml** [comment]
And another one, not just coreos.  https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/23689/node-pull-build-e2e-test/1691/build-log.txt
