### ISSUE TITLE
Better one stop update-all script 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#24312]
Todays update-all script has a few cryptic, frustrating failure modes. 
A `update-all --group foo --resource bar --clobber --fail-fast` script would be helpful. 

Here are a few things I ran into, lots of moving parts when adding a new apigroup so some of this might be user error:
1. Need to update a couple of imports in cmd/libs, failing to do so will just silently not give you the right autogen files (deep_copy_generated i think)
2. ~~Need to add  a podSpec conversion function for things that use PodSpec.~~ (this is fixed)
3. I had to update internal_clientset with an import (which is really confusing, because the path to that file has "generated" in it. Or maybe this was something that should actually be autogenerated but I ended up doing it by hand) will lead to update-swagger failing with `panic: KUBE_API_VERSIONS contains versions that are not installed: ["apps/v1alpha1"].`
4. update-swagger should also surface errors better, I needed to invoke the same apiserver command it runs by hand to see the panic. 
5. Not `touching` types.generated.go will not fail hard enough, you just won't get a types.generated.go
6. Api-docs gets confused: https://github.com/kubernetes/kubernetes/issues/24310
7. ~~I need to add my group to update-generated-conversions~~ (this is fixed)
8. There's a dependency problem when custom conversion functions are used, generated-swagger-docs will fail because the apiserver won't come up, which will not work till one runs update-codegen (the last step of update-all).
9. I just delete all auto generated files when I change a type. 

@lavalamp

**Comment by bprashanth** [comment]
The apigroup in question https://github.com/kubernetes/kubernetes/pull/24315

**Comment by soltysh** [comment]
Big fat :+1: on no. 8 I've stumbled upon just now wasting some time to find out the codegen wasn't run. I'd suggest tweaking the script order in such a way that one doesn't have to think about stuff like that.

**Comment by kargakis** [comment]
A update-all-no-failures-please-dont-make-me-think.sh script would be ideal.

**Comment by smarterclayton** [comment]
Update all is pretty good now.
