### ISSUE TITLE
Implement /evict subresource for pod

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#24321]
Apparently we never filed an issue for this.

Client sends a DELETE for the pod's /evict subresource. This would delete the pod (if it is allowed by the DisruptionBudget; see #22774 for a discussion of how the DisruptionBudget part would work). Subresources are "virtual" resources (other examples: /binding and /scale) 

Additional discussion and context in #22217.

cc/ @mml @bgrant0607 @jiangyaoguo

**Comment by roberthbailey** [comment]
@davidopp what's the status of this issue?

**Comment by davidopp** [comment]
@mml took this over. Reassigning to him.

**Comment by davidopp** [comment]
(Oh, and moving to next-candidate.)

**Comment by ConnorDoyle** [comment]
What's the current status of this feature? Is help needed to get this one over the finish line for 1.4?

**Comment by pwittrock** [comment]
@mml @davidopp Moving this out of v1.4.  Please take a look and update if it needs to be in 1.4

**Comment by davidopp** [comment]
This will be in 1.4. just needs docs and a couple more e2e tests.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @davidopp @mml

**Comment by dims** [comment]
@davidopp @mml all issues must be labeled either release blocker or non release blocking by end of day 18 November 2016 PST. (or please move it to 1.6) cc @kubernetes/goog-control-plane

**Comment by davidopp** [comment]
This was implemented in #31033, closing.
