### ISSUE TITLE
e2e flake: Preparation for creating a cluster are ridiculously long (45+ minutes)

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#24325]
In this example:
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-kubemark-5-gce/1469/consoleFull

It took 45 minutes before we even started creating a cluster. Few log lines:

    00:17:08 Started by timer
    00:17:08 Started by timer
    00:17:08 Started by timer
    00:17:08 Started by timer
    00:17:08 Started by upstream project "kubernetes-build" build number 9424
    ...
    00:17:12 + gsutil -mq cp gs://kubernetes-release/ci/v1.3.0-alpha.2.181+8f3c623287e2f4/kubernetes.tar.gz gs://kubernetes-release/ci/v1.3.0-alpha.2.181+8f3c623287e2f4/kubernetes-test.tar.gz .
    00:21:16 + unpack_binaries
    00:21:16 + md5sum kubernetes.tar.gz kubernetes-test.tar.gz
    00:21:21 b3f9851f4bf241f0d87fb4b094c89ef1  kubernetes.tar.gz
    00:21:24 f49f8a8da9579df2a9a29177651d394d  kubernetes-test.tar.gz
    00:21:24 + tar -xzf kubernetes.tar.gz
    00:39:19 + tar -xzf kubernetes-test.tar.gz
    01:03:57 ++ cut -c 2-
    01:03:57 ++ echo v1.3.0-alpha.2.181+8f3c623287e2f4
    ...

After 45 minutes we didn't even call kube-up yet. This is some disaster.
We need to fix it, or we will be blocking merge-bot frequently because of timeouts.

@kubernetes/goog-testing @fejta @spxtr @ixdy

**Comment by wojtek-t** [comment]
I guess it may be related to overloading of Jenkins - if so we need to really prioritize it.

**Comment by fejta** [comment]
Assigning over to infra oncall. 

Actually I suspect the most likely problem is that we're exceeding our IOPs, network and/or some other throttle. I'm going to see if there is a way we can figure this out.

**Comment by spxtr** [comment]
It is due to overloaded Jenkins. Sometimes when we're busy untarring kubernetes takes over ten minutes.

We're working on turning up more Jenkins machines and spreading the load.

**Comment by spxtr** [comment]
We were exceeding disk write IOPs, which is why untarring took so long. Now that we've switched to using multiple Jenkins machines, untarring takes just a few seconds.

Let me know if you think the problem isn't fixed.
