### ISSUE TITLE
Load test failed in large cluster

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#24320]
I've found the following failure of load test:

scaling rc load-test-small-rc-821 for the first time
  Expected error:
      <*errors.errorString | 0xc83e461430>: {
          s: "error while scaling RC load-test-small-rc-821 to 2 replicas: the server has received too many requests and has asked us to try again later (get replicationControllers load-test-small-rc-821)",
      }
      error while scaling RC load-test-small-rc-821 to 2 replicas: the server has received too many requests and has asked us to try again later (get replicationControllers load-test-small-rc-821)
  not to have occurred

This is clearly a test issue - we should fix it

http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-kubemark-gce-scale/1020/consoleText

@gmarek

**Comment by wojtek-t** [comment]
Hmm - it seems that we already have auto-retry incorporate into client:
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/request.go#L813

This means that:
- either it doesn't work
- or we got the "429" response 10 times in the row.

@lavalamp - any thoughts?

**Comment by gmarek** [comment]
Do we have an exact 429 response? I.e. do we know how long did API server asked client to wait?

**Comment by wojtek-t** [comment]
To be honest, I also don't see any corresponding log in apiserver log file (i.e. there aren't any 429 logs there). And there aren't any "rc-821" error logs in apiserver around the time when it happened.

**Comment by lavalamp** [comment]
We should write an integration test to verify that 429 behavior works as expected if there's any question about this.

**Comment by wojtek-t** [comment]
I faced this again here:

http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-kubemark-gce-scale/1163/

I will take a look into it (but probably next week after freeze).

**Comment by wojtek-t** [comment]
This one was fixed by https://github.com/kubernetes/kubernetes/pull/26874
