### ISSUE TITLE
How to use the cluster addons?

### ISSUE THREAD

**Issue by anzhsoft** [kubernetes/kubernetes#24326]
I cannot find any useful info in the homepage,  the right practice is to prepare the yaml files under /etc/kubernetes/addons?
[kubernetes]# ls /etc/kubernetes/addons/
grafana-service.yaml  heapster-controller.yaml  heapster-service.yaml  influxdb-grafana-controller.yaml  influxdb-service.yaml

However, i prepared these files, and cannot find the expected things happen. 

any reply will be very appreciated.

**Comment by iamthemuffinman** [comment]
Yeah, the correct way to do it is to put them under ```/etc/kubernetes/addons```. Although, it's hard to debug without any more information. Have you checked logs using ```kubectl```? Or checked the logs under ```/var/log/containers```?

**Comment by zhouhaibing089** [comment]
@anzhsoft is the service `kube-addmons` running.

**Comment by anzhsoft** [comment]
i didn't create or start the service  kube-addons, and it didn't run too. How should I do to run it ? thank you.

**Comment by zhouhaibing089** [comment]
@anzhsoft see here: https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt/kube-addons

basically, the kube-addons service will take care of the foler `/etc/kubernetes/addons`, and use `kubectl` to create them.

**Comment by anzhsoft** [comment]
thank you Haibing. I tried as your comments, but now I failed to start the "heapster pod, the logs listed below:
I0418 20:02:47.925293   24534 manager.go:1679] Found pod infra container for "heapster-v1.1.0.beta1-3608176707-edbv4_kube-system(9efc4773-054b-11e6-9624-6c92bf139d06)"
I0418 20:02:47.925327   24534 manager.go:1692] Pod infra container looks good, keep it "heapster-v1.1.0.beta1-3608176707-edbv4_kube-system(9efc4773-054b-11e6-9624-6c92bf139d06)"
I0418 20:02:47.925404   24534 manager.go:1708] Container {Name:heapster Image:registry.baidu.com/zhanganzhan/heapster:v1.1.0-beta1 Command:[/heapster --source=kubernetes.summary_api:'' --sink=influxdb:http://monitoring-influxdb:8086 --metric_resolution=60s] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[cpu:{Amount:0.100 Format:DecimalSI} memory:{Amount:209715200.000 Format:BinarySI}] Requests:map[cpu:{Amount:0.100 Format:DecimalSI} memory:{Amount:209715200.000 Format:BinarySI}]} VolumeMounts:[] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
I0418 20:02:47.925461   24534 manager.go:1708] Container {Name:eventer Image:registry.baidu.com/zhanganzhan/heapster:v1.1.0-beta1 Command:[/eventer --source=kubernetes:'' --sink=influxdb:http://monitoring-influxdb:8086] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[memory:{Amount:209715200.000 Format:BinarySI} cpu:{Amount:0.100 Format:DecimalSI}] Requests:map[cpu:{Amount:0.100 Format:DecimalSI} memory:{Amount:209715200.000 Format:BinarySI}]} VolumeMounts:[] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
I0418 20:02:47.925558   24534 manager.go:1708] Container {Name:heapster-nanny Image:registry.baidu.com/zhanganzhan/addon-resizer:1.0 Command:[/pod_nanny --cpu=100m --extra-cpu=0m --memory=200Mi --extra-memory={{ 4 }}Mi --threshold=5 --deployment=heapster-v1.1.0.beta1 --container=heapster --poll-period=300000] Args:[] WorkingDir: Ports:[] Env:[{Name:MY_POD_NAME Value: ValueFrom:0xc2089d82e0} {Name:MY_POD_NAMESPACE Value: ValueFrom:0xc2089d8320}] Resources:{Limits:map[memory:{Amount:104857600.000 Format:BinarySI} cpu:{Amount:0.050 Format:DecimalSI}] Requests:map[cpu:{Amount:0.050 Format:DecimalSI} memory:{Amount:104857600.000 Format:BinarySI}]} VolumeMounts:[] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
I0418 20:02:47.925640   24534 manager.go:1708] Container {Name:eventer-nanny Image:registry.baidu.com/zhanganzhan/addon-resizer:1.0 Command:[/pod_nanny --cpu=100m --extra-cpu=0m --memory=200Mi --extra-memory={{ 500 }}Ki --threshold=5 --deployment=heapster-v1.1.0.beta1 --container=eventer --poll-period=300000] Args:[] WorkingDir: Ports:[] Env:[{Name:MY_POD_NAME Value: ValueFrom:0xc2089d8560} {Name:MY_POD_NAMESPACE Value: ValueFrom:0xc2089d85a0}] Resources:{Limits:map[cpu:{Amount:0.050 Format:DecimalSI} memory:{Amount:104857600.000 Format:BinarySI}] Requests:map[cpu:{Amount:0.050 Format:DecimalSI} memory:{Amount:104857600.000 Format:BinarySI}]} VolumeMounts:[] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.

when i created the /etc/kubernetes/addons/heapster-controller.yaml, the following definations seems wrong:

{% set metrics_memory = "200Mi" -%}
{% set eventer_memory = "200Mi" -%}
{% set metrics_memory_per_node = 4 -%}
{% set eventer_memory_per_node = 500 -%}
{% set num_nodes = pillar.get('num_nodes', -1) -%}
{% if num_nodes >= 0 -%}
  {% set metrics_memory = (200 + num_nodes * metrics_memory_per_node)|string + "Mi" -%}
  {% set eventer_memory = (200 * 1024 + num_nodes * eventer_memory_per_node)|string + "Ki" -%}
{% endif -%}

So I just hard code them and succeeded in creating it, but failed to start it. very appreciated for your help.

**Comment by anzhsoft** [comment]
kc get deployment --all-namespaces=true
NAMESPACE     NAME                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   heapster-v1.1.0.beta1   1         1         1            0           2h

the other services appears to work ok.

**Comment by anzhsoft** [comment]
more info:
kc get pods --all-namespaces=true -o wide
NAMESPACE     NAME                                     READY     STATUS             RESTARTS   AGE       NODE
kube-system   heapster-v1.1.0.beta1-3608176707-edbv4   0/4       CrashLoopBackOff   132        2h        test.kube-cluster.host1

the yaml:
cat heapster-controller.yaml
#{% set 200Mi = 200Mi -%}
#{% set 200Mi = 200Mi -%}
#{% set 4 = 4 -%}
#{% set 500 = 500 -%}
#{% set num_nodes = pillar.get('num_nodes', -1) -%}
#{% if num_nodes >= 0 -%}
#  {% set 200Mi = (200 + num_nodes * 4)|string + "Mi" -%}
#  {% set 200Mi = (200 * 1024 + num_nodes * 500)|string + "Ki" -%}
#{% endif -%}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-v1.1.0.beta1
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.1.0.beta1
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
      version: v1.1.0.beta1
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.1.0.beta1
    spec:
      containers:
        - image: registry.baidu.com/zhanganzhan/heapster:v1.1.0-beta1
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          command:
            - /heapster
            - --source=kubernetes.summary_api:''
            - --sink=influxdb:http://monitoring-influxdb:8086
            - --metric_resolution=60s
        - image: registry.baidu.com/zhanganzhan/heapster:v1.1.0-beta1
          name: eventer
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          command:
            - /eventer
            - --source=kubernetes:''
            - --sink=influxdb:http://monitoring-influxdb:8086
        - image: registry.baidu.com/zhanganzhan/addon-resizer:1.0
          name: heapster-nanny
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=100m
            - --extra-cpu=0m
            - --memory=200Mi
            - --extra-memory={{ 4 }}Mi
            - --threshold=5
            - --deployment=heapster-v1.1.0.beta1
            - --container=heapster
            - --poll-period=300000
        - image: registry.baidu.com/zhanganzhan/addon-resizer:1.0
          name: eventer-nanny
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=100m
            - --extra-cpu=0m
            - --memory=200Mi
            - --extra-memory={{ 500 }}Ki
            - --threshold=5
            - --deployment=heapster-v1.1.0.beta1
            - --container=eventer
            - --poll-period=300000


 cat /etc/kubernetes/addons/heapster-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: heapster
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Heapster"
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    k8s-app: heapster

**Comment by anzhsoft** [comment]
@zhouhaibing089

**Comment by zhouhaibing089** [comment]
@anzhsoft maybe you would get more luck there: https://github.com/kubernetes/heapster. if you could use code block to format your logs and specs, it would help a lot.
