### ISSUE TITLE
kube-proxy iptables: service will fail with fixed probability if one of endpoints unreachable

### ISSUE THREAD

**Issue by njuicsgz** [kubernetes/kubernetes#24322]
I am not sure this is a design issue or not, but it puzzled me a lot.

I found my service fails with fixed probability if one of endpoints unreachable when use kube-proxy with iptables mode. 

It is a critical problem that client's real requests will be refused when
1) my service is down while container is running ok, before next readiness time interval come if I have readiness probe
2) I am doing a rolling update

The user space mode does not have this problem since kube-proxy will make a real connection to endpoint before proxy the flow.

Since AWS ELB could retry the next endpoint if one endpoint is unreachable, so should I hide my service behind of a ELB to avoid this issue? Bug how to do when I am in a baremetal env, create a nginx for each service?
1. Environment:
   root@ip-172-20-0-9:~# kubectl version
   Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
   Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
2. How to reproduce:
   2.1 create rc with 2 pods of nginx:
   root@xx# cat nginx.rc.json 
   {
   "apiVersion": "v1", 
   "kind": "ReplicationController", 
   "metadata": {
       "name": "nginx", 
       "namespace": "default"
   }, 
   "spec": {
       "replicas": 2, 
       "selector": {
           "name": "nginx", 
           "version": "latest"
       }, 
       "template": {
           "metadata": {
               "labels": {
                   "name": "nginx", 
                   "version": "latest"
               }, 
               "namespace": "default"
           }, 
           "spec": {
               "containers": [
                   {
                       "image": "nginx", 
                       "name": "nginx",
                       "command": [
                           "/bin/bash",
                           "-c",
                           "service nginx start && sleep 3600"
                       ],
                       "ports": [], 
                       "resources": {
                           "limits": {
                               "memory": "128Mi"
                           }
                       }
                   }
               ]
           }
       }
   }
   }

root@ip-172-20-0-9:~# kubectl get po
NAME          READY     STATUS    RESTARTS   AGE
nginx-rbrob   1/1       Running   0          18m
nginx-ucp14   1/1       Running   0          18m

2.2 run a service
root@ip-172-20-0-9:~# kubectl describe service nginx
Name:                   nginx
Namespace:              default
Labels:                 <none>
Selector:               name=nginx
Type:                   ClusterIP
IP:                     10.0.253.87
Port:                   <unset> 40080/TCP
Endpoints:              10.244.1.4:80,10.244.1.5:80
Session Affinity:       None
No events.

2.3 disable one endpoint by close nginx service
root@ip-172-20-0-67:/home/ubuntu# docker exec -it 940c8b5b02b3 service nginx stop
root@ip-172-20-0-67:/home/ubuntu# docker exec -it 940c8b5b02b3 service nginx status
nginx is not running ... failed!

2.4 Curl the nginx by service IP, it fails in half chance.
root@ip-172-20-0-67:/home/ubuntu# curl -s -o /dev/null -w "%{http_code}" 10.0.253.87:40080
200
root@ip-172-20-0-67:/home/ubuntu# curl -s -o /dev/null -w "%{http_code}" 10.0.253.87:40080
000
root@ip-172-20-0-67:/home/ubuntu# curl -s -o /dev/null -w "%{http_code}" 10.0.253.87:40080
000
root@ip-172-20-0-67:/home/ubuntu# curl -s -o /dev/null -w "%{http_code}" 10.0.253.87:40080
200

2.5 Curl ELB will return 200 always
root@ip-172-20-0-9:~# kubectl describe service nginx
Name:                   nginx
Namespace:              default
Labels:                 <none>
Selector:               name=nginx
Type:                   LoadBalancer
IP:                     10.0.145.10
LoadBalancer Ingress:   a99110e7402db11e6978d0663f446fd2-1127146940.us-east-1.elb.amazonaws.com
Port:                   <unset> 40080/TCP
NodePort:               <unset> 32616/TCP
Endpoints:              10.244.1.4:80,10.244.1.5:80
Session Affinity:       None
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason                  Message

---

  18m           18m             1       {service-controller }                   Normal          CreatingLoadBalancer    Creating load balancer
  18m           18m             1       {service-controller }                   Normal          CreatedLoadBalancer     Created load balancer

$ for((i=1;i<=1000;i++));do curl -s -o /dev/null -w "%{http_code}" a99110e7402db11e6978d0663f446fd2-1126940.us-east-1.elb.amazonaws.com:40080 && sleep 0.1; done
200

**Comment by boynux** [comment]
Would you please let us know how is your Kubernetes cluster setup?

**Comment by njuicsgz** [comment]
@boynux
I installed k8s on AWS by official auto script, however, I think there is no difference with the env setup manually on AWS.

**Comment by thockin** [comment]
This is a limitation of the VIP implementation in iptables.  There isn't a
userspace hook - the tradeoff is performance and transparency.  The idea is
that your readiness probes are fast enough to handle failures.  The only
other answer I see is a "real" proxy, which is significantly more expensive.

**Comment by njuicsgz** [comment]
@thockin I don't think it is even a tradeoff, because I can not accept the loss of real user requests in a prod env.

What about run a nginx as DaemonSet to proxy node port to real endpoints? So the request could be retried with another endpoint when one fails.

**Comment by thockin** [comment]
That is a valid workaround for now. Or you can use Ingress to set up an L7
balancer directly

**Comment by smarterclayton** [comment]
Both IPVS (https://github.com/kubernetes/kubernetes/issues/17470) and some form of conntrack based observation have the potential to identify connections that are denied / ignored by the remote endpoint.

**Comment by danwinship** [comment]
Someone assigned this to me, I guess because I filed a doc bug (https://github.com/kubernetes/kubernetes.github.io/issues/401) related to it. Anyway, I am not working on this other than getting the docs updated to explain the current behavior, and that is now merged, so you should probably un-assign me (which, crazily, I apparently cannot do myself).
