### ISSUE TITLE
[k8sm] Can not delete auto generated ReplicaSet

### ISSUE THREAD

**Issue by k82** [kubernetes/kubernetes#24332]
## Version:

Kubernetes: master (1.3)
Mesos: master (mesos 0.29.0)

## Steps

1. Create ReplicaSet & Pods:
```
kubectl run mynginx --image=nginx --replicas=2
```
2. Delete ReplicaSet

```
kc delete ReplicaSet/mynginx-121855510
replicaset "mynginx-121855510" deleted
```

3. Check the Pod, the ReplicaSet is still here

```
$ kc get po
NAME                        READY     STATUS              RESTARTS   AGE
mynginx-121855510-2sawo     0/1       RunContainerError   0          1h
mynginx-121855510-37ocb     0/1       RunContainerError   0          1h
```

**Comment by bgrant0607** [comment]
@k82 Please observe the message printed by kubectl. Delete the deployment, not the replicaset.

https://groups.google.com/forum/#!topic/kubernetes-announce/mOFVst-iNZY

**Comment by k82** [comment]
Got that, thanks very much :).
