### ISSUE TITLE
Support cockroach db in PetSet

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#24334]
https://github.com/cockroachdb/cockroach/issues/5967#issuecomment-210048164

**Comment by josephjacks** [comment]
@bprashanth should we close this issue given https://github.com/cockroachdb/cockroach/issues/5967#issuecomment-254838400 ?

**Comment by a-robinson** [comment]
Yeah, this can be closed. We have

* An example - https://github.com/kubernetes/kubernetes/tree/master/examples/cockroachdb
* Docs - https://www.cockroachlabs.com/docs/orchestrate-cockroachdb-with-kubernetes.html
* A helm chart - https://github.com/kubernetes/charts/tree/master/incubator/cockroachdb
