### ISSUE TITLE
Kubelet test flaky failure - expected only one container in the pod \"bin-false\"

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#24341]
[build logs](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24197/node-pull-build-e2e-test/1700)

>
04:51:35 • Failure [60.001 seconds]
04:51:35 Kubelet Container Manager
04:51:35 /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/container_manager_test.go:92
04:51:35   oom score adjusting
04:51:35   /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/container_manager_test.go:90
04:51:35     when scheduling a busybox command that always fails in a pod
04:51:35     /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/container_manager_test.go:89
04:51:35       it should have an error terminated reason [It]
04:51:35       /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/container_manager_test.go:83
04:51:35 
04:51:35       Timed out after 60.000s.
04:51:35       Expected
04:51:35           <*errors.errorString | 0xc82032a370>: {
04:51:35               s: "expected only one container in the pod \"bin-false\"",
04:51:35           }
04:51:35       to be nil
04:51:35 
04:51:35       /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/container_manager_test.go:82

**Comment by Random-Liu** [comment]
I think this one is added by @vishh  :)

**Comment by vishh** [comment]
The test is running a single container pod and it is complaining about seeing multiple containers in the pod status. I cannot fix the test today though. I can look at it on monday if no one else gets to it by then.

**Comment by liangchenye** [comment]
I also saw this issue in my developing. In my case, it turned out that there is no container. (len() == 0)
I think we need to wait for a moment after a pod has been created, or there will not be enough time for the related container to be created.

**Comment by goltermann** [comment]
@vishh what's the latest here?  still valid?

**Comment by vishh** [comment]
Closing this issue for now. We can re-open it if the test fails again.
