### ISSUE TITLE
Integration test flake k8s.io/kubernetes/pkg/kubelet/dockertools

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#24355]
Not a whole log in the logs other than that the dockertools test failed

>
FAIL	k8s.io/kubernetes/pkg/kubelet/dockertools	1.039s

[link to logs](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24339/kubernetes-pull-test-unit-integration/21487/)

**Comment by yujuhong** [comment]
This is a dup of #24298
