### ISSUE TITLE
Resource quota should ignore pod resource requirement updates

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#24352]
https://github.com/kubernetes/kubernetes/blob/master/pkg/quota/evaluator/core/pods.go#L50

The scenario that presented a problem was the following:

a) create pods in a namespace that do not make a memory claim
b) add a quota that tracks memory
c) update one of the pods previously created by reducing its active deadline.

Expected result:
Since a pod cannot change its resources via update, we should have been allowed to update the pod spec.

Actual Result:
error since the pod did not make a memory claim, quota rejects the pod.

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra
