### ISSUE TITLE
Kubemark runs fails

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24368]
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-kubemark-5-gce/1508/consoleFull

```
16:36:46 docker build -t gcr.io/k8s-jenkins-kubemark/kubemark .
16:36:46 make: docker: Command not found
```

**Comment by fejta** [comment]
slaves issue?

**Comment by gmarek** [comment]
Seems that @spxtr fixed it - big thanks for solving this this late on Friday!

**Comment by spxtr** [comment]
We can't run the kubemark tests in the container in the same way we're trying to do the others. For now it'll have to live on the jenkins master, outside of a container :(

**Comment by spxtr** [comment]
Should be fixed. I left the kubemark tests running on the Jenkins master as they were before.
