### ISSUE TITLE
Reserve DNS Cluster IP

### ISSUE THREAD

**Issue by k82** [kubernetes/kubernetes#24363]
##  Version

Kubernetes: master (1.3)
Mesos: master (0.29.0)

## Phenomenon

The `kubernetes` used DNS Cluster IP, the DNS service maybe failed.

## Steps

```
root@ma1demo1:~# kubectl get service
NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
k8sm-scheduler   10.1.1.243   <none>        10251/TCP   9h
kubernetes       10.1.1.1     <none>        443/TCP     9h
root@ma1demo1:~# vim README.md ^C
root@ma1demo1:~# ps -ef | grep api
root     17363     1  0 10:20 ?        00:03:51 km apiserver --address=9.21.58.21 --etcd-servers=http://9.21.58.21:4001 --service-cluster-ip-range=10.1.1.0/24 --port=8888 --cloud-provider=mesos --cloud-config=mesos-cloud.conf --secure-port=0 --v=1
root     17373     1  0 10:20 ?        00:00:43 km scheduler --address=9.21.58.21 --mesos-master=ma1demo1:5050 --etcd-servers=http://9.21.58.21:4001 --mesos-user=root --api-servers=9.21.58.21:8888 --cluster-dns=10.1.1.1 --cluster-domain=kube-demo --v=2
```

**Comment by k82** [comment]
cc @jdef

**Comment by jdef** [comment]
This isn't k8sm-specific - you've manually configured the DNS service IP to conflict with the service IP that the k8s master will always try to use. Yous should perhaps pick x.x.x.10 as the address for the DNS service (I believe that the salt scripts do this).

k8s master will always try to grab x.x.x.1 for itself: https://github.com/kubernetes/kubernetes/blob/master/pkg/genericapiserver/genericapiserver.go#L376

**Comment by thockin** [comment]
I'm going to close this for now.  Please reopen if you think there's a bug in code or docs.
