### ISSUE TITLE
Informer should not saturate workqueue with sync events

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#24375]
Initial discussion is in https://github.com/kubernetes/kubernetes/pull/24323

#### Problem:
When cluster is large and a periodic relist happens, a large number of RCs added by Sync event will block the work queue, thus RCs added by Added/Updated/Deleted event may have a long latency(those events are usually caused by users, they should be processed ASAP).
>
I have done a benchmark about replication_controller: if we have 1000 namespace, each have 10 RCs, each RC have 10 replicas(so, 100, 000 pod in total), when periodic list happens, replication_controller need 20s to process the RCs added into work queue by relist, which means if a user create a new RC just at that time, it will be processed after 20 seconds. Users are always captious and impatient.

https://github.com/kubernetes/kubernetes/issues/23394 propose to distinguish relist and resync, but that's not enough:

> IIUC, use replication_controller as example:
* Relist means "reflector send LIST request to etcd, replace local cache with items get form etcd, and put all deltas to a queue, then the controller framework pop deltas from the queue and put the RC need to process to work queue".
* Resync means "go through the items in the local cache, put all RCs(in local cache) to work queue".
>
Since both relist and resync will add ALL RCs(all RCs from etcd when relist, all RCs from local storage when resync) to work queue, when cluster is large, a large number of RCs will block work queue for a long time. If a unfortunate user create a new RC just at that time, he will get a bad user experience.

#### Proposal

If my understanding of relist/resync is correct, I propose to let [work queue](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L93) respect priority: RCs added by Added/Updated/Deleted event(usually caused by users operation) will have a higher priority when pop, so they could be processed ASAP. RCs added by periodic relist/resync will have a relatively lower priority.

This proposal and https://github.com/kubernetes/kubernetes/issues/23394 is not conflict, they are complementary actually.

**Comment by mqliang** [comment]
@bprashanth @lavalamp @wojtek-t @smarterclayton @kubernetes/sig-scalability

**Comment by bprashanth** [comment]
My immediate concern is that we end up sending out of order updates and the controllers need to compare resource versions etc. Maybe there's an easy solution that allows us to resync only those RCs that haven't synced in a while.

**Comment by smarterclayton** [comment]
Can we process relist more effectively inside the controller?  Whats the breakdown of that 20s - calling our to the pod cache?

**Comment by bprashanth** [comment]
We don't need to process 10,000 different RCs from the workqueue serially, you should be able to bump up https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L211 through https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L195

**Comment by mqliang** [comment]
@bprashanth 
> My immediate concern is that we end up sending out of order updates and the controllers need to compare resource versions etc

Also think about it. Since we actually insert the ***key*** of RC into workqueue(see [enqueue controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L379-L393) ), even we process RCs out of order, it still ensure correctness.

> We don't need to process 10,000 different RCs from the workqueue serially

yeah, setting the "--concurrentRCSyncs" flag as a larger value could make replica management more responsive. But I don't think it's a good enough idea:

* It increase concurrency, thus more CPU (and network) load
* Don't forget that we have QPS in client side and "max-requests-inflight" limit in API server, and we have other controllers(job/daemonset/deployment, etc), increasing concurrency may not help a lot.

Letting work queue respect priority seems reasonable: 
* process urgent ones first. 
* it still ensure correctness even we process RCs out of order. 
* let controllers do the priority decision, for tasks must be FIFO, setting the priority as same value

**Comment by mqliang** [comment]
@smarterclayton 

> Can we process relist more effectively inside the controller? Whats the breakdown of that 20s - calling our to the pod cache?

Yeah, we can try process relist more effectively inside the controller, but even we have the [lookup cache](https://github.com/kubernetes/kubernetes/pull/19043), there is still a 20s breakdown when relist/resync if we have 10,000 RCs(at the same time, we may have some Jobs/DaemonSets/Deployments, etc, and we have QPS in client side and "max-requests-inflight" limit in API server). And we will eventually have a larger cluster, so I think maybe it's time now to let work queue respect priority, so that urgent RCs/RSs/Jobs/ could be more responsive.

**Comment by bprashanth** [comment]
I was ratholed by your pr that made modifications in the informer, yeah adding a new type of queue that respects priority and only using it in the RC should be safe. 

Obviously it's not safe to reorder things if we weren't enqueuing a simple string that is the ns/name of the object, so if we do this I'd want to make it really clear to any users of the queue that they must not enqueue stateful objects (the queue accepts interface{}).

**Comment by smarterclayton** [comment]
Why not break relist up into tranches then?  Priority doesn't seem to
be the real issue, just saturation.  I don't think at 100k RC we want
to be running them all naively anyway, and a work queue that is order
independent can be sliced and diced in lots of ways.  If we're trying
to avoid saturation then relist is already broken.

**Comment by lavalamp** [comment]
Like Clayton, I *really* don't want to add a priority concept. Add more workers, or split resyncs into smaller batches.

**Comment by timothysc** [comment]
In our experiments the re-list was unnecessary in *most* cases except restart, and watch failure.  @rrati is working on a patch to clean up and separate.

**Comment by wojtek-t** [comment]
Agree with the above posts. I don't think priority concept is necessary - we can workaround it in other ways (e.g. what @smarterclayton described above).

And note that we will be removing periodic relists - it should happen soon and will help a lot with that too.

**Comment by erictune** [comment]
@bprashanth can you prioritize?

**Comment by bprashanth** [comment]
I think everyone sort of agrees that we shouldn't add priorities to the work queue. The 2 work arounds are:
1. Add more workers
2. Batching relists

1 is possible today, making this issue about 2.

@wojtek-t the controller will still continue to sync (not relist from apiserver but from store) so this is still a problem, even after we remove apiserver relists right?

**Comment by wojtek-t** [comment]
@bprashanth - yes it will still continue to sync from local cache  [but relists from apiserver can be very expensive (in terms of network traffic and cpu-consumption because of deserialization) and we will avoid that].

**Comment by timothysc** [comment]
and relist "should be" unnecessary.

**Comment by wojtek-t** [comment]
>
and relist "should be" unnecessary.

Agree (assuming that there weren't errors in the list/watch).

**Comment by mqliang** [comment]
Oh, sorry, I think I should be more specific:

I don't mean let the [Queue](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/framework/controller.go#L34) of Informer respect priority. Actually, the queue of Informer ***MUST*** be FIFO, since the informer framework is used by many clients outside the core kube repo and we should be careful not to violate the FIFO assumptions downstream users might have. 

Actually, I'd like the [work queue](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L103) of controller respect priority: for add/update/delete event, set a relatively higher priority when [enqueue](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L425), and sync events will have a relatively lower priority. So new created RC could bee processed ASAP. 

And, it's up to controller to decide the priority, if the controller want process definitely FIFO, just set priority for all events as same.

The priority mechanisms may be a little complicated, and I am fine with some better solutions about this issue.
