### ISSUE TITLE
Dead Links in Guestbook Example

### ISSUE THREAD

**Issue by zplizzi** [kubernetes/kubernetes#24373]
In the [README for the guestbook example](https://github.com/kubernetes/kubernetes/blob/release-1.2/examples/guestbook/README.md#step-one-start-up-the-redis-master), the line `Before continuing to the gory details, we also recommend you to read Quick walkthrough, Thorough walkthough and Concept guide.` appears to contain several dead links.

**Comment by bgrant0607** [comment]
cc @kubernetes/docs

**Comment by bgrant0607** [comment]
Result of the doc move.

**Comment by asalkeld** [comment]
Can we close this issue now?

**Comment by nikhita** [comment]
ping: we can close this now.

Links are fixed with this PR: https://github.com/kubernetes/kubernetes/pull/39064
