### ISSUE TITLE
controller manager not starting due to empty preferred version in third party resource

### ISSUE THREAD

**Issue by polvi** [kubernetes/kubernetes#24380]
https://github.com/kubernetes/kubernetes/issues/23799#issuecomment-206735608 shows that the third party resource controller is creating API groups with empty preferred versions: 

#23985 fixes this returning error when the dynamic client finds an empty group version: 

https://github.com/kubernetes/kubernetes/pull/23985/files#diff-eeb7b9143db6fd30f0968ba5024cc056R128

As far as I can tell, controller-manager uses the discovery client to start-up. Therefore if I have an existing third party resource, and restart the controller-manager, it will not start because the controller manager errors out:

```
F0416 10:20:44.775767   34280 controllermanager.go:278] Failed to get supported resources from server: groupVersion shouldn't be empty
```

To reproduce: 

1. start a master
2. register a new third party resource
3. restart kube-controller-manager

**Comment by bgrant0607** [comment]
cc @caesarxuchao @lavalamp

**Comment by caesarxuchao** [comment]
@polvi, thanks for reporting the problem. I think https://github.com/kubernetes/kubernetes/pull/24006 should fix this, could you update your API server?

**Comment by lavalamp** [comment]
I think #24006 should fix this-- please leave a note here if not and we'll reopen.
