### ISSUE TITLE
README.md media page link broken

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kubernetes#24383]
When I click [Media Page](http://kubernetes.io/media/) link in [Are you ready to add to the discussion?](https://github.com/kubernetes/kubernetes#are-you-ready-to-add-to-the-discussion) in `README.md` I am taken to non-existent http://kubernetes.io/media/

**Comment by surajssd** [comment]
This is how it looked before migration https://web.archive.org/web/20150923035335/http://kubernetes.io/media

**Comment by idvoretskyi** [comment]
@surajssd please, submit this issue here (kubernetes.io website repo) - https://github.com/kubernetes/kubernetes.github.io/issues

**Comment by bgrant0607** [comment]
cc @kubernetes/docs

**Comment by bgrant0607** [comment]
We should remove this link from the main repo.

**Comment by surajssd** [comment]
@idvoretskyi should I create a parallel issue closing this?

**Comment by surajssd** [comment]
@johndmulhausen ping

**Comment by nikhita** [comment]
The link has been removed from `README.md`. Media is gone as per: https://github.com/kubernetes/kubernetes.github.io/issues/17#issuecomment-189065253

This issue can be closed now.
