### ISSUE TITLE
ConvertToVersion to same version should not be using reflection conversion

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#24389]
Invoking ConvertToVersion when the object is already in the destination version should be a no-op.  Right now it's going into the default conversion path (and doing a bunch of useless work).

Also, ConvertToVersion needs to switch to take an array of desired versions so that we can convert nested runtime.Objects.  It's possible that we want to have the behavior that if you try to do:

     scheme.Convert(&api.List{Items: []runtime.Object{&internal.Pod{}, &internal.Autoscaler{}}}, "v1")

that we get back

    &v1.List{Items: runtime.Object{v1.Pod, v1beta1.Autoscaler}

by using registered.EnabledVersions() as our default list for anything that is not in the group sent to conversion.

**Comment by smarterclayton** [comment]
I'm tempted to advance the argument that Convert should *not* provide the guarantee that data won't be shared between the objects after conversion, or that we should split the use cases for conversion into "to get an external" and "for everything else".  While there is a safety issue with not doing full copy, the primary use case for conversion is underneath `pkg/runtime/serializer/versioning` (99% of all calls) to generate external versions.  We generate conversions specifically so that that code path is fast.  I'm also not 100% sure that we even provide the guarantee that the originating object is unchanged today in the reflection path (since we use IsAssignable and IsConvertible in some cases).  

If we remove the need to avoid copy (mutations to `in` are considered unsafe while the `out` object is live), there is a much larger space of optimizations in conversion that we can tackle (probably 50% of the allocations are avoidable).

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery general question about conversion design.

**Comment by lavalamp** [comment]
We have a mechanism for representing a full list of desired versions, it's a Codec. We should dump ConvertToVersion before adding a list like that, IMO.

This gets in to the huge hole in our conversion mechanism, where the embedded conversions don't have access to the parent codec.

**Comment by smarterclayton** [comment]
Codecs use ConvertToVersion?  Not sure what you mean "a list like that".

**Comment by smarterclayton** [comment]
This is fixed.
