### ISSUE TITLE
Idea: something like Linux kernel's 'make config' for cluster config

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#24397]
One of the issues we face right now is that the various addons and cluster components have flags and parameters.  It's not at all clear which params apply to all settings, and which just apply to some, or what all the valid options are.  It strikes me as awfully similar to Linux's kconfig.

Imagine if things like network integrations and addons just registered themselves by existing in specific dirs with specifically named files.  Some `make config` process would walk the dirs, joining the input files into a tree of options, and then would allow you to configure your cluster turnup.  Once finished, it would generate a `cluster.yaml` or something which would be used by kube-up (or its successors) to set up the cluster.  That yaml could even find itsway into a config map.  This would be somethign users could check in to version control or share with colleagues or for support tickets.

This would be INFINITELY better than the existing config-default junk we have.

Obviously this is an idea, and not fully formed.

@mikedanese

**Comment by danehans** [comment]
@thockin that sounds similar to how addons register themselves with the addon-mgr service. Here is how I envision the flow:

1. Node PXE boots.
2. One or more pieces of metadata (i.e labels) are provisioned to the node.
     a. The label can be delivered post-PXE using something like cloud-init, Ignition, etc..
3. The labels are based on built-in or user-defined attributes.
3. The node, with it's metadata label is added to a dynamic inventory.
4. A notification that a new node was added is delivered to the config-mgr service as you describe above.
5. The config-mgr service uses the label to select the appropriate config template (like label selctor)
6. An Ansible playbook (i.e. cluster.yml) is generated from the config-template
7. The Ansible playbook is run to configure the node.
