### ISSUE TITLE
Improve cluster autoscaling

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#24404]
Current hacky version has number of drawbacks:
- works only on GCE
- doesn't support number of cases and we may still have pending pods
- very cloud provider specific
- very hard to update configuration
- UX is very poor

We'd like to improve it to:
- support all cases for pending pods
- provide a reference implementation that could be ported to other cloud providers.

It should support both scaling up (P1) and scaling down (P2).

This an umbrella bug used for referencing PRs etc.

**Comment by fgrzadkowski** [comment]
@davidopp @roberthbailey @piosz @aronchick

**Comment by davidopp** [comment]
Can you list what work remains to be done before you can move this issue to 1.4 milestone?

**Comment by davidopp** [comment]
ping - can you list what work remains to be done before you can move this issue to 1.4 milestone?

**Comment by matchstick** [comment]
Please list what work needs to be done for next candidate.

**Comment by mwielgus** [comment]
* More efficient unneeded node analysis. The current code will work ok for small to medium clusters (50-150 nodes with 1k-3k pods) but will not work for 1k node/30k pods.
* Reduce latency in scale down. Right now we are super conservative when considering nodes for scale down - for 10 min we check whether is is possible to schedule all of their pods on other machines. Once we delete one node the checks for other machines are invalid (to some degree) and we start counting from the begin. This means that we can only remove 6 nodes per hour. We have to either consider deletion of multiple machines at once or relax our strategy.
* Clean ups in the code.
* Decide what to do with best effort pods.

**Comment by mwielgus** [comment]
Closing the issue. All Cluster Autoscaler issues should be tracked inside https://github.com/kubernetes/autoscaler.
Moreover, all of the improvements mentioned above were done.
