### ISSUE TITLE
Clarify `kubectl get service` output

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#24411]
Someone reported:
```
I then use kubectl get services and I don’t have an external IP address. 
NAME         CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
frontend     10.163.255.126                 80/TCP    24s
kubernetes   10.163.240.1     <none>        443/TCP   27m

I panic a little cause I thought I requested it. I look up a few things and in a lark rerun and kubectl get services get:
NAME         CLUSTER-IP       EXTERNAL-IP     PORT(S)   AGE
frontend     10.163.255.126   146.X.Y.Z   80/TCP    4m
kubernetes   10.163.240.1     <none>          443/TCP   32m

Okay. It might be nice if it had told me that it was requesting, instead of just being blank.
```

The empty output is caused by:
```
func getServiceExternalIP(svc *api.Service) string {
	switch svc.Spec.Type {
	case api.ServiceTypeClusterIP:
		if len(svc.Spec.ExternalIPs) > 0 {
			return strings.Join(svc.Spec.ExternalIPs, ",")
		}
		return "<none>"
	case api.ServiceTypeNodePort:
		if len(svc.Spec.ExternalIPs) > 0 {
			return strings.Join(svc.Spec.ExternalIPs, ",")
		}
		return "nodes"
	case api.ServiceTypeLoadBalancer:
		lbIps := loadBalancerStatusStringer(svc.Status.LoadBalancer)
		if len(svc.Spec.ExternalIPs) > 0 {
			result := append(strings.Split(lbIps, ","), svc.Spec.ExternalIPs...)
			return strings.Join(result, ",")
		}
		return lbIps
	}
	return "unknown"
}
```

Note the last case doesn't check for an empty list. 

We should settle on a term for values that are currently empty but we expect to be populated asynchronously. I don't like "requesting". Elsewhere we use "pending", such as for unscheduled pods, so let's go with that. 

And, let's ensure that all the non-literal values are bracketed consistently: `<pending>`, `<nodes>`, `<unknown>`.

We should update the kubectl conventions accordingly.

Similar recent PRs: #22279,  #22635

cc @AdoHe

**Comment by bgrant0607** [comment]
See also #22702

**Comment by janetkuo** [comment]
I believe the remaining task for this issue is to update kubectl conventions https://github.com/kubernetes/kubernetes/blob/master/docs/devel/kubectl-conventions.md? cc @k82

**Comment by AdoHe** [comment]
I think so. @k82 if you have bandwidth, please go ahead.

**Comment by k82** [comment]
@AdoHe & @janetkuo , I'll continue to work on it :).

**Comment by k82** [comment]
@AdoHe & @janetkuo , the document was updated accordingly :).

**Comment by AdoHe** [comment]
Thanks @k82

**Comment by dims** [comment]
Looks like the two PR(s) in this issue are merged already. Can we close this issue please?

**Comment by roberthbailey** [comment]
@bgrant0607 is this issue resolved?

**Comment by bgrant0607** [comment]
@k82 In the future, please put "fixes #issue" in the PR that should close the issue, and it will be closed automatically.

**Comment by k82** [comment]
#bgrant0607 , copy that. Thanks very much :).
