### ISSUE TITLE
When Kubemark tests fail JUnit_XX files are not filled correctly.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24415]
Even when some test fails contents are:
```
<testsuite tests="0" failures="0" time="15.245789696">
...
```

cc @kubernetes/sig-testing @wojtek-t

**Comment by spxtr** [comment]
Could you add some more info, such as an example run's GCS bucket?

**Comment by gmarek** [comment]
Pretty much any failure: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-kubemark-500-gce/2964/artifacts/?project=kubernetes-jenkins

**Comment by spxtr** [comment]
Ginkgo didn't actually run any tests on that run, so there aren't any test failures. For some reason that gets marked as a failure overall.

**Comment by gmarek** [comment]
If you look into test it failed. Maybe it's related to https://github.com/kubernetes/kubernetes/pull/21302

**Comment by spxtr** [comment]
Oh, for some reason ginkgo ran twice, and the second run skipped all tests and overwrote `junit_01.xml`.

```
Ran 2 of 277 Specs in 7302.088 seconds
FAIL! -- 1 Passed | 1 Failed | 0 Pending | 275 Skipped --- FAIL: TestE2E (7302.14s)
FAIL

Ginkgo ran 1 suite in 2h1m42.735208185s

...

Ran 0 of 277 Specs in 15.246 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 277 Skipped PASS

Ginkgo ran 1 suite in 16.238071694s
Test Suite Passed
```

**Comment by ixdy** [comment]
[This](https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e-runner.sh#L340-L345) is why ginkgo runs twice:
```shell
  # Similarly, if tests fail, we trigger empty set of tests that would trigger storing logs from the base cluster.
  ./test/kubemark/run-e2e-tests.sh --ginkgo.focus="${KUBEMARK_TESTS}" --gather-resource-usage="false" && kubemark_succeeded="$?" || kubemark_succeeded="$?"
  if [[ "${kubemark_succeeded}" != "0" ]]; then
    go run ./hack/e2e.go -v --test --test_args="--ginkgo.focus=DO\sNOT\sMATCH\sANYTHING"
    exit 1
  fi
```

**Comment by ixdy** [comment]
(We should just replace that with a call to `cluster/log-dump.sh`. I don't think it existed when this bit was originally written.)

**Comment by gmarek** [comment]
Yeah - I guess it was just a hack to get logs uploaded.

**Comment by gmarek** [comment]
@ixdy @spxtr can one of you fix this, as you know how it works exactly?
