### ISSUE TITLE
Newrelic should work on GCE/GKE

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#24418]
alanhartless [1:27 PM] 

> Anyone by chance know if the fact that `/sys/fs/cgroup/cpuacct/docker` doesn’t exist in a google container node is a Google, Debian, kubernetes, or docker issue? New Relics docker monitor apparently doesn’t work because `/sys/fs/cgroup/cpuacct/docker` and `/sys/fs/cgroup/memory/docker` doesn’t exist. https://discuss.newrelic.com/t/docker-metrics-not-report-correctly-for-google-container-engine/36127/3?u=alan.hartless

beeps [4:42 PM] 

> @alanhartless: your stats should just be in /cpuacct not under /docker
> i.e /sys/fs/cgroup/cpu/$(docker inspect --format {{.Id}} <container-id>)/cpu.shares
> I'm guessing this is because we reparent cgroups.

alanhartless [7:45 PM]

> @beeps thanks; apparently New Relic disagrees :simple_smile: I hope they fix it.

alanhartless [9:19 AM] 

> @beeps On the subject of New Relic’s docker monitoring feature (http://newrelic.com/docker), they replied with
> ```Google Container Engine's implementation of Docker isn't currently supported by the LSM. This is because of the difference in the path to the .stat files. I have heard of folks using custom cgroups in their docker run command to revert the GCE behavior to default, and get the LSM working, but I have yet to see it in action. This might be worth investigating.
> By chance know if that’s possible and if so, what implications are there for kubernetes?

@kubernetes/sig-node to comment on "Google Container Engine's implementation of Docker", maybe there's an easy workaround?

**Comment by vishh** [comment]
kubelet manages cgroups independently of docker daemon. I will not recommend relying on cgroups API for monitoring kubelet managed pods/containers.

**Comment by bprashanth** [comment]
I think tools like newrelic expose container stats and expect to find them at a location that differs from the one on our GCE nodes, because of the reparenting. So IMO we should either:     

1. Tell newrelic how to monitor pods instead
2. Tell people newrelic monitoring of containers just won't work
3. Provide some workaround so cpu.stats etc show up where the tools expect to find them

**Comment by bprashanth** [comment]
To me this is like saying ps and atop won't work because fedora decided to move /proc

**Comment by vishh** [comment]
> To me this is like saying ps and atop won't work because fedora decided to move /proc

I don't get this. Kubelet intends to keep cgroups as an implementation detail. Components in kubernetes ecosystem should rely on stable APIs and not implementation details.

I'm happy to work with the NewRelic folks on getting their agent working on a kube cluster. Can you include/mention someone from their team in this issue?

**Comment by bprashanth** [comment]
I can try and find out who'd be interested but it sounds like a stretch to expect everyone to reimplement to support kube, it's probably not just newrelic.

**Comment by alanhartless** [comment]
Here's the link to the New Relic forum conversation where the quote came. Should I cross link this issue there to see if they bite? https://discuss.newrelic.com/t/docker-metrics-not-report-correctly-for-google-container-engine/36127/7

**Comment by vishh** [comment]
Yeah. Cross-linking might help with making progress.

**Comment by paralin** [comment]
I'm going to update the NewRelic example, so I should probably pay attention to thi

#24484

**Comment by derekwaynecarr** [comment]
Agree with @vishh that no one should assume a particular location for a
container cgroup.  Especially if they plan to target multiple distributions.

**Comment by cwt** [comment]
Any update on this issue? I just upgrade GKE node to the latest version (1.2.3) and also install the latest new relic agent. Still can't monitor my docker instances.
