### ISSUE TITLE
docker-proxy processes may or may not have been charged to the docker-daemon cgroup on containerVM

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#24417]
Docker runs a userland proxy (`docker-proxy`) process for pods using host ports. E.g., one of the the add-on pods (`monitoring-influxdb-grafana`) uses host ports. 

```
root      1015  0.0  0.4 241128 37016 ?        Sl   Apr15   0:25 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8086 -container-ip 10.245.2.3 -container-port 8086
root      1021  0.0  0.5 175848 38608 ?        Sl   Apr15   0:25 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8083 -container-ip 10.245.2.3 -container-port 8083
```

In the containerVM, kubelet moves the docker process to the docker-daemon cgroup. If the `docker-proxy` processes was created _before_ that, they wouldn't have been moved along with the docker daemon. This seems to be the case for most freshly created e2e clusters (I checked two clusters). If the `docker-proxy` processes are created _after_ docker has been moved, they're be part docker-daemon cgroup.

These cause a several issues when tracking the resource usage in the e2e tests:
- Only one node in the cluster _may_ have higher memory usage than others.
- If the docker daemon is managed by systemd, it's likely that the `docker-proxy` processes are charged to the same docker.service cgroup. This is different from the default behavior we see in containerVM nodes.

Options to mitigate this impact on the resource tracking tests:
1. Increase the memory threshold to account for the difference.
2. Move the resource usage tracking test to the node e2e suite, where there is no cluster addons pods.

I think we can relax the memory threshold first (1), and then migrate this test later (2).

Besides the test issues, we still have the problem of not being able to track the docker runtime usage consistently. Should we charge the docker-proxy process to the pod or should in be in docker generally? 

/cc @dchen1107 @vishh @kubernetes/sig-node

**Comment by andyzheng0831** [comment]
cc/ @andyzheng0831 @wonderfly

**Comment by vishh** [comment]
> If the docker daemon is managed by systemd, it's likely that the docker-proxy processes are charged to the same docker.service cgroup. This is different from the default behavior we see in containerVM nodes.

This is a known issue. Ideally, we should have our supervisord scripts setup cgroups for docker.

**Comment by vishh** [comment]
> Besides the test issues, we still have the problem of not being able to track the docker runtime usage consistently. Should we charge the docker-proxy process to the pod or should in be in docker generally?

Why don't we fix the issue rather than hacking the test?

**Comment by yujuhong** [comment]
@vishh, what's the desired behavior -- `docker-proxy` be charged per pod or to the docker daemon? If it's the latter, the test has to accommodate the potentially higher usage and/or should not be run with addon pods. If it's the former, do you have any suggestions on how to fix it?

**Comment by vishh** [comment]
Ideally our init service should move docker daemon. That is not a viable option on ContainerVM as of now.
For now, I'd say we should have the kubelet move the proxy process as well.

**Comment by vishh** [comment]
My desired policy would be to move the proxy to a pod/container level
cgroup. But that is not possible today.

**Comment by yujuhong** [comment]
> My desired policy would be to move the proxy to a pod/container level
> cgroup. But that is not possible today.

Then the test still have to deal with the weird memory usage spike on one node, and I don't see why we can *just fix the issue* without touching the test. 

On the other hand, why does monitoring-influxdb-grafana need to use host port? @vishh do you know if it's safe to remove that?

**Comment by vishh** [comment]
It is safe to remove hostports from influxdb-grafana pod.

> Then the test still have to deal with the weird memory usage spike on one
node, and I don't see why we can *just fix the issue* without touching the
test.

I see your point. What I meant was that we should not fix the test alone,
but also update kubelet to do what it can do reliably today.

**Comment by yujuhong** [comment]
> I see your point. What I meant was that we should not fix the test alone,
> but also update kubelet to do what it can do reliably today.

Got it. I agree that we should fix the root cause regardless. @dchen1107 will probably know whether we're in the process of handling the root cause.

As far as the test goes, I'll try removing the host port usage from influxdb-granfana pod as the first step. #24437
