### ISSUE TITLE
Junit.xml for integration test

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#24412]
tests in `test/integration/...` do not emit a `junit.xml`, so we can't see details of their failures in Jenkins.

Either run a post-processor like https://github.com/jstemmer/go-junit-report, or convert tests to use Ginkgo/Gomega, which will emit junit.xml.  The former seems easier.

**Comment by gmarek** [comment]
cc @kubernetes/sig-testing

**Comment by erictune** [comment]
Or https://github.com/tebeka/go2xunit

**Comment by spxtr** [comment]
I think `test/integration` tests do output JUnit, but `cmd/integration` tests do not. Related: #21420

**Comment by ixdy** [comment]
Yup, @spxtr is correct. Though `go-junit-report` is basically a ball of hacks and I wish go had a better way.

**Comment by spxtr** [comment]
Related, and somewhat sad: https://github.com/golang/go/issues/2981

**Comment by erictune** [comment]
cmd/integration does not have junit, but I don't want to encourage putting more tests in there.
