### ISSUE TITLE
kubelet test flake - coreos killed ssh connection mid test

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#24423]
>
17:20:21 • [SLOW TEST:11.682 seconds]
17:20:21 PrivilegedPod
17:20:21 /var/lib/jenkins/workspace/kubelet-gce-e2e-ci/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:84
17:20:21   should test privileged pod
17:20:21   /var/lib/jenkins/workspace/kubelet-gce-e2e-ci/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:83
17:20:21 ------------------------------
17:20:21 I0418 00:19:33.350505    1028 privileged_test.go:154] Deserialized output is map[error:exit status 2 output:RTNETLINK answers: Operation not permitted
17:20:21 ]
17:20:21 ••••••Connection to tmp-node-e2e-ca7b49a2-e2e-node-coreos-stable20160218-image closed by remote host.
17:20:21 
17:20:21 ================================================================

[full logs](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/1654)

**Comment by pwittrock** [comment]
Adding ssh keep alive in #24426 to see if this fixes the issue

**Comment by pwittrock** [comment]
This is still happening and is the most frequent cause of flaky tests:

>
Connection to tmp-node-e2e-18a7a193-e2e-node-coreos-stable20160218-image closed by remote host.

**Comment by dchen1107** [comment]
@yifan-gu please triage or delegate. This causes a lot of flakes in node e2e test suite. Thanks!

**Comment by pwittrock** [comment]
Let me know if you need more logs

**Comment by yifan-gu** [comment]
cc @euank

**Comment by yifan-gu** [comment]
cc @crawford

**Comment by yifan-gu** [comment]
@pwittrock Did you turn off the automatic reboots on the coreos machine?

**Comment by yifan-gu** [comment]
@pwittrock Also, do you have the console output of the coreos machine?

**Comment by pwittrock** [comment]
@yifan-gu No I didn't turn them off.  How should I do that?  The test deletes the instance after it completes so the console output is lost.  I can update the test to keep failed instances around so that we can get debug info.

**Comment by yifan-gu** [comment]
@pwittrock So you want to turn that off, otherwise the coreos will reboot after it automatically updates.(https://coreos.com/os/docs/latest/update-strategies.html#disable-automatic-updates-daemon)

If you are using cloud config, you can do by drop in these https://github.com/yifan-gu/kubernetes/blob/gce_coreos_rkt/cluster/gce/coreos/node.yaml#L4-L10

**Comment by pwittrock** [comment]
I am just using a vanilla image off of gce.  [this page](https://coreos.com/os/docs/latest/booting-on-google-compute-engine.html) describes how to add a cloud config as metadata to an instance.  Do you know if this will also add it to an image I create from the instance?

**Comment by crawford** [comment]
@pwittrock it will not. What you _can_ do is just boot an instance and mask locksmith (`systemctl mask locksmithd.service`).

**Comment by pwittrock** [comment]
@crawford Thanks.  I will update the e2e tests to do this.

**Comment by smarterclayton** [comment]
Seeing something like this almost continually now: https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/24966/node-pull-build-e2e-test/3589/build-log.txt

**Comment by philips** [comment]
@pwittrock So, @vishh just disabled CoreOS instead of waiting for you to fix this. Do you need help fixing this or can @yifan-gu help?

**Comment by philips** [comment]
@vishh can you reopen this, your fix just disables the test instead of fixing the cause. https://github.com/kubernetes/kubernetes/pull/24990

**Comment by yifan-gu** [comment]
@pwittrock I don't know how you provision the machine, do you actually run [this script](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/environment/setup_host.sh) for each instance?

If you want to add cloud config when creating the instance, you can do `gcloud compute instances create ${node_name} --metadata-from-file "user-data=${path_to_cloud_config}"`

**Comment by pwittrock** [comment]
@philips Yes, sorry.  I intended to fix the issue without disabling, but we started seeing a lot of failures so I asked @vishh just to disable until we could apply a fix, which is at the top of my list.  I have been OOO but will get back late tonight.  If @yifan-gu can update the [node test harness](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/e2e_node_suite_test.go) to prevent the instance for auto-updating and restarting that would definitely help.  I also plan to update the coreos image to a more recent release and add a beta imate.

**Comment by pwittrock** [comment]
@yifan-gu We provision machines using images we configured with that script.  The script is just run once and then we save the instance to an image.

**Comment by yifan-gu** [comment]
@pwittrock OK, so does [this](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/e2e_node_suite_test.go#L56) run on the machine? How can I test if I added something here and it works?

**Comment by pwittrock** [comment]
Yes that run on the host being tested.  For testing we can use the PR builder `@k8s-bot node e2e test this`.  You can add the coreos in the same PR as the fix and it will be tested by the PR builder.  Alternatively, you can create your own image in another project and use that per the instructions [here](https://github.com/kubernetes/kubernetes/blob/dae5ac482861382e18b1e7b2943b1b7f333c6a2a/docs/devel/e2e-node-tests.md).
