### ISSUE TITLE
./hack/build-go.sh can take 35 minutes on jenkins

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#24424]
kubelet ci test hit 45 minute timeout of after spendint 35 minutes building the go binaries

> 02:10:14 Started by timer
> ...
> 02:13:43 I0417 02:13:43.341929   17879 e2e_build.go:34] Building k8s binaries...
> 02:48:23 I0417 02:48:23.986454   17879 e2e_remote.go:57] Building ginkgo k8s test binaries...
> ...
> 02:55:58 
> Build timed out (after 45 minutes). Marking the build as failed.

[full log](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/1632)

**Comment by janetkuo** [comment]
+1

**Comment by janetkuo** [comment]
Ref #24285
