### ISSUE TITLE
Create logging soak

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#24427]
Problem

Various logging frameworks and the ELK stack need to be rapidly validated for survivability over time. 

Solution

Create an E2E that soaks the container-space with logs at a well defined rate, so users can verify that logging holds up to TB, PB, etc. scale.

cc @kubernetes/sig-scalability  @kubernetes/sig-testing  (@timothysc)

**Comment by jayunit100** [comment]
This PR will reuse ` +func (f *Framework) CreateServiceWithPods(contPort int, svcPort int, appName string, podSpec func(n api.Node) api.PodSpec, count int) { ` from 22869.

**Comment by timothysc** [comment]
This is done, closing.
