### ISSUE TITLE
Improve/fix kubelet perf dashboard

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#24436]
http://perf-dash.k8s.io/ now includes kubelet cpu and memory usage distributions. This is great! Thanks @Random-Liu!
There are some issues with it and some enhancements that can be made to make the dashboard useful.
1. Cpu usage can be in cores instead of a percentage
2. The graph currently plots a distribution of average usage. Having at-least max in addition to average will be useful with making decisions with this data. For example, average RSS can be a lot lesser than max RSS and the limit needs to be set based on the max usage.

cc @pwittrock @yujuhong @Random-Liu

**Comment by Random-Liu** [comment]
It would be easy to update the perfdash if we have the data exposed in kubelet perf e2e test.

**Comment by yujuhong** [comment]
> The graph currently plots a distribution of average usage. Having at-least max in addition to average will be useful with making decisions with this data. For example, average RSS can be a lot lesser than max RSS and the limit needs to be set based on the max usage.

Are these exposed via the kubelet summary metrics API? If so, we can add them to the test.

**Comment by vishh** [comment]
> Are these exposed via the kubelet summary metrics API? If so, we can add them to the test

Not yet. cAdvisor does [provide](https://github.com/google/cadvisor/blob/master/info/v2/container.go#L188) those stats though.

We can address `1` right away.

**Comment by yujuhong** [comment]
@Random-Liu, I just noticed that the kubelet's RSS memory is higher than the working set, which doesn't seem right. I checked the build logs and they are correct. Is it possible that those two are revered by accident?

**Comment by Random-Liu** [comment]
@vishh Will send a PR addressing `1` right away.

@yujuhong May be something wrong when calculating the node average, I'll check it.
