### ISSUE TITLE
rkt: Support dynamic pod.

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#24430]
Today, rkt's pod is immutable, which means once started, all the changes made to the pod or the containers within the pod will require the pod to be restarted.

As we are moving towards mutable pods in the future, rkt should support container level interfaces, which can also benefit us from making the container runtime interface more generic and runtime agnostic https://github.com/kubernetes/kubernetes/issues/22964 , as well as implement something like https://github.com/kubernetes/kubernetes/pull/23567

Ref https://github.com/coreos/rkt/issues/2375

**Comment by jonboulle** [comment]
@tmrts want to assign this to yourself?

**Comment by tmrts** [comment]
@jonboulle done, feel free to ping me in related issues if I miss one

**Comment by fabiand** [comment]
Is somebody aware of an issue tracking the general topic of a mutable pod?

**Comment by yujuhong** [comment]
I think we can close this and track the relevant issues in rkt or rkelet repositories, if this is not already done.
