### ISSUE TITLE
No e2e or integration tests for third party watch

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#24441]
We had a bug introduced by streaming serialization and we didn't catch it in tests.

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery not sure who is tracking third party resource completion right now.

**Comment by lavalamp** [comment]
@brendandburns You were working on a test for this at one point, did it exercise watch?

**Comment by AdoHe** [comment]
I think watch on third party resource will fail. I just came across this issue #24963 a few days ago.

**Comment by brendandburns** [comment]
There is an outstanding PR:

https://github.com/kubernetes/kubernetes/pull/19852

that I'm (slowly) working on getting going.  There are several issues that are blocking it working correctly. 

but it doesn't test watch.

It's currently blocked on getting https://github.com/kubernetes/kubernetes/issues/25084 merged.

**Comment by AdoHe** [comment]
@brendandburns anything I can help?

**Comment by brendandburns** [comment]
I'm going to take a look at fixing this today.

**Comment by smarterclayton** [comment]
CRD replaces TPR.
