### ISSUE TITLE
Flake in ./hack/test-cmd.sh, too few cassandra labels

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#24453]
```
21:11:50 FAIL!
21:11:50 Get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}
21:11:50   Expected: cassandra:cassandra:cassandra:cassandra:
21:11:50   Got:      cassandra:cassandra:
21:11:50 (B
21:11:50 1727 ./hack/test-cmd.sh
21:11:50 (B
```
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/11039/

**Comment by mikedanese** [comment]
And again http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/11052/

cc @caesarxuchao @kuberentes/kubectl

**Comment by caesarxuchao** [comment]
Last time this test was reported as flaky is #22128, but they seem to be irrelevant.

**Comment by bgrant0607** [comment]
Dupe of #24704
