### ISSUE TITLE
CIDR management and Node health monitoring should be done by separate controllers

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24467]
Currently those two, completely independent things are done by the NodeController.

cc @kubernetes/goog-control-plane

**Comment by gmarek** [comment]
Ugh, I'm not really sure how it's related to scalability sig (except the fact that I work on Node controller in my free cycles). There's no good SIG for this, but maybe @kubernetes/sig-network-misc want to take ownership of CIDR allocator?

**Comment by bowei** [comment]
This is sig-network owned.

**Comment by aanm** [comment]
@gmarek you can set up the pod-cidrs on the api-server

**Comment by gmarek** [comment]
@aanm - I know, I wrote (parts) of that code:) This is only about the scalability SIG assignment.

**Comment by gmarek** [comment]
@cheftako
