### ISSUE TITLE
Load Balanced NFS Volume

### ISSUE THREAD

**Issue by owenhaynes** [kubernetes/kubernetes#24469]
At the moment the NFS Volume only take a single IP as the NFS server, this does not play well with systems such as Avere which acts as a cache on top of NFS, and multiple servers addresses are offered. 

Maybe something similar should be done to the NFS volume like we have on the Glusterfs volume, and use endpoints to locate the NFS server address from a pool?

**Comment by thockin** [comment]
Could you make a Service from your Avere endpoints and then use the Service
IP?  I have not used Avere so I don't know how well it would work...

**Comment by owenhaynes** [comment]
On the font of it it just acts like a normal NFS server, but provides 1-n IPs for each of the caches in the Avere cluster. 

Will try using the service IP, but there must of been a reason why the gluster volume did not take this approach?

**Comment by thockin** [comment]
I am not sure why we didn't do this for gluster, and I am not saying no to
making this a list, but let's try Services first :)

@rootfs

**Comment by rootfs** [comment]
glusterfs is a symmetric scale-out filesystem, while generic NFS is not. NFS HA implementations vary among rather vendors. In your case, making a service IP (or use round robin DNS) looks the good solution.

**Comment by owenhaynes** [comment]
I agree service IP is most likely the best option after some thought.
