### ISSUE TITLE
Link to L7 load balancer controller dead in GLBC addon README

### ISSUE THREAD

**Issue by aknuds1** [kubernetes/kubernetes#24462]
The [GLBC cluster addon README](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-loadbalancing/glbc) has [a dead link](https://github.com/kubernetes/contrib/tree/master/Ingress/controllers/gce) to the Google L7 load balancer controller.

**Comment by paralin** [comment]
+1

**Comment by mikedanese** [comment]
LGTM'd the pr
