### ISSUE TITLE
Add --verbose option to test/e2e/ 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#24471]
_Problem_
There are a few issues in the e2e tests which are very verbose at +10 node scale.  This can make it hard to interpret and read through the results of a test run, esp. when there are multiple failures.  The two things i've seen in the past.
- hanging at large scale.
- (failures) dumping all data for 100s of nodes to stdout.  

_Proposed Solution (4/18/2016)_ 

When developing e2es at small (2-4) node scale, the info is very useful.  We should log lots of stuff, but just minimize the output, unless the user specifies `--verbose`.

_UPDATED SOLUTION (4/21/2016)_

The simplest solution wound up simply supporting (2) below.  (1) can be done later if we really need to.  

So we should
1. introspect the cluster and find out how many nodes there are.
2. Add a `Debugf` which runs by default in small clusters.
3. Make dump call `Debugf`.
4. Drastically reduce the use of `Logf` across the e2e suite.

cc @kubernetes/sig-testing @kubernetes/sig-scalability

**Comment by jayunit100** [comment]
```
currStep = "N/A"
currCount = 0
print "starting"
def status():
        print currStep, " ", currCount
for line in fileinput.input():
        if "STEP" in line:
                status()
                currStep = line
                currCount = 0
        else:
                currCount = currCount + 1
print currCount
```
runnning this on the test output from the CI, I get these culprits for scaleout overlogging...

```
STEP: Waiting for a default service account to be provisioned in namespace
  85
STEP: waiting for all containers in name=update-demo pods to come up.
  36
STEP: Waiting for a default service account to be provisioned in namespace
  85
STEP: Waiting for a default service account to be provisioned in namespace
  85
STEP: waiting for all containers in name=update-demo pods to come up.
  36
STEP: waiting for all containers in name=update-demo pods to come up.
  49
STEP: creating replication controller cleanup60-7b6834b4-0720-11e6-a521-42010af0000d in namespace e2e-tests-kubelet-hb0om
  59
STEP: deleting replication controller cleanup60-7b6834b4-0720-11e6-a521-42010af0000d in namespace e2e-tests-kubelet-hb0om
  103
STEP: Waiting for a default service account to be provisioned in namespace
  47
STEP: Waiting for a default service account to be provisioned in namespace
  125
STEP: creating replication controller svc-latency-rc in namespace e2e-tests-svc-latency-cs82v
  407
STEP: Waiting for a default service account to be provisioned in namespace
  32
STEP: Waiting for a default service account to be provisioned in namespace
  85
STEP: Successfully fetched pod logs:KUBERNETES_PORT=tcp://10.0.0.1:443
  24
STEP: checking the created volume is readable and retains data
  25
STEP: Waiting for a default service account to be provisioned in namespace
  125
STEP: curling local port output
  28
STEP: waiting for all containers in name=update-demo pods to come up.
  36
STEP: waiting for all containers in name=update-demo pods to come up.
  32
STEP: Using the kubectl in /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/kubernetes/platforms/linux/386/kubectl
  21
STEP: Running kubectl in netexec via an HTTP proxy using https_proxy
  21
STEP: using delete to clean up resources
  24
STEP: creating replication controller rc-light in namespace e2e-tests-horizontal-pod-autoscaling-s2l8u
  27
STEP: Successfully fetched pod logs:content of file "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt": -----BEGIN CERTIFICATE-----
  23
STEP: creating replication controller proxy-service-rd0m4 in namespace e2e-tests-proxy-51h6k
  692
STEP: creating replication controller rc-light in namespace e2e-tests-horizontal-pod-autoscaling-0nq13
  30
136
```

**Comment by jayunit100** [comment]
fyi @timothysc "scale killers" overlogging.

**Comment by timothysc** [comment]
Then fix them ;-)

**Comment by jayunit100** [comment]
On it yup

**Comment by jayunit100** [comment]
culprit: `config.DefaultReporterConfig.Verbose` this is currently set to true.

- This has the advantage of giving us spec progress.
- The disadvantage is that in ginkgo that also means the Logs get streamed out.

So, I think the simplest solution is to have the debug logs go into an output file, which has both INFO as well as DEBUG.

**Comment by jayunit100** [comment]
Dug some more, I have a patch that will do this the easy way, it will suppress everything to level `-v 2` using `Debugf`.  That way the user can decide and no need for extra directories/files.
