### ISSUE TITLE
AWS: Support spot fleet

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#24472]
It would be nice to support Spot Fleet on AWS, for the nodes.  The challenge is that Spot Fleet does not support tags (AFAIK), and we rely on our nodes being tagged in the k8s AWS cloudprovider.

**Comment by innovia** [comment]
Here's a working solution for SPOT Fleet:

1) create an IAM role for the spot fleet
```json
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Action": [
       "ec2:DescribeImages",
       "ec2:DescribeSubnets",
       "ec2:RequestSpotInstances",
       "ec2:TerminateInstances",
       "iam:PassRole"
        ],
    "Resource": ["*"]
  }]
}
```

2) place everything below (except the deploy.js) in a folder called k8-minion-spot

3) Create the base config for your fleet (with the role arn)
```json
{
  "IamFleetRole": "arn:aws:iam::123456789012:role/aws-ec2-spot-fleet-role",
  "TargetCapacity": 8, 
  "SpotPrice": "0.01",
  "TerminateInstancesWithExpiration": true
}
```

4) set the launch config specification as follow:
* note the ami number for your matching selected distro
* note the subnet you need the instance to be on ( multiple subnets = multiple launch configs / fleets setup)
```
{
    "ImageId": "ami-6c9ea606",
    "KeyName": "kubernetes-3b27b382121ff545b1521c80b95c207c",
    "NetworkInterfaces": [
      {
        "DeviceIndex": 0,
        "SubnetId": "subnet-12345678",
        "DeleteOnTermination": true,
        "AssociatePublicIpAddress": true,
        "Groups": [
          "sg-e6128d9e"
        ]
      }
    ],
    "BlockDeviceMappings": [
        {
            "DeviceName": "/dev/sdc",
            "VirtualName": "ephemeral0"
        },
        {
            "DeviceName": "/dev/sdf",
            "VirtualName": "ephemeral3"
        },
        {
            "DeviceName": "/dev/sdd",
            "VirtualName": "ephemeral1"
        },
        {
            "DeviceName": "/dev/sde",
            "VirtualName": "ephemeral2"
        },
        {
            "DeviceName": "/dev/xvda",
            "Ebs": {
                "DeleteOnTermination": true,
                "VolumeSize": 32,
                "VolumeType": "gp2"
            }
        }
    ],
    "IamInstanceProfile": {
        "Name": "kubernetes-minion"
    }
}
```

5) set the bid pricing and weight in a file called meta.json
* the Target Capacity from the step1 is being controlled by the weight here

```json

{
    "subnets": [
        "subnet-0b17a621"
    ],
    "instances": {
        "c3.large": {
            "bid": "0.105",
            "weight": 2
        },
        "c3.xlarge": {
            "bid": "0.21",
            "weight": 4
        },
        "c3.2xlarge": {
            "bid": "0.42",
            "weight": 8
        },
        "c3.4xlarge": {
            "bid": "0.479",
            "weight": 16
        },
        "c3.8xlarge": {
            "bid": "0.479",
            "weight": 32
        },
        "c4.large": {
            "bid": "0.105",
            "weight": 2
        },
        "c4.xlarge": {
            "bid": "0.209",
            "weight": 4
        },
        "c4.2xlarge": {
            "bid": "0.419",
            "weight": 8
        },
        "c4.4xlarge": {
            "bid": "0.419",
            "weight": 16
        },
        "c4.8xlarge": {
            "bid": "0.419",
            "weight": 32
        }
    }
}
```

6) copy the user data from the instance of the kuberentes minon (node) using awscli 
and alter it  to allow tags and node labels

save the file as user-data.sh.orig
```bash
#! /bin/bash
echo "Create ec2 Tags!"

INSTANCE_ID=$(curl -S http://169.254.169.254/latest/meta-data/instance-id)

/usr/local/bin/aws ec2 create-tags --region 'us-east-1' --resources $INSTANCE_ID \
  --tags "Key=Name,Value=kubernetes-minion Spot" \
         "Key=Role,Value=kubernetes-minion" \
         "Key=KubernetesCluster,Value=kubernetes"

mkdir -p /var/cache/kubernetes-install
cd /var/cache/kubernetes-install
cat > kube_env.yaml << __EOF_KUBE_ENV_YAML
ENV_TIMESTAMP: '2016-03-20T09:32:51+0000'
INSTANCE_PREFIX: 'kubernetes'
NODE_LABELS: 'k8group=kubernetes-system'
..
...
....
```

7) make sure to change the role for the kubernetes minions to allow ec2 create tags

8) run the following commands to generate a valid compressed user-data file
```bash
cp user-data.sh.orig user-data.sh
gzip user-data.sh
mv user-data.sh.gz user-data.sh
```

9) run this deploy script (copy it to a file called deploy.js and chmod a+x deploy.js )

```bash
./deploy k8-minion-spot
```


```javascript
'use strict';
var aws = require('aws-sdk');
var ec2 = new aws.EC2({region: 'us-east-1'});
var fs = require('fs');
var async = require('async');
var directory = process.argv[2];
if (!directory) {
    console.log("You must call this function with the name of the directory being deployed");
    process.exit(1);
}


async.waterfall([
    function checkDirectory(cb) {
        fs.open(directory, 'r', cb);
    },
    function getStaticFiles(ignore, cb) {
        async.mapSeries([
            directory + '/base-config.json',
            directory + '/launch-specification.json',
            directory + '/user-data.sh',
            directory + '/meta.json'
        ], fs.readFile, cb);
    },
    function stuff(contents, cb) {
        var configstr = contents[0].toString();
        var launchstr = contents[1].toString();
        var userData = contents[2].toString('base64');
        var metastr = contents[3].toString();
        var meta;
        try {
            JSON.parse(configstr);
            JSON.parse(launchstr);
            meta = JSON.parse(metastr);
        } catch (e) {
            return cb(e);
        }
        async.mapSeries(meta.subnets, function (subnet, cb) {
            var thisConfig = JSON.parse(configstr);
            thisConfig.LaunchSpecifications =
                    Object.keys(meta.instances).map(function (instanceSize) {
                var instanceConfig = meta.instances[instanceSize];
                var thisLaunchSpec = JSON.parse(launchstr);
                thisLaunchSpec.InstanceType = instanceSize;
                if (instanceConfig.bid) {
                    thisLaunchSpec.SpotPrice = instanceConfig.bid;
                }
                if (instanceConfig.weight) {
                    thisLaunchSpec.WeightedCapacity = instanceConfig.weight;
                }
                thisLaunchSpec.NetworkInterfaces[0].SubnetId = subnet;
                thisLaunchSpec.UserData = userData;
                return thisLaunchSpec;
            });
            ec2.requestSpotFleet({
                SpotFleetRequestConfig: thisConfig
            }, cb);
        }, cb);
    }
], function (err, resp) {
    if (err) {
        console.log(err);
    } else if (resp) {
        console.log(resp);
    }
});
```

enjoy :)

**Comment by roberthbailey** [comment]
@justinsb what is the status of this?

**Comment by justinsb** [comment]
Moving to 1.4

**Comment by diegomarangoni** [comment]
Would be nice to extend this support to [kops](https://github.com/kubernetes/kops) aswell.

**Comment by dims** [comment]
@justinsb ok to move this to 1.6? please holler if not appropriate

**Comment by philk** [comment]
For anyone who stumbles across this and is curious. Using an AutoScaling Group that requests spot instances seems to work just fine.

**Comment by ApsOps** [comment]
@philk won't there be request failures when a node goes away? 🤔 How do you deal with that?

**Comment by innovia** [comment]
@philk ASG can create spot instances but for the same kind, SPOT Fleet ensure that you will have the capcaity you need because of the diversity of the instance sizes

@ApsOps  when the node goes away kubernetes master saves the state the pod should be ("Running") on etcd does it will reallocate it to another node.
so it's a very good setup for queue related stuff like SQS workers
 
with regards to node goes away panic -> you can have a script that monitor the termination notice and act to shutdown the node gracefully

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html

**Comment by philk** [comment]
@ApsOps I guess I should've explained our setup a bit better.
We're using the [cluster-autoscaler](https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler) which handles draining a node prior to terminating it and we're only doing this on data processing nodes (just read jobs off a queue) that could be terminated arbitrarily by AWS and the processing would get retried by another node after a timeout.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by spiffxp** [comment]
@kubernetes/sig-aws-misc do you want this in v1.7? is this the right sig to own this issue?

**Comment by justinsb** [comment]
sig/aws definitely; this is highly specific to AWS.

1.7, I don't think it's going to happen; moved to next-candidate.

**Comment by bcorijn** [comment]
AWS has announced spot fleet now supports tags: https://aws.amazon.com/about-aws/whats-new/2017/07/tag-your-spot-fleet-ec2-instances/

**Comment by egeland** [comment]
Hoping this will land soon... ?

**Comment by FisterDotOrg** [comment]
@justinsb Is this even necessary now that AWS supports propagating tags?

**Comment by azman0101** [comment]
What's new about this support ?

By the way 
[New – Stop & Resume Workloads on EC2 Spot Instances
](https://aws.amazon.com/blogs/aws/new-stop-resume-workloads-on-ec2-spot-instances/)

**Comment by jnicholls** [comment]
+1

**Comment by KernelPanicAUS** [comment]
Happy new year everyone!!
Any updates on this feature request?

**Comment by bhack** [comment]
@kubernetes/sig-aws-misc Have this feature a K8S target release?

**Comment by KernelPanicAUS** [comment]
@kubernetes/sig-aws is this still on the roadmap?

**Comment by KernelPanicAUS** [comment]
anything?
