### ISSUE TITLE
kubectl create secret generic does not support values with '=' character when --from-literal option is used

### ISSUE THREAD

**Issue by rijuk** [kubernetes/kubernetes#24488]
When a value that contains the character '=' is used, "kubectl create secret" currently fails with the following error

$ kubectl create secret generic mysecret --from-literal=key=foo= --dry-run
error: invalid literal source key=foo=, expected key=value

'=' is a common character for base64 encoded values. So, this pretty much prevents passing any base64 encoded value.

The issue seems to be happening because of this check - https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/kubectl.go#L233

**Comment by bgrant0607** [comment]
cc @pmorie @derekwaynecarr

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by derekwaynecarr** [comment]
I assume you need to send base64 because you consume base64?  Agree we should fix.

**Comment by derekwaynecarr** [comment]
The simple fix is to split on the first '=' only, I will send a PR this week.

@pmorie - ack as config map i think calls the same underlying code.

**Comment by pmorie** [comment]
@derekwaynecarr it does
