### ISSUE TITLE
Does apiserver support websockets when watching for events?

### ISSUE THREAD

**Issue by 0x777** [kubernetes/kubernetes#24482]
The documentation [here](https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/api.md) suggests that it does. 

However, I can't get this working, in the websocket library I'm using, when I try to make open a ws connection to `127.0.0.1:8001/api/v1/pods?watch=true`, it fails with a message `Wrong response status or message`. So, I tried using curl to inspect the headers sent by the server 

``` bash
curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: localhost:8001" -H "Origin:http://localhost:8001" 'http://127.0.0.1:8001/api/v1/pods?watch=true'
```

The response headers do not suggest that a protocol upgrade is happening. 

``` http
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Tue, 19 Apr 2016 17:14:14 GMT
Transfer-Encoding: chunked
```

I tried hitting the apiserver directly (without the kubectl proxy) and no luck there either.

**Comment by 0x777** [comment]
This is happening because of an [issue](https://github.com/golang/go/issues/6361) in golang's net package (the Haskell library I was using wasn't sending the `Origin` header). 

However, websockets do not work with `kubectl proxy`, which is the [recommended method](http://kubernetes.io/docs/user-guide/accessing-the-cluster/#accessing-the-api-from-a-pod) for accessing the API from inside a pod.

**Comment by smarterclayton** [comment]
Closing, moving focus to #25126
