### ISSUE TITLE
Update NewRelic DaemonSet example

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#24484]
The NewRelic DaemonSet example needs a best-practices pass and cleanup.

See #16014, comments at the end.

@brendandburns

**Comment by alanhartless** [comment]
Will the update include resolving 

```
 Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 8fd79675bc4f560c9cdb306e030964209e28c337b56bfa60d64d0c51ed4f707f: /dev/mqueue is not mounted, but must be for --ipc=host
```

? :-)

**Comment by alanhartless** [comment]
For GCE, I just removed hostIPC: true and it works now.

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by Trane9991** [comment]
The same problem.

Strage that after running newrelic agent in docker contaienr manually with
`sudo docker run -it --privileged=true --pid=host --net=host -v /sys:/sys -v /dev:/dev -v /var/run/docker.sock:/var/run/docker.sock -v /var/log:/var/log:rw -e NRSYSMOND_license_key=REPLACE_WITH_REAL_KEY -e NRSYSMOND_logfile=/var/log/nrsysmond.log newrelic/nrsysmond:latest bash`

**/dev/mqueue** was automounted and then kubernetes was able to start it too.

**Comment by ankon** [comment]
As part of this best-practices cleanup it would be nice to also simplify the whole thing: secrets can be used as sources for variables, so most of the "magic" of that example can just be deleted.

**Comment by kargakis** [comment]
/sig apps
@ahmetb

**Comment by ahmetb** [comment]
We won't maintain those examples in the kubernetes/example repository going further. We encourage maintainers of such third party examples (if any) to move the example to another repository where they can easily maintain, or make it a Helm chart for others to consume easily.

/assign

**Comment by powellc** [comment]
Any chance you can add a deprecation notice to the examples directory or just remove it altogether? Took me a while to realize that these aren't maintained anymore.
