### ISSUE TITLE
Cassandra on Kubernetes - Update Docker Image

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#24493]
Hey all

So a few observations 😄 I recommend some TLC for the docker example image.  We probably want to look at using the docker image from here:

https://hub.docker.com/_/cassandra/

This we lessen a lot of the pain points.  For instance:

- version wise we are way behind
- we need to compile the snitch with the same version of C*
- the jdk that is being used is like "NOT RECOMMENDED", as it gives us a warning, what the heck are you doing

I will put in a pull request unless there are any objections.

**Comment by bgrant0607** [comment]
Thanks, @chrislovecnm. 

One challenge we have is that we run tests against some of our examples, including cassandra, to try to ensure they stay working. However, we've found Docker Hub to be too unreliable to test against. #13288

Also, what would we do about the custom seed provider?

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by chrislovecnm** [comment]
@bgrant0607 I understand about the reliability ... grrr.  We probably want to appropriate how the build the docker :)  Let me start on that. You have any problem with running it off of alpine?  I am guessing that google has a gcr.io alpine or jre8 image. 

The custom seed provider is still under review.  I am talking with peeps from Datastax (commercial cassandra) this week.  I would like to get the Seed Provider more stable, and see if we can get it into the C* code base.

**Comment by chrislovecnm** [comment]
Couple of notes

1. see if google/debian:jessie has openjdk 8
2. the way we have cassandra.yaml setup the cluster name is not configurable
3. get the SeedProvider building against 3.3

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kubernetes/pull/24885 fixes all of this 😄

**Comment by bgrant0607** [comment]
@chrislovecnm Re. alpine: We've had problems with DNS resolution in the past:
https://github.com/gliderlabs/docker-alpine/blob/master/docs/caveats.md

It looks like you decided not to use it, though.

**Comment by chrislovecnm** [comment]
@bgrant0607 nope figured out Java 8 on Debian. Only really care that is is Linux and Java 8 ... Lol

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kubernetes/pull/26022 is a good start.  Would like to migrate to alpine, once DNS is not a problem....  Or get the small version of ubuntu working.
