### ISSUE TITLE
Quota not fully enforced in a HA setup?

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#24494]
Reflectors are used extensively in Kubernetes to reduce the load on the etcd backend. In a non-HA setup, where there's only 1 apiserver, inconsistencies between what's in the local cache vs. what's actually in etcd probably doesn't matter as there's only 1 apiserver that's touching this data. However, in a non-HA setup, there's a higher chance of inconsistencies between local cache and etcd as multiple apiservers are in play. I could see there are corner cases that an apiserver could admit a pod to be created simply because its local cache is a bit behind the actual state. Could this happen? If so, are there anything put in place to mitigate such situation?

**Comment by huang195** [comment]
Looking at this a bit more, it seems there are other problems in a HA setup. Due to having multiple apiservers servicing requests and during quota checking, nothing is locked, but we might get the following problematic race condition:

1. apiserver1 checks if pod A can be admitted (let's assume quota is set to 5 and 4 are in use)
2. apiserver2 checks if pod B can be admitted (again, it will see we're under the quota)
3. apiserver1 admits pod A
4. apiserver2 admits pod B
5. We now have 6 pods running in this namespace where 5 is set as the quota limit

**Comment by erictune** [comment]
@derekwaynecarr

**Comment by derekwaynecarr** [comment]
Even when not in HA there is a potential for a race between admission and
quota controller recalculation.

I had some initial ideas on how to mitigate that but have not found time to
address.  In practice, I have yet to encounter this race, but it had a
similar outcome where you could exceed quota by 1.

A write up that describe situation was here:
https://github.com/kubernetes/kubernetes/pull/20113

In reality, I think it would be sufficient to have a flag on the quota
document to alert when its usage is greater than its specification so
operators can choose what they want to do to address.  This is similar to
situations where quota is lowered below observed usage.

**Comment by derekwaynecarr** [comment]
To elaborate some more, my hope was that we could use etcd3 multi object
transactions when that became available but that is still TBD if it's
something we will leverage in admission control.

**Comment by huang195** [comment]
@derekwaynecarr ah ok, so even in the non-HA setup, a race condition could happen, although very rarely. It seems in a HA setup (see the above example), a race condition can happen more commonly due to user requests getting sprayed to all the apiservers. I see the PR was closed. Is there any workaround in the meantime before etcd3 multi object transaction is available?
