### ISSUE TITLE
e2e_node/privileged_test gets Unexpected Error executing in Docker Container: 7

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#24508]
>
15:40:09 STEP: Creating a privileged pod
15:40:09 STEP: Executing privileged command on privileged container
15:40:09 STEP: Exec-ing into container over http. Running command: curl -q 'http://172.17.0.2:8080/shell?shellCommand=ip+link+add+dummy1+type+dummy'
15:40:09 
15:40:09 ------------------------------
15:40:09 • Failure [10.173 seconds]
15:40:09 PrivilegedPod
15:40:09 /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:84
15:40:09   should test privileged pod [It]
15:40:09   /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:83
15:40:09 
15:40:09   Error running command "curl -q 'http://172.17.0.2:8080/shell?shellCommand=ip+link+add+dummy1+type+dummy'": error executing remote command: error executing command in container: Error executing in Docker Container: 7
15:40:09   Expected error:
15:40:09       <*errors.errorString | 0xc8204ca400>: {
15:40:09           s: "error executing remote command: error executing command in container: Error executing in Docker Container: 7",
15:40:09       }
15:40:09       error executing remote command: error executing command in container: Error executing in Docker Container: 7
15:40:09   not to have occurred
15:40:09 
15:40:09   /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:149

**Comment by pwittrock** [comment]
@yujuhong Let me know if you are the right person to assign to

**Comment by yujuhong** [comment]
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24429/node-pull-build-e2e-test/2152

```
STEP: Creating a privileged pod
STEP: Executing privileged command on privileged container
STEP: Exec-ing into container over http. Running command: curl -q 'http://172.17.0.2:8080/shell?shellCommand=ip+link+add+dummy1+type+dummy'

------------------------------
â€¢ Failure [10.173 seconds]
PrivilegedPod
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:84
  should test privileged pod [It]
  /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:83

  Error running command "curl -q 'http://172.17.0.2:8080/shell?shellCommand=ip+link+add+dummy1+type+dummy'": error executing remote command: error executing command in container: Error executing in Docker Container: 7
  Expected error:
      <*errors.errorString | 0xc8204ca400>: {
          s: "error executing remote command: error executing command in container: Error executing in Docker Container: 7",
      }
      error executing remote command: error executing command in container: Error executing in Docker Container: 7
  not to have occurred

  /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:149
------------------------------
```

The error code is from `curl`: cURL Error (7): couldn't connect to host

/cc the original test author @ArtfulCoder

**Comment by ArtfulCoder** [comment]
test has been green for a while? 

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/15238/testReport/(root)/Kubernetes%20e2e%20suite/_k8s_io__PrivilegedPod_should_test_privileged_pod/history/

**Comment by yujuhong** [comment]
@ArtfulCoder this is a ported test in the node e2e suite. The ported test is functionally the same as the original test, with minor changes to for the node e2e test environment.

**Comment by ArtfulCoder** [comment]
Did it ever pass in the node e2e test env ?

**Comment by yujuhong** [comment]
Yes, node e2e runs per-PR builds, and this is just one failure/flake.

**Comment by yujuhong** [comment]
@ArtfulCoder: the suite: http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/
The test: https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/privileged_test.go

**Comment by yujuhong** [comment]
@ArtfulCoder would you mind taking a look?

**Comment by yujuhong** [comment]
This hasn't happened for a while and I'm not actively looking at it. Unassign myself for now.

**Comment by fejta** [comment]
Assigned to @ArtfulCoder per @yujuhong comment

**Comment by dchen1107** [comment]
Last 50 runs, there is no failure. I am closing it for now. Please re-open it if occured again.

**Comment by timstclair** [comment]
I just saw this again from the PR builder: https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/24771/node-pull-build-e2e-test/8199/build-log.txt

**Comment by yujuhong** [comment]
Let's close this one in favor of the automatically-filed issue #26297

**Comment by jingxu97** [comment]
I see the same error in this run 
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/27576/node-pull-build-e2e-test/10954/

**Comment by yujuhong** [comment]
Dup of #27498
