### ISSUE TITLE
Unit test flake: k8s.io/kubernetes/pkg/registry/configmap/etcd TestWatch flake

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#24507]
```
=== RUN   TestWatch
--- FAIL: TestWatch (27.02s)
	resttest.go:945: unexpected error: 105: Key already exists (/registry/configmaps/test/foo) [12]
FAIL
FAIL	k8s.io/kubernetes/pkg/registry/configmap/etcd	35.667s
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24504/kubernetes-pull-test-unit-integration/21925/

**Comment by lavalamp** [comment]
Left this running overnight, repro'd a different issue though...

**Comment by lavalamp** [comment]
Hm, never mind, it was just the 10 minute test timeout, sigh.

**Comment by goltermann** [comment]
closing - no hits since May 5
