### ISSUE TITLE
Build slowness from `go test -c`

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#24518]
A big part of a do-nothing build being slow is the calls to `go test -c` in `hack/lib/golang.sh` - about 28 of the 32 seconds it takes on my laptop.  This is a note to fix that.  If someone who knows the go tools well gets time - great way to make a lot of people happy :)

@madhusudancs @mikedanese

**Comment by mml** [comment]
@madhusudancs I can't tell from your PR.  Will it fix this?

**Comment by madhusudancs** [comment]
@mml sorry about that. Yes, my PR (#24850) fixes this issue.

**Comment by goltermann** [comment]
@madhusudancs can this be closed now?
