### ISSUE TITLE
Propose kubelet symlink in hyperkube image

### ISSUE THREAD

**Issue by pbx0** [kubernetes/kubernetes#24510]
I would like to propose adding a symlink `/kubelet` pointing to `/hyperkube` in the kubelet image. This is useful because it allows the hyperkube image to work as a drop in replacement for something that expects a kubelet image instead.

Our use case is with the kubelet-wrapper script we ship with CoreOS: https://github.com/coreos/coreos-overlay/blob/master/app-admin/kubelet-wrapper/files/kubelet-wrapper

The script runs the kubelet in a rkt container. It currently defaults to using our own hyperkube image release and we'd like people to be able to drop-in any upstream hyperkube builds as well. 

Also, there might be a question of why not add a symlink for all the components of hyperkube. I'm happy to update the PR to do that as well but it seems like on nodes in which those components are used, it is always fine to pull down the entire hyperkube image while worker nodes might just want to start pulling a more minimal kubelet image.

**Comment by HackToday** [comment]
It seems not a docker issue , just image requirements?

**Comment by mikedanese** [comment]
We should do this for all binaries linked into hyperkube

**Comment by thockin** [comment]
+1

even better would be if the components all were registered so you could
call hyperkube --make-symlinks and it would do all the work...

**Comment by pbx0** [comment]
@thockin I'll work on updating the PR to include a `hyperkube --make-symlinks` flag that just makes symlinks to hyperkube for each server in the current directory.  Does this sound OK?

**Comment by thockin** [comment]
If it is easy to do, that would be awesome

**Comment by luxas** [comment]
Great, now it's merged!
Thanks @pbx0

Closing as fixed
