### ISSUE TITLE
kubernetes-e2e-gce-flannel has not passed in two months

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#24520]
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-flannel/ and http://kubekins.dls.corp.google.com/ show that we run this job every few minutes, but it never passes.

I'm going to send out a PR to disable this job until someone has the time to investigate and resolve.

**Comment by bprashanth** [comment]
It's failing before tests even start: 
```
08:44:27 Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.2.397+f3f6ffaa283024", GitCommit:"f3f6ffaa283024977a04b921230c224198170e05", GitTreeState:"clean", BuildDate:"2016-04-20T14:22:52Z", GoVersion:"go1.6", Compiler:"gc", Platform:"linux/amd64"}
08:44:27 error: couldn't read version from server: Get http://localhost:8080/version: dial tcp [::1]:8080: getsockopt: connection refused
08:44:27 2016/04/20 08:44:27 e2e.go:200: Error running get status: exit status 1
08:44:27 2016/04/20 08:44:27 e2e.go:196: Step 'get status' finished in 67.646246ms
08:44:27 2016/04/20 08:44:27 e2e.go:194: Running: up
08:44:27 Project: kubernetes-flannel
```

**Comment by bprashanth** [comment]
At this point I don't think it's a flake, we needed flannel for a release and it's less important now so I'm not investigating why the cluster isn't coming up soon. I do believe if the cluster comes up a majority if not all of the tests will pass, and the ones that don't will flake for known reasons.
