### ISSUE TITLE
Jenkins GitHub Plugin hangs

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#24538]
>
Receiving objects:  93% (236874/254255), 149.66 MiB | 264 KiB/s   
Receiving objects:  93% (236943/254255), 149.96 MiB | 224 KiB/s   
Receiving objects:  93% (236943/254255), 150.09 MiB | 224 KiB/s   
Receiving objects:  93% (236943/254255), 150.31 MiB | 219 KiB/s   
Receiving objects:  93% (236943/254255), 150.57 MiB | 222 KiB/s   
Receiving objects:  93% (236943/254255), 150.76 MiB | 222 KiB/s   
Receiving objects:  93% (236943/254255), 151.01 MiB | 224 KiB/s   
Receiving objects:  93% (236943/254255), 151.28 MiB | 230 KiB/s   
Receiving objects:  93% (236943/254255), 151.57 MiB | 245 KiB/s   
Receiving objects:  93% (236943/254255), 151.86 MiB | 263 KiB/s   
Receiving objects:  93% (236943/254255), 152.13 MiB | 271 KiB/s   
Receiving objects:  93% (236944/254255), 152.39 MiB | 280 KiB/s   
Receiving objects:  93% (236944/254255), 152.62 MiB | 262 KiB/s   
Receiving objects:  93% (236944/254255), 152.91 MiB | 259 KiB/s   
Receiving objects:  93% (236944/254255), 153.21 MiB | 271 KiB/s   
Receiving objects:  93% (236944/254255), 153.52 MiB | 275 KiB/s   
Receiving objects:  93% (236944/254255), 153.67 MiB | 281 KiB/s   
Receiving objects:  93% (237075/254255), 153.80 MiB | 287 KiB/s   
09:02:29 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
09:02:29 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1463)
09:02:29 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
09:02:29 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
09:02:29 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:506)
09:02:29 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
09:02:29 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
09:02:29 	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
09:02:29 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
09:02:29 	at hudson.remoting.Request$2.run(Request.java:332)
09:02:29 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
09:02:29 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
09:02:29 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09:02:29 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
09:02:29 	at java.lang.Thread.run(Thread.java:745)
09:02:29 	at ......remote call to jenkins-builder-3(Native Method)
09:02:29 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
09:02:29 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
09:02:29 	at hudson.remoting.Channel.call(Channel.java:781)
09:02:29 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
09:02:29 	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
09:02:29 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:02:29 	at java.lang.reflect.Method.invoke(Method.java:606)
09:02:29 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
09:02:29 	at com.sun.proxy.$Proxy58.execute(Unknown Source)
09:02:29 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1057)
09:02:29 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
09:02:29 	at hudson.scm.SCM.checkout(SCM.java:485)
09:02:29 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
09:02:29 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
09:02:29 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
09:02:29 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
09:02:29 	at hudson.model.Run.execute(Run.java:1738)
09:02:29 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:02:29 	at hudson.model.ResourceController.execute(ResourceController.java:98)
09:02:29 	at hudson.model.Executor.run(Executor.java:410)
09:02:29 ERROR: null

[logs](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/1793)

**Comment by fejta** [comment]
@ixdy ever seen this before?

**Comment by ixdy** [comment]
Relevant line is
```
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/heads/*:refs/remotes/origin/*" returned status code 143:
```

Per quick google searching, 143 seems to mean "timed out". Not sure why the checkout took 10 minutes.

**Comment by fejta** [comment]
@spxtr any idea if we're hitting our disk quota?

**Comment by spxtr** [comment]
I don't think we're hitting disk quota, the Jenkins machine was well below its limit.

**Comment by fejta** [comment]
I'm going to consider this a github flake... although it seems a little perverse that we download over 150MB per job run...

**Comment by fejta** [comment]
http://kubekins.dls.corp.google.com/job/kubernetes-test-go/11173/console

**Comment by fejta** [comment]
@spxtr and @rmmh are looking to reduce the amount of github pulling we are doing.

**Comment by spxtr** [comment]
The easiest solution here is to not delete the `.git` folder before each build starts. Do your tests leave around artifacts? Would it be fine to just turn off workspace cleanup for that job?

**Comment by goltermann** [comment]
@fejta what's the latest on this one?  no updates in a month.

**Comment by fejta** [comment]
Please reopen this the next time you see it
