### ISSUE TITLE
Automatic issue triage

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#24555]
Our build cop looks at issues, attempts to categorize them, and labels them accordingly:
* support, bug, feature, etc.
* team/component

Labels don't appear as notifications, however, so people interested in a particular type of issue need to poll issues with that label.

Also, issues are often miscategorized.

This seems like a job for a machine.

We could have manually written pattern-matching or use machine learning (using old issues for training), but I'd like some means of automatic triage.

I suggest we start with kubectl, as a test case. If an issue mentions kubectl, we could:
* label the issue with component/kubectl and team/ux
* cc "@kubernetes/kubectl"

Lots of misc. bug reports contain kubectl commands, so it would be useful to think about how to filter those out.

Somewhat related: We should create an issue template #21437, which would facilitate some amount of user-supplied categorization.

cc @fejta

**Comment by grodrigues3** [comment]
The bot now automatically adds labels to the K8s repo.  [https://github.com/kubernetes/contrib/issues/1432](url)
