### ISSUE TITLE
Endpoints performance is O(n) in the number of IP:port pairs

### ISSUE THREAD

**Issue by matthiasr** [kubernetes/kubernetes#24552]
When stress-testing an unrelated component, I scaled up 5000 pods covered by the same service. The latency of the verb=PUT,resource=endpoint requests, as reported by kube-apiserver, went through the roof with a peculiar curve:

![grafana_-_k8s___overview](https://cloud.githubusercontent.com/assets/131590/14688384/dd29c61c-0731-11e6-96be-efb09d5bc015.png)

I think the problem is that Endpoint is one object containing a list of IP:port pairs. This list gets larger and larger, thus updating it takes much longer. This should also affect GET but at a much lower level.

The levelling off is the rate of additions going down because each endpoint addition takes longer. I think the behaviour here can be improved; I will file a separate issue for this.

As far as I can tell, this is inherent in the endpoint data structure.

Here is the etcd latency (again, as reported by kube-apiserver) for the same timeframe:

![grafana_-_k8s___overview](https://cloud.githubusercontent.com/assets/131590/14688497/61f20fc6-0732-11e6-96ee-9b5204b054f6.png)

relates to #10436

**Comment by matthiasr** [comment]
The cluster version is 1.2.0:

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
```

Of course, this is a highly artificial setup. With more realistic pod counts (hundreds) this is not a big issue.

**Comment by smarterclayton** [comment]
We may also be over allocating memory as well, the algo may be creating a lot of garbage since we do a set of transformations

**Comment by thockin** [comment]
We knew this was coming.  It would be great to get a profile or trace while
some of these operations were happening.

**Comment by ncdc** [comment]
cc @kubernetes/rh-scalability

**Comment by thockin** [comment]
@wojtek-t @gmarek FYI this is what I was mentioning earlier

**Comment by matthiasr** [comment]
It turns out this is more than a performance issue, once it crosses a certain threshold. I noticed that the endpoints list is stuck at

> 10.x.0.23:80,10.x.0.24:80,10.x.0.25:80 + 4021 more...

which doesn't add up to 5000. It stayed stuck at this even when scaling down to 5 pods (which in itself worked fine). The kube-controller-manager is spewing

> 2016-04-21_16:42:04.42376 E0421 16:42:04.423744   31869 endpoints_controller.go:426] Error updating endpoints: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint.
> 2016-04-21_16:42:05.15794 E0421 16:42:05.157922   31869 endpoints_controller.go:426] Error updating endpoints: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint.
> 2016-04-21_16:42:05.88528 E0421 16:42:05.885201   31869 endpoints_controller.go:426] Error updating endpoints: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint.

It looks to me like this is running into a timeout and failing to ever update again.

Collecting profiles now, @thockin will send them to you privately.

**Comment by matthiasr** [comment]
Here's the corresponding log output from kube-apiserver:

> 2016-04-21_17:32:10.90069 E0421 17:32:10.900629    8118 errors.go:63] apiserver received an error that is not an unversioned.Status: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint.
> 2016-04-21_17:32:10.90088 I0421 17:32:10.900862    8118 trace.go:57] Trace "Update /api/v1/namespaces/rocket/endpoints/rocket" (started 2016-04-21 17:32:10.281821835 +0000 GMT):
> 2016-04-21_17:32:10.90089 [14.144µs] [14.144µs] About to convert to expected version
> 2016-04-21_17:32:10.90090 [161.631µs] [147.487µs] Conversion done
> 2016-04-21_17:32:10.90090 [177.549µs] [15.918µs] About to store object in database
> 2016-04-21_17:32:10.90091 [618.98485ms] [618.807301ms] END
> 2016-04-21_17:32:10.90095 I0421 17:32:10.900934    8118 handlers.go:152] PUT /api/v1/namespaces/rocket/endpoints/rocket: (619.541864ms) 500
> 2016-04-21_17:32:10.90096 goroutine 15391668 [running]:
> 2016-04-21_17:32:10.90097 k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc224700930, 0x1f4)
> 2016-04-21_17:32:10.90098       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
> 2016-04-21_17:32:10.90098 k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc224700930, 0x1f4)
> 2016-04-21_17:32:10.90099       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
> 2016-04-21_17:32:10.90100 k8s.io/kubernetes/pkg/apiserver.(*baseTimeoutWriter).WriteHeader(0xc241a174e0, 0x1f4)
> 2016-04-21_17:32:10.90100       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:258 +0xba
> 2016-04-21_17:32:10.90101 k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc21a2c3ec0, 0x1f4)
> 2016-04-21_17:32:10.90102       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x53
> 2016-04-21_17:32:10.90103 k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x7f5881ab6938, 0xc20830a360, 0x0, 0x0, 0x1d49d60, 0x2, 0x7f5881895970, 0xc2082a1860, 0xc20ef40b60, 0x1f4, ...)
> 2016-04-21_17:32:10.90104       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:429 +0x174
> 2016-04-21_17:32:10.90105 k8s.io/kubernetes/pkg/apiserver.errorNegotiated(0x7f5881aa9080, 0xc2080332e0, 0x7f5881ab6938, 0xc20830a360, 0x0, 0x0, 0x1d49d60, 0x2, 0x7f5881895970, 0xc2082a1860, ...)
> 2016-04-21_17:32:10.90105       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:441 +0xdd
> 2016-04-21_17:32:10.90106 k8s.io/kubernetes/pkg/apiserver.(*RequestScope).err(0xc2084ce5b0, 0x7f5881aa9080, 0xc2080332e0, 0x7f5881895970, 0xc2082a1860, 0xc20ef40b60)
> 2016-04-21_17:32:10.90107       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:84 +0x11f
> 2016-04-21_17:32:10.90107 k8s.io/kubernetes/pkg/apiserver.func·034(0xc21a2c3e30, 0xc21523d740)
> 2016-04-21_17:32:10.90108       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:685 +0x13f9
> 2016-04-21_17:32:10.90109 k8s.io/kubernetes/pkg/apiserver/metrics.func·001(0xc21a2c3e30, 0xc21523d740)
> 2016-04-21_17:32:10.90110       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x269
> 2016-04-21_17:32:10.90111 github.com/emicklei/go-restful.(*Container).dispatch(0xc20818e360, 0x7f5881895850, 0x [[kube-controller-manager/v1.2.0 (linux/amd64) kubernetes/5cb86ee/endpoint-controller] 10.33.33.57:45980]

**Comment by timothysc** [comment]
This is data model problem, on a narrow use case.  We've seen this for a while but it's never popped to the top of the list

/cc @gmarek @kubernetes/sig-scalability

**Comment by matthiasr** [comment]
Just to be clear, this is also not a blocker for us.

To recover from this, I now used `kubectl delete endpoints` on the offending object. The controller-manager recreated it again with the correct set of IP:port pairs within seconds.

**Comment by smarterclayton** [comment]
This may be because the object is too large to store in etcd (near the 1M
limit).

**Comment by gmarek** [comment]
@xiang90 @hongchaodeng

**Comment by xiang90** [comment]
@smarterclayton My best guess is that the object contains too many sub-objects and encoding/decoding starts to slow everything down. For the 1mb limit in etcd, it should not really slow anything down from the io latency perspective.

**Comment by matthiasr** [comment]
@smarterclayton it maxed out at 707831 bytes, well below 1MiB

**Comment by smarterclayton** [comment]
That's the etcd key size or API response size?

**Comment by matthiasr** [comment]
This is the size of the object I `etcdctl get`

**Comment by smarterclayton** [comment]
Ok

**Comment by thockin** [comment]
Ref #8190

**Comment by aojea** [comment]
@robscott @thockin do you think this was solved by endpoint slices?

**Comment by robscott** [comment]
Thanks for catching this! I've tested EndpointSlices with Services backed by 50,000 pods and performance has seemed relatively reasonable, definitely much improved over anything that Endpoints could offer. Unfortunately this will not be completely solved until nothing relies on Endpoints and end users could safely disable the Endpoints controller. I do think this is likely solved enough to close at this point, but feel free to reopen if I've missed anything.

/close
