### ISSUE TITLE
Cassandra on Kubernetes - javadocs and unit tests

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#24550]
Custom [SeedProvider ](https://github.com/kubernetes/kubernetes/blob/master/examples/cassandra/java/src/io/k8s/cassandra/KubernetesSeedProvider.java) needs some TLC.

1. Javadocs in code
2. Junit unit test
3. Look at refactor for only getting a few seeds

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kubernetes/pull/24885 is a good start!

**Comment by chrislovecnm** [comment]
Fixed in Head
