### ISSUE TITLE
kube-controller-manager should batch Endpoint updates

### ISSUE THREAD

**Issue by matthiasr** [kubernetes/kubernetes#24553]
As laid out in #24552, updating the Endpoint object is O(n) in the number of pods covered by the corresponding service.

Additionally, as far as I can tell, kube-controller-manager adds IP:port pairs to the Endpoint list one by one, leading to the curve observed there. Since there are n updates, overall updating the endpoint list for a service is O(n^2) in the number of pods.

By the time the first few hundred endpoints are added, all the pods have become available, and kube-controller-manager could just add them all at once, bringing the time to converge back to O(n) and finish within an acceptable time (#10436).

**Comment by matthiasr** [comment]
The cluster version is 1.2.0:

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
```

Of course, this is a highly artificial setup. With more realistic pod counts (hundreds) this is not a big issue.

**Comment by thockin** [comment]
I like the idea of batching the updates.  Good project for someone if
community - not too hard and reasonably approachable.

**Comment by rikatz** [comment]
Should we keep this open with EndpointSlices also going on?

**Comment by aojea** [comment]
> Should we keep this open with EndpointSlices also going on?

ping @robscott  ;)

**Comment by robscott** [comment]
I do think EndpointSlices have largely solved this issue, though unfortunately the load on controller manager due to the Endpoints controller won't go away until we start significantly limiting the size of Endpoints or have sufficient enough adoption of EndpointSlices that it would be possible to disable the Endpoints controller in some clusters. For now though, I'm open to closing this issue if it helps clear up the backlog.

**Comment by matthiasr** [comment]
What I was originally thinking about is sort of independent of endpoint slices. I would not be surprised if this has actually been done in the meantime and just wasn't linked back to this issue.

Consider a large and fast cluster. A reasonable number, say, 100 pods, become ready roughly at the same time. The behavior I observed back then was that this would cause 100 separate updates to the Endpoints; the same could happen with EndpointSlices.

The better behavior would be to observe that 100 pods are ready and write the Endpoint(Slice)s only once or twice. I haven't had an opportunity to retest this. I think it is entirely plausible that this already happened as a side effect of some controller framework conversion.

**Comment by robscott** [comment]
Thanks for the clarification @matthiasr! That makes a lot of sense. Most controllers now, including both the Endpoints and EndpointSlice controllers use queuing to process updates. In the case of these controllers, a change to anything related to a Service drops that Service into the queue if it's not already there. Then a syncService() call reconciles all the Pods matching a Service and translates them to Endpoints or EndpointSlices. In my scale testing I've observed endpoints being added in batches of ~100 per cycle at sufficient scale, but that all depends on how much is in the queue at a given time and how long each syncService() call takes. It sounds like this does solve the original problem, so I'll go ahead and close the issue. Thanks for filing the issue and following up!

/close
