### ISSUE TITLE
kubelet may start syncing pods before syncing network status (i.e., get pod CIDR)

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#24558]
This is based on what @freehan observed in his cluster.

`syncNetworkStatus` calls `kl.runtimeState.setNetworkState()` to set an error if anything fails (i.e., no pod CIDR). However, [kubelet runs `syncNetworkStatus` in a goroutine](https://github.com/kubernetes/kubernetes/blob/bf69b2a8629b0ba35b5d9986a808477eb069d2a4/pkg/kubelet/kubelet.go#L1028). This means that kubelet could start syncing the pods before `syncNetworkStatus` runs once. The creation of the infra containers will continuously fail until pod CIDR is properly set.

@vishh, correct me if I'm wrong, I don't think this is the intended behavior, and kubelet should block until the method is run once.

**Comment by vishh** [comment]
In the past, networking used to be setup synchronously and kubelet used a
container runtime health check as a barrier in the initialization path.

**Comment by yujuhong** [comment]
There are a few paths to update pod CIDR in the runtimeState, which are quite confusing. It seems to be that it's possible that kubelet will move on to the sync loop when pod CIDR is an empty string.

**Comment by bprashanth** [comment]
Won't the syncLoop hang on errors() and you always start with an error?

**Comment by yujuhong** [comment]
> you always start with an error?

I don't think that's true.

**Comment by bprashanth** [comment]
Maybe we're not actually hitting this? 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/runtime.go#L96

**Comment by yujuhong** [comment]
> Maybe we're not actually hitting this? 
> https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/runtime.go#L96

Then the problem could be that kubenet did not synchronously sets the CIDR. Anyway, closing this issue until we have further information.
