### ISSUE TITLE
rktnetes - e2e/dns test failures

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#24563]
The DNS tests fail on our rktnetes e2e right now for two reasons:

1) `metadata` not resolving due to `google.internal` not in the host's search path - On the CoreOS alpha image we're running on, the dhcp search domains we receive are not populated on the host, so they similarly don't end up in the container. When they're on the host this part of the test passes.

Resolution: It's very likely a near-future CoreOS alpha release will resolve this issue. This is really a CoreOS bug, not a rktnetes one. Alternate resolutions include a cloud-init that uses `dhcpcd` over systemd-resolved`.

2) Pod DNS not resolving due to `hostname -i` not working in rkt - This is pretty much exactly https://github.com/coreos/rkt/issues/2223

Resolution: If the above rkt issue is not fixed, the test can be altered to work (`hostname -i` is a detail, not part of what needs to be tested). The following diff works for that:

```
-       probeCmd += fmt.Sprintf(`podARec=$$(hostname -i| awk -F. '{print $$1"-"$$2"-"$$3"-"$$4".%s.pod.cluster.local"}');`, namespace)
+       probeCmd += fmt.Sprintf(`podARec=$$(ip -4 -o addr show dev eth0 | grep -Eo "([0-9]{1,3}\.){3}[0-9]{1,3}"| awk -F. '{print $$1"-"$$2"-"$$3"-"$$4".%s.pod.cluster.local"}');`, namespace)
```

It's preferable to fix the rkt issue however since it's possible users will also expect the hostname to resolve correctly in applications.

Making the two changes above (dhcpcd + that patch) caused the tests to pass on rktnetes for me.

**Comment by sjpotter** [comment]
Re #2 in docker/kubernetes the /etc/hosts file is managed by k8s.  We fail that test and have been ignoring it as of course our version isny managed by the current code path.  Perhaps we need to say no we have to be compatible with it, perhaps even abstracting/sharing the current code to generate the/etc/hosts file that we mount/copy into the file system?

**Comment by yifan-gu** [comment]
@euank What's the test name of the 1st test? Is the pod using the host's /etc/hosts?

**Comment by euank** [comment]
Test "should provide DNS for the cluster" (really anything in `e2e/dns.go` I believe, but that's a good example one). Although I'm talking about two failures, they're both in the same test as that test fails in both of those ways at once.

The host's `/etc/hosts` file is not used and that wouldn't help, since the missing entry is `$podIP    $podHostname` (the docker & kubelet+docker behavior).

**Comment by euank** [comment]
We now have the `/etc/hosts` file populated correctly, however the tests still fail because CoreOS instances on GCE do not correctly populate all dns search strings. This is due to https://github.com/systemd/systemd/issues/2710

I believe that the best resolution here is to do one of the following (in order of preference):

1) Modify the kube-up scripts for GCE + CoreOS to add a file in `/etc/systemd/network/10-domains.network` that contains `Domains=google.internal`.
2) Modify the test to not test for the search domain under CoreOS
3) Modify kube-up for GCE to use dhcpcd instead of systemd-resolved

In any cases, we should link back to this issue and note that this workaround should only be needed for coreos versions where the above systemd issue is present.

**Comment by yifan-gu** [comment]
@euank Please document this workaround for 1.3

**Comment by euank** [comment]
Closing this as stale; rktnetes has transitioned to [rktlet](https://github.com/kubernetes-incubator/rktlet/), if this failure is relevant there it should be filed there

/close
