### ISSUE TITLE
Represent API "enums" in swagger

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#24562]
Currently they are just strings. 

Example: pod restart policy.

**Comment by nikhiljindal** [comment]
Would be great if we can figure out a way to represent valid values and use that in swagger schema validation. 
Right now, we put valid values in comments and dont validate them in swagger schema validation.

**Comment by nikhiljindal** [comment]
http://stackoverflow.com/a/27606822 explains how we can represent enums in 2.0 swagger spec.

**Comment by nikhiljindal** [comment]
1.2 spec supports representing enums as well: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md#433-data-type-fields

**Comment by bgrant0607** [comment]
See also #2971

**Comment by stuart-warren** [comment]
Do we just need to add more struct tags?

https://github.com/emicklei/go-restful-openapi/blob/fcb3b5066076d24834269f956e1ab68496f69a49/property_ext_test.go#L14

**Comment by garethr** [comment]
Just a note that exposing this information in the schema rather than the comment would be most useful for tools consuming that schema. For instance see this issue against kubeval https://github.com/garethr/kubeval/issues/18 which would be fixed with the addition of enums.
