### ISSUE TITLE
.dockercfg problems

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#2456]
* Probable multi-threading bug: https://github.com/GoogleCloudPlatform/kubernetes/blob/f0f4092fc54b19dc3828e97307c11b7f1b7e8d86/pkg/kubelet/runonce.go#L56
* .dockercfg appears to get read only on startup; we should poll it or detect when it changes
* No positive confirmation that .dockercfg was read shows up in the kubelet log
* never called and should be deleted: https://github.com/GoogleCloudPlatform/kubernetes/blob/d9426f8848883033e771ba1e28f86f624612b0f5/pkg/kubelet/dockertools/config.go#L36

**Comment by bgrant0607** [comment]
Is this still relevant?

**Comment by erictune** [comment]
seems obsolete
