### ISSUE TITLE
AWS EBS mkfs and mount failures are difficult to debug

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#24568]
I helped a user troubleshoot an issue with EBS volumes not being formatted correctly today and found that there is almost no logging to help determine what happened when mkfs or mount fails.  In my particular case, it's not even clear whether `mkfs` was ever run.  So, we should:

1.  Ensure that the shared `SafeFormatAndMount` code has appropriate logging
2.  Ensure that the EBS volume code has appropriate logging

**Comment by screeley44** [comment]
@pmorie - I can look into this, can the user or you supply any other steps or notes on how to reproduce... thanks!

**Comment by screeley44** [comment]
seems the mkfs for xfs might be squashed - referencing BZ here  https://bugzilla.redhat.com/show_bug.cgi?id=1329370

will continue to focus on adding better logging for the identified areas above
