### ISSUE TITLE
Fix cluster-wide constraint validation

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#2457]
https://github.com/GoogleCloudPlatform/kubernetes/pull/2094 introduced into a validation method a cluster wide constraint check. This needs to be moved to registry.go or rest.go. Validation cannot even in theory do this check properly, it's inherently racy. Also IMO validation should not have external dependencies (like a lister); things that require global constraints be satisfied are not good candidates for validation checks, and should be checked at admission time, or write-to-etcd-time.

**Comment by smarterclayton** [comment]
Since we have no concrete use case or plan to implement cluster wide constraints, keeping this open seems unnecessary.  Controllers, initializers, and admission control all provide ways of enforcing global checks.
