### ISSUE TITLE
upgrade to 1.2.2 etcd TLS issues

### ISSUE THREAD

**Issue by streamnsight** [kubernetes/kubernetes#24578]
reported here and on slack.

http://stackoverflow.com/questions/36758328/kubernetes-1-2-2-api-server-fails-cant-find-mounted-certs-for-tls-on-etcd

I'm been struggling to get `api-server 1.2.2` to run with **etcd** secured with **TLS**.

I am upgrading from `1.1.2` to `1.2.2`

In 1.1.2 I was using the `--etcd-config` flag and had a file that looked like:

```
{
  "cluster": {
    "machines": [
      "https://XXX.XXX.XXX.XXX:2379",
      "https://XXX.XXX.XXX.XXY:2379",
      "https://XXX.XXX.XXX.XXZ:2379"
    ]
  },
  "config": {
    "certFile": "/etc/ssl/etcd/etcd-peer.cert.pem",
    "keyFile": "/etc/ssl/etcd/private/etcd-peer.key.pem",
    "caCertFiles": [
      "/etc/ssl/etcd/ca-chain.cert.pem"
    ],
    "consistency": "STRONG_CONSISTENCY"
  }
}

```

now this is no longer supported and I switched to using the flags:

```
--etcd-cafile="/etc/ssl/etcd/ca-chain.cert.pem"
--etcd-certfile="/etc/ssl/etcd/etcd-peer.cert.pem"
--etcd-keyfile="/etc/ssl/etcd/private/etcd-peer.key.pem"    
--etcd-servers="https://XXX.XXX.XXX.XXX:2379, https://XXX.XXX.XXX.XXY:2379,https://XXX.XXX.XXX.XXZ:2379"

```

now I am getting this error:

`F0421 00:54:40.133777       1 server.go:291] Invalid storage version or misconfigured etcd: open "/etc/ssl/etcd/etcd-peer.cert.pem": no such file or directory`

So, it seems like it cannot find the cert file. The file paths and names are the same as before, and they are mounted with hostPath the exact same way as with v1.1.2, so I don't understand why api-server would not not find them.

I have been trying to figure what is going on with the file paths by simply switching the command in the pod from

```
- /hyperkube
- api-server
...
```

to

```
- /bin/sleep
- 60
```

but kubelet won't start this pod for some reason I don't understand.

Does it have to do with the yaml file name or something?

I don't understand what is happening why kubelet won't run with this command.
I don't know why my cert files are not found and without being able to get inside the container with the mounts it is difficutl to troubleshoot.

thanks for help.

**Comment by streamnsight** [comment]
So i made a little progress in the sense I managed to get into the container, by making it run the scheduler instead of the apiserver

So I can now get inside the container and was able to cat the files apiserver is complaining about

So i don't understand the problem: either the error is not reporting the actual problem, or there is some other issue with this TLS setup

**Comment by wojtek-t** [comment]
@xiang90 @hongchaodeng

**Comment by liggitt** [comment]
are you passing these flags in a shell script or in a container command array? If it is in a container command array, I think you need to omit the quotes around the filenames

**Comment by streamnsight** [comment]
@liggitt  good point! will try this. Thanks

**Comment by streamnsight** [comment]
@liggitt that did it... 
what a stupid way to waste 2 days!
