### ISSUE TITLE
Unable to launch container, error complaining about SHM size must be greater than 0

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#24588]
I am getting errors like the following:

```
$ cluster/kubectl.sh describe pods
Name:		nginx-2040093540-0ietl
Namespace:	default
Node:		127.0.0.1/127.0.0.1
Start Time:	Thu, 21 Apr 2016 02:10:40 -0400
Labels:		pod-template-hash=2040093540,run=nginx
Status:		Pending
IP:		
Controllers:	ReplicaSet/nginx-2040093540
Containers:
  nginx:
    Container ID:	
    Image:		nginx
    Image ID:		
    Port:		
    QoS Tier:
      cpu:			BestEffort
      memory:			BestEffort
    State:			Waiting
      Reason:			ContainerCreating
    Ready:			False
    Restart Count:		0
    Environment Variables:	<none>
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  default-token-h7ms3:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-h7ms3
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  48s		48s		1	{default-scheduler }			Warning		FailedScheduling	no nodes available to schedule pods
  47s		47s		1	{default-scheduler }			Normal		Scheduled		Successfully assigned nginx-2040093540-0ietl to 127.0.0.1
  44s		8s		4	{kubelet 127.0.0.1}			Warning		FailedSync		Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: Error response from daemon: SHM size must be greater then 0"
```

I am running the following:

```
$ uname -r
4.4.7-300.fc23.x86_64$ 
$ docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-9.gitee06d03.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      ee06d03/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-9.gitee06d03.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      ee06d03/1.9.1
 Built:           
 OS/Arch:         linux/amd64
```

Are we now required to set a `ShmSize` moving forward now that we have switched to the docker engine API?  I was able to work around it on my system by supplying `ShmSize` like the following:

```
	hc := &dockercontainer.HostConfig{
		Binds:          binds,
		NetworkMode:    dockercontainer.NetworkMode(netMode),
		IpcMode:        dockercontainer.IpcMode(ipcMode),
		UTSMode:        dockercontainer.UTSMode(utsMode),
		PidMode:        dockercontainer.PidMode(pidMode),
		ReadonlyRootfs: readOnlyRootFilesystem(container),
		Resources: dockercontainer.Resources{
			Memory:     memoryLimit,
			MemorySwap: -1,
			CPUShares:  cpuShares,
		},
		ShmSize:     1024 * 1024 * 64,
		SecurityOpt: securityOpts,
	}
```

which I think is consistent with what docker CLI is doing by default.

/cc @kubernetes/sig-node @vishh @Random-Liu @mrunalp @kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
Since this blocks my ability to launch containers, bump to p0.  See associated PR that sets ShmSize to match what docker CLI does by default.  We could probably get fancier with ShmSize in future.

**Comment by Random-Liu** [comment]
@derekwaynecarr `ShmSize` is added after docker 1.9+, and is documented in docker 1.10.
As is documented:
```
ShmSize - Size of /dev/shm in bytes. The size must be greater than 0. If omitted the system uses 64MB.
```
Go-dockerclient doesn't have this issue because it doesn't even support it see [https://github.com/fsouza/go-dockerclient/blob/master/container.go#L599-L645], so the filed is omitted when json encoding.

While the engine-api supports it now see [https://github.com/docker/engine-api/blob/master/types/container/host_config.go#L292], and the field is not omitted even when it is empty (0), which causes this error.

**Comment by Random-Liu** [comment]
@derekwaynecarr 
In our ContainerVM, we are using the earliest docker 1.9.1:
https://github.com/docker/docker/commit/a34a1d5

While the `ShmSize` PR gets in after that:
https://github.com/docker/docker/pull/16168

The version you are using quite new:
https://github.com/docker/docker/commit/ee06d03

When I validated docker 1.10, we were still using go-dockerclient, which doesn't have this problem (see https://github.com/kubernetes/kubernetes/issues/24588#issuecomment-212784346).

**Comment by ncdc** [comment]
We have a new Fedora Docker RPM pending to fix this.

**Comment by derekwaynecarr** [comment]
@Random-Liu - I am fine with option 1, I will update this PR.

**Comment by derekwaynecarr** [comment]
Per discussion this morning with @eparis and @ncdc , I am not a fan of hidden default flags that have a history of breaking us.  As a result, I would like kube to set an explicit default `ShmSize` using the option 1 proposed by @Random-Liu and I wonder if we should look to expose `ShmSize` as a per container option in the future.

**Comment by Random-Liu** [comment]
It seems that docker doesn't support ShmSize of 0 after https://github.com/anusha-ragunathan/docker/commit/ef1d410b0270fa7309d76aded34113396def7fb2, but change to support that after https://github.com/docker/docker/commit/5190794f1d85d5406611eb69c270df62ac1cdc7f.

There is no public docker release between them, so this should not happen in any docker released version.  Maybe we don't need to care about it too much for now. :)
