### ISSUE TITLE
NodeController shouldn't evict Pods when all Nodes are NotReady

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24597]
cc @davidopp @lavalamp @mml @roberthbailey @cjcullen @fgrzadkowski

**Comment by lavalamp** [comment]
This is like a (very) rough approximation of the rule "don't evict things that have no place to go". It's obviously super complicated to implement that rule completely, but there's some obvious conditions that we can catch, like this one.

(The motivation here is to avoid having node controller do a bunch of evictions when it and apiserver are segmented from the nodes.)

**Comment by davidopp** [comment]
@gmarek Is there some reason you didn't assign this to yourself?

Also, I assume you're going to integrate this into #20979 ?

**Comment by gmarek** [comment]
No reason, except that I'm not going to start working on it for next few weeks. If someone wants to jump in, I don't want to discourage her/him.

I'd rather keep it separate from #20979 - those are orthogonal changes.

**Comment by davidopp** [comment]
@gmarek Will you be able to do this for 1.3, or should we reassign?

**Comment by gmarek** [comment]
Depends on the priority.

**Comment by davidopp** [comment]
To clarify -- this issue is a P0 release blocker for 1.3, because it has caused at least one user to lose data.

**Comment by roberthbailey** [comment]
Looks like this was fixed by https://github.com/kubernetes/kubernetes/pull/25571.
