### ISSUE TITLE
Kubectl drain doesn't know about ReplicaSets

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#24592]
Kubectl won't automatically delete Pods managed by a ReplicaSet only ReplicationController, Job, or DaemonSet.

**Comment by zhouhaibing089** [comment]
Are you using the HEAD code? It should be handled in this commit: https://github.com/kubernetes/kubernetes/commit/fdf409861ace0ebab0786d509321bfce4a75f98d

**Comment by hanikesn** [comment]
Using 1.2.2. So I will close this.
