### ISSUE TITLE
Remove support for golang 1.4

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#24599]
The `etcd` client code now makes has a dependency on the golang 1.5 http API (the `Cancel` call), so we should remove support for go 1.4.

**Comment by ncdc** [comment]
RHEL 7 doesn't have go > 1.4 yet. It's coming (I don't remember the ETA off-hand). But we need to take this into consideration.

cc @eparis @smarterclayton

**Comment by eparis** [comment]
It is available internally, but that is stinky. Maybe we can get him to push it to CentOS....

**Comment by ixdy** [comment]
cc @spxtr @krousey

**Comment by pmorie** [comment]
> It is available internally, but that is stinky. Maybe we can get him to push it to CentOS....

Bleh

**Comment by wojtek-t** [comment]
@lavalamp 
In the past we had a policy of supporting previous go version (for rollback policy). Did we already drop it?

**Comment by lavalamp** [comment]
We haven't made a group decision to drop that policy, but it was only ever an artifact of history and I think in this case I'd advocate for dropping 1.4 support asap.

**Comment by wojtek-t** [comment]
I also vote for dropping 1.4 support - just was ensuring if it isn't against some policy.

**Comment by rootfs** [comment]
I just hit the missing `Cancel` call in `http.Request` on RHEL 7.2. but there is no golang 1.5 or higher on RHEL 7.2 yet....

**Comment by spxtr** [comment]
I believe we can close this.
