### ISSUE TITLE
Give .Admit the original object on Update

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#24596]
Admission choices for updates often need access to the original object in order to compute a diff.  The current structure of the code makes this difficult/non-obvious.

A similar decision is logically required for "protected" objects on a delete.

@derekwaynecarr @kubernetes/rh-cluster-infra is there an existing issue/design for making this work?

**Comment by derekwaynecarr** [comment]
@deads2k - i had been looking the original object up on update where the admission controller required it.  do enough controllers have this requirement on update to see the previous object to make it global?

**Comment by deads2k** [comment]
> @deads2k - i had been looking the original object up on update where the admission controller required it. do enough controllers have this requirement on update to see the previous object to make it global?

I want to do it to allow authorization to make a decision based on the labels of an original object.  The lookup is "mostly" right, but not perfectly right.

**Comment by derekwaynecarr** [comment]
This is now supported per https://github.com/kubernetes/kubernetes/pull/25787
