### ISSUE TITLE
Flickering routes on GCE when registering with FQDN

### ISSUE THREAD

**Issue by cvle** [kubernetes/kubernetes#24590]
Hi! 

I was manually deploying with CoreOS on GCE.
The default hostname recognized by CoreOS is a FQDN, thus the nodes where registered
with FQDN. Kubernetes didn't complain about this. There were no error logs. The kube-controller-manager was creating and destroying routes every second. Correcting the hostname fixed the problem.

If this is a GCE only problem, the gce cloud provider, should at least check and complain about wrong hostnames in the logs.

This would save a lot of time for others running into the same problem.

**Comment by wikiwi** [comment]
Here are the logs produced by the kube-controller-manager:

    routecontroller.go:94] Creating route for node k8s-master.c.mesa-1287.internal 10.244.0.0/24 with hint eaea3301-0781-11e6-8649-42010a8c0002
    routecontroller.go:112] Deleting route k8s-eaea3301-0781-11e6-8649-42010a8c0002 10.244.0.0/24
    routecontroller.go:97] Could not create route eaea3301-0781-11e6-8649-42010a8c0002 10.244.0.0/24 for node k8s-master.c.mesa-1287.internal after 557.118824ms: googleapi: Error 409: The resource 'projects/mesa-1287/global/routes/k8s-eaea3301-0781-11e6-8649-42010a8c0002' already exists, alreadyExists
    routecontroller.go:117] Deleted route k8s-eaea3301-0781-11e6-8649-42010a8c0002 10.244.0.0/24 after 18.805178035s
    routecontroller.go:94] Creating route for node k8s-master.c.mesa-1287.internal 10.244.0.0/24 with hint eaea3301-0781-11e6-8649-42010a8c0002
    routecontroller.go:99] Created route for node k8s-master.c.mesa-1287.internal 10.244.0.0/24 with hint eaea3301-0781-11e6-8649-42010a8c0002 after 22.150191743s`

**Comment by caseydavenport** [comment]
@cvle I think I'm also hitting this issue on a GCE CoreOS cluster.

Could you clarify what you meant by "Correcting the hostname fixed the problem"?

**Comment by cvle** [comment]
Sorry to reply this late, I somehow missed the notification for this. 
As far as I remember the default hostname in CoreOS was set to the full FQDN e.g.
`k8s-master.c.mesa-1287.internal`, but kubernetes expects only the hostname which in this case would be `k8s-master`.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gce
since we lack a sig-gcp at the moment
