### ISSUE TITLE
Reduce build times by not compiling protobuf / codecgen for certain platforms

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#24608]
Client performance for non linux/amd64 platforms is unlikely to be important enough that we should compile protobuf and codecgen for those platforms.  I suspect conditionally disabling those everything except a few would dramatically cut compile times and speed up builds and the merge queue

@kubernetes/sig-api-machinery @kubernetes/sig-testing

**Comment by luxas** [comment]
cc @luxas 

Will this affect any features for platforms that get this disabled?

**Comment by smarterclayton** [comment]
We should separate server platforms from clients, and internal clients from external clients.  Internal server platforms and clients want protobuf.  External, high traffic clients should have the jsoncodec gen.  Internal server clients probably should preserve jsoncodec for now.  All others probably don't need either, or if they do, the want it selectively.

**Comment by luxas** [comment]
@smarterclayton is this relevant anymore?
