### ISSUE TITLE
e2e_node/privileged_test Failed waiting for pod to become running

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#24605]
[logs](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/1855)

>
09:28:38 • Failure [65.098 seconds]
09:28:38 PrivilegedPod
09:28:38 /var/lib/jenkins/workspace/kubelet-gce-e2e-ci/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:83
09:28:38   should test privileged pod [It]
09:28:38   /var/lib/jenkins/workspace/kubelet-gce-e2e-ci/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:82
09:28:38 
09:28:38   Failed waiting for pod "privileged-pods/privileged-pod" to become running: Time out while waiting for pod privileged-pods/privileged-pod to become running; current status: {Phase:Pending Conditions:[{Type:Ready Status:False LastProbeTime:{Time:0001-01-01 00:00:00 +0000 UTC} LastTransitionTime:{Time:2016-04-21 16:26:58 +0000 UTC} Reason:ContainersNotReady Message:containers with unready status: [privileged-container not-privileged-container]}] Message: Reason: HostIP:10.240.0.31 PodIP: StartTime:2016-04-21T16:26:58Z ContainerStatuses:[{Name:not-privileged-container State:{Waiting:0xc8205488e0 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/netexec:1.4 ImageID: ContainerID:} {Name:privileged-container State:{Waiting:0xc820548960 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/netexec:1.4 ImageID: ContainerID:}]}
09:28:38   Expected error:
09:28:38       <*errors.errorString | 0xc820550160>: {
09:28:38           s: "Time out while waiting for pod privileged-pods/privileged-pod to become running; current status: {Phase:Pending Conditions:[{Type:Ready Status:False LastProbeTime:{Time:0001-01-01 00:00:00 +0000 UTC} LastTransitionTime:{Time:2016-04-21 16:26:58 +0000 UTC} Reason:ContainersNotReady Message:containers with unready status: [privileged-container not-privileged-container]}] Message: Reason: HostIP:10.240.0.31 PodIP: StartTime:2016-04-21T16:26:58Z ContainerStatuses:[{Name:not-privileged-container State:{Waiting:0xc8205488e0 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/netexec:1.4 ImageID: ContainerID:} {Name:privileged-container State:{Waiting:0xc820548960 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/netexec:1.4 ImageID: ContainerID:}]}",
09:28:38       }
09:28:38       Time out while waiting for pod privileged-pods/privileged-pod to become running; current status: {Phase:Pending Conditions:[{Type:Ready Status:False LastProbeTime:{Time:0001-01-01 00:00:00 +0000 UTC} LastTransitionTime:{Time:2016-04-21 16:26:58 +0000 UTC} Reason:ContainersNotReady Message:containers with unready status: [privileged-container not-privileged-container]}] Message: Reason: HostIP:10.240.0.31 PodIP: StartTime:2016-04-21T16:26:58Z ContainerStatuses:[{Name:not-privileged-container State:{Waiting:0xc8205488e0 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/netexec:1.4 ImageID: ContainerID:} {Name:privileged-container State:{Waiting:0xc820548960 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:gcr.io/google_containers/netexec:1.4 ImageID: ContainerID:}]}
09:28:38   not to have occurred
09:28:38 
09:28:38   /var/lib/jenkins/workspace/kubelet-gce-e2e-ci/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:210

**Comment by Random-Liu** [comment]
https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/25326/node-pull-build-e2e-test/4985/build-log.txt

**Comment by dchen1107** [comment]
For last 50 runs, the test never failed. Close this as obsolete now.
