### ISSUE TITLE
Add a `shellcheck` based pre-submit

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#24614]
[shellcheck](https://github.com/koalaman/shellcheck) is a bash script linter which could help catch common problems in our (numerous) bash scripts. I know we'd like to reduce our use of bash scripts, but until then I think being stricter about script quality would be helpful.

/cc @zmerlynn

**Comment by spxtr** [comment]
cc @krousey you were talking about this earlier.

It has to only check modified lines.

**Comment by krousey** [comment]
False positives are a problem. For instance, not being able to follow a `source` call through an environment variable causes an error.

I would be much more comfortable with a non-blocking way to point out these issues, and leave to it human judgement.

**Comment by zmerlynn** [comment]
Yeah, I've been interested in doing this for a while, but `shellcheck` can be pretty persnickety and I haven't yet taken the time to configure it to be less noisy (or figure out if it can be). It's good, though.

**Comment by timstclair** [comment]
Yeah, it would definitely need to be configured to ignore a lot of types of errors, but I still think it could be used to check for some types of errors. We could start with a pretty minimal set.

**Comment by krousey** [comment]
I would settle for something that just produced a quick-fix format artifact in the GCS bucket, and then the PR munger reading from it and commenting on the PR. We could re-use that for other linters too.

**Comment by goltermann** [comment]
https://goreportcard.com/report/k8s.io/kubernetes#misspell has been pretty accurate historically.

**Comment by krousey** [comment]
@goltermann shellcheck, not spellcheck

**Comment by goltermann** [comment]
reading too many issues in a row...carry on

**Comment by spiffxp** [comment]
/sig testing
/priority awaiting-more-evidence
Might be more noise than it's worth, but we do pylint our .py scripts now

**Comment by BenTheElder** [comment]
We also have non-blocking and optionally-run presubmits, even just having an easy way for reviewers to request a shellcheck result for changed files seems like something we should do.

I also think we should fix the existing failures. Glancing through some k/k bash with shellcheck in my editor, these generally seem to be things that are actually wrong.

**Comment by BenTheElder** [comment]
This is done now. Only took two years :^)
