### ISSUE TITLE
Seccomp umbrella issue

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#24611]
Umbrella issue for seccomp support

Original issue: #20870 

Alpha implementation (1.3):

- [x] [Proposal](https://github.com/kubernetes/kubernetes/pull/24602)
- [ ] [Implementation](https://github.com/kubernetes/kubernetes/pull/25324)

**Comment by dchen1107** [comment]
Should we close this one for 1.3? I saw the implementation pr was merged.

**Comment by dims** [comment]
+1 to @dchen1107 comment (PR is https://github.com/kubernetes/kubernetes/commit/aa8c72adaaab6cba51ff868516ac5b423a95f069). @pmorie can we please close this?

**Comment by ncdc** [comment]
We should either close #20870 or this one, but we need to leave one open until #26710 merges

**Comment by dchen1107** [comment]
Close this one as dup of #20870
