### ISSUE TITLE
Fallback to json unmarshal if Ugorji codec is not generated

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#24610]
Currently, if the Ugorji codec is not generated for types, a json serializer doesn't panic or return an error when decode, it just returns an empty result. It should fallback to use the json.Unmarsh instead.

@krousey @wojtek-t

**Comment by wojtek-t** [comment]
ohh - actually it should fallback. At least that's what documentation claims.

**Comment by caesarxuchao** [comment]
I'm attempting a PR.

**Comment by caesarxuchao** [comment]
On second thought, it makes more sense to return an error than falling back to json.Unmarshal, because we want to force people to use ugorji.

**Comment by wojtek-t** [comment]
Actually I don't agree. ugorji is just a performance optimization. If because of some reason we don't have codec for it, we _should_ fallback to json. The only thing that we should probably do at this point is log a warning/error that we are doing it.

**Comment by wojtek-t** [comment]
@kubernetes/sig-api-machinery

**Comment by wojtek-t** [comment]
Another point is that once we migrate to protobufs and we are sure they are stable for one release, we should probably get rid of ugorji.

**Comment by smarterclayton** [comment]
We should warn at compile time if types don't have ugorji, but it should not be required

**Comment by lavalamp** [comment]
The problem is type meta is embedded, so if the parent type doesn't have the generated functions, then silently only type meta unmarshals stuff...

**Comment by smarterclayton** [comment]
Plan is to nuke ugorji.
