### ISSUE TITLE
Can someone explain those flags?

### ISSUE THREAD

**Issue by streamnsight** [kubernetes/kubernetes#24612]
Can someone explain those flags in `apiserver` ? 

```
      --kubelet-certificate-authority="": Path to a cert. file for the certificate authority.
      --kubelet-client-certificate="": Path to a client cert file for TLS.
      --kubelet-client-key="": Path to a client key file for TLS.
      --kubelet-https[=true]: Use https for kubelet connections
      --kubelet-timeout=5s: Timeout for kubelet operations
```

**Comment by zhouhaibing089** [comment]
It is the tls config for authentication with kubelet, that's to say, the kubelet should know that it is a trusted connection from a real api-server.

**Comment by streamnsight** [comment]
is apiserver the only component to use this TLS setup? i guess apiserver is controlling kubelet, right? So it's only needed on the master.

**Comment by goblain** [comment]
you need it configured on both ends (api and kubelet)

**Comment by siddharthist** [comment]
Looks like this issue can be closed.
