### ISSUE TITLE
e2e flake: Kubectl client [k8s.io] Kubectl expose [It] should create services for rc [Conformance]

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#24619]
```
â€¢ Failure [122.478 seconds]
[k8s.io] Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:426
  [k8s.io] Kubectl expose
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:426
    should create services for rc [Conformance] [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:786

    Expected error:
        <*errors.errorString | 0xc8200e7090>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    not to have occurred

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:760
```
https://github.com/kubernetes/kubernetes/pull/24574#issuecomment-213100652

**Comment by pwittrock** [comment]
Another one:

[logs](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke/4816)

**Comment by pwittrock** [comment]
Seeing a lot of this on (log)[https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24445/node-pull-build-e2e-test/2546]

**Comment by jayunit100** [comment]
^ the above (24706) should fix this test.  however, its interesting to me that this is an issue - the # of pods should be available as soon as the request is made i think... but maybe very asynchronous in strained situation.

**Comment by piosz** [comment]
Two more:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke/5066/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke/5068/

**Comment by piosz** [comment]
The fix is merged. Let's observe whether it helped.

**Comment by soltysh** [comment]
And one here: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23493/kubernetes-pull-build-test-e2e-gce/36831/

**Comment by jayunit100** [comment]
```
Apr 25 02:50:10.613: INFO: namespace e2e-tests-kubectl-zapm5
Apr 25 02:50:10.613: INFO: Running '/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://130.211.195.232 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/examples/guestbook-go/redis-master-controller.json --namespace=e2e-tests-kubectl-zapm5'
Apr 25 02:50:10.727: INFO: stderr: ""
Apr 25 02:50:10.727: INFO: stdout: "replicationcontroller \"redis-master\" created"
Apr 25 02:50:10.753: INFO: Selector matched 1 pods for map[app:redis]
Apr 25 02:50:10.753: INFO: ForEach: Found 0 pods from the filter.  Now looping through them.
STEP: exposing RC
```

I think Doesnt have the new log statement `Waiting for Redist master to start`, so that might be an old one?.

**Comment by soltysh** [comment]
It might be my branch didn't have that fix yet. Agree with @jayunit100 about closing this issue.

**Comment by kargakis** [comment]
Still there: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25034/kubernetes-pull-build-test-e2e-gce/37862/

**Comment by pwittrock** [comment]
Looks like another image pull failure.  Filed #26320

>
STEP: Collecting events from namespace "e2e-tests-kubectl-dpxvf".
May  2 03:41:55.600: INFO: At {2016-05-02 03:39:25 -0700 PDT} - event for redis-master: {replication-controller } SuccessfulCreate: Created pod: redis-master-1u5dd
May  2 03:41:55.600: INFO: At {2016-05-02 03:39:25 -0700 PDT} - event for redis-master-1u5dd: {default-scheduler } Scheduled: Successfully assigned redis-master-1u5dd to e2e-gce-master-1-minion-qsg1
May  2 03:41:55.600: INFO: At {2016-05-02 03:39:26 -0700 PDT} - event for redis-master-1u5dd: {kubelet e2e-gce-master-1-minion-qsg1} Pulling: pulling image "redis"
May  2 03:41:55.619: INFO: POD                                                  NODE                          PHASE    GRACE  CONDITIONS

**Comment by pwittrock** [comment]
Should have been addressed by pre-pulling images
