### ISSUE TITLE
tests in test/integration/ don't fail as expected

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#24635]
hack/test-integration.sh passes even with an explicit "t.Fatalf()" in the test/integration/pods.go:
```
func TestPodUpdateActiveDeadlineSeconds(t *testing.T) {
 	t.Fatalf("FAIL")
        ...
``` 
(see https://github.com/caesarxuchao/kubernetes/commit/682875b5ff213c4808e7156ae421074838be70c4#diff-8f08d0bc51b37140950a80ee07940db1R36).

Appreciate any insight.

@ixdy @krousey

**Comment by krousey** [comment]
The script essentially runs `go test -tags 'integration no-etcd' ./test/integration`. Check the build tags at the top of the file. It's not even compiled in.

**Comment by caesarxuchao** [comment]
The script is using the 'no-docker' tag, not 'no-etcd', so I expect the tests to be compiled.

**Comment by krousey** [comment]
run `go list -f '{{.TestGoFiles}}' with those build tags and see if that file in in there, just to be sure.

**Comment by caesarxuchao** [comment]
`pods.go` doesn't have "_test" in the filename..

**Comment by caesarxuchao** [comment]
Thanks @krousey, the command is handy.
