### ISSUE TITLE
Simplifying specification of multiple files/URLs in kubectl

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#24649]
Would make it easier to stand up examples and apps without multiple flags, multiple commands, or a separate tool.

Ideas, some of which have been proposed before:
- Recursive directory traversal: #19767
- Manifest that can specify multiple files/URLs
  - ideally the same file of relative paths could work for both locals files and fetched via http
- Default file/URL manifest (ala Dockerfile or Makefile or maybe git): #3268
- Unpack archive (tgz, zip, OCI image) specified via `-f` and then invoke `-f` on that directory
- URL shortening via default URL prefix (need to fix preferences: #10693)
- kubectl could expand globs: #12123
- kubectl could support a more distinctive well known extension: #15387
- kubectl could support git sources

Ideally they'd be compatible with current `-f` usage.

cc @kubernetes/sig-cli-feature-requests

**Comment by bgrant0607** [comment]
On multiple files/URLs, that could be as simple as a list. For example, for examples/guestbook, it would be:
```
frontend-deployment.yaml
frontend-service.yaml
redis-master-deployment.yaml
redis-master-service.yaml
redis-slave-deployment.yaml
redis-slave-service.yaml
```
Explicitly naming the file:
```
cd kubernetes/examples/guestbook
kubectl create --file-list=Kubefiles
```
or
```
kubectl create --file-list=http://github.com/kubernetes/kubernetes/examples/guestbook/Kubefiles?raw=true
```
or, using Kubefiles as a convention (which maybe should be configurable in preferences):
```
cd kubernetes/examples/guestbook
kubectl create -f .
```

**Comment by bgrant0607** [comment]
See #24711 for a use case

**Comment by saturnism** [comment]
i should add, when using `kubectl create -f .`, it should ignore hidden files by default.

**Comment by AdoHe** [comment]
@saturnism sounds reasonable to me. @bgrant0607 ptal.

**Comment by bgrant0607** [comment]
@saturnism @AdoHe Ignoring dot files by default makes sense. It could break existing usage, but an argument could be made on security grounds.

cc @smarterclayton

**Comment by smarterclayton** [comment]
I agree that it is justifiable on security grounds.  Many other cli
commands avoid scanning . without explicit permission to do so.

**Comment by dims** [comment]
@AdoHe @bgrant0607 @smarterclayton - How about using "@" to indicate that the stream is a list of files (`javac` command line supports that syntax). Example

```
kubectl create -f @-
kubectl create -f @Kubefiles.txt
kubectl create -f @http://github.com/kubernetes/kubernetes/examples/guestbook/Kubefiles?raw=true
```

When we see the "@" symbol we parse the stream/file/url to get a list of file paths (relative or full paths) and then process those as though they were passed in using multiple `-f` on the command line.

**Comment by smarterclayton** [comment]
Why not add a new flag "--filenames " which supports "-" or any file like construct?  That works just as well as a new @ syntax and is easier to describe in man and help pages

**Comment by dims** [comment]
@smarterclayton right. definitely that would work too

**Comment by AdoHe** [comment]
`--filenames` is fine, but I am thinking whether it has right meaning here.

**Comment by dims** [comment]
@AdoHe how about `--file-list`?

**Comment by errordeveloper** [comment]
I think `--file-list` (`-F`) is good, it's more explicit about what it is. Using stdin is also a good idea, basically just like `-f`. Not too sure about `--filenames`, it seems like it'd be easy to misread.

**Comment by smarterclayton** [comment]
Are there any standard names in use in GNU utils that we can crib?

On Fri, Jul 22, 2016 at 8:22 AM, Ilya Dmitrichenko <notifications@github.com

**Comment by fabianofranz** [comment]
> Are there any standard names in use in GNU utils that we can crib?

@smarterclayton Maybe `--files-from` from the POSIX guidelines: http://www.gnu.org/prep/standards/html_node/Option-Table.html#Option-Table

**Comment by smarterclayton** [comment]
That's about as official as I can imagine!

**Comment by bgrant0607** [comment]
Kops uses a VFS overlay on S3:

The VFS layer is here: https://github.com/kubernetes/kops/tree/master/util/pkg/vfs 

And it can be used like this: https://github.com/kubernetes/kops/blob/master/channels/pkg/channels/apply.go#L34

**Comment by dims** [comment]
let's close this out given the Kustomize stuff has landed.

/close
