### ISSUE TITLE
Doc bug: jobs

### ISSUE THREAD

**Issue by njoneja** [kubernetes/kubernetes#24643]
http://kubernetes.io/docs/user-guide/jobs/ - the example does not create a job whose selector is `app=pi` as indicated - rather, it creates a job whose selector looks more like: `controller-uid=71da17d0-081d-11e6-a71c-42010af00145,job-name=pi`

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by soltysh** [comment]
I guess that's a leftover from when @erictune was adding auto-selector for jobs. If he doesn't I'll create a PR tomorrow.

**Comment by soltysh** [comment]
The current state of the docs is correct, thus closing this issue.
