### ISSUE TITLE
Missing storage medium type for VolumeStats in Kubelet metrics /summary API 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#24640]
In today's /summary API, VolumeStats doesn't include storage medium type, so that we might misaccount /tmpfs usage as a disk usage.

**Comment by dchen1107** [comment]
cc/ @derekwaynecarr for correctness of out-of-memory detection.

**Comment by dchen1107** [comment]
I will send a pr to fix this shortly.

**Comment by derekwaynecarr** [comment]
@dchen1107 - thanks for heads up.  was there a PR?

**Comment by jingxu97** [comment]
@dchen1107 Is this still an issue?
