### ISSUE TITLE
kube-proxy userspace: service may direct to a failed endpoint continuely with session affinity setting 

### ISSUE THREAD

**Issue by njuicsgz** [kubernetes/kubernetes#24648]
I used kube-proxy userspace mode with SessionAffinity=ClientIP. I got a failed endpoint by accessing service, while I have other available endpoints. It is not make sense and different from other LoadBalancers (ELB, nginx). What I want is that choosing a session affinity endpoint firstly, however, if the affinity endpoint can not be connected (port down), I'd like to move to other endpoints.

I will create a PR to fix this issue by deleting the endpoint from the affinityMap if it can not be connected, so it will choose other endpoints in next try.

# Environment:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}

# Reproduce:
- create nginx RC and Service 

$ kubectl get po
NAME                               READY     STATUS    RESTARTS   AGE
fbagent-service-v2.1.0-005-ygr06   0/1       Running   2          23h
nginx-qzxny                        1/1       Running   0          21m
nginx-ss0i7                        1/1       Running   0          21m

root@paas-185 /opt/yaas/1.2/bin
$ kubectl describe service nginx
Name:                   nginx
Namespace:              default
Labels:                 <none>
Selector:               name=nginx
Type:                   ClusterIP
IP:                     10.0.10.106
Port:                   <unset> 40080/TCP
Endpoints:              10.10.3.46:80,10.10.38.24:80
Session Affinity:       ClientIP
No events.

- stop nginx service and check the result

root@paas-185 /opt/yaas/1.2/bin
$ curl 10.0.10.106:40080
nginx-qzxny

root@paas-185 /opt/yaas/1.2/bin
$ kubectl exec -it nginx-qzxny service nginx stop

root@paas-185 /opt/yaas/1.2/bin
$ curl 10.0.10.106:40080
curl: (56) Recv failure: Connection reset by peer

the output of kube-proxy:
E0422 11:04:32.496879   30547 proxysocket.go:104] Dial failed: dial tcp 10.10.3.46:80: connection refused
E0422 11:04:32.497490   30547 proxysocket.go:104] Dial failed: dial tcp 10.10.3.46:80: connection refused
E0422 11:04:32.498046   30547 proxysocket.go:104] Dial failed: dial tcp 10.10.3.46:80: connection refused
E0422 11:04:32.498576   30547 proxysocket.go:104] Dial failed: dial tcp 10.10.3.46:80: connection refused
E0422 11:04:32.498680   30547 proxysocket.go:138] Failed to connect to balancer: failed to connect to an endpoint.

**Comment by bprashanth** [comment]
proposed fix sounds ok to me, do send a pr

**Comment by njuicsgz** [comment]
It works for me following above reproduce steps.

**Comment by njuicsgz** [comment]
closed since it is fixed already
