### ISSUE TITLE
Unable to access URLs from master proxy URIs (grafana, influxdb)

### ISSUE THREAD

**Issue by suryaveerc** [kubernetes/kubernetes#24650]
I have setup Kubernetes coreos cluster on Openstack on [Auro.io](auro.io) cloud.

My setup has 1 Master, 1 node DNS, heapster, influxdb and grafana. Everything is working which I check from pod logs but I am not able to access grafana UI and for that matter any URL from master proxy URL. I even tried HPA example php-apache app, that's also not working.

I tried **112**,**118**, and **122** releases.
I have added all the details in the following SO [question](http://stackoverflow.com/questions/36773792/unable-to-access-grafana-ui-on-kubernetes)

Strangely, the same setup was working on local openstack environment. Not sure if environment has something to do with it. 

Opening issue after a suggestion on slack.

Thanks

**Comment by kargakis** [comment]
Closing in favor of the SO question. Feel free to ask in the kubernetes-users mailing list too.
