### ISSUE TITLE
Periodically verify that the getting started guides with "project" support level work

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#24651]
http://kubernetes.io/docs/getting-started-guides/

Someone on Slack reported a week or so ago that the Fedora RPM (I think they were following [Fedora manual config](http://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/)) had all the extension APIs disabled for some reason.

**Comment by kargakis** [comment]
@ahmetb this is related to enabling testing in the examples repo

**Comment by ahmetb** [comment]
@kargakis this does not seem like it's about the examples repo. The recipes or packages provided at http://kubernetes.io/docs/getting-started-guides/ (which is now https://kubernetes.io/docs/setup/pick-right-solution/) are not part of the examples repository.

**Comment by kargakis** [comment]
The goal of the issue is related. We need to do the same thing for the examples: verify that they work between k8s releases.
