### ISSUE TITLE
curl command from kubectl for "exec" does not work

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#24668]
Running this command:
`kubectl --v=99 exec nginx-app-2883164633-2u2nf "ls"`:

Outputs the sample curl command:
[http://paste.openstack.org/show/495175/](http://paste.openstack.org/show/495175/)

Trying the curl command does not work:
[http://paste.openstack.org/show/495176/](http://paste.openstack.org/show/495176/)

> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {},
>   "status": "Failure",
>   "message": "Upgrade request required",
>   "reason": "BadRequest",
>   "code": 400
> * Connection #0 to host 127.0.0.1 left intact
> }

**Comment by dims** [comment]
@nikhiljindal : couple of more feedback on this /exec curl problem 

- looks like the kubernetes api service is switching protocols to SPDY/3.1 (http://paste.openstack.org/show/495175/) so any code generated by swagger will not work either. 
- the swagger json does not have something to say (-H "X-Stream-Protocol-Version: v2.channel.k8s.io" -H "X-Stream-Protocol-Version: channel.k8s.io" ) is needed in the request header

**Comment by nikhiljindal** [comment]
Yes you need a SPDY aware client for using exec.
https://groups.google.com/forum/#!topic/google-containers/j03gw7PjUeY has some related discussion.

You are right. swagger generated client will not be work.

**Comment by dims** [comment]
@nikhiljindal : thanks for confirming. i understand that if i need both stdout and stderr then i'll need SPDY for multiplexing the streams. Would it be possible to help older clients if they wish just one of them? (say stdout only!)

**Comment by nikhiljindal** [comment]
cc @krousey @kubernetes/sig-api-machinery

**Comment by lavalamp** [comment]
Yeah, I'm not 100% sure why we display the curl command, I guess it was a debugging thing. `kubectl` doesn't actually use curl. You might be able to get more data (i.e., avoid that particular error) by adding the right upgrade request headers, but I would not expect to get any data back without actually supporting SPDY.

**Comment by smarterclayton** [comment]
It's so a human can debug or emulate the API.  It's fairly common for
integrators to use (I use it occasionally).

**Comment by dims** [comment]
@lavalamp @smarterclayton ack on the curl i really love that support when i am trying new things. 

At this point, would it be possible to support non-SPDY enabled clients for some scenarios (say they just want stdout and not stderr). Example common python libraries do not support SPDY. 

Also is there a way to mark swagger API with additional information that seems to be needed at runtime (upgrade headers, spdy) etc. Also documentation about the API should be corrected (text/plain is returned by default).

**Comment by smarterclayton** [comment]
Exec supports websockets - the protocol should be documented in pkg/kubelet somewhere (sub folder remote or attach I think).  There is an implementation in JavaScript in a few places - let me look

**Comment by smarterclayton** [comment]
https://github.com/kubernetes-ui/container-terminal?files=1

**Comment by dims** [comment]
@smarterclayton thanks!

**Comment by bgrant0607** [comment]
This needs to be better documented (#16095), but it sounds like this was resolved.

**Comment by runseb** [comment]
It would be nice to have an example of exec and (port-forward) in different languages. Implementing this call with SPDY is not dead trivial.

**Comment by jonathan-kosgei** [comment]
Hi, holding off on opening another issue, I have this same problem. How exactly do I get curl to work? A working example would really help. I tried adding the headers above with no succes.
```
curl -H "X-Stream-Protocol-Version: v2.channel.k8s.io" -H "X-Stream-Protocol-Version: channel.k8s.io" http://172.10.2.1:8080/api/v1/namespaces/mailho/pods/webmail-2495503454-zufoc/exec?container=webmail&command=ls
```

**Comment by LQkinglear** [comment]
@dims did you have solve this problem？
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "Upgrade request required",
"reason": "BadRequest",
"code": 400

Connection #0 to host 127.0.0.1 left intact
}

**Comment by dims** [comment]
@LQkinglear : yes, see calls to websocket from python in client-python repo - https://github.com/kubernetes-incubator/client-python/search?utf8=%E2%9C%93&q=websocket_call&type=

**Comment by LQkinglear** [comment]
@dims thanks,but  i need to request the k8s api  by https,and how can i achieve like this:
![image](https://cloud.githubusercontent.com/assets/16059650/24791865/61b2ade0-1bae-11e7-93a4-7bfe30f71d08.png)

**Comment by dims** [comment]
@LQkinglear did you see the links from @smarterclayton ? https://github.com/kubernetes-ui/container-terminal?files=1

**Comment by LQkinglear** [comment]
@dims  thank you very much. I just started learning k8s,

**Comment by michrabi** [comment]
@dims your link from April 6th is broken. Please assist since I still face the issue. Thanks

**Comment by ncdc** [comment]
@michrabi does this help? https://github.com/kubernetes-client/python/blob/77a504e294cd3e0bf95245ae06fa90b3cf95a476/examples/exec.py

**Comment by jtuttle** [comment]
@smarterclayton Did you ever find the exec websocket docs? I've searched through [pkg/kubelet](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet) but I don't see anything relevant. Thanks.
