### ISSUE TITLE
Verify flake: verify-generated-protobuf.sh

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24661]
```
+++ [0422 02:01:46] Creating data container
Error response from daemon: open /var/lib/docker/containers/39f63297738b06376d88f1295c428572710aa560223e3c79d9bcbef891e5da07/config.json: no such file or directory
!!! Error in /go/src/k8s.io/kubernetes/hack/../build/common.sh:595
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/../build/common.sh:595 kube::build::run_build_command(...)
  2: /go/src/k8s.io/kubernetes/hack/update-generated-protobuf.sh:57 main(...)
Exiting with status 1
!!! Error in /go/src/k8s.io/kubernetes/hack/after-build/verify-generated-protobuf.sh:44
  '"${KUBE_ROOT}/hack/update-generated-protobuf.sh"' exited with status 1
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/after-build/verify-generated-protobuf.sh:44 main(...)
Exiting with status 1
!!! Error in ./hack/../hack/verify-generated-protobuf.sh:26
  '"${KUBE_ROOT}/hack/after-build/verify-generated-protobuf.sh" "$@"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-generated-protobuf.sh:26 main(...)
Exiting with status 1
FAILED   ./hack/../hack/verify-generated-protobuf.sh	3s
```
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24291/kubernetes-pull-test-unit-integration/22388/

cc @kubernetes/sig-testing @wojtek-t

**Comment by ixdy** [comment]
Looks like this ran as the same time as the daily docker cleanup... guess it's a race of sorts. Wonder if we can run the cleanup only when no other jobs are running. @spxtr

**Comment by spxtr** [comment]
I don't know if there's an easy way to do that. We're running jobs all the time on post-commit Jenkins, and it can take a few hours to go quiet...

**Comment by smarterclayton** [comment]
I also saw

```
SUCCESS
Error deleting container: Error response from daemon: Driver aufs failed to remove root filesystem 08e49cee468a671d333d15193dff2e4e336853866fcce430665e21001ffe310c: rename /var/lib/docker/aufs/mnt/08e49cee468a671d333d15193dff2e4e336853866fcce430665e21001ffe310c /var/lib/docker/aufs/mnt/08e49cee468a671d333d15193dff2e4e336853866fcce430665e21001ffe310c-removing: device or resource busy
--2016-04-22 16:01:48--  https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/apis/batch/v1/register.go
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.44.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.44.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1549 (1.5K) [text/plain]
Saving to: â€˜register.go€™
```

in https://00e9e64bac9ae239af839370a064be9cfa90d8cc2954d696bc-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F24666%2Fkubernetes-pull-test-unit-integration%2F22434%2Fbuild-log.txt?qk=AD5uMEuBBwIeXagwuD69rX1CNfz852NwqLVCDDHDBFmrR8Xx3R_1D4nNu6QthTQLXoafcbWpgVVSTTWZamUl0W-gMkrwTe-4XIkWRYtwhA6ivLyvCRpapK7O3lmAscQ70rkiswCYV_OHXkAniVob9BOYYcHiVKqKsvzDy__gCUpm1w4NQEtEf4tUNzw4q_dGSagpUeFFbG2HPHdHXelB9V9hiEjTJMpCkbHsEOGzljXCfgCphTtHpdFN3tWq1Zghx693uPWqHMG8lGTRdAULzyL3_ow_B0svmd2Ur5bvEjxpSpGCJjawG5hbnTlIIQyYc_WQMLTsNMbdLsWPDb2wrtI002ly6Jmk-G99REIOgy0eyJ_ZioeH9Y_aIpw_7wmlFQwZE0YLUzBpKYud-kwS2WQ4x4BIaLgS1IpmaYPZLQTTZFqDbDrtG6a5B5DdrjA90kH7DqxyNXvg7Vx2KPRa93ioB1OPd1WQXyr1uv_jerqeBblsLNabu4Y7-8_aQKlfo5n1_MhuJrXfX5SyH1eW-P2yuGECrcnz2SudBicNLU0FdwXt1eTW0a8ZPEEWal1UC8I_aHybA0c4EUHHKHJxr2nPlPSdBFlnMh4xt3ZKs5Ev8EFpMBCE_sh9R6LlL8M0IcKaM_r-doLOFzQv_YFTS3ouJjARItBaoh1Lkjnx_Gnh-lQGnn5keRCktnkPEFh_IyRM0FmcRMGM5Wjy4M7XMzFdkNWBrjOIDd3TLBvoiE9FiqveXVKown1C4WlFlWYera7q-TRPridvr1B9vpLHteXHhvJ26drg9i4OzZANyO8bHUdG6sWiAjLkpHgUk1soMhF4UQYDXucBryS7KSgjrHHKTLaAGstpuYrvCUJn3_qz0Q1cpAyw8x3MZmHyJpvljRdvJMsyVhlzYiuN3O_OnFVGbrJ-gFpMpM6WtZZn0PN-NB0ZqVJbCkE

Related?

**Comment by ixdy** [comment]
That build did not happen at the same time as the cleanup job, so I don't think so.

**Comment by fejta** [comment]
What is the race exactly?

**Comment by fejta** [comment]
Hit here: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24131/kubernetes-pull-test-unit-integration/22815/

**Comment by ixdy** [comment]
@fejta in `build/common.sh`, we create the build container and then run it. it's apparently possible for this container to be cleaned up between creation and running, because it's not running or attached to anything.

**Comment by ixdy** [comment]
Might be worth seeing if there's some way to only clean up containers/images older than an hour.

**Comment by ixdy** [comment]
#24832 maybe.

**Comment by andyzheng0831** [comment]
Hit it again, here: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24987/kubernetes-pull-test-unit-integration/23448/

**Comment by fejta** [comment]
Verifying ./hack/../hack/verify-generated-protobuf.sh
/go/src/k8s.io/kubernetes/hack/after-build/verify-generated-protobuf.sh: line 42: sudo: command not found
+++ [0429 03:26:14] Verifying Prerequisites....
+++ [0429 03:26:14] Building Docker image kube-build:build-91dbedbcaf.
+++ [0429 03:26:15] Running build command....
Go version: go version go1.6 linux/amd64
+++ [0429 03:26:16] Building go targets for linux/amd64:
    cmd/libs/go2idl/go-to-protobuf
    cmd/libs/go2idl/go-to-protobuf/protoc-gen-gogo
!!! Error in /go/src/k8s.io/kubernetes/hack/../build/common.sh:595
  '"${docker_cmd[@]}" "$@"' exited with status 137
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/../build/common.sh:595 kube::build::run_build_command(...)
  2: /go/src/k8s.io/kubernetes/hack/update-generated-protobuf.sh:58 main(...)
Exiting with status 1
!!! Error in /go/src/k8s.io/kubernetes/hack/after-build/verify-generated-protobuf.sh:44
  '"${KUBE_ROOT}/hack/update-generated-protobuf.sh"' exited with status 1
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/after-build/verify-generated-protobuf.sh:44 main(...)
Exiting with status 1
!!! Error in ./hack/../hack/verify-generated-protobuf.sh:26
  '"${KUBE_ROOT}/hack/after-build/verify-generated-protobuf.sh" "$@"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-generated-protobuf.sh:26 main(...)
Exiting with status 1
FAILED   ./hack/../hack/verify-generated-protobuf.sh	7s

**Comment by ixdy** [comment]
Neither of those builds happened at the same time as the cleanup job, so I don't think it's the cleanup race anymore. Not sure what is causing `docker` to exit with status 137.

**Comment by ixdy** [comment]
Ugh, it looks like builds are not properly isolated from each other.

Both kubernetes-pull-test-unit-integration/23398 and kubernetes-pull-test-unit-integration/23399 started at about the same time on Friday morning.

From 23398's build log:
```
Verifying ./hack/../hack/verify-generated-protobuf.sh
/go/src/k8s.io/kubernetes/hack/after-build/verify-generated-protobuf.sh: line 42: sudo: command not found
+++ [0429 03:26:14] Verifying Prerequisites....
+++ [0429 03:26:14] Building Docker image kube-build:build-91dbedbcaf.
+++ [0429 03:26:15] Running build command....
Go version: go version go1.6 linux/amd64
+++ [0429 03:26:16] Building go targets for linux/amd64:
    cmd/libs/go2idl/go-to-protobuf
    cmd/libs/go2idl/go-to-protobuf/protoc-gen-gogo
!!! Error in /go/src/k8s.io/kubernetes/hack/../build/common.sh:595
  '"${docker_cmd[@]}" "$@"' exited with status 137
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/../build/common.sh:595 kube::build::run_build_command(...)
  2: /go/src/k8s.io/kubernetes/hack/update-generated-protobuf.sh:58 main(...)
Exiting with status 1
!!! Error in /go/src/k8s.io/kubernetes/hack/after-build/verify-generated-protobuf.sh:44
  '"${KUBE_ROOT}/hack/update-generated-protobuf.sh"' exited with status 1
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/after-build/verify-generated-protobuf.sh:44 main(...)
Exiting with status 1
!!! Error in ./hack/../hack/verify-generated-protobuf.sh:26
  '"${KUBE_ROOT}/hack/after-build/verify-generated-protobuf.sh" "$@"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-generated-protobuf.sh:26 main(...)
Exiting with status 1
FAILED   ./hack/../hack/verify-generated-protobuf.sh	7s
```

From 23399's build log:
```
Verifying ./hack/../hack/verify-generated-protobuf.sh
/go/src/k8s.io/kubernetes/hack/after-build/verify-generated-protobuf.sh: line 42: sudo: command not found
+++ [0429 03:26:20] Verifying Prerequisites....
+++ [0429 03:26:20] Building Docker image kube-build:build-91dbedbcaf.
+++ [0429 03:26:20] Running build command....
Go version: go version go1.6 linux/amd64
+++ [0429 03:26:22] Building go targets for linux/amd64:
    cmd/libs/go2idl/go-to-protobuf
    cmd/libs/go2idl/go-to-protobuf/protoc-gen-gogo
+++ [0429 03:26:27] Placing binaries
type checker error: github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuacct.go:22:25: GetClockTicks not declared by package system
type checking encountered some errors in "github.com/opencontainers/runc/libcontainer/cgroups/fs", but ignoring.
2016/04/29 03:26:29 Processing package "k8s.io.kubernetes.pkg.util.intstr", disk location "/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/intstr"
...
SUCCESS  ./hack/../hack/verify-generated-protobuf.sh	19s
```

Note how the docker build for each started within seconds of each other, and they both used the same image name.

**Comment by ixdy** [comment]
Aha, I've figured it out. While the two jobs have separate workspaces on the actual Jenkins VM, they're running inside Docker, so `$KUBE_ROOT` is the same for both jobs. As a result, the computed hash is the same in https://github.com/kubernetes/kubernetes/blob/master/hack/update-generated-protobuf.sh#L34.

**Comment by smarterclayton** [comment]
That's fun
