### ISSUE TITLE
swagger definition for pods/{name}/log is incorrect

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#24664]
The following API, does not produce appliction/json, it returns text/plain:
/api/v1/namespaces/{namespace}/pods/{name}/log

The API should has an incorrect responseModel as well:
"responseModel": "v1.Pod"

Please see the definition here:
https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L8400

See verbose output for ["kubectl --v=99 logs nginx-app-2883164633-2u2nf"](http://paste.openstack.org/show/495147/) to see the problem

**Comment by nikhiljindal** [comment]
Closing as dup of https://github.com/kubernetes/kubernetes/issues/14071
