### ISSUE TITLE
CodecFactory should not have a deep copy generated

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#24667]
I tried adding +gencopy=false to the codecfactory and it still created one.  Maybe we need a package level comment for exclusion.

**Comment by smarterclayton** [comment]
@wojtek-t fyi,not a high priority, just noticed.

**Comment by wojtek-t** [comment]
I will take a look next week.

**Comment by smarterclayton** [comment]
Looks like a lot of the packages has them - conversion shouldn't really either.

**Comment by wojtek-t** [comment]
Conversions are only generated where they are needed. We should just fix it for deep-copies.

**Comment by wojtek-t** [comment]
This has already been fixed in the meantime.
