### ISSUE TITLE
unit flake: kubelet: TestHandlePortConflicts

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24680]
```
--- FAIL: TestHandlePortConflicts (0.00s)
	kubelet_test.go:2417: expected pod status "Pending". Got "Failed".
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24674/kubernetes-pull-test-unit-integration/22446/

cc @kubernetes/sig-node @dchen1107

**Comment by yujuhong** [comment]
@gmarek The same set of tests have failed twice for your PR.
```
=== RUN   TestHandlePortConflicts
W0422 11:17:42.442151   32164 plugins.go:166] can't set sysctl net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
--- FAIL: TestHandlePortConflicts (0.03s)
	kubelet_test.go:2417: expected pod status "Pending". Got "Failed".
=== RUN   TestHandleHostNameConflicts
W0422 11:17:42.471729   32164 plugins.go:166] can't set sysctl net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
--- FAIL: TestHandleHostNameConflicts (0.00s)
	kubelet_test.go:2480: expected pod status "Pending". Got "Failed".
=== RUN   TestHandleNodeSelector
W0422 11:17:42.474016   32164 plugins.go:166] can't set sysctl net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
--- FAIL: TestHandleNodeSelector (0.01s)
	kubelet_test.go:2535: expected pod status "Pending". Got "Failed".
```

Could you run the test locally to see if it's caused by your PR?

**Comment by gmarek** [comment]
Will do. It'll be very sad if it is.

**Comment by dchen1107** [comment]
The only change in this area lately I could think about is #20204, but I double check the code, I couldn't figure out the link between the failure and #20204.

**Comment by yujuhong** [comment]
> Will do. It'll be very sad if it is.

kubelet does share the same predicate library with the scheduler, so it's not unlikely.

@gmarek, assigning the issue to you to rule out or verify whether this is a flake. Feel free to unassign after the triaging.

**Comment by gmarek** [comment]
I have it failing on the head...

**Comment by gmarek** [comment]
Oh sorry, no - I had a dirty master branch.

**Comment by gmarek** [comment]
Yeah - it was a problem with PR/kubelet tests. Closing this issue.
