### ISSUE TITLE
Merge RunInContainer and ExecInContainer in kubelet's runtime interface

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#24689]
For docker, [`RunInContainer`](https://github.com/kubernetes/kubernetes/blob/de5f40705851fcc30a3ec102b96b1a5415fedc10/pkg/kubelet/dockertools/manager.go#L1015) is implemented using `docker exec`, while `ExecInContainer` either using [`docker exec`](https://github.com/kubernetes/kubernetes/blob/de5f40705851fcc30a3ec102b96b1a5415fedc10/pkg/kubelet/dockertools/exec.go#L101) or [nsenter](https://github.com/kubernetes/kubernetes/blob/de5f40705851fcc30a3ec102b96b1a5415fedc10/pkg/kubelet/dockertools/exec.go#L40).
For rkt, the implementations for both are similar: [`ExecInContainer`](https://github.com/kubernetes/kubernetes/blob/de5f40705851fcc30a3ec102b96b1a5415fedc10/pkg/kubelet/rkt/rkt.go#L1400) and [`RunInContainer`](https://github.com/kubernetes/kubernetes/blob/de5f40705851fcc30a3ec102b96b1a5415fedc10/pkg/kubelet/rkt/rkt.go#L1362).

In theory, we should be able to merge [RunInContainer and ExecInContainer in the container runtime interface](https://github.com/kubernetes/kubernetes/blob/f9e2f522b4b99359c23d6b15f80075d9c58a32bf/pkg/kubelet/container/runtime.go#L107). Is there any reason not to do it?

@kubernetes/sig-node

**Comment by yifan-gu** [comment]
@yujuhong I don't remember there is any special reason not to do this.

**Comment by feiskyer** [comment]
+1 for merge.

**Comment by yujuhong** [comment]
The two methods have different arguments and return types.
```
RunInContainer(containerID ContainerID, cmd []string) ([]byte, error)
ExecInContainer(containerID ContainerID, cmd []string, stdin io.Reader, stdout, stderr io.WriteCloser, tty bool) error
```
RunInContainer expects the combined stdout/stderr returned in the byte array, and is mostly used for internal operations for convenience (e.g., probing). @yifan-gu @feiskyer, what do you think about keeping only `ExecInContainer` in the `Runtime` interface, and implement `RunInContainer` by wrapping `ExecInContainer`? In other words, runtime only has to implement `ExecInContainer`, and kubelet will use it to implement `RunInContainer`.

**Comment by feiskyer** [comment]
@yujuhong Agree. I could take this if you have not started this work.

**Comment by feiskyer** [comment]
@yujuhong This issue could be closed.
