### ISSUE TITLE
kubernetes-e2e-gce-release-1.0/ flake Nodes Resize should be able to delete nodes

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#24686]
Failed a couple times in the past few days:

>
Nodes Resize should be able to delete nodes
>
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:460 Expected error: <*errors.errorString | 0xc20825dec0>: { s: "failed to wait for pods responding: pod with UID a2a6228f-08c4-11e6-9b4e-42010af00002 is no longer a member of the replica set. Must have been restarted for some reason. Current replica set: &{{ } {/api/v1/namespaces/e2e-tests-resize-nodes-g95sc/pods 2259} [{{ } {my-hostname-delete-node-0zjcv my-hostname-delete-node- e2e-tests-resize-nodes-g95sc /api/v1/namespaces/e2e-tests-resize-nodes-g95sc/pods/my-hostname-delete-node-0zjcv c8dda693-08c4-11e6-9b4e-42010af00002 2247 0 2016-04-22 12:59:55 -0700 PDT map[name:my-hostname-delete-node] map[kubernetes.io/created-by:{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"e2e-tests-resize-nodes-g95sc\",\"name\":\"my-hostname-delete-node\",\"uid\":\"a29d17b8-08c4-11e6-9b4e-42010af00002\",\"apiVersion\":\"v1\",\"resourceVersion\":\"2216\"}}]} {[{default-token-p2vg8 { 0xc20825d1a0 }}] [{my-hostname-delete-node gcr.io/google_containers/serve_hostname:1.1 [] [] [{ 0 9376 TCP }] [] {map[] map[]} [{default-token-p2vg8 true /var/run/secrets/kubernetes.io/serviceaccount}] /dev/termination-log IfNotPresent }] Always ClusterFirst map[] default e2e-gce-1-0-minion-wqg4 false []} {Pending [] 2016-04-22 12:59:55 -0700 PDT []}} {{ } {my-hostname-delete-node-perit my-hostname-delete-node- e2e-tests-resize-nodes-g95sc /api/v1/namespaces/e2e-tests-resize-nodes-g95sc/pods/my-hostname-delete-node-perit c8d74aa7-08c4-11e6-9b4e-42010af00002 2231 0 2016-04-22 12:59:55 -0700 PDT map[name:my-hostname-delete-node] map[kubernetes.io/created-by:{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"e2e-tests-resize-nodes-g95sc\",\"name\":\"my-hostname-delete-node\",\"uid\":\"a29d17b8-08c4-11e6-9b4e-42010af00002\",\"apiVersion\":\"v1\",\"resourceVersion\":\"2182\"}}]} {[{default-token-p2vg8 { 0xc20825d230 }}] [{my-hostname-delete-node gcr.io/google_containers/serve_hostname:1.1 [] [] [{ 0 9376 TCP }] [] {map[] map[]} [{default-token-p2vg8 true /var/run/secrets/kubernetes.io/serviceaccount}] /dev/termination-log IfNotPresent }] Always ClusterFirst map[] default e2e-gce-1-0-minion-wqg4 false []} {Pending [] 2016-04-22 12:59:55 -0700 PDT []}}]}", } failed to wait for pods responding: pod with UID a2a6228f-08c4-11e6-9b4e-42010af00002 is no longer a member of the replica set. Must have been restarted for some reason. Current replica set: &{{ } {/api/v1/namespaces/e2e-tests-resize-nodes-g95sc/pods 2259} [{{ } {my-hostname-delete-node-0zjcv my-hostname-delete-node- e2e-tests-resize-nodes-g95sc /api/v1/namespaces/e2e-tests-resize-nodes-g95sc/pods/my-hostname-delete-node-0zjcv c8dda693-08c4-11e6-9b4e-42010af00002 2247 0 2016-04-22 12:59:55 -0700 PDT map[name:my-hostname-delete-node] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"e2e-tests-resize-nodes-g95sc","name":"my-hostname-delete-node","uid":"a29d17b8-08c4-11e6-9b4e-42010af00002","apiVersion":"v1","resourceVersion":"2216"}}]} {[{default-token-p2vg8 { 0xc20825d1a0 }}] [{my-hostname-delete-node gcr.io/google_containers/serve_hostname:1.1 [] [] [{ 0 9376 TCP }] [] {map[] map[]} [{default-token-p2vg8 true /var/run/secrets/kubernetes.io/serviceaccount}] /dev/termination-log IfNotPresent }] Always ClusterFirst map[] default e2e-gce-1-0-minion-wqg4 false []} {Pending [] 2016-04-22 12:59:55 -0700 PDT []}} {{ } {my-hostname-delete-node-perit my-hostname-delete-node- e2e-tests-resize-nodes-g95sc /api/v1/namespaces/e2e-tests-resize-nodes-g95sc/pods/my-hostname-delete-node-perit c8d74aa7-08c4-11e6-9b4e-42010af00002 2231 0 2016-04-22 12:59:55 -0700 PDT map[name:my-hostname-delete-node] map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"e2e-tests-resize-nodes-g95sc","name":"my-hostname-delete-node","uid":"a29d17b8-08c4-11e6-9b4e-42010af00002","apiVersion":"v1","resourceVersion":"2182"}}]} {[{default-token-p2vg8 { 0xc20825d230 }}] [{my-hostname-delete-node gcr.io/google_containers/serve_hostname:1.1 [] [] [{ 0 9376 TCP }] [] {map[] map[]} [{default-token-p2vg8 true /var/run/secrets/kubernetes.io/serviceaccount}] /dev/termination-log IfNotPresent }] Always ClusterFirst map[] default e2e-gce-1-0-minion-wqg4 false []} {Pending [] 2016-04-22 12:59:55 -0700 PDT []}}]} not to have occurred

[logs](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-release-1.0/4469)

**Comment by goltermann** [comment]
@davidopp @pwittrock this has no update since it was opened.  is this flake still occurring?
