### ISSUE TITLE
Customize cAdvisor event storage policy

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#24698]
By default cAdvisor stores up to 100,000 events for up to 24 hours. At capacity, that's around O(10MB) that is unused by the Kubelet.

The default values are customized by the `--event_storage_{age,event}_limit` flags. We should add our own defaults to disable the event store.

/cc @kubernetes/sig-node

**Comment by vishh** [comment]
+1. Does kubelet use these events?

**Comment by timstclair** [comment]
Kubelet watches the event stream for Oom events, but never queries the storage. I'd like to just disable event storage completely for the Kubelet's cAdvisor, but that would be a regression if anyone was querying it through the cAdvisor endopoints. It is configurable from a flag though.

**Comment by vishh** [comment]
If a user wants that feature, they can always run cAdvisor in a DaemonSet :P

**Comment by yujuhong** [comment]
Not sure how cadvsior event stream works internally. After kubelet restarts, will it be able to get OOM events that happened in the past N minutes?

**Comment by timstclair** [comment]
The event store is an in-memory data structure, so if kubelet restarts it would be lost anyway.

**Comment by yujuhong** [comment]
I assume cadvisor parses the kernel log again during startup. Is that not correct?

**Comment by timstclair** [comment]
Ah, I understand your question. If it restarts, it will reparse the kernel log. The event stream is independent of the event store - so each event will be sent to the watchers and also (independently) added to the event store.

**Comment by yujuhong** [comment]
I see. Thanks for the clarification!

**Comment by roberthbailey** [comment]
What is the status of this issue? We are past the feature freeze for 1.3 and this is still part of the milestone.

**Comment by timstclair** [comment]
It depends on https://github.com/kubernetes/kubernetes/pull/25914, which has been LGTM'd for over a week... I'll get this reviewed now though, so it can go in as soon as the dependency is in.

**Comment by timstclair** [comment]
Oops, that comment was referring to the PR which addresses this (https://github.com/kubernetes/kubernetes/issues/24771).

**Comment by timothysc** [comment]
Just as a general note, I would still like to off-load events entirely out of the mainline path. 

/cc @kubernetes/sig-scalability

**Comment by timstclair** [comment]
@timothysc - I don't understand your comment. This issue refers to events generated by cAdvisor from scanning the kernel logs. Were you referring to the same events?

**Comment by timothysc** [comment]
@timstclair ohh... I was referring to kubernetes events.

**Comment by timstclair** [comment]
Ok, makes sense. This should have no effect on kubernetes events.
