### ISSUE TITLE
Add events for Volumes

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#24690]
I think it would be beneficial for debugging to add events about volumes in the system.  A couple examples:
1.  A PV should have an event recorded when it is attached / detached from a node.
2.  We should make an event when a mount happens (whether it failed or not)
3.  We should make an event when a volume is formatted (whether the format fails or not)

If a volume that requires a cloud provider attach is used directly in a pod, I suggest that event should be generated for that pod where applicable.  For example, detach may not be applicable since the pod will necessarily have been deleted or died.

For the record, I think this is probably more applicable to network storage than to things like secrets or configmaps, but it's not strictly PVs, since pods can use volumes directly without using PVs.

@kubernetes/sig-storage

**Comment by jayunit100** [comment]
Also can we make an event on vol unmount?  <- @rootfs

**Comment by pmorie** [comment]
@jayunit100 yeah, i definitely support an event for PVs being unmounted

**Comment by thockin** [comment]
Wrinkle - events are namespaces objects.  Into which namespace should they
go?

**Comment by erinboyd** [comment]
If you are an admin, can you see them across all namespaces? Can you use flags line for other objects to limit namespaces?

**Comment by thockin** [comment]
Not sure what you're asking. I think we have a generic problem - any
non-namespaced object has at-best awkward semantics for events.

**Comment by bprashanth** [comment]
I think it's more important that it shows up in `describe volume`, I rarely use `get events` standalone. One option is to just shove it in pv annotations and deserialize in kubectl's describe handler.

**Comment by pmorie** [comment]
I feel like @derekwaynecarr and i discussed this and had some ideas, though
I forget the outcome of the convo and issue number :-|

**Comment by derekwaynecarr** [comment]
Should we just be consistently awkward and treat them no different than
node events?

**Comment by pmorie** [comment]
It seems like they should be treated however node events are, yeah.

**Comment by erinboyd** [comment]
@thockin Yes, I guess I was asking why we wouldn't treat them like any other resource. I was looking at them in terms of permissions to view on roles, not the nature in which they would be produced. However, irt the action that is looking at the mount is namespaced (pvc) for instance. So when the pod spec used to stake that claim is also namespaced, I don't understand what you mean by non-namespaced objects. Just creating the PV doesn't perform the mount, so I guess I am missing something. Unless, this is somehow changing in the future where when you create the PV spec, it goes out and does a 'pre-mount' or something...?

**Comment by erinboyd** [comment]
@pmorie @thockin So talking with Paul there are two MAIN use cases:
1) pod attached to PV via PVC
2) pod attached to volume via plugin

Both of these are namespaced and could be driven from there.

The event I am thinking of though, would be:
1) Volume becomes unavailable, via network or catastrophic event
1) Volume gets deleted from a pod consuming it 

These events would need to be funneled back into the pods tied to them and the event created in a non-namespaced place.
