### ISSUE TITLE
Update Wikipedia on a release

### ISSUE THREAD

**Issue by craigbox** [kubernetes/kubernetes#24691]
https://en.wikipedia.org/wiki/Kubernetes has an Infobox with these two lines (hand-updated today) —

```
| latest release version = 1.2.3<ref name="github releases">{{cite web|url=https://github.com/kubernetes/kubernetes/releases |title=GitHub Releases page |work=github.com | date=2016-04-22}}</ref>
| latest release date    = {{release date|2016|04|22}}
```

It would be great if updating this could be part of the release process.

**Comment by mml** [comment]
IANAL.

I draw everyone's attention to https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest

Maybe the right thing to do is visit https://en.wikipedia.org/wiki/Talk:Kubernetes and use https://en.wikipedia.org/wiki/Template:Request_edit

**Comment by mml** [comment]
@kubernetes/docs
