### ISSUE TITLE
integration flake: cassandra

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24704]
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24674/kubernetes-pull-test-unit-integration/22488/

```
FAIL!
Get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}
  Expected: cassandra:cassandra:cassandra:cassandra:
  Got:      cassandra:cassandra:
```

cc @janetkuo

**Comment by jayunit100** [comment]
I think this is it https://github.com/kubernetes/kubernetes/commit/03f48e730e6894bc3fef2d694823430e168bb1b5#diff-e2c8544666bb21f92286b190d5c8cb9a ...

**Comment by bgrant0607** [comment]
@jayunit100 Yes, a PR would be appreciated.

**Comment by jayunit100** [comment]
ok i can put this in @bgrant0607

**Comment by cjcullen** [comment]
I'm pretty sure I [saw this again](https://00e9e64bacd0d0d5aca9f59e02ddbf9f2275ffb1eae5037453-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F25312%2Fkubernetes-pull-test-unit-integration%2F24812%2Fbuild-log.txt?qk=AD5uMEuhaHacbBE1LN9BNvOPDns87gUqlSC1kaqdMweoVrrVO7gAHTFo7lSkA-zNdLiohDmd_iattKh7kD1mecNBrk4VqlYCkzarhILrxA3uJNDMT1ntAaLYIurib9Yt_iyv0jsAA0ayHd5Va5nWf7l99ZPw9A7ebvQzs9qbzqMfqWRHvNEan9JvoTZdX8dpqccz4pRTGCZhpz2y3k_9WV6Pve4Ow5yHAdVWwVPHez8ertHb7-0zRjDkNHa1ueFTOhEnQoFCSRALpSv_-yPQxBHMpRun5SSwkV8bgMsgqKqPHBDLU6C3D9CIKGF5NXNFGC64TwwA13wuEcl5HAwJQb3DNgxkMLYLnIRmLQC8T6WV9RkamwcBvH91zVCBUk9RKdoS8kBsmcXWQNVxgc3CcEL2CXqOV22kktVjAdUJdjghIbjLjWforaR6UufQU5CjgaxGLKcLx1sHLUqb2wpk5b0EvvVAp5XvY4BQEi8_hTgU-ECst4UQWz6K4D_CbgHYjthPWNzUTZKLjCpYXQLhAmmyPbl9xrfIfwVkY8ci1nkW-hk9A9-XhV68VdHZOjEtdvEdsoMFWaOiQRKUu0mJKrXBMcR1Jplr8_CiZkOl_aOlZLY4FHtj83OZ0K_cDvnU6lYYCMJfjVsjZ6_0rqReMeerRQHmObiUazTj96P5PeebmMVKTcAkuEwDwLT4444j4oBSF40Jlg0D8s6NjKUNcfZjGMOh2Kd298R2gOBRq-J6G8NHYsqgSKiN0tIYBOrhMFDM1JAMTB9NxVDbGUHkkw7doNwIECoaOf15H4C_9W-N8GHhfWnulCupQWu0JwKWjAMLXXR2AyF1c_2KEkxARZ2wKHaESde2ZKeb6w2dmh2kKpRFGWM0dGgT-ed8rp7EQa2XggkT-Wbz3-ev3Mw0gPZJoFslHtx0dYXNOA4l4BlTP5dLNI-byt0) in an integration test on #25312

**Comment by jayunit100** [comment]
Hmmm...I don't see the flake. ?

**Comment by cjcullen** [comment]
:( I didn't realize those links expired.

My integration test failed w/ the exact same:
```
FAIL!
Get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}
  Expected: cassandra:cassandra:cassandra:cassandra:
  Got:      cassandra:cassandra:
```

**Comment by jayunit100** [comment]
Ok, but just letting you know Even if it prints that it still might pass .  Do you have the full trace?

**Comment by cjcullen** [comment]
I don't have a full trace. Sounds like that may not have even been my actual flake. Re-closing this, as there's nothing left to go on.

**Comment by spxtr** [comment]
```
(B+++ [0516 17:22:59] Testing resource aliasing
replicationcontroller "cassandra" created
service "cassandra" created

FAIL!
Get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}
  Expected: cassandra:cassandra:cassandra:cassandra:
  Got:      cassandra:cassandra:
(B
2066 ./hack/test-cmd.sh
(B

FAIL!
Get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}
  Expected: cassandra:cassandra:cassandra:
  Got:      cassandra:cassandra:
(B
2067 ./hack/test-cmd.sh
(B
I0516 17:23:00.059828    5266 event.go:216] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"cassandra", UID:"829ee7de-1bc5-11e6-9a01-0242ac110003", APIVersion:"v1", ResourceVersion:"1382", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: cassandra-ukgsa
I0516 17:23:00.066628    5266 event.go:216] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"cassandra", UID:"829ee7de-1bc5-11e6-9a01-0242ac110003", APIVersion:"v1", ResourceVersion:"1382", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: cassandra-e2d8q

FAIL!
Get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}
  Expected: cassandra:cassandra:
  Got:      cassandra:cassandra:cassandra:cassandra:
(B
2068 ./hack/test-cmd.sh
(B
!!! Error in ./hack/test-cmd.sh:53
```
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25505/kubernetes-pull-test-unit-integration/26196/

**Comment by jayunit100** [comment]
Yeah timeout will help it be less flakey but I guess either way the test is inherently async and polling is required
