### ISSUE TITLE
Serialize and write api.Pod/Container spec/status as container annotations 

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#24702]
Forked from the discussion in #23725.

In short, we've been writing information as docker labels and rkt annotations to container/pods due to the lack of kubelet checkpointing. As the results, we have to handle label/annotation backward compatibility issues. Instead of doing that, we can just serialize the kubernetes pod/container objects and write it as annotations.

After discussing with @vishh and @dchen1107, we may also checkpoint the pod "status" (instead of just the spec), so that we can delete an container as soon as the new one starts.

There are two options:
1. Write the entire pod object (spec/status) to every container in the pod. This is easy to implement, and the last created container has the complete spec and status. 
2. Write pod spec/status to the pod sandbox (i.e., infra container for docker), and container spec/status to individual containers. This is cleaner in general.

@Random-Liu, feel free to grab this one since you were working on docker labels. 
@dchen1107, I marked this v1.3 tentatively.

/cc @kubernetes/sig-node

**Comment by Random-Liu** [comment]
Sure. Grab it! :)

**Comment by vishh** [comment]
* we should store the v1 Pod object
* we should see if we can store protos instead of json

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
Is the annotation updated on every sync or just on container creates?

**Comment by Random-Liu** [comment]
@derekwaynecarr At least docker label is immutable after container created, so the annotation should never been changed after container creates.

**Comment by dchen1107** [comment]
cc/ @yifan-gu for this change. 

This is just a temporary alternative solution of kubelet checkpointing. Other systems built upon Kubernetes shouldn't depend on the reliability of this.

**Comment by pmorie** [comment]
+1 to storing the protobuf serialization

**Comment by yifan-gu** [comment]
sgtm.

For option 2. Which part of the pod status will be serialized? @yujuhong @Random-Liu

**Comment by Random-Liu** [comment]
@yifan-gu All except the container status?

**Comment by vishh** [comment]
@Random-Liu Any updates on this feature?

**Comment by Random-Liu** [comment]
@vishh Will work on this late this week.

**Comment by Random-Liu** [comment]
Offline discussed with @yujuhong and @vishh , we decided to serialize an internal versioned object containing only necessary information instead of the api.Pod object, because:
1) We can not serialize only container spec or status with the current runtime serializer, because the serializer can only serialize the whole `runtime.Object`.
2) If we serialize the whole api.Pod into each container, because labels are immutable, in fact only the label on the newest container has the newest and useful api.Pod.
We could go with 2), but the implementation would be a bit wired and ugly.
So at last, we decided to define an internal object with dumb version control, and serialize the internal object instead of the whole api.Pod.

**Comment by yujuhong** [comment]
> We could go with 2), but the implementation would be a bit wired and ugly.

Just wanted to add that the pod spec written on the container may be outdated, and we don't want people to start relying on it.

This would be much simpler if annotations are mutable or if we can checkpoint somewhere else...

**Comment by dchen1107** [comment]
This is not required for 1.3 release at all. Pending pr requires more thoughts. Punt for next release.
