### ISSUE TITLE
How to get the associated pod name of completed Job?

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubernetes/kubernetes#24709]
Hi,
I want to get the pod name of a completed job, so I can query the log from k8s API or elasticsearch matching the pod name. But seems I can only find the pod name in the job's event, is there any better/easy approach to achieve this?
Thanks a lot!

**Comment by thockin** [comment]
Kubectl get pods --show-all ?

**Comment by nkwangleiGIT** [comment]
@thockin, thanks for quick response.
But I want to get the associated Pod of a Job using API, in Job documentation, I can see your answer:
`kubectl get pods --show-all`
But it'll list all pods, I only want to get the associated Pods of a Job, and use k8s REST API, any other approach? thanks!

**Comment by soltysh** [comment]
@nkwangleiGIT the best option for you is to get the selector of pods creating a job (`.spec.selector`) based on that you can get a list of pods associated with a job. This is how k8s is getting the pods as well.

**Comment by nkwangleiGIT** [comment]
@soltysh, thanks for your comments. 

Yes, for now, I'm using Lable to match the pods of Job, as they should have the same lablel.

I'm cloing this issue, thanks all!

**Comment by yanqd0** [comment]
By default, there is a label named 'job-name' in every Pod triggerred by a Job.

```sh
kubectl get pods --selector=job-name=YOUR_JOB_NAME
```
