### ISSUE TITLE
Add ability to assert container ready-ness on rolling-update via scripted check

### ISSUE THREAD

**Issue by srcspider** [kubernetes/kubernetes#24712]
Right now the only thing preventing a container that's not ready from being served to is an update period set on rolling-update (as far as I'm aware). While this (mostly-)works, it's not ideal.

 - for containers that can start almost instantly the timer simply makes the rolling-update take unnecessarily long (potentially minutes, due to other containers needing minutes to be safe).
 - for containers that can have potentially long running startup checks this can prove troublesome even if set to relatively long period since the checks may find and try to fix some "major" problems (eg. bad permissions on a mounted file system with a lot of files)
 - it's sometimes just as important for the deploy to happen ASAP (especially in the aftermath of a bad deploy) as it is for the deploy to happen safely. In combination to the previous point, doing it with a timer may potentially be the worst way to go about it for such cases.

The simplest way (IMO) to get around this is to provide a way for pods to specify an `assert` command. When kubernetes sees the `assert` field present for the image it ignores timers when performing `rolling-update` or any other operation that involves creating a container. Instead it creates the container simply runs: `docker exec -it [containerId] [assert]` periodically and waits for a response.

The semantics of the response are not very important, but let's assume kubernetes expects a json with `status` field of "ready" and an optional `message` field which it pastes in it's log whenever it receives it. If it doesn't get a json or gets a status that's not "ready" it just logs it to the pod startup and tries again later.

There's no reason to support anything more then one assert script since the container itself can just aggregate multiple assert scripts into one easily.

By having asserts deploys can happen as-fast as the image can start, and there's also no risk of containers that are not *truly* ready prematurely replacing good containers due to bad estimations on the update period timer or otherwise unexpected long startup processes occurring.

**Comment by janetkuo** [comment]
@kubernetes/kubectl

**Comment by smarterclayton** [comment]
Can you identify how you think the existing readiness check (which gates rollout today) would play into the proposed "assert"? I.e. when would someone use a readiness check and when would someone use this new assert check?

**Comment by thockin** [comment]
I really don't understand how this is different from readiness...

**Comment by nikhiljindal** [comment]
Yes `--update-period` is to control the rate of rolling update. Default is 1 min. You can set it to 0 for an ASAP update.
Are you suggesting changing the default to 0?

We have now introduced [deployments](http://kubernetes.io/docs/user-guide/deployments/) which provide server side rolling update. The corresponding parameter in deployments is `MinReadySeconds` and the default value for that is 0.
Deployments is still in beta and would love your feedback on any changes. Changing default `kubectl rolling-update` behavior is tricky since it can lead to unexpected changes for many users.

Re: assert, as others have pointed out, we have readiness checks which might be what you are looking for. 
http://kubernetes.io/docs/user-guide/production-pods/#liveness-and-readiness-probes-aka-health-checks has more info. Readiness checks are in pod definitions tough.

**Comment by srcspider** [comment]
@nikhiljindal 
> Yes --update-period is to control the rate of rolling update. Default is 1 min. You can set it to 0 for an ASAP update. Are you suggesting changing the default to 0?

No. I'm not.

The problem is with this assumption that you can set a time. There is no such thing as "startup" will only take 1 minute. You can certainly _design and intend_ for it to be be less then 1min, but the real world isn't always so forgiving as to give you what you want. You should basically always assume the time your container might take to get ready is: `sleep(rand(0, end_of_time))`. You can see how this is a problem when kubernetes tells you to specify a fixed time after which it just throws it out into the world.

@smarterclayton
> Can you identify how you think the existing readiness check (which gates rollout today) would play into the proposed "assert"? I.e. when would someone use a readiness check and when would someone use this new assert check?

If both are present, both would need to be true. But if `assert` is present, unless there's other containers that do not specify `assert`'s, then the `update-period` would be ignored.

If you have a container with an `assert` and a container with out one then the behavior should be: update-period becomes "minimum time" and kubernetes needs to ensure the assert passes too before it can move forward.

@nikhiljindal
> We have now introduced deployments which provide server side rolling update. The corresponding parameter in deployments is MinReadySeconds and the default value for that is 0.
Deployments is still in beta and would love your feedback on any changes. Changing default kubectl rolling-update behavior is tricky since it can lead to unexpected changes for many users.

I don't think deployments actually affect this. I haven't looked into deploys too deeply (currently a bit shy with new features due to all the problems that seem to be happening lately between minor versions). If there's something other then ready seconds which has the same issue as mentioned above, let me know.

@nikhiljindal
> Re: assert, as others have pointed out, we have readiness checks which might be what you are looking for.
http://kubernetes.io/docs/user-guide/production-pods/#liveness-and-readiness-probes-aka-health-checks has more info. Readiness checks are in pod definitions tough.

I wasn't aware of this, and I could (probably) make it emulate the behavior I need but... I have a few problems with this. **The first, and biggest problem, is that it's clearly NOT designed for what I need.** It's designed to be a simple "server is up" and as such if I use it I'd rather actually tie it to the actual server when applicable, not to a random port connecting to a random server who's only purpose is to run a script. Because if I do, who's to say you're not going to completely break _everything_ by adding restrictions and "features" relevant to "server is up" functionality. Much like it happened recently with the restriction on only being able to update with the same image.

This leads into the second problem with this... _why do I need a server for this?_ 

Kubernetes can very easily run a script as root. Kubernetes is trusted, the pod definition is trusted, and the image contents are trusted. So everything is perfectly safe and simple to use. Setting up a server on the other hand, involves listening to a port (or 80 which is probably a bad idea). In addition the server is probably your default server, again a bad idea since when using selinux for example it involves assigning various security roles the server shouldn't have to be able to run the scripts in question. Or, alternatively you have _another_ server that runs next to your server who again has these potentially dangerous security rules associated with it. Or, in the worst case your pod doesn't need a server at all, but you have to inject all the required server packages and architecture in it, because kubernetes needs it.

I mentioned earlier that I would rather use this probe feature (when kubernetes versions stabilize a bit) only for the purpose it's intended to fix, even if it _could_ be hacked into an assert. This is not directly related, but "being in a usable state" and "being in a ready state" is not really the same thing. For example, to achieve fast deploy times, as much startup checks (and potential system fixes) are off-loaded to background processes; primarily to safeguard against the failings of only having a time limit on the kubernetes side. That state where the server is "up" but hasn't figured out yet if it's "100% okey" yet is a state where a "server probe" check will report "ready" but an assert would report "not ready." Because, and opinion my vary on this, I'd rather one small part of the system report `503` (in case it "doesn't go as planned") then everything report `503`. It's not great, and I'd rather avoid it, but usually works out since the troublesome parts are usually not very used parts.

**Comment by smarterclayton** [comment]
If you want fast deploys, that's what the percentages on the rolling
deployment are intended for - surge, and maxUnavailable.  You can set surge
to 100% and we will only wait for readiness before removing the old items -
i.e. we would *instantly* create a full new set of pods, then remove old
ones as the readiness checks go live.

Readiness is a very precise decision today - "should this be included in
load balancers".  Since rolling updates are about adding items to load
balancers predictably, that's what we gate on.

You can have readiness checks that run exec in the container - so you
shouldn't need a server.

**Comment by kargakis** [comment]
readinessProbe.exec.command is probably what you need to specify

https://godoc.org/k8s.io/kubernetes/pkg/api/v1#ExecAction

**Comment by srcspider** [comment]
@kargakis wasn't aware of that one. Thank you.

Closing.
