### ISSUE TITLE
kubelet fails cadvisor stats summary

### ISSUE THREAD

**Issue by Jackong** [kubernetes/kubernetes#24713]
`E0424 04:07:05.023414       1 summary.go:114] error while getting metrics summary from Kubelet: request failed - "500 Internal Server Error", response: "Internal Error: non-existent label \"root\""`

The same as https://github.com/coreos/bugs/issues/1225

**Comment by timstclair** [comment]
Sounds like this should be fixed with the cAdvisor Godeps bump in https://github.com/kubernetes/kubernetes/pull/24113

**Comment by timstclair** [comment]
@Jackong Are you able to reproduce this at HEAD anymore?

**Comment by Jackong** [comment]
@timstclair How to use HEAD image: gcr.io/google_containers/hyperkube-amd64:<TAG>?

**Comment by olalonde** [comment]
Seeing a similar error in my logs:

```json
{"log":"E0809 04:34:05.009539       1 summary.go:114] error while getting metrics summary from Kubelet: request failed - \"500 Internal Server Error\", response: \"Internal Error: unable to find data for container /docker/571f771e787e2325ed487c5a2f37940e5d7a26c2455a3533e0b06bdf5cccb872\"\n","stream":"stderr","docker":{"container_id":"ac2dc20bf16ce97a0c79d91717b7d067535d4e9289fb433bc61910d137da5639"},"kubernetes":{"namespace_name":"kube-system","pod_id":"7aa4ed88-57f9-11e6-a5e2-068755380eff","pod_name":"heapster-v1.0.2-2148290995-82low","container_name":"heapster","labels":{"k8s-app":"heapster","pod-template-hash":"2148290995","version":"v1.0.2"},"host":"ip-172-20-0-131.us-west-1.compute.internal"}}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
```

**Comment by timstclair** [comment]
@olalonde It was fixed in Kubernetes 1.3, but the fix involved an API change and couldn't be cherrypicked to 1.2.x

**Comment by olalonde** [comment]
@timstclair thanks

**Comment by spzala** [comment]
@Jackong hello, since it's long time this issue was discussed last time, a gentle touch base - seems like it's resolved and if that's case, it would be great if you close the issue? I don't know the exact steps to recreate/verify it but I could see stat fine with latest minikube.  Thanks! /cc @timstclair
