### ISSUE TITLE
Error 'endpoints kubernetes-dashboard not found' launching docker cluster

### ISSUE THREAD

**Issue by gonfva** [kubernetes/kubernetes#24714]
When running Kubernetes locally using docker (http://kubernetes.io/docs/getting-started-guides/docker/) if I try to visit 

http://localhost:8080/ui

I get redirected to 

http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

And that shows an error page with the following text:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "endpoints \"kubernetes-dashboard\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "endpoints"
  },
  "code": 404
}
```

If I visit the URL 

http://localhost:8080/api/v1/proxy/namespaces/default/services/kubernetes-dashboard

the dashboard appears correctly. 

My understanding is that ui is expecting the namespace to be `kube-system`

https://github.com/kubernetes/kubernetes/blob/master/pkg/ui/installsupport.go#L28

But the default namespace for hyperkube is `default`

https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/options/options.go#L89

**Comment by deathtrix** [comment]
+1

**Comment by cheld** [comment]
hmm.. I can not fully reproduce this:

1. Create local cluster (http://kubernetes.io/docs/getting-started-guides/docker/)

2. Create kube-system namespace (kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/docs/getting-started-guides/docker-multinode/kube-system.yaml
)

3. Create dashboard as in readme (kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml)

4. Open browser http://localhost:8080/ui

=> works


But there are a few strange things, I agree.
1. why is hyperkube deployed to default namespace?
2. why is kube-system namespace not created?
3. should we add some add-ons to hyperkube by default or make it more easy to add them?


@fgrzadkowski, @luxas  Do you know if there are any reasons to keep the current behavior? Otherwise, I can have a look into it


CC @bryk

**Comment by luxas** [comment]
> 1. why is hyperkube deployed to default namespace?

fixed at HEAD. It doesn't matter much anyway, as they are static pods, not normal k8s objects

> 2. why is kube-system namespace not created?

it isn't but that's something I would like to fix

> 3. should we add some add-ons to hyperkube by default or make it more easy to add them?

Have been thinking about it, but it will probably wait before we see how `minikube` evolves.

**Comment by bryk** [comment]
@luxas Why is K8s dashboard deployed in `default` namespace? Is this something intentional? Or the namespace was just not specified?

Dashboard UI must be deployed in kube-system namespace in order to `/ui` redirect work.

**Comment by cheld** [comment]
@bryk The deployment of add-ons are not described in the guide (http://kubernetes.io/docs/getting-started-guides/docker/). I assume @gonfva deployed dashboard himself to default namespace. 

Everything is fine when using the docs and the provided yamls, but it is not convenient to find and collect all the information. 

So, I suggest to (more or less) automate the deployment of the most important add-ons (DNS, Heapster, Dashboard). Just waiting for some initial PRs to be merged.

**Comment by gonfva** [comment]
For the record, I didn't deploy the dashboard myself. As I mentioned, I followed the instructions in this page http://kubernetes.io/docs/getting-started-guides/docker/ for the stable release at that moment (1.2.x). That version deployed the dashboard (in the default namespace)

**Comment by luxas** [comment]
@bryk I talked about the master components, they were in the default ns until ~a week ago.
But that has nothing to do with dashboard.

@gonfva The docker guide does not deploy the dashboard automatically. It hasn't _ever_.
Look at the [source code](https://github.com/kubernetes/kubernetes/tree/master/cluster/images/hyperkube)

The only thing I can think of is that you had deployed the dashboard earlier (in the default ns) so it got stored in `/var/lib/kubelet`, and k8s spun up the containers again.

**Comment by luxas** [comment]
See #25196

**Comment by bgrant0607** [comment]
cc @vishh @dlorenc

**Comment by cheld** [comment]
Issue can be closed
