### ISSUE TITLE
base64 EncodeToString issue in RBD volume

### ISSUE THREAD

**Issue by xxyztwz** [kubernetes/kubernetes#24728]
I had read the code pkg/volume/rbd/rbd.go, line 88. 
```
for name, data := range secretName.Data {
	secret = string(data)   // line 88
	glog.V(1).Infof("ceph secret info: %s/%s", name, secret)
}
```

I have a question that in other volume like pkg/volume/flexvolume/flexvolume.go, they use `base64.StdEncoding.EncodeToString(data)` , so is there a bug in rbd volume? Or just I use the wrong way to connect to ceph with secret?

**Comment by mml** [comment]
- [rbd.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/rbd/rbd.go#L88)
 - [flexvolume.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/flexvolume/flexvolume.go#L120)

**Comment by nelcy** [comment]
@xxyztwz It is not a bug in rbd volume code.

flexvolume passes params to the backend driver in "json format". Kubernetes handles secrets in json in base64 encoding. To keep it consistent, we decided to keep the flex volume secrets in based64 encoding. Nothing wrong with the drivers.
