### ISSUE TITLE
deployment does detect pod/container failures for reasons other than `ImagePullBackoff`

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes/kubernetes#24726]
Steps: edit deployment and set image: to a "bad"-nonexistent image.
Results: deployments aborts with 1 pod down and remaining (2 - per update-demo example) up an running.
------
Steps: edit deployment and set image: to a "bad"-failing to start service image (for example w/ invalid configs, etc.)
Results: deployments proceeds despite the facts that service fails to start, leaving with with 0 - available pods.  
```
NAME                           READY     STATUS             RESTARTS   AGE
foo-3854944627-1aqxn         0/1       CrashLoopBackOff   3          1m
foo-3854944627-38fyx         0/1       CrashLoopBackOff   3          1m
foo-3854944627-3sp5i         0/1       Error              3          1m

NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
foo     3         3         3            0           1h
```
Expected: 1 pod is down and 2 available (just as with invalid-nonexistent image case).

**Comment by Raffo** [comment]
Same here, with a difference: I know that I can pull the image only from one node (private registry, credential available only on that node) and I would have expected the deployment to retry over and over again till it tries on that node. I have something like:


````
~ % kubectl get pods --watch
NAME                                    READY     STATUS             RESTARTS   AGE
private-image-test-1-1011904087-1zbhb   0/1       ImagePullBackOff   0          25m
private-image-test-1-1011904087-318th   0/1       ImagePullBackOff   0          25m
private-image-test-1-1011904087-amswl   0/1       ImagePullBackOff   0          25m
````

````
~ % kubectl get deployments
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
private-image-test-1   3         3         3            0           39m
````

Maybe there's something about Deployments I am missing? 

I'm running 1.2.2 on GKE.

**Comment by ichekrygin** [comment]
Update: after setting `minReadySeconds` (http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_deployment) this issue went away, which makes sense since the default value for `minReadySeconds` is 0. 

Feel free to close this this issue.
