### ISSUE TITLE
make update

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#24737]
Run ./hack/update-all.sh via make (`make update` or something)

Or switch `make check` to run those cc: @smarterclayton

**Comment by mml** [comment]
@kargakis some context would really help here.

**Comment by kargakis** [comment]
`make` is used for most of the development flow: build, test, verify. The only thing that seems missing is hooking up the update-all script which updates a bunch of generated code, docs, etc.

https://github.com/kubernetes/kubernetes/blob/master/Makefile
