### ISSUE TITLE
Scheduling predicates should handle volumes which are referenced through a PVC

### ISSUE THREAD

**Issue by swagiaal** [kubernetes/kubernetes#24738]
This is handled for direct volumes here: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L126
We need something similar for when volumes are accessed through PVC's and PV's

**Comment by mml** [comment]
What do you mean "cause an error"?  The predicate you link to is used in scheduling to avoid making certain scheduling decisions, but it doesn't cause an error.

**Comment by swagiaal** [comment]
I have updated the title. The predicate checks volumes which are specified in a pod and prevents scheduling of two pods which reference the same storage asset (where appropriate), but if I do the same thing through a PVC the scheduler is non the wiser. This is a reminder to address that

**Comment by jingxu97** [comment]
What is the status for this? From this doc https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/devel/scheduler_algorithm.md, it looks like we support a few validations for storage. Should we consider adding more validation to avoid system entering in a unexpected state which is hard to work on?
