### ISSUE TITLE
Process for keeping docs up to date

### ISSUE THREAD

**Issue by dlsniper** [kubernetes/kubernetes#24735]
Hi,

I'm trying to get started (again, new machine, workplace bla bla) with Kubernetes but so far the experience if nothing short but confusing. I was expecting to have a clear documentation for how to start on a Ubuntu machine but in turn I can't find anything that correctly replicates the real life (especially since I can't remember what arcane stuff I've done the previous time to get it working).

I've spent more than an hour figuring out how to boot up the thing locally on my Ubuntu machine and I'm still not sure if I've understood how to do it.

I appreciate that the pace of development is fast and things move a lot but that's exactly why such a process must enforce that documentation matches what's in the code and the other way around.

If you look at other projects, the usually have a development period and a cool down period in which various features are documented and bugs are ironed out.

Also, any change that affects the users in terms of getting started should be accepted only if they provide the changes for the documentation as well.

Finally, no release should be done if there are still pending documentation issues that have not been sorted out as that leads to the current case where documentation is P2 or P3 or whatever P that's not critical for doing a release.

Please take a bit of time to improve experience for users as it's a pity to have an awesome project with a less than ideal documentation.

Thank you.

**Comment by mml** [comment]
@bgrant0607

**Comment by dlsniper** [comment]
I've opened this: https://github.com/kubernetes/kubernetes.github.io/pull/454 as a first step for this.

**Comment by bgrant0607** [comment]
@dlsniper The biggest problem with Ubuntu (on bare metal?) is that nobody supports it. As an open-source project, we rely on the community to support what they contribute, but it doesn't always happen. 

The matrix of support levels is here:
http://kubernetes.io/docs/getting-started-guides/#table-of-solutions
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/index.md

We're discussing putting an owner and date of last update on each doc to provide a clearer indication of which docs may be out of date.

cc @kubernetes/docs

**Comment by bgrant0607** [comment]
The feature-tracking proposal is somewhat related:
https://github.com/kubernetes/features/pull/1/files

We're also working on overhauling the docs:
https://docs.google.com/document/d/12Nfj2E8tZL-CMnnpkSH9m5k_oqd4qJh4qDwYDxPGJJI/edit?ts=5705b1fc#

**Comment by dlsniper** [comment]
Any updates on this?

**Comment by dlsniper** [comment]
First of all, @fejta-bot you're rotten, not the issue.
Second of all, the k8s documentation is still the worst I've seen.
Third of all, if someone says that I should fix it given how this is open-source and all that fluff, I would kindly invite you to get me hired at one of the companies that actually develop k8s and pay money to get people to "open-source develop" it, and I'll be happy to write your documentation "for free".
Fourth of all, I've stopped using k8s altogether because of this, Nomad is much better at actually running and providing documentation for itself.
Fifth of all, GG k8s leadership for addressing the most critical part of your project with such a poor response, guess that rotten label should be applied to your processes and priorities as well.

**Comment by castrojo** [comment]
The kubeadm documentation has been updated since the original issue was filed and works fine on Ubuntu, have you seen: https://kubernetes.io/docs/setup/independent/install-kubeadm/

**Comment by zacharysarah** [comment]
@dlsniper 👋 I see you opened this issue in April of 2016. Twenty-one months is a long time for a substantive reply. I'm sorry your wait has been so long. The CNCF hired me in November to help manage documentation. My goal is that others will not have to repeat your experience.

> I've stopped using k8s altogether because of this

I hear your frustration. Kubernetes is complicated to use, and the documentation sometimes does little to help, especially for beginning users. For Ubuntu specifically, @castrojo's comment ☝️ about kubeadm hopefully addresses your original concern.

SIG Docs is actively working on a better, smoother experience with documentation: [user journeys](https://github.com/kubernetes/website/pull/4630), currently on track for release in Q1. You can also see improvements planned for the coming year in [this tracking issue](https://github.com/kubernetes/website/issues/6935). These aren't immediate fixes, but then, the problem wasn't created immediately, either. We see the problems with K8s docs, we're frustrated by them too, and we're actively working to make them better.

> the k8s documentation is still the worst I've seen.

Personally, [Apache Lucene](https://lucene.apache.org/core/7_2_1/index.html) still takes the prize.
