### ISSUE TITLE
[RFC] Eliminate retry operations in volume code and rely on pod sync

### ISSUE THREAD

**Issue by swagiaal** [kubernetes/kubernetes#24747]
Several of the volume plugins have retry logic around attaching volumes, watching for devices, getting the cloud provider etc.

What do you guys think of eliminating all of these and relying on the pod sync loop to do retries when needed. It would make for cleaner code I think but I was wondering if you guys have run into use cases which require the tight loop retries.

@jsafrane @saad-ali @justinsb

**Comment by saad-ali** [comment]
This should naturally fall out of the mount/unmount refactor: specifically I think the existing retries are there mostly to be able to handle the "wait for attach/detach" cases. Once that logic is factored out, then, if the wait for attach times out, or the mount fails, etc. it would be ok to fail and let the volume manager handle retrying.

**Comment by jsafrane** [comment]
I like the idea, although I am not sure about pod sync interval - it takes ~20 seconds after `volumePlugin.SetUp()` finishes and before next `SetUp()` call. Should it be faster?

**Comment by justinsb** [comment]
For AWS, I concur with what @saad-ali said: we primarily (only?) use it for waiting for attach/detach; it's not ideal but that's what the original interface supported.  Moving that retry logic up a layer would likely be an improvement - if we time out on an attach/detach we could be in a bad state and we have no way to surface that currently.
