### ISSUE TITLE
Test Flakes: Measure flake rate per-test

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24758]
We should track, for each test, the number of runs and the number of failures. There should be a way of indicating "this test was fixed, start again from zero". We need this data to help people prioritize which flakes need to be fixed most urgently. We can also use this data to help determine whether a failure is due to a test infrastructure failure or whether it is due to an individual test being flaky (#24755).

This should be visible in a dashboard somewhere, and it should be machine-queryable at least from whatever component is filing/assigning flaky test issues.

Part of #24753

**Comment by bgrant0607** [comment]
I think we want rates over past day, 3 days, week, month.

A super-dense graph showing the individual successes and failures, with links to test artifacts, similar to our internal test dashboard, would be super-useful, also.

**Comment by spxtr** [comment]
[This page](http://storage.googleapis.com/kubernetes-test-history/static/index.html) is a start. It shows the pass/fail rate of merge-queue blocking tests for the last 24 hours.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/sig testing
We do something like this with our [wall of shame](http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1)

We only display this for presubmit test failures.  I would be interested in doing the same for postsubmits
