### ISSUE TITLE
Test Flakes: Individual test owners

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24754]
Implement a system of ownership for tests.

A test owner should:
* Fix the test in a reasonable amount of time if it is broken.
* Fix the system in a reasonable amount of time if the system is causing the test to fail.
* Drive the test into a non-flaky state, if the test is broken for reasons beyond the owner's control.
* Rewrite poorly designed tests.
* Move tests into the smallest framework possible.

A test owner should NOT:
* Fix parts of the system they have little experience with-- file a bug against the relevant people.
* Fix test infrastructure which is breaking multiple tests. We will do our best to avoid incorrectly filing such issues against individual test owners, but should one slip through, the test owner should contact the test-infra team. We don't want 10 individual test owners all working on the same thing at the same time!
* Paper over system issues by e.g. extending timeouts.

Test ownership can be accomplished in multiple ways. It needs to be machine readable, so that we can use it for assignment and in the OWNERs system. Worst case, we can split out the tests into separate files and do per-file owners.

Part of: #24753

**Comment by fejta** [comment]
Please see https://groups.google.com/d/msg/kubernetes-dev/Cq7rrGIbQ8w/2vES0WZ9AwAJ and sign up to maintain your favorite tests!

**Comment by lavalamp** [comment]
Thanks @rmmh and @fejta!
