### ISSUE TITLE
Test Flakes: Measure API coverage

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24763]
We want to measure our test coverage of the API surface area.

This could involve scraping apiserver's logs and looking at the paths. We can talk about the best way to find all the things that _should_ be called.

Part of #24753

**Comment by oomichi** [comment]
Through the design discussion[1] of the measuring tool, we have a consensus to implement it on test-infra repo. Then I created another issue (https://github.com/kubernetes/test-infra/issues/5701) on test-infra side and this can be close.

[1]: https://docs.google.com/document/d/1Upo8lTeR7gy4olD6hASTCdn8Vy7WuDwkO_o9Y5nrxhs/edit#

**Comment by oomichi** [comment]
This can be closed because the test-infra one is closed now and we have API coverage measuring tool in test-infra
