### ISSUE TITLE
ContainerManager system validation fails when running Kubelet in hyperkube container via rkt

### ISSUE THREAD

**Issue by activeshadow** [kubernetes/kubernetes#24767]
I'm running Kubernetes on CoreOS and using the `kubelet-wrapper` script provided by CoreOS to run the `kubelet` on my minions. When I pass the `--containerized=true` option, I get the following error from the `kubelet`:

```
kubelet-wrapper[1277]: I0425 22:47:26.061605    1277 kubelet.go:2365] skipping pod synchronization - [Failed to start ContainerManager system validation failed - open /rootfs/proc/mounts: no such file or directory]
```

I'm wanting to mount NFS shares into pods, which works when I use the native `kubelet` app that CoreOS provides (`v1.1.2`), but doesn't work when I use the `kubelet-wrapper`. After some digging, I'm thinking I need to pass the `--containerized=true` option to the `kubelet-wrapper` (to pass through to the `kubelet` container `rkt` is running) in order to get the NFS persistent volumes working.

**Comment by dchen1107** [comment]
cc/ @yifan-gu

**Comment by yifan-gu** [comment]
cc @pbx0 @aaronlevy

**Comment by aaronlevy** [comment]
@activeshadow: When running the via the kubelet-wrapper, you do not need to use the `--containerized` flag. We don't actually mount / at /rootfs (which the `--containerized` flag expects).

Resolving the NFS mount issue is a little trickier, and is being tracked here: https://github.com/coreos/coreos-kubernetes/issues/372

I've also just opened a PR to start adding the NFS utils to the coreos-hyperkube image: https://github.com/coreos/kubernetes/pull/36
