### ISSUE TITLE
Test Flakes: Measure time spent by PRs in the submit queue

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#24762]
The heading is pretty self explanatory. The stop-watch starts when the test is both LGTM'd _and_ the PR tests have passed. The stop-watch stops when the PR is merged. We can stuff this information in the same place we store test flake rates.

Part of: #24753

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/contrib/issues/869

**Comment by eparis** [comment]
from the first LGTM or the last LGTM?

**Comment by spiffxp** [comment]
/remove-lifecycle stale
There is https://k8s.devstats.cncf.io/dashboard/db/time-metrics?orgId=1 but it's not something we can alert on
/sig testing
Presumably we would expect this go down over time as we transition from mungegithub to tide
