### ISSUE TITLE
Daemonset Example not working

### ISSUE THREAD

**Issue by prashantchitta** [kubernetes/kubernetes#24770]
I am using this example to create Daemonset
https://github.com/kubernetes/kubernetes/blob/release-1.2/examples/cassandra/cassandra-daemonset.yaml

It was working fine in 1.1. But in 1.2 its not working. Daemonset gets created, but the pods are not being created. When i do describe of daemonset, i see following info.

```
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Misscheduled: 0
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Reason		Message
  ─────────	────────	─────	────			─────────────	──────		───────
  16s		16s		1	{daemonset-controller }			SelectingAll	This controller is selecting all pods. Skipping sync.
  15s		15s		1	{daemonset-controller }			SelectingAll	This controller is selecting all pods. Skipping sync.
  16s		9s		3	{daemonset-controller }			SelectingAll	This controller is selecting all pods. Skipping sync.
```

I see that this fix was causing the error message "This controller is selecting all pods". This fix was done in 1.2
https://github.corp.ebay.com/tess/kubernetes/commit/3c14a6da0a0b1c785e3583d86ed58c63941e11bc#diff-4ab5e087aeafb461a3cc1856c353165bR629

@mikedanese I see that this PR belongs to you. Any idea if you can update the example? It would be great if you can let us know what the fix is

**Comment by mikedanese** [comment]
As part of upgrading to v1.2, you need to delete all DaemonSets and Deployments then recreate them. This is documented in the release notes "actions required". We say there is a possibility that this will happen if you use alpha features. Please read the section about DaemonSets:

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md/#action-required-2

**Comment by prashantchitta** [comment]
It worked. Thanks @mikedanese. Updating my kubectl to server version 1.2 fixed the issue.
