### ISSUE TITLE
DNS stopped working inside Kubernetes

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#24779]
We have a Kubernetes cluster running inside GCE for some time using the official scripts. Today the DNS stopped working. If I try to ping google.com from inside a pod, it will not resolve google.com. DNS was working properly in pods create before today. After we restarted the DNS pods in kube-system, DNS started working in newer pods again. How do we debug and fix issues like this?

Thanks.

**Comment by thockin** [comment]
GCE with OSS or GKE?  It might be hard to post-mortem, but logs would be
the first best clue.  I am out of office, so please pardon my latency

**Comment by codefx9** [comment]
It is GCE with OSS. We checked the logs for DNS pods. Nothing looked suspicious.

**Comment by talk2vino** [comment]
I have the similar issue in #24734 . 

Just curious to know how to restarted the DNS pods in kube-system ?

**Comment by codefx9** [comment]
I just deleted the DNS pod using `kubectl delete pod <dns-pod-name> --namespace=kube-system`. DNS rc then restarts the pod.
