### ISSUE TITLE
flake: TestGetPodsToSync failed

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#24788]
I just run `./hack/test-go.sh` against the master branch code, and see errors below:

```console
$ ./hack/test-go.sh
...
--- FAIL: TestGetPodsToSync (0.00s)
	kubelet_test.go:4467: expected 3 pods to sync, got 2
...
```

The test case is here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_test.go#L4418-L4469 

/cc @Random-Liu

**Comment by Random-Liu** [comment]
@zhouhaibing089 Thanks, will look into it.

**Comment by zhouhaibing089** [comment]
@Random-Liu thank you.. does it matter with the node configuration(high mem or more CPU)?

**Comment by Random-Liu** [comment]
@zhouhaibing089 That test is bad, :(
I use the real clock in the unit test, so I could imagine that in some extreme situation the test may fail.

**Comment by zhouhaibing089** [comment]
@Random-Liu it does not happen frequently though. :)

**Comment by zhouhaibing089** [comment]
@Random-Liu I see your point, The tests *always*(haven't see error until now) get passes when I run it on my local machine, it did happen on virtual machines, I think that's the problem what you said about the clock.
