### ISSUE TITLE
flake: TestFreeSpaceImagesInUseContainersAreIgnored failed

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#24784]
I pull the latest master code, and run `./hack/test-go.sh` on ubuntu 14.04, however it failed, and the error I observed is:

```console
$ ./hack/test-go.sh
...
I0426 00:38:43.902969    1459 image_manager.go:282] [ImageManager]: Removing image "image-0" to free 1024 bytes
I0426 00:38:43.903046    1459 image_manager.go:282] [ImageManager]: Removing image "image-1" to free 2048 bytes
--- FAIL: TestFreeSpaceImagesInUseContainersAreIgnored (0.00s)
        Error Trace:    image_manager_test.go:237
	Error:		Not equal: 1024 (expected)
			        != 3072 (actual)

        Error Trace:    image_manager_test.go:238
	Error:		"[]" should have 1 item(s), but has 0
...
```

The test case is:

```go
func TestFreeSpaceImagesInUseContainersAreIgnored(t *testing.T) {
	manager, fakeRuntime, _ := newRealImageManager(ImageGCPolicy{})
	fakeRuntime.ImageList = []container.Image{
		makeImage(0, 1024),
		makeImage(1, 2048),
	}
	fakeRuntime.AllPodList = []*container.Pod{
		{
			Containers: []*container.Container{
				makeContainer(1),
			},
		},
	}

	spaceFreed, err := manager.freeSpace(2048, time.Now())
	assert := assert.New(t)
	require.NoError(t, err)
	assert.EqualValues(1024, spaceFreed)
	assert.Len(fakeRuntime.ImageList, 1)
}
```

According to the logs, when it tries to free 2048 bytes space,  `image-0` and `image-1` get both removed, while only `image-0` is expected.

/cc @yujuhong @feiskyer @vmarmol

**Comment by zhouhaibing089** [comment]
This could be reproduced by running `godep go test k8s.io/kubernetes/pkg/kubelet -v` multiple times though, @yujuhong would you mind help a little bit here?

**Comment by zhouhaibing089** [comment]
FYI, I am running this test on a VM, if that matters.

**Comment by yujuhong** [comment]
I looked at the code and the test compares the time when calling freeSpace and the time when scanning the images (i.e., detected time). See the code [here](https://github.com/kubernetes/kubernetes/blob/641ba92aa375b84fdfbc020e890aa961956b6e33/pkg/kubelet/image_manager.go#L270).

In your case, maybe the two timestamps are the same?

Change the line of code to
```
if !freeTime.After(image.lastUsed) {
```
and see if the test still fails.

**Comment by zhouhaibing089** [comment]
Cool, now it show passes every(six times continuously). Unit test works normally on a bare metal while flakes on VMs, and it should be a clock issue as @Random-Liu pointed out at #24788

**Comment by zhouhaibing089** [comment]
So curious about this phenomenon, we are running kubernetes on VMs managed by openstack, does it mean that we may encounter real issues related with clock even if the probability is extremely low?

/cc @ashw7n @chengyli

**Comment by Random-Liu** [comment]
@zhouhaibing089 At least for #24788, the flake should only happen when the clock goes very slow. :)

**Comment by yujuhong** [comment]
It's better for the tests to use a fake clock instead.

The unit tests use mocked out components (e.g., container runtime). In a real cluster, the operations will take much longer and it's very unlikely that the same error would happen. That said, we can fix the code to allow equality to ensure this wouldn't happen.

**Comment by zhouhaibing089** [comment]
@yujuhong thanks! we really really hope that tests could be running stable on VM.. if allow equality is reasonable, I will submit a fix for this.
