### ISSUE TITLE
AWS does not detach volumes that timed out

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#24807]
AWS cloud provider & volume plugin leaves EBS volumes attached when `AttachDisk` call times out.

Sequence is like this:
1. user creates a pod that uses EBS volume. The request goes through kubelet and AWS volume plugin  `SetUp()` call to [attachDiskAndVerify](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/aws_ebs/aws_util.go#L170).
2.  `attachDiskAndVerify` periodically calls `AWS cloud provider.AttachDisk()`, which issues `AttachVolume` API call to AWS.
3. When AWS is really busy, this call times out and `attachDiskAndVerify` gives up trying to attach the volume. Note that nobody "cancels" the API call to AWS (is there a way to do that?).
4. AWS **is still trying to attach the volume and it will succeed eventually**, but the volume plugin has given up waiting. This is good when the pod still lives - next kubelet sync loop will continue trying to attach the volume. On the other side, when the pod is deleted in the meantime, **nobody will detach the volume**. Kubelet does not know about it (last `SetUp()` failed).

I am able to reproduce this bug "pretty reliably" (>10%) by creating 50 pods (1 volume each) on a single-node cluster. Scheduler starts only 39 pods, leaving 11 Pending. When these 39 pods are Running, I delete them. Now the kubelet detaches 39 old volumes and attaches 11 new ones, making everything very very slow and one of the attach calls times out. When I delete these 11 new pods at the right time, sometimes I get an orphan volume attached to the node.

I have no idea how to fix it properly though. Should there be a standalone cleanup goroutine in AWS cloud provider that would detach these orphan volumes? Should we refactor AWS volume plugin to do proper `TearDown` of volumes that were attached, but not mounted properly? Both are quite lot of work and seem error prone to me and we have a real bug that needs to be fixed, even before attach controller is merged.

@justinsb, @swagiaal, any ideas?
@saad-ali, can the same happen for GCE PDs? The code has very similar structure, I did not check it though. Maybe GCE is faster and it does not time out.

**Comment by saad-ali** [comment]
For https://github.com/kubernetes/kubernetes/issues/20262 I am planning to have the controller reach out to cloud providers to figure out exactly which volumes are attached to which nodes. This mechanism can detach such orphaned volumes.

**Comment by msau42** [comment]
@jsafrane can this be closed?

/sig storage

**Comment by jsafrane** [comment]
yeah, let's close it. I don't remember seeing it lately
