### ISSUE TITLE
when finished rolling-update, couldn't know old pods names 

### ISSUE THREAD

**Issue by keontang** [kubernetes/kubernetes#24805]
Although we have elasticsearch to store pod logs, if one didn't list pods before rolling-update, it's a bit painful to find historical pod logs. It's better if we print old pods names and new pods names during rolling-update, so pod names can be traced.

For example, it's hard to find logs of my-nginx-xxxx in the following example.

```
root@master-1:/home/vagrant# /opt/bin/kubectl rolling-update my-nginx -f ./nginx-rc-new.yaml
Created my-nginx-v4
Scaling up my-nginx-v4 from 0 to 2, scaling down my-nginx from 2 to 0 (keep 2 pods available, don't exceed 3 pods)
Scaling my-nginx-v4 up to 1
Scaling my-nginx down to 1
Scaling my-nginx-v4 up to 2
Scaling my-nginx down to 0
Update succeeded. Deleting my-nginx
replicationcontroller "my-nginx" rolling updated to "my-nginx-v4"
```

If rolling-update output can list the names of the pods went down and the names of the pods going up, then we can check all the logs from the elasticsearch by pod name.

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by kargakis** [comment]
It would be nice to be consistent with the output from create/delete. For example, the log above should be something like:
```
Created my-nginx-v4
Scaling up my-nginx-v4 from 0 to 2, scaling down my-nginx from 2 to 0 (keep 2 pods available, don't exceed 3 pods)
Scaling my-nginx-v4 up to 1
pod "my-nginx-v4-aaaa" created
Scaling my-nginx down to 1
pod "my-nginx-fhdsh" deleted
Scaling my-nginx-v4 up to 2
pod "my-nginx-v4-bbbb" created
Scaling my-nginx down to 0
pod "my-nginx-34532" deleted
Update succeeded. Deleting my-nginx
replicationcontroller "my-nginx" rolling updated to "my-nginx-v4"
```

**Comment by kargakis** [comment]
Clsoing this in favor of the Deployment API

If you wish to associate old pods with logs you can use the existing replica set names as prefixes.
