### ISSUE TITLE
PreStop HttpGet Hook Not Honored by Kubernetes

### ISSUE THREAD

**Issue by yongk802** [kubernetes/kubernetes#24803]
It looks like at some point the preStop hook stopped working for httpGet. I say this because it looks like it used to be supported according to some PRs I've seen and documentation I've found here: 

```
http://kubernetes.io/docs/user-guide/container-environment/#container-hooks
```

However, I cannot get it to work. The exec directive seems to work just fine though. Below is the relevant part of the configuration:

```
    "containers": [{
        "name": "vertx-docker-example-fabric",
        "image": "vertx/vertx3-example-fabric8",
        "ports": [{
            "name": "http",
            "containerPort": 8080,
            "protocol": "TCP"
        }],
        "lifecycle": {
            "preStop": {
                "httpGet": {
                    "path": "/v1/close",
                    "port": 8080
                }
            }
        }
    }]
```

Here is the version output from our Kubernetes implementation as well:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0+5cb86ee", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"not a git tree"}

Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0-36-g4a3f9c5", GitCommit:"ef1caba", GitTreeState:"not a git tree"}
```

I can curl the endpoint above just fine from outside of Vagrant as well as inside Vagrant and inside the container itself, (using nodeports from outside) so I know the endpoint itself is available. It just seems that Kubernetes never sends this GET request when shutting down a Pod.

Can someone verify that this does or does not work?

Thanks!

Yong Kim

**Comment by dgaviola** [comment]
This is also affecting us. We cannot make Kubernetes sends us the preStop HTTP GET request. We are using Google Container Engine with versions 1.2.3 for master and 1.2.2 for nodes.

**Comment by dgaviola** [comment]
Finally we got it working. We had to define preStop and postStart, even when we were not using postStart. That solved our problem at least.

Still we think this is a bug as it doesn't make much sense and it is not documented.

**Comment by chees** [comment]
We're also running into this. Did you ever find a solution for this?

**Comment by crunchie84** [comment]
I have currently tried:
- `preStop` combined with `preStart` as suggested by @dgaviola -> preStop not executed
- used `exec` to execute curl instead of `httpGet` in the preStop event -> preStop not executed

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dgaviola** [comment]
@crunchie84 sorry, at the end that wasn't the issue. I think the problem was that the format of the URL wasn't correct. Not sure if there was a trailing slash or something else that was causing the issue, but when we changed the way we were putting the URL it started to work. However not sure if you are having the same issue.

**Comment by sbonar** [comment]
Has there ever been any movement on this?  I am also seeing this. I have an exec preStop configured and it never gets executed.  I am currently running 1.5.4

**Comment by ftripier** [comment]
Bump.

**Comment by PMende** [comment]
Any resolution to this? I'm current trying to get a `preStop` hook that will sync a particular directory in a container to a location on S3. The stop never runs, however. I can invoke the same command after doing a `kubectl exec -it ...` and it works just fine.

**Comment by micmax93** [comment]
For `httpGet` hook try setting path without leading slash, so `v1/close` instead of `/v1/close` - worked for us.

**Comment by Krizz** [comment]
> For `httpGet` hook try setting path without leading slash, so `v1/close` instead of `/v1/close` - worked for us.

Thank you @micmax93, this seems to have worked. 

Shouldn't this issue be reopened ?

**Comment by hmeerlo** [comment]
I want to bump this issue once again. I can not get the httpGet preStop hook to be executed whatever I do. I removed the slash from the URL but that didn't change anything. This is my config:
```
   lifecycle:
      preStop:
        httpGet:
          httpHeaders:
          - name: <redacted>-secret
            value: <redacted>
          path: system/shutdown
          port: 4859
          scheme: HTTP
```
