### ISSUE TITLE
Flake in k8s.io/kubernetes/pkg/controller/framework controller_test.go

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#24815]
Flake in unit tests in k8s.io/kubernetes/pkg/controller/framework

```
<testcase classname="framework" name="TestHammerController" time="0.850">
<failure message="Failed" type="">
controller_test.go:228: Expected HasSynced() to return true after the initial sync controller_test.go:283: got: map[string][]string{"default/七µA盻Y½褃怢釕b帙覘灜":[]string{"add"}, "default/ǅ隱ęp涓ǋ\"Ġ5c/":[]string{"add", "update"}, "default/ğ兵ǈ慢Ƴ营璜頿箭詔Ƥ簁+氏揊樧":[]string{"add", "update", "update"}, "default/ȑɿ剴c嵲ƙz0Ƈǝ奰ɾ哃?掀ǫ因ʞ蚭":[]string{"add"}, "default/ÿù甑ƅƼýgɦ":[]string{"add", "update"}}
</failure>
</testcase>
```

@deads2k somehow I know this is you :)

**Comment by deads2k** [comment]
> @deads2k somehow I know this is you :)

You're not going to believe this, but it's not.

@derekwaynecarr just because you'll find it amusing.

**Comment by smarterclayton** [comment]
You've corrupted him!

**Comment by derekwaynecarr** [comment]
@deads2k - you are not alone!

**Comment by hongchaodeng** [comment]
Happened again: [log](https://00e9e64baca09fbe31405bf7162dfcf15b24c6a75deefeb824-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F24455%2Fkubernetes-pull-test-unit-integration%2F23158%2Fartifacts%2Fjunit_v1,extensions-v1beta1,metrics-v1alpha1,federation-v1alpha1_20160427-164429.stdout?qk=AD5uMEuxt5tbb1eivL88UCDgQN5nJhyTXu-3izHjx6eN19jZgnBPNc0Uf5bWUwb1JZn5vaDF8v9h9eP6L5Wds5ymo0kVvetHZiors5G_iEh7f_LhN3RLuT0aCShhgtTd_fhUPkuWxwslI8tOBfl0D0cd-NsQdfCLkppLkGr3W-QXU28rUHXji8UruDu6BZgwdiXMDpRpLjPlavA_cOOqTb2TOG13TKapyEm-Gmrc7DIaW-cnx6RFTjqpANI7t_qSVak7KMumeTpoxDPOfovy4tsubI5Gv1fM_P0f_dfzM0aYsPurk4I4IVIzstevFKIAJ7Vc9vW7vEKAVqvQ5NquMZH1NHMK1cTOCRGhyC2gBYEZS6w-zsEvYir1MILvY0G_jJTNjwCHfJAmjsO2-5uTDvwnBvBRUf5OB4urMXv5Y2CP6K0tqJNSwfpfvgGUIq8SUi-pNxdW01pRyM06Q7oUWlo6-XkmBiCtA3mkxpnyKdyeieBzJDT1BtvKhxJYYTTbsJiCt1evn9QdiTXf-i-KxrK4sQICQsVA6uqEhajYZ5cEl3gP7SaPP_7q8dPlgawejKrJhi1Ww_35tYtS8Hr1sH2LS53HRkE7ziRIY9ITSGTQo2lKCjH84U1h_ytozhr1spQP9IbYR8wDt7vKnlyNBOiHacpyl3evBV7lXxap4B1B3zNUL0_eRvmIhaAFey_rbe2rZKcV5SGINMzeFB5Fe22PRYC521HASF97xhZkFhddlnTgQ7YH4L1wp3t7O3MfaJINqX2TYgY9WBwi5QFDVtrTOHvraQWjgv4YVqCmHZ9ul9FHtzSW45vPmY4xzGOHr5-BQ-cYntidrf5wIAY4VkcKopobLP32u6zH8mTTVKJurqzsXMvdnJeWbU6vZ45NK3GJcZIt8HFKGvWlY_Hj5x-WkEuOxJztrj0IAPAO4wXv8mDXX74H_44OMriX7hG6QnymHtOPeRyzye0ERWewVOUq1kV4S16Gfb4aCFE5HiuG6_stRtHESgkvOY6_SLXL8MHC3veAzjgbcE2gBeWJ2py6dL9F9q5AUA)
