### ISSUE TITLE
kube2sky: the server has asked for the client to provide credentials

### ISSUE THREAD

**Issue by streamnsight** [kubernetes/kubernetes#24829]
I was running v10 and it had its hickups, but somehow after restarting it a few time it would work...

I saw there has been some updates so I wanted to try.
I am using this version:
https://github.com/kubernetes/kubernetes/blob/78dc9c77167f7017af37f3c2df012a5698aedc36/cluster/addons/dns/skydns-rc.yaml.in

I have read through:
https://github.com/kubernetes/kubernetes/issues/11687
https://github.com/kubernetes/kubernetes/issues/10265#
and 
https://github.com/kubernetes/kubernetes/issues/12784

but I seem to have a different problem:

it's `kube2sky` again which is at fault, but I get this message:

`I0426 22:20:24.996111       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: the server has asked for the client to provide credentials (get services kubernetes). Sleeping 1s before retrying.`

I have 1 serviceaccount per namespace, but I see that I have several `default-token-xxx` in the `kube-system` namespace

```
kubectl get serviceaccounts --all-namespaces                                                                                                     
NAMESPACE     NAME       SECRETS   AGE
default       default    1         129d
dev           default    1         81d
kube-system   default    3         129d
```

```
kubectl get secrets --all-namespaces                                                                                                             
NAMESPACE     NAME                   TYPE                                  DATA      AGE
default       default-token-8vsgq    kubernetes.io/service-account-token   3         101d
default       registry               kubernetes.io/dockercfg               1         90d
dev           default-token-ogops    kubernetes.io/service-account-token   3         81d
dev           registry               kubernetes.io/dockercfg               1         81d
kube-system   default-token-2zzxp    kubernetes.io/service-account-token   3         101d
kube-system   default-token-lnaup    kubernetes.io/service-account-token   3         101d
kube-system   default-token-vgh32    kubernetes.io/service-account-token   3         93d
```

Note they all the service-account-token contain the `ca.crt`, `token` and a `namespace` that seems to be randomly generated.

From reading the above issues, it may be that I may need to delete those tokens, but I'd like to understand the consequences.

Also, one part is confusing to me:

in @thockin 's comments here: https://github.com/kubernetes/kubernetes/issues/10265#issuecomment-117267504 the calls use the default namespace, not the `kube-system` namespace (or is it assumed that we are in the `kube-system` namespace?)

All seems correct if I use the `kube-system` namespace: I find the token, it's mounted in the pod etc...

```
$ kubectl get secret --namespace=kube-system $(kubectl get serviceaccount default --namespace=kube-system -o template --template '{{(index .secrets 0).name}}')
NAME                  TYPE                                  DATA      AGE
default-token-lnaup   kubernetes.io/service-account-token   3         101d
$ echo -ne "token: "; test -n "$(kubectl get secret --namespace=kube-system $(kubectl get serviceaccount default --namespace=kube-system -o template --template '{{(index .secrets 0).name}}') -o template --template '{{index .data "token"}}')" && echo yes || echo no
token: yes
$ echo -ne "ca-crt: "; test -n "$(kubectl get secret --namespace=kube-system $(kubectl get serviceaccount default --namespace=kube-system -o template --template '{{(index .secrets 0).name}}') -o template --template '{{index .data "ca.crt"}}')" && echo yes || echo no
ca-crt: yes
$ echo -ne "pod has secret: "; [[ $(kubectl get pod -l "k8s-app=kube-dns" --namespace=kube-system -o template --template "{{len (index .items 0).spec.volumes}}") -ge 1 ]] && echo yes || echo no
pod has secret: yes
```

The token listed as mounted in the pod is a token from the `kube-system` namespace. 
Checking specifically for this token, it has the ca.crt and token fields.

So why am I still having issues with credentials?

If  I add the `- --kube_master_url=https://${MASTER_IP}` argument (i.e. the TLS secured Master URL), I get:

`I0426 23:05:42.122626       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: Get https://XXX.XXX.XXX.XXX/api/v1/namespaces/default/services/kubernetes: x509: failed to load system roots and no roots provided. Sleeping 1s before retrying.`

So either way kube2sky doesn't seem to be able to connect to api-server.

Should I delete my tokens? what happens when tokens are deleted? 
What happens to the pods that use them? (I have pods that use the service-account to lookup other pods IPs, am I going to have to restart those?)

Thanks

**Comment by streamnsight** [comment]
I ended up deleting the secrets in `kube-system` namespace and kube2sky started working.

**Comment by AlessioMartorelli** [comment]
Hi @streamnsight  how did you delete the secrets? I think I have the same problem but couldn't find a way to delete it. I'd also be ok with deleting the pods and starting from scratch if required.

Thanks

**Comment by streamnsight** [comment]
@AlessioMartorelli  
`kubectl delete secret <secret_ref> --namespace=kube-system`

**Comment by streamnsight** [comment]
btw, you WILL have to delete the pod and recreate it so it gets the new secret

**Comment by yannchristensen** [comment]
I hit this issue after our kubernetes certs were rotated. Deleting the service-account-token for kube-system and deleting the kube-dns pod fixed the issue. Thanks so much for the detailed troubleshooting steps here, much appreciated.

**Comment by tobilarscheid** [comment]
Hi guys, deleting all secrets of type `kubernetes.io/service-account-token` (`kubectl get secrets --all-namespaces` is your friend) fixed this issue for us as well.

The question remains how we could ever end up in such a state and what can be done to avoid this?!
