### ISSUE TITLE
Need the ability to limit how long of a grace period a pod can declare

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#24820]
This is potentially something we could do on limit range.

/cc @kubernetes/rh-cluster-infra @kubernetes/sig-node @smarterclayton @bgrant0607

**Comment by bgrant0607** [comment]
I figured this was coming eventually. :-)

cc @mml @davidopp

**Comment by davidopp** [comment]
@bgrant0607 Heh. And we even know what comes next in this line of thinking, once we have preemption...

**Comment by vishh** [comment]
+1 for adding this feature to limit range.
