### ISSUE TITLE
pod with hostNetwork: true cannot access SkyDNS/service by name

### ISSUE THREAD

**Issue by sols1** [kubernetes/kubernetes#24831]
If the pod has hostNetwork: true, then it cannot use SkyDNS to convert service name into service IP.

Example: I run graphite as a service and collectd as a daemon set. collectd pods need hostNetwork: true to see actual server name (and possibly for other reasons), however, this prevents them for using graphite service by name.

Of course, it is possible to get around this problem by hack but it would be nice to have a cleaner and more reliable method.

**Comment by thockin** [comment]
This is a dup, but I can not find the original bug (sigh).  This is an artifact from docker - running in host networking mode means you get the host's DNS, too.

To change that would be somewhat significant, and has some implications for other runtimes (rkt).  @ArtfulCoder and @dchen1107  for consideration

**Comment by feiskyer** [comment]
Will the pod with `hostNetwork: true` get correct podIP?

**Comment by thockin** [comment]
It should get the field set to the host's IP

**Comment by thockin** [comment]
Dup of #17406 which I have reopened for discussion
