### ISSUE TITLE
KUBE_AWS_INSTANCE_PREFIX in AWS config default should be annotated

### ISSUE THREAD

**Issue by chitezh** [kubernetes/kubernetes#24854]
I was trying to provision a second kubernetes box on AWS for hours without success.
After going through the config-default.sh and digging for a way to get the second instance up, I realized I could just set KUBE_AWS_INSTANCE_PREFIX to the desired name. This created the cluster in a new VPC.

I propose an annotation for KUBE_AWS_INSTANCE_PREFIX describing its usefulness.

**Comment by justinsb** [comment]
That is correct.  Can you propose an improvement to the docs?
