### ISSUE TITLE
kubectl attach support for multiple types

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#24857]
Similar to `kubectl logs`. Note that we already support attach on various types, exposing it only in `kubectl run --attach`. See https://github.com/kubernetes/kubernetes/blob/6b1e59e8c87f75772aad219ad47ccfe5377e8f30/pkg/kubectl/cmd/util/factory.go#L651-L684 

Also that helper needs to support replica sets.

@kubernetes/kubectl

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by shiywang** [comment]
@kargakis I would like to take a look on this one if it's not in a hurry.

**Comment by shiywang** [comment]
also seems @kubernetes/sig-cli-misc is no longer exist? @pwittrock @fabianofranz @AdoHe

**Comment by kargakis** [comment]
@shiywang feel free to work on it.

**Comment by shiywang** [comment]
@kargakis I think we can close this, thanks
