### ISSUE TITLE
Proper Upgrading AWS kubernetes cluster brought up with kube-up is not possible ATM

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#24860]
My understanding is that there is no way currently to do that, right?

kube-push is broken (I'm on 1.2.3)

And even if it worked, it would not do a proper upgrade of the cluster, it would only affect the nodes that are currently up but if I scale up the minions auto-scaling group the new machines would not come updated, right?

AWS is a very important provider and I feel it needs more love...

**Comment by c4po** [comment]
+1
The kube-push is broken. And for AWS cluster, it's better to create a new *Launch Configurations* and update the *Auto Scaling Groups" than to upgrade Kubernetes on each node. I'm working on a script for that. 
Does anyone has idea how to upgrade the *Master Node* in AWS?

**Comment by felipejfc** [comment]
@c4po I did like U said some weeks ago to replace the instance types of my cluster, I think it must work well for upgrading kubernetes on them as well. For master, from my understanding you ony have to:
1) upgrade kubelet binary
2) restart the service
3) upgrade the manifests @ /etc/kubernetes/manifests with the new images tags

**Comment by c4po** [comment]
@felipejfc  I just tested to create new **Launch Configurations** with new **user-data** for binary url and hash checksum. It works. And the kubernetes master can manage the mixed version of minions. (v1.2.3 and v1.2.4). I think I just need delete all minions nodes created with old **Launch Config** and let the **Auto Scaling Groups** bring up new node and join them to the k8s cluster.

For the Master node,  I would like to copy the idea from **gce/upgrade.sh** which delete the current mater and create a new one with same IP and certs.

**Comment by felipejfc** [comment]
@c4po have you finished the script? I'ld llike to take a look when it is finished...
For the master, I think it would work well deleting it and creating another one **with the same name** and assigning the same elastic ip to it.
The same name so that it doesn't mess with kube-down.
If you manage to get it to work please let me know.

**Comment by c4po** [comment]
https://github.com/kubernetes/kubernetes/pull/25680/files

**Comment by c4po** [comment]
As the master node create on AWS is not in cluster.
My concern about delete master node and create it again is we may lose the data store in the etcd on the master node.

**Comment by felipejfc** [comment]
Oh, you are right... maybe it's better to wait for master to be clusterized then, I think it is already on the pipeline for v1.3...

About your PR, you fixed the ASG name:
ASG_NAME="prod-minion-group-us-west-1b"
I think you intended to parametrize it?

**Comment by c4po** [comment]
oh, no. it's a mistake. need remove the test data. ASG_NAME is calculated in util.sh

**Comment by felipejfc** [comment]
@c4po have you managed to upgrade your master node?

**Comment by hernandanielg** [comment]
Has someone tried [this procedure](http://bit.ly/2iPrUxg)? 
I am going to try it in a test environment but I don't know how much downtime it involves. Kops makes managements easier.
