### ISSUE TITLE
Attached PDE in GCE fails with FQDN as the node name

### ISSUE THREAD

**Issue by cmoad** [kubernetes/kubernetes#24864]
Using v1.2.3 we are getting the following error with the default name of the node as registered by the kubelet.

```
989350    2417 gce_util.go:187] Error attaching PD "sinopia-e1b": googleapi: Error 400: Invalid value 'k8s-node-frontend03.c.geofeedia-qa1.internal'. Values must match the following
989561    2417 gce_util.go:183] Retrying attach for GCE PD "sinopia-e1b" (retry count=3).
```

We are able to get around the issue by explicitly running the kubelet with `--hostname-override=$(hostname -s)` but this issue could trip up others and it would be nice to avoid the workaround.

**Comment by matchstick** [comment]
We believe this is fixed in 1.3.4. Please reopen if you can reproduce.
