### ISSUE TITLE
Elasticsearch stops logging on AWS cluster

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#24862]
It is the second time this happens to me, after some time kibana stops showing new log messages from my pods:

![image](https://cloud.githubusercontent.com/assets/285782/14854882/de15b712-0c67-11e6-9ab6-8e9d9bc51f7b.png)

My pods continue to work normally and I can see the logs with logs -f. kube-system pods seems to be working well too:

```
felipejfc@MyMac ~/dev/tfg/kubernetes-prod-cluster$ kubectl-prod get pods --namespace kube-system
NAME                                                 READY     STATUS    RESTARTS   AGE
elasticsearch-logging-v1-e5jj5                       1/1       Running   0          6d
elasticsearch-logging-v1-wkn9m                       1/1       Running   0          6d
fluentd-elasticsearch-ip-172-20-0-120.ec2.internal   1/1       Running   0          12d
fluentd-elasticsearch-ip-172-20-0-21.ec2.internal    1/1       Running   0          10d
fluentd-elasticsearch-ip-172-20-0-56.ec2.internal    1/1       Running   0          12d
fluentd-elasticsearch-ip-172-20-1-108.ec2.internal   1/1       Running   0          12d
fluentd-elasticsearch-ip-172-20-1-112.ec2.internal   1/1       Running   0          10d
fluentd-elasticsearch-ip-172-20-1-57.ec2.internal    1/1       Running   0          12d
heapster-v1.0.2-980111707-92myy                      4/4       Running   0          12d
kibana-logging-v1-zfljc                              1/1       Running   2          12d
kube-dns-v11-uzype                                   4/4       Running   2          12d
kube-proxy-ip-172-20-0-120.ec2.internal              1/1       Running   0          12d
kube-proxy-ip-172-20-0-21.ec2.internal               1/1       Running   0          10d
kube-proxy-ip-172-20-0-56.ec2.internal               1/1       Running   0          12d
kube-proxy-ip-172-20-1-108.ec2.internal              1/1       Running   0          12d
kube-proxy-ip-172-20-1-112.ec2.internal              1/1       Running   0          10d
kube-proxy-ip-172-20-1-57.ec2.internal               1/1       Running   0          12d
kubernetes-dashboard-v1.0.1-xmwq0                    1/1       Running   1          12d
monitoring-influxdb-grafana-v3-9v0vz                 2/2       Running   0          6d

```

The first time this happened I deleted the elasticsearch pods and when new ones born they started to receive logging again...

Any tip on how can I debug this?

**Comment by therc** [comment]
On mobile now, but it's basically https://forums.aws.amazon.com/thread.jspa?threadID=222600 and you need to set reload_connections to false. Store a custom config in a config map, then mount it in your pod. I can add more details later.

**Comment by felipejfc** [comment]
mount into which pod? kibana-logging? all this pods webe brought by default by kube-up

**Comment by therc** [comment]
I don't use kube-up, but yes, that's the idea. Maybe we should turn it off by default. @a-robinson

**Comment by therc** [comment]
I don't use kube-up, but yes, that's the idea. Maybe we should turn it off by default. @a-robins

**Comment by felipejfc** [comment]
But in which pod should I turn it off? fluentd-elasticsearch ones? 
regards

**Comment by a-robinson** [comment]
@therc - that forum post talks about the issue being unique to AWS's hosted elasticsearch. If it's also an issue for our default ES config, shouldn't we just update our default config?

**Comment by felipejfc** [comment]
Any quick fix for that in AWS cluster? It is very anoying to keep restarting my elasticsearch pods for making them work

**Comment by therc** [comment]
@felipejfc Are you running your own ES or AWS' hosted one?

I use a custom fluentd-logging YAML file, with these changes:

```
        volumeMounts:
        - name: config-volume
          mountPath: /etc/td-agent
[...]
      - name: config-volume
        configMap:
          name: td-agent-config
```

The configmap was created like this:

`kubectl create configmap --namespace kube-system td-agent-config --from-file=td-agent.conf`

It's important that your custom file that gets passed to kubectl be named `td-agent.conf`.

**Comment by felipejfc** [comment]
@therc I brought up my Kubernetes AWS cluster with kube-up so It provisioned two ES pods automatically for me... So I think my own.
From what I read I think in this case I shouldn't be having this error, right?

All my config files are default ones that kube-up provisioned for me.

**Comment by therc** [comment]
Ah, then forget what I said, this looks like a different issue. No idea, sorry. :-(

**Comment by felipejfc** [comment]
@therc, I'm now using [](https://github.com/kopeio/aws-es-proxy) with a elasticsearch cluster in aws elastic search service, It seems that my fluentd pods stops sending logs to my elasticsearch just like when I was using the elasticsearch pods provided by get.k8s...
I will try to set that config you said before (reload_connections)... but if thats the case I think it should be set by default..

**Comment by thenayr** [comment]
@felipejfc Take a look at this issue - https://github.com/kubernetes/kubernetes/issues/13313

I've been having these exact problems with my ELK stack and they seem to be related to Fluentd not having access to log files inside of the pods.

**Comment by drora** [comment]
@justinsb any news on that?

**Comment by felipejfc** [comment]
the problem here is that the ELK stack that comes up with the cluster is clearly not suitable for high production loads... My solution for that was to point fluentd to another elasticsearch outside of k8s cluster

**Comment by drora** [comment]
@felipejfc we are discussing the usage of fluentd along with aws-es-proxy. as oppused to local elasticsearch-logging pods

**Comment by felipejfc** [comment]
this is strange @drora, I don't remember this behavior.. This is my current td-agent.conf:

```
<match **>
   type elasticsearch
   log_level info
   include_tag_key true
   host ourescluster.internal
   port 9200
   logstash_format true
   buffer_chunk_limit 8M
   buffer_queue_limit 32
   flush_interval 30s
   max_retry_wait 30
   disable_retry_limit
   reload_connections true
</match>
```

I think that the ```reload_connections true``` part is important. I can confirm that with this setup I had no problems, note that I'm **not using aws-es-service**, I just pointed it directly to my ES cluster.

**Comment by crassirostris** [comment]
@drora Elasticsearch is going to stop being a part of the core Kubernetes, because it's not about Kubernetes per se. Current setup in this repo is far from perfect, e.g. there's no persistent storage. I encourage you to take a look at different open-source integrations or event at Elastic offerings.

We hope to polish our integration with different logging solutions and than make a clear list of recommended sources of information about it, instead of keeping those integrations inside this repo. Stay tuned!

**Comment by drora** [comment]
@crassirostris I totally agree ES shouldn't be integrated as part of k8s distro. this is about the default fluentd setup that for some reason stops shipping logs to AWS-ES-SERVICE via @justinsb aws-es-proxy after a while.
I'm trying to alter the setup according to @felipejfc suggestion (adding "reload_connections true" to td-agent.conf derived from original kubernetes fluentd-es-image). will update in a few days if it will stop reproducing.

**Comment by crassirostris** [comment]
@drora Sorry for the confusion! I meant that both Elasticsearch deployment and fluentd-for-elasticsearch deployment will be removed from the Kubernetes repo.

I'm happy if the @felipejfc's solution helps! Also, updating this issue will definitely be of use, thanks for that!

It's just next time you open or ping an issue here, it might not get the proper response, whereas creating an issue in e.g. https://github.com/fabric8io/docker-fluentd-kubernetes might yield much better results much faster. I wanted to give you a heads up on this topic :)

**Comment by drora** [comment]
@crassirostris cool. thanks for that. will update next week.

**Comment by drora** [comment]
Hi guys,
adding reload_connections true to td-agent.conf didn't help.
fluentd stopped shipping logs to aws-es-service via aws-proxy after a day, restarted fluentd and logs came back in. it will stop logging again soon enough.
IMHO this problem is still very much alive.

**Comment by crassirostris** [comment]
@drora You can try to adapt a liveness probe similar to the one in [fluentd-gcp](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml#L66)

**Comment by crassirostris** [comment]
@drora And create an issue in fluentd or in https://github.com/uken/fluent-plugin-elasticsearch or in https://github.com/fluent/fluentd

**Comment by drora** [comment]
hi @crassirostris,
thanks a lot for responding..
loved the liveness-probe idea. trying that now. hopefully, this will be the end of it.
