### ISSUE TITLE
Vagrant docs with invalid links

### ISSUE THREAD

**Issue by mikebrow** [kubernetes/kubernetes#24866]
Vagrant getting started guide:  kubernetes/docs/getting-started-guides/vagrant.md is an empty shell pointing to its new location on the web at http://releases.k8s.io/release-1.2/docs/getting-started-guides/vagrant.md with the source for said web page being located at kubernetes.github.io/docs/getting-started-guides/vagrant.md.  However, http://releases.k8s.io/release-1.2/docs/getting-started-guides/vagrant.md has been deleted. See kubernetes/kubernetes.github.io#294.  1) Thus, the file kubernetes/docs/getting-started-guides/vagrant.md, the empty shell, is now pointing to a file that  no longer exists.  This file should be deleted. 

There was a similar almost duplicate version of the file that was deleted that is in the devel/ tree: 
https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/devel/developer-guides/vagrant.md.  This version of the vagrant guide as with the other documents in the devel/ tree have not been moved to the web site docs in the releases.k8s.io fork. However the file docs/devel/running-locally.md has a link in it that is pointing to the now deleted version of the vagrant guide.  `Not running Linux? Consider running Linux in a local virtual machine with [Vagrant](../getting-started-guides/vagrant.md), or on a cloud provider like [Google Compute Engine](../getting-started-guides/gce.md).` 2) This link needs to be updated to point to the remaining version of the vagrant guide instead of pointing to the deleted version.  

I have a PR that addresses these two issues: #24495

**Comment by spzala** [comment]
@mikebrow hi Mike, a gentle touch base - this issue is probably not valid any more with all the recent changes - I see that vagrant.md points to minkube local cluster and running-locally.md is not there any more. Just a gentle touch base, as I mentioned, if you can verify this is not needed then please close it. Thanks!

**Comment by mikebrow** [comment]
Closing as this issue has been addressed.
