### ISSUE TITLE
Dependency on docker-proxy

### ISSUE THREAD

**Issue by leshik** [kubernetes/kubernetes#24876]
I'm not sure if this is correct repo to file this issue so please move it elsewhere if I'm wrong.
I played with nginx-ingress-lb resource and found that `hostPort` option depends on docker-proxy to do port forwarding. I had `--userland-proxy=false` option set and, since we also have to set `--iptables=false` to work with Kubernetes, therefore hairpin NAT is off, it took me awhile to figure out why external traffic cannot reach the container. While not a problem in my setup, I believe that Kubernetes tries to use iptables when possible to avoid userspace proxying. This could also affect other containerization engines, such as rkt. Probably it's worth to make `hostPort` option work through iptables also.

**Comment by thockin** [comment]
There's a very old bug on this - #15 in fact!  The problem is that Docker's
flags are/were too coarse and conflicted with our own use, which meant we
had to turn it off.  We could probably subsume that logic now, but it's a
bit of a weird factoring problem.

@dcbw @freehan wrt CNI

**Comment by dnascimento** [comment]
When exposing hostPort 80/443 as cluster entry point, this has a huge impact on performance. Docker-proxy takes 50% of CPU while nginx takes 20%. 
How can we fix this?

**Comment by thockin** [comment]
If you switch to kubenet as a network plugin (available in kubernetes v1.3)
this is fixed.  No more userspace proxy.

**Comment by dnascimento** [comment]
The NETWORK_PROVIDER on AWS Configuration is set to none. 
https://github.com/kubernetes/kubernetes/blob/release-1.3/cluster/aws/config-default.sh#L151

Should this configuration be updated? Is kubenet working on AWS?

**Comment by thockin** [comment]
I have not tried it first hand, but it should work.

@justinsb

On Thu, Jul 28, 2016 at 10:22 PM, Dário Nascimento <notifications@github.com

**Comment by dnascimento** [comment]
It works and removes the docker-proxy. 
On kube-up.sh, set NETWORK_PROVIDER=kubenet
That's it.
