### ISSUE TITLE
AWS: kube-up configure kube-config context 

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kubernetes#24877]
I've run `kube-up` to create a cluster, which resulted in a `aws_kubernetes` cluster and user being created in kube-config. 

Now I want to run `kube-up` again with different parameters, to create a second cluster in a different AWS account. I would like to use a different name for the cluster and user for this cluster. From what I can see from the [script](https://github.com/kubernetes/kubernetes/blob/e9c57e6970c5628f77bbd637bee1aac16fa7ff80/cluster/aws/util.sh#L1291), there seems to be no way to completely override the name used.

I understand that I can use a separate kube-config file, but I don't want to do that. I want to use the same kube-config file, with multiple clusters and users, all handled by `kube-up`.

**Comment by yissachar** [comment]
Manually overwriting `aws/util.sh` file to set CONTEXT to a different value works to achieve the effect that I want.

This value should be allowed to be set externally so that we don't have to resort to manually editing the file for each cluster.

**Comment by paralin** [comment]
Fixed in #24910
