### ISSUE TITLE
e2e test for federated-apiserver

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#24880]
Now that https://github.com/kubernetes/kubernetes/pull/23847 is merged, we should have an e2e test that verifies that POST, GET, DELETE cluster works as expected.

@colhom I believe you are working on this?

cc @kubernetes/sig-cluster-federation

**Comment by colhom** [comment]
@nikhiljindal I am working on it, should have a WIP PR up soon.

I'm finishing up getting kube-up to provision a federated control plane. I believe the actual e2e tests will require kubectl, so I'm also blocking on #24016 (currently needs rebase :( )

**Comment by nikhiljindal** [comment]
I was thinking that our first e2e test can be without kubectl.

It just brings up the federated-apiserver backed by etcd and calls direct HTTP POST, GET, and DELETE cluster requests on federated-apiserver.

**Comment by erictune** [comment]
Assigned to @nikhiljindal as owner on behalf of colhom.

**Comment by nikhiljindal** [comment]
@colhom Any update?

I see that the first part of this is to just bring up the federation control plane (bring up kubernetes cluster, then bring up federation etcd in a pod, and then the federation apiserver and controller manager pods). We can have deployment and service yaml files for federation etcd, apiserver and controller manager. So that bringing up federation control plane is as easy as running `kubectl create -f federation/control-plane-configs/`, where federation/control-plane-configs dir contains our yaml config files.

That is an easy way to bring up the control plane, but users will have to modify the config files themselves if they want to change the command line arguments of apiserver and controller manager.
We can later, provide a script that updates the command line arguments in the config files before using those files.

Also, @lavalamp pointed out that we will need to add a volume and volume claim for federation etcd pod. I am not sure if we will need special code for that on GCE and AWS.

So I see that there is a lot of work left to be done here.
Depending on how much you have done already, we can maybe split the tasks into smaller subtasks which multiple people can work on parallel.

What do you think?

**Comment by colhom** [comment]
@nikhiljindal I should have a PR up by EOD today. I have the apiserver being provisioned on top of the existing cluster, and am in the process of getting that endpoint hooked up to ginkgo. Right now it's only for the vagrant platform. I take it GCE and then AWS, as far as priority w.r.t making it work with other providers?

Where are the deployment/service files that you're talking about?

**Comment by nikhiljindal** [comment]
Yes.

The config YAML files dont exist yet :) That is a subtask that can be worked on in parallel.

**Comment by colhom** [comment]
I've been putting those in `federation/manifests`. Reasonable?

**Comment by nikhiljindal** [comment]
yes :)

**Comment by quinton-hoole** [comment]
@colhom @lavalamp Followup to our discussion today. @lavalamp and I agreed with @ixdy that pushing the Ubernetes control plane binaries to gcr.io by default (with option to override with alternative registry) would be sufficient, and easier than other alternatives we discussed (e.g. creating a registry inside the federated clusters).

**Comment by lavalamp** [comment]
As an action item for a googler-- we need to create a testing bucket in
gcr.io for this to work. @ixdy or @fejta?

**Comment by ixdy** [comment]
@spxtr is current testinfra on-call

**Comment by davidopp** [comment]
ping -- any update on this? it is listed as 1.3 milestone but is not prioritized

**Comment by quinton-hoole** [comment]
This is done in [e2e tests for federated-apiserve #25125](#25125)

**Comment by quinton-hoole** [comment]
So yes, I think we can close this @nikhiljindal ?

**Comment by nikhiljindal** [comment]
We still need to include the test in tests that merge-bot runs and add more test cases, but we have bugs open for those individually, so fine with closing this one.
Ref https://github.com/kubernetes/kubernetes/issues/26723
