### ISSUE TITLE
`kubectl replace deployment` doesn't remove ReplicaSet from the old deployment

### ISSUE THREAD

**Issue by saturnism** [kubernetes/kubernetes#24888]
I have a deployment resource named: `helloworld`, with labels `app=helloworld,version=1`
I want to replace the deployment with a new version of image, but with an updated label, `version=2`

This seem to be impossible to do. If I do: `kubectl apply -f deployment-v2.yaml`, it'll tell me selector doesn't match template labels.

If I do `kubectl replace deployment helloworld -f deployment-v2.yaml`, it'll in fact replace the Deployment resource, and create a new ReplicaSet, and create new Pods with the new labels. But the old ReplicaSet and the old Pods with the `version=1` label are not removed.

Should the replace operation also remove any old ReplicaSet/Pods associated with the previous Deployment?

**Comment by bgrant0607** [comment]
Yeah, don't do that.

**Comment by bgrant0607** [comment]
kubectl replace --force will do cascading delete.

**Comment by bgrant0607** [comment]
Oh, wait. This is not impossible if you just omit version when you specify the selector.

**Comment by bgrant0607** [comment]
cc @janetkuo

**Comment by saturnism** [comment]
so I suppose don't use the default generated selector but specify it myself.

the premise is that I'd like to associate a new label or replace the value of a label to the new pods, since my service could be using this label as a selector.

**Comment by saturnism** [comment]
omitting version from selector can also be problematic if I need to canary two versions (e.g., with 2 deployments).

it'll create a situation where the deployments will go into an infinite loop of deleting and creating pods...

**Comment by bgrant0607** [comment]
There's additional discussion on #26202

**Comment by bgrant0607** [comment]
@saturnism If you want 2 release tracks, but want to be able to update versions in each track, use release-track labels to distinguish the 2 deployments rather than just the version labels.
http://kubernetes.io/docs/user-guide/managing-deployments/#canary-deployments

**Comment by kargakis** [comment]
Canaries will be easier once we have auto-pause: https://github.com/kubernetes/kubernetes/issues/11505

I don't see any other issue here, we still need to document the implications of changing the Deployment selector: https://github.com/kubernetes/kubernetes.github.io/issues/1938
