### ISSUE TITLE
Conversion functions should not be generated if manual conversion functions exist

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#24899]
For example, there is a [manual conversion function](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/conversion.go#L269) for PodSpec and a [generated conversion function](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/conversion_generated.go#L5287).

This doesn't cause any real issue because the generated function is not used. However, it confuses people when they add fields and see the generated conversion functions have covered the new fields, but the roundtrip tests fail.

@wojtek-t @lavalamp

**Comment by wojtek-t** [comment]
hmm - so do we know why the manual conversion exists? I think that if there were any incompatible fields, the generated one wouldn't exists. So maybe the manual one is not needed?
