### ISSUE TITLE
"kubectl run xxxxxxxx" create pod,but got image not found error

### ISSUE THREAD

**Issue by adezdl** [kubernetes/kubernetes#24903]
Failed to pull image "zdlzdltomcatimage": Error: image library/zdlzdltomcatimage not found.
"zdlzdltomcatimage" is my local image.

my question is: why k8s still pull images from docker hub ingoring the local one?

k8s:1.2.2, docker:1.10.3

**Comment by rshriram** [comment]
Same error here

**Comment by fmovlex** [comment]
What do you mean "local" image? does it exist on every node's docker engine?

Having the image locally on one machine (on the master, for example) is meaningless, each node's docker instance tries to pull the image you asked for, doesn't find it locally, and goes to dockerhub by default.

**Comment by rshriram** [comment]
This is running on a single node installation (vagrant box). I followed the
tutorials to setup kubernetes on vagrant using docker (as outlined in the
docs).
I am consistently getting the error that the image is not found, when I use
a local image (one that isn't pushed to dockerhub or GCE). It seems to
automatically append a prefix "library/" and starts looking for images from
gcr.io (?) at library/imageName.

If login to dockerhub vis command line and push the image to the hub, then
things seem to work.

On Mon, May 2, 2016 at 4:37 AM Adam <notifications@github.com> wrote:

> What do you mean "local" image? does it exist on every node's docker
> engine?
>
> Having the image locally on one machine (on the master, for example) is
> meaningless, each node's docker instance tries to pull the image you asked
> for, doesn't find it locally, and goes to dockerhub by default.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/24903#issuecomment-216143967>
>
-- 

~shriram

**Comment by bgrant0607** [comment]
Please ask usage questions on stackoverflow.

Also PTAL at the documentation:
http://kubernetes.io/docs/user-guide/images/

Kubernetes always pulls from a registry.

**Comment by FreakTheMighty** [comment]
@adezdl this confused me as well. Ultimately things started working when I added a tag (other than latest) to my locally built image. The tip came from this blog https://www.brandpending.com/2016/09/20/using-minikube-as-a-local-kubernetes-test-and-development-environment-on-macos/

>Now, run the following command to build and tag the local Docker image:
 `docker build -t static-web2:v1 .`
Note: it is critical that you provide a tag in the image name. Kubernetes will try to look for your > image in a repository if it is asked to get the :latest image (or if you don't provide any tag).

**Comment by benmcp** [comment]
If anyone else ends up on this thread, the solution that worked for me was updating the `image pull policy`, you can find info on this [here](https://kubernetes.io/docs/user-guide/images/#pre-pulling-images). From the docs: `Be default, the kubelet will try to pull each image from the specified registry`. You need to update this so it can look locally.

If you're running from the CLI, add `--image-pull-policy=IfNotPresent` to your `kubectl run some-node-proj --image=my-awesome-local-image:v1` 👍

**Comment by wmaintw** [comment]
I met the same issue when I try to set new (local) image (e.g. `hello-node:v2`) to a container, k8s always try to pull image but append a prefix to the image name, like this: `library/hello-node:v2`

After a few spike, I found a workaround: build docker image and add a prefix to the image, just like this:

`docker build -t library/hello-node:v2`

Hope this could help.

**Comment by Rev1408** [comment]
@benmcp I am on minikube, and I have the same problem, i tried to run  kubectl run some-node-proj --image=my-awesome-local-image:v1 --image-pull-policy=IfNotPresent

docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
nginx                                  latest              46102226f2fd        6 days ago          109 MB
alpine                                 latest              4a415e366388        8 weeks ago         3.99 MB
gcr.io/google_containers/echoserver    1.4                 a90209bb39e3        11 months ago       140 MB
gcr.io/google_containers/pause-amd64   3.0                 99e59f495ffa        12 months ago       747 kB

But still i have the issue.

**Comment by fisshy** [comment]
I managed to solve this issue in Powershell by pointing docker client to my VM.

Using this command

Powershell
` & minikube docker-env | Invoke-Expression`

Terminal
`echo ${minikube docker-env}`

**Comment by mienaikoe** [comment]
@Rev1408 I'm also using Google Cloud. This isn't documented anywhere on google's docs that I could find, but you have to use Google Cloud Repository for docker images on their kubernetes. You can learn more here:  https://cloud.google.com/container-registry/docs/quickstart

**Comment by Gisleburt** [comment]
Thought I should add my dumb mistake in here so no one else spends ages wondering why none of the above works. 

If you've made a config file to use with `--apply`, make sure you haven't set `imagePullPolicy: "Always"` instead try `imagePullPolicy: "IfNotPresent"`

Thank you @benmcp for getting me there. 😀

**Comment by cmgurba** [comment]
I ran across a similar error and I simply was building images in a terminal which wasn't pointed to my minikube docker-env.  I needed to run `eval $(minikube docker-env)` and build my images again.  😨

**Comment by esetnik** [comment]
I have this issue but it seems to affect only `latest` tag images. The specific error is `Failed to pull image "hello-node:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for hello-node, repository does not exist or may require 'docker login'`

For example:

```
❯ eval $(minikube docker-env)
❯ docker build -t hello-node .
❯ docker images
REPOSITORY                                                       TAG                 IMAGE ID            CREATED             SIZE
hello-node                                                       latest              98571ec055b8        7 minutes ago
❯ kubectl run hello-node --image=hello-node --port=8080
❯ kubectl describe pods hello-node
Name:           hello-node-785b48577d-58r7r
Namespace:      default
Node:           minikube/192.168.64.2
Start Time:     Fri, 06 Apr 2018 19:53:06 -0400
Labels:         pod-template-hash=3416041338
                run=hello-node
Annotations:    <none>
Status:         Pending
IP:             172.17.0.6
Controlled By:  ReplicaSet/hello-node-785b48577d
Containers:
  hello-node:
    Container ID:
    Image:          hello-node:latest
    Image ID:
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-95zqq (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  default-token-95zqq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-95zqq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age                From               Message
  ----     ------                 ----               ----               -------
  Normal   Scheduled              10m                default-scheduler  Successfully assigned hello-node-785b48577d-58r7r to minikube
  Normal   SuccessfulMountVolume  10m                kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-95zqq"
  Normal   Pulling                8m (x4 over 10m)   kubelet, minikube  pulling image "hello-node:latest"
  Warning  Failed                 8m (x4 over 10m)   kubelet, minikube  Failed to pull image "hello-node:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for hello-node, repository does not exist or may require 'docker login'
  Warning  Failed                 8m (x4 over 10m)   kubelet, minikube  Error: ErrImagePull
  Normal   BackOff                8m (x6 over 10m)   kubelet, minikube  Back-off pulling image "hello-node:latest"
  Warning  Failed                 4m (x20 over 10m)  kubelet, minikube  Error: ImagePullBackOff
```

When I give the image a tag it works:
```
❯ docker tag hello-node hello-node:v1
❯ kubectl run hello-node2 --image=hello-node:v1 --port=8080
❯ kubectl describe pods hello-node2
Name:           hello-node2-59dbddb456-46g2t
Namespace:      default
Node:           minikube/192.168.64.2
Start Time:     Fri, 06 Apr 2018 20:06:45 -0400
Labels:         pod-template-hash=1586886012
                run=hello-node2
Annotations:    <none>
Status:         Running
IP:             172.17.0.7
Controlled By:  ReplicaSet/hello-node2-59dbddb456
Containers:
  hello-node2:
    Container ID:   docker://d49001c55710415c1d9cee480db0fe784913f74728f1691a0cda9045d9ab8050
    Image:          hello-node:v1
    Image ID:       docker://sha256:98571ec055b8447a351a62ecb99c8354736a36c09eeb8e5775bf47f9ad260e60
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 06 Apr 2018 20:06:46 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-95zqq (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  default-token-95zqq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-95zqq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type    Reason                 Age   From               Message
  ----    ------                 ----  ----               -------
  Normal  Scheduled              38s   default-scheduler  Successfully assigned hello-node2-59dbddb456-46g2t to minikube
  Normal  SuccessfulMountVolume  38s   kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-95zqq"
  Normal  Pulled                 37s   kubelet, minikube  Container image "hello-node:v1" already present on machine
  Normal  Created                37s   kubelet, minikube  Created container
  Normal  Started                37s   kubelet, minikube  Started container
```

**Comment by jkaipa** [comment]
@esetnik - How did you resolve the docker image pull issue?

**Comment by ewilansky** [comment]
I'm also using kubernetes in docker for mac and encountered the same issue. Deleting all replicas, deployments, services and pods didn't help. Eventually, all resources would be recreated. The solution I found was to open Docker for Mac > Preferences > Reset tab and then click Reset Kubernetes cluster.

**Comment by schollii** [comment]
For minikube to pull from your own local docker registry, the tag affects the pull policy. Per [Images docs](https://kubernetes.io/docs/concepts/containers/images), pull policy is `IfNotPresent` by default EXCEPT if
- you use `:latest` as the tag for the image to use
- OR you omit the tag for the image to use.

In those cases the pull policy will effectively default to `Always`, which will attempt to pull from docker hub. This will cause minikube to be unable to fetch local images that have no tag or "latest" tag. 

Moral of the story is, don't rely on the default because it is too confusing :)

So always explicitly state the pull policy: 

- when deploying into minikube the pull policy should be `IfNotPresent` or `Never` for the local images
- when deploying into a cloud host (like AWS), pull policy should be as for public images (see below)
- the pull policy should be `Always` for those public images that use a tag like "latest" or "stable" (because the image the tag points will change over time), and `IfNotPresent` for tags that always point to the same image (to avoid fetching more than necessary)

This means that if you avoid using tags like latest and stable etc, there is only one rule to follow: 
- explicitly set the `imagePullPolicy` in your spec (or on the command line in the case of run) to `IfNotPresent`, as this is will always look for it locally first, and go to public registry if it is not found locally, and this will work whether or not you are deploying into minikube or cloud.
