### ISSUE TITLE
e2e all DNS testing failed on local cluster

### ISSUE THREAD

**Issue by gouyang** [kubernetes/kubernetes#24917]
I run e2e test on local cluster and the 3 DNS testing failed because of 

```
No pods match the label selector k8s-app=kube-dns,kubernetes.io/cluster-service=true
```

Checking the code, I think verifyDNSPodIsRunning(f) is called at the very beginning should be the cause, because the pod is not created yet.  

```
var _ = framework.KubeDescribe("DNS", func() {
          f := framework.NewDefaultFramework("dns")

          It("should provide DNS for the cluster [Conformance]", func() {
                  verifyDNSPodIsRunning(f)

```

Put this line `verifyDNSPodIsRunning(f)` after 
`validateDNSResults(f, pod, append(wheezyFileNames, jessieFileNames...))`, I could see the pods were created, although it's still failed, but it's another story.

**Comment by gouyang** [comment]
cc @ArtfulCoder Seems you're the author of the code, could you please help looking at this.

**Comment by kargakis** [comment]
Shouldn't be a problem today I think, please reopen otherwise.
