### ISSUE TITLE
Upgrading to Go-1.6.2

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#24922]
Hi all,

Go folks have released go-1.6.2. https://golang.org/doc/devel/release.html#go1.6.minor. Due to golang/go#15135, golang-1.6.0 is having issues with ppc64le arch. The issue is fixed in golang-1.6.2. I would like to propose to upgrade to go-1.6.2.

@luxas @zmerlynn @thockin

**Comment by luxas** [comment]
@spxtr is already having a PR for it: #24266 :)

**Comment by luxas** [comment]
#24266 was merged. Closing as solved
