### ISSUE TITLE
GKE / GCE Network Isolation - Is it possible?

### ISSUE THREAD

**Issue by microadam** [kubernetes/kubernetes#24920]
Hello,

Just curious if it is possible to use the beta network isolation features which some of the overlay networks  (calico, Romana, OpenShift etc) are starting to support? Or if this is planned for the future? Not been able to find any documentation on it anywhere, or what the future plans for it might be.

Thanks a lot

**Comment by mikedanese** [comment]
cc @cjcullen @bprashanth

**Comment by bprashanth** [comment]
I think this depends on the backend implementation. If a backend requires L2 connectivity, no, if it's just using iptables yes, for example. I believe calico should work (https://www.projectcalico.org/calico-network-policy-comes-to-kubernetes/), unsure about the others. Suggest inquiring on the net-sig: https://groups.google.com/forum/#!forum/kubernetes-sig-network

**Comment by microadam** [comment]
Thanks for the response! Apologies though, I don't think I worded my question that well. 

If I was running directly on GKE (hosted Kubernetes), is it possible to use the network namespace isolation now? Or is it something that is planned for the future? Or something that is never on the roadmap? 

If using just plain GCE, can I use the network namespace isolation without running something like calico? I am almost certain the answer is no, just been unable to find any conclusive answer. 

Thanks a lot!

**Comment by randunel** [comment]
You wouldn't be able to use any network policies ok GKE, but someone is "looking at" that https://groups.google.com/d/topic/kubernetes-users/U-2IzS3Awew/discussion

-----

Regarding GCE, here's an excerpt from the [docs](https://kubernetes.io/docs/user-guide/networkpolicies/):

> You must also be using a networking solution which supports `NetworkPolicy`
