### ISSUE TITLE
Document units in cpu limits

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes#24925]
http://kubernetes.io/docs/user-guide/compute-resources/ nor the references manual seem to document the accepted formats for `cpu`. It seems that at least two formats are possible:

  - `100m` meaning 10% cores
  - `0.1` meaning probably the same
  - any more?

**Comment by mikedanese** [comment]
cc @vishh

**Comment by vishh** [comment]
That document states the following - "CPU is specified in units of cores."
CPU is mentioned as an absolute value and not a relative (%) value. So `100m` translates to 100 milli cores or 1/10th of a single core.

**Comment by vishh** [comment]
If the fact that CPU values are not absolute is not clear, we can definitely make that explicit in the doc.

**Comment by wernight** [comment]
What's the difference between 1/10th of single core and noting is `10%`? The fact that it depends on the number of cores and doesn't care about frequency is pretty odd but that's not the main point. I was really asking about different valid ways to say 1/10th of single core, mostly because I find `100m` so misleading.

**Comment by vishh** [comment]
Not normalizing across CPU types is an explicit choice as of now. In the future, we might support such normalizations.
The API requests number of core**s**, and so `10%` could also mean 10% of all the core**s** on the machine. Whereas, `100m` is explicit, where you are asking for 100 [milli](https://en.wikipedia.org/wiki/Milli-)cores.

**Comment by wernight** [comment]
So on a dual core: `10%` = `0.1` = 10% of 2 cores = `200m`? And all those string are valid in Kubernetes?

**Comment by erictune** [comment]
`%` is not valid for specifying cpu in a yaml/json.  So, its meaning is not precisely defined.  I think you started using `%` in this issue.

`0.1` is the same amount of cpu on a single core, dual core, or 48 core machine.   

Definition:

*For a single-threaded program, a cpu usage of `0.1` means that if you could freeze the machine at the machine at a random moment in time, and look at what each core is doing, there is a 1 in 10 chance that your single thread is running at that instant.  The number of cores on the machine does not affect the meaning of `0.1`.  For a container with multiple threads, a cpu usage of `0.1` mean that the sum of the probabilities for of the individual threads (as above) is `0.1`.  There is no guarantee about which core you run on, and you might run on a different core at different points in your container's lifetime. *

**Comment by wernight** [comment]
Thanks for the clarification. Does it mean that on **quad core** `0.1` would be equivalent to `400m`?

**Comment by erictune** [comment]
No.  The number of cores on your machine never matters when interpreting a cpu usage.

**Comment by wernight** [comment]
If it doesn't, can you explain? Because I understood that on a dual core
`200m` = `10%`, but those are not equivalent on a single core for example.

**Comment by wernight** [comment]
@erictune Can you please explain what you mean?

**Comment by erictune** [comment]
Say your pod has a container that asks for `100m`.  

- If it is scheduled onto a node with 1 core, then the container gets 102 cpu shares (`round(0.1 * 1024 * 1)`)
- if it is scheduled onto a node with 4 cores, then the container gets 409 cpu shares (`round(0.1 * 1024 * 4)`)
- if it is scheduled onto a Intel Xeon E5-2687W v4 Twelve-Core Broadwell, which has 24 hardware threads, then the container gets 2458 cpu shares (`round(0.1 * 1024 * 24)`)

See the docker documentation for an explanation of cpu shares:
https://docs.docker.com/engine/reference/run/#/cpu-share-constraint

**Comment by wernight** [comment]
@erictune My initial question which I think is still unresolved (documentation isn't improved) is about allowed ways to mark `cpu:` shares and limits in Kubernetes. So far there is the `XXXm` notation and the `XXX%` notation which are not documented and which mean different things.

**Comment by erictune** [comment]
There is not an `XXX%` notation.  

```
$ cat > wrong.yaml <<EOF
apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: x
spec:
  containers:
  - name: c
    image: busybox
    resources:
      requests:
        cpu: "100%"
EOF
$ kubectl create -f wrong.yaml
unable to decode "wrong.yaml": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

**Comment by erictune** [comment]
I think maybe you are talking about the % that is shown in `kubectl describe node foo`.

`XXX%` is not an acceptable format for CPU in a pod spec.  

It is shown as a convenience in kubectl describe nodes. In that case, percent-cpu = node-capacity / pod-request-or-limit
So a node with capacity 2 , with pod with request 100m has request of `0.100 / 2 = 0.05 = 5%`

**Comment by wernight** [comment]
Yes you're right. Ok so there is only the `XXXm` notation. That was actually my question (updating my own doc).

**Comment by erictune** [comment]
No, 0.1 notation also means 10% of **a core**.  Where are you seeing otherwise?

**Comment by wernight** [comment]
That was my understanding from:

> 10% of all the cores on the machine. **Whereas**, 100m is explicit, where you are asking for 100 **millicores**.

> 0.1 is the same **amount** of cpu on a single core, dual core, or 48 core machine.

Ok both are equivalent. Would you mind having on http://kubernetes.io/docs/user-guide/compute-resources/ or http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_resourcerequirements that `100m` is the same as `0.1` and those two are the only valid notations?

**Comment by erictune** [comment]
https://github.com/kubernetes/kubernetes.github.io/pull/794
and
https://github.com/kubernetes/kubernetes/pull/28696

**Comment by heshamMassoud** [comment]
I have a question here, if I have:

Pod **A** deployed there has `spec.containers[].resources.requests.cpu`:0.2
Pod **B** deployed there has `spec.containers[].resources.requests.cpu`:0.8

In the case of a single core node on GCP → 1 CPU:
- Pod A will get 20% of the CPU time.
- Pod B will get 80% of the CPU time.

In the case of a dual-core node on GCP → 2 CPU:
- Pod **A** will get (0.2/2 = 10%) of the CPU time.
- Pod **B** will get (0.8/2 = 40%) of the CPU time.

**Comment by vishh** [comment]
Assume that there is 200 quantums of cpu time available across 2 cores.
With your example, pod A will get 40 quantums of time while pod B will get
160 quantums of cpu time.
In the case of since core, there will 100 quantums of cpu time, where pod A
gets 20 quantums and pod B gets 80 quantums.

**Comment by novaterata** [comment]
@vishh said:
> That document states the following - "CPU is specified in units of cores."
> CPU is mentioned as an absolute value and not a relative (%) value. So 100m translates to 100 milli cores or 1/10th of a single core.

@erictune said:
> Say your pod has a container that asks for 100m.
> 
>     If it is scheduled onto a node with 1 core, then the container gets 102 cpu shares (round(0.1 * 1024 * 1))
>     if it is scheduled onto a node with 4 cores, then the container gets 409 cpu shares (round(0.1 * 1024 * 4))
>     if it is scheduled onto a Intel Xeon E5-2687W v4 Twelve-Core Broadwell, which has 24 hardware threads, then the container gets 2458 cpu shares (round(0.1 * 1024 * 24))
> 
> See the docker documentation for an explanation of cpu shares:
> https://docs.docker.com/engine/reference/run/#/cpu-share-constraint

To me these statements are contradictory. Reading this thread has confused me more than before. If 100m increases with the number of cores per node then it is relative not absolute. I don't consider this issue closed until someone addresses the confusion in the documentation in addition to the definition.

**Comment by novaterata** [comment]
Can someone give me a straight answer: Is there a way to set a resource limit that scales with node size?

**Comment by vishh** [comment]
Here's [the code](https://github.com/kubernetes/kubernetes/blob/a21a7502496418d8ef26a5d1522f8f246110f5fc/pkg/kubelet/kuberuntime/helpers_linux.go#L33) of how k8s calculates "cpu shares" based on "CPUs" requested. 
k8s assigns 1024 CPU shares per CPU. So if you machine has 2 CPUs, then that node can have a total of 2*1024 - 2048 CPU shares. A single pod requesting 1 CPU will be assigned 1024 shares. 
If two pods each asking 1 CPU is assigned to the same node, then all the CPUs on that node are given away. 
If one pod is idle, the other pod can use up all the two CPUs. If both pods are utilizing as much as possible, they will each be restricted to one CPU.

**Comment by novaterata** [comment]
So does that not invalidate what Eric said?

**Comment by vishh** [comment]
@novaterata yeah, k8s overrides docker default behavior.

**Comment by novaterata** [comment]
I don't know what that means in this context. I feel like nothing I've
asked has been addressed. Like I'm wasting my breathe. Just nevermind then.

**Comment by vishh** [comment]
@novaterata 
1. You asked `If 100m increases with the number of cores per node then it is relative not absolute.`
2. I responded saying CPU requests are absolute and so it's meaning is the same irrespective of the machine size, and that it's is inherently not a hard limit where a container can use up as much CPU as it wants when available irrespective of it's requests.
3. You asked if Eric's comment was not valid anymore and I said yes.

What is still causing confusion?

**Comment by novaterata** [comment]
>You asked if Eric's comment was not valid >anymore and I said yes.

I did not get that from what you said. You said something about docker.
That is the primary point of confusion.

**Comment by novaterata** [comment]
Thank you for eventually answering me
