### ISSUE TITLE
[e2e] Add fast, simple a DNS `Before` hook.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#24926]
There should be a good quick smoke test for DNS which we run in a `Before` hook which proceeds alot of the tests to speed them along (i.e. guestbook,liveness,....).  

Otherwise, tests will just poll for several minutes with no chance of succeeding and send users with broken clusters on a wild good chase.

cc @rrati @timothysc @kubernetes/sig-testing

**Comment by timothysc** [comment]
"In general" we are missing a bunch of pre-condition checks for skipping, that are annoying when running local-cluster-up.
