### ISSUE TITLE
Controllers don't take any actions except updating Status if deletionTimestamp != nil

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24934]
When controller is being deleted it shouldn't try to change state of the cluster (e.g. delete/create Pods in case of ReplicaSet).

cc @kubernetes/sig-api-machinery @bgrant0607 @caesarxuchao @lavalamp

**Comment by lavalamp** [comment]
Does deletion implicitly set replicas to 0? Will orphaned pods count towards the number of replicas?

Clients that wait for generation == status.observedGeneration && spec.replicas == status.replicas may have issues.

**Comment by gmarek** [comment]
For this I'd thing that it doesn't change anything it it's spec. Just don't try to take any actions.

Another option would be to set replicas to 0 and remove label selector, but I'm pretty sure that would break someone.

**Comment by gmarek** [comment]
I believe this was fixed.
/close
