### ISSUE TITLE
Setting deletionTimestamp in a Controller should bump its generation.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#24935]
cc @kubernetes/sig-api-machinery @bgrant0607 @caesarxuchao @lavalamp

**Comment by lavalamp** [comment]
No need to limit this to controller objects if generation is already implemented generically.

**Comment by derekwaynecarr** [comment]
I am confused by this issue.  Can you elaborate?

**Comment by gmarek** [comment]
AFAICT currently Generation is bumped only when Spec of a given object is changed. The idea behind the generation is that as long as the generation is the same, the behavior of the object doesn't change (i.e. update of Status generally doesn't change behavior of the object). deletionTimestamp will change the behavior of controllers, as they will stop "controlling" things (#24934).

This is needed for controllerRef: #24946

**Comment by lavalamp** [comment]
We need a way to tell if a controller has observed a deletion.

**Comment by kargakis** [comment]
> We need a way to tell if a controller has observed a deletion.

Why does it have to be different from Generation/ObservedGeneration?

**Comment by gmarek** [comment]
It doesn't. The thing is that currently only spec changes bump generation. Deletion timestamp is in object meta.

**Comment by kargakis** [comment]
Nevermind, I thouhgt you wanted to do this in a different way.

**Comment by smarterclayton** [comment]
This was implemented
