### ISSUE TITLE
Improve Redis example

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes#24930]
A few points of improvement of the Redis example on https://github.com/kubernetes/kubernetes/tree/master/examples/redis:
- Configuration files should include only fields that deviate from the [default](http://download.redis.io/redis-stable/redis.conf) in order to clarify. For example for `redis-master.conf` it could probably be (excluding comments) using [CONFIG GET](http://redis.io/commands/config-get) to check, or just use a single `redis.conf` like:
  
  ```
  save 900 1
  save 300 10
  save 60 10000
  dir /redis-master-data
  slaveof ${master-ip} ${master-port}  # only for slave, not when bootstrapping.
  ```
- Describe how to use in clients (should be to use the `redis-sentinel` host name but should be documented)
- Describe how to upgrade to newer versions of Redis, preferably using the `Deployment` Job.
- Could simplify [`run.sh`](https://github.com/kubernetes/kubernetes/blob/master/examples/redis/image/run.sh):
  - Use `cat some.config.template | envsubst > some.config` for both cases: `launchsentinel()` and `launchslave()`
  - Use Kubernetes `args: ["redis-server", "/redis-master/redis.conf"]` to start the master.
  - Use Kubernetes `args` to ask the `redis-master` Pod to start with master IP set to `$(hostname -i)`.
  - Possibly even remove completely `run.sh`
- Remove to describe `redis-proxy.yaml`

Extra question: Instead of `while true`, why not just let Kubernetes handle that? It seems useful to see pods restarting vs seeing them running. Of course one should include some probes (could be in the example as well), so that it'd get restarted anyway.

**Comment by wernight** [comment]
One idea to simplify deployment and updates:

1. Have all yml into a single `redis.yml`, all using `Deployment` with:
      - `replicas: 0` for `redis-master`
      - `replicas: 3` for `redis-sentinel` and `redis-slave`
2. To upgrade, simply `kubectl apply -f redis.yml`
3. To (re-)bootstrap, scale down to 0 `redis-sentinel` and `redis-slave`, then to 1 the `redis-master`

Another option would be to have a `redis-boostrap.yml` and a `redis.yml` with different number of replicas (as above) but that would duplicate lots of code.

**Comment by mikedanese** [comment]
cc @kubernetes/examples

**Comment by melalj** [comment]
Any updates on this?

**Comment by kargakis** [comment]
/sig apps
@ahmetb

**Comment by ahmetb** [comment]
If anybody is interested, please feel free to submit a patch to https://github.com/kubernetes/examples/tree/master/staging/storage/redis. We are not going to be maintaining the examples of third-party software (such as Redis in this case) going forward.

If there are community members volunteering to maintain this recipe going forward, we encourage creating a new repository and continue working on it there. Alternatively creating a Helm chart would be preferable as well (in this case, we do have Helm charts for Redis).

/assign
