### ISSUE TITLE
kubenet flake: pod is ready but not serving traffic

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#24953]
This can be reproduced by running `service up and down` test. Further debugging show that iptables rules were in place. And request to service did got routed to backend pods. But one of the backend pod was not ready to serve traffic even though podStatus was ready.  I kept the services and RCs, if test failed. When I revisit it, they were acting normally. 
Network setup and container creation happens sequentially. So network should be ready long before pod is ready. Open to suggestion for what to look for next.

cc: @dcbw

**Comment by freehan** [comment]
It is due to `arp` cache does not have valid mac address of the new pod immediately after the new pod becomes ready. 

I think this is largely due to the ip allocation logic in CNI 'host-local' ipam. It tends to allocate ips which are recently used. It should do a round robin instead.

**Comment by dims** [comment]
Is this still a problem? Does not seem to have been referenced by anyone since Apr 29. Can we please close this?

**Comment by freehan** [comment]
The fix has been merged upstream. But k8s has not updated CNI version yet. I am waiting for another fix to get in to upstream and bump the CNI version all together.

**Comment by bprashanth** [comment]
@freehan ETA on the second fix? getting the first fix in will clear up some confusion around other failures, though if it's within the next day or so waiting should be ok

**Comment by freehan** [comment]
@bprashanth The first fix was already in for quite some time. The fix was not in the official CNI code base at the time. Hence I keep this open to track the upstream issue.
