### ISSUE TITLE
Go client uses localhost instead of 127.0.0.1

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/kubernetes#24951]
The Kubernetes Go client uses `localhost` by default to access the apiserver.

On CoreOS, where it is common to not have an `/etc/hosts` file, this means apps using the client will often fail to lookup `localhost` and be unable to access the API.

Shouldn't the client be using `127.0.0.1` instead of `localhost` here?

https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/client_config.go#L39

**Comment by jmzwcn** [comment]
#dibs

**Comment by jmzwcn** [comment]
Hi, I am a freshman, could I have a try for this issue?

**Comment by thockin** [comment]
not having a name lookup for `localhost` seems like a really really bad
idea to me...

**Comment by caseydavenport** [comment]
@thockin - It seems odd to me as well (though this is apparently the norm for CoreOS, just discovered that).  I'm not sure what the reasoning is, but @aaronlevy might have more input.

**Comment by aaronlevy** [comment]
You can do a localhost lookup, but this was brought up due to a container running with `hostNetwork=true` and I believe Docker's `--net=host` behavior is to copy the host `/etc/hosts` into the container fs (which on CoreOS doesn't exist).

I opened a related issue against CoreOS here: https://github.com/coreos/bugs/issues/1260

**Comment by aanm** [comment]
Also, why `127.0.0.1` and not `::1` for example?

**Comment by caseydavenport** [comment]
@aanm - Yes, the more I've thought about this the more I've realized assuming `127.0.0.1` is probably the wrong way to go.  Happy to close this with the understanding that you need to configure name lookups for "localhost"

**Comment by thockin** [comment]
@aaronlevy - how does a CoreOS node define "localhost" if not /etc/hosts?

**Comment by aaronlevy** [comment]
@thockin via `/etc/nsswitch.conf` - which defines a hosts location at `/usr/share/baselayout/hosts`. The `/etc/hosts` location is still checked, just the "default" OS copy is in /usr/share/baselayout

**Comment by thockin** [comment]
Ahh, thanks
