### ISSUE TITLE
Conversion generator should create cross group conversions

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#24960]
Most people are copying and pasting, which leads to lots of code that decays and has to be hand maintained.

Example: "extensions"

**Comment by mml** [comment]
@lavalamp Seems pretty closely related to #18762.  Just fold it in?

**Comment by lavalamp** [comment]
I think this is sufficiently different, assuming I understand it.

**Comment by smarterclayton** [comment]
Yeah, this is more mechanical "no one should be writing cross group
conversions of identical types, because either conversion tooling is
limited, or we should be using go aliases"
