### ISSUE TITLE
Gobindata automation

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#24976]
after #24867 

**current status** Gobindata will be important moving forward for a lot of our tests that rely on things like guestbook, while retaining binary portability...  To generate the artifacts, currently a developer needs to do this.

```
 go-bindata \
 	-pkg generated -ignore .jpg -ignore .png -ignore .md \
 	./examples/* ./docs/user-guide/* test/e2e/testing-manifests/kubectl/* test/images/*
 cp bindata.go test/e2e/generated
```

**goal**

Maintaining gobindata is not a huge task,  since likely we don't need to update too often.  But we should automate for the sake of simplicity and to avoid human-error.

**proposed implementation**  

*The current commited gobindata should be phased out into an automated, `go generate` type just-in-time build artifact.* <- thoughts?

**Comment by jayunit100** [comment]
@timothysc @kubernetes/sig-testing

**Comment by timothysc** [comment]
It should be part of the build process.

**Comment by jayunit100** [comment]
Yup that's what I mean,

**Comment by fejta** [comment]
It should be part of the merge process.

**Comment by jayunit100** [comment]
Hmmm... I I feel like hack/verify is for things that aren't already automated, right?

**Comment by timothysc** [comment]
hack/verify is the last line of defense for manual processes.  If you do it as part of the build itself then you don't need hack/verify.  If you do it once in a while via human intervention then you should have a hack/verify script.

**Comment by jayunit100** [comment]
Yup, agree

**Comment by ixdy** [comment]
this is done, right?

**Comment by jayunit100** [comment]
Yup
