### ISSUE TITLE
flake: TestDelNode failed

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#24971]
Running `godep go test k8s.io/kubernetes/pkg/controller/node -v` show failures at times:

```console
$ godep go test k8s.io/kubernetes/pkg/controller/node -v
...
=== RUN   TestDelNode
--- FAIL: TestDelNode (0.00s)
	rate_limited_queue_test.go:76: Invalid queue. Got [0xc820251c00 0xc820251bc0], expected [second third]
...
```

The expected queue is `[second third]` while got `[third second]`, see code here: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/rate_limited_queue_test.go#L76

I would give an idea that these cases have something similar, so referring #24784 and #24788 

/cc @gmarek

**Comment by gmarek** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
I think so as well.

**Comment by smarterclayton** [comment]
The debugging I added to the test is obviously not correct - I'll fix that separately.

**Comment by smarterclayton** [comment]
I wonder if on very short intervals we're not getting a goroutine schedule swap, which causes this race to manifest (based on comments in the other thread).

**Comment by smarterclayton** [comment]
Does heap insertion guarantee order if the heap value is equivalent?
I don't think so.

**Comment by smarterclayton** [comment]
This seems like it is that now() is not monotonically increasing, so we
violate the add ordering condition.  Since we already have a lock in most
cases, we may want to either wrap now() to make it monotonic inc, or have
the queue check for equality in the heap and add one nanosecond until there
is no matching heap item.

On Apr 29, 2016, at 7:12 PM, Marek Grabowski <notifications@github.com>
wrote:

cc @smarterclayton <https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/24971#issuecomment-215904703>

**Comment by zhouhaibing089** [comment]
@smarterclayton Thanks for clarification, so it looks like we need to give some time break between doing `evictor.Add("")`, I'll see whether that helps.

**Comment by smarterclayton** [comment]
I believe this is a bug in rate limited queue, so we definitely need to fix it (esp. since it's happening in the real world)

**Comment by erictune** [comment]
@smarterclayton you wrote pkg/controller/node/rate_limited_queue.go.  Would you be a good person to pick an owner for this bug?

Giving P1 since we think happens in real world and I don't understand severity.

**Comment by smarterclayton** [comment]
@gmarek and I are probably the two who have touched it, I think
@mikedanese as well but may be misremembering.  It should be a
straightforward fix to make now monotonic, I don't know when I can get
to it

**Comment by gmarek** [comment]
Me neither. If it's P1 I most likely won't have time before v1.3.

**Comment by zhouhaibing089** [comment]
@smarterclayton I think override the `now()` function call as you did [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/rate_limited_queue_test.go#L155-L167) in `TestDelNode` would resolve this issues, what do you think, if you agree with this, I am gonna to try that.

**Comment by smarterclayton** [comment]
It would fix it, although I think this is broken in the core code, not just in the test.  We suspect real workloads have been impacted by this.

**Comment by smarterclayton** [comment]
Opened #25822 to determine whether we actually need to fix the RLQ

**Comment by fejta** [comment]
Assigning to @bprashanth per https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/OWNERS
