### ISSUE TITLE
Running update-all.sh on latest master fails 

### ISSUE THREAD

**Issue by aveshagarwal** [kubernetes/kubernetes#24986]
```
# ./hack/update-all.sh 
Running in the silent mode, run with -v if you want to see script logs.
Running in short-circuit mode; run with -a to force all scripts to run.
Updating generated-protobuf
!!! Error in ./hack/../hack/../build/common.sh:595
  '"${docker_cmd[@]}" "$@"' exited with status 126
Call stack:
  1: ./hack/../hack/../build/common.sh:595 kube::build::run_build_command(...)
  2: ./hack/../hack/update-generated-protobuf.sh:58 main(...)
Exiting with status 1
Updating generated-protobuf FAILED
```

**Comment by mml** [comment]
Please try running with -v and/or try running u-g-protobuf directly and post the output.

**Comment by nikhiljindal** [comment]
cc @smarterclayton

**Comment by aveshagarwal** [comment]
#./hack/update-all.sh -v
Running in short-circuit mode; run with -a to force all scripts to run.
Updating generated-protobuf
+++ [0502 15:19:27] Verifying Prerequisites....
+++ [0502 15:19:27] Building Docker image kube-build:build-cfba5e2a29.
+++ [0502 15:19:27] Running build command....
/bin/bash: hack/after-build/update-generated-protobuf.sh: Permission denied
!!! Error in ./hack/../hack/../build/common.sh:595
  '"${docker_cmd[@]}" "$@"' exited with status 126
Call stack:
  1: ./hack/../hack/../build/common.sh:595 kube::build::run_build_command(...)
  2: ./hack/../hack/update-generated-protobuf.sh:58 main(...)
Exiting with status 1
./hack/update-all.sh: line 75: Updating: unbound variable

**Comment by aveshagarwal** [comment]
```
# ./hack/update-generated-protobuf.sh -v
+++ [0502 15:20:53] Verifying Prerequisites....
+++ [0502 15:20:53] Building Docker image kube-build:build-cfba5e2a29.
+++ [0502 15:20:53] Running build command....
/bin/bash: hack/after-build/update-generated-protobuf.sh: Permission denied
!!! Error in ./hack/../build/common.sh:595
  '"${docker_cmd[@]}" "$@"' exited with status 126
Call stack:
  1: ./hack/../build/common.sh:595 kube::build::run_build_command(...)
  2: ./hack/update-generated-protobuf.sh:58 main(...)
Exiting with status 1
```

**Comment by aveshagarwal** [comment]
permission denied? let me check why it says that

**Comment by smarterclayton** [comment]
That was the sudo check, before, or access to docker.

**Comment by aveshagarwal** [comment]
I was running it as root.

**Comment by mml** [comment]
Yeah, that is weird.  Do the permissions look right on `hack/after-build/update-generated-protobuf.sh`?

**Comment by mml** [comment]
Also, to rule out docker, can you do something simple like build inside docker?  I.e.,

```
% build/run.sh hack/build-go.sh
```

**Comment by aveshagarwal** [comment]
`build/run.sh hack/build-go.sh` runs fine.

**Comment by aveshagarwal** [comment]
I dont see this issue any more with `update-all.sh` on latest master so closing this.

**Comment by ecordell** [comment]
Had a similar issue, I believe caused by building first on OSX, then mounting the source into an ubuntu vm and attempting to build again without first running `make clean`
