### ISSUE TITLE
Allow Kube-Proxy and kubelets to use etcd-based sevice discovery for HA

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubernetes#24988]
This proposal is related to the following issues, but (I believe) not entirely duplicative of them:  #18623, #6363, #19443, #18174. If it is duplicative, then you know what to do ;-)

The way it is now: 

The APIserver and supports leader election, allowing for nearly seamless failover of the kube-master with simple configurations.  However kube-proxy and the kubelets on the workers will not see the new apiserver until their configuration is updated and restarted.  The official recommendation for this is to use an external load-balancer, but that's just kicking the problem down the road;  Kubernetes should, as much as possible, be the source of its own HA.

The simple fix:

Kubelet and Kube-proxy could allow use of etcd-based service discovery for locating the apiserver.  Combined with running an etcd node (in small clusters) or an etcd standby node (in larger clusters).  Combined with the other features which already exist, this would allow small to medium clusters to have fully automated kube-master failover "out of the box", using only tools we already use.

Drawbacks:

For larger clusters, load on etcd is already a bottleneck, and adding additional service discovery wouldn't help. However, dedicated clustered load-balancers make a lot more sense for a larger cluster, and should still be the recommended configuration for those.

**Comment by lavalamp** [comment]
Thanks for putting thought into this. Unfortunately letting non-apiserver components talk to etcd is a non-starter. It breaks encapsulation and the security model. (access to etcd == root on cluster). Running a separate etcd for this is too operationally complex.

This problem is solvable with local kubelet & kube-proxy changes, the system already exports enough information.

**Comment by beekhof** [comment]
@lavalamp Could you expand on or point the way to a document explaining the changes you have in mind for kublet & kube-proxy?

**Comment by lavalamp** [comment]
@mikedanese might know where to look for the latest plans around this.

**Comment by bogdando** [comment]
@lavalamp 
> Unfortunately letting non-apiserver components talk to etcd is a non-starter. It breaks encapsulation and the security model.

Do you mean both writing to and reading from/watching on? What if clients only to consume aliveness information for apiservers endpoints and nothing more? What tracks aliveness and update that info in etcd is a completely another story though. It may be apiservers itself, thus everything would be kept secure and encapsulated.

**Comment by lavalamp** [comment]
@bogdando: Right, I mean there should be zero network connectivity between etcd and anything other than apiserver.

immediate term solution: look at /api/v1/componentstatuses/ (IIRC) for etcd health.

longer term solution: the system should be self-hosted, etcd should be running in pods, and you can look at those pod objects to see if it is healthy (kubelet does health checks).
