### ISSUE TITLE
keystone insecure certificate override/ca specification

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#24984]
If you are deploying test OpenStack systems with self signed certs and want to test kubernetes/keystone authentication against it, it currently fails due to cert validation.

There needs to be two options to apiserver
 --keystone-insecure=true - Ignore certificate issues. Only for testing
 --certificate-authority=/path/to/ca.pem - Specify the certificate authority used to issue the keystone cert.

**Comment by idvoretskyi** [comment]
@kfox1111 what kind of OpenStack/Kubernetes deployment are you speaking about?

Please, provide us with the more detailed use case.

**Comment by kfox1111** [comment]
Ok, Say I deploy an OpenStack DevStack to do OpenStack development. I now have a Keystone running on a VM that I can test against. I then want to install Kubernetes on the same VM and point it at that development system with --experimental-keystone-url. There's no reason to create a properly secured SSL Keystone endpoint in this environment since it takes a lot of effort, and traffic won't ever leave the VM. We'd like to make it very easy to deploy both OpenStack & Kubernetes for developers. Ideally, we'd even write a DevStack plugin (shell script) to deploy Kubernetes along with the rest of the OpenStack bits all at once in this mode. Kubernetes will then get easy access to a bunch more developers.

**Comment by mkumatag** [comment]
Rightnow I don't see a way to establish a insecure connection via gophercloud package instead we can add a keystone ca.pem to the trusted directory, instruction mentioned [here](http://kb.kerio.com/product/kerio-connect/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html) for more information.

IMO with this we can close this issue.

**Comment by kfox1111** [comment]
I have added it to the proposed keystone token authentication docs.

**Comment by kfox1111** [comment]
I have added it to the proposed keystone token authentication docs.
