### ISSUE TITLE
Apiserver, there's no option to completly disable insecure access

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#24981]
Currently it's not possible to set `--insecure-bind-address` for the apiserver to a value that completely disables insecure access to the apiserver. The most secure option is to have it listen on localhost, but that means blocking access to localhost if you want to have other software running on the same host.

**Comment by zhouhaibing089** [comment]
> Currently it's not possible to set --insecure-bind-address for the apiserver to a value that completely disables insecure access to the apiserver.

I once heard from @liangjinebaycom that you could disable insecure access by setting `--insecure-port=0`.

**Comment by tristanz** [comment]
This is a dupe of https://github.com/kubernetes/kubernetes/issues/13598. While you can set `--insecure-port=0` this will currently break AdmissionControllers.

**Comment by hanikesn** [comment]
Closing because of dupe.
