### ISSUE TITLE
RFC: Adding test cases to e2e/volumes.go

### ISSUE THREAD

**Issue by rootfs** [kubernetes/kubernetes#24985]
# RFC: Adding test cases to [e2e/volumes.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/volumes.go)
## Background

As we are developing features and new volume plugins, the e2e test cases are not catching up at the same pace. This proposal aims to cover the security context and more volume plugins.
## Existing test cases in [e2e/volumes.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/volumes.go)

A storage server Pod that runs one of Glusterfs, NFS, Ceph RBD, Ceph FS, iSCSI, and OpenStack Cinder exports a file share. The file share containers a sample file. The test passes if a client Pod can mount the file share and test passes and read the sample file. 

Since the client Pod has SELinux label and fsGroup in securityContext, securityContext must be enabled. The server container runs in privileged mode, so kubelet must allow privileged mode.
## Existing Red Hat Tests proposed for transfer to Kubernetes E2E Test Environment

| Test Case | PR | Status |
| --- | --- | --- |
| 1 | #25100 |  |
| 2 |  |  |
| 3 |  |  |
| 4 |  |  |
| 5 |  |  |
| 6 |  |  |
| 7 |  |  |
### 1. Support more volume plugins

Similar to the existing server Pods, we want to test against other volume plugins such as EBS, GCE PD, git repo, and probably fibre channel and Azure file.
#### 2. Verify that client Pod with correct gid could access the volume
- Setup. In server (not NFS) Pod, if the file share’s gid is unknown, set the file share’s gid to 100001 (chown root:100001 /path/to/share). In client Pod, set supplementalGroups to the same gid
- Expected result: client Pod can read sample on the file share
#### 3. Verify that client Pod with wrong gid cannot access the volume
- Setup. In server (not NFS) Pod, if the file share’s gid is unknown, set the file share’s gid to 100001 (chown root:100001 /path/to/share). In client Pod, set supplementalGroups to 100002
- Expected result: client Pod can not read sample on the file share
#### 4. Verify the files created by client Pod under the volume has expected uid/gid
- Setup. In server (not NFS) Pod, if the file share’s gid is unknown, set the file share’s gid to 100001 (chown root:100001 /path/to/share), set the file share to be writable. In client Pod, set supplementalGroups to 100001 and RunAsUser to 100002, client Pod writes a file to the file share
- Expected result: client Pod can write to the file share and the file’s uid is 100002 and gid is 100001 (or the file share's gid if it is known)
#### 5. For block storage (iSCSI, Ceph RBD,  AWS EBS, GCE PD, and OpenStack Cinder), verify the volume has expected gid as in fsGroup
- Setup. In server (not NFS) Pod, if the file share’s gid is unknown, set the file share to be writable. In client Pod, set fsGroup to 100001 and RunAsUser to 100002, client Pod writes a file to the file share
- Expected result: client Pod can write to the file share and the file’s uid is 100002 and gid is 100001 (or the file share's gid if it is known)
#### 6. Verify directory with expected selinux label
- Setup. In server (not NFS) Pod, set the file share to be writable. In client Pod, set seLinuxOptions to “s0:c13,c2”, client Pod writes a file to the file share
- Expected result: client Pod can write to the file share and the file’s selinux label is “s0:c13,c2”

@kubernetes/sig-storage @kubernetes/sig-testing

**Comment by jayunit100** [comment]
Thanks @rootfs this is a great outline.  these should be genericized.  we should also support the `--scale` option in these tests to for any volumes supporting N clients

**Comment by jeffvance** [comment]
@rootfs These look great. The focus here seems to be security/access of pod to volume, which is important to test.
I am looking at adding PV->PVC bind testing to test that  PVs / claims are bound to the correct target and released/recycled correctly, especially in cases where the PV or claim is pre-bound. I'll add the pr# here.

**Comment by rootfs** [comment]
@jeffvance yes, this is just for e2e/volumes.go. Will have another one for [e2e/persistent_volumes.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/persistent_volumes.go), which covers PV/PVC tests.

**Comment by jeffvance** [comment]
@rootfs Should my new/updated pv bind tests be place in the test/e2e dir, or under controller/persistentvolume/?

**Comment by rootfs** [comment]
e2e test goes to [e2e] (https://github.com/kubernetes/kubernetes/blob/master/test/e2e), unit test goes to controller/persistentvolume, integration test goes to [integration](https://github.com/kubernetes/kubernetes/tree/master/test/integration)

**Comment by jeffvance** [comment]
@rootfs Thanks for the pr above. There are a lot of tests there.

**Comment by rootfs** [comment]
opened #25100 to support GCE PD

**Comment by humblec** [comment]
@rootfs Thanks, this outline looks great!. I have one small suggestion here, we should clarify some more on `set the file share to be writable`.  As per me, we should mention exactly what are the the user/group permission bits  on this share. 
 ```
4. Verify the files created by client Pod under the volume has expected uid/gid
 Setup. In server (not NFS) Pod, if the file share’s gid is unknown, set the file share’s gid to 100001 (chown root:100001 /path/to/share), set the file share to be writable. In client Pod, set supplementalGroups to 100001 and RunAsUser to 100002, client Pod writes a file to the file share```

**Comment by jeffvance** [comment]
Would like to see a priority label on this issue. @rootfs do you think it's a p1 now?

**Comment by msau42** [comment]
@rootfs can this be closed?
