### ISSUE TITLE
Refactor kubernetes scheduler and controller manager to enable code reuse

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#24996]
Forked from https://github.com/kubernetes/kubernetes/pull/24038#issuecomment-215610094

We are adding federation scheduler and controller manager as per the plan in https://github.com/kubernetes/kubernetes/issues/23653.

There is obviously some common code that is shared with kubernetes controller manager and kubernetes scheduler.
We want to pull out that code into libraries to enable code reuse rather than having to duplicate code.

We need to figure out the right name and directory structure for such libraries.

cc @davidopp @madhusudancs @kubernetes/goog-control-plane @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
Note that there was same issue with kubernetes and federation apiserver. We now have a library `pkg/genericapiserver` that solves that problem.

**Comment by nikhiljindal** [comment]
Marking this 1.3 since this is also required for cluster controller which is planned for 1.3.
Scheduler is not strictly required for 1.3

**Comment by nikhiljindal** [comment]
For reference, cluster controller PR is https://github.com/kubernetes/kubernetes/pull/23430 and federation scheduler PR is https://github.com/kubernetes/kubernetes/pull/24038

**Comment by nikhiljindal** [comment]
I discussed this with @davidopp and summarizing our discussion here:

controller-manager:
* Common code: Setting up the binary: command line arguments (adding flags, parsing them, setting defaults, validating values). Mostly the code in `cmd/` directory.
* Different code: Which controllers to run, business logic in each controller.

We do want to refactor common code, but dont necessarily want to block the controller PR on that.


Scheduler: There should not be a lot of common code between federation and kubernetes schedulers.
* The core business logic in both the schedulers will be very different (kube scheduler watches pods and sends POST requests to pod bindings while fed scheduler will watch replicasets and POST sub replicasets).
* There will be some common command line flags related to talking to API server (URL, auth, etc) but that is same for any component talking to API server (like kubelet). nothing special with federation scheduler

So we can start with federated scheduler independently and if it later turns out that there is a lot of common code (which we hope will not happen), we can refactor.


So neither scheduler nor controller manager is blocked on refactoring.

**Comment by davidopp** [comment]
> We do want to refactor common code, but dont necessarily want to block the controller PR on that.

Yeah, it sounds like we don't have time to figure out and implement exactly the "right" way to do the refactoring. But we need to do it right after 1.3 ships. We can't leave this duplicated code around.

**Comment by quinton-hoole** [comment]
This fits into what @mwielgus is working on.  Tentatively assigning to him so that we don't lose track of it.

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by timothysc** [comment]
@jayunit100 This is part of the 1.6 cleanup items for you.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#42.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
