### ISSUE TITLE
shells made with exec or attach have wonky readline behavior

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/kubernetes#25012]
When logging into a specific pod with kubernetes 1.2.2 client (into a 1.2.2 server pod) with a shell for interactive behavior like so:

    kubectl --namespace=prod exec -it godebug-534338858-5fxr2-2376885364-ip0ry /bin/bash

the shell has wonky behavior when a line gets too long. 

The easiest and clearest way to reproduce the problem is to type in a command that goes longer than your terminal's width, and see that the text starts to overlaps the text at the beginning of the same visual line on the terminal.

There's similar problems when you hit "up" to grab a previously run long command and edit it.

**Comment by jmhodges** [comment]
(Interestingly, even if you resize the terminal and you hit "up" to get a command that was overlapping, that new instance of the command will also show up as overlapping the text on the same line.)

**Comment by jmhodges** [comment]
Ah, it's not even getting resize notifications. Maybe it's because I'm following the GKE instructions and running my kubectl commands in a docker instance and SIGWINCH isn't being forwarded from the wrapping docker process to the `kubectl exec` instance?

**Comment by jmhodges** [comment]
Ah, yep, this is https://github.com/kubernetes/kubernetes/issues/13585

**Comment by jmhodges** [comment]
Actually, the text overlapping itself seems to be a bug separate from the SIGWINCH stuff, maybe?

**Comment by jmhodges** [comment]
Ah! That's because the PS1 in this container had `${debian_chroot:+($debian_chroot)}` at the beginning of it. It had been

    PS1="${debian_chroot:+($debian_chroot)}\u@\h:\w\$ "

and changing that to

    PS1="\u@\h:\w\$ "

fixed the issue.

This doesn't occur when I run the image with `docker run` on its own. So, probably another `kubectl exec` bug but I'm not sure what.

**Comment by jmhodges** [comment]
I've made https://github.com/kubernetes/kubernetes/issues/25013 with just the overlapping text PS1 problem.

**Comment by gopishrk** [comment]
The overlapping issue disappeared when:
1. Opened ssh session in putty with window size of putty is not maximized
2. Opened docker shell from the above ssh session using command 'docker exec -it <container_name> /bin/bash'
3. Maximized window size of the putty, now the overlapping issue is gone
