### ISSUE TITLE
make-ca-cert.sh , easy-rsa download breaks when inside firewallproxy.

### ISSUE THREAD

**Issue by jsfeutz** [kubernetes/kubernetes#25016]
Was working on installing via kubernetes/docs/getting-started-guides/docker-multinode/

Tried different http_proxy/https_proxy env settings in both docker, and passing to the script. The initial container sets correctly.. but the containers kicked off by the initial container do not set proxy correctly. So  apiserver container starts up complains about missing ca.crt. 

--> line in make-ca-cert.sh
curl -L -O http://storage.googleapis.com/kubernetes-release/easy-rsa/easy-rsa.tar.gz > /dev/null 2>&1
tar xzf easy-rsa.tar.gz > /dev/null 2>&1

side note--->
For those of behind a Corporate firewall, usually we are running a Private Registry or Proxying the public registries with artifactory or nexus. Simply creating ENV variables that we can set the image source and repo variables would be useful so we repoint the scripts to internal mirrors.

*Read about Artifactory proxying
K8S_REPO=gcr.io  (could change to myrepo.com/google_containers/hybercube-amd64:v1.2.3
GAPI_REPO=storage.googleapis.com

**Comment by jimmyjones2** [comment]
Fixed in #24218
