### ISSUE TITLE
resource.Quantity allocates too many objects in conversion and decoding

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#25019]
Calling the .Round() operation to maintain compat with millisecond values is ~90% of the optimized node conversion/decode path in terms of allocations, and the more resources we have, the more expensive it gets.  In addition, quantities are rarely compared, but we do the decode of the value eagerly, which is expensive.  Quantity needs to get much more efficient.

Some areas to investigate:

1. Can we reduce the number of allocations in normal use of Quantity and inf.Dec without more drastic changes?
2. Can we make .String() on a Quantity much more efficient, and then potentially defer decoding it unless we need to change it?  Right now it's a large part of Node and Pod output, and is likely going to impact the scheduler more than other components.  (a naive implementation of this was tried, but String() is far too expensive to be a speed up).
3. Can we do a "fast path" for Quantities that have less precision than int64 (99.99% of them) that is efficient?
4. We should create benchmarks for the following quantity operations - serialization to JSON, string(), copy, round, and validation

Quantity is now the primary source of allocations during encode/decode/conversion after protobuf and the other conversion improvements are taken into account.  If we can tackle this for 1.3 we can potentially get another 10-25% improvement in master CPU for anything with quantity (pods, nodes, quota, limit ranges, scheduling).

**Comment by smarterclayton** [comment]
@kubernetes/sig-scalability @kubernetes/sig-api-machinery

**Comment by hongchaodeng** [comment]
The problem described here sounds very similar to what we have tackled in https://github.com/kubernetes/kubernetes/pull/18170.
We could extend that to more use cases.

**Comment by smarterclayton** [comment]
Yeah, round() is the big culprit, but String() and parse from string are also significant.  We'd need all three of those to make a dent - quantity protobuf representation should really be a string, but we'd need a path forward here to make it worthwhile.

**Comment by smarterclayton** [comment]
Current state:

```
 go test ./pkg/api/resource -benchmem -run=XXX -bench=Benchmark -test.memprofile mem.out
PASS
BenchmarkQuantityString-8       	 1000000	      1144 ns/op	     464 B/op	      13 allocs/op
BenchmarkQuantityMarshalJSON-8  	 1000000	      1223 ns/op	     475 B/op	      14 allocs/op
BenchmarkQuantityUnmarshalJSON-8	 1000000	      2377 ns/op	     944 B/op	      24 allocs/op
BenchmarkParseQuantity-8        	 1000000	      2161 ns/op	     906 B/op	      22 allocs/op
BenchmarkCanonicalize-8         	 1000000	      1102 ns/op	     461 B/op	      13 allocs/op
BenchmarkQuantityCopy-8         	10000000	       159 ns/op	     123 B/op	       2 allocs/op
BenchmarkQuantityAdd-8          	 1000000	      1034 ns/op	    2723 B/op	       1 allocs/op
BenchmarkQuantityRound-8        	50000000	        29.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkScaledValueSmall-8     	30000000	        36.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkScaledValueLarge-8     	 3000000	       518 ns/op	      48 B/op	       1 allocs/op
```

Going to look into a couple of options w.r.t. faster behavior.

**Comment by smarterclayton** [comment]
Benchmarks are here https://github.com/kubernetes/kubernetes/pull/25229

**Comment by lavalamp** [comment]
I'm definitely on board with optimizing this if needed. It is super well tested, so not too much fear of breaking things.

**Comment by smarterclayton** [comment]
Tried out some optimizations in #25243.

1. Turned Quantity.Amount into an interface to try having an *inf.Dec impl and an int64 impl
2. Gave the Amount impls an `AsInt64() (int64, bool)` to allow fast comparisons and addition (when scales match)
3. Added a fast path to ParseQuantity that looked for strings without decimals and created an int64 amount
4. Reused more bigs during addition

Some other optimizations I have not tried yet

1. Avoid the `[]string` creation from the regex (we always get 3 parts, we can do a state machine here)
2. The regex is slow - avoid it altogether (same state machine as above)
3. Add a "round" method that the API conversion function can use that for int64 is faster - `Round` on quantity *sucks*


```
BenchmarkQuantityString-8       	 1000000	      1130 ns/op	     405 B/op	      12 allocs/op
BenchmarkQuantityMarshalJSON-8  	 1000000	      1239 ns/op	     416 B/op	      13 allocs/op
BenchmarkQuantityUnmarshalJSON-8	 1000000	      1255 ns/op	     244 B/op	       7 allocs/op
BenchmarkParseQuantity-8        	 1000000	      1034 ns/op	     207 B/op	       5 allocs/op
BenchmarkCanonicalize-8         	 1000000	      1067 ns/op	     402 B/op	      11 allocs/op
BenchmarkQuantityCopy-8         	10000000	       167 ns/op	     123 B/op	       2 allocs/op
BenchmarkQuantityAdd-8          	10000000	       161 ns/op	     112 B/op	       3 allocs/op
BenchmarkQuantityRound-8        	30000000	        35.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkScaledValueSmall-8     	30000000	        39.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkScaledValueLarge-8     	 3000000	       546 ns/op	      48 B/op	       1 allocs/op
```

**Comment by smarterclayton** [comment]
5. For Canonicalize(), `Round` and `removeFactors` is slow, mostly because of the allocations but also the big decimal mods.  An int64 version should be significantly faster.

**Comment by davidopp** [comment]
That package predated my joining the project and always struck me as overgenerality. Is there any reason we can't just use int64 for our internal representation of every resource quantity? I am unable to think of any resource for which that wouldn't work. Maybe there's something I'm not seeing...

If we could just use int64 internally, then we could convert to/from the current resource.Quantity just for the benefit of compatibility with end-user (not internal cluster) clients?

**Comment by wojtek-t** [comment]
Some of the gains are quite significant, e.g. 2x on "BenchmarkQuantityUnmarshalJSON-8".

>
That package predated my joining the project and always struck me as overgenerality. Is there any reason we can't just use int64 for our internal representation of every resource quantity? I am unable to think of any resource for which that wouldn't work. Maybe there's something I'm not seeing...

Actually - that was also my question. @smarterclayton can you please clarify the reason why we have it?

**Comment by smarterclayton** [comment]
First goal was correctness and generality of definition. I.e., that we have a consistent resource definition we can apply in many places.

As for where an int64 is not enough, precision aspects on very large quotas would be the first thing I can think of.  Rollup of 10GB across a thousand pods is very close to the int64 precision.  As we move to connected clusters, I would expect global quota / count values to exceed int64.

All that said, I think my current path is to continue to implement an int64 version that can overflow to Dec without consumers being aware - we would get the benefit of both.

**Comment by smarterclayton** [comment]
In the init PR I noticed that a lot of places are actually using Quantity.Value() today, which returns an int64, and is using that for calculations.  So we're potentially using Quantity in a way that doesn't benefit from Dec() in many cases.

@derekwaynecarr because you noticed this on init containers and I noticed that we were using Value()

**Comment by smarterclayton** [comment]
And we are doing comparisons on those int64

**Comment by davidopp** [comment]
Hopefully I'm not giving away any state secrets, but the per-cluster quotas at Google are expressed in int64 and I've never heard a request that it be changed to a larger datatype. At the risk of sounding provincial, if int64 is large enough for quotas at Google, I'd question whether there will exist Kubernetes installations that will need something larger. Now, you could argue (as you seem to be) that federation in Kubernetes might result in Kubernetes systems that are larger than a single Google cluster, but I would argue that right now we should be optimizing for simplicity and performance rather than that distant future possibility.

**Comment by smarterclayton** [comment]
I'm hesitant to throw out the Dec implementation, but I am pretty convinced
we should have an int64 implementation, and if we're going to do that we
should at least consider the possibility of overflow promotion into the
higher order.

**Comment by lavalamp** [comment]
@davidopp ah yes, but internally we don't store memory in millibytes! ;)

(this is a joke about previous bugs in resource.Quantity-- for anyone who hasn't followed it carefully)

More seriously, the metrics API IIRC does want to store things in nanocores for some reason or other. Expanding beyond int64 might be needed. I'm on board with a int64 implementation as long as there's a fallback.

**Comment by davidopp** [comment]
@timstclair @vishh @piosz Is it true that the node-level or master-level metrics API wants to measure things in nanocores? If so, why?

**Comment by wojtek-t** [comment]
yeah - nanocores granurality sound at least strange; are we even able to e.g. force limits at the level of nanocores?

**Comment by vishh** [comment]
@davidopp 
Milli-cores is the current precision for CPU in our API. Kubelet exposes Cpu in nano-cores mainly because the kernel provides that granularity and we decided to let the callers round up according to their needs. I don't see why metrics APIs would expose CPU with any higher precision than Millicores.

**Comment by smarterclayton** [comment]
I have an int64 implementation where we can plug in overflow calculations to the existing inf.Dec implementation, and with that we should have a fast path and an unbounded-precision path that callers can be oblivious to.  Will work on that over the next week or so - don't see why we can't have this for 1.3.

**Comment by derekwaynecarr** [comment]
@smarterclayton - we will need to make sure the cluster resource overcommit
handler in origin plays well with this.  That was the plugin that was the
source of millibytes bug :-).   In general, I never met a big number
library I liked so int64 for common case works well for me.  No more
fractional bytes!

**Comment by smarterclayton** [comment]
Actually... in ParseQuantity, we have:

```
	// The max is just a simple cap.
	if amount.Cmp(maxAllowed.Dec) > 0 {
		amount.Set(maxAllowed.Dec)
	}
```

So in practice... we weren't dealing with overflow on stored quantities, just on live quantities.

**Comment by smarterclayton** [comment]
With a "mostly" complete implementation that can check for overflow and promote up the int64 version, for all int64 values we're down significantly:

```
BenchmarkQuantityString-8       	10000000	       217 ns/op	       7 B/op	       2 allocs/op
BenchmarkQuantityMarshalJSON-8  	 5000000	       309 ns/op	      18 B/op	       3 allocs/op
BenchmarkQuantityUnmarshalJSON-8	 1000000	      1109 ns/op	     173 B/op	       4 allocs/op
BenchmarkParseQuantity-8        	 2000000	       879 ns/op	     135 B/op	       2 allocs/op
BenchmarkCanonicalize-8         	10000000	       153 ns/op	       4 B/op	       1 allocs/op
BenchmarkQuantityCopy-8         	20000000	        57.4 ns/op	      48 B/op	       1 allocs/op
BenchmarkQuantityAdd-8          	20000000	        58.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkQuantityRound-8        	50000000	        27.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkScaledValueSmall-8     	30000000	        39.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkScaledValueLarge-8     	 3000000	       539 ns/op	      48 B/op	       1 allocs/op
```

Going to optimize the parse path to avoid the regex, and then work to fix up the remainder in marshal/unmarshal.  Add could probably be faster without the overflow checks, and I'm sure there's some non-optimal things I'm doing in there w.r.t. scale precision that might have shortcuts.

**Comment by piosz** [comment]
In Master Metrics API we have the same unit that in requests/limits which is milli-cores.

**Comment by smarterclayton** [comment]
Finished String/JSON optimization, parse is all that is left.

```
BenchmarkQuantityString-8        	10000000	       167 ns/op	      23 B/op	       2 allocs/op
BenchmarkQuantityStringBinarySI-8	10000000	       212 ns/op	      32 B/op	       2 allocs/op
BenchmarkQuantityMarshalJSON-8   	10000000	       150 ns/op	      35 B/op	       1 allocs/op
BenchmarkQuantityUnmarshalJSON-8 	 1000000	      1010 ns/op	     173 B/op	       4 allocs/op
BenchmarkParseQuantity-8         	 2000000	       806 ns/op	     135 B/op	       2 allocs/op
BenchmarkCanonicalize-8          	20000000	        83.8 ns/op	       3 B/op	       0 allocs/op
BenchmarkQuantityCopy-8          	20000000	        54.5 ns/op	      48 B/op	       1 allocs/op
BenchmarkQuantityAdd-8           	50000000	        32.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkQuantityRound-8         	50000000	        25.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkScaledValueSmall-8      	30000000	        35.3 ns/op	       0 B/op	       0 allocs/op
BenchmarkScaledValueLarge-8      	 3000000	       514 ns/op	      48 B/op	       1 allocs/op
```

**Comment by smarterclayton** [comment]
I think this is the bulk of the low hanging fruit.  We *could* keep the value as a string and on demand convert it to a value if we manipulate it, but that'll make the object bigger.

```
BenchmarkQuantityString-8        	10000000	       175 ns/op	      23 B/op	       2 allocs/op
BenchmarkQuantityStringBinarySI-8	10000000	       214 ns/op	      32 B/op	       2 allocs/op
BenchmarkQuantityMarshalJSON-8   	10000000	       156 ns/op	      35 B/op	       1 allocs/op
BenchmarkQuantityUnmarshalJSON-8 	10000000	       194 ns/op	       2 B/op	       1 allocs/op
BenchmarkParseQuantity-8         	10000000	       142 ns/op	       0 B/op	       0 allocs/op
BenchmarkCanonicalize-8          	20000000	        89.2 ns/op	       3 B/op	       0 allocs/op
BenchmarkQuantityCopy-8          	20000000	        55.0 ns/op	      48 B/op	       1 allocs/op
BenchmarkQuantityAdd-8           	50000000	        33.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkQuantityRound-8         	50000000	        25.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkScaledValueSmall-8      	30000000	        35.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkScaledValueLarge-8      	 3000000	       511 ns/op	      48 B/op	       1 allocs/op
```

Ready to take review on the other PR.
