### ISSUE TITLE
"Running Kubernetes Locally via Docker" Guide is not working at all for MacOS, ssh command just hanging

### ISSUE THREAD

**Issue by xhe** [kubernetes/kubernetes#25023]
I am following this Guide to start using Kubernetes on MacOS. Is this guide valid? 

1. When I am doing this step:
```shell
docker-machine ssh `docker-machine active` -N -L 8080:localhost:8080
```
They command is hanging, no repsponse at all;

2. Looking at docker ps -l, I have 
`CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
b1e95e26f46d        gcr.io/google_containers/hyperkube-amd64:v1.2.3   "/hyperkube apiserver"   About an hour ago   Up About an hour                        k8s_apiserver.c08c1df_k8s-master-127.0.0.1_default_d95a6048198f747c5fcb74ee23f1f25c_d0c6d2fc`
So it means kubernete is running

3. I run this command:
`docker-machine ssh `docker-machine active`  -L 8080:localhost:8080`
I can login to docker machine, then exit, run kubectl get nodes again, hanging, no response

Anything wrong here?
If this step can not pass, how can I use Kubernete?

Any help is appreciated.

Thanks

**Comment by luxas** [comment]
@vishh

**Comment by vishh** [comment]
@xhe 
```shell
docker-machine ssh `docker-machine active` -N -L 8080:localhost:8080
```
This command will start a ssh tunnel. This command will itself not generate any output. You should be able to use `kubectl` while this command is running.

You can also run this command in the background by adding `-f` option to `docker-machine ssh`. If you do that, you will have to manually identify the "ssh" tunnel process and kill it once you are done. More helpful info on ssh tunnels [here](https://gist.github.com/scy/6781836)

**Comment by xhe** [comment]
Thank you!
Now for this guide:
http://kubernetes.io/docs/user-guide/quick-start/
After I run:

kubectl run my-nginx --image=nginx --replicas=2 --port=80 --expose
--service-overrides='{ "spec": { "type": "LoadBalancer" } }'


I run:  kubectl get po

I do see:

my-nginx-3800858182-52as6   1/1       Running   0          6m

my-nginx-3800858182-mddua   1/1       Running   0          6m


And:

kubectl get service/my-nginx

NAME       CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE

my-nginx   10.0.0.224                 80/TCP    8m


But when I visit:

http://10.0.0.224/
It is totally blank, not available

I am using MacOs.

Any idea why?

Thanks

**Comment by vishh** [comment]
cc @pwittrock 

This is a problem with our documentation. Services are not accessible directly while running on OSX. You need to ssh into docker-machine VM to access the service, or add `--type=NodePort` to `kubectl expose ...` and use the `NodeIP:Port` for the service.

**Comment by pwittrock** [comment]
Right now there isn't a great way to document this since it is specific per-cluster type.

**Comment by pwittrock** [comment]
@dlorenc FYI

**Comment by pwittrock** [comment]
We hope to be fixing this in [minikube](https://github.com/kubernetes/minikube).
