### ISSUE TITLE
Authorization and Capabilites

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#2502]
Proposal:

Define an enum of Capabilities, to include:
  - `KubeCapHostDir`: allows arbitrary hostDir volumes.
  - `KubeCapPrivCont`: allows running privileged containers.
  - other items to be added late

Define a new function in the `Attributes` interface (defined in pkg/auth/authorizer/interfaces.go) called `CapabilitiesNeeded() []string`. 

When a request (create or update pod) arrives which would imply a Capability, it is added to the list of capabilities needed.  (This would happen in `func (r *requestAttributeGetter) GetAttribs(req *http.Request) authorizer.Attributes` in pkg/apiserver/handlers.go.)

Policy such as in `pkg/auth/authorizer/abac/abac.go` is extended to have a "CapabilitiesAllowed` field.

The Authorizer rejects as Forbidden any requests which need a capability string, but don't have one.   The match logic for capabilities would be somewhat different from the other fields: a request with no CapabilitiesNeeded could match a Policy which has some CapabilitiesAllowed, but not vice-versa.

Add policy objects with CapabilitiesAllowed to users that need it.

**Comment by erictune** [comment]
#4849

**Comment by bgrant0607** [comment]
Host networking (#175) is another example.

**Comment by erictune** [comment]
Capability could guard ability to request  Access to host device #5607

**Comment by smarterclayton** [comment]
I think this is resolved by pod security policy in #7893

**Comment by smarterclayton** [comment]
All use cases described here have been implemented.
