### ISSUE TITLE
why securityContext is not in ServiceAccount?

### ISSUE THREAD

**Issue by chengyli** [kubernetes/kubernetes#25025]
In Service Account design document, the securityContext is included in ServiceAccount struct,
But I saw that ServiceAccount struct doesn't include securityContext in the lastest code, is there any background for this change? 

Without the namespace level securityContext, if I want to forbidden all pods in cluster to run as root user by default, how to handle then?

https://github.com/kubernetes/kubernetes/blob/master/docs/design/service_accounts.md
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1575

**Comment by liggitt** [comment]
security context policy was never part of the service account implementation, that design should be updated. The `PodSecurityPolicy` object (https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/security-context-constraints.md) is intended to allow control over pod security context. Granting API users or service accounts permission to use a particular PodSecurityPolicy is being tracked in https://github.com/kubernetes/kubernetes/issues/23217

cc @pweil-

**Comment by pweil-** [comment]
Right, this definitely needs to be updated if it still shows the SC as part of an SA.  

@chengyli the ability to control settings is the SC is part of the PSP work that was mentioned.  The initial implementation is in the works (https://github.com/kubernetes/kubernetes/pull/24600).  The idea behind it is that an admin can define cluster level policies that can provide defaulting and validation for requests to ensure that they are within the allowable ranges.  This includes the ability to run as root.  

Currently there is also a `RunAsNonRoot` option in the SecurityContext that will trigger a check by the kubelet to ensure that either a `RunAsUser` is set or the image itself defines a UID.  This could be set by a custom admission controller right now but ultimately that will be the job of the PSP.

**Comment by chengyli** [comment]
@pweil- @liggitt Thanks for the clarification! I shall read PodSecurityPolicy releated doc and code.
