### ISSUE TITLE
Presubmit for sed -> jinja translators

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#25031]
So we avoid situations like: https://github.com/kubernetes/kubernetes/pull/24124/commits/fa9d79df75d0a5326fb6ca72308ebbaf5bde603e#r61679635

Obviously this is not needed if we just get rid of the sed, salt, jinja, etc. 
I don't know which team this belongs to, the team that cares about the sed stuff? If someones adding more jinja, it shouldn't break our non-jinja setup scripts.

**Comment by mml** [comment]
By presubmit I think we just mean a test.  @thockin since you commented on the original PR, can you say what the correct team label is?

**Comment by bprashanth** [comment]
like one of those verify-foo-bar.sh/py things that keeps failing when I try to upload a badly vetted go file
