### ISSUE TITLE
Move pods.go e2e to the node suite

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#25049]
[pods.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/pods.go) tests pod level features. It can be moved to the node e2e. 
If there are parts of the test that are testing the API server and not the kubelet, then those parts can be retained and the rest can be moved.

The move might be as trivial as,

``` shell
git mv test/e2e/pods.go test/e2e_node/pods_test.go
sed -i 's/framework.NewDefaultFramework/NewDefaultFramework/g'
# verify the new test
make test_e2e_node
```

cc @kubernetes/sig-node

**Comment by vishh** [comment]
@dubstack do you want to try posting a PR for this?

**Comment by dubstack** [comment]
Yes I will take a stab at this.

**Comment by yujuhong** [comment]
It's now `test/e2e/node/pods.go`, but the issue is still relevant
/remove-lifecycle stale
