### ISSUE TITLE
Propagating grace period in a cascading deletion

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#25055]
An example of "Propagating grace period" is in a cascading deletion of a Replica Set and its Pods, if a user deletes the Replica Set with 30s grace period, the Pods should be deleted with the same grace period. See https://github.com/kubernetes/kubernetes/pull/23656#issuecomment-215612461.

In the proposal for cascading deletion (#23656), we note that we will not propagate the grace period when implementing the garbage collector, though the design can be extended to support the grace period propagation. We will discuss related problems here.

@lavalamp @smarterclayton @kubernetes/sig-api-machinery

**Comment by derekwaynecarr** [comment]
I am not in favor of cascading grace period.

See discussion here:
https://github.com/kubernetes/kubernetes/pull/24964

**Comment by smarterclayton** [comment]
There was a discussion somewhere about separating cascade and delete propagation and ensuring they were clearly distinguishable from each other.

**Comment by xiang90** [comment]
@caesarxuchao What is the current progress on this issue?

**Comment by caesarxuchao** [comment]
GC doesn't propagate the grace period. Is there a new use case?

**Comment by ecsdigitalih** [comment]
has this issue been resolved?

**Comment by paultiplady** [comment]
Looks like this issue has died through inactivity -- would just like to record my use-case here in case that's useful.

Suppose we have a Deployment that's running pods which could be executing a long-running task (e.g. a worker of some sort). It would be ideal for that worker to be killable at any time, but if it's interacting with an external system (e.g. transmitting payments, sending emails) then it's not always possible to determine the state of the in-process work, and so we'd rather not pull the rug out from an in process worker.

Many workers (such as Celery) support graceful termination, such that they refuse new work and finish currently in-progress work; it would be ideal to be able to use this behaviour, by sending a SIGTERM to the pod and then waiting an hour or two for the worker to drain.

This could be supported by deleting the pod manually, with a grace period. But it doesn't seem to be supported for a Deployment rollout, making that operation unsafe.

@derekwaynecarr is there a different mechanism that you favour for handling this sort of graceful termination in Kubernetes?

**Comment by rekhachougule** [comment]
> Looks like this issue has died through inactivity -- would just like to record my use-case here in case that's useful.
> 
> Suppose we have a Deployment that's running pods which could be executing a long-running task (e.g. a worker of some sort). It would be ideal for that worker to be killable at any time, but if it's interacting with an external system (e.g. transmitting payments, sending emails) then it's not always possible to determine the state of the in-process work, and so we'd rather not pull the rug out from an in-progress worker.
> 
> Many workers (such as Celery) support graceful termination, such that they refuse new work and finish currently in-progress work; it would be ideal to be able to use this behaviour, by sending a SIGTERM to the pod and then waiting an hour or two for the worker to drain.
> 
> This could be supported by deleting the pod manually, with a grace period. But it doesn't seem to be supported for a Deployment rollout, making that operation unsafe.
> 
> @derekwaynecarr is there a different mechanism that you favour for handling this sort of graceful termination in Kubernetes?

yes , --grace-period is not working ofr me also, but it worked when set through .yaml file i.e terminationGracePeriodSeconds
