### ISSUE TITLE
Allow nodes with no internet connection to become master nodes

### ISSUE THREAD

**Issue by MartinPyka** [kubernetes/kubernetes#25050]
Hi, 

I am trying to get a kubernetes cluster running in offline mode (no internet connection in production). I ran into the same issue as reported here:

https://github.com/kubernetes/kubernetes/issues/23976

Following the code links in issue 23976 I found the following comment in 
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/net/interface.go#L200

> //ChooseHostInterface is a method used fetch an IP for a daemon.
> //It uses data from /proc/net/route file.
> **//For a node with no internet connection ,it returns error**
> //For a multi n/w interface node it returns the IP of the interface with gateway on it.

Is this correct? Do I really need to have an internet connection to run e.g. kube-apiserver?

Studying the code at https://github.com/kubernetes/kubernetes/blob/master/pkg/util/net/interface.go#L238 it seems that the code is looking for an interface that occurs in /proc/net/route and has 00000000 as destionation. This could be easily changed! 

Could you change the code in a way that an internet gateway is not necessary? Shouldn't be a big deal, should it? 

Or am I missing here something else. Is there anyway to start kube-apiserver without being connected with the internet?

**Comment by mml** [comment]
To be a little more specific, it's not just that you're not connected to the open internet (which shouldn't be required), but that you have no gateway at all.  The entire universe of machines you want to talk to or manage is on the local network with you.

This strikes me as a reasonable arrangement to make work in a lab setting or from within VMs all living together in an unrouted virtual network.

**Comment by MartinPyka** [comment]
Wouldn't it be way easier and safer if the host interface would be a config parameter rather then selecting one based on heuristics? Then those people who are working in closed and very restricted settings would have an easier time getting kubernetes running!?

**Comment by MartinPyka** [comment]
can be closed
