### ISSUE TITLE
Easy deployment for workflow (and possibly other API objects in the future)

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#25067]
There are a lot of workflow systems out there, which suggests that different people have different requirements and there is no perfect solution. As a result, there is reluctance to make [workflow](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/workflow.md) be a "core" API in Kubernetes. On the other hand, workflow (or at least simple job pipelines) is a very important feature. So if workflow is not a core API object, we want there to be at least one trivial-to-install-and-use workflow controller, that integrates seamlessly with users' normal interaction with Kubernetes. This issue is about how we can achieve that.

Ideally, whatever approach we use here can be used for other API objects that may arise in the future, i.e. alternative workflow implementations and other important controllers that we don't want to be a core API object. Creating a generic package manager is a non-goal--we're focusing here on functionality that runs as part of the Kubernetes control plane, not applications you would run on top of Kubernetes. We assume the functionality is expressed as a controller and a REST interface

Offline @brendandburns suggested
- controller runs in a pod on the user's cluster
- user interacts with the controller via ThirdPartyResource
- the controller or something else running in the same pod as the controller is responsible for creating the relevant ThirdPartyResource if it doesn't exist

So all the user would have to do to start using it is
`kubectl run workflow-controller --image=XXX...`
which would launch the controller and register the new type.

For key functionality like workflow, we could build a Docker image for it with every Kubernetes release (like we do for Heapster), just to make sure it really is available and up-to-date. We should also integrate testing it into the CB, though IIUC we haven't really solved the CB-spanning-repos problem so if the code goes into contrib, this may not be possible initially, and we'd only test systematically as part of qualifying a release.

The only downsides I can see compared to a core API resource are
1. extra "installation" step, though it's just one line so hard to complain about that
2. kubectl won't have any native understanding of the resource  (unless we somehow make kuebctl extensible at runtime), so `kubectl describe workflow` (or whatever) couldn't pretty-print like we do for the "core" API objects ([job](https://github.com/kubernetes/kubernetes/blob/ee2a0694b649941fc0c3be606746db041b75b91d/pkg/kubectl/describe.go#L1092) etc.).
3. the testing issue I mentioned above, though that's a property of putting the code in contrib, not a property of the deployment approach

I assume auth won't be a problem, but thought I'd mention it anyway (the controller needs to be able to manager the user's other API resources).

cc/ @bgrant0607 @erictune @thockin @sdminonne 

ref/ #24781

**Comment by sdminonne** [comment]
@davidopp what is described here it makes perfect sense to me, and basically, I understand some motivations reported by @erictune [here](https://github.com/kubernetes/kubernetes/pull/24781#issuecomment-215914822)
Now: I'm OK to help to write an `addon` for a minimal workflow controller. It something similar it was described in the [proposal](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/workflow.md), so it will be a DAG where every `step` starts when all dependencies are completed.

**Comment by erictune** [comment]
I would like a ScheduledJob to be able to trigger a workflow.  One way it could do that is to run a job that is just a kubectl command that creates a workflow object and waits for it to finish, and if it is restarted, it checks if it already exists and waits for it.  We should document that pattern.  

The other way is to extend the ScheduledJob object to be able to create arbitrary objects rather than just jobs.  Basically, you could provide either a JobTemplateSpec, or a [generic template](https://github.com/kubernetes/kubernetes/issues/23896).

**Comment by sdminonne** [comment]
+1 this will help in our major use case. 
Obviously I would prefer the second one, eventually renaming `ScheduledJob` to something more generic or at least less `Job`-oriented. Internally we've a `TimeInitiatedActivity` entity which is pretty similar.

**Comment by sdminonne** [comment]
@timstclair FYI

**Comment by soltysh** [comment]
:+1: for the generic template idea. I've created https://github.com/kubernetes/kubernetes/issues/28349 to handle that one as soon as we have SJ in.

**Comment by timstclair** [comment]
@timothysc

**Comment by timothysc** [comment]
So this is exactly the path that I/we (red hat) had discussed for future add-on support.  My only concern is test automation mechanics.  At some point in the future there will likely be a lot of extensions/add-ons to the point where we will want mechanics to qualify those extensions/add-ons.

**Comment by timothysc** [comment]
I'd honestly move to close this.  There are an assorted number of workflow projects that exist outside the core now.

**Comment by kargakis** [comment]
@timothysc agreed. This means though we should close all the relevant issues: https://github.com/kubernetes/kubernetes/issues/34363 https://github.com/kubernetes/kubernetes/issues/1704 https://github.com/kubernetes/kubernetes/issues/29453

**Comment by timothysc** [comment]
@kargakis +1 from me.  We have enough cruft.

**Comment by soltysh** [comment]
+1 on my end end, as well.

**Comment by kargakis** [comment]
Got agreement by @bgrant0607 too - closing this and all related issues.

**Comment by kargakis** [comment]
Additional comment by Brian

"I think that particular issue is subsumed by the work on custom resources."
