### ISSUE TITLE
Kubernetes Masters should alert if they have different certs

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#25063]
When you setup TLS assets, you need to make sure each master API server is using the same ones, unless you were running a single master. But this is a super common mistake, and it often breaks things.

Because the masters validating tokens using that key, the controller-manager also has this service-account key, and it’s responsible for creating tokens for service accounts. So, depending on which apiserver the pod is talking to, that service-account token may, or may not work. This most commonly surfaces in kube2sky (the dns addon).

Result: Tokens are invalidated regularly (~10 minutes)
Expected: Warning about system having different certs (or some alert).

Would this ever be a valid configuration?

**Comment by roberthbailey** [comment]
@aronchick Is this specifically for an HA setup (since you mention multiple apiservers)? Or do you mean that each master component should have the same cert?

**Comment by aronchick** [comment]
Correct - it's the HA deployment.

**Comment by roberthbailey** [comment]
I don't think that the apiservers should necessarily cross-check each other (and all other system components like the controller manager) and alert. If you are running an HA deployment, you should have something else making sure that your deployment is correct. On cluster creation, the startup scripts should do it.

**Comment by aronchick** [comment]
I guess what I'm saying is that we know this is going to be a problem. There's almost no way to make this NOT a problem, yet it is a very easy bug to get into.

So... with that in mind, what's the path for doing this? When you add a second master to your HA config, how does it establish trust with the first HA? Could we check at that point?

**Comment by timothysc** [comment]
> On cluster creation, the startup scripts should do it.

Yup, we do this on provision time with Ansible.
