### ISSUE TITLE
Adding a third party extension, then removing, then re-adding fails

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#25084]
Repro:
```
kubectl create -f rsrc.json
kubectl delete -f rsrc.json
kubectl create -f rsrc.json
```

apiserver panics.

This is caused by an underlying bug in go-restful:  https://github.com/emicklei/go-restful/issues/289

**Comment by roberthbailey** [comment]
@brendandburns is this fixed?

**Comment by brendandburns** [comment]
@roberthbailey not yet.

See: https://github.com/kubernetes/kubernetes/pull/25365

The original go-restful update didn't actually contain the fix.  See:

https://github.com/emicklei/go-restful/issues/289

and

https://github.com/emicklei/go-restful/commit/0e9e201e5de4f54c61e6d09aef44c4cfde43ede6
