### ISSUE TITLE
e2e flake: `Kubectl client Kubectl describe should check if kubectl describe prints relevant information for rc and pods` 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25083]
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/16103

```
• Failure [140.118 seconds]
[k8s.io] Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:502
  [k8s.io] Kubectl describe
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:502
    should check if kubectl describe prints relevant information for rc and pods [Conformance] [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:713

    May  3 08:10:44.677: Failed to find 1 Running in Pods Status:	0 Running / 1 Waiting / 0 Succeeded / 0 Failed

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1210
```

this is by far the most flaky test

@bgrant0607 @kubernetes/kubectl

**Comment by janetkuo** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubectl.go#L615-L714

Two problems in this test:

1. we shouldn't rely on docker hub in our test
2. we shouldn't wait for a short amount of time and expect an async thing to happen (in this test, we waited for 1s and expect the redis pods are running)

cc @mwielgus can you take a look?

**Comment by janetkuo** [comment]
Updating test conventions docs in #25089

**Comment by bgrant0607** [comment]
This test has been failing several times a day since 4/21.

**Comment by janetkuo** [comment]
#24849 will fix the 1st problem

**Comment by bgrant0607** [comment]
The test has failed twice since #24849 merged, so that didn't seem to make much difference. :-(

**Comment by AdoHe** [comment]
@janetkuo Actually the `waitFor` did do some wait & retry logical. I found this test flake a little bit trick.
```
waitFor(1)
// Pod
forEachPod(func(pod api.Pod) {
	output := framework.RunKubectlOrDie("describe", "pod", pod.Name, nsFlag)
	requiredStrings := [][]string{
		{"Name:", "redis-master-"},
		{"Namespace:", ns},
		{"Node:"},
		{"Labels:", "app=redis", "role=master"},
		{"Status:", "Running"},
		{"IP:"},
		{"Controllers:", "ReplicationController/redis-master"},
		{"Image:", redisImage},
		{"cpu:", "BestEffort"},
		{"State:", "Running"},
	}
	checkOutput(output, requiredStrings)
})

// Rc
output := framework.RunKubectlOrDie("describe", "rc", "redis-master", nsFlag)
requiredStrings := [][]string{
	{"Name:", "redis-master"},
	{"Namespace:", ns},
	{"Image(s):", redisImage},
	{"Selector:", "app=redis,role=master"},
	{"Labels:", "app=redis,role=master"},
	{"Replicas:", "1 current", "1 desired"},
	{"Pods Status:", "1 Running", "0 Waiting", "0 Succeeded", "0 Failed"},
	// {"Events:"} would ordinarily go in the list
	// here, but in some rare circumstances the
	// events are delayed, and instead kubectl
	// prints "No events." This string will match
	// either way.
	{"vents"}}
checkOutput(output, requiredStrings)
```
After the first `checkOutput`, the pod should be running. But when we describe the rc, we just get the pod status is waiting.

**Comment by janetkuo** [comment]
It's becoming pretty green now. Possibly because of #24849

**Comment by janetkuo** [comment]
@AdoHe thanks for looking into this. From the log, it seems that `waitFor(1)`, which waits for 1 pod to be running within 90 seconds, timed out and caused the test to fail... which means that the pod's `checkOutput` isn't executed. 

This flake is considered solved now. If it becomes flaky in the future, we should increase the timeout in `waitFor`.

**Comment by janetkuo** [comment]
Removing it from flaky list #25291
