### ISSUE TITLE
GCE cluster scripts: prompt user to pick zone

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#2510]
We should probably prompt users to pick a zone instead of having a default.  We should then save that into something like ~/.kube/cluster_defaults.  For backward compat, we should probably default to us-central1-b when calling kubecfg/kubectl.sh.

**Comment by roberthbailey** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/5472. In the mean time, users can select a zone by changing a config entry in `config-default.sh`.
