### ISSUE TITLE
verify-codecgen and update-codecgen disagree with each other

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#25103]
See, e.g.

- https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25102/kubernetes-pull-test-unit-integration/23972/
- https://github.com/kubernetes/kubernetes/pull/23684#issuecomment-216654698
- #25102

This seems to be blocking multiple PRs from even being tested.

**Comment by lavalamp** [comment]
Looking.

**Comment by lavalamp** [comment]
I think I figured it out. The order of generation matters. The verify script subtly breaks that by renaming and checking the files one at a time. The update script deletes everything and then recreates them.

**Comment by lavalamp** [comment]
I have a fix. Will send a PR shortly.
