### ISSUE TITLE
Use cases for kubectl port-forward

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#25113]
As we are figuring out the next-version container runtime interface, I'd like to gather some feedback on existing features we support.

The description of kubectl port-forward is [here](https://github.com/kubernetes/kubernetes/blob/1d96b4c55b6b4e6bc9bda5d12a7b99834056bdf4/docs/user-guide/kubectl/kubectl_port-forward.md).
What are the existing use cases? Is this feature mainly used for debugging?

/cc @kubernetes/sig-node 
/cc @thockin @vishh

**Comment by vishh** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by ncdc** [comment]
This is essentially a debugging tool. If you need to connect to a port in your pod and you don't ever want to expose that port via a service or via ingress, you'll need to use port forwarding to get temporary access to that port. One good example is connecting to the JVM debugging port for remote debugging of Java processes.

**Comment by yifan-gu** [comment]
We should be able to achieve the same by `kubectl exec` the `socat` inside the pod's namespace. Though we need to have `socat` in the container image. But on the other hand, we need `socat` on the host today.

@euank @sjpotter Actually found the PortForward is broken for rkt today, as the PID of the pod returned by rkt api service is not the PID1 of the pod, (it's changed to the pid of nspawn/kvm) so it does not hold the namespace now.

**Comment by yujuhong** [comment]
> We should be able to achieve the same by kubectl exec the socat inside the pod's namespace

Yes, supporting this for normal Linux containers should not be a problem. This, however, might be a problem for hypervisors and windows? AFAIK, hyper doesn't support this (@feiskyer, correct me if I am wrong).

This is a "pod-level" feature that is not tied to a specific container, so it'd be good to figure out how and whether we are going to support it as part of the sandbox operation proposed in the doc.

**Comment by ncdc** [comment]
> We should be able to achieve the same by kubectl exec the socat inside the pod's namespace

This would make for a much less friendly UX. Also, `kubectl port-forward` and the associated code in the kubelet already has all the plumbing necessary to listen on local ports on the user's system and to copy the data back and forth between the user's local ports and the ports in the pod.

I know our users would be unhappy if we suggested that port forwarding was going away.

cc @smarterclayton @pweil- @bparees @eparis

**Comment by smarterclayton** [comment]
This is a very common way to debug and diagnose both development and production features.  

I would love to have a more generalized framework for executing in-container helpers (injected static binaries that can evolve differently from the container runtime), especially to decouple them from the kubelet.

**Comment by smarterclayton** [comment]
s/features/applications/

**Comment by feiskyer** [comment]
> Yes, supporting this for normal Linux containers should not be a problem. This, however, might be a problem for hypervisors and windows? AFAIK, hyper doesn't support this (@feiskyer, correct me if I am wrong).

@yujuhong Right, Hyper doesn't support port-forward.

> This is a very common way to debug and diagnose both development and production features.

@smarterclayton Could we achieve this by some wrapping on ExecInContainer?

**Comment by ncdc** [comment]
> Could we achieve this by some wrapping on ExecInContainer?

It's not that simple. You have to bind to local ports so you can accept connections from local clients, and then you need to get the data copied between the client and the pod. Right now we do client -> `kubectl port-forward` ports -> apiserver -> kubelet -> pod's network namespace via socat. There is a lot more going on here than just "exec"ing something 😄

**Comment by smarterclayton** [comment]
The ideal would be "client -> api server -> kubelet -> launch process in
container context -> redirect from kubelet to listening process in
container context -> serve back to client", allowing the kubelet to offload
any communication traffic.

The "standard process" could be a process inside the VM or out, just as
long as there was a way to execute it.  I don't think that we should go
lowest common denominator though and say "we'll only support things that
only work inside of VMs" (which I don't necessarily think you are saying,
but is important to see in mind).  The container runtime being able to say
"I don't support port-forward" gracefully is a good first step.

**Comment by euank** [comment]
It can also be used as a means to run once-off deployment/migration/analytics type jobs against a service which should not generally be exposed (e.g. for security reasons).

You might argue that it's better for these jobs to run on K8, not on a developer's machine, but I don't think that level of overhead is always warranted / desired, and it certainly can't replace interactive sessions (e.g. poking around in sql workbench).

Those sorts of usecases might also fall under "debugging" in your book, and could also be solved with ssh portforwarding usually, but I don't think that means K8 shouldn't know how to do this.

**Comment by yujuhong** [comment]
I think there are a few questions mixed in this discussion:
 1. Should we allow the container runtime to selectively support kubernetes features? If so, do we expose the supported features for each runtime and how? We should set a general rule on this.
 2. Whether we want to keep port forwarding feature or not? The general feedback seems to be that the feature is good for debugging and is valuable to keep. 
 3. How Hyper is going to support port-forwarding if it wants to. @feiskyer, do you have a more concrete idea of how/whether to proceed for hyper?
 4. How we can define port forwarding in the new container runtime interface. Does the interface need to speak network namespace?

**Comment by vishh** [comment]
> How we can define port forwarding in the new container runtime interface. Does the interface need to speak network namespace?

FYI: @smarterclayton is suggesting a runtime agnostic solution in https://github.com/kubernetes/kubernetes/issues/25113#issuecomment-216717692

**Comment by dchen1107** [comment]
+1 on @smarterclayton's solution at https://github.com/kubernetes/kubernetes/issues/25113#issuecomment-216717692

**Comment by smarterclayton** [comment]
In practice we have all the tools to do that today.  Maybe something we
queue up for 1.4 to try and do port-forward that way to start, then exec,
then potentially attach.

**Comment by yujuhong** [comment]
Alright, so the plan is to drop this from the container runtime interface/api, and implement the function in kubelet. 

Thanks for the inputs!

**Comment by derekwaynecarr** [comment]
i assume we can only drop it when we validate that we can support the alternate route?  for example, we can't move to container runtime until we have port fowarding using the alternate proposal?

**Comment by ncdc** [comment]
@smarterclayton 

> The ideal would be "client -> api server -> kubelet -> launch process in
container context -> redirect from kubelet to listening process in
container context -> serve back to client", allowing the kubelet to offload
any communication traffic.

How do we handle traffic from "client -> listening process in container context" - does it still go through the apiserver? Or using Ingress somehow? Otherwise I don't see how we go from an external client to a pod.

**Comment by smarterclayton** [comment]
client -> apiserver -> listening process in container context

**Comment by philips** [comment]
@ncdc I don't think you can or should avoid the api server because that is the access control for this one time debugging task thingie. Did you have a different design in mind?

**Comment by ncdc** [comment]
No, I just wanted to make sure I understood the suggested design
completely.

**Comment by smarterclayton** [comment]
Yeah, the redirect would be from kubelet -> listening process, which would
be handled by the internal tunnel established from the apiserver.
Offloading the apiserver has been discussed but there would still have to
be something like an apiserver acting as a secure proxy.  This is probably
different from the "temporarily expose a port all the way to the edge" use
case (like a very temporary host port or node port) which is useful for
testing or verifying network connectivity, but could not enforce security.

**Comment by derekwaynecarr** [comment]
Cross-referencing comments: https://github.com/kubernetes/kubernetes/pull/25899/files#r66263302

**Comment by yujuhong** [comment]
@ncdc @dcbw, would any of you be willing to pick up this and try exploring the suggested solution in https://github.com/kubernetes/kubernetes/issues/25113#issuecomment-216717692? Thanks in advance anyway.

**Comment by ncdc** [comment]
I can pick it up

**Comment by yujuhong** [comment]
Thanks!

**Comment by pskrzyns** [comment]
cc @lukasredynk

**Comment by yujuhong** [comment]
This is subsumed by #29579
