### ISSUE TITLE
rkt: portforward is broken

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#25117]
Since the pid of the pod returned by rkt api service is not the PID1 of the pod now, so it doesn't hold the namespace, thus cannot be used by `nsenter` to enter the namespace and run `socat`.

Ref https://github.com/kubernetes/kubernetes/issues/25113#issuecomment-216708103

**Comment by yifan-gu** [comment]
cc @euank @sjpotter

**Comment by euank** [comment]
Using the well-known network namespace path we'll have after #25062 should allow us to use `nsenter --net=path` if it's particularly difficult to get the correct pid1.

**Comment by yifan-gu** [comment]
> Using the well-known network namespace path we'll have after #25062 should allow us to use nsenter --net=path if it's particularly difficult to get the correct pid1.

Sounds like a better way. But as discussed in https://github.com/kubernetes/kubernetes/issues/25113#issuecomment-218003607  , maybe a quick fix today is enough.

**Comment by yifan-gu** [comment]
FYI, I believe this will be fixed once #25062 lands.

**Comment by yifan-gu** [comment]
Tested, this will be fixed once https://github.com/kubernetes/kubernetes/pull/26096 and https://github.com/kubernetes/kubernetes/pull/25902 is merged:

```
$ go run hack/e2e.go -v --test --test_args="--ginkgo.focus=forwarding --ginkgo.dryRun=false"
...
Ran 3 of 300 Specs in 97.385 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 297 Skipped PASS
```

**Comment by yifan-gu** [comment]
This can be closed now.
