### ISSUE TITLE
azureFile not recognized at valid

### ISSUE THREAD

**Issue by kjnsn** [kubernetes/kubernetes#25111]
When attempting to create the file given at `examples/azure_file/azure.yaml` I receive the following error:

`error validating "azure-file.yaml": error validating data: found invalid field azureFile for v1.Volume; if you choose to ignore these errors, turn validation off with --validate=false`

Versions are as follows:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"b57e8bdc7c3871e3f6077b13c42d205ae1813fbd", GitTreeState:"clean"}
```

According to the documentation this should have been valid with versions including and after 1.2

**Comment by roberthbailey** [comment]
@errordeveloper, @squillace, @chanezon, @crossorigin (listed as the azure owners in http://kubernetes.io/docs/getting-started-guides/#table-of-solutions)

**Comment by roberthbailey** [comment]
Hi @kjnsn. I'm sorry that no one was able to help you with this issue. Since it hasn't been updated for almost a year, I'm going to close it as obsolete. Please re-open or create a new issue if you are still experiencing this problem using Kubernetes 1.6.
