### ISSUE TITLE
kubectl proxy doesn't allow WebSockets

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#25126]
There is no specific issue that addresses this issue, which I think is rather critical. I haven't tested SPDY and HTTP/2 yet, but those are probably broken also. In amy environments `kubectl proxy` would be the only user-friendly way to to get to the internal services, although it's understood that it can only carry HTTP traffic, it should support modern uses of HTTP.

**Comment by errordeveloper** [comment]
This had already been reported in #17032 and #24482, but nobody got to the bottom of where this bug lies.

**Comment by errordeveloper** [comment]
xref #25126

**Comment by errordeveloper** [comment]
Also, turns out one cannot issue `kubectl port-forward` against the proxy, it fails with `Upgrade request required`.

**Comment by pshirshov** [comment]
Hi guys, it so funny that this issue is still unresolved.

**Comment by joan38** [comment]
@pshirshov, your funny contribution is welcome to fix this issue.

**Comment by lenartj** [comment]
See #49534 also.

**Comment by errordeveloper** [comment]
It appears that #49534 fixed this.
