### ISSUE TITLE
kubectl failed to create ThirdPartyResource object because of different Plurality Rule

### ISSUE THREAD

**Issue by AdoHe** [kubernetes/kubernetes#25129]
@brendandburns As I commented [here](https://github.com/kubernetes/kubernetes/issues/24584#issuecomment-216829751), I think the root cause is plurality rule. I noticed such log in `kube-apiserver.log`:
```
I0504 07:58:27.817445   10307 handlers.go:161] POST /apis/experimental.example.com/v1/namespaces/default/networkpolicies: (126.685µs) 404 [[Go-http-client/1.1] 127.0.0.1:59963]
```
But if you request this address: `http://127.0.0.1:8080/apis/experimental.example.com/v1/namespaces/default/networkpolicys`, it's just ok. So whether we should use `policys` or `policies`?

**Comment by brendandburns** [comment]
We should make sure that pluralization is consistent between server and client.  I will take a look at fixing this.

thanks!
--brendan
