### ISSUE TITLE
Set up jenkins suite testing protobuf communication

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25132]
Once we have (initial) support for protobufs already merged (e.g. migration is not required for it), we should set up a Jenkins job running tests where all components are using protobufs to communicate.

@smarterclayton

**Comment by wojtek-t** [comment]
For this, I specifically mean correctness tests at first.

**Comment by wojtek-t** [comment]
@zmerlynn - FYI

**Comment by wojtek-t** [comment]
I think that for now we require just 2 PR before doing that:
https://github.com/kubernetes/kubernetes/pull/24789
https://github.com/kubernetes/kubernetes/pull/24710

**Comment by wojtek-t** [comment]
I will create a project and set up testing for it (hopefully tomorrow).

**Comment by smarterclayton** [comment]
I'm going to probably add a new condition to unit test jobs that runs the
unit tests with protobuf enabled - doing it for integration will be
trickier, so agree it'll be useful to run the e2e suite with proto enabled.

**Comment by wojtek-t** [comment]
This suite is already set up:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-proto/

Test are not passing due to #25258 but I hope I just fixed it. Will be monitoring if the suite will repair.

**Comment by wojtek-t** [comment]
This is done.
