### ISSUE TITLE
unit flake: TestAddTwoFireEarly

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25135]
--- FAIL: TestAddTwoFireEarly (10.15s)
	delaying_queue_test.go:92: unexpected err: timed out waiting for the condition

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/24164/kubernetes-pull-test-unit-integration/22236/build-log.txt

**Comment by roberthbailey** [comment]
@wojtek-t is this fixed?

**Comment by wojtek-t** [comment]
I didn't touch this. I've seen it once and I think noone looked into it yet.

**Comment by gmarek** [comment]
It's not fixed.

**Comment by dims** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/26689 ?

**Comment by deads2k** [comment]
> Duplicate of #26689 ?

Yeah, they're the same.  haven't seen a reference since #26700 merged

**Comment by lavalamp** [comment]
OK, if it happens again the bot will open a new issue.
