### ISSUE TITLE
GCE: should refuse to create a firewall rule with no tag

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#25145]
In some custom setup cases the prefix-matching logic for GCE load-balancers can break and end up creating a firewall rule with no tags.  We should instead refuse to create the rule.  In fact, if we find it, we should probably delete the rule, but that's maybe too aggressive.

pkg/cloudprovider/providers/gce/gce.go

Looking at the logic, if we return error in the tag-selection, we'll abort the whole load-balancer creation, which is unfortunate, but not TERRIBLE.  We could just silently not create the firewall but not return error, which will just retry over and over.

**Comment by thockin** [comment]
@a-robinson Are you active on this?  @jingxu97 may have some starter-project bandwidth to help.

**Comment by a-robinson** [comment]
Not active. It would indeed be a good starter project :)
