### ISSUE TITLE
Remove kubenet CNI bridge plugin txqueuelen workaround

### ISSUE THREAD

**Issue by dcbw** [kubernetes/kubernetes#25143]
Once https://github.com/containernetworking/cni/pull/199 gets merged and we upload a new version of the CNI plugins for cluster/saltbase/salt/cni/init.sls we can revert https://github.com/kubernetes/kubernetes/pull/25136.

**Comment by dcbw** [comment]
@mikedanese here's the workaround removal issue; anything else I need to add to it?

**Comment by mikedanese** [comment]
Nope! This is what we need to track it. Thanks for opening.

**Comment by dcbw** [comment]
The upstream CNI fix got merged for CNI 0.3.0.

**Comment by mikedanese** [comment]
cc @freehan

**Comment by freehan** [comment]
Great. Will clean up for the next version bump.
