### ISSUE TITLE
Rewrite/enhance hack/cherry_pick_pull.sh script

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#25154]
It should be a more curated, friendly and guided experience.  Possibly look into doing away with hub.

cc @zmerlynn @davidopp

**Comment by roberthbailey** [comment]
This doesn't sound like a 1.3 feature. Can we remove it from the milestone?

**Comment by david-mcmahon** [comment]
Closing.  A plugin is almost ready to do this via Prow.
