### ISSUE TITLE
flake e2e node conformance test failure

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#25169]
>
23:49:35       Expected error:
23:49:35           <*errors.StatusError | 0xc82057fe00>: {
23:49:35               ErrStatus: {
23:49:35                   TypeMeta: {Kind: "Status", APIVersion: "v1"},
23:49:35                   ListMeta: {SelfLink: "", ResourceVersion: ""},
23:49:35                   Status: "Failure",
23:49:35                   Message: "pods \"busybox\" not found",
23:49:35                   Reason: "NotFound",
23:49:35                   Details: {Name: "busybox", Group: "", Kind: "pods", Causes: nil, RetryAfterSeconds: 0},
23:49:35                   Code: 404,
23:49:35               },
23:49:35           }
23:49:35           pods "busybox" not found
23:49:35       not to have occurred

[logs](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/2473)

**Comment by pwittrock** [comment]
cc @Random-Liu

**Comment by Random-Liu** [comment]
@pwittrock @liangchenye 
Offline discussed with @caesarxuchao, this is a known issue https://github.com/kubernetes/kubernetes/issues/19403#issuecomment-175296720.

For short, event though the pod is deleted on the apiserver, kubelet may still try to delete the pod again. If we create a pod with the same name and namespace right after deleting the pod, the new pod will be deleted by kubelet accidentally.

As a quick fix, we should randomize the pod name for different test cases.
As a better fix, we should start using the e2e test framework and use different namespace for different test cases.
In the long run, we should fix kubelet let kubelet delete pod by UID, see https://github.com/kubernetes/kubernetes/pull/22965

/cc @yujuhong

**Comment by pwittrock** [comment]
Great.  Seems like we have a quick fix then.

**Comment by yujuhong** [comment]
> For short, event though the pod is deleted on the apiserver, kubelet may still try to delete the pod again. If we create a pod with the same name and namespace soon after deleting the it, the new pod will be deleted by kubelet accidentally.

Don't we check the pod UID before deleting it?

**Comment by Random-Liu** [comment]
@yujuhong But there is still a race between kubelet and apiserver.

* Kubelet gets the old pod, and update the status.
* Apiserver deletes the pod because it reaches the timeout.
* Test create the new pod with the same name and namespace.
* Kubelet deletes the nwe pod.

**Comment by yujuhong** [comment]
Ah...yeah...that jogged my memory. Thanks for the explanation. Deleting by UID would be great.

**Comment by caesarxuchao** [comment]
> Don't we check the pod UID before deleting it?

This is not enough, the pod may be deleted and recreated after the check in kubelet and before the deletion request reaches the API server. We need to use #22965, which technically is still "deleting by Name", but you can set the UID as a precondition.
