### ISSUE TITLE
kubectl should suggest possibly matching kubectl commands

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25180]
For example, 
- `get`: `ps`, `list`
- `delete`: `rm`

@kubernetes/kubectl

**Comment by janetkuo** [comment]
It's pretty simple to add suggestions. Take a stab at this in #25181. Keep this open for more ideas on other suggestions.

**Comment by janetkuo** [comment]
In the future, if we support `kubectl create pods`, its suggestion list will include `kubectl create containers`.

**Comment by AdoHe** [comment]
@janetkuo actually in #25181, kubectl can just give correct command if you are using some wrong command, like `git`, more advanced we want kubectl can suggest the next command. For example you may want to run `kubectl get pod <pod_name>` after you create a pod.

**Comment by janetkuo** [comment]
> kubectl can just give correct command if you are using some wrong command

@AdoHe did you mean alias the command, i.e. `kubectl ps` takes you directly to `kubectl get`? We deliberately don't want to support that because this makes it confusing in docs and there will be more commands to learn for the users. cc @bgrant0607 

> we want kubectl can suggest the next command

Yes, I'm aware of that. It's part of the [kubectl roadmap](https://github.com/kubernetes/community/wiki/Roadmap:-kubectl).

**Comment by bgrant0607** [comment]
Yes, we decided a long time ago not to support built-in aliases. We should document that in kubectl conventions if it's not there already.

**Comment by janetkuo** [comment]
> Yes, we decided a long time ago not to support built-in aliases. We should document that in kubectl conventions if it's not there already.

Documented in #25269

**Comment by pigmej** [comment]
Shouldn't it be closed?
