### ISSUE TITLE
Pod with key `scheduler.alpha.kubernetes.io/name` but empty value should be ignored by any scheduler.

### ISSUE THREAD

**Issue by HaiyangDING** [kubernetes/kubernetes#25184]
Currently in multi-scheduler scenario, a pod will be scheduled by `default-scheduler` iff its annotations meets one of the 3 following conditions:

1. has no key (nor value): `scheduler.alpha.kubernetes.io/name`
2. has proper key&value referring to default scheduler, i.e. `scheduler.alpha.kubernetes.io/name: default-scheduler`
3. has key but empty value, i.e. `scheduler.alpha.kubernetes.io/name: <nil>`

However, I think it would be more reasonable if pods with  `scheduler.alpha.kubernetes.io/name: <nil>` are ignored by any schedulers. For instance, the pod's owner deliberately "creates" a pod but does not want it scheduled immediately. Any ideas?

@davidopp  @kubernetes/sig-scheduling

**Comment by davidopp** [comment]
It is already possible to create a pod and not have it scheduled immediately (create it with a NodeName set to some value that does not correspond to any actual node.) I think we should actually reject `scheduler.alpha.kubernetes.io/name: <nil>` in validation.

**Comment by HaiyangDING** [comment]
Sorry I did not reply in time. I agree. Closing this issue.
