### ISSUE TITLE
e2e flake: SchedulerPredicates [Serial] 

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#25201]
When running `validates resource limits of pods that are allowed to run` test, the number of additional pods to create to saturate each node's cpu resource is something `0`. When this happens, the e2e fails due to  calling `framework.StartPods` which expects non-zero number of additional pods to be created.

I have introduce condition to skip the waiting part if the number of replicas is `0` [1]. Still, the question is if the test is always supposed to create at least one additional pod?

I am running the test on cluster with 1 master and 2 nodes. I can image upstream CI has more than 2 nodes. Still, this should not matter. What is the "proper" pre-condition for the test?

**Runs where the test passed**:

```
Node: 10.8.53.89 has capacity: 90
Node: 10.8.51.123 has capacity: 600
STEP: Starting additional 1 Pods to fully saturate the cluster CPU and trying to start another one

---
Node: 10.8.48.180 has capacity: 190
Node: 10.8.48.230 has capacity: 500
STEP: Starting additional 1 Pods to fully saturate the cluster CPU and trying to start another one

---
Node: 10.8.52.190 has capacity: 190
Node: 10.8.52.29 has capacity: 500
STEP: Starting additional 1 Pods to fully saturate the cluster CPU and trying to start another one

```

**Runs where the test failed**:

```
Node: 10.8.48.127 has capacity: 290
Node: 10.8.55.126 has capacity: 400
STEP: Starting additional 0 Pods to fully saturate the cluster CPU and trying to start another one

---
Node: 10.8.49.156 has capacity: 300
Node: 10.8.52.190 has capacity: 390
STEP: Starting additional 0 Pods to fully saturate the cluster CPU and trying to start another one

---
Node: 10.8.50.79 has capacity: 390
Node: 10.8.50.131 has capacity: 300
STEP: Starting additional 0 Pods to fully saturate the cluster CPU and trying to start another one
```

When the resources allocated are "almost" uniformly distributed, no need to create any additional pod.
Is the scheduler supposed to always create non-uniform distribution? Or should be the capacity of each node just increased so there is always a need for at least one additional pod?

[1] https://github.com/kubernetes/kubernetes/pull/25192

**Comment by ingvagabund** [comment]
@kubernetes/rh-cluster-infra @kubernetes/sig-testing

**Comment by ingvagabund** [comment]
The ``validates resource limits of pods that are allowed to run`` is not the only tests using ``framework.StartPods`` and relying on the non-zero number of replicas. Would be worth fixing all occurences and updating the ``StartPods`` to panic or at least noisily  complaint if its input is invalid.

**Comment by david-mcmahon** [comment]
This is currently killing kubernetes-e2e-gce-serial and holding up the latest alpha.

**Comment by ingvagabund** [comment]
@david-mcmahon even with the https://github.com/kubernetes/kubernetes/pull/25192 fix? Do you have its test log?

**Comment by david-mcmahon** [comment]
@ingvagabund thanks for the response.  Is this the same issue?
https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/1250/build-log.txt

**Comment by ingvagabund** [comment]
By the look it is different

**Comment by ingvagabund** [comment]
```
stderr:
      the path "/workspace/kubernetes/test/e2e/node-selection/pod-with-pod-affinity.yaml" does not exist
``` 
The file definitely exists as I can locate it: ``test/e2e/node-selection/pod-with-pod-affinity.yaml``. Maybe, some test run before removed the file and the flake is somewhere else.

**Comment by gmarek** [comment]
@david-mcmahon - this is not the failure that's killing gce-serial. This is about resource usage scheduler predicates which didn't failed for few months now.

**Comment by david-mcmahon** [comment]
Ok, thanks for confirming @gmarek
