### ISSUE TITLE
new namespace non-functional for over 5 minutes due to default service account creation delay

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#25204]
We've occasionally run into an issue where we create a new namespace, but the corresponding service account isn't created for over 5 minutes, during which time the new namespace remains non-functional.

That is, we can create a replication controller in the new namespace, but it throws errors every second complaining that it's `unable to create pods: pods "grafana-20160505-063149-" is forbidden: service account grafana/default was not found, retry after the service account is created`. Then, after a little over 5 minutes, the service account finally appears, and the replication controller succeeds at creating pods.

**stdout:**

```
[2016-05-05 06:31:51] $ echo "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"name\":\"grafana\"}}" | kubectl create -f -
[2016-05-05 06:31:51] namespace "grafana" created

[2016-05-05 06:31:53] $ kubectl --namespace=grafana create -f /tmp/template_grafana_rc_20160505-063149.yaml
[2016-05-05 06:31:53] replicationcontroller "grafana-20160505-063149" created
```

**Logs:**

```
$ kubectl logs kube-controller-manager-m1kmaster1 | grep grafana | (head;echo;tail)
I0505 06:31:53.649666       1 replication_controller.go:434] Too few "grafana"/"grafana-20160505-063149" replicas, need 1, creating 1
I0505 06:31:54.741814       1 replication_controller.go:440] Failed creation, decrementing expectations for controller "grafana"/"grafana-20160505-063149"
E0505 06:31:54.741867       1 replication_controller.go:442] unable to create pods: pods "grafana-20160505-063149-" is forbidden: service account grafana/default was not found, retry after the service account is created
I0505 06:31:54.741772       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"grafana", Name:"grafana-20160505-063149", UID:"0e901b1c-128b-11e6-ab4d-0050561d25b2", APIVersion:"v1", ResourceVersion:"1213", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "grafana-20160505-063149-" is forbidden: service account grafana/default was not found, retry after the service account is created
I0505 06:31:54.826712       1 replication_controller.go:434] Too few "grafana"/"grafana-20160505-063149" replicas, need 1, creating 1
I0505 06:31:56.564281       1 replication_controller.go:440] Failed creation, decrementing expectations for controller "grafana"/"grafana-20160505-063149"
E0505 06:31:56.564311       1 replication_controller.go:442] unable to create pods: pods "grafana-20160505-063149-" is forbidden: service account grafana/default was not found, retry after the service account is created
I0505 06:31:56.564946       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"grafana", Name:"grafana-20160505-063149", UID:"0e901b1c-128b-11e6-ab4d-0050561d25b2", APIVersion:"v1", ResourceVersion:"1216", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "grafana-20160505-063149-" is forbidden: service account grafana/default was not found, retry after the service account is created
I0505 06:32:08.337451       1 replication_controller.go:434] Too few "grafana"/"grafana-20160505-063149" replicas, need 1, creating 1

I0505 06:36:58.402888       1 replication_controller.go:434] Too few "grafana"/"grafana-20160505-063149" replicas, need 1, creating 1
I0505 06:36:59.935364       1 replication_controller.go:440] Failed creation, decrementing expectations for controller "grafana"/"grafana-20160505-063149"
I0505 06:36:59.935517       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"grafana", Name:"grafana-20160505-063149", UID:"0e901b1c-128b-11e6-ab4d-0050561d25b2", APIVersion:"v1", ResourceVersion:"1216", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "grafana-20160505-063149-" is forbidden: service account grafana/default was not found, retry after the service account is created
E0505 06:36:59.936915       1 replication_controller.go:442] unable to create pods: pods "grafana-20160505-063149-" is forbidden: service account grafana/default was not found, retry after the service account is created
I0505 06:36:59.937674       1 replication_controller.go:434] Too few "grafana"/"grafana-20160505-063149" replicas, need 1, creating 1
I0505 06:37:01.318998       1 replication_controller.go:440] Failed creation, decrementing expectations for controller "grafana"/"grafana-20160505-063149"
E0505 06:37:01.319034       1 replication_controller.go:442] unable to create pods: pods "grafana-20160505-063149-" is forbidden: service account grafana/default was not found, retry after the service account is created
I0505 06:37:01.319169       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"grafana", Name:"grafana-20160505-063149", UID:"0e901b1c-128b-11e6-ab4d-0050561d25b2", APIVersion:"v1", ResourceVersion:"1216", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: pods "grafana-20160505-063149-" is forbidden: service account grafana/default was not found, retry after the service account is created
I0505 06:37:27.413235       1 replication_controller.go:434] Too few "grafana"/"grafana-20160505-063149" replicas, need 1, creating 1
I0505 06:37:27.429364       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"grafana", Name:"grafana-20160505-063149", UID:"0e901b1c-128b-11e6-ab4d-0050561d25b2", APIVersion:"v1", ResourceVersion:"1216", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: grafana-20160505-063149-omw8d
```

**Api server flags:**

```
$ ps aux | grep api
root      2912  1.2  2.1 748936 43584 ?        Sl   06:05   7:53 /opt/kubernetes/bin/hyperkube kubelet --v=2 --api-servers=https://192.168.1.6:6443 --register-node=true --register-schedulable=false --config=/etc/kubernetes/manifests --kubeconfig=/highland/tmp/kubeconfig --port=10250 --address=0.0.0.0 --hostname_override=m1kmaster1 --cadvisor-port=4194 --allow-privileged=true --pod-infra-container-image=docker.prod.skytap.com:5000/skytap-pause-0.8.0:f4ba5159b328400b467cdf9d914ea614379d5715
root      3750  1.3 11.1 543000 229440 ?       Ssl  06:07   8:18 /hyperkube apiserver --v=2 --advertise-address=192.168.1.6 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota --secure-port=6443 --kubelet-port=10250 --insecure-bind-address=127.0.0.1 --etcd-servers=http://127.0.0.1:4001 --service-cluster-ip-range=11.1.1.0/24 --client-ca-file=/highland/config/kubernetes/certs-jenga-pp/ca.crt --tls-cert-file=/highland/config/kubernetes/certs-jenga-pp/server.cert --tls-private-key-file=/highland/config/kubernetes/certs-jenga-pp/server.key --token-auth-file=/etc/kube-known-tokens --allow-privileged=true
```

At what point should we decide whether kubernetes has failed to create the service account, versus just waiting longer?

Or, is the existence of this occasional 5-minute delay a bug that needs fixing?

**Comment by liggitt** [comment]
Do you have quota set on the new namespace? Specifically on service accounts or secrets?

**Comment by liggitt** [comment]
And how many other namespaces exist, and are they changing rapidly?

**Comment by DreadPirateShawn** [comment]
* No quotas have been set, we haven't started using those yet.
* About 6 other namespaces existed at this point, but none were changing rapidly -- our test sequence creates them sequentially and relatively slowly (create namespace, create replication controller, start building image for next service, repeat).

**Comment by liggitt** [comment]
are you running with an etcd cluster? https://github.com/kubernetes/kubernetes/pull/23858 is likely to help with this (will merge once 1.4 queue opens up)

**Comment by DreadPirateShawn** [comment]
@liggitt We are indeed running with an etcd cluster. Though, #23858 doesn't seem to reference etcd and all, and only seems to apply when using quotas -- does Kubernetes have some quotas in place by default?

(That said, agreed that #23858 seems to describe a symptom very similar to what we're seeing.)

**Comment by liggitt** [comment]
no quotas in place by default.

the work queue PR addresses the general issue of a token creation failing by requeueing failed creations (currently, failures aren't reattempted until the controller resyncs, which can be a long time)

**Comment by DreadPirateShawn** [comment]
Roger. So -- in this ticket, the service account itself didn't get created, not just the token -- would that be covered as well, or does #23858 address the secret token specifically?

**Comment by liggitt** [comment]
... 

I totally missed that. #23858 is just the token. I've never seen an issue creating the service account in a namespace. Do you see anything in the log from serviceaccounts_controller.go?

**Comment by DreadPirateShawn** [comment]
Sorry -- apart from the partial logs from the controller manager in the original ticket (filtered by the relevant namespace), the raw logs are no longer available.

But yeah, we saw contant `service account grafana/default was not found, retry after the service account is created` errors for about 5 minutes, while the service account wasn't showing up, then finally pod creation started to work.

**Comment by liggitt** [comment]
are you still seeing this in 1.4?

**Comment by DreadPirateShawn** [comment]
@liggitt Unknown -- we're currently on Kube 1.2.2 and Docker 1.10.3. We attempted to upgrade to Kube 1.4 and Docker 1.2 recently, but ultimately ran into https://github.com/docker/docker/issues/27607 as a blocker issue, and we needed to rollback fully.

We considered trying to upgrade each separately, but at this point it makes more sense to wait for Docker 1.3 (pending soon) and revisit.

**Comment by DreadPirateShawn** [comment]
@liggitt Actually, I found an environment that still had Kube 1.4 -- and yes, confirmed, I'm still able to repro this in 1.4.

Specifically:

**Comment by liggitt** [comment]
can you capture the controller manager logs and the results of a watch of service accounts in a new namespace? not seeing this elsewhere

**Comment by DreadPirateShawn** [comment]
Got it! Took let's say about 600 repro cycles, this time.

Overview:

**Start time: 1103 @ 23:54:22**

**First: Deleted namespace to ensure clean slate:**
```
Command: kubectl --server=https://192.168.0.203:6443 --kubeconfig=/highland/config/kubernetes/config delete namespace foo
namespace "foo" deleted
Waiting for namespace to disappear (up to 60 seconds)...
```
**Next: Started watch:**
```
kubectl.sh get serviceaccounts --watch --namespace=$NAMESPACE --v=8
```
**Last: Created namespace, monitored up to 60 seconds for it to appear, then monitored up to 60 seconds for the service account to appear:**
```
Command: kubectl --server=https://192.168.0.203:6443 --kubeconfig=/highland/config/kubernetes/config create namespace foo
namespace "foo" created
Waiting for namespace to appear with 'Active' status (up to 60 seconds)...
Checking for serviceaccount (up to 60 seconds)...  
Failed to create serviceaccount
=== FAIL, this is a repro of Kubernetes issue 25204. ===
```

The results of the watch are attached, as are the controller manager logs (level v=10), from 1103 @ 23:54:00 through 1104 @ 00:05:01.

[Issue25204_kube-controller-manager-kube-master1.log.gz](https://github.com/kubernetes/kubernetes/files/570822/Issue25204_kube-controller-manager-kube-master1.log.gz)

**Comment by liggitt** [comment]
in 1.5, the service account controller was rewritten to make use of a retrying queue in https://github.com/kubernetes/kubernetes/pull/35230

In your log, I see a single related error:
```
E1103 23:54:25.633607       1 serviceaccounts_controller.go:223] namespaces "foo" not found 
```

Prior to the rewrite, if an error was encountered creating a service account, it wouldn't get retried until the next sync period. Now, it will get retried repeatedly on a timed backoff.
