### ISSUE TITLE
Limit the number of images exposed as part of NodeStatus

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#25209]
`NodeStatus` currently includes a list of all images along with its size. This list can grow arbitrarily large on some clusters and it is bounded only by the disk capacity on each node. 
The main purpose for exposing images in NodeStatus is to aid scheduling, by placing pods on nodes that already contain most of the required images. 
If we can safely assume that the image pull latency for small images is negligible, then we can choose to expose only the largest `N` images on a node. This `N` can either be a fixed number for each node, or can be derived based on some threshold. For example, "expose the largest 20 images" or "expose all images that are larger than 50MB"

cc @kubernetes/sig-node

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra @smarterclayton

**Comment by yujuhong** [comment]
How is this issue different from #23355?

**Comment by aveshagarwal** [comment]
A quick thought (or concern) that comes to my mind is that from scheduling point of view, it seems like there is a high probability it might cause some applications with large images to land on some specific nodes always, somewhat tying those applications to those nodes, unless more care is taken. Only applications with smaller images would have a chance to experience  whole cluster. If this is desired that it seems very similar to pre pulling images for applications (with large images) and then scheduling them on those nodes.

**Comment by ncdc** [comment]
We have spreading predicates and priorities for that in the scheduler

**Comment by derekwaynecarr** [comment]
Is there an alternate API that could be invoked to find the exhaustive list of locally available images if its not in node status?

**Comment by vishh** [comment]
cAdvisor already exposes a list of images.

**Comment by resouer** [comment]
I will update this to a top N list
