### ISSUE TITLE
@k8s-merge-robot is a conniving liar

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#25212]
I ran into a flake on the node e2e (#24479). I asked @k8s-bot for a retest. It did kick off a new test run, but @k8s-merge-robot responded saying that I needed to link to an issue to get a retest. I was pretty sure I had, but when I checked back on my PR, my comments was gone. Luckily, I still had another window open with my comment, so I took a screenshot for evidence: https://github.com/kubernetes/kubernetes/pull/24902#issuecomment-217241961

**Comment by cjcullen** [comment]
@spxtr

**Comment by yujuhong** [comment]
+1. I have experienced it a couple of times. It ate my comments.

**Comment by eparis** [comment]
I bet it is the capital `I`

**Comment by cjcullen** [comment]
I opened https://github.com/kubernetes/contrib/issues/920 to track this in contrib.
