### ISSUE TITLE
CoreOS: Cluster scripts don't place cni plugins

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#25219]
In `cluster/saltbase/salt/cni/init.sls` the CNI plugin is downloaded / placed appropriately (e.g. `/opt/cni/bin`

The CoreOS scripts don't set this up.

This breaks rktnetes with #25062 on a `./cluster/kube-up.sh` setup.

cc @yifan-gu

**Comment by yifan-gu** [comment]
Maybe I can include the fix in #22663 ?

**Comment by yifan-gu** [comment]
Fixed by #22663
