### ISSUE TITLE
Enable search in `kubectl help`

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25234]
It'd be similar to Linux [`apropos` command](http://www.cyberciti.biz/faq/unix-linux-command/), a command to search the man page files 

@kubernetes/kubectl

**Comment by smarterclayton** [comment]
Why not just make `kubectl help` do a search if it doesn't have an exact match?

**Comment by smarterclayton** [comment]
```
kubectl help something
error: 'something' not found, did you mean:

get - a command to get values
describe - a command to show values
```

**Comment by AdoHe** [comment]
sounds good.

**Comment by bgrant0607** [comment]
SGTM

**Comment by gitfred** [comment]
Can be useful in this issue https://github.com/spf13/cobra/issues/15

**Comment by pigmej** [comment]
I will work on this issue, if nobody is already working on it ( @gitfred is not working on it).

**Comment by janetkuo** [comment]
@pigmej thanks!

**Comment by pigmej** [comment]
@janetkuo I focused currently on a bit different stuff, sorry. So I will start/finish it later. If anyone want to take over this one, feel free for now.
