### ISSUE TITLE
Implement `kubectl rollout status`

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25235]
Users now need to use `kubectl get deployment` to [check the rollout status of a deployment](http://kubernetes.io/docs/user-guide/deployments/#the-status-of-a-deployment), but it's subtle. We should add `kubectl rollout status` for better user experience. 

Ref [proposal](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/deploy.md#deployment-version), original issue #17168 and original PR #19946

@kubernetes/kubectl @kubernetes/sig-config

**Comment by AdoHe** [comment]
@janetkuo why the original PR is closed? should we reopen it?

**Comment by janetkuo** [comment]
@AdoHe it's because this can be done with `kubectl get deployments`; we wanted to receive feedback from community first before adding `kubectl rollout status` command. So yes, we should reopen it.

**Comment by janetkuo** [comment]
The PR is merged
