### ISSUE TITLE
Deployment Undo doesn't undo number of replicas

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#25236]
Execute the following:

```
kubectl create -f app-deployment.yml
kubectl scale deployment app-deployment --replicas=10
# Edit app-deployment.yml to make a change
kubectl apply -f app-deployment.yml # Replicas=4 in this file
kubectl rollout undo deployment/app-deployment

```

This results in 4 replicas running, instead of the expected 10 (since the deployment was undone).

**Comment by aronchick** [comment]
Related? https://github.com/kubernetes/kubernetes/issues/22512

**Comment by roberthbailey** [comment]
@aronchick is this a dupe of https://github.com/kubernetes/kubernetes/issues/25238?

**Comment by bgrant0607** [comment]
This is working as intended. Scaling is orthogonal to deployment. 

What if the user set up HPA? Should HPA's changes be undone? 

Scale is set/changed at least 3 different ways above (create, scale, apply). In that scenario, there's no way we could infer user intent regarding whether they expected scale to be undone or not. Note that the Deployment API doesn't really know the difference between apply and other commands, and apply doesn't itself cause Deployment versioning to happen. It's changes in the pod template spec that do, and scaling doesn't change the pod template spec.

@janetkuo is this documented in undo?

**Comment by janetkuo** [comment]
> @janetkuo is this documented in undo?

Yes, it is in http://kubernetes.io/docs/user-guide/deployments/#rolling-back-a-deployment: 
```
You should note that only the update to the Deployment’s “pod template” is seen as a different revision of rollout.
```

**Comment by janetkuo** [comment]
I'll make it more obvious, considering most people would skim the doc.

**Comment by janetkuo** [comment]
Updated docs https://github.com/kubernetes/kubernetes.github.io/pull/484

**Comment by janetkuo** [comment]
Closing since doc is updated

**Comment by aronchick** [comment]
I didn't intend to change both # of replicas & image; i overlooked the fact that the # of replicas was different when I rolled out the new image.

I have a new template that has a number of replicas in it. When I applied that new template, it used that new number in it. 

It still feels, for better or worse, that ANY changes I made should be "undone" when I roll back given what I'm doing. Documentation will not address this - years of hitting cmd-Z on my laptop tells me that whatever I just did is now rolled back, that's what this felt like.

Alternative may be if you're doing a roll out that changes multiple things, maybe we highlight that?

$ kubectl apply -f new_ds.yml
This change will apply the following changes:
replicas: 5 -> 7
image: foo -> bar
y/n?

Doesn't solve my problem entirely - since when I undo/rollback, I still would have expected 7 to go back to 5 and bar to go back to foo.

**Comment by kargakis** [comment]
We could make it configurable at the very least. Something like `--change-scaling-settings` (we already do this in OpenShift with `oc rollback`. ). @pwittrock this is where we need to know the last size for a replica set and https://github.com/kubernetes/kubernetes/pull/28162/files#diff-9035ca88b01f4a0aab7c52b8bf8a753fR79 will be useful

**Comment by bgrant0607** [comment]
Working as intended
