### ISSUE TITLE
kubectl apply -f works for only a subset of resources in the file

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#25241]
A user reported this error in the #kubernetes-users Slack channel. 

``` shell
$ kubectl apply -f kafka-services.yml
service "kafka1" configured
service "kafka-meta" configured
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"kafka2\",\"creationTimestamp\":null,\"labels\":{\"app\":\"kafka-2\"}},\"spec\":{\"ports\":[{\"name\":\"client\",\"port\":9092,\"targetPort\":0}],\"selector\":{\"broker\":\"kafka-2\"}},\"status\":{\"loadBalancer\":{}}}"},"namespace":null,"resourceVersion":null,"selfLink":null,"uid":null},"spec":{"clusterIP":null,"ports":[{"name":"client","port":9092,"targetPort":0}],"sessionAffinity":null,"type":null}}
to:
&{0xc820331920 0xc820180070 default kafka2 kafka-services.yml 0xc8204ba480 0xc8204f2160 253797 false}
for: "kafka-services.yml": Service "kafka2" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable]
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"kafka3\",\"creationTimestamp\":null,\"labels\":{\"app\":\"kafka-3\"}},\"spec\":{\"ports\":[{\"name\":\"client\",\"port\":9092,\"targetPort\":0}],\"selector\":{\"broker\":\"kafka-3\"}},\"status\":{\"loadBalancer\":{}}}"},"namespace":null,"resourceVersion":null,"selfLink":null,"uid":null},"spec":{"clusterIP":null,"ports":[{"name":"client","port":9092,"targetPort":0}],"sessionAffinity":null,"type":null}}
to:
&{0xc820331920 0xc8202b4af0 default kafka3 kafka-services.yml 0xc820154d80 0xc8202acb00 254232 false}
for: "kafka-services.yml": Service "kafka3" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable]
```

Here is their config:

``` yaml

---
apiVersion: v1
kind: Service
metadata:
  name: kafka1
  labels:
    app: kafka-1
spec:
  ports:
  - name: client
    port: 9092
  selector:
    broker: kafka-1

---
apiVersion: v1
kind: Service
metadata:
  name: kafka2
  labels:
    app: kafka-2
spec:
  ports:
  - name: client
    port: 9092
  selector:
    broker: kafka-2

---
apiVersion: v1
kind: Service
metadata:
  name: kafka3
  labels:
    app: kafka-3
spec:
  ports:
  - name: client
    port: 9092
  selector:
    broker: kafka-3
```

I tried to help debug a bit but without any luck. I think the user will be able to add more context. I will share this issue with them.

**Comment by oliverdain** [comment]
I am the user in question. The only additional context I can provide is that I was trying to do an `apply` to change the selector as, as you can see, it worked for one service but not the other two. This is a test cluster and I'm happy to get on a Google Hangouts and do a screen share if that'll help y'all debug.

**Comment by AdoHe** [comment]
@oliverdain First could you provide the original yaml which you use to create the resource? And then the new yaml file which you use to do apply, I will try to reproduce this and take a look.

**Comment by madhusudancs** [comment]
@AdoHe the yaml(s) in question is right in my issue description. Start with

```yaml
selector:
  app: kafka-{1,2,3}
```

for all the services and then replace it with the one in my message above.

**Comment by AdoHe** [comment]
@madhusudancs @oliverdain in a recently PR #25074 I have updated this, so if you use apply to create the original resource, and then update it , it should be ok. I test this on HEAD, it's ok.

**Comment by matthiasr** [comment]
We also hit this snag, also with a selector update involved. Because in 1.1 `kubectl apply` would _not_ create we have `create -f`'d every existing service in our cluster. Is there a way to recover from this without deleting and recreating the service?

**Comment by madhusudancs** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
Updates are documented here:
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/managing-deployments.md#in-place-updates-of-resources

If the lack of a config annotation is the problem, you should be able to use `kubectl patch --save-config` to make this change and add the annotation.

To remove the old label, you'll need to explicitly null the value in the patch, like the following, but using json:
```
  selector:
    app: null
    broker: kafka-3
```

cc @kubernetes/kubectl

**Comment by matthiasr** [comment]
Ah! This put me on the right path. In our case, the problem was not the absence of the annotation but its presence and content. Because of the way we had run a migration (dump objects, search/replace, apply) the `kubectl.kubernetes.io/last-applied-configuration` annotation contained more fields than our normal source files which we create-or-apply. The `apply` logic rightfully interpreted this as trying to delete all those (normally auto-generated/default-valued) fields, which works but generates an invalid object.

I realised I can work around this by going the other way and _deleting_ the annotation to force the fallback behaviour, which works well enough: `kubectl --namespace=$ns annotate service --all kubectl.kubernetes.io/last-applied-configuration-` allowed the next `apply` to proceed.

**Comment by oliverdain** [comment]
I can't confirm if this solves it or not as the cluster is now in a happy state via a manual `kubectl edit` I did a while back. However, it doesn't seem likely that this is the fix:

* The update to the first resource was fine even though it changed selectors.
* The error message wasn't about the selector, it was about `spec.clusterIP` which is something we do not want to set explicitly in our .yml files: we want Kubernetes to pick an IP for our service on our behalf.

I know that `kubectl edit` or `kubectl patch` can get the cluster in the state we want. That works but it has one big downside. If we can run apply with our resources we know what's in git matches what's running. We know that if we spin up a new cluster and re-use those .yml files we'll get the same setup (though perhaps with different IP addresses). The `patch` or `edit` route forces us to manually change the state so that we **think** it matches what's in our .yml files. Not the end of the world, but not ideal.

**Comment by matthiasr** [comment]
@oliverdain we do the same – from this discussion I updated our procedures to always use `apply`. In our case it was just an error of not using our own source files that introduced the inconsistency.

It looks like in your case the failing `patch` looked at the existing annotation and thought it should be deleting `spec.clusterIP`, which is not possible after a service exists. I don't know where it got that idea from though. I suppose you can't reproduce the state of `kubectl.kubernetes.io/last-applied-configuration` when it's failing? Are you consistently using `apply` or combinations of `create`/`edit`/`patch`/`apply`?

**Comment by dtschan** [comment]
Looks like I hit this issue on OCP 3.3 while developing an Ansible module which configures resources using `oc apply`. After a resource is edited manually, e.g. with `oc edit`, the next module run fails when calling `oc apply` with:

    metadata.resourceVersion: Invalid value: 0: must be specified for an update

Example: the resource is initially created with `oc apply` using this input:

    {
      "apiVersion": "v1",
      "kind": "ImageStream",
      "metadata": {
        "name": "rhel7",
        "labels": {
          "app": "appuio-infra"
        }
      },
      "spec": {
        "dockerImageRepository": "registry.access.redhat.com/rhel7"
      }
    }

After using `oc edit` to change the value of `.spec.dockerImageRepository` to `registry.access.redhat.com/rhel` the value the `kubectl.kubernetes.io/last-applied-configuration` attribute looks like:

    {
      "kind": "ImageStream",
      "apiVersion": "v1",
      "metadata": {
        "name": "rhel7",
        "namespace": "appuio-infra",
        "selfLink": "/oapi/v1/namespaces/appuio-infra/imagestreams/rhel7",
        "uid": "3b86f23d-8bfa-11e6-a4e6-5254003d8dc2",
        "resourceVersion": "31904",
        "generation": 2,
        "creationTimestamp": "2016-10-06T19:22:33Z",
        "labels": {
          "app": "appuio-infra"
        },
        "annotations": {
          "openshift.io/image.dockerRepositoryCheck": "2016-10-06T19:22:44Z"
        }
      },
      "spec": {
        "dockerImageRepository": "registry.access.redhat.com/rhel",
        "tags": [
          {
            "name": "7.0-21",
            "annotations": null,
            "from": {
              "kind": "DockerImage",
              "name": "registry.access.redhat.com/rhel7:7.0-21"
            },
            "generation": 2,
            "importPolicy": {}
          },
          {
            "name": "7.0-23",
            "annotations": null,
            "from": {
              "kind": "DockerImage",
              "name": "registry.access.redhat.com/rhel7:7.0-23"
            },
            "generation": 2,
            "importPolicy": {}
          },
          {
            "name": "7.0-27",
            "annotations": null,
            "from": {
              "kind": "DockerImage",
              "name": "registry.access.redhat.com/rhel7:7.0-27"
            },
            "generation": 2,
            "importPolicy": {}
          },
          {
            "name": "7.2",
            "annotations": null,
            "from": {
              "kind": "DockerImage",
              "name": "registry.access.redhat.com/rhel7:7.2"
            },
            "generation": 2,
            "importPolicy": {}
          },
          {
            "name": "latest",
            "annotations": null,
            "from": {
              "kind": "DockerImage",
              "name": "registry.access.redhat.com/rhel7:latest"
            },
            "generation": 2,
            "importPolicy": {}
          }
        ]
      },
      "status": {
        "dockerImageRepository": "172.30.1.1:5000/appuio-infra/rhel7",
        "tags": [
          {
            "tag": "latest",
            "items": [
              {
                "created": "2016-10-06T19:22:44Z",
                "dockerImageReference": "registry.access.redhat.com/rhel7@sha256:eac2421be7a6844a5c83b8f394d1f5f121b18fa4e455c5f09be940e0384a1d97",
                "image": "sha256:eac2421be7a6844a5c83b8f394d1f5f121b18fa4e455c5f09be940e0384a1d97",
                "generation": 2
              }
            ]
          },
          {
            "tag": "7.2",
            "items": [
              {
                "created": "2016-10-06T19:22:44Z",
                "dockerImageReference": "registry.access.redhat.com/rhel7@sha256:300ee766706e2ab3b0fb0022902bf5418fafc15ca771b4ae33d5e920be294771",
                "image": "sha256:300ee766706e2ab3b0fb0022902bf5418fafc15ca771b4ae33d5e920be294771",
                "generation": 2
              }
            ]
          },
          {
            "tag": "7.0-21",
            "items": [
              {
                "created": "2016-10-06T19:22:44Z",
                "dockerImageReference": "registry.access.redhat.com/rhel7@sha256:141c69dc6ae89c73339b6ddd68b6ec6eeeb75ad7b4d68bcb7c25e8d05d9f5e60",
                "image": "sha256:141c69dc6ae89c73339b6ddd68b6ec6eeeb75ad7b4d68bcb7c25e8d05d9f5e60",
                "generation": 2
              }
            ]
          },
          {
            "tag": "7.0-23",
            "items": [
              {
                "created": "2016-10-06T19:22:44Z",
                "dockerImageReference": "registry.access.redhat.com/rhel7@sha256:a588fb3e2db43b58d01606de547c8c0723790b96d666a25d113cbf3d6d7ddaa6",
                "image": "sha256:a588fb3e2db43b58d01606de547c8c0723790b96d666a25d113cbf3d6d7ddaa6",
                "generation": 2
              }
            ]
          },
          {
            "tag": "7.0-27",
            "items": [
              {
                "created": "2016-10-06T19:22:44Z",
                "dockerImageReference": "registry.access.redhat.com/rhel7@sha256:489b7ba5ed0c9f63d85fd94b990f52b719f2bde006a0df168d2999fc771e5cca",
                "image": "sha256:489b7ba5ed0c9f63d85fd94b990f52b719f2bde006a0df168d2999fc771e5cca",
                "generation": 2
              }
            ]
          }
        ]
      }
    }

And running `oc apply` with the original input generates above error message. Removing the `kubectl.kubernetes.io/last-applied-configuration` attribute from the resources works around the issue.

**Comment by exarkun** [comment]
Here is the code (found for me by a colleague) responsible for generating the "spec.ClusterIP" error message:

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L2584-L2588

The condition is basically "If the service's old type was not ExternalName and the service's new type is not ExternalName and the service's old spec had a ClusterIP assigned, reject the update with the 'immutable field' message."

This strikes me as a legitimate bug in `ValidateServiceUpdate`.  If the new service spec is not trying to set the ClusterIP, the update should be allowed.

The other error in the original report, 'metadata.resourceVersion: Invalid value: "": must be specified for an update' looks like user error to me.  To update an object, you must set metadata.resourceVersion to the object's current resourceVersion or the update is rejected.  This is a safety measure in the API to prevent unintentionally clobbering the data from a different update you didn't account for.

The `spec.ClusterIP` part of this, the legitimate bug, is currently biting me and means I'll have to implement some more complicated PATCH logic for my application instead of the simpler (also correct) PUT that I was hoping to do.

**Comment by AdoHe** [comment]
@ymqytw ptal.

**Comment by banchee** [comment]
So I have run into this issue, and needing to use circleCI to apply new changes to our cluster. How I got around the clusterIP issue is as follows 

```
cluster_ip=`kubectl get svc nginx-ingress-controller -o json | jq '.spec.clusterIP'`
```
```
sed -e 's/\$CLUSTER_IP/'"$test_ip"'/' < k8s/deployments/nginx-ingress.template.yaml > k8s/deployments/nginx-ingress.yaml
```

Then in the k8s/deployments/nginx-ingress.template.yaml I have the following - **see clusterIP key** 

```
# Source: nginx-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.8.4
    component: "controller"
    heritage: Tiller
    release: lucky-owl
  name: nginx-ingress-controller
spec:
  clusterIP: $CLUSTER_IP  # Value to be replaced with clusterIP address from service
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: nginx-ingress
    component: "controller"
    release: lucky-owl
  type: "LoadBalancer"

```

Then after the new files has been created from the template file, I run apply and dont get the clusterIP is immutable error. 

Hope this helps out the next poor soul who runs into this issue. 

Running 1.7.5 on both client and cluster, and the `apply` is still returning the error - as state by @exarkun earlier.

**Comment by bgrant0607** [comment]
Another apply issue
cc @apelisse

**Comment by thockin** [comment]
@apelisse close?

**Comment by apelisse** [comment]
Yeah, this is so old (with very few updates in the last few years), I'm not really sure it's relevant anymore.
