### ISSUE TITLE
Update documentation examples incorrectly referring to replication controllers with replica sets

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/kubernetes#25248]
A number of examples spread across various documentation pages still speak of replication controllers where they should instead say replica sets. Many of these are of an introductory nature and thus tend to confuse Kubernetes newcomers in particular (as determined anecdotally by the number of Slack questions I personally see getting posted in this regard). One particular use case is the application of the `kubectl run` command which is often accompanied by telling the reader to run `kubectl get rc` to see the created replication controllers afterwards where instead it should be `kubectl get rs` these days to list replica sets.

All such occurrences should be updated accordingly. Specifically, I came across

- http://kubernetes.io/docs/user-guide/simple-nginx/
- http://kubernetes.io/docs/user-guide/pods/multi-container/
- http://kubernetes.io/docs/user-guide/walkthrough/k8s201/

There may be additional pages though that I'm not aware of.

I'd be happy to provide a PR to update the pages above and any others people point out.

Thanks.

**Comment by roberthbailey** [comment]
@timoreimann PRs would be greatly appreciated!

**Comment by bgrant0607** [comment]
Any `kubectl run` examples should actually mention Deployment, not ReplicaSet. 

There are other issues at least for simple-nginx.

cc @janetkuo

**Comment by bgrant0607** [comment]
See also #23604

**Comment by timoreimann** [comment]
@bgrant0607 I suppose this ticket could be considered a duplicate of #23604. Would you prefer to have PRs targeting that issue or this one? In case of the latter, how do the two differ?

Still happy to provide pull requests if that's desired. Thanks!

**Comment by bgrant0607** [comment]
@timoreimann Yes, this is a duplicate. If you could copy relevant info to the other issue and then close this one, that would be appreciated.

**Comment by timoreimann** [comment]
@bgrant0607, thanks for moving things over to the other issue. Apologies for not taking care of things myself, was busy all day.
