### ISSUE TITLE
AWS: applications become unavailable when nodes are being scaled down

### ISSUE THREAD

**Issue by luispabon** [kubernetes/kubernetes#25257]
I have an experimental set up on a cluster using k8s 1.2.3 on AWS, configured with autoscaling both of nodes and of pods.

I have manually added policies to the generated AWS autoscaling group to both scale up and down the cluster based on certain metrics, as k8s' command line tooling (eg kube-up.sh) don't seem to support this.

Scaling up works well. Pods are flowed into the new node very quickly after it becomes available.

Scaling down however completely breaks the cluster for a few minutes, turning some of the apps unavailable. The ELBs correctly remove nodes as they become unavailable, but k8s seems very slow to react - a good 3 or 4 minutes. 

It looks as if some pods only have presence on the node being taken (this includes the system pods such as grafana or dashboard as well as my application pods), and when this happens, these services become entirely unavailable.

My replication controllers and pod autoscaling define a minimum of 1 pod per rc, and a maximum which depends on the application's and my own budgetary requirements.

**Comment by errm** [comment]
I think there is a 5 minute timeout on a node being marked as dead when it goes away.

You might have better results if you set the minimum number of pods in the autoscaler to 2, and ensure that your AWS autoscaling policy does not remove more than 1 node every 5 minutes.

**Comment by luispabon** [comment]
It's not much better. I have set up a new environment with 2 nodes and all my apps deployed with a minimum of 2 replicas. Then I've manually terminated one of the minions.

Applications still went unavailable for a couple of minutes.

Also, when the new node came back up online, pods failed to flow into it.

**Comment by luispabon** [comment]
Interestingly, when I bring the node down, new pods are created pretty much straight away, and I can from the command line open a shell into all of them. The service however is still unavailable from the ELB endpoint, even though the ELB only points to the only node available.

**Comment by vrobert78** [comment]
We are facing the same problem on GKE.
On a scale down, if the evited node contains kube-dns container, the service discovery seems to be unavailable until it will be fully restarted on another node.

Our apps become unavailable, nginx can't connect to phpfpm:

nginx: [emerg] host not found in upstream

**Comment by justinsb** [comment]
@luispabon how did you install the cluster?  I believe that if you're running kube-controller-manager with the aws cloud-provider option, we should poll the instances and rapidly delete the instance when it is deleted in the AWS API.

**Comment by luispabon** [comment]
@justinsb the cluster was deployed with the kubernetes-provided aws cloud scripts (kube-up).

**Comment by ProTip** [comment]
Has consideration been put into using autoscale [LifeCycle Hooks](http://docs.aws.amazon.com/autoscaling/latest/userguide/lifecycle-hooks.html)? This would provide kubernetes with the opportunity to relocate the pods before the instance is terminated. It could also be handy for an ELB ingress controller..

**Comment by ahasnaini** [comment]
Getting the same issue, I killed the node myself wanted to test how kubernetes reacts to it. For someone service become entirely unavailable even thou pods were running on other nodes.
Currently kubernetes doesn't work well at all with a node dying on aws atleast.
