### ISSUE TITLE
Incorrect comparison in unversioned.MatchesServerVersion

### ISSUE THREAD

**Issue by dominikh** [kubernetes/kubernetes#25252]
The following code compares cVer.GitTreeState against itself. The RHS should probably use sVer instead:

```
if cVer.GitVersion != sVer.GitVersion || cVer.GitCommit != sVer.GitCommit || cVer.GitTreeState != cVer.GitTreeState {
	return fmt.Errorf("server version (%#v) differs from client version (%#v)!\n", sVer, cVer)
}
```

```
/src/github.com/kubernetes/kubernetes/pkg/client/unversioned/helper.go:117:79: identical expressions on the left and right side of the '!=' operator
```

**Comment by lavalamp** [comment]
Note that fixing this may make kubectl complain about mismatched versions much more frequently...

**Comment by caesarxuchao** [comment]
kubectl's "match-server-version" flag is default to false and in our repo it's set to true only in test-cmd.sh. I don't think many people set this flag in production, and even if they do, they expect kubectl to complain. So I think the fix is fine.
