### ISSUE TITLE
Stabilize describer outputs

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/kubernetes#25251]
All describers should exhibit a stable output behavior; that is, the output should only change if the state of the underlying object changes. Specifically, we should make sure that all iterations over maps (which Go randomizes) are always carried out in a stable, deterministic fashion.

TODO list (and related object(s)):
- [x] QoS classes (pod)
- [x] resource limits (pod)
- [x] resource requests (pod)
- [ ] labels
- [ ] annotations
- [ ] selectors
- [ ] secrets
- [ ] ConfigMap data
- [ ] Flex volume source options

(_Original issue descriptions:_

`kubectl describe pod <some pod>` enumerates container resources for various aspects, namely CPU and memory for QoS tiers, limits, and requests at this moment. When invoking the command multiple times, one can see that the order is not stable: Sometimes, CPU is listed before memory, and other times it's just vice versa. It's not stable across resource types either (i.e., QoS tiers may show CPU first while limits doesn't).

For certain use cases (such as when passing the command to `watch -1`), a stable order would be helpful to minimize distraction from such "irrelevant" output changes.

Happy to work on a PR if folks agree.)

**Comment by bgrant0607** [comment]
This is due to random map order. Agree that stable order would be useful.
cc @kubernetes/kubectl

**Comment by smarterclayton** [comment]
Agreed - all describers should be stable order and we should probably make sure we educate reviewers to look for that.

**Comment by bgrant0607** [comment]
Among other things, all maps need to be sorted.

**Comment by timoreimann** [comment]
Unless someone has already started to work on this, I'd like to take a stab.

**Comment by gitfred** [comment]
@timoreimann Have you started working on this? If not I would like to take it over

**Comment by timoreimann** [comment]
@gitfred I did actually. I plan to push out a PR over the weekend.

**Comment by timoreimann** [comment]
@roberthbailey @bgrant0607 @smarterclayton @jlowdermilk @derekwaynecarr fixed order output for pod descriptions. Do you know of any other describers that use maps as well? A quick glance on my end didn't yield anything but maybe I missed some.

**Comment by bgrant0607** [comment]
@timoreimann Maps in the API are: labels, annotations, resources, selectors, Secret and ConfigMap data, Flex volume source options

**Comment by timoreimann** [comment]
@bgrant0607 thanks. I'll go over the list and see what still needs to be done. Please let me know if you have a preference towards either covering everything as part of this issue or a new one (that I can create) instead.

**Comment by derekwaynecarr** [comment]
I think this one issue is fine to track.  The current work handled resources.  If you want to put a task list on the issue to track that is fine too.

**Comment by timoreimann** [comment]
@bgrant0607 @derekwaynecarr I updated the issue title and description to better reflect the broader scope of the ticket.

Will continue to work on the individual bits and pieces.

**Comment by errordeveloper** [comment]
I fixed two bugs that relate to this (https://github.com/kubernetes/kubernetes/pull/32229, https://github.com/kubernetes/kubernetes/pull/35112), I think we need a better contract.

I am looking at `pkg/kubectl/describe.go` and, and I feel like it can be made more elegant with good use of `text/template`, or maybe be just a few extra structs could work better. It's just a massive set of special cases right now, with formatting characters everywhere (which seem fairly consistent, but you can never tell 100%).

To illustrate, the structs could look something like these:
```Go

type Section struct {
   Name string
}

type LineDescriptions struct {
    Tabs int32
    Data map[string]string
}

type Table struct {
    Head []string
    Data  [][]string
}
```

Let's also consider more convertable output formats, I am thinking of markdown or something similar (of course we don't want YAML, we already have that), it'd help a lot for folks who want to work on IDE integrations and other similar things (I've started more specific discussion in https://github.com/kubernetes/kubernetes/issues/37576).

**Comment by smarterclayton** [comment]
Since we're going to move this to the server side, it would be better not
to dig into this until we settle on that design.

On Mon, Nov 28, 2016 at 5:24 PM, Ilya Dmitrichenko <notifications@github.com

**Comment by AdoHe** [comment]
@smarterclayton you mean this proposal #29472?

**Comment by smarterclayton** [comment]
That was the rough draft yes - it needs more detail on describe.

**Comment by timoreimann** [comment]
Just picked up this issue again.

@smarterclayton is it okay to continue working on the describer output? or is that move to the server side still ongoing?

**Comment by smarterclayton** [comment]
We’re going to discuss it again the first week in January.  Probably best to wait until then

**Comment by timoreimann** [comment]
@smarterclayton have you had a chance to discuss the matter?

**Comment by timoreimann** [comment]
Still plan to do this, albeit with low priority.

/remove-lifecycle stale

**Comment by McCoyAle** [comment]
Hey, @timoreimann @errordeveloper This one has been open for some time. Is there anything that is needed?

**Comment by timoreimann** [comment]
@McCoyAle tbh, I haven't worked on this one so long that I'm not sure whether it's still relevant. Do you possibly know? If not and you happen to have a moment to verify whether output ordering is still an issue, I'd love to hear about it.

**Comment by timoreimann** [comment]
for now:

/remove-lifecycle rotten
