### ISSUE TITLE
Add doomed-to-failure detection to Job

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#25254]
Per [this comment](https://github.com/kubernetes/kubernetes/issues/24533#issuecomment-217058534) we want infant-mortality detection to Job, with no knob, and backoff in the event of failures in the middle of Job execution (#2529).

**Comment by soltysh** [comment]
@bgrant0607 mind assigning this one to me

**Comment by bgrant0607** [comment]
cc @erictune @kargakis @janetkuo

**Comment by derekwaynecarr** [comment]
Can we avoid calling it by this name?

**Comment by pmorie** [comment]
please

**Comment by derekwaynecarr** [comment]
Maybe premature failure detection, where failure window is defined as X

**Comment by soltysh** [comment]
The name is an open topic, I don't mind picking a different one.

**Comment by erictune** [comment]
Renamed "doomed-to-failure"

**Comment by erictune** [comment]
Closing in favor of #30243
