### ISSUE TITLE
Watch seems to NOT work with protobufs

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25258]
Today I enabled e2e suite where we are using protobufs to:
- communicate with apiserver
- store them in etcd

Tests are not even starting, because system pods are not starting. And it seems that scheduler is not even seeing anything to schedule.

I did some experiment and added a log in framer:
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/framer/framer.go#L87

to see the value of "remaining".

And here is what I'm getting:

    E0506 12:19:41.455467       6 framer.go:89] 2065855609
    E0506 12:19:47.876298       6 framer.go:89] 2065855609
    E0506 12:19:48.370385       6 framer.go:89] 2065855609
    E0506 12:20:05.628425       6 framer.go:89] 2065855609
    E0506 12:20:11.906172       6 framer.go:89] 2065724537
    E0506 12:20:32.481072       6 framer.go:89] 2065855609
    E0506 12:21:09.922379       6 framer.go:89] 2065593465

It seems that something is wrong with framer.

@smarterclayton

**Comment by wojtek-t** [comment]
We are definitely not having objects of 2GB - those "remaining" values should be in order of 1000s

**Comment by smarterclayton** [comment]
It's probably pretty easy to recreate this under the BenchmarkWatchProtobuf if it's on the server side - just add arbitrarily large fields to some of the items

**Comment by wojtek-t** [comment]
I'm still not sure if it's server or client side. Still debugging.
BTW, I tried to modify the existing test in watch_test.go, but so far it's passing for me.

**Comment by wojtek-t** [comment]
BTW, to reproduce:

    export TEST_CLUSTER_API_CONTENT_TYPE="--kube-api-content-type=application/vnd.kubernetes.protobuf"
    export TEST_CLUSTER_STORAGE_CONTENT_TYPE="--storage-media-type=application/vnd.kubernetes.protobuf"
    make clean && make quick-release && go run hack/e2e.go -v --up

**Comment by wojtek-t** [comment]
Another finding:
- it seems that client is using "lengthDelimitedFrameReader" (it is first reading 4 bytes as a length of the frame)
- it seems that server is NOT using "lengthDelimitedFrameWriter" (I added a lot in its Write() method and this log doesn't appear at all)

**Comment by smarterclayton** [comment]
Definitely a bug.  Is the framer not set in the codec factory?

On May 6, 2016, at 8:51 AM, Wojciech Tyczynski <notifications@github.com>
wrote:

Another finding:

   - it seems that client is using "lengthDelimitedFrameReader" (it is
   first reading 4 bytes as a length of the frame)
   - it seems that server is NOT using "lengthDelimitedFrameWriter" (I
   added a lot in its Write() method and this log doesn't appear at all)

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/25258#issuecomment-217430535>

**Comment by wojtek-t** [comment]
What I don't understand is that we are using exactly the same CodecFactory both in client and server.
So maybe WatchServer is not receiving anything from storage?

**Comment by wojtek-t** [comment]
I mean from cacher? But we didn't change cacher at all, so if it works for jsons, it should also work for protobufs.

Let me do an experiment what happens if I switch on protobufs only for storage and clients will still be using jsons.

**Comment by smarterclayton** [comment]
Maybe my changes with StreamSerializerInfo broke it.  I don't see an obvious spot where it would have chosen the wrong framer.

**Comment by wojtek-t** [comment]
Hmm - I have some problem with my project, so those experiments might take me some time.

I'm still wondering why may client behavior differ from server behavior, so maybe something else is wrong... But I don't see the reason why client is using framer and server seems to not use it...

**Comment by wojtek-t** [comment]
OK - so I confirmed that if we just switch protobufs on for storage, that seem to work.

So the problem is in the server <-> client communication.
So if storage works fine (which means cacher which we don't touch when changing client<->server communication is also working fine and delivering watch events to WatchServer) that means that something is probably wrong with framer on the apiserver side.

That's at least my hypothesis.

**Comment by wojtek-t** [comment]
So one more data point - I took a look what Framer in apiserver is.
And printing reflect.TypeOf(framer) here
https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/watch.go#L149
returns:

    fancyResponseWriterDelegator

IIUC, that means, that s.framer there is simply returning the given ResponseWriter.

Which means we are using incorrect framer in apiserver. Don't know why yet.

**Comment by wojtek-t** [comment]
OK - so the problem is that in apiserver we are using JSON as a streaming serialization codec.

So the problem seem to be that Accept header is empty (although I'm not sure why, yet)

**Comment by wojtek-t** [comment]
But what I confirmed for 100% is that apiserver is using JSON streamserializer instead of protobuf one.

**Comment by wojtek-t** [comment]
@smarterclayton - I'm assuming that you didn't have time to look into it yesterday, right? I'm going to look into it on Monday, so if you have any further findings just let me know.

**Comment by smarterclayton** [comment]
No, got bogged down in other stuff

**Comment by wojtek-t** [comment]
Looking into it now. I already have some hypothesis - need to verify (it seems we are not setting headers for watch & stream requests).

**Comment by wojtek-t** [comment]
Got it - the fix is pretty easy. Will send a PR for it shortly.
