### ISSUE TITLE
Determine which File system plugins work, and are  stable for writing 1k, 1M, 1G of data,  over service endpoints.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#25268]
I think @rootfs  mentioned this hasn't been tested thoroughly in e2e tests.
- we want to know that volume plugins ability to work for basic content is tested in CI, at least for some highly stable things like NFS.
- (previously used --scale idea for the plan but now moving to using viper to customize data structures, see logging_soak for example)

**Comment by jayunit100** [comment]
@kubernetes/sig-testing @kubernetes/sig-storage

**Comment by jayunit100** [comment]
this stems originally from some thoughts in #22665 , #24687

**Comment by childsb** [comment]
Similar #28367

**Comment by jeffvance** [comment]
@msau42 @jayunit100 @timothysc:
I'm looking at possibly combining tests for this issue and [28367](https://github.com/kubernetes/kubernetes/issues/28367) in a single suite. Also I've been looking at the existing _logging_soak.go_ and _storage/volumes.go_ tests for ideas. 
Questions: 
1. should this new test be its own file or would it be better to leverage an existing test? Adding a new `It` block to _volumes.go_ to handle large i/o/streaming test cases seem reasonable to me.
2. do we need to run the i/o tests simultaneously on all nodes, as done in the log soak? Or is it ok to run the i/o tests (one per plugin) and let them run on whichever node they hit?
3. is a bash `for` loop writing to a known file an acceptable way to simulate larger writes and streaming? Is a `sleep` in this loop necessary or is it better without? 
Thanks.

**Comment by jayunit100** [comment]
- own file for sure under storage/
- IMO run on all nodes like we do in logging_soak with a target percentage of 50% of nodes completing or something.  Make that percentage viperizable as well. 
- the nice thing is that the echo+sleep means you can pull down a tiny e2e test image from test/images/ as the base image and customize it in the e2e test code, rather then having to maintain separate code for your docker image.  
- Echo performance: Probably not worth bikeshedding on it b/c even it was is not a 'perfect' I/O mechanism, you can always amortize writing the file out and using cat if you need to optimize it later.

**Comment by jsafrane** [comment]
I've noticed there is a test that reads 1MB, 100MB and 1GB  from some volume plugins (depending of availability of containerized server and its image size). See https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volume_io.go

/close
