### ISSUE TITLE
Documentation incorrect for e2e testing on local cluster  

### ISSUE THREAD

**Issue by mikebrow** [kubernetes/kubernetes#25264]
The documentation for learning how to run e2e tests sends you down a path that will not work.  Specifically it has you set up a single node local cluster to run the e3e tests locally. See: 

```
Local clusters

It can be much faster to iterate on a local cluster instead of a cloud-based one. To start a local cluster, you can run:

# The PATH construction is needed because PATH is one of the special-cased
# environment variables not passed by sudo -E
sudo PATH=$PATH hack/local-up-cluster.sh
This will start a single-node Kubernetes cluster than runs pods using the local docker daemon. Press Control-C to stop the cluster.

Testing against local clusters

In order to run an E2E test against a locally running cluster, point the tests at a custom host directly:

export KUBECONFIG=/path/to/kubeconfig
go run hack/e2e.go -v --test_args="--host=http://127.0.0.1:8080"
```

Run the cluster...  run `go run hack/e2e.go -v --build --up --test --down`

Build works fine ... then on the --up part you get the following error:
 e2e.go:170: Cluster size (1) is too small to run e2e tests.  2 Nodes are required.

Am I missing something?  Or should the docs be edited to include pointers to local multi-node setup for docker?  If so I'll PR the docs. 

Cheers.

**Comment by rpothier** [comment]
Are there still issues with the documentation for e2e on local clusters?
I am getting many failures running e2e. Is something missing? 
Is it expected that e2e should work on a local cluster?

**Comment by mikebrow** [comment]
Yes, e2e should work now on a local single node cluster. The docs were cleaned up some and the bug referenced by this issue was fixed a while back. Closing this issue as I thought it was already closed. @rpothier failures on e2e tests may be known flake issues that need to be resolved.
