### ISSUE TITLE
Allow enabling AWS ECR Credentials Provider outside AWS nodes

### ISSUE THREAD

**Issue by spiralman** [kubernetes/kubernetes#25265]
It would be nice to be able to enable the AWS ECR Credentials Provider independent from setting the cloud-provider to "aws".

We would like to enable developers to stand up their own instance of our cluster and services on their local machines to enable local integration testing. 

Our particular use-case is:
1. Developer stands up local cluster inside docker, using `latest` images from ECR for all services
2. They do their development on Service X
3. They do a local build of Service X and push it to their local cluster for testing.

By enabling the ECR credentials plugin on their local cluster, the developers can quickly get a stack up and running without worrying about building or pulling down all the services that are necessary to run, but not ones they are currently working on.

There would be some obvious other use cases, too, such as consolidating an image registry for clusters deployed in multiple vendors, or using ECR for clusters not hosted in AWS (i.e. in a cloud provider that doesn't provide a Docker Registry, or on a bare metal cluster).

I saw there is a `TODO` about this in the ECR Credentials Plugin source, but could not find an issue for it. If this is a dupe (or covered elsewhere), please feel free to close it as such.

**Comment by therc** [comment]
I wrote the ECR code and that TODO in particular. I was thinking of the bare metal cluster use case (we have one we'll migrate to Kubernetes, but only after we can support multiple GPU devices per node). I guess this issue is mine.

**Comment by Kamshak** [comment]
That would be very nice, exact same use case as @spiralman here! Is there a way to achieve this right now?
