### ISSUE TITLE
Hook for executing command before reducing number of pods deployed

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#25275]
**Need / Justification**

Multiple big data stacks, and other technologies, cannot gracefully leave a their cluster when running inside of k8s

I have been looking for something to get my hooks into for more of a contribution to this project, and this may be one of them.  Before I start coding could use some advice on making sure this is not supported and how to do this well.  Still bit of a n00b when is comes to k8s source base!

From the docs:

There are currently two container hooks that are surfaced to containers:

**PostStart**
This hook is sent immediately after a container is created.  It notifies the container that it has been created.  No parameters are passed to the handler. It is NOT guaranteed that the hook will execute before the container entrypoint.

**PreStop**
This hook is called immediately before a container is terminated. No parameters are passed to the handler. This event handler is blocking, and must complete before the call to delete the container is sent to the Docker daemon. The SIGTERM notification sent by Docker is also still sent. A more complete description of termination behavior can be found in Termination of Pods.

I have a use case for a third hook:

**PreStopReduceSizeOfScale"

This is a horrible name, but going with it for now.  

_Use Case_

Multiple big data stacks, and other technologies, require a unit of work to be completed for a member of a cluster / ring / group to leave.  For example:
- Cassandra requires a `nodetool decommission` for a node to leave a ring.  
- Elastic requires HTTP rest call to be executed to modify the cluster routing allocation.
- Kafka requires a reassign partition command

I a lot of cases using a `PreStop` is fine.  But a use case is upgrades with PetSet.  You need to be able to run a `kubectl rolling-update`. I don't believe rolling-updates is supported by PetSet at this point, but that is an open question.

**Comment by chrislovecnm** [comment]
@bgrant0607 can you assist with the tagging, and who the heck do I talk to about this one ...  

Got another fun one coming in ..

**Comment by bgrant0607** [comment]
Cc @bprashanth @smarterclayton

**Comment by chrislovecnm** [comment]
@bgrant0607 much appreciated!

**Comment by smarterclayton** [comment]
The goal is to have something concrete an admin can invoke in the PetSet when cluster membership changes.  No promises for 1.3 (with alpha pet set), but we totally agree the use case you describe is critical to operation.

**Comment by chrislovecnm** [comment]
@smarterclayton much thanks, was not expecting it in 1.3 - just am happy to build a herd of pets ... Would it be a school of pets ;)

**Comment by bprashanth** [comment]
> The goal is to have something concrete an admin can invoke in the PetSet when cluster membership changes. No promises for 1.3 (with alpha pet set), but we totally agree the use case you describe is critical to operation.

Yes that's "on-change". The request seems to be specifically about "on-scale-down".
If you can figure out that it's a scale down when you get a list of peers on-change, great.
If not, I'm still not convinced you can't just either terminationGracePeriodSeconds or prestop. 

Why is it significant that you know the delete is in fact a delete from petset scale, vs a delete from user? Today, if you scale a petset down by N, it will do so one by one. Meaning you get:
pod-1,2,3
pod-3 receives sigterm (and prestop)
petset controller waits till pod-3 is dead
pod-2 receives sigterm (and prestop)

Maybe you can elaborate on the specific rolling-update case?

**Comment by bprashanth** [comment]
A channel whereby an admin can invoke the script is easy. Dosn't matter what the script it, it can be on-change, on-foobar etc. If the system is going to be responsible for sending the notifications, the easiest thing to detect is on-change.

**Comment by smarterclayton** [comment]
this also gets into the script being able to easily know the desired scale of the cluster, vs the current scale.

**Comment by chrislovecnm** [comment]
> Why is it significant that you know the delete is in fact a delete from petset scale, vs a delete from user? 

Both are the same.  The Pet needs to know if it is being deleted, restarted, or updated.  

We have three different behaviors in my mind.

1. scale down - DELETE - drain node - drop the mike - walk away
2. rolling update - UPDATE - restart the pid - sequential (1,2,3,4,5)
3. rolling restart - RESTART - stop - update container - use the same disk - start 

Scale down is just that.  I am a pet that is leaving the cluster.  I need to notify the cluster and drain my data off of disk.

Rolling update is when I am a pet that is not leaving the cluster, I just need a new container to update.  Then need to occur sequentially in order to maintain cluster data integrity :)

Rolling restart - yah my cluster is not happy.  I need to restart the entire thing LIVE.  Don't move data, don't update container ... restart. Sequential

Theoretically you can handle leave an update in the same manner - but here is some math if we force a data move around the cluster on an upgrade / replace / restart.  

So let's do some math.  And can someone who is smarter than this engineer check it ... Cause I went to school for engineering not math ... LOL

500 GB - 1TB per C* container stored on GCE ssd persistent disk.  So say 750 GB ... pretty much the sweet spot for C*.
1000 C* containers

So that is 750 terabytes.  Not a huge amount of data (yah I typed that ... wow) ...  We have to get it off of the disk and over the wire.

So gce instance time - n1-standard-16 * 2GB/s * 16 cores = 32 GB per second. 
 
Theoretically.  23 437 seconds (6.5 hr) to move 750 TB.  And that is at full network saturation and degraded service.  Which you can NEVER do :) So scratch 6.5 hrs.

So say we can only use 30% of our network bandwidth for an upgrade.  So that is 32 GB/s * .3 = 9.6 GB/s.  That is reasonable.  So 750 TB / 9.6 GB/s = 78 125s.  So that is 21 hrs.  I would push it up again ... 24 hr.

That is just the time to move the data off of the disk, and on to another disk.  That does not include the time that it takes for the new pod to launch. Then we have to move the data back ...  Say in a super busy system it takes 2 min for a new disk and a new pod to be pulled and launched.

2 min * 1000 = 1.3 days.  I am thinking that the disk creation is the bottle neck.

Then move the data back ... another 24 hours.

So we are talking 3 days ish ...

Now if we don't have to move the data around, and can do a petSet update with the data in place - 24 hrs ish.  That is 24 hrs for 1k upgrade vs 3 days.  

Am I wrong?  Please tell me I am hallucinating and awful at math! How else can we do this better?

**Comment by bprashanth** [comment]
> Theoretically you can handle leave an update in the same manner - but here is some math if we force a data move around the cluster on an upgrade / replace / restart.

Yeah, thanks for the context, that's the discussion we had https://github.com/kubernetes/kubernetes/pull/24912#discussion_r61774323.

Most of the pets I've prototyped, modelling an update as: leave cluster, updated, join cluster works. Agree that we can do better with fine grained events, we should target this > alpha. Most likely > beta though, since the main focus for beta will be getting things like upgrade (including node upgrade with pets on it) to *work* in a generic way for all pets.

**Comment by timothysc** [comment]
xref: https://github.com/openshift/origin-metrics/issues/141#issuecomment-225294524

**Comment by chrislovecnm** [comment]
A work in progress here https://github.com/kubernetes/kubernetes/pull/26884#issuecomment-225190426

**Comment by eyalzek** [comment]
So the solution ATM is to use pod disruption budget on the stateful set and handle scaling down manually? Or did I miss some functionality ?

**Comment by Dhatchana** [comment]
We are facing the similar issue. There is no way to identify with the present hook whether the shutdownhook is called during descaling or restart or upgrade scenarios. 

Let us know how to fix this.
