### ISSUE TITLE
Validating GCI image as the default image for GCE & GKE

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#25276]
We want to deprecate today's debian-based container-vm image, and switch to GCI image by default. Before we do that, we need to validate the image using Kubernetes testing infrastructure. GCI image has three different release channels: dev, beta, and stable. Besides that they also build ci release nightly. Today we already run the the following jenkins jobs against each image release: 
  * kubernetes-gce-e2e, 
  * kubernetes-gce-e2e-slow,
  * kubernetes-gce-e2e-serial
  
But we are missing kubernetes-gce-e2e-soak, kubernetes-gce-e2e-scalability, probably also kubernetes-gce-e2e-upgrade (? not sure how to handle this since it is the first release), and kubernetes-gce-e2e-features.

We also need to include gci image to node-e2e test suite too. 

Next step we should to identify the critical builds for gci to block merge-bot. 

Eventually, we can switch GCI image as the default image on GCE, but keep debian-based container-vm image testing until we can deprecate it.

@andyzheng0831 and @wonderfly are going to write detail plan on this. 

cc/ @roberthbailey from GKE side. 
cc/ @mansoorj from PM side

**Comment by roberthbailey** [comment]
> Eventually, we can switch GCI image as the default image on GCE, but keep debian-based container-vm image testing until we can deprecate it.

Why not do this now so that we get as much soak time as possible before the 1.3 branch is cut? I'm not sure if we want to duplicate all of the soak and scalability tests or just start running them on GCI instead of the older debian-based container-vm.

**Comment by wonderfly** [comment]
I think this can be closed now?

**Comment by roberthbailey** [comment]
We are using it as the default for masters, but not as the default for nodes. The team/node label is still on this issue, so I expect we will use it to track switching the default on nodes (maybe as part of the 1.4 release).

**Comment by wonderfly** [comment]
> We are using it as the default for masters, but not as the default for nodes. The team/node label is still on this issue, so I expect we will use it to track switching the default on nodes (maybe as part of the 1.4 release).

In that case, lets close this (to progress so far) and create another one just for nodes?

**Comment by timstclair** [comment]
Assigning to Michael to find an owner.

**Comment by dchen1107** [comment]
This one was filed for using GCI image for nodes by default.

**Comment by goltermann** [comment]
@dchen1107 This is a 1.4 P0, but hasn't been touched in a while.  What's the latest?

**Comment by vishh** [comment]
Current status:

* All the critical tests exist for gci - [https://k8s-testgrid.appspot.com/google-gci](https://k8s-testgrid.appspot.com/google-gci)

* k8s on GCE is using GCI by default

From my perspective, this issue is completed. Closing it for now.
