### ISSUE TITLE
rest_client_request_status_codes Metrics is recoding a value that is not a code

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#25274]
This is from a production server - not sure how this value got in here, but the rest client looks like it's recording the wrong field (maybe .Status, instead of .Code) in error cases.

```
rest_client_request_status_codes{code="Get https://ip-X-X-X-X.ec2.internal/api/v1/limitranges?resourceVersion=0: dial tcp 172.31.8.245:443: connection refused",host="ip-X-X-X-X.ec2.internal",method="GET"} 6
```

**Comment by timstclair** [comment]
Any idea where this metric is being generated? I can't find the string `rest_client_request_status_codes` anywhere in our code base.

**Comment by timstclair** [comment]
nvm, found it in 1.5, it was renamed in 1.6: https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/client/metrics/prometheus/prometheus.go

Looks like this was fixed in https://github.com/kubernetes/kubernetes/pull/38058
