### ISSUE TITLE
Fix incomplete kubectl bash completion 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25287]
We have bash completion for some `kubectl` commands:
```console
# lists all resources that you can get
$ kubectl get [tab][tab]

# lists all pods that you can get
$ kubectl get pod [tab][tab]
```

but many other commands don't support this (or have limited support)
```console
# gives you nothing 
$ kubectl edit [tab][tab]
```

Ref:

- to enable bash completion http://kubernetes.io/docs/getting-started-guides/gce/#enabling-bash-completion-of-the-kubernetes-command-line-tools 
- cobra docs https://github.com/spf13/cobra/blob/master/bash_completions.md
- https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L32 

@kubernetes/kubectl

**Comment by janetkuo** [comment]
Ref #23801 is moving it to `kubectl completion`

**Comment by xingzhou** [comment]
not sure if this is still valid? if so, I'd like to take investigation of this ticket

**Comment by AdoHe** [comment]
@xingzhou Thanks very much, now I cannot assign this issue to you, but you did own this, just go ahead.
