### ISSUE TITLE
Generation of project_hash in cluster/aws/config-default.sh has problems if you have multiple releases per aws account&user

### ISSUE THREAD

**Issue by dmcnaught** [kubernetes/kubernetes#25289]
When I uploaded a new version for testing (1.2.2), it made it so that bootstrapping the old version would fail (1.2.0) - scaling up the ASG for the minions.
Failure = endless loop:
`== kubernetes-server-linux-amd64.tar.gz corrupted, sha1 0a63308708b67aef20f274a17168848057b49325 doesn't match expected 289db0f893b47fc00461204dcdddef457def08b6 ==
== Hash validation of https://s3.amazonaws.com/kubernetes-staging-6af41275918785086feb8f14d1298807/devel/kubernetes-server-linux-amd64.tar.gz failed. Retrying. ==`

Looking into the code, I see that the hash function for the S3 bucket name is 
`project_hash=$(md5 -q -s "${USER} ${key}")` : https://github.com/kubernetes/kubernetes/commit/e3e6c8377f141ac5ba82c6dc8577db65ffbc2e2d#diff-ca69b7d9d3c476654cc9fef6909b1ff0R219
This will stop an aws user having multiple k8s versions per account (I don't think we want that).

Maybe we can add the k8s version into the hash generation?

**Comment by justinsb** [comment]
Thanks @dmcnaught  - you're right.  But closing as kube-up is in maintenance mode, and this is difficult to fix in a backwards compatible way, so we're unlikely to fix it.  kops, kube-aws or kubeadm are the way forward I think..
