### ISSUE TITLE
Update `kubectl help` descriptions and examples from docs

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25290]
- [ ] Update kubectl commands descriptions to align with descriptions in [kubectl operations table](http://kubernetes.io/docs/user-guide/kubectl-overview/#operations)
- [ ] Add appropriate examples to kubectl commands from [kubectl overview examples](http://kubernetes.io/docs/user-guide/kubectl-overview/#examples-common-operations) and [kubectl cheatsheet](http://kubernetes.io/docs/user-guide/kubectl-cheatsheet/)
- [ ] Change use of `.json` to `.yaml` (see [best practice](http://kubernetes.io/docs/user-guide/config-best-practices/#using-kubectl)) (can be found with `grep -r "json" docs/user-guide/kubectl --include=*.md`)

Ref https://github.com/kubernetes/kubernetes/blob/master/docs/devel/kubectl-conventions.md#documentation-conventions

@kubernetes/kubectl

**Comment by janetkuo** [comment]
@AdoHe do you have time for this one?

**Comment by AdoHe** [comment]
@janetkuo I have put it into my ToDo list, will open a PR asap.

**Comment by janetkuo** [comment]
@AdoHe thanks! Assigning this to you

**Comment by adnavare** [comment]
@janetkuo: Is anyone working on this? I can update this maybe
