### ISSUE TITLE
GKE: Support autoscaling of instances based on HTTP load through L7 ingress

### ISSUE THREAD

**Issue by aknuds1** [kubernetes/kubernetes#25334]
Google Container Engine is supposed to [support autoscaling of instances based on HTTP load](https://cloud.google.com/compute/docs/autoscaler/scaling-cpu-load-balancing#scaling_based_on_https_load_balancing_serving_capacity), but when the L7 ingress is installed, this simply doesn't work (even though the GKE UI won't inform you of it). For reference, see [my SO question](http://stackoverflow.com/questions/37080797/google-container-engine-how-to-auto-scale-an-instance-group-based-on-http-load/37082052#37082052) on the matter.

According to Prashanth B, the reason is that instance autoscaling is not yet implemented for the L7 ingress. Could this please be implemented?

**Comment by chrishiestand** [comment]
Is it possible to scale based on instance cpu usage or another managed instance group metric for your kubernetes nodes? Confusingly there is an "HTTP load balancing usage" option .

![image](https://cloud.githubusercontent.com/assets/100825/16296153/c4edc7c6-38df-11e6-8d82-14f25bb66740.png)
