### ISSUE TITLE
Deployment tests are panic-ing when run with protobufs

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25347]
Example stack:

      Test Panicked
      runtime error: invalid memory address or nil pointer dereference
      /usr/local/go/src/runtime/panic.go:443

      Full Stack Trace
      	/usr/local/go/src/runtime/panic.go:443 +0x4e9
      k8s.io/kubernetes/test/e2e/framework.WaitForDeploymentRevisionAndImage.func1(0x1991f00, 0x0, 0x0)
  	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2585 +0x2f2
      k8s.io/kubernetes/pkg/util/wait.WaitFor(0xc820ac37e0, 0xc820973c00, 0xc8203c0cc0, 0x0, 0x0)
      	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:181 +0x77
      k8s.io/kubernetes/pkg/util/wait.pollInternal(0xc820ac37e0, 0xc820973c00, 0x0, 0x0)
      	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:143 +0x8a
      k8s.io/kubernetes/pkg/util/wait.Poll(0x77359400, 0xdf8475800, 0xc820973c00, 0x0, 0x0)
      	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:137 +0x4f
      k8s.io/kubernetes/test/e2e/framework.WaitForDeploymentRevisionAndImage(0x7f2474238528, 0xc82069d020, 0xc8207142a0, 0x1a, 0x2371ba0, 0x18, 0x2195280, 0x1, 0x23dd2c0, 0x22, ...)
  	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2572 +0x19c
      k8s.io/kubernetes/test/e2e.testRecreateDeployment(0xc8200fedc0)
  	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:390 +0xf8a
      k8s.io/kubernetes/test/e2e.glob.func14.4()
      	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:63 +0x20
      k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc820427920, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
      	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:230 +0x42c
      k8s.io/kubernetes/test/e2e.TestE2E(0xc8200c5cb0)
      	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:30 +0x21
      testing.tRunner(0xc8200c5cb0, 0x328b820)
      	/usr/local/go/src/testing/testing.go:473 +0x98
      created by testing.RunTests
      	/usr/local/go/src/testing/testing.go:582 +0x892

@smarterclayton

**Comment by wojtek-t** [comment]
I'm looking into it now.

**Comment by smarterclayton** [comment]
`deployment.Spec.Template` is nil?  It *could* be that protobuf is detecting all those fields are empty and eliding them, if one particular test managed to get to the server and drop the template filed somehow.

**Comment by wojtek-t** [comment]
In particular, we have 10 test failing with protobufs switched on:

    Summarizing 10 Failures:
    [Panic!] [k8s.io] Deployment [It] deployment should support rollback when there's replica set with no revision 
    [Panic!] [k8s.io] Deployment [It] RollingUpdateDeployment should scale up and down in the right order 
    [Panic!] [k8s.io] Deployment [It] deployment should support rollover 
    [Panic!] [k8s.io] Deployment [It] RollingUpdateDeployment should delete old pods and create new ones 
    [Panic!] [k8s.io] Deployment [It] RecreateDeployment should delete old pods and create new ones 
    [Panic!] [k8s.io] Deployment [It] deployment should create new pods 
    [Panic!] [k8s.io] Deployment [It] deployment should support rollback 
    [Panic!] [k8s.io] Deployment [It] deployment should label adopted RSs and pods 
    [Fail] [k8s.io] Deployment [It] deployment should delete old replica sets 
    [Panic!] [k8s.io] Deployment [It] paused deployment should be ignored by the controller 

    06:43:14 FAIL! -- 160 Passed | 10 Failed | 0 Pending | 122 Skipped 


So maybe this time there is some deployment-specific thing (e.g. generated protobuf schemas for deployements are incorrect? or sth like that) instead of infrastructure-specific one? Just guessing...

[However, not that Job tests are passing, and those are also not part of v1 api, so it's not that all non-v1 API test are failing)

**Comment by smarterclayton** [comment]
It seems unlikely that this is some sort of random corruption in framing (for that many tests to fail).  It seems more likely that somehow deployment fails to decode properly, or is partially encoded by one side.

Validation should reject incoming responses that have the data missing - if we use the CLI to population it would be using JSON and so would come in fine.

**Comment by wojtek-t** [comment]
>
It seems unlikely that this is some sort of random corruption in framing (for that many tests to fail). It seems more likely that somehow deployment fails to decode properly, or is partially encoded by one side.

that's what I meant

>
Validation should reject incoming responses that have the data missing - if we use the CLI to population it would be using JSON and so would come in fine.

Actually, I think that tests are still using JSON (only components are using protobuf - scheduler, kubelet, kube-proxy, controller-manager)

**Comment by wojtek-t** [comment]
I'm trying to switch it on for tests, but it's not done yet:
https://github.com/kubernetes/test-infra/pull/26

**Comment by smarterclayton** [comment]
Oops, that was container that was nil.  same principle though.

**Comment by smarterclayton** [comment]
I can't reproduce anything like this with just serialization / deserialization for Deployments (where containers is empty).

We should add logging to framework/util that if containers is empty, we fetch the latest deployment from the server using JSON and protobuf and then compare them.

**Comment by wojtek-t** [comment]
I did some quick experiment and it seemed to me that the whole deployment was empty (I mean not only container/template, but it also didn't have any metadata like name). Although I may have logged something wrong, because I was rushing...

**Comment by smarterclayton** [comment]
So I have seen cases where the client submits an empty record to the
server.  I haven't seen the server respond with an empty item.  But I bet
the proto decode path has some bugs.

Also, it's possible for a decode to succeed in some cases now when data is
not completely filled out.  If the server returns something mismatched
(maybe a status with kind and apiVersion unset), but deserialize has an
into arg, then it may try to deserialize it and then get no values.  Also,
extensions doesn't set kind or version because of  back compat - we may
actually have a serious problem here being hidden by that.

On Mon, May 9, 2016 at 2:24 PM, Wojciech Tyczynski <notifications@github.com

**Comment by wojtek-t** [comment]
It seems that the problem is not related to Deployment, but to ReplicaSets.
I'm trying to debug it and I'm hopefully getting closer.

**Comment by wojtek-t** [comment]
OK - so I have some finding that is answer for those panics.

So I focused my debugging on "deployment should create new pods" this test (but the problem seem to be similar in all cases).

So the problem is that deploymentutil.GetNewReplicaSet() method is returning nil:
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/deployment/deployment.go#L73

And the problem is that in fact we have a corresponding ReplicaSet, but because of some reason, it has a different "pod-template-hash" label.
E.g. in one example I had:

    Labels:map[string]string{"name":"nginx", "pod-template-hash":"1289224154"}

vs

    Labels:map[string]string{"name":"nginx", "pod-template-hash":"3514667032"}

I still don't understand why it is so.
@nikhiljindal - any hints how this is computed?

**Comment by wojtek-t** [comment]
And note that this test is simple enough, that it has to be the corresponding RS, because there shouldn't be more than 1 (at least initially where it is failing).

**Comment by wojtek-t** [comment]
hmmm.. - something strange is happening here.
I've added some logging in deployment controller logging PodTemplateSpec for which we are computing hash. And here is a log:

    E0510 11:54:36.549456       6 deployment_controller.go:729] QQQ api.PodTemplateSpec{ObjectMeta:api.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(0x2b0e420)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"name":"nginx"}, Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container{api.Container{Name:"nginx", Image:"gcr.io/google_containers/nginx:1.7.9", Command:[]string(nil), Args:[]string(nil), WorkingDir:"", Ports:[]api.ContainerPort(nil), Env:[]api.EnvVar(nil), Resources:api.ResourceRequirements{Limits:api.ResourceList(nil), Requests:api.ResourceList(nil)}, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.Probe)(nil), ReadinessProbe:(*api.Probe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", ImagePullPolicy:"IfNotPresent", SecurityContext:(*api.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc821226420), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc82029efc0), ImagePullSecrets:[]api.LocalObjectReference(nil), Hostname:"", Subdomain:""}}

The problem is that it has CreationTimestamp which is not nil, and I have no idea why...

**Comment by wojtek-t** [comment]
Another portion of finding

The problem seem to be related to timestamps not deployements themself.

It seems we have some problem in marshaling/unmarshaling of unversioned.Time fields.

In particular, adding line

    deployment.Spec.Template.CreationTimestamp = unversioned.Time{}

in deployment controller before computing hashes helps.

**Comment by wojtek-t** [comment]
OK - so I fully understand the problem now.

Basically, roundtrip (with protobuf serializer) on unversioned.Time is not idempotent.
We should fix that

**Comment by wojtek-t** [comment]
@smarterclayton - unfortunately my fix doesn't, but unit test seem to be useful.

Note, that unit test is passing with the fix, but the fix breaks the cluster (it doesn't start with the following error:

    F0510 14:31:16.906620       8 controller.go:86] Unable to perform initial IP allocation check: unable to refresh the service IP block: provided data does not appear to be a protobuf message, expected prefix [107 56 115 0]
)

I'm reassigning this issue to you.

**Comment by smarterclayton** [comment]
Found it - your fix was off because Size() was wrong for 0 values:

```
 // Size implements the protobuf marshalling interface.
-func (m *Time) Size() (n int) { return m.ProtoTime().Size() }
+func (m *Time) Size() (n int) {
+       if m == nil || m.Time.IsZero() {
+               return 0
+       }
+       return m.ProtoTime().Size()
+}
 
 // Reset implements the protobuf marshalling interface.
 func (m *Time) Unmarshal(data []byte) error {
        if len(data) == 0 {
                m.Time = time.Time{}
-       } else {
-               p := Timestamp{}
-               if err := p.Unmarshal(data); err != nil {
-                       return err
-               }
-               m.Time = time.Unix(p.Seconds, int64(p.Nanos)).Local()
+               return nil
+       }
+       p := Timestamp{}
+       if err := p.Unmarshal(data); err != nil {
+               return err
        }
+       m.Time = time.Unix(p.Seconds, int64(p.Nanos)).Local()
        return nil
 }
 
 // Marshal implements the protobuf marshalling interface.
 func (m *Time) Marshal() (data []byte, err error) {
        if m == nil || m.Time.IsZero() {
-               return make([]byte, 0), nil
+               return nil, nil
        }
        return m.ProtoTime().Marshal()
 }
```

**Comment by smarterclayton** [comment]
With that everything starts for me.  It was incredibly hard to find though - I'm going to add a defensive check in serialization for this because this is insanely tough to debug.

**Comment by smarterclayton** [comment]
Defensive check in #25436, but we need to merge your change first in order to to pass.  pkg/api now catches the incorrectly encoded timestamp.

**Comment by wojtek-t** [comment]
@smarterclayton - thanks a lot for debugging it!
I will update my PR in few minutes and also double check that everything works fine.

**Comment by wojtek-t** [comment]
Yeah - it works for me too! - Thanks!
I've updated the PR and will going to self-merge it manually once tests are green to see what other problems do we have.
