### ISSUE TITLE
ThirdPartyResource Watch

### ISSUE THREAD

**Issue by borismattijssen** [kubernetes/kubernetes#25340]
I'm having problems watching my own ThirdParty resource. When I request http://localhost:8080/apis/nerdalize.com/v1alpha1/namespaces/default/workflows?watch=true it works the first time. When a 'workflow' is added the request terminates, although it outputs nothing (blank page in browser). When I request the same URL again, it immediately shows me the blank page.

The two files describing the i) the ThirdPartyResource and the ii) Workflow can be found [here](https://gist.github.com/borismattijssen/111fadce850203ea9b3d66329c382cb9).

Kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.3.176+49bf9d39bc28ce", GitCommit:"49bf9d39bc28ce1c7c1277511ca0498b80128f07", GitTreeState:"clean", BuildDate:"2016-05-03T17:10:02Z", GoVersion:"go1.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.3.176+49bf9d39bc28ce", GitCommit:"49bf9d39bc28ce1c7c1277511ca0498b80128f07", GitTreeState:"clean", BuildDate:"2016-05-03T17:10:02Z", GoVersion:"go1.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by nowprovision** [comment]
I suspect this is due to watch on ThirdPartyResource not returning an resourceVersion as part of the list output. This will confuse the client controllers.

**Comment by nowprovision** [comment]
ListMeta doesn't seem to be populated on ThirdPartyResourceDataList

**Comment by nowprovision** [comment]
I suspect it is because of this
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/thirdpartyresourcedata/codec.go#L381

Im going to have a go at fixing this via a PR, it might not be perfect surely better than string templating and omission of ListMeta for metdata.

**Comment by borismattijssen** [comment]
Great! Good luck with the fix :)

**Comment by nowprovision** [comment]
24963 is a little different, I've created a quick fix for it  at
https://github.com/sitepod/kubernetes/commit/d0e9c029cbe7379f386fc2a6696824df604dfd0d
But will wait on feedback before submitting a PR, seems there might be more to it

**Comment by nikinath** [comment]
I believe this issue can be closed now. Watch is working fine for TPRs.

Create the TPR and the TPR object.

```
# create a tpr
$ cat tpr.yaml
metadata:
  name: workflow.nerdalize.com
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "Adding workflow functionality"
versions:
- name: v1alpha1

# create a tpr object
$ cat workflow.yaml
apiVersion: nerdalize.com/v1alpha1
kind: Workflow
metadata:
  name: test-workflow
spec:
  steps:
  - name: step-a
  - name: step-b
    dependsOn: step-a
```
Check that watch works.

```
# watch using curl
$ curl "http://localhost:8080/apis/nerdalize.com/v1alpha1/namespaces/default/workflows?watch=true"
{"type":"ADDED","object":{"apiVersion":"nerdalize.com/v1alpha1","kind":"Workflow","metadata":{"name":"test-workflow","namespace":"default","selfLink":"/apis/nerdalize.com/v1alpha1/namespaces/default/workflows/test-workflow","uid":"7c9af4fd-1ea4-11e7-9e11-f0761cb232d1","resourceVersion":"12436","creationTimestamp":"2017-04-11T10:49:07Z"},"spec":{"steps":[{"name":"step-a"},{"dependsOn":"step-a","name":"step-b"}]}}}
{"type":"DELETED","object":{"apiVersion":"nerdalize.com/v1alpha1","kind":"Workflow","metadata":{"name":"test-workflow","namespace":"default","selfLink":"/apis/nerdalize.com/v1alpha1/namespaces/default/workflows/test-workflow","uid":"7c9af4fd-1ea4-11e7-9e11-f0761cb232d1","resourceVersion":"15899","creationTimestamp":"2017-04-11T10:49:07Z"},"spec":{"steps":[{"name":"step-a"},{"dependsOn":"step-a","name":"step-b"}]}}}

# watch using kubectl
$ kubectl get workflow -w
NAME            KIND
test-workflow   Workflow.v1alpha1.nerdalize.com
test-workflow   Workflow.v1alpha1.nerdalize.com
```
Also works on browser at: http://localhost:8080/apis/nerdalize.com/v1alpha1/namespaces/default/workflows?watch=true

kubectl version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.1.183+6d7e6c74c933c7-dirty", GitCommit:"6d7e6c74c933c7b7475c9d7f902c468825505a00", GitTreeState:"dirty", BuildDate:"2017-04-11T07:24:17Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.1.183+6d7e6c74c933c7-dirty", GitCommit:"6d7e6c74c933c7b7475c9d7f902c468825505a00", GitTreeState:"dirty", BuildDate:"2017-04-11T07:24:17Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sttts** [comment]
@borismattijssen closing. If you still see this issue, please reopen.
