### ISSUE TITLE
SELinux causing problems when running hack/update-all.sh

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#25343]
This follows #24662 and some recent changes, apparently. Generally when running `hack/update-generated-protobuf.sh` as part of `hack/update-all.sh` some binaries (`cmd/libs/go2idl/go-to-protobuf` `cmd/libs/go2idl/go-to-protobuf/protoc-gen-gogo`) are created while running in docker. Thus resulting in them being created and owned by root. This includes the entire `_output/local/bin` directory. After that the next process (`hack/update-codegen.sh`) can't write to that directory and errors the entire script.

The temporary solution to this problem is:

- run `hack/build-go.sh cmd/libs/go2idl/go-to-protobuf cmd/libs/go2idl/go-to-protobuf/protoc-gen-gogo` before running `hack/update-all.sh`, or
- remove `generated-protobuf` from `hack/update-all.sh` temporarily to run it and run `hack/update-generated-protobuf.sh` manually afterwards.

I'm working on fixing this issue.

**Comment by soltysh** [comment]
Closing since https://github.com/kubernetes/kubernetes/issues/25354 merged.

**Comment by thockin** [comment]
Can we make it policy to ALWAYS run build containers as $(id -u) so we don't have to deal with this?

**Comment by soltysh** [comment]
That was my initial approach, but the builder is already running as root and I had some problems around that. I haven't had enough time to dig deeper. But it might be useful to have such option.

**Comment by soltysh** [comment]
Replying to the other question: yes it's a problem of running a container as root, not a SELinux issue.
