### ISSUE TITLE
Kubectl describe doesn't support json output

### ISSUE THREAD

**Issue by jnardiello** [kubernetes/kubernetes#25353]
I need to programmatically access info contained in `kubectl describe nodes` and for doing so i was expecting `-o=json` to exist. It doesn't seem the case though and it would be really nice to have this feature, also for consistency with `kubectl get`

**Comment by fabioy** [comment]
You can get the json for a single node by specifying its name in `kubectl get`:

`kubectl get node k8s-node-name-here -o=json`

Let me know if you'd like to keep this issue as a feature request for the `describe` command.

**Comment by jnardiello** [comment]
@fabioy Unfortunately the two commands, while similar, contain different information.

See this for more context: https://github.com/kubernetes/kubernetes/issues/25355

I need to access the resources available for each node, that info is not available when using `get node <node-name> -o=json`. So yeah, I really think we should open a feature request for the describe command as well.

**Comment by isubuz** [comment]
I would like to work on this and present a proposal, if that's ok. What is the usual way to announce that I intend to work on an issue?

**Comment by janetkuo** [comment]
@isubuz you may just say so in the issue. However I don't think we should support json output in `describe`. Closing this as a dup of #25355 and we can continue the discussion there.

**Comment by jnardiello** [comment]
@janetkuo why saying so? Doesn't make much sense to me that some of the commands support `json` and other don't. I might be missing the point and would love to hear your point of view.
`describe` has some additional info if compared to `get` which people could need to access programmatically automating their infrastructure.

By saying "we should not support" you are forcing them to rely on parsing the output, which is by no mean reliable as any change would break their implementations.

The reason why I'm asking this here and not on the other referenced issue is that I strongly believe they are highly related but still separate

**Comment by janetkuo** [comment]
I'm saying that because `describe` is more human-readable than machine-readable (script-friendly). If we really want to supporting -o json in `describe` we need some standard scheme that maintains backward comparability. 

Reopen since we don't have an agreement here. Also cc @kubernetes/kubectl

**Comment by smarterclayton** [comment]
I'm fairly concerned about making Describe a structured API that has to have version compatibility.  I do think it's valuable that some elements of it be consumable by machines, but I think that's a much larger discussion and good UX may trump good machine consumption.

**Comment by pracucci** [comment]
I understand each point of view here. As an user, I would need (it's a real need, not just a wish) to get `describe` consumable by APIs, yet I understand it could be quite hide (and maybe limiting) to support its backward compatibility at this stage.

@janetkuo is an harder backward compatibility support the only reason why `describe` currently doesn't support `-o json` or there are other reasons?

**Comment by kargakis** [comment]
I don't think describe ever existed with the intention to make it programatically consumable. Agreed it's a part of a larger discussion and we should definitely provide programmatic access to all info, I am just not sure how to do it or if a simple -o json flag is the solution.

**Comment by derekwaynecarr** [comment]
For context, what info about the node is available in describe that is not
available in get that you are trying to use?  Maybe there is an alternate
operation we can recommend to get the same data set.

**Comment by janetkuo** [comment]
If we want a programmatic way to get, say, allocated resources info from a node, we should probably expose that in node status, and thus that information can be retrieved with `get -o json`.

**Comment by pracucci** [comment]
We currently use `describe nodes` to get info about resources (CPU and memory) allocated and free. It's the bases of our nodes autoscaler. Being able to get such resources with `get -o json` would solve our use case.

@jnardiello can you confirm?

**Comment by pwittrock** [comment]
If your goal is to get specific information from describe that is not available anywhere else, we should open an issue for making it available elsewhere.

**Comment by pwittrock** [comment]
As a work around, would a simpler solution for your use case be doing what the describe does: list all the pods, aggregate them, and compute the resources used for each node?

**Comment by jnardiello** [comment]
Just to confirm, as @pracucci said: we currently use `describe nodes` to extract computed resource as that's the only place where this info is available.

@pwittrock I've already opened this: https://github.com/kubernetes/kubernetes/issues/27404
Which eventually will result in computed resources available in the `get` (and therefore available in `json`).

The work-around you proposed would definitely do the job for us, computed resources is the only info we need in our autoscaling mechanism.

**Comment by pracucci** [comment]
I'm actually not sure if the proposed workaround works on a large scale. We do the check very frequently and calling the `get node` for each single node could take some time.

**Comment by jnardiello** [comment]
To clearify, for our specific use-case issuing a `kubectl get nodes -o=json` and getting back also the computed resources would be enough. The point I was making with this issue is that it doesn't make any sense to me to have a `describe` command which is inconsistent with other commands which on the other hand support `json` output.

I do now get that to programmatically access these info it is recommended to use the API and that `kubectl` was specifically designed to be a human-friendly tool, which in this case I don't understand why the the `get` command supports json output as that is handy only for machines.

**Comment by kargakis** [comment]
> I do now get that to programmatically access these info it is recommended to use the API and that kubectl was specifically designed to be a human-friendly tool, **which in this case I don't understand why the the get command supports json output as that is handy only for machines.**

Note that you need to explicitly ask for json output in `get`. Its default output is human-friendly.

**Comment by jnardiello** [comment]
> Note that you need to explicitly ask for json output in get. Its default output is human-friendly.

Either it's a human-only tool, in which case we are cool, or it's a mix with machine-friendly features (that people will use, default or not), in which case you need to be consistent across all your interfaces imho.
Again, this is out of the scope of our specific needs for which adding the info to the get command would be just fine.

**Comment by smarterclayton** [comment]
It's a human-only tool that enables administrative scripting.  For example:

     kubectl get nodes --template '{{ range .items.status.allocatable }}{{
output CSV style data }}' | tr <cleverness> | <more bash magic>

I think the use case you described is probably achievable through kubectl.
The point is Kubectl doesn't *itself* add new APIs.

**Comment by pwittrock** [comment]
@jnardiello 

>
I do now get that to programmatically access these info it is recommended to use the API and that kubectl was specifically designed to be a human-friendly tool, which in this case I don't understand why json is implemented for the get command.

Json is implemented for the `get` command because the get command returns well defined go objects that are parsed into json objects in the response.

`describe` performs multiple http requests to different apis and aggregates the cross-api data to print a summary for human consumption.  There is no json object that exists for this data since it just just an aggregation of json objects.  The closest thing would be to print all of the json objects that `describe` fetches in order to print the summary, but this would not get you the aggregated results, just the raw data which is already available to.  Manually fetching this data is what I suggested in my work around.  Outputing a json object for the aggregated data would require that we define a json representation for it first, which is not something I think we should do because describe can be very inefficient and manually aggregating the data could be implemented more efficiently for your task.


@pracucci 

>
I'm actually not sure if the proposed workaround works on a large scale. We do the check very frequently and calling the get node for each single node could take some time.

If I recall correctly, `describe` does the same aggregation on the client side that I suggested, except it does it less efficiently by performing redundant lookups when describing multiple nodes.  If necessary I can provide more guidance here.

**Comment by kargakis** [comment]
> kubectl get nodes --template '{{ range .items.status.allocatable }}{{
> output CSV style data }}' | tr <cleverness> | <more bash magic>

It's reasonable to have this as part of the node status, isn't it?

**Comment by pracucci** [comment]
@pwittrock 

> If I recall correctly, describe does the same aggregation on the client side that I suggested, except it does it less efficiently by performing redundant lookups when describing multiple nodes. If necessary I can provide more guidance here.

Your proposed solution looks pretty clear to me and we'll give it a try. Let me just outline that if the resources info will be exported with `get nodes -o json` it will just be much more convenient to be consumed from a bash script, instead of manually iterating over all nodes.

**Comment by liggitt** [comment]
describe includes data from many different objects, each of which has their own API. we don't want to create a meta client-side API for describe.
/close

**Comment by Nowaker** [comment]
I run `kubectl describe pod <pod-name>` to find which node the pod lives on. Having this information outputted as YAML or JSON allows me to get that info easily in an automated manner. Doing so with regular output, I have to deal with grep, awk and splitting hostname from IP, and so on.

It doesn't matter `describe` doesn't return a single object. I'm interested in a JSON/YAML representation of `describe` output, and that's it. For example, it lists pod's labels. Great, let me access that via JSON/YAML too, not just plain text.

Please consider reopening @liggitt because the use case is legitimate. Thanks.

**Comment by liggitt** [comment]
> I run kubectl describe pod <pod-name> to find which node the pod lives on. Having this information outputted as YAML or JSON allows me to get that info easily in an automated manner. Doing so with regular output, I have to deal with grep, awk and splitting hostname from IP, and so on.

`kubectl get pod <name> -o json` (or `-o jsonpath="{.spec.nodeName}"`) is what you want for getting api content

**Comment by Nowaker** [comment]
> It does if it means we have to invent a new API representation for kubectl to output the stitched-together version of those objects

[libxo](https://github.com/Juniper/libxo) is a nice way to do it - popular on FreeBSD. Most userland utilities got JSON/YAML output capabilities because of this. It's like `printf` but preserves context for other formats.
