### ISSUE TITLE
Large clusters fail to start because some system containers are not running.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#25356]
This is causing failures in enormous cluster tests for a past month, and it doesn't get any better. We have to fix it before 1.3, as scaling to 2k Nodes in one of our main goals.

Judging by logs at first Kubelet wasn't able to connect to Docker daemon: 
```
E0509 13:18:46.874917    3373 generic.go:197] GenericPLEG: Unable to retrieve pods: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

After some time it succeeded (I guess):
```
I0509 13:18:51.905148    3373 manager.go:282] Recovery completed
```

Then there's a number of errors:
```
E0509 13:18:56.882828    3373 metadata.go:117] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
E0509 13:18:56.883147    3373 metadata.go:134] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
E0509 13:18:58.420476    3373 pod_workers.go:138] Error syncing pod a88aa0529552d7eb6970b6d9e26ddd4c, skipping: failed to "StartContainer" for "kube-proxy" with ErrImagePull: "Tag 6d4819be8d00b0251cf079f16a2a0db0 not found in repository gcr.io/google_containers/kube-proxy"
E0509 13:18:58.970388    3373 pod_workers.go:138] Error syncing pod a88aa0529552d7eb6970b6d9e26ddd4c, skipping: failed to "StartContainer" for "kube-proxy" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/kube-proxy:6d4819be8d00b0251cf079f16a2a0db0\""
```

Few infos:
```
I0509 13:19:11.925444    3373 container_manager_linux.go:524] Found 44 PIDs in root, 44 of them are not to be moved
```

And then the crashloop: 
```
E0509 13:22:06.861064    3373 pod_workers.go:138] Error syncing pod 4bae25c9-15e8-11e6-9198-42010af00002, skipping: failed to "StartContainer" for "kibana-logging" with CrashLoopBackOff: "Back-off 40s restarting failed container=kibana-logging pod=kibana-logging-v1-gunvo_kube-system(4bae25c9-15e8-11e6-9198-42010af00002)"
I0509 13:22:11.948799    3373 container_manager_linux.go:524] Found 42 PIDs in root, 42 of them are not to be moved
I0509 13:22:18.861384    3373 manager.go:2055] Back-off 40s restarting failed container=kibana-logging pod=kibana-logging-v1-gunvo_kube-system(4bae25c9-15e8-11e6-9198-42010af00002)
```

cc @kubernetes/goog-node @kubernetes/sig-node @zmerlynn @wojtek-t @goltermann

**Comment by gmarek** [comment]
@dchen1107 please delegate.

**Comment by wojtek-t** [comment]
Most of the failures (maybe all of them?) are because of pulling image is hanging forever.

We should introduce a timeout for pulling image - I know that @Random-Liu was working on it at some point? Do we already support it? If not, do we have any ETA for it?

**Comment by Random-Liu** [comment]
@gmarek @wojtek-t Not yet, the PR is pending in the queue now #24918.
If we divide the image pulling process into two steps, the first is creating the connection, and the second is transferring the image. We don't know whether the image pulling is hanging in the first step or the second. **#24918 only added timeout for the first step**.
For the second step, because the transferring time depends on network condition and image size, it is hard to set a fixed timeout for now. The current plan is to expose the image pulling progress to better surface the problem.

**Comment by yujuhong** [comment]
It's a bit unclear to me what pods failed from the log that @gmarek posted.
 - kube-proxy image pulling "failed" with `Tag 6d4819be8d00b0251cf079f16a2a0db0 not found in repository gcr.io/google_containers/kube-proxy`. That seems like a race condition(?) or a registry problem. Did it succeed or in the next try or did it get into a crash loop or hang? 
 - kibana-logging in CrashLoopBackOff doesn't seem related to image pulling at all. Why was the restart necessary?

Maybe more description of the common failure case, with a complete kubelet.log will help.

> Most of the failures (maybe all of them?) are because of pulling image is hanging forever.
> 
> We should introduce a timeout for pulling image - I know that @Random-Liu was working on it at some point? Do we already support it? If not, do we have any ETA for it?

I don't see the clear connection between the log posted above and image pulling hanging. Regardless, @Random-Liu added timeouts for all docker operations in #24918. The PR is waiting for the submit queue to pick up. For image pulling, the PR adds a two minute timeout for the initial request. Once the pulling starts, there is no timeout because image pulling could take arbitrarily long, depending on the image size and the bandwidth.

**Comment by wojtek-t** [comment]
Can we make the timeout of second phase of pulling a configurable parameter? In case of our tests we know what we are pulling and where from, so we may actually set it up for the test purpose (it's good enough for us to make it a kubelet flag or sth like that).

@yujuhong - actually you're right regarding the above log - it has nothing to do with what I wrote.
But I've seen 5+ situations of hanging image pulling in this suite:
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-e2e-gce-scalability/

I see that currently there is also another failure which is:
"network bridge not found"
- see docker logs in:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/7271/artifacts/e2e-scalability-minion-jx4l/?project=kubernetes-jenkins

**Comment by Random-Liu** [comment]
@wojtek-t Make it configurable SGTM. We can set no timeout by default, but for user who knows exactly the upper bound, they can configure the timeout manually. @yujuhong WDYT?

**Comment by yujuhong** [comment]
> I see that currently there is also another failure which is:
> "network bridge not found"

That seems like one of the docker 1.9 network bugs :\
https://github.com/docker/docker/issues/18113#issuecomment-217381910
@dchen1107 added some docker restart logic to handle this, but it's possible that we didn't fix all of them.

@wojtek-t, I think it helps to list problems and file separate issues for them. It's hard to navigate this issue when we are talking about 5 different issues :-)

The image pulling hang is a common problem. Once @Random-Liu's PR landed, we can at least know where the pull request gets stuck.


> @wojtek-t Make it configurable SGTM. We can set no timeout by default, but for user who knows exactly the upper bound, they can configure the timeout manually. @yujuhong WDYT?

SGTM.

**Comment by dchen1107** [comment]
Related to comment at https://github.com/kubernetes/kubernetes/issues/25356#issuecomment-217983358
This is not the same problem. Why docker is not up because kubelet doesn't config cbr0 for it yet. The reason kubelet couldn't configure cbr0 is that kubelet cannot talk to API server, and get PodCIDR from node object. I don't know why Kubelet cannot talk to API server though. 

From Kubelet log, you can see the following error printed out all the time:

```
I0509 19:17:47.193234    3376 kubelet.go:2428] skipping pod synchronization - [ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now container runtime is down]
```

Paralleling docker pulling causes docker hung is a known issue. That is why in the production, Kubelet disables concurrent docker pulling. Unfortunately we have to enable this for testing due to the way our tests are written. 

Also we know there is a gcr repository issue which cause docker pull much longer occasionally. cc/ @mattmoor  gcr expert.

**Comment by yujuhong** [comment]
kubelet recreated cbr0 successfully around 19:17:52, and no cbr0 error appeared after that.
```
I0509 19:17:52.188933    3376 config.go:269] Setting pods for source file
I0509 19:17:52.193398    3376 kubelet.go:2428] skipping pod synchronization - [ConfigureCBR0 requested, but PodCIDR not set. Will not configure CBR0 right now container runtime is down]
I0509 19:17:52.213606    3376 container_bridge.go:77] CBR0 doesn't exist, attempting to create it with range: 10.245.6.1/24
I0509 19:17:52.229104    3376 container_manager_linux.go:524] Found 53 PIDs in root, 53 of them are not to be moved
I0509 19:17:52.235809    3376 container_bridge.go:67] Recreated cbr0 and restarted docker
```
However, docker log was full of network bridge errors till the end:
```
time="2016-05-09T19:38:41.294553305Z" level=info msg="POST /containers/42342a717bdc2e6b8e1750de1f9ced5a8d9a785427b7fb5133ea408432eb1959/start" 
time="2016-05-09T19:38:41.308700879Z" level=error msg="could not find endpoint count key docker/network/v1.0/endpoint_count/8ffa9cb27673bda21b924200942aff17efef17ffbd8300418e874ebff7c4605b/ for network bridge while listing: Key not found in store" 
time="2016-05-09T19:38:41.308799163Z" level=error msg="could not find endpoint count key docker/network/v1.0/endpoint_count/8ffa9cb27673bda21b924200942aff17efef17ffbd8300418e874ebff7c4605b/ for network bridge while listing: Key not found in store" 
time="2016-05-09T19:38:41.309530928Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/42342a717bdc2e6b8e1750de1f9ced5a8d9a785427b7fb5133ea408432eb1959/shm: no such file or directory\nfailed to umount /var/lib/docker/containers/42342a717bdc2e6b8e1750de1f9ced5a8d9a785427b7fb5133ea408432eb1959/mqueue: no such file or directory" 
time="2016-05-09T19:38:41.348314002Z" level=error msg="Handler for POST /containers/42342a717bdc2e6b8e1750de1f9ced5a8d9a785427b7fb5133ea408432eb1959/start returned error: Cannot start container 42342a717bdc2e6b8e1750de1f9ced5a8d9a785427b7fb5133ea408432eb1959: network bridge not found" 
time="2016-05-09T19:38:41.348405118Z" level=error msg="HTTP Error" err="Cannot start container 42342a717bdc2e6b8e1750de1f9ced5a8d9a785427b7fb5133ea408432eb1959: network bridge not found" statusCode=500 
```
@dchen1107 I think this is a legit error.

**Comment by wojtek-t** [comment]
>
@wojtek-t, I think it helps to list problems and file separate issues for them. It's hard to navigate this issue when we are talking about 5 different issues :-)

Sure - sorry for that.

>>
@wojtek-t Make it configurable SGTM. We can set no timeout by default, but for user who knows exactly the upper bound, they can configure the timeout manually. @yujuhong WDYT?
>
SGTM.

Thanks

**Comment by dchen1107** [comment]
Re: https://github.com/kubernetes/kubernetes/issues/25356#issuecomment-218025374

Yes, it is a docker bug found in 1.9 release, and docker claimed it is fixed in 1.10.X.

**Comment by dchen1107** [comment]
Here are the status updates on this P0. There are two main issues included in this one, and both are docker related issues:

1) long docker pull or docker pull hung: In 1.3, Kubelet switches to docker native client library and applies timeout to most of docker operations. https://github.com/kubernetes/kubernetes/issues/23563 For docker pull, we applied timeout for initial request. If the download package part of docker pull takes a long time for our test, we should resolve that issue separately. But today at least, we have the data to monitor that.
2) docker network bridge issue: It is a known issue for docker 1.9.X release. But in 1.3 release, we are going to switch to kubenet (https://github.com/kubernetes/kubernetes/issues/24211). Once that is done, we shouldn't run into this particular problem. 

I am closing this one for now.

**Comment by gmarek** [comment]
I forgot to mention: I was running 2k Node cluster, and some (~80) Nodes failed to start for this reason. After few minutes retry kicked in and I got all 2k Nodes happily running  in time to `validate-cluster` to pass. So - great thanks, it seems to be working. I guess we can even retry a bit sooner.
