### ISSUE TITLE
Kubectl get nodes doesn't include allocated resources info

### ISSUE THREAD

**Issue by jnardiello** [kubernetes/kubernetes#25355]
I'm especially interested in programmatically extracting this bit:
```
Allocated resources:
  (Total limits may be over 100%, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests  CPU Limits      Memory Requests Memory Limits
  ------------  ----------      --------------- -------------
  1770m (88%)   3672m (183%)    1600Mi (42%)    2350Mi (62%)
```

While the information seems to be available via `describe` (which currently doesn't support `json` output), it's not included into `get`.

**Comment by nebril** [comment]
I will try to provide a fix for that. I will try to add the data that's available in `describe` into `get`, as `describe` seems to be purely CLI command.

**Comment by nebril** [comment]
@jnardiello a question: when you get output from
./kubectl get nodes -o json
You have access to `root['items'][0]['status']['capacity']` and `root['items'][0]['status']['allocatable']`. Won't you be able to retrieve the data you need by subtracting allocatable from capacity?

**Comment by jnardiello** [comment]
Yes, what is missing is the critical info about `CPU Requests`, which is by no mean available in the `get`

**Comment by janetkuo** [comment]
@kubernetes/kubectl

**Comment by smarterclayton** [comment]
The output is calculated in a fairly intensive way across multiple APIs.  You're really asking to expose an API that can provide this info, which isn't unreasonable.

**Comment by pwittrock** [comment]
Filed #27404 to track providing the node allocated resource directly through the api

**Comment by jnardiello** [comment]
Thanks @pwittrock
