### ISSUE TITLE
Add `kubectl sh`, an interactive shell 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25385]
`kubectl sh` will list pods/containers to choose from, and then spawn a shell (default `/bin/sh`) into that container (a shortcut for `exec`ing into a container for debugging).

@kubernetes/kubectl

**Comment by smarterclayton** [comment]
We did the simpler "oc rsh" in OpenShift without selection.  I do think selection is useful for many users, but we had started with the assumption that most users would know what pod they were selecting.  We now support "best effort alias" so you can for instance say "oc rsh deployment/foo" and it will pick the oldest pod under the deployment.  That has some nice properties, in that you don't have to get attached to a pod.

@kargakis

**Comment by smarterclayton** [comment]
https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/rsh.go#L16

**Comment by smarterclayton** [comment]
Actually, we haven't added multi resources yet, that's https://github.com/openshift/origin/pull/8279.

If the syntax and behavior makes sense, @kargakis can do the simple port upstream.

**Comment by kargakis** [comment]
We could possibly provide selection as there already is with `kubectl logs -c` but I don't think it offers much value on the pod level.

**Comment by smarterclayton** [comment]
Yeah, the error message should list the containers if you don't specify one
and have multiple - that's enough.

**Comment by kargakis** [comment]
> Yeah, the error message should list the containers if you don't specify one and have multiple - that's enough.

I was talking about something different, disambiguating between pods but it doesn't provide any additional value at all because you can always point to the pod as an argument. We should definitely have `-c` for choosing between multiple containers.

**Comment by wstrange** [comment]
For me this is all about saving keystrokes. I can already kubectl exec with the right arguments to get a shell.

I'd like to see it be super easy  / interactive. I thought of printing a list of pods/containers with a number to choose from- but a grep like pattern with nearest match might also work

**Comment by bgrant0607** [comment]
There are kube-shell and others
