### ISSUE TITLE
Define and document kubectl conventions for users

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25388]
We only have [kubectl conventions for developers](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/kubectl-conventions.md). We should create one for users.

Ref #22569 for documenting kubectl run best practice
Ref http://kubernetes.github.io/docs/user-guide/config-best-practices/

@kubernetes/kubectl

**Comment by bgrant0607** [comment]
Some of the conventions from https://github.com/kubernetes/kubernetes/blob/master/docs/devel/kubectl-conventions.md could be added to the kubectl overview: http://kubernetes.io/docs/user-guide/kubectl-overview/
