### ISSUE TITLE
Pipe-to-sh to install kubectl 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25386]
We should also offer a pipe-to-sh solution for installing kubectl, which includes bash completion. 

@kubernetes/kubectl

**Comment by zhouhaibing089** [comment]
How about providing a docker image which wraps the kubectl?

**Comment by bgrant0607** [comment]
See also #25900

**Comment by rothgar** [comment]
Would this be something that would be part of the existing get.k8s.io script or a separate url? I'm not sure where the main script lives. If someone knows I can work on this.

**Comment by aabed** [comment]
are we looking for something like 
https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get

if so I'd like to work on it

**Comment by bgrant0607** [comment]
I don't think we will do this.
