### ISSUE TITLE
PodAffinity SchedulerPredicates tests are broken.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#25398]
because we turned pod affinity feature off. @davidopp 

@david-mcmahon - this is the thing that's killing serial suite.

**Comment by davidopp** [comment]
I disabled all the pod affinity tests except the ones that were testing validation, because I thought the validation ones should still work, since when we disabled pod affinity, we only disabled the scheduler feature, not the validation. But I must not have checked this test thoroughly. I'm looking into it now.

**Comment by davidopp** [comment]
(I should say: I disabled all the e2e's.)

**Comment by davidopp** [comment]
This problem actually does not have anything to do with making the pod affinity scheduler predicates to not run by default. The problem is that we moved the `pod-with-node-affinity.yaml` and `pod-with-pod-affinity.yaml` files from `docs/user-guide/node-selection/` to `test/e2e/node-selection/`

I would have assumed that the e2e tests would have access to the test/e2e/ directory, but apparently they don't, e.g here is the failure of "Kubernetes e2e suite.[k8s.io] SchedulerPredicates [Serial] validates that embedding the JSON NodeAffinity setting as a string in the annotation value work":

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:729
Expected error:
    <*errors.errorString | 0xc8207c5ac0>: {
        s: "Error running &{/jenkins-master-data/jobs/kubernetes-soak-weekly-deploy-gce/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://199.223.233.210 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-soak-weekly-deploy-gce/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-soak-weekly-deploy-gce/workspace/kubernetes/test/e2e/node-selection/pod-with-node-affinity.yaml --namespace=e2e-tests-sched-pred-56n40] []  <nil>  the path \"/jenkins-master-data/jobs/kubernetes-soak-weekly-deploy-gce/workspace/kubernetes/test/e2e/node-selection/pod-with-node-affinity.yaml\" does not exist\n [] <nil> 0xc820593c40 exit status 1 <nil> true [0xc8202460b0 0xc8202460d8 0xc820246100] [0xc8202460b0 0xc8202460d8 0xc820246100] [0xc8202460c8 0xc8202460e8] [0x9987f0 0x9987f0] 0xc82019b080}:\nCommand stdout:\n\nstderr:\nthe path \"/jenkins-master-data/jobs/kubernetes-soak-weekly-deploy-gce/workspace/kubernetes/test/e2e/node-selection/pod-with-node-affinity.yaml\" does not exist\n\nerror:\nexit status 1\n",
    }
    Error running &{/jenkins-master-data/jobs/kubernetes-soak-weekly-deploy-gce/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://199.223.233.210 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-soak-weekly-deploy-gce/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-soak-weekly-deploy-gce/workspace/kubernetes/test/e2e/node-selection/pod-with-node-affinity.yaml --namespace=e2e-tests-sched-pred-56n40] []  <nil>  the path "/jenkins-master-data/jobs/kubernetes-soak-weekly-deploy-gce/workspace/kubernetes/test/e2e/node-selection/pod-with-node-affinity.yaml" does not exist
     [] <nil> 0xc820593c40 exit status 1 <nil> true [0xc8202460b0 0xc8202460d8 0xc820246100] [0xc8202460b0 0xc8202460d8 0xc820246100] [0xc8202460c8 0xc8202460e8] [0x9987f0 0x9987f0] 0xc82019b080}:
    Command stdout:
    
    stderr:
    the path "/jenkins-master-data/jobs/kubernetes-soak-weekly-deploy-gce/workspace/kubernetes/test/e2e/node-selection/pod-with-node-affinity.yaml" does not exist
    
    error:
    exit status 1
    
not to have occurred
```

@ixdy @spxtr  Any suggestions how to make Jenkins able to access test/e2e/node-selection/ ?

ref/ #23105

**Comment by davidopp** [comment]
cc/ @kevin-wangzefeng

**Comment by davidopp** [comment]
Feel free to disable those two tests temporarily (add [Feature:PodAffinity]) while we figure out how to make this work.

**Comment by david-mcmahon** [comment]
So this is somewhat of an infra issue?  The question is, is it safe to cut an alpha from master with this issue or do we want resolution here first?

**Comment by david-mcmahon** [comment]
cc @fabioy this is killing the kubernetes-e2e-gke-serial tests this week.

**Comment by fabioy** [comment]
Ah, good to know. Thanks for the update.

**Comment by davidopp** [comment]
ref #22985

**Comment by hongchaodeng** [comment]
Can anyone share the logs?
Is it reproducible? I might want to give it a try.

**Comment by davidopp** [comment]
The problem is probably something in the Jenkins configuration, because the failure is that Jenkins can't access test/e2e/node-selection/ directory. So if you want to try to fix it, you need to understand (and be able to modify) the Jenkins configuration.

**Comment by ixdy** [comment]
The e2e projects don't have access to the repo, only `kubernetes.tar.gz` and `kubernetes-test.tar.gz`. Most likely you'll need to add `test/e2e/node-selection` here: https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L130

**Comment by ixdy** [comment]
Alternately, move `node-selection` into `test/e2e/testing-manifests`, which is already included in the test tarball.

**Comment by ixdy** [comment]
cc @jayunit100 cause I think he's been working on this, too.

cc @kubernetes/sig-testing for good measure

**Comment by david-mcmahon** [comment]
Is this what's current killing kubernetes-e2e-gce-serial again?

**Comment by gmarek** [comment]
It seems that we had another regression. I'm not familiar with PodAffinity tests at all, but MaxPods are broken as well. Affinity failure is probably more relevant:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:1283 Expected : jenkins-e2e-minion-group-7xqz to equal : jenkins-e2e-minion-group-t917
```

cc @davidopp

**Comment by davidopp** [comment]
@kevin-wangzefeng

**Comment by davidopp** [comment]
Affinity test only failed once recently (last 10 runs or so). I'm going to mark this as a flake issue.

**Comment by gmarek** [comment]
It fails 1/2 times locally for me. It's a poorly written test, that doesn't clean after itself (I'll send a PR that fixes some of it), but I think it succeeds by chance if pod affinity is disabled in the scheduler.

**Comment by krousey** [comment]
This is also failing in the soak tests that we're investigating in #27374

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-soak-continuous-e2e-gke/7477#k8sio-schedulerpredicates-serial-validates-that-embedding-the-json-nodeaffinity-setting-as-a-string-in-the-annotation-value-work

**Comment by kevin-wangzefeng** [comment]
@krousey the test failing you mentioned is to test nodeAffinity, not podAffinity.
The reason it fail is the node.labels leak during tests which is fixed in #26886.

**Comment by krousey** [comment]
@kevin-wangzefeng Thanks for pointing that out.

**Comment by gmarek** [comment]
It was fixed by something a looong time ago.
