### ISSUE TITLE
Kubernetes HA documentation has image with podmaster

### ISSUE THREAD

**Issue by blerko** [kubernetes/kubernetes#25406]
The current HA documentation shows an image with the podmaster still in place. I believe this is no longer used, so have done a quick edit to remove it. Github doesn't like the svg filetype, happy to send it on by email in that case

**Comment by luxas** [comment]
@mikedanese

**Comment by janetkuo** [comment]
@blerko thanks, please send a PR to fix this document https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/high-availability/index.md

**Comment by blerko** [comment]
Finally got the cla check to pass, hope this is OK:

Modify ha diagrams to remove podmaster #26143

**Comment by bogdando** [comment]
Folks, what could we do to make that a minor doc change to land?

**Comment by takahser** [comment]
The pod master is still on the diagram on the official kubernetes HA docs: https://kubernetes.io/docs/admin/high-availability/

**Comment by arehmandev** [comment]
Yup podmaster still on diagram, had me confused for a second

**Comment by xiangpengzhao** [comment]
The diagram is still not updated....

**Comment by takahser** [comment]
I don't understand why it takes so long to remove an obsolete image from the docs. It's very confusing especially to people who are new to K8. Again, the affected part of the docs is located here: https://kubernetes.io/docs/admin/high-availability/

**Comment by xiangpengzhao** [comment]
/reopen
cc @kubernetes/sig-docs-maintainers
