### ISSUE TITLE
System pods are not starting because they cannot pull image

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25408]
System pods are not starting because they cannot pull image. See e.g. logs:

    I0510 14:44:53.324450    3371 server.go:618] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"fluentd-elasticsearch-e2e-scalability-minion-5448", UID:"aa9cc1b8d68dc2a2ddc284a5380ef29a", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "fluentd-elasticsearch" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/fluentd-elasticsearch:1.15\""

This comes from run:
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-e2e-gce-scalability/7298/consoleFull

The bad kubelet is: e2e-scalability-minion-5448

See: 
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/7298/artifacts/e2e-scalability-minion-5448/?project=kubernetes-jenkins

@yujuhong @kubernetes/sig-node

**Comment by yujuhong** [comment]
```
07:42:49 May 10 07:42:49.216: INFO: At {2016-05-10 07:31:49 -0700 PDT} - event for elasticsearch-logging-v1-z4sxa: {kubelet e2e-scalability-minion-5448} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "elasticsearch-logging" with ErrImagePull: "net/http: request canceled"
07:42:49 
07:42:49 May 10 07:42:49.216: INFO: At {2016-05-10 07:31:49 -0700 PDT} - event for elasticsearch-logging-v1-z4sxa: {kubelet e2e-scalability-minion-5448} Failed: Failed to pull image "gcr.io/google_containers/elasticsearch:1.8": net/http: request canceled
07:42:49 May 10 07:42:49.216: INFO: At {2016-05-10 07:31:49 -0700 PDT} - event for fluentd-elasticsearch-e2e-scalability-minion-5448: {kubelet e2e-scalability-minion-5448} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "fluentd-elasticsearch" with ErrImagePull: "net/http: request canceled"
07:42:49 
07:42:49 May 10 07:42:49.216: INFO: At {2016-05-10 07:31:49 -0700 PDT} - event for fluentd-elasticsearch-e2e-scalability-minion-5448: {kubelet e2e-scalability-minion-5448} Failed: Failed to pull image "gcr.io/google_containers/fluentd-elasticsearch:1.15": net/http: request canceled
07:42:49 May 10 07:42:49.216: INFO: At {2016-05-10 07:31:49 -0700 PDT} - event for l7-lb-controller-v0.6.0-53fmw: {kubelet e2e-scalability-minion-wtsk} Unhealthy: Liveness probe failed: HTTP probe failed with statuscode: 500
07:42:49 May 10 07:42:49.216: INFO: At {2016-05-10 07:31:49 -0700 PDT} - event for monitoring-influxdb-grafana-v3-8gutu: {kubelet e2e-scalability-minion-5448} Pulling: pulling image "gcr.io/google_containers/heapster_influxdb:v0.5"
07:42:49 May 10 07:42:49.216: INFO: At {2016-05-10 07:31:49 -0700 PDT} - event for monitoring-influxdb-grafana-v3-8gutu: {kubelet e2e-scalability-minion-5448} Failed: Failed to pull image "gcr.io/google_containers/heapster_grafana:v2.6.0-2": net/http: request canceled
```

The build in question had the new docker operation timeout added by @Random-Liu. Some image pulls failed with "net/http: request canceled", which indicated that the registry was slow to respond (> 2 minute). 
It could be that the concurrent pulling from 100 nodes overwhelmed the registry, and the e2e-scalability-minion-5448 node was just the unlucky one (?).

@wojtek-t @Random-Liu, how about we bump the timeout to 3 or even 5 minutes? It doesn't address the fundamental problem, whatever it might be, but may stop the build from failing.

**Comment by Random-Liu** [comment]
@wojtek-t @yujuhong If the image pulling timeout, the error should be "operationTimeout: context deadline exceeded".
We never cancel a context on our side, so I guess docker cancel the image pulling from its side. I'll dig into it more soon.

**Comment by yujuhong** [comment]
The pulling failed ~2 minutes after the it started, so it it *might* be related to the new timeout.

**Comment by yujuhong** [comment]
> We never cancel a context on our side, so I guess docker canceled the image pulling from its side because of some reason. I'll dig into it more soon.

Might be related to https://github.com/docker/docker/pull/22445, but I didn't look closely.

It's also suspicious that only one node had this problem.

**Comment by dchen1107** [comment]
dup of #25277

**Comment by kadyogesh** [comment]
Some image pulls failed with "net/http: request canceled"  could someone please help me in fixing it?

**Comment by nmrony** [comment]
@dchen1107, @kadyogesh  I am also facing the same for local registry 
```sh
Failed to pull image "localhost:5000/my-alpine": rpc error: code = 2 desc = net/http: request canceled
Error syncing pod, skipping: failed to "StartContainer" for "local-registry-test" with ErrImagePull: "rpc error: code = 2 desc = net/http: request canceled"
```

**Comment by sam-untapt** [comment]
@nmrony Did you find the root cause? I am seeing the same issue (although I am pulling my image from gcr.io)

**Comment by clairethebear** [comment]
I had also gotten this error. I fixed it by adding the tag at the end of my image path. So when it was failing my deployment.yaml was the following:

containers:                                                                                   
   - name: kubestats                                                                             
    image: gcr.io/[PROJECT-NAME]/kubestats

Then after adding:

containers:                                                                                   
   - name: kubestats                                                                             
   image: gcr.io/[PROJECT-NAME]/kubestats:v1

The container created with no problems after that.

**Comment by minasys** [comment]
I face the same issue too!

**Comment by jerlam06** [comment]
same here!

**Comment by penrique** [comment]
same issue
