### ISSUE TITLE
kubelet with rkt is using wrong network for probing

### ISSUE THREAD

**Issue by pskrzyns** [kubernetes/kubernetes#25404]
When kubelet is running Liveness probe it's using ip from flannel network, i think it should use ip from default-restricted network.

@yifan-gu could you confirm it ?

**Comment by yifan-gu** [comment]
@pskrzyns I think it's the expected behavior. The IP from the flannel network is the IP of the pod. BTW, We will get rid of the default-restricted network after #25062 
After that PR, rkt will be given a network namespace created by kubelet, and will run in `--net=host` in all cases.

**Comment by yifan-gu** [comment]
cc @euank

**Comment by jellonek** [comment]
@yifan-gu in `rkt` we have `default` or `default-restricted` networks for communication between host and pod. There is (or was, because now k8s rkt driver expects this) no requirement for adding host into same flannel network which is used by pods to communicate with each other.

Btw. kvm flavored rkt does not support `--net=host`. Is this "getting rid of the default-restricted" an intentional move to keep kvm flavor out of k8s scope?

Please keep in mind whole perspective and again - please do not rely on internals of particular stage1 flavor (like in cadvisor situation some time ago).

**Comment by yifan-gu** [comment]
cc @dcbw @euank

**Comment by yifan-gu** [comment]
@jellonek No, I am more than eager to have kvm flavor working, that's one of the major priority besides the new container runtime inteface.
Sorry, I am not aware that rkt kvm doesn't support `--net=host`. Do you know if we have a doc in rkt repo that contains a list of what features/flags are not supported by kvm flavor? So we can have a plan on how to deal with this cases. Thank you :)

**Comment by yifan-gu** [comment]
Also cc @jonboulle @philips @alban @iaguis @tmrts

**Comment by jellonek** [comment]
Good question. We don't have such things documented, but mostly you can assume that if there is something other than host networking not working under kvm flavor - it's probably a bug or missing feature, so should be corrected.

**Comment by jellonek** [comment]
To be confirmed: cni flannel plugin (and it's reimplementation in kvm flavored rkt) provides possibility to connect from host to pod public IP given by flannel. This is not working when on same host is started docker, with its bridge device (simple stopping docker should resolve rkt issues with flannel networking).

**Comment by yifan-gu** [comment]
@jellonek I am not worrying docker runs with rkt at the same time. We can assume only one container runtime is running.

Still, it seems that give a network namespace to a rkt pod and let it run with `--net=host` doesn't work well for kvm stage1 /cc @steevj

**Comment by iaguis** [comment]
@steveeJ

**Comment by steveeJ** [comment]
> Still, it seems that give a network namespace to a rkt pod and let it run with --net=host doesn't work well for kvm stage1 /cc @steevj

Do we have an issue for that? Is it any different in k8s than from running rkt manually?

**Comment by jellonek** [comment]
@steveeJ no, we don't have an issue for this and this is same when rkt is started by k8s or manually.

**Comment by steveeJ** [comment]
@pskrzyns Do you still see this as an issue? If so, I think that the setup for this issue is not clearly defined, at least not clear enough for me to fully understand the issue. Would you mind filling in some details to reproduce this?
