### ISSUE TITLE
Credential manager does not normalize :443 or :80 ports before checking secrets

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#25435]
Servers that include the canonical ports are not being properly handled by the credential provider for docker pull secrets.

We should normalize 443 and 80 prior to lookup.

In this case an artifactory server was configured with foo.bar.host.com that redirected to foo.bar.host.com:443 - user was unable to find a match for their secret.

**Comment by liggitt** [comment]
this is an kubelet/image pull issue
@kubernetes/sig-node-bugs

**Comment by smarterclayton** [comment]
I recently did some more security work on this - we can only safely normalize 443 - we should not normalize 80 because you should explicitly indicate you want your secret going over the wire unprotected (same behavior as the daemon)
