### ISSUE TITLE
kubectl: exec errors with a segfault when the kubelet's runtime is rkt

### ISSUE THREAD

**Issue by dgonyeo** [kubernetes/kubernetes#25430]
I spun up a libvirt coreos+k8s cluster that used rkt for its runtime, and `kubectl exec` would error out with a segfault every time it was used, regardless of if the requested binary existed or not.

```
derek@rokot ~/git/kubernetes> kubectl exec frontend-gbecy ls
error: error executing remote command: error executing command in container: signal: segmentation fault (core dumped)
```

The changes that I made to the cloud configs such that it would be a rktnetes cluster are [here](https://github.com/dgonyeo/kubernetes/commit/6af938e72b9bb93224ec2da75dacad234c081c29).

cc @yifan-gu

**Comment by euank** [comment]
I can't trivially reproduce this. Can you verify that you're using a kubectl binary that is compiled from the same codebase? I'm using `./cluster/kubectl.sh -it exec my-single-container-pod echo hi`. Any more information about how to repro would be helpful.

**Comment by euank** [comment]
Per above xref I was able to reproduce it and tracked it down (with @dgonyeo's help) to a bug in rkt. I think we can leave this issue open to track setting a version of rkt without said bug as the recommended version.

**Comment by yifan-gu** [comment]
@euank Are you able to test if the rkt 1.6 fixed this?
