### ISSUE TITLE
Confusing error messages with --enable-debug-handlers=false

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#25448]
I'm not sure what the ideal behaviour is, but at the very least we should give better error messages. Currently the following operations give a variation of a 404:

```
$ kubectl logs --namespace=kube-system kube-scheduler-k8s-stclair-master
Error from server: the server could not find the requested resource ( pods/log kube-scheduler-k8s-stclair-master)

$ kubectl attach --namespace=kube-system kube-scheduler-k8s-stclair-master
error: unable to upgrade connection: 404 page not found

$ kubectl attach -t --namespace=kube-system kube-scheduler-k8s-stclair-master
Unable to use a TTY - container kube-scheduler doesn't allocate one
error: unable to upgrade connection: 404 page not found

$ kubectl exec -i -t --namespace=kube-system kube-scheduler-k8s-stclair-master -- /bin/sh
error: unable to upgrade connection: 404 page not found
```

However, `kubectl get pod` and `kubectl describe pod` _do_ work for the master pods.

This appears to also affect single-node clusters (see http://stackoverflow.com/q/37138714/1837431).

/cc @kubernetes/sig-node @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
Interestingly we already classify these errors, it should be easy to
target specific conditions from pkg/kubectl for better messages
(unless people are wrapping and returning errors, which they generally
should not do).

**Comment by timstclair** [comment]
It looks like these are caused by setting `--enable-debug-handlers=false` (thanks @dchen1107 !). We should still fix the error messages though.
