### ISSUE TITLE
test status links: unsubstituted values

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#25441]
I clicked on a status link of an in-progress build and it sent me to `https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/$%7BghprbPullId%7D/kubernetes-pull-build-test-e2e-gce/$%7BBUILD_NUMBER%7D/`.

Astonishingly, `https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/$%7BghprbPullId%7D/` actually exists, so maybe this is actually a problem?

@ixdy? @fejta?

**Comment by ixdy** [comment]
The plugin is dumb. It posts the link as soon as it queues the job, but the build number hasn't been assigned yet, so it doesn't expand the variable. As soon as the job actually starts, it usually updates the link accordingly.

It looks like there are only three builds under that path. I'm not sure this is worth investigating.
