### ISSUE TITLE
Deprecate pkg/client/unversioned/

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#25442]
Components should be using the generated clientset instead.

Unfortunately, it cannot be removed yet, at least kubectl still relies on it. We should stop people using/updating the package. Maybe adding a deprecation warning message in each file?

@krousey @lavalamp @nikhiljindal @janetkuo @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
We still use this exclusively in Openshift - so we'll need some time
to adapt.  I'm fine with making it clear that implementations should
be moving out to the client set.

**Comment by soltysh** [comment]
@caesarxuchao we've discussed this in https://github.com/kubernetes/kubernetes/pull/27157#issuecomment-233067071 As promised, I'll start working on it, once ScheduledJobs will be in mergable state.

**Comment by caesarxuchao** [comment]
Thank you @soltysh!
