### ISSUE TITLE
Node bringup soak test

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#25445]
For the scalability work, it would be desirable to push node bringup to multiple 9s of reliability. It's honestly not there, given issues like #24295 and #25356. I think things like the Node e2e are a start, but they don't actually cover the on-the-ground bringup.

Proposal: We need a node soak test that's capable of just creating and recreating nodes with an inplace master. We have most of the pieces in place with existing e2es already, but a few pieces might need some work:
- We can start with e.g. a 5 node cluster and scale up / scale down, re-checking cluster state. There's already an e2e that does something close to this, IIRC. We just need to run it in a loop.
- Whenever there's a failure to bring up a node after a specific timeout, we need to log the master state, but we also need to gather logs / serial console on the failed node. I don't think we do this yet.

We really need 5 9's of reliability on node bringup for a 1000 node cluster to get to 99% cluster-up reliability, if we want to remove the slop calculus (which would be nice), and it'll take us basically 6 9's if we want to get to 5000. It'd be really nice to get rid of that slop.

**Comment by zmerlynn** [comment]
cc @roberthbailey @dchen1107 @pwittrock

**Comment by gmarek** [comment]
cc @kubernetes/sig-node @kubernetes/sig-scalability

**Comment by vishh** [comment]
> I think things like the Node e2e are a start, but they don't actually cover the on-the-ground bringup.

@zmerlynn Why do you think the node e2e is not suitable for testing node bring up?

**Comment by zmerlynn** [comment]
Can you describe what the node e2e is doing, then (there ? And can it implement what I described?

Is it really that we need about 10,000 node e2es in parallel to hit green?

**Comment by yujuhong** [comment]
Node e2e creates a single-node cluster with the apiserver and the kubelet on the same machine. It doesn't start any other master component, and also doesn't run add-on pods.
Most of the "node bring-up" problems mentioned in this issue actually manifested via the add-on pods. If the goal is to test node bring-up in the k8s cluster environment, node e2e suite is not  suitable as it is today.

**Comment by zmerlynn** [comment]
That would certainly catch some class of bugs if run enough (and it's not clear we have sufficient runs for the numbers needed), but yes, we would need a real cluster with its normal add-ons to catch some of these. The method I proposed would, I *think*, catch issues in a cheaper way than spinning up 1000 node clusters, though.
