### ISSUE TITLE
Add local/util.sh for local cluster e2e testing

### ISSUE THREAD

**Issue by gouyang** [kubernetes/kubernetes#25452]
If I specify `KUBERNETES_PROVIDER=local` to run e2e testing, an error is happening immediately:

```
2016/05/11 11:00:00 e2e.go:194: Running: get status
/home/kubernetes/hack/e2e-internal/e2e-status.sh: line 30: prepare-e2e: command not found
```

Comparing to other providers, cluster/local/util.sh should be there and include prepare-e2e.

**Comment by mikebrow** [comment]
I had the same fail on the current build and have verified that his stub is needed to run the e2e tests on local.
