### ISSUE TITLE
godeps restore throws error

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#25462]
I'm cloning the latest code and running godeps restore command but hitting with following error:
```
[root@jupiter-vm1181 kubernetes]# godep restore 
godep: Dep (github.com/appc/spec/schema) restored, but was unable to load it with error:
	Package (k8s.io/kubernetes/pkg/api/resource) not found
godep: Error checking some deps.
[root@jupiter-vm1181 kubernetes]#
```

**Comment by thockin** [comment]
godep is finicky.  What version of godep?  What is your `pwd` and GOPATH?
Did you update to head?  Try rm -rf Godeps/_workspace

**Comment by mkumatag** [comment]
My bad.! I followed the steps properly from developer guide and able to proceed further. We can close this ticket.
