### ISSUE TITLE
kubernetes-minion policy to create launch configuration when deploying k8s on aws

### ISSUE THREAD

**Issue by ngtuna** [kubernetes/kubernetes#25476]
Hi,

I reached an issue when deploying k8s on aws in the following guideline: http://kubernetes.io/docs/getting-started-guides/aws/

```
A client error (ValidationError) occurred when calling the CreateLaunchConfiguration operation: You are not authorized to perform this operation.
```

I figured out the `kubernetes-minion-policy.json` does not cover autoscaling:launchconfiguration permission. It should be included, right ?

**Comment by justinsb** [comment]
When did you see this error?  It sounds more like the account under which you were running kube-up does not have permissions to call CreateLaunchConfiguration...

**Comment by ngtuna** [comment]
@justinsb no I have used full administration access account. I figured out that if you deployed success k8s before, then running `kube-down.sh` will not remove `kube-master` & `kube-minion` IAM roles. However, with the new deployment, `kube-up.sh` will generate IAM role with `kubernetes-minion-policy.json` which currently doesn't cover launchconfiguration permission. If I add it, then deployment will be done.

**Comment by justinsb** [comment]
Can you explain how to reproduce the problem?  I regularly kube-up / kube-down / kube-up on the same account (often many times a day!), without problem.

**Comment by ngtuna** [comment]
Could you try: 

- kube-down
- remove `kube-minion` & `kube-master` roles on IAM portal
- kube-up again

**Comment by ngtuna** [comment]
@justinsb I've already made a tiny change locally to make it work. In case you verify the issue, I can make a PR for that.

**Comment by jfkeegan** [comment]
Any chance you could share the change you made, @ngtuna ? I am seeing this same error and can't seem to resolve it...

**Comment by kymy86** [comment]
Hi @jfkeegan, I suggest you to:
- Check the aws instance profiles you've installed on your local machine (`aws iam list-instance-profiles`)
- Remove the kubernetes-minion profile (`aws iam delete-instance-profile --instance-profile-name kubernetes-minion`)
- `kube-down` / `kube-up` again
