### ISSUE TITLE
elazarl/goproxy needs to be updated in godeps

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#25474]
I've seen that while running godep save seen following issue error:

```
[root@jupiter-vm1181 kubernetes]# godep save ./...
godep: Package (code.google.com/p/go-charset/charset) not found
[root@jupiter-vm1181 kubernetes]#
```

Then I tried manually getting that package but hit with following error:

```
[root@jupiter-vm1181 kubernetes]# go get code.google.com/p/go-charset/charset
package code.google.com/p/go-charset/charset: unable to detect version control system for code.google.com/ path
```

Then searched the code repo who is using this package and found to be `github.com/elazarl/goproxy` but if I see a latest code for this project it has been modifed and referring the repo from github.com, so it will be good if we upgrade this package to latest one.

```
[root@jupiter-vm1181 kubernetes]# grep -r code.google.com/p/go-charset/charset *
vendor/github.com/elazarl/goproxy/ext/html/html.go:	"code.google.com/p/go-charset/charset"
[root@jupiter-vm1181 kubernetes]# 
```

**Comment by thockin** [comment]
I don't think you want to `godep save ./...` any more because that includes
vendor, in this case that dep is in a path we don't use so it is not
recursively explored.  I think.  It's hard to tell what godep is actually
doing...

**Comment by mkumatag** [comment]
I've been following the instructions given in [developer guide](https://github.com/kubernetes/kubernetes/blob/def76394572878c72be4c42e583b8ccb0515028c/docs/devel/development.md#using-godep). And the package elazarl/goproxy is old which was referring code from code.google.com. In latest version they are referring to github.com package, so submitted a PR to update the package to latest version. Please look into PR for more information.

**Comment by thockin** [comment]
As far I can tell code.google.com deps are now fixed.

**Comment by mkumatag** [comment]
The recent elazarl/goproxy package is now referring to github package and morever I'm getting following error when I try accessing package from code.google
```
[manjunath@oc1275007250 ~]$ go get code.google.com/p/go-charset/charset
package code.google.com/p/go-charset/charset: unable to detect version control system for code.google.com/ path
[manjunath@oc1275007250 ~]$
```

As we all know code.google.com is no more operating, refer [here](http://google-opensource.blogspot.in/2015/03/farewell-to-google-code.html) for more information.

Keeping all the above points, I prefer to update elazarl/goproxy to the latest level.

**Comment by mkumatag** [comment]
ah.. seems like it got fixed part of https://github.com/kubernetes/kubernetes/commit/c708e2cc8262527b176db007dedbff7680048bbe
