### ISSUE TITLE
Specify NodePort in "kubectl expose" command

### ISSUE THREAD

**Issue by hvalls** [kubernetes/kubernetes#25478]
If `Service` type is `NodePort`, it would be desirable to specify the `nodePort` in command `kubectl expose`. 

Example:
`kubectl expose rc example-rc --type=NodePort --port=9000 --target-port=8080 --node-port=32001`

If you define a `Service` declaratively, in a `yaml` file, you use the field `spec.ports[*].nodePort` to achieve it. But, if it is not possible to create a declarative `Service`, there is not a way to specify the `nodePort`.

**Comment by AdoHe** [comment]
@bgrant0607 wdyt?

**Comment by smarterclayton** [comment]
We've been discussing recently that expose has too many options.  If we have create service, do we need this in expose?

**Comment by thockin** [comment]
I'd much prefer that `create service` be the place where we accumulate
flag-per-field sorts of things.  Expose is supposed to be simple.  That
said, this flag is not egregious to me, since there's ample precedent

**Comment by bigdestroyer** [comment]
I didn't know of the existence of the feature `create service`. So I'm agree with place it in `kubectl create service`.

> I'd much prefer that `create service` be the place where we accumulate
flag-per-field sorts of things.  Expose is supposed to be simple.  That
said, this flag is not egregious to me, since there's ample precedent

**Comment by bgrant0607** [comment]
I'd also like to add `--edit` to expose (and to run, create), which would allow someone to add arbitrary fields that didn't have flags. #18064

**Comment by charpty** [comment]
@hvalls hi, how did you solve this problem?

**Comment by hvalls** [comment]
@charpty Actually, I didn't. I just used the declarative way, automating yml generation.

**Comment by mkasep** [comment]
@hvalls So besides te declarative way, there is no other way to describe a nodeport on a single command?

**Comment by odedpriva** [comment]
you can do something like that 
```
kubectl expose deployment source-ip-app --name=nodeport --port=80 --target-port=8080 --type=NodePort  --overrides '{ "apiVersion": "v1","spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080,"nodePort":30031}]}}'
```

you can also add `--dry-run -o yaml` to check validate the service object that will be created.

**Comment by Sher-Chowdhury** [comment]
Here's how I managed to do it:

```
kubectl create service nodeport myservice --node-port=31000 --tcp=3050:80
```

**Comment by cawoodm** [comment]
> Expose is supposed to be simple.
Expose already offers 2 ports, one of which (port) is superfluous for nodeports since we only care about the nodePort and the targetPort. Adding one more port would really help everyone confronted with the thousands of tutorials using `kubectl expose` which don't mention that you can't specify a nodeport.

**Comment by ultraasi-atanas** [comment]
> > kubectl create service nodeport myservice --node-port=31000 --tcp=3050:80
> 
> This doesn't seem to be well documented. How do you specify which pods you are selecting?

I don't think you do - that's another issue that's documented - https://github.com/kubernetes/kubernetes/issues/46191, as @mmumshad pointed out, this will not use the pods labels as selectors, instead it will assume selectors as app=myservice

**Comment by alkdese** [comment]
> I'd much prefer that `create service` be the place where we accumulate flag-per-field sorts of things. Expose is supposed to be simple. That said, this flag is not egregious to me, since there's ample precedent
> 
> On Wed, May 11, 2016 at 7:17 PM, Clayton Coleman [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > We've been discussing recently that expose has too many options. If we
> > have create service, do we need this in expose?
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > [#25478 (comment)](https://github.com/kubernetes/kubernetes/issues/25478#issuecomment-218642159)

expose already simple and very nice coz I do not need specify selectors it does that for me. But what I do not like is that coz I can't specify nodeport I need to do more jumps review labels and add selector. I wish `--node-port` was there. Do not use if you don't need it

**Comment by carlosjmarin** [comment]
have we added nodeport as an option to expose yet? Seems cumbersome to have to create a service for this declaratively
