### ISSUE TITLE
rkt: Support nvdia GPU resource

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#25494]
Captured from https://github.com/kubernetes/kubernetes/pull/24836#discussion_r62761860

To support GPU resources, we would need:
- Create mount points for those devices with correct file mode, e.g. `crw-rw-----` 
- Sufficient capability support 

cc @euank @sjpotter

**Comment by matchstick** [comment]
@thockin We think there are other ways to support GPUs. Closing for now. We introduce GPU support in 1.3 using other methods.

**Comment by euank** [comment]
Is this the issue you meant to close @matchstick?

If it was, please provide more details about what you mean.

**Comment by thockin** [comment]
This is a really clunky way to do GPUs.  My understanding is we have a
better GPU solution (but I didn't follow the details) @davidopp

**Comment by yifan-gu** [comment]
@thockin We think there are other ways to support GPUs. Closing for now. We introduce GPU support in 1.3 using other methods.

@matchstick Correct me if wrong, but seems you are talking about supporting GPU in general. And this issue is tracking GPU support in rktnetes, so it's slightly different topics?
