### ISSUE TITLE
RunAutoscale code should be refactored into separate method

### ISSUE THREAD

**Issue by metral** [kubernetes/kubernetes#25514]
Per @deads2k's [suggestion](https://github.com/kubernetes/kubernetes/pull/23673#discussion_r58708157), the following [section of code ](https://github.com/kubernetes/kubernetes/pull/23673#discussion_r58708157) in `pkg/kubectl/cmd/autoscale.go` should probably be refactored into a separate method to ease readability & management of the code

**Comment by mwielgus** [comment]
Noone requested/pinged for this for more than a year, closing.
