### ISSUE TITLE
Kubernetes HA documentation doesn't reference --api-servers flag

### ISSUE THREAD

**Issue by blerko** [kubernetes/kubernetes#25529]
Noticed that api-servers in a HA cluster fight and put "Resetting endpoints for master service" in their logs. Need to specify the number of servers with --api-server=x

The kubernetes documentation doesn't reference this in the example yaml file

**Comment by pwittrock** [comment]
@vishh You mentioned you had some bandwidth to help out with docs a bit.

**Comment by matthiasr** [comment]
What does this flag need to be set on? I can't find it referenced in the kube-apiserver or kube-proxy help?

**Comment by matthiasr** [comment]
Is this `--apiserver-count`?
