### ISSUE TITLE
PersistentVolume方式挂载nfs目录，怎么分目录

### ISSUE THREAD

**Issue by DreamLog** [kubernetes/kubernetes#25528]
spec: 
      containers:
        - name: mysql
          image: 172.16.0.24:5000/mysql:5.6.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              # change this
              value: bxn500
          ports:
            - containerPort: 3306
              name: port-mysql
    #         hostPort: 33306
          volumeMounts:
            - name: nfs-bj001
              mountPath: /var/lib/mysql
        - name: bxnpf
          image: 172.16.0.24:5000/bxnpf:6.2.0
          ports:
            - containerPort: 18080
              name: port-bxnpf
    #         hostPort: 30080
          volumeMounts:
            - name: **nfs-bj001**
              mountPath: /usr/bx_app/config
            - name: **nfs-bj001**
              mountPath: /usr/bx_app/f_data
            - name: **nfs-bj001**
              mountPath: /var/log/logs
      volumes:
        - name: nfs-bj001
          persistentVolumeClaim:
            claimName: nfs-bj001
场景：仅挂载一个nfs目录，而一个container挂载多个目录
如何避免不同目录下的文件在nfs服务器上都集中在同一目录下
期望结果：可以分目录存放这些文件

**Comment by thockin** [comment]
Please post questions and support requests on StackOverflow, where they can be found more easily

**Comment by DreamLog** [comment]
@thockin Thank you very much for reminding me. I find that you appeared in many places.
so, I encountered a new issues, can you help me?
That is : I have done all kubernetes DNSservice config,and test it running ok. but how could I reach the pod from serviceName(DNS domain name)? 

```
[root@test-s59tr /]# nslookup bj001
Server:		10.254.0.2
Address:	10.254.0.2#53

Name:	bj001.default.svc.cluster.local
Address: 10.254.54.162
```

above this， dns works ok. but.....
```
[root@test-s59tr /]# curl bj001:18010/sso/login
^C
```

how ever, use IP works.
```
[root@test-s59tr /]# curl 172.17.12.3:18010/sso/login
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>测试学校--登录</title>
```
