### ISSUE TITLE
Propogated errors missing context

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#25521]
## Problem

Our code is riddled with snippets that look like this:

``` go
if err != nil {
  return nil, err
}
```

These lines bubble errors up the call stack until someone decides to log them and move on:

``` go
if err != nil {
  glog.Errorf("Something failed: %v", err)
}
```

Which can yield an unhelpful error message like (fake, but not totally unreasonable):

```
E0426 01:02:59.506727    2740 manager.go:110] Something failed: unexpected EOF
```

And now we're tasked with trying to crawl through the code to figure out where that error actually came from.

We discourage logging an error that's also returned (duplicate log statements interwoven throughout the code can also be confusing), but if you (the person debugging) is lucky someone has attached a unique context message that can help you find the source (e.g. `Operation foo called on pod bar (441234) failed: %v`).
## Assumptions
- Errors are relatively uncommon - i.e. this doesn't apply to "not found" errors that should probably be `bool`s, or errors which can be generated in a tight loop
- Errors are ephemeral - that is, they are handled (e.g. logged) and then discarded (not stored anywhere)
- When an error is produced, it is not always possible to know how it will be handled, or even how severe it is
## Proposal

From the above assumptions, I get 2 guiding principles:
1. If returning an error, it is your job to provide the maximum amount of debugging information and context around that error.
2. If handling an error, it is your job to use the _appropriate_ context for the specific case (e.g. a critical failure should have more detail than something that is expected to occassionally fail and will be retried).

To this end, I'd like to create a kubernetes error package that we promote everywhere. The constructor could look something like (rough sketch, not final API):

``` go
func New(msg string, context ...Context) Error { ... } // Context TBD
func Wrap(msg string, err error, context ...Context) Error { ... }
```

In addition to the provided message, error, and context the constructors could automatically attach additional metadata such as: a full stack trace, timestamp, etc.

We would also provide formatting functions that could flatten the error objects and format them to various levels of detail for logging. Finally, to get the maximum benefit, we would want to discourage the pattern of returning a raw error without first wrapping it with extra context.

For implementation, there are already several projects which provide similar functionality:
- https://github.com/go-errors/errors ([blog](http://blog.bugsnag.com/go-errors))
- https://github.com/hashicorp/errwrap

X-ref: https://github.com/kubernetes/kubernetes/issues/6461, https://github.com/kubernetes/kubernetes/issues/23338 - This proposal is independent of which log library we use, we just need to provide functions to log the appropriate context in whatever format.

/cc @thockin @timothysc @pwittrock @bgrant0607

**Comment by bgrant0607** [comment]
cc @lavalamp

**Comment by thockin** [comment]
+100 I meant to write something about this.

http://dave.cheney.net/paste/gocon-spring-2016.pdf

http://github.com/pkg/errors is my leading contender for error-wrapper.

**Comment by bgrant0607** [comment]
cc @fejta

**Comment by bgrant0607** [comment]
Most stuff the system does is done on behalf of some object: a pod, controller, service, etc. If its group+kind+namespace+name(+uid) were carried as context and added to every log in a consistent format, then it would be easier to filter logs and trace what happened with respect to a particular object.

**Comment by pmorie** [comment]
I'll toss another 100 do-want points in the pot.  I would love to see us build some debugging tooling with this that could make the log filtering dead-simple ('give me logs after X time coordinate for pod Y')

Semi-related, while I am thinking about it: it would be super useful to print the verbose-level of info statements as well for the same type of tooling.

**Comment by thockin** [comment]
Let's not confuddle errors with logs.  We often print errors into the logs,
but they aren't the same thing,.

**Comment by lavalamp** [comment]
Good error handling is hard. I agree that the pkg/errors @thockin linked is a big improvement over fmt.Errorf--I consider that an anti-pattern.

But often it's appropriate to construct errors that are programmatically inspectable (WITHOUT using string parsing), especially if those errors will cross module boundaries. For this reason I think an iron-clad rule is not good. I'd prefer source errors to take the form of `var ( MyErr = errors.New("oops") )` blocks somewhere, or a moral equivalent.

Sometimes it's nice to wrap with context down the stack, but inconsistent usage of the wrapping and unwrapping procedures could actually make things super confusing... (Imagine tracing an error back up a stack and also trying to figure out what go type it was at the same time)

**Comment by timstclair** [comment]
I agree that errors need to be programmatically inspectable (which is why it's important to distinguish errors and logs), but I think that could be accomplished if we enforced a standard error package across the entire project. As the slide deck linked above mentions, most of the uses for inspecting errors I've seen could have been better served using a different signal (e.g. return bool instead of NotFound error). Note that this logic doesn't apply to library code intended to be reused outside of k8s (like the clients), since we cannot expect other projects to agree to our non-standard errors.

pkg/errors looks nice, but as @bgrant0607 mentioned above adding a bit of context in addition to the message could go along way. What about creating a wrapper library around that package which adds the ability to attach arbitrary key:value (`string: interface{}`) pairs? That could also help with the error-inspection (e.g. `if errors.GetString(err, "foo") == "bar"` ...)

**Comment by lavalamp** [comment]
> What about creating a wrapper library around that package which adds the ability to attach arbitrary key:value ...

Maybe I need to see an example, but it seems worse than declaring a custom error type and using type assertion logic to introspect.

**Comment by timothysc** [comment]
You see a lot of this in langs that don't ```throw```, so +1 in general.  

Problem is this is a massive cleanup effort... 
many hands make light work.    

Execution and enforcement are just as important.  Are there any rules based static analysis tools yet for golang?

**Comment by thockin** [comment]
I think we would get a lot of mileage from

1) declaring a standard error-utils package
2) writing down "this is how to handle errors, when to return directly,
when to wrap-and-return, and when to log and discard"
3) converting large swath of code to the new technique

Adding key-value lists and other stuff is secondary, and might make more
sense if/when we have a (related but different) logging overhaul).

I do think that many hands make light work, and if we converted one
substantial package (e.g. kubelet) to use the new style and then declared a
bounty or a fixit or something, we could get a good fraction of the
codebase converted.

**Comment by asalkeld** [comment]
Eventf() should probably also use this package. Actually I wish kubelet logs and events would just merge (so the user could get access to all kubelet logs "kubectl logs mypod" should be able to get the relevant logs from kubelet.log).

**Comment by lavalamp** [comment]
Note that 100% of the discussion above is invalid now that the standard errors package has the concept of wrapping, `Is()`, and `As()`.

**Comment by logicalhan** [comment]
/sig architecture
/cc @johnbelamaric 
(this is kinda a code-arch concern, no?)

**Comment by thockin** [comment]
I'm closing this as absolete and not helpful any more.  We should still handle errors better, but making a blanket bug doesn't really further that, I think.
