### ISSUE TITLE
Build namespace index at API server cache for namespace scoped resource to improve LIST performance

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#25534]
aware of this when do https://github.com/kubernetes/kubernetes/pull/25329 and https://github.com/kubernetes/kubernetes/pull/25342

when client LIST a dir, the API server cache will traverse ALL objects in the store and filter(see [store.list()](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/watch_cache.go#L231) and  [list and filter](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L330-L342) ), which is really expensive.

For namespace scoped resource, I think we could build namespace index for it. It will help a lot when list objects in a namespace. 

@wojtek-t Any ideas?

**Comment by wojtek-t** [comment]
Agree - I was planning to do that, but I won't have time for this before 1.3

**Comment by mqliang** [comment]
@wojtek-t Mind me address this with https://github.com/kubernetes/kubernetes/pull/25342 together? I am working on https://github.com/kubernetes/kubernetes/pull/25342 where I am trying to make the cache return a KeyNotFoundErr when client list from a nonexistent namespace. It's more simple and efficient to judge whether a namespace exist if we have build the index.

**Comment by wojtek-t** [comment]
@mqliang - I would prefer to have them separate; #25342 is a bug fix that we will merge 1.3; index is a feature for which is too late to have it in 1.3

**Comment by mqliang** [comment]
There is two bug in https://github.com/kubernetes/kubernetes/pull/25342 actually:

1) filter function is not strong enough so that a client may get events which it is not interested in
2) list from a nonexistent namespace return an empty list, instead of a KeyNotFoundErr

1) is easy to fix, but 2) is much harder(inefficient) if we don't have index.

**Comment by wojtek-t** [comment]
Can you please fix 1 and 2 in separate PRs?

Regarding 2 - I can imagine just having a list of namespaces cached, or having a full index from namespace to pods (potentially with something else?). The former is pretty simple to do and is fine to do, 2nd is much more complicated and it's too late to do that.
