### ISSUE TITLE
Ingress controller addon not deployed onto HEAD gke clusters

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#25544]
Looks we're not actually creating the l7 addon from yesterday (May 10 night was the last green run). We still create it on gke-1.2 clusters and HEAD/1-2 gce:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-ingress-release-1.2/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-ingress/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-ingress/

@kubernetes/goog-gke I ssh-d into nodes and none of them had the l7 contaienr (docker ps). Maybe we stopped scheduling it because of the recent gci change? or a change to node permissions?

**Comment by jlowdermilk** [comment]
cc @maisem

**Comment by bprashanth** [comment]
Oh this is fixed, I think it was the GCI image issue
