### ISSUE TITLE
Misleading error message when mutating multiple resources without `--all` or label selector

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25541]
When users try to label/annotate multiple resources, we should tell them to add `--all`.

**Current output:**
```
$ kubectl label deployments,rc app=nginx
error: you must provide one or more resources by argument or filename (.json|.yaml|.yml|stdin)
```

**Expected output:**
```
$ kubectl label deployments,rc app=nginx
error: multiple resources were provided, but no label selector or --all flag specified
```

@kubernetes/kubectl

**Comment by janetkuo** [comment]
and `kubectl delete` too

**Comment by smarterclayton** [comment]
Instead of "--all is false", say "multiple resources were provided, but no label selector or --all flag specified"

**Comment by janetkuo** [comment]
Description updated based on suggestion

**Comment by mbohlool** [comment]
I think "resource(s) were provided, but no name, label selector, or --all flag specified" is better. I will send a pull request for this as my first PR.
