### ISSUE TITLE
cadvisor supports rkt runtime

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#25549]
Capturing https://github.com/google/cadvisor/pull/1263#issuecomment-218888039

To make cadvisor support rkt in 1.3, we will need to get https://github.com/google/cadvisor/pull/1263 and another PR (implements a rkt specific watcher) in cadvisor, and bump the cadvisor version.

cc @kubernetes/sig-node @tmrts @philips @jonboulle

**Comment by dchen1107** [comment]
Close this one since cAdvisor is upgraded already. Please re-open it if you disagree.

**Comment by yifan-gu** [comment]
Thank you @dchen1107
