### ISSUE TITLE
kubectl apply cannot delete entry from ObjectMeta.Finalizers

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#25550]
There are system components updating 
ObjectMeta.Finalizers, so it requires the three-way merge feature of the strategic merge patch.

ObjectMeta.Finalizers is a slice of string, but the strategicmerge package doesn't handle the merge patch for a slice of a base type. It only uniqifies the entries in the merged slice, but doesn't support removing an entry.

There are two possible solutions:
1. make ObjectMeta.Finalizers a list of structs;
2. define a strategic merge patch syntax to express the deletion of an entry in a slice of a base type. For example:
supposing originally Object.Fanalizers=["foo","bar"], after applying the patch

```
ObejctMeta
  $patch/finalizers: delete foo
  finalizers:
    - baz
```

It should become ["bar", "baz"]

**Comment by bgrant0607** [comment]
Since `$patch` is currently a directive to the parent, I think the new directive should specify that it applies to a sibling.

I also think we need to move the directive to the key, since the value could be arbitrary (e.g., an integer).

Something like:
```
    $patchDeleteFromSibling=finalizers: foo
```

A slash could work as the separator, also. Or maybe `@`.

**Comment by bgrant0607** [comment]
Another apply-related issue
@apelisse

**Comment by thockin** [comment]
@apelisse should we close this now?

**Comment by apelisse** [comment]
Also to be fair, I think that works now. I've definitely seen people update finalizers with smp.
/close
