### ISSUE TITLE
Services unable to reach themselves in hyperkube (local docker)

### ISSUE THREAD

**Issue by carsonoid** [kubernetes/kubernetes#25555]
So running the simplest example of nginx on hyperkube everything goes well. I can reach nginx from other pods in the cluster and from the host. But when I try to curl the service ip from within the pod itself then I get no response.

The iptables rules below illustrate the problem

```bash
carsonanderson ~ # iptables-save |egrep "10.0.0.25|KUBE-SVC-4N57TFCL4MD7ZTDA|KUBE-SEP-YAIKK2SEJQZ5ZUOS|MARK"
:KUBE-MARK-MASQ - [0:0]
:KUBE-SEP-YAIKK2SEJQZ5ZUOS - [0:0]
:KUBE-SVC-4N57TFCL4MD7ZTDA - [0:0]
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-SEP-YAIKK2SEJQZ5ZUOS -s 172.17.0.2/32 -m comment --comment "default/nginx:" -j KUBE-MARK-MASQ
-A KUBE-SEP-YAIKK2SEJQZ5ZUOS -p tcp -m comment --comment "default/nginx:" -m tcp -j DNAT --to-destination 172.17.0.2:80
-A KUBE-SERVICES -d 10.0.0.25/32 -p tcp -m comment --comment "default/nginx: cluster IP" -m tcp --dport 80 -j KUBE-SVC-4N57TFCL4MD7ZTDA
-A KUBE-SVC-4N57TFCL4MD7ZTDA -m comment --comment "default/nginx:" -j KUBE-SEP-YAIKK2SEJQZ5ZUOS
```

I think it's because we are marking it for masquerade and then sending the traffic out of the network when the source is one of the pods serving a service. 

The  `-A KUBE-SEP-YAIKK2SEJQZ5ZUOS -s 172.17.0.2/32 -m comment --comment "default/nginx:" -j KUBE-MARK-MASQ` line should probably also take into account if the destination is the same as the source and route back into itself directly or jump to the KUBE-SVC-XXX rule instead of hitting the masquerade table and going out to the world.

**Comment by freehan** [comment]
I bet this is a dup of #24350

**Comment by thockin** [comment]
This is an e2e covered feature, so we know it works at least in our "standard" setup.  what cloud are you on, and how did you configure it all?  Did you set the hairpin-mode flag to kubelet?

**Comment by carsonoid** [comment]
I followed the [local setup guide](http://kubernetes.io/docs/getting-started-guides/docker/) exactly. I'm guessing that the issue is indeed a duplicate of #24350 and that I need to run hyperkube with rw access to /sys so that hairpin can work. I'll report back after testing.

**Comment by carsonoid** [comment]
Running with the /sys mount as rw does indeed fix the issue.

**Comment by luxas** [comment]
Okay, let's add `-v /sys:/sys:rw` to the docker guide.
@thockin Does that sound resonable to fix the problem?

**Comment by carsonoid** [comment]
I've already got a PR #506 for this if that's what you want.

**Comment by luxas** [comment]
The PR is merged
