### ISSUE TITLE
NVIDIA GPU: The details needed and risks for NVIDIA GPU workloads, what should be included in kube-scheduler/kubelet?

### ISSUE THREAD

**Issue by Hui-Zhi** [kubernetes/kubernetes#25557]
# What are needed for NVIDIA GPU functionalites in kubernetes,

Below are a few of my opinions, any feedback is welcome:
- CUDA version relative things and version check.
  - Without version check, workloads could be run on different CUDA version randomly, the libs inside different containers could be different, and drivers installed different bare metals also could be different, but 1 CUDA version can't work with all the version of drivers. Volumn mount could be a solution for this, mount different driver/CUDA libs to containers, need to be discussed.
- NVIDIA GPU discovery
  - Need to discovery more details of NVIDIA GPU. kubelet and kube-scheduler need different information, and the NVIDIA gpu information could be found by nvidia-smi or NVML libs:

nvidia-smi http://developer.download.nvidia.com/compute/cuda/6_0/rel/gdk/nvidia-smi.331.38.pdf
 NVML https://developer.nvidia.com/nvidia-management-library-nvml
- NVIDIA GPU information needed by kubelet:
  - For GPU added:
    - must have: /dev/nvidia-uvm, /dev/nvram
    - devices path: /dev/nvidia0, /dev/nvidia1, /dev/nvidia2, etc...
  - For CUDA/driver compatible issue:
    - kube-scheduler should be aware of:
      - GPU vendor: like NVIDIA, Intel...
      - Driver version
      - Number, 
      - Family, 
      - Memory, for future use, (not dedicated).
      - Cores, for future use, (not dedicated).
    - kubelet should be aware of:
      Besides all the information kube-schedule needs, still needs,
      - devices path: like /dev/nvidia0, /dev/nvidia1, etc...
      - ... Others need to be discussed.
- kube-scheduler enhancement for support NVIDIA GPU.
  - NVIDIA GPU needs more information than CPU and memory, so we may need to expend the resource type to make it could be more compatible.

**Comment by Hui-Zhi** [comment]
relative reference:
#19049 #24836 #17035

@therc @erictune @vishh @davidopp the requirements need to be implemented are from my perspective, some features and their details need to be discussed and some of them may not the necessary thing . Also, we need other customers' feedback. Would you mind let me know your feedback first?

**Comment by Hui-Zhi** [comment]
@vishh I think the discovery functionality must be included in Kubelet, and the right way to get it is by NVML, do you think the same?

**Comment by Hui-Zhi** [comment]
There have 2 parts about NVIDIA GPU we need to consider, 

1. NVML libs, this is for NVIDIA GPU management.
2. CUDA libs, this is for the application running inside container.

**Comment by Hui-Zhi** [comment]
@erictune Do you have any comments about this?

**Comment by Hui-Zhi** [comment]
Volume relative: #831

**Comment by Hui-Zhi** [comment]
@vishh the volume mount in kubelet works for NVIDIA GPU, but discovery for GPU still need in kubelet, it could be in kubelet or cadvisor, which one you think is better?

**Comment by vishh** [comment]
Discovery logic should be in kubelet.

**Comment by Hui-Zhi** [comment]
For dedicated GPU, so far I think the Driver version/Family/Memory/Cores, even the NVML is not necessary.

**Comment by timothysc** [comment]
@ConnorDoyle @balajismaniam , could you triage this one?

**Comment by Hui-Zhi** [comment]
@ConnorDoyle <https://github.com/ConnorDoyle> @balajismaniam <https://github.com/balajismaniam> I think for now we add it to Kubelet as a alpha version is good enough, and once we decide to enable more GPU capabilities, and this will need to enable NVML, then we can add it to Cadvisor, do you think the same?


Regards,
Hui-Zhi Zhao
