### ISSUE TITLE
glide dependency flattening

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#25572]
Now that we're using glide / vendoring (hooray - thank you @thockin ), we have a vendor directory.  But I'm hitting a problem using glide myself in a separate project (upup):

1. I'm taking k8s as a dependency (I want the safe format and mount utility)
2. Because we don't have a glide.yaml / glide.lock file, glide does not flatten the dependencies AFAICT.
3. So glog gets defined twice, once because I am using glog, and once in vendor/k8s.io/kubernetes/vendor.  This is the same problem as listed here https://github.com/Masterminds/glide#q-should-i-check-vendor-into-version-control
4. That causes an error because glog's log_dir flag is then defined twice.

I was able to work around this by manually deleting the vendor directory from vendor/k8s.io/kubernetes/vendor.

I think if we checked in the glide.yaml / glide.lock files, glide would detect that k8s is using vendoring and would flatten the dependencies.  At least that is how I read the glide documentation.

I may also not be using glide correctly or be misunderstanding something bigger!

**Comment by justinsb** [comment]
I think the workaround is to do ` glide install --strip-vendor --strip-vcs`, but that give a lot of warnings the second time (for a lot of packages) e.g.

```
[WARN] k8s.io/kubernetes appears to be a vendored package. Unable to set new version. Consider the '--update-vendored' flag.
```

**Comment by ramitsurana** [comment]
I don't know if this may help you or not.But I think @justinsb that maybe glide has some unresolved issues.This is a conversation on using glide on minikube https://github.com/kubernetes/minikube/pull/71 .Although currently I fail to understand why kubernetes is using godeps if they have glide installed and working in place ? This is just a suggestion,I maybe wrong about this.

**Comment by thockin** [comment]
Kubernetes is NOT using glide yet.  We filed a number of bugs with glide, and are waiting for them.  They seemed like smallish bugs, but the glide folks have a more general solution they want to use, which has left us waiting.

@mattfarina is there no shorter path? I filed my issues literally 3 months ago.

Anyway, I am going to close this since I think it was based on the mistaken belief that we had achieved glide.  We haven't.

**Comment by ramitsurana** [comment]
Cool.Thanks @thockin for the clarification.Hopefully glide guys could fix those issues asap.It would be interesting to watch out for the kubernetes advancement with the upcoming glide features.Hey @thockin just a quick question out of the box,Any plans on using https://github.com/coreos/torus or https://github.com/emccode/rexray for any future kubernetes releases ?

**Comment by thockin** [comment]
Wrt torus and rexray, we have not investigated using them directly as part
of the system.  Concrete ideas on how to leverage new tech into better
solutions are ALWAYS welcome, though.

**Comment by atombender** [comment]
@thockin: Does this bug have a corresponding issue filed in the Glide repo that I can track? I'm trying to write an app that uses the Kubernetes client, and my app is using Glide, and so of course I ran into this issue right away.

FWIW, Glide has a lot of bugs, and not a lot of development activity, but is still the best vendoring solution available to us.

**Comment by timoreimann** [comment]
@atombender Listing the [issues created by Tim](https://github.com/Masterminds/glide/issues/created_by/thockin) is probably a good start.

FWIW, the glide upstream issues shouldn't be a blocker to vendoring Kubernetes in your application. At least, it wasn't for me when I vendored Kubernetes 1.2.5 for [my Kube example application](https://github.com/timoreimann/kubernetes-goclient-example).
