### ISSUE TITLE
Bug in Go client example documentation

### ISSUE THREAD

**Issue by girishkalele** [kubernetes/kubernetes#25578]
pkg/client/unversioned/doc.go

Example to list pods fails to compile -

pods, err := client.Pods(api.NamespaceDefault).List(labels.Everything(), fields.Everything())

should be

everythingSelector := api.ListOptions{LabelSelector: labels.Everything(), FieldSelector: fields.Everything()}
pods, err := client.Pods(api.NamespaceDefault).List(everythingSelector)

**Comment by jayunit100** [comment]
Good catch ; and This should maybe live in something like `TestExampleGoClient` , so that it runs as part of the unit tests, right?

**Comment by girishkalele** [comment]
This was in the comments for godoc to pick up and publish in the online docs - ideally, we would want to make this a TestExampleGoClient and run unit tests on it, which still retaining the ability for GoDoc generation to pick it up, but I am not sure how we go about it.

**Comment by girishkalele** [comment]
Looks like @errordeveloper fixed this today.

Pull Request: https://github.com/kubernetes/kubernetes/pull/25661
