### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#25588]
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/releasing.md

`[Jenkins](http://go/k8s-test/)` Link goes to nowhere land. ... Line 85

**Comment by janetkuo** [comment]
Hmm it's actually a Google internal link. cc @ihmccreery who authored this line.

**Comment by chrislovecnm** [comment]
While he is at it would be awesome for him document how to run a local release w/o uploading it to Google Storage. Took me awhile to hunt for the GCE variable ;) Not at my computer or I would list the var.

**Comment by ihmccreery** [comment]
Please file a separate issue for running a local release without uploading.
