### ISSUE TITLE
createdBy annotation has wrong apiVersion

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#25582]
My cluster is version 1.2.4.
I have this pods object created just now, by my Job object.
The annotation key `kubernetes.io/created-by` has the value:

``` json
{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"Job","namespace":"default","name":"pi","uid":"5ef034e0-1890-11e6-8935-42010af0003e","apiVersion":"extensions","resourceVersion":"427339"}}
```

The problem is that `apiVersion` is just `extensions`, not `extensions/v1beta1`, or `batch/v1`, as I might have expected.

**Comment by xiangpengzhao** [comment]
@erictune createdBy annotation has been deprecated (#44407), so I think this issue is no longer relevant. I'm going to close it. Feel free to correct me if I'm wrong :)
