### ISSUE TITLE
rkt: Measure the performance for rktnetes

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#25581]
As an important aspect of the rktnetes 1.0, we want to give users some data on how the rktnetes performs today in terms of:
- [x] Pod resource overhead
  - CPU, memory usage (https://github.com/coreos/rkt/pull/2520)
  - It's almost there, we might need to do the benchmark for a longer period (>> 10s).
- [x] Pod launch latency
  - From kubelet receives the pod spec to when the pod is running.
  - Run the e2e density test. [Desity test result](https://console.cloud.google.com/storage/browser/rktnetes-benchmark)
- [x] Node CPU usage
  - For given number of pods running on a host (e.g. 30, 50, 100)
  - [Result and comparison with Docker](https://docs.google.com/spreadsheets/d/1lcmajSnR6suev9K75O_w0sKLGSF0gVc5ueTLZGzt5dY/edit?usp=sharing)

cc @kubernetes/sig-node @philips @jonboulle @tmrts

**Comment by yujuhong** [comment]
> rkt/kubelet average CPU / memory usage
> For given number of pods running on a host (e.g. 10, 50, 100, 200, ...)

How are you going to measure the cpu/memory usage for rkt? Is that just going to be the metadata server?

**Comment by yifan-gu** [comment]
@yujuhong Yes. the rkt api serice

**Comment by yifan-gu** [comment]
@yujuhong Do you know if we have any e2e tests for such things already? I found the density test might be helpful.

**Comment by yujuhong** [comment]
> @yujuhong Do you know if we have any e2e tests for such things already? I found the density test might be helpful.

Yes, density test tracks the pod startup latency and breaks it down into different segments (e.g., scheduling time). Overall, the pod startup time from create to running should be < 5s to meet the SLo.

For resource usage tracking of kubelet and rkt, we have the resource usage tracking test, which you already know. The relies on the "runtime" resource usage reported by the cadvisor, and I don't think rkt api service is reported as "runtime". For the latest numbers using docker, see http://perf-dash.k8s.io/ and select "Kubelet perf 100" (for 100 pods) in the drop down menu.

**Comment by yifan-gu** [comment]
Not able to run the kubelet-perf test as for #https://github.com/kubernetes/kubernetes/issues/25928. So I am going to use https://github.com/coreos/rkt/pull/2324 to record the avg CPU/memory for kubelet and rkt api service.

**Comment by dchen1107** [comment]
I marked the priority as P2, and we can document & release what we have so far for 1.3 release. Keeping improve over releases. cc/ @philips

**Comment by yifan-gu** [comment]
I am getting back to this. Will try to have some results for the CPU/memory average usage soon.
Besides, another thing I want to get from this is to investigate why the startup time is slower than docker.

**Comment by yifan-gu** [comment]
Uploaded a spreadsheet that has the throughput / latency / CPU usage for rkt and docker runtime. 
https://docs.google.com/spreadsheets/d/1lcmajSnR6suev9K75O_w0sKLGSF0gVc5ueTLZGzt5dY/edit?usp=sharing

cc @euank

**Comment by euank** [comment]
Great work @yifan-gu! It's nice to know where we stand and have a baseline to improve from

**Comment by yifan-gu** [comment]
Captured from https://github.com/kubernetes/kubernetes/pull/27220#issuecomment-226606342
I found that if we omit the `stage1-image` flag, then we could have a big performance boost as we won't need to unpack the stage1 image each time for every pod.

I updated the kubelet's flag in that PR to include the change, will run the benchmark again and put some new result.

**Comment by yifan-gu** [comment]
@dchen1107 @yujuhong Do we want to expose the result somewhere?

**Comment by yujuhong** [comment]
We are still working on a node performance benchmark, and haven't established the practices for publishing the numbers (even for docker) yet. Maybe you could post the key numbers in this issue (with details of the setup) just for the reference?

**Comment by yifan-gu** [comment]
@yujuhong Gotcha.

The result I got recently: 
https://docs.google.com/spreadsheets/d/1lcmajSnR6suev9K75O_w0sKLGSF0gVc5ueTLZGzt5dY/edit?usp=sharing

Test environment: rkt 1.8.0 / docker 1.10 / kubernetes 1.3 / coreos-alpha-1032-0-0-v20160428 / n1-standard-2 on GCE, running e2e/density.go

**Comment by pskrzyns** [comment]
cc @pskrzyns

**Comment by tmrts** [comment]
@yifan-gu is this issue now resolved or needs to be updated with the latest rkt version?

**Comment by yifan-gu** [comment]
@tmrts We probably need to update the result with the new rktlet now. cc @euank
