### ISSUE TITLE
Surface kubectl clusters in kubectl help when talking to federation apiserver

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#25592]
From https://github.com/kubernetes/kubernetes/pull/24016#issuecomment-218585269:

> We also want kubectl get clusters to come up in kubectl help, but it should only show up when kubectl is talking to a federation apiserver.
> We can do that by configuring the output based on discovery API from apiserver rather than being a hardcoded list in kubectl.

Will be great to have this. Not critical for 1.3

Ref https://github.com/kubernetes/kubernetes/issues/23653

cc @jianhuiz @kubernetes/sig-cluster-federation

**Comment by pwittrock** [comment]
@jianhuiz Should this issue be closed now?

**Comment by nikhiljindal** [comment]
No this is not fixed yet.
The referenced PR added `kubectl get clusters` command. We still need to surface it in `kubectl help`

**Comment by nikhiljindal** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/31719 to include clusters in the list of resources printed by kubectl help. This is a short term fix.

The longer term correct fix is to replace the hard coded list by discovery list.

**Comment by dims** [comment]
switching this to 1.6 as it's too late for 1.5. ok? (please switch it right back if you disagree)

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by shiywang** [comment]
hi @nikhiljindal 

> The longer term correct fix is to replace the hard coded list by discovery list.

I'm working on this [TODO](https://github.com/kubernetes/kubernetes/blob/b776df8a20444568614804791d24e64cc3fee0be/pkg/kubectl/cmd/cmd.go#L201), and pr here: https://github.com/kubernetes/kubernetes/pull/51324 

> Another way to implement this is to have a way for kubectl to detect that it is talking to federation apiserver (using discovery api) and then always use the federation clientset and FederationDescriber.

I will add a detect function which return a value like `isFedrationCluster` with discoveryClient, if `isFedrationCluster == true` will always use the federation clientset and FederationDescriber in anonther pr, it this what you want ?

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#43.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
