### ISSUE TITLE
Add Ready replica count to DaemonsetStatus

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#25605]
Readiness is as relevant to daemonsets as deployments, but while DeploymentStatus has "AvailableReplicas" i.e. the number of pods ready for at least minReadySeconds, DaemonsetStatus does not have an equivalent count of replicas that are healthy/ready. Not only can services point at daemonset pods, making readiness relevant, but readiness can also be used to indicate general health. I suggest adding "readyReplicas" to DaemonsetStatus.

The main use case should be for kubectl, but I also would like to add a metric to [kubernetes/kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/) reflecting ready replicas of a daemonset, as it exists for deployments.

**Comment by jayunit100** [comment]
-  should we  evaluate all the semantics of a deployment and ask what is in common w/ DaemonSetStatus? 
- is a daemonset just a specialized case of a deployment, and thus, should it reuse the deployment status parameters ?  
There may be some ignorance in my comments here, I'm still trying to wrap my head around the differences between daemonsets vs deployments.

**Comment by pwittrock** [comment]
cc @pwittrock

**Comment by ghodss** [comment]
@bgrant0607 If we add ready counts to services, we should add them to daemonsets as well as per this issue.

**Comment by ghodss** [comment]
@jayunit100 I think daemonsets and deployments are different enough that we can consider adding fields to DaemonsetStatus on a case-by-case basis.

**Comment by bgrant0607** [comment]
And RC/RS, PetSet, probably even Job.
https://github.com/kubernetes/kubernetes/pull/29481#issuecomment-235628491

**Comment by bgrant0607** [comment]
ref #7483
