### ISSUE TITLE
Support for live migration scenario

### ISSUE THREAD

**Issue by newtack** [kubernetes/kubernetes#25603]
I have a partitioned in-memory custom database with let's say 2 partitions dealing with separate accounts (multi-tenant database). I want only 2 instances running on my cluster. When a new version of my custom database is released I'd like to spin off 2 new instances of the new version, transfer the state from the old database to the new one (this would be handled by the database itself) and when completed want to shut down the old instances. In the transition period all requests are received by the initial two instances, once everything is transferred from the "old" instances to the new ones, I want new requests to go to the new server instances and shut down the old server instances.

Can this be done today with Kubernetes? If so, how? If not, any plans for it going forward? 

The in-memory DB would have snapshots and transactions stored in the cloud, so there is no need for local disk, but the live upgrade is a requirement and I'd love to do it with Kubernetes.

**Comment by jlowdermilk** [comment]
Since your db is in-memory, you can probably accomplish this by running it in a [deployment](http://kubernetes.io/docs/user-guide/deployments/) and writing a [job](http://kubernetes.io/docs/user-guide/jobs/) that creates the new deployment, triggers the migration, and then spins down the old deployment.

**Comment by jlowdermilk** [comment]
A nicer way to accomplish this sort of custom flow would be to use an init container (see #23666 for proposal), which is being implemented fairly soon. That would potentially let you use deployment's update, but the standard rolling-update flow is spin up new pod/wait for running/spin down old pod/repeat. You may still be better off writing a job to manage your custom upgrade scenario.

**Comment by pwittrock** [comment]
@bprashanth Anything like this in PetSets?

**Comment by resouer** [comment]
@newtack Real live migration is heavily related to the underlying container runtime, I suggest you to keep eye open on [Hyper](http://hypercontainer.io/) integration work with Kubernetes, and also: #/25899

**Comment by bgrant0607** [comment]
see also #3949

**Comment by bgrant0607** [comment]
Closing in favor of #3949.
