### ISSUE TITLE
Delete cluster from kubectl config

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#25601]
I know `gcloud container clusters` will get the credentials of a cluster and `kubectl config view clustes` will show those credentials. How do I do the opposite? (remove a cluster from what kubectl shows me). 

I have lots of random clusters that are long dead in my kubeconfig. I tried some obvious things with no luck:

```
$ kubectl config delete
Usage:
  kubectl config SUBCOMMAND [flags]
  kubectl config [command]

Available Commands:
  view            Displays merged kubeconfig settings or a specified kubeconfig file.
  set-cluster     Sets a cluster entry in kubeconfig
  set-credentials Sets a user entry in kubeconfig
  set-context     Sets a context entry in kubeconfig
  set             Sets an individual value in a kubeconfig file
  unset           Unsets an individual value in a kubeconfig file
  current-context Displays the current-context
  use-context     Sets the current-context in a kubeconfig file

$ gcloud container clusters delete gke_kubernetesdev_us-central1-b_cluster-1
The following clusters will be deleted.
 - [gke_kubernetesdev_us-central1-b_cluster-1] in [us-central1-b]

Do you want to continue (Y/n)?  y

ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
 - ResponseError: code=404, message=The resource "projects/kubernetesdev/zones/us-central1-b/clusters/gke_kubernetesdev_us-central1-b_cluster-1" was not found.
No cluster named 'gke_kubernetesdev_us-central1-b_cluster-1' in kubernetesdev.

$ kubectl config view | grep gke_kubernetesdev_us-central1-b_cluster-1
  name: gke_kubernetesdev_us-central1-b_cluster-1

$ gcloud container clusters list 
NAME  ZONE  MASTER_VERSION  MASTER_IP  MACHINE_TYPE  NODE_VERSION  NUM_NODES  STATUS
Listed 0 items.

```

Is there an alternative to opening kubeconfig and deleting by hand? This combined with https://github.com/kubernetes/kubernetes/issues/20374 will make the cluster swapping operations more friendly IMO

@kubernetes/kubectl

**Comment by deads2k** [comment]
`kubectl config unset clusters.gke_kubernetesdev_us-central1-b_cluster-1`.

**Comment by ProProgrammer** [comment]
So to remove all entries for a stale cluster config (i.e. config for a cluster that no longer exists/or you want to use), we should do `kubectl config unset clusters.<cluster_name> && kubectl config unset users.<cluster_name>` individually for each cluster?
I removed the contexts using `kubectl config delete-context <cluster_name>`. Should we have that also delete the corresponding entries from `clusters` and `users` section of kubeconfig file?
