### ISSUE TITLE
kube-controller-manager ties node CIDR allocation with cloud route provisioning

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#25602]
kube-controller-manager currently has one flag, allocate-node-cidrs, which turns on two controllers:

1. A controller which assigns a CIDR to every node created
1. A controller which configures cloud routes for those nodes (on clouds that support this)

However I would like to do the CIDR allocation, without setting up the cloud routes.  In particular, AWS has a 50 node limit for cloud routes, so in order to support bigger clusters, I'm pondering setting up a simple complete graph of GRE tunnels between nodes, using a simple controller on each node that watches the nodes and sets up the tunnels.

One way to separate the two controllers would be to add a flag which turns off cloud route management, but defaults to true.  It would only come in to play when allocate-node-cidrs=true; then setting manage-cloud-routes=false would allow for kube-controller-manager to set podCIDR on nodes, but would not ask the cloud provider configure the routes.

```
fs.BoolVar(&s.ManageCloudRoutes, "manage-cloud-routes", true, "Should routes for Pod CIDRs be configured on the cloud provider.")
```

cc @thockin

**Comment by justinsb** [comment]
Proposed #25614 - I used "configure-cloud-routes" there as the option name but happy to change.

**Comment by aarondav** [comment]
Out of curiosity, what is the use-case resolved by `allocate-node-cidrs=true` and `configure-cloud-rotes=false` which is not satisfied by a networking overlay such as flannel? It sounds like you want to build your own network overlay using GRE tunnels.

**Comment by justinsb** [comment]
@aarondav this is so that a network overlay (like flannel) can use the k8s API as a source of truth.  And then, yes, I did build a simple network overlay using GRE tunnels https://github.com/kopeio/kope-routing/tree/master/pkg/routecontroller/routingproviders

**Comment by aarondav** [comment]
Got it, thanks, that's very interesting. It implies that flannel could operate in a read-only mode from the API server, without direct access to an etcd.
