### ISSUE TITLE
[AWS] Repeated DescribeInstances calls when KCM restarts

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#25610]
On AWS, whenever the set of nodes changes, or when controller-manager is restarted, controller-manager calls DescribeInstances once for *every* service to get detailed information about the nodes. This, together with other AWS API calls, causes the AWS API request limit to be hit when you have enough services.

The call chain is

nodeSyncLoop --->
updateLoadBalancerHosts --->
(for each service) lockedUpdateLoadBalancerHosts --->
s.balancer.UpdateLoadBalancer --->
s.getInstancesByNodeNames

**Comment by justinsb** [comment]
Going to try to fix this in 1.3, but I don't know if we'll make it...

**Comment by therc** [comment]
If you're not going to look at this by Monday, I can give it a shot.
