### ISSUE TITLE
kubectl get not recommending petset

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#25615]
I am running the latest code off of masters which should include some of the petset functionality that is slated for 1.3.  The recommendation for petset is not showing.  Is the recommend hidden??  I noticed that executing:

```command
$ kubectl get
bunch of lines redacted
   * pods (aka 'po')
   * persistentvolumes (aka 'pv')
   * persistentvolumeclaims (aka 'pvc')
   * quota
   * resourcequotas (aka 'quota')
   * replicasets (aka 'rs')
   * replicationcontrollers (aka 'rc')
   * secrets
   * serviceaccounts (aka 'sa')
   * services (aka 'svc')
error: Required resource not specified.
See 'kubectl get -h' for help and examples.
```
Does not include:
```
  * petset
```

The command is in the source because:

```command
bash-3.2$ kubectl get petset
bash-3.2$
```

Does not throw an error.

**Comment by bprashanth** [comment]
Yeah kubectl understands petset, just doesn't know how to recommend it

**Comment by kargakis** [comment]
This list should be dynamically populated

**Comment by chrislovecnm** [comment]
Can we get a `pet` abbreviation as well??

**Comment by nhlfr** [comment]
@kargakis it's not that automatically pupulated, please see my pull request.
@chrislovecnm `pet` subcommand isn't working for me yet. Am I missing something?

**Comment by kargakis** [comment]
> @kargakis it's not that automatically populated, please see my pull request.

It is not currently, it "should be".

**Comment by bgrant0607** [comment]
PetSet is alpha and isn't enabled by default. Listing it unconditionally will generate confusion among users unable to use it. If we add it to the static list, it needs a caveat.

cc @kubernetes/kubectl

**Comment by chrislovecnm** [comment]
@nhlfr you going to merge that into HEAD?
