### ISSUE TITLE
Example in "kubernetes 101" does not work.

### ISSUE THREAD

**Issue by mrhwick** [kubernetes/kubernetes#25620]
I have tried to follow the (extremely) brief example described in the below docs:
http://kubernetes.io/docs/user-guide/walkthrough/#pod-management

When I get to the step where we use a simple curl to the pod, the example stops working:

```bash
╰─$ curl http://$(kubectl get pod nginx -o go-template={{.status.podIP}})
curl: (7) Failed to connect to 10.60.0.4 port 80: Operation timed out
```

If I am doing something wrong to cause the issue, then I apologize for complaining. I just ran the tutorial on a fresh set up, and encountered issues.

**Comment by isubuz** [comment]
As the documentation says, the pod IPs aren't externally available for most providers. I suppose you are running the curl from your local machine?

**Comment by mrhwick** [comment]
Looks like the documentation has changed since I filed this issue, as the command I provided was taken directly from the documentation and it no longer provided there.

**Comment by isubuz** [comment]
Seems like it. So maybe we can close this one.
