### ISSUE TITLE
jenkins node e2e failed without any log

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#25621]
A latest result of node e2e in #25415 showed failure with links to log:

https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/25415/node-pull-build-e2e-test/5947/build-log.txt

It only shows "not found"..

**Comment by fejta** [comment]
Can we make this point to gubernator?

**Comment by fejta** [comment]
@rmmh please talk to @thockin about moving pr-

For example from https://github.com/kubernetes/kubernetes/pull/26916 

GCE e2e build/test **failed** for commit 422fc018c3646ea91249f93cd299c0d23ff0c490.
* [Build Log](http://pr-test.k8s.io/26916/kubernetes-pull-build-test-e2e-gce/43475/build-log.txt)
* [Test Artifacts](https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26916/kubernetes-pull-build-test-e2e-gce/43475/artifacts/)
* [Internal Jenkins Results](http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce//43475)

Please reference the [list of currently known flakes](https://github.com/kubernetes/kubernetes/issues?q=is:issue+label:kind/flake+is:open) when examining this failure. If you request a re-test, you must reference the issue describing the flake.

We should replace all of this with a single link to gubernator

**Comment by fejta** [comment]
Please reopen if you see it again, I'm going to move the pr-test.k8s.io over to gubernator work to https://github.com/kubernetes/test-infra/issues/195

**Comment by rmmh** [comment]
I manually fixed up the bad links.
