### ISSUE TITLE
cluster-dns setting is not applied to daemonset pods

### ISSUE THREAD

**Issue by mingfang** [kubernetes/kubernetes#25626]
Setting cluster-dns causes the /etc/resolv.conf file to be configured correctly for all "normal" pods.
However this does not seem to work for pods created from daemonsets.

**Comment by zhouhaibing089** [comment]
maybe the daemonsets use hostnetwork?

**Comment by mingfang** [comment]
@zhouhaibing089 Thanks. Yes my daemonset is using hostnetwork. Is that the expected behavior?

I'm trying to run Zabbix agents as a daemonset and am using hostnetwork to try to monitor the network at the host level.

**Comment by zhouhaibing089** [comment]
referring this: https://github.com/kubernetes/kubernetes/issues/17406

**Comment by mikedanese** [comment]
> Is that the expected behavior?

yes
