### ISSUE TITLE
[Kubectl] - Validate every yaml files before processing them

### ISSUE THREAD

**Issue by samber** [kubernetes/kubernetes#25628]
When I execute `kubectl create -f namespace.yaml -f pod-app.yaml`, even if pod-app.yaml is not properly formated, namespace.yaml is parsed and interpreted:

```
namespace "linerio-system" created
unable to decode "pod-app.yaml": [pos 59]: json: expect char '{' but got char '['
```

I think both configuration files should be validated before processing resources.

**Comment by jayunit100** [comment]
hmmm... 
- Are you suggesting a requirement?  
- Or are you suggesting this is a  bug?

**Comment by samber** [comment]
It's not a requirement or a bug, just a small improvement to a better experience with kubectl.

I was writing some config files and after my syntax error, I needed to delete my namespace before retrying.

**Comment by jayunit100** [comment]
I agree with you, this has bit me before as well.  I think you're suggesting a requirement nevertheless that kubectl actions should attempt to be "atomic" for lack of a better word

**Comment by samber** [comment]
Exactly ! ;-)

**Comment by boj** [comment]
Ran across this myself and figured it'd be a good issue to tackle.

I spent a little time today digging through the code and identifying where to possibly handle this.  I'll tie in a PR once I have a satisfactory solution.

**Comment by krmayankk** [comment]
i can help fix this as my first contribution to Kubernetes. I would need some help though.

**Comment by asalkeld** [comment]
@krmayankk are you working on this, or can I take it?

**Comment by kargakis** [comment]
/sig cli
/sig api-machinery

I think it's generally accepted today that validation should only happen server-side but @kubernetes/sig-api-machinery-misc folks know better.
