### ISSUE TITLE
Not enough ips in kubernetes-jenkins-pull 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#25629]
Master didn't come up because there were no ips:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23567/kubernetes-pull-build-test-e2e-gce/40061/artifacts/
```
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/regions/us-central1/addresses/e2e-gce-builder-2-0-master-ip].
Generating certs for alternate-names: IP:146.148.108.105,IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:e2e-gce-builder-2-0-master
+++ Logging using Fluentd to elasticsearch
ERROR: (gcloud.compute.instances.create) Some requests did not succeed:
 - Quota 'IN_USE_ADDRESSES' exceeded.  Limit: 120.0
```
we're at:
```
In-use IP addresses us-central1	
97%
117 of 120
```
so we're either running too much on that project or leaking ips.

@kubernetes/goog-testing

**Comment by ixdy** [comment]
Now we have a different problem. Someone or something deleted all of the Jenkins GCE VMs in that project.

**Comment by bprashanth** [comment]
Sorry, I'm retarded. I did what i always do when there's a leak, free resources. Thought i was deleting disposable vms but i clearly messed that up.

**Comment by ixdy** [comment]
well, I will take this opportunity to fully clean up the project.

The node e2e tests occasionally leak VMs. We need to improve our infrastructure to garbage-collect these.

**Comment by bprashanth** [comment]
Things should be running now, closing. More than 60% of the ips are unused.

**Comment by bprashanth** [comment]
So it looks like we go from 0-100, real quick. We're back at 90 something % usage of ips.
I think we're just naturally saturating and need a quota bump, and till that gets approved some runs might flake. Leaving this open in the interim so people don't keep opening issues for the same thing.

**Comment by ixdy** [comment]
Cleaned up leaked node e2e VMs:
```
gcloud compute instances list --project=kubernetes-jenkins-pull --filter="NOT tags.items:do-not-delete AND creationTimestamp<'$(date +%Y-%m-%dT%H:%M:%S%z --date='1 hour ago')' AND NOT name~'.*jenkins.*'" --format='value(name)' | xargs gcloud compute instances delete --project=kubernetes-jenkins-pull --zone=us-central1-f
```

**Comment by bprashanth** [comment]
Hmm, looks like we're maxing out 150 ips now (https://github.com/kubernetes/kubernetes/pull/25171#issuecomment-219397215)

```
In-use IP addresses us-central1	
99%
148 of 150
```
Once bitten twice shy, @ixdy kick off your cleanup script? (or gc in a cron job till we fix the leak?)

**Comment by ixdy** [comment]
Yeah, cleaning up now. I'll make it part of our daily cleanup, but we need to figure out why so many of the node e2e tests are getting stuck, which is the root cause. @pwittrock

**Comment by ixdy** [comment]
Root cause (leaking VMs) fixed. Should be in the clear now.

**Comment by bprashanth** [comment]
@ixdy it occurred to me that an alert on quota > 75% indicates imminent flake. I'd subscribe to that if we had it.

**Comment by ixdy** [comment]
I'm working on setting up monitoring and alerting of our GCP quotas. It's unnecessarily difficult to integrate, unfortunately.
