### ISSUE TITLE
kube-down aws ec2

### ISSUE THREAD

**Issue by ericln** [kubernetes/kubernetes#25632]
I have created a cluster on aws with `kube-up` script (v1.2.4), and im trying to run the `kube-down` on a different machine from where I ran the `kube-up` with the same kubeConfig file. I only set the env variable `KUBERNETES_PROVIDER=aws`. But after running `kube-down` script (receiving a "done" message), the cluster seems to be....still up, nothing has changed.

I am curious what are the things we need to set to bring down the cluster with `kube-down` script

**Comment by rata** [comment]
@ericln Do you have the aws-shell installed with the same credentials? (or another user with permission for all, but the same credentials seems easier, if the permission hasn't changed).

What is the output?

**Comment by ericln** [comment]
yes the same awscli credential I used for running kube-up (on different machine), following is the output I got from running kube-down.sh

```
Bringing down cluster using provider: aws
Done
```

**Comment by rata** [comment]
On Mon, May 16, 2016 at 08:24:11AM -0700, Eric Lin wrote:
> yes the same awscli credential I used for running kube-up (on different machine), following is the output I got from running kube-down.sh
> 
> ```
> Bringing down cluster using provider: aws
> Done
> ```

Are you sure all the env variables are the same? In which region is the cluster?

**Comment by ericln** [comment]
@rata, that's what Im asking, what are the environment variables I need to set for the kube-down to work properly ? I am setting the region and provider that's it

**Comment by rata** [comment]
On Mon, May 16, 2016 at 09:08:56AM -0700, Eric Lin wrote:
> @rata, that's what Im asking, what are the environment variables I need to set for the kube-down to work properly ? I am setting the region and provider that's it

You need the same env variables that you use for the setup, that's all you need.
Probably you are setting the region wrong.

So, again, in which region is the cluster? And which env variables are you
setting? (you said only the provider first, now you say provider+region..)

**Comment by ericln** [comment]
@rata thanks, actually i just got it to work, thanks to your tips :) thanks, I have to set the `aws_default_profile` !!

**Comment by ericln** [comment]
just curious, how does kube-down knows which cluster to bring down ? if i have multiple cluster in the same region

**Comment by rata** [comment]
On Mon, May 16, 2016 at 09:35:16AM -0700, Eric Lin wrote:
> just curious, how does kube-down knows which cluster to bring down ? if i have multiple cluster in the same region

It uses tags on AWS.

A cluster has a name, and things of that cluster are tagged.


Can you close this now? :)
