### ISSUE TITLE
About kube-scheduler supports different node using different scheduling policies

### ISSUE THREAD

**Issue by ping035627** [kubernetes/kubernetes#25649]
As I understand, kube-scheduler doesn't supports different node using different scheduling policies currently. I want to know whether the community plans to achieve the function or not. Certainly If my understanding is wrong, please tell me, thanks very much.

**Comment by timothysc** [comment]
I'm not entirely certain what you are asking.  There exists node affinity functions, as well as taints and tolerations to treat nodes as "special".  I'm going to close this issue b/c it lacks a detailed description.  If you have further questions, please feel free to reopen.
