### ISSUE TITLE
test-cmd flake: kubectl rollout pause deployments --recursive

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubernetes#25645]
```
FAIL!
Get deployment {{range.items}}{{.spec.paused}}:{{end}}
  Expected: true:true:
  Got:      <no value>:true:
(B
1090 ./hack/test-cmd.sh
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25221/kubernetes-pull-test-unit-integration/25998/

**Comment by nikhiljindal** [comment]
cc @janetkuo

**Comment by fejta** [comment]
Assigning to @janetkuo per test-cmd.sh

**Comment by mikedanese** [comment]
Flaked again https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26190/kubernetes-pull-test-unit-integration/27676/

**Comment by janetkuo** [comment]
The flake actually happens when pausing the deployment. Changing issue title.

**Comment by janetkuo** [comment]
When `kubectl rollout pause -f hack/testdata/recursive/deployment --recursive`, sometimes one of the deployments isn't paused. 

cc @metral @kargakis

**Comment by metral** [comment]
I can't access the internal Google logs to examine the cause, nor can I reproduce this issue locally. Is there any additional information that you can provide to help troubleshoot the flake?

**Comment by metral** [comment]
I've gone ahead and attempted a fix for this in https://github.com/kubernetes/kubernetes/pull/26243

**Comment by kargakis** [comment]
We should fix this in https://github.com/kubernetes/kubernetes/issues/20437 eventually

**Comment by janetkuo** [comment]
@metral the external links are here (`s/pantheon.corp/console.cloud`):
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25221/kubernetes-pull-test-unit-integration/25998/
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26190/kubernetes-pull-test-unit-integration/27676/
