### ISSUE TITLE
Kubernetes monitoring tools updation

### ISSUE THREAD

**Issue by mohanbmahajan** [kubernetes/kubernetes#25647]
Grafana 3 has nice plugin features, it can be included in the upcoming release

**Comment by mikedanese** [comment]
who usually updates this? cc @vishh

**Comment by vishh** [comment]
@mohanbmahajan Can you open this issue against kubernetes/heapster? As of now Grafana integration is community maintained.

**Comment by kargakis** [comment]
Please reopen in the heapster repo if this is still relevant.
