### ISSUE TITLE
web interface not working

### ISSUE THREAD

**Issue by AaronTao1990** [kubernetes/kubernetes#25642]
I referred to the tutorial in [Running Kubernetes Locally via Docker](http://kubernetes.io/docs/getting-started-guides/docker/)  with v1.2.3 and I failed to access the web interface.

Here is the output.

```
{
    kind: "Status",
    apiVersion: "v1",
    metadata: { },
    status: "Failure",
    message: "endpoints "kubernetes-dashboard" not      found",
    reason: "NotFound",
    details: {
        name: "kubernetes-dashboard",
        kind: "endpoints"
    },
    code: 404
}
```

Any kind of help will be appriciated :)

**Comment by pwittrock** [comment]
@AaronTao1990 Due it being a maintenance nightmare, we are replacing the local docker setup with a new custom local cluster called [minikube](https://github.com/kubernetes/minikube).  It should be released soon, but is available for pre-release

@dlorenc Do you know if minikube runs the dashboard?

cc @vishh

**Comment by dlorenc** [comment]
We haven't tried yet but we have it tracked here: https://github.com/kubernetes/minikube/issues/3

AFAIK it *should* just work because we support service accounts, but we obviously won't know for sure until someone tries it.

**Comment by castrojo** [comment]
/assign

I'm closing this since minikube exists now, if you have any issues using that tool please file a new issue, thanks!
