### ISSUE TITLE
kube::golang::verify_go_version ssh termination bug

### ISSUE THREAD

**Issue by tmrts** [kubernetes/kubernetes#25659]
When I run `hack/test-go.sh` with Go 1.5, it prints out `Please install Go version 1.6 or later` and then terminates my SSH session.

**Comment by xiangpengzhao** [comment]
I run `hack/test-go.sh`/`make test` at HEAD with GO 1.5, but it doesn't reproduce. We're going to close this issue. Feel free to re-open if you still face it.

/sig testing

cc @thockin
