### ISSUE TITLE
on ubuntu 14.04 (vmware vm) , validating cluster failed 

### ISSUE THREAD

**Issue by singvey999** [kubernetes/kubernetes#25650]
Dear all,
  We met this kind of issue when do "KUBERNETES_PROVIDER=ubuntu ./kube-up.sh".
  the issue came at the below step,
- /root/kube/reconfDocker.sh i
  docker stop/waiting
  docker start/running, process 4601
  Connection to 192.168.132.4 closed.
  Validating master
  Validating root@192.168.132.2
  Validating root@192.168.132.3
  Validating root@192.168.132.4
  Using master 192.168.132.2
  cluster "ubuntu" set.
  user "ubuntu" set.
  context "ubuntu" set.
  switched to context "ubuntu".
  Wrote config for ubuntu to /root/.kube/config
  ... calling validate-cluster
  Error from server: an error on the server has prevented the request from succeeding
  (kubectl failed, will retry 2 times)
  Error from server: an error on the server has prevented the request from succeeding
  (kubectl failed, will retry 1 times)

... calling validate-cluster
Error from server: an error on the server has prevented the request from succeeding
(kubectl failed, will retry 2 times)
Error from server: an error on the server has prevented the request from succeeding
(kubectl failed, will retry 1 times)
Error from server: an error on the server has prevented the request from succeeding
('kubectl get nodes' failed, giving up)
Error from server: an error on the server has prevented the request from succeeding
(kubectl failed, will retry 2 times)

**Comment by singvey999** [comment]
we have 3 nodes(ai,i,i), the nodes'  OS is ubuntu 14.04 ,the environment variables were set properly.
We met this issue many times and could not finish this step "KUBERNETES_PROVIDER=ubuntu ./kube-up.sh".
we can check the nodes status with kubectl get nodes as below
******
root@ubuntu02:~/kubernetes/cluster/ubuntu/binaries# ./kubectl get nodes
NAME            STATUS    AGE
192.168.132.2   Ready     15m
192.168.132.3   Ready     15m
192.168.132.4   Ready     15m

**Comment by singvey999** [comment]
the related status checking as below:
root@ubuntu02:~/kubernetes/cluster/ubuntu/binaries# ./kubectl get svc
NAME         CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes   192.168.132.1   <none>        443/TCP   22m
root@ubuntu02:~/kubernetes/cluster/ubuntu/binaries# ./kubectl get rc
root@ubuntu02:~/kubernetes/cluster/ubuntu/binaries# ./kubectl get no
NAME            STATUS    AGE
192.168.132.2   Ready     22m
192.168.132.3   Ready     21m
192.168.132.4   Ready     21m
root@ubuntu02:~/kubernetes/cluster/ubuntu/binaries# ./kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   
controller-manager   Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
root@ubuntu02:~/kubernetes/cluster/ubuntu/binaries# ./kubectl get ep
NAME         ENDPOINTS            AGE
kubernetes   192.168.132.2:6443   22m
root@ubuntu02:~/kubernetes/cluster/ubuntu/binaries# ./kubectl get ns
NAME      STATUS    AGE
default   Active    22m

**Comment by ryansavino** [comment]
I am seeing the same issue. I have a 3 node setup, all with "Ubuntu 14.04.3 LTS". However, none of my kubectl status commands are working; they report the same error.

error:
root@mh-node-savino-70-40:~/kubernetes/cluster# KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
... Starting cluster using provider: ubuntu
... calling verify-prereqs
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
... calling kube-up
~/kubernetes/cluster/ubuntu ~/kubernetes/cluster
Prepare flannel 0.5.5 release ...
Prepare etcd 2.3.1 release ...
Prepare kubernetes 1.2.4 release ...
Done! All your binaries locate in kubernetes/cluster/ubuntu/binaries directory
~/kubernetes/cluster
Deploying master and node on machine 10.1.70.40
make-ca-cert.sh                                                                  100% 4028     3.9KB/s   00:00
easy-rsa.tar.gz                                                                  100%   42KB  42.4KB/s   00:00
config-default.sh                                                                100% 5557     5.4KB/s   00:00
util.sh                                                                          100%   29KB  28.6KB/s   00:00
kube-proxy.conf                                                                  100%  684     0.7KB/s   00:00
kubelet.conf                                                                     100%  644     0.6KB/s   00:00
kubelet                                                                          100% 2158     2.1KB/s   00:00
kube-proxy                                                                       100% 2233     2.2KB/s   00:00
kube-apiserver.conf                                                              100%  674     0.7KB/s   00:00
kube-controller-manager.conf                                                     100%  744     0.7KB/s   00:00
kube-scheduler.conf                                                              100%  674     0.7KB/s   00:00
etcd.conf                                                                        100%  709     0.7KB/s   00:00
kube-apiserver                                                                   100% 2358     2.3KB/s   00:00
kube-scheduler                                                                   100% 2360     2.3KB/s   00:00
etcd                                                                             100% 2073     2.0KB/s   00:00
kube-controller-manager                                                          100% 2672     2.6KB/s   00:00
reconfDocker.sh                                                                  100% 2094     2.0KB/s   00:00
kube-apiserver                                                                   100%   58MB  58.2MB/s   00:00
kube-scheduler                                                                   100%   42MB  42.0MB/s   00:00
flanneld                                                                         100%   16MB  15.8MB/s   00:00
etcd                                                                             100%   16MB  15.9MB/s   00:00
kube-controller-manager                                                          100%   52MB  51.8MB/s   00:01
etcdctl                                                                          100%   14MB  13.7MB/s   00:00
flanneld                                                                         100%   16MB  15.8MB/s   00:00
kubelet                                                                          100%   60MB  60.3MB/s   00:00
kube-proxy                                                                       100%   35MB  34.8MB/s   00:00
flanneld.conf                                                                    100%  577     0.6KB/s   00:00
flanneld                                                                         100% 2121     2.1KB/s   00:00
flanneld.conf                                                                    100%  568     0.6KB/s   00:00
flanneld                                                                         100% 2131     2.1KB/s   00:00
[sudo] password to start master:
etcd start/running, process 23196
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
docker stop/waiting
docker start/running, process 23447
Connection to 10.1.70.40 closed.
Deploying node on machine 10.1.71.82
config-default.sh                                                                100% 5557     5.4KB/s   00:00
util.sh                                                                          100%   29KB  28.6KB/s   00:00
reconfDocker.sh                                                                  100% 2094     2.0KB/s   00:00
kube-proxy.conf                                                                  100%  684     0.7KB/s   00:00
kubelet.conf                                                                     100%  644     0.6KB/s   00:00
kubelet                                                                          100% 2158     2.1KB/s   00:00
kube-proxy                                                                       100% 2233     2.2KB/s   00:00
flanneld                                                                         100%   16MB  15.8MB/s   00:00
kubelet                                                                          100%   60MB  60.3MB/s   00:01
kube-proxy                                                                       100%   35MB  34.8MB/s   00:00
flanneld.conf                                                                    100%  577     0.6KB/s   00:00
flanneld                                                                         100% 2121     2.1KB/s   00:00
[sudo] password to start node:
flanneld start/running, process 12274
docker stop/waiting
docker start/running, process 12397
Connection to 10.1.71.82 closed.
Deploying node on machine 10.1.71.96
config-default.sh                                                                100% 5557     5.4KB/s   00:00
util.sh                                                                          100%   29KB  28.6KB/s   00:00
reconfDocker.sh                                                                  100% 2094     2.0KB/s   00:00
kube-proxy.conf                                                                  100%  684     0.7KB/s   00:00
kubelet.conf                                                                     100%  644     0.6KB/s   00:00
kubelet                                                                          100% 2158     2.1KB/s   00:00
kube-proxy                                                                       100% 2233     2.2KB/s   00:00
flanneld                                                                         100%   16MB  15.8MB/s   00:00
kubelet                                                                          100%   60MB  60.3MB/s   00:01
kube-proxy                                                                       100%   35MB  34.8MB/s   00:01
flanneld.conf                                                                    100%  577     0.6KB/s   00:00
flanneld                                                                         100% 2121     2.1KB/s   00:00
[sudo] password to start node:
flanneld start/running, process 30085
docker stop/waiting
docker start/running, process 30218
Connection to 10.1.71.96 closed.
Validating master
Validating kubernetes@10.1.70.40
Validating kubernetes@10.1.71.82
Validating kubernetes@10.1.71.96
Using master 10.1.70.40
cluster "ubuntu" set.
user "ubuntu" set.
context "ubuntu" set.
switched to context "ubuntu".
Wrote config for ubuntu to /root/.kube/config
... calling validate-cluster
Error from server: an error on the server has prevented the request from succeeding
(kubectl failed, will retry 2 times)
Error from server: an error on the server has prevented the request from succeeding
(kubectl failed, will retry 1 times)
Error from server: an error on the server has prevented the request from succeeding
('kubectl get nodes' failed, giving up)

**Comment by ryansavino** [comment]
from /var/log/upstart/kube-proxy.log:
E0524 11:28:39.645186   23228 server.go:340] Can't get Node "10.1.70.40", assuming iptables proxy: Get http://10.1.70.40:8080/api/v1/nodes/10.1.70.40: dial tcp 10.1.70.40:8080: connection refused
I0524 11:28:39.646192   23228 server.go:200] Using iptables Proxier.
I0524 11:28:39.646284   23228 proxier.go:208] missing br-netfilter module or unset br-nf-call-iptables; proxy may not work as intended
I0524 11:28:39.646319   23228 server.go:213] Tearing down userspace rules.
I0524 11:28:39.653656   23228 conntrack.go:36] Setting nf_conntrack_max to 262144
I0524 11:28:39.653717   23228 conntrack.go:41] Setting conntrack hashsize to 65536
I0524 11:28:39.653987   23228 conntrack.go:46] Setting nf_conntrack_tcp_timeout_established to 86400
E0524 11:28:39.654406   23228 event.go:202] Unable to write event: 'Post http://10.1.70.40:8080/api/v1/namespaces/default/events: dial tcp 10.1.70.40:8080: connection refused' (may retry after sleeping)

**Comment by erictune** [comment]
@resouer @dalanlan @yeasy @ZhangZhenhua can one of you help debug this issue?

**Comment by dalanlan** [comment]
@ryansavino Seems apiserver is not working, would you mind showing me the log of that?

**Comment by ryansavino** [comment]
Here's the output from /var/log/upstart/kube-apiserver.log:
I0602 17:47:23.661928    9434 server.go:188] Will report 10.1.70.40 as public IP address.
I0602 17:47:23.662012    9434 plugins.go:71] No cloud provider specified.
I0602 17:47:23.662123    9434 server.go:112] constructing etcd storage interface.
  sv: v1
  mv: __internal
I0602 17:47:23.662210    9434 genericapiserver.go:82] Adding storage destination for group
I0602 17:47:23.662249    9434 server.go:296] Configuring extensions/v1beta1 storage destination
I0602 17:47:23.662267    9434 server.go:112] constructing etcd storage interface.
  sv: extensions/v1beta1
  mv: extensions/__internal
I0602 17:47:23.662340    9434 genericapiserver.go:82] Adding storage destination for group extensions
I0602 17:47:23.662360    9434 genericapiserver.go:82] Adding storage destination for group autoscaling
I0602 17:47:23.662372    9434 genericapiserver.go:82] Adding storage destination for group batch
I0602 17:47:23.662388    9434 server.go:325] Configuring autoscaling/v1 storage destination
I0602 17:47:23.662405    9434 server.go:339] Using autoscaling/v1 for autoscaling group storage version
I0602 17:47:23.662421    9434 server.go:112] constructing etcd storage interface.
  sv: autoscaling/v1
  mv: extensions/__internal
I0602 17:47:23.662481    9434 genericapiserver.go:82] Adding storage destination for group autoscaling
I0602 17:47:23.662504    9434 server.go:352] Configuring batch/v1 storage destination
I0602 17:47:23.662520    9434 server.go:366] Using batch/v1 for batch group storage version
I0602 17:47:23.662536    9434 server.go:112] constructing etcd storage interface.
  sv: batch/v1
  mv: extensions/__internal
I0602 17:47:23.662605    9434 genericapiserver.go:82] Adding storage destination for group batch
[restful] 2016/06/02 17:47:24 log.go:30: [restful/swagger] listing is available at https://10.1.70.40:443/swaggerapi/
[restful] 2016/06/02 17:47:24 log.go:30: [restful/swagger] https://10.1.70.40:443/swaggerui/ is mapped to folder /swagger-ui/
I0602 17:47:24.006208    9434 genericapiserver.go:692] Serving securely on 0.0.0.0:6443
I0602 17:47:24.006245    9434 genericapiserver.go:734] Serving insecurely on 0.0.0.0:8080

**Comment by ZhangZhenhua** [comment]
> I0524 11:28:39.646284 23228 proxier.go:208] missing br-netfilter module or unset br-nf-call-iptables; proxy may not work as intended

This error message seems suspicious. Might duplicated with #23385.

**Comment by dalanlan** [comment]
The problem of iptables kube-proxy should not harm apiserver though.
It's clear that kubectl cannot talk to apiserver itself



Sent from myMail for iOS


Friday, June 3, 2016, 10:03 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by ryansavino** [comment]
I actually resolved this issue:
> I0524 11:28:39.646284 23228 proxier.go:208] missing br-netfilter module or unset br-nf-call-iptables; > proxy may not work as intended

by upgrading to a later kernel and installing the module.

**Comment by ryansavino** [comment]
Just to clarify, the main issue still exists...

**Comment by ryansavino** [comment]
The apiserver is up and running. I can even access it remotely.

I think the issue is that the kubectl binary is observing the proxy configuration for connections to 127.0.0.1 or localhost when it is not supposed to.

From my config-default.sh:
PROXY_SETTING=${PROXY_SETTING:-"http_proxy=http://proxy-us.intel.com:911 https_proxy=http://proxy-us.intel.com:911 no_proxy=localhost,127.0.0.1,127.0.1.1"}

When specifically calling the apiserver using a curl command:
root@savyk8snode1:~# curl http://127.0.0.1:8080
<HTML>
<HEAD><TITLE>Redirection</TITLE></HEAD>
<BODY><H1>Redirect</H1></BODY>

With noproxy set:
root@savyk8snode1:~# curl --noproxy 127.0.0.1 http://127.0.0.1:8080
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/resetMetrics",
    "/swagger-ui/",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]

**Comment by ryansavino** [comment]
Also, on a side note, I noticed that line 62-63 of cluster/ubuntu/reconfDocker.sh overwrite any existing docker configuration in /etc/default/docker:
   echo DOCKER_OPTS=\"${DOCKER_OPTS} -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock \
        --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}\" > /etc/default/docker

This was an issue for me as I was configuring the proxy for docker in that file.

**Comment by dalanlan** [comment]
>Also, on a side note, I noticed that lines 62-63 of cluster/ubuntu/reconfDocker.sh overwrite any existing docker configuration in /etc/default/docker:
echo DOCKER_OPTS=\"${DOCKER_OPTS} -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock \
--bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}\" > /etc/default/docker
This was an issue for me as I was configuring the proxy for docker in that file.

Would `source /etc/default/docker` help?

**Comment by ryansavino** [comment]
The proxy configuration in /etc/default/docker just goes on a separate line, which gets overwritten with that command. There is a way to configure the proxy for docker directly in the init script, but I couldn't get that working. For now, I've just added my proxy configuration lines to reconfDocker.sh

**Comment by ryansavino** [comment]
I've managed to get my cluster up. The issue turned out to be related to the proxy configuration; just a matter of setting http_proxy and no_proxy variables in the correct places for ubuntu, docker and kubernetes.

Thanks to all who assisted.

**Comment by karunchennuri** [comment]
@ryansavino I exactly have the same kind of configuration. Can you pls let me know what all files you've changed for http_proxy & no_proxy?

**Comment by ryansavino** [comment]
In ubuntu user .profile:
```
export HTTP_PROXY=[proxy]
export http_proxy=[proxy]
export HTTPS_PROXY=[proxy]
export https_proxy=[proxy]
```

I couldn't get CIDR notation to work correctly so I listed my node ips out:
```
export NO_PROXY="10.1.70.40,10.1.71.82,10.1.71.96,localhost,127.0.0.1,127.0.1.1"
export no_proxy="10.1.70.40,10.1.71.82,10.1.71.96,localhost,127.0.0.1,127.0.1.1"
```

I also added kubernetes bin directory to path:
`export PATH=$PATH:[PATH_TO]/kubernetes/cluster/ubuntu/binaries/`

Added "--no-sync" argument to etcdctl calls in kubernetes/cluster/ubuntu/reconfDocker.sh.

Added these lines to kubernetes/cluster/ubuntu/reconfDocker.sh - after line 63-64 "echo DOCKER_OPTS=...":
```
  echo -e "export HTTP_PROXY='[proxy]'" >> /etc/default/docker
  echo -e "export http_proxy='[proxy]'" >> /etc/default/docker
  echo -e "export HTTPS_PROXY='[proxy]'" >> /etc/default/docker
  echo -e "export https_proxy='[proxy]'" >> /etc/default/docker
```

Added proxy to kubernetes/cluster/ubuntu/config-default.sh:
`PROXY_SETTING="http_proxy=[proxy] https_proxy=[proxy] no_proxy=10.1.70.40,10.1.71.82,10.1.71.96,localhost,127.0.0.1,127.0.1.1"`

**Comment by karunchennuri** [comment]
@ryansavino thanks for the steps. After proxy settings, the reported issue is gone. However, my setup now still fails at the validate-cluster part... but this time with a different issue...

`Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.`

I've checked upstart logs, I see nothing suspicious. Have you encountered this issue?

**Comment by karunchennuri** [comment]
My bad... I realized that i was using old version of kubernetes which has this issue... when i upgraded to latest stable version, everything works fine...
thanks a lot @ryansavino

**Comment by xiangpengzhao** [comment]
Already solved, right?

/ sig cluster-ops

@thockin

**Comment by xiangpengzhao** [comment]
Oops
/sig cluster-ops
