### ISSUE TITLE
flake: e2e test timed out

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#25652]
I got "Build timed out (after 80 minutes)" in https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25216/kubernetes-pull-build-test-e2e-gce/40063/

Build and Installation seems to take quite a long time:
```
2016/05/15 09:15:36 e2e.go:196: Step 'build-release' finished in 26m37.531945477s
2016/05/15 09:57:45 e2e.go:196: Step 'up' finished in 40m54.545362154s
```

Which gives us ~13 minutes for actual tests.

**Comment by dims** [comment]
@jsafrane @rmmh - Looks like this has not happened in a while. So can we close it?
