### ISSUE TITLE
Move PodSecurityPolicy to policy api group

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#25666]
As the name `podsecuritypolicy` suggests, it may be better to put it at [policy](https://github.com/kubernetes/kubernetes/tree/master/pkg/apis/policy) api group.

Besides, it looks there is convention violation [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L838-L841): 

```go
podSecurityPolicyStorage := pspetcd.NewREST(restOptions("podsecuritypolicy"))
// ....(restOptions("podsecuritypolicies")) ?
if c.APIResourceConfigSource.ResourceEnabled(version.WithResource("podsecuritypolicy")) {
	storage["podSecurityPolicies"] = podSecurityPolicyStorage
	// storage["podsecuritypolicies"] = podSecurityPolicyStorage ?
}
```

/cc @erictune @liggitt @pweil-

**Comment by liggitt** [comment]
The policy API group didn't exist when PSP was added. If I understand it correctly, it is not intended to contain authorization type policy objects (which @deads2k pointed out would be confusing when the policy API group was introduced)

**Comment by zhouhaibing089** [comment]
I see there is an ongoing pull request which introduces [networkpolicy](https://github.com/kubernetes/kubernetes/pull/25638) and that's why I feel the same for psp. what's the confusing point then? I personally feel it is more natural to find a `podsecuritypolicy` in a policy api group..

**Comment by zhouhaibing089** [comment]
nothing is tracked here, close it.
