### ISSUE TITLE
Backoff in scheduler is not working as intended

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25663]
It seems that if a pod doesn't fit on any node, we are trying to schedule it without any backoff.

As an example see those logs from our big cluster:

```
I0516 11:17:25.112607       5 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"heapster-v1.1.0.beta1-3233973386-krr39", UID:"75476330-1b54-11e6-a7f5-42010af00002", APIVersion:"v1", ResourceVersion:"229057", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' pod (heapster-v1.1.0.beta1-3233973386-krr39) failed to fit in any node
...
I0516 11:17:25.213493       5 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"heapster-v1.1.0.beta1-3233973386-krr39", UID:"75476330-1b54-11e6-a7f5-42010af00002", APIVersion:"v1", ResourceVersion:"229058", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' pod (heapster-v1.1.0.beta1-3233973386-krr39) failed to fit in any node
...
I0516 11:17:25.290314       5 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"heapster-v1.1.0.beta1-3233973386-krr39", UID:"75476330-1b54-11e6-a7f5-42010af00002", APIVersion:"v1", ResourceVersion:"229162", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' pod (heapster-v1.1.0.beta1-3233973386-krr39) failed to fit in any node
...
I0516 11:17:25.351509       5 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"heapster-v1.1.0.beta1-3233973386-krr39", UID:"75476330-1b54-11e6-a7f5-42010af00002", APIVersion:"v1", ResourceVersion:"229171", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' pod (heapster-v1.1.0.beta1-3233973386-krr39) failed to fit in any node
```

 So it seems we are trying to schedule as often as possible, which is definitely a bug.

@davidopp @gmarek @kubernetes/sig-scheduling

**Comment by gmarek** [comment]
Repro: run a cluster with heapster memory size set to too big to fit on a machine.

**Comment by wojtek-t** [comment]
OK - I think I debugged it.

It was broken by https://github.com/kubernetes/kubernetes/pull/24459 by @fgrzadkowski 

To clarify what exactly happens here is that:

1. we are trying to schedule a pod
2. scheduling fails
3. this triggers sending "Unschedulable" pod condition
4. then scheduler watches this change (this is not scheduled pod)
5. and then is trying to schedule again
6. [the backoff is done in the background, so we are adding this pod even more times to the scheduling queue]

To be honest, I'm not sure what is the best way to fix that. I would like to avoid "backoff" in the main path of the scheduler, because this will slow down the scheduler in a healthy state.

@fgrzadkowski - can you please fix that?

**Comment by wojtek-t** [comment]
And it wouldn't be that bad, if the condition wouldn't change, but it contains error, which is our case was FitError.Error(), which unfortunately is undeterministic because it is iteration over map.

**Comment by mqliang** [comment]
a "smart" workqueue with:
1) priority 
2) deadline: we could set the deadline(dequeue time) 
3) duplicate removal

may could help in such a case. Have a related proposal for such a workqueue, see https://github.com/kubernetes/kubernetes/pull/20203. (may need update now).

**Comment by wojtek-t** [comment]
This would be way to complicated for this usecase in my opinion.

**Comment by mqliang** [comment]
> This would be way to complicated for this usecase in my opinion.

I agree. We should do some simple in short term. But in the long run, we may need a "smart workqueue"(or a collection of workqueues with different feature combination), which should support:

1) priority
2) round-robin across namespace
3) duplicate removal
4) deadline
5) other potential features

The current FIFO workqueue is too simple IMO.

**Comment by fgrzadkowski** [comment]
As discussed offline we will stop setting message (short-term) and later with each watch update compare spec and re-attempt scheduling only if spec has changed, i.e. ignore status updates.

**Comment by kevin-wangzefeng** [comment]
> later with each watch update compare spec and re-attempt scheduling only if spec has changed, i.e. ignore status updates.

This seems doesn't support the case if a pod failed scheduling because of resource not fit, and later on the admin added some resource to the cluster, wishing the pod can be successfully scheduled and started.

What I am think about is introducing a max-retry/cool-down mechanism:
1. add a field i.e. `schedulingRetryCounts` to PodStatus to count a pod failed scheduling and retry times,
2. add another field i.e. `lastTimeScheduling` to PodStatus to record the last time scheduler trying to schedule the pod.
It should works like below:
1. after the first time scheduling failed, scheduler will still re-attempt to schedule the pod, and every time it retries, update the `schedulingRetryCounts` and `lastTimeScheduling`
2. when `schedulingRetryCounts` reached the max retry counts (this could be a startup config parameter for scheduler), scheduler won't try to schedule the pod but just check `lastTimeScheduling` and wait for it cools down.
3. when `time.Now() - lastTimeScheduling` is greater than the cooldown threshold, scheduler reset the two fields `schedulingRetryCounts`, `lastTimeScheduling` and starts retry.

This mechanism maybe not very smart but easy to do.

**Comment by fgrzadkowski** [comment]
@kevin-wangzefeng Pod will be scheduled again, but after a backoff. So this will work. The problem that we have now is that with each status update we ignore back-off mechanism and retry scheduling.

**Comment by kevin-wangzefeng** [comment]
@fgrzadkowski I see, thanks for explaining.

**Comment by fgrzadkowski** [comment]
@wojtek-t @davidopp After #25741 we will only update the pod once, when updating pod condition for the first time. That means that back-off mechanism will be working, but the first re-iteration will too quickly (immediately after updating pod condition). After offline discussion with @wojtek-t I believe this is now P1 and is not blocking 1.3. Do you confirm? Can we remove 1.3 mileston?

**Comment by davidopp** [comment]
Yes that seems fine. Removing 1.3 milestone.

**Comment by timothysc** [comment]
@fgrzadkowski are you planning on working on this?

**Comment by fgrzadkowski** [comment]
No.

**Comment by timothysc** [comment]
@balajismaniam can you triage please.
