### ISSUE TITLE
NODE_SIZE update

### ISSUE THREAD

**Issue by rmaugusto** [kubernetes/kubernetes#25668]
Is it possible create a feature in kube-push to update NODE_SIZE instead of recreate a cluster ? I am using AWS.

**Comment by felipejfc** [comment]
last time I needed to do that, I created a new launch configuration equal to the one kube-up created, just changing the instance type, then I replaced it on the auto-scaling group.
I dont think that we have anything more automated than this, It would be very good...

**Comment by rmaugusto** [comment]
I tried that but AWS forces to clear previous storage configuration and I would need to add storages manually, it is not complicated but to automize could make sense if more users have this need.  Thanks

**Comment by justinsb** [comment]
This will likely best be done as part of #23478

**Comment by bgrant0607** [comment]
Closing as a dupe / obsolete. Follow SIG cluster lifecycle for current efforts.
