### ISSUE TITLE
Out of context pod names in examples

### ISSUE THREAD

**Issue by isubuz** [kubernetes/kubernetes#25675]
This is a minor documentation comment.

As per the documentation [here](http://kubernetes.io/docs/user-guide/pods/single-container/), to create a single container pod, `kubectl run` can be used as follows:

```sh
~ kubectl run example --image=nginx
deployment "example" created
```

The actual name of the created pod has the prefix `example` followed by some characters.

However, in the **Viewing the pod** section, in all the examples, the pod name is displayed as `example` which is slightly confusing for someone glancing through the docs starting from the top. We use the same name `example` in couple of other examples. For me, it was a bit more confusing, because in the `kubectl describe` command we can use `example` because this command accepts a  `NAME_PREFIX`, but the documentation mentions `NAME`.

However, in the below example, we use the correct name (in context):

```sh
$ kubectl get pods

NAME                 READY     STATUS    RESTARTS   AGE
example-xypvc        1/1       Running   0          1m
frontend-7kdod       1/1       Running   0          1d
```

IMHO, for people starting out with this project, keeping the context in the examples will make things clearer and easier to grasp.

I can make the change, if it seems like the right to do.

**Comment by pwittrock** [comment]
cc @johndmulhausen 

@isubuz Fixing this seems like the right thing todo.  If you create a PR against kubernetes/kubernetes.github.io @johndmulhausen and I will review it.

**Comment by isubuz** [comment]
Sounds good!

**Comment by isubuz** [comment]
Now that the code has been merged, does the issue get closed by an automated process? Or can I close it?

**Comment by dims** [comment]
@isubuz please close the bug. thanks!
