### ISSUE TITLE
e2e broken: Kubectl describe should check if kubectl describe prints relevant information for rc and pods

### ISSUE THREAD

**Issue by spxtr** [kubernetes/kubernetes#25677]
This has been broken ever since #24806 merged, cc @jayunit100. [Example failure](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-flaky/16994). This test needs to be fixed, deflaked, and then moved out of the flaky suite.

**Comment by janetkuo** [comment]
@jayunit100 the PR #24806 basically undoes #24849...

**Comment by jayunit100** [comment]
hi @spxtr let me get on this right away

**Comment by bprashanth** [comment]
I'm not convinced it was docker hub flake though, we're seeing general image pull fail (https://github.com/kubernetes/kubernetes/issues/24782, https://github.com/kubernetes/kubernetes/issues/25277#issuecomment-219199703, https://github.com/kubernetes/kubernetes/issues/25277#issuecomment-219256108 to name a few)

**Comment by spxtr** [comment]
This one wasn't just flaky, it was outright broken, and it's back to just being flaky now :)

**Comment by jayunit100** [comment]
Hmmmm This is a conformance test iirc... I wonder how it broke in the CI?  Maybe because the container got removed slightly after the PR merged .

**Comment by spxtr** [comment]
@jayunit100 this test was so flaky (~20%) that I moved it to the flaky suite, so it doesn't block merges.
