### ISSUE TITLE
RBD plugin looks for secret in pod namespace instead of PV namespace

### ISSUE THREAD

**Issue by relaxdiego** [kubernetes/kubernetes#25697]
It took me a while to get past this error because the documentation implied that the secret must be created in the same namespace as the rbd PV. This would be the default namespace and I agree with the documentation.

However, the code seems to behave differently. From this line: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/rbd/rbd.go#L82 I can see that it's using the namespace of the Pod that's mounting the PVC that's bound to the PV.

The result of this confusion is that I get this cryptic error message in `oc describe pod`:

```
Events:
  FirstSeen LastSeen    Count   From                    SubobjectPath   Reason      Message
  ─────────   ────────    ───── ────                    ───────────── ──────      ───────
  1h        1h      1   {scheduler }                        Scheduled   Successfully assigned redis-master-ann1v to 10-0-3-21.cloud.opsource.net
  1h        54s     404 {kubelet 10-0-3-21.cloud.opsource.net}          FailedMount Unable to mount volumes for pod "redis-master-ann1v_marktest": unsupported volume type
  1h        54s     404 {kubelet 10-0-3-21.cloud.opsource.net}          FailedSync  Error syncing pod, skipping: unsupported volume type
```

I get a little bit more hint from `service atomic-openshift-node status -l`:

```
May 16 18:20:07 10-0-3-21.cloud.opsource.net atomic-openshift-node[27177]: E0516 18:20:07.472766   27177 rbd.go:88] Couldn't get secret marktest/&{ceph-secret}
```

When I moved the secret from the default context to the project's context (marktest), the pods finally get created.

Shouldn't the RBD plugin use the PV's namespace in the above code?

**Comment by relaxdiego** [comment]
Adding a diagram of my understanding of how PVs and PVCs should be used. From what I understand from the docs, the PVs are supposed to abstract out the details of the underlying storage backend which includes the credentials.

![screen shot 2016-05-19 at 9 52 34 am](https://cloud.githubusercontent.com/assets/110545/15402203/d86b4a7e-1da7-11e6-8378-c51bb980be1f.png)

**Comment by childsb** [comment]
The reason to keep CEPH secret in its own namespace is security.  If CEPH secret is in the default namespace a malicious user could access backing volume.

I'll leave this open as a documentation bug.

**Comment by relaxdiego** [comment]
Thanks @childsb! If I understand it correctly, part of the documentation fix is to change the instruction to use a Ceph user key instead of a Ceph admin key otherwise any project that uses the Ceph backend will have a copy of the admin key. Is that correct?

**Comment by rootfs** [comment]
@relaxdiego I see two topics discussed here: ceph secret namespace and ceph user. As @childsb said, the secret is in the same namespace as the project, so the same Ceph cluster resource can be shared among multiple projects, each of the projects can be properly isolated as well.

Sharing Ceph admin, the privileged user, among projects risks exposing the entire Ceph cluster to unprivileged users. So it is better to create one user for one project to preserve privacy.

**Comment by relaxdiego** [comment]
@rootfs (awesome username!) thanks for the clarification.
