### ISSUE TITLE
Containers within a pod don't share the same UTS namespace

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#25700]
During reviewing container runtime interface proposal, I surprisingly found that containers within a pod today only share both network and IPC namespace, not uts one. I don't think there are any production issues caused by this, but we should clean up this. 

cc/ @yujuhong @vishh

**Comment by Random-Liu** [comment]
@dchen1107 It seems that docker hasn't support sharing uts namespace between containers yet.
Container can only share host name when using host network. (See https://github.com/docker/engine-api/blob/c08ca7c7fadc784880c3ceb3e89d923aa6c13396/types/container/host_config.go#L115-L136)

And also ref https://github.com/kubernetes/kubernetes/issues/1615.

**Comment by bprashanth** [comment]
Personally I don't care about UTS that much because I get hostname anyway

**Comment by yujuhong** [comment]
Yes, docker doesn't support setting UTS namespace to a container yet, but it does allow setting the hostname. Given that we already have an issue #1615 tracking namespace sharing, let's close this one.
