### ISSUE TITLE
Removing images causes Nodes to stop reporting status

### ISSUE THREAD

**Issue by mingfang** [kubernetes/kubernetes#25702]
Running a command like this `docker rmi `docker images -q --filter dangling=true`` will cause the Node to stop reporting status.  The Master will think that the Node has died and will eventually start evicting all the Pods.  
This is happening even though the Node is healthy.

**Comment by dchen1107** [comment]
@mingfang I couldn't reproduce the issue. 

Which docker version are you using? What is the output of kubectl describe nodes <node-id> when the master thinks node is not_ready. Why do you want to remove the images manually? Kubelet does gc un-used images periodically, is it not meeting your requirements?

**Comment by mingfang** [comment]
Because I'm running kubelet containerize I believe the image garbage collection does not work.
In my logs I'm seeing a lot of these
```kubelet.go:956] Image garbage collection failed: non-existent label "docker-images"```

**Comment by mingfang** [comment]
i think this is docker issue and doubt there's anything kubernetes can do about it.
closing.
