### ISSUE TITLE
storePodsNamespacer.List() returns the same pod more than once

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#25705]
I haven't isolated this in a test case yet, but the code is at https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/listers.go#L79

I am using this in the disruption controller to count up all the pods that match the PodDisruptionBudget, and I was puzzled as to why the controller sometimes counted 2 pods, and sometimes 1.  Below are some log lines.  As you can see, it's the same yo-yo-yo pod the whole time, only sometimes it gets counted twice.

```
 I0516 17:40:35.781262   14907 disruption.go:106] update DB "foo"
 I0516 17:40:35.787901   14907 disruption.go:242] 3 desired, 1 expected
 I0516 17:40:35.787918   14907 disruption.go:244] ("yo-yo-yo", "f70bbca5-1bc7-11e6-bb0a-40a8f055c9c7", "116", {"2016-05-16 17:40:33 -0700 PDT"})
[...]
 I0516 17:41:04.780701   14907 disruption.go:106] update DB "foo"
 I0516 17:41:04.780760   14907 disruption.go:242] 3 desired, 2 expected
 I0516 17:41:04.780775   14907 disruption.go:244] ("yo-yo-yo", "f70bbca5-1bc7-11e6-bb0a-40a8f055c9c7", "122", {"2016-05-16 17:40:33 -0700 PDT"})
 I0516 17:41:04.780798   14907 disruption.go:244] ("yo-yo-yo", "f70bbca5-1bc7-11e6-bb0a-40a8f055c9c7", "122", {"2016-05-16 17:40:33 -0700 PDT"})
 I0516 17:41:04.782873   14907 disruption.go:106] update DB "foo"
 I0516 17:41:04.788320   14907 disruption.go:242] 3 desired, 2 expected
 I0516 17:41:04.788333   14907 disruption.go:244] ("yo-yo-yo", "f70bbca5-1bc7-11e6-bb0a-40a8f055c9c7", "122", {"2016-05-16 17:40:33 -0700 PDT"})
 I0516 17:41:04.788352   14907 disruption.go:244] ("yo-yo-yo", "f70bbca5-1bc7-11e6-bb0a-40a8f055c9c7", "122", {"2016-05-16 17:40:33 -0700 PDT"})
 I0516 17:41:33.781160   14907 reflector.go:282] Listing and watching *policy.PodDisruptionBudget from pkg/controller/disruption/disruption.go:91
[...]
```

**Comment by mml** [comment]
@kubernetes/sig-api-machinery

**Comment by kargakis** [comment]
@mml do you have a pull for the disruption controller somewhere?

**Comment by smarterclayton** [comment]
Yikes

**Comment by derekwaynecarr** [comment]
Would need to see the corresponding PR to know how you are using it.... are you using NamespaceAll?

**Comment by lavalamp** [comment]
The linked code clearly has a locking problem. The call to List and the call to Index will see different sets of data. Thanks for reporting.

**Comment by lavalamp** [comment]
Most likely introduced in #23795. @wojtek-t @mqliang ideas for a fix?

**Comment by lavalamp** [comment]
This would be a regression, so we need to fix before cutting 1.3.

**Comment by mml** [comment]
I'm surprised no other test is flaky because of this.

**Comment by mqliang** [comment]
@lavalamp 
> The linked code clearly has a locking problem. The call to List and the call to Index will see different sets of data.

Could you please be more specific here?

**Comment by mml** [comment]
I just spoke to @lavalamp and he said he thought we were calling both `List()` and `Index()` at different times without a lock to assure we always acted on the same data.  I'm not convinced.  The logic is a little confusing, but it breaks down into these cases.

 - If namespace = all, call indexer.List(), append matching pods to an empty PodList, then return.
 - Otherwise, call Index(NamespaceIndex, namespace).  If that succeeds, append matched pods to an empty PodList, then return.
 - If the Index() call failed, log a warning then fall back to indexer.List(), and append matching pods *to a PodList we don't clear first* (this time checking that they match both the namespace and the selector), then return.

In the third case, we assume that items is still empty and start appending to it.  That looks like a possible bug, but it's not the one I encountered here.  If it was, I'd see a "can not retrieve..." warning log line, and that line's nowhere in the logfile.

So, I don't think it's the locking problem, and I don't think it's this other possible bug.  I'll keep looking.

**Comment by mml** [comment]
OK, AFAICT the problem was with me, the caller.

Two bugs together hid this from me.  (1) I accidentally created a DisruptionBudget with an empty selector, which matched everything (should have been a validation failure *and* should probably have special logic to match nothing).  (2) I was reusing a pointer, so that if the DisruptionBudget matched N pods, I would get N copies of the same pod in my list.
