### ISSUE TITLE
node e2e flake: failed to initialize e2e tests using image

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#25713]
[Logs](https://00e9e64bacb99b30797b8fbdd2233cfcfc5508ffb429d7b7e1-apidata.googleusercontent.com/download/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F24016%2Fnode-pull-build-e2e-test%2F6243%2Fbuild-log.txt?qk=AD5uMEudCCk5x1Ei5cad2dfRspmdProNptmGJSw6vrXYSPwyLC5FKWXnvwfT1DvXi_ajz0vTt8G9Q2_o8AOi_G3riXrkocZJgSdmNnuIbdfPKsVs9WkDAyuk_jRzfLrD-aKALNKSZc8twDISA4U43iegMYuRpx0oyxus5S4mqK8a6ilzK_przi3AfJDYuS0O_ZEumPxRMUv6BwGKjetR2AIPTT5nntMnWygaMs41C346BI8IwcsmKFl7hJOIhGJ6CWEEL_xzcRQn-3NxWPll2Let9KAcHZcRxKqbP3ONBeBiUakZJcYS6Yir7NGLKAx0XP2MolCrtOdOXBGRxVhaxCqjl5A8QlpYEZHYSKL3elIAqCDevnux972mhohvfgl9hwHSMU5EjJCTIBh10vcLzQgDpoWHx1ZZCdemgV11ae5SOdnE9hLddEnebZe_kLyC8FJXv0XhjJSSLZlS292DVvVpIBHQ5F_7E9ac7Ptgd3MTb4jHknzP2sViKlxnwIc4Z6DWGAQzavAoyKFRyc4i0TzGAEqYJmhqKUcwJPBNnhK5iDsG6u8UyF2GvbuCUZSIGe6DAvVrjiy5sbg-Pr7QsKbK75T1FBbVvi6vVMMqjZaDDaBNiVSYFJDKJmnIWpflulUx7_WqpbKwokWt2YySLrXz4GGJRC16dhf1qMODpYIxptwu8A7YIQLRP3cuSeSAtBd1jsB6dlj88uhvnvTn8TkLZUwmduVUnSPwaMBxlnV2KVGpY9fJe0PicmhHk4I_BgN0ufd6s271tz1UzDonqzcO0AkPTlMO-qaxdLXqrMTtp0j4ybmjE4nN9QSfKLCQ20afl6HOayAphYYVST-0UHMRqv5_ZuTuvw)

```
Initializing e2e tests using image e2e-node-ubuntu-trusty-docker10-image.
Initializing e2e tests using image e2e-node-ubuntu-trusty-docker9-image.
Initializing e2e tests using image e2e-node-ubuntu-trusty-docker8-image.
Initializing e2e tests using image e2e-node-coreos-stable20160218-image.
Initializing e2e tests using image e2e-node-containervm-20160217-image.
================================================================
Failure Finished Host tmp-node-e2e-81450923-e2e-node-ubuntu-trusty-docker8-image Test Suite

Command [ssh -i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 tmp-node-e2e-81450923-e2e-node-ubuntu-trusty-docker8-image -- sh -c 'cd /tmp/gcloud-e2e-1011909081 && tar -xzvf ./e2e_node_test.tar.gz && ./e2e_node.test --logtostderr --v 2 --build-services=false --stop-services=false --node-name=tmp-node-e2e-81450923-e2e-node-ubuntu-trusty-docker8-image'] failed with error: exit status 2 and output:
Warning: Permanently added 'tmp-node-e2e-81450923-e2e-node-ubuntu-trusty-docker8-image' (ECDSA) to the list of known hosts.
./
./e2e_node.test
./kube-apiserver
./kubelet
```

cc @pwittrock @kubernetes/sig-node

**Comment by fejta** [comment]
assigning to @dchen1107 per team/node label
