### ISSUE TITLE
docker daemon rootfs does not exist

### ISSUE THREAD

**Issue by AaronTao1990** [kubernetes/kubernetes#25729]
After installing docker is just working fine and hello-world image runs ok as well. But when I tried to set up a separate “bootstrap” instance of the Docker daemon the hello-world procedure went wrong.

I am trying to set up k8s cluster environment bug got stuck on the first step. I referred to the tutorial in [Installing a Kubernetes Master Node via Docker](http://kubernetes.io/docs/getting-started-guides/docker-multinode/master/). 

Here is the first shell script:

```
sudo sh -c 'docker daemon -H unix:///var/run/docker-bootstrap.sock -p /var/run/docker-bootstrap.pid --iptables=false --ip-masq=false --bridge=none --graph=/var/lib/docker-bootstrap 2> /var/log/docker-bootstrap.log 1> /dev/null &'
```

After this I tried to run hello-world again with the following command:

```
[worker@103-32-121-sh-100-L09 ~]$ sudo docker -H unix:///var/run/docker-bootstrap.sock run hello-world
```

and here is the error:

```
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: rootfs (\"/var/lib/docker-bootstrap-new/devicemapper/mnt/feb2d63cb4d1119cf85c7b140acf344ff14f48ea1ab33732aa752b58d005c130/rootfs\") does not exist".
```

and here is the daemon startup log:

```
[worker@103-32-121-sh-100-L09 ~]$ cat /var/log/docker-bootstrap.log 
time="2016-05-17T16:54:09.166770136+08:00" level=info msg="previous instance of containerd still alive (25485)" 
time="2016-05-17T16:54:09.211061699+08:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section." 
time="2016-05-17T16:54:09.249240707+08:00" level=info msg="devmapper: Creating filesystem xfs on device docker-8:2-941302080-base" 
time="2016-05-17T16:54:09.412389141+08:00" level=info msg="devmapper: Successfully created filesystem xfs on device docker-8:2-941302080-base" 
time="2016-05-17T16:54:09.443867451+08:00" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2016-05-17T16:54:09.452249581+08:00" level=info msg="Firewalld running: false" 
time="2016-05-17T16:54:09.479355218+08:00" level=warning msg="mountpoint for pids not found" 
time="2016-05-17T16:54:09.479821075+08:00" level=info msg="Loading containers: start." 
time="2016-05-17T16:54:09.479888418+08:00" level=info msg="Loading containers: done." 
time="2016-05-17T16:54:09.479905263+08:00" level=info msg="Daemon has completed initialization" 
time="2016-05-17T16:54:09.479923187+08:00" level=info msg="Docker daemon" commit=5604cbe graphdriver=devicemapper version=1.11.1 
time="2016-05-17T16:54:09.536976600+08:00" level=info msg="API listen on /var/run/docker-bootstrap.sock" 
```

As you can see there are two warnings there.

Output of `Docker version`

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

Output of `Docker info`

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-8:2-1611963456-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 32.24 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.3 GB
 Metadata Space Used: 614.4 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 125.6 GiB
Name: 103-32-121-sh-100-L09.yidian.com
ID: QGSK:Z3ID:LBXX:V267:WREM:EENP:FHDG:QFMN:5OJZ:HZDX:INVQ:TWBU
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by Wenfeng-GAO** [comment]
I got exactly the same error when go through the tutorial.

    docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: rootfs (\"/var/lib/docker-bootstrap/devicemapper/mnt/8b34255bf18ae27be5f63452001f50a9a81a4fa7411ed862e16b8da72f52fdc0/rootfs\") does not exist".

I use the `master.sh` script on CentOS-7, the kernel is `3.10.0-327.el7.x86_64` and my `docker info` is

    Client:
    Version:      1.11.1
    API version:  1.23
    Go version:   go1.5.4
    Git commit:   5604cbe
    Built:        Wed Apr 27 00:34:42 2016
    OS/Arch:      linux/amd64

    Server:
    Version:      1.11.1
    API version:  1.23
    Go version:   go1.5.4
    Git commit:   5604cbe
    Built:        Wed Apr 27 00:34:42 2016
    OS/Arch:      linux/amd64

By the way, if we download the script directly from the [link](http://kubernetes.io/docs/getting-started-guides/docker-multinode/)(which is not the latest one on GitHub), we will get a version that miss an `"` on line 29

    # Make sure k8s version env is properly set
    K8S_VERSION=${K8S_VERSION:-"1.2.2}

**Comment by AaronTao1990** [comment]
@Wenfeng-GAO 

I found a similar issue in docker [#here](https://github.com/docker/docker/issues/22684)



And it is really confusing.


I downgrade the docker version to 1.11.0 and the problem is gone.

But still I can not figure out the real reason that causes the problem.




And here comes my new issue.. #25795

**Comment by Wenfeng-GAO** [comment]
Thanks, my case has been solved by add a line `--exec-root=/var/run/docker-bootstrap` in the bootstrap_daemon part in the master.sh script. Some thing like this:

    ${docker_daemon} \
        -H unix:///var/run/docker-bootstrap.sock \
        -p /var/run/docker-bootstrap.pid \
        --iptables=false \
        --ip-masq=false \
        --bridge=none \
	--exec-root=/var/run/docker-bootstrap \
        --graph=/var/lib/docker-bootstrap \
            2> /var/log/docker-bootstrap.log \
            1> /dev/null &

See [[1.11.1] Docker bootstrap: Cannot start a container because of oci runtime error. #22684](https://github.com/docker/docker/issues/22684), hope that work for you.
