### ISSUE TITLE
How to use rolling-update with restful api ?

### ISSUE THREAD

**Issue by luguangzhen** [kubernetes/kubernetes#25725]
When I use kubectl tool to rolling-update, everything is normal.
`kubectl rolling-update k8s-ru1 --image=xx:5000/k8s-ru2:latest`

However, follow the guide of kubernetes deployment to achieve rolling-update with the restful api **/apis/extensions/v1beta1/namespaces/bigdata/deployments**, there are 100+ pods created with Terminating status.

k8s-ru1-deployment-4284186922-03yrx                 0/1       Terminating   0          35s
k8s-ru1-deployment-4284186922-13utb                 0/1       Terminating   0          5s
k8s-ru1-deployment-4284186922-17ib8                 0/1       Terminating   0          1m
k8s-ru1-deployment-4284186922-1ymkk                 0/1       Terminating   0          35s
k8s-ru1-deployment-4284186922-21xf4                 0/1       Terminating   0          29s

The POST request body likes below:
```json
{
    "apiVersion": "extensions/v1beta1",
    "kind": "Deployment",
    "metadata": {
        "name": "k8s-ru1-deployment"
    },
    "spec": {
        "replicas": "2",
        "strategy": {
        	"rollingUpdate": {
            	"maxSurge": 5
            }
        },
        "template": {
            "metadata": {
                "labels": {
                    "name": "k8s-ru1"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "k8s-ru1",
                        "image": "xx:5000/k8s-ru2",
                        "ports": [
                            {
                                "containerPort": "8080"
                            }
                        ]
                    }
                ]
            }
        }
    }
}
```

**Comment by kargakis** [comment]
@luguangzhen what was the state of your deployment prior to the update? You only changed the image, right? Note that `kubectl set image` is on the way: https://github.com/kubernetes/kubernetes/pull/25509

cc: @kubernetes/deployment

**Comment by luguangzhen** [comment]
@kargakis Actually, I just want to change (or upgrade) the image with the restful api. That is to say, I just want to use restful API to achieve the operation of rolling-update.

**Comment by luguangzhen** [comment]
What I have done before is create pods by create a replicationController, then rolling-update pods by create a deployment, however it does not work.

This issue is sloved by creating a deployment, it create rs and pod automatically, then partially update this deployment with changing the image. The api of create deployment is `POST /apis/extensions/v1beta1/namespaces/{namespace}/deployments`, while `PATCH /apis/extensions/v1beta1/namespaces/{namespace}/deployments/{name}` is the api of update deployment. 
And the process of rolling-up seems OK. 

root@ubuntu:~# kubectl describe deployment k8s-ru5-deployment  
Name:                   k8s-ru5-deployment
Namespace:              default
CreationTimestamp:      Thu, 19 May 2016 18:59:29 +0800
Labels:                 name=k8s-ru5
Selector:               name=k8s-ru5
Replicas:               2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
OldReplicaSets:         <none>
NewReplicaSet:          k8s-ru5-deployment-3927409657 (2/2 replicas created)
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  7m            7m              1       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled up replica set k8s-ru5-deployment-3848635384 to 1
  7m            7m              1       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled down replica set k8s-ru5-deployment-3927409657 to 1
  7m            7m              1       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled down replica set k8s-ru5-deployment-3927409657 to 0
  **36m           37s             2       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled up replica set k8s-ru5-deployment-3927409657 to 1
  36m           37s             2       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled down replica set k8s-ru5-deployment-3848635384 to 1
  36m           37s             2       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled up replica set k8s-ru5-deployment-3927409657 to 2
  36m           29s             2       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled down replica set k8s-ru5-deployment-3848635384 to 0**

**Comment by ling2yt** [comment]
i try to update the deployment using the REST API: PATCH /apis/extensions/v1beta1/namespaces/{namespace}/deployments/{name}

can i test it with postman ?
and what the request body should be? the whole new yaml ?
