### ISSUE TITLE
Getting a Power CI for kubernetes

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#25730]
Hi all,

Since release 1.3.0-alpha3, gcr.io has all the images required to run k8s on powerpc architecture. It would be good to have a CI setup for power, so that future stuff doesn't break on it. How should I proceed with that? I have been told one way is to get the servers in CNCF, but again what would be the specs in that case? Alternatively who is the person to contact?

TIA.

cc: @luxas @bgrant0607 @roberthbailey @thockin

**Comment by roberthbailey** [comment]
You should chat with the @kubernetes/test-infra-maintainers folks.

**Comment by luxas** [comment]
First off, I'm obviously a huge +1 on this.

As the implementor of this feature, I would say that we have one important CI layer already: Does it compile on Power?

On every PR, k8s will be built for `arm`, `arm64` and `ppc64le`, and e2e will fail if the code doesn't compile on the given platform (example: earlier there were `+// build linux,amd64` in some places in the code, which broke all other platforms, and some other things as well I had to fix before I made the arm64 and ppc64le PR).

But although Go should produce next-to-identical code regardless of platform, bugs will sometimes show up, so it would also be good to have a nightly e2es (including windows when we get so far)

I think, however, that if we setup something in collaboration with CNCF or whoever, we should setup `arm` and `arm64` CIs as well.

BTW, I'm writing a proposal in the meantime about Kubernetes on different platforms. 
I'll cc you on it later

**Comment by luxas** [comment]
xref: #17981

**Comment by ixdy** [comment]
cc @kubernetes/sig-testing

**Comment by luxas** [comment]
@ixdy Opinions on this?

**Comment by ixdy** [comment]
I think it's a great idea, but (obviously) the challenge is getting hardware. I don't have any leads on that, but if anyone has hardware and wants to start running tests, we can definitely federate those results into our dashboards.

**Comment by bpradipt** [comment]
@ixdy if you can share  min spec of the hardware required for CI (cpu, mem, disk), we can take a look and come back with availability.

**Comment by seelam** [comment]
yes, we can get the hardware access, if we get the specs.

**Comment by ixdy** [comment]
I'm not sure if I'm the best person to answer that question.

For the majority of our CI testing on GCE, we use 3-node clusters:
* master: n1-standard-1 (1 vCPU, 3.75 GB ram), 20 GB SSD PD
* nodes (3): n1-standard-2 (2 vCPU, 7.5 GB ram), 100 GB non-SSD PD

For our larger-cluster tests, we use a larger master node. "Real" clusters have different sizes, too.

Our beefiest machines (with 32 vCPU) are those running builds and unit tests, but I don't imagine we need to do builds on `power` - that's what crossbuild is for.

I have no idea what's typical for non-GCE deployments. And I think the `arm` testing @luxas has been all single-machine using Docker, so he probably has a better idea of the specs there.

**Comment by ixdy** [comment]
@kubernetes/sig-testing have any opinions about usual hardware specs you use for clusters in CI testing?

**Comment by ixdy** [comment]
I'll also note that we have many CI clusters running simultaneously, but that level of parallelism/scale isn't strictly necessary. We can scale testing to as little or as much hardware as we have. Just running the conformance subset of tests somewhere semi-regularly would be a great start.

**Comment by luxas** [comment]
A nightly build shouldn't be so heavyweight imo

I haven't run `e2e` tests yet on the Raspberry Pi (issue #22876) , but I think it'll handle it (especially if it's 1-5 times a day)

For `arm64` @tianon recommends this one: https://github.com/docker/docker/pull/19013#issuecomment-171182828 :smile:

Of course, it's possible to run both `arm` and `arm64` binaries on an `arm64` board.
WDYT about arm CI @ixdy? That would be awesome!

But for `ppc64le`, we have to fix this issue first: #25886

**Comment by ixdy** [comment]
As noted in https://github.com/kubernetes/kubernetes/issues/25730#issuecomment-219794140, if anyone wants to run CI on these platforms, I'm happy to help get results federated in the test dashboards.

**Comment by ixdy** [comment]
(I know that "running CI" is not trivial right now. I'm hoping to make it simpler soon. @euank might be able to comment on the experience setting it up for CoreOS.)

**Comment by luxas** [comment]
So should the CI be run by community members, CNCF or Google?

**Comment by ixdy** [comment]
The Google test-infra team does not have the resources to maintain much beyond the GCE/GKE CI builds at the moment. ARM/Power will probably have to be owned by the community for the time being.

**Comment by luxas** [comment]
@ixdy Any details how to setup a CI cluster? Is it possible to run the CI on top of an existing Kubernetes cluster. If it is, it would be awesome, as I've already got an arm cluster, and it isn't hard to setup at all.

I.e. is all CI testing dockerized and automated?

After #25972 is in, about 30% of the conformance tests are passing

I ran this against a [docker-multinode](https://github.com/kubernetes/kube-deploy/tree/master/docker-multinode) cluster consisting of one machine only. Many of the test are failing because of the `SecurityContextDeny` admission controller, which is removed at HEAD, but not in the release I was testing against.

The mostly other things fail because the test is trying to use an amd64 image.
https://gist.github.com/luxas/effc8bdf5887666b047d79ad144ef593

Our next step with this should be to cross-build `gcr.io/google_containers/busybox` and `gcr.io/google_containers/nginx`, and that isn't hard at all.
But where is the source of those images?

**Comment by Pensu** [comment]
Now that #30659 is merged and ppc64le builds are disbaled because of golang issues. That golang issue might take some time to go into upstream, till that can we have a separate CI for ppc64le builds with patched golang?

CC: @ixdy @spxtr @david-mcmahon @luxas

**Comment by ixdy** [comment]
Is there documentation (or even better, a script?) for how to run a build with patched golang?

**Comment by Pensu** [comment]
@ixdy Yeah, I can provide a script. Do you want to cross compile or want to run it on ppc64le box? That can be arranged too.

**Comment by ixdy** [comment]
If we're going to build ppc64le binaries for official releases, we probably want a script for cross compilation. I'm not sure who's owning building ppc64le for CI. Google is currently owning the `make release` cross build, though it doesn't have ppc64le right now. We aren't doing any testing though, as you probably know.

**Comment by ixdy** [comment]
And our CI runs entirely on amd64.

**Comment by ixdy** [comment]
To be more decisive:  if `make release` did the right thing and built amd64, arm64, and ppc64le (as it used to), I would be happy.

**Comment by luxas** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/26863

First target is to actually make it possible to run the whole e2e infrastructure on amd64 on top of any Kubernetes cluster.
Second target is to cross-build all images needed for k8s-on-k8s testing
Third target is to make it possible for IBM to set up a ppc64le e2e testing k8s cluster and those results should show up on k8s-testgrid
Fourth target is to increase multi-arch coverage to 100% or at least 70-80% by cross-building images used for testing
Fifth target is to make Google run tests on physical (in this case ppc64le) machines, maybe donated by IBM

And right now we're on step zero; so we have a quite long way to go...

**Comment by kargakis** [comment]
@detiber

**Comment by mkumatag** [comment]
@luxas, @ixdy... All of the mentioned prereqs are met, now can you please let me know how can we proceed further to get ppc64le platform into CI setup to run conformance tests continuously?

> ref: #26863
> 
> First target is to actually make it possible to run the whole e2e infrastructure on amd64 on top of any Kubernetes cluster.
> Second target is to cross-build all images needed for k8s-on-k8s testing
> Third target is to make it possible for IBM to set up a ppc64le e2e testing k8s cluster and those results should show up on k8s-testgrid
> Fourth target is to increase multi-arch coverage to 100% or at least 70-80% by cross-building images used for testing
> Fifth target is to make Google run tests on physical (in this case ppc64le) machines, maybe donated by IBM
> 
> And right now we're on step zero; so we have a quite long way to go...

**Comment by luxas** [comment]
@mkumatag set up [federated testing](https://github.com/kubernetes/test-infra/blob/master/docs/federated_testing.md) from your clusters

**Comment by luxas** [comment]
This can be done with federated testing now, and is the recommended way. If you have a PowerPC cluster, you can run it using kubeadm, and submit the e2e results to testgrid. The k8s community is not gonna do it for you (as we don't have machines), but feel free to help out with this here :smile:
If you want to set up federated testing you can open an issue in test-infra to add the bucket, once you have results up. Thanks!
