### ISSUE TITLE
What is the current preferred way to implement a name-based ingress LB on Bare Metal?

### ISSUE THREAD

**Issue by dcowden** [kubernetes/kubernetes#25747]
For k8s clusters that are running on bare metal ( for example, on a single developer workstation), we need to implement a dynamic, ingress loadbalancer. 

Desired functionality:

1. map inbound host names, or contexts, to an internal service
2. automatically detect new backend services and reconfigure the proxy accordingly
3. use new ingress controllers, so that our production configuration is consistent with development
4. expose  a status page showing all of the backends and their status
5. do SSL termination, using different SSL certificates for the various host names.

I have found two possible solutions:

The 'service-loadbalancer' project here:
https://github.com/kubernetes/contrib/tree/master/service-loadbalancer

And the nginx-ingress-controller here:
https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx

**Question 1**:  Which of these is preferred, and why?  

**Question 2**: Is it possible with either solution to implement TLS termination on the loadbalancer, using different certificates for different host names?  I can see how to implement, for example, foo.example.com and bar.example.com, but how would i implement foo.blah.com and foo.bar.com?  It is possible to configure nginx to do this, but i cannot see how to configure an ingress to handle it, since each ingress can only have one TLS secret?

**Comment by luxas** [comment]
@bprashanth @aledbf

**Comment by aledbf** [comment]
@dcowden service-loadbalancer is not an Ingress controller so is not a "fair" comparison. With service-loadbalancer can accomplish point 2. If you use an Ingress controller you need to create one or more rules to route traffic. Both components provide an status page and SSL termination. The Ingress controller provides better granularity.

> Question 1:

It depends. It's easy to start with service-loadbalancer but once you need to control the path, use multiple certificates or multiples paths per hostname the nginx controller is what you need.

> Question 2:

yes, please check [this](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/multi-tls) example

**Comment by dcowden** [comment]
Thank you!  So it seems like the nginx-controller is the preferred solution.  
Thank you for the example link, that's perfect!
