### ISSUE TITLE
Cassandra Example Version Bump 3.4 to 3.5

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#25749]
https://github.com/kubernetes/kubernetes/commit/2c1149b09cd34444a48c961a67a039849a220cdd

Bumped the version to 3.5, but the SeedProvider is not at 3.5, as it is built against 3.4.  We either need to get the SeedProvider built against 3.5 or back this out.  An update to 3.5 could easily break this example.  I want to get the SeedProvider into the C* code base so this won't be an ongoing issue.

@bobintornado can you get the SeedProvider building against 3.5?

Here is the pom for the SeedProvider: https://github.com/kubernetes/kubernetes/blob/master/examples/cassandra/java/pom.xml

cc: @bgrant0607

**Comment by chrislovecnm** [comment]
cc: @kubernetes/examples

**Comment by chrislovecnm** [comment]
@bgrant0607 thoughts?

**Comment by bobintornado** [comment]
I see. I will try building SeedProvider against 3.5

**Comment by chrislovecnm** [comment]
Revert in progress https://github.com/kubernetes/kubernetes/pull/25785

**Comment by chrislovecnm** [comment]
PR https://github.com/kubernetes/kubernetes/pull/26022 bumps this up to 3.5
