### ISSUE TITLE
Disambiguate IP handling in Kubelet

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#25754]
There is a method called `GetContainerIP` which uses nsenter to do some work related to the name of the function.  Having spent some time working on downward API for pod IP, I found this method a bit confusing.  In general I feel like it would be helpful to disambiguate the handling of IPs in the kubelet, either in developer documentation or code comments.

@kubernetes/sig-node @kubernetes/sig-network

**Comment by ArtfulCoder** [comment]
@freehan since he is doing kubenet work.

**Comment by rinsu1987** [comment]
Can I start looking into this? Please assign it to me.
