### ISSUE TITLE
Passing k8s cluster credentials to federation control plane

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#25761]
We need a way to pass kubernetes cluster credentials to federation control plane (for it to be able to talk to each k8s cluster).

Right now, we have a string field called `Credential` in ClusterSpec (https://github.com/kubernetes/kubernetes/blob/4e6e51dc266030fa045ac10f0239e6da8d0acd08/federation/apis/federation/v1alpha1/types.go#L43) which admins are required to pass while registering a kubernetes cluster with the federation apiserver. Federation controllers are expected to use this value while talking to the k8s cluster. But a string field is not going to be enough.

Looking at how its done in kubernetes:
kube-controller-manager gets the path to kubeconfig file as a command line flag. It reads the credentials information from that file to create a client that can talk to the apiserver. (It uses the current context to decide on which apiserver it needs to talk to if there are multiple cluster infos in kubeconfig): https://github.com/kubernetes/kubernetes/blob/ee2a0694b649941fc0c3be606746db041b75b91d/cmd/kube-controller-manager/app/controllermanager.go#L121. 

Our options for what we can do in federation cluster API:
* We can use similar structs as used by kubeconfig in the ClusterSpec API object. These will be the Cluster and AuthInfo structs here:  https://github.com/kubernetes/kubernetes/blob/13a7d92d0f50e877edeb4225f73ae106b33bf152/pkg/client/unversioned/clientcmd/api/v1/types.go#L58
* We can add a field for path to kubeconfig file. This will require admins to copy their kubeconfig files from each k8s cluster to the server running federation api server.
* To allow admins to use a single unified kubeconfig file for all k8s clusters, we can also add a field for which context to use in the kubeconfig file along with its path.

The second option should require the least amount of changes since there is already code to create a client given path to kubeconfig file.

@quinton-hoole @lavalamp @roberthbailey @kubernetes/sig-cluster-federation thoughts?

**Comment by lavalamp** [comment]
I think the credential string is totally wrong, and should be removed. Creds should *not* be stored there. Let's think about the use case-- people are going to run an ubernetes shard in a kubernetes cluster. The mechanism we have for giving secret config data is via a secret. You should probably engineer this to work well with a secret. So instead of a "Credential" field, consider a secret ref.

It's still a bit awkward, since the clusters could come and go dynamically. You can't be reading and writing disk files, that will be difficult to manage. So I think you need to watch these objects and get the secrets manually when they change, and store them in memory.

As for what should be stored in the secrets, a kubeconfig file is the obvious option. Or you could look at the service account secret which we give to pods in a cluster for introspection, and do the same thing that does (which may only work for tokens, so it may not work if you want to do client cert).

You also need to consider and define the ubernetes' cluster's identity, and the federated clusters must all know this and accept it...

**Comment by nikhiljindal** [comment]
How much work do you think will it be for using secrets?

How about changing the string field to kubeconfig path so that it atleast works (in 1.3). And then we improve it by using secrets (post 1.3)?

cc @colhom @jianhuiz @huangyuqi @mfanjie

**Comment by lavalamp** [comment]
I don't think a static kubeconfig path is a great idea, since to use it
you'll have to change what's mounted inside the ubernetes control plane
every time you add or remove a kubernetes cluster.

**Comment by nikhiljindal** [comment]
Yea :)

Am wondering how will the federation controller manager access these secrets.
The standard way is to refer the secrets that a pod needs in the PodSpec (and secrets need to be created before pod is created). In this case, federation controller manager will need access to secrets dynamically.
One way can be by using InClusterConfig in federation controller manager to talk to the k8s apiserver that is running it as a pod and get the secret from it.

But am not sure if anyone can access any secret from the apiserver?
What access constraints are we planning to add in the future, that might break this?
Will we have to require admins to create the secrets in the same namespace as the one that contains federation control plane components?

And how will this work when we have federation control plane components in multiple k8s clusters (HA)? Will the admin have to create the secret in all k8s clusters?

cc @kubernetes/sig-auth

**Comment by nikhiljindal** [comment]
c @smarterclayton

**Comment by smarterclayton** [comment]
Secrets definitely will be limited.  And yes, they will be namespace scoped where possible.

It's useful to think about capabilities - if every cluster needs access to every other cluster's secrets, we have a challenge that a compromise of any cluster is a compromise of all clusters.  The answer to that is usually that if you care about that, you limit the access the federated API server has (so it acts as a regular user, with limited roles and quotas).  In that mode, the secrets are limited in scope.

One path would be to keep secret injection into the pod, but do it via a convention.  I.e. have a config directory which is a set of kube config files - one for each cluster (or one with multiple clusters if necessary).  Then inject the secrets into that directory or subdirectory and have the federated API server scan them.  I think that approach has some limitations as identified by Dan.  

The alternative is to put those secrets into the federated controller itself - so having federated secrets just like individual clusters have secrets.

**Comment by nikhiljindal** [comment]
Discussed this with @erictune and here is one way this can work:
* Federation control plane can get secrets containing kubeconfig for each k8s cluster using the apiserver of the "bootstrap k8s cluster". bootstrap k8s cluster is the k8s cluster on which the federation control plane pods are running. This is special since the federation control plane pods can access this apiserver with just the default service account (doesnt need any special secrets / service accounts)
* To add a k8s cluster to federation, admin first creates a secret in the bootstrap k8s cluster. That secret contains the kubeconfig for that k8s cluster. Admin then creates the Cluster object in federation apiserver. As part of ClusterSpec, admin mentions the secretRef. federation controller manager uses this secretRef to get the kubeconfig to talk to the k8s apiserver.
* federation controller manager can just get secrets on the bootstrap k8s apiserver using the default service account.

This way, we do not need any directory/file handling. But it does have the problem that the bootstrap k8s cluster has secrets for accessing all k8s clusters. We can mitigate this by having a separate bootstrap k8s cluster whose only job is to host the federation control plane and then restrict access to that.

**Comment by quinton-hoole** [comment]
@nikhiljindal As discussed, SGTM.

**Comment by lavalamp** [comment]
I argued that these secrets really must be stored in the federation's control plane, NOT the individual kubernetes cluster's control plane. I consider this a very basic requirement. @nikhiljindal promised me he'll move it there in the future.

**Comment by nikhiljindal** [comment]
Yes. Thanks for summarizing our discussion @lavalamp. I will move it to federation control plane when we start supporting secrets there.
