### ISSUE TITLE
"Simple pod should support exec through an HTTP proxy" test fails on kernel 4.4.4+

### ISSUE THREAD

**Issue by andyzheng0831** [kubernetes/kubernetes#25778]
Our Jenkins running on the GCI with kernel 4.4.4 captured this failure. The root cause is that test code always uploads linux/386 platform kubectl to a pod for test (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubectl.go#l301). This version works well on kernel 3.18, but fails on 4.4.4 because of modify_ldt call. Here is the information captured by strace:

execve("./kubectl-386", ["./kubectl-386", "--kubeconfig=./config", "--server=https://130.211.132.11:"..., "get", "nodes"], [/* 16 vars */]) = 0
[ Process PID=1211 runs in 32 bit mode. ]
modify_ldt(1, {entry_number:7, base_addr:0x94da788, limit:1048575, seg_32bit:1, contents:0, read_exec_only:0, limit_in_pages:1, seg_not_present:0, useable:1}, 16) = -1 ENOSYS (Function not implemented)
--- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL} ---
+++ killed by SIGTRAP +++
Trace/breakpoint trap

The issue is reproducible even running the binary directly in the instance, instead of a pod. I think the test case should be smarter than always using linux/386 version kubectl. 

@dchen1107 @roberthbailey @fabioy , I will patch the test code to make it work on the latest GCI (we can always use amd64 for GCI). For long-term fix, please feel free to assign it to a suitable person.

cc/ @kubernetes/goog-image FYI

**Comment by andyzheng0831** [comment]
@ixdy FYI

**Comment by adityakali** [comment]
Note that this is just because CONFIG_MODIFY_LDT_SYSCALL is not set for GCI. Not specifically related to the particular kernel version.

**Comment by andyzheng0831** [comment]
It was set in previous GCI kernel 3.18? Or this is a new kernel flag? Why
not turn it on, if it is on in other distros?
