### ISSUE TITLE
Why expose OutOfDisk condition by default?

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#25773]
Kubelet currently exposes `OutOfDisk` condition with `Status` set to `false` by default. Why expose that condition unless OutOfDisk condition was observed?

cc @dchen1107 @bgrant0607

**Comment by bgrant0607** [comment]
Why not?

It also might be nicer for clients to flip the polarity to match Ready, say SufficientDisk, in which case being present all the time makes more sense.

For scheduling, we may also want something to translate explicitly these to taints, so that it could respond generically:
https://github.com/kubernetes/kubernetes/blob/master/docs/design/taint-toleration-dedicated.md

**Comment by vishh** [comment]
So would that mean we ideally want to expose all Node Conditions by default even when they are false?

**Comment by bgrant0607** [comment]
Such as node problems?

Maybe Ready needs to be special because it lets us know whether we can trust any other information

**Comment by vishh** [comment]
[MemoryPressure](
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1893)
and other node problems...

At the least, we can avoid showing `false` conditions by default in
`kubectl describe nodes`

**Comment by bgrant0607** [comment]
Except for Ready=false

**Comment by vishh** [comment]
Oh yeah. Thats right!

**Comment by Random-Liu** [comment]
After introducing node problem detector #23028, there may be much more node conditions than today. Most of them will only exist when there is corresponding node problem daemon running.
Then for a node problem related condition, there could be 3 states:
* True
* False
* Not monitored at all.

If so, keeping the false condition is necessary. :)
However it is annoying to have a long list conditions when describe node, so +1 for https://github.com/kubernetes/kubernetes/issues/25773#issuecomment-219881281.

**Comment by lukaszo** [comment]
Looks simply enough for the k8s beginner. If you don't mind I can work on it

**Comment by derekwaynecarr** [comment]
@vishh - I would prefer we keep showing all node conditions, not just those that are true.  It's useful to see information about the LastTransitionTime even when a condition is currently displaying false.  What is the concern in having the information displayed?

**Comment by lukaszo** [comment]
`copy paste from PR` I may add a flag to kubectl to show all conditions. Will it be enough for you?

**Comment by derekwaynecarr** [comment]
We did a similar flag for events (i.e. --show-events) but that at least was common to all things described.  To be honest, I am not sure the list of conditions are really the problem if we are worried about verbosity of output since they do a good job giving an overview on health of the node.  The pod list is way more exhaustive...

**Comment by vishh** [comment]
@derekwaynecarr Acknowledged. The goal was to define a policy for kubelet and make kubectl user-friendly. When I view the node conditions via kubectl, the fact that I have to look at their Status is not obvious from kubectl. As a user why would I care about non-critical conditions? If necessary, we can add an optional flag to dump `false` conditions as well in kubectl.

IIUC, the summary is as follows:
* Kubelet will expose all conditions by default, even if they are `false`, to allow API clients to observe edge transitions.
* kubectl will not display `false` conditions by default. TBD: a flag to `kubectl describe` expose all conditions on demand.

**Comment by lukaszo** [comment]
I added to my PR new commit https://github.com/kubernetes/kubernetes/pull/25877
It adds flag --show-all so it can be reused with other `kubectl describe` resources. What do you think about this approach?

**Comment by jlowdermilk** [comment]
IMO a flag for showing all conditions isn't necessary. `kubectl describe` is already a cherrypicked selection of info that is intended to be 'just the important bits'. If you want everything you can dump yaml with `kubectl get nodes $nodename -o yaml`.

**Comment by derekwaynecarr** [comment]
@vishh - the assumption is that all node conditions should correspond to problem states, and therefore `True` corresponds to a problem always.  Of course, ready is not this way today.  I would prefer that we state this assumption in api-conventions and that we change `Ready` to `NotReady` if we wanted to pursue this.  I tried to look at the list of conditions that will be reported in the `node-problem-detector` - it looks like https://github.com/kubernetes/node-problem-detector/blob/master/config/kernel-monitor.json the current listing follows that convention.

**Comment by derekwaynecarr** [comment]
I don't want to be the hold out, its a shame `Ready` has the wrong polarity.  I am fine with this if we document the convention.  I know I would miss it in code reviews.

**Comment by vishh** [comment]
@derekwaynecarr +1 for documentation. The purpose of this issue was to figure out a convention. 
@bgrant0607 Any objections towards treating Node Conditions as `problem` states? 

As for `Ready`, we can also have `kubectl describe` treat it as a special case for now, by outputting a custom string instead of the Condition itself.

**Comment by Random-Liu** [comment]
> it looks like https://github.com/kubernetes/node-problem-detector/blob/master/config/kernel-monitor.json the current listing follows that convention.

Yeah, all conditions reported by node-problem-detector should be a permanent problem, `Status=True` means the problem happened, while `Status=False` means not happened.

**Comment by dchen1107** [comment]
+1 for document for now. 

I am ok to make one:one mapping between node condition to problem state in next release or later. But before to do that, we need to change today's ready condition which hides several problem states: runtime, network configuration, etc. Then we need to push today's logic of readiness in kubelet code to node controller / remedy controller.

**Comment by Random-Liu** [comment]
> we need to change today's ready condition which hides several problem states: runtime, network configuration, etc. Then we need to push today's logic of readiness in kubelet code to node controller / remedy controller.

Strongly +1. :)

**Comment by dchen1107** [comment]
re: https://github.com/kubernetes/kubernetes/issues/25773#issuecomment-219966814

We should well defined those problem related node condition, not like what we had today with NodeProblemDetector because 

1) We want scheduler only understands taints, neither condition nor events. 
2) Remedy controller / node controller will take action on those conditions. To do that, the conditions have to be pre-defined.

**Comment by liggitt** [comment]
> @dchen1107:
> 1) We want scheduler only understands taints, neither condition nor events. 

fyi, https://github.com/kubernetes/kubernetes/pull/36210 just updated scheduler to gate on all conditions

> 2) Remedy controller / node controller will take action on those conditions. To do that, the conditions have to be pre-defined. 

does that mean the node has to be aware of and responsible for setting initial state on all conditions? https://github.com/kubernetes/kubernetes/pull/36209 is wanting to set additional custom conditions at Node creation time

**Comment by dchen1107** [comment]
re: https://github.com/kubernetes/kubernetes/issues/25773#issuecomment-262025672

> fyi, https://github.com/kubernetes/kubernetes/pull/36210 just updated scheduler to gate on all conditions, need to decide if we're ok with that for 1.5

For Core Conditions pre-defined in the API, I think the change made in #36210 should be fine for 1.5.  But obviously the user can update the node object with new condition, #36210 changed the semantics and behavior of the scheduler upon these logic. I think we should revert that pr avoid a regression.

Again, we should have a plan to deprecate problem-related NodeConditions to Taints as discussed in https://github.com/kubernetes/kubernetes/issues/23028#issuecomment-215578728. 

> does that mean the node has to be aware of and responsible for setting initial state on all conditions? https://github.com/kubernetes/kubernetes/pull/36209 is wanting to set additional custom conditions at Node creation time.

No. Eventually Condition should be information-only, not for decision-making. Once Taint is in beta, we should convert all well-defined conditions to taints, including Ready.

**Comment by liggitt** [comment]
> Once Taint is in beta, we should convert all well-defined conditions to taints, including Ready.

That seems reasonable, though I'm wondering which component is responsible for setting taints on new Node objects (sort of the equivalent of "Unknown" state of custom conditions)? If we wanted new nodes to show up as unschedulable until some outside controller removed a taint, how do we ensure the taints are present as soon as the node is created to avoid the node being briefly schedulable?

**Comment by bgrant0607** [comment]
@liggitt Re. how to apply taints

The obvious options are:
1. Initializers
2. New node policy resource
3. Kubelet

@davidopp, what mechanism do we plan to use to add custom node labels and custom compute resources?

**Comment by bgrant0607** [comment]
Flag / config field for an admission controller as in #36209 could be another approach, but I'm not keen to hide that kind of policy in component configuration.

**Comment by davidopp** [comment]
> No. Eventually Condition should be information-only, not for decision-making. Once Taint is in beta, we should convert all well-defined conditions to taints, including Ready.

Yes, I agree this is the plan.

> If we wanted new nodes to show up as unschedulable until some outside controller removed a taint, how do we ensure the taints are present as soon as the node is created to avoid the node being briefly schedulable?

#31647
