### ISSUE TITLE
Fix how revisions are sorted in kubectl rollout history

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25788]
Ref https://github.com/kubernetes/kubernetes/issues/24858#issue-151367079 and https://github.com/kubernetes/kubernetes/issues/24858#issuecomment-219210074
`kubectl rollout history` should sort revisions correctly (10 should be after 9, not 1).

@kubernetes/kubectl @kargakis

**Comment by dshulyak** [comment]
I can help with this bug. Looks like trivial fix in PrintRolloutHistory

**Comment by janetkuo** [comment]
Thanks

**Comment by krmayankk** [comment]
@dshulyak are you still taking care of this one ? I am searching for some easy to do PR to just get familiar with the process and put my first PR in.

**Comment by dshulyak** [comment]
@krmayankk I created pr some time ago to close this issue #25802

**Comment by krmayankk** [comment]
@dshulyak great thanks :-)

**Comment by janetkuo** [comment]
@krmayankk you can look for help-wanted issues https://github.com/kubernetes/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Ahelp-wanted
or check https://github.com/kubernetes/community/wiki/Roadmap:-kubectl and https://github.com/kubernetes/community/wiki/Roadmap:-Deployment

**Comment by krmayankk** [comment]
@janetkuo thanks
