### ISSUE TITLE
Failed to get api server running

### ISSUE THREAD

**Issue by AaronTao1990** [kubernetes/kubernetes#25795]
I am trying to set up a k8s cluster via docker and followed the tutorial [here](http://kubernetes.io/docs/getting-started-guides/docker-multinode/master/)

And failed to get the api server run when I came to the last step. Below is the log from k8s.

PS. I tried to do the same thing with tutorial [here](http://kubernetes.io/docs/getting-started-guides/docker/), which is much more clear and simple. But got the same error output saying that api server is not working.

Any kind of help will be appreciated. :)	
	
	
	
	I0518 09:11:02.035772   34396 server.go:140] Running kubelet in containerized mode (experimental)
	W0518 09:11:02.320674   34396 server.go:449] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
	W0518 09:11:02.320697   34396 server.go:410] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
	I0518 09:11:02.320824   34396 plugins.go:71] No cloud provider specified.
	I0518 09:11:02.320832   34396 server.go:316] Successfully initialized cloud provider: "" from the config file: ""
	I0518 09:11:02.321057   34396 manager.go:132] cAdvisor running in container: "/system.slice/docker-6d0d68eb72597e13153ec38c4a8d562c6b4efe37360e6726896058f4dd771b10.scope"
	I0518 09:11:02.487522   34396 fs.go:109] Filesystem partitions: map[/dev/mapper/docker-8:2-1208543372-9fbc2da541cf3777ee03ef8c67a24c4c21ee726c818a7e5a6f45a30a60b8af45:{mountpoint:/rootfs/var/lib/docker-bootstrap/devicemapper/mnt/9fbc2da541cf3777ee03ef8c67a24c4c21ee726c818a7e5a6f45a30a60b8af45 major:253 minor:2 fsType: blockSize:0} /dev/mapper/docker-8:2-382038-6d0d68eb72597e13153ec38c4a8d562c6b4efe37360e6726896058f4dd771b10:{mountpoint:/ major:253 minor:4 fsType: blockSize:0} /dev/sda2:{mountpoint:/rootfs major:8 minor:2 fsType: blockSize:0} /dev/sda1:{mountpoint:/rootfs/boot major:8 minor:1 fsType: blockSize:0} /dev/mapper/docker-8:2-1208543372-430314ecf4c4af2fdc64b05780f8af233fad91c8d55a38606bdf8d0d0e4a291d:{mountpoint:/rootfs/var/lib/docker-bootstrap/devicemapper/mnt/430314ecf4c4af2fdc64b05780f8af233fad91c8d55a38606bdf8d0d0e4a291d major:253 minor:0 fsType: blockSize:0}]
	I0518 09:11:04.498180   34396 manager.go:169] Machine: {NumCores:32 CpuFrequency:2400000 MemoryCapacity:134896713728 MachineID:77d7d9bd15824975b1e31bdd86206ec2 SystemUUID:37353532-3538-3643-5536-303857343558 BootID:625f3b13-06b5-42a2-aa30-95e7edd5f514 Filesystems:[{Device:/dev/sda1 Capacity:829685760 Type:vfs Inodes:817152} {Device:/dev/mapper/docker-8:2-1208543372-430314ecf4c4af2fdc64b05780f8af233fad91c8d55a38606bdf8d0d0e4a291d Capacity:10725883904 Type:vfs Inodes:10484736} {Device:/dev/mapper/docker-8:2-1208543372-9fbc2da541cf3777ee03ef8c67a24c4c21ee726c818a7e5a6f45a30a60b8af45 Capacity:10725883904 Type:vfs Inodes:10484736} {Device:/dev/mapper/docker-8:2-382038-6d0d68eb72597e13153ec38c4a8d562c6b4efe37360e6726896058f4dd771b10 Capacity:10725883904 Type:vfs Inodes:10484736} {Device:/dev/sda2 Capacity:294686031872 Type:vfs Inodes:287920128}] DiskMap:map[253:2:{Name:dm-2 Major:253 Minor:2 Size:10737418240 Scheduler:none} 253:3:{Name:dm-3 Major:253 Minor:3 Size:107374182400 Scheduler:none} 253:4:{Name:dm-4 Major:253 Minor:4 Size:10737418240 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:299966445568 Scheduler:deadline} 253:0:{Name:dm-0 Major:253 Minor:0 Size:10737418240 Scheduler:none} 253:1:{Name:dm-1 Major:253 Minor:1 Size:107374182400 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:14:02:ec:3e:d5:c0 Speed:1000 Mtu:9000} {Name:eth1 MacAddress:5c:b9:01:95:ba:f0 Speed:0 Mtu:1500} {Name:eth2 MacAddress:14:02:ec:3e:d5:c1 Speed:1000 Mtu:1500} {Name:eth3 MacAddress:5c:b9:01:95:ba:f1 Speed:0 Mtu:1500} {Name:eth4 MacAddress:14:02:ec:3e:d5:c2 Speed:0 Mtu:1500} {Name:eth5 MacAddress:5c:b9:01:95:ba:f2 Speed:0 Mtu:1500} {Name:eth6 MacAddress:14:02:ec:3e:d5:c3 Speed:0 Mtu:1500} {Name:eth7 MacAddress:5c:b9:01:95:ba:f3 Speed:0 Mtu:1500} {Name:flannel0 MacAddress: Speed:10 Mtu:8972}] Topology:[{Id:0 Memory:68587696128 Cores:[{Id:0 Threads:[0 16] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[1 17] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:2 Threads:[2 18] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:3 Threads:[3 19] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[4 20] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:5 Threads:[5 21] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:6 Threads:[6 22] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:7 Threads:[7 23] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]} {Id:1 Memory:68719476736 Cores:[{Id:0 Threads:[8 24] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[9 25] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:2 Threads:[10 26] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:3 Threads:[11 27] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[12 28] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:5 Threads:[13 29] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:6 Threads:[14 30] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:7 Threads:[15 31] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
	I0518 09:11:04.499760   34396 manager.go:175] Version: {KernelVersion:3.10.0-327.10.1.el7.x86_64 ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.9.0 CadvisorVersion: CadvisorRevision:}
	I0518 09:11:04.500943   34396 server.go:348] Using root directory: /var/lib/kubelet
	I0518 09:11:04.501174   34396 server.go:678] Adding manifest file: /etc/kubernetes/manifests-multi
	I0518 09:11:04.501417   34396 file.go:47] Watching path "/etc/kubernetes/manifests-multi"
	I0518 09:11:04.501433   34396 server.go:688] Watching apiserver
	W0518 09:11:04.510001   34396 kubelet.go:516] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
	I0518 09:11:04.510040   34396 kubelet.go:381] Hairpin mode set to "hairpin-veth"
	I0518 09:11:04.673903   34396 manager.go:224] Setting dockerRoot to /var/lib/docker
	I0518 09:11:04.675590   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/aws-ebs"
	I0518 09:11:04.675626   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/empty-dir"
	I0518 09:11:04.675644   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/gce-pd"
	I0518 09:11:04.675658   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/git-repo"
	I0518 09:11:04.675673   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/host-path"
	I0518 09:11:04.675686   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/nfs"
	I0518 09:11:04.675702   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/secret"
	I0518 09:11:04.675719   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/iscsi"
	I0518 09:11:04.675737   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/glusterfs"
	I0518 09:11:04.675754   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/persistent-claim"
	I0518 09:11:04.675769   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/rbd"
	I0518 09:11:04.675785   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/cinder"
	I0518 09:11:04.675801   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/cephfs"
	I0518 09:11:04.675818   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/downward-api"
	I0518 09:11:04.675833   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/fc"
	I0518 09:11:04.675846   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/flocker"
	I0518 09:11:04.675859   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/azure-file"
	I0518 09:11:04.675873   34396 plugins.go:291] Loaded volume plugin "kubernetes.io/configmap"
	I0518 09:11:04.676254   34396 server.go:650] Started kubelet v1.3.0-alpha.3.0+95f2ca2ff65a03
	E0518 09:11:04.676424   34396 kubelet.go:968] Image garbage collection failed: unable to find data for container /
	I0518 09:11:04.676449   34396 server.go:134] Starting to listen read-only on 0.0.0.0:10255
	I0518 09:11:04.676449   34396 server.go:117] Starting to listen on 0.0.0.0:10250
	E0518 09:11:04.684913   34396 event.go:207] Unable to write event: 'Post http://localhost:8080/api/v1/namespaces/default/events: dial tcp 127.0.0.1:8080: getsockopt: connection refused' (may retry after sleeping)
	I0518 09:11:04.686282   34396 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
	I0518 09:11:04.686315   34396 manager.go:123] Starting to sync pod status with apiserver
	I0518 09:11:04.686348   34396 kubelet.go:2390] Starting kubelet main sync loop.
	I0518 09:11:04.686359   34396 kubelet.go:2399] skipping pod synchronization - [container runtime is down]
	I0518 09:11:04.869601   34396 kubelet.go:2791] Recording NodeHasSufficientDisk event message for node 127.0.0.1
	I0518 09:11:04.869660   34396 kubelet.go:1146] Attempting to register node 127.0.0.1
	I0518 09:11:04.877978   34396 kubelet.go:1149] Unable to register 127.0.0.1 with the apiserver: Post http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	I0518 09:11:04.894209   34396 factory.go:233] Registering Docker factory
	I0518 09:11:04.901467   34396 factory.go:97] Registering Raw factory
	I0518 09:11:05.074142   34396 manager.go:1003] Started watching for new ooms in manager
	I0518 09:11:05.076413   34396 oomparser.go:182] oomparser using systemd
	I0518 09:11:05.077671   34396 manager.go:256] Starting recovery of all containers
	I0518 09:11:05.098328   34396 kubelet.go:2791] Recording NodeHasSufficientDisk event message for node 127.0.0.1
	I0518 09:11:05.098390   34396 kubelet.go:1146] Attempting to register node 127.0.0.1
	I0518 09:11:05.101749   34396 kubelet.go:1149] Unable to register 127.0.0.1 with the apiserver: Post http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	I0518 09:11:05.181769   34396 manager.go:261] Recovery completed
	E0518 09:11:05.215095   34396 event.go:207] Unable to write event: 'Post http://localhost:8080/api/v1/namespaces/default/events: dial tcp 127.0.0.1:8080: getsockopt: connection refused' (may retry after sleeping)
	I0518 09:11:05.514549   34396 kubelet.go:2791] Recording NodeHasSufficientDisk event message for node 127.0.0.1
	I0518 09:11:05.514593   34396 kubelet.go:1146] Attempting to register node 127.0.0.1
	I0518 09:11:05.518478   34396 kubelet.go:1149] Unable to register 127.0.0.1 with the apiserver: Post http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	I0518 09:11:06.329757   34396 kubelet.go:2791] Recording NodeHasSufficientDisk event message for node 127.0.0.1
	I0518 09:11:06.329793   34396 kubelet.go:1146] Attempting to register node 127.0.0.1
	I0518 09:11:06.333628   34396 kubelet.go:1149] Unable to register 127.0.0.1 with the apiserver: Post http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	I0518 09:11:07.944776   34396 kubelet.go:2791] Recording NodeHasSufficientDisk event message for node 127.0.0.1
	I0518 09:11:07.944832   34396 kubelet.go:1146] Attempting to register node 127.0.0.1
	I0518 09:11:07.948688   34396 kubelet.go:1149] Unable to register 127.0.0.1 with the apiserver: Post http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	I0518 09:11:09.686882   34396 kubelet.go:2422] SyncLoop (ADD, "file"): "k8s-proxy-127.0.0.1_kube-system(2cc95e9e633f16928358b2f369ff5c37), k8s-master-127.0.0.1_kube-system(10253ae01cb59696c7ffc32084001d23)"
	I0518 09:11:09.698046   34396 kubelet.go:2791] Recording NodeHasSufficientDisk event message for node 127.0.0.1
	E0518 09:11:09.702971   34396 kubelet.go:1777] Failed creating a mirror pod for "k8s-proxy-127.0.0.1_kube-system(2cc95e9e633f16928358b2f369ff5c37)": Post http://localhost:8080/api/v1/namespaces/kube-system/pods: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	W0518 09:11:09.703049   34396 manager.go:408] Failed to update status for pod "_()": Get http://localhost:8080/api/v1/namespaces/kube-system/pods/k8s-proxy-127.0.0.1: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	I0518 09:11:09.703099   34396 manager.go:1693] Need to restart pod infra container for "k8s-proxy-127.0.0.1_kube-system(2cc95e9e633f16928358b2f369ff5c37)" because it is not found
	I0518 09:11:09.779929   34396 provider.go:115] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
	I0518 09:11:09.780340   34396 docker.go:165] Pulling image gcr.io/google_containers/pause:2.0 without credentials
	I0518 09:11:09.787118   34396 kubelet.go:2791] Recording NodeHasSufficientDisk event message for node 127.0.0.1
	E0518 09:11:09.791786   34396 kubelet.go:1777] Failed creating a mirror pod for "k8s-master-127.0.0.1_kube-system(10253ae01cb59696c7ffc32084001d23)": Post http://localhost:8080/api/v1/namespaces/kube-system/pods: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	W0518 09:11:09.791869   34396 manager.go:408] Failed to update status for pod "_()": Get http://localhost:8080/api/v1/namespaces/kube-system/pods/k8s-master-127.0.0.1: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	I0518 09:11:09.821858   34396 manager.go:1693] Need to restart pod infra container for "k8s-master-127.0.0.1_kube-system(10253ae01cb59696c7ffc32084001d23)" because it is not found
	I0518 09:11:11.160083   34396 kubelet.go:2791] Recording NodeHasSufficientDisk event message for node 127.0.0.1
	I0518 09:11:11.160126   34396 kubelet.go:1146] Attempting to register node 127.0.0.1
	I0518 09:11:11.163926   34396 kubelet.go:1149] Unable to register 127.0.0.1 with the apiserver: Post http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	W0518 09:11:14.690397   34396 manager.go:408] Failed to update status for pod "_()": Get http://localhost:8080/api/v1/namespaces/kube-system/pods/k8s-proxy-127.0.0.1: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	W0518 09:11:14.693950   34396 manager.go:408] Failed to update status for pod "_()": Get http://localhost:8080/api/v1/namespaces/kube-system/pods/k8s-master-127.0.0.1: dial tcp 127.0.0.1:8080: getsockopt: connection refused
	E0518 09:11:15.219325   34396 event.go:207] Unable to write event: 'Post http://localhost:8080/api/v1/namespaces/default/events: dial tcp 127.0.0.1:8080: getsockopt: connection refused' (may retry after sleeping)
	I0518 09:11:17.574738   34396 kubelet.go:2791] Recording NodeHasSufficientDisk event message for node 127.0.0.1
	I0518 09:11:17.574779   34396 kubelet.go:1146] Attempting to register node 127.0.0.1
	I0518 09:11:17.578582   34396 kubelet.go:1149] Unable to register 127.0.0.1 with the apiserver: Post http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: getsockopt: connection refused

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by Madhav1217** [comment]
hi frds i tried kubernetes deployment in jenkins via terraform file i got error please help me
04:42:20 * kubernetes_deployment.polaris-administration: Failed to create deployment: Post http://localhost/apis/apps/v1/namespaces/default/deployments: dial tcp [::1]:80: connect: connection refused
