### ISSUE TITLE
unit/integration flake: No test results found

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#25791]
My PR #25024 failed for `Jenkins unit/integration — No test results found.` @vishh once helped to trigger the test again, but failure still exists.

#25674 reports a similar problem `Jenkins GCE e2e — No test results found.`

I also find that several PRs have the same unit/integration flake: #25737, #25771, etc.

@lavalamp would you please help to check this? Thanks!

The build-log is shown as below:

https://console.cloud.google.com/m/cloudstorage/b/kubernetes-jenkins/o/pr-logs/pull/25024/kubernetes-pull-test-unit-integration/25017/build-log.txt

```
+++ [0509 13:06:26] Placing binaries
SUCCESS  ./hack/../hack/verify-symbols.sh	38s
Verifying ./hack/../hack/verify-flags-underscore.py
SUCCESS  ./hack/../hack/verify-flags-underscore.py	28s
Build step 'Execute shell' marked build as failure
Recording test results
ERROR: Step 鈥楶ublish JUnit test result report鈥� failed: No test report files were found. Configuration error?
[PostBuildScript] - Execution post build scripts.
[kubernetes-pull-test-unit-integration@2] $ /bin/bash -xe /tmp/hudson5373222481076070063.sh
+ [[ -x ./hack/jenkins/upload-to-gcs.sh ]]
+ ./hack/jenkins/upload-to-gcs.sh
Called without JENKINS_BUILD_STARTED or JENKINS_BUILD_FINISHED set.
Assuming a legacy invocation.
Run finished at Mon May  9 13:06:58 PDT 2016
Uploading to gs://kubernetes-jenkins/pr-logs/pull/25024/kubernetes-pull-test-unit-integration/25017 (attempt 1)
Uploading build result: [UNSET]
Marking build 25017 as the latest completed build
```

**Comment by xiangpengzhao** [comment]
The build log also shows 
```
Verifying ./hack/../hack/verify-gofmt.sh
!!! 'gofmt -s' needs to be run on the following files: 
./pkg/kubelet/dockertools/docker.go
FAILED   ./hack/../hack/verify-gofmt.sh	8s
```
But it seems that there is no format problem in the file.

**Comment by lavalamp** [comment]
Looks like you found the problem. Please make sure you're running gofmt with `-s` option and use the same version that the server is using, should be 1.6 now?

**Comment by xiangpengzhao** [comment]
I build Kubernetes using Docker [(instructions)](https://github.com/kubernetes/kubernetes/blob/master/build/README.md). I think the containerized  build env version is the same with that the server is using. Will the unit/integration test be blocked if verify-gofmt.sh returns `FAILED`? 
Thanks! @lavalamp

**Comment by lavalamp** [comment]
Yes, verify-gofmt.sh must succeed.

**Comment by xiangpengzhao** [comment]
Thanks :smile:

**Comment by xiangpengzhao** [comment]
The Jenkins unit/integration of PR #25024 shows `6142 tests run, 24 skipped, 0 failed.` now, but its status is failed.

PTAL @lavalamp , thanks!

[build-log.txt](https://00e9e64bac998487c253d35c7f0e4d28edf2b420016dabf6cb-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F25024%2Fkubernetes-pull-test-unit-integration%2F26960%2Fbuild-log.txt?qk=AD5uMEvPPOM0ir-VIxxZ18XmYVgrurOM3uxHxSbRZaAH2BkPGI9aZGO-7kU2_iixqqTCQ4KxCAZpDjEtbwX4hHZodi5cmEosKfV2uGbjDIzjoKRcX5YPb09gN9IxdVf5vcC66KZJYMLTTw35hJCLNDrp99RsMUQWOI5_m7Odccaq0ADMmwhLUIe-fZilEqJjuxqWnnKvp8QqqNwIzRqc8EdFDFnwHQZmrkN7aduNBjE2wEeJAceK4p2EaKiXWd84Pm6bGWFr0VeTbjhAuKT0aj079q-UyD7Lmu4QpH7Hw-3rHAGRsTnn2XTc_lYOp0KG3rmEUbz4XsXtkv1lqV-rtsTZZtkBPDDvgNcnLAucyU3fUoqyujYmpIq70CUXejDv888Y6KrXnJYul_vx2pGEaw9332U4LR-PB0K7a9K7qS5u05OVHmKeUS0kigdTz1RTYPgD6VSM7G0sxynEwM9Ox92vrFiSjuxwzyNkKDMegfz9GIuHV3Mz8yupk58_TUwRxhFy7rfRlqI-VTPFizgs59MwpzLMt1iA8n6Oh14JsPG6rOGTzdsJBh8bmlYakQe3ilJ4szhxtTUu5wE96s3BW7gCRhKS9g3hjliBL00OZbQp9pxtUMdxwLEQnlUYHrkFBsRZVWyJkLrDKRo8TwoRE9odcvHUakqOI0i7sfOaPw5Bs6BsI_gE1jffmLMgXryJ_yJHoykwZdwQosh70HYCdREZRif5ae4JnF9KvWzYKsbwm8rO4adBKntIPoYJx5WcqIjhBdQ6w1iN0Y37LdBLBLLM0drdAdUSczaE82nM0U4INud3axU4zIT4FoGAtqQKuJp5oW6W7RUZ2oGMMQNLLqUkBNKc3E6xMLLlQ4DzID-wDA2KBzYkqmpQmoCSLDAyAQIYR3QjAjQWe1khspHumXpBqNnNZwB8PnjZVHnWFQliXhmh1I5gXKs)

Some error messages:

```
................
FAIL!
Get deployment {{range.items}}{{.spec.paused}}:{{end}}
  Expected: true:true:
  Got:      <no value>:true:
(B
1091 ./hack/test-cmd.sh
(B
!!! Error in ./hack/test-cmd.sh:53
  'return 1' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:53 runTests(...)
  2: ./hack/test-cmd.sh:2176 main(...)
Exiting with status 1
+++ [0520 10:38:25] Clean up complete
Build step 'Execute shell' marked build as failure
Recording test results
```
