### ISSUE TITLE
Unfriednly error while executing ./hack/update-generated-docs.sh script

### ISSUE THREAD

**Issue by andreykurilin** [kubernetes/kubernetes#25807]
I tried to use update-generated-docs.sh script to update docs and it failed with next log:

> $ ./hack/update-generated-docs.sh 
> Go version: go version go1.6 linux/amd64
> +++ [0518 16:29:07] Building go targets for linux/amd64:
>     cmd/gendocs
>     cmd/genkubedocs
>     cmd/genman
>     cmd/genyaml
>     cmd/genbashcomp
>     cmd/mungedocs
> +++ [0518 16:29:08] Placing binaries
> output: fatal: Not a valid object name upstream/release-1.2
> ,
> ERROR: exit status 128
> `git ls-tree -r --name-only upstream/release-1.2 failed. We'll ignore this error locally, but Jenkins may pick an error. Munger uses the output of this command to determine in unversioned warning, if it should add a link to the doc in release branch.
> output: fatal: Not a valid object name upstream/release-1.2
> ,
> ERROR: exit status 128
> `git ls-tree -r --name-only upstream/release-1.2 failed. We'll ignore this error locally, but Jenkins may pick an error. Munger uses the output of this command to determine in unversioned warning, if it should add a link to the doc in release branch.
> output: fatal: Not a valid object name upstream/release-1.2
> ,
> ERROR: exit status 128
> `git ls-tree -r --name-only upstream/release-1.2 failed. We'll ignore this error locally, but Jenkins may pick an error. Munger uses the output of this command to determine in unversioned warning, if it should add a link to the doc in release branch.

It is hard to understand how can I fix this error without reading code. 

Imo, we need additional check `[[ `git remote` == *$KUBE_GIT_UPSTREAM* ]]` and print user-friendly error if not.

**Comment by lavalamp** [comment]
Thanks for the PR!
