### ISSUE TITLE
exec, logs, attach and any other "container" command should work on init containers

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#25818]
Need to finish so the client allows you to select an init container, and verify the kubelet works correctly.

@bprashanth

**Comment by bprashanth** [comment]
@kubernetes/kubectl (this is a nice intersection of new in 1.3, node and usability, if anyone wants to give it a shot, pretty sure Clayton is busier than I am and I don't think I'll get to it)

**Comment by smarterclayton** [comment]
Will be happy to review any changes - should be fairly straightforward.

**Comment by resouer** [comment]
@smarterclayton Will init container exited after if finished it's job?

**Comment by smarterclayton** [comment]
Yes, init containers are "run to completion" always.

**Comment by AdoHe** [comment]
@smarterclayton IIUC when the init containers of pod have not complete, the pod should be in `Pending` status, which means `kubectl exec` will fail, if init containers run to completion, they will exit, `kubectl exec` still fail. I don't know what you mean exec should work on init containers?

**Comment by bprashanth** [comment]
the init container is still up and running even when the pod is in pending, we should be able to exec and  debug why it's hung, for example.

**Comment by AdoHe** [comment]
add a straightforward exec implementation #26693 @smarterclayton ptal.
