### ISSUE TITLE
kubectl autoscale prevents CPU percentages over 100%

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#25815]
In #18294, it was decided that CPU percentages over 100% on the HPA were valid, but should be warned about.  However, `kubectl autoscale` prevents you from passing `--cpu-percent=X` when X is over 100.

It seems confusing that if you create an autoscaler with `autoscale` it will prevent target CPU percentages over 100%, but after you create it, you can go in and edit it to be over 100% (or you could just create it with a value over 100% by creating via YAML).

We should probably change `kubectl autoscale` to just warn to be consistent.

cc @janetkuo @piosz @kubernetes/autoscaling @ncdc

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by piosz** [comment]
cc @jszczepkowski

**Comment by jszczepkowski** [comment]
> We should probably change kubectl autoscale to just warn to be consistent.

+1
