### ISSUE TITLE
release-1.2 build package dependence error

### ISSUE THREAD

**Issue by minjs** [kubernetes/kubernetes#25823]
c117-2:kubernetes u738$ godep restore
# cd .; git clone https://code.google.com/p/go-decimal-inf.exp /Users/u738/workspace/go/src/speter.net/go/exp/math/dec/inf
Cloning into '/Users/u738/workspace/go/src/speter.net/go/exp/math/dec/inf'...
**fatal: repository 'https://code.google.com/p/go-decimal-inf.exp/' not found**
godep: error downloading dep (speter.net/go/exp/math/dec/inf): exit status 128
godep: Error downloading some deps. Aborting restore and check.

**Comment by minjs** [comment]
This was fixed in master branch by switching to "gopkg.in/inf.v0".

**Comment by lavalamp** [comment]
We're probably not going to cherry-pick this, sorry-- it still builds. You can manually copy out of the Godeps/_workspace directory if you need to simulate `godep restore`.

**Comment by robdaemon** [comment]
@lavalamp I urge you to reconsider this - it does not build properly for people that are depending on the Kubernetes client APIs and have to vendorize them. 1.2 is still the stable, released version.

This change is forcing me to move a product to an alpha version of Kubernetes at this time. You cannot godep restore anymore:

```
rroland@rrolandz620:~/k8/src/k8s.io$ cd kubernetes/
rroland@rrolandz620:~/k8/src/k8s.io/kubernetes$ git checkout -b release-1.2 --track origin/release-1.2
Branch release-1.2 set up to track remote branch release-1.2 from origin.
Switched to a new branch 'release-1.2'
rroland@rrolandz620:~/k8/src/k8s.io/kubernetes$ godep restore
# cd .; git clone https://code.google.com/p/go-decimal-inf.exp /home/rroland/k8/src/speter.net/go/exp/math/dec/inf
Cloning into '/home/rroland/k8/src/speter.net/go/exp/math/dec/inf'...
fatal: repository 'https://code.google.com/p/go-decimal-inf.exp/' not found
godep: error downloading dep (speter.net/go/exp/math/dec/inf): exit status 128
godep: Error downloading some deps. Aborting restore and check.
```

**Comment by lavalamp** [comment]
@roberthbailey has been gatekeeping cherry-picks.

**Comment by bgrant0607** [comment]
@robdaemon You might also take a look at work others have done to tease out the client code, such as:
https://github.com/technosophos/kubelite

**Comment by roberthbailey** [comment]
I would consider a cherry pick for the 1.2 branch if it was small and easily reviewable. This is a reported bug; is anyone volunteering to send a cherry pick PR?

**Comment by brendandburns** [comment]
@robdaemon can you send the cherry pick?

**Comment by roberthbailey** [comment]
I'm going to close this, since we've seen a sharp decrease in cherry picks for the 1.2 release branch and we haven't cut a 1.2.x release in over a month. Please re-open if you'd still like to see this fixed.
