### ISSUE TITLE
Discuss: Support user-defined healthchecks in docker image

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#25829]
Docker is adding support for user-defined healthchecks as part of Dockerfile, and the proposal is at https://github.com/docker/docker/pull/22719. We should think about if we want to support that feature? If yes, how? 

cc/ @thockin @bgrant0607 @kubernetes/goog-node @derekwaynecarr

**Comment by derekwaynecarr** [comment]
My initial bias is that health checks are a layer above the container
runtime interface, but if we did support it, it must be reflected in the
pod spec and not hidden from view when introspecting the pod.

We have interfaces today that ask the user to add health checks if not
specified on the pod spec, it would be confusing for them to be hidden in
the image definition alone.

I don't think it makes sense to inherit health checks from previous image
layers.  I also would find it odd if we supported both pod spec liveness
probes and container image health checks without unifying them as I would
expect a consistent set of events around liveness failures in the
experience.

**Comment by yujuhong** [comment]
I agree with what @derekwaynecarr's points. I have also expressed similar concerns in the brief discussion today. It's not desirable to have kubelet running health checks for a container without explicitly expressing it in the pod spec.

**Comment by bgrant0607** [comment]
Trying the Socratic method. :-)

Why are any container properties represented in image metadata?

What would we have done if this had been supported by Docker from the beginning?

What did we do for other container properties, such as ports? 

How are ports different from entrypoint and command?

Why don't we use Docker's restart policy even though it mimics ours?

What would we do about readiness probes if we supported Docker's health checks?

What are the other facets of an application's management/introspection surface? Would they make sense as image properties?

What about other runtimes?

Why did Docker add this feature?

**Comment by xenoterracide** [comment]
HEALTHCHECK has been supported for years now... seems redundant to have a liveness check in my pod file and in my dockerfile.

**Comment by joebowbeer** [comment]
@xenoterracide are you advocating for support of the HEALTHCHECK Dockerfile instruction that was added for Swarm - which has been disabled in Kubernetes for years? #50703
