### ISSUE TITLE
[GKE] Pod Can't Mount Volumes (Fails to Create Paths) Won't Leave ContainerCreating State

### ISSUE THREAD

**Issue by pnovotnak** [kubernetes/kubernetes#25828]
We have a disk "databases-us-central1-b-kube" that contains some protein databases (blast non-redundant, pdb, hhsearch, etc.) It's supposed to be mounted read-only.

We had a replication controller/replica in our "development" namespace (which was created long ago) that was accidentally set to mount this drive as read-write. It was previously the only thing using the drive, so we had no issues then and didn't notice. However, we recently tried to add a second controller/replica that tries to mount the same drive as read-only. When we noticed our mistake in the first controller, we changed it's configuration to expose the drive as read-only, deleted the replication controller with `kubectl delete rc/theservice` and re-created it with `kubectl create -f theservice-controller.yml`.

Now we're having this awesome problem where *almost* nothing can mount disks. I had the bright idea to restart each node in the cluster via the google cloud console in an attempt to fix things, and now things that mount a disks are failing to start.

There is come collateral here from services that depend on things that are failing, but I think this illustrates the problem fairly clearly. Everything listed here in `Error` state was running fine with disks happily attached until I rebooted the nodes, the original controller was deleted before I rebooted the nodes;

$ kubectl get pods --all-namespaces  # post cluster recycle, reboot, etc.

    NAMESPACE     NAME                                                                       READY     STATUS             RESTARTS   AGE
    daemons       athingath-soka2                                                            1/1       Running            1          1d
    daemons       blahblah-u8mjb                                                             1/1       Running            1          1d
    daemons       blahblah-wshsd                                                             1/1       Running            1          1d
    development   cthin-298yb                                                                1/1       Running            1          1d
    development   dth-n5ce0                                                                  4/4       Running            4          21h
    development   eth-zttp5                                                                  1/1       Running            1          1d
    development   fthingf-uc7v1                                                              3/3       Running            3          14h
    development   gthinggt-yjb3n                                                             1/1       Running            1          1d
    development   hthinghti-yrtap                                                            1/1       Running            1          1d
    development   ithingi-plbf1                                                              1/1       Running            1          1d
    development   jthingjt-9r0s3                                                             0/2       Error              0          23h
    development   kthingk-cc3sf                                                              1/1       Running            2          1d
    kube-system   fluentd-cloud-logging-gke-nananananananananaanananananananananaanan-oc5l   1/1       Running            1          1d
    kube-system   fluentd-cloud-logging-gke-nananananananananaanananananananananaanan-xr5o   1/1       Running            1          1d
    kube-system   heapster-v1.0.2-595387591-8mwzx                                            2/2       Running            2          1d
    kube-system   kube-dns-v11-o56o6                                                         4/4       Running            4          1d
    kube-system   kube-proxy-gke-nananananananananaanananananananananaanan-oc5l              1/1       Running            1          1d
    kube-system   kube-proxy-gke-nananananananananaanananananananananaanan-xr5o              1/1       Running            1          1d
    kube-system   kubernetes-dashboard-v1.0.1-816o3                                          1/1       Running            1          1d
    kube-system   l7-lb-controller-v0.6.0-tov5q                                              2/2       Running            8          1d
    production    cthin-4rux8                                                                2/2       Running            2          1d
    production    dth-hjg5f                                                                  4/4       Running            9          1d
    production    eth-1buwt                                                                  2/2       Running            2          1d
    production    fthingf-fyr51                                                              3/3       Running            9          1d
    production    gthinggt-mk8ok                                                             2/2       Running            2          1d
    production    hthinghti-94r7k                                                            2/2       Running            2          1d
    production    ithingi-lkrzj                                                              0/1       Error              0          1d
    production    jthingjt-wlnpt                                                             0/3       Error              1          1d
    production    kthingk-qfuyg                                                              2/2       Running            2          1d
    staging       cthin-8co0y                                                                1/1       Running            1          1d
    staging       dth-2jppb                                                                  3/4       CrashLoopBackOff   16         1d
    staging       eth-qfh2z                                                                  1/1       Running            1          1d
    staging       fthingf-a5x7l                                                              3/3       Running            4          1d
    staging       gthinggt-bdpui                                                             1/1       Running            1          1d
    staging       hthinghti-6vxcz                                                            1/1       Running            1          1d
    staging       ithingi-mi93m                                                              0/1       Error              0          1d
    staging       jthingjt-aloy7                                                             0/2       Error              2          1d
    staging       kthingk-3l3ja                                                              1/1       Running            1          1d
 
Here are some debugging outputs;

$ kubectl version

    Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
    Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}

$ kubectl get events  # pre cluster recycle & reboot

    FIRSTSEEN   LASTSEEN   COUNT     NAME            KIND                    SUBOBJECT                   TYPE      REASON             SOURCE                                                 MESSAGE
    10h         27s        609       thing-apz0y     Pod                                                 Warning   FailedMount        {kubelet gke-redacted-node-rq7o}   Unable to mount volumes for pod "thing-apz0y_development(redacted-uuid)": Could not attach GCE PD "databases-us-central1-b-kube". Timeout waiting for mount paths to be created.
    10h         27s        609       thing-apz0y     Pod                                                 Warning   FailedSync         {kubelet gke-redacted-node-rq7o}   Error syncing pod, skipping: Could not attach GCE PD "databases-us-central1-b-kube". Timeout waiting for mount paths to be created.

$ kubectl get pods

    NAME              READY     STATUS              RESTARTS   AGE
    ...
    thing-apz0y       0/2       ContainerCreating   0          10h
    ...

Here's an rc config from the horse's mouth;

$ kubectl edit rc/athing

    # Please edit the object below. Lines beginning with a '#' will be ignored,
    # and an empty file will abort the edit. If an error occurs while saving this file will be
    # reopened with the relevant failures.
    #
    apiVersion: v1
    kind: ReplicationController
    metadata:
      creationTimestamp: 2016-05-18T...
      generation: 1
      labels:
        name: thing
      name: thing
      namespace: development
      resourceVersion: "redacted"
      selfLink: /api/v1/namespaces/development/replicationcontrollers/thing
      uid: redacted-uid
    spec:
      replicas: 1
      selector:
        name: thing
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: thing
            track: build
        spec:
          containers:
          - command:
            - fab
            - uwsgi
            env:
            ...
            image: gcr.io/cyrusmolcloud/thing:build
            imagePullPolicy: Always
            name: thing
            ports:
            - containerPort: 80
              name: thing-web
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            volumeMounts:
            - mountPath: /var/databases
              name: databases
          - command:
            - fab
            - runworkers
            env:
            ...
            image: gcr.io/cyrusmolcloud/thing:build
            imagePullPolicy: Always
            name: worker
            resources: {}
            terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - gcePersistentDisk:
              fsType: ext4
              pdName: databases-us-central-1-kube
              readOnly: true
            name: databases
    status:
      fullyLabeledReplicas: 1
      observedGeneration: 1
      replicas: 1

So, the great thing is that some/all drives are actually mounted to the nodes;

$ gcloud compute instances describe gke-redacted-node-rq7o

    canIpForward: true
    cpuPlatform: Intel Haswell
    creationTimestamp: '2016-05-16T...'
    disks:
    - autoDelete: true
      boot: true
      deviceName: persistent-disk-0
      index: 0
      interface: SCSI
      kind: compute#attachedDisk
      licenses:
      - https://www.googleapis.com/compute/v1/projects/gke-node-images/global/licenses/gke-node
      mode: READ_WRITE
      source: https://www.googleapis.com/compute/v1/projects/cyrusmolcloud/zones/us-central1-b/disks/gke-redacted-node-rq7o
      type: PERSISTENT
    - autoDelete: false
      boot: false
      deviceName: databases-us-central1-b-kube
      index: 1
      interface: SCSI
      kind: compute#attachedDisk
      mode: READ_ONLY
      source: https://www.googleapis.com/compute/v1/projects/cyrusmolcloud/zones/us-central1-b/disks/databases-us-central1-b-kube
      type: PERSISTENT
    - autoDelete: false
      boot: false
      deviceName: databases-us-central-1-kube-1
      index: 2
      interface: SCSI
      kind: compute#attachedDisk
      mode: READ_ONLY
      source: https://www.googleapis.com/compute/v1/projects/cyrusmolcloud/zones/us-central1-b/disks/databases-us-central-1-kube-1
      type: PERSISTENT
    id: 'redacted'
    kind: compute#instance
    machineType: https://www.googleapis.com/compute/v1/projects/cyrusmolcloud/zones/us-central1-b/machineTypes/n1-standard-16
    metadata:
    ...

I can't even see any clear patterns in the failures.

**Comment by pnovotnak** [comment]
cc @javierbq

**Comment by pnovotnak** [comment]
Destroying the service and controller, then re-creating both fixed the issue

**Comment by pnovotnak** [comment]
I tried switching over to persistent volumes & persistent volume claims, the problem persists :)

    NAMESPACE     NAME        STATUS    VOLUME      CAPACITY   ACCESSMODES   AGE
    development   databases   Bound     databases   500Gi      ROX           2m 
    production    databases   Pending   databases   0                        58s
    staging       databases   Pending   databases   0                        1m

**Comment by lavalamp** [comment]
@thockin

**Comment by pnovotnak** [comment]
I added an additional node to our cluster, just in case we were resource-constrained, a second persistent volume and associated claim for our "production" namespace against a second disk. I got the same results as before. We have other controllers 

$ kubectl describe pv

    Name:       databases
    Labels:     <none>
    Status:     Bound
    Claim:      development/databases
    Reclaim Policy: Retain
    Access Modes:   ROX
    Capacity:   500Gi
    Message:
    Source:
        Type:   GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
        PDName: databases-us-central1-b-kube
        FSType: ext4
        Partition:  0
        ReadOnly:   false


    Name:       databases-1
    Labels:     <none>
    Status:     Bound
    Claim:      production/databases
    Reclaim Policy: Retain
    Access Modes:   ROX
    Capacity:   500Gi
    Message:
    Source:
        Type:   GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
        PDName: databases-us-central1-b-kube-1
        FSType: ext4
        Partition:  0
        ReadOnly:   false


$ kubectl describe pvc --namespace=development

    Name:       databases
    Namespace:  development
    Status:     Bound
    Volume:     databases
    Labels:     <none>
    Capacity:   500Gi
    Access Modes:   ROX


$ kubectl describe pvc --namespace=production

    Name:       databases
    Namespace:  production
    Status:     Bound
    Volume:     databases-1
    Labels:     <none>
    Capacity:   500Gi
    Access Modes:   ROX


$ kubectl describe pod/thing-6ap8s

    Name:       thing-6ap8s
    Namespace:  production
    Node:       gke-node-1e9640bd-oc5l/10.240.0.4
    Start Time: Thu, 19 May 2016 14:08:01 -0700
    Labels:     name=thing,track=build
    Status:     Pending
    IP:
    Controllers:    ReplicationController/thing
    Containers:
      thing:
        Container ID:
        Image:      gcr.io/cyrusmolcloud/thing:production
        Image ID:
        Port:       80/TCP
        Command:
          fab
          uwsgi
        QoS Tier:
          cpu:      BestEffort
          memory:       BestEffort
        State:      Waiting
          Reason:       ContainerCreating
        Ready:      False
        Restart Count:  0
        Environment Variables:
          ...
      worker:
        Container ID:
        Image:      gcr.io/cyrusmolcloud/thing:production
        Image ID:
        Port:
        Command:
          fab
          runworkers
        QoS Tier:
          cpu:      BestEffort
          memory:       BestEffort
        State:      Waiting
          Reason:       ContainerCreating
        Ready:      False
        Restart Count:  0
        Environment Variables:
          ...
    Conditions:
      Type      Status
      Ready     False
    Volumes:
      databases:
        Type:   PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
        ClaimName:  databases
        ReadOnly:   false
      default-token-redacted:
        Type:   Secret (a volume populated by a Secret)
        SecretName: default-token-redacted
    Events:
      FirstSeen LastSeen    Count   From                                SubobjectPath   Type        Reason      Message
      --------- --------    -----   ----                                -------------   --------    ------      -------
      2m        2m      1   {default-scheduler }                                Normal      Scheduled   Successfully assigned thing-6ap8s to gke-node-1e9640bd-oc5l
      1m        26s     2   {kubelet gke-node-1e9640bd-oc5l}            Warning     FailedMount Unable to mount volumes for pod "thing-6ap8s_production(redacted-uid)": Could not attach GCE PD "databases-us-central1-b-kube-1". Timeout waiting for mount paths to be created.
      1m        26s     2   {kubelet gke-node-1e9640bd-oc5l}            Warning     FailedSync  Error syncing pod, skipping: Could not attach GCE PD "databases-us-central1-b-kube-1". Timeout waiting for mount paths to be created.

**Comment by pnovotnak** [comment]
I can provide access to the cluster for debugging.

peter at cyrusbio d com

**Comment by saad-ali** [comment]
Hey Peter, looks like you're hitting two known, and really annoying, issues with persistent disks in Kubernetes v1.2:

> we recently tried to add a second controller/replica that tries to mount the same drive as read-only. When we noticed our mistake in the first controller, we changed it's configuration to expose the drive as read-only, deleted the replication controller with kubectl delete rc/theservice and re-created it with kubectl create -f theservice-controller.yml [...] Now we're having this awesome problem where almost nothing can mount disks. I had the bright idea to restart each node in the cluster via the google cloud console in an attempt to fix things, and now things that mount a disks are failing to start.

This is most likely issue https://github.com/kubernetes/kubernetes/issues/19953

> Everything listed here in Error state was running fine with disks happily attached until I rebooted the nodes

This is most likely issue https://github.com/kubernetes/kubernetes/issues/14642

Both of these issues have the same root cause, and the fix will be part of the upcoming v1.3 release.

Work around for the reboot issue is to manually detach the disk after a reboot (or delete the pod/RC to trigger automatic detach). No good work around for the read-only issue (only way to avoid it would be to make sure pods using the same disk end up on different nodes).

We can leave this issue open, until v1.3 is out (https://github.com/kubernetes/kubernetes/wiki/Release-1.3#proposed-timeline) and you can confirm the issue is resolved.

**Comment by pnovotnak** [comment]
Thanks @saad-ali! Seems like those two issues will indeed resolve the issues I'm seeing, but yes, let's let it be for now. I'll set up some reminders for myself to update this issue after 1.3 hits.

**Comment by pnovotnak** [comment]
I've upgraded to 1.3, but I'm still having the issue where ROX volume claims are not mounted properly.

`$ kubectl get pv`

    NAME        CAPACITY   ACCESSMODES   STATUS    CLAIM                   REASON    AGE
    databases   500Gi      ROX           Bound     a-namespace/databases             7m

`$ kubectl get pvc --namespace=a-namespace`

    NAME        STATUS    VOLUME      CAPACITY   ACCESSMODES   AGE
    databases   Bound     databases   0                        7m

`$ kubectl get events`

    ...
    ...timeout expired waiting for volumes to attach/mount for pod "mypod-id"/"a-namespace". list of unattached/unmounted volumes=[databases]

**Comment by saad-ali** [comment]
@pnovotnak Let's debug it then.

Could you repro the issue and share the following with me:
  * The pv/pvc/pod definition files.
  * What order you created the pods in which ones succeed which ones fail.
  * Your `/var/log/kubelet.log` files from your nodes

Feel free to email this to me (email address in profile) if you don't want to share publically.

**Comment by FlavioF** [comment]
@saad-ali, @pnovotnak any new about it? Same problem here.

**Comment by saad-ali** [comment]
I haven't received any information from @pnovotnak yet.

@FlavioF if you are running into the same issue, feel free to share your pod/pv/pvc files, your repro steps, kubelet logs, and master kube-controller-manager logs with me and I'll take a look. There are a handful of storage bugs in 1.3 that we're tracking. I'd like to understand if you guys are running into a new issue or hitting one of those.

**Comment by pnovotnak** [comment]
Sorry for the delay!

So, it works to create a PV, then a PVC in each namespace. However, only one pod manages to bind the PVC and start. Here are the steps to reproduce (run these commands inside the extracted contents of [kube-pvc-debug-configs.tar.gz](https://github.com/kubernetes/kubernetes/files/398220/kube-pvc-debug-configs.tar.gz));

```bash
#!/bin/bash
gcloud compute disks create --zone=us-central1-b --size=500gb pvc-test-drive
gcloud container clusters create --machine-type=n1-standard-1 --zone=us-central1-b pvc-testing
kubectl version > kubectl-version.txt
kubectl create -f ./
sleep 15  # wait for namespaces to come online so that PVCs can be created
kubectl create -f ./

# wait for a controller to come online
while [ -z "$(kubectl get pods --all-namespaces | awk '/dummy-controller/ && /Running/')" ]; do
  sleep 1
done

# snag system logs from all compute instances
while read node; do
  gcloud beta compute scp --recurse $node:/var/log $node-logs
done < <(kubectl get nodes | awk '/gke/ {print $1}')

# All finished. Make sure the user knows that things are still online...
watch kubectl get pods --all-namespaces
```

@saad-ali: I emailed you a tar.gz created with the above script.

**Comment by saad-ali** [comment]
Sync'd with @pnovotnak offline. 

He was having trouble with setting up PV/PVCs with a ReadOnlyMany relationship. He was creating one PV object and multiple PVC objects in different namespaces expecting all the PVC objects to bind to the single PV object.

However, a single PV can only be bound to a single PVC at a given time, regardless of whether it is ROX or not (once a PV/PVC binds, the PV can't bind to any other PVC, and the way to use the PV is via the bound PVC pointer).

Once a PV/PVC is bound, ReadOnlyMany PVCs may be referenced from multiple pods. Peter, however, couldn't use a single PVC object since he was trying to refer to it from multiple namespaces, and PVCs are namespaced (and PV objects are not). So to make this work Peter will have to create multiple PV objects that are identical (referring to the same disk) except for the name. This will allow each of his PVC objects to find a PV object to bind to.

**Comment by pnovotnak** [comment]
@FlavioF feel free to re-open with details if you are still having issues, but I'm all set, so I'm going to close this.
