### ISSUE TITLE
Unit test flake Test_NewGoRoutineMap_Positive_WaitEmpty

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#25825]
```
=== RUN   Test_NewGoRoutineMap_Positive_WaitEmpty
--- FAIL: Test_NewGoRoutineMap_Positive_WaitEmpty (0.14s)
	goroutinemap_test.go:216: Error waiting for GoRoutineMap.Wait: timeout after 50ms
=== RUN   Test_NewGoRoutineMap_Positive_Wait
--- PASS: Test_NewGoRoutineMap_Positive_Wait (0.16s)
FAIL
FAIL	k8s.io/kubernetes/pkg/util/goroutinemap	0.676s
```

**Comment by smarterclayton** [comment]
Found in #24768

**Comment by lavalamp** [comment]
Can't figure out where this is even used. Can we just delete it?

**Comment by lavalamp** [comment]
Marking cluster team since it looks like @saad-ali added this.

**Comment by janetkuo** [comment]
Again in #25509

**Comment by saad-ali** [comment]
This is used by the yet-to-be-merged Attach Detach controller and persistent volume controller refactor.

Assigning to @jsafrane who introduced this particular test. Jan, not sure what's better increasing the timeout or removing the test altogether.

**Comment by jsafrane** [comment]
0.14 s is not enough to start a trivial goroutine??? I'll increase all the timeouts.

**Comment by smarterclayton** [comment]
Unit tests can be arbitrarily delayed under load.  We have had flakes due
to tests that assumed that 15s is long enough to sleep.

Short answer: don't use timeouts, rewrite your test and code to not depend
on the passage of time.

On May 20, 2016, at 4:23 AM, Jan Šafránek <notifications@github.com> wrote:

0.14 s is not enough to start a trivial goroutine??? I'll increase all the
timeouts.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/25825#issuecomment-220545174>

**Comment by jsafrane** [comment]
This flaky test checks that `something.Wait()` waits until a separate goroutine finishes. It has to stop waiting and report error at some point. Previously, it waited for 50ms after the goroutine stopped. What is suggested time then? Or should I let the test runner itself time out?

**Comment by smarterclayton** [comment]
You should use a channel or other synchronization to deliver that, not
waits.

**Comment by jsafrane** [comment]
Then I need to wait for message in the channel with a timeout to throw an error that the test failed, that's not really a difference.

**Comment by smarterclayton** [comment]
It's ok to have VERY long timeouts for failures (unit tests shouldn't be
broken).
