### ISSUE TITLE
protobuf codegen does not handle *[]Foo and *map[Foo]Bar

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#25835]
I took a look at the code generator and it seems pretty clearly wrong for this case, but I am not deeply familiar with it, so I am crying for help.

Specifically, I think we need to handle the case of pointer-to-slice and pointer-to-map specially, and inject an intermediate type. Coincidentally, this is what we will have to do for proto3 optional primitives, anyway.

```
type Struct struct {
    foos *[]Foo
}
```

has to become

```
message Struct {
    optional _FooList foos = 1;
}
message _FooList {  //TODO: generate a unique name
    repeated Foo foos = 1;  //TODO: name it the same as the outer or with a generic name?
}
```

I could be misreading the codegen, but it looks like membersToFields is the place where we can recognize `field.Nullable && field.Slice`, but it's not obvious how to generate a new message type from within this function. There are approximately zero comments in the whole file :(

@smarterclayton @wojtek-t please advise, @lavalamp FYI

**Comment by smarterclayton** [comment]
*[]Foo should be redundant - a slice can already be nil.  Same for maps.
I'll look tonight

On May 18, 2016, at 5:35 PM, Tim Hockin <notifications@github.com> wrote:

I took a look at the code generator and it seems pretty clearly wrong for
this case, but I am not deeply familiar with it, so I am crying for help.

Specifically, I think we need to handle the case of pointer-to-slice and
pointer-to-map specially, and inject an intermediate type. Coincidentally,
this is what we will have to do for proto3 optional primitives, anyway.

type Struct struct {
    foos *[]Foo
}

has to become

message Struct {
    optional _FooList foos = 1;
}
message _FooList {  //TODO: generate a unique name
    repeated Foo foos = 1;  //TODO: name it the same as the outer or
with a generic name?
}

I could be misreading the codegen, but it looks like membersToFields is the
place where we can recognize field.Nullable && field.Slice, but it's not
obvious how to generate a new message type from within this function. There
are approximately zero comments in the whole file :(

@smarterclayton <https://github.com/smarterclayton> @wojtek-t
<https://github.com/wojtek-t> please advise, @lavalamp
<https://github.com/lavalamp> FYI

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/25835>

**Comment by lavalamp** [comment]
There's actually not really a difference between a zero-length and a nil
slice in go, at least not an easily-discoverable one. I suppose the request
is to tell the difference between `"x": null` (or `x` being omitted) and
`"x": []`?

**Comment by smarterclayton** [comment]
If you have omitempty set, JSON deserialization will *always* return an
empty slice.  If you don't have omit empty set, you'll get a nil slice if
the user sent no field or "field: null", or an empty slice if the user set
slice.

This is why omitempty should never be used on slices or maps, where we want
to discriminate between empty and unspecified.  It's not the right signal.

**Comment by smarterclayton** [comment]
I can't think of a reason to use `*[]Foo` over `[]Foo` without omitempty.  We shouldn't need it.

**Comment by smarterclayton** [comment]
I present as evidence:

on Sep 29, 2011
<https://github.com/golang/go/issues/2278#issuecomment-66058926>

**Comment by thockin** [comment]
We discussed on slack.

Some notes.  If we leave out 'omitempty' on the slice, it mostly does the right thing.  It marshals as "null" but I can live with that.  HOWEVER, we're using 'omitempty' to represent 'optional', so any such field now becomes documented (and code-generated) as required.  BAD.  We need a different tag for swagger to use.  We should probably do that ANYWAY.

And now on to protobuf, which has no way to represent the distinction between a nil repeated and an empty repeated.  Clayton is considering options there

**Comment by smarterclayton** [comment]
As determined by testing, it's marshaling with omitempty where Go turns an
empty array into a nil (which then comes back as nil).  So JSON with
omitempty has no way to determine set vs. unset.

**Comment by thockin** [comment]
I now feel like the lesser of 2 evils is to remove 'omitempty' for the case at hand, and deal with the false requiredness, and know that protobuf simply will not work for this type, until we have some fix.

**Comment by smarterclayton** [comment]
I'm going to look at an intermediate type representation for slices, since
in proto3 we'd need one anyway to do a union for nullable.

**Comment by smarterclayton** [comment]
Proposed https://github.com/gogo/protobuf/issues/181 and will follow up.

**Comment by thockin** [comment]
In discussing with @lavalamp, another idea:. What if we simply said "don't
do that" and demand that we use a real struct to wrap the nil-matters
slice?  It would make the go, JSON, and protobuf APIs more consistent (by
making them all uglier) and would not depend on "magic".

I don't know how many other places in our API make this distinction (or
think they do, heh), but maybe we caught this early enough?

**Comment by smarterclayton** [comment]
OpenShift has a few.  Not many though.  Will "inlining" work on it in JSON?

I'm not opposed to it being obvious.  I think it may be the more practical
solution in the short term.

**Comment by smarterclayton** [comment]
It will make a few serialization places slower.

**Comment by lavalamp** [comment]
I suggested making a go alias instead of a struct.

I think making separate structs for optional sections of the api might be a net improvement, though.

**Comment by smarterclayton** [comment]
The alias won't help with gogoproto because of the way it generates the
struct on the output.

**Comment by smarterclayton** [comment]
I'm starting to feel the separate structs might be inevitable.  I'll pull
together a quick example support and then respond back.

**Comment by smarterclayton** [comment]
I think this should work for us:

```
// pkg/runtime/types.go
type OptionalStrings []string

... custom marshaller and unmarshaller for proto that preserves status
```

We'd still have to fix the omitempty.  We should check ugorji to see if it handles it differently than go (i.e., correctly).

**Comment by smarterclayton** [comment]
I can make the custom unmarshaller work for a set of arrays.  We could move to generation in the future if necessary.  How many primitive arrays do we need to support?

**Comment by smarterclayton** [comment]
I think I can make the custom unmarshaller bypass the omit empty problem, but need to test.

**Comment by wojtek-t** [comment]
Are we aware of any such places in our API (where we need to distinct nil and empty arrays)?
If not, I would personally vote for wrapping those into structs. In my opinion such api is cleaner.
Regarding slower serialization, I don't think it will be a problem.

As for having a custom marshaller/unmarshaller, I would vote for having it only if it is really really needed (i.e. if it is required to support existing API (which we can't change)).

**Comment by smarterclayton** [comment]
Wrapping with structs I believe will make us have to write custom
unmarshal long anyway, because you can't use "inline" on two children
in the same struct (afaik) and the output json would be disgusting
otherwise:

{"field": {"optionalStringArray": []}}

I think we want our JSON schema to be the thing we optimize for
usability and clarity.  There is nothing ambiguous about

{"field": []}

And we should be optimizing to make that work (not optimizing to make
omitempty be our way of saying "optional")

**Comment by wojtek-t** [comment]
>
because you can't use "inline" on two children
in the same struct (afaik) and the output json would be disgusting
otherwise:

OK - that one I didn't know. It's a good argument.

>
I think we want our JSON schema to be the thing we optimize for
usability and clarity. 

+100

**Comment by thockin** [comment]
I don't think inline helps, either.  This applies to maps as well as slices.

https://play.golang.org/p/XCSKUbifxB

@girishkalele

If we think we should optimize for JSON clarity, then it falls on the
protobuf impl to handle the mess.  I can live with that.  I don't know if
there are any places that currently need to know empty vs null for slices
(except the new ones I want) but there are old-style selectors (e.g.
Service) that claim to care about the difference.

Worse, depending on whether you use `kubectl patch` or not, a `[]` or `{}`
value may come through as always-nil or as sometimes-nil-sometimes-empty.
Sigh

Other than Service do we have any such old-style selectors left?

**Comment by smarterclayton** [comment]
I definitely have to solve empty but not nil for Openshift.

I'm not aware of any other special old selector fields.

**Comment by girishkalele** [comment]
I did some quick tests with a service created with a selector and then patched with selector:null vs selector:{}, I also dumped the etcd authoritative source of JSON entry at every step.

I see _no_ difference in the JSON between nil vs {} - the selector field is omitted in both cases.

```
$ execp etcd-server-kubernetes-master "etcdctl get /registry/services/specs/default/trsvc"
{"kind":"Service","apiVersion":"v1","metadata":{"name":"trsvc","namespace":"default","uid":"bedce12b-2131-11e6-89da-42010a800002","creationTimestamp":"2016-05-23T22:00:22Z","labels":{"app":"trsvc"}},"spec":{"ports":[{"name":"iperf","protocol":"TCP","port":5201,"targetPort":5201}],
"selector":{"app":"trsvc"},"clusterIP":"10.0.198.216","type":"ClusterIP","sessionAffinity":"None"},"status":{"loadBalancer":{}}}

$ kubectl describe svc trsvc
Name:                   trsvc
Namespace:              default
Labels:                 app=trsvc
Selector:               app=trsvc
Type:                   ClusterIP
IP:                     10.0.198.216
Port:                   iperf   5201/TCP
Endpoints:              10.244.0.7:5201,10.244.1.7:5201
Session Affinity:       None
No events.

PATCH AS NULL:

$ kubectl patch svc trsvc -p '{ "spec": { "selector" : null } }'
"trsvc" patched
$ kubectl describe svc trsvc
Name:                   trsvc
Namespace:              default
Labels:                 app=trsvc
Selector:               <none>
Type:                   ClusterIP
IP:                     10.0.198.216
Port:                   iperf   5201/TCP
Endpoints:              10.244.0.7:5201,10.244.1.7:5201
Session Affinity:       None
No events.

$ execp etcd-server-kubernetes-master "etcdctl get /registry/services/specs/default/trsvc"
{"kind":"Service","apiVersion":"v1","metadata":{"name":"trsvc",
"namespace":"default","uid":"bedce12b-2131-11e6-89da-42010a800002","creationTimestamp":"2016-05-23T22:00:22Z","labels":{"app":"trsvc"}},
"spec":{"ports":[{"name":"iperf","protocol":"TCP","port":5201,"targetPort":5201}],
"clusterIP":"10.0.198.216","type":"ClusterIP","sessionAffinity":"None"},"status":{"loadBalancer":{}}}

PATCH AS {}:

$ kubectl patch svc trsvc -p '{ "spec": { "selector" : {} } }'
"trsvc" patched
$ execp etcd-server-kubernetes-master "etcdctl get /registry/services/specs/default/trsvc"
{"kind":"Service","apiVersion":"v1","metadata":{"name":"trsvc","namespace":"default",
"uid":"bedce12b-2131-11e6-89da-42010a800002","creationTimestamp":"2016-05-23T22:00:22Z","labels":{"app":"trsvc"}},
"spec":{"ports":[{"name":"iperf","protocol":"TCP","port":5201,"targetPort":5201}],
"clusterIP":"10.0.198.216","type":"ClusterIP","sessionAffinity":"None"},"status":{"loadBalancer":{}}}
```

**Comment by lavalamp** [comment]
Well, I guess it's a good thing no one would want that behavior, then...

**Comment by thockin** [comment]
So I think we should un-document the "selects all" behavior of
service.spec.selector.  For medium term we need to decouple "omitempty"
from "optional" in swagger (use a different tag, I guess) and then we can
mark these fields as optional, but not omitempty.  This will keep JSON
happy and simple, and leave the fugliness to protobuf's impl.

**Comment by smarterclayton** [comment]
What was the NetworkPolicy field that you wanted to support here?  Is it critical for 1.3?  Trying to decide whether to do the cheap or hard fix.

**Comment by lavalamp** [comment]
@thockin can I kick this out of 1.3? Unless it's blocking petset or Ubernetes, I think the answer should be yes.

**Comment by thockin** [comment]
It's fine to kick from 1.3

**Comment by smarterclayton** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/27258.

You add an alias 

    // +protobuf.nullable=true
    type OptionalMap map[string]string

And will get the right generated output.  Lightly tested right now because test_apis can't be used from protobuf for lots of reasons.
