### ISSUE TITLE
ConfigMap [Conformance] tests fail with recommended admission-control settings

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#25839]
Either [the recommended / default admission-control settings](https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/admission-controllers.md#is-there-a-recommended-set-of-plug-ins-to-use) are wrong, or the following ConfigMap tests need to get kicked out of [Conformance]

```
• Failure [8.943 seconds]
ConfigMap
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/configmap.go:202
  should be consumable from pods in volume as non-root [Conformance] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/configmap.go:40

  May 18 15:27:22.273: Failed to create pod: pods "pod-configmaps-b07b6fb0-1d47-11e6-9b88-a45e60eb55a3" is forbidden: pod.Spec.SecurityContext.RunAsUser is forbidden

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:1685

• Failure [8.411 seconds]
ConfigMap
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/configmap.go:202
  should be consumable from pods in volume with mappings as non-root [Conformance] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/configmap.go:52

  May 18 15:27:38.958: Failed to create pod: pods "pod-configmaps-ba6d6ed7-1d47-11e6-ad85-a45e60eb55a3" is forbidden: pod.Spec.SecurityContext.RunAsUser is forbidden

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:1685
```

What caused `SecurityContextDeny` to be placed in the recommended list in the first place?

/cc @kubernetes/sig-testing

**Comment by spiffxp** [comment]
I'm guessing per #21004 the default settings are wrong and should be corrected?

/cc @pmorie @vishh @ArtfulCoder @bgrant0607 @roberthbailey

**Comment by roberthbailey** [comment]
AFAIK it was in the recommended list of admission controllers prior to the 1.2 release. It looks like http://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-plug-ins-to-use should be updated for 1.2 (or maybe expanded to show for recommendations for 1.0, 1.1, 1.2, etc).

**Comment by spiffxp** [comment]
Well, there's a PR with the one delta I now know about :)  If folks are happy with that, can cherrypick back into release-1.2

**Comment by bgrant0607** [comment]
SecurityContextDeny still appears in several admission control lists, including AWS and local-up-cluster.sh:
https://github.com/kubernetes/kubernetes/search?l=bash&q=SecurityContextDeny&utf8=%E2%9C%93

**Comment by spiffxp** [comment]
No longer defaults to being present on local-up-cluster, calling this done
