### ISSUE TITLE
service controller does not clear endpoints if selector is empty

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#25837]
If you create a Service with an empty selector, you see `<none>` endpoints.  If you start with a valid selector (so you get one endpoint) then remove the selector, the endpoint sticks.  If you use a selector that selects no endpoints, it is cleared properly.

@jingxu97 or @mhrgoog this might be an easy one

**Comment by girishkalele** [comment]
@thockin 

Am trying to reproduce this issue - Am unclear on the 'remove the selector' part - will kubectl patch work ?
I used kubectl patch to change the selector to a non-existent pod/label. The Endpoints show <none> immediately after (and the selector patch change also)

[trivial-service.yaml.txt](https://github.com/kubernetes/kubernetes/files/271597/trivial-service.yaml.txt)

`console

$ kubectl create -f trivial-service.yaml 
replicationcontroller "trsvc" created
service "trsvc" created
$ kubectl describe svc trsvc
Name:                   trsvc
Namespace:              default
Labels:                 app=trsvc
Selector:               app=trsvc
Type:                   ClusterIP
IP:                     10.0.186.186
Port:                   iperf   5201/TCP
Endpoints:              10.244.1.6:5201
Session Affinity:       None
No events.

$ kubectl patch svc trsvc -p '{  "spec": { "selector" : { "app" : "foo"} } }'
"trsvc" patched
$ kubectl describe svc trsvc
Name:                   trsvc
Namespace:              default
Labels:                 app=trsvc
Selector:               app=foo
Type:                   ClusterIP
IP:                     10.0.186.186
Port:                   iperf   5201/TCP
Endpoints:              \<none\>
Session Affinity:       None
No events.
`

**Comment by lavalamp** [comment]
IMO, this is working as intended-- `nil` selector means you want to manage the endpoints yourself. The controller has no way to know you don't want that endpoint.

**Comment by lavalamp** [comment]
@girishkalele, @thockin is talking about removing the selector completely. `nil` means you want to provide your own endpoints, `{}` means you want to select every pod. Yes, really, that's the api :/

**Comment by lavalamp** [comment]
Anyway, the only way to fix this is to demarcate system-created endpoints somehow (annotation?), and have the endpoint controller delete them if the label selector is nil. Seems like a lot of work to change this behavior.

**Comment by girishkalele** [comment]
@lavalamp 

Thanks for the explanation - I tried {} and it showed me no difference, but I had only one pod running.

A question for my understanding, with '{}' would it even include pods that don't expose the protocol/port that the service services ?

**Comment by girishkalele** [comment]
@thockin @lavalamp 

So, for the nil case, do want to wipe out the endpoints list ?
And, do we want to change the {} case to also wipe out the endpoint list ?

**Comment by lavalamp** [comment]
IMO you should not wipe out the endpoints list, like I think this issue is
asking for a thing that we should not be doing. Maybe Tim disagrees?

**Comment by thockin** [comment]
Daniel is, not surprisingly, correct.  Once we write a nil/empty selector
the controller has no idea whether the endpoints that exist are there
because a human wanted them there or because they are leftover.  We should
leave them alone.  If we REALLY want to clear them automatically, we would
need an annotation that tells the service controller "I did this", and I
don't think we need that without some concrete use case.  Now that we have
written this out, I predict a user-bug will be filed within 48 hours.
