### ISSUE TITLE
Expose kube-controller-manager's "terminated-pod-gc-threshold" flag so it's configurable via script

### ISSUE THREAD

**Issue by fabioy** [kubernetes/kubernetes#25831]
The default teminated gc pod settings seems to increase the memory utilization on cluster masters to a much higher level than v1.1.x. This is causing some issues. This option is adjustable via this flag, but it needs to be exposed through the salt and startup scripts so it can be changed via env vars.

**Comment by lavalamp** [comment]
This now needs to get plumbed through the GCI setup scripts, not salt.
