### ISSUE TITLE
Expose usage of network volumes via kubelet Summary API

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#25840]
As of now kubelet exports usage of local disk based volumes only. It is useful for users to track usage on network based volumes as well.

**Comment by alex-mohr** [comment]
GCE PDs appear the same as local disks on the VM.  Clarify what you mean by network based volumes?

**Comment by vishh** [comment]
I'm referring to the different types of volume plugins that we support today. Kubelet currently tracks usage of all volumes that share a single partition that kubelet is expected to manage.

**Comment by aaronc** [comment]
Is this metric now visible to end users in current versions of Kubernetes? I'm running Kubernetes 1.4 but am not seeing persistent disk info in Heapster data in InfluxDB.
