### ISSUE TITLE
Discuss:Support local files in cluster\ubuntu\download-release.sh

### ISSUE THREAD

**Issue by lojies** [kubernetes/kubernetes#25854]
As  [http://kubernetes.io/docs/getting-started-guides/ubuntu/](url) introduced,
when i run following command:
`$ KUBERNETES_PROVIDER=ubuntu ./kube-up.sh`
curl in the ubuntu\download-release.sh can't work correctly, because my k8s is installed in a LAN that can't access the internet.

can consider support the following changes:
- add a directory named downloads for example in the cluster\ubuntu\
- users put the correct releases of flannel etcd kubernetes in the downloads directory before running the kube-up.sh
- when running into ubuntu\download-release.sh, add file eixisted judgment before 
  `curl -L https://github.com/......tar.gz` .if file existed, install k8s with local files in the downloads directory .

**Comment by lavalamp** [comment]
@david-mcmahon

**Comment by david-mcmahon** [comment]
@lavalamp is this not just a cluster (or other team) doc/example/usage fix?
