### ISSUE TITLE
e2e flake - Post https://$ip/api: dial tcp $ip: i/o timeout   not to have occurred

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#25855]
Flake looks like the API server was unavailable for a subset of tests. I don't see another flake issue for this:

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25062/kubernetes-pull-build-test-e2e-gce/40667/

```
â€¢ Failure [44.117 seconds]
[k8s.io] Pods
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:508
  should *not* be restarted with a /healthz http liveness probe [Conformance] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:1164

  creating pod liveness-http
  Expected error:
      <*url.Error | 0xc82038cf00>: {
          Op: "Post",
          URL: "https://104.154.95.7/api/v1/namespaces/e2e-tests-pods-6nwro/pods",
          Err: {
              Op: "dial",
              Net: "tcp",
              Source: nil,
              Addr: {
                  IP: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xffh\x9a_\a",
                  Port: 443,
                  Zone: "",
              },
              Err: {},
          },
      }
      Post https://104.154.95.7/api/v1/namespaces/e2e-tests-pods-6nwro/pods: dial tcp 104.154.95.7:443: i/o timeout
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:58
```

From issue https://github.com/kubernetes/kubernetes/pull/25062#issuecomment-220149798

**Comment by lavalamp** [comment]
@euank thanks for report, next time can you include the test name so it's easier to categorize? thanks.

**Comment by lavalamp** [comment]
Wait, nvm, the name is in there I just didn't look carefully enough, sorry.

**Comment by lavalamp** [comment]
guessing at cluster team, maybe network problem? Some connections to apiserver worked...

**Comment by bprashanth** [comment]
This is jenkins builder to apiserver right? so my best guess would be gce network flake or apiserver flake

**Comment by euank** [comment]
I excluded the test name because there were three tests with different names showing the same failure, and they didn't seem related to the given test name. Since random other tests will fail with the same error, I assume, I thought it would be better to have the error highly visible.

**Comment by fejta** [comment]
Assigning to @thockin per team/cluster label

**Comment by goltermann** [comment]
@thockin any update here?  think this is still a valid flake issue?

**Comment by matchstick** [comment]
Closing this issue. If it occurs again we will see with merge bot.
