### ISSUE TITLE
DNS options ndots cause wrong result

### ISSUE THREAD

**Issue by openxxs** [kubernetes/kubernetes#25861]
Kubernetes v1.1.7+e4e6878
Kubelet is started with`--cluster-dns=172.16.40.1 --cluster-domain=xxx.com`;
And SkyDNS RC is created with `--domain=xxx.com` and `--nameservers=10.16.72.188:53`, Kube2sky with `--domain=xxx.com`.
Then I run a docker container, the /etc/resolv.conf in container likes:

> search default.svc.xxx.com svc.xxx.com xxx.com
> nameserver 172.16.40.1
> nameserver 10.16.72.188
> options ndots:5

In this container, I run `nslookup zk.inner.xxx.cn`, **sometimes** it returns wrong result 

> Server:       10.16.72.188
> Address:  10.16.72.188#53
> 
> Non-authoritative answer:
> Name: zk.inner.xxx.cn.svc.xxx.com
> Address: 75.126.101.234` 

which causes error. It seems that "zk.inner.xxx.cn.svc.xxx.com" is passed to 10.16.72.188, instead of "zk.inner.xxx.cn".
When I remove `options ndots:5` in resolv.conf, the problem has gone.
Is it a bug?

**Comment by openxxs** [comment]
I have built another cluster(1 master with 2 slaves) for test, with 3 SkyDNS pods and 1 kube2sky pod. The problem can be re-produced by three steps:
1. create a pod;
2. docker exec into the container created by this pod;
3. sh test.sh:
`#!/bin/sh
for i in {1..10000}; do
  ( ping zk.inner.xxx.cn -c 1 ; ) &
done`
The result includes some wrong records like:

> PING zk.inner.xxx.cn.focus.com...
> ...
> PING zk.inner.xxx.cn.svc.focus.com...
> ...
> PING zk.inner.xxx.cn.default.svc.focus.com...
> ...

These records are very little but exist. I think there is a problem when SkyDNS is busy.

**Comment by jhu-arod** [comment]
I'm experiencing the same thing however I don't know what the solution was for this case.  It seems according to https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configmap-options, that out of the box "Without custom configurations: Any query that does not match the configured cluster domain suffix, such as “www.kubernetes.io”, is forwarded to the upstream nameserver inherited from the node."
