### ISSUE TITLE
e2e flake: kube-proxy liveness probe returns 503

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#25878]
In 1000-Node cluster run a Kubelet failed to download a kube-dns image at first, but after retry it succeeded. Sadly started container wasn't healthy: 
```
Liveness probe for "kube-dns-v11-tcab2_kube-system(bac28ecd-1aaf-11e6-985b-42010af00002):kube2sky" failed (failure): HTTP probe failed with statuscode: 503
```

This caused test to fail, as we had 3 unready system pods: `kube-dns`, `kibana` (depends on `kube-dns`) and ingress (I guess it also depends on `kube-dns`)

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-enormous-cluster/120

cc @kubernetes/goog-cluster @kubernetes/goog-node

**Comment by bprashanth** [comment]
The probe failed because
```
2016/05/15 15:27:41 Client ip 10.240.163.1:33643 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
2016/05/15 15:27:41 Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
, at 2016-05-15 15:27:41.512635648 +0000 UTC, error exit status 1
```

Which failed because 
```

STEP: Logs of kube-system/kube-dns-v11-tcab2:kube2sky on node e2e-enormous-cluster-minion-59lg
May 15 09:03:03.134: INFO: I0515 15:59:51.869734       1 kube2sky.go:485] Etcd server found: http://127.0.0.1:4001
I0515 15:59:52.871976       1 kube2sky.go:552] Using https://10.0.0.1:443 for kubernetes master
I0515 15:59:52.872070       1 kube2sky.go:553] Using kubernetes API <nil>
I0515 15:59:52.872992       1 kube2sky.go:621] Waiting for service: default/kubernetes
I0515 16:00:22.873708       1 kube2sky.go:627] Ignoring error while waiting for service default/kubernetes: Get https://10.0.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.0.0.1:443: i/o timeout. Sleeping 1s before retrying.
F0515 16:00:51.649033       1 kube2sky.go:648] Received signal terminated
```

kube-dns comes up and synchronously waits for the kubernetes service, which was not found apparently. So this seems like apiserver/master problem? The DNS pod just loops and lists, so no watch even: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kube2sky/kube2sky.go#L625

**Comment by fejta** [comment]
Assigning to @thockin per team/cluster label

**Comment by girishkalele** [comment]
@thockin @ArtfulCoder 

Looking to pickup a test flake issue - Is it worth investigating this or wait for the next run now that #23930 is merged ?

**Comment by bprashanth** [comment]
There is a much higher chance this is team/control-plane and not team/cluster give https://github.com/kubernetes/kubernetes/issues/25878#issuecomment-220379438

Also I'm not sure this failure mode will occur post kube-dns rewrite

**Comment by matchstick** [comment]
Closing as DNS rewrite should obsolete this. If this is incorrect. Feel free to re-open.
