### ISSUE TITLE
Error serializing/deserializing protobuf data?

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25870]
I've seen the following error in load test with protobufs:

    go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:182 creating rc load-small-rc-1532 Expected error: <*errors.errorString | 0xc821b8ba90>: { s: "Error creating replication controller: the object provided is unrecognized (must be of type ReplicationController): empty data", } Error creating replication controller: the object provided is unrecognized (must be of type ReplicationController): empty data not to have occurred

It seems to be pretty rare, because other 5 runs of this 6-hour test passed. But it seems something like that can happen.

@smarterclayton

**Comment by smarterclayton** [comment]
This *could* be the retry bug I fixed in #24768 - it looks exactly the same.

**Comment by smarterclayton** [comment]
Retries of PUT/POST to the server would fail, and we trigger retries
above the rate limit in some cases.

**Comment by wojtek-t** [comment]
Yeah - that sounds very probable. Especially because it was in load test on large cluster, where the load was significant.

**Comment by smarterclayton** [comment]
I'll split out the parts of that that aren't correlated with the watch
timeout issue.

**Comment by wojtek-t** [comment]
Thanks @smarterclayton !
I agree that it may be exactly this issue. If so, should be fixed by #25871

**Comment by wojtek-t** [comment]
After merging that PR I think it is fixed. So I'm closing this PR. Will reopen if I face this issue again.
