### ISSUE TITLE
Encoding is being invoked on the same annotation map for pods across two different encodes

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#25880]
I've just seen the following crash of apiserver

    fatal error: I0518 16:49:34.663726    3519 handlers.go:161] PUT /api/v1/namespaces/e2e-tests-density-c37gb/pods/density-latency-pod-1514-xph9f/status: (175.155856ms) 200 [[kubemar        k/v1.3.0 (linux/amd64) kubernetes/952e830] 104.154.120.247:40256]
    concurrent map writes

From the go-routines logs it seems that the victim ones are:

    5953382 goroutine 25813550 [running]:
    5953383 runtime.throw(0x2dab540, 0x15)
    5953384   /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8f10cff90 sp=0xc8f10cff78
    5953385 runtime.mapdelete(0x1f2ef60, 0xc86825cb40, 0xc8f10d0078)
    5953386   /usr/local/go/src/runtime/hashmap.go:559 +0x5a fp=0xc8f10cfff0 sp=0xc8f10cff90
    5953387 k8s.io/kubernetes/pkg/api/v1.Convert_api_Pod_To_v1_Pod(0xc914c6c4b0, 0xc914d6d268, 0x7f6837340900, 0xc8f4398e10, 0x0, 0x0)
    5953388   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:536 +0x5c9 fp=0xc8f10d00d0 sp=0xc8f10cfff0
    5953389 k8s.io/kubernetes/pkg/api/v1.autoConvert_api_PodList_To_v1_PodList(0xc8dac18ba0, 0xc8e7bf20c0, 0x7f6837340900, 0xc8f4398e10, 0x0, 0x0)
    5953390   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/v1/conversion_generated.go:4834 +0x31a fp=0xc8f10d01d8 sp=0xc8f10d00d0
    5953391 k8s.io/kubernetes/pkg/api/v1.Convert_api_PodList_To_v1_PodList(0xc8dac18ba0, 0xc8e7bf20c0, 0x7f6837340900, 0xc8f4398e10, 0x0, 0x0)
    5953392   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/v1/conversion_generated.go:4845 +0x4b fp=0xc8f10d0210 sp=0xc8f10d01d8
    5953393 runtime.call64(0xc8206778c0, 0x32c6778, 0xc840badaa0, 0x2000000030)
    5953394   /usr/local/go/src/runtime/asm_amd64.s:473 +0x3e fp=0xc8f10d0258 sp=0xc8f10d0210
    5953395 reflect.Value.call(0x23ce0c0, 0x32c6778, 0x13, 0x2b79030, 0x4, 0xc8f10d0778, 0x3, 0x3, 0x0, 0x0, ...)
    5953396   /usr/local/go/src/reflect/value.go:435 +0x120d fp=0xc8f10d05a8 sp=0xc8f10d0258
    5953397 reflect.Value.Call(0x23ce0c0, 0x32c6778, 0x13, 0xc8f10d0778, 0x3, 0x3, 0x0, 0x0, 0x0)
    5953398   /usr/local/go/src/reflect/value.go:303 +0xb1 fp=0xc8f10d0608 sp=0xc8f10d05a8
    5953399 k8s.io/kubernetes/pkg/conversion.(*Converter).callCustom(0xc8201cc200, 0x29ac1c0, 0xc8dac18ba0, 0x16, 0x2ab5400, 0xc8e7bf20c0, 0x16, 0x23ce0c0, 0x32c6778, 0x13, ...)
    5953400   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/conversion/converter.go:584 +0x4f4 fp=0xc8f10d07c8 sp=0xc8f10d0608
    5953401 k8s.io/kubernetes/pkg/conversion.(*Converter).convert(0xc8201cc200, 0x27236e0, 0xc8dac18ba0, 0x199, 0x284d180, 0xc8e7bf20c0, 0x199, 0xc8f4398e10, 0x0, 0x0)
    5953402   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/conversion/converter.go:627 +0xb76 fp=0xc8f10d0980 sp=0xc8f10d07c8
    5953403 k8s.io/kubernetes/pkg/conversion.(*Converter).(k8s.io/kubernetes/pkg/conversion.convert)-fm(0x27236e0, 0xc8dac18ba0, 0x199, 0x284d180, 0xc8e7bf20c0, 0x199, 0xc8f4398e10, 0x0, 0x0)
    5953404   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/conversion/converter.go:524 +0x84 fp=0xc8f10d09d8 sp=0xc8f10d0980
    5953405 k8s.io/kubernetes/pkg/conversion.(*Converter).doConversion(0xc8201cc200, 0x29ac1c0, 0xc8dac18ba0, 0x2ab5400, 0xc8e7bf20c0, 0x0, 0xc8eedf8698, 0xc8f10d0c18, 0x0, 0x0)
    5953406   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/conversion/converter.go:561 +0x45e fp=0xc8f10d0b78 sp=0xc8f10d09d8
    5953407 k8s.io/kubernetes/pkg/conversion.(*Converter).Convert(0xc8201cc200, 0x29ac1c0, 0xc8dac18ba0, 0x2ab5400, 0xc8e7bf20c0, 0x0, 0xc8eedf8698, 0x0, 0x0)
    5953408   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/conversion/converter.go:524 +0x28d fp=0xc8f10d0c48 sp=0xc8f10d0b78
    5953409 k8s.io/kubernetes/pkg/runtime.(*Scheme).UnsafeConvertToVersion(0xc8201c4340, 0x7f683733b850, 0xc8dac18ba0, 0x0, 0x0, 0x2b85300, 0x2, 0x0, 0x0, 0x0, ...)
    5953410   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/runtime/scheme.go:586 +0x1540 fp=0xc8f10d10f8 sp=0xc8f10d0c48
    5953411 k8s.io/kubernetes/pkg/runtime.unsafeObjectConvertor.ConvertToVersion(0xc8201c4340, 0x7f683733b850, 0xc8dac18ba0, 0x0, 0x0, 0x2b85300, 0x2, 0x0, 0x0, 0x0, ...)
    5953412   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/runtime/helper.go:61 +0x8e fp=0xc8f10d1158 sp=0xc8f10d10f8
    5953413 k8s.io/kubernetes/pkg/runtime/serializer/versioning.(*codec).EncodeToStream(0xc901634cb0, 0x7f683733b850, 0xc8dac18ba0, 0x7f6837362488, 0xc83df9bc20, 0x0, 0x0, 0x0, 0x0, 0x0)
    5953414   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/runtime/serializer/versioning/versioning.go:268 +0xb4d fp=0xc8f10d1438 sp=0xc8f10d1158
    5953415 k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x7f683733ffa8, 0xc8206ce150, 0x0, 0x0, 0x2b85300, 0x2, 0x7f6837362120, 0xc83df9bc20, 0xc8e31e90a0, 0xc8, ...)
    5953416   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:443 +0x30e fp=0xc8f10d1520 sp=0xc8f10d1438
    5953417 k8s.io/kubernetes/pkg/apiserver.write(0xc8, 0x0, 0x0, 0x2b85300, 0x2, 0x7f683733ffa8, 0xc8206ce150, 0x7f683733b850, 0xc8dac18ba0, 0x7f6837362120, ...)
    5953418   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:427 +0xb70 fp=0xc8f10d1748 sp=0xc8f10d1520
    5953419 k8s.io/kubernetes/pkg/apiserver.ListResource.func1(0xc8d9ab9110, 0xc8dac18300)
    5953420   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:327 +0xeb3 fp=0xc8f10d1b48 sp=0xc8f10d1748
    5953421 k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc8d9ab9110, 0xc8dac18300)
    5953422   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x25c fp=0xc8f10d1c28 sp=0xc8f10d1b48
    5953423 k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc8201dea20, 0x7f6837361f98, 0xc83df9bc00, 0xc8e31e90a0)
    5953424   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:249 +0xf30 fp=0xc8f10d1de0 sp=0xc8f10d1c28
    5953425 k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7f6837361f98, 0xc83df9bc00, 0xc8e31e90        a0)
    5953426   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:95 +0x3e fp=0xc8f10d1e08 sp=0xc8f10d1de0
    5953427 net/http.HandlerFunc.ServeHTTP(0xc820d49880, 0x7f6837361f98, 0xc83df9bc00, 0xc8e31e90a0)
    5953428   /usr/local/go/src/net/http/server.go:1618 +0x3a fp=0xc8f10d1e28 sp=0xc8f10d1e08
    5953429 net/http.(*ServeMux).ServeHTTP(0xc820416c90, 0x7f6837361f98, 0xc83df9bc00, 0xc8e31e90a0)
    5953430   /usr/local/go/src/net/http/server.go:1910 +0x17d fp=0xc8f10d1e80 sp=0xc8f10d1e28
    5953431 k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7f6837361f98, 0xc83df9bc00, 0xc8e31e90a0)
    5953432   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157 fp=0xc8f10d1f08 sp=0xc8f10d1e80
    5953433 net/http.HandlerFunc.ServeHTTP(0xc8203bb8c0, 0x7f6837361f98, 0xc83df9bc00, 0xc8e31e90a0)
    5953434   /usr/local/go/src/net/http/server.go:1618 +0x3a fp=0xc8f10d1f28 sp=0xc8f10d1f08
    5953435 k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP.func1(0xc820634a80, 0x7f6837361f58, 0xc83df9bc00, 0xc8e31e90a0, 0xc8dac18120)
    5953436   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:191 +0x91 fp=0xc8f10d1f68 sp=0xc8f10d1f28
    5953437 runtime.goexit()
    5953438   /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8f10d1f70 sp=0xc8f10d1f68
    5953439 created by k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP
    5953440   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:193 +0x15b

and

    6505750 goroutine 25813385 [runnable]:
    6505751 reflect.mapiterinit(0x2634200, 0xc9235c56b0, 0x195)
    6505752   /usr/local/go/src/runtime/hashmap.go:1014 +0x4a
    6505753 reflect.Value.MapKeys(0x2634200, 0xc8e0514f98, 0x195, 0x0, 0x0, 0x0)
    6505754   /usr/local/go/src/reflect/value.go:1075 +0xec
    6505755 encoding/json.(*mapEncoder).encode(0xc820880378, 0xc8db7ff970, 0x2634200, 0xc8e0514f98, 0x195, 0x1c000)
    6505756   /usr/local/go/src/encoding/json/encode.go:614 +0xd6
    6505757 encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x2634200, 0xc8e0514f98, 0x195, 0x0)
    6505758   /usr/local/go/src/encoding/json/encode.go:632 +0x51
    6505759 encoding/json.(*structEncoder).encode(0xc821031440, 0xc8db7ff970, 0x27ffae0, 0xc8e0514f90, 0x199, 0x1c000)
    6505760   /usr/local/go/src/encoding/json/encode.go:587 +0x2c4
    6505761 encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x27ffae0, 0xc8e0514f90, 0x199, 0x0)
    6505762   /usr/local/go/src/encoding/json/encode.go:601 +0x51
    6505763 encoding/json.(*structEncoder).encode(0xc821030930, 0xc8db7ff970, 0x2add560, 0xc8e0514f00, 0x199, 0x1c000)
    6505764   /usr/local/go/src/encoding/json/encode.go:587 +0x2c4
    6505765 encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x2add560, 0xc8e0514f00, 0x199, 0x2add500)
    6505766   /usr/local/go/src/encoding/json/encode.go:601 +0x51
    6505767 encoding/json.(*arrayEncoder).encode(0xc820686b90, 0xc8db7ff970, 0x1eddca0, 0xc922064ee0, 0x197, 0x1c000)
    6505768   /usr/local/go/src/encoding/json/encode.go:690 +0x11b
    6505769 encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x1eddca0, 0xc922064ee0, 0x197, 0x0)
    6505770   /usr/local/go/src/encoding/json/encode.go:697 +0x51
    6505771 encoding/json.(*sliceEncoder).encode(0xc820686b98, 0xc8db7ff970, 0x1eddca0, 0xc922064ee0, 0x197, 0x1c000)
    6505772   /usr/local/go/src/encoding/json/encode.go:667 +0xb0
    6505773 encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x1eddca0, 0xc922064ee0, 0x197, 0x0)
    6505774   /usr/local/go/src/encoding/json/encode.go:676 +0x51
    6505775 encoding/json.(*structEncoder).encode(0xc82112fbf0, 0xc8db7ff970, 0x2add8e0, 0xc922064eb0, 0x199, 0x1c000)
    6505776   /usr/local/go/src/encoding/json/encode.go:587 +0x2c4
    6505777 encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x2add8e0, 0xc922064eb0, 0x199, 0x0)
    6505778   /usr/local/go/src/encoding/json/encode.go:601 +0x51
    6505779 encoding/json.(*structEncoder).encode(0xc82112fb00, 0xc8db7ff970, 0x28c72c0, 0xc922064dc0, 0x199, 0x1bd00)
    6505780   /usr/local/go/src/encoding/json/encode.go:587 +0x2c4
    6505781 encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x28c72c0, 0xc922064dc0, 0x199, 0x28c7200)
    6505782   /usr/local/go/src/encoding/json/encode.go:601 +0x51
    6505783 encoding/json.(*arrayEncoder).encode(0xc820686e08, 0xc8db7ff970, 0x1ede780, 0xc914313ba0, 0x197, 0x0)
    6505784   /usr/local/go/src/encoding/json/encode.go:690 +0x11b
    6505785 encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x1ede780, 0xc914313ba0, 0x197, 0x0)
    6505786   /usr/local/go/src/encoding/json/encode.go:697 +0x51
    6505787 encoding/json.(*sliceEncoder).encode(0xc820686e10, 0xc8db7ff970, 0x1ede780, 0xc914313ba0, 0x197, 0x0)
    6505788   /usr/local/go/src/encoding/json/encode.go:667 +0xb0
    6505789 encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x1ede780, 0xc914313ba0, 0x197, 0x0)
    6505790   /usr/local/go/src/encoding/json/encode.go:676 +0x51
    6505791 encoding/json.(*structEncoder).encode(0xc82112f9b0, 0xc8db7ff970, 0x284d180, 0xc914313b60, 0x199, 0x7f6800000000)
    6505792   /usr/local/go/src/encoding/json/encode.go:587 +0x2c4
    6505793 encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x284d180, 0xc914313b60, 0x199, 0xc914313b00)
    6505794   /usr/local/go/src/encoding/json/encode.go:601 +0x51
    6505795 encoding/json.(*ptrEncoder).encode(0xc820686e18, 0xc8db7ff970, 0x2ab5400, 0xc914313b60, 0x16, 0x0)
    6505796   /usr/local/go/src/encoding/json/encode.go:709 +0xea
    6505797 encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc8db7ff970, 0x2ab5400, 0xc914313b60, 0x16, 0xc914313b00)
    6505798   /usr/local/go/src/encoding/json/encode.go:714 +0x51
    6505799 encoding/json.(*encodeState).reflectValue(0xc8db7ff970, 0x2ab5400, 0xc914313b60, 0x16)
    6505800   /usr/local/go/src/encoding/json/encode.go:301 +0x6b
    6505801 encoding/json.(*encodeState).marshal(0xc8db7ff970, 0x2ab5400, 0xc914313b60, 0x0, 0x0)
    6505802   /usr/local/go/src/encoding/json/encode.go:274 +0xa9
    6505803 encoding/json.(*Encoder).Encode(0xc8e39c2b58, 0x2ab5400, 0xc914313b60, 0x0, 0x0)
    6505804   /usr/local/go/src/encoding/json/stream.go:188 +0x94
    6505805 k8s.io/kubernetes/pkg/runtime/serializer/json.(*Serializer).EncodeToStream(0xc8201c4380, 0x7f683733c048, 0xc914313b60, 0x7f6837362488, 0xc8442738c8, 0x0, 0x0, 0x0, 0x0, 0x0)
    6505806   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/runtime/serializer/json/json.go:185 +0x323
    6505807 k8s.io/kubernetes/pkg/runtime.(*SerializerInfo).EncodeToStream(0xc927271da0, 0x7f683733c048, 0xc914313b60, 0x7f6837362488, 0xc8442738c8, 0x0, 0x0, 0x0, 0x0, 0x0)
    6505808   <autogenerated>:34 +0xbe
    6505809 k8s.io/kubernetes/pkg/runtime/serializer/versioning.(*codec).EncodeToStream(0xc91c5a6460, 0x7f683733c048, 0xc914313b60, 0x7f6837362488, 0xc8442738c8, 0x0, 0x0, 0x0, 0x0, 0x0)
    6505810   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/runtime/serializer/versioning/versioning.go:277 +0xc38
    6505811 k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x7f683733ffa8, 0xc8206ce150, 0x0, 0x0, 0x2b85300, 0x2, 0x7f6837362120, 0xc8442738c8, 0xc8da52eee0, 0xc8, ...)
    6505812   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:443 +0x30e
    6505813 k8s.io/kubernetes/pkg/apiserver.write(0xc8, 0x0, 0x0, 0x2b85300, 0x2, 0x7f683733ffa8, 0xc8206ce150, 0x7f683733b850, 0xc8e6d11f20, 0x7f6837362120, ...)
    6505814   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:427 +0xb70
    6505815 k8s.io/kubernetes/pkg/apiserver.ListResource.func1(0xc8d9ea8510, 0xc8e6d11bc0)
    6505816   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:327 +0xeb3
    6505817 k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc8d9ea8510, 0xc8e6d11bc0)
    6505818   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x25c
    6505819 k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc8201dea20, 0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505820   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:249 +0xf30
    6505821 k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7f6837361f98, 0xc844273898, 0xc8da52ee        e0)
    6505822   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:95 +0x3e
    6505823 net/http.HandlerFunc.ServeHTTP(0xc820d49880, 0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505824   /usr/local/go/src/net/http/server.go:1618 +0x3a
    6505825 net/http.(*ServeMux).ServeHTTP(0xc820416c90, 0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505826   /usr/local/go/src/net/http/server.go:1910 +0x17d
    6505827 k8s.io/kubernetes/pkg/apiserver.WithAuthorizationCheck.func1(0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505828   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:482 +0xf4
    6505829 net/http.HandlerFunc.ServeHTTP(0xc82028a6c0, 0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505830   /usr/local/go/src/net/http/server.go:1618 +0x3a
    6505831 k8s.io/kubernetes/pkg/apiserver.WithImpersonation.func1(0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505832   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:417 +0xfe
    6505833 net/http.HandlerFunc.ServeHTTP(0xc82028a700, 0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505834   /usr/local/go/src/net/http/server.go:1618 +0x3a
    6505835 k8s.io/kubernetes/pkg/auth/handlers.NewRequestAuthenticator.func1(0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505836   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:47 +0x1c5
    6505837 net/http.HandlerFunc.ServeHTTP(0xc8203ff4f0, 0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505838   /usr/local/go/src/net/http/server.go:1618 +0x3a
    6505839 k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505840   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
    6505841 net/http.HandlerFunc.ServeHTTP(0xc8203bb880, 0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505842   /usr/local/go/src/net/http/server.go:1618 +0x3a
    6505843 k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505844   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
    6505845 net/http.HandlerFunc.ServeHTTP(0xc8203bb8a0, 0x7f6837361f98, 0xc844273898, 0xc8da52eee0)
    6505846   /usr/local/go/src/net/http/server.go:1618 +0x3a
    6505847 k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP.func1(0xc8206395e0, 0x7f6837361f58, 0xc844273898, 0xc8da52eee0, 0xc8e6d11b00)
    6505848   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:191 +0x91
    6505849 created by k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP
    6505850   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:193 +0x15b

It seems that we are using UnsafeConvertToVersion too optimistically (or doing something wrong elsewhere).

@smarterclayton @lavalamp @kubernetes/sig-api-machinery

**Comment by wojtek-t** [comment]
Logs coming from this run:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-kubemark-gce-scale/1161/?project=kubernetes-jenkins

**Comment by smarterclayton** [comment]
So this may mean that someone is mutating an object they are sending to serialization.  Which is a terrifying issue.

**Comment by smarterclayton** [comment]
I.e. an object is being pulled out of a cache and reused.  It is *good* that this was caught.

**Comment by smarterclayton** [comment]
An object being mutated within the `Encode` call has undefined behavior, which is a p0.

**Comment by smarterclayton** [comment]
Ok, so the same object is being encoded at the same time, and annotations is being mutated by the init containers (I think).

**Comment by smarterclayton** [comment]
So this isn't a copy, it's a mutation.

**Comment by smarterclayton** [comment]
Hrm... trying to think of why two threads would have the same annotation map in the current code.  The current code should be creating a copy of the underlying map.  And then changing the copy.  Which means the current code is *not* copying the map.

**Comment by smarterclayton** [comment]
Um... were we using ugorji for serializing JSON before?  Not related, but surprising.

**Comment by wojtek-t** [comment]
IIRC we were using it only for deserialization.

**Comment by smarterclayton** [comment]
I think this means that something in a code path is copying the same annotation map into multiple pods somehow.  Deep copy and conversion are (or should) both be copying them.  But, by the time encode is invoked, the two have the same annotation map.

**Comment by lavalamp** [comment]
agree w/ P0 marking & diagnosis so far

**Comment by smarterclayton** [comment]
Some notes:

UnsafeConversion should not be unsafe yet.  It's just preparation.
The annotation map should have been copied.  If that's not the case, it would be the simplest explanation for the mutation.  If it was copied, then we might have to find a more exotic explanation.

**Comment by smarterclayton** [comment]
How old was this code?  It shouldn't be calling through the reflection code, unless the fast path broke.

**Comment by smarterclayton** [comment]
Realized we never added a pod list fast path.

**Comment by smarterclayton** [comment]
Found it.  It was init containers, we were accidentally mutating the inner object in the wrong place.

**Comment by smarterclayton** [comment]
Fix open

**Comment by wojtek-t** [comment]
@smarterclayton - thanks for debugging and fixing!
