### ISSUE TITLE
Jenkins unit/integration — No test results found.

### ISSUE THREAD

**Issue by ping035627** [kubernetes/kubernetes#25883]
FROM https://github.com/kubernetes/kubernetes/pull/25606

Verifying ./hack/../hack/verify-flags-underscore.py SUCCESS ./hack/../hack/verify-flags-underscore.py 58s Build step 'Execute shell' marked build as failure Recording test results ERROR: Step 鈥楶ublish JUnit test result report鈥� failed: No test report files were found. Configuration error? [PostBuildScript] - Execution post build scripts. [kubernetes-pull-test-unit-integration@2] $ /bin/bash -xe /tmp/hudson1472969172450311051.sh
* [[ -x ./hack/jenkins/upload-to-gcs.sh ]]
* ./hack/jenkins/upload-to-gcs.sh Called without JENKINS_BUILD_STARTED or JENKINS_BUILD_FINISHED set. Assuming a legacy invocation. Run finished at Tue May 17 20:25:26 PDT 2016 Uploading to gs://kubernetes-jenkins/pr-logs/pull/25606/kubernetes-pull-test-unit-integration/26441 (attempt 1) Uploading build result: [UNSET] Marking build 26441 as the latest completed build
*** View logs and artifacts at https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25606/kubernetes-pull-test-unit-integration/26441 ***

**Comment by lavalamp** [comment]
```
Verifying ./hack/../hack/verify-gofmt.sh
!!! 'gofmt -s' needs to be run on the following files: 
./plugin/pkg/scheduler/generic_scheduler.go
FAILED   ./hack/../hack/verify-gofmt.sh	11s
```

This is not a flake, it doesn't get to the junit files if you don't pass the linters. Sorry that the output isn't clear right now :(
