### ISSUE TITLE
Add cassandra image to test/images , fix e2e test

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#25889]
Problem 

Cassnandra tests recently reported as broken, should use petsets, should have a better example, and should use the latest image from chriss which has a more production-sane set of defaults.

Solution

Have @chrislovecnm iterate a couple of PRs in so that we can move towards a productionable, fully working cassandra e2e  again.

**Comment by jayunit100** [comment]
needs #25583 to start.

**Comment by chrislovecnm** [comment]
@jayunit100 might be a good idea to keep the image needs to be in one.  Cause we would have a mess if we have it in two ... We can move it out of examples.

cc @bgrant0607 @kubernetes/examples 

The need needs to be improved:

1. create petset
2. exec nodetool status or cqlsh against the cluster

Parsing logs just AINT right 😄

**Comment by chrislovecnm** [comment]
Also this is related: https://github.com/kubernetes/kubernetes/issues/20999

**Comment by chrislovecnm** [comment]
@kubernetes/examples any recommendations on steps 2 &3 that I listed above?  Would be a good pattern to have for all of our examples.  We would need the base docker template (debian image) on gcr.io.  Docker hub at times SUCKS.

**Comment by pwittrock** [comment]
>
1. install local repo
2. push the docker to local repo

Are these steps to run a docker registry inside the cluster?  Sorry if this was discussed already, but why is this necessary?

**Comment by pwittrock** [comment]
Nevermind, I see this is to test the image from #26023

**Comment by chrislovecnm** [comment]
@pwittrock I thought of pushing the image to a local google project registry, but then the e2e test would only work when hosted in Google cloud.

Maybe both?

**Comment by pwittrock** [comment]
@chrislovecnm Is the image built as part of the example, or can we pre-build it and get someone with permissions to stick it in gcr.io?

**Comment by chrislovecnm** [comment]
@pwittrock the image is built as part of the example, and it is pre-built and uploaded to gcr.io.  What I am thinking is more automation and testing.  This can impact all examples, not just Cassandra.

@jayunit100 you think a title change for this issue is appropriate?

**Comment by pwittrock** [comment]
@lavalamp Another case where it would be helpful to build and push container images for use in e2e tests.

**Comment by chrislovecnm** [comment]
@jayunit100 https://github.com/kubernetes/kubernetes/pull/30577 is mergered and this is addressed. Shall we close?

**Comment by chrislovecnm** [comment]
@jayunit100 seems that we have a flaky test.  Please hold off closing.

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @chrislovecnm @jayunit100

**Comment by chrislovecnm** [comment]
This should be resolved.  The name change to StatefulSet cause issues as well, but it should be fixed now.

**Comment by dims** [comment]
@chrislovecnm Cool. Let me close this out then.
