### ISSUE TITLE
Determine docker version(s) for Kubernetes 1.3 release 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#25893]
Each docker release has some known issues running in Kubernetes as a runtime. Node team spent a lot of time on validating each release, and decided which release(s) as validated / recommended one(s), and documented the known issues for each, etc. For kubernetes 1.3, we validated both 1.10 (https://github.com/kubernetes/kubernetes/issues/19720) and 1.11 (https://github.com/kubernetes/kubernetes/issues/23397). Currently, we are running soaking tests against docker 1.11.1, and planed to have similar soak for 1.10 too. 

cc/ @kubernetes/goog-node @zmerlynn @andyzheng0831 @derekwaynecarr

**Comment by apatil** [comment]
@dchen1107, which storage backends do you test when validating?

**Comment by dchen1107** [comment]
@apatil By default the validation is running against aufs, but redhat is validating docker against devicemapper. Also internally, we started validation against overlayfs too lately through our new cloud image: gci.

**Comment by apatil** [comment]
@dchen1107 Does that mean you're testing against something Debian-based, or is there a method you recommend for installing aufs on CentOS? I'd like to get as close as possible to a validated setup, but need to use Rhel 7.

**Comment by yujuhong** [comment]
We test debian + aufs, and [GCI](https://cloud.google.com/compute/docs/containers/vm-image/) (chromium os-based) + overlayfs.

For Rhel 7, you should probably stick to redhat folks's recommendation for storage backend and docker version.

**Comment by dchen1107** [comment]
Currently Kubelet supports 3 graph drivers: devicemapper (Redhat / openshift), aufs (GCE / GKE), and overlayfs (CoreOS / GCI). We are working on node conformance tests which including runtime too, but not that yet.

**Comment by apatil** [comment]
Thanks, I appreciate the clarifications.

**Comment by apatil** [comment]
@dchen1107, out of curiosity will you be supporting ZFS on late Ubuntu versions?

**Comment by vishh** [comment]
@apatil We are not testing against zfs as of now. We can add testing for zfs in the future, but we are already spread too thin testing three storage drivers. Given that the community is enabling distributed testing, we'd encourage testing for additional storage drivers by the community.

**Comment by derekwaynecarr** [comment]
@dchen1107 - is there a date you want to have known issues gathered by for docker 1.10?  For RHEL based platforms, we will have some data based on the *docker version packaged by Red Hat* , which as discussed would be docker 1.10 with the patches specifically enumerated for whatever docker 1.10.x is packaged at the time.  We would then publish the list of those carried patches per our normal convention.

https://github.com/projectatomic/docker/blob/fedora-1.10.3/README.md
https://github.com/projectatomic/docker/blob/rhel7-1.10.3/README.md

**Comment by erictune** [comment]
Status update: this issue is open just to remind us to document what the recommended docker version is for 1.3.

**Comment by stefanodoni** [comment]
Hi guys,

Any news about that?

As k8s 1.3 has been officially released, what's the recommended docker version?

Thank you

**Comment by yujuhong** [comment]
From https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#known-issues-and-important-steps-before-upgrading: 
"The following versions of Docker Engine are supported - v1.10, v1.11 Although v1.9 is still compatible, we recommend upgrading to one of the supported versions. All prior versions of docker will not be supported."

**Comment by goltermann** [comment]
This is an issue marked v1.3 and kind/documentation.  Can you get it fixed up this week?

**Comment by dchen1107** [comment]
I am closing this one since all validation and release doc were done for 1.3 release.
