### ISSUE TITLE
unit test flake: TestOfferStorage

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#25891]
Hit this in #25509

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25509/kubernetes-pull-test-unit-integration/26630/

[Log](https://00e9e64bac56e6ab763091cf4c6a56daf7ac2fa782f3cf747e-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F25509%2Fkubernetes-pull-test-unit-integration%2F26630%2Fartifacts%2Fjunit_v1,extensions-v1beta1,metrics-v1alpha1,federation-v1alpha1_20160518-214542.stdout?qk=AD5uMEvcowIsgEu1U1-NSdGSx4BeYRtqZ0IGgPIy_MULP7NAkMkbCt_1sGkRE9yqDfMm0WCs6adY-TOmKRxX7EtzppIdLxTDyJLN_YSkPhWl20x5KSXjDbaeuaC1guQQK1dxSHA8ieho2EfUzgiCKTrmquopAURyMoYhc8ZMrrMzyr0xw9O26Fpv9SQ6d8U7P1I37zmN0xp4APDJkeRvAhMjSI8a27PX5_V9X9pK1N9N4LFDfO3nij15JmcffziOggRdJugCSf3wY8_F_IKIZfFrdMryWzOstF4Jeapgzn6XcwY-5VWUhP2jGKXoMLtvOq5Qjpqby_a4oLTFix1kFc0qugIsz1g7GjmxpzrbxnohP72tVBGXIcxPq4zzdY0fCoHBI9MsBAWmXFSQswqmtsv3DAyeMhrqatAdVC20BnzDve0f03j0XTNHLYiVFRra26fkYxiXejl5q8vPl8sSYsLfDVY7NTCwsDTxwV6sDtLOi_tlsJJ1X69ni89yJwTG4tnJdstiVuw5SnrjLK6lZ19i3kzrdWHxcEVUWPQkhosJcN69DkktzUzSOK5E7uh5wPVgoo7yrCfLPGjlAK22hFHXmQtcccHyg2v7I9EhbkI2YP5xkKB0aqmr4RBLo9LB-c2YnLFXJbUeaIcVQOfRZ0stm442RCwV_sw7Aj8Ryd9FGKux7s6foaiUstbDTJVt-gfWGfBi88fD1xh_eFjmBdmEV5QCnfBanwUCdHlqj4f_RW176vVswXsCjjTrmwftB_wBvOE68fowxKMYpiq1pXQlsDtk1l8X85TsHQoeXCCJbhPna81MsUsaQMnEsErwAONFLa1XkQydBsjeujby_sAwMy5B9Emotdd045YAdW_9dMMAjAe7p2sd2NapBPPXXEI4uI4wCodS3e1l4F57ee_7p-LCX5I3b6ukO3ZG3K0Q7H0rURxjL7Eh2_7uPyfv0q8kR6H73y0Mf2ND40IBvgrWYeoF6raD6bGqczhmmlQ8R0Pbx-I_0COIcCx2dI5-vHNZe1j3WZMTS9y380yMU5Gk-aHX0qGJsw):
```
--- FAIL: TestOfferStorage (1.86s)
	offers_test.go:163: released offer is not declined after 2*ttl
FAIL	k8s.io/kubernetes/contrib/mesos/pkg/offers	4.408s
```

**Comment by ncdc** [comment]
The code and test probably need to be updated to use `util.Clock` so the tests can be properly time-controlled instead of using `time.Sleep()`

**Comment by fejta** [comment]
Assigning to @karlkfi per https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/OWNERS

**Comment by k82cn** [comment]
In `TestOfferStorage`, the TTL is 0.25s; the offer will be declined after `2*ttl` and the test sleep `3*ttl` as tolerated time. The PR increased the tolerated time to `4*ttl` which does not impact the expected result.

**Comment by k82cn** [comment]
@jdef , @deads2k , should we close all those issues and trace them in https://github.com/kubernetes-incubator/kube-mesos-framework/ ?

**Comment by deads2k** [comment]
> @jdef , @deads2k , should we close all those issues and trace them in https://github.com/kubernetes-incubator/kube-mesos-framework/ ?

Yes.
