### ISSUE TITLE
Flake: garbage_collector_test.go:211: timed out waiting for the condition

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#25890]
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-test-go/12285/

@caesarxuchao maybe we can now reduce the amount of work it does a bit? Maybe you can look at the logs to double check that it's not a deadlock or anything first.

**Comment by caesarxuchao** [comment]
The log says it's timed out waiting for the GC to observe the deletion of the RC. It seems the GC never received the deletion of RC in 120s.

**Comment by lavalamp** [comment]
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-test-go/12296/

**Comment by lavalamp** [comment]
This has failed like four times in a row. Going to make a PR to stop the bleeding.

**Comment by lavalamp** [comment]
@caesarxuchao Please undo my "fix" when you figure this out :) I don't know why it got so much worse all of a sudden.

**Comment by caesarxuchao** [comment]
This is the [log](https://00e9e64bacc66d0c5d67dd11645e9aeeebbe0a594e562a9a9c-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F25923%2Fkubernetes-pull-test-unit-integration%2F26797%2Fbuild-log.txt?qk=AD5uMEvE-gWUewGqubcPSI-kHocbeN_4mlgqQ8h9HQPS8Xd3TNV_b9q4mwq_GbWVG1wPcuOrPrs6IThQrmEnq8TjZHDMSY6Dn_rZqNDybLPCWYzjPmV-WWotucU7ReYQYN3aibzqiY9SwbhwoGTAAzHxk-YtEyJXL5Y5CwV7sX_2_jMMGrcF6JWfZ7BnLBnvyhEd_PFNV6l-9bNqTSbClQHZONm90fr0lm2hW663zlr0T-Hpw8UAxl0jk2ohAXDauYAAnpI0be0KuVb9spfsIvjQG6iQGVQut9mof4ZTjzPlOCEzouHoWuzkGkHpRDE_eWtAT544ImDGIXM7QkO1XftFz6-OLCgJj_QowVJnmvGw1GxDbKiBUtaTBZxeGkYKQURQZr1prmKq4U5AFrBmx27wD2bB8r07CJKwG2YPca5xFFTsZgpENa8S8O5E348I9fFmLF9NcD1bfNGe_ZNlBBR0PRMxtk5HODfztueSKlVOR5XcElC2GZSJJWQXTGuFfb-0szeMpJRJd00cBq8j1p9Vw1NcVg3NRangLAYZNDxw4zHFsdD8Z3t4XK5PpO4h0UGEWQEVIzcIyacvQumQEOf47nHqxTrQ8OE2gJUWpGYhYoXUSqLcy98YmNLnK2z0pjo3IQgKNsxwcEfSP-k1oOi0bck51rHJrGVu6MuZvFKxNK7JGDdkQXEE6pdyqIRQtHebMYAR8iZmpaanfJnkcxJiOprb3OPlusib7x0VKBCawdmJBecNq0CJfRWw6hhpoaSJCCCbaNAL24q8oLlC8xZqZGLb5MUm8RBTgGNbSD3_QPtlrBpYZvnL2lZkep9PZi_ZHdXJEtmfYA_sT6-KOZK7712tOfhyJ4DBzWtSVXme0yEOEtZdJtfvcOWZBuXYGiJIIdtKt8DVZEvQ-MBneeV7Gx3FbMdivh50XI6jM93k12EaLGlFb5w) of 25923 which prints verbose log. It seems the GC never sees the creation of the RC, but never sees the deletion of it. @lavalamp do you have any clue?

**Comment by caesarxuchao** [comment]
There is a slight change #25599 will fix this, there is a potential race on the graph in this test, though I would expect go's race detector would have caught it.

**Comment by lavalamp** [comment]
@caesarxuchao This is fixed, right? Or is it not merged yet?

**Comment by caesarxuchao** [comment]
Yes, fixed by #26493. Closing.
