### ISSUE TITLE
Publishing newer kubectl container images

### ISSUE THREAD

**Issue by adleong** [kubernetes/kubernetes#25900]
kubectl container images should be published with each release.

**Comment by lavalamp** [comment]
We should cut them with a sensible location & tag, e.g. gcr.io/kubernetes/kubectl:1.2.3

**Comment by dims** [comment]
Looks like we have something to start with here:
https://github.com/kubernetes/kubernetes/tree/master/examples/kubectl-container

**Comment by bgrant0607** [comment]
Dupe of #16437
