### ISSUE TITLE
kubelet container manager cgroup detection should error if cpu and memory differ

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#25909]
`kubelet` container manager setup node routine should ensure that cpu and memory cgroups for container runtime are of the same value, and warn if they are equal to `/`.

For background, on systemd environments, the default unit file for `docker` has CPU and Memory accounting not enabled, so the /proc/.../cgroup file reports `/` as cpu cgroup.

https://github.com/kubernetes/kubernetes/pull/25907#issuecomment-220449234

**Comment by vishh** [comment]
Looking forward to the fix @derekwaynecarr

**Comment by derekwaynecarr** [comment]
The PR that fixes this issue was prematurely merged by the merge bot so re-opening.
