### ISSUE TITLE
Client Cert Authentication

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#2591]
In a recent hangout @jbeda described a scheme where nodes would either:
1. have a PKI certificate distributed to them as part of the node setup process, 
2. or generate their own certificate and somehow distribute it to the apiserver (used in environments with simpler security models), possibly involving a "rendezvous point" (@jbeda to publish doc on this).

This is separate but complementary to the kubelet self registration work by @brendandburns in #2435.

Proposal:
- I'll write an authenticator module that accepts clients who present client certs that are signed by the same root CA as the master's cert.  This seems like it fits well with option 1 above.  I don't understand option 2 well enough yet to know if it will work.  But it seems needed for 1 so I propose to write it regardless.
-  associcate such a certificates first DNSName with a user.Info (creating if needed).
- write a multi-authenticator module that takes a request and first tries Token auth, and then client-cert auth, and returns the user.Info from the first successful authentication. 

@smarterclayton @liggitt  feedback wanted too.

**Comment by liggitt** [comment]
API server and kubelet both accept client cert authn now, validated by a CA bundle specified for that purpose
