### ISSUE TITLE
rkt: kubelet performance test fails to run on rktnetes

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#25928]
```
node "yifan-rkt-minion-6uvd" runtime operation error rate:


node "yifan-rkt-minion-h379" runtime operation error rate:


node "yifan-rkt-minion-tsc1" runtime operation error rate:



• Failure [1332.537 seconds]
[k8s.io] Kubelet-perf [Serial] [Slow]
/home/yifan/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:508
  [k8s.io] regular resource usage tracking
  /home/yifan/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:508
    resource tracking for 35 pods per node [It]
    /home/yifan/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:258

    Expected error:
        <errors.aggregate | len:4, cap:4>: [
            {
                s: "Resource usage on node \"yifan-rkt-master\" is not ready yet",
            },
            {
                s: "Resource usage on node \"yifan-rkt-minion-6uvd\" is not ready yet",
            },
            {
                s: "Resource usage on node \"yifan-rkt-minion-h379\" is not ready yet",
            },
            {
                s: "Resource usage on node \"yifan-rkt-minion-tsc1\" is not ready yet",
            },
        ]
        [Resource usage on node "yifan-rkt-master" is not ready yet, Resource usage on node "yifan-rkt-minion-6uvd" is not ready yet, Resource usage on node "yifan-rkt-minion-h379" is not ready yet, Resource usage on node "yifan-rkt-minion-tsc1" is not ready yet]
    not to have occurred

    /home/yifan/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:101
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Summarizing 1 Failure:

[Fail] [k8s.io] Kubelet-perf [Serial] [Slow] [k8s.io] regular resource usage tracking [It] resource tracking for 35 pods per node 
/home/yifan/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:101

Ran 1 of 284 Specs in 1332.576 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 283 Skipped --- FAIL: TestE2E (1332.80s)
FAIL
```

Full logs [here](https://gist.github.com/yifan-gu/f6ab6d76a21cc5c1fbb0990e47353c6c)

cc @kubernetes/sig-node

**Comment by yujuhong** [comment]
@yifan-gu the test expects to see the "runtime" stats from kubelet's summary api. For rkt, this doesn't work. Will need to modify the test to only check the "runtime" resource usage if the runtime is docker. The kubelet resource usage should be fine.

**Comment by dchen1107** [comment]
Is this a regression? Or we just started to run this test against rkt? 

For rkt case, there is no daemon, that missing-runtime-issue are not fit for rkt.

**Comment by yujuhong** [comment]
It's not a regression. rkt has never passed this test. We'll need to make the test pick what to check based on the container runtime.

**Comment by sjpotter** [comment]
Pretty sure we discussed this before.   I think i hacked the test to ignore the daemon cgroups it expects to see to get it to run

**Comment by yujuhong** [comment]
@sjpotter, yes we discussed this before and I even had a half-baked local branch to disable daemon check for non-docker runtimes, but that needs a lot of fixes (or just a complete rewrite) after switching to the new summary api. 

@sjpotter, if you want to submit a PR, I'd be happy to review. Otherwise, I'll try to pick this up sometime next week.

**Comment by yifan-gu** [comment]
@yujuhong Where can I disable the docker runtime in the code just for now? Comment out the ones in the TargetContainers() ?

**Comment by yujuhong** [comment]
Yes, TargetContainers should not include "runtime" for rkt.

To actually fix this, TargetContainers should be pass to the resource collector, instead of being hard-coded. The test should checks the name of the runtime to decide what the target containers are.
For example, see https://github.com/kubernetes/kubernetes/commit/9af7953e3a2735cf86dc97051684cedebe866a1b to get the idea. This commit needs significant rebase and doesn't work anymore.

**Comment by yifan-gu** [comment]
Going to move to v1.1 as this is a non-blocker.

**Comment by yujuhong** [comment]
Closing this since relevant issues should be handled in CRI or moved to the rktlet repository.
