### ISSUE TITLE
integration test flake: kubectl edit can update the image field of a pod (hack/test-cmd.sh)

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#25925]
```
...
FAIL!
Get pods {{range.items}}{{(index .spec.containers 0).image}}:{{end}}
  Expected: gcr.io/google_containers/serve_hostname:
  Got:      nginx:
(B
714 ./hack/test-cmd.sh
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25894/kubernetes-pull-test-unit-integration/26773/

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by janetkuo** [comment]
`Edit cancelled, no valid changes were saved.`

Somehow the `edit` command didn't edit the resource.

**Comment by brendandburns** [comment]
I actually think this was caused by something in my PR.  closing this issue.
