### ISSUE TITLE
Possibility of using gluster volume in k8s if glusterfs client package on container

### ISSUE THREAD

**Issue by peijunfu** [kubernetes/kubernetes#25939]
Kubernetes supports several types of Volumes including GlusterFS. Also GlusterFS can be Persistent Volumes in k8s.
https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/glusterfs/

For using glusterfs volumes in k8s, one of prerequisites is "Install Glusterfs client package on the Kubernetes nodes". But if it is expect that everything shall be in containers. Is that possible that put gluster client in container (e.g. DaemonSet deploy gluster client on k8s node first), while k8s still can suing glusterfs as above example?

Will k8s support such using scenarios?  

Thank you.

**Comment by peijunfu** [comment]
Any one can help on this topic? Thank you.

**Comment by xiangpengzhao** [comment]
/kind support

Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user documentation](http://kubernetes.io/docs/)
  * [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/)

We're going to close this issue. Thanks!

/cc @thockin

**Comment by humblec** [comment]
@peijunfu Its well possible to put gluster client in containers. however in kube, the glusterfs plugin mount the gluster share in kubelet ( kubernetes node) where pod is running and then bind mount to the container. Can you please explain what exactly you want to achieve?
