### ISSUE TITLE
pre-commit hook is broken for godeps changes

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#25931]
if you make a godep change and run the pre-commit hook, it tries to run verify-godeps.  Two things go wrong.

1) git sets the GIT_DIR variable, which apparently makes godep puke in its own lap.

2) godep finds "dirty  working tree" for every file in the tmp GOPATH

investigating in background.

**Comment by thockin** [comment]
@mhrgoog

**Comment by xiangpengzhao** [comment]
Since pre-commit is removed in #47673, we can close these pre-commit related stale issues.
/cc @thockin

**Comment by cblecker** [comment]
Closing as fixed.
/close
