### ISSUE TITLE
Integration test error

### ISSUE THREAD

**Issue by ping035627** [kubernetes/kubernetes#25936]
From #25863

E0519 10:00:18.757632   15966 event.go:207] Unable to write event: 'dial tcp 127.0.0.1:50322: getsockopt: connection refused' (may retry after sleeping)
E0519 10:00:20.345152   15966 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
E0519 10:00:20.744882   15966 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
E0519 10:00:21.144832   15966 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
E0519 10:00:21.544645   15966 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
FAIL	k8s.io/kubernetes/test/integration	412.596s
+++ [0519 10:00:28] Saved JUnit XML test report to /workspace/artifacts/junit_v1,autoscaling-v1,batch-v1,apps-v1alpha1,policy-v1alpha1,extensions-v1beta1_20160519-095319.xml
!!! Error in /go/src/k8s.io/kubernetes/hack/test-go.sh:241
  'return ${rc}' exited with status 1
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/test-go.sh:241 main(...)
Exiting with status 1
!!! Error in ./hack/test-integration.sh:53
  'KUBE_GOFLAGS="-tags 'integration no-docker' " KUBE_RACE="" KUBE_TIMEOUT="${KUBE_TIMEOUT}" KUBE_TEST_API_VERSIONS="$1" "${KUBE_ROOT}/hack/test-go.sh" test/integration' exited with status 1
Call stack:
  1: ./hack/test-integration.sh:53 runTests(...)
  2: ./hack/test-integration.sh:85 main(...)
Exiting with status 1
+++ [0519 10:00:28] Integration test cleanup complete
Build step 'Execute shell' marked build as failure
Recording test results
[PostBuildScript] - Execution post build scripts.
[kubernetes-pull-test-unit-integration@2] $ /bin/bash -xe /tmp/hudson6877560626007845289.sh
+ [[ -x ./hack/jenkins/upload-to-gcs.sh ]]
+ ./hack/jenkins/upload-to-gcs.sh
Called without JENKINS_BUILD_STARTED or JENKINS_BUILD_FINISHED set.
Assuming a legacy invocation.
Run finished at Thu May 19 10:00:30 PDT 2016
Uploading to gs://kubernetes-jenkins/pr-logs/pull/25863/kubernetes-pull-test-unit-integration/26703 (attempt 1)
Uploading build result: [UNSET]
Uploading artifacts
Marking build 26703 as the latest completed build

*** View logs and artifacts at https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25863/kubernetes-pull-test-unit-integration/26703 ***

**Comment by fejta** [comment]
Please reopen if you see again
