### ISSUE TITLE
Unit test flake: TestReflectorResync exactly 2 iterations were expected, got: 3

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#25953]
```
-- FAIL: TestReflectorResync (0.01s)
	reflector_test.go:380: exactly 2 iterations were expected, got: 3
```
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25904/kubernetes-pull-test-unit-integration/26834/

**Comment by mml** [comment]
I saw this as well.

Log: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25895/kubernetes-pull-test-unit-integration/26824/
Brief discussion in #25895

**Comment by ncdc** [comment]
I think I have a fix for this

**Comment by ncdc** [comment]
Just submitted a PR that I believe fixes this. I was able to get the flakes locally w/o my PR and haven't seen any with it. PTAL!

**Comment by mml** [comment]
@ncdc how did you repro locally?  I tried ran this test 1,000 times last night and it passed 1,000 times.

**Comment by ncdc** [comment]
Change the resync period from 1 milli to 1 microsecond. You can also add
'stress -c 8' to the mix.

**Comment by wojtek-t** [comment]
@rrati - FYI

**Comment by piosz** [comment]
@xiang90 sent #26013 which should fix this
