### ISSUE TITLE
Disable kube-system services

### ISSUE THREAD

**Issue by NiclasHedam** [kubernetes/kubernetes#25958]
Hello,

I would like to disable kube-system DNS and kube-system dashboard, since they are unused in my cluster. When I delete the pods and rc, it just gets recreated again. How to disable these correctly?

**Comment by dims** [comment]
@NiclasHedam can you try deleteing the kube-system namespace? `kubectl delete namespace kube-system`

**Comment by NiclasHedam** [comment]
There is some kube-system addons and pods I would like to keep, therefore deleting the whole namespace is not an option.

I'm only interested in deleting the dashboard and dns.

**Comment by luxas** [comment]
@dims The `kube-system` namespace should never be deleted, and in newer releases (`v1.3.0-alpha.4+`) a such request is rejected.

@NiclasHedam It depends on which deployment solution you have how easy it is. It's the `kube-addon-manager` that's recreating the objects. Maybe just remove the files you don't want in `/etc/kubernetes/addons` on the master

Assigning @mikedanese to advise

**Comment by NiclasHedam** [comment]
I don't think I have access to the Kubernetes master on GKE. Correct me if I'm wrong.

**Comment by thockin** [comment]
Disabling kube-dns will cause some components to fail to operate.  It is,
for all intents, required.  What are you hoping to achieve?

**Comment by NiclasHedam** [comment]
Which? As far as I can read, the kube-dns service is only a nameserver. Which internal components will fail?

I'm hoping to free CPU and memory. There is no need to have unused pods, when their space can be used by replicas.

**Comment by thockin** [comment]
DNS lookups are done by a great number of examples and docs.  Without
kube-DNS, things like `https://kubernetes.default/` will not work.  DNS is
required and it's relatively low overhead.  Disabling it is not "supported"
- proceed at your own risk.
