### ISSUE TITLE
Make integration test failures easier to identify and debug

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#25965]
Currently the output from the integration tests is rarely useful for pinpointing the cause of an integration test failure.  We should make `test-integration.sh` easier to debug; if possible, there should be a foolproof way to diagnose the specific test case down to file/line number that failed.

I know @thockin was recently thinking about this too.  cc @ixdy @kubernetes/sig-testing

**Comment by yujuhong** [comment]
Related issue for deprecating tests in cmd/integration/integration.go #24440

**Comment by brendandburns** [comment]
I'm marking this P0 as part of the general "we need to make testing/flake fixing suck less" effort we're putting together.

**Comment by fejta** [comment]
@janetkuo any suggestions about what we could do here? This would really make investigating things like https://github.com/kubernetes/kubernetes/issues/25539 faster.

**Comment by pmorie** [comment]
I made a PR to holp with this -- #26032, which has been merged.

**Comment by fejta** [comment]
Awesome!
