### ISSUE TITLE
Kubelet e2e tests are not compatible with merge queue logic

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#25966]
Kubelet e2e tests are run manually using go command. As a result jenkins treats test failures as "red" ones not "yellow". AFAIU this means that we will block with the first flake, not two in the row as for other suites.

@kubernetes/sig-node @lavalamp @wojtek-t

**Comment by pwittrock** [comment]
I have been working on this, and hope to get a PR out today.  Will update when sent.

**Comment by pwittrock** [comment]
Working on this in #26101

**Comment by pwittrock** [comment]
@fgrzadkowski Where do I need to put the junit01.xml files?  Since the test suite is run on different hosts, there are several junit01.xml files I need to copy over from the remote hosts.

**Comment by pwittrock** [comment]
It looks like I just dump them in the artifacts directory with a count suffix.

**Comment by lavalamp** [comment]
Yup, just dump them all there and make sure the numbers are continuous.

**Comment by pwittrock** [comment]
@fgrzadkowski I may have miss understood what is required here.  Can you tell me how the tests should be run (not manually as a go command?)  I have another PR to export the junit.xml files.  Is this what the merge queue expects?

**Comment by pwittrock** [comment]
The node e2e tests now emit junit.xml test artifacts.  Let me know if this fixed the issue or there is something else I need to do.

**Comment by pwittrock** [comment]
@spxtr @ixdy Do you know if there is any work remaining to be done here?

**Comment by ixdy** [comment]
If only tests fail, the node e2e test runner should exit with status 0. It should only return a nonzero exit status on build, setup, teardown or other infra failures.

**Comment by pwittrock** [comment]
Good to know.

**Comment by pwittrock** [comment]
@vishh I think i know what needs to be done here

**Comment by fgrzadkowski** [comment]
@pwittrock To be honest I don't how this should be done. I've just noticed it doesn't work well with Jenkins :)

**Comment by pwittrock** [comment]
No worries, I have this PR out to fix: #26461

**Comment by pwittrock** [comment]
Fixed in #26461
