### ISSUE TITLE
support adding a transparent local proxy/load balancer as a sidecar (without having to change the original docker container to be aware of it)?

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/kubernetes#25961]
So the [DNS service discovery](http://kubernetes.io/docs/user-guide/services/#dns) in kubernetes is awesome. It encourages simplicity on the container image developer to just use simple service names to discover and communicate with services which then works in whatever namespace your pod is running.

The consumer of a docker image thats using DNS service discovery may decide they wish to use a side car container to do service discovery/load balancing/retry/circuit breakers/monitoring though. e.g. via something like https://traefik.io/ or some other reverse proxy to get different load balancing algorithms or behaviour. To enable a proxy we need to move away from the DNS discovery, so rather than calling `http://foo/` we'd need to call `http://localhost:1234` to talk to the proxy. This results in needing to change the docker image code to swizzle the URL. 

It would be really cool if we could do this swizzling via DNS, `/etc/hosts` or `/etc/resolv.conf` in some way purely in the kubernetes manifest. i.e. without changing the docker image at all we could configure the pod to talk not to the `foo` service IP address but instead talk to some 127.0.1.2 IP address which the sidecar listens on.  So some kind of annotations or whatever in the pod resource would instruct the kubelet to setup the right /etc/hosts or DNS resolver.

This would mean that the `foo` name resolves differently in the pod with this configuration or other pods; but it would provide a slick developer experience; letting developers reuse off the shelf docker containers that are easy to compose; the choice of using a side car load balancer/reverse proxy is down to the manifest author.

One alternative is to move away from DNS discovery and only ever use [environment variable discovery](http://kubernetes.io/docs/user-guide/services/#environment-variables); a colleague tells me DNS is the solution to all problems so that would make him sad ;)

Anyone got any other ideas or approaches to make the use of sidecar load balancers a little easier (so its purely configured in the manifest and doesn't bleed into the docker images)?

**Comment by snejati86** [comment]
@jstrachan 

> It would be really cool if we could do this swizzling via DNS, /etc/hosts or /etc/resolv.conf in some way purely in the kubernetes manifest. i.e. without changing the docker image at all we could configure the pod to talk not to the foo service IP address but instead talk to some 127.0.1.2 IP address which the sidecar listens on. So some kind of annotations or whatever in the pod resource would instruct the kubelet to setup the right /etc/hosts or DNS resolver.

In a way, by doing this you are changing the configuration of a container at runtime, how would this be different than getting the URL from the environment variables ? Any do you know why your colleague is against env variables ?

**Comment by jstrachan** [comment]
@snejati86 I think its more he's pro DNS :). 

But yeah I guess any iptables, `/etc/hosts`, `/etc/resolv.conf` stuff need to be done on startup first before any of the containers start; so via a lifecycle hook or something to be sure that when all the containers in the pod start; the new DNS mapping / iptable rule is in force

**Comment by jimmidyson** [comment]
> DNS is the solution to all problems so that would make him sad

Lots of things do make me sad, this is not one of them. I do _prefer_ DNS but I realise it is not a panacea.

I'm not against env vars at all, but it does mean you need to specify what they all are at startup. I'm playing with iptables DNAT to redirect all outbound traffic in a pod to a proxy running in the pod. That allows us to then not make any changes, add any env vars, etc to the app - a transparent proxy for all outbound requests that we can then use buoyant/traefik/whatever to forward on to destination & enable tracing, etc for relatively free.

**Comment by jimmidyson** [comment]
Playing with iptables in the pod net namespace started off promisingly... but then there are all sorts of problems with kernel modules not available in containers so using different stuff like running proxy sidecar as different uid & redirecting all traffic from non-proxy uid to proxy, allowing all traffic out from proxy uid didn't work to get a nice transparent proxy. Still feels like there should be a way to get this to work but my iptables fu fails me. @thockin Wonder if you have any ideas if there's a way to make it work/?

Would be awesome to make a portable sidecar container that can act as a transparent proxy though. Guess this might be a better issue name if @jstrachan feels like updating?

**Comment by jstrachan** [comment]
@jimmidyson I just gave it my best shot :)

**Comment by jstrachan** [comment]
BTW this looks a really great implementation of the sidecar
https://lyft.github.io/envoy/

it lets you do automatic retries of HTTP requests, circuit breakers, timeouts and so forth.

The big challenge is how to be able to configure DNS or `/etc/hosts` on a per pod basis so that we can point services to the sidecar so we can easily enable/disable sidecar based client side proxying without having to change the upstream docker images to switch from a nice DNS name for a service `foo` to some localhost ip address instead

**Comment by rhuss** [comment]
One question which comes to mind is, if you change the ip lookup of a service globally in a pod, how can a LB sidecar container then can find the *real* service ? hmm, probably by doing an DNS lookup explicitly . But what is if the original app does a DNS lookup itself e.g. for finding out the port from the SRV record ?

**Comment by rhuss** [comment]
Could the usage of the `HOSTALIASES` environment variable a solution ? See e.g. this [SO](http://unix.stackexchange.com/a/56288)

**Comment by jstrachan** [comment]
@rhuss yeah the client side load balancer would be using DNS SRV records or watching the Endpoints in kubernetes (i.e. talking directly to the pods rather than the service DNS name).

But yeah, I guess it'd be nice to configure the DNS names for services per container (rather than globally for all containers in the pod). e.g. container1 might want client side load balancing for services A and B, container2 might want client side load balancing for B and C and container3 might not want client side load balancing. 

Also for different container's client side load balancing rules (e.g. timeouts, circuit breakers,  retry counts and whatnot) we may want to point different containers in a pod to different local host ports in the load balancer to get different client side load balancing policies. (container1 might need different retries or timeouts to container2 for service B)

**Comment by jstrachan** [comment]
@rhuss I didn't know about `HOSTALIASES` - thats worth a try!

**Comment by therc** [comment]
Does the sidecar need to run in the same pod or could it be node-wide? I am trying to get node-local services implemented in 1.5 and this would be one of the use cases. You would lose some flexibility, namely multiple configurations. You could perhaps have a service exposed twice: first, as an ordinary service with a ClusterIP and random backend selection; the second service would then be a node-local instance of the load balancer, which is scheduled as a Daemonset and then does round-robin, load-balanced forwarding of traffic. This is only feasible if your service gets enough traffic to justify running a load balancer on every machine or if you find a way to share a single load balancer across multiple services.

**Comment by jstrachan** [comment]
@therc being in the pod would be a great option; then you could have per pod policies for retries, timeouts, circuit breaking for different services. different pods will want to have different retry/timeout configurations for different services.

Incidentally linkerd looks a really nice sidecar too https://linkerd.io/

**Comment by jimmidyson** [comment]
`HOSTALIASES` env var is a no-go - from http://serverfault.com/questions/65199/is-it-possible-to-alias-a-hostname-in-linux#comment1019328_490188:

> HOSTALIASES only works for applications using getaddrinfo(3) or gethostbyname(3) - This mean that it will work for applications trying to explictly resolve the hostname by a specific system call: It is never the case. see http://unix.stackexchange.com/questions/10438/can-i-create-a-user-specific-hosts-file-to-complement-etc-hosts so the only solution is local dns (dnsmasq)

**Comment by sandys** [comment]
@jstrachan i came across this bug because we have been thinking about this for a while. related bug is https://github.com/kubernetes/kubernetes/issues/28610

One of the questions I have been discussing with others on slack is whether this is best done at the Service abstration. Meaning instead of a fixed iptables + kubeproxy based Service abstraction... why not let the Service be pluggable. 

This way I can plug in envoy, linkerd, etc (as long as they provide the endpoints that a Service object should). 

My viewpoint is that load balancers .. and even Ingresses ... are pluggable. Why not Services (which are basically a load balancer on a group of pods)

**Comment by thockin** [comment]
Services *are* pluggable, but Services are, by definition, L4 for now.
What I am hearing most people (in this context) ask for is L7.  Mostly, but
not exclusively, HTTP.

There's some debate about whether such a sidecar should trap *all* traffic
or only traffic to services that the user has declared.

There's some debate about how magical and transparent such a proxy NEEDS to
be.

There's some debate about noisy-neighbor and complex resource management
with a per-node proxy, but per-pod without iptables can only be so
magical.  With iptables requires privileged containers.

I am committed to helping find solutions, but as of now I have more
questions than answers.  Enrico has a doc that captures a lot of this - see
sig-network mailing list.

On Mon, Dec 26, 2016 at 3:42 AM, Sandeep Srinivasa <notifications@github.com

**Comment by timoreimann** [comment]
For those looking for the link to the doc Tim mentioned, I think it's here: https://groups.google.com/d/topic/kubernetes-sig-network/weni52UMrI8/discussion

**Comment by sandys** [comment]
@timoreimann thanks for this.. i was really getting frustrated with looking for it. 

@timoreimann @thockin slightly OT, but i would really like to request SIG discussion to move away from google docs and into pull requests. this is such a great way to create and discuss a proposal. you could make this as a kubernetes/proposals git repo in itself.
https://github.com/kubernetes/kubernetes/pull/34013

Doc files are really really bad for discoverability - same thing happened to us with the kuberentes upgrades proposal document.

**Comment by thockin** [comment]
Sorry for the lack of link - I was on mobile :)

**Comment by timoreimann** [comment]
@sandys re: proposal discussions: It probably makes sense to take this to one of the general mailing lists if you think it's worth changing. Personally, I can see how using Github PRs makes more sense on the surface. Not sure though how often people use features in Google Docs that are hard to do in markdown (like graphs or diagrams).

**Comment by sandys** [comment]
@timoreimann i feel very strongly about this - having been bitten by this more than once in kubernetes-sig. which mailing list would you recommend ?

**Comment by timoreimann** [comment]
@sandys I believe the contribex-sig mailing list would be a good fit as that sig apparently already has some of the points you mentioned on their roadmap: https://github.com/kubernetes/community/wiki/Roadmap:-Contributor-Experience

**Comment by bgrant0607** [comment]
cc @louiscryan
