### ISSUE TITLE
Switch master node on GCE to GCI image by default 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#25977]
We recently switched GKE's master node to GCI image, but not GCE master node. This discrepancy causes a lot of issues for us, especially some prs merged might work on GCE, but totally break GKE. We should get rid of that difference. 

cc/ @roberthbailey @kubernetes/goog-gke @kubernetes/goog-node @kubernetes/goog-image

**Comment by andyzheng0831** [comment]
The master image for test is defined here: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L39. We want to switch all test jobs? Or just one particular job, e.g., k8s ci testing k8s master head? I am afraid that simply replacing the image in that script will affect all test jobs

**Comment by lavalamp** [comment]
I think this is a bad plan unless we continue to test container VM start up somehow. We can't break that while people still use it!

**Comment by andyzheng0831** [comment]
An alternative: Set up another jenkins job dedicated for the purpose and mark it as commit queue blocker.

**Comment by fabioy** [comment]
It may be better to just switch GKE masters back to containerVM for now, then redo the sequence (i.e. switch GCE to GCI, then GKE master to GCI).

**Comment by roberthbailey** [comment]
@lavalamp if we switch both the test and non-test default from cvm -> gci then starting with the 1.3 release people won't be using it (by default), so testing becomes less important.

**Comment by wonderfly** [comment]
> It may be better to just switch GKE masters back to containerVM for now, then redo the sequence (i.e. switch GCE to GCI, then GKE master to GCI).

I don't think we have to. The GKE CI job is already a CQ blocker, but it runs after submit so bad PRs still get merged (though they get identified quickly). What we need is a PR builder that runs tests with GCI, so we can block bad changes in the first place.

**Comment by wonderfly** [comment]
Definition about PR builers: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#the-pr-builder

cc/ @kubernetes/test-infra-admins

**Comment by lavalamp** [comment]
> What we need is a PR builder that runs tests with GCI, so we can block bad changes in the first place.

Yes. It could be even simpler, it just has to start up a cluster and tear it down. Just run like 1 fast test. @ixdy @fejta

**Comment by lavalamp** [comment]
We've got to do something though, the queue has been blocked for like 3 hours on GKE tests not passing.

**Comment by wonderfly** [comment]
>Yes. It could be even simpler, it just has to start up a cluster and tear it down. Just run like 1 fast test. @ixdy @fejta

I'd still like to run the e2e tests as some tests make assumptions of the OS distro and thus fail on GCI.

@ixdy @spxtr Can we duplicate [this job] (http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/) (that runs gce-e2e on every PR), replacing ContainerVM with GCI as the master and (or) node image?

**Comment by spxtr** [comment]
> @ixdy @spxtr Can we duplicate this job (that runs gce-e2e on every PR), replacing ContainerVM with GCI as the master and (or) node image?

It's a bit of a pain to do this, since that job also does a full build and it feels like a major waste to build each PR again. The Jenkins agents probably can't handle that much load, anyway.

**Comment by ixdy** [comment]
at some point we probably need to bite the bullet and set up pipelines so we only build kubernetes once, rather than separately in the unit/integration, e2e, and node e2e jobs.

I have no idea how well any of that interacts with the pull request plugin, of course.

**Comment by wonderfly** [comment]
Thanks for the information @spxtr . So looks like the first alternative, _running tests with GCI/GKE and block bad changes in the first place_, is hard to get done due to some infrastructure challenges (as mentioned in https://github.com/kubernetes/kubernetes/issues/25977#issuecomment-220709516). It's not impossible though, just not prioritized right now.

The second alternative would be, keep running the post-submit tests (the GKE e2e tests), and fix issues as they appear, which is not too bad imo since they run every 30 min and block submit queue on failure. At the end of the day, you cannot prevent 100% of breakages in presubmit tests, and that's why we _have to_ have postsubmit tests to complement.

**Comment by dchen1107** [comment]
I think start another jenkins job as one more pr builder, which have the master node on GCI image and rest of nodes on ContainerVM is the simplest thing unblock us. 

After 1.3, I suggested we do https://github.com/kubernetes/kubernetes/issues/25276

**Comment by lavalamp** [comment]
> which is not too bad imo since they run every 30 min and block submit queue on failure

No, this is not acceptable! we've been blocked for 10 out of the last 24 hours due to this! :)

**Comment by roberthbailey** [comment]
I agree that we need to catch this before merging instead of after merging. The question is how best to do so.

**Comment by spxtr** [comment]
> which is not too bad imo since they run every 30 min and block submit queue on failure

The problem is that the submit-queue puts them in at odd hours, and we don't expect OSS oncall to be watching at 2 AM.

**Comment by wonderfly** [comment]
> No, this is not acceptable! we've been blocked for 10 out of the last 24 hours due to this! :)

Well, the flip side is you don't have to run all tests (on all providers) so that all your PRs get merged faster. I am not saying I prefer postsubmit tests, it just something you have to face, no matter its gke tests or gce tests.

> I agree that we need to catch this before merging instead of after merging. The question is how best to do so.

I would prefer that too.

**Comment by spxtr** [comment]
> Well, the flip side is you don't have to run all tests (on all providers) so that all your PRs get merged faster. I am not saying I prefer postsubmit tests, it just something you have to face, no matter its gke tests or gce tests.

I think the solution to this is to run more tests when the PR is created, but then when the submit queue asks for a retest before merging only run a smoke test. I think that's a good tradeoff.

**Comment by wonderfly** [comment]
> I think the solution to this is to run more tests when the PR is created, but then when the submit queue asks for a retest before merging only run a smoke test. I think that's a good tradeoff.

That's a good topic to talk and I have some ideas about that too, but I'd stop dragging the focus too far. :smile:

**Comment by alex-mohr** [comment]
I don't see any compelling reasons to have a different master image-type for GCE and GKE -- there are strong benefits to them being identical, as we've observed.  We want 1.3+ to run GCI for GKE, therefore I propose we switch both GCE and GKE to use GCI for the master on all 1.3+ tests by default, including PR and post-submit.

If there is a testing gap in that situation, because we think it's important to support containerVM for 1.3+ masters on GCE (but not GKE), then add coverage for that gap.  I don't have enough context to know whether that's pre-submit or post-submit or both.

**Comment by alex-mohr** [comment]
(To append: I think post-submit coverage is horrible and would support a P0 of any test tiger team and/or code-yellow exit criteria being that we have pre-submit coverage of all the various test matrix points.  I realize that'll be expensive in both time and machine resources, but it'll be less expensive than our current approach and I suspect generate significant velocity benefits.)

**Comment by lavalamp** [comment]
> I think the solution to this is to run more tests when the PR is created, but then when the submit queue asks for a retest before merging only run a smoke test. I think that's a good tradeoff.

This is a decent idea.

**Comment by dchen1107** [comment]
@andyzheng0831 is out for vacation, @wonderfly could you please pick up this one? I think we agreed to have a separate jenkins job as one more pr builder, which have the master node on GCI image and rest of nodes on ContainerVM. The newly created job should only run the basic test suites.

If you need some help, please ask @lavalamp

**Comment by roberthbailey** [comment]
After talking with @lavalamp and @dchen1107 we came to the following agreement:

1. We will switch the default base image for master nodes running on GCE from debian container-vm to GCI.
1. We will add a jenkins job that runs periodically (post-submit) that will continue to test master nodes running the debian container-vm, initially running against the master branch.
1. We will pin this job to the 1.3 release branch once it is cut, and no longer run it against the master branch.
1. We will delete the new jenkins job once we have full confidence that we will not roll back the master image from GCI to the debian container-vm, sometime between now and the 1.4 release.

**Comment by wonderfly** [comment]
A am going to work on a PR for no. 1.

cc/ @kubernetes/goog-image

**Comment by roberthbailey** [comment]
no. 2 is being added in https://github.com/kubernetes/test-infra/pull/70

**Comment by mikedanese** [comment]
It happened again: https://github.com/kubernetes/kubernetes/pull/26190
