### ISSUE TITLE
Are we going to update to protobuf 3.0.0-beta-3 before v1.3?

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#25976]
The title says it all.
@smarterclayton @wojtek-t

**Comment by smarterclayton** [comment]
I had no plans to, and reason we need to?

**Comment by smarterclayton** [comment]
Ref #8134

On May 20, 2016, at 1:15 PM, Lucas Käldström <notifications@github.com>
wrote:

The title says it all.
@smarterclayton <https://github.com/smarterclayton> @wojtek-t
<https://github.com/wojtek-t>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/25976>

**Comment by luxas** [comment]
I had no specific reason, just asked
I just thought it might be of interest. It was released some days ago.
> 
    Improved hash maps.
        Improved hash maps comments. In particular, please note that equal hash maps will not necessarily have the same iteration order and serialization.
        Added a new hash maps implementation that will become the default in a later release.
    Arenas
        Several inlined methods in Arena were moved to out-of-line to improve build performance and code size.
        Added SpaceAllocatedAndUsed() to report both space used and allocated
        Added convenient class UnsafeArenaAllocatedRepeatedPtrFieldBackInserter
    Any
        Allow custom type URL prefixes in Any packing.
        TextFormat now expand the Any type rather than printing bytes.
    Performance optimizations and various bug fixes.

Performance optimizations and bug fixes are always a good thing (unless it was packaged with new bugs instead :smile:)
I don't know, but would it solve protobuf-related issues like #25835 in some way?

**Comment by smarterclayton** [comment]
It would not, all the optimizations are for C / Java etc, not Golang.

**Comment by luxas** [comment]
Okay, got it.
Closing for now (as it should not be in this release)

We might reopen it in the future if there's need for it
