### ISSUE TITLE
Test containers should be regularly recompiled and updated. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#25970]
In digging into a couple of issues it was clear the containers had not been recompiled against golang 1.6. 

https://github.com/kubernetes/kubernetes/pull/25280#issuecomment-220633165

/cc @kubernetes/sig-testing @ixdy

**Comment by ixdy** [comment]
Wonder if there's a good way to automate this. It seems to require:
* bumping up tags for every test image (which don't really follow consistent patterns, IIRC)
* building all images and pushing them to gcr.io
* updating all tests to use the new tag

All the while hoping that any other new changes brought in don't break the tests in some way.

**Comment by timothysc** [comment]
I think it could be done, and would be highly useful.  
/cc @jayunit100

**Comment by timothysc** [comment]
Closing, Fixed.
