### ISSUE TITLE
add metadata when using docker --log-driver=journald

### ISSUE THREAD

**Issue by richm** [kubernetes/kubernetes#25975]
When using OpenShift with the standard docker log driver, there are container logs in the following format::

    /var/log/containers/$name_of_pod-$name_of_project-$name_of_container-$containeruuid.log

The fluentd log collector uses $name_of_pod and $name_of_project to look up in k8s additional metadata for the pod and project (such as the uuids).

When using docker daemon `--log-driver=journald`, these files no longer exist, and the journal entries are missing $name_of_pod and $name_of_project in the metadata::

    __CURSOR=s=7c08f275b8a545a9afb1770ef779ebb8;i=3148;b=caa653694cfa4a6ea9e4213e6cf4065b;m=13700ce9;t=53347368f6904;x=770aebf7b30ab7b3
    __REALTIME_TIMESTAMP=1463755834616068
    ...
    _COMM=docker-current
    _EXE=/usr/bin/docker-current
    _CMDLINE=/usr/bin/docker-current daemon --authorization-plugin=rhel-push-plugin --selinux-enabled --log-driver=journald
    CONTAINER_ID=a160de6fe8fa
    CONTAINER_ID_FULL=a160de6fe8facb49103c45f2bd14854b455b42153b777634ea58fb8a95124a40
    CONTAINER_NAME=silly_bhaskara

When running containers via docker directly, you can use `-e` and `-l` to pass additional metadata through to the journal output::

    docker run -e FOOT=BALL -l LA=SF --rm --name toasted \
      --log-driver=journald --log-opt env=FOOT --log-opt labels=LA \
      fedora /bin/pwd

    MESSAGE=/
    CONTAINER_NAME=toasted
    LA=SF
    FOOT=BALL
    CONTAINER_ID=37772f57b118
    CONTAINER_ID_FULL=37772f57b1189306fed624675cd33412461a6f04ff0f4d7a4ea5d1d41f637641

Is there some way to make k8s and/or OpenShift add fields like `K8S_POD_NAME=$name_of_pod` and
`K8S_NAMESPACE_NAME=$name_of_project` to the journal entries?
This will also be needed by https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter which assumes the entries are tagged in a similar format to the filename above.  Of course if k8s/openshift can be configured to automatically add that additional metadata (such as pod uuid, namespace uuid, etc.) to the journal entries then the fluentd k8s metadata plugin might not be needed.

**Comment by ncdc** [comment]
@richm the examples above are from non-Kube containers (looking at the `CONTAINER_NAME`) values - am I correct?

Here's what I see for a container created from a pod locally:

`CONTAINER_NAME=k8s_bob.94e110c7_bob-iq0d4_default_2d67916a-1eac-11e6-94ba-001c42e13e5d_8b4b7e3d`

From this, we can extract:

- container name in pod: bob
- pod name: bob-iq0d4
- namespace: default
- pod uid: 2d67916a-1eac-11e6-94ba-001c42e13e5d

It may be nice to have these added as separate metadata fields per journald entry, but I think we can extract the info we need today.

**Comment by richm** [comment]
@ncdc That works.  Thanks!

**Comment by richm** [comment]
@ncdc in `bob.94e110c7` - the `94e110c7` is the container hash?  `"io.kubernetes.container.hash": "94e110c7"` What exactly is that?

The hex at the very end - the `8b4b7e3d` - what is that?

**Comment by ncdc** [comment]
@richm the container hash is the checksum of the container's definition. It's used to compare the running container with its desired spec.

The hex at the end is random. It's there to prevent collisions if you had two instances of the same container for the same pod/pod UID. See https://github.com/kubernetes/kubernetes/blob/7796b619fdfd4e492616346cd61913ff1173b248/pkg/kubelet/dockertools/docker.go#L247
