### ISSUE TITLE
Cleanup system configuration at node

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#26005]
Forked from https://github.com/kubernetes/kubernetes/pull/26001

To make debian-based node compatible with docker 1.11.X, I updated both /proc/sys/kernel/keys/root_maxkey and /proc/sys/kernel/keys/root_maxbytes. Also other kubernetes components do the similar thing. For example, kube_proxy: https://github.com/kubernetes/kubernetes/blob/dae5ac482861382e18b1e7b2943b1b7f333c6a2a/cmd/kube-proxy/app/conntrack.go#L42

We should clean up those configurations into one common place.

**Comment by dchen1107** [comment]
cc/ @vishh

**Comment by cmluciano** [comment]
Is this looking for an owner? It seems the ask is to generalize these types of settings in a module.

**Comment by vishh** [comment]
Yeah. We update quite a few kernel settings in kubelet itself. We should move the ones mentioned in this issue to kubelet if it is applicable to other distros too.

@cmluciano want to own this?

**Comment by cmluciano** [comment]
Sure, I'll start poking.

**Comment by cmluciano** [comment]
Test results so far for a few distributions' default settings

Operating System|Key|Value
--- | ---  | ---
Debian Jessie 8.7.5|/proc/sys/kernel/keys/root_maxkeys|200
--- |/proc/sys/kernel/keys/root_maxbytes|20000
--- |/sys/module/nf_conntrack/parameters/hashsize|undefined|
--- |/proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established|undefined|
Ubuntu 14.04|/proc/sys/kernel/keys/root_maxkeys|200
--- |/proc/sys/kernel/keys/root_maxbytes|20000
--- |/sys/module/nf_conntrack/parameters/hashsize|undefined|
--- |/proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established|undefined|
Ubuntu 16.04|/proc/sys/kernel/keys/root_maxkeys|1000000
--- |/proc/sys/kernel/keys/root_maxbytes|25000000
--- |/sys/module/nf_conntrack/parameters/hashsize|undefined|
--- |/proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established|undefined|
CentOS 7|/proc/sys/kernel/keys/root_maxkeys|1000000
--- |/proc/sys/kernel/keys/root_maxbytes|25000000
--- |/sys/module/nf_conntrack/parameters/hashsize|undefined|
--- |/proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established|undefined|
Fedora 25|/proc/sys/kernel/keys/root_maxkeys|1000000
--- |/proc/sys/kernel/keys/root_maxbytes|25000000
--- |/sys/module/nf_conntrack/parameters/hashsize|undefined|
--- |/proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established|undefined|
Redhat Atomic 25|/proc/sys/kernel/keys/root_maxkeys|1000000
--- |/proc/sys/kernel/keys/root_maxbytes|25000000
--- |/sys/module/nf_conntrack/parameters/hashsize|16384
--- |/proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established|432000
CoreOS stable|/proc/sys/kernel/keys/root_maxkeys|1000000
--- |/proc/sys/kernel/keys/root_maxbytes|25000000
--- |/sys/module/nf_conntrack/parameters/hashsize|undefined
--- |/proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established|undefined
