### ISSUE TITLE
Host search domains not considered in containers

### ISSUE THREAD

**Issue by Frusty** [kubernetes/kubernetes#26009]
Kubernetes 1.2.4
CoreOS beta channel (1010)

I am running a kubernetes cluster inside an AWS VPC with custom DNS servers. Those are configured in my host /etc/resolv.conf together with an additional search domain (example.com).

Kubernetes DNS Addon is configured to fall back to our DNS servers.

When in a kubernetes managed container, I can nslookup our externally managed systems by their full name (e.g. kafka.example.com) but not by their short name (kafka). On the host, the search domain is respected and `nslookup kafka` returns as expected.

If I edit the /etc/resolv.conf inside the container to add my search domain, subsequent lookups work as expected.

The DNS documentation states that Kubernetes should respect the hosts resolv.conf and only prepend the kubernetes internal search domains.

How can I add my search domain permanently?

**Comment by aronchick** [comment]
can you try the following:

`dig +search kafka`

**Comment by Frusty** [comment]
```
# dig +search kafka01

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> +search kafka01
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 20282
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kafka01.			IN	A

;; Query time: 0 msec
;; SERVER: 10.200.0.10#53(10.200.0.10)
;; WHEN: Sun May 22 04:28:46 UTC 2016
;; MSG SIZE  rcvd: 25
```

**Comment by thockin** [comment]
The host's resolv.conf entries should be populated into containers.  Are
you running kubelet with a --resolv-conf flag?  Does your pod have an
dnsPolicy of "Default" ?  What does /etc/resolv.conf look like in your
container?

**Comment by Frusty** [comment]
The kubelets do not use `--resolv-conf` flag.
`dnsPolicy` is not part of the kubernetes definition of the POD in question.

container resolv.conf
```
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.200.0.10
options ndots:5
```

**Comment by Frusty** [comment]
This was falsely closed with my last comment. Issue still persists.

**Comment by alexanderkiel** [comment]
I have the same problem. I run Kubernetes v1.3.0 and have two pods from one replicaset running on two identically configured workers. One pod has my custom search domain in it's resolv.conf and the other not.

```
worker-1 $ cat /etc/resolv.conf
nameserver ip-1
nameserver ip-2
search example.com
```

```
worker-1 $ sudo cat /var/lib/docker/containers/.../resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.3.0.10
options nods:5
```

```
worker-2 $ cat /etc/resolv.conf
nameserver ip-1
nameserver ip-2
search example.com
```

```
worker-2 $ sudo cat /var/lib/docker/containers/.../resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local example.com
nameserver 10.3.0.10
options nods:5
```

I run kubelet with `--cluster-dns=10.3.0.10` and `--cluster-domain=cluster.local` as direct process (no rkt or docker) on both workers.

**Comment by timbunce** [comment]
Possibly related: coreos/coreos-kubernetes#506

**Comment by thockin** [comment]
Are you looking at the resolv.conf for `pause` containers or real app
containers?  Pause will use the default docker form of resolv.conf.  Are
the apps using hostNetwork?

I can not repro this *at all*.  Help wanted to repro...
