### ISSUE TITLE
avoid putting heavy load on etcd by issuing unnecessary/large relist

### ISSUE THREAD

**Issue by xiang90** [kubernetes/kubernetes#26015]
We have a cache layer in front of etcd to reduce the load directly hit at etcd.

The cache layer works in two steps: first builds the initial state through listing the entire state, then watches on items and applies incremental changes to the initial state.

The first list can be very expensive when the initial is large. A list/re-list can suddenly put a lot of load onto etcd and blocks other normal operations.

We should:
1. avoid unnecessary relist
2. avoid large relist

<del> Today's reflector always tries to do relist no matter what the state the backing store is: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/reflector.go#L291. We should improve this by trying to catch up with the state of store by watch first. Reflector should only do a relist when etcd does not have the required history event. </del>

Second, as etcd3 supports consistent snapshot and pagination, we should limit the number of item to list and build the initial state in a controlled manner.

/cc @wojtek-t @timothysc @lavalamp @mqliang @hongchaodeng

**Comment by mqliang** [comment]
@xiang90 
I am curious about why a recursive GET request will put a lot of load onto etcd and blocks other normal operations, but WATCH will not. AFAIK, all requests are served sequentially. Is it because the [GET](https://github.com/coreos/etcd/blob/master/store/store.go#L119-L156) method in store package is much more time-consuming than [WATCH](https://github.com/coreos/etcd/blob/master/store/store.go#L441-L456) ?

IIUC, it would be an awesome optimization.

**Comment by xiang90** [comment]
> I am curious about why a recursive GET request will put a lot of load onto etcd 

List might need to process thousands or even tens of thousands requests a time. It can require extensive amount of CPU, Memory and network IO. When you do not have enough physical resources, it blocks other operations. 

Watch only process one item a time. List and Watch are different.

**Comment by xiang90** [comment]
> AFAIK, all requests are served sequentially. Is it because the GET method in store package is much more time-consuming than

Also by etcd, I mean both the server and client. If Kubernetes has 10 clients issues 10 list at the same time, Kubernetes API server itself will suffer from high network bandwidth usage, CPU usages and slow down other operations.

**Comment by wojtek-t** [comment]
@xiang90 - sorry I'm not really following this issue.

We explicitly set 0 resync period here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L164

so unless we don't go out of history window in etcd with the watch, we will never do a full relist on etcd. And to be honest, I've never seen that in our performance tests.

>
Second, as etcd3 supports consistent snapshot and pagination, we should limit the number of item to list and build the initial state in a controlled manner.

This one I agree, but we are not there yet.

**Comment by mqliang** [comment]
@wojtek-t I think @xiang90 means the [first list](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/reflector.go#L262) when reflector start. Since etcd v3 could keep all the history(unless explicit compaction), it's possible to replace the first list to watch if the [resource version](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/reflector.go#L261) we want list are still in the history window

**Comment by AdoHe** [comment]
@mqliang @xiang90 @wojtek-t , in the current implementation, the first list is mainly used to retrieve resource version, then we use correct resource version to do watch operation. If etcd v3 could keep all the history, the first list may be unnecessary. The question is every time reflector start, how to know the resource version, if we don't do list.

**Comment by wojtek-t** [comment]
@AdoHe @mqliang - no; it's not used just for resourceVersion; we NEED to know all elements and their state in the cache, because we are also serving lists from cache;
but even if we wouldn't we need it because we need to know the previous state of the object to correctly send a watch event (e.g. if there is some label selector, depending on the previous labels in the object, the new event may be all add, update and delete).

So we REALLY need a full "list" at the beginning in the "cacher"

**Comment by xiang90** [comment]
@AdoHe As @wojtek-t mentioned, the first list is needed anyway. I hope to avoid any large lists afterwards.

> We explicitly set 0 resync period here:

Oh. I was not aware of that 0 means give me the "fresh" items in the store. I was thinking 0 requires the fresh items, which should be in etcd thus forcing a relist. I double check the watchCache code, I think you are right. Sorry for the noise.

I do observe relist in my test. There might be an issue with the test I wrote. I will get back to you after I figure out what exactly happens in my test.

**Comment by timothysc** [comment]
imho that code is very confusing, both @rrati and myself were tripped up by the subtleties.  

post recent mods we do not see a relist, except on a watch fail of some kind.  

FWIW a net-split could force a thundering re-list, that condition still remains.

**Comment by xiang90** [comment]
> except on a watch fail of some kind.

Even a watch fail should not trigger re-list for normal case, since we still have state in the cache. It should catch up from the cached store.

> FWIW a net-split could force a thundering re-list, that condition still remains.

Yes. We need pacing all the relist in the future.

**Comment by AdoHe** [comment]
@xiang90 @wojtek-t yes, the first list is needed anyway.

**Comment by mqliang** [comment]
@xiang90 

> List might need to process thousands or even tens of thousands requests a time. It can require extensive amount of CPU, Memory and network IO. When you do not have enough physical resources, it blocks other operations.

Could [chunked encoding](https://www.httpwatch.com/httpgallery/chunked/)  help in such a case?  Maybe we could break large list response into several chunks.

**Comment by wojtek-t** [comment]
>
Even a watch fail should not trigger re-list for normal case, since we still have state in the cache. It should catch up from the cached store.

Assuming that we have enough history etcd, I agree. We should probably do it at some point.

**Comment by xiang90** [comment]
> We should probably do it at some point.

>  This one I agree, but we are not there yet.

Actually hongchao and I have some time now. So we can help on this now, just because we already have etcd3 support. 

One more thing is that etcd2 itself will actually stupidly disconnect watch. The client API we use today hides that reconnecting details, but yes it still does that underneath. So if k8s is under highload, relist might still be triggered by etcd itself. We will solve them all soon.

**Comment by timothysc** [comment]
A lot of work was put into 1.4/.5 that fixes this issue, closing.
