### ISSUE TITLE
Create process for testing and updating container images

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#26023]
We have two challenges:
1. Container images must be manually uploaded into gcr.io.  These images include containers like  gcr.io/google_samples/cassandra must be manually uploaded after each update.
2. Container images cannot be tested until they are uploaded.

This is causing issue with testing and also releasing containers that are broken.  We do not have a e2e test cycle that will support this.

Proposal:
1. Determine if we can use a docker registry that is installed as a rc
   - build the container via e2e test
   - push the container to the registry in the k8s cluster
   - deploy an example application from that registry
   - validate that the container is working (not via logs, actually use the app)
2. Once the above tests have passed
   - merge code
   - build and upload image automatically

**Comment by chrislovecnm** [comment]
cc @jayunit100 @kubernetes/examples

**Comment by jayunit100** [comment]
Hmmmm No dupe issues for this?  I thought we had one oriented around the Makefile that satnam created a while back.  ....

**Comment by chrislovecnm** [comment]
@jayunit100 find me the dupe 😄

**Comment by jayunit100** [comment]
https://github.com/kubernetes/kubernetes/issues/5465 I kinda think we should close that issue since this issue solves both without-loss-of-generatilty.

**Comment by pwittrock** [comment]
Why can't we test the container images by uploading them to gcr.io/your_name_here/cassandra?

**Comment by chrislovecnm** [comment]
@pwittrock how would developers that don't have GCE accounts run e2e tests?

**Comment by pwittrock** [comment]
I guess I am unclear on if the image is built and uploaded as part as running the example?  If we do want to built them, ignore my following comments.

I am trying to better understand:

> Container images cannot be tested until they are uploaded.

I don't think we want to be uploading untested container images if it can be avoided.  Does this approach solve the issue?

- Build and upload the image to your own repo
- Run the e2e tests using your image - **it should now be tested**
- Send a PR with the image build file
  - PR approver builds the image and uploads to gcr.io
- Update your tests to use the gcr.io image

**Comment by chrislovecnm** [comment]
> Build and upload the image to your own repo
> Run the e2e tests using your image - it should now be tested

The challenge that I have with that is that we are changing the test.  I would prefer to have the test run locally as it run during the PR process.

The test case is when containers for examples are updated.  For instance I just put in https://github.com/kubernetes/kubernetes/pull/26022 to modify the cassandra example.  e2e testing would need to build the new image, and run the testing.   For the PR I basically did what you are recommending and ran into two more problems, and I had to wait for someone to upload the image again.

Also the e2e tests should automatically be able to test the image w/o a PR.  For instance what happens when a base image is updated such as Debian, and suddenly the image does not work?  This is more automated in my mind.  

On of the other googler's mentioned that the image upload should happen automatically when the PR is merged, but I understand manual intervention as well.

**Comment by pwittrock** [comment]
> The challenge that I have with that is that we are changing the test. I would prefer to have the test run locally as it run during the PR process.

What is stopping you now from changing the [image in the yaml](https://github.com/chrislovecnm/kubernetes/blob/742b92a034fa505c982959f13aff368fcd016b20/examples/cassandra/cassandra-controller.yaml) to something you control and running the tests locally?

>  For the PR I basically did what you are recommending and ran into two more problems, and I had to wait for someone to upload the image again.

What problems did you run into?  Why were you not able to catch these when running the tests locally?

> Also the e2e tests should automatically be able to test the container w/o a PR. For instance what happens when a base container is updated such as Debian, and suddenly the container does not work? This is more automated in my mind.

Are you suggesting something different from what is done by the [jenkins-ci e2e tests](http://submit-queue.k8s.io/#/e2e)?

**Comment by chrislovecnm** [comment]
What are your concerns about the e2e tests building the images and testing them locally? What are your recommendations to improve this?

> What is stopping you now from changing the image in the yaml to something you control and running the tests locally?

With tests I don't want anything different.  But that is because I am really picky about them.  But then again maybe I am over complicating it. It makes more sense to me to have the e2e test to use a built container rather than pulling a staged container out of a repo, but this over complicated?

> What problems did you run into? Why were you not able to catch these when running the tests locally?

Permissions issues within the docker build.  Do not know why I did not catch them locally.  If we have the same test, then I am hallucinating that I may catch the errors.  If we have the e2e tests build the container locally we may have less human process, and remove errors.

What do you recommend?

> Are you suggesting something different from what is done by the jenkins-ci e2e tests?

Yes.  The containers are not built and pushed to a local repository.  We use the containers that are in the yaml.  We have to have someone push the container to gcr.io, and then test.  That is human process, and I like to eliminate human process when it comes to testing, but I am open to other options.  Also the container has to be uploaded to gcr.io before the e2e tests will fully function.

**Comment by pwittrock** [comment]
I think I understand now.  The problem you are trying to solve is to test that the image actually builds from the Dockerfile and passes validation.  This seems like a generally good thing to do.  My biggest concerns with this would be:

- Introducing more complexity / instability / flakiness to our already brittle e2e tests
- Time required to build / review this approach

**Comment by pwittrock** [comment]
Actually, it looks like we are already running a local registry that you can use.  :)

**Comment by pwittrock** [comment]
cc @lavalamp

**Comment by chrislovecnm** [comment]
@pwittrock in the e2e cluster?

**Comment by pwittrock** [comment]
Yes, but apparently it isn't being used and is poorly supported.  We are considering using our own image registry generally for testing to address some issues we have been seeing with test failures due to image pulls timing out.

See #26390 and #1319
