### ISSUE TITLE
Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [cpuset]

### ISSUE THREAD

**Issue by vanloswang** [kubernetes/kubernetes#26038]
On raspberry pi 3 running Fedora 23.

go version
go version go1.5.4 linux/arm

go env
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"738b7603b042dcda7a5ba419ab0e7f40a617080c", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"738b7603b042dcda7a5ba419ab0e7f40a617080c", GitTreeState:"clean"}

kubectl get node
NAME        STATUS     AGE
127.0.0.1   NotReady   10h
kubelet report such an error, and the node entering NotReady because kubelet return setupfailed here.  After deep into the source code, I found out that only cpu and memory are required. So the error info maybe change to a warning. The source code is as follow:

// checks if the required cgroups subsystems are mounted.
// As of now, only 'cpu' and 'memory' are required.
// cpu quota is a soft requirement.
func validateSystemRequirements(mountUtil mount.Interface) (features, error) {
        const ( 
                cgroupMountType = "cgroup"
                localErr        = "system validation failed"
        )
        var (  
                cpuMountPoint string
                f             features
        )
        mountPoints, err := mountUtil.List()
        if err != nil {
                return f, fmt.Errorf("%s - %v", localErr, err)
        }

```
    expectedCgroups := sets.NewString("cpu", "cpuacct", "cpuset", "memory")
    for _, mountPoint := range mountPoints {
            if mountPoint.Type == cgroupMountType {
                    for _, opt := range mountPoint.Opts {
                            if expectedCgroups.Has(opt) {
                                    expectedCgroups.Delete(opt)
                            }
                            if opt == "cpu" {
                                    cpuMountPoint = mountPoint.Path
                            }
                    }
            }
    }

    if expectedCgroups.Len() > 0 {
            return f, fmt.Errorf("%s - Following Cgroup subsystem not mounted: %v", localErr, expectedCgroups.List())
    }

    // Check if cpu quota is available.
    // CPU cgroup is required and so it expected to be mounted at this point.
    periodExists, err := util.FileExists(path.Join(cpuMountPoint, "cpu.cfs_period_us"))
    if err != nil {
            glog.Errorf("failed to detect if CPU cgroup cpu.cfs_period_us is available - %v", err)
    }
    quotaExists, err := util.FileExists(path.Join(cpuMountPoint, "cpu.cfs_quota_us"))
    if err != nil {
            glog.Errorf("failed to detect if CPU cgroup cpu.cfs_quota_us is available - %v", err)
    }
    if quotaExists && periodExists {
            f.cpuHardcapping = true
    }
    return f, nil
```

}

**Comment by luxas** [comment]
cc @vishh 

If 'cpuset` and `cpuacct` only are soft requirements, we should definitely fix this before `v1.3`

**Comment by vishh** [comment]
@luxas We will need those cgroups in the near future. Instead of introducing a breaking change later, we decided to require them from the beginning. Do you still think its necessary to remove those cgroups?
Is this a technical issue or a documentation issue?

**Comment by luxas** [comment]
Didn't know you're planning to use them soon.
Then it's a documentation issue. See: #26093

**Comment by stevesloka** [comment]
I had the same problem running k8s on Hypriot. I had to add `cgroup_enable=cpuset` to `/boot/cmdline.txt`

I'm running v1.3.0

**Comment by choldrim** [comment]
@stevesloka thanks hints, but I can found `/boot/cmdline.txt` file
perhaps I am using grub2 on debian like system, and I found the solution for me on this page [https://wiki.debian.org/LXC](https://wiki.debian.org/LXC)

> it can be easily done by setting `GRUB_CMDLINE_LINUX="cgroup_enable=memory"` in `/etc/default/grub` and running `update-grub2`

for this issue, if someone using the debian like system, just add `GRUB_CMDLINE_LINUX="cgroup_enable=cpuset"` in `/etc/default/grub` and running `sudo update-grub2`
