### ISSUE TITLE
Kubernetes networking options for Azure

### ISSUE THREAD

**Issue by codefx9** [kubernetes/kubernetes#26039]
Hi,
I am trying to setup a Kubernetes cluster for Azure. What are my networking options? I have found some articles and a CoreOS based setup with Weave. I am interested in using their new resource group model instead of the classic VMs.

Thanks.

**Comment by mikedanese** [comment]
cc @colemickens

**Comment by colemickens** [comment]
Networking options? Today you'll want to run an overlay network like flannel. I'm working on a cloudprovider implementation for Azure that will use User Defined Routes (like on GCE/AWS) for native routing, but that's still a couple weeks away at least.

**Comment by thockin** [comment]
@colemickens - AWESOME news!!

**Comment by caseydavenport** [comment]
@colemickens - Awesome! Really excited for that :)

@codefx9 - As mentioned above, flannel (vxlan backend) is a good choice here.  We've been working with the CoreOS folks on [canal](https://github.com/tigera/canal), which combines the numerous backends provided by flannel together with the security policy from Calico.  Details on how to try it out can be found here: https://github.com/coreos/coreos-kubernetes

**Comment by codefx9** [comment]
@colemickens - This is GREAT news!!!

**Comment by codefx9** [comment]
@colemickens, If I may ask a follow up question, can you point me to some good documentation about the internals of Azure networking? I found some docs via googling, but those are not detailed enough. I am looking for docs that explains how the networking stacks, public private IP allocation, firewalls, etc works in Azure (something similar to https://cloud.google.com/compute/docs/networking doc but for Azure).

**Comment by colemickens** [comment]
* [Networking Overview](https://azure.microsoft.com/en-us/documentation/services/virtual-network/)

which includes these topics:

* [User Defined Routes](https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-udr-overview/)

* [Network Security Groups](https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-nsg/)

**Comment by codefx9** [comment]
Thanks a lot @colemickens
