### ISSUE TITLE
Make sure all deepcopy generated files are actually generated by the new generator

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#26036]
@thockin reports that this is not true.

P0 because if this is not true, we may be copying partial objects.

**Comment by thockin** [comment]
Look at util/sets, instructions, pkg/API/resource, meta etc.

**Comment by wojtek-t** [comment]
Just answering for pkg/api/resource:

- it is generated, because it's imported from e.g. pkg/api

And because it's not explicitly mentioned in main.go file in generator, it doesn't have init() function:
https://github.com/kubernetes/kubernetes/blob/master/cmd/libs/go2idl/deepcopy-gen/generators/deepcopy.go#L93

I'm pretty sure the same case is for other files, but I will double check on Monday.

**Comment by thockin** [comment]
```
$ make clean
build/make-clean.sh
+++ [0522 20:40:30] Verifying Prerequisites....
!!! [0522 20:40:30] Build image not built.  Cannot clean via docker build image.
+++ [0522 20:40:30] Removing data container
+++ [0522 20:40:30] Cleaning out local _output directory
+++ [0522 20:40:30] Deleting docker image kube-build:build-c7855f1405
+++ [0522 20:40:31] Cleaning all other untagged docker images
rm -rf _output
rm -rf Godeps/_workspace # Just until we are sure it is gone

$ find . -name deep_copy_generated.go | xargs rm

$ ./hack/update-codegen.sh >/dev/null 2>&1

$ git st -s | grep "^ *D"
 D pkg/api/meta/deep_copy_generated.go
 D pkg/api/meta/metatypes/deep_copy_generated.go
 D pkg/api/resource/deep_copy_generated.go
 D pkg/api/unversioned/deep_copy_generated.go
 D pkg/conversion/deep_copy_generated.go
 D pkg/labels/deep_copy_generated.go
 D pkg/runtime/deep_copy_generated.go
 D pkg/runtime/serializer/deep_copy_generated.go
 D pkg/util/intstr/deep_copy_generated.go
 D pkg/util/sets/deep_copy_generated.go
```

**Comment by wojtek-t** [comment]
@thockin - something has changed recently - it used to work ~month ago. I will take a look (I can reproduce it locally).

**Comment by wojtek-t** [comment]
Yeah - actually it was added ~2 weeks ago in:
https://github.com/kubernetes/kubernetes/pull/25033

@smarterclayton 

Though, after this change, if we simply get rid of "inputs.Has(...)" there, it will try to generate files also from non-k8s dependencies, which we don't want.

I will try to do some quick fix for now.

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/26051 is a quick fix for that

However, we can probably solve it differently at some point. Though that PR should reduce priority of this bug.

**Comment by smarterclayton** [comment]
I noticed this yesterday and thought I was crazy.

**Comment by smarterclayton** [comment]
These directories should be in the "inputs"

**Comment by thockin** [comment]
Then we need to distinguish which inputs self-register and which do not.

**Comment by wojtek-t** [comment]
Yeah - we probably need another flag to pass those that shouldn't be registered.

**Comment by smarterclayton** [comment]
In the proto code I used the "-" prefix to indicate a package that is
included in the search order, but should not automatically generate
messages for everything.

**Comment by smarterclayton** [comment]
Opened #26179, I prefer this over #26051 because it keeps OpenShift not broken and also fixes a few other DeepCopy issues.
