### ISSUE TITLE
Scheduler cache could double assume pods

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#26043]
Recently bind action was made asynchronous. However, a pod is **assumed** before bind:

https://github.com/kubernetes/kubernetes/blob/57f63217886937888a9d27c60b9e8cb5374cdf55/plugin/pkg/scheduler/scheduler.go#L122-L122

If bind failed, it will call Error(), which is this func:

https://github.com/kubernetes/kubernetes/blob/57f63217886937888a9d27c60b9e8cb5374cdf55/plugin/pkg/scheduler/factory/factory.go#L476-L511

We saw that the pod would be retried again:

``` Go
            if pod.Spec.NodeName == "" {
                podQueue.AddIfNotPresent(pod)
            }
```

This breaks the assumption made in scheduler cache:

https://github.com/kubernetes/kubernetes/blob/57f63217886937888a9d27c60b9e8cb5374cdf55/plugin/pkg/scheduler/schedulercache/interface.go#L34-L53

In cache, we assumes that double assume shouldn't take place. But now it's possible.

**Comment by hongchaodeng** [comment]
@wojtek-t @xiang90 @kubernetes/sig-scheduling

**Comment by wojtek-t** [comment]
I think this is a result of #24459

@fgrzadkowski @davidopp

**Comment by fgrzadkowski** [comment]
@wojtek-t Can you please explain how this is related with the pod condition change? The scenario that @hongchaodeng described could have happened before #24459

**Comment by wojtek-t** [comment]
@fgrzadkowski - yeah, I think you're right. I think I didn't read the whole store carefully enough.

**Comment by hongchaodeng** [comment]
I have two solutions:
- allow double assume
- resume assumed pod when bind() failed

I would prefer the second one because of its stronger checking. WDYT? @wojtek-t

**Comment by wojtek-t** [comment]
In 2. we need to be very careful about races. I would have to think about it...

**Comment by timothysc** [comment]
Can we close this issue?
