### ISSUE TITLE
hack/install-etcd.sh installs Linux binary on non-Linux machines

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/kubernetes#26041]
`hack/install-etcd.sh` is [hard-wired to download a Linux binary](https://github.com/kubernetes/kubernetes/blob/52707ac7ee95e4fd4ee67c167785920cdbdc8ec4/hack/lib/etcd.sh#L71) and does not honor the platform it is invoked on. I noticed this when I needed to install etcd on my Mac (which, in turn, was required by `hack/update-swagger-spec.sh` and transitively by the pre-commit hooks) and later failed to execute it due to an incompatible binary.

**Comment by MHBauer** [comment]
Oh wow, that explains my failures. I ended up using homebrew.
