### ISSUE TITLE
unit flake: reflector_test.go:384: expected exiting from err expected resync reached, got: <nil>

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#26058]
In per-PR build:
```
--- FAIL: TestReflectorResync (0.01s)
	reflector_test.go:384: expected exiting from err expected resync reached, got: <nil>
```
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26054/kubernetes-pull-test-unit-integration/27306/

cc @kubernetes/sig-api-machinery @wojtek-t @lavalamp

**Comment by wojtek-t** [comment]
@rrati @xiang90

**Comment by wojtek-t** [comment]
This is not a flake - it's broken.
I will send a fix for it in few minutes.
