### ISSUE TITLE
e2e flake: Pod Disks tests are very flaky

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#26076]
The following tests failed multiple times both in GCE and GKE suites:
```
Pod Disks should schedule a pod w/two RW PDs both mounted to one container
Pod Disks should schedule a pod w/ a RW PD shared between multiple containers
```
The error message is the same:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:271 Expected error: <*exec.ExitError | 0xc8207d7c60>: { ProcessState: { pid: 5426, status: 256, rusage: { Utime: {Sec: 0, Usec: 92000}, Stime: {Sec: 0, Usec: 16000}, Maxrss: 29244, Ixrss: 0, Idrss: 0, Isrss: 0, Minflt: 2153, Majflt: 0, Nswap: 0, Inblock: 0, Oublock: 0, Msgsnd: 0, Msgrcv: 0, Nsignals: 0, Nvcsw: 725, Nivcsw: 5, }, }, Stderr: nil, } exit status 1 not to have occurred
```

Logs:
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5896
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5899
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5903
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5904

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4491
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4495
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4496
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4497
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4500
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4503

**Comment by piosz** [comment]
Assigning @thockin for fix or triage.
cc @kubernetes/sig-storage

**Comment by rootfs** [comment]
I can work on this, as I am writing tests for openstack in `pd.go`.

**Comment by piosz** [comment]
It would be great!

**Comment by thockin** [comment]
Huamin,

Thanks for jumping on this.  Please consider it priority - flaky tests are
killing us, and if this turns out to be real, we need it fixed.

**Comment by rootfs** [comment]
sure

**Comment by spxtr** [comment]
These two tests are so flaky that they will block the merge queue for over half of the time it takes to merge a fix. If you think the fix will take more than a day, I'd suggest moving these to the flaky suite until they're fixed.

**Comment by ixdy** [comment]
I'd suggest tagging them flaky ASAP. Whenever they get fixed they can be untagged.

**Comment by pmorie** [comment]
I am okay with moving these to the flaky suite until we can get some focus on it. @childsb

**Comment by spxtr** [comment]
PR is #26089, will likely need a manual merge since the SQ is so blocked.

**Comment by saad-ali** [comment]
Hang on this looks like it was broken by a PR merged on Sunday: https://github.com/kubernetes/kubernetes/pull/21709

Test Run http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-slow/5873/ and earlier are Green.
Test Run http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-slow/5874/ (after this PR was merged) are Flaky.

CC @swagiaal 

I'll prepare a roll back.

**Comment by rootfs** [comment]
@saad-ali good catch, i'll take a look at the gce attacher.

**Comment by rootfs** [comment]
@saad-ali give me some moments to figure out a fix

**Comment by spxtr** [comment]
I think the appropriate thing to do here was to move them into the flaky suite or revert the offending PR right away.

**Comment by saad-ali** [comment]
Agreed, this could've been handled better.

**Comment by saad-ali** [comment]
PR marking tests as flaky (https://github.com/kubernetes/kubernetes/pull/26089) has been merged. @rootfs will follow up with his PR (https://github.com/kubernetes/kubernetes/pull/26100) to see if he can fix the test, if so, he will move the tests back out of flaky.

**Comment by lavalamp** [comment]
Occurrences tracked automatically in #26127. I don't care if you leave this one open too.

**Comment by saad-ali** [comment]
Closing this in favor autogenerated #26127
