### ISSUE TITLE
Identify, document and maybe remove kubelet dependencies

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#26093]
Kubelet has a few dependencies, and we should be aware of them, document them so users know what's the minimum amount of other programs kubelet needs around it to execute successfully.

I'm testing this by compiling kubelet statically and running it in a `busybox` container with absolutely nothing. I've been surprised how well it runs after all.

I'm listing some, both hard and soft dependencies:
- `glibc`: hard dependency on the right libraries at runtime. We should get rid of this, as it's unnecessary: #26028
- `root` access: hard dependency and unavoidable. The kubelet has to have full control of the machine (`CAP_SYS_ADMIN` is one of the privs that are needed, at least when running in a container)
- `cgroups`
  - `cpu` and `memory`: required and used in the meantime
  - `cpuacct` and `cpuset`: required but not used (but @vishh said they will be used in the future)
- `journalctl`: _bug in cAdvisor_, should not be required
- `iptables`: Is required for the kubelet it seems: #26264, although now flannel isn't initialized when not used.
- `ethtool`: Required for `hairpin` [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/hairpin/hairpin.go#L72). I do not really understand what `hairpin` is required/used for... @thockin @bprashanth  
- `nsenter`: Used as `util/io/writer` when `--containerized`. Used by `--docker-exec-handler`, but not default. Used with `socat` for port forwarding within a pod.
- `mount`, `umount` and `findmnt`: Used in `NsenterWriter` in `util/io/writer`
- `socat`: Used for port forwarding within a pod. [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1056)
- `touch`: Used by `rkt` [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/rkt/rkt.go#L215)
- `docker` or `rkt` obviously
- `systemd`? Does `rkt` require a `systemd` host? @yifan-gu 
- Paths:
  - `/:ro` it must be able to read from the whole host
  - `/var/run/:rw` required for communicating with docker, setting up certs etc.
  - `/sys/:rw` for various `cgroup` things
  - `/var/lib/kubelet:rw` and `/var/lib/docker:rw` it obviously must be able to write to it's own and docker's dir

for `kube-proxy`:
- `iptables`: is of course a hard requirement. But the problem is that (as it seems) iptables has to be linked dynamically, which sets a `glibc` dep on the `kube-proxy` image.
- `conntrack`: used for limiting requests (I think)

inside client containers:
- `env`: Seems like it's required inside a container that Kubernetes is running, but only when using `--docker-exec-handler=native` [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/exec.go#L48)

volume plugins:
- `dmidecode`: required for the vsphere plugin
- `glusterfs-server`, `glusterfs-client` are required for the `glusterfs` plugin
- `git` is required for the git plugin

Please correct me if I'm wrong, and comment if there is anything I've missed. 
Would appreciate discussion about this (and we should have multi-platform Kubernetes in mind)

cc @vishh @smarterclayton @mikedanese @pmorie

**Comment by vishh** [comment]
@pwittrock What is the best way to document these requirements moving forward?

**Comment by pmorie** [comment]
@luxas Classy digging, and this is super-useful to have.  +100

We should decide at what level we want to document transitive deps.  For example, cadvisor is going to begin calling `thin_ls` to monitor containers backed by devicemapper thin pools.  Since disk eviction is going to use this, I would want to know about that specific dep, though it is not strictly a dependency of the kubelet itself.

**Comment by pwittrock** [comment]
@vishh I think adding a page to the "Administering Clusters" at http://kubernetes.io/docs/ would be the best place

**Comment by luxas** [comment]
@pmorie Thanks :) It took some time to dig it out.

When we document it, I think we should present them in groups, e.g. always required, required with option `--xxx`, required when using yyy as the storage driver, and nice-to-haves.

But we should also get rid of some:
 - `glibc`: #26028
 - `touch` when using `rkt`. Seems simple enough to remove.
 - `iptables` we shouldn't call `NewFlannelOverlay()` regardless of the option, only if it's enabled.

**Comment by luxas** [comment]
Some things I've learned so far (will update the list)
 - iptables is effectively required for the kubelet, although flannel is deactivated: #26264 
 - journalctl shouldn't be a dependency to cAdvisor, that's a bug: google/cadvisor#1313

**Comment by pmorie** [comment]
Looks like #26658 may add a dependency on `dmidecode`

**Comment by pmorie** [comment]
There's a dependency on `dmidecode` in the vSphere volume plugin.

**Comment by luxas** [comment]
@pmorie Added. Do you remember any others right now?

**Comment by pmorie** [comment]
@luxas Nope, I just saw that one during a code review.

**Comment by timstclair** [comment]
In addition to documenting these, I think it would be useful to check for all of them on kubelet startup. Hard dependencies should log fatal errors, and soft dependencies could log warnings.

**Comment by detiber** [comment]
nfs-utils is needed by the nfs volume plugin.

**Comment by detiber** [comment]
ceph-common (at least on Fedora/Red Hat/CentOS based systems) is needed for the ceph volume plugin

**Comment by detiber** [comment]
glusterfs-fuse should be all that is needed for using the gluster storage plugin (at least on Fedora/Red Hat/CentOS based systems).

**Comment by detiber** [comment]
iscsi-initiator-utils (Fedora/Red Hat/CentOS based systems) is needed by the iscsi volume plugin

**Comment by detiber** [comment]
@timstclair I'm not sure you would want a fatal error if a storage plugin dependency isn't available, I would expect them to just not be loaded (and an obvious event and log message generated) if that is the case.

**Comment by luxas** [comment]
Thanks @detiber! (And for anyone out there that knows even more deps of the kubelet, comment!)

I think @timstclair meant that all storage drivers are soft deps, so kubelet would log a warning.

**Comment by philips** [comment]
Is this part of NodeSpec? I am still unclear what https://github.com/kubernetes/features/issues/56 is trying to describe.

cc @vishh @dchen1107 @yujuhong @aronchick @aaronlevy

**Comment by luxas** [comment]
Just noticed that `pkg/kubelet/container_bridge.go` has a lot of dependencies on binaries in $PATH.
 - brctl
 - ip
 - pkill
 - (service|systemd|docker-babysitter)

**Comment by luxas** [comment]
Summarizing the PATH requirements for kubelet (oh my!):
 - `pidof` in `pkg/kubelet/cm/container_manager_linux.go`
 - `uname -n` in `pkg/util/node/node.go`
 - `mount` and `umount` in `pkg/util/mount/mount_linux.go`
 - `lsblk`, `fsck`, `mkfs` in `pkg/util/mount/mount_linux.go`
 - `nsenter` in a lot of places!
 - `ethtool` in `pkg/kubelet/network/hairpin/hairpin.go`
 - `socat` in `pkg/kubelet/dockertools/docker_manager.go` and `pkg/kubelet/rkt/rkt.go`
 - `touch` in `pkg/kubelet/rkt/rkt.go`
 - `env` (inside the container) in `pkg/kubelet/dockertools/exec.go`
 - `iptables`, `iptables-restore`, `iptables-save` in `pkg/util/iptables/iptables.go` and many other places
 - `brctl` in `pkg/kubelet/container_bridge.go`
 - `pkill` in `pkg/kubelet/container_bridge.go`
 - `ip` in `pkg/kubelet/container_bridge.go`, `pkg/kubelet/network/plugins.go`, `pkg/kubelet/network/plugins.go`, `pkg/kubelet/rkt/rkt.go`
 - `modprobe` in `pkg/kubelet/network/plugins.go`
 - `tc` in `pkg/util/bandwidth/linux.go`
 - `journalctl` in `vendor/github.com/google/cadvisor/utils/oomparser/oomparser.go`, but it's not a hard requirement
 - `thin_ls` in `vendor/github.com/google/cadvisor/devicemapper/thin_ls_client.go` for the devicemapper storage driver
 - `nice`, `du`, `dmsetup` in `vendor/github.com/google/cadvisor/fs/fs.go`, are these important?

Hard requirements (kubelet should fail without these):
 - root access (is there an easy way to check for `CAP_SYS_ADMIN`?)
 - `cpu`, `cpuset`, `cpuacct`, `memory` cgroups mounted
 - `iptables`, `ip` must be present for kubelet networking
 - `nsenter` must be present for kubelet container management
 -  `mount` and `umount` is required for nearly all types of volumes
   - `syscall.Mount()` [is a wrapper](https://golang.org/src/syscall/syscall_linux.go?s=20289:20384#L786) for [`mount(2)`](http://linux.die.net/man/2/mount), but if we strictly need `mount(8)`, that's a hard dependency @kubernetes/sig-storage 
 - the `br-netfilter` module. kubelet should try to enable it on linux >= 3.18 with modprobe, and if it isn't enabled earlier or if modprobe doesn't exist, kubelet should fail (or should it?)
 - write access to `/sys`, `/var/lib/docker` and `/var/lib/kubelet`

I'm not sure if these should be hard or soft deps:
 - `socat` might be replaced by the `gRPC` protocol when `Exec`-ing, but still it's used for port-forwarding
 - `ethtool` used for `hairpin` @thockin how important is it?

How to remove some dependencies (before v1.4):
 - `uname -n` should be replaced with `os.Hostname`
 - `brctl` should be replaced by calls to the `netlink` go package
 - `pkill` with `syscall.Kill`
 - `pidof`, if we think it's worth it, we can do [this](http://stackoverflow.com/a/375136)
 - `touch` can be replaced with `os.Chtimes` [link](http://grokbase.com/t/gg/golang-nuts/13bmsb9tzd/go-nuts-can-go-set-a-timestamp-to-a-file)

A dedicated `pkg/util/nsenter` package should be made, now it's called in ~10 different places in 10 different ways.

I can start to implement a `pkg/kubelet/validator` package that checks for these dependencies.

WDYT?
@kubernetes/sig-cluster-lifecycle @kubernetes/sig-node @kubernetes/sig-network

**Comment by jsafrane** [comment]
>*  mount and umount is required for nearly all types of volumes
>  *    syscall.Mount() is a wrapper for mount(2), but if we strictly need mount(8), that's a hard dependency @kubernetes/sig-storage

Not only we need `/bin/mount`, we need all mount utilities like `mount.nfs`, `mount.ceph` and `mount.glusterfs`. Simple `mount(2)` syscall is not enough.

**Comment by euank** [comment]
the rkt runtime does require systemd on the host currently, @luxas. There's no immediate plans to change it, but also no hard reason it couldn't be changed.

cc @aaronlevy @pbx0

**Comment by ncdc** [comment]
We're looking at moving `socat` to the pod infra image eventually.

**Comment by lukemarsden** [comment]
@luxas, that would be awesome. We'd like to add a pre-flight check to initial cluster installation in @kubernetes/sig-cluster-lifecycle 

> Pre-flight check: If any of the computers don't have working dependencies installed (e.g. bad version of Docker, too-old Linux kernel), I am informed early on and given clear instructions on how to fix it so that I can keep trying until it works.

Relatedly, do we have an idea about which versions of Docker are recommended, and also which kernels are suitable?

**Comment by luxas** [comment]
Yes, I'm a part of sig-cluster-lifecycle, and have worked quite a lot on tasks related to it, just couldn't make it to the meetups (yet!)

v1.4 will probably support 1.10, 1.11 and 1.12 with the "three dockers rule", but I haven't got this confirmed yet.

I don't know a specific linux kernel number that's required, but have got things ~working on a 3.10 kernel.
(Didn't test all features though, and 3.10 is out of scope as it's EOL)

**Comment by lukemarsden** [comment]
Awesome, thanks @luxas! As soon as you have some code in `pkg/kubelet/validator` I'd be happy to review and/or test it.

@bgrant0607 do you happen to know which dockers 1.4 is likely to support, and also which kernel versions cause problems for us?

**Comment by lukemarsden** [comment]
@Random-Liu thanks for noticing the overlap with #28408!

**Comment by luxas** [comment]
@pmorie in https://github.com/kubernetes/kubernetes/issues/4869#issuecomment-213581040
> What I would like to be able to do is containerize all mount operations so we can package fs drivers as containers and avoid dependencies on the host at all

Are there plans to do this for v1.4? Yet, I've been focusing on kubelet's core dependencies.

**Comment by lukemarsden** [comment]
FWIW, for @kubernetes/sig-cluster-lifecycle we are presently assuming that kubelet will not run containerized in the default configuration; rather that kubelet is installed using OS packages (which will also install e.g. systemd units to start it on boot) and run as a bare Golang binary on the host.

**Comment by luxas** [comment]
Yes, I know, but I think this was about packaging the storage drivers themselves in containers so kubelet would just pull e.g. `gcr.io/google_containers/storage-driver-nfs` and use that for mounting volumes.

**Comment by lukemarsden** [comment]
Could storage drivers be add-ons, installed via `kubectl apply`? That's what we're planning to do for CNI network drivers.

**Comment by colemickens** [comment]
You need to mount `/var/log/containers` for fluentd to be able to grab container logs.

**Comment by bgrant0607** [comment]
cc @kubernetes/docs

**Comment by luxas** [comment]
Status update:

Things that kubelet depend hard on:
 - being root: https://github.com/kubernetes/kubernetes/pull/30466
 - `glibc` (kubelet won't start otherwise)
 - cpu, cpuset, cpuacct, memory cgroups mounted
 - `iptables`, `iptables-restore`, `iptables-save`, `ip`, `nsenter`, `mount` and `umount`
 - `socat` for port-forwarding
 - the `br-netfilter` module. (if the module is not enabled when kernel is >= 3.18, `modprobe` is required)
 - write access to /sys, /var/lib/docker and /var/lib/kubelet

Soft (recommended) deps:
 - `lsblk`, `fsck`, `mkfs` for remounting filesystems in `pkg/util/mount/mount_linux.go`
 - `touch`, `systemd` when using `rkt`
 - `tc` when trying to shape network traffic when using kubenet

Deps that are on their way out:
 - `uname -n` https://github.com/kubernetes/kubernetes/pull/30014
 - `brctl` https://github.com/kubernetes/kubernetes/pull/30056
 - `pkill` https://github.com/kubernetes/kubernetes/pull/30087
 - `pidof` https://github.com/kubernetes/kubernetes/pull/30002
 - `ethtool` https://github.com/kubernetes/kubernetes/pull/30356
 - I'm trying to get rid of `glibc` https://github.com/kubernetes/kubernetes/pull/26028

I'm working on a package that validates the kubelet deps, but all deps will initially be soft (non-fatal) to avoid regressions.
cc @kubernetes/sig-cluster-lifecycle

**Comment by thockin** [comment]
While I applaud the effort, is this really worth the effort?  Specifically all the tiny network utils.  You're replacing obvious, debugged code (calls to exec well-known tools) with new undebugged code that is significantly longer and more complicated.

Is it REALLY worthwhile?

**Comment by jimmycuadra** [comment]
Long term it seems worth it, though the ratio of effort to practical benefit may not be great for some of the more ubiquitous tools. In some cases there are problems with assuming things about the host, like the lack of socat on CoreOS hosts.

**Comment by thockin** [comment]
That's not a great argument to me -- we're not going to implement socat
ourselves.  That is a highly optimized piece of code with a bazillion
features.

**Comment by jimmycuadra** [comment]
I was talking about packaging tools like that in the kubelet image, not reimplementing them as part of the kubelet binary.

**Comment by errordeveloper** [comment]
Packaging tools like this in a container works for Weave Net, although we
have recently got rid of ethtool and implemented the only feature we used
in Go. There is a long debate on wether kubelet should be containerised or
not, but tools could be in a container of their own. Also, statically
linked tools in a prefix directory is something we should discuss as an
alternative.

**Comment by thockin** [comment]
For containerized kubelet, getting rid of exec() deps is sort of pointless, right?

For "native" kubelet, there's some attractive things about eliminating these deps, but this process REALLY REALLY comes at a cost.  I am less convinced over time that the cost is justified.

Looking at the PRs that are currently pending but not merged, I am worried that we're trading complexity OUTSIDE of kubernetes (tools) for complexity INSIDE.  This feels backwards to me...

**Comment by luxas** [comment]
> For containerized kubelet, getting rid of exec() deps is sort of pointless, right?

No, it isn't pointless. At least for me, every MB counts when dealing with the `hyperkube` image, and the less packages we have to install, the better.

> For "native" kubelet, there's some attractive things about eliminating these deps, but this process REALLY REALLY comes at a cost. I am less convinced over time that the cost is justified.

> Looking at the PRs that are currently pending but not merged, I am worried that we're trading complexity OUTSIDE of kubernetes (tools) for complexity INSIDE. This feels backwards to me...

I guess you mean my PRs for ethtool and brctl.
I understand your worry, but I don't think it's that bad:
 - brctl can be replaced with `vishvananda/netlink`, which I think is a pretty well-tested package
   - `exec.Command("brctl", "addbr", "cbr0").Run() => netlink.LinkAdd`
   - `exec.Command("ip", "addr", "add", wantCIDR.String(), "dev", "cbr0").Run() => netlink.AddrAdd`
   - `exec.Command("ip", "link", "set", "dev", "cbr0", "mtu", "1460", "up").Run() => netlink.LinkSetUp`
   - `exec.Command("ip", "addr", "show", "cbr0").Output() => netlink.AddrList(br, syscall.AF_INET)`
   - That´s all. I don't think this adds complexity at all, pretty the opposite as I cleaned up the file a bit at the same time.
 - I found that `ip link` shows the same output as `ethtool` in most cases. 
   - Somehow @freehan found a corner case, but anyway, I think we could:
   - query `ip link` first (which is a well-known dep already), and then if `ip link` doesn't find anything,
   - query `ethtool`, and if `ethtool` doesn't find anything,
   - do it for all interfaces.
   - In this case, I'd only add one step: searching for the pair interface with `ip link`. That does not add much complexity given that probably in 90% of the cases, `ethtool` won't be required.

@thockin Will you merge https://github.com/kubernetes/kubernetes/pull/30056, which is ready or do you still think it's too much?


My primary goal is to identify the deps and make a package that checks for them. Also, I'm planning to write a doc to the users. That's worth a lot for end users, since no one wants to read through the whole k8s code searching for deps: Why didn't this feature X work?

But those deps that are obvious and quite simple to remove, should be removed. (e.g. `uname -a` == `os.Hostname()`)

**Comment by errordeveloper** [comment]
Personally, I agree with Lucas, the netlink stuff  is rather reasonable
bring in.

**Comment by euank** [comment]
Each MB should not count with containerized kubelet. We've already got a honkin' 170MB binary in hyperkube, with a docker image that weighs in at ~500MB.

When I removed socat it saved me... 950KB. When I'm deploying a 500MB binary, no, every MB does not count. If that MB avoids even a single bug, or just a few hours of development effort, it's worth it to me. And reimplementing socat in go will increase the hyperkube size, possibly by more than it saved :smile: 

I'm all for trimming execs and dependencies when those dependencies have proven to be buggy, a bad fit, or there's some other data supporting it... but the majority of the kubelet dependencies (`mount` calls, network tools) are thin, battle-hardened, and easy to get your hands on.

Anyways, I think a document listing all the dependencies would be great to have. Thanks for all the work identifying them!
One other type of dependency we haven't listed here yet is kernel modules, which might be worth calling out. I'm thinking of something like the [check-config](https://github.com/docker/docker/blob/v1.12.1/contrib/check-config.sh) script docker has, which is really nifty and we could potentially borrow wholesale.

Finally, after we document these, it might be worth fitting these into the idea of "node conformance" (e.g. run this to make sure your node is good for running k8s stuff), which I think is tracked by the n feature: https://github.com/kubernetes/features/issues/56. @phillips asked if this is related to that above, and I don't think we got an answer, so cc @vishh @dchen1107 for if the document of all dependencies will be used in creating that feature.

**Comment by luxas** [comment]
> When I removed socat it saved me... 950KB. When I'm deploying a 500MB binary, no, every MB does not count. If that MB avoids even a single bug, or just a few hours of development effort, it's worth it to me. And reimplementing socat in go will increase the hyperkube size, possibly by more than it saved :smile:

I haven't and will never propose to remove the socat dep. On the other hand, I'll gladly investigate if it's worth it to move the socat dep into a container, as the comments above the `PortForward` code says.

> I'm all for trimming execs and dependencies when those dependencies have proven to be buggy, a bad fit, or there's some other data supporting it... but the majority of the kubelet dependencies (mount calls, network tools) are thin, battle-hardened, and easy to get your hands on.

Yeah, this is mostly about identifying them all. If we then find something unnecessary (like `uname -a`), we should remove it. And also, if we find an exec with a dep that's unnecessary like `brctl` we should replace it with a) exec `ip` (another already required dep) or b) `netlink`.

The same goes for `ethtool`. When kubenet or cni is used, the default iface name inside container will be `eth0@ifxxx` where `xxx` equals to `ethtool -S eth0`. So why not just replace the `ethtool` exec then with an `ip` exec? (In the meantime, the old cbr0 stuff didn't have `eth0@ifxxx` names, so we have to wait to 1.5 before applying my patch)

That's what this issue is about.

> One other type of dependency we haven't listed here yet is kernel modules, which might be worth calling out

I have found at least one, ping me if you find more required kernel modules.
> - the br-netfilter module. (if the module is not enabled when kernel is >= 3.18, modprobe is required)

> I'm working on a package that validates the kubelet deps, but all deps will initially be soft (non-fatal) to avoid regressions.

I'm working on a check-config-like package for kubelet and kube-proxy written in Go, which will be available in v1.5. Then an utility like kubeadm may also vendor that package and provide a `kubeadm verify-node` command for example.

> Finally, after we document these, it might be worth fitting these into the idea of "node conformance" (e.g. run this to make sure your node is good for running k8s stuff), which I think is tracked by the n feature: kubernetes/features#56. @phillips asked if this is related to that above, and I don't think we got an answer, so cc @vishh @dchen1107 for if the document of all dependencies will be used in creating that feature.

I'm not too familiar with how you're planning to implement the `NodeSpec` feature, but I guess it will be integrated quite a lot with this issue.

One thing I'm _really_ looking forward to is the containerized volume drivers. cc @kubernetes/sig-storage again. Can we implement this for real in time for v1.5? At least for the most common ones: `nfs`, `ceph` and `glusterfs`. That would be a significant improvement for end users, since they don't want to install and set up a lot of storage drivers "they might use" at some point in the future just to be safe; they just want to start the kubelet and let it mount whatever filesystem is passed.

@euank Thanks for the feedback, let's move on in v1.5!

**Comment by SEJeff** [comment]
@luxas It doesn't look like anyone answered your hairpin NAT question, so here goes... Hairpin NAT is a new-ish feature in Linux that allows requests from the internal bridged interface for an ip assigned to the external interface get NAT'd as though they came externally. Basically, it allows routing on loopback interfaces. This is how they managed to get rid of the abomination in docker (hold your jokes) that was `docker-proxy`. Pre-hairpin NAT support, they needed docker-proxy to do NAT routing bits on loopback along with all of the throughput/latency/general fail it was. Now [docker](https://github.com/docker/docker/commit/b39d02b611f1cc0af283f417b73bf0d36f26277a) supports it along with [libcontainer](https://github.com/docker/libcontainer/pull/62)

**Comment by thockin** [comment]
NB that hairpin mode triggers a kernel bug in all known kernels, which
hangs the machine.  We use a different technique to achieve the same
result, until the bug is fixed.

**Comment by chrislovecnm** [comment]
@thockin / @luxas this issue is SUPER important.  Can we get a PR with a document 😀 

This issue is a tad difficult to follow.... Justsayin

**Comment by luxas** [comment]
> this issue is SUPER important

Well, that's why I created it :smile:

Seriously then, I'm having a lot to do right now, but if someone else could take it on, I'd appreciate it.
Everything one should need is stated in the comments above, but yeah, it might be a little bit difficult to follow given the amount of information at different given times.

**Comment by chrislovecnm** [comment]
@luxas more than that we need tooling to do this.  This is an issue that will cause us not to be able to scale, and once we break up the repos, it will be WORSE.

**Comment by pires** [comment]
Any updates on making the kubelet depend on less things or at least have it documented somewhere?

**Comment by luxas** [comment]
@pires I don't know.

cc @kubernetes/sig-node-feature-requests

**Comment by edevil** [comment]
So, I've just been bitten by the removal of "modprobe" from the hyperkube image when upgrading from 1.7 to 1.8 (https://github.com/kubernetes/kubernetes/issues/53396). What is the rational for removing needed tools from the image? Somehow I missed this detail in the release notes.

Anyway, what is the approach that we should take when deploying kubelet, proxy, etc from the hyperkube image? Do we have to mount the binaries from the host?

Is there an up-to-date list of the tools we need to mount?

**Comment by errordeveloper** [comment]
@luxas do you think we should keep this open and set `/lifecycle frozen`?

**Comment by luxas** [comment]
/help
I don't know what dependencies kubelet of today has, if someone could do an audit and dig into all the Exec calls, and report here it'd be great :smile:

**Comment by tallclair** [comment]
I was thinking about this a bit over the weekend, and have an idea I'd like to float before writing a more formal proposal. It's not a complete solution to this problem, but should help:

1. For every command that is exec'd, introduce a new package for that command (e.g. `k8s.io/command/git`)
    i. In that package, there is a dedicated object for building out the command arguments, and then exec'ing the command.
        a. Commands like `git` can have sub-commands (e.g. `GitClone` and `GitCheckout`)
        b. Commands like `nsenter` can accept other commands to wrap (there would be a standard interface for commands)
        c. Commands like `mount` can have sub-packages (e.g. `mount/nfs`)
    ii. The command has a setter for each argument, the setter MUST strongly validate the input. This is to address security issues where we're not sure whether the input has already been validated elsewhere in the stack. E.g. `func SetPath(path string) error { ... }`
2. Forbid raw usage of the `os/exec` library in Kubernetes code (once everything is migrated to the command package, or forbid new usage).
    i. Introduce a whitelist mechanism for vendored dependencies that use commands, requiring an audit of the command usage, but generally strongly discouraging dependencies that issue raw commands.

What does this get us?

- By making the dependencies part of the import path, it becomes much easier to audit their usage.*
- By centralizing the actual usage of `os/exec`, it means we can centrally require approval for new dependencies, and require security review as necessary.
- By centralizing the command code, we can ensure that every usage has fully validated arguments, for security

WDYT? Is it worth pursuing this idea further?

_* It even enables things like a 'registration' mechanism, so binaries can report their dependencies and check them at startup (differentiating required & optional deps)._

**Comment by rphillips** [comment]
@tallclair This proposal is extremely valuable. Being able to audit what tools are shelled out to helps with security, packaging, and maintenance. We could ship an image or package of standard 'shell utilities', be able to upgrade them and audit them for security vulnerabilities when needed.

Couple thoughts:

1) There should be a mechanism of extracting the utility's version... Semver might be needed if a utility is upgraded past a certain point.
2) Depending on the calling process logger's verbosity, the stdout and stderr from the utility process should be propagated back to the calling process's logger for easier debugging.

**Comment by dims** [comment]
@tallclair some similar work from openstack

- https://docs.openstack.org/oslo.rootwrap/queens/user/usage.html
- https://specs.openstack.org/openstack/oslo-specs/specs/juno/rootwrap-daemon-mode.html#daemon-starting

**Comment by PatrickLang** [comment]
+1 here. This will make it easier to make sure all OS or distro-dependent exec calls are audited and sanitized.

**Comment by luxas** [comment]
/assign @tallclair 
:smile:

**Comment by dims** [comment]
cc @andrewrynhard

**Comment by invidian** [comment]
I'm not sure if that's the right place to drop that (perhaps new issue should be created?), but for people running `kubelet` as a container while deploying Kubernetes, it would be super useful to have a list of capabilities, host directories etc where `kubelet` needs to have access **on host** in order to function properly. 

For my project, I run `kubelet` as a Docker container. I've tried looking for some documentation on how to do that, but I couldn't find any, so I had to do that simply with trials and errors, starting with simply running `kubelet` from `hyperkube` image via Docker, looking into error messages and googling each one for a solution.

I documented it [here](https://github.com/flexkube/libflexkube/blob/master/pkg/kubelet/kubelet.go#L189-L287), even though it's probably incomplete, as I didn't test everything yet.

**Comment by neolit123** [comment]
> I documented it here, even though it's probably incomplete, as I didn't test everything yet.

this type of documentation improvement is nice to have.
you can get feedback on this in the #sig-node slack channel on k8s slack or if you join their meeting:
https://github.com/kubernetes/community/tree/master/sig-node

**Comment by anarkiwi** [comment]
Just a note here - I had my own version of nsenter installed (via pip3 install) on ubuntu20. This caused a continual kubelet crash which took a while to diagnose - kubelet of course wanted nsenter from util-linux.

It sure would be nice if the preflight called out the dependency on the distro version of nsenter.

Oct 09 18:45:59 faucet kubelet[296741]: E1009 18:45:59.180219  296741 pod_workers.go:191] Error syncing pod db24ffc3-ef58-45b8-87f9-6da3dd701ce7 ("coredns-f9fd979d6-7d488_kube-system(db24ffc3-ef58-45b8-87f9-6da3dd701ce7)"), skipping: failed to "StartContainer" for "coredns" with CrashLoopBackOff: "back-off 40s restarting failed container=coredns pod=coredns-f9fd979d6-7d488_kube-system(db24ffc3-ef58-45b8-87f9-6da3dd701ce7)"
Oct 09 18:45:59 faucet kubelet[296741]: W1009 18:45:59.259650  296741 docker_sandbox.go:402] failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod "coredns-f9fd979d6-mm6kj_kube-system": unexpected command output usage: nsenter [-h] --target PID [--proc PROCFS] [--user] [--net] [--ipc]
Oct 09 18:45:59 faucet kubelet[296741]:                [--uts] [--pid] [--mnt] [--all]
Oct 09 18:45:59 faucet kubelet[296741]:                [command [command ...]]
Oct 09 18:45:59 faucet kubelet[296741]: nsenter: error: argument --net: ignored explicit argument '/proc/327613/ns/net'
Oct 09 18:45:59 faucet kubelet[296741]:  with error: exit status 2
Oct 09 18:45:59 faucet kubelet[296741]: E1009 18:45:59.260055  296741 pod_workers.go:191] Error syncing pod 5b915605-4d4a-4e22-967c-aaeee184f0cd ("coredns-f9fd979d6-mm6kj_kube-system(5b915605-4d4a-4e22-967c-aaeee184f0cd)"), skipping: failed to "StartContainer" for "coredns" with CrashLoopBackOff: "back-off 40s restarting failed container=coredns pod=coredns-f9fd979d6-mm6kj_kube-system(5b915605-4d4a-4e22-967c-aaeee184f0cd)"

**Comment by camilamacedo86** [comment]
@thockin, 

Could you please let us know why did you close this one?
Was it not accepted in the triage? If so, what is the reason?

**Comment by thockin** [comment]
Mostly backlog grooming.  This is 7 years old and the last meaningful update was 3 years ago.  Does it serve a purpose to leave it open?  Is someone going to do it?  It's a wonderful idea....if someone will act on it, let's reopen?
