### ISSUE TITLE
logo inconsistencies

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#26103]
The logo `name_*.svg` ([blue](https://github.com/kubernetes/kubernetes/blob/master/logo/name_blue.svg), [white](https://github.com/kubernetes/kubernetes/blob/master/logo/name_white.svg)) font does not match the others. I believe the png/pdf versions are correct.

**Comment by thockin** [comment]
What other ones?  It should be the same font - they look the same to me...
