### ISSUE TITLE
Fix PD tests and move out of flaky 

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#26141]
PR #https://github.com/kubernetes/kubernetes/pull/26089 moved some PD tests to flaky to resolve issue https://github.com/kubernetes/kubernetes/issues/26127 (and duplicate #26076). These tests started failing due to PR #21709.

@rootfs is working on a patch to de-flake the tests.

This issue is to track the fix and should be closed when:

1. The PD tests have been deflaked (verify by running the "pd.go" e2e tests back to back for a couple of hours to verify the issue is fixed).
2. The flaky label has been removed from the "pd.go" tests that were marked flaky in https://github.com/kubernetes/kubernetes/pull/26089

CC @kubernetes/sig-storage

**Comment by rootfs** [comment]
@piosz, how to watch the submit queue and find if the flake is gone?

**Comment by piosz** [comment]
I don't know.

@fejta is there any way @rootfs can verify whether test is no longer flaky?

**Comment by saad-ali** [comment]
@rootfs I'm not sure what the publicly accessible link for `kubernetes-e2e-gce-flaky` test history is.

I took a look for you:
* Pod Disks should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession
  * Failed 3 times in the last 30 runs. Stability: 90 %
* Pod Disks should schedule a pod w/two RW PDs both mounted to one container, write to PD, verify contents, delete pod, recreate pod, verify contents, and repeat in rapid succession
  * Failed 1 times in the last 30 runs. Stability: 96 %

I have a PR pending that enables the new attach/detach controller and I was able to run the tests back to back overnight without any failures. So once that gets merged, we can take a look at moving these tests back.

**Comment by jsafrane** [comment]
Something in PD attach/detach affects also 'Dynamic provisioning' e2e test, a PD is still attached to a node ~15 minutes after appropriate pod was deleted and thus deleter can't delete it.

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25881/kubernetes-pull-build-test-e2e-gce/42353/

```
...
May 27 14:29:19.926: INFO: PersistentVolume pvc-d002f85a-244e-11e6-b940-42010af00002 found and phase=Failed (19m56.091844001s)
May 27 14:29:24.927: INFO: Unexpected error occurred: PersistentVolume pvc-d002f85a-244e-11e6-b940-42010af00002 still exists within 20m0s

...

[k8s.io] Dynamic provisioning
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:641
  [k8s.io] DynamicProvisioner
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:641
    should create and delete persistent volumes [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/volume_provisioning.go:123

    Expected error:
        <*errors.errorString | 0xc820885b80>: {
            s: "PersistentVolume pvc-d002f85a-244e-11e6-b940-42010af00002 still exists within 20m0s",
        }
        PersistentVolume pvc-d002f85a-244e-11e6-b940-42010af00002 still exists within 20m0s
    not to have occurred
```

From controller log:

```
I0527 21:09:24.443191       7 gce_util.go:58] Error deleting GCE PD volume e2e-gce-master-0-dynam-pvc-d002f85a-244e-11e6-b940-42010af00002: googleapi: Error 400: The disk resource 'e2e-gce-master-0-dynam-pvc-d002f85a-244e-11e6-b940-42010af00002' is already being used by 'e2e-gce-master-0-minion-group-vd4g', resourceInUseByAnotherResource

...

I0527 21:14:31.371906       7 gce_util.go:58] Error deleting GCE PD volume e2e-gce-master-0-dynam-pvc-d002f85a-244e-11e6-b940-42010af00002: googleapi: Error 400: The disk resource 'e2e-gce-master-0-dynam-pvc-d002f85a-244e-11e6-b940-42010af00002' is already being used by 'e2e-gce-master-0-minion-group-vd4g', resourceInUseByAnotherResource

...

I0527 21:24:31.395811       7 gce_util.go:58] Error deleting GCE PD volume e2e-gce-master-0-dynam-pvc-d002f85a-244e-11e6-b940-42010af00002: googleapi: Error 400: The disk resource 'e2e-gce-master-0-dynam-pvc-d002f85a-244e-11e6-b940-42010af00002' is already being used by 'e2e-gce-master-0-minion-group-vd4g', resourceInUseByAnotherResource
```

**Comment by fejta** [comment]
@rootfs @piosz  please take a look at https://k8s-testgrid.appspot.com/k8s#gce-flaky&width=20

**Comment by rootfs** [comment]
thanks @fejta 

so at least one of the flake has a different error than "container not found"
In [this](https://00e9e64bac492f2110a8acec7a1c545e0e722fb58644dc4284-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/logs%2Fkubernetes-e2e-gce-flaky%2F18051%2Fbuild-log.txt?qk=AD5uMEuMyunMxmBtqicPK3kC7IKj2n64e39OaU15F87vWPYL53Ylv5B5SbXQTMChkJ2v_0aC49qMnkVR4osGkSUvmtomZlSY7cL0tvCsWWuErQkpm-shWlSq7oFvZaVn5J8aS8ZCciVXfJ9kl3IdIOERr5G30s9W63ZB8Ql4fvOPZvmlHIBb5C2tlj7nHzGMFN03S-ECE7WbmPrPl2hhje3HbeLJHOIYE9aBoZsyR6bVs4GheF3g7PyUlGfz8CiFuPb85nw9gQrTJdR11LZE3aKgT6xeRd7_vKTikrBpmfTEX3yeI3n8OVu29DIZfGiksxZVyu2t14GT-Yhca1OLTJFTVgaf3oKjSKXXRLaLGuywmsujgJ3jHJ46LdMomBJ3Q-5AGNRFHhnoHYWU0zrMa-SemnOYKkieWX99aAnt0t0vgwJ4X1i-Y15272gFFBFGOLFZaUjnwcbCV__gGzxjr79gXqr-b2A39DC8-IWjbwGSBtjnAHzON017sMqgQrmBJEL8KEN3ccAEiFtXJLNdct-RFGwF_uJ26u-nuOHh7fVQONegXoqSX1UoRZ2FGg83Dx9erdMGskUD4l2y6uGSHVt8j9giTM7mBTZ9FJwHfofvEIKx3VgQWq-CfSWZK2sTzRC_qNUEUVjCTdiPYyhFVjLmYOulkXnAJF6lzh3sr2C41_5K0_ewnhr9H4-0618iiEtUgyXuhIcrwZVMxq_cVyQZonf9pS4I8Q4NsKlXGGQjnEG6tON8cdPm45asTP8FY05nbt_F-TVxvBl73eGm1LFInL5oZmcnjd6e20ak56pxCL-rXeV3BvX0Vz5vpvmImn5Q3ChkLEj8q8atRYYGpEY9FlcqYLgRQxlqYxwCeaczznc_OTnDeigVyy1wyojZ12TOnq4yEThx) one, the error is 
```text
STEP: reading a file in the container
Jun  2 10:52:53.987: INFO: Running '/workspace/kubernetes/platforms/linux/amd64/kubectl exec --namespace=e2e-tests-pod-disks-rvzlu pd-test-cafe866e-28ea-11e6-a243-0242ac110005 -c=mycontainer3 -- cat /testpd1/tracker1'
Jun  2 10:52:54.182: INFO: error running kubectl exec to read file: exit status 1
stdout=rpc error: code = 2 desc = "oci runtime error: exec failed: lstat /proc/10006/ns/ipc: no such file or directory"
stderr=error: error executing remote command: error executing command in container: Error executing in Docker Container: 126
)
Jun  2 10:52:54.182: INFO: Error reading file: exit status 1
Jun  2 10:52:54.182: INFO: Unexpected error occurred: exit status 1
```

**Comment by pmorie** [comment]
^^ the above seems like a possible bug in exec

@ncdc

**Comment by ncdc** [comment]
@mrunalp ^

**Comment by mrunalp** [comment]
The error to me indicates that the original container is no longer around as exec can't find the ipc namespace fd. Are we sure the container that we are trying to join is still around?

**Comment by rootfs** [comment]
@ncdc my memory is rusty but did you have an idea to randomize the container id in this pd test?

**Comment by ncdc** [comment]
@rootfs see the info here: https://github.com/kubernetes/kubernetes/pull/26100#issuecomment-221103398

**Comment by matchstick** [comment]
Close we will track this with https://github.com/kubernetes/kubernetes/issues/26127
