### ISSUE TITLE
Fix performance problem of pod affinity

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#26144]
We can use this issue to discuss ideas.

Suggestions so far have been indexing and equivalence classes+caching (or both).

cc/ @wojtek-t @kevin-wangzefeng 

ref/ #25319 #25313

**Comment by wojtek-t** [comment]
Let me get back to it, after I'm done with my 1.3 work.

**Comment by wojtek-t** [comment]
I took a deeper look into it and here are some thoughs about it, that should significantly improve performance of pod-affinity features (hopefully it will be good enough to switch it on by default at this point).

1. We should limit the number of allowed "failure domain" values to some constant number. Currently, the default ones are: "host", "zone" and "region". We may consider adding 1 or 2 more, but we should limit the amount of those to say <=5.

2. For each of those, in scheduler we should keep an index:
("topology key", "its value") => (set of nodes in this group).
This should be easily maintainable.

3. Then the algorithm for computing (I will focus on priority function for now) should be:
```
// we are scheduling "pod".
for ep : all existing scheduled pods  {
  for term : affinity/antiaffinity of pod {
    if ep matches term {
      add weight of term to the whole group Index(term topology key, value(ep.Node))
    }
  }
  for term : affinity/antiaffinity of ep {
    // Do the same as above.
  }
}

for node : allNodes {
  for group: it belongs to in Index (there are only <=5 of them) {
    score[node] += (value of that group)
  }
}
```

This makes the algorithm work in O(#pods + #nodes + #affinity/antiaffinity terms).

The first loop can easily be parallelized by pods.

The complexity of it would be then exaclty the same as complexity of selector spreading priority function, which should make this usable and possible to switch it on by default.


For predicates, it should look roughly the same, but we should do some tricks in the framework to avoid computing it for every node. In other words, we should somehow precompute all the values at the beginning, and then the predicate function itself should just answer by taking the precomputed value for a given node.
