### ISSUE TITLE
kube-proxy  proxier.getServiceInfo(serviceName) is very slow

### ISSUE THREAD

**Issue by z32109571** [kubernetes/kubernetes#26148]
we have 700 services.But when created a servicce for a pod ,we found the create iptables  rule was very slow.The Pod usually was connected by services after 10 minutes。So I chage the code for logging the execution time。
the code at pkg/proxy/userspace/proxier.go
` for i := range services {
        service := &services[i]
        glog.V(1).Infof("muke-debug:get service: %+v", service)

```
    // if ClusterIP is "None" or empty, skip proxying
    if !api.IsServiceIPSet(service) {
        glog.V(3).Infof("Skipping service %s due to clusterIP = %q", types.NamespacedName{Namespace: service.Namespace, Name: service.Name}, service.Spec.ClusterIP)
        continue
    }   
    glog.V(1).Infof("muke-debug:IsServiceIPSet")

    for i := range service.Spec.Ports {
        servicePort := &service.Spec.Ports[i]
        glog.V(1).Infof("muke-debug:get port: %+v", servicePort)
        serviceName := proxy.ServicePortName{NamespacedName: types.NamespacedName{Namespace: service.Namespace, Name: service.Name}, Port: servicePort.Name}
        activeServices[serviceName] = true
        glog.V(1).Infof("muke-debug:start prase ip")
        serviceIP := net.ParseIP(service.Spec.ClusterIP)
        glog.V(1).Infof("muke-debug:finsih prase ip")
        info, exists := proxier.getServiceInfo(serviceName)
        glog.V(1).Infof("muke-debug:fisnish get info: %+v", info)`
```

I add some log.

the log as follow:
I0524 16:21:23.862748   21788 proxier.go:353] muke-debug:get service: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:muke-13-1941728 GenerateName: Namespace:muke-13 SelfLink:/api/v1/namespaces/muke-13/services/muke-13-1941728 UID:541fb924-20d4-11e6-aea8-0050569057b5 ResourceVersion:6321830 Generation:0 CreationTimestamp:2016-05-23 18:51:39 +0800 CST DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[version:V1 class_name:muke-13 user_id:1941728] Annotations:map[]} Spec:{Type:ClusterIP Ports:[{Name:port-1 Protocol:TCP Port:20958 TargetPort:{Kind:0 IntVal:80 StrVal:} NodePort:0} {Name:port-2 Protocol:TCP Port:17771 TargetPort:{Kind:0 IntVal:8000 StrVal:} NodePort:0}] Selector:map[user_id:1941728 version:V1 class_name:muke-13] ClusterIP:10.254.177.236 ExternalIPs:[] LoadBalancerIP: SessionAffinity:None} Status:{LoadBalancer:{Ingress:[]}}}
I0524 16:21:23.863486   21788 proxier.go:360] muke-debug:IsServiceIPSet
I0524 16:21:23.863532   21788 proxier.go:364] muke-debug:get port: &{Name:port-1 Protocol:TCP Port:20958 TargetPort:{Kind:0 IntVal:80 StrVal:} NodePort:0}
I0524 16:21:23.863595   21788 proxier.go:367] muke-debug:start prase ip
I0524 16:21:23.863609   21788 proxier.go:369] muke-debug:finsih prase ip
I0524 16:22:38.885857   21788 proxier.go:371] muke-debug:fisnish get info: <nil>
I0524 16:22:38.885998   21788 proxier.go:390] muke-debug:start port next
I0524 16:22:38.886020   21788 proxier.go:392] muke-debug:finish port next: 0
I0524 16:22:38.886055   21788 proxier.go:398] Adding new service "muke-13/muke-13-1941728:port-1" at 10.254.177.236:20958/TCP
I0524 16:22:39.134444   21788 proxier.go:364] muke-debug:get port: &{Name:port-2 Protocol:TCP Port:17771 TargetPort:{Kind:0 IntVal:8000 StrVal:} NodePort:0}
I0524 16:22:39.134765   21788 proxier.go:367] muke-debug:start prase ip
I0524 16:22:39.134783   21788 proxier.go:369] muke-debug:finsih prase ip
I0524 16:23:54.773997   21788 proxier.go:371] muke-debug:fisnish get info: <nil>
I0524 16:23:54.778447   21788 proxier.go:390] muke-debug:start port next
I0524 16:23:54.779744   21788 proxier.go:392] muke-debug:finish port next: 0
I0524 16:23:54.779898   21788 proxier.go:398] Adding new service "muke-13/muke-13-1941728:port-2" at 10.254.177.236:17771/TCP
I0524 16:23:54.964318   21788 proxier.go:353] muke-debug:get service: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:muke-15-2402720 GenerateName: Namespace:muke-15 SelfLink:/api/v1/namespaces/muke-15/services/muke-15-2402720 UID:e0a35239-0ad7-11e6-aea8-0050569057b5 ResourceVersion:4987913 Generation:0 CreationTimestamp:2016-04-25 19:21:38 +0800 CST DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[class_name:muke-15 user_id:2402720 version:V1] Annotations:map[]} Spec:{Type:ClusterIP Ports:[{Name:port-1 Protocol:TCP Port:24096 TargetPort:{Kind:0 IntVal:80 StrVal:} NodePort:0} {Name:port-2 Protocol:TCP Port:16521 TargetPort:{Kind:0 IntVal:8000 StrVal:} NodePort:0}] Selector:map[user_id:2402720 version:V1 class_name:muke-15] ClusterIP:10.254.159.63 ExternalIPs:[] LoadBalancerIP: SessionAffinity:None} Status:{LoadBalancer:{Ingress:[]}}}
I0524 16:23:54.965449   21788 proxier.go:360] muke-debug:IsServiceIPSet
I0524 16:23:54.965487   21788 proxier.go:364] muke-debug:get port: &{Name:port-1 Protocol:TCP Port:24096 TargetPort:{Kind:0 IntVal:80 StrVal:} NodePort:0}
I0524 16:23:54.970388   21788 proxier.go:367] muke-debug:start prase ip
I0524 16:23:54.970456   21788 proxier.go:369] muke-debug:finsih prase ip
I0524 16:25:09.250432   21788 proxier.go:371] muke-debug:fisnish get info: <nil>
I0524 16:25:09.250713   21788 proxier.go:390] muke-debug:start port next
I0524 16:25:09.250751   21788 proxier.go:392] muke-debug:finish port next: 0
I0524 16:25:09.250866   21788 proxier.go:398] Adding new service "muke-15/muke-15-2402720:port-1" at 10.254.159.63:24096/TCP

sometimes the proxier.getServiceInfo(serviceName) costs two minutes.I want to slove it .could somebody can give me  an optimization method

**Comment by AdoHe** [comment]
@z32109571 `getServiceInfo` just do a map get operation, it should be fast normally. But if the lock is already in use by other goroutine, for example the periodically sync loop may hold the lock and do some slow operations. You could add more logs to the `Sync` process.

**Comment by AdoHe** [comment]
@thockin ptal.

**Comment by z32109571** [comment]
@AdoHe i logs to the sync process.I found proxier.ensurePortals()  costs two minutes.could you  give me an optimization method

**Comment by thockin** [comment]
This is in the userspace proxier.  I might be talked into accepting patches against it, but I'm wary of investing much time into it, since the iptables proxier is pretty much better in every way.  Have you tried the iptables mode?

**Comment by thockin** [comment]
To be clear, my preference is that people use the iptables mode and that the userspace mode be considered deprecated.

**Comment by AdoHe** [comment]
@z32109571 this is possible, as `ensurePortals ()` will loop over the entire services map. As @thockin said, you should use iptables mode, instead of userspace mode. would you like to give a try?
