### ISSUE TITLE
Question: what's the functionality of SelfLink in ObjectMeta?

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#26158]
May I ask what's the functionality of SelfLink in ObjectMeta?

It seems that we don't use it for any feature whereas it may affect performance, since we don't set SelfLink at object creation time but generate it every time when server response, see [setSelfLink](https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L115).

@caesarxuchao @wojtek-t

**Comment by mqliang** [comment]
I am sorry that this is not a issue reporting. I am really curious about this.

**Comment by caesarxuchao** [comment]
My understanding is that SelfLink is used for a human or a script or a thirdparty client to quickly figure out where to find the object on the server.

Do you have access to Slack or StackOverflow? They are more proper places for this kind of questions and probably you can get an answer more quickly :)

**Comment by mikedanese** [comment]
This would be a good question for kubernetes-dev mailing list

**Comment by Aracki** [comment]
`selfLink is a URL representing this object. Populated by the system. Read-only.`
