### ISSUE TITLE
kube-dns pod is missing in GKE/GCI

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#26176]
A lot of tests have started failing in kubernetes-e2e-gke since build 7657
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke/7657/

One symptom is the missing KubeDNS service: `06:17:52 May 24 06:17:46.123: INFO: Missing KubeDNS in kubectl cluster-info`
I grepped "kube-dns" in the build.log, which dumped the list of pods multiple times due to test failures, and it was nowhere to be seen. 

The only change in the build is #26159

/cc @wojtek-t @andyzheng0831

**Comment by yujuhong** [comment]
Related failures: #26172, #26175, #26171, #26168, #26164

**Comment by andyzheng0831** [comment]
I find what is wrong. The PR #26159 is incorrect. Here is error log:

configure-helper.sh[1093]: /home/kubernetes/bin/configure-helper.sh: line 661: base_metrics_memory: command not found

I will fix it immediately

**Comment by yujuhong** [comment]
@andyzheng0831 Thanks! Assigning the issue to you for ease of tracking.

**Comment by andyzheng0831** [comment]
Root cause: The PR #26159 used metrics_memory="$(base_metrics_memory)", in which "(" and ")" should be "{" and "}". The script configure-helper.sh has a protective setting existing on error. So, it fails on setting up heapster and exist. The step for setting up remaining addon pods are skipped. This is intentionally, so that the breakage can be seen easily.

I am verifying my fix and then send out for review

**Comment by yujuhong** [comment]
@andyzheng0831 where was the error printed? I also suspected that the script errored out, but wasn't sure where to look (and I didn't spend more time digging). In the case where the setup fails, it'd be great if we can surface that, instead of continue running all the tests.

**Comment by andyzheng0831** [comment]
@yujuhong when you ssh into an instance, you should see broken motd information printed out by code block https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure.sh#l27-38. Use the "systemctl" commands there to see the log of gci cluster configuration.

**Comment by yujuhong** [comment]
@andyzheng0831 I was hoping the log would be collected and uploaded to the google storage bucket :\

**Comment by andyzheng0831** [comment]
The fix https://github.com/kubernetes/kubernetes/pull/26190 is out for review. I am officially on vacation these days, so please not be surprised if I don't respond promptly.

**Comment by andyzheng0831** [comment]
@yujuhong The motd is in the same way as ContainerVM. If the log collection is in the image, please log an issue for GCI team. If the log collection mechanism is out-of-box, please point its configuration to me, so that I can make it work with GCI.

**Comment by andyzheng0831** [comment]
@yujuhong There is an internal issue logged by GKE team for bridging the log collection. More specifically, that is for uploading logs collected by journald. The cluster initialization is written as systemd jobs, so the log is collected by journald.

**Comment by yujuhong** [comment]
@andyzheng0831 thanks for fixing it!

**Comment by yujuhong** [comment]
#26195 was merged and the build is green. Closing the issue.
