### ISSUE TITLE
jenkins getting 503 curling github

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#26186]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-kubemark-5-gce/4980/console
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-kubemark-500-gce/3361/console

cc @fejta @ixdy

**Comment by ixdy** [comment]
I'm not really sure what we can do about this. GitHub periodically goes down, and it's outside our control.

**Comment by fejta** [comment]
Change it so we don't download the upload-to-gcs.sh script every time. It could be in the image, for instance.

**Comment by fejta** [comment]
@ixdy does this retry?

**Comment by ixdy** [comment]
We pass `--retry 3` to curl, yes.

**Comment by fejta** [comment]
Please reactivate if you see this after June 15 when we moved to one executor per vm for cpu intensive loads
