### ISSUE TITLE
OS_DISTRIBUTION should be split into two vars

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/kubernetes#26183]
This came up while I was working on #25977, for which I am adding support to run clusters with the master on GCI and nodes on Debian. I find it difficult to do within current framework that uses a single env var, `OS_DISTRIBUTION`, to select the OS distro for both the master and nodes. Different distros tend to have different configs, ranging from instance metadata to initialization instructions, e.g., Debian uses salt but GCI uses systemd.

If we are going to support hybrid clusters for a while, I think we should have two vars as opposed to one, maybe something like `MASTER_OS_DISTRIBUTION` and `NODE_OS_DISTRIBUTION`, so that we could avoid hacks like [this](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L732).

**Comment by wonderfly** [comment]
cc/ @dchen1107 @roberthbailey @andyzheng0831

**Comment by roberthbailey** [comment]
That sounds reasonable to me.

**Comment by dchen1107** [comment]
hmm, we used to have that OS_DISTRIBUTION variable or something similar which I added to have a CoreOS & rkt demo by bringing up a hybrid cluster. I guess ppl deprecated that variable. SGTM

**Comment by gitfred** [comment]
Should it be closed?

**Comment by wonderfly** [comment]
I think it should be assigned rather than closed. :smile:

**Comment by gmarek** [comment]
This may be a cause of Node upgrade failures. We should investigate if that's the case, as it may be a blocker.

**Comment by wonderfly** [comment]
>  This may be a cause of Node upgrade failures. We should investigate if that's the case, as it may be a blocker.

If you read anything more than just the tile, you'll notice this is an unimplemented feature request.

**Comment by gmarek** [comment]
It's also a problem we stumbled upon today, as the "lack of this feature" broken an upgrade script. There's certainly a workaround, but it doesn't mean that this is not a root cause.

**Comment by maisem** [comment]
I can take this if no one is already working on it.

**Comment by davidopp** [comment]
IIUC @andyzheng0831 thinks he fixed the original problem without having to implement this (in #27824). Is that correct @andyzheng0831 ? If so, this issue is probably not needed to be fixed for 1.3.

**Comment by gmarek** [comment]
Yup, it seems it works, so it's not a blocker for v1.3. The "fix" is actually a hack, that shadows function definitions and makes the scripts volatile (@wojtekt already fixed the bug that was caused by a similar thing).

**Comment by andyzheng0831** [comment]
@davidopp @gmarek I agree that the current fix that checking OS_DISTRIBUTION together with the node image is more like a hack, which used in upgrade.sh and kube-up.sh. Splitting OS_DISTRIBUTION into two vars should be the real support for the hybrid cluster which has master and nodes on different distro. But it is quite tricky and risky. @maisem, you may need to think about variable possible cases and backwards compatibility when you work on it.
