### ISSUE TITLE
systemd based node images need to enable accounting for node e2e

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#26198]
The following PR is blocked by this problem (best I can tell)
https://github.com/kubernetes/kubernetes/pull/25982

Change needed:

```shell
$ mkdir -p /etc/systemd/system.conf.d
cat <<EOF >/etc/systemd/system.conf.d/kubernetes-accounting.conf
[Manager]
DefaultCPUAccounting=yes
DefaultMemoryAccounting=yes  
EOF
$ systemctl daemon-reload
```

To verify accounting is enabled, you should restart the kubelet and docker

```shell
$ cat /proc/$(pidof docker)/cgroup
11:pids:/
10:cpu,cpuacct:/system.slice/docker.service
9:cpuset:/
8:devices:/system.slice/docker.service
7:hugetlb:/
6:memory:/system.slice/docker.service
5:net_cls,net_prio:/
4:blkio:/system.slice/docker.service
3:perf_event:/
2:freezer:/
1:name=systemd:/system.slice/docker.service
```

Where the important thing to very is that the cpu,cpuacct and memory have an entry that is not `/` and matches where the unit is launched.

@pwittrock - as discussed in today's node sig.

@dchen1107 - I will send a PR to systemd node spec that ensures this is there too for future reference.

**Comment by pwittrock** [comment]
@derekwaynecarr would you update [setup_host.sh](https://github.com/kubernetes/kubernetes/blob/11105355fc19ee124013554398355eeac36356d2/test/e2e_node/environment/setup_host.sh) with the proposed change and make sure running it on a clean rhel instance will give the desired result?

**Comment by ingvagabund** [comment]
Testing on RHEL. The solution works only if I do the following:

```
mkdir -p /etc/systemd/system.conf.d
cat <<EOF >/etc/systemd/system.conf.d/kubernetes-accounting.conf
[Manager]
DefaultCPUAccounting=yes
DefaultMemoryAccounting=yes  
EOF
$ systemctl daemon-reexec
$ systemctl restart docker
```

**Comment by ingvagabund** [comment]
Tested on RHEL cluster (https://github.com/kubernetes/contrib/pull/1064). On nodes with kubelet/docker running on, cgroups are mounted as expected.

**Comment by derekwaynecarr** [comment]
Closing this issue as the setup_host.sh has been updated, and the other issues tracking core os specific problems with their image are tracking that problem.
