### ISSUE TITLE
kubenet:  failed to "TeardownNetwork"

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#26199]
Kubelet log is full of errors from tearing down network at HEAD. 

```
Failed killing the pod "e2e-test-nginx-job-96ib7": failed to "TeardownNetwork" for "e2e-test-nginx-job-96ib7_e2e-tests-kubectl-kuous" with TeardownNetworkError: "Failed to teardown network for pod \"963a42a1-21de-11e6-af3b-42010af00002\" using network plugins \"kubenet\": Error removing container from network: Failed to open /proc/0/ns/net: open /proc/0/ns/net: no such file or directory"
E0524 18:39:22.984933    3378 pod_workers.go:183] Error syncing pod d14ef1dc-21de-11e6-af3b-42010af00002, skipping: failed to "TeardownNetwork" for "pod-configmaps-d14e8c7a-21de-11e6-9f89-0242ac11000d_e2e-tests-configmap-razxa" with TeardownNetworkError: "Failed to teardown network for pod \"d14ef1dc-21de-11e6-af3b-42010af00002\" using network plugins \"kubenet\": Error removing container from network: Failed to open /proc/0/ns/net: open /proc/0/ns/net: no such file or directory"
```

From the log, a lot of them were the result of trying to access `/proc/0/ns/net`. Note that if you `docker inspect` an exited container, the returned PID will be 0. Therefore, my guess is that kubelet tried to tear down the network *after* the container has already exited. I didn't dig further.

@freehan could you take a look?

**Comment by freehan** [comment]
Is this a dup of #20379?
IIUC, we can add a safe guard to prevent TearDown to proceed, but it will not solve the root cause.

**Comment by yujuhong** [comment]
See also #26204

**Comment by yujuhong** [comment]
I don't think #26204 failed because of this.

@freehan this is probably caused by #26204, like you said. The fact that we are seeing more errors than before is likely due to #24964, which enforces graceless namespace deletions. Before that, most objects in the e2e were deleted gracefully and the race condition was rarely hit. Now most objects will hit this path. 

It'd still be a good idea to add a safeguard to check whether the pid is 0.
