### ISSUE TITLE
Stop checking in generated docs

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#26205]
Instead, have a presubmit test that verifies that the docs can be generated. This will reduce the number of conflicts & rebases, therefore increase speed through the queue.

Confirmed with @bgrant0607 that nothing depends on these docs at the moment.

@johndmulhausen fyi, some manual process might have to change once this is in.

**Comment by bgrant0607** [comment]
Yes, we want to generate the docs into kubernetes.github.io, anyway.

cc @kubernetes/docs

**Comment by johndmulhausen** [comment]
Excellent. One closer step to YAML generation, I hope. :)

**Comment by lavalamp** [comment]
@apelisse was interested in working on this.

**Comment by pwittrock** [comment]
@jfrazelle Want to get started on this?

**Comment by alexandercampbell** [comment]
@pwittrock is this still a goal of ours?

**Comment by apelisse** [comment]
I've seen a thread this week-end about that. I think docs have moved but we still need to generate them there.

**Comment by alexandercampbell** [comment]
@apelisse can this issue be closed then?

**Comment by apelisse** [comment]
related to #46348 ?

**Comment by bgrant0607** [comment]
/remove-lifecycle stale
/lifecycle frozen

There's still cruft in the docs directory.

**Comment by spiffxp** [comment]
/sig docs
/sig release
/remove-area test-infra
/area build-release
/area kubeadm
/area kubectl

All of the following dirs/files have the following content.  Do we need them?
>This file is autogenerated, but we've stopped checking such files into the repository to reduce the need for rebases. Please run hack/generate-docs.sh to populate this file.

- docs/admin: .md files for kube components and kubeadm commands
- man/man1: .1 files for same
- user-guide/kubectl: .md files for kubectl commands
- yaml/kubectl: .yaml files for kubectl commands

**Comment by spiffxp** [comment]
/help
Now that we have /good-first-issue, I think this _does_ meet the criteria for help wanted.  Probably need to talk to someone from sig-docs and figure out if/how these are used.

**Comment by spiffxp** [comment]
/remove-priority important-soon
/priority important-longterm
This hasn't been committed to for any release cycle in a while. I hope someone does commit to it, but I personally cannot, so I'm bumping down to the "hopefully next time" priority.

/kind cleanup
in addition to docs

This impacts merge velocity of any kubectl/kubeadm changes because the docs/OWNERS file is small.  We're going to work around by adding OWNERS files for the relevant sigs to the relevant dirs.  But if these files don't have to exist in the first place, that'd be even better.

**Comment by neolit123** [comment]
> We're going to work around by adding OWNERS files for the relevant sigs to the relevant dirs. But if these files don't have to exist in the first place, that'd be even better.

as discovered today this would not work as OWNERS in sub-folders do not solve the problem with the /docs/.generated_docs file which is in the parent folder.

i've been looking into a solution to remove the placeholders completely and make verify-docs only consist  of kube::util::gen-docs. this will:
- ensure that godoc errors and such still block presubmits
- the contributors are not blocked having to commit placeholder files

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/pull/70052

/lifecycle active

**Comment by neolit123** [comment]
/remove-lifecycle stale
/lifecycle active
as PR is still in flight.
