### ISSUE TITLE
Document rkt known issue for kubernetes 1.3 release

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#26201]
For each release, we test and validate docker as runtime, and document the known issue. rktnetes 1.0 is targeted for Kubernetes 1.3 release, let us also document the known issues related to rkt as the runtime.

**Comment by dchen1107** [comment]
cc/ @yifan-gu

**Comment by euank** [comment]
Taken from the [v1.1 milestone](https://github.com/kubernetes/kubernetes/milestones/rktnetes-v1.1):

The following features are not supported with rkt as the container runtime currently:

* Init containers
* NVIDIA GPU support via the `--experimental-nvidia-gpus` flag
* OOM Score adjust for QoS classes
* HostPID / HostIPC namespace
* `kubectl attach`
* Updating a container's image without restarting the entire pod

In addition, running alternate stage1's may have additional issues. Currently, networking does not work for the kvm flavor stage1, and logging might have further issues.

cc @sjpotter as well

**Comment by dchen1107** [comment]
cc/ @david-mcmahon and assign this to myself to make sure we include the known issues in release notes.

**Comment by david-mcmahon** [comment]
The "action required" label is a good way to get this pulled into the release notes and can be further expanded upon in the known issues section (immediately) post-release.

**Comment by pwittrock** [comment]
cc @kubernetes/docs

**Comment by pskrzyns** [comment]
At this moment logging works kvm stage1
As for networking it works but there are some issues connected to networking

**Comment by yifan-gu** [comment]
Ref kubernetes/kubernetes.github.io#699

> Logging will work for kvm stage1 with rkt 1.9
As for networking it works but there are some issues connected to networking

What's the details of the issue actually?

**Comment by yifan-gu** [comment]
Should be fixed by kubernetes/kubernetes.github.io#741

**Comment by pskrzyns** [comment]
@yifan-gu:
problem with creating kube-dns (should be solved by https://github.com/coreos/rkt/pull/2769)
there is not implemented port forwarding
and there is problem with etc/hosts so "DNS should provide DNS" tests are failing
kubenet won't work 
additionally i was testing it using flannel only, so i don't know how it looks with other configuration

**Comment by yifan-gu** [comment]
@pskrzyns Thanks, I will do an update on the known issues today as well.

**Comment by goltermann** [comment]
This is an issue marked v1.3 and kind/documentation.  Can you get it fixed up this week?

**Comment by yifan-gu** [comment]
I think this is fixed. Closing.
