### ISSUE TITLE
Node e2e remote copy kernel logs from runs

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#26218]
Node e2e tests will only copy the kubelet.log, kube-apiserver.log, etcd.log, and junit.xml files as test artifacts. - to be done in #26101  Copy additional useful logs, such as kernel logs and even container logs.

**Comment by yujuhong** [comment]
+1 for container runtime logs (e.g., docker.log)

**Comment by vishh** [comment]
This is done. Node e2e framework now exposes kernel and docker logs.
