### ISSUE TITLE
Node e2e dump namespace debug info on failed tests

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#26219]
When a test expectation fails, we should dump as much contextual debug information as possible so we don't have to comb through logs to figure out the context.  It would be helpful to use tools such as [DumpAllNamespaceInfo](https://github.com/kubernetes/kubernetes/blob/316103875e91511268bd0c2b4221a5a982275e5f/test/e2e/framework/util.go#L2250) to display the test state.

**Comment by dchen1107** [comment]
cc/ @vishh and @timstclair

**Comment by vishh** [comment]
@pwittrock Is this as simple as setting `--dump-logs-on-failure=true` as part of the e2e?

**Comment by pwittrock** [comment]
:P  It might be, I haven't looked into it.  I ran into some issues when trying to parse the framework flags, which may prevent using that feature.
