### ISSUE TITLE
Deploy kubedns instead of kube2sky+skydns 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#26239]
We recently moved to gci and using cloud-init instead of salt. This reverted our recent kube-dns rewrite by continuing to deploy the skydns rc, as is evident from this run: http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/17559/consoleFull
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce/17559/

```
19:22:34 May 24 19:22:29.198: INFO: kube-dns-v11-m8wnv started at 2016-05-24T19:15:18-07:00 (0+4 container statuses recorded)
19:22:34 May 24 19:22:29.198: INFO: 	Container etcd ready: true, restart count 0
19:22:34 May 24 19:22:29.198: INFO: 	Container healthz ready: true, restart count 0
19:22:34 May 24 19:22:29.198: INFO: 	Container kube2sky ready: true, restart count 0
19:22:34 May 24 19:22:29.198: INFO: 	Container skydns ready: true, restart count 0
```

@wonderfly assuming https://github.com/kubernetes/kubernetes/pull/26197 flipped the switch

As a side note, we should surface cluster addon version somewhere in e2e-up output, I had to find a failed run and lookup the dumped pods to prove this point.

**Comment by roberthbailey** [comment]
Do we have any tests that differentiate between the two dns implementations?

**Comment by bprashanth** [comment]
I don't think so, the rewrite was supposed to be compatible (though https://github.com/kubernetes/kubernetes/issues/26116 indicates some differences, we apparently don't capture it in a test). Some of the newer ubernetes features aren't present in the old dns, but I don't think we're e2e testing ubernetes yet.

**Comment by bprashanth** [comment]
As Robbie mentioned elsewhere, we've probably also skewed GKE and OSS since the new dns went in for pretty much the same reason

**Comment by girishkalele** [comment]
Working on this - switching cluster deployment scripts to use kubedns.

**Comment by girishkalele** [comment]
Related discussion - https://github.com/kubernetes/kubernetes/pull/26197

**Comment by girishkalele** [comment]
A lot of flakes were due to the failure to startup kube-dns - #26195 fixed that issue, but we still have the older 4 container skydns pod running when doing GCE kube-up.

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/pull/26335
