### ISSUE TITLE
Create fuzz testing for kubectl apply

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#26234]
We discover bugs in kubectl apply on a field-by-field basis: #26229, #23551.

We don't have rigorous testing of the diff and patch code, nor of the API spec itself. There are many known problems, such as lack of ability to distinguish unset fields from Go default values for non-pointer primitive fields.

We should develop a random fuzz tester for kubectl apply.

cc @ghodss @kubernetes/kubectl

**Comment by dshulyak** [comment]
I would like to help with this bug.

**Comment by AdoHe** [comment]
@dshulyak that would be great. Thanks :)

**Comment by dshulyak** [comment]
@AdoHe @bgrant0607 Am i right that the goal is to validate k8s objects using schema after applying ThreeWayMergePatch?
If so fuzz tester should be able to:
1. Generate k8s object (using existing helper)
2. Generate 2nd version of this object
3. Create and apply three way merge patch
4. Validate resulted object using schema, plus additional tests

**Comment by bgrant0607** [comment]
@dshulyak I think the main challenge is how to determine correctness of the result. That needs more thought before this will be worth doing.

**Comment by bgrant0607** [comment]
cc @apelisse

**Comment by apelisse** [comment]
> We don't have rigorous testing of the diff and patch code, nor of the API spec itself.
> ...
> We should develop a random fuzz tester for kubectl apply.

I don't necessarily agree that the first statement should lead to the second. I'll keep in mind that we want solid unit-testing for diff/patch. I think "determining correctness" would indeed be an unnecessary challenge.

**Comment by sftim** [comment]
We have server-side apply now. Is this issue description still right?

**Comment by apelisse** [comment]
It's hard to tell for sure. We haven't really created fuzzing, I think we have a much stronger test suite now. We're also not bug-free (obviously), but I think this issue is somewhat irrelevant, let's close it.
/close
