### ISSUE TITLE
Master PD file location inconsistent between Debian & GCI

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#26235]
The location of apiserver auth certs and keys and the kube-apiserver SSH keys are inconsistent between Debian and GCI.  This means that master upgrades from Debian to GCI are broken.

In Debian, Salt puts these files in `master-pd/srv/kubernetes` (via `/srv/salt-overlay/salt/kube-apiserver/basic_auth.csv` and `/srv/kubernetes/basic_auth.csv`, see [configure-vm.sh](https://github.com/kubernetes/kubernetes/blob/1ef19062096c4fcf8ddeaf3a46731d9f262a0c04/cluster/gce/configure-vm.sh) and [init.sls](https://github.com/kubernetes/kubernetes/blob/1ef19062096c4fcf8ddeaf3a46731d9f262a0c04/cluster/saltbase/salt/kube-apiserver/init.sls)), whereas GCI expects it in `master-pd/etc/srv/kubernetes` (see [configure-helper.sh](https://github.com/kubernetes/kubernetes/blob/1ef19062096c4fcf8ddeaf3a46731d9f262a0c04/cluster/gce/gci/configure-helper.sh), originally introduced in https://github.com/kubernetes/kubernetes/pull/20463).

cc @mikedanese @adityakali @andyzheng0831

**Comment by ihmccreery** [comment]
It terrifies me that this is such a strong coupling between these two scripts, which are approximate—but not exact—duplicates of each other.  @roberthbailey, I'm worried there might be other pernicious problems here; should we prioritize a refactor that DRYs the code to reduce risk for v1.2-v1.3 release?

**Comment by andyzheng0831** [comment]
This is intentionally. The dirs in containervm may not be in GCI. You
cannot expect everything is exactly the same in both images. The only
concern is that /etc in GCI is stateless. So we may put master certs in
/var.

**Comment by ihmccreery** [comment]
> The dirs in containervm may not be in GCI.

For master upgrades to work properly, we should expect that data stored on the PD will persist.  Without that assumption, how can we expect master upgrades to work at all?

**Comment by andyzheng0831** [comment]
The auth file path in containervm contains"salt", which does not make sense
in GCI, as GCI does not use salt

**Comment by adityakali** [comment]
> this is such a strong coupling between these two scripts
Its not really a strong coupling. The setup on each distro is expected to be different. Hence there are so many environment vars which allows decoupling. 
I expect this particular case of switching underlying OS_DISTRO for the same master to be very uncommon (once in a lifetime kind of thing?).

**Comment by ihmccreery** [comment]
> Its not really a strong coupling.

We expect persistent data on the PD to be available across upgrades (otherwise, why would we store it on the PD?), so it should be in the same place.  I don't care if it's mounted on the OS in a different place.

> The auth file path in containervm contains"salt", which does not make sense
in GCI, as GCI does not use salt

On a CVM master, I see no Salt in either `/srv/kubernetes` or `/srv/sshproxy`.  Even if there was extra stuff there, why would it matter?

I'd hear an alternate proposal for making upgrades work from CVM to GCI that doesn't involve using the old files, but we do need upgrades to work.
