### ISSUE TITLE
Volume plugins cleanup

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#26230]
Filing this for future work.

pkg/volume/plugins.go defines a set of `*VolumePlugin` types that all implement small interfaces like `NewDeleter()`.  This started with `NewMounter()` and `NewUnmounter()` which plugins implement with different structs and are passed around.  It got cargo-culted into a half dozen other such interfaces that do not have the same restrictions, and generally are called like:

```
r := plugin.NewRecycler(name, spec)
r.Recycle()
```

Most of these interfaces could be reduced to:

```
plugin.Recycle(name, spec)
```

Relatively easy one for someone to jump on, but NOT going into the 1.3 milestone.

Additionally, `NewMounter()` and `NewUnmounter()` could be extracted to a `MountableVolumePlugin` type and `VolumeHost` could go through a similar fragmenting.

@jingxu97

**Comment by thockin** [comment]
The linked PR was closed for lack of time on the contributor's part, but it's almost done.  Someone who has an hour or two of time could easily finish this off.

**Comment by kpgriffith** [comment]
@thockin I'm new to k8s and looking for something to get me started.  Does this fit?

**Comment by thockin** [comment]
I think this is still open.

**Comment by kpgriffith** [comment]
@thockin Okay.  I'd like to pick it up if no one else is working on it.  You want the same approach from the closed PR?

**Comment by thockin** [comment]
#28432 seems like a good starting place.  Please make sure to comprehend it and figure out what makes the most sense :)
