### ISSUE TITLE
mismatch between user-bound claim and pv

### ISSUE THREAD

**Issue by jeffvance** [kubernetes/kubernetes#26233]
k8s version:
```
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.4.450+e1dcf2066861a0-dirty", GitCommit:"e1dcf2066861a0d2c7301a798bf66246c164c158", GitTreeState:"dirty", BuildDate:"2016-05-24T22:37:08Z", GoVersion:"go1.6.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.4.450+e1dcf2066861a0-dirty", GitCommit:"e1dcf2066861a0d2c7301a798bf66246c164c158", GitTreeState:"dirty", BuildDate:"2016-05-24T22:37:08Z", GoVersion:"go1.6.1", Compiler:"gc", Platform:"linux/amd64"}
```
It is fairly simple to reproduce the situation of 2 pvs and 2 claims where a "user-bound" (pre-bound) claim is not bound to its target pv due to the other claim binding first.  Eg:
```
#create pv1,pv2,claim1,claim2
#where claim2 is pre-bound to pv2 using claim.Spec.VolumeName

# kc get pv
NAME      CAPACITY   ACCESSMODES   STATUS      CLAIM                REASON    AGE
nfs-pv1   1Gi        RWO           Available                                  19m
nfs-pv2   1Gi        RWO           Bound       default/nfs-claim1             19m
# kc get pvc
NAME         STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
nfs-claim1   Bound     nfs-pv2   0                        19m
nfs-claim2   Pending   nfs-pv2   0                        19m
```
pv1 is Available since claim2 is pre-bound to pv2, but pv2 was _claimed_ by claim1 first.
**Note:** pre-binding a pv (via claimRef) does not exhibit the same result. In my testing using several pvs, including 1 pre-bound pv, and several claims, all resources were bound.

I created this issue because it seems reasonable, when "looking" at several PVs and claims, to expect that pre-bound resources will be matched whenever possible. Is it possible to boost the sync frequency of pre-bound resources? Or, perhaps introduce the concept of a resource priority, where sync's of higher priority claims/pvs would be attempted more frequently?

**Comment by jeffvance** [comment]
@pmorie @childsb @jsafrane: PTAL. Interested in your thoughts. Please add any labels you feel are appropriate.

**Comment by jsafrane** [comment]
This is inherently time-sensitive and racy. If a PV is created with empty claimref, this PV is available to *any* claim that matches. This PV is not reserved to any claim. If you create the PV first, how is the controller supposed to know that there will be a claim pre-bound to it in near future? And if you can create the claim first, why can't you create the PV pre-bound to the claim if you want it to have precedence before all other matching claims?

**Comment by jeffvance** [comment]
@jsafrane Fully agree with your comment above. However, why is the behavior asymmetric? If the pv is pre-bound it always binds to the target claim, but if the claim is pre-bound it is a race with unpredictible results.

**Comment by jsafrane** [comment]
@jeffvance, you're right, pre-bound PVs are always matched first, as side-effect of dynamic provisioning which uses the same mechanism to bind provisioned volumes to claims.

Question is if benefit of more predictable binding excuses costs of effort required to rewrite the matching... We should eventually bind volumes in `syncVolume` (i.e., when a claim is created first and a volume after that) and this should be natural extension.
