### ISSUE TITLE
Too many open files error in small cluster

### ISSUE THREAD

**Issue by bobintornado** [kubernetes/kubernetes#26246]
I am running a very small cluster (4 VMs) with CoreOS, but keep hitting the following "Too many open files" error while trying to do some very basic deployment. 

> Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container f0a2b72747555228a89592ae28436f521ba389623f53ef5f2103f4aea3f7ac4e: [8] System error: too many open files in system\n"

I wonder if this is the same issue as https://github.com/kubernetes/kubernetes/issues/6351, but I am running a very small cluster and very few deployments (like 10 pods max).

So I wonder if this is a etcd or kubernetes leaking issues, as I suspect some files are not closed.

Is this only me or has the rest counter similar issues?

**Comment by dims** [comment]
@bobintornado Did you already rule out docker itself? (Check docker logs?)

**Comment by bobintornado** [comment]
@dims I didn't see the connection between a syncing error and docker itself, would you mind elaborating a bit?

**Comment by bobintornado** [comment]
@dims and majority of the container i am running are pretty standard stuff, like postgresql, nginx, cassandra, and redis, and I am using official images from docker hub without modifications. So I think probably docker isn't the issue?

**Comment by bobintornado** [comment]
Update: I upgrade my nodes from 1 core 1.75 GB RAM into 2 core 7 GB RAM backed with SSD. Maybe this is because my nodes are too weak. Will keep updating.

**Comment by bobintornado** [comment]
Issue magically disappeared after using much more powerful machines. (2 core 7 GB with better throughput and IO, namely Azure Standard D2_v2, was Azure A1 Basic). 

Could close the issue.

**Comment by chrislovecnm** [comment]
Sounds like kernel config issue ... did you break down the old cluster?

**Comment by bobintornado** [comment]
@chrislovecnm yeah indeed it sounds like a kernel config issue. 

Yeah I did break down the old cluster so I didn't know what really happened there anymore.

The new cluster seems to run pretty smoothly until now. The only issue is the pod often stuck at Pending or Terminating status, the rest is fine now. :)

**Comment by chrislovecnm** [comment]
@bobintornado can we please close?

**Comment by bobintornado** [comment]
@chrislovecnm yes please close this issue.

**Comment by chrislovecnm** [comment]
You have the power for that not I ;)
