### ISSUE TITLE
Persistent Volume Controller should use Shared Informer

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#26247]
The attach detach controller (PR https://github.com/kubernetes/kubernetes/pull/25457) introduces shared PV/PVC informers that all controllers can share. After it goes in, we should refactor `pkg/controller/volume/persistentvolume/controller_base.go` to use them.

**Comment by wongma7** [comment]
@jsafrane okay if I try to work on this? Looks like there's lots of examples..

**Comment by jsafrane** [comment]
@wongma7, sure, fix this issue as you see fit. And thanks in advance :-).

**Comment by kargakis** [comment]
@wongma7 @jsafrane is this fixed?

**Comment by jsafrane** [comment]
#38615 is a prerequisite, we will resume our work when it's merged

**Comment by wongma7** [comment]
@ncdc I see you've got custom resync periods in https://github.com/kubernetes/kubernetes/pull/40759 and are working on moving a lot of controllers over to shared informers, is the PV controller also one you plan to move?

**Comment by ncdc** [comment]
@wongma7 yes, I am planning on moving all of them

**Comment by ncdc** [comment]
I'm tracking the overall list here https://trello.com/c/kpiFmic9/121-use-generated-shared-informers-listers-everywhere-possible

**Comment by ncdc** [comment]
If you have bandwidth, feel free to work on some of them. Just let me know so we don't both do the same thing!

**Comment by wongma7** [comment]
@ncdc okay, I'm going to start working on converting the PV controller. (we have a trello card too https://trello.com/c/K4pGlGPV/391-persistent-volume-controller-should-use-shared-informer ;) ).

**Comment by ncdc** [comment]
@wongma7 you'll need to base it off of #40759

**Comment by liggitt** [comment]
it appears this was already done - https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/core.go#L135-L153

**Comment by wongma7** [comment]
yes, we can close this https://github.com/kubernetes/kubernetes/pull/41273

**Comment by liggitt** [comment]
Great. Opened related issue around the excessively short PV/PVC resync period - https://github.com/kubernetes/kubernetes/issues/48941
