### ISSUE TITLE
Duplicate UDP packets between pods

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#26255]
We're using Kubernetes 1.2.1 on AWS.

We've been experiencing duplicate UDP packets. It happens only on a very specific setup:
1. A pod (pod1) that exposes some UDP port
2. A service that directs traffic to that pod
3. Another pod (pod2) to send UDP packets (we used netcat for this)
4. The pods must be running on the **same** node

When pod2 sends a UDP message to pod1 via the **service** pod1 shows it received the message twice.
When we go from pod2 directly to the ip of pod1 the message is received once without duplications..
Also, when sending UDP messages from a pod that is running on another machine we don't get the duplication both to the service and pod ip.

We created a repository do make the problem re-produceable here: https://github.com/nanit/udp-server. It contains:
1. A kube directory with both the deployment and service definitions.
2. An app directory with the Dockerfile we used to run the udp listener (using tcpdump).

We used netcat in order to send UDP packets to the listener:
`echo "some message" | nc -u udp-listen 8088`

When we replaced udp-listen (the service name)  with the explicit ip of the pod we didn't get the duplication.
Also, when sending UDP messages from a pod running on another node we didn't get the duplications.

I'll be happy to provide any further info if needed.

**Comment by AdoHe** [comment]
@thockin ptal.

**Comment by thockin** [comment]
Dup of #25793

**Comment by girishkalele** [comment]
@erez-rabih 

Referring to notes in #25793, switching the bridge mode from bridge-promiscuous to hairpin-veth will prevent the duplication but introduces the potential for the kernel refcount issue to show up. You can try  with hairpin-veth mode and see if your kernel is stable.

**Comment by erez-rabih** [comment]
@girishkalele I am not fully familiar with the bridging mode you're talking about.
1. How can I change the bridge mode?
2. Is "kernel" referring to linux kernel or kubernetes kernel?
3. If they say it introduces other bugs why should I go this way?

**Comment by girishkalele** [comment]
@erez-rabih 

1. It is a configuration option in cluster/gce/config-default.sh (or its equivalent for AWS).

`# How should the kubelet configure hairpin mode?`
`HAIRPIN_MODE="${HAIRPIN_MODE:-promiscuous-bridge}" # promiscuous-bridge, hairpin-veth, none`

2. Linux kernel

3. To confirm that hairpin-veth mode fixes your duplicate packets issue, which would mean its the same issue as reported in #25793. I wouldn't recommend running this way for production, only for testing.

**Comment by erez-rabih** [comment]
@girishkalele I am running on AWS, does it have an equivalent settings somewhere?
