### ISSUE TITLE
integration flake: PersistentVolumeController could not update claim "default/fake-pvc"

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#26256]
PersistentVolume integration tests fail sometimes: 
https://console.cltoud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26105/kubernetes-pull-test-unit-integration/27563/

```
E0523 22:12:02.268570   29064 controller_base.go:259] PersistentVolumeController could not update claim "default/fake-pvc": persistentvolumeclaims "fake-pvc" not found
panic: test timed out after 10m0s
```

There are some interesting reports in the log like:

```
E0523 22:06:52.344753   28799 controller_base.go:259] PersistentVolumeController could not update claim "default/fake-pvc-59": Put http://127.0.0.1:41421/api/v1/namespaces/default/persistentvolumeclaims/fake-pvc-59/status: dial tcp 127.0.0.1:41421: getsockopt: connection refused
```

Thans @quinton-hoole  for report.

**Comment by jsafrane** [comment]
It turns out that volume integration tests have no logs at all, `err` was not checked and I don't really know what's going on there. #26262 adds error checks to help me find out what's wrong there. Still, I suspect there are some troubles with etcd, not related to the test itself.

**Comment by jsafrane** [comment]
This flake affects also TestPersistentVolumeMultiPVs:

```
goroutine 13886 [chan receive, 7 minutes]:
k8s.io/kubernetes/test/integration.waitForPersistentVolumePhase(0x7fd74c3ba278, 0xc82c328630, 0x23fe688, 0x5)
    /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:281 +0x6b
k8s.io/kubernetes/test/integration.TestPersistentVolumeMultiPVs(0xc8290fd680)
    /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:184 +0x89f
testing.tRunner(0xc8290fd680, 0x3568318)
    /usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
    /usr/local/go/src/testing/testing.go:582 +0x892
```

**Comment by jsafrane** [comment]
Extended logging got merged just now, please post links to logs when it breaks again!

**Comment by matchstick** [comment]
Marking as P1 as per @saad-ali  @jsafrane

**Comment by jsafrane** [comment]
I have no real usable logs, but I think it could be fixed by #26629, it hasn't flaked since it was merged. And I have #26894 (in merge queue) to further stabilize the tests.

**Comment by matchstick** [comment]
Not blocking this on 1.3.

**Comment by jsafrane** [comment]
It hasn't flaked for almost a month, can we close this?

**Comment by childsb** [comment]
Closing this issue since previous fixes made the flake go away.
