### ISSUE TITLE
Kubelet failed to detect running docker process when name is not `docker`

### ISSUE THREAD

**Issue by Gnouc** [kubernetes/kubernetes#26259]
I used [this instructions](https://docs.openshift.org/latest/getting_started/administrators.html) to install Openshift Origin v3, along with its embed Kubernetes. All thing is fine until I get the error:

```
E0525 16:17:20.437528    1899 container_manager_linux.go:267] failed to detect process id for "docker" - failed to find pid of "docker": exit status 1
```

It's weird, I'm sure that docker was started:

```
$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-05-25 15:26:01 ICT; 56min ago
     Docs: http://docs.docker.com
 Main PID: 3291 (sh)
   CGroup: /system.slice/docker.service
           ├─3291 /bin/sh -c /usr/bin/docker-current daemon $OPTIONS            $DOCKER_STORAGE_OPTIONS            $DOCKER_NETWORK_OPTIONS            $ADD_...
           ├─3292 /usr/bin/docker-current daemon --selinux-enabled
           └─3293 /usr/bin/forward-journald -tag docker

$ docker search lamdt
INDEX       NAME                              DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
docker.io   docker.io/lamdt/salt-master-ssh   Based on Ubuntu 12.04. That container incl...   0
```

I go through `kubelet` and seems to find the culprit, in [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go#L57):

```
dockerProcessName = "docker"
```

`dockerProcessName` was hard-coded to `docker`, while in my system, the `docker` process named `docker-current`:

```
$ ps aux | grep [d]ocker
root      3291  0.0  0.0 115244  1432 ?        Ss   15:25   0:00 /bin/sh -c /usr/bin/docker-current daemon $OPTIONS            $DOCKER_STORAGE_OPTIONS            $DOCKER_NETWORK_OPTIONS            $ADD_REGISTRY            $BLOCK_REGISTRY            $INSECURE_REGISTRY            2>&1 | /usr/bin/forward-journald -tag docker
root      3292  0.4  0.3 619668 29684 ?        Sl   15:25   0:15 /usr/bin/docker-current daemon --selinux-enabled
root      3293  0.0  0.0 101728  1904 ?        Sl   15:25   0:00 /usr/bin/forward-journald -tag docker
```

`/usr/bin/docker` is actually a shell script, which will call `docker-current`:

```
$ command -v docker
/usr/bin/docker
$ file "$(command -v docker)"
/usr/bin/docker: POSIX shell script, ASCII text executable
```

My OS is:

```
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

I'm not sure it should be considered an OS bug, or `kubelet` bug itself?

**Comment by dims** [comment]
@Gnouc It's probably best to open a bug against OpenShift Origin and close this one:
https://github.com/openshift/origin/issues

**Comment by Gnouc** [comment]
@dims why Openshift Origin?

If I ran kubernetes alone, the same issue occur.

I think we should state this an OS bug, or make `kubelet` handle this situation

**Comment by dims** [comment]
@smarterclayton - what's the best venue for this bug?

**Comment by smarterclayton** [comment]
This is a Kubernetes bug - the line referenced by @gnouc points out that the kubelet assumes the docker binary is called "docker" which is not necessarily the case.

**Comment by smarterclayton** [comment]
I think at a minimum that should not be a constant, but be defaulted.  The workaround for now is to hardlink the `docker-current` process you have to `docker`.

**Comment by dims** [comment]
@smarterclayton thanks, sounds good. I have heard many times that there are patches/hardening to docker and kubernetes and was not sure.

**Comment by Gnouc** [comment]
@smarterclayton If you don't mind, I can push the fix for this issue.

**Comment by acavas1** [comment]
@smarterclayton I'm having the same issue. If you don't mind explaining how to hardlink docker-current process to docker. Thanks

**Comment by TomasTomecek** [comment]
`ln docker-current docker`

**Comment by acavas1** [comment]
thanks

**Comment by acavas1** [comment]
I couldn't do a hard link in a bin directory as there already is a file named docker, so i moved docker-current, renamed it to docker and edited the  /usr/lib/systemd/system/docker.service file with the new location of the renamed docker-current file. 
Now I don't get the error, but get � in browser when I try to access the console.

**Comment by acavas1** [comment]
My didn't access it with https.

**Comment by smarterclayton** [comment]
@derekwaynecarr system container Cgrouping is broken with the latest docker packages due to the process name changing.

**Comment by dims** [comment]
@acavas1 : can you try setting the pidfile parameter for your docker daemon? that may be an easier work around?

--pidfile=/var/run/docker.pid

Thanks,
Dims

**Comment by Gnouc** [comment]
@acavas1 Change the docker script to use `#!/bin/bash`, then replace the `exec` line with `exec -a docker`.

**Comment by derekwaynecarr** [comment]
This has been fixed in Kubernetes here:
https://github.com/kubernetes/kubernetes/pull/25907

**Comment by derekwaynecarr** [comment]
The origin cherry pick is here: https://github.com/openshift/origin/pull/9060

**Comment by priyanka5** [comment]
@TomasTomecek @smarterclayton : i am also facing the same issue in origin 1.2.0 with quick installation method. Can anybody tell me is this resolved and whats docker-current. how to use the workaround.

**Comment by smarterclayton** [comment]
Hi @priyanka5, let's move this discussion to the origin repository (issue openshift/origin#9060)

**Comment by lvthillo** [comment]
@dims I tried your solution on origin 1.2.0 (--pidfile in /etc/sysconfig/docker and restart). The logs aren't showen anymore. But I don't have enough knowledge about this issue. Hope it's a right solution.

**Comment by lvthillo** [comment]
@Gnouc How does your /usr/bin/docker looks like? 
Still same issue on ```
oc v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
```

**Comment by Gnouc** [comment]
@lvthillo Here is it:
```
#!/bin/sh
. /etc/sysconfig/docker
[ -e "${DOCKERBINARY}" ] || DOCKERBINARY=/usr/bin/docker-current
if [ ! -f /usr/bin/docker-current ]; then
    DOCKERBINARY=/usr/bin/docker-latest
fi
if [[ ${DOCKERBINARY} != "/usr/bin/docker-current" && ${DOCKERBINARY} != /usr/bin/docker-latest ]]; then
    echo "DOCKERBINARY has been set to an invalid value:" $DOCKERBINARY
    echo ""
    echo "Please set DOCKERBINARY to /usr/bin/docker-current or /usr/bin/docker-latest
by editing /etc/sysconfig/docker"
else
    exec ${DOCKERBINARY} "$@"
```

Change the shebang to `#!/bin/bash`, then `exec ${DOCKERBINARY} "$@"` to `exec -a docker ${DOCKERBINARY} "$@"`

**Comment by lvthillo** [comment]
@Gnouc Thanks for the fast reply.
Now my /usr/bin/docker looks like this:
```
#!/bin/bash
. /etc/sysconfig/docker
[ -e "${DOCKERBINARY}" ] || DOCKERBINARY=/usr/bin/docker-current
if [ ! -f /usr/bin/docker-current ]; then
    DOCKERBINARY=/usr/bin/docker-latest
fi
if [[ ${DOCKERBINARY} != "/usr/bin/docker-current" && ${DOCKERBINARY} != /usr/bin/docker-latest ]]; then
    echo "DOCKERBINARY has been set to an invalid value:" $DOCKERBINARY
    echo ""
    echo "Please set DOCKERBINARY to /usr/bin/docker-current or /usr/bin/docker-latest
by editing /etc/sysconfig/docker"
else
    exec -a docker ${DOCKERBINARY} "$@"
fi
```

I restarted everything:
```
sudo service docker restart
sudo service origin-node restart
```

in logs:
` E0629 10:42:53.022798    9519 container_manager_linux.go:267] failed to detect process id for "docker" - failed to find pid of "docker": exit status 1`

**Comment by lvthillo** [comment]
What I don't really understand is the fact that:
```
pidof docker returns nothing
pidof docker-current returns pid
cat /var/run/docker.pid returns same pid as docker-current.
```

**Comment by khanamura** [comment]
"/usr/bin/docker" is not used from the systemd.
See /usr/lib/systemd/system/docker.service

**Comment by lvthillo** [comment]
@khanamura 
What should I edit?
```
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=network.target
Wants=docker-storage-setup.service

[Service]
Type=notify
NotifyAccess=all
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-storage
EnvironmentFile=-/etc/sysconfig/docker-network
Environment=GOTRACEBACK=crash
ExecStart=/bin/sh -c '/usr/bin/docker-current daemon \
          --exec-opt native.cgroupdriver=systemd \
          $OPTIONS \
          $DOCKER_STORAGE_OPTIONS \
          $DOCKER_NETWORK_OPTIONS \
          $ADD_REGISTRY \
          $BLOCK_REGISTRY \
          $INSECURE_REGISTRY \
          2>&1 | /usr/bin/forward-journald -tag docker'
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TimeoutStartSec=0
MountFlags=slave
Restart=on-abnormal
StandardOutput=null
StandardError=null

[Install]
WantedBy=multi-user.target
```

**Comment by Gnouc** [comment]
@lvthillo Change `sh -c '/usr/bin/docker-current ...` to `sh -c 'exec -a /usr/bin/docker-current ...`

**Comment by khanamura** [comment]
@lvthillo
Change sh -c '/usr/bin/docker-current ... to sh -c 'exec -a **docker** /usr/bin/docker-current ...

and then

# systemctl daemon-reload
# systemctl restart docker.service
# systemctl restart origin-node.service

**Comment by lvthillo** [comment]
@khanamura @Gnouc Thanks, it works

**Comment by mootezbessifi** [comment]
@khanamura 
Hi sir,
i tried to execute the some steps above. exactly the same by some time it cgoup changes to docker and some time still docker-current.
i am fed up with this issue that takes from me too much time.
please help
