### ISSUE TITLE
Cannot build master code by running release.sh

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#26265]
When I git clone the master code and run build/release.sh, I get an error `./../build/common.sh: line 32: hack/lib/init.sh: No such file or directory`. Any one else has got this problem?

I think the `common.sh` may lost a line `cd "${KUBE_ROOT}"`. Running `release.sh` works well if I add the line into `common.sh`.

Should we add the line [like this](https://github.com/xiangpengzhao/kubernetes/commit/5a8f02fee439c6ef7766bdebb00d05cd2e28178b)? 

hi @lavalamp , would you please check this? If it's okay, I will create a PR.

**Comment by lavalamp** [comment]
What is your working directory when you run the build script?

**Comment by xiangpengzhao** [comment]
@lavalamp 

More info:
code:
```
git remote -v:
origin	https://github.com/kubernetes/kubernetes.git (fetch)
origin	https://github.com/kubernetes/kubernetes.git (push)
```
local working directory:
`/home/paas/zxp/code/k8s/k8smaster/kubernetes/`

When I run build/release.sh for dockerized building, it fails.

If I add an echo in init.sh like this:
```
..........
# This will canonicalize the path
KUBE_ROOT=$(cd $(dirname "${BASH_SOURCE}")/.. && pwd -P)
echo `pwd`
source hack/lib/init.sh
```
it shows:
```
/home/paas/zxp/code/k8s/k8smaster/kubernetes/build
./../build/common.sh: line 32: hack/lib/init.sh: No such file or directory
```

And if I add `cd "${KUBE_ROOT}"` in init.sh like this:
```
..........
# This will canonicalize the path
KUBE_ROOT=$(cd $(dirname "${BASH_SOURCE}")/.. && pwd -P)
cd "${KUBE_ROOT}"
echo `pwd`
source hack/lib/init.sh
```
it shows as below and works well:
```
/home/paas/zxp/code/k8s/k8smaster/kubernetes
+++ [0525 20:41:05] Verifying Prerequisites....
+++ [0525 20:41:22] Building Docker image kube-build:build-d4a8d07e54.
```

**Comment by lavalamp** [comment]
What OS are you on? What version of bash? Maybe the cd in `$(cd $(dirname "${BASH_SOURCE}")/.. && pwd -P)` is escaping the subshell in your environment?

Just to triple check, you're running the script from the kubernetes directory?

```bash
$ pwd
.../kubernetes
$ build/release.sh
...
```

**Comment by xiangpengzhao** [comment]
I'm not so sure whether the cd in $(cd $(dirname "${BASH_SOURCE}")/.. && pwd -P) is escaping the subshell or not. It seems so.

OS:
```
root@vm:/home/paas/zxp/code/k8s/k8smaster/kubernetes/build# uname -a
Linux vm 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Run the script:
```
root@vm:/home/paas/zxp/code/k8s/k8smaster/kubernetes/build# ./release.sh 
./../build/common.sh: line 31: hack/lib/init.sh: No such file or directory
```

**Comment by xiangpengzhao** [comment]
```
root@vm:/home/paas/zxp/code/k8s/k8smaster# which bash
/bin/bash
root@vm:/home/paas/zxp/code/k8s/k8smaster# bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by xiangpengzhao** [comment]
If I just run `cd .. && pwd -P`, it seems OK

```
root@vm:/home/paas/zxp/code/k8s/k8smaster/kubernetes/build# cd .. && pwd -P
/home/paas/zxp/code/k8s/k8smaster/kubernetes
root@vm:/home/paas/zxp/code/k8s/k8smaster/kubernetes#
```

@lavalamp

**Comment by lavalamp** [comment]
```
root@vm:/home/paas/zxp/code/k8s/k8smaster/kubernetes/build# ./release.sh 
./../build/common.sh: line 31: hack/lib/init.sh: No such file or directory
```

No, this is the problem. You can't run it from the build directory. It's only tested when run from the root of the repository. (this is what I was trying to ask previously.)

It doesn't seem worth it to me to fix this-- chance of making the build script worse on some other system or way of running it is too high. (Adding a `cd` like you propose isn't good--users don't like scripts that randomly change directories--so the proper fix would be to make it robust to being run with different working directories.)

Hope this helps!

**Comment by xiangpengzhao** [comment]
Thanks @lavalamp , it works well by running `build/release.sh` from the root of the repository now. BTW, I used to run `./release.sh` from the build directory and it worked well, so I thought that's the right way to build. :sweat_smile:

**Comment by xiangpengzhao** [comment]
hi @lavalamp , would you please check another issue #26261 ? Thanks!
