### ISSUE TITLE
Maximum number of concurrent CreateRoute calls should be configurable

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#26274]
#26263 introduces a limit on the number of concurrent CreateRoute calls in flight. This is necessary, because GCE has such a limit and we want to avoid a huge number of "Rate Limit Exceeded" errors.

However, this is now a constant number - this should be configurable and also depend on the cloud provider.

@zmerlynn @gmarek

**Comment by gitfred** [comment]
Guys it should be closed.

**Comment by gmarek** [comment]
Wrong SIG.
/sig cluster-lifecycle
