### ISSUE TITLE
Need a way for user to specify container labels

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#26275]
I need a way for a client creating a pod to put something in the pod that specifies some container labels.  Please note that I am **_not_** talking about making a pod's containers inherit all the pod's labels.  Rather, I am talking about a new bit of specification for labels that are intended just for the containers.

For my use case, it suffices to give the client a way to specify one set of labels, and that set gets put on every container of the pod.  I could also use a more flexible interface that gives independent control over the labels going on to each container.

To be concrete, the less expressive interface would be an additional pod spec field whose name is something like `containerLabels` and whose value is a map from label name to label value.  The more expressive interface would be an additional container spec field like that, but named something simpler like `labels`.

For prototyping the less expressive interface, we might start with supporting annotations of the form `alpha.kubernetes.io/containers-labels/XXX=YYY`, each meaning to put the label `XXX=YYY` on each container of the pod.

The more expressive interface could be prototyped with something like annotations of the form `alpha.kubernetes.io/container-labels/ZZZ/XXX=YYY`, each meaning that the label `XXX=YYY` is to be put on the pod's container named `ZZZ`.

**Comment by MikeSpreitzer** [comment]
BTW, for my use case, I do not need to update the container labels --- the client can supply the needed labels from the start, and they do not need to change during the lifetime of the pod.

**Comment by MikeSpreitzer** [comment]
I have realized that there can not be two slashes in an annotation.  So here are proposed annotations that use only one slash:
```
containers-label.alpha.kubernetes.io: XXX=YYY
container-label.alpha.kubernetes.io/{{container_name}}: XXX=YYY
```

**Comment by dims** [comment]
@MikeSpreitzer - I see a comment https://github.com/kubernetes/kubernetes/pull/27964#issuecomment-232136812 which references another https://github.com/kubernetes/kubernetes/issues/28789 So we can close this right?

**Comment by MikeSpreitzer** [comment]
Closing in favor of lifecycle hooks.

**Comment by EdSchouten** [comment]
My observation is that not having any support for container-level labels also makes the way you can let Prometheus scrape multiple containers in one pod pretty awful:

https://github.com/prometheus/prometheus/issues/1864

At Kumina we have some pods running multiple containers, some of them providing metrics, some don't. In our case we'd like to say: "for these three containers, please scrape metrics for two of them."

Right now you can only choose to scrape exactly one (by setting prometheus.io/port: 12345) or all three of them (by not setting prometheus.io/port at all). Ideally you'd want to be able to set prometheus.io/port on a per-container basis.

Is there any chance per-container labels will still appear at some point in time?

**Comment by runcom** [comment]
This has never landed as a feature even post CRI - there are use cases out there that would benefit from having this. The previous attempt is here https://github.com/kubernetes/kubernetes/pull/27964 but it was closed because of the CRI introduction. Should this be reopened and make another proposal?

@Random-Liu @feiskyer @MikeSpreitzer @mrunalp PTAL

**Comment by xujihui1985** [comment]
is there any chance to reopen this issue?

**Comment by cjreyn** [comment]
+1 for this

**Comment by qalinn** [comment]
+1

**Comment by chetanyachopra** [comment]
+1

**Comment by sftim** [comment]
/reopen
Just to mark this as not planned

**Comment by sftim** [comment]
We didn't find capacity for this.
/close not-planned
