### ISSUE TITLE
OS_DISTRIBUTION / NODE_IMAGE backwards incompatible change

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#26291]
As of #26197 (specifically [here](https://github.com/kubernetes/kubernetes/pull/26197/files#diff-57380bb03c3598646d5a3cb66518fa0bR50)), running `kube-up` against GCE without setting a node image defaults it to containervm, whereas before it defaulted it to the master image.

For example, my config of:
```
KUBE_GCE_MASTER_PROJECT=coreos-cloud
KUBE_GCE_MASTER_IMAGE=coreos-stable-899-17-0-v20160504
KUBE_OS_DISTRIBUTION=coreos
....
```

brings up a coreos master and then launches nodes with `containervm` images. Before the above-referenced change this gave me my expected coreos nodes.

Was this change intentional?

The easiest fix that comes to mind for me is only doing the new containervm defaulting if `OS_DISTRIBUTION` is gci.

cc @wonderfly

**Comment by wonderfly** [comment]
Yeah, this was something I was concerned too while making the change. However, the decision seems to have been that we decided to default `MASTER_IMAGE` to GCI, yet still default `NODE_IMAGE` to the debian based containervm. Also, if we are to seriously start supporting hybrid clusters, i.e., master and nodes run on different OS distros, which seems true according to #26183 , this old assumption of `NODE_IMAGE` defaults to `MASTER_IMAGE` needs to disappear anyways.

cc/ @roberthbailey @dchen1107 Thoughts?

**Comment by roberthbailey** [comment]
> The easiest fix that comes to mind for me is only doing the new containervm defaulting if `OS_DISTRIBUTION` is gci.

That sounds reasonable to me. We clearly didn't think about your use case whilst making this change.

**Comment by euank** [comment]
@wonderfly I don't see the issue with defaulting to non-hybrid while supporting hybrid.. Defaulting `NODE_IMAGE = MASTER_IMAGE` seems totally reasonable even in a world where hybrid support is possible. A user could explicitly control that they want hybrid via setting them to different values regardless of the defaulting, or wherever hybrid is toggled on different defaulting could be done.

I left a few questions on the referenced original issue which, if/when answered, might help me in making a PR to fix this for my usecase more cleanly.

**Comment by wonderfly** [comment]
> Defaulting NODE_IMAGE = MASTER_IMAGE seems totally reasonable even in a world where hybrid support is possible. 

Agreed.

I am making a fix to this.
