### ISSUE TITLE
Set timeout for docker image pull calls

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#26300]
We recently removed the timeout for image pulls because the default is too low (i.e. 2 min), and it's hard to gauge what time will work for the users.

However, it's important that we set "a certain" timeout for such requests to resolve the cases where the request hangs indefinitely.
Off the top of my head, there are two options:

 1. Add the timeout back. Set the default to something longer (e.g., 10 minutes) and make it configurable through kubelet flags.
 2. Detect whether the pull request is making progress by leveraging the pull progress reporter (#26145) and cancel the request if the progress has stalled over a threshold.

/cc @kubernetes/sig-node

**Comment by Random-Liu** [comment]
I'll try option 2 once #26145 gets merged.

**Comment by ncdc** [comment]
+1 to option 2
