### ISSUE TITLE
Google Cloud Platform resources leaked while running tests: target-pools

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#26319]
Prashanth, would you have time to look into this?  If not, suggest someone else on cluster?

A run of kubernetes-e2e-gke failed due to a leaked target-pool:

From http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke/7753/console
16:15:45 +++ /workspace/_artifacts/gcp-resources-after.txt	2016-05-25 16:15:45.033318520 -0700
16:15:45 @@ -94,0 +95 @@ [ target-pools ]
16:15:45 +a2454310622cd11e6bc4642010af0000  us-central1'
16:15:45 + true
16:15:45 ++ echo '--- /workspace/_artifacts/gcp-resources-before.txt	2016-05-25 16:00:13.285558292 -0700
16:15:45 +++ /workspace/_artifacts/gcp-resources-after.txt	2016-05-25 16:15:45.033318520 -0700
!!! FAIL: Google Cloud Platform resources leaked while running tests!

@kubernetes/goog-cluster @kubernetes/sig-network

**Comment by thockin** [comment]
The test that leaked this was "e2e-tests-resourcequota-jmbvk/test-service"
(as discovered in the 'description' field)

@derekwaynecarr

**Comment by derekwaynecarr** [comment]
Just so I understand, would this be caused by a test that created a load balancer service?

**Comment by derekwaynecarr** [comment]
I can't seem to open the linked document, but the test does create a node port service and a load balancer service.  If there is something special I need to do to ensure that the load balancer is properly cleaned up?  It should be purged by namespace deletion.

**Comment by bprashanth** [comment]
I think you can see https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke/7753/ if you log into your (public) google account.

Yes simply deleting the service *should* cleanup the loadbalancer.

**Comment by ncdc** [comment]
@bprashanth I've never been able to access pantheon.corp. It always redirects to https://login.corp.google.com/request?s=pantheon.corp.google.com:443/uberproxy/&d=https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke/7753/....

A URL like this does work for me: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke/7753/

**Comment by thockin** [comment]
The linking to anything.corp is a problem.

**Comment by zmerlynn** [comment]
Also seen on: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke/8659?pli=1

**Comment by ncdc** [comment]
Public links please! 😄

**Comment by bprashanth** [comment]
Someone should write a chrome plugin that s/pantheon.corp/console.cloud/

**Comment by derekwaynecarr** [comment]
There is a fix in the queue for this.  +1 on a plug-in.

**Comment by davidopp** [comment]
@derekwaynecarr Do you have the PR # for the fix? Thanks!

**Comment by ncdc** [comment]
@davidopp #26803 along with #26806 (to have equivalent test coverage)
