### ISSUE TITLE
Kubemark: Use unstable state, don't fail completely

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#26318]
https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/e2e-runner.sh#L367

If we fail completely, it blocks the submit queue.

@wojtek-t or @gmarek can one of you fix this ~asap? This is blocking the merge queue unnecessarily. See: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-kubemark-500-gce/3375/

**Comment by wojtek-t** [comment]
@lavalamp - sorry, I don't understand what you want me to do. Can you please clarify?

**Comment by lavalamp** [comment]
When kubemark fails, it leaves its status in jenkins as "failed".

If instead its status was "unstable" and it printed out JUnit files like our other e2e test suites, then the queue optimization would work and it wouldn't block the queue until the same test failed twice in a row.

This is costing us an hour or two a day of merge time.

**Comment by pwittrock** [comment]
I can pick this up

**Comment by gmarek** [comment]
Thankis @pwittrock!
