### ISSUE TITLE
Fix hack/update-godeps-license.sh, re-enable hack/verify-godeps-license.sh, and commit updated godeps licenses to master.

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#26328]
Details in:

https://github.com/kubernetes/kubernetes/pull/26020#issuecomment-221625046

@lavalamp and I could not get hack/update-godeps-license.sh to work.

Hence #26020 got merged without updating the godeps licenses accordingly.
hack/verify-godeps-license.sh is currently disabled.

cc: @goltermann @david-mcmahon @karlkfi @zmerlynn

**Comment by roberthbailey** [comment]
We should try to fix this before we cut the 1.3 branch.

**Comment by thockin** [comment]
I'm taking a quick look, since I touched some of this.

**Comment by thockin-cc** [comment]
#26348 offered as a godeps-licenses fix.

**Comment by bgrant0607** [comment]
@thockin Can this be closed?

**Comment by quinton-hoole** [comment]
Yes, it can be closed. I tried to mark the pr to auto-close this but must have messed it up. We need a different, replacement PR which I will open now and cross-reference.

**Comment by quinton-hoole** [comment]
#26469 refers
