### ISSUE TITLE
Docker cannot find pre-pull imagse

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#26320]
Another image pull related failure:

[artifacts](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25034/kubernetes-pull-build-test-e2e-gce/37862/)

Looking at the docker logs, it looks like docker is getting a 404 pulling some of the images

>
time="2016-05-02T10:38:57.316460860Z" level=info msg="GET /images/gcr.io/google_containers/redis:e2e/json?size=1" 
time="2016-05-02T10:38:57.316701560Z" level=error msg="Handler for GET /images/gcr.io/google_containers/redis:e2e/json returned error: No such image: gcr.io/google_containers/redis:e2e" 
time="2016-05-02T10:38:57.316734734Z" level=error msg="HTTP Error" err="No such image: gcr.io/google_containers/redis:e2e" statusCode=404 
time="2016-05-02T10:38:57.324811116Z" level=info msg="GET /version" 
time="2016-05-02T10:38:57.332173281Z" level=info msg="POST /images/create?fromImage=gcr.io%2Fgoogle_containers%2Fredis&tag=e2e"

**Comment by Random-Liu** [comment]
@pwittrock The error message is normal. We always inspect to see whether the image presents before pulling image. If the image doesn't present, docker will record 404 error in log.

**Comment by yujuhong** [comment]
The logs are from May 2nd, when we didn't have the image prepulling. Closing the issue.
