### ISSUE TITLE
Solution discussion for rebuilding federation service controller cache on restart

### ISSUE THREAD

**Issue by mfanjie** [kubernetes/kubernetes#26329]
I am working on federation service controller, and there is a limitation on current cache, after had a call with @quinton-hoole, as it's not a common case, we will leave it as is in v1.3, and I open this issue to track the problem and to find out a more robust solution.

**Federation service controller behavior description:**
1. service controller watch federation apiserver for new services, create service map in the form of
`fedServiceMap: [serviceName]cachedService: {service info, endpointMap: [clusterName]int, serviceStatusMap: [clusterName]api.LoadBalancerStatus}`
endpointMap and serviceStatusMap have no element at this moment.
2. service controller create the service on all healthy clusters
3. service controller watches all healthy clusters for services and endpoints.
When new serviceStatus with LB info is returned, add it to serviceStatusMap and service info and update federation apiserver with the new LB info.
4. when new endpoint info returned, add it to endpoint map with flag 1 which indicates there is reachable endpoints

**Problem description:**
From above behavior description, we can see that serviceStatusMap is the only place to link clusterName and LB info, it is not persisted anywhere and it will go on service controller down.

So if during service controller down time, the service on any clusters is deleted, and after federation service controller being starts, the service will be rebuild on that cluster again, with different LB info, and as we lost the link between cluster and LB info, we do not know which old LB info in federation service was returned by from that cluster, as a result, we can add the new IP to federation service, but there is no way to remove the old one.

**One typical example**
Federation service:S1
Clusters: C1, C2
after S1 is created, it will be created in C1 and C2, with LB IP1, and LB IP2 assigned.
So after the a while S1 will changed to S1[LB:{IP1, IP2}]
serviceCache is same S1[LB:{IP1, IP2}]
serviceStatusMap [C1]S1[LB:IP1], [C2]S1[LB:IP2] , most import one, it links Ingress IP and clusters.
endpointMap [C1]1,[C2]1 

For the case that LB IP in C1 changed from IP1 to IP3
If we have the cache info, we know IP1 is from C1 previously, so we can remove it and add IP3.
But If Service Controller is restarted, we will lose the old LB IP info, we do not know which IP we should remove from Federation IP, and the ingress info will be changed to S1[LB:{IP1, IP2, IP3}]

**Comment by quinton-hoole** [comment]
Provisionally assigning to @mwielgus who has been thinking about similar things.  Some of this is now incorporated into our common federation controller library.  We can close this once we have ported the Federated Service Controller to the common federation controller library (there is an issue for that somewhere), and verified that all of the cases outlined in this issue are addressed by that port.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#44.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
