### ISSUE TITLE
Submit queue's unit tests taking more than 1 hour to run

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#26337]
In PRs that the mungebot is trying to merge, the e2es are passing after ~40 minutes, but the unit/integration are taking around an hour (or a bit more).  That's a significant slowdown to the rate at which we can merge.

See e.g. http://submit-queue.k8s.io/#/history that shows the time elapsed between Requesting a run to MERGED of ~1 hour.

Example PR, with "test this" from over an hour ago, e2e's finished 23 mins ago, and unit/integration still not done: https://github.com/kubernetes/kubernetes/pull/25895

**Comment by alex-mohr** [comment]
@kubernetes/sig-testing @kubernetes/test-infra-maintainers

**Comment by fejta** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/25940
