### ISSUE TITLE
doc bug in http://kubernetes.io/docs/user-guide/compute-resources/

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#26340]
At http://kubernetes.io/docs/user-guide/compute-resources/

The following line
``
The following pod has two containers. Each has a request of 0.25 core of cpu and 64MiB (2^20 bytes) of memory and a limit of 0.5 core of cpu and 128MiB of memory. The pod can be said to have a request of 0.5 core and 128 MiB of memory and a limit of 1 core and 256MiB of memory.
``
incorrectly mentions 64Mib as 2^20bytes.
MiB is 2^20 so 64MiB is 64*2^20 which would be 2^26

**Comment by dims** [comment]
@krmayankk on the web page link you pasted, you will see blue circle on the right hand side with a pencil inside. if you click on it, it will walk you through an editor where you can submit a change yourself.

Thanks,
Dims

**Comment by bgrant0607** [comment]
@krmayankk Please file this on kubernetes.github.io

**Comment by a-robinson** [comment]
Opened https://github.com/kubernetes/kubernetes.github.io/issues/597 for you. Contributions welcome! :)
