### ISSUE TITLE
cluster-autoscaler: incompatible variable names with GKE

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#26343]
In kube-up we use var `ENABLE_NODE_AUTOSCALER` while in GKE, documentation, issues etc I think we call it cluster autoscaler. We should make it consistent.

**Comment by davidopp** [comment]
I assume this is what you were already thinking, but: I think we should change it to cluster autoscaler (everywhere). You scale the cluster by adding/removing nodes. You scale a node by adding/removing resources to/from the node, so node autoscaler isn't the right term IMO.
