### ISSUE TITLE
Warning image link is broken across docs

### ISSUE THREAD

**Issue by rnowling** [kubernetes/kubernetes#26357]
This includes `podaffinity.md` but effects multiple docs.

**Comment by joe2far** [comment]
This issue was also raised on the kubernetes.github.io repository, see: [ Issue 154](https://github.com/kubernetes/kubernetes.github.io/issues/154)

**Comment by eyalev** [comment]
What's needed to fix this? Are the broken headers being generated automatically somewhere?

**Comment by joe2far** [comment]
@eyalev - The warning section is pre-pended to the md docs from the following script
cmd/mungedocs/unversioned_warning.go

The [PR #26702](https://github.com/kubernetes/kubernetes/issues/26702) fixes this issue, updating this script and all the docs...
However,  there is an open question as to where the docs should be removed from this repo which has prevent this PR from being merged.
