### ISSUE TITLE
Persist node tags to apiserver

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#26358]
Persisting important config options in a salted file works, but we expose ourselves to bugs on every cluster update. I'm more confident about a solution that persists important information through the apiserver. 

One way to achieve this is: service controller comes up, looks for config map, if not found - looks for gce.conf:nodeTags and persists to config map. This would also allow a reconciliation loop that doesn't depend on in memory state.

@kubernetes/goog-cluster

**Comment by jingxu97** [comment]
I think there is a assumption that gce.conf.nodeTags must match a common tag of each instance in the cluster. If we allow user to change tags for the cluster, can we find a way to also update the config nodeTags? Otherwise, they won't match.

**Comment by bprashanth** [comment]
The reconciliation loop in the controller should completely own this. The tag is a cluster level property enforced on each node in the cluster and all firewall rules created for the cluster.

**Comment by bgrant0607** [comment]
This is obsolete.
