### ISSUE TITLE
Return 400 when i use kubernetes Deployment rollback API

### ISSUE THREAD

**Issue by workhardcc** [kubernetes/kubernetes#26353]
Sorry, maybe this is not a problem.
Post data as below to url 
http://$ip:8080/apis/extensions/v1beta1/namespaces/default/deployments/deployment-1/rollback
`{"kind":"Deployment","apiVersion":"extensions\/v1beta1","name":"deployment-1","updatedAnnotations":"1111","rollbackTo":{"revision":0}}`
return error:
`{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Deployment in version \"v1beta1\" cannot be handled as a DeploymentRollback: converting (v1beta1.Deployment) to (extensions.DeploymentRollback): UpdatedAnnotations not present in src","reason":"BadRequest","code":400}`
Is there anything wrong with my post data?
Another question: 
If a Deployment has two pods, there're two container in each of pod. I want update one container's image(use the url `http://$ip:8080/apis/extensions/v1beta1/namespaces/default/deployments/$deployment_name`). If i just change the first container's image, another container is gone! Is that right? It means that if I want update one containers' label or image I need define all the info of the containers which in the same pod?

**Comment by workhardcc** [comment]
For the second question use command like this still have the same issue.
curl --request PATCH --header "Content-Type:application/merge-patch+json" http://$ip:8080/apis/extensions/v1beta1/namespaces/default/deployments/deploymen‌​t-patch --data '{"spec":{"template":{"spec":{"containers":[{"name":"mofang-web","image":"abc.co‌​m\/docker\/mofang-web-cc:stable"}]}}}}' 

version:1.22

**Comment by Laisky** [comment]
@workhardcc did you solved these problems? I got the same errors.

**Comment by workhardcc** [comment]
@Laisky yes, did you solved it ?

**Comment by Laisky** [comment]
@workhardcc still not work on Kubernetes v1.2.6

There are two kinds of errors.

If I POST

```
data = {
    'kind': 'DeploymentRollback',
    'apiVersion': 'extensions/v1beta1',
    'name': 'test-hello-world',
    'rollbackTo': {
        'revision': 1
    }
}
```

return:
```
{'apiVersion': 'v1',
 'code': 500,
 'kind': 'Status',
 'message': 'expected pointer, but got invalid kind',
 'metadata': {},
 'status': 'Failure'}
```

If I post

```
data = {
    'kind': 'Deployment',
    'apiVersion': 'extensions/v1beta1',
    'name': 'test-hello-world',
    'UpdatedAnnotations': {'label': 'test'},
    'rollbackTo': {
        'revision': 1
    }
}
```

Return:

```
{'apiVersion': 'v1',
 'code': 400,
 'kind': 'Status',
 'message': 'Deployment in version "v1beta1" cannot be handled as a DeploymentRollback: converting (v1beta1.Deployment) to (extensions.DeploymentRollback): UpdatedAnnotations not present in src',
 'metadata': {},
 'reason': 'BadRequest',
 'status': 'Failure'}
```

**Comment by workhardcc** [comment]
@Laisky I forgot how I fix this problem last time. I will try it tonight again.

**Comment by workhardcc** [comment]
here is my note:
{
    "kind": "DeploymentRollback",           
    "apiVersion": "extensions/v1beta1",     
    "name": "node-46",           //deployment's name           
    "rollbackTo": {
        "revision": 3                     
    }
}

HTTP Produces: application/json
访问方式：POST方法传入json串

**Comment by rohanKanojia** [comment]
@workhardcc @Laisky : Did you guys manage to solve this? I am facing the same issue

**Comment by liuhengliang666** [comment]
你们解决了吗，我也遇到同样的问题了！
