### ISSUE TITLE
Reminder: Revert #24808 when mount.glusterfs enables --verbose error returns functionality is implemented

### ISSUE THREAD

**Issue by screeley44** [kubernetes/kubernetes#26367]
This is a place holder to revert the reading of glusterfs logs for true errors.  There is currently a work in progress to enabled glusterfs mount.glusterfs to use --verbose option which would return the error directly to the caller rather than writing to a log file and then having an extra step of opening and parsing the log file to obtain the true error.

when this functionality is available we can revert #24808

**Comment by msau42** [comment]
@screeley44 can this be closed?
