### ISSUE TITLE
Don't blindly trust cached state of load balancer resources in service controller

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#26362]
Multiple users have been bit by some variant of the following problem: they delete a resource from their cloud provider that was created as part of a service's external load balancer. If they deleted it accidentally, they wonder why their load balancer stopped working. If they deleted it intentionally, they wonder why it comes back after an indeterminate amount of time (typically on the order of days or weeks).

This is caused by us caching the last observed state of the cloud provider resources in the service controller (with no TTL) rather than rechecking it periodically, such that it only gets rechecked when the controller manager process is restarted. This confusion isn't worth saving a few cloud API calls, particularly given that most clusters don't expose all that many external services.

We might want to include this as a bug fix in 1.3, but it's not absolutely critical. Happy to hear your thoughts on that.

@bprashanth @thockin @alex-mohr

**Comment by thockin** [comment]
@matchstick good one

I think this is P2 for 1.3.

**Comment by therc** [comment]
In AWS land, now that we have addressed in 1.3 most or all of the reasons for which users used to mess manually with ELBs (and keep their fingers crossed that their controllers wouldn't restart for weeks at a time), I think we're ready to refetch service state every minute or two. I could tackle it, but only after #26900, which addresses what's maybe the current leading candidate for getting users throttled. 

@justinsb

**Comment by thockin** [comment]
I'm ejecting this from 1.3.  We want this, but there's just no way we can make it for 1.3

**Comment by bprashanth** [comment]
If it's not making 1.3 we might as well https://github.com/kubernetes/kubernetes/pull/25189 and make sure we get the refresh logic right going down that path

**Comment by a-robinson** [comment]
Not trusting the cache seems like a significantly safer change than the major rewrite in #25189...

**Comment by thockin** [comment]
I guess we can consider PRs, if they are very safe and ready to go.  I
don't know this code, so I assumed it was a hard change :)
