### ISSUE TITLE
kube-up.sh for AWS: better error reporting for hitting quota limits for Elastic IPs

### ISSUE THREAD

**Issue by markine** [kubernetes/kubernetes#26368]
As of kubernetes v1.2.4, kube-up.sh has a somewhat opaque error when it is unable to reserve an Elastic IP for a cluster (for our case, we were out of quota for EIPs):

```
...
Adding tag to sg-XXX: KubernetesCluster=ZZZ
Using master security group: kubernetes-master-ZZZ sg-XXX
Using minion security group: kubernetes-minion-ZZZ sg-BBB
Creating master disk: size CCC, type gp2
Adding tag to vol-YYY: Name=ZZZ-master-pd
Adding tag to vol-YYY: KubernetesCluster=ZZZ

A client error (AddressLimitExceeded) occurred when calling the AllocateAddress operation: The maximum number of addresses has been reached.
```

The request here is to have a clearer error to communicate that this is an EIP issue and suggestions as to what to do about it.

**Comment by ptarpan** [comment]
As an alternative, can a private IP instead of EIP be used to at least bring up the cluster? Considering the shortage of IPv4 addresses, I am trying to avoid EIPs altogether.

**Comment by justinsb** [comment]
kube-up is in maintenance mode, so we're trying to avoid making changes of this type.  If you hit this in e.g. kops please open an issue there.

But actually this issue itself is great documentation - the error message and the explanation.  Hopefully it will come up in searches if people hit it in future :-)
