### ISSUE TITLE
e2e test flake: package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: net/http: TLS handshake timeout)

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#26385]
```
package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: net/http: TLS handshake timeout)
```

I've seen it 3 times in different PRs.

https://github.com/kubernetes/kubernetes/pull/25604#issuecomment-221978379
https://github.com/kubernetes/kubernetes/pull/25599#issuecomment-221948050
and this [one](https://00e9e64bace6f97fd736df25072ad5a584cc18e6d653618ee4-apidata.googleusercontent.com/download/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F26381%2Fnode-pull-build-e2e-test%2F8072%2Fbuild-log.txt?qk=AD5uMEuy_jabW3fRwUBlJZQ-K_FuLqBdcHaBDLjbNIZCVap8K-JTlrjLoF7-4HvNwUhxB3kGAFdSnegElnIyt8z3ZGUuIuEIKBd315UEXZ_KTUdj6PoNUiUAkII1lV_7WRLiuu8rrNmMR7PuKW9CVlsduc9SCl1-J1NUyHCcB96qWa7jL7LRbvc6WvCZ72JO3AWtEgyYgamg_h52mKVIY1b-iDe_-yyrQ4YaMaCcnF95KAZYaMMoBok-lm50KPYGPOaXIPPWcyTlj6gH1BVHKJXLHVrkFmg4hjenDNroFqBoKjmjVA5pg1qbJUSOb7E7i4vc3wMHvFmnGvoZ3ea-lZFsq8hqkBbXYiYAJ_EvlWwJ_F90Hv7gJrJPpO8CSqRvdafY14mknmCyRsoGGgcXzNzASjzYBfYe7yHs1z6tVJjtGjS7unNkDwDzzj9B6on4IZF9A157Y062I-cnOQ8k2L6ceHadgU3HE8GMnxg7OEpjdeZ616EprXtQpqTgWONrys1IKaSs0CkLpNUittx1T70Xeaf_FMLm_Zjl5KGYm6vFvmYiY1v14PDmLGgs8ccYZsaCxQ6UGccNnJ2ahJ5YBWcLYiQ2BAVX7B5O6TqKih6zi96kFlv8FmlfCrQnu1tQiyIIJXGb3tyl3Eae50ITB7OoPl9JGaGvZ84JkoIL1kql7pULYPovb9GD-_4hqeT6CTXVSysiL1JP2U8hP22XNTr60xvUqpHDi6laJzK_gFadsxKwDKIoHrkyyxhxfEJE-A4uJ-6_BAUMo4XNhp3S7-VmdPM-MZTzZ6E3q0popPugr4xl0vH63xHA2MfzSIDaM4SWJNJ1d-HDBW8mXHOb-zdj5XTD1ButHw)

**Comment by caesarxuchao** [comment]
Is it because `https://gopkg.in` was down?

**Comment by janetkuo** [comment]
Again https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/26386/node-pull-build-e2e-test/8079/build-log.txt

**Comment by janetkuo** [comment]
```
+ go get -u github.com/onsi/gomega
# cd .; git clone https://gopkg.in/yaml.v2 /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/gopkg.in/yaml.v2
Cloning into '/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/gopkg.in/yaml.v2'...
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
package gopkg.in/yaml.v2: exit status 128
Build step 'Execute shell' marked build as failure
```

**Comment by alex-mohr** [comment]
@lavalamp or @thockin who understands godep stuff?  If not you, someone else?

**Comment by dims** [comment]
@alex-mohr @thockin @lavalamp - i suspect we can get past this problem by switching from https:// to git:// using this .gitconfig trick:
https://github.com/golang/go/issues/6968#issuecomment-66089342

**Comment by ericchiang** [comment]
@dims to the best of my knowledge gopkg.in doesn't support the git:// scheme. It's not simply redirecting you to github, it's actually rewriting the refs[0] so the go tool thinks it's cloning the default branch.

```
$ rm -rf $GOPATH/src/gopkg.in/yaml.v2
$ go get -x gopkg.in/yaml.v2 2>&1 | grep 'git clone'
git clone https://gopkg.in/yaml.v2 /home/eric/src/gopkg.in/yaml.v2
```

The errors look like they were cased by gopkg.in being down, and not being able to get the info needed to find the git repo.

```
package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: net/http: TLS handshake timeout)
```

[0] https://github.com/niemeyer/gopkg/blob/65998c5554ba84a0aa56c479868c2c0fae466c8c/main.go#L291

**Comment by lavalamp** [comment]
Is this a failure running the godep verification script?

**Comment by dims** [comment]
@ericchiang i see..please see the "go get -u github.com/onsi/gomega" in the last comment from @janetkuo

**Comment by lavalamp** [comment]
@mhrgoog, @david-mcmahon, @thockin: can one of you take this? I've got no time to dig in.

Is this really P0?

@dims Would that make a difference? It looks like the problem is connectivity, I don't know that changing the transport would help?

**Comment by timothysc** [comment]
umm why are you pulling an updated dep to the node-e2es?  

There is already a vetted version in the vendored/godeps.  You could literally break yourself on an random update..?  

This step seems unnecessary.

**Comment by mhrgoog** [comment]
I am a noob but I am poking around and learning as I go on this bug. 

One log file that logs the error for PR 25599 is found at kubernetes-jenkins/pr-logs/pull/25599/node-pull-build-e2e-test/8044.

+ ./test/e2e_node/jenkins/e2e-node-jenkins.sh ./test/e2e_node/jenkins/jenkins-pull.properties
+ : ./test/e2e_node/jenkins/jenkins-pull.properties
+ . ./test/e2e_node/jenkins/jenkins-pull.properties
++ GCE_HOSTS=
++ GCE_IMAGES=e2e-node-ubuntu-trusty-docker10-image,e2e-node-ubuntu-trusty-docker9-image,e2e-node-ubuntu-trusty-docker8-image,e2e-node-coreos-stable20160218-image,e2e-node-containervm-v20160321-image
++ GCE_ZONE=us-central1-f
++ GCE_PROJECT=kubernetes-jenkins-pull
++ INSTALL_GODEP=true
++ CLEANUP=true
+ '[' true = true ']'
+ go get -u github.com/tools/godep
+ go get -u github.com/onsi/ginkgo/ginkgo
+ go get -u github.com/onsi/gomega
package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: net/http: TLS handshake timeout)
Build step 'Execute shell' marked build as failure
[PostBuildScript] - Execution post build scripts.

**Comment by thockin** [comment]
we have talked about vendoring godep before.  Time to just do it?

**Comment by timothysc** [comment]
> I am not sure why we need godeps for this test, it looks like these "go get" calls were added by pwittrock. He might know. ccing him on the issue.

I don't think we should be doing this.   You could be pulling in an update that is un-vetted and breaks your code.

**Comment by pwittrock** [comment]
@timothysc I agree the 'go get' calls are sub-optimal.  I'll see what I can do to remove them.

**Comment by pwittrock** [comment]
cc @vishh

**Comment by pwittrock** [comment]
Looks like godep isn't needed anymore, and onsi is already vendored. #26571

**Comment by lavalamp** [comment]
Thanks guys. We really shouldn't be running godep anything at test time as opposed to build time, or at least I can't think of a good reason for that.

**Comment by mhrgoog** [comment]
Side note. I was misusing "go list' I see now that onsi/gomega does depend on gopkg.in/yaml.v2:

$ go list -f "{{.Name}} {{.Deps}}" github.com/onsi/gomega/... | grep gopkg.in/yaml.v2 | sed 's/\[.*\]//'
gomega 
gexec 
ghttp 
matchers 
$

**Comment by fejta** [comment]
https://github.com/kubernetes/kubernetes/pull/26571
