### ISSUE TITLE
e2e failures: GKE CI masters failing to pull tarball

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#26383]
This is causing cluster creation failures, blocking the submit queue.

It appears to be trying to get the blob from the asia bucket, even though the cluster is in us-central1.

@k8s-oncall @zmerlynn 

```
May 26 21:08:46 configure.sh[637]: [155B blob data]
May 26 21:08:46 configure.sh[637]: curl: (22) The requested URL returned error: 404 Not Found
May 26 21:08:46 configure.sh[637]: == Failed to download https://storage.googleapis.com/kubernetes-release-asia/ci/v1.3.0-alpha.4.556+f24b7a
73918f62/kubernetes-manifests.tar.gz. Retrying. ==
May 26 21:08:46 configure.sh[637]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
May 26 21:08:46 configure.sh[637]: Dload  Upload   Total   Spent    Left  Speed
May 26 21:08:46 configure.sh[637]: [155B blob data]
May 26 21:08:46 configure.sh[637]: == kubernetes-manifests.tar.gz corrupted, sha1 01f1b459e59417b832a8b22332b770e098d5a9ac doesn't match exp
ected 6c10d517706e759a686ce5b953b76027def6715b ==
May 26 21:08:46 configure.sh[637]: == Hash validation of https://storage.googleapis.com/kubernetes-release/ci/v1.3.0-alpha.4.556+f24b7a73918
f62/kubernetes-manifests.tar.gz failed. Retrying. ==
May 26 21:08:46 configure.sh[637]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
May 26 21:08:46 configure.sh[637]: Dload  Upload   Total   Spent    Left  Speed
```

**Comment by a-robinson** [comment]
As mentioned in #26379, there seems to be some correlation of this happening with me SSHing to the master while it's initializing, but that's likely just a coincidence.

**Comment by a-robinson** [comment]
I suppose the more worrying part of those logs is that hash validation of the tarball that did exist failed:

```
May 26 21:08:46 configure.sh[637]: == Hash validation of https://storage.googleapis.com/kubernetes-release/ci/v1.3.0-alpha.4.556+f24b7a73918
f62/kubernetes-manifests.tar.gz failed. Retrying. ==
```

Anyone seen errors like this before?

@kubernetes/release-maintainers @kubernetes/test-infra-maintainers

**Comment by ixdy** [comment]
For mysterious reasons, the kubernetes-build job has been retriggering for the same git sha, e.g. very recently with
kubernetes-build/10069 and kubernetes-build/10070, kubernetes-build/10071 and kubernetes-build/10072.

When uploading build artifacts, the job deletes any existing tarballs before uploading the new ones. This makes sense if something was wrong with the first version, but it means that we can get into race conditions where the "latest build" file points at a nonexistent tarball.

**Comment by a-robinson** [comment]
That could certainly do it. It's not failing every time, just occasionally.

**Comment by a-robinson** [comment]
Is there anything that we can do about it? Is a different issue tracking it?

**Comment by dchen1107** [comment]
re: https://github.com/kubernetes/kubernetes/issues/26383#issuecomment-222000830

We ran into a similar issue last release: https://github.com/kubernetes/kubernetes/issues/8705

**Comment by ixdy** [comment]
#8705 was a different root cause, I think - it involved the GCS staging path for server resources we use when starting a cluster, not the GCS path where the `kubernetes-build` job uploads the built tarballs.

**Comment by ixdy** [comment]
We may want to change `hack/jenkins/build.sh` to only build/upload if the artifacts aren't already there.

The side effect is that if there is a bad build and we need to rebuild at the same sha1, we'll need to explicitly delete the old artifacts. That's probably OK though.

**Comment by a-robinson** [comment]
Ack. Assigning to you as current test infra oncall. This is causing a lot of flakes in the GKE suites. Let me know if there's anything I can do to help

**Comment by a-robinson** [comment]
Is there any reason that this would be affecting GKE, but not GCE? That's the part that confuses me.

**Comment by ixdy** [comment]
Bad luck? It should be affecting both.

**Comment by ixdy** [comment]
*cries* https://github.com/kubernetes/kubernetes/blob/a092fd2dd4091b735cc2389015ce4bef951abfab/build/common.sh#L1113-L1117

```shell
function kube::release::gcs::copy_release_artifacts() {
  # TODO: This isn't atomic.  There will be points in time where there will be
  # no active release.  Also, if something fails, the release could be half-
  # copied.  The real way to do this would perhaps to have some sort of release
  # version so that we are never overwriting a destination.
```

**Comment by ixdy** [comment]
Actually, this may be as simple as unsetting KUBE_GCS_DELETE_EXISTING in `build/push-ci-build.sh`. I'll do that now.
