### ISSUE TITLE
Serve e2e images from local docker registry

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#26390]
Yet another potential solution for the image pulling flake observed in https://github.com/kubernetes/kubernetes/issues/25277, https://github.com/kubernetes/kubernetes/issues/20550

Quoting email thread:

> I just found that this exists: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry
> It looks untested and I doubt it functions well, but we can start with it.
> We should run a local private registry in clusters.
> We should build a set of test images from the PR under test and push them to that registry.
> I think this is the way we should fix this for real.

Other ideas include: https://github.com/kubernetes/kubernetes/issues/26322, flipping nodes to schedulable only once they've pulled the entire image list, and running a daemon set with the list of "images" as a list of "containers" (this has the advantage of working with all supported image distribution mechanisms). 

We're currently doing a quick and dirty static pod image puller. 

@kubernetes/sig-node @lavalamp

**Comment by vishh** [comment]
I like the PD option that @timstclair had proposed earlier. Essentially have a PD with all the images stored as tar files and load it using docker upon node startup. 
We will have to manage the lifecycle of these PDs out of band. Assuming that PD is more reliable than remote registries, this option is more robust and will probably be faster too..

**Comment by vishh** [comment]
Related issue - #26322

**Comment by bprashanth** [comment]
I was not against the pd option. I'm just not comfortable with the fact that if we can't pull images reliably our whole house of cards will crumble. It feels like testing `service.Type=LoadBalancer` without actually spinning up an external GCE lb but using nginx, because that's slow.

**Comment by vishh** [comment]
It depends on what we want to test. Not all contributors to Kubernetes care
about `gcr.io` or `dockerHub` being healthy. We can continue to test GCR
and other GCE services in localized tests. But making them a pre-requisite
for all our testing sounds a bit overwhelming to me.

**Comment by bgrant0607** [comment]
ref #1319

**Comment by bprashanth** [comment]
> Not all contributors to Kubernetes care about `gcr.io` or `dockerHub` being healthy.

Yeah but image pulling via http should work in a variety of conditions and environments, which is difficutl to ensure in a controlled test with a handful of images

**Comment by vishh** [comment]
If we want to include real world randomness to some extend, can we run our
tests with and without dependency on remote registries?
From Kubernetes perspective, we primarily care about the client side
implementation of registries, not the server side. IMHO, the less
dependencies we have, the more reliable our core testing can be.

**Comment by pwittrock** [comment]
Can we focus on testing gcr.io + dockerhub compatibility separately from the rest of our merge-blocking tests?

**Comment by bprashanth** [comment]
I care less about compatibility with a specific registry and more about noticing when the daemon messes up asking for a given layer, or for a new image hash, or locks up getting 1 layer etc. I don't think a controlled environment will trigger all such conditions, and it's definitely not what customers will do.

**Comment by yujuhong** [comment]
We need to test `docker pull` to some extent, whether it be in a separate cluster or in the regular e2e. 
Since we don't care about what registry (gcr.io or dockerhub) we're testing, and we actually don't want to test those remote registries testing against a local registry makes sense.

**Comment by pwittrock** [comment]
I agree these are good things to test.  Can we test them in a way that doesn't block our merge process when due to a remote infrastructure failure?

**Comment by bprashanth** [comment]
That's what this issue is about? (Serve e2e images from local docker registry)

**Comment by pwittrock** [comment]
Got it, I miss interpreted a previous comment to mean we needed to test both a local repo and against remote repos.

**Comment by vishh** [comment]
Can we stress test the daemon in a separate test suite? It is much simpler
to stress test docker daemon wrt. image pulls as part of the node test
suite.

If we want to have a test setup that matches customer's production
clusters, why not have a dedicated test suite for that.

**Comment by bprashanth** [comment]
> If we want to have a test setup that matches customer's production
clusters, why not have a dedicated test suite for that.

I disagree with this. It's one thing to have a local cache (or cache proxy) for gcr.io, and a completely different thing to not test what your customers are actually running via the defacto cluster setup. Image pulling is too big a piece to mock out, unless we think the local registry approach is flawed in some way.

**Comment by vishh** [comment]
Given that we don't have any data against the local registry option I think
it is definitely worth giving a shot!

In general I feel that we need more focussed tests that having all the
tests have a lot of dependencies.

**Comment by lavalamp** [comment]
We need to test the client side of container pulling, but not the server
side. That means that we need to actually be calling `docker pull`
*somewhere*, even if we pre-populate most images. If we test `docker pull`
once per test run instead of (number of tests) per test run, then we won't
need 5 9's from our container source.

Basically I'm saying that it's OK to cheat by mounting a PD or whatever
magic you want, *as long as you add (or leave) one test that doesn't cheat*.
