### ISSUE TITLE
Kubernetes RC wait until pod is really ready before scaling down

### ISSUE THREAD

**Issue by steve-ng** [kubernetes/kubernetes#26408]
I have a ruby on rails app on kubernetes.

Here's what I do

1. kubernetes rolling-update new_file
2. Kubernetes began to create new pods
3. When the new pods are ready, Kubernetes kills the old pod.

However, although my new pod are in ready state, they are actually still doing rails assets build/compressing. They aren't ready yet. How can I let kubernetes know that it's not ready yet?

**Comment by dims** [comment]
@steve-ng Does liveness check(s) help?

http://kubernetes.io/docs/user-guide/liveness/
http://kubernetes.io/docs/user-guide/production-pods/#liveness-and-readiness-probes-aka-health-checks

**Comment by steve-ng** [comment]
thanks, readiness probe will solve this!
