### ISSUE TITLE
Allow shared informers to set custom resync periods

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#26406]
This feature request is based on https://github.com/kubernetes/kubernetes/pull/26402

With Issue #23394 (PR #24142) resync was split into resync and relist. This gives informers the ability to set more aggressive ResyncPeriods since resync now just requeues items in the existing cache and does not make expensive network calls to API server to re-fetch all items (relist).

However, since shared informers are shared by multiple controllers, changing the existing ResyncPeriod of 12 hours to something more aggressive (1 minute?) would result in a performance hit since all controllers using shared informers would have to handle frequent resyncs, this could be problematic performance wise especially for large clusters.

Feature request: allow consumers of shared informers to be able to either set their own resync periods, or opt in to a faster resync period. That way they get the benefit of using a shared informer, and other consumers of the shared informer do not suffer due to shorter ResyncPeriod.

**Comment by ncdc** [comment]
I am currently working on this

**Comment by timothysc** [comment]
Only request is ample jitter across they sync intervals.

**Comment by ncdc** [comment]
In the current WIP, I'm not adding any new timers. It'll piggy-back off the existing one.

**Comment by ncdc** [comment]
Or are you if I have 2 event handlers that both want their resync period to be 5 seconds, you want jitter for each of them?

**Comment by timothysc** [comment]
jitter for each of them.  in the past a fair amount of effort has been put behind ensuring we are not syncing on the same intervals b/c it causes large spikes.

**Comment by ncdc** [comment]
As discussed on slack (without resolution yet): the code in the repo currently broadcasts each added/updated/deleted item from the shared informer's reflector to all the event handlers as soon as the item is available, and with no jitter.

**Comment by timothysc** [comment]
@ncdc I think we're going to need to refactor that.

**Comment by ncdc** [comment]
@timothysc ok, but maybe as a follow-up to my to-be PR to close out this issue? Unless it's easy to add the jitter.

**Comment by timothysc** [comment]
@ncdc sgtm.
