### ISSUE TITLE
Kubernetes openstack cloud provider - too many request per minute

### ISSUE THREAD

**Issue by AlbertoPeon** [kubernetes/kubernetes#26404]
Hi,

We are using the kubernetes Openstack cloud provider to get dynamic provisioning of Cinder volumes. While it is working, the number of requests to the Openstack nova API per minute is pretty high. ( Around `(10 * number of masters and nodes) / minute`). From what we could see, masters and nodes both make the same number of requests.

These calls seem to be part of the normal sync loop of kubernetes, although they are a bit redundant (not much will change in a few seconds wrt to dynamic provisioning)

Is there a way to change the frequency of the Openstack API requests? What would you recommend?

As we understand, it is possible to change the frequency of the Kubernetes sync loop [`node-status-update-frequency`](https://github.com/kubernetes/kubernetes/blob/9a20ca2899b52cdf6eec53d8137f55cc3446c748/cmd/kubelet/app/options/options.go#L198) but this will eventually hamper the Kubernetes sync loop.

There is also the [`node-sync-period`](https://github.com/kubernetes/kubernetes/blob/ee2a0694b649941fc0c3be606746db041b75b91d/cmd/kube-controller-manager/app/options/options.go#L109) variable, which seems to be exactly what we need. However it's only a master's setting, so it won't really help us.

**Comment by dims** [comment]
@AlbertoPeon Do you see failures on Nova/Cinder because of this?

**Comment by AlbertoPeon** [comment]
@dims We don't have so many nodes in our installation (currently we have ~15 machines, but the number is expected to grow up) to be sure how bad it is, but we can already see a peak of load in the nova servers.

IMHO, it's worrying the fact that there is no need for this frequency of calls (as the information is not very likely to change)

**Comment by dims** [comment]
@AlbertoPeon - agree. was trying to figure out where things should be cached.. sounds like this would be changes in the code that calls Nova/Cinder. But guessing that these calls are being made from many master/nodes at the same time and is tough to introduce a cache. right?

**Comment by kovvik** [comment]
Any progress with it? We have the same problem, pretty much Cinder API request  (couple hundreds/min) with 6 nodes and 3 volumes.

**Comment by jamiehannaford** [comment]
What types of requests are being sent to the Nova/Cinder APIs? GET calls which check the status of the create operation? I can't seem to find the place in the codebase which does that, the chatter to OpenStack seems fairly minimal: 

https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/cinder/attacher.go#L88
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L65
https://github.com/rackspace/gophercloud/blob/master/openstack/compute/v2/extensions/volumeattach/requests.go#L57

**Comment by mikebryant** [comment]
This call happens every time it tries to attach, or detach a volume, it's called multiple times during the reconciliation loop - and it gets a list of every volume in the openstack project.

https://github.com/kubernetes/kubernetes/blob/8ecc256e88317d6c61ff7834fb8e19af11b012c2/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L118

**Comment by jamiehannaford** [comment]
Looking at the code, it seems we're using volume names and UUIDs interchangeably. Perhaps we can refactor to only use UUIDs, meaning that we can bypass the list lookup. This would mean 1 HTTP call per create/delete operation, as opposed to however many paginated collections of volumes there are in an OpenStack project. 

The only operation I see which accepts a `volumeName` arg is `DeleteVolume`, which it passes on to gophercloud [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L216). But since the SDK only accepts UUIDs the arg might not really be a name  at all, so hopefully there's no backwards incompatibility issues.

**Comment by dims** [comment]
looks like the referenced PR has merged

/assign
