### ISSUE TITLE
CrashLoopBackOff - Galera Replication for MySQL on Kubernete

### ISSUE THREAD

**Issue by Simon-lush** [kubernetes/kubernetes#26409]
I have used the mysql-galera example supplied in this repo by following the instructions in it's readme, but am having an issue where pxc-node2 and pxc-node3 repeatedly restart until they get stuck in a CrashLoopBackOff status.

**Comment by dims** [comment]
@Simon-lush : does `kubectl describe pod pxc-node2` show any information? There are a few more tips here http://kubernetes.io/docs/user-guide/introspection-and-debugging/

**Comment by bprashanth** [comment]
Deploying galera is a little tricky. Unfortunately if you start them all up at the same time with the wrong gcomm string, members might start crashing and require human intervention. To help with situations like this we developed petset (in 1.3 and head). You can find petset galera example here:

**Comment by dims** [comment]
This one right @bprashanth? 
https://github.com/kubernetes/kubernetes/pull/25848/commits/d57575762b8da8d925db931675eda6bacd12c293#diff-b4499bc7dee379adfbd1c0e2586760c2R1

**Comment by bprashanth** [comment]
On a phone and hit send to soon. https://github.com/kubernetes/contrib/tree/master/pets/mysql/galera

Note if you're actually going to try it right now with HEAD, there's a DNS bug that I'm fixing: https://github.com/kubernetes/kubernetes/pull/26393

**Comment by bprashanth** [comment]
@dims checked in now, works modulo bugs

**Comment by dims** [comment]
@bprashanth yay! :)

**Comment by erictune** [comment]
Assuming this fixed it for the OP since not comments in months.
