### ISSUE TITLE
Build infrastructure: Eliminating flakes at the source.  

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#26420]
So I ran a number of experiments locally trying to reproduce a number of test flakes in the registry.

When running 100's of iterations I had 0 failures. So I decided to try testing to see what happens when I do too many tests in parallel. Using a simple script:

```
#!/bin/sh

for i in {1..20}
do
    go test -timeout 120s k8s.io/kubernetes/pkg/registry/generic/registry &
done
```

I can essentially peg my cpu, hit swap, and cause timeouts. In general, I think a lot of these flakes are due to running too many concurrent jobs. Ideally, we should use kubernetes to build kubernetes, monitor resource usage, and quarantine each build+test.  Our build and test mechanics are far to resource intensive and we should move to try and reduce the load as well. 

/cc @kubernetes/sig-testing

**Comment by dchen1107** [comment]
This issue is arguably a flake or enhancement, but @timothysc I agree with you that some of the flakes are due to the load on the test machine.

**Comment by ixdy** [comment]
I'm trying to figure out how to remedy this.

Looking at Jenkins, we don't appear to be swapping, so I don't think we're being memory-limited.

We could play with Docker resource limits, but I don't know how much that will help - we should theoretically already be sharing CPU equally among the various containers.

We might be hindered by the somewhat old kernel we're using (3.16), as evidenced by `docker info`:
```
WARNING: No memory limit support
WARNING: No swap limit support
```

though I'm not sure if that's relevant.

**Comment by ixdy** [comment]
(we're also still using a pretty old version of docker - 1.9.1.)

**Comment by fejta** [comment]
FYI I have the post-commit cpu intensive jobs (build/unit/integration) down to a single executor per VM. I'm now doing the same with the pre-commit PR jobs.

**Comment by timothysc** [comment]
@fejta awesome I think that should help reduce the non-reproducible flakes.

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/pull/143 moved our pr and heavy agents to 1 executor per VM (currently 8 cores, @spxtr considering moving to 16 or 32). Light agents currently configured to 10 executors per 8 core instance

**Comment by fejta** [comment]
Let's call this done for the time being. Please reactivate if you see similar flakes in the future!
