### ISSUE TITLE
kubectl exec doesn't return command exit code

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#26424]
```sh
$ kubectl run --image=busybox sleep -- /bin/sh -c "sleep 1000"
$ kubectl exec -it sleep-548116132-nc8zh -- /bin/sh -c "exit 5"
$ echo $?
1
```

The last line should be 5.

**Comment by dims** [comment]
@sttts i am trying kubectl 1.2.4 and i see

```
$ ./kubectl exec -it sleep-548116132-yf6wd -- /bin/sh -c "exit 5"
error: error executing remote command: error executing command in container: Error executing in Docker Container: 5
```

**Comment by sttts** [comment]
@dims that's right. But the return code in the shell of the whole command is 1, compare `$?`.

**Comment by dims** [comment]
@sttts ack, just making sure we are seeing the same thing :)

**Comment by sttts** [comment]
Haven't looked into the code yet. Not sure cobra supports that.

**Comment by dims** [comment]
@sttts looks like kubelet itself is treating exit code and the error stream as one thing. This will take some non-trivial work i think

**Comment by sttts** [comment]
I don't want to introduce another stream for the return code only. I would propose to switch the error stream protocol to json, e.g. `{message: "the old message string", code: 42}`. Looking at https://github.com/kubernetes/kubernetes/pull/25273 for resize events, it seems to be a good moment to add this with protocol v3.

Opinions @dims @ncdc ?

**Comment by dims** [comment]
@sttts - just for error stream. yes, i think that would be good!

**Comment by ncdc** [comment]
Yes that's what I had been thinking as well.

**Comment by ncdc** [comment]
Do you want to bundle this in with my terminal resizing pull, or try to
maybe do it right set it merges?

**Comment by sttts** [comment]
@ncdc working on it right now. Makes sense to put that on-top of your PR.

**Comment by dims** [comment]
Looks like PR #26541 is close to merging.

**Comment by sttts** [comment]
Waiting for #25273 to go in.

**Comment by VojtechVitek** [comment]
`--attach=true --restart=Never` returns with the pod's exit code :)
