### ISSUE TITLE
Swagger API: invalid schema v1.FinalizerName 

### ISSUE THREAD

**Issue by Project0** [kubernetes/kubernetes#26434]
v1.FinalizerName seems to be invalid/incomplete in the swagger spec, its assumes an string, but properties is an empty object in definition. 
This brokes the usage of listNamespace.

> Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class io.swagger.client.model.V1FinalizerName] from String value ('kubernetes'); no single-String constructor/factory method
>  at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@5be6e01c; line: 19, column: 11](through reference chain: io.swagger.client.model.V1NamespaceList["items"]->java.util.ArrayList[0]->io.swagger.client.model.V1Namespace["spec"]->io.swagger.client.model.V1NamespaceSpec["finalizers"]->java.util.ArrayList[0])

**Comment by dims** [comment]
Guess its one of those things limited by the expressiveness of swagger. Here's the intent:
https://github.com/kubernetes/kubernetes/blob/4db3cc7e5ef74aacd7609a90cc362b8b4eab1a98/docs/design/namespaces.md#finalizers

cc @kubernetes/sig-api-machinery

**Comment by nikhiljindal** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/25716
