### ISSUE TITLE
container name should be optional in pod manifest

### ISSUE THREAD

**Issue by proppy** [kubernetes/kubernetes#2643]
and inferred from the pod name and suffixed by the image

**Comment by bgrant0607** [comment]
Container name could be defaulted from the image name, which would eliminate a line of configuration.

**Comment by thockin** [comment]
note that container name validation will reject names that are valid image
names.  But we can mangle and uniquify if it makes life simpler.   Or we
could default to names like "0", "1", "2"...

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by thockin** [comment]
This would be a strictly breaking change.  I am not sure we can safely make this change.

**Comment by bgrant0607** [comment]
I no longer believe that setting some fields based on values from other fields by default is a good idea, anyway.
