### ISSUE TITLE
Update ingress docs

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#26447]
With feedback from https://code.google.com/p/google-cloud-sdk/issues/detail?id=838

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/26579

**Comment by goltermann** [comment]
bringing a few P2 doc bugs back in the 1.3 milestone

**Comment by bprashanth** [comment]
This isn't needed for 1.3, I'm updating the docs anyway in https://github.com/kubernetes/contrib/pull/1324 but contrib moves independent of main tree anyway

**Comment by cmluciano** [comment]
I think this can be closed @bprashanth
