### ISSUE TITLE
Enabling TLS on the kubernetes docker local development.

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kubernetes#26444]
Powering through the code here: https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/static-pods/master.json

I see references to TLS certification / ca files / etc.

I've tried for the life of me to get this working by going through http://kubernetes.io/docs/admin/authentication/

and applying it to:

http://kubernetes.io/docs/getting-started-guides/docker/

But I get a

```
--client-ca-file unknown flag
```

Error when launching the `kubelet`.

It is possible to get some guidance on how to enable the local docker kubernetes development to use tls certificates?

**Comment by dims** [comment]
I count 6 flags, not all the command lines have all the options (by design):
```
root-ca-file
client-ca-file
tls-cert-file
tls-private-key-file
service-account-key-file
service-account-private-key-file
```

Magnum has good examples of securing the services:
http://codesearch.openstack.org/?q=client-ca-file%7Ctls-cert-file%7Ctls-private-key-file%7Croot-ca-file%7Cservice-account-private-key-file%7Cservice-account-key-file&i=nope&files=magnum%2Ftemplates%2Fkubernetes%2Ffragments%2F.*&repos=

**Comment by cdrage** [comment]
Yeah... by design you're unable to pass `client-ca-file` to the hyperkube and hence not being able to enable TLS :(

**Comment by cdrage** [comment]
Unless the changes are to the apiserver manifest file?

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
I'm guessing you own minikube (which is what the above getting-started-guide link now redirects me to)

**Comment by cdrage** [comment]
@spiffxp Docker local development has been deprecated, so I'm going to close this issue as it's been changed / redirected to Minikube as an alternative.
