### ISSUE TITLE
limit usage of flags in libraries

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#2644]
From #2437:

thockin: Frankly I find the idea of libs binding flags to be suspect from the beginning, doubly so if that imposes particular flag libs on the caller. Instinct would lead me to say "just fill a struct and let the main pkg define flags". Is that a non-starter?

smarterclayton: The point of this was to prevent everyone from inventing their own flags. Both major flag libs are compatible.

thockin: I get the point, but IMO flags are strictly the domain of the app. we use flags-in-libs pervasively in google and it's sort of a nightmare, in my opinion, though reasonable people disagree. Without flag namespacing, it's a slippery slope, and I don't want most of our code following this pattern.

thockin: As an example of why I dislike it: skydns uses our BindFlags... and they end up with a flag called -master. That is a thoroughly UNHELPFUL flag name. It should have been --kubernetes-master or something. We can not, in a library, predict what flag names will make sense in an app, and we should not pretend we can.

smarterclayton: The counter argument here is that having 29 different flag names for the same security params is worse.  This was mostly targeted at that.  And if master doesn't have consistent meaning across our commands (kubelet, proxy, client), that's just as confusing

thockin: Just because they CAN be different doesn't mean they WILL be. simply being able to prefix them all with "k8s-" is "different" but not substantively so.

As a compromise, I could live with a lib that exposed the common flags and produced a set of common structs or an interface which was mandatory for any client binary inside our own codebase, but optional for clients like skydns. Bonus points if the flag names could be trivially prefixed, so that this lib was usable by skydns in a sane way.

smarterclayton: That makes sense to me.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc
