### ISSUE TITLE
unit test flake - TestWatchContextCancel - watcher_test.go:196: cancelling context shouldn't return any error. Err: <nil>

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#26452]
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26397/kubernetes-pull-test-unit-integration/28223/

```
--- FAIL: TestWatchContextCancel (0.26s)
    watcher_test.go:196: cancelling context shouldn't return any error. Err: <nil>
```

cc @hongchaodeng

**Comment by hongchaodeng** [comment]
This happened due to grpc issue. grpc somehow forgot sending context cancelled error back.
It's fixed in https://github.com/grpc/grpc-go/commit/9ac074585f926c8506b6351bfdc396d2b19b1cb1
Bumping up etcd dep should fix it.
