### ISSUE TITLE
Upgrade GCI image with docker 1.11.2

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#26455]
Now GCE master node switch to GCI image by default, and all worker nodes on GCE are using the latest containervm image with docker 1.11.1, which makes our master node's docker version mismatches with rest of clusters. Please cut a new release and enable the tests. 

cc/ @kubernetes/goog-image

**Comment by dchen1107** [comment]
cc/ @yinghan

**Comment by dchen1107** [comment]
cc/ @roberthbailey

**Comment by roberthbailey** [comment]
@kubernetes/goog-image

**Comment by wonderfly** [comment]
@adityakali had made a GCI image with docker 1.11.1 and it's been under some testing. Should be able to cut a release soon.

**Comment by goltermann** [comment]
This is a P0 that's 10d old.  What's the latest status?

**Comment by adityakali** [comment]
There is a preview image under testing. The release image is expected to be available this week.

**Comment by dchen1107** [comment]
ping...

Can we have the image with docker 1.11.2 ready for testing today? Thanks!

**Comment by adityakali** [comment]
I am building one now.
