### ISSUE TITLE
Error from server: error when creating "foo.json": pods "blahblah" is forbidden: service account default/default was not found, retry after the service account is created

### ISSUE THREAD

**Issue by dcbw** [kubernetes/kubernetes#26457]
At some point in the past couple weeks hack/local-up-cluster.sh began failing to create pods with this message.

**Comment by dcbw** [comment]
cf7a3475f37c2e4ae5faac25dc7ae7eb84734483 is the first bad commit
commit cf7a3475f37c2e4ae5faac25dc7ae7eb84734483
Author: mqliang <mqliang.zju@gmail.com>
Date:   Mon May 16 18:57:44 2016 +0800

    Don't allow node controller to allocate into service CIDR range

:040000 040000 6f32fab91bd722869310c0a59416849dca58b762 0595a463995e20c6be5c9e673aca02b075b76287 M	cluster
:040000 040000 d338ac8d6408fb6eb33307ece6944dba46dbfaad 25fb196448eed1afb1e925ff41a73cf1f8e9b8da M	cmd
:040000 040000 b740cbcaf7deacaa17f361fb3943483945aced52 a7bbba031b0625176695f0374cc7fc8c6440d631 M	contrib
:040000 040000 cb4d2967edc61887eb6b7b21a4deba482b4c8f4a 36a43beb307dc8cdf34001be7de374eabd23c760 M	pkg

**Comment by dcbw** [comment]
cc @davidopp

**Comment by davidopp** [comment]
Thanks for reporting. Is this the same or different from the problem you found with 
https://github.com/kubernetes/kubernetes/pull/26197/
?

**Comment by dcbw** [comment]
@davidopp it's a different problem.  Once I figured out how to fix #26197 I ran into this one.

**Comment by dcbw** [comment]
This may actually be fixed by the recently merged 08385b2c5fabb033b202a9fc79b72950856c3ae6.  I'll double-check and close if it is.

**Comment by dcbw** [comment]
Yeah, should be fixed by #26054.
