### ISSUE TITLE
How does the PR template release-note label system work?

### ISSUE THREAD

**Issue by mbruzek** [kubernetes/kubernetes#26450]
I created #26446 with 
```
release-note-none
```
from the start but the k8s-merge-robot added  release-note-label-needed  to the PR.

I have read the PR process: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes and I don't see where the "release-note-label-needed" tag comes off the PR for ones requesting that status.

Please clarify.

**Comment by yujuhong** [comment]
Someone needs to apply the release-note-* label to the PR, and non-maintainers don't have the permission to apply the labels AFAIK.
The merge-bot doesn't know how to parse your comment and apply the label. You'll need to wait until the reviewer to do it manually for you.

**Comment by mbruzek** [comment]
Ok thanks!
