### ISSUE TITLE
Kubernetes on Azure docs 

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#26468]
Google search on "Kubernetes Azure" gives:

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/azure.md

This links to

http://kubernetes.io/docs/getting-started-guides/azure/

which gives a 404.

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/azure/README.md seems specific to CoreOS.

Where are the normative instructions for running Kubernetes on Azure?

**Comment by colemickens** [comment]
See: https://github.com/kubernetes/kubernetes.github.io/pull/149

**Comment by mikedanese** [comment]
Looks like this is in the wrong repo
