### ISSUE TITLE
Add docker performance tests for image pulling 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#26464]
Our docker 1.11.X validation stats (https://github.com/kubernetes/kubernetes/issues/23397) show overall performance improvements, but lack the performance measurement with docker pull operation. After upgrading to docker 1.11.1, the issue https://github.com/kubernetes/kubernetes/pull/25784#issuecomment-221699143, https://github.com/kubernetes/kubernetes/issues/25277  are not observed. 

I did experiment against both docker 1.9.1 and docker 1.11.1 on docker pulling, and the overall performance on docker 1.11.1 is way better than 1.9.1, but we should include those tests to our docker performance validation test suite. The below are the steps I did: 

IMAGES="gcr.io/google_containers/iperf:e2e 1>/dev/null & time for i in gcr.io/google_containers/busybox gcr.io/google_containers/busybox:1.24 gcr.io/google_containers/dnsutils:e2e gcr.io/google_containers/eptest:0.1 gcr.io/google_containers/fakegitserver:0.1 gcr.io/google_containers/hostexec:1.2 gcr.io/google_containers/iperf:e2e gcr.io/google_containers/jessie-dnsutils:e2e gcr.io/google_containers/liveness:e2e gcr.io/google_containers/mounttest:0.2 gcr.io/google_containers/mounttest:0.5 gcr.io/google_containers/mounttest:0.6 gcr.io/google_containers/mounttest-user:0.3 gcr.io/google_containers/netexec:1.4 gcr.io/google_containers/netexec:1.5 gcr.io/google_containers/nettest:1.7 gcr.io/google_containers/nettest:1.8 gcr.io/google_containers/nginx:1.7.9 gcr.io/google_containers/nginx-slim:0.5 gcr.io/google_containers/n-way-http:1.0 gcr.io/google_containers/pause:2.0 gcr.io/google_containers/pause-amd64:3.0 gcr.io/google_containers/porter:cd5cb5791ebaa8641955f0e8c2a9bed669b1eaab gcr.io/google_containers/portforwardtester:1.0 gcr.io/google_containers/redis:e2e gcr.io/google_containers/resource_consumer:beta2 gcr.io/google_containers/serve_hostname:v1.4 gcr.io/google_containers/servicelb:0.1 gcr.io/google_containers/test-webserver:e2e gcr.io/google_containers/ubuntu:14.04 gcr.io/google_containers/update-demo:kitten gcr.io/google_containers/update-demo:nautilus gcr.io/google_containers/volume-ceph:0.1 gcr.io/google_containers/volume-gluster:0.2 gcr.io/google_containers/volume-iscsi:0.1 gcr.io/google_containers/volume-nfs:0.6 gcr.io/google_containers/volume-rbd:0.1 gcr.io/google_samples/gb-redisslave:v1" 

1) time the command: for i in $IMAGES; do echo $(date '+%X') pulling $i; docker pull $i 1>/dev/null; done;

3) See the impact of LIST operation to docker pull 

for i in 1..1000; do docker ps -a 1>/dev/null; sleep 2; done & time for i in $IMAGES; do echo $(date '+%X') pulling $i; docker pull $i 1>/dev/null; done;

3) See the impact of CREATION operation to docker pull

for i in {1..1000}; do docker run busybox sleep 1; sleep 1; done & time for i in $IMAGES; do echo $(date '+%X') pulling $i; docker pull $i 1>/dev/null; done;

4) See the impact of DELETE operation to docker pull

for i in {1..1000}; do docker run --rm busybox sleep 1; sleep 1; done & time for i in $IMAGES; do echo $(date '+%X') pulling $i; docker pull $i 1>/dev/null; done;

5) See the impact of concurrent pulling:

IMAGES2=... ===> another set of images with some dup. 

for i in $IMAGES2; do docker pull $i 1>/dev/null; done & time for i in $IMAGES; do echo $(date '+%X') pulling $i; docker pull $i 1>/dev/null; done;

@liangchenye Can we include all above tests to the docker performance validation test suite? 

cc/ @kubernetes/goog-node @timothysc

**Comment by yujuhong** [comment]
We can add general image pulling tests and it's good in general, but I just wanted to point out that it's hard to reproduce flakes we encountered in the jenkins builds. 

I've written a small go program using the docker-engine api client that we use in the kubelet to pull image concurrently. It pulled all the e2e test images and never failed in the 3 hours of the test.

**Comment by dchen1107** [comment]
Yes, I didn't expect this one reproduce all flakes in the jenkins jobs caused by slow pulling. But making this test automated, we can 

* Easily identify the performance regression from docker pull, and report the issue to docker as soon as possible.
* Easily rule out the docker issue and found the root cause in other area.

**Comment by yujuhong** [comment]
If we want to test for performance regression, it'd make sense to set up a local registry. Otherwise, we'd also be testing the registry itself.

**Comment by yujuhong** [comment]
We should repurpose this bug to test pulling images in CRI runtimes.
