### ISSUE TITLE
Some kubectl errors are hidden incorrectly 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#26466]
https://github.com/kubernetes/kubernetes/issues/26425#issuecomment-222258484:

> Found a hidden issue here: if the output flag `-o` is specified, the "resource not found" error will not be exposed. 
> 
> ``` console
> $ kubectl get pods abc 
> Error from server: pods "abc" not found
> $ kubectl get pods abc -o name
> <no error>
> $ kubectl get pods abc -o template --template='{{if (exists . "status" "containerStatuses")}}{{range .status.containerStatuses}}{{if (and (eq .name "update-demo") (exists . "state" "running"))}}true{{end}}{{end}}{{end}}'
> <no error>
> ```

Why? In https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/get.go, the errors returned by `r.Visit` are appended to `allErrs` but then `return printer.PrintObj(obj, out)` is called and `allErrs` are dropped silently.

Also, the error returned by `sorting, err := cmd.Flags().GetString("sort-by")` isn't handled/returned either. 

Some of these are related to the changes made in #23673. This may happen to other kubectl commands too. 

cc @metral @kubernetes/kubectl

**Comment by metral** [comment]
Not at computer, but there's a PR in the works to refactor and flatten the aggregated errors in https://github.com/kubernetes/kubernetes/pull/26242. That said, the total changes I added in https://github.com/kubernetes/kubernetes/pull/23673 and https://github.com/kubernetes/kubernetes/pull/26242 combined doesn't change get.go too drastically to examine. 

I must not be handling one of the error cases accordingly. I most likely won't be able to get to this til next week but happy to examine it then

**Comment by janetkuo** [comment]
@metral thanks!

**Comment by metral** [comment]
> Found a hidden issue here: if the output flag -o is specified, the "resource not found" error will not be exposed.

> $ kubectl get pods abc 
Error from server: pods "abc" not found
$ kubectl get pods abc -o name
<no error>
$ kubectl get pods abc -o template --template='{{if (exists . "status" "containerStatuses")}}{{range .status.containerStatuses}}{{if (and (eq .name "update-demo") (exists . "state" "running"))}}true{{end}}{{end}}{{end}}'
<no error>
Why? In https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/get.go, the errors returned by r.Visit are appended to allErrs but then return printer.PrintObj(obj, out) is called and allErrs are dropped silently.

I've gone ahead and created a PR to fix these issues in https://github.com/kubernetes/kubernetes/pull/26686


> Also, the error returned by sorting, err := cmd.Flags().GetString("sort-by") isn't handled/returned either.

Errors for `sorting, err := cmd.Flags().GetString("sort-by")` were never originally handled - refer to [cmd/get.go from v1.2.0](https://github.com/kubernetes/kubernetes/blob/v1.2.0/pkg/kubectl/cmd/get.go#L248)

**Comment by asalkeld** [comment]
please close the issue, PR is merged.

**Comment by AdoHe** [comment]
@pwittrock feel free to close this one, please.
