### ISSUE TITLE
Kube-ui dashboard is blank

### ISSUE THREAD

**Issue by jonathan-kosgei** [kubernetes/kubernetes#26479]
Hi, I'm following the ubuntu/calico cluster setup at http://kubernetes.github.io/docs/getting-started-guides/ubuntu-calico/. 

I manually created the kube-ui service, however when I browse to the url there's nothing to show, the dashboard is there but I don't see any of the nodes/pods/services etc that I've setup.

**Comment by luxas** [comment]
kube-ui is deprecated in favor for https://github.com/kubernetes/dashboard.
Please deploy that one instead.
