### ISSUE TITLE
The service without specified port should be supported

### ISSUE THREAD

**Issue by qq690388648** [kubernetes/kubernetes#26471]
In some cases, just like the ApplicationMaster of yarn, the service may listen on a random port. That means we can not use kubernetes's service to support these cases.
To hold these cases, I think there should be a type of service without specified ports so that all request to the service's ip can be routed to the pods ignored the port. And I think it is achievable with current iptable based kube-proxy,.

**Comment by thockin** [comment]
It is not implementable in the userspace proxy and I am not sure it is
generically implementable.  This is the same as supporting ranges #23864

**Comment by qq690388648** [comment]
It is a bit like the https://github.com/kubernetes/kubernetes/issues/23864 on function, but they have great differences on their implements, because the `iptable` does not support doing routing for port range, but it supports doing routing  ignoring ports.
