### ISSUE TITLE
Test apiserver prefix

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#26489]
#26416 removed this test. We need to continue testing this.

This wasn't about testing upgrades, the prefix has nothing to do with upgrades. It's just there so people can share etcd. We maybe don't need to double everything but we do need to make sure that keeps working.

**Comment by wojtek-t** [comment]
To be honest - I think that what we was testing before didn't give us completely any information. We didn't testing what information we are storing in etcd and where. That said, if we had a hardcoded prefix somewhere in our code, we wouldn't discover it at all, and those tests would still be passing.

We should have a test that is directly checking etcd contents. I think it should be possible to write a simple unit test for it. Will try to put something together next week.
