### ISSUE TITLE
Bind Docker to a Unix socket under upstart in kubernetes master node

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [kubernetes/kubernetes#26481]
Refer to this article(http://kubernetes.io/docs/getting-started-guides/docker-multinode/master/).
It mention about if you need a separate “bootstrap” instance of the Docker daemon and running this on a long running system, you should run the bootstrap Docker instance under something like SysV init, upstart or systemd so that it is restarted across reboots and failures. Here because I use the ubuntu 14.04, so I just want to know the upstart.I am confused how to achieve it , is just write some script under upstart folder or anything else?

**Comment by mikedanese** [comment]
cc @luxas

**Comment by spzala** [comment]
@earthIsAPrisonIfYouNotAwareItCanNotOut  @mikedanese hi, it seems like we should move this question to https://stackoverflow.com/questions/ask/advice?tags=kubernetes and close this issue? Thanks!   (ref: https://github.com/kubernetes/community/blob/master/contributors/devel/issues.md#determine-if-its-a-support-request)

**Comment by luxas** [comment]
Support for this deployment has been deprecated for a year and it has been removed, so closing

**Comment by spzala** [comment]
@luxas Thanks!!
