### ISSUE TITLE
Pod's restarting - dial unix /var/run/docker.sock:

### ISSUE THREAD

**Issue by naveensrinivasan** [kubernetes/kubernetes#26487]
I have pods that are restarting often with the message  `FailedSync Error syncing pod, skipping: Get http://unix.sock/containers/json?all=1: dial unix /var/run/docker.sock: no such file or directory`. 

This is running on aws and the cluster was setup using `kube-up.sh`. What could be wrong?

```
    Error syncing pod, skipping: failed to "KillContainer" for "jenkins"   
 with KillContainerError: "Post http://unix.sock/containers/59054ab9fa813858922a42cec3e96d4b818285ed17a0cd1787249c7da5ade67f/stop?t=30:  
 dial unix /var/run/docker.sock: no such file or directory"

```

**Comment by zhouhaibing089** [comment]
It looks like the docker daemon has been crashed, what's the logs from docker?

**Comment by xiangpengzhao** [comment]
Since there isn't enough info to debug and no more response from @naveensrinivasan, we're going to close this issue. Feel free to re-open it if you still face the issue.

@thockin
