### ISSUE TITLE
Kubelet [Serial] [Slow] [k8s.io] regular resource usage tracking resource tracking for 35 pods per node

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#26495]
This is deterministically failing only in kubernetes-e2e-gce-serial with
`Memory usage exceeding limits: node jenkins-e2e-minion-group-glrh: container "runtime"`

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-serial/1381/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-serial/1380/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-serial/1379/
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-serial/1378/
and so on.

cc/ @dchen1107 @yujuhong @vishh

**Comment by bprashanth** [comment]
Docker 1.11 probably just has a higher resource footprint (https://github.com/docker/docker/issues/21737)

**Comment by yujuhong** [comment]
We moved containerd to the docker cgroup in #26391, and the build started to fail (http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-serial/1376/)

I'll bump the memory limit now for docker 1.11.

**Comment by timstclair** [comment]
Thanks Yu-ju, this issue got lost in the noise for me.
