### ISSUE TITLE
How Webhook works, where can find the details? thanks

### ISSUE THREAD

**Issue by xiaochunyn** [kubernetes/kubernetes#26513]
1 Is webhook plugin stable?
2 How webhook works?
3 How can I use webhook and where can find detailed information.

Thank you very much!

**Comment by dims** [comment]
@xiaochunyn please see http://kubernetes.io/docs/admin/authorization/

**Comment by xiaochunyn** [comment]
@dims thank you for your answer, I have seen the page, you know the page didn't describe how webkook works clearly. Therefore, I want to know how webhook implements authorization and authentication, and the process of authorization and authentication, can you give me a detailed explanation. Thank you again!

**Comment by dims** [comment]
@xiaochunyn - For more details you have to look in the code and tests as mentioned in the page above.

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/webhook/webhook.go

**Comment by xiaochunyn** [comment]
@dims I have read "webhook.go" and related packages several days ago, I have not find how webhook works in detail, so I pulled a issue. Thank you very much.

**Comment by nikhiljindal** [comment]
cc @cjcullen @erictune

**Comment by xiangpengzhao** [comment]
These questions got some more detailed answers in #26552. We are going to close this. If you have other similar questions, please post at stackoverflow. Thanks!

@thockin
