### ISSUE TITLE
hyperkube image is missing the 'conntrack' utility

### ISSUE THREAD

**Issue by j-vizcaino** [kubernetes/kubernetes#26515]
`kube-proxy` requires the `conntrack` binary but the binary is not available in `gcr.io/google_containers/hyperkube:v1.2.4`.

`conntrack` is provided by the `conntrack` Debian package.

**Comment by j-vizcaino** [comment]
It seems the problem has been introduced with PR #22573: the `kubernetes/cluster/images/hyperkube/Dockerfile` file is missing `conntrack` in the `apt-get install` command

**Comment by j-vizcaino** [comment]
Thank you for the fix!
Is this planned for the next 1.2.x release?

**Comment by luxas** [comment]
I'll be fixed with the upcoming `v1.3` release.
