### ISSUE TITLE
Node controller can evict healthy pods in large clusters few minutes after startup (failing load.go e2e test)

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#26511]
There were a couple of flakes, that finished with the error like this one:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:182 creating rc
load-small-rc-4196 Expected error: <*errors.errorString | 0xc8217c0eb0>: { s: "Number of reported pods
for load-small-rc-4196 changed: 4 vs 5", } Number of reported pods for load-small-rc-4196 changed: 4 vs
5 not to have occurred
```

This particular error come from:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-kubemark-gce-scale/1183/

**Comment by wojtek-t** [comment]
I did some debugging of this particular run, and here are some logs from this run:

- Initially replication-controller successfully creates all 5 pods:
```
I0528 14:54:35.067756    3570 event.go:216] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"e2e-tests-load-30-nodepods-5-8ccib", Name:"load-small-rc-4196", UID:"17b7e       ecf-24e4-11e6-9843-42010af00018", APIVersion:"v1", ResourceVersion:"21805", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: load-small-rc-4196-l43yt
I0528 14:54:35.067892    3570 event.go:216] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"e2e-tests-load-30-nodepods-5-8ccib", Name:"load-small-rc-4196", UID:"17b7e       ecf-24e4-11e6-9843-42010af00018", APIVersion:"v1", ResourceVersion:"21805", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: load-small-rc-4196-yvz5k
I0528 14:54:35.067988    3570 event.go:216] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"e2e-tests-load-30-nodepods-5-8ccib", Name:"load-small-rc-4196", UID:"17b7e       ecf-24e4-11e6-9843-42010af00018", APIVersion:"v1", ResourceVersion:"21805", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: load-small-rc-4196-ngemx
I0528 14:54:35.068034    3570 event.go:216] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"e2e-tests-load-30-nodepods-5-8ccib", Name:"load-small-rc-4196", UID:"17b7e       ecf-24e4-11e6-9843-42010af00018", APIVersion:"v1", ResourceVersion:"21805", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: load-small-rc-4196-zyeft
I0528 14:54:35.068065    3570 event.go:216] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"e2e-tests-load-30-nodepods-5-8ccib", Name:"load-small-rc-4196", UID:"17b7e       ecf-24e4-11e6-9843-42010af00018", APIVersion:"v1", ResourceVersion:"21805", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: load-small-rc-4196-ja76p
```

From now, let's focus on "load-small-rc-4196-ngemx" with logs.

- All of them are successfully picked up by scheduler and scheduled, e.g.:
```
I0528 14:54:35.152824    3517 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"e2e-tests-load-30-nodepods-5-8ccib", Name:"load-small-rc-4196-ngemx", UID:"17b91e49-24e4-11e       6-9843-42010af00018", APIVersion:"v1", ResourceVersion:"21812", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned load-small-rc-4196-ngemx to 10.180.9.78
```

- All of them are the successfully picked up by hollow-kubelets, and those hollow-kubelets start posting statuses for them, e.g.:
```
I0528 14:54:35.156833    3518 handlers.go:165] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-5-8ccib/pods/load-small-rc-4196-ngemx: (1.007673ms) 200 [[kubemark/v1.3.0 (linux/amd64) kub    ernetes/e543bd6] 104.197.125.91:50474]
I0528 14:54:35.168476    3518 handlers.go:165] PUT /api/v1/namespaces/e2e-tests-load-30-nodepods-5-8ccib/pods/load-small-rc-4196-ngemx/status: (10.275287ms) 200 [[kubemark/v1.3.0 (linux/am    d64) kubernetes/e543bd6] 104.197.125.91:50474]
...
I0528 14:54:36.497228    3518 handlers.go:165] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-5-8ccib/pods/load-small-rc-4196-ngemx: (1.101961ms) 200 [[kubemark/v1.3.0 (linux/amd64) kub    ernetes/e543bd6] 104.197.125.91:50474]
I0528 14:54:36.519892    3518 handlers.go:165] PUT /api/v1/namespaces/e2e-tests-load-30-nodepods-5-8ccib/pods/load-small-rc-4196-ngemx/status: (16.442561ms) 200 [[kubemark/v1.3.0 (linux/am    d64) kubernetes/e543bd6] 104.197.125.91:50474]
```

And then, something super strange happens - node-controller is trying to force deletion of this pod:
- logs from apiserver:
```
I0528 14:54:44.939666    3518 handlers.go:165] DELETE /api/v1/namespaces/e2e-tests-load-30-nodepods-5-8ccib/pods/load-small-rc-4196-ngemx: (32.679341ms) 200 [[kube-controller-manager/v1.3.    0 (linux/amd64) kubernetes/e543bd6/node-controller] 127.0.0.1:48636]
...
I0528 14:54:45.057839    3518 handlers.go:165] DELETE /api/v1/namespaces/e2e-tests-load-30-nodepods-5-8ccib/pods/load-small-rc-4196-ngemx: (796.358µs) 404 [[kube-controller-manager/v1.3.0     (linux/amd64) kubernetes/e543bd6/node-controller] 127.0.0.1:48636]
```
- logs from node-controller:
```
E0528 14:54:45.058099    3570 nodecontroller.go:467] pods "load-small-rc-4196-ngemx" not found
```

I initially thought that this may be slow watch in apiserver/etcd, but that's not the case - those pods are scheduled & started on kubelets (those operations are also based on watch). So this is not watch in general.

For me it really seems like a problem with "node-controller".
@gmarek - I'm assigning to you, but I'm happy to sit with you and debug it further together with you.

@gmarek @davidopp

**Comment by wojtek-t** [comment]
It seems that in this particula run, node-controller removed 1855 different pods within the first 7 minutes of the test, and then stopped removing and the test continued to working smoothly after that.

It clear seems that we have some problems on startup here.

**Comment by wojtek-t** [comment]
We already have some hypothesis with @gmarek 

It basically seems that allocateOrOccupyCIDR function in NodeController is long. Since this is called synchronously on "ADD node" watch events, this means that we are not processing the next watch event before the previous one is processed.

If that's true (@gmarek will confirm it), then we are simply removing pods that were scheduled on nodes, that we still didn't process "ADD" event for.
That also explains, why after some time, we no longer remove any pods.

**Comment by gmarek** [comment]
It seems that assigning single CIDR to a Node can take ~0.3s. Virtually all time is used by sending an update and (possibly) re-getting the Node. I'm going to send a PR that moves this logic to the go routine.

**Comment by wojtek-t** [comment]
It seems that we fully understand it now.

The plan to fix it is:
1. change the handler function in the informer to just queue things to process
2. have few workers that will be processing them in background

**Comment by gmarek** [comment]
Extending what @wojtek-t wrote - the reason behind this problem is client-side throttling in the controller. The fix @wojtek-t mentioned is only temporary and probably wouldn't be needed if we had a backpreassure mechanism. @timothysc

**Comment by wojtek-t** [comment]
Not really - client-side throttling become a problem when we actually just make the handle function start the go-routine with the current handler function. Currently, we don't have problem with client-throttling. So the problem now is just that the simplest possible fix doesn't work.
