### ISSUE TITLE
Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: Failed to find object

### ISSUE THREAD

**Issue by ladlavj** [kubernetes/kubernetes#26527]
This problem still persist, I am running kubelet v1.2.4 on `CoreOS 1053.2.0`, I refereed prior open/closed issues #20146 , #13556 and #15537.

I have Openstack setup with DB2.
I get API calls on openstack which has encoded characters `name=%5Enode%24` which causing issue. 

```
INFO nova.osapi_compute.wsgi.server [req-_____ ______ ____ - - -] 1.2.3.4 "GET /v2/_____/servers/detail?name=%5Enode%24&status=ACTIVE HTTP/1.1" status: 200 len: 187 time: 0.0362272
```

I tried using curl too, that didn't work but; it did after removing %5E and %24 `name=node`.
Possibility can be that regex doesn't work for DB2 database?

**Comment by zhouhaibing089** [comment]
`%5E=^` and `%24=$`, and according to the code here: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L325, it seems the result is expected.

AFAIK, when you just provide the parameters as just `node`, `anode, nodeb` will be all returned if there is. I personally feel this issue comes from the openstack side, which version are you using?

**Comment by zhouhaibing089** [comment]
Looks like it is related with DB2 according to the documentation here: http://developer.openstack.org/api-ref-compute-v2.1.html#listServers

> Filters the response by a server name, as a string.

> You can use regular expressions in the query. For example, the ?name=bob regular expression returns both bob and bobb. If you must match on only bob, you can use a regular expression that matches the syntax of the underlying database server that is implemented for Compute, such as MySQL or PostgreSQL.

Does DB2 supports this regular expression for query?

**Comment by ladlavj** [comment]
I am running openstack Kilo. not sure that db2 supports regex same as mysql, but it does. I am not sure about `^` and `$`

I found something here http://stackoverflow.com/questions/32603822/use-regexp-substr-in-db2

	
REGEXP_SUBSTR does not exist in DB2! The way to use regular expressions is with xquery (I already answered that question). What you can do is to wrap the xquery into a UDF in order to have the function you said. Also, you can install a set of stored procedure that provide regular expressions (look in DeveloperWorks) – AngocA

does that mean kubelet can not use cloud provider openstack when it has database DB2 ?

**Comment by zhouhaibing089** [comment]
> does that mean kubelet can not use cloud provider openstack when it has database DB2 ?

Yes, you could try to fix this.

**Comment by dims** [comment]
/close

Looks like this is a wont-fix as there is no way to recreate the DB2 environment easily. please free to reopen if you have an environment to recreate the problem.
