### ISSUE TITLE
Update API Reference script

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubernetes#26526]
Hi, 

there is a minor bug in the [hack/update-api-reference-docs.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/update-api-reference-docs.sh) script or at least some inconsistency. When I run the update script white spaces are ignores with the `-w`option [see line 98](https://github.com/kubernetes/kubernetes/blob/master/hack/update-api-reference-docs.sh#L98) but in the [verify script](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-api-reference-docs.sh#L38) white spaces are not ignored. So for consistency we should either ignore white spaces at all or we should diff white spaces (what I would prefer).

I wanted to discuss  with you the different options before providing a pull request because it's very confusing when you run the update script and afterwards the verify script tells you there are diffs.

Thanks!

**Comment by ixdy** [comment]
cc @caesarxuchao @nikhiljindal @spxtr
