### ISSUE TITLE
turn validation off with --validate=false

### ISSUE THREAD

**Issue by rhohubbuild** [kubernetes/kubernetes#26532]
my host OS ubuntu 16.04, i followed docs 
1)http://kubernetes.io/docs/getting-started-guides/docker/
then 
2) http://kubernetes.io/docs/getting-started-guides/docker-multinode/deployDNS/

i got error when i try this 
3) user@host:~/kubernetes$ kubectl create -f ./skydns.yaml
error validating "./skydns.yaml": error validating data: [unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object]; if you choose to ignore these errors, turn validation off with --validate=false

then i did
4) user@host:~/kubernetes$ kubectl create -f ./skydns.yaml --validate=false
replicationcontroller "kube-dns-v10" created
service "kube-dns" created

Am i going in correct way ?
if not then how to fix this issue (without using  --validate=false flag)?

**Comment by zhouhaibing089** [comment]
I meet this issue before, and it is mostly because I am using an outdated `kubectl`.

**Comment by pwittrock** [comment]
Closing this issue.  Please re-open if it has not been addressed.

**Comment by liqiang75** [comment]
i also meet this problem,but before this one ,i kubectl create another successfully,i want to know why this oappears?
