### ISSUE TITLE
reference definitions refer to ".md" URLs instead of their canonical forms

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/kubernetes#26545]
If you look at all the links in the "Definitions" sections in the Reference docs (e.g. the links in the descriptions of "type" and "clusterIP" in [ServiceSpec](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_servicespec)), the links are broken because they refer to URLs with `.md` in them.

It would be nice for those links to be turned into the correct links (which all seem to mean just replacing the ".md" with a "/").

I'm not sure what publishing tool is used to handle the docs, but it maybe needs to dig a bit deeper.

**Comment by mikedanese** [comment]
cc @johndmulhausen

**Comment by mikedanese** [comment]
Those pages don't exist anymore.
