### ISSUE TITLE
deploy HDFS cluster with kubernetes + flannel can't work

### ISSUE THREAD

**Issue by GavinSong123** [kubernetes/kubernetes#26546]
I use the Flannel network, and enable the dns service, then make the service and replication-controller templates with some ports exposed such as 8020, 50070 and so on. And the pods were provisioned by the replication-controller.

I configured the Namenode host by using Service name, for example, service name is namenode-svc, then the Namenode host is namenode-svc and fs.default.name=hdfs://namenode-svc:8020
, and the other configurations were analogue to this way.

I started hdfs namenode and datanode via kubernetes replication-controller. In my case, one namenode and two datanodes happens to be on different hosts. And namenode pod and datanode pod can ping each other successfully.

However I encountered the following two problems when trying to start hdfs datanode:
When datanode tried to register itself to namenode via rpc request, namenode got the wrong ip address for the datanode. Normally it should get the pod ip of the datanode, but in this case flannel.1 inet address of datanode host is reported to namenode.

**Comment by lvlv** [comment]
In short, a hacky way to work around this is to use headless service, let
me know if you meet with further issues. :-)

Longer version, when you use service, the request will be handled by
kube-proxy, which will replace the source ip. The namenode will then get a
register request from the node ip instead of the pod ip, and reject it.

**Comment by GavinSong123** [comment]
@lvlv What is headless service? Can you describe in detail? And..Er..Can you speak Chinese? :)

**Comment by lvlv** [comment]
You may find headless services at:
http://kubernetes.io/docs/user-guide/services/#headless-services

**Comment by GavinSong123** [comment]
@lvlv Thank you! It has solved.

**Comment by yangshuai93** [comment]
@lvlv  HDFS can work now, but I can't access from outside ( ip:port) . what's the problem ?

**Comment by lvlv** [comment]
The client has to join the flannel network also, or you may use webhdfs
instead.
