### ISSUE TITLE
kubectl run --restart=Never does restarts

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#26549]
```sh
$ kubectl run -it --image=busybox --restart=Never false /bin/false
```

I expect this to run the /bin/false once. Instead a job is created which restarts `/bin/false` until it succeeds (which it never does).

This way it is impossible to create real one-off tasks with `kubectl run`.

**Comment by AdoHe** [comment]
seems dup of #24533

**Comment by sttts** [comment]
@AdoHe thanks for the link. It's a duplicate.
