### ISSUE TITLE
ingress user guide should mention that services need to be of the NodePort type

### ISSUE THREAD

**Issue by jmhodges** [kubernetes/kubernetes#26579]
It seems that Ingresses need the Services they connect to be of type NodePort, but this isn't documented in the [Ingress user guide](http://kubernetes.io/docs/user-guide/ingress/). At least, they do in Google Container Engine.

The "alternatives" section probably needs an update, too.

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/26508

Node port is actually not a requirement of Ingress per-se, only on cloud providers. You can get more elaborate docs on the GCE ingress controller here: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce

I'm planning to update docs before 1.3 anyway, will handle this bit of clarification when I do that
