### ISSUE TITLE
Allow node e2e base images to exist in different GCE projects

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#26587]
As of now we create a lot of base images for the GCE VMs that we spin up for node e2e. These images are duplicated in two different GCE projects for the purposes of CI.

Instead, we can have the node e2e framework spin up VMs from non-local projects. That way, we can avoid duplication and also let the community contribute images that needs to be included in the node e2e CI.

**Comment by vishh** [comment]
cc @derekwaynecarr This feature will make it straightforward to update existing test images and add new images.

**Comment by derekwaynecarr** [comment]
@vishh - is this being done prior to 1.3?

**Comment by vishh** [comment]
I can't think of a reason not to do it prior to v1.3, given that most of
the contributors are focused on tests as of now.
