### ISSUE TITLE
Unable to get Pod IP from downward API when kubelet cannot contact API server

### ISSUE THREAD

**Issue by derekparker** [kubernetes/kubernetes#26590]
When a kubelet is not in standalone mode, and attempts to start a static pod with host networking, and the kubelet is unable to contact an API server, it is unable to get the host IP from the node information. Essentially, in `Kubelet.GetNode` it will return `kl.initialNodeStatus` if the kubelet is in standalone mode, if not it attempts to get that information from the `CachedNodeInfo`, which it appears is filled via API server watches. If the kubelet cannot contact the API server, that cache is never filled, so the kubelet cannot return node info, meaning `podStatus.IP` is never properly filled out.

**Comment by yujuhong** [comment]
ref: #6558
