### ISSUE TITLE
Pointers of structs can't be printed with %+v anymore 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#26591]
I remember this worked before, but now printing pointer of kubernetes objects with `%+v` becomes useless (which affected lots of logs). 

```go
curPod := cur.(*api.Pod)
oldPod := old.(*api.Pod)
glog.V(4).Infof("Pod %s updated %+v -> %+v.", curPod.Name, oldPod, curPod)
```

```
I0531 13:46:55.896399   31819 deployment_controller.go:335] Pod nginx-3137573019-po48c updated kind:"" apiVersion:""  -> kind:"" apiVersion:"" .
```

Changing `%+v` to `%#v`, or de-reference the pointer when using `%+v` would work.

**Comment by mikedanese** [comment]
did this change between golang versions?

**Comment by pwittrock** [comment]
Hm, I don't remember this ever working with the rational being that go couldn't figure out how to handle circular refs.  If you need this `spew` handles it correctly.

**Comment by nhlfr** [comment]
I'm going to work on this, if nobody has anything against.

**Comment by mikedanese** [comment]
Go for it! Thanks!

**Comment by dims** [comment]
cc @lixiaobing10051267
