### ISSUE TITLE
"SSH should SSH to all nodes and run commands" takes a ridiculous amount of time on large clusters

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#26600]
On 2k nodes, this test took 53m. We should either do it in batches of nodes, or just subsample the nodes.

**Comment by zmerlynn** [comment]
And it probably doesn't need to test 4 different variant command sets against all of the nodes, either. :P

**Comment by zmerlynn** [comment]
@wojtek-t: When you asked me about the 2k node test, this was the test that was running. I'm not sure why other tests weren't also running in parallel or if this was just the final long pole, but it's a beastly test. PR incoming.

**Comment by wojtek-t** [comment]
@zmerlynn - thanks for looking into it. THe PR is already lgtm-ed by me.
