### ISSUE TITLE
Seccomp annotations name format need redefine

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#26610]
Now pod annotations validation only allow no more than one slash. But seccomp annotations format has more than one slash. like: security.alpha.kubernetes.io/seccomp/container/<container name>
https://github.com/kubernetes/kubernetes/blob/master/docs/design/seccomp.md#api-changes

When create a pod with  seccomp annotations, it will error.
```
$ kubectl create -f pod-seccomp.yaml
The Pod "pod-seccomp" is invalid.
metadata.annotations: Invalid value: "security.alpha.kubernetes.io/seccomp/pod": must be a qualified name (at most 63 characters, matching regex ([A-Za-z0-9][-A-Za-z0-9_.])?[A-Za-z0-9]), with an optional DNS subdomain prefix (at most 253 characters, matching regex [a-z0-9]([-a-z0-9][a-z0-9])?(.a-z0-9?)*) and slash (/): e.g. "MyName" or "example.com/MyName"
```
which is caused by name validation. (more than one slash)
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L92
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/validation/validation.go#L38
related https://github.com/kubernetes/kubernetes/pull/25324

**Comment by mdshuai** [comment]
@ncdc @pmorie

**Comment by sttts** [comment]
It's not only the slash which might lead to conflicts, but also the length. The container `name` field is a DNS_LABEL (https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L40) with up to 63 characters. The same limit applies to the string right to the / in the annotation key. 

Moving everything other than the container name to the left of the / should help.

**Comment by ncdc** [comment]
@sttts @pmorie who wants to fix this? 😄

**Comment by sttts** [comment]
I can do that tomorrow (if @pmorie doesn't insist to do it himself before ;) )

**Comment by jfrazelle** [comment]
ah good catch
