### ISSUE TITLE
e2e flake: Generated release_1_3 clientset [It] should create pods, delete pods, watch pods 

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#26628]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/26622/kubernetes-pull-build-test-e2e-gce/42787/build-log.txt

```
Failed to query for pods: Get https://130.211.140.201/api/v1/namespaces/e2e-tests-clientset-lwmck/pods?labelSelector=time%3D569192984: dial tcp 130.211.140.201:443: i/o timeout
```

it seems that API server were unresponsive for some time. cc @lavalamp

**Comment by caesarxuchao** [comment]
This happened with `kubectl exec` as well: https://github.com/kubernetes/kubernetes/pull/20932.

Not sure if we should dig this up or just retry when i/o timeout occurs.

**Comment by wojtek-t** [comment]
So far most of the i/o timeouts that I faced were because apiserver was down at that time.

**Comment by wojtek-t** [comment]
But it wasn't the case here...

**Comment by fejta** [comment]
@krousey you're randomly assigned this test via the spreadsheet. Please take a look or else update the spreadsheet and assign to @lavalamp

**Comment by krousey** [comment]
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26714/kubernetes-pull-build-test-e2e-gce/42787/

I hate that the storage.googleapis.com url isn't browse-able.

**Comment by krousey** [comment]
Looking through the api server log, there's no record of that request.

**Comment by krousey** [comment]
Any idea of the frequency. Is it frequent? Or is it possible that this is just a transient network issue?

**Comment by gmarek** [comment]
I saw this for the first time, so it might be a red herring.

**Comment by caesarxuchao** [comment]
Might be caused by running too much tests at once on Jenkins VMs. See https://github.com/kubernetes/kubernetes/issues/26420

**Comment by lavalamp** [comment]
look for evidence of apiserver having crashed-- @wojtek-t fixed something
similar recently.

**Comment by krousey** [comment]
@lavalamp , @wojtek-t already stated that it wasn't because the apiserver was down in this case.

**Comment by lavalamp** [comment]
Yeah, sorry, I somehow missed that.

**Comment by krousey** [comment]
Seems to not have re-occurred. Any objections to closing this?

**Comment by krousey** [comment]
It's been a week and no more occurences were pointed out. Also no objections were raised.
