### ISSUE TITLE
Local e2e_node tests broken, possible etcd issue?

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#26640]
If I try to run `make test_e2e_node`, I get the following error:

```
Failure [11.229 seconds]
[BeforeSuite] BeforeSuite 
/usr/local/google/home/mtaufen/go-tools/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:100

  Unable to start node services.
  `/usr/bin/sudo sudo /usr/local/google/home/mtaufen/go-tools/src/k8s.io/kubernetes/_output/local/go/bin/kube-apiserver --etcd-servers http://127.0.0.1:4001 --insecure-bind-address 0.0.0.0 --service-cluster-ip-range 10.0.0.1/24 --kubelet-port 10250 --allow-privileged true --v 8 --logtostderr` health-check: http://127.0.0.1:8080/healthz Failed with error "exit status 255".  Output written to: kube-apiserver.log
```

If I check the log (at least what I think is the related log: `kubernetes/test/e2e_node/kube-apiserver.log`), I see a lot of variations on the following error message:
```
E0601 10:07:04.787544   95013 cacher.go:221] unexpected ListAndWatch error: pkg/storage/cacher.go:164: Failed to list *api.PersistentVolume: client: etcd cluster is unavailable or misconfigured
```

According to the log, this also happens for identifiers other than `api.PersistentVolume`, e.g. `policy.PodDistributionBudget`, `autoscaling.HorizontalPodAutoscaler`, and it looks like at least several others.

This showed up just before I left work yesterday. I had rebased on the most recent master yesterday, so maybe this is related to a recent change?

**Comment by mtaufen** [comment]
Another potentially interesting message from the logs:
```
E0601 10:52:56.173170   95013 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
```

**Comment by timstclair** [comment]
I just reproduced this after aborting a test run, and fixed it with
```
killall kubelet && killall kube-apiserver
```
Does that help you?

**Comment by mtaufen** [comment]
@timstclair No, that didn't really help. Just gave me the following:
```
kube-apiserver(95013): Operation not permitted
kube-apiserver: no process found
```

Prior to trying your suggestion, I waited for a while, and then things started working again, which got me thinking about how long sudo credentials last. 

Sure enough, running `sudo -v` to re-credential just before trying to run the tests reproduced the problem, and running `sudo -k` before running the tests made the problem go away again.

This is annoying, because there are several things buried in the test infrastructure that ask for my password, which means these tests are anything but fire and forget. :/
