### ISSUE TITLE
Jenkins unit/integration flake: no test report files were found

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#26644]
Sometimes a jenkins build will appear to run successfully, but fail with the following message:

```
ERROR: Step â€˜Publish JUnit test result reportâ€™ failed: No test report files were found. Configuration error?
```

Example build: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24808/kubernetes-pull-test-unit-integration/28759/

**Comment by wojtek-t** [comment]
@kubernetes/test-infra-maintainers

**Comment by spxtr** [comment]
```
FAILED   ./hack/../hack/verify-boilerplate.sh	1s
```

We never ran unit/integration tests so there was no JUnit to report so this plugin also failed.

**Comment by ixdy** [comment]
The plan is to have the verify- checks emit junit, but that's not been implemented yet.

**Comment by spxtr** [comment]
I'd also like to move the verify checks into a separate job.

**Comment by wojtek-t** [comment]
We want to move due to performance reasons.
@spxtr - is anyone already working on it? Is there any ETA on it?

**Comment by fejta** [comment]
This will happen once the jenkins PR jobs are under source control

**Comment by pmorie** [comment]
Yeah, this one was my bad.  +1 to moving the verify checks to a separate job - that would be awesome.
