### ISSUE TITLE
Token File "Groups" Docs

### ISSUE THREAD

**Issue by nVitius** [kubernetes/kubernetes#26659]
The documentation for [Authentication](http://kubernetes.io/docs/admin/authentication/) talks about "groups" when it mentions the token file. However, it doesn't talk about what they are used for nor how they are created.

**Comment by a-robinson** [comment]
Opened https://github.com/kubernetes/kubernetes.github.io/issues/598 to replace this, since we track docs issues in the kubernetes.github.io docs repo.
