### ISSUE TITLE
support docker image pull by digest

### ISSUE THREAD

**Issue by tam7t** [kubernetes/kubernetes#26651]
I would like to specify my docker image by `digest` instead of `tag` for a more 'immutable'  guarantee that the image  pulled is the exact image I specified in my `PodSpec`.

docker supports this with the `@DIGEST` format: `docker pull [OPTIONS] NAME[:TAG|@DIGEST]`

example:

```
$ docker pull internal-registry/dashboard@sha256:b2ea388fdbabb22f10f2e9ecccaccf9efc3a11fbd987cf299c79825a65b62751
sha256:b2ea388fdbabb22f10f2e9ecccaccf9efc3a11fbd987cf299c79825a65b62751: Pulling from dashboard
Digest: sha256:b2ea388fdbabb22f10f2e9ecccaccf9efc3a11fbd987cf299c79825a65b62751
Status: Image is up to date for internal-registry/dashboard@sha256:b2ea388fdbabb22f10f2e9ecccaccf9efc3a11fbd987cf299c79825a65b62751
```

But when I specify the following:

```
image: internal-registry/dashboard@sha256:366f2380e0511597490ccbb3b2c2d1e5804b667a61c4a91d04bf84ef4e41305e
```

The pod errors with:

```
Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard-canary" with ErrImagePull: "image pull failed for internal-registry/dashboard@sha256:366f2380e0511597490ccbb3b2c2d1e5804b667a61c4a91d04bf84ef4e41305e, this may be because there are no credentials on this request.  details: (API error (500): missing signature key\n)"
```

I believe the error is in parsing the `image` logic somewhere around https://github.com/kubernetes/kubernetes/blob/6a87dba0b8a50dccaddb67a4c7748696db1918ec/pkg/kubelet/dockertools/docker.go#L148-L153

**Comment by Random-Liu** [comment]
I believe the HEAD has already fixed this. :) https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker.go#L148-L177

**Comment by tam7t** [comment]
ahh, I'm running `1.2.4` thanks for pointing that out!

**Comment by smarterclayton** [comment]
Fixed as commented

**Comment by hiscal2015** [comment]
Hi, all
I defined with tag for image, but why Kubernetes pulled digest? I can't find the reason. (Kubernetes 1.7)

https://github.com/rancher/rancher/issues/9525

**Comment by smarterclayton** [comment]
I'm pretty sure that rancher is printing the value of the container image
status field, which is "docker-pullable://pullspecbydigest".  You should
ask the rancher team which field they print in their UI.  Kubernetes
reports the effective digest id, because that's what allows you to know
what content is actually being run.
