### ISSUE TITLE
Reuse federation docker images in e2e tests when nothing has changed

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#26656]
If I build the federation images and push them, I should be able to reuse them in the subsequent `federation/cluster/federated-up.sh`. But this is not the behavior I am seeing right now. I am expected to push the images every time I run the build even when I don't touch anything in the federation directory. 

@colhom I am not able to assign issues to you. So I am assigning it to myself now and CC'ing you. But please assume that I am assigning this to you :) Also, please feel free to re-assign.

cc @quinton-hoole @nikhiljindal @kubernetes/sig-cluster-federation

**Comment by colhom** [comment]
@madhusudancs What is stopping you from re-using pushed images in `federation/cluster/federated-up.sh`? Assuming you don't re-run the build or change `FEDERATION_PUSH_REPO_BASE` between calling `federated-push.sh` and `federated-up.sh`, `federated-up.sh` should continue to use the last images that you built and pushed every time you call it.

**Comment by madhusudancs** [comment]
Every time I run `make quick-release` and run `federation/cluster/federated-up.sh`, federation-apiserver pod never comes up. The container just keeps crashing with ImagePullErr. The event log says that the kubelet/docker can't find the image with the given ID. If I run `federation/cluster/federated-push.sh` and then `federation/cluster/federated-up.sh` everything works fine.

**Comment by colhom** [comment]
`federated-push.sh` is what pushes the docker images from `make quick-release` to your docker repo. You can run `federated-push.sh` once after your build, and then just do `federated-up.sh` iteratively to re-deploy with the same container images.

**Comment by madhusudancs** [comment]
@colhom Mentioned this on IM, but also pasting it here so that it is easier to keep track of. 

`federated-up.sh` never succeeds if I run it before running `federated-push.sh` and this happens every time I run make quick-release, even on successive `federated-push.sh` runs. If I don't push, `federated-apiserver` pod just keeps crashing.

**Comment by nikhiljindal** [comment]
How about federated-up.sh detecting if the image with that ID exists and if not, it automatically calls federated-push.sh?

**Comment by madhusudancs** [comment]
That solves one part of the actual problem and we should do that nevertheless. However, the other part of the problem is pushing the images themselves. It should not be necessary to push the images every time, esp. when nothing has changed. From what @colhom described here it looks the current behavior is not intentional. We should debug that.

**Comment by quinton-hoole** [comment]
I assume that @madhusudancs will want to take care of this as part of his improvements to the Federation build and deploy automation?  Adding 1.4 milestone for tracking purposes.

**Comment by goltermann** [comment]
@madhusudancs still in plan for 1.4?

**Comment by madhusudancs** [comment]
This is already fixed. Fixed in PR #29515.
