### ISSUE TITLE
Create clusters concurrently while setting up federation e2e

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#26655]
The time to bring up a federation (of clusters) to run e2e test is very long right now. Much of that work can be done concurrently. For example GCE nodes can be created concurrently, etc. At the minimum we should run [the iterations in this loop](https://github.com/kubernetes/kubernetes/blob/master/hack/e2e-internal/e2e-up.sh#L37) concurrently.

@colhom I am not able to assign issues to you. So I am assigning it to myself now and CC'ing you. But please assume that I am assigning this to you :) Also, please feel free to re-assign.

cc @quinton-hoole @nikhiljindal @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
Sounds like a good idea.   How long are you seeing? If it's less than 30 minutes, lets do this optimization later.  For now, lets focus on getting the e2e tests in and passing :-)

**Comment by madhusudancs** [comment]
It is right at about 30 minutes, give or take a few minutes depending on various factors not in our control. Also, I am blowing through my monthly data usage limit. For example. we stage the server tars for each cluster right now. Each of them is about 300MB. Plus 100MB for federation-apiserver image (it is not clear if this is being uploaded each time). But roughly, every time I bring up the federation, I spend about a gigabyte. It is only 1st of the month and I am already feeling bad :)

**Comment by colhom** [comment]
How do we want to mux the log output from the concurrent kube-up invocations in a maximally jenkins-friendly manner? 
* Line by line with line prefixes? 
* N-line batch groups with header label sections? 
* Write each to a file, print out the file path and cat each file out at the end?

**Comment by quinton-hoole** [comment]
Fair enough @madhusudancs , that sounds worth fixing (but only after the tests are running and passing :-) )

**Comment by madhusudancs** [comment]
@colhom I have been thinking about that, but I don't have a good answer. I did not think about your option 2, i.e.

> * N-line batch groups with header label sections?

I think doing just 3 

> * Write each to a file, print out the file path and cat each file out at the end?

Will lead to a bad experience. For example, people won't be able to look at the output in the in Jenkins console output.

I think line prefix is the quickest solution and which is what we should do in the short term.

In the medium term, we should split up the steps to bring up a cluster and run the individual steps one after the other, but parallelize the individual steps themselves. For example, we can create the MIGs for each cluster in parallel that creates nodes for each cluster. But we can wait for that before moving on to next step of creating network rules.

Also, it is worth discussing this with @mikedanese and see if the cluster deployment simplification work that he is doing can help here.

@quinton-hoole Ack.

**Comment by quinton-hoole** [comment]
I gather that this is done now.

**Comment by madhusudancs** [comment]
Work is all done, the PR is under review. I will close it once the PR is merged.
