### ISSUE TITLE
Integrate federated service DNS record management: Address remaining code review comments.

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#26669]
See unresolved comments in #25991 for details.

In particular: 
- Possibly return ErrNotFound rather than empty slice from getRrsets()

**Comment by quinton-hoole** [comment]
@madhusudancs FYI

**Comment by goltermann** [comment]
@quinton-hoole needed for 1.4, or should we push it out?

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @quinton-hoole

**Comment by madhusudancs** [comment]
Changed the milestone to v1.6

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by marun** [comment]
Not a release blocker.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#45.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
