### ISSUE TITLE
IP restrict SSH

### ISSUE THREAD

**Issue by Naddiseo** [kubernetes/kubernetes#26661]
I'd like to be able to IP restrict SSH on the master and minions, and also IP restrict API access on master. I'm not sure about other providers, but AWS is commented by @justinsb as "Would be fairly easy to replace 0.0.0.0/0 in these rules", so I'd like to request that this be made possible.

**Comment by a-robinson** [comment]
Contributions are very welcome if there's a particular provider that you'd like to enable this on! The scripts for cluster creation (which typically create the firewalls you're referring to) live under the `cluster/` directory.
