### ISSUE TITLE
broken sample links on kubernetes.io

### ISSUE THREAD

**Issue by joshuacox** [kubernetes/kubernetes#26672]
Lot's of the sample links are broken at the moment on kubernetes.io, perhaps there is quite a bit missing from release-1.2?

e.g.:

https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/logging-demo/

https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/k8spetstore/
looks like it should be:
https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/k8petstore

all from this page:
http://kubernetes.io/docs/samples/

**Comment by a-robinson** [comment]
I've opened https://github.com/kubernetes/kubernetes.github.io/issues/599 to replace this, since we track docs issues on the kubernetes.github.io docs repo. Contributions welcome to fix these up!
