### ISSUE TITLE
Remove federation-apiserver's dependency on kubernetes APIs

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#26675]
Right now `--storage-versions` in federation-apiserver includes all the k8s APIs (see https://github.com/kubernetes/kubernetes/blob/master/docs/admin/federation-apiserver.md), which is wrong.
This is happening because an API group is registered if there is a dependency on it.

Here is how federation-apiserver depends on k8s extensions API group:

```
$ go run godepq.go -from k8s.io/kubernetes/federation/cmd/federation-apiserver -to k8s.io/kubernetes/pkg/apis/extensions
Packages:
  k8s.io/kubernetes/federation/cmd/federation-apiserver
  k8s.io/kubernetes/federation/cmd/federation-apiserver/app
  k8s.io/kubernetes/pkg/admission
  k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset
  k8s.io/kubernetes/pkg/apis/extensions/install
```

This dependency route exists for all k8s apis.

cc @kubernetes/sig-api-machinery @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
The refactoring that @lavalamp was doing can help here. clientset and federation-apiserver can use different instances of registered. So an API group can be registered with the client but not with the apiserver.

**Comment by quinton-hoole** [comment]
@nikhiljindal Can this issue be closed yet?

**Comment by nikhiljindal** [comment]
No. We still need to fix it. It requires some changes in our API machinery code. Doesnt look like we will be able to get to this in 1.4. Will fix in 1.5

**Comment by dims** [comment]
@nikhiljindal Is this still target-ted for 1.5? looks like PR #35162 referenced does not have 1.5 milestone on it either. please switch milestones if appropriate

**Comment by nikhiljindal** [comment]
Removed the milestone

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#200.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
