### ISSUE TITLE
Don't wait for more nodes when 99% of the cluster is up.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#26691]
Currently we assume that the cluster is healthy if 99% of Nodes are. We keep on waiting for more nodes even after 99% are up, until all Nodes are ready or we reach the timeout, even though we know that the cluster will be considered healthy.

The question is shouldn't we finish validation when 99% of the cluster is up. This will increase the possibility that some additional Nodes will join the cluster after it started, but I'm not sure that's bad.

My proposal is to do it, i.e. validate cluster should wait only for first 99% of the cluster.

@smarterclayton @lavalamp @wojtek-t @zmerlynn @davidopp

**Comment by lavalamp** [comment]
Sounds fine to me. Suggestion: maybe wait like 20 more seconds rather than
the full timeout.

**Comment by wojtek-t** [comment]
I think that we shouldn't stop as soon as we have 99% of nodes. But I agree with @lavalamp that waiting at most X from the time when we have 99% of nodes sounds like a good idea.
