### ISSUE TITLE
PodAffinity SchedulerPredicates are not well isolated

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#26698]
Those tests add labels to Nodes and depend on Node labels, but they don't clean up after themselves, thus leaking some state between tests. This is very bad and fixing this is critical before we can enable tests (and thus pod affinity feature) again.

cc @davidopp @wojtek-t @fejta

**Comment by dims** [comment]
Is this related to the other flake in https://github.com/kubernetes/kubernetes/issues/25398 ?

**Comment by gmarek** [comment]
Possibly, but when I looked at it only one test that was looking at those labels was enabled, so this shouldn't be causing flakes.
