### ISSUE TITLE
Elasticsearch should run in a PetSet with PVs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#26708]
When we install elasticsearch, we currently use a hostVolume.  This means that ES will eventually fill the disk on that node and likely take the node down.  We should instead ship ES with PetSets backed by PVs, so this cannot happen.

cc @ajohnstone

**Comment by chrislovecnm** [comment]
@justinsb until ssd is available as a storage type, elastic should not run on PVs ... Both elastic and cassandra are SUPER disk sensitive.

**Comment by chrislovecnm** [comment]
@justinsb also there is an elastic plugin for k8s, do you need petset?  Storage??

**Comment by kargakis** [comment]
@justinsb @chrislovecnm does this issue need to move in a different repo, eg. examples? Not sure why it's opened here.

**Comment by chrislovecnm** [comment]
We should close this. Elastic can run as a deployment or a statefulset. With kube-up it is installed I think as a deployment.

To me this is a non-issue. @justinsb?

**Comment by spiffxp** [comment]
/sig instrumentation
I believe sig-instrumentation owns the fluentd-elasticsearch addon, if that's what's being referenced here, which still uses a `ReplicationController` and `emptyDir` volume

**Comment by chrislovecnm** [comment]
@spiffxp yah that is kinda not anything I would recommend in production.  But really should that even be part of the base install?

**Comment by spiffxp** [comment]
/close
The linked addon deploys elasticsearch as a statefulset.  Please /reopen if I have closed this in error
