### ISSUE TITLE
kubectl patch --record not saving change cause

### ISSUE THREAD

**Issue by Draiken** [kubernetes/kubernetes#26703]
I'm using patch with JSON patch mode for some deployments, and when checking rollout history, change cause is always empty

https://github.com/kubernetes/kubernetes/blob/f500194d92ab0f8d64836f0b38a6eeefc2c612ee/pkg/kubectl/cmd/patch.go#L158

If I read the code correctly, this would fail silently, so maybe something is not working specifically with the `patch` command.

**Comment by a-robinson** [comment]
Could you give an example of a command that you run?

**Comment by Draiken** [comment]
Sure!
```
patch='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"someimage"}]'
kubectl patch deployment thing --type='json' -p='$patch' --record=true
```
And then running
```
kubectl rollout history deployment/thing
```
I get
```
deployments "thing":
REVISION	CHANGE-CAUSE
1		<none>
2		<none>
3		<none>
```

**Comment by pwittrock** [comment]
cc @janetkuo 

Are you creating the patch through kubectl?  I believe the annotation is applied by the kubectl client, not defaulted in the server.

[link to code](https://github.com/kubernetes/kubernetes/blob/0a6a52b19ddddc4ee0893b5841b944e640ea70e8/pkg/kubectl/cmd/util/helpers.go#L447)

**Comment by Draiken** [comment]
Yes, I'm using kubectl.

From what I understood, it takes the `Command()` string from the cobra command, annotates the object with it and sends it to the server. Maybe it's because it's using jsonpath instead of the more common merge strategy? I really don't know

**Comment by danielwhatmuff** [comment]
I have the same behaviour - how can I enable the CHANGE-CAUSE to be recorded?

**Comment by Draiken** [comment]
I should not here that this issue has been resolved for me for some time now.
Change-cause is set to whatever command was used to introduce the change as it should.

**Comment by adimania** [comment]
A similar thing is happening to me. I am using the deployment definition from [here](https://github.com/training-devops/kubernetes-artifacts/blob/master/nginx-deployment.yml). After the deployment is created successfully, I update the image using `kubectl set image deployment my-nginx my-nginx=nginx:1.11`. However, rollout history is not able to capture this
```
kubectl rollout history  deployment/my-nginx
deployments "my-nginx"
REVISION	CHANGE-CAUSE
1		<none>
2		<none>

```

**Comment by janetkuo** [comment]
Hi all, "change cause" is populated from the `kubernetes.io/change-cause` annotation of the resource. Using `--record=true` flag while running `kubectl` command will record the command in the aforementioned annotation. You can manually annotate deployments to see the change cause in rollout history too.

Also note that there is a separate discussion around deprecating `--record` #40422.
