### ISSUE TITLE
kube-dns should be a daemonset / run on every node

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#26707]
As DNS is so crucial to k8s, and I have seen failures due to resource starvation preventing kube-dns from starting, we should run kube-dns in an HA configuration.  I believe we should run it on a daemonset on every node.

It might be that the kube2sky -> etcd -> skydns setup is too resource intensive for this; if so we should probably make a controller that removes etcd and integrates kube2sky & skydns, now that this pattern is well-known & proven.  @thockin I thought you had some notes on how to do this but github search is failing me.

cc @ajohnstone

**Comment by four43** [comment]
I was having the DNS slowness issue, as referenced by [kube-aws #533](https://github.com/coreos/coreos-kubernetes/issues/533) above. We found that DNS performance on our cluster was limiting our requests. An estimate of 40,000 DNS requests/min I think would be a fair estimate for our usage and we had to scale our DNS pods out to use 600 CPU units (100/pod in our setup) in order to handle that load. Micro-services are fun :)

**Comment by thockin** [comment]
This is a dup.  I am on vacation, but I know there's already a bug to
consider this - I updated it this week :)

**Comment by bgrant0607** [comment]
See also #7470

**Comment by roberthbailey** [comment]
@thockin - if there's another bug can you de-dupe this? Otherwise, I'm going to consider it on the networking sig's backlog, since while cluster lifecycle is responsible for the mechanics of deploying addons, the networking sig should determine the policy of how the DNS addon is run in a cluster.

**Comment by thockin** [comment]
@mdelio

**Comment by kenden** [comment]
Related https://github.com/kubernetes/kops/pull/2705
running on every node (not only masters) would surely be HA enough, but with a high number of nodes it could be a waste of resources?

**Comment by JorritSalverda** [comment]
I think if we make sure the minimum number of pods for kube-dns is 2 or 3 instead of 1 and it gets a  `preferredDuringSchedulingIgnoredDuringExecution` `podAntiAffinity` with `topologyKey: kubernetes.io/hostname` it should be much more resilient already. I'm not sure if this works for single host clusters, but you shouldn't do that anyway.

We run GKE on top of preemptibles and kube-dns being unavailable has bitten us multiple times because all pods were scheduled on the same preemptible host.

**Comment by mongrelion** [comment]
> We run GKE on top of preemptibles and kube-dns being unavailable has bitten us multiple times because all pods were scheduled on the same preemptible host.
@JorritSalverda so does your `podSpec` example fix the issue?

**Comment by odino** [comment]
FYI this is also possible through workarounds ([official doc](https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/#determining-your-scale-target))

**Comment by rlees85** [comment]
Just another case for this that haven't been mentioned. It would be nice to scale down idle clusters to 1 or even 0 nodes (keeping the masters up).

Currently kube-dns prevents this. Once scaled down to 2, the single point of failure flag prevents scaling down further (which I would like to keep enabled as if the cluster is running 2 or more nodes I would like HA kube-dns)

Even with the single point of failure flag to false, the cluster will always have 1 node.

Daemonsets do not prevent cluster auto-scaler from scaling down.

I agree it could end up being a waste of resources especially on clusters with lots of small nodes.

**Comment by krmayankk** [comment]
@justinsb  can you provide some more context on why you recommend a daemonset approach as opposed to just HA (2-3 instances) ? Are you thinking each Pod would just talk to its local kubeDNS  running on that node ? Wouldnt that mean each kubeDNS is listening for pods and services on all nodes which would kill the apiserver ?

**Comment by krmayankk** [comment]
Who would this be achieved using CoreDNS (https://github.com/kubernetes/community/pull/1956) ?

**Comment by jasonrichardsmith** [comment]
So I have played around with an init container that has a shared volume with a container for /etc/resolve.conf.
In the initcontainer:
1. Through the downward api I get the nodeName.
2. Using the nodename I get the pod for for dns daemonset running on the same node.
3. Using that I write the resolve.conf and exit the initcontainer.

I think this will insure the shortest route.
I would like to write an admission controller that does this for any pod.

**Comment by bowei** [comment]
Let's merge the discussion on to issue #45363

/close
