### ISSUE TITLE
Bare Metal Kubernetes cluster deployment on Ubuntu 14.04 insecure certificate 

### ISSUE THREAD

**Issue by isobina** [kubernetes/kubernetes#26713]
I had an issue, with deploying Kubernetes cluster on bare metal. kube-up.sh suddenly stopped after executing successfully download-release.sh. The reason was that the following command  
curl -L -O https://storage.googleapis.com/kubernetes-release/easy-rsa/easy-rsa.tar.gz > /dev/null 2>&1 was failing due to not trusted certificate. Workaround add **--insecure**.

**Comment by roberthbailey** [comment]
Support for ubuntu in kube-up was removed in https://github.com/kubernetes/kubernetes/pull/44344 so I'm going to mark this as obsolete.
