### ISSUE TITLE
TFTP service with external IP not accessible from outside

### ISSUE THREAD

**Issue by j-vizcaino** [kubernetes/kubernetes#26718]
#### Environment
- Kubernetes 1.2.4
- Bare-metal, CoreOS >= 991
- Flannel + VXLAN for internal cluster comm. Dedicated eth1
- Public network on eth0
- kube-proxy mode : `iptables`
- kube-proxy masquerade-all=false (default)
#### How to reproduce
- declare the TFTP service (type UDP, port 69), with clusterIP and externalIP. externalIP is a publicIP of a node.
- run a pod with TFTP service
- try to access the service from the outside, UDP packet reaches the service but cannot be sent back (recvfrom: connection refused)

NOTE: internal cluster access is working (pod to pod), as well as accessing the service through its clusterIP.

**Comment by j-vizcaino** [comment]
Testing further, we discovered that, using the exact same setup, DNS UDP trafic was correctly routed and `conntrack` did its job correctly.
It appears, `conntrack` need a special module in order to track TFTP trafic: module is called `nf_conntrack_tftp`.

**Comment by j-vizcaino** [comment]
It seems to be related to how the TFTP protocol works:

```
Client:x → Srv:69 - client requests
Client:x ← Srv:y - server replies from a random port, not 69
Client:x → Srv:y - client acknowledges on dedicated port
```

Loading the `nf_conntrack_tftp` show `helper=tftp` in the `conntrack` events but does not help much.
Is this dynamic port binding ExternalIP:portY → PodIP:portY even supposed to work?

**Comment by sr00373954** [comment]
Hi,
Is there any solution for this issue?
Requesting you to guide on how to resolve this.

**Comment by kvaps** [comment]
Hi @sr00373954 I've tried to load `nf_nat_tftp`and `nf_conntrack_tftp` modules, it wasn't help to me. I've tried both modes for proxy `ipvs` and `iptables`.
For now I just use pipework for passthrough ip address directly into pod - this is working fine.

@thockin, if you have any solution please describe it. This issue very interesting for me.

**Comment by dimasmjunior** [comment]
I'm having the same problem. Have someone found a solution?

**Comment by kvaps** [comment]
Hi @dimasmjunior, yes, the only way is to use modified tftp-server with [single port mode](https://github.com/vcabbage/go-tftp#unique-features)

**Comment by dimasmjunior** [comment]
Hey @kvaps, thank you very much!

I'm trying to port a PXE solution to Kubernetes and ended up running into this problem. I will try running in single port mode. I'm hoping my booting firmware goes along with it.

**Comment by kvaps** [comment]
I just wanted to stick this issue with [trivialt](https://github.com/kvaps/trivialt), CLI for go-tftp with single port feature.
And with the similar [feature request for dnsmasq](http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2019q4/013650.html).

**Comment by xeuzuex** [comment]
> Hey @kvaps, thank you very much!
> 
> I'm trying to port a PXE solution to Kubernetes and ended up running into this problem. I will try running in single port mode. I'm hoping my booting firmware goes along with it.

using the following iptables rule on the node solved my issue
`iptables -t raw -A PREROUTING -p udp -m udp --dport 69 -j CT --helper tftp`
