### ISSUE TITLE
include federation e2e in merge bot testing

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#26723]
We should include federation e2e in merge bot testing, so that we can catch PRs that break the test.
We need to ensure that it is 100% green before doing this.

@colhom Can you take this up?

cc @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
I can take this.  Lets focus on getting them all green first though.

**Comment by nikhiljindal** [comment]
@quinton-hoole can you detail the steps that are required?
It will be good to get a PR ready.

**Comment by quinton-hoole** [comment]
@nikhiljindal I don't know the precise steps offhand, but in essence there are two parts:

1. the merge-bot configuration needs to be updated to to include the "kubernetes-e2e-gce-federation" test job as a merge-blocker.  That way, if that job is failing, automated merges will be blocked.
2. the per-PR merge bot needs to be updated to deploy the federation control plane into the e2e test cluster, and add "--test_args="--ginkgo.focus=\[Feature:Federation\]" to the e2e tests that are run on every PR. This will ensure that the federation e2e tests are run (against a federation which includes only a single underlying cluster) for every PR.  We can extend this to multiple clusters as a second step (as this might be slightly more difficult to configure).

**Comment by goltermann** [comment]
Applying P1 priority - adjust if that's not right.

**Comment by nikhiljindal** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
> the per-PR merge bot needs to be updated to deploy the federation control plane into the e2e test cluster, and add "--test_args="--ginkgo.focus=[Feature:Federation]" to the e2e tests that are run on every PR. This will ensure that the federation e2e tests are run (against a federation which includes only a single underlying cluster) for every PR. We can extend this to multiple clusters as a second step (as this might be slightly more difficult to configure)

You can only do this if it doesn't make the test take longer! Needs to stay under 30 minutes.

**Comment by quinton-hoole** [comment]
Agreed, that is part of what I meant by "more difficult" :-)

**Comment by nikhiljindal** [comment]
Created a test-infra issue for the second item as per discussion with @ixdy 
https://github.com/kubernetes/test-infra/issues/155

**Comment by quinton-hoole** [comment]
@nikhiljindal seems to have this done.  Reassigning.

**Comment by quinton-hoole** [comment]
This is done in kubernetes/test-infra#335. Closing.

**Comment by nikhiljindal** [comment]
Yes that PR was merged. But the test is still not passing on Jenkins. federation-apiserver pod fails to come up. I am trying to figure out how to get logs (We dont get pod logs right now)

**Comment by goltermann** [comment]
@nikhiljindal @quinton-hoole are these passing now?  Is this issue a 1.4 blocker?

**Comment by madhusudancs** [comment]
@goltermann federation tests are passing, but this issue isn't completely resolved. This isn't a 1.4 blocker. Re-targeting to 1.5.

**Comment by dims** [comment]
@madhusudancs : is this still target-ted for 1.5?

**Comment by saad-ali** [comment]
@nikhiljindal @kubernetes/sig-cluster-federation I am marking this as non-release blocking for 1.5.

FYI the federation E2E suite for release-1.5 is [ci-kubernetes-e2e-gce-federation-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation-release-1.5)

**Comment by nikhiljindal** [comment]
Yes removed from 1.5 milestone

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#46.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
