### ISSUE TITLE
/var/log/kubelet.log is missing on master

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#26726]
Use `journalctl -u kubelet` to view kubelet logs for now.

**Comment by yujuhong** [comment]
This is a known issue. @kubernetes/goog-image

**Comment by adityakali** [comment]
There is no plan to bring back /var/log/kubelet.log. All logs (even for other /var/log/kube*.log files in future) will be available in journald.

**Comment by andyzheng0831** [comment]
It is an issue for log collection via fluentd, as we really need some code change to bridge it. We already logged an internal issue for it. But for manual log check, it is arguable whether it is an issue. Using "journalctl -u kubelet" can see the log.

**Comment by yujuhong** [comment]
Should we close this if there is no plan to add the feature?

**Comment by ksemaev** [comment]
Discusting - all logs except kubelet stayed at /var/log so now I have to have 2 different approaches to get logs from nodes. Maybe you at least give us some possibility to get logs from /var/log from kubelet too?
