### ISSUE TITLE
Federation-e2e flake - federation-apiserver connection refused

### ISSUE THREAD

**Issue by colhom** [kubernetes/kubernetes#26725]
The kubernetes-e2e-gce-federation jenkins jobs in consistently flaking with the following output.

```
â€¢ Failure [5.905 seconds]
[k8s.io] Federation apiserver [Feature:Federation]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:641
  should allow creation of cluster api objects [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/federation-apiserver.go:63

  creating cluster: Post https://146.148.36.68:443/apis/federation/v1alpha1/clusters: dial tcp 146.148.36.68:443: getsockopt: connection refused
  Expected error:
      <*url.Error | 0xc8209cc6f0>: {
          Op: "Post",
          URL: "https://146.148.36.68:443/apis/federation/v1alpha1/clusters",
          Err: {
              Op: "dial",
              Net: "tcp",
              Source: nil,
              Addr: {
                  IP: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\x92\x94$D",
                  Port: 443,
                  Zone: "",
              },
              Err: {
                  Syscall: "getsockopt",
                  Err: 0x6f,
              },
          },
      }
      Post https://146.148.36.68:443/apis/federation/v1alpha1/clusters: dial tcp 146.148.36.68:443: getsockopt: connection refused
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/federation-apiserver.go:53
------------------------------
```

This is kubectl attempting to open a connection with the federation-apiserver via a loadbalancer service.

There are two possible underlying causes here, which are not mutually exclusive:
- federation-apiserver pod is not yet ready
- GCE loadbalancer has not finished initializing

I plan to remedy this by introducing some more "is it ready yet?" logic to `federated-up` procedure:
- wait until the federation-apiserver pod stays ready for 10 seconds. right now we only wait until it's running
- attempt to do `kubectl version` for another 30 seconds before allowing the e2e tests to start, to verify loadbalancer is initialized. right now we assume the loadbalancer is ready to serve traffic after the service ingress metadata becomes available. this is most likely a poor assumption

\cc @quinton-hoole @nikhiljindal @madhusudancs

**Comment by quinton-hoole** [comment]
Thanks @colhom SGTM.

**Comment by quinton-hoole** [comment]
@colhom Is this done yet?  If you're too busy we could try to find some community volunteers.

**Comment by colhom** [comment]
@quinton-hoole I am pretty swamped at the moment, so if there are any more expedient volunteers, by all means.

**Comment by quinton-hoole** [comment]
@shashidharatd Has volunteered to take this one.  Thanks Shashi!

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#47.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
