### ISSUE TITLE
Federation API server is presenting incorrect TLS certs

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#26731]
When I try to visit federation API server from Google Chrome, I get this error:

> \<IP_REDACTED\> normally uses encryption to protect your information. When Google Chrome tried to connect to \<IP_REDACTED\> this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be \<IP_REDACTED\>, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

> You cannot visit \<IP_REDACTED\> right now because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

This doesn't happen for kube-apiserver though. This needs to be fixed. It is hard to do many types of debugging otherwise.

@nikhiljindal Please feel free to assign this to yourself.

cc @kubernetes/sig-cluster-federation @nikhiljindal @quinton-hoole @colhom

**Comment by nikhiljindal** [comment]
@madhusudancs Are you still seeing this?

**Comment by madhusudancs** [comment]
@nikhiljindal yes, I am still seeing this.

**Comment by nikhiljindal** [comment]
Yes I see this now as well.
This is most probably a certificates issue.

cc @lavalamp
