### ISSUE TITLE
integration flake: timed out while in waitForPersistentVolumePhase

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/kubernetes#26730]
Test failed with `panic: test timed out after 10m0s` and the relevant part of the stack trace is:

```
goroutine 21070 [chan receive, 4 minutes]:
k8s.io/kubernetes/test/integration.waitForPersistentVolumePhase(0x7f26fa06d128, 0xc82de80c90, 0x27eb170, 0x9)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:321 +0x6b
k8s.io/kubernetes/test/integration.TestPersistentVolumeRecycler(0xc8260a2360)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:87 +0xb7a
testing.tRunner(0xc8260a2360, 0x3b14e78)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
```

Logs: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25841/kubernetes-pull-test-unit-integration/28338/

**Comment by jsafrane** [comment]
@fejta (or anyone), integration tests do not log much and I don't know what's going on in volume controller. Would it be possible to raise integration test log level at least to v=3 (4 preferred)?

**Comment by fejta** [comment]
@spxtr what is the status of https://github.com/kubernetes/test-infra/pull/103?

**Comment by jsafrane** [comment]
@pmorie, can you please take a look?

**Comment by spxtr** [comment]
Increasing integration log level can go into `hack/test-integration.sh` I think. It's probably a good idea to split them into their own job.
