### ISSUE TITLE
Incorrect meeting time in SIG Cluster Ops page

### ISSUE THREAD

**Issue by egustafson** [kubernetes/kubernetes#26739]
The meeting near the top of the sig-cluster-ops page (https://github.com/kubernetes/kubernetes/wiki/SIG-Cluster-Ops) incorrectly states _Friday_.   The correct meeting time is *Thursday*.  The correct day is stated at the bottom near the Hangouts link.

**Comment by a-robinson** [comment]
Fixed, thanks.
