### ISSUE TITLE
Node e2e framework killing issues

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#26748]
Node e2e framework starts the kubelet, apiserver and etcd as root [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/e2e_service.go#L129), but attempts to kill those processes as a non-root user [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/e2e_service.go#L80)

cc @kubernetes/sig-node

**Comment by vishh** [comment]
cc @mtaufen

**Comment by timstclair** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/26735
