### ISSUE TITLE
pkg/util/deployment isn't a util, it should live near deployments

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#26750]
pkg/util should really be code that is used in many places and is plausibly generic.

@nikhiljindal

**Comment by asalkeld** [comment]
Seems to be used by kubectl too:
```
git grep "pkg/util/deployment"
pkg/controller/deployment/deployment_controller.go:     deploymentutil "k8s.io/kubernetes/pkg/util/deployment"
pkg/controller/deployment/util.go:      deploymentutil "k8s.io/kubernetes/pkg/util/deployment"
pkg/kubectl/describe.go:        deploymentutil "k8s.io/kubernetes/pkg/util/deployment"
pkg/kubectl/history.go: deploymentutil "k8s.io/kubernetes/pkg/util/deployment"
pkg/kubectl/rollback.go:        deploymentutil "k8s.io/kubernetes/pkg/util/deployment"
pkg/kubectl/rolling_updater.go: "k8s.io/kubernetes/pkg/util/deployment"
pkg/kubectl/stop.go:    deploymentutil "k8s.io/kubernetes/pkg/util/deployment"
pkg/kubectl/stop_test.go:       deploymentutil "k8s.io/kubernetes/pkg/util/deployment"
test/e2e/deployment.go: deploymentutil "k8s.io/kubernetes/pkg/util/deployment"
test/e2e/framework/util.go:     deploymentutil "k8s.io/kubernetes/pkg/util/deployment"
```

Do you want to move anything not used by kubectl into pkg/controller/deployment/util.go?

**Comment by kargakis** [comment]
Totally agreed.

cc: @kubernetes/deployment

**Comment by kargakis** [comment]
We may want to consider a pkg/controller/deployment/util package.

**Comment by thockin** [comment]
My thinking is that the path should reflect the context.  These are utils
SPECIFICALLY about deployments, so pkg/controller/deployment/util even
pkg/api/deployment would be better.

We do have a precedent of util functions related to specific API kinds
being in `pkg/api/<kind>`

**Comment by asalkeld** [comment]
Thanks for the feedback, I'll move this to a standalone package as suggested. Also I didn't have to move any tests - so none of these  had unit tests! I'll look at improving that..

**Comment by kargakis** [comment]
Let's move those utils in pkg/controller/deployment/util. A bunch of them take clients as arguments and I am not sure we want them under pkg/api
