### ISSUE TITLE
Kubernetes Guestbook Example with Flask/NGINX

### ISSUE THREAD

**Issue by ltiao** [kubernetes/kubernetes#26764]
The official Kubernetes walkthrough guide often points to the guestbook application as a starting point for deploying a simple, but complete, multi-tier web application. The only thing is that the frontend is implemented in PHP. I think it would be much more useful and relatable if there existed an example implementation with a more modern paradigm/framework (Node.js, Flask/Django, Rails, etc.)

I have re-implemented the frontend of the guestbook example with a multi-container pod, serving Flask with a uWSGI server, and serving static files (`index.html`, `controllers.js`) using NGINX. The example lives in my fork: https://github.com/ltiao/kubernetes/tree/master/examples/guestbook-flask
I provide a comprehensive walkthrough of the process here: http://louistiao.me/posts/re-implementing-the-kubernetes-guestbook-example-with-flask-and-nginx/

If there is any value in incorporating this example implementation into the official repo, I would be glad to submit a PR :)

**Comment by a-robinson** [comment]
Hi @ltiao, there's no harm in sending a PR for a maintainer to take a look at if you already have the example ready :)

**Comment by dims** [comment]
@ltiao i second @a-robinson 's suggestion.
