### ISSUE TITLE
Grafana not showing POD graphs and Autoscaling not working

### ISSUE THREAD

**Issue by amitbitcse** [kubernetes/kubernetes#26769]
Docker Version - 1.11.1
Kubectl Version - 1.1.8
OS - Windows 7 (Installed Docker using Docker Toolbox version 1.11.1)

I am Running Kubernetes locally via Docker (https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/docker.md) with below modifications:
1. Changed --hostname-override="127.0.0.1" to --hostname-override="192.168.99.100"
2. Changed --config=/etc/kubernetes/manifests to --config=/etc/kubernetes/manifests-multi
3. Added --cluster-dns=10.0.0.10 and --cluster-domain=cluster.local while starting Master. 

Running DNS (https://github.com/kubernetes/kubernetes/tree/release-1.1/cluster/addons/dns) with below modifications
1. Added -kube_master_url=http://192.168.99.100:8080 in kube2sky container

Starting Heapster (https://github.com/kubernetes/kubernetes/tree/release-1.1/cluster/addons/cluster-monitoring/influxdb) with below modifications
1. Changed --source=kubernetes:'' to --source=kubernetes:http://192.168.99.100:8080?inClusterConfig=false&useServiceAccount=true

There is no error in InfluxDB, Heapster, Grafana, DNS or Kubernetes logs.

Cluster graph is coming up on Grafana (http://192.168.99.100:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/dashboard/db/cluster)
![image](https://cloud.githubusercontent.com/assets/5464002/15774415/c3ffd476-2999-11e6-9761-889e4693106e.png)

Pod graph is not coming up
![image](https://cloud.githubusercontent.com/assets/5464002/15774390/ad1daeae-2999-11e6-8723-a9529458a719.png)

Also when I am trying to autoscale my "nginx" replicationcontroller, I am getting below error in K8s Controller Manager:
_Failed to reconcile nginx: failed to compute desired number of replicas based on CPU utilization for ReplicationController/kube-system/nginx: failed to get cpu utilization: failed to get CPU consumption and request: metrics obtained for 0/1 of pods_

Please help

**Comment by devlina** [comment]
I am exactly facing same issue. I can see cluster nodes graphs but pods dropdown is empty. Do I need to add pods to grafana manually.

**Comment by amitbitcse** [comment]
@devlina 
No graphs come up even after adding pods manually to grafana.
Also, please check if you are getting any stats in heapster on accessing below url
http://xxx.xxx.xxx.xxx:8080/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/kube-system/pods/nginx-5otae/stats

In my case, no stats are coming up which means heapster is not communicating properly with Kubernetes.

**Comment by amitbitcse** [comment]
I tried it again using latest Kubenetes version (Running kubernetes cluster via minikube) and it is working, so closing it.
