### ISSUE TITLE
kube-addon-manager is using ~2CPUs 

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#26770]
It wakes up every 10 seconds and bursts the usage to 2CPUs when it available.

It's shouldn't cause any problems, as it has only 5 CPU shares, but it seems a lot for a process that monitors the status of few addons. I'm not sure how well it behaves when it's starved on CPU - it may be worth rewriting it to go (or anything other than bash really).

cc @wojtek-t @davidopp @mikedanese @luxas @thockin

**Comment by wojtek-t** [comment]
Actually what this script is doing is terrible - it shouldn't be required to e.g. spawn multiple python process just to ensure that addons are running in a correct version...

**Comment by mikedanese** [comment]
@gmarek it has .05 cpu share request. Is that not sufficient to mitigate impact? If not we can set a limit on it. It's not latency sensitive. I agree that the entire thing needs a rewrite but I'm not sure how urgent it is.

**Comment by gmarek** [comment]
I added a P3 priority:) I agree that it's .05 should be enough to mitigate the impact, as long as nothing external is looking for CPU usage as a signal to check if master is big enough. And as I mentioned I have no idea what will happen when we'll starve it.

**Comment by yujuhong** [comment]
CPU usage on my master node before and after killing kube-addon-manager:

![addon-manager](https://cloud.githubusercontent.com/assets/10524058/16213574/55e428d8-3705-11e6-96ee-5273c0097160.png)

**Comment by gmarek** [comment]
Oh, the beauty of the bash scripts. We probably should prioritize it higher then. @wojtek-t @jlowdermilk

**Comment by wojtek-t** [comment]
Yeah - I think we should

**Comment by mikedanese** [comment]
Do we actually know that this is the problem? Does the soak test pass when we disable the addon manager? The quickest fix is to drop the interval back down to 15 minutes like it was before.

**Comment by gmarek** [comment]
@mikedanese It makes master machine *seem* overutilized, so all automated monitoring will claim that we need bigger ones (@jlowdermilk) . I think we should rewrite addon updater sooner rather than later.

**Comment by mikedanese** [comment]
We've been discussing this a bit in https://github.com/kubernetes/kubernetes/issues/23233
