### ISSUE TITLE
Handle properly scaleTargetReference in HPA controller

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#26776]
Raised by @deads2k in https://github.com/kubernetes/kubernetes/issues/21577#issuecomment-199379149

cc @fgrzadkowski @jszczepkowski @mwielgus @kubernetes/autoscaling

**Comment by deads2k** [comment]
To add some detail here.  The code currently assumes that it can make a lexical conversion between kind and resource, this isn't correct.  The discovery doc can be used to find the authoritative mapping  between kind and resource, the two values do not have to match.

**Comment by nagarjung** [comment]
Can I have a look at this Bug if it is a beginner level. @piosz @deads2k  If yes could you help me to understand more about the Bug.

**Comment by DirectXMan12** [comment]
This was fixed last release or so

/close
