### ISSUE TITLE
AWS Security Group Issue

### ISSUE THREAD

**Issue by brockoffdev** [kubernetes/kubernetes#26787]
Hello K8s Lovers and Devs!

Quick question, we're currently working on getting Kubernetes up and running in AWS, however I've run into a little snag.  One of the things we'd love to do is have Kubernetes automatically generate an ELB for spun up services by our devs using the "LoadBalancer" service type.  Currently, our Node instances have two security groups, one that allows communication within the private VPC and its subnets, and one that allows for outbound NAT traffic.  (Worth noting that our EC2 Kube Node instances are in private subnets)

With that being said, we are consistently seeing this error:

```
  6m        9s  52  {service-controller }       Warning CreatingLoadBalancerFailed  Error creating load balancer (will retry): Failed to create load balancer for service bryant/id-staging-db: Multiple tagged security groups found for instance i-07727b3; ensure only the k8s security group is tagged
```

Having dug into the source code, I can't find anything specific that should be tagged in the security group itself save for a `KubernetesCluster` tag.  So we erased all tags on our one security group, which then allowed for only one security group to actually be tagged, and just for good measure added the `KubernetesCluster` tag noted in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go.

Any thoughts as to what may be happening here?  I know there is active discussion in the issues about SecurityGroup things that need to be cleaned up in K8s, but wondering for now what the best option is to get this working.  In theory, the ELBs could just be internal, and we can then just route to them, but it would also be great to have it working with quick and simple internet access when a service is created.

**Comment by sp-joseluis-ledesma** [comment]
Hello,

    found same behaviour here. The problem is we cannot remove tags for any of the security groups as it would break other company processes. Any workaround we may use to have loadbalancing working in AWS with multiple tagged securitygroups?

**Comment by philk** [comment]
It looks like this is the problem you're hitting (me as well). It seems like based on the comment this is a known issue but I'm not sure why the requirement for one and only one security group. AFAIK best practice is to split up specific permissions across security groups and add them as needed to instance types.

**Comment by mrook** [comment]
We also ran into this issue. We have a few worker instances with three security groups, of which one has a KubernetesCluster tag.

It looks like all security groups are retrieved in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L2549, the KubernetesCluster filter is missing.

**Comment by WeiBanjo** [comment]
Even removing tags doesn't work for us.  We are still getting error message ```Multiple tagged security groups found for instance i-xxxxxx; ensure only the k8s security group is tagged```

By looking at `getTaggedSecurityGroups` method in [aws.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L2830) file. I feel like calling `DescribeSecurityGroupsInput` with `nil` filter will return all the security groups instead of tagged security groups. That will cause all the security groups belong to a instance get appended to `tagged` array. https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L2800

I am not familiar with golang. It will be great if any golang experts can confirm that.

**Comment by WeiBanjo** [comment]
Solved problem with tagging master instance(s) with a `KubernetesCluster=<value>`.

**Comment by dhawal55** [comment]
Yes, tagging all master instances and one of the security groups in your worker node solves the problem.
