### ISSUE TITLE
Improve Jenkins soak test suites

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#26799]
I noticed that this week of kubernetes-soak-weekly-deploy-gce failed due to #23545

Build #104 (May 31, 2016 12:13:01 AM)

00:13:38 ERROR: gcloud crashed (error): [Errno 111] Connection refused

The issue is filed for test-infra improvement. No matter what cause for kubernetes-soak-weekly-deploy-gce, shouldn't we re-try? So that soaking test can be unblocked.

**Comment by dchen1107** [comment]
Now I manually started the build.

**Comment by fejta** [comment]
Will you talk to Dawn about this one?

**Comment by fejta** [comment]
@apelisse please talk to @dchen1107 about what we need to do here.

**Comment by dchen1107** [comment]
Had offline discussion with @apelisse. I changed the title to reflect what we had discussed, and removed flake label from it since a lot of them should be infrastructure improvements. I am summarizing what we had discussed so far.

Today kubernetes-soak-weekly-deploy-gce is pre-scheduled to run every Tuesday morning. If the build is failed, no retry. If the build succeeded, we deploy the build to kubernetes-soak-continuous-e2e-gce; otherwise do nothing. This means we have to wait for another week to re-build & re-deploy the build for soaking test unless someone manually kickout the new job for kubernetes-soak-weekly-deploy-gce. The below is what I suggested:
  1. Plan a weekly-deploy job on a specific time, like what we had today: Tuesday morning.
  1. The weekly-deploy job should check kubernetes-build and find the latest green one, and start from there. We might already did this, but it is difficult, if not impossible, to find the corresponding kubernetes-build from the logs of weekly-deploy jobs, which makes debugging much harder.
  1. If the weekly-deploy job failed, please repeat step 2 and retry.
  1. If the weekly-deploy job succeeded, deploy the package to soak-continuous build for about one week soaking test; and weekly-deploy build should be blocked until the next scheduled time is reached or some admin manually triggered. To make the navigation between builds and jobs easier, I suggested to corresponding each soak-continuous job with weekly-deploy job. Today, I have to guess the build based on the time.

**Comment by spxtr** [comment]
Aside: The [testgrid](http://k8s-testgrid.appspot.com/k8s#gce-soak) shows which git commit is being used. I was under the impression that it only uses green builds.

**Comment by fejta** [comment]
The best way to do this seems to be to merge these two jobs into one job and make it smart enough to know whether to redeploy or not based on the age and/or health of the cluster before running tests.

**Comment by fejta** [comment]
@krousey you're working on the soak tests. Does this fit under your purview?

**Comment by krousey** [comment]
@fejta I'm helping out with #27374 and trying to track down test failures. I could look into this, but I'm not that familiar with the test infra work.

**Comment by fejta** [comment]
I think a useful way to improve this test is to make it automatically detect and recover from deployment failures. I do not believe we need new jenkins/etc infrastructure to accomplish this. I can also help on this after I move the graphing process onto a VM instead of Ryan's workstation.

**Comment by krousey** [comment]
Odd. I would think that Jenkins would have functionality like this built in.

1. Run job A once a week and retry on failure.
2. Run job B every 4 hours  as long as job A isn't running and its last run was green.

Does it not have that?

**Comment by spxtr** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Naginator+Plugin but I'd rather not use it.

**Comment by fejta** [comment]
@krousey I'm sure someone has written something to do that, but that is not how I want to solve this problem -- coupling our tests to jenkins. I want to do the following:

Have a single job that does both a weekly deployment, health check and test running:

1. Read the GCS file to determine the age of the cluster, if more than a week old, delete the cluster.
2. If the cluster does not exist, deploy it and save the time of the deployment to a GCS file.
3. Check the health of the cluster, delete the cluster and fail if it is not healthy.
4. Run the tests on the healthy cluster.

We can do all of this in a single job, saving us a great deal of hassle.

**Comment by spxtr** [comment]
I don't think it needs to read any GCS files to determine how old it is, since it's reusing the same workspace. It can just save a file to the workspace when it starts a new cluster.

**Comment by fejta** [comment]
Ideally I'd like to eliminate the requirement that the job has to always run on the same machine, which we can remove by storing state in gcs.
