### ISSUE TITLE
Deployment should not do rollout when new fields are defaulted

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#26797]
Deployment relies on a PodTemplate hash to find compare ReplicaSets, however when new fields are added + defaulted it will change the expected Hash even though nothing should be changed.

**Comment by janetkuo** [comment]
Ref #26724 where this concern was raised.

**Comment by bgrant0607** [comment]
GetPodTemplateSpecHash shouldn't compute the hash on the internal representation, which may change (we don't guarantee backward compatibility), and shouldn't include fields set by default, since we may add new fields.

**Comment by bgrant0607** [comment]
We also need a test that the hash doesn't change.

**Comment by bgrant0607** [comment]
Another option is that we could just recompute the Deployment and RS pod template hashes.

**Comment by krmayankk** [comment]
When we say, new fields are added and defaulted, what does that mean ? How would you differentiate between defaulted or explicitly provided a value. Sorry i am just trying to familiarize myself with this codebase. I think its easier to just recompute the hashes

**Comment by kargakis** [comment]
@kubernetes/deployment

**Comment by janetkuo** [comment]
A third option, as #26792 implemented, is to not compare the hash value, but just compare podTemplateSpec.

**Comment by goltermann** [comment]
#26792 has merged - anything left before closing this P0?

**Comment by goltermann** [comment]
@pwittrock #26922 looks merged, time to close this one?

**Comment by pwittrock** [comment]
Yup.  Thanks.
