### ISSUE TITLE
Prepare projects in Jenkins for 1.3 branch

### ISSUE THREAD

**Issue by goltermann** [kubernetes/kubernetes#26798]
We're planning to branch 1.3 on June 10, so we should have all projects and quota ready to go for that date.

**Comment by spxtr** [comment]
Necessary new jobs:
```
build-1.3
test-go-release-1.3

e2e-g{c,k}e-release-1.3
e2e-g{c,k}e-serial-release-1.3
e2e-g{c,k}e-slow-release-1.3

soak-{weekly-deploy, continuous}-g{c,k}e-release-1.3
```

Delete jobs:
```
e2e-gke-ingress-release-1.2
```

Move jobs:
```
e2e-aws-release-1.2 -> 1.3
e2e-gce-scalability-release-1.2 -> 1.3
soak-{}-1.2 -> 1.3
```

**Comment by david-mcmahon** [comment]
Branch release-1.3 is now available for jenkins.

**Comment by spxtr** [comment]
Okay, the most important jobs are in. They'll fail their first run or two, but then they should go green.

**Comment by spxtr** [comment]
I need to know which feature jobs need to be created. For 1.2 this was a problem, so if someone doesn't definitively say what to do I'll bother people.

**Comment by goltermann** [comment]
@spxtr, who do you need to ask?  Want to close this P0 asap.

**Comment by spxtr** [comment]
I just need to know which feature jobs need to be created for 1.3. It looks like these are candidates:
* es-logging @freehan
* ingress @bprashanth 
* petset @bprashanth 
* proto ?

**Comment by bprashanth** [comment]
Ingress needs a 1.3 branch, if we're dropping gke-ingress-1.2 we can reuse that project for gke-1.3. I'll need to allocate a new project for gce-ingress-1.3. 

PetSet is in alpha so I think testing it at HEAD should suffice.

**Comment by bprashanth** [comment]
When're we branching so I know how to prioritize this? Fyi I'm adding a lot of ingress e2es in https://github.com/kubernetes/kubernetes/pull/26821

**Comment by goltermann** [comment]
We branched Friday.  We'll probably end code slush and start cherrypicking
today.

On Mon, Jun 13, 2016 at 10:16 AM, Prashanth B <notifications@github.com>
wrote:

> When're we branching so I know how to prioritize this? Fyi I'm adding a
> lot of ingress e2es in #26821
> <https://github.com/kubernetes/kubernetes/pull/26821>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/26798#issuecomment-225647311>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AI7MjiJKTV5wDGwD6l5FrWGnQEVkggkzks5qLZBUgaJpZM4Ity2U>
> .
>



-- 

-T.J. Goltermann

**Comment by freehan** [comment]
Nothing changes for es-logging in 1.3. It should just works. 

Only problem I foreseen is GCI integration. That might cause some missing logs. But GCI has not been turned on yet on nodes. 

I guess testing at HEAD should be good enough.

**Comment by goltermann** [comment]
@smarterclayton for proto question above

**Comment by smarterclayton** [comment]
Proto is a no, we flipped the default in master.  We may add another job in the future but this one can be skipped.

**Comment by goltermann** [comment]
ETA @spxtr?  All remaining v1.3 bugs are getting a lot of attention now.
