### ISSUE TITLE
kubectl run --overrides ignores non existent fields

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#26804]
From [stackoverflow question](http://stackoverflow.com/questions/37555281/create-kubernetes-pod-with-volume-using-kubectl-run/37621761), the user was adding `"containers"` to the wrong object. Rather than reporting an error, the mismatched fields were silently ignored.  More generally, any arbitrary fields added (`"foo": "bar",`) are silently ignored, making the config difficult to debug.

**Comment by pwittrock** [comment]
cc @janetkuo @AdoHe

@lavalamp Is there any reason we want this behavior from the api machinery perspective, or does this sound like it is just a bug

**Comment by lavalamp** [comment]
kubectl run should do validation just like create -f, since it apparently
allows users to specify field snippets. This sounds like a recipe for
unmaintainable scripts IMO, I think that's an anti-feature...

**Comment by AdoHe** [comment]
kubectl run has no validation logical compared with other commands, maybe we should enable this here.

**Comment by vefimova** [comment]
Hi, working on this one.

**Comment by AdoHe** [comment]
@vefimova thanks, just go ahead and if you have any problem, just comment here.

**Comment by tallclair** [comment]
:boom:
