### ISSUE TITLE
Add a Make rule to run node e2e on remote hosts

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#26808]
There is an exiting [script](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/jenkins/e2e-node-jenkins.sh) that makes it possible to run node e2e on GCE VMs. It is not easily discover-able and requires understanding of a template to use it.
For new contributors, a simple make rule that runs tests against a preset GCE VM image will be helpful.

We can choose a standard image to run tests against and also make the image configurable.
We can preserve the VMs and re-use it when the same image is used for testing.

**Comment by pwittrock** [comment]
Fixed in #26832
