### ISSUE TITLE
Running DaemonSet only on Schedulable Nodes

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#26810]
Today, DaemonSet Pods will be scheduled even on nodes that are marked `SchedulingDisabled` (`node.spec.unschedulable==true`).

Is there an out-of-the-box way to use a selector to select only schedulable nodes? Or is the user required to manually label their nodes and then use an appropriate selector?

CC: @theobolo

**Comment by dchen1107** [comment]
cc/ @Random-Liu We ran into the similar issue with node problem detector.

**Comment by Random-Liu** [comment]
XRef https://github.com/kubernetes/node-problem-detector/pull/13 for similar issue we encountered in node problem detector.

**Comment by therc** [comment]
For the record, I have been relying on this behaviour for months. I have kubelet running on my master nodes with --register-schedulable=false. That way, normal pods won't schedule, but the fluentd DaemonSet does.

**Comment by colemickens** [comment]
Yes, I need the same thing. I'm not proposing changing that behavior, just adding some sort of label for `--register-schedulable=false` machines that can be easily used in a DaemonSet selector. (Or documentation of it if such a label already exists.)

**Comment by lukaszo** [comment]
I believe it's tracked here #22205

**Comment by colemickens** [comment]
I believe that #22205 is about having the scheduler respect affinity contraints for daemonset pods.

In this case, the scheduler already knows how to use node selectors... I'm just seeking to have kubelet automatically label nodes that are marked `--register-schedulable=false` so that I can use that label in the daemonset's node selector.

(Unless there's already a label/mechanism to do this?)
