### ISSUE TITLE
Unit test flake: k8s.io/kubernetes/plugin/pkg/client/auth/oidc

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#26815]
I hit a test flake in `k8s.io/kubernetes/plugin/pkg/client/auth/oidc`

Example build: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26807/kubernetes-pull-test-unit-integration/29103/

**Comment by fejta** [comment]
Assigning to @cjcullen per spreadsheet

**Comment by lavalamp** [comment]
cc @erictune

**Comment by erictune** [comment]
Failure log:
```
--- FAIL: TestNewOIDCAuthProvider (2.70s)
	oidc_test.go:152: case 1: unexpected error on newOIDCAuthProvider: open /tmp/oidc-cert: no such file or directory
```

Most likely there are two unit tests using this file running in parallel and they raced.

@mml

**Comment by mml** [comment]
Robot more optimistic than my "May fix #XXX" message warrants, but OK.  If this occurs again, please reopen.
