### ISSUE TITLE
Possible Bug: Deployment Rollout History Missing Deployments

### ISSUE THREAD

**Issue by osterman** [kubernetes/kubernetes#26818]
## background

We're running deployments in a CI/CD context. Sometimes there will be two commits in rapid succession triggering nearly back-to-back deployments. When we observe the `kubectl rollout history` we are missing some deployments. These are likely caused when two deployments happen at/around the same time.
## the problem
- running `kubectl rollout history deployment <something>` does not show all deployments
- running `kubectl apply -f <deployment>` returns success and indicates success (e.g. `deployment "edge-router" configured`) even if it is not represented in the rollout history.
## our expectation
- if `kubectl` returns `deployment configured` then there should be a corresponding entry in the `rollout history` otherwise return an error
- ideally, `kubectl` should output the revision that was created e.g. `deployment "edge-router" configured (revision 1234)`
## how to reproduce
1. create a deployment resource
2. add a tag like `serial: $SERIAL`
3. use the following script

```
serial=0
while true; do
  serial=$(($serial + 1))
  echo $serial
  sed "s/\$SERIAL/$serial/g" /tmp/test-deployment.yml | kubectl apply -f -
done
```
1. inspect each revision (E.g. `kubectl rollout history deployment test --revision 1`, then check 2, 3, 4, 5)
2. Notice that at some point, a serial will be lost. It seems to get worse the longer the script runs.
## screenshots

Do a bunch of deployments. Output from `kubectl` indicates success. 
![image](https://cloud.githubusercontent.com/assets/52489/15793592/dd3171c0-2999-11e6-83fb-918d2917be94.png)

Check each revision. Notice that 7 & 8 are missing. If I continue iterating over the rest of the revision, I find even bigger gaps and no deployment for 7 or 8. In fact, I ran 100+ deploymemnts and the rollout history has only 33 entries. 

![image](https://cloud.githubusercontent.com/assets/52489/15793572/bed71234-2999-11e6-810a-12713f6b172e.png)

**Comment by osterman** [comment]
Possibly related: https://github.com/kubernetes/kubernetes/issues/26673

**Comment by janetkuo** [comment]
@kubernetes/deployment

**Comment by janetkuo** [comment]
I believe this is due to race. The configured deployment is configured again before the deployment controller observe the last change, and thus the change is overwritten/lost.

**Comment by kargakis** [comment]
I am not sure this is a bug. The events generated by etcd will end up being compressed when they are coming fast through the watch so the deployment controller observes state and not separate mutations. If you want your separate mutations to be observed, you need to poll d.status.observedGeneration between mutations ie. d.generation == d.status.observedGeneration means that the controller has observed the latest state.

**Comment by kargakis** [comment]
Another reason for missing history is rollbacks. When you rollback the old replica set becomes the new thus you lose the information that you had an old replica set. Fortunately, we added a new annotation that stores old revisions a replica set has served in https://github.com/kubernetes/kubernetes/pull/34249. I am still not convinced about exposing this to `kubectl rollout history` though..
