### ISSUE TITLE
detach EBS volumes when node restarted

### ISSUE THREAD

**Issue by Thermi** [kubernetes/kubernetes#26847]
Hello,

Currently, kubernetes does not try to (force) detach EBS volumes after a node was restarted.
This leads to the situation that pods that require an EBS and are started on another node do not come up. To fix that, the user has find the EBS volumes and (force) detach them, so that kubernetes can attach them to the node that the pod is supposed to run on. 
A solution to this problem would be to track the EBS volumes that are desired by the pods (or the RCs) and to force detach those from nodes that restarted.

Please review this proposal and/or develop another solution, because this really causes issues in my setup.

Best regards,
Thermi

**Comment by IanLewis** [comment]
This may be related to #14642 and possibly fixed in #25457 and #26351 (1.3).

**Comment by saad-ali** [comment]
This is fixed in v1.3 by https://github.com/kubernetes/kubernetes/pull/26351
