### ISSUE TITLE
The file "resourcequota" in docs/user-guide/resourcequota path can't be found

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#26844]
The file "resourcequota"  URL is http://kubernetes.io/docs/admin/resourcequota/, not http://kubernetes.io/docs/user-guide/resourcequota/.

Maybe we shoud delete https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/resourcequota. Because it references http://kubernetes.io/docs/user-guide/resourcequota/, but we get an "404 Error!" page.

**Comment by a-robinson** [comment]
cc @johndmulhausen
