### ISSUE TITLE
make launch-kube - No response

### ISSUE THREAD

**Issue by ChaiBapchya** [kubernetes/kubernetes#26842]
Following the steps mentioned in - https://github.com/pachyderm/pachyderm/blob/master/SETUP.md

After cloning the pachyderm repo from git,
the command - make launch-kube gets stuck;
On first run, it couldn't find image locally hence pulled it;
Status showed download complete
However it hangs there/snaps. No response henceforth
Waited for 40 minutes

root@localhost pachyderm]# make launch-kube
etc/kube/start-kube-docker.sh
Unable to find image 'gcr.io/google_containers/hyperkube:v1.2.2' locally
v1.2.2: Pulling from google_containers/hyperkube
81cc5f26a6a0: Pull complete
a3ed95caeb02: Pull complete
063437597255: Pull complete
b4020ee389e8: Pull complete
89b2db79f15b: Pull complete
df40237c8d23: Pull complete
d475cf290f14: Pull complete
9fb4d210982d: Pull complete
f23e487dc7e4: Pull complete
c110bb056d31: Pull complete
7f996656b2e2: Pull complete
8ea8f63d36ec: Pull complete
c6a923a7896b: Pull complete
9fcfc590bc83: Pull complete
da14f8f2d525: Pull complete
Digest: sha256:c2de5dbedfd1864048fa399185b56a302fd07f886ce94e08220b89802196c787
Status: Downloaded newer image for gcr.io/google_containers/hyperkube:v1.2.2
efb9798117aea548560ef34d5e10d23407a17aa298c61926b89460b7674b3841
![make launch-kubehang](https://cloud.githubusercontent.com/assets/10992635/15798800/a057128a-2a63-11e6-99bd-7933cce60b6a.png)

**Comment by a-robinson** [comment]
Seems as though you'll be best off asking your question on the pachyderm repo or on StackOverflow. Sorry!

**Comment by ChaiBapchya** [comment]
Actually the error seemed to be in the code for make launch-kube. Hence posted in the kubernetes github. With much work, glitch was with the pachyderm installation and dependency conflict. Thanks anyway
