### ISSUE TITLE
Shard apiservers by resource type

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#26853]
API server cacher should have some locality property
-------------------

Currently, we have a cache layer in API server, which is responsible for serving WATCH and LIST requests. But the cacher will cache for ALl kinds of resources. IMO, since we have multi API server, the cacher should have locality property. Le me explicate it with an example, I have 3 API servers, and I configure the nginx/haproxy as: 

* API server A is dedicated for all Pod related requests by default, API server B and C are backups when A is unhealthy
* API server B is dedicated for all Node related requests, A and C are backups.
* API server C is dedicated for other requests, A and B are backups.

In such a case, It's fine that API server A just cache for Pod, right? Cache for ALL resources works though, it consumes much more memory and cpu, build more connections to etcd server. Hence, I suggest the cacher works as follows:

* Only start caching(list&watch form etcd) when server the first LIST/WATCH request. If it never server any LIST/WATCH requests about a resource, it does not need cache for it.

* Have expiration policy. For example, if it has not server any LIST/WATCH requests about a resource for a long time(this could be configurable), stop caching for that resource and free the memory it used.

Just my thoughts for discussion. I could also work on it if it sounds good.

@kubernetes/sig-scalability

**Comment by mqliang** [comment]
@bgrant0607 I'd like hear your opinion about this.

**Comment by wojtek-t** [comment]
I think this bug is not about locality from cacher - this would be super easy to do. I think the real request here is to configure the cluster so that, the requests will be send to appropriate apiservers.

But I think that this is more longer-term issue - we are not focusing actively on HA setups right now.

**Comment by davidopp** [comment]
This would actually make HA harder, because you'd have to inform the clients about the failover policy (the three bullet points at the beginning of the first entry in this issue). The current policy where in HA configuration any client can send to any API server replica just requires the client to know the identities of the servers, and pick any that is "up".

**Comment by wojtek-t** [comment]
That's a good point. 

Also, I would like to understand the motivation here. Are you trying to reduce amount of RAM used by apiserver? [If so, this still wasn't a goal for us, and there are probably easier way to achieve this.]

**Comment by mqliang** [comment]
@wojtek-t 
> I think this bug is not about locality from cacher - this would be super easy to do.

It not a bug actually. It's just an optimization. And yes, it'd not hard to do.

> But I think that this is more longer-term issue - we are not focusing actively on HA setups right now.

Yeah, it's not urgent now. But it would be much helpful(less cpu, less mem, less networking burden) if the cacher just cache for the resources it serves. 

> Also, I would like to understand the motivation here. Are you trying to reduce amount of RAM used by apiserver? [If so, this still wasn't a goal for us, and there are probably easier way to achieve this.]

Not only memory, but also cpu, networking, and burden to etcd. And the most important issue is about my understanding of cache: cache are always have locality property and have cache hit/miss. Let my explicate it with an extreme example: assume we have 1TB disk and we take RAM as a cache layer for disk, should we need a 1TB RAM to cache all the data on disk?

**Comment by mqliang** [comment]
@davidopp 
> This would actually make HA harder, because you'd have to inform the clients about the failover policy (the three bullet points at the beginning of the first entry in this issue). 

Oh, I think I should be more specific. I don't mean configure API server so that it just cache for one(or some) resource.  And clients also do not need know about the failover policy. I configure the nginx/haproxy so that it forward a request to it's dedicate API server. 

> The current policy where in HA configuration any client can send to any API server replica just requires the client to know the identities of the servers, and pick any that is "up".

It works. If client send(or nginx forward) requests randomly, the API server will cache for all resources. The current cacher will start caching for all resources when it start. I propose to call [startCaching](https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L184-L193) when cacher serve the first LIST/WATCH request. So, if one API server never any request about a resource, it will not caching for that resource. If client send(or nginx forward) requests randomly, the API server will cache for all resources.

**Comment by davidopp** [comment]
You only get the efficiency property if all the clients know the policy. If you have even one client that picks randomly, then eventually all the objects get populated in all the API server caches. I think the extra complexity is only justified if it is really making the API server replicas more efficient. But as @wojtek-t said, it's not clear there's actually a problem right now.

**Comment by mqliang** [comment]
@davidopp 
> You only get the efficiency property if all the clients know the policy. If you have even one client that picks randomly, then eventually all the objects get populated in all the API server caches.

Why is it not enough to just let nginx/proxy to know the policy, I configure the API server address as the address of nginx/proxy for all clients, and let nginx/proxy forward all the requests.

> it's not clear there's actually a problem right now.

Year, no big problem now. Just too many memory usage(especially when user add a looot of third-party resources), and may bring down API server by OOM. We could always use a larger RAM, after all, hardwares are really cheap now. But, I'd like implement what I proposed, since it not hard to do.

**Comment by xiang90** [comment]
@mqliang If the resource usage is a concern, especially memory. One thing we (k8s team at CoreOS) are considering to do is to cache all objects effectively. We did some benchmark and found API + controller used a few times more memory than etcdv3 server.  There could be a low hanging fruit somewhere.

**Comment by mqliang** [comment]
@xiang90 Did you guys do the benchmark with SharedInformer in controller? Before we have the SharedInformer, controller will cache Pod multi times.

**Comment by xiang90** [comment]
@mqliang Also some thoughts for the 3rd party resources, if you start to store a loooot of these etcd2 server would suffer first. Even if you switch to etcd3, probably you cannot expect to have 10Xpods or more than 1KB/pods. I am not sure the desired direction of 3rd party resources, but as long as the backend store is still non-sharded etcd, it is limited. The scalability of a non-sharded etcd is limited by the speed of a single disk/cpu hardware, not the size of the disk nor the number of cores. 

Personally, I dislike the idea of putting a lot of data as 3rd party resources. Basically, you are start to use k8s as a generic key/value store or even an object store.

I mentioned this here since I have heard a few users want to store a loooot of 3rd party resources.

/cc @philips

**Comment by xiang90** [comment]
@mqliang Yes. We do.

**Comment by mqliang** [comment]
@xiang90 
> Also some thoughts for the 3rd party resources, if you start to store a loooot of these etcd2 server would suffer first

> Basically, you are start to use k8s as a generic key/value store or even an object store.

We use dedicate etcd cluster for those 3rd party resources. Just like use a dedicate etcd cluster for events.

> We did some benchmark and found API + controller used a few times more memory than etcdv3 server. There could be a low hanging fruit somewhere.

The only place I could think of is: the cache in client is a two-level design. The cache have a [DeltaFIFO](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/framework/shared_informer.go#L124) ad as a queue, and have a [Indexer](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/framework/shared_informer.go#L69) to save all datas. So API/controller will use at least 2 times memory than etcd.

**Comment by wojtek-t** [comment]
I generally agree with @xiang90 - we need to define a problem and solve the problem, instead of thinking about fancy solution and then trying to argument why it would be useful.

Basically, if we decide that the problem is e.g. memory, we should try to first find all low-hanging fruits, which I'm 100% sure there are some.

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
We have a *lot* of low hanging fruit today - for instance, not using shared caches in admission controllers (PR opened a few days ago), not using shared caches in the controllers, which consume a lot more memory right now than the etcd cache.

**Comment by lavalamp** [comment]
I think this is a request for sharding. I think it will be easy to set that up in the future, once we have the discovery summarizer & proxy running, just by running multiple apiservers and directing different resources to them. I don't think we should focus on this yet as it add significant system complexity.

Also, after we switch to etcd3, there's some chance we could remove the apiserver cache completely? We should experiment with that. We should be able to soon get rid of the serialization cache, at the very least.

**Comment by lavalamp** [comment]
I edited the title of this issue to make it clearer.

**Comment by timothysc** [comment]
Why not just configure session affinity on your load-balancers?

**Comment by mqliang** [comment]
> Why not just configure session affinity on your load-balancers?

Yeah, this is what exactly I mean by " configure the nginx/haproxy as ..."(I am not a native english speaker). But event if we configure session affinity on load-balancers, current cacher in API server will still cache for all resource type. That's why I propose to " start caching when cacher serve the first LIST/WATCH request" and have some expiration policy.

**Comment by timothysc** [comment]
I'd like to 1st try to optimize the efficiency of the caching itself https://github.com/kubernetes/kubernetes/issues/27053
