### ISSUE TITLE
High Availability: kubelet doesn't try to talk to a different API server in case of failures

### ISSUE THREAD

**Issue by ovidiucp** [kubernetes/kubernetes#26852]
I setup a highly available Kubernetes cluster on some physical machines. On the `m1a` node machine I run kubelet this way:

```shell
/usr/local/bin/hyperkube kubelet \
 --logtostderr=true \
 --hostname-override=m1a \
 --api-servers=http://m1b:8080,http://m1c:8080,http://m2a:8080,http://m2b:8080,http://m2c:8080 \
 --cluster-domain=cluster.local \
 --tls-cert-file=/srv/kubernetes/kubelet.crt \
 --tls-private-key-file=/srv/kubernetes/kubelet.key \
 --node-ip=172.17.0.3 \
 --v=10
```

I then kill the API server on machine `m1b` which is the first API server specified in `--api-servers`. The expected behavior would be for the kubelet to detect the failure and try to connect to a different API server.

Instead the kubelet keeps trying to connect indefinitely to m1b:

```
E0604 20:45:34.506189   13655 reflector.go:271] pkg/kubelet/kubelet.go:259: Failed to watch *api.Node: Get http://m1b:8080/api/v1/watch/nodes?fieldSelector=metadata.name%3Dm1a&resourceVersion=32575&timeoutSeconds=452: dial tcp 172.17.0.4:8080: connection refused
E0604 20:45:34.506202   13655 reflector.go:271] pkg/kubelet/kubelet.go:240: Failed to watch *api.Service: Get http://m1b:8080/api/v1/watch/services?resourceVersion=32289&timeoutSeconds=501: dial tcp 172.17.0.4:8080: connection refused
E0604 20:45:35.229843   13655 kubelet.go:2745] Error updating node status, will retry: error getting node "m1a": Get http://m1b:8080/api/v1/nodes/m1a: dial tcp 172.17.0.4:8080: connection refused
...
E0604 20:45:35.237364   13655 kubelet.go:2745] Error updating node status, will retry: error getting node "m1a": Get http://m1b:8080/api/v1/nodes/m1a: dial tcp 172.17.0.4:8080: connection refused
E0604 20:45:35.237393   13655 kubelet.go:1183] Unable to update node status: update node status exceeds retry count
...
```

The result of this is that all the nodes in the cluster that list `m1b` first in the list of API servers move in the state `NotReady`, which is not really necessary. In a real production cluster with hundreds of machines this becomes a real issue.

Could we implement a reusable library that knows how to talk to API servers, that load balances the requests across them, is resilient to such transient failures, and can try reconnecting to dead API servers?

Other servers that could benefit from this library are the proxy, the scheduler, and the controller manager. All these servers can only talk to one master using the `--master` flag.

**Comment by robvalk** [comment]
We've encountered the same symptoms after an AWS outage in the ap-southeast-2 region.
kubelets were configured with a list of api server addresses. The first api server in the list failed but none of the kubelets failed over to a secondary server. This caused a full cluster outage since the remaining masters incorrectly assumed all nodes had failed.

**Comment by keontang** [comment]
Besides, for `proxy`, `scheduler` and `controller manager`, maybe we should change **`--master`** to **`--masters`** flag to support multiple api-servers.

> Other servers that could benefit from this library are the proxy, the scheduler, and the controller manager. All these servers can only talk to one master using the --master flag.

**Comment by yujuhong** [comment]
Closing this in favor of #18174.
