### ISSUE TITLE
kubernetes-e2e-gce-master-on-cvm has been broken since 5/31

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#26850]
We have a test suite called `kubernetes-e2e-gce-master-on-cvm` running to allow us to, in theory, switch back from GCI masters to Container VM masters at any point. 

We succeeded at http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-master-on-cvm/lastStableBuild/ (c1c0567e37b699) and then failed at http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-master-on-cvm/338 (ee412efcefc75b), and it's all consistently DNS related issues, so I'm pretty sure #26335 broke this suite entirely.

It's also somewhat blocking me from evaluating a new version of Container VM, but not really - I think we're safe to evaluate it on nodes only for now.

cc @roberthbailey @thockin

**Comment by zmerlynn** [comment]
An alternate resolution to this bug is that we abandon CVM masters entirely in open source, but that's a larger decision.

**Comment by roberthbailey** [comment]
We want to keep CVM working for now (which is why I stuck this test into the 1.3 tab in Jenkins). 

@girishkalele -- can you please take a look tomorrow?

**Comment by girishkalele** [comment]
I'll fix it - should be straightforward - #26335 actually was to fix the breakage in DNS when we moved to GCI masters, the skydns yaml files were moved and the dns pod is probably not even starting up in CVM masters.

**Comment by girishkalele** [comment]
@zmerlynn 

Is there a way I can ask the testbot to trigger this specific Jenkins (CVM-on-Master) test on my pull request ?

The fix is simple - svc and rc DNS files were renamed.

```
Jun  6 17:03:48 jenkins-e2e-master startupscript: [INFO    ] Executing state file.managed for /etc/kubernetes/addons/dns/kubedns-svc.yaml
Jun  6 17:03:48 jenkins-e2e-master startupscript: [ERROR   ] Unable to cache file 'salt://kube-dns/kubedns-svc.yaml.in' from saltenv 'base'.
Jun  6 17:03:48 jenkins-e2e-master startupscript: [ERROR   ] Source file salt://kube-dns/kubedns-svc.yaml.in not found
Jun  6 17:03:48 jenkins-e2e-master startupscript: [ERROR   ] Unable to cache file 'salt://kube-dns/kubedns-rc.yaml.in' from saltenv 'base'.
Jun  6 17:03:48 jenkins-e2e-master startupscript: [ERROR   ] Source file salt://kube-dns/kubedns-rc.yaml.in not found
```

**Comment by zmerlynn** [comment]
@girishkalele: No, but it's easy to `kube-up` a CVM master (just override KUBE_OS_DISTRIBUTION to `debian`), and if it's just detecting whether DNS comes up, you can just do it manually fairly fast.

**Comment by girishkalele** [comment]
Got an error setting just the KUBE_OS_DISTRIBUTION flag.
'''
 - Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/google-containers/global/images/debian-8'. The referenced image resource cannot be found.
'''

Then, I set all image related KUBE variables to the below and the master doesn't get ready.

KUBE_GCE_NODE_IMAGE=container-v1-3-v20160604
KUBE_GCE_MASTER_IMAGE=container-v1-3-v20160604
KUBE_OS_DISTRIBUTION=debian

**Comment by zmerlynn** [comment]
@girishkalele: That last set is exactly what `kubernetes-e2e.yaml` sets, so I'm not sure what's different with you and Jenkins:
```
                export KUBE_OS_DISTRIBUTION="debian"                                                                         
                export KUBE_GCE_MASTER_IMAGE="container-v1-3-v20160604"                                                      
                export KUBE_GCE_NODE_IMAGE="container-v1-3-v20160604"                                                        
```

**Comment by girishkalele** [comment]
The Debian debian-8 images are not visible when I do ```gcloud compute instances list``` as myself. 

I think it is not accessible to folks who don't have read perms for google_containers.

**Comment by zmerlynn** [comment]
That shouldn't be launching `debian-8` at all.

**Comment by girishkalele** [comment]
Closed via https://github.com/kubernetes/kubernetes/pull/26902

Merged at 2:09 PM, Jenkins jobs started passing right after.
