### ISSUE TITLE
Service endpoints MIA after network blip

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#26865]
Spun off from https://github.com/kubernetes/contrib/issues/297. GKE user had working endpoints, then something happened and they ended up with working, ready pods but unready endpoints (https://github.com/kubernetes/contrib/issues/297#issuecomment-223837365). Restarting all pods seems to have fixed it, this is obviously a very drastic counter measure. 

@MaxDaten @kubernetes/goog-gke

**Comment by offlinehacker** [comment]
Ok, today i woke up, and `/etc/resolv.conf` was empty on one of the gke nodes, and of course load balancer was unable to get token.

**Comment by bprashanth** [comment]
@offlinehacker was the token issue just dns again? resolv.conf was empty on the vm itself or inside a pod?

**Comment by bprashanth** [comment]
We fixed a couple of issues in this space (eg: https://github.com/kubernetes/kubernetes/pull/30828), please reopen if it happens again
