### ISSUE TITLE
GCE loadbalancer

### ISSUE THREAD

**Issue by SephVelut** [kubernetes/kubernetes#26883]
I can't get a client's ip when using the loadbalancer service with GCE to hook into my app. Reading `x-forwarded-for` and trying other methods, I'm only able to obtain an internal cluster ip. Is there a way to allow services to send the client ip in ip related headers when they route traffic?

**Comment by pigmej** [comment]
I don't want to sound abusive but you should use StackOverflow for asking questions @SephVelut :) Github bugs are not for questions now.

**Comment by SephVelut** [comment]
Not at all. I should have posted on SO. I'll close issue.
