### ISSUE TITLE
Init containers are in CrashLoopBackOff but RESTARTS count is still 0

### ISSUE THREAD

**Issue by lukaszo** [kubernetes/kubernetes#26892]
The output looks like below:

```
NAME            READY        STATUS                  RESTARTS            AGE
zoo-0          0/1          Init:CrashLoopBackOff   0                   19m
```

What is expected behavior? Does restart counter should increase when init containers are failing? Does restart counter should be reseted when InitContainer will start work and normal containers start?

cc @smarterclayton

**Comment by smarterclayton** [comment]
Restarts are tracked per container - I'd be concerned that the restarts the user is concerned with don't map exactly to the init container restarts, although knowing how many attempts to init have been made are useful.  Since init containers are processed serially, when an init container passes, do we reset the restart count to zero?

I think we could show the current init container restart count (if pod is in init) in this field.  But once the init container succeeds it has to drop back to zero.

**Comment by lukaszo** [comment]
For normal containers `RESTARTS` field shows the sum of `RestartCount` from containers status.

I think for init containers as we know which container is running (when #26829 is merged) we can show restart count for current init container. 
For normal containers behavior should not change.
So it would look like these:

_First init container is failing_
```
NAME            READY        STATUS                  RESTARTS            AGE
zoo-0          0/2          Init:CrashLoopBackOff   5                   19m
```

_Second init container is failing_
```
NAME            READY        STATUS                  RESTARTS            AGE
zoo-0          1/2          Init:CrashLoopBackOff   3                   19m
```

_Normal container is failing_
```
NAME            READY        STATUS                  RESTARTS            AGE
zoo-0          1/2          CrashLoopBackOff   2                   19m
```

For better readability we may also add `init` word like in status:
_Second init container is failing_
```
NAME            READY        STATUS                  RESTARTS            AGE
zoo-0          1/2          Init:CrashLoopBackOff   Init:3                   19m
```

What do you think?

**Comment by smarterclayton** [comment]
Yeah, although I don't know that we need the Init prefix in the status.  I
think users can reasonably be expected to infer that RESTARTS is
subordinate to STATUS.  The init prefix makes it harder to read without
adding a ton.

**Comment by lukaszo** [comment]
Ah, I messed up. `READY` shows status of normal containers. `Init:1/2` in Status shows status of init containers: I think this part should be always showed. 
So it will look like these: 
```
NAME            READY        STATUS                  RESTARTS            AGE
zoo-0          0/2          Init:1/2:CrashLoopBackOff   Init:3                   19m
```

What do you think?

**Comment by lukaszo** [comment]
Ok, I decided to use the same approach as for normal containers. RESTARTS just shows sum of all init containers restarts.

**Comment by lukaszo** [comment]
Fix is merged
