### ISSUE TITLE
Probe timeout ignored by ExecAction

### ISSUE THREAD

**Issue by rhcarvalho** [kubernetes/kubernetes#26895]
I'm using a readiness probe that may take a long time to run, and I expected it to be interrupted after the specified timeout.

A probe defined like this:

``` json
"readinessProbe": {
  "exec": {
    "command": ["bash", "-c", "sleep 15"]
  },
  "timeoutSeconds": 5
}
```

Instead of timing out and failing, it is actually succeeding and ignoring the timeout.

I noticed that both `TCPSocketAction` and `HTTPGetAction` probes timeout according to the value of `TimeoutSeconds`, `ExecAction` on the other hand ignores it.

Looking at the code:

`if p.Exec != nil`, no reference to timeout:
[pkg/kubelet/prober/prober.go#L146](https://github.com/kubernetes/kubernetes/blob/6ecfb4c8fad41156e1fbccf29ac9f5d98901e991/pkg/kubelet/prober/prober.go#L146)

`if p.HTTPGet != nil || p.TCPSocket != nil`, timeout is used:
[pkg/kubelet/prober/prober.go#L163](https://github.com/kubernetes/kubernetes/blob/6ecfb4c8fad41156e1fbccf29ac9f5d98901e991/pkg/kubelet/prober/prober.go#L163)
[pkg/kubelet/prober/prober.go#L171](https://github.com/kubernetes/kubernetes/blob/6ecfb4c8fad41156e1fbccf29ac9f5d98901e991/pkg/kubelet/prober/prober.go#L171)

**Comment by rhcarvalho** [comment]
@kubernetes/sig-node-bugs (cc @derekwaynecarr)

FYI, I haven't worked on k8s for months now, I don't know the current state of this issue, but I believe it to be interesting enough to get someone's attention.

**Comment by klausenbusk** [comment]
/reopen

I just experienced this today, so it haven't been fixed. I'm not sure why https://github.com/kubernetes/kubernetes/pull/35893 wasn't merged.

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rhcarvalho** [comment]
/reopen

Let's see if that works.

**Comment by Whitespirit0** [comment]
/remove-lifecycle rotten

I'm still seeing this.

**Comment by alston-dmello** [comment]
I still see this issue in v1.14.8.  Has this been fixed in a later version?

**Comment by mindw** [comment]
Still there in v1.16.x :(

**Comment by dims** [comment]
@tedyu can you please take a look at this?

/reopen

**Comment by tedyu** [comment]
@rhcarvalho
Do you want to continue your work in the WIP which was closed ?

**Comment by rhcarvalho** [comment]
@tedyu feel free to take it over

**Comment by tedyu** [comment]
pkg/kubelet/dockertools/exec.go has moved.
The change in WIP PR doesn't apply to pkg/kubelet/dockershim/exec.go

Let me read through the comments and try to figure out what to do.

**Comment by mikehuston** [comment]
@tedyu thanks for fixing! I also ran into this :(

For anyone looking for a workaround, I used the [timeout](https://ss64.com/bash/timeout.html) command and it seems to have the intended effect.

That is, something like..
```
"readinessProbe": {
  "exec": {
    "command": ["bash", "-c", "timeout 5 sleep 15"]
  },
}
```

**Comment by carlosalberto** [comment]
Still seeing this.

**Comment by oomichi** [comment]
I tried to reproduce this issue on Kubernetes v1.18.2 but the issue seems solved on the version.

The test sample YAML is
```
$ cat readiness.yaml 
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-exec
spec:
  containers:
  - name: readiness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - sleep 15
      timeoutSeconds: 5
```
And the readinessProbe timeout works without being ignored:
```
$ kubectl describe pod readiness-exec
...
Events:
  Type     Reason     Age                 From                         Message
  ----     ------     ----                ----                         -------
  Normal   Scheduled  2m51s               default-scheduler            Successfully assigned default/readiness-exec to kind-control-plane
  Normal   Pulling    2m51s               kubelet, kind-control-plane  Pulling image "k8s.gcr.io/busybox"
  Normal   Pulled     2m49s               kubelet, kind-control-plane  Successfully pulled image "k8s.gcr.io/busybox"
  Normal   Created    2m49s               kubelet, kind-control-plane  Created container readiness
  Normal   Started    2m49s               kubelet, kind-control-plane  Started container readiness
  Warning  Unhealthy  25s (x3 over 115s)  kubelet, kind-control-plane  Readiness probe errored: rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 5s exceeded: context deadline exceeded
```

**Comment by oomichi** [comment]
Oops, my previous comment was wrong based on kind(Kubernetes in Docker) test.
This issue still happens on v1.18.9 of actual Kubernetes cluster.

Now https://github.com/kubernetes/kubernetes/issues/94080 is active issue and please see the issue instead of this.
