### ISSUE TITLE
Ensure kubelet cgroups detection on CoreOS works reliably

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#26903]
In the past, Kubelet Summary API e2e tests have flaked on CoreOS specifically. The failure were all related to Kubelet not being able to identify its own cgroups and hence not including `kubelet` summary stats in the output of `/stats/summary`.

Running the summary tests multiple times should help reproduce this issue. `FOCUS=summary make test_e2e_node`.

https://github.com/kubernetes/kubernetes/pull/26586#issuecomment-224017858

cc @euank @yifan-gu @derekwaynecarr

**Comment by derekwaynecarr** [comment]
I suspect this is a problem for how the kubelet is launched on CoreOS since CoreOS does not actually use a `user.slice`.  Let me spin up a CoreOS image to take a look as well.

**Comment by derekwaynecarr** [comment]
I did the following:

* Start CoreOS stable 1010.5.0 
* Run https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/environment/setup_host.sh
* Reboot machine
* Verified CPU Accounting and Memory Accounting were enabled by default (systemctl show systemd) and see `CPUAccounting=yes` and `MemoryAccounting=yes`.

If I run anything via SSH on this box, I see I get cgroups like the following:

```
cat /proc/1389/cgroup
9:memory:/system.slice/system-sshd.slice/sshd@0-10.240.0.6:22-74.125.42.99:43656.service
8:freezer:/
7:blkio:/system.slice/system-sshd.slice
6:devices:/system.slice/system-sshd.slice
5:perf_event:/
4:net_cls,net_prio:/
3:cpuset:/
2:cpu,cpuacct:/system.slice/system-sshd.slice/sshd@0-10.240.0.6:22-74.125.42.99:43656.service
1:name=systemd:/system.slice/system-sshd.slice/sshd@0-10.240.0.6:22-74.125.42.99:43656.service
```

As you can see memory, cpu and name cgroups all are equivalent:
`/system.slice/system-sshd.slice/sshd@0-10.240.0.6:22-74.125.42.99:43656.service`

Which should be valid per https://github.com/kubernetes/kubernetes/pull/26586

I am not sure what is different with my procedure and our e2e setup.

**Comment by vishh** [comment]
AFAIK, there are no issues with the image itself. I suspect issues with
kubelet detection of systemd cgroups.

Check out #26832 which should make it easy to run e2e against the CoreOS
image that node e2e currently uses.

**Comment by pwittrock** [comment]
FYI, you can also create an instance using the coreos image using

```sh
gcloud compute instances create <name> --image=e2e-node-coreos-stable20160218-image --image-project=kubernetes-node-e2e-images
```

**Comment by euank** [comment]
@pwittrock That's an old image, the current node_e2e was using `e2e-node-coreos-stable20160531-image` which I don't think is publicly shared. Listing images from the `kubernetes-node-e2e-images` project gets me the older one you reference above, not the current one of interest.

**Comment by derekwaynecarr** [comment]
@pwittrock - that must be the old image... i spun up an instance and it did not have accounting enabled.

**Comment by derekwaynecarr** [comment]
@euank I am happy to help look at this when the image is made public.

**Comment by pwittrock** [comment]
Yes, I see that it is.  Just copied over the new image used by https://github.com/kubernetes/kubernetes/blob/015bc3d60d9ae3f8bb4b6cdc615d23ed086c28ba/test/e2e_node/jenkins/jenkins-ci.properties.

**Comment by euank** [comment]
@derekwaynecarr and i did a little further investigation today (thanks for the help!), and I wanted to update with what I observed here:

With CPU/Mem accounting, the kubelet detects a cgroup slice of something like `/system.slice/system-sshd.slice/sshd@2532-10.240.0.15` when run via ssh (as in the node_e2e test). This differs slightly from the key in the [info map](https://github.com/kubernetes/kubernetes/blob/6a388d4a0d9e7fc2549ab89c97bf29ce53982e39/pkg/kubelet/server/stats/summary.go#L69) returned from cadvisor which has `/system.slice/system-sshd.slice/sshd@2532-10.240.0.15:22-209.251.245.232:59644.service` as the only item with the `2532` identifier in it.

More investigation might be needed, but this also can be lowered from p1 once the above-referenced PR is merged (node-e2e coverage of this is enabled again) since this issue shouldn't impact anyone running kubelet as a systemd unit or as part of a container solution that sets up a sane cgroup hierarchy for it.

**Comment by derekwaynecarr** [comment]
I think we should update the e2e to run the service using systemd-run so
it's launched as a transient unit and can be reliably accounted under
something like kubernetes.slice.

I can see how easy or hard that is do to do in the current framework
tomorrow.

**Comment by euank** [comment]
After a little further thought about the problem, note that the `/proc/pid/cgroup` file has the longer string and contains a ':'. I hunted down the runc code that `container_manager_linux` calls for this [here](https://github.com/opencontainers/runc/blob/e40e71f521f4fcc2c0ef817fa38161d72635b113/libcontainer/cgroups/utils.go#L265) and noticed that they Split on ':', not SplitN or such. That explains how a line in `/proc/x/cgroup` of `1:name=systemd:/system.slice/system-sshd.slice/sshd@2532-10.240.0.15:22-209.251.245.232:59644.service` lost the trailing bit for the kubelet, while cadvisor includes that trailing bit.

**Comment by derekwaynecarr** [comment]
@euank  - nice detective work.

**Comment by philips** [comment]
Yes, nice work @euank!

**Comment by philips** [comment]
@euank what is the resolution on this?

**Comment by euank** [comment]
xref: https://github.com/coreos/bugs/issues/1435 #28407 https://github.com/opencontainers/runc/issues/931

The original issue this was filed over was solved by running the kubelet as a unit during these tests.

There's still some issues with detection that are tracked in the above, but we should be able to close this.

**Comment by euank** [comment]
There was an additional issue related to this, specifically the issue discussed in https://github.com/google/cadvisor/pull/1792. I think this is safe to close

/close
