### ISSUE TITLE
Missing watch event for new namespace

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#26911]
When watching events in global namespace (`/v1/events?watch=true`) no create event is received for new namespaces. Subsequent events for resources created in these new namespaces are received correctly.

/cc @buildlackey

**Comment by liggitt** [comment]
no Event object is intended to be recorded when a namespace is created

**Comment by liggitt** [comment]
Event objects are reported separately from object creation, and only by some object creators (typically controllers, to report on what they are doing)
