### ISSUE TITLE
Address outstanding DNS review comments in #26694

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#26921]
See https://github.com/kubernetes/kubernetes/pull/26694 for details.  Specifically:
1. Don't call ensureDnsRecords() if the DNS provider has not been initialized.
2. Don't discard errors returned by getClusterZoneNames()

cc: @mfanjie FYI

**Comment by goltermann** [comment]
@quinton-hoole this is P2...time to punt to v1.5?

**Comment by quinton-hoole** [comment]
@golterman Yes, 1.5 is fine.  I seem to have lost the authority to update the Milestone?  Did you perhaps change permissions?

**Comment by goltermann** [comment]
I moved it - no idea why you wouldn't have permission on the kubernetes repo.

**Comment by dims** [comment]
ok to move this to 1.6? please holler if not appropriate

**Comment by quinton-hoole** [comment]
Reassigning to @nikhiljindal in case he wants to address this in future.  @mfanjie would also be a suitable candidate.

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by marun** [comment]
Not a release blocker for 1.7.

**Comment by irfanurrehman** [comment]
This issue was labelled only for sig/multicluster and is thus moved over to kubernetes/federation#48.
If this does not seem to be right, please reopen this and notify us @kubernetes/sig-multicluster-misc.
/close
