### ISSUE TITLE
Wish kubernetes had a simple LB / ingress solution

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubernetes#26928]
I just want easier to using Load balancer /ingress for my pods/service with kubernets.

```
kubectl portmapper -t tcp node1:80  nginx-svc
```
or
```
kubectl portmapper -t tcp node1:80  nginx-svc:80
```

A command like this will forward node1 port 80 to service nginx-svc default port

-t means protocol type tcp/udp/icmp or what ever.

node1 was Kubernete node name, 80 was the port number.
nginx-svc was my service name, it can be like a nginx inside container.

**Comment by paralin** [comment]
This already exists in Ingress, Services (with NodePort), etc. I think abstracting it to a single command like that would likely not fit well with Kubernetes' resource and object based config patterns.

Have you tried using ingresses?

**Comment by netroby** [comment]
I failed to configure ingress, failed to configure with load balancer. I deploy kubernetes with my local machine.

The NodePort can only expose port in a higher range, with up 30000, but we want to expose normal port, like 80,3306,443.

**Comment by pigmej** [comment]
@netroby have you seen: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx ?
It's very easy to do stuff that you want there
Also for LB: https://github.com/kubernetes/contrib/tree/master/service-loadbalancer it's also quite simple.

In both cases you just need service and properly pass it into ingress/LB.

**Comment by jlowdermilk** [comment]
@netroby it seems solutions for your use case exist, but maybe are not well documented. If you have specific setup problems, recommend posting for help on [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).
