### ISSUE TITLE
Implement "local" as a regular KUBERNETES_PROVIDER

### ISSUE THREAD

**Issue by nhlfr** [kubernetes/kubernetes#26937]
When discussing the issue #26453, we came to conclusion that we should get rid of `hack/local-cluster-up.sh` script in favor of `cluster/kube-up.sh` which will do the same if the value of KUBERNETES_PROVIDER env var is set to `local`.

That will increase consistency - after setting up the KUBERNETES_PROVIDER user will be able to do just `cluster/kube-up.sh` and `cluster/kubectl.sh` to operate on local k8s instance.

**Comment by nhlfr** [comment]
I'm going to work of this, just FYI.

**Comment by paralin** [comment]
It'd be nice if LoadBalancers would map to something on local. Same with NodePort.

**Comment by nhlfr** [comment]
Same reason as in pull request - this proposal is too controversial.
