### ISSUE TITLE
[k8sm] Run local km in agent host

### ISSUE THREAD

**Issue by k82** [kubernetes/kubernetes#26930]
I'd like to run local `km` in agent host. The parameters `--executor-path` is used to set executor, but it did not set `km`'s arguments.

The proposal is to provide an argument `--km-patch` to set the local path of `km` in agent host.

cc @jdef

**Comment by k82** [comment]
It seems we have a hidden parameter `--km-path`, I'll try it firstly.

https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/pkg/scheduler/service/service.go#L347

**Comment by k82** [comment]
@jdef any suggestion?

**Comment by jdef** [comment]
how did `--km-path` work out? if you ran into problems .. what were they?

**Comment by k82** [comment]
Just have a try, it seems not work; I'm on sure whether configuration issue.

**Comment by k82** [comment]
@jdef , just go through the code; the `--km-path` will only point to the `km` binaries in master and Mesos agent will fetch it. It did not match this requirement.

**Comment by k82** [comment]
@jdef , would you help to review the patch?

**Comment by jdef** [comment]
Yes, just provided some feedback on your PR
