### ISSUE TITLE
Deployment does not update when adding environment variables

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#26944]
Hi,

We're using deployments on Kubernetes version 1.2.1.

In order to update deployments we update the corresponding deployment.yml file and the run
`kubectl apply -f deployment.yml`

Everything works well most of the time except for the case in which we add an environment variable to one of the containers on the deployment.yml.

In that case we see that a new replica set is not created and the old pods keep on running.

**Comment by AdoHe** [comment]
The same problem as #25585, and the fix landed #26418, @erez-rabih ptal.

**Comment by AdoHe** [comment]
@bgrant0607 I am wondering whether we should create a cherry pick for 1.2, I have seen users ran into this bug several times.

**Comment by erez-rabih** [comment]
@AdoHe I agree it looks like a duplicate of #25585. I'm closing this.

**Comment by bgrant0607** [comment]
@AdoHe Yes, please create a cherrypick PR.

**Comment by danielloczi** [comment]
Hi! I'm facing the same issue now: adding a new env variable does not touch running pods, the new env varibale is not puplished down to the pods.

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by adohe** [comment]
@danielloczi I think this has already be fixed, could u please show how to reproduce this? I would take a look.

**Comment by bgrant0607** [comment]
cc @apelisse

**Comment by danielloczi** [comment]
Hi!

I have a set of environment variables configured for a deployment. The deployment is applied using kubectl apply -f deployment.yaml
After I edit the yaml file and add an extra env varibale, then apply it using the same command:
kubectl apply -f deployment.yaml
After that kubectl logs that the deployment is configured, but the pod not terminates, and the new env variable is not promoted to the pod level.

**Comment by danielloczi** [comment]
Update: I tried to reproduce it a couple of minutes ago, but I was unable. I trying to find the case, when it does not work.

**Comment by zerthimon** [comment]
Got this now in 1.11 on a DaemonSet.

**Comment by DeRain** [comment]
> Got this now in 1.11 on a DaemonSet.

Same for me

**Comment by peterromfeldhk** [comment]
also having the issue with DaemonSet
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.13-eks-g484b8", GitCommit:"484b857e3134d55ac6373fea2f51798fefa0533f", GitTreeState:"clean", BuildDate:"2019-03-08T05:32:36Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by iahmad-khan** [comment]
why this issue is closed? on latest version of kubernetes i am facing the same issue.

updating the deployment.yaml with adding new env var , and then kubectl apply , is not updating the deployment/pod with new env var.

**Comment by apelisse** [comment]
@iahmad-khan Would you mind coming-up with a minimal example that I would be able to build into a test or something?

**Comment by apelisse** [comment]
I'd need to see:
- The exact sequence of event,
- How the object is impact on the server, like the generation number for example.

**Comment by abheist** [comment]
Any fixes, seems like, I'm running commands, not in the correct order.

I updated `env-config` and deleted `deployment` and `pods` and all the `services` and created again with `apply`, still not picking new `configs`

**Comment by apelisse** [comment]
Can you reproduce the steps with a minimal example, the commands that you run and how the yaml looks like after?

**Comment by jun0tpyrc** [comment]
hitting this also sometimes, might be control plane &/ persistent problem 

Once this occurs , it persists for me even i delete deployment & service to recreate both in following orders 

1) Create a deployment & service exposing it 
(set some vars not yet existed on the deployment)
2) kubectl set env deploy/xxxxxx --containers=XXXX AAA=BBB
3a)(check pods started &/ delete them to let replicaset recreate pods,  see if vars exist )
3b) [delete both deployment & service to further reproduce , still can't set]

**Comment by apelisse** [comment]
OK Let's try to reproduce this:
```shell
$ kubectl create deployment --image nginx:latest nginx
deployment.apps/nginx created
$ kubectl set env deployment nginx --containers=nginx MY_ENV=1234
deployment.apps/nginx env updated
$ kubectl set env deployment nginx --containers=nginx MY_ENV_2=5678
deployment.apps/nginx env updated
$ kubectl get -o yaml deployment nginx | grep -A 5 env
      - env:
        - name: MY_ENV
          value: "1234"
        - name: MY_ENV_2
          value: "5678"
        image: nginx:latest
$ kubectl get pods nginx-7db6cbd99f-pwkxq -o yaml | grep -A 5 env 
  - env:
    - name: MY_ENV
      value: "1234"
    - name: MY_ENV_2
      value: "5678"
    image: nginx:latest
```

I still don't see what I should be looking at?
