### ISSUE TITLE
Zeppelin Image unable to config, [Environment Variables] (Spark Example)

### ISSUE THREAD

**Issue by thesuperzapper** [kubernetes/kubernetes#26941]
With the Zeppelin image from `gcr.io/google_containers/zeppelin:v0.5.6_v1`, referenced in, [zeppelin-controller.yaml](https://github.com/kubernetes/kubernetes/blob/master/examples/spark/zeppelin-controller.yaml), how can we set Zeppelin's environment variables. 

For example, to make notebooks persists through pod restarts, you could mount some volume to the container, and point the notebook directory at it. But I cant seem to change the config/environment-variable that tells zeppelin where to store them:

`ZEPPELIN_NOTEBOOK_DIR`

In addition to this, It would be nice to be able to use [ZeppelinHub](http://help.zeppelinhub.com/zeppelin_integration/), with

`ZEPPELINHUB_API_ADDRESS` 
`ZEPPELINHUB_API_TOKEN`
`ZEPPELINHUB_USER_KEY`

**Comment by pwittrock** [comment]
@jeffmendoza Mind taking a look at this?

**Comment by jeffmendoza** [comment]
@pwittrock sure!

**Comment by jeffmendoza** [comment]
Hi @thesuperzapper, while the `examples/` directory is meant to show k8s best practices, it is primarily educational. The goal here is not to create the best possible docker images.

As seen in the README, it looks like the zepplin image source is here: https://github.com/kubernetes/application-images/tree/master/spark/zeppelin I see that, yes, the `zeppelin-env.sh` file is setting the `ZEPPELIN_NOTEBOOK_DIR` variable without taking into account that it may be already set. Feel free to use the source as a starting point to create an improved docker image.

If you think that storing the notebooks on a PV would improve the tutorial, please submit a PR for the docker image and tutorial readme. I can help get it published on `gcr.io/google-containers`. Thanks!

**Comment by kargakis** [comment]
If this issue is still relevant, please reopen in the kubernetes/examples repo.
