### ISSUE TITLE
How to use "ABAC" plugin ? thanks

### ISSUE THREAD

**Issue by xiaochunyn** [kubernetes/kubernetes#26954]
I want to use "ABAC" plugin in my project, But I have some questions.
I have read the doc in [http://kubernetes.io/docs/admin/authorization/](url) and set 
`--authorization-mode=Webhook ----authorization-policy-file=abac.jsonl`
 
the content of "abac.jsonl " as follows:
`{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"*",         "nonResourcePath": "*", "readonly": true}}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"admin",     "namespace": "*",              "resource": "*",         "apiGroup": "*"                   }}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"scheduler", "namespace": "*",              "resource": "pods",                       "readonly": true }}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"scheduler", "namespace": "*",              "resource": "bindings"                                     }}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"kubelet",   "namespace": "*",              "resource": "pods",                       "readonly": true }}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"kubelet",   "namespace": "*",              "resource": "services",                   "readonly": true }}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"kubelet",   "namespace": "*",              "resource": "endpoints",                  "readonly": true }}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"kubelet",   "namespace": "*",              "resource": "events"                                       }}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"alice",     "namespace": "namespace1", "resource": "*",         "apiGroup": "*"                   }}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"bob",       "namespace": "namespace1", "resource": "*",         "apiGroup": "*", "readonly": true }}`

Now , I want to know, how to validate whether it takes effect ?
Thank you !

**Comment by ericchiang** [comment]
You've provided the wrong authorization mode.

```
--authorization-mode=Webhook
```

Should instead be

```
--authorization-mode=ABAC
```

**Comment by jlowdermilk** [comment]
@xiaochunyn looks like your issue was resolved, so closing this. For future reference, you will usually get faster response posting for help on [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).
