### ISSUE TITLE
docker pull from gcr.io blocked via storage.googleapis.com

### ISSUE THREAD

**Issue by wu105** [kubernetes/kubernetes#26989]
docker pull gcr.io/google_containers/pause:0.8.0

gets the following:

Pulling repository gcr.io/google_containers/pause
Error pulling image (0.8.0) from gcr.io/google_containers/pause, Get https://storage.googleapis.com/artifacts.google-containers.appspot.com/containers/images/2c40b0526b6358710fd09e7b8c022429268cc61703b4777e528ac9d469a07ca1/ancestry: read tcp 216.58.216.240:443: connection reset by peer

Apparently, our company is blocking https://storage.googleapis.com via McAfee because the googleapis site is considered a security threat.  https://www.quora.com/What-is-Storage-googleapis-com says it is a drive-by-download threat.  This must be resolved (i.e., making googleapis or whatever used by downloading from gcr.io not appearing as a security threat) for us even to test Kubernetes.

**Comment by bprashanth** [comment]
Hmm, urls are supposed to be case sensitive. I haven't confirmed Storage vs storage, but storage.googleapis.com is the domain of GCS (https://cloud.google.com/storage/docs/xml-api/reference-uris). Now of course someone could upload malware to a cloud storage location, or if you're downloading a random image it could contain malware etc.

**Comment by wu105** [comment]
Thanks for the quick reply.
This can be serious problem because anti-malware policies could block the entire site.
You may want to work with major anti-malware vendors to make sure that sites essential for Kubernetes are not blocked.

By the way, McAfee thinks “Google Cloud SDK (Google-Cloud SDK.zip) show malware infections” and we are forced to remove it.

**Comment by bprashanth** [comment]
This appears to be a "antivirus vendors are misinformed" problem, @aronchick maybe?

**Comment by wu105** [comment]
The "read tcp 216.58.216.240:443: connection reset by peer" error apparently went away just before 5:20AM Eastern time from our servers.  What could possibly causing this error?

"Antivirus vendor misinform" issues on https://storage.googleapis.com and Google Cloud SDK zip file nonetheless should be followed up because it is still a crippling issue for us.

**Comment by jlowdermilk** [comment]
cc @mattmoor

**Comment by mattmoor** [comment]
cc @jonjohnsonjr

**Comment by mattmoor** [comment]
IMO this is a pretty easy "won't fix".  All other registries will do something similar and you'll end up with a redirect to S3/CloudFront, which is virtually identical.

I'd recommend following whatever solution Kubernetes has in place for air gapped clusters.

**Comment by bprashanth** [comment]
Outside the scope of this bug, but maybe we can do something about McAfee profiling GCS as a virus vendor? Closing.
