### ISSUE TITLE
rkt: Use GetLogs() API to replace journalctl shell out calls

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#26997]
Because of https://github.com/coreos/rkt/issues/2740 , today we still need to shell out to journalctl to get container logs.

@pbx0 is investigating whether we need to switch to GetLogs() API to make the kubelet-wrapper work with rktnetes.

@kubernetes/sig-node @euank @tmrts

**Comment by pbx0** [comment]
Shelling out to journalctl works until you restart the kubelet and can no longer follow the symlink `/var/log/journal/$MACHINE_ID -> /var/lib/rkt/run/...` to any previously launched rkt pods. This is where we need rbind in stage1.

**Comment by yifan-gu** [comment]
cc @pbx0 So as #27098 is merged, we don't need to bind mount the journalctl binary now :)
