### ISSUE TITLE
Attach Detach Controller should verify pods exist periodically

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#26994]
The Attach Detach/Controller should periodically verify that pods in the desired state of the world still exist  (whether it should check with the informer cache or directly with the API server is yet to be decided).

This will add an additional layer of robustness: if the controller misses a pod delete event for any reason (which appears to happen occasionally, see https://github.com/kubernetes/kubernetes/issues/26682#issuecomment-224323518), this would rectify the problem.

**Comment by saad-ali** [comment]
Assigning to Jing to implement this

**Comment by erictune** [comment]
@saad-ali can you update on how the fix is progressing?

**Comment by jingxu97** [comment]
The PR is #27576. I am addressing the comments from @saad-ali now.

On Fri, Jun 17, 2016 at 8:35 AM, Eric Tune <notifications@github.com> wrote:

> @saad-ali <https://github.com/saad-ali> can you update on how the fix is
> progressing?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/26994#issuecomment-226802479>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxcaSU5j-kE54PJza4b7ZlkOReIP_ks5qMr7KgaJpZM4IwUWl>
> .
>



-- 
- Jing
