### ISSUE TITLE
isLikelyNotMountPoint() function needs refactored 

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#26996]
CC @kubernetes/sig-storage 

Currently, isLikelyNotMountPoint() is implemented in mount_linux.go and nsenter_mount.go. They use different approach to determine whether a path is mounted or not.
1. mount_linux.go checks if the directory has a different device as parent, then it is a mountpoint.
2. nsenter_mount.go uses findmnt command result to check the mountpoint. This approach has issue: if the path is relatively long, findmnt execute output will truncate the last letter of the path. 

Open an issue here to investigate whether we need to different approaches for this function. Another related issue is that isLikelyNotMountPoint() is called by many places and served as two purposes, one is checking whether directory exists or not, the other is to check the mount point. Suggest to separate these two functions.

**Comment by luxas** [comment]
I think this should also be fixed before `v1.3`, as it's a bit related to: https://github.com/kubernetes/kubernetes/issues/26943#issuecomment-224519722

**Comment by pmorie** [comment]
@eparis

**Comment by jingxu97** [comment]
Yes, I just sent out a fix which should solve the problem. But we want to
do more refactoring work a little bit later.
Please check https://github.com/kubernetes/kubernetes/pull/27054

Thanks and please let me know if there is any issue related to this.

Jing

On Wed, Jun 8, 2016 at 8:16 AM, Lucas Käldström <notifications@github.com>
wrote:

> I think this should also be fixed before v1.3, as it's a bit related to: #26943
> (comment)
> <https://github.com/kubernetes/kubernetes/issues/26943#issuecomment-224519722>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/26996#issuecomment-224621842>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxZOR2D4bN7-s97LEeP99y69qjWZsks5qJty0gaJpZM4IwVlt>
> .
>



-- 
- Jing

**Comment by thockin** [comment]
I don't buy that findmnt is broken, especially if it is only when run through exec.Cmd.  More likely the bug is in our processing of the output

**Comment by dims** [comment]
Others are finding it too https://github.com/kubernetes/kubernetes/issues/26864

**Comment by childsb** [comment]
@jingxu97 did #27054 resolve this issue?  Is this remaining open for future refactoring?

If so i'd like to adjust the priority

**Comment by jingxu97** [comment]
No, it is not resolved yet. We want to keep it open and I should have time
to address this early next week. Thanks!

On Wed, Jul 13, 2016 at 8:17 AM, bradley childs <notifications@github.com>
wrote:

> @jingxu97 <https://github.com/jingxu97> did #27054
> <https://github.com/kubernetes/kubernetes/pull/27054> resolve this issue?
> Is this remaining open for future refactoring?
>
> If so i'd like to adjust the priority
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/26996#issuecomment-232388028>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxYUM0Aw9wwwZIeMEmughYYLbhDmhks5qVQF2gaJpZM4IwVlt>
> .
>



-- 
- Jing

**Comment by jamiehannaford** [comment]
Can we not just search `/proc/mounts` for a given path? We're seeing some potential issues with this function in production (esp. with Cinder mounts).

**Comment by luxas** [comment]
ping @jingxu97

**Comment by jamiehannaford** [comment]
Actually after searching around a bit I think this PR might have introduced a better check: https://github.com/kubernetes/kubernetes/pull/48402. The next step is updating code like the cloud volume drivers to use the new version. 

@jingxu97 Does this answer your original question? If so, can we go ahead and close?

**Comment by jingxu97** [comment]
@jamiehannaford  Thanks for the updates. Close this issue now.

**Comment by jamiehannaford** [comment]
@jingxu97 Since this is not my issue, can you close this? Thanks!
