### ISSUE TITLE
limiting bandwidth and iops per container.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#27000]
We've seen several issues where multiple concurrent openshift builds running on a node can denial of service attack the nodes control plane such that the controller thinks the node is unresponsive. 

/cc @kubernetes/sig-node @kubernetes/sig-network @jeremyeder 

xref: https://github.com/kubernetes/kubernetes/issues/21331

**Comment by derekwaynecarr** [comment]
I am not sure giving proportional access will be enough within a given QoS.  If everything is Burstable, it would be good to vary iops within that tier on a per pod basis, but agree with the requisite steps outlined by @vishh.

**Comment by jeremyeder** [comment]
We can take a piece-meal approach to nailing down the reasons we can swamp the control plane, but I thought taking the inverse approach would be better and create "floors" for the all the processes in the system-reserved cgroups...no?  "shield" them no matter what the apps do?

BTW RHEL defaults to deadline, not cfq, but that's an aside for now...

Further...specifically about builds... I may not even want those co-located with my prod apps.  I want to shove them off in a dark corner where they can't affect anything in the production zone.  This is like compiling an app on your prod boxes and wondering why your page load times suddenly suck.  Poor design IMHO.

**Comment by timothysc** [comment]
> We can take a piece-meal approach to nailing down the reasons we can swamp the control plane, but I thought taking the inverse approach would be better and create "floors" for the all the processes in the system-reserved cgroups...no? "shield" them no matter what the apps do?

Yes, but we're still going to have the noisy neighbors problem so doesn't hurt to start the conversation.  If it's not builds it will be something else.

**Comment by pinkencryption** [comment]
I would like to request to prioritize this. It is important to isolate IO to run pods properly to include database storage etc.

**Comment by pinkencryption** [comment]
This might also help run a system like hadoop without affecting the node health

**Comment by vishh** [comment]
FYI: The general guideline thus far is to increase network bandwidth and user storage over the network for most applications.

**Comment by pinkencryption** [comment]
@vishh  : Can you elaborate ?

**Comment by astropuffin** [comment]
@vishh "increase network bandwidth" isn't an option for iops centered workloads (like image processing). Docker now offers very useful flags to handle this:
```
      --device-read-bps value       Limit read rate (bytes per second) from a device (default [])
      --device-read-iops value      Limit read rate (IO per second) from a device (default [])
      --device-write-bps value      Limit write rate (bytes per second) to a device (default [])
      --device-write-iops value     Limit write rate (IO per second) to a device (default [])
```
Not sure about rkt support, but I don't think the scope needs to be that large. Assuming docker as the runtime, iops and bps could be added as another optional container level resource like cpu and memory. Storage limits is handled much better with persistent volumes.

**Comment by liqlin2015** [comment]
Any update on this issue? Will pod support iops and bps option as docker?

**Comment by mkleint** [comment]
Any update on this issue? Will pod support iops and bps option as docker?

**Comment by mkleint** [comment]
Any update on this issue? Will pod support iops and bps option as docker?

**Comment by mkleint** [comment]
closed just in time to remind me to corner someone about this at Kubecon!

**Comment by pinkencryption** [comment]
This needs to happen, how can we request this ?

**Comment by max-lobur** [comment]
Having same issue with own k8s distro here. Would like to see this feature

**Comment by lovejoy** [comment]
We made some modification to  k8s to add storage limit option to pod's resource ,and it use the blkio cgroup to control device read-write bandwidth. Although we now that the blkio can't control all the io bandwidth ,It works well now.

**Comment by max-lobur** [comment]
@lovejoy what k8s release? can you share doc link pls, it it's published already
Thank you

**Comment by vishh** [comment]
@pinkencryption why does this feature *need* to happen? Have you thought of how this feature (IOPS isolation) will function in a coherent way across diverse environments (spinning/solid/network storage media)?
Is using local (NVMe) SSDs an option whenever IO is a constraint, especially for workloads like ML? Can databases be dedicated physical spinning disks especially when I/O is a constraint?

**Comment by lovejoy** [comment]
@max-lobur We made some changes like this https://github.com/kubernetes/kubernetes/pull/70573

**Comment by xiegang1** [comment]
Do we have any update about this feature? Can we isolated the iops now in k8s?  We are planning to migrate our hadoop apps to k8s, and think iops could be a problem and iops isolation is required.

**Comment by Pandoraemon** [comment]
Any update on this issue?

**Comment by xiuxiu** [comment]
My application requires a lot of Disk IO. It will impact ETCD a lot. ETCD will come to unhealthy occasionally.

**Comment by Xuehai-Chen** [comment]
Any update on this issue?

**Comment by septatrix** [comment]
@fetja this is still relevant and fresh, could you please remove the corresponding labels?

**Comment by tungdam** [comment]
+1

**Comment by duanmengkk** [comment]
+1

**Comment by vinh-pham-cko** [comment]
+1
