### ISSUE TITLE
Delayed route creation in gke-slow

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#27005]
Some slow tests check for number of nodes > 2. Sometimes route creation is delayed long enough that they fail. There seems to be enough quota, I can't get controller manager logs to see what the route controller was doing. Observed on: https://github.com/kubernetes/kubernetes/issues/26490#issuecomment-224438182

GKE because this only seems to happen in gke-slow and control-plane because it might be route controller starvation issue on master.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
/area platform/gke
since we lack a sig-gcp at the moment
