### ISSUE TITLE
Initial single-master dual-node (minion) cluster 

### ISSUE THREAD

**Issue by ptarpan** [kubernetes/kubernetes#27002]
I provisioned a single master two node cluster in AWS (us-west-2 region) using the startup guide at: http://kubernetes.io/docs/getting-started-guides/aws/. After some tweaking of the "util.sh" script, the cluster has now been initialized successfully as this script does not throw any configuration errors. Then, I followed: http://kubernetes.io/docs/user-guide/simple-nginx/ and ran "kubectl run my-nginx --image=nginx --replicas=2 --port=80" to run two nginx pods. My question is: why are the pods remaining in pending state? Here are the results of "kubectl get pods" 

NAME                                       READY     STATUS    RESTARTS   AGE
my-nginx-3800858182-2cxev   0/1            Pending     0                   8m
my-nginx-3800858182-iywbi    0/1            Pending     0                   8m 

Can someone point me in the right direction on the next troubleshooting steps? I am happy to provide more information including logs if need be.

**Comment by jlowdermilk** [comment]
See the troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/) for next steps. For future reference, you will generally get much faster responses if you post help/debugging questions on [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).
