### ISSUE TITLE
Node E2E: We need a test to test image pulling

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#27007]
After https://github.com/kubernetes/kubernetes/pull/25944, all images in node e2e test expect images in image conformance test are prepulled.

Now, image conformance test is marked as flaky https://github.com/kubernetes/kubernetes/pull/26811, then we lost the coverage.

In fact, the original image conformance test doesn't cover all aspects, either. So we need a image pulling test to test:
* Pull an invalid image;
* Pull an image from gcr;
* Pull an image from docker hub;
* Pull an image needs auth with/without secrets.

@liangchenye @pwittrock @vishh 
/cc @kubernetes/sig-node

**Comment by dchen1107** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/26464
