### ISSUE TITLE
kubernetes cannot create deployment with swaggerapi/apis/v1 404 error

### ISSUE THREAD

**Issue by kandycs** [kubernetes/kubernetes#27003]
Hi everyone, 
I just set up a cluster and can create a pod using 
`kubectl create -f nignx_pod.yaml` (kind: Pod)

But I met an error with message  when executing:
`kubectl create -f nignx_deployment.yaml` (kind: Deployment)

> the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false

Run it again with --v=10 options
It reports that:

> I0607 22:22:26.324464     499 debugging.go:102] curl -k -v -XGET  -H "User-Agent: kubectl/v1.1.8 (linux/amd64) kubernetes/a8af33d" http://localhost:8080/api
> I0607 22:22:26.325175     499 debugging.go:121] GET http://localhost:8080/api 200 OK in 0 milliseconds
> I0607 22:22:26.325201     499 debugging.go:127] Response Headers:
> I0607 22:22:26.325209     499 debugging.go:130]     Content-Type: application/json
> I0607 22:22:26.325216     499 debugging.go:130]     Date: Tue, 07 Jun 2016 22:22:26 GMT
> I0607 22:22:26.325222     499 debugging.go:130]     Content-Length: 57
> I0607 22:22:26.325252     499 request.go:746] Response Body: {
>   "kind": "APIVersions",
>   "versions": [
>     "v1"
>   ]
> }
> I0607 22:22:26.325455     499 debugging.go:102] curl -k -v -XGET  -H "User-Agent: kubectl/v1.1.8 (linux/amd64) kubernetes/a8af33d" http://localhost:8080/version
> I0607 22:22:26.325742     499 debugging.go:121] GET http://localhost:8080/version 200 OK in 0 milliseconds
> I0607 22:22:26.325761     499 debugging.go:127] Response Headers:
> I0607 22:22:26.325769     499 debugging.go:130]     Content-Type: application/json
> I0607 22:22:26.325777     499 debugging.go:130]     Date: Tue, 07 Jun 2016 22:22:26 GMT
> I0607 22:22:26.325784     499 debugging.go:130]     Content-Length: 146
> I0607 22:22:26.325816     499 request.go:746] Response Body: {
>   "major": "1",
>   "minor": "1",
>   "gitVersion": "v1.1.8",
>   "gitCommit": "a8af33dc07ee08defa2d503f81e7deea32dd1d3b",
>   "gitTreeState": "clean"
> }
> I0607 22:22:26.326145     499 decoder.go:144] decoding stream as YAML
> I0607 22:22:26.326406     499 debugging.go:102] curl -k -v -XGET  -H "User-Agent: kubectl/v1.1.8 (linux/amd64) kubernetes/a8af33d" http://localhost:8080/swaggerapi/apis/v1
> I0607 22:22:26.326643     499 debugging.go:121] GET http://localhost:8080/swaggerapi/apis/v1 404 Not Found in 0 milliseconds
> I0607 22:22:26.326662     499 debugging.go:127] Response Headers:
> I0607 22:22:26.326670     499 debugging.go:130]     Date: Tue, 07 Jun 2016 22:22:26 GMT
> I0607 22:22:26.326678     499 debugging.go:130]     Content-Length: 24
> I0607 22:22:26.326684     499 debugging.go:130]     Content-Type: text/plain; charset=utf-8
> I0607 22:22:26.326703     499 request.go:746] Response Body: ApiDeclaration not found
> I0607 22:22:26.326718     499 request.go:803] Response Body: ApiDeclaration not found
> F0607 22:22:26.326794     499 helpers.go:96] error validating "./nginx_deployment.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false

I checked the web-ui. I did not find v1 under swaggerapi/apis/, but I found one under swaggerapi/api/

What I missed in my configuration and How can I fix this problem ?

**Comment by nikhiljindal** [comment]
I see that you are using version 1.1.8. Deployments were alpha and hence off by default in 1.1.
I will recommend using the latest 1.2 version. deployments went beta with 1.2 and hence are turned on by default there.

**Comment by janetkuo** [comment]
If you run `kubectl get deployments`, would the server prints error saying something like "this resource type isn't supported"? If so, it's off and you need to manually turn support for deployment on. Or you can upgrade it to >1.2 like @nikhiljindal recommended.

**Comment by kargakis** [comment]
@kandycs closing this one, please let us know if you have any more problems with this issue.
