### ISSUE TITLE
[k8s.io] Services should work after restarting apiserver [Disruptive]

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#27011]
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/1470/

This test is deterministically broken on gke-serial for quite some time, I guess no one is looking.

**Comment by quinton-hoole** [comment]
@lavalamp Surely this one should also block the merge queue?

**Comment by bprashanth** [comment]
It failed because it couldnt' restart apiserver, not because services didn't come up. Why does it think it needs to update?
```
â€¢ Failure [13.938 seconds]
[k8s.io] Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:639
  should work after restarting apiserver [Disruptive] [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:369

  Jun  7 13:07:26.441: error restarting apiserver: error running gcloud [container --project=jenkins-gke-e2e-serial --zone=us-central1-f clusters upgrade jenkins-e2e --master --cluster-version=1.3.0-alpha.5.165+7476d97781563b --quiet]; got error exit status 1, stdout "<ClusterUpdate\n desiredMasterVersion: '1.3.0-alpha.5.165+7476d97781563b'>\n", stderr "ERROR: (gcloud.container.clusters.upgrade) ResponseError: code=400, message=Cluster master can only be upgraded to the latest (default) version. This does not upgrade the nodes..\n"

  /go/src/k8s.io/kubernetes/_output/docke
```

@kubernetes/goog-gke @kubernetes/goog-testing

**Comment by zmerlynn** [comment]
Because sledgehammer repair (in-place upgrade to the same version) is the only tool we have to force the apiserver to reboot for e2es on GKE. I suspect this project isn't whitelisted to force it from the API, though.

**Comment by wojtek-t** [comment]
Can we whitelist this project?

**Comment by zmerlynn** [comment]
Well, that was the confusing thing. This project should've been whitelisted ages ago even to be running in test. I suspect something else, filed internal 29201862.

**Comment by jlowdermilk** [comment]
I'll take this. I turned the test on for GKE but didn't verify master upgrade worked for custom versions.

**Comment by jlowdermilk** [comment]
Added project to whitelist. Next run should be good.

**Comment by lavalamp** [comment]
Yes, we should make this one block the queue once it's green.

**Comment by jlowdermilk** [comment]
The fix was good and it went green briefly before upgrade command got broken by a different change. Fix incoming.

**Comment by bprashanth** [comment]
GKE staging just failed with the upgrade failure on https://github.com/kubernetes/kubernetes/issues/28257

**Comment by jlowdermilk** [comment]
Unrelated. GKE staging failure is trying to upgrade with wrong version. Will look into on #28257
