### ISSUE TITLE
federation clientset need event support

### ISSUE THREAD

**Issue by mfanjie** [kubernetes/kubernetes#27026]
Federation clientset does not support event yet, we need to add it later to support event just like kuberenetes clientset. currently we comments the code line of start recording temporarily.
```
// broadcaster.StartRecordingToSink(&unversioned_core.EventSinkImpl{Interface: kubeClient.Core().Events("")})
```
log this issue for tracking.

**Comment by quinton-hoole** [comment]
@nikhiljindal is working on adding support for events.
