### ISSUE TITLE
e2e Flake: Node fails to come up?  Has read-only file system?

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#27024]
[logs](https://00e9e64bac5171409eb6cd3968cbf008a20bb476652dd1436d-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F26914%2Fkubernetes-pull-test-unit-integration%2F29624%2Fbuild-log.txt?qk=AD5uMEt6_KrgZgPVzn6fRmhVpuY7DL25J27ySkPtQ26xLZtbEUlWIweJ0KbeYE7-sQUbuTAXHTQV3HzckV55UtylSfVXS94iYiXKjIlZTJJYlDZBQQD_3Z-ogWyc_hvBlFVkjDwK9e8uLHUQr-rYDTZb26nqgOOdPX3O69quEXVv_YYaIqjxouYe0ey3cE6yNujRwB_CO9hQ3EQMFOrc9JafEYr63iq4LvV8gf4X59MtA7nRnoYxlOZwCTRSvzLewTLf2Yeho4Tl_A68F1dys-hZT0yc9-2--9saIYjlXDf5JPEDv3zHL3vJvacnkOpqAqpBzxwwbODWFKtzTAC1BL-6nvUCSbY3rwQHV_YcVSVDIgcTgK2Dd4Qf33EFsiVh1KBj2zmvwUsbIbuCT2P3XeK4ON-8xCZ_0NsAdXepsnRyvsHViGfzhcH9GVytJTtbpXICBkzBEkmxTcqjkHsu9TsqQ9uRCzqdApgtH7KQ_qJz-70tpj4sdW9o_FDtUvygXmEk_zgCyajpyqcYBlSq8ttfYlh9StxHoHxg3i3n7GlsxJhsFNLDWO2hnyG0gSp9sd6MEEjfy4EBIhb72WaZdqwI22zcyC_15JbervaiDCPkmadZOZ6XI5wtiHGfOeh3ZxA5hYpYEh0kCo2I9RoHiEBq-dGJagYUkEhL1xU5PLe7gRdavsK89jEr8bVijnLPVaKDAR9xgi1cpzW2lWjX35CjiL5J8h01M_wyDIfNQqXGYW26zuALrefB_OTMPcOgoArTPNQIBKXtyhgy6M0Cx8Db_Fdnud7BFMoTr1LQNsva24WNrAgBuR0BXd2LK4I2R2JpAwqYlzJwsdtGhz5JDYN0M4pE7v71J1ORoCv2iYkLc1ysHF0d_Lj9yBsCqEcioFTDiNDyr6P5S166oYKAX_wKijFEimUXEW5MOsUbXdDuRQmALhV7bC8)

+++ [0607 20:09:44] Starting kubelet in masterless mode
W0607 20:09:45.184793   13291 iptables.go:144] Error checking iptables version, assuming version at least 1.4.11: executable file not found in $PATH
I0607 20:09:45.185081   13291 plugins.go:71] No cloud provider specified.
I0607 20:09:45.185214   13291 manager.go:138] cAdvisor running in container: "/docker/46be1b0d208e194f5ae1cccebe2b267b92ea89c48ad5a72ec7d85b45145a8b6c"
W0607 20:09:45.388613   13291 manager.go:146] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
I0607 20:09:45.599842   13291 fs.go:119] Filesystem partitions: map[/dev/disk/by-uuid/fb1d5dbb-e79b-4105-89f9-241ef7d018d2:{mountpoint:/bin/docker major:8 minor:1 fsType: blockSize:0} none:{mountpoint:/ major:0 minor:28 fsType:aufs blockSize:0}]
I0607 20:09:45.606551   13291 manager.go:192] Machine: {NumCores:32 CpuFrequency:2499998 MemoryCapacity:220203401216 MachineID:564161e13a244cc5a6ab8d83267ccb7a SystemUUID:963D4797-069E-8B90-D6B9-C5D9DEA54B5E BootID:1107a1a5-dc66-4119-9dcb-50c0d47a775f Filesystems:[{Device:/dev/disk/by-uuid/fb1d5dbb-e79b-4105-89f9-241ef7d018d2 Capacity:528303898624 Type:vfs Inodes:32768000} {Device:none Capacity:528303898624 Type:vfs Inodes:32768000}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:536870912000 Scheduler:noop}] NetworkDevices:[{Name:eth0 MacAddress:02:42:ac:11:00:02 Speed:10000 Mtu:1460}] Topology:[{Id:0 Memory:220203401216 Cores:[{Id:0 Threads:[0 1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[2 3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:2 Threads:[4 5] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:3 Threads:[6 7] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[8 9] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:5 Threads:[10 11] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:6 Threads:[12 13] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:7 Threads:[14 15] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:8 Threads:[16 17] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:9 Threads:[18 19] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:10 Threads:[20 21] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:11 Threads:[22 23] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:12 Threads:[24 25] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:13 Threads:[26 27] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:14 Threads:[28 29] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:15 Threads:[30 31] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:GCE InstanceType:n1-highmem-32 InstanceID:2702066277297994448}
I0607 20:09:45.607462   13291 manager.go:198] Version: {KernelVersion:3.16.0-0.bpo.4-amd64 ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.9.1 CadvisorVersion: CadvisorRevision:}
W0607 20:09:45.608322   13291 server.go:653] No api server defined - no events will be sent to API server.
W0607 20:09:45.608400   13291 kubelet.go:552] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
I0607 20:09:45.608422   13291 kubelet.go:386] Hairpin mode set to "hairpin-veth"
W0607 20:09:45.608579   13291 plugins.go:170] can't set sysctl net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
I0607 20:09:45.608755   13291 manager.go:235] Setting dockerRoot to 
I0607 20:09:45.612694   13291 server.go:691] Setting keys quota in /proc/sys/kernel/keys/root_maxkeys to 1000000
W0607 20:09:45.612728   13291 server.go:694] Failed to update /proc/sys/kernel/keys/root_maxkeys: open /proc/sys/kernel/keys/root_maxkeys: read-only file system
I0607 20:09:45.612761   13291 server.go:707] Setting keys bytes in /proc/sys/kernel/keys/root_maxbytes to 25000000
W0607 20:09:45.612781   13291 server.go:710] Failed to update /proc/sys/kernel/keys/root_maxbytes: open /proc/sys/kernel/keys/root_maxbytes: read-only file system
I0607 20:09:45.612808   13291 server.go:723] Started kubelet v1.3.0-alpha.5.184+8e0d83f79ced7b
W0607 20:09:45.612948   13291 kubelet.go:978] No api server defined - no node status update will be sent.
I0607 20:09:45.612960   13291 server.go:117] Starting to listen on 127.0.0.1:10250
E0607 20:09:45.613056   13291 kubelet.go:921] Image garbage collection failed: unable to find data for container /
E0607 20:09:45.614244   13291 kubelet.go:982] Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]
I0607 20:09:45.614274   13291 manager.go:119] Kubernetes client is nil, not starting status manager.
I0607 20:09:45.614296   13291 kubelet.go:2568] Starting kubelet main sync loop.
I0607 20:09:45.614327   13291 kubelet.go:2577] skipping pod synchronization - [Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory] network state unknown container runtime is down]
+++ [0607 20:09:45] On try 2, kubelet(masterless): ok
+++ [0607 20:09:45] Starting kubelet in masterful mode
W0607 20:09:46.514275   13325 iptables.go:144] Error checking iptables version, assuming version at least 1.4.11: executable file not found in $PATH
W0607 20:09:46.514598   13325 server.go:480] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
W0607 20:09:46.514643   13325 server.go:441] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.

**Comment by dchen1107** [comment]
Unfortunately the logs attached isn't working anymore.

But from pasted log, error message of "read-only file system" is red-herring, not issue. We simply just moved on if failed to update those configurations. Also those configurations only affect maximum number containers can be started by docker, which is what our unittest test for here. 

Last warning is missing  /var/lib/kubelet/kubernetes_auth, but from log, the test is moving with defaults, not fatal though.

**Comment by dchen1107** [comment]
I am closing this one no information to debug for now, and please feel free re-open it with more logs if occurs again.
