### ISSUE TITLE
service iptable route is very slow

### ISSUE THREAD

**Issue by z32109571** [kubernetes/kubernetes#27021]
we have 2000 services..But when created a servicce for a pod ,we found the create iptables rule was very slow.The Pod usually was connected by services after 10 minutes。So I change the code for logging the execution time。
I found  ensurePortals() costs two minutes.when create a service,the ensurePortals start running .I want to slove it .could somebody can give me an optimization method #26148

**Comment by thockin** [comment]
This is a dup of #26148 isn't it?  Why have 2 issues?
