### ISSUE TITLE
Flake: cluster size autoscaling should increase cluster size if pending pods are small

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#27035]
The test is flaky in kubernetes-e2e-gce-autoscaling-migs. Cluster autoscaler adds node to mig, but node controller is not assimilating it:

cluster autoscaler's log:
```
I0608 07:44:46.220528       5 scale_up.go:116] Estimated 1 nodes needed in https://content.googleapis.com/compute/v1/projects/k8s-jnks-e2e-gce-autoscl-migs/zones/us-central1-f/instanceGroups/jenkins-e2e-minion-group-1
I0608 07:44:46.344409       5 scale_up.go:126] Setting https://content.googleapis.com/compute/v1/projects/k8s-jnks-e2e-gce-autoscl-migs/zones/us-central1-f/instanceGroups/jenkins-e2e-minion-group-1 size to 2
...
W0608 07:53:55.265482       5 cluster_autoscaler.go:123] Cluster is not ready for autoscaling: wrong number of nodes for mig: https://content.googleapis.com/compute/v1/projects/k8s-jnks-e2e-gce-autoscl-migs/zones/us-central1-f/instanceGroups/jenkins-e2e-minion-group-1 expected: 2 actual: 1
```

test's log:
```
[k8s.io] Cluster size autoscaling [Slow] should increase cluster size if pending pods are small [Feature:ClusterSizeAutoscalingScaleUp]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_size_autoscaling.go:129 Expected error: <*errors.errorString | 0xc8206be0a0>: { s: "timeout waiting 5m0s for appropriate cluster size", } timeout waiting 5m0s for appropriate cluster size not to have occurred
```

failed execution:
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-autoscaling-migs/322

**Comment by jszczepkowski** [comment]
@mwielgus @gmarek 
Marek, can you check what's happening on node controller?

**Comment by gmarek** [comment]
IIUC kubelect didn't registered Node in the API server at all, so NC wasn't doing anything with it. @jszczepkowski claims that `jenkins-e2e-minion-group-1` was expected to be resized, but NodeControlled didn't saw any new node around the time of the failure.

It's either autoscalers fault and it didn't created a new machine, or Kubelet failed to register in the API server in time.

**Comment by gmarek** [comment]
First new Node NC notices was round 0:57 which was during next suite: `should add node to the particular mig` and it worked perfectly fine - I expect that this is an autoscaler bug.

**Comment by jszczepkowski** [comment]
> First new Node NC notices was around 7:57 which was during next suite: should add node to the particular mig and it worked perfectly fine - I expect that this is an autoscaler bug.

@mwielgus Can you comment on this?

**Comment by mwielgus** [comment]
The suite is all green. The issues is obsolete/fixed.
