### ISSUE TITLE
Kubernetes issues with setting up on AWS 

### ISSUE THREAD

**Issue by bedekarsarvesh** [kubernetes/kubernetes#27030]
Hello all .. I tried to install kubernetes on coreos using the following description in the link :

https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html

I am stuck at the following error :-

sarvesh-HP-Pavilion-g6-Notebook-PC my-cluster # kubectl --kubeconfig=kubeconfig get nodes
Unable to connect to the server: dial tcp: lookup kubernetescluster on 127.0.1.1:53: read udp 127.0.1.1:53: i/o timeout

**Comment by jlowdermilk** [comment]
Please post your question to  [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We use github issues to track bugs and feature request/proposals. Help/support questions will be responded to much faster on stackoverflow, and you may find answers/solutions to a similar issue that will work for you. The Kubernetes team regularly scans stackoverflow and will try to ensure questions don't go unanswered. Thanks.
