### ISSUE TITLE
kubectl logs UX when init containers are used

### ISSUE THREAD

**Issue by lukaszo** [kubernetes/kubernetes#27040]
Im extracting logs part from #25818 

The current behavior is as follow: 

- when pod has one container
`kubectl get logs` return logs for this one container

- when pod has more than one container
`kubectl get logs` returns error:
`Error from server: a container name must be specified for pod kube-dns-v14-z0ho6, choose one of: [kubedns dnsmasq healthz]
`
As you can see in both cases init containers are ignored. The question are:

-  in first case should we return error and list all containers including init containers? 
- in second case should we also list init containers?

**Comment by dchen1107** [comment]
@lukaszo first case is designed on purpose that way for the usability, especially the users who switch from docker single container to Kubernetes pod. But what you suggested above for the second case are great, we should do it. Mind to send pr fixing it? Thanks!

**Comment by lukaszo** [comment]
@dchen1107 sure, I will prepare pr. I'm wondering if we should somehow distinguish init containers and normal containers.

- we can add `init:` to init container name but this may be misleading. 
- we can also add second list with init containers. Something like these:
`Error from server: a container name must be specified for pod kube-dns-v14-z0ho6, choose one of: [kubedns dnsmasq healthz] or from init containers [bootstrap]`
- Or just show all in one list without any changes.

What do you think?

**Comment by dchen1107** [comment]
I prefer not introducing a prefix "init:" here. I like the second option better. cc/ @smarterclayton WDYT?

**Comment by smarterclayton** [comment]
I like the second option as well.  We generally avoid prefixes or special syntax except in rare cases.

**Comment by smarterclayton** [comment]
@sttts since I know you are also looking at code in these places.

**Comment by sttts** [comment]
+1 for the second option.
