### ISSUE TITLE
How to log on GCE with severity level from my pods?

### ISSUE THREAD

**Issue by hekike** [kubernetes/kubernetes#27046]
Hi,

currently, I'm logging to the `stdout` from my Docker containers which appears in the GCE Logging as: 
```
{
  metadata: {…} 
  textPayload: "[32minfo[39m: App is listening on 3001"
  insertId: "insert-id"    
  log: "my-service"    
}
```

I would like to send severity to my logs to being bale to filter/alert etc based on that.
I tried to send a JSON string to `stdout`, without any luck *(I thought that Kubernetes maybe recognize that this is a JSON format and merge with the meta data)*

```
{
  metadata: {…}    
  textPayload: "{"severity":"INFO","message":"Worker is running"}"    
  insertId: "insert-id"    
  log: "my-service"    
}
````

Can you help me?
Is it possible to achieve this and send severity from my pods?

Thanks,
Peter

**Comment by hekike** [comment]
I tried the following formats with no luck:

````
ERROR: logging before flag.Parse: I0609 07:03:23.373119 82504 main.go:40] Prepare to repel boarders
I0609 07:03:23.373119 82504 main.go:40] App is listening 1
{"severity":"INFO","timestamp":"2016-06-09T07:03:23.000Z","message":"App is listening 2"}
[info:2016-06-09T07:03:23.930-08:00] App is listening 3
````

**Comment by jlowdermilk** [comment]
See http://stackoverflow.com/questions/35582153/logging-to-the-google-cloud-in-google-container-compute-engine-with-go

**Comment by hekike** [comment]
@jlowdermilk thanks!
