### ISSUE TITLE
HPA controller should better inform user about failed failures in reading metrics

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/kubernetes#27044]
Currently HPA will only generate events that it cannot read metrics:

```
Events:
  FirstSeen LastSeen    Count   From                SubobjectPath   Type        Reason          Message
  --------- --------    -----   ----                -------------   --------    ------          -------
  9m        7s      22  {horizontal-pod-autoscaler }            Warning     FailedGetMetrics    failed to get CPU consumption and request: metrics obtained for 0/1 of pods
  9m        7s      22  {horizontal-pod-autoscaler }            Warning     FailedComputeReplicas   failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 0/1 of pods
```

We should be more specific and explain that for example pod is not running, or heapster is not responding or we cannot resolve url to heapster.

@kubernetes/autoscaling

**Comment by davidopp** [comment]
This is marked as 1.3. Are you planning to do a cherrypick for this?

**Comment by piosz** [comment]
I've started working on this but I'm not sure whether it's possible to easily do it. If yes I'll do a cherrypick.

**Comment by piosz** [comment]
I've started working on this but I'm not sure whether it's possible to easily do it. If yes I'll do a cherrypick.

**Comment by erictune** [comment]
Improved debugging is not a release blocked.

**Comment by fgrzadkowski** [comment]
I agree. Thanks for removing the 1.3 milestone.

**Comment by DirectXMan12** [comment]
HPA status conditions should have improved this sufficiently

/close
