### ISSUE TITLE
Ping doesn't work from Pods on GCI

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#27059]
ref: #26379

**Comment by freehan** [comment]
identified one problem: 
master pod cidr mismatch with network route in test setup.

**Comment by freehan** [comment]
identified one problem: firewall is not open for icmp in GCI setup.

I opened it manually. Still does not work.

**Comment by freehan** [comment]
Here are the symptoms: 
1. All node can ping each other
2. On one node, it can ping all pods on it, and vice versa. 
3. On one node or pod, it can ping all cbr0 gateways(10.X.X.1). But not the pod ips except on the same node. 
4. On pod, it cannot ping google.com but able to curl.

**Comment by bprashanth** [comment]
My first thought would be somethings blockign ping. your options are iptables, firewall, icmp is disabled alltogether (sysctl or somewhere in /proc/sys/net/ there should be a setting). Try traceroute and see where it gets to.

**Comment by freehan** [comment]
I have a working version now. GCI setup added icmp ACCEPT rules in INPUT chain of filter table. But not in OUTPUT or FORWARD chain.

**Comment by freehan** [comment]
In summary, 2 problems:
1. firewall is not opened for icmp
2. iptables is filtering icmp on FORWARD chain. INPUT chain is not enough

Will submit a fix 
@a-robinson @andyzheng0831

**Comment by a-robinson** [comment]
Great detective work, @freehan!

Is this a ping-specific problem, or are there going to be problems with other types of outgoing traffic from pods on GCI as well?

**Comment by freehan** [comment]
I do not see any problem for udp/tcp traffic so far. e2e tests already covers lots of them. Unfortunately, no e2e covers ping tests and GCI happens to filter it.

**Comment by andyzheng0831** [comment]
We should add a test in networking suite for ping.

**Comment by dims** [comment]
Is this missing a milestone 1.3?
