### ISSUE TITLE
Optimize caching 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#27053]
We can see from experimental data that @rrati produced: https://docs.google.com/document/d/18HYc3nNQQEL8oE3uXOoZ9WP3oG451ZgwowhvJbRU7wM/edit?usp=sharing 

That the %memory increase from controller caches can eclipse much of the memory gains shown from etcd3.  The cached data are fully blown out data-structures, and a lot of it is repetitive and un-necessary.  

There are potentially multiple roads we could take here, so I thought we could start the discussion now in for 1.4. 

/cc @kubernetes/sig-scalability @smarterclayton @rrati

**Comment by hongchaodeng** [comment]
@timothysc 
Any specific component (informer, rc manager, etc.) on top of your head?

**Comment by xiang90** [comment]
@timothysc Add some more data:

We tried to create 1 controller that creating 1M pods.

At the end of the test:

etcd3 used 3GB memory (db size was around 1gb. go runtime preserves 2gb.). 

API server used around 10GB.

Controller used around 10GB.

**Comment by timothysc** [comment]
Much of the data is not needed to perform operations honestly... In a former life we created what were sparse cache trees.

**Comment by xiang90** [comment]
@timothysc 

Also you probably did not see a huge memory drop between etcd3 and etcd2. It is because etcd3 maintain ALL versions of keys. So starting a pod actually creates at least 3 slight different keys in etcd3. 

The space can be compacted and will be kept in a free-list for future usage rather than returns to the user. If you try a large scale and long running test, etcd3 would use significantly less memory than etcd2.

**Comment by timothysc** [comment]
We will do more elaborate isolated testing of etcd3 in the coming weeks.

**Comment by hongchaodeng** [comment]
@rrati @timothysc 
I can tell the relationship between RC and pods.
Can you share how you created "services" and "namespaces"? How are they related to RC and pods?

**Comment by rrati** [comment]
51000 Pods
- 13 in kube-system
- 5 from each rc
- 1 additional pod in almost all namespaces
10004 Replication Controllers
- 4 system
- 10 per namespace
   - Each running 5 pods
20007 Services
- 6 system services
- 1 default service
- 20 per namespace
1002 Namespaces
- default
- kube-system
- 1000 other
300 Nodes

@hongchaodeng Is ^^ What you are looking for?

**Comment by timothysc** [comment]
Going to close this one in favor of the execution patch around informer modifications: 
https://github.com/kubernetes/kubernetes/issues/27519
