### ISSUE TITLE
GCE Kubernetes Cannot Attach Volume to a Particular Docker Image

### ISSUE THREAD

**Issue by patwhite** [kubernetes/kubernetes#27051]
This refers to the docker repo at:
https://github.com/sonatype/docker-nexus3

If you try to attach a GCE Persistent Disk, this image will consistently fail to start with the issue described here:
http://stackoverflow.com/questions/34171019/could-not-attach-gce-pd-timeout-waiting-for-mount-paths/37695212#37695212

My answer on that question is only partly right, for this image in particular I was never able to get it to start up.

**Comment by jlowdermilk** [comment]
> the issue ended up being that the application running inside the docker container was actually shutting down immediately - this caused gce to try and restart it, but it would fail when GCE tried to attach the disk (already attached).

Do you mean that the container was failing immediately and being restarted? Seems like "already attached" should not be an error. Also, sounds like image is not gracefully terminating, so consider filing issue against https://github.com/sonatype/docker-nexus3/issues.

**Comment by msau42** [comment]
@patwhite are you still seeing the issue?  The volume controller has gone through significant rework since this issue was first filed.

/sig storage

**Comment by msau42** [comment]
Yeah, sorry about the delay in response.  We're trying to do some bug cleanup for the thousands of issues...  Anyway, if you run into this issue again, please open a new issue.
/assign
