### ISSUE TITLE
Run node e2e tests against the images used by the cluster e2e's

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#27063]
Specifically, we aren't currently running the node e2e tests against the 2 images we plan to launch 1.3 on GCE with: gci and container-v1-3-v20160604

/cc @dchen1107 @vishh @pwittrock

**Comment by vishh** [comment]
We need to add the container vm to `kubernetes-node-e2e-images` project and
to jenkins properties files under `test/e2e_node/jenkins/*`

**Comment by timstclair** [comment]
I think this is fixed?
