### ISSUE TITLE
Downward API for resource specification should default to node capacity when limits are not set.

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#27062]
As of now the downward API for resource specification defaults to `0` for `limits` when `limits` are not specified in the pod spec. This behavior is not ideal for applications. 
What does a limit of `0` mean? 
In reality, not having a limit translates to being limited by node capacity as of now, and node allocatable in the future once it is enforced. 
We should default to node capacity instead of setting `limit.memory` to `0` when `limits` are not set.
And for `limits.cpu` we should again default to node capacity and allocatable in the future.

**Comment by derekwaynecarr** [comment]
@vishh - do you want to handle requests with any special convention?  After all, 0 cpu requests is really whatever we set min cpu shares too (~1m)

**Comment by derekwaynecarr** [comment]
@vishh - when we have pod and qos tier cgroups, BE will not really be node allocatable.  It may be a sensible thing to do, but if you then tie your JVM heap size to that value, it will immediately OOM kill since the actual limit will be much lower.

**Comment by derekwaynecarr** [comment]
Questions:

1. How should an application know its qos tier via downward API?
2. If we do something with requests, is it confusing to do anything that makes it appear I have a better QoS class than I do in reality?

**Comment by aveshagarwal** [comment]
@derekwaynecarr Regarding your first question,  I see this function GetPodQos, GetQoS in pkg/kubelet/qos/util/qos.go, i think these should help in exposing qos status via downward API.

**Comment by vishh** [comment]
> do you want to handle requests with any special convention? After all, 0 cpu requests is really whatever we set min cpu shares too (~1m)

Requests are a lower bound. Having a `0` for cpu requests just means that there are no guarantees. From an app standpoint that should be OK right? We can choose to implement no guarantees in different ways over time. Today we set cpu shares to `2`. As for memory, we don't do anything with requests today. So its OK to default requests at `0` as well.

> when we have pod and qos tier cgroups, BE will not really be node allocatable. It may be a sensible thing to do, but if you then tie your JVM heap size to that value, it will immediately OOM kill since the actual limit will be much lower.

Yeah. Thats true. Since the limits for BE are dynamic, it will be difficult to use that. This was one of the reasons why I did not like using env vars in the first place. 
On the other hand, I'd argue that apps that don't specify any memory limits are bound to get evicted or OOM killed if they use more than they requested. So in the case of JVM, JVM should use requests instead of limits to set its heap size. That way it is guaranteed to not OOM. WDYT?

> How should an application know its qos tier via downward API?

Shouldn't this be a separate downward API?

> If we do something with requests, is it confusing to do anything that makes it appear I have a better QoS class than I do in reality?

Are you referring to defaulting requests in this question?

**Comment by vishh** [comment]
BTW. I'm working on a patch to fix this issue for v1.3.

**Comment by derekwaynecarr** [comment]
I am ok with setting limits to allocatable.  What I was concerned about is
if it obfuscated my applications ability to determine its qos if it's
Kubernetes aware.   Previously, I could have deduced BE qos with checking
that request and limit for all resources was 0.  This change prevents that
which is fine, but it does call out the need to have Kubernetes aware
applications have a way of knowing their effective qos reliably.  So in the
JVM case, my container could choose to tune differently.  Alternatively, I
guess that if your request for both CPU and memory were 0 it would be BE
given how our defaulting works.  Anyway, +1 on this change, and feature
request to know qos tier to make better use of the info.

**Comment by aveshagarwal** [comment]
@vishh @derekwaynecarr  I am trying to understand why not change resources.limits.cpu/memory when the limits are unset? So that downward api would get it "automatically" and would be consistent with resources.limits.cpu/memory? What is the issue with it?

Also I dont see any change in functionality in practice if we do it. For example:

For a resource: 

1. 
Before: limit =0, req =0 : -> BE
After: limit = node capacity/node allocatable , req=0 -> BE

2. 
Before: limit =0, req > 0 : -> Burstable
After: limit = node capacity/node allocatable , req > 0 -> Burstable (The only corner case here is if req=node capacity/node allocatable then Guranteed)

So I see mostly the functionality remains same.

**Comment by vishh** [comment]
> I am trying to understand why not change resources.limits.cpu/memory when the limits are unset? So that downward api would get it "automatically" and would be consistent with resources.limits.cpu/memory? What is the issue with it?

Are you suggesting defaulting in the node or at the API level?

**Comment by derekwaynecarr** [comment]
@aveshagarwal - defaulting at the API is not something that can happen.  I think defaulting in the node makes the local caches complicated, and could confuse other code paths.  I would prefer we keep defaulting for this local to the point of injection.

**Comment by vishh** [comment]
I feel the same way. Given the current state of code, a global defaulting
even at the node side will have un-expected consequences.

**Comment by aveshagarwal** [comment]
@vishh @derekwaynecarr  I meant at node level. But if there are issues with that, then its fine to go with the current implementation approach.   

Is one of the issues is that nodes might have different node capacities?

**Comment by vishh** [comment]
Capacity for cpu and memory cannot change today since kubelet uses the
capacity surfaced by the kernel.

Capacity is a part of NodeStatus and not Spec and as per the API it is
mutable. That said, I don't think we have to design for varying capacity.

**Comment by dchen1107** [comment]
@derekwaynecarr Is this one required for 1.3 release? There is a pending pr under review, but @vishh is out for vacation this week.

**Comment by derekwaynecarr** [comment]
@dchen1107 - i just lgtm-ed https://github.com/kubernetes/kubernetes/pull/27107  --- so assuming it merges, we should be good.

**Comment by derekwaynecarr** [comment]
(and yes, it should be required for 1.3)

**Comment by derekwaynecarr** [comment]
This is reverted so reopening.

**Comment by erictune** [comment]
@vishh @derekwaynecarr this is listed as a release blocker.  Is one of you actively working on a fix for this?

**Comment by derekwaynecarr** [comment]
Yes.

There is a PR open with fix:
https://github.com/kubernetes/kubernetes/pull/27441
