### ISSUE TITLE
The `kubectl get events -w` logs' first column should be `LASTSEEN`

### ISSUE THREAD

**Issue by dkaplan-pivotal** [kubernetes/kubernetes#27060]
Hello Kubernetes,

The order of the columns when you get events confused me.  I was thinking,

> In our Kubernetes environments, the event logs (ie:  `kubectl get events -w`) aren't always ordered chronologically.  For example, line 1 will be from 30 minutes ago, line 2 will be 5 seconds ago, line 3 will be 20 minutes ago then line 4 will be 1 second ago.  I'm not sure if this is a problem with our Kubernetes install or Kubernetes itself.

Turns out it's just a visual problem where these events are sorted correctly (by `LASTSEEN`), but the first column is `FIRSTSEEN`.  I think the first column should be `LASTSEEN` because that's the order the events are listed.

**Comment by justinsb** [comment]
This also confused me when I first saw it - I think this ordering would be more intuitive and help users discover the aggregation feature logically, instead of first having to grapple with why events are "out of order"

**Comment by therc** [comment]
Should the order be always LASTSEEN,FIRSTSEEN or just when using -w?
I have an ugly PR for the latter, but perhaps we should just go for the former.
