### ISSUE TITLE
Cassandra PetSet example

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#27074]
Move the example from https://github.com/k8s-for-greeks/gpmr/tree/master/pet-race-devops into the examples in this code base.

Some time in July ish I will have time to do this.

cc: @kubernetes/examples 

Please tag with Cassandra tag and assign to me.

**Comment by bgrant0607** [comment]
@chrislovecnm Could we just use #24030 for this?

**Comment by chrislovecnm** [comment]
@bgrant0607 that is fine, but I actually need another issue.  Working on a demo here: https://github.com/k8s-for-greeks/gpmr  will move in once it is documented :)
