### ISSUE TITLE
replicationcontrollers cannot be found when setting up a local cluster with vagrant

### ISSUE THREAD

**Issue by lxjuly** [kubernetes/kubernetes#27073]
I was using `1.3.0-alpha6` release to setup a local cluster with vagrant on my `OS X 10.11.5`. The instruction is referenced here:
http://kubernetes.io/docs/getting-started-guides/vagrant/

After deploying the `nginx` apps and set replica to 3. I can get three pods with `./cluster/kubectl.sh get pods`. But `./cluster/kubectl.sh get replicationcontrollers` returns nothing.

I received two error while provisioning the master server:

```bash
----------
==> master:           ID: /etc/kubernetes/addons/dns/kubedns-svc.yaml
==> master:     Function: file.managed
==> master:       Result: False
==> master:      Comment: Source file salt://kube-dns/kubedns-svc.yaml.in not found
==> master:      Started: 18:58:34.175030
==> master:     Duration: 4.074 ms
==> master:      Changes:   
==> master: ----------
==> master:           ID: /etc/kubernetes/addons/dns/kubedns-rc.yaml
==> master:     Function: file.managed
==> master:       Result: False
==> master:      Comment: Source file salt://kube-dns/kubedns-rc.yaml.in not found
==> master:      Started: 18:58:34.179282
==> master:     Duration: 0.854 ms
==> master:      Changes:
```

Not sure if the errors are related but just post it here anyways.

**Comment by jlowdermilk** [comment]
Message at the top of http://kubernetes.io/docs/getting-started-guides/vagrant/ indicates the vagrant guide is now superseded by [Minikube](http://kubernetes.io/docs/getting-started-guides/minikube/).

**Comment by lxjuly** [comment]
@jlowdermilk Thanks!!
