### ISSUE TITLE
GKE Node created without a route

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#27071]
Spin off of https://github.com/kubernetes/kubernetes/issues/26970

the environment seems wrong in [5092](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/5092/). Specifically 2 out of 3 nodes do not have a route

```sh
[BeforeEach] [k8s.io] Pod Disks
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:69
Jun  7 08:27:35.862: INFO: Condition NetworkUnavailable of node gke-jenkins-e2e-default-pool-ccf481db-h5nt is true instead of false. Reason: NoRouteCreated, message: Node created without a route
Jun  7 08:27:35.862: INFO: Condition NetworkUnavailable of node gke-jenkins-e2e-default-pool-ccf481db-w3tg is true instead of false. Reason: NoRouteCreated, message: Node created without a route
```
On the other hand the logs do not have this error for `gke-jenkins-e2e-default-pool-ccf481db-syf0`

@ihmccreery can you find someone on gke to investigate this? Is there anything interesting in the node artifacts or gke logs about this?

**Comment by ihmccreery** [comment]
Priority?  I can't look at this right now, so I can do it later, or pass it off.

**Comment by wojtek-t** [comment]
This is working as intended. Routes are being created by route controller asynchronously. It's possible that tests start before all routes are created.
However, nodes without routes are considered unschedulable.

For more details you can look into: https://github.com/kubernetes/kubernetes/pull/26415
