### ISSUE TITLE
Configure union merge for plaintext lists

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#27088]
We have files that are merely a plaintext list of 1 item per line.  E.g., `hack/verify-flags/known-flags.txt`.  These cause pointless merge conflicts, one of which I just experienced and had to resolve.

You can tell git that the right answer is to accept the lines from both sides of the merge by using `.gitattributes` to select `git merge-file --union`.  I have a PR that does this and will send it in a sec.

**Comment by mml** [comment]
Le sigh.  I can make this work on my machine, but I see no way to configure custom merge drivers to be used by github.

If anyone cares, the recipe is to put this in some `gitconfig` file

```ini
[merge "aggregate"]
  name = aggregate both new sections
  driver = git merge-file --union -L %P %A %O %B
```

And then this:

```diff
diff --git a/hack/verify-flags/.gitattributes b/hack/verify-flags/.gitattributes
index e69de29..9c4df64 100644
--- a/hack/verify-flags/.gitattributes
+++ b/hack/verify-flags/.gitattributes
@@ -0,0 +1 @@
+known-flags.txt merge=aggregate
```

Part two is easy, but part one isn't something I see how to do.

@kubernetes/release-maintainers and @kubernetes/sig-testing in the absence of a sub-team that owns dev infra or "the build" generically.

**Comment by rmmh** [comment]
I think `merge=union` should work without any gitconfig changes.

**Comment by mml** [comment]
@rmmh Thanks, that seems correct.  Is that documented somewhere?

**Comment by rmmh** [comment]
It's in [`man gitattributes`](https://git-scm.com/docs/gitattributes#_built_in_merge_drivers) under "Built-in merge drivers".
