### ISSUE TITLE
kube-controller-manger fails to come up when started using hyperkube

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#27085]
service controller requires `--cloud-provider` to be set on kube-controller-manager. It otherwise fails with:
```
 Failed to start service controller: ServiceController should not be run without a cloudprovider.
```
as per this code: https://github.com/kubernetes/kubernetes/blob/a550cf16b9aadeb1287ef30db6fbf0ccca19c87a/pkg/controller/service/servicecontroller.go#L163.

But there is no way to pass the --cloud provider flag to kube-controller-manager when following the instructions as per http://kubernetes.io/docs/getting-started-guides/docker/

```
docker run -d \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:rw \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged \
    gcr.io/google_containers/hyperkube-${ARCH}:${K8S_VERSION} \
    /hyperkube kubelet \
        --containerized \
        --hostname-override=127.0.0.1 \
        --api-servers=http://localhost:8080 \
        --config=/etc/kubernetes/manifests \
        --cluster-dns=10.0.0.10 \
        --cluster-domain=cluster.local \
        --allow-privileged --v=2
```

**Comment by nikhiljindal** [comment]
Ref http://serverfault.com/questions/772747/servicecontroller-should-not-be-run-without-a-cloudprovider

**Comment by nikhiljindal** [comment]
cc @mikedanese @luxas 
Not sure who maintains hyperkube

**Comment by mikedanese** [comment]
@fgrzadkowski @jbeda @aaronlevy since they all have used hyperkube.

this seems bad.

**Comment by aaronlevy** [comment]
That error (at least in the past) was never fatal. In the future it might be bad if new non-cloud-provider functionality is added -- but the only thing the service controller is (was?) doing is cloud-provider related anyway. Maybe just a less worrisome error message?

Ref (hyperkube + non-cloud-provider): https://github.com/coreos/coreos-kubernetes/blob/master/single-node/user-data#L247-L251 -- I've also been testing this against v1.3.0-alpha.5 recently and haven't noticed controller-manager failing outright.

I think this might just be an issue of how to cleanly override the static manifests shipped with the hyperkube image (or if this is even a goal?)

**Comment by aaronlevy** [comment]
Still seems to be non-fatal: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L249-L251

I tested the instructions in http://kubernetes.io/docs/getting-started-guides/docker against `v1.2.4` & `v1.3.0-alpha.5` on a fresh CoreOS node, and it mostly seemed to work (k8s-master comes up in both instances. The dns/dashboard were in crash loops on v1.3.0-alpha.5 -- but didn't debug as unrelated).

**Comment by dims** [comment]
one more data point, just running local-up-cluster.sh seems to use `--cloud-provider=` and works fine

`
$ ps auxw | grep controller-manager | grep -v grep
root     30662  0.0  0.0  54796  3840 pts/1    S+   19:57   0:00 sudo -E /home/dims/kubernetes/_output/local/bin/linux/amd64/hyperkube controller-manager --v=3 --service-account-private-key-file=/tmp/kube-serviceaccount.key --root-ca-file=/var/run/kubernetes/apiserver.crt --enable-hostpath-provisioner=false --pvclaimbinder-sync-period=10m --cloud-provider= --master=127.0.0.1:8080
root     30670  0.8  0.4 445876 67652 pts/1    Sl+  19:57   0:00 /home/dims/kubernetes/_output/local/bin/linux/amd64/hyperkube controller-manager --v=3 --service-account-private-key-file=/tmp/kube-serviceaccount.key --root-ca-file=/var/run/kubernetes/apiserver.crt --enable-hostpath-provisioner=false --pvclaimbinder-sync-period=10m --cloud-provider= --master=127.0.0.1:8080
`
