### ISSUE TITLE
Several Examples E2Es Determinstically Broken

### ISSUE THREAD

**Issue by goltermann** [kubernetes/kubernetes#27086]
https://k8s-testgrid.appspot.com/k8s#gce-examples&width=5 shows Cassandra, RabbitMQ, Hazelcast, Redis, RethinkDB, Spark, Storm all broken.

Taking a look, my initial theory is we're not checking that the created service is up in the right way.

**Comment by goltermann** [comment]
Looks like a good old fashioned test code race condition for several of these, working on a PR.

**Comment by janetkuo** [comment]
dup with #27325

**Comment by chrislovecnm** [comment]
@janetkuo should we close this??

cc: @bgrant0607

**Comment by goltermann** [comment]
yes, this is done, I'll close
