### ISSUE TITLE
kubectl get -o jsonpath does not handle objects with RawExtension

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#27090]
This will break when we add templates @pwittrock @bprashanth @bparees.  It looks like JSONPath either needs special handling for `RawExtension`, or we have to switch to JSON when we hit an object we don't recognize.

**Comment by smarterclayton** [comment]
On an object from OpenShift (which is using RawExtension to nest an object)

```
Error executing template: Config is not found. Printing more information for debugging the template:
	template was:
		{.image.dockerImageMetadata.Config.Entrypoint}
	object given to jsonpath engine was:
		&v1.ImageStreamTag{TypeMeta:unversioned.TypeMeta{Kind:"ImageStreamTag", APIVersion:"v1"}, ...

error: error executing jsonpath "{.image.dockerImageMetadata.Config.Entrypoint}": Config is not found
```

**Comment by smarterclayton** [comment]
We should probably be marshaling our JSONpath objects to... JSON... before we call jsonpath.

**Comment by smarterclayton** [comment]
Note that RawExtension has "Raw" (so it can store the actual JSON bytes when unmarshalled) and "Object" so that a versioned client can deserialize, have a place to store the deserialized object, and then continue.

**Comment by janetkuo** [comment]
@kubernetes/kubectl

**Comment by pwittrock** [comment]
@smarterclayton Is there someone from RH working on upstreaming Templates or are you talking about something else?
