### ISSUE TITLE
v1.1 e2e fails against v1.3 cluster: Error waiting for all pods to be running and ready

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#27096]
I am trying to set up a test with v1.1 version against new cluster v1.3. The following is the steps I did

1. In master branch, start a cluster with command and check the cluster is up
```        
go run hack/e2e.go -v --up
```
2. Checkout to another branch and get v1.1 code 
```
git checkout tags/v1.1.7 -b release-1.1
```
3. In release-1.1 branch, start e2e test 
```
go run ./hack/e2e.go --check_version_skew=false -v --test '--test_args=--ginkgo.skip=Autoscaling\sSuite|resource\susage\stracking|Nodes|Etcd\sFailure|MasterCerts|experimental\sresource\susage\stracking|ServiceLoadBalancer|Shell|Daemon\sset|Deployment|Skipped|Restart\sshould\srestart\sall\snodes|Example|Reboot|ServiceLoadBalancer|DaemonRestart\sController\sManager|Daemon\sset\sshould\srun\sand\sstop\scomplex\sdaemon|Resource\susage\sof\ssystem\scontainers|allows\sscheduling\sof\spods\son\sa\sminion\safter\sit\srejoins\sthe\scluster'
```

But the test failed with error waiting for all pods to be running and ready

Some output 
```
Jun  8 16:21:05.879: INFO: POD                                                NODE                              PHASE      GRACE  CONDITIONS
Jun  8 16:21:05.879: INFO: e2e-image-puller-e2e-test-jinxu-minion-group-04mx  e2e-test-jinxu-minion-group-04mx  Succeeded   [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-08 15:05:35 -0700 PDT PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-06-08 15:12:18 -0700 PDT PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-08 15:05:35 -0700 PDT  }]
Jun  8 16:21:05.879: INFO: e2e-image-puller-e2e-test-jinxu-minion-group-f40j  e2e-test-jinxu-minion-group-f40j  Succeeded   [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-08 15:05:31 -0700 PDT PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-06-08 15:12:14 -0700 PDT PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-08 15:05:31 -0700 PDT  }]
Jun  8 16:21:05.879: INFO: e2e-image-puller-e2e-test-jinxu-minion-group-zlks  e2e-test-jinxu-minion-group-zlks  Succeeded   [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2016-06-08 15:07:07 -0700 PDT PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2016-06-08 15:12:25 -0700 PDT PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2016-06-08 15:07:07 -0700 PDT  }]
Jun  8 16:21:05.879: INFO: 
Jun  8 16:21:07.816: INFO: The status of Pod e2e-image-puller-e2e-test-jinxu-minion-group-04mx is Succeeded, waiting for it to be either Running or Failed
Jun  8 16:21:07.816: INFO: The status of Pod e2e-image-puller-e2e-test-jinxu-minion-group-f40j is Succeeded, waiting for it to be either Running or Failed
Jun  8 16:21:07.816: INFO: The status of Pod e2e-image-puller-e2e-test-jinxu-minion-group-zlks is Succeeded, waiting for it to be either Running or Failed
```

@dchen1107  Could you please take a look? Thanks!

**Comment by ihmccreery** [comment]
Huh, interesting.

This setup certainly seems reasonable, though I'd probably check out `HEAD` of the release-1.1 branch.
1.1.7 likely doesn't have all test fixes necessary:

```
git checkout release-1.1
```

We sometimes commit test fixes that aren't reason enough to cut a new minor version, so they just sit on `HEAD` of a branch.

**Comment by ihmccreery** [comment]
I'm working on writing up some docs on how to do version-skew testing; sorry they don't exist yet.

**Comment by dchen1107** [comment]
e2e-image-puller-e2e-test* pods are helper pods introduced to pre-pull test images for 1.3 release (https://github.com/kubernetes/kubernetes/pull/25784), but only for test environment. In your test, you are running 1.1 test infrastructure which lacking of WaitForPodsSuccess method introduced at https://github.com/kubernetes/kubernetes/pull/25784/files#diff-53314d6a19fc22810420c6bee965f5b8R139

**Comment by dchen1107** [comment]
To workaround your issue, you can simply updating cluster/gce/config-test.sh

PREPULL_E2E_IMAGES="${PREPULL_E2E_IMAGES:-false}"

**Comment by jingxu97** [comment]
@dchen1107 The workaround works. Thanks! 
The steps are listed as follows 

1.  In master (or some other) branch, rebase to the v1.3 code, also modify the file  cluster/gce/config-test.sh, set the PREPULL_E2E_IMAGES to false. Then start a cluster and check the cluster is up
PREPULL_E2E_IMAGES="${PREPULL_E2E_IMAGES:-false}"

go run hack/e2e.go -v --up
```
2. Checkout to another branch (release-1.1) and get v1.1 code 
```
git checkout tags/v1.1.7 -b release-1.1
```
3. In release-1.1 branch, modify file  cluster/gce/util.sh change a line 
```
"${MASTER_NAME}" --fields networkInterfaces[0].accessConfigs[0].natIP \		 +      "${MASTER_NAME}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
 -      --format=text | awk '{ print $2 }')
```
to
``` 
"${MASTER_NAME}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
```
Then start e2e test 
```
go run ./hack/e2e.go --check_version_skew=false -v --test '--test_args=--ginkgo.skip=Autoscaling\sSuite|resource\susage\stracking|Nodes|Etcd\sFailure|MasterCerts|experimental\sresource\susage\stracking|ServiceLoadBalancer|Shell|Daemon\sset|Deployment|Skipped|Restart\sshould\srestart\sall\snodes|Example|Reboot|ServiceLoadBalancer|DaemonRestart\sController\sManager|Daemon\sset\sshould\srun\sand\sstop\scomplex\sdaemon|Resource\susage\sof\ssystem\scontainers|allows\sscheduling\sof\spods\son\sa\sminion\safter\sit\srejoins\sthe\scluster'
```
