### ISSUE TITLE
Proposal: Add scheduler priority function for scheduling pod using host filesystem.

### ISSUE THREAD

**Issue by xuant** [kubernetes/kubernetes#27093]
## Background

For applications that need to use host local filesystem, we need some level of node-affinity in case when the application pod get wiped out on some host, we want the host to be of high priority once the pod gets rescheduled. 
At the beginning, the application might not care where it is going to be deployed. However, once it gets scheduled onto some node, the node should keep in mind (by adding a label or annotation) that this application has been deployed onto itself and should be able to get high priority next time with the same app.
## Use case:

Applications wishing to use this priority function need to add a label (or annotation) so that the priority function can decide whether to run against the application. An example would be:

```
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "",
    "labels": {
      "name": ""
    },
    "generateName": "",
    "namespace": "",
    "annotations": {
        "usePriorityFunction": "MyPriorityFunction"
    }
  },
  "spec": {

    ....

  }
}
```

When first time deployed, this priority function will have no effect because no node has information of having deployed this app. So the application will be deployed just like without this priority function.
Once it gets deployed, the node will start having the history of hosting this application. Now, for some reason, the application pod gets wiped out (while the node is still working), a new pod will be scheduled. This time the node will have the information of hosting the application thus the priority function will put this node in a high priority. The app-hosting history can be stored as an annotation of the node.
## Benefits

Application intending to use node filesystem has low chance of losing data.

**Comment by binarybana** [comment]
@xuant, I'll share our experience if it helps you (this proposal might not be needed): We are doing something similar to this, but using node labels and 1.2 alpha node affinity. Here's roughly how it works:

- There is a "download cacher" RC (I'll call it CACHE) and two jobs that depend on the downloaded file that CACHE puts on the machine (A and B)
- The CACHE RC and A and B jobs all get scheduled on the cluster at the same time.
- A and B have `nodeSelector`s for `DownloadFinished=true` which does not initially exist on any of the nodes
- CACHE gets scheduled on some node and begins downloading to the local host filesystem
- Once done, CACHE adds the `DownloadFinished=true` node label to where it is, and then enters a sleeping state.
- A and B then get serially scheduled onto this node (they each use up all the CPU's on the machine for a few hours)
- Then our external workflow management system (Luigi) detects A and B completion and deletes the CACHE rc, this then detects SIGSTOP and deletes the node label, deletes the data, and gracefully exits.

We also use other node labels along with the alpha node affinity to ensure that only one CACHE gets run on a single machine at a time (it uses up more than half of the local free space). I've also glossed over other details about how we deal with multiple file types etc..

It works pretty well, and out of the box on 1.2 clusters.

**Comment by xuant** [comment]
@binarybana , thank you so much for providing your use case!
In your case, CACHE RC generates some data onto its host that needs to be consumed by A and B. CACHE RC informs A and B the location of the data by adding a label `DownloadFinished=true` to the node. The whole process is more like event-driven process -- the finish of file download will trigger the start of A and B.

Our use case is a little different. We are deploying a single application (web-service) and there is no preprocess that tries to add a label to the node. 

I have thought about this method:we might be able to add a specific application label to a bunch of nodes so that the application will always be deployed within these nodes. But it is problematic for our use case:

  - A node with specific application label doesn't necessarily contains the data generated by the previous running pod especially when there are a lot of nodes with the same label.
  - There are going to be huge number of such applications deployed and wipe out everyday. We don't have the capability to manage the labels.

Thus it might be better to implement a priority function for this. I'm not sure if I miss something, I'd like to hear your feedback!

**Comment by davidopp** [comment]
I believe what you're requesting is what's usually called "data gravity." We plan to implement it as part of #7562.

**Comment by xuant** [comment]
@davidopp I have implemented the feature using Annotation and a customized priority function downstream which is now a workaround for our case but ultimately we will use the "data gravity" feature that has been planned but not been implemented (yet?). Is there a detailed implementation plan? I'm thinking maybe I could help do something. Thanks.

**Comment by davidopp** [comment]
We don't currently have a plan for it but hopefully we can start designing it later this year. I would suggest to subscribe to issue #7562 and watch for updates. We would definitely like to get community help in designing and implementing it!

**Comment by timothysc** [comment]
@ConnorDoyle want to triage this one, it's pretty heavy.

**Comment by davidopp** [comment]
I think #30044 will provide the desired functionality. I'd suggest we consolidate the discussion for this topic in #7562 or #30044. I assume sig-storage is the SIG where this will get disussed.

**Comment by timothysc** [comment]
ok, closing this one then in lieu of comment above.  reopen if needed.
