### ISSUE TITLE
Node PR Puller `node-pull-build-e2e-test` failing with "unable to create test archive failed to copy ginkgo"

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#27104]
[Node PR Puller `node-pull-build-e2e-test` suite](http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/) is failing with: 
```
17:30:31 +++ [0608 17:30:31] Placing binaries
17:30:33 I0608 17:30:33.122280   23621 e2e_remote.go:104] Building archive...
17:30:33 ================================================================
17:30:33 Failure Finished Host  Test Suite
17:30:33 
17:30:33 unable to create test archive failed to copy ginkgo exit status 1..
17:30:33 ================================================================
17:30:34 ================================================================
17:30:34 Failure Finished Host  Test Suite
17:30:34 
17:30:34 unable to create test archive failed to copy ginkgo exit status 1..
17:30:34 ================================================================
17:30:34 ================================================================
17:30:34 Failure Finished Host  Test Suite
17:30:34 
17:30:34 unable to create test archive failed to copy ginkgo exit status 1..
17:30:34 ================================================================
17:30:34 ================================================================
17:30:34 Failure Finished Host  Test Suite
17:30:34 
17:30:34 unable to create test archive failed to copy ginkgo exit status 1..
17:30:34 ================================================================
17:30:34 Failure: 4 errors encountered.exit status 1
```

Examples:
* http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/9733/console
* http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/9734/
* http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/9735/
* http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/9736/
* http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/9737/
* http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/9738/
* http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/9739/

**Comment by fejta** [comment]
This is the failing line of code...
```sh
	out, err = exec.Command("cp", ginkgo, filepath.Join(tardir, "ginkgo")).CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("failed to copy ginkgo %v.", err)
	}
```

**Comment by fejta** [comment]
PASS: http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/9732/console
FAIL: http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/9733/console

Seems like this disappeared:
17:13:20  > /usr/bin/git rev-list fb5873732f5ee808686d9e9adb40c48778257f67 # timeout=10

**Comment by fejta** [comment]
@pwittrock my leading theory is this is something in https://github.com/kubernetes/kubernetes/commit/e94e1c6e3de9dc0515827ff0c38abd032baf0b90#diff-2cf4815674d337c5531ee1bbf343d97c

**Comment by fejta** [comment]
The issue is that the above PR changed a bunch of `foo()` to be `go foo()` and thus we no longer wait for getArchive() to complete before starting tests

**Comment by dchen1107** [comment]
After merging, kubelet-gce-e2e-ci still failed with the same issue. reopen the issue. Currently the failure blocked the merge-bot.

**Comment by dchen1107** [comment]
#27108 did stop the bleeding. Now kubelet-gce-e2e-ci is green:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubelet-gce-e2e-ci/4197/console

and merge-bot is unblocked.

**Comment by pwittrock** [comment]
@fejta I think the "go arc" piece was a red herring.  I suspect the issue is that the same PR tries to copy the `ginkgo` binary into the archive directory, but PR #26830 stops building ginkgo, so the copy fails.

That is why this line then fails...

```go
out, err = exec.Command("cp", ginkgo, filepath.Join(tardir, "ginkgo")).CombinedOutput()
    if err != nil {
        return "", fmt.Errorf("failed to copy ginkgo %v.", err)
    }
```
