### ISSUE TITLE
Kubelet: Add a DELETE PodUpdate type

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#27105]
Now `kubelet/config` generates 4 kinds of pod update operations:
* ADD: The pod is newly added.
* UPDATE: The pod is semantically different.
* REMOVE: The pod is removed.
* RECONCILE: The pod is semantically the same, but the pod status is different.

See [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/types/pod_update.go#L37-L44)
However, graceful deletion doesn't remove the pod, only sets the DeletionTimestamp, so it is always treated as a `UPDATE`.
This makes the code hard to understand and also makes it very hard to distinguish in the log whether the pod is really updated or gracefully deleted.

We should add a new update operation `DELETE` for graceful deletion to make the code and log more intuitive. XRef #27101.

@yujuhong 
/cc @kubernetes/sig-node

**Comment by resouer** [comment]
@Random-Liu May I handle this? I'm doing work related to pod lifecycle recently.

**Comment by Random-Liu** [comment]
@resouer Of course! Feel free to do it :)
