### ISSUE TITLE
Unclear docs regarding AWS EBS persistent volumes on a Multi AZ cluster

### ISSUE THREAD

**Issue by erez-rabih** [kubernetes/kubernetes#27116]
Hi,

The docs mention that the volume must be created in the same AZ of the cluster.

What happens when I have a multi AZ cluster and make a PVC on a pod for a volume that was created on AZ-X? The docs doesn't mention anything about that.
As I see it there are two options:

1. The scheduler will be aware of that PVC and schedule that pod only on nodes that belong to AZ-X
2. The scheduler will not be aware of that and when it schedules the pod to a node on a different AZ than AZ-X the pod creation will fail.

Which of them is the expected behavior?

**Comment by jlowdermilk** [comment]
cc @saad-ali, @justinsb

**Comment by saad-ali** [comment]
@quinton-hoole

**Comment by quinton-hoole** [comment]
@erez-rabih The answer is 1.

It's documented in https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/multiple-zones.md

Please do let us know if anything is unclear, or if you struggled to find the above documentation.

Regards

Quinton

**Comment by erez-rabih** [comment]
@quinton-hoole thanks for the pointer it clearly answers my question.

**Comment by mabushey** [comment]
> Please do let us know if anything is unclear, or if you struggled to find the above documentation. 

The docs are very unclear/non-existent, and the above link gives a 404.
