### ISSUE TITLE
open-iscsi software iscsi initiator broken for non-default interfaces

### ISSUE THREAD

**Issue by mcumings** [kubernetes/kubernetes#27131]
open-iscsi software initiators are currently broken for non-`default` interfaces due to the fact that
the devicePath (in iscsi_util.go) is assumed to use the `/dev/disk/by-path/pci` prefixing scheme
for all interfaces not named `default`.  This causes waitForPathToExist to timeout after 10 seconds
since the device path that it is waiting for is not the `/dev/disk/by-path/ip`- prefixed path that is
created, resulting in host logging such as:

```
Jun 09 04:35:12 kube-node1 kubelet[1427]: E0609 04:35:12.736129    1427 kubelet.go:1780] Unable to mount volumes for pod "monitoring-influxdb-grafana-v3-cyict_kube-system(8749dff7-2dfb-11e6-a330-00163e0a0a01)": Could not attach disk: Timeout after 10s; skipping pod
```
or K8S event logs such as:

```
2016-06-08 21:25:27 -0700 PDT   2016-06-08 21:26:36 -0700 PDT   4         monitoring-influxdb-grafana-v3-hm0t5     Pod                                                       Warning   FailedMount         {kubelet 192.168.10.11}     Unable to mount volumes for pod "monitoring-influxdb-grafana-v3-hm0t5_kube-system(2a81fc54-2dfa-11e6-a330-00163e0a0a01)": Could not attach disk: Timeout after 10s
2016-06-08 21:25:27 -0700 PDT   2016-06-08 21:26:36 -0700 PDT   4         monitoring-influxdb-grafana-v3-hm0t5     Pod                                                       Warning   FailedSync          {kubelet 192.168.10.11}     Error syncing pod, skipping: Could not attach disk: Timeout after 10s
```

open-iscsi support for hardware transports was added in the following commit:

https://github.com/kubernetes/kubernetes/commit/6e46fa1fd4c6222993e4fb7d64fd694fdebb6f9c

In this commit, software iSCSI support was assumed to be done through only the use of the default
interface.  According to the documentation at https://github.com/open-iscsi/open-iscsi (Section 5.1.1)
both software and offload/hardware interfaces are intended to be configured using named interface
specifications and `default` is only a backwards-compatibility vehicle.  Configuration of `default`
cannot be done via the use of `/etc/iscsi/ifaces/default` as this approach is specifically forbidden in
the documentation:

```
Warning: Do not name a iface config file  "default" or "iser".
They are special value/file that is used by the iscsi tools for
backward compatibility. If you name a iface default or iser, then
the behavior is not defined.
```

Leaving this here to help others associate various failure modes with this issue and possible resolution:

In my case I am just learning and this is my first iSCSI deployment.  My initial error was that I was
receiving an `Invalid Initiatorname` message at discovery-time even though I had used
`/etc/iscsi/initiatorname.iscsi` to define a name.  This approach failed because I didn't realize that
iscsid needed to be bounced before it would pick up changes to that file.  I had defined a
custom `/etc/iscsi/ifaces/iface` specification and was using that to accomplish the task of setting
my initiator name.  I was able to unwind this mess and return to the use of `default` once I read
the code and understood what it was attempting to do.

**Comment by childsb** [comment]
i'm marking this as a feature request against the iscsi volume driver.

RFE:  support iscsi interfaces named something besides 'default'.

**Comment by rootfs** [comment]
@anish

**Comment by anish** [comment]
Sorry about the previous comment, I was logged in to the wrong account.

In theory the fix should be easy, just move the path check from iface name to transport_name. I will take a look asap, unfortunately I am travelling till monday.

@mcumings can you share your iface file ? It will help me validate

**Comment by mcumings** [comment]
I no longer have the file precisely as it was.  However, I did have some version of what I had used committed into my VCS.  While not 100% sure this is what I was using while encountering the failure it does looks to be about what I'd expect:

```
iface.transport_name = tcp
iface.initiatorname = iqn.2016-06.elided.kube-node1:eth0
iface.net_ifacename = eth0
iface.state = enable
iface.num = 0

iface.transport_name = tcp
iface.initiatorname = iqn.2016-06.elided.kube-node1:default
iface.net_ifacename = default
iface.state = enable
iface.num = 1
```
