### ISSUE TITLE
Vagrant kube-up broken ?

### ISSUE THREAD

**Issue by VinayKumarbrsoft** [kubernetes/kubernetes#27149]
I am trying to do a kube-up on vagrant with the latest version and have run into problems: Cluster provisioning stops at the following:

`==> node-1:           ID: /etc/cron.hourly/logrotate
==> node-1:     Function: file.managed
==> node-1:       Result: True
==> node-1:      Comment: File /etc/cron.hourly/logrotate updated
==> node-1:      Started: 21:20:15.348227
==> node-1:     Duration: 6.661 ms
==> node-1:      Changes:   
==> node-1:               ----------
==> node-1:               diff:
==> node-1:                   New file
==> node-1:               mode:
==> node-1:                   0755
==> node-1: 
==> node-1: Summary
==> node-1: -------------
==> node-1: Succeeded: 29 (changed=26)
==> node-1: Failed:     8
==> node-1: -------------
==> node-1: Total states run:     37`

kubectl get nodes command returns

`kubernetes vbi01$ kubectl get nodes
The connection to the server 10.245.1.2 was refused - did you specify the right host or port?`

docker version is : 

`[root@kubernetes-master ~]# docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-9.gitee06d03.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      ee06d03/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-9.gitee06d03.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      ee06d03/1.9.1
 Built:           
 OS/Arch:         linux/amd64`

kubelet on master is running but throws following error:

`[root@kubernetes-master ~]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-06-09 21:15:44 UTC; 14min ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 5178 (kubelet)
   Memory: 7.9M
      CPU: 7.754s
   CGroup: /system.slice/kubelet.service
           ├─5178 /usr/local/bin/kubelet --enable-debugging-handlers=false --config=/etc/kubernetes/manifests --allow-privileged=True --v=2 --cluster-dns=10.247.0.10 --cluster-domain=cluster.local...
           └─5288 journalctl -k -f

Jun 09 21:16:06 kubernetes-master kubelet[5178]: I0609 21:16:06.989623    5178 manager.go:1691] Need to restart pod infra container for "etcd-server-kubernetes-master_kube-system(04739...is not found
Jun 09 21:16:06 kubernetes-master kubelet[5178]: I0609 21:16:06.991015    5178 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
Jun 09 21:16:06 kubernetes-master kubelet[5178]: I0609 21:16:06.991197    5178 docker.go:161] Pulling image gcr.io/google_containers/pause:2.0 without credentials
Jun 09 21:16:21 kubernetes-master kubelet[5178]: I0609 21:16:21.413480    5178 docker.go:161] Pulling image gcr.io/google_containers/pause:2.0 without credentials
Jun 09 21:16:22 kubernetes-master kubelet[5178]: I0609 21:16:22.134755    5178 kubelet.go:2414] SyncLoop (PLEG): "etcd-server-events-kubernetes-master_kube-system(7e7822789321abfd8fbefa5d63c5f4ee)...
Jun 09 21:16:25 kubernetes-master kubelet[5178]: I0609 21:16:25.375858    5178 docker.go:161] Pulling image gcr.io/google_containers/etcd:2.2.1 without credentials
Jun 09 21:16:26 kubernetes-master kubelet[5178]: I0609 21:16:26.156371    5178 kubelet.go:2414] SyncLoop (PLEG): "etcd-server-kubernetes-master_kube-system(047397a03841de24aac3acbd0cab7cfa)", even...
Jun 09 21:16:58 kubernetes-master kubelet[5178]: I0609 21:16:58.901724    5178 docker.go:161] Pulling image gcr.io/google_containers/etcd:2.2.1 without credentials
Jun 09 21:17:00 kubernetes-master kubelet[5178]: I0609 21:17:00.484414    5178 kubelet.go:2414] SyncLoop (PLEG): "etcd-server-events-kubernetes-master_kube-system(7e7822789321abfd8fbefa5d63c5f4ee)...
Jun 09 21:17:02 kubernetes-master kubelet[5178]: I0609 21:17:02.552022    5178 kubelet.go:2414] SyncLoop (PLEG): "etcd-server-kubernetes-master_kube-system(047397a03841de24aac3acbd0cab7cfa)", even..`

None of kube-apiserver, kube-control-manager, kube-scheduler are running. 

`[root@kubernetes-master ~]# systemctl status kube-apiserver
● kube-apiserver.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
`

Docker ps command on master gives me the following:
`[root@kubernetes-master ~]# docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
e73d2fd8850b        gcr.io/google_containers/etcd:2.2.1   "/bin/sh -c '/usr/loc"   15 minutes ago      Up 15 minutes                           k8s_etcd-container.d95563a7_etcd-server-kubernetes-master_kube-system_047397a03841de24aac3acbd0cab7cfa_53846a40
970392e7dc78        gcr.io/google_containers/etcd:2.2.1   "/bin/sh -c '/usr/loc"   15 minutes ago      Up 15 minutes                           k8s_etcd-container.caff6bc4_etcd-server-events-kubernetes-master_kube-system_7e7822789321abfd8fbefa5d63c5f4ee_3a9179aa
12f578d11226        gcr.io/google_containers/pause:2.0    "/pause"                 16 minutes ago      Up 16 minutes                           k8s_POD.6059dfa2_etcd-server-kubernetes-master_kube-system_047397a03841de24aac3acbd0cab7cfa_e4ee8706
a20c00663e10        9981ca1bbdb5                          "/pause"                 16 minutes ago      Up 16 minutes                           k8s_POD.6059dfa2_etcd-server-events-kubernetes-master_kube-system_7e7822789321abfd8fbefa5d63c5f4ee_d5ec2182
`

The logs has got following errors:

`[root@kubernetes-master ~]# journalctl -r
-- Logs begin at Sat 2015-12-26 10:24:57 UTC, end at Thu 2016-06-09 21:34:01 UTC. --
Jun 09 21:34:01 kubernetes-master kube-addons.sh[5037]: The connection to the server localhost:8080 was refused - did you specify the right host or port?
Jun 09 21:34:00 kubernetes-master kube-addons.sh[5037]: The connection to the server localhost:8080 was refused - did you specify the right host or port?
Jun 09 21:33:44 kubernetes-master salt-minion[4588]: [ERROR   ] Master hostname: 'salt' not found. Retrying in 30 seconds
Jun 09 21:33:44 kubernetes-master salt-minion[4588]: [ERROR   ] DNS lookup of 'salt' failed.
`

I have tried several times now and getting exactly the same error and cluster provisioning stops at the same point.   

```
export KUBERNETES_PROVIDER=vagrant
curl -sS https://get.k8s.io | bash
```

**Comment by lxjuly** [comment]
Use the head version!

**Comment by VinayKumarbrsoft** [comment]
I am using the head version. What I am doing wrong?

`vbi01$ cat HEAD
 ref: refs/heads/master`

**Comment by VinayKumarbrsoft** [comment]
Provisio-utils.sh had following code in the distribution: 

` # Install salt binaries
    curl -sS -L --connect-timeout 20 --retry 6 --retry-delay 10 https://bootstrap.saltstack.com | sh -s`

Replaced it with the following and restarted the cluster to resolve the problem:

`# Install salt from official repositories
    # Need to enable testing-repos to get version of salt with fix for dnf-core-plugins
    dnf config-manager --set-enabled updates-testing
    dnf install -y salt-minion`

**Comment by jessehu** [comment]
Hi @VinayKumarbrsoft I'm using k8s 1.3.5 and get the same issue.  Do you mean this: replace "https://bootstrap.saltstack.com | sh -s" with "dnf install -y salt-minion", then re-run "kube-up.sh" ? 

But "dnf install -y salt-minion" installs the same version that installed by "https://bootstrap.saltstack.com | sh -s"

sudo dnf install -y salt-minion
Last metadata expiration check: 0:29:16 ago on Fri Aug 26 10:38:59 2016.
Package salt-minion-2015.5.10-2.fc23.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by VinayKumarbrsoft** [comment]
@jessehu Sorry for late reply but the below did work for me. 

```
dnf config-manager --set-enabled updates-testing
dnf install -y salt-minion
```
