### ISSUE TITLE
Finish implementing Acting-As

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#27152]
First, move [proposal](https://github.com/kubernetes/kubernetes/pull/16933) to a design doc and update to describe what was done in the [current implementation](https://github.com/kubernetes/kubernetes/pull/23549).

Then rewrite the controllers to know how to Act-As a certain user.

Need to decide what user the controllers act as.

The user that the controller should act as _could_ be the default service account, but in general this user needs more power than the service account that is automatically added to the Pods.  So, each namespace probably needs at least two types of default service accounts: one that can make pods in that namespace, etc, and one that is the default for the Containers themselves, with less privileges by default.

Need to make all this the default and have it be part of all e2es.

**Comment by erictune** [comment]
APIserver side was implemented in   https://github.com/kubernetes/kubernetes/pull/23549 but still need to have client side.

**Comment by erictune** [comment]
Current implementation is using  "unrestricted impersonation".  In the future, consider having the ability to do "restricted impersonation".  In the latter, the action is authorized if both the authenticated and "acting-as" roles are authorized to do the action.   

This makes it possible to two two things at once: (1) restrict the controller to only do the operations it needs to do (e.g. a pod controller can only make pods, and not configure the network), and (2) avoid being a confused deputy.  This would applying a double authorization check in the request authorization stage.

**Comment by liggitt** [comment]
I *really* don't want to give controllers the ability to impersonate any user they want. I'd rather see us define the permissions each controller needs and give it a service account with just those permissions.

**Comment by deads2k** [comment]
> I really don't want to give controllers the ability to impersonate any user they want. I'd rather see us define the permissions each controller needs and give it a service account with just those permissions. That seems like a good first step, even without a "unioning impersonation", which I'm not sure about

If I'm reading the comments correctly, it sounds like restricting individual controllers to their minimal permissions is a first step for @erictune's proposal too.  Otherwise, a user who can delete nodes with an unrestricted controller account could delete nodes.

I also have reservations about having controllers impersonate users.  I'm of the opinion that if I grant someone the ability to create RCs, I shouldn't also have to grant them the power to create pods.  I don't see much utility in it.

I'm also worried about trying to handle ownership.  If deads makes rc1 and liggitt edits rc1, who owns the rc?

**Comment by erictune** [comment]
Concrete example of intersection:

- user rc-manager can read/write pods in all namespaces
- user eric can create read/write pods and secrets in namespace N
- rc-manager acting as eric can read/write pods in namespace N (and nothing else)

---

I'm not sure I follow deads's comment that "I grant someone the ability to create RCs, I shouldn't also have to grant them the power to create pod".  Do you mean you want to prevent users from directly creating pods?  Or that you want having permission to make RCs imply permission to make pods?

---

Regarding the ownership question in previous post, here is how I thought it might work:
- When deads creates rc1, there is a new field on it called "podCreationUser".  Since deads didn't know about this field, it got defaulted to the name of a certain service account in that namespace, called `system:service-account:somens:default-robot`.
- deads has to be able to act as `system:service-account:somens:default-controller`.
- when the rc-manager makes podA in response to rc1, it acts as  `system:service-account:somens:default-controller`.
- when liggit edits rc1, it checks that liggit has permission to edit rcs, in general, and that liggitt can act as  `system:service-account:somens:default-controller`, which he can.
- when the rc-manger makes podB for rc1, it still acts as  `system:service-account:somens:default-controller`.
- there is no "owner" for rc1, podA, or podB.  
- peoples permissions to create rcs, pods, and to act as service accounts can change at any time, and the rc manager and the pod objects don't need to know about it.  They don't store "ownership" inside themselves.

-

**Comment by deads2k** [comment]
> "I grant someone the ability to create RCs, I shouldn't also have to grant them the power to create pod". Do you mean you want to prevent users from directly creating pods? Or that you want having permission to make RCs imply permission to make pods?

I would deny them from creating pods directly.  The RC/pods example makes it a little less clear since one covers the other, but one reason for creating a second API is to create a curated sub-set of functionality from some larger component.  Allowing access to the smaller API can result in an escalation to perform work that the user doesn't have the power to perform.

I'm also not convinced that we're less likely to have bugs downgrading a controllers permissions.  I definitely agree that we should subdivide permissions for individual controllers (see openshift's usage of ServiceAccounts in this area: https://github.com/openshift/origin/blob/master/pkg/cmd/server/bootstrappolicy/infra_sa_policy.go), but the impersonation bit seems complex and bugs would be hard to detect since the controller would already have the power to perform the action.

**Comment by erictune** [comment]
Some second APIs do what you said (provide controlled access to powerful
actions).    Other second APIs just provide automation of tasks a user
could do (if they didn't need sleep).  Like RCs.

On Jul 1, 2016 5:25 AM, "David Eads" <notifications@github.com> wrote:

"I grant someone the ability to create RCs, I shouldn't also have to grant
them the power to create pod". Do you mean you want to prevent users from
directly creating pods? Or that you want having permission to make RCs
imply permission to make pods?

I would deny them from creating pods directly. The RC/pods example makes it
a little less clear since one covers the other, but one reason for creating
a second API is to create a curated sub-set of functionality from some
larger component. Allowing access to the smaller API can result in an
escalation to perform work that the user doesn't have the power to perform.

I'm also not convinced that we're less likely to have bugs downgrading a
controllers permissions. I definitely agree that we should subdivide
permissions for individual controllers (see openshift's usage of
ServiceAccounts in this area:
https://github.com/openshift/origin/blob/master/pkg/cmd/server/bootstrappolicy/infra_sa_policy.go),
but the impersonation bit seems complex and bugs would be hard to detect
since the controller would already have the power to perform the action.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/27152#issuecomment-229933649>,
or mute the thread
<https://github.com/notifications/unsubscribe/AHuudsJ4pkp3hivLVTK-dqECU2w8GQ8vks5qRQdCgaJpZM4Iye2y>
.

**Comment by liggitt** [comment]
we don't plan to make controllers use impersonation at this time
