### ISSUE TITLE
PersistentVolumeClaim doesn't bind to a volume when created again

### ISSUE THREAD

**Issue by metral** [kubernetes/kubernetes#27164]
This is a dup of https://github.com/kubernetes/kubernetes/issues/20753 since the original filer hasn't reopened the issue.

I'm hitting this issue on v1.2.4 with NFS + PVC's.

**Kubernetes OS**: CoreOS 835.9.0
**NFS OS**: Ubuntu 16.04

Feel free to close this if https://github.com/kubernetes/kubernetes/issues/20753 gets reopened.

**Comment by childsb** [comment]
@metral can you retry this on the 1.3 code base and attach logs of the failure? We made extensive changes to the Volume controller code in 1.3..

The issue #20753 was with the recycler.  Yours may be the same or dif.

**Comment by matchstick** [comment]
We believe this is addressed in 1.3. If you still find it there, please re-open.
