### ISSUE TITLE
Integration tests seem to not run

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#27175]
When running integration tests yesterday I had:
```
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":3,"createdIndex":3}}
+++ [0610 10:32:05] Running integration test cases
Running tests for APIVersion: v1,extensions/v1beta1 with etcdPrefix: registry
+++ [0610 10:32:05] Running tests without code coverage
ok  	k8s.io/kubernetes/test/integration	368.253s
```

Today I have:
```
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":3,"createdIndex":3}}
+++ [0610 10:47:11] Running integration test cases
Running tests for APIVersion: batch/v1 with etcdPrefix: registry
+++ [0610 10:47:11] Running tests without code coverage
ok  	k8s.io/kubernetes/test/integration	0.234s
```

It seems that we no longer running integration tests (I don't believe we speeded them up by 1500x)

@mikedanese @lavalamp @kubernetes/sig-testing

**Comment by wojtek-t** [comment]
@k8s-oncall - FYI

**Comment by wojtek-t** [comment]
And from Jenkins builder from a random PR:
```
Running tests for APIVersion: batch/v1 with etcdPrefix: registry
+++ [0610 02:24:25] Running tests without code coverage
ok  	k8s.io/kubernetes/test/integration	0.037s
```

Clearly something is really wrong:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/30014/consoleFull

**Comment by wojtek-t** [comment]
In particular, it seems we are only running a single test:
```
TestMasterExportsSymbols
```

See e.g.:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/12875/artifacts/?project=kubernetes-jenkins

**Comment by wojtek-t** [comment]
The first run in which it was broken is this one:
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-test-go/12866/

**Comment by wojtek-t** [comment]
So most probably this was broken by:
https://github.com/kubernetes/kubernetes/pull/26188

**Comment by wojtek-t** [comment]
I'm going to try to revert that PR.

**Comment by wojtek-t** [comment]
@brendandburns @spxtr

**Comment by wojtek-t** [comment]
Reverting that PR helps. I'm going to merge it manually once tests are green.

**Comment by lavalamp** [comment]
thanks!

**Comment by wojtek-t** [comment]
BTW - it seems that I broke build in the meantime for few hours. But I think it was still a better solution than not running integration tests at all and risking breaking next test...

**Comment by dchen1107** [comment]
@fejta please triage and delegate to the engineer. Thanks!

**Comment by fejta** [comment]
@wojtek-t fixed things here. http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-test-unit-integration/30140/consoleFull shows integration tests run again
