### ISSUE TITLE
No encoder for resource.Quantity 

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#27178]
When I'm running the new version of [addon-resizer](https://github.com/kubernetes/contrib/tree/master/addon-resizer) I see the following logs:

```
proto: no encoder for i resource.int64Amount [GetProperties]
proto: no encoder for d resource.infDecAmount [GetProperties]
proto: no encoder for s string [GetProperties]
proto: no encoder for Format resource.Format [GetProperties]
```

What did I wrong?

cc @smarterclayton @wojtek-t

**Comment by piosz** [comment]
I had cluster in version `v1.3.0-alpha.5.313+f1edc31d526094` and addon-resizer in version 1.1 which uses client in version `release_1_2` from commit https://github.com/kubernetes/kubernetes/commit/7476d97781563b70e8b89a8bd3f99ea75ae6c290. 

There were also other suspicious logs:
```
I0609 20:22:38.954902       1 nanny_lib.go:102] The expected resources are %!v(PANIC=reflect.Value.Interface: cannot return value obtained from unexported field or method)
```

**Comment by piosz** [comment]
cc @fgrzadkowski @lavalamp

**Comment by smarterclayton** [comment]
This is a bug because something is using an internal version to encode a
value.  We've seen this for kubectl apply and a few other commands - if you
end up calling Marshal on an internal API object it will print these errors.

**Comment by smarterclayton** [comment]
The issue for apply is https://github.com/kubernetes/kubernetes/issues/26840

**Comment by piosz** [comment]
I don't see this issue anymore.
