### ISSUE TITLE
Failed to start kubernetes API server in docker after system crash

### ISSUE THREAD

**Issue by smsahu** [kubernetes/kubernetes#27172]
I am unable to start my existing kebernetes setup in local docker after a system crash.

smrutiranjans@smrutirn-ub:~$ docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
c70007d8bea6        gcr.io/google_containers/hyperkube-amd64:v1.2.4   "/setup-files.sh IP:1"   8 seconds ago       Up 7 seconds                            k8s_setup.eb843218_k8s-master-127.0.0.1_default_721118f359852533089009890ac21208_b1639811
fb91febe762b        gcr.io/google_containers/hyperkube-amd64:v1.2.4   "/hyperkube scheduler"   8 seconds ago       Up 7 seconds                            k8s_scheduler.dbfcc0_k8s-master-127.0.0.1_default_721118f359852533089009890ac21208_2f4d2aa4
61a1433ede84        gcr.io/google_containers/hyperkube-amd64:v1.2.4   "/hyperkube controlle"   9 seconds ago       Up 8 seconds                            k8s_controller-manager.76914b67_k8s-master-127.0.0.1_default_721118f359852533089009890ac21208_9bf5d3cf
4bd7b18f5d33        gcr.io/google_containers/hyperkube-amd64:v1.2.4   "/hyperkube proxy --m"   9 seconds ago       Up 8 seconds                            k8s_kube-proxy.a1014855_k8s-proxy-127.0.0.1_default_0cda4a663a246109121ac68b3c7e82b7_7728e293
b513d59d66ab        gcr.io/google_containers/pause:2.0                "/pause"                 9 seconds ago       Up 8 seconds                            k8s_POD.6059dfa2_k8s-etcd-127.0.0.1_default_1df6a8b4d6e129d5ed8840e370203c11_40008c24
4e0ce2e742b9        gcr.io/google_containers/pause:2.0                "/pause"                 9 seconds ago       Up 8 seconds                            k8s_POD.6059dfa2_k8s-master-127.0.0.1_default_721118f359852533089009890ac21208_4f56912c
f49704b85001        gcr.io/google_containers/pause:2.0                "/pause"                 9 seconds ago       Up 8 seconds                            k8s_POD.6059dfa2_k8s-proxy-127.0.0.1_default_0cda4a663a246109121ac68b3c7e82b7_b6ad1dc8
f57c030975d4        gcr.io/google_containers/hyperkube-amd64:v1.2.4   "/hyperkube kubelet -"   28 seconds ago      Up 27 seconds                           hopeful_noether
smrutiranjans@smrutirn-ub:~$ docker logs f57c030975d4
I0610 05:04:01.171324     657 server.go:137] Running kubelet in containerized mode (experimental)
W0610 05:04:02.567108     657 server.go:445] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Trying auth path instead.
W0610 05:04:02.567133     657 server.go:406] Could not load kubernetes auth path /var/lib/kubelet/kubernetes_auth: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
I0610 05:04:02.567253     657 plugins.go:71] No cloud provider specified.
I0610 05:04:02.567266     657 server.go:312] Successfully initialized cloud provider: "" from the config file: ""
I0610 05:04:02.567343     657 manager.go:132] cAdvisor running in container: "/docker/f57c030975d4b52b1bd09c721bd95d7331a6250a16fa4ed4b607b6810a6c6f0f"
I0610 05:04:02.637692     657 fs.go:109] Filesystem partitions: map[/dev/sda2:{mountpoint:/rootfs major:8 minor:2 fsType: blockSize:0}]
I0610 05:04:05.389501     657 machine.go:50] Couldn't collect info from any of the files in "/rootfs/etc/machine-id,/var/lib/dbus/machine-id"
I0610 05:04:05.389552     657 manager.go:169] Machine: {NumCores:4 CpuFrequency:3300000 MemoryCapacity:8273645568 MachineID: SystemUUID:4C4C4544-0054-5A10-804C-C2C04F443032 BootID:47a1af30-e71f-45b7-9685-34766d257edf Filesystems:[{Device:/dev/sda2 Capacity:117004935168 Type:vfs Inodes:7266304}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:128035676160 Scheduler:deadline}] NetworkDevices:[{Name:eth0 MacAddress:ec:f4:bb:04:24:d7 Speed:4294967295 Mtu:1500} {Name:wlan0 MacAddress:ac:7b:a1:3e:0d:82 Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:8273645568 Cores:[{Id:0 Threads:[0 2] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[1 3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:4194304 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I0610 05:04:05.390158     657 manager.go:175] Version: {KernelVersion:3.19.0-59-generic ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.11.2 CadvisorVersion: CadvisorRevision:}
I0610 05:04:05.390610     657 server.go:344] Using root directory: /var/lib/kubelet
I0610 05:04:05.390778     657 server.go:673] Adding manifest file: /etc/kubernetes/manifests
I0610 05:04:05.390790     657 file.go:47] Watching path "/etc/kubernetes/manifests"
I0610 05:04:05.390796     657 server.go:683] Watching apiserver
W0610 05:04:05.400387     657 kubelet.go:508] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
I0610 05:04:05.400425     657 kubelet.go:380] Hairpin mode set to "hairpin-veth"
I0610 05:04:05.460749     657 manager.go:212] Setting dockerRoot to /var/lib/docker
I0610 05:04:08.564015     657 plugins.go:56] Registering credential provider: .dockercfg
I0610 05:04:14.719090     657 plugins.go:291] Loaded volume plugin "kubernetes.io/aws-ebs"
I0610 05:04:14.719134     657 plugins.go:291] Loaded volume plugin "kubernetes.io/empty-dir"
I0610 05:04:14.719153     657 plugins.go:291] Loaded volume plugin "kubernetes.io/gce-pd"
I0610 05:04:14.719176     657 plugins.go:291] Loaded volume plugin "kubernetes.io/git-repo"
I0610 05:04:14.719203     657 plugins.go:291] Loaded volume plugin "kubernetes.io/host-path"
I0610 05:04:14.719220     657 plugins.go:291] Loaded volume plugin "kubernetes.io/nfs"
I0610 05:04:14.719236     657 plugins.go:291] Loaded volume plugin "kubernetes.io/secret"
I0610 05:04:14.719252     657 plugins.go:291] Loaded volume plugin "kubernetes.io/iscsi"
I0610 05:04:14.719280     657 plugins.go:291] Loaded volume plugin "kubernetes.io/glusterfs"
I0610 05:04:14.719300     657 plugins.go:291] Loaded volume plugin "kubernetes.io/persistent-claim"
I0610 05:04:14.719316     657 plugins.go:291] Loaded volume plugin "kubernetes.io/rbd"
I0610 05:04:14.719332     657 plugins.go:291] Loaded volume plugin "kubernetes.io/cinder"
I0610 05:04:14.719354     657 plugins.go:291] Loaded volume plugin "kubernetes.io/cephfs"
I0610 05:04:14.719379     657 plugins.go:291] Loaded volume plugin "kubernetes.io/downward-api"
I0610 05:04:14.719394     657 plugins.go:291] Loaded volume plugin "kubernetes.io/fc"
I0610 05:04:14.719410     657 plugins.go:291] Loaded volume plugin "kubernetes.io/flocker"
I0610 05:04:14.719436     657 plugins.go:291] Loaded volume plugin "kubernetes.io/azure-file"
I0610 05:04:14.719453     657 plugins.go:291] Loaded volume plugin "kubernetes.io/configmap"
I0610 05:04:14.719514     657 server.go:645] Started kubelet
E0610 05:04:14.719574     657 kubelet.go:956] Image garbage collection failed: unable to find data for container /
I0610 05:04:14.719647     657 server.go:109] Starting to listen on 0.0.0.0:10250
I0610 05:04:14.719957     657 server.go:126] Starting to listen read-only on 0.0.0.0:10255
E0610 05:04:14.720260     657 event.go:202] Unable to write event: 'Post http://localhost:8080/api/v1/namespaces/default/events: dial tcp 127.0.0.1:8080: connection refused' (may retry after sleeping)
I0610 05:04:14.723084     657 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
I0610 05:04:14.723097     657 manager.go:123] Starting to sync pod status with apiserver
I0610 05:04:14.723110     657 kubelet.go:2356] Starting kubelet main sync loop.
I0610 05:04:14.723116     657 kubelet.go:2365] skipping pod synchronization - [container runtime is down]
E0610 05:04:14.798120     657 manager.go:2142] Unable to inspect container "755099b049377c01f41476088812a42442e9f573ff7091524d2d1bebbe609746": No such container: 755099b049377c01f41476088812a42442e9f573ff7091524d2d1bebbe609746
E0610 05:04:14.823614     657 manager.go:2142] Unable to inspect container "704c19d126fbf156fbfd329c3b8feb139eca941885119476e7305579db22c015": No such container: 704c19d126fbf156fbfd329c3b8feb139eca941885119476e7305579db22c015
E0610 05:04:14.929092     657 manager.go:212] Docker container factory registration failed: docker found, but not using native exec driver.
I0610 05:04:14.935127     657 factory.go:97] Registering Raw factory
I0610 05:04:15.126804     657 kubelet.go:2754] Recording NodeHasSufficientDisk event message for node 127.0.0.1
I0610 05:04:15.126846     657 kubelet.go:1134] Attempting to register node 127.0.0.1
I0610 05:04:15.127678     657 kubelet.go:1137] Unable to register 127.0.0.1 with the apiserver: Post http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: connection refused
I0610 05:04:15.132819     657 manager.go:1003] Started watching for new ooms in manager
I0610 05:04:15.136803     657 oomparser.go:182] oomparser using systemd
I0610 05:04:15.138147     657 manager.go:256] Starting recovery of all containers
I0610 05:04:15.146285     657 manager.go:261] Recovery completed
I0610 05:04:15.392870     657 kubelet.go:2754] Recording NodeHasSufficientDisk event message for node 127.0.0.1
I0610 05:04:15.392907     657 kubelet.go:1134] Attempting to register node 127.0.0.1
I0610 05:04:15.393415     657 kubelet.go:1137] Unable to register 127.0.0.1 with the apiserver: Post http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: connection refused

**Comment by smsahu** [comment]
started using below command:--

export K8S_VERSION=v1.2.4
export ENABLE_DEPLOYMENTS=true
export ARCH=amd64
docker run -d \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:rw \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged \
    gcr.io/google_containers/hyperkube-${ARCH}:${K8S_VERSION} \
    /hyperkube kubelet \
        --containerized \
        --hostname-override=127.0.0.1 \
        --api-servers=http://localhost:8080 \
        --config=/etc/kubernetes/manifests \
        --cluster-dns=10.0.0.10 \
        --cluster-domain=cluster.local \
        --allow-privileged --v=2

**Comment by smsahu** [comment]
Issue got fixed after I commented below 2 lines on startup script.
#        --cluster-dns=10.0.0.10 \
#        --cluster-domain=cluster.local \

But can any one let me know why it failed to work with dns without any system changes???

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
