### ISSUE TITLE
Name resolving not working in CNI plugin

### ISSUE THREAD

**Issue by cheld** [kubernetes/kubernetes#27177]
Problem:
The name resolving is not working when cni network plugin is used. 

Steps:
1. setup cni configuration as described: https://github.com/containernetworking/cni
2. run kubelet with cni plugin. define one container in manifest
```
$ sudo ./kubelet --network-plugin="cni" --network-plugin-dir="/etc/cni/net.d" --config=/home/cheld/Downloads/manifest

$ docker exec .... ping www.google.com
ping: unknown host

$ docker exec ... cat /etc/resolv.conf
search xxxx.fujitsu.com
nameserver 127.0.1.1
options ndots:5
```

Remark:
It works when launching with docker-run script:
```
sudo CNI_PATH=$CNI_PATH ./docker-run.sh debian cat /etc/resolv.conf
search xxx.fujitsu.com

nameserver 8.8.8.8
nameserver 8.8.4.4
```

I am using Docker 1.10. According to https://docs.docker.com/engine/userguide/networking/configure-dns/ something changed in 1.10

@freehan

**Comment by cheld** [comment]
Additional remark: network is setup correctly. ping with ip works

CC @zreigz

**Comment by freehan** [comment]
Are you running stand alone kubelet? 
It looks like kubelet pick configure the wrong dns for container. You can try to set your pod's dnsPolicy to Default. See if that helps.

**Comment by cheld** [comment]
Thanks for commenting. I was mistaken. The behavior is not related to CNI network plugin
