### ISSUE TITLE
PVClaim deletion should be graceful wrt running pods

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#27198]
The scheduler knows which pods are on which nodes. It figures out all volumes on a node by the sum of its pods.  It does this to enforce constraints in a cloud environment.

It is possible to delete a PVC while a pod is still running.  The pod will continue to function, the PV remains attached to a node.  

When the scheduler attempts to place new pods on the node, it looks up all its existing PVs and their backing PVCs , except the PVC has been deleted, an error is thrown, and the scheduler fails.

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L157

The user gets an ugly error message about a namespace they don't own. Their pod won't run and the error message is confusing.

@kubernetes/rh-storage @kubernetes/sig-storage

**Comment by childsb** [comment]
Mark, can you provide a recreate scenario for this?

**Comment by markturansky** [comment]
1.  Create a PVC in a cloud environment.
2.  Use it in a pod.  Watch your pod run successfully.
3.  Delete the PVC.  Your pod is still running.
4.  That's it.  All new pods will fail.

**Comment by childsb** [comment]
thanks we'll take a look at this

**Comment by markturansky** [comment]
We diagnosed this because the PVs were in Failed state with the error message ""Deletion error: error deleting EBS volumes: VolumeInUse: Volume vol-9dbdca38 is currently attached to i-0edeb841d8a2d3a77\n\tstatus code: 400, request id: "

We saw the PVC was missing and confirmed the pod using it was still running.

**Comment by markturansky** [comment]
Subsequent pods get an error event like this:

1:52:57 PM	notebook-3-6obzq	Pod	Warning	Failed scheduling 	PersistentVolumeClaim 'testproject/database' is not in cache

**Comment by abhgupta** [comment]
Possible approaches:

1. Continue to other nodes when scheduler returns an error with one node. 
 - since the "broken" PV exists on a particular node, the pod should be able to be successfully scheduled on a different node
 - issue already exists --> https://github.com/kubernetes/kubernetes/issues/22554
2. Prevent the PVC from being deleted by the user
 - we could do this with an admission controller that checks if the PVC is being referenced by a running pod
3. Count the PV for limit calculation purposes resource if the PVC went missing
 - we will falsely over-count some PVs that are not the same "type", but better than option 1 in terms of node utilization

**Comment by abhgupta** [comment]
Had a discussion with @markturansky and @smarterclayton and I am going to submit a PR for option 3 listed in https://github.com/kubernetes/kubernetes/issues/27198#issuecomment-225298492

**Comment by pmorie** [comment]
@abhgupta I'm not sure I get this phrase: Count the PV for limit calculation purposes resource if the PVC went missing

**Comment by abhgupta** [comment]
@pmorie reworded to --> Count the PV for limit calculation purposes if the PVC is deleted (not in the cache)

**Comment by markturansky** [comment]
@abhgupta been thinking, your fix is appropriate and it *doesn't* actually overcount resources.   This happens only when the PV is still attached and in use by a pod, so counting it is correct.

**Comment by abhgupta** [comment]
@markturansky Sure, the PV is still around, but we can't be sure of the "type" (source) of the PV and each type of PV could have their own limits for a node. So, the "overcount" is in counting a PV of one type in the limit calculation of all PVs of a different type.

**Comment by dchen1107** [comment]
Are we sure we want to include a fix in v1.3? This issue has been here for a long time, at least existing for more than one releases.

**Comment by dchen1107** [comment]
cc/ @matchstick

**Comment by childsb** [comment]
from email w/@saad-ali -- "... this is scheduler code--hasn't been touched in a long time so the bug existed for a long time."

**Comment by smarterclayton** [comment]
Up until recently no one has been limiting PVs on AWS or GCE - so
effectively the bug has been here but now people are running realistic
production workloads that exercise it (running > 16 pods with PVs on a host
for GCE).  The failure mode for this bug is particularly severe.

**Comment by DirectXMan12** [comment]
Something to consider for future work: it seems to me that a running pod referencing a deleted PVC is in an invalid state.  Perhaps we should mark or stop the pod somehow?  It seems like this could cause confusion and/or issues in the future.

**Comment by childsb** [comment]
since this is scheduler and not volume/storage assigning to @DirectXMan12

**Comment by DirectXMan12** [comment]
> PVC's should have graceful deletion - the PVC should remain until all pods referencing it are in shutdown, and the kubelet shouldn't allow you to start a pod that has a PVC in graceful termination.

@smarterclayton :+1: I like that idea

**Comment by eparis** [comment]
@smarterclayton or should PVC deletion just be an error entirely if it is is currently in use by a Pod? I think I like your method bettering since:

create PVC; create Pod; delete PVC; delete Pod;    works for you but not for errors on delete

**Comment by DirectXMan12** [comment]
@eparis: I discussed a bit with @pmorie, and he noted that erroring on delete makes the order of deletion important, which could make certain operations more difficult.

**Comment by wojtek-t** [comment]
@davidopp - FYI

**Comment by abhgupta** [comment]
We might want to keep this issue open to discuss the broader issue of graceful PVC deletion.

**Comment by goltermann** [comment]
Should it remain in the v1.3 milestone, or is the 1.3 required work finished?

**Comment by davidopp** [comment]
Not for 1.3

**Comment by thockin** [comment]
FIRST: is this still happening?  The failure mode, as described, is REALLY nasty. 

SECOND: wrt graceful deletion, I think that sounds awesome, but how?  We can set the deletion time on the PVC but who actually will delete it?  Do we need a controller for this?  It's racy...

@pmorie @smarterclayton @jsafrane

**Comment by markturansky** [comment]
@thockin https://github.com/kubernetes/kubernetes/pull/27227 fixed the nastiness.

**Comment by smarterclayton** [comment]
Re: deletion it will eventually have to be the controller that owns
the lock on the PV I assume w.r.t. attach (deletion prereqs on
detach?)

**Comment by thockin** [comment]
I'm going to re-title this to reflect the graceful deletion idea.

This is a tricky one because multiple pods can ref the same PVC and we do not keep back-pointers to them all.  I guess we can:

* set deletion time
* from this point on, kubelet will not start any new pods that use the PVC
* existing pods are existing
* a/the controller periodically scans all pods for references to this PVC
* if none, delete it

This is sort of crappy in that it is poll-loop driven.  Open to ideas, but this is extremely unlikely in 1.4.  Un-milestoning.

**Comment by smarterclayton** [comment]
I think the attach/detach controller has to know all the pods that
reference a PVC anyway?

**Comment by pwittrock** [comment]
@smarterclayton @thockin @markturansky  I am moving this out of the blocking issues we are tracking for the 1.4 release.  If there is still 1.4 work to be done here, move it back and provide daily updates to this issue.

**Comment by saad-ali** [comment]
Moving out of 1.4 milestone

**Comment by jsafrane** [comment]
this is fixed by PVCProtection feature in 1.9
/close
