### ISSUE TITLE
Azure Resource Manager support for E2E Tests

### ISSUE THREAD

**Issue by WeixuZhuang** [kubernetes/kubernetes#27201]
With a PR recently azure E2E support was re-instated in Kubernetes master repository. This is as referenced by the following issue -
https://github.com/kubernetes/kubernetes/pull/21207
The methodology used in the previous commits were the old way of using ASM Apis.

There was a request to support Azure E2E with ARM templates that use the new Azure Resource Manager APIs which are being support long term by Azure.

These set of commits enable ARM Api support for Kubernetes E2E on Azure.
With the ARM changes, Kubernetes Master upstream/origin is tested nightly and results are reported on a federated dashboard here -
https://k8s-testgrid.appspot.com/k8s#azure

**Comment by jdumars** [comment]
Closing this issue as stale.
