### ISSUE TITLE
PR jenkins is unhappy

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#27216]

**Comment by spxtr** [comment]
For the last few hours we've been trying to update a configuration on PR Jenkins. Unfortunately, it gets to the very last post-build step and freezes in the console, despite the logs saying it's finished and successful. Then, Jenkins crashes and we have to reboot the master, which makes everyone else's builds break.

Sorry for the disruption.

**Comment by fejta** [comment]
Please reactive and let me know if you see further problems in PR jenkins.
