### ISSUE TITLE
jenkins job kubernetes-e2e-gke* are completely broken

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#27219]
Both kubernetes-e2e-gke and kubernetes-e2e-gke-slow are broken since 5:00pm. 

Digging into ...

**Comment by jlowdermilk** [comment]
e2e-gke* tests are broken because we missed some config needed by GCI masters to run `v1.3.0-beta.0`. That fix is submitted and rolling out now.

**Comment by dchen1107** [comment]
It turns out both gke* jenkins jobs were broken due to an internal issue which causes the image cannot be found. The issue was fixed, and the image is pushed by @jlowdermilk 

#27144 and #27217 should fix pinned jobs. I revert-revert both prs.

**Comment by dchen1107** [comment]
Finally jenkins job: kubernetes-e2e-gke/8925 picks up the right config and the test cluster is up now!

**Comment by dchen1107** [comment]
cc/ @jlowdermilk I am closing this one for now, but will continue monitoring the builds. :-)
