### ISSUE TITLE
`kubectl get rs` should be ordered better and hide 0 replica ones by default

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#27212]
Right now when you get RS with `kubectl get rs`, they're ordered alphabetically by their name. Since most RS will be created by deployments, it'd be `<deployment-name>-<pod-template-hash>` and the order will be totally random. We should order them better, for example, by number of current replicas, and hide the ones with 0 replicas by default. 

@kubernetes/kubectl @kubernetes/deployment

**Comment by therc** [comment]
I requested something similar for kubernetes-dashboard:

https://github.com/kubernetes/dashboard/issues/817#issuecomment-224580252

It would be nice for both interfaces to sort replicasets the same way, although the interfaces are obviously quite different.

**Comment by bryk** [comment]
We generally aim to make the UI show things the same way as CLI does, so similarity is what we aim for.

**Comment by pwittrock** [comment]
@AdoHe Interested?

**Comment by therc** [comment]
I can do it, since I'm a heavy user of deployments and recently fixed `kubectl get service`.

**Comment by therc** [comment]
Does my idea of 'desiredReplicas > 0` as primary sorting key and recency as secondary sound good?

**Comment by bryk** [comment]
@therc Can you also upstream this to the Dashboard UI? This should be as easy as sorting a list of things in our go backend.

**Comment by janetkuo** [comment]
> I can do it, since I'm a heavy user of deployments and recently fixed kubectl get service.

@therc thanks!

**Comment by therc** [comment]
#27510 is out, but it's kinda ugly...

**Comment by AdoHe** [comment]
@therc I will help you review this one.
