### ISSUE TITLE
rkt: ServiceAccounts should mount an API token into pods [Conformance] failure

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#27228]
This test has started failing under rkt 1.8.0 with the GetLogs API change.

An example failure can be seen in https://console.cloud.google.com/storage/browser/rktnetes-jenkins/logs/kubernetes-e2e-gce/2639/

I'm fairly confident the root cause is https://github.com/coreos/go-systemd/issues/172

cc @yifan-gu (and good work finding that issue :)

**Comment by yifan-gu** [comment]
cc @iaguis @alban @kubernetes/rktnetes-maintainers

**Comment by dchen1107** [comment]
@yifan-gu I am assigning this to you since the issue with p0 and 1.3 milestone at this moment definitely requires an owner. Please triage and re-assign. Thanks!

**Comment by erictune** [comment]
Is rkt support a 1.3 blocker?

**Comment by euank** [comment]
This issue is best resolved by updating the required rkt version.

However, users can avoid this issue without any changes in k8s by just using a newer rkt version than the minimum required one.
Because of that, I think it's okay for this issue to not block v1.3 (though I hope we can cherry-pick in that one line version requirement bump).

**Comment by dchen1107** [comment]
Yes, also this one can be document as known issue for rkt as alternative runtime at: https://github.com/kubernetes/kubernetes/issues/26201

**Comment by euank** [comment]
We can close this since rkt v1.9.1 is released and the tests are happy under rktnetes there. We've already also documented that you should use v1.9.1 and updated the required version I believe.

**Comment by yifan-gu** [comment]
Closing.
