### ISSUE TITLE
IP Networking between K8s deployments - Cassandra and other applications

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#27239]
@paralin has some awesome ideas on a GCE specific setup.  This is a placeholder to document these thoughts.  

 Requirements:
- 2 or more non-federated K8s deployments or possibly K8s Federated
- K8s deployment alpha - petset alpha is deployed
- K8s deployment beta - petset beta is deployed
- petset alpha and beta are applications that must communicate with every Pet ip address in K8s alpha and K8s beta.
- Petsets distributed HA systems that are designed to provide multiple datacenter HA.
- Petsets are distributed systems that provide capability for work load specific uses cases inside of a Datacenter - Data is the same across distributed systems, but Petset alpha 1 is configured differently than Petset alpha 2.  Analytics workloads vs Data ingestion workloads.

Software applications Impacted:
- Cassandra  - P1
- Apache Spark - P1 (master has to talk to all nodes, needs further vetting)
- Elastic (need to vet)
- Redis (may not be a valid use case)

Cassandra Use Case:

Specifically Cassandra instances CANNOT be load balanced.  A client external to cluster must see every Cassandra IP address, and when doing multiple Datacenters between K8s deployments all nodes must talk to each other.  Federated will assist, but since Cassandra provides amazing HA, I almost would recommend to have Cassandra to handle itself.  A SeedProvider and SnitchProvider for Cassandra could utilize muitple K8s endpoints for discovery. 

Cassandra routinely uses IP addresses instead of DNS, and with Petsets ... voila!

Ubernetes Multiple Cassandra Datacenters - every node must be able to talk to every other node. DC1 eight nodes, DC2 eight nodes. All 16 nodes must be able to lookup and talk to each other.
External Clients - For instance the cassandra java driver needs to be able to communicate to every server in a C\* ring. Going through a loadbalancer just does not fit multiple features that C\* clients rely on.

Items Impacted:
- DNS
- IP networking
- Cassandra SeedProvider
- Cassandra Snitch
- Cassandra Racks and Datacenters.

@bgrant0607 who is the networking super guru that can assist.
@mward29 pulling you in because of your aws / Cassandra awesomeness
@bprashanth / @smarterclayton I think PetSet is fully ready for this 😄 

cc @kubernetes/examples - do we have other use cases in apps?

Once this is vetted, I can put in a formal proposal after 1.3 launch ... till then I am SUPER busy

**Comment by paralin** [comment]
I have joining networks over VPN working well and it's a huge priority for me right now to make sure that works. To be clear I'm joining a non kubernetes network and a k8s network such that everyone can see everyone else - you can hit pods from the remote network and the k8s network can hit the remote computers

This would work fine with multiple k8s locations if you set up a different pod CIDR between the two. 

The only thing I can't get working is service routing which I made an issue about.

**Comment by chrislovecnm** [comment]
@paralin you using GCE vpn or vpn pods inside of K8s.  I know there are some significant new capability with 1.2 networking, and I am not a guru to comment.  @bgrant0607 should be able to point us to the right people.

**Comment by chrislovecnm** [comment]
@bprashanth / @smarterclayton any thoughts about specifying a range of ips for a PetSet?  That way we know the ip addresses of pet alpha-0, alpha-1, alpha-2 before we deploy?

**Comment by paralin** [comment]
@chrislovecnm VPN pods inside k8s. I'm not interested in using any cloud-provider specific features, although I am running on GCE. And it would also be wayy more expensive for me to use GCE VPNs, especially with the volume of connections / specific servers I'm running.

**Comment by chrislovecnm** [comment]
@paralin wouldn't it be cool to have a DC in aws, a DC in gce, and a bare metal DC at a datacenter??  I completely agree with you in regards to multiple cloud DC's!

**Comment by chrislovecnm** [comment]
@mward29 is in production on AWS with k8s btw .. and is a C* guru.  That is why I dragged him in over here :)

What are u using for VPN?

**Comment by paralin** [comment]
OpenVPN. I use Babel for route redistribution, and since Babel can't talk over the GCE networks, I use Google Cloud Networking routes to define the IP CIDRs I have behind the VPN. However, in my "remote datacenter" babel gossip works so I have it running on all the nodes. It results in a very robust setup.

**Comment by chrislovecnm** [comment]
What amount of throughput have you tested with? 

The only resource I could find on google quickly on babel gossip is a Chinese site ... Docs on Babel?

**Comment by paralin** [comment]
https://www.irif.univ-paris-diderot.fr/~jch/software/babel/

It's a really well known routing algorithm.

**Comment by paralin** [comment]
See #27161

**Comment by chrislovecnm** [comment]
@paralin craps ... let me close this one .. will copy over comments

**Comment by chrislovecnm** [comment]
Closed becaue of https://github.com/kubernetes/kubernetes/issues/27239

**Comment by paralin** [comment]
Re-open please, this one has a much larger scope than the other issue.

**Comment by lavalamp** [comment]
What is this issue asking for?

**Comment by paralin** [comment]
@lavalamp I think it's intended as a central location for ideas / development direction around ubernetes-like concepts for linking multiple data centers in the networking layer and integrating for example petsets with that

**Comment by smarterclayton** [comment]
@kubernetes/sig-network @kubernetes/sig-cluster-federation

**Comment by kant111** [comment]
I would like headless-service to be accessible through a public DNS so a client external to the cluster can  communicate to the pods directly and be able to do the load balancing themselves.

**Comment by smarterclayton** [comment]
Can you not set up a CNAME and then expose your cluster DNS to the outside.  You'd have to be aware that may leak information about your cluster.

**Comment by kant111** [comment]
I am not sure..how to do that?

**Comment by chrislovecnm** [comment]
@kant111 can you put in another issue and link it to this one?

**Comment by surajpasuparthy** [comment]
@chrislovecnm 
Moving here from another thread.
could you give me an idea about how i can set up this networking ?
So far, i only can think of a tunnel (TLS) between the 2 VMs(2 single node K8S clusters). but that will still forward the handshake only to the svc ip and the Pod IPs are private to the cluster.
As a workaround i am using the "hostNetwork=true" to use the VM's ip to be assigned as the Pod ip. The problem being i am exposing the host network and am limited by just 1 cassandra POD.
Thanks in advance

**Comment by chrislovecnm** [comment]
Closing this issue.  @surajpasuparthy we have a proposal for federation of Stateful Sets and certain technologies such as weave and calico allow for meshing two clusters pod networks together.  Really a sig networking question.
