### ISSUE TITLE
e2e failure: kubernetes-e2e-gce-federation fails consistently with 'yaml: line 17: mapping values are not allowed in this context'

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#27236]
e.g. http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-federation/557/console

This failure started happening consistently between 16:40 and 17:17 PDT on Friday 6/10/16.  Pretty sure it's due to one of my PR's that merged around that time.  I'm going to revert it. 

cc: @madhusudancs @nikhiljindal @mml @colhom @mfanjie FYI

```
17:33:31 attempting to get federation-apiserver loadbalancer hostname (12 / 30)
17:33:32 Found federation-apiserver host at 8.35.192.15
17:33:34 yaml: line 17: mapping values are not allowed in this context
17:33:34 2016/06/10 17:33:34 e2e.go:218: Error running up: exit status 1
17:33:34 2016/06/10 17:33:34 e2e.go:214: Step 'up' finished in 13m59.571595362s
```

**Comment by quinton-hoole** [comment]
I have somewhat inconclusively narrowed the cause of this down to one of three PRs:

Run 556 succeeded:

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-federation/556/

Run 557, and all subsequent runs are failing consistently as above:

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-federation/557/

The PR's that merged between these two are:

1. third time charm for #27144 (@jlowdermilk)
2. revert both commits breaking swagger-check #27218 (@dchen1107)
3. e2e-runner.sh: don't overwrite readonly var #27217 (@jlowdermilk)

I'll try to confirm by reproducing and rolling those back in a local branch.

**Comment by quinton-hoole** [comment]
PS:  It actually makes way more sense for #27158 to cause this failure, but that PR merged 4.5 hours before the failures started to occur, and unless I'm misreading the test logs, many and all test runs including #27158 (including some manual ones by myself), passed with flying colors.

**Comment by colhom** [comment]
@quinton-hoole I believe I've found the cause of the test failures.

```sh
++ gsutil cat gs://kubernetes-release/ci/latest.txt
+ build_version=v1.3.0-beta.0
+ echo 'Using published version ci/v1.3.0-beta.0 (from ci/latest)'
+ fetch_tars_from_gcs ci v1.3.0-beta.0
+ local -r bucket=ci
+ local -r build_version=v1.3.0-beta.0
+ echo 'Pulling binaries from GCS; using server version ci/v1.3.0-beta.0.'
+ gsutil -mq cp gs://kubernetes-release/ci/v1.3.0-beta.0/kubernetes.tar.gz gs://kubernetes-release/ci/v1.3.0-beta.0/kubernetes-test.tar.gz .
Using published version ci/v1.3.0-beta.0 (from ci/latest)
Pulling binaries from GCS; using server version ci/v1.3.0-beta.0.
```

This is from the latest federation-e2e logs. The latest run of federation-build produced this version string:

```sh
 v1.3.0-alpha.5.396_5d8710196be7c5
```

Root cause of error: federation-e2e job is pulling tarballs that weren't build by federation-build.

Pulling in tarballs built by the regular kubernetes build job (not the federated one), would produce the line: 17 yaml error your seeing, as `federated-image.tag` file will not be there.

I think we should just make federation-build and federation-e2e jobs agree that the latest ci build version should be in `gs://kubernetes-release/ci/latest-federation.txt` or something along those lines.

**Comment by colhom** [comment]
@quinton-hoole I've tracked this down and have a fix. https://github.com/kubernetes/test-infra/issues/145

**Comment by nikhiljindal** [comment]
I see that the test is green now, so fine to close this?

**Comment by quinton-hoole** [comment]
Yes, the fix PR merged.  Thanks!  Closing.

**Comment by quinton-hoole** [comment]
We're seeing this again consistently on federation e2e tests.  Not yet sure what the root cause is, but a wild guess would be that we have a regression as per above.

cc: @kubernetes/sig-cluster-federation @kubernetes/sig-testing @colhom @madhusudancs

**Comment by ixdy** [comment]
@quinton-hoole do you have a link showing the failure?
