### ISSUE TITLE
make release-skip-tests dont work with user namespaces.

### ISSUE THREAD

**Issue by mercuriete** [kubernetes/kubernetes#27234]
the isolation and permission that provides user namespaces make imposible to build kubernetes.

steps to reproduce:
1) run your docker daemon with 
        ExecStart=/usr/bin/docker daemon --userns-remap=default -H fd://
2) check your /etc/subuid
    cat subuid
    dockremap:100000:65536
3) check your /etc/subgid
    cat subgid 
    dockremap:100000:65536
4) check you are in docker group
5) clone kubernetes
    git clone ........
6) export KUBERNETES_PROVIDER=libvirt-coreos
7) make release-skip-tests

OUTPUT:

+++ [0611 10:58:55] Placing binaries
mkdir: cannot create directory '/go/src/k8s.io/kubernetes/_output/dockerized/bin/linux': Permission denied
!!! Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:384
  'mkdir -p "${KUBE_OUTPUT_BINPATH}/${platform}"' exited with status 1
Call stack:
  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:384 kube::golang::place_bins(...)
  2: hack/build-cross.sh:36 main(...)
Exiting with status 1
!!! Error in build/../build/common.sh:616
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: build/../build/common.sh:616 kube::build::run_build_command(...)
  2: build/release.sh:33 main(...)
Exiting with status 1
Makefile:158: fallo en las instrucciones para el objetivo 'release-skip-tests'
make: **\* [release-skip-tests] Error 1

proposed solution:

it seems you tried to copy from inside a container to outside and it is imposible because of the file permissions.

it is better to use "docker cp container" from outside because we are in docker group.

Thanks for your work. :smile:

**Comment by mfanjie** [comment]
same problem here, reported by #29247

**Comment by mfanjie** [comment]
the root cause is
https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L597 OS user is set to container, while it actually does not exists in container. introduced by commit: https://github.com/kubernetes/kubernetes/commit/ac75bd11cfd9ca927b38b51e08a55d626e5a3131.
my build can be run by comment this line.

**Comment by thockin** [comment]
We don't really support user-namespaces at all, and as such I have very little context on how Docker has implemented them (I just have not played with it yet).

I am open to ideas on how to solve this.

@jfrazelle for some expertise.  Context: our dockerized tools used to run as root, which left debris on the host-side with owner-root, requiring `sudo make clean`.  Now we always run docker images as the calling user, which means no root-owned leftovers, but now this.

**Comment by mercuriete** [comment]
Thanks for the answer.
I've already tried to fix my problem disabling user-namespaces and of course it works.

I am concern about the debris left by docker when using volumes so i enable this feature in order to fail when a container tries to write files where i dont want to.

I dont have enough experience with docker and kubernetes to propose any solution but it would be good if someone came up with one solution.

Kubernetes is an excelent product. Thanks for your work :smile:

**Comment by jfrazelle** [comment]
seems like if the user configured their docker daemon to use user namespaces, kubernetes should just work... the configurations for username spaces is at the docker daemon level it shouldn't affect how a container is actually run.

**Comment by jfrazelle** [comment]
I can look into the failing script... is this more for _building_ kubernetes on a machine where userns is enabled? or _running_ it. I really believe _running_ it should have no issues. Building is a completely different story. For example you cannot build docker on a machine configured with userns enabled because the container that builds docker is privileged.

**Comment by mercuriete** [comment]
the problem is when i build kubernetes with userns.. with my configuration the process runs with uid = 100000. (and this uid doesn't exist as user in my system)
But the owner of the folder where the kubernetes source is cloned... is me (uid = 1000).
So it is imposible to copy from a container even beeing root because root is mapped to 100000 that doesnt exists.

Maybe is my fault. but in the end... The problem is still there. you can't copy the files out from a container.

Cheers
:)

**Comment by mercuriete** [comment]
mmm maybe i have to put 777 permissions to this folder in order to give access to the container...
I will try it tomorrow.

**Comment by dgonzalez** [comment]
Same problem here and the line commented above (the one that fixes the problem) does not exist anymore.

**Comment by mfanjie** [comment]
I encountered this problem on Mac with docker-machine enabled, it was gone after I update my docker version to latest. You can try as well if you have the same config.

**Comment by dgonzalez** [comment]
I'll try to update docker to the latest version but I already installed it fresh last week... I think the way to go is Linux.
