### ISSUE TITLE
Watching an endpoints throws an error 

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#27248]
the client was 1.2.0 and server was 1.2.4

kc get endpoints shared-e2etest-0-phx --namespace test --watch
NAME                   ENDPOINTS                                                           AGE
shared-e2etest-0-phx   172.16.86.42:8080,172.16.86.43:8080,172.16.86.44:8080 + 3 more...   2d
Error from server: too old resource version: 1416148 (1585264)

**Comment by nhlfr** [comment]
I wasn't able to reproduce this on master - watching an endpoint works well (even with custom namespaces).

**Comment by krmayankk** [comment]
@nhlfr did you try client 1.2.0 with server 1.2.4 ?

**Comment by lavalamp** [comment]
@krmayankk Probably not going to look at this unless you can repro on master or there's a really good reason why that particular version combo needs to do what you want. :) Let me know...

**Comment by krmayankk** [comment]
sure no big reason for me to support those two versions.
