### ISSUE TITLE
Unable to deploy kubernetes on local ubuntu machine (so one node)

### ISSUE THREAD

**Issue by kant111** [kubernetes/kubernetes#27240]
Below is my error trace. I am not sure if the following lines from the error trace below is the reason why I wasn't able to deploy kube-up.sh

**Error: 100: Key not found (/coreos.com) [1]
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}**

---------------------------------------------------------------------------------
ERROR TRACE

 KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
... Starting cluster using provider: ubuntu
... calling verify-prereqs
... calling kube-up
~/kubernetes/cluster/ubuntu ~/kubernetes/cluster
Prepare flannel 0.5.0 release ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0    102      0 --:--:--  0:00:05 --:--:--   138
100 2757k  100 2757k    0     0   194k      0  0:00:14  0:00:14 --:--:--  739k
Prepare etcd 2.2.0 release ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   606    0   606    0     0    101      0 --:--:--  0:00:05 --:--:--   175
100 7183k  100 7183k    0     0   468k      0  0:00:15  0:00:15 --:--:-- 1871k
Prepare kubernetes 1.2.4 release ...
Done! All your binaries locate in kubernetes/cluster/ubuntu/binaries directory
~/kubernetes/cluster

Deploying master and node on machine 192.168.245.244
make-ca-cert.sh                                                                               100% 4028     3.9KB/s   00:00    
easy-rsa.tar.gz                                                                               100%   42KB  42.4KB/s   00:00    
config-default.sh                                                                             100% 5419     5.3KB/s   00:00    
util.sh                                                                                       100%   29KB  28.6KB/s   00:00    
kubelet.conf                                                                                  100%  644     0.6KB/s   00:00    
kube-proxy.conf                                                                               100%  684     0.7KB/s   00:00    
kubelet                                                                                       100% 2158     2.1KB/s   00:00    
kube-proxy                                                                                    100% 2233     2.2KB/s   00:00    
kube-scheduler.conf                                                                           100%  674     0.7KB/s   00:00    
etcd.conf                                                                                     100%  709     0.7KB/s   00:00    
kube-controller-manager.conf                                                                  100%  744     0.7KB/s   00:00    
kube-apiserver.conf                                                                           100%  674     0.7KB/s   00:00    
kube-apiserver                                                                                100% 2358     2.3KB/s   00:00    
kube-scheduler                                                                                100% 2360     2.3KB/s   00:00    
kube-controller-manager                                                                       100% 2672     2.6KB/s   00:00    
etcd                                                                                          100% 2073     2.0KB/s   00:00    
reconfDocker.sh                                                                               100% 2094     2.0KB/s   00:00    
kube-apiserver                                                                                100%   58MB  58.2MB/s   00:00    
kube-scheduler                                                                                100%   42MB  42.0MB/s   00:00    
kube-controller-manager                                                                       100%   52MB  51.8MB/s   00:00    
etcdctl                                                                                       100%   12MB  12.3MB/s   00:00    
etcd                                                                                          100%   14MB  13.8MB/s   00:00    
flanneld                                                                                      100%   11MB  10.8MB/s   00:00    
kubelet                                                                                       100%   60MB  60.3MB/s   00:01    
kube-proxy                                                                                    100%   35MB  34.8MB/s   00:00    
flanneld                                                                                      100%   11MB  10.8MB/s   00:00    
flanneld.conf                                                                                 100%  577     0.6KB/s   00:00    
flanneld                                                                                      100% 2121     2.1KB/s   00:00    
flanneld.conf                                                                                 100%  568     0.6KB/s   00:00    
flanneld                                                                                      100% 2131     2.1KB/s   00:00    
[sudo] password to start master: 
etcd start/running, process 100639
**Error:  100: Key not found (/coreos.com) [1]
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}**
docker stop/waiting
docker start/running, process 101035
Connection to 192.168.245.244 closed.
Validating master
Validating kant@192.168.245.244
Using master 192.168.245.244
cluster "ubuntu" set.
user "ubuntu" set.
context "ubuntu" set.
switched to context "ubuntu".
Wrote config for ubuntu to /home/kant/.kube/config
... calling validate-cluster
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.
Waiting for 1 ready nodes. 0 ready nodes, 0 registered. Retrying.

**Comment by dalanlan** [comment]
Seems flannel failed to rise up, nothing to do with etcd at the first glance.

**Comment by kant111** [comment]
@dalanlan How so I fix it? any idea?

**Comment by dalanlan** [comment]
What does the log of flannel say?

**Comment by kant111** [comment]
where are they located? I am new to all this..

**Comment by Hui-Zhi** [comment]
I think you need to ensure the flannel could connect to etcd first.

**Comment by dalanlan** [comment]
@kant111 `/var/log/upstart/flannel.log`, I guess.

**Comment by kant111** [comment]
@dalanlan Thanks here is the copy of entire /var/log/upstart/flannel.log

I0612 20:29:30.065583 79263 main.go:292] Exiting...
I0612 20:29:51.650654 74619 main.go:275] Installing signal handlers
I0612 20:29:51.651944 74619 main.go:188] Using 192.168.245.237 as external interface
I0612 20:29:51.652257 74619 main.go:189] Using 192.168.245.237 as external endpoint
E0612 20:29:51.661936 74619 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [1]
W0612 20:29:52.664978 74619 device.go:94] "flannel.1" already exists with incompatable configuration: vtep (external) IP: 192.168.245.237 vs 192.168.245.251; recreating device
I0612 20:29:52.708871 74619 etcd.go:204] Picking subnet in range 172.16.1.0 ... 172.16.255.0
I0612 20:29:52.709513 74619 etcd.go:84] Subnet lease acquired: 172.16.25.0/24
I0612 20:29:52.715559 74619 ipmasq.go:50] Adding iptables rule: FLANNEL -d 172.16.0.0/16 -j ACCEPT
I0612 20:29:52.737252 74619 ipmasq.go:50] Adding iptables rule: FLANNEL ! -d 224.0.0.0/4 -j MASQUERADE
I0612 20:29:52.750474 74619 ipmasq.go:50] Adding iptables rule: POSTROUTING -s 172.16.0.0/16 -j FLANNEL
I0612 20:29:52.758219 74619 ipmasq.go:50] Adding iptables rule: POSTROUTING ! -s 172.16.0.0/16 -d 172.16.0.0/16 -j MASQUERADE
I0612 20:29:52.767016 74619 vxlan.go:153] Watching for L3 misses
I0612 20:29:52.767177 74619 vxlan.go:159] Watching for new subnet leases
I0612 20:29:52.785200 74619 vxlan.go:273] Handling initial subnet events
I0612 20:29:52.785533 74619 device.go:159] calling GetL2List() dev.link.Index: 243

**Comment by kant111** [comment]
@dalanlan any idea?

**Comment by dalanlan** [comment]
That's odd. Notice that I don't have any machines available for now to test, hence my best guess is 

1. `E0612 20:29:51.661936 74619 network.go:53] Failed to retrieve network config: 100: Key not found (/coreos.com) [1]`
this is a timing thing, and it's resolved later.

2. It seems that you've already built up a flannel bridge before. Hence there is a conflict configuration. What's `ifconfig flannel.1` give you?

3. check it out whether flannel is working properly and `docker0` bridge is linked to the right setting.

**Comment by lavalamp** [comment]
Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team
