### ISSUE TITLE
Cannot generate protobuf for map[string][]string, blocks authorization from being generated

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#27259]
The proto serialization chosen for `map[string][]string` is incorrect (it treats `[]string` as `string`) which prevents the `authorization` API group from getting protobuf structs due to the `Extra` field.

**Comment by smarterclayton** [comment]
This is fixable with #27258

**Comment by dims** [comment]
@smarterclayton the referenced PR seems merged. What else needs to be done here? (trying to see if i can help)

**Comment by smarterclayton** [comment]
Still needs an individual fix.  []string is not a valid map type for protobuf (to the best of my knowledge).  Will look at this before 1.4.

**Comment by smarterclayton** [comment]
This was fixed.

**Comment by jianzhangbjz** [comment]
@smarterclayton I encounter the same problem #46024  now, how to fix it?

**Comment by jianzhangbjz** [comment]
@smarterclayton Already fixed, sorry for bothering.
