### ISSUE TITLE
the official website docker-mutinode should be more details

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [kubernetes/kubernetes#27251]
In this page http://kubernetes.io/docs/getting-started-guides/docker-multinode/master/, the forum of Setup Docker Bootstrap warm that '**_If you are running this on a long running system, rather than experimenting, you should run the bootstrap Docker instance under something like SysV init, upstart or systemd so that it is restarted across reboots and failures_**.'Expecting to add related links to solve it.

**Comment by lavalamp** [comment]
I can't understand what you're asking for, sorry.
