### ISSUE TITLE
[Feature:PetSet] Basic PetSet functionality should provide basic identity 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#27299]
Eg: http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-petset/116/
Suspect it's because of: https://github.com/kubernetes/kubernetes/issues/27058

**Comment by erictune** [comment]
@bprashanth If this hasn't been seen in 3 months, okay to close?

**Comment by bprashanth** [comment]
Yes we fixed it with https://github.com/kubernetes/kubernetes/issues/27058
