### ISSUE TITLE
multiple pods become stuck in ContainerCreating/Terminating state on single kubelet

### ISSUE THREAD

**Issue by macb** [kubernetes/kubernetes#27306]
We've been encountering increasing number of issues where the `kubelet` seems to be in some sort of hung state while handling processing events (like creating or destroying a pod):

```
$ kubectl get po
NAME                                   READY     STATUS              
appname-2331821309-lgj2o      0/1       ContainerCreating
```

Getting on the `kubelet` where the container is hung, the logs seem to have a lot of transport errors (maybe our `kube-apiserver` crashed or disappeared):

`kubelet.log`:

```
kubelet: E0613 11:01:53.943206   28599 reflector.go:271] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: Get https://kube-apiserver:6443/api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubelet01&resourceVersion=6439574&timeoutSeconds=420: dial tcp 10.0.0.1:6443: connection refused
kubelet: E0613 11:01:53.943276   28599 reflector.go:271] pkg/kubelet/kubelet.go:240: Failed to watch *api.Service: Get https://kube-apiserver:6443/api/v1/watch/services?resourceVersion=6439299&timeoutSeconds=487: dial tcp 10.0.0.1:6443: connection refused
kubelet: E0613 11:01:53.943315   28599 reflector.go:271] pkg/kubelet/kubelet.go:259: Failed to watch *api.Node: Get https://kube-apiserver:6443/api/v1/watch/nodes?fieldSelector=metadata.name%3Dkubelet01&resourceVersion=6468007&timeoutSeconds=505: dial tcp 10.0.0.1:6443: connection refused
kubelet: E0613 11:01:55.640953   28599 reflector.go:271] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: too old resource version: 6439574 (6468022)
kubelet: E0613 11:01:55.667667   28599 reflector.go:271] pkg/kubelet/kubelet.go:240: Failed to watch *api.Service: too old resource version: 6439299 (6468022)
kubelet: E0613 11:01:55.843807   28599 reflector.go:271] pkg/kubelet/kubelet.go:259: Failed to watch *api.Node: too old resource version: 6468007 (6468022)
kubelet: E0613 11:09:54.814446   28599 reflector.go:271] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: too old resource version: 6468023 (6468279)
kubelet: E0613 15:34:56.610783   28599 reflector.go:271] pkg/kubelet/kubelet.go:259: Failed to watch *api.Node: Get https://kube-apiserver:6443/api/v1/watch/nodes?fieldSelector=metadata.name%3Dkubelet01&resourceVersion=6496591&timeoutSeconds=398: dial tcp 10.0.0.1:6443: connection refused
kubelet: E0613 15:34:56.615108   28599 reflector.go:271] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: Get https://kube-apiserver:6443/api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubelet01&resourceVersion=6468845&timeoutSeconds=374: dial tcp 10.0.0.1:6443: connection refused
kubelet: E0613 15:34:56.615166   28599 reflector.go:271] pkg/kubelet/kubelet.go:240: Failed to watch *api.Service: Get https://kube-apiserver:6443/api/v1/watch/services?resourceVersion=6468023&timeoutSeconds=532: dial tcp 10.0.0.1:6443: connection refused
kubelet: E0613 15:34:57.613588   28599 reflector.go:271] pkg/kubelet/kubelet.go:259: Failed to watch *api.Node: Get https://kube-apiserver:6443/api/v1/watch/nodes?fieldSelector=metadata.name%3Dkubelet01&resourceVersion=6496591&timeoutSeconds=405: dial tcp 10.0.0.1:6443: connection refused
kubelet: E0613 15:34:57.617199   28599 reflector.go:271] pkg/kubelet/kubelet.go:240: Failed to watch *api.Service: Get https://kube-apiserver:6443/api/v1/watch/services?resourceVersion=6468023&timeoutSeconds=429: dial tcp 10.0.0.1:6443: connection refused
kubelet: E0613 15:34:57.617255   28599 reflector.go:271] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: Get https://kube-apiserver:6443/api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubelet01&resourceVersion=6468845&timeoutSeconds=526: dial tcp 10.0.0.1:6443: connection refused
kubelet: E0613 15:34:58.786094   28599 reflector.go:271] pkg/kubelet/kubelet.go:259: Failed to watch *api.Node: too old resource version: 6496591 (6496612)
kubelet: E0613 15:34:58.969776   28599 reflector.go:271] pkg/kubelet/kubelet.go:240: Failed to watch *api.Service: too old resource version: 6468023 (6496611)
kubelet: E0613 15:34:59.037563   28599 reflector.go:271] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: too old resource version: 6468845 (6496611)
kubelet: E0613 15:35:00.512631   28599 reflector.go:271] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: too old resource version: 6496612 (6496617)
```

Restarting the `kubelet` process seems to make everything process as expected.

While it's definitely not ideal (the apiserver being unavailable) I would not expect what is a very possible intermittent network failure to result in a completely unresponsive kubelet. Instead I'd expect it to gracefully resolve itself and resume communication with the apiserver or to crash altogether. The latter would be a lot easier from an operators standpoint as at least we would have some idea there is an issue occurring.

Sorry in advance for the sparse information in this issue. I'm happy to provide as much as possible but the issue has been pretty intermittent and the `kubelet` logs don't seem overly helpful.

**Comment by macb** [comment]
After looking more closely at the log, you can see 2 different time stampts 11:01 and 15:34. To my knowledge after the 11:01 everything recovered as expected (we were only notified of a problem after the more recent event).

**Comment by lavalamp** [comment]
(personal note: your kubelet was having problems talking to your apiserver. (see: all the "dial tcp 10.0.0.1:6443: connection refused" messages.) I'd look and see if your apiserver restarted.)

Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by macb** [comment]
Is stackoverflow the place to report bugs as well?

**Comment by macb** [comment]
@lavalamp is this something that can be re-opened as a bug report wrt failure recovery when an api server becomes unavailable? The alternative is opening an additional issue but I didn't want to duplicate it.

**Comment by lavalamp** [comment]
@macb sorry, I triaged a *lot* of issues and didn't give this one enough attention.

**Comment by macb** [comment]
np! I'm impressed with the sheer number of issues you all are able to get through. Much respect for that!

**Comment by mirague** [comment]
Find my cluster in a similar state after upgrading/cycling Nodes. Any new-found pointers?
