### ISSUE TITLE
httpsGet support for livenessProbe health checks

### ISSUE THREAD

**Issue by theothermike** [kubernetes/kubernetes#27304]
Our app only runs on HTTPS since we're wanting to check client certificates.  It would be great if the livenessCheck supported https as well.  Currently using exec and curl.

It would also be handy to have a Certificate Authority check toggle, for dev environments where not using a real Cert

**Comment by lavalamp** [comment]
Consider listening on a separate, non-exposed port for serving your health info.

**Comment by theothermike** [comment]
@lavalamp we may very well do that once we have some more tooling in place.  Still a 'Ready For Business' check on the actual https connection is desirable

**Comment by theothermike** [comment]
scheme: HTTPS worked, closing out
