### ISSUE TITLE
etcd 2: directory cleanup needed after namespace deletion?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#27307]
I came upon a cluster that had had the namespace code thoroughly exercised. No namespaces currently existed, but many had been created and deleted in the past. Its etcd had lots of empty directories under each resource that had held items when those namespaces were alive (secrets, serviceaccounts, pods...). 

Do we need to be doing something to clean these empty directories up? It seems like this etcd was consuming a lot of memory.

**Comment by lavalamp** [comment]
@xiang90 or @hongchaodeng might know the answer to this question.

**Comment by hongchaodeng** [comment]
Right. We should delete them.
It might get tricky for concurrent cases like A checks if dir is empty, B creates, then A deletes it.
What does it look like currently in creating and deleting namespace?

**Comment by lavalamp** [comment]
How much memory does a directory entry take? Does it really sound possible to run out of memory while snapshotting on account of too many empty directories?

**Comment by lavalamp** [comment]
@derekwaynecarr @liggitt @deads2k-- have you guys encountered this? I think you run with more namespaces than we do. But maybe yours are mostly populated?

**Comment by liggitt** [comment]
Yes, we've seen it. c.f. https://github.com/openshift/origin/issues/7032

**Comment by liggitt** [comment]
Approximate memory use we saw from empty dirs: https://github.com/openshift/origin/issues/7032#issuecomment-191352835

**Comment by bgrant0607** [comment]
cc @technosophos

**Comment by derekwaynecarr** [comment]
The patch we debated carrying is here: https://github.com/openshift/origin/pull/7344

Our hope was to just wait to etcd v3 where this would not be a problem.

**Comment by lavalamp** [comment]
@mbohlool can you link to your clean-up script here?

**Comment by mbohlool** [comment]
I needed another PR to run the pod automatically on master.
