### ISSUE TITLE
Kubelet configmap manifest

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#27312]
With kubelet in standalone mode, I can put pods in /etc/kubernetes/manifests and it works ok.
If it references a config map though, and I put the config map in /etc/kubernetes/manifests too, it doesn't work. but if I leave the pod in /etc/kubernetes/manifests and upload the config map through a server, it does work.

It would be nice, for those slowly transitioning from docker-compose to kubelet standalone, but not quite to full blown kubernetes to be able to load config map's via local manifests too.

**Comment by zhouhaibing089** [comment]
The files under `/etc/kubernetes/manifests` could only be pod spec(I believe you will hit this error: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/file.go#L159). if you are given a configmap, how would kubelet know how to process it?

**Comment by kfox1111** [comment]
Yeah. I believe it only is at the moment. Just wondering how hard it would be to make it support configmaps too.

**Comment by zhouhaibing089** [comment]
@kfox1111 

1.  When you are saying standalone mode, I assume there is no apiserver.
2.  If you expect there is a folder, you could put any spec, and update automatically whenever there is a modifications, then I think `kube-addons` is the one you want.(It requires an endpoint for apiserver)
3.  Configmap could be used for more than one pods in different node, so if you would like to use configmap for static pods, what prevents you from using a plain hostPath then?

**Comment by kfox1111** [comment]
Yeah, by standalone mode I mean kubelet with no apiserver.

Nothing is preventing just using a hostPath. I'm doing that now.

Just thinking of the case where users are migrating from not kubernetes to kubernetes in some places and more kuberntes in other places.

For example, I have a full blown k8s on my laptop but only kubelet on some vm's.

For some vm's, we just use kubelet in standalone mode as I've not been able to support full mode yet. But I've been able to successfully argue that the keepalive/autostart features alone in kubelet are enough to justify its use over something like docker-compose.

So I'm in the position of being able to write pods nicely with configmaps on my laptop but not be able to deploy them as simply on kubelet standalone nodes. (rewrites required)

Things like git backed volumes work, but configmap backed volumes don't. I could also fake it with git backed volumes instead of hostPath volumes.

Its kind of nice to be able to tell a user, "yum install kubernetes-node; systemctl start kubelet;' and here, untar this tarball into /etc/kubernetes/manifests to get a test system up and going.

I could include hostPath bits in the tarball and say, extract this in '/' but thats a little scarier.

With configmap in manifests, you can also say, if you have a full blown k8s, you can load all of the stuff in the tarball with kubectl create but you have to have separate templates if you use hostPath.

This is not a critical feature in any way. just a thought on how things could be polished a bit to make transitioning easier.

Stand alone mode in kubernetes has been a huge selling point to us here, as it has allowed us to take baby steps towards k8s and get comfortable with it before going all in and rewriting everything in it before we're ready.
