### ISSUE TITLE
cluster/ubuntu scripts are not ready for Xenial

### ISSUE THREAD

**Issue by cityofships** [kubernetes/kubernetes#27339]
Maybe more like a feature request but currently this method of k8s deployment only supports Trusty and is completely systemd unaware. Is this going to change in the near future?

**Comment by resouer** [comment]
@lavalamp  Wrong label? This should be cluster-lifecycle or os/ubuntu I think. 

@cityofships This is in TODO list but seems no one is working on that.

**Comment by lavalamp** [comment]
Yeah, this stuff doesn't categorize cleanly into one of our team labels.

**Comment by chuckbutler** [comment]
Just wanted to follow up on this, that this PR is fully addressed in #40324 and once that lands this should be safe to close out. As we've moved to xenial by default and the charms are fully systemd aware. We've dropped support for legacy init systems like upstart.

Thanks for filing this report!

**Comment by roberthbailey** [comment]
Support for ubuntu in kube-up was removed in #44344 so I'm going to mark this as obsolete.
