### ISSUE TITLE
RBAC unusable due to oversight in validation code

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#27337]
`clusterRoleBinding.subject[].apiVersion` is required, but no value is accepted by validation code for `kind: user` or `kind: group`.

**Comment by erictune** [comment]
This makes the entire feature unusable, so setting the priority to P0.

**Comment by erictune** [comment]
Fix in #26984 thanks to @ericchiang

**Comment by erictune** [comment]
fixed by #26984

**Comment by ericchiang** [comment]
@erictune should we close this now that #26984 is merged?
