### ISSUE TITLE
the hyperkube dockerfile error

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [kubernetes/kubernetes#27348]
when use the /kubernetes/cluster/image/hyperkube/dockerfile, a error occurs:
```
Sending build context to Docker daemon 22.53 kB
Step 1 : FROM BASEIMAGE
Error parsing reference: "BASEIMAGE" is not a valid repository/tag
```

**Comment by lavalamp** [comment]
Please read the README in that directory. Use the Makefile. https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/README.md
