### ISSUE TITLE
`kubectl get cs` problem with secured etcd2

### ISSUE THREAD

**Issue by win-t** [kubernetes/kubernetes#27343]
i am trying to setup simple kubernetes cluster, with 3 master, each master running etcd2 instance in HTTPS mode. But when i run `kubectl get cs` i got:

```
etcd-2               Unhealthy   Get http://c.master.kubeinternal:2379/health: malformed HTTP response "\x15\x03\x01\x00\x02\x02"   
etcd-1               Unhealthy   Get http://b.master.kubeinternal:2379/health: malformed HTTP response "\x15\x03\x01\x00\x02\x02"   
etcd-0               Unhealthy   Get http://a.master.kubeinternal:2379/health: malformed HTTP response "\x15\x03\x01\x00\x02\x02"   
```

i already have specified

```
--etcd-cafile=/etc/kubernetes/ssl/cert-ca.pem
--etcd-certfile=/etc/kubernetes/ssl/cert-master.pem
--etcd-keyfile=/etc/kubernetes/ssl/key-master.pem
--etcd-servers=https://a.master.kubeinternal:2379,https://b.master.kubeinternal:2379,https://c.master.kubeinternal:2379
```

in apiserver command line, but it seem doesn't work.

btw, this is output from `etcdctl cluster-health`

```
member 522d6830c147a014 is healthy: got healthy result from https://c.master.kubeinternal:2379
member 5c228a4de15dee8f is healthy: got healthy result from https://b.master.kubeinternal:2379
member fbb23dfd5f0a4b59 is healthy: got healthy result from https://a.master.kubeinternal:2379
```

**Comment by zhouhaibing089** [comment]
@win-t which version are you using? I believe it should be fixed with https://github.com/kubernetes/kubernetes/pull/23903

**Comment by win-t** [comment]
@zhouhaibing089 hyperkube v1.2.4 from quay.io,
hmm, so that patch was not applied in v1.2.4.
thanks, i will recompile the binary then

**Comment by win-t** [comment]
i think i will close it after i try it

**Comment by win-t** [comment]
oke, it is done, thanks @zhouhaibing089

**Comment by win-t** [comment]
After i enabled `--client-cert-auth` on my etcd cluster, i got another error

    etcd-0               Unhealthy   Get https://a.master.kubeinternal:2379/health: remote error: bad certificate                   
    etcd-1               Unhealthy   Get https://b.master.kubeinternal:2379/health: remote error: bad certificate                   
   etcd-2               Unhealthy   Get https://c.master.kubeinternal:2379/health: remote error: bad certificate 

i look like when apiserver check etcd cluster, it is not using `--etcd-certfile` and `--etcd-keyfile` at all

**Comment by mrl045** [comment]
+1

**Comment by zhouhaibing089** [comment]
@win-t Sadly, it is not configurable with certificate data.

1.  There is no field to set. https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/validator.go#L39-L45
2.  The tls configuration hardcoded. https://github.com/kubernetes/kubernetes/blob/master/pkg/probe/http/http.go#L33-L37

**Comment by win-t** [comment]
oh, I see, 
because of default HTTPProber https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/componentstatus/rest.go#L39, 
but, i can say that etcd is not same as other component, it is not created/maintained by kubernetes project, so, i thinks it is ok to create custom HTTPProber.
we can create some condition around https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/componentstatus/rest.go#L98, check if `name` is prefixed with `etcd-` then use custom http probber instead of default one.

**Comment by pawankkamboj** [comment]
seems still not fixed, I am using "gcr.io/google_containers/kube-apiserver-amd64:v1.4.6" and still getting bad certificate for etcd health.

[root@kube1 ~]# kubectl get cs
NAME                 STATUS      MESSAGE                                                              ERROR
scheduler            Healthy     ok                                                                   
controller-manager   Healthy     ok                                                                   
etcd-1               Unhealthy   Get https://172.16.7.12:2379/health: remote error: bad certificate   
etcd-0               Unhealthy   Get https://172.16.7.11:2379/health: remote error: bad certificate   
etcd-2               Unhealthy   Get https://172.16.7.13:2379/health: remote error: bad certificate  

[root@kube1 ~]# etcdctl  -cert-file=/etc/kubernetes/pki/etcd.pem --ca-file=/etc/kubernetes/pki/ca.pem --key-file=/etc/kubernetes/pki/etcd-key.pem   member list
3a24731bbbb50806: name=kube2 peerURLs=https://172.16.7.12:2380 clientURLs=https://172.16.7.12:2379 isLeader=false
7b8f6804a483e938: name=kube1 peerURLs=https://172.16.7.11:2380 clientURLs=https://172.16.7.11:2379 isLeader=true
812af6000899ab40: name=kube3 peerURLs=https://172.16.7.13:2380 clientURLs=https://172.16.7.13:2379 isLeader=false

[root@kube1 ~]# etcdctl  -cert-file=/etc/kubernetes/pki/etcd.pem --ca-file=/etc/kubernetes/pki/ca.pem --key-file=/etc/kubernetes/pki/etcd-key.pem  cluster-health
member 3a24731bbbb50806 is healthy: got healthy result from https://172.16.7.12:2379
member 7b8f6804a483e938 is healthy: got healthy result from https://172.16.7.11:2379
member 812af6000899ab40 is healthy: got healthy result from https://172.16.7.13:2379
cluster is healthy
[root@kube1 ~]#

**Comment by pawankkamboj** [comment]
Not yet, have tried on 1.5.1 and still same.

**Comment by Overbryd** [comment]
@zhouhaibing089 same here. Running `v1.5.1+coreos.0` @ `cc65f5321f9230bf9a3fa171155c1213d6e3480e`

```console
$ kubectl get cs
NAME                 STATUS      MESSAGE                                                                                              ERROR
controller-manager   Healthy     ok                                                                                                   
scheduler            Healthy     ok                                                                                                   
etcd-2               Unhealthy   Get https://ip-10-0-0-6.eu-west-1.compute.internal:2379/health: remote error: tls: bad certificate   
etcd-0               Unhealthy   Get https://ip-10-0-0-4.eu-west-1.compute.internal:2379/health: remote error: tls: bad certificate   
etcd-1               Unhealthy   Get https://ip-10-0-0-5.eu-west-1.compute.internal:2379/health: remote error: tls: bad certificate   
```

**Comment by zhouhaibing089** [comment]
gonna try to reproduce this in my own environment, and fix it if possible.

**Comment by zhouhaibing089** [comment]
Reproduced:

```console
$ ps aux | grep etcd
root      7800  336  0.1 495156 37148 pts/0    Rl   14:54   4:25 etcd -bind-addr=0.0.0.0:2379 --ca-file=/etc/etcd/pki/cert.pem --cert-file=/etc/etcd/pki/cert.pem --key-file=/etc/etcd/pki/key.pem --client-cert-auth=true
root      7838 76.0  2.0 548600 495580 pts/0   Sl   14:54   1:00 /usr/local/bin/kube-apiserver --etcd-servers=https://${masterfqdn}:2379 --etcd-cafile=/etc/etcd/pki/cert.pem --etcd-certfile=/etc/kubernetes/pki/etcd/cert.pem --etcd-keyfile=/etc/kubernetes/pki/etcd/key.pem --insecure-bind-address=0.0.0.0 --admission-control=LimitRanger,ServiceAccount,ResourceQuota --authorization-mode=ABAC --runtime-config=api/v1,extensions/v1beta1,extensions/v1beta1/podsecuritypolicy,extensions/v1beta1/thirdpartyresources --service-cluster-ip-range=192.168.0.0/16 --service-account-key-file=/etc/ssl/kubernetes/serviceaccount.key --experimental-keystone-url=https://os-identity.vip.ebayc3.com:5443/v2.0 --authorization_policy_file=/etc/sysconfig/abac.json --tls-cert-file=/var/run/kubernetes/apiserver.crt --tls-private-key-file=/var/run/kubernetes/apiserver.key --v=10
$ kubectl get cs
NAME                 STATUS      MESSAGE                                                                                   ERROR
scheduler            Healthy     ok
controller-manager   Healthy     ok
etcd-0               Unhealthy   Get https://${masterfqdn}:2379/health: remote error: bad certificate
```

**Comment by billyteves** [comment]
same as above. I also encountered the issue of bad certificate:
`NAME                 STATUS      MESSAGE                                                                                                ERROR
controller-manager   Healthy     ok                                                                                                     
scheduler            Healthy     ok                                                                                                     
etcd-0               Unhealthy   Get https://<ip>:2379/health: remote error: tls: bad certificate `

**Comment by billyteves** [comment]
same as above.
`etcd-0                        Unhealthy   Get https://ip-here:2379/health: remote error: tls: bad certificate `

**Comment by zhouhaibing089** [comment]
Fixes is submitted at https://github.com/kubernetes/kubernetes/pull/39716.

**Comment by billyteves** [comment]
Hi, issue still occurs in 0.9.3, i think changes still not merged?
