### ISSUE TITLE
Error scheduling: No suitable offers for pod/task

### ISSUE THREAD

**Issue by pangbingqiang** [kubernetes/kubernetes#27355]
I run k8s in mesos, when i use ''kubectl' to creat a pod ,my yaml is as follow:

> apiVersion: v1
> kind: Pod
> metadata:
>   name: hello-world
> spec:
>   restartPolicy: Never
>   containers:
>     name: hello
>     image: "ubuntu:14.04"
>     command: ["/bin/echo","hello world"]
>     imagePullPolicy: IfNotPresent

it can't success ,error log is as follow:
`I0614 19:37:53.741166   11035 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"hello-world", UID:"32ea6371-3224-11e6-bed4-90e2ba857fb8", APIVersion:"v1", ResourceVersion:"107", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' Error scheduling: No suitable offers for pod/task`

**Comment by pangbingqiang** [comment]
I can see kubernets framework run success in mesos, but when i create a pod it will not success,the offer will not suitable

**Comment by jlowdermilk** [comment]
Please post your question to  [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We use github issues to track bugs and feature request/proposals. Help/support questions will be responded to much faster on stackoverflow, and you may find answers/solutions to a similar issue that will work for you. The Kubernetes team regularly scans stackoverflow and will try to ensure questions don't go unanswered. Thanks.
