### ISSUE TITLE
Error scheduling: No suitable offers for pod/task

### ISSUE THREAD

**Issue by pangbingqiang** [kubernetes/kubernetes#27354]
I run k8s in mesos, when i use ''kubectl' to creat a pod ,my yaml is as follow:
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: Never
  containers:
    name: hello
    image: "ubuntu:14.04"
    command: ["/bin/echo","hello world"]
    imagePullPolicy: IfNotPresent
  it can't success ,error log is as follow:
`I0614 19:37:53.741166   11035 event.go:216] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"hello-world", UID:"32ea6371-3224-11e6-bed4-90e2ba857fb8", APIVersion:"v1", ResourceVersion:"107", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' Error scheduling: No suitable offers for pod/task`

**Comment by dchen1107** [comment]
dup of #27355
