### ISSUE TITLE
AWS in-place restore/upgrade fails to adopt existing ELBs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#27363]
When we do a upgrade/restore with no matching subnets, we get the following error:

```
I0614 14:42:34.452211       6 aws_loadbalancer.go:81] Detaching load balancer from removed subnets
E0614 14:42:34.459697       6 servicecontroller.go:196] Failed to process service delta. Retrying in 1m20s: Failed to create load balancer for service default/guestbook: error detaching AWS loadbalancer from subnets: InvalidConfigurationRequest: Requested configuration change for LoadBalancer "a5047cedf323c11e6b74902fb69f76aa" is invalid because you attempted to detach all the subnets for this LoadBalancer and a LoadBalancer cannot be attached to zero subnets in VPC.
        status code: 409, request id: 3b3ca506-323e-11e6-93ba-3322bb22fd8e
```

**Comment by justinsb** [comment]
There's a pretty painful ELB restriction; we can't remove a subnet if there's only one, and we can't add a subnet if it's in the same zone.  Checkmate.  Workaround will likely be to encourage multizone on AWS (at least for the nodes).

Even with manually adding another subnet in another zone, hit this error during the reconciliation loop:

```
E0614 19:16:50.329013       6 servicecontroller.go:196] Failed to process service delta. Retrying in 5m0s: Failed to create load balancer for service default/guestbook: error attaching AWS loadbalancer to subnets: SubnetNotFound: The subnet ID '' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidSubnetID.NotFound; Request ID: 090e55c7-56f4-4f5b-b830-859309cb29c2)
        status code: 400, request id: 8b993290-3264-11e6-b6d6-576921d79f9d
```

**Comment by davidopp** [comment]
@justinsb Do you think this is a release blocker? If so, do you think you can do a fix by (say) Monday?

**Comment by erictune** [comment]
I am marking this documentation on the assumption we are going to report this as a known issue for 1.3.0.

**Comment by justinsb** [comment]
OK!  I actually plan on getting to this - I think it might be fixed already in fact, just need to verify.  If not, we can treat as a docs issue presuming it is not more serious.

**Comment by goltermann** [comment]
This is an issue marked v1.3 and kind/documentation.  Can you get it fixed up this week?

**Comment by chezbut** [comment]
still having this issue on 1.7

**Comment by dmytroleonenko** [comment]
same on 1.6

**Comment by vendrov** [comment]
This issue is still reproduced on 1.8
