### ISSUE TITLE
Post submit builds should not silently succeed if binary is wrong version

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#27367]
...I don't think this needs explanation. This just happened to us when we cut the 1.3 branch and it took days before we noticed.

**Comment by ixdy** [comment]
what does "wrong version" mean?

**Comment by fejta** [comment]
Please assign back once the question is answered

**Comment by lavalamp** [comment]
When we cut the 1.3 branch, all of our testing at head started testing 1.3 binaries instead of binaries built at head due to a configuration error. I filed this so we would not silently test the wrong binary. I can dig up the old email thread if that's not clear enough.

**Comment by ixdy** [comment]
The old email thread would be helpful. Right now there's still not enough context to know what should actually be done to prevent this.

Put another way: our non-release-builds [use `ci/latest`](https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/e2e-runner.sh#L290). The release builds use `ci/latest-$VERSION`. I don't know what went wrong with 1.3 where this did the wrong thing.

**Comment by ixdy** [comment]
Closing because I still don't understand what this issue is requesting.
