### ISSUE TITLE
Recreate deployments dont wait for pod termination

### ISSUE THREAD

**Issue by chbatey** [kubernetes/kubernetes#27362]
The scenario is a single replica with an attached EBS. 

The create seems to happen right after the delete not waiting for the pod to be terminated. This results in the two kubelets fighting over the EBS which generally results in AWS becoming unhappy meaning the EBS has to be force detached.

From the docs `All existing Pods are killed before new ones are created when .spec.strategy.type==Recreate` I would have thought deployments would wait until the pod is actually killed.

Is this a bug or am i misinterpreting the docs?

**Comment by kargakis** [comment]
@kubernetes/deployment

**Comment by pwittrock** [comment]
@chbatey As a work around, what happens if you use a rolling update with MaxSurge=0 and MaxUnavailable=1?

**Comment by pwittrock** [comment]
@janetkuo Just assigned for triage, not to fix the issue.  Can clear your assignment once this is triaged.

**Comment by kargakis** [comment]
> @chbatey As a work around, what happens if you use a rolling update with MaxSurge=0 and MaxUnavailable=1?

Deployments with size of 1 should be the same (both in that it's really a Recreate and it has the same problem even though it only matters for Recreate), larger deployments should be rolling.

**Comment by janetkuo** [comment]
It's because `Recreate` Deployment scales old RS down to 0 (`.spec.replicas`=0, and RS controller will observe this change later and then kill its pods) and then scales up the new one. So it's possible there's a race here.

**Comment by kargakis** [comment]
Opened #27713 that partially fixes this.

**Comment by ChipmunkV** [comment]
Why it's closed?

It's not fixed: Recreate still doesn't wait for termination.

**Comment by kargakis** [comment]
@ChipmunkV what version are you using?

**Comment by ChipmunkV** [comment]
@kargakis, 1.6.2-00 from deb package.

I'm changing the Deployment to use different configmap. K8s recreates pod, but the new one can't listen on ports that are probably used by the old one (using `hostNetwork`). Both are appearing in `kubectl get all` at the same time (old one is 'Terminating').

**Comment by kargakis** [comment]
This regressed in 1.6 but was fixed again in https://github.com/kubernetes/kubernetes/pull/43963. I don't think it was cherry-picked back to 1.6 though and the cherry-pick is not clean. @ChipmunkV are you interested in backporting it to the release-1.6 branch?

**Comment by ChipmunkV** [comment]
@kargakis, the cherry-pick isn't clean mostly because of comments.

Don't have time to actually build and test the PR though.

**Comment by woqer** [comment]
We are having this issue too. After deploying a change we have to manually `kubectl delete pod foo` to actually force the recreation.

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-04T07:48:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by kargakis** [comment]
@rcoh I cannot reproduce it anymore, can you provide a reproducer?

**Comment by rcoh** [comment]
Not easily at the moment -- we ended up changing our pods to handle multiple running simultaneously gracefully.

**Comment by imduffy15** [comment]
Hi All,

I'm still seeing this on the following version:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

I am using recreate and can see my current pod go into a terminating state and my new pod come up. It is my understanding that the new pod should not come up until the old pod is terminated completely.

**Comment by seanturner83** [comment]
Seeing this on 1.14.3 too - AWS hardware went bad and stuff was in terminating (but still running) and our stateful singleton was brought back up alongside

**Comment by khuongdp** [comment]
We see the same problem with 1.14.3 where the old pod is Terminating and the new pod is in ContainerCreating even if we set the strategy.type==recreate. Got problem with Volume is already used by pod(s)...

**Comment by InfinityGone** [comment]
@kargakis The easiest way I've found to reproduce this is by using bash interactively - it swallows SIGTERM giving a bigger window to observe the behavior.

One thing to note, the behavior is different with an explicit delete and one caused by a changing annotation. When changing an annotation, the new pod won't be scheduled until the old one is completely gone, but an explicit delete will create the new pod right away. That said, I don't know how it will behave with other events, say a node going away or being drained.

Here is a way to reproduce it. Delete the pod (`kubectl delete pod -l name=recreate`) and watch the new one spin up right away.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recreate
spec:
  replicas: 1
  selector:
    matchLabels:
        name: recreate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: recreate
      annotations:
        foo: bar
    spec:
      containers:
      - name: recreate
        image: "centos:7"
        command: ["bash"]
        stdin: true
        tty: true
```

**Comment by kargakis** [comment]
@seanturner83 @InfinityGone recreate deployments wait for the termination of an old version **only** during a deployment upgrade. The deployment api has been designed with availability in mind and cannot ensure consistency during node upgrades (use PDBs), unexpected node shutdowns, or any other reason that could cause a pod to be recreated (apart from deployment upgrades). If your application has a hard requirement on consistency (eg. database), use [statefulsets](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/).

@imduffy15 @khuongdp can you please provide a reproducer? Thanks.

**Comment by ylhyh** [comment]
Same issue here with version v1.17.6:

Deployment with "Recreate" strategy:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: root-manager-g2117
  name: root-manager-g2117
  namespace: g2117
spec:
    replicas: 1
    selector:
    matchLabels:
      app: root-manager-g2117
  strategy:
    type: Recreate
  template:
...
```

If I try to delete a pod, the old pod is still Terminating, the new pod has already get initialized and Running:
```shell
root@master01 g2117 10:50:31 # kubectl get pods -n g2117 -o wide
NAME                                 READY   STATUS        RESTARTS   AGE   IP              NODE       NOMINATED NODE   READINESS GATES
root-manager-g2117-f69d44c54-4vxrf   1/1     Terminating   0          17m   10.112.11.225   node0008   <none>           <none>
root-manager-g2117-f69d44c54-dtvc2   0/1     Init:0/1      0          8s    <none>          node0008   <none>           <none>

root@master01 g2117 10:55:28 # kubectl get pods -n g2117 -o wide
NAME                                 READY   STATUS        RESTARTS   AGE   IP              NODE       NOMINATED NODE   READINESS GATES
root-manager-g2117-f69d44c54-4vxrf   1/1     Terminating   0          18m   10.112.11.225   node0008   <none>           <none>
root-manager-g2117-f69d44c54-dtvc2   1/1     Running       0          66s   10.112.11.208   node0008   <none>           <none>
```

**Comment by kargakis** [comment]
@ylhyh see the comment right above you

"recreate deployments wait for the termination of an old version only during a deployment upgrade. The deployment api has been designed with availability in mind and cannot ensure consistency during node upgrades (use PDBs), unexpected node shutdowns, or any other reason that could cause a pod to be recreated (apart from deployment upgrades). If your application has a hard requirement on consistency (eg. database), use statefulsets."
