### ISSUE TITLE
Pushing public images of federation control plane on every release

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#27382]
Right now, to start federation control plane, users first need to build and push the images (for federation-apiserver, federation-controller-manager) into a repository that their cluster can access.

We can eliminate this step by providing public images.
We can generate and push these images as part of our general release process.
Some of our tests (that are not testing the control plane binaries, but for ex: some related scripts) can also use these images instead of having to build and push images each time.

cc @kubernetes/sig-cluster-federation @colhom

**Comment by nikhiljindal** [comment]
cc @lavalamp @kubernetes/release-maintainers 

@david-mcmahon Do you know if we push public kubernetes images as part of our release?

**Comment by nikhiljindal** [comment]
cc @zmerlynn since he did a lot of release tooling

**Comment by david-mcmahon** [comment]
I believe you just want to add your binaries to the list [here](https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L1508).

**Comment by nikhiljindal** [comment]
Thanks a lot @david-mcmahon!
Sent https://github.com/kubernetes/kubernetes/pull/27396

**Comment by davidopp** [comment]
@david-mcmahon you added LGTM label to this, but it's an issue.

**Comment by david-mcmahon** [comment]
Indeed.  Removed.

**Comment by goltermann** [comment]
@nikhiljindal what work remains before closing this issue?

**Comment by nikhiljindal** [comment]
The PR is now merged: https://github.com/kubernetes/kubernetes/pull/27396. Closing.

**Comment by nikhiljindal** [comment]
Verified that we recently built `v1.3.0-beta.2` with https://github.com/kubernetes/kubernetes/pull/27396 and we pushed the relevant binaries as expected

```
$ docker search gcr.io/google_containers/federation
NAME                                                      DESCRIPTION   STARS     OFFICIAL   AUTOMATED
google_containers/federation-apiserver-amd64                            0                    
google_containers/federation-apiserver-arm                              0                    
google_containers/federation-apiserver-arm64                            0                    
google_containers/federation-apiserver-ppc64le                          0                    
google_containers/federation-apiserver                                  0                    
google_containers/federation-controller-manager-amd64                   0                    
google_containers/federation-controller-manager-arm                     0                    
google_containers/federation-controller-manager-arm64                   0                    
google_containers/federation-controller-manager-ppc64le                 0                    
google_containers/federation-controller-manager                         0
```
