### ISSUE TITLE
Containers failing to start running density up to capacity

### ISSUE THREAD

**Issue by rrati** [kubernetes/kubernetes#27388]
Using the density test to run max-capacity pods on kubelets, containers get reported as failing to start by the kubelet.  I usually see between 1-5 containers reported they fail to start.

Additionally there appears to be a timeout in the streamwatcher on the apiserver (where the e2e.test is being run)

Density test errors:
...
Jun 14 14:37:31.254: INFO: Density Pods: 160 out of 160 created, 0 running, 160 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:37:41.254: INFO: Density Pods: 160 out of 160 created, 0 running, 160 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:37:51.255: INFO: Density Pods: 160 out of 160 created, 0 running, 160 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:38:01.254: INFO: Density Pods: 160 out of 160 created, 0 running, 160 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:38:11.254: INFO: Density Pods: 160 out of 160 created, 0 running, 160 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:38:21.255: INFO: Density Pods: 160 out of 160 created, 0 running, 160 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:38:31.254: INFO: Density Pods: 160 out of 160 created, 0 running, 160 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:38:41.255: INFO: Density Pods: 160 out of 160 created, 0 running, 160 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:38:51.255: INFO: Density Pods: 160 out of 160 created, 0 running, 160 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:39:01.255: INFO: Density Pods: 160 out of 160 created, 0 running, 160 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:39:11.255: INFO: Density Pods: 160 out of 160 created, 12 running, 148 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:39:21.255: INFO: Density Pods: 160 out of 160 created, 13 running, 147 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:39:31.256: INFO: Density Pods: 160 out of 160 created, 14 running, 146 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:39:41.254: INFO: Density Pods: 160 out of 160 created, 15 running, 145 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:39:51.254: INFO: Density Pods: 160 out of 160 created, 16 running, 144 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:40:01.255: INFO: Density Pods: 160 out of 160 created, 19 running, 141 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:40:11.255: INFO: Density Pods: 160 out of 160 created, 21 running, 139 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:40:21.255: INFO: Density Pods: 160 out of 160 created, 21 running, 139 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:40:31.254: INFO: Density Pods: 160 out of 160 created, 22 running, 138 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:40:41.255: INFO: Density Pods: 160 out of 160 created, 23 running, 137 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:40:51.255: INFO: Density Pods: 160 out of 160 created, 23 running, 137 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:41:01.254: INFO: Density Pods: 160 out of 160 created, 23 running, 137 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:41:11.255: INFO: Density Pods: 160 out of 160 created, 23 running, 137 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:41:21.254: INFO: Density Pods: 160 out of 160 created, 23 running, 137 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:41:31.255: INFO: Density Pods: 160 out of 160 created, 25 running, 135 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:41:41.254: INFO: Density Pods: 160 out of 160 created, 30 running, 130 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:41:51.255: INFO: Density Pods: 160 out of 160 created, 31 running, 129 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:42:01.255: INFO: Density Pods: 160 out of 160 created, 32 running, 128 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:42:11.254: INFO: Density Pods: 160 out of 160 created, 33 running, 127 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:42:21.254: INFO: Density Pods: 160 out of 160 created, 37 running, 123 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
E0614 14:42:21.259895   20078 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0614 14:42:21.260096   20078 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0614 14:42:21.265931   20078 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0614 14:42:21.289515   20078 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
Jun 14 14:42:31.255: INFO: Density Pods: 160 out of 160 created, 40 running, 120 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:42:41.256: INFO: Density Pods: 160 out of 160 created, 41 running, 119 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:42:51.254: INFO: Density Pods: 160 out of 160 created, 45 running, 115 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:43:01.255: INFO: Density Pods: 160 out of 160 created, 48 running, 112 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:43:11.254: INFO: Density Pods: 160 out of 160 created, 52 running, 108 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:43:21.256: INFO: Density Pods: 160 out of 160 created, 54 running, 106 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:43:31.254: INFO: Density Pods: 160 out of 160 created, 57 running, 103 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 14 14:43:41.254: INFO: Density Pods: 160 out of 160 created, 59 running, 101 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
...
Jun 14 14:43:50.848: INFO: Unexpected error occurred: 2 containers failed which is more than allowed 0
panic: 
Your test failed.
...

At the time of the test failure, kubelet showed:
$ docker ps | grep -v CONTAINER | wc -l
314

In the kubelet logs I see:
...
Jun 13 15:23:50 kubelet-v1.3.novalocal kubelet[11378]: E0613 15:23:50.234387   11378 manager.go:1981] Failed to create pod infra container: RunContainerError; Skipping pod "density160-0-044d88ec-319c-11e6-b728-fa163e626a22-zoanl_e2e-tests-density-bhx9a(07581d94-319c-11e6-a101-fa163e626a22)"
Jun 13 15:23:50 kubelet-v1.3.novalocal kubelet[11378]: E0613 15:23:50.234553   11378 pod_workers.go:183] Error syncing pod 07581d94-319c-11e6-a101-fa163e626a22, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: operation timeout: context deadline exceeded"
...

**Comment by rrati** [comment]
I also ran a separate test for docker running up to 250 containers and docker ps rarely took over 1s to respond.

**Comment by wojtek-t** [comment]
Which is expected, because we officially don't support more than 100 pods/node now...

**Comment by wojtek-t** [comment]
And thus we also don't test that.

**Comment by rrati** [comment]
This isn't really 250 pods/node.  It's --max-pods=250 but also pods-per-core=10 and running on a 16 core vm, so in reality it's testing 160 pods on this node.

**Comment by wojtek-t** [comment]
Which is still more than we officially support and test.

**Comment by yujuhong** [comment]
`context deadline exceeded" suggest that kubelet can't start containers within two minutes. Could you bump the [default timeout](https://github.com/kubernetes/kubernetes/blob/49c8683c24fad4f7e182d979a3bba606cad20f21/pkg/kubelet/dockertools/kube_docker_client.go#L60) to see if it helps? We should try to rate limit docker operations to avoid cases like this.

**Comment by timothysc** [comment]
> We should try to rate limit docker operations to avoid cases like this.

It's our interaction that appears to be at the root.  Straight up spawning, and periodic monitoring does not show this behavior.

**Comment by yujuhong** [comment]
> It's our interaction that appears to be at the root.

Care to elaborate, @timothysc?

**Comment by timothysc** [comment]
We can easily spawn hundreds of containers through raw scripts and perform periodic monitoring in those scripts.  (no issues, no timeout)

It's when we try to push the kubelet to higher scales we see issues, even when these machines have ample resources.

**Comment by yujuhong** [comment]
> We can easily spawn hundreds of containers through raw scripts and perform periodic monitoring in those scripts. (no issues, no timeout)
> 
> It's when we try to push the kubelet to higher scales we see issues, even when these machines have ample resources.

You can get the actually docker requests by increasing the log verbosity of docker and compare them against your raw scripts. Then we can see what the difference is.

That's also why I suggested tuning the timeout since that may be one source of difference.

FWIW, I started ~300 pods on a node a few weeks ago and didn't encounter serious issues.

**Comment by Random-Liu** [comment]
Just FYI, according to my benchmark before, starting containers concurrently in different goroutines could make each start operation quite quite slow.

For docker 1.9.1 the highest container starting speed is 3.5/s, if you start 160 containers at the same time, it is possible that some of them will wait minutes.

In my benchmark, I started 100 routines to create and stop containers, the highest operation latency could be 70s+.

**Comment by euank** [comment]
The time it takes to create a large number of containers depends greatly on the graphdriver used (e.g. devicemapper usually is much slower than overlay, especially via a loopback device) and the backing disk iops (nfs vs SSDs and so on).

Out of curiosity, what graphdriver are you using on what sort of storage?

**Comment by timothysc** [comment]
> Out of curiosity, what graphdriver are you using on what sort of storage?

it's devicemapper

**Comment by rrati** [comment]
storage is an lvm thinpool, graphdriver is devicemapper.
$ docker info
...
Storage Driver: devicemapper
...
 Pool Name: docker_vg-docker--pool
...
Logging Driver: journald

**Comment by rrati** [comment]
@yujuhong I increased the default timeout:
-       defaultTimeout = 2 * time.Minute
+       defaultTimeout = 5 * time.Minute

and it made a difference.  It didn't quite complete starting all the pods, but came within 3.  I saw docker had 317 containers running and the last 3 took a while.  The test failed  with 3 containers failing to start, so this seems this timeout or the rate at which the kubelet attempts to start containers could need some adjustment for larger pod counts.

**Comment by yujuhong** [comment]
@rrati, BTW, what version of docker do you use?

> and it made a difference. It didn't quite complete starting all the pods, but came within 3. I saw docker had 317 containers running and the last 3 took a while. The test failed with 3 containers failing to start, so this seems this timeout or the rate at which the kubelet attempts to start containers could need some adjustment for larger pod counts.

Yes, that's why I suggested rate limiting the docker operations. The pod startup throughput is inherently limited by how fast docker can process them (which include other factors as @euank mentioned in https://github.com/kubernetes/kubernetes/issues/27388#issuecomment-226054429). We don't have an SLO for pod startup throughput on kubelet AFAIK. We may work on publishing some reference number for our setup in the future releases, and we'd like the community to pitch in and publish their own results.

In my gce e2e cluster running 1.3 k8s (containervm, docker1.11, aufs, etc), the numbers seem much better and I didn't have to adjust the docker request timeout.

(note: I ran density test, which may be slightly different from the test you ran)
100 pod startup on a single node using the density test (with bumped apiserver client qps limits):
```
STEP: creating replication controller density100-0-d3186cc0-3322-11e6-ae39-c4346b658736 in namespace e2e-tests-density-zv1pq
Jun 15 10:58:54.758: INFO: Created replication controller with name: density100-0-d3186cc0-3322-11e6-ae39-c4346b658736, namespace: e2e-tests-density-zv1pq, replica count: 100
Jun 15 10:59:04.565: INFO: Density Pods: 100 out of 100 created, 0 running, 100 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 10:59:14.565: INFO: Density Pods: 100 out of 100 created, 0 running, 100 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 10:59:24.565: INFO: Density Pods: 100 out of 100 created, 0 running, 100 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 10:59:34.565: INFO: Density Pods: 100 out of 100 created, 6 running, 94 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 10:59:44.565: INFO: Density Pods: 100 out of 100 created, 68 running, 32 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 10:59:54.565: INFO: Density Pods: 100 out of 100 created, 100 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 10:59:54.760: INFO: E2E startup time for 100 pods: 1m0.1956967s
Jun 15 10:59:54.760: INFO: Throughput (pods/s) during cluster saturation phase: 1.6666666
```

200 pod startup time on a single node:
```
Jun 15 11:09:22.127: INFO: Created replication controller with name: density200-0-490a396f-3324-11e6-a0b4-c4346b658736, namespace: e2e-tests-density-cgmyc, replica count: 200
Jun 15 11:09:31.939: INFO: Density Pods: 200 out of 200 created, 0 running, 200 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:09:41.939: INFO: Density Pods: 200 out of 200 created, 0 running, 200 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:09:51.939: INFO: Density Pods: 200 out of 200 created, 0 running, 200 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:10:01.939: INFO: Density Pods: 200 out of 200 created, 0 running, 200 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:10:11.939: INFO: Density Pods: 200 out of 200 created, 0 running, 200 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:10:21.939: INFO: Density Pods: 200 out of 200 created, 0 running, 200 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:10:31.939: INFO: Density Pods: 200 out of 200 created, 0 running, 200 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:10:41.939: INFO: Density Pods: 200 out of 200 created, 0 running, 200 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:10:51.939: INFO: Density Pods: 200 out of 200 created, 10 running, 190 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:11:01.939: INFO: Density Pods: 200 out of 200 created, 31 running, 169 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:11:11.939: INFO: Density Pods: 200 out of 200 created, 45 running, 155 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:11:21.939: INFO: Density Pods: 200 out of 200 created, 98 running, 102 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:11:31.939: INFO: Density Pods: 200 out of 200 created, 198 running, 2 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:11:41.939: INFO: Density Pods: 200 out of 200 created, 200 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Jun 15 11:11:42.133: INFO: E2E startup time for 200 pods: 2m20.194725854s
Jun 15 11:11:42.133: INFO: Throughput (pods/s) during cluster saturation phase: 1.4285715
```

**Comment by rrati** [comment]
@yujuhong My tests were run on RHEL 7.2 vms with docker 1.10 running on OpenStack.

Currently I don't think the docker timeout is exposed as a configuration variable on the kubelet.  Would it make sense to make it available?  Maybe some other tuning knobs?

**Comment by yujuhong** [comment]
> Currently I don't think the docker timeout is exposed as a configuration variable on the kubelet. Would it make sense to make it available? Maybe some other tuning knobs?

Yes, I think exposing request timeout for container runtime is reasonable. I don't recall any other existing knob that's well-defined and would help with this situation directly.
/cc @Random-Liu, who worked on adding the docker timeout.

**Comment by Random-Liu** [comment]
@rrati @yujuhong No configuration for now. We planed to add one before, but because it didn't cause issue at that time, and 2 minutes seems to be long enough, so we haven't done that yet.

I have concern about batch container creation from beginning, because the benchmark shows that could be quite slow. So I added operation timeout metrics in `regular resource tracking` in `kubelet_perf.go`, and found that with current configuration timeout almost never happens. (The regular resource tracking start 100 pods per node)

If needed, I can add one. :)

**Comment by rrati** [comment]
@yujuhong @Random-Liu I think exposing the docker timeout and making it configurable might be a good first step.  #26394 may be the longer term solution.

**Comment by yujuhong** [comment]
@Random-Liu, exposing the knob might be good for rkt as well? I think we should add a generic `--runtime-request-timeout` flag that can be reused by rkt/remote runtimes.

**Comment by Random-Liu** [comment]
@yujuhong If so, should we have timeout in runtime interface?

**Comment by Random-Liu** [comment]
Offline discussed with @yujuhong, the new client/server interface also has context, we can set timeout as what we've done now.

**Comment by feiskyer** [comment]
> Offline discussed with @yujuhong, the new client/server interface also has context #17048, we can set timeout as what we've done now.

+1

**Comment by goltermann** [comment]
@rrati @wojtek-t any work needed here for 1.4?

**Comment by wojtek-t** [comment]
@goltermann - technically, all the discussions above were about more than 100 pods on a single node, which ismore than we officially support.  So from my perspective it's not blocking.

**Comment by trizvanov** [comment]
I've been having a lot of troubles with spinning up my containers, where a particular one may take more than 2 minutes to start.
Is there a guide on setting up timeout values in Kubernetes ?

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @rrati @wojtek-t @Random-Liu

**Comment by yujuhong** [comment]
Removing the milestone since we don't officially support >100 pods per node yet.
