### ISSUE TITLE
scheduler should leverage resource usage for pod placement

### ISSUE THREAD

**Issue by proppy** [kubernetes/kubernetes#274]
Currently the scheduler is doing a round robbin placement over all nodes:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/scheduler.go#L71

I'd be great if the scheduler was leveraging cAdvisor stats for influencing the pod placement decisions.

related #160

**Comment by bgrant0607** [comment]
We're currently working on the stats collection, but not on the scheduling.

**Comment by nkwangleiGIT** [comment]
This is also a great feature that we're looking for, also for the scheduler enhancement.
So for now, we'll enable kubelet to pull data from cAdvisor, and get machine level resource usage first? and then do the scheduler enhancement based on this work?
Thanks a lot!

**Comment by bgrant0607** [comment]
See also #4057

**Comment by davidopp** [comment]
@bgrant0607 noticed this is a dup of #12455; since this one received almost no comments for the last year and a half, I'm going to close it in favor of the newer one.
