### ISSUE TITLE
Write a PR status tool to show details per user on master and branch PR state

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#27403]
Open/closed in both locations and relevant labels cherrypick-*.
cc @matchstick

**Comment by lavalamp** [comment]
Should this just be added to @eparis's dashboard?

**Comment by david-mcmahon** [comment]
That's probably a good place.  I was working a bit on a command-line tool as well.

**Comment by david-mcmahon** [comment]
Not actively working on this anymore.  Unassigning.

**Comment by bgrant0607** [comment]
@david-mcmahon FYI, these kinds of issues should be filed in contrib (at the moment).

**Comment by david-mcmahon** [comment]
Closing.  Dup of https://github.com/kubernetes/contrib/issues/1372
