### ISSUE TITLE
Replication Controller doesn't notice changes in pods labels

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#27405]
To reproduce, I create a rc, wait for its pods to be created, then modify the labels of the pod so that it doesn't match the rc's selector anymore. RC should create another pod, but it doesn't try to.

The problem is this [line](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L357). It should enqueue the old rc if old rc exists.

I have a local fix for the rc manager. I'll check the replicaset controller and add a test then send the PR.

cc @bprashanth

**Comment by bprashanth** [comment]
Yeah, that got dropped somewhere along the way. This should happen: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L349
Nice catch.

**Comment by bprashanth** [comment]
This is important. Marking 1.3.
