### ISSUE TITLE
Set "burst" rate to zero for node evictions in NodeController

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#27413]
Is there any good reason to have a nonzero burst rate? Ten is way too high for small clusters, and the number seems to be chosen at random even for large clusters (it's not really the size of any typical failure domain). I think that for now we should set it to zero.

@gmarek Does this sound reasonable to you?

**Comment by gmarek** [comment]
I think that by 0 you mean 1. Goal of #20979 was to set it in some sane way. I'll send a simple PR changing it to 1.

**Comment by davidopp** [comment]
Yeah sorry, I meant 1.

I'm not suggesting to do the full-blown "make rate proportional to cluster size" thing right now, just to change the burst.

**Comment by goltermann** [comment]
#27422 got merged, can this be closed?

**Comment by davidopp** [comment]
Yes, thanks for noticing.

**Comment by gmarek** [comment]
@goltermann - do you know what description should a PR have to auto close the issue?

**Comment by davidopp** [comment]
I think the problem is that you put a stray period after "Fix"

**Comment by davidopp** [comment]
https://help.github.com/articles/closing-issues-via-commit-messages/
