### ISSUE TITLE
Break genericapiserver and API machinery into separate repos

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#2742]
It would be useful to break the apiserver generic REST infrastructure into a separate project.

/cc @smarterclayton

**Comment by bgrant0607** [comment]
Previous instance of this issue was #700.

**Comment by lavalamp** [comment]
We're splitting it in place. Actual physical separate repo will be future, perhaps distant.

**Comment by bgrant0607** [comment]
cc @ncdc

**Comment by ncdc** [comment]
We're also interested in being able to reuse the code generation tooling against arbitrary repos / go packages. See my post to kubernetes-dev about it today for more details.

**Comment by thockin** [comment]
I've thought about it for DeepCopy, and it should be pretty close to
doable.  Conversion is more complicated.

**Comment by ncdc** [comment]
I have many of the generators working in a separate repo, but I had to hack the scripts a lot. See https://github.com/openshift/kube-projects/pull/9 plus what's already in tree

**Comment by bgrant0607** [comment]
@ncdc Yes, the API machinery needs to be moved into a separate repo also.

**Comment by pmorie** [comment]
>  We're also interested in being able to reuse the code generation tooling against arbitrary repos / go packages. See my post to kubernetes-dev about it today for more details.

We also need stuff like boilerplate verification, gofmt verification, etc to be available to people building things outside the core.  Example: kubernetes-incubator/service-catalog#33

**Comment by kargakis** [comment]
api machinery: https://github.com/kubernetes/apimachinery
api server: https://github.com/kubernetes/apiserver

**Comment by bgrant0607** [comment]
This issue served its purpose.
