### ISSUE TITLE
Broken link in Kubernetes 201 walkthrough

### ISSUE THREAD

**Issue by boucher** [kubernetes/kubernetes#27440]
There's a link in the Deployments section of the [201 walkthrough](http://kubernetes.io/docs/user-guide/walkthrough/k8s201/) to a longer description that's broken. It links to `http://kubernetes.io/docs/user-guide/deployment` but should link to `http://kubernetes.io/docs/user-guide/deployments` (missing an `s`).

**Comment by nikhiljindal** [comment]
Thanks for filing this @boucher 
https://github.com/kubernetes/kubernetes.github.io is the right place to file this issue.
cc @kubernetes/docs @janetkuo

**Comment by boucher** [comment]
Looks like a duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/589.
