### ISSUE TITLE
git checkout fails with "reference is not a tree"

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#27462]
I see the following in Jenkins verification of https://github.com/kubernetes/kubernetes/pull/27453:

```
hudson.plugins.git.GitException: Command "/usr/bin/git checkout -f 6676629a96bf8631fbe106ff5ad147527359cbcc" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 6676629a96bf8631fbe106ff5ad147527359cbcc
```

Artifacts at https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/27453/kubernetes-pull-verify-all/140

**Comment by fejta** [comment]
@mikedanese can you triage? Is this related to the new job somehow?

**Comment by mikedanese** [comment]
Ok, it's also happening on unit/integration on that pr

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/27453/kubernetes-pull-test-unit-integration/30794

**Comment by mikedanese** [comment]
Could be something that only happens with cherrypicks.

**Comment by spxtr** [comment]
Oh! I think I remember this one. I think what happens is this:

1. You open a PR whose head has sha abcde123.
1. Jenkins queues up a build with that sha, but doesn't run it yet.
1. You force-push over that commit, so the head of your PR is now something else.
1. Jenkins tries to checkout the old sha, which no longer exists.

It might not be exactly that, since we actually try to check out the merge commit, but I think that's the idea.

**Comment by wojtek-t** [comment]
@spxtr - what you wrote sounds reasonable and it seems that we can't do much with it. Can we close this one?

**Comment by spxtr** [comment]
I think so, or maybe remove the `kind/flake` label and call it a P3 to try to detect this and fail with a more reasonable message.

**Comment by yujuhong** [comment]
There was no push in #27913, but it still encountered the same problem. Reopening the issue.

**Comment by fejta** [comment]
Check out https://github.com/kubernetes/kubernetes/issues/28021 I am pretty sure at least part of what's happening here is that the plugin isn't designed to handle multiple pulls at the same time.

So PR 28015 actually winds up trying to pull the merge for 28018.

**Comment by ixdy** [comment]
So it looks pretty clear that the GitHub PR builder plugin doesn't handle multiple executors very well. We try to check out `origin/pr/${ghprbPullId}/merge`, but increasingly frequently this is set to a different PR that we're testing at the same time.

There was a rework of some of the envvar code recently, and I tried upgrading the plugin to see if that fixed the issue, but I then ran into a different as-of-yet undiagnosed issue where the plugin was failing to schedule any jobs at all.

I'm noticing that https://github.com/jenkinsci/ghprb-plugin/commit/9c46eab31437d8feaeec7658fcef5062f6b7a40c merged since then, and could very likely explain the more recent issue. So I might try upgrading the plugin again.

**Comment by ixdy** [comment]
Yeah, https://github.com/jenkinsci/ghprb-plugin/issues/366 is almost certainly the more recent issue.

**Comment by ixdy** [comment]
Upgraded the plugin, and tests are running again. Let's see if we keep having issues with the checkouts.

**Comment by ixdy** [comment]
Latest version of the plugin (1.32.8) is broken in a new and fun way:
```
$ while true; do curl -slL https://api.github.com/rate_limit?access_token=[elided] | jq .resources.core.remaining ; sleep 1; done
592
591
589
587
586
584
582
575
564
553
545
535
529
519
509
500
491
483
478
476
473
```

Looking at the logs, it seems to be repeatedly querying PRs without abandon; I see lines like
```
Jul 05, 2016 10:05:04 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #16,062 was updated on repo kubernetes/kubernetes but there aren't any new comments nor commits; that may mean that commit status was updated.
Jul 05, 2016 10:05:04 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #13,925 was updated on repo kubernetes/kubernetes but there aren't any new comments nor commits; that may mean that commit status was updated.
Jul 05, 2016 10:05:04 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #13,216 was updated on repo kubernetes/kubernetes but there aren't any new comments nor commits; that may mean that commit status was updated.
```
repeating a few times per PR per minute.

Downgrading back to 1.31.4 again...

**Comment by ixdy** [comment]
https://github.com/jenkinsci/ghprb-plugin/issues/377 if you want to follow along.

**Comment by ixdy** [comment]
also, the latest version made the bot comment more - you can see this on some of the PRs I linked. maybe the config XML changed?

**Comment by therc** [comment]
I'm stumped with this problem, over in #28743. Do I need to keep prodding k8s-bot, or...?

**Comment by spxtr** [comment]
BTW this is a problem with the Git plugin, not the GitHub PR Builder plugin.

**Comment by ixdy** [comment]
What makes you say that? [From a recent run](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/31064/kubernetes-pull-build-test-e2e-gce/56049/build-log.txt):

```
GitHub pull request #31064 of commit 12c248315f8191396574085591e1d749ab0fe670, no merge conflicts.
...
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/31064/merge:refs/remotes/origin/pr/31064/merge # timeout=20
...
Checking out Revision da5feb577274a5f7b4bb31e9f4bd655b0f143e64 (origin/pr/31373/merge)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f da5feb577274a5f7b4bb31e9f4bd655b0f143e64 # timeout=20
FATAL: Could not checkout da5feb577274a5f7b4bb31e9f4bd655b0f143e64
```

Note how the branch being checked out suddenly changed. I assume that is the GitHub PR Builder plugin's fault, not git.

**Comment by spxtr** [comment]
I hit this issue in a test job that didn't use the PR builder plugin, only the Git plugin. I deleted the test job and now I can't find the logs.

The PR builder plugin just triggers the jobs with the appropriate parameters. It doesn't actually do the checkout.

**Comment by ixdy** [comment]
@spxtr maybe it's a bug in Jenkins' parameter handling, then?

**Comment by ixdy** [comment]
anyway, once we get rid of the GHPRB plugin, we can update Jenkins and see if the issue goes away.

**Comment by spxtr** [comment]
Agreed. If not then Erick is working on getting rid of the Git plugin.

**Comment by ixdy** [comment]
@spxtr https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32082/kubernetes-pull-test-unit-integration/43439/ was once again the GHPRB plugin...

**Comment by rmmh** [comment]
It's the Git plugin. I've patched it and installed the fixed version on pr-jenkins last night, and haven't observed any failures since then. Normally there are ~20 failures per day.

See [JENKINS-26290](https://issues.jenkins-ci.org/browse/JENKINS-26290#comment-269569) for the full details.
