### ISSUE TITLE
sidecar exec

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#27464]
Say I keep my containers as light weight as possible, perhaps using alpine or some other light weight distro.

When something goes wrong in a pod, it can be difficult to exec in and debug sometimes because there are no debugging tools in the container.

It would be awesome if you could temporarily attach a new sidecar container to the specified pod for debugging purposes.

something like:
kubectl exec -it mypod -s mydebugcont /bin/bash

It could even perhaps take a -c flag and attach to the same pid namespace of the specified container so stuff like running strace -p <pid> would work.

**Comment by lavalamp** [comment]
I'm pretty sure this is a duplicate request... Not sure how to find the other issue though. I'll leave this open because it's a well written clear feature request, thanks.

**Comment by kfox1111** [comment]
docker 1.12 has this implemented:
https://github.com/docker/docker/issues/10163

Which I think would be a prereq.

**Comment by jascott1** [comment]
I am very interested in this feature.

**Comment by wilkers-steve** [comment]
I also think this would be a great feature to have

**Comment by jeremyschlatter** [comment]
Similar to #27140

**Comment by xiangpengzhao** [comment]
Yeah this is a dup of #27140. The proposal is https://github.com/kubernetes/community/pull/649. @verb is working on it. The related WIP PRs are #45442, #46243, #46256, #46261.

I suggest we close this issue and follow @verb 's work.

@thockin
