### ISSUE TITLE
Sample cassandra image doesn't work with GCE persistent disk

### ISSUE THREAD

**Issue by lwander** [kubernetes/kubernetes#27476]
Replacing `emptyDir` with a Persistent Volume Claim pointing to a GCE persistent disk for both version 8 and 9 of the sample Cassandra image causes Cassandra to fail during startup due to permission errors around the directory `/cassandra_data`. On :v9 the log output looks like [this](https://gist.github.com/lwander/10a111d7c42fd56cffa478e69ec6166a), and :v8 it looks like [this](https://gist.github.com/lwander/e64cba2795d22f0456cd4c171456d475).

@chrislovecnm
@jeffmendoza

**Comment by chrislovecnm** [comment]
My initial guess is that C* docker user is Cassandra. There was a version of v9 that had that bug. Can you start the image locally and determine the user?

Also I have encountered an issue with 3.x at scale, which is open with Cassandra. Do you need 3 or would 2.2 work for yah?

@bgrant0607 is there anyone that can investigate this? I know everyone is super busy for the 1.3 release, and I am working on the darn demo ;( May be an old docker image...

**Comment by lwander** [comment]
User is `cassandra` (from `$ id -u -n `). 

I'm working on removing cassandra as a dependency from this project, so no need to rush to find a solution.

**Comment by chrislovecnm** [comment]
Removing Cassandra as a dependency?

Do you have access to upload to gcr.io? Noticed that you are a googler, and it looks like the image was not uploaded correctly. The Docker in head does not use Cassandra as a user.

**Comment by lwander** [comment]
> Removing Cassandra as a dependency?

Sorry, I wasn't clear, I meant the project I'm using the Cassandra image in will no longer need Cassandra. 

Do you want me to rebuild the docker image at head and then upload that? I don't think I'll have access to that specific `gcr.io` repository.

**Comment by chrislovecnm** [comment]
@lwander yah we need the image uploaded again ... thanks for the clarification 😄 

@bgrant0607 who can help us figure out if we have something odd going on with `gci.io`. We probably need to re-upload the C* image.

**Comment by jeffmendoza** [comment]
I'm happy to rebuild and upload, what can I check to make sure that the image I'm building is correct?

**Comment by lwander** [comment]
Will checking the user be enough? I think ideally replacing `EmptyDir` with a `GCEPersistentDisk` and making sure Cassandra can start will ensure this is fixed (right now it just crash loops).

**Comment by jeffmendoza** [comment]
I just pulled from head and rebuilt, it is the same as the `v9` I pushed before, image id `108a1ece523a`. Running bash and `whoami` gives `cassandra`.

**Comment by jeffmendoza** [comment]
Also, looking here https://github.com/kubernetes/kubernetes/blob/master/examples/cassandra/image/Dockerfile#L66 I see `USER cassandra` is this correct?

**Comment by chrislovecnm** [comment]
CRAP ... thought got that :(  It is a bug.....

**Comment by pwittrock** [comment]
cc @pwittrock

**Comment by chrislovecnm** [comment]
@lwander this should be addressed in https://github.com/kubernetes/kubernetes/pull/30577

**Comment by chrislovecnm** [comment]
@pwittrock / @lwander shall we close?

**Comment by lwander** [comment]
SGTM, looks like your petset example demonstrates this is fixed.

**Comment by chrislovecnm** [comment]
Eh?

**Comment by xiangpengzhao** [comment]
This should have been fixed in #30577. We're going to close this.

@thockin
