### ISSUE TITLE
rkt: Expose runtime operation latency

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#27485]
Today, we expose the docker runtime's operation latency via the `pkg/kubelet/metrics` package to `prometheus`. We would like to do the same for rkt runtime to understand better about the performance, and help us figure out how to improve.

cc @kubernetes/sig-node @kubernetes/rktnetes-maintainers

**Comment by chancez** [comment]
I was thinking about this the other day. Since the api-service is basically stateless, and rkt has no long living process, one possibility is to have `rkt` create files on disk for the prometheus node-exporter to read:
https://github.com/prometheus/node_exporter#textfile-collector

**Comment by yujuhong** [comment]
Closing this since relevant issues should be handled in CRI or moved to the rktlet repository.
