### ISSUE TITLE
Packet laundering as a workaround for promiscuous mode

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#27489]
To avoid the unregister_netdevice race due to hairpin mode (https://github.com/docker/docker/issues/5618, which is due to a kernel bug, maybe https://bugzilla.kernel.org/show_bug.cgi?id=81211) we flipped the container bridge to promiscuous, but this has various side effects (performance hit, duplicate acks, martian packets etc).

To workaround this we discussed a packet laundering ns, eg: https://gist.github.com/bprashanth/0e3c0cf8ef7fd21fc2e857c96eb6f4d0

And adding 2 rules to the host:
1. DNAT packets going from an endpoint to the service into the laundering netns
2. Don't MASQ packets coming out of the laundering netns, just pass them back to the endpoint

This would probably mean that endpoints can never reach their peers thorugh the Service vip, I think that should be OK? (petset pods DNS lookup their peers through the Service, then use individual hostnames to talk to them). 

@girishkalele

**Comment by bprashanth** [comment]
@kubernetes/goog-cluster @matchstick 

This seems to bug me more than others, probably because I was the one that put in promiscuous mode workaround, but we should definitely try to do something about it in either a minor release or 1.4 latest.

**Comment by freehan** [comment]
This remind me of a potential fix we could try out. 

Kubenet keeps add/delete operation sequential. That guarantees each veth setup/teardown happens separately. I suspect this could help us avoid the kernel bug. I can setup a soak cluster with kubenet+hairpin-veth mode. I remember we had a soak cluster for test, right?

**Comment by thockin-cc** [comment]
It bugs me a lot, but the laundering solution is a gross hack.

**Comment by bprashanth** [comment]
But packet loss, martian source randomness seems worse, no? i see martian packets from duplicate acks in tests

@freehan k8s-jkns-gce-soak-2 should already be doing that I think, but I haven't been following it week to week to know if it ran into anything

**Comment by freehan** [comment]
I could only find recent logs and did not see the kernel bug so far. But this is not convincing enough.

**Comment by freehan** [comment]
Okay... Thanks to a bug. Looks like we are always running in haripin-veth mode. 

```
W0616 00:10:20.375339    2706 kubelet.go:527] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, 
falling back to "hairpin-veth"
I0616 00:10:20.375366    2706 kubelet.go:371] Hairpin mode set to "hairpin-veth"
```

https://github.com/kubernetes/kubernetes/blob/release-1.3/pkg/kubelet/kubelet.go#L552

**Comment by bprashanth** [comment]
when did we start setting `--configure-cbr0=false` ?

**Comment by freehan** [comment]
https://github.com/kubernetes/kubernetes/blob/release-1.3/pkg/kubelet/kubelet.go#L308

**Comment by bprashanth** [comment]
oh, no kubenet sets it https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/kubenet/kubenet_linux.go#L351

**Comment by freehan** [comment]
sorry. please ignore my previous comment. The log lines are misleading. We are in `promiscuous-bridge` mode.

**Comment by bprashanth** [comment]
fantastic, more confusion, maybe we can clarify the logs? i think the logs used to say the right thing, when we shipped 1.2 at least.

**Comment by freehan** [comment]
Okay. It is a known issue. The containervm already has kubelet running and salt will reconfig it and restart it. That is why it seems like kubelet started twice with different configs.

**Comment by girishkalele** [comment]
Prototyping a possibly higher performance solution needing only one tunnel traversal using a separate routing table, avoiding multiple NAT operations too.

1. Setup an IP-in-IP tunnel between two IPs on the same node.
2. `ip rule` to put packets with the masq-mark 0x4000 into a second routing table with a default route pointing into the tunnel.
3. Packets immediately show up on the other end of the tunnel with intact source/destination addresses but 'laundered' to be a new skb and avoid the hairpin check.
4. Continue DNAT operation. Or we can DNAT cluster ip -> pod ip before sending into the tunnel.

https://gist.github.com/girishkalele/905e5e4a260e9c88cbce1504caa8fc99

**Comment by freehan** [comment]
FYI, I ran the stress test from [here](https://github.com/kubernetes/kubernetes/issues/20096#issuecomment-182531030) on my 2 node cluster in haripin-veth mode. It has been more than 36 hours now and yet it has not explode.

**Comment by girishkalele** [comment]
@freehan 

Did you change the code to do sequential veth operations ?

**Comment by bprashanth** [comment]
Is coreos using kubenet ? https://github.com/kubernetes/kubernetes/issues/27498, quite a few reports of this from the wild have been kube+coreos

**Comment by freehan** [comment]
@girishkalele Yes. It has been done for quite some time for some other reasons. 

@bprashanth Nope. It looks like node test is not using network plugins.

**Comment by freehan** [comment]
Ran the stress test over the weekend. Still has not bump into the kernel bug. 
But kubelet breaks this morning due to OOM + cadvisor issue. @dchen1107 will follow up with that.

This looks promising. We can observe soak cluster for sometime. And consider switching to `hairpin-veth` mode with `kubenet` for 1.3.1. 

FYI, soak tests currently is not healthy  #27630 #27374

**Comment by chrislovecnm** [comment]
I am hitting a challenge with Martian messages in `dmesg`.  Is this related?

```console
[145884.019682] ll header: 00000000: ff ff ff ff ff ff 0a 58 0a f6 c5 03 08 06        .......X......
[145885.012372] IPv4: martian source 10.246.197.1 from 10.246.197.3, on dev cbr0
```

**Comment by freehan** [comment]
`kubenet` + `hairpin-veth` does not work out. #27498

Need Plan B

**Comment by thockin** [comment]
I really like this attack.  OPen questions:

What IPs to use?  I think we have to use link-local addresses, or maybe we
can actually trick this into working with 127.0 addresses?

I don't think we want to do this for all SNAT packets - that will include
external traffic through load-balancers.  We could add a rule  to recognize
the packets from X to X and add another mark, though.

Not urgent priority, but as background, a demo with those constraints
addressed would be VERRY welcome

**Comment by bprashanth** [comment]
By "this" you mean the ip encap idea? @girishkalele I thought that didn't work because the connection was stateful so it dropped packets on the way back with martian source, did you actually figure that out? i agree that would be pretty cool.

**Comment by girishkalele** [comment]
@thockin @bprashanth 

It worked on the way from A to B, it routed packets to the second routing table, injected them into the tunnel and then back from the other end of the tunnel, then DNAT to the cbr0 ->veth B.

With the SYN response however, conntrack failed to match the packets to the flow, so they couldn't SNAT on the way back...I didn't investigate further though, it might be possible to fix conntrack's matching.

We need addresses for the tunnel's 2 endpoints, I used cbr0 and eth0 addresses, otherwise no additional addresses are needed.

**Comment by thockin** [comment]
You resused their addresses - how does that even work?

**Comment by girishkalele** [comment]
Yes, GRE tunnels must specify a local interface ip as local address. In this case, we just create two tunnels pointing between two local IPs on the node. The tunnels themselves have no ips - they are just point-to-point links.

```
# ip addr show dev cbr0
5: cbr0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1460 qdisc htb state UP qlen 1000
    inet 10.180.3.1/24 scope global cbr0
# ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP qlen 1000
    inet 10.240.0.3/32 brd 10.240.0.3 scope global eth0

# ip tunnel add laundryin mode gre remote 10.240.0.3 local 10.180.3.1
# ip link set laundryin up
# ip tunnel add laundryout mode gre local 10.240.0.3 remote 10.180.3.1
# ip link set laundryout up
# ip addr show dev laundryin
15: laundryin@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 65512 qdisc noqueue state UNKNOWN
    link/gre 10.180.3.1 peer 10.240.0.3
# ip addr show dev laundryout
16: laundryout@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 65512 qdisc noqueue state UNKNOWN
    link/gre 10.240.0.3 peer 10.180.3.1
```

Gist: https://gist.github.com/girishkalele/905e5e4a260e9c88cbce1504caa8fc99

**Comment by thockin-cc** [comment]
Won't that encap all traffic between eth0 and cbr0?

**Comment by girishkalele** [comment]
Yes, but only the traffic going to the tunnel interface gets encapsulated using the eth0 and cbr0 IPs as the outer IP header.
If this laundry scheme can get past conntrack issues, it would be best to create two loopback interfaces with 127.0.1.x addresses to use for the tunnel so that we don't depend on the eth0 and cbr0 interfaces.

**Comment by bprashanth** [comment]
We're using an ebtables hack, as undesirable as it is, it's more desirable than the hack proposed in this issue
