### ISSUE TITLE
Investigate possible scheduler spreading issues

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#27484]
In the last few weeks we've received a couple of reports of the scheduler not spreading pods as expected. We haven't changed this code recently so I strongly suspect it is WAI, but it seems worth investigating anyway.

http://stackoverflow.com/questions/37494314/kubernetes-pods-are-not-spreaded-across-different-nodes
http://stackoverflow.com/questions/37784480/avoiding-kubernetes-scheduler-to-run-all-pods-in-single-node-of-kubernetes-clust

We should investigate
(1) if you request and limit 0, does it spread evenly (taking into account system pods, of course) using the default small mem/CPU we give to zero-resource pods
(2) if you use a normal request and/or limit, does it spread properly (taking into account system pods, of course)

**Comment by erictune** [comment]
I cannot hold the release on hearsay about a regression.  Kicking out of 1.3.

**Comment by timothysc** [comment]
@ConnorDoyle Can you investigate this one?

**Comment by davidopp** [comment]
Suggestion: Take a look at the scheduler unit tests to make sure we are adequately testing spreading (resource spreading, selector spreading, etc.). Consider adding one or more integration tests, just to make sure we're testing this at a higher level.
