### ISSUE TITLE
IAM roles should be cluster specific

### ISSUE THREAD

**Issue by crizCraig** [kubernetes/kubernetes#27490]
`config-default.sh` currently sets AWS IAM roles with:

```
IAM_PROFILE_MASTER="kubernetes-master"
IAM_PROFILE_NODE="kubernetes-minion"
```

However, it seems that I would not want my staging minions to have access to the same resources as my production minions.

The `kubernetes-master` IAM role policy looks like this:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["ec2:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": ["elasticloadbalancing:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::kubernetes-*"
      ]
    }
  ]
}
```

So would it make sense to change resource lists from things like `arn:aws:s3:::kubernetes-*` to `arn:aws:s3:::kubernetes-${CLUSTER_ID}*`?

**Comment by justinsb** [comment]
Thanks for the report - I agree, but as kube-up is in maintenance mode we're not going to be making changes like this (trying to do so in a backwards compatible way makes it tricky!)

kops does separate IAM roles by cluster, so may be a better match.
