### ISSUE TITLE
Enable ABAC configuration files update dynamically

### ISSUE THREAD

**Issue by jay-lau** [kubernetes/kubernetes#27516]
Currently, for ABAC mode, I need to configure the basic-auth-file and authorization-policy-file first, then start the API with those two files.

The problem is that if there are some new users added in basic-auth-file, I need to restart apiserver, this is not convenient for the admin, it is better enhance API server can reload those files dynamicaly without restart.

**Comment by jay-lau** [comment]
Currently, I was using "confd" to reload the apiserver if there are any changes in those configuration files, the only problem is that the apiserver needs to be restart if it was reloaded.

But as most customers are now using kubernetes to manage long running services, I think it is OK to restart the apisever; But as Kubernetes also support job, and restarting apiserver may cause some job failed, so it is better to address this in kubernetes roadmap to make sure those files can be reloaded without restart apiserver.

**Comment by harryge00** [comment]
#23502
@huang195 has already submitted a PR on detecting and reloading ABAC policy. But closed then...
I also need such feature.

**Comment by jay-lau** [comment]
Thanks @harryge00 I posted some comments there in https://github.com/kubernetes/kubernetes/pull/23502 , I do not know why they recommended to use OpenShift but not Kubernetes, hope we can get more feedback for this soon. Thanks.

**Comment by lavalamp** [comment]
Dup of #27418
