### ISSUE TITLE
Proposal: informer redesign

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#27519]
(To continue https://github.com/kubernetes/kubernetes/issues/27004#issuecomment-225643876)

Recently, we have found a race in informer in https://github.com/kubernetes/kubernetes/issues/27004. Although the P0 issue has been fixed as quickly as possible, we agreed that we should redesign it properly after 1.3 release: https://github.com/kubernetes/kubernetes/issues/27004#issuecomment-225969446, https://github.com/kubernetes/kubernetes/pull/27341#discussion_r67003455, https://github.com/kubernetes/kubernetes/pull/27341#issuecomment-225921010.

The problem of current informer design is that it couples queue and store. This has caused some races. Wojtek has done a great job fixing it for 1.3 release. I am reluctantly pointing out that it's not the ideal solution. First, it couples the queue and store with complicated locking; Second, it's really hard to maintain if someone wants to change the code in the future.
![f3f57e10-314b-11e6-9814-32c555988dc6](https://cloud.githubusercontent.com/assets/920884/16105411/0f38225a-333f-11e6-8e3e-4c9f964da6a1.png)

One redesign choice we made is serialize all updates on store inside controller:
![b3741b74-3170-11e6-8020-eadab862ba10](https://cloud.githubusercontent.com/assets/920884/16101359/ba072ce2-3319-11e6-917a-6a48e94cc3bf.png)
Now the queue wouldn't talk to store anymore. The diff comparison on Relisting, iterating items in Resync will be serialized along with Add/Update/Delete operations inside controller. Controller is the only one that mades changes upon store.
With this redesign, we should be more confident to guarantee race-free in informer, and separate concerns of sub-components. This will improve maintainability and ease mindset of future maintainer, contributor.

Finally, I want to give a big shoutout for Wojtek for the quick fix.

**Comment by timothysc** [comment]
+1 from me.  Folks should be aware that there are other controllers written in the broader ecosystem that will be affected in the 1.4-ish timeframe. 

/cc @deads2k @rrati @smarterclayton

**Comment by rrati** [comment]
+1 from me too

**Comment by smarterclayton** [comment]
Let's queue this up for a discussion in the next @kubernetes/sig-api-machinery meeting.

**Comment by lavalamp** [comment]
added to agenda

**Comment by timothysc** [comment]
per-discussion, @hongchaodeng is going to outline an execution strategy on this issue. 
/cc @deads2k

**Comment by hongchaodeng** [comment]
ref: #27984

**Comment by hongchaodeng** [comment]
@lavalamp 
In last week's @kubernetes/sig-api-machinery meeting, I think we have talked about too many separate things, which didn't lead to any conclusion on this issue.

Now let's focus on original reason of this redesign, focus on the pure goal of eliminating the race in informer. Do we want to make the race free something that is easy to reason about? If so, let me give the following comparison:
- Design 1: The store store will get changes from the queue and apply them. But the queue is also getting data from the store and sending changes based on the data. What's more, this is not even done sequentially, but concurrently in separate goroutines.
- Design 2: The store will still get changes from the queue and apply the. But the queue never gets data from the store. We should shift the processing logic into store, into only one place.

Now let me ask the question, is Design 2 easier to reason about than Design 1? Do we want to make informer race free and do we want to make the race free easy to reason about? If so, is there still any concern that we should be aware of?

Thanks in advance for the reply!

**Comment by lavalamp** [comment]
@hongchaodeng

I'm severely lacking in design review bandwidth right now. Given that we've
fixed the races, is this urgent? This is not something I want to change
without giving it a lot of attention to get it right and I just don't have
attention to spare right now, since this is not on my list of priorities
for 1.4...

**Comment by xiang90** [comment]
@lavalamp I feel this is urgent since we want to push forward the shared informer stuff in 1.4. We'd better to get a solid implementation of informer with clear APIs guarantee soon.

**Comment by hongchaodeng** [comment]
Can you reason about how the race has been fixed? This is something that we are worried about given shared informer will introduce more complicated concurrency patterns. It is also what this proposal tries to reach.

**Comment by lavalamp** [comment]
I was under the impression we'd already merged the shared informer stuff.
Is there more to do? Is there an issue I should be following?

**Comment by hongchaodeng** [comment]
Here are the questions that I believe we need to answer and document clearly, so that we can have a correctness review of the shared informer and write tests: https://github.com/kubernetes/kubernetes/issues/27984

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.
