### ISSUE TITLE
Misleading "PersistentVolumeClaim 'xy' is not in cache" warning

### ISSUE THREAD

**Issue by asalkeld** [kubernetes/kubernetes#27523]
$subject is not currently supported. Is there any reason why this hasn't been done?

The docs do correctly show the current state:
http://kubernetes.io/docs/user-guide/persistent-volumes/

I'd like to add support for this, any objections?

**Comment by asalkeld** [comment]
So this is somewhat working:
I can create the PV and PVC, but the pod has an error.

```
$ kubectl get pv
NAME         CAPACITY   ACCESSMODES   STATUS    CLAIM                    REASON    AGE
ceph-fs-pv   1Gi        RWX           Bound     default/ceph-claim-rwm             3m
$ kubectl get pvc
NAME             STATUS    VOLUME       CAPACITY   ACCESSMODES   AGE
ceph-claim-rwm   Bound     ceph-fs-pv   0                        3m
$ kubectl get events
...
1m          18s        8         pod-with-pv   Pod                   Warning   FailedScheduling          {default-scheduler }     PersistentVolumeClaim 'default/ceph-claim-wm' is not in cache
```

Anyone know what "is not in the cache" error means - or how it can be resolved?
kubectl describe pod shows the same error.

**Comment by asalkeld** [comment]
I found this in the logs:

```
I0620 15:41:21.222049   22862 controller.go:513] claim "default/angus-claim-rwm" entered phase "Lost"
I0620 15:41:21.222066   22862 controller.go:535] claim "default/angus-claim-rwm" changed status to "Lost": Bound claim has lost its PersistentVolume. Data on the volume is lost!
```

**Comment by saad-ali** [comment]
cc @rootfs @jsafrane @kubernetes/sig-storage

**Comment by jsafrane** [comment]
CephFS PVs **should** work, there is nothing special about them... All these messages mean that something has deleted the PV and Kubernetes can't start a pod that uses it:

* `volume "cephfs-angus" deleted` 
* `Lost` PVC status
* `PersistentVolumeClaim 'default/ceph-claim-wm' is not in cache`

Kubernetes do not implement any deleter for Ceph volumes (yet), it must have been deleted by something outside of Kubernetes.

**Comment by asalkeld** [comment]
thanks @jsafrane , I am not manually doing any deleting. I'll check for some magic happening in ceph.

**Comment by asalkeld** [comment]
OK, this was user error on my part. But totally unhelpful errors.
Basically I had a type-o in the pods "claimName" so it only failed in a GET to the api-server.
It would be nice to validate this earlier.

So I had "ceph-claim-rwm" in the claim and "ceph-claim-wm" in the pod.
```
427 desired_state_of_world_populator.go:158] Error processing volume "ceph-volume" for pod "default"/"pod-angus-wm": error processing PVC "default"/"angus-claim-wm": failed to fetch PVC default/angus-claim-wm from API server. err=persistentvolumeclaims "angus-claim-wm" not found
```
Sorry for the noise.

**Comment by jsafrane** [comment]
We can easily update `kubectl describe pod` output to say `PersistentVolumeClaim 'default/ceph-claim-wm' not found` instead `is not in cache`, I filled #27772 for that.
