### ISSUE TITLE
kubectl completion breaks git completions when sourced on zsh

### ISSUE THREAD

**Issue by juanvallejo** [kubernetes/kubernetes#27538]
`source <(kubectl completion zsh)`
breaks `git` command completions when sourced on a zsh shell.

When pressing `tab` to see completions on zsh, after sourcing output from `kubectl completion zsh`, the following output is produced:

```
_git:58: _git_commands: function definition file not found
_git:58: _git_commands: function definition file not found
_git:58: _git_commands: function definition file not found
```

**Comment by jguenther-va** [comment]
I'm having a similar issue, except in my case sourcing `kubectl` completion breaks `gcloud` completion. If I re-source `gcloud` completions (from the Google cloud SDK) they work again, but that breaks `kubectl` completion. No errors are output, but when this happens hitting `TAB` just offers file/dir completion candidates from my current directory.

As far as I can tell, no other completion sources are affected (and git completion works fine for me)

zsh 5.2 (from homebrew)
Google Cloud SDK 120.0.0
kubectl-darwin-x86_64 1.3.3 (installed via `gcloud components install kubectl`)

**Comment by wrs** [comment]
A workaround for this seems to be to re-issue the `complete` commands from `completion.zsh.inc` after doing the `source <(kubectl completion zsh)`:

```sh
source '/Users/walter/bin/google-cloud-sdk/path.zsh.inc'
source '/Users/walter/bin/google-cloud-sdk/completion.zsh.inc'
source <(kubectl completion zsh)

# Workaround for https://github.com/kubernetes/kubernetes/issues/27538
complete -o nospace -o default -F _python_argcomplete "gcloud"
complete -o default -F _bq_completer bq
complete -o nospace -F _python_argcomplete gsutil
```

**Comment by philpennock** [comment]
I believe that this may be a side-effect of the bug which I've reported as issue #32029 -- I filed a new bug for the root-cause which I _know_ affects me, I'm not certain that it's the cause of your issues too.

I'm currently using:

```
if [[ "${path[(r)*/google-cloud-sdk/bin]}" != "" ]]; then
        local d
        d="${path[(r)*/google-cloud-sdk/bin]}"
        if grep -qs '^compinit$' "${d:h}/completion.zsh.inc" ; then
                print -u2 "zshrc: avoiding compinit-invoking ${d:h}/completion.zsh.inc"
        else
                source "${d:h}/completion.zsh.inc"
        fi
        unset d
fi
if [[ -d ~/.kube ]] && have_cmd kubectl ; then
        . <( kubectl completion zsh | grep -v '^autoload .*compinit$' )
fi
```

(which relies upon having a `have_cmd` function, but you can fake it; that's only because this zshrc is shared across multiple systems, most of which won't have kubectl installed).

Then manually comment out the completion system initialization commands from `completion.zsh.inc` and you should be able to see if the system-init is what was stomping on your existing completions.

**Comment by wrs** [comment]
Indeed yes, for my simple one-laptop setup this "live patch" seems to do the trick:

```sh
source <(grep -v compinit ~/bin/google-cloud-sdk/completion.zsh.inc)
source <(kubectl completion zsh  | grep -v '^autoload .*compinit$')
```
