### ISSUE TITLE
upgrade "github.com/imdario/mergo"

### ISSUE THREAD

**Issue by onlyjob** [kubernetes/kubernetes#27543]
Please upgrade vendored [github.com/imdario/mergo](https://github.com/imdario/mergo/releases): its releases are semantically versioned and problems that made Kubernetes stick to older version of _mergo_ appears to be fixed.
I think there is no need to delay upgrade any longer.

**Comment by lavalamp** [comment]
feel free to send us a PR!

**Comment by MHBauer** [comment]
I'd like to give this a try. See if I can understand how to use godep.

**Comment by spiffxp** [comment]
/sig api-machinery
client-go uses mergo, although given that this work has been tried and abandoned at least once, this issue can probably be closed as stale / wont-fix

**Comment by onlyjob** [comment]
Still not fixed, still causing [troubles](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878254) on 1.7.7... :(

Here is patch as per https://github.com/kubernetes/kubernetes/pull/28270#issuecomment-230105707:

~~~~
--- a/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
+++ b/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
@@ -168,15 +168,15 @@
 		userAuthPartialConfig, err := config.getUserIdentificationPartialConfig(configAuthInfo, config.fallbackReader, persister)
 		if err != nil {
 			return nil, err
 		}
-		mergo.Merge(clientConfig, userAuthPartialConfig)
+		mergo.MergeWithOverwrite(clientConfig, userAuthPartialConfig)
 
 		serverAuthPartialConfig, err := getServerIdentificationPartialConfig(configAuthInfo, configClusterInfo)
 		if err != nil {
 			return nil, err
 		}
-		mergo.Merge(clientConfig, serverAuthPartialConfig)
+		mergo.MergeWithOverwrite(clientConfig, serverAuthPartialConfig)
 	}
 
 	return clientConfig, nil
 }
@@ -194,9 +194,9 @@
 	configClientConfig := &restclient.Config{}
 	configClientConfig.CAFile = configClusterInfo.CertificateAuthority
 	configClientConfig.CAData = configClusterInfo.CertificateAuthorityData
 	configClientConfig.Insecure = configClusterInfo.InsecureSkipTLSVerify
-	mergo.Merge(mergedConfig, configClientConfig)
+	mergo.MergeWithOverwrite(mergedConfig, configClientConfig)
 
 	return mergedConfig, nil
 }
 
@@ -256,10 +256,10 @@
 		}
 		promptedConfig := makeUserIdentificationConfig(*promptedAuthInfo)
 		previouslyMergedConfig := mergedConfig
 		mergedConfig = &restclient.Config{}
-		mergo.Merge(mergedConfig, promptedConfig)
-		mergo.Merge(mergedConfig, previouslyMergedConfig)
+		mergo.MergeWithOverwrite(mergedConfig, promptedConfig)
+		mergo.MergeWithOverwrite(mergedConfig, previouslyMergedConfig)
 		config.promptedCredentials.username = mergedConfig.Username
 		config.promptedCredentials.password = mergedConfig.Password
 	}
 
@@ -399,13 +399,13 @@
 	contextName, required := config.getContextName()
 
 	mergedContext := clientcmdapi.NewContext()
 	if configContext, exists := contexts[contextName]; exists {
-		mergo.Merge(mergedContext, configContext)
+		mergo.MergeWithOverwrite(mergedContext, configContext)
 	} else if required {
 		return clientcmdapi.Context{}, fmt.Errorf("context %q does not exist", contextName)
 	}
-	mergo.Merge(mergedContext, config.overrides.Context)
+	mergo.MergeWithOverwrite(mergedContext, config.overrides.Context)
 
 	return *mergedContext, nil
 }
 
@@ -415,13 +415,13 @@
 	authInfoName, required := config.getAuthInfoName()
 
 	mergedAuthInfo := clientcmdapi.NewAuthInfo()
 	if configAuthInfo, exists := authInfos[authInfoName]; exists {
-		mergo.Merge(mergedAuthInfo, configAuthInfo)
+		mergo.MergeWithOverwrite(mergedAuthInfo, configAuthInfo)
 	} else if required {
 		return clientcmdapi.AuthInfo{}, fmt.Errorf("auth info %q does not exist", authInfoName)
 	}
-	mergo.Merge(mergedAuthInfo, config.overrides.AuthInfo)
+	mergo.MergeWithOverwrite(mergedAuthInfo, config.overrides.AuthInfo)
 
 	return *mergedAuthInfo, nil
 }
 
@@ -430,15 +430,15 @@
 	clusterInfos := config.config.Clusters
 	clusterInfoName, required := config.getClusterName()
 
 	mergedClusterInfo := clientcmdapi.NewCluster()
-	mergo.Merge(mergedClusterInfo, config.overrides.ClusterDefaults)
+	mergo.MergeWithOverwrite(mergedClusterInfo, config.overrides.ClusterDefaults)
 	if configClusterInfo, exists := clusterInfos[clusterInfoName]; exists {
-		mergo.Merge(mergedClusterInfo, configClusterInfo)
+		mergo.MergeWithOverwrite(mergedClusterInfo, configClusterInfo)
 	} else if required {
 		return clientcmdapi.Cluster{}, fmt.Errorf("cluster %q does not exist", clusterInfoName)
 	}
-	mergo.Merge(mergedClusterInfo, config.overrides.ClusterInfo)
+	mergo.MergeWithOverwrite(mergedClusterInfo, config.overrides.ClusterInfo)
 	// An override of --insecure-skip-tls-verify=true and no accompanying CA/CA data should clear already-set CA/CA data
 	// otherwise, a kubeconfig containing a CA reference would return an error that "CA and insecure-skip-tls-verify couldn't both be set"
 	caLen := len(config.overrides.ClusterInfo.CertificateAuthority)
 	caDataLen := len(config.overrides.ClusterInfo.CertificateAuthorityData)
--- a/staging/src/k8s.io/client-go/tools/clientcmd/loader.go
+++ b/staging/src/k8s.io/client-go/tools/clientcmd/loader.go
@@ -208,24 +208,24 @@
 	// first merge all of our maps
 	mapConfig := clientcmdapi.NewConfig()
 
 	for _, kubeconfig := range kubeconfigs {
-		mergo.Merge(mapConfig, kubeconfig)
+		mergo.MergeWithOverwrite(mapConfig, kubeconfig)
 	}
 
 	// merge all of the struct values in the reverse order so that priority is given correctly
 	// errors are not added to the list the second time
 	nonMapConfig := clientcmdapi.NewConfig()
 	for i := len(kubeconfigs) - 1; i >= 0; i-- {
 		kubeconfig := kubeconfigs[i]
-		mergo.Merge(nonMapConfig, kubeconfig)
+		mergo.MergeWithOverwrite(nonMapConfig, kubeconfig)
 	}
 
 	// since values are overwritten, but maps values are not, we can merge the non-map config on top of the map config and
 	// get the values we expect.
 	config := clientcmdapi.NewConfig()
-	mergo.Merge(config, mapConfig)
-	mergo.Merge(config, nonMapConfig)
+	mergo.MergeWithOverwrite(config, mapConfig)
+	mergo.MergeWithOverwrite(config, nonMapConfig)
 
 	if rules.ResolvePaths() {
 		if err := ResolveLocalPaths(config); err != nil {
 			errlist = append(errlist, err)
--- a/staging/src/k8s.io/client-go/tools/clientcmd/client_config_test.go
+++ b/staging/src/k8s.io/client-go/tools/clientcmd/client_config_test.go
@@ -33,17 +33,17 @@
 		X string
 	}
 	dst := T{X: "one"}
 	src := T{X: "two"}
-	mergo.Merge(&dst, &src)
+	mergo.MergeWithOverwrite(&dst, &src)
 	if dst.X != "two" {
-		// mergo.Merge changed in an incompatible way with
+		// mergo.MergeWithOverwrite changed in an incompatible way with
 		//
 		//   https://github.com/imdario/mergo/commit/d304790b2ed594794496464fadd89d2bb266600a
 		//
 		// We have to stay with the old version which still does eager
 		// copying from src to dst in structs.
-		t.Errorf("mergo.Merge library found with incompatible, new behavior")
+		t.Errorf("mergo.MergeWithOverwrite library found with incompatible, new behavior")
 	}
 }
 
 func createValidTestConfig() *clientcmdapi.Config {
~~~~

**Comment by imdario** [comment]
Please, check this issue related to Kubernetes and Mergo: https://github.com/imdario/mergo/issues/33#issuecomment-357105051

I just released version 0.3.0, which introduces transformers and fixes several bugs.

**Comment by nikhita** [comment]
@onlyjob Is this still needed?

**Comment by onlyjob** [comment]
Of course it is needed... This bug is still opened, isn't it?

**Comment by imdario** [comment]
FYI, I released version 0.3.3 with more fixes and introduced semantic versioning.

**Comment by onlyjob** [comment]
Over two years passed... Perhaps it's time to finally fix the issue instead of closing it automatically?

**Comment by nikhita** [comment]
For those who want to work on this, instructions for bumping a dependency exist here: https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md.

**Comment by andrewshadura** [comment]
This issue is trivial to fix, why does it take so long to even have it looked at?

**Comment by dims** [comment]
@imdario @onlyjob @andrewshadura we could use help! there is a open PR which seems to have got stuck, can you please work with the author of https://github.com/kubernetes/kubernetes/pull/56775 (or take over that PR?)

**Comment by onlyjob** [comment]
I can't help and you guys should be able to do it without asking author of  "mergo"  for help...  :)

**Comment by onlyjob** [comment]
I've heard "feel free to send us a PR" before. But there are some problems:

 * Bad dynamics. I feel little incentive to participate when such a trivial issue remains to be the problem for years...

 * Contributor's agreement. You wouldn't even accept PRs from me so I'm not even trying any more. I've made it easy for you by pasting valid tested patch here and anyone is still free to apply it on my behalf. No credits required.

 * Poor dependency hygiene. Tracking dependency libraries is clearly neglected by Kubernetes project. Updating libraries should be more important...

**Comment by dims** [comment]
@onlyjob we have been discussing such concerns and trying to come up with solutions in the `Contributor Experience Special Interest Group` in https://github.com/kubernetes/community/tree/master/sig-contributor-experience please do feel free to join us on the slack channel etc. would love for you to participate and help come up with solutions to make things better. For example adding/modifying dependencies were a big pain 2 years ago, it took a lot of iterations to get it to the point where it is not such a big problem any more https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md . there is a lot of work going on in test-infra repo around bots and ci jobs, so may be we can think about ways and means to automatically propose dependency updates for example. hope that helps with the larger questions. 

On the contributors agreement, yes, CNCF require a CLA (https://github.com/kubernetes/community/blob/master/CLA.md) projects are investigating switching to DCO (example https://github.com/kubernetes/helm/issues/4206 )

**Comment by imdario** [comment]
I'm happy to help but I won't be able to in the next two weeks. I'll check this [TestOldMergoLib](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/clientcmd/client_config_test.go#L31) in order to ensure the compatibility.

I'm obliged to say that the old behavior was based in a real bug, so it wasn't intended to work as it did. It should be possible to update Mergo. Proof of this is that Docker is using the latest version 0.3.5: https://github.com/moby/moby/pull/37239

**Comment by dims** [comment]
Awesome! thanks @imdario

**Comment by andrewshadura** [comment]
@dims, @imdario: but there’s a patch somewhere in the comments above, I thought that should be helpful already :) It shouldn’t be difficult for someone who’s actually contributing to the project to take that patch and rebase it to the current code.

**Comment by MHBauer** [comment]
Wow, what a blast from the past. I took a whack at this as one of my first attempts at a PR. I'm curious enough to take a quick look at it, but I'd prefer if an expert ended up handling it.

**Comment by cblecker** [comment]
@onlyjob @andrewshadura This issue was opened telling "us" to take an action. It wasn't opened as a bug, or with details on why this action should be taken. Upgrading for upgrading's sake isn't something that is necessarily needed with vendored code. The whole point of vendoring your source code is so that a code base isn't broken when a dependency makes a breaking change, like the mergo library did.

With nearly 2200 issues open, we triage based on priority. With no details, why would this be a priority? The api machinery code is working just fine the way it is. As @dims mentioned, this is a volunteer, community driven open source project.

Now, having done some digging, what I see is there is an issue with the way [Debian packages kubernetes](https://sources.debian.org/patches/kubernetes/1.7.16+dfsg-1/), and I'm guessing there is some forced reliance on a newer version of mergo, rather than allowing it to use the vendored version of the library.

The biggest thing missing from this issue right from the beginning is an explanation of *why*. I'd suggest including that in future reports if you would like a more timely response.

**Comment by dims** [comment]
@onlyjob please see @cblecker 's effort and help if possible there - https://github.com/kubernetes/kubernetes/pull/65779#issuecomment-402279223

**Comment by rzr** [comment]
Even if this ticket is closed let me crosslink to debian tracker which is linking to this (no more blocking) issue:
https://bugs.debian.org/886739

**Comment by onlyjob** [comment]
@rzr, This issue was never "blocking". A while ago I have patched Kubernetes in Debian with the patch that I've contributed here.

**Comment by dims** [comment]
@onlydole @rzr https://github.com/kubernetes/kubernetes/pull/65779 has merged. is there anything else to do here?

**Comment by onlyjob** [comment]
@dims, we are all good, nothing else to do here, thanks. I was just replying to @rzr. Sorry for noise.

**Comment by rzr** [comment]
This ticket can be closed, but I was wondering if there is also other tickets related to integration in debian archive.

Otherwise track:
https://bugs.debian.org/795652

**Comment by onlyjob** [comment]
@rzr please follow Debian related issues in Debian.
No more comments here please since there is nothing left here to do.
