### ISSUE TITLE
Want: MultiKey RW Transactions + Indexing in Storage

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#27548]
Workloads are implemented using multiple api objects in etcd (Deployment => RS => Pod) that often need to be read and written transactionally.

Because we do not have multi key write transactions, our business logic needs to identify and handle partially applied changes (e.g. scaling multiple RS in a deployment).  This pushes complexity into the business logic of the controller that should instead be handled by storage.

Because we are not able to index fields (e.g. labels) in the storage layer, the full storage is read into an in-memory cache and indexed in-memory.  The cache is updated asynchronously after writes are persisted (not a write-through cache).  This makes it hard to make guarantees about what persisted changes are reflected in our reads when syncing objects.

Pushing the management of "transactions" out of our business logic and into the storage layer will reduce the total complexity of the system.  Pushing indexes into the storage layer will reduce the need for an in-memory cache.

Right now the complexity is manageable, but that will become less true as more controllers are added.

**Comment by lavalamp** [comment]
We need a way of doing batch api transactions first, IMO. Right now we have no way of even attempting to indicate a transaction to the apiserver.

Additionally, as we start to federate apiservers (imagine openshift installed on a k8s cluster) this won't be possible even in theory, since different storage backends will be used. Even in our current set up, events are not stored in the same place as other items. So clients would have to understand what is co-located in order to produce valid transactions. That's also complexity that's unfortunate to push off onto the client.

**Comment by bgrant0607** [comment]
I agree with @lavalamp. 

We want to facilitate multiple layers of APIs and systems built atop the core primitive: pods. 

We could expose atomic transactions at the storage layer, but that wouldn't be accessible to the next layer.

One could implement three-phase commit in any layer, but I don't think that's better.

**Comment by hongchaodeng** [comment]
@pwittrock 
Thanks for raising the issue. We are optimizing the storage layer and definitely would like to hear more feedback!
Some questions:
- Indexing labels and fields are pretty straight-forward. Other than these two, is there anything else to be indexed?
- Re. multi-key transaction, can you clarify more about:

> our business logic needs to identify and handle partially applied changes (e.g. scaling multiple RS in a deployment)

**Comment by hongchaodeng** [comment]
ref: #20572

**Comment by bgrant0607** [comment]
@hongchaodeng I think better use cases for multi-resource transactions are #1468 and #8625 -- uses that would be underneath the current API rather than exposed through the API.

**Comment by hongchaodeng** [comment]
Submitted a proposal: #29888

**Comment by kargakis** [comment]
Give transactions to the people!

**Comment by jsafrane** [comment]
I have another use case: we need to write `persistentVolume.spec.claimRef` and `persistentVolumeClaim.spec.volumeName` in a single transaction. Now we do it in two writes and we have lot of code to recover from corner case when PV is successfully written and write of PVC has failed from some reason.

**Comment by timothysc** [comment]
So we'll need to factor out the multi-op through the storage interface and make certain it can apply throughout the registry. 

@wojtek-t @lavalamp @hongchaodeng and myself would need to get the base in place to support this.

**Comment by justinsb** [comment]
Regardless of etcd2/etcd3 concerns, note that it's going to be tricky to do transactions across different resources, because of `--etcd-servers-overrides` - I think it requires support for something like two-phase commit.

**Comment by kargakis** [comment]
Proportional scaling in Deployments could benefit from this since we need to scale multiple ReplicaSets at the same time.

**Comment by timothysc** [comment]
The only reason that feature existed was due to limitations in v2, it should be deprecated.

**Comment by bgrant0607** [comment]
We're not going to expose multi-resource-type transactions via the API.

**Comment by kargakis** [comment]
@bgrant0607 can we at least leave this open to track transaction on the same resource?

**Comment by snowman39** [comment]
@bgrant0607 Hi, May I ask you what the fair reason was for Kubernetes' decision not to expose multikey transactions via the API?

**Comment by bgrant0607** [comment]
@snowman39 

The reason to not support transactions across resource types is that we want to be able to shard by resource type to scale the system. This is commonly done with events and some cases where this is applied to other high-churn resources, such as CRDs, Pods, Nodes, and Leases.

The reason to not support transactions within a resource type, such as Pod, is the potential impact on clients. Kubernetes uses the Etcd sequence number in the resourceVersion as a watch bookmark. Currently each resource receives a unique value upon creation and update. It is unknown whether using the same value would break any clients in the ecosystem.

Another issue is whether there would need to be an API for observing multi-resource transactions, particularly in the case of multiple resources types. Existing clients would not be able to observe the transactional behavior explicitly, so they'd still perceive the changes to be independent in some arbitrary order, which may or may not be ok.
