### ISSUE TITLE
find a cleaner alternative for salt configs on distros that do not support salt

### ISSUE THREAD

**Issue by adityakali** [kubernetes/kubernetes#27547]
Kubernetes maintains most of the node/master configuration as jinja templates at https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt. These templates are evaluated using saltstack on the nodes. This requires that the distro running on the nodes support python and jinja evaluators.
This is undesirable for several reasons:
1. the syntax is complex and difficult to maintain (example: https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest)
2. node OS (like GCI and CoreOS) find it undesirable to support salt (mainly because of heavy dependency on several python modules - https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/salt/salt-2015.8.8.ebuild#n29)

Current status:
1. CoreOS:
   (This is just my understanding, but coreos devs can comment here)
   CoreOS today has forked the templates and maintain their own manifests - https://github.com/kubernetes/kubernetes/tree/master/cluster/gce/coreos/kube-manifests
   This has drawback that they don't support all k8s features and so cannot pass all tests.
2. GCI
   In order to be backwards compatible to old containervm and to support all tests, GCI adopted to resolve existing salt templates using 'sed' commands - https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L567.
   This is ugly and keeps breaking and no one wants to do this.
   (Please add if any other distros have any other concerns w.r.t. salt).

The purpose of this bug is two fold:
1. If not salt, what should be the other (hopefully simpler and cleaner) way to specify node configuration
2. Figure out how to migrate existing salt configurations to the new way

I had a brief meeting with @dchen1107 and @mikedanese last week about this. Options discussed in that meeting were:
1. Do the salt config evaluation locally (rather than on remote k8s node) -- this may not be possible in certain cases where or node specific info is needed (like ipaddress or hostname, etc).
2. Use some other template mechanism and evaluator ... preferably one with statically linked binary evaluator. This can be provided in a container  or as-is alongwith other kubernetes packages. And the host simply runs it during setup. https://github.com/google/jsonnet was suggested.

@kubernetes/goog-node @roberthbailey @dchen1107 @mikedanese @kubernetes/sig-cluster-lifecycle

**Comment by mikedanese** [comment]
cc @bgrant0607 @sparkprime @aaronlevy This issue is about sharing addon and static pod manifests between all the different deployment automation. To do this we need to pick a friendlier configuration process for distros that don't use salt or package python.

cc @bgrant0607 @sparkprime @aaronlevy

**Comment by dchen1107** [comment]
cc/ @matchstick too since we briefly talked about node specification yesterday.

**Comment by bgrant0607** [comment]
Is this primarily about node configuration, or also about master configuration?

What kinds of information needs to be configurable?

Has anyone thought about approaches that wouldn't require substitution?

See also:
* #23174 
* https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/cluster-deployment.md
* https://github.com/kubernetes/kube-deploy/tree/master/min-turnup
* https://github.com/kubernetes/kube-deploy/tree/master/upup
* https://github.com/kubernetes/community/wiki/Roadmap:-Cluster-Deployment
