### ISSUE TITLE
apiserver leaks memory?

### ISSUE THREAD

**Issue by sols1** [kubernetes/kubernetes#27556]
apiserver memory usage increases linearly to >400 MB in 2 days:

<img width="1032" alt="screen shot 2016-06-16 at 10 33 37 am" src="https://cloud.githubusercontent.com/assets/17886050/16126827/b029d112-33ae-11e6-9e88-a9ae451c42cc.png">

This is a cluster with just 2 nodes and minimal activity over 2 days. 

kubernetes version ~1.3

This is an example - I observed similar behavior multiple times.

**Comment by lavalamp** [comment]
Can you try setting --deserialization-cache-size to a small value?

**Comment by sols1** [comment]
Did I just not wait long enough?

It looks like the slop decreases after 2 days:

<img width="1031" alt="screen shot 2016-06-20 at 11 50 32 am" src="https://cloud.githubusercontent.com/assets/17886050/16206522/a7aebd40-36dd-11e6-9cbe-7fd8c56f63ba.png">

**Comment by sols1** [comment]
It looks like after several days the memory consumption by api server stabilizes in the 500-600 MB range, so closing this.

<img width="1017" alt="screen shot 2016-06-30 at 9 58 29 am" src="https://cloud.githubusercontent.com/assets/17886050/16496994/a348a698-3ea9-11e6-9e0b-c8f1d195f82f.png">

**Comment by ddysher** [comment]
@sols1 Did you observe the stability via setting --deserialization-cache-size?  We are running quite a few small clusters, and almost all of them stops working due to api-server stop responding; and it seems like api server eats most memory. (and start using swap)

@lavalamp master memory is 1GB with 2 nodes.  Is it too small?  It's simple to just bump the memory, but want to know if there is any memory leaks.  k8s version 1.2.4

```
Tasks:  95 total,   2 running,  93 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.4 us,  1.0 sy,  0.0 ni,  0.0 id, 97.6 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   1017896 total,   953996 used,    63900 free,     3560 buffers
KiB Swap:  1048572 total,   534108 used,   514464 free.    43852 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                      
 7036 root      20   0  923732 587668    208 S  1.0 57.7 460:30.10 kube-apiserver                                                                                                                                                                                               
 2260 root      20   0  175972  16208   1340 S  0.3  1.6 251:59.38 etcd                                                                                                                                                                                                         
 2268 root      20   0  696756  23088   7624 S  0.3  2.3 311:47.78 kubelet                                                                                                                                                                                                      
 2497 root      20   0  818632  21956   4660 S  0.3  2.2 462:17.50 docker                                                                                                                                                                                                       
 2718 root      20   0  698368  55908   1892 S  0.3  5.5 238:14.46 td-agent                                                                                                                                                                                                     
    1 root      20   0   33752   1436    688 S  0.0  0.1  23:24.29 init                                                                                                                                                                                                         
```

**Comment by lavalamp** [comment]
Check the deserialization cache flag setting-- set it smaller for small
masters. Memory usage will grow until that cache is full.

**Comment by sols1** [comment]
@ddysher I did't have time to test `--deserialization-cache-size`.

I doubt you can get stable operation with just 1GB.

**Comment by ddysher** [comment]
Thanks @sols1 @lavalamp  I'll see if that helps.
