### ISSUE TITLE
Test Flake Exit Criteria: Postsubmit requirements

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#27579]
From the [doc shared with kubernetes-dev mailing list](https://docs.google.com/document/d/1jnGRrZymgnXoVUNnZVER_TOKH_Z11VvsKxlLxU1gg0A/)

Post-submit tests must not test things that are not tested by presubmit tests. Postsubmit tests _may_ test things that take lots of resources.
- Good example: kubemark-5 in presubmit, kubemark-500 in postsubmit.
- Bad example: both of the above as a postsubmit.

**Comment by spiffxp** [comment]
/close
We're taking another stab at this by defining the criteria for release-blocking, since we no longer block the queue on postsubmits.  See https://github.com/kubernetes/sig-release/issues/24
