### ISSUE TITLE
Change in salt from merged PR isn't making it into releases.

### ISSUE THREAD

**Issue by matjohn2** [kubernetes/kubernetes#27575]
Hi All, 
Just noticed changes merged to the cni salt automation arent making it into the cni.sls file in any of the tagged releases.

Is this normal?

Commit in question: https://github.com/kubernetes/kubernetes/commit/ce220836c38aefc3c23055643ef9da1dae373316#diff-0c1826ac28b55a46c642c8dd403c1ffc

**Comment by lavalamp** [comment]
It should go into release 1.3? If you think it should be cherrypicked in previous releases, you'll have to make a cherrypick PR.
