### ISSUE TITLE
Update cadvisor godep for kubernetes 1.3 release

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#27573]
We have to update cadvisor to the latest cherrypick release to include the following fixes:

   - Check for thin_is binary in path for devicemapper when using ThinPoolWatcher
   - Fix uint64 overflow issue for CPU stats
   - Cap the maximum consecutive du commands	
   - Fix a panic when a prometheus endpoint ends with a newline

**Comment by dchen1107** [comment]
cc/ @kubernetes/sig-node @pmorie @timstclair @Random-Liu

**Comment by goltermann** [comment]
@dchen1107 Please close if the cadvisor version bump was all we needed.
