### ISSUE TITLE
node e2e test teardown crashes with nil deref if node services could not be started

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#27582]
In `/test/e2e_node/e2e_node_suite_test.go`, the node services are started in the `BeforeSuite` logic. If they fail to start, ginkgo's `Fail` function is called, which ultimately initiates test tear down and thus the `AfterSuite` logic in the same file.

The `AfterSuite` logic calls `e2es.stop()` (defined in `test/e2e_node/e2e_service.go`), which will try to e.g. `es.stopService(es.kubeletCmd)`, where `es` is the `e2eService` and `kubeletCmd` is the `*killCmd` for the kubelet service. 

Unfortunately, because the service failed to start, this pointer is nil, and we get a nil pointer dereference in the `Kill` function (in `test/e2e_node/e2e_service.go`). 

Off the top of my head, I see two potential solutions to this problem.

1. Pre-allocate default `killCmd` structs on the `e2eService` struct created in the `newE2eService` function in `test/e2e_node/e2e_service.go`. We could just make `killCmd.cmd = nil` on these, because the assumption appears to be that if `killCmd.cmd == nil`, the service is not running. (It appears that prior to the addition of `killCmd`, a nil `cmd` was interpreted as 'service not running,' and that this `cmd` field got rolled into `killCmd`, see 66d74f969dbbde894949b87366d215e020167faf).
2. Or, simply add an additional check to the `Kill` function, where we assume that if the `killCmd` is `nil`, the respective service is not running.

Thoughts? I want to make sure I'm not missing something here.

@timstclair because you added teardown code in 66d74f969dbbde894949b87366d215e020167faf
@euank because you added `killCmd` in 34996f1b84104a83033fb62cec72ec86f9eef8c1

Note: Tim is on vacation so I'm not really expecting a response from him.

**Comment by euank** [comment]
Either of those solutions sounds reasonable with a slight preference for the first.

Is this causing actual pain/problems somewhere? Ofc we should fix it, but since this only happens in failure scenarios it's not critical, right?

**Comment by mtaufen** [comment]
Right, non-critical, you pretty much have to break something else to see this show up. I noticed it when I broke the kubelet on a branch I'm currently working on. 

I'm also leaning towards the first fix, imo if something else causes the killCmd to be nil by the time we tear down, we'll want to see that there's a problem. I'll put together a PR with that change.

**Comment by lavalamp** [comment]
IMO you should handle cleanup like this by `defer`ing a call to the cleanup command (if it is possible).

**Comment by mtaufen** [comment]
Reopened wrt @lavalamp's suggestions. PR coming soon.
