### ISSUE TITLE
Docker's log level isn't set to warning on GCI

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#27584]
It's set to warning on containervm to avoid all the unnecessary log spam it generates (and hence the CPU that it wastes):
https://github.com/kubernetes/kubernetes/pull/15728
https://github.com/kubernetes/kubernetes/issues/15590
https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/docker/docker-defaults#L13

@andyzheng0831 @adityakali

**Comment by adityakali** [comment]
Docker daemon args are assembled at https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L271

**Comment by dchen1107** [comment]
We need to address this for release otherwise, the master node will run out of disk very quickly.
