### ISSUE TITLE
Test Flake Exit Criteria: retest succeeds 95% of the time

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#27581]
When the merge queue initiates a retest, that should succeed 95% of the time. If that number falls below 80% (3d rolling window average), a human will be paged. The human's job is then to escalate issues as necessary until the flakes have been fixed.

https://docs.google.com/document/d/1jnGRrZymgnXoVUNnZVER_TOKH_Z11VvsKxlLxU1gg0A/edit#

Additionally:
- Percentage of the time during which a merge is possible (post submit tests are not broken)
  - 24h rolling window
  - 90% is the target. < 60% means page.

**Comment by lavalamp** [comment]
test-infra is on the hook for measuring this, but the rest of us are on the hook for actually fixing things.

**Comment by dims** [comment]
@lavalamp This has been a p0 for about 5 months. is it still valid? should this be assigned to someone?

**Comment by lavalamp** [comment]
I guess I will downgrade this since no one is doing anything about it :(

**Comment by dims** [comment]
@lavalamp unfortunately... thanks!
