### ISSUE TITLE
Kubelet times out docker container logs after 2 minutes

### ISSUE THREAD

**Issue by csrwng** [kubernetes/kubernetes#27588]
When streaming logs to a client of a long-running pod, the log will be closed after 2 minutes with

```
net/http: request canceled
```

In the kubelet docker client, a default context (with 2 min timeout) is created for the Logs call:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/kube_docker_client.go#L339

**Comment by csrwng** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
I would not expect all logs calls to be always terminated after 2 minutes.

**Comment by smarterclayton** [comment]
@dchen1107

**Comment by dchen1107** [comment]
Yes, this is a regression issue for usability aster switching to docker client library. Will fix it shortly.

**Comment by dchen1107** [comment]
Should we not give any timeout value for all log calls or only streaming ones?

**Comment by smarterclayton** [comment]
Good point - probably only streaming ones.  Regular log calls being limited
to 2 minutes doesn't worry me.
