### ISSUE TITLE
Volume Operation Executor Should Generate Events

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#27590]
The volume operation executor (which executes Attach/Detach/Mount/Unmount operations) logs errors, but that is hard for users to discover. Instead, these operations should generate `Events` on failure (and maybe even success). So if a pod fails to start, the user can look at the events and see the error for that particular volume.

**Comment by AdoHe** [comment]
SGTM.

**Comment by pmorie** [comment]
@screeley44 this is the issue we have been discussing.

**Comment by screeley44** [comment]
@saad-ali - I am about to push up a PR with what I think might fix this, but not sure I implemented correctly, will let you know when I have it up there but wanted to give a heads up that I was poking around on this one as this being broken ruins all the volume mount error handling UXP I've been working on
