### ISSUE TITLE
Build failing in the first step

### ISSUE THREAD

**Issue by prashantabkari** [kubernetes/kubernetes#27601]
Hi - I have downloaded kubernetes and trying to install it by running make release. It is flagging below error. Since i am working behind a proxy, i changed the proxy by following the recommendation mentioned in https://github.com/kubernetes/kubernetes/issues/5706 but after running make release the Dockerfile gets overwritten. 

Error seen is 
+++ [0617 11:02:32] Verifying Prerequisites....
+++ [0617 11:02:39] Building Docker image kube-build:build-69d554a524.
+++ Docker build command failed for kube-build:build-69d554a524

Sending build context to Docker daemon 41.81 MB
Step 1 : FROM gcr.io/google_containers/kube-cross:v1.6.2-2
Get https://gcr.io/v1/_ping: dial tcp 74.125.206.82:443: i/o timeout

To retry manually, run:

docker build -t kube-build:build-69d554a524 --pull=false /home/abkari/Downloads/kubernetes/_output/images/kube-build:build-69d554a524

!!! Error in build/../build/common.sh:534
  'return 1' exited with status 1
Call stack:
  1: build/../build/common.sh:534 kube::build::build_image(...)
  2: build/release.sh:32 main(...)
Exiting with status 1
make: *** [release] Error 1

**Comment by lavalamp** [comment]
You can try setting a [proxy env var](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=proxy%20environment%20variable) but if that doesn't work you're probably on your own, our build scripts assume you can talk to the internet...
