### ISSUE TITLE
CNI flannel plugin doesn't work with kubernetes

### ISSUE THREAD

**Issue by zreigz** [kubernetes/kubernetes#27603]
The issue is also created here https://github.com/containernetworking/cni/issues/250 with detailed description how to reproduce and test it.

**Comment by zreigz** [comment]
cc @bprashanth

**Comment by zreigz** [comment]
I just verify it with the newest k8s. It seems to work fine. I close the issue

**Comment by cheld** [comment]
@freehan, @luxas 

I have tested hyperkube v1.3.0-beta.1. The cni-flannel plugin is not working properly.

After upgrading to latest version of CNI (build from master) everything works fine. 

How can upload the latest release of CNI?

@zreigz please reopen

**Comment by freehan** [comment]
Since the current one has been tested for quite some time and 1.3 release is close, we plan to update CNI after 1.3 release. 
Can you work around the problem by overwriting the cni binary for now?

**Comment by luxas** [comment]
@freehan I think we can do it right after v1.3, and we'll validate the new release with docker-multinode then.

**Comment by cheld** [comment]
@freehan can you update 

https://storage.googleapis.com/kubernetes-release/network-plugins/cni-${CNI_RELEASE}.tar.gz 

with the latest cni release?

Is there are reason why we are not using the official URL?

https://github.com/containernetworking/cni/releases/download/v0.3.0/cni-v0.3.0.tgz

**Comment by freehan** [comment]
Let me double check if 0.3.0 included some required fixed and come back.

**Comment by freehan** [comment]
The following two fixes are not in 0.3.0. Need at least one of them to fix a major problem. See https://github.com/kubernetes/kubernetes/issues/24953  I will update the binary with HEAD. 

https://github.com/containernetworking/cni/pull/237
https://github.com/containernetworking/cni/pull/254

**Comment by luxas** [comment]
@freehan When are you going to update CNI?
Also, at which commit?

**Comment by freehan** [comment]
@luxas Since it is post 1.3 release, I am doing it at current HEAD (8a936732094c0941e1543ef5d292a1f4fffa1ac5). 
see #28799

**Comment by nhlfr** [comment]
Can we close this or this issue still occurs?

**Comment by cheld** [comment]
You can close
