### ISSUE TITLE
e2e flake: "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#27612]
In gke-large-cluster suite, two tests failed for me with the following error:
"Unable to connect to the server: x509: certificate signed by unknown authority"

```
01:39:45   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubeproxy.go:107
01:39:45 
01:39:45   Expected error:
01:39:45       <*errors.errorString | 0xc8211d8480>: {
01:39:45           s: "Error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://8.35.199.16 --kubeconfig=/workspace/.kube/config exec --namespace=e2e-tests-e2e-kubeproxy-rew7e host-test-container-pod -- /bin/sh -c for i in $(seq 1 5); do echo 'hostName' | timeout -t 3 nc -w 1 -u 10.38.215.4 8081; echo; sleep 1s; done | grep -v '^\\s*$' |sort | uniq -c | wc -l] []  <nil> Please enter Username: Please enter Password:  Unable to connect to the server: x509: certificate signed by unknown authority\n [] <nil> 0xc82358a460 exit status 1 <nil> true [0xc820dd1790 0xc820dd17a8 0xc820dd17c0] [0xc820dd1790 0xc820dd17a8 0xc820dd17c0] [0xc820dd17a0 0xc820dd17b8] [0xa7bfc0 0xa7bfc0] 0xc820ffafc0}:\nCommand stdout:\nPlease enter Username: Please enter Password: \nstderr:\nUnable to connect to the server: x509: certificate signed by unknown authority\n\nerror:\nexit status 1\n",
01:39:45       }
01:39:45       Error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://8.35.199.16 --kubeconfig=/workspace/.kube/config exec --namespace=e2e-tests-e2e-kubeproxy-rew7e host-test-container-pod -- /bin/sh -c for i in $(seq 1 5); do echo 'hostName' | timeout -t 3 nc -w 1 -u 10.38.215.4 8081; echo; sleep 1s; done | grep -v '^\s*$' |sort | uniq -c | wc -l] []  <nil> Please enter Username: Please enter Password:  Unable to connect to the server: x509: certificate signed by unknown authority
01:39:45        [] <nil> 0xc82358a460 exit status 1 <nil> true [0xc820dd1790 0xc820dd17a8 0xc820dd17c0] [0xc820dd1790 0xc820dd17a8 0xc820dd17c0] [0xc820dd17a0 0xc820dd17b8] [0xa7bfc0 0xa7bfc0] 0xc820ffafc0}:
01:39:45       Command stdout:
01:39:45       Please enter Username: Please enter Password: 
01:39:45       stderr:
01:39:45       Unable to connect to the server: x509: certificate signed by unknown authority
01:39:45       
01:39:45       error:
01:39:45       exit status 1
01:39:45       
01:39:45   not to have occurred
01:39:45 
01:39:45   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:3449
```

Those errors come from:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gke-large-cluster/51/console

@zmerlynn

**Comment by fejta** [comment]
Assigning to people based on thread activity. Please help reassign this correctly!

**Comment by wojtek-t** [comment]
@cjcullen @roberthbailey @kubernetes/goog-gke 

ping - this just happened again in gke-serial:
http://kubekins.dls.corp.google.com:8080/view/Critical%20Builds/job/kubernetes-e2e-gke-serial/1599/

**Comment by wojtek-t** [comment]
@davidopp @erictune

**Comment by cjcullen** [comment]
#28034 should fix this.

**Comment by cjcullen** [comment]
I'm seeing another x509 failure in gke-serial: https://github.com/kubernetes/kubernetes/issues/27537#issuecomment-228630948

**Comment by zmerlynn** [comment]
This seems to be fixed. Please reopen if not?

**Comment by cjcullen** [comment]
Finally got inside a running Jenkins VM for this. Here's what the kubecfg file looks like:
```
# cat ~/.kube/config 
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users:
- name: gke_jenkins-gke-e2e-serial_us-central1-f_jenkins-e2e
  user:
    auth-provider:
      config:
        access-token: <redacted, but valid>
        expiry: 2016-06-27T18:27:47.859578747-07:00
      name: gcp
```

**Comment by cjcullen** [comment]
I looked at the ModifyConfig code closer, and it is doing inidividual writes for each section of the kubeconfig. That now means that some sections can succeed, while others fail (because the file is being locked). We should be able to fix this by batching up the writes for each possible destinationFile and issuing a single `WriteToFile` per file at the end of `ModifyConfig`.

**Comment by krousey** [comment]
To be fair, this could happen before the file locking too. The file locking just adds another failure path, but prevents corruption.

**Comment by cjcullen** [comment]
@krousey: Agreed.

I think #28197 should prevent the token refresh case from causing kubeconfig data loss. We still won't have a fully parallelizable ModifyConfig, but that is lower priority.

**Comment by cjcullen** [comment]
Made a new PR #28232 to address comments from #28197.

**Comment by krousey** [comment]
@cjcullen can this be closed now?

**Comment by cjcullen** [comment]
I believe so. #28232 has been merged, and gke-serial has had 6 greens in a row since that (hopefully I'm not jinxing it).
