### ISSUE TITLE
e2e flake: "e2e PR builder timed out"

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#27615]
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/45191/consoleFull

Unfortunately we don't have logs.

@fejta @ixdy - can you please take care of uploading logs in case of timeout?

**Comment by fejta** [comment]
@wojtek-t  Which logs are missing from https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/27220/kubernetes-pull-build-test-e2e-gce/45191? The cluster logs?

**Comment by ixdy** [comment]
yeah, this is still kubernetes/test-infra/issues/79.

**Comment by wojtek-t** [comment]
Oh yeah - it's duplicate of https://github.com/kubernetes/test-infra/issues/79 - thanks @ixdy for pointing on it.
