### ISSUE TITLE
/usr/lib/golang/pkg/tool/linux_arm64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

### ISSUE THREAD

**Issue by vanloswang** [kubernetes/kubernetes#27614]
```bash
# go version
```
go version go1.6.2 linux/arm64
```bash
#go env
```
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

Just build k8s 1.2.0 on aarch64 platform on CentOS aarch64 edition and give the error as follow:
Go version: go version go1.6.2 linux/arm64
+++ [0616 15:45:17] Building go targets for linux/arm64:
cmd/hyperkube
cmd/kube-apiserver
*# k8s.io/kubernetes/cmd/hyperkube
/usr/lib/golang/pkg/tool/linux_arm64/link: running aarch64-linux-gnu-gcc failed: fork/exec /usr/bin/aarch64-linux-gnu-gcc: cannot allocate memory

!!! Error in /home/ws/rpmbuild/BUILD/ose-738b7603b042dcda7a5ba419ab0e7f40a617080c/hack/lib/golang.sh:423
'go build -o "${outfile}" "${goflags[@]:+${goflags[@]}}" -ldflags "-B 0x$(head -c20 /dev/urandom|od -An -tx1|tr -d ' \n') ${goldflags}" "${binary}"' exited with status 2
Call stack:
1: /home/ws/rpmbuild/BUILD/ose-738b7603b042dcda7a5ba419ab0e7f40a617080c/hack/lib/golang.sh:423 kube::golang::build_binaries_for_platform(...)
2: /home/ws/rpmbuild/BUILD/ose-738b7603b042dcda7a5ba419ab0e7f40a617080c/hack/lib/golang.sh:576 kube::golang::build_binaries(...)
3: hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in /home/ws/rpmbuild/BUILD/ose-738b7603b042dcda7a5ba419ab0e7f40a617080c/hack/lib/golang.sh:496
'kube::golang::build_binaries "$@"' exited with status 1
Call stack:
1: /home/ws/rpmbuild/BUILD/ose-738b7603b042dcda7a5ba419ab0e7f40a617080c/hack/lib/golang.sh:496 kube::golang::build_binaries(...)
2: hack/build-go.sh:26 main(...)
Exiting with status 1
error: Bad exit status from /var/tmp/rpm-tmp.OphhgA (%build)

RPM build errors:
Bad exit status from /var/tmp/rpm-tmp.OphhgA (%build)

**Comment by vanloswang** [comment]
CC https://github.com/golang/go/issues/16082

**Comment by davecheney** [comment]
You need to add some swap, Linux won't use it, but if no swap is configured the kernel will not permit any over allocation of memory.

**Comment by vanloswang** [comment]
@davecheney Thanks, setup swap to 2GB size works for me. compile k8s will take more than 2GB memory.

**Comment by davecheney** [comment]
Compiler memory usage should be better in go 1.7.
