### ISSUE TITLE
RFE: Inter-pod signaling on cohort life-cycle events.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#27624]
**Motivation:** 
As a distributed systems designer who would like to create a "better batch" system atop of kubernetes, I would like to be able to create my own master-worker model using kubernetes concepts to sustain an overall higher throughput.

**Background:**
In traditional batch systems there is often the notion of "claim re-use".   Traditional batching will typically have a queue which can sometimes be several orders of magnitude greater then the resources provided, and in order to maximize overall throughput designers tend to avoid unnessary scheduling and other lifecycle events.  Other systems often refer to this as "claim-reuse".  Your job has been matched to a machine, and once it is finished another is ready to follow behind it without going through scheduling etc. 

**RFE Requirements:** 
Leveraging kubernetes co-scheduling, I would like to schedule a pod to a machine where one of the members of the pod is actually a worker to be executed.  I would like to denote via spec, that a given container should be signaled on life-cycle changes to any changes in the cohort, and could potentially augment some of the parameters of the next container to be run.    The specifics of both the events and interactions are still TBD. 

**High level example use cases:** 
- Large DAGs whose executions are pleasingly parallel
- Iterative machine learning

/cc @kubernetes/sig-node @jayunit100 @rrati @jeremyeder @sdminonne

**Comment by timothysc** [comment]
@k82cn - fyi, previous thoughts here a while ago.

**Comment by k82cn** [comment]
ack, let me check it :).

**Comment by timothysc** [comment]
I still think this is a useful thing.

**Comment by k82cn** [comment]
Agree, I'd like to make k8s as a basic for "batch job" too. There're also some requirements from customers that one platform for all workloads, e.g. service, batch job; and build dedicated cluster for special requirements if any.

xref https://github.com/kubernetes/features/issues/269
