### ISSUE TITLE
Add e2e test that federated servicecontroller recreates deleted services in underlying clusters

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#27623]
As mentioned in https://github.com/kubernetes/kubernetes/pull/27587#discussion_r67451976 when the service is deleted from the underlying cluster, the controller should recreate it, but it does not.

Below's a transcript.  `ukc` is talking to the federation-apiserver, and `kc` is talking to the normal cluster it's pointed at.

``` console
% tee >(cat) < ../data.kubernetes/cluster.yaml| ukc create -f -
apiVersion: federation/v1alpha1
kind: Cluster
metadata:
  name: federation-e2e-gce-us-central1-f
spec:
  secretRef:
    name: federation-e2e-gce-us-central1-f
  serverAddressByClientCIDRs:
  - clientCIDR: 0.0.0.0/0
    serverAddress: https://130.211.176.7
cluster "federation-e2e-gce-us-central1-f" created

% tee >(cat) < ../data.kubernetes/service.yaml| ukc create -f -
apiVersion: v1
kind: Service
metadata:
  name: e2e-foo
spec:
  selector:
    foo: bar
  ports:
    - name: portname1
      port: 80
      targetPort: svc1
    - name: portname2
      port: 80
      targetPort: svc2

service "e2e-foo" created

% ukc get services -oname
service/e2e-foo

% kc get services -oname
service/e2e-foo
service/kubernetes

% kc delete service e2e-foo
service "e2e-foo" deleted

% kc get services -oname -w
krun: Using _output/dockerized/bin
service/kubernetes
^C%
```

**Comment by nikhiljindal** [comment]
Thanks for catching this @mml 
cc @kubernetes/sig-cluster-federation

**Comment by quinton-hoole** [comment]
cc @mfanjie

**Comment by quinton-hoole** [comment]
This is definitely a bug, but I think that we can kick it out into v1.4.  Until fixed (i.e. while in beta), we can tell customers not to delete the underlying services in their clusters.

**Comment by mfanjie** [comment]
it should not be, I have tested this before. How long did you wait when you check the service existence in last step? Can you send me the logs? 

The service deletion will cause federation service update, and then the federation service watcher will catch the update even and call another round of service updates to all clusters.

When you delete the service, if the service got ingress ip already? I am thinking if the deletion did not trigger federation service update? So so no update event generated..

**Comment by quinton-hoole** [comment]
@mfanjie @mml I think that the best way forward will be to encode this in a reproducible e2e test, otherwise there are too many variables to debug effectively.  @mfanjie It's great to know that you've tested this case, and it works in at least some scenarios.

**Comment by mfanjie** [comment]
@quinton-hoole one possible solution come into my mind, currently we set the service full sync time to 10 minutes `serviceSyncPeriod = 10 * time.Minute`, if we change it back to 30s, then at least during the full sync, the deleted service will be re-created.
I will send a PR anyway, you can judge if it should be put to v1.3

**Comment by quinton-hoole** [comment]
@mfanjie I think we need to find and fix the underlying problem, not cover it up with a shorter sync period.  If we have the correct watch on each service, we will be notified as soon as they are deleted.  Why is the watch notification not firing correctly?

**Comment by quinton-hoole** [comment]
Keeping this open until we've verified this fix in e2e tests.

**Comment by quinton-hoole** [comment]
I believe this to be fixed, but we still lack an e2e test to verify conclusively.  @mml would you like to take this on along with the other e2e tests that you are busy adding?

**Comment by quinton-hoole** [comment]
ping @mml

**Comment by goltermann** [comment]
@mml @quinton-hoole plan on doing this for 1.4?  or bump to 1.5?

**Comment by quinton-hoole** [comment]
Yes, 1.5 is fine.

**Comment by dims** [comment]
@quinton-hoole switching this to 1.6 as it's too late for 1.5. ok?

**Comment by ethernetdan** [comment]
Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.
