### ISSUE TITLE
Support `--image-family` in GCE cluster creation

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/kubernetes#27629]
The `gcloud compute instances create` and `gcloud compute instance-templates create` commands both support the flag [`--image-family`](https://cloud.google.com/compute/docs/images#image_families), which allows creating instances with the latest image in a family. This makes it easier to update default OS images as you don't have to update the hardcoded image name any more.

Is this in the plan?

**Comment by fejta** [comment]
@bgrant0607 do the cluster/up scripts fit under CSI? See https://github.com/kubernetes/kubernetes/pull/27083#issuecomment-226879027 for some additional discussion about this -- we want a `KUBE_GCE_MASTER_IMAGE_FAMILY` to take precedence over `KUBE_GCE_MASTER_IMAGE`

**Comment by bgrant0607** [comment]
@fejta This is cluster lifecycle, which currently has an area label rather than a team label. Applied ux and node team labels for now.

**Comment by roberthbailey** [comment]
At this point I don't see us implementing this feature request for GCE's kube-up scripts since we haven't done it in the past year.
