### ISSUE TITLE
Using kubernetes to build kubernetes

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#27631]
Allow myself to introduce myself.  

All joking aside, this needs to happen, and we should track progress and make it a deliverable.  

/cc @kubernetes/sig-testing @jayunit100

**Comment by justinsb** [comment]
I think we should also replace our build system with bazel, and I think it is within reach:  https://github.com/bazelbuild/rules_go/issues/15#issuecomment-226757589

I was able to build a docker container of a small controller of mine, with vendored golang dependencies, with no need for docker-in-docker.  Creating the BUILD files for the dependencies was tedious but I think can be easily automated.

**Comment by spxtr** [comment]
I played around with this and got to the point where I could automatically trigger builds: https://github.com/spxtr/test-infra/tree/ciongke/ciongke

This is definitely something I'm interested in working on.

I'm not a huge fan of bazel until it's more mature. The go tool is smart enough to do incremental builds.

**Comment by luxas** [comment]
+100, If we get an easy way to test Kubernetes on an existing cluster, it will be soo much easier to set up distributed testing (for non-amd64 arches in my case)

**Comment by lavalamp** [comment]
The go tool is not smart enough to do things like automatically build the generated code...

**Comment by spxtr** [comment]
We're building and testing kubernetes on kubernetes with bazel. There's more to do, of course, but I think we can close this.

**Comment by timothysc** [comment]
@spxtr doc, or it didn't happen ;-)

**Comment by spxtr** [comment]
I could write a doc. All kubernetes bazel build jobs are running in [prow](https://github.com/kubernetes/test-infra/tree/master/prow), on GKE.

**Comment by ixdy** [comment]
It's also on my list to update https://github.com/kubernetes/community/blob/master/contributors/devel/bazel.md.
