### ISSUE TITLE
PetSet controller hot loops on authorization failures and other errors

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#27634]
Testing PetSet in OpenShift where policy is denying creation (just as a verification) I see the PetSetController hot loop forever, which blows up the controller manager.

We should never treat failures as "hotloop", normally this goes into a retry queue or a backoff.  The client retry limit isn't enough.

```
E0617 14:05:05.982113   90122 pet_set.go:267] Error syncing PetSet default/zoo, requeuing: [User "system:serviceaccount:openshift-infra:pet-set-controller" cannot get apps.petsets in project "default"]
I0617 14:05:05.982144   90122 pet_set.go:317] Syncing PetSet default/zoo with 1 pets
I0617 14:05:05.984501   90122 pet_set.go:325] PetSet zoo blocked from scaling on pet zoo-0
I0617 14:05:05.995782   90122 pet.go:101] PetSet zoo waiting on unhealthy pet zoo-0
I0617 14:05:06.008899   90122 pet.go:106] Create of zoo-1 in PetSet zoo blocked by unhealthy pet zoo-0
I0617 14:05:06.020767   90122 pet.go:106] Create of zoo-2 in PetSet zoo blocked by unhealthy pet zoo-0
I0617 14:05:06.023355   90122 pet_set.go:308] Failed to update replica count for petset default/zoo; requeuing; error: User "system:serviceaccount:openshift-infra:pet-set-controller" cannot get apps.petsets in project "default"
E0617 14:05:06.023368   90122 pet_set.go:267] Error syncing PetSet default/zoo, requeuing: [User "system:serviceaccount:openshift-infra:pet-set-controller" cannot get apps.petsets in project "default"]
I0617 14:05:06.023398   90122 pet_set.go:317] Syncing PetSet default/zoo with 1 pets
I0617 14:05:06.028499   90122 pet_set.go:325] PetSet zoo blocked from scaling on pet zoo-0
I0617 14:05:06.041673   90122 pet.go:101] PetSet zoo waiting on unhealthy pet zoo-0
I0617 14:05:06.054616   90122 pet.go:106] Create of zoo-1 in PetSet zoo blocked by unhealthy pet zoo-0
I0617 14:05:06.067500   90122 pet.go:106] Create of zoo-2 in PetSet zoo blocked by unhealthy pet zoo-0
I0617 14:05:06.070307   90122 pet_set.go:308] Failed to update replica count for petset default/zoo; requeuing; error: User "system:serviceaccount:openshift-infra:pet-set-controller" cannot get apps.petsets in project "default"
E0617 14:05:06.070323   90122 pet_set.go:267] Error syncing PetSet default/zoo, requeuing: [User "system:serviceaccount:openshift-infra:pet-set-controller" cannot get apps.petsets in project "default"]
I0617 14:05:06.070356   90122 pet_set.go:317] Syncing PetSet default/zoo with 1 pets
I0617 14:05:06.074654   90122 pet_set.go:325] PetSet zoo blocked from scaling on pet zoo-0
I0617 14:05:06.088103   90122 pet.go:101] PetSet zoo waiting on unhealthy pet zoo-0
I0617 14:05:06.101371   90122 pet.go:106] Create of zoo-1 in PetSet zoo blocked by unhealthy pet zoo-0
I0617 14:05:06.115373   90122 pet.go:106] Create of zoo-2 in PetSet zoo blocked by unhealthy pet zoo-0
I0617 14:05:06.118198   90122 pet_set.go:308] Failed to update replica count for petset default/zoo; requeuing; error: User "system:serviceaccount:openshift-infra:pet-set-controller" cannot get apps.petsets in project "default"
E0617 14:05:06.118212   90122 pet_set.go:267] Error syncing PetSet default/zoo, requeuing: [User "system:serviceaccount:openshift-infra:pet-set-controller" cannot get apps.petsets in project "default"]
I0617 14:05:06.118240   90122 pet_set.go:317] Syncing PetSet default/zoo with 1 pets
I0617 14:05:06.120950   90122 pet_set.go:325] PetSet zoo blocked from scaling on pet zoo-0
I0617 14:05:06.135342   90122 pet.go:101] PetSet zoo waiting on unhealthy pet zoo-0
```

**Comment by smarterclayton** [comment]
@bprashanth we need to triage this - I don't think it meets the 1.3 bar because of alpha but quota / auth / other failures can bring down the controller manager.

**Comment by smarterclayton** [comment]
@kubernetes/sig-apps @kubernetes/sig-api-machinery

**Comment by bprashanth** [comment]
don't most controllers run into this? we should add backoff to the work queue and this will just fix itself i think

**Comment by bprashanth** [comment]
Ah https://github.com/kubernetes/kubernetes/issues/15095#issuecomment-147462028, so sounds like we should just teach controllers to use the delayed queue addeded in https://github.com/kubernetes/kubernetes/pull/23444

**Comment by smarterclayton** [comment]
Yeah, I *think* some other controllers have explicit backoff protection on failures (scheduler and RC I vaguely recall going through the motions) but delayed queue is the future thing.  As I said I wouldn't block 1.3 on this either.

**Comment by bprashanth** [comment]
I think we should go through and audit the controllers, modify the ones that blindly requeue on error to use the delayed queue instead. Scheduler is probably backing off, but most things written with informer+workqueue are probably not (endpoints, servicecontroller, daemon etc). They'll just GET and queue.Add on error (eg: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L576)

**Comment by bprashanth** [comment]
Oh servicecontroller is backing off with the horrific time.Sleep in a goroutine thing. https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L203

**Comment by smarterclayton** [comment]
:)

**Comment by smarterclayton** [comment]
Namespace controller and quota controller are using the delaying queue
right now (asked Derek).

**Comment by bprashanth** [comment]
@foxish this is a good one to pick up if you're starting with controllers. 
See Ingress controller for an example of how to use this delayed queue (https://github.com/kubernetes/contrib/pull/1285/commits/46b397d6948ea6b87f2fd9535f9fdcb5b6fe23b8) or namespace controller (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/namespace/namespace_controller.go#L50) then modify the controllers that hot loop to use the pattern.

**Comment by foxish** [comment]
@smarterclayton Looking into this now. How does one reproduce this? It seems like this kind of hot-looping only occurs with certain types of failures. I tried triggering `FailedScheduling` and that did not lead to the behavior seen in this bug.

**Comment by smarterclayton** [comment]
The easiest would be to set a quota on pods and try to scale the pet set up
past the quota.  Another option is to deny the pet set controller
permission to access resources, but that's a lot harder since the
controller manager isn't plumbed to have unique client per controller.

**Comment by foxish** [comment]
I think this is resolved now, and can be closed.
