### ISSUE TITLE
Kubernetes DNS not working in some containers

### ISSUE THREAD

**Issue by prasadbsd** [kubernetes/kubernetes#27642]
Hi,

I created a kubernetes cluster with one master and two nodes(etcd + flannel + Kube)

Installed some cluster addons. Trying to make heapster work but having DNS issue.. I was able to install skyDNS but doesnt seem to be working correctly

-> kubectl get svc --all-namespaces
NAMESPACE    NAME    CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
default    kubernetes    10.254.0.1    <none>    443/TCP    1d
kube-system    heapster    10.254.172.226    <none>    80/TCP    3h
kube-system    kube-dns    10.254.0.10    <none>    53/UDP,53/TCP    44m
kube-system    kube-ui    10.254.76.51    <none>    80/TCP    1d
kube-system    kubernetes-dashboard    10.254.197.167    nodes    80/TCP    1d
kube-system    monitoring-grafana    10.254.149.90    nodes    80/TCP    2h
kube-system    monitoring-influxdb    10.254.69.249    <none>    8083/TCP,8086/TCP    2h

SkyDNS seems to be working from busybox container 

-> kubectl    exec    -ti    busybox    --    nslookup    kubernetes
Server:    10.254.0.10
Address    1:    10.254.0.10

Name:    kubernetes
Address    1:    10.254.0.1

-> kubectl    exec    -ti    busybox    --    nslookup    monitoring-influxdb
Server:    10.254.0.10
Address    1:    10.254.0.10

Name:    monitoring-influxdb
Address    1:    10.254.69.249

DNS doesnt seem to work from containers other than busybox .. /etc/resolv.conf has same settings in all containers

error in grafana container not able to access [http://monitoring-influxdb:8086]

2016-06-17T19:40:37.375731367Z 2016/06/17 19:40:37 http: proxy error: dial tcp: i/o timeout

    what am I doing wrong ?

**Comment by jlowdermilk** [comment]
Please post your question to  [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We use github issues to track bugs, feature requests, and proposals. Help/support questions will be responded to much faster on stackoverflow, and you may find someone else has already posted a similar question and found a solution. The Kubernetes team regularly scans stackoverflow and will try to ensure questions don't go unanswered. Thanks.
