### ISSUE TITLE
GCE kube-up: /usr/bin/kubectl is created with mode 744

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#27643]
This means that we have to sudo to run kubectl...  It should be created with 755, not 744

```
justinsb@kubernetes-master ~ $ kubectl get pvc
-bash: /usr/bin/kubectl: Permission denied
justinsb@kubernetes-master ~ $ ls -l /usr/bin/kubectl
-r-xr--r-- 1 root root 55400872 Jun 17 19:44 /usr/bin/kubectl
```

**Comment by roberthbailey** [comment]
This is a regression. It a 1.2.4 master I see 

```
$ ls -l `which kubectl`
-rwxr-xr-x 1 root root 41225728 Jun 20 18:17 /usr/local/bin/kubectl
```

**Comment by roberthbailey** [comment]
@andyzheng0831 - this is likely a result of switching the masters from containervm -> gci. Can you take a look?

**Comment by andyzheng0831** [comment]
sure, I will work on it

**Comment by vishh** [comment]
I don't see any issues with the build/release pipeline. @roberthbailey Thanks for the tip!

**Comment by andyzheng0831** [comment]
I think the problem is at https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure.sh#l142-143. For the kubelet and kubectl built in GCI image, we have the correct permission 755. I will make a change to fix it shortly
