### ISSUE TITLE
The multizone setting in gce.conf is ignored by PersistentVolumeLabel

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#27656]
gce.conf is not even read while building the GCE cloudprovider:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/persistentvolume/label/admission.go#L176

As such, multizone is ignored, and a PV in a zone other than that in which the apiserver is running cannot be created on GCE.

**Comment by justinsb** [comment]
The most important consequence of this bug is #27657.  I propose that if we can work around that we can punt this to 1.4.

**Comment by justinsb** [comment]
Workaround to justify punting in #27553

**Comment by goltermann** [comment]
@justinsb, @quinton-hoole #27533 is merged - is the right thing to keep this open, but move out of v1.3?

**Comment by justinsb** [comment]
I believe so, yes: we have a workaround that avoids the problem - you specify the zone annotations if running multizone.  The dynamic provisioner specifies them automatically, so for most users volumes "just work".  Punting to 1.4

**Comment by jingxu97** [comment]
@justinsb, Could you please let me know what is the status of the bug? It is assigned to me, but I am wondering whether you already worked on it. Also what is the appropriate priority for this issue? Thanks!

**Comment by quinton-hoole** [comment]
No work done on this yet for 1.4 - punting it to the next release, given that we have a workaround.

**Comment by dims** [comment]
@quinton-hoole we have to do it again...punt to 1.6 please?

**Comment by msau42** [comment]
@gnufied, does #40537 fix this issue?

**Comment by gnufied** [comment]
Yes it does. Lets close this one. I will backport the fix.
