### ISSUE TITLE
Pin the nameserver for cluster.local in dnsmasq config

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/kubernetes#27679]
Now that kube-dns is fronted by dnsmasq, I believe there is an opportunity to avoid sending queries to  kube-dns for which it has no expectation of returning an answer, and, conversely, to avoid sending queries to additional general purpose recursive nameservers for cluster service names.
                  
Would it be worth considering configuring dnsmasq in places such as saltbase (https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-dns/skydns-rc.yaml.base#L90) thusly

```
args:
- --cache-size=1000
- --no-resolv
- --server=/cluster.local/127.0.0.1#10053
- --server=8.8.8.8
...
```

using 8.8.8.8 as an example of a general purpose recursive nameserver.  By pinning the kube-dns nameserver at 127.0.0.0#10053 to the domain cluster.local, we unburden it from answering queries for which it has no backing information.  Examples of such queries would be for external hosts on the Internet.  In the same way, for queries not on cluster.local, the server 8.8.8.8 would service the query.  

All this presumes that kube-dns is not a recursive name server itself, capable of resolving queries for hosts on the greater Internet.  I have not read all its code, but I have seen no runtime evidence that it is.

Thoughts on this?

Thanks.

References: dnsmasq man page:  http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

**Comment by luxas** [comment]
@bprashanth @ArtfulCoder @girishkalele

**Comment by ae6rt** [comment]
Ping.

I know people are busy, but I understood that k8s 1.4 has a focus on usability, which this issue plays into.

Many thanks.

**Comment by bprashanth** [comment]
> to the domain cluster.local, we unburden it from answering queries for which it has no backing information

I think the issue here is search path. Today we have:
```
search default.svc.cluster.local svc.cluster.local cluster.local c.kubernetesdev.internal. google.internal
namerserver 10.0.0.10
```
If someone does `nslookup kubernetes` I want a hit on `kubernetes.default.svc.cluster.local`.  Even though `google` is a valid service name and `com` is a valid namespace, if someone does `nslookup google.com` I don't want to cycle through the search path. 

@kubernetes/sig-network

**Comment by girishkalele** [comment]
There was also concern about PTR records which we support in 1.3 - I don't recall if we did testing to see how dnsmasq behaves with the ```--server=/cluster.local/127.0.0.1#10053``` option for PTR records.

**Comment by ae6rt** [comment]
Thank you.  This helps clarify my thinking and questions.

I am running k8s v1.3.

Let me back up a bit.  

Consider this snippet of "kubectl describe <kube dns pod>", showing the dnsmasq container config in an essentially out of the box configuration (https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/cluster/saltbase/salt/kube-dns/skydns-rc.yaml.in#L89)

```
  dnsmasq:
    Container ID:	docker://b8161c7fe1803a20d5ca201224c7691cf6b610890d01ad15a62c04b9e6bf2868
    Image:		gcr.io/google_containers/dnsmasq:1.1
    Image ID:		docker://sha256:d965753679e59e52913edbc2ab7eced430e4eaaa5cc10a8dc7002eadea2b2471
    Ports:		53/UDP, 53/TCP
    Args:
      --cache-size=1000
      --no-resolv
      --server=127.0.0.1#10053
    State:			Running
...
```

running under the jurisdiction of this kubelet invocation

```
 5199 ?        Ssl    0:40 /opt/xoom/apps/kubernetes/bin/kubelet --logtostderr=true --v=0 --api-servers=https://kubernetes:6443 --address=0.0.0.0 --hostname-override=10.2.23.193 --cluster-dns=169.254.8.53 --cluster-domain=cluster.local --kubeconfig=/etc/kubernetes/kubeconfig --network-plugin=cni --network-plugin-dir=/etc/cni/net.d
```

with this /etc/resolv.conf in the dnsmasq container

```
search dev.xoom.com
nameserver 10.2.18.46
nameserver 10.7.113.3
nameserver 10.7.113.2
nameserver 10.7.113.1
options ndots:5
```

Next, consider a busybox container with this /etc/resolv.conf

```
search default.svc.cluster.local svc.cluster.local cluster.local dev.xoom.com
nameserver 169.254.8.53
options ndots:5
```

and this resultant query for some host on the Internet

```
$ kubectl exec busybox -- nslookup api.twitter.com
Server:    169.254.8.53
Address 1: 169.254.8.53 kube-dns.kube-system.svc.cluster.local

Name:      api.twitter.com
Address 1: 199.59.149.232 r-199-59-149-232.twttr.com
Address 2: 199.59.149.199 r-199-59-149-199.twttr.com
Address 3: 199.59.150.41 r-199-59-150-41.twttr.com
Address 4: 199.59.148.87 r-199-59-148-87.twttr.com
```

I'm confused as to why api.twitter.com even resolves.  dnsmasq receives the query, and it has its --no-resolv flag set.  dnsmasq appears to be consulting the nameservers in its /etc/resolv.conf anyway.  I do not see a complete explanation for this here https://github.com/kubernetes/kubernetes/blob/master/build/kube-dns/README.md#inheriting-dns-from-the-node.  

If I can understand how that host resolves, it will help me ask better questions around this issue.

Many thanks.
Mark

**Comment by girishkalele** [comment]
The dnsmasq container will forward entries to the kube-dns container, which consults its local /etc/resolv.conf (all containers in a pod should have the same /etc/resolv.conf I believe), and forwards to the upstream nameservers.

**Comment by ae6rt** [comment]
I see.  My apologies for the misunderstanding.  From my perspective, this issue may be closed, unless someone sees value I cannot.
