### ISSUE TITLE
Resource Advice in Pod Templates

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#2768]
Starting assumption: *Kubernetes should start defaulting to having hard enforcement of pod memory and cpu limits, and requiring pods to make resource requests.*  That's a premise of this issue -- if you disagree with it, let's discuss it in a separate issue.  

If you accept that premise, then pods will have to have resource limits set on them.   But, who should set them?

I think that a lot of people will want to start with a pod spec written by someone else.  I'll call that a template, but in this context I don't mean the pod template that a replication controller uses.

The person who writes the pod template is in the best position to know things like:
  - what the minimum memory usage for the pod is in any reasonable scenario. 
  - what the memory usage is in a "typical scenario".
  - which flags to set on processes to advise them of their memory limits.

The person who instantiates the pod template is in the best position to know if his usage scenario is small, medium, large, etc.

How to split those responsibilities, then?
#### Multiple templates
One approach would be to come up with several templates for different use cases, like this:

Filename `some_java_app_1G.pod.template` contains:
```
{ "kind": "Pod", "apiVersion": "v1beta1", "id": "some-java-app",
   "desiredState": {  "manifest": { "containers": [{
        "image": "some-java-app",
        "command": ["java", "-jar", "some-app.jar","-Xmx", "1G"],
        "memory": "1G",
      }]  }}
```
... and so on for 512MG, 2G, and various sizes.
However, this doesn't take advantage of the continuously adjustable resource limits provided by containers.

#### Parameters to Templates
A template file could declare and document its parameters, perhaps inside comments.  Something like this:

File `some_java_app.pod.template` contains:
```
# Params:
#    MAX_MEM:
#      Type: Bytes
#      Default: 1G
#      MinRecommended: 128MB
#      Description: Container memory limit.
{ "kind": "Pod", "apiVersion": "v1beta1", "id": "some-java-app",
   "desiredState": {  "manifest": { "containers": [{
        "image": "some-java-app",
        "command": ["java", "-jar", "some-app.jar","-Xmx", "$MAX_MEM"],
        "memory": "1G",
      }]  }}
```

then you could use a tool to expand the template like this:
```
ktemplate expand some_java_app.pod.template | kubectl createall
```
which would use the default value or else set your own value:
```
ktemplate expand --set MAX_MEM=2G some_java_app.pod.template | kubectl createall
```
and it could have have warnings:
```
$ ktemplate expand --set MAX_MEM=1M some_java_app.pod.template | kubectl createall
ktemplate: warning: MAX_MEM less than MinRecommended (1G).
```

However, it seems like it is a short step from just substituting variables, to wanting to do computations (e.g. set `-Xmx` to 95% of the container limit).

#### Generator script

To allow for computations in templates, you could make up a DSL, or you could just let people use whatever language they want, like:

File `some_java_app_podmaker.go` contains:
```go
import (
  "flag"
  "fmt"
)
var mem = flag.Int("memory", 1024*1024*1024, "memory limit")
main() {
  fmt.Printf(
`
{ "kind": "Pod", "apiVersion": "v1beta1", "id": "some-java-app",
   "desiredState": {  "manifest": { "containers": [{
        "image": "some-java-app",
        "command": ["java", "-jar", "some-app.jar","-Xmx", "%d"],
        "memory": %d,
      }]  }}
`, 0.9 * mem, mem)
```

and run like this:
`
go run some_java_app.podmaker.go -- --mem 2000000000 | kubectl createall
`
#### Complex systems
Real examples would have multiple pods and replication controllers, and services and such.  How will people share knowledge about how to write more complex config?  How would that integrate with horizontal scaling of pods?  Automatic vertical scaling?

**Comment by smarterclayton** [comment]
Do we need this open still?  I think we've defined most of the pieces of this although we haven't captured the actual philosophy - use requests when writing your software, allow admins to enforce limits (hard or soft) via out of band processes, use auto-sizing to estimate in the absence of info, use rescheduling and cluster info to revise initial estimations, try to avoid over specifying as end user (unless you know for sure).

**Comment by erictune** [comment]
Fine with closing this.

There will be multiple templating systems:
  - Helm Charts
  - OpenShift templates
  - jsonnet [e.g. as used at @Box](https://blog.box.com/blog/kubernetes-box-microservices-maximum-velocity/)

Different ones may have different takes on how to default limits.

Admins may enforce upper limits on limits.  Users should set request=limit if they need best QoS.
Not sure if Guaranteed or Burstable is the best default.  Right now there is not enough pressure to pick one or the other.
