### ISSUE TITLE
Build federation-controller-manager docker image with ca-certificates

### ISSUE THREAD

**Issue by kelseyhightower** [kubernetes/kubernetes#27684]
Current the federation-controller-manager docker images does not include a root ca cert bundle which causes syncing with DNS providers to fail:

```
E0619 04:21:56.993123       1 endpoint_helper.go:88] Failed to sync service: Get https://www.googleapis.com/dns/v1/projects/hightowerlabs/managedZones?alt=json: x509: failed to load system roots and no roots provided, put back to service queue
```

To fix this issue I created my own container image using the following Dockerfile:

```
FROM ubuntu
MAINTAINER Kelsey Hightower <kelsey.hightower@gmail.com>
RUN apt-get update
RUN apt-get install -y ca-certificates
ADD federation-controller-manager /federation-controller-manager
ENTRYPOINT ["/federation-controller-manager"]
```

This resulted in a working image with a root cert bundle. Syncing with the GCE DNS provider now works.

**Comment by quinton-hoole** [comment]
cc: @colhom @nikhiljindal @mml FYI...

**Comment by mml** [comment]
@quinton-hoole I'm willing to grab this tomorrow.

**Comment by quinton-hoole** [comment]
Cool, thanks @mml .  Re-assigning.
