### ISSUE TITLE
`git describe` to semver translation wrong in hack/lib/version.sh

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#27699]
The line in question is https://github.com/kubernetes/kubernetes/blob/527cb50583a2599823e1784b0c35deb1e8ad763a/hack/lib/version.sh#L59

We built a custom version off of v1.2.4. The output of `git describe` is `v1.2.4-1-ge191e9760c2dbd`

After the translation, it became `v1.2.4.1+e191e9760c2dbd`.

It's not a valid semver. Node controller complained about this fact:
```
nodecontroller.go:364] couldn't parse verions "v1.2.4.1+e191e9760c2dbd" of minion: Invalid character(s) found in patch number "4.1"
```
One consequence of this is the node is presumed to not support graceful shutdown (https://github.com/kubernetes/kubernetes/blob/v1.2.4/pkg/controller/node/nodecontroller.go#L365), and every pod deletion resulted in forceful shutdown, which caused a bunch of problems for us.

**Comment by girishkalele** [comment]
Marked as P2 because submitter mentions that **every pod deletion resulted in forceful shutdown, which caused a bunch of problems for us**

**Comment by guoshimin** [comment]
Well we do have a solution (making sure we tag our custom builds), so it's not blocking us. But it might be a problem for others who try to patch Kubernetes. The nasty part is that it's very unintuitive that the forceful shutdown is caused by the incorrect versioning.

**Comment by zmerlynn** [comment]
I'm sorry you ran into this. Yes, bump builds off of true releases don't work with this particular expression. The supported way is to branch the `1.2.5-alpha.0` tag and build that, or something similar, which is the tag we create we branch the release.

I'm closing this for now, because it was never intended to work.

**Comment by guoshimin** [comment]
If it's not supposed to work, it should give the user a big fat error, given that it could lead to such unintuitive consequences.

**Comment by guoshimin** [comment]
@zmerlynn Wouldn't integration tests on versions between releases run into the same problem? How do integration tests ensure that kubelet is built with a semver-compliant version?

**Comment by zmerlynn** [comment]
They build off of `master` or `release-1.3`, etc. The actual tag point for the release is somewhat special.
