### ISSUE TITLE
Federation: Proposal: support snapshotting or mirroring persistent volumes between clusters

### ISSUE THREAD

**Issue by chris-milsted** [kubernetes/kubernetes#27710]
Reading the Ubernetes proposal and specifically with interest in Scenario 4:

"I want to be immune to any single data centre or cloud availability zone outage, so I want to spread my service across multiple such zones (and ideally even across multiple cloud providers)."

I would like to add scenario 5 to also include thinking which covers persistent volumes if these were available across both clusters (via some external storage replication mechanism). This would allow applications to retain state (subject to any asynchronous replication conditions of course) in the case of failover between sites.

Akin to DR and worrying about RTO/RPO.

Comments for @quinton-hoole  . Opening as an issue initially to discuss.

The scenario I have in mind is similar to 4, but it also includes PV/PVC which is replicated between two distant sites (for example London and New York).

I have three assumptions I am making:
1. There is something external to the clusters that is replicating storage between the locations.
2. I am putting the network fail-over out of scope, I am  also assuming that you do have service discover-ability external to the cluster.
3. There is a distributed Source Configuration Management system which is available in all locations and makes globally available deployment yaml files and container images.

So if we had a service which was discover-able externally via a DNS entry at one location where it normally ran:

service1.production.london.example.com

If there is a DR event and we need to restart the service in New York then I am going to assume for now that we could find it at a different location such as:

service1.production.ny.example.com

Assuming that some of the pods for this service are using persistent storage and we want to recover the state by attaching the replicated PV and creating a corresponding PVC at the remote site, then we may need to have a copy of the list of PV's at each location as well as some API call to the control plane that is replication storage to find out what identifier the replicated storage is using for the same PV at each site.

For example, if the PVC for the London storage was backed by a PV with an identifier of 12345, then we could ask the storage replication controller what the corresponding identifer would be in NY, which could be 54321. In this case we would want to update the pod definition to attach the correct PV as part of the deployment.

Thanks

Chris

**Comment by quinton-hoole** [comment]
Thanks for your input @chris-milsted.  Yes, we definitely have some form of data replication/migration on the long-term roadmap for cluster Federation.  Be warned that it's going to be difficult to come up with a general-purpose, performant, reliable data replication model though.

In the mean time however I envisage that multiple datastore-specific mechanisms will emerge from the community.

Lets keep this issue open for future requirements and design discussion.

**Comment by firebook** [comment]
Any one have solution to support this feature without using Federation?
