### ISSUE TITLE
AWS service without ELB (implement PBR)

### ISSUE THREAD

**Issue by Thermus** [kubernetes/kubernetes#27718]
Hello,

I need to make pods reachable from the internet, but I can't use ELBs for that, because I need static IPs. I want to use the elastic IPs for that, but the NAT that happens between the elastic IP and the private IP only translates the IP address, it can not translate the ports. The pods have overlapping ports, so I need to run one pod on each node.
The problem with that is, that the pods that are reachable through elastic IP A need to run on the server that has elastic IP A bound to it. The reason for that is, that the response needs to come from the same node that the request came in on. If that is not the case, the packet is dropped when it is supposed to be routed on the node that the pod runs on. So to fix it, we need policy based routing and track the connections, so the responses are routed over the same network path that the request arrived over.

**Comment by cmluciano** [comment]
@kubernetes/sig-aws-misc
