### ISSUE TITLE
Proposal to enable setting of multiple handlers per probe type

### ISSUE THREAD

**Issue by vefimova** [kubernetes/kubernetes#27723]
Hi, I wonder, is there a reason of having restriction to only one probe handler per probe type (Liveness and readiness) per container? Because it seems reasonable to provide at least possibility to set HTTP or TCP handler (to check endpoint availability) along with exec handler (for application specific checks inside container)? If there are no crucial objections against this, I would like to discuss details here and implement such possibility.

**Comment by girishkalele** [comment]
@vefimova 

The subject of multiple health checks has been discussed before here - https://github.com/kubernetes/kubernetes/issues/21493 - the suggestion was to use sidecar containers to run elaborate health checks triggered by single readiness/liveness check.

See responses from @bgrant0607 @thockin @smarterclayton 
https://github.com/kubernetes/kubernetes/issues/21493#issuecomment-186716990

**Comment by vefimova** [comment]
@girishkalele 

Thanks a lot for explanations, got it. But several more questions:

1. If this way of implementing elaborate health checks is a suggestion for now, is it planned to officially declare it in the nearest time and describe in documentation?
2. Is it restricted somehow/recommended to have sidecar container per worload container or  there can be one sidecar container serving healthchecks of all others in the pod?
3. Is it assumed to use basic health checks for sidecar container itself?
4. I suppose this must be used as a reference/example https://github.com/kubernetes/contrib/tree/master/exec-healthz?

**Comment by vefimova** [comment]
cc @kubernetes/kubelet Hey guys, can someone clarify on above questions?

**Comment by bgrant0607** [comment]
@vefimova Why do you want multiple handlers per type? What is the specific use case? Why won't a sidecar work?

I think the bigger issue with readiness probes is #14848

**Comment by vefimova** [comment]
@bgrant0607 I got the point with sidecar containers, I just want to get more clarification on questions in  https://github.com/kubernetes/kubernetes/issues/27723#issuecomment-227814633 comment regarding their usage.

**Comment by bgrant0607** [comment]
@vefimova Documenting the sidecar approach would be useful. I view it as a just a tip about how to use the system. @johndmulhausen and/or @pwittrock can guide you towards our new task-oriented doc templates.

Probes are specified and evaluated on a per-container basis. You could run a single sidecar with different API endpoints for querying about different containers and liveness vs. readiness, or use multiple sidecar containers, as is convenient for you. I'd recommend a distinct probe endpoint for the sidecar itself.

exec-healthz could be used as an example. We need to find a better home for it and write some tests.

**Comment by thockin** [comment]
> If this way of implementing elaborate health checks is a suggestion for now, is it planned to officially declare it in the nearest time and describe in documentation?

I'd love some better documentation on this, or even a good example of a multiplexing healthcheck.

> Is it restricted somehow/recommended to have sidecar container per worload container or there can be one sidecar container serving healthchecks of all others in the pod?

You can have as many sidecars as you want.  The "sidecar" designation isn't anything real - it's just human-centric nomenclature that indicates it is not part of the "main app".  You can have multiple sidecars running, each exposing a different port.

> Is it assumed to use basic health checks for sidecar container itself?

You can health-check the health-checker, though I don't see most people doing that.

> I suppose this must be used as a reference/example https://github.com/kubernetes/contrib/tree/master/exec-healthz?

That's a good example

**Comment by thockin** [comment]
We can keep the discussion going, but I don't think we're going to add multiple handlers right now.

**Comment by pwittrock** [comment]
@vefimova Would you be interested in adding a focussed "task" document for this.  See the [instructions here](http://kubernetes.io/docs/templatedemos/).
