### ISSUE TITLE
Kubelet displays MissingClusterDNS despite cluster-dns and cluster-domain options are given

### ISSUE THREAD

**Issue by metal3d** [kubernetes/kubernetes#27722]
I installed kubernetes 1.2.4 on 3 REHEL7 servers (no internet access).
I've got everything working great excepting the kubedns example given in documentation.

Configuration:
```
kubectl get svc kube-dns --namespace=kube-system
NAME       CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
kube-dns   172.16.99.99   <none>        53/UDP,53/TCP   15m

cat /opt/kubernetes/cfg/kubelet
...
# Add your own!
KUBELET_ARGS=" --cluster-dns=172.16.99.99 --cluster-domain=kubernetes.local "

ps ax | grep kubelet
 6077 ?        Ssl    0:07 /opt/kubernetes/bin/kubelet --logtostderr=true --v=0 --address=0.0.0.0 --port=10250 --hostname-override=k8s-minion-1.XXXXXX --api-servers=http://k8s-master.XXXXXX:8080 --allow-privileged=false  --cluster-dns=172.16.99.99 --cluster-domain=kubernetes.local

kubectl get pods  --namespace=kube-system
NAME                 READY     STATUS             RESTARTS   AGE
kube-dns-v11-f2f4a   3/4       CrashLoopBackOff   7          18m




kubectl describe rc  --namespace=kube-system
Name:		kube-dns-v11
Namespace:	kube-system
Image(s):	our.registry/gcr.io/google_containers/etcd-amd64:2.2.1,our.registry/gcr.io/google_containers/kube2sky:1.14,our.registry/gcr.io/google_containers/skydns:2015-10-13-8c72f8c,our.registry/gcr.io/google_containers/exechealthz:1.0
Selector:	k8s-app=kube-dns,version=v11
Labels:		k8s-app=kube-dns,kubernetes.io/cluster-service=true,version=v11
Replicas:	1 current / 1 desired
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Volumes:
  etcd-storage:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  19m		19m		1	{replication-controller }			Normal		SuccessfulCreate	Created pod: kube-dns-v11-f2f4a


#To be sure
kubectl get all --all-namespaces 
NAMESPACE     NAME                 DESIRED        CURRENT            AGE
kube-system   kube-dns-v11         1              1                  24m
NAMESPACE     NAME                 CLUSTER-IP     EXTERNAL-IP        PORT(S)         AGE
default       kubernetes           172.16.0.1     <none>             443/TCP         27m
kube-system   kube-dns             172.16.99.99   <none>             53/UDP,53/TCP   24m
NAMESPACE     NAME                 READY          STATUS             RESTARTS        AGE
default       busybox              1/1            Running            0               23m
kube-system   kube-dns-v11-f2f4a   3/4            CrashLoopBackOff   9               24m
```

I loaded the "busybox" example and see events:

```
20m		20m		2	{kubelet k8s-minion-1.XXXXXX}					Warning		MissingClusterDNS	kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
```

But if you look to the congfiguration file and the "ps ax" output I've given, dns and dns-domain are given to the kubelete options.

So why kubelet says : "MissingClusterDNS	kubelet does not have ClusterDNS IP configured" ?

The crashloopbackoff says that:
```
Warning	Unhealthy	Readiness probe failed: Get http://172.16.23.2:8081/readiness: dial tcp 172.16.23.2:8081: connection refused
...
Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kube2sky" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube2sky pod=kube-dns-v11-f2f4a_kube-system(27d70b7c-36f9-11e6-b4fe-fa163ee85c45)"

```

And... as you may understand, it's very complicated to work without kube-dns to make pods contacting each others :)

So please: help

**Comment by girishkalele** [comment]
Please re-post your question to [stackoverflow]
(http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support
are posted so that we can improve our efficiency in responding to your requests,
and to make it easier for you to find answers to frequently asked questions and
how to address common use cases.

We regularly see messages posted in multiple forums, with the full response
thread only in one place or, worse, spread across multiple forums. Also, the
large volume of support issues on github is making it difficult for us to use
issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to
ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to
similar questions, and also familiarize yourself with:

  * [user guide](http://kubernetes.io/docs/user-guide/)
  * [troubleshooting guide](http://kubernetes.io/docs/admin/cluster-troubleshooting/)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by metal3d** [comment]
My apologies. I will post on stackoverflow so.

Le mar. 21 juin 2016 00:23, Girish Kalele <notifications@github.com> a
écrit :

**Comment by metal3d** [comment]
@girishkalele I'm sorry but it seems that there is a bug anyway. Or enhancement about logs. Using `--cluster-dns=...` and `--cluster-domain=...` should not display errors from kubelete saying "kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy" because it's wrong. I did it :)

**Comment by metal3d** [comment]
https://github.com/kubernetes/kubernetes/blob/a8fecd0cc643db30720bc5b9cce6ef8bce090661/pkg/kubelet/kubelet.go#L1665 it's clear that kl.clusterDomain is false there despite the fact I set option

**Comment by girishkalele** [comment]
@metal3d 

I will reopen the issue as a bug, I haven't looked at it in detail yet.
Could you reword the title a little bit to summarize the issue ?

We also need to evaluate whether the same bug exists in master - the DNS pod is running different code in 1.3 as well as many other changes in other parts of the code.

**Comment by metal3d** [comment]
No problem, let me few minutes to change title and content. BTW I will get the code and put some logs to follow what happends.
Thanks a lot

**Comment by metal3d** [comment]
@girishkalele I found a strange issue.

I forked and add logs in cmd/kubectl/kubectl.go just after the line:

```go
utils.InitLogs()
log.Println("LOG >> ", s.ClusterDNS)
```

Then I launched my binary in minion... I sets this options:

    --cluster-dns='10.10.0.10' --custer-domain='cluster.local'

And I see this:

    logs.go:41] LOG dns options after init >>  '10.10.0.10' --cluster-domain='cluster.local'

I've got the same with or without simple quotes, or double quotes.

It seems that the options are badly parsed.

**Comment by metal3d** [comment]
and if I invert options, I have:

    logs.go:41] LOG dns options after init >>

**Comment by metal3d** [comment]
OK... @girishkalele you can definitively bit me, hate me and forget this issue.

Because I saw "10.10.0.10 --cluster-domain=..." I suspected that options were sent "in one string". 

So I tried to launch the command manually (copy paste from "ps" command) and... That worked.

I've understood after 2 minutes or reflection...

I was using the kubelet config file from "centos" subdirectory that gives a "KUBELET_ARGS" variable.

And I've written:

    KUBELET_ARGS="--cluster-dns= 10.10.0.10 --cluster-domain=cluster.local"

But... Because it's an environment file for systemd, variables works like Bash => one string is one argument.

By splitting arguments or removing double quotes:

    KUBELET_ARGS=--cluster-dns= 10.10.0.10 --cluster-domain=cluster.local

This works perfectly...

Maybe one remark: kubelet should print a "bad dns form" error or something like that to help.  

All my apologies. I can close the issue.
