### ISSUE TITLE
NoDiskConflict failure with RBD read-only volumes

### ISSUE THREAD

**Issue by erikgrinaker** [kubernetes/kubernetes#27725]
Only a single pod per node is able to use the same Ceph RBD image in read-only mode. Further pods fail to be scheduled with `NoDiskConflict`.

I would expect multiple pods per node to be able to use the same RBD image in read-only mode, for example by mapping the image once per node and bind-mounting it into each pod. Is there any reason why this isn't possible?

**Comment by girishkalele** [comment]
@erikgrinaker

Will wait for confirmation whether this is as per-design or a bug from a storage area engineer.
If this is a bug, need a pointer to the log snippets for further debugging.

cc @saad-ali

**Comment by saad-ali** [comment]
According to [this](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L107), Ceph RBD forbids any two pods from sharing the same monitor, and match pool and image.

@rootfs for details

CC @kubernetes/sig-storage

**Comment by rootfs** [comment]
@erikgrinaker yes, it is a valid use case. let me run some tests first.

**Comment by childsb** [comment]
This is an issue with the PV logic but works in volumes as mentioned here: #24738

**Comment by rootfs** [comment]
@erikgrinaker opened a fix.

**Comment by erikgrinaker** [comment]
Great, thanks @rootfs!
