### ISSUE TITLE
Log version/build info as the first line of every glog log from every binary

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#27744]
This makes it so much easier to tell _what_ you are debugging.
#27735 is a not great version--the stringification elides some useful info--but it's a start.

**Comment by mml** [comment]
And also flag values.

**Comment by mml** [comment]
#28374 is the same thing but adds flags.

**Comment by mml** [comment]
#46047 will handle flags for everything that uses `k8s.io/apiserver/pkg/util/flag`.

**Comment by nikhita** [comment]
/remove-lifecycle rotten

Adding a good first issue label on this because the idea is clear. If anyone wants to work on this,

- please see https://github.com/kubernetes/kubernetes/pull/27735 and https://github.com/kubernetes/kubernetes/pull/46047 as examples on how to add the version info.
- go through all binaries and check if these exist. If they don't, add these in the glog lines.


/good-first-issue

**Comment by sahitpj** [comment]
Hey @nikhita could I take this one?

**Comment by nikhita** [comment]
> Hey @nikhita may I take this one?

@sahitpj We would love to get this fixed but would prefer if you choose one good-first-issue out of this and https://github.com/kubernetes/kubernetes/issues/68578 first. Feel free to send a PR for one issue and if the other issue hasn't been claimed yet, feel free to send a PR for that one as well. :)

**Comment by rosti** [comment]
@sahitpj @tanshanshan please, sync up together, since your PRs are overlapping from kubeadm's perspective :)

**Comment by tanshanshan** [comment]
@rosti  , I remove kubeadm's perspective , thanks.

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/pull/68667#issuecomment-435640069

**Comment by cheftako** [comment]
+1

**Comment by cewood** [comment]
@mml @anubhabMajumdar I believe this issue can be closed now, from what I could see all the intended binaries now include version logging.

**Comment by mml** [comment]
@cewood thanks!  Were there some other CLs for binaries besides kubemark?

**Comment by cewood** [comment]
Sry was away for a long weekend.

> @cewood thanks! Were there some other CLs for binaries besides kubemark?

@mml I count/see the following:

1. [federation/cmd/federation-controller-manager](https://github.com/kubernetes/kubernetes/pull/27735/files)
1. [cmd/kube-dns](https://github.com/kubernetes/kubernetes/pull/28374/files)
1. [cmd/kube-apiserver, cmd/kube-controller-manager](https://github.com/kubernetes/kubernetes/pull/46047/files)
1. [cmd/cloud-controller-manager](https://github.com/kubernetes/kubernetes/pull/68664/files)
1. [cmd/kube-scheduler](https://github.com/kubernetes/kubernetes/pull/73109/files)
1. [cmd/kubemark](https://github.com/kubernetes/kubernetes/pull/82629/files)
1. [cmd/kube-proxy, cmd/kubelet](https://github.com/kubernetes/kubernetes/commit/af09159419d5d9fbdc2543e31d38817a659daa27)

Which I think covers everything that makes sense; notable exclusions being hyperkube, kubeadm, kubectl, and a few of the other misc things under /cmd

**Comment by gkarthiks** [comment]
Seems the list is complete. Should this issue be closed rather still open?
