### ISSUE TITLE
rkt: Support restart back-off for containers

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#27745]
Today, the restart strategy is exponential back-off(https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/pod-states.md#restartpolicy). There are discussions on other back-off strategies as well (https://github.com/kubernetes/kubernetes/issues/17801) , but none of them is implemented in rktnetes yet as we are not able to do per container restart yet.

cc @kubernetes/sig-rktnetes @kubernetes/sig-node

**Comment by yifan-gu** [comment]
I think this will be addressed once we switched to CRI

**Comment by yujuhong** [comment]
> I think this will be addressed once we switched to CRI

Yes, this can wait.

**Comment by yujuhong** [comment]
Closing this since relevant issues should be handled in CRI or moved to the rktlet repository.
