### ISSUE TITLE
rkt: cni plugin is not supported

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#27751]
We have been solving the support for kubenet, but however there's a little left for cni plugin support: The cniNetworkPlugin bails out if the runtime [is not docker](https://github.com/kubernetes/kubernetes/blob/v1.3.0-beta.1/pkg/kubelet/network/cni/cni.go#L141), ehh..

Fortunately we can easily remove most of these lines except the one in the `GetPodNetworkStatus()` as it requires the runtime to implement `GetContainerIP()`.

However, we should be able to get the IP of the pod by nsenter with the netns path today. So we should be able to remove the `dockertools.GetContainerIP()` and use some common code to retrieve IP for both runtimes like we did in [kubenet](https://github.com/kubernetes/kubernetes/blob/v1.3.0-beta.1/pkg/kubelet/network/kubenet/kubenet_linux.go#L440-L459).

Will work out a PR ASAP.

@kubernetes/sig-rktnetes @kubernetes/sig-network @dcbw

**Comment by dchen1107** [comment]
Ok, #27878 was merged. Can we close this?

**Comment by yifan-gu** [comment]
@dchen1107 Hmm but the kubenet's host port is not working yet. I am debugging this.

**Comment by yifan-gu** [comment]
https://github.com/kubernetes/kubernetes/issues/27751#issuecomment-227903649 is actually another issue, so closing this one.
