### ISSUE TITLE
Ceph RBD 'failed fork/exec /usr/bin/rbd: invalid argument' when creating the pod 

### ISSUE THREAD

**Issue by hanpenghero** [kubernetes/kubernetes#27758]
I installed latest kubernetes version 1.2.1 on 4 nodes separately . And after installation I run the command kubectl get nodes , I can see all nodes stay on the ready status . Also I may create tomcat RC successfully . After that I install CEPH with version 0.94 on another grouped machines .
[root@master-kub ~]# ceph -s
    cluster 5bab69d4-a34b-439c-876f-b63e4f6cde29
     health HEALTH_OK
     monmap e1: 1 mons at {ceph-mon0=9.111.102.165:6789/0}
            election epoch 2, quorum 0 ceph-mon0
     mdsmap e5: 1/1/1 up {0=ceph-mds0=up:active}
     osdmap e27: 3 osds: 2 up, 2 in
      pgmap v30991: 184 pgs, 4 pools, 248 MB data, 115 objects
            17660 MB used, 398 GB / 415 GB avail
                 184 active+clean
 
But when I use the examples rbd-with-secret.json

{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "name": "rbd4"
    },
    "spec": {
        "nodeName": "kub-node5",
        "containers": [
            {
                "name": "rbd-rw",
                "image": "kubernetes/pause",
                "volumeMounts": [
                    {
                        "mountPath": "/mnt",
                        "name": "rbd"
                    }
                ]
            }
        ],
        "volumes": [
            {
                "name": "rbd",
                "rbd": {
                    "monitors": [
                                                        "9.111.102.165:6789"
                                 ],
                    "pool": "rbd",
                    "image": "foo1",
                    "user": "admin",
                    "keyring": "/etc/ceph/ceph.client.admin.keyring",
                    "secretRef": {
                                                  "name": "ceph-secret"
                                         },
                    "fsType": "ext4",
                    "readOnly": true
                }
            }
        ]
    }
}

after run kubectl create -f rbd-with-secret.json , I got the following error from kubectl describe pod rbd4 
root@master-kub mysql]# kubectl get pods
NAME            READY     STATUS              RESTARTS   AGE
rbd4            0/1       ContainerCreating   0          13h
tomcat8-houkf   1/1       Running             0          7d
tomcat8-iixd7   1/1       Running             0          11d

Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  13h		10s		3592	{kubelet kub-node5}					FailedMount	Unable to mount volumes for pod "rbd4_default(dc732f9e-374f-11e6-b127-525465305302)": rbd: map failed fork/exec /usr/bin/rbd: invalid argument 
  13h		10s		3592	{kubelet kub-node5}					FailedSync	Error syncing pod, skipping: rbd: map failed fork/exec /usr/bin/rbd: invalid argument 

BTW , I followed the instruction of the example readme , installed ceph-common and ceph and configured the connection with mon node with authentication key . Also I create the secret on kubernets as well .  

Anyone has any idea to help me out . thanks

**Comment by boweeb** [comment]
I was getting "rbd: map failed fork/exec /usr/bin/rbd: invalid argument" as well.  I fixed it by encoding the ceph secret with base64.

So on a ceph-mon:
> sudo ceph auth get-key client.admin | base64
and put that value in your ceph-secret.

Does that help?

**Comment by hanpenghero** [comment]
@boweeb thank you so so so much . the error message confused me so that I never thought that was the key error . it now works well . thanks again .

**Comment by akantak** [comment]
I think it should be mentioned [here](https://github.com/kubernetes/kubernetes/tree/master/examples/experimental/persistent-volume-provisioning) because I encountered this issue too when I was trying to use Ceph RBD StorageClass.

**Comment by boweeb** [comment]
Man, that was a while ago.  I can't take personal credit.  Normally I like to cite my sources but I think I couldn't find it again at the time I posted.  It was casually mentioned on a blog somewhere.

Is it still not mentioned anywhere in the docs?  I agree @akantak -- this seems like a vital piece of information.

**Comment by akantak** [comment]
It is standard in creating secrets for k8s:
http://kubernetes.io/docs/user-guide/secrets/#creating-a-secret-manually
but mention about it there can save time to newbies.

**Comment by elsonrodriguez** [comment]
I have a pending PR to make this more clear: https://github.com/kubernetes/kubernetes/pull/34042/files

Will also send another PR for the new `--type=kubernetes.io/rbd` requirement.
