### ISSUE TITLE
Error at startup "PersistentVolumeController can't initialize caches ..."

### ISSUE THREAD

**Issue by asalkeld** [kubernetes/kubernetes#27757]
When we startup there is the following error:
```
E0621 11:07:01.331816     425 controller_base.go:142] PersistentVolumeController can't initialize caches, expected list of volumes, got: &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1/persistentvolumes ResourceVersion:11} Items:[]}
```
I don't think an empty list should result in a startup error.

Also, the function returns at that point instead of checking the claim list
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/persistentvolume/controller_base.go#L145

**Comment by jingxu97** [comment]
After testing, a simple fix like the following will pass the unit test. 

volumeList, ok := volumeListObj.(*api.PersistentVolumeList)

I will test with e2e like Jan suggested. Please let me know if you have any concern about the fix. Thanks!

Jing
