### ISSUE TITLE
different pod status handling in kubectl describe and get

### ISSUE THREAD

**Issue by AdoHe** [kubernetes/kubernetes#27752]
FYI. When I use `kubectl get` to get pod info, I get the pod status `CrashLoopBackOff`, but if I use `kubectl describe`, the pod status is `Running`. I am not clear this is intented or not, I would expect the output the same. Besides we are using kubernetes 1.2 @kubernetes/kubectl @bgrant0607

**Comment by bgrant0607** [comment]
@AdoHe 

Please see #25160
