### ISSUE TITLE
influxdb-grafana-controller dies over time

### ISSUE THREAD

**Issue by tbrox** [kubernetes/kubernetes#27761]
Not sure whether this is incorrect use, a bug or just missing functionality.

I'm running a kube-upped Kubernetes 1.2.3 cluster on AWS, on two m4.large nodes, and I'm using the auto-installed influx-grafana pod for cluster monitoring.

After a week or so, the influx-container appears to be OOM-killed, and will time out trying to restart.
`4434 manager.go:2050] Back-off 5m0s restarting failed container=influxdb`

The only way I've found to deal with this problem so far is to kill the entire pod. This will make Kubernetes recreate it from scratch, which also means losing all existing monitoring-data.

**Comment by girishkalele** [comment]
@tbrox 

It looks like there is already an issue tracking this OOM condition. Please see https://github.com/kubernetes/kubernetes/issues/27630

**Comment by tbrox** [comment]
Looks like you're right, I'll add my comments there and close this one
