### ISSUE TITLE
How to get logs of terminated jobs?

### ISSUE THREAD

**Issue by stefanodoni** [kubernetes/kubernetes#27768]
Hi,

I've created a simple Job that echo a value when it exists.

However, I'm unable to get the logs of the pod/job after it has completed its processing.

$ kubectl get jobs
NAME      DESIRED   SUCCESSFUL   AGE
sleeper   1         1            8m

$ kubectl get pods -a  | grep sleeper
sleeper-psc5l                0/1       Completed   0          7m

$ kubectl logs sleeper
Error from server: pods "sleeper" not found
$ kubectl logs -p sleeper
Error from server: pods "sleeper" not found

How can I retrieve the job logs after its exit?

The k8s doc about Jobs states that this should be possible (http://kubernetes.io/docs/user-guide/jobs/#job-termination-and-cleanup):

_When a Job completes, no more Pods are created, but the Pods are not deleted either. Since they are terminated, they don’t show up with kubectl get pods, but they will show up with kubectl get pods -a. Keeping them around allows you to still **view the logs of completed pods**_

**Comment by stefanodoni** [comment]
Solved:

$ kubectl logs sleeper-psc5l
1

Thanks!

**Comment by PavelPrischepa** [comment]
I'm failed to get logs of a completed job, because of error:

```
$kubectl logs pi-zhdc6
no such container: "8989d08431716d01b0d186a62033d0361fad5c5f3c75a73424720d3ed334360b"
```

**Comment by PavelPrischepa** [comment]
I specified `--minimum-container-ttl-duration=10m` in kubelet config, so pod and container available during 10 minutes after job will be finished.

**Comment by everett-toews** [comment]
Good advice here on the topic

https://kubernetes.io/docs/concepts/jobs/run-to-completion-finite-workloads/#job-termination-and-cleanup

**Comment by davidwhthomas** [comment]
One other approach:

1. kubectl describe job $JOB
2. Pod name is shown under "Events"
3. kubectl logs $POD

**Comment by andersjanmyr** [comment]
It's also possible to use the name of the hook with log. 
```
$ kubectl logs --help
...
 # Return snapshot logs from first container of a job named hello
  kubectl logs job/hello
...
```

Example:
```
$ kubectl -n wce-system logs job/dingo-ns-create-concord-ns-tokens
Found 2 pods, using pod/dingo-ns-create-concord-ns-tokens-x86kd
Invalid password: Passwords may NOT contain three (3) consecutive characters from your user account name
```

**Comment by manishbansal8843** [comment]
`kubectl logs job/job_name` does not work for me. Although, my jobs are listed by `kubectl get jobs`. However, the pods created by those jobs are gone. Further, there is no pod name inside events section of job description. Is there any way to keep pod alive until job is not deleted? As mentioned [here](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/), we can keep the job (only) till `ttlSecondsAfterFinished`. However, what is its use if the pods which are created by jobs gets deleted from the cluster?

**Comment by alculquicondor** [comment]
Pods might be deleted by the garbage collection to keep the efficiency of the apiserver. If you really need to keep them, you can use finalizers https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers

**Comment by rhigdon** [comment]
I feel the `Note` in this section was very helpful to me:

https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy

So when debugging my job I just set the restart policy to never.  The problem I was facing that I was getting an error, and the pod would be terminated due to the back off limit.  If you remove this for debugging purposes then your pod should stick around.

**Comment by palaueb** [comment]
Maybe this helps
`kubectl logs -f $(kubectl describe job <job-name> | grep SuccessfulCreate | tail -n1 | awk '{print $7}')`
