### ISSUE TITLE
node e2e flake: mirror pod failure

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#27779]
```
Summarizing 6 Failures:

[Fail] [k8s.io] MirrorPod when create a mirror pod  [BeforeEach] should be updated when static pod updated 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:52

[Fail] [k8s.io] MirrorPod when create a mirror pod  [BeforeEach] should be recreated when mirror pod gracefully deleted 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:52

[Fail] [k8s.io] MirrorPod when create a mirror pod  [BeforeEach] should be recreated when mirror pod forcibly deleted 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:52

[Fail] [k8s.io] Kubelet when scheduling a busybox command in a pod [It] it should print the output to logs 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/kubelet_test.go:67

[Fail] [k8s.io] Kubelet when scheduling a read only busybox container [It] it should not write to root filesystem 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/kubelet_test.go:120

[Fail] [k8s.io] Kubelet metrics api when querying /stats/summary [It] it should report resource usage through the stats api 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/kubelet_test.go:212

Ran 20 of 23 Specs in 1126.176 seconds
FAIL! -- 14 Passed | 6 Failed | 0 Pending | 3 Skipped --- FAIL: TestE2eNode (1126.18s)
FAIL
```

[log](https://00e9e64bacdc940d452af5b52517f6a059b53fa08ab2cef716-apidata.googleusercontent.com/download/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F27733%2Fnode-pull-build-e2e-test%2F11383%2Fbuild-log.txt?qk=AD5uMEtOQ26CkCH7yz8cdHhzCc-vRBJR73QNAGM2WU4bqA6i7JurfHNJuYydhvlekik4rUmCkUehUmyoIGkGGLmTJLudT9lbkT-rQOWaBNuee0duzwQYA0EMXea0r_6Yu8nG2B4HdSggjP6L_ZBGfQEaqFu9JuQUFqzZ1o95-PHc-ZS9mFgTElQPxXEMGc1Ca9EU2s5AjxXaUUMXvXs5P8pKmLBf4hCwjs9AKVhMKYXfSUdQJT4AQxhUpatrW7m4YmE9bRKr3ON1dobazaUWC8Cb3t3ZNyC8p_PzyJDuQF0wclYjkopixlVLq-mijlCijPrSizpeYs14BrrTSrze1p8boF6klCG_97p-FZMNhMANNbxuqIeEyYbFcndGa1NkTO3aXiB7k9KT1ycW3FLy9_YXao93ZFkCsnRXOS5BJdVEPAlmMbGTf8qaVd-SjFR_4BbypoZGRbnqrjenFF1eBbFJl5JyIa3QPUXEuMlMovzM_NCOr1_9yeGXqM39aiP90mj4YYy7AwLNdKnsBOhasowwscY4i58cZItZZgVP0dFHev5SDn-wh8cRnx-sTw0yA8wz0oF735PjN8oxrUWkJGTYw3l_bYiM7xAHrdfHR6H1AYpl99vH_WK1yCiPzKj7_Uye1eueVBZzl81ToPUz4uGBxB274JBXa2liFbIrzsh1vTzSx8HgHOWTMZ_m7GaN4rQFJXoUUVp9zV5jvGRzDa7iAn08K5QA0uaKU3-e-sghfxtcKtkAyKoFIhmpZbvVNRoqlu6hQphFYJSW6Inuch5gYDUuRPifL4wCI6DGWfflnD1cv0ul9t39Crb9btm2z4JpsqhjV-jh8Q9out5KGi_PGUxwoMu0tw)

**Comment by dchen1107** [comment]
@yujuhong Can you take a look at this? Thanks!

**Comment by Random-Liu** [comment]
@caesarxuchao The log link is dead. :(

**Comment by caesarxuchao** [comment]
Copy-pasted in pastebin: http://pastebin.com/VpaEhj9m

**Comment by Random-Liu** [comment]
@dchen1107 @yujuhong This is still a group of failure on coreos image. There is no docker or kernel log now, I guess it's https://github.com/kubernetes/kubernetes/issues/27498, but no evidence yet.

**Comment by yujuhong** [comment]
Since we don't have other logs to triage the failure, let's close this issue. @Random-Liu, hanks for taking a look~

**Comment by Random-Liu** [comment]
@yujuhong I found the kernel log, and found
```
Jun 21 04:50:24 localhost kernel: unregister_netdevice: waiting for lo to become free. Usage count = 2
Jun 21 04:50:24 localhost kernel: unregister_netdevice: waiting for vethb6dd68f to become free. Usage count = 1
```
Proved my guess. :)

**Comment by nikhiljindal** [comment]
Some of these MirrorPod failures happened again: [logs](https://00e9e64baca16e33340ac7a96a2da35c59e2a9c44a32aa616a-apidata.googleusercontent.com/download/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F28043%2Fnode-pull-build-e2e-test%2F11968%2Fbuild-log.txt?qk=AD5uMEv-mgmXUse4wIxVv9WIKK60BMo0zNxJH579s4t-iMoa5zQS_YxpD8w6-Bcllbcc9_c2ZoeGvUt_hF38pMxroVIBMGDHgQRskUowGYHho7kbzwYpa3FF2cneJmpwiw_KKS1T63mYj0Paf4DdkTSvr7wAj3CnSQnlaMexT-dhhsdwDw0R_wCbpGRrAP0XT1-Ap3FtHzGjEupEXwtFkYp7qGxEYR5XnlpNGtX9oRntodQPZitWhxq_Thl-8AaXwtw3qtbDubx33BrtCpU3fzrFeOXQ0fh2ij7Ty7pn0_EXt64_GKrwt2ZwHUIRlCGNe7vlxwEckp7wf5vv7QF9E2hIl8NN7ZeDPQUMaNL0NBhyoouRN3P4K7yNFScrNdvdGzyMjmcYcacoM7XpkvnqVIsxWghHSzmBx5HtVP2nfADRCsxDkttPQMcUaqm1QXyTStXJAoINf33-z-i-9J8-c3EG8kwKlcSQIbotI3UZp--BbLrqV1ZW4fgT9aQwtaNAFrrHpX_gyYa7Ns1LIaRm5ae1nSQ2KSXljTMdgOjbSECu_f19-QbRIR-Kztbk-rF_WAngFPF3412f59wHHEvc0J5RINpMEwBzmjiDYKISRcTDpIIZUVGqeKOXDW0pdt4BHKIwlZ_AQPgCclDwmm7iOpStVekoCSIYMj_s8b960t3maqK2FbcY5kHD6CPL9RMP_TO-icfwKdZmUatEOe7RotqR7B5FyldDQ0dzX-MZqov-JTbHge4VVh_hxtoIRRebmyXgsxf8Li0BJbwISweQu3rQD-i-y9MFcpbHmpbEN7XkwThO-4YFMorDHW0fdxdmgaD5ScHmetnE3QipkRRdZ4e4fWuQIrw5fg)

**Comment by yujuhong** [comment]
> Some of these MirrorPod failures happened again: logs

There are multiple test failures (incl. but not limited to the mirror pod tests) and all on the coreos image. This seems similar to #27498
