### ISSUE TITLE
Panic detaching volume on AWS

### ISSUE THREAD

**Issue by sp-joseluis-ledesma** [kubernetes/kubernetes#27774]
Hi,

I was emulating some minions failures (in this case a made the minion unreachable by bringing down the network). This minion had a pod with a volume attached, and it seems the controller-manager is unable to detach de volume after the failure:

`I0621 13:35:48.956705       5 reconciler.go:103] Started DetachVolume for volume "kubernetes.io/aws-ebs/vol-546074f1" to node "ip-172-20-0-188.ec2.internal" due to maxWaitForUnmountDuration expiry.
E0621 13:35:49.038081       5 runtime.go:58] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:52
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:40
/usr/local/go/src/runtime/asm_amd64.s:472
/usr/local/go/src/runtime/panic.go:443
/usr/local/go/src/runtime/panic.go:62
/usr/local/go/src/runtime/sigpanic_unix.go:24
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go:993
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go:1491
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/aws_ebs/attacher.go:192
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/attacherdetacher/attacher_detacher.go:176
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/goroutinemap/goroutinemap.go:73
/usr/local/go/src/runtime/asm_amd64.s:1998
`
Kubernetes version: 1.3.0-beta.1

If you need any other information do not hesitate to ask me :)

**Comment by girishkalele** [comment]
@justinsb cc@tpounds PTAL

Around ```pkg/cloudprovider/providers/aws/aws.go:993```

**Comment by justinsb** [comment]
I added a missing error check which was causing the panic: #27793

I am not sure this is a complete fix, in that I don't think we will detach the volume, but it should at least fix the panic.

**Comment by goltermann** [comment]
Panic fix is in, do we need to fix the detach volume logic for v1.3?

**Comment by sp-joseluis-ledesma** [comment]
IMHO kubernetes should be able to detach a volume in case of minion failure without manual intervention. 

I was trying to check what would happen in a 1.3.0-beta.2 kubernetes cluster but found a new issue (this time attaching the volume) #27875
