### ISSUE TITLE
Proposal: Log "reason" when executing kubectl exec

### ISSUE THREAD

**Issue by Raffo** [kubernetes/kubernetes#27777]
We are currently trying to use Kubernetes (GKE) and kubectl in our company in a setup where we have to pass audits from external auditors. For this reason one of our requirements is to log the reason why a user wants to get access to a container which in Kubernetes terms means executing `kubectl exec -it POD_NAME /bin/sh`. What we would love to have is Kubectl asking for the reason (prompting the user to enter it) or having a parameter that will then be transfered to the API server. We would love to discuss this feature and get an understanding of what would be desirable for the community.

**Comment by AdoHe** [comment]
@kubernetes/kubectl
