### ISSUE TITLE
Improve "constraint violation" error message

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#2778]
The constraint.Allowed function should return an error or list of errors that explain *which* constraint would be violated. Then we can give much more helpful error messages here:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/etcd/etcd.go#L214

**Comment by bgrant0607** [comment]
Should have been closed by #4132 cc @jszczepkowski
